### ISSUE TITLE
`x64-mingw-dynamic` triplet cannot find WindowsSDKVersion/WindowsSdkDir in environment

### ISSUE THREAD

**Issue by tntxtnt** [microsoft/vcpkg#25076]
**Problem**
I was trying to build `uwebsockets` for `x64-mingw-dynamic` triplet, since MSYS2 doesn't have `uwebsockets` library. I couldn't build it because `usockets` (which `uwebsockets` uses) needs to link with `ws2_32`. So I need to install `usockets` with `network` feature which will link `usockets` to `ws2_32`. This `network` feature requires `winsock2` library, which calls `vcpkg_get_windows_sdk` that needs `$ENV{WindowsSDKVersion}`, and `winsock2` ifself also needs `$ENV{WindowsSdkDir}` but vcpkg can't find any of `WindowsSDKVersion` or `WindowsSdkDir`. I did call `vcvars64.bat` to populate environment variables and check that my env has `WindowsSDKVersion` and `WindowsSdkDir`, but vcpkg cannot find them.

**Proposed solution**
Add `WindowsSDKVersion` and `WindowsSdkDir` to `VCPKG_ENV_PASSTHROUGH` in `x64-mingw-dynamic` triplet, and maybe to all of mingw triplets.
```cmake
set(VCPKG_ENV_PASSTHROUGH PATH WindowsSDKVersion WindowsSdkDir)
```

**Additional questions**
Can mingw triplets passthrough all environment variables? My proposed  solution looks like a quick fix than a permanent solution. ~~Also I have to call `vcvars...` beforehand to populate all those env vars, while `x64-windows` triplet gets them without calling `vcvars...`. Can mingw triplets do that?~~ Edit: I don't have to call vcvars.

**Comment by dg0yt** [comment]
`ws2_32` linking also works on mingw, and mingw must work without `WindowsSDKVersion` `WindowsSdkDir`. You should share the original error logs.

**Comment by tntxtnt** [comment]
Error logs when I called `vcpkg install usockets[network]:x64-mingw-dynamic`
```
Computing installation plan...
The following packages will be built and installed:
    usockets[core,network]:x64-mingw-dynamic -> 0.8.1
  * winsock2[core]:x64-mingw-dynamic -> 0.0#4
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-mingw-dynamic...
Restored 0 packages from D:\vcpkg\archives in 974.3 us. Use --debug to see more details.
Starting package 1/2: winsock2:x64-mingw-dynamic
Building package winsock2[core]:x64-mingw-dynamic...
-- Using community triplet x64-mingw-dynamic. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\Users\tri\vcpkg\triplets\community\x64-mingw-dynamic.cmake
CMake Error at ports/winsock2/portfile.cmake:10 (message):
  Portfile not yet configured for Windows SDK with version:
Call Stack (most recent call first):
  scripts/ports.cmake:146 (include)


error: building winsock2:x64-mingw-dynamic failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+winsock2
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[winsock2]+Build+error
including:
  package: winsock2[core]:x64-mingw-dynamic -> 0.0#4
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: faed44dfa 2022-06-03 (34 hours ago)

Additionally, attach any relevant sections from the log files above.
```

**Comment by dg0yt** [comment]
Okay...
- `winsocks2` seems rather pointless to be, from a mingw POV. No idea what it means for MSVC.
  I turned it into an empty port by prepending this to the `portfile.cmake`:
  ~~~cmake
  if(VCPKG_TARGET_IS_MINGW)
      set(VCPKG_POLICY_EMPTY_PACKAGE enabled)
      return()
  endif()
  ~~~
- `usockets[network]` wants `Ws2_32`, but in my case-sensitive mingw installation, the actual spelling is `ws2_32`.
  This can be fixed in the port's custom  `CMakeLists.txt`.

And this is all.

**Comment by tntxtnt** [comment]
@dg0yt But still `vcpkg_get_windows_sdk` cannot find WinSDK version for mingw triplet, is that ok?

**Comment by dg0yt** [comment]
> @dg0yt But still `vcpkg_get_windows_sdk` cannot find WinSDK version for mingw triplet, is that ok?

I don't see where mingw would need an external WinSDK here. With the proposed winsocks change above (prepended!), it will not enter the portfile code which seems to be written for MSVC. (But I can't really say much about WinSDK.)

**Comment by tntxtnt** [comment]
Can you make a PR and close this issue?

**Comment by dg0yt** [comment]
https://github.com/microsoft/vcpkg/pull/25079

**Comment by tntxtnt** [comment]
> Thanks for dg0yt's help! @tntxtnt Did dg0yt's change fix the issue you were having?

Yessir.  You can merge the PR and close this issue now.

**Comment by Cheney-W** [comment]
Thanks for your reply!
