### ISSUE TITLE
[New Port Request] NGINX libunit

### ISSUE THREAD

**Issue by lolgab** [microsoft/vcpkg#25070]
Library name:
libunit

Library description:
NGINX Unit is a polyglot app server, a reverse proxy, and a static file server, available for [Unix-like systems](https://unit.nginx.org/installation/#source-prereqs). It was built by [nginx](https://nginx.org/en/) team members from scratch to be highly efficient and fully configurable at runtime.

`libunit` is the library used to build integrations with NGINX Unit.

Example external integration: https://github.com/lolgab/snunit

Source repository URL:
https://github.com/nginx/unit

Project homepage (if different from the source repository):
https://unit.nginx.org

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
