### ISSUE TITLE
[miracl] miracl / MIRACL static library

### ISSUE THREAD

**Issue by kexuedaishu** [microsoft/vcpkg#25085]
Library name: Miracl

Library description: Multiprecision Integer and Rational Arithmetic Cryptographic Library

Source repository URL: https://github.com/miracl/MIRACL

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
Seems that miracl is not available, having one will be great!

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
