### ISSUE TITLE
[New Port Request] <lepton>

### ISSUE THREAD

**Issue by Zunnki0** [microsoft/vcpkg#25082]
Library name: lepton

Library description: A small C++ library for parsing, evaluating, differentiating, and analyzing mathematical expressions.

Source repository URL: https://github.com/rdinizcal/lepton

Project homepage (if different from the source repository):  https://simtk.org/projects/lepton

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
