### ISSUE TITLE
[dbus] install dubs on the ci.

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#25094]
Please install dbus on the ci.
I am aware of PR that want to add port dbus:
https://github.com/microsoft/vcpkg/pull/22642
It open from January and not going to be merge to the master anytime soon.

dbus now holding for at-spi2-atk that hold gtk3 ports.
https://github.com/microsoft/vcpkg/pull/24934
https://github.com/microsoft/vcpkg/pull/22201

Meanwhile we waiting for dubs port, can you install dbus on the ci, that we can continue the work on these PRs. Thank you.

**Comment by talregev** [comment]
It not my first issue around here ... But thanks!

**Comment by dg0yt** [comment]
@Cheney-W This is not a request for a *new-port*  but for changes to CI. Which is not a *good-first-issue*.

**Comment by Cheney-W** [comment]
Thanks for your reply! I have removed the `good-first-issue` lable.

According to the contents of the PR: https://github.com/microsoft/vcpkg/pull/22642, it is indeed adding new ports, so I think the `new-port` label is suitable for this issue.

Which label do you think is more suitable for this issue?

**Comment by talregev** [comment]
This issue don't talk about the new port, it talking about update the ci. please remove new port and add depends:vm-image tag

**Comment by JackBoosY** [comment]
cc @BillyONeal
