### ISSUE TITLE
[gmp] Build error

### ISSUE THREAD

**Issue by painer15999** [microsoft/vcpkg#25098]
**Failure logs**

Detecting compiler hash for triplet arm64-linux...
The following packages will be built and installed:
  * fmt[core]:arm64-linux -> 8.1.1#1
    gmp[core]:arm64-linux -> 6.2.1#9
    jsoncpp[core]:arm64-linux -> 1.9.5
    libmariadb[core,mariadbclient,openssl,ssl]:arm64-linux -> 3.1.15
  * libzip[bzip2,core,default-aes,openssl]:arm64-linux -> 1.8.0
    libzippp[core]:arm64-linux -> 5.1-1.8.0
    luajit[core]:arm64-linux -> 2.0.5#8
    protobuf[core]:arm64-linux -> 3.19.4
    pugixml[core]:arm64-linux -> 1.12.1
    spdlog[core]:arm64-linux -> 1.10.0#1
Additional packages (*) will be modified to complete this operation.
Restored 1 packages from /root/.cache/vcpkg/archives in 1.692 s. Use --debug to see more details.
Installing 1/10 gmp:arm64-linux...
Building gmp[core]:arm64-linux...
-- Using community triplet arm64-linux. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /home/ubuntu/vcpkg/triplets/community/arm64-linux.cmake
-- Using cached gmp-6.2.1.tar.xz.
-- Cleaning sources at /home/ubuntu/vcpkg/buildtrees/gmp/src/gmp-6.2.1-f412680bba.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/ubuntu/vcpkg/downloads/gmp-6.2.1.tar.xz
-- Applying patch tools.patch
-- Using source at /home/ubuntu/vcpkg/buildtrees/gmp/src/gmp-6.2.1-f412680bba.clean
-- Getting CMake variables for arm64-linux-dbg
-- Getting CMake variables for arm64-linux-rel
-- Generating configure for arm64-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: /usr/bin/autoreconf -vfi
    Working Directory: /home/ubuntu/vcpkg/buildtrees/gmp/src/gmp-6.2.1-f412680bba.clean/
    Error code: 1
    See logs for more information:
      /home/ubuntu/vcpkg/buildtrees/gmp/autoconf-arm64-linux-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:617 (vcpkg_execute_required_process)
  ports/gmp/portfile.cmake:46 (vcpkg_configure_make)
  scripts/ports.cmake:146 (include)

error: building gmp:arm64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+gmp
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[gmp]+Build+error
Include '[gmp] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2999-12-31-unknownhash
    vcpkg-scripts version: 7ff57dfe9 2022-06-06 (29 minutes ago)

**Failure logs**

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: /usr/bin/autoreconf -vfi
    Working Directory: /home/ubuntu/vcpkg/buildtrees/gmp/src/gmp-6.2.1-f412680bba.clean/
    Error code: 1
    See logs for more information:
      /home/ubuntu/vcpkg/buildtrees/gmp/autoconf-arm64-linux-err.log

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
configure.ac:3791: warning: AC_LIBTOOL_PROG_COMPILER_PIC is m4_require'd but not m4_defun'd
acinclude.m4:2363: GMP_ASM_X86_GOT_UNDERSCORE is expanded from...
configure.ac:3791: the top level
configure.ac:3794: warning: AC_ENABLE_SHARED is m4_require'd but not m4_defun'd
acinclude.m4:2717: GMP_ASM_X86_MCOUNT is expanded from...
configure.ac:3794: the top level
configure.ac:3794: warning: AC_PROG_LIBTOOL is m4_require'd but not m4_defun'd
acinclude.m4:2717: GMP_ASM_X86_MCOUNT is expanded from...
configure.ac:3794: the top level
autoreconf: configure.ac: tracing
configure.ac:3791: warning: AC_LIBTOOL_PROG_COMPILER_PIC is m4_require'd but not m4_defun'd
acinclude.m4:2363: GMP_ASM_X86_GOT_UNDERSCORE is expanded from...
configure.ac:3791: the top level
configure.ac:3794: warning: AC_ENABLE_SHARED is m4_require'd but not m4_defun'd
acinclude.m4:2717: GMP_ASM_X86_MCOUNT is expanded from...
configure.ac:3794: the top level
configure.ac:3794: warning: AC_PROG_LIBTOOL is m4_require'd but not m4_defun'd
acinclude.m4:2717: GMP_ASM_X86_MCOUNT is expanded from...
configure.ac:3794: the top level
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:3791: warning: AC_LIBTOOL_PROG_COMPILER_PIC is m4_require'd but not m4_defun'd
acinclude.m4:2363: GMP_ASM_X86_GOT_UNDERSCORE is expanded from...
configure.ac:3791: the top level
configure.ac:3794: warning: AC_ENABLE_SHARED is m4_require'd but not m4_defun'd
acinclude.m4:2717: GMP_ASM_X86_MCOUNT is expanded from...
configure.ac:3794: the top level
configure.ac:3794: warning: AC_PROG_LIBTOOL is m4_require'd but not m4_defun'd
acinclude.m4:2717: GMP_ASM_X86_MCOUNT is expanded from...
configure.ac:3794: the top level
configure.ac:2664: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:2754: error: possibly undefined macro: AC_PROG_LIBTOOL
configure.ac:2877: error: possibly undefined macro: AC_CHECK_LIBM
configure:11253: error: possibly undefined macro: AC_PROG_NM
configure:15228: error: possibly undefined macro: AC_LIBTOOL_PROG_COMPILER_PIC
configure:15323: error: possibly undefined macro: AC_ENABLE_SHARED
autoreconf: /usr/bin/autoconf failed with exit status: 1

I tried to do this but I couldn't solve it I posted the log right up there

Issue https://github.com/microsoft/vcpkg/issues/24788

**Comment by painer15999** [comment]
solved install ``apt-get install libtool`` 

using the command  ./vcpkg install gmp

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
