### ISSUE TITLE
Add GNU Scientific Library

### ISSUE THREAD

**Issue by traversaro** [Microsoft/vcpkg#251]
It would be great to have a port for the GNU Scientific Library library ( https://www.gnu.org/software/gsl/ ).

The first problem in this case is find a suitable port name, as `gsl` is already taken by the [Guidelines Support Library](https://github.com/Microsoft/GSL). 

Secondly, to get Visual Studio support perhaps the easiest way is to just roll our own alternative CMake-based build system, as done successfully in several other ports. 
Relevant links: 
* https://github.com/robotology/yarp/blob/master/packaging/windows/src/build_gsl.sh#L102
* https://github.com/robotology/yarp/blob/master/packaging/windows/src/gsl/CMakeLists.txt
* https://github.com/ampl/gsl

**Comment by ras0219-msft** [comment]
I'll propose `libgsl` or `gnusl` as names to package it under.

**Comment by ras0219-msft** [comment]
Fixed by #1009!

We've renamed `gsl` to `ms-gsl` and will use the port `gsl` to refer to the GNU Scientific Library.
