### ISSUE TITLE
[luajit] Build error

### ISSUE THREAD

**Issue by Sh3Ns** [microsoft/vcpkg#25102]
**Failure logs**

Detecting compiler hash for triplet arm64-linux...
The following packages will be built and installed:
  * boost-algorithm[core]:arm64-linux -> 1.79.0
  * boost-align[core]:arm64-linux -> 1.79.0
  * boost-array[core]:arm64-linux -> 1.79.0
    boost-asio[core]:arm64-linux -> 1.79.0
  * boost-assert[core]:arm64-linux -> 1.79.0
  * boost-atomic[core]:arm64-linux -> 1.79.0
  * boost-bind[core]:arm64-linux -> 1.79.0
  * boost-build[core]:arm64-linux -> 1.79.0
  * boost-chrono[core]:arm64-linux -> 1.79.0
  * boost-concept-check[core]:arm64-linux -> 1.79.0
  * boost-config[core]:arm64-linux -> 1.79.0
  * boost-container[core]:arm64-linux -> 1.79.0
  * boost-container-hash[core]:arm64-linux -> 1.79.0
  * boost-conversion[core]:arm64-linux -> 1.79.0
  * boost-core[core]:arm64-linux -> 1.79.0
  * boost-date-time[core]:arm64-linux -> 1.79.0
  * boost-detail[core]:arm64-linux -> 1.79.0
  * boost-dynamic-bitset[core]:arm64-linux -> 1.79.0
  * boost-exception[core]:arm64-linux -> 1.79.0
    boost-filesystem[core]:arm64-linux -> 1.79.0
  * boost-function[core]:arm64-linux -> 1.79.0
  * boost-function-types[core]:arm64-linux -> 1.79.0
  * boost-fusion[core]:arm64-linux -> 1.79.0
  * boost-integer[core]:arm64-linux -> 1.79.0
  * boost-intrusive[core]:arm64-linux -> 1.79.0
  * boost-io[core]:arm64-linux -> 1.79.0
    boost-iostreams[bzip2,core,lzma,zlib,zstd]:arm64-linux -> 1.79.0
  * boost-iterator[core]:arm64-linux -> 1.79.0
  * boost-lexical-cast[core]:arm64-linux -> 1.79.0
    boost-lockfree[core]:arm64-linux -> 1.79.0
  * boost-modular-build-helper[core]:arm64-linux -> 1.79.0#2
  * boost-move[core]:arm64-linux -> 1.79.0
  * boost-mp11[core]:arm64-linux -> 1.79.0
  * boost-mpl[core]:arm64-linux -> 1.79.0
  * boost-numeric-conversion[core]:arm64-linux -> 1.79.0
  * boost-optional[core]:arm64-linux -> 1.79.0
  * boost-parameter[core]:arm64-linux -> 1.79.0
  * boost-predef[core]:arm64-linux -> 1.79.0
  * boost-preprocessor[core]:arm64-linux -> 1.79.0
  * boost-random[core]:arm64-linux -> 1.79.0
  * boost-range[core]:arm64-linux -> 1.79.0
  * boost-ratio[core]:arm64-linux -> 1.79.0
  * boost-rational[core]:arm64-linux -> 1.79.0
  * boost-regex[core]:arm64-linux -> 1.79.0
  * boost-smart-ptr[core]:arm64-linux -> 1.79.0
  * boost-static-assert[core]:arm64-linux -> 1.79.0
    boost-system[core]:arm64-linux -> 1.79.0
  * boost-throw-exception[core]:arm64-linux -> 1.79.0
  * boost-tokenizer[core]:arm64-linux -> 1.79.0
  * boost-tuple[core]:arm64-linux -> 1.79.0
  * boost-type-index[core]:arm64-linux -> 1.79.0
  * boost-type-traits[core]:arm64-linux -> 1.79.0
  * boost-typeof[core]:arm64-linux -> 1.79.0
  * boost-uninstall[core]:arm64-linux -> 1.79.0
  * boost-unordered[core]:arm64-linux -> 1.79.0
  * boost-utility[core]:arm64-linux -> 1.79.0
    boost-variant[core]:arm64-linux -> 1.79.0
  * boost-variant2[core]:arm64-linux -> 1.79.0
  * boost-vcpkg-helpers[core]:arm64-linux -> 1.79.0
  * boost-winapi[core]:arm64-linux -> 1.79.0
  * bzip2[core]:arm64-linux -> 1.0.8#2
    curl[core,non-http,openssl,ssl]:arm64-linux -> 7.83.1#2
  * fmt[core]:arm64-linux -> 8.1.1#1
    gmp[core]:arm64-linux -> 6.2.1#9
    jsoncpp[core]:arm64-linux -> 1.9.5
  * liblzma[core]:arm64-linux -> 5.2.5#6
    libmariadb[core,mariadbclient,openssl,ssl]:arm64-linux -> 3.1.15
  * libzip[bzip2,core,default-aes,openssl]:arm64-linux -> 1.8.0
    libzippp[core]:arm64-linux -> 5.1-1.8.0
    luajit[core]:arm64-linux -> 2.0.5#8
  * openssl[core]:arm64-linux -> 3.0.3#2
    protobuf[core]:arm64-linux -> 3.19.4
    pugixml[core]:arm64-linux -> 1.12.1
    spdlog[core]:arm64-linux -> 1.10.0#1
  * vcpkg-cmake[core]:arm64-linux -> 2022-05-10
  * vcpkg-cmake-config[core]:arm64-linux -> 2022-02-06
  * vcpkg-cmake-get-vars[core]:arm64-linux -> 2022-05-10
  * zlib[core]:arm64-linux -> 1.2.12#1
  * zstd[core]:arm64-linux -> 1.5.2#1
Additional packages (*) will be modified to complete this operation.
Restored 75 packages from /root/.cache/vcpkg/archives in 2.318 s. Use --debug to see more details.
Installing 1/79 boost-uninstall:arm64-linux...
Elapsed time to handle boost-uninstall:arm64-linux: 1.034 ms
Installing 2/79 boost-vcpkg-helpers:arm64-linux...
Elapsed time to handle boost-vcpkg-helpers:arm64-linux: 461.9 us
Installing 3/79 boost-config:arm64-linux...
Elapsed time to handle boost-config:arm64-linux: 20.68 ms
Installing 4/79 boost-static-assert:arm64-linux...
Elapsed time to handle boost-static-assert:arm64-linux: 612.5 us
Installing 5/79 boost-type-traits:arm64-linux...
Elapsed time to handle boost-type-traits:arm64-linux: 19 ms
Installing 6/79 boost-assert:arm64-linux...
Elapsed time to handle boost-assert:arm64-linux: 871.7 us
Installing 7/79 boost-throw-exception:arm64-linux...
Elapsed time to handle boost-throw-exception:arm64-linux: 804 us
Installing 8/79 boost-preprocessor:arm64-linux...
Elapsed time to handle boost-preprocessor:arm64-linux: 51.16 ms
Installing 9/79 boost-io:arm64-linux...
Elapsed time to handle boost-io:arm64-linux: 1.649 ms
Installing 10/79 boost-core:arm64-linux...
Elapsed time to handle boost-core:arm64-linux: 5.545 ms
Installing 11/79 boost-utility:arm64-linux...
Elapsed time to handle boost-utility:arm64-linux: 2.511 ms
Installing 12/79 vcpkg-cmake:arm64-linux...
Elapsed time to handle vcpkg-cmake:arm64-linux: 1.187 ms
Installing 13/79 boost-predef:arm64-linux...
Elapsed time to handle boost-predef:arm64-linux: 9.15 ms
Installing 14/79 boost-winapi:arm64-linux...
Elapsed time to handle boost-winapi:arm64-linux: 8.129 ms
Installing 15/79 boost-mp11:arm64-linux...
Elapsed time to handle boost-mp11:arm64-linux: 2.79 ms
Installing 16/79 boost-variant2:arm64-linux...
Elapsed time to handle boost-variant2:arm64-linux: 1.402 ms
Installing 17/79 vcpkg-cmake-get-vars:arm64-linux...
Elapsed time to handle vcpkg-cmake-get-vars:arm64-linux: 1.372 ms
Installing 18/79 boost-modular-build-helper:arm64-linux...
Elapsed time to handle boost-modular-build-helper:arm64-linux: 1.395 ms
Installing 19/79 boost-build:arm64-linux...
Elapsed time to handle boost-build:arm64-linux: 58.17 ms
Installing 20/79 boost-system:arm64-linux...
Elapsed time to handle boost-system:arm64-linux: 4.334 ms
Installing 21/79 boost-move:arm64-linux...
Elapsed time to handle boost-move:arm64-linux: 5.021 ms
Installing 22/79 boost-smart-ptr:arm64-linux...
Elapsed time to handle boost-smart-ptr:arm64-linux: 6.962 ms
Installing 23/79 boost-mpl:arm64-linux...
Elapsed time to handle boost-mpl:arm64-linux: 43.64 ms
Installing 24/79 boost-integer:arm64-linux...
Elapsed time to handle boost-integer:arm64-linux: 3.505 ms
Installing 25/79 boost-detail:arm64-linux...
Elapsed time to handle boost-detail:arm64-linux: 3.693 ms
Installing 26/79 boost-container-hash:arm64-linux...
Elapsed time to handle boost-container-hash:arm64-linux: 3.448 ms
Installing 27/79 boost-concept-check:arm64-linux...
Elapsed time to handle boost-concept-check:arm64-linux: 3.512 ms
Installing 28/79 boost-regex:arm64-linux...
Elapsed time to handle boost-regex:arm64-linux: 49.13 ms
Installing 29/79 boost-typeof:arm64-linux...
Elapsed time to handle boost-typeof:arm64-linux: 8.874 ms
Installing 30/79 boost-type-index:arm64-linux...
Elapsed time to handle boost-type-index:arm64-linux: 3.507 ms
Installing 31/79 boost-bind:arm64-linux...
Elapsed time to handle boost-bind:arm64-linux: 3.788 ms
Installing 32/79 boost-function:arm64-linux...
Elapsed time to handle boost-function:arm64-linux: 3.894 ms
Installing 33/79 boost-optional:arm64-linux...
Elapsed time to handle boost-optional:arm64-linux: 3.668 ms
Installing 34/79 boost-tuple:arm64-linux...
Elapsed time to handle boost-tuple:arm64-linux: 3.2 ms
Installing 35/79 boost-function-types:arm64-linux...
Elapsed time to handle boost-function-types:arm64-linux: 6.676 ms
Installing 36/79 boost-fusion:arm64-linux...
Elapsed time to handle boost-fusion:arm64-linux: 64.61 ms
Installing 37/79 boost-conversion:arm64-linux...
Elapsed time to handle boost-conversion:arm64-linux: 3.865 ms
Installing 38/79 boost-iterator:arm64-linux...
Elapsed time to handle boost-iterator:arm64-linux: 5.332 ms
Installing 39/79 boost-tokenizer:arm64-linux...
Elapsed time to handle boost-tokenizer:arm64-linux: 3.747 ms
Installing 40/79 boost-array:arm64-linux...
Elapsed time to handle boost-array:arm64-linux: 3.571 ms
Installing 41/79 boost-range:arm64-linux...
Elapsed time to handle boost-range:arm64-linux: 10.41 ms
Installing 42/79 boost-numeric-conversion:arm64-linux...
Elapsed time to handle boost-numeric-conversion:arm64-linux: 4.877 ms
Installing 43/79 boost-intrusive:arm64-linux...
Elapsed time to handle boost-intrusive:arm64-linux: 8.489 ms
Installing 44/79 boost-container:arm64-linux...
Elapsed time to handle boost-container:arm64-linux: 13.42 ms
Installing 45/79 boost-lexical-cast:arm64-linux...
Elapsed time to handle boost-lexical-cast:arm64-linux: 4.61 ms
Installing 46/79 boost-unordered:arm64-linux...
Elapsed time to handle boost-unordered:arm64-linux: 4.796 ms
Installing 47/79 boost-exception:arm64-linux...
Elapsed time to handle boost-exception:arm64-linux: 4.903 ms
Installing 48/79 boost-algorithm:arm64-linux...
Elapsed time to handle boost-algorithm:arm64-linux: 8.005 ms
Installing 49/79 boost-date-time:arm64-linux...
Elapsed time to handle boost-date-time:arm64-linux: 9.069 ms
Installing 50/79 boost-rational:arm64-linux...
Elapsed time to handle boost-rational:arm64-linux: 4.223 ms
Installing 51/79 boost-ratio:arm64-linux...
Elapsed time to handle boost-ratio:arm64-linux: 5.647 ms
Installing 52/79 boost-chrono:arm64-linux...
Elapsed time to handle boost-chrono:arm64-linux: 9.495 ms
Installing 53/79 boost-align:arm64-linux...
Elapsed time to handle boost-align:arm64-linux: 5.948 ms
Installing 54/79 boost-asio:arm64-linux...
Elapsed time to handle boost-asio:arm64-linux: 35.24 ms
Installing 55/79 boost-atomic:arm64-linux...
Elapsed time to handle boost-atomic:arm64-linux: 11.69 ms
Installing 56/79 boost-filesystem:arm64-linux...
Elapsed time to handle boost-filesystem:arm64-linux: 20.96 ms
Installing 57/79 vcpkg-cmake-config:arm64-linux...
Elapsed time to handle vcpkg-cmake-config:arm64-linux: 5.098 ms
Installing 58/79 zstd:arm64-linux...
Elapsed time to handle zstd:arm64-linux: 13.68 ms
Installing 59/79 zlib:arm64-linux...
Elapsed time to handle zlib:arm64-linux: 5.538 ms
Installing 60/79 liblzma:arm64-linux...
Elapsed time to handle liblzma:arm64-linux: 7.9 ms
Installing 61/79 boost-dynamic-bitset:arm64-linux...
Elapsed time to handle boost-dynamic-bitset:arm64-linux: 4.971 ms
Installing 62/79 boost-random:arm64-linux...
Elapsed time to handle boost-random:arm64-linux: 11.51 ms
Installing 63/79 bzip2:arm64-linux...
Elapsed time to handle bzip2:arm64-linux: 5.507 ms
Installing 64/79 boost-iostreams:arm64-linux...
Elapsed time to handle boost-iostreams:arm64-linux: 20.15 ms
Installing 65/79 boost-parameter:arm64-linux...
Elapsed time to handle boost-parameter:arm64-linux: 9.703 ms
Installing 66/79 boost-lockfree:arm64-linux...
Elapsed time to handle boost-lockfree:arm64-linux: 5.364 ms
Installing 67/79 boost-variant:arm64-linux...
Elapsed time to handle boost-variant:arm64-linux: 6.245 ms
Installing 68/79 openssl:arm64-linux...
Elapsed time to handle openssl:arm64-linux: 674.3 ms
Installing 69/79 curl:arm64-linux...
Elapsed time to handle curl:arm64-linux: 16.42 ms
Installing 70/79 gmp:arm64-linux...
Elapsed time to handle gmp:arm64-linux: 33.26 ms
Installing 71/79 jsoncpp:arm64-linux...
Elapsed time to handle jsoncpp:arm64-linux: 233.1 ms
Installing 72/79 libmariadb:arm64-linux...
Elapsed time to handle libmariadb:arm64-linux: 1.721 s
Installing 73/79 libzip:arm64-linux...
Elapsed time to handle libzip:arm64-linux: 87.39 ms
Installing 74/79 libzippp:arm64-linux...
Elapsed time to handle libzippp:arm64-linux: 6.366 ms
Installing 75/79 luajit:arm64-linux...
Building luajit[core]:arm64-linux...
-- Using community triplet arm64-linux. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /home/ubuntu/vcpkg/triplets/community/arm64-linux.cmake
-- Using cached LuaJIT-LuaJIT-v2.0.5.tar.gz.
-- Cleaning sources at /home/ubuntu/vcpkg/buildtrees/luajit/src/v2.0.5-86b97027bc.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/ubuntu/vcpkg/downloads/LuaJIT-LuaJIT-v2.0.5.tar.gz
-- Applying patch 001-fix-build-path.patch
-- Applying patch 002-fix-crt-linkage.patch
-- Applying patch 003-do-not-set-macosx-deployment-target.patch
-- Using source at /home/ubuntu/vcpkg/buildtrees/luajit/src/v2.0.5-86b97027bc.clean
-- Building arm64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: make -j5 -f /home/ubuntu/vcpkg/buildtrees/luajit/src/v2.0.5-86b97027bc.clean/Makefile clean
    Working Directory: /home/ubuntu/vcpkg/buildtrees/luajit/src/v2.0.5-86b97027bc.clean
    See logs for more information:
      /home/ubuntu/vcpkg/buildtrees/luajit/clean-arm64-linux-debug-out.log
      /home/ubuntu/vcpkg/buildtrees/luajit/clean-arm64-linux-debug-err.log

Call Stack (most recent call first):
  ports/luajit/portfile.cmake:41 (vcpkg_execute_build_process)
  scripts/ports.cmake:146 (include)

error: building luajit:arm64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+luajit
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[luajit]+Build+error
Include '[luajit] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2999-12-31-unknownhash
    vcpkg-scripts version: 7ff57dfe9 2022-06-06 (3 hours ago)

**Failure logs** /home/ubuntu/vcpkg/buildtrees/luajit/clean-arm64-linux-debug-err.log

lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
   55 | #error "No support for this architecture (yet)"
      |  ^~~~~
lj_arch.h:294:2: error: #error "No target architecture defined"
  294 | #error "No target architecture defined"
      |  ^~~~~
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
   55 | #error "No support for this architecture (yet)"
      |  ^~~~~
lj_arch.h:294:2: error: #error "No target architecture defined"
  294 | #error "No target architecture defined"
      |  ^~~~~
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
   55 | #error "No support for this architecture (yet)"
      |  ^~~~~
lj_arch.h:294:2: error: #error "No target architecture defined"
  294 | #error "No target architecture defined"
      |  ^~~~~
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
   55 | #error "No support for this architecture (yet)"
      |  ^~~~~
lj_arch.h:294:2: error: #error "No target architecture defined"
  294 | #error "No target architecture defined"
      |  ^~~~~
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
   55 | #error "No support for this architecture (yet)"
      |  ^~~~~
lj_arch.h:294:2: error: #error "No target architecture defined"
  294 | #error "No target architecture defined"
      |  ^~~~~
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
   55 | #error "No support for this architecture (yet)"
      |  ^~~~~
lj_arch.h:294:2: error: #error "No target architecture defined"
  294 | #error "No target architecture defined"
      |  ^~~~~
Makefile:254: *** Unsupported target architecture.  Stop.
make: *** [/home/ubuntu/vcpkg/buildtrees/luajit/src/v2.0.5-86b97027bc.clean/Makefile:153: clean] Error 2

Issue https://github.com/draios/sysdig/issues/697

issue two https://github.com/ntop/ntopng/issues/1404

**Comment by painer15999** [comment]
up

**Comment by sonaldo** [comment]
up

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated in 3 months, if it is still an issue, please reopen this issue.
