### ISSUE TITLE
[openssl] Build error

### ISSUE THREAD

**Issue by whamer100** [microsoft/vcpkg#25107]
**Host Environment**
- OS: Windows 21H2 (19044.1706)
- Compiler: VS2019 (ninja)

    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: 203f5f3be 2022-06-06 (7 hours ago)

**To Reproduce**
`vcpkg install openssl`

**Failure logs**
```
-- Downloading https://www.openssl.org/source/openssl-3.0.3.tar.gz -> openssl-3.0.3.tar.gz...
-- Downloading https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-32bit.zip -> strawberry-perl-5.32.1.1-32bit.zip...
-- Extracting source E:/vcpkg/downloads/openssl-3.0.3.tar.gz
-- Applying patch E:/vcpkg/ports/openssl/windows/flags.patch
-- Using source at E:/vcpkg/buildtrees/openssl/src/openssl-3-e86111fb66.clean
-- Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip;https://fossies.org/windows/misc/nasm-2.15.05-win32.zip -> nasm-2.15.05-win32.zip...
-- Downloading https://download.qt.io/official_releases/jom/jom_1_1_3.zip;https://mirrors.ocf.berkeley.edu/qt/official_releases/jom/jom_1_1_3.zip -> jom_1_1_3.zip...
-- Found external ninja('1.10.2').
-- Getting CMake variables for x86-windows
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x86-windows-rel
-- Configure x86-windows-rel done
-- Build x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: E:/vcpkg/downloads/tools/jom/jom-1.1.3/jom.exe -j 1 -f makefile install_sw install_ssldirs
    Working Directory: E:/vcpkg/buildtrees/openssl/x86-windows-rel
    Error code: Access violation
    See logs for more information:
      E:\vcpkg\buildtrees\openssl\build-x86-windows-rel-1-err.log

Call Stack (most recent call first):
  ports/openssl/windows/portfile.cmake:103 (vcpkg_execute_required_process)
  ports/openssl/portfile.cmake:31 (include)
  scripts/ports.cmake:146 (include)
```

[build-x86-windows-rel-1-err.log](https://github.com/microsoft/vcpkg/files/8850423/build-x86-windows-rel-1-err.log)

**Additional context**
I just ran `git pull` before running this. Will provide more info if needed, however this was all the error information it provided me just by running. AV is currently not running.

**Comment by JackBoosY** [comment]
```
Command failed: E:/vcpkg/downloads/tools/jom/jom-1.1.3/jom.exe -j 1 -f makefile install_sw install_ssldirs
...
Error code: Access violation
```
Can you please double confirm your AV is closed, then remove folder _E:/vcpkg/downloads/tools/jom_ and try again?

Thanks.

**Comment by whamer100** [comment]
Just ran it again with ensuring my AV is disabled and even added an exclusion to the program. Got identical errors, access violation exception, and logs.

**Comment by JackBoosY** [comment]
jom.exe may have been disabled by AV causing this issue. So please delete jom folder, make sure no **other** AV is installed on the machine and try again.

**Comment by alexsualdea** [comment]
I had the same problem. In my case the problem was that I was using ConEmu and seems that some incompatibility with jom arised (probably a bug in ConEmu). When executed in cmd.exe it worked.

**Comment by whamer100** [comment]
> jom.exe may have been quarantined by AV causing this issue. So please delete jom folder, make sure no **other** AV is installed on the machine and try again.

I only have one antivirus installed on my machine, and nothing has been quarantined.

> I had the same problem. In my case the problem was that I was using ConEmu and seems that some incompatibility with jom arised (probably a bug in ConEmu). When executed in cmd.exe it worked.

Oh interesting, I'm using ConEmu as well (specifically cmder). I'll try using strictly cmd and see if it works then.

**Comment by whamer100** [comment]
Can confirm the command works when not using ConEmu. I wonder what's causing jom to have compatibility issues with ConEmu.

**Comment by JackBoosY** [comment]
@whamer100 We prefer to use powershell instead of other tools such as cmd. So I think the workaround is call pwsh in ConEmu.

**Comment by pubg-hacks** [comment]
Same for me cmder which is based on ConEmu caused the error and using cmd fixed it

**Comment by dg0yt** [comment]
Did anyone try to update ConEmu, given that they fixed a `jom` issue in 2021?
