### ISSUE TITLE
[fmt] Build error

### ISSUE THREAD

**Issue by frits-greuter** [microsoft/vcpkg#25109]
**Host Environment**
- OS: [windows 10]
- Compiler: revision

**To Reproduce**
`./vcpkg install fmt`

**Failure logs**
C:\vcpkg>vcpkg install fmt
Computing installation plan...
The following packages will be built and installed:
    fmt[core]:x86-windows -> 8.1.1#1
Detecting compiler hash for triplet x86-windows...
Restored 0 packages from C:\Users\User\AppData\Local\vcpkg\archives in 219.4 us. Use --debug to see more details.
Installing 1/1 fmt:x86-windows...
Building fmt[core]:x86-windows...
-- Using cached fmtlib-fmt-8.1.1.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/fmt/src/8.1.1-11f8359597.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/fmtlib-fmt-8.1.1.tar.gz
-- Applying patch fix-write-batch.patch
-- Applying patch fix-invalid-command.patch
-- Using source at C:/vcpkg/buildtrees/fmt/src/8.1.1-11f8359597.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
    Working Directory: C:/vcpkg/buildtrees/fmt/x86-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\fmt\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:112 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/fmt/portfile.cmake:20 (vcpkg_cmake_install)
  scripts/ports.cmake:146 (include)

error: building fmt:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+fmt
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[fmt]+Build+error
Include '[fmt] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: 203f5f3be 2022-06-06 (12 hours ago)

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8852444/install-x64-windows-dbg-out.log)
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8852445/install-x86-windows-dbg-out.log)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Adela0814** [comment]
https://github.com/fmtlib/fmt/issues/2896

**Comment by Adela0814** [comment]
@frits-greuter please try the PR https://github.com/microsoft/vcpkg/pull/25137

**Comment by Adela0814** [comment]
@frits-greuter ping for response.
