### ISSUE TITLE
[vcpkg-ce] TypeError: Cannot read properties of undefined (reading 'update')

### ISSUE THREAD

**Issue by vitaly-fanaskov** [microsoft/vcpkg#25112]
It's not possible to use `vcpkg activate` in github actions CI.

**Environment**
- OS: [ubuntu-20.04, ubuntu-22.04]

**To Reproduce**
1. Create a simple CMake-based project
2. Add a few required artifacts to the vcpkg-configuration.json 
3. Create a `build.yml` for github actions with at least the following steps: get vcpkg or use the existing one, run `vcpkg activate`
4. Push to the CI

**Expected behavior**
Artifacts (for example, cmake and ninja) are installed

**Actual behavior**
```
 /home/runner/.vcpkg/node_modules/vcpkg-ce/ce/dist/cli/artifacts.js:95
                        dl.update(percent);
                           ^
TypeError: Cannot read properties of undefined (reading 'update')
```
[log.txt](https://github.com/microsoft/vcpkg/files/8853410/log.txt)

**Additional context**
This works perfectly fine on my local machine, but doesn't work in the github actions.
Using system or bundled Node.js makes no difference. Also it doesn't matter which vcpkg I use.
I guess, it's possible to workaround the bug by using something like `dl?.update(percent);`, but it's not the desired way, I guess.

**Comment by AugP** [comment]
Thanks for reporting! We added this bug to our backlog and will roll out a fix as soon as we're able.

**Comment by BillyONeal** [comment]
For other reviewers: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1496625 is the same bug reported internally-only before. It is some kind of race in where ce is trying to draw progress bars and similar when the output is not a terminal. (Internally it was experienced trying to drive vcpkg with msbuild)

**Comment by BillyONeal** [comment]
This was fixed a couple of tool releases ago I think :)
