### ISSUE TITLE
Incomplete file download using vcpkg_download_distfile

### ISSUE THREAD

**Issue by inie0722** [microsoft/vcpkg#25140]
**Describe the bug**
I want to use vcpkg_download_distfile to download the library on my company's intranet gitlab, but each download is always incomplete, and the error SHA512 is inconsistent.
I have no problems downloading with wget.

**Environment**
- OS: [Linux]

**To Reproduce**
portfile.cmake
```
vcpkg_download_distfile(ARCHIVE
    URLS "http://172.16.18.3:8888/develop/strategysystem/-/archive/test/strategysystem-test.zip"
    FILENAME "strategysystem.zip"
    SHA512 9392e227009a0c3692e48df8547131e5c79729ba10e1e56c4b84d1023322fa51dff6e0cfc513857ca8d210f76663cfe21bdfe35a30b10a40ef4a3288ef1eacb4
)

vcpkg_extract_source_archive_ex(
    OUT_SOURCE_PATH SOURCE_PATH
    ARCHIVE "${ARCHIVE}"
)

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
)

vcpkg_cmake_install()
```
vcpkg install strategy-system

**Expected behavior**
file download complete.

**Failure logs**

> Computing installation plan...
The following packages will be built and installed:
    strategy-system[core]:x64-linux -> 1.0
Detecting compiler hash for triplet x64-linux...
Restored 0 packages from /home/inie0722/.cache/vcpkg/archives in 101.1 us. Use --debug to see more details.
Installing 1/1 strategy-system:x64-linux...
Building strategy-system[core]:x64-linux...
-- Downloading http://172.16.18.3:8888/develop/strategysystem/-/archive/test/strategysystem-test.zip -> strategysystem.zip...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] 1498622: popen(curl --fail -L http://172.16.18.3:8888/develop/strategysystem/-/archive/test/strategysystem-test.zip --create-dirs --output /home/inie0722/company/vcpkg/downloads/strategysystem.zip.1498622.part 2>&1)
[DEBUG] 1498622: cmd_execute_and_stream_data() returned 0 after   167512 us
Error: Failed to download from mirror set:
File does not have the expected hash:
             url : [ http://172.16.18.3:8888/develop/strategysystem/-/archive/test/strategysystem-test.zip ]
       File path : [ /home/inie0722/company/vcpkg/downloads/strategysystem.zip.1498622.part ]
   Expected hash : [ 9392e227009a0c3692e48df8547131e5c79729ba10e1e56c4b84d1023322fa51dff6e0cfc513857ca8d210f76663cfe21bdfe35a30b10a40ef4a3288ef1eacb4 ]
     Actual hash : [ b8030d9c2ec496f1321c1ff23eba14d3b4a194fd153028000fb411ab82985171838ca02b8b17ec20018ce8df12bf3dfbd61e4323bbb6f43148e378695d7d2906 ]

[DEBUG] /mnt/vss/_work/1/s/src/vcpkg/base/downloads.cpp(751): 
[DEBUG] Time in subprocesses: 168748 us
[DEBUG] Time in parsing JSON: 1 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 88 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 169.5 ms (168070 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:24 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. Your proxy's remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:249 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/strategy-system/portfile.cmake:1 (vcpkg_download_distfile)
  scripts/ports.cmake:146 (include)

error: building strategy-system:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+strategy-system
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[strategy-system]+Build+error
Include '[strategy-system] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: 279cb1766 2022-06-08 (20 minutes ago)

**Comment by autoantwort** [comment]
What is the content of the downloaded file?

**Comment by inie0722** [comment]
> And is `test` a branch? Each time a commit is pushed to the branch the hash will change if you download the latest commit

This file is unchanged, because the data downloaded each time is incomplete, resulting in different sha512.

**Comment by autoantwort** [comment]
Do you also get this problem if you run the command `curl --fail -L http://172.16.18.3:8888/develop/strategysystem/-/archive/test/strategysystem-test.zip --create-dirs --output /home/inie0722/company/vcpkg/downloads/strategysystem.zip.1498622.part 2>&1` manually

**Comment by inie0722** [comment]
> Do you also get this problem if you run the command `curl --fail -L http://172.16.18.3:8888/develop/strategysystem/-/archive/test/strategysystem-test.zip --create-dirs --output /home/inie0722/company/vcpkg/downloads/strategysystem.zip.1498622.part 2>&1` manually

This is the output.
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   103  100   103    0     0    528      0 --:--:-- --:--:-- --:--:--   528
100 26509    0 26509    0     0  90166      0 --:--:-- --:--:-- --:--:-- 90166
```

The curl download is also incomplete.
The full size of the file is 27045 bytes, and curl only downloaded 26509 bytes. I don't know what caused it. The files I downloaded using wget or browser are all 27045 bytes.

**Comment by inie0722** [comment]
Seems like because my project is private, wget may log into my account.
After I set the project to public, there is no problem with curl download.
