### ISSUE TITLE
[<port name>] build failure

### ISSUE THREAD

**Issue by 153808632253** [microsoft/vcpkg#25143]
1>节点 1 上的项目“F:\vcpkg\buildtrees\libpq\x64-windows-rel\libpq.vcxproj”(默认目标)。
     1>项目“F:\vcpkg\buildtrees\libpq\x64-windows-rel\libpq.vcxproj”(1)正在节点 1 上生成“F:\vcpkg\buildtrees\libpq\x64-windows-rel\libpgcommon.vcxproj”(2) (默认目标)。
     2>D:\VS2019Pro\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(436,5): error MSB8013: 此项目不包含配置和平台组合 Release|x64。 [F:\vcpkg\buildtrees\libpq\x64-windows-rel\libpgcommon.vcxproj]
     2>已完成生成项目“F:\vcpkg\buildtrees\libpq\x64-windows-rel\libpgcommon.vcxproj”(默认目标)的操作 - 失败。
     1>项目“F:\vcpkg\buildtrees\libpq\x64-windows-rel\libpq.vcxproj”(1)正在节点 2 上生成“F:\vcpkg\buildtrees\libpq\x64-windows-rel\libpgport.vcxproj”(3) (默认目标)。
     3>D:\VS2019Pro\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(436,5): error MSB8013: 此项目不包含配置和平台组合 Release|x64。 [F:\vcpkg\buildtrees\libpq\x64-windows-rel\libpgport.vcxproj]
     3>已完成生成项目“F:\vcpkg\buildtrees\libpq\x64-windows-rel\libpgport.vcxproj”(默认目标)的操作 - 失败。
     1>已完成生成项目“F:\vcpkg\buildtrees\libpq\x64-windows-rel\libpq.vcxproj”(默认目标)的操作 - 失败。

生成失败。

       “F:\vcpkg\buildtrees\libpq\x64-windows-rel\libpq.vcxproj”(默认目标) (1) ->
       “F:\vcpkg\buildtrees\libpq\x64-windows-rel\libpgcommon.vcxproj”(默认目标) (2) ->
       (PrepareForBuild 目标) -> 
         D:\VS2019Pro\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(436,5): error MSB8013: 此项目不包含配置和平台组合 Release|x64。 [F:\vcpkg\buildtrees\libpq\x64-windows-rel\libpgcommon.vcxproj]

       “F:\vcpkg\buildtrees\libpq\x64-windows-rel\libpq.vcxproj”(默认目标) (1) ->
       “F:\vcpkg\buildtrees\libpq\x64-windows-rel\libpgport.vcxproj”(默认目标) (3) ->
         D:\VS2019Pro\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(436,5): error MSB8013: 此项目不包含配置和平台组合 Release|x64。 [F:\vcpkg\buildtrees\libpq\x64-windows-rel\libpgport.vcxproj]

    0 个警告
    2 个错误

已用时间 00:00:01.15

**Comment by Cheney-W** [comment]
Dup to https://github.com/microsoft/vcpkg/issues/24495
