### ISSUE TITLE
[abseil:x64-windows] build failure

### ISSUE THREAD

**Issue by sasha-gil** [microsoft/vcpkg#25153]
**Host Environment**
- OS: Windows
- Compiler: cl.exe 19.12.25833.4. C++17 is off.

**To Reproduce**
vcpkg running in an internal build environment, details: https://stackoverflow.microsoft.com/questions/310157

**Failure logs**

The following packages will be built and installed:
  * abseil[core]:x64-windows -> 20211102.1
...

then from vcpkg\x64-windows\buildtrees\abseil\install-x64-windows-dbg-out.log:

[92/185] E:\CoreXTCache\.A\VisualCppTools.lKaUbCUnN0BT-Cda-2j8iw\lib\native\bin\amd64\cl.exe   /TP  -ID:\Git\kirin_sfs\Logs\vcpkg\x64-windows\buildtrees\abseil\src\cae233d0bf-0b16e4be7c.clean /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -MDd /W3 /DNOMINMAX /DWIN32_LEAN_AND_MEAN /D_CRT_SECURE_NO_WARNINGS /D_SCL_SECURE_NO_WARNINGS /D_ENABLE_EXTENDED_ALIGNED_STORAGE /bigobj /wd4005 /wd4068 /wd4180 /wd4244 /wd4267 /wd4503 /wd4800 /showIncludes /Foabsl\status\CMakeFiles\status.dir\status.cc.obj /Fdabsl\status\CMakeFiles\status.dir\status.pdb /FS -c D:\Git\kirin_sfs\Logs\vcpkg\x64-windows\buildtrees\abseil\src\cae233d0bf-0b16e4be7c.clean\absl\status\status.cc
FAILED: absl/status/CMakeFiles/status.dir/status.cc.obj 
E:\CoreXTCache\.A\VisualCppTools.lKaUbCUnN0BT-Cda-2j8iw\lib\native\bin\amd64\cl.exe   /TP  -ID:\Git\kirin_sfs\Logs\vcpkg\x64-windows\buildtrees\abseil\src\cae233d0bf-0b16e4be7c.clean /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -MDd /W3 /DNOMINMAX /DWIN32_LEAN_AND_MEAN /D_CRT_SECURE_NO_WARNINGS /D_SCL_SECURE_NO_WARNINGS /D_ENABLE_EXTENDED_ALIGNED_STORAGE /bigobj /wd4005 /wd4068 /wd4180 /wd4244 /wd4267 /wd4503 /wd4800 /showIncludes /Foabsl\status\CMakeFiles\status.dir\status.cc.obj /Fdabsl\status\CMakeFiles\status.dir\status.pdb /FS -c D:\Git\kirin_sfs\Logs\vcpkg\x64-windows\buildtrees\abseil\src\cae233d0bf-0b16e4be7c.clean\absl\status\status.cc
D:\Git\kirin_sfs\Logs\vcpkg\x64-windows\buildtrees\abseil\src\cae233d0bf-0b16e4be7c.clean\absl/meta/type_traits.h(174): error C2678: binary '=': no operator found which takes a left-hand operand of type 'const absl::lts_20211102::Cord' (or there is no acceptable conversion)
D:\Git\kirin_sfs\Logs\vcpkg\x64-windows\buildtrees\abseil\src\cae233d0bf-0b16e4be7c.clean\absl/strings/cord.h(154): note: could be 'absl::lts_20211102::Cord &absl::lts_20211102::Cord::operator =(absl::lts_20211102::string_view)'
D:\Git\kirin_sfs\Logs\vcpkg\x64-windows\buildtrees\abseil\src\cae233d0bf-0b16e4be7c.clean\absl/strings/cord.h(1196): note: or       'absl::lts_20211102::Cord &absl::lts_20211102::Cord::operator =(absl::lts_20211102::Cord &&) noexcept'
D:\Git\kirin_sfs\Logs\vcpkg\x64-windows\buildtrees\abseil\src\cae233d0bf-0b16e4be7c.clean\absl/strings/cord.h(1174): note: or       'absl::lts_20211102::Cord &absl::lts_20211102::Cord::operator =(const absl::lts_20211102::Cord &)'
D:\Git\kirin_sfs\Logs\vcpkg\x64-windows\buildtrees\abseil\src\cae233d0bf-0b16e4be7c.clean\absl/meta/type_traits.h(174): note: while trying to match the argument list '(const absl::lts_20211102::Cord, const absl::lts_20211102::Cord)'
D:\Git\kirin_sfs\Logs\vcpkg\x64-windows\buildtrees\abseil\src\cae233d0bf-0b16e4be7c.clean\absl/meta/type_traits.h(154): note: see reference to alias template instantiation 'IsCopyAssignableImpl<const absl::lts_20211102::Cord&>' being compiled
D:\Git\kirin_sfs\Logs\vcpkg\x64-windows\buildtrees\abseil\src\cae233d0bf-0b16e4be7c.clean\absl/meta/type_traits.h(195): note: see reference to class template instantiation 'absl::lts_20211102::type_traits_internal::is_detected<absl::lts_20211102::type_traits_internal::IsCopyAssignableImpl,T>' being compiled
        with
        [
            T=const absl::lts_20211102::Cord &
        ]
D:\Git\kirin_sfs\Logs\vcpkg\x64-windows\buildtrees\abseil\src\cae233d0bf-0b16e4be7c.clean\absl/meta/type_traits.h(495): note: see reference to class template instantiation 'absl::lts_20211102::is_copy_assignable<T>' being compiled
        with
        [
            T=const absl::lts_20211102::Cord &
        ]
D:\Git\kirin_sfs\Logs\vcpkg\x64-windows\buildtrees\abseil\src\cae233d0bf-0b16e4be7c.clean\absl/functional/internal/function_ref.h(48): note: see reference to class template instantiation 'absl::lts_20211102::is_trivially_copy_assignable<const absl::lts_20211102::Cord &>' being compiled
D:\Git\kirin_sfs\Logs\vcpkg\x64-windows\buildtrees\abseil\src\cae233d0bf-0b16e4be7c.clean\absl/functional/internal/function_ref.h(54): note: see reference to function template instantiation 'bool absl::lts_20211102::functional_internal::PassByValue<T>(void)' being compiled
        with
        [
            T=const absl::lts_20211102::Cord &
        ]
D:\Git\kirin_sfs\Logs\vcpkg\x64-windows\buildtrees\abseil\src\cae233d0bf-0b16e4be7c.clean\absl/functional/function_ref.h(136): note: see reference to class template instantiation 'absl::lts_20211102::functional_internal::ForwardT<const absl::lts_20211102::Cord &>' being compiled
D:\Git\kirin_sfs\Logs\vcpkg\x64-windows\buildtrees\abseil\src\cae233d0bf-0b16e4be7c.clean\absl\status\status.cc(165): note: see reference to class template instantiation 'absl::lts_20211102::FunctionRef<void (absl::lts_20211102::string_view,const absl::lts_20211102::Cord &)>' being compiled
D:\Git\kirin_sfs\Logs\vcpkg\x64-windows\buildtrees\abseil\src\cae233d0bf-0b16e4be7c.clean\absl/strings/internal/cord_rep_ring.h(360): note: see reference to class template instantiation 'absl::lts_20211102::container_internal::internal_layout::LayoutImpl<std::tuple<absl::lts_20211102::cord_internal::CordRepRing::pos_type,absl::lts_20211102::cord_internal::CordRep *,absl::lts_20211102::cord_internal::CordRepRing::offset_type>,absl::lts_20211102::integer_sequence<T>,absl::lts_20211102::integer_sequence<T,0>>' being compiled
        with
        [
            T=::size_t
        ]

**Additional context**
Build succeeds with vcpkg's version 2021.9.27.59-59a3f35e7, fails with newer vcpkg versions (e.g. 2022.4.4.218-01d6f6ff1) - that issue blocks vcpkg version upgrade. I did not find differences in abseil versions here and there, I guess that something might be different in compiler flags, applied patches.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Did you run `git pull` and `.\bootstrap-vcpkg.bat` before installing `abseil`? Or you installed it failed on a latest vcpkg? I can install abseil succeed on vcpkg version (2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8).
![image](https://user-images.githubusercontent.com/94091114/172755120-38ab27f5-4d77-41f9-b53a-529248a3ed13.png)

**Comment by sasha-gil** [comment]
@LilyWangLL I do not have boostrap-vcpkg.bat in my enlistment: our repo uses vcpkg as an internal NuGet package and there is no boostrap-vcpkg.bat in that packaging. Also, I do not launch vcpkg install on my own, build process does that. I guess I should start drilling from the side of our internal build infrastructure.

**Comment by LilyWangLL** [comment]
> @LilyWangLL I do not have boostrap-vcpkg.bat in my enlistment: our repo uses vcpkg as an internal NuGet package and there is no boostrap-vcpkg.bat in that packaging. Also, I do not launch vcpkg install on my own, build process does that. I guess I should start drilling from the side of our internal build infrastructure.

Thanks for your reply. How your project update vcpkg to latest source? Or clone new vcpkg everytime when build project?

**Comment by LilyWangLL** [comment]
Ping @sasha-gil for response.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
