### ISSUE TITLE
[libheif] Build error: _iconv, _iconv_close & _iconv_open undefined

### ISSUE THREAD

**Issue by MarkCallow** [microsoft/vcpkg#25161]
**Host Environment**
- OS: macOS 12.4
- Compiler: Apple Clang 13.1.6

**To Reproduce**
`./vcpkg install libheif`

**Failure logs**
```
Computing installation plan...
The following packages will be built and installed:
    libheif[core]:x64-osx -> 1.12.0#3
Detecting compiler hash for triplet x64-osx...
Restored 0 packages from /Users/mark/.cache/vcpkg/archives in 17.34 us. Use --debug to see more details.
Installing 1/1 libheif:x64-osx...
Building libheif[core]:x64-osx...
-- Using cached strukturag-libheif-56c8a2613370562fc330af2c70c1510aa5fd9ff6.tar.gz.
-- Cleaning sources at /Users/mark/Projects/github/vcpkg/buildtrees/libheif/src/0aa5fd9ff6-7d0174337d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/mark/Projects/github/vcpkg/downloads/strukturag-libheif-56c8a2613370562fc330af2c70c1510aa5fd9ff6.tar.gz
-- Applying patch gdk-pixbuf.patch
-- Using source at /Users/mark/Projects/github/vcpkg/buildtrees/libheif/src/0aa5fd9ff6-7d0174337d.clean
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:122 (message):
    Command failed: /opt/local/bin/cmake --build . --config Debug --target install -- -v -j9
    Working Directory: /Users/mark/Projects/github/vcpkg/buildtrees/libheif/x64-osx-dbg
    See logs for more information:
      /Users/mark/Projects/github/vcpkg/buildtrees/libheif/install-x64-osx-dbg-out.log

Call Stack (most recent call first):
  installed/x64-osx/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-osx/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/libheif/portfile.cmake:17 (vcpkg_cmake_install)
  scripts/ports.cmake:146 (include)

error: building libheif:x64-osx failed with: BUILD_FAILED
```
[install-x64-osx-dbg-out.log](https://github.com/microsoft/vcpkg/files/8869450/install-x64-osx-dbg-out.log)

**Additional context**

vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
vcpkg-scripts version: 1323f4b83 2022-06-08 (11 hours ago)

**Comment by MarkCallow** [comment]
/opt/local stuff is from [MacPorts](https://www.macports.org/). I don't understand how the build ended up picking `/opt/local/bin/cmake` as `/Applications/CMake.app/Contents/bin` appears before `/opt/local/bin` in my PATH. I suppose it is because that cmake was used that `-isystem /opt/local/include` appears in all the compile commands and some of the dylibs found and explicitly linked to are in `/opt/local/lib`.

Is there a recommended way to avoid conflicts with other package managers?

**Comment by jimwang118** [comment]
I retested this problem on macos, and now there is no problem with the installation.I think this issue can be closed, if someone has new idea, please reopen this issue.
