### ISSUE TITLE
When compiling a PORT, is it possible to specify the version of this PORT?  Or keep multiple versions at the same time?

### ISSUE THREAD

**Issue by KangLin** [microsoft/vcpkg#25167]
When compiling a PORT, is it possible to specify the version of this PORT? Or keep multiple versions at the same time?
eg:
Openssl version is 3.0.3 in current vcpkg. but I need openssl 1.1.1.
How do i do it?

**Comment by JackBoosY** [comment]
In classic mode vcpkg only supports updating to the version owned by GIT_HEAD. 
And you can use the manifest pattern to specify the specific version number you want.
See https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md

**Comment by Neumann-A** [comment]
OR user overlay-ports https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by KangLin** [comment]
@JackBoosY Thanks you! manifest mode can solved the problem.
How to know which versions of OPENSSL are supported by vcpkg?

**Comment by JackBoosY** [comment]
@KangLin `./vcpkg x-history openssl`.

**Comment by KangLin** [comment]
@Neumann-A I use  overlay-ports, but it is fail.
- I copy openssl1.1.n port to my project folder https://github.com/KangLin/RabbitRemoteControl/tree/develop/vcpkg/ports/openssl from old vcpkg.
- I run vcpkg install openssl --overlay-ports=D:\source\rabbitremotecontol\vcpkg\ports . it is fail.
- I set  environment variable VCPKG_OVERLAY_PORTS. it is fail.

Where am I doing wrong?

Run result:
D:\source\vcpkg>vcpkg install openssl --overlay-ports=D:\source\rabbitremotecont
rol\vcpkg\ports
Computing installation plan...
The following packages will be built and installed:
    openssl[core]:x86-windows -> 3.0.5#4
  * vcpkg-cmake[core]:x64-windows -> 2022-07-18
  * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06#1
  * vcpkg-cmake-get-vars[core]:x64-windows -> 2022-05-10#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
Restored 3 package(s) from C:\Users\Administrator\AppData\Local\vcpkg\archives i
n 68.54 ms. Use --debug to see more details.
Installing 1/4 vcpkg-cmake:x64-windows...
Elapsed time to handle vcpkg-cmake:x64-windows: 16.39 ms
Installing 2/4 vcpkg-cmake-config:x64-windows...
Elapsed time to handle vcpkg-cmake-config:x64-windows: 14.54 ms

**Comment by JackBoosY** [comment]
@KangLin Can you please provide the full output?

**Comment by KangLin** [comment]
@JackBoosY  @Neumann-A 

vcpkg version: f688b2e29676bfa3a02ead4b7096c589f8af8180
openssl 1.1.n:  https://github.com/KangLin/RabbitRemoteControl/tree/develop/vcpkg/ports/openssl

Run result:
D:\source\vcpkg>vcpkg install openssl --overlay-ports=D:\source\rabbitremotecontrol\vcpkg\ports
Computing installation plan...
The following packages will be built and installed:
    openssl[core]:x86-windows -> 3.0.5#4
  * vcpkg-cmake[core]:x64-windows -> 2022-07-18
  * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06#1
  * vcpkg-cmake-get-vars[core]:x64-windows -> 2022-05-10#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
A suitable version of powershell-core was not found (required v7.2.5). Downloadi
ng portable powershell-core v7.2.5...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v7.2.5/PowerShell-7
.2.5-win-x86.zip -> D:\source\vcpkg\downloads\PowerShell-7.2.5-win-x86.zip
Extracting powershell-core...
Detecting compiler hash for triplet x86-windows...
A suitable version of 7zip was not found (required v21.7.0). Downloading portabl
e 7zip v21.7.0...
Downloading 7zip...
  https://www.7-zip.org/a/7z2107-extra.7z -> D:\source\vcpkg\downloads\7z2107-ex
tra.7z
Extracting 7zip...
Restored 3 package(s) from C:\Users\Administrator\AppData\Local\vcpkg\archives i
n 10.64 s. Use --debug to see more details.
Installing 1/4 vcpkg-cmake:x64-windows...
Elapsed time to handle vcpkg-cmake:x64-windows: 17.82 ms
Installing 2/4 vcpkg-cmake-config:x64-windows...
Elapsed time to handle vcpkg-cmake-config:x64-windows: 17.3 ms
Installing 3/4 vcpkg-cmake-get-vars:x64-windows...
Elapsed time to handle vcpkg-cmake-get-vars:x64-windows: 10.16 ms
Installing 4/4 openssl:x86-windows...
Building openssl[core]:x86-windows...
-- Downloading https://github.com/openssl/openssl/archive/openssl-3.0.5.tar.gz -
> openssl-openssl-openssl-3.0.5.tar.gz...
-- Extracting source D:/source/vcpkg/downloads/openssl-openssl-openssl-3.0.5.tar
.gz
-- Applying patch D:/source/vcpkg/ports/openssl/windows/flags.patch
-- Using source at D:/source/vcpkg/buildtrees/openssl/src/nssl-3.0.5-df50913d32.
clean
-- Downloading https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32
.1.1-32bit.zip -> strawberry-perl-5.32.1.1-32bit.zip...
-- Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.1
5.05-win32.zip;https://fossies.org/windows/misc/nasm-2.15.05-win32.zip -> nasm-2
.15.05-win32.zip...
-- Downloading https://download.qt.io/official_releases/jom/jom_1_1_3.zip;https:
//mirrors.ocf.berkeley.edu/qt/official_releases/jom/jom_1_1_3.zip -> jom_1_1_3.z
ip...
-- Found external ninja('1.10.2').
-- Getting CMake variables for x86-windows
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x86-windows-rel
-- Configure x86-windows-rel done
-- Build x86-windows-rel
-- Build x86-windows-rel done
-- Copying openssl debug source files...
-- Copying openssl debug source files... done
-- Configure x86-windows-dbg
-- Configure x86-windows-dbg done
-- Build x86-windows-dbg
-- Build x86-windows-dbg done
CMake Warning at scripts/cmake/vcpkg_copy_pdbs.cmake:44 (message):
  Could not find a matching pdb file for:

      D:/source/vcpkg/packages/openssl_x86-windows/bin/legacy.dll
      D:/source/vcpkg/packages/openssl_x86-windows/bin/libcrypto-3.dll
      D:/source/vcpkg/packages/openssl_x86-windows/bin/libssl-3.dll
      D:/source/vcpkg/packages/openssl_x86-windows/debug/bin/legacy.dll
      D:/source/vcpkg/packages/openssl_x86-windows/debug/bin/libcrypto-3.dll
      D:/source/vcpkg/packages/openssl_x86-windows/debug/bin/libssl-3.dll

Call Stack (most recent call first):
  ports/openssl/windows/portfile.cmake:218 (vcpkg_copy_pdbs)
  ports/openssl/portfile.cmake:36 (include)
  scripts/ports.cmake:147 (include)


-- Installing: D:/source/vcpkg/packages/openssl_x86-windows/share/openssl/copyri
ght
-- Fixing pkgconfig file: D:/source/vcpkg/packages/openssl_x86-windows/lib/pkgco
nfig/libcrypto.pc
-- Fixing pkgconfig file: D:/source/vcpkg/packages/openssl_x86-windows/lib/pkgco
nfig/libssl.pc
-- Fixing pkgconfig file: D:/source/vcpkg/packages/openssl_x86-windows/lib/pkgco
nfig/openssl.pc
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.
2-3-any.pkg.tar.zst;https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/m
ingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://mirror.yandex.ru/mirro
rs/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://m
irrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-
any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-
config-0.29.2-3-any.pkg.tar.zst;https://mirror.bit.edu.cn/msys2/mingw/i686/mingw
-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mi
ngw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://mirrors.sjtu
g.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zs
t -> msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst...
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-gi
t-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://www2.futureware.at/~nickoe/msys
2-mirror/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.
pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-lib
winpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://mirrors.tuna.tsing
hua.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd8
3-1-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-
libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://mirror.bit.edu.
cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.
pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-libwinpthr
ead-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://mirrors.sjtug.sjtu.edu.cn
/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pk
g.tar.zst -> msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pk
g.tar.zst...
-- Using msys root at D:/source/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Fixing pkgconfig file: D:/source/vcpkg/packages/openssl_x86-windows/debug/lib
/pkgconfig/libcrypto.pc
-- Fixing pkgconfig file: D:/source/vcpkg/packages/openssl_x86-windows/debug/lib
/pkgconfig/libssl.pc
-- Fixing pkgconfig file: D:/source/vcpkg/packages/openssl_x86-windows/debug/lib
/pkgconfig/openssl.pc
-- Installing: D:/source/vcpkg/packages/openssl_x86-windows/share/openssl/usage
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: "C:\Users\Administrator\AppData\Local\vcpkg\archives\c2\c21
e89cb18679e5abfe86b49e03719d440d4d103c0d8ce1c88fab5cf090ec326.zip"
Elapsed time to handle openssl:x86-windows: 1.935 h

Total elapsed time: 6.142 h

The package openssl is compatible with built-in CMake targets:

    find_package(OpenSSL REQUIRED)
    target_link_libraries(main PRIVATE OpenSSL::SSL OpenSSL::Crypto)

**Comment by JackBoosY** [comment]
`vcpkg.json` is not exist in your path https://github.com/KangLin/RabbitRemoteControl/tree/develop/vcpkg/ports/openssl.

**Comment by KangLin** [comment]
@JackBoosY Thank you! It is work.

In classic mode, I just need to specify the old version. Using overlays feels a bit complicated. Can there be an easier way? For example: vcpkg install openssl:version

**Comment by JackBoosY** [comment]
> In classic mode, I just need to specify the old version. Using --overlay-ports feels a bit complicated. Can there be an easier way? For example: vcpkg install openssl:version

Corrently no, sorry. I think we will improve this part of usage in the future.

**Comment by natsuki-Uzu** [comment]
It is recommended to use vcpkg install openssl --overlay-ports=D:\source\rabbitremotecontrol\vcpkg\ports instead of vcpkg upgrade --no-dry-run --overlay-ports=D:\source\rabbitremotecontrol\vcpkg\ports
