### ISSUE TITLE
[libgcrypt] build failure on linux

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#25177]
libgcrypt build failure on linux:
It not recognize libgpg-error version even it install with vcpkg. 
```
Installing 1/3 libgcrypt:x64-linux...
Building libgcrypt[core]:x64-linux...
-- [OVERLAY] Loading triplet configuration from: /home/ubuntu/boinc/3rdParty/vcpkg_ports/triplets/ci/x64-linux.cmake
-- Using cached /home/ubuntu/boinc/3rdParty/linux/vcpkg/downloads/libgcrypt-ae0e567820c37f9640440b3cff77d7c185aa6742.tar.gz
-- Extracting source /home/ubuntu/boinc/3rdParty/linux/vcpkg/downloads/libgcrypt-ae0e567820c37f9640440b3cff77d7c185aa6742.tar.gz
-- Using source at /home/ubuntu/boinc/3rdParty/linux/vcpkg/buildtrees/libgcrypt/src/c185aa6742-57ce97cffa.clean
-- Getting CMake variables for x64-linux-rel
-- Generating configure for x64-linux
-- Finished generating configure for x64-linux
-- Configuring x64-linux-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: /usr/bin/bash -c "V=1 ./../src/c185aa6742-57ce97cffa.clean/configure  \"--disable-doc\" \"--disable-silent-rules\" \"--with-libgpg-error-prefix=/home/ubuntu/boinc/3rdParty/linux/vcpkg/installed/x64-linux/tools/libgpg-error\" \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"--prefix=/home/ubuntu/boinc/3rdParty/linux/vcpkg/installed/x64-linux\" \"--bindir=\\${prefix}/tools/libgcrypt/bin\" \"--sbindir=\\${prefix}/tools/libgcrypt/sbin\" \"--libdir=\\${prefix}/lib\" \"--mandir=\\${prefix}/share/libgcrypt\" \"--docdir=\\${prefix}/share/libgcrypt\" \"--datarootdir=\\${prefix}/share/libgcrypt\""
    Working Directory: /home/ubuntu/boinc/3rdParty/linux/vcpkg/buildtrees/libgcrypt/x64-linux-rel
    Error code: 1
    See logs for more information:
      /home/ubuntu/boinc/3rdParty/linux/vcpkg/buildtrees/libgcrypt/config-x64-linux-rel-out.log
      /home/ubuntu/boinc/3rdParty/linux/vcpkg/buildtrees/libgcrypt/config-x64-linux-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:799 (vcpkg_execute_required_process)
  ports/libgcrypt/portfile.cmake:9 (vcpkg_configure_make)
  scripts/ports.cmake:146 (include)
```

```
> ./vcpkg list | grep error
libgpg-error:x64-linux                             1.42#3           A common dependency of all GnuPG components
```
[config-x64-linux-rel-out.log](https://github.com/microsoft/vcpkg/files/8880138/config-x64-linux-rel-out.log)
[config-x64-linux-rel-err.log](https://github.com/microsoft/vcpkg/files/8880139/config-x64-linux-rel-err.log)

**Comment by JackBoosY** [comment]
libgcrypt does depend on libgpg-error:
https://github.com/microsoft/vcpkg/blob/8e1f46de11423e5f7d2395458f5252738ffffbbd/ports/libgcrypt/vcpkg.json#L7-L9

Maybe your vcpkg is outdated?

**Comment by talregev** [comment]
> libgcrypt does depend on libgpg-error:
> https://github.com/microsoft/vcpkg/blob/8e1f46de11423e5f7d2395458f5252738ffffbbd/ports/libgcrypt/vcpkg.json#L7-L9
> 
> Maybe your vcpkg is outdated?

Latest vcpkg.
If you look inside the log it looking for libgpg-error.
You should add it as a dependency.
Please try it local and tell me if you can produce this bug.

**Comment by JackBoosY** [comment]
I can't reproduce this locally, can you please remove port libgpg-error and try again?

Thanks.

**Comment by talregev** [comment]
> libgcrypt does depend on libgpg-error:
> https://github.com/microsoft/vcpkg/blob/8e1f46de11423e5f7d2395458f5252738ffffbbd/ports/libgcrypt/vcpkg.json#L7-L9
> 
> Maybe your vcpkg is outdated?

It install the libgpg-error as I show in the screen shot. but it not recognize the correct one.
It taking the os libgpg-error instead the vcpkg one

**Comment by talregev** [comment]
> I can't reproduce this locally, can you please remove port libgpg-error and try again?
> 
> Thanks.

You have libgpg-error on your system?
If not please install it then you will have the bug.

**Comment by JackBoosY** [comment]
cc @wrobelda

**Comment by wrobelda** [comment]
```
checking for gpg-error-config... /home/ubuntu/boinc/3rdParty/linux/vcpkg/installed/x64-linux/tools/libgpg-error/bin/gpg-error-config
checking for gpgrt-config... /usr/bin/gpgrt-config
checking for GPG Error - version >= 1.27... no`
```

While the configure script honors the `--with-libgpg-error-prefix=${CURRENT_INSTALLED_DIR}/tools/libgpg-error` I pass it to config script, it does not use it to lookup the `gpgrt-config`, which it picks up from root `/usr/bin`. 

This has been previously reported to GnuPG people, including myself, and their explanation is rather unsatisfying:
https://dev.gnupg.org/T5365

@JackBoosY  You can see my comments there, which had been mostly ignored, and, frankly speaking, the GnuPG is such a mess that I simply choose to spend my free time on different projects than trying to workaround their "it is like this because we feel like it and it's not going to change" attitude 💁🏻‍♂️

I still think that the ShiftMediaProject is the way to go when it comes to GnuPG toolkit portfolio.
