### ISSUE TITLE
Use proxy information from Windows when downloading files

### ISSUE THREAD

**Issue by ras0219-msft** [microsoft/vcpkg#252]
Currently, portfiles use CMake's built-in downloading function to acquire sources. This function is backed by `curl`, which doesn't use Windows' system-wide proxy settings and instead requires special environment variables (http_proxy, https_proxy, ftp_proxy, ...).

Inside `vcpkg.exe`, we should detect the Windows settings and fill in these environment variables before calling CMake so users get a much cleaner out-of-the-box experience.

**Comment by KindDragon** [comment]
> Inside vcpkg.exe, we should detect the Windows settings and fill in these environment variables before calling CMake so users get a much cleaner out-of-the-box experience.

But in this case, the user will still have to specify a username and password?

**Comment by ras0219-msft** [comment]
Perhaps; curl will use the username/password information from the environment variable so we could prompt for credentials (or, more nicely, take it from a command line argument/config file).

**Comment by PhoebeHui** [comment]
I think https://github.com/microsoft/vcpkg-tool/pull/49 has implemented this, @ras0219-msft, please reopen this issue if i'm wrong.
