### ISSUE TITLE
[apsi] Build error

### ISSUE THREAD

**Issue by simingzhao** [microsoft/vcpkg#25216]
**Host Environment**
- OS: macOS 12.4
- Compiler: clang-1316.0.21.2.5

**To Reproduce**
`./vcpkg install apsi:x64-osx`

**Failure logs**
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: /Applications/CMake.app/Contents/bin/cmake --build . --config Debug --target install -- -v -j9
    Working Directory: /Users/siming/vcpkg/buildtrees/apsi/x64-osx-dbg
    See logs for more information:
      /Users/siming/vcpkg/buildtrees/apsi/install-x64-osx-dbg-out.log

Call Stack (most recent call first):
  installed/arm64-osx/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/arm64-osx/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/apsi/portfile.cmake:26 (vcpkg_cmake_install)
  scripts/ports.cmake:146 (include)

**Comment by Cheney-W** [comment]
Could you please provide us with `/Users/siming/vcpkg/buildtrees/apsi/install-x64-osx-dbg-out.log`? Thank you!

**Comment by Sand2Silicon** [comment]
I'm going to work on a new report but at a glance this is the same error I started getting yesterday afternoon, except on Windows and with protobuf. My whole build process was working, until it started failing with unresolved linking errors to the protobuf lib I'm pulling through vcpkg in manifest mode with a pinned version number from months ago.

**Comment by Cheney-W** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
