### ISSUE TITLE
[OpenCV]Error:  file failed to open for reading

### ISSUE THREAD

**Issue by z2665** [Microsoft/vcpkg#2522]
I build it in vs2017 and win10
It seems build debug version failed
Package: opencv:x86-windows
 Vcpkg version: 0.0.100-2018-01-05-2dab9a2576a4f2c03d65abc9ad2668d2f34c6ba5

-- Build x86-windows-rel
-- Build x86-windows-rel done
-- Build x86-windows-dbg
-- Build x86-windows-dbg done
CMake Error at D:/vcpkg/vcpkg/ports/opencv/portfile.cmake:186 (file):
  file failed to open for reading (No such file or directory):

    D:/vcpkg/vcpkg/packages/opencv_x86-windows/debug/share/opencv/x86/vc15/lib/OpenCVModules-debug.cmake
Call Stack (most recent call first):
  D:/vcpkg/vcpkg/scripts/ports.cmake:72 (include)

**Comment by fawkes74** [comment]
This patch should fix it:
`diff --git a/scripts/cmake/vcpkg_build_cmake.cmake b/scripts/cmake/vcpkg_build_cmake.cmake
index 66503f4b..8bafee4d 100644
--- a/scripts/cmake/vcpkg_build_cmake.cmake
+++ b/scripts/cmake/vcpkg_build_cmake.cmake
@@ -80,7 +80,7 @@ function(vcpkg_build_cmake)
             endif()
 
             execute_process(
-                COMMAND ${CMAKE_COMMAND} --build . --config Release ${TARGET_PARAM} -- ${BUILD_ARGS} ${PARALLEL_ARG}
+                COMMAND ${CMAKE_COMMAND} --build . --config ${CONFIG} ${TARGET_PARAM} -- ${BUILD_ARGS} ${PARALLEL_ARG}
                 OUTPUT_FILE "${LOGPREFIX}-out.log"
                 ERROR_FILE "${LOGPREFIX}-err.log"
                 RESULT_VARIABLE error_code
@@ -99,7 +99,7 @@ function(vcpkg_build_cmake)
                 if(out_contents MATCHES "LINK : fatal error LNK1102:" OR out_contents MATCHES " fatal error C1060: ")
                     # The linker ran out of memory during execution. We will try continuing once more, with parallelism disabled.
                     execute_process(
-                        COMMAND ${CMAKE_COMMAND} --build . --config Release ${TARGET_PARAM} -- ${BUILD_ARGS} ${NO_PARALLEL_ARG}
+                        COMMAND ${CMAKE_COMMAND} --build . --config ${CONFIG} ${TARGET_PARAM} -- ${BUILD_ARGS} ${NO_PARALLEL_ARG}
                         OUTPUT_FILE "${LOGPREFIX}-out-1.log"
                         ERROR_FILE "${LOGPREFIX}-err-1.log"
                         RESULT_VARIABLE error_code
@@ -124,7 +124,7 @@ function(vcpkg_build_cmake)
                         file(TO_NATIVE_PATH "${LOG}" NATIVE_LOG)
                         list(APPEND STRINGIFIED_LOGS "    ${NATIVE_LOG}\n")
                     endforeach()
-                    set(_eb_COMMAND ${CMAKE_COMMAND} --build . --config Release ${TARGET_PARAM} -- ${BUILD_ARGS} ${NO_PARALLEL_ARG})
+                    set(_eb_COMMAND ${CMAKE_COMMAND} --build . --config ${CONFIG} ${TARGET_PARAM} -- ${BUILD_ARGS} ${NO_PARALLEL_ARG})
                     set(_eb_WORKING_DIRECTORY ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-${SHORT_BUILDTYPE})
                     message(FATAL_ERROR
                         "  Command failed: ${_eb_COMMAND}\n"
`

**Comment by z2665** [comment]
thanks~ It build success
