### ISSUE TITLE
Some thing wrong when cmake build SDL2 program at windows

### ISSUE THREAD

**Issue by AserJoker** [microsoft/vcpkg#25222]
**Describe the bug**
CMake found the wrong include path

**Environment**
- OS: Windows 10
- Compiler: MinGW-w64 with CMake

**To Reproduce**
1. ./vcpkg install sdl2:x64-windows
2. set Clion CMake Option with vcpkg toolchain
3. edit cmake with
```cmake
cmake_minimum_required(VERSION 3.21)

project(Lux)

set(CMAKE_CXX_STANDARD 20)
find_package(SDL2 CONFIG REQUIRED)

add_executable(Lux main.cpp)
target_link_libraries(Lux SDL2::SDL2 SDL2::SDL2main)
```

**Failure logs**
```txt
  CMake Error in CMakeLists.txt:
  Imported target "SDL2::SDL2" includes non-existent path

    "/opt/local/x86_64-w64-mingw32/include/SDL2"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```
**Additional context**
I build the project on Windows,why cmake gives a linux-like include path?

**Comment by dg0yt** [comment]
> Compiler: MinGW-w64 with CMake
> `./vcpkg install sdl2:x64-windows`

`x64-windows` does not use MinGW-w64.

**Comment by dg0yt** [comment]
> 2\. set Clion CMake Option with vcpkg toolchain

Don't forget to also set the triplet and host triplet.

**Comment by JackBoosY** [comment]
Is this resolved?

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated in 3 months, if it is still an issue, please reopen this issue.
