### ISSUE TITLE
Support C++17 features in Catch2

### ISSUE THREAD

**Issue by davidmatson** [microsoft/vcpkg#25236]
Does the Catch2 port support compiling with C++17 features enabled?

For example:
```c++
inline std::string_view test()
{
    throw std::runtime_error{"bad"};
}

TEST_CASE("Log exception")
{
    REQUIRE(test() == "good");
}
```

I get a linker error when using catch2 v3.0.1 but not when using v2.*.

Note that Catch2 compiles with C++14 by default.

For more context, see:
https://github.com/catchorg/Catch2/issues/2046
https://github.com/catchorg/Catch2/issues/2210

Is some kind of feature switch needed, or should the port just always use C++17?

**Comment by Cheney-W** [comment]
We do not accept adding c/cxx standard as a feature.
See https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-use-features-to-control-alternatives-in-published-interfaces

**Comment by davidmatson** [comment]
What is the recommended solution to provide a port that "just works" for consumers on C++17 or higher? The abseil[cxx17] technique from the linked page?

**Comment by davidmatson** [comment]
I'm looking for a way that doesn't require using a port overlay (or patch on top of the vcpkg repo). What's the current best solution in vcpkg? (Perhaps there's a larger vcpkg feature ask here.)

**Comment by Cheney-W** [comment]
The best way is to let upstream itself set the default language standard to c++17.

**Comment by davidmatson** [comment]
Upstream intentionally supports back to C++14, as documented in their About section here:
https://github.com/catchorg/Catch2

How do other upstream libraries handle supporting older C++ versions?
Suppose a project wants to support compiling with both the latest C++ standard or with older versions, and "just work" either way. Is that possible to do with vcpkg?

**Comment by Cheney-W** [comment]
> Suppose a project wants to support compiling with both the latest C++ standard or with older versions, and "just work" either way. Is that possible to do with vcpkg?

It is their freedom to use that language standard upstream, vcpkg does not make any restrictions on this. 
If some users need to use some specific language standards, they can either report their requirements to the upstream, or use the [overlay ports](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md) feature of vcpkg to customize the ports they need locally.

**Comment by davidmatson** [comment]
Does vcpkg support projects that offer compilation with multiple language versions, with a lower minimum but more features on more recent versions?

**Comment by davidmatson** [comment]
> If the port itself supports the use of different language standards under different conditions, then vcpkg supports such a port using different conditions as its own feature.

In that case, can we add a c++17 feature to the catch2 port? (Or am I misunderstanding your reply?)

**Comment by Cheney-W** [comment]
Are there explicit conditions in the cmakelists.txt provided by upstrem to control the use of c++17 or c++14?

**Comment by davidmatson** [comment]
Not that I see, though I'm not a CMake expert:
https://github.com/catchorg/Catch2/blob/devel/src/CMakeLists.txt

What would upstream need to do for vcpkg to support a c++17 feature for it?

**Comment by Cheney-W** [comment]
Could you please submit a PR for this issue?
We can judge whether it conforms to the specification according to the actual modification of the PR.

**Comment by dg0yt** [comment]
There is #25019.
And there is discussion in #24762.
