### ISSUE TITLE
[CPR]  Update to 1.8.3 (again, see details)

### ISSUE THREAD

**Issue by Binary-System** [microsoft/vcpkg#25237]
Library name: CPR

New version number: 1.8.3

Other information that may be useful:
1.8.3 is currently included but there where features added to 1.8.3 after the inclusion into vcpkg. (Like ReserveSize and others)

**Comment by JonLiu1993** [comment]
@Binary-System ,Thanks for posting this issue, when the next release version pubilsh, I will update this port.

**Comment by JonLiu1993** [comment]
Duplicate of #25833
