### ISSUE TITLE
[getopt-win32] Build error

### ISSUE THREAD

**Issue by probit2011** [microsoft/vcpkg#25243]
Hi,

I have been trying to install getopt.h (getopt) via vcpkg, after following the instructions on the webpage. However, it fails because it also tries to install getopt-win32, which I did not ask. You will find below the output from the request and the failure log attached.

![image](https://user-images.githubusercontent.com/44330046/173754754-1a32d697-65d6-4c14-b3ae-470be05028ba.png)

[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/8906314/config-x86-windows-out.log)

Could you please help me make sense of this (this should have been a fairly seamless transaction...). Also, could you please tell me what I should have written to ensure that vcpkg installs 'getopt' only.

Thanks in advance.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. There are error `--mt=CMAKE_MT-NOTFOUND` in your log. Please according to this comment https://github.com/microsoft/vcpkg/issues/21580#issuecomment-975929352 to resolve this problem. 
In addition, `getopt-win32` is dependency of `getopt`, installing `getopt` need first install `getopt-win32`.

**Comment by probit2011** [comment]
Hi @LilyWangLL ,

I followed the same actions as in https://github.com/microsoft/vcpkg/issues/21580#issuecomment-975929352 (see my screenshot), but I obtain the same error message and result. What else have I missed?

![image](https://user-images.githubusercontent.com/44330046/173766014-80f356b0-5eb3-4a24-9e1c-7f2d66d5ec45.png)

**Comment by LilyWangLL** [comment]
Did you install English Language package in your Visual Studio Installer?

**Comment by probit2011** [comment]
Yes, the Community version in English language. No other languages installed.

**Comment by probit2011** [comment]
Also, I tried to install the nlohmann-json package via vcpkg, and obtained similar results (see below). It appears that it managed to install a different CMake, but it failed when it tried to install the JSON package.

![image](https://user-images.githubusercontent.com/44330046/173942717-c045b833-612b-4da7-b07c-4ed30730284d.png)

**Comment by LilyWangLL** [comment]
I feel confused, could you test clone a new vcpkg and install this port again? I can't confirm the Visual Studio setting sync up to your vcpkg or not.😵

**Comment by probit2011** [comment]
Hi,

I re-cloned vcpkg, ran the bootstrap-vcpkg.bat, integrated vcpkg into VS (vcpkg integrate install) and tried again to run 'vcpkg install getopt'. I obtained the same error message/output.

I noticed that some things might have gone wrong during the cloning. Please find attached the CMakeError and CMakeOutput file as found in the /ports/genann/out/build/x64-Debug/CMakeFiles folder. Maybe they contain some clues about why this is going wrong?

[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/8915550/CMakeOutput.log)
[CMakeError.log](https://github.com/microsoft/vcpkg/files/8915551/CMakeError.log)

**Comment by LilyWangLL** [comment]
There is a same issue on CMake, you can try the solution from https://gitlab.kitware.com/cmake/cmake/-/issues/19054.

**Comment by probit2011** [comment]
I already have Windows 10 SDK (10.0.19041.0) installed, which is the most recent SDK available. Surely, I don't have to also install older versions (e.g. 10.0.18362.0, 10.017763.0, etc.)?

I am that close to give up coding using VS, too many unnecessary hurdles...

**Comment by JackBoosY** [comment]
@probit2011 Can you please provide the full Visual Studio component list which you installed?

**Comment by probit2011** [comment]
![image](https://user-images.githubusercontent.com/44330046/174011934-8eb13693-3dc9-4010-83e7-04f6d39428b5.png)
![image](https://user-images.githubusercontent.com/44330046/174012020-9795339e-10e5-4820-b7e3-d08f1d777fc0.png)
![image](https://user-images.githubusercontent.com/44330046/174012082-19d49d27-c554-4255-be2f-de89c48d6ea3.png)
![image](https://user-images.githubusercontent.com/44330046/174012170-bea87a1f-a636-4be7-bb15-145b54e162f0.png)
![image](https://user-images.githubusercontent.com/44330046/174012337-82e902fe-367d-43f2-a331-8aafb5244242.png)
![image](https://user-images.githubusercontent.com/44330046/174012416-9e527354-79f8-4d3b-b826-698c8018e5a8.png)
![image](https://user-images.githubusercontent.com/44330046/174012479-0c88ee7f-349f-4812-8d6c-362f23abde0e.png)

**Comment by JackBoosY** [comment]
> I already have Windows 10 SDK (10.0.19041.0) installed, which is the most recent SDK available. Surely, I don't have to also install older versions (e.g. 10.0.18362.0, 10.017763.0, etc.)?
> 
> I am that close to give up coding using VS, too many unnecessary hurdles...

The Windows SDK you installed may not have its path added to the registry correctly, causing Visual Studio to not be able to find it correctly.
Please reinstall it with administrator privileges.

**Comment by Kamrulhasan12345** [comment]
I am sorry for interrupting. I installed getopt in vcpkg successfully, but whenever I try to do `cmake --build ./`, I see `unresolved external symbol __imp_getopt_a referenced in function main` errors. I know that the library is not linked so that's showing. I also tried adding getopt o `target_link_libraries`, but shows me, `cannot open file 'getopt.lib'` errors when I try to build in msvc.

Can you please tell me any way to use getopt ang getopt-win32 in cmake with vcpkg?

**Comment by Kamrulhasan12345** [comment]
Phew! I found it working with this:
```cmake
find_library(GETOPT_LIB getopt)

target_link_libraries(your_target PRIVATE ${GETOPT_LIB} ...)
```

**Comment by JackBoosY** [comment]
@Kamrulhasan12345 That's a usage issue, please open a new issue to report that.

Thanks.
