### ISSUE TITLE
[redis-plus-plus] Support async interface with features

### ISSUE THREAD

**Issue by elmanelman** [microsoft/vcpkg#25248]
**Is your feature request related to a problem? Please describe.**
For now it isn't possible to choose whether to install and build async part of redis-plus-plus with vcpkg. These features are enabled with cmake variables: `REDIS_PLUS_PLUS_BUILD_ASYNC=libuv` and, optionally, `REDIS_PLUS_PLUS_ASYNC_FUTURE=boost`, if you want to use `boost::future` instead of `std::future`.

**Proposed solution**
Add library features that, being selected, will set `...BUILD_ASYNC` and `...ASYNC_FUTURE` variables.

For instance, `redis-plus-plus[async]` (or `[async-std]`) could set `...BUILD_ASYNC=libuv` only, and `redis-plus-plus[async-boost]` could set both `...BUILD_ASYNC=libuv` and `...ASYNC_FUTURE=boost`.

**Describe alternatives you've considered**
I couldn't find any other concise ways to solve this.

**Comment by JackBoosY** [comment]
According to our policy, we refuse to accept adding conflicting features. So do you need `std` or `boost`?

**Comment by JackBoosY** [comment]
Which boost components is required by `async-futures-boost`?

**Comment by JackBoosY** [comment]
@elmanelman According to [our doc](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-use-features-to-implement-alternatives), we can only pick one feature, `std` or `boost`.

**Comment by elmanelman** [comment]
Hmm, I got it and think we can leave `async` & `async-std` for now, as you implemented in https://github.com/microsoft/vcpkg/pull/25272. 

But what is the right way to give a choice between `std` and `boost` futures?

**Comment by JackBoosY** [comment]
If you need to use `async-futures-boost`, you may need to modify vcpkg.json(add feature and add dependency items boost components) and portfile.cmake(check the feature whether it's enabled and set `-DREDIS_PLUS_PLUS_ASYNC_FUTURE=boost` to `vcpkg_configure_make` to enable it) using overlay port feature.
See https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md.

**Comment by elmanelman** [comment]
Awesome, thanks!
