### ISSUE TITLE
The Sqlite3 package should also install the sqlite3.exe command line tool

### ISSUE THREAD

**Issue by nerdile** [Microsoft/vcpkg#2526]
The sqlite3.exe command line shell is very helpful when learning or using sqlite3. The shell source comes with the amalgamated source drop.

I've created a PR #2525  showing how this could be added and installed.  Would there be any concerns with adding this tool to the sqlite3 port?

Thanks,
Daniel

**Comment by pravic** [comment]
Since @2525 was merged, it is worth to close this issue :)

**Comment by JackBoosY** [comment]
Hi @nerdile , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
