### ISSUE TITLE
[poppler] Add glib support

### ISSUE THREAD

**Issue by Febbe** [microsoft/vcpkg#25266]
****

The poppler port lacks the glib bindings. Adding poppler[glib] would help.

**Proposed solution**
Adding poppler[glib]

**Describe alternatives you've considered**
Self compiling and adding it to the path.

**Comment by Febbe** [comment]
Another thing: why is poppler in the namespace "unofficial::". When searching package manager independent, this will lead to a conflict. find_package(poppler) vs find_package(unofficial-poppler)

**Comment by dg0yt** [comment]
> why is poppler in the namespace "unofficial::". 

Only upstream can provide official config. The unofficial config is a vcpkg polyfill. Vcpkg maintainers cannot know how upstream would design its package (package name, variable names, target names).

> When searching package manager independent, this will lead to a conflict. find_package(poppler) vs find_package(unofficial-poppler)

No, the unofficial:: namespace avoids a conflict. It requires a concious decision by the consumer whether to do tight coupling with vcpkg, or to use another mechanism. 
(Tight coupling is no problem within vcpkg, or in transitive dependencies of ports. Such as port `gdal` forwarding a depenency on poppler.)
