### ISSUE TITLE
Error in vcpkg_configure_meson.cmake

### ISSUE THREAD

**Issue by heretic13** [microsoft/vcpkg#25277]
**Describe the bug**
I am compiling wt library for NanoPi Neo board (http://nanopi.io/nanopi-neo.html) via vcpkg.
I use chroot+qemu+native gcc compiler on a powerful machine for this.
The build fails with an error on package "fontconfig".

**Environment**
- OS: Armbian 22.02.1 Jammy with Linux 5.15.25-sunxi
- CPU: Allwinner H3, Quad-core Cortex-A7 Up to 1.2GHz.   armv7l architecture
- Compiler: gcc version 10.2.1 20210110 (Debian 10.2.1-6)

**To Reproduce**
1. ./vcpkg install fontconfig
2. See error
`
CMake Error at scripts/cmake/vcpkg_configure_meson.cmake:238 (message):
  Unhandled machine: armv7l

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:345 (z_vcpkg_meson_generate_cross_file)
  ports/fontconfig/portfile.cmake:17 (vcpkg_configure_meson)
  scripts/ports.cmake:146 (include)
`

**Expected behavior**
Good build with not errors :)

**Failure logs**
-(please attached failure logs)

**Additional context**
If you look in the vcpkg_configure_meson.cmake file, then in lines 224-239 machine architecture is detected.
There is no ARM architecture listed (other than 64-bit).

And there is a comment
# https://github.com/mesonbuild/meson/blob/master/docs/markdown/Reference-tables.md#cpu-families

The link page lists a wide range of architectures. 32-bit ARM processors are there.

Looks like an error in the configuration file vcpkg_configure_meson.cmake

Why do I think this should be fixed?
Because the 32-bit ARM architecture lives on in millions of devices around the world.

**Comment by heretic13** [comment]
[stdout-arm-linux.log](https://github.com/microsoft/vcpkg/files/8919541/stdout-arm-linux.log)

**Comment by heretic13** [comment]
I think that the problem will arise with the installation of any port through vpckg if it uses meson in the process.

**Comment by Neumann-A** [comment]
`vcpkg_configure_meson` probably requires a similar escape hatch as `vcpkg_configure_make` for its build/target CPU selection
