### ISSUE TITLE
[vcpkg] Incorrect install failure message

### ISSUE THREAD

**Issue by JackBoosY** [microsoft/vcpkg#25270]
OS: Windows 10
vcpkg: commit 3d8f78171a2a37d461077bf8d063256b63e25a4f
vcpkg-tool: 2022-06-05
Visual Studio version: 2017

When install a port failed, the console shows (with option `--debug`):
```
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: F:/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: F:/vcpkg/buildtrees/redis-plus-plus/x86-windows-dbg
    See logs for more information:
      F:\vcpkg\buildtrees\redis-plus-plus\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:102 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/redis-plus-plus/portfile.cmake:38 (vcpkg_cmake_install)
  scripts/ports.cmake:146 (include)


[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 13928: cmd_execute_and_stream_data() returned 1 after  8567778 us
error: building redis-plus-plus:x86-windows failed with: BUILD_FAILED
Value was null
[DEBUG] F:\vcpkg-tool\vcpkg-tool\src\vcpkg\build.cpp(1652):
[DEBUG] Time in subprocesses: 10386355 us
[DEBUG] Time in parsing JSON: 334312 us
[DEBUG] Time in JSON reader: 265495 us
[DEBUG] Time in filesystem: 327636 us
[DEBUG] Time in loading ports: 978594 us
[DEBUG] Exiting after 12.49 s (12484542 us)
```
Related code: https://github.com/microsoft/vcpkg-tool/blob/b0f08e40f8e8752dd0b260138ee078bd9599559c/src/vcpkg/build.cpp#L1652
```cpp
        const auto& compiler_info = abi_info.compiler_info.value_or_exit(VCPKG_LINE_INFO);
```
It seems that `abi_info.compiler_info` is a null pointer.

I can't reproduce this with the latest vcpkg-tool commit on my VS2019 machine. But still reproducible on VS2017 machine using vcpkg.exe built on VS2019 machine.

cc @BillyONeal

**Comment by autoantwort** [comment]
What is the command that you have executed?

**Comment by BillyONeal** [comment]
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/1544943/174133155-679754f9-5e0b-42d9-9626-fb9cdd19e3d0.png">
No repro for me

**Comment by JackBoosY** [comment]
@BillyONeal Yeah that's weird.

**Comment by autoantwort** [comment]
@JackBoosY Do you still have this issue?

**Comment by JackBoosY** [comment]
> @JackBoosY Do you still have this issue?

Currently no.

**Comment by Cheney-W** [comment]
We haven't been able to reproduce this, if more information comes up, or this issue appears again, please reopen.

**Comment by sidharthsudheer20** [comment]
<img width="1416" alt="Screenshot 2023-06-22 at 11 44 29 AM" src="https://github.com/microsoft/vcpkg/assets/72302924/deee28bf-d4f8-47b2-abb9-f96cf90067dd">
Hi,I'm getting the same error.

i'm trying to build folly library in ppc64le machine
OS: Ubuntu 22.04
vcpkg-tool:  2999-12-31

**Comment by autoantwort** [comment]
No you got https://github.com/microsoft/vcpkg/issues/31908 :)

**Comment by autoantwort** [comment]
No you probably got https://github.com/microsoft/vcpkg/issues/31908 :)

**Comment by BillyONeal** [comment]
> No you probably got #31908 :)

This is 1512 not 889 so I suspect it's a different bug, but the fix for that might fix it
