### ISSUE TITLE
[rtmidi] Build error

### ISSUE THREAD

**Issue by itmuckel** [microsoft/vcpkg#25279]
**Host Environment**
- OS: Windows 10
- Compiler: mingw g++ x64 in msys2

**To Reproduce**
I used CLion with this CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.22)

set(VCPKG_BUILD_TYPE release)
set(VCPKG_TARGET_TRIPLET x64-mingw-dynamic)

project(oud)

set(CMAKE_CXX_STANDARD 17)

find_package(RtAudio CONFIG REQUIRED)
find_package(RtMidi CONFIG REQUIRED)

add_executable(oud main.cpp)
target_link_libraries(oud PRIVATE RtAudio::rtaudio)
```

and this is my vcpkg.json
```json
{
  "name": "oud",
  "version-string": "0.1.0",
  "dependencies": [
    "rtaudio",
    "rtmidi"
  ]
}
```

**Failure logs**
In `D:\vcpkg\buildtrees\rtmidi\install-x64-mingw-dynamic-dbg-out.log`
```
[1/4] C:\msys64\mingw64\bin\x86_64-w64-mingw32-g++.exe -DRTMIDI_EXPORT -D__RTMIDI_DEBUG__ -D__WINDOWS_MM__ -ID:/vcpkg/buildtrees/rtmidi/src/8debb9376a-c9eae017fc.clean -Wall -Werror -g -std=c++11 -MD -MT CMakeFiles/rtmidi.dir/rtmidi_c.cpp.obj -MF CMakeFiles\rtmidi.dir\rtmidi_c.cpp.obj.d -o CMakeFiles/rtmidi.dir/rtmidi_c.cpp.obj -c D:/vcpkg/buildtrees/rtmidi/src/8debb9376a-c9eae017fc.clean/rtmidi_c.cpp
[2/4] C:\msys64\mingw64\bin\x86_64-w64-mingw32-g++.exe -DRTMIDI_EXPORT -D__RTMIDI_DEBUG__ -D__WINDOWS_MM__ -ID:/vcpkg/buildtrees/rtmidi/src/8debb9376a-c9eae017fc.clean -Wall -Werror -g -std=c++11 -MD -MT CMakeFiles/rtmidi.dir/RtMidi.cpp.obj -MF CMakeFiles\rtmidi.dir\RtMidi.cpp.obj.d -o CMakeFiles/rtmidi.dir/RtMidi.cpp.obj -c D:/vcpkg/buildtrees/rtmidi/src/8debb9376a-c9eae017fc.clean/RtMidi.cpp
FAILED: CMakeFiles/rtmidi.dir/RtMidi.cpp.obj 
C:\msys64\mingw64\bin\x86_64-w64-mingw32-g++.exe -DRTMIDI_EXPORT -D__RTMIDI_DEBUG__ -D__WINDOWS_MM__ -ID:/vcpkg/buildtrees/rtmidi/src/8debb9376a-c9eae017fc.clean -Wall -Werror -g -std=c++11 -MD -MT CMakeFiles/rtmidi.dir/RtMidi.cpp.obj -MF CMakeFiles\rtmidi.dir\RtMidi.cpp.obj.d -o CMakeFiles/rtmidi.dir/RtMidi.cpp.obj -c D:/vcpkg/buildtrees/rtmidi/src/8debb9376a-c9eae017fc.clean/RtMidi.cpp
D:/vcpkg/buildtrees/rtmidi/src/8debb9376a-c9eae017fc.clean/RtMidi.cpp: In member function 'virtual void MidiInWinMM::openPort(unsigned int, const std::string&)':
D:/vcpkg/buildtrees/rtmidi/src/8debb9376a-c9eae017fc.clean/RtMidi.cpp:2731:20: error: comparison of integer expressions of different signedness: 'int' and 'unsigned int' [-Werror=sign-compare]
 2731 |   for ( int i=0; i < inputData_.bufferCount; ++i ) {
      |                  ~~^~~~~~~~~~~~~~~~~~~~~~~~
D:/vcpkg/buildtrees/rtmidi/src/8debb9376a-c9eae017fc.clean/RtMidi.cpp: In member function 'virtual void MidiInWinMM::closePort()':
D:/vcpkg/buildtrees/rtmidi/src/8debb9376a-c9eae017fc.clean/RtMidi.cpp:2785:22: error: comparison of integer expressions of different signedness: 'int' and 'std::vector<midihdr_tag*>::size_type' {aka 'long long unsigned int'} [-Werror=sign-compare]
 2785 |     for ( int i=0; i < data->sysexBuffer.size(); ++i ) {
      |                    ~~^~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus.exe: all warnings being treated as errors
ninja: build stopped: subcommand failed.
```

**Additional context**
I think the problem is that it compiles with -Werror. Of course the dependency itself shouldn't have warnings, but I just want to use it, not debug it. Is this something that needs to be fixed here? Can I tell vcpkg to compile a dependency without Werror? Should I open an issue at RtMidi Repo?

**Comment by Thomas1664** [comment]
This doesn't work; you're building release and debug versions:

```cmake
set(VCPKG_BUILD_TYPE release)
set(VCPKG_TARGET_TRIPLET x64-mingw-dynamic)
```

You have to set `VCPKG_BUILD_TYPE release` in the triplet file. My suggestion is to copy the triplet file for `x64-mingw-dynamic` rename the copy to `x64-mingw-dynamic-release` and do `set(VCPKG_BUILD_TYPE release)` in there.

This way you get rid of `-Werror`

**Comment by itmuckel** [comment]
While that workaround made the build work, the executable now exits with `Process finished with exit code -1073741515 (0xC0000135)` and doesn't do anything (it played a note before until I pressed a key). Also I don't even link rtmidi, only rtaudio.

**Comment by Thomas1664** [comment]
> Can I tell vcpkg not to pass -Werror when building the dependency rtmidi?

This problem isn't related to vcpkg but to upstream itself. They pass `-Werror` on debug builds when `CMAKE_COMPILER_IS_GNUCXX` is true. However, it is possible to add a patch that disables this behaviour. 

> While that workaround made the build work, the executable now exits with Process finished with exit code -1073741515 (0xC0000135) and doesn't do anything (it played a note before until I pressed a key). Also I don't even link rtmidi, only rtaudio.

It seems like `rtmidi` won't work on mingw in general. Please open an issue on the upstream project `rtmidi` and ask them to support mingw.
