### ISSUE TITLE
Installing packages in manifest mode from the command line vs. MSBuild appears to use different "installed" folders.

### ISSUE THREAD

**Issue by bkuhns** [microsoft/vcpkg#25281]
**Describe the bug**
In manifest mode, `vcpkg install` and running a build through MSBuild install packages in different folders.

**Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019 16.11.16

**To Reproduce**
Define a vcpkg.json manifest file with at least one dependency.
1. Run `./vcpkg install` from a command line.
2. Then build a .vcxproj project under the same path as the manifest file through MSBuild.

**Expected behavior**
Since `vcpkg install` was already run manually, I expect the build through MSBuild to detect the installed packages and continue without re-installing the packages.

**Observed behavior**
Instead, the subsequent MSBuild build will pull the packages and install them again, but in a different location on disk.

**Additional Context**
Running `vcpkg install` seems to install packages in `./vcpkg_installed/x86-windows/` but when running through MSBuild, the installed packages are duplicated under `./vcpkg_installed/x86-windows/x86-windows/`.

**Workaround**
I applied the following change and now vcpkg behaves as defined in the above "expected behavior":
```
--- a/scripts/buildsystems/msbuild/vcpkg.targets
+++ b/scripts/buildsystems/msbuild/vcpkg.targets
@@ -51,7 +51,7 @@
   <Choose>
     <When Condition="'$(VcpkgEnableManifest)' == 'true'">
       <PropertyGroup>
-        <_ZVcpkgInstalledDir Condition="'$(_ZVcpkgInstalledDir)' == ''">$(_ZVcpkgManifestRoot)vcpkg_installed\$(VcpkgTriplet)\</_ZVcpkgInstalledDir>
+        <_ZVcpkgInstalledDir Condition="'$(_ZVcpkgInstalledDir)' == ''">$(_ZVcpkgManifestRoot)vcpkg_installed\</_ZVcpkgInstalledDir>
       </PropertyGroup>
     </When>
     <Otherwise>
```

**Comment by bkuhns** [comment]
> This is intended behavior. See [#23023 (review)](https://github.com/microsoft/vcpkg/pull/23023#pullrequestreview-878288016)

Very strange. Is there an explanation for why the `vcpkg install` command does it differently, then?

**Comment by autoantwort** [comment]
The msbuild integration only uses a custom installation folder via `vcpkg install --x-install-root=...`

**Comment by bkuhns** [comment]
So the stance is that it's unreasonable to expect running `vcpkg install` from the command line under a project directory and building that project with MSBuild will use the same packages?

**Comment by autoantwort** [comment]
It would be nice. But it is not possible to achieve. See https://github.com/microsoft/vcpkg/pull/23023#pullrequestreview-878288016. Otherwise multi config VS Solutions will fail because they try to install multiple triplets in the same installed folder which is not possible.

**Comment by bkuhns** [comment]
I read that entire thread but the details are lost on me. I'm only a (fairly recent) user of vcpkg and only recently moved to "manifest mode" because I needed versioning. I don't understand the point "try to install multiple triplets in the same installed folder". Why wouldn't it do the same thing as the command line? If I pick `Debug|x86`, then use `vcpkg_installed/x86-windows`. If I pick `Debug|x64` then use `vcpkg_installed/x64-windows`. I don't see the problem?

I don't mean to sound standoffish, I just genuinely don't understand the explanation in the PR review. As a naive user, it seems intuitive to expect `vcpkg install` and building my project to do the same thing. I would like a dev environment with all the third party libraries already installed without yet running the build of my own product so I have a good "reset point" if I need it.

If I wanted to mimic the MSBuild behavior, should I then run `vcpkg install --x-install-root=vcpkg_installed\x86-windows` instead?

**Comment by autoantwort** [comment]
>  I don't understand the point "try to install multiple triplets in the same installed folder". Why wouldn't it do the same thing as the command line?

Because the definition of manifest mode is "Install the ports given in the vcpkg.json file for the given triplet into the installation folder and remove everything else"

> If I wanted to mimic the MSBuild behavior, should I then run vcpkg install --x-install-root=vcpkg_installed\x86-windows instead?

Yes

**Comment by bkuhns** [comment]
The response isn't satisfying (still feels **very** unintuitive), but I have a command to reproduce the same environment as running through MSBuild. So, I'm reluctantly closing this issue.
