### ISSUE TITLE
[icu] Build error

### ISSUE THREAD

**Issue by RyotaWatanabe327** [microsoft/vcpkg#25287]
git clone https://github.com/microsoft/vcpkg
cd vcpkg
./bootstrap-vcpkg.bat
./vcpkg install colmap [cuda, tests]: x64-windows

I ran the installation with the above command, but got an error(reference image).

I got the same error when I installed only icu: x64-windows by next command.
./vcpkg install icu: x64-windows

How do you get all the installation done smartly?
![コメント 2022-06-17 151043](https://user-images.githubusercontent.com/107600328/174236289-799ed966-db61-4d98-b84a-e49de456bfbd.png)

**Comment by JackBoosY** [comment]
Can you please provide the failure logs mentioned in the output?

Thanks.

**Comment by JackBoosY** [comment]
```
/usr/bin/install: cannot remove 'C:/Users/4044561/Desktop/work/vcpkg/packages/icu_x64-windows/C/Users/4044561/Desktop/work/vcpkg/installed/x64-windows/debug/lib/icudtd71.dll': Permission denied
```
Please clone vcpkg in non-system disk or run install command with administrator privileges.

**Comment by RyotaWatanabe327** [comment]
I run Windows PowerShell as administrator and run install command.
Is it a different way?

**Comment by JackBoosY** [comment]
Maybe related to your installed anti-virus but I can't guarantee that.

**Comment by dg0yt** [comment]
> Please clone vcpkg in non-system disk or run install command with administrator privileges.

I don't think the latter is a good idea.

**Comment by RyotaWatanabe327** [comment]
It is necessary to install packages(cuda) related gpu to PC.
I want to install it on the PC.Do you recommend the former?

**Comment by JackBoosY** [comment]
@RyotaWatanabe327 Yes.

**Comment by RyotaWatanabe327** [comment]
> > Please clone vcpkg in non-system disk or run install command with administrator privileges.
> 
> I don't think the latter is a good idea.

Could you tell me that?

**Comment by JackBoosY** [comment]
@RyotaWatanabe327 Please close this issue if it's resolved.

**Comment by ooeygui** [comment]
This still reproduces, both previous release tag and current master running an admin command prompt with vs2022.
`make[1]: ./../src/c-71_1-src-08c83f7de1.clean/source/install-sh: No such file or directory`

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8981583/install-x64-windows-dbg-out.log)
[install-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/8981584/install-x64-windows-dbg-err.log)

**Comment by JackBoosY** [comment]
@ooeygui Your issue should be the same with https://github.com/microsoft/vcpkg/issues/23323.
