### ISSUE TITLE
BUILD_FAILED in  boost-regex:x64-windows with space in the path

### ISSUE THREAD

**Issue by Roman-Koshelev** [Microsoft/vcpkg#2528]
D:\Program Files (x86)\vcpkg-master>.\vcpkg.exe install boost:x64-windows
The following packages will be built and installed:
    boost[core]:x64-windows
  * boost-accumulators[core]:x64-windows
  * boost-algorithm[core]:x64-windows
  * boost-align[core]:x64-windows
  * boost-any[core]:x64-windows
  * boost-asio[core]:x64-windows
  * boost-assign[core]:x64-windows
  * boost-atomic[core]:x64-windows
  * boost-beast[core]:x64-windows
  * boost-bimap[core]:x64-windows
  * boost-callable-traits[core]:x64-windows
  * boost-chrono[core]:x64-windows
  * boost-circular-buffer[core]:x64-windows
  * boost-compute[core]:x64-windows
  * boost-container[core]:x64-windows
  * boost-context[core]:x64-windows
  * boost-conversion[core]:x64-windows
  * boost-convert[core]:x64-windows
  * boost-coroutine[core]:x64-windows
  * boost-coroutine2[core]:x64-windows
  * boost-crc[core]:x64-windows
  * boost-date-time[core]:x64-windows
  * boost-disjoint-sets[core]:x64-windows
  * boost-dll[core]:x64-windows
  * boost-dynamic-bitset[core]:x64-windows
  * boost-endian[core]:x64-windows
  * boost-exception[core]:x64-windows
  * boost-fiber[core]:x64-windows
  * boost-filesystem[core]:x64-windows
  * boost-flyweight[core]:x64-windows
  * boost-foreach[core]:x64-windows
  * boost-format[core]:x64-windows
  * boost-geometry[core]:x64-windows
  * boost-gil[core]:x64-windows
  * boost-graph[core]:x64-windows
  * boost-graph-parallel[core]:x64-windows
  * boost-hana[core]:x64-windows
  * boost-heap[core]:x64-windows
  * boost-icl[core]:x64-windows
  * boost-interprocess[core]:x64-windows
  * boost-interval[core]:x64-windows
  * boost-intrusive[core]:x64-windows
  * boost-io[core]:x64-windows
  * boost-iostreams[core]:x64-windows
  * boost-lambda[core]:x64-windows
  * boost-lexical-cast[core]:x64-windows
  * boost-local-function[core]:x64-windows
  * boost-locale[core]:x64-windows
  * boost-lockfree[core]:x64-windows
  * boost-log[core]:x64-windows
  * boost-logic[core]:x64-windows
  * boost-math[core]:x64-windows
  * boost-metaparse[core]:x64-windows
  * boost-mp11[core]:x64-windows
  * boost-mpi[core]:x64-windows
  * boost-msm[core]:x64-windows
  * boost-multi-array[core]:x64-windows
  * boost-multi-index[core]:x64-windows
  * boost-multiprecision[core]:x64-windows
  * boost-numeric-conversion[core]:x64-windows
  * boost-odeint[core]:x64-windows
  * boost-parameter[core]:x64-windows
  * boost-phoenix[core]:x64-windows
  * boost-poly-collection[core]:x64-windows
  * boost-polygon[core]:x64-windows
  * boost-pool[core]:x64-windows
  * boost-process[core]:x64-windows
  * boost-program-options[core]:x64-windows
  * boost-property-map[core]:x64-windows
  * boost-property-tree[core]:x64-windows
  * boost-proto[core]:x64-windows
  * boost-ptr-container[core]:x64-windows
  * boost-python[core]:x64-windows
  * boost-qvm[core]:x64-windows
  * boost-random[core]:x64-windows
  * boost-range[core]:x64-windows
  * boost-ratio[core]:x64-windows
  * boost-rational[core]:x64-windows
  * boost-regex[core]:x64-windows
  * boost-scope-exit[core]:x64-windows
  * boost-serialization[core]:x64-windows
  * boost-signals[core]:x64-windows
  * boost-signals2[core]:x64-windows
  * boost-sort[core]:x64-windows
  * boost-spirit[core]:x64-windows
  * boost-stacktrace[core]:x64-windows
  * boost-statechart[core]:x64-windows
  * boost-system[core]:x64-windows
  * boost-test[core]:x64-windows
  * boost-thread[core]:x64-windows
  * boost-timer[core]:x64-windows
  * boost-tokenizer[core]:x64-windows
  * boost-tti[core]:x64-windows
  * boost-type-erasure[core]:x64-windows
  * boost-ublas[core]:x64-windows
  * boost-units[core]:x64-windows
  * boost-unordered[core]:x64-windows
  * boost-uuid[core]:x64-windows
  * boost-variant[core]:x64-windows
  * boost-vmd[core]:x64-windows
  * boost-wave[core]:x64-windows
  * boost-winapi[core]:x64-windows
  * boost-xpressive[core]:x64-windows
  * bzip2[core]:x64-windows
  * python3[core]:x64-windows
  * zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/106: boost-regex:x64-windows
Building package boost-regex:x64-windows...
-- CURRENT_INSTALLED_DIR=D:/Program Files (x86)/vcpkg-master/installed/x64-windows
-- DOWNLOADS=D:/Program Files (x86)/vcpkg-master/downloads
-- CURRENT_PACKAGES_DIR=D:/Program Files (x86)/vcpkg-master/packages/boost-regex_x64-windows
-- CURRENT_BUILDTREES_DIR=D:/Program Files (x86)/vcpkg-master/buildtrees/boost-regex
-- CURRENT_PORT_DIR=D:/Program Files (x86)/vcpkg-master/ports/boost-regex/.
-- Using cached D:/Program Files (x86)/vcpkg-master/downloads/boostorg-regex-boost-1.66.0.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Building x64-windows-rel
CMake Error at D:/Program Files (x86)/vcpkg-master/scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: D:/Program Files (x86)/vcpkg-master/installed/x64-windows/tools/boost-build/b2.exe;--stagedir=D:/Program Files (x86)/vcpkg-master/buildtrees/boost-regex/x64-windows-rel/stage;--build-dir=D:/Program Files (x86)/vcpkg-master/buildtrees/boost-regex/x64-windows-rel;--user-config=D:/Program Files (x86)/vcpkg-master/buildtrees/boost-regex/x64-windows-rel/user-config.jam;-j8;--debug-configuration;--debug-building;--debug-generators;--disable-icu;--ignore-site-config;--hash;-q;threadapi=win32;threading=multi;runtime-link=shared;link=shared;address-model=64;architecture=x86;toolset=msvc-14.1;variant=release;debug-symbols=on
    Working Directory: D:/Program Files (x86)/vcpkg-master/buildtrees/boost-regex/src/regex-boost-1.66.0
    See logs for more information:
      D:\Program Files (x86)\vcpkg-master\buildtrees\boost-regex\build-x64-windows-rel-out.log
      D:\Program Files (x86)\vcpkg-master\buildtrees\boost-regex\build-x64-windows-rel-err.log

Call Stack (most recent call first):
  D:/Program Files (x86)/vcpkg-master/installed/x64-windows/share/boost-vcpkg-helpers/boost-modular.cmake:174 (vcpkg_execute_required_process)
  D:/Program Files (x86)/vcpkg-master/ports/boost-regex/portfile.cmake:20 (boost_modular_build)
  D:/Program Files (x86)/vcpkg-master/scripts/ports.cmake:72 (include)

Error: Building package boost-regex:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-regex:x64-windows
  Vcpkg version: 0.0.100-unknownhash

Additionally, attach any relevant sections from the log files above.

![2018-01-08_02-32-01](https://user-images.githubusercontent.com/34384083/34655525-2e779d5e-f41c-11e7-80d7-d138f95a175d.png)

**Comment by Roman-Koshelev** [comment]
Success. ( Moved vcpkg in a directory name with no spaces. )

**Comment by alexkaratarakis** [comment]
The whitespace issue is now fixed (485c0aebf681f85ec6102d225baf7bdc772b2039).
