### ISSUE TITLE
[sdl2-image/mixer/net/ttf] Update to exported targets names.

### ISSUE THREAD

**Issue by FtZPetruska** [microsoft/vcpkg#25284]
****

## Description

Recently, a major CMake rework was done in the SDL2 subprojects, adding a consistent naming for the targets. Unfortunately, the naming chosen is inconsistent with the one used by vcpkg's ports.

The new naming consists in:
- The namespace `SDL2_XXX::` where `XXX` is the name of the subproject
- A static target `SDL2_XXX::SDL_XXX-static` linked to `SDL2::SDL2-static`
- A dynamic target `SDL2_XXX::SDL_XXX` linked to `SDL2::SDL2`

## Proposed solution

Adopt the naming chosen by the maintainers.

## Alternatives

To avoid breaking existing projects/ports, the targets currently in use by vcpkg could be kept as an alias of the new one with a deprecation message, similar to what is currently done in [SDL_ttf](https://github.com/libsdl-org/SDL_ttf/blob/fdb59157330bd0a8b0143d148a387823f2cc1c78/CMakeLists.txt#L401-L405).

## Additional context

Related PRs:
- https://github.com/libsdl-org/SDL_image/pull/238
- https://github.com/libsdl-org/SDL_mixer/pull/410
- https://github.com/libsdl-org/SDL_net/pull/48
- https://github.com/libsdl-org/SDL_ttf/pull/213

**Comment by FtZPetruska** [comment]
Hello, I just wanted to update you about the upstream CMake changes.

The new target names have been shipped in the following stable releases:
- SDL2_image: [version 2.6.x](https://github.com/libsdl-org/SDL_image/releases/tag/release-2.6.0)
- SDL2_mixer: [version 2.6.x](https://github.com/libsdl-org/SDL_mixer/releases/tag/release-2.6.0)
- SDL2_ttf: [version 2.20.x](https://github.com/libsdl-org/SDL_ttf/releases/tag/release-2.20.0)

In addition to the original issue, I noticed that the naming is also different between vcpkg's ports and the official releases when using `find_package`:
- vcpkg uses `sdl2-XXX`
- official releases use `sdl2_XXX`

**Comment by dg0yt** [comment]
Related: #25803
