### ISSUE TITLE
[New Port Request] Unity Test

### ISSUE THREAD

**Issue by ajpocus** [microsoft/vcpkg#25280]
Library name: Unity Test

Library description: Unity Test is a unit testing framework built for C, with a focus on working with embedded toolchains.

Source repository URL: https://github.com/ThrowTheSwitch/Unity

Project homepage (if different from the source repository): N/A

Anything else that is useful to know when adding (such as optional features the library may have that should be included): I'd be happy to open a PR to add Unity Test to the registry, if that's something the community agrees would be useful.

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
