### ISSUE TITLE
[wxwidgets] Build error

### ISSUE THREAD

**Issue by togisoft** [microsoft/vcpkg#25306]
**Host Environment**
- OS: [Linux Zorin OS]
- Compiler: g++ 11

**To Reproduce**
`vcpkg install wxwidgets`

**Failure logs**
error: building wxwidgets:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+wxwidgets
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[wxwidgets]+Build+error
Include '[wxwidgets] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-06-15-b0f08e40f8e8752dd0b260138ee078bd9599559c
    vcpkg-scripts version: 92136965a 2022-06-17 (27 minutes ago)

**Comment by autoantwort** [comment]
Please provide the error logs

**Comment by togisoft** [comment]
[stdout-x64-linux.log](https://github.com/microsoft/vcpkg/files/8933275/stdout-x64-linux.log)

**Comment by autoantwort** [comment]
And 
```
    See logs for more information:
      /opt/vcpkg/buildtrees/wxwidgets/config-x64-linux-dbg-out.log
      /opt/vcpkg/buildtrees/wxwidgets/config-x64-linux-dbg-err.log
```

**Comment by togisoft** [comment]
[config-x64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/8933279/config-x64-linux-dbg-err.log)
[config-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/8933280/config-x64-linux-dbg-out.log)

**Comment by dg0yt** [comment]
This is the error:
~~~
CMake Error at /opt/vcpkg/scripts/buildsystems/vcpkg.cmake:613 (_add_library):
  Target "wxgl" links to target "OpenGL::GLU" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
Call Stack (most recent call first):
  build/cmake/functions.cmake:413 (add_library)
  build/cmake/lib/gl/CMakeLists.txt:26 (wx_add_library)
~~~

**Comment by togisoft** [comment]
` sudo apt-get install freeglut3-dev`
I solved the problem with this. Thank you
