### ISSUE TITLE
[abseil] Link failure when using clang on Windows (unknown argument '-ignore:4221')

### ISSUE THREAD

**Issue by PigeonF** [microsoft/vcpkg#25300]
**Host Environment**
- OS: Windows x64
- Compiler: `cl` 19.32.31329, `clang` 14.0.5
- vcpkg: master (at the time of writing `91393faf123c4f1d22ef3dbfb4ec03531bac907a`)

**To Reproduce**
Install the `abseil` package and attempt to link it when using `clang`.

I have created a repository for reproduction: https://github.com/PigeonF/vcpkg-abseil-ignore-4221

**Failure logs**
See the readme of the linked repository. clang fails to link the executable, with the error `clang: error: unknown argument: '-ignore:4221'`

**Additional context**
This is the same issue as #13945.

I think the issue is that vcpkg builds abseil with `cl`, which leads to the `-ignore:4221` flag being added to the linkflags (https://github.com/abseil/abseil-cpp/blob/lts_2021_11_02/absl/copts/AbseilConfigureCopts.cmake#L55-L58), but the library is consumed from clang.

I do not know if this is an issue with abseil itself, the vcpkg port, or me "mixing" `clang` and `cl`.

As mentioned in the reproduction repository, the build is fixed if all references to `-ignore:4221` are removed from `vcpkg_installed\x64-windows\share\absl\abslTargets.cmake`

[config-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/8928964/config-x64-windows-rel-out.log)
[patch-x64-windows-0-out.log](https://github.com/microsoft/vcpkg/files/8928965/patch-x64-windows-0-out.log)
[config-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8928966/config-x64-windows-dbg-out.log)

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by wong-hao** [comment]
> I believe you shouldn't use triplet x64-windows when using clang on Windows because x64-windows uses msvc on Windows by default.

Sir so what should we use?

**Comment by JackBoosY** [comment]
I believe this issue should be fixed by the upstream since `-ignore:4221` is exported by the internal cmake.
