### ISSUE TITLE
[libusb] build failure:  autoreconf & libudev are installed but still requested by vcpkg

### ISSUE THREAD

**Issue by njk42** [microsoft/vcpkg#25302]
**Host Environment**
- OS: Ubuntu 18.04
- Compiler: gcc/g++ 7.5 

**To Reproduce**

Create a Docker image with the following:

              # Use the 18.04 ubuntu Image
              FROM ubuntu:bionic
              
              # install system tools
              RUN apt-get update && apt-get install -y g++ git curl zip unzip tar autoconf libudev-dev
              
              # install vcpkg
              RUN git clone https://github.com/Microsoft/vcpkg.git
              RUN ./vcpkg/bootstrap-vcpkg.sh
              RUN ./vcpkg/vcpkg integrate install

then start a container and execute:

              ./vcpkg/vcpkg install libusb

**Failure logs**
- Console output:

                Computing installation plan...
                A suitable version of cmake was not found (required v3.22.2). Downloading portable cmake v3.22.2...
                Downloading cmake...
                  https://github.com/Kitware/CMake/releases/download/v3.22.2/cmake-3.22.2-linux-x86_64.tar.gz -> /vcpkg/downloads/cmake-3.22.2linux-x86_64.tar.gz
                Extracting cmake...
                The following packages will be built and installed:
                    libusb[core]:x64-linux -> 1.0.26
                Detecting compiler hash for triplet "x64-linux"...
                Restored 0 packages from /root/.cache/vcpkg/archives in 9.898 us. Use --debug to see more details.
                Installing 1/1 libusb:x64-linux...
                Building libusb[core]:x64-linux...
                libusb currently requires the following tools and libraries from the system package manager:
                    autoreconf
                    libudev
                
                These can be installed on Ubuntu systems via apt-get install autoreconf libudev-dev
                -- Downloading https://github.com/libusb/libusb/archive/4239bc3a50014b8e6a5a2a59df1fff3b7469543b.tar.gz -> libusb-libusb-4239bc3a50014b8e6a5a2a59df1fff3b7469543b.tar.gz...
                -- Extracting source /vcpkg/downloads/libusb-libusb-4239bc3a50014b8e6a5a2a59df1fff3b7469543b.tar.gz
                -- Using source at /vcpkg/buildtrees/libusb/src/3b7469543b-a464ae495e.clean
                -- Getting CMake variables for x64-linux-dbg
                -- Getting CMake variables for x64-linux-rel
                -- Generating configure for x64-linux
                CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:83 (message):
                    Command failed: /usr/bin/autoreconf -vfi
                    Working Directory: /vcpkg/buildtrees/libusb/src/3b7469543b-a464ae495e.clean/
                    Error code: 1
                    See logs for more information:
                      /vcpkg/buildtrees/libusb/autoconf-x64-linux-err.log
                
                Call Stack (most recent call first):
                  scripts/cmake/vcpkg_configure_make.cmake:525 (vcpkg_execute_required_process)
                  ports/libusb/portfile.cmake:61 (vcpkg_configure_make)
                  scripts/ports.cmake:146 (include)
                
                
                error: building libusb:x64-linux failed with: BUILD_FAILED
                Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
                Then check for known issues at:
                    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libusb
                You can submit a new issue at:
                    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libusb]+Build+error
                Include '[libusb] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
                    vcpkg-tool version: 2022-06-15-b0f08e40f8e8752dd0b260138ee078bd9599559c
                    vcpkg-scripts version: 91393faf1 2022-06-16 (16 hours ago)
                
                You can also use the prefilled template from /vcpkg/installed/vcpkg/issue_body.md.
                

-Please attach any additional failure logs mentioned in the console output:

/vcpkg/buildtrees/libusb/autoconf-x64-linux-err.log contains the following:

                  autoreconf: Entering directory `.'
                  autoreconf: configure.ac: not using Gettext
                  autoreconf: running: aclocal --force -I m4
                  aclocal: warning: couldn't open directory 'm4': No such file or directory
                  autoreconf: configure.ac: tracing
                  autoreconf: configure.ac: not using Libtool
                  autoreconf: running: /usr/bin/autoconf --force
                  autoreconf: running: /usr/bin/autoheader --force
                  autoreconf: running: automake --add-missing --copy --force-missing
                  configure.ac:23: installing './compile'
                  configure.ac:26: installing './install-sh'
                  configure.ac:26: installing './missing'
                  Makefile.am: installing './INSTALL'
                  examples/Makefile.am: installing './depcomp'
                  libusb/Makefile.am:6: error: Libtool library used but 'LIBTOOL' is undefined
                  libusb/Makefile.am:6:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
                  libusb/Makefile.am:6:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
                  libusb/Makefile.am:6:   If 'LT_INIT' is in 'configure.ac', make sure
                  libusb/Makefile.am:6:   its definition is in aclocal's search path.
                  autoreconf: automake failed with exit status: 1

**Additional context**

I've seen this issue mentioned in several other closed tickets with no solutions other than "install autoconf and udev"... but I've already done that and it still doesn't work.  Hopefully the uber-simple approach above with a fresh OS install in a Docker container will help debugging efforts.

**Comment by njk42** [comment]
Related tickets are #20712, #18450, and #17796

**Comment by njk42** [comment]
Also tried the same process on the "devel" version of Ubuntu with gcc 11.3 and get the same error.

**Comment by njk42** [comment]
Update:   I also ran:

    apt-get install libtool
    apt-get install png-config

and the vcpkg install process seems to get a bit father but still errors with:

            CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:83 (message):
                Command failed: /usr/bin/bash -c "V=1 ./../src/3b7469543b-a464ae495e.clean/configure  \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"--prefix=/vcpkg/installed/x64-linux/debug\" \"--bindir=\\${prefix}/../tools/libusb/debug/bin\" \"--sbindir=\\${prefix}/../tools/libusb/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/libusb\""
                Working Directory: /vcpkg/buildtrees/libusb/x64-linux-dbg
                Error code: 1
                See logs for more information:
                  /vcpkg/buildtrees/libusb/config-x64-linux-dbg-out.log
                  /vcpkg/buildtrees/libusb/config-x64-linux-dbg-err.log

and the config-x64-linux-dbg-err.log shows:

          config.status: error: in `/vcpkg/buildtrees/libusb/x64-linux-dbg':
          config.status: error: Something went wrong bootstrapping makefile fragments
              for automatic dependency tracking.  If GNU make was not used, consider
              re-running the configure script with MAKE="gmake" (or whatever is
              necessary).  You can also try re-running configure with the
              '--disable-dependency-tracking' option to at least be able to build
              the package (albeit without support for automatic dependency tracking).


I hope someone can help solve this issue.  Thanks!

**Comment by JonLiu1993** [comment]
@njk42 ,Thanks for posting this issue, I can install libusb successfully:
````
test@test002:~/fix-bug/vcpkg$ ./vcpkg install libusb
Computing installation plan...
The following packages will be built and installed:
    libusb[core]:x64-linux -> 1.0.24#7
Detecting compiler hash for triplet "x64-linux"...
Restored 0 packages from /home/test/.cache/vcpkg/archives in 29.69 ms. Use --debug to see more details.
Installing 1/1 libusb:x64-linux...
Building libusb[core]:x64-linux...
libusb currently requires the following tools and libraries from the system package manager:
    autoreconf
    libudev

These can be installed on Ubuntu systems via apt-get install autoreconf libudev-dev
-- Downloading https://github.com/libusb/libusb/archive/c6a35c56016ea2ab2f19115d2ea1e85e0edae155.tar.gz -> libusb-libusb-c6a35c56016ea2ab2f19115d2ea1e85e0edae155.tar.gz...
-- Extracting source /home/test/fix-bug/vcpkg/downloads/libusb-libusb-c6a35c56016ea2ab2f19115d2ea1e85e0edae155.tar.gz
-- Using source at /home/test/fix-bug/vcpkg/buildtrees/libusb/src/5e0edae155-faf13d1dff.clean
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Generating configure for x64-linux
-- Finished generating configure for x64-linux
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Installing x64-linux-dbg
-- Building x64-linux-rel
-- Installing x64-linux-rel
-- Fixing pkgconfig file: /home/test/fix-bug/vcpkg/packages/libusb_x64-linux/lib/pkgconfig/libusb-1.0.pc
-- Fixing pkgconfig file: /home/test/fix-bug/vcpkg/packages/libusb_x64-linux/debug/lib/pkgconfig/libusb-1.0.pc
-- Installing: /home/test/fix-bug/vcpkg/packages/libusb_x64-linux/share/libusb/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: /home/test/.cache/vcpkg/archives/a6/a67f9751a872590cda721bb04ff11514d1be9603484385ed1beadb5c7154804f.zip
Elapsed time to handle libusb:x64-linux: 35.93 s

Total elapsed time: 43.63 s

The package libusb:x64-linux provides CMake targets:

    find_package(libusb CONFIG REQUIRED)
    target_include_directories(main PRIVATE ${LIBUSB_INCLUDE_DIRS})
    target_link_libraries(main PRIVATE ${LIBUSB_LIBRARIES})

test@test002:~/fix-bug/vcpkg$
````

Could you please provide '`config.log' ?

**Comment by njk42** [comment]
Thanks @JonLiu1993 for your reply.   Interesting that you are also getting the message about udev and autoreconf, but it doesn't appear to be fatal so perhaps it's unrelated to my issue.  

I also notice that your output does not start off with a download of cmake, and it's also installing libusb 1.0.24 rather than 1.0.26 which I'm trying to install, so there are other differences in our environments. 

I tried with cmake pre-installed (3.23.2) but this didn't fix my issue.

I don't know where to find 'config.log'...  I don't see it in buildtrees/libusb/ like the other log files for this attempted installation.  Can you point me to the expected path for this file?

**Comment by dg0yt** [comment]
~~~
autoreconf: configure.ac: not using Libtool
~~~
Can you try `sudo apt-get install libtool`?

**Comment by njk42** [comment]
Hi @dg0yt,  yes - I tried that as well as pkg-config (see comment above) and the process got a bit further but still ended in an error.

**Comment by JonLiu1993** [comment]
@njk42 ,Can you send me the entire error log: :
````
 /vcpkg/buildtrees/libusb/config-x64-linux-dbg-err.log
````

**Comment by dg0yt** [comment]
> I don't know where to find 'config.log'... I don't see it in buildtrees/libusb/ like the other log files for this attempted installation. Can you point me to the expected path for this file?

When the configure step fails, it is in `buildtrees/libusb/x64-linux-dbg`.

**Comment by njk42** [comment]
Here are the contents of my buildtrees/libusb/ folder... I don't see the `x64-linux-dbg `subdirectory or` config-x64-linux-dbg-err.log`:

          root@4d67670462c8:/vcpkg# ls -l -a buildtrees/libusb/
          total 64
          drwxr-xr-x 3 root root 4096 Jun 20 12:14 .
          drwxr-xr-x 4 root root 4096 Jun 20 12:14 ..
          -rw-r--r-- 1 root root 1187 Jun 20 12:14 autoconf-x64-linux-err.log
          -rw-r--r-- 1 root root    0 Jun 20 12:14 autoconf-x64-linux-out.log
          -rw-r--r-- 1 root root 4309 Jun 20 12:14 cmake-vars-x64-linux-dbg.cmake.log
          -rw-r--r-- 1 root root 4353 Jun 20 12:14 cmake-vars-x64-linux-rel.cmake.log
          -rw-r--r-- 1 root root  144 Jun 20 12:14 cmake-vars-x64-linux.cmake.log
          -rw-r--r-- 1 root root   52 Jun 20 12:14 error-logs-x64-linux.txt
          -rw-r--r-- 1 root root    0 Jun 20 12:14 extract-err.log
          -rw-r--r-- 1 root root    0 Jun 20 12:14 extract-out.log
          -rw-r--r-- 1 root root  225 Jun 20 12:14 get-cmake-vars-x64-linux-dbg-err.log
          -rw-r--r-- 1 root root  620 Jun 20 12:14 get-cmake-vars-x64-linux-dbg-out.log
          -rw-r--r-- 1 root root  225 Jun 20 12:14 get-cmake-vars-x64-linux-rel-err.log
          -rw-r--r-- 1 root root  620 Jun 20 12:14 get-cmake-vars-x64-linux-rel-out.log
          drwxr-xr-x 3 root root 4096 Jun 20 12:14 src
          -rw-r--r-- 1 root root 1260 Jun 20 12:14 stdout-x64-linux.log
          -rw-r--r-- 1 root root 1150 Jun 20 12:14 x64-linux.vcpkg_abi_info.txt

**Comment by JonLiu1993** [comment]
@njk42 ，Please send me the entire error log: :
````
 /vcpkg/buildtrees/libusb/config-x64-linux-dbg-err.log
````

**Comment by njk42** [comment]
@JonLiu1993  I would if I could, but that file is not getting created.  The list above shows the only files present in `buildtrees/libusb/` after I try the installation, and `config-x64-linux-dbg-err.log` is not one of them.

**Comment by dg0yt** [comment]
@njk42 `stdout-x64-linux.log` tells you which log files were generated last.
- Initially your build failed in the autoreconf step. At this time, there is only the `src` directory. It generates the `autoconf` log files. If the step fails, you don't get to the next step...
- The next step is configure. It operates in the binary directories (`x64-linux-dbg`, `x64-linux-rel`) and creates `config` log files.
- The actually `configure` script writes to `config.log` in the binary directory. On success, it is moved next to the other log files. If configuration fails, it is still in the binary dir.

**Comment by dg0yt** [comment]
So you don't even have `make`. Install that, or install the `packaging-dev` meta-package.

**Comment by JonLiu1993** [comment]
@njk42 ,Is this issue be sloved?

**Comment by JonLiu1993** [comment]
> Might I recommend that these required Linux system resources (e.g. make, libtool, pkg-config, etc) be added to the installation instructions "Prerequisites" list, since vcpkg doesn't automatically install them (like it did for cmake). The existing "Getting Started with Vcpkg" site doesn't list any other required system resources besides git and g++:
> 
> https://vcpkg.io/en/getting-started.html

@njk42, We will consider its feasibility, thank you for your suggestion!
