### ISSUE TITLE
[zlib] build failure on wasm32-emscripten triplet

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#25314]
zlib build failure on wasm32-emscripten triplet:
try on linux ubuntu wsl2
Before change of today it was working.
```
Installing 4/7 zlib:wasm32-emscripten...
Building zlib[core]:wasm32-emscripten...
-- [OVERLAY] Loading triplet configuration from: /home/tal/boinc/3rdParty/vcpkg_ports/triplets/ci/wasm32-emscripten.cmake
-- Downloading https://github.com/madler/zlib/archive/v1.2.12.tar.gz -> madler-zlib-v1.2.12.tar.gz...
-- Extracting source /home/tal/boinc/3rdParty/wasm/vcpkg/downloads/madler-zlib-v1.2.12.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch debug-postfix-mingw.patch
-- Applying patch 0002-android-build-mingw.patch
-- Using source at /home/tal/boinc/3rdParty/wasm/vcpkg/buildtrees/zlib/src/v1.2.12-f2d39b538c.clean
-- Configuring wasm32-emscripten-rel
-- Building wasm32-emscripten-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: /home/tal/boinc/3rdParty/wasm/vcpkg/downloads/tools/cmake-3.22.2-linux/cmake-3.22.2-linux-x86_64/bin/cmake --build . --config Release --target install -- -v -j13
    Working Directory: /home/tal/boinc/3rdParty/wasm/vcpkg/buildtrees/zlib/wasm32-emscripten-rel
    See logs for more information:
      /home/tal/boinc/3rdParty/wasm/vcpkg/buildtrees/zlib/install-wasm32-emscripten-rel-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/zlib/portfile.cmake:26 (vcpkg_cmake_install)
  scripts/ports.cmake:146 (include)
```
[install-wasm32-emscripten-rel-out.log](https://github.com/microsoft/vcpkg/files/8934313/install-wasm32-emscripten-rel-out.log)

**Comment by autoantwort** [comment]
> Before change of today it was working.

zlib was not changed within the last month.

**Comment by talregev** [comment]
> > Before change of today it was working.
> 
> zlib was not changed within the last month. 

I was compile it before and it was compiled.
Then today/yesterday there was a build world? Because all the packages compile again, then zlib is fail. So something is change in vcpkg in recent 24h or so.

**Comment by autoantwort** [comment]
So if you use an commit from 2 days ago it works again?

**Comment by talregev** [comment]
> So if you use an commit from 2 days ago it works again? 

I will try it and let you know. This is a good idea.

**Comment by talregev** [comment]
@autoantwort I compile on my local wsl with commit 2 days ago (91393faf123c4f1d22ef3dbfb4ec03531bac907a) and It fail.
Then tested on our CI on the latest vcpkg and it working. So I delete vcpkg and emsdk from my local wsl and compile from scratch. 
So it something local on my wsl. So I am closing this issue, and if there is a problem, I will open it again. Thank you!
