### ISSUE TITLE
[Podofo] Add CMake usage instructions to Podofo port

### ISSUE THREAD

**Issue by daljit97** [microsoft/vcpkg#25310]
****

**Is your feature request related to a problem? Please describe.**
The Podofo port of vcpkg doesn't give the user any instructions on how to integrate the library in an existing CMake project. When running `vcpkg install podofo:x64-windows` no instructions are shown on how to use this in a project. 

**Proposed solution**
Like with other libraries, when the installation of the package finishes there should be a brief description on how to use the package within a CMake project. 

**Describe alternatives you've considered**
I've tried reading the build files for the port to find appropriate instructions to integrate Podofo in an existing CMake project, but couldn't find it.

**Comment by JackBoosY** [comment]
The upstream doesn't provide this.
