### ISSUE TITLE
[brotli] Build error :x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by MasterofGames77** [microsoft/vcpkg#25322]
**Host Environment**
- OS: [Windows 11]
- Compiler: cmake 3.22.2

category: vcpkg-bug

**To Reproduce**
`./vcpkg install sfml
./ vcpkg install sfml:x64-windows

**Failure logs**
CMake Error at scripts/cmake/vcpkg_copy_tool_dependencies.cmake:31 (message):
  Could not find PowerShell Core; please open an issue to report this.
Call Stack (most recent call first):
  ports/brotli/portfile.cmake:24 (vcpkg_copy_tool_dependencies)
  scripts/ports.cmake:146 (include)

error: building brotli:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
vcpkg-tool version: 2022-06-15-b0f08e40f8e8752dd0b260138ee078bd9599559c
vcpkg-scripts version: 945e171c8 2022-06-17 (2 days ago)

**Additional context**
I am able to install other packages just fine. For some reason it doesn't work for (sfml)

**Comment by Cheney-W** [comment]
Could you please try below workaround?
`Just open vcpkg/scripts/vcpkgTools.xml and go to end of file. you will see <tool name="powershell-core" os="windows"> so change it to <tool name="pwsh" os="windows"> and save file.`

**Comment by MasterofGames77** [comment]
I tried the workaround you suggested but it still gave me the same error as before.

CMake Error at scripts/cmake/vcpkg_copy_tool_dependencies.cmake:31 (message):
  Could not find PowerShell Core; please open an issue to report this.
Call Stack (most recent call first):
  ports/brotli/portfile.cmake:24 (vcpkg_copy_tool_dependencies)
  scripts/ports.cmake:146 (include)

error: building brotli:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.

**Comment by MasterofGames77** [comment]
I was updating my files and it gave me this message.
The following packages differ from their port versions:
    vcpkg-cmake:x64-windows          2022-05-10#1 -> 2022-06-07

**Comment by Cheney-W** [comment]
> Could not find PowerShell Core; please open an issue to report this

If you installed the PowerShell from Windows Store, then you still need to install PowerShell Core; or uninstall the PowerShell from Windows Store.

**Comment by MasterofGames77** [comment]
So I uninstalled PowerShell I downloaded from the Windows Store and re-downloaded it from another source. And once I tried installing sfml, it actually worked this time. Now I can implement sfml into my projects. 
Thank you again for your assistance Cheney-W.

**Comment by Cheney-W** [comment]
Thanks for your reply!
