### ISSUE TITLE
[docs] Update list of supported platforms in FAQ

### ISSUE THREAD

**Issue by SamVanheer** [microsoft/vcpkg#25321]
The FAQ does not list all of the platforms currently supported by vcpkg's official triplets.
See https://github.com/microsoft/vcpkg/blob/b49b2bdf22559c89eddbf29a29621a1dc6929320/docs/about/faq.md?plain=1#L27-L28

vcpkg has supported Linux and mac OS since 2018, whereas this section in the FAQ dates back to 2016, so listing this information would be very helpful to users.

**Comment by AugP** [comment]
Good catch, we should probably have reviewed the FAQ a while ago and updated it for 2022. I submitted a PR that updates that section of the FAQ along with a few others that are out of date. 

Thank you for raising this issue!
