### ISSUE TITLE
[fontconfig] Build error - cross compiling for iOS

### ISSUE THREAD

**Issue by tomlandrum** [microsoft/vcpkg#25334]
**Host Environment**
- OS: MacOS 12.4
- Compiler: clang     13.1.6 "Apple clang version 13.1.6 (clang-1316.0.21.2.5)"

  package: fontconfig[core]:arm64-ios -> 2.14.0#2
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: b49b2bdf2 2022-06-17 (3 days ago)

**To Reproduce**
`./vcpkg install --triplet=arm64-ios fontconfig`

**Failure logs**
-Cut and paste the appropriate build messages from the console output.

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:83 (message):
    Command failed: /usr/local/bin/python3 /Users/tom/src/vcpkg/installed/x64-osx/tools/meson/meson.py -Ddoc=disabled -Dcache-build=disabled -Dtests=disabled --buildtype plain --backend ninja --wrap-mode nodownload --cross /Users/tom/src/vcpkg/buildtrees/fontconfig/meson-cross-arm64-ios.log --native /Users/tom/src/vcpkg/scripts/buildsystems/meson/none.txt --default-library static --libdir lib --cross /Users/tom/src/vcpkg/buildtrees/fontconfig/meson-cross-arm64-ios-debug.log -Ddebug=true --prefix /Users/tom/src/vcpkg/packages/fontconfig_arm64-ios/debug --includedir ../include -Dcmake_prefix_path=['/Users/tom/src/vcpkg/installed/arm64-ios/debug','/Users/tom/src/vcpkg/installed/arm64-ios'] /Users/tom/src/vcpkg/buildtrees/fontconfig/src/2.14.0-523cc719dc.clean
    Working Directory: /Users/tom/src/vcpkg/buildtrees/fontconfig/arm64-ios-dbg
    Error code: 1
    See logs for more information:
      /Users/tom/src/vcpkg/buildtrees/fontconfig/config-arm64-ios-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:428 (vcpkg_execute_required_process)
  ports/fontconfig/portfile.cmake:17 (vcpkg_configure_meson)
  scripts/ports.cmake:146 (include)

-Please attach any additional failure logs mentioned in the console output.

[config-arm64-ios-dbg-out.log](https://github.com/microsoft/vcpkg/files/8940829/config-arm64-ios-dbg-out.log)
[meson-log.txt](https://github.com/microsoft/vcpkg/files/8940832/meson-log.txt)

**Comment by dg0yt** [comment]
~~~
Command line:  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -I/Users/tom/src/vcpkg/installed/arm64-ios/include /Users/tom/src/vcpkg/buildtrees/fontconfig/arm64-ios-dbg/meson-private/tmpblbyqe3o/testfile.c -o /Users/tom/src/vcpkg/buildtrees/fontconfig/arm64-ios-dbg/meson-private/tmpblbyqe3o/output.obj -c -fPIC -g -O0 -Werror=implicit-function-declaration -Werror=unknown-warning-option -Werror=unused-command-line-argument -Werror=ignored-optimization-argument 
...
Compiler stderr:
 /Users/tom/src/vcpkg/buildtrees/fontconfig/arm64-ios-dbg/meson-private/tmpblbyqe3o/testfile.c:2:12: fatal error: 'string.h' file not found
  #include <string.h>
           ^~~~~~~~~~
1 error generated.
~~~
Perhaps another instance of a missing sysroot?

**Comment by tomlandrum** [comment]
How/where should that be set?

**Comment by dg0yt** [comment]
I guess it needs changes in `vcpkg_configure_meson.cmake` similar to what is done for macOS.

**Comment by daschuer** [comment]
The root issue is that a tool cannot be found: 
```
[5/57] /Users/runner/mixxx-vcpkg/installed/arm64-osx-min11.0/tools/gperf/gperf --pic -m 100 src/fcobjshash.gperf --output-file src/fcobjshash.h
FAILED: src/fcobjshash.h 
```

**Comment by daschuer** [comment]
I think a host dependency to gperf will do the trick, just trying.
or 
`brew install gperf``

**Comment by daschuer** [comment]
arm64-osx-min11.0 is target the x64-osx the host in my case.

**Comment by dg0yt** [comment]
And the original log has:
~~~
Program gperf found: YES (/usr/local/bin/gperf)
~~~

**Comment by daschuer** [comment]
Oh sorry for the noise, I have:  
2022-06-29T18:48:07.7427410Z   VCPKG_DEFAULT_TRIPLET: arm64-osx-min11.0
2022-06-29T18:48:07.7427680Z   VCPKG_DEFAULT_HOST_TRIPLET: arm64-osx-min11.0
This is wrong.

**Comment by tomlandrum** [comment]
Setting the sysroot (via SDKROOT) got past the problem with gperf.

**Comment by fwcd** [comment]
Hm, this seems more like a workaround. Is there a way to tell Meson about the sdkroot without resorting to env vars? I've seen that `vcpkg_configure_meson` also doesn't fully support cross-compilation yet:

- https://github.com/microsoft/vcpkg/issues/11230
