### ISSUE TITLE
vcpkg-tool-gn cannot run under CentOS 7

### ISSUE THREAD

**Issue by 0x8A63F77D** [microsoft/vcpkg#25337]
**Describe the bug**
vcpkg-tool-gn requires GLIBC_2.18 or later, which causes it cannot run under CentOS 7.

**Environment**
- OS: CentOS 7
- Compiler: GCC11

**Failure logs**
```
/home/0x8A63F77D/Test/cmake-build-debug/vcpkg_installed/x64-linux/tools/gn/gn: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/0x8A63F77D/Test/cmake-build-debug/vcpkg_installed/x64-linux/tools/gn/gn)
```

**Comment by 0x8A63F77D** [comment]
@autoantwort Google team said they won't fix this: [Building on Centos 7](https://groups.google.com/g/discuss-webrtc/c/y81rZPO3KG4/m/daz_pwU5CwAJ) [Issue 327617: GN: tools/gn/bin/linux/gn requires a too recent GLIBC version for Debian stable](https://bugs.chromium.org/p/chromium/issues/detail?id=327617). Would it be possible that vcpkg build gn instead of download the prebuild binary?

**Comment by Neumann-A** [comment]
> Would it be possible that vcpkg build gn instead of download the prebuild binary?

Theoretically yes but you need to fight @BillyONeal. The team doesn't seem to have a clean story for such cases which really annoys me (see discussion around https://github.com/microsoft/vcpkg/pull/23659#issuecomment-1151867976).

**Comment by BillyONeal** [comment]
>Theoretically yes but you need to fight @BillyONeal. The team doesn't seem to have a clean story for such cases which really annoys me (see discussion around https://github.com/microsoft/vcpkg/pull/23659#issuecomment-1151867976).

Ports aren't intended to be a toolchain deployment problem; building tools from source is an absolute last resort when we can do nothing else. Now that RHEL7 is effectively out of support I don't think it meets the bar I don't speak for all maintainers on that.

@ras0219 @ras0219-msft @vicroms @dan-shaw @JavierMatosD
