### ISSUE TITLE
[vcpkg-tools] update 7zip to 22.00

### ISSUE THREAD

**Issue by PriitUring** [microsoft/vcpkg#25336]
Library name: 7-Zip

New version number: 22.00

https://github.com/microsoft/vcpkg/blob/0cf5b4305ba811d069d3ce328261eeb54bf61c3a/scripts/vcpkgTools.xml#L133-L145

https://www.7-zip.org/download.html

https://sourceforge.net/p/sevenzip/discussion/45797/thread/9c2d9061ce/

**Comment by xavier2k6** [comment]
@JonLiu1993 #19568

**Comment by JonLiu1993** [comment]
@PriitUring ,Thanks for posting issue, we will update the tool together later, so I will temporarily close this issue. let's track this issue in https://github.com/microsoft/vcpkg/issues/19568
