### ISSUE TITLE
[gtest] update to HEAD

### ISSUE THREAD

**Issue by Tradias** [microsoft/vcpkg#25387]
Library name: https://github.com/google/googletest

New version number: HEAD (at the time of writing that would be https://github.com/google/googletest/commit/7df7853ea02371f6d24ccf4a0cf9e16553d23d05)

GoogleTest has been following the Live-At-Head philosophy for a while now, see https://github.com/google/googletest#live-at-head. In comparison to release 1.11.0 there are several fixes related to C++20 features, like coroutines.

**Comment by MehdiChinoune** [comment]
https://github.com/google/googletest/releases/tag/release-1.12.0
