### ISSUE TITLE
[boost] wrong platform toolset used to built in VS2019 (vc140 instead of vc142)

### ISSUE THREAD

**Issue by danyhm** [microsoft/vcpkg#25392]
**Describe the bug**
"vcpkg install boost" uses the wrong platform toolset to build the libraries.

**Environment**
- OS: [e.g. Windows]
- Compiler: 19.29.30145 for x86

**To Reproduce**
1. ./vcpkg install boost 
2. See error
produced libs are build using vc140 platform toolset (e.g. boost_coroutine-vc140-mt.lib) instead of vc142 for VS2019

**Expected behavior**
the libs should be build using vc142

**Failure logs**

**Additional context**

**Comment by Neumann-A** [comment]
> e.g. boost_coroutine-vc140-mt.lib

Build log?

**Comment by Cheney-W** [comment]
This is by design, It actually uses vc142, just named vc140.
More info please see: https://github.com/microsoft/vcpkg/issues/601

**Comment by danyhm** [comment]
Thanks for the tip. It's very confusing
