### ISSUE TITLE
[benchmark] Build Error during install for arm64-osx triplet

### ISSUE THREAD

**Issue by jayhomn-bitquill** [microsoft/vcpkg#25397]
**Host Environment**
- OS: MacOS Monterey 12.4
- vcpkg-tool version: 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e
- vcpkg-scripts version: 019027ada 2022-06-21 

**To Reproduce**
- Create vcpkg.json and add "benchmark" as dependency
- `./vcpkg install --triplet=arm64-osx --host-triplet=x64-osx --x-install-root=vcpkg/installed`

**Failure logs**
`CMake Error at CMakeLists.txt:304 (message):
  Failed to determine the source files for the regular expression backend`

[config-arm64-osx-dbg-out.log](https://github.com/microsoft/vcpkg/files/8960349/config-arm64-osx-dbg-out.log)

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated in 3 months, if it is still an issue, please reopen this issue.
