### ISSUE TITLE
"vcpkg integrate install" breaks UWP builds

### ISSUE THREAD

**Issue by pdehne** [Microsoft/vcpkg#254]
I am testing with the Blank App Template under Visual C++/Windows/Universal. I am using VS 14.0.25431.01 Update 3.

After doing "vcpkg integrate install" the build of the Blank App breaks during linking with unresolved external symbol errors. E.g:

`
App.xaml.obj : error LNK2019: unresolved external symbol "public: void __cdecl BlankCPP2::App::InitializeComponent(void)" (?InitializeComponent@App@BlankCPP2@@Q$AAAXXZ) referenced in function "public: __cdecl BlankCPP2::App::App(void)" (??0App@BlankCPP2@@Q$AAA@XZ)`

After doing "vcpkg integrate remove" the build completes successfully again.

**Comment by ras0219-msft** [comment]
This is an issue that would really drive people crazy; thank you so much for bringing it up. I've managed to repro it locally and I'll let you know when I have a fix.

**Comment by ras0219-msft** [comment]
I have reverted the `/MT` integration which was causing this issue (e515285).

Essentially, the CRT type is not expressed in MSBuild as a property that can be easily detected (CMake is similar), so our attempts to detect it anyway were much more fragile than expected. We will now not automatically switch triplets based on the CRT type -- you can still access this by specifying the Vcpkg triplet directly in your MSBuild via the property `VcpkgTriplet` or in CMake using `VCPKG_TARGET_TRIPLET`.

**Comment by pdehne** [comment]
Glad I could help :-)

And many thanks for fixing it so fast!
