### ISSUE TITLE
[sdl2:x64-osx] incorrect build

### ISSUE THREAD

**Issue by Trider12** [microsoft/vcpkg#25402]
**Describe the bug**
See https://discourse.libsdl.org/t/sdl2-linking-errors-on-macos/37387

**Environment**
- OS: [macOS Big Sur 11.0.1]
- Compiler: AppleClang 12.0.5

**To Reproduce**
1. ./vcpkg install sdl2

**Comment by JackBoosY** [comment]
I think you need to use 
```
find_package(SDL2 CONFIG REQUIRED) # provided by vcpkg
target_link_libraries(${TARGET} PRIVATE SDL2::SDL2 SDL2::SDL2-static)
```
instead.

**Comment by Trider12** [comment]
@JackBoosY, thanks! Replacing `${SDL2_LIBRARIES}` with `SDL2::SDL2 SDL2::SDL2-static` did solve the issue. Could you please explain why the original version doesn't work on macOS, but does work on Linux which also builds statically?

**Comment by JackBoosY** [comment]
1. `find_package(SDL2 REQUIRED)` uses `FindSDL2.cmake`, not `SDL2Config.cmake` which generated by the source. So the behavor is not the same.
2. SDL2 depends on some apple frameworks in OSX, so if your project link with sdl2 library, those frameworks are also needed.
3. There may have some bugs in `FindSDL2.cmake`, which caused this issue.

**Comment by Trider12** [comment]
> 1. `find_package(SDL2 REQUIRED)` uses `FindSDL2.cmake`, not `SDL2Config.cmake` which generated by the source. So the behavor is not the same.

Actually, I haven't changed that line, so `FindSDL2.cmake` is still being used in all cases.

**Comment by JackBoosY** [comment]
> Actually, I haven't changed that line, so `FindSDL2.cmake` is still being used in all cases.

Since sdl2 in vcpkg has `vcpkg-cmake-wrapper`, it will always add sdl2 targets, but you still need to add the keyword `CONFIG` in `find_package` to ensure the correctness of the contents of the targets.

**Comment by dg0yt** [comment]
I think this issue is valid and should be reopened.

- Exported SDL2 config should be self contained. Missing dependencies should be patched (and upstreamed).
- The wrapper should add the the missing dependencies for the Find module in CMake. (Patches could be upstreamed to Kitware.)
- Linking both `SDL2::SDL2 SDL2::SDL2-static` smells like poor output from the vcpkg tool usage heuristics, not like the actual usage requirement.

**Comment by Trider12** [comment]
To fully clarify - I replaced this version (doesn't work on macOS):
```
find_package(SDL2 REQUIRED) # provided by vcpkg
target_link_libraries(${TARGET} PRIVATE {SDL2_LIBRARIES}) 
```

with this version (does work on macOS):
```
find_package(SDL2 REQUIRED) # provided by vcpkg
target_link_libraries(${TARGET} PRIVATE SDL2::SDL2-static SDL2::SDL2main) 
```

So there's no `CONFIG` keyword and no linking `SDL2` twice.

**Comment by JackBoosY** [comment]
@dg0yt Did you mean that sdl2 vcpkg-cmake-wrapper needs to force users to use CONFIG mode when using `find_package` and fix macros which are provided by `FindSDL2.cmake`?

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. The latest usage of `sdl2` is as below, it could test succeed on MACOS, so I am closing this issue for now.
```
    find_package(SDL2 CONFIG REQUIRED)
    target_link_libraries(main
        PRIVATE
        $<TARGET_NAME_IF_EXISTS:SDL2::SDL2main>
        $<IF:$<TARGET_EXISTS:SDL2::SDL2>,SDL2::SDL2,SDL2::SDL2-static>
    )
```
