### ISSUE TITLE
[rapidxml and zlib] These two packages don't compile together

### ISSUE THREAD

**Issue by Jeremyvp** [microsoft/vcpkg#25407]
****

**Machine setup**
I use Windows 10, vcpkg (2022.06.15.1), Visual Studio 2019 Professional v16.9.2

**The problem**
Both rapidxml (rapidxml.hpp line 385) and zlib (zlib.h line 81) typedef a function pointer called alloc_func. When both headers are included in a source file, I understandably get a compilation error.

rapidxml.hpp
`385: typedef void *(alloc_func)(std::size_t);       // Type of user-defined function used to allocate memory`

zlib.h
`81: typedef voidpf (*alloc_func) OF((voidpf opaque, uInt items, uInt size));`

**Steps to reproduce**
1. Use vcpkg to install both libraries `vcpkg install zlib rapidxml`.
2. Include both rapidxml.hpp and zlib.h in a source file.
3. Try to compile.

**Current workaround**
We are currently trying to move to vcpkg as our dependency manager and don't use it yet. Up until now we circumvented this problem is by renaming the typedef in zlib to alloc_func_zlib (lines 81 and 97).

**Possible solution**
It would be an improvement if these two libraries worked together out of the box somehow. We are considering either leaving zlib as is and not use vcpkg for that library, or try to write a patch and use a port overlay that fixes this for us in the same way.

I'm not the most experienced with vcpkg, so is there any way to solve this problem in a better way?

**Comment by JackBoosY** [comment]
`alloc_func` in zlib is a public function. However, `alloc_func` in raipdxml is `rapidxml::memory_pool::alloc_func`, so I think there is no conflict when not using the namespace `rapidxml` directly (this is why we need namespace).
This is an upstream issue, please report this to rapidxml (I don't think zlib will change their code).

Thanks.

**Comment by Jeremyvp** [comment]
Reordering some header files so that the rapidxml headers are always included first seems to fix the issue. It's not very robust, but at least it gets the job done for now. Thanks for your comment!

**Comment by dg0yt** [comment]
#47161 may have a proper fix for rapdidxml (or for MSCV, the only compiler which complains.)
