### ISSUE TITLE
libpqxx  non-standard debug suffix

### ISSUE THREAD

**Issue by iciuperca** [Microsoft/vcpkg#2540]
In CMakeLists.txt there is a line that should be removed:

`set(CMAKE_DEBUG_POSTFIX "D")`

Other ports do not seem to have any kind of debug prefix as that is handled by the directories they are placed in, and it makes things harder for `find_library`

**Comment by Cheney-W** [comment]
@iciuperca, Could you please describe in detail what you said "it makes things harder for find_library"?

**Comment by Neumann-A** [comment]
probably related to the regression seen in #5543

**Comment by wangli28** [comment]
Hi @iciuperca, Thanks for posting this issue. Please open a new issue if this is still a problem for you.
