### ISSUE TITLE
How do I specify the compile option of GPU/CPU, when exec vcpkg install tensorflow-cc?

### ISSUE THREAD

**Issue by x-bruce** [microsoft/vcpkg#25411]
How do I specify the compile option of GPU/CPU, when exec vcpkg install tensorflow-cc?

**Comment by JackBoosY** [comment]
It should be a tensorflow-cc new feature, not by compile option.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
