### ISSUE TITLE
No able to download vcpkg-glibc in openshift

### ISSUE THREAD

**Issue by minhaajk** [microsoft/vcpkg#25415]
**Describe the bug**

Hello I am trying to build a docker application using vcpkg as my package manager. But when bootstrap-vcpkg.sh is run, I am getting 403 error while downloading vcpkg-glibc. 

So I just tried the curl command to download vcpkg-glibc and look for the error.

**Environment**

- OS: Openshift

**To Reproduce**

RUN in docker file, I am using rhel base image

RUN curl -v -L "https://github.com/microsoft/vcpkg-tool/releases/download/2022-06-17/vcpkg-glibc" --tlsv1.2 --create-dirs --retry 3 --output "/app/temp/vcpkg.part" --show-error 

**Expected behavior**
vcpkg-glibc should be downloaded successfully.

**Failure logs**

< HTTP/1.1 403 Forbidden
< Cache-Control: no-cache
< X-XSS-Protection: 1
< Connection: close
< Content-Type: text/html; charset=utf-8
< Content-Length: 732
< Pragma: no-cache
< 
* Received HTTP code 403 from proxy after CONNECT
* CONNECT phase completed!
* Closing connection 1

**Comment by Cheney-W** [comment]
Can you download other github resources on Openshift successfully?

**Comment by minhaajk** [comment]
Hello,

Looks like githubusercontent.com is forbidden from our proxy, so need to add to the list to allow access.
Closing this question :)
