### ISSUE TITLE
[libpng] Build error

### ISSUE THREAD

**Issue by zsy0514** [microsoft/vcpkg#25425]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs**
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JonLiu1993** [comment]
@zsy0514, Thanks for your issue, please follow the template above to fill in your reproduction environment, reproduction steps and error log

**Comment by LilyWangLL** [comment]
Thanks for posting this issue, now `libpng` build succeed on Windows and Linux. If this is still a problem for you, please reopen this issue with more info.
