### ISSUE TITLE
[gdal] duplicate pdb in `lib`

### ISSUE THREAD

**Issue by Osyotr** [microsoft/vcpkg#25422]
**Describe the bug**
Installed gdal has duplicate pdb file in `lib` (and `debug/lib`). This is not that big of an issue, but still ~300mb of storage wasted.

**Environment**
- OS: Windows
- Compiler: MSVC 17.2.3

**To Reproduce**
1. `./vcpkg install gdal:x64-windows`
2. Check installed files in `bin` and `lib`

**Expected behavior**
Only one copy of `gdal304.pdb` should exist

**Comment by dg0yt** [comment]
Are you sure that there can be only one copy if they don't match? Cf. #7256.

And I don't think this should be fixed for nmake now while the switch to cmake is pending.

**Comment by Osyotr** [comment]
I've checked, they have the same SHA256.
