### ISSUE TITLE
[qt5] fail to build qt widget project in VS2019 with vcpkg-installed qt5 x64 windows 

### ISSUE THREAD

**Issue by snowman4628** [microsoft/vcpkg#25434]
**Describe the bug**
I've installed qt5[x64 windows] by vcpkg, and configured VS2019 and qt project as below.
![image](https://user-images.githubusercontent.com/17664600/175781897-1737e4bc-0c8d-4aff-82d4-7183ab91f9c6.png)
![image](https://user-images.githubusercontent.com/17664600/175781900-ef81d0f2-024f-4a9d-9fb5-cb977bcfd20f.png)
configure qt version - qt5 in path "[vcpkg root]\installed\x64-windows\tools\qt5\bin"
configure qt version - qt5_debug in path "[vcpkg root]\installed\x64-windows\tools\qt5\debug\bin"

![image](https://user-images.githubusercontent.com/17664600/175781986-eadbb557-7e3f-4fff-ab69-ce5793f5ef43.png)
configure qt version of project in release mode - qt5
![image](https://user-images.githubusercontent.com/17664600/175782000-a3f8aced-e53a-4d47-b3f8-fa643896e1ed.png)
configure qt version of project in debug mode - qt5_debug

I successfully built my qt widget project in release mode, but failed in debug mode.
Here's the build error message
![image](https://user-images.githubusercontent.com/17664600/175782226-12c0c69c-7d8b-48f4-9e3f-c93b040a97b5.png)
MSB3073	" The command "[vcpkg root]\installed\x64-windows\tools\qt5\debug\bin\rcc.exe" --list "QtWidgetsApplication1.qrc" > "x64\Debug\rcc_list.txt" 2> nul" exited with code -1073741515.	QtWidgetsApplication1	C:\Users\oem\AppData\Local\QtMsBuild\rcc\qtrcc.targets	116	

**Environment**
- OS: Windows 10
- Compiler: VS2019 16.11.16

**To Reproduce**
1.create qt widget project by default template
2.configure project qt version as description
3.build qt widget project in debug mode

**Expected behavior**
Successfully build debug mode qt5 widget project in VS2019

**Failure logs**
MSB3073	" The command "[vcpkg root]\installed\x64-windows\tools\qt5\debug\bin\rcc.exe" --list "QtWidgetsApplication1.qrc" > "x64\Debug\rcc_list.txt" 2> nul" exited with code -1073741515.	QtWidgetsApplication1	C:\Users\oem\AppData\Local\QtMsBuild\rcc\qtrcc.targets	116

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Could you please provide the file: **x64\Debug\rcc_list.txt**?

**Comment by snowman4628** [comment]
Is vcpkg support qt vs tool now? 
I can build VS project(using qt classes) debug mode if I create my project without applying VS-Qt project template.

**Comment by LilyWangLL** [comment]
cc @Neumann-A Could you help take a look this issue? I have not used qt in MSbuild project. Thanks in advance.
