### ISSUE TITLE
[curl:x86-windows-static] Strange strings in a binary file after compilation in a release mode

### ISSUE THREAD

**Issue by sergoutre** [microsoft/vcpkg#25436]
**Describe the bug**
Hi there, idk where should I post it, so ...
The problem is, when I compile a code with a curl lib in a release mode i get such strings in my compiled file: [click](https://imgur.com/a/iQphTkD)

**Environment**
- OS: Win 10
- Compiler: VS 2022

**To Reproduce**
1. ./vcpkg install curl:x86-windows-static
2. Compile this code with a release config:
```
#include <stdio.h>
#include <curl/curl.h>

#ifdef _DEBUG
#pragma comment (lib, "libcurl-d.lib")
#else
#pragma comment (lib, "libcurl.lib")
#endif

#pragma comment(lib, "Normaliz.lib")
#pragma comment(lib, "Ws2_32.lib")
#pragma comment(lib, "Wldap32.lib")
#pragma comment(lib, "Crypt32.lib")
#pragma comment(lib, "advapi32.lib")

int main()
{
    CURL* curl;
    CURLcode res;
    curl = curl_easy_init();
    if (curl) {
        curl_easy_setopt(curl, CURLOPT_URL, "http://example.com");
        /* example.com is redirected, so we tell libcurl to follow redirection */
        curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);
        /* Perform the request, res will get the return code */
        res = curl_easy_perform(curl);
        /* Check for errors */
        if (res != CURLE_OK)
            fprintf(stderr, "curl_easy_perform() failed: %s\n",
                curl_easy_strerror(res));

        /* always cleanup */
        curl_easy_cleanup(curl);
    }
    return 0;
}
```

**Expected behavior**
I don't think that those strings should be in a bin file.

**Comment by aizuon** [comment]
Looks like these come from *free* function calls (2nd param is the line number for debugging purposes)

![image](https://user-images.githubusercontent.com/44760523/175793300-3b98f328-6669-4f26-a3e0-8be5a80c1239.png)
![image](https://user-images.githubusercontent.com/44760523/175793312-4f76d664-5fe2-48c5-9216-ff55a66544be.png)

sub_14009BDA0 is: 

![image](https://user-images.githubusercontent.com/44760523/175793340-c0605356-6f52-4bc8-a3da-82968b21493d.png)

Which matches this func from the src:

![image](https://user-images.githubusercontent.com/44760523/175793352-73d267fe-f69a-401c-a4d9-2bd9a546e51d.png)

So *free* is overloaded with a debug func that takes the line it's called from with a macro. 

I agree that this debugging *free* func should not be used in a release build. However, the code you gave also has paths from openssl. It is simply not practical to have your binary file path-free. If you would like your binary to be harder to reverse engineer, use an obfuscator, or if you would like to not leak your Windows user name, build it in a root path.

**Comment by dg0yt** [comment]
These code is enabled because the portfile always sets `-DENABLE_DEBUG=ON`:
https://github.com/microsoft/vcpkg/blob/c168ce4e765409509c9c482faa0468c4e1ab386b/ports/curl/portfile.cmake#L83-L92

Before https://github.com/microsoft/vcpkg/pull/9613/files, this was limited to the debug build. I wonder if this change was intentional, e.g. required for identical pdb files. CC @JackBoosY

**Comment by JackBoosY** [comment]
Ops, I shouldn't remove the related option name `OPTIONS_DEBUG`.

**Comment by JackBoosY** [comment]
Ah this issue should be fixed by https://github.com/microsoft/vcpkg/pull/25515. can you please confirm this?
Thanks @dg0yt!
