### ISSUE TITLE
[vcpkg remove] Can't remove package if overlay-triplet doesn't exist anymore.

### ISSUE THREAD

**Issue by olafurw** [microsoft/vcpkg#25442]
**Describe the bug**
If I install a package with a custom triplet and --overlay-triplet and then remove the triplet file, I can't remove the package.

**Environment**
- OS: Windows

**To Reproduce**
Install a package with a custom triplet and --overlay-triplet=somepath
Then delete/rename the file.
Then try to remove the package.

**Expected behavior**
If I know the full package name I should be able to remove it.

**Failure logs**
```
C:\Users\olafu\source\vcpkg>vcpkg list raylib
raylib:raylib-framerate                            4.0.0#3          A simple and easy-to-use library to enjoy videog...
raylib[use-audio]:raylib-framerate                                  Build raylib with audio module
```

Ok then I try to remove raylib.

```
C:\Users\olafu\source\vcpkg>vcpkg remove raylib
The following packages are not installed, so not removed:
    raylib:x86-windows
Another installed package matches the name of an unmatched request. Did you mean raylib:raylib-framerate?
Removing 1/1 raylib:x86-windows
```

Sure, I can remove that triplet.

```
C:\Users\olafu\source\vcpkg>vcpkg remove raylib:raylib-framerate
Error: invalid triplet: raylib-framerate
Available architecture triplets
VCPKG built-in triplets:
  arm-uwp
  arm64-windows
  ... // continues on, listing all the normal triplets, not including raylib-framerate
```

I even try the folder that used to have the custom triplet.

```
C:\Users\olafu\source\vcpkg>vcpkg remove raylib:raylib-framerate --overlay-triplets="c:\Users\olafu\source\repos\chain-reaction"
Error: invalid triplet: raylib-framerate
Available architecture triplets
VCPKG built-in triplets:
  arm-uwp
  arm64-windows
  ... // continues on, listing all the normal triplets, not including raylib-framerate
```

If I put the file back it works.

**Comment by JackBoosY** [comment]
I'm not clear this should be `feature` or `bug.`, marked vcpkg-feature temporary.
cc @BillyONeal

**Comment by BillyONeal** [comment]
In general, I think `remove` should not be looking at the inputs (ports, triplets, etc.) at all. If it exists in the installed tree, it should be removable.

It is certainly in the gray area between bug and feature.

**Comment by BillyONeal** [comment]
@ras0219-msft tells me that the installed database should have that information so it should be doable, yes.

**Comment by olafurw** [comment]
❤️

**Comment by dg0yt** [comment]
When was this broken again? AFAICT this was fixed a long time ago, and it works for me:
~~~
$ ./vcpkg install --overlay-ports scripts/test_ports vcpkg-ci-ffmpeg
Computing installation plan...
The following packages are already installed:
    vcpkg-ci-ffmpeg:x64-linux -> 1#2
vcpkg-ci-ffmpeg:x64-linux is already installed
Total install time: 7.29 us
$ ./vcpkg remove vcpkg-ci-ffmpeg
The following packages will be removed:
    vcpkg-ci-ffmpeg:x64-linux
Removing 1/1 vcpkg-ci-ffmpeg:x64-linux
$ ./vcpkg --version
vcpkg package management program version 2023-06-22-f19f3d9939100085fe2f7e41502d60b08e2083b6

See LICENSE.txt for license information.

**Comment by BillyONeal** [comment]
Was fixed in https://github.com/microsoft/vcpkg/pull/32885
