### ISSUE TITLE
[libiconv] i met some problems when use "vcpkg install libiconv:x64-windows"

### ISSUE THREAD

**Issue by BaiwanHuang** [microsoft/vcpkg#25449]
[issue_body.md](https://github.com/microsoft/vcpkg/files/8989502/issue_body.md)

Searched a lot of issues about libiconov, but still did not solve.
I felt a little anxious, who can help me

**Comment by Cheney-W** [comment]
I can't reproduce this issue with following test environments:
1. VS2022 17.2.4 + V143 + latest vcpkg 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e
2. VS2017 15.9.49 + V141 + latest vcpkg 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e

Also, I see in your log that the code page of your running window is 65001, while mine is 437. I think you can try to modify your active code page as 437 and then install libiconv again.

**Comment by BaiwanHuang** [comment]
> I can't reproduce this issue with following test environments:
> 
> 1. VS2022 17.2.4 + V143 + latest vcpkg 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e
> 2. VS2017 15.9.49 + V141 + latest vcpkg 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e
> 
> Also, I see in your log that the code page of your running window is 65001, while mine is 437. I think you can try to modify your active code page as 437 and then install libiconv again.

thanks for your attention,i tried changing the page code to 437, but still had the same problem.

**Comment by Cheney-W** [comment]
What's the result when you do below steps:
1. git pull
2. .\bootstrap-vcpkg.bat
3. .\vcpkg.exe install libiconv:x64-windows --binarysource=clear

**Comment by BaiwanHuang** [comment]
> What's the result when you do below steps:
> 
> 1. git pull
> 2. .\bootstrap-vcpkg.bat
> 3. .\vcpkg.exe install libiconv:x64-windows --binarysource=clear

thanks for your attention,i tried, but still had the same results

**Comment by dg0yt** [comment]
Given the occurences of `Active code page: 65001`: check 
https://stackoverflow.com/questions/48183570/how-to-fix-windows-batch-file-for-command-returing-active-code-page-65001
The build could be affected by output from auto-run commands.
CC @dad98253 for #27047.

**Comment by sfhacker** [comment]
https://english-for-chinese.blogspot.com/2008/06/and-meet-problem.html

**Comment by LilyWangLL** [comment]
> Given the occurences of `Active code page: 65001`: check https://stackoverflow.com/questions/48183570/how-to-fix-windows-batch-file-for-command-returing-active-code-page-65001 The build could be affected by output from auto-run commands.

@BaiwanHuang Please refer to this solution, if this issue still exist, please reopen.
