### ISSUE TITLE
[New Port Request] <PySide>

### ISSUE THREAD

**Issue by kashif1973** [microsoft/vcpkg#25455]
Library name:
PySide
Library description:

Source repository URL:

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JonLiu1993** [comment]
@kashif1973 ,Thanks for your issue, could you please provide the Source repository URL and Project homepage?

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
