### ISSUE TITLE
Unable to locate 'afxres.h'.  Ensure you have installed the ATL/MFC

### ISSUE THREAD

**Issue by kael0930** [microsoft/vcpkg#25468]
PS C:\Users\39273\Desktop> vcpkg install QScintilla
Computing installation plan...
The following packages will be built and installed:
  * atlmfc[core]:x64-windows -> 0#1
    qscintilla[core]:x64-windows -> 2.12.0#1
  * qt5-winextras[core]:x64-windows -> 5.15.5
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet "x64-windows"...
-- Automatically setting HTTP(S)_PROXY environment variables to "127.0.0.1:10809".
Restored 0 packages from C:\Users\39273\AppData\Local\vcpkg\archives in 342.9 us. Use --debug to see more details.
Installing 1/3 atlmfc:x64-windows...
Building atlmfc[core]:x64-windows...
CMake Error at ports/atlmfc/portfile.cmake:7 (message):
  Unable to locate 'afxres.h'.  Ensure you have installed the ATL/MFC
  component of Visual Studio.
Call Stack (most recent call first):
  scripts/ports.cmake:146 (include)

**Comment by Adela0814** [comment]
@kael0930 do you install ATL/MFC component? if not, could you install it by visual studio installer?
![image](https://user-images.githubusercontent.com/95600143/176336710-29b88c13-b0cb-44a6-bf91-ba5a8768e066.png)

**Comment by kael0930** [comment]
thanks for your reminder
