### ISSUE TITLE
[openvpn3] use on osx will link windows lib

### ISSUE THREAD

**Issue by SpenserCai** [microsoft/vcpkg#25463]
**Describe the bug**
use on osx will link windows lib

**Environment**
- OS: [x64-osx]
- Compiler: revision

**To Reproduce**
https://github.com/microsoft/vcpkg/blob/master/ports/openvpn3/CMakeLists.txt
![截屏2022-06-28 下午7 44 05](https://user-images.githubusercontent.com/25168945/176170626-46e855ff-79eb-48b0-9a5d-0792ced874e6.png)

**Comment by Adela0814** [comment]
Upstream has already fixed this issue, I will update `openvpn3` once the change released.

**Comment by Adela0814** [comment]
I will use upstream [CMakeLists](https://github.com/OpenVPN/openvpn3/blob/master/CMakeLists.txt) instead of [vcpkg/ports/openvpn/CMakeLists.txt](https://github.com/microsoft/vcpkg/blob/master/ports/openvpn3/CMakeLists.txt).

**Comment by SpenserCai** [comment]
> 我将使用上游[CMakeLists](https://github.com/OpenVPN/openvpn3/blob/master/CMakeLists.txt)而不是[vcpkg/ports/openvpn/CMakeLists.txt](https://github.com/microsoft/vcpkg/blob/master/ports/openvpn3/CMakeLists.txt)。

it's look like for ovpnagent not for ovpncli lib

**Comment by JackBoosY** [comment]
Not only requires Windows system libs but also OSX system libs.

**Comment by SpenserCai** [comment]
if use [CMakeLists](https://github.com/OpenVPN/openvpn3/blob/master/CMakeLists.txt) may be not generates libovpncli.a?
on windows ovpncli.lib's size is 32M,but on osx only 2.2M so can't be link with other dylib

**Comment by JackBoosY** [comment]
> if use [CMakeLists](https://github.com/OpenVPN/openvpn3/blob/master/CMakeLists.txt) may be not generates libovpncli.a? on windows ovpncli.lib's size is 32M,but on osx only 2.2M so can't be link with other dylib

Yeah we should use official CMakeLists instead.

**Comment by SpenserCai** [comment]
> > if use [CMakeLists](https://github.com/OpenVPN/openvpn3/blob/master/CMakeLists.txt) may be not generates libovpncli.a? on windows ovpncli.lib's size is 32M,but on osx only 2.2M so can't be link with other dylib
> 
> Yeah we should use official CMakeLists instead.

i thank if use official will not gen .lib or .a file
![image](https://user-images.githubusercontent.com/25168945/176429147-fd21d155-704f-40ab-8c0f-30122452cb72.png)

**Comment by JackBoosY** [comment]
@SpenserCai I think we should handle this in the PR.

**Comment by SpenserCai** [comment]
> <img alt="@JackBoosY" width="40" height="40" src="https://avatars.githubusercontent.com/u/47264268?s=88&amp;u=ca22eb954672cfd093c37f2aba7de59ec9cb20f3&amp;v=4">

ok,so when wil we start the PR for fix this bug

**Comment by JackBoosY** [comment]
@SpenserCai We are trying to fix this.

**Comment by mrizkihidayat66** [comment]
> if use [CMakeLists](https://github.com/OpenVPN/openvpn3/blob/master/CMakeLists.txt) may be not generates libovpncli.a? on windows ovpncli.lib's size is 32M,but on osx only 2.2M so can't be link with other dylib

Hi mate @SpenserCai, how did you create the .lib?
