### ISSUE TITLE
crashpad link issue

### ISSUE THREAD

**Issue by RAVER0306** [microsoft/vcpkg#25466]
crashpad link is normal in 2022.04.12 

Linking fails on latest branch

**Comment by RAVER0306** [comment]
windows

**Comment by RAVER0306** [comment]
file not found chromeos_buildflags.h

**Comment by JackBoosY** [comment]
Is this a build issue or a usage issue? Can you please provide the full log instead?
If it's a usage issue, please provide the sample code to reproduce it.

Thanks.

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
