### ISSUE TITLE
[vcpkg-cmake] `ADD_BIN_TO_PATH` should add lib/ to LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by ras0219-msft** [microsoft/vcpkg#25475]
`ADD_BIN_TO_PATH` currently only handles dynamic libraries for Windows by adding `bin/` to `%PATH%`. However, there is an exact analogue for non-Windows: `LD_LIBRARY_PATH`.

`vcpkg_cmake_build()`/`_install()` should prepend the configuration-specific `lib/` directory to `LD_LIBRARY_PATH` when passed `ADD_BIN_TO_PATH`.

**Comment by dg0yt** [comment]
`ADD_BIN_TO_PATH` is one of the most confusing options...
- It is named `*_BIN_*` which reads like *executables* for the non-windows world (`bin` dirs contain executables) but actually means *runtime* for vcpkg (executables moved out of `bin` dir).
- It doesn't care for cross builds (using `CURRENT_INSTALLED_DIR`).
- It will also affect actual libraries loaded by system tools so it should probably be flagged "last resort".

**Comment by RealLitb** [comment]
Please implement this - it's necessary for qtwebengine. QtWebEngine executes some tools that it build, and apparently links them to target libraries. So it needs the target's debug/non-debug lib path in LD_LIBRARY_PATH. 

Similar to vcpkg's autotools, it also needed lib/pkgconfig in PKG_CONFIG_PATH. Please provide an option for  vcpkg_cmake_configure to do that. Issue report will be created shortly.
