### ISSUE TITLE
[llvm] Build error

### ISSUE THREAD

**Issue by kreuzerkrieg** [microsoft/vcpkg#25474]
- OS: Ubuntu 20.4
- Compiler: gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)

`./vcpkg install llvm[libunwind]`

The repo was pulled yesterday

```
/home/user/Development/vcpkg/buildtrees/llvm/src/org-14.0.4-df58f01928.clean/libunwind/src/UnwindLevel1.c:23:10: fatal error: 'stdbool.h' file not found
#include <stdbool.h>
         ^~~~~~~~~~~
```
LLVM builds ok, libunwind fails, please see attached logs
[install-x64-linux-dbg-.zip](https://github.com/microsoft/vcpkg/files/9008148/install-x64-linux-dbg-.zip)

**Comment by kreuzerkrieg** [comment]
> Could you find the stdbool.h file on your linux machine?

```
sudo find / -name stdbool.h

/home/user/Development/vcpkg/installed/x64-linux/include/aws/common/stdbool.h
/home/user/Development/vcpkg/buildtrees/llvm/src/org-14.0.4-df58f01928.clean/clang-tools-extra/test/clang-tidy/checkers/Inputs/modernize-deprecated-headers/stdbool.h
/home/user/Development/vcpkg/buildtrees/llvm/src/org-14.0.4-df58f01928.clean/clang/test/Modules/Inputs/System/usr/include/stdbool.h
/home/user/Development/vcpkg/buildtrees/llvm/src/org-14.0.4-df58f01928.clean/clang/lib/Headers/stdbool.h
/home/user/Development/vcpkg/buildtrees/llvm/src/org-14.0.4-df58f01928.clean/libcxx/include/stdbool.h
/home/user/Development/vcpkg/buildtrees/llvm/x64-linux-dbg/lib/clang/14.0.4/include/stdbool.h
/usr/include/c++/9/tr1/stdbool.h
/usr/include/c++/10/tr1/stdbool.h
/usr/lib/llvm-10/lib/clang/10.0.0/include/stdbool.h
/usr/lib/gcc/x86_64-linux-gnu/9/include/stdbool.h
/usr/lib/gcc/x86_64-linux-gnu/10/include/stdbool.h
/usr/lib/gcc/x86_64-linux-gnu/8/include/stdbool.h
/usr/lib/llvm-11/lib/clang/11.0.0/include/stdbool.h
/usr/lib/llvm-14/lib/clang/14.0.5/include/stdbool.h
/usr/lib/llvm-9/lib/clang/9.0.1/include/stdbool.h
/usr/lib/llvm-12/lib/clang/12.0.0/include/stdbool.h
/snap/clion/198/bin/clang/linux/include/stdbool.h
/snap/clion/193/bin/clang/linux/include/stdbool.h

```

**Comment by Cheney-W** [comment]
Could you please use `./vcpkg install llvm[libunwind] --debug` and send the `stdout-x64-linux.log` to me? Thank you!

**Comment by kreuzerkrieg** [comment]
> Could you please use `./vcpkg install llvm[libunwind] --debug` and send the `stdout-x64-linux.log` to me? Thank you!

here you go. BTW, I dont see the debug output being captured in the `stdout-x64-linux.log`
[stdout-x64-linux.log](https://github.com/microsoft/vcpkg/files/9034522/stdout-x64-linux.log)
[libunwind.log](https://github.com/microsoft/vcpkg/files/9034523/libunwind.log)

**Comment by kreuzerkrieg** [comment]
@Cheney-W any news? any additional input you need?

**Comment by Cheney-W** [comment]
Sorry for the delay! I can't reproduce the issue here, I think you can delete other versions of g++, keep only one version, and try if the issue still exists.
