### ISSUE TITLE
[vcpkg] One line install does not work on Linux PowerShell

### ISSUE THREAD

**Issue by benmcmorran** [microsoft/vcpkg#25487]
**Environment**
- OS: WSL Ubuntu 20.04

**To Reproduce**
1. Install `pwsh` by following [these instructions](https://docs.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.2#installation-via-package-repository).
2. Run `iex (iwr -useb https://aka.ms/vcpkg-init.ps1)`.

**Expected behavior**
vcpkg installs successfully.

**Failure logs**
vcpkg fails to install.

```pwsh
PS /home/ben> iex (iwr -useb https://aka.ms/vcpkg-init.ps1)
Installing vcpkg to /home/ben/.vcpkg
ResourceUnavailable:
Line |
 107 |    & $VCPKG z-bootstrap-standalone
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Program 'vcpkg.exe' failed to run: An error occurred trying to start process '/home/ben/.vcpkg/vcpkg.exe' with working directory '/home/ben'. No such file or directoryAt line:107 char:3
+   & $VCPKG z-bootstrap-standalone
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
bootstrap-vcpkg:
Line |
 123 |  if( -not (bootstrap-vcpkg )) {
     |            ~~~~~~~~~~~~~~~
     | ERROR! Bootstrapping vcpkg failed.
```

**Comment by Cheney-W** [comment]
Thank for reporting this issue to us. I could reproduce this issue in my VM.

@BillyONeal 
The [blog](https://devblogs.microsoft.com/cppblog/vcpkg-artifacts/#acquire-vcpkg) mentioned that we can use
 `iex (iwr -useb https://aka.ms/vcpkg-init.ps1)` 
to acquire vcpkg in powershell, but it did not mention whether this powershell is on linux or windows. 
I tested it locally, and vcpkg can be successfully obtained on windows, but on linux it will be the same as the user the error.

So I want confirm with you that if this command is only works on windows powershell. Thank you!

**Comment by BillyONeal** [comment]
It is desirable to work on Linux as well.
