### ISSUE TITLE
[abseil] cant detect c++17 support

### ISSUE THREAD

**Issue by kreuzerkrieg** [microsoft/vcpkg#25481]
abseil is built with `gnu++11` flag with my gcc 9.4 on linux. Looks like this code 
```
vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
                     FEATURES
                     cxx17 ABSL_USE_CXX17
)
```
fails to detect c++17

**Environment**
- OS: Ubuntu 20.4
- Compiler: gcc 9.4

1. ./vcpkg install abseil
2. Try to use `absl::StrCat` with `std::string_view`

Temporary worked it around by
```
vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
                     INVERTED_FEATURES
                     cxx17 ABSL_USE_CXX17
)
```

**Comment by Cheney-W** [comment]
Please use following command to enable the c++17 in abseil:
`./vcpkg install abseil[cxx17]`

**Comment by kreuzerkrieg** [comment]
> Please use following command to enable the c++17 in abseil: `./vcpkg install abseil[cxx17]`

oooooh! Thank you very much! I guess this is the way the "feature" stuff works, I would never figure it out )
