### ISSUE TITLE
[boost-exception] Build error (cross-compile for Arm/Arm64 Android on Windows)

### ISSUE THREAD

**Issue by daminiac** [microsoft/vcpkg#25491]
**Host Environment**
- OS: [Windows]
- Compiler: revision

**To Reproduce**
`.\vcpkg.exe install boost-property-tree:arm-android`

**Failure logs**
Building boost-exception[core]:arm-android...
warning: -- Using community triplet arm-android. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\SW\vcpkg\triplets\community\arm-android.cmake
-- Using cached boostorg-exception-boost-1.79.0.tar.gz.
-- Cleaning sources at C:/SW/vcpkg/buildtrees/boost-exception/src/ost-1.79.0-1b4bdfb5ca.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/SW/vcpkg/downloads/boostorg-exception-boost-1.79.0.tar.gz
-- Using source at C:/SW/vcpkg/buildtrees/boost-exception/src/ost-1.79.0-1b4bdfb5ca.clean
-- Building release...
CMake Error: File C:/SW/vcpkg/installed/arm-android/share/boost-build/Jamroot.jam does not exist.
CMake Error at installed/x64-windows/share/boost-build/boost-modular-build.cmake:118 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:141 (unix_build)
  ports/boost-exception/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:146 (include)

vcpkg-tool version: 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e
vcpkg-scripts version: 339a9f5e1 2022-06-29 (2 hours ago)

**Comment by JackBoosY** [comment]
Please remove `boost-uninstall:arm-android` then try again.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
