### ISSUE TITLE
Building package opencv4:x64-mingw-dynamic/static failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by JackieYangGit** [microsoft/vcpkg#25492]
**Host Environment**
- OS: win11
- Compiler: mingw1120_64

**To Reproduce**
./vcpkg install opencv:x64-mingw-dynamic 
./vcpkg install opencv:x64-mingw-static 

**Failure logs**
error: building opencv4:x64-mingw-static failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+opencv4
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[opencv4]+Build+error
Include '[opencv4] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e
    vcpkg-scripts version: 339a9f5e1 2022-06-29 (3 hours ago)

**Additional context**
I have already tried the command `git pull` and `vcpkg update` ,  but still have this issue.

**Comment by JackBoosY** [comment]
Please provide the failure logs in the output first.

**Comment by longnguyen2004** [comment]
Try this branch of mine https://github.com/longnguyen2004/vcpkg/tree/opencv4

**Comment by dg0yt** [comment]
Mingw was fixed with #25431.
Related: https://github.com/microsoft/vcpkg/issues/25775

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This issue has been fixed, so I am closing this issue for now.
