### ISSUE TITLE
problem to install openni2 

### ISSUE THREAD

**Issue by Jayefo** [microsoft/vcpkg#25493]
D:\vcpkg\vcpkg\buildtrees\openni2\src\2.2-beta2-bffbc37bdc.clean\Source\Drivers\Kinect\KinectDriver.cpp(5,10): fatal error C1083: 无法打开包括文件: “atlstr.h”: No such file or directory [D:\vcpkg\vcpkg\buildtrees\openni2\src\2.2-beta2-bffbc37bdc.clean\Source\Drivers\Kinect\Kinect.vcxproj]

error: building openni2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openni2
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openni2]+Build+error
Include '[openni2] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e
    vcpkg-scripts version: b0ea874c7 2022-06-22 (7 days ago)

You can also use the prefilled template from D:\vcpkg\vcpkg\installed\vcpkg\issue_body.md.

**Comment by JackBoosY** [comment]
It should be a wtl issue and should be fixed by https://github.com/microsoft/vcpkg/pull/25229, can you please ensure your vcpkg is latest?

**Comment by JackBoosY** [comment]
Which Visual Studio version did you install?

**Comment by Jayefo** [comment]
VS 2019

**Comment by JackBoosY** [comment]
Sorry, `atlstr.h` should belong to Visual Studio component `ATLMFC`:
![image](https://user-images.githubusercontent.com/47264268/176634152-2c499c5c-6309-4c47-8417-3b941aa547aa.png)
Can you please install it then try again?

Thanks.

**Comment by Jayefo** [comment]
ok thanks i will try it right now

**Comment by Jayefo** [comment]
ok thanks i will try it right now

**Comment by Jayefo** [comment]
successfully solve it , thanks
