### ISSUE TITLE
[rapidjson:x64-windows] build failure (File does not have expected hash)

### ISSUE THREAD

**Issue by StarGate-One** [microsoft/vcpkg#25508]
**Host Environment**
- OS: [e.g. Windows/Linux etc...] Windows Version [10.0.22000.778] aka Windows 11 x64
- Compiler: revision
  Visual Studio Community 2022 Version: [17.2.5]  VS Tools Version: [14.31.31103] 
  Microsoft (R) C/C++ Optimizing Compiler Version [19.31.31107] for x64 

**To Reproduce**

`default/host triplet x64-windows`

`./vcpkg install rapidjson`

**Failure logs**
- Cut and paste the appropriate build messages from the console output.
`D:\vcpkg`
`->vcpkg install rapidjson`
`Computing installation plan...`
`The following packages will be built and installed:`
`    rapidjson[core]:x64-windows -> 2022-06-28`
`Installing 1/1 rapidjson:x64-windows...`
`Building rapidjson[core]:x64-windows...`
`CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:14 (message):`
``
``
`  File does not have expected hash:`
``
`          File path: [ D:/vcpkg-downloads/Tencent-rapidjson-232389d4f1012dddec4ef84861face2d2ba85709.tar.gz ]`
`          Expected hash: [ 60bfbfe4884122aa9ae8755531da18ce4a793bb217c06474dd8c5afe0f2f5df280c40be2f303c1740f5af14c7ad5cc2a57f08de5205cc7ab27d6166b0f49130d ]`
`        Actual hash: [ 0d7d751179abdaa6ebf6167d522651a2d13bc024d20c7e3f775c7397a8aab4cd866a6c91a55521ad7847e910822fcf982625c7308c74f5df663e6fd81336c9fc ]`
``
`  The cached file SHA512 doesn't match.  The file may have been corrupted.`
`  To re-download this file please delete cached file at path`
`  D:/vcpkg-downloads/Tencent-rapidjson-232389d4f1012dddec4ef84861face2d2ba85709.tar.gz`
`  and retry.`
``
`Call Stack (most recent call first):`
`  scripts/cmake/vcpkg_download_distfile.cmake:171 (z_vcpkg_download_distfile_test_hash)`
`  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)`
`  ports/rapidjson/portfile.cmake:2 (vcpkg_from_github)`
`  scripts/ports.cmake:146 (include)`
``
``
`error: building rapidjson:x64-windows failed with: BUILD_FAILED`
`Please ensure you're using the latest port files with `git pull` and `vcpkg update`.`
`Then check for known issues at:`
`    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+rapidjson`
`You can submit a new issue at:`
`    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[rapidjson]+Build+error`
`Include '[rapidjson] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.`
`    vcpkg-tool version: 2022-06-30-b4d664f526fda6a151f5092bfeaf9c726698b1c6`
`    vcpkg-scripts version: 881c1b04a 2022-06-30 (4 hours ago)`
``
`You can also use the prefilled template from D:\vcpkg\installed\vcpkg\issue_body.md.`

- Please attach any additional failure logs mentioned in the console output.
No log files generated

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
- I can see in commit in [[rapidjson][ms-gltf] Upgrade up to 2022-06-28 #21112](https://github.com/microsoft/vcpkg/pull/21112) the hash was originally 0d7d751179abdaa6ebf6167d522651a2d13bc024d20c7e3f775c7397a8aab4cd866a6c91a55521ad7847e910822fcf982625c7308c74f5df663e6fd81336c9fc but was change to 60bfbfe4884122aa9ae8755531da18ce4a793bb217c06474dd8c5afe0f2f5df280c40be2f303c1740f5af14c7ad5cc2a57f08de5205cc7ab27d6166b0f49130d where I am getting a mismatch just the opposite now.
- I thought I may have been getting a download issue, so I downloaded from the URL directly and the SHA512 was what it was originally, both the vcpkg downloaded version and manually downloaded version matched but different from the portfile.cmake???
- I checked the pipeline for this commit and unless I am mistaken, it did not appear port rapidjson was tested, so I would guess this is why it was not flagged as failure during the PR.

/cc: @FrankXie05 @dan-shaw @alexander-smyslov @NancyLi1013

**Comment by dg0yt** [comment]
> * I checked the pipeline for this commit and unless I am mistaken, it did not appear port rapidjson was tested, so I would guess this is why it was not flagged as failure during the PR.

If it wasn't tested in the last run, then it was tested and saved in artifact cache in a previous run, and reused in the last run.
(However, this implies that the source asset was not downloaded again.)

**Comment by Liiii007** [comment]
You can overwrite the SHA512 located in Line6 of `.\vcpkg\ports\rapidjson\portfile.cmake` for youself and it should work.
The correct SHA512 is 0d7d751179abdaa6ebf6167d522651a2d13bc024d20c7e3f775c7397a8aab4cd866a6c91a55521ad7847e910822fcf982625c7308c74f5df663e6fd81336c9fc
This is a temporary solution.

**Comment by StarGate-One** [comment]
> You can overwrite the SHA512 located in Line6 of `.\vcpkg\ports\rapidjson\portfile.cmake` for youself and it should work. The correct SHA512 is 0d7d751179abdaa6ebf6167d522651a2d13bc024d20c7e3f775c7397a8aab4cd866a6c91a55521ad7847e910822fcf982625c7308c74f5df663e6fd81336c9fc This is a temporary solution.

Thank you @Liiii007!!!
I tested/used @FrankXie05 fix to portfile.cmake to verify it worked properly. I then copied the fixed portfile.cmake into my production vcpkg and all is good until the fixed gets pushed into online vcpkg master.
Terrific work and suggestions all. 👍🏼 💯 🥇

**Comment by StarGate-One** [comment]
> > * I checked the pipeline for this commit and unless I am mistaken, it did not appear port rapidjson was tested, so I would guess this is why it was not flagged as failure during the PR.
> 
> If it wasn't tested in the last run, then it was tested and saved in artifact cache in a previous run, and reused in the last run. (However, this implies that the source asset was not downloaded again.)

@dg0yt I checked pipeline for x64-windows in #25509 (fix the hash for rapidjson), as I am trying to understand how the pipeline works, taking port rapidjson in this case, I could not find where the port was downloaded, extracted and installed or am I still missing something? 
Or is the pipeline somehow not detecting a change or as was mentioned it was downloaded in an earlier PR related to rapidjson or an earlier PR dealing with something else totally different?

Below are the log entries for rapidjson:x64windows (I removed the other ports for brevity to make easier readability):

`Detecting compiler hash for triplet "x64-windows"...`
`2022-07-01T03:05:36.1198087Z                    rapidjson:x64-windows:        *: b8683edf5e30f099c80b759296ca3671ff730bbb5f827edaecd4593c909bfcec`

`2022-07-01T03:05:36.9748977Z The following packages will be built and installed:`
`2022-07-01T03:05:37.6331405Z     rapidjson[core]:x64-windows -> 2022-06-28`

`2022-07-01T03:05:39.2523079Z Detecting compiler hash for triplet "x64-windows"...`
`2022-07-01T03:05:49.2783027Z                    rapidjson:x64-windows:     pass: 691d87d64ca412517c1839dca1222da828a230b53f11cb339efb8ce0dc22b330`

`2022-07-01T03:05:50.0938957Z Attempting to fetch 323 packages from HTTP servers.`
`2022-07-01T03:06:58.7223678Z Installing 129/346 rapidjson:x64-windows...`
`2022-07-01T03:06:58.7506346Z Elapsed time to handle rapidjson:x64-windows: 28.83 ms`

`2022-07-01T06:26:18.0911615Z RESULTS`

`2022-07-01T06:26:18.1506671Z     rapidjson:x64-windows: SUCCEEDED: 28.83 ms`

Complete pipeline log for [PR 25509 hash change for port rapidjson x64-windows.log](https://github.com/microsoft/vcpkg/files/9029719/PR.25509.hash.change.for.port.rapidjson.x64-windows.log)

Again just trying to understand better how CI pipeline works. 

Thank you all for the hard work you do on vcpkg, we all appreciate it very much.
I am one who wants to know why/how something works, rather than just accept is it works/not works, as I can review logs and help not only find issues, but help fix the issue. 👍🏼 💯 🥇 

Have a great holiday weekend everyone.

/cc: @BillyONeal

**Comment by dg0yt** [comment]
> Below are the log entries for rapidjson:x64windows (I removed the other ports for brevity to make easier readability):
> 
> `Detecting compiler hash for triplet "x64-windows"...` 
> `2022-07-01T03:05:36.1198087Z rapidjson:x64-windows: *: b8683edf5e30f099c80b759296ca3671ff730bbb5f827edaecd4593c909bfcec`

^^^ This is from a "dry-run" for the current state of master. It doesn't download or build any port, even if missing from artifact cache (`*` indicates missing). It is only used to save the artifact cache keys for each port (aka parent hashes). 

v  v  v Below ist the actual CI build. It only installs ports which have a changed artifact cache key (i.e. were modified by this PR), and of course their dependencies. However, "install" doesn't imply "build from source" here. It will prefer the cached artifact when available - and "pass" indicates that it is available for rapidjson, i.e. it was built succesfully in an earlier CI run for this PR (an earlier push) and not affected by later modifcations.

> `2022-07-01T03:05:36.9748977Z The following packages will be built and installed:`  
> `2022-07-01T03:05:37.6331405Z rapidjson[core]:x64-windows -> 2022-06-28`
> `2022-07-01T03:05:39.2523079Z Detecting compiler hash for triplet "x64-windows"...`  
> `2022-07-01T03:05:49.2783027Z rapidjson:x64-windows: pass: 691d87d64ca412517c1839dca1222da828a230b53f11cb339efb8ce0dc22b330`
> `2022-07-01T03:05:50.0938957Z Attempting to fetch 323 packages from HTTP servers.`  
> `2022-07-01T03:06:58.7223678Z Installing 129/346 rapidjson:x64-windows...`  
> `2022-07-01T03:06:58.7506346Z Elapsed time to handle rapidjson:x64-windows: 28.83 ms` 
> `2022-07-01T06:26:18.0911615Z RESULTS` 
> `2022-07-01T06:26:18.1506671Z rapidjson:x64-windows: SUCCEEDED: 28.83 ms` 

Now when was `691d87d64ca412517c1839dca1222da828a230b53f11cb339efb8ce0dc22b330` built`? I don't know. I cannot find an earlier CI run (and log) for this PR on AZP. But this is normal when such a run was canceled (e.g. by a new push). And indeed, you can see from the PR that there was a push for [3dac026](https://github.com/microsoft/vcpkg/pull/25509/commits/3dac0269fae76ca4117518470a81056132ce674a) which was [canceled before x64-windows finished](https://github.com/microsoft/vcpkg/runs/7143163363).

**Comment by StarGate-One** [comment]
@dg0yt - thanks, for the explanation.
