### ISSUE TITLE
Port requests - Cgicc, Jinja2CppLight

### ISSUE THREAD

**Issue by DragonOsman** [microsoft/vcpkg#2550]
Hi.

I'd like to make three port requests, if this is the right place for doing that (if not, please let me know), the names of which I are mentioned in the title of this post.  The latest stable release versions, if possible.

**Comment by JackBoosY** [comment]
Hi @DragonOsman , I am looking forward to your Pull Request! The document link here:
https://github.com/Microsoft/vcpkg/blob/master/docs/examples/packaging-github-repos.md
If you have any trouble with package a new port, I'm happy to help you.
Thx.

**Comment by AlvinZhangH** [comment]
Hi @DragonOsman,port cgicc and jinja2cpplight already added, thanks for reporting this issue.
