### ISSUE TITLE
[gdal 2.2.2] Fails to build in x86-windows

### ISSUE THREAD

**Issue by jslee02** [Microsoft/vcpkg#2551]
* The machine setup: Windows 10 Enterprise (10.0.16299 Build 16299) + vcpkg (0.0.101-2018-01-11-6bdc3bf9eb5cc93e579cddcbb01c41e991082c8c)
* Package and version I'm building: gdal 2.2.2
* The steps to reproduce: `vcpkg install gdal`
* The outcome I expected: building gdal w/o any errors
* The actual outcome: https://gist.github.com/jslee02/4674f53df7435693ffbeed46f76713f8

**Comment by ras0219-msft** [comment]
Thanks for posting!

Could you attach
> C:\Users\jslee02\dev\vcpkg\buildtrees\gdal\nmake-build-x86-windows-release-out.log
      C:\Users\jslee02\dev\vcpkg\buildtrees\gdal\nmake-build-x86-windows-release-err.log

**Comment by jslee02** [comment]
Here are the files:
https://gist.github.com/jslee02/da5b472da4d0bff54ceb6cda456652a0
https://gist.github.com/jslee02/f08777eec509f54d08c0548e4b5cca30

**Comment by ras0219-msft** [comment]
> frmts\o\ngsgeoiddataset.obj : fatal error LNK1136: invalid or corrupt file

I'm not sure what could cause this -- maybe a MAX_PATH issue?

Also note that it `libmysql` has dropped support for 32-bit Windows in the newest version, which also prevents gdal from compiling. Because of this, I'm going to close this issue for now.
