### ISSUE TITLE
[llvm[core,clang]] build failure

### ISSUE THREAD

**Issue by Chlorie** [microsoft/vcpkg#25511]
Triplet: x64-windows
OS: Windows 11

**To Reproduce**
`./vcpkg install llvm[core,clang]`

**Failure logs**
```
Installing 1/1 llvm:x64-windows...
Building llvm[clang,compiler-rt,core,enable-threads,tools]:x64-windows...
-- Note: llvm only supports static library linkage. Building static library.
-- Using cached llvm-llvm-project-llvmorg-14.0.4.tar.gz.
-- Cleaning sources at C:/UserFiles/Applications/vcpkg/buildtrees/llvm/src/org-14.0.4-df58f01928.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/UserFiles/Applications/vcpkg/downloads/llvm-llvm-project-llvmorg-14.0.4.tar.gz
-- Applying patch 0002-fix-install-paths.patch
-- Applying patch 0004-fix-dr-1734.patch
-- Applying patch 0005-fix-tools-path.patch
-- Applying patch 0007-fix-compiler-rt-install-path.patch
-- Applying patch 0009-fix-tools-install-path.patch
-- Applying patch 0010-fix-libffi.patch
-- Applying patch 0011-fix-install-bolt.patch
-- Using source at C:/UserFiles/Applications/vcpkg/buildtrees/llvm/src/org-14.0.4-df58f01928.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: C:/UserFiles/Applications/vcpkg/packages/llvm_x64-windows/share/clang/copyright
-- Installing: C:/UserFiles/Applications/vcpkg/packages/llvm_x64-windows/share/clang/usage
CMake Error at installed/x64-windows/share/vcpkg-cmake-config/vcpkg_cmake_config_fixup.cmake:129 (message):

  'C:/UserFiles/Applications/vcpkg/packages/llvm_x64-windows/debug/share/llvm'
  does not exist.
Call Stack (most recent call first):
  ports/llvm/portfile.cmake:267 (vcpkg_cmake_config_fixup)
  ports/llvm/portfile.cmake:281 (llvm_cmake_package_config_fixup)
  scripts/ports.cmake:146 (include)


error: building llvm:x64-windows failed with: BUILD_FAILED
```

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please provide the log: _[VCPKG_ROOT]/buildtrees/llvm/install-x64-windows-dbg-out.log_.

**Comment by Chlorie** [comment]
Sorry, I already deleted the log since the build tree was huge and I don't have much disk space left. I managed to get it built successfully by just editing the line reporting the error `vcpkg_cmake_config_fixup.cmake:129` from terminating on not finding the folder to just creating an empty folder. It's an ugly hack that I don't know what the consequences are but it was built successfully.

**Comment by Chlorie** [comment]
> * I personally use the `--clean-buildtrees-after-build` and `--clean-packages-after-build` as I do not care about the buildtrees sources after a successful port build nor do I use the export option of vcpkg so I do not care about the packages built after successful build...

Yes, I am cleaning the buildtrees and the packages manually.

But the install logs are contained in the buildtrees folder...

**Comment by StarGate-One** [comment]
> Yes, I am cleaning the buildtrees and the packages manually.
> 
> But the install logs are contained in the buildtrees folder...

@Chlorie 
I see what you mean, some of the ports have several megs of log/error files.

**Comment by LilyWangLL** [comment]
Could you test clone vcpkg to short path, like `C:/dev`, and rebuild `llvm`?

**Comment by LilyWangLL** [comment]
Ping @Chlorie for response.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
