### ISSUE TITLE
[ffmpeg[avisynthplus]] Could it be possible to have this as Static version too please ? 

### ISSUE THREAD

**Issue by jalba69** [microsoft/vcpkg#25534]
Hello,

Could it be possible to have **ffmpeg[avisynthplus]** able to be built with **static** triplet please ?

Right now when trying `vcpkg install FFmpeg[avisynthplus]:x64-windows-static` we get this :
`Error: ffmpeg[avisynthplus] is only supported on 'windows & !static'`

 but on the other hand it is possible to have the current single _AviSynthPlus_ as static installed, from my _vcpkg list_ :
`avisynthplus:x64-windows-static`

Same thing seems to happens when trying to build the main single FFMPEG port and setting manually AvisynthPlus as option to true there, we get an error message saying static version is not possible.

Is there any hard limitations to make AviSynthPlus possible as a Static version included in FFMPEG or maybe it was just an old limitation not reviewed since a while ? 

We have the single AvisynthPlus possible as Static then I imagine it should be possible, could you please look into this so it will be possible to have  **ffmpeg[avisynthplus]** static or maybe be able to manually modify the main FFmpeg to add AvisynthPlus option to the static version there ? 

Thanks a lot in advance :)

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Feature `ffmpeg[avisynthplus]` doesn't support static is changed by PR https://github.com/microsoft/vcpkg/pull/18803.
cc @mcmtroffaes I saw your comment in https://github.com/microsoft/vcpkg/pull/18803#:~:text=The%20library%20itself%20can%20be%20built%20statically%20since%203.7.0%2C%20however%20there%20are%20still%20some%20bugs%20with%20this%20build%20(which%20I%27ve%20reported%20upstream), is this the upstream PR https://github.com/AviSynth/AviSynthPlus/pull/222?

**Comment by mcmtroffaes** [comment]
Yes, I've been trying to get static builds to work with avisynthplus. I submitted four PR's upstream to that effect: https://github.com/AviSynth/AviSynthPlus/pull/192 https://github.com/AviSynth/AviSynthPlus/pull/219 https://github.com/AviSynth/AviSynthPlus/pull/221 https://github.com/AviSynth/AviSynthPlus/pull/222 - all are merged except the last one (i.e. the one you mention) although only Windows XP is affected for that one.

**Comment by mcmtroffaes** [comment]
... also I haven't checked recently if ffmpeg already supports static linking against avisynthplus. I don't think it does:

https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/avisynth.c

**Comment by mcmtroffaes** [comment]
... however I managed to dig out an old ffmpeg patch by one of the avisynthplus developers which enables a regularly linked avisynthplus: https://github.com/qyot27/FFmpeg/commit/e70f70a6d4e096bdf146bbf4a444299dc35421ef

In short: ffmpeg does not support regular linking against avisynthplus, and until they do, vcpkg cannot realistically support it either in the long term (IMO, as it's a rather hefty patch, better suited to be managed upstream).

**Comment by jalba69** [comment]
Hello, this is way out of my league but for what it's worth i done it manually :

Had `avisynthplus:x64-windows-static` installed, went to FFmpeg port folder, inside _vcpkg.json_ at lines 226 and 294 removed `& !static`

then :
`vcpkg install ffmpeg[core,ffmpeg,swresample,swscale,avdevice,avisynthplus]:x64-windows-static --clean-after-build`

And if i recall correctly that's all i done, needed those files for another thing, compiled other program seems to work correctly and accepts my avisynth .avs files. There might be some issues around, this i don't know but so far i managed to get it done this way.

**Comment by qyot27** [comment]
>And if i recall correctly that's all i done, needed those files for another thing, compiled other program seems to work correctly and accepts my avisynth .avs files. There might be some issues around, this i don't know yet, but so far i managed to get it done this way and it is working for the needs i have.

All that means is that there's already an `AviSynth.dll` somewhere on your library search paths from a previous install.  As mentioned, FFmpeg dynamically loads AviSynth using LoadLibrary, rather than by linking to either a shared or static version of the library.  The only thing an otherwise-static build of FFmpeg needs are the *headers* from AviSynth+, and it'll see and use an existing `AviSynth.dll`, if it exists.

>... however I managed to dig out an old ffmpeg patch by one of the avisynthplus developers which enables a regularly linked avisynthplus: https://github.com/qyot27/FFmpeg/commit/e70f70a6d4e096bdf146bbf4a444299dc35421ef

The newer version is cleaner: https://github.com/qyot27/FFmpeg/commits/avs_static
