### ISSUE TITLE
[vcpkg-tool][openssl] Vcpkg doesn't restore port from binary cache when ran from PowerShell

### ISSUE THREAD

**Issue by Thomas1664** [microsoft/vcpkg#25536]
**Describe the bug**

**Environment**
- OS: Windows 10 with VS 2022 and PowerShell 7.2.5

**To Reproduce**
Run the following commands from a PowerShell:
1. vcpkg install openssl
2. vcpkg remove openssl
3. vcpkg install openssl

**Expected behavior**
Restore `openssl` from binary cache

**Actual behavior**
Build `openssl` again

**Additional context**
This issue is specific to the PowerShell. If I run the same steps from cmd, everything works as expected.

`[DEBUG] Default binary cache path is: C:\Users\[...]\AppData\Local\vcpkg\archives` also appears on PowerShell

I also tried out other ports like `glm` and `nlohmann-json` but they work as expected from PowerShell. Only `openssl` fails.

**Comment by JackBoosY** [comment]
I can't repro this issue using [the official github release 7.2.5-win64](https://github.com/PowerShell/PowerShell/releases/download/v7.2.5/PowerShell-7.2.5-win-x64.zip) (https://github.com/PowerShell/PowerShell/releases/tag/v7.2.5).

Can you please add option `--debug` to the 2 install commands and provide the full output?
```
./vcpkg install openssl --debug
./vcpkg remove openssl
./vcpkg install openssl --debug
```

Thanks.

**Comment by JackBoosY** [comment]
Is this resolved?

**Comment by Thomas1664** [comment]
I can't reproduce the issue anymore.
