### ISSUE TITLE
Supports installation to different directories

### ISSUE THREAD

**Issue by aorandexiaohai** [microsoft/vcpkg#25541]
If library A depends on library B.
Now if I run "vcpkg install A", the default installed directory layout:

     include
          A
              A.h
          B 
              B.h
     lib
          A.lib
          B.lib
    bin
         A.dll
         B.dll

But what I want is:

    A
        include
            A.h
        lib
            A.lib
        bin
            A.dll

    B
      include
            B.h
      lib
          B.lib
      bin
         B.dll

**Comment by aorandexiaohai** [comment]
Duplicate, but no solution.

**Comment by JackBoosY** [comment]
Also duplicated to https://github.com/microsoft/vcpkg/discussions/18703, please track discussions.

**Comment by aorandexiaohai** [comment]
> Also duplicated to #18703, please track discussions.

Not duplicate.

**Comment by aorandexiaohai** [comment]
I found what I need in "packages" directory.
