### ISSUE TITLE
CloudCompare

### ISSUE THREAD

**Issue by TeamLK** [microsoft/vcpkg#25546]
Library name: CloudCompare

Library description: CloudCompare is a 3D point cloud (and triangular mesh) processing software

Source repository URL: https://github.com/CloudCompare/CloudCompare

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
