### ISSUE TITLE
[zlib] Build error

### ISSUE THREAD

**Issue by us3-r** [microsoft/vcpkg#25540]
**Host Environment**
- Host: x64-windows
- Compiler: MSVC 19.32.31332.0
-    vcpkg-tool version: 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e
    vcpkg-scripts version: 4826ede84 2022-07-01 (28 hours ago)

**To Reproduce**
`vcpkg install cpr`

**Failure logs**
```
-- Downloading https://github.com/madler/zlib/archive/v1.2.12.tar.gz -> madler-zlib-v1.2.12.tar.gz...
-- Extracting source C:/Users/gfhyt/vcpkg/downloads/madler-zlib-v1.2.12.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch debug-postfix-mingw.patch
-- Applying patch 0002-android-build-mingw.patch
-- Using source at C:/Users/gfhyt/vcpkg/buildtrees/zlib/src/v1.2.12-f2d39b538c.clean
-- Found external ninja('1.10.2').
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:83 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/Users/gfhyt/vcpkg/buildtrees/zlib/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\gfhyt\vcpkg\buildtrees\zlib\config-x86-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:238 (vcpkg_execute_required_process)
  ports/zlib/portfile.cmake:17 (vcpkg_cmake_configure)
  scripts/ports.cmake:146 (include)
```
**Additional context**
Tried to search for `PREFER_NINJA` in `\ports\zlib\portfile.cmake` file but couldn't find it.
The language in MS2022 is Englis
![Screenshot 2022-07-03 120839](https://user-images.githubusercontent.com/89808542/177034997-70686386-99c6-41bf-bc6b-cec4af7b6576.png)

**Comment by ShenMian** [comment]
I have the same error, using Manjaro Linux, which uses `pacman` as the package manager. but here it try to use `apt-get` to install a package.

**Comment by Cheney-W** [comment]
Could you please provide `C:\Users\gfhyt\vcpkg\buildtrees\zlib\config-x86-windows-out.log` to me?

**Comment by us3-r** [comment]
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/9039905/config-x86-windows-out.log)
Here you go :)

**Comment by ToukiLiu** [comment]
I have same problem when I try to install zlib and boots.

**Comment by Cheney-W** [comment]
Please refer to the solution here: https://github.com/microsoft/vcpkg/issues/21580

**Comment by Cheney-W** [comment]
Does this issue still exist?

**Comment by us3-r** [comment]
I would have no idea since I have tried to installer since back then

**Comment by JonLiu1993** [comment]
@us3-r, the latest version of  has been updated to 1.9.3, please try to see if this problem has been resolved.

**Comment by zanerogl** [comment]
> Please refer to the solution here: #21580

Hi, I have a same issue, but my environment is Linux, Is there any way to solve this problem?

**Comment by zanerogl** [comment]
> Please refer to the solution here: #21580

Hi, I have a same issue, but my environment is Centos7, Is there any way to solve this problem?
