### ISSUE TITLE
[New Port Request] gltf-toolkit

### ISSUE THREAD

**Issue by Yejneshwar** [microsoft/vcpkg#25558]
Library name: microsoft/glTF-Toolkit

Library description: This project contains a collection of tools and libraries to modify and optimize glTF assets.

Additionally the repository includes a command line tool that uses these steps in sequence in order to convert a glTF 2.0 core asset for use in the Windows Mixed Reality home, following the published [documentation](https://developer.microsoft.com/en-us/windows/mixed-reality/creating_3d_models_for_use_in_the_windows_mixed_reality_home). The latest release of the Windows Mixed Reality Asset converter is available on the [releases tab](https://github.com/Microsoft/glTF-Toolkit/releases)

Source repository URL: [gltf-toolkit](https://github.com/microsoft/glTF-Toolkit.git)

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included): Windows Mixed Reality Asset converter is available on the [releases tab](https://github.com/Microsoft/glTF-Toolkit/releases) as an .exe

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
