### ISSUE TITLE
[wxwidgets] Build Failed with x64-mingw-dynamic on Windows 10

### ISSUE THREAD

**Issue by ThIsJaCk23657689** [microsoft/vcpkg#25556]
Package: wxwidgets[core,sound]:x64-mingw-dynamic -> 3.1.6#2
**Host Environment**
- Host: x64-windows
- Compiler: GNU 10.3.0
-    vcpkg-tool version: 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e
    vcpkg-scripts version: 4826ede84 2022-07-01 (2 days ago)

**To Reproduce**
`vcpkg install wxwidgets`

**Failure logs**
```
-- Using cached wxWidgets-wxWidgets-35a6d7b15fedfdb5198bb6c28b31cda33b2c2a76.tar.gz.
-- Cleaning sources at C:/dev/vcpkg/buildtrees/wxwidgets/src/a33b2c2a76-d7830df458.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/wxWidgets-wxWidgets-35a6d7b15fedfdb5198bb6c28b31cda33b2c2a76.tar.gz
-- Applying patch install-layout.patch
-- Applying patch relocatable-wx-config.patch
-- Applying patch nanosvg-ext-depend.patch
-- Applying patch fix-libs-export.patch
-- Applying patch fix-pcre2.patch
-- Using source at C:/dev/vcpkg/buildtrees/wxwidgets/src/a33b2c2a76-d7830df458.clean
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at C:/dev/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Found external ninja('1.10.2').
-- Configuring x64-mingw-dynamic
-- Building x64-mingw-dynamic-dbg
-- Building x64-mingw-dynamic-rel
CMake Error at ports/wxwidgets/portfile.cmake:111 (file):
  file RENAME failed to rename

    C:/dev/vcpkg/packages/wxwidgets_x64-mingw-dynamic/bin/wx-config

  to

    C:/dev/vcpkg/packages/wxwidgets_x64-mingw-dynamic/tools/wxwidgets/wx-config

  because: �t�Χ䤣����w���ɮסC

Call Stack (most recent call first):
  scripts/ports.cmake:146 (include)

```

**Additional context**
I have tried `git pull` and `vcpkg upgrade` in the vcpkg root directory, but I still can not build wxWidgets completely.  I have tried `vcpkg install wxwidget --triplet=x64-windows` and it works, but I want use the `x64-mingw-dynamic` triplet.

And I don't know why my error message looks like in the wrong encoding, I've tried `chcp 65001` which didn't work. I have confirmed that message is "No such file or directory". 

I've checked the folder `C:/dev/vcpkg/packages/wxwidgets_x64-mingw-dynamic/bin/wx-config` which didn't exist, and the folder `C:/dev/vcpkg/packages/wxwidgets_x64-mingw-dynamic/tools/wxwidgets/wx-config` is empty.

**Comment by dg0yt** [comment]
Confirmed

> I've checked the folder `C:/dev/vcpkg/packages/wxwidgets_x64-mingw-dynamic/bin/wx-config` which didn't exist, and the folder `C:/dev/vcpkg/packages/wxwidgets_x64-mingw-dynamic/tools/wxwidgets/wx-config` is empty.

It is a script, not folders. And the source (`bin/wx-config`) is missing now.

**Comment by dg0yt** [comment]
Please test #25572.

**Comment by ThIsJaCk23657689** [comment]
> Please test #25572.

I've tested this PR #25572, and vcpkg installs wxWidgets with x64-mingw-dynamic triplet successfully. However, there is another problem that I'm getting error at cmake configuration with my project.

```
CMake Error at C:/Program Files/CMake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.23/Modules/FindwxWidgets.cmake:1025 (find_package_handle_standard_args)
  C:/dev/vcpkg/installed/x64-mingw-dynamic/share/wxwidgets/vcpkg-cmake-wrapper.cmake:49 (_find_package)
  C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:778 (include)
  CMakeLists.txt:41 (find_package)

-- Configuring incomplete, errors occurred!
```

I've tried setting the `wxWidgets_LIB_DIR` and `wxWidgets_ROOT_DIR` variables according to this discussion but with no luck: https://groups.google.com/g/wx-dev/c/i06WTStk2Nw/m/YtXWgpM3BAAJ

**Comment by dg0yt** [comment]
You shouldn't set any variables. `share/wxwidgets/vcpkg-cmake-wrapper.cmake`  is doing the work for you. 
I can test mingw on Windows later. 

> https://groups.google.com/g/wx-dev/c/i06WTStk2Nw/m/YtXWgpM3BAAJ

This is an old discussion and doesn't know about the wrapper. (`FindwxWidgets` doesn't seem to work well MinGW, but the wrapper was tested with wxWidgets 3.1.5.)

**Comment by dg0yt** [comment]
I was able to reproduce the new problem on Windows ... when `sh` was not in the `PATH`.

**Comment by dg0yt** [comment]
Can you test again? For native mingw builds (on windows), I switched to the MSVC layout, so that the find module can operatore in win32 mode, not needing `sh` for `wx-config`.
Downside: there is no `wx-config` for mingw on windows.

**Comment by ThIsJaCk23657689** [comment]
> Can you test again? For native mingw builds (on windows), I switched to the MSVC layout, so that the find module can operatore in win32 mode, not needing `sh` for `wx-config`. Downside: there is no `wx-config` for mingw on windows.

Now the cmake configuration problem is fixed, but unfortunately, I am getting numerous "undefined reference to" errors at linking status, and I am sure that I'm exactly following the cmake integration instruction add these code in `CMakeLists.txt`:
```
find_package(wxWidgets REQUIRED)
target_compile_definitions(${MY_EXECUTABLE} PRIVATE ${wxWidgets_DEFINITIONS} "$<$<CONFIG:DEBUG>:${wxWidgets_DEFINITIONS_DEBUG}>")
target_include_directories(${MY_EXECUTABLE} PRIVATE ${wxWidgets_INCLUDE_DIRS})
target_link_libraries(${MY_EXECUTABLE} PRIVATE ${wxWidgets_LIBRARIES})
```

The cmake log reports that it had found the libraries of wxWidgets (but some components are missing):
```
-- Found wxWidgets: C:/dev/vcpkg/installed/x64-mingw-dynamic/debug/lib/libwxmsw31ud_core.a;C:/dev/vcpkg/installed/x64-mingw-dynamic/debug/lib/libwxbase31ud.a;winmm;comctl32;uuid;oleacc;uxtheme;rpcrt4;shlwapi;version;wsock32 (found version "3.1.7") found components: core base missing components: png tiff jpeg zlib regex expat
-- Found wxWidgets: debug;C:/dev/vcpkg/installed/x64-mingw-dynamic/debug/lib/libwxmsw31ud_core.a;optimized;C:/dev/vcpkg/installed/x64-mingw-dynamic/lib/libwxmsw31u_core.a;debug;C:/dev/vcpkg/installed/x64-mingw-dynamic/debug/lib/libwxbase31ud.a;optimized;C:/dev/vcpkg/installed/x64-mingw-dynamic/lib/libwxbase31u.a;winmm;comctl32;uuid;oleacc;uxtheme;rpcrt4;shlwapi;version;wsock32 (found version "3.1.7") found components: core base missing components: png tiff jpeg zlib regex expat
-- Configuring done
-- Generating done
```

And there is the compile log:
```
====================[ Build | wxwidghets_hello | Debug ]========================
"C:\Program Files\CMake\bin\cmake.exe" --build C:\Users\user\Desktop\OpenGL\ProgramPlayground\Wxwidget\out\debug --target wxwidghets_hello -j 16
[0/2] Re-checking globbed directories...
[1/1] Linking CXX executable wxwidghets_hello.exe
FAILED: wxwidghets_hello.exe 
cmd.exe /C "cd . && C:\dev\TDM-GCC-64\bin\c++.exe -g  CMakeFiles/wxwidghets_hello.dir/src/auidemo.cpp.obj -o wxwidghets_hello.exe -Wl,--out-implib,libwxwidghets_hello.dll.a -Wl,--major-image-version,0,--minor-image-version,0  C:/dev/vcpkg/installed/x64-mingw-dynamic/debug/lib/libwxmsw31ud_core.a  C:/dev/vcpkg/installed/x64-mingw-dynamic/debug/lib/libwxbase31ud.a  -lwinmm  -lcomctl32  -luuid  -loleacc  -luxtheme  -lrpcrt4  -lshlwapi  -lversion  -lwsock32  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cmd.exe /C "cd /D C:\Users\user\Desktop\OpenGL\ProgramPlayground\Wxwidget\out\debug && "C:\Program Files\PowerShell\7\pwsh.exe" -noprofile -executionpolicy Bypass -file C:/dev/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/Users/user/Desktop/OpenGL/ProgramPlayground/Wxwidget/out/debug/wxwidghets_hello.exe -installedDir C:/dev/vcpkg/installed/x64-mingw-dynamic/debug/bin -OutVariable out""
C:/dev/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/wxwidghets_hello.dir/src/auidemo.cpp.obj: in function `MyFrame::MyFrame(wxWindow*, int, wxString const&, wxPoint const&, wxSize const&, long)':
C:/Users/user/Desktop/OpenGL/ProgramPlayground/Wxwidget/src/auidemo.cpp:652: undefined reference to `__imp__ZN12wxAuiManagerC1EP8wxWindowj'
...
...
(a lot of undefined reference to errors)
...
...
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

I don't why it crashed by this problem, and I've tried use x64-windows and MSVC, I got the same linking issues.

PS: I use TDM-GCC, does it cause the influence?

**Comment by dg0yt** [comment]
> missing components: png tiff jpeg zlib regex expat

These components are implicitly added in win32 mode of FindwxWidgets but it is not an error if they are missing unless requested explicitly. Maybe this eventually needs to be resolved, for explicit requests. But do the linking errors point to these libs?

> `C:/Users/user/Desktop/OpenGL/ProgramPlayground/Wxwidget/src/auidemo.cpp:652: undefined reference to '__imp__ZN12wxAuiManagerC1EP8wxWindowj'`

I'm not an wxWidgets expert. I guess you need to also request the `aui` component with the `find_package(wxWidgets` call. IIRC each lib is a separate component in wxWidgets. From the CI file list:
~~~
wxwidgets:x64-windows:/lib/wxbase31u.lib
wxwidgets:x64-windows:/lib/wxbase31u_net.lib
wxwidgets:x64-windows:/lib/wxbase31u_xml.lib
wxwidgets:x64-windows:/lib/wxmsw31u_adv.lib
wxwidgets:x64-windows:/lib/wxmsw31u_aui.lib
wxwidgets:x64-windows:/lib/wxmsw31u_core.lib
wxwidgets:x64-windows:/lib/wxmsw31u_gl.lib
wxwidgets:x64-windows:/lib/wxmsw31u_html.lib
wxwidgets:x64-windows:/lib/wxmsw31u_media.lib
wxwidgets:x64-windows:/lib/wxmsw31u_propgrid.lib
wxwidgets:x64-windows:/lib/wxmsw31u_qa.lib
wxwidgets:x64-windows:/lib/wxmsw31u_ribbon.lib
wxwidgets:x64-windows:/lib/wxmsw31u_richtext.lib
wxwidgets:x64-windows:/lib/wxmsw31u_stc.lib
wxwidgets:x64-windows:/lib/wxmsw31u_webview.lib
wxwidgets:x64-windows:/lib/wxmsw31u_xrc.lib
~~~
The default components were printed by CMake: `found components: core base`. 
Cf. https://docs.wxwidgets.org/trunk/overview_cmake.html#cmake_find_package
