### ISSUE TITLE
vcpkgsrv.exe unknown software exception (0xc0000096)

### ISSUE THREAD

**Issue by wxilas21** [microsoft/vcpkg#25566]
I've been getting an exception when I open Visual Studio for the past few days. Do you have any solution that might help?

![image](https://user-images.githubusercontent.com/16443513/177233330-55db3a2f-b39d-42b4-a50b-e7758148c55a.png)

**Comment by JackBoosY** [comment]
0xC0000096 `STATUS_PRIVILEGED_INSTRUCTION` `{EXCEPTION} Privileged instruction.`

**Comment by LilyWangLL** [comment]
This should be a Visual Studio bug, could you please report a feedback for Visual Studio? This is documentation of how to report a feeaback: https://developercommunity.visualstudio.com/report?space=8&entry=problem

**Comment by wxilas21** [comment]
> This should be a Visual Studio bug, could you please report a feedback for Visual Studio? This is documentation of how to report a feeaback: https://developercommunity.visualstudio.com/report?space=8&entry=problem

As you said, I asked for feedback. thank you

https://developercommunity.visualstudio.com/t/vcpkgsrvexe-unknown-software-exception/10087595?port=1025&fsid=6a43a249-1015-4ff5-b616-8d29a8baa28e&entry=myfeedback&ref=native&refTime=1657000229368&refUserId=9ff7c1cd-b75d-6b06-862a-46636bbe2a73

**Comment by LilyWangLL** [comment]
Since this issue has been reported to feedback, I am closing this issue for now.
