### ISSUE TITLE
BUILD_FAILED boost with icu and custom triplet

### ISSUE THREAD

**Issue by plasticbox** [microsoft/vcpkg#2556]
Hi.
I need a custom triplet. because our build machines serve various projects.
before modularize no problem. do you have any good idea?

**triplet file**
x64-custom.cmake
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
```

**before  Modularize**
`vcpkg install boost[locale-icu,regex-icu]:x64-custom --featurepackages`

**now**
`vcpkg install boost-locale[icu]:x64-custom boost-regex[icu]:x64-custom boost:x64-custom --featurepackages`

**Comment by PhoebeHui** [comment]
@plasticbox, does this still be a problem for you? you can reference https://github.com/microsoft/vcpkg/blob/5e40afca0d7286a9a7d742822cc2a1179a9e63fc/docs/users/triplets.md#community-triplets to set the custom triplets.

**Comment by PhoebeHui** [comment]
@plasticbox, please reopen this issue if it still be a problem for you.
