### ISSUE TITLE
[wtl] Visual Studio Wizard there but not working

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#25571]
****

**Is your feature request related to a problem? Please describe.**

After `vcpkg install wtl`, `AppWizard` for WTL is also installed, e.g. at
```
vcpkg\installed\x64-windows\share\wtl\AppWizard
```

**Proposed solution**

No idea, a clue below.

Earlier it works for Visual Studio 2022 Pro following the steps below
1. Copy folder<br>`wtl\AppWizard\Files`<br>into<br>`%PROGRAMFILES%\Microsoft Visual Studio\2022\Professional\Common7\IDE\VC\vcprojects`, <br>and rename it to "WTL"
2. Run `x64 Native Tools Command Prompt for VS 2022`
3. Run `devenv /updateconfiguration`

Now in Windows 11 and Visual Studio 2022 Pro 17.2.5, it doesn't work any more.
At https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/wizard-dot-vsz-file?view=vs-2022, `VSWizard` version is 8.0, but by only changing the version, it still doesn't work.

**Describe alternatives you've considered**

If not supported, AppWizard should not be installed, considering:
* `vcpkg install` need admin privilege to copy inito `%PROGRAMFILES%`, it also needs to find `devenv`
* `vcpkg remove` should be well supported in this situation

**Comment by Cheney-W** [comment]
If you download WTL10 build 10320 Release directly from https://sourceforge.net/projects/wtl/files, will the issue recur? If yes, please submit a feedback ticket on [Developer Community](https://developercommunity.visualstudio.com/report?space=62&entry=problem).

**Comment by playgithub** [comment]
> If you download WTL10 build 10320 Release directly from https://sourceforge.net/projects/wtl/files, will the issue recur? If yes, please submit a feedback ticket on [Developer Community](https://developercommunity.visualstudio.com/report?space=62&entry=problem).

Yes, tried and failed
![image](https://user-images.githubusercontent.com/3665590/177528001-f101e8df-c4c6-447c-b474-cd8c14dc5715.png)

**Comment by playgithub** [comment]
I've failed to post a ticket. Any help? Ticket as below

### Title
WTL AppWizard doesn't not work for VS2022

### Env
Windows 11 Pro
Visual Studio 2022 Pro 17.2.5
WTL 10.0.10320

### Problem

Earlier it works for Visual Studio 2022 Pro after running `setup.js` which installs VsWizard for WTL.
Now in Windows 11 and Visual Studio 2022 Pro 17.2.5, it doesn't work any more.
At https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/wizard-dot-vsz-file?view=vs-2022, VSWizard version is 8.0, but by changing the version, it still doesn't work.

### More Info

`devenv /updateconfiguration` applied manually

**Comment by Cheney-W** [comment]
I have submitted this issue on Developer Community:
https://developercommunity.visualstudio.com/t/WTL-AppWizard-doesnt-not-work-for-VS202/10088655

**Comment by Cheney-W** [comment]
Please pay attention to and reply to the information on [10088655](https://developercommunity.visualstudio.com/t/WTL-AppWizard-doesnt-not-work-for-VS202/10088655) in time. Thank you!

**Comment by Cheney-W** [comment]
@playgithub There is a new comment on [10088655](https://developercommunity.visualstudio.com/t/WTL-AppWizard-doesnt-not-work-for-VS202/10088655), could you please take a look? Thank you!

**Comment by playgithub** [comment]
It works now, maybe because of some updates.

Thanks

**Comment by allenk** [comment]
Since I needed to use WTL again, I found that WTL did not work in VS2022, so I updated my project WTL Wizard VS2017 and made it work for VS2022.

[WTL-Wizard-VS2022](https://github.com/allenk/WTL-Wizard-VS2017)

If anyone is still interested in WTL, you can try my updated version.
