### ISSUE TITLE
[<vtk>] build failure

### ISSUE THREAD

**Issue by seewjr** [microsoft/vcpkg#25579]
**Host Environment**
- OS: Windows 10
- Compiler: MSVC++ 14.3 （VS2022) 

**To Reproduce**
**First set the vtk environment to x64**
VCPKG_DEFAULT_TRIPLET=x64-windows
`./vcpkg install vtk[all]`

**Failure logs**
-- VTK module debug building: VTK::TestingGenericBridge is being built
-- VTK module debug building: VTK::FiltersAMR is being built
-- VTK module debug building: VTK::RenderingVolumeAMR is being built
-- VTK module debug building: VTK::RenderingRayTracing is being built
CMake Warning at C:/VCPKG/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package):
  By not providing "Findospray.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ospray", but
  CMake did not find one.

  Could not find a package configuration file provided by "ospray" (requested
  version 2.1) with any of the following names:

    osprayConfig.cmake
    ospray-config.cmake

  Add the installation prefix of "ospray" to CMAKE_PREFIX_PATH or set
  "ospray_DIR" to a directory containing one of the above files.  If "ospray"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMake/vtkModule.cmake:4222 (find_package)
  Rendering/RayTracing/CMakeLists.txt:58 (vtk_module_find_package)

CMake Error at CMake/vtkModule.cmake:4228 (message):
  Could not find the ospray external dependency.
Call Stack (most recent call first):
  Rendering/RayTracing/CMakeLists.txt:58 (vtk_module_find_package)

-- Configuring incomplete, errors occurred!
See also "C:/VCPKG/vcpkg/buildtrees/vtk/x64-windows-dbg/CMakeFiles/CMakeOutput.log".
See also "C:/VCPKG/vcpkg/buildtrees/vtk/x64-windows-dbg/CMakeFiles/CMakeError.log".
ninja: build stopped: subcommand failed.

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/9045647/config-x64-windows-out.log)

**Comment by seewjr** [comment]
It seems that vcpkg doesn't have the port of ospray. I have downloaded the ospray source code from github and set the ospray_DIR to the directory of the ospray's cmake folder but it doesn't works. 

I have also installed the Intel oneAPI toolkit which has the ospray lib but I don't know how to let vcpkg link it.

**Comment by JackBoosY** [comment]
Confirmed, `visrtx` also not found.
No idea why our pipeline didn't test it.

**Comment by JackBoosY** [comment]
Will be fixed by https://github.com/microsoft/vcpkg/pull/24740

**Comment by soroush** [comment]
Any progress on this? We also need it.
