### ISSUE TITLE
error: building vcpkg-cmake:x64-linux failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by suichanwa** [microsoft/vcpkg#25576]
**Host Environment**
- i've use arch linux with latest update
- gcc 12.1.0

**To Reproduce**

i've been trying to install opencv2 with vckpg by using comand `sudo vcpkg install opencv2`

**Failure logs**
Computing installation plan...
The following packages will be built and installed:
  * atk[core]:x64-linux -> 2.38.0#1
  * brotli[core]:x64-linux -> 1.0.9#2
  * bzip2[core]:x64-linux -> 1.0.8#2
  * cairo[core,fontconfig,freetype,gobject,x11]:x64-linux -> 1.17.6#2
  * eigen3[core]:x64-linux -> 3.4.0#2
  * expat[core]:x64-linux -> 2.4.8#1
  * fontconfig[core]:x64-linux -> 2.14.0#2
  * freetype[brotli,bzip2,core,png,zlib]:x64-linux -> 2.12.1
  * fribidi[core]:x64-linux -> 1.0.12
  * gdk-pixbuf[core]:x64-linux -> 2.42.8#2
  * getopt[core]:x64-linux -> 0#2
  * glib[core]:x64-linux -> 2.70.5#2
  * gperf[core]:x64-linux -> 3.1#4
  * graphene[core]:x64-linux -> 1.10.2#2
  * gtk[core]:x64-linux -> 4.6.2
  * harfbuzz[core]:x64-linux -> 4.2.0#1
  * libepoxy[core]:x64-linux -> 1.5.9#1
  * libffi[core]:x64-linux -> 3.4.2#5
  * libjpeg-turbo[core]:x64-linux -> 2.1.3#3
  * liblzma[core]:x64-linux -> 5.2.5#6
  * libpng[core]:x64-linux -> 1.6.37#18
  * libsass[core]:x64-linux -> 3.6.5#1
  * libuuid[core]:x64-linux -> 1.0.3#11
  * lzo[core]:x64-linux -> 2.10#7
    opencv2[core,default-features,eigen,gtk,jpeg,png,tiff]:x64-linux -> 2.4.13.7#13
  * pango[core]:x64-linux -> 1.50.7
  * pcre[core]:x64-linux -> 8.45#3
  * pixman[core]:x64-linux -> 0.40.0#2
  * pthread[core]:x64-linux -> 3.0.0#1
  * pthreads[core]:x64-linux -> 3.0.0#10
  * sassc[core]:x64-linux -> 3.6.2
  * tiff[core,jpeg,lzma,zip]:x64-linux -> 4.4.0#1
  * vcpkg-cmake[core]:x64-linux -> 2022-05-10#1
  * vcpkg-cmake-config[core]:x64-linux -> 2022-02-06#1
  * vcpkg-get-python-packages[core]:x64-linux -> 2022-04-11#1
  * vcpkg-tool-meson[core]:x64-linux -> 0.62.1
  * zlib[core]:x64-linux -> 1.2.12#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet "x64-linux"...
Restored 0 packages from /root/.cache/vcpkg/archives in 125.3 us. Use --debug to see more details.
Installing 1/37 vcpkg-cmake:x64-linux...
Building vcpkg-cmake[core]:x64-linux...
-- Installing: /opt/vcpkg/packages/vcpkg-cmake_x64-linux/share/vcpkg-cmake/vcpkg_cmake_configure.cmake
-- Installing: /opt/vcpkg/packages/vcpkg-cmake_x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake
-- Installing: /opt/vcpkg/packages/vcpkg-cmake_x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake
-- Installing: /opt/vcpkg/packages/vcpkg-cmake_x64-linux/share/vcpkg-cmake/vcpkg-port-config.cmake
CMake Error at ports/vcpkg-cmake/portfile.cmake:13 (file):
  file INSTALL cannot find "/opt/vcpkg/LICENSE.txt": No such file or
  directory.
Call Stack (most recent call first):
  scripts/ports.cmake:146 (include)

error: building vcpkg-cmake:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+vcpkg-cmake
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[vcpkg-cmake]+Build+error
Include '[vcpkg-cmake] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e
    vcpkg-scripts version: unknown

You can also use the prefilled template from /opt/vcpkg/installed/vcpkg/issue_body.md.

**Comment by dg0yt** [comment]
> file INSTALL cannot find "/opt/vcpkg/LICENSE.txt": No such file or directory.
> ...
> vcpkg-scripts version: unknown

Your vcpkg at `/opt/vcpkg` is incomplete.
Better use a git checkout.

**Comment by suichanwa** [comment]
>Better use a git checkout\


What you mean? can i get link?

**Comment by LilyWangLL** [comment]
Did you use git to clone vcpkg? 

> Your vcpkg at /opt/vcpkg is incomplete.

**Comment by dg0yt** [comment]
> > Better use a git checkout\
> 
> What you mean? can i get link?

Here is the Quick Start from the README:
https://github.com/microsoft/vcpkg#quick-start-windows

**Comment by suichanwa** [comment]
> Did you use git to clone vcpkg?
> 
> > Your vcpkg at /opt/vcpkg is incomplete.

yep i already do that

**Comment by suichanwa** [comment]
k guys, for some reason now he works, may when i trying to install on the last week i deed something wrong, thx all
