### ISSUE TITLE
[readline(win32)] Readline package not found by CMake

### ISSUE THREAD

**Issue by luizfernandonb** [microsoft/vcpkg#25589]
**Describe the bug**
Well, when installing the readline package (readline-win32), vcpkg doesn't give the hint on how to import this library into the project.

![image](https://user-images.githubusercontent.com/42288418/177405375-60e66cd9-3842-45d2-8af9-47a39ddfb5e6.png)

When trying to guess the name of the library, CMake warns by Intelisense that it did not find the library.
![image](https://user-images.githubusercontent.com/42288418/177405556-438fa3a9-913a-4a65-bc5d-1addec05b184.png)

When compiling, another error appears.

1> [CMake] CMake Error at D:/Programacao/Repositorios/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package):
1> [CMake]   Could not find a package configuration file provided by "readline" with any
1> [CMake]   of the following names:
1> [CMake] 
1> [CMake]     readlineConfig.cmake
1> [CMake]     readline-config.cmake
1> [CMake] 
1> [CMake]   Add the installation prefix of "readline" to CMAKE_PREFIX_PATH or set
1> [CMake]   "readline_DIR" to a directory containing one of the above files.  If
1> [CMake]   "readline" provides a separate development package or SDK, be sure it has
1> [CMake]   been installed.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   CMakeLists.txt:14 (find_package)
1> [CMake] -- Configuring incomplete, errors occurred!

**Environment**
- OS: Windows 10
- Compiler: MSVC

**To Reproduce**
1. ./vcpkg install readline-win32
2. Try to import this library into your project (somehow why won't vpckg tell you what the name of the library is for you to import via find_package())
3. Compile case you can import

**Expected behavior**
I can import the library, use it normally and compile it with my project.

**Failure logs**
It doesn't have an error log other than the Visual Studio console output.

**Additional context**
Nothing.

**Comment by Adela0814** [comment]
I will export a usage for `readline-win32`
