### ISSUE TITLE
[imgui] Set C++ 11 standard in CMakeLists.txt

### ISSUE THREAD

**Issue by xaedes** [microsoft/vcpkg#25588]
****

**Is your feature request related to a problem? Please describe.**
When compiling imgui with vcpkg on Ubuntu Xenial the compiler rightfully complains about needing C++ 11 for `constexpr` which is used in imgui code.

**Proposed solution**
The CMakeLists.txt should set the compiler flags for C++ 11, as the code contains C++ 11 features.

**Describe alternatives you've considered**
I tried setting `CMAKE_CXX_STANDARD=11` from the outside (e.g. with `cmake -DCMAKE_CXX_STANDARD=11 ....`), which should enable C++ 11 in imgui code, but it does not get propagated by vcpkg. 
Switching to another compiler so it defaults to C++ 11 might be an last resort alternative.

**Additional context**
This is the compilation error that I get on a fresh ubuntu:xenial. Well mostly fresh: as vcpkg needs at least cmake-3.7 and ubuntu:xenial does not provide it, cmake-3.8.2 is compiled from source - but that should make no difference on the compilation error:

```
.../vcpkg/buildtrees/imgui/src/v1.88-34c93572a3.clean/imgui.h:252:5: error: ‘constexpr’ does not name a type
     constexpr ImVec2()                      : x(0.0f), y(0.0f) { }
     ^
.../vcpkg/buildtrees/imgui/src/v1.88-34c93572a3.clean/imgui.h:252:5: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
.../vcpkg/buildtrees/imgui/src/v1.88-34c93572a3.clean/imgui.h:253:5: error: ‘constexpr’ does not name a type
     constexpr ImVec2(float _x, float _y)    : x(_x), y(_y) { }
     ^
.../vcpkg/buildtrees/imgui/src/v1.88-34c93572a3.clean/imgui.h:253:5: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11

... goes on forever...
```

**Comment by dg0yt** [comment]
There is nothing fresh about Ubuntu Xenial (16.04) ;-)
And vcpgk will need and use a much fresher CMake (3.22) to build ports. You can use CMake 3.7 for user project but YMMV.

**Comment by lerppana** [comment]
Is it better to use `cxx_std_11` meta feature instead of locking the version number? This should indicate cmake to use at least 11 instead of exactly 11. Honest question, I do not know.

**Comment by xaedes** [comment]
> There is nothing fresh about Ubuntu Xenial (16.04) ;-) And vcpgk will need and use a much fresher CMake (3.22) to build ports. You can use CMake 3.7 for user project but YMMV.

Yea, Xenial is truly not that fresh in itself. But officially supported by vcpkg^^. I think you need at least cmake 3.7 for vcpkg to automatically download cmake 3.22 which it then uses.
