### ISSUE TITLE
Add post built checks about the crt used

### ISSUE THREAD

**Issue by alexkaratarakis** [Microsoft/vcpkg#256]

**Comment by barcharcraz** [comment]
is the internal PE parser mature enough to use for this? Also I don't know how static libs declare dependencies (beyond just unresolved symbols).

**Comment by alexkaratarakis** [comment]
At this point, the PE parser reads very specific data from the binaries, namely architecture used. 
Therefore, it would require a bit of modification. 
The crt checks that were added around bf7978dcf962c8ff37b3319121e60eb1629be684 are currently calling dumpbin.

**Comment by alexkaratarakis** [comment]
Also, static libs are not linked, so there aren't any dependencies besides the unresolved symbols.

**Comment by alexkaratarakis** [comment]
Closing resolved issue.
