### ISSUE TITLE
Modular Boost removed GZIP support in Boost iostreams

### ISSUE THREAD

**Issue by rjoco** [Microsoft/vcpkg#2562]
Tested this in the Master branch.

1) Installed boost with "vcpkg install boost:x64-windows"
2) Made a CMake app that uses boost zip iterators in VS2017
3) Tried to compile the app but received bzip and gzip linking errors:
error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl boost::iostreams::detail::gzip_header::~gzip_header(void)" (__imp_??1gzip_header@detail@iostreams@boost@@QEAA@XZ) referenced in function "unsigned __int64 __cdecl UnCompress(enum COMPRESSION_MODE,char *,unsigned __int64,char *,unsigned __int64)" (?UnCompress@@YA_KW4COMPRESSION_MODE@@PEAD_K12@Z)
…

I switched to an old vcpkg branch that didn't use modular boost from early December and the same app linked fine. Am I doing something wrong?

**Comment by dbenson2000** [comment]
I believe I'm able to resolve this issue with this pull request:
https://github.com/Microsoft/vcpkg/pull/2589

**Comment by cmpute** [comment]
Shouldn't this issue be closed?

**Comment by JackBoosY** [comment]
Hi everyone, thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
