### ISSUE TITLE
[cairo] Cmake can't find package

### ISSUE THREAD

**Issue by MikeGitb** [Microsoft/vcpkg#2563]
I've installed cairo and Visual Studio 2017 finds it in normal projects (both header and library).

However, when I call  `find_package(Cairo REQUIRED)` in a cmake project (configured with -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake) cmake is unable to find it and stops with the usual message

    CMake Error at C:/vcpkg/scripts/buildsystems/vcpkg.cmake:216 (_find_package):
    1>   By not providing "FindCairo.cmake" in CMAKE_MODULE_PATH this project has
    1>   asked CMake to find a package configuration file provided by "Cairo", but
    1>   CMake did not find one.
    [...]

The same happens when I spell the package `cairo` or `CAIRO`. Does the packege have a different name or is this a bug?

**Comment by ras0219-msft** [comment]
Unfortunately, it's neither :(

The Cairo project doesn't provide CMake integration files, so we don't have them. We are considering adjusting this policy, but in the immediate term your best approach is to use something like:
```cmake
find_library(CAIRO_LIB_DEBUG cairod)
find_library(CAIRO_LIB_RELEASE cairo)
find_library(CAIRO_GOBJECT_LIB_DEBUG cairo-gobjectd)
find_library(CAIRO_GOBJECT_LIB_RELEASE cairo-gobject)

find_path(CAIRO_INCLUDE_DIR cairo/cairo.h)


target_include_directories(main PRIVATE ${CAIRO_INCLUDE_DIR})
target_link_libraries(main PRIVATE $<$<CONFIG:Debug>:${CAIRO_LIB_DEBUG}> $<$<CONFIG:Release>:${CAIRO_LIB_RELEASE}>)
```

**Comment by MikeGitb** [comment]
@ras0219-msft: Thanks for the explanation. I added my opinion to the linked thread. Maybe the above snipped could be used to extend the documentation (Most of it is already in the usage example, but not the separatation for release and debug).

**Comment by WolvenSpirit** [comment]
After all these years it seems this issue still exists, unfortunately @ras0219-msft fix didn't work for me.

Here's what worked:

```cmake
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/vcpkg/installed/x64-linux/include/cairo)
target_link_directories(your-project-name PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/vcpkg/installed/x64-linux/lib/cairo)
```
In case your vcpkg clone is not symlinked to your project dir then just replace it with your path to vcpkg.
