### ISSUE TITLE
[openssl] Build error

### ISSUE THREAD

**Issue by 1glassof** [microsoft/vcpkg#25647]
**Host Environment**
- OS: Windows wsl 1 ubuntu 20
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs**
error: building openssl:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openssl]+Build+error
Include '[openssl] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e
    vcpkg-scripts version: e6c8c2bc0 2022-07-07 (15 hours ago)

You can also use the prefilled template from /home/shortlegdog/Desktop/OpentelemetryTry/OpenCpp/tools/vcpkg/installed/vcpkg/issue_body.md.

**Additional context**
 ./vcpkg  install opentelemetry-cpp
sudo ./vcpkg  install opentelemetry-cpp

**Comment by JackBoosY** [comment]
Can you please provide the failure logs which mentioned in the output first?

Thanks.

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
