### ISSUE TITLE
[cmake] find_package(MagnumPlugins) doesn't work in static tripplets

### ISSUE THREAD

**Issue by Stof25** [Microsoft/vcpkg#2564]
After building magnum-plugins, the header files aren't copied in `vcpkg\installed\x64-windows\include\MagnumPlugins`. The dlls are correctly found though.

As a result, using `find_package(MagnumPlugins REQUIRED)` in a CMakeLists.txt fails with the error:

```
CMake Error at C:/Program Files/CMake/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find MagnumPlugins (missing: MAGNUMPLUGINS_INCLUDE_DIR
  PngImporter)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  E:/dev/vcpkg/installed/x64-windows/share/cmake/MagnumPlugins/FindMagnumPlugins.cmake:354 (find_package_handle_standard_args)
  E:/dev/vcpkg/installed/x64-windows/share/cmake/MagnumPlugins/MagnumPluginsConfig.cmake:26 (include)
  E:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:216 (_find_package)
  src/CMakeLists.txt:11 (find_package)
```

This isn't the first error though but I can confirm that no headers were installed for this package.

The previous error I got seems unrelated but here it is in case it matters :
```
CMake Error at E:/dev/vcpkg/installed/x64-windows/share/cmake/MagnumPlugins/FindMagnumPlugins.cmake:305 (set_property):
  Property INTERFACE_LINK_LIBRARIES may not contain link-type keyword
  "optimized".  The INTERFACE_LINK_LIBRARIES property may contain
  configuration-sensitive generator-expressions which may be used to specify
  per-configuration rules.
Call Stack (most recent call first):
  E:/dev/vcpkg/installed/x64-windows/share/cmake/MagnumPlugins/MagnumPluginsConfig.cmake:26 (include)
  E:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:216 (_find_package)
  src/CMakeLists.txt:11 (find_package)


CMake Error at E:/dev/vcpkg/installed/x64-windows/share/cmake/MagnumPlugins/FindMagnumPlugins.cmake:325 (set_property):
  Property INTERFACE_LINK_LIBRARIES may not contain link-type keyword
  "optimized".  The INTERFACE_LINK_LIBRARIES property may contain
  configuration-sensitive generator-expressions which may be used to specify
  per-configuration rules.
Call Stack (most recent call first):
  E:/dev/vcpkg/installed/x64-windows/share/cmake/MagnumPlugins/MagnumPluginsConfig.cmake:26 (include)
  E:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:216 (_find_package)
  src/CMakeLists.txt:11 (find_package)
```
Those seem more meant for the magnum devs.

**Comment by mosra** [comment]
Hi!

I just fixed the `INTERFACE_LINK_LIBRARIES` errors in mosra/magnum-plugins@e4c0d2ea1c4daf35ac75d0d22a672fdd50b1126d, installing plugins with `--head` should pick that change up I think.

For the other error -- I think this line may be the culprit: https://github.com/Microsoft/vcpkg/blob/43098d47ab8773e2bf463930f0a054714e2a0377/ports/magnum-plugins/portfile.cmake#L48 As far as I can tell, it already works properly for release libraries, moving this line inside the `else()` conditional below would make it work for debug libraries as well.

Unfortunately I have no access to a Windows machine at the moment, so I can't provide a tested patch. Help welcome :)
