### ISSUE TITLE
[Qt5-SVG] build failure

### ISSUE THREAD

**Issue by nickanthony-dgl** [microsoft/vcpkg#25653]
**Host Environment**
- OS: Windows 10
- Compiler: MSVC 14.32
- vcpkg-tool version: 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e
- vcpkg-scripts version: 98f8d00e8 2022-07-08 (8 hours ago)

**To Reproduce**
I was having an issue with installing Qt5 where the process would randomly hang. It seems this is an issue with Jom and I'm not the only person to run into it. In this issue #25634 I was advised to use `set(VCPKG_QMAKE_USE_NMAKE ON)` in my triplet file and that appears to have resolved the issue. However, I am now getting a different issue that I think has to do with the Qt5-SVG not correctly handling the `VCPKG_QMAKE_USE_NMAKE` option.

**Failure logs**
Here is the output to the console:
```
-- Package build-x64-windows-wavetracer-dbg
1> [CMake] CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
1> [CMake]     Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/Hostx64/x64/nmake.exe" -j 17
1> [CMake]     Working Directory: C:/vcpkg/buildtrees/qt5-svg/x64-windows-myproject-dbg
1> [CMake]     See logs for more information:
1> [CMake]       C:\vcpkg\buildtrees\qt5-svg\package-build-x64-windows-myproject-dbg-err.log
1> [CMake] 
1> [CMake] Call Stack (most recent call first):
1> [CMake]   scripts/cmake/vcpkg_build_qmake.cmake:3 (vcpkg_execute_build_process)
1> [CMake]   scripts/cmake/vcpkg_build_qmake.cmake:75 (z_run_jom_build)
1> [CMake]   C:/Users/NicholasAnthony/source/repos/wt_gui/out/build/MSVC-Debug/vcpkg_installed/x64-windows-myproject/share/qt5/qt_build_submodule.cmake:14 (vcpkg_build_qmake)
1> [CMake]   C:/Users/NicholasAnthony/source/repos/wt_gui/out/build/MSVC-Debug/vcpkg_installed/x64-windows-myproject/share/qt5/qt_submodule_installation.cmake:9 (qt_build_submodule)
1> [CMake]   ports/qt5-svg/portfile.cmake:2 (qt_submodule_installation)
1> [CMake]   scripts/ports.cmake:146 (include)
1> [CMake] error: building qt5-svg:x64-windows-myproject failed with: BUILD_FAILED
```

Here is the content of "qt5-svg/package-build-x64-windows-myproject-dbg-err":
```

Microsoft (R) Program Maintenance Utility Version 14.32.31332.0
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1065: invalid option 'j'
Stop.
```

**Comment by JackBoosY** [comment]
I heard about this before, @Neumann-A any ideas?

**Comment by dg0yt** [comment]
With `nmake`, you cannot use parallel jobs (`-j`) - this is the whole point of `jom`.

I would suggest to try a shorter build path first. We know that Qt has issues with long paths on Windows.

**Comment by Neumann-A** [comment]
https://github.com/microsoft/vcpkg/blob/98f8d00e89fb6a8019c2045cfa1edbe9d92d3405/scripts/cmake/vcpkg_build_qmake.cmake#L4-L5

need to conditionally add `-j` flags. If `VCPKG_QMAKE_USE_NMAKE` is set it shouldn't add `-j` flags

**Comment by nickanthony-dgl** [comment]
> I would suggest to try a shorter build path first. We know that Qt has issues with long paths on Windows.

I already have VCPKG at C:/VCPKG. Would it matter that the project I'm running the manifest for has a long path?



> 
> need to conditionally add `-j` flags. If `VCPKG_QMAKE_USE_NMAKE` is set it shouldn't add `-j` flags

That seems right to me. Right now it looks like "-j" is hardcoded in to the function. I don't know that I know CMake well enough to do this in a clean way. Maybe it makes sense to leave that function as is and just have an entirely separate function run in the case of NMake?

**Comment by nickanthony-dgl** [comment]
Just wanted to check in if there is any feedback on how to properly fix this issue.

**Comment by sfhacker** [comment]
This OPEN issue is from 2022!

**Comment by dg0yt** [comment]
@JonLiu1993 Is there a reason why you are working against the Stale bot?

**Comment by JonLiu1993** [comment]
This issue is about a tool update and has no resolution, so we should not let it be closed due to being old.
