### ISSUE TITLE
[minizip] unzGetCurrentFileInfo not working

### ISSUE THREAD

**Issue by ITotalJustice** [microsoft/vcpkg#25676]
**Describe the bug**
For some reason, unzGetCurrentFileInfo is not working when linking against vcpkg build of minizip.
The function returns that it was successful, however the `info` and `filename` params are not filled in.
Strangely, if using `unzGetCurrentFileInfo64`, then the `filename` param is filled in, but `info` struct still isn't.

The miniunz binary that gets built with vcpkg still works, this is because it does not query the `info.uncompressed_size` to get file size, instead it loops over `unzReadCurrentFile` until all data is read. Also, it uses the func64 functions, which is why the filename can still be read.

I have built the same minizip version from source and linked against it, and it works (same for older / later version).

**Environment**
- OS: Linux (fedora)
- Compiler: g++ (GCC) 12.1.1 20220507 (Red Hat 12.1.1-1)

**To Reproduce**
https://gist.github.com/ITotalJustice/906268cfa1980ec37722f6208824d9a0

**Expected behavior**
`info.uncompressed_size` and `filename` params should be filled.

**Failure logs**
-(please attached failure logs)

**Additional context**
I haven't tried on windows or mac

**Comment by ITotalJustice** [comment]
i have updated the gist to ensure that the src build of minizip is the exact same version used in vcpkg.

i have also tried using src-minizip along with vcpkg-zlib, just to rule out zlib being the culprit, that isn't the case though.

only thing i havent tried is applying those patches <https://github.com/microsoft/vcpkg/tree/master/ports/minizip> but none of those seem to apply to the linux build anyway.

**Comment by jimwang118** [comment]
Update `vcpkg` to the latest version, use the test reproduction steps you provided to compile the code, and the compilation result is normal. Unable to reproduce this error.
![image](https://github.com/microsoft/vcpkg/assets/122244446/e8f0ba2f-9db4-48af-ad02-da9be3d27200)

**Comment by jeaye** [comment]
@ITotalJustice did you resolve this? I'm seeing the same.

@jimwang118 The problem was a run-time issue, not a compile-time issue. After compiling it, you'll need to run the program and provide it a zip file to see the issue.
