### ISSUE TITLE
Bootstrap vcpkg failed.

### ISSUE THREAD

**Issue by billchenchina** [Microsoft/vcpkg#2567]
When I run `PS C:\Users\billc\vcpkg> .\bootstrap-vcpkg.bat` to bootstrap vcpkg, Powershell tells me that

```
vcpkgDownloadFile : 使用“2”个参数调用“DownloadFile”时发生异常:“无法连接到远程服务器”
所在位置 C:\Users\billc\vcpkg\scripts\fetchDependency.ps1:78 字符: 5
+     vcpkgDownloadFile $url $downloadPath
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [vcpkgDownloadFile], MethodInvocationException
    + FullyQualifiedErrorId : WebException,vcpkgDownloadFile

```

which means I failed to connect the internal server in English. (Because of the slow speed of my network)

Now I have an HTTP Proxy, so how can I use my proxy to bootstrap vcpkg? Is there any option for the bootstrap bat? Thx! 😃

**Comment by fryderykhuang** [comment]
直接在Internet设置里设置系统代理就可以了

**Comment by billchenchina** [comment]
@fryderykhuang 谢谢！一会试试！

**Comment by billchenchina** [comment]
Closed
