### ISSUE TITLE
msbuild integration selects wrong vcpkg.exe

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vcpkg#25696]
**Describe the bug**
We use the msbuild integration with manifest mode. Often the pipeline is successful, but sometimes it fails with the following error:
```
...
"C:\JenkinsSlave\workspace\GitLab-Cpp\vcpkg\vcpkg.exe" install "--host-triplet=x86-windows-v140-static" --x-wait-for-lock --triplet "x86-windows-v140-static" --vcpkg-root "C:\JenkinsSlave\workspace\GitLab-Cpp\vcpkg\\" "--x-manifest-root=C:\JenkinsSlave\workspace\develop-Cpp-Debug\\" "--x-install-root=C:\JenkinsSlave\workspace\develop-Cpp-Debug\vcpkg_installed\x86-windows-v140-static\\" --binarysource=files,G:/Entwicklung/vcpkg/binarycache,readwrite --overlay-triplets=C:\JenkinsSlave\workspace\develop-Cpp-Debug\all\\..\custom-triplets --overlay-ports=C:\JenkinsSlave\workspace\develop-Cpp-Debug\all\\..\vcpkg-overlay-ports --x-asset-sources=x-azurl,file:///G:/Entwicklung/vcpkg/assetcache,,readwrite
         Waiting to take filesystem lock on C:\JenkinsSlave\workspace\GitLab-Cpp\vcpkg\.vcpkg-root...
...
Installs everything
...
10>C:\JenkinsSlave\workspace\develop-Cpp-Debug\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(156,5): error MSB3073: Der Befehl ""C:\JenkinsSlave\workspace\GitLab-Cpp\vcpkg\vcpkg.exe" install "--host-triplet=x86-windows-v140-static" --x-wait-for-lock --triplet "x86-windows-v140-static" --vcpkg-root "C:\JenkinsSlave\workspace\GitLab-Cpp\vcpkg\\" "--x-manifest-root=C:\JenkinsSlave\workspace\develop-Cpp-Debug\\" "--x-install-root=C:\JenkinsSlave\workspace\develop-Cpp-Debug\vcpkg_installed\x86-windows-v140-static\\" --binarysource=files,G:/Entwicklung/vcpkg/binarycache,readwrite --overlay-triplets=C:\JenkinsSlave\workspace\develop-Cpp-Debug\all\\..\custom-triplets --overlay-ports=C:\JenkinsSlave\workspace\develop-Cpp-Debug\all\\..\vcpkg-overlay-ports --x-asset-sources=x-azurl,file:///G:/Entwicklung/vcpkg/assetcache,,readwrite" wurde mit dem Code -1 beendet. [C:\JenkinsSlave\workspace\develop-Cpp-Debug\lib\stringlib\stringlib.vcxproj]
```
`develop-Cpp-Debug` is the current pipeline and `C:\JenkinsSlave\workspace\develop-Cpp-Debug` the current workspace.  
As you see, `vcpkg.exe` from `C:\JenkinsSlave\workspace\GitLab-Cpp` is selected and not from `C:\JenkinsSlave\workspace\develop-Cpp-Debug`. 

**Environment**
- OS: Windows Server
- Compiler: MSVC

**To Reproduce**
I don't know, I wish I could.

**Comment by JackBoosY** [comment]
We do not recommend using multiple vcpkgs on your single machine.
Or you need to use `./vcpkg integrate remove` to the deprecate vcpkg copy.

**Comment by autoantwort** [comment]
I never have run `./vcpkg integrate install`

**Comment by JackBoosY** [comment]
> I never had run `./vcpkg integrate install` on that machine

Can you double confirm that? I don't think so.

**Comment by autoantwort** [comment]
`VCPKG_ROOT` is not set and
```
C:\JenkinsSlave\workspace\GitLab-Cpp\vcpkg>vcpkg integrate remove
User-wide integration is not installed
```

**Comment by BillyONeal** [comment]
>10>C:\JenkinsSlave\workspace\develop-Cpp-Debug\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(156,5)

This is:

https://github.com/microsoft/vcpkg/blob/26ba6f56c1e819b94361dbefa8eee3e0c7108bca/scripts/buildsystems/msbuild/vcpkg.targets#L156-L157

so it comes from `$(_ZVcpkgExecutable)`, which comes from:

https://github.com/microsoft/vcpkg/blob/26ba6f56c1e819b94361dbefa8eee3e0c7108bca/scripts/buildsystems/msbuild/vcpkg.targets#L70

Which starts with:

https://github.com/microsoft/vcpkg/blob/26ba6f56c1e819b94361dbefa8eee3e0c7108bca/scripts/buildsystems/msbuild/vcpkg.targets#L15

(which in most cases is provided by the default value from the props:

https://github.com/microsoft/vcpkg/blob/26ba6f56c1e819b94361dbefa8eee3e0c7108bca/scripts/buildsystems/msbuild/vcpkg.props#L8

)

If you didn't run `integrate install` how does this vcxproj know vcpkg exists in the first place? My guess is that whatever machine has this pipeline had another vcpkg instance whose props got loaded first somehow...

**Comment by autoantwort** [comment]
The problem was that the User-wide integration was installed for the Jenkins user that is used by Jenkins but not when a real person logs on to the CI machine.
