### ISSUE TITLE
[osg] OSG examples no longer work

### ISSUE THREAD

**Issue by lenihan** [microsoft/vcpkg#25705]
**Describe the bug**
The examples that come with OSG no longer work.  The issue appears related to textures.

The examples worked in vcpkg 2022.02.02. 
The examples do NOT work in vcpkg 2022.05.10.
The examples do NOT work in vcpkg 2022.06.16.1.

**Environment**
- OS: Windows 11
- Compiler: Visual Studio revision 17.2.5

**To Reproduce**
1.  `md ~/desktop/repro`
2.  `cd ~/desktop/repro`
4. `git clone https://github.com/openscenegraph/OpenSceneGraph-Data.git`
5. `$env:OSG_FILE_PATH="$home/desktop/repro/OpenSceneGraph-Data"`
6. `git clone https://github.com/microsoft/vcpkg.git`
7. `.\vcpkg\bootstrap-vcpkg.bat`
8. `.\vcpkg\vcpkg.exe --triplet=x64-windows --recurse install osg[plugins,examples]`
9.  `$env:OSGNOTIFYLEVEL="DEBUG_FP"`
10. `cd .\vcpkg\installed\x64-windows\bin\`
11. `..\tools\osg\osgtexture1D.exe`

You will see a black truck...
![image](https://user-images.githubusercontent.com/22015149/178363975-b7b71899-1038-4e06-a4c5-445e2a39ed5d.png)
In the console, you will see lots of warnings/errors...
```
...
Warning: TexGen::apply(State&) - not supported.
Warning: detected OpenGL error 'invalid enumerant' after applying GLMode 0xc60
Warning: detected OpenGL error 'invalid enumerant' after applying GLMode 0xde0
Warning: detected OpenGL error 'invalid enumerant' after applying GLMode 0xb50
Warning: Material::apply(State&) - not supported.
Warning: detected OpenGL error 'invalid enumerant' after applying GLMode 0xb50
Warning: detected OpenGL error 'invalid enumerant' after applying GLMode 0xc60
Warning: detected OpenGL error 'invalid enumerant' after applying GLMode 0xc60
cull()g: detected OpenGL error 'invalid enumerant' after applying GLMode 0xde0
cull()
Warning: Material::apply(State&) - not supported.
Warning: Material::apply(State&) - not supported.
...
```

**Expected behavior**
If you build the latest version of OSG, you see the proper behavior.

You will see a colored truck
![image](https://user-images.githubusercontent.com/22015149/178364635-64d08f57-b679-42ea-966c-38da6f6b247c.png)

The console does not have any warnings/errors...
```
...
end draw() 0000021A36FE49C0
cull() got SceneView 0000021A37024D20
end cull() 0000021A36FE49C0
draw() 0000021A36FE49C0
draw() got SceneView 0000021A37024D20
end draw() 0000021A36FE49C0
...
```

**Failure logs**
N/A

**Additional context**
The version of OSG that vcpkg gets: 
tag OpenSceneGraph-3.6.5
**January 31, 2020**
https://github.com/openscenegraph/OpenSceneGraph/tree/OpenSceneGraph-3.6.5

The latest version of OSG
master branch (no tags that I could find)
**April 7, 2022**
https://github.com/openscenegraph/OpenSceneGraph/tree/master

I believe the fix for this issue is to update [osg/port.cmake](https://github.com/microsoft/vcpkg/blob/master/ports/osg/portfile.cmake)  to use the latest OSG update to master.

**Comment by lenihan** [comment]
> This is probably because default opengl profile was changed. Try setting it back to GL2. #24108

Thanks @Osyotr, your suggested fixed the issue.

Here is the output from `git diff` that made the example work again...
```
diff --git a/ports/osg/portfile.cmake b/ports/osg/portfile.cmake
index d4cd4aaa5..4a5f87b4a 100644
--- a/ports/osg/portfile.cmake
+++ b/ports/osg/portfile.cmake
@@ -77,7 +77,7 @@ endif()
 # The package osg can be configured to use different OpenGL profiles via a custom triplet file:
 # Possible values are GLCORE, GL2, GL3, GLES1, GLES2, GLES3, and GLES2+GLES3
 if(NOT DEFINED osg_OPENGL_PROFILE)
-    set(osg_OPENGL_PROFILE "GL3")
+    set(osg_OPENGL_PROFILE "GL2")
 endif()

 vcpkg_configure_cmake(
 ```

**Comment by Osyotr** [comment]
@lenihan this is supposed to be set in triplet file

**Comment by lenihan** [comment]
> @lenihan this is supposed to be set in triplet file

As a workaround, I'll use a triplet file.

The vcpkg default should match what OSG is doing so the examples work out of the box.

**Comment by RDCH106** [comment]
As I can see changing the default OpenGL break completely the backward compatibility. I use OSG from vcpkg for several project using default behaviour and now all these project are crashing due this change.

Regarding stability, the default version should be GL2 instead of GL3 because it keeps the original behavior and let use the examples. The GL3 option should be an option during the OSG installation.

@LilyWangLL Any progress or information on this?

**Comment by LilyWangLL** [comment]
> @LilyWangLL Any progress or information on this?

I have updated PR #26120, waiting for merged.
