### ISSUE TITLE
"Goto Definition" doesn't work in Visual Studio 2022

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#25716]
****

**Is your feature request related to a problem? Please describe.**
"Goto Definition" doesn't work in Visual Studio 2022
e.g. when using WTL
```cpp
LRESULT CView::OnPaint(UINT /*uMsg*/, WPARAM /*wParam*/, LPARAM /*lParam*/, BOOL& /*bHandled*/)
{
	CPaintDC dc(m_hWnd);

	return 0;
}
```
`CPaintDC` here is highlighted, but "Goto Definition" on it doesn't work, error message:
> A definition for the symbol 'CPaintDC' could not be located.

**Proposed solution**
Let "Goto Definition" work by default.

**More Info**
If add WTL include path (e.g. vcpkg\packages\wtl_x64-windows\include) to the project, "Goto Definition" works.

**Comment by AugP** [comment]
I assume WTL is installed as a vcpkg port? If so, was "vcpkg integrate install" run to add vcpkg integration to your VS project? Can your code build successfully? 

Go To Definition is an IntelliSense feature in VS so it uses the EDG-based IntelliSense parser. If it fails when referencing something from WTL that suggests that IntelliSense doesn't know about WTL. Do you have other issues in your codebase with respect to WTL (e.g. squiggles, no autocompletion, ...)?

**Comment by LilyWangLL** [comment]
Ping @playgithub for response.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
