### ISSUE TITLE
[New Port Request] <libtorch>

### ISSUE THREAD

**Issue by Patrikchan** [microsoft/vcpkg#25712]
Library name:

Library description: An open source machine learning framework that accelerates the path from research prototyping to production deployment.

Source repository URL: https://github.com/pytorch/pytorch

Project homepage (if different from the source repository): https://pytorch.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
Officially had provided a precompiled binary version cu11_stable1.12

**Comment by JackBoosY** [comment]
Duplicated of #16319
