### ISSUE TITLE
Building package atlmfc:x64-windows failed

### ISSUE THREAD

**Issue by vinodgutta** [Microsoft/vcpkg#2571]
Installation failed for the below package:
Package: atlmfc:x64-windows
  Vcpkg version: 0.0.101-2018-01-12-7f104409b6998abeb6593f9f001e2285f57eac4e

Log file:
The following packages will be built and installed:
  * atlmfc[core]:x64-windows
    qt5[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: atlmfc:x64-windows
Building package atlmfc:x64-windows...
-- CURRENT_INSTALLED_DIR=C:/temp/vcpkg/installed/x64-windows
-- DOWNLOADS=C:/temp/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/temp/vcpkg/packages/atlmfc_x64-windows
-- CURRENT_BUILDTREES_DIR=C:/temp/vcpkg/buildtrees/atlmfc
-- CURRENT_PORT_DIR=C:/temp/vcpkg/ports/atlmfc/.
CMake Error at C:/temp/vcpkg/ports/atlmfc/portfile.cmake:7 (message):
  Unable to locate 'afxres.h'.  Ensure you have installed the ATL/MFC
  component of Visual Studio.
Call Stack (most recent call first):
  C:/temp/vcpkg/scripts/ports.cmake:72 (include)

**Comment by ras0219-msft** [comment]
> Unable to locate 'afxres.h'. Ensure you have installed the ATL/MFC
component of Visual Studio.

Have you installed the ATL/MFC component of visual studio?

**Comment by vinodgutta** [comment]
After installing ATL/MFC components of visual studio the installation went through.
Thanks for the hint!
