### ISSUE TITLE
[openssl] Build error

### ISSUE THREAD

**Issue by PaiGack** [microsoft/vcpkg#25729]
**Host Environment**
- OS: Centos7
- Compiler: 
devtoolset-10

**To Reproduce**
`./vcpkg install openssl`

**Failure logs**
```bash

Computing installation plan...
The following packages will be built and installed:
    openssl[core]:x64-linux -> 3.0.5
Detecting compiler hash for triplet "x64-linux"...
Restored 0 packages from /root/.cache/vcpkg/archives in 220.5 us. Use --debug to see more details.
Installing 1/1 openssl:x64-linux...
Building openssl[core]:x64-linux...
CMake Warning at ports/openssl/portfile.cmake:7 (message):
  openssl currently requires the following library from the system package
  manager:

      linux-headers

  It can be installed on alpine systems via apk add linux-headers.
Call Stack (most recent call first):
  scripts/ports.cmake:146 (include)


-- Using cached openssl-openssl-openssl-3.0.5.tar.gz.
-- Cleaning sources at /mnt/e/Code/cpp/vcpkgwsl/vcpkg/buildtrees/openssl/src/nssl-3.0.5-30ecfd0d02.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /mnt/e/Code/cpp/vcpkgwsl/vcpkg/downloads/openssl-openssl-openssl-3.0.5.tar.gz
-- Using source at /mnt/e/Code/cpp/vcpkgwsl/vcpkg/buildtrees/openssl/src/nssl-3.0.5-30ecfd0d02.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: /mnt/e/Code/cpp/vcpkgwsl/vcpkg/downloads/tools/cmake-3.22.2-linux/cmake-3.22.2-linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j9
    Working Directory: /mnt/e/Code/cpp/vcpkgwsl/vcpkg/buildtrees/openssl/x64-linux-dbg
    See logs for more information:
      /mnt/e/Code/cpp/vcpkgwsl/vcpkg/buildtrees/openssl/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/openssl/unix/portfile.cmake:21 (vcpkg_cmake_install)
  ports/openssl/portfile.cmake:39 (include)
  scripts/ports.cmake:146 (include)


error: building openssl:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openssl]+Build+error
Include '[openssl] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-06-15-b0f08e40f8e8752dd0b260138ee078bd9599559c
    vcpkg-scripts version: d769781d1 2022-07-11 (9 hours ago)

You can also use the prefilled template from /mnt/e/Code/cpp/vcpkgwsl/vcpkg/installed/vcpkg/issue_body.md.
```

**Additional context**

yum install perl-IPC-Cmd

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Did this issue resolved by installing `perl-IPC-Cmd`? If it cannot resolve this issue, please provide the error log.

**Comment by Xiaobin0860** [comment]
I also encountered this problem, installing `perl-IPC-Cmd` solved my problem, here is the log

$ cat install-x64-linux-dbg-out.log
[1/3] cd /data/soft/vcpkg/buildtrees/openssl/x64-linux-dbg/3.0.3-ba651081cb.clean && export PATH=/usr/bin:/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/bin:/data/soft/vcpkg/downloads/tools/ninja/1.10.2-linux && export CC=/usr/bin/cc && export AR=/usr/bin/ar && export LD=/usr/bin/ld && export RANLIB=/usr/bin/ranlib && export MAKE=/usr/bin/make && export MAKEDEPPROG=/usr/bin/cc && export WINDRES= && /usr/bin/perl Configure no-shared no-module enable-static-engine no-zlib no-ssl2 no-idea no-cast no-seed no-md2 no-tests linux-x86_64 --prefix=/data/soft/vcpkg/packages/openssl_x64-linux/debug --openssldir=/etc/ssl "-fPIC -g" && /data/soft/vcpkg/downloads/tools/cmake-3.22.2-linux/cmake-3.22.2-linux-x86_64/bin/cmake -DDIR=/data/soft/vcpkg/buildtrees/openssl/x64-linux-dbg/3.0.3-ba651081cb.clean -P /data/soft/vcpkg/ports/openssl/unix/remove-deps.cmake
FAILED: 3.0.3-ba651081cb.clean/Makefile /data/soft/vcpkg/buildtrees/openssl/x64-linux-dbg/3.0.3-ba651081cb.clean/Makefile
cd /data/soft/vcpkg/buildtrees/openssl/x64-linux-dbg/3.0.3-ba651081cb.clean && export PATH=/usr/bin:/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/bin:/data/soft/vcpkg/downloads/tools/ninja/1.10.2-linux && export CC=/usr/bin/cc && export AR=/usr/bin/ar && export LD=/usr/bin/ld && export RANLIB=/usr/bin/ranlib && export MAKE=/usr/bin/make && export MAKEDEPPROG=/usr/bin/cc && export WINDRES= && /usr/bin/perl Configure no-shared no-module enable-static-engine no-zlib no-ssl2 no-idea no-cast no-seed no-md2 no-tests linux-x86_64 --prefix=/data/soft/vcpkg/packages/openssl_x64-linux/debug --openssldir=/etc/ssl "-fPIC -g" && /data/soft/vcpkg/downloads/tools/cmake-3.22.2-linux/cmake-3.22.2-linux-x86_64/bin/cmake -DDIR=/data/soft/vcpkg/buildtrees/openssl/x64-linux-dbg/3.0.3-ba651081cb.clean -P /data/soft/vcpkg/ports/openssl/unix/remove-deps.cmake
Can't locate IPC/Cmd.pm in @INC (@INC contains: /data/soft/vcpkg/buildtrees/openssl/x64-linux-dbg/3.0.3-ba651081cb.clean/util/perl /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 . /data/soft/vcpkg/buildtrees/openssl/x64-linux-dbg/3.0.3-ba651081cb.clean/external/perl/Text-Template-1.56/lib) at /data/soft/vcpkg/buildtrees/openssl/x64-linux-dbg/3.0.3-ba651081cb.clean/util/perl/OpenSSL/config.pm line 18.
BEGIN failed--compilation aborted at /data/soft/vcpkg/buildtrees/openssl/x64-linux-dbg/3.0.3-ba651081cb.clean/util/perl/OpenSSL/config.pm line 18.
Compilation failed in require at Configure line 23.
BEGIN failed--compilation aborted at Configure line 23.
ninja: build stopped: subcommand failed.

3.0.3-ba651081cb.clean/util/perl/OpenSSL/config.pm
```
      1 #! /usr/bin/env perl
      2 # Copyright 1998-2022 The OpenSSL Project Authors. All Rights Reserved.
      3 #
      4 # Licensed under the Apache License 2.0 (the "License").  You may not use
      5 # this file except in compliance with the License.  You can obtain a copy
      6 # in the file LICENSE in the source distribution or at
      7 # https://www.openssl.org/source/license.html
      8
      9 # Determine the operating system and run ./Configure.  Far descendant from
     10 # Apache's minarch and GuessOS.
     11
     12 package OpenSSL::config;
     13
     14 use strict;
     15 use warnings;
     16 use Getopt::Std;
     17 use File::Basename;
     18 use IPC::Cmd;
```

**Comment by PaiGack** [comment]
> 感谢您发布此问题。此问题是否已通过安装得到解决？如果无法解决此问题，请提供错误日志。`perl-IPC-Cmd`

通过更新 perl 已解决该问题

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This issue has been fixed, so I am closing this issue for now.
