### ISSUE TITLE
How can I handle an air gapped build?

### ISSUE THREAD

**Issue by wbuck** [microsoft/vcpkg#25734]
I'm in the process of creating a [custom registry](https://vcpkg.io/en/docs/maintainers/registries.html) hosted in `Azure DevOps`.
The plan going forward will be to host some third party libraries as well as our own libraries in this custom registry.
Each project will then be using `manifests` in order to declare all dependencies and their required versions.

So far everything works as expected. I've already created a port out of one of our libraries and I'm currently distributing it via our custom registry.

Now the part I'm unsure how to handle.
At my company we do an "air gapped" build which means the source code is taken to some machine on a private network with no internet connection where the build is performed.

This is of course problematic as the air gapped machine will not have access to the custom ports registry we're hosting on ADO, nor will it have access to the repos hosting those projects we're distributing via our custom registry.

I'm trying to figure out a solution to this issue.
My first thought was to tell the Air Gap team to first clone the required repos to a USB stick. Then we could configure Visual Studio to use `overlay-ports` which would use the source that was cloned on to the USB stick and a custom port file. I have no idea if this would actually work.

I'm curious what other folks have done who might be in a similar situation?
Does anyone have any ideas on how I could handle this scenario using `vcpkg`?

**Comment by Cheney-W** [comment]
@vicroms Could you please help take a look this issue?

**Comment by Neumann-A** [comment]
> At my company we do an "air gapped" build which means the source code is taken to some machine on a private network with no internet connection where the build is performed.

On a machine with internet:
https://github.com/microsoft/vcpkg/blob/master/docs/users/assetcaching.md (just write to something local)
and also use `--downloads-root=somepath`. if I remember correctly there is some option to only perform downloads (`--only-downloads`)

Carry data to machine without internet and setup vcpkg to use it. (ports using `vcpkg_from_git` may need some manual work.)

**Comment by wbuck** [comment]
@Neumann-A Now is this something I can do in manifest mode from Visual Studio? In this case I'm thinking I could pass those options to `vcpkg` via `Additional Options` exposed in the property sheet.

**Comment by wbuck** [comment]
OK, so I was able to get something working.

First I download the required package via the following command:

    vcpkg install --x-wait-for-lock --triplet "x64-windows-static-md" --vcpkg-root "C:\dev\vcpkg\\" "--x-manifest-root=C:\Users\me\source\repos\MyApplication\MyApplication\\" "--x-install-root=C:\Users\me\source\repos\MyApplication\MyApplication\vcpkg_installed\x64-windows-static-md\\" --downloads-root="C:\Users\me\Documents\cache" --only-downloads --x-asset-sources="x-azurl,file:////ComputerName/cache/,,readwrite"

This command produced an archive of the package (via `--downloads-root`) and also a `SAH512` file (via `--x-asset-sources`)

I then created a port overlay for this library. I'm only going to show what I believe is the relevant part of the portfile:

    vcpkg_download_distfile(
        ARCHIVE
        URLS "//ComputerName/cache/mylib-bc21e051c938e68ed9f26fed19e6d3f80b33d8c8.tar.gz"
        FILENAME "mylib-bc21e051c938e68ed9f26fed19e6d3f80b33d8c8.tar.gz"
        SHA512 96365ba763ae8d9c7bc1b97bb89e1764a5a9d53039117bb05e7b57b95c356789e3c50dbda99434c2a8ae4bfa74285cfa7f040ebe45e939bd34fa0e1d301a0723
    )

    vcpkg_extract_source_archive_ex(
        OUT_SOURCE_PATH SOURCE_PATH
        ARCHIVE "${ARCHIVE}"
        NO_REMOVE_ONE_LEVEL   
    )

The `SHA512` value you see passed to `vcpkg_download_distfile` is copied from the file created by passing the `--x-asset-sources` to `vcpkg install`.

The file `mylib-bc21e051c938e68ed9f26fed19e6d3f80b33d8c8.tar.gz` passed to `vcpkg_download_distfile` was copied from the file created by passing `--downloads-root` to `vcpkg install`.

I placed this port file in a directory (which will be passed to vcpkg later in VS) along side a `vcpkg.json` file.

Within VS I specified the following `Additional Options` which get passed to `vcpkg`:

    --overlay-ports="C:\Users\me\Documents\overlay-ports"

I then attempted to build but received an error that the `SHA512` value was not correct. It then showed me what it was expecting. I replaced the `SHA512` value with the value that was expected and it worked (I also tried this after disabling both the wi-fi and NIC).

OK, so like I said I "kind" of have a working solution.

A couple of questions:
1. What am I supposed to do with the `SHA512` file generated by passing `--x-asset-sources=` to `vcpkg install`?
2. Do I need to generate this `SHA512` artifact if `downloads-root` seems to give me what I need?
3. How can I determine what the `SHA512` hash is of the archive downloaded from `downloads-root`?
4. Did I do this correctly? Am I using the correct helpers in my portfile?

**Comment by vicroms** [comment]
@wbuck when using asset caching you should keep using the original URLs in the portfiles. 

Asset caching translates URLs to specific assets in a cache location, when a download is requested then we do the following:
1) If an asset exists in the cache, use it
2) If (1) failed, use the URL to download the asset
3) If (2) succeded, store the asset in the cache

We use a SHA512 of the URL to name the assets for easy retrieval, those are the files you see in the cache location. The SHA512 argument in the `vcpkg_download_distfile()` is the hash of the file, we use that argument to check that the file you downloaded is indeed the one you wanted to download, and it has not been tampered.

Downloaded assets are extracted into `downloads-root`.

The steps I would follow are:

1. Set `X_VCPKG_ASSET_SOURCES` to 
`clear;x-azurl,file:///C:/some/cache/location,,readwrite`
2. Use a fresh vcpkg (or delete `installed/`, `downloads/`, `buildtrees/` folders)
3. `vcpkg install --no-binarycaching <pkgs you need>` (disable binary caching to make sure that everything is being rebuilt).
4. Copy `C:/some/cache/location` into your air-gapped system
5.  In you air-gapped system, set `X_VCPKG_ASSET_SOURCES` to 
`clear;x-azurl,file:///C:/some/cache/location,,read;x-block-origin`

If you want to make sure that everything is cached before copying, remove all the output folders (`downloads`, `installed`, `buildtrees`) and run `vcpkg install --no-binarycaching --x-asset-sources=x-block-origin <pkgs>`. This will force vcpkg to only use artifacts from the asset cache and not attempt to download anything. If everything is set up correctly then the install should succeed.

**Comment by vicroms** [comment]
Feel free to reach us at vcpkg@microsoft.com to get help from the whole team.

**Comment by wbuck** [comment]
@vicroms Thank-you for the detailed instructions (I needed a bit of hand holding).

One question: The cached asset, is it the source code (and anything else the package included), or a compiled binary?

**Comment by vicroms** [comment]
Asset caching, caches anything that vcpkg downloads. For ports that is usually their source code, however, vcpkg and ports may need to download binary tools to run/build (powershell-core, 7zip, CMake, Ninja, meson, mingw, etc.) and the asset cache will store those as well.

`vcpkg` does not download pre-built libraries from the internet, our preferred method to install a library is to download the source code and build it in the user machine. We have a feature that caches package binaries once they are built at least once (see our [binary caching documentation](https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md)) and those can be reused by vcpkg to skip having to rebuild the same library.

**Comment by wbuck** [comment]
@vicroms I wasn’t wondering if it downloads the prebuilt binaries, moreover I was wondering if the package was built locally and then cached.

Regardless that answers my question, thank you. I did the steps you laid out above but it’s failing as vcpkg is looking for a cached file that doesn’t exists on the air gapped system (I suspect it’s a specific version of Cmake).

Instead of detailing the issue here I’ll use the email you provided.

**Comment by dg0yt** [comment]
I hope the hidden conversation will result in a public documentation.

**Comment by wbuck** [comment]
If/when I get this working I’m planning on making a very detailed post of SO.

**Comment by wbuck** [comment]
OK so I was able to get this to work if I only use the built in registry and not our custom private registry.
I also had to manually install the following tools on the air gapped machine:
1. Cmake
2. Powershell version 7.2.5
3. Git

Question:
It seems some tools are included in the cached files but others are not. Does `vcpkg` automatically detect tools that are already installed on the machine that is creating the assets and only include tools that are not currently installed?

I would like to figure out what I need to do in order to get this to work with our custom private registry.
When I attempt to do a "Rebuild" on the air gapped machine I can see that `vcpkg` is attempting to fetch the registry information from our private custom registry which of course fails because the air gapped machine does not have an internet connection.

This, I believe makes sense as `vcpkg` has no knowledge of the `URL`'s of our private repos so it wouldn't know how to construct the `SHA512` file names (There wouldn't be any port files on the local air gapped machine).

In this case should I be using the overlays?

**Comment by autoantwort** [comment]
> Does vcpkg automatically detect tools that are already installed on the machine that is creating the assets and only include tools that are not currently installed in the cached asset?

Yes   
You can use `--x-abi-tools-use-exact-versions` so the tools are probably downloaded even on your meshine with internet. 

> When I attempt to do a "Rebuild" on the air gapped machine I can see that vcpkg is attempting to fetch the registry information from our private custom registry which of course fails because the air gapped machine does not have an internet connection.

Afaik vcpkg needs access to the git repo and don't uses asset caching for that.

**Comment by Cheney-W** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
