### ISSUE TITLE
Confusing: compiler messages ending with ".c", ".cpp", etc didn't appear in build logs

### ISSUE THREAD

**Issue by namniav** [microsoft/vcpkg#25736]
**Describe the bug**

Some output of `#pragma message(...)` didn't appear in build logs. It turns out that only those lines ending with ".c", ".cpp", etc are dropped.  <sub>Feeling sad :( that it wasted my couple of hours...<sub>

**Environment**
- OS: WIndows 10 21H2 64bit
- Compiler: MSVC 19.29.30145

**To Reproduce**
1. Choose a C++ project you like. This repro uses the small `libcopp`, you can choose any one.
2. Choose a C++ source file you like.
3. Create a patch file `ports/libcopp/repro-bug.patch` that inserts these `#pragma message(...)` lines:
```patch
diff --git a/src/libcopp/utils/uint64_id_allocator.cpp b/src/libcopp/utils/uint64_id_allocator.cpp
index 2ad62f8..f5099c4 100644
--- a/src/libcopp/utils/uint64_id_allocator.cpp
+++ b/src/libcopp/utils/uint64_id_allocator.cpp
@@ -1,3 +1,20 @@
+#pragma message("balabala cpp")
+#pragma message("balabala cpp!")
+#pragma message("balabala .c")
+#pragma message("balabala .c!")
+#pragma message("balabala .cpp")
+#pragma message("balabala .cpp!")
+#pragma message("balabala .cxx")
+#pragma message("balabala .cxx!")
+#pragma message("balabala .cc")
+#pragma message("balabala .cc!")
+#pragma message("balabala .h")
+#pragma message("balabala .h!")
+#pragma message("balabala .hpp")
+#pragma message("balabala .hpp!")
+#pragma message("balabala .other")
+#pragma message("balabala .other!")
+
 #include <ctime>

 #include <libcopp/utils/atomic_int_type.h>

```
4. Edit `ports/libcopp/portfile.cmake` to apply the patch:
```cmake
    PATCHES fix-x86-windows.patch
            repro-bug.patch # <-- add this line
```
5. Re-build: `./vcpkg.exe install libcopp` (remove first if it is already installed)
6. Search "balabala" in build log file `buildtrees/libcopp/install-x86-windows-dbg-out`, note that messages ending with ".c", ".cpp", ".cxx", ".cc" are missing.
```
balabala cpp
balabala cpp!
balabala .c!
balabala .cpp!
balabala .cxx!
balabala .cc!
balabala .h
balabala .h!
balabala .hpp
balabala .hpp!
balabala .other
balabala .other!
```

**Expected behavior**
All `#pragma message(...)` outputs should appear in build log file.

**Failure logs**
no failure logs

**Additional context**
I'm not sure if it's vcpkg or cmake dropped those outputs.
Copy the compilation command from build log file and execute it manually from build directory(`buildtrees/libcopp/x86-windows-dbg/`), the compiler outputs all expected messages(although the compilation failed because of other reasons):
```
balabala cpp
balabala cpp!
balabala .c
balabala .c!
balabala .cpp
balabala .cpp!
balabala .cxx
balabala .cxx!
balabala .cc
balabala .cc!
balabala .h
balabala .h!
balabala .hpp
balabala .hpp!
balabala .other
balabala .other!
```

**Comment by JackBoosY** [comment]
I can confirm this works. You should find the logs in `install-*-out.log`.
Did you install cmake manually?

**Comment by namniav** [comment]
@JackBoosY See the commit linked above and  [its github actions logs](https://github.com/namniav/vcpkg/runs/7323939452).
<img width="862" alt="image" src="https://user-images.githubusercontent.com/68486394/178770145-ca386c9a-698a-4fde-98c5-3f062f88eadd.png">

**Comment by dg0yt** [comment]
Note that the output also passes through `ninja` which actively manages merges the merge of stdout and stderr. That's why ...-err.log is normally empty for cmake builds.

**Comment by namniav** [comment]
> Can you please find the missing logs in install-x86-windows-dbg-err.log?

No, it's empty.

@JackBoosY I think the tag "requires:more-information" can be removed because all information needed to reproduce are provided in the metioned small commit and its triggered github action. The commit didn't do any new stuff than above described repro steps, was there any difference when you "confirmed this works"?

**Comment by namniav** [comment]
Also I can confirm that cmake outputs all expected messages when building with cmake *directly*.

**Comment by namniav** [comment]
And I think this problem is yelling for verbose output/logging feater(#6191).

**Comment by JackBoosY** [comment]
I can confirm the compiler send those message. So I think this maybe a ninja bug or cmake bug.

**Comment by JackBoosY** [comment]
> And I think this problem is yelling for verbose output/logging feature(#6191).

No, I can also reproduce this using `--log-level=VERBOSE`.

**Comment by dg0yt** [comment]
> ninja bug

Or feature.
https://github.com/ninja-build/ninja/blob/d4017a2b1ea642f12dabe05ec99b2a16c93e99aa/src/clparser.cc#L69-L77

**Comment by namniav** [comment]
> I can also reproduce this using `--log-level=VERBOSE`.

How to use this option? vcpkg doesn't recognize it and I can't find it in vcpkg's docs.

I mean vcpkg should provide an option that enable verbose output/logging for tools it uses. Parsing and filtering output from other tools correctly is difficult and complicated, having verbose logging can make life easier when there're problems.

**Comment by JackBoosY** [comment]
Pass `--log-level=VERBOSE` to `vcpkg_cmake_configure` `OPTIONS`.

**Comment by namniav** [comment]
Because it only enables cmake's verbose logging, ninja still drops those message. In fact, cmake doesn't drop those message without this option.

**Comment by dg0yt** [comment]
> https://github.com/ninja-build/ninja/blob/d4017a2b1ea642f12dabe05ec99b2a16c93e99aa/src/clparser.cc#L69-L77

You still need to verify that this is active in the regular build. Perhaps create a ninja script manually.

**Comment by JonLiu1993** [comment]
@namniav, It looks like this is not a vcpkg issue but about `ninja` and `cmake`.
