### ISSUE TITLE
[vcpkg-docs] The archive URL in Example 2: Packaging zlib does not exist

### ISSUE THREAD

**Issue by CdecPGL** [microsoft/vcpkg#2573]
In the [example of packaging zlib](https://github.com/Microsoft/vcpkg/blob/master/docs/examples/packaging-zlib.md) of the document, bellow example code does not work because of URL error.

```no-highlight
PS D:\src\vcpkg> .\vcpkg create zlib2 http://zlib.net/zlib128.zip zlib128.zip
```

The cause is that the URL "http://zlib.net/zlib128.zip" no longer exist.

I thing it is better to change the version of zlib from 1.2.9 to 1.2.11 in the example because "http://zlib.net/zlib1211.zip" is available.

There is same problem in https://vcpkg.readthedocs.io/en/latest/examples/packaging-zlib/.

**Comment by NancyLi1013** [comment]
Hi @CdecPGL, thanks for posting this issue.
The docs you mentioned above have been updated now. Please refer to the latest docs:
https://github.com/microsoft/vcpkg/blob/e36d550dd4c1bcc2f8a1aabbd6ce9d394bad8603/docs/examples/packaging-zipfiles.md

https://vcpkg.readthedocs.io/en/latest/examples/packaging-zipfiles/
