### ISSUE TITLE
Port Request: net-snmp

### ISSUE THREAD

**Issue by a-tinsmith** [microsoft/vcpkg#2575]
Would be nice to see [**net-snmp**](http://www.net-snmp.org/) project ported to vcpkg system. If porting the entire suit is too ambitious, then having just an equivalent of the **net-snmp-libs** and **net-snmp-devel** Linux packages is a big step forward.

**Comment by unclevlad** [comment]
I second this. I have a major project in limbo as net-snmp is such a bear to compile and maintain from Windows and we have had to evaluate alternatives.

**Comment by Voskrese** [comment]
https://github.com/winlibs/net-snmp

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
