### ISSUE TITLE
[volk] Enable using vulkan-headers package instead of vulkan package

### ISSUE THREAD

**Issue by Iyeyasu** [microsoft/vcpkg#25762]
Currently `volk` requires the `vulkan` package, which in turn requires Vulkan SDK to be installed on the development machine. This partly defeats the point of dynamic loaders, which allows building the project without anything except the Vulkan headers. It should be possible to use the vcpkg version of Volk without having to install the Vulkan SDK and instead only require the Vulkan headers.

There are at least two possible solutions:

1. Replace `vulkan` with `vulkan-headers` as a dependency.
2. Using vcpkg.json `"features"` field, allow choosing between `vulkan` and `vulkan-headers` as a dependency (defaulting in the old behaviour).

With the `"features"` approach, the headers-only version could then be used in a project with the following `vcpkg.json`:

```json
{
  "dependencies": [{
    "name": "volk",
    "default-features": false,
    "features": ["vulkan-headers"]
  }]
}
```

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. For your two suggestions,
> 1. Replace vulkan with vulkan-headers as a dependency.
1. There are information in _[VOLK_SOURCE_PATH]/README.md_, so If use wat use `volk`, he need install `vulkan`. We cannot use `vulkan-headers` instead of `vulkan` as a dependency.
```
## Basic usage

To use volk, you have to include `volk.h` instead of `vulkan/vulkan.h`; this is necessary to use function definitions from volk.

If some files in your application include `vulkan/vulkan.h` and don't include `volk.h`, this can result in symbol conflicts; consider defining `VK_NO_PROTOTYPES` when compiling code that uses Vulkan to make sure this doesn't happen. It's also important to make sure that `vulkan-1` is not linked into the application, as this results in symbol name conflicts as well.

To initialize volk, call this function first:

```c++
VkResult volkInitialize();

This will attempt to load Vulkan loader from the system; if this function returns `VK_SUCCESS` you can proceed to create Vulkan instance.
If this function fails, this means Vulkan loader isn't installed on your system.
```
> 2. Using vcpkg.json "features" field, allow choosing between vulkan and vulkan-headers as a dependency (defaulting in the old behaviour).

3. If we add `vulkan` and `vulkan-headers` as features to `volk`, and set `vulkan` to `default-features`, you cannot only build volk with feature `vulkan-headers`. Due to `vulkan` is a default feature, so build `volk[vulkan-headers]` as your example will install `volk[core,vulkan,vulkan-headers]`. This is by design. So this way is is not feasible.

**Comment by Iyeyasu** [comment]
> There are information in [VOLK_SOURCE_PATH]/README.md, so If use wat use volk, he need install vulkan

Can you point to the exact line/information that says this? Volk simply includes the `<vulkan/vulkan.h>` header, which is also provided by `vulkan-headers`. There should be no need for any other component of the Vulkan SDK. In fact, part of the appeal of dynamic loading is that you aren't limited in any ways by the Vulkan support of your build platform, only the target platform.

> If we add vulkan and vulkan-headers as features to volk, and set vulkan to default-features, you cannot only build volk with feature vulkan-headers.

At least with manifest mode this is possible by using `default-features: false` as shown in my example. It also seems that defining `volk[core, vulkan-headers]` removes all default features. More information here: https://vcpkg.readthedocs.io/en/latest/users/selecting-library-features/

**Comment by LilyWangLL** [comment]
There are the following codes in _[VOLK_SOURCE_PATH]/CMakeLists.txt_:
```
if(VOLK_PULL_IN_VULKAN)
  # If CMake has the FindVulkan module and it works, use it.
  # Otherwise try the environment variable.
  find_package(Vulkan QUIET)
  if(TARGET Vulkan::Vulkan)
      message(" Vulkan as target")
    target_link_libraries(volk PUBLIC Vulkan::Vulkan)
    target_link_libraries(volk_headers INTERFACE Vulkan::Vulkan)
  elseif(DEFINED ENV{VULKAN_SDK})
      message(" Vulkan as path")
    target_include_directories(volk PUBLIC "$ENV{VULKAN_SDK}/include")
    target_include_directories(volk_headers INTERFACE "$ENV{VULKAN_SDK}/include")
  endif()
endif()
```
Now install `volk` use `Vulkan as target`. I don't know if using `Vulkan as path` will affect the function of `volk`.

**Comment by Iyeyasu** [comment]
It seems that for header-only Volk you would need to set at least `VOLK_PULL_IN_VULKAN=OFF` and `VOLK_HEADERS_ONLY=ON`.

**Comment by Arech** [comment]
Just noting that proposed `"feature"` -based approach doesn't fit into `vcpkg` requirements due to a functionality misuse. Unfortunately, [features](https://learn.microsoft.com/en-us/vcpkg/users/manifests#features) aren't meant to specify alternatives, it's for additive functionality only, so the updated port might not be accepted into public `vcpkg` repository...

**Comment by Iyeyasu** [comment]
This has been resolved with PR https://github.com/microsoft/vcpkg/pull/27747
