### ISSUE TITLE
[metis] upstream is gone

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/vcpkg#25764]
See also https://github.com/microsoft/vcpkg/issues/25609

<img width="852" alt="image" src="https://user-images.githubusercontent.com/1544943/178866228-885de5b8-4205-40b8-a3b7-034d6264da6f.png">

I looked at what's in that repo suggested as an alternative ( https://github.com/KarypisLab/METIS ) vs. what's in our cached copy of that release file `metis-5.1.0.tar.gz` and there seem to be meaningful differences. @karypis @BarclayII @zheng-da @pvc1989 can you either:

(1) let us know where we should look for `metis-5.1.0.tar.gz` now, or
(2) let us know what we should be doing instead (e.g. updating our `metis` port to something more recent than 2013?)

**Comment by JackBoosY** [comment]
We already know this, but it looks like the official webset doesn't restore yet.
cc @LilyWangL

**Comment by JackBoosY** [comment]
The `internal` label should not be used in issues 😄

**Comment by kysucix** [comment]
Metis on github is much different. In particular it's not embedding GKlib as a submodule but it's using it as an external dependency.
In care there's a switch to Metis on github a new port for GKlib is required as well.

**Comment by BillyONeal** [comment]
> Metis on github is much different. In particular it's not embedding GKlib as a submodule but it's using it as an external dependency.

Would you be willing to create a 'release' that has the exact content of `metis-5.1.0.tar.gz`? (We have a copy of the file but generally don't rehost things because it creates licensing / copyright headaches if the copyright holder doesn't do the publishing themselves.

> In case there's a switch to Metis on github a new port for GKlib is required as well.

OK we can investigate doing that.

**Comment by JackBoosY** [comment]
@BillyONeal Please note that we are fixing this issue.

**Comment by ifekonja** [comment]
https://www.nektar.info/thirdparty/

**Comment by ifekonja** [comment]
vcpkg_download_distfile(ARCHIVE
	URLS "https://www.nektar.info/thirdparty/metis-5.1.0.tar.gz"
	FILENAME "metis-5.1.0.tar.gz"
    SHA512 deea47749d13bd06fbeaf98a53c6c0b61603ddc17a43dae81d72c8015576f6495fd83c11b0ef68d024879ed5415c14ebdbd87ce49c181bdac680573bea8bdb25
)

**Comment by BillyONeal** [comment]
> https://www.nektar.info/thirdparty/

The name "thirdparty" suggests that this isn't an actual upstream

**Comment by ifekonja** [comment]
It works

V sre., 20. jul. 2022 19:05 je oseba BillyONeal ***@***.***>
napisala:
