### ISSUE TITLE
Error: Building package boost-math:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by bolbol2night** [Microsoft/vcpkg#2576]
Hello,
While trying to install package cpprestsdk I faced this issue:

Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-math:x86-windows
  Vcpkg version: 0.0.101-2018-01-14-c1d0597003fbf0b98dd6e6bfb1b86691258140da

I'm already using an up-to-date version of vcpkg.

**Comment by ras0219-msft** [comment]
Thanks for reporting this issue!

Could you please attach the log files listed in the error output? They should be above the message you've written.

**Comment by atkawa7** [comment]
@ras0219-msft Could you reopen this? I am having a similar issue

**Comment by atkawa7** [comment]
[build-x86-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/1671087/build-x86-windows-rel-out.log)

**Comment by ThomasChen1220** [comment]
same here

**Comment by JackLee889** [comment]
same here

**Comment by wangli28** [comment]
Could you pull master and try again? I installed it successfully with VS2017 15.9.11 and VCPKG latest source. Please open a new issue if this is still a problem for you.

> PS F:\b\vcpkg> .\vcpkg.exe install boost-math
The following packages will be built and installed:
/ * boost-array[core]:x86-windows
 / * boost-assert[core]:x86-windows
  /* boost-atomic[core]:x86-windows
  /* boost-bind[core]:x86-windows
  /* boost-build[core]:x86-windows
  /* boost-compatibility[core]:x86-windows
 / * boost-concept-check[core]:x86-windows
  /* boost-config[core]:x86-windows
  /* boost-container[core]:x86-windows
  /* boost-container-hash[core]:x86-windows
  /* boost-conversion[core]:x86-windows
/  * boost-core[core]:x86-windows
/  * boost-detail[core]:x86-windows
/  * boost-function-types[core]:x86-windows
/  * boost-fusion[core]:x86-windows
/  * boost-integer[core]:x86-windows
/  * boost-intrusive[core]:x86-windows
/  * boost-iterator[core]:x86-windows
/  * boost-lambda[core]:x86-windows
/  * boost-lexical-cast[core]:x86-windows
/    boost-math[core]:x86-windows
/  * boost-modular-build-helper[core]:x86-windows
/  * boost-move[core]:x86-windows
/  * boost-mpl[core]:x86-windows
/  * boost-numeric-conversion[core]:x86-windows
/  * boost-optional[core]:x86-windows
/  * boost-predef[core]:x86-windows
/  * boost-preprocessor[core]:x86-windows
/  * boost-range[core]:x86-windows
/  * boost-regex[core]:x86-windows
/  * boost-smart-ptr[core]:x86-windows
/  * boost-static-assert[core]:x86-windows
/  * boost-throw-exception[core]:x86-windows
/  * boost-tuple[core]:x86-windows
/  * boost-type-traits[core]:x86-windows
/  * boost-typeof[core]:x86-windows
/  * boost-utility[core]:x86-windows
/  * boost-vcpkg-helpers[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/38: boost-vcpkg-helpers:x86-windows
Building package boost-vcpkg-helpers[core]:x86-windows...
/......
Building package boost-math[core]:x86-windows... done
Installing package boost-math[core]:x86-windows...
Installing package boost-math[core]:x86-windows... done
Elapsed time for package boost-math:x86-windows: 1.23 min
/
Total elapsed time: 4.622 min
