### ISSUE TITLE
No archive produced when specifying --only-downloads and --downloads-root

### ISSUE THREAD

**Issue by wbuck** [microsoft/vcpkg#25779]
**Describe the bug**
I'm trying to only download the source for the dependencies specified in the `vcpkg.json` file located in the root of my Visual Studio project. 

I'm attempting to only download the source at this time due to an air gapped build requirement we have at my company.
The idea is to download the required source on to a USB stick, then bring that USB stick to the air gapped machine which will then be used to build the product and all of its dependencies.

When I run the following command:

    vcpkg install --x-wait-for-lock --triplet "x64-windows-static" --vcpkg-root "C:\dev\vcpkg\\" "--x-manifest-root=C:\Users\me\source\repos\MyApp\MyApp\\" "--x-install-root=C:\Users\me\source\repos\MyApp\MyApp\vcpkg_installed\x64-windows-static\\" --downloads-root="C:\Users\me\Documents\cache\" --only-downloads

I expected to see archives for each dependency (currently I only have `fmt`) I have listed in the `vcpkg.json` file located in the root of my project.

Instead I see nothing in the directory I specified using `--downloads-root` when calling `vcpkg install`.

This is the output I see on the command line:
```
Fetching registry information from https://github.com/microsoft/vcpkg (HEAD)...
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x64-windows-static...
The following packages will be built and installed:
    fmt[core]:x64-windows-static -> 8.1.1#1 -- C:\Users\me\AppData\Local\vcpkg\registries\git-trees\602d9743b7957c9e82a06d0e81d58637c6df5222
  * vcpkg-cmake[core]:x64-windows -> 2022-04-21 -- C:\Users\me\AppData\Local\vcpkg\registries\git-trees\8273918a04a5822ad7cc21ea5249402f2e999a7a
  * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06 -- C:\Users\me\AppData\Local\vcpkg\registries\git-trees\24dc7dfc704406e9f745f033643dc25f56e4ca18
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: vcpkg-cmake-config:x64-windows
Building package vcpkg-cmake-config[core]:x64-windows...
-- Installing port from location: C:\Users\me\AppData\Local\vcpkg\registries\git-trees\24dc7dfc704406e9f745f033643dc25f56e4ca18
-- Installing: C:/dev/vcpkg/packages/vcpkg-cmake-config_x64-windows/share/vcpkg-cmake-config/vcpkg_cmake_config_fixup.cmake
-- Installing: C:/dev/vcpkg/packages/vcpkg-cmake-config_x64-windows/share/vcpkg-cmake-config/vcpkg-port-config.cmake
-- Installing: C:/dev/vcpkg/packages/vcpkg-cmake-config_x64-windows/share/vcpkg-cmake-config/copyright
Downloaded sources for package vcpkg-cmake-config[core]:x64-windows
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+vcpkg-cmake-config
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[vcpkg-cmake-config]+Build+error
including:
  package: vcpkg-cmake-config[core]:x64-windows -> 2022-02-06
    vcpkg-tool version: 2022-03-08-85dc3d9d4e1e7b643f811eac0b9d884419fead79
    vcpkg-scripts version: 8b14e7e87 2022-07-13 (12 hours ago)

Additionally, attach any relevant sections from the log files above.
```
    
I checked the logs located in the `vcpkgroot\buildtrees` and I see no errors for either `fmt` or ` vcpkg-cmake-config`.

**Environment**
- OS: Windows 10 - 21H2
- Compiler: Visual Studio 2022 - 17.2.5 - v143

**To Reproduce**
1. Create a project
2. Create the `vcpkg.json` file in project root
3. Add `fmt` as a dependency
4. Manually issue the `vcpkg install` command I showed above (making sure to specify `--only-downloads` and `--downloads-root`
5. Check to see if there is an archive produced in the directory specified with `--only-downloads`

**Expected behavior**
I expected to see the downloaded archived source in the directory I specified with `--downloads-root`

**Failure logs**
None of the logs show a failure

**Comment by autoantwort** [comment]
In my experience `--only-downloads` is broken. Simply run without `--only-downloads`. The downloads folder is the same.

**Comment by wbuck** [comment]
One thing I do also want to mention. When I follow the above steps for our private registry whose packages are `MSBuild` based and not `CMake` it works as expected. I'm going to fork `fmt` today and attempt to perform the above steps and see if an archive is generated.

**Comment by wbuck** [comment]
So, it appears the downloading of the source fails when the `vcpkg-cmake-config` (and other "host" packages) are required.

**Comment by Thomas1664** [comment]
You're not using the latest version of the vcpkg tool. Please run the bootstrap script again to download the lastest version: `bootstrap-vcpkg.bat`.

**Comment by wbuck** [comment]
Updating did solve the issue
