### ISSUE TITLE
[skia] Linker error when using Skia DLL build on Windows with CMake

### ISSUE THREAD

**Issue by codemonaut** [microsoft/vcpkg#25774]
**Describe the bug**

When trying to create a project based on Skia using CMake configuration of Skia port it won't link in MSVC 2022.

**Environment**
- OS: Windows
- Compiler: MSVC (v143)

**To Reproduce**
`./vcpkg install skia[direct3d]:x64-windows`  (`./vcpkg install skia:x64-windows` results in the same error)

CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.9)
set(CMAKE_TOOLCHAIN_FILE ${CMAKE_SOURCE_DIR}/vcpkg/scripts/buildsystems/vcpkg.cmake CACHE STRING "")
project(skia-win32 VERSION 1.0 LANGUAGES CXX)
find_package(skia CONFIG REQUIRED)
add_executable(demo-win32 main.cpp)

# Skia vcpkg seems to fail setting dll_export vs. dll_import flags correctly.
# SKIA_IMPLEMENTATION=1 is evaluated to __declspec(dll_export) when compiling 
# the demo but it has to be __declspec(dll_import).
# Hence we overwrite SKIA_IMPLEMENTATION=1 by SKIA_IMPLEMENTATION=0!

# UNCOMMENT TO FIX LINK ERRORS
# get_target_property(skia_interface_defs skia INTERFACE_COMPILE_DEFINITIONS)
# string(REPLACE "SKIA_IMPLEMENTATION=1" "SKIA_IMPLMENTATION=0" skia_interface_defs_fixed "${skia_interface_defs}")
# set_target_properties(skia PROPERTIES INTERFACE_COMPILE_DEFINITIONS "${skia_interface_defs_fixed}")

target_compile_features(demo-win32 PRIVATE cxx_std_17)
target_link_libraries(demo-win32 PRIVATE skia::skia)
target_link_libraries(demo-win32 PRIVATE d3d12.lib dxgi.lib)
```

main.cpp:
```
#include "skia/core/SkMatrix.h"
int main()
{
    SkMatrix mat;
}
```

**Expected behavior**
main.cpp should compile and linker should succeed to build application.

**Failure logs**
```
1>main.obj : error LNK2001: unresolved external symbol "private: static void (__cdecl*const * const SkMatrix::gMapXYProcs)(class SkMatrix const &,float,float,struct SkPoint *)" (?gMapXYProcs@SkMatrix@@0QBQ6AXAEBV1@MMPEAUSkPoint@@@ZB)
1>main.obj : error LNK2001: unresolved external symbol "private: static void (__cdecl*const * const SkMatrix::gMapPtsProcs)(class SkMatrix const &,struct SkPoint * const,struct SkPoint const * const,int)" (?gMapPtsProcs@SkMatrix@@0QBQ6AXAEBV1@QEAUSkPoint@@QEBU2@H@ZB)
```

**Additional context**

Looking into https://github.com/google/skia/blob/main/include/core/SkTypes.h you can see that SK_API is defined to `__declspec(dll_export)` when `SKIA_IMPLEMENTATION` is set. That's wrong for **using the DLL** but ok for building the DLL.
```
#if SKIA_IMPLEMENTATION
  #define SK_API __declspec(dllexport)
#else
  #define SK_API __declspec(dllimport)
```

`skiaConfig.cmake` sets `SKIA_IMPLEMENTATION=1` when using CMake to create VS solution projects. Hence you get the linker error.

Uncommenting the cmake hack in CMakeLists.txt above will fix the problem but it's probably not the best solution here. 

Am I missing something or is the problem on the vcpkg port side of things?

**Comment by kelteseth** [comment]
I have a similar problem:
```
QmlRive.lib(Rive.cpp.obj) : error LNK2019: unresolved external symbol "bool __cdecl SkStrEndsWith(char const * const,char const * const)" (?SkStrEndsWith@@YA_NQEBD0@Z) referenced in function "public: bool __cdecl SkString::endsWith(char const * const)const " (?endsWith@SkString@@QEBA_NQEBD@Z)
RiveSkiaRenderer.lib(skia_factory.cpp.obj) : error LNK2001: unresolved external symbol "bool __cdecl SkStrEndsWith(char const * const,char const * const)" (?SkStrEndsWith@@YA_NQEBD0@Z)
QmlRive.lib(Rive.cpp.obj) : error LNK2019: unresolved external symbol "bool __cdecl SkStrEndsWith(char const * const,char)" (?SkStrEndsWith@@YA_NQEBDD@Z) referenced in function "public: bool __cdecl SkString::endsWith(char)const " (?endsWith@SkString@@QEBA_ND@Z)
RiveSkiaRenderer.lib(skia_factory.cpp.obj) : error LNK2001: unresolved external symbol "bool __cdecl SkStrEndsWith(char const * const,char)" (?SkStrEndsWith@@YA_NQEBDD@Z)
QmlRive.lib(Rive.cpp.obj) : error LNK2001: unresolved external symbol "private: static void (__cdecl*const * const SkMatrix::gMapXYProcs)(class SkMatrix const &,float,float,struct SkPoint *)" (?gMapXYProcs@SkMatrix@@0QBQ6AXAEBV1@MMPEAUSkPoint@@@ZB)
RiveSkiaRenderer.lib(skia_factory.cpp.obj) : error LNK2001: unresolved external symbol "private: static void (__cdecl*const * const SkMatrix::gMapXYProcs)(class SkMatrix const &,float,float,struct SkPoint *)" (?gMapXYProcs@SkMatrix@@0QBQ6AXAEBV1@MMPEAUSkPoint@@@ZB)
QmlRive.lib(Rive.cpp.obj) : error LNK2001: unresolved external symbol "private: static void (__cdecl*const * const SkMatrix::gMapPtsProcs)(class SkMatrix const &,struct SkPoint * const,struct SkPoint const * const,int)" (?gMapPtsProcs@SkMatrix@@0QBQ6AXAEBV1@QEAUSkPoint@@QEBU2@H@ZB)
RiveSkiaRenderer.lib(skia_factory.cpp.obj) : error LNK2001: unresolved external symbol "private: static void (__cdecl*const * const SkMatrix::gMapPtsProcs)(class SkMatrix const &,struct SkPoint * const,struct SkPoint const * const,int)" (?gMapPtsProcs@SkMatrix@@0QBQ6AXAEBV1@QEAUSkPoint@@QEBU2@H@ZB)
TestProject.exe : fatal error LNK1120: 4 unresolved externals
```

Also isn't it weird that the .lib files end with skia.dll.lib?

![image](https://user-images.githubusercontent.com/1071536/180598765-fbdb895f-556d-4de6-adbb-b0177711d831.png)

**Comment by dg0yt** [comment]
> `skiaConfig.cmake` sets `SKIA_IMPLEMENTATION=1` when using CMake to create VS solution projects. Hence you get the linker error.
> 
> Uncommenting the cmake hack in CMakeLists.txt above will fix the problem but it's probably not the best solution here.

I would guess that `SKIA_IMPLEMENTATION=1` is to indicate that the skia lib is being compiled, not used. So it shouldn't be in the config for downstream usage.

> Am I missing something or is the problem on the vcpkg port side of things?

The CMake config comes from the vcpkg port, so the problem is there.

> Also isn't it weird that the .lib files end with skia.dll.lib?

I would guess that this name was chosen for the import lib to make it different from the static lib.
Most vcpkg would try to eliminate the difference, to facilitate things like `find_library`.

**Comment by errata-c** [comment]
Same build issue as [kelteseth](https://github.com/kelteseth) above, fix by [codemonaut](https://github.com/codemonaut) solves all the unresolved symbol errors. My system is Windows 10 home, Version 10.0.19044 Build 19044, vcpkg version 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22, with skia[core,gl]:x64-windows.

**Comment by kelteseth** [comment]
@errata-c  Adding a simple `set(SKIA_IMPLEMENTATION TRUE)` to `/ports/skia/skiaConfig.cmake.in` fixed it for me :)

![image](https://user-images.githubusercontent.com/1071536/195625651-2690c564-2124-46ac-ad72-5ab507faa3a4.png)
