### ISSUE TITLE
Building package boost-build:x64-windows failed with: BUILD_FAILED 

### ISSUE THREAD

**Issue by twkun** [Microsoft/vcpkg#2577]
Vcpkg version: 0.0.101-unknownhash
msvc version: vs2015 15.0.25431.01 update 3

err log:
vcpkg install boost-build:x64-windows

The following packages will be built and installed:
    boost-build[core]:x64-windows
Starting package 1/1: boost-build:x64-windows
Building package boost-build:x64-windows...
-- CURRENT_INSTALLED_DIR=D:/ProgramLanguage/vcpkg-master/installed/x64-windows
-- DOWNLOADS=D:/ProgramLanguage/vcpkg-master/downloads
-- CURRENT_PACKAGES_DIR=D:/ProgramLanguage/vcpkg-master/packages/boost-build_x64-windows
-- CURRENT_BUILDTREES_DIR=D:/ProgramLanguage/vcpkg-master/buildtrees/boost-build
-- CURRENT_PORT_DIR=D:/ProgramLanguage/vcpkg-master/ports/boost-build/.
-- Using cached D:/ProgramLanguage/vcpkg-master/downloads/boostorg-build-boost-1.66.0.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Using cached D:/ProgramLanguage/vcpkg-master/downloads/boost_LICENSE_1_0.txt
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Using cached D:/ProgramLanguage/vcpkg-master/downloads/boost-1.66.0-boostcpp.jam
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Bootstrapping...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: D:/ProgramLanguage/vcpkg-master/packages/boost-build_x64-windows/tools/boost-build/bootstrap.bat;msvc
    Working Directory: D:/ProgramLanguage/vcpkg-master/packages/boost-build_x64-windows/tools/boost-build
    See logs for more information:
      D:\ProgramLanguage\vcpkg-master\buildtrees\boost-build\bootstrap-x64-windows-out.log
      D:\ProgramLanguage\vcpkg-master\buildtrees\boost-build\bootstrap-x64-windows-err.log

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:47 (vcpkg_execute_required_process)
  scripts/ports.cmake:72 (include)

Error: Building package boost-build:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-build:x64-windows
  Vcpkg version: 0.0.101-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by twkun** [comment]
bootstrap-x64-windows-out.log

Bootstrapping the build engine

Failed to bootstrap the build engine
Please consult bootstrap.log for furter diagnostics.

**Comment by twkun** [comment]
bootstrap-x64-windows-err.log

cl: 命令行 warning D9035 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000  .........     :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe 中有内部编译器错误。系统将会提示你稍后向 Microsoft 发送错误报告。
“C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe”中的内部编译器错误
  请选择 Visual C++ 
“帮助”菜单上的“技术支持”命令，或打开技术支持帮助文件来获得详细信息

**Comment by ras0219-msft** [comment]
Could you try installing the English language pack for VS? (See https://github.com/Microsoft/vcpkg/issues/2422)


If that doesn't work, please attach
>D:\ProgramLanguage\vcpkg-master\packages\boost-build_x64-windows\tools\boost-build\bootstrap.log

**Comment by 2812140729** [comment]
same problem

**Comment by whidbey** [comment]
same error I found

**Comment by wangli28** [comment]
Does the issue still occur? I installed it successfully with VS2015 and VCPKG latest source.

> PS E:\vcpkg> .\vcpkg.exe install boost-build:x64-windows
The following packages will be built and installed:
    boost-build[core]:x64-windows
Starting package 1/1: boost-build:x64-windows
Building package boost-build[core]:x64-windows...
A suitable version of cmake was not found (required v3.14.0). Downloading portable cmake v3.14.0...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.14.0/cmake-3.14.0-win32-x86.zip -> E:\vcpkg\downloads\cmake-3.14.0-win32-x86.zip
Extracting cmake...
-- Downloading https://github.com/boostorg/build/archive/boost-1.69.0.tar.gz...
-- Extracting source E:/vcpkg/downloads/boostorg-build-boost-1.69.0.tar.gz
-- Using source at E:/vcpkg/buildtrees/boost-build/src/ost-1.69.0-1d1e4d577d
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.69.0/LICENSE_1_0.txt...
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.69.0/boostcpp.jam...
-- Installing: E:/vcpkg/packages/boost-build_x64-windows/share/boost-build/copyright
-- Installing: E:/vcpkg/packages/boost-build_x64-windows/tools/boost-build/boostcpp.jam
-- Bootstrapping...
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-build[core]:x64-windows... done
Installing package boost-build[core]:x64-windows...
Installing package boost-build[core]:x64-windows... done
Elapsed time for package boost-build:x64-windows: 57.96 s
\
Total elapsed time: 57.96 s

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
