### ISSUE TITLE
request a new  port : Sofa

### ISSUE THREAD

**Issue by longzhmm** [microsoft/vcpkg#25771]
Library name:
sofa
Library description:
SOFA (Standards Of Fundamental Astronomy) software package is a subroutine library of astronomical basic standards written by IAU. At present, there are a total of 161 subroutines, which are mainly written in Fortran F77 and ANSI C. Each subroutine is placed in a .f file. Its main content includes two aspects: basic vector operations and astronomical basic standards.
Source repository URL:
https://iausofa.org/2021_0512_C/sofa_c-20210512.zip or https://github.com/longzhmm/csofa
Project homepage (if different from the source repository):
https://iausofa.org/ 
Anything else that is useful to know when adding (such as optional features the library may have that should be included):
I have built a local version of the library, but due to the lack of github open source knowledge, I hope someone can improve it and release it so that more people can use it.

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
