### ISSUE TITLE
./bootstrap-vcpkg.sh  gives me Exec format error while following Azure Embedded C IoT

### ISSUE THREAD

**Issue by uBoscuBo** [microsoft/vcpkg#25781]
Hello, 

I am trying to follow the instructions given [here](https://github.com/Azure/azure-sdk-for-c/tree/main/sdk/samples/iot) for the vcpkg section. When I follow the instruction using vcpkg version `tags/2020.06`, the `./bootstrap-vcpkg.sh` gives me the following error 

`./bootstrap-vcpkg.sh: 252: /home/uboscubo/EmbeddedDevTutorial/Chap11_Exploring_BBB/vcpkg/scripts/bootstrap.sh: /home/uboscubo/EmbeddedDevTutorial/Chap11_Exploring_BBB/vcpkg/downloads/tools/cmake-3.17.2-linux/cmake-3.17.2-Linux-x86_64/bin/cmake: Exec format error`

Is there anything wrong with this specific tag? Azure IoT recommended the using the tag 2020.06 as documented.

Thank you

I tried asking Azure IoT [here](https://github.com/Azure/azure-sdk-for-c/issues/2272)

**Comment by uBoscuBo** [comment]
I suspect it has to do with something with cmake version 3.17.2 and 2020.06 vcpkg.sh?

**Comment by uBoscuBo** [comment]
Repro: 

![image](https://user-images.githubusercontent.com/68073921/179235995-f4f39fea-780c-4f6b-8d78-7f8a63597a6c.png)

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
