### ISSUE TITLE
absolute paths to pdbs in dlls/exe and static libs

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#25794]
Some ports like openssl overwrite/ignore vcpkg setting of `/Z7` and use  `/Zi` instead. This however encodes absolute paths into the dll/exe which is pointed into the `buildtrees` folder where it was originally build.

This can be fixed by adding:
```
string(APPEND CMAKE_SHARED_LINKER_FLAGS " /PDBALTPATH:%_PDB%")
string(APPEND CMAKE_EXE_LINKER_FLAGS " /PDBALTPATH:%_PDB%")
```

which however breaks the `vcpkg_copy_pdbs()` since it uses that absolute path to detect where the pdb is in the buildtree.

(Further note: This is also the reason why we probably can never use `/Zi` since the same happens for static libs without a way to fix it.)

**Comment by Neumann-A** [comment]
next problem static libs also have references to non existing pdbs in buildtrees. Only way around that is to pass `/Brepro` to cl.

**Comment by JackBoosY** [comment]
@BillyONeal What do you think about?

**Comment by BillyONeal** [comment]
To my limited understanding, while these are full paths, they are 'hints' that shouldn't be necessary to consume anything in the 'installed' tree so I don't think they create serious problems, but it would hamper a strong post-build check for absolute paths.
