### ISSUE TITLE
[qt5-base] Build error

### ISSUE THREAD

**Issue by mikeb-ah** [microsoft/vcpkg#25798]
**Host Environment**
- OS: Windows 10 (Build 19044.1826)
- Compiler: VS2019 16.11.15

**To Reproduce**
`./vcpkg add port qt5[essentials]`
`./vcpkg install`

**Failure logs**
End of log: 

-- Configuring x64-windows-dbg
-- Configuring x64-windows-dbg done
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: C:/short-repos/Production-Builds/lightfield/submodules/vcpkg/downloads/tools/jom/jom-1.1.3/jom.exe /J 17
    Working Directory: C:/short-repos/Production-Builds/lightfield/submodules/vcpkg/buildtrees/qt5-base/x64-windows-dbg
    See logs for more information:
      C:\short-repos\Production-Builds\lightfield\submodules\vcpkg\buildtrees\qt5-base\build-x64-windows-dbg-out.log
      C:\short-repos\Production-Builds\lightfield\submodules\vcpkg\buildtrees\qt5-base\build-x64-windows-dbg-err.log

Call Stack (most recent call first):
  ports/qt5-base/cmake/install_qt.cmake:92 (vcpkg_execute_build_process)
  ports/qt5-base/portfile.cmake:355 (install_qt)
  scripts/ports.cmake:147 (include)
[build-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/9122664/build-x64-windows-dbg-err.log)
[build-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/9122666/build-x64-windows-dbg-out.log)

error: building qt5-base:x64-windows failed with: BUILD_FAILED

**Additional context**
Logs attached

**Comment by JackBoosY** [comment]
```
C:\short-repos\Production-Builds\lightfield\submodules\vcpkg\buildtrees\qt5-base\src\5.15.5-451bf817fc.clean\include\QtEventDispatcherSupport\5.15.5\QtEventDispatcherSupport/private/qwindowsguieventdispatcher_p.h(1): fatal error C1083: Cannot open include file: '../../../../../src/platformsupport/eventdispatchers/qwindowsguieventdispatcher_p.h': No such file or directory
```
Please clone vcpkg in a shorter path such as `c:/vcpkg` then try again.

Thanks.

**Comment by michaelaeriksen** [comment]
I also can't build QT5. Looks like same `jom` error

```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: E:/vcpkg/downloads/tools/jom/jom-1.1.3/jom.exe -j 17
    Working Directory: E:/vcpkg/buildtrees/qt5-declarative/x64-windows-dbg
    See logs for more information:
      E:\vcpkg\buildtrees\qt5-declarative\package-build-x64-windows-dbg-out.log
      E:\vcpkg\buildtrees\qt5-declarative\package-build-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_qmake.cmake:3 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_build_qmake.cmake:75 (z_run_jom_build)
  installed/x64-windows/share/qt5/qt_build_submodule.cmake:14 (vcpkg_build_qmake)
  installed/x64-windows/share/qt5/qt_submodule_installation.cmake:9 (qt_build_submodule)
  ports/qt5-declarative/portfile.cmake:2 (qt_submodule_installation)
  scripts/ports.cmake:147 (include)


error: building qt5-declarative:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qt5-declarative
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[qt5-declarative]+Build+error
Include '[qt5-declarative] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-07-14-fb7e3b1bb3b1ca185fffe2be36b2fbc53198360f
    vcpkg-scripts version: 678c0ea99 2022-07-18 (43 minutes ago)

You can also use the prefilled template from E:\vcpkg\installed\vcpkg\issue_body.md.
```

**Comment by JackBoosY** [comment]
@michaelaeriksen Please provide _E:\vcpkg\buildtrees\qt5-declarative\package-build-x64-windows-dbg-out.log_ first.

**Comment by michaelaeriksen** [comment]
[package-build-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/9136403/package-build-x64-windows-dbg-out.log)

**Comment by JackBoosY** [comment]
Also please provide _E:\vcpkg\buildtrees\qt5-declarative\package-build-x64-windows-dbg-err.log_, the error details are not in dbg-out.

**Comment by michaelaeriksen** [comment]
[package-build-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/9136418/package-build-x64-windows-dbg-err.log)

**Comment by JackBoosY** [comment]
```

jom 1.1.3 - empower your cores

WARNING: Failure to find: qt5qmld_metatypes.json
WARNING: Failure to find: E:/vcpkg/buildtrees/qt5-declarative/src/5.15.5-83ce81531c.clean/src/3rdparty/masm/assembler/*.h
WARNING: Failure to find: E:/vcpkg/buildtrees/qt5-declarative/src/5.15.5-83ce81531c.clean/src/3rdparty/masm/wtf/*.h
WARNING: Failure to find: E:/vcpkg/buildtrees/qt5-declarative/x64-windows-dbg/src/qml/qt5qmld_metatypes.json
WARNING: Failure to find: qt5qml_metatypes.json
WARNING: Failure to find: E:/vcpkg/buildtrees/qt5-declarative/src/5.15.5-83ce81531c.clean/src/3rdparty/masm/assembler/*.h
WARNING: Failure to find: E:/vcpkg/buildtrees/qt5-declarative/src/5.15.5-83ce81531c.clean/src/3rdparty/masm/wtf/*.h
WARNING: Failure to find: E:/vcpkg/buildtrees/qt5-declarative/x64-windows-dbg/src/qml/qt5qml_metatypes.json
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
jom: E:\vcpkg\buildtrees\qt5-declarative\x64-windows-dbg\src\qml\Makefile.Debug [.generated\debug\RegExpJitTables.h] Error 9009
jom: E:\vcpkg\buildtrees\qt5-declarative\x64-windows-dbg\src\qml\Makefile [debug] Error 2
jom: E:\vcpkg\buildtrees\qt5-declarative\x64-windows-dbg\src\Makefile [sub-qml-make_first-ordered] Error 2
jom: E:\vcpkg\buildtrees\qt5-declarative\x64-windows-dbg\Makefile [sub-src-make_first] Error 2
```
Did you install python in Windows store or some where?

**Comment by michaelaeriksen** [comment]
I have Python at `C:\Python310`

**Comment by michaelaeriksen** [comment]
and I have `C:\Python310\Scripts\;C:\Python310\` in my PATH

**Comment by JackBoosY** [comment]
@Neumann-A Does qt5-declarative implicitly depend on python3?

**Comment by JackBoosY** [comment]
@mikeb-ah This is because the path is too long.
You can also enable long path on Windows, see https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later
Or use `--x-buildtrees-root=SHORTER_PATH` to install qt5 only.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by michaelaeriksen** [comment]
I was never able to find a solution other than not build `qt5-declarative`.

**Comment by minorsecond** [comment]
@michaelaeriksen how do you instruct vcpkg to not build `qt5-declarative`?
