### ISSUE TITLE
How to build for XP

### ISSUE THREAD

**Issue by VikingExplorer** [microsoft/vcpkg#2580]
what change do I have to make in order to support Windows XP?

Is it: set(VCPKG_PLATFORM_TOOLSET v141_xp)

**Comment by VikingExplorer** [comment]
I tried this, but got:

Additional packages (*) will be modified to complete this operation.
Starting package 1/270: boost-vcpkg-helpers:x86-windows-static-md
Building package boost-vcpkg-helpers:x86-windows-static-md...
A suitable version of cmake was not found (required v3.10.1). Downloading portable cmake v3.10.1...
Could not find Visual Studio instance with v141_xp toolset.

However, absolutely not true:
<img width="649" alt="capture" src="https://user-images.githubusercontent.com/15109208/34950988-c843a2e0-f9e2-11e7-8b0e-4c0aeefc0db7.PNG">

**Comment by D4N** [comment]
You cannot set the platform toolset from within a `CMakeLists.txt`, you have to pass it via the `-T` parameter to cmake on the command line **and** you must use a Visual Studio generator (ninja won't work). For example:
```
cmake -G "Visual Studio 15 2017" -T v141_xp /path/to/CMakeLists/folder/
```
That will create a Visual Studio solution in the folder where you invoked cmake, which you can use to compile the project.

Hope this helps! (I haven't tried this and I have never used vcpkg, I just found your post via google from an unrelated issue.)

**Comment by NancyLi1013** [comment]
Hi all.

Thanks for posting this issue. It's duplicated to #2225. So let's move the discussion there.
