### ISSUE TITLE
cpr update to 1.8.4

### ISSUE THREAD

**Issue by hamzaahmedzia1** [microsoft/vcpkg#25813]
Library name:
[cpr](https://github.com/libcpr/cpr)
New version number:
1.8.4
Other information that may be useful (release notes, etc...)
Currently cpr port is at Version: 1.7.2

**Comment by dg0yt** [comment]
Duplicates #25686.

**Comment by JackBoosY** [comment]
Dupliated of https://github.com/microsoft/vcpkg/issues/25237
