### ISSUE TITLE
[SDL1] build failure

### ISSUE THREAD

**Issue by quinnsummerfield** [microsoft/vcpkg#25818]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2022

**To Reproduce**
- Open VS 2022
- Clone https://github.com/Microsoft/vcpkg.git

**Failure logs**
C:\vc\ports\sdl1\SDL\SDL.vcxproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\vc\ports\sdl1\SDL\SDL.vcxproj'.

**Additional context**
- I uninstalled and reinstalled VS 2022, making sure I had all of the necessary components and workflows. I installed it with everything that is currently an option (even things I personally don't believe I need), but that didn't resolve the issue.

- I've tried shortening the path by cloning directly to C:\vc since the documentation listed the path length as a possible issue, but no matter how short the path name, this issue occurs for me.

**Comment by Cheney-W** [comment]
Does this issue occur when you use `.\vcpkg install sdl1:x64-windows` ?

**Comment by quinnsummerfield** [comment]
Please excuse my ignorance, as I'm still learning...where do I use that command?

![image](https://user-images.githubusercontent.com/65475850/179632091-7a80f2a1-813f-41c3-ac33-709e497ed647.png)

**Comment by Cheney-W** [comment]
A general procedure for using vcpkg:
1. Open PowerShell. `(cmd also works)`
2. Pushd E:\ `(Determine the path where the vcpkg folder is stored)`
3. git clone https://github.com/Microsoft/vcpkg.git `(clone vcpkg)`
4. cd .\vcpkg\
5.  .\bootstrap-vcpkg.bat (download the vcpkg.exe)
6. ./vcpkg install sdl1:x64-windows 

https://github.com/Microsoft/vcpkg#quick-start-windows

**Comment by Cheney-W** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
