### ISSUE TITLE
I Have failed to build MUMPS 

### ISSUE THREAD

**Issue by sweety2142** [Microsoft/vcpkg#2581]
this is my result 

-- Configuring x86-windows-rel
-- Configuring x86-windows-rel done
-- Configuring x86-windows-dbg
-- Configuring x86-windows-dbg done
-- Build x86-windows-rel
-- Build x86-windows-rel done
-- Build x86-windows-dbg
-- Build x86-windows-dbg done
-- Performing post-build validation
Detected outdated dynamic CRT in the following files:

    C:/Users/sweet/Downloads/vcpkg-fortran-ports/vcpkg-fortran-ports/packages/reference-lapack_x86-windows/debug/bin/libblas.dll: msvcrt.dll
    C:/Users/sweet/Downloads/vcpkg-fortran-ports/vcpkg-fortran-ports/packages/reference-lapack_x86-windows/debug/bin/libcblas.dll: msvcrt.dll
    C:/Users/sweet/Downloads/vcpkg-fortran-ports/vcpkg-fortran-ports/packages/reference-lapack_x86-windows/debug/bin/liblapack.dll: msvcrt.dll
    C:/Users/sweet/Downloads/vcpkg-fortran-ports/vcpkg-fortran-ports/packages/reference-lapack_x86-windows/debug/bin/liblapacke.dll: msvcrt.dll
    C:/Users/sweet/Downloads/vcpkg-fortran-ports/vcpkg-fortran-ports/packages/reference-lapack_x86-windows/bin/libblas.dll: msvcrt.dll
    C:/Users/sweet/Downloads/vcpkg-fortran-ports/vcpkg-fortran-ports/packages/reference-lapack_x86-windows/bin/libcblas.dll: msvcrt.dll
    C:/Users/sweet/Downloads/vcpkg-fortran-ports/vcpkg-fortran-ports/packages/reference-lapack_x86-windows/bin/liblapack.dll: msvcrt.dll
    C:/Users/sweet/Downloads/vcpkg-fortran-ports/vcpkg-fortran-ports/packages/reference-lapack_x86-windows/bin/liblapacke.dll: msvcrt.dll

To inspect the dll files, use:
    dumpbin.exe /dependents mydllfile.dll
Found 1 error(s). Please correct the portfile:
    C:\Users\sweet\Downloads\vcpkg-fortran-ports\vcpkg-fortran-ports\ports\reference-lapack\portfile.cmake
-- Performing post-build validation done
Error: Building package reference-lapack:x86-windows failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: reference-lapack:x86-windows

I do not understand this results. 
please help me

**Comment by albertziegenhagel** [comment]
`MUMPS` is not available as an official port in `vcpkg`. I assume you used the `fortran-ports` branch of my fork with the Fortran compiler set to `GNU`. GNU/gfortran support is experimental only at the moment since MinGW does not support linking to the new UCRT yet (hence you are seeing the errors). Please take a look at #1098 and #485 for more information.

You may want to switch the compilers. `Intel` should work but is not free. `PGI` is free and should work as well, but you need to install Visual Studio 2015 (although after that you can use the Visual Studio 2017 toolset). `GNU` has the problems mentioned above. `Flang` is the new hope because it is free but it is still in kind of early develepment states. Maybe @isuruf or @xoviat can comment on what the current status of Flang is.

**Comment by xoviat** [comment]
Are there any problems with flang? The main issue is that we haven't had enough battle testing but that requires people to use it.

**Comment by albertziegenhagel** [comment]
I did not do a lot of testing as well. The last time when I tried to build MUMPS there was an error about a missing include file although my first impression was that all `-I<path>` arguments where correct.

@xoviat  Is `flang-5.0.0-vc14_1` still the most up-to-date build of flang in the conda packages? If not, just let me know which packages is up to date and I will update the flang version that is downloaded in my fortran branch.

**Comment by isuruf** [comment]
Latest packages
```
clangdev:       5.0.0-flang_3       conda-forge [flang vc14]
flang:          5.0.0-vc14_20180101 conda-forge [vc14      ]
libflang:       5.0.0-vc14_20180101 conda-forge [vc14      ]
openmp:         5.0.0-vc14_0        conda-forge [vc14      ]
```

**Comment by albertziegenhagel** [comment]
I think that would be great!

**Comment by isuruf** [comment]
Done. Now, even if they are removed from the main codna-forge channel, the links will be stable.

**Comment by xoviat** [comment]
flang should have been able to build MUMPS without any issues. Let me attempt to reproduce this...

**Comment by xoviat** [comment]
FYI Perhaps you should add triplets to your branch.

**Comment by xoviat** [comment]
So the first problem that I encountered is that the reference LAPACK failed to build. However, I was able to build the reference lapack without any problems [here](https://ci.appveyor.com/project/langou/lapack/build/1.0.146).

**Comment by albertziegenhagel** [comment]
> FYI Perhaps you should add triplets to your branch.

I think the policy of vcpkg is not to have to many default triplets provided. Instead the user should adjust the triplets himself if he needs to.

> So the first problem that I encountered is that the reference LAPACK failed to build.

The last time I checked it was working correctly. I will try to update Flang and check again. Thanks for the hint.

**Comment by sweety2142** [comment]
Thanks guys~ I solved problem with option adding

**Comment by xoviat** [comment]
Sorry, I forgot to mention this: flang currently requires the CMake development branch; the version available on conda is patched until the next release comes out. That might be why the build is currently failing.

**Comment by xoviat** [comment]
Currently the best build performance is available using the CMake development branch and kitware ninja. Eventually patches will be merged into mainline, but ninja is moving very slowly.
