### ISSUE TITLE
vcpkg upgrade doesn't work

### ISSUE THREAD

**Issue by VikingExplorer** [Microsoft/vcpkg#2582]
1. Open VS dev Cmd prompt
	2. cd C:\Dev\3pLibs\vcpkg
	3. git pull
	4. (bootstrap-vcpkg.bat) if it indicates
	5. vcpkg update   (to see what is out of date)
	6. vcpkg upgrade --no-dry-run

All mayhem ensued. Errors galore. Packages disappeared.

Deleted vcpkg entirely, started over.

	1. install 64 bit git (https://git-scm.com/download/win)
	2. Open VS dev Cmd prompt
	3. cd C:\Dev\3pLibs
	4. git clone https://github.com/Microsoft/vcpkg
	5. cd vcpkg
	6. bootstrap-vcpkg.bat
	7. open up VS -> Source Control Explorer
	8. Select files in $/3pLibs/vcpkg/triplets (make sure that our triplet files are downloaded)
	9. Right click, select "Check out for edit"  (Lock type: Unchanged)
	10. vcpkg install

		1. vcpkg install boost:x64-windows-static-md boost:x86-windows-static-md

**Comment by ras0219-msft** [comment]
>The following packages are not installed, so not removed:
**boost**:x64-windows-static-md

>C:\Dev\Couloir\3pLibs\vcpkg>vcpkg list
**boost-algorithm**:x64-windows-static-md 1.66.0 Boost algorithm module

In 1.66 we've modularized boost, so each sub-library is listed separately. For convenience, we still have a "meta-package" named "boost" which requires each of the smaller libraries, however this unfortunately only works for _installation_ and not for removal.

In this case, you can call `vcpkg remove boost-algorithm:x64-windows-static-md` to remove that specific sub-library. To ensure all boost sublibraries are removed, you can either use `vcpkg list boost` and remove each sub-library (brute force fallback) or simply remove `boost-vcpkg-helpers` and `boost-build` which all the other libraries depend upon.

That said, this is definitely an area that could use improvement!

**Comment by VikingExplorer** [comment]
Tried it again.   All worked fine.

**Comment by VikingExplorer** [comment]
It didn't work.

produced: boost_system-vc140-mt-gd.lib
expected: boost_system-vc140-mt-gd-1_66.lib

1>Linking to lib file: boost_system-vc140-mt-gd-1_66.lib
1>foo.cpp
1>Linking to lib file: boost_date_time-vc140-mt-gd-1_66.lib
**1>LINK : fatal error LNK1104: cannot open file 'boost_system-vc140-mt-gd-1_66.lib'**

**Comment by ras0219-msft** [comment]
Unfortunately, these are the "correct" library names. You can take a look at the conversation starting at [1] for the full details, but basically:

- Boost has added an extra component to their lib names by default which breaks CMake before 3.10.3 (`-x64-`)
- Therefore, we used to remove that part of the lib name (which worked)
- The _latest_ CMake has added code to handle the `-x64-` tag, but now _requires_ it if it detects that the boost version is `1_66` or greater. This breaks our previous workaround and prevents either scheme from functioning
- However, all CMake versions _do_ detect the scheme `boost_<lib>-<compiler>-mt-gd.lib`. Therefore, we use this to satisfy all currently deployed CMake versions.

[1] https://github.com/Microsoft/vcpkg/issues/2459#issuecomment-357723448
