### ISSUE TITLE
[glib] update to 2.72.3

### ISSUE THREAD

**Issue by desowin** [microsoft/vcpkg#25836]
Library name: glib

New version number: 2.72.3

Other information that may be useful (release notes, etc...)
GLib 2.72 release makes it possible to [integrate GLib into foreign event loops](https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1960).

**Comment by FrankXie05** [comment]
@desowin I see the latest version of `glib` is 2.73.2, I will update version to this. 
https://gitlab.gnome.org/GNOME/glib/-/tree/2.73.2

**Comment by desowin** [comment]
> @desowin I see the latest version of `glib` is 2.73.2, I will update version to this. https://gitlab.gnome.org/GNOME/glib/-/tree/2.73.2

When the second number is odd, it indicates unstable release.

**Comment by FrankXie05** [comment]
Thanks for your reply, I get it. :)

**Comment by desowin** [comment]
From GLib [SECURITY.md](https://gitlab.gnome.org/GNOME/glib/-/blob/main/SECURITY.md)
> Under GLib’s versioning scheme, stable release series have an even minor
> component (for example, 2.66.0, 2.66.1, 2.68.3), and development release series
> have an odd minor component (2.67.1, 2.69.0).
