### ISSUE TITLE
liblzma build failure

### ISSUE THREAD

**Issue by c0do** [microsoft/vcpkg#2584]
trying to install libxslt and the build for a dependant project liblzma fails.
package liblzma:arm-uwp
vcpkg version: 0.0.85-unknown hash

[package-arm-uwp-rel-out.log](https://github.com/Microsoft/vcpkg/files/1633251/package-arm-uwp-rel-out.log)

**Comment by ras0219-msft** [comment]
Thanks for posting this issue!

First, I'd recommend you update to the latest vcpkg (0.0.101) -- just run
```
git pull
bootstrap-vcpkg.bat
vcpkg upgrade
```

Next, unfortunately `liblzma` does not currently build for UWP. I'd love to accept a patch that fixes it though!

**Comment by NancyLi1013** [comment]
Hi @c0do, thanks for posting this issue. This port has been updated. It can support UWP now. This feature has been merged in this PR #5607. Please try to update this port to the latest version and try to use it.
