### ISSUE TITLE
vcpkg edit: EDITOR variable not considered

### ISSUE THREAD

**Issue by Squareys** [Microsoft/vcpkg#2585]
Hello everybody!

I just started using vcpkg, and I like it so far!

Trying to use vcpkg edit [magnum](https://github.com/mosra/magnum/), I noticed that this always outputs:

~~~
[...]\build>vcpkg edit magnum
Error: Visual Studio Code was not found and the environment variable EDITOR is not set.
The following paths were examined:

    C:/Program Files/Microsoft VS Code Insiders/Code - Insiders.exe
    C:/Program Files (x86)/Microsoft VS Code Insiders/Code - Insiders.exe
    C:/Program Files/Microsoft VS Code/Code.exe
    C:/Program Files (x86)/Microsoft VS Code/Code.exe

You can also set the environmental variable EDITOR to your editor of choice.

[...]\build>echo %EDITOR%
C:\Program Files\Vim\vim80\gvim.exe
~~~

As you can tell, my environment var is definitely set.
Looking at the code, [this line](https://github.com/Microsoft/vcpkg/blob/master/toolsrc/src/vcpkg/commands.edit.cpp#L71) is pretty suspicious: While it tries to find a file and uses where.exe to do so, it tries to find a file called `"EDITOR"` without ever resolving that to a variable. Given it executes a command in that function and captures the output, I think "%EDITOR%" could work instead.

Thanks for your help!
Cheers, Jonathan

**Comment by Squareys** [comment]
Passing `"%EDITOR%"` did not work (maybe not properly escaped?).

Adding this on line 74 in commands.edit.cpp, did, though:

~~~cpp
        auto editor = System::get_environment_variable("EDITOR");
        if (editor.has_value()) {
            candidate_paths.push_back(fs::path(*editor.get()));
        }
~~~

**Comment by ras0219-msft** [comment]
Thanks for posting this issue!

Yep, I agree this is the solution. I'd love to accept that as a PR, would you mind opening one?
