### ISSUE TITLE
[chartdir] Build error

### ISSUE THREAD

**Issue by joebre** [microsoft/vcpkg#25854]
**Host Environment**
- Windows 10 x64
- Compiler: vs 2019

**To Reproduce**
`./vcpkg install wxchartdir`

**Failure logs**
Computing installation plan...
The following packages will be built and installed:
  * chartdir[core]:x64-windows -> 7.0.0#2
    wxchartdir[core]:x64-windows -> 1.0.0#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\joel.brenner\AppData\Local\vcpkg\archives in 237.8 us. Use --debug to see more details.
Starting package 1/2: chartdir:x64-windows
Building package chartdir[core]:x64-windows...
-- Downloading https://www.advsofteng.net/chartdir_cpp_win.zip -> chartdir_cpp_win-7.0.0.zip...
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Downloading https://www.advsofteng.net/chartdir_cpp_win.zip
Error: Failed to download from mirror set:
File does not have the expected hash:
             url : [ https://www.advsofteng.net/chartdir_cpp_win.zip ]
       File path : [ C:\srcvcpkg\vcpkg\downloads\chartdir_cpp_win-7.0.0.zip.2424.part ]
   Expected hash : [ 38d9dae641c0341ccee4709138afd37ad4718c34def70a0dc569956bf9c3488d0d66072f604dca4663dc80bd09446a2ba27ef3806fc3b87dda6aaa5453a7316f ]
     Actual hash : [ e5b5d387cff693a7f5ee98c2d2df75f421129b006e4324ae30ace0cbaac58867f048868ddfacdb3224c7165c8f27219c4273f3c778be3330d39ef95260d4186b ]

[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(705)
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 1 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 795 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 19.2 s (19194364 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):

      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. You proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:309 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/chartdir/portfile.cmake:9 (vcpkg_download_distfile)
  scripts/ports.cmake:145 (include)

Error: Building package chartdir:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+chartdir
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[chartdir]+Build+error
including:
  package: chartdir[core]:x64-windows -> 7.0.0#2
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: 2b543e52d 2022-01-31 (6 months ago)

Additionally, attach any relevant sections from the log files above.

**Comment by autoantwort** [comment]
> vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
vcpkg-scripts version: https://github.com/microsoft/vcpkg/commit/2b543e52da6a7a595760f10c1160e808d89c41ed 2022-01-31 (6 months ago)

Please update your vcpkg version :)

**Comment by FrankXie05** [comment]
@joebre The current version of port `chartdir` is `7.0.0#5` https://github.com/microsoft/vcpkg/blob/master/ports/chartdir/vcpkg.json , please use the latest `vcpkg` and try again. :)

**Comment by FrankXie05** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by joebre** [comment]
Hi Frank, yes … your advice fixed the problem …. Thx

 

Regards, Joel
