### ISSUE TITLE
[google-cloud-cpp] Build error

### ISSUE THREAD

**Issue by GitHubby148** [microsoft/vcpkg#25857]
- OS: Windows
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30139 for x86 

./vcpkg install google-cloud-cpp:x86-windows
./vcpkg install google-cloud-cpp:x64-windows

error: building google-cloud-cpp:x86-windows failed with: BUILD_FAILED
error: building google-cloud-cpp:x64-windows failed with: BUILD_FAILED

CMake Error at googleapis_download-stamp/download-googleapis_download.cmake:170 (message):
  Each download failed!

    error: downloading 'https://github.com/googleapis/googleapis/archive/e0d0106516a5c613510533821e4508bc6c943b11.tar.gz' failed
          status_code: 22
          status_string: "HTTP response code said error"
          log:
          --- LOG BEGIN ---
          Uses proxy env variable https_proxy == 'http:// XXXX.XXXX.XXX:8080'

  timeout on name lookup is not supported

    Trying 10.111.1.14:8080...

  Connected to XXXX.XXXX.XXX (X.X.X.X) port 8080 (#0)

  allocate connect buffer!

  Establish HTTP proxy tunnel to github.com:443

  CONNECT github.com:443 HTTP/1.1

  Host: github.com:443

  User-Agent: curl/7.79.1

  Proxy-Connection: Keep-Alive

  

  HTTP/1.1 407 Proxy Authentication Required

  Proxy-Authenticate: NEGOTIATE

  Proxy-Authenticate: NTLM

  Cache-Control: no-cache

  Pragma: no-cache

  X-XSS-Protection: 1

  Content-Type: text/html; charset=utf-8

  Proxy-Connection: close

  Connection: close

  Content-Length: 3379

  

  Ignore 3379 bytes of response-body

  The requested URL returned error: 407

  CONNECT phase completed!

  Closing connection 0

Notes: Generally downloading succeeds, and proxy settings are correct - but for some reason this download does not seems to authenticate with the proxy

This causes further errors down the line (issue is generally the same for 64 & 32 bit builds)
Peeking into the log the build process:
[38/1223] C:\PROGRA~2\MIB055~1\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x86\cl.exe   /TP -DJSON_DIAGNOSTICS=0 -DJSON_USE_IMPLICIT_CONVERSIONS=1 -IC:\dev\vcpkg\vcpkg\buildtrees\google-cloud-cpp\src\v2.0.0-ff07c4dea9.clean -external:IC:\dev\vcpkg\vcpkg\installed\x86-windows\include -external:IC:\dev\vcpkg\vcpkg\buildtrees\google-cloud-cpp\x86-windows-dbg -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -MDd /experimental:external /external:W0 /external:anglebrackets /W3 /showIncludes /Fogoogle\cloud\CMakeFiles\google_cloud_cpp_rest_internal.dir\internal\curl_impl.cc.obj /Fdgoogle\cloud\CMakeFiles\google_cloud_cpp_rest_internal.dir\google_cloud_cpp_rest_internal.pdb /FS -c C:\dev\vcpkg\vcpkg\buildtrees\google-cloud-cpp\src\v2.0.0-ff07c4dea9.clean\google\cloud\internal\curl_impl.cc
ninja: build stopped: subcommand failed.

Manually running the command line yields the following error:
C:\dev\vcpkg\vcpkg\buildtrees\google-cloud-cpp\src\v2.0.0-ff07c4dea9.clean\google/cloud/version.h(21): fatal error C1083: Cannot open include file: 'string': No such file or directory

**Comment by JackBoosY** [comment]
Please download [this file](https://github.com/microsoft/vcpkg/files/9146040/googleapis-e0d0106516a5c613510533821e4508bc6c943b11.tar.gz) and put it into _VCPKG_ROOT/downloads_ then try again.

Thanks.

**Comment by GitHubby148** [comment]
Already got that, managed to work around the issue by copying the file to the destination part during configuration, little messy but got the job done - from my perspective it looks like there is something which is not configured for negotiate protocol when using a proxy
