### ISSUE TITLE
[luajit] add 2.1.0-beta3

### ISSUE THREAD

**Issue by Wires77** [microsoft/vcpkg#25851]
Library name: luajit

New version number: 2.1.0-beta3

Many people are using the v2.1 branch of https://github.com/LuaJIT/LuaJIT and it would be useful to have that as an option, even if it's not the default

**Comment by JonLiu1993** [comment]
@Wires7,  Our policy does not allow port to be upgraded to beta version, I will wait for the 2.1.0 stable version to be released and continue to upgrade to the latest version and then merge pr

**Comment by Wires77** [comment]
@JonLiu1993 This beta has been out for 5 years now, so I'm not hopeful for a timely stable version to be released.  I understand that you have to tie the vcpkg version to a git hash, though.  Is there another workaround besides creating my own port file or using your PR branch?

**Comment by JonLiu1993** [comment]
> @JonLiu1993 This beta has been out for 5 years now, so I'm not hopeful for a timely stable version to be released. I understand that you have to tie the vcpkg version to a git hash, though. Is there another workaround besides creating my own port file or using your PR branch?

If you want to use this beta, just use my pr, you can also ask upstream if they will release the latest version soon, because I found that they are still submitting pr upstream to solve the problem recently
