### ISSUE TITLE
[python3] build failure with mixed linkage of dependent libraries.

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#25868]
**To Reproduce**
`./vcpkg install python3:x64-mixed-linkage-windows`
with a custom triplet having either zlib or bzip2 with `set(VCPKG_LIBRARY_LINKAGE static)` (and the rest dynamic)

**Comment by Hoikas** [comment]
failure logs?

**Comment by Neumann-A** [comment]
I have this already fixed with https://github.com/microsoft/vcpkg/compare/master...Neumann-A:vcpkg:python3_fix_mixed_dep_linkage. Currently trying to make the build with clang-cl work.

**Comment by jimwang118** [comment]
@Neumann-A You say this has been fixed by a [PR](https://github.com/microsoft/vcpkg/pull/26370). Is it possible to close this issue.
