### ISSUE TITLE
[boost-math] Build error

### ISSUE THREAD

**Issue by AdanJSuarez** [microsoft/vcpkg#25866]
**Host Environment**
- OS: Linux.
- Compiler: mingw-w64

**To Reproduce**
`./vcpkg install boost-math:x64-mingw-static`

**Failure logs**
[error.log](https://github.com/microsoft/vcpkg/files/9140728/error.log)

**Comments**
The error come from trying to build Hyperscan with mingw. Some Boost packages are the dependencies.

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated in 3 months, if it is still an issue, please reopen this issue.
