### ISSUE TITLE
[New Port Request] <minilzo>

### ISSUE THREAD

**Issue by ITotalJustice** [microsoft/vcpkg#25867]
Library name: minilzo

Library description: "miniLZO is a very lightweight subset of the LZO library intended for easy inclusion with your application. It is generated automatically from the LZO source code and contains the most important LZO functions."

Source repository URL: http://www.oberhumer.com/opensource/lzo/download/minilzo-2.10.tar.gz

Project homepage (if different from the source repository): http://www.oberhumer.com/opensource/lzo/#minilzo

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

the full lzo is already added, as seen here. https://github.com/microsoft/vcpkg/blob/master/ports/lzo/portfile.cmake

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
