### ISSUE TITLE
[New Port Request] xtensor-python

### ISSUE THREAD

**Issue by spectre-ns** [microsoft/vcpkg#25875]
Library name: xtensor-python

Library description: allows interoperability between python and xtensor 

Source repository URL: https://github.com/xtensor-stack/xtensor-python

Project homepage (if different from the source repository): https://xtensor-python.readthedocs.io/en/latest/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
Considering how many other xtensor libraries are available it would be nice to see this one added.

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
