### ISSUE TITLE
[pcl] build failure

### ISSUE THREAD

**Issue by Elija-hard** [microsoft/vcpkg#25880]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler:  Windows

**To Reproduce**
`./vcpkg install pcl

**Failure logs**
Installing 1/15 liblzma:x86-windows...
Building liblzma[core]:x86-windows...
-- Using cached xz-mirror-xz-v5.2.5.tar.gz.
-- Cleaning sources at D:/work/vcpkg/buildtrees/liblzma/src/v5.2.5-2a8bfa3c42.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/work/vcpkg/downloads/xz-mirror-xz-v5.2.5.tar.gz
-- Applying patch enable-uwp-builds.patch
-- Applying patch fix_config_include.patch
-- Applying patch win_output_name.patch
-- Applying patch add_support_ios.patch
-- Applying patch build-tools.patch
-- Using source at D:/work/vcpkg/buildtrees/liblzma/src/v5.2.5-2a8bfa3c42.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: D:/work/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j7
    Working Directory: D:/work/vcpkg/buildtrees/liblzma/x86-windows-dbg
    See logs for more information:
      D:\work\vcpkg\buildtrees\liblzma\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/liblzma/portfile.cmake:24 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building liblzma:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+liblzma
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[liblzma]+Build+error
Include '[liblzma] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-07-14-fb7e3b1bb3b1ca185fffe2be36b2fbc53198360f
    vcpkg-scripts version: 8ff168270 2022-07-19 (8 hours ago)

You can also use the prefilled template from D:\work\vcpkg\installed\vcpkg\issue_body.md.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Cheney-W** [comment]
Could you please provide us with `D:\work\vcpkg\buildtrees\liblzma\install-x86-windows-dbg-out.log`?

**Comment by Elija-hard** [comment]
The log file is too large to upload

**Comment by Cheney-W** [comment]
`Microsoft Visual Studio 14.0`? Which version of VS is installed locally? Besides v140, do you have a higher version of toolset installed?

**Comment by Elija-hard** [comment]
vs2015，No other version is installed

**Comment by Cheney-W** [comment]
Does this issue still exist?

**Comment by Hankyin** [comment]
o shit， I meet the same question！
who can tell me how to solve it please？I use VS2022 on Win10.

**Comment by Hankyin** [comment]
I don‘t want to use PCL-AllInOne， configure VS is too boring

**Comment by sfhacker** [comment]
https://english-for-chinese.blogspot.com/2008/06/and-meet-problem.html

**Comment by Cheney-W** [comment]
@Hankyin Could you send me your complete error logs?

**Comment by Hankyin** [comment]
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: C:/Users/CodeRepository/vcpkg/downloads/tools/cmake-3.24.0-windows/cmake-3.24.0-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: C:/Users/MyProject/CodeRepository/vcpkg/buildtrees/pcl/x86-windows-dbg
    See logs for more information:
      C:\Users\MyProject\CodeRepository\vcpkg\buildtrees\pcl\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/pcl/portfile.cmake:85 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

config-x86-windows-err.log is empty

[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/9738863/config-x86-windows-out.log)

**Comment by Hankyin** [comment]
@Cheney-W

**Comment by dg0yt** [comment]
> ~~~
> See logs for more information:
> C:\Users\MyProject\CodeRepository\vcpkg\buildtrees\pcl\install-x86-windows-dbg-out.log

Please attach the right log file...

**Comment by Hankyin** [comment]
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/9740556/install-x86-windows-dbg-out.log)

I'm so sorry, 😅
I always read the wrong log file,No wonder I can't find the error message

**Comment by Hankyin** [comment]
at the end of this log :
xxxxxxxxxxx
FAILED: bin/pcl_filtersd.dll lib/pcl_filtersd.lib 
xxxxxxxxxxxx
LINK : fatal error LNK1168: 无法打开 bin\pcl_filtersd.dll 进行写入(can not open bin\pcl_filtersd.dll for writing)

**Comment by Hankyin** [comment]
I solve the problem !!!

**Comment by Hankyin** [comment]
delete the 
    AlibabaProtect
    AliPaladin
is useful.

https://github.com/microsoft/vcpkg/issues/10139#issuecomment-1097718000

**Comment by Cheney-W** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.

**Comment by best-pureer** [comment]
> 

阿里巴巴是真滴恶心
alibaba is a real super standard shit
