### ISSUE TITLE
[rapidjson] build failure

### ISSUE THREAD

**Issue by LegalizeAdulthood** [microsoft/vcpkg#25895]
**Host Environment**
- OS: WSL Ubuntu 20.04
- Compiler: g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

**To Reproduce**
Start with a fresh WSL installation
Check out vcpkg with git clone into ~/vcpkg
create a manifest like:
```
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json",
  "name": "comicsdb",
  "version": "1.0.0",
  "dependencies": [
    "pistache",
    "rapidjson"
  ]
}
```
Run cmake:
```
cmake -DCMAKE_TOOLCHAIN_FILE:FILEPATH=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake ../comicsdb
```

**Failure logs**
console:
```
cmake -DCMAKE_TOOLCHAIN_FILE:FILEPATH=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake ../comicsdb
-- Running vcpkg install
Detecting compiler hash for triplet x64-linux...
The following packages will be built and installed:
    pistache[core]:x64-linux -> 2021-03-31#3
    rapidjson[core]:x64-linux -> 2022-06-28#2
Restored 0 package(s) from /home/rthomson/.cache/vcpkg/archives in 294.1 us. Use --debug to see more details.
Installing 1/2 rapidjson:x64-linux...
Building rapidjson[core]:x64-linux...
-- Using cached Tencent-rapidjson-232389d4f1012dddec4ef84861face2d2ba85709-2.tar.gz.
-- Cleaning sources at /home/rthomson/vcpkg/buildtrees/rapidjson/src/2d2ba85709-f8b6aae484.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/rthomson/vcpkg/downloads/Tencent-rapidjson-232389d4f1012dddec4ef84861face2d2ba85709-2.tar.gz
CMake Error at scripts/cmake/vcpkg_extract_source_archive.cmake:159 (file):
  file RENAME failed to rename

    /home/rthomson/vcpkg/buildtrees/rapidjson/src/2d2ba85709-f8b6aae484.clean.tmp/rapidjson-232389d4f1012dddec4ef84861face2d2ba85709

  to

    /home/rthomson/vcpkg/buildtrees/rapidjson/src/2d2ba85709-f8b6aae484.clean

  because: Permission denied

Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:8 (vcpkg_extract_source_archive)
  scripts/cmake/vcpkg_from_github.cmake:113 (vcpkg_extract_source_archive_ex)
  ports/rapidjson/portfile.cmake:2 (vcpkg_from_github)
  scripts/ports.cmake:147 (include)


error: building rapidjson:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+rapidjson
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[rapidjson]+Build+error
Include '[rapidjson] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-07-14-fb7e3b1bb3b1ca185fffe2be36b2fbc53198360f
    vcpkg-scripts version: 8ff168270 2022-07-19 (18 hours ago)

You can also use the prefilled template from /home/rthomson/pistache/build/vcpkg_installed/vcpkg/issue_body.md.

-- Running vcpkg install - failed
CMake Error at /home/rthomson/vcpkg/scripts/buildsystems/vcpkg.cmake:858 (message):
  vcpkg install failed.  See logs for more information:
  /home/rthomson/pistache/build/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/share/cmake-3.23/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:2 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```
-Please attach any additional failure logs mentioned in the console output.
[vcpkg.zip](https://github.com/microsoft/vcpkg/files/9151974/vcpkg.zip)

**Additional context**
This is fresh from scratch WSL.  Earlier error messages gave confusing indications until I realized that g++ wasn't installed by default in WSL.

The attached code ZIP doesn't compile, but it should cmake configure (I'm working up an example of using pistache by converting a restbed example)
[comicsdb.zip](https://github.com/microsoft/vcpkg/files/9151990/comicsdb.zip)

**Comment by LegalizeAdulthood** [comment]
`vcpkg install rapidjson` succeeds, so it's something specific to manifest mode apparently

**Comment by LegalizeAdulthood** [comment]
vcpkg hash 8ff168270bc5977384b008bec6e879e15089d850

**Comment by LegalizeAdulthood** [comment]
If I remove `rapidjson` from the manifest, then I get the same permissions error when attempting to install pistache from the manifest, so perhaps it's a generic problem not specific to rapidjson

**Comment by LegalizeAdulthood** [comment]
Also, apparently one of the build recipes required ninja but didn't download and install it for itself, so I got an earlier error with the manifest complaining about ninja in the log files.  Manually installing ninja on WSL got past that problem.

**Comment by FrankXie05** [comment]
@LegalizeAdulthood  Please check your file permissions.
````
because: Permission denied
````
About error:  Make sure your system is installed and can successfully use build tools such as `gcc` or `ninja`
````
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
````

**Comment by FrankXie05** [comment]
@LegalizeAdulthood does the issue still occur?

**Comment by FrankXie05** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by LegalizeAdulthood** [comment]
@FrankXie05 Did anything change?  If not, then yes, it still occurs.

**Comment by LegalizeAdulthood** [comment]
There's no open for me to "reopen", just comment.

**Comment by LegalizeAdulthood** [comment]
You guys really need to get out of the habit of closing things just for the sake of closing them.  This is a horrible habit you're carrying over from MSVC project style bug management.

**Comment by FrankXie05** [comment]
@LegalizeAdulthood Sorry for the confused, apparently you didn't answer my question(https://github.com/microsoft/vcpkg/issues/25895#issuecomment-1190987913). and didn't reply me the second time I pinged you.https://github.com/microsoft/vcpkg/issues/25895#issuecomment-1198909734

So for our policy, I closed it after two weeks without feedback.

**Comment by LegalizeAdulthood** [comment]
gcc and ninja work just fine.  The problem is not my system which is a clean WSL setup of ubuntu with gcc installed.

The reason I didn't bother replying is because it sounds like you're just throwing out questions to me without bothering to try and reproduce it yourself with the information I reported.

Did you try what I reported in the steps to reproduce?  Not starting with an existing WSL, but installing WSL fresh from scratch?  You're always eager to close things when I don't answer your question in a manner that you consider prompt enough for you, but I never see any indication in your comments that you tried what I reported and weren't able to reproduce, it's just "oh you must have a crap environment and it's something wrong with your setup" (my paraphrasing).

**Comment by FrankXie05** [comment]
@LegalizeAdulthood 
![image](https://user-images.githubusercontent.com/65999885/183584412-c7dc4285-3390-41a2-99a5-2a48a2a965e6.png)

Sorry, I didn't reproduce your problem. Apparently according to what you said https://github.com/microsoft/vcpkg/issues/25895#issuecomment-1190504489, the permission problem still appears after you delete the port. Please use admin privileges and try again.

**Comment by LegalizeAdulthood** [comment]
> please use admin privileges and try again

Never before while doing anything with vcpkg have I needed admin privileges.  Are you **guessing** that this is the problem or are you **certain** that this is the problem?  Were you running as a regular user or admin in WSL?

**Comment by FrankXie05** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.

**Comment by LegalizeAdulthood** [comment]
You didn't answer my question:

Are you **guessing** that admin privileges are needed or are you **certain** that admin privileges are needed?

**Comment by LegalizeAdulthood** [comment]
You keep closing all my issues because "information wasn't provided" yet you provide very little information about what you are doing to attempt to reproduce my issues and you don't answer my questions when I ask what you're doing to reproduce the problem.

You are behaving as if you are being measured by management based on the number of open bugs and you are rushing to close them as soon as you possibly can, all while doing as little as possible to determine their causes.

This is not the way the issues should be run for an open source project, IMO.  There's no penalty for leaving an issue open.

**Comment by sfhacker** [comment]
I suspect one of the issues here is what I call: 'language barrier'.
Another issue seems to be lack of experience or very poor/basic troubleshooting skills.
For example, issues about the same port (e.g. OpenSSL) appear dozen times! It seems issues are never (completely) fixed!

@LegalizeAdulthood I understand your frustration. Many users have walked away from this product.
Anyway, I will try to reproduce your issue locally. We use Windows here but I will have a go at it anyway.

**Comment by LegalizeAdulthood** [comment]
To reproduce the problem you have to use a fresh install of WSL on Windows, e.g. not an existing WSL install with a bunch of packages already installed.

**Comment by sfhacker** [comment]
Just built rapidjson from source on Windows 10 x64. No issues at all!

![image](https://user-images.githubusercontent.com/25817529/192078986-67ed41c7-5a0f-4adb-b9af-87ab49018eb7.png)

I haven't built comicsdb, but I could do so should the need arise.

**Comment by sfhacker** [comment]
Any news/update on this 'bizarre' open issue?

**Comment by JonLiu1993** [comment]
@LegalizeAdulthood, does the issue still occur?
