### ISSUE TITLE
vcpkg.io says pistache is available on all platforms, but it's linux only

### ISSUE THREAD

**Issue by LegalizeAdulthood** [microsoft/vcpkg#25896]
**Describe the bug**

**Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
1. ./vcpkg install xxxx
2. See error
Repro code when

**Expected behavior**

**Failure logs**
-(please attached failure logs)

**Additional context**

**Comment by JackBoosY** [comment]
Please report this issue to https://github.com/vcpkg/vcpkg.github.io/issues instead.
Thanks.
