### ISSUE TITLE
[tiff] Building package fails when OpenGL is available

### ISSUE THREAD

**Issue by Morten242** [Microsoft/vcpkg#259]
``  Package: tiff:x86-windows
  Vcpkg version: 0.0.50-e745e3f8552f94554337b8535de9f5233dfc5d15``

Fails because one of its tools requires unistd.h:

``  D:\path\to\vcpkg\buildtrees\tiff\src\tiff-4.0.6\tools\tiffgt.c(32): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory [D:\path\to\vcpkg\buildtrees\tiff\x86-windows-rel\tools\tiffgt.vcxproj]``

This tool only gets built if opengl is available. (tiff-4.0.6/tools/CmakeLists.txt:126)

Edit: if the solution to this is to patch it, then it'd be nice if an option was added to disable building executables.

**Comment by ras0219-msft** [comment]
Thanks for reporting this, I disabled building all nonessential components.
