### ISSUE TITLE
[triton] Build error

### ISSUE THREAD

**Issue by KaiTang2** [microsoft/vcpkg#25902]
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/9157632/install-x64-windows-dbg-out.log)
**Host Environment**
- OS: win11 x64
- Compiler: revision

**To Reproduce**
`./vcpkg install triton triton:x64-windows`

**Failure logs**
Installing 4/6 triton:x64-windows...
Building triton[core]:x64-windows...
-- Downloading https://github.com/JonathanSalwan/Triton/archive/243026c9c1e07a5ca834c4aaf628d1079f6a85ea.tar.gz -> JonathanSalwan-Triton-243026c9c1e07a5ca834c4aaf628d1079f6a85ea.tar.gz...
-- Extracting source E:/GitHub/vcpkg/downloads/JonathanSalwan-Triton-243026c9c1e07a5ca834c4aaf628d1079f6a85ea.tar.gz
-- Applying patch 001-fix-dependency-z3.patch
-- Applying patch 002-fix-capstone-5.patch
-- Applying patch 003-fix-python.patch
-- Using source at E:/GitHub/vcpkg/buildtrees/triton/src/079f6a85ea-4848cd5073.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j21
    Working Directory: E:/GitHub/vcpkg/buildtrees/triton/x64-windows-dbg
    See logs for more information:
      E:\GitHub\vcpkg\buildtrees\triton\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/triton/portfile.cmake:41 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

 vcpkg-tool version: 2022-07-14-fb7e3b1bb3b1ca185fffe2be36b2fbc53198360f
    vcpkg-scripts version: 8ff168270 2022-07-19 (33 hours ago)

**Comment by LilyWangLL** [comment]
Please provide the error log: **E:\GitHub\vcpkg\buildtrees\triton\install-x64-windows-dbg-out.log**

**Comment by KaiTang2** [comment]
@LilyWangLL done

**Comment by JackBoosY** [comment]
```
E:\GitHub\vcpkg\buildtrees\triton\src\079f6a85ea-4848cd5073.clean\src\libtriton\includes\triton/tritonTypes.hpp(17): fatal error C1083: Cannot open include file: 'boost/multiprecision/cpp_int.hpp': No such file or directory
```
Can you please remove `boost-uninstall boost-uninstall:x64-windows` then try again?

Thanks.

**Comment by KaiTang2** [comment]
> 

I tried, but I still have this problem

**Comment by JackBoosY** [comment]
You may need to clone a new vcpkg and try again.

**Comment by KaiTang2** [comment]
@JackBoosY  I update to vcpkg-tool version: 2022-07-14-fb7e3b1bb3b1ca185fffe2be36b2fbc53198360f
    vcpkg-scripts version: b2a22ff59 2022-07-20 (11 hours ago), it still have this problem

**Comment by JackBoosY** [comment]
> @JackBoosY I update to vcpkg-tool version: 2022-07-14-fb7e3b1bb3b1ca185fffe2be36b2fbc53198360f vcpkg-scripts version: [b2a22ff](https://github.com/microsoft/vcpkg/commit/b2a22ff59ab523788a26980f7d38a4e5d4fedb8f) 2022-07-20 (11 hours ago), it still have this problem

You should use command `./vcpkg upgrade`.
Or you should remove `boost-build boost-modular-build-helper boost-build:x64-windows boost-modular-build-helper:x64-windows`.

**Comment by KaiTang2** [comment]
> 

I've tried both methods, but it's the same mistake
