### ISSUE TITLE
[imgui] metal C++ binding can't be linked against

### ISSUE THREAD

**Issue by Raildex** [microsoft/vcpkg#25906]
**Describe the bug**
The C++ Metal Binding for ImGui can't be linked against.
It looks like the Metal Binding is not built with `IMGUI_IMPL_METAL_CPP`

**Environment**
- OS: Mac OSX 12.4
- Compiler: Clang

**To Reproduce**
```
vcpkg install imgui[metal-binding,osx-binding,glfw-binding]
```
```
find_package(imgui CONFIG REQUIRED)
target_link_libraries(Runtime PRIVATE imgui::imgui)
target_include_directories(Runtime PRIVATE ${IMGUI_INCLUDE_DIRS})
```
```
target_compile_definitions(Runtime PRIVATE IMGUI_IMPL_METAL_CPP)
```
**Failure logs**
```
[build] Undefined symbols for architecture x86_64:
[build]   "ImGui_ImplMetal_NewFrame(MTL::RenderPassDescriptor*)", referenced from: [...]
[build]   "ImGui_ImplMetal_RenderDrawData(ImDrawData*, MTL::CommandBuffer*, MTL::RenderCommandEncoder*)", referenced from: [...]
[build] ld: symbol(s) not found for architecture x86_64
```

**Comment by JackBoosY** [comment]
Function `ImGui_ImplMetal_NewFrame` is declared in https://github.com/ocornut/imgui/blob/master/backends/imgui_impl_metal.h with 2 simlar mode:
```cpp
...
#ifdef __OBJC__
IMGUI_IMPL_API void ImGui_ImplMetal_NewFrame(MTLRenderPassDescriptor* renderPassDescriptor);
...
#endif
...
#ifdef IMGUI_IMPL_METAL_CPP
#include <Metal/Metal.hpp>
#ifndef __OBJC__
...
IMGUI_IMPL_API void ImGui_ImplMetal_NewFrame(MTL::RenderPassDescriptor* renderPassDescriptor);
...
#endif
#endif
```

**Comment by JackBoosY** [comment]
So `IMGUI_IMPL_METAL_CPP` has conflict with `__OBJC__` which related to build `.mm` file. Right?

**Comment by Raildex** [comment]
I am not sure. To me it looks like the vcpkg port is compiled without the CPP define

**Comment by JackBoosY** [comment]
@ocornut Needs some help here.

**Comment by ocornut** [comment]
Hello,
Can't really help myself.
I am not very well acquainted with Mac infrastructure even less so about this ObjC/C++ shenanigans.

**Comment by JackBoosY** [comment]
We need to understand the source code before we fix this issue.

**Comment by Raildex** [comment]
The port needs to compile the files with a Cpp compiler and a ObjC compiler separately I guess

**Comment by JackBoosY** [comment]
Hi @ocornut , do you know who contribute these related code?

**Comment by ocornut** [comment]
@warrenm and @o-micron might know but lacking details i’m not sure its a problem on our end. If you have a linking error without specifying exact compile/linking params it is difficult to help.

The backend can indeed be built both for ObjC and C++, I don’t know how this handled in term of vcpkg but i imagine it should be an option.

**Comment by o-micron** [comment]
Metal-cpp is a header only library, so we need to add these definitions to generate the implementation in a cpp file
```Cpp
#define NS_PRIVATE_IMPLEMENTATION
#define CA_PRIVATE_IMPLEMENTATION
#define MTL_PRIVATE_IMPLEMENTATION
#include <Foundation/Foundation.hpp>
#include <Metal/Metal.hpp>
#include <QuartzCore/QuartzCore.hpp>
```

**Comment by o-micron** [comment]
Sorry for last comment I thought the linking errors were related to Metal-cpp ..
I think yes if we build the current metal backend (objc), we need to define `IMGUI_IMPL_METAL_CPP ` before building or simply the symbols won't be exported with the library.

**Comment by Raildex** [comment]
Exactly. There are two things in the metal binding:
The Obj-C part which is compiled with an objc-compiler and the C++ part, which is compiled with a C++ compiler and with `IMGUI_IMPL_METAL_CPP`. Both need to be compiled separately.

**Comment by truedat101** [comment]
I'll test this locally, curious myself.
