### ISSUE TITLE
Getting started in the readme part linux part about g++ link errors in the preconditions of linux.

### ISSUE THREAD

**Issue by Sugar0612** [microsoft/vcpkg#25907]
**Describe the bug**
When I tried to learn how to use vcpkg on the linux platform through Readme [Chinese document], I saw the introductory document reminding linux that there are preconditions, one is to have git, the other is to have g++ >= 6, I clicked on git The link is very good to enter the official page of git, but when I clicked the link about g++ in the vcpkg introductory document, I did not enter the g++ document, but re-entered the vcpkg linux introductory document. I repeated several times and found that it was true There is a problem, it should be that the g++ link you gave is wrong. [Chinese document]

**Environment**

linux

**To Reproduce**
[Chinese Overview]->[Getting Started]->[macOS and Linux]->[g++] (There is a problem with the jump here when you click g++)
[中文总览]->[入门]->[macOS 和 Linux]->[g++](There is a problem with the jump here when you click g++)
Repro code when

**Expected behavior**
Should jump to the g++ official website or the g++ jump location like the English document

**Failure logs**
- error: Getting started in the readme part linux part about g++ link errors in the preconditions of linux.
**Additional context**
 no

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. These links will be completed in the future, you can find the method to install g++ and gcc online.
