### ISSUE TITLE
A build error occurs when installing curl with vcpkg.

### ISSUE THREAD

**Issue by Sugar0612** [microsoft/vcpkg#25929]
**Describe the bug**
I went through the curl documentation and found that I need to download the latest version of the curl file through vcpkg, and then I did the same. Then when I executed the "vcpkg install curl[tool]" command, an error occurred:

error: building openssl:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openssl]+Build+error
Include '[openssl] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-07-14-fb7e3b1bb3b1ca185fffe2be36b2fbc53198360f
    vcpkg-scripts version: b2a22ff59 2022-07-20 (2 天前)

You can also use the prefilled template from /home/uwa/ossSdkThird/vcpkg/installed/vcpkg/issue_body.md.

**Environment**

Linux

**To Reproduce**

1. git clone https://github.com/Microsoft/vcpkg.git
2. cd vcpkg
3. ./bootstrap-vcpkg.sh
4. ./vcpkg integrate install
5. vcpkg install curl[tool] (Error at this step,there will be the above error)

**Expected behavior**
build error

**Failure logs**
-(please attached failure logs)

**Additional context**
https://curl.se/docs/install.html

**Comment by autoantwort** [comment]
> You can also use the prefilled template from /home/uwa/ossSdkThird/vcpkg/installed/vcpkg/issue_body.md.

Please use it :)

**Comment by FrankXie05** [comment]
@Sugar0612 Make sure you download the latest `linux-headers` and please provide the failure log.
