### ISSUE TITLE
[vcpkg] Crash when attempting to upgrade not installed packages

### ISSUE THREAD

**Issue by CookiePLMonster** [microsoft/vcpkg#25948]
EDIT: The link Vcpkg provided for reporting this issue implied that I'd get this issue labeled with `category:vcpkg-bug`, however this didn't seem to have happened.

**Describe the bug**
Vcpkg reports a crash when attempting to upgrade a package that is either not installed or does not exist, as per the repro steps below.

**Environment**
- OS: Windows 10 21H1
- Compiler: Visual Studio 2022
- Vcpkg version (output of `./vcpkg version`): `vcpkg package management program version 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22`

**To Reproduce**
Steps to reproduce the behavior. These steps assume that package `foo` does not exist.
1. `./vcpkg upgrade foo:x86-windows`
2. Vcpkg reports failure, **and** crashes with an error: `internal error: D:\a\_work\1\s\src\vcpkg\commands.upgrade.cpp(189): vcpkg has crashed; no additional details are available.`

The same reproduction steps apply if the package in question is valid, but not installed.

**Expected behavior**
Vcpkg reports failure, as it does now, without crashing.

**Failure logs**
None pointed to by Vcpkg during the crash.

**Comment by LilyWangLL** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/21117.
