### ISSUE TITLE
MKL port ?

### ISSUE THREAD

**Issue by vlj** [Microsoft/vcpkg#2594]
I'm trying to add some ML Framework to vcpkg. Most of them allow to select the underlying matrix Library : atlas, openblas or Intel MKL.

I think it would make sense to have a "fake" MKL port like Cuda's one since there's no source available : the port will only check that the lib is installed and export the location.

**Comment by ras0219-msft** [comment]
This seems reasonable, though I'd probably call it `intel-mkl` just to be clearer.

**Comment by zhihaoy** [comment]
Close this?
