### ISSUE TITLE
[cpr] undefined reference to cpr::Session after linking

### ISSUE THREAD

**Issue by coding-famer** [microsoft/vcpkg#25940]
When I install libcpr and use it, I got 
```
In function `cpr::Response cpr::Get<cpr::Url>(cpr::Url&&)':
..... : undefined reference to `cpr::Session::~Session()'
```
I think there may be something wrong in this port.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Could you please provide the repro codes or sample project which can reproduce this issue?

**Comment by coding-famer** [comment]
Hi, I meet this problem when I configured the environment of [cs106L-assignment1](https://github.com/snme/cs106L-assignment1)

**Comment by coding-famer** [comment]
And many people meet this problem https://github.com/snme/cs106L-assignment1/issues/3

**Comment by MonicaLiu0311** [comment]
Sorry for being late.

Investigation found that [snme/cs106L-assignment1#3](https://github.com/snme/cs106L-assignment1/issues/3) has been resolved by https://github.com/snme/cs106L-assignment1/pull/4.

And I found [similar issues upstream](https://github.com/libcpr/cpr/issues/689) , has also been resolved.

Currently the `cpr` in `vcpkg` has been updated to 1.9.3.

So, I will close this issue, if it is still an issue, please reopen it.
