### ISSUE TITLE
Undefined reference to pcre2 with qtbase and gdal in combination

### ISSUE THREAD

**Issue by m-kuhn** [microsoft/vcpkg#25941]
**Describe the bug**
When creating an application that links against qtbase and gdal, the resulting library failed to link with undefined reference to pcre symbols.

My understanding of the problem:

Both, qt and gdal cache the library in `PCRE2_LIBRARY`, but link against different versions of it:

- gdal `libpcre2-8.a`
- qt `libpcre2-16.a`

This leads to a race condition where the package that is found first will define which flavor of the pcre2 library is used, symbols from the second one are missing.

**Environment**
- OS: Linux (Fedora 35), MinGW, others untested
- Compiler: gcc12.1.1

**To Reproduce**
Create an application that links against `gdal` and `qtbase`.
Build and link.

**Expected behavior**
No linker errors

**Failure logs**
```
ogrsqlitevirtualogr.cpp:(.text+0xabd): undefined reference to `pcre2_compile_8'
/usr/bin/ld: ogrsqlitevirtualogr.cpp:(.text+0xad8): undefined reference to `pcre2_config_8'
/usr/bin/ld: ogrsqlitevirtualogr.cpp:(.text+0xb03): undefined reference to `pcre2_code_free_8'
/usr/bin/ld: ogrsqlitevirtualogr.cpp:(.text+0xb86): undefined reference to `pcre2_jit_compile_8'
/usr/bin/ld: ogrsqlitevirtualogr.cpp:(.text+0xba6): undefined reference to `pcre2_get_error_message_8'
/usr/bin/ld: ogrsqlitevirtualogr.cpp:(.text+0xbdf): undefined reference to `pcre2_code_free_8'
/usr/bin/ld: ogrsqlitevirtualogr.cpp:(.text+0xbfa): undefined reference to `pcre2_get_error_message_8'
/usr/bin/ld: vcpkg_installed/x64-linux/lib/libgdal.a(ogrsqlitevirtualogr.cpp.o): in function `OGRSQLiteREGEXPFunction(sqlite3_context*, int, sqlite3_value**)':
ogrsqlitevirtualogr.cpp:(.text+0xcac): undefined reference to `pcre2_match_data_create_from_pattern_8'
/usr/bin/ld: ogrsqlitevirtualogr.cpp:(.text+0xcdd): undefined reference to `pcre2_match_8'
/usr/bin/ld: vcpkg_installed/x64-linux/lib/libgdal.a(ogrsqlitevirtualogr.cpp.o): in function `OGRSQLiteExtensionData::~OGRSQLiteExtensionData()':
ogrsqlitevirtualogr.cpp:(.text+0x32ee): undefined reference to `pcre2_code_free_8'
```

**Possible solutions**

- Link gdal against pcre2-16
- Rename the variable names to `PCRE2-8_LIBRARY` and `PCRE2-16_LIBRARY` or similar

CC @Neumann-A @dg0yt

**Comment by dg0yt** [comment]
Both upstreams should rename the variables. To avoid clashes with packages you didn't find yet.

**Comment by m-kuhn** [comment]
https://github.com/OSGeo/gdal/pull/6116

**Comment by Neumann-A** [comment]
I think we can safely rename the variables in qtbase to `PCRE2_16_LIBRARY_RELEASE`. qt will use the target `WrapSystemPCRE2::WrapSystemPCRE2` any way.

**Comment by Neumann-A** [comment]
Also upstream of pcre2 has targets already?

https://github.com/qt/qtbase/blob/a1ca0c99deef5fcacb05d004ce69025886a220a4/cmake/FindWrapSystemPCRE2.cmake#L9-L12

**Comment by m-kuhn** [comment]
So ideally both upstreams would link the PCRE2 upstream target properly if I understand correctly?

In this case, is there somewhere a good template/reference implementation for a Find module that looks for an existing config target first with fallback logic to pkg-config?

**Comment by dg0yt** [comment]
If pcre2 in vcpkg provides config with targets, then we might direct gdal to use this (similar to what is done for netcdf), and remove the find module from the gdal sources so that it doesn't end up in the installed package.

**Comment by dg0yt** [comment]
This doesn't matter for vcpkg.

**Comment by m-kuhn** [comment]
It does matter for an upstream PR as proposed above.

**Comment by m-kuhn** [comment]
Update, the upstream PR on GDAL has been merged (and is being backported to 3.5), so the issue will be fixed with the next update.
I'd still be interested in knowing potential better ways to handle cases like this (in vcpkg and upstream).

**Comment by dg0yt** [comment]
> is there somewhere a good template/reference implementation for a Find module that looks for an existing config target first with fallback logic to pkg-config?

No. Probably it is just too hard to do it right across configs and platforms, so there are many bad examples: 
- Official `FindCURL.cmake` (from Kitware). Loads config, but breaks the traditional variables API. (Opt-out available.)
- Official `FindExpat.cmake` (from Kitware). Loads pkg-config only to discover the root path, but doesn't reuse the other information (in particular library names).
- Official `FindPkgConfig.cmake` (from Kitware). Should provide variables and targets as needed, but actually fails to properly deal with libraries which are given with full path. 

And you don't want implicit nested search. Because it makes it harder to define an explicit serial search order (as a project maintainer), or to use standard CMake parameters to change the search process (as a project user).

GDAL's utility function for package lookup is quite good with regard to configuration options (as we use for netcdf) and in generating corresponding `find_dependency`. Well, we provided input and testing.

**Comment by O-Tom** [comment]
Hi,I ran into exactly this problem using the latest release (https://github.com/microsoft/vcpkg/releases/tag/2024.08.23)
Under linux/gcc at link time, pcre2 symbols consumed by qtbase are reported undefined. On the same project, under windows, there is no problem.
In the gcc/linux log, these lines in particular catch my eye:
```
-- Found PCRE2: /builds/xxx/_build_/vcpkg_installed/x64-linux/lib/libpcre2-8.a (found version "10.43") 
-- Found WrapSystemPCRE2: optimized;/builds/xxx/_build_/vcpkg_installed/x64-linux/lib/libpcre2-8.a;debug;/builds/xxx/_build_/vcpkg_installed/x64-linux/lib/libpcre2-16.a (found version "10.43") 
-- Using system PCRE2.
-- Found WrapPCRE2: TRUE  
```
The _8 variant of the library is selected by default and I see that the _16/release version appears in the debug targets.

Has the problem reappeared recently, or had no solution or workaround been found ?
