### ISSUE TITLE
[eastl] Add natvis file

### ISSUE THREAD

**Issue by SamVanheer** [microsoft/vcpkg#25944]
****

**Is your feature request related to a problem? Please describe.**
EASTL provides a `.natvis` file to visualize the contents of containers when debugging with Visual Studio. This file is not included in the vcpkg port.

**Proposed solution**
Add the file to the vcpkg port. Found here: https://github.com/electronicarts/EASTL/blob/ae8cc01d8844dab8240d0e05bb29727e7910db63/doc/EASTL.natvis

**Describe alternatives you've considered**
The EASTL documentation says to add this file manually, but this only applies when not using vcpkg. When using vcpkg the file's location is not known to the user.

**Additional context**
See the EASTL documentation on CMake setup here: https://github.com/electronicarts/EASTL/blob/fad54717f8e4ebb13b20095da7efd07a53af0f10/doc/CMake/EASTL_Project_Integration.md

**Comment by Adela0814** [comment]
Users can find the source code downloaded using vcpkg at `\vcpkg\buildtrees\eastl`. You can also add [EASTL.natvis](https://github.com/electronicarts/EASTL/blob/ae8cc01d8844dab8240d0e05bb29727e7910db63/doc/EASTL.natvis) manually following the documentation.

**Comment by SamVanheer** [comment]
The path to the file in my copy is `vcpkg\buildtrees\eastl\src\5ab9f1222a-d1a090d24e.clean\doc\EASTL.natvis`.

The `.clean` directory name seems to include the vcpkg commit hash. Is there any way to locate this directory without hard-coding it?

I can't find any information about locating the downloaded source code in the documentation. Some way to get this path, perhaps using a CMake function or variable would make this a lot easier.

**Comment by SamVanheer** [comment]
@Adela0814 is there a way to get the path to the port's root directory in a `CMakeLists.txt` file? I couldn't find this information in the documentation.

**Comment by Adela0814** [comment]
`CMAKE_CURRENT_LIST_DIR` is your current port path. `CMAKE_CURRENT_BINARY_DIR` is your binary path. you can use these variables in your CMakeLists.txt.

**Comment by SamVanheer** [comment]
You misunderstand. I'm trying to get the path to the file from my own project that's including EASTL using vcpkg.

This is the directory setup i'm dealing with:
* `repository root/CMakeLists.txt`
* `repository root/vcpkg/buildtrees/eastl/src/5ab9f1222a-d1a090d24e.clean/doc/EASTL.natvis`

I'm trying to get the path to that file from my project's root `CMakeLists.txt`.

As far as i can tell there are no variables or functions to get that path. Do i have to make a custom port to do this or is there some other way to get this path?

**Comment by Adela0814** [comment]
I'm so sorry. In fact, you can only use the files in the `vcpkg/installed` directory in your own project. If you really need to use EASTL.natvis, please open an issue upstream, they need to add some commands to install EASTL.natvis for external use.

**Comment by SamVanheer** [comment]
I've created 2 pull requests to improve EASTL install support:
https://github.com/electronicarts/EASTL/pull/486
https://github.com/electronicarts/EASTL/pull/487

I suspect more changes are required (e.g. a config file for CMake CONFIG mode) but this will at least add the file in a location that can be linked to.

Vcpkg already has the work done so maybe that should be made into pull requests on the original repository.
