### ISSUE TITLE
[openssl] Build error

### ISSUE THREAD

**Issue by srsec** [microsoft/vcpkg#25955]
**Host Environment**
- OS: [Windows 11 Home]
- Compiler: revision

**To Reproduce**
`./vcpkg install openssl

**Failure logs**
"C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe"  /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -MP  -MD -O2 -Oi -Gy -DNDEBUG   -FS -I"." -I"include" -I"apps\include" -D"L_ENDIAN" -D"OPENSSL_PIC" -D"OPENSSLDIR=\"E:\\rat\\Khepri\\vcpkg\\packages\\openssl_x64-windows\"" -D"ENGINESDIR=\"E:\\rat\\Khepri\\vcpkg\\packages\\openssl_x64-windows\\lib\\engines-3\"" -D"MODULESDIR=\"E:\\rat\\Khepri\\vcpkg\\packages\\openssl_x64-windows\\lib\\ossl-modules\"" -D"OPENSSL_BUILDING_OPENSSL" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"NDEBUG"   -c /Foapps\lib\libapps-lib-app_libctx.obj "apps\lib\app_libctx.c"
app_libctx.c
cl : Command line error D8050 : cannot execute 'C:\Program Files (x86)\Microsoft Visual **Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\c1.dll': failed to get command line into debug records**

**Additional context**
![image](https://user-images.githubusercontent.com/50904323/180658207-bd9bf0ff-41a3-45dc-a27a-3fad8d18c50b.png)
Thinks.

**Comment by Adela0814** [comment]
Can you please repair your Visual Studio using Visual Studio installer then try again?

**Comment by Adela0814** [comment]
@srsec ping~

**Comment by Adela0814** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
