### ISSUE TITLE
[cpprestsdk] Cannot find dynamic library dependencies at runtime

### ISSUE THREAD

**Issue by klalumiere** [microsoft/vcpkg#25978]
**Describe the bug**
On Linux, `cpprestsdk` cannot find its dynamic libraries dependencies at runtime, like `libboost_random.so.1.79.0`.

**Environment**
- OS: Linux
- Compiler: clang version 10.0.0-4ubuntu1

**To Reproduce**
1. Add a dependency on `qpid-proton` in `vcpkg.json`:
    ```json
            {
                "name": "cpprestsdk",
                "version>=": "2.10.18#1"
            }
    ```
1. Link on it.
1. Compile it with the triplet [x64-linux-dynamic](https://github.com/microsoft/vcpkg/blob/master/docs/examples/overlay-triplets-linux-dynamic.md) and run your program. At runtime, you'll see an error looking like `error while loading shared libraries: libboost_random.so.1.79.0: cannot open shared object file: No such file or directory`. You can use `lddtree` to confirm that the transitive dependency missing comes from `cpprestsdk`.

**Expected behavior**
No runtime error.

**Failure logs**
`error while loading shared libraries: libboost_random.so.1.79.0: cannot open shared object file: No such file or directory`

**Additional context**
It's a `RUNPATH` (`RPATH`) problem. I'll open a pull request in a few seconds.

**Comment by Osyotr** [comment]
https://github.com/microsoft/vcpkg/pull/23035 is merged, so the linked doc is outdated. Please update your vcpkg instance and use `VCPKG_FIXUP_ELF_RPATH` flag

**Comment by klalumiere** [comment]
This work. Thanks a lot! :smiley:

**Comment by klalumiere** [comment]
This work. Thanks a lot! :smiley:
