### ISSUE TITLE
[libzip] exported dll function "struct zip_t zip_open(const char*, int, int*)" points to wrong definition "struct zip_t zip_open(const char*, int, char)"

### ISSUE THREAD

**Issue by beemibrahim** [microsoft/vcpkg#25973]
**Describe the bug**

When I call the function "zip_open()" and debug into it, it opens a wrong definition of it.

The exported declaration is : **struct zip_t zip_open(const char\*, int, int\* )**

The real definition is : **struct zip_t zip_open(const char\*, int, char)**

I don't know what is going on. please fix your **bug**.

**Environment**
- OS: **Windows**
- Compiler: **Visual Studio 2022 v143 x64**

**To Reproduce**
1. **./vcpkg install libzip:x64-windows**

Thats all I know :(

**Expected behavior**

The wrong definition of **zip_open()**

Here is a video : 

[video.zip](https://github.com/microsoft/vcpkg/files/9181597/video.zip)

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. I will test this issue locally.

**Comment by beemibrahim** [comment]
I've actually already fixed this issue. It turns out that I was using two vcpkg libraries that had the same include headers.

These libraries are :

1. `vcpkg install libzip`

2. `vcpkg install kubazip`

Both of these libraries had the header `zip.h`

**Comment by LilyWangLL** [comment]
Yes, there two ports both have `zip.h`, but their include path is different. `kubazip` is `zip/zip.h`, `libzip` is `zip.h`. Since this issue has been resolved, so I am closing this issue for now.
![image](https://user-images.githubusercontent.com/94091114/181147207-cace41d1-c0db-46fc-90d6-aeb6c577f03f.png)
