### ISSUE TITLE
Qt6 pkg-config files not installed

### ISSUE THREAD

**Issue by Be-ing** [microsoft/vcpkg#25988]
**Describe the bug**
The qt (Qt6) package does not install pkg-config files.

**Environment**
- OS: x64-osx
- Compiler: clang 13

**To Reproduce**
```
./vcpkg install qt
```

**Expected behavior**
pkg-config files generated by Qt's build system are installed

**Failure logs**
Contents of pkgconfig directory after installing Qt6:
```
./build/vcpkg_installed/x64-osx/debug/lib/pkgconfig/openssl.pc
./build/vcpkg_installed/x64-osx/debug/lib/pkgconfig/icu-uc.pc
./build/vcpkg_installed/x64-osx/debug/lib/pkgconfig/libpng16.pc
./build/vcpkg_installed/x64-osx/debug/lib/pkgconfig/libjpeg.pc
./build/vcpkg_installed/x64-osx/debug/lib/pkgconfig/libbrotlienc.pc
./build/vcpkg_installed/x64-osx/debug/lib/pkgconfig/libpq.pc
./build/vcpkg_installed/x64-osx/debug/lib/pkgconfig/icu-io.pc
./build/vcpkg_installed/x64-osx/debug/lib/pkgconfig/bzip2.pc
./build/vcpkg_installed/x64-osx/debug/lib/pkgconfig/harfbuzz-subset.pc
./build/vcpkg_installed/x64-osx/debug/lib/pkgconfig/harfbuzz.pc
./build/vcpkg_installed/x64-osx/debug/lib/pkgconfig/freetype2.pc
./build/vcpkg_installed/x64-osx/debug/lib/pkgconfig/libturbojpeg.pc
./build/vcpkg_installed/x64-osx/debug/lib/pkgconfig/zlib.pc
./build/vcpkg_installed/x64-osx/debug/lib/pkgconfig/libzstd.pc
./build/vcpkg_installed/x64-osx/debug/lib/pkgconfig/libssl.pc
./build/vcpkg_installed/x64-osx/debug/lib/pkgconfig/libbrotlicommon.pc
./build/vcpkg_installed/x64-osx/debug/lib/pkgconfig/icu-i18n.pc
./build/vcpkg_installed/x64-osx/debug/lib/pkgconfig/libcrypto.pc
./build/vcpkg_installed/x64-osx/debug/lib/pkgconfig/libbrotlidec.pc
./build/vcpkg_installed/x64-osx/debug/lib/pkgconfig/sqlite3.pc
./build/vcpkg_installed/x64-osx/debug/lib/pkgconfig/libpcre2-posix.pc
./build/vcpkg_installed/x64-osx/debug/lib/pkgconfig/libpcre2-8.pc
./build/vcpkg_installed/x64-osx/debug/lib/pkgconfig/libpcre2-16.pc
./build/vcpkg_installed/x64-osx/debug/lib/pkgconfig/libpcre2-32.pc
./build/vcpkg_installed/x64-osx/debug/lib/pkgconfig/libb2.pc
./build/vcpkg_installed/x64-osx/debug/lib/pkgconfig/libpng.pc
```

**Additional context**
I am working on getting Cargo to link Qt from vcpkg. qmake can tell me the paths of the Qt installation, however, I don't think it can show me the transitive dependencies needed for statically linking Qt. So I am [using pkg-config](https://github.com/KDAB/cxx-qt/blob/841c4e04e7271de74a7d917e3ab8fc2980eadcb9/qt-build/src/lib.rs#L162), but the Qt6 packages do not install pkg-config files. If you look at the file list for the [qt6-base package for Arch Linux](https://archlinux.org/packages/extra/x86_64/qt6-base/) you can see that Qt's build system can generate pkg-config files (I also noticed Fedora's and Ubuntu's Qt6 packages do not ship pkg-config files, sigh).

**Comment by FrankXie05** [comment]
cc @Neumann-A

**Comment by Be-ing** [comment]
Unfortunately it looks like this [isn't supported upstream with static linking](https://codereview.qt-project.org/gitweb?p=qt/qtbase.git;a=commitdiff;h=5b07f14a4ff6b08887473b1b583ee2f71dec6f76). From the commit message:

> Although it has some limitations, with qt_internal_add_qml_module if
it specifies non-public deps these won't be listed and with non-Qt
requirements, notably in static builds, not being appended to the
PkgConfig file.

and in the code:

```
    if(NOT BUILD_SHARED_LIBS)
        return()
    endif()
```

**Comment by Be-ing** [comment]
It turns out this was not implemented upstream until recently. https://codereview.qt-project.org/c/qt/qtbase/+/405678 was merged to the Qt 6.3 branch 2022-04-12. According to https://wiki.qt.io/Qt_6.3_Release Qt 6.3.0 was released 2022-04-12 and Qt 6.3.1 was released 2022-06-14, so pkgconfig file generation was first added in Qt 6.3.1. So I think the Qt6 packages need to be updated to resolve this, although that will only resolve it for dynamic linking on Linux and macOS.

**Comment by Be-ing** [comment]
vcpkg already has Qt 6.3.1 as of #25259, however I do not see any `vcpkg_fixup_pkgconfig` calls in the Qt6 packaging scripts.

**Comment by Neumann-A** [comment]
Upstream issue? ;) I mean I can add the `vcpkg_fixup_pkgconfig()` in the next update but it won't fix what upstream isn't installing. In general you could try to use the qmake *.prl files to figure out what you require for linking.

**Comment by dg0yt** [comment]
Now with dynamic community triplets, handling `vcpkg_fixup_pkgconfig` would be beneficial even without additional polyfill for static triplets.

**Comment by Neumann-A** [comment]
> Now with dynamic community triplets, handling vcpkg_fixup_pkgconfig would be beneficial even without additional polyfill for static triplets.

Wasn't a thing at the time. If I remember correctly I tried to activate pc file generation for everything but Qt was exporting so much incorrect trash that I decided to wait for upstream to fix it.

**Comment by Be-ing** [comment]
> In general you could try to use the qmake *.prl files to figure out what you require for linking.

Oh, I didn't know about these. Is there a way to qmake to read a specific file and output a variable from it, maybe somehow with `qmake -query`? Or would I need to read the file and process the text myself?

**Comment by Neumann-A** [comment]
> Oh, I didn't know about these. Is there a way to ask qmake to read a specific file and output a variable from it, maybe somehow with qmake -query? Or would I need to read the file and process the text myself?

In Qt5 the prl files were/are manually parsed to create the cmake configs and populate the targets. So I would assume there is no way to ask qmake for the info because otherwise they would have used it(?)

**Comment by Be-ing** [comment]
It turns out that parsing the .qrl files was quite simple with this regex `^QMAKE_PRL_LIBS = (.*)$` then finding and replacing `$$[QT_INSTALL_PREFIX]` with the result of `qmake -query QT_INSTALL_PREFIX`. This is nice because I don't have to rely on pkg-config being installed. So my immediate issue is resolved, but the pkgconfig files should still be shipped when updating to 6.3.1.

**Comment by FrankXie05** [comment]
@Be-ing  Does the issue still occur?

**Comment by Be-ing** [comment]
AFAIK nothing has been done to fix this yet.

**Comment by Cheney-W** [comment]
@Be-ing Qt6 has been updated to 6.4.2, could you please confirm whether this issue is solved? Thank you!

**Comment by dg0yt** [comment]
> could you please confirm whether this issue is solved?

We only need to check the CI file lists: The issue is not resolved. And it is causing doing good ports downstream, cf. https://github.com/microsoft/vcpkg/pull/29615#issuecomment-1429168967.

**Comment by Be-ing** [comment]
The issue has been fixed upstream. Fedora's qt6-qtcore-devel package ships these files:

/usr/lib64/pkgconfig/Qt6.pc
/usr/lib64/pkgconfig/Qt6Concurrent.pc
/usr/lib64/pkgconfig/Qt6Core.pc
/usr/lib64/pkgconfig/Qt6DBus.pc
/usr/lib64/pkgconfig/Qt6Gui.pc
/usr/lib64/pkgconfig/Qt6Network.pc
/usr/lib64/pkgconfig/Qt6OpenGL.pc
/usr/lib64/pkgconfig/Qt6OpenGLWidgets.pc
/usr/lib64/pkgconfig/Qt6Platform.pc
/usr/lib64/pkgconfig/Qt6PrintSupport.pc
/usr/lib64/pkgconfig/Qt6Sql.pc
/usr/lib64/pkgconfig/Qt6Test.pc
/usr/lib64/pkgconfig/Qt6Widgets.pc
/usr/lib64/pkgconfig/Qt6Xml.pc

So at this point it's a bug in the vcpkg port that those files don't get installed.

**Comment by Neumann-A** [comment]
```
# Create a Qt6*.pc file intended for pkg-config consumption.
function(qt_internal_generate_pkg_config_file module)
    # TODO: PkgConfig is supported under MSVC with pkgconf (github.com/pkgconf/pkgconf)
    if((NOT UNIX OR QT_FEATURE_framework) AND NOT MINGW OR CMAKE_VERSION VERSION_LESS "3.20")
        return()
    endif()
    if(NOT BUILD_SHARED_LIBS)
        return()
    endif()
```
Not a vcpkg bug not fixed by upstream. Qt6 in vcpkg on linux is static....

**Comment by MehdiChinoune** [comment]
I got an error when building quazip against Qt6 in #30345 
```
-- Fixing pkgconfig file: /Users/vagrant/Data/packages/quazip_x64-osx/lib/pkgconfig/quazip1-qt6.pc
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:141 (message):
  /usr/local/bin/pkg-config --exists quazip1-qt6 failed with error code: 1

      ENV{PKG_CONFIG_PATH}: "/Users/vagrant/Data/packages/quazip_x64-osx/lib/pkgconfig:/Users/vagrant/Data/packages/quazip_x64-osx/share/pkgconfig:/Users/vagrant/Data/installed/x64-osx/lib/pkgconfig:/Users/vagrant/Data/installed/x64-osx/share/pkgconfig"
      output: Package Qt6Core was not found in the pkg-config search path.

  Perhaps you should add the directory containing `Qt6Core.pc'

  to the PKG_CONFIG_PATH environment variable

  Package 'Qt6Core', required by 'quazip1-qt6', not found
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:206 (z_vcpkg_fixup_pkgconfig_check_files)
  ports/quazip/portfile.cmake:27 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:147 (include)


error: building quazip:x64-osx failed with: BUILD_FAILED
```
