### ISSUE TITLE
error: in triplet x64-windows: Unable to find a valid Visual Studio instance

### ISSUE THREAD

**Issue by Lishen1** [microsoft/vcpkg#25986]
**Describe the bug**
[DEBUG] CreateProcessW("C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease -legacy -products * -format xml)
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 2648: cmd_execute_and_stream_data() returned 0 after    23124 us
error: in triplet x64-windows: Unable to find a valid Visual Studio instance
    at "C:/Program Files/Microsoft Visual Studio/2022/Preview"
The following Visual Studio instances were considered:
    C:\Program Files\Microsoft Visual Studio\2022\Preview
    C:\Program Files\Microsoft Visual Studio\2022\Preview
The following paths were examined for Visual Studio instances:
    C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Auxiliary/Build\vcvarsall.bat
    C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools/MSVC\14.33.31627\bin/HostX86/x86\dumpbin.exe
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC/vcvarsall.bat

paths is valid

**Environment**
- OS: win 11
- Compiler: visual studio 2022

**Comment by Adela0814** [comment]
@Lishen1 Please provide the reproduce steps and full failure logs.

**Comment by Lishen1** [comment]
steps to  reproduce
./vcpkg install opencv3:x64-windows --debug

log:

```
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Failed to open: D:\dev\vcpkg\vcpkg-bundle.json
[DEBUG] Using scripts-root: D:\dev\vcpkg\scripts
[DEBUG] Bundle config: readonly=0, usegitregistry=0, embeddedsha=nullopt
[DEBUG] Using builtin-ports: D:\dev\vcpkg\ports
[DEBUG] Using installed-root: D:\dev\vcpkg\installed
[DEBUG] Using buildtrees-root: D:\dev\vcpkg\buildtrees
[DEBUG] Using packages-root: D:\dev\vcpkg\packages
[DEBUG] Using vcpkg-root: D:\dev\vcpkg
[DEBUG] Using scripts-root: D:\dev\vcpkg\scripts
[DEBUG] Using builtin-registry: D:\dev\vcpkg\versions
[DEBUG] Using downloads-root: D:\dev\vcpkg\downloads
[DEBUG] Default binary cache path is: C:\Users\spectra\AppData\Local\vcpkg\archives
Computing installation plan...
[DEBUG] Found path: C:\Program Files\CMake\bin\cmake.exe
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin\cmake.exe" --version)
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 7348: cmd_execute_and_stream_data() returned 0 after    31100 us
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin\cmake.exe" -DVCPKG_ROOT_DIR=D:/dev/vcpkg -DPACKAGES_DIR=D:/dev/vcpkg/packages -DBUILDTREES_DIR=D:/dev/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=D:/dev/vcpkg/installed -DDOWNLOADS=D:/dev/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "D:\dev\vcpkg\buildtrees\0.vcpkg_dep_info.cmake")
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 7348: cmd_execute_and_stream_data() returned 0 after    19594 us
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin\cmake.exe" -DVCPKG_ROOT_DIR=D:/dev/vcpkg -DPACKAGES_DIR=D:/dev/vcpkg/packages -DBUILDTREES_DIR=D:/dev/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=D:/dev/vcpkg/installed -DDOWNLOADS=D:/dev/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "D:\dev\vcpkg\buildtrees\1.vcpkg_dep_info.cmake")
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 7348: cmd_execute_and_stream_data() returned 0 after    19352 us
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin\cmake.exe" -DVCPKG_ROOT_DIR=D:/dev/vcpkg -DPACKAGES_DIR=D:/dev/vcpkg/packages -DBUILDTREES_DIR=D:/dev/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=D:/dev/vcpkg/installed -DDOWNLOADS=D:/dev/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "D:\dev\vcpkg\buildtrees\0.vcpkg_tags.cmake")
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 7348: cmd_execute_and_stream_data() returned 0 after    21844 us
The following packages will be built and installed:
  * libjpeg-turbo[core]:x64-windows -> 2.1.3#3
  * liblzma[core]:x64-windows -> 5.2.5#6
  * libpng[core]:x64-windows -> 1.6.37#18
  * libwebp[core,libwebpmux,nearlossless,simd,unicode]:x64-windows -> 1.2.2
    opencv3[core,default-features,dnn,flann,jpeg,png,quirc,tiff,webp]:x64-windows -> 3.4.16#9
  * protobuf[core]:x64-windows -> 3.21.3
  * quirc[core]:x64-windows -> 1.1#3
  * tiff[core,jpeg,lzma,zip]:x64-windows -> 4.4.0#1
  * vcpkg-cmake[core]:x64-windows -> 2022-07-18
  * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06#1
  * vcpkg-get-python-packages[core]:x64-windows -> 2022-04-11#1
  * zlib[core]:x64-windows -> 1.2.12#1
Additional packages (*) will be modified to complete this operation.
[DEBUG] CreateProcessW("C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease -legacy -products * -format xml)
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 7348: cmd_execute_and_stream_data() returned 0 after    23419 us
error: in triplet x64-windows: Unable to find a valid Visual Studio instance
    at "C:/Program Files/Microsoft Visual Studio/2022/Preview"
The following Visual Studio instances were considered:
    C:\Program Files\Microsoft Visual Studio\2022\Preview
    C:\Program Files\Microsoft Visual Studio\2022\Preview
    C:\Program Files\Microsoft Visual Studio\2022\Preview
    C:\Program Files\Microsoft Visual Studio\2022\Preview
The following paths were examined for Visual Studio instances:
    C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Auxiliary/Build\vcvarsall.bat
    C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools/MSVC\14.33.31627\bin/HostX86/x86\dumpbin.exe
    C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools/MSVC\14.31.31103\bin/HostX86/x86\dumpbin.exe
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC/vcvarsall.bat

[DEBUG] D:\a\_work\1\s\src\vcpkg\vcpkgpaths.cpp(1363):
[DEBUG] Time in subprocesses: 115309 us
[DEBUG] Time in parsing JSON: 982 us
[DEBUG] Time in JSON reader: 482 us
[DEBUG] Time in filesystem: 2725 us
[DEBUG] Time in loading ports: 3072 us
[DEBUG] Exiting after 141 ms (134656 us)
```
vcpkg package management program version 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22

**Comment by Lishen1** [comment]
VCPKG_VISUAL_STUDIO_PATH was set. so, vcpkg don't try to find in other places (but talk in log like trying to fing)

**Comment by Adela0814** [comment]
@Lishen1 could you please try the solutions in https://github.com/microsoft/vcpkg/issues/22074.

**Comment by Lishen1** [comment]
i tried all solutions what i found, especially from issues. it doesn't work. i solved my problem, just remove  VCPKG_VISUAL_STUDIO_PATH from my env. but vcpkg don't give any useful information in logs to point me

**Comment by tarazu** [comment]
I'm trying to use https://hub.docker.com/_/microsoft-dotnet-framework-sdk/ with vcpkg and I'm stuck on this error

This might not be the same issue a previous posts, but since you are looking for more information I here have a reproducable case running in docker.

Here is the Dockerfile I use

```
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8

RUN Set-ExecutionPolicy Bypass -Scope Process -Force; \
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; \
    iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

RUN choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y --no-progress; \
    choco install git -y --no-progress; \
    refreshenv

# we should now have choco, nuget, wget, cmake, git and msbuild

ENV VCPKG_VISUAL_STUDIO_PATH="C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools"

RUN git clone https://github.com/Microsoft/vcpkg.git; \
    .\vcpkg\bootstrap-vcpkg.bat -disableMetrics; \
    C:\vcpkg\vcpkg.exe integrate install

ADD vcpkg.json .
RUN C:\vcpkg\vcpkg.exe install --triplet x64-windows-static --debug --debug-env
```

The error I get is this:

```
error: in triplet x64-windows-static: Unable to find a valid Visual Studio instance
    at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
Could not locate a complete Visual Studio instance
The following paths were examined for Visual Studio instances:
    C:\Program Files (x86)\Microsoft Visual Studio\2022\TestAgent\VC\Auxiliary/Build\vcvarsall.bat
```

I don't really know what it wrong, the container might be missing something for vcpkg to play nice. BUT it would be really nice for CI if the Microsoft SDK container worked with Microsoft vcpkg!!

**Comment by Adela0814** [comment]
Do you still have the problem?

**Comment by tarazu** [comment]
Thanks for the reply, but I wasn't able to solve the issue. I actually ended up abandoning both windows containers and vcpkg. I went back to old tech, I run a windows VM and use conan. Mostly visual studio that was causing me headaches. There may be easier ways to do CI like this for windows, probably with llvm.

**Comment by AlexandreAero** [comment]
I'm having this issue too, really annoying. I tried everything, got everything installed but still instance error...

**Comment by AlexandreAero** [comment]
![image](https://user-images.githubusercontent.com/66020831/233805084-90adbdc2-6fb0-4490-b1f6-8081405e97c8.png)

**Comment by Yuki-Tani** [comment]
### For people who have both _VS 2022 IDE_ and _VS 2022 Build Tools_
I had the similar error. I will leave a comment here so that no one else loses a day as I did for the same reasons. 
```
error: in triplet x64-windows: Unable to find a valid Visual Studio instance
    Could not locate a complete Visual Studio instance
    The following paths were examined for Visual Studio instances:
        C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary/Build\vcvarsall.bat 
```
### Environment
- win11
- I had `C:\Program Files\Microsoft Visual Studio\2022\Enterprise` (VS Enterprise 2022 IDE) in my machine. Apart from that, `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools` **(VS Build Tools 2022) is also installed** in my machine.
- I had `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat`, but I didn't have `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvarsall.bat`. In other words, Visual Studio components listed in [the list](https://github.com/microsoft/vcpkg/issues/22074#issuecomment-1022840591) were installed in VS Enterprise 2022 IDE, but not installed in VS Build Tools 2022.
- vcpkg is run in VS 2022 IDE, during the build process.

### What I tried (but didn't resolve the issue)
I thought vcpkg could not find VS 2020 IDE's `vcvarsall.bat`, so I tried setting an environment variable `VCPKG_VISUAL_STUDIO_PATH` to `C:\Program Files\Microsoft Visual Studio\2022\Enterprise`, reopening VS IDE and rebuilding. However, it still showed an error. 
```
error: in triplet x64-windows: Unable to find a valid Visual Studio instance
        at "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
    Could not locate a complete Visual Studio instance
    The following paths were examined for Visual Studio instances:
        C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary/Build\vcvarsall.bat
```

### Workaround
**Uninstalling "VS Build Tools 2022" and leaving "VS Enterprise 2022 (IDE)" alone**. This workaround prevents vcpkg from confusing. (VCPKG_VISUAL_STUDIO_PATH was not necessary)

(Another workaround might be installing Visual Studio components listed in [the list](https://github.com/microsoft/vcpkg/issues/22074#issuecomment-1022840591) to VS Build Tools 2022 side)

**Comment by Yuki-Tani** [comment]
There seems to be a bug where the path to the Visual Studio instance cannot be found correctly, when we have multiple versions of Visual Studio (including VS Build Tool).

**Comment by sfhacker** [comment]
This is getting more and more embarrassing!

**Comment by sfhacker** [comment]
Embarrassing!
