### ISSUE TITLE
[yasm] Build error in the file vcpkg_execute_buil_process.cmake line 129

### ISSUE THREAD

**Issue by LionelPeeters** [microsoft/vcpkg#25991]
** ----------------------------------------------------------------------------------------------**
**Host Environment**
Window 11

** ----------------------------------------------------------------------------------------------**
**To Reproduce**
1) execute the following script in windows cmdline or gitbash
@echo off

IF NOT EXIST vcpkg (
	echo First time setup. Downloading vcpkg
	git clone https://github.com/microsoft/vcpkg.git
	.\vcpkg\bootstrap-vcpkg.bat -disableMetrics
	.\vcpkg\vcpkg.exe integrate install
	.\vcpkg\vcpkg.exe integrate project
) ELSE (
	echo vcpkg is available. Updating.
	cd vcpkg
	git pull
	.\bootstrap-vcpkg.bat -disableMetrics
)
// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// Here are the JSON dependencies used
"builtin-baseline": "14e7bb4ae24616ec54ff6b2f6ef4e8659434ea44",
	"dependencies": [
		"freetype",
		"libflac",
		"libogg",
		"libpng",
		"libsndfile",
		"libtheora",
		"libvorbis",
		"libvpx",
		"minizip",
		"mp3lame",
		"mpg123",
		"openssl",
		"pthread",
		"restclient-cpp",
		"zlib"
	],
	"overrides": [
		{ "name": "freetype", "version": "2.12.1" },
		{ "name": "libflac", "version": "1.3.4" },
		{ "name": "libogg", "version": "1.3.5" },
		{ "name": "libpng", "version": "1.6.37", "port-version": 17 },
		{ "name": "libsndfile", "version": "1.1.0" },
		{ "name": "libtheora", "version": "1.1.1" },
		{ "name": "libvorbis", "version": "1.3.7" },
		{ "name": "libvpx", "version": "1.11.0" },
		{ "name": "minizip", "version": "1.2.11" },
		{ "name": "mp3lame", "version": "3.100-1" },
		{ "name": "mpg123", "version": "1.29.3" },
		{ "name": "openssl", "version": "3.0.3" },
		{ "name": "pthread", "version": "3.0.0" },
		{ "name": "restclient-cpp", "version": "2022-02-09" },
		{ "name": "zlib", "version": "1.2.12" }

2) type .\vcpkg\vcpkg.exe install

3) the installation fails

** ----------------------------------------------------------------------------------------------**
**Failure logs**

LionelFixe@DESKTOP-04AAUDS MINGW64 /e/dev/github/Winamp-Desktop/external_dependencies (main)
$ ./vcpkg/vcpkg.exe install
Detecting compiler hash for triplet x86-windows...
Detecting compiler hash for triplet x64-windows...
The following packages will be built and installed:
  * curl[core,non-http,schannel,ssl,sspi]:x86-windows -> 7.83.0 -- E:\Dev\github\Winamp-Desktop\external_dependencies\vcpkg\buildtrees\versioning_\versions\curl\d72a11c8c3990818ba5987cc1ceee799046de9be
    libsndfile[core,external-libs,mpeg]:x86-windows -> 1.1.0 -- E:\Dev\github\Winamp-Desktop\external_dependencies\vcpkg\buildtrees\versioning_\versions\libsndfile\1ec8249a4721dda26735a12603defe2aa680c264
    libtheora[core]:x86-windows -> 1.1.1 -- E:\Dev\github\Winamp-Desktop\external_dependencies\vcpkg\buildtrees\versioning_\versions\libtheora\099587b9692d8e05ceed9ba922140bbefa763753
    libvorbis[core]:x86-windows -> 1.3.7 -- E:\Dev\github\Winamp-Desktop\external_dependencies\vcpkg\buildtrees\versioning_\versions\libvorbis\0b0587525c2053316552dce564fe504a2a40cc91
    libvpx[core]:x86-windows -> 1.11.0 -- E:\Dev\github\Winamp-Desktop\external_dependencies\vcpkg\buildtrees\versioning_\versions\libvpx\3ec8aec9ecbcb2e3b5a0af7cea8045359d9aec94
    minizip[core]:x86-windows -> 1.2.11 -- E:\Dev\github\Winamp-Desktop\external_dependencies\vcpkg\buildtrees\versioning_\versions\minizip\ef35aa9f1b2e49df05aebea8b2f2caafe5179625
    mp3lame[core]:x86-windows -> 3.100-1 -- E:\Dev\github\Winamp-Desktop\external_dependencies\vcpkg\buildtrees\versioning_\versions\mp3lame\3a83237960b5f3c8f927dcf060fa858289772545
    mpg123[core]:x86-windows -> 1.29.3 -- E:\Dev\github\Winamp-Desktop\external_dependencies\vcpkg\buildtrees\versioning_\versions\mpg123\2b99f7a71d1996dc6a61c81a11a9a98805eba1c4
    openssl[core]:x86-windows -> 3.0.3 -- E:\Dev\github\Winamp-Desktop\external_dependencies\vcpkg\buildtrees\versioning_\versions\openssl\973408910bc03c5a350f502080548a0d1ac68352
  * opus[core]:x86-windows -> 1.3.1#6 -- E:\Dev\github\Winamp-Desktop\external_dependencies\vcpkg\buildtrees\versioning_\versions\opus\e718de4be5f3dcb0e0c7922a9ef7ef13bf5148b3
    pthread[core]:x86-windows -> 3.0.0 -- E:\Dev\github\Winamp-Desktop\external_dependencies\vcpkg\buildtrees\versioning_\versions\pthread\f26e38024e286875f1e954fb75bda82b3a3329f4
  * pthreads[core]:x86-windows -> 3.0.0#10 -- E:\Dev\github\Winamp-Desktop\external_dependencies\vcpkg\buildtrees\versioning_\versions\pthreads\ab9d25f08115355ea2d4e4c6eae94626fa86fded
    restclient-cpp[core]:x86-windows -> 2022-02-09 -- E:\Dev\github\Winamp-Desktop\external_dependencies\vcpkg\buildtrees\versioning_\versions\restclient-cpp\7eeae27247c8a1e6f5dab2356cb94370aaabb7fc
  * yasm[core,tools]:x64-windows -> 1.3.0#3 -- E:\Dev\github\Winamp-Desktop\external_dependencies\vcpkg\buildtrees\versioning_\versions\yasm\4368509dc3dfe6cab848b8713b22c9c0ef408527
  * yasm-tool-helper[core]:x86-windows -> 2020-03-11#1 -- E:\Dev\github\Winamp-Desktop\external_dependencies\vcpkg\buildtrees\versioning_\versions\yasm-tool-helper\0a2dfb294bebae79c48cc710756756164175be1d
Additional packages (*) will be modified to complete this operation.
Restored 0 package(s) from C:\Users\LionelFixe\AppData\Local\vcpkg\archives in 460.9 us. Use --debug to see more details.
Installing 1/15 yasm:x64-windows...
Building yasm[core,tools]:x64-windows...
-- Installing port from location: E:\Dev\github\Winamp-Desktop\external_dependencies\vcpkg\buildtrees\versioning_\versions\yasm\4368509dc3dfe6cab848b8713b22c9c0ef408527
-- Using cached yasm-yasm-009450c7ad4d425fa5a10ac4bd6efbd25248d823.tar.gz.
-- Cleaning sources at E:/Dev/github/Winamp-Desktop/external_dependencies/vcpkg/buildtrees/yasm/src/d25248d823-91ef8ed31f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/Dev/github/Winamp-Desktop/external_dependencies/vcpkg/downloads/yasm-yasm-009450c7ad4d425fa5a10ac4bd6efbd25248d823.tar.gz
-- Applying patch add-feature-tools.patch
-- Using source at E:/Dev/github/Winamp-Desktop/external_dependencies/vcpkg/buildtrees/yasm/src/d25248d823-91ef8ed31f.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Warning at scripts/cmake/vcpkg_execute_build_process.cmake:60 (message):
  Please ensure your system has sufficient memory.
Call Stack (most recent call first):
  E:/Dev/github/Winamp-Desktop/vcpkg_installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:112 (vcpkg_execute_build_process)
  E:/Dev/github/Winamp-Desktop/vcpkg_installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  buildtrees/versioning_/versions/yasm/4368509dc3dfe6cab848b8713b22c9c0ef408527/portfile.cmake:27 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: E:/Dev/github/Winamp-Desktop/external_dependencies/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: E:/Dev/github/Winamp-Desktop/external_dependencies/vcpkg/buildtrees/yasm/x64-windows-dbg
    See logs for more information:
      E:\Dev\github\Winamp-Desktop\external_dependencies\vcpkg\buildtrees\yasm\install-x64-windows-dbg-out.log
      E:\Dev\github\Winamp-Desktop\external_dependencies\vcpkg\buildtrees\yasm\install-x64-windows-dbg-out-1.log

Call Stack (most recent call first):
  E:/Dev/github/Winamp-Desktop/vcpkg_installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:112 (vcpkg_execute_build_process)
  E:/Dev/github/Winamp-Desktop/vcpkg_installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  buildtrees/versioning_/versions/yasm/4368509dc3dfe6cab848b8713b22c9c0ef408527/portfile.cmake:27 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building yasm:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+yasm
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[yasm]+Build+error
Include '[yasm] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: b010f2789 2022-07-25 (14 hours ago)

You can also use the prefilled template from E:\Dev\github\Winamp-Desktop\vcpkg_installed\vcpkg\issue_body.md.

**Comment by JackBoosY** [comment]
Can you please provide the following logs first?
E:\Dev\github\Winamp-Desktop\external_dependencies\vcpkg\buildtrees\yasm\install-x64-windows-dbg-out.log
E:\Dev\github\Winamp-Desktop\external_dependencies\vcpkg\buildtrees\yasm\install-x64-windows-dbg-out-1.log

**Comment by LionelPeeters** [comment]
Yes no problem
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/9195670/install-x64-windows-dbg-out.log)
[install-x64-windows-dbg-out-1.log](https://github.com/microsoft/vcpkg/files/9195671/install-x64-windows-dbg-out-1.log)

**Comment by JackBoosY** [comment]
```
LINK : fatal error LNK1104: cannot open file 'vsyasm.exe'
```
Please make sure your vcpkg is latest, remove `yasm:x64-windows` then try again.

Thanks.

**Comment by LionelPeeters** [comment]
```
$ ./vcpkg.exe version
vcpkg package management program version 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
```
This seems to be the last version no?

**Comment by JackBoosY** [comment]
@LionelPeeters Please check with `git pull`.

**Comment by dg0yt** [comment]
~~~
FAILED: vsyasm.exe 
cmd.exe /C "cd . && E:\Dev\github\Winamp-Desktop\external_dependencies\vcpkg\downloads\tools\cmake-3.22.2-windows\cmake-3.22.2-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=frontends\vsyasm\CMakeFiles\vsyasm.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MICROS~2\2022\COMMUN~1\VC\Tools\MSVC\1431~1.311\bin\Hostx64\x64\link.exe  frontends\vsyasm\CMakeFiles\vsyasm.dir\vsyasm.obj frontends\vsyasm\CMakeFiles\vsyasm.dir\__\yasm\yasm-options.obj frontends\vsyasm\CMakeFiles\vsyasm.dir\__\yasm\yasm-plugin.obj  /out:vsyasm.exe /implib:vsyasm.lib /pdb:vsyasm.pdb /version:0.0 /machine:x64 /nologo    /debug /INCREMENTAL /subsystem:console  yasm.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
LINK Pass 1: command "C:\PROGRA~1\MICROS~2\2022\COMMUN~1\VC\Tools\MSVC\1431~1.311\bin\Hostx64\x64\link.exe frontends\vsyasm\CMakeFiles\vsyasm.dir\vsyasm.obj frontends\vsyasm\CMakeFiles\vsyasm.dir\__\yasm\yasm-options.obj frontends\vsyasm\CMakeFiles\vsyasm.dir\__\yasm\yasm-plugin.obj /out:vsyasm.exe /implib:vsyasm.lib /pdb:vsyasm.pdb /version:0.0 /machine:x64 /nologo /debug /INCREMENTAL /subsystem:console yasm.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:frontends\vsyasm\CMakeFiles\vsyasm.dir/intermediate.manifest frontends\vsyasm\CMakeFiles\vsyasm.dir/manifest.res" failed (exit code 1104) with the following output:
LINK : fatal error LNK1104: cannot open file 'vsyasm.exe'
~~~

I would rather suspect anti-virus locking the newly created exe.

**Comment by LionelPeeters** [comment]
The git pull didn't do anything yesterday and to it does...
```
$ git pull
remote: Enumerating objects: 67, done.
remote: Counting objects: 100% (67/67), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 67 (delta 30), reused 51 (delta 26), pack-reused 0
Unpacking objects: 100% (67/67), 106.99 KiB | 125.00 KiB/s, done.
From https://github.com/microsoft/vcpkg
   b010f2789..0257395b0  master     -> origin/master
Updating b010f2789..0257395b0
Fast-forward
 ports/brotli/portfile.cmake               | 19 +++++-----
 ports/brotli/vcpkg.json                   | 17 +++++++--
 ports/daw-header-libraries/portfile.cmake |  4 +-
 ports/daw-header-libraries/vcpkg.json     |  2 +-
 ports/dpp/make-pkgconfig-required.patch   | 16 ++++++++
 ports/dpp/portfile.cmake                  | 32 ++++++++++++++++
 ports/dpp/usage                           |  3 ++
 ports/dpp/vcpkg.json                      | 23 ++++++++++++
 ports/freetype/portfile.cmake             | 10 ++---
 ports/freetype/vcpkg.json                 |  1 +
 ports/openssl/vcpkg.json                  |  1 +
 ports/openssl/windows/portfile.cmake      | 61 +++++++++++++++++++------------
 ports/vamp-sdk/portfile.cmake             |  9 ++---
 ports/vamp-sdk/vcpkg.json                 |  7 +---
 scripts/ci.baseline.txt                   | 17 +++++++++
 versions/b-/brotli.json                   |  5 +++
 versions/baseline.json                    | 14 ++++---
 versions/d-/daw-header-libraries.json     |  5 +++
 versions/d-/dpp.json                      |  9 +++++
 versions/f-/freetype.json                 |  5 +++
 versions/o-/openssl.json                  |  5 +++
 versions/v-/vamp-sdk.json                 |  5 +++
 22 files changed, 209 insertions(+), 61 deletions(-)
 create mode 100644 ports/dpp/make-pkgconfig-required.patch
 create mode 100644 ports/dpp/portfile.cmake
 create mode 100644 ports/dpp/usage
 create mode 100644 ports/dpp/vcpkg.json
 create mode 100644 versions/d-/dpp.json
```
After cleaning and full build it is working, sorry guy...
