### ISSUE TITLE
add libarchive

### ISSUE THREAD

**Issue by vaintroub** [Microsoft/vcpkg#260]
https://github.com/libarchive/libarchive

The libarchive project develops a portable, efficient C library that can read and write streaming archives in a variety of formats. It also includes implementations of the common tar, cpio, and zcat command-line tools that use the libarchive library.

**Comment by codicodi** [comment]
Judging from libarchive's CMakeLists most (all?) of it's dependencies are optional, but the library is barely functional without them. IMHO it would be best to gather most important ones before adding libarchive's port.

 Complete list of what buildsystem tries to find:

- [x] zlib
- [ ] bzip2, see #200
- [ ] [liblzma](http://tukaani.org/xz/)
- [ ] [lzo2](http://www.oberhumer.com/opensource/lzo/) <- GPL licensed - better not link to it by default
- [ ] [lz4](https://github.com/lz4/lz4)
- [ ] [nettle](https://www.lysator.liu.se/~nisse/nettle/) <- quite big and configure only, also [license hell](https://en.wikipedia.org/wiki/Nettle_(cryptographic_library)#Licence_and_motivation)
- [x] openssl
- [ ] [libmd](http://martin.hinner.info/libmd/) <- used only if openssl not found
- [x] iconv
- [x] libxml2
- [x] expat <- used only if libxml2 not found
- [x] pcre <- only for samples/tools/tests

I think we could add libarchive once we add bzip2, lz4 and liblzma ports. All of them are quite small so this shouldn't be difficult.

**Comment by vaintroub** [comment]
libarchive is functional without dependencies, but it would basically support tar/cpio  without them.
compression libraries are interesting, what is this nettle thing for, I have no idea (or even openssl)

**Comment by jonwil** [comment]
Does libarchive actually need nettle or can it get all the cryptography it needs from OpenSSL if Nettle isn't found?

**Comment by codicodi** [comment]
Buildscript isn't as clear in this case as in libxml2/expat situation but after searching for occurences of `HAVE_LIBNETTLE`  macro in source I believe no functionality will be lost. There is also a mode that definitely bears inverstigating in which winapi is used for cryptography, so maybe we could avoid any big dependency in this regard.

**Comment by ras0219-msft** [comment]
Closing this as fixed by #493.
