### ISSUE TITLE
If the import parameter command cannot be found, how can I import the binary package exported by export into vcpkg

### ISSUE THREAD

**Issue by szrushi** [microsoft/vcpkg#26001]
If the import parameter command cannot be found, how can I import the binary package exported by export into vcpkg

**Comment by JackBoosY** [comment]
You can use [integration](https://github.com/microsoft/vcpkg/blob/master/docs/users/buildsystems/integration.md) or [binarycaching](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/binarycaching.md).

**Comment by szrushi** [comment]
Thank you so much, this perfectly solved my needs.

**Comment by szrushi** [comment]
@JackBoosY  Thank you so much, this perfectly solved my needs.
