### ISSUE TITLE
vcpkg upgrade and modularized boost

### ISSUE THREAD

**Issue by cenit** [Microsoft/vcpkg#2600]
Since when `./vcpkg upgrade` has been introduced, I use it everytime. Most of the time, the `--no-dry-run` option is required. But one problem bothers me and just happened again: I will try my best to explain it. I think it's mostly related to modular boost anyway.
I have boost installed in 4 triplets variants (x86, x86-static, x64, x64-static). I just did `./vcpkg upgrade --no-dry-run` to update boost as per recent commit. But again (and it happens very often), after the upgrade, if I launch a `./vcpkg install boost boost:x86-windows-static boost:x64-windows boost:x64-windows-static` then `vcpkg`, instead of saying that they are already installed, notifies me that many `boost-...` packages have to be installed (not all of them but many, maybe all the ones that were not upgraded). This is again so strange, since boost should be already fully installed). And in fact during the install it's a flood of "File xxx was already present and will be overwritten".
Am I the only one to have this problem?

**Comment by Bitkoda** [comment]
It happened to me as well this morning, I had to reinstall the whole vcpkg because my list of installed packages was corrupted (I had less packages than was installed somehow, so whenever I was trying to install one, it would say all the files are already here)

But I got into another problem, I ran `vcpkg remove --outdated --recurse` then did a simple `vcpkg install boost-asio` (since it's all I need), and it installed 31 packages, here's a comparison of my `vcpkg list`: [before](https://i.imgur.com/aqlW51X.png), [after](https://i.imgur.com/9nLFIIo.png)

**Comment by ras0219-msft** [comment]
@bitkoda Just to be clear -- the "before" screen you posted seems fine given this series of events:
```
>vcpkg remove --outdated --recurse
>vcpkg list
>// take screenshot "before"
>vcpkg install boost-asio
>vcpkg list
>// take screenshot "after"
```
Sometimes we need to tweak individual boost sublibraries, which means they don't _all_ need to be uninstalled (another benefit of modularizing! 😄).

@cenit That definitely sounds like a bug -- you should ideally never get the "File xxx should be overwritten" except if a very, very, very rare race condition triggers with Ctrl-C.

Could you start backing up your `installed\vcpkg` folder before upgrading? This is the folder that contains the full "database" of installed information, such as what files belong to what and what packages are installed.

If you are able to reproduce strange behavior like this, please mail us the before/during/after at vcpkg@microsoft.com!

**Comment by cenit** [comment]
I could reproduce it on all my computers (to be honest, they are all identically configured, so at least in that configuration is reproducible). 
I will try to reproduce it again, maybe installing vcpkg from a past commit and then upgrading, and mail the results

**Comment by cenit** [comment]
email sent. 
I will report here any useful outcome if it is going to be a fault on my side and maybe others have the same problem.
