### ISSUE TITLE
[CPR] update to 1.9

### ISSUE THREAD

**Issue by bleriaf** [microsoft/vcpkg#26019]
Library name: CPR

New version number: 1.9

Other information that may be useful (release notes, etc...)
vcpkg has cpr already updated for version 1.9 but there was an update to the library 2 days ago which adds things i really need and vcpkg isn't updated for it

**Comment by JonLiu1993** [comment]
Fixed by https://github.com/microsoft/vcpkg/pull/25244

**Comment by bleriaf** [comment]
@JonLiu1993 hello, i dont think you have read the "more information" text i have shared, vcpkg IS updated for 1.9 but not for the latest commit: https://github.com/libcpr/cpr/commit/5ae5fdeadfbbb784192c034be0222016123c94ad which adds some stuff which are very helpful

**Comment by JonLiu1993** [comment]
@bleriaf ,the frequency of cpr Upstream releases the official version is very high, we do not recommend updating the port to the unofficial version of commit, you can wait for a while and I will update to the latest version immediately after the latest version of cpr is released.
