### ISSUE TITLE
Package request: libigl

### ISSUE THREAD

**Issue by patrikhuber** [microsoft/vcpkg#2601]
Hi!
It would be awesome to have libigl in the vcpkg repo: https://github.com/libigl/libigl
:-)

Also, nanogui (which is a dependency of libigl) - https://github.com/wjakob/nanogui.

**Comment by jjpepper** [comment]
I second that!

**Comment by JackBoosY** [comment]
Hi @patrikhuber, thanks for reporting this issue.
This port has been added in vcpkg, please update vcpkg and try to install it.

Thanks.
