### ISSUE TITLE
curl build failure

### ISSUE THREAD

**Issue by GRRedWings** [microsoft/vcpkg#26015]
**Host Environment**
- OS: Windows 10
Microsoft Visual Studio Enterprise 2019
Version 16.11.16
VisualStudio.16.Release/16.11.16+32602.291
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA239
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.11.106.23128
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.11.106.23128
Azure App Service Tools v3.0.0

C# Tools   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.11.21196.2
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.11.2
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.11.21196.2
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Profiling support   16.11.21196.2
Profiling support for Python projects.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.30526.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.11.0-beta.21514.6+b6c2c4f53ea3a08fa603ea93d6d2f808a62a21d1
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

**To Reproduce**
./vcpkg.exe install curl --triplet x64-windows

**Failure logs**
Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:184 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".

      If error with status 4 (Issue #15434),
      try setting "http://user:password@your-proxy-ip-address:port/".

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:90 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_acquire_msys.cmake:138 (msys_package_download)
  scripts/cmake/vcpkg_find_acquire_program.cmake:446 (vcpkg_acquire_msys)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:112 (vcpkg_find_acquire_program)
  ports/zlib/portfile.cmake:48 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:136 (include)

Error: Building package zlib:x64-windows failed with: BUILD_FAILED

**Additional context**
clean pull on git and ran the command above.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Now the version of `mingw-w64-i686-pkg-config` is 0.29.2-3, did you use the latest vcpkg to install `zlib:x64-windows`? Or you can run command `git pull` and `.\bootstrap-vcpkg.bat` to update vcpkg.

**Comment by GRRedWings** [comment]
I tried, and zlib is the problem

-- Downloading
https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz
-> msys-mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz...
-- Downloading
https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz...
Failed. Status: 6;"Couldn't resolve host name"
-- Downloading
https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz
-> msys-mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz...
-- Downloading
https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz...
Failed. Status: 22;"HTTP response code said error"
-- Downloading
https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz
-> msys-mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz...
-- Downloading
https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz...
Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:184 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
environment
      variables to ***@***.***:port/".

      If error with status 4 (Issue #15434),
      try setting ***@***.***:port/".

      Otherwise, please submit an issue at
https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:90 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_acquire_msys.cmake:138 (msys_package_download)
  scripts/cmake/vcpkg_find_acquire_program.cmake:446 (vcpkg_acquire_msys)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:112 (vcpkg_find_acquire_program)
  ports/zlib/portfile.cmake:48 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:136 (include)


Error: Building package zlib:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x64-windows
  Vcpkg version: 2020.11.12--unknownhash

Additionally, attach any relevant sections from the log files above.
PS D:\SPE\Authentication\liboauth2\vcpkg> .\vcpkg.exe update
Using local portfile versions. To update the local portfiles, use `git
pull`.
No packages need updating.
PS D:\SPE\Authentication\liboauth2\vcpkg>

**Comment by StarGate-One** [comment]
@GRRedWings 

> Package: zlib:x64-windows 
>Vcpkg version: 2020.11.12--unknownhash 

This is a very old version of vcpkg (18 months give or take a few days), therefore many of the supporting tools used by that version vcpkg are out of date and are no longer available (msys normally keeps only a few current versions available).
I would suggest creating a new clone of vcpkg (either deleting the current one or creating a new clone with a different name) using the instructions found here in the [Quick Start: Windows](https://github.com/microsoft/vcpkg#quick-start-windows).

**Comment by GRRedWings** [comment]
I see that my error was that I had a sub module, and while I thought I was pulling the latest that was over writing. Sorry about that
