### ISSUE TITLE
[wxwidgets] Add support for WebView2 backend for wxWebView control on Windows

### ISSUE THREAD

**Issue by fishnet37222** [microsoft/vcpkg#26013]
****

**Is your feature request related to a problem? Please describe.**
The Trident engine behind Internet Explorer has been deprecated and will probably be removed from Windows at some point in the future.

**Proposed solution**
wxWidgets already supports using WebView2 as a backend for wxWebView on Windows, but it is not enabled by default.  I'd like to see this port updated to enable that functionality if so desired by the user.

**Describe alternatives you've considered**
The only alternative is to build wxWidgets myself which defeats the purpose of using vcpkg.

**Additional context**
Enabling this feature seems pretty simple according to the [wxWidgets documentation](https://docs.wxwidgets.org/3.2/classwx_web_view.html).

**Comment by fishnet37222** [comment]
I took the liberty of trying to implement this myself, and I have it partially working.  I have it so it builds the wxWebView library with support for the Edge backend, but I'm not sure how to associate it with a feature nor how to get it to copy the WebView2Loader.dll file to the output folder along with all the other libraries.

Here is the only change I've made so far.
![image](https://user-images.githubusercontent.com/1977106/182132757-7748e307-4492-4a2f-9831-fde46a4ea655.png)

Here you can see the DLLs with the WebView2Loader.dll selected.
![image](https://user-images.githubusercontent.com/1977106/182133248-c6261a11-0baa-47ca-99fa-81602379758c.png)

**Comment by scott-t** [comment]
Would be nice to support the static Edge option (WXWIDGETS_USE_WEBVIEW_EDGE_STATIC=ON) as well, but then the .lib ends up in a deep 
```
buildtrees\wxwidgets\x86-windows-static-md-dbg\packages\Microsoft.Web.WebView2.1.0.705.50\runtimes\win-x86\native
```
path (or x64, etc) that I'm not sure how to pull out programmatically.

When STATIC=OFF but in a static-build triplet, the loader dll is correctly moved into the buildtree lib folder too so can be copied out by an appropriate cmake command.

**Comment by fishnet37222** [comment]
I just tried the new change, and it doesn't copy the "WebView2Loader.dll" to the output folder.  That DLL is required in order for this feature to work.

I used a manifest file in my test project, and the DLL was in the "vcpkg_installed\x64-windows\bin" folder.  The loader DLL should be copied to the output folder whenever "wxmsw32ud_webview_vc.dll" is copied to the output folder.

**Comment by Adela0814** [comment]
The `webview2 `we are using now is the port in `vcpkg`, so you can find the dll and lib in `vcpkg_installed\x64-windows`. 
What problems do you encounter when using it, you can create a new issue and provide the full failure logs.
