### ISSUE TITLE
pcre build failure

### ISSUE THREAD

**Issue by GRRedWings** [microsoft/vcpkg#26014]
**Host Environment**
- OS: Windows 10
Microsoft Visual Studio Enterprise 2019
Version 16.11.16
VisualStudio.16.Release/16.11.16+32602.291
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA239
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.11.106.23128
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.11.106.23128
Azure App Service Tools v3.0.0

C# Tools   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.11.21196.2
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.11.2
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.11.21196.2
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Profiling support   16.11.21196.2
Profiling support for Python projects.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.30526.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.11.0-beta.21514.6+b6c2c4f53ea3a08fa603ea93d6d2f808a62a21d1
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

**To Reproduce**
./vcpkg.exe install pcre --triplet x64-windows

**Failure logs**
Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"

**Additional context**
Building on Windows 10 in powershell. Just running the command above after a clean git pull on the repo

**Comment by FrankXie05** [comment]
MSYS2 is a rolling release project, and `vcpkg` currently cannot save obsolete binary packages. Please `git pull` and try again. 
This link has expired. ` https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz`
Or  unzip this 
[msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zip](https://github.com/microsoft/vcpkg/files/9206007/msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zip)
and put it into VCPKG_ROOT/downloads then try again.

**Comment by GRRedWings** [comment]
I'm getting the same error on curl now.  Is this something that also needs
to be fixed?


B

**Comment by StarGate-One** [comment]
@GRRedWings 
See my https://github.com/microsoft/vcpkg/issues/26015#issuecomment-1198563709 - this is the same issue. The vcpkg version you have to too old and still references msys tools that are not longer available.

**Comment by GRRedWings** [comment]
I see that my error was that I had a sub module, and while I thought I was pulling the latest that was over writing. Sorry about that
