### ISSUE TITLE
The boost Python package cannot be used in visual studio.

### ISSUE THREAD

**Issue by linjiahao962889027** [microsoft/vcpkg#26022]
**Describe the bug**

**Environment**
- OS: Windows 10
- Compiler: Visual Studio 2022（143）

**To Reproduce**
./vcpkg install boost:x64-windows-static python3:x64-windows-static
![image](https://user-images.githubusercontent.com/46292984/181413211-95f4f7ee-e842-45ec-8bea-14aa8130d3b8.png)
Repro code when
![屏幕截图 2022-07-28 112110](https://user-images.githubusercontent.com/46292984/181413391-2d8de4c9-c380-4018-8b6b-dc38fd406c35.png)
**Expected behavior**
Use the python package of boost normally in visual studio.

**Failure logs**
See the picture.

**Additional context**
1. Other boost packages are used normally.
2. The normal python310 folder included in the project settings of visual studio cannot be successfully compiled in x64 release mode.
![屏幕截图 2022-07-28 113024](https://user-images.githubusercontent.com/46292984/181414358-57c2501d-86fa-4abc-a2ec-c30ab0e591b9.png)
3. After the normal python310 folder included in the project settings of visual studio, it still cannot be compiled successfully in x64 debug mode, and prompts that the file python310.lib cannot be opened.
![屏幕截图 2022-07-28 113640](https://user-images.githubusercontent.com/46292984/181415180-5095c541-dd5c-4dbb-a064-38fe11866763.png)

**Comment by Osyotr** [comment]
Regarding the link issue, it's probably https://github.com/microsoft/vcpkg/issues/23374

**Comment by JackBoosY** [comment]
Yes, it seems the same issue with #23374.
