### ISSUE TITLE
msys2 64-bit is installed when running on 32-bit OS

### ISSUE THREAD

**Issue by kambala-decapitator** [microsoft/vcpkg#26036]
**Describe the bug**

Some ports (FFmpeg, ICU) require MSYS2 package. But vcpkg downloads 64-bit version which can't be launched on 32-bit OS.

**Environment**
- OS: Windows 8.1 32-bit
- Compiler: msvc 2019 (Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30146 for x86)
- vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
- vcpkg-scripts version: e20e1c790 2022-07-27 (20 hours ago)

**To Reproduce**
1. ./vcpkg install ffmpeg:x86-windows
2. See error

**Expected behavior**
MSYS2 for 32-bit is downloaded.

**Failure logs**

```
-- Using cached msys-bash-5.1.008-1-x86_64.pkg.tar.zst.
...
-- Building ffmpeg for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: D:/vcmi-build/vcpkg/downloads/tools/msys2/79d5b6b790550399/usr/bin/bash.exe ./build.sh
    Working Directory: D:/vcmi-build/vcpkg/buildtrees/ffmpeg/x86-windows-rel
    Error code: This version of %1 is not compatible with the version of Windows that you're running. Check your computer's system information and then contact the software publisher
    See logs for more information:

Call Stack (most recent call first):
  ports/ffmpeg/portfile.cmake:548 (vcpkg_execute_required_process)
  scripts/ports.cmake:147 (include)
```

**Additional context**

Had the same issue with Ninja, but that was easily solved by symlinking my built version into expected location: https://github.com/microsoft/vcpkg/issues/21482#issuecomment-1198195050

**Comment by JackBoosY** [comment]
cc @dg0yt @Neumann-A

**Comment by Neumann-A** [comment]
> cc @dg0yt @Neumann-A

Why are we getting pinged? If I remember correctly @ras0219-msft did the rewrite of the msys stuff. 
If I also remember correctly there is no x86 version of msys anymore. (the x86 toolchain still exists but that won't help will the underlying tools)

**Comment by JackBoosY** [comment]
Yeah... the upstream doesn't support x86 now: https://repo.msys2.org/msys/

**Comment by kambala-decapitator** [comment]
> Yeah... the upstream doesn't support x86 now: https://repo.msys2.org/msys/

[i686 packages](https://repo.msys2.org/msys/i686/) are still there, but 32-bit installer is no longer published, last release that contains it is https://github.com/msys2/msys2-installer/releases/tag/2020-05-17.

Please provide a workaround for using local copy of msys2.

**Comment by JackBoosY** [comment]
@kambala-decapitator Can you please make a PR to fix this?
