### ISSUE TITLE
How to handle dependencies when packaging a Github repo for a new port?

### ISSUE THREAD

**Issue by diegovelaz** [microsoft/vcpkg#26037]
I'm packaging [microsoft/tracelogging](https://github.com/microsoft/TraceLogging) to be consumed through vcpkg, but it has a dependency on [LTTng](https://github.com/lttng) which doesn't have a vcpkg port yet. Is there a way to handle this dependency without creating a port for all the modules of LTTng that TraceLogging depends on?

**Comment by diegovelaz** [comment]
@bhardwajs

**Comment by ras0219-msft** [comment]
Generally dependencies should be split out into independent ports so we avoid ODR violations and they're easy to maintain and update. How many modules does LTTng have? Generally, one repo turns into one port.

**Comment by diegovelaz** [comment]
[LTTng](https://github.com/lttng) has 9 separate modules for what I can tell, each on its own repo, but [microsoft/tracelogging](https://github.com/microsoft/TraceLogging) only depends on two of them:

- lttng-ust-dev
- lttng-tools

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
