### ISSUE TITLE
[libmariadb]:x64-mingw-static build error

### ISSUE THREAD

**Issue by omeranha** [microsoft/vcpkg#26059]
**Host Environment**
- OS: Windows
Hi, i'm trying to generate cmake cache using vcpkg and x64-mingw-static but this error occurs every time, I don't know what to do
I can't generate cache with x64-windows because it needs an visual studio instance, and I don't want to use vs
I know x64-mingw-static is a community triplet configuration but maybe someone can fix this
**To Reproduce**
`./vcpkg install libmariadb[core,mariadbclient,schannel,ssl]:x64-mingw-static`

**Failure logs**
-- Building x64-mingw-static-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: C:/opentibia/CMake/bin/cmake.exe --build . --config Debug --target install -- -v -j7
    Working Directory: C:/opentibia/vcpkg/buildtrees/libmariadb/x64-mingw-static-dbg
    See logs for more information:
      C:\opentibia\vcpkg\buildtrees\libmariadb\install-x64-mingw-static-dbg-out.log

Call Stack (most recent call first):
  C:/opentibia/canary/build/windows-release/vcpkg_installed/x64-mingw-static/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  C:/opentibia/canary/build/windows-release/vcpkg_installed/x64-mingw-static/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/libmariadb/portfile.cmake:62 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building libmariadb:x64-mingw-static failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libmariadb
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libmariadb]+Build+error
Include '[libmariadb] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: 47a0bd967 2022-07-28 (10 hours ago)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Thomas1664** [comment]
Please provide the log files:

> See logs for more information:
C:\opentibia\vcpkg\buildtrees\libmariadb\install-x64-mingw-static-dbg-out.log

**Comment by omeranha** [comment]
> Please provide the log files:
> 
> > See logs for more information:
> > C:\opentibia\vcpkg\buildtrees\libmariadb\install-x64-mingw-static-dbg-out.log

https://pastebin.com/aPbPUKT5

**Comment by Thomas1664** [comment]
The issue is that mingw doen't define `CALG_ECDH` in `wincrypt.h` and other symbols of `wincrypt.h`. I suggest that you use the openssl backend:
`./vcpkg install libmariadb[core,mariadbclient,openssl]:x64-mingw-static`

**Comment by omeranha** [comment]
@Thomas1664 thank you it solved the issue, but I have one on luajit now, can you help me with that?
as far as i understand the installation is getting the wrong Makefile, it should be using src/makefile(for mingw compilation), i don't know exactly

Installing 1/1 luajit:x64-mingw-static...
Building luajit[core]:x64-mingw-static...
warning: -- Using community triplet x64-mingw-static. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\opentibia\vcpkg\triplets\community\x64-mingw-static.cmake
-- Using cached LuaJIT-LuaJIT-v2.0.5.tar.gz.
-- Cleaning sources at C:/opentibia/vcpkg/buildtrees/luajit/src/v2.0.5-86b97027bc.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/opentibia/vcpkg/downloads/LuaJIT-LuaJIT-v2.0.5.tar.gz
-- Applying patch 001-fix-build-path.patch
-- Applying patch 002-fix-crt-linkage.patch
-- Applying patch 003-do-not-set-macosx-deployment-target.patch
-- Using source at C:/opentibia/vcpkg/buildtrees/luajit/src/v2.0.5-86b97027bc.clean
-- Building x64-mingw-static-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: make -j7 -f C:/opentibia/vcpkg/buildtrees/luajit/src/v2.0.5-86b97027bc.clean/Makefile clean
    Working Directory: C:/opentibia/vcpkg/buildtrees/luajit/src/v2.0.5-86b97027bc.clean
    See logs for more information:
      C:\opentibia\vcpkg\buildtrees\luajit\clean-x64-mingw-static-debug-out.log
      C:\opentibia\vcpkg\buildtrees\luajit\clean-x64-mingw-static-debug-err.log

Call Stack (most recent call first):
  ports/luajit/portfile.cmake:41 (vcpkg_execute_build_process)
  scripts/ports.cmake:147 (include)


error: building luajit:x64-mingw-static failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+luajit
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[luajit]+Build+error
Include '[luajit] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: 66045de4d 2022-07-29 (22 hours ago)

You can also use the prefilled template from C:\opentibia\vcpkg\installed\vcpkg\issue_body.md.

**Comment by Thomas1664** [comment]
Please open a new issue for the `luajit` build failure

**Comment by dg0yt** [comment]
You need a more recent mingw-w64 toolchain, or you must opt out of feature `schannel`.
