### ISSUE TITLE
[sdl2-mixer] CMake find_package is incomplete

### ISSUE THREAD

**Issue by matthiakl** [microsoft/vcpkg#26064]
**Describe the bug**
`find_package(SDL2_mixer REQUIRED)` fails, but sdl2-mixer is installed. The project builds fine with mingw (also version 2.6.1). 
Maybe related to #25284.

**Environment**
- Github runner: windows-2022
- Compiler: MSVC 19.32.31332.0

**Expected behavior**
`SDL2_MIXER_LIBRARIES` should be set.

**Failure logs**
After installation of sdl2-mixer:
```
 sdl2-mixer provides CMake targets:
    # this is heuristically generated, and may not be correct
    find_package(SDL2_mixer CONFIG REQUIRED)
    # note: 6 additional targets are not displayed.
    target_link_libraries(main PRIVATE FLAC::FLAC MPG123::mpg123 libxmp::libxmp tremor::tremor)
```
During cmake configuration to find package:
```
-- Found SDL2: C:/vcpkg/installed/x86-windows-static/lib/SDL2.lib (found version "2.0.22") 
-- Found SDL2main: C:/vcpkg/installed/x86-windows-static/lib/manual-link/SDL2main.lib (found version "2.0.22") 
-- Found SDL2_image: C:/vcpkg/installed/x86-windows-static/debug/lib/SDL2_image.lib (found version "2.0.5") 
CMake Error at C:/Program Files/CMake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find SDL2_mixer (missing: SDL2_MIXER_LIBRARIES) (found version
  "2.6.1")
Call Stack (most recent call first):
-- Configuring incomplete, errors occurred!
  C:/Program Files/CMake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindSDL2_mixer.cmake:199 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
  CMakeLists.txt:159 (find_package)
```

**Comment by Thomas1664** [comment]
Please try to use `find_package($<IF:$<TARGET_EXISTS:SDL2_mixer::SDL2_mixer>,SDL2_mixer::SDL2_mixer,SDL2_mixer::SDL2_mixer-static>)`

Please don't close the issue if it works because the usage hint needs to be fixed in this case.

**Comment by matthiakl** [comment]
No, this doesn't change anything. CMake already stopped at the `find_package` call, so I guess the `target_link_libraries` is not evaluated.

**Comment by dg0yt** [comment]
The vcpkg usage proposal is CMake `CONFIG` and targets installed by vcpkg.
But the error message is from a local Find module (`cmake/Modules/FindSDL2_mixer.cmake`). If you want to continue with the Find module, you will need to set input variables, or even modify it.

**Comment by matthiakl** [comment]
> The vcpkg usage proposal is CMake CONFIG and targets installed by vcpkg.

Ah, sorry I misread it. After some fiddling around I got it now. Thanks for the comment.
However, I find the proposed usage update misleading, it didn't help much for resolving the problem.
