### ISSUE TITLE
[wxwidgets] Enable use of private fonts on Linux.

### ISSUE THREAD

**Issue by fishnet37222** [microsoft/vcpkg#26065]
****

**Is your feature request related to a problem? Please describe.**
I need to be able to use the private font functionality of wxWidgets on Linux.  That functionality is not enabled by default.

**Proposed solution**
I'd like the ability to specify in my project's vcpkg manifest file that I need the private font functionality of wxWidgets.

**Describe alternatives you've considered**
I tried adding pango to my vcpkg manifest file since the private font functionality requires it on Linux.  The only other alternative would be to build wxWidgets myself outside of vcpkg, which defeats the purpose of vcpkg.

**Additional context**
The [wxWidgets documentation](https://docs.wxwidgets.org/3.2/classwx_font.html#ab96266bba385bc770a40ec4c7d1ec620) gives some more information about enabling this functionality.

**Comment by Adela0814** [comment]
@fishnet37222 could you please open an issue to upstream? If upstream thinks that `wxFont `should be used in downstream projects (i.e. is public API), then it would be upstream's task to add a proper install command (and integrate with the exported CMake config, and add documentation).

**Comment by fishnet37222** [comment]
It already is public functionality.  The documentation for the [wxFont::AddPrivateFont()](https://docs.wxwidgets.org/3.2/classwx_font.html#ab96266bba385bc770a40ec4c7d1ec620) function describes how to enable it on Linux.  When I build the library myself, all I do is make sure the pango development package is installed and set "wxUSE_PRIVATE_FONTS" to ON.

**Comment by fishnet37222** [comment]
I was actually able to get it working by modifying the portfile as shown below.
![image](https://user-images.githubusercontent.com/1977106/182170116-d8f23818-15f6-4d9d-b4f6-d2ee8d963dea.png)

You might want to modify the warning message about required system packages to include libpango.
