### ISSUE TITLE
[protobuf:arm64-android] build failure

### ISSUE THREAD

**Issue by JerryYOJ** [microsoft/vcpkg#26079]
**Host Environment**
- OS: Windows 10
- Compiler: cmake

**To Reproduce**
vcpkg install protobuf:arm64-android

**Failure logs**
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Failed to open: C:\Users\elain\Downloads\Compressed\vcpkg-2022.07.25\vcpkg-bundle.json
[DEBUG] Using scripts-root: C:\Users\elain\Downloads\Compressed\vcpkg-2022.07.25\scripts
[DEBUG] Bundle config: readonly=0, usegitregistry=0, embeddedsha=nullopt
[DEBUG] Using builtin-ports: C:\Users\elain\Downloads\Compressed\vcpkg-2022.07.25\ports
[DEBUG] Using installed-root: C:\Users\elain\Downloads\Compressed\vcpkg-2022.07.25\installed
[DEBUG] Using buildtrees-root: C:\Users\elain\Downloads\Compressed\vcpkg-2022.07.25\buildtrees
[DEBUG] Using packages-root: C:\Users\elain\Downloads\Compressed\vcpkg-2022.07.25\packages
[DEBUG] Using vcpkg-root: C:\Users\elain\Downloads\Compressed\vcpkg-2022.07.25
[DEBUG] Using scripts-root: C:\Users\elain\Downloads\Compressed\vcpkg-2022.07.25\scripts
[DEBUG] Using builtin-registry: C:\Users\elain\Downloads\Compressed\vcpkg-2022.07.25\versions
[DEBUG] Using downloads-root: C:\Users\elain\Downloads\Compressed\vcpkg-2022.07.25\downloads
[DEBUG] Default binary cache path is: C:\Users\elain\AppData\Local\vcpkg\archives
Computing installation plan...
[DEBUG] Found path: C:\Program Files\CMake\bin\cmake.exe
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin\cmake.exe" --version)
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 27936: cmd_execute_and_stream_data() returned 0 after    59851 us
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin\cmake.exe" -DVCPKG_ROOT_DIR=C:/Users/elain/Downloads/Compressed/vcpkg-2022.07.25 -DPACKAGES_DIR=C:/Users/elain/Downloads/Compressed/vcpkg-2022.07.25/packages -DBUILDTREES_DIR=C:/Users/elain/Downloads/Compressed/vcpkg-2022.07.25/buildtrees -D_VCPKG_INSTALLED_DIR=C:/Users/elain/Downloads/Compressed/vcpkg-2022.07.25/installed -DDOWNLOADS=C:/Users/elain/Downloads/Compressed/vcpkg-2022.07.25/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\Users\elain\Downloads\Compressed\vcpkg-2022.07.25\buildtrees\0.vcpkg_tags.cmake")
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 27936: cmd_execute_and_stream_data() returned 0 after    52542 us
The following packages will be built and installed:
    protobuf[core]:arm64-android -> 3.21.3
Detecting compiler hash for triplet arm64-android...
[DEBUG] Found path: C:\Program Files\Git\cmd\git.exe
[DEBUG] CreateProcessW("C:\Program Files\Git\cmd\git.exe" --version)
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 27936: cmd_execute_and_stream_data() returned 0 after    36957 us
[DEBUG] CreateProcessW("C:\Users\elain\Downloads\Compressed\vcpkg-2022.07.25\downloads\tools\powershell-core-7.2.5-windows\pwsh.exe" --version)
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 27936: cmd_execute_and_stream_data() returned 0 after   236083 us
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin\cmake.exe" -DCURRENT_PORT_DIR=C:/Users/elain/Downloads/Compressed/vcpkg-2022.07.25/scripts/detect_compiler -DCURRENT_BUILDTREES_DIR=C:/Users/elain/Downloads/Compressed/vcpkg-2022.07.25/buildtrees/detect_compiler -DCURRENT_PACKAGES_DIR=C:/Users/elain/Downloads/Compressed/vcpkg-2022.07.25/packages/detect_compiler_arm64-android -D_HOST_TRIPLET=arm64-android -DCMD=BUILD -DDOWNLOADS=C:/Users/elain/Downloads/Compressed/vcpkg-2022.07.25/downloads -DTARGET_TRIPLET=arm64-android -DTARGET_TRIPLET_FILE=C:/Users/elain/Downloads/Compressed/vcpkg-2022.07.25/triplets/community/arm64-android.cmake -DVCPKG_BASE_VERSION=2022-07-21 -DVCPKG_CONCURRENCY=17 -DVCPKG_PLATFORM_TOOLSET=external "-DGIT=C:/Program Files/Git/cmd/git.exe" -DVCPKG_ROOT_DIR=C:/Users/elain/Downloads/Compressed/vcpkg-2022.07.25 -DPACKAGES_DIR=C:/Users/elain/Downloads/Compressed/vcpkg-2022.07.25/packages -DBUILDTREES_DIR=C:/Users/elain/Downloads/Compressed/vcpkg-2022.07.25/buildtrees -D_VCPKG_INSTALLED_DIR=C:/Users/elain/Downloads/Compressed/vcpkg-2022.07.25/installed -DDOWNLOADS=C:/Users/elain/Downloads/Compressed/vcpkg-2022.07.25/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\Users\elain\Downloads\Compressed\vcpkg-2022.07.25\scripts\ports.cmake")
[DEBUG] -- Configuring arm64-android
[DEBUG] CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
[DEBUG]     Command failed: C:/Users/elain/Downloads/Compressed/vcpkg-2022.07.25/downloads/tools/ninja/1.10.2-windows/ninja.exe -v
[DEBUG]     Working Directory: C:/Users/elain/Downloads/Compressed/vcpkg-2022.07.25/buildtrees/detect_compiler/arm64-android-rel/vcpkg-parallel-configure
[DEBUG]     Error code: 1
[DEBUG]     See logs for more information:
[DEBUG]       C:\Users\elain\Downloads\Compressed\vcpkg-2022.07.25\buildtrees\detect_compiler\config-arm64-android-CMakeCache.txt.log
[DEBUG]       C:\Users\elain\Downloads\Compressed\vcpkg-2022.07.25\buildtrees\detect_compiler\config-arm64-android-out.log
[DEBUG]
[DEBUG] Call Stack (most recent call first):
[DEBUG]   scripts/cmake/vcpkg_configure_cmake.cmake:299 (vcpkg_execute_required_process)
[DEBUG]   scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
[DEBUG]   scripts/ports.cmake:147 (include)
[DEBUG]
[DEBUG]
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 27936: cmd_execute_and_stream_data() returned 1 after   230308 us
[DEBUG]
[DEBUG] Compiler information tracking can be disabled by passing --feature-flags=-compilertracking
error: while detecting compiler information:
The log file content at "C:\Users\elain\Downloads\Compressed\vcpkg-2022.07.25\buildtrees\detect_compiler\stdout-arm64-android.log" is:
-- Configuring arm64-android
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: C:/Users/elain/Downloads/Compressed/vcpkg-2022.07.25/downloads/tools/ninja/1.10.2-windows/ninja.exe -v
    Working Directory: C:/Users/elain/Downloads/Compressed/vcpkg-2022.07.25/buildtrees/detect_compiler/arm64-android-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\elain\Downloads\Compressed\vcpkg-2022.07.25\buildtrees\detect_compiler\config-arm64-android-CMakeCache.txt.log
      C:\Users\elain\Downloads\Compressed\vcpkg-2022.07.25\buildtrees\detect_compiler\config-arm64-android-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:299 (vcpkg_execute_required_process)
  scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:147 (include)

error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.
[DEBUG] D:\a\_work\1\s\src\vcpkg\build.cpp(697):
[DEBUG] Time in subprocesses: 615741 us
[DEBUG] Time in parsing JSON: 98 us
[DEBUG] Time in JSON reader: 108 us
[DEBUG] Time in filesystem: 4992 us
[DEBUG] Time in loading ports: 1449 us
[DEBUG] Exiting after 663 ms (641372 us)

**Additional context**
The ninja.exe is in its directory, can be executed just fine. The build.ninja file exsits in the working dir, too.
I tried some other packages with arm64-android, but all failed with ninja error. No idea why.

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated in 1 month, if it is still an issue, please reopen this issue.
