### ISSUE TITLE
[luajit]:x64-mingw-static build failure

### ISSUE THREAD

**Issue by omeranha** [microsoft/vcpkg#26087]
**Host Environment**
- OS: Windows

**To Reproduce**
`./vcpkg install luajit[core]:x64-mingw-static`

**Failure logs**
both logs: [pastebin.com/srrvkkZM](https://pastebin.com/srrvkkZM)

Installing 1/1 luajit:x64-mingw-static...
Building luajit[core]:x64-mingw-static...
warning: -- Using community triplet x64-mingw-static. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\opentibia\vcpkg\triplets\community\x64-mingw-static.cmake
-- Using cached LuaJIT-LuaJIT-v2.0.5.tar.gz.
-- Cleaning sources at C:/opentibia/vcpkg/buildtrees/luajit/src/v2.0.5-86b97027bc.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/opentibia/vcpkg/downloads/LuaJIT-LuaJIT-v2.0.5.tar.gz
-- Applying patch 001-fix-build-path.patch
-- Applying patch 002-fix-crt-linkage.patch
-- Applying patch 003-do-not-set-macosx-deployment-target.patch
-- Using source at C:/opentibia/vcpkg/buildtrees/luajit/src/v2.0.5-86b97027bc.clean
-- Building x64-mingw-static-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
Command failed: make -j7 -f C:/opentibia/vcpkg/buildtrees/luajit/src/v2.0.5-86b97027bc.clean/Makefile clean
Working Directory: C:/opentibia/vcpkg/buildtrees/luajit/src/v2.0.5-86b97027bc.clean
See logs for more information:
C:\opentibia\vcpkg\buildtrees\luajit\clean-x64-mingw-static-debug-out.log
C:\opentibia\vcpkg\buildtrees\luajit\clean-x64-mingw-static-debug-err.log

Call Stack (most recent call first):
ports/luajit/portfile.cmake:41 (vcpkg_execute_build_process)
scripts/ports.cmake:147 (include)

error: building luajit:x64-mingw-static failed with: BUILD_FAILED
Please ensure you're using the latest port files with git pull and vcpkg update.
Then check for known issues at:
[https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+luajit](https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+luajit+sort%3Aupdated-desc)
You can submit a new issue at:
[https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[luajit]+Build+error](https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=%5Bluajit%5D+Build+error)
Include '[luajit] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
vcpkg-scripts version: https://github.com/microsoft/vcpkg/commit/66045de4dcc5da3d1029c02b606307f5951dcb22 2022-07-29 (22 hours ago)

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated in 1 month, if it is still an issue, please reopen this issue.
