### ISSUE TITLE
cmake cant find package

### ISSUE THREAD

**Issue by kaijaz123** [microsoft/vcpkg#26091]
I am building the jsoncpp library using the vcpkg install on visual studio code on windows.

I did run the following command from vcpkg instructions for setup step.
`git clone https://github.com/microsoft/vcpkg.git`
`./bootstrap-vcpkg.bat`
`vcpkg integrate install`

then continue with downloading the jsoncpp
`vcpkg install jsoncpp --triplet x64-windows`

Below is my CMakeLists.txt
`set(CMAKE_TOOLCHAIN_FILE "D:/kai/vcpkg/scripts/buildsystems/vcpkg.cmake")`
`cmake_minimum_required(VERSION 3.0.0)`
`project(cpp VERSION 0.1.0)`
`set(CMAKE_CXX_STANDARD 17)`
`include(CTest)
enable_testing()`
`find_package(jsoncpp REQUIRED)`
`add_executable(cpp main.cpp)`
`target_link_libraries(cpp PRIVATE jsoncpp_lib jsoncpp_object)`
`set(CPACK_PROJECT_NAME ${PROJECT_NAME})`
`set(CPACK_PROJECT_VERSION ${PROJECT_VERSION})`
`include(CPack)`

I have checked the installed package in vcpkg (output below):
`vcpkg list`
Output:
**`jsoncpp:x64-windows                                1.9.5            jsoncpp is an implementation of a JSON reader an`
`vcpkg-cmake-config:x64-windows                     2022-02-06#1`
`vcpkg-cmake:x64-windows                            2022-07-18`**

Error I get:
[{
	"resource": "/D:/kai/vcpkg/scripts/buildsystems/vcpkg.cmake",
	"owner": "cmake-configure-diags",
	"severity": 8,
	"message": "CMake Error at D:/kai/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package):Could not find a configuration file for package \"jsoncpp\" that is\ncompatible with requested version \"\".\n\nThe following configuration files were considered but not accepted:\n\n  D:/kai/vcpkg/installed/x64-windows/share/jsoncpp/jsoncppConfig.cmake, version: 1.9.5 (64bit)",
	"source": "CMake (_find_package)",
	"startLineNumber": 824,
	"startColumn": 1,
	"endLineNumber": 824,
	"endColumn": 10000,
	"relatedInformation": [
		{
			"startLineNumber": 15,
			"startColumn": 1,
			"endLineNumber": 15,
			"endColumn": 1000,
			"message": "In call to 'find_package' here",
			"resource": "/d:/kai/cpp/CMakeLists.txt"
		}
	]
}]

Any idea what I am doing wrong?
**Note: I did clean the CMakecache.txt file and run again but same error.

Project structure:

> D:/kai
> > cpp
> > > main.cpp
> > > CMakeLists.txt

**Comment by FrankXie05** [comment]
@kaijaz123 Thanks for submitting the issue, I didn't reproduce your problem.
![image](https://user-images.githubusercontent.com/65999885/182128521-f6a5142f-b0c4-4de0-a9d4-4b6be97dafae.png)

1. Could you please check if your build architecture matches: `x64` or `x86`.
2. I suggest you follow the standard steps to use the packages provided by `vcpkg`.  :)
See https://github.com/microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md

**Comment by FrankXie05** [comment]
@kaijaz123 Does the issue still occur?

**Comment by kaijaz123** [comment]
@FrankXie05 Hi there, sorry for late reply. I have somehow managed to solve it by reinstalling the vcpkg and clear all the cmake cache file. Thanks for you time!
