### ISSUE TITLE
Copying of dlls with applocal.ps1 in a nuget-package uses incorrect (relative) paths

### ISSUE THREAD

**Issue by meastp** [Microsoft/vcpkg#2609]
Hi,

I am using vcpkg export --nuget to make a package that I use as a dependency in my projects.

I could not get vcpkg's automatic copying of dlls to the output directory during a build in VS to the correct paths. I had to change the file scripts/buildsystems/msbuild/vcpkg.targets from:

$(IntDir)vcpkg.applocal.log

$(TLogLocation)$(ProjectName).write.1u.tlog

to

$([System.IO.Path]::Combine($(ProjectDir),$(IntDir)))vcpkg.applocal.log

$([System.IO.Path]::Combine($(ProjectDir),$(TLogLocation)))$(ProjectName).write.1u.tlog

for this to work correctly, as the relative paths were not interpreted correctly by the applocal.ps1 script.

Is this a bug or am I doing something wrong?

**Comment by Cheney-W** [comment]
@meastp, The zlibd1.dll could be copied to the output folder successfully when I used zlib port to reproduce your issue. I think this issue should be fixed, so close this issue.
