### ISSUE TITLE
[Tesseract] Windows ARM64 support

### ISSUE THREAD

**Issue by nursik** [microsoft/vcpkg#26104]
****

**Proposed solution**
Add support for arm64-windows by changing supported platform expression to `!(arm & (osx | linux))` The proposed change only for core features.

**Additional context**
The build is successful on both ARM64 and x64 based machines using **VS22 Preview 3**. The generated executables work and produce the same output on the test image.

**Comment by nursik** [comment]
Created a [PR](https://github.com/microsoft/vcpkg/pull/26242).

**Comment by Cheney-W** [comment]
This issue will be closed automatically when your PR is merged.
