### ISSUE TITLE
[oatpp*] remove setting of CMAKE_CXX_FLAGS from within the portfile

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#26100]
adds unnecessary pre-process flags overwriting the toolchain......

**Comment by JackBoosY** [comment]
I think the problem is simply overriding the `CMAKE_C_FLAGS`/ `CMAKE_CXX_FLAGS` settings in the toolchain.
The other additional flags in the toolchain do not affect this setting itself.

**Comment by Neumann-A** [comment]
You just need to remove the setting from the toolchain.

**Comment by JackBoosY** [comment]
> You just need to remove the setting from the portfile.

As far as I know our toolchain does not have `_CRT_SECURE_NO_WARNINGS` and `_WINSOCK_DEPRECATED_NO_WARNINGS` set?
Then what we should do is to convert the `-DCMAKE_CXX_FLAGS=...` passed into `vcpkg_cmake_configure `to append to `VCPKG_C_FLAGS` and `VCPKG_CXX_FLAGS`.

Right?

**Comment by Neumann-A** [comment]
I meant portfile. The ports are passing it via cmake configure.
