### ISSUE TITLE
[libvpx] Build error

### ISSUE THREAD

**Issue by david-antiteum** [microsoft/vcpkg#26102]
**Host Environment**
- OS: macOS 12.5 (Apple Silicon using arm64-osx)
- Compiler: Xcode 13.4.1

**To Reproduce**
`./vcpkg install libvpx`

**Failure logs**
```bash
Computing installation plan...
The following packages will be built and installed:
    libvpx[core]:arm64-osx -> 1.11.0#1
Detecting compiler hash for triplet arm64-osx...
Restored 0 package(s) from /Users/myname/.cache/vcpkg/archives in 23.25 us. Use --debug to see more details.
Installing 1/1 libvpx:arm64-osx...
Building libvpx[core]:arm64-osx...
warning: -- Using community triplet arm64-osx. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /Users/Shared/vcpkg/triplets/community/arm64-osx.cmake
-- Using cached webmproject-libvpx-v1.11.0.tar.gz.
-- Cleaning sources at /Users/Shared/vcpkg/buildtrees/libvpx/src/v1.11.0-389889d770.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/Shared/vcpkg/downloads/webmproject-libvpx-v1.11.0.tar.gz
-- Applying patch 0002-Fix-nasm-debug-format-flag.patch
-- Applying patch 0003-add-uwp-v142-and-v143-support.patch
-- Applying patch 0004-remove-library-suffixes.patch
-- Using source at /Users/Shared/vcpkg/buildtrees/libvpx/src/v1.11.0-389889d770.clean
-- Build info. Target: arm64-darwin20-gcc; Options: --disable-examples --disable-tools --disable-docs --disable-unit-tests --enable-pic --enable-static --disable-shared
-- Configuring libvpx for Release
-- Building libvpx for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: /bin/bash --noprofile --norc -c "make -j8"
    Working Directory: /Users/Shared/vcpkg/buildtrees/libvpx/arm64-osx-rel
    Error code: 2
    See logs for more information:
      /Users/Shared/vcpkg/buildtrees/libvpx/build-arm64-osx-rel-err.log

Call Stack (most recent call first):
  ports/libvpx/portfile.cmake:220 (vcpkg_execute_required_process)
  scripts/ports.cmake:147 (include)
```

And the content of file `/Users/Shared/vcpkg/buildtrees/libvpx/build-arm64-osx-rel-err.log` is:

```
make: *** [.DEFAULT] Error 2
```

**Additional context**
I just did a pull from vcpkg repo (and a full upgrade of all the packages) before trying to install libvpx as part of Qt 6

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Is this the only information in the error log? These information is too vague. Could you please provide the `/Users/Shared/vcpkg/buildtrees/libvpx/build-arm64-osx-rel-out.log`? I can install `libvpx` succeed locally.

**Comment by david-antiteum** [comment]
The file `/Users/Shared/vcpkg/buildtrees/libvpx/build-arm64-osx-rel-out.log` is empty. I have a few brew packages installed too. Maybe related?

**Comment by LilyWangLL** [comment]
Sorry I can't confirm, I don't have arm64-osx machine. 
cc @autoantwort, could you help take a look this issue?

**Comment by LilyWangLL** [comment]
@david-antiteum `libvpx` has been updated to version 1.12.0 by PR #26159. Could you update vcpkg and try install new version of `libvpx`?

**Comment by david-antiteum** [comment]
Same problem using version 1.12. The content of `vcpkg/buildtrees/libvpx/build-arm64-osx-rel-err.log` is:

make: *** [.DEFAULT] Error 2

**Comment by treellama** [comment]
I see the same problem when building with x64-osx host / target. mac OS 12.6 / Xcode 14.0.1

**Comment by treellama** [comment]
Removing the entire buildtree/libvpx directory and rebuilding succeeded

**Comment by LilyWangLL** [comment]
> Removing the entire buildtree/libvpx directory and rebuilding succeeded

@david-antiteum You can try this solution.

**Comment by LilyWangLL** [comment]
> @LilyWangLL All good! Thanks!

That's great! Since this issue has been fixed, so I am closing this issue for now.
