### ISSUE TITLE
[nlohmann-json] update to 3.11.0

### ISSUE THREAD

**Issue by hamzaahmedzia1** [microsoft/vcpkg#26103]
Library name: nlohmann-json

New version number: 3.11.0

Other information that may be useful (release notes, etc...)
https://github.com/nlohmann/json/releases/tag/v3.11.0

**Comment by SamVanheer** [comment]
Version 3.11.0 should be skipped since it has a bug. Version 3.11.1 should be used: https://github.com/nlohmann/json/releases/tag/v3.11.1

**Comment by falbrechtskirchinger** [comment]
Version 3.11.2 will be released soon-ish. Both 3.11.0 and 3.11.1 have bugs and should be skipped. See #26124.

**Comment by ylz-at** [comment]
Quick, quick, quick... 🤪 

std::filesystem::path support is missing due to a bug(https://github.com/nlohmann/json/pull/3240) in 3.10.5.

```c++
        #if defined(_MSC_VER) && _MSC_VER < 1940
            #undef JSON_HAS_FILESYSTEM
            #undef JSON_HAS_EXPERIMENTAL_FILESYSTEM
        #endif
```

**Comment by falbrechtskirchinger** [comment]
Working on it. ;-)
Targeting Sunday at the earliest.

Also, the `pdal` port needs an update first, if someone wants to help. It should check for the existence of `single_include/nlohmann/json_fwd.hpp` in `nlohmann-json` (will be introduced in v3.11.2) and replace `pdal/JsonFwd.hpp` (make sure to patch the file the same way `json.hpp` is patched in the portfile).

**Comment by SamVanheer** [comment]
3.11.2 is out: https://github.com/nlohmann/json/releases/tag/v3.11.2

Doesn't look like there are any show-stopper issues.

**Comment by falbrechtskirchinger** [comment]
> 3.11.2 is out: [nlohmann/json@`v3.11.2` (release)](https://github.com/nlohmann/json/releases/tag/v3.11.2)
> 
> Doesn't look like there are any show-stopper issues.

See #26124.

**Comment by SamVanheer** [comment]
Ah, thanks. I didn't realize the pull request had been updated.
