### ISSUE TITLE
How to list the optional features of a package?

### ISSUE THREAD

**Issue by patrikhuber** [Microsoft/vcpkg#2611]
I read through the documentation and a few issues/PRs here that added optional package features, and according to one of the PRs, `.\vcpkg.exe search opencv` should give a list of all the features, like

> opencv               3.4.0            computer vision library
> opencv[ffmpeg]   .............
> opencv[....]    etc.

However on my system the output is just this:

```
.\vcpkg.exe search opencv --x-full-desc
opencv               3.4.0            computer vision library

If your library is not listed, please open an issue at and/or consider making a pull request:
    https://github.com/Microsoft/vcpkg/issues
```

How can I find out what all the optional feature are that I can pass to a particular package like OpenCV?

I believe that manually opening and inspecting `vcpkg\ports\opencv\CONTROL` each time for each package is not a good solution.

**Comment by ras0219-msft** [comment]
Thanks for posting this issue!

Feature packages (as you may have found) are still off-by-default. You can pass the flag `--featurepackages` to enable them for a specific command, such as search:

```
D:\src\vcpkg> vcpkg search opencv --featurepackages
opencv               3.4.0            computer vision library
opencv[sfm]                           opencv_sfm module
opencv[cuda]                          CUDA support for opencv
opencv[ffmpeg]                        prebuilt ffmpeg support for opencv
opencv[qt]                            Qt GUI support for opencv
opencv[vtk]                           vtk support for opencv
opencv[gdcm]                          GDCM support for opencv

If your library is not listed, please open an issue at and/or consider making a pull request:
    https://github.com/Microsoft/vcpkg/issues
```

**Comment by patrikhuber** [comment]
Aah, the `--featurepackages` flag is of course needed for the `search` as well. That makes complete sense. Thank you!

(PS: Maybe during this transition phase, it would help if `--featurepackages` was listed (maybe as "experimental") if we type `vcpkg search help`?)

**Comment by ras0219-msft** [comment]
I've done one better: We've just transitioned to on-by-default ☺

**Comment by patrikhuber** [comment]
Wohoo! `git pull`-ing now ;-)
