### ISSUE TITLE
Use GetShortPathName() to workaround build path issues

### ISSUE THREAD

**Issue by taviso** [microsoft/vcpkg#26129]
This is a continuation of the discussion on https://github.com/microsoft/vcpkg/issues/21442#issuecomment-1201257428

There can be package build failures if the build directory has a space. A workaround would be to check if there is a space in the build directory, and then `SetCurrentDirectory()` to the [*short* path](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#short-vs-long-names).

You use `GetShortPathName()` to look up the short name. A short path never has spaces, and so the package should build successfully.

**Comment by Neumann-A** [comment]
That probably won't work since vcpkg needs the same path behavior as cmake. (for path replacements etc.)

**Comment by dg0yt** [comment]
> That probably won't work since vcpkg needs the same path behavior as cmake. (for path replacements etc.)

https://github.com/microsoft/vcpkg/issues/21442#issuecomment-1202647572

**Comment by StarGate-One** [comment]
This assumes the vcpkg instance is located where short (MS-DOS 8.3) path/file names exists.
From Windows 7/Windows Server 2008 R2 or newer, short names can be disable on the System Volume, also Non-System volumes are disable by default unless the user or a process turns short (MS-DOS 8.3) path/file names on.
In essence if the GetShortPathName() finds no short (MS-DOS 8.3) path/file name, it will cause some other undesirable results.

Case in hand, I have windows 11 pro and a windows 10 pro system - short (MS-DOS 8.3) path/file names are only active on the C: or system volume.
My vcpkg instance on both machines is located on the D: volume, no short (MS-DOS 8.3) path/file names exist, my S:  volume, mapped network volumes and UNC backups drive volumes also have no short (MS-DOS 8.3) path/file names.

If @taviso wants to create/submit a PR to works through all the issues and can successfully create workable libraries, binaries, source, etc for all the supported ports/features and operating systems, then I see no reason why not let him try - at worst it will not work correctly and we just not push the PR into master?

**Comment by taviso** [comment]
There are times when it won't work and then you get the same behavior as right now, a build failure. That sucks, but in a large number of cases (maybe the majority, but sure, not all!) this would make that error go away, and everything will just magically work.

Seems like there is zero downside? If it doesn't work, you get a build failure, same as today. If it does work, nice - no build failure!

I'm not volunteering though sorry, It's just a feature suggestion.

**Comment by JackBoosY** [comment]
Result after discussion with @BillyONeal :
This trick is obviously not universal.
Example: short file names no longer exist on ReFS volumes.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by JackBoosY** [comment]
We will fix this issue in the future, but not this way.
