### ISSUE TITLE
[vtk] eigen3:build failure

### ISSUE THREAD

**Issue by SPBsoftware** [microsoft/vcpkg#26123]
**Host Environment**
- Windows: x64-windows10
- Compiler: revision

**To Reproduce**
./vcpkg install vtk vtk:x65-windows 

**Failure logs**
error: building eigen3:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+eigen3
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[eigen3]+Build+error
Include '[eigen3] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: 48369f2a2 2022-08-01 (12 hours ago)

You can also use the prefilled template from C:\src\vcpkg\installed\vcpkg\issue_body.md.

what should I do about it ? I have turned of the anti-Virus protection too but the result is the same

**Comment by JackBoosY** [comment]
Please provide the full output and the failure logs mentioned in the ouput first.

Thanks.

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
