### ISSUE TITLE
[imgui] Build error

### ISSUE THREAD

**Issue by CRC32EX** [microsoft/vcpkg#26125]
**Host Environment**
- OS: Windows 11 64bit 21H2
- Compiler: Visual Studio 2022 64bit Version 17.1.6 (Visual Studio 2022 v143)

**To Reproduce**
1. Launch Visual Studio 2022
2. Create new empty C++ project
3. Create `vcpkg.json`
4. Edit `vcpkg.json`

```txt
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json",
  "name": "my-project",
  "version": "1.0.0",
  "dependencies": [
    {
      "name": "imgui",
      "features": [ "win32-binding" ]
    }
  ]
}
```

5. Run build
6. Error

**Failure logs**
- [build-log.txt](https://github.com/microsoft/vcpkg/files/9242208/build-log.txt)
- [error-logs-x64-windows.txt](https://github.com/microsoft/vcpkg/files/9242209/error-logs-x64-windows.txt)

**Additional context**
![image](https://user-images.githubusercontent.com/25629617/182376152-6d4e3c4b-3d73-4c17-937d-4e45a4945b1d.png)

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Could you also please provide the error log: `D:\ALL\vcpkg\buildtrees\imgui\install-x64-windows-dbg-out.log`?

**Comment by CRC32EX** [comment]
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/9247666/install-x64-windows-dbg-out.log)

**Comment by CRC32EX** [comment]
This issues is my fault.
I'm install Windows 11 on VMWare.
Diff files.

I found `libloaderapi.h` is changed by me. 
(I don't know why changed)

```diff
WINAPI
- LoadLibraryA(
+ LoadLibrary(
    _In_ LPCSTR lpLibFileName
    );
```

So, i undo it, this issues is solved.

```diff
```diff
WINAPI
- LoadLibrary(
+ LoadLibraryA(
    _In_ LPCSTR lpLibFileName
    );
```
