### ISSUE TITLE
OpenCV CMake targets message after installing

### ISSUE THREAD

**Issue by patrikhuber** [Microsoft/vcpkg#2612]
After `vcpkg install opencv`, there is this slightly confusing message:
```
The package opencv:x64-windows provides CMake targets:

    find_package(lib REQUIRED)
    # Note: 40 targets were omitted
    target_link_libraries(main PRIVATE ${__cvcomponent} opencv_core opencv_flann opencv_imgproc)
```

1) Shouldn't it be `find_package(OpenCV REQUIRED)` instead of `lib`?
And it may be good (same as the message after installing boost) to highlight that components can be selected, i.e.:
`find_package(OpenCV REQUIRED core imgproc)`.

2) What is `${__cvcomponent}`? I think that's a displaying error of this message - I have never seen or needed this before?

**Comment by ras0219-msft** [comment]
Thanks for posting this issue!

These messages are automatically generated based on some heuristics -- unfortunately, OpenCV's CMake integration is a bit too clever for us and this results in the output you're seeing.

I've pushed a handwritten set of usage instructions to master, so you should now see a much more useful and reasonable output :)

**Comment by patrikhuber** [comment]
I see! For an auto-generated message, it does pretty okay. But even better to have that overwritten by a handwritten one. 👍
