### ISSUE TITLE
[tensorflow] Build error

### ISSUE THREAD

**Issue by eugeneugene** [microsoft/vcpkg#26127]
**Host Environment**
- OS: Windows 21H2 19044.1826
- Compiler: VisualStudio Community 2022 17.2.6

**To Reproduce**
`./vcpkg install tensorflow:x64-windows`

**Failure logs**
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: D:/Devel/GitHub/Microsoft/VCpkg/downloads/tools/msys2/70289b324bc026d6/usr/bin/bash.exe --noprofile --norc -c "'D:/Devel/GitHub/Microsoft/VCpkg/downloads/tools/bazel/4.2.2-windows/bazel.exe' --output_user_root='D:/Devel/GitHub/Microsoft/VCpkg/buildtrees/tensorflow/.bzl' --max_idle_secs=1 build --verbose_failures --compilation_mode=dbg --features=fastbuild    --python_path='D:/Devel/GitHub/Microsoft/VCpkg/downloads/tools/msys2/70289b324bc026d6/mingw64/bin/python3.exe' --define=no_tensorflow_py_deps=true ///tensorflow:tensorflow.dll ///tensorflow:install_headers"
    Working Directory: D:/Devel/GitHub/Microsoft/VCpkg/buildtrees/tensorflow/x64-windows-dbg
    See logs for more information:
      D:\Devel\GitHub\Microsoft\VCpkg\buildtrees\tensorflow\build-x64-windows-dbg-err.log
[build-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/9242675/build-x64-windows-dbg-err.log)

Call Stack (most recent call first):
  installed/x64-windows/share/tensorflow-common/tensorflow-common.cmake:249 (vcpkg_execute_build_process)
  ports/tensorflow/portfile.cmake:5 (include)
  scripts/ports.cmake:147 (include)

**Comment by Cheney-W** [comment]
https://github.com/microsoft/vcpkg/issues/21246

**Comment by jamesjohnmcguire** [comment]
I believe I am also running into this issue.  Running the same command:

`vcpkg install tensorflow:x64-windows`

With seemingly the same output.   The contents of `C:\Util\vcpkg\buildtrees\tensorflow\config-x64-windows-dbg-out.log` is the following:

`Cannot find bazel. Please install bazel/bazelisk.`

I then install bazel/bazelisk via:

`choco install bazelisk`

Tried again from a new command line window.  Only to get the exact same results.

Bazel seems installed, typing:

`bazel version`

shows:

```
Bazelisk version: v1.15.0
WARNING: Invoking Bazel in batch mode since it is not invoked from within a workspace (below a directory having a WORKSPACE file).
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
Build label: 5.3.2
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Oct 19 18:23:26 2022 (1666203806)
Build timestamp: 1666203806
Build timestamp as int: 1666203806

```

Yes, seems very much related to #21246.

**Comment by jamesjohnmcguire** [comment]
Any movement or additional information on this issue?

**Comment by JackyYin** [comment]
Hi @eugeneugene,

>Error: Couldn't find undname.exe under C:\Program Files\Microsoft Visual Studio\2022\Community\VC, please check your VC installation and set BAZEL_VC environment variable correctly.

I think you need to set `BAZEL_VC`,  could you try this solution ?
https://github.com/bazelbuild/bazel/issues/14232#issuecomment-1007946021

**Comment by Kemler-J** [comment]
@jamesjohnmcguire  I meet the same problem,  I only installed VC2022 on my laptop, and after I install vcpkg, I build tensorflow, it shows "Cannot find bazel. Please install bazel/bazelisk." in error log.  But I had installed bazelisk with choco.
Did you finally resolve it?

**Comment by jamesjohnmcguire** [comment]
@Kemler-J I was actually trying to build FFMpeg.  I guess tensorflow is a dependency.  I ended up finding the binary libs and header files for FFMpeg somewhere else, which I then used to compile the project I was working on.  So, this became a low priority issue for me.

However, I still update vcpkg routinely and try installing the ffmpeg packages.  But no change in status, the same (I think?) errors seem to be appear.

**Comment by jimwang118** [comment]
This is a conflict issue between bazel and vs2022, could you try this solution ?
https://github.com/bazelbuild/bazel/issues/14232#issuecomment-1007946021. not vcpkg. I think this issue can be closed, if someone has new idea, please reopen this issue.

**Comment by jamesjohnmcguire** [comment]
I am now able to build FFMpeg in vcpkg, which was breaking before because of a dependency to tensorflow, I believe.  So, I do the issue is fixed.
