### ISSUE TITLE
VCPKG Failing to compile -- Multiple Packages

### ISSUE THREAD

**Issue by PhantomeAlighieri** [microsoft/vcpkg#26133]
**Describe the bug**
I cannot compile anything with VCPKG.  I've attempted through both MSYS and Visual Studio.

**Environment**
- OS:Windows 11
- Compiler: cmake-3.22.2-windows
- Visual Studio Community ninja('1.11.0')

**To Reproduce**
1. ./vcpkg install cpprestsdk[compression,core] cpprestsdk[compression,core]:x64-windows --debug
2. See error
=====================================================================================
[error.txt](https://github.com/microsoft/vcpkg/files/9244460/error.txt)
-------------------------------------------------------------------------------------------------------------------------------------------------
> I have attempted to run it through VS Code, Through CMD, Through PS.
> I have run a repair for VS Code
> I removed Visual Studio Enterprise
> I have installed Visual Studio Community
> I've read through multiple error threads and nothing they suggest fix it.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please also provide the error log: `C:\Tools\vcpkg\buildtrees\zlib\config-x64-windows-out.log`.

**Comment by PhantomeAlighieri** [comment]
> 
I actually solved it with the following:
### Installed Visual Studio Enterprise > then opened PowerShell through dev console
PS mk dir tools
PS cd tools
PS git clone https://github.com/Microsoft/vcpkg.git
PS .\vcpkg\bootstrap-vcpkg.bat
PS cd vcpkg
PS .\vcpkg integrate install
PS .\vcpkg integrate profile
PM Install-Package "vcpkg.F.Tools.vcpkg" -Source "C:\Tools\vcpkg\scripts\buildsystems"
PS .\vcpkg install cpprestsdk:x64-windows

**Comment by PhantomeAlighieri** [comment]
NGL no idea what caused the issue.  But, I was successful with that method twice (three times if you count my students success).

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
