### ISSUE TITLE
[New Port Request] < QSimpleUpdater >

### ISSUE THREAD

**Issue by ilongshan** [microsoft/vcpkg#26135]
Library name: QSimpleUpdater

Library description: QSimpleUpdater is an implementation of an auto-updating system to be used with Qt projects. It allows you to easily check for updates, download them and install them. Additionally, the QSimpleUpdater allows you to check for updates for different "modules" of your application. 

Source repository URL: https://github.com/alex-spataru/QSimpleUpdater

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by ilongshan** [comment]
Hope it will be added

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
