### ISSUE TITLE
[New Port Request] <SingleApplication>

### ISSUE THREAD

**Issue by ilongshan** [microsoft/vcpkg#26136]
Library name: SingleApplication

Library description: This is a replacement of the QtSingleApplication for Qt5 and Qt6.

Keeps the Primary Instance of your Application and kills each subsequent instances. It can (if enabled) spawn secondary (non-related to the primary) instances and can send data to the primary instance from secondary instances.

Source repository URL: https://github.com/itay-grudev/SingleApplication

Project homepage (if different from the source repository): https://itay-grudev.github.io/SingleApplication/

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by ilongshan** [comment]
Hope it will be added to vcpkg, please reopen it.

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
