### ISSUE TITLE
Meson build is missing ObjectiveC support

### ISSUE THREAD

**Issue by Naville** [microsoft/vcpkg#26147]
**Describe the bug**
Cross Compile to x64 mac from arm64-mac fails due to lack of support in meson native config

**Environment**
- OS: macOS
- Compiler: Xcode 13.x

**To Reproduce**
``vcpkg install glib --triplet=x64-osx`` on a AArch64 Mac
2. See error

**Failure logs**
[config-x64-osx-dbg-meson-log.txt.log](https://github.com/microsoft/vcpkg/files/9249054/config-x64-osx-dbg-meson-log.txt.log)
[config-x64-osx-dbg-out.log](https://github.com/microsoft/vcpkg/files/9249055/config-x64-osx-dbg-out.log)

**Additional context**
Core problem is this error during meson configuration:

```
Header <dlfcn.h> has symbol "RTLD_NEXT" : YES 
Message: Checking whether to use statfs or statvfs .. statfs
Compiler for language objc for the build machine not found.

../src/2.72.3-eda9959d65.clean/meson.build:799:2: ERROR: 'objc' compiler binary not defined in cross or native file
```

Which I suspect is due to ``z_vcpkg_meson_generate_cross_file`` in ``vcpkg_configure_meson.cmake`` but I don't know any meson to submit my own patch

I'm currently using vcpkg @ 5bb332b432e0fa3899de1a2ef8fc4c10c435408d environment listed below:

```
➜  vcpkg git:(master) ✗ sw_vers
ProductName:	macOS
ProductVersion:	12.5
BuildVersion:	21G72
➜  vcpkg git:(master) ✗ arch
arm64
➜  vcpkg git:(master) ✗ meson --version
0.63.0
➜  vcpkg git:(master) ✗ cmake --version
cmake version 3.23.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by Naville** [comment]
```
string(APPEND "${var_to_append}" "objc = 'clang'\n")
```
in ``function(z_vcpkg_append_proglist var_to_append additional_binaries)`` seems to work, should I submit a PR?

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated in 1 month, if it is still an issue, please reopen this issue.

**Comment by stevenwdv** [comment]
Hi, I just encountered this issue when trying to crosscompile. Could it be reopened?
