### ISSUE TITLE
MSMPI doesn't build

### ISSUE THREAD

**Issue by Chris-R-R** [Microsoft/vcpkg#2614]
The build seems to expect MSMPI to be installed in C:\Program Files/Microsoft MPI/Bin/mpiexec.exe but on my machine (windows 10 64 bit with VS2017) it is installed in C:\Program Files (x86)\Microsoft SDKs\MPI\

`D:\vcpkg\vcpkg>vcpkg install msmpi

The following packages will be built and installed:

    msmpi[core]:x64-windows-static

Starting package 1/1: msmpi:x64-windows-static

Building package msmpi:x64-windows-static...

-- CURRENT_INSTALLED_DIR=D:/vcpkg/vcpkg/installed/x64-windows-static

-- DOWNLOADS=D:/vcpkg/vcpkg/downloads

-- CURRENT_PACKAGES_DIR=D:/vcpkg/vcpkg/packages/msmpi_x64-windows-static

-- CURRENT_BUILDTREES_DIR=D:/vcpkg/vcpkg/buildtrees/msmpi

-- CURRENT_PORT_DIR=D:/vcpkg/vcpkg/ports/msmpi/.

-- Downloading https://download.microsoft.com/download/D/B/B/DBB64BA1-7B51-43DB-8BF1-D1FB45EACF7A/msmpisdk.msi...

-- Downloading https://download.microsoft.com/download/D/B/B/DBB64BA1-7B51-43DB-8BF1-D1FB45EACF7A/msmpisdk.msi... OK

-- Testing integrity of downloaded file...

-- Testing integrity of downloaded file... OK

-- Downloading https://download.microsoft.com/download/D/B/B/DBB64BA1-7B51-43DB-8BF1-D1FB45EACF7A/MSMpiSetup.exe...

-- Downloading https://download.microsoft.com/download/D/B/B/DBB64BA1-7B51-43DB-8BF1-D1FB45EACF7A/MSMpiSetup.exe... OK

-- Testing integrity of downloaded file...

-- Testing integrity of downloaded file... OK

CMake Error at ports/msmpi/portfile.cmake:56 (message):

    Could not find:

      C:\Program Files/Microsoft MPI/Bin/mpiexec.exe

    Please install the MSMPI redistributable package before trying to install this port.

    The appropriate installer has been downloaded to:

      D:/vcpkg/vcpkg/downloads/MSMpiSetup-8.1.exe
`

**Comment by timautry** [comment]
You only have the SDK installed. Go here [https://www.microsoft.com/en-us/download/details.aspx?id=55991[](https://www.microsoft.com/en-us/download/details.aspx?id=55991)](url) and download/install the MPI redistributable binaries (MsMPISetup.exe).

**Comment by Chris-R-R** [comment]
Ok, I was confused thinking it was enough to install either the .msi or the .exe, I didn't realize both were needed. Downloading the linked exe gives this:

CMake Error at ports/msmpi/portfile.cmake:38 (message):
    The version of the installed MSMPI redistributable packages does not match the version to be installed
      Expected version: 8.1.12438.1084
      Found version: 8.1.12438.1091
    Please upgrade the installed version on your system.
    The appropriate installer for the expected version has been downloaded to:
      D:/vcpkg/vcpkg/downloads/MSMpiSetup-8.1.exe

I was able to get it working by uninstalling this version and then installing the version under vcpkg.

**Comment by ras0219-msft** [comment]
I've also updated the `msmpi` port to accept the newer version (8.1.12438.1091) if you'd like to upgrade!
