### ISSUE TITLE
[sentry-native] Build error when building x64-windows on arm64 host

### ISSUE THREAD

**Issue by glebignatieff** [microsoft/vcpkg#26150]
**Host Environment**
- OS: Windows 11 on Apple M1 (Parallels)
- Compiler: 17.3 Preview

**To Reproduce**

0. Ensure you have an Arm64 device with Windows 11.
1. Uninstall any prior versions of Visual Studio 2022 from your Arm64 device.
2. Download and install [Visual Studio 2022 17.3 Preview 2](https://visualstudio.microsoft.com/vs/preview/) with arm64 and x64 build tools.
3. Install `sentry-native` for x64 `./vcpkg install sentry-native:x64-windows`

**Failure logs**
```
FAILED: crashpad_build/util/CMakeFiles/crashpad_util.dir/misc/capture_context_win.asm.obj ^M
ml64 -DCRASHPAD_LSS_SOURCE_EMBEDDED -DCRASHPAD_ZLIB_SOURCE_SYSTEM -DNOMINMAX -DUNICODE -DWIN32_LEAN_AND_MEAN -DZLIB_CONST -D_CRT_SECURE_NO_WARNINGS -D_HAS_EXCEPTIONS=0 -D_UNICODE -IC:\Users\glebignatev\vcpkg\buildtrees\sentry-native\src\y-native-0-bf71db22ea.clean\external\crashpad -IC:\Users\glebignatev\vcpkg\buildtrees\sentry-native\src\y-native-0-bf71db22ea.clean\external\crashpad\third_party\mini_chromium\mini_chromium -IC:\Users\glebignatev\vcpkg\buildtrees\sentry-native\src\y-native-0-bf71db22ea.clean\external\crashpad\compat\win -IC:\Users\glebignatev\vcpkg\buildtrees\sentry-native\src\y-native-0-bf71db22ea.clean\external\crashpad\third_party\mini_chromium -IC:\Users\glebignatev\vcpkg\installed\x64-windows\include /wd4201 -c -Fo crashpad_build\util\CMakeFiles\crashpad_util.dir\misc\capture_context_win.asm.obj C:\Users\glebignatev\vcpkg\buildtrees\sentry-native\src\y-native-0-bf71db22ea.clean\external\crashpad\util\misc\capture_context_win.asm^M
CreateProcess failed: The system cannot find the file specified.
```

```
ninja: fatal: ReadFile: The handle is invalid.
```

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/9250737/install-x64-windows-dbg-out.log)
[install-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/9250738/install-x64-windows-dbg-err.log)

**Additional contenxt**
I've successfully built `sentry-native` manually with `cmake` in `x64 Native Tools Command Prompt for VS 2022 Preview`.

**Comment by Cheney-W** [comment]
Please try to use below command:
`./vcpkg install sentry-native:x64-windows --host-triplet=arm64-windows`

**Comment by Cheney-W** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
