### ISSUE TITLE
[alsa] Search for alsa plugins in system directory

### ISSUE THREAD

**Issue by quyykk** [microsoft/vcpkg#26161]
****

**Is your feature request related to a problem? Please describe.**

ALSA plugins reside in a local directory in the same path as libasound.so file, called `alsa-lib`. Those plugins get loaded by libasound.so at runtime.

However, libasound.so doesn't look for the plugins inside the system lib directory, but in the current one. This means that unless you're using pure ALSA, your binary will fail to start (since vcpkg's libasound.so will try to look for Pipewire plugins inside the vcpkg lib directory where they're not).

For example, on Fedora (which switched completely to Pipewire), an application using the [alsa] port willl always fail to start because libasound.so can't find the pipewire ALSA plugin.

**Proposed solution**

[alsa] should be patched to look for plugins inside the system directory (/usr/lib). However, I do not have enough knowledge to say whether this is the correct, since the plugins are more likely than not compiled for a different version of ALSA than the one in vcpkg.

**Describe alternatives you've considered**

Provide the alsa plugins using vcpkg as well. I'm not sure how feasible this is however.

A fix for this would be highly appreciated, as this makes the [alsa] port completely unusable on Fedora (as well as on other distros which use Pipewire).

**Comment by JackBoosY** [comment]
Marked as port feature temporary.
