### ISSUE TITLE
[vcpkg] `vcpkg-init.cmd` returns a non-zero exit code on success

### ISSUE THREAD

**Issue by benmcmorran** [microsoft/vcpkg#26172]
**Describe the bug**

The `vcpkg-init.cmd` script shows usage information and returns a non-zero exit code despite successfully adding vcpkg to the shells environment.

**Environment**
- OS: WIndows 10 CMD
- Compiler: N/A

**To Reproduce**
Run these commands in a Windows CMD prompt where vcpkg is already installed.

1. `git clone https://github.com/azure-rtos/getting-started`
2. `cd getting-started\MXChip\AZ3166`
3. `vcpkg activate` As expected, this returns an error because vcpkg has not yet been initialized.
4. `%USERPROFILE%\.vcpkg\vcpkg-init.cmd` Note that usage information is displayed.
5. `echo %errorlevel%`

Expected result: `0`
Actual result: `1`

Note that even though the exit code is non-zero, running `vcpkg activate` now will succeed.

**Comment by Cheney-W** [comment]
I can't reproduce this issue in my side, my errorlevel is 0.
![image](https://user-images.githubusercontent.com/38240633/183049032-bdbdd9e0-d3f9-4056-9d4d-87649e938ed6.png)

**Comment by benmcmorran** [comment]
Looks like this only repros if vcpkg is installed, but not already initialized. Much simpler repro steps (all in Windows CMD):

1. `curl -LO https://aka.ms/vcpkg-init.cmd && .\vcpkg-init.cmd`
2. Close the terminal window and open a new Windows CMD window.
5. `%USERPROFILE%\.vcpkg\vcpkg-init.cmd`
6. `echo %errorlevel%`

![image](https://user-images.githubusercontent.com/6981284/183124756-72a789da-803f-4aba-9164-29ee035f6ade.png)

![image](https://user-images.githubusercontent.com/6981284/183124914-2f752acd-281a-4a48-9473-beba77298dd0.png)
