### ISSUE TITLE
vcpkg cmake folder names with spaces errors

### ISSUE THREAD

**Issue by beckend** [microsoft/vcpkg#26178]
**Describe the bug**
`cmake --build ...` fails with (No such file or directory).

**Environment**
- OS: Arch Linux 5.19.0
- Compiler: gcc (GCC) 12.1.1 20220730, clang version 14.0.6
- CMake 3.23.3

**To Reproduce**
1. clone https://github.com/beckend/vcpkg-bug into a folder with space in it's name, execute build with `./bug.sh`
2. See error `file failed to open for writing (No such file or directory)`
3. rename cloned folder without space, re-run `./bug.sh` without errors.

**Expected behavior**
No errors

**Failure logs**
```
CMake Error at path 1/path 2/path 3/vcpkg/scripts/buildsystems/vcpkg.cmake:515 (file):
  file failed to open for writing (No such file or directory):

    /tmp/ww\ ww\ w\ sds\ Ldsa/build/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/share/cmake/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:12 (project)
```

**Comment by BillyONeal** [comment]
What version of CMake are you using?

This looks like somehow the build output dir is missing for that write to fail?

https://github.com/microsoft/vcpkg/blob/578a0c61a4bd63a5de29fd3e1cc03dc37e440fa6/scripts/buildsystems/vcpkg.cmake#L514-L515

**Comment by beckend** [comment]
cmake version 3.23.3

try replacing the line 514 to this and it will work:
```bash
set(Z_VCPKG_MANIFEST_INSTALL_LOGFILE "${CMAKE_BINARY_DIR}/vcpkg-manifest-install.log")
```

**Comment by strega-nil-ms** [comment]
This seems to be a bug in CMake; `file(TO_NATIVE_PATH "a b")` now returns `"a\ b"`, when it should just return `"a b"`, imo.

**Comment by dg0yt** [comment]
The new `cmake_path(NATIVE_PATH <var> <out_var>)` doesn't seem to have this problem.

**Comment by dg0yt** [comment]
BTW `TO_NATIVE_PATH` doesn't seem right for values which are used in CMake commands.
