### ISSUE TITLE
vcpkg failed to install wt due to issue at  boost-system:x64-windows

### ISSUE THREAD

**Issue by mohitmukhija** [Microsoft/vcpkg#2617]
Hi,

I used the command "vcpkg install wt:x64-windows" to install wt for visual studio.

I have latest vcpkg on my system as shown in logs below. Installation logs are as below:

Starting package 1/62: boost-system:x64-windows
Building package boost-system:x64-windows...
-- CURRENT_INSTALLED_DIR=C:/vcpkg downloads/vcpkg-master/vcpkg-master/installed/x64-windows
-- DOWNLOADS=C:/vcpkg downloads/vcpkg-master/vcpkg-master/downloads
-- CURRENT_PACKAGES_DIR=C:/vcpkg downloads/vcpkg-master/vcpkg-master/packages/boost-system_x64-windows
-- CURRENT_BUILDTREES_DIR=C:/vcpkg downloads/vcpkg-master/vcpkg-master/buildtrees/boost-system
-- CURRENT_PORT_DIR=C:/vcpkg downloads/vcpkg-master/vcpkg-master/ports/boost-system/.
-- Using cached C:/vcpkg downloads/vcpkg-master/vcpkg-master/downloads/boostorg-system-boost-1.66.0.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Building x64-windows-rel
CMake Error at C:/vcpkg downloads/vcpkg-master/vcpkg-master/scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: C:/vcpkg downloads/vcpkg-master/vcpkg-master/installed/x64-windows/tools/boost-build/b2.exe;--stagedir=C:/vcpkg downloads/vcpkg-master/vcpkg-master/buildtrees/boost-system/x64-windows-rel/stage;--build-dir=C:/vcpkg downloads/vcpkg-master/vcpkg-master/buildtrees/boost-system/x64-windows-rel;--user-config=C:/vcpkg downloads/vcpkg-master/vcpkg-master/buildtrees/boost-system/x64-windows-rel/user-config.jam;-j8;--debug-configuration;--debug-building;--debug-generators;--disable-icu;--ignore-site-config;--hash;-q;-sZLIB_INCLUDE="C:/vcpkg downloads/vcpkg-master/vcpkg-master/installed/x64-windows\include";-sBZIP2_INCLUDE="C:/vcpkg downloads/vcpkg-master/vcpkg-master/installed/x64-windows\include";threadapi=win32;threading=multi;runtime-link=shared;link=shared;address-model=64;architecture=x86;toolset=msvc-14.1;-sZLIB_BINARY=zlib;-sZLIB_LIBPATH="C:/vcpkg downloads/vcpkg-master/vcpkg-master/installed/x64-windows\lib";-sBZIP2_BINARY=bz2;-sBZIP2_LIBPATH="C:/vcpkg downloads/vcpkg-master/vcpkg-master/installed/x64-windows\lib";variant=release;debug-symbols=on
    Working Directory: C:/vcpkg downloads/vcpkg-master/vcpkg-master/buildtrees/boost-system/src/system-boost-1.66.0
    See logs for more information:
      C:\vcpkg downloads\vcpkg-master\vcpkg-master\buildtrees\boost-system\build-x64-windows-rel-out.log
      C:\vcpkg downloads\vcpkg-master\vcpkg-master\buildtrees\boost-system\build-x64-windows-rel-err.log

Call Stack (most recent call first):
  C:/vcpkg downloads/vcpkg-master/vcpkg-master/installed/x64-windows/share/boost-build/boost-modular-build.cmake:188 (vcpkg_execute_required_process)
  C:/vcpkg downloads/vcpkg-master/vcpkg-master/ports/boost-system/portfile.cmake:14 (boost_modular_build)
  C:/vcpkg downloads/vcpkg-master/vcpkg-master/scripts/ports.cmake:72 (include)

Error: Building package boost-system:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-system:x64-windows
  Vcpkg version: 0.0.101-unknownhash

Additionally, attach any relevant sections from the log files above.

C:\vcpkg downloads\vcpkg-master\vcpkg-master>.\vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

Regards,
Mohit Mukhija

**Comment by NancyLi1013** [comment]
@mohitmukhija , the PR has been merged. And I can install it on my machine successfully.
Could you please help us confirm whether this issue still exists on your machine now?
If fixed, please close this issue.Thanks.
Here are the test results on my machine:
PS F:\ Files\Git\vcpkg> .\vcpkg install wt:x64-windows
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be built and installed:
  * boost-logic[core]:x64-windows
  * boost-program-options[core]:x64-windows
  * boost-signals[core]:x64-windows
  * boost-ublas[core]:x64-windows
  * cairo[core]:x64-windows
  * dirent[core]:x64-windows
  * fontconfig[core]:x64-windows
  * gettext[core]:x64-windows
  * glib[core]:x64-windows
  * harfbuzz[core,glib,ucdn]:x64-windows
  * libffi[core]:x64-windows
  * libpq[core]:x64-windows
  * pango[core]:x64-windows
  * pcre[core]:x64-windows
  * pixman[core]:x64-windows
  * ragel[core]:x64-windows
  * sqlite3[core]:x64-windows
    wt[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/18: sqlite3:x64-windows
Building package sqlite3[core]:x64-windows...
-- Downloading https://sqlite.org/2018/sqlite-amalgamation-3260000.zip...
-- Extracting source F:/ Files/Git/vcpkg/downloads/sqlite-amalgamation-3260000.zip
-- Using source at F:/ Files/Git/vcpkg/buildtrees/sqlite3/src/3260000-c1b7ab1eed
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package sqlite3[core]:x64-windows... done
Installing package sqlite3[core]:x64-windows...
Installing package sqlite3[core]:x64-windows... done
Elapsed time for package sqlite3:x64-windows: 30.35 s
Starting package 2/18: pcre:x64-windows
Building package pcre[core]:x64-windows...
-- Downloading ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.41.zip...
-- Downloading ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.41.zip... Failed. Status: 7;"Couldn't connect to server"
-- Downloading https://downloads.sourceforge.net/project/pcre/pcre/8.41/pcre-8.41.zip...
-- Extracting source F:/ Files/Git/vcpkg/downloads/pcre-8.41.zip
-- Applying patch F:/ Files/Git/vcpkg/ports/pcre/fix-option-2.patch
-- Applying patch F:/ Files/Git/vcpkg/ports/pcre/fix-arm-config-define.patch
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package pcre[core]:x64-windows... done
Installing package pcre[core]:x64-windows...
Installing package pcre[core]:x64-windows... done
Elapsed time for package pcre:x64-windows: 1.629 min
Starting package 3/18: libffi:x64-windows
Building package libffi[core]:x64-windows...
-- Downloading https://github.com/libffi/libffi/archive/v3.1.tar.gz...
-- Extracting source F:/ Files/Git/vcpkg/downloads/libffi-libffi-v3.1.tar.gz
-- Using source at F:/ Files/Git/vcpkg/buildtrees/libffi/src/v3.1-206c189062
-- Applying patch F:/ Files/Git/vcpkg/ports/libffi/export-global-data.patch
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package libffi[core]:x64-windows... done
Installing package libffi[core]:x64-windows...
Installing package libffi[core]:x64-windows... done
Elapsed time for package libffi:x64-windows: 33.27 s
Starting package 4/18: gettext:x64-windows
Building package gettext[core]:x64-windows...
-- Downloading https://ftp.gnu.org/pub/gnu/gettext/gettext-0.19.tar.gz...
-- Extracting source F:/ Files/Git/vcpkg/downloads/gettext-0.19.tar.gz
-- Applying patch 0001-Fix-macro-definitions.patch
-- Applying patch 0002-Fix-uwp-build.patch
-- Using source at F:/ Files/Git/vcpkg/buildtrees/gettext/src/0.19-4a9943ed56
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package gettext[core]:x64-windows... done
Installing package gettext[core]:x64-windows...
Installing package gettext[core]:x64-windows... done
Elapsed time for package gettext:x64-windows: 52.65 s
Starting package 5/18: glib:x64-windows
Building package glib[core]:x64-windows...
-- Downloading https://ftp.gnome.org/pub/gnome/sources/glib/2.52/glib-2.52.3.tar.xz...
-- Extracting source F:/ Files/Git/vcpkg/downloads/glib-2.52.3.tar.xz
-- Applying patch F:/ Files/Git/vcpkg/ports/glib/use-libiconv-on-windows.patch
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package glib[core]:x64-windows... done
Installing package glib[core]:x64-windows...
Installing package glib[core]:x64-windows... done
Elapsed time for package glib:x64-windows: 2.085 min
Starting package 6/18: pixman:x64-windows
Building package pixman[core]:x64-windows...
-- Downloading https://www.cairographics.org/releases/pixman-0.34.0.tar.gz...
-- Extracting source F:/ Files/Git/vcpkg/downloads/pixman-0.34.0.tar.gz
-- Using source at F:/ Files/Git/vcpkg/buildtrees/pixman/src/0.34.0-e6a74850da
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing CMake integration test
-- Performing post-build validation
-- Performing post-build validation done
Building package pixman[core]:x64-windows... done
Installing package pixman[core]:x64-windows...
Installing package pixman[core]:x64-windows... done
Elapsed time for package pixman:x64-windows: 45.26 s
Starting package 7/18: dirent:x64-windows
Building package dirent[core]:x64-windows...
-- Downloading https://github.com/tronkko/dirent/archive/1.23.1.tar.gz...
-- Extracting source F:/ Files/Git/vcpkg/downloads/tronkko-dirent-1.23.1.tar.gz
-- Using source at F:/ Files/Git/vcpkg/buildtrees/dirent/src/1.23.1-a8e14f922d
-- Up-to-date: F:/ Files/Git/vcpkg/packages/dirent_x64-windows/include
-- Installing: F:/ Files/Git/vcpkg/packages/dirent_x64-windows/include/dirent.h
-- Installing: F:/ Files/Git/vcpkg/packages/dirent_x64-windows/share/dirent/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package dirent[core]:x64-windows... done
Installing package dirent[core]:x64-windows...
Installing package dirent[core]:x64-windows... done
Elapsed time for package dirent:x64-windows: 2.866 s
Starting package 8/18: fontconfig:x64-windows
Building package fontconfig[core]:x64-windows...
-- Downloading https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.12.4.tar.gz...
-- Extracting source F:/ Files/Git/vcpkg/downloads/fontconfig-2.12.4.tar.gz
-- Applying patch fcobjtypehash.patch
-- Using source at F:/ Files/Git/vcpkg/buildtrees/fontconfig/src/2.12.4-3074630478
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing CMake integration test
-- Performing post-build validation
-- Performing post-build validation done
Building package fontconfig[core]:x64-windows... done
Installing package fontconfig[core]:x64-windows...
Installing package fontconfig[core]:x64-windows... done
Elapsed time for package fontconfig:x64-windows: 46.76 s
Starting package 9/18: cairo:x64-windows
Building package cairo[core]:x64-windows...
-- Downloading http://cairographics.org/snapshots/cairo-1.15.8.tar.xz...
-- Extracting source F:/ Files/Git/vcpkg/downloads/cairo-1.15.8.tar.xz
-- Applying patch export-only-in-shared-build.patch
-- Applying patch 0001_fix_osx_defined.patch
-- Using source at F:/ Files/Git/vcpkg/buildtrees/cairo/src/1.15.8-b8303883e7
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing CMake integration test
-- Performing post-build validation
-- Performing post-build validation done
Building package cairo[core]:x64-windows... done
Installing package cairo[core]:x64-windows...
Installing package cairo[core]:x64-windows... done
Elapsed time for package cairo:x64-windows: 1.577 min
Starting package 10/18: ragel:x64-windows
Building package ragel[core]:x64-windows...
-- Downloading http://www.colm.net/files/ragel/ragel-6.10.tar.gz...
-- Extracting source F:/ Files/Git/vcpkg/downloads/ragel-6.10.tar.gz
-- Applying patch F:/ Files/Git/vcpkg/ports/ragel/0001-Remove-unistd.h-include-1.patch
-- Applying patch F:/ Files/Git/vcpkg/ports/ragel/0002-Remove-unistd.h-include-2.patch
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package ragel[core]:x64-windows... done
Installing package ragel[core]:x64-windows...
Installing package ragel[core]:x64-windows... done
Elapsed time for package ragel:x64-windows: 1.425 min
Starting package 11/18: harfbuzz:x64-windows
Building package harfbuzz[core,glib,ucdn]:x64-windows...
-- Downloading https://github.com/harfbuzz/harfbuzz/archive/1.8.4.tar.gz...
-- Extracting source F:/ Files/Git/vcpkg/downloads/harfbuzz-harfbuzz-1.8.4.tar.gz
-- Applying patch 0001-fix-uwp-build.patch
-- Applying patch find-package-freetype-2.patch
-- Applying patch glib-cmake.patch
-- Applying patch 0001-fix-cmake-export.patch
-- Applying patch 0002-fix-macos-build.patch
-- Using source at F:/ Files/Git/vcpkg/buildtrees/harfbuzz/src/1.8.4-e7fe7a2838
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing CMake integration test
-- Performing post-build validation
-- Performing post-build validation done
Building package harfbuzz[core,glib,ucdn]:x64-windows... done
Installing package harfbuzz[core,glib,ucdn]:x64-windows...
Installing package harfbuzz[core,glib,ucdn]:x64-windows... done
Elapsed time for package harfbuzz:x64-windows: 1.57 min
Starting package 12/18: pango:x64-windows
Building package pango[core]:x64-windows...
-- Downloading http://ftp.gnome.org/pub/GNOME/sources/pango/1.40/pango-1.40.11.tar.xz...
-- Extracting source F:/ Files/Git/vcpkg/downloads/pango-1.40.11.tar.xz
-- Applying patch 0001-fix-static-symbols-export.diff
-- Using source at F:/ Files/Git/vcpkg/buildtrees/pango/src/1.40.11-f997ae867d
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package pango[core]:x64-windows... done
Installing package pango[core]:x64-windows...
Installing package pango[core]:x64-windows... done
Elapsed time for package pango:x64-windows: 31.07 s
Starting package 13/18: boost-logic:x64-windows
Building package boost-logic[core]:x64-windows...
-- Downloading https://github.com/boostorg/logic/archive/boost-1.69.0.tar.gz...
-- Extracting source F:/ Files/Git/vcpkg/downloads/boostorg-logic-boost-1.69.0.tar.gz
-- Using source at F:/ Files/Git/vcpkg/buildtrees/boost-logic/src/ost-1.69.0-3a3b3c1dc7
-- Packaging headers
-- Packaging headers done
-- Using cached F:/ Files/Git/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: F:/ Files/Git/vcpkg/packages/boost-logic_x64-windows/share/boost-logic/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-logic[core]:x64-windows... done
Installing package boost-logic[core]:x64-windows...
Installing package boost-logic[core]:x64-windows... done
Elapsed time for package boost-logic:x64-windows: 3.028 s
Starting package 14/18: libpq:x64-windows
Building package libpq[core]:x64-windows...
-- Downloading https://ftp.postgresql.org/pub/source/v9.6.3/postgresql-9.6.3.tar.bz2...
-- Extracting source F:/ Files/Git/vcpkg/downloads/postgresql-9.6.3.tar.bz2
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: F:/ Files/Git/vcpkg/packages/libpq_x64-windows/share/libpq/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package libpq[core]:x64-windows... done
Installing package libpq[core]:x64-windows...
Installing package libpq[core]:x64-windows... done
Elapsed time for package libpq:x64-windows: 1.306 min
Starting package 15/18: boost-program-options:x64-windows
Building package boost-program-options[core]:x64-windows...
-- Downloading https://github.com/boostorg/program_options/archive/boost-1.69.0.tar.gz...
-- Extracting source F:/ Files/Git/vcpkg/downloads/boostorg-program_options-boost-1.69.0.tar.gz
-- Using source at F:/ Files/Git/vcpkg/buildtrees/boost-program-options/src/ost-1.69.0-7f4dde9e4d
-- Building x64-windows-rel
-- Building x64-windows-rel done
-- Building x64-windows-dbg
-- Building x64-windows-dbg done
-- Packaging x64-windows-rel
-- Packaging x64-windows-rel done
-- Packaging x64-windows-dbg
-- Packaging x64-windows-dbg done
-- Packaging headers
-- Packaging headers done
-- Using cached F:/ Files/Git/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: F:/ Files/Git/vcpkg/packages/boost-program-options_x64-windows/share/boost-program-options/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-program-options[core]:x64-windows... done
Installing package boost-program-options[core]:x64-windows...
Installing package boost-program-options[core]:x64-windows... done
Elapsed time for package boost-program-options:x64-windows: 31.92 s
Starting package 16/18: boost-signals:x64-windows
Building package boost-signals[core]:x64-windows...
-- Downloading https://github.com/boostorg/signals/archive/boost-1.68.0.tar.gz...
-- Extracting source F:/ Files/Git/vcpkg/downloads/boostorg-signals-boost-1.68.0.tar.gz
-- Using source at F:/ Files/Git/vcpkg/buildtrees/boost-signals/src/ost-1.68.0-f206adfc9c
-- Building x64-windows-rel
-- Building x64-windows-rel done
-- Building x64-windows-dbg
-- Building x64-windows-dbg done
-- Packaging x64-windows-rel
-- Packaging x64-windows-rel done
-- Packaging x64-windows-dbg
-- Packaging x64-windows-dbg done
-- Packaging headers
-- Packaging headers done
-- Using cached F:/ Files/Git/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: F:/ Files/Git/vcpkg/packages/boost-signals_x64-windows/share/boost-signals/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-signals[core]:x64-windows... done
Installing package boost-signals[core]:x64-windows...
Installing package boost-signals[core]:x64-windows... done
Elapsed time for package boost-signals:x64-windows: 12.7 s
Starting package 17/18: boost-ublas:x64-windows
Building package boost-ublas[core]:x64-windows...
-- Downloading https://github.com/boostorg/ublas/archive/boost-1.69.0.tar.gz...
-- Extracting source F:/ Files/Git/vcpkg/downloads/boostorg-ublas-boost-1.69.0.tar.gz
-- Using source at F:/ Files/Git/vcpkg/buildtrees/boost-ublas/src/ost-1.69.0-5c52c43b77
-- Packaging headers
-- Packaging headers done
-- Using cached F:/ Files/Git/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: F:/ Files/Git/vcpkg/packages/boost-ublas_x64-windows/share/boost-ublas/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-ublas[core]:x64-windows... done
Installing package boost-ublas[core]:x64-windows...
Installing package boost-ublas[core]:x64-windows... done
Elapsed time for package boost-ublas:x64-windows: 5.025 s
Starting package 18/18: wt:x64-windows
Building package wt[core]:x64-windows...
-- Downloading https://github.com/emweb/wt/archive/4.0.5.tar.gz...
-- Extracting source F:/ Files/Git/vcpkg/downloads/emweb-wt-4.0.5.tar.gz
-- Applying patch 0002-link-glew.patch
-- Applying patch 0003-disable-boost-autolink.patch
-- Applying patch 0004-link-ssl.patch
-- Using source at F:/ Files/Git/vcpkg/buildtrees/wt/src/4.0.5-0d346e3a00
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: F:/ Files/Git/vcpkg/packages/wt_x64-windows/share/wt/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package wt[core]:x64-windows... done
Installing package wt[core]:x64-windows...
Installing package wt[core]:x64-windows... done
Elapsed time for package wt:x64-windows: 11.14 min

Total elapsed time: 25.64 min

**Comment by LarryIII** [comment]
Please open a new issue if this is still a problem for you
