### ISSUE TITLE
I couldn't use vcpkg to install imgui (or any other package)

### ISSUE THREAD

**Issue by RuoXian233** [microsoft/vcpkg#26189]
- Command: vcpkg install imgui
- OS: Windows 10 x64
- Toolchain: Visual Studio 2022 (MSVC) + standalone cmake
I got the output like this

![ScreenShot 2022-08-05 202549](https://user-images.githubusercontent.com/88079598/183076803-cc1b492e-1997-45ae-b0f9-9dd0342974cc.png)

- I noticed that the imgui version is x86, which doesn't match my platform
- But I run the command *vcpkg search imgui*, I couldn't found the x64 version of imgui

![ScreenShot 2022-08-05 203646](https://user-images.githubusercontent.com/88079598/183078565-f6629aef-b44e-40c8-adaf-adf4178eb6dc.png)

- Seems the error info told me that I should run **vcpkg update** and **git pull**, it didn't work

I tried to install boost library use vcpkg, but I've got almost the same error, the message doesn't decleare what's the reason, so what should I do?

**Comment by Osyotr** [comment]
>the message doesn't decleare what's the reason

There is a list of three possible causes right above the red wall of text.

**Comment by RuoXian233** [comment]
Oh thanks for your notice, I'd read the reasons above and checked my proxy settings. But I tried for over 10 times, luckily, it works! Seems it was the problem of my network connection
