### ISSUE TITLE
[OpenSSL] warning C4191: 'type cast': unsafe conversion from 'void (__cdecl *const )(void)' to 'OSSL_FUNC_core_gettable_params_fn (__cdecl *)'

### ISSUE THREAD

**Issue by BullyWiiPlaza** [microsoft/vcpkg#26193]
**Describe the bug**
When compiling my code using the latest OpenSSL port, I get the following warning:
```
C:\vcpkg\installed\x64-windows-static\include\openssl\core_dispatch.h(65,1): warning C4191: 'type cast': unsafe conversion from 'void (__cdecl *const )(void)' to 'OSSL_FUNC_core_gettable_params_fn (__cdecl *)'
Calling this function through the result pointer may cause your program to fail (compiling source file xxx.cpp)
```

**Environment**
- OS: Windows 11 Pro
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.32.31332 for x64

**To Reproduce**
1. `vcpkg install openssl:x64-windows-static`
2. Compile a static hello world program including `#include <openssl/evp.h>`

**Expected behavior**
No warning from within the library code occurs.

**Comment by Neumann-A** [comment]
Upstream issue.... not vcpkg.

**Comment by estape** [comment]
Got the same C4191

**Comment by sfhacker** [comment]
This is from 2022!
