### ISSUE TITLE
[<port name>] build failure

### ISSUE THREAD

**Issue by 915157600** [microsoft/vcpkg#26208]
**Host Environment**
- OS: Windows10
- Compiler: Visual Studio 2019

**To Reproduce**
vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static

**Failure logs**
Computing installation plan...
The following packages will be built and installed:
    libvpx[core]:x64-windows-static -> 1.10.0#2
    libyuv[core]:x64-windows-static -> 2021-04-15
    opus[core]:x64-windows-static -> 1.3.1#6
Detecting compiler hash for triplet x64-windows-static...
Restored 0 packages from C:\Users\Administrator\AppData\Local\vcpkg\archives in 732.7 us. Use --debug to see more details.
Starting package 1/3: libvpx:x64-windows-static
Building package libvpx[core]:x64-windows-static...
-- Using cached webmproject-libvpx-v1.10.0.tar.gz.
-- Cleaning sources at D:/Program Files/vcpkg/buildtrees/libvpx/src/v1.10.0-6771bc71c3.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Program Files/vcpkg/downloads/webmproject-libvpx-v1.10.0.tar.gz
-- Applying patch 0002-Fix-nasm-debug-format-flag.patch
-- Applying patch 0003-add-uwp-and-v142-support.patch
-- Applying patch 0004-remove-library-suffixes.patch
-- Using source at D:/Program Files/vcpkg/buildtrees/libvpx/src/v1.10.0-6771bc71c3.clean
-- Using cached msys-gzip-1.10-1-x86_64.pkg.tar.xz.
-- Using cached msys-bash-4.4.023-2-x86_64.pkg.tar.xz.
-- Using cached msys-diffutils-3.7-1-x86_64.pkg.tar.xz.
-- Using cached msys-coreutils-8.32-1-x86_64.pkg.tar.xz.
-- Using cached msys-grep-3.0-2-x86_64.pkg.tar.xz.
-- Using cached msys-sed-4.8-1-x86_64.pkg.tar.xz.
-- Using cached msys-libpcre-8.44-1-x86_64.pkg.tar.xz.
-- Using cached msys-gawk-5.1.0-1-x86_64.pkg.tar.xz.
-- Using cached msys-mpfr-4.1.0-1-x86_64.pkg.tar.zst.
-- Using cached msys-gmp-6.2.0-1-x86_64.pkg.tar.xz.
-- Using cached msys-libreadline-8.0.004-1-x86_64.pkg.tar.xz.
-- Using cached msys-ncurses-6.2-1-x86_64.pkg.tar.xz.
-- Using cached msys-pkg-config-0.29.2-4-x86_64.pkg.tar.zst.
-- Using cached msys-make-4.3-1-x86_64.pkg.tar.xz.
-- Using cached msys-libintl-0.19.8.1-1-x86_64.pkg.tar.xz.
-- Using cached msys-libiconv-1.16-2-x86_64.pkg.tar.zst.
-- Using cached msys-gcc-libs-9.3.0-1-x86_64.pkg.tar.xz.
-- Using cached msys-msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst.
-- Using msys root at D:/Program Files/vcpkg/downloads/tools/msys2/1dd5855cc99d59fc
-- Generating makefile
-- Generating MSBuild projects
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: "D:/Program Files/vcpkg/downloads/tools/msys2/1dd5855cc99d59fc/usr/bin/bash.exe" --noprofile --norc -c "make dist"
    Working Directory: D:/Program Files/vcpkg/buildtrees/libvpx/x64-windows-static
    Error code: 2
    See logs for more information:
      D:\Program Files\vcpkg\buildtrees\libvpx\generate-x64-windows-static-err.log

Call Stack (most recent call first):
  ports/libvpx/portfile.cmake:97 (vcpkg_execute_required_process)
  scripts/ports.cmake:142 (include)

Error: Building package libvpx:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libvpx
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libvpx]+Build+error
including:
  package: libvpx[core]:x64-windows-static -> 1.10.0#2
    vcpkg-tool version: 2021-11-24-48b94a6946b8a70abd21529218927fd478d02b6c
    vcpkg-scripts version: 5ddd7f026 2021-12-01 (8 months ago)

Additionally, attach any relevant sections from the log files above.

[generate-x64-windows-static-err.log](https://github.com/microsoft/vcpkg/files/9274633/generate-x64-windows-static-err.log)

**Comment by Cheney-W** [comment]
Could you please install this port with the latest vcpkg 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22?
![image](https://user-images.githubusercontent.com/38240633/183356787-be71031b-4ce8-49e7-b6c4-3ff5608b81a3.png)

**Comment by Cheney-W** [comment]
We haven't been able to repro this, if more information comes up, or this issue appears again, please reopen.
