### ISSUE TITLE
[qtwebengine] Build error

### ISSUE THREAD

**Issue by rjosh003-CS** [microsoft/vcpkg#26215]
**Host Environment**

 OS: Windows 10 Pro 21H1
 OS-built: 19043.1826
 Compiler: Visual Studio 2019 16.11.17

To Reproduce
./vcpkg install qt:x64-windows

**Failure logs**
-- Setting up python virtual environmnent...
-- Installing python packages: html5lib
-- Setting up python virtual environmnent...finished.
CMake Warning at ports/qtwebengine/portfile.cmake:83 (message):
  Buildtree path 'C:/dev/vcpkg/buildtrees/qtwebengine' is too long.

  Consider passing --x-buildtrees-root=<shortpath> to vcpkg!

  Trying to use 'C:/dev/vcpkg/buildtrees/qtwebengine/../tmp'
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)

CMake Error at ports/qtwebengine/portfile.cmake:88 (message):
  Buildtree path is too long.  Build will fail! Pass
  --x-buildtrees-root=<shortpath> to vcpkg!
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)

**Comment by Neumann-A** [comment]
not enough information..... probably latest VS2022 -> ICE. nothing vcpkg can do against. try using VS 2022 Preview or the VS 2019 toolset.

**Comment by Cheney-W** [comment]
Could you please provide the error log to us?

**Comment by BenKey** [comment]
I am seeing this as well.

**Host Environment**
- Host: x64-windows
- Compiler: MSVC 19.33.31629.0
-    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: 3691f02fb 2022-08-10 (27 hours ago)


**To Reproduce**
`vcpkg install qt[default-features]`

**Failure logs**
```
-- Using cached win_flex_bison-2.5.25.zip.
-- Setting up python virtual environmnent...
-- Installing python packages: html5lib
-- Setting up python virtual environmnent...finished.
CMake Warning at ports/qtwebengine/portfile.cmake:83 (message):
  Buildtree path 'D:/vcpkg/buildtrees/qtwebengine' is too long.

  Consider passing --x-buildtrees-root=<shortpath> to vcpkg!

  Trying to use 'D:/vcpkg/buildtrees/qtwebengine/../tmp'
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)


CMake Error at ports/qtwebengine/portfile.cmake:88 (message):
  Buildtree path is too long.  Build will fail! Pass
  --x-buildtrees-root=<shortpath> to vcpkg!
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)

[stdout-x64-windows.log](https://github.com/microsoft/vcpkg/files/9312218/stdout-x64-windows.log)
[issue_body.md](https://github.com/microsoft/vcpkg/files/9312230/issue_body.md)

**Comment by rjosh003-CS** [comment]
Hi, I got this resolved. It seems that qantlib library is a static library. For that you have to use .\vcpkg install qantlib:x64-windows-static to download. By default vcpkg install dynamic library.

**Comment by rjosh003-CS** [comment]
Qantlib is a static library so we have to use -static keyword while using vckpg install.
