### ISSUE TITLE
Link FLTK 1.4.x

### ISSUE THREAD

**Issue by fpolli** [microsoft/vcpkg#26211]
According to the FLTK docs, development and bugfix support for 1.3.8 has been closed and all active development is on 1.4.x, which is not available to pull with vcpkg at the moment

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Version 1.4.x of `fltk` is current development branch, and there are new changes everyday, It is unstable. We need wait the 1.4.x is released, then submit a PR to update `fltk` to new release version.

**Comment by dg0yt** [comment]
Does this issue need to stay open? From https://www.fltk.org/software.php aka "Download":
"Developing new FLTK applications? Use 1.3.8, the first entry in the table below."

As with any future release, 1.4.0 can become an open issue when it is released.

**Comment by LilyWangLL** [comment]
Closed this issue until 1.4.x is released.

**Comment by gvnnz** [comment]
FLTK 1.4 has been released a while ago - current version is 1.4.2 : https://github.com/fltk/fltk/releases/tag/release-1.4.2
