### ISSUE TITLE
[New Port Request] liquid-dsp

### ISSUE THREAD

**Issue by voltagex** [microsoft/vcpkg#26217]
Library name: liquid-sdr

Library description: "a free and open-source signal processing library for software-defined radios written in C. Its purpose is to provide a set of extensible DSP modules that do not rely on external dependencies or cumbersome frameworks"

Source repository URL: https://github.com/jgaeddert/liquid-dsp

Project homepage (if different from the source repository): https://liquidsdr.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by YashasviChaurasia** [comment]
@voltagex @FrankXie05 I would like to work on this issue, but could you please guide me on how to proceed?
Thank you

**Comment by FrankXie05** [comment]
@YashasviChaurasia We'd love to see more and more users getting involved. 🦾
For adding new ports : 

- Check the name against https://repology.org/ / No hits
- Check the name against Bing/Google. / No relevant hits for c9y, but c9y c++ matches.
- Check the build system of the source code
- Check the compiled usage of the new port

See: https://github.com/microsoft/vcpkg/blob/master/docs/examples/packaging-github-repos.md

For build system of the source code: 
The upstream uses make to compile(https://github.com/jgaeddert/liquid-dsp/blob/master/makefile.in), we hope to use the `cmake` compilation system to make it easier to read and manage. This means that you need cmake knowledge and add CMakeLists.tx. Of course you can also use `vcpkg_configure_make` to compile with `make`.

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
