### ISSUE TITLE
[pybind11] link failure using CMake, linking to "optimized.lib"

### ISSUE THREAD

**Issue by ahhz** [microsoft/vcpkg#26220]
**Host Environment**
- OS: Windows
- Visual Studio 2022
- CMake 3.22 

**To Reproduce**
- Install pybind11 using vcpkg

- Create project CMakeLists.txt with the following contents:
```
cmake_minimum_required(VERSION 3.20)
project(test_pybind11_project)
find_package(pybind11 CONFIG REQUIRED)
pybind11_add_module(test_pybind11_module MODULE ${CMAKE_CURRENT_SOURCE_DIR}/python.cpp)
target_link_libraries(test_pybind11_module PRIVATE pybind11::module) 
```

The python.cpp file has the following content:

```
#include <pybind11/pybind11.h>

PYBIND11_MODULE(my_module, m) {
    m.doc() = "empty bindings"; 
}
```

Configure and Generate using CMake and CMake toolchain file. `C:/Users/.../vcpkg/scripts/buildsystems/vcpkg.cmake`
Open project and Build

**Failure logs**
```
Build started...
1>------ Build started: Project: test_pybind11_module, Configuration: Debug x64 ------
1>python.cpp
1>LINK : fatal error LNK1104: cannot open file 'optimized.lib'
1>Done building project "test_pybind11_module.vcxproj" -- FAILED.
2>------ Skipped Build: Project: ALL_BUILD, Configuration: Debug x64 ------
2>Project not selected to build for this solution configuration 
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 1 skipped ==========
```
**Further Information**
I think this may be related to another recent issue that was resolved: #25163

**Comment by JackBoosY** [comment]
Confirmed.

**Comment by JackBoosY** [comment]
```
optimized.lib;F:\vcpkg\installed\x64-windows\lib\python310.lib;debug.lib;F:\vcpkg\installed\x64-windows\debug\lib\python310_d.lib
```
This should related to `find_dependency(python3)`.

**Comment by JackBoosY** [comment]
Will discuss with the upstream first.

**Comment by henryiii** [comment]
Ahh, so this is injecting the "optimized" and "debug" keywords into the libs? That's ugly. Okay, I think it's easy to fix via IMPORTED.

**Comment by ahhz** [comment]
Thanks all! Solved it for me.
