### ISSUE TITLE
[libheif] Build error

### ISSUE THREAD

**Issue by kmd18896995681** [microsoft/vcpkg#26221]
D:/workspace/QT/vcpkg/downloads/tools/msys2/9a1ec3f33446b195/mingw32/bin/pkg-config.exe
  --exists libheif failed with error code: 1

      ENV{PKG_CONFIG_PATH}: "D:/workspace/QT/vcpkg/packages/libheif_x64-windows/lib/pkgconfig;D:/workspace/QT/vcpkg/packages/libheif_x64-windows/share/pkgconfig;D:/workspace/QT/vcpkg/installed/x64-windows/lib/pkgconfig;D:/workspace/QT/vcpkg/installed/x64-windows/share/pkgconfig"
      output: Package 'libde265' has no Name: field
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:154 (z_vcpkg_fixup_pkgconfig_check_files)
  ports/libheif/portfile.cmake:26 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:147 (include)

error: building libheif:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libheif
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libheif]+Build+error
Include '[libheif] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: 9b22b40c6 2022-08-06 (2 days ago)

You can also use the prefilled template from D:\workspace\QT\vcpkg\installed\vcpkg\issue_body.md.

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated in 1 month, if it is still an issue, please reopen this issue.
