### ISSUE TITLE
Absolute path to zlib in opencv core

### ISSUE THREAD

**Issue by bredej** [Microsoft/vcpkg#2622]
I'm on Windows 7 64-bit.

Installing OpenCV creates a dependency to zlib with absolute paths. 

`vcpkg install opencv:x64-windows-static  
`

installed\x64-windows-static\share\opencv\x64\vc15\lib\OpenCVModules.cmake contains this section  

`set_target_properties(opencv_core PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:opengl32>;\$<LINK_ONLY:glu32>;\$<LINK_ONLY:ippiw>;\$<LINK_ONLY:ippicv>;C:/source/GitHub/vcpkg/installed/x64-windows-static/lib/zlib.lib;\$<LINK_ONLY:ittnotify>"
)
`

Using an exported package on another computer will most likely fail.

**Comment by cenit** [comment]
I encountered a similar problem in my PR #2764 for OpenCV, which caused me to rebuild libraries internally in OpenCV and not reuse vcpkg's ones.

**Comment by NancyLi1013** [comment]
Hi @bredej , thanks for posting this issue. The related PR https://github.com/Microsoft/vcpkg/pull/5857 has been merged to the master. So this issue should be fixed now.
