### ISSUE TITLE
[New Port Request] lttng-ust (liblttng-ust-dev), tracelogging

### ISSUE THREAD

**Issue by diegovelaz** [microsoft/vcpkg#26237]
Hi there,

I have built the following two new ports:
- **lttng-ust**: https://github.com/diegovelaz/vcpkg/commit/84d3182894fac6081b5968a4555b086ec8e00ba0
- **tracelogging**: https://github.com/diegovelaz/vcpkg/commit/e24de5e0e0db7f64b82be8ad7e24f86d33f791a2

vcpkg contribution guidelines recommends submitting an issue before a pull request, so this is it. Please let me know what else is needed before I submit a PR for each port.

Thanks!

**Comment by diegovelaz** [comment]
@bhardwajs

**Comment by JonLiu1993** [comment]
@diegovelaz, Thanks for posting this issue, you don't need to do anything more, welcome to submit pr.

**Comment by JonLiu1993** [comment]
Wait for pr merge before closing

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
