### ISSUE TITLE
log4cplus lib link failed

### ISSUE THREAD

**Issue by mybestcool** [Microsoft/vcpkg#2624]
提示以下内容，疑是 字符集(char-set) 问题

1>test-exception.obj : error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: static class log4cplus::Logger __cdecl log4cplus::Logger::getInstance(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (__imp_?getInstance@Logger@log4cplus@@SA?AV12@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)，该符号在函数 "private: __thiscall xhnet::CLogger<&char const * const xhnet::logname_trace>::CLogger<&char const * const xhnet::logname_trace>(void)" (??0?$CLogger@$1?logname_trace@xhnet@@3QBDB@xhnet@@AAE@XZ) 中被引用
1>xh-net.lib(traceback.obj) : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: static class log4cplus::Logger __cdecl log4cplus::Logger::getInstance(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (__imp_?getInstance@Logger@log4cplus@@SA?AV12@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
1>xh-net.lib(traceback.obj) : error LNK2019: 无法解析的外部符号 "__declspec(dllimport) class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > & __cdecl log4cplus::detail::get_macro_body_oss(void)" (__imp_?get_macro_body_oss@detail@log4cplus@@YAAAV?$basic_ostringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)，该符号在函数 "public: __thiscall xhnet::CCPlusPlusException::CCPlusPlusException(unsigned int,struct _EXCEPTION_POINTERS *)" (??0CCPlusPlusException@xhnet@@QAE@IPAU_EXCEPTION_POINTERS@@@Z) 中被引用
1>xh-net.lib(traceback.obj) : error LNK2019: 无法解析的外部符号 "__declspec(dllimport) void __cdecl log4cplus::detail::macro_forced_log(class log4cplus::Logger const &,int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,char const *,int,char const *)" (__imp_?macro_forced_log@detail@log4cplus@@YAXABVLogger@2@HABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PBDH2@Z)，该符号在函数 "public: __thiscall xhnet::CCPlusPlusException::CCPlusPlusException(unsigned int,struct _EXCEPTION_POINTERS *)" (??0CCPlusPlusException@xhnet@@QAE@IPAU_EXCEPTION_POINTERS@@@Z) 中被引用
1>xh-net.lib(filelog.obj) : error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: __thiscall log4cplus::PatternLayout::PatternLayout(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (__imp_??0PatternLayout@log4cplus@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)，该符号在函数 "public: bool __thiscall xhnet::CFileLogger::AddLogger(class log4cplus::Logger &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int)" (?AddLogger@CFileLogger@xhnet@@QAE_NAAVLogger@log4cplus@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z) 中被引用
1>xh-net.lib(filelog.obj) : error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __thiscall log4cplus::Logger::getName(void)const " (__imp_?getName@Logger@log4cplus@@QBEABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)，该符号在函数 "private: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall xhnet::CFileLogger::GetFileAppenderName(class log4cplus::Logger &)" (?GetFileAppenderName@CFileLogger@xhnet@@AAE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AAVLogger@log4cplus@@@Z) 中被引用
1>xh-net.lib(filelog.obj) : error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: __thiscall log4cplus::DailyRollingFileAppender::DailyRollingFileAppender(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,enum log4cplus::DailyRollingFileSchedule,bool,int,bool,bool,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (__imp_??0DailyRollingFileAppender@log4cplus@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4DailyRollingFileSchedule@1@_NH220@Z)，该符号在函数 "public: bool __thiscall xhnet::CFileLogger::AddLogger(class log4cplus::Logger &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int)" (?AddLogger@CFileLogger@xhnet@@QAE_NAAVLogger@log4cplus@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z) 中被引用
1>xh-net.lib(filelog.obj) : error LNK2001: 无法解析的外部符号 "public: virtual void __thiscall log4cplus::PatternLayout::formatAndAppend(class std::basic_ostream<char,struct std::char_traits<char> > &,class log4cplus::spi::InternalLoggingEvent const &)" (?formatAndAppend@PatternLayout@log4cplus@@UAEXAAV?$basic_ostream@DU?$char_traits@D@std@@@std@@ABVInternalLoggingEvent@spi@2@@Z)
1>C:\_work\_source\xhnet\xhnet_bitbucket\msvc12\bins\Debug\test-exception.exe : fatal error LNK1120: 7 个无法解析的外部命令

**Comment by Cheney-W** [comment]
@mybestcool , Could you provide us a detailed repro step which could reproduce your issue?

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
