### ISSUE TITLE
[cpp-base64] base64.cpp linker error

### ISSUE THREAD

**Issue by BullyWiiPlaza** [microsoft/vcpkg#26246]
**Describe the bug**
Why do I get a linker error with the `base64.cpp` file of this library? With other libraries I don't need to manually add a `*.cpp` file to my project. A workaround is `Add` -> `Existing Item...` in Visual Studio.

**Environment**
- OS: Windows 11 Pro
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.32.31332 for x64

**To Reproduce**
1. `vcpkg install cpp-base64:x64-windows`
2. Add `#include <cpp-base64/base64.h>` to the top of a source file and call `base64_encode()` somewhere in your code.
3. Compile and observe the linker error occurring:
```
LNK2019	unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl base64_encode(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,bool)" (?base64_encode@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV12@_N@Z) referenced in function [...]
```

**Expected behavior**
Including the header and compiling will work with no further action required by the developer just like how almost all other ports behave.

**Comment by JackBoosY** [comment]
Did you installed 2 or more versions of Visual Studio on your machine?

**Comment by BullyWiiPlaza** [comment]
@JackBoosY I only have 1 version installed, namely Visual Studio Enterprise 2022.

**Comment by JackBoosY** [comment]
Can you please provide a **full** reproducible test code?

**Comment by BullyWiiPlaza** [comment]
> Can you please provide a **full** reproducible test code?
Yes, it's very easy to reproduce.
```
#include <iostream>
#include <cpp-base64/base64.h>

int main()
{
    const auto encoded = base64_encode("Hello, world!");
    std::cout << "Encoded: " << encoded << std::endl;
}
```
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl base64_encode(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,bool)" (?base64_encode@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV12@_N@Z) referenced in function main	cpp-base64-linker-error-testing	C:\CppProjects\cpp-base64-linker-error-testing\cpp-base64-linker-error-testing.obj	1	
```

**Comment by JackBoosY** [comment]
I can't repro this issue with your code, and I think this is an upstream bug since vcpkg doesn't touch anything here.
Please report this to the [upstream](https://github.com/ReneNyffenegger/cpp-base64/issues) instead.

Thanks.

**Comment by BullyWiiPlaza** [comment]
Hello @JackBoosY, no, this isn't an upstream issue. vcpkg does not install the `base64.cpp` file correctly to allow automatic linking:
![image](https://user-images.githubusercontent.com/7620135/184321812-087dc178-7850-41b7-90c6-af45f8a9ebb9.png)
As comparison, I can use the `pe-parse` port, it only has headers in the include directory:
![image](https://user-images.githubusercontent.com/7620135/184321982-64cc743d-a705-4f63-838a-8ae6039e468e.png)
Unlike the `cpp-base64` port, `pe-parse` has a `pe-parse.lib` file in the `lib` folder which allows automatic linking:
![image](https://user-images.githubusercontent.com/7620135/184322071-b03d8745-8529-4dfa-8c61-89eab279e94d.png)
It would be great if `cpp-base64` could work the same way.

**Comment by JackBoosY** [comment]
I totally get what you mean.
For ports that serve source files directly, you should add them to your custom project.
