### ISSUE TITLE
PDBs for qt and boost missing

### ISSUE THREAD

**Issue by MikeGitb** [Microsoft/vcpkg#2626]
It seems that the boost and qt ports are missing pdbs (or do I have to use some command line flag when I install those libraries?).

**Comment by MikeGitb** [comment]
Will check when I've the time to rebuild.

**Comment by ras0219-msft** [comment]
Qt is likely to still be missing PDB's -- I'll post back after further investigation.

**Comment by MikeGitb** [comment]
Seems the pdbs are there (at least in debug mode). I can't verify if they are found by VS at the moment, but I'm closing this issue for now.
