### ISSUE TITLE
[xalan-c] build failure

### ISSUE THREAD

**Issue by satish-sudo** [microsoft/vcpkg#26260]
**Host Environment**
- OS: [CentOS Linux release 7.7.1908 (Core)]
- Compiler: g++ (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)

**To Reproduce**
`./vcpkg install xalan-c:x64-linux`

**Failure logs**
# ./vcpkg install xalan-c:x64-linux
The following packages will be built and installed:
    xalan-c[core]:x64-linux
Starting package 1/1: xalan-c:x64-linux
Building package xalan-c[core]:x64-linux...
-- Note: xalan-c only supports dynamic library linkage. Building dynamic library.
-- Using cached /home/satish/workspace/vcpkg/downloads/apache-xalan-c-4055bb0c58e3053b04fcd0c68fdcda8f84411213.tar.gz
-- Extracting source /home/satish/workspace/vcpkg/downloads/apache-xalan-c-4055bb0c58e3053b04fcd0c68fdcda8f84411213.tar.gz
-- Applying patch fix-win-deprecated-err.patch
-- Applying patch fix-missing-dll-error.patch
-- Applying patch fix-linux-no-bin.patch
-- Using source at /home/satish/workspace/vcpkg/buildtrees/xalan-c/src/8f84411213-46f0020fde
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: /home/satish/workspace/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v
    Working Directory: /home/satish/workspace/vcpkg/buildtrees/xalan-c/x64-linux-dbg
    See logs for more information:
      /home/satish/workspace/vcpkg/buildtrees/xalan-c/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/xalan-c/portfile.cmake:20 (vcpkg_install_cmake)
  scripts/ports.cmake:74 (include)

Error: Building package xalan-c:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: xalan-c:x64-linux
  Vcpkg version: 2019.07.18-unknownhash

Additionally, attach any relevant sections from the log files above.

**Additional context**
Log file shows undefined reference to curl functions so tried adding "-DCMAKE_DISABLE_FIND_PACKAGE_CURL=ON" in port file but no luck.
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/9294160/install-x64-linux-dbg-out.log)

**Comment by Cheney-W** [comment]
`Vcpkg version: 2019.07.18-unknownhash`

I could install this port successfully with the latest vcpkg 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22, could you please try the latest vcpkg?

**Comment by satish-sudo** [comment]
I can't use a newer version as that will update the ports as well. Let me see if I can update vcpkg with existing ports.

**Comment by satish-sudo** [comment]
With 2022.02.23 vcpkg version, build is successful. Thanks @Cheney-W . I am closing the bug.
