### ISSUE TITLE
[gdal] Build error

### ISSUE THREAD

**Issue by Dizww** [microsoft/vcpkg#26276]
**Host Environment**
- OS:  Windows
- Compiler: MSVC

**To Reproduce**
`./vcpkg install osg:x64-windows`

**Failure logs**

> Building gdal[core,curl,default-features,geos,hdf5,libspatialite,netcdf,postgresql,recommended-features]:x64-windows...
> -- Using cached OSGeo-gdal-v3.5.1.tar.gz.
> -- Cleaning sources at E:/package/vcpkg/buildtrees/gdal/src/v3.5.1-2bdd297034.clean. Use --editable to skip cleaning for the packages you specify.
> -- Extracting source E:/package/vcpkg/downloads/OSGeo-gdal-v3.5.1.tar.gz
> -- Applying patch find-link-libraries.patch
> -- Using source at E:/package/vcpkg/buildtrees/gdal/src/v3.5.1-2bdd297034.clean
> -- Found external ninja('1.10.2').
> -- Configuring x64-windows
> -- Building x64-windows-dbg
> CMake Warning at scripts/cmake/vcpkg_execute_build_process.cmake:60 (message):
>   Please ensure your system has sufficient memory.
> Call Stack (most recent call first):
>   installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
>   installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
>   ports/gdal/portfile.cmake:90 (vcpkg_cmake_install)
>   scripts/ports.cmake:147 (include)
> 
> 
> -- Restarting build without parallelism
> CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
>     Command failed: D:/Developer/CMake/bin/cmake.exe --build . --config Debug --target install -- -v -j21
>     Working Directory: E:/package/vcpkg/buildtrees/gdal/x64-windows-dbg
>     See logs for more information:
>       E:\package\vcpkg\buildtrees\gdal\install-x64-windows-dbg-out.log
>       E:\package\vcpkg\buildtrees\gdal\install-x64-windows-dbg-out-1.log
> 
> Call Stack (most recent call first):
>   installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
>   installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
>   ports/gdal/portfile.cmake:90 (vcpkg_cmake_install)
>   scripts/ports.cmake:147 (include)
> 
> 
> error: building gdal:x64-windows failed with: BUILD_FAILED
> Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
> Then check for known issues at:
>     https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+gdal
> You can submit a new issue at:
>     https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[gdal]+Build+error
> Include '[gdal] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.

**The requested files are**
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/9303026/install-x64-windows-dbg-out.log)
[install-x64-windows-dbg-out-1.log](https://github.com/microsoft/vcpkg/files/9303027/install-x64-windows-dbg-out-1.log)

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. I test this issue locally and I can reproduce it. The problem is `gdal` build failed with the high version of CMake, you can uninstall CMake which installed by yourself and use the CMake installed by vcpkg. This can make `gdal` install succeed.
