### ISSUE TITLE
Port for gmp lib

### ISSUE THREAD

**Issue by nunoplopes** [Microsoft/vcpkg#2628]
Hi,

It would be great to have the gmp lib (https://gmplib.org/) available.  It's widely used and I needed it build/work on a project.

Thank you!

**Comment by jasjuang** [comment]
gmp equivalent on windows is mpir, and vcpkg has it

**Comment by sdcb** [comment]
It's said that GMP is born for linux, and never want to port to Windows. 
And MPIR already has GMP inside, I think GMP is nothing about vcpkg, it's about the author.

**Comment by nunoplopes** [comment]
I'll give mpir a try. Didn't know about it, thanks!

**Comment by nunoplopes** [comment]
mpir seems to be good enough for the project I'm porting. closing, thanks!
