### ISSUE TITLE
[New Port Request] <SIMDIS SDK>

### ISSUE THREAD

**Issue by AkashBujju** [microsoft/vcpkg#26287]
Library name: SIMDIS SDK

Library description: The SIMDIS Software Development Kit (SDK) is an open source C++ framework providing functionality to create 3D scenes consisting of objects, whose position and state change with time, that are placed relative to a geographic map. 

Source repository URL: https://github.com/USNavalResearchLaboratory/simdissdk

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
