### ISSUE TITLE
[boost-exception] Build error

### ISSUE THREAD

**Issue by GalarzaSoft** [microsoft/vcpkg#26293]
**Host Environment**
- OS: Windows 11
- Compiler: Visual Studio 2022

**To Reproduce**
`./vcpkg install boost-exception:x64-windows-static`

**Failure logs**
Computing installation plan...
The following packages will be built and installed:
    boost-exception[core]:x64-windows-static -> 1.79.0
Detecting compiler hash for triplet x64-windows-static...
Restored 0 package(s) from C:\Users\hewha\AppData\Local\vcpkg\archives in 107.3 us. Use --debug to see more details.
Installing 1/1 boost-exception:x64-windows-static...
Building boost-exception[core]:x64-windows-static...
-- Using cached boostorg-exception-boost-1.79.0.tar.gz.
-- Cleaning sources at C:/dev/vcpkg/buildtrees/boost-exception/src/ost-1.79.0-1b4bdfb5ca.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/boostorg-exception-boost-1.79.0.tar.gz
-- Using source at C:/dev/vcpkg/buildtrees/boost-exception/src/ost-1.79.0-1b4bdfb5ca.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/dev/vcpkg/buildtrees/boost-exception/x64-windows-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\dev\vcpkg\buildtrees\boost-exception\cmake-get-vars-x64-windows-static-CMakeCache.txt.log
      C:\dev\vcpkg\buildtrees\boost-exception\cmake-get-vars-x64-windows-static-CMakeCache.txt.log
      C:\dev\vcpkg\buildtrees\boost-exception\cmake-get-vars-x64-windows-static-out.log

**Additional context**
I first saw the error while updating my libraries. I deleted the vcpkg install directory and the vcpkg one under AppData\Local and tried again resulting on the same error
[cmake-get-vars-x64-windows-static-out.log](https://github.com/microsoft/vcpkg/files/9308378/cmake-get-vars-x64-windows-static-out.log)
[cmake-get-vars-x64-windows-static-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/9308379/cmake-get-vars-x64-windows-static-CMakeCache.txt.log)
[cmake-get-vars-x64-windows-static-err.log](https://github.com/microsoft/vcpkg/files/9308380/cmake-get-vars-x64-windows-static-err.log)

**Comment by JackBoosY** [comment]
```
C:\dev\vcpkg\buildtrees\boost-exception\x64-windows-static-dbg\CMakeFiles\CMakeTmp\testCCompiler.c(11) : fatal error C1001: Internal compiler error.
```
Please provide the Visual Studio version you installed and create a feedback to [Visual Studio](https://developercommunity.visualstudio.com/report?space=62&entry=problem).

Thanks.

**Comment by PhoebeHui** [comment]
@GalarzaSoft, does this still be a problem for you?

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
