### ISSUE TITLE
[GMP / MPFR] Add CMake integration

### ISSUE THREAD

**Issue by maximecharriere** [microsoft/vcpkg#26290]
****

### Issue 
After installing GMP or MPFR via vcpkg, the `find_package(GMP)` or `find_package(MPFR)` function in CMakeList.txt doesn't work.  

I don't think it's a bug on my side, because when installing for example Boost, vcpkg tells me: 
```
The package boost is compatible with built-in CMake targets:

    find_package(Boost REQUIRED [COMPONENTS <libs>...])
    target_link_libraries(main PRIVATE Boost::boost Boost::<lib1> Boost::<lib2> ...)
```
With GMP or MPFR, this message isn't prompted.  

### Request
For the moment I'm using `FindGMP.cmake` and `FindMPFR.cmake` files from CGAL ([found here](https://github.com/CGAL/cgal/tree/master/Installation/cmake/modules)), but it would be greate if CMake could automatically find GMP and MPFR lib installed with vcpkg.

**Comment by Neumann-A** [comment]
Use FindPkgConfig!
