### ISSUE TITLE
Dependencies DLL are not copied to target directory (FreeImage)

### ISSUE THREAD

**Issue by Tryum** [Microsoft/vcpkg#2630]
**Setup**: Windows 10, vs 2017.
**Package**: FreeImage:x64-windows

For instance, linking with FreeImage will copy FreeImage.dll, but I have to manually copy some of FreeImage's dependencies : raw_r.dll and lcms2.dll ( weither I'm building in release or in debug, the app needs release dll of these libraries ).

**Comment by Mathias-Fuchs** [comment]
Having the same issue!

**Comment by NancyLi1013** [comment]
@trylle , could you please help us confirm whether the PR you make in #3643 can only fix the problem in release?
I have the same test result with lianera. And the dlls such as raw_r.dll and lcms2.dll can be only found in release directory  ../installed/x64-windows/bin.
Thanks.

**Comment by trylle** [comment]
@NancyLi1013 The PR I made should have no effect on release builds - it already built correctly there. The debug build was broken and caused FreeImage to link to release builds of libraw and lcms. #3643 fixes this. That in turn allows the dependency copy build step to locate the proper binaries for the debug configuration (raw_rd.dll, lcms2d.dll).

**Comment by NancyLi1013** [comment]
Hi trylle, thanks a lot for your clarification. @Tryum , could you help confirm whether this issue still exists on your machine? The PR in #3643 was merged, so it should be worked normally on debug builds now. 
If fixed, please close it. Thanks.
