### ISSUE TITLE
[curl][c-ares] can't link to curl built with c-ares on Apple platforms

### ISSUE THREAD

**Issue by redbaron** [microsoft/vcpkg#26307]
It looks like c-ares uses libresolv, but dependency on it is not propagated in installed CMake config files. As a result, when trying to build app using libcurl it fails to link due to missing -lresolv flag

**Host Environment**
- OS: OSX, but I suspect iOS as well

**To Reproduce**
install curl with c-ares feature with static linkage, try to use that curl in your app

**Failure logs**
```
Undefined symbols for architecture arm64:
  "_res_9_getservers", referenced from:
      _ares_init_options in libcares.a(ares_init.c.o)
  "_res_9_ninit", referenced from:
      _ares_init_options in libcares.a(ares_init.c.o)
  "_res_9_ndestroy", referenced from:
      _ares_init_options in libcares.a(ares_init.c.o)
ld: symbol(s) not found for architecture arm64
```

**Additional context**

I am using Ninja generator to build my app on OSX

**Comment by JackBoosY** [comment]
Can you please provide a sample project to reproduce this?

Thanks.

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!

**Comment by royshil** [comment]
If anyone ever gets here, this had the answer: https://github.com/c-ares/c-ares/issues/675#issuecomment-1871159204
Just link with `resolv` e.g. `-lresolv` on Mac

**Comment by dg0yt** [comment]
> Just link with `resolv` e.g. `-lresolv` on Mac

That's what the orginal post suggests.

But this is already carried in CMake config and in pkg-config.
