### ISSUE TITLE
[shogun] missing source files

### ISSUE THREAD

**Issue by Johi92** [microsoft/vcpkg#26308]
**Describe the bug**
Some of the shogun source files have not been installed with './vcpkg install shogun:x64-windows', e.g. 'shogun/util/factory.h'.

**Environment**
- Windows 10
- Compiler: MinGW-w64 i guess

**To Reproduce**
1. ./vcpkg install shogun:x64-windows

**Expected behavior**
I tried to #include <shogun/util/factory.h> in Visual Studio 17.2.6 but it could not find the file. It is missing in the buildtree too, as are several other files. Compare https://github.com/shogun-toolbox/shogun/tree/develop/src/shogun/util to the attached image. 
![image](https://user-images.githubusercontent.com/78536043/184311993-f20dce60-0810-4312-845a-7614e11c5731.png)
This might affect other source directories too, i did not do a full comparison.

**Failure logs**
Installation logs attached:
[install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/9314707/install-x64-windows-rel-out.log)
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/9314708/install-x64-windows-dbg-out.log)

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. These header files belong to branch `develop` of `shogun`, vcpkg use the release version belong to branch `master` of `shogun`. The `develop` version has some compiler problems. The release version is more stable.
