### ISSUE TITLE
[New Port Request] tensorflowlite

### ISSUE THREAD

**Issue by xiaozhuai** [microsoft/vcpkg#26313]
Library name: tensorflowlite

Library description: tensorflow lite

Source repository URL: [https://github.com/tensorflow/tensorflow](https://github.com/tensorflow/tensorflow)

**Comment by Cheney-W** [comment]
There are currently 3 ports related to `tensorflow` in vcpkg, aren't they what you expect?
tensorflow-common: https://github.com/microsoft/vcpkg/blob/master/ports/tensorflow-common/vcpkg.json
tensorflow: https://github.com/microsoft/vcpkg/blob/master/ports/tensorflow/vcpkg.json
tensorflow-cc: https://github.com/microsoft/vcpkg/blob/master/ports/tensorflow-cc/vcpkg.json

**Comment by xiaozhuai** [comment]
Thanks  @Cheney-W !
No, I want tensorflowlite only. I don't want to build other tensorflow's stuffs since I don't need it.

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by abique** [comment]
tensorflow-lite is different than tensorflow.
tensorflow is like the builder and tensorflow-lite the player.
