### ISSUE TITLE
[FluidSynth] update from 2.2.6 to 2.2.8

### ISSUE THREAD

**Issue by kcgen** [microsoft/vcpkg#26327]
Library name: **fluidsynth**

New version number: **2.2.8**

Updates since prior vcpkg version:

 - Fix file driver not working correctly on Windows (https://github.com/FluidSynth/fluidsynth/pull/1076)
 - Add a function to create a sequencer event from a midi event (https://github.com/FluidSynth/fluidsynth/issues/1078, thanks to @jimhen3ry)
 - Precompiled x86 binaries are now x87-FPU compatible (https://github.com/FluidSynth/fluidsynth/discussions/1079)
 - Fix fluidsynth not responding to SIGINT and SIGTERM when using recent SDL2 (https://github.com/FluidSynth/fluidsynth/issues/1071, thanks to @mawe42)
 - ALSA and WinMIDI drivers now pass system real-time messages on to user callback (https://github.com/FluidSynth/fluidsynth/pull/1115, thanks to @albedozero)
 - Fix FPU division by zero in fluid_player_set_tempo() (https://github.com/FluidSynth/fluidsynth/issues/1111)
 - Fix system-wide config file not loaded (https://github.com/FluidSynth/fluidsynth/issues/1118)
 - Pluseaudio driver now honors audio.periods setting (https://github.com/FluidSynth/fluidsynth/pull/1127, thanks to @pedrolcl)

Ref: https://github.com/FluidSynth/fluidsynth/releases

Thank you, vcpkg team!

**Comment by Cheney-W** [comment]
Fixed by PR https://github.com/microsoft/vcpkg/pull/25951
