### ISSUE TITLE
[llvm] Turn on LLVM_EXPORT_SYMBOLS_FOR_PLUGINS to support custom pass on Windows

### ISSUE THREAD

**Issue by zhwa** [microsoft/vcpkg#26325]
Based on this [discussion](https://discourse.llvm.org/t/how-to-create-pass-independently-on-windows/474), it is quite non-trivial to create a custom pass (which is built as a DLL) for LLVM on Windows. A suggested solution is, turn on flag ```LLVM_EXPORT_SYMBOLS_FOR_PLUGINS ``` (and perhaps a few others like ```LLVM_ENABLE_PLUGINS```) in CMake to enable this feature.

The discussion gave a hacky alternative: compile the whole LLVM project into a DLL. I think this approach isn't quite preferable.

A similar explanation can be found [here](https://stackoverflow.com/a/41980033).

**Comment by FrankXie05** [comment]
Fixed by PR https://github.com/microsoft/vcpkg/pull/23734
