### ISSUE TITLE
[eigen3] Build error

### ISSUE THREAD

**Issue by sjondavey** [microsoft/vcpkg#26331]
**Host Environment**
- OS: Windows
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.32.31332 for x86

**To Reproduce**
`./vcpkg install Eigen3`

Package: eigen3[core]:x86-windows -> 3.4.0#2
**Host Environment**
- Host: x64-windows
- Compiler: MSVC 19.32.31332.0
-    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: 48369f2a2 2022-08-01 (11 days ago)

**To Reproduce**
`vcpkg install Eigen3`

**Failure logs**
```
CMake Warning at scripts/cmake/vcpkg_buildpath_length_warning.cmake:4 (message):
  eigen3's buildsystem uses very long paths and may fail on your system.

  We recommend moving vcpkg to a short path such as 'C:\src\vcpkg' or using
  the subst command.
Call Stack (most recent call first):
  ports/eigen3/portfile.cmake:1 (vcpkg_buildpath_length_warning)
  scripts/ports.cmake:147 (include)
(My Note: I have tried this from D:\vcpkg and the error about the dependency below is the dame so I don't think this is a issue relating to directory length)

-- Using cached libeigen-eigen-3.4.0.tar.gz.
-- Cleaning sources at D:/sd/Programming/C++/vcpkg/buildtrees/eigen3/src/3.4.0-74a8d62212.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/sd/Programming/C++/vcpkg/downloads/libeigen-eigen-3.4.0.tar.gz
-- Applying patch remove_configure_checks.patch
-- Applying patch fix-vectorized-reductions-half.patch
-- Using source at D:/sd/Programming/C++/vcpkg/buildtrees/eigen3/src/3.4.0-74a8d62212.clean
CMake Error at ports/eigen3/portfile.cmake:15 (vcpkg_cmake_configure):
  Unknown CMake command "vcpkg_cmake_configure".
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)



```

**Additional context**

**Comment by Neumann-A** [comment]
`D:/sd/Programming/C++/vcpkg/` regex characters in the working dir can also be a problem.

**Comment by sjondavey** [comment]
Here is the same "issue_body.md" file but when vcpkg is installed without the special characters. i really think the dependency Unknown CMake command "vcpkg_cmake_configure". is the issue but I am unsure how to resolve this. The only other instance of this I found [here](https://github.com/microsoft/vcpkg/issues/20769) required something done on the vcpkg-cmake dependency (in that case in boost) 


Package: eigen3[core]:x86-windows -> 3.4.0#2
**Host Environment**
- Host: x64-windows
- Compiler: MSVC 19.32.31332.0
-    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: 48369f2a2 2022-08-01 (12 days ago)


**To Reproduce**
`vcpkg install Eigen3`


**Failure logs**
```
-- Using cached libeigen-eigen-3.4.0.tar.gz.
-- Cleaning sources at D:/vcpkg/buildtrees/eigen3/src/3.4.0-74a8d62212.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/libeigen-eigen-3.4.0.tar.gz
-- Applying patch remove_configure_checks.patch
-- Applying patch fix-vectorized-reductions-half.patch
-- Using source at D:/vcpkg/buildtrees/eigen3/src/3.4.0-74a8d62212.clean
CMake Error at ports/eigen3/portfile.cmake:15 (vcpkg_cmake_configure):
  Unknown CMake command "vcpkg_cmake_configure".
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)



```


**Additional context**

**Comment by JackBoosY** [comment]
> `D:/sd/Programming/C++/vcpkg/` regex characters `+` in the working dir can also be a problem.

Not related to `+`, I tested.

> Unknown CMake command "vcpkg_cmake_configure"

Please remove`vcpkg-cmake` then try again.

**Comment by sjondavey** [comment]
Ok. I did a fresh install of vcpkg and I no longer get this error. All packages seem to be installing correctly. Thanks

**Comment by timmeh87** [comment]
I had been messing around with vcpkg on ubuntu including pressing "ctrl+c" while it was running, changing my manifest, re-running, etc. I got this same error from lapack-reference : "Unknown CMake command "vcpkg_cmake_configure"." and this was the top google result for me. This thread led me to first try a manifest with ONLY the offending package, same error,  but also many other errors about not uninstalling packages properly...

Then I deleted my "vcpkg-installed" folder, re-ran the full manifest, no problem anymore.

This is a frustrating problem because no log is generated so I just wanted to add in case anyone else comes here from google with this problem.

**Comment by dg0yt** [comment]
@timmeh87 Your real issue was using an outdated version of port `vcpkg-cmake`.

**Comment by timmeh87** [comment]
First thing I tried was "vcpkg update" and it said up to date, also the virtual machine I am building on was only created yesterday, I think its more likely that I just borked the vcpkg_installed folder. Mostly I just wanted to add that deleting the "installed" folder fixed it, which might be a less invasive solution for some people than the "fresh install of vcpkg" solution above

**Comment by dg0yt** [comment]
Deleting the installed folder isn't much different from "fresh install", If the manifest refers to an outdated version of `vcpkg-cmake`, the problem should just come back. That's why it is helpful to understand the real problem.
