### ISSUE TITLE
[fftw] build failure

### ISSUE THREAD

**Issue by Rossmaxx** [microsoft/vcpkg#26333]
**Host Environment**
- Windows 11 64 bit
- Compiler: MinGW 11.2 64 bit / msvc build tools 2022

**To Reproduce**
`./vcpkg install fftw`

**Failure logs**
```
PS C:\vcpkglibs\vcpkg> git pull
Already up to date.
PS C:\vcpkglibs\vcpkg> ./vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
PS C:\vcpkglibs\vcpkg> ./vcpkg install fftw3
Computing installation plan...
The following packages will be built and installed:
    fftw3[core]:x86-windows -> 3.3.10#4
<deleted these for clarity>
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/vcpkglibs/vcpkg/buildtrees/fftw3/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkglibs\vcpkg\buildtrees\fftw3\config-x86-windows-CMakeCache.txt.log
      C:\vcpkglibs\vcpkg\buildtrees\fftw3\config-x86-windows-CMakeCache.txt.log
      C:\vcpkglibs\vcpkg\buildtrees\fftw3\config-x86-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:238 (vcpkg_execute_required_process)
  ports/fftw3/portfile.cmake:46 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)

error: building fftw3:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
```
**Additional context**
I am trying to build lmms which uses fftw3 as a dependency. vcpkg is throwing an error and is not letting me get a fftw library. tried `git pull` and `vcpkg update`. not working. 

tried to attach the log files but that's not working either.

**Comment by Rossmaxx** [comment]
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/9332716/config-x86-windows-out.log)
[config-x86-windows-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/9332717/config-x86-windows-CMakeCache.txt.log)

here are the log files

**Comment by autoantwort** [comment]
Please install a Windows SDK

**Comment by Rossmaxx** [comment]
![image](https://user-images.githubusercontent.com/74815851/184530780-fd459884-37d2-4172-988f-ebbb9c28e0a6.png)

which one of these sdks should i download?

**Comment by autoantwort** [comment]
One of the Windows SDKs. Simply select one of them.

**Comment by Rossmaxx** [comment]
ok will try later. my data is almost over so will try tmrw if i can.

**Comment by Rossmaxx** [comment]
sorry for the late response. i got it built and it works now. thanks.
