### ISSUE TITLE
[libspatialite] Build error

### ISSUE THREAD

**Issue by fujiinzukaatusi** [microsoft/vcpkg#26344]
**Host Environment**
- OS: Windows10 x64
- Compiler: cl.exe 19.29.30146 for x64
- CMake: 3.24.0

**To Reproduce**
`vcpkg install gdal:x64-windows-static `

**Failure logs**
I modified some part of the logs that originally says my project's absolute path.

Below is the copy-pasted console output.
```
[my project path]\vcpkg>vcpkg install gdal:x64-windows-static
Computing installation plan...
The following packages will be built and installed:
    gdal[core,curl,default-features,geos,hdf5,libspatialite,netcdf,postgresql,recommended-features]:x64-windows-static -> 3.5.1#5
  * libspatialite[core,freexl,geocallbacks]:x64-windows-static -> 5.0.1#7
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows-static...
Restored 0 packages from C:\Users\[my user name]\AppData\Local\vcpkg\archives in 210.1 us. Use --debug to see more details.
Starting package 1/2: libspatialite:x64-windows-static
Building package libspatialite[core,freexl,geocallbacks]:x64-windows-static...
-- Using cached libspatialite-5.0.1.tar.gz.
-- Extracting source [my project path]/vcpkg/downloads/libspatialite-5.0.1.tar.gz
-- Applying patch fix-makefiles.patch
-- Applying patch fix-linux-configure.patch
-- Applying patch gaiaconfig-msvc.patch
-- Applying patch fix-mingw.patch
-- Using source at [my project path]/vcpkg/buildtrees/libspatialite/src/atialite-5-71f24500eb.clean
-- Building and installing x64-windows-static-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/nmake.exe" /NOLOGO /G /U -f makefile.vc all install INSTALLDIR=[my project path]\\vcpkg\\packages\\libspatialite_x64-windows-static\\debug "CL_FLAGS= /I[my project path]/vcpkg/installed/x64-windows-static/debug/../include /I[my project path]/vcpkg/installed/x64-windows-static/debug/../include/libxml2 /DLIBXML_STATIC /DSQLITE_ENABLE_RTREE /DQLITE_OS_WIN=1" INST_DIR=[my project path]\\\\vcpkg\\\\packages\\\\libspatialite_x64-windows-static\\debug "LIBS_ALL=/LIBPATH:[my project path]/vcpkg/installed/x64-windows-static/debug/lib /libpath:[my project path]/vcpkg/installed/x64-windows-static/debug/lib geos_c.lib geos.lib libxml2.lib proj_d.lib ole32.lib shell32.lib tiffd.lib jpeg.lib lzma.lib libcurl-d.lib winmm.lib ws2_32.lib advapi32.lib crypt32.lib sqlite3.lib zlibd.lib freexl.lib charset.lib iconv.lib iconv.lib charset.lib" LINK_FLAGS=/debug
    Working Directory: [my project path]/vcpkg/buildtrees/libspatialite/x64-windows-static-dbg
    See logs for more information:
      [my project path]\vcpkg\buildtrees\libspatialite\install-x64-windows-static-dbg-out.log
      [my project path]\vcpkg\buildtrees\libspatialite\install-x64-windows-static-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_nmake.cmake:118 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_nmake.cmake:49 (vcpkg_build_nmake)
  ports/libspatialite/portfile.cmake:83 (vcpkg_install_nmake)
  scripts/ports.cmake:147 (include)


error: building libspatialite:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libspatialite
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libspatialite]+Build+error
including:
  package: libspatialite[core,freexl,geocallbacks]:x64-windows-static -> 5.0.1#7
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: d293ac220 2022-08-12 (2 days ago)

Additionally, attach any relevant sections from the log files above.

```

Following are the logs mentioned in the console output.
[install-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/9333482/install-x64-windows-static-dbg-out.log)
[install-x64-windows-static-dbg-err.log](https://github.com/microsoft/vcpkg/files/9333483/install-x64-windows-static-dbg-err.log)

**Additional context**
I once tried to upgrade OpenSceneGraph package but failed for failing to build gdal package.
I tried to individually install gdal pakcage, then I got this issue.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Could your install English language package on Visual Studio and rebuild this port?

**Comment by fujiinzukaatusi** [comment]
Hello, Lily. Thank you for response.

Firstly, I have to apologise to have already discarded the original environment in which I met this issue. So I cloned new vcpkg repository and I tried to install gdal package again after changing the language setting. I'll share the error that still happened then.

Console output.
````
[my project path]\vcpkg>vcpkg install gdal[core,libspatialite]:x64-windows-static
Computing installation plan...
The following packages will be built and installed:
    gdal[core,libspatialite]:x64-windows-static -> 3.5.1#5
  * libspatialite[core,freexl,geocallbacks]:x64-windows-static -> 5.0.1#7
  * vcpkg-pkgconfig-get-modules[core]:x64-windows -> 2022-02-10#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows-static...
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\[my user name]\AppData\Local\vcpkg\archives in 347.1 us. Use --debug to see more details.
Installing 1/3 libspatialite:x64-windows-static...
Building libspatialite[core,freexl,geocallbacks]:x64-windows-static...
-- Using cached libspatialite-5.0.1.tar.gz.
-- Cleaning sources at [my project path]/vcpkg/buildtrees/libspatialite/src/atialite-5-71f24500eb.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source [my project path]/vcpkg/downloads/libspatialite-5.0.1.tar.gz
-- Applying patch fix-makefiles.patch
-- Applying patch fix-linux-configure.patch
-- Applying patch gaiaconfig-msvc.patch
-- Applying patch fix-mingw.patch
-- Using source at [my project path]/vcpkg/buildtrees/libspatialite/src/atialite-5-71f24500eb.clean
-- Building and installing x64-windows-static-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/nmake.exe" /NOLOGO /G /U -f makefile.vc all install INSTALLDIR=[my project path]\\vcpkg\\packages\\libspatialite_x64-windows-static\\debug "CL_FLAGS= /I[my project path]/vcpkg/installed/x64-windows-static/debug/../include /I[my project path]/vcpkg/installed/x64-windows-static/debug/../include/libxml2 /DLIBXML_STATIC /DSQLITE_ENABLE_RTREE /DQLITE_OS_WIN=1" INST_DIR=[my project path]\\\\vcpkg\\\\packages\\\\libspatialite_x64-windows-static\\debug "LIBS_ALL=/LIBPATH:[my project path]/vcpkg/installed/x64-windows-static/debug/lib /libpath:[my project path]/vcpkg/installed/x64-windows-static/debug/lib geos_c.lib geos.lib libxml2.lib proj_d.lib ole32.lib shell32.lib tiffd.lib jpeg.lib lzma.lib libcurl-d.lib winmm.lib ws2_32.lib advapi32.lib crypt32.lib sqlite3.lib zlibd.lib freexl.lib charset.lib iconv.lib iconv.lib charset.lib" LINK_FLAGS=/debug
    Working Directory: [my project path]/vcpkg/buildtrees/libspatialite/x64-windows-static-dbg
    See logs for more information:
      [my project path]\vcpkg\buildtrees\libspatialite\install-x64-windows-static-dbg-out.log
      [my project path]\vcpkg\buildtrees\libspatialite\install-x64-windows-static-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_nmake.cmake:118 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_nmake.cmake:49 (vcpkg_build_nmake)
  ports/libspatialite/portfile.cmake:83 (vcpkg_install_nmake)
  scripts/ports.cmake:147 (include)


error: building libspatialite:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libspatialite
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libspatialite]+Build+error
Include '[libspatialite] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: 4217fee51 2022-08-17 (13 hours ago)

You can also use the prefilled template from [my project path]\vcpkg\installed\vcpkg\issue_body.md.

````

.log files.
[install-x64-windows-static-dbg-err.log](https://github.com/microsoft/vcpkg/files/9374049/install-x64-windows-static-dbg-err.log)
[install-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/9374073/install-x64-windows-static-dbg-out.log)

Hope this helps.

**Comment by smarttigerfly** [comment]
### Host Environment

- OS: windows11
- Compiler: Visual Studio Community 2022

### Failure log

```
.\vcpkg.exe install mapnik[input-gdal,input-sqlite,utility-pgsql2sqlite]:x64-windows --recurse
Computing installation plan...
The following packages will be built and installed:
  * gdal[core,curl,default-features,geos,hdf5,libspatialite,netcdf,postgresql,recommended-features]:x64-windows -> 3.5.1#6
  * libgeotiff[core]:x64-windows -> 1.7.1#1
  * libodb[core]:x64-windows -> 2.4.0#8
  * libodb-pgsql[core]:x64-windows -> 2.4.0#6
  * libspatialite[core,freexl,geocallbacks]:x64-windows -> 5.0.1#8
  * libxml2[core]:x64-windows -> 2.9.14#1
    mapnik[core,grid-renderer,input-gdal,input-sqlite,jpeg,png,proj,svg-renderer,tiff,utility-pgsql2sqlite,webp]:x64-windows -> 2022-01-28#2
  * netcdf-c[core,dap,hdf5,nczarr,netcdf-4,platform-default-features]:x64-windows -> 4.8.1#2
  * pkgconf[core]:x64-windows -> 1.8.0#3
  * proj[core,net,tiff]:x64-windows -> 9.1.0
  * qhull[core]:x64-windows -> 8.0.2#3
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 1 package(s) from C:\Users\wangxiaohu\AppData\Local\vcpkg\archives in 211.6 ms. Use --debug to see more details.

......

Installing 4/11 libspatialite:x64-windows...
Building libspatialite[core,freexl,geocallbacks]:x64-windows...
-- Downloading https://www.gaia-gis.it/gaia-sins/libspatialite-sources/libspatialite-5.0.1.tar.gz -> libspatialite-5.0.1.tar.gz...

-- Using cached libspatialite-5.0.1.tar.gz.
-- Extracting source E:/vcpkg/downloads/libspatialite-5.0.1.tar.gz
-- Applying patch fix-makefiles.patch
-- Applying patch fix-linux-configure.patch
-- Applying patch gaiaconfig-msvc.patch
-- Applying patch fix-mingw.patch
-- Using source at E:/vcpkg/buildtrees/libspatialite/src/atialite-5-71f24500eb.clean
CMake Error at installed/x64-windows/share/vcpkg-pkgconfig-get-modules/x_vcpkg_pkgconfig_get_modules.cmake:56 (message):
  extra arguments passed to x_vcpkg_pkgconfig_get_modules: CFLAGS
Call Stack (most recent call first):
  ports/libspatialite/portfile.cmake:49 (x_vcpkg_pkgconfig_get_modules)
  scripts/ports.cmake:147 (include)


error: building libspatialite:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libspatialite
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libspatialite]+Build+error
Include '[libspatialite] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-09-20-522aa94e9d261c7d7b2f079bf2591ca62df5c714
    vcpkg-scripts version: 86eb754bc 2022-09-22 (16 hours ago)


Please use the prefilled template from E:\vcpkg\installed\vcpkg\issue_body.md when reporting your issue.
```

**Comment by dg0yt** [comment]
You must upgrade your installed packages: `vcpkg upgrade --no-dry-run`.

**Comment by fujiinzukaatusi** [comment]
@fujiinzukaatusi I tried that building after installing English lang pack for VS and changing the lang setting to use it.
Also I confirmed any file paths don't contain Asian characters( even in ``[my project path]``).

**Comment by fujiinzukaatusi** [comment]
> Hello, Lily. Thank you for response.
> 
> Firstly, I have to apologise to have already discarded the original environment in which I met this issue. So I cloned new vcpkg repository and I tried to install gdal package again after changing the language setting. I'll share the error that still happened then.
> 
> Console output.
> 
> ```
> [my project path]\vcpkg>vcpkg install gdal[core,libspatialite]:x64-windows-static
> Computing installation plan...
> The following packages will be built and installed:
>     gdal[core,libspatialite]:x64-windows-static -> 3.5.1#5
>   * libspatialite[core,freexl,geocallbacks]:x64-windows-static -> 5.0.1#7
>   * vcpkg-pkgconfig-get-modules[core]:x64-windows -> 2022-02-10#1
> Additional packages (*) will be modified to complete this operation.
> Detecting compiler hash for triplet x64-windows-static...
> Detecting compiler hash for triplet x64-windows...
> Restored 0 package(s) from C:\Users\[my user name]\AppData\Local\vcpkg\archives in 347.1 us. Use --debug to see more details.
> Installing 1/3 libspatialite:x64-windows-static...
> Building libspatialite[core,freexl,geocallbacks]:x64-windows-static...
> -- Using cached libspatialite-5.0.1.tar.gz.
> -- Cleaning sources at [my project path]/vcpkg/buildtrees/libspatialite/src/atialite-5-71f24500eb.clean. Use --editable to skip cleaning for the packages you specify.
> -- Extracting source [my project path]/vcpkg/downloads/libspatialite-5.0.1.tar.gz
> -- Applying patch fix-makefiles.patch
> -- Applying patch fix-linux-configure.patch
> -- Applying patch gaiaconfig-msvc.patch
> -- Applying patch fix-mingw.patch
> -- Using source at [my project path]/vcpkg/buildtrees/libspatialite/src/atialite-5-71f24500eb.clean
> -- Building and installing x64-windows-static-dbg
> CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
>     Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/nmake.exe" /NOLOGO /G /U -f makefile.vc all install INSTALLDIR=[my project path]\\vcpkg\\packages\\libspatialite_x64-windows-static\\debug "CL_FLAGS= /I[my project path]/vcpkg/installed/x64-windows-static/debug/../include /I[my project path]/vcpkg/installed/x64-windows-static/debug/../include/libxml2 /DLIBXML_STATIC /DSQLITE_ENABLE_RTREE /DQLITE_OS_WIN=1" INST_DIR=[my project path]\\\\vcpkg\\\\packages\\\\libspatialite_x64-windows-static\\debug "LIBS_ALL=/LIBPATH:[my project path]/vcpkg/installed/x64-windows-static/debug/lib /libpath:[my project path]/vcpkg/installed/x64-windows-static/debug/lib geos_c.lib geos.lib libxml2.lib proj_d.lib ole32.lib shell32.lib tiffd.lib jpeg.lib lzma.lib libcurl-d.lib winmm.lib ws2_32.lib advapi32.lib crypt32.lib sqlite3.lib zlibd.lib freexl.lib charset.lib iconv.lib iconv.lib charset.lib" LINK_FLAGS=/debug
>     Working Directory: [my project path]/vcpkg/buildtrees/libspatialite/x64-windows-static-dbg
>     See logs for more information:
>       [my project path]\vcpkg\buildtrees\libspatialite\install-x64-windows-static-dbg-out.log
>       [my project path]\vcpkg\buildtrees\libspatialite\install-x64-windows-static-dbg-err.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_build_nmake.cmake:118 (vcpkg_execute_build_process)
>   scripts/cmake/vcpkg_install_nmake.cmake:49 (vcpkg_build_nmake)
>   ports/libspatialite/portfile.cmake:83 (vcpkg_install_nmake)
>   scripts/ports.cmake:147 (include)
> 
> 
> error: building libspatialite:x64-windows-static failed with: BUILD_FAILED
> Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
> Then check for known issues at:
>     https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libspatialite
> You can submit a new issue at:
>     https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libspatialite]+Build+error
> Include '[libspatialite] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
>     vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
>     vcpkg-scripts version: 4217fee51 2022-08-17 (13 hours ago)
> 
> You can also use the prefilled template from [my project path]\vcpkg\installed\vcpkg\issue_body.md.
> ```
> 
> .log files. [install-x64-windows-static-dbg-err.log](https://github.com/microsoft/vcpkg/files/9374049/install-x64-windows-static-dbg-err.log) [install-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/9374073/install-x64-windows-static-dbg-out.log)
> 
> Hope this helps.

**Comment by fujiinzukaatusi** [comment]
Sorry, I once closed the issue by misoperation. Never mind it.

**Comment by Cheney-W** [comment]
In general, the required running environment of vcpkg on Windows is as follows: (installed by Visual Studio Installer)
1. English language packages.
2. Desktop development with c++
![image](https://user-images.githubusercontent.com/38240633/218952720-e3f7ae44-a3fc-425e-b1a2-fbe154c8558f.png)
3. Git for windows.
4. Debugging Tools for Windows (installed by Windows Software Development Kit)
![image](https://user-images.githubusercontent.com/38240633/218953151-9b00d7b0-cdb7-450b-9858-83b03af6e1a6.png)

Please check if you have installed them.
