### ISSUE TITLE
[libsquish] build failure

### ISSUE THREAD

**Issue by bugproof** [microsoft/vcpkg#26343]
**Host Environment**
- OS: Windows
- Compiler: MSVC 2022

**To Reproduce**
`./vcpkg install libsquish`

```
cmake_minimum_required(VERSION 3.23)

project(untitled2)

set(CMAKE_CXX_STANDARD 14)

find_package(unofficial-libsquish CONFIG REQUIRED)
add_executable(untitled2 main.cpp)
target_link_libraries(untitled2 PRIVATE unofficial::libsquish::squish)

````

**Failure logs**
> fatal error C1083: Cannot open include file: 'squish.h': No such file or directory

For some weird reason it fails to find squish.h

When I add a second random package it finds it... I don't have this problem with any other dependency

**Comment by bugproof** [comment]
Doing

```
find_path(SQUISH_INCLUDE_DIR squish.h)
include_directories(${SQUISH_INCLUDE_DIR})
```

it worked... weird I don't need to do this with other dependencies can you explain what's happening and why this instruction was not provided?

**Comment by JackBoosY** [comment]
Confirmed.
