### ISSUE TITLE
bootstrap script doesn't work

### ISSUE THREAD

**Issue by benapetr** [Microsoft/vcpkg#2634]
I am getting these errors when building https://pastebin.com/kTEP4xeJ it looks like the script chooses wrong SDK?

```
  3>cl : Command line warning D9002: ignoring unknown option '/std:c++latest' [D:\libs\vcpkg\toolsrc\vcpkglib\vcpkgl
       ib.vcxproj]
         commands.autocomplete.cpp
     3>D:\libs\vcpkg\toolsrc\include\vcpkg/base/strings.h(7): error C3083: 'Strings': the symbol to the left of a '::'
       must be a type (compiling source file ..\src\vcpkg\base\checks.cpp) [D:\libs\vcpkg\toolsrc\vcpkglib\vcpkglib.vcx
       proj]
```

**Comment by alexkaratarakis** [comment]
@benapetr 
It appears you have VS 2015 without Update 3, which adds `/std:c++latest` and nested namespaces (`namespace A::B::C::D {}`). This causes the build to break. Please update to VS 2015 Update 3 or any VS 2017.
