### ISSUE TITLE
matplotplusplus update to 1.1.0

### ISSUE THREAD

**Issue by Nosenzor** [microsoft/vcpkg#26347]
Library name: matplotplusplus

New version number: 1.1.0

Other information that may be useful (release notes, etc...)
The new version is from May 2021 
Note that the version number system does not match with the one you have on vcpkg  (2021-04-11)
Here are the note from the author :
New vector fields plot with [colormap magnitudes](https://alandefreitas.github.io/matplotplusplus/plot-types/vector-fields/quiver-3d/) (Thanks @matthew-hennefarth)
Support for experimental filesystem
All pedantic warnings fixed for MSVC, GCC, and Clang
Improved tests and CI workflows

**Comment by Nosenzor** [comment]
Any updates ?

**Comment by JonLiu1993** [comment]
Fixed by PR #31796
