### ISSUE TITLE
Build luajit error project

### ISSUE THREAD

**Issue by beats-dh** [microsoft/vcpkg#26348]
**Describe the bug**
After updating lib LuaJit I can not build on the project it simply from the error at the time of linking the .exe

**Environment**
- OS: Windows 11

![image](https://user-images.githubusercontent.com/61994374/184557036-04e19bfd-d9dd-45c1-b2fe-c13c44b7d889.png)

![image](https://user-images.githubusercontent.com/61994374/184557301-c47f4c4b-539f-4819-a2be-cc9717b40093.png)

**Comment by JackBoosY** [comment]
Can you please provide a reproducible project?

**Comment by beats-dh** [comment]
> Can you please provide a reproducible sample project?

https://github.com/opentibiabr/canary

**Comment by BillyONeal** [comment]
Fixed by https://github.com/microsoft/vcpkg/pull/26360
