### ISSUE TITLE
[libjpeg-turbo] build failure (arm64 target)

### ISSUE THREAD

**Issue by NiQ1** [microsoft/vcpkg#26353]
**Host Environment**
- OS: Windows 10 x64
- Compiler: Visual Studio 2017

**To Reproduce**
`vcpkg.exe install libjpeg-turbo:arm64-windows`

**Failure logs**
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.
`C:\Users\user\Code\vcpkg>vcpkg.exe install libjpeg-turbo:arm64-windows
Computing installation plan...
The following packages will be built and installed:
    libjpeg-turbo[core]:arm64-windows -> 2.1.3#3
Detecting compiler hash for triplet arm64-windows...
Restored 0 package(s) from C:\Users\user\AppData\Local\vcpkg\archives in 284.7 us. Use --debug to see more details.
Installing 1/1 libjpeg-turbo:arm64-windows...
Building libjpeg-turbo[core]:arm64-windows...
-- Using cached libjpeg-turbo-libjpeg-turbo-c5f269eb9665435271c05fbcaf8721fa58e9eafa.tar.gz.
-- Cleaning sources at C:/Users/user/Code/vcpkg/buildtrees/libjpeg-turbo/src/fa58e9eafa-51b986428d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/user/Code/vcpkg/downloads/libjpeg-turbo-libjpeg-turbo-c5f269eb9665435271c05fbcaf8721fa58e9eafa.tar.gz
-- Applying patch add-options-for-exes-docs-headers.patch
-- Applying patch workaround_cmake_system_processor.patch
-- Using source at C:/Users/user/Code/vcpkg/buildtrees/libjpeg-turbo/src/fa58e9eafa-51b986428d.clean
-- Configuring arm64-windows
-- Building arm64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: C:/Users/user/Code/vcpkg/downloads/tools/cmake-3.24.0-windows/cmake-3.24.0-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j5
    Working Directory: C:/Users/user/Code/vcpkg/buildtrees/libjpeg-turbo/arm64-windows-dbg
    See logs for more information:
      C:\Users\user\Code\vcpkg\buildtrees\libjpeg-turbo\install-arm64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/libjpeg-turbo/portfile.cmake:56 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building libjpeg-turbo:arm64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libjpeg-turbo
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libjpeg-turbo]+Build+error
Include '[libjpeg-turbo] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: d293ac220 2022-08-12 (2 days ago)

You can also use the prefilled template from C:\Users\user\Code\vcpkg\installed\vcpkg\issue_body.md.

C:\Users\user\Code\vcpkg>`

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
[install-arm64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/9336430/install-arm64-windows-dbg-out.log)

**Comment by Cheney-W** [comment]
This issue should be fixed in VS2019 or VS2022.

**Comment by Cheney-W** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
