### ISSUE TITLE
[draco] Build error

### ISSUE THREAD

**Issue by KaiTang2** [microsoft/vcpkg#26352]
**Host Environment**
- OS: [windows-x64]

**To Reproduce**
vcpkg.exe install draco:x64-windows

**Failure logs**
The following packages will be built and installed:
    draco[core]:x64-windows -> 1.5.2
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\唐凯\AppData\Local\vcpkg\archives in 259.7 us. Use --debug to see more details.
Installing 1/1 draco:x64-windows...
Building draco[core]:x64-windows...
-- Note: draco only supports static library linkage. Building static library.
-- Downloading https://github.com/google/draco/archive/bd1e8de7dd0596c2cbe5929cbe1f5d2257cd33db.tar.gz -> google-draco-bd1e8de7dd0596c2cbe5929cbe1f5d2257cd33db.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Downloading https://github.com/google/draco/archive/bd1e8de7dd0596c2cbe5929cbe1f5d2257cd33db.tar.gz
Error: Failed to download from mirror set:
https://github.com/google/draco/archive/bd1e8de7dd0596c2cbe5929cbe1f5d2257cd33db.tar.gz: failed: status code 404

[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(766):
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 3 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 438 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 1.177 s (1166258 us)

**Additional context**
this github url couldn't link

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Can you click this link to download succeed the source of `draco`?https://github.com/google/draco/archive/bd1e8de7dd0596c2cbe5929cbe1f5d2257cd33db.tar.gz

**Comment by KaiTang2** [comment]
No I can't; @LilyWangLL ,the [vcpkg install sdl2:x64-windows] [vcpkg install opencascade:x64-windows] also have the same problem

**Comment by JackBoosY** [comment]
Personal mirror address: https://gitee.com/jackboosy/vcpkg/issues/I44496

**Comment by LilyWangLL** [comment]
Ping @KaiTang2 for response, can you use Jack's link to install port on vcpkg succeed?
