### ISSUE TITLE
Version is "0" in pkg-config file of opus and x265

### ISSUE THREAD

**Issue by asuper0** [microsoft/vcpkg#26369]
**Describe the bug**
The Version string of opus.pc and x265.pc are "0", which located in vcpkg\installed\x64-windows\lib\pkgconfig

**Environment**
- OS: [e.g. Windows]
- Compiler: msvc 2022

**To Reproduce**
1. vcpkg_default_triplet=x64-windows
2. ./vcpkg install opus x265

**Expected behavior**
.pc files contains correct version info

**Comment by JackBoosY** [comment]
Confirmed.
