### ISSUE TITLE
Specify minimum aws cli version for binary caching

### ISSUE THREAD

**Issue by qdin** [microsoft/vcpkg#26377]
****

**Is your feature request related to a problem? Please describe.**
I was trying to get binary caching to work with AWS S3. I used the following line in my cmake:
`set(VCPKG_INSTALL_OPTIONS "--binarysource=clear\;default,readwrite\;x-aws,s3://my-bucket/path/to/cache/,readwrite" CACHE STRING "..." FORCE) `

When I went to build I was getting the following error:

```
Attempting to fetch 116 package(s) from AWS
Could not automatically acquire aws because there is no entry in C:\Users\qdin\Documents\work\repos\main\vcpkg\scripts\vcpkgTools.xml for os=windows. You may be able to install aws via your system package manager.
note: updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
-- Running vcpkg install - failed
```

I'm running vcpkg version 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8.

After a bunch of toiling around, I upgraded my aws cli. I was previously at version 2.1.15, and just upgraded to 2.7.23, and everything started working. 

**Proposed solution**
The docs as well as the error message should specify the minimum version of AWS CLI. 

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by JackBoosY** [comment]
I'm not familiar with this part, let's wait for what @ras0219-msft says.

**Comment by autoantwort** [comment]
I think this can be closed now.

**Comment by jimwang118** [comment]
This issue has been fixed by PR https://github.com/microsoft/vcpkg-tool/pull/1099.
