### ISSUE TITLE
Looking for a cmake function to turn off vcpkg

### ISSUE THREAD

**Issue by LedLoaf** [microsoft/vcpkg#26385]
Hello,

So I have cmake build my project and it always turns back on vcpkg so I have to turn that off each time which is annoying. A while back, I came across a nice little script to pop in cmake that turned it off for me each time I build it. I'm not having success finding it anymore. If anyone knows one or a way to do this I would appreciate it.

Thanks

**Comment by JackBoosY** [comment]
For cmake projects, the only way to use vcpkg is to pass the vcpkg toolchain to your cmake arguments, and vcpkg uses the same process as your cmake configuration.
You just need to choose whether to pass the vcpkg toolchain to enable/disable vcpkg.
For "turns back on vcpkg", can you describe in more detail?

**Comment by Kushal-Chandar** [comment]
Don't use toolchain file directly and add this to your top level CMakeLists.txt before you add your project keyword. 

```cmake
option(ENABLE_VCPKG OFF)

if(ENABLE_VCPKG)
include(path/to/toolchain)
endif()
```

**Comment by dg0yt** [comment]
Can you explain what is meant by "turns back on vcpkg"?

**Comment by LedLoaf** [comment]
Sorry everyone, I forgot about this message. 

So to clarify.

vcpkg is always on by default in Visual Studio. So it becomes a pain when you are using cmake to build a project and you have to go back to the options and turn off vcpkg so you don't get any conflicts. I don't recall **ENABLE_VCPKG** a few months (or more) ago, was this a new contribution is recent times? Because I use to have a script that did some funky stuff to get it off and apparently at the time it was the only thing available? 

That solves it though, it was as simple as using that.

**Comment by LedLoaf** [comment]
Thanks!

**Comment by dg0yt** [comment]
> vcpkg is always on by default in Visual Studio.

I assume this implies ["MSBuild Integration"](https://github.com/microsoft/vcpkg/blob/master/docs/users/buildsystems/integration.md).

`ENABLE_VCPKG` as proposed in https://github.com/microsoft/vcpkg/issues/26385#issuecomment-1221470702 is something which would need to be added to your `CMakeLists.txt`. This proposal implies CMake and seems even more intrusive: it disables something which shouldn't be in the file.

There is a CMake option to turn off manifest mode, `VCPKG_MANIFEST_MODE`, and a corresponding MSBuild integration option, `VcpkgManifestInstall`. But without a `vcpkg.json` manifest, it wouldn't be activated anyways.
