### ISSUE TITLE
[vcpkg] One line install doesn't upgrade vcpkg

### ISSUE THREAD

**Issue by merlynomsft** [microsoft/vcpkg#26381]
Environment:
Windows

Pre-req: an older version of vcpkg is installed by previous invocation of vcpkg-init.ps1.

Powershell session:
```
> iex (iwr -useb https://aka.ms/vcpkg-init.ps1)
For more help (including examples) see the accompanying README.md and docs folder.
> vcpkg version
Vcpkg package management program version 2022-02-03-457b0309cefb58fae0dcb2e4c06de9bd7582967f
```

Result: newer version expected to be installed

**Proposed solution**
vcpkg-init.ps1 should automatically upgrade

**Comment by BillyONeal** [comment]
Hmmm are you still seeing this?

**Comment by merlynomsft** [comment]
Sorry, I can’t reproduce the issue without an old vcpkg install, which I don't have readily available. Feel free to close if it’s fixed.

**Comment by BillyONeal** [comment]
I think it's fixed but I also thought it was in August 2022 🤷 . Please feel free to reopen if it repros again!
