### ISSUE TITLE
vcpkg libraries are not found by GetPrerequisites (CMake)

### ISSUE THREAD

**Issue by maximecharriere** [microsoft/vcpkg#26397]
## Describe the bug
I'm building a installer for my program using CPack, but all dependencies need to be packaged together in order to build a standalone installer.  
CMake is shipped with the [BundleUtilities](https://cmake.org/cmake/help/latest/module/BundleUtilities.html) to do that. It will find all dependencies of your program using [GetPrerequisites](https://cmake.org/cmake/help/latest/module/GetPrerequisites.html) and make a package.  

Previously I had installed all my dependencies myself and GetPrerequisites found them. I decided to switch to vcpkg to simplify the setup of the program, but now GetPrerequisites can't find them.  

find_package() works, everything builds fine and the libraries are found, it's only during installation that GetPrerequisites fails to find dlls installed by vcpkg.  

I don't understand why there is a difference if the installation is done manually or by vcpkg. It just seems to me that the problem is that the [gp_resolve_item()](https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/GetPrerequisites.cmake#L318) function cannot find the vcpkg libraries.  

It is possible to pass an additional search folder to GetPrerequisites, so for now I have provided the vcpkg installation folder.  
**But wouldn't it be possible to modify `scripts\buildsystems\vcpkg.cmake` so that GetPrerequisites automatically finds the libraries installed by vcpkg?**

## Environment
- OS: Windows
- Compiler: MSVC
- Build system: CMake/Ninja

## Expected behavior
GetPrerequisites should find the dlls installed by vcpkg without having to provide the vcpkg installation folder. 

## Concerned CMakeLists.txt part
Not working code _(fixup_bundle() can't find vcpkg librairies)_.
```cmake
# Install all needed system libraries 
include(InstallRequiredSystemLibraries)

# Install all needed third party libraries
install (CODE "
  include(BundleUtilities)
  fixup_bundle(\"${CMAKE_INSTALL_PREFIX}/bin/${IA4FH_EXE_NAME}.exe\" \"\" \"\")
")
```

Working code _(fixup_bundle() find vcpkg librairies)_.
```cmake
# Install all needed system libraries 
include(InstallRequiredSystemLibraries)

# Install all needed third party libraries
install (CODE "
  include(BundleUtilities)
  fixup_bundle(\"${CMAKE_INSTALL_PREFIX}/bin/${IA4FH_EXE_NAME}.exe\" \"\" \"${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/bin\")
")
```

## CMake output on error
fixup_bundle() can't copy dll in package because there are not found. 
```
-- fixup_bundle
--   app='D:/ia4fh/out/install/bin/ia4fh.exe'
--   libs=''
--   dirs=''
--   ignoreItems=''
-- fixup_bundle: preparing...
--
******************************************************************************
warning: cannot resolve item 'boost_program_options-vc143-mt-x64-1_79.dll'

  possible problems:
    need more directories?
    need to use InstallRequiredSystemLibraries?
    run in install tree instead of build tree?

    context='D:/ia4fh/out/install/bin/ia4fh.exe'
    item='boost_program_options-vc143-mt-x64-1_79.dll'
    exepath='D:/ia4fh/out/install/bin'
    dirs=''
    resolved_item_var='resolved_file'
******************************************************************************

-- warning: gp_resolved_file_type non-absolute file 'boost_program_options-vc143-mt-x64-1_79.dll' returning type 'other' -- possibly incorrect


...


-- fixup_bundle: copying...
-- 1/12: *NOT* copying 'D:/ia4fh/out/install/bin/ia4fh.exe'
-- 2/12: copying 'D:/ia4fh/out/install/bin/VCOMP140.DLL'
-- warning: resolved_item == resolved_embedded_item - not copying...
-- 3/12: copying 'boost_program_options-vc143-mt-x64-1_79.dll'
Error copying file "boost_program_options-vc143-mt-x64-1_79.dll" to "D:/ia4fh/out/install/bin/boost_program_options-vc143-mt-x64-1_79.dll".
-- 4/12: copying 'gmp-10.dll'
Error copying file "gmp-10.dll" to "D:/ia4fh/out/install/bin/gmp-10.dll".
-- 5/12: copying 'libsodium.dll'
Error copying file "libsodium.dll" to "D:/ia4fh/out/install/bin/libsodium.dll".
-- 6/12: copying 'mpfr-6.dll'
Error copying file "mpfr-6.dll" to "D:/ia4fh/out/install/bin/mpfr-6.dll".
-- fixup_bundle: fixing...
-- 7/12: fix-up not required on this platform 'D:/ia4fh/out/install/bin/ia4fh.exe'
-- 8/12: fix-up not required on this platform 'D:/ia4fh/out/install/bin/vcomp140.dll'
-- 9/12: fix-up not required on this platform 'D:/ia4fh/out/install/bin/boost_program_options-vc143-mt-x64-1_79.dll'
-- 10/12: fix-up not required on this platform 'D:/ia4fh/out/install/bin/gmp-10.dll'
-- 11/12: fix-up not required on this platform 'D:/ia4fh/out/install/bin/libsodium.dll'
-- 12/12: fix-up not required on this platform 'D:/ia4fh/out/install/bin/mpfr-6.dll'
-- fixup_bundle: cleaning up...
-- fixup_bundle: verifying...
-- ===========================================================================
-- Analyzing app='D:/ia4fh/out/install/bin/ia4fh.exe'
-- bundle='D:/ia4fh/out/install/bin'
-- executable='D:/ia4fh/out/install/bin/ia4fh.exe'
-- valid='1'
-- executable file 1: D:/ia4fh/out/install/bin/ia4fh.exe
--
******************************************************************************
```

**Comment by Neumann-A** [comment]
`install (CODE` runs in its own cmake script invoke so unless you give it all the information it won't know where to search.

**Comment by maximecharriere** [comment]
Okay so here configurations made by vcpkg.cmake are unknown at the call of fixup_bundle() ?
All cache, env, and normal variables set during the cmake configuration are unknown by code present in `install (CODE ... )` ?
It was certainly working when I have builded libraries myself because system env variables were set to `<PackageName>_DIR`, helping GetPrerequisites to find the dlls.   

So for you, the best way is to specify to fixup_bundle() the path to vcpkg install dir ?

**Comment by Neumann-A** [comment]
> So for you, the best way is to specify to fixup_bundle() the path to vcpkg install dir ?

I don't think this is strictly related to vcpkg but your `fixup_bundle` call should have:
```
install (CODE "
  include(BundleUtilities)
  fixup_bundle(\"${CMAKE_INSTALL_PREFIX}/bin/${IA4FH_EXE_NAME}.exe\" \"\" \"${dep_search_paths}\")
")
```
anyway. Having an empty `dep_search_paths` is simply wrong (although you got lucky by setting so many env variables).

**Comment by maximecharriere** [comment]
`dep_search_paths` would be a cmake variable that you populate yourself? For example after calling `find_package(<PackageName>)`, add `<PackageName>_LIBRARY_RELEASE` to `dep_search_paths`?  
Doesn't CMake provide a way to group all the paths to the dependencies since they are already found by `find_package`?

**Comment by dg0yt** [comment]
(Commenting now because it was picked up in a recent comment to another issue.)

> `dep_search_paths` would be a cmake variable that you populate yourself?

Yes. (But it is not much different from providing `${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/bin` directly.)

> For example after calling `find_package(<PackageName>)`, add `<PackageName>_LIBRARY_RELEASE` to dep_search_paths?

No.  `dep_search_paths` must list the *directories* where to find the *runtime* libraries (DLLs, .so). `<PackageName>_LIBRARY_RELEASE` would typically point to the *build-time import library* on Windows.

CMake doesn't have a general/reliable way to know the location of the runtime libs. But for vcpkg, it is fairly well defined: the `bin` directories for DLLs, and the `lib` directories for non-Windows shared objects. 
It is important to properly deal with the dual-config nature of vcpkg. It can probably be handled with a generator expression like (untested):
~~~cmake
install(CODE "
  include(BundleUtilities)
  fixup_bundle(
    \"${CMAKE_INSTALL_PREFIX}/bin/${IA4FH_EXE_NAME}.exe\"
    \"\"
    \"${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}$<$<CONFIG:Debug>:/debug>/bin;${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}$<$<NOT:$<CONFIG:Debug>>:/debug>/bin\"
)
")
~~~

It is also important to understand that the code created with `install(CODE ...)` doesn't run during project configuration, but in script mode at install time. I.e. when it runs, it doesn't have the full toolchain context (e.g. a `VCPKG_INSTALLED_DIR` variable), but only the values which are literally written into the script at configuration time (e.g. the value from expanding `${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/bin`).

Last not least, some packages need extra care with regard to plugins.
