### ISSUE TITLE
qt5-tools macdeployqt in tools/qt5-tools/bin/macdeployqt not functional

### ISSUE THREAD

**Issue by m-kuhn** [microsoft/vcpkg#26390]
**Describe the bug**
`qt5-tools` installs `macdeployqt` in 2 locations:

- `tools/qt5-tools/bin/macdeployqt`
- `tools/qt5/bin/macdeployqt`

[macdeployqt looks for qmlimportscanner at a path relative to the application path](https://github.com/qt/qttools/blob/5.15.2/src/macdeployqt/shared/shared.cpp#L1259).
Since qmlimportscanner is built by `qt5-declarative` it will end up in `tools/qt5-declarative/bin` and `tools/qt5/bin` but not in `tools/qt5-tools/bin`

To make things slightly more complicated, `find_program` will pick up the version in `tools/qt5-tools/bin` as it appears earlier in `CMAKE_PROGRAM_PATH` than `tools/qt5/bin`.

**Environment**
- OS: macOS

**Expected behavior**
Every installed version of macdeployqt should be functional.
- Either by helping the `tools/qt5-tools/bin` version to find a copy of `qmlimportscanner`
- Or probably easier (?) by removing this copy

Or at least the functional copy should be the first in `CMAKE_PROGRAM_PATH` (a bandaid might be justified here as qt6 is expected to be taking over more and more)

**Comment by m-kuhn** [comment]
Workaround:

```
get_filename_component(_qt_bin_dir ${QT_MOC_EXECUTABLE} DIRECTORY)
find_program(MACDEPLOYQT_EXECUTABLE macdeployqt HINTS "${_qt_bin_dir}" NO_DEFAULT_PATH)
```

**Comment by trileyinvicro** [comment]
Just got bit by this - I think they behave differently (the instance in `qt5/bin/macdeployqt` correctly copies Qt plugins correctly while the qt5-tools binary doesn't).

**Comment by m-kuhn** [comment]
This is probably not a port-feature, but a bug.

**Comment by sfhacker** [comment]
This issue is two years old!
