### ISSUE TITLE
[Suggestion] Default triplets should be static builds with /MD.

### ISSUE THREAD

**Issue by ghost** [microsoft/vcpkg#2639]
Right now the default triplets enable DLL build with /MD.. But it causes a certain number of issues with libraries, such as Botan (C4251 all over the place) in addition of quickly polluting the output folders.

Unfortunately the *-static triplets only allows for static CRT linkage, which is in my knowledge, not a very good choice nor a very popular one.

Is there any reason yet why DLL build is preferred over static build ? Could it be possible to change the default triplets and rename the old ones as *-dll instead ?

**Comment by glachancecmaisonneuve** [comment]
Changing the triplets now would be a lot of work.

If you don't like the provided triplets make your own.
```x64-windows-Bitkoda.cmake
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
```

If you want that triplet to be the default, set VCPKG_DEFAULT_TRIPLET=x64-windows-Bitkoda

Did I miss the point of your request?

**Comment by faburaya** [comment]
What if we add an option for static linkage with dynamic CRT linkage?

**Comment by JackBoosY** [comment]
See [reply](https://github.com/microsoft/vcpkg/issues/15122#issuecomment-745497720).

Please track this issue in #15122.
