### ISSUE TITLE
[azure-kinect-sensor-sdk] Cannot use in a static build

### ISSUE THREAD

**Issue by pgoorts** [microsoft/vcpkg#26408]
**Host Environment**
- OS: Windows
- Compiler: VS 16 (2019)

**To Reproduce**
Make manifest with `azure-kinect-sensor-sdk` as package and `find_package(k4a CONFIG REQUIRED)` and `find_package(k4arecord CONFIG REQUIRED)` in CMake. Build with triplet `x64-windows-static`

**Failure logs**
```
CMake Error at D:/Projects/build/vs2019_x64/vcpkg_installed/x64-windows-static/share/k4a/k4aTargets.cmake:73 (message):
  The imported target "k4a::k4a" references the file

     "D:/Projects/build/vs2019_x64/vcpkg_installed/x64-windows-static/debug/bin/k4a.dll"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "D:/Projects/build/vs2019_x64/vcpkg_installed/x64-windows-static/share/k4a/k4aTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  D:/Projects/build/vs2019_x64/vcpkg_installed/x64-windows-static/share/k4a/k4aConfig.cmake:7 (include)
  Dependencies/scripts/buildsystems/vcpkg.cmake:816 (_find_package)
  CMakeLists.txt:150 (find_package)
```

**Additional context**
* `x64-windows` does work as expected
* Deleting the cache does not resolve the issue

**Comment by Cheney-W** [comment]
After checking the source's cmakelist.txt, I found that [k4a](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/src/sdk/CMakeLists.txt) and [k4arecord](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/src/record/sdk/CMakeLists.txt) only support dynamic compilation, could you please report an issue to upstream to confirm whether these two targets support static? Thank you!

**Comment by pgoorts** [comment]
I have done so and will provide any updates here too.

**Comment by Cheney-W** [comment]
https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1820
