### ISSUE TITLE
[openssl] build failure "crypto\aes\aesni-mb-x86_64.asm:1: error: parser: instruction expected"

### ISSUE THREAD

**Issue by bjornpiltz** [microsoft/vcpkg#26409]
**Host Environment**
- OS: Windows 10 Enterprise, Version 21H2
- Compiler: MSVC/14.29.30037, Microsoft Visual Studio Professional 2019, Version 16.11.18

**To Reproduce**
`./vcpkg --triplet x64-windows install openssl[core]`

**Failure logs**
```-- Configure x64-windows-dbg done
-- Build x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: .../vcpkg/downloads/tools/jom/jom-1.1.3/jom.exe -j 1 -f makefile install_sw install_ssldirs
    Working Directory: .../vcpkg/buildtrees/openssl/x64-windows-dbg
    Error code: 2
    See logs for more information:
      ...\vcpkg\buildtrees\openssl\build-x64-windows-dbg-1-out.log
      ...\vcpkg\buildtrees\openssl\build-x64-windows-dbg-1-err.log

Call Stack (most recent call first):
  ports/openssl/windows/portfile.cmake:152 (vcpkg_execute_required_process)
  ports/openssl/portfile.cmake:36 (include)
  scripts/ports.cmake:147 (include)
```
In the logs, I find this:
```
jom 1.1.3 - empower your cores

crypto\aes\aesni-mb-x86_64.asm:1: error: parser: instruction expected
crypto\aes\aesni-mb-x86_64.asm:6: error: parser: instruction expected
```

[build-x64-windows-dbg-1-err.log](https://github.com/microsoft/vcpkg/files/9374242/build-x64-windows-dbg-1-err.log)
[build-x64-windows-dbg-1-out.log](https://github.com/microsoft/vcpkg/files/9374243/build-x64-windows-dbg-1-out.log)

**Comment by Adela0814** [comment]
@bjornpiltz Could you please try the solution in [here](https://github.com/microsoft/vcpkg/issues/18481)?

**Comment by bjornpiltz** [comment]
**What I tried**
* Go to Settings and then: All Settings -> Time & Language -> Language -> "Administrative Language Settings".
In the tab "Administrative" press "Change System locale..." and check the box "Beta: Use Unicode UTF-8 for worldwide language support.
* Reboot.
* Nuke the vcpkg folder and start over.

**What I get**
The same error with a different .asm file. A second run triggers the error in yet another file. I'm starting to suspect Microsoft Defender is the culprit here.

**Comment by Adela0814** [comment]
> * Go to Settings and then: All Settings -> Time & Language -> Language -> "Administrative Language Settings".

Have you tried to install the English language pack for your VS?

**Comment by bjornpiltz** [comment]
> Have you tried to install the English language pack for your VS?
My VS is in English. I haven't installed any other language packs.

**Comment by Adela0814** [comment]
And you still have the same issue? have you tried deleting the downloads directory, rebootstrapping, and then running ./vcpkg install openssl:x64-windows again?

**Comment by Adela0814** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
