### ISSUE TITLE
[Boost] Cannot find version.hpp in static build

### ISSUE THREAD

**Issue by pgoorts** [microsoft/vcpkg#26407]
**Host Environment**
- OS: Windows
- Compiler: VS16 (2019)

**To Reproduce**
Make manifest with Boost as package and `find_package(Boost REQUIRED)` in CMake. Build with triplet x64-windows-static

**Failure logs**
```
CMake Error at C:/Program Files/CMake/share/cmake-3.19/Modules/FindBoost.cmake:1643 (file):
  file STRINGS file
  "D:/Projects/build/vs2019_x64/vcpkg_installed/x64-windows/include/boost/version.hpp"
  cannot be read.
Call Stack (most recent call first):
  D:/Projects/build/vs2019_x64/vcpkg_installed/x64-windows-static/share/boost/vcpkg-cmake-wrapper.cmake:11 (_find_package)
  Dependencies/scripts/buildsystems/vcpkg.cmake:770 (include)
  CMakeLists.txt:147 (find_package)
```

**Additional context**
A workaround is to move the file from `x64-windows-static/include/boost/version.hpp` to `x64-windows/include/boost/version.hpp`

**Comment by Osyotr** [comment]
This error usually happens when switching triplets without deleting cmake cache.

**Comment by pgoorts** [comment]
I checked this to confirm. When deleting the cache, the issue does not appear. When building with `x64-windows-static`, and then `x64-windows` (or reverse), the issue shows up

**Comment by Osyotr** [comment]
Maybe vcpkg should track changes to `VCPKG_TARGET_TRIPLET` (and `VCPKG_HOST_TRIPLET`) and emit an error saying that people should delete cmake cache.
@ras0219-msft
