### ISSUE TITLE
[vcpkg search] output lists %-*s %s instead of port/features

### ISSUE THREAD

**Issue by StarGate-One** [microsoft/vcpkg#26415]
**Describe the bug**

**Environment**
- OS: [Windows 10.0.22000.856] Windows 11
- Compiler:
  Visual Studio Community 2022 Version: [17.3.1]  VS Tools Version: [14.33.31629] 
  Microsoft (R) C/C++ Optimizing Compiler Version [19.33.31629] for x64 

 Fresh clones of `vcpkg` and `vcpkg-tool` repos.

**NOTE 1** The `vcpkg.exe` being used is built, compiled and linked from the vcpkg-tool source with commit [ [[localization][automated][ci skip] update locale file](https://github.com/microsoft/vcpkg-tool/commit/7753a34a97311391e6fac8d035e762a063d5be32), although I suspect one of the following is the actual culprit causing the improperly formatted text in  `vcpkg search` output:
https://github.com/microsoft/vcpkg-tool/pull/662
https://github.com/microsoft/vcpkg-tool/pull/646

The search was working properly after commit https://github.com/microsoft/vcpkg-tool/pull/642 .

**NOTE 2** The `vcpkg.exe` produces the correct output when running `vcpkg list sdl2`

**NOTE 3** I ran `bootstrap-vcpkg.bat` to download, installed the latest microsoft created `vcpkg` and search does work correctly, so this would eliminated corruption of my vcpkg instance.

**To Reproduce**
1. Clone, build, clone and link the latest `vcpkg-tool` code as of 08/18/2022 @ 22:30 EDT
2. ./vcpkg search sdl2
3. Sample output
username@computer Microsoft Windows [Version 10.0.22000.856] 08/18/2022 22:15:36
D:\vcpkg
>->`vcpkg search sdl2`
>%-*s %s
>%-*s %s
>%-*s %s
>%-*s %s
>%-*s %s
>%-*s %-*s %s
>%-*s %s
>%-*s %s
>%-*s %s
>%-*s %-*s %s
>%-*s %-*s %s
>%-*s %s
>%-*s %s
>%-*s %s
>%-*s %-*s %s
>%-*s %s
>%-*s %s
>%-*s %s
>%-*s %s
>%-*s %s
>%-*s %s
>%-*s %s
>%-*s %-*s %s
>%-*s %-*s %s
>%-*s %s
>%-*s %-*s %s
>%-*s %s
>The result may be outdated. Run `git pull` to get the latest results.
>If your port is not listed, please open an issue at and/or consider making a pull request.    -  >https://github.com/Microsoft/vcpkg/issues

**Expected behavior**
./vcpkg search sdl2 - should list all ports/features containing the term "sdl2"

**Failure logs**
- No Failure logs

**Additional context**
Note: I use vcpkg in classic mode, no registries, no overlays, no binary caching, etc.

**Comment by LilyWangLL** [comment]
I can reproduce this issue locally. @BillyONeal Could you help take a look this issue?

**Comment by BillyONeal** [comment]
![image](https://user-images.githubusercontent.com/1544943/185650506-ee44e79b-0713-4bd8-a998-036c2d6cbf16.png)

🤣😬

Thanks for the report

**Comment by StarGate-One** [comment]
Thank you very much @BillyONeal - works as advertised now :)
Have a super wonderful weekend.

**Comment by BillyONeal** [comment]
https://www.reddit.com/r/ProgrammerHumor/comments/wqjgbn/lgtm/
