### ISSUE TITLE
[igraph] build failure, possibly an issue with the [libxml2] port

### ISSUE THREAD

**Issue by szhorvat** [microsoft/vcpkg#26410]
**Host Environment**
- OS: macOS 10.14
- Compiler: Apple clang version 11.0.0 

**To Reproduce**
`./vcpkg install igraph`

**Failure logs**

```
/Users/szhorvat/Repos/vcpkg/buildtrees/igraph/src/igraph-0-52e81377b8.clean/src/io/graphml.c:43:10: fatal error: 'libxml/encoding.h' file not found
#include <libxml/encoding.h>
         ^~~~~~~~~~~~~~~~~~~
```

**Additional context**

This may have happened due to a change in the `libxml2` port. The cause is that the `-I` option passed to the compiler looks like this:

```
-I/Users/szhorvat/Repos/vcpkg/buildtrees/igraph/src/igraph-0-58d5a34798.clean/src/Users/szhorvat/Repos/vcpkg/installed/x64-osx/include/libxml2
```

Notice that a path that should be absolute got concatenated to the working directory used during the build.

I suspect that this is an issue not with igraph but with a change in vcpkg, possible a change in the libxml2 port.

**Comment by FrankXie05** [comment]
Thanks for posting this issue, I didn't reproduce your problem, can you provide the complete error log?
````
vcpkg@VCPKGMM-12 vcpkg % ./vcpkg install igraph
Computing installation plan...
The following packages will be built and installed:
  * blas[core]:x64-osx -> 1#1
  * gklib[core]:x64-osx -> 2022-07-27#1
    igraph[core,graphml]:x64-osx -> 0.9.9
  * lapack[core]:x64-osx -> 2022-02-22
  * lapack-reference[blas-select,core,noblas]:x64-osx -> 3.10.1
  * metis[core]:x64-osx -> 2022-07-27
  * openblas[core]:x64-osx -> 0.3.20
  * pthread[core]:x64-osx -> 3.0.0#1
  * pthreads[core]:x64-osx -> 3.0.0#11
  * suitesparse[core]:x64-osx -> 5.8.0#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-osx...
...
...
Installing 10/10 igraph:x64-osx...
Building igraph[core,graphml]:x64-osx...
-- Downloading https://github.com/igraph/igraph/releases/download/0.9.9/igraph-0.9.9.tar.gz -> igraph-0.9.9.tar.gz...
-- Extracting source /Users/vcpkg/test/vcpkg/downloads/igraph-0.9.9.tar.gz
-- Applying patch glpk-uwp.patch
-- Using source at /Users/vcpkg/test/vcpkg/buildtrees/igraph/src/igraph-0-52e81377b8.clean
-- Found external ninja('1.10.2').
-- Configuring x64-osx
-- Building x64-osx-dbg
-- Building x64-osx-rel
-- Installing: /Users/vcpkg/test/vcpkg/packages/igraph_x64-osx/share/igraph/copyright
-- Fixing pkgconfig file: /Users/vcpkg/test/vcpkg/packages/igraph_x64-osx/lib/pkgconfig/igraph.pc
-- Fixing pkgconfig file: /Users/vcpkg/test/vcpkg/packages/igraph_x64-osx/debug/lib/pkgconfig/igraph.pc
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: "/Users/vcpkg/.cache/vcpkg/archives/89/89f531b6a1b7b1c8f8138e0074617e52c4b3e19160945d254cfc60a09680deaa.zip"
Elapsed time to handle igraph:x64-osx: 33.68 s

Total elapsed time: 4.115 min

igraph provides CMake targets:
    # this is heuristically generated, and may not be correct
    find_package(igraph CONFIG REQUIRED)
    target_link_libraries(main PRIVATE igraph::bliss igraph::igraph igraph::prpack igraph::cliquer)

vcpkg@VCPKGMM-12 vcpkg %
````

For port `libnxml2`, the path where the header files are installed is `set(XML_INCLUDEDIR "-I\${includedir}/libxml2")` https://gitlab.gnome.org/GNOME/libxml2/-/blob/2.9/CMakeLists.txt#L697.

For port `igraph`, the way to get the path that depends on `libxml2` is `$<$<BOOL:${LIBXML2_INCLUDE_DIRS}>:${LIBXML2_INCLUDE_DIRS}>` (from `igraph` src/CMakeLists.txt), where the obtained path value is 
````
E:/test/ vcpkg/installed/x86-windows/include/libxml2;E:/test/vcpkg/installed/x86-windows/include
```` 
and for both paths, there is a header folder named `libxml` under their paths , which includes the header file `encoding.h`.

[CMakeLists.txt](https://github.com/microsoft/vcpkg/files/9379584/CMakeLists.txt)
![image](https://user-images.githubusercontent.com/65999885/185555023-5a78be42-d398-48b1-b8c5-f498d6d5eabc.png)

**Comment by szhorvat** [comment]
Attaching all logfiles: [igraph-logs.zip](https://github.com/microsoft/vcpkg/files/9379734/igraph-logs.zip)

**Comment by szhorvat** [comment]
The `LIXBML2_INSTALL_DIRS` variable appears to be correct when set by libxml2. Something might be going wrong on the igraph side after all. I'll look at it a bit more carefully and will get back to you.

**Comment by dg0yt** [comment]
Are your installed packages up-to-date? There is a number of ports depending on libxml2 and the `LibXml2` CMake package, but there is no error in vcpkg CI.

**Comment by szhorvat** [comment]
Yes, I started with a clean and up-to-date vcpkg repo.

**Comment by szhorvat** [comment]
On a different machine this works correctly, and it also does for a colleague. However, it _did_ work on my machine as well last time igraph was updated (~ 2 months ago?)

Something seems to be going wrong with the expansion of the generator expression `$<$<BOOL:${LIBXML2_INCLUDE_DIRS}>:${LIBXML2_INCLUDE_DIRS}>` which somehow causes the path to be appended to the working directory. The value of `LIBXML2_INCLUDE_DIRS` is correct at this point in the CMake file, but it somehow changes when the generator expression is expanded.

Since the problem appears only on my machine so far, here are details of my system:

 - macOS 10.14.6
 - Latest Xcode available for this system with Apple clang version 11.0.0 (clang-1100.0.33.17)
 - I have a MacPorts installation on this machine, which is where I get gfortran from. I do not have Homebrew. However, everything does work fine on another machine that also has MacPorts.

The problem appears only when building igraph with vcpkg, not when building it independently.

**Comment by szhorvat** [comment]
In fact, getting rid of the generator expression and replacing `$<$<BOOL:${LIBXML2_INCLUDE_DIRS}>:${LIBXML2_INCLUDE_DIRS}>` by simply `${LIBXML2_INCLUDE_DIRS}` (knowing that with this configuration libxml2 is present) makes the problem go away.

This confirms that it's the expansion of the generator expression that goes wrong, but I'm not sure how to debug that.

**Comment by szhorvat** [comment]
I believe this may have been a problem with igraph. Quoting the generator expression fixes it. On my machine `LIBXML2_INCLUDE_DIRS` does contain two semicolon-separated entries, and this may somehow be causing problems. Why this happens only on my machine (and not other machines where there are also two entries) and why only in vcpkg (and not when building igraph separately) I do not understand. Closing this for now, but any insights are most welcome!
