### ISSUE TITLE
How do I build  gstreamer in visual studio

### ISSUE THREAD

**Issue by rinechran** [microsoft/vcpkg#26417]
Please create a discussion in https://github.com/microsoft/vcpkg/discussions/new instead.

![image](https://user-images.githubusercontent.com/15512801/185552188-3c3057d1-08a6-42d2-8798-b30b2acc1245.png)

i installed gstream using vcpkg . 

But it doesn't build at all in the visual studio.

![image](https://user-images.githubusercontent.com/15512801/185552324-38d82322-d0ec-4ad1-80c2-74efa5e52c96.png)
![image](https://user-images.githubusercontent.com/15512801/185552347-81971288-fc0a-48c3-9b6f-a760393b1e46.png)

**Comment by FrankXie05** [comment]
1.  Make sure the port you download is consistent with the system architecture of your vs (x64/x86).

2.  If you are using `MSBuild` project, please run the command` ./vcpkg integrate install` then restart `VS` and try again.

3.  If you are using VS's cmake project, make sure you add `CMAKE_TOOLCHAIN_FILE` to `CMakeSettings.json` , and add `gstreamer` useage to the top-level CMakeLists.txt.

Please see the documentation for details: https://github.com/microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md

**Comment by rinechran** [comment]
i already did. but it not working

**Comment by FrankXie05** [comment]
@rinechran Is this issue only for `gstreamer`? Or all from the ports provided by vcpkg?

**Comment by rinechran** [comment]
i don't know about other vcpkg projects , but i checked is only gstream.

**Comment by FrankXie05** [comment]
Could you  please try using the port provided by vcpkg according to doc https://github.com/microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md ? Perhaps we missed a step? :)

**Comment by rinechran** [comment]
i did't miss task 

After installing x64/x86 version  i did ``` ./vcpkg integrate install``` 

but the build doesn't work
![image](https://user-images.githubusercontent.com/15512801/185572818-1542c3db-ec63-428d-94db-efb37083f161.png)

**Comment by FrankXie05** [comment]
For port `gstreamer`, please use `#include <gstreamer-1.0/gst/gst.h>`


![image](https://user-images.githubusercontent.com/65999885/185574725-bc6de453-d6ec-4058-976d-4c66d3b210e8.png)

**Comment by rinechran** [comment]
![image](https://user-images.githubusercontent.com/15512801/185575197-add58013-84ed-488b-bd39-567e89c0cc8e.png)
The build doesn't work.

**Comment by FrankXie05** [comment]
For the integration of vcpkg projects, the default path is `{VCPKG_INCLUDE_DIR}/${TRIPLET}/include`. For my project, this value is `E:\port-update\vcpkg\installed\x64-windows\include`, so if you want to use `gstreamer` header files, each `include` must contain `gstreamer-1.0`.
Like : `#include <gstreamer-1.0/gst/gstversion.h>`

**Comment by rinechran** [comment]
Have you tried compiling the header file?

**Comment by rinechran** [comment]
> `:\port-update\vcpkg\installed\x64-windows\include`, so if you want to use `gstreamer` header files, each `include` must contain `gstreamer-1.0`.


Have you tried compiling the header file?

**Comment by FrankXie05** [comment]
@rinechran Yes, this is indeed a bug. For upstream behavior, the `gstreamer` headers should be installed under the outer folder named `gst`. I will fix it. :)

**Comment by Sharpe49** [comment]
For me, it's not a bug.
Official builds from upstream are using the include/gstreamer-1.0/gst folder to store the include files.
And the pkgconfig files do point to the right folder:
`Cflags: -I"${includedir}/gstreamer-1.0"`

**Comment by Sharpe49** [comment]
Are you using CMake or MSBuild in your project?

**Comment by rinechran** [comment]
i am use MSBuild

> Are you using CMake or MSBuild in your project?

**Comment by m-riley04** [comment]
Still no fix for this :( I'll look into a workaround for the time being
