### ISSUE TITLE
[New Port Request] x11

### ISSUE THREAD

**Issue by rinechran** [microsoft/vcpkg#26418]
Library name: x11

Library description: linux gui 

Source repository URL:  https://cgit.freedesktop.org/wiki/xorg/

Project homepage (if different from the source repository): https://www.x.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

opencv gtk , qt5 , gstreamer

**Comment by FrankXie05** [comment]
Will be fixed by PR https://github.com/microsoft/vcpkg/pull/21584

**Comment by Osyotr** [comment]
> Good first issue

😂😂😂

**Comment by Neumann-A** [comment]
> opencv gtk , qt5 , gstreamer

making all the other ports depend on it however is a completely different issue and will require a linux CI without any of those libs installed.

**Comment by rinechran** [comment]
> making all the other ports depend on it however is a completely different issue and will require a linux CI without any of those libs installed.
I understand.
