### ISSUE TITLE
[New Port Request] <LRC-Tools>

### ISSUE THREAD

**Issue by ilongshan** [microsoft/vcpkg#26422]
Library name:
LRC-Tools
Library description:
Tools for parsing and playing back LRC lyrics.
Source repository URL:
https://github.com/ywh233/LRC-Tools

**Comment by rinechran** [comment]
I tried to work on that port, but it didn't even build.

@JackBoosY 
What should we do in this case? Should I fix the source code and add a port?


```rinechran@rinechran:/mnt/c/Users/rinec/Desktop/LRC-Tools - Copy/build$ make
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/c/Users/rinec/Desktop/LRC-Tools/build
Consolidate compiler generated dependencies of target liblrc
[ 25%] Building CXX object CMakeFiles/liblrc.dir/liblrc/lyrics.cc.o
/mnt/c/Users/rinec/Desktop/LRC-Tools/liblrc/lyrics.cc:47:10: error: ‘numeric_limits’ is not a member of ‘std’
   47 |     std::numeric_limits<int32_t>::max() >> 1;
      |          ^~~~~~~~~~~~~~
/mnt/c/Users/rinec/Desktop/LRC-Tools/liblrc/lyrics.cc:47:32: error: expected primary-expression before ‘>’ token
   47 |     std::numeric_limits<int32_t>::max() >> 1;
      |                                ^
/mnt/c/Users/rinec/Desktop/LRC-Tools/liblrc/lyrics.cc:47:35: error: ‘::max’ has not been declared; did you mean ‘std::max’?
      |                                   ^~~
      |                                   std::max
In file included from /usr/include/c++/11/algorithm:62,
                 from /mnt/c/Users/rinec/Desktop/LRC-Tools/liblrc/lyrics.cc:11:
/usr/include/c++/11/bits/stl_algo.h:3467:5: note: ‘std::max’ declared here
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~```

**Comment by JackBoosY** [comment]
@rinechran Can you please make a PR first?

**Comment by rinechran** [comment]
On , I  didn't think of that , thank you

**Comment by JackBoosY** [comment]
According to the [c++ standard doc](https://en.cppreference.com/w/cpp/types/numeric_limits), I think this is not related to the c++ standard setting.

**Comment by rinechran** [comment]
I'm sorry. I modified the cmake to make a port, but there was a mistake.

**Comment by JackBoosY** [comment]
> I'm sorry. I modified the cmake to make a port, but there was a mistake.

Please [open a PR](https://github.com/microsoft/vcpkg/compare) in github page so I can figure out what happened.

**Comment by rinechran** [comment]
The package was not provided in a separate library format, so it was unofficially cmake packaged to provide the library in vcpkg.

Meanwhile, a compilation error occurred, and a separate patch was made to solve this problem.

https://github.com/microsoft/vcpkg/pull/27023

**Comment by eunsikNota** [comment]
this port merge https://github.com/microsoft/vcpkg/pull/27023

**Comment by LilyWangLL** [comment]
Since this issue has been resolved, so I am closing this issue for now.
