### ISSUE TITLE
[New Port Request] <sonic>

### ISSUE THREAD

**Issue by ilongshan** [microsoft/vcpkg#26423]
Library name:
sonic
Library description:
Simple library to speed up or slow down speech
Source repository URL:
https://github.com/waywardgeek/sonic

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by ilongshan** [comment]
Hope it will be added to vcpkg, please reopen it.

**Comment by LilyWangLL** [comment]
> Hope it will be added to vcpkg, please reopen it.

Could you please submit a PR to add this port to vcpkg?
