### ISSUE TITLE
[gettext] aclocal folder with macros missing on X86 Windows

### ISSUE THREAD

**Issue by wrobelda** [microsoft/vcpkg#26426]
**Describe the bug**
`share/gettext/aclocal` has `gettext.m4`, amongst other macros, on *Nix and Windows X64 platform. However, Windows x86 build is missing `aclocal` folder altogether 

**Environment**
- OS: Windows x86

**To Reproduce**
1. `./vcpkg install gettext:windows-x86`
2. Notice the `share\gettext` has missing `aclocal`

**Comment by Neumann-A** [comment]
use `CURRENT_HOST_INSTALLED_DIR` and make `gettext[tools]` a host dependency?

**Comment by wrobelda** [comment]
Yeah, literally just realized that, my bad

**Comment by wrobelda** [comment]
Still, this's quite some inconsistency between the platforms, probably worth fixing? Or is that on purpose?

**Comment by Neumann-A** [comment]
> Still, this's quite some inconsistency between the platforms, probably worth fixing? Or is that on purpose?

Where? It should always be a host dependency. But some stuff was added/done before host dependencies exist.

**Comment by wrobelda** [comment]
> Where? 
Between

**Comment by Neumann-A** [comment]
did you install `gettext[tools]` on x86 or just `gettext`?

**Comment by wrobelda** [comment]
I'm not installing anything explicitly, everything gets installed via the manifest file, so both platforms use `gettext[tools]`

**Comment by Neumann-A** [comment]
> I'm not installing anything explicitly, everything gets installed via the manifest file, so both platforms use gettext[tools]

that doesn't make sense. Only the host would require `tools`. I think you need to take a closer look at your manifests.

**Comment by dg0yt** [comment]
> > Where?
> 
> Between the x86 and x64 installed packages filesets.

I think there is no inconsistency, except that nowadays x64 is the host for building x86. If you build x86 natively (i.e. with x86 host triplet), you will find ports that pull in `gettext[tools]:x86-*`

**Comment by Adela0814** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
