### ISSUE TITLE
[python3] Build error

### ISSUE THREAD

**Issue by Nosenzor** [microsoft/vcpkg#26431]
**Host Environment**
- OS: Mac Os 10.15.7
- Compiler: Apple Clang

**To Reproduce**
`./vcpkg install python3`

**Failure logs**
Building python3[core]:x64-osx...
-- Using cached python-cpython-v3.10.5.tar.gz.
-- Cleaning sources at /Users/Romain/CLionProjects/PhotoTools/vcpkg/buildtrees/python3/src/v3.10.5-bfee21776f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/Romain/CLionProjects/PhotoTools/vcpkg/downloads/python-cpython-v3.10.5.tar.gz
-- Applying patch 0001-static-library.patch
-- Applying patch 0002-use-vcpkg-zlib.patch
-- Applying patch 0003-devendor-external-dependencies.patch
-- Applying patch 0004-dont-copy-vcruntime.patch
-- Applying patch 0005-only-build-required-projects.patch
-- Applying patch 0009-python.pc.patch
-- Applying patch 0010-bz2d.patch
-- Applying patch 0011-dont-skip-rpath.patch
-- Using source at /Users/Romain/CLionProjects/PhotoTools/vcpkg/buildtrees/python3/src/v3.10.5-bfee21776f.clean
-- Getting CMake variables for x64-osx-dbg
-- Getting CMake variables for x64-osx-rel
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: /usr/bin/make V=1 -j 9 -f Makefile all
    Working Directory: /Users/Romain/CLionProjects/PhotoTools/vcpkg/buildtrees/python3/x64-osx-dbg/
    See logs for more information:
      /Users/Romain/CLionProjects/PhotoTools/vcpkg/buildtrees/python3/build-x64-osx-dbg-out.log
      /Users/Romain/CLionProjects/PhotoTools/vcpkg/buildtrees/python3/build-x64-osx-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:147 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:2 (vcpkg_build_make)
  ports/python3/portfile.cmake:230 (vcpkg_install_make)
  scripts/ports.cmake:147 (include)

error: building python3:x64-osx failed with: BUILD_FAILED
nclude '[python3] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: 030c53833 2022-08-09 (10 days ago)

**Additional context**
Note that installing python2 work smoothly

**Comment by JackBoosY** [comment]
Please provide the following logs first:
/Users/Romain/CLionProjects/PhotoTools/vcpkg/buildtrees/python3/build-x64-osx-dbg-out.log
/Users/Romain/CLionProjects/PhotoTools/vcpkg/buildtrees/python3/build-x64-osx-dbg-err.log


Thanks.

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
