### ISSUE TITLE
[New Port Request] Clipper2

### ISSUE THREAD

**Issue by shelllet** [microsoft/vcpkg#26448]
Library name: Clipper2

Library description:
A Polygon [Clipping](https://en.wikipedia.org/wiki/Clipping_(computer_graphics)) and [Offsetting](https://en.wikipedia.org/wiki/Parallel_curve) library (in C++, C# & Delphi)
Clipper2 is a major update of my original [Clipper](https://sourceforge.net/projects/polyclipping/) library which I'm now calling Clipper1.
Clipper1 was written over 10 years ago and still works very well, but Clipper2 is better in just about every way.
Source repository URL:

Project homepage (if different from the source repository):
https://github.com/AngusJohnson/Clipper2

**Comment by legacy3** [comment]
Looking forward to this port.

**Comment by dg0yt** [comment]
I wonder if it can be used as a drop-in replacement, or if clipper and clipper2 can be installed/used side by side.

**Comment by legacy3** [comment]
> I wonder if it can be used as a drop-in replacement, or if clipper and clipper2 can be installed/used side by side.

It's not a drop in replacement, however the API is very similar. You can use them side by side without any issues. We do this currently in our project. I'd suggest leaving in the Clipper1 port and adding the Clipper2 as a new port.
