### ISSUE TITLE
How do I vcpkg patch Error

### ISSUE THREAD

**Issue by rinechran** [microsoft/vcpkg#26469]
Please create a discussion in https://github.com/microsoft/vcpkg/discussions/new instead.

I'm looking at the issue (https://github.com/microsoft/vcpkg/issues/26422 )  and trying to create a port.

however, an error occurred dring the patch

![image](https://user-images.githubusercontent.com/15512801/185976177-5403f901-f253-42fd-a9f0-0288f6166bbe.png)

I put the port where the error occurred on my github

https://github.com/rinechran/vcpkg/tree/liblrc

can you check it ?

**Comment by FrankXie05** [comment]
@rinechran  Thanks for posting this issue,
I looked at the patch in your repo, but it shows binary. https://github.com/rinechran/vcpkg/commit/0f21e0980494e049c38281bf63d115b1e5914e49 This is also the cause of the error.
1. Currently git will not apply binary patches, it will be treated as a no-op. https://git-scm.com/docs/git-apply 
````
Historically we did not allow binary patch applied without an explicit permission from the user, and this flag was the way to do so. Currently we always allow binary patch application, so this is a no-op.
````
2. Patch files should be UTF-8 encoded and have Linux style line endings (LF).
3. You can recreate the patch using:
````
git init .
git add .
git commit -m "test amp"
Modify source
git diff | out-file -enc ascii fix.patch
````

**Comment by rinechran** [comment]
LGTM
