### ISSUE TITLE
[qt5] libtool chokes at -framework in dependency_libs in libQt5Core.la

### ISSUE THREAD

**Issue by wrobelda** [microsoft/vcpkg#26467]
**Describe the bug**
While working on #26424, I am getting the following error when building on macOS:

```
libtool: warning: library '/Users/cromo/Documents/Sourcecode/vcpkg/installed/arm64-osx/debug/lib/libQt5Core_debug.la' was moved.
libtool:   error: cannot find the library '' or unhandled argument 'DiskArbitration'
```

Apparently lib tool does not understand the `-framework` syntax in `dependency_libs`, and so they need to be moved to `inherited_linker_flags`.

See https://github.com/NixOS/nixpkgs/issues/96977 for the reference and https://github.com/NixOS/nixpkgs/commit/8e4e38cdcdc5f2be6875e6506d0789e9e5411ea6 for a solution

**Environment**
- OS: macOS
- 
**To Reproduce**
1. Checkout the PR linked above on macOS
1. ./vcpkg install gpgme[qt]
2. See error

**Comment by Neumann-A** [comment]
the `*.la` files of qt5 should probably be removed.

**Comment by wrobelda** [comment]
Well, I manually edited them to build successfully, but removing them also fixes the issue.
