### ISSUE TITLE
[dpp] Build error

### ISSUE THREAD

**Issue by RamiR294** [microsoft/vcpkg#26462]
[issue_body.md](https://github.com/microsoft/vcpkg/files/9393468/issue_body.md)

**Comment by FrankXie05** [comment]
@RamiR294 Please provide the error log: 
````
C:\dev\vcpkg\vcpkg\buildtrees\dpp\install-x64-windows-dbg-err.log
````

**Comment by FrankXie05** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
