### ISSUE TITLE
Allow specifying version when installing from command line

### ISSUE THREAD

**Issue by Zipdox** [microsoft/vcpkg#26463]
****

**Is your feature request related to a problem? Please describe.**
Currently the only way to do versioning is using a manifest file with a build system. This is extremely inconvenient if you just need one package or if you don't use a compatible build system. Even if it's easy, forcing users to do it this way is extremely bad practice and I have never seen a package manager do it like this.

**Proposed solution**
Allow specifying versions in a similar manner to npm like
`vcpkg install gtk@3`

**Describe alternatives you've considered**
An option to specify the version
`vcpkg install -v 3 gtk`

**Additional context**
Related discussion:
https://github.com/microsoft/vcpkg/discussions/25622

**Comment by Adela0814** [comment]
A new port gtk3 is now added. https://github.com/microsoft/vcpkg/pull/27026
Alternatively, you can use the manifest mode to specify the installed version.
