### ISSUE TITLE
Cannot build vcpkg (MSBuild error)

### ISSUE THREAD

**Issue by nhbusch** [Microsoft/vcpkg#2647]
After pulling the latest sources (from version 0.0.102 onward), I can no longer build the vcpkg executable.

System:
OS 6.1.7601 Win7, System locale: en-us, Input locale: de
Visual Studio 2017 15.5.5, MSBuild 15.5.180.51428
Windows SDK 10.0.16299.15
PowerShell 5.0

I run `.\bootstrap-vcpkg.bat`

Error message:
```
MSBUILD : error MSB1009: Project file does not exist.
Switch: dirs.proj
```
I have also tried to directly execute the `scripts\bootstrap.ps1` script.
Same result.
Also tried executing from `cmd.exe` or Powershell.
Cloning into a pristine directory yields the same error.

To me it seems as if line 59 in `bootstrap.ps1` 
```powershell
vcpkgInvokeCommandClean $msbuildExe $arguments -wait:$true
```
gives the error.

I am attaching the output of running `.\bootstrap.p1 -Verbose`.
[vcpkg.log](https://github.com/Microsoft/vcpkg/files/1665234/vcpkg.log)

**Comment by alexkaratarakis** [comment]
@nhbusch 
I made some improvements. Can you try with latest master?

**Comment by nhbusch** [comment]
@alexkaratarakis 

My $PROFILE is indeed changing directory. There is a Set-Location call at the end.
I'll try your fixes as soon as I am no longer behind a corporate firewall

**Comment by nhbusch** [comment]
Works for me now. Thanks a lot.
