### ISSUE TITLE
[New Port Request] yojimbo

### ISSUE THREAD

**Issue by bugproof** [microsoft/vcpkg#26485]
Library name: yojimbo

Library description: A network library for client/server games written in C++

Source repository URL: https://github.com/networkprotocol/yojimbo/tree/master/vcpkg/ports/yojimbo

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

There is already a port in the main repo. What could be done to make this available in the official vcpkg registry?

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
