### ISSUE TITLE
[sqlcipher] Add build support for other OS

### ISSUE THREAD

**Issue by longnguyen2004** [microsoft/vcpkg#26484]
****

**Is your feature request related to a problem? Please describe.**
Currently, the `sqlcipher` port is Windows-only. I'd like to see support for other targets as well.

**Comment by wrobelda** [comment]
`sqlcipher` port is mostly a copy of `sqlite3` port, except for the amalgamation code, which doesn't look to be Windows-specific. It could be that the original author developed it for Windows under Windows and didn't have means/couldn't be bothered to test under different platforms. 

I'd encourage you to try and see if you can get it building on your end, starting with comparing the `sqlite3` and `sqlcipher` ports for any differences that arose from the evolution of `sqlite3` portfile and back-porting them as needed..

**Comment by longnguyen2004** [comment]
Yeah, `sqlcipher` doesn't have a pre-made amalgamation, so the portfile generates it using `Makefile.msc`. On other platforms, this can be done with `./configure && make sqlite3.c`. I'll try to poke around at it.
