### ISSUE TITLE
[commonlibae] Build error

### ISSUE THREAD

**Issue by bruinp8n** [microsoft/vcpkg#26494]
Fresh pull from github, ran the bat file encountered this towards the end

``
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
    Working Directory: C:/projects/skymp/vcpkg/buildtrees/commonlibae/x64-windows-sp-dbg
    See logs for more information:
      C:\projects\skymp\vcpkg\buildtrees\commonlibae\install-x64-windows-sp-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:78 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:18 (vcpkg_build_cmake)
  C:/projects/skymp/overlay_ports/commonlibae/portfile.cmake:17 (vcpkg_install_cmake)
  scripts/ports.cmake:147 (include)

error: building commonlibae:x64-windows-sp failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+commonlibae
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[commonlibae]+Build+error
Include '[commonlibae] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: 88b1071e3 2022-08-23 (12 hours ago)

You can also use the prefilled template from C:\projects\skymp\build\vcpkg_installed\vcpkg\issue_body.md.

-- Running vcpkg install - failed
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:863 (message):
  vcpkg install failed.  See logs for more information:
  C:\projects\skymp\build\vcpkg-manifest-install.log
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.24/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:55 (project)

-- Configuring incomplete, errors occurred!``

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated in 1 month, if it is still an issue, please reopen this issue.
