### ISSUE TITLE
[wxWidgets] update to version 3.2 to fix wxTextCtrl problem

### ISSUE THREAD

**Issue by ThIsJaCk23657689** [microsoft/vcpkg#26492]
Library name: wxWidgets
New version number: version 3.2 [this PR](https://github.com/wxWidgets/wxWidgets/pull/22641)

I build a wxWidgets program by using TDM-GCC 10.3.0. I realize that I put two or more `wxTextCtrl` in my `wxFrame`, It will crash when my main frame is closed. There is no problem when I just use only one `wxTextCtrl`. The example code is down below:
```cpp
#include <wx/wx.h>

class MyApp : public wxApp {
public:
    bool OnInit() override {
        wxFrame*    frame = new wxFrame(nullptr, wxID_ANY, "wxTextCtrl Test");
        wxBoxSizer* sizer = new wxBoxSizer(wxVERTICAL);

        sizer->Add(new wxTextCtrl(frame, wxID_ANY), wxSizerFlags().Border().Expand());
        sizer->Add(new wxTextCtrl(frame, wxID_ANY), wxSizerFlags().Border().Expand());
        frame->SetSizer(sizer);
        frame->Show();

        return true;
    }
}; 
wxIMPLEMENT_APP(MyApp);
```

I had already report [this issue](https://github.com/wxWidgets/wxWidgets/issues/22735) at wxWidgets repo, they told me that this issue have been [solved](https://github.com/wxWidgets/wxWidgets/issues/22639). 

Would vcpkg update this package to fix this problem?

**Comment by FrankXie05** [comment]
@ThIsJaCk23657689 Thanks for posting this issue.
According to the update port policy, we should update to the released stable version instead of the specific master commit. Even if the upstream solves the problem. 
I think the best way is to ask the upstream if a new version has been released recently. :)

**Comment by PriitUring** [comment]
wxWidgets 3.2.1 was released 5 hours ago.

https://github.com/wxWidgets/wxWidgets/releases/tag/v3.2.1

**Comment by FrankXie05** [comment]
@PriitUring Thanks for your attention, I will update it today.

**Comment by ThIsJaCk23657689** [comment]
Thank you guys for try to fixed this issue.
But unfortunately, I update wxWidgets package from 3.2.0 to 3.2.1, the multiple textctrl problem is still not fixed.
Also, there is another problem, I can't to link "wx::gl" library after I update this package. 
``` 
find_package(wxWidgets CONFIG REQUIRED)
target_link_libraries(main PRIVATE wx::core wx::base wx::gl)
```

it will crash at cmake configuring step.
Here is the error message:
```
CMake Error at C:/dev/vcpkg/installed/x64-mingw-dynamic/share/wxwidgets/wxWidgetsTargets.cmake:177 (set_target_properties):
  The link interface of target "wx::wxgl" contains:

    OpenGL::GLU

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  C:/dev/vcpkg/installed/x64-mingw-dynamic/share/wxwidgets/wxWidgetsConfig.cmake:52 (include)
  C:/dev/vcpkg/installed/x64-mingw-dynamic/share/wxwidgets/vcpkg-cmake-wrapper.cmake:55 (_find_package)
  C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:783 (include)
  CMakeLists.txt:38 (find_package)
```

**Comment by ThIsJaCk23657689** [comment]
I find the solution that fixed the linkin "wx::gl" library, I need add `find_package(OpenGL)` in my CMakeList.txt.
Like this:
```
find_package(OpenGL)
find_package(wxWidgets CONFIG REQUIRED)
target_link_libraries(${MY_EXECUTABLE} PRIVATE wx::core wx::base wx::gl)
```

**Comment by dg0yt** [comment]
This must be transformed into a `find_dependency` in wxWidgets config.

**Comment by FrankXie05** [comment]
@ThIsJaCk23657689 Please open a new issue.
