### ISSUE TITLE
[qtbase] Why does qtbase has both unconditional dependency on freetype and freetype feature?

### ISSUE THREAD

**Issue by equeim** [microsoft/vcpkg#26491]
I want to build qtbase without GUI support, and freetype dependency is kinda unnecessary. However I can't disable it because it is unconditional: https://github.com/microsoft/vcpkg/blob/88b1071e39f13b632644d9d953738d345a4ac055/ports/qtbase/vcpkg.json#L10

Even though it is already added via feature: https://github.com/microsoft/vcpkg/blob/88b1071e39f13b632644d9d953738d345a4ac055/ports/qtbase/vcpkg.json#L156

Is this intentional?

**Comment by Neumann-A** [comment]
It could be an oversight but it could also be that qtbase doesn't build without freetype even if the gui feature was disabled. That might however have changed since the 6.1 release so somebody needs to retest it.

**Comment by equeim** [comment]
Well right now I'm building it using my custom script and it certainly does (and did it back in Qt 5 days too). I will try to remove it in vcpkg.json and see what happens.

**Comment by FrankXie05** [comment]
@equeim Is there any progress?
