### ISSUE TITLE
List packages installed files

### ISSUE THREAD

**Issue by amc522** [Microsoft/vcpkg#2649]
Is it possible to list all the files that a package installed (not including dependencies)?

**Comment by alexkaratarakis** [comment]
1) You can use the command `vcpkg owns <LibraryName>`
2) The directory `installed\vcpkg\info` contains text files that list each library's installed files.
3) The directory `packages` has each library in individual folders. The `packages` folder is a staging ground before we copy the files over in the `installed` directory from where the files are actually being used.

**Comment by amc522** [comment]
Thanks for the response! Exactly what I was looking for.
