### ISSUE TITLE
[libb2] Build error for x86-android

### ISSUE THREAD

**Issue by equeim** [microsoft/vcpkg#26490]
**Host Environment**
- OS: Fedora 36 x86_64
- Compiler: Android (8075178, based on r437112b) clang version 14.0.1 (https://android.googlesource.com/toolchain/llvm-project 8671348b81b95fc603505dfc881b45103bee1731)

**To Reproduce**
`./vcpkg install libb2:x86-android`

./configure fails with following error:
```
configure:3826: /home/alexey/Android/Sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -fPIC  -avoid-version -L/home/alexey/projects/tremotesf-android/libtremotesf/vcpkg_installed/x86-android/debug/lib conftest.c -latomic -lm -l-static-libstdc++ >&5
clang-14: warning: argument unused during compilation: '-avoid-version' [-Wunused-command-line-argument]
ld: error: unable to find library -l-static-libstdc++
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
```

I suspend that issue is caused by this: https://github.com/microsoft/vcpkg/blob/88b1071e39f13b632644d9d953738d345a4ac055/scripts/cmake/vcpkg_configure_make.cmake#L576

Vcpkg adds value VCPKG_DETECTED_CMAKE_CXX_STANDARD_LIBRARIES (which is " -static-libstdc++ -latomic -lm" in this case) to LIBS environment variable, transforming it to add "-l" prefix for each flag. However it causes compilation error because "-l-static-libstdc++" flag is invalid.

**Comment by equeim** [comment]
It seems that issue is gone in NDK r25 (probably because they switched back to their own toolchain instead of using CMake's builtin Android support). -static-libstdc++ now appears in VCPKG_DETECTED_RAW_CMAKE_SHARED_LINKER_FLAGS/VCPKG_DETECTED_RAW_CMAKE_EXE_LINKER_FLAGS/VCPKG_DETECTED_RAW_CMAKE_EXE_LINKER_FLAGS/VCPKG_DETECTED_CMAKE_EXE_LINKER_FLAGS_DEBUG variables instead.

Though the root issue with all_libs_list in vcpkg_configure_make.cmake remains of course.

However there is another issue with this package now: it is always built for x86_64 architecture with all android triplets.
Here is logs for arm64-android:

[autoconf-arm64-android-err.log](https://github.com/microsoft/vcpkg/files/9436123/autoconf-arm64-android-err.log)
[autoconf-arm64-android-out.log](https://github.com/microsoft/vcpkg/files/9436124/autoconf-arm64-android-out.log)
[build-arm64-android-dbg-err.log](https://github.com/microsoft/vcpkg/files/9436125/build-arm64-android-dbg-err.log)
[build-arm64-android-dbg-out.log](https://github.com/microsoft/vcpkg/files/9436126/build-arm64-android-dbg-out.log)
[cmake-vars-arm64-android-dbg.cmake.log](https://github.com/microsoft/vcpkg/files/9436127/cmake-vars-arm64-android-dbg.cmake.log)
[config-arm64-android-dbg-config.log](https://github.com/microsoft/vcpkg/files/9436128/config-arm64-android-dbg-config.log)
[config-arm64-android-dbg-err.log](https://github.com/microsoft/vcpkg/files/9436129/config-arm64-android-dbg-err.log)
[config-arm64-android-dbg-out.log](https://github.com/microsoft/vcpkg/files/9436130/config-arm64-android-dbg-out.log)
[get-cmake-vars-arm64-android-dbg-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/9436131/get-cmake-vars-arm64-android-dbg-CMakeCache.txt.log)
[get-cmake-vars-arm64-android-dbg-err.log](https://github.com/microsoft/vcpkg/files/9436132/get-cmake-vars-arm64-android-dbg-err.log)
[get-cmake-vars-arm64-android-dbg-out.log](https://github.com/microsoft/vcpkg/files/9436133/get-cmake-vars-arm64-android-dbg-out.log)
.

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated in 1 month, if it is still an issue, please reopen this issue.
