### ISSUE TITLE
[qtbase] build failure for Android triplets

### ISSUE THREAD

**Issue by equeim** [microsoft/vcpkg#26500]
Building Qt for Android requires passing -DANDROID_SDK_ROOT="path to Android SDK" option to CMake, vcpkg port doesn't do it right now. I'm not sure how it should be done since Android triplets don't depend on SDK, only on NDK (maybe via environment variable like ANDROID_NDK_HOME in scripts/toolchains/android.cmake)

**Comment by Neumann-A** [comment]
provide your own andorid toolchain which does stuff like that.

**Comment by equeim** [comment]
> provide your own andorid toolchain which does stuff like that.

This would add this flag for every package that uses CMake, no? I believe this should be done in qtbase portfile instead since it's Qt-specific flag.

**Comment by Neumann-A** [comment]
>  I believe this should be done in qtbase portfile instead since it's Qt-specific flag.

So if this flag is qt specific can Qt deduce it by stuff of the normal android toolchain? If yes it should probably fixed by upstream.

**Comment by equeim** [comment]
I don't think it can, reliably. It does know where NDK is located because of CMake toolchain file that sets necessary variables, but it has no way of knowing where SDK is. While NDK is typically downloaded by SDK's sdkmanager in predefined location, it can also be downloaded separately. In fact, if you only build native code you don't need SDK at all, only NDK (Qt needs it because it also compiles some Java code). So Qt requires passing SDK location explicitly.

I think it would be reasonable to add conditional code in Qt portfile that sets adds this argument from environment variable when building for Android (with error message is env variable is not set so that use would know what to do).

**Comment by Neumann-A** [comment]
I don't think it is necessary in the portfile. You can add 
```
if(PORT MATCHES "qtbase")
 set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DANDROID_SDK_ROOT=<your_path>")
endif()
```
to your triplet to achieve the same.

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated in 1 month, if it is still an issue, please reopen this issue.
