### ISSUE TITLE
[luajit] nearly all CRT functions from stdio are exported by lua51.lib

### ISSUE THREAD

**Issue by z16166** [microsoft/vcpkg#26511]
Windows 11 x64 + VS2019 x64 build, luajit:x64-windows-static.

If I statically linking to lua51.lib, my dll/exe export table will contain 170+ CRT functions such as "sprintf/sscanf/fprintf" etc.

modify src\msvcbuild.bat,

change "/D_CRT_STDIO_INLINE=__declspec(dllexport)__inline" to "/D_CRT_STDIO_INLINE=__inline"

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This should be a upstream bug, @z16166 could you please submit an issue or PR to upstream to report this issue. If upstream has better solution, I will sync up their change to my PR.
The upstream address: https://github.com/LuaJIT/LuaJIT

**Comment by z16166** [comment]
done. 

https://github.com/LuaJIT/LuaJIT/issues/889

**Comment by LilyWangLL** [comment]
> done.
> 
> [LuaJIT/LuaJIT#889](https://github.com/LuaJIT/LuaJIT/issues/889)

Thanks for your work, according to this comment: https://github.com/LuaJIT/LuaJIT/issues/889#issuecomment-1229169333, this change will cause usage problems, so I think I can close my PR. Waiting the upstream has better solution, I will sync up their solution to vcpkg.

**Comment by LilyWangLL** [comment]
Since this issue is an upstream issue and need upstream to resolve this issue, so I am closing this issue for now. If the upstream has a solution to resolve this issue, please reopen this issue.
