### ISSUE TITLE
[minizip] Just an alias for zlib

### ISSUE THREAD

**Issue by Thomas1664** [microsoft/vcpkg#26515]
The ports `minizip` and `zlib` are pointing to the same upstream repo (`madler/zlib`):
https://github.com/microsoft/vcpkg/blob/55112eb54a1c4cfaec5dd2592a39cea72f78ed56/ports/minizip/portfile.cmake#L5
https://github.com/microsoft/vcpkg/blob/55112eb54a1c4cfaec5dd2592a39cea72f78ed56/ports/zlib/portfile.cmake#L3

[Repology](https://repology.org/projects/?search=minizip) shows that there is no official package called `minizip`. Only a few [package managers](https://repology.org/project/minizip-unclassified/versions) have a package called `minizip`.

Interestingly, it doesn't seem like there are errors about duplicated symbols.

Therefore, I think the port `minizip` can be removed.

I'm opening the issue to get some ideas on how to handle this situation and if it even is possible to remove `minizip`.

The following ports depend on `zlib` and `minizip`:

- [ ] assimp
- [ ] collada-dom
- [ ] libkml
- [ ] qtwebengine

The following ports depend just on `minizip`

- [ ] xlsxio

The following ports are associated with `minizip` but depend on `zlib`:

- [ ] minizip-ng
- [ ] quazip

**Comment by JackBoosY** [comment]
@atkawa7 @Neumann-A What do you think about?

**Comment by dg0yt** [comment]
> Interestingly, it doesn't seem like there are errors about duplicated symbols.

Well, `minizip` uses port `zlib`. There is no overlap in actual source code: `minizip` only uses `contrib/minizip`.

There is a separate (vcpkg) `CMakeLists.txt`, distinct patches and distinct fixup. From a maintainability POV, I would prefer to leave these ports separated for now.

**Comment by atkawa7** [comment]
I will second that @dg0yt

**Comment by Thomas1664** [comment]
agreed
