### ISSUE TITLE
error: building boost-build:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Nick7K** [microsoft/vcpkg#26526]
error: building boost-build:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-build
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-build]+Build+error
Include '[boost-build] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: a9dc9a4b3 2022-08-25 (37 minutes ago)

**Comment by vfekete** [comment]
I too bumped into this problem. Problem was inconsistent hash of boost-build 1.80 (the github path looks wrong, so it downloaded nothing). 

When I checked out commit prior to [[boost] update to 1.80.0](https://github.com/microsoft/vcpkg/commit/8424da584e59e05956913bf96f87654aa3096c7e) it worked ok.

**Comment by thebelin** [comment]
I ran into this issue and it looks like someone stored the wrong hash.

The hotfix above is what fixed it for me.

**Comment by Nick7K** [comment]
Thanks!

**Comment by michaeltryby** [comment]
In case it helps, here is the output. 
'''
Installing 13/43 boost-build:x64-windows...
Building boost-build[core]:x64-windows...
-- Downloading https://github.com/boostorg/build/archive/boost-1.80.0.tar.gz -> boostorg-build-boost-1.80.0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Downloading https://github.com/boostorg/build/archive/boost-1.80.0.tar.gz
Error: Failed to download from mirror set:
File does not have the expected hash:
             url : [ https://github.com/boostorg/build/archive/boost-1.80.0.tar.gz ]
       File path : [ D:\a\vcpkg-boost-example\vcpkg-boost-example\vcpkg\downloads\boostorg-build-boost-1.80.0.tar.gz.2388.part ]
   Expected hash : [ 9076732697f9d8f682b5857f6552b537e7745fedfcee3b82083d497a1f58a795ae73c652ab2a04340b9264155738f4eccfe33095bc996169a4e5117e641644fb ]
     Actual hash : [ 11ac21b27c5c656951784734c6642a2d4efa185e074ec48561f2800203b639d4a628fec6d356bb733494889141327a7ac730ce127449bfc7d509d5d[213](https://github.com/michaeltryby/vcpkg-boost-example/runs/8038384854?check_suite_focus=true#step:5:214)[216](https://github.com/michaeltryby/vcpkg-boost-example/runs/8038384854?check_suite_focus=true#step:5:217)995 ]
'''

**Comment by CBugBuster** [comment]
I have error: building boost-config:x64-windows failed with: BUILD_FAILED
https://github.com/microsoft/vcpkg/issues/36831
