### ISSUE TITLE
[openssl] Build error

### ISSUE THREAD

**Issue by Tangjp-wraith** [microsoft/vcpkg#26543]
**Host Environment**
- OS: Ubuntu 20.04 LTS
- Compiler:  gcc 9.4.0

**To Reproduce**
`./vcpkg install cpr`

**Failure logs**
Computing installation plan...
A suitable version of cmake was not found (required v3.24.0). Downloading portable cmake v3.24.0...
Extracting cmake...
The following packages will be built and installed:
    cpr[core,ssl]:x64-linux -> 1.9.0#1
  * curl[core,non-http,openssl,ssl]:x64-linux -> 7.84.0#1
  * openssl[core]:x64-linux -> 3.0.5#4
  * zlib[core]:x64-linux -> 1.2.12#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Restored 0 package(s) from /home/tang/.cache/vcpkg/archives in 9.618 us. Use --debug to see more details.
Installing 1/4 openssl:x64-linux...
Building openssl[core]:x64-linux...
CMake Warning at ports/openssl/portfile.cmake:7 (message):
  openssl currently requires the following library from the system package
  manager:

      linux-headers

  It can be installed on alpine systems via apk add linux-headers.
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)

-- Downloading https://github.com/openssl/openssl/archive/openssl-3.0.5.tar.gz -> openssl-openssl-openssl-3.0.5.tar.gz...
-- Cleaning sources at /home/tang/CS106L/cs106L-assignment1/vcpkg/buildtrees/openssl/src/nssl-3.0.5-30ecfd0d02.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/tang/CS106L/cs106L-assignment1/vcpkg/downloads/openssl-openssl-openssl-3.0.5.tar.gz
-- Using source at /home/tang/CS106L/cs106L-assignment1/vcpkg/buildtrees/openssl/src/nssl-3.0.5-30ecfd0d02.clean
-- Configuring x64-linux
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: /home/tang/CS106L/cs106L-assignment1/vcpkg/downloads/tools/cmake-3.24.0-linux/cmake-3.24.0-linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j5
    Working Directory: /home/tang/CS106L/cs106L-assignment1/vcpkg/buildtrees/openssl/x64-linux-dbg
    See logs for more information:
      /home/tang/CS106L/cs106L-assignment1/vcpkg/buildtrees/openssl/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/openssl/unix/portfile.cmake:21 (vcpkg_cmake_install)
  ports/openssl/portfile.cmake:39 (include)
  scripts/ports.cmake:147 (include)

error: building openssl:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openssl]+Build+error
Include '[openssl] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: e85b5bb95 2022-08-26 (10 hours ago)

You can also use the prefilled template from /home/tang/CS106L/cs106L-assignment1/vcpkg/installed/vcpkg/issue_body.md.

**Comment by FrankXie05** [comment]
@Tangjp-wraith  Thanks for posting this issue, please install `linux-headers` and try again. :)

**Comment by FrankXie05** [comment]
@Tangjp-wraith Does the issue still occur?

**Comment by Tangjp-wraith** [comment]
@FrankXie05

**Comment by FrankXie05** [comment]
@Tangjp-wraith Please provide the error log. :)

**Comment by Tangjp-wraith** [comment]
@FrankXie05 
```
sudo apt-get install linux-headers-$(uname -r)
sudo apt-get update && sudo apt-get upgrade
```
I use the above code for installing `linux-headers`
but the error log is the same as before.

Computing installation plan...
The following packages will be built and installed:
    cpr[core,ssl]:x64-linux -> 1.9.2
  * curl[core,non-http,openssl,ssl]:x64-linux -> 7.84.0#2
  * openssl[core]:x64-linux -> 3.0.5#4
  * zlib[core]:x64-linux -> 1.2.12#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Restored 0 package(s) from /home/tang/.cache/vcpkg/archives in 142.5 us. Use --debug to see more details.
Installing 1/4 openssl:x64-linux...
Building openssl[core]:x64-linux...
CMake Warning at ports/openssl/portfile.cmake:7 (message):
  openssl currently requires the following library from the system package
  manager:

      linux-headers

  It can be installed on alpine systems via apk add linux-headers.
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)


-- Using cached openssl-openssl-openssl-3.0.5.tar.gz.
-- Cleaning sources at /home/tang/CS106L/cs106L-assignment1/vcpkg/buildtrees/openssl/src/nssl-3.0.5-30ecfd0d02.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/tang/CS106L/cs106L-assignment1/vcpkg/downloads/openssl-openssl-openssl-3.0.5.tar.gz
-- Using source at /home/tang/CS106L/cs106L-assignment1/vcpkg/buildtrees/openssl/src/nssl-3.0.5-30ecfd0d02.clean
-- Configuring x64-linux
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: /home/tang/CS106L/cs106L-assignment1/vcpkg/downloads/tools/cmake-3.24.0-linux/cmake-3.24.0-linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j5
    Working Directory: /home/tang/CS106L/cs106L-assignment1/vcpkg/buildtrees/openssl/x64-linux-dbg
    See logs for more information:
      /home/tang/CS106L/cs106L-assignment1/vcpkg/buildtrees/openssl/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/openssl/unix/portfile.cmake:21 (vcpkg_cmake_install)
  ports/openssl/portfile.cmake:39 (include)
  scripts/ports.cmake:147 (include)


error: building openssl:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openssl]+Build+error
Include '[openssl] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-09-01-dfb82802c8cc562ce3b665a904a65b22314de724
    vcpkg-scripts version: d8f53e80e 2022-09-06 (11 hours ago)

You can also use the prefilled template from /home/tang/CS106L/cs106L-assignment1/vcpkg/installed/vcpkg/issue_body.md.

I post the issue_body.md
[issue_body.md](https://github.com/microsoft/vcpkg/files/9504801/issue_body.md)

**Comment by FrankXie05** [comment]
@Tangjp-wraith Thanks for the info, I will confirm the issue soon. :)

**Comment by FrankXie05** [comment]
@Tangjp-wraith 
````
make[1]: *** [Makefile:2383: apps/lib/libapps-lib-app_params.o] Error 1
/usr/bin/ccache: invalid option -- 'I'
Usage:
    ccache [options]
    ccache compiler [compiler options]
    compiler [compiler options]          (via symbolic link)

Common options:
    -c, --cleanup             delete old files and recalculate size counters
                              (normally not needed as this is done
                              automatically)
    -C, --clear               clear the cache completely (except configuration)
    -F, --max-files=N         set maximum number of files in cache to N (use 0
                              for no limit)
    -M, --max-size=SIZE       set maximum size of cache to SIZE (use 0 for no
                              limit); available suffixes: k, M, G, T (decimal)
                              and Ki, Mi, Gi, Ti (binary); default suffix: G
    -p, --show-config         show current configuration options in
                              human-readable format
    -s, --show-stats          show summary of configuration and statistics
                              counters in human-readable format
    -z, --zero-stats          zero statistics counters

    -h, --help                print this help text
    -V, --version             print version and copyright information

Options for scripting or debugging:
        --dump-manifest=PATH  dump manifest file at PATH in text format
    -k, --get-config=K        print the value of configuration key K
        --hash-file=PATH      print the hash (<MD4>-<size>) of the file at PATH
        --print-stats         print statistics counter IDs and corresponding
                              values in machine-parsable format
    -o, --set-config=K=V      set configuration item K to value V

See also <https://ccache.dev>.
make[1]: *** [Makefile:2385: apps/lib/libapps-lib-app_provider.o] Error 1
````
According to the error log, your system tried to use ccache for compilation caching and could not resolve an unknown parameter "-I".
You should link your ccache with gcc.  See https://stackoverflow.com/questions/1815688/how-to-use-ccache-with-cmake

**Comment by FrankXie05** [comment]
@Tangjp-wraith Does the issue still occur?

**Comment by FrankXie05** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by Tangjp-wraith** [comment]
@FrankXie05  it has been solved
