### ISSUE TITLE
[freetype]Some questions in freetype-targets.cmake

### ISSUE THREAD

**Issue by dbxmm** [microsoft/vcpkg#26542]
### 1.install freetype
vcpkg install freetype:x86-windows-static-md

### 2.use cmake to generate visual studio project
Debug Mode
list(APPEND CMAKE_PREFIX_PATH "${VCPKG_HOME}/installed/x86-windows-static-md")
find_package(freetype CONFIG REQUIRED)
add_executeable(
   exe main.cpp
)
target_link_libraries(exe
    freetype
)

### 3.Visual Studio
duplicate input library
E:\vcpkg\installed\x86-windows-static-md\lib\zlib.lib
E:\vcpkg\installed\x86-windows-static-md\debug\lib\zlibd.lib
![image](https://user-images.githubusercontent.com/9135359/187017388-01c8971e-5996-42f7-a039-e062b4510a09.png)

### 4. see file  "installed\x86-windows-static-md\share\freetype\freetype-targets.cmake"
![image](https://user-images.githubusercontent.com/9135359/187017367-b8add4a7-caba-490c-b6c9-7ecda1438fa6.png)
around line 63
set_target_properties(freetype PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ZLIB::ZLIB>;..."
)

"\$<LINK_ONLY:ZLIB::ZLIB>;"  make visual studio import multiple zlib libraries
**What is the meaning of this line of code, and why does Visual Studio no longer generate duplicate input libraries after deleting it?**

**Comment by dbxmm** [comment]
just add:
list(APPEND CMAKE_PREFIX_PATH "${VCPKG_HOME}/installed/x86-windows-static-md/debug")
We have to tell zlib the location of the debug library directly, which other open source libraries don't need

**Comment by dg0yt** [comment]
> list(APPEND CMAKE_PREFIX_PATH "${VCPKG_HOME}/installed/x86-windows-static-md")

This doesn't give you vcpkg's wrappers (i.e. fixup). Use the vcpkg CMake toolchain instead.

> set_target_properties(freetype PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include" INTERFACE_LINK_LIBRARIES "$<LINK_ONLY:ZLIB::ZLIB>;..." )
> 
> "$<LINK_ONLY:ZLIB::ZLIB>;" make visual studio import multiple zlib libraries **What is the meaning of this line of code, and why does Visual Studio no longer generate duplicate input libraries after deleting it?**

`ZLIB::ZLIB` is an imported target created by CMake's `FindZLIB.cmake` which will carry proper properties for the configuration types zlib was built for. That is, *if you vcpkg's cmake toolchain* which wraps CMake's find module into an extra helper.

> just add:
> list(APPEND CMAKE_PREFIX_PATH "${VCPKG_HOME}/installed/x86-windows-static-md/debug")
> We have to tell zlib the location of the debug library directly, which other open source libraries don't need

No. Use the vcpkg toolchain.

**Comment by dbxmm** [comment]
Hello @dg0yt , thanks for your reply.
What does "use the vcpkg toolchain" mean?
I already have the following code which makes me think I am using the vcpkg toolchain:
`set(CMAKE_TOOCHAIN_FILE ${VCPKG_HOME}/scripts/buildsystems/vcpkg.cmake)`
