### ISSUE TITLE
error: building qt5-webengine:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by RichardsATcn** [microsoft/vcpkg#26546]
Installing 1/1 qt5-webengine:x64-windows...
Building qt5-webengine[core]:x64-windows...
CMake Warning at scripts/cmake/vcpkg_buildpath_length_warning.cmake:4 (message):
  qt5-webengine's buildsystem uses very long paths and may fail on your
  system.

  We recommend moving vcpkg to a short path such as 'C:\src\vcpkg' or using
  the subst command.
Call Stack (most recent call first):
  ports/qt5-webengine/portfile.cmake:4 (vcpkg_buildpath_length_warning)
  scripts/ports.cmake:147 (include)

CMake Warning at ports/qt5-webengine/portfile.cmake:5 (message):
  The qt5-webengine source was will be extracted to
  G:/vcpkg/vcpkg/buildtrees/qt5-webengine , which has more then 35 characters
  in length.
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)

CMake Error at ports/qt5-webengine/portfile.cmake:6 (message):
  terminating due to G:/vcpkg/vcpkg/buildtrees/qt5-webengine being too long.
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)

error: building qt5-webengine:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qt5-webengine
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[qt5-webengine]+Build+error
Include '[qt5-webengine] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: e85b5bb95 2022-08-26 (12 hours ago)

You can also use the prefilled template from G:\vcpkg\vcpkg\installed\vcpkg\issue_body.md.

PS C:\Users\Bluebuger> vcpkg install qt5-webengine:x64-windows
Computing installation plan...
The following packages will be built and installed:
    qt5-webengine[core]:x64-windows -> 5.15.5
Detecting compiler hash for triplet x64-windows...
-- Automatically setting HTTP(S)_PROXY environment variables to "127.0.0.1:10809".
Restored 0 package(s) from C:\Users\Bluebuger\AppData\Local\vcpkg\archives in 253.1 us. Use --debug to see more details.
Installing 1/1 qt5-webengine:x64-windows...
Building qt5-webengine[core]:x64-windows...
CMake Warning at scripts/cmake/vcpkg_buildpath_length_warning.cmake:4 (message):
  qt5-webengine's buildsystem uses very long paths and may fail on your
  system.

  We recommend moving vcpkg to a short path such as 'C:\src\vcpkg' or using
  the subst command.
Call Stack (most recent call first):
  ports/qt5-webengine/portfile.cmake:4 (vcpkg_buildpath_length_warning)
  scripts/ports.cmake:147 (include)

CMake Warning at ports/qt5-webengine/portfile.cmake:5 (message):
  The qt5-webengine source was will be extracted to
  G:/vcpkg/vcpkg/buildtrees/qt5-webengine , which has more then 35 characters
  in length.
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)

CMake Error at ports/qt5-webengine/portfile.cmake:6 (message):
  terminating due to G:/vcpkg/vcpkg/buildtrees/qt5-webengine being too long.
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)

error: building qt5-webengine:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qt5-webengine
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[qt5-webengine]+Build+error
Include '[qt5-webengine] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: e85b5bb95 2022-08-26 (12 hours ago)

You can also use the prefilled template from G:\vcpkg\vcpkg\installed\vcpkg\issue_body.md.

**Comment by JackBoosY** [comment]
```
CMake Error at ports/qt5-webengine/portfile.cmake:6 (message):
terminating due to G:/vcpkg/vcpkg/buildtrees/qt5-webengine being too long.
```
Please clone vcpkg in a shorter path such as _G:/vcpkg_ then try again.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
