### ISSUE TITLE
[boost-serialization] Build error

### ISSUE THREAD

**Issue by coderev** [microsoft/vcpkg#26540]
Hello, I encountered a boost library build error while trying to install `pcl[vtk]`, the error message is as below:

**Host Environment**
- OS: WIN10
- Compiler: VS2022 Community

**To Reproduce**
`./vcpkg install pcl[vtk]`

**Failure logs**
error: building boost-serialization:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-serialization
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-serialization]+Build+error
Include '[boost-serialization] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: e85b5bb95 2022-08-26 (5 hours ago)

You can also use the prefilled template from D:\vcpkg\installed\vcpkg\issue_body.md.

**Additional context**
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/9437123/install-x86-windows-dbg-out.log)
![boost-serialization-installation](https://user-images.githubusercontent.com/11421154/187009884-25107bf3-abc2-420b-861b-609f69df52ac.png)

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. There are the following message in your log:
```
CreateProcessA() Windows API failed: 225 - Ξ·¨³ɹ¦ͪ³ɲٗ÷£¬ҲΪ΄¼þ°üº¬²¡¶¾»򇱔ڵĀ¬»øȭ¼þ¡£
...skipped <pD:\vcpkg\buildtrees\boost-serialization\x86-windows-dbg\stage\lib>boost_serialization-vc143-mt-gd-x32-1_80.dll for lack of <pD:\vcpkg\buildtrees\boost-serialization\x86-windows-dbg\boost\build\be5942cda3c3f2780e89dae0e486e1dd>boost_serialization-vc143-mt-gd-x32-1_80.dll...
compile-c-c++ D:\vcpkg\buildtrees\boost-serialization\x86-windows-dbg\boost\build\be5942cda3c3f2780e89dae0e486e1dd\xml_woarchive.obj
```
Did this file **boost_serialization-vc143-mt-gd-x32-1_80.dll** exist in folder _D:\vcpkg\buildtrees\boost-serialization\x86-windows-dbg\boost\build\be5942cda3c3f2780e89dae0e486e1dd_?
If not, could you please remove the folder _D:\vcpkg\buildtrees\boost-serialization_ and rebuild `boost-serialization:x86-windows`?

**Comment by coderev** [comment]
> 

hi Lily, there is no file **"boost_serialization-vc143-mt-gd-x32-1_80.dll"** located in _D:\vcpkg\buildtrees\boost-serialization\x86-windows-dbg\boost\build\be5942cda3c3f2780e89dae0e486e1dd._
Now I'm trying to remove the entire boost-serialization folder, and install it again.

**Comment by coderev** [comment]
this problem is solved by uninstalling a rogue software called "rav endpoint protection", which was silently installed to the system with BitComet.
