### ISSUE TITLE
Command line option for limiting building processes?

### ISSUE THREAD

**Issue by MrMYHuang** [microsoft/vcpkg#2654]
Could vcpkg provide a command line option for limiting number of building processes?
I was building caffe2 on my PC with Intel Core i7 (4 cores, 8 threads) and  8 GB RAM. My PC went down at the linking stage. Before the down, the task manager showed the build consumed more than 4-GB RAM and the HDD IO LED kept lighting (it seems the physical RAM run out and the virtual memory was massively used).

If I could limit the number of building processes, e.g., to 4 processes, my PC would not run out of physical RAM and finally get a success build (although it would take a longer build time than the one with 8 processes and no out of RAM), isn't it?

**Comment by NancyLi1013** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.

**Comment by j-rivero** [comment]
For reference is someone is looking for limiting building threads using command line, the `VCPKG_MAX_CONCURRENCY` variable can be used, it is documented https://vcpkg.readthedocs.io/en/latest/users/config-environment/.
