### ISSUE TITLE
[gdal] build failure

### ISSUE THREAD

**Issue by deibbun** [microsoft/vcpkg#26550]
**Host Environment**
- OS: Windows 10
- Compiler: VS 2022

**To Reproduce**
`./vcpkg install gdal[mysql-libmariadb]:x64-windows`

**Failure logs**
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/vcpkg/vcpkg/buildtrees/gdal/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg\vcpkg\buildtrees\gdal\config-x64-windows-CMakeCache.txt.log
      C:\vcpkg\vcpkg\buildtrees\gdal\config-x64-windows-CMakeCache.txt.log
      C:\vcpkg\vcpkg\buildtrees\gdal\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:238 (vcpkg_execute_required_process)
  ports/gdal/portfile.cmake:70 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)

error: building gdal:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+gdal
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[gdal]+Build+error
Include '[gdal] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: e85b5bb95 2022-08-26 (13 hours ago)

**Additional context**
Trying to use vcpkg to install mysql but that gives [boost] build errors.  I finally got boost to install by .\vcpkg integrate remove / install commands and install commands alternately.  I used .\vcpkg install sqlpp11-connector-mysql[mysql]:x64-windows and that started the boost build errors.  I found in the logs where GDAL_USE_MSSQL_ODBC=ON is recommended but I don't know which file or where to put this.  I looked in the mentioned config files but can't find this flag.

**Comment by deibbun** [comment]
When I run .\vcpkg install sqlpp11-connector-mysql[mysql]:x64-windows, I get FATAL ERROR:  libmysql and libmariadb are incompatible.  I am trying to install mysql and not mariadb, but some of the installs that worked installed mariadb.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Could you please provide the following error logs?
```
C:\vcpkg\vcpkg\buildtrees\gdal\config-x64-windows-CMakeCache.txt.log
C:\vcpkg\vcpkg\buildtrees\gdal\config-x64-windows-CMakeCache.txt.log
C:\vcpkg\vcpkg\buildtrees\gdal\config-x64-windows-out.log
```

**Comment by noeffn** [comment]
#26366 is related
libmariadb has a duplicate target as it creates a shared and and a static version of the library and also creates a symlink I patched it locally to remove the create_symlink macro call and ninja does not complain anymore but then it has other problems it tries to find a file in share called unofficial-libmariadb that doesnt exist.

**Comment by LilyWangLL** [comment]
> #26366 is related libmariadb has a duplicate target as it creates a shared and and a static version of the library and also creates a symlink I patched it locally to remove the create_symlink macro call and ninja does not complain anymore but then it has other problems it tries to find a file in share called unofficial-libmariadb that doesnt exist.

`libmariadb` will be fixed by PR https://github.com/microsoft/vcpkg/pull/26704.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
