### ISSUE TITLE
why QODBC not included

### ISSUE THREAD

**Issue by MrAhmedSayedAli** [microsoft/vcpkg#26553]
https://github.com/microsoft/vcpkg/blob/e85b5bb95a14ff7e014601e88a8dc2fea6798e33/ports/qtbase/vcpkg.json#L62

**Comment by JackBoosY** [comment]
Do you mean qodbc should be a feature or should qodbc be replaced by sql?

**Comment by MrAhmedSayedAli** [comment]
@JackBoosY vcpkg  build  only qsqlite and qsqlpsql  drivers  {vcpkg install qt:x64-windows  || vcpkg install qtbase:x64-windows }
is ask about how build qsqlodbc driver to use sql server 😅

![image](https://user-images.githubusercontent.com/7157140/187407280-ed33420b-ca45-40df-88d9-3190f25a47f0.png)

**Comment by FrankXie05** [comment]
No stale.
