### ISSUE TITLE
Error: Building package zlib:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by gomggx** [Microsoft/vcpkg#2656]
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:129 (message):
    Command failed: C:/Program Files/vcpkg/downloads/cmake-3.10.2-win32-x86/bin/cmake.exe;--build;.;--config;Release;--target;install;--;-v;-j1
    Working Directory: C:/Program Files/vcpkg/buildtrees/zlib/x86-windows-rel
    See logs for more information:
      C:\Program Files\vcpkg\buildtrees\zlib\install-x86-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/zlib/portfile.cmake:26 (vcpkg_install_cmake)
  scripts/ports.cmake:72 (include)

**Error: Building package zlib:x86-windows failed with: BUILD_FAILED**
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x86-windows
  Vcpkg version: 0.0.103-2018-01-25-92ad00179c2a1adefa55f3d77d7f3165a68b697a

Additionally, attach any relevant sections from the log files above.

========================================================

**"C:\Program Files\vcpkg\buildtrees\zlib\install-x86-windows-rel-out.log" files is :**
........
注意: 包含文件:     C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\corecrt_wstdlib.h
注意: 包含文件:  c:\program files\vcpkg\buildtrees\zlib\src\zlib-1.2.11\trees.h
[16/18] "C:/Program Files/vcpkg/downloads/cmake-3.10.2-win32-x86/bin/cmcldeps.exe" RC "C:\Program Files\vcpkg\buildtrees\zlib\src\zlib-1.2.11\win32\zlib1.rc" CMakeFiles\zlib.dir\win32\zlib1.res.d CMakeFiles\zlib.dir\win32\zlib1.res "עӢ: Ѽڬτݾ:  " "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe" C:\PROGRA~2\WI3CF2~1\8.1\bin\x64\rc.exe -DNO_FSEEKO -DZLIB_DLL -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -I"C:\Program Files\vcpkg\buildtrees\zlib\src\zlib-1.2.11" -I"C:\Program Files\vcpkg\buildtrees\zlib\x86-windows-rel" /DWIN32 /foCMakeFiles\zlib.dir\win32\zlib1.res "C:\Program Files\vcpkg\buildtrees\zlib\src\zlib-1.2.11\win32\zlib1.rc"
FAILED: CMakeFiles/zlib.dir/win32/zlib1.res 
"C:/Program Files/vcpkg/downloads/cmake-3.10.2-win32-x86/bin/cmcldeps.exe" RC "C:\Program Files\vcpkg\buildtrees\zlib\src\zlib-1.2.11\win32\zlib1.rc" CMakeFiles\zlib.dir\win32\zlib1.res.d CMakeFiles\zlib.dir\win32\zlib1.res "עӢ: Ѽڬτݾ:  " "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe" C:\PROGRA~2\WI3CF2~1\8.1\bin\x64\rc.exe -DNO_FSEEKO -DZLIB_DLL -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -I"C:\Program Files\vcpkg\buildtrees\zlib\src\zlib-1.2.11" -I"C:\Program Files\vcpkg\buildtrees\zlib\x86-windows-rel" /DWIN32 /foCMakeFiles\zlib.dir\win32\zlib1.res "C:\Program Files\vcpkg\buildtrees\zlib\src\zlib-1.2.11\win32\zlib1.rc"
cl : 命令行 warning D9035 : cl : 命令行 error D8000 : cl: 命令行 error D8000 : cl: 命令行 error D8000 : cl: 命令行 error D8000 : cl: 命令行 error D8000 : cl: 命令行 error D8000 : cl: 命令行 error D8000 : cl: 命令行 error D8000 : cl: 命令行 error D8000
........

**Comment by JackBoosY** [comment]
Hi @gomggx , there is nothing wrong with build zlib-x86-windows in the newest version. 
It should be fixed. Could you repro it?

**Comment by JackBoosY** [comment]
Please open a new issue if this is still a problem for you.
Thx.
