### ISSUE TITLE
[vcpkg-tool] missing help vor --x-scripts-root

### ISSUE THREAD

**Issue by invy** [microsoft/vcpkg#26565]
**Describe the bug**
I've updated vcpkg-tool to the relatively version from github (commit: 39c475eb57424f11d71ee2ac9c3b3224ebc681ea)
When looking through help menu I didn't found --x-scripts-root option, which is however still present in vcpkg and is correctly evaluated.

**Environment**
- everywhere

**To Reproduce**
1. ./vcpkg help
2. See error
There's no mention of --x-scripts-root option.

**Expected behavior**
--x-scripts-root should be displayed alongside with --x-install-root, x-packages-root, --downloads-root and so on.

**Additional context**
I've found the commit the help was removed in:
https://github.com/microsoft/vcpkg-tool/pull/253#issue-1045346429
Why you don't want people to use it? This is very useful option for custom on-premise vcpkg deployments. And removing one you still keep (and add) others, which makes this removal non-symmetrical.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Now feature `--x-scripts-root` has bug in vcpkg, the related issue: https://github.com/microsoft/vcpkg/issues/8160. If you have question of it, you can comment on this issue https://github.com/microsoft/vcpkg/issues/8160.
