### ISSUE TITLE
[opencv4] Build error

### ISSUE THREAD

**Issue by chuckypt** [microsoft/vcpkg#26578]
**Host Environment**
- OS: windows 10
- Compiler: revision

**To Reproduce**
./vcpkg --triplet=x64-windows-static install opencv4

**Failure logs**
Computing installation plan...
The following packages will be built and installed:
    opencv4[core,default-features,dnn,jpeg,png,quirc,tiff,webp]:x64-windows-static -> 4.6.0#2
Detecting compiler hash for triplet x64-windows-static...
-- Using HTTP(S)_PROXY in environment variables.
Restored 0 packages from C:\Users\Administrator\AppData\Local\vcpkg\archives in 1.6 ms. Use --debug to see more details.Installing 1/1 opencv4:x64-windows-static...
Building opencv4[core,default-features,dnn,jpeg,png,quirc,tiff,webp]:x64-windows-static...
-- Using cached opencv-opencv-4.6.0-1.tar.gz.
-- Cleaning sources at D:/vcpkg/buildtrees/opencv4/src/4.6.0-754ca27223.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/opencv-opencv-4.6.0-1.tar.gz
-- Applying patch 0001-disable-downloading.patch
-- Applying patch 0002-install-options.patch
-- Applying patch 0003-force-package-requirements.patch
-- Applying patch 0004-fix-eigen.patch
-- Applying patch 0005-fix-policy-CMP0057.patch
-- Applying patch 0006-fix-uwp.patch
-- Applying patch 0008-devendor-quirc.patch
-- Applying patch 0009-fix-protobuf.patch
-- Applying patch 0010-fix-uwp-tiff-imgcodecs.patch
-- Applying patch 0011-remove-python2.patch
-- Applying patch 0012-fix-zlib.patch
-- Applying patch 0015-fix-freetype.patch
-- Applying patch 0017-mingw-strsafe-no-deprecate.patch
-- Using source at D:/vcpkg/buildtrees/opencv4/src/4.6.0-754ca27223.clean
-- Using cached opencv-cache/tiny_dnn/adb1c512e09ca2c7a6faef36f9c53e59-v1.0.0a3.tar.gz.
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: D:/vcpkg/downloads/tools/cmake-3.24.0-windows/cmake-3.24.0-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: D:/vcpkg/buildtrees/opencv4/x64-windows-static-dbg
    See logs for more information:
      D:\vcpkg\buildtrees\opencv4\install-x64-windows-static-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:112 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/opencv4/portfile.cmake:459 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building opencv4:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+opencv4
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[opencv4]+Build+error
Include '[opencv4] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: e85b5bb95 2022-08-26 (2 days ago)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Cheney-W** [comment]
Could you please provide us with `D:\vcpkg\buildtrees\opencv4\install-x64-windows-static-dbg-out.log`?
Also, please update your vcpkg to the latest and install this port again.

**Comment by chuckypt** [comment]
> D:\vcpkg\buildtrees\opencv4\install-x64-windows-static-dbg-out.log
[install-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/9442877/install-x64-windows-static-dbg-out.log)

**Comment by chuckypt** [comment]
> Could you please provide us with `D:\vcpkg\buildtrees\opencv4\install-x64-windows-static-dbg-out.log`? Also, please update your vcpkg to the latest and install this port again.
[install-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/9442888/install-x64-windows-static-dbg-out.log)

**Comment by Cheney-W** [comment]
I could install opencv4 successfully with the latest vcpkg 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22.
According to the error log you provided: 
`d:\vcpkg\buildtrees\opencv4\x64-windows-static-dbg\modules\dnn\opencv-caffe.pb.h(17): fatal error C1189: #error:  This file was generated by an older version of protoc which is`

I think you should update your vcpkg first.
