### ISSUE TITLE
[python3] build failure on GCC <= 9.4

### ISSUE THREAD

**Issue by chrismile** [microsoft/vcpkg#26573]
**Host Environment**
- OS: Ubuntu 20.04 (also confirmed on Ubuntu 18.04)
- Compiler: GCC 9.4.0

**To Reproduce**
The build of many built-in Python modules fails silently during the build of the python3 port on Linux systems with older versions of GCC.

`./vcpkg install python3`
`./installed/x64-linux/tools/python3/python3.10 -m ensurepip --upgrade`

Output: `ModuleNotFoundError: No module named 'binascii'`

**Failure logs**

From build-x64-linux-dbg-out.log ([build-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/9440373/build-x64-linux-dbg-out.log)):
```
/usr/bin/cc -pthread -fPIC -Wno-unused-result -Wsign-compare -g -Og -Wall -fPIC -g -fPIC -g -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration -fvisibility=hidden -I./../src/v3.10.5-bfee21776f.clean/Include/internal -I./../src/v3.10.5-bfee21776f.clean/Include -I/home/christoph/Programming/C++/vcpkg/installed/x64-linux/debug/../include -IObjects -IPython -I. -I/usr/include/x86_64-linux-gnu -I/usr/local/include -I/home/christoph/Programming/C++/vcpkg/buildtrees/python3/src/v3.10.5-bfee21776f.clean/Include -I/home/christoph/Programming/C++/vcpkg/buildtrees/python3/x64-linux-dbg -c /home/christoph/Programming/C++/vcpkg/buildtrees/python3/src/v3.10.5-bfee21776f.clean/Modules/binascii.c -o build/temp.linux-x86_64-3.10-pydebug/home/christoph/Programming/C++/vcpkg/buildtrees/python3/src/v3.10.5-bfee21776f.clean/Modules/binascii.o -DUSE_ZLIB_CRC32

[...]

/usr/bin/cc -pthread -shared -L/home/christoph/Programming/C++/vcpkg/installed/x64-linux/debug/lib -L/home/christoph/Programming/C++/vcpkg/installed/x64-linux/debug/lib -L/home/christoph/Programming/C++/vcpkg/installed/x64-linux/debug/lib -fPIC -g build/temp.linux-x86_64-3.10-pydebug/home/christoph/Programming/C++/vcpkg/buildtrees/python3/src/v3.10.5-bfee21776f.clean/Modules/binascii.o -L/home/christoph/Programming/C++/vcpkg/installed/x64-linux/debug/lib -L/usr/lib/x86_64-linux-gnu -L/usr/local/lib -R/home/christoph/Programming/C++/vcpkg/installed/x64-linux/debug/lib -R/usr/lib/x86_64-linux-gnu -R/usr/local/lib -R/lib64 -R/usr/lib64 -R/lib -R/usr/lib -lz -o build/lib.linux-x86_64-3.10-pydebug/binascii.cpython-310d-x86_64-linux-gnu.so

[...]

Failed to build these modules:
_bz2                 _crypt               _ctypes           
_curses              _curses_panel        _elementtree      
_hashlib             _lzma                _sqlite3          
_ssl                 _uuid                binascii          
nis                  pyexpat              zlib              
```

From build-x64-linux-dbg-err.log ([build-x64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/9440371/build-x64-linux-dbg-err.log)):
```
cc: error: unrecognized command line option ‘-R’
```

**Additional context**
I tried manually building Python 3 from source on Ubuntu 20.04, and no `-R` statements are then used for building the built-in Python modules. Thus, the normal build without vcpkg works as expected.

When using vcpkg to build Python 3 on Ubuntu 22.04, the build does not fail, as GCC 11 seems to accept the `-R` flags by now. The `-R` flag seems to originally come from the Clang compiler.

According to this source (https://github.com/rbgirshick/py-faster-rcnn/issues/706), `-Wl,-R` or `-Wl,-rpath=` should be used on GCC instead of `-R`. I can confirm that this solves the problem when manually compiling the .so files.

**Comment by JackBoosY** [comment]
`-R` is comes from the official `configure.ac`:
```
BLDLIBRARY='-Wl,-R,$(LIBDIR) -L. -lpython$(LDVERSION)'
```
I think you need to report this to the upstream first: https://github.com/python/cpython/issues

Thanks.
