### ISSUE TITLE
[New Port Request] userver

### ISSUE THREAD

**Issue by ONLY-VEDA** [microsoft/vcpkg#26584]
Library name: userver

Library description:  userver is the modern open source asynchronous framework with a rich set of abstractions for fast and comfortable creation of C++ microservices, services and utilities. The problem of efficient I/O interactions is solved transparently for the developers.

Source repository URL: https://github.com/userver-framework/userver

Project homepage: https://userver.tech/

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
