### ISSUE TITLE
[<port name>] build failure

### ISSUE THREAD

**Issue by ZRR666** [microsoft/vcpkg#26587]
**Host Environment**
- OS: windows10
vcpkg.exe install v8:x86-windows-static  or vcpkg.exe install v8

error: building v8:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+v8
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[v8]+Build+error
Include '[v8] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: e85b5bb95 2022-08-26 (3 days ago)

You can also use the prefilled template from C:\src\vcpkg\installed\vcpkg\issue_body.md.

**Comment by autoantwort** [comment]
> You can also use the prefilled template from C:\src\vcpkg\installed\vcpkg\issue_body.md

Please use it

**Comment by Cheney-W** [comment]
Dup to https://github.com/microsoft/vcpkg/issues/26588
