### ISSUE TITLE
[New Port Request] libcron

### ISSUE THREAD

**Issue by klarkxy** [microsoft/vcpkg#26590]
Library name: libcron

Library description: About a C++ scheduling library using cron formatting.

Source repository URL: https://github.com/PerMalmberg/libcron

Project homepage (if different from the source repository): https://github.com/PerMalmberg/libcron

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
