### ISSUE TITLE
[gstreamer] gst-plugins-base does not contain opusenc and opusdec

### ISSUE THREAD

**Issue by broothy** [microsoft/vcpkg#26595]
I have installed `gstreamer:x64-windows`.

gst-plugins-base should contain `opusenc` and `opusdec` elements, but they are unavailable, their dlls are not installed. Most probably a configuration switch is not set, but it cannot be modified through the vcpkg options.

**Comment by Adela0814** [comment]
@broothy Please try the PR #26785 .
