### ISSUE TITLE
install multiple triplet in mantest mode

### ISSUE THREAD

**Issue by okhowang** [microsoft/vcpkg#26599]
****

**Is your feature request related to a problem? Please describe.**
I'm building an mac library by cmake and vcpkg.
and I depends on openssl.
there is a `vcpkg.json` as below
```json
{
  "name": "foo",
  "version-string": "0.1.0",
  "dependencies": [
    "openssl"
  ]
}
```
but I want build multiarch(arm64;x86_64) in one cmake build.
but vcpkg manifest mode only install one triplet(x64-osx) on my Mac.
there is not arm64-osx installed

**Proposed solution**

**Describe alternatives you've considered**

**Additional context**

**Comment by LilyWangLL** [comment]
Thanks for posting this issue, you need add `-DVCPKG_TARGET_TRIPLET=arm64-osx` to your install command.

**Comment by okhowang** [comment]
if I add `-DVCPKG_TARGET_TRIPLET=arm64-osx` vcpkg will remove exists `x64-osx` depends.
and I couldn't build with `CMAKE_OSX_ARCHITECTURES=arm64;x86_64` because it's always missing dependencies on one arch

**Comment by LilyWangLL** [comment]
Thanks for your reply. There is a discussion https://github.com/microsoft/vcpkg/discussions/17760 about multiple triplet. And this comment https://github.com/microsoft/vcpkg/discussions/17760#discussioncomment-2554589 indicates that we will implement this feature in the future. 
I think this issue can be closed as duplicate to https://github.com/microsoft/vcpkg/discussions/17760.

**Comment by okhowang** [comment]
got it, thanks
