### ISSUE TITLE
How to add addition  download package mirror  on MacOS

### ISSUE THREAD

**Issue by mullerhai** [microsoft/vcpkg#26608]
HI:
     I used to use scala  java  package management like sbt  or maven ,them can edit the mirror address , as you know ,github in china download is  very slowly, so  I need to add china mirror instead of vcpkg the normal github download url.

so  I have question, how to edit  add download mirror?
thanks

**Comment by FrankXie05** [comment]
@mullerhai Thanks for posting this issue.
For Chinese users, we specially provide mirrors. [http://106.15.181.5/](http://106.15.181.5)
You can set according to the following: 
````
1. Set environment variables
    `X_VCPKG_ASSET_SOURCES` -> `x-azurl,http://106.15.181.5/`
2. Make sure your vcpkg is the latest version
3. Rerun the script `bootstrap-vcpkg`
````
![image](https://user-images.githubusercontent.com/65999885/187651742-517c6608-8b94-4776-9c82-150ff53b4149.png)

We also deployed vcpkg on [gitee](https://gitee.com/jackboosy/vcpkg), you can fork it to quickly download vcpkg. :)

**Comment by mullerhai** [comment]
> bootstrap
thanks,
I have already installed vcpkg, not need to reinstall the vcpkg, just ask install the cpp dependency package use vcpkg.
Are you  sure the command is also make same effect in macos env?I think you just paste the windows vcpkg setting for me,I have exec  set the env variable export X_VCPKG_ASSET_SOURCES=x-azurl:http://106.15.181.5/
but where is the the script `bootstrap-vcpkg` ?

**Comment by mullerhai** [comment]
> thanks,
> I have already installed vcpkg, not need to reinstall the vcpkg, just ask install the cpp dependency package use vcpkg.
> Are you sure the command is also make same effect in macos env?I think you just paste the windows vcpkg setting for me,I have exec set the env variable export X_VCPKG_ASSET_SOURCES=x-azurl:http://106.15.181.5/
> but where is the the script `bootstrap-vcpkg` ?

thanks,
I have already installed vcpkg, not need to reinstall the vcpkg, just ask install the cpp dependency package use vcpkg.
Are you sure the command is also make same effect in macos env?I think you just paste the windows vcpkg setting for me,I have exec set the env variable export X_VCPKG_ASSET_SOURCES=x-azurl:http://106.15.181.5/
but where is the the script bootstrap-vcpkg ?

**Comment by FrankXie05** [comment]
@mullerhai The directory of the `script` is located in the root directory of the `vcpkg` folder. 
For how to download and use the package, you can refer to the documentation https://github.com/microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md

**Comment by FrankXie05** [comment]
@mullerhai Does the issue still occur?

**Comment by FrankXie05** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by mullerhai** [comment]
> We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

very thanks
