### ISSUE TITLE
[icu] Build error

### ISSUE THREAD

**Issue by gene-thomas** [microsoft/vcpkg#26607]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
Windows
- Compiler: revision
    vcpkg-tool version: 2022-08-24-d2c0bb0d74d3bbbcc0bbba1b828079d5f9f88d72
    vcpkg-scripts version: f688b2e29 2022-08-29 (29 hours ago)

**To Reproduce**
`vcpkg.exe install --triplet x64-windows-mega icu`

**Failure logs**

C:>Source>vcpkg>..\2231-transfer\3rdparty_sdk\vcpkg\vcpkg.exe·install·--triplet·x64-windows-mega·icu
Computing installation plan...
The following packages will be built and installed:
    icu[core]:x64-windows-mega -> 69.1#16
Detecting compiler hash for triplet x64-windows-mega...
Restored 0 package(s) from C:\Users\Gene Thomas\AppData\Local\vcpkg\archives in 130.9 us. Use --debug to see more details.
Installing 1/1 icu:x64-windows-mega...
Building icu[core]:x64-windows-mega...
CMake Warning at scripts/cmake/vcpkg_fail_port_install.cmake:2 (message):
  vcpkg_fail_port_install has been removed and all values should be moved by
  adding `supports` field to manifest file or directly adding `icu:=fail` to
  _scripts/ci.baseline.txt_.

  Please remove `vcpkg_fail_port_install(...)`.

Call Stack (most recent call first):
  ports/icu/portfile.cmake:1 (vcpkg_fail_port_install)
  scripts/ports.cmake:147 (include)

-- Using cached icu4c-69_1-src.tgz.
-- Cleaning sources at C:/Source/2231-transfer/3rdparty_sdk/vcpkg/buildtrees/icu/src/c-69_1-src-86e71a956d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Source/2231-transfer/3rdparty_sdk/vcpkg/downloads/icu4c-69_1-src.tgz
-- Applying patch disable-escapestr-tool.patch
-- Applying patch remove-MD-from-configure.patch
-- Applying patch fix_parallel_build_on_windows.patch
-- Applying patch fix-extra.patch
-- Applying patch mingw-dll-install.patch
-- Applying patch disable-static-prefix.patch
-- Using source at C:/Source/2231-transfer/3rdparty_sdk/vcpkg/buildtrees/icu/src/c-69_1-src-86e71a956d.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows-mega
-- Using cached msys-gzip-1.11-1-x86_64.pkg.tar.zst.
-- Using cached msys-bash-5.1.008-1-x86_64.pkg.tar.zst.
-- Using cached msys-autoconf-2.71-3-any.pkg.tar.zst.
-- Using cached msys-diffutils-3.8-2-x86_64.pkg.tar.zst.
-- Using cached msys-binutils-2.37-5-x86_64.pkg.tar.zst.
-- Using cached msys-libtool-2.4.6-9-x86_64.pkg.tar.xz.
-- Using cached msys-file-5.41-2-x86_64.pkg.tar.zst.
-- Using cached msys-zlib-1.2.11-1-x86_64.pkg.tar.xz.
-- Using cached msys-libbz2-1.0.8-3-x86_64.pkg.tar.zst.
-- Using cached msys-coreutils-8.32-2-x86_64.pkg.tar.zst.
-- Using cached msys-grep-3.0-2-x86_64.pkg.tar.xz.
-- Using cached msys-sed-4.8-2-x86_64.pkg.tar.zst.
-- Using cached msys-libpcre-8.45-1-x86_64.pkg.tar.zst.
-- Using cached msys-m4-1.4.19-2-x86_64.pkg.tar.zst.
-- Using cached msys-automake-wrapper-11-4-any.pkg.tar.zst.
-- Using cached msys-gawk-5.1.0-2-x86_64.pkg.tar.zst.
-- Using cached msys-mpfr-4.1.0-1-x86_64.pkg.tar.zst.
-- Using cached msys-gmp-6.2.1-1-x86_64.pkg.tar.zst.
-- Using cached msys-libreadline-8.1.001-1-x86_64.pkg.tar.zst.
-- Using cached msys-ncurses-6.2-2-x86_64.pkg.tar.zst.
-- Using cached msys-automake1.16-1.16.3-3-any.pkg.tar.zst.
-- Using cached msys-perl-5.32.1-2-x86_64.pkg.tar.zst.
-- Using cached msys-libcrypt-2.1-3-x86_64.pkg.tar.zst.
-- Using cached msys-pkg-config-0.29.2-4-x86_64.pkg.tar.zst.
-- Using cached msys-make-4.3-3-x86_64.pkg.tar.zst.
-- Using cached msys-findutils-4.8.0-1-x86_64.pkg.tar.zst.
-- Using cached msys-libintl-0.21-1-x86_64.pkg.tar.zst.
-- Using cached msys-libiconv-1.16-2-x86_64.pkg.tar.zst.
-- Using cached msys-gcc-libs-11.2.0-3-x86_64.pkg.tar.zst.
-- Using cached msys-msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst.
-- Using msys root at C:/Source/2231-transfer/3rdparty_sdk/vcpkg/downloads/tools/msys2/7d0d2a26fa8a8f0c
-- Configuring x64-windows-mega-dbg
-- Configuring x64-windows-mega-rel
-- Building x64-windows-mega-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: C:/Source/2231-transfer/3rdparty_sdk/vcpkg/downloads/tools/msys2/7d0d2a26fa8a8f0c/usr/bin/make.exe -j 17 --trace -f Makefile all
    Working Directory: C:/Source/2231-transfer/3rdparty_sdk/vcpkg/buildtrees/icu/x64-windows-mega-dbg/
    See logs for more information:
      C:\Source\2231-transfer\3rdparty_sdk\vcpkg\buildtrees\icu\build-x64-windows-mega-dbg-out.log
      C:\Source\2231-transfer\3rdparty_sdk\vcpkg\buildtrees\icu\build-x64-windows-mega-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:147 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:2 (vcpkg_build_make)
  ports/icu/portfile.cmake:128 (vcpkg_install_make)
  scripts/ports.cmake:147 (include)

error: building icu:x64-windows-mega failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+icu
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[icu]+Build+error
Include '[icu] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-08-24-d2c0bb0d74d3bbbcc0bbba1b828079d5f9f88d72
    vcpkg-scripts version: f688b2e29 2022-08-29 (29 hours ago)

You can also use the prefilled template from C:\Source\2231-transfer\3rdparty_sdk\vcpkg\installed\vcpkg\issue_body.md.

-Please attach any additional failure logs mentioned in the console output.
attached

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
[build-x64-windows-mega-dbg-err.log](https://github.com/microsoft/vcpkg/files/9458693/build-x64-windows-mega-dbg-err.log)
[build-x64-windows-mega-dbg-out.log](https://github.com/microsoft/vcpkg/files/9458694/build-x64-windows-mega-dbg-out.log)

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated in 1 month, if it is still an issue, please reopen this issue.
