### ISSUE TITLE
vcpkg seems to randomly rebuild all packages when running the CI?

### ISSUE THREAD

**Issue by Pentarctagon** [microsoft/vcpkg#26601]
### Discussed in https://github.com/microsoft/vcpkg/discussions/25525

<div type='discussions-op-text'>

<sup>Originally posted by **Pentarctagon** July  1, 2022</sup>
For the Battle for Wesnoth we're currently using the vcpkg+cmake integration to manage Wesnoth's dependencies on Windows.

These dependencies take quite a while to build - almost an hour, and about twice as long as building Wesnoth itself - so for our Windows CI jobs (with Github Actions) I enabled caching for the built vcpkg dependencies. The problem is that vcpkg seems to decide more or less at random that it needs to rebuild all the dependencies, which then defeats the purpose of caching them. For example (the Windows jobs are the bottom two):
* https://github.com/wesnoth/wesnoth/actions/runs/2580439823 - both the Release and Debug jobs correctly used the cached dependencies, since the `Use cmake` step took under two minutes.
* https://github.com/wesnoth/wesnoth/actions/runs/2580718914 - the CI run for the next commit rebuilds all dependencies for the Debug job, but not the Release job, since the `Use cmake` step took ~52 minutes.
* https://github.com/wesnoth/wesnoth/actions/runs/2582800845 - the CI run for the commit after that is then back to correctly using the cached dependencies.

Important things to note:
* The cache is **not updated** after any of these CI runs. All three used the exact same cache.
* vcpkg itself is always checked out to the [same commit](https://github.com/wesnoth/wesnoth/blob/9d5266d624246a0d4e81537f461ab98de0a94d44/.github/workflows/ci-main.yml#L275-L279) each time.

The question then: Why is cmake/vcpkg only sometimes deciding it needs to rebuild all the dependencies, and how can I get it to stop doing that so it always correctly uses the existing cache?</div>

**Comment by JackBoosY** [comment]
Hi maintainer,
Thanks for posting this issue.
vcpkg will only do a full rebuild of dependency ports when an element in the dependency chain changes (such as bug fix, update, common function changed).
To avoid this rebuild, you can use mainfest mode and set a fixed builtin-baseline.

**Comment by Pentarctagon** [comment]
We do use manifest mode already; what's a fixed builtin-baseline though?

**Comment by JackBoosY** [comment]
See https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md#builtin-baseline.
Just choose a vcpkg github commit id to avoid using the latest commit in every build.

**Comment by Pentarctagon** [comment]
What's the correct format for using that? I tried adding it as https://github.com/wesnoth/wesnoth/blob/b1d740d85d28d38f5df7fdb0258c31e0d01f4358/vcpkg.json#L5-L8 which gives the error:
> unexpected field 'default-registry', did you mean 'default-features'?See https://github.com/Microsoft/vcpkg/tree/master/docs/users/manifests.md for more information.

**Comment by JackBoosY** [comment]
Directly set `"builtin-baseline": "96c35a683eed6695172ebe30d752654d9c0658e6"` in your manifest file root.

**Comment by Pentarctagon** [comment]
Thanks, it seems to be working for now.

**Comment by Pentarctagon** [comment]
This issue has started happening again, even with the `builtin-baseline` set.

As an example: in job https://github.com/wesnoth/wesnoth/actions/runs/4600357907/jobs/8126849573 it was able to successfully create a new cache of the vcpkg dependencies, however just a couple days later it again started rebuilding the whole set of dependencies for unknown reasons (https://github.com/wesnoth/wesnoth/actions/runs/4621553000/jobs/8173116801).

The build error is a result of https://github.com/microsoft/vcpkg/issues/28722, which makes this doubly frustrating since not using the cached dependencies doesn't just result in longer build times, it also often results in build failures.

The builtin-baseline is set in https://github.com/wesnoth/wesnoth/blob/master/vcpkg.json

**Comment by JackBoosY** [comment]
cc @Cheney-W

**Comment by Pentarctagon** [comment]
To provide the answer here as well - the issue is that the github actions runner image is updated frequently along with the compiler and various tools, changing any of which results in vcpkg deciding to rebuild all dependencies. There's not really a solution to this beyond designing a cache key that accurately enough reflects when vcpkg will decide it needs to rebuild everything.
