### ISSUE TITLE
[nvtt] build failure

### ISSUE THREAD

**Issue by david-antiteum** [microsoft/vcpkg#26611]
**Host Environment**
- OS: macOS 12.5
- Compiler: Apple clang version 13.1.6 

**To Reproduce**
`./vcpkg install nvtt`

**Failure logs**

This version of clang does not support `-march=native`. This makes the compilation fail:

```
clang: error: the clang compiler does not support '-march=native'
```

**Additional context**

This simpler solution, a patch in OptimalOptions.cmake to remove `-march=native`, creates problems elsewhere (compilation fails when trying to compile a 32bit version of the app!!!)

**Comment by Cheney-W** [comment]
I have seen many similar issue exist on the Internet on Apple M1, is this your computer?

**Comment by david-antiteum** [comment]
Yes.

**Comment by david-antiteum** [comment]
Extra info. Using this modification of the patch `fix-release-flags.patch` to remove `-march=native` (something that should be done in Apple clang case BTW):

```patch
diff --git a/cmake/OptimalOptions.cmake b/cmake/OptimalOptions.cmake
index e4d5c56..3a77ce9 100644
--- a/cmake/OptimalOptions.cmake
+++ b/cmake/OptimalOptions.cmake
@@ -1,7 +1,7 @@
 
 # Set optimal options for gcc:
 if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
-	SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=native")
+#	SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=native")
 	SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
 ENDIF()
 
@@ -11,8 +11,8 @@ IF(MSVC)
 #	SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /arch:SSE2 /fp:fast")
 
 	# Optimization flags.
-	SET(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS} /O2 /Ob2 /Oi /Ot /Oy /GL")
-	SET(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS} /O2 /Ob2 /Oi /Ot /Oy /GL")
+	SET(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} /O2 /Ob2 /Oi /Ot /Oy /GL")
+	SET(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /O2 /Ob2 /Oi /Ot /Oy /GL")
 	SET(CMAKE_EXE_LINKER_FLAGS_RELEASE "${CMAKE_EXE_LINKER_FLAGS_RELEASE} /LTCG")
 	SET(CMAKE_SHARED_LINKER_FLAGS_RELEASE "${CMAKE_SHARED_LINKER_FLAGS_RELEASE} /LTCG")
 	SET(CMAKE_MODULE_LINKER_FLAGS_RELEASE "${CMAKE_MODULE_LINKER_FLAGS_RELEASE} /LTCG")

```

Compilation starts but give me this errors:

```
/Users/Shared/vcpkg/buildtrees/nvtt/src/2188752e3f-f14c6a0dff.clean/src/nvcore/Debug.h:174:10: error: cast from pointer to smaller type 'uint32' (aka 'unsigned int') loses information
            if (reinterpret_cast<uint32>(ptr) == 0xcccccccc) return false;
...
```

It is compiling the 32bit version for ARM even when `__aarch64__` is defined.

**Comment by Cheney-W** [comment]
I think you could modify that option as `-mcpu=apple-m1`.

**Comment by david-antiteum** [comment]
Using `-mcpu=apple-m1` raises the same problem with the 32bit version.

**Comment by david-antiteum** [comment]
OK, the port uses version 2.1.2, the latest available. A commit after that release adds support for AARCH64. I will contact the maintainer to release a new version if possible and, meanwhile, I will try to patch the current version.

**Comment by david-antiteum** [comment]
And then another include fails (cmp_math_vec4.h) because the use of Intel intrinsics. There is a newer version of CMP_core that probably will work but this is a bit too much for me. So, no NVTT in Apple Silicon
