### ISSUE TITLE
Duplicate field error

### ISSUE THREAD

**Issue by Krisonrik** [Microsoft/vcpkg#2661]
When I run command  vcpkg install "repo_name" it gives me this odd error message in red that says Duplicate field.

What does it mean? I have never seen this error before. 
I originally thought it was because I installed it already, but that wasn't it. It failed to install and trying to remove it will say package not installed.

**Comment by MathiasMagnus** [comment]
I ran into this issue as well and I don't know why it happens or what the solution is. Have you found something?

**Comment by Krisonrik** [comment]
Well, I can't know for sure, but do you have some custom edit to the port files and such for your vcpkg? What I resorted to was completely reinstall vcpkg. The problem went away, not quite sure what's actually causing it though.
