### ISSUE TITLE
[qt] the ax_have_qt.m4 macro fails to detect qt on Windows (possibly clang-cl specific)

### ISSUE THREAD

**Issue by wrobelda** [microsoft/vcpkg#26619]
**Describe the bug**
While building #26363 with `[qt5]` feature enabled, config fails with `checking correct functioning of Qt installation... failure`. `config-err` additionally reports:
```
configure: error: Failed to find matching components of a complete
                  Qt installation. Try using more options,
                  see ./configure --help.
```

The [ax_have_qt.m4](https://www.gnu.org/software/autoconf-archive/ax_have_qt.html) macro is responsible for that.

Initially I thought it was due to `which` command that the macro uses, which `vcpkg_acquire_msys` did not offer for installation. Fixing that (#26618) didn't help, though. Next suspect was the ``QT_DIR=`$QT_QMAKE --version | grep -o -E /.+` `` line in the macro, which is incompatible with `C:/` style paths and ends up trimming the `C:` from the front.  However, after patching it with ``QT_DIR=`$QT_QMAKE --version | grep -o -E "in .+" | cut -c 4-` ``, it still didn't help. Then I thought that a hardcoded `C:/` style path (which is what `qmake --version` offers) for `QT_DIR`  is not expected at this point, given that all other paths (`QT_MOC` and `QT_UIC`) that this macro spits out are of`/c/` Cygwin style, but even after outright patching the macro with a fixed `QT_DIR=/c/...` path, it still fails. 

By that point I had it report:
```
checking for Qt... yes:
    QT_CXXFLAGS=-nologo -W3 -utf-8 -GR -EHsc -MP -Xcompiler -fuse-ld=lld -MDd -Z7 -Ob0 -Od -Xcompiler -RTC1  
    QT_DIR=/c/vcpkg-second/installed/x64-windows/lib
    QT_LIBS=-lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -lcomdlg32 -ladvapi32 
    QT_UIC=/c/vcpkg-second/installed/x64-windows/tools/qt5/bin/uic
    QT_MOC=/c/vcpkg-second/installed/x64-windows/tools/qt5/bin/moc
checking correct functioning of Qt installation... failure
```

Something must then be off with the test application that macro compiles (http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_have_qt.m4), but I did not find time to debug it further, so reporting the issue here to summarize it and get back to it, or hopefully for someone else to fix it by then.

Note that this may be specific to the `clang-cl` that this port uses. 

**Environment**
- OS: Windows
- Compiler: VS2022, 17.3.2

**To Reproduce**
1. Checkout the PR in speech
1. `./vcpkg install libgwenhywfar[cpp,qt5]`
2. See config error. Note that this port still actually fails to build qt5 feature on other platforms, but nonetheless it gets past the config stage there.

**Expected behavior**
`ax_have_qt.m4` should be able to detect the vcpkg-provided Qt on Windows just fine.

**Comment by Neumann-A** [comment]
```
  #### Being paranoid:
  if test x"$have_qt" = xyes; then
    AC_MSG_CHECKING(correct functioning of Qt installation)
    AC_CACHE_VAL(ax_cv_qt_test_result,
    [
      cat > ax_qt_test.h << EOF
#include <qobject.h>
class Test : public QObject
{
Q_OBJECT
public:
  Test() {}
  ~Test() {}
public slots:
  void receive() {}
signals:
  void send();
};
EOF

      cat > ax_qt_main.$ac_ext << EOF
#include "ax_qt_test.h"
#include <qapplication.h>
int main( int argc, char **argv )
{
  QApplication app( argc, argv );
  Test t;
  QObject::connect( &t, SIGNAL(send()), &t, SLOT(receive()) );
}
EOF
```

just force `ax_cv_qt_test_result` ? Or give the `config.log`

**Comment by JackBoosY** [comment]
So I think this issue is resolved?

**Comment by wrobelda** [comment]
It isn’t, needs further debugging. I’ll get to it this week.

**Comment by Cheney-W** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
