### ISSUE TITLE
vcpkg picks up system dependencies if its own don't meet find_package() version criteria

### ISSUE THREAD

**Issue by wrobelda** [microsoft/vcpkg#26625]
**Describe the bug**
I resumed working on a project I haven't touched in a while, which I use with vcpkg in manifest mode via `CMAKE_TOOLCHAIN_FILE`. vcpkg builds all packages just fine, the project in speech compiled fine, but then it kept SIGSEGVs upon launching. After spending a while on debugging it, it turned out that almost all the dependencies (KF5 framework) it had to locate, it loaded from the system `/opt/homebrew` location instead of vcpkg's own.

This is because the project in speech bumped the minimum version of the KF5 packages required, which vcpkg's own don't meet. 

I believe that when using `CMAKE_TOOLCHAIN_FILE`, _if_ a package is provided by vcpkg but otherwise does not meet the version criteria, vcpkg should fail. In any other case, one ends up with some potentially undefined behavior stemming from a frankensteined dev env, and it's easy to miss it during CMake configure stage.

**Comment by JackBoosY** [comment]
Yes. A practice that fully meets the requirements should:
1. Generate the version configuration when generating the cmake configuration.
2. Add version requirements to `find_package`.

However, we cannot enforce that all packages used by users are provided by vcpkg, because vcpkg is still in development and currently accepts a limited number of packages.
So, we must allow the user to use the packages included in the system, but first find and use the appropriate version of the packages that exists in vcpkg.

**Comment by wrobelda** [comment]
> However, we cannot enforce that all packages used by users are provided by vcpkg, because vcpkg is still in development  and currently accepts a limited number of packages.

That's not the point I was making, though.

> So, we must allow the user to use the packages included in the system, but first find and use the appropriate version of the packages that exists in vcpkg.

That's the point: if package _is_ provided by vcpkg but does not meet the _version criteria_, vcpkg _should not pick up the system-wide alternative_. Since user explicitly listed that package in the `vcpkg.json` manifest file, it means that they expect that _this, and this package only_ gets picked up. vcpkg implicitly using system package instead its own is misleading and will inevitably cause unintended behavior. 

Just imagine this scenario: you're building a binary package in CI/CD. One maintainer changed required version in CMakeLists.txt, and vcpkg no longer uses its own package, but instead resorts to a system-wide library that happens to be installed. You end up shipping a binary that is built against different set of packages, without alarming anyone in the process.
