### ISSUE TITLE
use vcpkg to install openssl

### ISSUE THREAD

**Issue by WangHHY19931001** [microsoft/vcpkg#26630]
![image](https://user-images.githubusercontent.com/6965518/187854870-8c74167f-e1e1-49a2-b247-a122bf9d23eb.png)

windows 10 x64

vcpkg install openssl:x64-windows openssl:x64-windows-static

![image](https://user-images.githubusercontent.com/6965518/187855038-107d2984-a140-41a0-bbfe-d664852dcc95.png)

can't done it without kill cmd.exe, please fix it

**Comment by WangHHY19931001** [comment]
now need kill jom.exe sub cmd.exe to done

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Did you install anti-virus on your machine?

**Comment by 333fps** [comment]
Same problem here. No firewall, no anti-virus....

**Comment by WangHHY19931001** [comment]
No firewall, no anti-virus

**Comment by FrankXie05** [comment]
Duplicate of https://github.com/microsoft/vcpkg/issues/24134
