### ISSUE TITLE
[vcpkg upgrade] Give vcpkg list output format which will be suitable for vcpkg install command.

### ISSUE THREAD

**Issue by pravic** [microsoft/vcpkg#2663]
Without doubt `vcpkg upgrade` is a great step forward, but we have sort of inconvenience now if upgrade fails for some reason. In that case we end up with uninstalled old libraries and partly installed the new ones.

Although `vcpkg upgrade` tells what it is going to update, but that list is not convenient to use for retry. I wish there was an additional output of the `upgrade` command, which would tell you how to properly continue or retry upgrade (basically a ready-to-copy list of libraries which can be pasted as an input for `install`).

Or, may be, upgrading should be atomic in ideal world.

@ras0219-msft:

> We did previously have this list as the final output of the `vcpkg update` command; it was something of the form "`vcpkg install openssl:x64-windows openssl:x64-window-static boost:x64-window-static boost:x64-windows .........`".

That would be useful indeed. Or some way to tell `vcpkg list` to print installed libraries in a suitable way for `vcpkg install` would be better? So in this case I'd just backup installed libraries. And it's nice to share your list of libraries to your colleagues or to move it between your computers.

Ideas are welcome!

**Comment by rexdf** [comment]
How about a `.retry` to keep the list ?

**Comment by horenmar** [comment]
I think vcpkg should copy pip a bit, so that something like `pip freeze > requirements.txt` and `pip install -r requirements.txt` is possible.

**Comment by NancyLi1013** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.

**Comment by horenmar** [comment]
What is there to update? Does vcpkg support usage similar to pip freeze and install from file? If yes, close the issue as implemented. If not, the feature is still unimplemented.

**Comment by pravic** [comment]
> if it is still an issue, please reopen.

It is an issue. Why close?

**Comment by BillyONeal** [comment]
@pravic Because there are a lot of bogus stale issues, closing them is a means of poking to see if the issue was valid and/or people still care.

**Comment by pravic** [comment]
If it's a bogus issue, why bother at all? Close immediately and mark as invalid or wontfix.

**Comment by BillyONeal** [comment]
@pravic It was a bulk operation, not a targeted one.

**Comment by PhoebeHui** [comment]
Related to https://github.com/microsoft/vcpkg/discussions/17787

**Comment by PhoebeHui** [comment]
Closing in favor of https://github.com/microsoft/vcpkg/discussions/17922 and https://github.com/microsoft/vcpkg/discussions/17787.

2 features request here:
1. vcpkg upgrade: if one of the packages fails, it should be continue or retry upgrade. Duplicated to https://github.com/microsoft/vcpkg/discussions/17922
2. vcpkg list:  Print installed libraries in a suitable way for vcpkg install. Duplicated to https://github.com/microsoft/vcpkg/discussions/17787
