### ISSUE TITLE
I install grpc，but I meet some problems

### ISSUE THREAD

**Issue by shao12138** [microsoft/vcpkg#26637]
**Describe the bug**

**Environment**
- OS: [e.g. Windows 10]
- Compiler: revision

**To Reproduce**
1. ./vcpkg install xxxx
2. See error
Repro code when

**Expected behavior**

**Failure logs**
C:\Users\ysy>vcpkg install grpc:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * abseil[core]:x64-windows -> 20211102.1
  * c-ares[core]:x64-windows -> 1.18.1#1
    grpc[codegen,core]:x64-windows -> 1.48.0#1
  * openssl[core]:x64-windows -> 3.0.5#4
  * protobuf[core]:x64-windows -> 3.21.4
  * re2[core]:x64-windows -> 2021-11-01
  * upb[codegen,core]:x64-windows -> 2022-04-04
  * vcpkg-cmake[core]:x64-windows -> 2022-07-18
  * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06#1
  * vcpkg-cmake-get-vars[core]:x64-windows -> 2022-05-10#1
  * zlib[core]:x64-windows -> 1.2.12#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
**error: in triplet x64-windows: Unable to find a valid toolchain for requested target architecture x64.
The selected Visual Studio instance is at: C:\Program Files\Microsoft Visual Studio\2022\Community
The available toolchain combinations are:**
See https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md#VCPKG_VISUAL_STUDIO_PATH for more information.
note: updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.

**Additional context**

**Comment by sfhacker** [comment]
https://english-for-chinese.blogspot.com/2008/06/and-meet-problem.html

**Comment by shao12138** [comment]
I hava sove this probles，I install some C++ plugin in VS, Thanks。
