### ISSUE TITLE
exiv2 not installing

### ISSUE THREAD

**Issue by Krisonrik** [Microsoft/vcpkg#2664]
Package: exiv2:x64-windows
  Vcpkg version: 0.0.103-2018-01-26-5c9c1bde53f562c11a5248090ad2c63e7e481633

And the error log as follows:

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ICONV_LIBRARY
    linked by target "cmTC_5525a" in directory C:/Libraries/vcpkg/buildtrees/exiv2/x64-windows-rel/CMakeFiles/CMakeTmp

CMake Error at C:/Program Files/CMake/share/cmake-3.10/Modules/CheckIncludeFile.cmake:60 (try_compile):
  Failed to configure test project build system.
Call Stack (most recent call first):
  config/generateConfigFile.cmake:35 (check_include_file)
  CMakeLists.txt:83 (include)

**Comment by JackBoosY** [comment]
Hi @Krisonrik , this bug should be solved, and I installed exiv2 correctly. Can you help us to have a repro with newest version?

**Comment by Krisonrik** [comment]
Yes, the bug was solved already.
