### ISSUE TITLE
[botan] Build error on arm64-osx

### ISSUE THREAD

**Issue by dinhndrwmacbook** [microsoft/vcpkg#26665]
**Host Environment**
- OS: [Mac OS X]
- Compiler: GNU Clang, Clang++

**To Reproduce**
`./vcpkg install botan`

**Failure logs**

Traceback (most recent call last):
  File "/Users/dinhndrwmacbook/DEV/vcpkg/buildtrees/botan/src/bed3024c4d-4a9d1b25ea.clean/src/scripts/build_docs.py", line 242, in <module>
    sys.exit(main())
  File "/Users/dinhndrwmacbook/DEV/vcpkg/buildtrees/botan/src/bed3024c4d-4a9d1b25ea.clean/src/scripts/build_docs.py", line 206, in main
    if sphinx_supports_concurrency():
  File "/Users/dinhndrwmacbook/DEV/vcpkg/buildtrees/botan/src/bed3024c4d-4a9d1b25ea.clean/src/scripts/build_docs.py", line 131, in sphinx_supports_concurrency
    proc = subprocess.Popen(['sphinx-build', '--version'],
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sphinx-build'

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. You need install `sphinx-build` on your machine, you can refer to https://stackoverflow.com/questions/36137496/os-x-install-of-sphinx-the-sphinx-build-and-sphinx-quickstart-not-found.

**Comment by dinhndrwmacbook** [comment]
A different error:

d: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [botan] Error 1
make: *** Waiting for unfinished jobs....
/Users/dinhndrwmacbook/DEV/vcpkg/buildtrees/botan/src/bed3024c4d-4a9d1b25ea.clean/doc/api_ref/pkcs11.rst:119: WARNING: Duplicate C++ declaration, also defined at api_ref/pkcs11:73.
Declaration is '.. cpp:function:: explicit LowLevel(FunctionListPtr ptr)'.
/Users/dinhndrwmacbook/DEV/vcpkg/buildtrees/botan/src/bed3024c4d-4a9d1b25ea.clean/doc/api_ref/pkcs11.rst:465: WARNING: Duplicate C++ declaration, also defined at api_ref/pkcs11:461.
Declaration is '.. cpp:function:: ObjectProperties(ObjectClass object_class)'.
/Users/dinhndrwmacbook/DEV/vcpkg/buildtrees/botan/src/bed3024c4d-4a9d1b25ea.clean/doc/api_ref/pkcs11.rst:477: WARNING: Duplicate C++ declaration, also defined at api_ref/pkcs11:472.
Declaration is '.. cpp:function:: StorageObjectProperties(ObjectClass object_class)'.
/Users/dinhndrwmacbook/DEV/vcpkg/buildtrees/botan/src/bed3024c4d-4a9d1b25ea.clean/doc/api_ref/pkcs11.rst:502: WARNING: Duplicate C++ declaration, also defined at api_ref/pkcs11:498.
Declaration is '.. cpp:function:: Object(Session& session, ObjectHandle handle)'.
/Users/dinhndrwmacbook/DEV/vcpkg/buildtrees/botan/src/bed3024c4d-4a9d1b25ea.clean/doc/api_ref/pkcs11.rst:506: WARNING: Duplicate C++ declaration, also defined at api_ref/pkcs11:498.
Declaration is '.. cpp:function:: Object(Session& session, const ObjectProperties& obj_props)'.
/Users/dinhndrwmacbook/DEV/vcpkg/buildtrees/botan/src/bed3024c4d-4a9d1b25ea.clean/doc/api_ref/pkcs11.rst:560: WARNING: Duplicate C++ declaration, also defined at api_ref/pkcs11:556.
Declaration is '.. cpp:function:: ObjectFinder(Session& session, const std::vector<Attribute>& search_template)'.

**Comment by LilyWangLL** [comment]
The attached log is empty. `arm64-osx` is community triplet, I have no machine to test this. `botan:x64-osx` can install succeed. You can attach the error log again, maybe other users have idea about this failure.

**Comment by dinhndrwmacbook** [comment]
No works

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
