### ISSUE TITLE
gflags failed

### ISSUE THREAD

**Issue by rexdf** [Microsoft/vcpkg#2666]
Package: gflags:x86-windows
  Vcpkg version: 0.0.103-2018-01-26-5c9c1bde53f562c11a5248090ad2c63e7e481633

```
Building package gflags[core]:x86-windows...
-- CURRENT_INSTALLED_DIR=A:/vcpkg/installed/x86-windows
-- DOWNLOADS=A:/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=A:/vcpkg/packages/gflags_x86-windows
-- CURRENT_BUILDTREES_DIR=A:/vcpkg/buildtrees/gflags
-- CURRENT_PORT_DIR=A:/vcpkg/ports/gflags/.
-- Using cached A:/vcpkg/downloads/gflags-gflags-v2.2.1.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Configuring x86-windows-rel
-- Configuring x86-windows-rel done
-- Configuring x86-windows-dbg
-- Configuring x86-windows-dbg done
-- Build x86-windows-rel
-- Build x86-windows-rel done
-- Build x86-windows-dbg
-- Build x86-windows-dbg done
CMake Error at A:/vcpkg/scripts/cmake/vcpkg_fixup_cmake_targets.cmake:36 (message):
  'A:/vcpkg/packages/gflags_x86-windows/debug/lib/cmake/gflags' does not
  exist.
Call Stack (most recent call first):
  A:/vcpkg/ports/gflags/portfile.cmake:25 (vcpkg_fixup_cmake_targets)
  A:/vcpkg/scripts/ports.cmake:72 (include)


Error: Building package gflags:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: gflags:x86-windows
  Vcpkg version: 0.0.103-2018-01-26-5c9c1bde53f562c11a5248090ad2c63e7e481633

Additionally, attach any relevant sections from the log files above.
```

**Comment by Andyjk1406** [comment]
Identical error for me with x64-windows. I can confirm that I have done 'git pull' and everything is up to date but gflags now won't build

**Comment by bahaki386** [comment]
Same error occured in my environment.
[config-x64-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/1681271/config-x64-windows-rel-out.log)
[install-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/1681272/install-x64-windows-dbg-out.log)
[install-x64-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/1681273/install-x64-windows-rel-out.log)
[config-x64-windows-dbg-err.log](https://github.com/Microsoft/vcpkg/files/1681274/config-x64-windows-dbg-err.log)
[config-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/1681275/config-x64-windows-dbg-out.log)
[config-x64-windows-rel-err.log](https://github.com/Microsoft/vcpkg/files/1681276/config-x64-windows-rel-err.log)

**Comment by MikeGitb** [comment]
Just as a datapoint, I could succesfully run `vcpkg install gflags:x64-windows` with `vcpkg version` returning:

    Vcpkg package management program version 0.0.103-2018-01-30-5700754bd11fe9b22728bd8682c9cfe67a69a462

and the port files pulld freshly from git (5700754bd11fe9).
gflags was not installed prior to this. Is there an option for vcpkg to show exactly which c++ toolset it picked for the build? This might be usefull for narrowig down the cause of such discrepancies.

**Comment by ras0219-msft** [comment]
Thanks everyone for chiming in on this issue!

This was a regression caused by https://github.com/Microsoft/vcpkg/commit/d4cf299de62a97d573445bf55c70816947940072#diff-1bce0c69b5590f23a9f4d712892f4b93 which removed a call to `vcpkg_apply_patches()`. While this would correctly not apply the patch when building from completely clean, the patch will still have been applied to existing users.

I've corrected this in https://github.com/Microsoft/vcpkg/commit/76c28ad78e728cceb9dd0d5f6bec5c3454d74d4d#diff-1bce0c69b5590f23a9f4d712892f4b93 which applies a "revert" patch, which will ensure consistency regardless of the initial state.

Please `git pull` and everything should be good :)
