### ISSUE TITLE
[ffmpeg] Build error

### ISSUE THREAD

**Issue by higithubhi** [microsoft/vcpkg#26666]
**Host Environment**
- OS:Windows 10 21H2 (19044.1766)
- Compiler: msvc

**To Reproduce**
`./vcpkg install ffmpeg`

**Failure logs**
-CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: D:/dev-libs/vcpkg/downloads/tools/msys2/79d5b6b790550399/usr/bin/bash.exe ./build.sh
    Working Directory: D:/dev-libs/vcpkg/buildtrees/ffmpeg/x64-windows-rel
    Error code: 2
    See logs for more information:
      D:\dev-libs\vcpkg\buildtrees\ffmpeg\build-x64-windows-rel-out.log
      D:\dev-libs\vcpkg\buildtrees\ffmpeg\build-x64-windows-rel-err.log

Call Stack (most recent call first):
  ports/ffmpeg/portfile.cmake:550 (vcpkg_execute_required_process)
  scripts/ports.cmake:147 (include)
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
[build-x64-windows-rel-err.log](https://github.com/microsoft/vcpkg/files/9482734/build-x64-windows-rel-err.log)
[build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/9482735/build-x64-windows-rel-out.log)

**Comment by JackBoosY** [comment]
```
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdlib.h(1186): error C2059: 语法错误:“(”
```

Please repair your Visual Studio using Visual Studio Installer then try again.

Thanks.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
