### ISSUE TITLE
[sqlpp11-connector-mysql[mysql]] build failure

### ISSUE THREAD

**Issue by VladislavAlpatov** [microsoft/vcpkg#26668]
**Host Environment**
- OS: [Windows 10 LTSC]
- Compiler: revision

**To Reproduce**
`./vcpkg install sqlpp11-connector-mysql[mysql]:x64-windows-static

**Failure logs**
````
Computing installation plan...
warning: vcpkg appears to be in a Visual Studio prompt targeting x86 but is installing packages for x64-windows-static. Consider using --triplet x86-windows or --triplet x86-uwp.
The following packages will be built and installed:
  * libmariadb[core,schannel,ssl]:x64-windows-static -> 3.1.15
  * sqlpp11[core,mariadb,mysql]:x64-windows-static -> 0.61
    sqlpp11-connector-mysql[core,mariadb,mysql]:x64-windows-static -> 0.61
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows-static...
Restored 0 package(s) from C:\Users\Vlad\AppData\Local\vcpkg\archives in 276.4 us. Use --debug to see more details.
Installing 1/3 libmariadb:x64-windows-static...
Building libmariadb[core,schannel,ssl]:x64-windows-static...
CMake Error at ports/libmariadb/portfile.cmake:2 (message):
  FATAL ERROR: libmysql and libmariadb are incompatible.
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)


error: building libmariadb:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libmariadb
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libmariadb]+Build+error
Include '[libmariadb] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: unknown

You can also use the prefilled template from C:\Users\Vlad\vcpkg\installed\vcpkg\issue_body.md.
````

**Comment by FrankXie05** [comment]
@VladislavAlpatov Thanks for posting this issue.

It can be seen from the error message: there is a conflict between `libmysql` and `libmariadb`.
If you wish to install `libmysql`, please remove `libmariadb` and try again.
````
CMake Error at ports/libmariadb/portfile.cmake:2 (message):
  FATAL ERROR: libmysql and libmariadb are incompatible.
````
Thanks.

**Comment by VladislavAlpatov** [comment]
i removed mariadb and still keep getting errors
`C:\Users\Vlad>vcpkg install sqlpp11-connector-mysql[mysql]:x64-windows-static
Computing installation plan...
The following packages will be built and installed:
  * libmariadb[core,schannel,ssl]:x64-windows-static -> 3.1.15
  * libmysql[core]:x64-windows-static -> 8.0.20#7
  * sqlpp11[core,mariadb,mysql]:x64-windows-static -> 0.61
    sqlpp11-connector-mysql[core,mariadb,mysql]:x64-windows-static -> 0.61
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows-static...
Restored 2 package(s) from C:\Users\Vlad\AppData\Local\vcpkg\archives in 4.136 s. Use --debug to see more details.
Installing 1/4 libmariadb:x64-windows-static...
Elapsed time to handle libmariadb:x64-windows-static: 111.5 ms
Installing 2/4 libmysql:x64-windows-static...
The following files are already installed in C:/Users/Vlad/vcpkg/installed/x64-windows-static and are in conflict with libmysql:x64-windows-static

Installed by libmariadb:x64-windows-static
    include/mysql/errmsg.h
    include/mysql/mysql.h
    include/mysql/mysql/client_plugin.h
    include/mysql/mysql/plugin_auth_common.h
    include/mysql/mysqld_error.h

Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libmysql
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libmysql]+Build+error
Include '[libmysql] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: unknown

**Comment by dg0yt** [comment]
In vcpkg, you must not use libmariadb and libmysql at the same time. The install command must opt-out of default features:
~~~
vcpkg install sqlpp11-connector-mysql[core,mysql]:x64-windows-static
~~~
Note the `core`.

**Comment by FrankXie05** [comment]
@VladislavAlpatov 
Please run the following commands: 
````
./vcpkg remove libmariadb:x64-windows-static
./vcpkg remove libmariadb:x64-windows
./vcpkg install sqlpp11-connector-mysql[core,mysql]:x64-windows-static
````

**Comment by dg0yt** [comment]
> ~~~
> ./vcpkg remove libmariadb:x64-windows

Not relevant for x64-windows-static.

**Comment by FrankXie05** [comment]
Yes, just for `static`. :)

**Comment by FrankXie05** [comment]
@VladislavAlpatov Does the issue still occur?

**Comment by FrankXie05** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
