### ISSUE TITLE
Question: Error finding google protobuf with FindProtobuf

### ISSUE THREAD

**Issue by dibyendumajumdar** [microsoft/vcpkg#2670]
Hi, recently I tried to use vcpkg but faced some problems. I provided the CMake command line the option to include the toolchain file as recommended. Then I expected following to work:

https://cmake.org/cmake/help/v3.10/module/FindProtobuf.html

However it did not seem to work - as it complained that Protobuf could not be found. 

If I run vcpkg list it shows:
```
protobuf:x64-windows-static                        3.5.0-1          Protocol Buffers - Google's data interchange format
```

When I run CMake build with:
```
cmake -DCMAKE_TOOLCHAIN_FILE=C:/work/vcpkg/scripts/buildsystems/vcpkg.cmake -G "Visual Studio 15 2017 Win64" -DVCPKG_TARGET_TRIPLET=x86-windows-static ..
```
CMake complains:

```
CMake Error at C:/Program Files/CMake/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Protobuf (missing: Protobuf_LIBRARIES Protobuf_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.10/Modules/FindProtobuf.cmake:543 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  C:/work/vcpkg/scripts/buildsystems/vcpkg.cmake:227 (_find_package)
  CMakeLists.txt:16 (find_package)
```

Since I have a multi-platform project, I needed to have this working the same way as it works on Linux. 

My question is: is this supposed to work? That is, after including the toolchain script, should the CMake modules work as they do in other platforms?

Thanks and Regards

**Comment by MikeGitb** [comment]
My guess would be that `protobuf:x64-windows-static` and `-DVCPKG_TARGET_TRIPLET=x86-windows-static` are incompatible due to the x86 / x64 mismatch.

**Comment by arthur-tacca** [comment]
I had the same problem and my triplets *did* match - both `x64-windows-static`. I think it is a bug in `FindProtoBuf.cmake` that comes with CMake. For me it was resolved by just upgrading the CMake version on my computer (I was using a separate installation rather than letting vcpkg download it automatically). I also slightly changed my CMakeLists.txt and rebuilt a couple of packages, so maybe updating CMake wasn't really the solution, but I thought it worth mentioning.

**Comment by devhandle** [comment]
@arthur-tacca I'm having the same issue. What changes did you make to your CMakeLists.txt?

**Comment by arthur-tacca** [comment]
@devhandle  I forget but I think it was the CMake upgrade, rather than the CMakeLists.txt change, that was important. What version of CMake are you using?

I certainly didn't add the protoc path to the PATH variable. That sounds like a recipe for long term pain!

**Comment by NancyLi1013** [comment]
Hi all,

Thanks for joining in the discussion about this issue.
`protobuf `has been updated. Please try to update vcpkg and rebuild it.

The usage like this:
```
find_package(protobuf CONFIG REQUIRED)
target_link_libraries(main PRIVATE protobuf::libprotoc protobuf::libprotobuf protobuf::libprotobuf-lite)
```
Please open an issue if you have any other problems about this.
