### ISSUE TITLE
[New Port Request] curl-impersonate

### ISSUE THREAD

**Issue by Kaspek2480** [microsoft/vcpkg#26716]
Library name: curl-impersonate

Library description: A special build of [curl](https://github.com/curl/curl) that can impersonate the four major browsers: Chrome, Edge, Safari & Firefox. curl-impersonate is able to perform TLS and HTTP handshakes that are identical to that of a real browser.

Source repository URL: https://github.com/lwthiker/curl-impersonate

**Comment by Kaspek2480** [comment]
@Adela0814 what is estimated time?

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
