### ISSUE TITLE
[OpenImageIO] doesn't bulid for arm64-osx (or arm64-ios)

### ISSUE THREAD

**Issue by MarkCallow** [microsoft/vcpkg#26726]
**Host Environment**
- OS: macOS 12.5 Monterey on x64 Mac
- Compiler: Apple clang version 13.1.6 (clang-1316.0.21.2.5)

**To Reproduce**
`./vcpkg install openimageio:arm64-osx`

**Failure logs**
```
Computing installation plan...
x265[core]:arm64-osx is only supported on '!(uwp | arm)'
```

**Additional context**

**Comment by Cheney-W** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.

**Comment by MarkCallow** [comment]
Please reopen. As there has been no fix it is still an issue.

I've given up trying to use OIIO, in part because of this.

**Comment by dg0yt** [comment]
I don't think that the issue still exists:
~~~
$ ./vcpkg install --dry-run x265:arm64-osx
Computing installation plan...
The following packages will be built and installed:
    x265[core]:arm64-osx -> 3.4#8
~~~
x265 was changed app. 7 weeks ago.
