### ISSUE TITLE
Port is missing

### ISSUE THREAD

**Issue by Amit-Mnnit929** [microsoft/vcpkg#26728]
I have Augustin Popa blog https://devblogs.microsoft.com/cppblog/registries-bring-your-own-libraries-to-vcpkg/
to implement vcpkg registry but while installation after creation of package its showing port is missing 
I do not understand the issue please some one guide me
```ps
C:\DEV\vcpkg>vcpkg install pt4all --overlay-ports="C:/repo/vcpkg-registry/ports/pt4all"
Computing installation plan...
The following packages will be built and installed:
    pt4all[core]:x86-windows -> 1.0.0 -- C:/repo/vcpkg-registry/ports/pt4all
Detecting compiler hash for triplet x86-windows...
Restored 0 package(s) from C:\Users\1032538\AppData\Local\vcpkg\archives in 148.9 us. Use --debug to see more details.
Installing 1/1 pt4all:x86-windows...
Building pt4all[core]:x86-windows...
-- Installing port from location: C:/repo/vcpkg-registry/ports/pt4all
CMake Error at scripts/ports.cmake:113 (message):
  Port is missing portfile:
  C:/repo/vcpkg-registry/ports/pt4all/portfile.cmake
```

D:\a\_work\1\s\src\vcpkg\build.cpp(1321): copy_file("C:\DEV\vcpkg\buildtrees\pt4all\x86-windows.vcpkg_abi_info.txt", "C:\DEV\vcpkg\packages\pt4all_x86-windows\share\pt4all\vcpkg_abi_info.txt"): The file exists.

**Comment by JackBoosY** [comment]
Can you please provide your manifest file?

Thanks.

**Comment by Amit-Mnnit929** [comment]
{
	"name": "pt4all",
	"version": "1.0.0",
	"description": "pt4all library",
	"homepage": "https://github.com/Amit-Mnnit929/pt4all"
}

**Comment by JackBoosY** [comment]
We don't have a port named `pt4all`, so you need to create a port folder that contains `portfile.cmake` and `vcpkg.json`.
The mainfest file is only implement the dependency relationship and version info.

**Comment by Amit-Mnnit929** [comment]
I have already created ports folder with portfile.cmake and vcpkg.json file 
![Screenshot (75)](https://user-images.githubusercontent.com/60483671/189330381-2d70abd3-d591-47e0-866f-48f72c6c99ae.png)

But I do not understand from where do I get REF and SHA512 value

**Comment by JackBoosY** [comment]
Can you please provide the 2 file `portfile.cmake` and `vcpkg.json`?

**Comment by Amit-Mnnit929** [comment]
->portfile.cmake

vcpkg_from_github(
	OUT_SOURCE_PATH SOURCE_PATH
	REPO Amit-Mnnit929/pt4all
	REF 9f8ffdcc8757ae518b6473c2f2ebe794633f1a08
	SHA512 95fc2a7b541c0da5ff550457d84d3081873374babdff98a4345029a6e58c0f544f7668b058c4fb5581eba37f5e7e687963f35e2360717e3f0c72c4e67e5358d9
	HEAD_REF main
)

vcpkg_configure_cmake(
	SOURCE_PATH "${SOURCE_PATH}"
	PREFER_NINJA
)
vcpkg_install_cmake()
vcpkg_fixup_cmake_targets()

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")

file(
	INSTALL "${SOURCE_PATH}/LICENSE"
	DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}"
	RENAME copyright)

---------------------------------------------------------------------------------------------------------------------------------------
-> vcpkg.json

{
	"name": "pt4all",
	"version": "1.0.0",
	"description": "pt4all library",
	"homepage": "https://github.com/Amit-Mnnit929/pt4all"
}

**Comment by JackBoosY** [comment]
```ps
C:\DEV\vcpkg>vcpkg install pt4all --overlay-ports="C:/repo/vcpkg-registry/ports/pt4all"
```
Should be:
```ps
C:\DEV\vcpkg>vcpkg install pt4all --overlay-ports="C:/repo/vcpkg-registry/ports"
```
BTW, the repo is unavaliable, please check again.

**Comment by Amit-Mnnit929** [comment]
Actually the repo(https://github.com/Amit-Mnnit929/pt4all) is private in my github that's why your are not able to see that

**Comment by Amit-Mnnit929** [comment]
I tried both above mentioned --overlay-ports but now I am getting different error i.e.,

![Screenshot (79)](https://user-images.githubusercontent.com/60483671/189885122-ef503866-3d2d-4ec9-9c7a-814dfce599a4.png)


![Screenshot (80)](https://user-images.githubusercontent.com/60483671/189885159-2cd1d0a8-f6c4-4919-86b0-3fdb6e001d2e.png)

**Comment by JackBoosY** [comment]
See https://github.com/microsoft/vcpkg/blob/d699e78f848027d18d337e6ae4803c2c7c18dbbb/docs/users/authentication.md

**Comment by MonicaLiu0311** [comment]
Is there any progress?
