### ISSUE TITLE
[colmap] Build error

### ISSUE THREAD

**Issue by vdelale** [microsoft/vcpkg#26739]
Hi, I'm trying to build colmap thanks to vcpkg, but I keep stumbling on an error. Below you can find the host environnment, the command executed and the failures logs and the log file.

I have already used the `git pull` , `vcpkg update` and `vcpkg upgrade --no-dry-run` commands, but I still get the following error.

Package: colmap[core,cuda,tests]:x64-windows -> 2022-03-14
**Host Environment**
- Host: x64-windows
- Compiler: MSVC 19.33.31629.0
-    vcpkg-tool version: 2022-09-01-dfb82802c8cc562ce3b665a904a65b22314de724
    vcpkg-scripts version: 1ddafcb6f 2022-09-08 (16 hours ago)

**To Reproduce**
`vcpkg install colmap[cuda,tests]:x64-windows`

**Failure logs**
```
-- Using cached colmap-colmap-29a1e3642a3b00734a52b21e597ea4d576485fe6.tar.gz.
-- Cleaning sources at C:/Users/consultant/vcpkg/buildtrees/colmap/src/d576485fe6-7dd36362d1.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/consultant/vcpkg/downloads/colmap-colmap-29a1e3642a3b00734a52b21e597ea4d576485fe6.tar.gz
-- Applying patch fix-dependencies.patch
-- Using source at C:/Users/consultant/vcpkg/buildtrees/colmap/src/d576485fe6-7dd36362d1.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: C:/Users/consultant/vcpkg/downloads/tools/cmake-3.24.0-windows/cmake-3.24.0-windows-i386/bin/cmake.exe --build . --config Release --target install -- -v -j9
    Working Directory: C:/Users/consultant/vcpkg/buildtrees/colmap/x64-windows-rel
    See logs for more information:
      C:\Users\consultant\vcpkg\buildtrees\colmap\install-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/colmap/portfile.cmake:53 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)
```

**Log file**
[install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/9536053/install-x64-windows-rel-out.log)

Do you have any idea what the problem might be ? Thanks in advance.

**Comment by JackBoosY** [comment]
```
C:\Users\consultant\vcpkg\installed\x64-windows\include\Eigen\src\Core\PlainObjectBase.h(591) : fatal error C1001: Internal compiler error.
(compiler file 'D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 224)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com 
Please choose the Technical Support command on the Visual C++ 
 Help menu, or open the Technical Support help file for more information
  cl!RaiseException()+0x69
  cl!RaiseException()+0x69
  cl!DllGetObjHandler()+0xdb94f
  cl!DllGetObjHandler()+0x100aac
```

Please report this issue to [Visual Studio feedback](https://developercommunity.visualstudio.com/report?space=62&entry=problem) instead.

Thanks.

**Comment by vdelale** [comment]
@JackBoosY I have Visual Studio 2022 installed. Would you recommand to install the older 2019 version in order to build colmap ?

**Comment by JackBoosY** [comment]
I can't promise the older Visual Studio version doesn't has this bug.
And we already received many same issues such as https://github.com/microsoft/vcpkg/issues/25303.

Anyway, you can have a try.
