### ISSUE TITLE
package qtdeclarative 6.3 is failing to build

### ISSUE THREAD

**Issue by r9guy** [microsoft/vcpkg#26730]
qtdeclarative 6.3.1 is failing to build

- OS: Windows 10
- Compiler: Visual Studio 2022

**To Reproduce**
1. ./vcpkg install qtdeclariative:x64-Windows
2. See error
`error: building qtdeclarative:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qtdeclarative
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[qtdeclarative]+Build+error
Include '[qtdeclarative] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-09-01-dfb82802c8cc562ce3b665a904a65b22314de724
    vcpkg-scripts version: 927006b24 2022-09-02 (6 days ago)

You can also use the prefilled template from C:\Users\ArshamA\vcpkg\installed\vcpkg\issue_body.md.`

**Comment by Neumann-A** [comment]
no useable logs..... I would guess `C:\Users\ArshamA\vcpkg` is too long of a root dir for it to work.

**Comment by r9guy** [comment]
> 
log is attached. 
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/9531091/install-x64-windows-dbg-out.log)

**Comment by Adela0814** [comment]
The latest `qtdeclarative `version is `6.3.1`.  I'm not able to repro this issue, could you please `git pull `the latest `vcpkg` and try again?

**Comment by Neumann-A** [comment]
@Adela0814 this is a known issue if the build path is too long. see e.g. https://github.com/microsoft/vcpkg/issues/23714

`C:\Users\ArshamA\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickDialogs2QuickImpl\6.3.1\QtQuickDialogs2QuickImpl\private/qtquickdialogs2quickimplforeign_p.h(1): fatal error C1083: Cannot open include file: '../../../../../../src/here-src-6-b9307f657e.clean/src/quickdialogs2/quickdialogs2quickimpl/qtquickdialogs2quickimplforeign_p.h': No such file or directory
`

**Comment by Adela0814** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
