### ISSUE TITLE
安装不上vcpkg

### ISSUE THREAD

**Issue by njuxdj** [Microsoft/vcpkg#2673]
操作系统：win10，按照文档clone到本地后，执行bootstrap-vcpkg.bat报错，错误信息如下：
PS D:\vcpkg> .\bootstrap-vcpkg.bat
Downloading vswhere...
使用“2”个参数调用“DownloadFile”时发生异常:“无法连接到远程服务器”
所在位置 D:\vcpkg\scripts\VcpkgPowershellUtils.ps1:116 字符: 5
+     $wc.DownloadFile($url, $downloadPartPath)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Move-Item : 找不到路径“D:\vcpkg\downloads\vswhere-2.3.2\vswhere.exe.part”，因为该路径不存在。
所在位置 D:\vcpkg\scripts\VcpkgPowershellUtils.ps1:117 字符: 5
+     Move-Item -Path $downloadPartPath -Destination $downloadPath
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\vcpkg\downlo...swhere.exe.part:String) [Move-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.MoveItemCommand

Downloading vswhere has completed successfully.
Resolve-Path : 找不到路径“D:\vcpkg\downloads\vswhere-2.3.2\vswhere.exe”，因为该路径不存在。
所在位置 C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.p
sm1:110 字符: 36
+                 $pathsToProcess += Resolve-Path $Path | Foreach-Objec ...
+                                    ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\vcpkg\downlo...3.2\vswhere.exe:String) [Resolve-Path], ItemNotFoundE
   xception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ResolvePathCommand

不能对 Null 值表达式调用方法。
所在位置 D:\vcpkg\scripts\VcpkgPowershellUtils.ps1:80 字符: 12
+     return $hash.ToLower()
+            ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) []，RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

vcpkgCheckEqualFileHash : 无法将参数绑定到参数“actualHash”，因为该参数为空字符串。
所在位置 D:\vcpkg\scripts\fetchDependency.ps1:86 字符: 107
+ ... ectedHash $expectedDownloadedFileHash -actualHash $downloadedFileHash
+                                                       ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [vcpkgCheckEqualFileHash]，ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,vcpkgCheckEqualFileHash

Could not detect or download vswhere
所在位置 D:\vcpkg\scripts\fetchDependency.ps1:116 字符: 9
+         throw ("Could not detect or download " + $Dependency)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not detect or download vswhere:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not detect or download vswhere

PS D:\vcpkg>

**Comment by wdx04** [comment]
You'll need a good VPN to be able to download the required files

**Comment by IULOVE** [comment]
下不了网络问题 FQ 或手动 去下载试试！ ，，手动下载完放到 downloads 目录就行了，但是名字要改好 vcpkg就会识别 , 不知道名字 看 downloads\temp 目录 没下载完的都在这里.

**Comment by vanxining** [comment]
Close this issue PLEASE.
关闭这个碍眼的 issue 吧，毫无建设性，开发组看得懂中文吗？
