### ISSUE TITLE
[New Port Request] libecc

### ISSUE THREAD

**Issue by kairisku** [microsoft/vcpkg#26733]
Library name: libecc

Library description: a library for elliptic curves based cryptography (ECC)

Source repository URL: https://github.com/ANSSI-FR/libecc

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
