### ISSUE TITLE
[vcpkg-tool] PATH set from toolchain file ignored, works when set _before_ calling vcpkg

### ISSUE THREAD

**Issue by omartijn** [microsoft/vcpkg#26749]
**Describe the bug**
For cross-compiling to macos I add a path from the toolchain to my PATH so that some tools (like `lipo` are found. This works if I use the toolchain file directly in CMake and do e.g. `execute_process`. However, when making a triplet and using `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` the path isn't set and `lipo` isn't found

**Environment**
- OS: Linux
- Compiler: Irrelevant

**To Reproduce**
1. Create a cross-compile toolchain
2. Make a cross-compile triplet and chainload the toolchain

**Expected behavior**
The package should build and tools in the PATH should be found

**Failure logs**
error: unable to determine the architectures of /home/martijn/git/vcpkg/packages/fmt_osxcross/debug/lib/libfmtd.a.
lipo -archs /home/martijn/git/vcpkg/packages/fmt_osxcross/debug/lib/libfmtd.a
error: lipo failed with exit code: (127).
sh: 1: lipo: not found

**Additional context**

**Comment by JackBoosY** [comment]
Can you please provide a sample toolchain file to reproduce this issue?

Thanks.

**Comment by Neumann-A** [comment]
the toolchain is loaded by cmake not by vcpkg. You need to setup the environment in the triplet if it should take effect within the script run of vcpkg.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
