### ISSUE TITLE
[New Port Request] wiiuse

### ISSUE THREAD

**Issue by matteoturini** [microsoft/vcpkg#26758]
Library name: wiiuse

Library description: wiiuse is a library to interact with wiimotes

Source repository URL: https://github.com/wiiuse/wiiuse

Project homepage (if different from the source repository): N/A

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
No optional features. Has CMake as a build system already.

**Comment by matteoturini** [comment]
bump

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
