### ISSUE TITLE
[New Port Request] ZLMediaKit

### ISSUE THREAD

**Issue by xilutian** [microsoft/vcpkg#26750]
Library name: ZLMediaKit

Library description: WebRTC/RTSP/RTMP/HTTP/HLS/HTTP-FLV/WebSocket-FLV/HTTP-TS/HTTP-fMP4/WebSocket-TS/WebSocket-fMP4/GB28181/SRT server and client framework based on C++11

Source repository URL: https://github.com/ZLMediaKit/ZLMediaKit

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by xilutian** [comment]
Has it been added? What's the name of respository

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
