### ISSUE TITLE
Port Request: vips

### ISSUE THREAD

**Issue by angelmixu** [microsoft/vcpkg#2676]
Hi people!

I'd like to use vips library, for imaging process, it's quite used on PHP and lately on Node, also for C++.

This is the project on github: https://github.com/jcupitt/libvips

The current buildsystem is based on MinGW and it's difficult compiling it when working on MSVC.
I've seen some CMake files for building, but I don't know in which state is it.

The author is very nice and answers quickly, and you can contact me if you need any help.

Thanks!

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
