### ISSUE TITLE
[nss] Import lib names not matching with official documentation

### ISSUE THREAD

**Issue by longnguyen2004** [microsoft/vcpkg#26760]
****

From the "Naming conventions and special libraries" of the [official documentation](https://firefox-source-docs.mozilla.org/security/nss/legacy/introduction_to_network_security_services/index.html#naming_conventions_and_special_libraries)

> ...So the NSS library has the following forms:
> - `libnss3.so` - Unix shared library
> - `libnss3.sl` - HP-UX shared library
> - `libnss.a` - Unix static library
> - `nss3.dll` - Windows shared library
> - `nss3.lib` - Windows import library binding to `nss3.dll`
> - `nss.lib` - Windows static library

However, installing the `nss` port results in `nss3.dll.lib` being generated, which doesn't match with upstream.

**Comment by Adela0814** [comment]
I tried installing `nss` on `x64-windows` and I got `vcpkg\installed\x64-windows\lib\nss.dll.lib` and `vcpkg\installed\x64-windows\bin\nss.dll`. I think this matches the upstream.

**Comment by longnguyen2004** [comment]
Upstream said the import lib should be `nss3.lib` (see above), so it doesn't match
Also, this breaks the assumption that `find_library(NSS_LIB nss3)` works everywhere, so that's a problem
I'll try to build it outside of vcpkg, to see if the bug still exists

**Comment by Adela0814** [comment]
@plq Could you help explain this?

**Comment by Adela0814** [comment]
@longnguyen2004 We hope your question was answered to your satisfaction.
