### ISSUE TITLE
use the libhv:x64-windows-static , linker can't resolve symbol

### ISSUE THREAD

**Issue by heheda123123** [microsoft/vcpkg#26777]
**Describe the bug**
use the libhv:x64-windows-static , linker can't resolve symbol

**Environment**
- OS:windows
- Compiler: visual studio 2019

**To Reproduce**
1. ./vcpkg install libhv:x64-windows-static
2. use follow code and do the following settings 
```
#include "hv/hv.h"

int main() {
    char exe_filepath[MAX_PATH] = { 0 };
    char run_dir[MAX_PATH] = { 0 };

    // 获取hv编译版本
    const char* version = hv_compile_version();

    // 获取可执行文件路径
    get_executable_path(exe_filepath, sizeof(exe_filepath));
    // 获取运行目录
    get_run_dir(run_dir, sizeof(run_dir));

    printf("exe_filepath=%s\n", exe_filepath);
    printf("run_dir=%s\n", run_dir);

    // 写日志
    LOGI("libhv version: %s", version);

    return 0;
}

```
![image](https://user-images.githubusercontent.com/97490782/189912146-c6bbdc6e-855c-4d90-8640-15bbcf2ee393.png)
![image](https://user-images.githubusercontent.com/97490782/189912188-473bcd74-35e7-43e6-a812-10cd0906885d.png)
![image](https://user-images.githubusercontent.com/97490782/189912223-6a299be3-fdf6-4476-ad43-92c53fdc17e3.png)

**Expected behavior**
build successful

**Failure logs**
```
已启动重新生成…
1>------ 已启动全部重新生成: 项目: ConsoleApplication6, 配置: Release x64 ------
1>ConsoleApplication6.cpp
1>ConsoleApplication6.obj : error LNK2001: 无法解析的外部符号 __imp_hv_compile_version
1>ConsoleApplication6.obj : error LNK2001: 无法解析的外部符号 __imp_logger_print
1>ConsoleApplication6.obj : error LNK2001: 无法解析的外部符号 __imp_get_run_dir
1>ConsoleApplication6.obj : error LNK2001: 无法解析的外部符号 __imp_hv_default_logger
1>ConsoleApplication6.obj : error LNK2001: 无法解析的外部符号 __imp_get_executable_path
1>C:\Users\Administrator\source\repos\ConsoleApplication6\x64\Release\ConsoleApplication6.exe : fatal error LNK1120: 5 个无法解析的外部命令
1>已完成生成项目“ConsoleApplication6.vcxproj”的操作 - 失败。
========== 全部重新生成: 成功 0 个，失败 1 个，跳过 0 个 ==========

```

**Additional context**

**Comment by heheda123123** [comment]
why thumbs down this issue?

**Comment by ithewei** [comment]
Add precompiled macro HV_STATICLIB, refer to
https://github.com/ithewei/libhv/wiki/%E4%B8%AD%E6%96%87FAQ#2%E9%9D%99%E6%80%81%E5%BA%93%E5%A3%B0%E6%98%8E%E5%AE%8Fhv_staticlib--%E9%9D%99%E6%80%81%E5%BA%93hv_staticlib

**Comment by jimwang118** [comment]
@heheda123123 Following the method suggested by @ithewei should solve the issue, if you solve it, I will close this issue.
