### ISSUE TITLE
glog forces /Zc:__cplusplus on consumers even for non-MSVC front end compilers

### ISSUE THREAD

**Issue by craigscott-crascit** [microsoft/vcpkg#26784]
Did the correct final version of the change in #25312 get merged? I see the `/Zc:__cplusplus` flag still being added, but the discussion there seems to conclude that the changes should have been reverted (but I could be misunderstanding @JackBoosY's review comments there).

The changes in #25312 broke projects that use msvc clang (not clang-cl) and pull in glog. That compiler builds for the MSVC ABI, but it doesn't support MSVC command line options. If this flag really does need to be added, the condition around adding it needs to be on the _consumer_, not on the compiler used to build glog. You could wrap it with a generator expression that checks the consumer's compiler ID, but then you'd have to pick a language (C or C++) to base that test on. It is probably simpler just to restore the relevant parts of the old patches instead of adding this flag as was done in #25312.

_Originally posted by @craigscott-crascit in https://github.com/microsoft/vcpkg/pull/25312#discussion_r970267279_

**Comment by craigscott-crascit** [comment]
CC: @JackBoosY @jiayuehua

**Comment by JackBoosY** [comment]
I believe we still need this fix, but we may need another way to implement.

**Comment by FrankXie05** [comment]
Fixed by PR https://github.com/microsoft/vcpkg/pull/28097

**Comment by craigscott-crascit** [comment]
How is this fixed by #28097? The only condition that PR checked is `$<$<NOT:$<COMPILE_LANGUAGE:CUDA>>:/Zc:__cplusplus>`, but that will still add the cl frontend's flag for non-cl frontend clang.

**Comment by FrankXie05** [comment]
Sorry, I missed something.
