### ISSUE TITLE
packages related to sqlpp11 is confusing.

### ISSUE THREAD

**Issue by shishirong** [microsoft/vcpkg#26786]
https://github.com/rbock/sqlpp11/issues/455#issue-1368691993

`sqlpp11-connector-mysql`,`sqlpp11-connector-sqlite3`,etc.. all connectors are contains in `sqlpp11` now,  need connectors packages no more.

**Comment by dg0yt** [comment]
sqlpp11-connector-mysql and sqlpp11-connector-sqlite3 are empty ports. All they do is pulling in sqlpp11. They won't go away to not break downstream usage.

**Comment by shishirong** [comment]
understand, thanks for answer.
modify the package descriptions clearly, maybe  should.

**Comment by dg0yt** [comment]
This is in the description already:
"A C++ wrapper for MySQL meant to be used in combination with sqlpp11 (obsolete, use sqlpp11 with the mariadb/mysql feature instead)" 
"A C++ wrapper for sqlite3 meant to be used in combination with sqlpp11 (obsolete, use sqlpp11 with the sqlite3 feature instead)"

**Comment by shishirong** [comment]
> This is in the description already: "A C++ wrapper for MySQL meant to be used in combination with sqlpp11 (obsolete, use sqlpp11 with the mariadb/mysql feature instead)" "A C++ wrapper for sqlite3 meant to be used in combination with sqlpp11 (obsolete, use sqlpp11 with the sqlite3 feature instead)"

sorry, it's my careless, descriptions  display Incomplete in my computer, just to "(ob..."
![image](https://user-images.githubusercontent.com/16620315/190885166-b1f9a7e8-0678-41cf-be6a-04a121c3c7dd.png)

**Comment by dg0yt** [comment]
Thanks for this screenshot. It is good to know next time I review such pull requests.
