### ISSUE TITLE
vcpkg integrate install does not work on my Atlassian Bamboo build agents running under the local system account

### ISSUE THREAD

**Issue by pceccato** [microsoft/vcpkg#26796]
Hi,

I have installed vcpkg on our atlassian bamboo build agent running Visual Studio 2022, and run:

vcpkg integrate install

However, the build agent which runs as the local system account cannot find the header files of my vcpkg libraries.
I have rebooted the machine, still no joy. I suspect it is because the build agent runs as the local system account.

I tried running vcpkg integrate install as part of the build plans so it ran as the LocalSystem account but it didn't help.

How can I get my build agent to work with vcpkg?

**Comment by JackBoosY** [comment]
Can you describe more?
Which project type do you use in your custom project?

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
