### ISSUE TITLE
got error "Value was null"

### ISSUE THREAD

**Issue by SouthAngel** [microsoft/vcpkg#26807]
**Describe the bug**
When i try install something from vcpkg i will get the waring "Downloading ... Value was null" what is the hell!
**Environment**
- OS: windows10
- Compiler: visaul studio 2022

**To Reproduce**
1. ./vcpkg install cjson
2. See error
PS C:\001\1\vcpkg> .\vcpkg.exe install cjson
Computing installation plan...
The following packages will be built and installed:
    cjson[core]:x64-windows -> 1.7.15#2
  * vcpkg-cmake[core]:x64-windows -> 2022-07-18
  * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
A suitable version of powershell-core was not found (required v7.2.5). Downloading portable powershell-core v7.2.5...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v7.2.5/PowerShell-7.2.5-win-x86.zip -> C:\001\1\vcpkg\downloads\PowerShell-7.2.5-win-x86.zip
Value was null

**Expected behavior**
can you give some detail log?

**Additional context**
anything got the same error
and i have try vs2017, it fail
![11](https://user-images.githubusercontent.com/40079503/190340856-7927bfe3-c72e-47bf-8d33-6e7366673b93.png)

**Comment by FrankXie05** [comment]
@SouthAngel Thanks for posting this issue, I have not reproduced this problem locally, I am using the vs 2019 version.
![image](https://user-images.githubusercontent.com/65999885/190370705-bd924fa9-3268-45ad-bb33-44f15a8963d2.png)

Could you re-clone a vcpkg and run the following command and return the console output to me?
And can you manually access this link?  https://github.com/PowerShell/PowerShell/releases/download/v7.2.5/PowerShell-7.2.5-win-x86.zip

**Comment by SouthAngel** [comment]
I have try again
![image](https://user-images.githubusercontent.com/40079503/190545354-c66acc2b-50c4-42da-861e-150dfc86c305.png)

**Comment by SouthAngel** [comment]
I am sure the download link have right to access. By the way, not only the powershell core, when process download in othe case, it get the same error.

**Comment by SouthAngel** [comment]
I have found out the trouble .. it is a spell error Environment Variables, like this 
![image](https://user-images.githubusercontent.com/40079503/190548294-888144af-45b7-48b1-98c3-3a4ba3e6e878.png)
Thanks for your help
