### ISSUE TITLE
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):    Failed to download file with error: 1

### ISSUE THREAD

**Issue by liangtongIrelia** [microsoft/vcpkg#26804]
The system I used was CenOS 7
cmake3 version 3.17.2

When I was downloading vcpkg which was requied by CMake3, some error occurred and the detailed error was found in vcpkg-manifest-install.log

_CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):

      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. Your proxy's remote server is out of service._
I was actually using an http proxy and I made sure that "http://address:port" was set to both HTTP_PROXY and HTTPS_PROXY, and also the proxy's remote server is working.

How can I solve this issue? Any help will be appreciated.

**Comment by liangtongIrelia** [comment]
The full error log is shown below:

_```
Detecting compiler hash for triplet x64-linux...
The following packages will be built and installed:
  * curl[core,non-http,openssl,ssl]:x64-linux -> 7.82.0
    openssl[core]:x64-linux -> 3.0.2#2
    protobuf[core]:x64-linux -> 3.19.4
    sentry-native[core]:x64-linux -> 0.4.15
    zlib[core]:x64-linux -> 1.2.12
Additional packages (*) will be modified to complete this operation.
Restored 0 packages from /home/liuliangtong/.cache/vcpkg/archives in 17.24 us. Use --debug to see more details.
Starting package 1/5: openssl:x64-linux
Building package openssl[core]:x64-linux...
CMake Warning at ports/openssl/portfile.cmake:7 (message):
  openssl currently requires the following library from the system package
  manager:

      linux-headers

  It can be installed on alpine systems via apk add linux-headers.
Call Stack (most recent call first):
  scripts/ports.cmake:145 (include)


-- Downloading https://www.openssl.org/source/openssl-3.0.2.tar.gz -> openssl-3.0.2.tar.gz...
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] 115591: popen(curl --fail -L https://www.openssl.org/source/openssl-3.0.2.tar.gz --create-dirs --output /home/liuliangtong/software/EternalTerminal/external/vcpkg/downloads/openssl-3.0.2.tar.gz.115591.part 2>&1)
[DEBUG] 115591: cmd_execute_and_stream_data() returned 60 after   418810 us
Error: Failed to download from mirror set:
https://www.openssl.org/source/openssl-3.0.2.tar.gz:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) The certificate issuer's certificate has expired. Check your system date and time.
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.


[DEBUG] /mnt/vss/_work/1/s/src/vcpkg/base/downloads.cpp(741):
[DEBUG] Time in subprocesses: 420257 us
[DEBUG] Time in parsing JSON: 4 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 130 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 420.8 ms (419088 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):

      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
"~/software/EternalTerminal/build/vcpkg-manifest-install.log" 100L, 5288C                                                                                                                                                                   1,48          Top
Detecting compiler hash for triplet x64-linux...
The following packages will be built and installed:
  * curl[core,non-http,openssl,ssl]:x64-linux -> 7.82.0
    openssl[core]:x64-linux -> 3.0.2#2
    protobuf[core]:x64-linux -> 3.19.4
    sentry-native[core]:x64-linux -> 0.4.15
    zlib[core]:x64-linux -> 1.2.12
Additional packages (*) will be modified to complete this operation.
Restored 0 packages from /home/liuliangtong/.cache/vcpkg/archives in 17.24 us. Use --debug to see more details.
Starting package 1/5: openssl:x64-linux
Building package openssl[core]:x64-linux...
CMake Warning at ports/openssl/portfile.cmake:7 (message):
  openssl currently requires the following library from the system package
  manager:

      linux-headers

  It can be installed on alpine systems via apk add linux-headers.
Call Stack (most recent call first):
  scripts/ports.cmake:145 (include)


-- Downloading https://www.openssl.org/source/openssl-3.0.2.tar.gz -> openssl-3.0.2.tar.gz...
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] 115591: popen(curl --fail -L https://www.openssl.org/source/openssl-3.0.2.tar.gz --create-dirs --output /home/liuliangtong/software/EternalTerminal/external/vcpkg/downloads/openssl-3.0.2.tar.gz.115591.part 2>&1)
[DEBUG] 115591: cmd_execute_and_stream_data() returned 60 after   418810 us
Error: Failed to download from mirror set:
https://www.openssl.org/source/openssl-3.0.2.tar.gz:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) The certificate issuer's certificate has expired. Check your system date and time.
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.


[DEBUG] /mnt/vss/_work/1/s/src/vcpkg/base/downloads.cpp(741):
[DEBUG] Time in subprocesses: 420257 us
[DEBUG] Time in parsing JSON: 4 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 130 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 420.8 ms (419088 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):

      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
"~/software/EternalTerminal/build/vcpkg-manifest-install.log" 100L, 5288C                                                                                                                                                                   1,48          Top
```_

**Comment by Cheney-W** [comment]
Could you access https://www.openssl.org/source/openssl-3.0.2.tar.gz directly and download `openssl-3.0.2.tar.gz` successfully?

**Comment by Cheney-W** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
