### ISSUE TITLE
[New Port Request] <socat>

### ISSUE THREAD

**Issue by shishirong** [microsoft/vcpkg#26803]
### Library name: 
**socat**

### Library description:

Relay for bidirectional data transfer
Socat is a relay for bidirectional data transfer between two independent data channels. Data channels may be files, pipes, devices (terminal or modem, etc.), or sockets (Unix, IP4, IP6 - raw, UDP, TCP), etc. It provides forking, logging, and tracing, different modes for interprocess communication, and many more options. It can be used, for example, as a TCP relay (one-shot or daemon), as an external socksifier, as a shell interface to Unix sockets, as an IP6 relay, as a netcat and rinetd replacement, for redirecting TCP-oriented programs like brutus to a serial line, or to establish a relatively secure environment (su and chroot) for running client or server shell scripts with network connections.

### Source repository URL:
[https://repo.or.cz/socat.git](https://repo.or.cz/socat.git)
### Project homepage (if different from the source repository):
[http://www.dest-unreach.org/socat/](http://www.dest-unreach.org/socat/)

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
