### ISSUE TITLE
No longer able to detect custom triplets

### ISSUE THREAD

**Issue by mattleibow** [microsoft/vcpkg#26818]
**Describe the bug**
I currently create a custom triplet as part of my build. This involves copying either a supported or a community triplet and making some modifications. 

Then, I would use that new triplet to install. 

This was working fine last week, but now all my builds are failing to find that triplet. 

Green build: 
https://dev.azure.com/xamarin/public/_build/results?buildId=70186&view=results
Red build: 
https://dev.azure.com/xamarin/public/_build/results?buildId=70457&view=logs&j=dc108c44-5d3a-5281-361f-26e86be56ee7&t=3b813966-f4ec-5c07-264f-331d91a5d534

Here is the simple code to copy files:
https://github.com/mono/SkiaSharp/blob/main/native/uwp/build.cake#L127

**Environment**
- OS: Windows
- Compiler: not there yet, just trying to find the triplets

**To Reproduce**

1. Clone vcpkg
2. Copy triplet and give it a new name
3. Try use the triplet
4. Observe it cannot be found

**Expected behavior**
Find the triplet

**Failure logs**
https://dev.azure.com/xamarin/public/_build/results?buildId=70457&view=logs&j=dc108c44-5d3a-5281-361f-26e86be56ee7&t=3b813966-f4ec-5c07-264f-331d91a5d534&l=789

**Additional context**
Was working on Sunday 11 September

**Comment by FrankXie05** [comment]
@mattleibow Thanks for posting this issue,
you need to download `System.Security.Permissions` and `Newton.Json package` via `Nuget`.
Log from https://dev.azure.com/xamarin/public/_build/results?buildId=70457&view=logs&j=dc108c44-5d3a-5281-361f-26e86be56ee7&t=3b813966-f4ec-5c07-264f-331d91a5d534
````
Resolving assembly 'System.Security.Permissions, Version=0.0.0.0, Culture=neutral, PublicKey***=cc7b13ffcd2ddd51' using runtime installed at 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.8\'...
Exception occurred while resolving assembly System.Security.Permissions: Could not load file or assembly 'System.Security.Permissions, Version=0.0.0.0, Culture=neutral, PublicKey***=cc7b13ffcd2ddd51'. The system cannot find the file specified.
Assembly 'System.Security.Permissions, Version=0.0.0.0, Culture=neutral, PublicKey***=cc7b13ffcd2ddd51' not resolved
Failed to load mscorlib.dll
````

**Comment by mattleibow** [comment]
That is other random errors that do not stop the build. All the other jobs are green.

https://dev.azure.com/xamarin/public/_build/results?buildId=70457&view=logs&j=4760d83b-7cba-5c67-1169-a96b7e9a0c60&t=94ca0470-696d-5647-7f77-938d504d0e91&l=303


It continues and then later on it goes

```
Read more about vcpkg telemetry at docs/about/privacy.md 

Copying file x86-uwp.cmake to D:/a/1/s/externals/vcpkg/triplets/community/x86-uwp-v142.cmake 

Executing: "D:/a/1/s/externals/vcpkg/vcpkg.exe" install angle:x86-uwp-v142 

Error: invalid triplet: x86-uwp-v142 

Available architecture triplets 

VCPKG built-in triplets: 
arm-uwp 
arm64-windows 
x64-linux 
x64-osx 
x64-uwp 
x64-windows-static 
x64-windows 
x86-windows 

VCPKG community triplets: 
arm-android 
arm-ios 
arm-linux 
arm-mingw-dynamic 
... 
```

**Comment by Neumann-A** [comment]
run with --debug. Somebody probably set `VCPKG_ROOT`.......

**Comment by Neumann-A** [comment]
also don't do what you are doing. Use `--overlay-triplets=<path_to_triplet_folder>`

**Comment by mattleibow** [comment]
I see this is exactly the case. Previously I would download my own vcpkg and use that - then they added it to the image. As of a few weeks ago, there is now a new variable: https://github.com/actions/runner-images/pull/6218
