### ISSUE TITLE
[msquic] update to 2.1

### ISSUE THREAD

**Issue by nibanks** [microsoft/vcpkg#26811]
## Library name

msquic v2.1.2 - https://github.com/microsoft/msquic/releases/tag/v2.1.2

## Other information

You can find the release notes on our MsQuic GitHub release linked above. But there are a few other things I'd like addressed:

- I notice vcpkg applies a number of patches. I'd like to get those removed. If changes are necessary, let's fix them in msquic itself.
- AFAIU, this `"supports": "!(static & staticcrt)"` claims we don't support static linking or static CRT? That's not true and should be corrected.
- The `vcpkg_cmake_configure` can be cleaned up:
  - Remove `-DQUIC_TLS_SECRETS_SUPPORT=ON`, `-DQUIC_BUILD_PERF=OFF`, `-DQUIC_BUILD_TEST=OFF`
  - Update `-DQUIC_STATIC_LINK_CRT=${STATIC_CRT}` to also set `-DQUIC_STATIC_LINK_PARTIAL_CRT=${STATIC_CRT}` (I think that's what you want)
  - Instead of hard coding `-DQUIC_TLS=openssl` you should have an option to use `schannel` on Windows. Make this a feature? Not sure how to do this. Then, if schannel is used, `perl` and `NASM` are unnecessary dependencies
  - I _think_ you want to set `-DQUIC_CI=on` since this is meant to mimic official builds; but I'm not sure

**Question** - How does vcpkg handle breaking changes from an update to the major version? This change moves from v1.2.0 to v2.1.1, which has breaking API changes.

Another thought, I think we should onboard [quicreach](https://github.com/microsoft/quicreach) to vcpkg as an example that builds off of msquic to validate everything. It's pretty simple.

cc @Cheney-W

**Comment by Cheney-W** [comment]
@nibanks Sorry for the late reply!
I found that this port will only export `target: msquic` under dynamic build, but not under static build, is this intentional design?
And when I try to export the `target: msquic_static` under static build, I got the following errors:
```
CMake Error: install(EXPORT "msquic" ...) includes target "msquic_static" which requires target "core" that is not in any export set.
CMake Error: install(EXPORT "msquic" ...) includes target "msquic_static" which requires target "platform" that is not in any export set.
CMake Error: install(EXPORT "msquic" ...) includes target "msquic_static" which requires target "inc" that is not in any export set.
CMake Error: install(EXPORT "msquic" ...) includes target "msquic_static" which requires target "logging" that is not in any export set.
CMake Error: install(EXPORT "msquic" ...) includes target "msquic_static" which requires target "main_binary_link_args" that is not in any export set.
```
I found on the web that to fix this error, we need to export every target that is linked. 
Since this solution will modify multiple CMakelists.txt files, do you have any good suggestions for this problem?

**Comment by nibanks** [comment]
Are you setting `QUIC_BUILD_SHARED` to `OFF`?

**Comment by Cheney-W** [comment]
Yes, I used `-DQUIC_BUILD_SHARED=${BUILD_SHARED_LIBS}` as a cmake config option, then the value of `BUILD_SHARED_LIBS` is automatically verified to be `on` or `off` based on the current triplet.

I verified that under x64-windows-static triplet, `QUIC_BUILD_SHARED` is off.

**Comment by nibanks** [comment]
I don't really know what those errors above mean (I'm not a CMake expert; perhaps @ThadHouse knows), but I know static linking works. For instance, [quicreach](https://github.com/microsoft/quicreach/blob/main/CMakeLists.txt) can statically link msquic just fine.

**Comment by Cheney-W** [comment]
Stay active

**Comment by Cheney-W** [comment]
Stay active

**Comment by Cheney-W** [comment]
Closed by https://github.com/microsoft/vcpkg/pull/39332
