### ISSUE TITLE
Trying to open ld-linux-x86-64.so.2 on arm64 version of linux

### ISSUE THREAD

**Issue by ylz-at** [microsoft/vcpkg#26810]
**Describe the bug**
can't integrate Vcpkg on arm64 version of linux.

**Environment**
- OS: Linux arm64
- Compiler: gcc12

**To Reproduce**
1. setup arm64 version of docker
2. run this dockerfile,
```Dockerfile
FROM ubuntu:22.10

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y build-essential ninja-build gdb
RUN apt-get install -y wget git curl zip unzip tar pkg-config
RUN wget -O cmake.sh https://github.com/Kitware/CMake/releases/download/v3.24.0/cmake-3.24.0-linux-x86_64.sh && sh ./cmake.sh --prefix=/usr/ --skip-license

RUN mkdir -p /opt
RUN git clone https://github.com/Microsoft/vcpkg.git /opt/vcpkg
RUN cd /opt/vcpkg && ./bootstrap-vcpkg.sh && ./vcpkg integrate install

RUN ln -s /opt/vcpkg/vcpkg /usr/local/bin/vcpkg
RUN vcpkg install spdlog && rm -rf /opt/vcpkg/buildtrees /opt/vcpkg/downloads

# clean up
RUN apt-get autoremove -y && apt-get autoclean -y
```
4. see error

Repro code when

**Expected behavior**
Successful build.

**Failure logs**
```
Step 9/12 : RUN cd /opt/vcpkg && ./bootstrap-vcpkg.sh && ./vcpkg integrate install
 ---> Running in 167d0a3a1da0
Unable to determine a binary release of vcpkg; attempting to build from source.
Downloading vcpkg tool sources
Building vcpkg-tool...
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```

**Additional context**
```shell
/# uname -a
Linux ae9cddfc4133 5.10.104-linuxkit #1 SMP PREEMPT Thu Mar 17 17:05:54 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by Osyotr** [comment]
Right now there's no prebuilt `vcpkg` binary for arm64-linux.
@BillyONeal would you mind including one in next release?

**Comment by BillyONeal** [comment]
I've always wanted to do that but don't know how.

https://github.com/microsoft/vcpkg-tool/blob/99fdff0e07edce961c649676e1788361151fbd8a/azure-pipelines/pipelines.yml#L2-L78

is our current build scripts on Linux, at least for debug validation. (I'm sure if I had a working version of that I could replicate it into the signing-accessible infrastructure)

I know there are docs floating around on doing cross compiling or something like that but I'd be nervous to ship such a thing without the ability to test it.

It does seem like bootstrap should somehow be detecting arm64 and choosing the from-source fallback instead here...

**Comment by Osyotr** [comment]
>It does seem like bootstrap should somehow be detecting arm64 and choosing the from-source fallback instead here...

Wait a second.. It does!
```
Unable to determine a binary release of vcpkg; attempting to build from source.
Downloading vcpkg tool sources
Building vcpkg-tool...
```

@ylz-at why do you install x86_64 CMake on aarch64 machine?
```
RUN wget -O cmake.sh https://github.com/Kitware/CMake/releases/download/v3.24.0/cmake-3.24.0-linux-x86_64.sh && sh ./cmake.sh --prefix=/usr/ --skip-license
```
The error might come from CMake, not vcpkg.

**Comment by ylz-at** [comment]
> why do you install x86_64 CMake on aarch64 machine?

@BillyONeal Ohhh. I originally wrote this Dockerfile for x64 machines and didn't notice that.
It's working after switching to aarch64 CMake.
