### ISSUE TITLE
can we build vcpkg package from external .dll, .lib without there source code

### ISSUE THREAD

**Issue by Amit-Mnnit929** [microsoft/vcpkg#26829]
Hey,
can we build vcpkg package from external .dll, .lib  file  without there source code ?
Means, like I have A.dll and B.lib and myheader.h , Now can we create vcpkg with these files ?

**Comment by Osyotr** [comment]
Yes you can! Just make sure it's compatible with your toolchain.
Here is an example of packaging prebuilt proprietary library.

[libxl.zip](https://github.com/microsoft/vcpkg/files/9584467/libxl.zip)

**Comment by Amit-Mnnit929** [comment]
ho to get REF and SHA512 value which mention in portfile file ?

**Comment by Amit-Mnnit929** [comment]
can we build vcpkg package only from .dll, .lib which is stored in my local system and without there source code ?
Means, like I have GemBox.dll , pt4all.lib and pt4all.h ?

And 
Can we build vcpkg from multiple header file and multiple .dll files 
I mean to build single vcpkg from multiple header files and multiple .dll files and these files are stored in my local storage ?

**Comment by JackBoosY** [comment]
For official repo: no, for custom registry: yes.

You just need to add the cmake code to find and install these libraries and header files in `portfile.cmake`.

If you need to use versioning, you should fork the official repo and commit your changes on your branch.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
