### ISSUE TITLE
[libiconv] build failure

### ISSUE THREAD

**Issue by ma-yongliang** [microsoft/vcpkg#26823]
**Host Environment**

- OS: [Windows.]
- Compiler: Visual Studio 2022

**To Reproduce**

`./vcpkg install libiconv:x64-windows`

**Failure logs**

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: D:/package/vcpkg/downloads/tools/powershell-core-7.2.5-windows/pwsh.exe -noprofile -executionpolicy Bypass -nologo -file D:/package
/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary D:/package/vcpkg/packages/libiconv_x64-windows/tools/libiconv/bin/iconv.exe -installedDi
r D:/package/vcpkg/packages/libiconv_x64-windows/bin -verbose
    Working Directory: D:/package/vcpkg
    Error code: 1
    See logs for more information:
[copy-tool-dependencies-0-err.log](https://github.com/microsoft/vcpkg/files/9581711/copy-tool-dependencies-0-err.log)
[copy-tool-dependencies-0-out.log](https://github.com/microsoft/vcpkg/files/9581713/copy-tool-dependencies-0-out.log)

      D:\package\vcpkg\buildtrees\libiconv\copy-tool-dependencies-0-out.log
      D:\package\vcpkg\buildtrees\libiconv\copy-tool-dependencies-0-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:9 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:41 (z_vcpkg_copy_tool_dependencies_search)
  ports/libiconv/portfile.cmake:42 (vcpkg_copy_tool_dependencies)
  scripts/ports.cmake:147 (include)

error: building libiconv:x64-windows failed with: BUILD_FAILED

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by jimwang118** [comment]
I could install this port successfully with the latest vcpkg 2023-06-08-19a3cb921a585fce63c0651f56a991a5a08bdc60, could you please run following commands in your vcpkg folder:

```
1. git pull
2. .\bootstrap-vcpkg.bat
3. .\vcpkg install libiconv--binarysource=clear
```
![image](https://github.com/microsoft/vcpkg/assets/122244446/df60bca5-2644-4e74-b5f9-c8d281431383)
