### ISSUE TITLE
[openblas] build failure

### ISSUE THREAD

**Issue by yangbin2566** [microsoft/vcpkg#26832]
I am trying to install {opencv4 ceres ceres[suitesparse] lapack suitesparse} lib for x64-windows with command vcpkg install opencv4 ceres ceres[suitesparse] lapack suitesparse --triplet x64-windows but fails. I have also tried both git pull and vcpkg update which are both up to date.

**Host Environment**

- OS: Windows
- Compiler: revision

**To Reproduce**

1. error log:
Computing installation plan...
The following packages will be built and installed:
  * blas[core]:x64-windows -> 1#1
    ceres[core,lapack,suitesparse]:x64-windows -> 2.1.0#2
  * eigen3[core]:x64-windows -> 3.4.0#2
  * gflags[core]:x64-windows -> 2.2.2#5
  * gklib[core]:x64-windows -> 2022-07-27#2
  * glog[core]:x64-windows -> 0.6.0
    lapack[core]:x64-windows -> 2022-02-22
  * lapack-reference[blas-select,core,noblas]:x64-windows -> 3.10.1
  * libjpeg-turbo[core]:x64-windows -> 2.1.4
  * liblzma[core]:x64-windows -> 5.2.5#6
  * libpng[core]:x64-windows -> 1.6.37#19
  * libwebp[core,libwebpmux,nearlossless,simd,unicode]:x64-windows -> 1.2.4
  * metis[core]:x64-windows -> 2022-07-27
  * openblas[core]:x64-windows -> 0.3.21
    opencv4[core,default-features,dnn,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.6.0#4
  * protobuf[core]:x64-windows -> 3.21.4
  * quirc[core]:x64-windows -> 1.1#3
    suitesparse[core]:x64-windows -> 5.8.0#1
  * tiff[core,jpeg,lzma,zip]:x64-windows -> 4.4.0#1
  * vcpkg-get-python-packages[core]:x64-windows -> 2022-06-30
  * vcpkg-gfortran[core]:x64-windows -> 3#2
  * zlib[core]:x64-windows -> 1.2.12#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\ben\AppData\Local\vcpkg\archives in 575.5 us. Use --debug to see more details.
Installing 1/22 openblas:x64-windows...
Building openblas[core]:x64-windows...
-- Using cached xianyi-OpenBLAS-b89fb708caa5a5a32de8f4306c4ff132e0228e9a.tar.gz.
-- Cleaning sources at D:/A_yangbin_files/code/python_code/RS_code/ODM-master/OpenSfM-main/vcpkg-master/buildtrees/openblas/src/32e0228e9a-ba8c0c7bab.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/A_yangbin_files/code/python_code/RS_code/ODM-master/OpenSfM-main/vcpkg-master/downloads/xianyi-OpenBLAS-b89fb708caa5a5a32de8f4306c4ff132e0228e9a.tar.gz
-- Applying patch uwp.patch
-- Applying patch fix-space-path.patch
-- Applying patch fix-redefinition-function.patch
-- Applying patch fix-uwp-build.patch
-- Applying patch install-tools.patch
-- Using source at D:/A_yangbin_files/code/python_code/RS_code/ODM-master/OpenSfM-main/vcpkg-master/buildtrees/openblas/src/32e0228e9a-ba8c0c7bab.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: "D:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: D:/A_yangbin_files/code/python_code/RS_code/ODM-master/OpenSfM-main/vcpkg-master/buildtrees/openblas/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\A_yangbin_files\code\python_code\RS_code\ODM-master\OpenSfM-main\vcpkg-master\buildtrees\openblas\config-x64-windows-CMakeCache.txt.log
      D:\A_yangbin_files\code\python_code\RS_code\ODM-master\OpenSfM-main\vcpkg-master\buildtrees\openblas\config-x64-windows-CMakeCache.txt.log
      D:\A_yangbin_files\code\python_code\RS_code\ODM-master\OpenSfM-main\vcpkg-master\buildtrees\openblas\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:238 (vcpkg_execute_required_process)
  ports/openblas/portfile.cmake:62 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)

error: building openblas:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openblas
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openblas]+Build+error
Include '[openblas] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-09-01-dfb82802c8cc562ce3b665a904a65b22314de724
    vcpkg-scripts version: unknown

You can also use the prefilled template from D:\A_yangbin_files\code\python_code\RS_code\ODM-master\OpenSfM-main\vcpkg-master\installed\vcpkg\issue_body.md.

**Comment by yangbin2566** [comment]
ninja: build stopped: subcommand failed.

  
Call Stack (most recent call first):
  cmake/system.cmake:166 (include)
  CMakeLists.txt:93 (include)


-- Configuring incomplete, errors occurred!
See also "D:/A_yangbin_files/code/python_code/RS_code/ODM-master/OpenSfM-main/vcpkg-master/buildtrees/openblas/x64-windows-dbg/CMakeFiles/CMakeOutput.log".
See also "D:/A_yangbin_files/code/python_code/RS_code/ODM-master/OpenSfM-main/vcpkg-master/buildtrees/openblas/x64-windows-dbg/CMakeFiles/CMakeError.log".
ninja: build stopped: subcommand failed.

**Comment by Adela0814** [comment]
Please provide the failure log: `D:\A_yangbin_files\code\python_code\RS_code\ODM-master\OpenSfM-main\vcpkg-master\buildtrees\openblas\config-x64-windows-out.log`.

**Comment by Adela0814** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
