### ISSUE TITLE
Github Actions recent update (2022-09) breaks CIs scripts that were using vcpkg

### ISSUE THREAD

**Issue by pthom** [microsoft/vcpkg#26835]
__This is not a bug in vcpkg per se, but in its recent integration into Github workflows__

Following a recent update to github actions, vcpkg is now preinstalled on MacOS and Windows GH runners.

I cannot get it to work anymore on windows runners.

See the issue I posted [in Github community discussions](https://github.com/community/community/discussions/33281).

Can someone from vcpkg help?

**Comment by Neumann-A** [comment]
Check the set environment variables. If there are `VCPKG_` variables set unset them.

**Comment by pthom** [comment]
Yes it works. Thank you!
