### ISSUE TITLE
[giflib] Debug library linked in release configuration

### ISSUE THREAD

**Issue by Chlumsky** [microsoft/vcpkg#26833]
**Host Environment**

- OS: Windows 10 & 11
- Compiler: Visual Studio 2015, 2019, 2022

**To Reproduce**

CMake project + vcpkg manifest.

vcpkg.json:
```json
{
    "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json",
    "name": "vcpkg-giflib-bug",
    "version": "1.0.0",
    "builtin-baseline": "a1737683a6f8ec5d8673890581c2a8c55838d411",
    "dependencies": [ "giflib" ]
}
```
CMakeLists.txt:
```cmake
cmake_minimum_required(VERSION 3.16)
project(vcpkg-giflib-bug)
find_package(GIF REQUIRED)
add_executable(vcpkg-giflib-bug main.cpp)
target_link_libraries(vcpkg-giflib-bug PRIVATE GIF::GIF)
```
main.cpp:
```c++
void main() { }
```

![image](https://user-images.githubusercontent.com/18639794/190670469-30a57eff-e82b-49d2-a0b0-421a496d459f.png)

All other libraries that I used except Giflib were linked correctly.

**Comment by dg0yt** [comment]
CMake's `FindGIF.cmake` doesn't support multi-config.
A vcpkg cmake wrapper would mitigate the issue.
