### ISSUE TITLE
[sqlite3] build failure

### ISSUE THREAD

**Issue by JohnMrziglod** [microsoft/vcpkg#26840]
Package: sqlite3[core]:x64-windows-static -> 3.39.2
**Host Environment**
- Host: x64-windows
- Compiler: MSVC 19.33.31630.0
-    vcpkg-tool version: 2022-09-01-dfb82802c8cc562ce3b665a904a65b22314de724
    vcpkg-scripts version: 637698b9c 2022-09-16 (2 hours ago)

**To Reproduce**
`vcpkg install sqlite3`

**Failure logs**
```
-- Downloading https://sqlite.org/2022/sqlite-amalgamation-3390200.zip -> sqlite-amalgamation-3390200.zip...
-- Cleaning sources at E:/Libs/vcpkg/buildtrees/sqlite3/src/3390200-90a72c9855.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/Libs/vcpkg/downloads/sqlite-amalgamation-3390200.zip
-- Applying patch fix-arm-uwp.patch
-- Using source at E:/Libs/vcpkg/buildtrees/sqlite3/src/3390200-90a72c9855.clean
CMake Error at ports/sqlite3/portfile.cmake:41 (vcpkg_cmake_configure):
  Unknown CMake command "vcpkg_cmake_configure".
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)



```

**Additional context**
Just trying to install sqlite3 as in the beginner tutorial.
This actually happens with all packages that I try to install.

**Comment by dg0yt** [comment]
Maybe the installed `vcpkg-cmake` (for the host triplet) needs an upgrade. Check with `./vcpkg upgrade`.

**Comment by JohnMrziglod** [comment]
Thank you for the suggestion. Unfortunately, it didn’t work. I reinstalled my vcpkg application and now it seems to work though. Can be closed.Enviar usando la aplicación de correo del móvilEl 17.09.22 en 5:39, Kai Pastor escribió:
                
            
            
                
                    De: "Kai Pastor" ***@***.***>Fecha: 17 de septiembre de 2022A: "microsoft/vcpkg" ***@***.***>Cc: "JohnMrziglod" ***@***.***>,"Author" ***@***.***>Asunto: Re: [microsoft/vcpkg] [sqlite3] build failure (Issue #26840)
                
                
Maybe the installed vcpkg-cmake (for the host triplet) needs an upgrade. Check with ./vcpkg upgrade.

**Comment by dg0yt** [comment]
> Unfortunately, it didn’t work.

Not sure what you tried and where you stopped.

> I reinstalled my vcpkg application and now it seems to work though.

This is another way to ensure that the installed `vcpkg-cmake` is up-to-date.
