### ISSUE TITLE
[glfw3] Build error

### ISSUE THREAD

**Issue by andresfelipemendez** [microsoft/vcpkg#26848]
used the CMake with vcpackage manifest from visual studio 2022 that builds in windows and tried to clone and compile in Ubuntu but vcpkg fails to install GLFW3

for reference this is the repo that I'm trying to build and the commit at the moment its failing
https://github.com/andresfelipemendez/OGLPG/tree/617392fd638b4b95d0c1b3cd873fde7b4cc985c1

**Host Environment**

- OS: [Linux Ubuntu 22.04 LTS 64-bit]
- Compiler: revision

**To Reproduce**

cmake configure -S . -DCMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake

**Failure logs**
-- Running vcpkg install
Detecting compiler hash for triplet x64-linux...
The following packages will be built and installed:
  * egl-registry[core]:x64-linux -> 2021-11-23 -- /home/andres/vcpkg/buildtrees/versioning_/versions/egl-registry/ec272777ea9d0ceccf5cc8b0336f038853e5c911
    glad[core,loader]:x64-linux -> 0.1.36 -- /home/andres/vcpkg/buildtrees/versioning_/versions/glad/fa93b14c1581057e1d14650f5f15c9b0757dd548
    glfw3[core]:x64-linux -> 3.3.2 -- /home/andres/vcpkg/buildtrees/versioning_/versions/glfw3/948e1bd3085f0de7b3af12c5a71afe1c8969ea55
    glm[core]:x64-linux -> 0.9.9.8#1 -- /home/andres/vcpkg/buildtrees/versioning_/versions/glm/4aafac80f39a72fadaf6a31afb961790678062de
    imgui[core]:x64-linux -> 1.88#1 -- /home/andres/vcpkg/buildtrees/versioning_/versions/imgui/2a4c55df4b895535fba9e3934ed64cef92bf4a4d
  * nlohmann-json[core]:x64-linux -> 3.11.2 -- /home/andres/vcpkg/buildtrees/versioning_/versions/nlohmann-json/caa64b8c731ac2457575ea3c5f1827bc82ecac84
  * opengl-registry[core]:x64-linux -> 2021-11-17 -- /home/andres/vcpkg/buildtrees/versioning_/versions/opengl-registry/7f4a1e05a6cfbd923a2eaf9d32da22bde0742a15
  * stb[core]:x64-linux -> 2021-09-10#1 -- /home/andres/vcpkg/buildtrees/versioning_/versions/stb/9ebadca0be90431f35a8d20b44f40b07285eb33d
    tinygltf[core]:x64-linux -> 2.5.0 -- /home/andres/vcpkg/buildtrees/versioning_/versions/tinygltf/68e4d0aabd2073861e4add08af282c0eff858a1e
  * vcpkg-cmake[core]:x64-linux -> 2022-07-18 -- /home/andres/vcpkg/buildtrees/versioning_/versions/vcpkg-cmake/a7b618b7782f3c841d7fd2d84a6ba3619815362a
  * vcpkg-cmake-config[core]:x64-linux -> 2022-02-06#1 -- /home/andres/vcpkg/buildtrees/versioning_/versions/vcpkg-cmake-config/8d54cc4f487d51b655abec5f9c9c3f86ca83311f
Additional packages (*) will be modified to complete this operation.
Restored 5 package(s) from /home/andres/.cache/vcpkg/archives in 35.57 ms. Use --debug to see more details.
Installing 1/11 vcpkg-cmake-config:x64-linux...
Elapsed time to handle vcpkg-cmake-config:x64-linux: 1.167 ms
Installing 2/11 vcpkg-cmake:x64-linux...
Elapsed time to handle vcpkg-cmake:x64-linux: 1.107 ms
Installing 3/11 egl-registry:x64-linux...
Elapsed time to handle egl-registry:x64-linux: 1.859 ms
Installing 4/11 opengl-registry:x64-linux...
Elapsed time to handle opengl-registry:x64-linux: 10.37 ms
Installing 5/11 glad:x64-linux...
Elapsed time to handle glad:x64-linux: 4.301 ms
Installing 6/11 glfw3:x64-linux...
Building glfw3[core]:x64-linux...
-- Installing port from location: /home/andres/vcpkg/buildtrees/versioning_/versions/glfw3/948e1bd3085f0de7b3af12c5a71afe1c8969ea55
-- Using cached glfw-glfw-3.3.2.tar.gz.
-- Cleaning sources at /home/andres/vcpkg/buildtrees/glfw3/src/3.3.2-558ea1f140.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/andres/vcpkg/downloads/glfw-glfw-3.3.2.tar.gz
-- Using source at /home/andres/vcpkg/buildtrees/glfw3/src/3.3.2-558ea1f140.clean
GLFW3 currently requires the following libraries from the system package manager:
    xinerama
    xcursor
    xorg
    libglu1-mesa

These can be installed on Ubuntu systems via sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: /home/andres/vcpkg/downloads/tools/cmake-3.24.0-linux/cmake-3.24.0-linux-x86_64/bin/cmake /home/andres/vcpkg/buildtrees/glfw3/src/3.3.2-558ea1f140.clean -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/andres/vcpkg/packages/glfw3_x64-linux/debug -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_MAKE_PROGRAM=/home/andres/vcpkg/downloads/tools/ninja/1.10.2-linux/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/andres/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/home/andres/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/home/andres/vcpkg -DZ_VCPKG_ROOT_DIR=/home/andres/vcpkg -D_VCPKG_INSTALLED_DIR=/home/andres/Development/OGLPG/vcpkg_installed -DVCPKG_MANIFEST_INSTALL=OFF
    Working Directory: /home/andres/vcpkg/buildtrees/glfw3/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /home/andres/vcpkg/buildtrees/glfw3/config-x64-linux-dbg-CMakeCache.txt.log
      /home/andres/vcpkg/buildtrees/glfw3/config-x64-linux-dbg-out.log
      /home/andres/vcpkg/buildtrees/glfw3/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:314 (vcpkg_execute_required_process)
  buildtrees/versioning_/versions/glfw3/948e1bd3085f0de7b3af12c5a71afe1c8969ea55/portfile.cmake:20 (vcpkg_configure_cmake)
  scripts/ports.cmake:147 (include)

error: building glfw3:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+glfw3
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[glfw3]+Build+error
Include '[glfw3] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-09-01-dfb82802c8cc562ce3b665a904a65b22314de724
    vcpkg-scripts version: 01b29f6d8 2022-09-16 (29 hours ago)

You can also use the prefilled template from /home/andres/Development/OGLPG/vcpkg_installed/vcpkg/issue_body.md.

-- Running vcpkg install - failed
CMake Error at /home/andres/vcpkg/scripts/buildsystems/vcpkg.cmake:863 (message):
  vcpkg install failed.  See logs for more information:
  /home/andres/Development/OGLPG/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:6 (project)

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

**Additional context**

{
  "name": "chapter1",
  "description": "...",
  "version-string": "0.0.1",
  "dependencies": [
    "glad",
    "glfw3",
    "imgui",
    "glm",
    "tinygltf"
  ],
  "overrides": [
    {
      "name": "glfw3",
      "version": "3.3.2"
    }
  ],
  "builtin-baseline": "a291bcad8093f9f17988fe66543aefd674812f0e"
}

CMakePresets.json
        {
            "name": "linux-debug",
            "displayName": "Linux Debug",
            "generator": "Ninja",
            "binaryDir": "${sourceDir}/out/build/${presetName}",
            "installDir": "${sourceDir}/out/install/${presetName}",
            "cacheVariables": {
                "CMAKE_BUILD_TYPE": "Debug"
            },
            "condition": {
                "type": "equals",
                "lhs": "${hostSystemName}",
                "rhs": "Linux"
            },
            "vendor": {
                "microsoft.com/VisualStudioRemoteSettings/CMake/1.0": {
                    "sourceDir": "$env{HOME}/.vs/$ms{projectDirName}"
                }
            }
        },

# CMakeList.txt : Top-level CMake project file, do global configuration
# and include sub-projects here.
#
cmake_minimum_required (VERSION 3.8)

project ("OGLPG" LANGUAGES CXX)

add_subdirectory ("CHPT1")

Add any other context about the problem here, such as what you have already tried to resolve the issue.

the build error mentions :
GLFW3 currently requires the following libraries from the system package manager:
    xinerama
    xcursor
    xorg
    libglu1-mesa

I tried to install them but only  libglu1-mesa is found and already installed, I'm running an nvidia 980
NVIDIA Driver Version: 515.65.01 if its relevant

**Comment by andresfelipemendez** [comment]
solved by running `sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev`

**Comment by BSoDium** [comment]
Thank you, would be nice if vcpkg could actually run this on its own, or at least prompt the user to install them automatically.

**Comment by dg0yt** [comment]
> Thank you, would be nice if vcpkg could actually run this on its own, or at least prompt the user to install them automatically.

@BSoDium Note that there is this console output:
~~~
GLFW3 currently requires the following libraries from the system package manager:
xinerama
xcursor
xorg
libglu1-mesa
These can be installed on Ubuntu systems via sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev
~~~
