### ISSUE TITLE
[tesseract[training-tools]] build failure

### ISSUE THREAD

**Issue by w-hsiung** [microsoft/vcpkg#26847]
I tried to install tesseract training tools (tesseract[training-tools]) but the build failed.

Package: tesseract[core,training-tools]:x64-windows -> 5.2.0#2
**Host Environment**
- Host: x64-windows
- Compiler: MSVC 19.33.31630.0
-   vcpkg-tool version: 2022-09-01-dfb82802c8cc562ce3b665a904a65b22314de724
    vcpkg-scripts version: 01b29f6d8 2022-09-16 (18 hours ago)

**To Reproduce**
`vcpkg install tesseract[training-tools]:x64-windows`

**Failure logs**
```
-- Using cached tesseract-ocr-tesseract-5ad5325a0aa8effc47ca033625b6a51682f82767.tar.gz.
-- Cleaning sources at T:/Dev/vcpkg/buildtrees/tesseract/src/1682f82767-2e636863e8.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source T:/Dev/vcpkg/downloads/tesseract-ocr-tesseract-5ad5325a0aa8effc47ca033625b6a51682f82767.tar.gz
-- Using source at T:/Dev/vcpkg/buildtrees/tesseract/src/1682f82767-2e636863e8.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig file: T:/Dev/vcpkg/packages/tesseract_x64-windows/lib/pkgconfig/tesseract.pc
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at T:/Dev/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Fixing pkgconfig file: T:/Dev/vcpkg/packages/tesseract_x64-windows/debug/lib/pkgconfig/tesseract.pc
CMake Error at scripts/cmake/vcpkg_copy_tools.cmake:36 (message):
  Couldn't find tool "ambiguous_words":

      "T:/Dev/vcpkg/packages/tesseract_x64-windows/bin/ambiguous_words.exe" does not exist
Call Stack (most recent call first):
  ports/tesseract/portfile.cmake:74 (vcpkg_copy_tools)
  scripts/ports.cmake:147 (include)



```

**Additional context**
[tesseract.zip](https://github.com/microsoft/vcpkg/files/9592074/tesseract.zip)

Complete build logs are attached.

**Comment by Adela0814** [comment]
Could you please check if you have the following files:
```
T:/Dev/vcpkg/packages/tesseract_x64-windows/bin/ambiguous_words.exe
T:/Dev/vcpkg/buildtrees/tesseract/x64-windows-dbg/bin/ambiguous_words.exe
```

**Comment by w-hsiung** [comment]
Thanks very much.

"ambiguous_words.exe" does not exist at both locations you mentioned above.

**Comment by Adela0814** [comment]
Sorry for delay, I'm not able to repro this issue, could you please provide your configure log.

**Comment by w-hsiung** [comment]
Package: tesseract[core,training-tools]:x64-windows -> 5.2.0#3

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.34.31933.0
-    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: 6f7ffeb18 2022-11-11 (9 hours ago)

**To Reproduce**

`vcpkg install tesseract[training-tools]:x64-windows`

**Failure logs**

```
-- Downloading https://github.com/tesseract-ocr/tesseract/archive/5ad5325a0aa8effc47ca033625b6a51682f82767.tar.gz -> tesseract-ocr-tesseract-5ad5325a0aa8effc47ca033625b6a51682f82767.tar.gz...
-- Extracting source T:/Dev/test/vcpkg/downloads/tesseract-ocr-tesseract-5ad5325a0aa8effc47ca033625b6a51682f82767.tar.gz
-- Using source at T:/Dev/test/vcpkg/buildtrees/tesseract/src/1682f82767-2e636863e8.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig file: T:/Dev/test/vcpkg/packages/tesseract_x64-windows/lib/pkgconfig/tesseract.pc
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at T:/Dev/test/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Fixing pkgconfig file: T:/Dev/test/vcpkg/packages/tesseract_x64-windows/debug/lib/pkgconfig/tesseract.pc
CMake Error at scripts/cmake/vcpkg_copy_tools.cmake:36 (message):
  Couldn't find tool "ambiguous_words":

      "T:/Dev/test/vcpkg/packages/tesseract_x64-windows/bin/ambiguous_words.exe" does not exist
Call Stack (most recent call first):
  ports/tesseract/portfile.cmake:74 (vcpkg_copy_tools)
  scripts/ports.cmake:147 (include)



```


**Additional context**

**Comment by w-hsiung** [comment]
Entire logs found at T:\Dev\test\vcpkg\buildtrees\tesseract are attached.
[logs.zip](https://github.com/microsoft/vcpkg/files/9994778/logs.zip)

**Comment by spindensity** [comment]
The same problem with VS 17.4.1.

**Comment by Adela0814** [comment]
> install tesseract[training-tools]:x64-windows

Confirmed.

**Comment by Adela0814** [comment]
> The same problem with VS 17.4.1.

Confirmed.

**Comment by c-toyama** [comment]
I pre-installed "vcpkg-pkgconfig-get-modules:x64-windows" and it succeeded.
Is this relevant?

**Comment by w-hsiung** [comment]
Nice catch. I tried a couple of installations on different machines, and all succeeded.

The only puzzle I have now is the installation for x64-windows-static variant. It failed with the same message - "ambiguous_words.exe" is missing.  But that was weeks ago after read your message.  Today I tried to install again for  the static variant and got different failure message.

**Comment by w-hsiung** [comment]
Thanks very much for the hard works.

Although x64-windows still requires pre-installing "vcpkg-pkgconfig-get-modules" as mentioned by c-toyama, both x64-windows and x64-windows-static variants build successfully now.
