### ISSUE TITLE
[boost-regex] Build error

### ISSUE THREAD

**Issue by Matc2018** [microsoft/vcpkg#26850]
**Host Environment**

- OS:  Windows
- Compiler: VS2019

**To Reproduce**

`./vcpkg install boost:x64-windows

**Failure logs**

Installing 1/120 boost-regex:x64-windows...
Building boost-regex[core]:x64-windows...
-- Using cached boostorg-regex-boost-1.79.0.tar.gz.
-- Cleaning sources at E:/vcpkg/buildtrees/boost-regex/src/ost-1.79.0-42753a2328.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/vcpkg/downloads/boostorg-regex-boost-1.79.0.tar.gz
-- Using source at E:/vcpkg/buildtrees/boost-regex/src/ost-1.79.0-42753a2328.clean
-- Including E:/vcpkg/ports/boost-regex/b2-options.cmake
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: E:/vcpkg/downloads/tools/cmake-3.24.0-windows/cmake-3.24.0-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j17
    Working Directory: E:/vcpkg/buildtrees/boost-regex/x64-windows-dbg
    See logs for more information:
      E:\vcpkg\buildtrees\boost-regex\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:136 (vcpkg_cmake_install)
  ports/boost-regex/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:147 (include)
- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/9593267/install-x64-windows-dbg-out.log)

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Matc2018** [comment]
vcpkg version：2022.08.15 Release

**Comment by cedral** [comment]
You should probably try the current master head and try again. They updated boost from 1.79 to 1.80 on August 24th.

**Comment by LilyWangLL** [comment]
> -- Using cached boostorg-regex-boost-1.79.0.tar.gz.

Now the version of `boost` is 1.8.0, please update vcpkg by command `git pull` and `.\bootstrap-vcpkg.bat`, then rebuild `boost-regex`.

**Comment by LilyWangLL** [comment]
Duplicated of https://github.com/microsoft/vcpkg/issues/24473

**Comment by Danielmelody** [comment]
> Duplicated of #24473

I doubt it, my vcpkg is up-to-date, I 've tried version 1.78, 1.19 and 1.80 and non of them worked. 
I finally find that my company's anti-virus software killed b2.exe and jamxxx.exe generated by boost, as I turn it off it worked immediately. @Matc2018 hope it helps.

**Comment by Matc2018** [comment]
> 
I tried your method but still failed.

**Comment by Matc2018** [comment]
> You should probably download the current master head and try again. They updated boost from 1.79 to 1.80 on August 24th.

At first I used the current master head version of master, after failure I tried the latest release version and still got the same error.

**Comment by Matc2018** [comment]
> > Duplicated of #24473
> 
> I doubt it, my vcpkg is up-to-date, I 've tried version 1.78, 1.19 and 1.80 and non of them worked. I finally find that my company's anti-virus software killed b2.exe and jamxxx.exe generated by boost, as I turn it off it worked immediately. @Matc2018 hope it helps.

I followed your method and still failed.

**Comment by LilyWangLL** [comment]
Could you double check if **D:\project\vcpkg\buildtrees\boost-regex\x64-windows-dbg\boost\standalone\msvc\19858a0c092d6daed3b7579665d68f18\msvc-setup.nup** exist?
Did you install anti-virus software on your machine? Anti-virus software may remove these files, if you have anti-virus software, please close it and rebuild `boost-regex` with new vcpkg.

**Comment by Matc2018** [comment]
> Could you double check if **D:\project\vcpkg\buildtrees\boost-regex\x64-windows-dbg\boost\standalone\msvc\19858a0c092d6daed3b7579665d68f18\msvc-setup.nup** exist? Did you install anti-virus software on your machine? Anti-virus software may remove these files, if you have anti-virus software, please close it and rebuild `boost-regex` with new vcpkg.

Thanks，I'll check and try it later.

**Comment by Matc2018** [comment]
I installed a new system environment using vmware, and the compilation passed without problems. So it's a problem with my local machine environment. It's probably related to antivirus software. Thanks again for help @Danielmelody @LilyWangLL .
