### ISSUE TITLE
[vcpkg-tool][ci] Add option `--quiet`

### ISSUE THREAD

**Issue by Thomas1664** [microsoft/vcpkg#26861]
In our CI script we first run `vcpkg ci --dry-run` and then `vcpkg ci`. The result of this it that the abi info is printed twice which makes stdout ~2000 lines longer and takes additional ~15-20 seconds on every CI run. Because it seems like the reason why we first make a dry run is that we want to print the install plan:

https://github.com/microsoft/vcpkg/blob/01b29f6d8212bc845da64773b18665d682f5ab66/scripts/azure-pipelines/test-modified-ports.ps1#L137-L156

https://github.com/microsoft/vcpkg/blob/01b29f6d8212bc845da64773b18665d682f5ab66/scripts/azure-pipelines/test-modified-ports.ps1#L166

I propose to add a `--quite` option that disables printing abi hashes and install plan. If we still want abi hashes for both runs (`vcpkg ci --dry-run` and `vcpkg ci`) and the plan I suggest to move them to artifacts because together they are more than 5000 lines long and clutter the console output. This allows us to better see which ports are failing without having to scroll through 5000 lines of useless (in terms of port development) information.

**Comment by dg0yt** [comment]
The dry-run is not for printing but to actually save the ABI hashes of the parent commit to a file.
FTR initially the output of the dry run was filtered in the script, but the filter was removed while searching for another vcpkg bug.
Maybe the `ci` command only needs a `--quiet` parameter

**Comment by Thomas1664** [comment]
> The dry-run is not for printing but to actually save the ABI hashes of the parent commit to a file. FTR initially the output of the dry run was filtered in the script, but the filter was removed while searching for another vcpkg bug. Maybe the `ci` command only needs a `--quiet` parameter

We would get the best performance if we did `vcpkg ci` only once. Why we can't do the regular `vcpkg ci` with `--output-hashes`, print the plan and only print hashes if they aren't saved to a file?

I assume that the hashes are saved to diff them with the new hashes. We could take it one step further and add `--diff-hashes=/path/to/hash/file` which automatically handles what we currently do with two calls to `vcpkg ci`

**Comment by dg0yt** [comment]
> We would get the best performance if we did `vcpkg ci` only once. Why we can't do the regular `vcpkg ci` with `--output-hashes`, print the plan and only print hashes if they aren't saved to a file?

These vcpkg CI runs are for different git commits. The parent hashes are for the HEAD of master. They are compared to the hashes of the current PR in order to remove the all packages which are not affected by the PR. This actually saves a lot of build time for unrelated packages over just looking at cache presence, and it improves isolation of PR builds from baseline regressions in unrelated packages in master.

**Comment by Thomas1664** [comment]
> These vcpkg CI runs are for different git commits. The parent hashes are for the HEAD of master. They are compared to the hashes of the current PR in order to remove all packages which are not affected by the PR. This actually saves a lot of build time for unrelated packages over just looking at cache presence, and it improves isolation of PR builds from baseline regressions in unrelated packages in master.

In this case our best option is to add `--quiet` for the dry run as you suggested.

**Comment by Thomas1664** [comment]
> You may be able to improve perf in the first case by shutting off binary caching, so that we don't consult anything, in that first pass, which doesn't require tool changes.

We already do this.

> The pause at the start of the run is not created by printing of the text, so if the motivation is performance I don't see a meaningful ask here.

It's not just about perf. It's also about 6000 lines of in most cases completely useless console output. This clutters console output and in some cases trigger weird things on the AZP UI, for example loading the console output is slow when you're watching CI while it's running. If these logs are needed, I suggest moving them to a file and storing them as an artifact instead. It's also very annoying that I have to scroll through all of this just to discover that no tests are run.

**Comment by BillyONeal** [comment]
It is precisely times when 'nothing was built' that you need both outputs in order to try to figure out *why* nothing was built. I don't think hoisting things into separate artifacts improves the situation: on the contrary, I think we should be endeavoring to get rid of reasons people need to access separate artifacts because the authentication mess to get to them is a mess.
