### ISSUE TITLE
vcpkg upgrade confirmation question without --no-dry-run

### ISSUE THREAD

**Issue by OlafvdSpek** [microsoft/vcpkg#2686]
Could `vcpkg upgrade` ask for confirmation (with a single Enter being enough)?
That's easier then repeating the command with --no-dry-run.

**Comment by claudiofantacci** [comment]
Hi, I downvoted as long as [this](https://github.com/Microsoft/vcpkg/issues/3023) may happen 😄 
Accidental upgrade could be painful!

**Comment by OlafvdSpek** [comment]
That's why the request is to ask for confirmation isn't it?

**Comment by claudiofantacci** [comment]
I understand your point of view and it is actually a behaviour that can be found in many other package managers.

My two cents here is that a _with a single Enter being enough_-confirmation type may be dangerous and can cause, with a single missclick, pain as in #3023.

I guess that explicit `--no-dry-run` has been implemented as a safety level to assume that the user is _really really sure and aware_ of what he's doing, and upgrade didn't happen by accident 😄

**Comment by OlafvdSpek** [comment]
It's not like `vcpkg upgrade` is typed by accident with a single press of the Enter key. ;)

**Comment by claudiofantacci** [comment]
> It's not like vcpkg upgrade is typed by accident with a single press of the Enter key. ;)

Agree, but it's an abrupt change in the behaviour.
Anyway, let's see if we get opinions form MSFT team as well! 😃

**Comment by NancyLi1013** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.
