### ISSUE TITLE
[New Port Request] imtui

### ISSUE THREAD

**Issue by lichray** [microsoft/vcpkg#26867]
Library name: imtui

Library description: Immediate mode text-based user interface library

Source repository URL: https://github.com/ggerganov/imtui

Project homepage (if different from the source repository): https://imtui.ggerganov.com/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): requires ncurses.

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
