### ISSUE TITLE
[freexl] build failure on x64-linux on fedora-36

### ISSUE THREAD

**Issue by ankurvdev** [microsoft/vcpkg#26860]
**Host Environment**

- OS: Linux Fedora 36
- Compiler: gcc-12

**To Reproduce**

`./vcpkg install freexl:x64-linux`

**Failure logs**

**Additional context**

The freexl port config fails due to missing libiconv while configuring make
Looking into the libiconv port. It seems libiconv is supposed to be an empty package on linux

```
if(NOT VCPKG_TARGET_IS_WINDOWS AND NOT VCPKG_TARGET_IS_ANDROID)
    set(VCPKG_POLICY_EMPTY_PACKAGE enabled)
    file(MAKE_DIRECTORY "${CURRENT_PACKAGES_DIR}/share/iconv")
    file(COPY "${CMAKE_CURRENT_LIST_DIR}/vcpkg-cmake-wrapper.cmake" DESTINATION "${CURRENT_PACKAGES_DIR}/share/iconv")
    return()
endif()
```
Removing the empty package snippet from port/libiconv/portfile.cmake fixes the issue.
Once libiconv is actually installed freexl proceeds without complaining

JFYI, 
On Fedora-36 Iconv is part of the glibc-common dnf package which i have it installed on my OS
However there doesnt seem to be a libiconv.a or libiconv.so provided by the OS packages.

**Comment by Cheney-W** [comment]
The problem is only happening on this particular system, so it's not a vcpkg issue.
As you mentioned above, after removing empty package snippet from `port/libiconv/portfile.cmake`, the problem is solved, I think you can use it as a workaround.

**Comment by dg0yt** [comment]
Regarding the freexl error: By properly reporting the original error, we could properly help to resolve the problem. vcpkg reports log files for this purpose.

Regarding libiconv: Did you install the development package corresponding to glibc-common?

**Comment by ankurvdev** [comment]
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: /usr/bin/bash -c "V=1 ./../src/freexl-1-0b9ac2177e.clean/configure  \"LIBS=-liconv $LIBS\" \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"--prefix=/home/ankurv/devel/vcpkg.test/installed/x64-linux/debug\" \"--bindir=\\${prefix}/../tools/freexl/debug/bin\" \"--sbindir=\\${prefix}/../tools/freexl/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/freexl\""
    Working Directory: /home/ankurv/devel/vcpkg.test/buildtrees/freexl/x64-linux-dbg
 ```
 
 
 vcpkg-tool version: 2022-09-01-dfb82802c8cc562ce3b665a904a65b22314de724
    vcpkg-scripts version: 4dbb7578c 2022-09-18 (3 days ago)
    
   ```
   cat       /home/ankurv/devel/vcpkg.test/buildtrees/freexl/config-x64-linux-dbg-err.log
configure: error: in `/home/ankurv/devel/vcpkg.test/buildtrees/freexl/x64-linux-dbg':
configure: error: C compiler cannot create executables
See `config.log' for more details
```
```
 cat       /home/ankurv/devel/vcpkg.test/buildtrees/freexl/config-x64-linux-dbg-out.log
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports the include directive... yes (GNU style)
checking for gcc... /usr/bin/cc
checking whether the C compiler works... no
```
```
 cat       /home/ankurv/devel/vcpkg.test/buildtrees/freexl/config-x64-linux-dbg-out.log
 
 ....
 configure:4199: $? = 1
configure:4219: checking whether the C compiler works
configure:4241: /usr/bin/cc -fPIC -g  -L/home/ankurv/devel/vcpkg.test/installed/x64-linux/debug/lib conftest.c -liconv  >&5
/usr/bin/ld: cannot find -liconv
collect2: error: ld returned 1 exit status

```

**Comment by ankurvdev** [comment]
I have the development packages 
glibc-devel
along with glibc-gconv-extra and glibc-utils too

**Comment by ankurvdev** [comment]
Is there a reason libiconv is turned off for x64-linux. 
I'm unblocked with the changes I suggested but i'm wondering why that isnt the default behaviour ?

**Comment by dg0yt** [comment]
AFAIU the reason is that iconv (the features) is present on most POSIXish systems, even without a distinct iconv (the library).

~~~
configure:4219: checking whether the C compiler works
configure:4241: /usr/bin/cc -fPIC -g  -L/home/ankurv/devel/vcpkg.test/installed/x64-linux/debug/lib conftest.c -liconv  >&5
/usr/bin/ld: cannot find -liconv
collect2: error: ld returned 1 exit status
~~~
The check for a working C compiler shouldn't use `-liconv` (which requires an iconv library), and it doesn't on my linux machine. At this early point, environment variable `LIBS` seems to be the only potential source for this flag.
It might be easier if we had the full `config-x64-linux-dbg-out.log`.

**Comment by ankurvdev** [comment]
[config-x64-linux-dbg-config.log](https://github.com/microsoft/vcpkg/files/9637913/config-x64-linux-dbg-config.log)

**Comment by dg0yt** [comment]
Configurations starts with 
~~~
$ ./../src/freexl-1-0b9ac2177e.clean/configure 'LIBS=-liconv ' ...
~~~
This is what I expected. There are two possible sources:
- your environment (check with `echo $LIBS`)
- your CMake installation, via `CMAKE_C_STANDARD_LIBRARIES` (cf. `cmake-vars-x64-linux-dbg.cmake.log`)

In either case, it is outside of vcpkg: vcpkg is explicitly told to use `-liconv`.

**Comment by ankurvdev** [comment]
LIBS is empty and i thought vcpkg downloads and uses its own cmake
[cmake-vars-x64-linux-dbg.cmake.log](https://github.com/microsoft/vcpkg/files/9638880/cmake-vars-x64-linux-dbg.cmake.log)

dont see liconv in the file you mentioned.

Also if my environment were the issue, i would get failures compiling pretty much everything.

Pretty much everything except freexl compiles fine on my environment

**Comment by ankurvdev** [comment]
Never mind .. Found the issue. It was indeed my environment. I made changes to fix freexl compilation on android. 
I'll close this one .
