### ISSUE TITLE
[New Port Request] <qoixx>

### ISSUE THREAD

**Issue by TimeEntropy** [microsoft/vcpkg#26886]
Library name:
qoixx

Library description:
qoixx is a high performance MIT licensed single-header [QOI](https://github.com/phoboslab/qoi) implementation written in C++20.

Source repository URL:
https://github.com/wx257osn2/qoixx.git

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
