### ISSUE TITLE
[New Port Request] screen_capture_lite

### ISSUE THREAD

**Issue by IshaanKarnik** [microsoft/vcpkg#26888]
Library name: [screen_capture_lite](https://github.com/smasherprog/screen_capture_lite)

Library description: Cross-platform screen and window capturing library

Source repository URL: https://github.com/smasherprog/screen_capture_lite.git

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
