### ISSUE TITLE
[catch2] windows build of catch2 should be using static build

### ISSUE THREAD

**Issue by horenmar** [microsoft/vcpkg#26880]
Catch2 recently enabled being built as a dynamic library, but it does not provide export macros. (And likely never fully will)

On Linux this is fine-ish due to symbols being visible by default, and variables being merged across dynamic libraries. On Windows this is an issue, because CMake's option for exporting all symbols on Windows cannot handle variables. Variables still need to be `dllimport`ed, and if they aren't, linking Catch2 does not work the way it should.

Combined with the default Windows triplet using dynamic linking for everything, this is kind of a big issue for people using Catch2 v3 through vcpkg.

**Comment by FrankXie05** [comment]
@horenmar Thanks for posting this issue and pointing out the issue.
Apparently you made a change to the symbol export of dynamic libraries on widnows, both my local cmake and MSVC projects can use catch2 normally. 
![image](https://user-images.githubusercontent.com/65999885/191901966-b882f92a-ba40-4d27-953a-5b402f503273.png)

https://github.com/catchorg/Catch2/commit/5a1ef7e4a6caf3d5f696eb82302e3d87ff5c2303
I would like to ask do you mean to make catch2 use static build by default on windows to avoid the problem you raised?

**Comment by horenmar** [comment]
The issue manifests when linking:

```cmake
cmake_minimum_required(VERSION 3.19)

project(link-test LANGUAGES CXX)

find_package(Catch2 REQUIRED CONFIG)
add_executable(tests tests.cpp)
target_link_libraries(tests PRIVATE Catch2::Catch2WithMain)
```

```cpp
#include <catch2/catch_test_macros.hpp>

TEST_CASE("foo", "[bar]") {
	Catch::StringMaker<double>::precision = 2;
	REQUIRE(1.0 != 2.0);
}
```

```
1>------ Build started: Project: tests, Configuration: Debug x64 ------
1>tests.cpp
1>tests.obj : error LNK2001: unresolved external symbol "public: static int Catch::StringMaker<double,void>::precision" (?precision@?$StringMaker@NX@Catch@@2HA)
1>C:\ubuntu\temp\msvc-sln\Debug\tests.exe : fatal error LNK1120: 1 unresolved externals
1>Done building project "tests.vcxproj" -- FAILED.
```
