### ISSUE TITLE
[protobuf] - x86-windows port cmake files

### ISSUE THREAD

**Issue by Eddie-cz** [microsoft/vcpkg#26893]
protobuf version 3.21.4

Is there a reason for x86-windows port not to set protobuf_BUILD_PROTOC_BINARIES, thus not importing protobuf::protoc in protobuf-targets*.cmake files?

x64-windows port does set it and produces correct cmake output imho.

**Comment by Neumann-A** [comment]
> Is there a reason for x86-windows port .....

You are using the `x86-windows` triplet in a cross-compiling context. Pass `--host-triplet=x86-windows` or set `VCPKG_HOST_TRIPLET` in cmake to the correct value. By default vcpkg assumes `x64-windows` to be the default host triplet.

**Comment by Eddie-cz** [comment]
Thanks for clarification, I confirm setting host triplet as suggested does produce expected output.
