### ISSUE TITLE
libxmlpp build failure

### ISSUE THREAD

**Issue by wgreene310** [microsoft/vcpkg#26890]
**Host Environment**

- OS:Windows 10
- Compiler: VS 2022

`./vcpkg install libxmlpp:x64-windows`

[package-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/9607942/package-x64-windows-dbg-out.log)

**Comment by wgreene310** [comment]
Here is some additional info:

**Host Environment**
- Host: x64-windows
- Compiler: MSVC 19.32.31332.0
-    vcpkg-tool version: 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e
    vcpkg-scripts version: 4340582bc 2022-09-19 (16 hours ago)


**To Reproduce**
`vcpkg install libxmlpp:x64-windows`


**Failure logs**
```
-- Using cached libxml++-5.0.0.tar.xz.
-- Cleaning sources at C:/Users/bgreene/Downloads/vcpkg/buildtrees/libxmlpp/src/libxml++-5-7c4d4a4cea.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/bgreene/Downloads/vcpkg/downloads/libxml++-5.0.0.tar.xz
-- Using source at C:/Users/bgreene/Downloads/vcpkg/buildtrees/libxmlpp/src/libxml++-5-7c4d4a4cea.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows
-- Configuring x64-windows-dbg
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at C:/Users/bgreene/Downloads/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Configuring x64-windows-dbg done
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Package x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" install -v
    Working Directory: C:/Users/bgreene/Downloads/vcpkg/buildtrees/libxmlpp/x64-windows-dbg
    Error code: 1
    See logs for more information:
      C:\Users\bgreene\Downloads\vcpkg\buildtrees\libxmlpp\package-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
  ports/libxmlpp/portfile.cmake:25 (vcpkg_install_meson)
  scripts/ports.cmake:147 (include)

**Comment by StarGate-One** [comment]
>FAILED: libxml++/MSVC_NMake_libxml++_libxml++.rc_libxml++.res 
>"C:/Program Files (x86)/Windows Kits/10/bin/10.0.19041.0/x64/rc.exe" "/nologo" "/folibxml++/MSVC_NMake_libxml++_libxml++.rc_libxml++.res" "MSVC_NMake/libxml++/libxml++.rc"
>MSVC_NMake/libxml++/libxml++.rc(4) : fatal error RC1015: cannot open include file 'afxres.h'.

The `afxres.h` file and most likely others that are part of the Optional components in the Desktop Development with C++ in Visual Studio 2022.

Open the visual studio install, scroll down to the Desktop Development with C++ and under Optional, ensure the first 2 items, are selected (if not select them) like the highlighted options shown below:
![image](https://user-images.githubusercontent.com/68293825/191315912-426a8ae3-9f17-430b-9266-322bf78137ab.png)

**Comment by wgreene310** [comment]
Many thanks, that seems to have solved the problem.

**Comment by StarGate-One** [comment]
You are most welcomed! Glad the problem is resolved. Have a super day.
