### ISSUE TITLE
Add libjpeg

### ISSUE THREAD

**Issue by Wakusei** [Microsoft/vcpkg#269]
I'd like to add libjpeg. I konw turbo-jpeg is already added and it's faster, but there is existing code using libjpeg. I think adding it is meaningful.

**Comment by barcharcraz** [comment]
libjpeg-turbo is ABI compatible with libjpeg. AFAIK most linux distros only distribute libjpeg-turbo, I just looked at ubuntu and this appears to be the case.

**Comment by barcharcraz** [comment]
Also if this were added it should be mutually exclusive with libjpeg-turbo

**Comment by Wakusei** [comment]
I forgot the compatibility though I used it years ago. libjpeg isn't needed.
