### ISSUE TITLE
[glog] Build error

### ISSUE THREAD

**Issue by liujin121** [microsoft/vcpkg#26904]
error: building glog:x64-mingw-dynamic failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+glog
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[glog]+Build+error
Include '[glog] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-09-20-522aa94e9d261c7d7b2f079bf2591ca62df5c714
    vcpkg-scripts version: unknown

**Comment by FrankXie05** [comment]
@liujin121 Please provide the error log.

**Comment by israel-gonzalezmedina** [comment]
[vcpkg-manifest-install.log](https://github.com/microsoft/vcpkg/files/10179430/vcpkg-manifest-install.log)

**Comment by FrankXie05** [comment]
```
CMake Error at ports/glog/portfile.cmake:22 (vcpkg_cmake_configure):
  Unknown CMake command "vcpkg_cmake_configure".
```
This method is provided by `vcpkg-cmake-config`, please make sure you use the latest vcpkg. 
https://github.com/microsoft/vcpkg/blob/30a20e8f15ff26eec665205dea52f4ffc6f0814b/ports/glog/vcpkg.json#L15

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
