### ISSUE TITLE
Download link for jxrlib is broken.

### ISSUE THREAD

**Issue by ventsin** [Microsoft/vcpkg#2690]
I can't seem to download the jxrlib_1_1.zip archive from the link in the portfile. Thus, after hanging for a while the install parameter times out and fails. Perhaps something to do with the CodePlex shutdown? Can anyone confirm if the package installation is failing as well?

Running Windows 10 (latest version) with pt-br locale.

For the sake of completeness the error can be reproduced by running: `.\vcpkg install jxrlib`, although my first attempt was at building Ogre3D: `.\vcpkg install ogre`. Is jxrlib really a dependency in this case? I can't seem to find any information on that in the dependency page for Ogre: http://wiki.ogre3d.org/Building+Dependencies.

  Package: jxrlib:x86-windows
  Vcpkg version: 0.0.103-2018-01-30-5700754bd11fe9b22728bd8682c9cfe67a69a462

Not entirely sure what other information may be useful.

The CodePlex Archive grants me this download link: https://codeplexarchive.blob.core.windows.net/archive/projects/jxrlib/jxrlib.zip.
And a community ported repository on GitHub for jxrlib:
https://github.com/4creators/jxrlib.

Maybe these links can be of help.

**Comment by ventsin** [comment]
I see the issue has been fixed, thanks!

**Comment by ras0219-msft** [comment]
Thanks! This is fixed in master.
