### ISSUE TITLE
[libjxl] update to 0.7.0

### ISSUE THREAD

**Issue by 0xC0000054** [microsoft/vcpkg#26909]
Library name: libjxl

New version number: 0.7.0

Other information that may be useful (release notes, etc...)
https://github.com/libjxl/libjxl/releases/tag/v0.7.0

Build notes:

libjxl now supports the CMake `BUILD_SHARED_LIBS` option, so the portfile needs be updated to use that.
The patches need to be updated.

**Comment by JonLiu1993** [comment]
Fixed by #27593
