### ISSUE TITLE
[qt] qt5-script build error

### ISSUE THREAD

**Issue by LetterfromLongBow** [microsoft/vcpkg#26925]
**Host Environment**

- OS: [Windows 10]
- vcpkg-tool version: 2022-09-20-522aa94e9d261c7d7b2f079bf2591ca62df5c714
- vcpkg-scripts version: d52632d9a 2022-09-21 (16 hours ago)

**To Reproduce**

`./vcpkg install qt5-script:x64-windows`

**Failure logs**

`CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: D:/SRC/vcpkg/downloads/tools/jom/jom-1.1.3/jom.exe -j 21
    Working Directory: D:/SRC/vcpkg/buildtrees/qt5-script/x64-windows-dbg
    See logs for more information:
      D:\SRC\vcpkg\buildtrees\qt5-script\package-build-x64-windows-dbg-out.log
      D:\SRC\vcpkg\buildtrees\qt5-script\package-build-x64-windows-dbg-err.log`
**And the error log shows:**
jom 1.1.3 - empower your cores
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
jom: D:\SRC\vcpkg\buildtrees\qt5-script\x64-windows-dbg\src\script\Makefile.Debug [..\..\lib\Qt5Scriptd.dll] Error 1120
jom: D:\SRC\vcpkg\buildtrees\qt5-script\x64-windows-dbg\src\script\Makefile [debug] Error 2
jom: D:\SRC\vcpkg\buildtrees\qt5-script\x64-windows-dbg\src\Makefile [sub-script-make_first-ordered] Error 2
jom: D:\SRC\vcpkg\buildtrees\qt5-script\x64-windows-dbg\Makefile [sub-src-make_first] Error 2

**Additional context**
I wanna use colmap,and it need qt-script.But when I bulid qt5-script,it always fail.How can I solve this problem

**Comment by Neumann-A** [comment]
Error 1120 -> unresolved symbol -> needs other log (package-build-x64-windows-dbg-out.log) to see what exactly is missing.

**Comment by LetterfromLongBow** [comment]
**In package-build-x64-dbg-out.log,it shows:** 
`JSGlobalData.obj : error LNK2019: unresolved external symbol "private: static void __cdecl QTJSC::MarkedArgumentBuffer::operator delete(void *,unsigned __int64)" (??3MarkedArgumentBuffer@QTJSC@@CAXPEAX_K@Z) referenced in function "int `private: __cdecl QTJSC::JSGlobalData::JSGlobalData(bool)'::`1'::dtor$9" (?dtor$9@?0???0JSGlobalData@QTJSC@@AEAA@_N@Z@4HA)`
`..\..\lib\Qt5Scriptd.dll : fatal error LNK1120: 1 unresolved externals`

**Comment by LetterfromLongBow** [comment]
[package-build-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/9630360/package-build-x64-windows-dbg-out.log)
[package-build-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/9630361/package-build-x64-windows-dbg-err.log)

**Comment by Adela0814** [comment]
@LetterfromLongBow The `qt5` is upgraded, could you please pull the latest vcpkg and try again?

**Comment by Adela0814** [comment]
I'm not able to repro this via vcpkg version `2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895`. If more information comes up, or this issue appears again, please reopen.
