### ISSUE TITLE
[USD] update to 22.08

### ISSUE THREAD

**Issue by Cheney-W** [microsoft/vcpkg#26920]
Library name: usd

New version number: 22.08

Other information that may be useful (release notes, etc...)
https://github.com/PixarAnimationStudios/USD/releases/tag/v22.08

This request is from https://github.com/PixarAnimationStudios/USD/pull/2041.

**Comment by meshula** [comment]
Hi @Cheney-W the PR looks great, thanks so much for tackling this :)

We are now in final QA on 22.11. The work in your PR https://github.com/microsoft/vcpkg/pull/26941), for 22.08 is the same as what will be needed for 22.11, just the hashes are different of course. Would it make sense to wait until the release of 22.11 [next week] and update USD on vcpkg all the way to 22.11, or would it make sense to land 22.08 now, and follow up shortly with the 22.11 version update?

**Comment by Cheney-W** [comment]
If the waiting time is not more than a month, I think it make sense to wait until the release of 22.11.

**Comment by meshula** [comment]
Ok, thanks! I'll update this thread asap with release data.

**Comment by Cheney-W** [comment]
@meshula 
I saw there is a [v22.11-rc1](https://github.com/PixarAnimationStudios/USD/releases/tag/v22.11-rc1) tag in PixarAnimationStudios/USD, can I update to this version?

**Comment by meshula** [comment]
The real release is almost ready, we're just finishing up now! I'll update this thread.

**Comment by meshula** [comment]
Okay v22.11 is tagged and released! https://github.com/PixarAnimationStudios/USD/releases/tag/v22.11
Thanks for your patience!

**Comment by meshula** [comment]
Hi @Cheney-W! I was just looking at https://github.com/PixarAnimationStudios/USD/pull/2041/files ~ it was waiting on the update to 22.08, as it seemed like a good checkpoint, in terms of pointing people to vcpkg to get a recent USD build. I was wondering what the status might be of updating USD in vcpkg?

**Comment by Cheney-W** [comment]
Update is blocked by https://github.com/PixarAnimationStudios/USD/issues/1600 now.

**Comment by meshula** [comment]
Oh! I didn't know that. I'll start tracking these issues together.

**Comment by Adela0814** [comment]
Fixed by https://github.com/microsoft/vcpkg/pull/29688.
