### ISSUE TITLE
[qtwebengine] Build error

### ISSUE THREAD

**Issue by undersilence** [microsoft/vcpkg#26939]
**Host Environment**
windows10 
vcpkg-tool version: 2022-09-20-522aa94e9d261c7d7b2f079bf2591ca62df5c714
vcpkg-scripts version: 86eb754bc 2022-09-22 (8 hours ago)

**To Reproduce**

vcpkg install qt:x64-windows

**Failure logs**

```
Computing installation plan...
The following packages will be built and installed:
    qt[core]:x64-windows -> 6.3.2
  * qtwebengine[core,default-features,geolocation,spellchecker,webchannel]:x64-windows -> 6.3.2
  * qtwebsockets[core,qml]:x64-windows -> 6.3.2
  * qtwebview[core,qml,webengine]:x64-windows -> 6.3.2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\zaili.tu\AppData\Local\vcpkg\archives in 287.7 us. Use --debug to see more details.
Installing 1/4 qtwebengine:x64-windows...
Building qtwebengine[core,default-features,geolocation,spellchecker,webchannel]:x64-windows...
-- Setting up python virtual environmnent...
-- Installing python packages: html5lib
-- Setting up python virtual environmnent...finished.
CMake Warning at ports/qtwebengine/portfile.cmake:83 (message):
  Buildtree path 'E:/Develop/vcpkg/buildtrees/qtwebengine' is too long.

  Consider passing --x-buildtrees-root=<shortpath> to vcpkg!

  Trying to use 'E:/Develop/vcpkg/buildtrees/qtwebengine/../tmp'
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)
```

**Additional context**

**Comment by Neumann-A** [comment]
close..... 

Answer here:

`Consider passing --x-buildtrees-root=<shortpath> to vcpkg!`

> E:/Develop/vcpkg/buildtrees/

is too long as a path ..... the log already tells you what to do.

**Comment by undersilence** [comment]
> close.....
> 
> Answer here:
> 
> `Consider passing --x-buildtrees-root=<shortpath> to vcpkg!`
> 
> > E:/Develop/vcpkg/buildtrees/
> 
> is too long as a path ..... the log already tells you what to do.

😂ok, how stupid i am to miss these important logs. Thx~

**Comment by Tanqingshan** [comment]
> > close.....
> > Answer here:
> > `Consider passing --x-buildtrees-root=<shortpath> to vcpkg!`
> > > E:/Develop/vcpkg/buildtrees/
> > 
> > 
> > is too long as a path ..... the log already tells you what to do.
> 
> 😂ok, how stupid i am to miss these important logs. Thx~

I am encountering the same problem. But how to set a short path? :(
