### ISSUE TITLE
[json schema] Missing `supports` for a feature

### ISSUE THREAD

**Issue by Thomas1664** [microsoft/vcpkg#26952]
When using our JSON schema I get a warning that `supports` is not allowed for features. This is no longer true and the schema needs to be updated.

![image](https://user-images.githubusercontent.com/46387399/192024418-03edc34d-f8c6-4a1a-b9c7-2b66206f1730.png)

**Comment by Cheney-W** [comment]
Which editor are you using?

**Comment by Thomas1664** [comment]
VS code

**Comment by Cheney-W** [comment]
I randomly found a `vcpkg.json` file and tried to add `"supports"` field to the feature `avx`, but I didn't encounter the problem you mentioned. 
![image](https://user-images.githubusercontent.com/38240633/192237866-9c18f37d-be79-4407-9ded-97b335d505a9.png)

This is my VS Code:
![image](https://user-images.githubusercontent.com/38240633/192238648-d681efe0-bbf4-4d24-887d-b59c61229b43.png)
What's the version of yours?

**Comment by Thomas1664** [comment]
Hi @Cheney-W,

Sorry for the confusion but this is indeed a bug: The JSON schema is missing the property `supports` of the object `features`. You can confirm this by searching for `feature` inside the schema: https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json

**Comment by BillyONeal** [comment]
It's here: https://github.com/microsoft/vcpkg-tool/blob/3e843923eef525d1c5c23a5768b00f8072145fdc/docs/vcpkg-schema-definitions.schema.json#L296-L298

Thanks :)
