### ISSUE TITLE
Should ISPC be a well-known tool?

### ISSUE THREAD

**Issue by Tradias** [microsoft/vcpkg#26965]
I am planning on contributing the port files of [OSPRay](https://github.com/ospray/OSPRay), [OpenVLK](https://github.com/OpenVKL/openvkl) and [rkcommon](https://github.com/ospray/rkcommon) that I have created. They depend on [ISPC](https://ispc.github.io/). I currently use `find_program` in their port files to acquire the system installed variant of it, but that will certainly not work for the vcpkg pipelines here. Therefore my question, how to best handle it? Adding it to [vcpkg_find_acquire_program](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_find_acquire_program.md) sounds like an option, but since ISPC is a compiler, I am not sure that is the right place (seeing that compilers are generally expected to be provided through toolchain files).

See also previous issues on ISPC: https://github.com/microsoft/vcpkg/issues/15846, https://github.com/microsoft/vcpkg/issues/8698

**Comment by LilyWangLL** [comment]
Thanks for posting this issue, you can add it like `vcpkg-tool-meson` or `vcpkg-tool-gn`.

**Comment by JonLiu1993** [comment]
Fixing by PR #29261
