### ISSUE TITLE
[luajit] lua libraries

### ISSUE THREAD

**Issue by DarthGandalf** [microsoft/vcpkg#26972]
****

**Is your feature request related to a problem? Please describe.**

Various lua libraries available in vcpkg, like `lpeg` or `sol2`, depend on lua, and there's no way to use them with luajit instead of lua

**Proposed solution**
Somehow tell the library whether it should build against lua or luajit. A new feature maybe.

**Describe alternatives you've considered**

1. Install these libraries not from vcpkg, but in some other way
1. Duplicate the lua libraries ports, to make e.g. `lpeg` and `lpeg-luajit`

**Additional context**

**Comment by DarthGandalf** [comment]
> Per our repo policy, stale issues get close

What a hostile policy.

**Comment by dg0yt** [comment]
A friendly reply to the bot message might have a more positive impact than an issue without a "hostile" bot message, burried below 1000 other stale issues.
(For this issue, you could get more information of what is possible at the moment and what isn't. But I'm afraid the issue wasn't sufficiently understood. Maybe the maintainers need a `topic:alternatives` label.)

**Comment by DarthGandalf** [comment]
Even if it was understood correctly, I really don't expect it to be fixed right away anyway :)

**Comment by dg0yt** [comment]
Port sol2 no longer depends on port Lua, #35545.
For lpeg, a hard dependency cannot be dropped. 

vcpkg currently doesn't really support choosing between alternatives. It might be possible to use a thin overlay port to replace one Lua with the other, but they are not really compatible.
