### ISSUE TITLE
How do i compile for iOS, tvOS and watchOS?

### ISSUE THREAD

**Issue by paulocoutinhox** [microsoft/vcpkg#26979]
Hi,

Im trying compile SDL2 for iOS, tvOS and watchOS and enable "bitcode", but i don't find any informations or example about this.

Can be an example about any library.

Can anyone help me?

Thanks.

**Comment by fwcd** [comment]
In principle you can cross-compile to iOS by passing `--triplet arm64-ios` to `vcpkg install`, but this is an unsupported community triplet, so you may encounter build failures. Depending on the error, you may also need to set the `SDKROOT` (which you can find by running `xcrun --sdk iphoneos --show-sdk-path`) or patch the package itself.

**Comment by FrankXie05** [comment]
@paulocoutinhox Thanks for posting this issue, you can run command `./vcpkg install sdl2 --triplet arm64-ios`.

**Comment by paulocoutinhox** [comment]
Hi @FrankXie05, thanks for answer.

How i can use the bitcode, arc and visibility flags?

**Comment by JackBoosY** [comment]
@paulocoutinhox Add `set(VCPKG_CXX_FLAGS <BITCODE_OPTION>)` and `set(VCPKG_C_FLAGS <BITCODE_OPTION>)` to the triplet file which in _triplets_ folder.

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
