### ISSUE TITLE
build libmysql in mac is successful,but in centos all  failed ,because of  BGL and  icu

### ISSUE THREAD

**Issue by mullerhai** [microsoft/vcpkg#26985]
HI:
       when I install  libmysql package with vcpkg ,on  mac  is  build successfully final ,but also meet so many failed try times,  on centos7 ,use vcpkg install libmysql ,straightly failed , cannot install, meet  icu4c-71_1-src.tgz    * icu[core]:x64-linux -> 71.1 and  Boost Graph Library  boostorg-graph-boost-1.80.0.tar.gz  not found.

thanks

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please provide the error log file. Did you install it on the latest vcpkg?

**Comment by mullerhai** [comment]
> Thanks for posting this issue. Please provide the error log file. Did you install it on the latest vcpkg?

yeah,the lastest vcpkg is install

**Comment by LilyWangLL** [comment]
> Please provide the error log file.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by mullerhai** [comment]
> Thanks for posting this issue. Please reopen this issue if this is still a problem for you.

Hi ,Now  I have clear the linux disk,can not find the log, in my opinion , the error should  be remeet by  all the linux  environment, We need to deal with  the execute-logical of  vcpkg install dependency packages, you can try any linux  machine  to execute the command  [vcpkg install libmysql ] ,will meet the same error

**Comment by LilyWangLL** [comment]
I can't reproduce this issue. I use the Ubuntu, this is my output log:
```
Elapsed time to handle libmysql:x64-linux: 7.855 min
Total elapsed time: 24.32 min

The package libmysql provides CMake targets:

    find_package(libmysql REQUIRED)
    target_link_libraries(main PRIVATE ${MYSQL_LIBRARIES})
```

**Comment by mullerhai** [comment]
> I can't reproduce this issue. I use the Ubuntu, this is my output log:
> 
> ```
> Elapsed time to handle libmysql:x64-linux: 7.855 min
> Total elapsed time: 24.32 min
> 
> The package libmysql provides CMake targets:
> 
>     find_package(libmysql REQUIRED)
>     target_link_libraries(main PRIVATE ${MYSQL_LIBRARIES})
> ```

please try to use centos7

**Comment by LilyWangLL** [comment]
> > I can't reproduce this issue. I use the Ubuntu, this is my output log:
> > ```
> > Elapsed time to handle libmysql:x64-linux: 7.855 min
> > Total elapsed time: 24.32 min
> > 
> > The package libmysql provides CMake targets:
> > 
> >     find_package(libmysql REQUIRED)
> >     target_link_libraries(main PRIVATE ${MYSQL_LIBRARIES})
> > ```
> 
> please try to use centos7

I don't have centos machine, I will reopen this issue. Maybe someone have idea about this issue.

**Comment by JonLiu1993** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
