### ISSUE TITLE
Error: building boost-python:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by zormnus** [microsoft/vcpkg#26995]
I've got following error message and i really don't have any ideas how to fix it...

PS C:\dev\vcpkg> .\vcpkg.exe install boost-python:x64-windows
Computing installation plan...
The following packages will be built and installed:
    boost-python[core,python3]:x64-windows -> 1.80.0
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\Макс\AppData\Local\vcpkg\archives in 399.5 us. Use --debug to see more details.
Installing 1/1 boost-python:x64-windows...
Building boost-python[core,python3]:x64-windows...
-- Using cached boostorg-python-boost-1.80.0.tar.gz.
-- Cleaning sources at C:/dev/vcpkg/buildtrees/boost-python/src/ost-1.80.0-64a3511b26.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/boostorg-python-boost-1.80.0.tar.gz
-- Using source at C:/dev/vcpkg/buildtrees/boost-python/src/ost-1.80.0-64a3511b26.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: C:/dev/vcpkg/downloads/tools/cmake-3.24.0-windows/cmake-3.24.0-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: C:/dev/vcpkg/buildtrees/boost-python/x64-windows-dbg
    See logs for more information:
      C:\dev\vcpkg\buildtrees\boost-python\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:136 (vcpkg_cmake_install)
  ports/boost-python/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:147 (include)

error: building boost-python:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-python
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-python]+Build+error
Include '[boost-python] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-09-20-522aa94e9d261c7d7b2f079bf2591ca62df5c714
    vcpkg-scripts version: 8e8a3d7c1 2022-09-25 (11 hours ago)

**Comment by JackBoosY** [comment]
Please provide C:\dev\vcpkg\buildtrees\boost-python\install-x64-windows-dbg-out.log first.

**Comment by zormnus** [comment]
I have already solve problem after open that file, thx

**Comment by zormnus** [comment]
it was cause of cyrillic symbols in my python's interpreter's directory

**Comment by Jreich64** [comment]
> I have already solve problem after open that file, thx

Hi Im having the same problem, would you be able to tell me what you did to fix it?
