### ISSUE TITLE
[openvdb] Build error

### ISSUE THREAD

**Issue by yunlong-monash** [microsoft/vcpkg#26993]
**Host Environment**

- OS: Windows
- Compiler: v142

**To Reproduce**

`./vcpkg install openvdb:x64-windows-static`

openvdb\openvdb\libopenvdb.lib : fatal error LNK1248: image size (1093ABD05) exceeds maximum allowable size (FFFFFFFF)
ninja: build stopped: subcommand failed.

**Comment by Cheney-W** [comment]
What's the version of your VS and vcpkg? 
Could you please provide the error log to us?

**Comment by yunlong-monash** [comment]
> What's the version of your VS and vcpkg? Could you please provide the error log to us?

The version of VS is 2019 and the error log is attached. Thanks!

[install-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/9654871/install-x64-windows-static-dbg-out.log)

**Comment by sparshpriyadarshi** [comment]
on `vcpkg install openvdb[core,tools]` for x64-windows, windows 10, VS 2019  I get a build failure too

[openvdb] Build error 
vcpkg-tool version: 2022-09-20-522aa94e9d261c7d7b2f079bf2591ca62df5c714
vcpkg-scripts version: 79fa9d85c 2022-10-17 (8 hours ago)

logs:
error: building openvdb:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.

**Comment by cgolchert** [comment]
Any movement on this?

**Comment by Sumobit** [comment]
I have this error as well when I build the static library. The release version compiles fine while the debug build fails with the specified error.

**Comment by dg0yt** [comment]
... too much debug information for static builds due to `/Z7`? IIUC `/Zi` could help, but needs extra work to deal with PDB files.
