### ISSUE TITLE
webpd.dll/webp.dll are not copied to debug/bin/ and bin/ after "vcpkg install libwebp"

### ISSUE THREAD

**Issue by rushio0x58** [Microsoft/vcpkg#2699]
Hello!
I installed the package `sdl2-image` and one of its dependencies `libwebp`. The library `sdl2-image` expects a dll named `webpd.dll`/`webp.dll` which is nowhere to be found in `vcpkg-master/installed/x64-windows/debug/bin/` or "`vcpkg-master/installed/x64-windows/bin/`. The static libraries webpd.lib and webp.lib are installed correctly. Both dlls hang around in the directory `vcpkg-master/buildtrees/libwebp/x64-windows-(dbg|rel)`, so there seems to be a missing copy statement somewhere?

- `vckpkg version` prints `0.0.103-unknownhash`
- OS: Windows 10, the cmake makes calls to `VC\Tools\MSVC\14.12.25827\bin\Hostx64\x64\cl.exe` in the build process

**Comment by rushio0x58** [comment]
I overlooked issue #2618, of which this issue is probably a duplicate of.

**Comment by lazyhamster** [comment]
It is similar issue but not a duplicate.

**Comment by lazyhamster** [comment]
Should be fixed now with ee1c60d2c8efcb305f2d715a5a200d7d00dd6574.

**Comment by rushio0x58** [comment]
Tested on 51e8b5da7cd8fd1273a99dac953de1aa193e7ac9 - webpd.dll and webp.dll are where they're supposed to be. As far as I can tell, it is fixed.
