### ISSUE TITLE
[fmt] Error when including using cmake

### ISSUE THREAD

**Issue by Morten242** [Microsoft/vcpkg#270]
When I use `find_package(fmt)` then I get the following error when I try to reconfigure my project:

```
» cmake .
CMake Error at D:/path/to/vcpkg/installed/x86-windows/share/fmt/fmt-targets.cmake:87 (message):
  The imported target "fmt" references the file

     "D:/path/to/vcpkg/installed/lib/fmt.lib"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "D:/path/to/vcpkg/installed/x86-windows/share/fmt/fmt-targets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  D:/path/to/vcpkg/installed/x86-windows/share/fmt/fmt-config.cmake:27 (include)
  src/CMakeLists.txt:1 (find_package)


-- Configuring incomplete, errors occurred!
```

There were no issues when building the library. The path to fmt.lib should be `D:/path/to/vcpkg/installed/x86-windows/lib/fmt.lib` to be valid.

Package&version: `fmt:x86-windows             3.0.0-1`

**Comment by traversaro** [comment]
This is specific instance of the problem described in https://github.com/Microsoft/vcpkg/issues/77 .

Currently we are solving it using the strategy described in https://github.com/Microsoft/vcpkg/issues/77#issuecomment-250028244 . In this case you need to add a `-DFMT_CMAKE_DIR=share/fmt` (see https://github.com/fmtlib/fmt/blob/master/fmt/CMakeLists.txt#L55 ) to the `OPTIONS` of `vcpkg_configure_cmake` and modify the debug targets as in (for example) https://github.com/Microsoft/vcpkg/blob/master/ports/openjpeg/portfile.cmake#L20 .

I think that also the `assimp` port is affected by the same issue.

**Comment by Morten242** [comment]
Ah, you're right. I even saw that issue earlier but didn't quite make the connection. Closing.

**Comment by traversaro** [comment]
I think it would be useful to have this issue open until the issue is solved for the `fmt` port in particular.

**Comment by ras0219-msft** [comment]
Yes, these sorts of GitHub issues are the only way we can track and find problems like this. Thanks for reporting it!
