### ISSUE TITLE
For the needs of vcpkg use

### ISSUE THREAD

**Issue by brinkqiang** [microsoft/vcpkg#27002]
I need a function that can easily get a specific version of a library.
For example: vcpkg vlist boost He can print out all versions of boost in the warehouse for me to choose, which can greatly improve work efficiency.

**Comment by Neumann-A** [comment]
You mean:

https://github.com/microsoft/vcpkg/blob/master/versions/b-/boost.json

Just lookup the corresponding version file.

**Comment by brinkqiang** [comment]
I mean the act of installing a specific version of a library is very common. Is it possible to provide a corresponding command to operate. Instead of me going to do these things manually.

**Comment by Neumann-A** [comment]
> I mean the act of installing a specific version of a library is very common. Is it possible to provide a corresponding command to operate. Instead of me going to do these things manually.

Not in classic mode. You want to use vcpkg in manifest mode if you want to install a specific version.

**Comment by dg0yt** [comment]
This turns into a FAQ. https://github.com/microsoft/vcpkg/discussions/25622.

**Comment by LilyWangLL** [comment]
Closed as duplicate of https://github.com/microsoft/vcpkg/discussions/25622.
