### ISSUE TITLE
cpr[core]:x64-windows Need functionality from cpr 1.9.2

### ISSUE THREAD

**Issue by lightheart33** [microsoft/vcpkg#27005]
****

**Is your feature request related to a problem? Please describe.**
The current version of cpr[core]:x64-windows in vcpkg is 1.3.0, I need functionality from cpr version 1.9.2.
cpr                  1.3.0-8          C++ Requests is a simple wrapper around libcurl inspired by the excellent Pyth...

**Proposed solution**
Update vcpkg of cpr to version 1.9.2.

**Describe alternatives you've considered**
If the version of cpr is not updated in vcpkg, I am forced to use NuGet Package which already is 1.9.2.

**Additional context**
Thank you for considering. M

**Comment by MonicaLiu0311** [comment]
Thanks for your PR. The current version of cpr is 1.9.2. You only need to update vcpkg to the latest version. 

The relevant PR is: https://github.com/microsoft/vcpkg/pull/26689

You can browse the [update process of the cpr](https://github.com/microsoft/vcpkg/blob/master/versions/c-/cpr.json) version here.
