### ISSUE TITLE
Building Boost for ARM iOS simulator builds for iPhone

### ISSUE THREAD

**Issue by Stannieman** [microsoft/vcpkg#27016]
**Describe the bug**
When building Boost for the ARM iOS simulator it still builds for iPhone.

**Environment**
- OS: macOS Monterey (12.6)
- Compiler: Apple Clang 13.1.6

**To Reproduce**
1. Create a custom triplet that looks like this
```
set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME iOS)
set(VCPKG_OSX_SYSROOT iphonesimulator)
```
2. Install Boost in your project.
3. The Boost static libs are built for iphoneos.
4. The Boost libs cannot be linked with your own lib because Boost is built for iphoneos and your code is built for iphonesimulator.

**Expected behavior**
The Boost static libs are built for iphonesimulator and linking works.

**Failure logs**
`ld: in /somethingSomething/build/ios-simulator-arm64-debug/vcpkg_installed/arm64-iossimulator13.7/debug/lib/libboost_thread.a(thread.o), building for iOS Simulator, but linking in object file built for iOS`

**Additional context**
Other libs build correctly for the ARM64 simulator so I think the triplet is correct.
I suspect that VCPKG_OSX_SYSROOT is not passed to b2 or that b2 ignores it.
Unfortunately I have zero experience with b2 so I hope someone is able to give some hints.

**Comment by MonicaLiu0311** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
