### ISSUE TITLE
[zlib] Build error

### ISSUE THREAD

**Issue by 291598912** [microsoft/vcpkg#27019]
PS D:\workspace\project\thirdparty\vcpkg> ./vcpkg install curl:x64-windows
Computing installation plan...
The following packages will be built and installed:
    curl[core,non-http,schannel,ssl,sspi]:x64-windows -> 7.83.1#2
  * zlib[core]:x64-windows -> 1.2.12#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\58497\AppData\Local\vcpkg\archives in 153.8 us. Use --debug to see more details.
Installing 1/2 zlib:x64-windows...
Building zlib[core]:x64-windows...
-- Using cached madler-zlib-v1.2.12.tar.gz.
-- Extracting source D:/workspace/project/thirdparty/vcpkg/downloads/madler-zlib-v1.2.12.tar.gz
CMake Error at scripts/cmake/vcpkg_extract_source_archive.cmake:227 (message):
  Could not unwrap top level directory from archive.  Pass
  NO_REMOVE_ONE_LEVEL to disable this.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:32 (vcpkg_extract_source_archive)
  scripts/cmake/vcpkg_from_github.cmake:189 (vcpkg_extract_source_archive_ex)
  ports/zlib/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:146 (include)

error: building zlib:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+zlib
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[zlib]+Build+error
Include '[zlib] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: 314018fef 2022-05-20 (4 months ago)

**Comment by Thomas1664** [comment]
> Please ensure you're using the latest port files with git pull and vcpkg update.

You're using an old version of vcpkg:

> vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
vcpkg-scripts version: https://github.com/microsoft/vcpkg/commit/314018fef43c7e3a52a3e46599313b70ace3977a 2022-05-20 (4 months ago)

Please run `git pull` and `bootstrap-vcpkg.bat` to update vcpkg and try again.

**Comment by LilyWangLL** [comment]
Ping @291598912 for response. Does this issue still exist on latest vcpkg?

**Comment by 291598912** [comment]
ok

**Comment by LilyWangLL** [comment]
> ok

Does this issue still exist?

**Comment by 291598912** [comment]
According to your plan, thank you

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
