### ISSUE TITLE
[New Port Request] Polygon Mesh Processing Library

### ISSUE THREAD

**Issue by Nosenzor** [microsoft/vcpkg#27010]
Library name: Polygon Mesh Processing Library

Library description:
The Polygon Mesh Processing Library is a modern C++ open-source library for processing and visualizing polygon surface meshes. Its main features are:

An efficient and easy-to-use mesh data structure
Standard algorithms such as decimation, remeshing, subdivision, or smoothing
Ready-to-use visualization tools
Seamless cross-compilation to JavaScript ([demo](https://www.pmp-library.org/mpview.html))

Source repository URL: https://github.com/pmp-library/pmp-library.git

Project homepage (if different from the source repository): https://www.pmp-library.org

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
