### ISSUE TITLE
How do I solve this

### ISSUE THREAD

**Issue by SidertheDoor** [microsoft/vcpkg#27029]
Currently I just started learning C++ and when I tried using visual studio 2022 to return a simple function it gave me this,
1>------ Build started: Project: C++ Primer Chapter 1.1, Configuration: Debug|Win32 ------
1>  main.cpp
1>C:\Users\Sider4life\source\repos\C++ Primer Chapter 1.1\C++ Primer Chapter 1.1\LINK : fatal error LNK1104: cannot open file 'ucrtd.lib'
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
I checked C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\ucrt\x64\ where its supposed to be and it is there, I have no idea what to do about this and would appreciate some help. Been a few years since I used 2019 for C so maybe i missed something in the installation any ideas are welcome.

**Comment by Cheney-W** [comment]
This issue is a Visual Studio issue instead of a vcpkg issue. 

Please submit an issue on https://developercommunity.visualstudio.com/
