### ISSUE TITLE
[New Port Request] SimpleAmqpClient

### ISSUE THREAD

**Issue by CayOest** [microsoft/vcpkg#27027]
Library name: SimpleAmqpClient

Library description: [SimpleAmqpClient](https://github.com/alanxz/SimpleAmqpClient) is an easy-to-use C++ wrapper around the [rabbitmq-c](https://github.com/alanxz/rabbitmq-c) C library. It derives inspiration from the [puka](http://majek.github.com/puka/puka.html) AMQP library in that it abstracts away the underlying AMQP wire concept of channels and uses them as an error/consumer scope. This should make writing simple single-threaded AMQP-enabled apps easy.

Source repository URL: https://github.com/alanxz/SimpleAmqpClient

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
