### ISSUE TITLE
[New Port Request] <open3D>

### ISSUE THREAD

**Issue by wyyw123** [microsoft/vcpkg#27032]
Library name:
open3D
Library description:
Open3D is an open-source library that supports rapid development of software that deals with 3D data. The Open3D frontend exposes a set of carefully selected data structures and algorithms in both C++ and Python. The backend is highly optimized and is set up for parallelization. We welcome contributions from the open-source community.
Source repository URL:
git clone https://github.com/isl-org/Open3D
Project homepage (if different from the source repository):
http://www.open3d.org/
Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by wawatt** [comment]
up
