### ISSUE TITLE
[New Port Request] <etcd-cpp-apiv3>

### ISSUE THREAD

**Issue by sdeastis** [microsoft/vcpkg#27039]
Library name: etcd-cpp-apiv3

Library description: The etcd-cpp-apiv3 is a C++ API for etcd's v3 client API, i.e., ETCDCTL_API=3.

Source repository URL:  https://github.com/etcd-cpp-apiv3

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by sighingnow** [comment]
See also existing effort from https://github.com/microsoft/vcpkg/pull/15373 and https://github.com/microsoft/vcpkg/pull/18921.

**Comment by sighingnow** [comment]
See also: https://github.com/microsoft/vcpkg/pull/29363

**Comment by JonLiu1993** [comment]
Fixed by PR #29363
