### ISSUE TITLE
Installation of boost fails if one module fails

### ISSUE THREAD

**Issue by katrasnikj** [Microsoft/vcpkg#2703]
When installing the complete boost package one module (atlmfc) fails. Consequently the installation of all remaining boost modules is stopped. I think it would be better to continue installation of the remaining modules and notify the user about the failed modules at the end of the installation.

**Comment by MikeGitb** [comment]
Sounds reasonable - More general, if one of multiple package installation fails only the dependent ones should be cancelled. With respect ot boost however, please note that there are quite a lot of dependencies between the modules, so depending on which module failed, you might still cancel most of the other modules.

**Comment by ras0219-msft** [comment]
Thanks for the suggestion! This is currently available by passing the `--keep-going` flag to install.

I'll look at improving the docs around this!

**Comment by MikeGitb** [comment]
> I'll look at improving the docs around this!

Well, `vcpkg help install` would have told me, if I'd just checked (seems obvious in hindsight) :(

One idea would be to mention this flag as part of the error message (assuming this is not already the case of course).

**Comment by katrasnikj** [comment]
Thank you very much for the information. I should have looked more closely at documentation.
