### ISSUE TITLE
print usage

### ISSUE THREAD

**Issue by amrezaee** [microsoft/vcpkg#27040]
Hi
Why --no-print-usage option is not available in manifest mode?
It's a useful option for suppressing usage instruction each time.

**Comment by demianmnave-pti** [comment]
I am in the process of submitting a pull request to implement this exact feature.

https://github.com/microsoft/vcpkg-tool/pull/721

**Comment by Cheney-W** [comment]
Waiting https://github.com/microsoft/vcpkg/pull/27209 merged.

**Comment by BillyONeal** [comment]
Fixed :)

**Comment by Zingam** [comment]
Now I see not print usage by default. Was this option enabled by default?

**Comment by BillyONeal** [comment]
> Now I see not print usage by default. Was this option enabled by default?

Do you have a repro? This sounds like an issue submission rather than a change for this PR.

**Comment by Zingam** [comment]
I'll see if I can report a repro. I have VSCode project with CMake presets. Before the current release I was complaining about seeing the find_package info but qfter the upgrade they disappeared completely.
