### ISSUE TITLE
`vcpkg install boost:x64-windows` does not install the pdb files

### ISSUE THREAD

**Issue by hkaiser** [Microsoft/vcpkg#2705]
Also `vcpkg export boost:x64-windows` does not add the pdb files to the generated archive, which is probably related. 

All of this happens for non-static builds, thus in the end the generated dll's miss their pdb files.

**Comment by alexkaratarakis** [comment]
Should be fixed in 09334981885478b8b9642755d981481dbd832c30. 
Thanks for reporting!

**Comment by hkaiser** [comment]
Thanks again!
