### ISSUE TITLE
[boost-vcpkg-helpers] Has inconsistent copyright info

### ISSUE THREAD

**Issue by horenmar** [microsoft/vcpkg#27067]
The `boost-vcpkg-helpers` license declaration is inconsistent. The [portfile downloads BSL copyright notice](https://github.com/microsoft/vcpkg/blob/5f144173006dbeea7b9cb017775675606666a207/ports/boost-vcpkg-helpers/portfile.cmake#L11-L15) but the [vcpkg.json](https://github.com/microsoft/vcpkg/blob/5f144173006dbeea7b9cb017775675606666a207/ports/boost-vcpkg-helpers/vcpkg.json#L5) declares MIT license.

**Proposed solution**
Make them consistent. I don't know which license is correct though.

**Comment by horenmar** [comment]
I would expect it to then install MIT `copyright` file into its own folder then.

**Comment by JackBoosY** [comment]
The license should be `BSL-1.0`.

**Comment by Neumann-A** [comment]
> The license should be BSL-1.0.

@JackBoosY: why? This is a script helper port and has nothing to do with boost....  Did you only look at the downloaded license?

**Comment by JackBoosY** [comment]
> > The license should be BSL-1.0.
> 
> @JackBoosY: why? This is a script helper port and has nothing to do with boost.... Did you only look at the downloaded license?

Reasonable. That's just a helper, the author is us, not boost.

**Comment by MonicaLiu0311** [comment]
@horenmar 
This is a script helper port and has nothing to do with boost, can this issue be closed?

**Comment by LilyWangLL** [comment]
I submitted PR #28617 to fix this issue, I copy the [MIT license file](https://github.com/microsoft/vcpkg/blob/master/LICENSE.txt) in vcpkg to _[VCPKG_ROOT]/ports/boost-vcpkg-helpers_. Also modify the `boost-modular-headers.cmake` to make other boost ports still use boost licnese.

**Comment by horenmar** [comment]
Great, thanks.
