### ISSUE TITLE
curl fails to compile static due to nghttp2

### ISSUE THREAD

**Issue by dgsantana** [Microsoft/vcpkg#2706]
When trying to compile Curl for windos-static, it fails due to nghttp2, which doesn't seem to easily support static linking. Although the Curl portfile, only requires nghttp2 for dynamic linking.
The failure is due to the CONTROL package dependencies, that are built before hand, there should be probably some flag/symbol (i.e. @) to control which are the required static and dynamic dependencies in the CONTROL file to avoid this. 
*Example*
Source: curl
Version: 7.58.0-1
Build-Depends: zlib, openssl, libssh2, @nghttp2
Description: A library for transferring data with URLs

**Comment by pravic** [comment]
Introduced in #2671. However this breaks the current state of libraries which use curl under `windows-static` triplets.

@ras0219-msft @alexkaratarakis Please take a look. May be it is better to remove nghttp2 dependency from curl for now.

**Comment by ras0219-msft** [comment]
I've instead opted to add support for static builds to nghttp2 :). This should work in the latest master (it does for me)!

**Comment by pravic** [comment]
Thanks!
