### ISSUE TITLE
libigl build failure

### ISSUE THREAD

**Issue by Nosenzor** [microsoft/vcpkg#27084]
**Host Environment**

- OS: [MacOs 12.6.]
- Compiler: Apple clang version 14.0.0 (clang-1400.0.29.102)
- MacBook Pro M2 (ARM)

**To Reproduce**

`./vcpkg install libigl`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- -- Running vcpkg install
Error: libigl:arm64-osx@2.3.0#2 is only supported on '!(arm | uwp)'

-- Running vcpkg install - failed

- Attach ***every failure log file*** mentioned in the console output.

Error: libigl:arm64-osx@2.3.0#2 is only supported on '!(arm | uwp)'

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Nosenzor** [comment]
Note : I'm ableto build and run the lib on Mac arm so it should be ok to enable it on vcpkg

**Comment by Cheney-W** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
