### ISSUE TITLE
Detect mismatched compiler when consuming an installed package

### ISSUE THREAD

**Issue by BrennanConroy** [microsoft/vcpkg#27090]
****

**Is your feature request related to a problem? Please describe.**
Recently I thought I found a bug in the STL. But it turns out the issue was due to a mismatch in the compiler used for a dependency I installed via vcpkg and the compiler used by my project.

I installed a dependency via the command line (which I later found out was finding and using the VS2019), then consumed the dependency in a project that I was building in VS2022.

**Proposed solution**
Consuming dependencies from CMake requires using the `find_package` helper. It seems like this should be able to do a compiler check and fail/warn when a different compiler version is detected. And potentially provide help on how to fix it (e.g. change path to VS used by vcpkg)

**Describe alternatives you've considered**
Try to figure out our own detection mechanism.

**Additional context**

**Comment by Osyotr** [comment]
Use manifest mode.

**Comment by Cheney-W** [comment]
Please try the following: 
Open `.\vcpkg\triplets\x64-windows.cmake` file(Modify which triplet you install)，add `set(VCPKG_DISABLE_COMPILER_TRACKING ON)` and reinstall the port you used.

**Comment by dg0yt** [comment]
> Open `.\vcpkg\triplets\x64-windows.cmake` file(Modify which triplet you install)，add `set(VCPKG_DISABLE_COMPILER_TRACKING ON)` and reinstall the port you used.

This will disable compiler tracking for vpckg ABI versioning. This will lead into installed ports facing the same ABI issues that the OP report for consuming an external dependency.

**Comment by Cheney-W** [comment]
Thanks for dg0yt's comment. You are right. It really can't solve the problem.
The compiler version used to build the dependency should be consistent with the compiler version used in the current project.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
