### ISSUE TITLE
Add VCPKG_OBJC_FLAGS and VCPKG_OBJCXX_FLAGS

### ISSUE THREAD

**Issue by DSMitten** [microsoft/vcpkg#27099]
****

**Is your feature request related to a problem? Please describe.**
If a MacOS cmake project uses the GTest port, and sets CMAKE_CXX_VISIBILITY_PRESET and CMAKE_OBJCXX_VISIBILITY_PRESET to hidden, linker warnings are encountered when building tests due to inconsistent visibility (GTest is built with default visibility and the product and tests are built with hidden visibility), such as:

```
ld: warning: direct access in function 'testing::internal::SuiteApiResolver<testing::Test>::GetSetUpCaseOrSuite(char const*, int)' from file 'test-file.cpp.o' to global weak symbol 'testing::Test::SetUpTestSuite()' from file '...path/x64-osx/debug/lib/libgtest.a(gtest-all.cc.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
```

This can be fixed by building GTest with the -fvisibility=hidden compiler option, but this is only possible for C++, not Objective-C++:

```cmake
# Works - no more linker warnings for C++ tests
set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} -fvisibility=hidden -fvisibility-inlines-hidden")
# Does not work - OBJCXX doesn't have any equivalent variable
set(VCPKG_OBJCXX_FLAGS "${VCPKG_OBJCXX_FLAGS} -fvisibility=hidden -fvisibility-inlines-hidden")
```

With the above custom triplet, I now only get linker warnings for objective-c files:
```
ld: warning: direct access in function 'testing::internal::SuiteApiResolver<testing::internal::(anonymous namespace)::FailureTest>::GetSetUpCaseOrSuite(char const*, int)' from file '...path/x64-osx/debug/lib/libgtest.a(gtest-all.cc.o)' to global weak symbol 'testing::Test::SetUpTestSuite()' from file 'testfile.mm.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
```
**Proposed solution**
Provide variables VCPKG_OBJC_FLAGS and VCPKG_OBJCXX_FLAGS allowing a custom triplet to set compiler flags for objective-c files

**Describe alternatives you've considered**
Allow a triplet to set a variable that will be passed through to the port (such as `gtest_hide_internal_symbols`\)

**Additional context**

**Comment by Neumann-A** [comment]
can you not use `VCPKG_CMAKE_CONFIGURE_OPTIONS` to pass the correct option to gtest?

**Comment by DSMitten** [comment]
Ive tried. Perhaps I made an error, but it doesn't work:
```cmake
set(VCPKG_CMAKE_CONFIGURE_OPTIONS
    -Dgtest_hide_internal_symbols=TRUE
)
```

The docs for this property say hardly anything, so I'm not sure how to correctly set it.

**Comment by Neumann-A** [comment]
> Ive tried. Perhaps I made an error, but it doesn't work:

Where did you set it? This needs to be set in the triplet.

**Comment by DSMitten** [comment]
Yes, we have a custom triplet x64-osx.cmake. Setting that option didn't change anything, so I just set VCPKG_C_FLAGS to pass -fvisibility=hidden and that works.

Now I'm trying to get it to build with libstdc++, which requires the command-line option of `-stdlib=libstdc++`
I can pass that for C++ files but not objective-C files, and mixing standard libraries in a project is probably a bad idea, so I'm stuck at the moment.

**Comment by Neumann-A** [comment]
> Setting that option didn't change anything

Check if it is passed in the config-xxx.log of gtest. 

>  custom triplet x64-osx.cmake
> I can pass that for C++ files but not objective-C files, and mixing standard libraries in a project is probably a bad idea, so I'm stuck at the moment.

Use a custom cmake toolchain? Or are you already doing that?
