### ISSUE TITLE
[ffmpeg] Enable libmfx for Intel Media SDK and oneVPL

### ISSUE THREAD

**Issue by js333031** [microsoft/vcpkg#27119]
****

**Is your feature request related to a problem? Please describe.**
The feature enable the use of hardware media decoder/encoder in Intel integrated GPUs and discreet GPUs

**Comment by FrankXie05** [comment]
@js333031 Thanks for posting this issue. Sorry, `vcpkg` currently has no `MediaSDK`, we should add it first and then consider the issue of supporting ffmpeg. 🧐 https://github.com/microsoft/vcpkg/issues/14342

**Comment by Sibras** [comment]
ffmpeg, currently supports Intel QSV using libmfx-dispatch. Its slightly older but can be enabled using ffmpeg[qsv]

**Comment by FrankXie05** [comment]
@Sibras FIxed by PR https://github.com/microsoft/vcpkg/pull/28263
