### ISSUE TITLE
[zlib] build failure

### ISSUE THREAD

**Issue by seanofw** [microsoft/vcpkg#27111]
**Host Environment**

- OS: Windows 10.0.19044.2006
- Compiler: Visual Studio 2022 64-bit v17.0.4
- Vcpkg `2022-09-20-522aa94e9d261c7d7b2f079bf2591ca62df5c714` (fresh install a half hour ago, and this computer has never had vcpkg installed before)

**To Reproduce**

`vcpkg install zlib:x64-windows`

**Failure logs**

```
Computing installation plan...
The following packages will be built and installed:
    zlib[core]:x64-windows -> 1.2.12#2
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\seanw\AppData\Local\vcpkg\archives in 465 us. Use --debug to see more details.
Installing 1/1 zlib:x64-windows...
Building zlib[core]:x64-windows...
-- Downloading https://github.com/madler/zlib/archive/v1.2.12.tar.gz -> madler-zlib-v1.2.12.tar.gz...

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: The system cannot find the file specified
      If you use a proxy, please check your proxy setting.

...

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:273 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/zlib/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:147 (include)

error: building zlib:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+zlib
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[zlib]+Build+error
Include '[zlib] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-09-20-522aa94e9d261c7d7b2f079bf2591ca62df5c714
    vcpkg-scripts version: fe5757109 2022-10-05 (54 minutes ago)
```
This computer has a direct connection to the Internet; there is no proxy.  I elided the proxy suggestions from the console messages above, since they're not relevant to the issue.

There do not appear to be any log files mentioned in the console output.  I'd be happy to attach some additional file if it exists somewhere.

**Additional context**

```
z:\prog\vcpkg>git pull
Already up to date.

z:\prog\vcpkg>vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
```

I was actually attempting to install `rocksdb:x64-windows`, but when I noticed it failed on zlib, I tried installing that directly.  I can successfully use `wget https://github.com/madler/zlib/archive/v1.2.12.tar.gz` to retrieve the file, so I'm not really sure what this is complaining about.

I've spent several decades programming in a variety of languages and on a variety of OSes, but this is my first time using `vcpkg`.  I followed the instructions to `git clone` it and then ran its bootstrap script, but maybe there's something else that needs to be done beyond those two steps to actually use it?

**Comment by Neumann-A** [comment]
> but maybe there's something else that needs to be done beyond those two steps to actually use it?

No there is not.

>  I'm not really sure what this is complaining about.

It couldn't download the file for some reason. Is your firewall blocking vcpkg to download stuff?

> wget https://github.com/madler/zlib/archive/v1.2.12.tar.gz  to retrieve the file

there should be a download folder in you vcpkg folder. You can rename the downloaded file to `madler-zlib-v1.2.12.tar.gz` and move it there. This is more of a hack than a solution since you would have to do it with every download.

**Comment by seanofw** [comment]
> When I open this file there don't have "#" before "PREFER_NINJA",

When I open this file, there is no `PREFER_NINJA` at all, so there's nothing to comment out:

```
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DSKIP_INSTALL_FILES=ON
        -DSKIP_BUILD_EXAMPLES=ON
    OPTIONS_DEBUG
        -DSKIP_INSTALL_HEADERS=ON
)
```

> It couldn't download the file for some reason. Is your firewall blocking vcpkg to download stuff?

When I was trying to use vcpkg to install `rocksdb`, it successfully downloaded three packages before it (7zip, CMake, and PowerShell, respectively), but it bombs every time on zlib.

Per your suggestion, I dropped the tarball into the folder and renamed it.  I ran vcpkg again, and it got a little farther through the process and then bombed out while trying to download `mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst`.  I don't have or use a proxy; and my firewall is just the standard Windows 10 firewall, with no fancy rules added.

Is vcpkg using anything other than normal HTTP(S) requests on ports 80 and 443 to download?  Does it use unusual techniques to download things?  Is there a guide somewhere for "How to configure your firewall for vcpkg"?

**Comment by tbthek** [comment]
I think that is not you firewall's problem, in period of time , I use `git pull`, but it's always show 443 or other erros, and I changed another network service, ran `git pull` again , it ran sucessful.

**Comment by seanofw** [comment]
> I think that is not you firewall's problem, in period of time

I don't think it's a timing issue.  The behavior is very consistent:  vcpkg can't download most files, but every other tool can, regardless of when I try it.

**Comment by tbthek** [comment]
Hey guy, I don't say it is a timing issue, I solved this problem by change my network servicer. But why vcpkg didn't work? I can't understand.

**Comment by seanofw** [comment]
Network-service-wise, my internal network is on a direct fiber-optic line into a major backbone provider at 100 Gb/s.  It's one of the best Internet connections you can get anywhere.  I highly doubt networking is the root cause of this, since _only_ vcpkg seems to be having trouble connecting:  Other devices on the network, and other software on the same computer, can both connect to everything just fine.

**Comment by Osyotr** [comment]
> Failed to download file with error: The system cannot find the file specified

This does not look like regular "check your internet connection" error. Could you run this command in terminal?
https://github.com/microsoft/vcpkg/blob/e2667a41fc2fc578474e9521d7eb90b769569c83/scripts/cmake/vcpkg_download_distfile.cmake#L258-L264

**Comment by JackBoosY** [comment]
> I elided the proxy suggestions from the console messages above, since they're not relevant to the issue.

I don't think so.
If the proxy information you set is displayed, it proves that vcpkg uses this proxy to download these packages.

**Comment by seanofw** [comment]
@JackBoosY  I'm going to reiterate: _I don't have a proxy and I never have had a proxy._  This is a direct connection to the Internet on a high-speed fiber-optic line.

Here is the _complete_ output from vcpkg, including the previously-omitted proxy-related/fiddler-related boilerplate text:
```
>vcpkg install zlib:x64-windows
Computing installation plan...
The following packages will be built and installed:
    zlib[core]:x64-windows -> 1.2.12#2
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\seanw\AppData\Local\vcpkg\archives in 256 us. Use --debug to see more details.
Installing 1/1 zlib:x64-windows...
Building zlib[core]:x64-windows...
-- Downloading https://github.com/madler/zlib/archive/v1.2.12.tar.gz -> madler-zlib-v1.2.12.tar.gz...

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: The system cannot find the file specified
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. Your proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:273 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/zlib/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:147 (include)


error: building zlib:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+zlib
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[zlib]+Build+error
Include '[zlib] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-09-20-522aa94e9d261c7d7b2f079bf2591ca62df5c714
    vcpkg-scripts version: fe5757109 2022-10-05 (4 days ago)


Please use the prefilled template from Z:\Dropbox\prog\vcpkg\installed\vcpkg\issue_body.md when reporting your issue.
```

**Comment by seanofw** [comment]
@Osyotr wrote:

> Could you run this command in terminal?

I'd be happy to, but you'll have to fill in the missing variables in it:  I don't know your tooling well enough to know what would be used for them, and that command obviously won't run without those variables:

cmd.exe:
```
>COMMAND "$ENV{VCPKG_COMMAND}" x-download "${downloaded_file_path}" ${sha512_param} ${urls_param} ${headers_param} --debug --feature-flags=-manifests
'COMMAND' is not recognized as an internal or external command,
operable program or batch file.
```
and PowerShell's response:
```
> COMMAND "$ENV{VCPKG_COMMAND}" x-download "${downloaded_file_path}" ${sha512_param} ${urls_param} ${headers_param} --debug --feature-flags=-manifests
COMMAND : The term '{VCPKG_COMMAND}' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ COMMAND "$ENV{VCPKG_COMMAND}" x-download "${downloaded_file_path}" ${ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: ({VCPKG_COMMAND}:String) [Get-Command], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand
```

**Comment by Osyotr** [comment]
Add `message("\"$ENV{VCPKG_COMMAND}\" x-download \"${downloaded_file_path}\" ${sha512_param} ${urls_param} ${headers_param} --debug --feature-flags=-manifests"` before `vcpkg_execute_in_download_mode` call I linked above and you will see the command.

**Comment by seanofw** [comment]
The only thing worse than failing software is _working_ software.

So I added `message("\"$ENV{VCPKG_COMMAND}\" x-download \"${downloaded_file_path}\" ${sha512_param} ${urls_param} ${headers_param} --debug --feature-flags=-manifests"` before `vcpkg_execute_in_download_mode`.

It printed out this —
```
-- Downloading https://github.com/madler/zlib/archive/v1.2.12.tar.gz -> madler-zlib-v1.2.12.tar.gz...
"Z:/Dropbox/prog/vcpkg/vcpkg.exe" x-download "Z:/Dropbox/prog/vcpkg/downloads/madler-zlib-v1.2.12.tar.gz" --sha512=5b029532a9f5f12ad425c12eccdf1b77c8d91801342c5b5e26ffb539f76a204e6c4882b40f0130f143f2cd38df90e90af2978cf4bb997e1fa3a0d1eff2ca979e --url=https://github.com/madler/zlib/archive/v1.2.12.tar.gz  --debug --feature-flags=-manifests
```
— _and then the download worked_.  I've changed nothing other than adding that one line (with the missing `)` at the end).  It's been failing for days, consistently, but adding that print statement somehow caused it to work.

And now it's _still_ working, and I don't know why.  To be absolutely certain, I completely deleted the entire `vcpkg\` directory and `C:\Users\seanw\AppData\local\vcpkg` directory, and then ran through `git clone` and bootstrap, and _now it's working_.

Are there any other artifacts that vcpkg leaves behind anywhere else on the system?  Any registry changes it or its tooling might make?  It's great that it's working, but I'd really like to know _why_ it wasn't working before, because there's probably still a download bug in it that's now being somehow hidden by whatever configuration change just happened.

**Comment by FrankXie05** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by hebercosfer** [comment]
On ZLib.net there's this message: Due to the first bug fix, any installations of 1.2.12 or earlier should be replaced with 1.2.13.

The link VCPKG is trying to reach is not available anymore. That should be an easy fix, no?

**Comment by Rrubidium** [comment]
I encountered the same problem. I found that the issue might be caused by your vcpkg directory path being too long or containing special characters like Chinese characters, which led to errors. Moving it to another directory solved the problem.

**Comment by aiyolo** [comment]
So, what's the solution to this issue?
