### ISSUE TITLE
[pkgconf] Build error on ubuntu 18.04 with python 3.6

### ISSUE THREAD

**Issue by jpfeuffer** [microsoft/vcpkg#27117]
Package: pkgconf[core]:x64-linux -> 1.8.0#3

**Host Environment**

- Host: x64-linux
- Compiler: GNU 7.5.0
-    vcpkg-tool version: 2022-09-20-522aa94e9d261c7d7b2f079bf2591ca62df5c714
    vcpkg-scripts version: fe5757109 2022-10-05 (15 hours ago)

**To Reproduce**

`vcpkg install `

**Failure logs**

```
-- Downloading https://github.com/pkgconf/pkgconf/archive/cef30268e1a3f79efd607c26abcf556aa314c9c4.tar.gz -> pkgconf-pkgconf-cef30268e1a3f79efd607c26abcf556aa314c9c4.tar.gz...
-- Extracting source /workspace/vcpkg/downloads/pkgconf-pkgconf-cef30268e1a3f79efd607c26abcf556aa314c9c4.tar.gz
-- Using source at /workspace/vcpkg/buildtrees/pkgconf/src/6aa314c9c4-8bd74a463d.clean
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: /usr/bin/python3 /workspace/OpenMS/build-vc/vcpkg_installed/x64-linux/tools/meson/meson.py -Dtests=false --buildtype plain --backend ninja --wrap-mode nodownload --native /workspace/vcpkg/buildtrees/pkgconf/meson-native-x64-linux.log --default-library static --libdir lib --native /workspace/vcpkg/buildtrees/pkgconf/meson-native-x64-linux-debug.log -Ddebug=true --prefix /workspace/vcpkg/packages/pkgconf_x64-linux/debug --includedir ../include -Dcmake_prefix_path=['/workspace/OpenMS/build-vc/vcpkg_installed/x64-linux/debug','/workspace/OpenMS/build-vc/vcpkg_installed/x64-linux'] /workspace/vcpkg/buildtrees/pkgconf/src/6aa314c9c4-8bd74a463d.clean
    Working Directory: /workspace/vcpkg/buildtrees/pkgconf/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /workspace/vcpkg/buildtrees/pkgconf/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:460 (vcpkg_execute_required_process)
  ports/pkgconf/portfile.cmake:9 (vcpkg_configure_meson)
  scripts/ports.cmake:147 (include)



```
<details><summary>/workspace/vcpkg/buildtrees/pkgconf/config-x64-linux-dbg-err.log</summary>

```
Traceback (most recent call last):
  File "/workspace/OpenMS/build-vc/vcpkg_installed/x64-linux/tools/meson/meson.py", line 26, in <module>
    from mesonbuild import mesonmain
  File "/workspace/OpenMS/build-vc/vcpkg_installed/x64-linux/tools/meson/mesonbuild/mesonmain.py", line 28, in <module>
    from . import mesonlib
  File "/workspace/OpenMS/build-vc/vcpkg_installed/x64-linux/tools/meson/mesonbuild/mesonlib/__init__.py", line 21, in <module>
    from .universal import *
  File "/workspace/OpenMS/build-vc/vcpkg_installed/x64-linux/tools/meson/mesonbuild/mesonlib/universal.py", line 17
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```
</details>
**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "name": "openms",
  "version-string": "3.0.0",
  "dependencies": [
    "zlib",
    "bzip2",
    "eigen3",
    "boost-core",
    "boost-math",
    "boost-regex",
    "boost-iostreams",
    "qt5-base",
    "qt5-svg",
    {
      "name": "qt5-webengine",
      "platform": "!static"
    },
    "clp",
    "cgl",
    "coinutils",
    "sqlite3",
    "libsvm"
  ]
}

```
</details>

**Comment by jpfeuffer** [comment]
Looks like the python version is not recent enough but this is my first time using vcpkg and I feel like this should be handled by your build tool and an appropriate error should be shown.

**Comment by eli-schwartz** [comment]
Dunno, I'm a Meson dev not a vcpkg one.  :)

**Comment by jpfeuffer** [comment]
Ah okay :) Then let's wait for some vcpkg input, maybe they need to update some "requirements" for meson. I can try to set up a newer python meanwhile but will have to rebuild the whole image.

**Comment by Neumann-A** [comment]
> How did vcpkg install Meson?

it just downloads from github and puts everything into a folder. Wouldn't consider this a "installation"

vcpkg uses `vcpkg_find_acquire_program` to get the python3 binary but this is just a glorified `find_program` of cmake on !windows (on windows it downloads 3.10).
I could add a python3 version check into the `vcpkg-tool-meson` port or `vcpkg_find_acquire_program` though.

**Comment by eli-schwartz** [comment]
That would be good -- we always support all non EOL versions of python (but after EOL we *may* bump the version if we find that it helps project development), and that's the only dependency, so the version check is low maintenance.

We *do* support running Meson uninstalled, but that does mean at copy-to-folder time there's nothing to check the python version and loudly complain if requirements aren't met. :)

**Comment by eastman-bechamo** [comment]
I'm having a similar issue on Ubuntu 18.04. My Python version is 3.6.x, and vcpkg is complaining about the future library. Is there anything I can do to remedy this?

**Comment by dg0yt** [comment]
> I'm having a similar issue on Ubuntu 18.04. My Python version is 3.6.x, and vcpkg is complaining about the future library. Is there anything I can do to remedy this?

When you install port python3, this is part of the output:
~~~
The package python3 provides a python interpreter that supports virtual environments:

    $ tools/python3/python3.10 -m venv /path/to/venv
    $ export VIRTUAL_ENV=/path/to/venv
    $ export PATH=/path/to/venv/bin:$PATH
    $ export -n PYTHONHOME
    $ unset PYTHONHOME

    See https://docs.python.org/3/library/venv.html for more details.
~~~

As  a variant, I created a permanent venv as in the first command line, and activate it with an included script before running vcpkg:
~~~
    $ tools/python3/python3.10 -m venv /path/to/venv
    $ . /path/to/venv/bin/activate
~~~

**Comment by eastman-bechamo** [comment]
I'm actually not using the Python3 port in my build

**Comment by dg0yt** [comment]
> I'm actually not using the Python3 port in my build

Building port pkgconf need meson; meson needs python; python in Ubuntu 18.04 is too old. Vcpkg port python3 is good enough.

**Comment by LilyWangLL** [comment]
> Building port pkgconf need meson; meson needs python; python in Ubuntu 18.04 is too old. Vcpkg port python3 is good enough.

I think this issue could be closed as a question, this answer from dg0yt resolved this issue, thanks for everyone's help.
