### ISSUE TITLE
Can't build freeimage.

### ISSUE THREAD

**Issue by ventsin** [Microsoft/vcpkg#2711]
I've been having trouble building freeimage with vcpkg.
Running Windows 10 (latest patch) and pt-br locale.

-- Configuring x86-windows-rel
-- Configuring x86-windows-rel done
-- Configuring x86-windows-dbg
-- Configuring x86-windows-dbg done
-- Build x86-windows-rel
CMake Error at C:/vcpkg/scripts/cmake/vcpkg_build_cmake.cmake:129 (message):
    Command failed: C:/vcpkg/downloads/cmake-3.10.2-win32-x86/bin/cmake.exe;--build;.;--config;Release;--target;install;--;-v;-j1
    Working Directory: C:/vcpkg/buildtrees/freeimage/x86-windows-rel
    See logs for more information:
      C:\vcpkg\buildtrees\freeimage\install-x86-windows-rel-out.log

Call Stack (most recent call first):
  C:/vcpkg/scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  C:/vcpkg/ports/freeimage/portfile.cmake:51 (vcpkg_install_cmake)
  C:/vcpkg/scripts/ports.cmake:72 (include)

Error: Building package freeimage:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: freeimage:x86-windows
  Vcpkg version: 0.0.103-2018-02-01-47265676398778e03ee16bfeb33ef357e8658676

Here's also the log file, it seems to be a linker issue:
[install-x86-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/1687282/install-x86-windows-rel-out.log)

**Comment by ras0219-msft** [comment]
Thanks! I believe this is fixed in master; please pull and run `vcpkg upgrade`, then `vcpkg install freeimage` (the upgrade is needed to update libwebp).
