### ISSUE TITLE
[freexl] Build error

### ISSUE THREAD

**Issue by hotasim** [microsoft/vcpkg#27125]
Package: freexl[core]:x64-linux -> 1.0.6#1

**Host Environment**

- Host: x64-linux
- Compiler: GNU 8.5.0
-    vcpkg-tool version: 2022-09-20-522aa94e9d261c7d7b2f079bf2591ca62df5c714
    vcpkg-scripts version: e2667a41f 2022-10-06 (10 hours ago)

**To Reproduce**

`vcpkg install pdal`

**Failure logs**

```
-- Using cached freexl-1.0.6.tar.gz.
-- Cleaning sources at /home/ec2-user/test_vcpkg/vcpkg/buildtrees/freexl/src/freexl-1-0b9ac2177e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/ec2-user/test_vcpkg/vcpkg/downloads/freexl-1.0.6.tar.gz
-- Applying patch fix-makefiles.patch
-- Applying patch fix-sources.patch
-- Applying patch fix-pc-file.patch
-- Using source at /home/ec2-user/test_vcpkg/vcpkg/buildtrees/freexl/src/freexl-1-0b9ac2177e.clean
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
CMake Error at scripts/cmake/vcpkg_configure_make.cmake:597 (message):
  freexl requires autoconf from the system package manager (example: "sudo
  apt-get install autoconf")
Call Stack (most recent call first):
  ports/freexl/portfile.cmake:18 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)
```

**Comment by dg0yt** [comment]
I read:

> freexl requires autoconf from the system package manager (example: "sudo apt-get install autoconf")

**Comment by autoantwort** [comment]
I always wounder how hard it is to read error messages

**Comment by hotasim** [comment]
Then I executed this.
`sudo yum install autoconf`

`Updating Subscription Management repositories.
Unable to read consumer identity
This system is not registered with an entitlement server. You can use subscription-manager to register.`

It seems that there is still a problem depending on AWS EC2 RHEL8, but it will be a separate issue from here.

Thanks.

**Comment by dg0yt** [comment]
> I always wounder how hard it is to read error messages

With vcpkg, it is harder than necessary. There are too many lines after the message. I insist that there should be a proper way to pass the concise error message from portfile to vcpkg tool. Then, the tool can highlight it for human readers or CI.

**Comment by Cheney-W** [comment]
@hotasim This issue could be fixed by manually install `autoconf` to the Linux machine.

**Comment by hotasim** [comment]
@Cheney-W  
I also installed the following in my environment.
autoconf
automake
libtool
python3.6.8 → 3.8.12

Still no good.
Moved to the next issue. Thank you.
https://github.com/microsoft/vcpkg/issues/27125

**Comment by dg0yt** [comment]
> Still no good.

With freexl (this issue?)

**Comment by hotasim** [comment]
Install autoconf as advised,
freexl itself worked without any problems.

I'm sorry that I omitted the explanation.
