### ISSUE TITLE
Highfive library does not install cmake files

### ISSUE THREAD

**Issue by hkaiser** [Microsoft/vcpkg#2715]
I'd expect for the library to provide something like `highfive-config.cmake` and `highfive-targets.cmake`, but there does not seem to be any of that available.

**Comment by ras0219-msft** [comment]
Fixed in https://github.com/Microsoft/vcpkg/commit/3bb83774a53a36d67789b1ba4a309e6b8d973e53!

It looks like they added those in a more recent version than we had.

**Comment by hkaiser** [comment]
Thanks!
