### ISSUE TITLE
[vcpkg-tool] Don't spread calls to `abort` around the codebase

### ISSUE THREAD

**Issue by Thomas1664** [microsoft/vcpkg#27152]
**Is your feature request related to a problem? Please describe.**

The tool exits almost always if it hits an exceptional state by calling `std::abort`. This happens via calls to `value_or_exit` and alike. There are a few issues with exiting the program: Most importantly, no stack unwinding is done. This will lead to problems, especially in the context of multithreading. Therefore, we can almost never use multithreading and parallel algorithms to make vcpkg faster.

**Proposed solution**

- Replace all calls to `value_or_exit` and alike that are outside a command's `perform_and_exit` either with throwing an exception, `vcpkg::Optional`, or `ExpectedS`/ `ExpectedT`.
- Express in the function name that a function may exit on failure.

**Describe alternatives you've considered**

Don't use multithreading/ parallel algorithms at all. Especially parallel algorithms can lead to massive performance improvements. This way, vcpkg would be a lot slower than it could be.

**Additional context**

https://github.com/microsoft/vcpkg-tool/pull/694#discussion_r982716332

CC: @ras0219-msft

**Comment by autoantwort** [comment]
Do you have an example where vcpkg is to slow currently?

**Comment by Thomas1664** [comment]
> Do you have an example where vcpkg is too slow currently? Edit: Ok I think my computer is too fast. In the PR you mention the command needs 12 seconds, for me the command only needs 900 ms (290ms release) which is fast enough.

I would argue that ~300 ms is still slow if you could get a 2-3x performance improvement with parallel algorithms.

The linked PR only takes baby steps. We might be able to significantly improve performance if we could handle uploads to binary caches in parallel. There might be some post build checks that are worth parallelizing as well.

**Comment by autoantwort** [comment]
> I would argue that ~300 ms is still slow

It is fast enough so that I can press enter and directly enter the next command that I want to execute. But yeah there are slower systems where this is probably not the case.

> We might be able to significantly improve performance if we could handle uploads to binary caches in parallel. 

Yeah I see a value in that. The code don't produces output (only warnings in case of errors) and don't call abort.

**Comment by Thomas1664** [comment]
> Yeah I see a value in that. The code don't produces output (only warnings in case of errors) and don't call abort.

To be clear: we don't call abort directly. It is hidden behind `value_or_exit` and alike. Are you sure that we don't exit during uploading to binary cache? We even exit in some filesystem or json functions

**Comment by autoantwort** [comment]
I know. I have not verified it 100%, but I am pretty sure they are not used there.

**Comment by Neumann-A** [comment]
> The tool exits almost always if it hits an exceptional state by calling std::abort

would installing a signal handler work in this case?
