### ISSUE TITLE
[build error?] error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.

### ISSUE THREAD

**Issue by ksp118** [microsoft/vcpkg#27164]
I installed vcpkg using **_git clone https://github.com/Microsoft/vcpkg.git_** and tried to install sdl2(x64 version) but I got this error message. 

> error: while detecting compiler information:
The log file content at "C:\Users\myname\Documents\DEV\vcpkg\buildtrees\detect_compiler\stdout-x64-windows.log" is:
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/Users/myname/Documents/DEV/vcpkg/buildtrees/detect_compiler/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\myname\Documents\DEV\vcpkg\buildtrees\detect_compiler\config-x64-windows-out.log

> Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:310 (vcpkg_execute_required_process)
  scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:147 (include)

> error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.

and this is the content of my log file
>[1/1] "C:/Users/myname/Documents/DEV/vcpkg/downloads/tools/cmake-3.24.0-windows/cmake-3.24.0-windows-i386/bin/cmake.exe" -E chdir ".." "C:/Users/myname/Documents/DEV/vcpkg/downloads/tools/cmake-3.24.0-windows/cmake-3.24.0-windows-i386/bin/cmake.exe" "C:/Users/myname/Documents/DEV/vcpkg/scripts/detect_compiler" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/Users/myname/Documents/DEV/vcpkg/packages/detect_compiler_x64-windows" "-DCMAKE_MAKE_PROGRAM=C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/myname/Documents/DEV/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v143" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/myname/Documents/DEV/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/Users/myname/Documents/DEV/vcpkg" "-DZ_VCPKG_ROOT_DIR=C:/Users/myname/Documents/DEV/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/Users/myname/Documents/DEV/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF"
FAILED: ../CMakeCache.txt 
"C:/Users/myname/Documents/DEV/vcpkg/downloads/tools/cmake-3.24.0-windows/cmake-3.24.0-windows-i386/bin/cmake.exe" -E chdir ".." "C:/Users/myname/Documents/DEV/vcpkg/downloads/tools/cmake-3.24.0-windows/cmake-3.24.0-windows-i386/bin/cmake.exe" "C:/Users/myname/Documents/DEV/vcpkg/scripts/detect_compiler" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/Users/myname/Documents/DEV/vcpkg/packages/detect_compiler_x64-windows" "-DCMAKE_MAKE_PROGRAM=C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/myname/Documents/DEV/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v143" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/myname/Documents/DEV/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/Users/myname/Documents/DEV/vcpkg" "-DZ_VCPKG_ROOT_DIR=C:/Users/myname/Documents/DEV/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/Users/myname/Documents/DEV/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF"
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.

I found this issue but none of those solutions worked on me. (https://github.com/microsoft/vcpkg/issues/21134)

what I've tried to fix this :

1. reinstall vcpkg
2. reinstall vs2022 after vcpkg deletion

**Comment by FrankXie05** [comment]
@ksp118 Thanks for posting this issue,  please provide the error file: 
`C:\Users\myname\Documents\DEV\vcpkg\buildtrees\detect_compiler\config-x64-windows-out.log`

**Comment by ksp118** [comment]
@FrankXie05 
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/9754601/config-x64-windows-out.log)

**Comment by FrankXie05** [comment]
@ksp118 Could you please clone vcpkg to the root of the disk and try again? :)

**Comment by ksp118** [comment]
@FrankXie05 dang it worked! thank you so much ╰(*°▽°*)╯
