### ISSUE TITLE
[clipp] Integrate C++20 compile fix from project's pull request

### ISSUE THREAD

**Issue by DominikGrabiec** [microsoft/vcpkg#27167]
I've got an issue with the `clipp` library where it does not compile with C++20 and I wanted to submit a pull request for fixing it by using a patch, but on the pull request screen suggested creating an issue to discuss the problem & solution so here I am.

**The Problem**
Currently the `clipp` library does not compile with C++20 (at least on Visual Studio 2022) because it uses deprecated functions. There's an open [pull request](https://github.com/muellan/clipp/pull/54) on the project which fixes this but the project itself hasn;'t been updated in many years. (Note I'm not blaming the project owner or expecting anything). 

**Proposed solution**
The patch in the project's pull request works and I've tested it locally by adding it to the `ports/clipp/` directory and then referencing it from `ports/clipp/portfile.cmake`.

This seems like the most light weight solution since we're not forking the project or anything. However I can see potential issues such as incompatability with older C++ standards and other compilers.

**Question**
So is adding this patch (or some similar patch with more `#ifdef`s) to fix the C++20 build issue something resonable that vcpkg would want to do or is it outside the scope of this project and people should do that manually?

**Comment by Cheney-W** [comment]
Normally, this problem should have been fixed by upstream, but it looks like upstream is not maintained anymore, so I think we can add a patch to vcpkg to fix it.
