### ISSUE TITLE
can not found the ffmpeg in vcpkg.io website

### ISSUE THREAD

**Issue by xiaoyifang** [microsoft/vcpkg#27192]
[**Describe the bug**
https://vcpkg.io/en/packages.html

can not found the ffmpeg package.
and the display result is wrong.

![image](https://user-images.githubusercontent.com/105986/195235106-70dc80da-bb08-46f5-890c-926e949f78dd.png)

**Comment by Adela0814** [comment]
@xiaoyifang Please open an issue to https://github.com/vcpkg/vcpkg.github.io/issues. Thanks.

**Comment by xiaoyifang** [comment]
https://github.com/vcpkg/vcpkg.github.io/issues/85
