### ISSUE TITLE
Binary Caching not recognized by other PCs

### ISSUE THREAD

**Issue by nstrahl** [microsoft/vcpkg#27197]
**Describe the bug**
Binary caching is not recognized when compiling/installing from different machines. I have set up a binary cache on a mapped network drive. When I run my install commands on my first PC, everything works great, including binary caching. When I switch to my other PC, the cached binaries are not restored. I get an output that says:
 Restored 0 packages(s) from G:\mybinarycache ...

Is vcpkg capable of doing this, or is binarycache only intended to work on one machine?
I cloned the latest version of vcpkg onto both of my machines. I also tried pulling the repositories again, but that does not fix this.

**Environment**
- OS: Windows 10
- Compiler: MSVC

**To Reproduce**

1. Clone and bootstrap vcpkg on two different machines
2. Carry out steps 3 and 4 in both machines
3. SET VCPKG_BINARY_SOURCES=files,G:\mybinarycache,readwrite
4. %VCPKG_DIR%\vcpkg.exe install double-conversion:x64-windows --only-binarycaching --debug

**Comment by Neumann-A** [comment]
check/compare `vcpkg_abi_info` for e.g. the zlib port on both pcs. If there is a difference you don't have the same setup on both.

**Comment by nstrahl** [comment]
Ok, everything is the same, except for two lines. That seems to be the problem. One machine runs MSVC 2022 Community, the other one has MSVC 2019 Professional. I had read that ABI compatibility is not an issue in the latest MSVC versions so I tried setting an environment variable with SET VCPKG_DISABLE_COMPILER_TRACKING=false in my batch script but I still get the same error. Is this the right way to use this environment variable? What exactly will it check for?

![image](https://user-images.githubusercontent.com/55232428/195522594-158d8433-77b7-4847-a38e-92d7dfdabc3f.png)

**Comment by autoantwort** [comment]
https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md#vcpkg_disable_compiler_tracking

It is a triplet and not a environment variable. You you have to write and use your own triplet.

**Comment by Neumann-A** [comment]
yeah but the abi of `vcpkg-cmake` is also different so the two pcs don't use the same baseline. Since `vcpkg-cmake` is the base for everything it doesn't even matter to fix the compiler stuff. 

>  I had read that ABI compatibility is not an issue in the latest MSVC

This is only valid for VS 2019 to VS 20222 not the other way around. I don't think vcpkg will consider this however. It only cares about compiler versions.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. You could resolve this issue by set option [`VCPKG_DISABLE_COMPILER_TRACKING`](https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md#vcpkg_disable_compiler_tracking) in triplet file.
