### ISSUE TITLE
how to install ffmpeg universal package on macos?

### ISSUE THREAD

**Issue by xiaoyifang** [microsoft/vcpkg#27190]
how to install ffmpeg universal package on macos?

the ffmpeg seems support the universal build ,but how to achieve this?

**Comment by LilyWangLL** [comment]
You can install it by command `.\vcpkg.exe install ffmpeg:x64-uwp`.

**Comment by xiaoyifang** [comment]
thanks ,this is the command on Windows
what is the corresponding command on Macos?

**Comment by jimwang118** [comment]
The installation command for macos is: .\vcpkg.exe install ffmpeg. You can try to install using command. I think this issue can be closed, if you has new quesion, plase reopen this issue.

**Comment by MonicaLiu0311** [comment]
> thanks ,this is the command on Windows what is the corresponding command on Macos?

Please operate according to the [tutorial](https://github.com/microsoft/vcpkg/blob/master/README.md#quick-start-unix).
