### ISSUE TITLE
[boost-build] Build error

### ISSUE THREAD

**Issue by wang89280** [microsoft/vcpkg#27208]
**Host Environment**

- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**

`./vcpkg install xxxx`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please provide the related error log file.

**Comment by wang89280** [comment]
![image](https://user-images.githubusercontent.com/24508092/195491612-14978852-8682-441a-932f-9eca78c105bb.png)
I just find this folder. Thanks for your help！


The content of the file patch-x64-windows-0-err contains the following: 

Checking patch src/tools/clang-linux.jam...
Applied patch src/tools/clang-linux.jam cleanly.

The content of the file x64-windows.vcpkg_abi_info contains the following: 

0002-fix-get-version.patch 108dd64121413cd2d56ede83507d31532c1688cf10d49a3f10fba16b88956e56
boost-uninstall 7687d1e98eed9b478f9f96b6feb5aea775c67be81abfa59897d356e356fe137f
cmake 3.24.0
features core
portfile.cmake 22f1dfa79d175ca1bf4c4a2a858dd970fcb876f7d2b2177b3e6e116a860b74bb
ports.cmake b4accc7941cb5ff993e1a0434cea6df3e99331137294958437b2b86b7216e2e2
post_build_checks 2
powershell 7.2.6
triplet x64-windows
triplet_abi 4556164a2cd3dd6f4742101eabb46def7e71b6e5856faa88e5d005aac12a803c-c0600b35e024ce0485ed253ef5419f3686f7257cfb58cb6a24febcb600fc4b4c-fb14aaf8509566d1c88308688301a1bdd32ed458
vcpkg.json 543507e36442be193837291c7764fdadc9240e2a99509a88776ebf4bcabeb165
vcpkg_download_distfile 257c2c17449e740e4553a7adc37fdd80e811045957ff1d86f18c142a290b5865
vcpkg_execute_required_process 975eab651b1f156e5550defb3abad898ff8159b57a0e0562d3ac3c959043476d
vcpkg_from_git 0aab20e34e84d52ba4763f009e539bfa8f418c41c918c8cf700156f1a8551a10
vcpkg_from_github b743742296a114ea1b18ae99672e02f142c4eb2bef7f57d36c038bedbfb0502f



The content of the file stdout-x64-windows contains the following: 
-- Downloading https://github.com/boostorg/build/archive/boost-1.80.0.tar.gz -> boostorg-build-boost-1.80.0.tar.gz...
-- Extracting source D:/Git/vcpkg/downloads/boostorg-build-boost-1.80.0.tar.gz
-- Applying patch 0002-fix-get-version.patch
-- Using source at D:/Git/vcpkg/buildtrees/boost-build/src/ost-1.80.0-d663e6deff.clean
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.80.0/LICENSE_1_0.txt -> boost_LICENSE_1_0.txt...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.80.0/LICENSE_1_0.txt
[DEBUG] Download failed -- retrying after 1000 ms.
[DEBUG] Download failed -- retrying after 2000 ms.
[DEBUG] Download failed -- retrying after 4000 ms.
Error: Failed to download from mirror set:
https://raw.githubusercontent.com/boostorg/boost/boost-1.80.0/LICENSE_1_0.txt: WinHttpReceiveResponse() failed: 12152
https://raw.githubusercontent.com/boostorg/boost/boost-1.80.0/LICENSE_1_0.txt: WinHttpReceiveResponse() failed: 12152
https://raw.githubusercontent.com/boostorg/boost/boost-1.80.0/LICENSE_1_0.txt: WinHttpReceiveResponse() failed: 12152
https://raw.githubusercontent.com/boostorg/boost/boost-1.80.0/LICENSE_1_0.txt: WinHttpReceiveResponse() failed: 12152

[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(766): 
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 4 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 2322 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 7.096 s (7083899 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. Your proxy's remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:273 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/boost-build/portfile.cmake:19 (vcpkg_download_distfile)
  scripts/ports.cmake:147 (include)

other file is empty!

**Comment by ice0** [comment]
@wang89280 

```
[DEBUG] Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.80.0/LICENSE_1_0.txt
[DEBUG] Download failed -- retrying after 1000 ms.
[DEBUG] Download failed -- retrying after 2000 ms.
[DEBUG] Download failed -- retrying after 4000 ms.
```

It looks like you have a network error. Is this URL accessible if you try to open it from a web browser?

**Comment by LilyWangLL** [comment]
Ping @wang89280 for response.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
