### ISSUE TITLE
STATUS_HEAP_CORRUPTION in OpenSSL built by `vcpkg`

### ISSUE THREAD

**Issue by Diggsey** [microsoft/vcpkg#27207]
**Describe the bug**
https://github.com/sfackler/rust-openssl/issues/1701

**Environment**
- OS: Windows
- Compiler: MSVC 2019 Build Tools

**To Reproduce**
Reproduction code along with other information in linked issue.

I believe this is an issue with `vcpkg` because the issue does not occur when using prebuilt OpenSSL from https://slproweb.com/products/Win32OpenSSL.html

**Comment by Adela0814** [comment]
@Diggsey please provide the repro steps and the full failure logs. Thanks.

**Comment by Diggsey** [comment]
Code to reproduce is in the linked issue.
```
vcpkg install openssl:x64-windows-static-md
cargo run
```

Not sure what you mean by "full failure logs" - the backtrace is again in the linked issue, and STATUS_HEAP_CORRUPTION is the error.

**Comment by Diggsey** [comment]
To make it easier to reproduce I've attached the project structure.
[Uploading openssl-test.zip…]()

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated in 3 months, if it is still an issue, please reopen this issue.
