### ISSUE TITLE
[boost] C26812 warning for 2 files in compile time

### ISSUE THREAD

**Issue by danyhm** [microsoft/vcpkg#27206]
****

**Is your feature request related to a problem? Please describe.**
there are 2 files that emit the same warning code C26812 when compiling with boost headers.

```
Warning	C26812	The enum type 'boost::archive::basic_text_oarchive<boost::archive::text_oarchive>::<unnamed-type-delimiter>' is unscoped. Prefer 'enum class' over 'enum' (Enum.3).	C:\dev\vcpkg\installed\x86-windows\include\boost\archive\basic_text_oarchive.hpp	75	
Warning	C26812	The enum type 'boost::detail::local_counted_base::count_type' is unscoped. Prefer 'enum class' over 'enum' (Enum.3).	C:\dev\vcpkg\installed\x86-windows\include\boost\smart_ptr\detail\local_counted_base.hpp	45	
```

**Proposed solution**
clear the warnings in the default configuration. either suppress the warnings or edit the code.

**Comment by Cheney-W** [comment]
Did you encounter this warning when using vcpkg to install boost, or when calling the boost header file in your own project?

**Comment by danyhm** [comment]
when calling the boost header files in my project. I guess this does not fall in vcpkg bugs then?

**Comment by Cheney-W** [comment]
Yes, it's not a vcpkg issue. 
You could You can suppress the warning according to the reply [here](https://developercommunity.visualstudio.com/t/no-option-to-suppress-c-code-analysis-warning-c268/724840), or submit an issue on boost to explain the problem.
