### ISSUE TITLE
v8 update to 10.6.194.18

### ISSUE THREAD

**Issue by runarundheim** [microsoft/vcpkg#27214]
Library name: v8

New version number: 10.6.194.18

The Google v8 engine version is old and should be updated to the latest stable version.

**Comment by runarundheim** [comment]
The latest stable version seems to be 10.7.193.22 now

**Comment by mz02005** [comment]
Waiting all day and all night ..............

**Comment by Atliac** [comment]
The v8 package support is not maintained.

[https://github.com/microsoft/vcpkg/issues/24510#issuecomment-1474479521](https://github.com/microsoft/vcpkg/issues/24510#issuecomment-1474479521)
