### ISSUE TITLE
Add SDL1.2 package

### ISSUE THREAD

**Issue by brupelo** [microsoft/vcpkg#2722]
Right now you can install SDL2, which is being built from sources and it'll generate a include folder SDL2 as well as SDL2.dll+SDL2.lib+SDL2main.lib.

That's great so far, now, thing is, there are a lot of projects out there still requiring SDL<=1.2, which won't work out of the box with SDL2. In fact, the API is not backwards compatible, more info [here](http://wiki.libsdl.org/MigrationGuide).

Anyway, how hard would be adding the [vc SDL package](https://www.libsdl.org/release/SDL-devel-1.2.15-VC.zip) to vcpkg? Right now I'm just unpacking manually that zip file into the vcpkg directories... but it'd be great to just doing `vcpkg install SDL`.

For someone knowing the whole nuget mechanisms I'm pretty sure this is a 10min feature. So please consider it.

Thanks in advance.

**Comment by brupelo** [comment]
Btw, kinda related to this issue, I'd like to ask you, would it be possible somehow to instruct vcpkg to uncompress+install packages which contain the library binaries without the sources?

For instance, let's say I got a repo with old libraries like SDL1.2, Directx9/10/11, containing just the binaries (include,lib) files for a certain triplet, would it be possible to use vcpkg somehow this tool is just intended to be used with source packages updated very often?

**Comment by brupelo** [comment]
@McNeight I've seen you've added sdl1 package to vcpkg... today i've tried to use it to compile some old sdl1 apps using vs2015 and with this library i'd get some errors.

After that, i've downloaded [https://www.libsdl.org/release/SDL-1.2.15.zip](https://www.libsdl.org/release/SDL-1.2.15.zip), build it specifically with vs2015 and the errors were gone... Plus, with your library you won't get SDLmain.lib, why?

**Comment by JackBoosY** [comment]
Hi @brupelo :

1. We already have port SDL1, although it is not suitable with some other ports.
2. If we join multi-version management, this will lead to more complicated port management.
3. We still want to compile the library file using source code. Because secure and less-download.

Sorry for late reply.

**Comment by PhoebeHui** [comment]
SDL1 has been added to vcpkg, and everything installed successfully with vs2015.
@brupelo, please open a new issue if it still be a problem for you.
