### ISSUE TITLE
[brotli] Build error - building brotli:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by chozhou** [microsoft/vcpkg#27222]
**Host Environment**

- OS:  Windows
- vcpkg-tool version: 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e
- vcpkg-scripts version: 98f8d00e8 2022-07-08 (3 months ago)

**To Reproduce**

D:\corextcache\Microsoft.Build.Vcpkg.2022.7.11.120-98f8d00e8\build\..\tools\vcpkg.exe install --x-wait-for-lock --triplet "x64-windows" --vcpkg-root "D:\corextcache\Microsoft.Build.Vcpkg.2022.7.11.120-98f8d00e8\build\..\tools\\" "--x-manifest-root=D:\DsMainDev\\" "--x-install-root=D:\DsMainDev\obj\x64debug\vcpkg_installed\x64-windows\\" --overlay-triplets "D:\DsMainDev\Build\vcpkg\triplets" --overlay-ports "D:\DsMainDev\Build\vcpkg\ports" --binarysource "clear;files,D:\DsMainDev\obj\x64debug\vcpkg_installed\x64-windows,readwrite"

**Failure logs**

Detecting compiler hash for triplet "x64-windows"...
The following packages will be built and installed:
  * brotli[core]:x64-windows -> 1.0.9#2
    cpprestsdk[brotli,compression,core,default-features]:x64-windows -> 2.10.18#1
Additional packages (*) will be modified to complete this operation.
Restored 0 packages from D:\DsMainDev\obj\x64debug\vcpkg_installed\x64-windows in 194 us. Use --debug to see more details.
Installing 1/2 brotli:x64-windows...
Building brotli[core]:x64-windows...
-- [OVERLAY] Loading triplet configuration from: D:\DsMainDev\Build\vcpkg\triplets\x64-windows.cmake
-- Using cached google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz.
-- Cleaning sources at D:/corextcache/Microsoft.Build.Vcpkg.2022.7.11.120-98f8d00e8/tools/buildtrees/brotli/src/6c62fc2c71-7c6c2710e9.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/corextcache/Microsoft.Build.Vcpkg.2022.7.11.120-98f8d00e8/tools/downloads/google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz
-- Applying patch install.patch
-- Applying patch fix-arm-uwp.patch
-- Applying patch pkgconfig.patch
-- Applying patch fix-ios.patch
-- Using source at D:/corextcache/Microsoft.Build.Vcpkg.2022.7.11.120-98f8d00e8/tools/buildtrees/brotli/src/6c62fc2c71-7c6c2710e9.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_copy_tool_dependencies.cmake:31 (message):
  Could not find PowerShell Core; please open an issue to report this.
Call Stack (most recent call first):
  ports/brotli/portfile.cmake:24 (vcpkg_copy_tool_dependencies)
  scripts/ports.cmake:146 (include)

error: building brotli:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+brotli
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[brotli]+Build+error
Include '[brotli] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e
    vcpkg-scripts version: 98f8d00e8 2022-07-08 (3 months ago)

You can also use the prefilled template from D:\DsMainDev\Obj\x64debug\vcpkg_installed\x64-windows\vcpkg\issue_body.md.

**Comment by survey10** [comment]
My pc has the same error!

**Comment by RazvanIonutz** [comment]
I was having a similar error. In VisualStudio I also had a warning on parsing the json file.
The error was a missing empty line, at line 7. I added the empty line and it worked ....

1. {
2.   "name": "trucks",
3.   "version-string": "1.0.0",
4.   "dependencies": [
5.     "raylib"
6.   ]
7. 
8. }

**Comment by chozhou** [comment]
what's the fun path of this json file?

**Comment by RazvanIonutz** [comment]
The name is vcpkg.json and i saved it in the project folder, where the .sln file is.

**Comment by dg0yt** [comment]
@RazvanIonutz This is entirely unrelated.

The original issue has
~~~
Could not find PowerShell Core; please open an issue to report this.
~~~
and
~~~
vcpkg-tool version: 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e
vcpkg-scripts version: https://github.com/microsoft/vcpkg/commit/98f8d00e89fb6a8019c2045cfa1edbe9d92d3405 2022-07-08 (3 months ago)
~~~

Now we wait for someone to suggest using an updated vcpkg, to see if the problem was resolved between 2022-06-17 and October 14.

**Comment by dg0yt** [comment]
.. or search for the error: 
https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+%22Could+not+find+PowerShell+Core%22

and try https://github.com/microsoft/vcpkg/issues/25322#issuecomment-1161150681.

**Comment by LilyWangLL** [comment]
@chozhou Could you try the solution from https://github.com/microsoft/vcpkg/issues/25322#issuecomment-1161150681?

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
