### ISSUE TITLE
DevIL's static patch fails to apply

### ISSUE THREAD

**Issue by andresiraola** [Microsoft/vcpkg#2723]
File paths in ports/devil/enable-static.patch are wrong.

`diff --git a/devil/src-ILU/CMakeLists.txt b/devil/src-ILU/CMakeLists.txt`

should be:

`diff --git a/src-ILU/CMakeLists.txt b/src-ILU/CMakeLists.txt`

**Comment by JackBoosY** [comment]
Hi, @andresiraola 
There is nothing wrong with build devil-static library. And i found the path "a/devil/src-ILU/" is correct with latest version. The base dir is vcpkg/buildtrees/devil/src/devil_patch_number-hash/.
Could you update and repro it?

**Comment by andresiraola** [comment]
Hi @JackBoosY,

I just pulled the last commit of vcpkg and built devil. 

It worked smootly. It might have been fixed in the last year.

I'm closing it.
