### ISSUE TITLE
[New Port Request] clipper2

### ISSUE THREAD

**Issue by MichaelGoulding** [microsoft/vcpkg#27236]
Library name: clipper2

Library description: Polygon Clipping and Offsetting Library

Source repository URL: https://github.com/AngusJohnson/Clipper2

Project homepage (if different from the source repository): http://www.angusj.com/clipper2/Docs/Overview.htm

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by dg0yt** [comment]
Duplicate of #26448.

**Comment by LilyWangLL** [comment]
> Duplicate of #26448.
