### ISSUE TITLE
[gdal] Add support for ZSTD compressed GeoTiff files

### ISSUE THREAD

**Issue by maxee** [microsoft/vcpkg#27247]
****

**Is your feature request related to a problem? Please describe.**
It appears that the built GDAL version does not support ZSTD compression for GeoTiff/Tiff files.
This leads to the problem that such files cannot be read/written.

Attempting to leads to the following messages:

```
ZSTD compression support is not configured
Cannot open TIFF file due to missing codec.
```

**Proposed solution**
Add support for ZSTD compressed GeoTiff/Tiff files.

**Describe alternatives you've considered**
Not using ZSTD compression at all which leads to larger files and longer processing times. Alternatively moving to linux altogether.

**Additional context**
I am using the rasterio library which depends on gdal. In the wheels gdal is built via vcpkg.
I originally opened an issue in the rasterio library, however it was noted there that it is an issue of vcpkg.

Original issue: https://github.com/rasterio/rasterio-wheels/issues/91

**Comment by dg0yt** [comment]
It is not a gdal issue. You have to go back in the dependency chain: Install `tiff[zstd]` before installing `gdal`. It is not a default feature of port `tiff`.
