### ISSUE TITLE
find_package error when trying to install a indirect custom overlay port library to vcpkg

### ISSUE THREAD

**Issue by GothicFox** [microsoft/vcpkg#27253]
**Describe the bug**
Hello everyone. I'm new to the vcpkg，I found it very useful to c++ project, especially the big one.

Recently, we are going to refactor our project's library dependencies with vcpkg. As you see, our project is complicated, it has many dependency libs/dlls. we came across a situation below when failure happens:

A-library:  

the A-library is a c++ library, which doesn't use other dll/libs, we set it as a custom port through vcpkg by run vcpkg overlay&install to the A-library, we succeed.  and it works in our hello-world project by , which is a executable project. the hello-world project is simplely as follows:

CMakeLists:

    cmake_minimum_required(VERSION 3.22)
    
    project(hello_world VERSION 1.0.0)
    
    set(CMAKE_CXX_STANDARD 17)
    
    add_executable(hello_world main.cpp test_do.cc test_do.h)
    
    find_package(A 1.0.0 CONFIG REQUIRED)
    
    target_link_libraries(hello_world PRIVATE
            A::A
            )

vcpkg-configuration.json：

    {
      "default-registry": {
        "kind": "git",
        "baseline": "55808d2b2053bfeaa4cb8e8acd4c36eebe54c885",
        "repository": "https://github.com/microsoft/vcpkg"
      },
      "registries": [
        {
          "kind": "git",
          "baseline": "e2ab019c5c265333a74a740814f954eaafc92777",
          "repository": "git@gitlab.xxxx-inc.com:xxxx/vcpkg-registry.git",
          "packages": [ "A" ]
        }
      ],
      "requires": {
        "microsoft:tools/kitware/cmake": "* 3.20.1"
      }
    }

B-library:  

the B-library depends on A-library, which means it includes A-library's header files and need link A-library's dll. And we hope that B-library itself is a custom port of vcpkg. when we finish writing the B's Cmakelists.txt,  and trying to build the B-library by it self, the result is success as follows: 

    MSBuild version 17.3.1+2badb37d1 for .NET Framework
      Checking Build System
      Building Custom Rule D:/workspace/projects/B/CMakeLists.txt
      file_util.cc
      dynamic_library.cc
      owner.cc
      provider.cc
      b_center.cc
      Generating Code...
      B.vcxproj -> D:\workspace\projects\B\cmake-build-debug\Debug\B.lib
    
    Build finished

and then we trying to install B to the vcpkg, for other upper libraries and executables can use it:

    vcpkg install B --overlay-ports=ports/B

it failed, and the error message is :

    -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Error at D:/workspace/sdk/vcpkg/scripts/buildsystems/vcpkg.cmake:834 (_find_package):
      Could not find a package configuration file provided by "A"
      (requested version 1.0.0) with any of the following names:
    
        AConfig.cmake
        A-config.cmake
    
      Add the installation prefix of "A" to CMAKE_PREFIX_PATH or set
      "A_DIR" to a directory containing one of the above files.  If
      "A" provides a separate development package or SDK, be sure it has
      been installed.
    Call Stack (most recent call first):
      CMakeLists.txt:35 (find_package)

so why B build success when built by itself, the A can be found at that situation, but failed when trying to install it to the vcpkg? 

i tried to read some docs of vcpkg, but didn't find anything. please help, thanks a lot.

the relative poject's files are as follows:

files of A-library:

CMakeLists.txt:

    cmake_minimum_required(VERSION 3.22)
    
    set(A_VERSION 1.0.0)
    
    project(A
            VERSION ${A_VERSION}
            DESCRIPTION "A between dlls"
            HOMEPAGE_URL "https://gitlab.xxxx.com/abc/A"
            LANGUAGES C CXX)
    
    enable_language(C CXX)
    
    include(CMakePackageConfigHelpers)
    include(GNUInstallDirs)
    
    add_library(A
            include/A.h
            include/A_api.h
            src/A.cc
            )
    add_library(A::A ALIAS A)
    
    if (BUILD_SHARED_LIBS AND WIN32)
        target_compile_definitions(A
                PRIVATE "A_EXPORT=__declspec(dllexport)"
                INTERFACE "A_EXPORT=__declspec(dllimport)")
    endif ()
    
    target_compile_features(A PUBLIC cxx_std_17)
    target_include_directories(A
            PUBLIC
            $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
            $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)
    
    ##
    
    configure_package_config_file(cmake/config.cmake.in
            ${CMAKE_CURRENT_BINARY_DIR}/A-config.cmake
            INSTALL_DESTINATION ${CMAKE_INSTALL_DATADIR}/A
            NO_SET_AND_CHECK_MACRO)
    write_basic_package_version_file(
            ${CMAKE_CURRENT_BINARY_DIR}/A-config-version.cmake
            VERSION ${A_VERSION}
            COMPATIBILITY SameMajorVersion)
    install(
            FILES
            ${CMAKE_CURRENT_BINARY_DIR}/A-config.cmake
            ${CMAKE_CURRENT_BINARY_DIR}/A-config-version.cmake
            DESTINATION
            ${CMAKE_INSTALL_DATADIR}/A)
    
    install(TARGETS A EXPORT A-targets)
    install(DIRECTORY include/ DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
    install(EXPORT A-targets
            NAMESPACE A::
            DESTINATION ${CMAKE_INSTALL_DATADIR}/A)

vcpkg.json:

    {
	    "name": "A",
	    "version": "1.0.0",
	    "description": "A between dlls",
	    "homepage": "https://gitlab.xxxx-inc.com/xxxx/A"
    }

files of B library:

CMakeLists.txt:

    cmake_minimum_required(VERSION 3.17)
    set(CMAKE_CXX_STANDARD 17)
    set(B_VERSION 1.0.0)
    set(PROJECT_NAME "B")
    project(${PROJECT_NAME}
            VERSION ${B_VERSION}
            DESCRIPTION "B framework"
            HOMEPAGE_URL "http://gitlab.xxxx-inc.com/abc/B"
            LANGUAGES C CXX)
    
    enable_language(C CXX)
    
    add_library(${PROJECT_NAME}
            # sources
            src/b/file_util.cc
            src/b/file_util.h
            src/b/dynamic_library.cc
            src/b/dynamic_library.h
            src/b/owner.cc
            src/b/provider.cc
            src/b/uce_dirent.h
            src/b/b_center.cc
    
            # headers
            include/b/config.h
            include/b/connector.h
            include/b/owner.h
            include/b/b_center.h
            include/b/provider.h
            include/b/b.h
            )
    
    add_library(B::B ALIAS B)
    
    find_package(A 1.0.0 CONFIG REQUIRED)
    
    target_link_libraries(${PROJECT_NAME} PUBLIC
            A::A
            )
    
    find_path(A_INCLUDE_DIRS "A/A.h")
    
    
    ############################################  vcpkg b congifg  ################################################
    
    include(CMakePackageConfigHelpers)
    
    include(GNUInstallDirs)
    
    if (BUILD_SHARED_LIBS AND WIN32)
        target_compile_definitions(B
                PRIVATE "B_EXPORT=__declspec(dllexport)"
                INTERFACE "B_EXPORT=__declspec(dllimport)")
    endif ()
    
    target_compile_features(B PUBLIC cxx_std_17)
    
    message("CMAKE_INSTALL_INCLUDEDIR: ${CMAKE_INSTALL_INCLUDEDIR}")
    target_include_directories(B
            PUBLIC
            $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include/>
            $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>
            )
    
    
    configure_package_config_file(cmake/config.cmake.in
            ${CMAKE_CURRENT_BINARY_DIR}/B-config.cmake
            INSTALL_DESTINATION ${CMAKE_INSTALL_DATADIR}/B
            NO_SET_AND_CHECK_MACRO)
    write_basic_package_version_file(
            ${CMAKE_CURRENT_BINARY_DIR}/B-config-version.cmake
            VERSION ${B_VERSION}
            COMPATIBILITY SameMajorVersion)
    install(
            FILES
            ${CMAKE_CURRENT_BINARY_DIR}/B-config.cmake
            ${CMAKE_CURRENT_BINARY_DIR}/B-config-version.cmake
            DESTINATION
            ${CMAKE_INSTALL_DATADIR}/B)
    
    install(TARGETS B EXPORT B-targets)
    install(DIRECTORY include/ DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
    
    find_path(A_INCLUDE_DIRS "A/A.h")
    
    message("A_INCLUDE_DIRS:  ${A_INCLUDE_DIRS}")
    message("CMAKE_INSTALL_INCLUDEDIR:  ${CMAKE_INSTALL_INCLUDEDIR}")
    install(DIRECTORY ${A_INCLUDE_DIRS}/ DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
    
    
    install(EXPORT B-targets
            NAMESPACE B::
            DESTINATION ${CMAKE_INSTALL_DATADIR}/B)

vcpkg-configuration.json：

    {
      "default-registry": {
        "kind": "git",
        "baseline": "55808d2b2053bfeaa4cb8e8acd4c36eebe54c885",
        "repository": "https://github.com/microsoft/vcpkg"
      },
      "registries": [
        {
          "kind": "git",
          "baseline": "e2ab019c5c265333a74a740814f954eaafc92777",
          "repository": "git@gitlab.xxxx-inc.com:abc/vcpkg-registry.git",
          "packages": [ "A" ]
        }
      ],
      "requires": {
        "microsoft:tools/kitware/cmake": "* 3.20.1"
      }
    }

vcpkg.json:

    {
      "name": "B",
      "version": "1.0.0",
      "description": "B framework",
      "homepage": "http://gitlab.xxxx-inc.com/abc/B",
      "dependencies": [
        "A"
      ]
    }

**Environment**
- OS: [e.g. Windows 11]
- Compiler: Visual Studio 17 2022

**Comment by Neumann-A** [comment]
What is the filelist of your vcpkg installed dir and how is As portfile designed?

SideNote:
You might also want to look into https://cmake.org/cmake/help/latest/module/GenerateExportHeader.html

**Comment by Cheney-W** [comment]
This issue hasn’t been updated for a long time, if it is still an issue for you, please reopen it.
