### ISSUE TITLE
How to add cmake library

### ISSUE THREAD

**Issue by MikeGitb** [Microsoft/vcpkg#2725]
Essentially, my question is: What is the most straight forward way to add a library which is already build via cmake, such that I can find the targets via `find_package`?

**Explanation:**
Sorry if I'm overlooking something obvious but after multiple hours of trying I still seem to be unable to add a library to vcpkg. I have a cmake based, header only library hosted on github that has an install target which copies the header files and generates an appropriate (at least I think so) <Lib>Config.cmake file. Manually installling this library allows me to use find_package to access the library. However, I'm unable to write a port file for it:

A plain

    vcpkg_from_github(...)
    vcpkg_configure_cmake(...)
    vcpkg_install_cmake()

    file(COPY${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/<lib> RENAME copyright)

sequence produces warnings about 
- header files being installed in the debug directory
- cmake files being placed outside of `share/sos`

when I remove / copy those files to the appropriate folders, the vcpkg install succeeds, but of course, now the <Lib>Config.cmake file provides invalid include paths.

For reference, you can find the library here: https://github.com/MikeGitb/ObjectStore, but be aware that this is just a dummy library that get deleted / renamed / reworked sooner rather than later.

**Comment by ras0219-msft** [comment]
Thanks for pointing out the documentation failure here!

You're 90% there, the only missing piece is `vcpkg_fixup_cmake_targets()` which will relocate the files and fix the paths. Using this, you do not need to do any copying.

It accepts a parameter (`CONFIG_PATH`) for the subpath where the config files are located.

**Comment by ras0219-msft** [comment]
You can use `git grep vcpkg_fixup_cmake` in the ports directory to quickly search for examples.

**Comment by MikeGitb** [comment]
Thank you very much!

**Comment by MikeGitb** [comment]
Ok, I used `vcpkg_fixup_cmake_targets()` and it mostly did the trick, except that a copy of the header files and the license file still ends up inside `debug` directory. Not sure if that is due to some misconfiguration in the library's cmake script, but as this is a header only library, I just delete the whole debug folder and everything seems to work just fine.

As far as I am concerned, this issue can be closed, unless you want to use it to track an addition to the docs.
