### ISSUE TITLE
[openssl] Build error

### ISSUE THREAD

**Issue by timluther** [microsoft/vcpkg#27257]
Windows 10
Microsoft Visual Studio Community 2022 (64-bit)
Version 17.2.3

**To Reproduce**

vcpkg install openssl

**Failure logs**

Computing installation plan...
The following packages will be built and installed:
    openssl[core]:x64-windows -> 3.0.5#5
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\luthe\AppData\Local\vcpkg\archives in 630 us. Use --debug to see more details.
Installing 1/1 openssl:x64-windows...
Building openssl[core]:x64-windows...
-- Using cached openssl-openssl-openssl-3.0.5.tar.gz.
-- Cleaning sources at E:/prog/vcpkg/buildtrees/openssl/src/nssl-3.0.5-df50913d32.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/prog/vcpkg/downloads/openssl-openssl-openssl-3.0.5.tar.gz
-- Applying patch E:/prog/vcpkg/ports/openssl/windows/flags.patch
-- Using source at E:/prog/vcpkg/buildtrees/openssl/src/nssl-3.0.5-df50913d32.clean
-- Getting CMake variables for x64-windows
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x64-windows-rel
-- Configure x64-windows-rel done
-- Build x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: E:/prog/vcpkg/downloads/tools/jom/jom-1.1.3/jom.exe -j 1 -f makefile install_sw install_ssldirs
    Working Directory: E:/prog/vcpkg/buildtrees/openssl/x64-windows-rel
    Error code: Access violation
    See logs for more information:
      E:\prog\vcpkg\buildtrees\openssl\build-x64-windows-rel-1-err.log

Call Stack (most recent call first):
  ports/openssl/windows/portfile.cmake:104 (vcpkg_execute_required_process)
  ports/openssl/portfile.cmake:36 (include)
  scripts/ports.cmake:147 (include)

error: building openssl:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openssl]+Build+error
Include '[openssl] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-10-12-b586c2752f75bcc3f6a243749e9a0d94d0d93ccd
    vcpkg-scripts version: a2261f65e 2022-10-14 (34 hours ago)

**Additional context**

Ran install several times, same outcome.
Updated portfiles, ran upgrade
Tried running 'jom.exe' separately on the files it appears to be crashing on but not sure how or where to do that (got 'Error: File makefile doesn't exist'). Not sure what 'Jom' even is tbh.

**Comment by timluther** [comment]
ran jom from E:\prog\vcpkg\buildtrees\openssl\x64-windows-rel
no errors, just some sort of marketing slogan
'jom 1.1.3 - empower your cores'

**Comment by dg0yt** [comment]
jom is an nmake replacement, helping to use all you CPU cores for compiling openssl.

As a workaround, try setting environment variable `VCPKG_MAX_CONCURRENCY` to 1 before installing openssl.

**Comment by FrankXie05** [comment]
Please provide the error log: `E:\prog\vcpkg\buildtrees\openssl\build-x64-windows-rel-1-err.log`.

**Comment by FrankXie05** [comment]
@timluther does the issue still occur? Have you tried the methods provided by [dg0yt](https://github.com/dg0yt)?

**Comment by wowim** [comment]
Package: openssl[core]:x64-windows -> 3.0.5#5

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.33.31630.0
- vcpkg-tool version: 2022-10-17-3247920fbdd47d08f36cbd480addd9890d3c2435
  vcpkg-scripts version: 253704407 2022-10-28 (2 days ago)

**To Reproduce**

`vcpkg install openssl:x64-windows`
or also 
`vcpkg install openssl:x86-windows`

I have the same error as @timluther, I have tried the methods provided by @dg0yt. No difference in the result. The same error ea before.

**Comment by wowim** [comment]
I found the problem .  I was using ConEmu. Using cmd it works. 
See [openssl] Build error #25107

**Comment by goodguysoft** [comment]
This error appears on other ports also. I experience it when build `boost` (due to `Python3`) and `Qt-6`. It is absent in 2022.08.15, but it appears in 2022.09.27 and 2022.10.19, as well as `master` branch for both `x64-windows` and `x64-windows-static` triplets. Probably any third-part tool that participates in build is buggy. I use Windows 11 that runs on Hyper-V, may be the fact that machine is virtual also plays any role here.

**Comment by FrankXie05** [comment]
@timluther We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
@goodguysoft Please submit a new issue.
