### ISSUE TITLE
[New Port Request] Steamworks SDK

### ISSUE THREAD

**Issue by njakob** [microsoft/vcpkg#27262]
**Library name**

Steamworks SDK

**Library description**

This is the library provided by Steam to integrate with their infrastructure.

**Source repository URL**

Sources are not accessible.

**Project homepage**

https://partner.steamgames.com/doc/sdk/api

**Anything else that is useful to know when adding?**

The port could provide a similar integration as [`discord-game-sdk`](https://github.com/microsoft/vcpkg/tree/master/ports/discord-game-sdk).

Having a simpler `find_package(steamworks-sdk CONFIG REQUIRED)` would definitely be welcome (compared to `discord-game-sdk`).

Directly integrating the application ticket system as a feature would be very beneficial  (`steamencryptedappticket`).

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by SNMetamorph** [comment]
https://github.com/Aleph-One-Marathon/vcpkg-registry/tree/main/ports/steamworks-sdk

**Comment by Waffle0823** [comment]
https://github.com/microsoft/vcpkg/pull/51368

Publishing Steamworks SDK to vcpkg
