### ISSUE TITLE
[highfive] Error when building 

### ISSUE THREAD

**Issue by jeanga** [Microsoft/vcpkg#2727]
Hi,

Command is: ./vcpkg install  highfive:x86-windows-static

Most relevant error message seems to be:
CMake Error at D:/vcpkg/downloads/cmake-3.10.2-win32-x86/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find HDF5 (missing: HDF5_LIBRARIES) (found version "1.10.1")

But hdf5:x86-windows-static is installed.
.\vcpkg.exe list hdf5
hdf5:x86-windows-static                            1.10.1-1         HDF5 is a data model, library, and file format f...

Complete error logs available on request.
Am also available to test any workaround/solution :-)

Thank you for any help you may provide me with!
Jean

**Comment by ras0219-msft** [comment]
Thanks for reporting! This should be fixed in the latest master :)

**Comment by jeanga** [comment]
Verified fixed in master!
thanks for the quick turnaround on this :-))
Jean
