### ISSUE TITLE
How do I install unistd.h and sys/time.h

### ISSUE THREAD

**Issue by tangguotongling** [microsoft/vcpkg#27270]
Please create a discussion in https://github.com/microsoft/vcpkg/discussions/new instead.
Hi~
I am trying to port C codes on Linux to Windows
And I found the pthread package in vcpkg
However, I did not find which package provide the basic linux headers such as unistd.h, sys/time.h, etc, which result a failure when building the source code.
Can anybody give me some suggestion? 
Thank you~

**Comment by dg0yt** [comment]
> `libfabric` and `libpq` provide header files named `unistd.h`, `sys/time.h`, but I don't guarantee that they have custom modifications, you can try them out. If they are not available, then you may need to manually download the relevant header files to your project.

I'm not sure if this advice is helpful. The user doesn't need just the named headers but the actual implementation of particular functions. Windows isn't POSIX and may or may not provide the desired functions. The named packages provide these headers for internal usage and may or may not  provide the desired functions.

**Comment by tangguotongling** [comment]
> 

Thanks for your advice, but I also need the header files since the compiler need to know the data type when compiling.........

**Comment by tangguotongling** [comment]
> `libfabric` and `libpq` provide header files named `unistd.h`, `sys/time.h`, but I don't guarantee that they have custom modifications, you can try them out. If they are not available, then you may need to manually download the relevant header files to your project.

Thanks, I'll try~

**Comment by Cheney-W** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
