### ISSUE TITLE
[New Port Request] Utf8Conv

### ISSUE THREAD

**Issue by GiovanniDicanio** [microsoft/vcpkg#27280]
Library name: Utf8Conv

Library description: Convenient Unicode UTF-8 <-> UTF-16 conversion functions for Windows C++ code.

Source repository URL: https://github.com/GiovanniDicanio/Utf8Conv

Project homepage (if different from the source repository):

vcpkg description files (`CONTROL` and `portfile.cmake`) are attached in the .zip archive.
[utf8conv_vcpkg_files-v1.0.0.zip](https://github.com/microsoft/vcpkg/files/9803012/utf8conv_vcpkg_files-v1.0.0.zip)

**Comment by GiovanniDicanio** [comment]
Any news??

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
