### ISSUE TITLE
find(g2o) failed in g2o package

### ISSUE THREAD

**Issue by ghost** [microsoft/vcpkg#2728]
@ras0219-msft 
after installing g2o, findg2o.cmake is not created in the vcpkg, hence it is very difficult to use g2o by any other application.

**Comment by jasjuang** [comment]
@apattnaik0721013  There really isn't an elegant solution for this. How are you using g2o if you build it from source? Do you manually copy `findg2o.cmake` to somewhere in your own project? Or did you manually point your `CMAKE_MODULE_PATH` for your own project to where `findg2o.cmake` in source?

I suppose I can update the portfile so `findg2o.cmake` will be copied to `vcpkg\installed\x64-windows\share\g2o` but you still have to manually point your `CMAKE_MODULE_PATH` there. Is this something that you want?

The best approach imo is someone create a PR upstream so g2o will actually export the targets so we can have g2o-config.cmake to use.

@ras0219-msft Is there anywhere in the `installed` folder that will be automatically added to the  `CMAKE_MODULE_PATH` when the toolchain file is loaded?

**Comment by NancyLi1013** [comment]
Hi @ghost
Thanks for posting this issue.
`g2o` has provided the usage in vcpkg:
```
   find_package(g2o CONFIG REQUIRED)
   target_link_libraries(main PRIVATE g2o::core g2o::stuff g2o::types_icp g2o::types_sba)
```
So you can use `g2o` in this way via CMake.

@jasjuang 
Thanks for looking into this issue.
