### ISSUE TITLE
[boost-vcpkg-helpers] Build error

### ISSUE THREAD

**Issue by munitioner** [microsoft/vcpkg#27292]
D:\Program Files (x86)\vcpkg\vcpkg>.\vcpkg install pcl[qt,vtk]:x64-windows
````
Computing installation plan...
The following packages will be built and installed:
  * boost-algorithm[core]:x64-windows -> 1.80.0
  * boost-align[core]:x64-windows -> 1.80.0
  * boost-any[core]:x64-windows -> 1.80.0
  * boost-array[core]:x64-windows -> 1.80.0
  * boost-asio[core]:x64-windows -> 1.80.0#1
  * boost-assert[core]:x64-windows -> 1.80.0
  * boost-atomic[core]:x64-windows -> 1.80.0
  ...
  ...
  
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\DELL\AppData\Local\vcpkg\archives in 1.789 ms. Use --debug to see more details.
Installing 1/143 boost-vcpkg-helpers:x64-windows...
Building boost-vcpkg-helpers[core]:x64-windows...
-- Installing: D:/Program Files (x86)/vcpkg/vcpkg/packages/boost-vcpkg-helpers_x64-windows/share/boost-vcpkg-helpers/boost-modular-headers.cmake
-- Installing: D:/Program Files (x86)/vcpkg/vcpkg/packages/boost-vcpkg-helpers_x64-windows/share/boost-vcpkg-helpers/usage
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.80.0/LICENSE_1_0.txt -> boost_LICENSE_1_0.txt...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.80.0/LICENSE_1_0.txt
[DEBUG] Download failed -- retrying after 1000 ms.
[DEBUG] Download failed -- retrying after 2000 ms.
[DEBUG] Download failed -- retrying after 4000 ms.
Error: Failed to download from mirror set:
https://raw.githubusercontent.com/boostorg/boost/boost-1.80.0/LICENSE_1_0.txt: WinHttpSendRequest() failed: 12007
https://raw.githubusercontent.com/boostorg/boost/boost-1.80.0/LICENSE_1_0.txt: WinHttpSendRequest() failed: 12007
https://raw.githubusercontent.com/boostorg/boost/boost-1.80.0/LICENSE_1_0.txt: WinHttpSendRequest() failed: 12007
https://raw.githubusercontent.com/boostorg/boost/boost-1.80.0/LICENSE_1_0.txt: WinHttpSendRequest() failed: 12007

[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(766):
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 3 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 1058 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 7.085 s (7040818 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. Your proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:273 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/boost-vcpkg-helpers/portfile.cmake:11 (vcpkg_download_distfile)
  scripts/ports.cmake:147 (include)


error: building boost-vcpkg-helpers:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-vcpkg-helpers
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-vcpkg-helpers]+Build+error
Include '[boost-vcpkg-helpers] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-10-12-b586c2752f75bcc3f6a243749e9a0d94d0d93ccd
    vcpkg-scripts version: 79fa9d85c 2022-10-17 (12 hours ago)


Please use the prefilled template from D:\Program Files (x86)\vcpkg\vcpkg\installed\vcpkg\issue_body.md when reporting your issue.
````

**Comment by FrankXie05** [comment]
Could you access https://raw.githubusercontent.com/boostorg/boost/boost-1.80.0/LICENSE_1_0.txt directly and download successfully? `boost_LICENSE_1_0.txt`

**Comment by FrankXie05** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen this issue.

**Comment by huangxn987** [comment]
./vcpkg.exe install cgal 
error info：

Computing installation plan...
The following packages will be built and installed:
  * boost-accumulators[core]:x86-windows -> 1.80.0#1
  * boost-algorithm[core]:x86-windows -> 1.80.0#1
  * boost-align[core]:x86-windows -> 1.80.0#1
  * boost-any[core]:x86-windows -> 1.80.0#1
  * boost-array[core]:x86-windows -> 1.80.0#1
  * boost-assert[core]:x86-windows -> 1.80.0#1
  * boost-atomic[core]:x86-windows -> 1.80.0#1
  * boost-bimap[core]:x86-windows -> 1.80.0#1
  * boost-bind[core]:x86-windows -> 1.80.0#1
  * boost-build[core]:x64-windows -> 1.80.0#2
  * boost-callable-traits[core]:x86-windows -> 1.80.0#1
  * boost-chrono[core]:x86-windows -> 1.80.0#1
  * boost-circular-buffer[core]:x86-windows -> 1.80.0#1
  * boost-compute[core]:x86-windows -> 1.80.0#1
  * boost-concept-check[core]:x86-windows -> 1.80.0#1
  * boost-config[core]:x86-windows -> 1.80.0#1
  * boost-container[core]:x86-windows -> 1.80.0#1
  * boost-container-hash[core]:x86-windows -> 1.80.0#1
  * boost-conversion[core]:x86-windows -> 1.80.0#1
  * boost-core[core]:x86-windows -> 1.80.0#1
  * boost-date-time[core]:x86-windows -> 1.80.0#1
  * boost-detail[core]:x86-windows -> 1.80.0#1
  * boost-dynamic-bitset[core]:x86-windows -> 1.80.0#1
  * boost-endian[core]:x86-windows -> 1.80.0#1
  * boost-exception[core]:x86-windows -> 1.80.0#1
  * boost-filesystem[core]:x86-windows -> 1.80.0#1
  * boost-foreach[core]:x86-windows -> 1.80.0#1
  * boost-format[core]:x86-windows -> 1.80.0#1
  * boost-function[core]:x86-windows -> 1.80.0#1
  * boost-function-types[core]:x86-windows -> 1.80.0#1
  * boost-functional[core]:x86-windows -> 1.80.0#1
  * boost-fusion[core]:x86-windows -> 1.80.0#1
  * boost-geometry[core]:x86-windows -> 1.80.0#1
  * boost-graph[core]:x86-windows -> 1.80.0#1
  * boost-heap[core]:x86-windows -> 1.80.0#1
  * boost-integer[core]:x86-windows -> 1.80.0#1
  * boost-interval[core]:x86-windows -> 1.80.0#1
  * boost-intrusive[core]:x86-windows -> 1.80.0#1
  * boost-io[core]:x86-windows -> 1.80.0#1
  * boost-iostreams[bzip2,core,lzma,zlib,zstd]:x86-windows -> 1.80.0#1
  * boost-iterator[core]:x86-windows -> 1.80.0#1
  * boost-lambda[core]:x86-windows -> 1.80.0#1
  * boost-lexical-cast[core]:x86-windows -> 1.80.0#1
  * boost-logic[core]:x86-windows -> 1.80.0#1
  * boost-math[core]:x86-windows -> 1.80.0#1
  * boost-modular-build-helper[core]:x64-windows -> 1.80.0#3
  * boost-move[core]:x86-windows -> 1.80.0#1
  * boost-mp11[core]:x86-windows -> 1.80.0#1
  * boost-mpl[core]:x86-windows -> 1.80.0#1
  * boost-multi-array[core]:x86-windows -> 1.80.0#1
  * boost-multi-index[core]:x86-windows -> 1.80.0#1
  * boost-multiprecision[core]:x86-windows -> 1.80.0#1
  * boost-numeric-conversion[core]:x86-windows -> 1.80.0#1
  * boost-optional[core]:x86-windows -> 1.80.0#1
  * boost-parameter[core]:x86-windows -> 1.80.0#1
  * boost-phoenix[core]:x86-windows -> 1.80.0#1
  * boost-polygon[core]:x86-windows -> 1.80.0#1
  * boost-pool[core]:x86-windows -> 1.80.0#1
  * boost-predef[core]:x86-windows -> 1.80.0#1
  * boost-preprocessor[core]:x86-windows -> 1.80.0#1
  * boost-property-map[core]:x86-windows -> 1.80.0#1
  * boost-property-tree[core]:x86-windows -> 1.80.0#1
  * boost-proto[core]:x86-windows -> 1.80.0#1
  * boost-ptr-container[core]:x86-windows -> 1.80.0#1
  * boost-qvm[core]:x86-windows -> 1.80.0#1
  * boost-random[core]:x86-windows -> 1.80.0#1
  * boost-range[core]:x86-windows -> 1.80.0#1
  * boost-ratio[core]:x86-windows -> 1.80.0#1
  * boost-rational[core]:x86-windows -> 1.80.0#1
  * boost-regex[core]:x86-windows -> 1.80.0#1
  * boost-serialization[core]:x86-windows -> 1.80.0#1
  * boost-smart-ptr[core]:x86-windows -> 1.80.0#1
  * boost-spirit[core]:x86-windows -> 1.80.0#1
  * boost-static-assert[core]:x86-windows -> 1.80.0#1
  * boost-system[core]:x86-windows -> 1.80.0#1
  * boost-thread[core]:x86-windows -> 1.80.0#1
  * boost-throw-exception[core]:x86-windows -> 1.80.0#1
  * boost-tokenizer[core]:x86-windows -> 1.80.0#1
  * boost-tti[core]:x86-windows -> 1.80.0#1
  * boost-tuple[core]:x86-windows -> 1.80.0#1
  * boost-type-index[core]:x86-windows -> 1.80.0#1
  * boost-type-traits[core]:x86-windows -> 1.80.0#1
  * boost-typeof[core]:x86-windows -> 1.80.0#1
  * boost-ublas[core]:x86-windows -> 1.80.0#1
  * boost-uninstall[core]:x64-windows -> 1.80.0#1
  * boost-units[core]:x86-windows -> 1.80.0#1
  * boost-unordered[core]:x86-windows -> 1.80.0#1
  * boost-utility[core]:x86-windows -> 1.80.0#1
  * boost-uuid[core]:x86-windows -> 1.80.0#1
  * boost-variant[core]:x86-windows -> 1.80.0#1
  * boost-variant2[core]:x86-windows -> 1.80.0#1
  * boost-vcpkg-helpers[core]:x86-windows -> 1.80.0#1
  * boost-winapi[core]:x86-windows -> 1.80.0#1
  * boost-xpressive[core]:x86-windows -> 1.80.0#1
  * bzip2[core,tool]:x86-windows -> 1.0.8#3
    cgal[core]:x86-windows -> 5.5.1
  * gmp[core]:x64-windows -> 6.2.1#13
  * gmp[core]:x86-windows -> 6.2.1#13
  * liblzma[core]:x86-windows -> 5.2.5#6
  * mpfr[core]:x86-windows -> 4.1.0#6
  * vcpkg-cmake-get-vars[core]:x64-windows -> 2022-09-04
  * zlib[core]:x86-windows -> 1.2.13
  * zstd[core]:x86-windows -> 1.5.2#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\huangxn\AppData\Local\vcpkg\archives in 855 us. Use --debug to see more details.
Installing 1/103 boost-vcpkg-helpers:x86-windows...
Building boost-vcpkg-helpers[core]:x86-windows...
-- Installing: E:/ProjectFile/1_SourceCode/7_Downloads/vcpkg/packages/boost-vcpkg-helpers_x86-windows/share/boost-vcpkg-helpers/boost-modular-headers.cmake
-- Installing: E:/ProjectFile/1_SourceCode/7_Downloads/vcpkg/packages/boost-vcpkg-helpers_x86-windows/share/boost-vcpkg-helpers/usage
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.80.0/LICENSE_1_0.txt -> boost_LICENSE_1_0.txt...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.80.0/LICENSE_1_0.txt
[DEBUG] Download failed -- retrying after 1000 ms.
[DEBUG] Download failed -- retrying after 2000 ms.
[DEBUG] Download failed -- retrying after 4000 ms.
Error: Failed to download from mirror set:
https://raw.githubusercontent.com/boostorg/boost/boost-1.80.0/LICENSE_1_0.txt: WinHttpSendRequest() failed: 12007
https://raw.githubusercontent.com/boostorg/boost/boost-1.80.0/LICENSE_1_0.txt: WinHttpSendRequest() failed: 12007
https://raw.githubusercontent.com/boostorg/boost/boost-1.80.0/LICENSE_1_0.txt: WinHttpSendRequest() failed: 12007
https://raw.githubusercontent.com/boostorg/boost/boost-1.80.0/LICENSE_1_0.txt: WinHttpSendRequest() failed: 12007

[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(766):
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 4 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 1311 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 7.103 s (7091516 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. Your proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:273 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/boost-vcpkg-helpers/portfile.cmake:11 (vcpkg_download_distfile)
  scripts/ports.cmake:147 (include)


error: building boost-vcpkg-helpers:x86-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-vcpkg-helpers
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-vcpkg-helpers]+Build+error
Include '[boost-vcpkg-helpers] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-10-17-3247920fbdd47d08f36cbd480addd9890d3c2435
    vcpkg-scripts version: fcfda3c78 2022-10-31 (15 hours ago)


Please use the prefilled template from E:\ProjectFile\1_SourceCode\7_Downloads\vcpkg\installed\vcpkg\issue_body.md when reporting your issue.

**Comment by FrankXie05** [comment]
@huangxn987 Have you tried this suggestion https://github.com/microsoft/vcpkg/issues/27292#issuecomment-1281874932 ? And please turn off the firewall and try again.

**Comment by SamuelXue** [comment]
> https://raw.githubusercontent.com/boostorg/boost/boost-1.80.0/LICENSE_1_0.txt

No, I can't access and download this file.

**Comment by FrankXie05** [comment]
@SamuelXue This link is valid. Please confirm whether your network is good and turn off the firewall. :)

**Comment by FrankXie05** [comment]
@SamuelXue Maybe rerun the script `bootstrap-vcpkg.bat` and try again.

**Comment by huangxn987** [comment]
> @huangxn987您是否尝试过这个建议[#27292（评论）](https://github.com/microsoft/vcpkg/issues/27292#issuecomment-1281874932)？请关闭防火墙并重试。

I don't know if it has anything to do with win11. Win10 is normal.

**Comment by FrankXie05** [comment]
Sorry, I can't reproduce your problem. May be due to proxy issues with `windows11`. Please make sure your network and proxy, if there are still problems, please report to `windows11`. :)
