### ISSUE TITLE
[nss] empty DLL Details - no description, version, product name, etc.

### ISSUE THREAD

**Issue by dinoele** [microsoft/vcpkg#27291]
**Describe the bug**
Details information (description, version, product name, etc.) is blank in the result DLL files.

**Environment**
- OS: Windows 10

**To Reproduce**
1. vcpkg install nss
2. check Details of the result DLLs (Properties -> General ->Details)

**Expected behavior**
Filled Details of the result DLLs.

**The following DLL files has empty Details:**
- freebl3.dll
- nss3.dll
- nssckbi.dll
- nssutil3.dll
- smime3.dll
- softokn3.dll
- sqlite3.dll
- ssl3.dll

**Comment by Adela0814** [comment]
What are the paths of these DLLs you are viewing？

**Comment by dinoele** [comment]
Paths are:
* vcpkg\installed\x86-windows\bin\<dllname>
* vcpkg\installed\x64-windows\bin\<dllname>
* vcpkg\packages\nss_x86-windows\bin\<dllname>
* vcpkg\packages\nss_x84-windows\bin\<dllname>

Note that _nspr4.dll_ result DLL (which is built as a step of nss build process) contains correct Details information.

**Comment by Osyotr** [comment]
Do they have this information when built without vcpkg? If not, that's an upstream bug.

**Comment by dinoele** [comment]
Could you please advise how it should be checked correctly?

**Comment by Osyotr** [comment]
Just build the package using its official build instructions and compare results with vcpkg

**Comment by Adela0814** [comment]
@dinoele any progress?

**Comment by Adela0814** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by plq** [comment]
It's an upstream bug: https://github.com/microsoft/vcpkg/pull/23917#issuecomment-1149048614
