### ISSUE TITLE
Boostrapping and installing packages from Windows command prompt fails

### ISSUE THREAD

**Issue by rchiodo** [Microsoft/vcpkg#2729]
I get this error:

> Downloading git has completed successfully.
> Extracting git...
> Move-Item : Access to the path 'F:\vcpkg\downloads\partially-extracted' is denied.
> At F:\vcpkg\scripts\VcpkgPowershellUtils.ps1:163 char:9
>          Move-Item -Path $destinationPartial -Destination $output
>          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>  CategoryInfo          : WriteError: (F:\vcpkg\downloads\partially-extracted:DirectoryInfo) [Move-Item], IOExcept
   ion
>     FullyQualifiedErrorId : MoveDirectoryItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand

> Extracting git has completed successfully.
> Could not detect or download git
> At F:\vcpkg\scripts\fetchDependency.ps1:116 char:9
>        throw ("Could not detect or download " + $Dependency)
>         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> CategoryInfo          : OperationStopped: (Could not detect or download git:String) [], RuntimeException
> FullyQualifiedErrorId : Could not detect or download git

**Comment by rchiodo** [comment]
It's working from the powershell prompt though.

**Comment by McNeight** [comment]
I'm having the exact same issue, and it is throwing the same error from both command prompt and PowerShell prompt as well.

I had never run a PowerShell script on this machine before, so all execution policies were set to undefined. I've now set the CurrentUser policy to Unrestricted, but that has no effect. I'm hesitant to muck around with other execution policy settings without fully understanding the problem.
