### ISSUE TITLE
Packages can't be imported in Visual Studio if new cmake project is selected

### ISSUE THREAD

**Issue by dylan-baros** [microsoft/vcpkg#27305]
**Describe the bug**
VCPKG packages cannot be found by Visual Studio if the new project type selected is a cmake project. Other project types work and the packages are found by Visual Studio. I use grpc as an example. 

**Environment**
- OS: Windows 10
- Visual Studio 2022 64 Bit
- vcpkg package management program version 2022-10-12-b586c2752f75bcc3f6a243749e9a0d94d0d93ccd

**To Reproduce**
1. ./vcpkg install grpc (64 bit)
2. Start a new Visual Studio cmake project
3.  Modify cmake presets file to point to toolchain (it is found with no errors)
4. Attempt to import anything from grpc in a file.

**Expected behavior**
Expect it to find the vcpkg packages.

**Additional context**
I have ran integrate install in both cmd and powershell both admin and not. Like I said, it is found in other projects..just not when you select new cmake project. 

Here is my cmake presets file:

    {
        "version": 3,
        "configurePresets": [
            {
                "name": "windows-base",
                "hidden": true,
                "generator": "Ninja",
                "binaryDir": "${sourceDir}/out/build/${presetName}",
                "installDir": "${sourceDir}/out/install/${presetName}",
                "cacheVariables": {
                    "CMAKE_C_COMPILER": "cl.exe",
                    "CMAKE_CXX_COMPILER": "cl.exe",
                    "CMAKE_TOOLCHAIN_FILE": {
                        "value": "$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake",
                        "type": "FILEPATH"
                    }
                },
                "condition": {
                    "type": "equals",
                    "lhs": "${hostSystemName}",
                    "rhs": "Windows"
                }
            },
            {
                "name": "x64-debug",
                "displayName": "x64 Debug",
                "inherits": "windows-base",
                "architecture": {
                    "value": "x64",
                    "strategy": "external"
                },
                "cacheVariables": {
                    "CMAKE_BUILD_TYPE": "Debug",
                    "CMAKE_TOOLCHAIN_FILE": {
                        "value": "$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake",
                        "type": "FILEPATH"
                    }
                }
            },
            {
                "name": "x64-release",
                "displayName": "x64 Release",
                "inherits": "x64-debug",
                "cacheVariables": {
                    "CMAKE_BUILD_TYPE": "Release",
                    "CMAKE_TOOLCHAIN_FILE": {
                        "value": "$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake",
                        "type": "FILEPATH"
                    }
                }
            },
            {
                "name": "x86-debug",
                "displayName": "x86 Debug",
                "inherits": "windows-base",
                "architecture": {
                    "value": "x86",
                    "strategy": "external"
                },
                "cacheVariables": {
                    "CMAKE_BUILD_TYPE": "Debug"
                }
            },
            {
                "name": "x86-release",
                "displayName": "x86 Release",
                "inherits": "x86-debug",
                "cacheVariables": {
                    "CMAKE_BUILD_TYPE": "Release"
                }
            },
            {
                "name": "linux-debug",
                "displayName": "Linux Debug",
                "generator": "Ninja",
                "binaryDir": "${sourceDir}/out/build/${presetName}",
                "installDir": "${sourceDir}/out/install/${presetName}",
                "cacheVariables": {
                    "CMAKE_BUILD_TYPE": "Debug"
                },
                "condition": {
                    "type": "equals",
                    "lhs": "${hostSystemName}",
                    "rhs": "Linux"
                },
                "vendor": {
                    "microsoft.com/VisualStudioRemoteSettings/CMake/1.0": {
                        "sourceDir": "$env{HOME}/.vs/$ms{projectDirName}"
                    }
                }
            },
            {
                "name": "macos-debug",
                "displayName": "macOS Debug",
                "generator": "Ninja",
                "binaryDir": "${sourceDir}/out/build/${presetName}",
                "installDir": "${sourceDir}/out/install/${presetName}",
                "cacheVariables": {
                    "CMAKE_BUILD_TYPE": "Debug"
                },
                "condition": {
                    "type": "equals",
                    "lhs": "${hostSystemName}",
                    "rhs": "Darwin"
                },
                "vendor": {
                    "microsoft.com/VisualStudioRemoteSettings/CMake/1.0": {
                        "sourceDir": "$env{HOME}/.vs/$ms{projectDirName}"
                    }
                }
            }
        ]
    }

**Comment by Neumann-A** [comment]
> ./vcpkg install grpc (64 bit)

Have a vcpkg.json alongside your `CMakeLists.txt` with grpc as a dep. 

Other possible solutions:

- delete your `CMakeCache.txt`. Toolchain must be set in first configure and changing presets does not invoke a clean reconfigure as far as I know. 

> I have ran integrate install

This does nothing in CMake. Only setting `CMAKE_TOOLCHAIN_FILE` matters

**Comment by dylan-baros** [comment]
@Neumann-A I do not understand why there is a problem at all? Looking in the cache file and I see the correct path to the toolchain. If I put find_package(gRPC CONFIG REQUIRED) in my cmake file and hover over it visual studio recognizes it. It is just if I try to use "#include <grpcpp/grpcpp.h>" in a header, visual studio gives me an error saying to install it with vcpkg..but it is installed.

**Comment by Neumann-A** [comment]
So I assume `find_package(gRPC CONFIG REQUIRED)` works and doesn't throw an error in cmake.
So did you `target_link_libraries(<your_target> PRIVATE <a_target_from_find_package_gRPC, e.g. gRPC::grpc++>)` as printed by vcpkg?
If the above is yes: Did you actually try to build the target? If yes did it succeed? If that is also a yes -> Intellisense is just acting up (try clangd instead.)

**Comment by dylan-baros** [comment]
> So I assume `find_package(gRPC CONFIG REQUIRED)` works and doesn't throw an error in cmake.
> 
> So did you `target_link_libraries(<your_target> PRIVATE <a_target_from_find_package_gRPC, e.g. gRPC::grpc++>)` as printed by vcpkg?
> 
> If the above is yes: Did you actually try to build the target? If yes did it succeed? If that is also a yes -> Intellisense is just acting up (try clangd instead.)

Correct, it does not throw an error. 

I have no code even written yet so I'm not even trying to compile. I am just trying to get the linter to recognize the include, which it does if I choose something other than a new cmake project.

**Comment by FrankXie05** [comment]
Have you tried adding the `CMAKE_TOOLCHAIN_FILE` to the top-level `CMakeSettings.json` ?
![image](https://user-images.githubusercontent.com/65999885/196580504-307f80d5-ea28-447b-af5f-983956648f7b.png)
`CMakeSettings.json`:
![image](https://user-images.githubusercontent.com/65999885/196580544-99abdfb8-76f3-4910-9699-64b8dfeaeab5.png)

**Comment by dylan-baros** [comment]
@FrankXie05 There is no CmakeSettings.json, just a CMakePresets.json.

**Comment by dylan-baros** [comment]
@FrankXie05 switched to using the CMakeSettings.json file instead and provided the -DCMAKE_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake argument as you have above, still same issue. Intellisense does not see the include.

**Comment by FrankXie05** [comment]
@dylan-baros Can you provide your error output?

**Comment by Neumann-A** [comment]
> I have no code even written yet so I'm not even trying to compile.

So how should VS/the linter know which target the file belongs to? Even more how should linter know where the stuff is installed? Using CMake the normal VS vcpkg integration is/has to be deactivated. (But your are using Ninja so there is no VS integration at all in play here)

You need:
- a target
- a source file for that target which you want to edit
- linked the target with the dependency (only this adds the include path to the compiler options.)

Otherwise IntelliSense has no chance of knowing what is going on. Since you are also using the Ninja generator you might also need to set `CMAKE_EXPORT_COMPILE_COMMANDS` but I don't know if IntelliSense can be configured to use that. (or try using a VS generator instead)

In general this is a CMake + Ninja + IntelliSense problem not a vcpkg specific problem.

**Comment by dylan-baros** [comment]
@FrankXie05 
![image](https://user-images.githubusercontent.com/74726798/196677150-759f585b-d7c4-42be-a5c4-7f58b9340fe9.png)

**Comment by dylan-baros** [comment]
> > I have no code even written yet so I'm not even trying to compile.
> 
> So how should VS/the linter know which target the file belongs to? Even more how should linter know where the stuff is installed? Using CMake the normal VS vcpkg integration is/has to be deactivated. (But your are using Ninja so there is no VS integration at all in play here)
> 
> You need:
> 
> * a target
> * a source file for that target which you want to edit
> * linked the target with the dependency (only this adds the include path to the compiler options.)
> 
> Otherwise IntelliSense has no chance of knowing what is going on. Since you are also using the Ninja generator you might also need to set `CMAKE_EXPORT_COMPILE_COMMANDS` but I don't know if IntelliSense can be configured to use that. (or try using a VS generator instead)
> 
> In general this is a CMake + Ninja + IntelliSense problem not a vcpkg specific problem.

@Neumann-A I opened and configured a project that uses gRPC and I get the same problem and it will not build because it cannot find the files.

**Comment by Neumann-A** [comment]
> @Neumann-A I opened and configured a project that uses gRPC and I get the same problem and it will not build because it cannot find the files.

Used (minimal) `CMakeLists.txt` ?

**Comment by dylan-baros** [comment]
> > @Neumann-A I opened and configured a project that uses gRPC and I get the same problem and it will not build because it cannot find the files.
> 
> Used (minimal) `CMakeLists.txt` ?

Correct. I can build with command line if I pass the toolchain location.

**Comment by dylan-baros** [comment]
Made some progress, seems to be that the problem is using Ninja as my generator. I switched to the visual studio generator and it works. Why would that happen? I have never used Ninja so I am not familiar with it. @Neumann-A @FrankXie05
