### ISSUE TITLE
libiconv:arm64-android failed

### ISSUE THREAD

**Issue by dusmit** [microsoft/vcpkg#27304]
**Host Environment**

- OS: macOS 12.6
- Compiler:~/Library/Android/sdk/ndk/23.2.8568313/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++

**To Reproduce**

vcpkg install libiconv:arm64-android --debug --binarysource=clear

**Failure logs**

CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: /usr/bin/make V=1 -j 13 -f Makefile all
    Working Directory: /Users/dusmit/Developer/vcpkg/buildtrees/libiconv/arm64-android-dbg/
    See logs for more information:
      /Users/dusmit/Developer/vcpkg/buildtrees/libiconv/build-arm64-android-dbg-out.log
      /Users/dusmit/Developer/vcpkg/buildtrees/libiconv/build-arm64-android-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:149 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:2 (vcpkg_build_make)
  ports/libiconv/portfile.cmake:39 (vcpkg_install_make)
  scripts/ports.cmake:147 (include)

[DEBUG] 34388: cmd_execute_and_stream_data() returned 1 after 53709918 us
error: building libiconv:arm64-android failed with: BUILD_FAILED

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by phasedarray** [comment]
+1. Any work-around ?

**Comment by dg0yt** [comment]
> See logs for more information:
> /Users/dusmit/Developer/vcpkg/buildtrees/libiconv/build-arm64-android-dbg-out.log
> /Users/dusmit/Developer/vcpkg/buildtrees/libiconv/build-arm64-android-dbg-err.log

**Comment by phasedarray** [comment]
In libiconv/build-arm64-android-dbg-err.log: 

/Users/me/Library/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/bits/fortify/stdio.h:53:53: error: use of undeclared identifier '__USE_FORTIFY_LEVEL'
    return __builtin___vsnprintf_chk(dest, size, 0, __bos(dest), format, ap);
                                                    ^
.././../src/1.17-e2a53830aa.clean/srclib/cdefs.h:144:48: note: expanded from macro '__bos'
#define __bos(ptr) __builtin_object_size (ptr, __USE_FORTIFY_LEVEL > 1)

**Comment by vrbhartiya** [comment]
Any more progress on this? I'm trying to compile GStreamer for android and getting stuck here.

**Comment by mgn-norm** [comment]
@vrbhartiya I was able to get 1.16 to build for android. if you revert commit '60993b8ec5d5cec012d7b3dc78d39d892a997a62' it should build for android until someone has a better solution.

**Comment by ankurvdev** [comment]
+1

**Comment by hushanjushi** [comment]
+1
