### ISSUE TITLE
OpenCV uwp(x86, x64, arm) fails to build with VS2017

### ISSUE THREAD

**Issue by carmines** [Microsoft/vcpkg#2731]
Build fails when trying to build for ARM/ARM64 for UWP.  opencv_core - filesystem.cpp is calling api's not available for UWP on ARM

-- Build arm-uwp-rel
CMake Error at D:/git/vcpkg/scripts/cmake/vcpkg_build_cmake.cmake:129 (message):
    Command failed: D:/git/vcpkg/downloads/cmake-3.10.2-win32-x86/bin/cmake.exe;--build;.;--config;Release;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No
    Working Directory: D:/git/vcpkg/buildtrees/opencv/arm-uwp-rel
    See logs for more information:
      D:\git\vcpkg\buildtrees\opencv\install-arm-uwp-rel-out.log

Build FAILED.

       "D:\git\vcpkg\buildtrees\opencv\arm-uwp-rel\install.vcxproj" (default target) (1) ->
       "D:\git\vcpkg\buildtrees\opencv\arm-uwp-rel\ALL_BUILD.vcxproj" (default target) (3) ->
       "D:\git\vcpkg\buildtrees\opencv\arm-uwp-rel\modules\core\opencv_core.vcxproj" (default target) (11) ->
       (ClCompile target) -> 
         D:\git\vcpkg\buildtrees\opencv\src\opencv-3.4.0\modules\core\src\stat.cpp(619): warning C4244: 'argument': conversion from 'float' to 'int32_t', possible loss of data [D:\git\vcpkg\buildtrees\opencv\arm-uwp-rel\modules\core\opencv_core.vcxproj]
         D:\git\vcpkg\buildtrees\opencv\src\opencv-3.4.0\modules\core\src\stat.cpp(4475): warning C4244: 'argument': conversion from 'float' to 'uint32_t', possible loss of data [D:\git\vcpkg\buildtrees\opencv\arm-uwp-rel\modules\core\opencv_core.vcxproj]
         D:\git\vcpkg\buildtrees\opencv\src\opencv-3.4.0\modules\core\src\ocl.cpp(1663): warning C4505: 'cv::ocl::parseOpenCLDeviceConfiguration': unreferenced local function has been removed [D:\git\vcpkg\buildtrees\opencv\arm-uwp-rel\modules\core\opencv_core.vcxproj]
         D:\git\vcpkg\buildtrees\opencv\src\opencv-3.4.0\modules\core\src\system.cpp(1653): warning C4100: 'name': unreferenced formal parameter [D:\git\vcpkg\buildtrees\opencv\arm-uwp-rel\modules\core\opencv_core.vcxproj]

       "D:\git\vcpkg\buildtrees\opencv\arm-uwp-rel\install.vcxproj" (default target) (1) ->
       "D:\git\vcpkg\buildtrees\opencv\arm-uwp-rel\ALL_BUILD.vcxproj" (default target) (3) ->
       "D:\git\vcpkg\buildtrees\opencv\arm-uwp-rel\modules\core\opencv_core.vcxproj" (default target) (11) ->
       (ClCompile target) -> 
         D:\git\vcpkg\buildtrees\opencv\src\opencv-3.4.0\modules\core\src\utils\filesystem.cpp(189): error C2664: 'BOOL CreateDirectoryA(LPCSTR,LPSECURITY_ATTRIBUTES)': cannot convert argument 1 from 'wchar_t [260]' to 'LPCSTR' [D:\git\vcpkg\buildtrees\opencv\arm-uwp-rel\modules\core\opencv_core.vcxproj]
         D:\git\vcpkg\buildtrees\opencv\src\opencv-3.4.0\modules\core\src\utils\filesystem.cpp(251): error C2039: 'CreateFileA': is not a member of '`global namespace'' [D:\git\vcpkg\buildtrees\opencv\arm-uwp-rel\modules\core\opencv_core.vcxproj]
         D:\git\vcpkg\buildtrees\opencv\src\opencv-3.4.0\modules\core\src\utils\filesystem.cpp(251): error C3861: 'CreateFileA': identifier not found [D:\git\vcpkg\buildtrees\opencv\arm-uwp-rel\modules\core\opencv_core.vcxproj]
         D:\git\vcpkg\buildtrees\opencv\src\opencv-3.4.0\modules\core\src\utils\filesystem.cpp(404): error C2664: 'DWORD GetTempPathW(DWORD,LPWSTR)': cannot convert argument 2 from 'char [261]' to 'LPWSTR' [D:\git\vcpkg\buildtrees\opencv\arm-uwp-rel\modules\core\opencv_core.vcxproj]

    4 Warning(s)
    4 Error(s)`

I have both 10204 and 16299 SDK's installed with all ARM and C++/UWP components installed for VS2017. Are there separate IoT SDK's that need to be installed?

**Comment by ras0219-msft** [comment]
Note: the previous push had a small bug (forgot to apply the source patch). This has been fixed in efedd6f2.

**Comment by carmines** [comment]
I am using a RaspPi-3 and there's only an IoT x64 image. I won't be able to test until that works.
