### ISSUE TITLE
[libflac] update to 1.4.1

### ISSUE THREAD

**Issue by PriitUring** [microsoft/vcpkg#27318]
Library name: libflac

New version number: 1.4.1

https://xiph.org/flac/changelog.html

https://github.com/xiph/flac/releases/tag/1.4.1

**Comment by HakanDanisik** [comment]
Hi @JonLiu1993, do you have a planned date for this update?
Thanks.

**Comment by JonLiu1993** [comment]
> 

@HakanDanisik , I am working on updating this port, I will commit a pr today.

**Comment by PriitUring** [comment]
* https://github.com/microsoft/vcpkg/issues/29588
* https://github.com/microsoft/vcpkg/pull/29584
