### ISSUE TITLE
[ogre] update to 13.4.4

### ISSUE THREAD

**Issue by TokyoSU** [microsoft/vcpkg#27327]
Library name: Ogre
New version number: 13.4.4
https://github.com/OGRECave/ogre/releases/tag/v13.4.4

**Comment by dg0yt** [comment]
https://github.com/microsoft/vcpkg/blob/ce99c947b64ea3c0e274e18cc3035ca727681089/ports/ogre/vcpkg.json#L1-L4

**Comment by TokyoSU** [comment]
weird, this site say otherwise: https://vcpkg.io/en/packages.html
i need to check the port in the folder myself next time :x

**Comment by TokyoSU** [comment]
well compiled it using vcpkg, the codec dll was not compiled :x 
rendersystem dll too.

**Comment by Adela0814** [comment]
Close it because the current version is already 13.4.4.
