### ISSUE TITLE
[OpenMesh] update to 9.0

### ISSUE THREAD

**Issue by Dizww** [microsoft/vcpkg#27334]
Library name: OpenMesh

New version number: 9.0

OpenMesh 8.1 are out. 8.1 was release in  April 23, 2020 and 9.0 in Jan. 18, 2022.

**Comment by Dizww** [comment]
@MonicaLiu0311, what is wrong with #27342?

**Comment by MonicaLiu0311** [comment]
> @MonicaLiu0311, what is wrong with #27342?

Just ran into a problem with the vcpkg deprecated functions, which is expected to be finished today.
