### ISSUE TITLE
[libiconv] Build error

### ISSUE THREAD

**Issue by ham12u** [microsoft/vcpkg#27337]
**Host Environment**
[issue_body.md](https://github.com/microsoft/vcpkg/files/9823655/issue_body.md)

- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**

`./vcpkg install xxxx`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Could you use a short path to clone vcpkg and install `libiconv` again? Like _C:/Users/DELL/vcpkg_.

**Comment by dg0yt** [comment]
~~~
    FAILED: cmTC_4c13c.exe 
    cmd.exe /C "cd . && C:\Users\DELL\Downloads\sw-master-windows-client(1)\vcpkg\downloads\tools\cmake-3.24.0-windows\cmake-3.24.0-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_4c13c.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x64\link.exe /nologo CMakeFiles\cmTC_4c13c.dir\testCCompiler.c.obj  /out:cmTC_4c13c.exe /implib:cmTC_4c13c.lib /pdb:cmTC_4c13c.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    'C:\Users\DELL\Downloads\sw-master-windows-client' is not recognized as an internal or external command,
~~~
It is not the length but `(1)`.

**Comment by ham12u** [comment]
@dg0yt I have tried this and now I am getting the error for "building openssl:x64-windows failed with: BUILD_FAILED"
[issue_body.md](https://github.com/microsoft/vcpkg/files/9827828/issue_body.md)

**Comment by LilyWangLL** [comment]
> [DEBUG] Downloading https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-32bit.zip
> [DEBUG] Download failed -- retrying after 1000 ms.
> [DEBUG] Download failed -- retrying after 2000 ms.
> [DEBUG] Download failed -- retrying after 4000 ms.
> Error: Failed to download from mirror set:
> https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-32bit.zip: WinHttpSendRequest() failed: 12002
> https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-32bit.zip: WinHttpSendRequest() failed: 12002
> https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-32bit.zip: WinHttpSendRequest() failed: 12002
> https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-32bit.zip: WinHttpSendRequest() failed: 12002
> 
> [DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(766): 
> [DEBUG] Time in subprocesses: 0 us
> [DEBUG] Time in parsing JSON: 9 us
> [DEBUG] Time in JSON reader: 0 us
> [DEBUG] Time in filesystem: 4272 us
> [DEBUG] Time in loading ports: 0 us
> [DEBUG] Exiting after 1.533 min (91958139 us)
> 
> CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
>       
>       Failed to download file with error: 1
>       If you use a proxy, please check your proxy setting. Possible causes are:
>       
>       1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
>          to `https://address:port`. This is not correct, because `https://` prefix
>          claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
>          , etc..) is an HTTP proxy. Try setting `http://address:port` to both
>          HTTP_PROXY and HTTPS_PROXY instead.
>       
>       2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
>          will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
>          Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
>          Change `http=address:port;https=address:port` to `address`, and fill the port number.
>       
>       3. Your proxy's remote server is out of service.
>       
>       In future vcpkg releases, if you are using Windows, you no longer need to set
>       HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
>       Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
>       and (https://github.com/microsoft/vcpkg-tool/pull/77)
>       
>       Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_download_distfile.cmake:273 (z_vcpkg_download_distfile_show_proxy_and_fail)
>   scripts/cmake/vcpkg_find_acquire_program.cmake:628 (vcpkg_download_distfile)
>   ports/openssl/portfile.cmake:28 (vcpkg_find_acquire_program)
>   scripts/ports.cmake:147 (include)

`openssl` build failed due to download failed, you could try manually download https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-32bit.zip

**Comment by LilyWangLL** [comment]
Ping @ham12u for response.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
