### ISSUE TITLE
 flatbuffers:x64-windows fails to build

### ISSUE THREAD

**Issue by stefando** [Microsoft/vcpkg#2735]
Package: flatbuffers:x64-windows
  Vcpkg version: 0.0.103-2018-02-05-7d969169956190b0e201d9e3d42d14e30eb46a63

-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Configuring x64-windows-dbg
-- Configuring x64-windows-dbg done
-- Build x64-windows-rel
-- Build x64-windows-rel done
-- Build x64-windows-dbg
-- Build x64-windows-dbg done
CMake Error at C:/Source/vcpkg/ports/flatbuffers/portfile.cmake:43 (file):
  file RENAME failed to rename

    C:/Source/vcpkg/packages/flatbuffers_x64-windows/bin/flatc.exe

  to

    C:/Source/vcpkg/packages/flatbuffers_x64-windows/tools/flatbuffers/flatc.exe

  because: File exists

Call Stack (most recent call first):
  C:/Source/vcpkg/scripts/ports.cmake:72 (include)

Error: Building package flatbuffers:x64-windows failed with: BUILD_FAILED

**Comment by ras0219-msft** [comment]
Thanks for reporting this! It should be fixed in the latest master.
