### ISSUE TITLE
[bzip2] Build error

### ISSUE THREAD

**Issue by qingchuanma** [microsoft/vcpkg#27365]
**Host Environment**

- OS: [e.g. Mac os]
- Compiler: revision

**To Reproduce**

`./vcpkg/vcpkg install rbdl`

**Failure logs**

- error: building bzip2:arm64-osx failed with: BUILD_FAILED
-error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+bzip2
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[bzip2]+Build+error
Include '[bzip2] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-10-17-3247920fbdd47d08f36cbd480addd9890d3c2435
    vcpkg-scripts version: f4b262b25 2022-10-17 (3 days ago)

**Comment by Adela0814** [comment]
@qingchuanma please provide the full failure logs. Thanks.

**Comment by Adela0814** [comment]
@qingchuanma ping~

**Comment by Adela0814** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
