### ISSUE TITLE
[dpp 10.0.20] x86 static build failure

### ISSUE THREAD

**Issue by veteri** [microsoft/vcpkg#27364]
**Host Environment**

- OS: Windows 10 64 Bit
- Compiler: x86 msvc v19.latest

**To Reproduce**

`./vcpkg install dpp:x86-windows-static`

**Failure logs**
`Error: dpp[core] is only supported on '(windows & !static & !uwp) | linux | osx'`

**Additional context**
The release pages of dpp github have a x86 static library, but it fails on vcpkg.

**Comment by LilyWangLL** [comment]
cc @braindigitalis 
Does `dpp` support static build?

**Comment by braindigitalis** [comment]
> cc @braindigitalis Does `dpp` support static build?

sorry for late reply - on windows, no it does not.

**Comment by LilyWangLL** [comment]
Since this port doesn't support x86 static on windows, so I am closing this issue for now.
