### ISSUE TITLE
[zlib] Build error

### ISSUE THREAD

**Issue by wellfuture** [microsoft/vcpkg#27375]
**Host Environment**

- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**

`./vcpkg install xxxx`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by asfernandes** [comment]
For me it's trying to download https://www.zlib.net/zlib-1.2.12.tar.gz but it does not exist. Only https://www.zlib.net/zlib-1.2.13.tar.gz is there.

I see there is https://zlib.net/fossils/zlib-1.2.12.tar.gz

**Comment by wellfuture** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by asfernandes** [comment]
My problem was happening when using version 1.2.12.

It worked when I used 1.2.12#2

**Comment by FrankXie05** [comment]
@asfernandes `zlib` is currently downloaded from `github`, please make sure you use the latest `vcpkg`.
https://github.com/microsoft/vcpkg/blob/934a99dc13cabb330824ae1a5ab4a53a9acc5a49/ports/zlib/portfile.cmake#L1

@wellfuture Please describe your error and provide an error log.

**Comment by foozmeat** [comment]
> @asfernandes `zlib` is currently downloaded from `github`, please make sure you use the latest `vcpkg`.

I've been using only the tagged releases to minimize the chance for bugs to creep in. What's the recommended best practice?

**Comment by FrankXie05** [comment]
@foozmeat Just keep the latest version.

**Comment by FrankXie05** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
