### ISSUE TITLE
UseSuiteSparse searches for SuiteSparse-config.cmake in a different location

### ISSUE THREAD

**Issue by ccamporesi** [Microsoft/vcpkg#2738]
I am trying to use VCPCK tool chain to support my build on windows and I encountered a problem including suite sparse. My current configuration is x64-windows non static but i believe the issue will affect all the builds.

Here are some steps to reproduce the issue adding these lines to a CMakeLists.txt: 
```
find_package(SuiteSparse REQUIRED)
include(${USE_SuiteSparse}) # found this on SuiteSparseConfig.cmake and wondering why is not included automatically
```
the include will raise a fatal error due to UseSuiteSparse.cmake looking for  SuiteSparse-config.cmake in the cmake/ subdirectory (which is not present). 
  
I apologize for not being very familiar with the vcpkg patterns and code but my guess is that the issue is related to this line:
https://github.com/Microsoft/vcpkg/blob/2d324592a4ac01086191c5137efe6eead3c3c65c/ports/suitesparse/portfile.cmake#L67
where the cmake sudirectory path is not maintained. 

Please let me know if you need more details about my current setup. 

Thanks for the great work!

Carlo

**Comment by JackBoosY** [comment]
Hi @ccamporesi , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
