### ISSUE TITLE
[sdl2] doesn't control its "optional" deps correctly ....

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#27390]
and feature flags are controlling the wrong variables. Somebody needs to take a closer look at options sdl2 has an how it interacts with the checks in `sdlchecks.cmake`. A lot of them seem to behave optionally and are not enforced!

**Comment by dg0yt** [comment]
I'm afraid there are not enough somebodys around...

For convenience, a port sdl2 issue collection:
https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+sdl2+in%3Atitle
