### ISSUE TITLE
vcpkg uses emscripten toolchain inconsistently

### ISSUE THREAD

**Issue by KivApple** [microsoft/vcpkg#27416]
****

**Is your feature request related to a problem? Please describe.**
If you pass `-DVCPKG_TARGET_TRIPLET=wasm32-emscripten` and have enviroment variables (including `EMSDK`) properly set, vcpkg will build packages using Emscripten, but it won't use Emscripten toolchain for the project itself, so you will end up with WASM packages and native project (which won't work). You need to pass explicitly `-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake` to CMake to everything work correctly.

**Proposed solution**
I think that triplet should set `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` for the whole project if a triplet file has such feature and no explicity `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` was set.

**Describe alternatives you've considered**

**Additional context**

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated in 3 months, if it is still an issue, please reopen this issue.
