### ISSUE TITLE
[icu] Build error at install phase in VS developer command prompt

### ISSUE THREAD

**Issue by equeim** [microsoft/vcpkg#27419]
**Host Environment**

- OS: Windows 11 22H2
- Compiler: MSVC 19.33.31630 (Visual Studio 2022)

**To Reproduce**

Building of icu fails at installation phase when vcpkg invoked in manifest mode from CMake in Visual Studio, or in classic/manifest mode in VS developer command prompt. When vcpkg is invoked in "clean" environment, build succeeds.

1. Enter VS developer command prompt
2. `vcpkg.exe install --triplet=x64-windows-static --host-triplet=x64-windows-static icu`

**Failure logs**

[install-x64-windows-static-dbg-err.log](https://github.com/microsoft/vcpkg/files/9846796/install-x64-windows-static-dbg-err.log)
[install-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/9846797/install-x64-windows-static-dbg-out.log)

**Comment by equeim** [comment]
I did more tests in different environments and it seems that somehow this is related to shell, not VS environment:
 - cmd.exe - build fails
 - cmd.exe with VS environment - build fails
 - Windows PowerShell  - build fails
 - Windows PowerShell with VS environment - build fails
 - PowerShell 7.2.7 - build succeeds
 - PowerShell 7.2.7 with VS environment - build succeeds

**Comment by equeim** [comment]
I was trying to reproduce this issue in clean Windows 11 installation in VM and had no luck for a while. I decided to incrementally recreate my own setup and when I installed "Windows Subsystem for Linux Preview" from Microsoft Store build started failing! When I uninstalled it on my host machine this issue disappeared.
It doesn't seem that "old" WSL from "Windows features" have this effect.

**Comment by vladsadovsky** [comment]
Same issue on Windows 11 with WSL present. 
Install step fails due to INSTALL_SCRIPT not expanding to /usr/bin/install with the message in error log:
	make[1]: ./../src/c-71_1-src-08c83f7de1.clean/source/install-sh: No such file or directory
	
Running the same script on clean Windows 11 VM without WSL shows the correct usage:?

	/usr/bin/install -c ./../src/c-71_1-src-08c83f7de1.clean/source/install-sh /C/opt/vcpkg/packages/icu_x64-		windows/C/opt/vcpkg/installed/x64-windows/debug/share/icu/icud/71.1/install-sh

**Comment by equeim** [comment]
@vladsadovsky did you install WSL from Microsoft Store or by enabling it in Windows features? For me it reproduced only with Store version.

**Comment by vladsadovsky** [comment]
From the Store, it is preferable IMO. 

I struggled for a while with this problem, because vcpkg based build is the only way I can get statically linked CMake based build for my application, based on qt5. It worked nicely till few months ago, when icu build broke and I must have WSL2 on my system. I still recall bits and pieces of Autoconfig in *nix and was able to go through build logs to find a break, but I don't have time to go through vcpkg specific patching solution - hopefully maintainers will do it.

For now the easiest workaround for me (I am on Windows 11) is to launch clean Hyper-V Development VM, but the whole vcpkg tree with dependencies I need there and copy the whole tree into the host. Cumbersome, but easy.

**Comment by nickdademo** [comment]
> Same issue on Windows 11 with WSL present. Install step fails due to INSTALL_SCRIPT not expanding to /usr/bin/install with the message in error log: make[1]: ./../src/c-71_1-src-08c83f7de1.clean/source/install-sh: No such file or directory
> 
> Running the same script on clean Windows 11 VM without WSL shows the correct usage:?
> 
> ```
> /usr/bin/install -c ./../src/c-71_1-src-08c83f7de1.clean/source/install-sh /C/opt/vcpkg/packages/icu_x64-		windows/C/opt/vcpkg/installed/x64-windows/debug/share/icu/icud/71.1/install-sh	
> ```

I am getting this same error. Came across it while building `qt-base`...

The following can also reproduce it:
```
vcpkg.exe install --triplet=x64-windows --host-triplet=x64-windows icu
````

**Comment by 4z0t** [comment]
Had the same problem. Changed vcpkg path to one without whitespaces as there message appears about it. Worked.

**Comment by nickdademo** [comment]
> Had the same problem. Changed vcpkg path to one without whitespaces as there message appears about it. Worked.

I still get the error and my `vcpkg` repo is already in a path with no spaces :(

**Comment by michaelaeriksen** [comment]
I get same error

**Comment by MonicaLiu0311** [comment]
In the latest version, the error has disappeared; if it is still an issue, please reopen this issue.

```
PS E:\vcpkg02> ./vcpkg install icu:x64-windows-static --binarysource=clear
Computing installation plan...
The following packages will be built and installed:
    icu[core]:x64-windows-static -> 72.1#4

...

-- Performing post-build validation
Stored binaries in 1 destinations.
Elapsed time to handle icu:x64-windows-static: 7.8 min
Total install time: 7.9 min
```
```
PS E:\vcpkg02> ./vcpkg version
vcpkg package management program version 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895

See LICENSE.txt for license information.
```

Related PR https://github.com/microsoft/vcpkg/pull/30544.
