### ISSUE TITLE
Error finding CMake executable after downloading and extracting CMake archive

### ISSUE THREAD

**Issue by maxula** [Microsoft/vcpkg#2741]
Using a fresh clone of VCPKG, I get an error when trying to build a package because CMake executable cannot be found. CMake archive is downloaded and extracted OK, but it seems there is an extra "cmake-3.10.2-win32-x86" subfolder in the extraction path : 

![image](https://user-images.githubusercontent.com/36202432/35911715-deafcf84-0bfa-11e8-9a3c-4814298af5dc.png)

Here is the error log : 

![image](https://user-images.githubusercontent.com/36202432/35911810-291eb576-0bfb-11e8-83ea-7148f33bf7fd.png)

**Comment by alexkaratarakis** [comment]
Should be fine in latest version. Please let me know if it works for you.

**Comment by maxula** [comment]
problem solved, thanks!
