### ISSUE TITLE
Libyuv installation failed

### ISSUE THREAD

**Issue by wj2355021** [microsoft/vcpkg#27410]
root@ecs-1ace:~# cmake -version
_cmake version 3.21.1_

root@ecs-1ace:~# lscpu
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  1
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           0x48
Model:               0
Stepping:            0x1
BogoMIPS:            200.00
L1d cache:           64K
L1i cache:           64K
L2 cache:            512K
L3 cache:            32768K
NUMA node0 CPU(s):   0,1

root@ecs-1ace:~# uname -a
Linux ecs-1ace 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:10 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux

CMake suite maintained and supported by Kitware (kitware.com/cmake).

root@ecs-1ace:~# vcpkg/vcpkg install libvpx libyuv
Computing installation plan...
The following packages are already installed:
    libvpx[core]:arm64-linux -> 1.10.0#2
The following packages will be built and installed:
    libyuv[core]:arm64-linux -> 2021-04-15
Package libvpx:arm64-linux is already installed
Detecting compiler hash for triplet arm64-linux...
Restored 0 packages from /root/.cache/vcpkg/archives in 6.441 us. Use --debug to see more details.
Starting package 1/1: libyuv:arm64-linux
Building package libyuv[core]:arm64-linux...
-- Using community triplet arm64-linux. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /root/vcpkg/triplets/community/arm64-linux.cmake
-- Using cached /root/vcpkg/downloads/libyuv-287158925b0e03ea4499a18b4e08478c5781541b.tar.gz
-- Cleaning sources at /root/vcpkg/buildtrees/libyuv/src/8c5781541b-2a09f85fed.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /root/vcpkg/downloads/libyuv-287158925b0e03ea4499a18b4e08478c5781541b.tar.gz
-- Applying patch fix_cmakelists.patch
-- Applying patch fix-build-type.patch
-- Using source at /root/vcpkg/buildtrees/libyuv/src/8c5781541b-2a09f85fed.clean
-- Configuring arm64-linux-dbg
-- Configuring arm64-linux-rel
-- Building arm64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: /usr/local/cmake21/bin/cmake --build . --config Debug --target install -- -v -j3
    Working Directory: /root/vcpkg/buildtrees/libyuv/arm64-linux-dbg
    See logs for more information:
      /root/vcpkg/buildtrees/libyuv/install-arm64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:106 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/libyuv/portfile.cmake:20 (vcpkg_install_cmake)
  scripts/ports.cmake:142 (include)

Error: Building package libyuv:arm64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libyuv
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libyuv]+Build+error
including:
  package: libyuv[core]:arm64-linux -> 2021-04-15
    vcpkg-tool version: 2021-11-24-unknownhash
    vcpkg-scripts version: 5ddd7f026 2021-12-01 (11 months ago)

Additionally, attach any relevant sections from the log files above.

root@ecs-1ace:~# more /root/vcpkg/buildtrees/libyuv/install-arm64-linux-dbg-out.log

/tmp/ccarvyhu.s: Assembler messages:
/tmp/ccarvyhu.s:824: Error: operand mismatch -- `mov v0.8h,v4.8h'
/tmp/ccarvyhu.s:824: Info:    did you mean this?
/tmp/ccarvyhu.s:824: Info:      mov v0.8b, v4.8b
/tmp/ccarvyhu.s:824: Info:    other valid variant(s):
/tmp/ccarvyhu.s:824: Info:      mov v0.16b, v4.16b
/tmp/ccarvyhu.s:825: Error: operand mismatch -- `mov v1.8h,v5.8h'
/tmp/ccarvyhu.s:825: Info:    did you mean this?
/tmp/ccarvyhu.s:825: Info:      mov v1.8b, v5.8b
/tmp/ccarvyhu.s:825: Info:    other valid variant(s):
/tmp/ccarvyhu.s:825: Info:      mov v1.16b, v5.16b
/tmp/ccarvyhu.s:884: Error: operand mismatch -- `mov v2.8h,v0.8h'
/tmp/ccarvyhu.s:884: Info:    did you mean this?
/tmp/ccarvyhu.s:884: Info:      mov v2.8b, v0.8b
/tmp/ccarvyhu.s:884: Info:    other valid variant(s):
/tmp/ccarvyhu.s:884: Info:      mov v2.16b, v0.16b
/tmp/ccarvyhu.s:956: Error: operand mismatch -- `mov v0.8h,v2.8h'
/tmp/ccarvyhu.s:956: Info:    did you mean this?
/tmp/ccarvyhu.s:956: Info:      mov v0.8b, v2.8b
/tmp/ccarvyhu.s:956: Info:    other valid variant(s):
/tmp/ccarvyhu.s:956: Info:      mov v0.16b, v2.16b
/tmp/ccarvyhu.s:962: Error: operand mismatch -- `mov v0.8h,v4.8h'
/tmp/ccarvyhu.s:962: Info:    did you mean this?
/tmp/ccarvyhu.s:962: Info:      mov v0.8b, v4.8b
/tmp/ccarvyhu.s:962: Info:    other valid variant(s):
/tmp/ccarvyhu.s:962: Info:      mov v0.16b, v4.16b
/tmp/ccarvyhu.s:965: Error: operand mismatch -- `mov v0.8h,v4.8h'
/tmp/ccarvyhu.s:965: Info:    did you mean this?
/tmp/ccarvyhu.s:965: Info:      mov v0.8b, v4.8b
/tmp/ccarvyhu.s:965: Info:    other valid variant(s):
/tmp/ccarvyhu.s:965: Info:      mov v0.16b, v4.16b
/tmp/ccarvyhu.s:966: Error: operand mismatch -- `mov v1.8h,v5.8h'
/tmp/ccarvyhu.s:966: Info:    did you mean this?
/tmp/ccarvyhu.s:966: Info:      mov v1.8b, v5.8b
/tmp/ccarvyhu.s:966: Info:    other valid variant(s):
/tmp/ccarvyhu.s:966: Info:      mov v1.16b, v5.16b
/tmp/ccarvyhu.s:1259: Error: operand mismatch -- `mov v0.8h,v4.8h'
/tmp/ccarvyhu.s:1259: Info:    did you mean this?
/tmp/ccarvyhu.s:1259: Info:     mov v0.8b, v4.8b
/tmp/ccarvyhu.s:1259: Info:    other valid variant(s):
/tmp/ccarvyhu.s:1259: Info:     mov v0.16b, v4.16b
/tmp/ccarvyhu.s:1260: Error: operand mismatch -- `mov v1.8h,v5.8h'
/tmp/ccarvyhu.s:1260: Info:    did you mean this?
/tmp/ccarvyhu.s:1260: Info:     mov v1.8b, v5.8b
/tmp/ccarvyhu.s:1260: Info:    other valid variant(s):
/tmp/ccarvyhu.s:1260: Info:     mov v1.16b, v5.16b
[47/53] /usr/bin/c++ -DHAVE_JPEG -I/root/vcpkg/buildtrees/libyuv/src/8c5781541b-2a09f85fed.clean/include -I/r
oot/vcpkg/installed/arm64-linux/include -fPIC -g -MD -MT CMakeFiles/yuv.dir/source/scale_common.cc.o -MF CMak
eFiles/yuv.dir/source/scale_common.cc.o.d -o CMakeFiles/yuv.dir/source/scale_common.cc.o -c /root/vcpkg/build
trees/libyuv/src/8c5781541b-2a09f85fed.clean/source/scale_common.cc
[48/53] /usr/bin/c++ -DHAVE_JPEG -I/root/vcpkg/buildtrees/libyuv/src/8c5781541b-2a09f85fed.clean/include -I/r
oot/vcpkg/installed/arm64-linux/include -fPIC -g -MD -MT CMakeFiles/yuv.dir/source/scale_uv.cc.o -MF CMakeFil
es/yuv.dir/source/scale_uv.cc.o.d -o CMakeFiles/yuv.dir/source/scale_uv.cc.o -c /root/vcpkg/buildtrees/libyuv
/src/8c5781541b-2a09f85fed.clean/source/scale_uv.cc
ninja: build stopped: subcommand failed.

**Comment by Yaoxiao1** [comment]
I've come up with the same problem, are there any progresses?

**Comment by Kingtous** [comment]
same issue here.

**Comment by slimsag** [comment]
The fix here is to disable NEON support. You can do this by editing `ports/libyuv/fix_cmakelists.patch` in the `vcpkg` repository to have the contents of this file:

https://gist.github.com/slimsag/a213374a5ef44194175aa6ae9ae55c5f

Then rereun `vcpkg install libyuv`

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
