### ISSUE TITLE
Please update to uriparser 0.8.5

### ISSUE THREAD

**Issue by hartwork** [Microsoft/vcpkg#2742]
Hi!

uriparser 0.8.5 has been released:
https://github.com/uriparser/uriparser/releases

Thanks for updating!

**Comment by KindDragon** [comment]
@hartwork Do you plan to support CMake build script (like [this](https://github.com/Microsoft/vcpkg/blob/master/ports/uriparser/CMakeLists.txt)) to simplify upgrade in the future?

**Comment by hartwork** [comment]
Makes sense. Please provide a pull request upstream. Thanks!

**Comment by alexkaratarakis** [comment]
Updated: d1e8095d634aa010a2974f23a90cca3ddc2f7fb5

As @KindDragon mentions, if you check the following CMakeLists.txt in the root of your repo, it will be easier in the future!

```cmake
# CMakeLists.txt
cmake_minimum_required(VERSION 3.8)
project(uriparser C)

if(MSVC)
  add_compile_options(/W3 /wd4005 /wd4996 /wd4018 -D_CRT_SECURE_NO_WARNINGS)
endif()

include_directories(include)

file(GLOB SRC src/*.c)

set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)

add_library(uriparser ${SRC})

install(
  TARGETS uriparser
  RUNTIME DESTINATION bin
  LIBRARY DESTINATION lib
  ARCHIVE DESTINATION lib
)

if(NOT DISABLE_INSTALL_HEADERS)
  install(DIRECTORY include/ DESTINATION include)
endif()

```

**Comment by hartwork** [comment]
Regarding CMake, please be invited to help https://github.com/uriparser/uriparser/pull/18 go further upstream.
