### ISSUE TITLE
[grpc] Build error

### ISSUE THREAD

**Issue by riwe1** [microsoft/vcpkg#27437]
**Host Environment**

- OS: [e.g. Windows/Linux etc...]
- Windows 11
- Compiler: revision
- Visual studio 2019 (latest build)

**To Reproduce**
install grpc:x64-windows

`./vcpkg install xxxx`

install grpc:x64-windows

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

-- Applying patch 00001-fix-uwp.patch
-- Applying patch 00002-static-linking-in-linux.patch
-- Applying patch 00003-undef-base64-macro.patch
-- Applying patch 00004-link-gdi32-on-windows.patch
-- Applying patch 00005-fix-uwp-error.patch
-- Applying patch 00009-use-system-upb.patch
-- Applying patch snprintf.patch
-- Applying patch 00012-fix-use-cxx17.patch
-- Applying patch 00014-pkgconfig-upbdefs.patch
-- Applying patch 00015-disable-download-archive.patch
-- Using source at <repo>/vcpkg/buildtrees/grpc/src/v1.49.0-b3763f9139.clean
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: <repo>/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe -v
    Working Directory: <repo>/vcpkg/buildtrees/grpc/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
     <repo>\vcpkg\buildtrees\grpc\config-x64-windows-CMakeCache.txt.log
     <repo>\vcpkg\buildtrees\grpc\config-x64-windows-CMakeCache.txt.log
      <repo>\vcpkg\buildtrees\grpc\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:246 (vcpkg_execute_required_process)
  ports/grpc/portfile.cmake:43 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

we're using the latest tagged release, but issue is present in last two tags of vcpkg. 

-- Configuring done
CMake Error at CMakeLists.txt:2407 (target_link_libraries):
  Target "grpc" links to:

    absl::any_invocable

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

CMake Error at CMakeLists.txt:2968 (target_link_libraries):
  Target "grpc_unsecure" links to:

    absl::any_invocable

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

CMake Error at CMakeLists.txt:3253 (target_link_libraries):
  Target "grpc++" links to:

    absl::cleanup

  but the target was not found.  Possible reasons include:

**Comment by Cheney-W** [comment]
Could you please provide us with:
```
\vcpkg\buildtrees\grpc\config-x64-windows-CMakeCache.txt.log
\vcpkg\buildtrees\grpc\config-x64-windows-out.log
```

**Comment by riwe1** [comment]
thank you for the update, I'm not sure I'm able to easily provide those files and don't want acidently share information. I appriciate the support.
