### ISSUE TITLE
[gmp] Build error

### ISSUE THREAD

**Issue by Nosenzor** [microsoft/vcpkg#27432]
error: building gmp:arm64-osx failed with: BUILD_FAILED

**Host Environment**

- OS: Mac OS 12.6 on ARM M2
- Compiler: Apple clang version 14.0.0 (clang-1400.0.29.102)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**To Reproduce**

`./vcpkg install amp`

**Failure logs**
Include '[gmp] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: 79fa9d85c 2022-10-17 (7 days ago)

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.
[autoconf-arm64-osx-err.log](https://github.com/microsoft/vcpkg/files/9860609/autoconf-arm64-osx-err.log)

**Comment by Nosenzor** [comment]
I've attached the log.

**Comment by Cheney-W** [comment]
Do you have `automake` installed on your machine?

**Comment by Nosenzor** [comment]
No I don't have it. I will try to install it and recheck if it fix the issue.

**Comment by Nosenzor** [comment]
I've installed automate but it does NOT fix the issue.

**Comment by Cheney-W** [comment]
> automate
Is this typo?

**Comment by Nosenzor** [comment]
Yeah it was typo.

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.

**Comment by yusufdeepwork** [comment]
> Do you have `automake` installed on your machine?

`brew install automake  ` fixed

**Comment by Nosenzor** [comment]
Note that this issue is related to [30334](https://github.com/microsoft/vcpkg/issues/30334)
