### ISSUE TITLE
[boost]The version of dll is inconsistent with that of lib

### ISSUE THREAD

**Issue by wuguinianjing** [microsoft/vcpkg#27438]
![image](https://user-images.githubusercontent.com/79711033/197527961-68f8c84d-0475-44a7-83ef-95f1d172eea1.png)

![image](https://user-images.githubusercontent.com/79711033/197527978-bc2f0afd-5691-4fa5-ab00-8eb42ee4ae9b.png)

**Comment by Adela0814** [comment]
This is by design. Boost libraries will be named -vc140 for VS2017 (at least for now).
More info please see: https://github.com/microsoft/vcpkg/issues/601

**Comment by Adela0814** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
