### ISSUE TITLE
[mpfr] build failure

### ISSUE THREAD

**Issue by Nosenzor** [microsoft/vcpkg#27439]
**Host Environment**

- OS: Mac OS 10.15
- Compiler: 
- Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**To Reproduce**

`./vcpkg install mpfr`

**Failure logs**
error: building mpfr:x64-osx failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+mpfr
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[mpfr]+Build+error
Include '[mpfr] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-09-20-522aa94e9d261c7d7b2f079bf2591ca62df5c714
    vcpkg-scripts version: 79fa9d85c 2022-10-17 (7 days ago)

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please provide the error log file.

**Comment by Nosenzor** [comment]
[autoconf-x64-osx-err.log](https://github.com/microsoft/vcpkg/files/9860554/autoconf-x64-osx-err.log)
[autoconf-x64-osx-out.log](https://github.com/microsoft/vcpkg/files/9860555/autoconf-x64-osx-out.log)

**Comment by LilyWangLL** [comment]
You could try install `autoconf-archive` to resolve this error, the similar issue: https://github.com/microsoft/vcpkg/issues/20887.

> configure.ac:550: the top level
> configure:15200: error: possibly undefined macro: AX_PTHREAD
>       If this token and others are legitimate, please use m4_pattern_allow.
>       See the Autoconf documentation.
> autoreconf: error: /usr/local/Cellar/autoconf/2.71/bin/autoconf failed with exit status: 1

**Comment by dg0yt** [comment]
@LilyWangLL Port bug? The prints a hint for linux but not for osx.

**Comment by Nosenzor** [comment]
I installed autoconf-archive through home-brew and it partially fixes the issue (build fixed) BUT It adds one dependency on the build system which break IMO vcpkg's aim.
Note : it fixes the issue on Mac x86-64 but not on ARM64

**Comment by LilyWangLL** [comment]
> I installed autoconf-archive through home-brew and it partially fixes the issue (build fixed) BUT It adds one dependency on the build system which break IMO vcpkg's aim.
> Note : it fixes the issue on Mac x86-64 but not on ARM64

Does Mac ARM64 has the same build error?
