### ISSUE TITLE
[superlu] make dependence on OpenBlas optional

### ISSUE THREAD

**Issue by bleppard** [microsoft/vcpkg#27443]
SuperLU depends on an implementation of BLAS, but it doesn't have to be OpenBlas. For my application I use a custom, optimized BLAS implementation. Also, for example, Intel provides its own optimized implementation in its Math Kernel Library. There are others.  

Hardcoding the BLAS dependency to OpenBlas makes it difficult to benchmark and/or deploy alternatives.

What I would like to see is OpenBlas be a default dependency rather than a core dependency, such that it's inclusion in the port can be optionally suppressed. Especially when using vcpkg.json manifests.

To get around this I would have to figure out how to suppress linking OpenBlas into my application when superlu is acquired via vcpkg.

My dev environment is Windows 10 x64, using Visual Studio 2022 x64 C++

**Comment by Neumann-A** [comment]
> SuperLU depends on an implementation of BLAS, but it doesn't have to be OpenBlas.

SuperLU depends on the metaport `blas` and not `openblas`. You can use an overlay (via overlay-ports) to overwrite this dependency and supply your own. Until the options RFC is implemented there is nothing vcpkg can do here.

**Comment by Cheney-W** [comment]
Did overlay `blas` solve this problem?

**Comment by bleppard** [comment]
Still learning vcpkg so haven't tried overlays yet. While it seems to me that this would likely work, it is a solution that would have to be duplicated by every user that wants to use their own blas library. Also the work to implement an overlay isn't exactly trivial, for a vcpkg and cmake newby at least. It seems to me that acquiring superlu without the blas dependency binding should be doable within the existing framework. I see other packages with different dependency configurations. But then I fully acknowledge that I could be wrong.

**Comment by Cheney-W** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
