### ISSUE TITLE
vcpkg install curl:x86-windows-static FAILED

### ISSUE THREAD

**Issue by David-Reguera-Garcia-Dreg** [Microsoft/vcpkg#2745]
C:\Users\Dreg\Downloads\vcpkg-master\vcpkg-master>vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

C:\Users\Dreg\Downloads\vcpkg-master\vcpkg-master>vcpkg install curl:x86-windows-static
The following packages will be built and installed:
    curl[core]:x86-windows-static
  * nghttp2[core]:x86-windows-static
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: nghttp2:x86-windows-static
Building package nghttp2[core]:x86-windows-static...
-- CURRENT_INSTALLED_DIR=C:/Users/Dreg/Downloads/vcpkg-master/vcpkg-master/installed/x86-windows-static
-- DOWNLOADS=C:/Users/Dreg/Downloads/vcpkg-master/vcpkg-master/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/Dreg/Downloads/vcpkg-master/vcpkg-master/packages/nghttp2_x86-windows-static
-- CURRENT_BUILDTREES_DIR=C:/Users/Dreg/Downloads/vcpkg-master/vcpkg-master/buildtrees/nghttp2
-- CURRENT_PORT_DIR=C:/Users/Dreg/Downloads/vcpkg-master/vcpkg-master/ports/nghttp2/.
nghttp2 doesn't currently support static library build
CMake Error at ports/nghttp2/portfile.cmake:10 (message):
  avoiding building DLL with static CRT.
Call Stack (most recent call first):
  scripts/ports.cmake:72 (include)

Error: Building package nghttp2:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: nghttp2:x86-windows-static
  Vcpkg version: 0.0.103-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by ras0219-msft** [comment]
Thanks for reporting this! It should be fixed in the latest master.

**Comment by David-Reguera-Garcia-Dreg** [comment]
The new release works fine, thx!
