### ISSUE TITLE
How do I get history versions of a port now

### ISSUE THREAD

**Issue by FAKERINHEART** [microsoft/vcpkg#27451]
Please create a discussion in https://github.com/microsoft/vcpkg/discussions/new instead.

In old versions, I can use `x-history` to get history version list of a port.
Now I find that this subcommand has been removed.
Thus, How can I get history of a port right now?

**Comment by MonicaLiu0311** [comment]
There's already a discussion about installing a fixed version, see if you're satisfied：
https://github.com/microsoft/vcpkg/discussions/25622

I have a method that is not very nice but can achieve the same(You can go to the version folder to see the corresponding .json file)：
`...\vcpkg\versions\s-\sqlite3.json`

**Comment by FAKERINHEART** [comment]
@MonicaLiu0311 
I suggest that `x-history`(or other substitutes) be back in new versions.

**Comment by MonicaLiu0311** [comment]
@FAKERINHEART 
There is a git command that completely replaces it:
`git blame -l versions/<port-first-char>-/<portname>.json`

Display list explanation:
`commitID` `fileName` `authorName` `date` `lineNumber` `lineContents`

**Comment by MonicaLiu0311** [comment]
The PR and rationale for removing this command are as follows:
https://github.com/microsoft/vcpkg-tool/pull/689

If you have a very important reason to restore the x-history command, please provide concrete customer use case at https://github.com/microsoft/vcpkg-tool/pull/689, thanks.

**Comment by FAKERINHEART** [comment]
> @FAKERINHEART There is a git command that completely replaces it: `git blame -l versions/<port-first-char>-/<portname>.json`
> 
> Display list explanation: `commitID` `fileName` `authorName` `date` `lineNumber` `lineContents`

Yes, I use this command instead, however, it is not convenient for me and other common users who want to control all versions in vcpkg.json witch `overrides`.

**Comment by MonicaLiu0311** [comment]
> it is not convenient for me and other common users who want to control all versions in vcpkg.json witch overrides.

I checked and found that this git command contains all the information that `x-history` can display. What is it that makes you feel inconvenient, can you explain it in detail?

**Comment by FAKERINHEART** [comment]
> > it is not convenient for me and other common users who want to control all versions in vcpkg.json witch overrides.
> 
> I checked and found that this git command contains all the information that `x-history` can display. What is it that makes you feel inconvenient, can you explain it in detail?

`CAN USE` is NOT equal `USE CONVENIENTLY`.

`git blame -l versions/<port-first-char>-/<portname>.json` VS `./vcpkg x-history portname`

Which is simple and convenient for users?
Why users should be care of how to press complicated `git command` keys to get the same effect of `x-history` which can be found in `./vcpkg --help` easily?

**Comment by MonicaLiu0311** [comment]
Ok, thanks for the detailed instructions, I'll report back on this.
