### ISSUE TITLE
Missing support for Git LFS

### ISSUE THREAD

**Issue by DDoS** [microsoft/vcpkg#27460]
As part of an effort to use a vcpkg registry to manage internal dependencies in our team, we ran into the problem that vcpkg doesn't support LFS. Trying to use `vcpkg_from_git` with a repository that uses FLS fails with a vague error message about a missing protocol.

We looked into using `vcpkg_download_distfile` to download archives already containing the LFS files, but the requirement to pass credentials explicitly (using headers) makes this a headaches for developers, who would rather rely on the git credential manager to do this automatically.

The problem with `vcpkg_from_git` is simply that it never fetches the LFS objects, and doesn't create a remote, so it can't be done automatically either. This can be fixed by adding an option to `vcpkg_from_git` to fetch LFS objects from the URL and ref, like we already do for the git objects. See #27461 for a draft PR.

I have seen #22158 and #18570, but both are closed. I propose a different solution in #27461 that is more inline with the rest of the `vcpkg_from_git` script.

**Comment by AbdulAbCellera** [comment]
+1 for this
