### ISSUE TITLE
[openssl] update to 3.0.7

### ISSUE THREAD

**Issue by ChrisWardy** [microsoft/vcpkg#27472]
Library name:
openssl

New version number:
3.0.7

Security vulnerability:
https://twitter.com/iamamoose/status/1584908434855628800

Source will be available 1st November.

**Comment by xavier2k6** [comment]
@JonLiu1993 `3.0.7` source available now:

* https://www.openssl.org/source/openssl-3.0.7.tar.gz
* https://twitter.com/HackingDave/status/1587471827298881539/photo/1

**Comment by xavier2k6** [comment]
PR: https://github.com/microsoft/vcpkg/pull/27594
