### ISSUE TITLE
[scintilla] Build errorInclude

### ISSUE THREAD

**Issue by FirmTH** [microsoft/vcpkg#27478]
**Host Environment**

- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**

`./vcpkg install xxxx`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

![Screenshot 2022-10-27 052007](https://user-images.githubusercontent.com/43969581/198149501-625cc76d-dd64-455a-af5e-c9a15bbd8175.png)

**Comment by FrankXie05** [comment]
@FirmTH Please provide the error log.
