### ISSUE TITLE
Error install all packages ":x64-linux" triplet on Windows10 for crossplatform compiling

### ISSUE THREAD

**Issue by Custler** [microsoft/vcpkg#27487]
Error install all packages ":x64-linux" triplet on Windows10 for crossplatform compiling.
For example: curl, openssl etc

**Environment**
- OS: Windows 10 Pro 22H2
- Compiler: MSVC 19.33.31630 (Visual Studio 2022)

**To Reproduce**
1. cd C:\vcpkg\
.\vcpkg install curl:x64-linux
2. See error
```
C:\vcpkg>.\vcpkg install curl:x64-linux
Computing installation plan...
The following packages will be built and installed:
    curl[core,non-http,openssl,ssl]:x64-linux -> 7.84.0#2
  * openssl[core]:x64-linux -> 3.0.5#5
  * zlib[core]:x64-linux -> 1.2.13
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
error: while detecting compiler information:
The log file content at "C:\vcpkg\buildtrees\detect_compiler\stdout-x64-linux.log" is:
-- Configuring x64-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: C:/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe -v
    Working Directory: C:/vcpkg/buildtrees/detect_compiler/x64-linux-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\detect_compiler\config-x64-linux-CMakeCache.txt.log
      C:\vcpkg\buildtrees\detect_compiler\config-x64-linux-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:310 (vcpkg_execute_required_process)
  scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:147 (include)

error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.
```

**Failure logs**
I added .txt to enable uploading
[config-x64-linux-out.log](https://github.com/microsoft/vcpkg/files/9877259/config-x64-linux-out.log)
[build.ninja.txt](https://github.com/microsoft/vcpkg/files/9877273/build.ninja.txt)
[CMakeError.log](https://github.com/microsoft/vcpkg/files/9877280/CMakeError.log)
[CMakeSystem.cmake.txt](https://github.com/microsoft/vcpkg/files/9877330/CMakeSystem.cmake.txt)

**Comment by Neumann-A** [comment]
> Error install all packages ":x64-linux" triplet on Windows10 for crossplatform compiling.

unless you somehow setup the environment for crosscompiling from win 10 to linux you are out of luck. vcpkg only setups the environment for VS. 
Consider installing WSL + build-essentials and executing vcpkg from within.

**Comment by Custler** [comment]
I am writing code in VS on Win 10, which is connected via ssh to a remote Linux server and would like to compile and debug it on that server. I think that vcpkg integration should help me with headers and libs, but not. I decide that is a bug.
 Of course, I can do all of that by hand, but it is not as convenient as by vcpkg.

**Comment by Neumann-A** [comment]
Can you configure a normal project without using vcpkg in that remote linux server? If yes use vcpkg in manifest mode. vcpkg should then install into the remote server instead.

**Comment by Adela0814** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
