### ISSUE TITLE
Port request: LCUI

### ISSUE THREAD

**Issue by nuriu** [microsoft/vcpkg#2748]
[LCUI](https://github.com/lc-soft/LCUI) is a freely available software library for building user interfaces. It is written in C, support the use XML and CSS to describe the graphical interface, you can use it to build simple desktop apps.

I could not see it in the list. It would be nice to have it in the current package ecosystem.

**Comment by fcharlie** [comment]
@lc-soft

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
