### ISSUE TITLE
How do I specify the installation directory

### ISSUE THREAD

**Issue by zzandyc** [microsoft/vcpkg#27482]
when I use vcpkg install --x-install-root=<path> package-name,then I use vcpkg list,the result is empty?

**Comment by Neumann-A** [comment]
> I use vcpkg list,the result is empty?

You probably need to use `vcpkg list  --x-install-root=<path>`

**Comment by zzandyc** [comment]
I want to put the libraries in the installed folder and classify them.for example,installed/jsoncpp/x86-windows,installed/curl/x64-windows,and I can use the vcpkg list to show all the installed libraries,what shall I do?

**Comment by Neumann-A** [comment]
> what shall I do?

Use vcpkg how it is intended to be used instead of doing some crazy hacking ;). vcpkg knows only one installed tree at a time and that is the whole meta of vcpkg.
