### ISSUE TITLE
MSVC boost-python static library cannot be linked

### ISSUE THREAD

**Issue by BewareMyPower** [microsoft/vcpkg#27491]
**Describe the bug**
I want to link my Python extension to a static boost-python library. However, it requires another two dependencies (python and zlib). So I added them as well. However, after the DLL was built successfully, when it was imported in Python, the python.exe crashed.

**Environment**
- OS: Windows
- Compiler: MSVC 14.29.30133

**To Reproduce**

Follow the steps in the repo: https://github.com/BewareMyPower/PythonExtensionDemo/tree/main/boost-python#windows

When I copied the `hello.pyd` to Python `libs` directory and import `hello` module, it crashed:

```PowerShell
> py
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import hello
# Crashed here
```

**Expected behavior**

It should be imported successfully.

**Failure logs**

You can see the libraried linked from the outputs of `cmake -B` command:

```
-- Python3_LIBRARIES: vcpkg_installed/x64-windows-static/lib/python310.lib
-- Boost Python3: vcpkg_installed/x64-windows-static/lib/boost_python310-vc140-mt.lib
-- ZLIB_LIBRARIES: vcpkg_installed/x64-windows-static/lib/zlib.lib
```

**Additional context**
The root cause might be the Python static library should not be linked into a C extension, which is loaded by the Python executable.

However, when I manually switched the linked Python library from static library to import library:

```cmake
target_link_libraries(hello PRIVATE
    ${Boost_PYTHON310_LIBRARY}
    ${CMAKE_SOURCE_DIR}/vcpkg_installed/x64-windows/lib/python310.lib
    ${ZLIB_LIBRARIES}
)
```

The build failed with unresolved symbols:

```
boost_python310-vc140-mt.lib(class.obj) : error LNK2001: unresolved external symbol _Py_NoneStruct [D:\github.com\BewareMy
Power\PythonExtensionDemo\boost-python\build\hello.vcxproj]
...
```

However, the zlib dependency can be switched to the import library:

```cmake
target_link_libraries(hello PRIVATE
    ${Boost_PYTHON310_LIBRARY}
    ${Python3_LIBRARIES}
    ${CMAKE_SOURCE_DIR}/vcpkg_installed/x64-windows/lib/zlib.lib
)
```

The build succeeded. Though it still crashed after I copied `hello.pyd` and `zlib1.dll` into the Python `libs` directory and imported the `hello` module.

**Comment by Osyotr** [comment]
Don't reference file names in `target_link_libraries`.
Usage of boost-python should look roughly like this:

```cmake
find_package(Python3 REQUIRED COMPONENTS Interpreter Development)
find_package(Boost REQUIRED COMPONENTS python310) # Can probably be python${Python3_VERSION_MAJOR}${Python3_VERSION_MINOR}

target_compile_definitions(${target_name} PRIVATE "$<$<CONFIG:Debug>:BOOST_DEBUG_PYTHON>")
target_compile_definitions(${target_name} PRIVATE "$<$<CONFIG:Debug>:Py_DEBUG>")
target_link_libraries(${target_name} PRIVATE Boost::python310) # Can probably be python${Python3_VERSION_MAJOR}${Python3_VERSION_MINOR}
target_link_libraries(${target_name} PRIVATE Python3::Python)
```

**Comment by BewareMyPower** [comment]
@Osyotr I tried your suggestion:

```diff
diff --git a/boost-python/CMakeLists.txt b/boost-python/CMakeLists.txt
index acf5759..f654d44 100644
--- a/boost-python/CMakeLists.txt
+++ b/boost-python/CMakeLists.txt
@@ -43,13 +43,16 @@ message(STATUS "Boost Python3: " ${Boost_PYTHON310_LIBRARY})
 find_library(ZLIB_LIBRARIES NAMES "zlib")
 message(STATUS "ZLIB_LIBRARIES: " ${ZLIB_LIBRARIES})

+find_package(Python3 REQUIRED COMPONENTS Interpreter Development)
+find_package(Boost REQUIRED COMPONENTS python310)
+
 add_library(hello SHARED hello.cc)
+target_compile_definitions(hello PRIVATE "$<$<CONFIG:Debug>:BOOST_DEBUG_PYTHON>")
+target_compile_definitions(hello PRIVATE "$<$<CONFIG:Debug>:Py_DEBUG>")
+target_link_libraries(hello PRIVATE Boost::python310)
+target_link_libraries(hello PRIVATE Python3::Python)
+
 include_directories(
     ${Boost_INCLUDE_DIRS}
     ${Python3_INCLUDE_DIRS}
 )
-target_link_libraries(hello PRIVATE
-    ${Boost_PYTHON310_LIBRARY}
-    ${Python3_LIBRARIES}
-    ${ZLIB_LIBRARIES}
-)
```

However, the zlib dependency is still missed.

```
python310.lib(zlibmodule.obj) : error LNK2001: unresolved external symbol deflateCopy
python310.lib(zlibmodule.obj) : error LNK2001: unresolved external symbol inflateSetDictionary
python310.lib(zlibmodule.obj) : error LNK2001: unresolved external symbol deflateSetDictionary
python310.lib(zlibmodule.obj) : error LNK2001: unresolved external symbol deflateInit_
...
```

**Comment by Osyotr** [comment]
Well maybe Python does not export its usage requirements properly. You can manually link to `ZLIB::ZLIB`.
Also, it's not clear, what version of what library you're trying to use - static boost-python and dynamic everything else? Then you might be looking for per-port customization https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md#per-port-customization

**Comment by BewareMyPower** [comment]
> static boost-python and dynamic everything else? 

I want to link static dependencies, including boost-python and the zlib it depends. The only exceptional case is python, because if it's statically linked, the module wouldn't be able to import.

I thought the following libs are the import libraries of Python:

```
-rwxrwxrwx 1 xyz xyz 355K Oct 27 17:48 vcpkg_installed/x64-windows-static/lib/manual-link/python.lib
-rwxrwxrwx 1 xyz xyz 176K Oct 27 14:19 vcpkg_installed/x64-windows/lib/python3.lib
-rwxrwxrwx 1 xyz xyz 348K Oct 27 14:18 vcpkg_installed/x64-windows/lib/python310.lib
```

However, only `python310.lib` can be linked but the unresolved external symbols would still happen, which means the symbols of `python310` cannot be included. The other libraries cannot be linked because the boost-python library depends on `python310.lib`:

> LINK : fatal error LNK1104: cannot open file 'python310.lib'

**Comment by BewareMyPower** [comment]
> Then you might be looking for per-port customization

I will take a look. Maybe the reason is that the import library was treated as a static library so that no symbol can be found.

**Comment by BewareMyPower** [comment]
This issue can be solved by adding a customized triplet:

```cmake
# triplets/x64-windows-static-boost.cmake
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
if (PORT MATCHES "python3")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
else ()
    set(VCPKG_LIBRARY_LINKAGE static)
endif ()
set(VCPKG_BUILD_TYPE release)
```

```cmake
set(VCPKG_OVERLAY_TRIPLETS ${CMAKE_SOURCE_DIR}/triplets)
set(VCPKG_TARGET_TRIPLET x64-windows-static-boost)
```
