### ISSUE TITLE
[docs] document how to invoke manifest mode manually. 

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#27508]
As the topic says:

Document/Show/Give examples how to manually invoke manifest mode via the command line without any build system integration.

**Comment by FrankXie05** [comment]
@Neumann-A The manifest mode is thought to free the user from the command line by adding a .json file to automatically implement the desired port behavior.

**Comment by Neumann-A** [comment]
@FrankXie05: 
a) This is not question.... this is a please do xyz request....
b) we are not speaking about a port in this case.
c) versioning is only available in manifest mode
d) people want to invoke it manually outside their build system (or from a build system without direct support for it e.g. meson)
e) you didn't follow the discussion in https://github.com/microsoft/vcpkg/discussions/25622

**Comment by FrankXie05** [comment]
@Neumann-A Indeed, we should improve the documentation on explicitly manually invoking manifest mode. Instead of just providing instructions on how to use one parameter (even if it is experimental). I'll discuss it at next week's meeting (including all experimental commands in more detail and examples)
https://github.com/microsoft/vcpkg/blob/master/docs/commands/common-options.md#--x-manifest-rootpath

**Comment by ras0219-msft** [comment]
We do have a "Manifest Mode" section on https://github.com/microsoft/vcpkg/blob/master/docs/commands/install.md. What additional documentation do you have in mind?

**Comment by Neumann-A** [comment]
A direct example of usage.

**Comment by MonicaLiu0311** [comment]
Manifest document:
https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/users/manifests.md
https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/commands/add.md

Example document:
https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/manifest-mode-cmake.md
https://github.com/microsoft/vcpkg-docs/tree/main/vcpkg/examples/snippets/manifest-mode-cmake

Usage example documentation already exists, so this issue will be closed now.
