### ISSUE TITLE
[gdk-pixbuf] build failure (incorrect portfile.cmake)

### ISSUE THREAD

**Issue by Cpt-Squirrell** [microsoft/vcpkg#27505]
**Host Environment**

- OS: Linux (Ubuntu)

**To Reproduce**

`./vcpkg install gdk-pixbuf`

**Failure logs**
```
Building gdk-pixbuf[core]:x64-linux...
CMake Error at scripts/cmake/vcpkg_from_gitlab.cmake:36 (message):
  REF must be specified if SHA512 is specified.
Call Stack (most recent call first):
  ports/gdk-pixbuf/portfile.cmake:1 (vcpkg_from_gitlab)
  scripts/ports.cmake:147 (include)
```

**Additional context**
Workaround which worked in my case:
Comment out `REF "${version}"` and `SHA512` from `vcpkg/ports/gdk-pixbuf/portfile.cmake` and specify `--head` when installing.
I encountered this error when attempting to install OpenCV.

**Comment by dg0yt** [comment]
~~~sh
./bootstrap-vcpkg.sh

**Comment by Cpt-Squirrell** [comment]
> ```shell
> ./bootstrap-vcpkg.sh
> ```
Pretty sure I have done that at some point. Can try it after OpenCV is finished building.

**Comment by dg0yt** [comment]
> Pretty sure I have done that at some point. Can try it after OpenCV is finished building.

But too long ago. The current tool version will provide the missing `${VERSION}` for the port.

**Comment by dg0yt** [comment]
Reminder to self: Use `vcpkg_minimum_required` more often.

**Comment by Cpt-Squirrell** [comment]
Is it intentional that `./bootstrap-vcpkg.sh` must be ran to update package info? Bootstrap sounds like you run it once upon installation.

**Comment by Cpt-Squirrell** [comment]
Then I'd suggest there be a line in the error from vcpkg asking to run bootstrap or verify bootstrap version for people like me. Speaking of which, what's the difference between running bootstrap and running git fetch/ pull as it asks you to do when searching for packages?

**Comment by Cpt-Squirrell** [comment]
Well would you look at that. I ran `./bootstrap-vcpkg.sh` and thereafter ran `vcpkg update`/ `upgrade` and it reports the same fault as I opened this issue for. Clearly it has done something because the portfile is modified.

**Comment by Cpt-Squirrell** [comment]
Turns out I just had to uncomment my changes. I don't really know how this all goes together but it now reports no new updates and did not have to upgrade the package.

**Comment by dg0yt** [comment]
> Then I'd suggest there be a line in the error from vcpkg asking to run bootstrap or verify bootstrap version for people like me. 

This would be have been achieved by adding `vcpkg_minimum_required` to the ports recipe.

> Speaking of which, what's the difference between running bootstrap and running git fetch/ pull as it asks you to do when searching for packages?

`git pull` updates the database of tool versions, port versions and build recipes. 
Bootstrap pulls the vcpkg tool binary which matches the database.

**Comment by dg0yt** [comment]
> Turns out I just had to uncomment my changes. I don't really know how this all goes together but it now reports no new updates and did not have to upgrade the package.

If you modified files in a port directory, you can do `git checkout -- ports/<dir>` to throw aways the changes.

**Comment by Cpt-Squirrell** [comment]
> `git pull` updates the database of tool versions, port versions and build recipes. Bootstrap pulls the vcpkg tool binary which matches the database.
This sounds like it should all just be bundled into a `vcpkg update` (different from the existing) command. Why are there so many steps if the end user should always use the most recent version either way . . .
