### ISSUE TITLE
Can't install openssl

### ISSUE THREAD

**Issue by Churan2018** [Microsoft/vcpkg#2750]
I am having problem to install openssl. I have the latest vcpkg. Could someone help?

C:\NetSense\netsense.core\tools\vcpkg>vcpkg install openssl
The following packages will be built and installed:
openssl[core]:x86-windows
Starting package 1/1: openssl:x86-windows
Building package openssl[core]:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/NetSense/netsense.core/tools/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/NetSense/netsense.core/tools/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/NetSense/netsense.core/tools/vcpkg/packages/openssl_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/NetSense/netsense.core/tools/vcpkg/buildtrees/openssl
-- CURRENT_PORT_DIR=C:/NetSense/netsense.core/tools/vcpkg/ports/openssl/.
-- Using cached C:/NetSense/netsense.core/tools/vcpkg/downloads/openssl-1.0.2n.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch C:/NetSense/netsense.core/tools/vcpkg/ports/openssl/ConfigureIncludeQuotesFix.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/NetSense/netsense.core/tools/vcpkg/ports/openssl/ConfigureIncludeQuotesFix.patch done
-- Applying patch C:/NetSense/netsense.core/tools/vcpkg/ports/openssl/STRINGIFYPatch.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/NetSense/netsense.core/tools/vcpkg/ports/openssl/STRINGIFYPatch.patch done
-- Applying patch C:/NetSense/netsense.core/tools/vcpkg/ports/openssl/EmbedSymbolsInStaticLibsZ7.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/NetSense/netsense.core/tools/vcpkg/ports/openssl/EmbedSymbolsInStaticLibsZ7.patch done
-- Applying patch C:/NetSense/netsense.core/tools/vcpkg/ports/openssl/RemoveNonASCIIChar.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/NetSense/netsense.core/tools/vcpkg/ports/openssl/RemoveNonASCIIChar.patch done
-- Configure x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
Command failed: C:/Windows/PERL;Configure;enable-static-engine;enable-capieng;no-ssl2;-utf-8;VC-WIN32;--prefix=C:/NetSense/netsense.core/tools/vcpkg/packages/openssl_x86-windows;--openssldir=C:/NetSense/netsense.core/tools/vcpkg/packages/openssl_x86-windows;-FS
Working Directory: C:/NetSense/netsense.core/tools/vcpkg/buildtrees/openssl/x86-windows-rel/openssl-1.0.2n
See logs for more information:

Call Stack (most recent call first):
ports/openssl/portfile.cmake:65 (vcpkg_execute_required_process)
scripts/ports.cmake:72 (include)

Error: Building package openssl:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with .\vcpkg update, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
Package: openssl:x86-windows
Vcpkg version: 0.0.103-2018-02-07-21de65f40e04df86410952ce03f4eaa48a053a68

Additionally, attach any relevant sections from the log files above.

**Comment by Zetanova** [comment]
run vcpkg in Visual Studio developer promt for VC 2017 (or 2015)

**Comment by NancyLi1013** [comment]
Hi @Churan2018 , thanks for posting this issue. I can install this package successfully on my machine with the latest vcpkg. So this issue should be fixed now. Please open a new issue if this is still a problem for you.
