### ISSUE TITLE
[gtk3[core]] CMake warns for deprecated options

### ISSUE THREAD

**Issue by Cpt-Squirrell** [microsoft/vcpkg#27519]
****

**Is your feature request related to a problem? Please describe.**
When installing, CMake warns the following:
```
CMake Warning at scripts/cmake/vcpkg_configure_meson.cmake:305 (message):
  Options ADDITIONAL_(NATIVE|CROSS)_BINARIES have been deprecated.  Only use
  ADDITIONAL_BINARIES!
```

**Proposed solution**
Remove deprecated options in favor of non-deprecated alternative.

**Describe alternatives you've considered**
Ignore it? 乁(´ツ`)ㄏ

**Comment by dg0yt** [comment]
Such harmless warnings (from central maintainer script updates) are you usually fixed with regular port updates.

**Comment by Cpt-Squirrell** [comment]
> Such harmless warnings (from central maintainer script updates) are you usually fixed with regular port updates.

I contemplated making an issue for it since it's not an error. Better to say something than nothing I decided.
