### ISSUE TITLE
[libhv] support for arm

### ISSUE THREAD

**Issue by WangHHY19931001** [microsoft/vcpkg#27518]
in windows 10 with ndk 25 ,please remove arm in supports
![image](https://user-images.githubusercontent.com/6965518/198525612-02d62e3e-699a-44ca-9457-ae6fa83f0ddb.png)

![image](https://user-images.githubusercontent.com/6965518/198525688-a21f3c4a-d8f9-4f43-8df4-3f0b5b5ee0c8.png)

![image](https://user-images.githubusercontent.com/6965518/198525787-a592b47c-b4d0-4855-8e9b-f2d72622da15.png)

**Comment by FrankXie05** [comment]
@WangHHY19931001 Is it supported on other triplets such as `arm64-windows`?

**Comment by FrankXie05** [comment]
Currently `vcpkg` only supports `arm64-windows` and `arm-uwp`. 
https://github.com/microsoft/vcpkg/tree/master/triplets
`android` is `community-triplet` https://github.com/microsoft/vcpkg/tree/master/triplets/community

**Comment by WangHHY19931001** [comment]
with change this，it worked
![image](https://user-images.githubusercontent.com/6965518/198548878-e57a8450-be37-46da-ba51-131c45b0ad84.png)
