### ISSUE TITLE
[libcurl] build failure

### ISSUE THREAD

**Issue by died64** [microsoft/vcpkg#27526]
Package: vcpkg-cmake[core]:x64-windows -> 2022-09-26

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.33.31629.0
-    vcpkg-tool version: 2022-10-17-3247920fbdd47d08f36cbd480addd9890d3c2435
    vcpkg-scripts version: c72cefb25 2022-10-26 (33 hours ago)

**To Reproduce**

`vcpkg install curl`

**Failure logs**

```
-- Installing: H:/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake
-- Installing: H:/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake
-- Installing: H:/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake
-- Installing: H:/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg-port-config.cmake
CMake Error at ports/vcpkg-cmake/portfile.cmake:13 (file):
  file INSTALL cannot find "H:/vcpkg/LICENSE.txt": File exists.
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)



```

**Additional context**

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Did you use the latest vcpkg? Could you please check the file **H:/vcpkg/LICENSE.txt** is exists? It exists in latest vcpkg as below.
![image](https://user-images.githubusercontent.com/94091114/198948546-f52b0f7e-95e6-42a7-91e5-9c07c2eed3a6.png)

**Comment by LilyWangLL** [comment]
Ping @died64 for response.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
