### ISSUE TITLE
[opencv4] Build error

### ISSUE THREAD

**Issue by workltech** [microsoft/vcpkg#27523]
**Host Environment**

- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**

`./vcpkg install xxxx`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Cheney-W** [comment]
Could you please provide us with the following info:
1. OS. compiler and vcpkg version.
2. Install command.
3. error log.

**Comment by Cheney-W** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
