### ISSUE TITLE
vcpkg ubuntu18 arm64 build error

### ISSUE THREAD

**Issue by hefengliang** [microsoft/vcpkg#27520]
**Describe the bug**
ubuntu18 arm64 build error

**Environment**
- OS: [ubuntu18 ]
- Compiler: revision

**To Reproduce**
./bootstrap-vcpkg.sh 

**Failure logs**
[25/161] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/binarycaching.cpp.o
FAILED: CMakeFiles/vcpkglib.dir/src/vcpkg/binarycaching.cpp.o 
/usr/bin/c++ -DVCPKG_BASE_VERSION=2999-12-31 -DVCPKG_VERSION=unknownhash -I/home/ubuntu/storedisk/open/vcpkg_new/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2022-10-17/include -I/home/ubuntu/storedisk/open/vcpkg_new/vcpkg/buildtrees/_vcpkg/build/_deps/fmt-src/include -O3 -DNDEBUG -include /home/ubuntu/storedisk/open/vcpkg_new/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2022-10-17/include/pch.h -pthread -std=c++1z -MD -MT CMakeFiles/vcpkglib.dir/src/vcpkg/binarycaching.cpp.o -MF CMakeFiles/vcpkglib.dir/src/vcpkg/binarycaching.cpp.o.d -o CMakeFiles/vcpkglib.dir/src/vcpkg/binarycaching.cpp.o -c /home/ubuntu/storedisk/open/vcpkg_new/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2022-10-17/src/vcpkg/binarycaching.cpp
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
In file included from /usr/include/c++/7/bits/stl_tempbuf.h:60:0,
                 from /usr/include/c++/7/bits/stl_algo.h:62,
                 from /usr/include/c++/7/algorithm:62,
                 from /home/ubuntu/storedisk/open/vcpkg_new/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2022-10-17/include/pch.h:25,
                 from <command-line>:0:
/usr/include/c++/7/bits/stl_construct.h: In instantiation of ‘void std::_Construct(_T1*, _Args&& ...) [with _T1 = std::unique_ptr<vcpkg::IBinaryProvider>; _Args = {const std::unique_ptr<vcpkg::IBinaryProvider, std::default_delete<vcpkg::IBinaryProvider> >&}]’:
/usr/include/c++/7/bits/stl_uninitialized.h:83:18:   required from ‘static _ForwardIterator std::__uninitialized_copy<_TrivialValueTypes>::__uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = __gnu_cxx::__normal_iterator<const std::unique_ptr<vcpkg::IBinaryProvider>*, std::vector<std::unique_ptr<vcpkg::IBinaryProvider> > >; _ForwardIterator = std::unique_ptr<vcpkg::IBinaryProvider>*; bool _TrivialValueTypes = false]’
/usr/include/c++/7/bits/stl_uninitialized.h:134:15:   required from ‘_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = __gnu_cxx::__normal_iterator<const std::unique_ptr<vcpkg::IBinaryProvider>*, std::vector<std::unique_ptr<vcpkg::IBinaryProvider> > >; _ForwardIterator = std::unique_ptr<vcpkg::IBinaryProvider>*]’
/usr/include/c++/7/bits/stl_uninitialized.h:289:37:   required from ‘_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = __gnu_cxx::__normal_iterator<const std::unique_ptr<vcpkg::IBinaryProvider>*, std::vector<std::unique_ptr<vcpkg::IBinaryProvider> > >; _ForwardIterator = std::unique_ptr<vcpkg::IBinaryProvider>*; _Tp = std::unique_ptr<vcpkg::IBinaryProvider>]’
/usr/include/c++/7/bits/stl_vector.h:331:31:   required from ‘std::vector<_Tp, _Alloc>::vector(const std::vector<_Tp, _Alloc>&) [with _Tp = std::unique_ptr<vcpkg::IBinaryProvider>; _Alloc = std::allocator<std::unique_ptr<vcpkg::IBinaryProvider> >]’
/home/ubuntu/storedisk/open/vcpkg_new/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2022-10-17/include/vcpkg/base/expected.h:42:57:   required from ‘vcpkg::ExpectedHolder<T>::ExpectedHolder(Fwd&&) [with Fwd = std::vector<std::unique_ptr<vcpkg::IBinaryProvider> >&; typename std::enable_if<(! is_same_v<vcpkg::ExpectedHolder<T>, typename std::remove_cv<typename std::remove_reference<_SrcTuple>::type>::type>), int>::type <anonymous> = 0; T = std::vector<std::unique_ptr<vcpkg::IBinaryProvider> >]’
/home/ubuntu/storedisk/open/vcpkg_new/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2022-10-17/include/vcpkg/base/expected.h:77:85:   required from ‘vcpkg::ExpectedT<T, Error>::ExpectedT(ConvToT&&) [with ConvToT = std::vector<std::unique_ptr<vcpkg::IBinaryProvider> >&; typename std::enable_if<(is_convertible_v<ConvToT, T> && (! is_same_v<typename std::remove_reference<_SrcTuple>::type, Error>)), int>::type <anonymous> = 0; T = std::vector<std::unique_ptr<vcpkg::IBinaryProvider> >; Error = std::__cxx11::basic_string<char>]’
/home/ubuntu/storedisk/open/vcpkg_new/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2022-10-17/src/vcpkg/binarycaching.cpp:2313:12:   required from here
/usr/include/c++/7/bits/stl_construct.h:75:7: error: use of deleted function ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = vcpkg::IBinaryProvider; _Dp = std::default_delete<vcpkg::IBinaryProvider>]’
     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/7/memory:80:0,
                 from /home/ubuntu/storedisk/open/vcpkg_new/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2022-10-17/include/pch.h:35,
                 from <command-line>:0:
/usr/include/c++/7/bits/unique_ptr.h:383:7: note: declared here
       unique_ptr(const unique_ptr&) = delete;

**Comment by autoantwort** [comment]
Which compiler are you using?

**Comment by Thomas1664** [comment]
@LilyWangLL This is a tool bug and not a build failure on a community triplet.

**Comment by Danfun64** [comment]
I am able to reproduce this bug. https://paste.debian.net/1258607

I had to also install ninja-build (version 1.8.201) in order to even reach this point.
