### ISSUE TITLE
[libsrtp] Incorrect CMake target file

### ISSUE THREAD

**Issue by Sharpe49** [microsoft/vcpkg#27538]
**Describe the bug**
The libSRTPTargets-debug.cmake and libSRTPTargets-release.cmake files have a wrong location for the DLL of libsrtp.

Example from libSRTPTargets-release.cmake :
`set_target_properties(libSRTP::srtp2 PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/srtp2.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/srtp2.dll"
  )`

The DLL location in this file should be ${_IMPORT_PREFIX}/**bin**/srtp2.dll

**Environment**
- OS: Windows 11 22H2
- Compiler: VS 2022

**To Reproduce**
1. ./vcpkg install libsrtp
2. Inspect share\libsrtp\libSRTPTargets-debug.cmake and libSRTPTargets-release.cmake files

**Expected behavior**

**Failure logs**
N/A

**Additional context**

**Comment by dg0yt** [comment]
This is the cause of https://github.com/microsoft/vcpkg/issues/20721.

**Comment by Sharpe49** [comment]
Yes, probably. For me, it impacts a modification I am making for the GStreamer port.
