### ISSUE TITLE
Why do the package installation options not include all of the MSVC2022 CMakeSettings?.

### ISSUE THREAD

**Issue by sildeag** [microsoft/vcpkg#27531]
eg. x64-Clang-Debug, x64-Clang-Release, x64-Debug, x64-Release, Mingw64-Release, Mingw64-Debug, ..  Are these all covered by x64-Windows?

**Comment by Cheney-W** [comment]
They are not covered by `x64-windows`. `x64-windows` is just one of the official triplet we provide, and the config,platform you mentioned we do not actively provide, but can be used by users as community triplets and independent. 

If you need some custom triplet, you can refer to the example from here: https://github.com/microsoft/vcpkg/tree/master/triplets/community

**Comment by Cheney-W** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
