### ISSUE TITLE
[Qt5Core] build failure when cross-compiling from Ubuntu22.04 to Windows using GCC 10-win32 x86_64-w64-mingw32

### ISSUE THREAD

**Issue by MarkH1994** [microsoft/vcpkg#27546]
**Host Environment**

- OS: Ubuntu 22.04
- Compiler: GCC 10-win32 x86_64-w64-mingw32

**To Reproduce**

Use the following `vcpkg.json`:
```
{
    "name" : "crypto-visualization",
    "version-string" : "0.0.1",
    "dependencies" : [
       "glew", 
       "glm", 
       "boost", 
       "qt5",
       "qt5-charts",
       "qt5-websockets",
       "boost-beast", 
       "nlohmann-json", 
       "mpir",
       "mongo-cxx-driver",
       "spdlog"
    ],
    "builtin-baseline": "94ce0dab56f4d8ba6bd631ba59ed682b02d45c46"
}
```

CMakeLists.txt is as follows:
```
cmake_minimum_required(VERSION 3.16)

project(Visualization)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_AUTOUIC ON)

if (MSVC)
    add_compile_options(/bigobj)
elseif(MINGW OR MSYS)
    add_compile_options(-Wa, -mbig-obj)
endif()

if (MSVC OR MINGW OR MSYS)
    add_definitions(-DWIN32_LEAN_AND_MEAN)
endif()

# find_package(OpenGL REQUIRED)


find_package(GLEW REQUIRED)
find_package(GLUT REQUIRED)
find_package(Boost COMPONENTS system REQUIRED)

find_package(nlohmann_json 3.2.0 REQUIRED)

find_package(glm REQUIRED)


# set(OPENSSL_USE_STATIC_LIBS TRUE)
find_package(OpenSSL REQUIRED)
message("OpenSSL include dir: ${OPENSSL_INCLUDE_DIR}")
message("OpenSSL libraries: ${OPENSSL_LIBRARIES}")



include_directories(${OPENSSL_INCLUDE_DIR})

find_package(Qt5 COMPONENTS Widgets Core Charts OpenGL WebSockets REQUIRED)
set_target_properties(Qt5::Core PROPERTIES AUTOMOC TRUE)
set_target_properties(Qt5::Widgets PROPERTIES AUTOMOC TRUE)

find_package(mongocxx CONFIG REQUIRED)
find_package(bsoncxx CONFIG REQUIRED)

find_package(spdlog CONFIG REQUIRED)
```

Run the following command for compilation:

`/usr/bin/cmake --no-warn-unused-cli -D_VCPKG_INSTALLED_DIR=/home/mark/Programming/cryptovisualization/vcpkg_installed_windows -D_VCPKG_TARGET_TRIPLET=x64-mingw-dynamic -D_VCPKG_HOST_TRIPLET=x64-mingw-dynamic -DCMAKE_TOOLCHAIN_FILE:STRING=/home/mark/Programming/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_BUILD:STRING=ON -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/x86_64-w64-mingw32-gcc -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/x86_64-w64-mingw32-g++ -S/home/mark/Programming/cryptovisualization -B/home/mark/Programming/cryptovisualization/build_windows/Release -G Ninja`

**Failure logs**

```
[cmake] CMake Error at vcpkg_installed_windows/x64-linux/share/cmake/Qt5Core/Qt5CoreConfig.cmake:95 (message):
[cmake]   Library not found: m
[cmake] Call Stack (most recent call first):
[cmake]   vcpkg_installed_windows/x64-linux/share/cmake/Qt5Core/Qt5CoreConfig.cmake:277 (_qt5_Core_process_prl_file)
[cmake]   /home/mark/Programming/vcpkg/scripts/buildsystems/vcpkg.cmake:834 (_find_package)
[cmake]   vcpkg_installed_windows/x64-linux/share/cmake/Qt5Gui/Qt5GuiConfig.cmake:231 (find_package)
[cmake]   /home/mark/Programming/vcpkg/scripts/buildsystems/vcpkg.cmake:834 (_find_package)
[cmake]   vcpkg_installed_windows/x64-linux/share/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:231 (find_package)
[cmake]   /home/mark/Programming/vcpkg/scripts/buildsystems/vcpkg.cmake:834 (_find_package)
[cmake]   vcpkg_installed_windows/x64-linux/share/cmake/Qt5/Qt5Config.cmake:28 (find_package)
[cmake]   /home/mark/Programming/vcpkg/scripts/buildsystems/vcpkg.cmake:834 (_find_package)
[cmake]   CMakeLists.txt:47 (find_package)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "/home/mark/Programming/cryptovisualization/build_windows/Release/CMakeFiles/CMakeOutput.log".
[cmake] See also "/home/mark/Programming/cryptovisualization/build_windows/Release/CMakeFiles/CMakeError.log".
[proc] The command: /usr/bin/cmake --no-warn-unused-cli -D_VCPKG_INSTALLED_DIR=/home/mark/Programming/cryptovisualization/vcpkg_installed_windows -D_VCPKG_TARGET_TRIPLET=x64-mingw-dynamic -D_VCPKG_HOST_TRIPLET=x64-mingw-dynamic -DCMAKE_TOOLCHAIN_FILE:STRING=/home/mark/Programming/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_BUILD:STRING=ON -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/x86_64-w64-mingw32-gcc -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/x86_64-w64-mingw32-g++ -S/home/mark/Programming/cryptovisualization -B/home/mark/Programming/cryptovisualization/build_windows/Release -G Ninja exited with code: 1 and signal: null
```

Looking at the most recent call stack in `vcpkg_installed_windows/x64-linux/share/cmake/Qt5Core/Qt5CoreConfig.cmake:95`, this is a generic message and I cannot find how it looks for the library `m`.

**Additional context**

I'm compiling this using VS Code and the command has been copied directly from VS code. I have tried to set the `VCPKG_TARGET_TRIPLET` and `VCPKG_HOST_TRIPLET` to `mingw-64-dynamic`, but to no avail. Further, I see that the error states that it looks in `x64-linux`, while I'm building for Windows. I'm not sure whether it should look in `x64-windows` instead. 

This code compiles just fine when using GCC 11.2.0 x86_64-linux-gnu and compiling it for Ubuntu 22.04.

Do you perhaps have an idea what might go wrong and how to successfully cross-compile the application?

Looking forwards to your replies.

**Comment by Osyotr** [comment]
`_VCPKG_TARGET_TRIPLET`
`_VCPKG_HOST_TRIPLET`
I'm pretty sure these should not start with underscore.
Also, why do you set mingw as host triplet on linux?

**Comment by MarkH1994** [comment]
Thanks for your reply. It does not make sense to set mingw as host triplet, so I've removed that. When running the following command:
`/usr/bin/cmake --no-warn-unused-cli VCPKG_INSTALLED_DIR=/home/mark/Programming/cryptovisualization/vcpkg_installed_windows VCPKG_TARGET_TRIPLET=x64-mingw-dynamic -DCMAKE_TOOLCHAIN_FILE:STRING=/home/mark/Programming/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_BUILD:STRING=ON -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/x86_64-w64-mingw32-gcc -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/x86_64-w64-mingw32-g++ -S/home/mark/Programming/cryptovisualization -B/home/mark/Programming/cryptovisualization/build_windows/Release -G Ninja`, the same error is still happening sadly.

**Comment by MarkH1994** [comment]
We have also tried to compile the code using older commits, but sadly, it still doesn't work. Does anyone maybe have an idea what could work?

**Comment by dg0yt** [comment]
The qt5 port do not work with mingw. Unfortunately.

**Comment by MarkH1994** [comment]
That is too bad. Any chances of this being supported in the future? I'm currently developing on Linux, but I share the executable with others who work on Windows. Right now I'm not in the position to switch to Windows, but perhaps I can utilize WSL for this. Or do  you have other suggestions?

**Comment by dg0yt** [comment]
It needs some more work to properly pass the dependencies. This is what I have: #20309

**Comment by dg0yt** [comment]
New mingw work in progress in #29505, but focusing on native builds.

**Comment by jimwang118** [comment]
Thanks to dg0yt, this issue will be resolved when commit https://github.com/microsoft/vcpkg/pull/29505 is completed. So I am closing this issue for now.

**Comment by dg0yt** [comment]
My experimentation showed that cross-builds still won't work after #29505. This needs independent work.
Basically, upstream qt5-base is not designed to build with Qt tools from a qt5-base host triplet installation, and vcpkg is not designed to pass the host toolchain settings into the target build.
