### ISSUE TITLE
[New Port Request] openfst

### ISSUE THREAD

**Issue by day253** [microsoft/vcpkg#27541]
Library name: openfst

Library description: OpenFst is a library for constructing, combining, optimizing, and searching weighted finite-state transducers (FSTs).

Source repository URL: https://github.com/kkm000/openfst

Project homepage (if different from the source repository):

https://www.openfst.org/twiki/bin/view/FST/WebHome

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
