### ISSUE TITLE
I installed vcpkg from "https://github.com/heysurfer/EnetProxy", and then tried to install openssl-windows:x64-windows. And i got this message.

### ISSUE THREAD

**Issue by RandomRoadman69** [microsoft/vcpkg#27548]
C:\Users\myname\OneDrive\Työpöytä\vcpkg-master>vcpkg install openssl-windows:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * openssl[core]:x64-windows -> 3.0.5#5
    openssl-windows[core]:x64-windows -> deprecated
  * vcpkg-cmake[core]:x64-windows -> 2022-09-26
  * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06#1
  * vcpkg-cmake-get-vars[core]:x64-windows -> 2022-09-04
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
error: while detecting compiler information:
The log file content at "C:\Users\myname\OneDrive\Työpöytä\vcpkg-master\buildtrees\detect_compiler\stdout-x64-windows.log" is:
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/Users/myname/OneDrive/Työpöytä/vcpkg-master/buildtrees/detect_compiler/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\myname\OneDrive\Työpöytä\vcpkg-master\buildtrees\detect_compiler\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:310 (vcpkg_execute_required_process)
  scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:147 (include)

error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.

i tried to fix it by:

1. reinstall vcpkg.
2. reinstall virtual studio 2022 after vcpkg deletion.

**Comment by LilyWangLL** [comment]
Please provide the error log file: `C:\Users\myname\OneDrive\Työpöytä\vcpkg-master\buildtrees\detect_compiler\config-x64-windows-out.log`.

**Comment by LilyWangLL** [comment]
And you could clone vcpkg to a short path and don't include `Työpöytä`.

**Comment by RandomRoadman69** [comment]
@LilyWangLL the "
And you could clone vcpkg to a short path and don't include Työpöytä." worked : D. Thx so much!!
