### ISSUE TITLE
[New Port Request] kaldi

### ISSUE THREAD

**Issue by day253** [microsoft/vcpkg#27544]
Library name: kaldi

Library description: Kaldi is a toolkit for speech recognition, intended for use by speech recognition researchers and professionals.

Source repository URL: https://github.com/kaldi-asr/kaldi

Project homepage (if different from the source repository): http://kaldi-asr.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

deps on:

#27541

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
