### ISSUE TITLE
[mp3lame] build failure (custom triplet)

### ISSUE THREAD

**Issue by dyfer** [microsoft/vcpkg#27559]
**Host Environment**

- OS: macOS x86_64
- Compiler: Apple clang 12.0.5 (clang-1205.0.22.11)

**To Reproduce**

`./vcpkg install mp3lame --triplet=x64-arm64-osx-release`

`x64-arm64-osx-release` triplet:
<details>

```
set(VCPKG_TARGET_ARCHITECTURE x86_64 arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
set(VCPKG_OSX_ARCHITECTURES x86_64 arm64)
set(VCPKG_BUILD_TYPE release)
```

</details>

**Failure logs**
`config-x64-arm64-osx-release-rel-err.log`:
```
configure: error: in `/Users/marcin/src/vcpkg/buildtrees/mp3lame/x64-arm64-osx-release-rel':
configure: error: C preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details
```
[config-x64-arm64-osx-release-rel-out.log](https://github.com/microsoft/vcpkg/files/9896927/config-x64-arm64-osx-release-rel-out.log)
[config-x64-arm64-osx-release-rel-err.log](https://github.com/microsoft/vcpkg/files/9896928/config-x64-arm64-osx-release-rel-err.log)
[config-x64-arm64-osx-release-rel-config.log](https://github.com/microsoft/vcpkg/files/9896929/config-x64-arm64-osx-release-rel-config.log)

**Additional context**

After https://github.com/microsoft/vcpkg/pull/27171, **building with this configuration works**, _but only on arm64 host_. This PR reports failure when building the same configuration on x86_64 host. 

I can't seem to figure out what the issue is. While the detection of the C Preprocessor is clearly wrong (see the error above), that might result from some other problems.

Trying to narrow this down, I have compared `config.log` between when building the same configuration on different hosts:
x86_64 host (fails): [config.log](https://github.com/microsoft/vcpkg/files/9896938/config.log)
arm64 host (works): [config.log](https://github.com/microsoft/vcpkg/files/9896939/config.log)
As you can see in the logs, the detection reports different paths for compilers etc. 
Additionally, when I run the configure script manually (`./../src/0844b9eadb-3f9a96cefa.clean/configure --host=universal-apple-darwin --enable-static=yes --enable-shared=no--with-pic=yes --disable-silent-rules --verbose --disable-shared --enable-static --prefix=/Users/user/src/vcpkg/installed/x64-arm64-osx-release-supercollider --bindir=/tools/mp3lame/bin --sbindir=/tools/mp3lame/sbin --libdir=/lib --mandir=/share/mp3lame --docdir=/share/mp3lame --datarootdir=/share/mp3lame`) in terminal on the same x86_64 host, the configuration actually passes. Heres' the output:
[config.log](https://github.com/microsoft/vcpkg/files/9896941/config.log)

For reference, here are outputs from the configure step on the same machine (x86_64) when building single architectures (both builds working):
x64-osx: [config.log](https://github.com/microsoft/vcpkg/files/9896943/config.log)
arm64-osx: [config.log](https://github.com/microsoft/vcpkg/files/9896946/config.log)

I'd appreciate any pointers as to how this could be solved.

**Comment by bramtayl** [comment]
I'm having issues with this on x64-mingw-dynamic

**Comment by bramtayl** [comment]
There error I'm getting is langinfo.h: No such file or directory, which is maybe a linux header not available on mingw?

**Comment by bramtayl** [comment]
https://github.com/bincrafters/community/issues/480

**Comment by bramtayl** [comment]
This seems have been fixed a few days after 3.100 was released, so might need to just add a few patches or use a development version

**Comment by dyfer** [comment]
@bramtayl AFAICT it doesn't seem like your problem is related to the one I reported. My problem occurs at the configuration stage, and only when cross-compiling into "fat" binaries on macos on x86_64 host.

**Comment by bramtayl** [comment]
Yeah maybe. I bet both would be fixed by packaging a more recent version though

**Comment by bramtayl** [comment]
Maybe https://sourceforge.net/p/lame/svn/6505/?

**Comment by dyfer** [comment]
To clarify: the original issue is still not solved.
