### ISSUE TITLE
7zip Please include 7z.h in the distribution for C developers

### ISSUE THREAD

**Issue by fgimian** [microsoft/vcpkg#27553]
**Is your feature request related to a problem? Please describe.**
The main C header file `7z.h` for 7-Zip is missing which makes it impossible to use the vcpkg package on C projects.

This header file includes the primary functions used to interact with the library in C, such as:

- SzArEx_Init
- SzArEx_Free
- SzArEx_Open
- SzArEx_Extract

**Proposed solution**
Please include `include\7zip\C\7z.h` in the distribution 😄 

**Describe alternatives you've considered**
I don't really have a workaround for this sadly.

**Additional context**
N/A

**Comment by FrankXie05** [comment]
@fgimian `7zip` headers are provided by upstream, https://github.com/microsoft/vcpkg/blob/5220969a9f4fd1d7800eade0b25c5c2b5189c3b1/ports/7zip/CMakeLists.txt#L401
https://github.com/microsoft/vcpkg/blob/253704407ae68efa37bf8f5b59b3e06dd40d3d3f/ports/7zip/portfile.cmake#L14
you can ask upstream if this header is publicly installable. :)
https://sourceforge.net/p/sevenzip/discussion/

**Comment by dg0yt** [comment]
@FrankXie05 You are pointing to vcpkg's vendored build system for 7zip, so the bug and maintenance burden is clearly in vcpkg, not upstream.

**Comment by FrankXie05** [comment]
@dg0yt Sorry, I got it wrong. i will fix this.

**Comment by fgimian** [comment]
> @dg0yt Sorry, I got it wrong. i will fix this.

Thank you so much for your help 😄
