### ISSUE TITLE
[zlib] Build error Include '[zlib] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.

### ISSUE THREAD

**Issue by 417900229** [microsoft/vcpkg#27560]
**Host Environment**

- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**

`./vcpkg install xxxx`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please provide your environment information and the error log.

**Comment by LilyWangLL** [comment]
Please reopen this issue if this is still a problem for you.
