### ISSUE TITLE
[assimp] Missing AssetHandler.h missing in installed include directory

### ISSUE THREAD

**Issue by runarundheim** [microsoft/vcpkg#27567]
The assimp library has a new AssertHandler.h file that should be part of the header files in the include folder after build. 
This file is not very important and it is possible to just copy it manually from the src directory, so this is not a big issue.

**Comment by MonicaLiu0311** [comment]
>The assimp library has a new AssertHandler.h file

I didn't find this file upstream, can you send me the link to the file?

**Comment by runarundheim** [comment]
I found the file here: vcpkg\buildtrees\assimp\src\v5.2.5-5480fca19f.clean\code\Common
I see the file have dll interface, but this file is does not exist where the other include files exist. So I should have reported this directly to the assimp team.

**Comment by MonicaLiu0311** [comment]
You can report this problem to the upstream first, and we will wait for the upstream reply.

**Comment by MonicaLiu0311** [comment]
Related: https://github.com/assimp/assimp/issues/4779, waiting for upstream changes.

**Comment by rundheim** [comment]
Thanks for looking into this issue @MonicaLiu0311. I think we can close this report and wait for assimp to fix it in the library. It is only used for debug build. Default handler will break the program on import on some 3d files with error in it. I want to override the handling to just inform with a message and continue execution. It is enough with only this file, but I just added the file into my local code where it is used, so I think that a patch is not needed on this.

**Comment by MonicaLiu0311** [comment]
Thank you for your answer, this issue will be closed.
