### ISSUE TITLE
[glib] build failure in Alpine

### ISSUE THREAD

**Issue by illera88** [microsoft/vcpkg#27566]
Package: glib[core]:x64-linux -> 2.74.0

**Host Environment**

- Host: x64-linux
- Compiler: GNU 10.3.1
-    vcpkg-tool version: 2999-12-31-unknownhash
    vcpkg-scripts version: c72cefb25 2022-10-26 (4 days ago)

**To Reproduce**

`VCPKG_FORCE_SYSTEM_BINARIES=1 vcpkg install glib`

**Failure logs**

```
-- Using cached glib-2.74.0.tar.xz.
-- Extracting source /home/default/code/vcpkg/downloads/glib-2.74.0.tar.xz
-- Applying patch use-libiconv-on-windows.patch
-- Applying patch libintl.patch
-- Using source at /home/default/code/vcpkg/buildtrees/glib/src/glib-2-22354247da.clean
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Configuring x64-linux-dbg
-- Configuring x64-linux-dbg done
-- Configuring x64-linux-rel
-- Configuring x64-linux-rel done
-- Package x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: /home/default/code/vcpkg/downloads/tools/ninja/1.10.2-linux/ninja install -v
    Working Directory: /home/default/code/vcpkg/buildtrees/glib/x64-linux-dbg
    Error code: No such file or directory
    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
  ports/glib/portfile.cmake:47 (vcpkg_install_meson)
  scripts/ports.cmake:147 (include)



```

**Additional context**
Seems related with the `ninja` version downloaded by `vcpkg`:

```
DESKTOP-BABMP59:~/code/vcpkg$ /home/default/code/vcpkg/downloads/tools/ninja/1.10.2-linux/ninja --version
-ash: /home/default/code/vcpkg/downloads/tools/ninja/1.10.2-linux/ninja: not found
DESKTOP-BABMP59:~/code/vcpkg$ ldd /home/default/code/vcpkg/downloads/tools/ninja/1.10.2-linux/ninja
        /lib64/ld-linux-x86-64.so.2 (0x7f5209988000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7f52097e7000)
        libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f5209988000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f52097cd000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f5209988000)
```

**Comment by illera88** [comment]
Indeed the problem is that the vcpkg ninja version is not statically compiled and uses libc so it doesn't work under alpine (uses musl). The solution would be to use statically compiled versions for cmake and ninja.

**Comment by dg0yt** [comment]
> `VCPKG_FORCE_SYSTEM_BINARIES=1 vcpkg install glib`

You tell vcpkg that your system provides `ninja` but it doesn't.

**Comment by illera88** [comment]
I had Ninja but it wasn't the expected version to build. When that was detected vcpkg downloaded a built ninja version but that version was not statically compiled so it couldn't run. Having vcpkg using statically compiled version of cmake and ninja would fix this problem.

**Comment by illera88** [comment]
I'm gonna close this ticket but my recommendation would be for vcpkg to use a statically compiled version of cmake so it will work in every Linux distro
