### ISSUE TITLE
[New Port Request] mariadb-connector-cpp

### ISSUE THREAD

**Issue by indygan** [microsoft/vcpkg#27571]
Library name: mariadb-connector-cpp

Library description: connector/c++ for MariaDB.

Source repository URL:https://github.com/mariadb-corporation/mariadb-connector-cpp

Project homepage (if different from the source repository): https://mariadb.com/docs/connect/programming-languages/cpp/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by rinechran** [comment]
I'll work on that library.

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
