### ISSUE TITLE
How do I make vcpkg use the pre-installed Qt library instead of building it?

### ISSUE THREAD

**Issue by SineStriker** [microsoft/vcpkg#27574]
I have installed the Qt 5.15.2 via Qt official installer, and it's at the root path of drive C.

When I want to use vcpkg to install a library which depends on Qt, vcpkg will download and build qt-base first. How to let vcpkg know that there's an existing Qt library and use it.

**Comment by Osyotr** [comment]
https://devblogs.microsoft.com/cppblog/using-system-package-manager-dependencies-with-vcpkg/#using-curl-and-openssl-from-the-system-package-manager

**Comment by SineStriker** [comment]
Thanks, but it's not over. I add an simple `vcpkg.json` and `portfile.cmake` into a custom directory and pass it as overlay-ports to `vcpkg install` command, and then cmake cannot find Qt5Config.cmake...

How to pass an env such as `Qt5_DIR` to cmake via `portfile.cmake`?

**Comment by Osyotr** [comment]
https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md#vcpkg_env_passthrough_untracked

**Comment by SineStriker** [comment]
> https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md#vcpkg_env_passthrough_untracked

Thanks so much.

**Comment by SineStriker** [comment]
````
set(ENV{Qt5_DIR} "/path/to/"
````
I think this is better.

**Comment by LilyWangLL** [comment]
Thanks for Osyotr's help. Since this issue has been resolved, so I am closing this issue for now.

**Comment by rockydut** [comment]
Can you list detailed implementation steps? QT is already installed, and external QT is used in vcpkg instead of recompilation.
My system is windows.

**Comment by rockydut** [comment]
@LilyWangLL Can you list detailed implementation steps? QT is already installed, and external QT is used in vcpkg instead of recompilation.
My system is windows.

**Comment by Joker2387089590** [comment]
> Can you list detailed implementation steps? QT is already installed, and external QT is used in vcpkg instead of recompilation. My system is windows.

You can try this in cmd: 
```
set QT5_DIR=C:/path/to/qt/msvc
cmake -DCMAKE_TOOLCHAIN_FILE=.../vcpkg.cmake ...
`
