### ISSUE TITLE
[opencv] How to use pkg-config (or is it possible)?

### ISSUE THREAD

**Issue by Cpt-Squirrell** [microsoft/vcpkg#27570]
I am trying to link to OpenCV through vcpkg using pkg-config. Is this possible?
I am getting a lot of undefined references from `/vcpkg/buildtrees/opencv4/src/4.6.0-9a95a1b699.clean/modules/imgproc/src/templmatch.cpp`, coming in particular from `/imgproc/src/templmatch.cpp`; it looks like it's compiling/ linking source code from vcpkg itself even though I'm linking to static libs. Amongst many other, It's undefined to `cv::Mat` and `cv::softdouble`.
I am using a `.pc` file I quickly made myself (using another package's file as template).
My `opencv.pc` file looks as following:
```
prefix=${pcfiledir}/../..

exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${exec_prefix}/lib

Version: 4.6.0
Name: OpenCV
Description: OpenCV Computer Vision library.
Libs: -L"${libdir}" -lopencv_ml4 -lopencv_dnn4 -lopencv_core4 -lopencv_flann4 -lopencv_photo4 -lopencv_video4 -lopencv_calib3d4 -lopencv_highgui4 -lopencv_imgproc4 -lopencv_videoio4 -lopencv_imgcodecs4 -lopencv_objdetect4 -lopencv_stitching4 -lopencv_features2d4
Cflags: -I"${includedir}"
```
I very much despise CMake so any help is appreciated, thanks! :)

**Comment by autoantwort** [comment]
See https://github.com/opencv/opencv/issues/13154

**Comment by Cpt-Squirrell** [comment]
> See [opencv/opencv#13154](https://github.com/opencv/opencv/issues/13154)

This thread is what sparked me to create this, actually!
If what it says there is true, how would one go about installing the package with pkg-config, since it obviously isn't by default included.

**Comment by autoantwort** [comment]
You can write an overlay port and enable this feature

**Comment by Cpt-Squirrell** [comment]
What's an overlay port?

**Comment by autoantwort** [comment]
https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md

**Comment by Cpt-Squirrell** [comment]
> https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md

Many thanks!
I do think that pkg-config files should just be standard for all packages out of courtesy.
It's not a particularly intensive demand I believe. Many people don't want to or can't use CMake.

**Comment by dg0yt** [comment]
> I do think that pkg-config files should just be standard for all packages out of courtesy.
> It's not a particularly intensive demand I believe

It is intensive. In particular if upstreams
- don't care for it at all,
- don't care for proper static linkage requirments,
- don't care for MSVC,

maintenance burden is on vcpkg contributors.
But situation is improving nevertheless. E.g. https://github.com/microsoft/vcpkg/pull/23898
