### ISSUE TITLE
[poco] Build error

### ISSUE THREAD

**Issue by harry123-sudo** [microsoft/vcpkg#27578]
error: building poco:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.

**Host Environment**-x64

- OS: [ Windows]
- Compiler: revision

**To Reproduce**

`./vcpkg install poco[netssl]  poco[netssl]:x64-windows --recurse`

**Failure logs**
error: building poco:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**
[issue_body.md](https://github.com/microsoft/vcpkg/files/9907761/issue_body.md)

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by harry123-sudo** [comment]
[config-x64-windows-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/9907964/config-x64-windows-CMakeCache.txt.log)
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/9907965/config-x64-windows-out.log)

these are logs for errors. I am unable to understand anything..please help me out

**Comment by LilyWangLL** [comment]
This error should install `openssl` before installing `poco[netssl]`, the same issue https://github.com/microsoft/vcpkg/issues/25723. This change is from PR https://github.com/microsoft/vcpkg/pull/16526, I will confirm this is a port bug or not soon.

**Comment by LilyWangLL** [comment]
@harry123-sudo Thomas has submitted a PR to fix this issue, could you test PR #27582 resolve this issue?
