### ISSUE TITLE
How to integrate a part of library?

### ISSUE THREAD

**Issue by zzandyc** [microsoft/vcpkg#27576]
I have installed many libraries locally,but I only want to integrate some of the libraries used into the project,what should I do?

**Comment by dg0yt** [comment]
> I think you could use the manifest mode.

No matter which mode you use: As soon as vcpkg would install a library which you also installed as a local library, you must use overlay ports or use registries to replace ports in vcpkg, in order to avoid incompatible implementations for the same symbol.

**Comment by Cheney-W** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
