### ISSUE TITLE
Error: Building package boost-build:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Andrey1394** [Microsoft/vcpkg#2757]
Package: boost-build:x86-windows
  Vcpkg version: 0.0.104-2018-02-07-d503a55412b3fa1b2b96ae0719286ee593f3d732

Starting package 1/111: boost-build:x86-windows
Building package boost-build[core]:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/projects/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/projects/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/projects/vcpkg/packages/boost-build_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/projects/vcpkg/buildtrees/boost-build
-- CURRENT_PORT_DIR=C:/projects/vcpkg/ports/boost-build/.
-- Using cached C:/projects/vcpkg/downloads/boostorg-build-boost-1.66.0.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Using cached C:/projects/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Using cached C:/projects/vcpkg/downloads/boost-1.66.0-boostcpp.jam
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Bootstrapping...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: C:/projects/vcpkg/packages/boost-build_x86-windows/tools/boost-build/bootstrap.bat;msvc
    Working Directory: C:/projects/vcpkg/packages/boost-build_x86-windows/tools/boost-build
    See logs for more information:
      C:\projects\vcpkg\buildtrees\boost-build\bootstrap-x86-windows-out.log
      C:\projects\vcpkg\buildtrees\boost-build\bootstrap-x86-windows-err.log

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:47 (vcpkg_execute_required_process)
  scripts/ports.cmake:72 (include)

Error: Building package boost-build:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-build:x86-windows
  Vcpkg version: 0.0.104-2018-02-07-d503a55412b3fa1b2b96ae0719286ee593f3d732

Additionally, attach any relevant sections from the log files above.

**Comment by R2RT** [comment]
Hey, can you attach files, please?
C:\projects\vcpkg\buildtrees\boost-build\bootstrap-x86-windows-out.log
C:\projects\vcpkg\buildtrees\boost-build\bootstrap-x86-windows-err.log

**Comment by catg0tfish** [comment]
I have same error.
bootstrap-x86-windows-err.log
`command line error D8000 :cl: command line error D8000 :cl: command line error D8000 :cl: command line error D8000 :cl: command line error D8000 :cl: command line error D8000 :cl: command line error D8000 :cl: command line error D8000 :cl: command line error D8000 :cl: command line error D8000 :cl: command line error D8000 :cl: command line error D8000 :cl: command line error D8000 :cl: command line error D8000 :cl: command line error D8000 :cl: command line error D8000 :cl: command line error D8000 :cl: command line error D8000 :cl: command line error D8000 :cl: command line error D8000 :cl: command line error D8000 :cl: command line error D8000 :cl: command line error D8000 :cl: command line error D8000 :cl: command line error D8000 
“C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64_x86\cl.exe” Internal compiler error`
build\bootstrap-x86-windows-out.log
`Bootstrapping the build engine

Failed to bootstrap the build engine
Please consult bootstrap.log for furter diagnostics.
`

**Comment by richard-bmc** [comment]
I have the same error, and there're lots of "error D8000" in the bootstrap-x86-windows-err.log.

**Comment by NancyLi1013** [comment]
Hi @Andrey1394 , thanks for posting this issue. It should be fixed now. And I can install it successfully on my machine. Please open a new issue if this is still a problem for you.
