### ISSUE TITLE
Error: Building package zlib:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Andrey1394** [Microsoft/vcpkg#2758]
C:\projects\vcpkg>vcpkg.exe install grpc
The following packages will be built and installed:
  * c-ares[core]:x86-windows
    grpc[core]:x86-windows
  * openssl[core]:x86-windows
  * protobuf[core]:x86-windows
  * zlib[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/5: zlib:x86-windows
Building package zlib[core]:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/projects/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/projects/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/projects/vcpkg/packages/zlib_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/projects/vcpkg/buildtrees/zlib
-- CURRENT_PORT_DIR=C:/projects/vcpkg/ports/zlib/.
-- Using cached C:/projects/vcpkg/downloads/zlib1211.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch C:/projects/vcpkg/ports/zlib/cmake_dont_build_more_than_needed.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/projects/vcpkg/ports/zlib/cmake_dont_build_more_than_needed.patch done
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: C:/projects/vcpkg/buildtrees/zlib/x86-windows-rel/vcpkg-parallel-configure
    See logs for more information:
      C:\projects\vcpkg\buildtrees\zlib\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:243 (vcpkg_execute_required_process)
  ports/zlib/portfile.cmake:16 (vcpkg_configure_cmake)
  scripts/ports.cmake:72 (include)

Error: Building package zlib:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x86-windows
  Vcpkg version: 0.0.104-2018-02-07-d503a55412b3fa1b2b96ae0719286ee593f3d732

**Comment by diegoferigo** [comment]
Just faced the same error while building `opencv[core]:x64-windows`. Solved with:

```
choco install ninja
```

**Comment by ras0219-msft** [comment]
Thanks for posting this issue!

Can you please post the error log:
>C:\projects\vcpkg\buildtrees\zlib\config-x86-windows-out.log

**Comment by brucejee** [comment]
I also run into this [error](https://github.com/Microsoft/vcpkg/issues/2985), and i uninstall cmake 3.11 and reinstall cmake 3.10.2, It's ok now.
You can see this issue, may help you.

**Comment by NancyLi1013** [comment]
Please open a new issue if this is still a problem for you.
