### ISSUE TITLE
[REQUEST] nayuki/QR-Code-generator

### ISSUE THREAD

**Issue by kirillkovalenko** [microsoft/vcpkg#2759]
Please add QR code generation library by naruki
https://github.com/nayuki/QR-Code-generator

**Comment by cmpute** [comment]
Makefile may be hard to check in

**Comment by miurahr** [comment]
> Makefile may be hard to check in

There are two examples to handle the issue.

1. Call nmake if project has makefile.vc

2. Add CMakeLists.txt for the project

The project mentioned is simple enough to create  CMakeLists.txt for C/C++ sources.

@cmpute You can find an example here https://github.com/miurahr/vcpkg/blob/rasterlite2/ports/librasterlite2/add-cmakefiles.patch
 that is a working in progress project to port configure/makefile based project to vcpkg with CMake.

Fortunately QR-Code-generator is a simple Makefile project, that does not require configure.cmake/config.h.cmake.in hack.

**Comment by miurahr** [comment]
How is this basic `<project-root>/CMakeLists.txt`?
```
cmake_minimum_required(VERSION 3.0)
project(QR-Code-generator C CXX)
option(BUILD_SHARED_LIBS "Set ON to build shared library" ON)
set(CSOURCES c/qrcodegen.c)
add_library(qrcodegen-c ${CSOURCES})
target_include_directories(qrcodegen-c PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/c)
set_target_properties(qrcodegen-c PROPERTIES   OUTPUT_NAME qrcodegen PREFIX "")
set(CPPSOURCES cpp/BitBuffer.cpp cpp/QrCode.cpp cpp/QrSegment.cpp)
add_library(qrcodegen-cpp ${CPPSOURCES})
target_include_directories(qrcodegen-cpp PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/cpp)
set_target_properties(qrcodegen-cpp PROPERTIES OUTPUT_NAME qrcodegen PREFIX "")
install(TARGETS qrcodegen-c  RUNTIME DESTINATION bin  ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
install(TARGETS qrcodegen-cpp RUNTIME DESTINATION bin ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
```

It generates  only libs, vcpkg ports can handle static/dynamic by `-DBUILD_SHARED_LIBS=ON/OFF`

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
