### ISSUE TITLE
[New Port Request] libphonenumber

### ISSUE THREAD

**Issue by trishvl** [microsoft/vcpkg#27595]
Library name: libphonenumber

Library description: Google's common Java, C++ and JavaScript library for parsing, formatting, and validating international phone numbers.

Source repository URL: https://github.com/google/libphonenumber

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by autoantwort** [comment]
Can be closed.

**Comment by FrankXie05** [comment]
Fixed by PR https://github.com/microsoft/vcpkg/pull/28093/
