### ISSUE TITLE
Installing vcpkg hides standard library includes?

### ISSUE THREAD

**Issue by TNT0305** [Microsoft/vcpkg#2760]
Hello,

I found vcpkg and thought this would be great for both boost and tbb.  So, with all instances of VS closed, I followed the instructions and installed vcpkg.  I then installed tbb.  I then went into visual studio and tried to "Full Rebuild" the project I was working on.  I got several errors of the "'string': undeclared identifier" variety.  I then created a new console application with the following as the code:

```
#include <string>
#include <iostream>
#include "stdafx.h"

using namespace std;

int main()
{
	string q;
	q = "test";

	std::cout << q << std::endl;
    return 0;
}

```
From this, I still get the "string: undeclared identifier" error as well as "cout is not a member of 'std'"

It appears that VS2017 cannot find its own include paths now.  I verified the various macros used in the "VC Directories" settings and the correct include paths are present (namely: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.12.25827\include")

Has this error happened to anyone else?

Also, I removed vcpkg (delete the directory as the instructions I read indicated) and I still fail to compile the simple "test" console app.

Any guidance toward resolving my issue would be appreciated.  

Thanks!

**Comment by TNT0305** [comment]
Well, I fiddled with it for a bit and reset the include paths to the original default and it seems to be working.  I ran into some issues around precompiled headers (which may have been the source of my entire problem).  I'm closing this issue as I've managed to get my build working.  However, because merely installing vcpkg and running integrate install broke a previously working project, I think *something* might be a little wonky.  

That said, now that I have it compiling again, I was able to install tbb using vcpkg and my project picked it right up and compiles.  So, hopefully, my initial experience was just me doing something stupid without realizing it.

Cheers!

**Comment by MikeGitb** [comment]
Afaik, `"stdafx.h"` has to be the first include in any file that includes it. So yes, your problem is most likely related to precomputed headers. But may I ask, which library from vcpkg you are actually including?

**Comment by TNT0305** [comment]
Actually, in the little test app I included in my post, I wasn't including
anything provided via vcpkg.  But, in that one, moving the stdafx.h ahead
of all the other includes allowed it to compile.  In my real project, I'm
including tbb.  I've got it working now with that.

For that, my main thing is C++/CLI dll that's using the tbb.  The tbb.dll
(or tbb_debug.dll) *is* automatically copied to the target directory of my
dll's project.  However, in my test exe, which references my C++/CLI dll, I
have to manually copy the dll to the exe's target directory.  I'm not sure
how vcpkg could possibly automate that (as its a downstream issue), but I
thought I'd bring it up.

FWIW, here's the top of one of my files that is compiling properly, now:
#pragma once

#include <string>
#include <iostream>
#include <fstream>
#include <memory>
#include <vector>
#include <unordered_map>
#include <set>

#include "DistCost.h"
#include "TurnCostManager.h"
#include "CostArray.h"
#include "SpinLock.h"
#include "lock_guard.h"
#include "serialize.h"

#include "tbb/tbb.h"
#define TBB_PREVIEW_CONCURRENT_LRU_CACHE 1
#include "tbb/concurrent_lru_cache.h"

#include "stdafx.h"

using namespace std;


As you can see, I have the #include "stdafx.h" at the bottom of the include
list.

Once i keyed on the "precompiled header crap is probably the cause of
this", I went and verified that all .cpp files where set to "Use", the
stdafx.cpp was set to "Create", and .cpp files compiled with /clr were set
to "not using precompiled headers", everything compiled again.

I hope this helps.  If you need me to try to work up an example project
mimicking my original situation, I can try to do that this weekend.  I
really dig the notion of a C++ package manager, though.  In windows dev,
its always been a pain.

Take care,
Troy
