### ISSUE TITLE
[mlpack] update to 4.0.0

### ISSUE THREAD

**Issue by rcurtin** [microsoft/vcpkg#27616]
Library name: mlpack

New version number: 4.0.0

Other information that may be useful (release notes, etc...):

 * the library is now header-only, so this should simplify the build process a good bit; no more need to link anything against mlpack.dll or similar
 * Boost is no longer a necessary dependency; it has been replaced with cereal (a header-only serialization library)

Happy to help out if there are any problems!  I saw @PhoebeHui did the last package update.

**Comment by Blakjak88** [comment]
Any progress on this?

**Comment by MonicaLiu0311** [comment]
@rcurtin 
I had a problem with testing usage, when building it pointed to a path that I didn't find in source, see:
![Screenshot 2022-11-08 181919](https://user-images.githubusercontent.com/110024546/200539632-c618e314-7179-48bb-a032-1992387de3c8.png)

**Comment by rcurtin** [comment]
@MonicaLiu0311 ah, there is now the new dependency of cereal: https://github.com/USCILab/cereal/.  You will need to either let CMake find it, or you can specify `CEREAL_INCLUDE_DIR` in the CMake configuration. :+1:

**Comment by MonicaLiu0311** [comment]
@rcurtin 
Because vcpkg has [the port of cereal](https://github.com/microsoft/vcpkg/blob/master/ports/cereal/portfile.cmake), I added `cereal` to the `dependencies` of `vcpkg.json` to solve this problem.
Here's another problem with the build:
![Screenshot 2022-11-09 104617](https://user-images.githubusercontent.com/110024546/200725041-7ab33589-8c99-4b79-b490-27ed98a4ba5e.png)

Details:
[ErrorList.txt](https://github.com/microsoft/vcpkg/files/9966866/ErrorList.txt)
[Output.txt](https://github.com/microsoft/vcpkg/files/9966875/Output.txt)

**Comment by rcurtin** [comment]
Yes, I saw this one in the various MSVC builds I have done... try setting the C++ standard to C++17.  You can do this by either patching `CMakeLists.txt` line 110 to be `set(CMAKE_CXX_STANDARD 17)`, or I think you can specify `/std:c++17` in `CMAKE_CXX_FLAGS` or something like that.  There will be an upstream patch to handle this for version 4.0.1.

**Comment by MonicaLiu0311** [comment]
Since it's a header-only library, just do this when testing: Copy your `mlpack/src/` folder as a whole to the `vcpkg/installed/x86-windows/include/` path, then include the path of the header file in the test case and build.

> Yes, I saw this one in the various MSVC builds I have done... try setting the C++ standard to C++17. You can do this by either patching `CMakeLists.txt` line 110 to be `set(CMAKE_CXX_STANDARD 17)`, or I think you can specify `/std:c++17` in `CMAKE_CXX_FLAGS` or something like that. 

I also tried your suggestion, but still the same.

>There will be an upstream patch to handle this for version 4.0.1.

Is it convenient to tell the upstream patch release time? We can consider updating directly to 4.0.1.

**Comment by rcurtin** [comment]
Can you tell me more about how you built mlpack?  I went looking, and realized that our CMake configuration should automatically set the C++ standard to C++17, so I am not sure what is happening in your case.

The release date for mlpack 4.0.1 isn't clear yet, and honestly I would prefer to figure out how to fix this case first, so that any patches that are needed here can be incorporated into that release. :)

**Comment by MonicaLiu0311** [comment]
Tried multiple times still the same error.
(I didn't study your port, just wanted to make sure it's available when including header files.)

For modification of portfile.ckame and vcpkg.json, see: https://github.com/microsoft/vcpkg/pull/27707/files.

The cmake project code is as follows:
![settting](https://user-images.githubusercontent.com/110024546/201617024-bcb636b8-3785-47ba-aa95-9f5a2d924cf1.png)
![cmakelists](https://user-images.githubusercontent.com/110024546/201616812-6b4e2634-bdb1-46a9-905c-822359a8d097.png)
![cpp](https://user-images.githubusercontent.com/110024546/201616806-b90f05f0-c4ea-4a88-9295-e3fa25361ca9.png)
![error](https://user-images.githubusercontent.com/110024546/201617590-fe635b69-caa3-43b7-9a19-e754108a5b38.png)

[ErrorList.txt](https://github.com/microsoft/vcpkg/files/10001307/ErrorList.txt)
[Output.txt](https://github.com/microsoft/vcpkg/files/10001308/Output.txt)

**Comment by rcurtin** [comment]
@MonicaLiu0311 thanks for the output!  Can you try adding this patch to mlpack?
https://gist.github.com/ed62ba9ea60b780b3bac5773f08ca852

Then you should get an error that indicates that mlpack programs need to be compiled with `/Zc:__cplusplus` and `/std:c++17`, and if you set those options, then the test program should compile fine.

(Technically the patch is only to give a better error message.  You should be able to specify `/Zc:__cplusplus` and `/std:c++17` for your test program in the compilation options and that should work too.)

**Comment by MonicaLiu0311** [comment]
@rcurtin 
Thanks for your reply. The build was successful by your method (but I think this method is temporary).

If you agree, I will follow [this PR](https://github.com/microsoft/vcpkg/pull/27707) to update the new version - 4.0.0, do you agree?
(But other users in the same situation as me also need to solve the problem through this method)

I think you may need to make an official explanation for version 4.0.0, what do you think?

**Comment by rcurtin** [comment]
Awesome, glad it worked!  The PR looks good to me.

Where would the right place for the official explanation be?  I'll be incorporating the patch I gave you into mlpack upstream, and version 4.0.1 will come with a release note that for MSVC we must use the compiler flags above.

**Comment by MonicaLiu0311** [comment]
>I'll be incorporating the patch I gave you into mlpack upstream,

Ok, I will submit [this PR](https://github.com/microsoft/vcpkg/pull/27707) after you merge [this patch](https://gist.github.com/ed62ba9ea60b780b3bac5773f08ca852).

>and version 4.0.1 will come with a release note that for MSVC we must use the compiler flags above.

Yep, that's what I want the official description to be seen by someone learning your library.
(just a small suggestion)

**Comment by rcurtin** [comment]
Sounds good---the patch is open in mlpack/mlpack#3318.  I updated the documentation and HISTORY.md too; please feel free to leave any comments if you like. :+1:

**Comment by MonicaLiu0311** [comment]
> Sounds good---the patch is open in [mlpack/mlpack#3318](https://github.com/mlpack/mlpack/pull/3318). I updated the documentation and HISTORY.md too; please feel free to leave any comments if you like. 👍

In view of the relatively long time for this [PR](https://github.com/microsoft/vcpkg/pull/27707), I will add the patch to vcpkg first, and then remove it when you update the next version (by then you will probably have merged the patch).

**Comment by rcurtin** [comment]
Yep, that sounds great! :+1:
