### ISSUE TITLE
[glib] build failure (Command failed: ninja install -v)

### ISSUE THREAD

**Issue by Cpt-Squirrell** [microsoft/vcpkg#27613]
**Host Environment**

- OS: Linux (Ubuntu)

**To Reproduce**

`./vcpkg install glib`

**Failure logs**
From `buildtrees/glib/package-x64-linux-dbg-out.log` (snipped):
```
[ . . . ]
FAILED: gio/kqueue/libkqueue.a.p/gkqueuefilemonitor.c.o 
/usr/bin/cc -Igio/kqueue/libkqueue.a.p -Igio/kqueue -I../src/glib-2-596f37cc56.clean/gio/kqueue -I. -I../src/glib-2-596f37cc56.clean -Iglib -I../src/glib-2-596f37cc56.clean/glib -Igmodule -I../src/glib-2-596f37cc56.clean/gmodule -Igio -Igobject -Ivcpkg/installed/x64-linux/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=gnu99 -O0 -g -D_GNU_SOURCE -fno-strict-aliasing -DG_ENABLE_DEBUG -Wduplicated-branches -Wimplicit-fallthrough -Wmisleading-indentation -Wunused -Wno-unused-parameter -Wno-cast-function-type -Wno-pedantic -Wno-format-zero-length -Wno-variadic-macros -Werror=format=2 -Werror=init-self -Werror=missing-include-dirs -Werror=pointer-arith -Werror=unused-result -Wstrict-prototypes -Wno-bad-function-cast -Werror=declaration-after-statement -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=pointer-sign -fPIC -g -fPIC '-DG_LOG_DOMAIN="GLib-GIO"' -DGIO_COMPILATION '-DGIO_LAUNCH_DESKTOP="vcpkg/packages/glib_x64-linux/debug/libexec/gio-launch-desktop"' '-DGIO_MODULE_DIR="vcpkg/packages/glib_x64-linux/debug/lib/gio/modules"' '-DLOCALSTATEDIR="vcpkg/packages/glib_x64-linux/debug/var"' -MD -MQ gio/kqueue/libkqueue.a.p/gkqueuefilemonitor.c.o -MF gio/kqueue/libkqueue.a.p/gkqueuefilemonitor.c.o.d -o gio/kqueue/libkqueue.a.p/gkqueuefilemonitor.c.o -c ../src/glib-2-596f37cc56.clean/gio/kqueue/gkqueuefilemonitor.c
../src/glib-2-596f37cc56.clean/gio/kqueue/gkqueuefilemonitor.c:26:10: fatal error: sys/event.h: No such file or directory
   26 | #include <sys/event.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
[ . . . ]
ninja: build stopped: subcommand failed.
```

**Additional context**
OpenCV was installed and my VSCode IntelliSense was relying on its headers. I ran `git pull` and `vcpkg update`/ `vcpkg upgrade`; `upgrade` removed 90 or so packages and tried to reinstall a good few. This is when `glib` failed and I am now unable to use/ install OpenCV amongst others.
[This could be related](https://github.com/microsoft/vcpkg/issues/27566) however I have double checked that Ninja is installed (`sudo apt install ninja`).

I'm well aware that it's likely something that went wrong with my local setup but I have no idea what in that case.
Nothing changed since last time I ran `git pull`.

**Comment by Cpt-Squirrell** [comment]
How would I check for changes in features?
IntelliSense is at least not finding any `<sys/event.h>` (though is finding `eventfd.h`).

**Comment by dg0yt** [comment]
I would inspect the glib build system. The kqueue subdir is enabled here:
https://github.com/GNOME/glib/blob/0d425bc27643ce441db104be69ae55f796a11b01/gio/meson.build#L794-L798

**Comment by dg0yt** [comment]
And the controlling variables are set here:
https://github.com/GNOME/glib/blob/77180daca538ff9e139a7dfb5748c4d70f4e8b18/meson.build#L653-L662
Git blame says this hasn't changed in years.

AFAIU  `kqueue` is a system call on BSD only.  My `config-x64-linux-dbg-out.log` has:
~~~
Checking for function "kevent" : NO 
Checking for function "kqueue" : NO 
~~~
More details are logged in `config-x64-linux-dbg-meson-log.txt.log`.

**Comment by Cpt-Squirrell** [comment]
Eugh. This'll be for tomorrow. I'm not out of luck either way, I am linking to `apt`s OpenCV installation anyways. It's only intellisense which was using vcpkg's (for some reason). I still want this ironed out though, looks like it will affect much more than OpenCV.
