### ISSUE TITLE
Fix for High Risk OpenSSL Security Vulnerabilities Announced – Guidance for vcpkg Users

### ISSUE THREAD

**Issue by AugP** [microsoft/vcpkg#27622]
[OpenSSL.org announced the release of OpenSSL 3.0.7](https://www.openssl.org/blog/blog/2022/11/01/email-address-overflows/) to address two security vulnerabilities rated as high risk. This patch is now available, including via vcpkg. The vulnerabilities impact users of OpenSSL 3.0.0 – 3.0.6. If you are relying on a version of OpenSSL in this range, it is strongly recommended to upgrade to 3.0.7 as soon as possible.

If you are a vcpkg user or port author depending on the OpenSSL vcpkg port, see this blog post to learn how to upgrade to the new version: https://devblogs.microsoft.com/cppblog/fix-for-high-risk-openssl-security-vulnerabilities-announced-guidance-for-vcpkg-users/

**Comment by dg0yt** [comment]
Port openssl is at version 3.0.8 now. Can this be closed?

**Comment by LilyWangLL** [comment]
Since this issue has been fixed. So I am closing this issue for now.
