### ISSUE TITLE
[Poco] linking problem with Poco & expat

### ISSUE THREAD

**Issue by Beafantles** [microsoft/vcpkg#27658]
**Describe the bug**
When I try to link `Poco::XML` library to a project using CMake, I get the following error:

```
CMake Error at C:/Users/Seb/src/vcpkg/installed/x64-windows/share/poco/PocoXMLTargets.cmake:60 (set_target_properties):
  The link interface of target "Poco::XML" contains:

    EXPAT::EXPAT

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  C:/Users/Seb/src/vcpkg/installed/x64-windows/share/poco/PocoXMLConfig.cmake:10 (include)
  C:/Users/Seb/src/vcpkg/scripts/buildsystems/vcpkg.cmake:834 (_find_package)
  C:/Users/Seb/src/vcpkg/installed/x64-windows/share/poco/PocoConfig.cmake:35 (find_package)
  C:/Users/Seb/src/vcpkg/scripts/buildsystems/vcpkg.cmake:834 (_find_package)
  backend/diff-merge/CMakeLists.txt:6 (find_package)
```

It seems like the error is related to the installation of `expat`.

**Environment**
- OS: Windows 11
- Compiler: MSVC 19.33.31630.0

**To Reproduce**
1. ./vcpkg install poco:x64-windows
2. Use the following `CMakeLists.txt`:
```cmake
cmake_minimum_required(VERSION 3.12)

project(TEST)

find_package(Poco REQUIRED COMPONENTS XML)

add_executable(test ${CMAKE_CURRENT_SOURCE_DIR}/main.cpp)

target_link_libraries(test PRIVATE Poco::XML)
```
3. Invoke CMake to configure the project, with the vcpkg toolchain

**Expected behavior**
There should not be any problem configuring the project.

**Failure logs**
Here's the content of [CMakeOutput.log](https://github.com/microsoft/vcpkg/files/9937251/CMakeOutput.log).
There is no `CMakeError.log` file.

**Comment by Beafantles** [comment]
Update: I only get this problem when using the latest Poco version (1.12.4).
No problem with older versions, such as 1.11.2.

**Comment by Beafantles** [comment]
Has this issue been solved? It has been marked as if it was but I still have the same error with the latest version (1.12.4).
My vcpkg is up to date.

**Comment by Cheney-W** [comment]
I think this issue has been solved. Please reinstall the port with `--binarysource=clear` option.

**Comment by Cheney-W** [comment]
Don't forget run `git pull` to update the port file.

**Comment by Beafantles** [comment]
Thank you very much Cheney-W!
I wasn't aware of the `--binarysource=clear` option, it indeed did the trick! :D
Have a great day!
