### ISSUE TITLE
[New Port Request] AWS Encryption SDK for C

### ISSUE THREAD

**Issue by nickdademo** [microsoft/vcpkg#27654]
Library name: aws-encryption-sdk-c

Library description: The AWS Encryption SDK for C is a client-side encryption library designed to make it easy for everyone to encrypt and decrypt data using industry standards and best practices.

Source repository URL: https://github.com/aws/aws-encryption-sdk-c

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
