### ISSUE TITLE
[flann] Build x64-mingw-dynamic error

### ISSUE THREAD

**Issue by ZhongKang97** [microsoft/vcpkg#27669]
**Host Environment**

- OS: Windows
- Compiler: revision
 vcpkg-tool version: 2022-10-17-3247920fbdd47d08f36cbd480addd9890d3c2435
 vcpkg-scripts version: 68ad399d5 2022-11-04 (15 hours ago)

**To Reproduce**

`./vcpkg install flann:x64-mingw-dynamic

**Failure logs**

- Cut and paste the appropriate build messages from the console output.

CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: "D:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
    Working Directory: D:/CODEing/package_install/vcpkg/buildtrees/flann/x64-mingw-dynamic-dbg
    See logs for more information:
      D:\CODEing\package_install\vcpkg\buildtrees\flann\install-x64-mingw-dynamic-dbg-out.log

Call Stack (most recent call first):
  installed/x64-mingw-dynamic/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-mingw-dynamic/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/flann/portfile.cmake:34 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building flann:x64-mingw-dynamic failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+flann
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[flann]+Build+error
Include '[flann] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-10-17-3247920fbdd47d08f36cbd480addd9890d3c2435
    vcpkg-scripts version: 68ad399d5 2022-11-04 (15 hours ago)

- Attach ***every failure log file*** mentioned in the console output.
[1/5] D:\Qt\Qt5.14.2\Tools\mingw730_64\bin\x86_64-w64-mingw32-g++.exe -DFLANN_EXPORTS -D_FLANN_VERSION=1.9.1 -ID:/CODEing/package_install/vcpkg/buildtrees/flann/src/638c8c7d9d-421926f7bb.clean/src/cpp -isystem D:/CODEing/package_install/vcpkg/installed/x64-mingw-dynamic/include -g   -Wall -Wno-unknown-pragmas -Wno-unused-function -MD -MT src/cpp/CMakeFiles/flann_cpp.dir/flann/flann_cpp.cpp.obj -MF src\cpp\CMakeFiles\flann_cpp.dir\flann\flann_cpp.cpp.obj.d -o src/cpp/CMakeFiles/flann_cpp.dir/flann/flann_cpp.cpp.obj -c D:/CODEing/package_install/vcpkg/buildtrees/flann/src/638c8c7d9d-421926f7bb.clean/src/cpp/flann/flann_cpp.cpp
In file included from D:/CODEing/package_install/vcpkg/buildtrees/flann/src/638c8c7d9d-421926f7bb.clean/src/cpp/flann/util/params.h:33:0,
                 from D:/CODEing/package_install/vcpkg/buildtrees/flann/src/638c8c7d9d-421926f7bb.clean/src/cpp/flann/flann.hpp:42,
                 from D:/CODEing/package_install/vcpkg/buildtrees/flann/src/638c8c7d9d-421926f7bb.clean/src/cpp/flann/flann_cpp.cpp:30:
D:/CODEing/package_install/vcpkg/buildtrees/flann/src/638c8c7d9d-421926f7bb.clean/src/cpp/flann/util/any.h: In member function 'virtual void flann::anyimpl::big_any_policy<T>::static_delete(void**)':
D:/CODEing/package_install/vcpkg/buildtrees/flann/src/638c8c7d9d-421926f7bb.clean/src/cpp/flann/util/any.h:81:9: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
         if (* x) delete (* reinterpret_cast<T**>(x)); *x = NULL;
         ^~
D:/CODEing/package_install/vcpkg/buildtrees/flann/src/638c8c7d9d-421926f7bb.clean/src/cpp/flann/util/any.h:81:55: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
         if (* x) delete (* reinterpret_cast<T**>(x)); *x = NULL;
                                                       ^
[2/5] cmd.exe /C "cd . && D:\Qt\Qt5.14.2\Tools\mingw730_64\bin\x86_64-w64-mingw32-g++.exe -g   -shared -o lib\libflann_cppd.dll -Wl,--out-implib,lib\libflann_cppd.dll.a -Wl,--major-image-version,1,--minor-image-version,9 src/cpp/CMakeFiles/flann_cpp.dir/flann/flann_cpp.cpp.obj  D:/CODEing/package_install/vcpkg/installed/x64-mingw-dynamic/debug/lib/liblz4d.dll.a  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
[3/5] D:\Qt\Qt5.14.2\Tools\mingw730_64\bin\x86_64-w64-mingw32-g++.exe -DFLANN_EXPORTS -D_FLANN_VERSION=1.9.1 -ID:/CODEing/package_install/vcpkg/buildtrees/flann/src/638c8c7d9d-421926f7bb.clean/src/cpp -isystem D:/CODEing/package_install/vcpkg/installed/x64-mingw-dynamic/include -g   -Wall -Wno-unknown-pragmas -Wno-unused-function -MD -MT src/cpp/CMakeFiles/flann.dir/flann/flann.cpp.obj -MF src\cpp\CMakeFiles\flann.dir\flann\flann.cpp.obj.d -o src/cpp/CMakeFiles/flann.dir/flann/flann.cpp.obj -c D:/CODEing/package_install/vcpkg/buildtrees/flann/src/638c8c7d9d-421926f7bb.clean/src/cpp/flann/flann.cpp
FAILED: src/cpp/CMakeFiles/flann.dir/flann/flann.cpp.obj 
D:\Qt\Qt5.14.2\Tools\mingw730_64\bin\x86_64-w64-mingw32-g++.exe -DFLANN_EXPORTS -D_FLANN_VERSION=1.9.1 -ID:/CODEing/package_install/vcpkg/buildtrees/flann/src/638c8c7d9d-421926f7bb.clean/src/cpp -isystem D:/CODEing/package_install/vcpkg/installed/x64-mingw-dynamic/include -g   -Wall -Wno-unknown-pragmas -Wno-unused-function -MD -MT src/cpp/CMakeFiles/flann.dir/flann/flann.cpp.obj -MF src\cpp\CMakeFiles\flann.dir\flann\flann.cpp.obj.d -o src/cpp/CMakeFiles/flann.dir/flann/flann.cpp.obj -c D:/CODEing/package_install/vcpkg/buildtrees/flann/src/638c8c7d9d-421926f7bb.clean/src/cpp/flann/flann.cpp
In file included from D:/CODEing/package_install/vcpkg/buildtrees/flann/src/638c8c7d9d-421926f7bb.clean/src/cpp/flann/util/params.h:33:0,
                 from D:/CODEing/package_install/vcpkg/buildtrees/flann/src/638c8c7d9d-421926f7bb.clean/src/cpp/flann/flann.hpp:42,
                 from D:/CODEing/package_install/vcpkg/buildtrees/flann/src/638c8c7d9d-421926f7bb.clean/src/cpp/flann/flann.h:603,
                 from D:/CODEing/package_install/vcpkg/buildtrees/flann/src/638c8c7d9d-421926f7bb.clean/src/cpp/flann/flann.cpp:31:
D:/CODEing/package_install/vcpkg/buildtrees/flann/src/638c8c7d9d-421926f7bb.clean/src/cpp/flann/util/any.h: In member function 'virtual void flann::anyimpl::big_any_policy<T>::static_delete(void**)':
D:/CODEing/package_install/vcpkg/buildtrees/flann/src/638c8c7d9d-421926f7bb.clean/src/cpp/flann/util/any.h:81:9: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
         if (* x) delete (* reinterpret_cast<T**>(x)); *x = NULL;
         ^~
D:/CODEing/package_install/vcpkg/buildtrees/flann/src/638c8c7d9d-421926f7bb.clean/src/cpp/flann/util/any.h:81:55: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
         if (* x) delete (* reinterpret_cast<T**>(x)); *x = NULL;
                                                       ^
D:/Qt/Qt5.14.2/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/as.exe: src/cpp/CMakeFiles/flann.dir/flann/flann.cpp.obj: too many sections (144650)
C:\Users\ADMINI~1\AppData\Local\Temp\ccnSEPRS.s: Assembler messages:
C:\Users\ADMINI~1\AppData\Local\Temp\ccnSEPRS.s: Fatal error: can't write 610 bytes to section .text of src/cpp/CMakeFiles/flann.dir/flann/flann.cpp.obj: 'File too big'
D:/Qt/Qt5.14.2/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/as.exe: src/cpp/CMakeFiles/flann.dir/flann/flann.cpp.obj: too many sections (144650)
C:\Users\ADMINI~1\AppData\Local\Temp\ccnSEPRS.s: Fatal error: can't close src/cpp/CMakeFiles/flann.dir/flann/flann.cpp.obj: File too big
ninja: build stopped: subcommand failed.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Adela0814** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
