### ISSUE TITLE
[realsense2] Build error: Command failed: /usr/bin/cmake --build . --config Debug --target install -- -v -j6

### ISSUE THREAD

**Issue by fattysun1121** [microsoft/vcpkg#27664]
**Host Environment**

- OS: VM Ubuntu 22.04 running on Macbook Air (m2 chip)
- Compiler: terminal

**To Reproduce**

`./vcpkg install realsense2`

**Failure logs**

-- Building arm64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: /usr/bin/cmake --build . --config Debug --target install -- -v -j6
    Working Directory: /home/fattysun1121/vcpkg/buildtrees/realsense2/arm64-linux-dbg
    See logs for more information:
      /home/fattysun1121/vcpkg/buildtrees/realsense2/install-arm64-linux-dbg-out.log

Call Stack (most recent call first):
  installed/arm64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/arm64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/realsense2/portfile.cmake:47 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building realsense2:arm64-linux failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+realsense2
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[realsense2]+Build+error
Include '[realsense2] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2999-12-31-unknownhash
    vcpkg-scripts version: 68ad399d5 2022-11-04 (2 hours ago)

This is the log file:
[install-arm64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/9942530/install-arm64-linux-dbg-out.log)

**Additional Context**
I am trying to install realsense SDK. I made sure all the packages were up-to-date, ran git pull, ./vcpkg update and whatnot. At first I thought it was because cmake is using -j5 flag when I only assigned 4 cores to the VM. I switched that to 5 cores, but it also used -j6 this time.

**Comment by fattysun1121** [comment]
Switched to ubuntu 20.04 and installed librealsense 2 successfully

**Comment by Cheney-W** [comment]
Looks like this issue is an upstream issue: https://github.com/IntelRealSense/librealsense/issues/10439

**Comment by MonicaLiu0311** [comment]
This issue has not been updated in 3 months, and I found that `realsense2` has been upgraded to [2.53.1](https://github.com/microsoft/vcpkg/blob/master/ports/realsense2/vcpkg.json#L3), and the upstream has also solved related problems in the new version; so I will close this issue, if it is still an issue, please reopen it.
