### ISSUE TITLE
Compiling order: debug first

### ISSUE THREAD

**Issue by cmpute** [Microsoft/vcpkg#2767]
A little suggestion: when do `vcpkg install`, the building target order is `release`(rel) first, and then `debug`(dbg). To find possible compile or link errors more quickly, I would suggest build `debug` first, because it will take less time to encounter the error when target `debug`.

This would be convenient when one needs to add or edit a port file.

**Comment by jasjuang** [comment]
This is a good idea

**Comment by ras0219-msft** [comment]
I'd be happy to review a PR!

**Comment by cmpute** [comment]
It's quite depressed to founding that there are many other ports which don't use vcpkg_build_cmake and remain release-first... 😢
