### ISSUE TITLE
[expat] Build error

### ISSUE THREAD

**Issue by derreisende77** [microsoft/vcpkg#27674]
**Host Environment**

- OS: macOS Ventura
- Compiler: Apple clang version 14.0.0 (clang-1400.0.29.202)

package: expat[core]:arm64-osx -> 2.5.0
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: 68ad399d5 2022-11-04 (2 days ago)

**To Reproduce**

`vcpkg install expat`

**Failure logs**

```
Computing installation plan...
The following packages will be built and installed:
    expat[core]:arm64-osx -> 2.5.0
Detecting compiler hash for triplet arm64-osx...
Restored 0 packages from /Users/XXX/.cache/vcpkg/archives in 539.7 us. Use --debug to see more details.
Starting package 1/1: expat:arm64-osx
Building package expat[core]:arm64-osx...
-- Using community triplet arm64-osx. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /Users/XXX/vcpkg/triplets/community/arm64-osx.cmake
-- Using cached libexpat-libexpat-R_2_5_0.tar.gz.
-- Cleaning sources at /Users/XXX/vcpkg/buildtrees/expat/src/R_2_5_0-56671c0753.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/XXX/vcpkg/downloads/libexpat-libexpat-R_2_5_0.tar.gz
-- Using source at /Users/XXX/vcpkg/buildtrees/expat/src/R_2_5_0-56671c0753.clean
-- Found external ninja('1.11.1').
-- Configuring arm64-osx
-- Building arm64-osx-dbg
-- Building arm64-osx-rel
CMake Error at installed/arm64-osx/share/vcpkg-cmake-config/vcpkg_cmake_config_fixup.cmake:36 (message):

  '/Users/XXX/vcpkg/packages/expat_arm64-osx/debug/lib/cmake/expat-'
  does not exist.
Call Stack (most recent call first):
  ports/expat/portfile.cmake:24 (vcpkg_cmake_config_fixup)
  scripts/ports.cmake:147 (include)


error: building expat:arm64-osx failed with: BUILD_FAILED
```

**Comment by dg0yt** [comment]
https://github.com/microsoft/vcpkg/issues/27671#issuecomment-1304599345

**Comment by derreisende77** [comment]
We are talking about MacOS not windows. Vcpkg binary is installed via homebrew and up to date

**Comment by dg0yt** [comment]
I see. The line cut was misleading me: 
~~~
CMake Error at installed/arm64-osx/share/vcpkg-cmake-config/vcpkg_cmake_config_fixup.cmake:36 (message):

  '/Users/XXX/vcpkg/packages/expat_arm64-osx/debug/lib/cmake/expat-'
  does not exist.
~~~

**Comment by dg0yt** [comment]
> We are talking about MacOS not windows. Vcpkg binary is installed via homebrew and up to date

In fact it isn't, according to your report:

> vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb

You need at least 2022-10-12.

**Comment by derreisende77** [comment]
Yeah you are right. After manually updating it does now work. Didn´t know that one must update vcpkg manually even if installed via homebrew.

**Comment by dg0yt** [comment]
Well, the responsibility for the homebrew package is elsewhere. Basically, you should always use the tool version which matches the repo, and bootstrapping takes care of this.
On the vcpkg side, some port updates slipped in with a dependency on the new tool version without proper guarding. Patches pending in https://github.com/microsoft/vcpkg/pull/27598.
