### ISSUE TITLE
Integrate environment variable "PATH"

### ISSUE THREAD

**Issue by cmpute** [microsoft/vcpkg#2768]
This is a suggestion to add a command like `vcpkg integrate path`. The proposing command will add `<vcpkg>/installed/<triplet>/bin` to system `PATH`. Besides, the architecture can be specfied with `--triplet` argument.

This command will be useful in two cases:
1. Use tools build from packages like pcl/vtk/etc. The built tools are put under `/installed/<triplet>/tools`, which cannot link with the runtime libraries, so PATH modification is needed.
2. Softwares downloaded from Internet can take advantages of the runtime libraries if they need external libraries which can be installed with vcpkg.

**Comment by jasjuang** [comment]
There is a thorough discussion here https://github.com/Microsoft/vcpkg/issues/1435

I think this should be avoided.

**Comment by ras0219-msft** [comment]
While adding the `bin\` folder would have a lot of problems (detailed in the other thread), I think there might be an interesting point about adding `tools\` to the path. I don't think adding it to the _system_ path would be good, but adding it to the current path seems quite reasonable. If it's appending to the current path, this fixes any concerns with "what if another installer does X?"

>... which cannot link with the runtime libraries ...

If this is happening, it's actually a bug in the portfile! It should be calling `vcpkg_copy_tool_dependencies()` to get all needed dependency DLLs packaged into the tools directory. Please open an issue if you have any problems with it!

**Comment by cmpute** [comment]
Great! Adding `tools\` to current path is useful too!

**Comment by tenomoto** [comment]
It would be nice if more exe's were installed rather than deleted and available from PowerShell. I see potentials in vcpkg because of the design decision to use CMake and to follow FreeBSD's ports. Let's make vcpkg not just a build system for libraries, but the best package manager for Windows. BTW, I don't understand why `bin\` is for dll's and is needed in addition to `lib\`.

**Comment by cmpute** [comment]
I have a propose: 
add a command (like `vcpkg integrate open`) that opens another cmd/ps window which add `tools\` or even `bin\` into the prompt `PATH`. This behavior is similar to what `vcvarsall.bat` does.

**Comment by davegorst** [comment]
I'm thinking this would allow us to find, via a relative path, the location of the CMake buildtools file, once we've found vcpkg.exe on the PATH. This would make it easier to feed this in to the initial run of CMake from the commandline, and would make distributing source-only packages a lot easier.

**Comment by Swoorup** [comment]
In linux, this stuff just works (TM) with the exception of multitude of different dll versions

**Comment by NancyLi1013** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.

**Comment by kotx** [comment]
Has this been added?

**Comment by NancyLi1013** [comment]
No, it hasn't been implemented yet. If you are still interested in this feature, we can reopen this.

**Comment by kotx** [comment]
> If you are still interested in this feature, we can reopen this.
Sounds good.

**Comment by NancyLi1013** [comment]
Related issue #16445.
