### ISSUE TITLE
[boost-config:x64-windows] build failure

### ISSUE THREAD

**Issue by RainbowTaro2022** [microsoft/vcpkg#27698]
error: building boost-config:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-config
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-config]+Build+error
Include '[boost-config] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-10-17-3247920fbdd47d08f36cbd480addd9890d3c2435
    vcpkg-scripts version: 68ad399d5 2022-11-04 (3 days ago)

**Comment by RainbowTaro2022** [comment]
Why hasn't my problem been solved yet

**Comment by dg0yt** [comment]
I think you don't provide enough information to analyze your problem. (It doesn't seem to occur for others or here in CI.) Note the following text in vcpkg output:

> ... attach any relevant failure logs from above.

**Comment by RainbowTaro2022** [comment]
> I think you don't provide enough information to analyze your problem. (It doesn't seem to occur for others or here in CI.) Note the following text in vcpkg output:
> 
> > ... attach any relevant failure logs from above.

I have tried to add information, no more information

**Comment by Cheney-W** [comment]
Could you please provide the logs in `vcpkg\buildtrees\boost-config`?

**Comment by Cheney-W** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
