### ISSUE TITLE
[sentry-native] support different backends via feature flags

### ISSUE THREAD

**Issue by AudriusButkevicius** [microsoft/vcpkg#27696]
****

**Is your feature request related to a problem? Please describe.**

I only use sentry for generic event reporting, and don't need the crashpad machinery.

**Proposed solution**
Add feature flags for different backends, including "none" backend.

**Describe alternatives you've considered**
Compile myself, but its a headache as its using cmake where as my projects use msbuild.

**Comment by FrankXie05** [comment]
@AudriusButkevicius Am I understanding that you want to build `sentry-native` without any backend?
If yes, the function of port `sentry-native` is an error and crash reporting client for native applications, if without any backend it will lose its own functionality just for testing and not reporting.

**Comment by AudriusButkevicius** [comment]
Sentry is not just for crash reporting i.e. segfaults etc.

It can also be used for reporting caught but unexpected exceptions, or just general events from your code (i.e some unexpected branch hit), in which case all of the crashpad baggage is a lot of extra unnecessary machinery
