### ISSUE TITLE
Request: Update Botan to 2.4.0 and add feature packages

### ISSUE THREAD

**Issue by ghost** [Microsoft/vcpkg#2769]
Latest version of Botan is 2.4.0 from 8th January 2018 but current vcpkg version if from 9th January 2017...
Lots of fixes and all, would actually be good if we could get it up to date.

Would also be nice if you added feature packages, as Botan support compiler switches like `--enable-modules=zlib` or `--disable-modules=rc5,idea`. I for example only needs AES/RC4/OAEP/RSA but end up with a very big build because of all the not useful algorithms included in the binary.

Thanks in advance

**Comment by ras0219-msft** [comment]
We'd be happy to accept a PR!

**Comment by mardy** [comment]
I'll create a PR for botan 2.6.0, if no one has objections. :-)

**Comment by mardy** [comment]
Actually, I cannot sign the CLA. When I go to https://cla.opensource.microsoft.com/ there is nothing to sign. I try to sign in, and it redirects me to github.com; I accept the connection, but when it redirects me to the microsoft site, nothing happens: I'm still not signed in.

**Comment by wangli28** [comment]
Hi Everyone,
Latest version is 2.9.0, you can update vcpkg and rebuild.
Thanks.
