### ISSUE TITLE
Failed to install package with openssl dependency

### ISSUE THREAD

**Issue by AFOEK** [microsoft/vcpkg#27708]
**Host Environment**

- OS: Ubuntu 20.04 WSL 2
- Compiler: gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)

**To Reproduce**

`./vcpkg install cpr`

**Failure logs**

```
Computing installation plan...
The following packages will be built and installed:
    curl[core,non-http,openssl,ssl]:x64-linux -> 7.84.0#2
  * openssl[core]:x64-linux -> 3.0.7
  * zlib[core]:x64-linux -> 1.2.13
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Restored 0 package(s) from /home/dmi/.cache/vcpkg/archives in 2.472 ms. Use --debug to see more details.
Installing 1/3 openssl:x64-linux...
Building openssl[core]:x64-linux...
CMake Error at scripts/cmake/vcpkg_minimum_required.cmake:29 (message):
  Your vcpkg executable is from 2022-09-20 which is older than required by
  the caller of vcpkg_minimum_required(VERSION 2022-10-12).  Please
  re-acquire vcpkg by running bootstrap-vcpkg.
Call Stack (most recent call first):
  ports/openssl/portfile.cmake:1 (vcpkg_minimum_required)
  scripts/ports.cmake:147 (include)

error: building openssl:x64-linux failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openssl]+Build+error
Include '[openssl] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-09-20-522aa94e9d261c7d7b2f079bf2591ca62df5c714
    vcpkg-scripts version: bdf073a83 2022-11-07 (7 hours ago)
```

**Additional context**
I already run `git pull` and `./bootstrap-vcpkg.sh`, and still get that error just `openssl` dependency.   
vcpkg version: vcpkg package management program version 2022-09-20-522aa94e9d261c7d7b2f079bf2591ca62df5c714

**Comment by AFOEK** [comment]
It's still same, with same error:
```
error: building openssl:x64-linux failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openssl]+Build+error
Include '[openssl] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-09-20-522aa94e9d261c7d7b2f079bf2591ca62df5c714
    vcpkg-scripts version: e79c0d2b5 2022-11-08 (8 hours ago)
```

**Comment by AFOEK** [comment]
Updates: it seems `openssl` requiring `linux-header`, since `vcpkg` can install `openssl` on my bare metal linux. And when I try deploy my project into docker it seems get same error which requiring `linux-header` for `openssl` can be installed.

**Comment by dg0yt** [comment]
> Updates: it seems `openssl` requiring `linux-header`, since `vcpkg` can install `openssl` on my bare metal linux. And when I try deploy my project into docker it seems get same error which requiring `linux-header` for `openssl` can be installed.

https://github.com/microsoft/vcpkg/blob/90b5fb836cda4eba4569a123bca63b957f55232b/ports/openssl/portfile.cmake#L7-L13

**Comment by AFOEK** [comment]
Yes I got that warning @dg0yt but my WSL is Ubuntu, since it's state alpine only system can get `linux-hearder`.

**Comment by anders-wind** [comment]
For people running into this run: `./vcpkg/bootstrap-vcpkg.sh` again :) You might have checked out a new version of vcpkg but the binary needs to be rebuilt.

**Comment by dg0yt** [comment]
In particular, you should re-run bootstrap-vcpkg when this is what vcpkg prints:
> ~~~
> Building openssl[core]:x64-linux...
> CMake Error at scripts/cmake/vcpkg_minimum_required.cmake:29 (message):
>   Your vcpkg executable is from 2022-09-20 which is older than required by
>   the caller of vcpkg_minimum_required(VERSION 2022-10-12).  Please
>   re-acquire vcpkg by running bootstrap-vcpkg.

(from initial post)

**Comment by FrankXie05** [comment]
@AFOEK Does the issue still occur?

**Comment by AFOEK** [comment]
Last time I use it on docker it's produce same error, for WSL it's already resolved. For docker I will test it again.

**Comment by AFOEK** [comment]
![image](https://user-images.githubusercontent.com/52521676/203929516-1111c015-9566-4621-aaef-f68da8a23e2b.png)
For ubuntu docker it's always give same error for openssl dependency but if build using alpine docker it build flawlessly.

**Comment by FrankXie05** [comment]
@AFOEK Could you please provide the error log? And install `linux-headers`? :)

**Comment by ihnorton** [comment]
FWIW, I was hitting [this "missing linux-headers" error message](https://github.com/microsoft/vcpkg/issues/27708#issuecomment-1327125874) on CentOS 7, but build log showed the actual failure in my case was due to `"Can't locate IPC/Cmd.pm in @INC"` when configuring nssl. That was resolved by `yum install perl-IPC-Cmd`, and the build command then succeeded (no linux-headers installed, and that package does not appear to even exist on CentOS).

**Comment by dg0yt** [comment]
Cf. #27261: Check for IPC::Cmd, adjusted message for headers (Ubuntu name: linux-libc-dev).

**Comment by FrankXie05** [comment]
PR https://github.com/microsoft/vcpkg/pull/27261 has added information about `Perl-IPC-Cmd`.

**Comment by AFOEK** [comment]
Sorry for late comment, for WSL version is already work as intended. Thanks for the patch :)
