### ISSUE TITLE
[Error] Nasm download

### ISSUE THREAD

**Issue by Rugau** [microsoft/vcpkg#27716]
I Trying to build ``vcpkg.exe install libjpeg-turbo:x64-windows``, but nasm 2.15.05 (win32) not exists! only (x64)

https://fossies.org/windows/misc/nasm-2.15.05-win32.zip

https://github.com/microsoft/vcpkg/blob/b92daebd09641f0647f0beb6305e40009fa639a8/scripts/cmake/vcpkg_find_acquire_program.cmake#L136

**Comment by Rugau** [comment]
I changeed win32 to win64, and works. 

https://github.com/Rugau/vcpkg/commit/b056b0619a8915b4020b64b3604c7b84c4b2617e

but I don't think it's a good solution. 🤔

**Comment by JackBoosY** [comment]
We shouldn't simply switch nasm to x64 one since it's x64 only.

**Comment by Rugau** [comment]
> We shouldn't simply switch nasm to x64 one since it's x64 only.

yep, but win32 build link is offline.

**Comment by dg0yt** [comment]
> yep, but win32 build link is offline.

AFAIU this only affects the fossils mirror but not the main nasm site.

**Comment by JackBoosY** [comment]
> > yep, but win32 build link is offline.
> 
> AFAIU this only affects the fossils mirror but not the main nasm site.

Yeah.. the upstream kills every x86 OS's dream.
