### ISSUE TITLE
PCL installation - Error: Building package vtk:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by vinodgutta** [Microsoft/vcpkg#2772]
CMake Error at C:/temp/vcpkg/scripts/cmake/vcpkg_build_cmake.cmake:129 (message):
    Command failed: C:/temp/vcpkg/downloads/cmake-3.10.2-win32-x86/bin/cmake.exe;--build;.;--config;Release;--target;install;--;-v;-j1
    Working Directory: C:/temp/vcpkg/buildtrees/vtk/x86-windows-rel
    See logs for more information:
      C:\temp\vcpkg\buildtrees\vtk\install-x86-windows-rel-out.log

Call Stack (most recent call firs
[install-x86-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/1713551/install-x86-windows-rel-out.log)
t):
  C:/temp/vcpkg/scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  C:/temp/vcpkg/ports/vtk/portfile.cmake:172 (vcpkg_install_cmake)
  C:/temp/vcpkg/scripts/ports.cmake:72 (include)

**Comment by aleksandergrzyb** [comment]
I have the same problem.

**Comment by NancyLi1013** [comment]
Hi @vinodgutta , thanks for posting this issue. It should be fixed now. I can install the package successfully on my machine with the latest vcpkg. Please open a new issue if this is still a problem for you.

**Comment by giorgk** [comment]
After a year I get the same issue, while trying to install pcl.
Package: vtk:x86-windows
Vcpkg version: 2018.11.23-nohash
Should I open a new issue?
