### ISSUE TITLE
[expat] Build error

### ISSUE THREAD

**Issue by heardawei** [microsoft/vcpkg#27748]
Package: expat[core]:x64-windows -> 2.5.0
**Host Environment**
- Host: x64-windows
- Compiler: MSVC 19.33.31630.0
-    vcpkg-tool version: 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e
    vcpkg-scripts version: 7e7c62d86 2022-11-09 (4 hours ago)

**To Reproduce**
`vcpkg install magic-enum nlohmann-json sqlitecpp jsoncpp ghc-filesystem eigen3 cxxopts fmt cpr cpp-httplib boost crow range-v3`

**Failure logs**
```
-- Downloading https://github.com/libexpat/libexpat/archive/R_2_5_0.tar.gz -> libexpat-libexpat-R_2_5_0.tar.gz...
-- Extracting source D:/vcpkg/downloads/libexpat-libexpat-R_2_5_0.tar.gz
-- Using source at D:/vcpkg/buildtrees/expat/src/R_2_5_0-56671c0753.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at installed/x64-windows/share/vcpkg-cmake-config/vcpkg_cmake_config_fixup.cmake:36 (message):
  'D:/vcpkg/packages/expat_x64-windows/debug/lib/cmake/expat-' does not
  exist.
Call Stack (most recent call first):
  ports/expat/portfile.cmake:24 (vcpkg_cmake_config_fixup)
  scripts/ports.cmake:147 (include)



```

**Additional context**

**Comment by dg0yt** [comment]
Please re-run vcpkg-bootstrap.

**Comment by Cheney-W** [comment]
Thanks for dg0yt's comment. 
This issue should be fixed by downloading the latest vcpkg.exe.
