### ISSUE TITLE
[physx] <PhysX 5.1>

### ISSUE THREAD

**Issue by di0rdna** [microsoft/vcpkg#27753]
Library name: PhysX 5.1

Library description: Physics library

Source repository URL: https://github.com/NVIDIA-Omniverse/PhysX

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by FrankXie05** [comment]
@di0rdna The current port is not in vcpkg, we currently only have [NVIDIAGameWorks/PhysX ](https://github.com/NVIDIAGameWorks/PhysX) https://github.com/microsoft/vcpkg/blob/master/ports/physx/portfile.cmake

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
