### ISSUE TITLE
[CMake] Weird bug fixed by re-ordering find_package calls.

### ISSUE THREAD

**Issue by Nemirtingas** [microsoft/vcpkg#27757]
**Describe the bug**
CMake can't find boost libraries if `find_package(CURL CONFIG REQUIRED)` is called before `find_package(Boost COMPONENTS thread REQUIRED)`.
It was not happening in an older version (March) of vcpkg.

**Environment**
- OS: Ubuntu 20.04
- Compiler: LLVM + Clang + Clang-Cl 11

**To Reproduce**
[test_project.zip](https://github.com/microsoft/vcpkg/files/9982725/test_project.zip)

```
unzip test_project.zip
docker run --rm -it -v "$(pwd)/test_project:/test_project" nemirtingas/windowscross_vcpkg:msvc2019_win10.0.18362.0 bash
cd test_project
bash build_windows_vcpkg.sh
bash build_windows_project.sh
```

See the error, now switch 
```
find_package(CURL CONFIG REQUIRED)
find_package(Boost COMPONENTS thread REQUIRED)
```
lines and see that it works.

**Expected behavior**
I expected that the order of `find_package` had no effects on future calls of `find_package`.

**Failure logs**
[log_before_curl.txt](https://github.com/microsoft/vcpkg/files/9982342/log_before_curl.txt)
[log_after_curl.txt](https://github.com/microsoft/vcpkg/files/9982343/log_after_curl.txt)

**Additional context**
It seems that in my context, calling `find_package(CURL CONFIG REQUIRED)` set some CMake internal state because after the find_package call, CMake started to look for boost with `lib` as prefix when before the `find_package` call it was not adding any prefix.

**Comment by Neumann-A** [comment]
could you please give a configure trace `--trace-expand`. So looks like something is modifying `CMAKE_FIND_LIBRARY_PREFIXES`

**Comment by Nemirtingas** [comment]
> could you please give a configure trace `--trace-expand`. So looks like something is modifying `CMAKE_FIND_LIBRARY_PREFIXES`

Hi, with --trace-expand, I can see that its the new cmake module FindZLIB.cmake that has an issue with CMAKE_FIND_LIBRARY_PREFIXES.
https://github.com/Kitware/CMake/commit/3f0b9663a449cd8c1fd96dc7dcdc475ff8fe9f2f#diff-24eda3faca9c693160520d323e93fe3b5e1acc64d30e85451b6c697b8411b6e7R98-R101

The cmake 3.24.0 commit added these 4 lines that, when removed, doesn't modify anymore the find_package behavior.

**Comment by dg0yt** [comment]
@Nemirtingas You originally pointed to https://github.com/Kitware/CMake/commit/3f0b9663a449cd8c1fd96dc7dcdc475ff8fe9f2f#, and maybe this is the bug indeed: See this change in CMake 3.24.2:
https://github.com/Kitware/CMake/commit/67b6f1a09b3e14373ba5683d11300a145c80877f.

**Comment by Nemirtingas** [comment]
> @Nemirtingas You originally pointed to [Kitware/CMake@3f0b966](https://github.com/Kitware/CMake/commit/3f0b9663a449cd8c1fd96dc7dcdc475ff8fe9f2f), and maybe this is the bug indeed: See this change in CMake 3.24.2: [Kitware/CMake@67b6f1a](https://github.com/Kitware/CMake/commit/67b6f1a09b3e14373ba5683d11300a145c80877f).

Hi, I updated to CMake 3.24.2 and the bug seems to be fixed.

**Comment by dg0yt** [comment]
I don't think this resolved as long as vcpkg uses the buggy CMake version internally. The problems may be hidden.

**Comment by Nemirtingas** [comment]
Yes, to fix my issue, I updated vcpkg cmake.
