### ISSUE TITLE
[mdnsresponder] build failure (invalid download URL)

### ISSUE THREAD

**Issue by Krzmbrzl** [microsoft/vcpkg#27758]
**Host Environment**

- OS: Windows
- Compiler: MSVC

**To Reproduce**

`./vcpkg install mdnsresponder  --triplet x64-windows-static-md`

```
[DEBUG] Downloading https://opensource.apple.com/tarballs/mDNSResponder/mDNSResponder-878.270.2.tar.gz
Error: Failed to download from mirror set:
https://opensource.apple.com/tarballs/mDNSResponder/mDNSResponder-878.270.2.tar.gz: failed: status code 404
```

The URL stored for mdnsresponder
https://github.com/microsoft/vcpkg/blob/2871ddd918cecb9cb642bcb9c56897f397283192/ports/mdnsresponder/portfile.cmake#L2
seems to no longer exist (or perhaps it is only temporarily unavailable?)

**Comment by Krzmbrzl** [comment]
I believe that the sources are now meant to be downloaded from https://github.com/apple-oss-distributions/mDNSResponder/tags
(At least Apple's own website now links to tarballs attached to the respective releases).
Could somebody confirm that this seems to make sense? Then I can create a PR...

**Comment by Adela0814** [comment]
Yes, please feel free to open a new PR.
