### ISSUE TITLE
[harfbuzz] Failed to import the targets if x64-windows-release triplet is used

### ISSUE THREAD

**Issue by toothache** [microsoft/vcpkg#27754]
****

**Is your feature request related to a problem? Please describe.**

Harfbuzz is using generator expressions to define the link_libraries for harfbuzz targets. For multi-config generator (VS), if we build dependencies using release only triplet (x64-windows-release), we'll not be able to link it in Debug build.

https://github.com/microsoft/vcpkg/blob/7e7c62d863b1bf599c1d104b76cd8b74475844d4/ports/harfbuzz/harfbuzzConfig.cmake.in#L22-L28

**Proposed solution**
Harfbuzz has cmake config inside the port folder. I workaround this issue by avoiding generator expression if debug targets are not found.

```:diff
 ports/harfbuzz/harfbuzzConfig.cmake.in | 7 ++++---
 1 file changed, 4 insertions(+), 3 deletions(-)

diff --git a/ports/harfbuzz/harfbuzzConfig.cmake.in b/ports/harfbuzz/harfbuzzConfig.cmake.in
index 42f8b2ee7..9b5faddbf 100644
--- a/ports/harfbuzz/harfbuzzConfig.cmake.in
+++ b/ports/harfbuzz/harfbuzzConfig.cmake.in
@@ -20,13 +20,14 @@ add_library(harfbuzz INTERFACE IMPORTED GLOBAL)
 add_library(harfbuzz::harfbuzz ALIAS harfbuzz)
 
 find_library(HARFBUZZ_LIBRARY_DEBUG NAMES harfbuzz PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug" PATH_SUFFIXES lib NO_DEFAULT_PATH)
+find_library(HARFBUZZ_LIBRARY_RELEASE NAMES harfbuzz PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}" PATH_SUFFIXES lib NO_DEFAULT_PATH)
 if(HARFBUZZ_LIBRARY_DEBUG)
     target_link_libraries(harfbuzz INTERFACE $<$<CONFIG:DEBUG>:${HARFBUZZ_LIBRARY_DEBUG}>)
+    target_link_libraries(harfbuzz INTERFACE $<$<NOT:$<CONFIG:DEBUG>>:${HARFBUZZ_LIBRARY_RELEASE}>)
+else()
+    target_link_libraries(harfbuzz INTERFACE ${HARFBUZZ_LIBRARY_RELEASE})
 endif()
 
-find_library(HARFBUZZ_LIBRARY_RELEASE NAMES harfbuzz PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}" PATH_SUFFIXES lib NO_DEFAULT_PATH)
-target_link_libraries(harfbuzz INTERFACE $<$<NOT:$<CONFIG:DEBUG>>:${HARFBUZZ_LIBRARY_RELEASE}>)
-
 set(HARFBUZZ_FEATURES @FEATURES@)
 
 if(APPLE)
```
**Describe alternatives you've considered**
The proposed solution is a work around, there should be better ways to write the CMake configs.

**Additional context**
N/A

**Comment by Neumann-A** [comment]
> we'll not be able to link it in Debug build.

That is on you. You cannot have debug config if you use a release only triplet. I don't see why this should be "fixed".

**Comment by toothache** [comment]
> That is on you. You cannot have debug config if you use a release only triplet. I don't see why this should be "fixed".
In our project, both Debug and Release build are linking with the same release only dependencies. We have several other dependencies, e.g., opencv, freetype, utf8proc, etc. Those configs are written in a way that can be imported in Debug build. Harfbuzz is the only exception in our cases.

I'm wondering if we can improve the config to no break the original design and can also satisfy our requirements.

**Comment by dg0yt** [comment]
The wrapper would need to properly setup an imported target with configurations. 
(The target should also be namespace, and the alias be turned around.)

**Comment by toothache** [comment]
Thanks for the reply. Will close this issue.
