### ISSUE TITLE
nanodbc port needs feature that can enable unicode cmake option

### ISSUE THREAD

**Issue by Darin-Barnes** [microsoft/vcpkg#27768]
****

**Is your feature request related to a problem? Please describe.**
The nanodbc port is hard coded to have Unicode disabled: https://github.com/microsoft/vcpkg/blob/7e7c62d863b1bf599c1d104b76cd8b74475844d4/ports/nanodbc/portfile.cmake#L27

**Proposed solution**
Please allow turning this CMake option to `ON` by providing a "unicode" feature for this port.

**Describe alternatives you've considered**
None, but I'm open to ideas.

**Additional context**
None

**Comment by LilyWangLL** [comment]
Thanks for your issue. The issue https://github.com/microsoft/vcpkg/issues/9128 still exist when open option `NANODBC_ENABLE_UNICODE`, the upstream issue https://github.com/microsoft/vcpkg/issues/6157. You should report this issue on upstream.

**Comment by Darin-Barnes** [comment]
I forgot to mention that when `NANODBC_ENABLE_UNICODE` option is enabled, the compile definition is needed: `add_compile_definitions(NANODBC_ENABLE_UNICODE)`

**Comment by dg0yt** [comment]
This request cannot be implemented as a port feature: It wouldn't be additive but effectively enable an alternative API, breaking ports or user projects which rely on the other API:
https://github.com/nanodbc/nanodbc/blob/2dc94b9a86f5b6d10e16b726e9f03defcdeb4534/nanodbc/nanodbc.cpp#L174-L180
https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-use-features-to-implement-alternatives


However, you can use a custom (or overlay) triplet (file) which injects the cmake option into the build:
~~~cmake
if(PORT STREQUAL "nanodbc")
    set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DNANODBC_ENABLE_UNICODE=ON"
endif()
~~~

**Comment by LilyWangLL** [comment]
> This request cannot be implemented as a port feature: It wouldn't be additive but effectively enable an alternative API, breaking ports or user projects which rely on the other API: https://github.com/nanodbc/nanodbc/blob/2dc94b9a86f5b6d10e16b726e9f03defcdeb4534/nanodbc/nanodbc.cpp#L174-L180 https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-use-features-to-implement-alternatives
> 
> However, you can use a custom (or overlay) triplet (file) which injects the cmake option into the build:
> 
> ```cmake
> if(PORT STREQUAL "nanodbc")
>     set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DNANODBC_ENABLE_UNICODE=ON"
> endif()
> ```

Thanks for answer from dg0yt, I think this issue can be closed as a question.
