### ISSUE TITLE
[tracy] update to v0.9

### ISSUE THREAD

**Issue by kcgen** [microsoft/vcpkg#27781]
**Library name:** `Tracy` (profiler library)

**New version number:** `v0.9`

Other information that may be useful (release notes, etc...) - 

Release notes:

https://github.com/wolfpld/tracy/releases/tag/v0.9

The updated v0.9 library is currently available in Meson wraps as well, so for projects that support MSYS2 Meson wraps and vcpkg, this will help those projects upgrade to the 0.9 API instead of maintaining two code branches.

Thank you!

**Comment by MonicaLiu0311** [comment]
Related PR: https://github.com/microsoft/vcpkg/pull/27703

**Comment by FrankXie05** [comment]
Closed by PR https://github.com/microsoft/vcpkg/pull/27703
