### ISSUE TITLE
[libusb] Build error

### ISSUE THREAD

**Issue by BorisDaich** [microsoft/vcpkg#27797]
PLEASE SEE ATTACHED FILES 
I have added the export of system information so you will have as full picture as I can think of...
 

**Host Environment**

- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**

`./vcpkg install xxxx`

**Failure logs**

the following is the screenshot and copy&paste of my console. this is what I did
![image](https://user-images.githubusercontent.com/406865/201563933-509010c4-7bbb-4a46-84fe-6051fa34d758.png)

c:\Work\Github>   git clone https://github.com/Microsoft/vcpkg.git
Cloning into 'vcpkg'...
remote: Enumerating objects: 169071, done.
remote: Total 169071 (delta 0), reused 0 (delta 0), pack-reused 169071
Receiving objects: 100% (169071/169071), 63.36 MiB | 1.24 MiB/s, done.
Resolving deltas: 100% (108931/108931), done.
Updating files: 100% (9511/9511), done.

c:\Work\Github>    cd vcpkg

c:\Work\Github\vcpkg>    .\bootstrap-vcpkg.bat
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2022-11-10/vcpkg.exe -> C:\Work\Github\vcpkg\vcpkg.exe... done.
Validating signature... done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md

c:\Work\Github\vcpkg>    .\vcpkg integrate install
Applied user-wide integration for this vcpkg root.
CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=C:/Work/Github/vcpkg/scripts/buildsystems/vcpkg.cmake"

All MSBuild C++ projects can now #include any installed libraries. Linking will be handled automatically. Installing new libraries will make them instantly available.

c:\Work\Github\vcpkg>    .\vcpkg install libusb
Computing installation plan...
A suitable version of cmake was not found (required v3.24.0) Downloading portable cmake 3.24.0...
Downloading cmake...
https://github.com/Kitware/CMake/releases/download/v3.24.0/cmake-3.24.0-windows-i386.zip->C:\Work\Github\vcpkg\downloads\cmake-3.24.0-windows-i386.zip
Downloading https://github.com/Kitware/CMake/releases/download/v3.24.0/cmake-3.24.0-windows-i386.zip
Extracting cmake...
The following packages will be built and installed:
    libusb[core]:x86-windows -> 1.0.26#2
Detecting compiler hash for triplet x86-windows...
A suitable version of powershell-core was not found (required v7.2.6) Downloading portable powershell-core 7.2.6...
Downloading powershell-core...
https://github.com/PowerShell/PowerShell/releases/download/v7.2.6/PowerShell-7.2.6-win-x86.zip->C:\Work\Github\vcpkg\downloads\PowerShell-7.2.6-win-x86.zip
Downloading https://github.com/PowerShell/PowerShell/releases/download/v7.2.6/PowerShell-7.2.6-win-x86.zip
Extracting powershell-core...
Restored 0 package(s) from C:\Users\boris\AppData\Local\vcpkg\archives in 342 us. Use --debug to see more details.
Installing 1/1 libusb:x86-windows...
Building libusb[core]:x86-windows...
-- Downloading https://github.com/libusb/libusb/archive/4239bc3a50014b8e6a5a2a59df1fff3b7469543b.tar.gz -> libusb-libusb-4239bc3a50014b8e6a5a2a59df1fff3b7469543b.tar.gz...
-- Extracting source C:/Work/Github/vcpkg/downloads/libusb-libusb-4239bc3a50014b8e6a5a2a59df1fff3b7469543b.tar.gz
-- Using source at C:/Work/Github/vcpkg/buildtrees/libusb/src/3b7469543b-a464ae495e.clean
-- Building msvc/libusb_dll_2015.vcxproj for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: msbuild C:/Work/Github/vcpkg/buildtrees/libusb/x86-windows-rel/3b7469543b-a464ae495e.clean/msvc/libusb_dll_2015.vcxproj /p:Configuration=Release /t:Rebuild /p:Platform=Win32 /p:PlatformToolset=v143 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion= /p:VcpkgTriplet=x86-windows /p:VcpkgInstalledDir=C:/Work/Github/vcpkg/installed /p:VcpkgManifestInstall=false /p:UseMultiToolTask=true /p:MultiProcMaxCount=9 /p:EnforceProcessCountAcrossBuilds=true /m:9
    Working Directory: C:/Work/Github/vcpkg/buildtrees/libusb/x86-windows-rel/3b7469543b-a464ae495e.clean
    Error code: 1
    See logs for more information:
      C:\Work\Github\vcpkg\buildtrees\libusb\build-x86-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_msbuild.cmake:79 (vcpkg_execute_required_process)
  ports/libusb/portfile.cmake:45 (vcpkg_install_msbuild)
  scripts/ports.cmake:147 (include)

error: building libusb:x86-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libusb
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libusb]+Build+error
Include '[libusb] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: 6f7ffeb18 2022-11-11 (2 days ago)

Please use the prefilled template from C:\Work\Github\vcpkg\installed\vcpkg\issue_body.md when reporting your issue.

c:\Work\Github\vcpkg>git pull
Already up to date.

c:\Work\Github\vcpkg>vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

c:\Work\Github\vcpkg>

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.
[issue_body.md](https://github.com/microsoft/vcpkg/files/9999062/issue_body.md)
[stdout-x86-windows.log](https://github.com/microsoft/vcpkg/files/9999029/stdout-x86-windows.log)
[x86-windows.vcpkg_abi_info.txt](https://github.com/microsoft/vcpkg/files/9999030/x86-windows.vcpkg_abi_info.txt)
[build-x86-windows-rel-err.log](https://github.com/microsoft/vcpkg/files/9999031/build-x86-windows-rel-err.log)
[build-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/9999032/build-x86-windows-rel-out.log)
[error-logs-x86-windows.txt](https://github.com/microsoft/vcpkg/files/9999033/error-logs-x86-windows.txt)
[extract-err.log](https://github.com/microsoft/vcpkg/files/9999034/extract-err.log)
[extract-out.log](https://github.com/microsoft/vcpkg/files/9999035/extract-out.log)

**Comment by Adela0814** [comment]
Please ensure you've installed Windows SDK first.
If the problem is not solved, please provide your vs include path:
Open VS command window and run `set include` as below:
![image](https://user-images.githubusercontent.com/95600143/201594777-bae1a311-a0f6-4eb9-ad21-1db4d15270e5.png)

**Comment by BorisDaich** [comment]
sorry for the delay 
I do have Visual Studio Build tools. 
![image](https://user-images.githubusercontent.com/406865/202334194-565b6fba-b18f-4184-b9a0-d3a8d30a7e5a.png)
but all I have in include path 
![image](https://user-images.githubusercontent.com/406865/202334514-b500f7ac-284a-4267-a86d-2979294746b9.png)

does not look right what do I miss ?

**Comment by BorisDaich** [comment]
wait I might actually do not have windows SDK 
Oops

**Comment by BorisDaich** [comment]
after installing  “Windows 11 SDK (10.0.22621.0)” in the optional components of the Visual Studio 2022 Installer.
![image](https://user-images.githubusercontent.com/406865/202336079-25167224-83ac-4aff-a56c-8befe6100fbf.png)
 
 and the build went well 
 thank you for your help!
