### ISSUE TITLE
[glfw3] Build error

### ISSUE THREAD

**Issue by Masterchief-07** [microsoft/vcpkg#27795]
**Host Environment**

- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**

`./vcpkg install xxxx`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by MonicaLiu0311** [comment]
@Masterchief-07 
>Failure logs
Cut and paste the appropriate build messages from the console output.
Attach every failure log file mentioned in the console output.

I successfully installed it locally and cannot reproduce your problem. Please send me the detailed error log.

**Comment by MonicaLiu0311** [comment]
Again, please provide error details.

**Comment by MonicaLiu0311** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
