### ISSUE TITLE
[expat] Build error

### ISSUE THREAD

**Issue by pahlevan** [microsoft/vcpkg#27793]
**Host Environment**

- OS: Window 11 22H2 22621.819
- Compiler: v17.4.0

**To Reproduce**

./vcpkg --triplet x64-windows-static-md install expat

**Failure logs**

Computing installation plan...
The following packages will be built and installed:
    expat[core]:x64-windows-static-md -> 2.5.0
Detecting compiler hash for triplet x64-windows-static-md...
-- Automatically setting HTTP(S)_PROXY environment variables to "127.0.0.1:8889".
Restored 0 package(s) from C:\Users\Pahle\AppData\Local\vcpkg\archives in 124.4 us. Use --debug to see more details.
Installing 1/1 expat:x64-windows-static-md...
Building expat[core]:x64-windows-static-md...
warning: -- Using community triplet x64-windows-static-md. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: D:\vcpkg\triplets\community\x64-windows-static-md.cmake
-- Using cached libexpat-libexpat-R_2_5_0.tar.gz.
-- Cleaning sources at D:/vcpkg/buildtrees/expat/src/R_2_5_0-56671c0753.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/libexpat-libexpat-R_2_5_0.tar.gz
-- Using source at D:/vcpkg/buildtrees/expat/src/R_2_5_0-56671c0753.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-static-md
-- Building x64-windows-static-md-dbg
-- Building x64-windows-static-md-rel
CMake Error at installed/x64-windows/share/vcpkg-cmake-config/vcpkg_cmake_config_fixup.cmake:36 (message):
  'D:/vcpkg/packages/expat_x64-windows-static-md/debug/lib/cmake/expat-' does
  not exist.
Call Stack (most recent call first):
  ports/expat/portfile.cmake:24 (vcpkg_cmake_config_fixup)
  scripts/ports.cmake:147 (include)

error: building expat:x64-windows-static-md failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+expat
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[expat]+Build+error
Include '[expat] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-09-01-dfb82802c8cc562ce3b665a904a65b22314de724
    vcpkg-scripts version: 6f7ffeb18 2022-11-11 (2 days ago)

You can also use the prefilled template from D:\vcpkg\installed\vcpkg\issue_body.md.

**Comment by dg0yt** [comment]
Please re-run vcpkg-bootstrap.

**Comment by pahlevan** [comment]
tnx
