### ISSUE TITLE
Error in Building  cpprestsdk:x86-windows-static

### ISSUE THREAD

**Issue by Pantau123** [Microsoft/vcpkg#278]
Hi i have another Problem:
i want to build  cpprestsdk:x86-windows-static but it didn't compile. 
I received the following error:

> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_configure_cmake.cmake:68 (vcpkg_execute_required_process)
>   ports/cpprestsdk/portfile.cmake:18 (vcpkg_configure_cmake)
>   scripts/ports.cmake:74 (include)
> 
> 
> 
> Error: building package cpprestsdk:x86-windows-static failed
> Please ensure sure you're using the latest portfiles with `vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: cpprestsdk:x86-windows-static
>   Vcpkg version: 0.0.51-cd22281a945cd9d011f6937dfaf62f603c2d2d81
> 
> Additionally, attach any relevant sections from the log files above.
> 

In the config-x86-windows-static-rel-err.log  have following

> CMake Error at D:/Tools/vcpkg/downloads/cmake-3.5.2-win32-6/share/cmake-3.5/Modules/FindBoost.cmake:1657 (message):
>   Unable to find the requested Boost libraries.
> 
>   Boost version: 1.62.0
> 
>   Boost include path: D:/Tools/vcpkg/installed/x86-windows-static/include
> 
>   Could not find the following Boost libraries:
> 
>           boost_regex
>           boost_system
>           boost_date_time
> 
>   No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
>   directory containing Boost libraries or BOOST_ROOT to the location of
>   Boost.
> Call Stack (most recent call first):
>   CMakeLists.txt:110 (find_package)

i had do "git pull" and build the boost:x86-windows-static

[config-x86-windows-static-rel-err.log.txt](https://github.com/Microsoft/vcpkg/files/585350/config-x86-windows-static-rel-err.log.txt)
[config-x86-windows-static-rel-out.log.txt](https://github.com/Microsoft/vcpkg/files/585351/config-x86-windows-static-rel-out.log.txt)

**Comment by alexkaratarakis** [comment]
Thanks for the bug report!
There were two issues:
1) a72be4b6b9b63a7a11f507782c1c26fdd2b18ad0 The flag in this commit is only applicable in dynamic builds

2) 7811ef602ecd963ae333e3427c82629d1c8e9f34 FindBoost (shipped with CMake) looks for differently named files depending on if it is dynamic or static. To fix the current issue, we chose to rename the output. 

I will open a new issue to discuss whether this is a good idea. 

In the meantime, if you pull the latest vcpkg and rebuild boost then you should be able to proceed with cpprestsdk. Use the following:
`vcpkg remove --purge boost:x86-windows-static`
`vcpkg install cpprestsdk:x86-windows-static`
(the latter will auto install boost, so no need to explicitly install it)

Please let me know if it worked for you.

**Comment by Pantau123** [comment]
thx it is resolved...
