### ISSUE TITLE
error while trying to install in manifest mode

### ISSUE THREAD

**Issue by cenit** [microsoft/vcpkg#27806]
**Describe the bug**
This new behaviour is happening since last vcpkg tool update in one of my ci pipelines (tests on manifest mode)
```
vcpkg install darknet[opencv-base]  --head  --recurse
To remove dependencies in manifest mode, edit your manifest (vcpkg.json) and run 'install'.
note: updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
Removing darknet through vcpkg failed! Exited with error code 1.
```

is the `--recurse` option unsupported now in manifest mode, without deprecation notices?

**Expected behavior**
no errors

**Comment by Adela0814** [comment]
We tested this option works fine in manifest mode, can you provide your sample project and produce steps? Thanks.

**Comment by cenit** [comment]
https://github.com/AlexeyAB/darknet/actions/runs/3466731953

just check the recent actions, there is only one broken recently every night and it's after the vcpkg-tool update

**Comment by cenit** [comment]
yes, it's part of the build script to update vcpkg tool. And in fact it's since the new vcpkg-tool that the specific pipeline has been broken, nothing else has changed

**Comment by jimwang118** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.

**Comment by cenit** [comment]
the repro is still there in the link, happening every day since the tool update mentioned above... anyway I will work-around it whenever i will find the time

**Comment by dg0yt** [comment]
IIUC the workaround is to not use `--recursive` in manifest mode, because it is meaningless in this mode.

**Comment by cenit** [comment]
the fact is that there is no manifest usage in the failing test case, but still... it might be due to the fact that vcpkg looks for manifests in many places (and the latest update broadened the search)

**Comment by dg0yt** [comment]
> the fact is that there is no manifest usage in the failing test case,

Indeed. Well, the issue's title is misleading then, even if it is citing the error message.
