### ISSUE TITLE
find_package: Could NOT find CURL

### ISSUE THREAD

**Issue by ennorehling** [microsoft/vcpkg#27812]
I have installed vcpkg in classic (not manifest) mode, in C:\VCPKG, and run `vcpkg install curl`. CMake cannot find the package, ostensiblu because it doesn't find the library:

```
PS E:\cmake> cmake . -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scrips/buildsystems/vcpkg.cmake
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
CMake Error at C:/Program Files/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.24/Modules/FindCURL.cmake:181 (find_package_handle_standard_args)
  CMakeLists.txt:4 (find_package)


-- Configuring incomplete, errors occurred!
```

My CMakeLists.txt file, reduced to the very minimum:
```
cmake_minimum_required(VERSION 3.0)
project(test C)

find_package(CURL REQUIRED)
```

I know the documentation says to use `find_package(CURL CONFIG REQUIRED)`, but that fails because there is no CURLConfig.cmake file. CMake 3.24 is installed, which comes with a FindCURL.cmake file, and as we see in the Call Stack above, that is found, but fails.

What am I doing wrong here? This problem is not limited to CURL, any other library installed through vcpkg seems to have the same problem.

**Comment by JackBoosY** [comment]
See https://github.com/microsoft/vcpkg/blob/master/README.md#using-vcpkg-with-cmake

**Comment by ennorehling** [comment]
I've read that, but I don't know what I'm missing. I have set the CMAKE_TOOLCHAIN_FILE variable in my cmake invocation, and I'm not using any of the IDEs mentioned, so the rest of the instructions don't seem to apply.

**Comment by FrankXie05** [comment]
@ennorehling Is `Visual Studio` installed on your computer?

**Comment by JackBoosY** [comment]
> I've read that, but I don't know what I'm missing. I have set the CMAKE_TOOLCHAIN_FILE variable in my cmake invocation, and I'm not using any of the IDEs mentioned, so the rest of the instructions don't seem to apply.

Plz provide the full configure log, maybe your configuration is mismatched.

**Comment by Drunk3nMonk3y** [comment]
Can you try with the flag `-DVCPKG_TARGET_TRIPLET=x64-windows` and try `cmake` again

**Comment by wuxianggujun** [comment]
In fact, you only need to put `set(CMAKE_TOOLCHAIN_FILE "D:/Programs/vcpkg/scripts/buildsystems/vcpkg.cmake" CACHE STRING "Vcpkg toolchain file")`
before the **project** to compile normally without error 
```
cmake_minimum_required(VERSION 3.30)
# vcpkg configuration
set(CMAKE_TOOLCHAIN_FILE "D:/Programs/vcpkg/scripts/buildsystems/vcpkg.cmake" CACHE STRING "Vcpkg toolchain file")

project(JsoncppTest)
```
