### ISSUE TITLE
[libsecret] Lack of CMake target

### ISSUE THREAD

**Issue by illera88** [microsoft/vcpkg#27822]
****

**Is your feature request related to a problem? Please describe.**
When you install a package you normally get the commands need to be used in your CMakelist.txt to find the installed package but there is nothing when libsecret is installed. Example:

sqlite3 provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(unofficial-sqlite3 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::sqlite3::sqlite3)

How should I look for libsecret in CMake if installed using vcpkg?

**Proposed solution**
Generate a target for `libsecret` so all its dependencies can be linked into a project using `libsecret`

**Describe alternatives you've considered**
Individually link all the dependency libraries from `libsecret`

**Comment by FrankXie05** [comment]
@illera88 For `libsecret`, its building system is not `cmake` but `meson`, so cannot be used `find_package`(provided by `cmake`).
But you can use the official `pkg_check_modules`(cmake:https://cmake.org/cmake/help/latest/module/FindPkgConfig.html) 
Refer to https://gnome.pages.gitlab.gnome.org/libsecret/libsecret-using.html

**Comment by illera88** [comment]
Hi @FrankXie05 

I've tried but since there is no `LibsecretConfig.cmake` or  `libsecret-config.cmake` it fails:
```
CMake Error at /home/default/code/vcpkg/scripts/buildsystems/vcpkg.cmake:834 (_find_package):
  By not providing "FindLibsecret.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Libsecret", but CMake did not find one.

  Could not find a package configuration file provided by "Libsecret" with
  any of the following names:

    LibsecretConfig.cmake
    libsecret-config.cmake

  Add the installation prefix of "Libsecret" to CMAKE_PREFIX_PATH or set
  "Libsecret_DIR" to a directory containing one of the above files.  If
  "Libsecret" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:38 (find_package)
```

**Comment by FrankXie05** [comment]
@illera88 Can you provide your project file? Do not use `find_ package`, using the official method
````
CMakeLists.txt:38 (find_package)
````

**Comment by illera88** [comment]
Sorry, that was stupid.

I've tried multiple things with `pkg_check_modules`:
```
find_package(PkgConfig REQUIRED)
pkg_check_modules(LIBSECRET REQUIRED libsecret-1)
```

I've seen [this project ](https://github.com/ohwgiles/focal/blob/b90178a3b9b16116fecd4e555ab093f255acdfd7/CMakeLists.txt#L41)that uses the same.

```
find_package(PkgConfig REQUIRED)
pkg_check_modules(LIBSECRET libsecret-1 IMPORTED_TARGET ${_FIND_ARGS})
```
Got this from [here](https://github.com/Murmele/Gittyup/blob/062c143743f3d98160c0366765b9be0463789371/dep/git/CMakeLists.txt#L28)

It just doesn't find the package
```
DESKTOP-BABMP59:~/code/GCC-stealer/build$ cmake .. -DCMAKE_TOOLCHAIN_FILE=/home/default/code/vcpkg/scripts/buildsystems/vcpkg.cmake
-- Checking for module 'libsecret-1'
--   Package 'libsecret-1', required by 'virtual:world', not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:562 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:784 (_pkg_check_modules_internal)
  CMakeLists.txt:39 (pkg_check_modules)
```

**Comment by dg0yt** [comment]
Make sure that your `cmake_minimum_required(VERSION ...)` is at least 3.1. (Probably much higer for Windows.)

**Comment by FrankXie05** [comment]
After version 3.1 of cmake, change the environment variable `CMAKE_ PREFIX_ PATH`、`CMAKE_ FRAMEWORK_ PATH` and `CMAKE_ APPBUNDLE_ PATH`, etc. is added to the pkg configuration search path.

**Comment by dg0yt** [comment]
You don't want to use legacy CMake behaviours, do you? `PKG_CONFIG_USE_CMAKE_PREFIX_PATH`, Cf. https://cmake.org/cmake/help/v3.25/module/FindPkgConfig.html?highlight=PKG_CONFIG_USE_CMAKE_PREFIX_PATH

**Comment by illera88** [comment]
Ohh I see.

So now I can include the headers with:
```
target_include_directories(target PRIVATE ${LIBSECRET_INCLUDE_DIRS})
```
And `libsecret` with its dependencies:
```
target_link_libraries(target PRIVATE ${LIBSECRET_LIBRARIES})
```

But for some reason instead of getting the full path to the `.a` files I get a relative path which CMake is not referencing with `-L` so it know where to look for all the libs. Shouldn't `${LIBSECRET_LIBRARIES}` contain the full path of each library?

Here is the linker command:
```
/usr/bin/c++ -static CMakeFiles/GCC-stealer.dir/src/GCC-stealer.cpp.o -o GCC-stealer  /home/default/code/vcpkg/installed/x64-linux/debug/lib/libsqlite3.a /home/default/code/vcpkg/installed/x64-linux/lib/libssl.a /home/default/code/vcpkg/installed/x64-linux/lib/libcrypto.a -lsecret-1 -lglib-2.0 -lglib-2.0 -lglib-2.0 -lglib-2.0 -lgio-2.0 -lglib-2.0 -lgobject-2.0 -lglib-2.0 -lffi -lgmodule-2.0 -lglib-2.0 -lm -lpcre2-8 -lz -lgcrypt -lgpg-error -ldl -lgio-2.0 -lgobject-2.0 -lffi -lgmodule-2.0 -lm -lpcre2-8 -lz -lgcrypt -lgpg-error
```
which fails because all of those libs are at `/home/default/code/vcpkg/installed/x64-linux/lib`.

I can fix it by passing `-L/home/default/code/vcpkg/installed/x64-linux/lib` but shouldn't cmake do that for me?

**Comment by dg0yt** [comment]
It is easier and more reliable to use the `IMPORTED_TARGET` argument and just link to the `PkgConfig::...` target.

**Comment by illera88** [comment]
That worked fine except that for whatever reason the linker is now trying to link against `libintl.so`
and it fails with:
`attempted static link of dynamic object /usr/lib/libintl.so`
which make sense since I'm trying to create a statically compile binary.
```
/usr/bin/c++ -static /usr/lib/libintl.so -pthread CMakeFiles/GCC-stealer.dir/src/GCC-stealer.cpp.o -o GCC-stealer  /home/default/code/vcpkg/installed/x64-linux/debug/lib/libsqlite3.a -lintl -ldl /home/default/code/vcpkg/installed/x64-linux/lib/libsecret-1.a /home/default/code/vcpkg/installed/x64-linux/lib/libglib-2.0.a /home/default/code/vcpkg/installed/x64-linux/lib/libgio-2.0.a /home/default/code/vcpkg/installed/x64-linux/lib/libgobject-2.0.a /home/default/code/vcpkg/installed/x64-linux/lib/libffi.a /home/default/code/vcpkg/installed/x64-linux/lib/libgmodule-2.0.a /home/default/code/vcpkg/installed/x64-linux/lib/libglib-2.0.a /home/default/code/vcpkg/installed/x64-linux/lib/libgio-2.0.a /home/default/code/vcpkg/installed/x64-linux/lib/libgobject-2.0.a /home/default/code/vcpkg/installed/x64-linux/lib/libffi.a /home/default/code/vcpkg/installed/x64-linux/lib/libgmodule-2.0.a /usr/lib/libm.a /home/default/code/vcpkg/installed/x64-linux/lib/libpcre2-8.a /home/default/code/vcpkg/installed/x64-linux/lib/libz.a /home/default/code/vcpkg/installed/x64-linux/lib/libgcrypt.a /home/default/code/vcpkg/installed/x64-linux/lib/libgpg-error.a
```
A couple of interesting things:

- `libintl` is required and I don't thing that `vcpkg` is counting with that
- There is no port for `libintl` AFAIK

I got another less elegant way to make it compile so I guess that I will follow that path
