### ISSUE TITLE
vcpkg integrate install stopped working on Linux

### ISSUE THREAD

**Issue by acgetchell** [microsoft/vcpkg#27832]
**Describe the bug**
`vcpkg integrate install` fails

**Environment**
- OS: Ubuntu 22.04 LTS
- Compiler: gcc-11, clang-14

**To Reproduce**

Currently fails on Travis-CI:

https://app.travis-ci.com/github/acgetchell/CDT-plusplus/builds/257819339

Worked 5 days ago:

https://app.travis-ci.com/github/acgetchell/CDT-plusplus/builds/257657548

Same travis.yml file here:

https://github.com/acgetchell/CDT-plusplus/blob/develop/.travis.yml

**Expected behavior**

I expected it to work as it's done hundreds of times before.

**Failure logs**

```
vcpkg integrate install
write_contents("/home/travis/.vcpkg/vcpkg.path.txt"): No such file or directory
```

https://app.travis-ci.com/github/acgetchell/CDT-plusplus/jobs/588548845#L927

**Additional context**

I suspect this broke with the update of vcpkg-tool to 2022-11-10.

https://github.com/microsoft/vcpkg/commit/8430e98114632544ee3d0d6c4a1b933ab3f9dccb

**Comment by LilyWangLL** [comment]
@BillyONeal Could you help take a look this issue? Thanks in advance.

**Comment by BillyONeal** [comment]
I'm a bit confused: `integrate install` is to integrate with Visual Studio and there's little reason to run that on Linux.

**Comment by acgetchell** [comment]
Okay. Well, it accidentally worked before, and doesn't now, which seems to be fine.

**Comment by BillyONeal** [comment]
> Okay. Well, it accidentally worked before, and doesn't now, which seems to be fine.

I mean, just crashing like it looks is happening isn't great either. I was replying not to say 'go away' but to better understand what you're trying to do.

**Comment by acgetchell** [comment]
Thank you! I understand you're all very busy so if this is an unsupported use case I'm fine with that. Maybe add something like "looks like you're trying to run this on Linux which is unsupported" to short-circuit this error.

**Comment by BillyONeal** [comment]
> Thank you! I understand you're all very busy so if this is an unsupported use case I'm fine with that. Maybe add something like "looks like you're trying to run this on Linux which is unsupported" to short-circuit this error.

I just tried this and it didn't repro for me but I added defenses anyway.
