### ISSUE TITLE
[skia] Missing header file

### ISSUE THREAD

**Issue by Chlumsky** [microsoft/vcpkg#27831]
**Host Environment**

- OS: Windows
- Compiler: Visual Studio 2022

**To Reproduce**

`./vcpkg install skia`

Add this include:

```c++
#include <skia/core/SkColorSpace.h>
```

**Failure logs**

```
C1083	Cannot open include file: 'modules/skcms/skcms.h': No such file or directory
...\vcpkg_installed\x64-windows-static\include\skia\core\SkColorSpace.h:14
```

**Additional context**

At the beginning of `SkColorSpace.h`, there is

```c++
#include "modules/skcms/skcms.h"
```

However, this file is not available in the include path or anywhere within `vcpkg_installed`. It is present in `buildtrees/skia/src/40cd0870fd-03fc96c3ab.clean/modules/skcms` and the issue can be worked around by copying this file to a location that matches the include directive and adding it to the include path explicitly. This issue was not present prior to Skia port version 0.36.

See also: https://groups.google.com/g/skia-discuss/c/RAs9yedISpM

**Comment by dg0yt** [comment]
Duplicates #27219.
