### ISSUE TITLE
[fontconfig] Build error

### ISSUE THREAD

**Issue by rexx-org** [microsoft/vcpkg#27833]
Package: fontconfig[core]:x64-windows -> 2.14.1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.16.27026.1
-    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: 6a7131cac 2022-11-15 (12 minutes ago)

**To Reproduce**

`vcpkg install fontconfig:x64-windows`

**Failure logs**

```
-- Downloading https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/2.14.1/fontconfig-2.14.1.tar.gz -> fontconfig-fontconfig-2.14.1.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
Downloading https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/2.14.1/fontconfig-2.14.1.tar.gz
Download failed -- retrying after 1000ms.Download failed -- retrying after 2000ms.Download failed -- retrying after 4000ms.error: Failed to download from mirror set
error: https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/2.14.1/fontconfig-2.14.1.tar.gz: WinHttpSendRequest() failed: 12175
https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/2.14.1/fontconfig-2.14.1.tar.gz: WinHttpSendRequest() failed: 12175
https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/2.14.1/fontconfig-2.14.1.tar.gz: WinHttpSendRequest() failed: 12175
https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/2.14.1/fontconfig-2.14.1.tar.gz: WinHttpSendRequest() failed: 12175

[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(774):
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 11 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 2042 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 12.77 s (12733562 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. Your proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:273 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_gitlab.cmake:118 (vcpkg_download_distfile)
  ports/fontconfig/portfile.cmake:3 (vcpkg_from_gitlab)
  scripts/ports.cmake:147 (include)



```

**Additional context**

Not using any proxy.
Same error occurs when attempting to install x86-windows version.
Have had no problems with installing any other ports.
Ran wget https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/2.14.1/fontconfig-2.14.1.tar.gz from cygwin window on same machine and it downloaded the file successfully.

**Comment by rexx-org** [comment]
I tried installing fontconfig on Windows 10 machine and it worked. Looks like a Windows 7 incompatibility.

**Comment by FrankXie05** [comment]
@rexx-org Re-run `.\bootstrap-vcpkg.bat` and try again.

**Comment by rexx-org** [comment]
Result of running bootstrap-vcpkg.bat:
$ ./bootstrap-vcpkg.bat
Method invocation failed because [System.String] doesn't contain a method named
 'IsNullOrWhiteSpace'.
At T:\vcpkg\scripts\bootstrap.ps1:28 char:38
+ if (-Not [string]::IsNullOrWhiteSpace <<<< ($withVSPath))
    + CategoryInfo          : InvalidOperation: (IsNullOrWhiteSpace:String) []
   , RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [System.String] doesn't contain a method named
 'IsNullOrWhiteSpace'.
At T:\vcpkg\scripts\bootstrap.ps1:33 char:38
+ if (-Not [string]::IsNullOrWhiteSpace <<<< ($withWinSDK))
    + CategoryInfo          : InvalidOperation: (IsNullOrWhiteSpace:String) []
   , RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2022-11-10/vcpkg.exe -> T:\vcpkg\vcpkg.exe... done.
Validating signature... done.

Ran git pull
Reran ./vcpkg install fontconfig:x64-windows 
Same failure as originally reported

**Comment by FrankXie05** [comment]
@rexx-org Please try the method mentioned in issue: https://github.com/microsoft/vcpkg/issues/16207. :)

**Comment by FrankXie05** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
