### ISSUE TITLE
[libspatialite] Build error : unrecognized command-line option '-V'

### ISSUE THREAD

**Issue by davesworking** [microsoft/vcpkg#27834]
-- Configuring arm64-linux-dbg
 CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
     Command failed: /usr/bin/bash -c "V=1 ./../src/atialite-5-71f24500eb.clean/configure  \"--enable-freexl\" \"--disable-gcp\" \"--enable-geocallbacks\" \"--disable-rttopo\" \"--disable-examples\" \"--disable-minizip\" \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"LIBS=-L/Developer/teamcity/work/8b343da6c721ac3e/Components/Library/Version/Linux-ARM64/arm64-linux/debug/lib/pkgconfig/../../lib -lgeos_c -lxml2 -lproj -lstdc++ -ltiffd -ljpeg -llzma -pthread -lcurl-d -lsqlite3 -ldl -lpthread -lz -lfreexl -lm $LIBS\" \"--prefix=/Developer/teamcity/work/8b343da6c721ac3e/Components/Library/Version/Linux-ARM64/arm64-linux/debug\" \"--bindir=\\${prefix}/../tools/libspatialite/debug/bin\" \"--sbindir=\\${prefix}/../tools/libspatialite/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/libspatialite\""
     Working Directory: /Developer/teamcity/work/8b343da6c721ac3e/Components/Library/Version/Build/Linux-ARM64/aarch64-glibc2.31-gcc10.2/vcpkg/buildtrees/libspatialite/arm64-linux-dbg
     Error code: 1
     See logs for more information:
       /Developer/teamcity/work/8b343da6c721ac3e/Components/Library/Version/Build/Linux-ARM64/aarch64-glibc2.31-gcc10.2/vcpkg/buildtrees/libspatialite/config-arm64-linux-dbg-config.log
       /Developer/teamcity/work/8b343da6c721ac3e/Components/Library/Version/Build/Linux-ARM64/aarch64-glibc2.31-gcc10.2/vcpkg/buildtrees/libspatialite/config-arm64-linux-dbg-out.log
       /Developer/teamcity/work/8b343da6c721ac3e/Components/Library/Version/Build/Linux-ARM64/aarch64-glibc2.31-gcc10.2/vcpkg/buildtrees/libspatialite/config-arm64-linux-dbg-err.log
 
 Call Stack (most recent call first):
   scripts/cmake/vcpkg_configure_make.cmake:808 (vcpkg_execute_required_process)
   ports/libspatialite/portfile.cmake:180 (vcpkg_configure_make)
   scripts/ports.cmake:147 (include)
 
 
 error: building libspatialite:arm64-linux failed with: BUILD_FAILED

CONFIG.LOG
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by libspatialite configure 5.0.1, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./../src/atialite-5-71f24500eb.clean/configure --enable-freexl --disable-gcp --enable-geocallbacks --disable-rttopo --disable-examples --disable-minizip --disable-silent-rules --verbose --disable-shared --enable-static LIBS=-L/Developer/teamcity/work/8b343da6c721ac3e/Components/Library/Version/Linux-ARM64/arm64-linux/debug/lib/pkgconfig/../../lib -lgeos_c -lxml2 -lproj -lstdc++ -ltiffd -ljpeg -llzma -pthread -lcurl-d -lsqlite3 -ldl -lpthread -lz -lfreexl -lm  --prefix=/Developer/teamcity/work/8b343da6c721ac3e/Components/Library/Version/Linux-ARM64/arm64-linux/debug --bindir=${prefix}/../tools/libspatialite/debug/bin --sbindir=${prefix}/../tools/libspatialite/debug/sbin --libdir=${prefix}/lib --includedir=${prefix}/../include --datarootdir=${prefix}/share/libspatialite

## --------- ##

uname -m = aarch64
uname -r = 5.10.103-v8+
uname -s = Linux
uname -v = #1530 SMP PREEMPT Tue Mar 8 13:06:35 GMT 2022

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = aarch64
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown
---
```
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 10.2.1-6' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20210110 (Debian 10.2.1-6) 
configure:3602: $? = 0
configure:3591: /usr/bin/cc -V >&5
cc: error: unrecognized command-line option '-V'
cc: fatal error: no input files
compilation terminated.
configure:3602: $? = 1
configure:3591: /usr/bin/cc -qversion >&5
cc: error: unrecognized command-line option '-qversion'; did you mean '--version'?
cc: fatal error: no input files
compilation terminated.
```

**Comment by dg0yt** [comment]
> Build error : unrecognized command-line option '-V'

Normal config test out. The error message is somewhere else.

**Comment by davesworking** [comment]
**config-arm64-linux-dbg-err.log**
./../src/atialite-5-71f24500eb.clean/configure: line 18771: 0: command not found
./../src/atialite-5-71f24500eb.clean/configure: line 18864: 0: command not found
configure: error: 'libgeos_c' (>= v.3.4.0) is required but it doesn't seem to be installed on this system. You may need to try re-running configure with a --disable-geosadvanced parameter.

**config,log**
...
conftest.c:13:10: fatal error: ac_nonexistent.h: No such file or directory
   13 | #include <ac_nonexistent.h>
      |          ^~~~~~~~~~~~~~~~~~
...
configure:19010: error: 'libgeos_c' (>= v.3.4.0) is required but it doesn't seem to be installed on this system. You may need to try re-running configure with a --disable-geosadvanced parameter.

**Comment by dg0yt** [comment]
> ...
> conftest.c:13:10: fatal error: ac_nonexistent.h: No such file or directory
> 13 | #include <ac_nonexistent.h>
> | ^~~~~~~~~~~~~~~~~~

Not relevant.

> ...
> configure:19010: error: 'libgeos_c' (>= v.3.4.0) is required but it doesn't seem to be installed on this system. You may need to try re-running configure with a --disable-geosadvanced parameter.

This is relevant, but not enough information for analysis. I assume the lib is present, but some lib lacks an extra link library for this platform. We would know from `config.log` if it was added as an attachment.
This is what was given to the configure:
~~~
"LIBS=-L/Developer/teamcity/work/8b343da6c721ac3e/Components/Library/Version/Linux-ARM64/arm64-linux/debug/lib/pkgconfig/../../lib -lgeos_c -lxml2 -lproj -lstdc++ -ltiffd -ljpeg -llzma -pthread -lcurl-d -lsqlite3 -ldl -lpthread -lz -lfreexl -lm $LIBS"
~~~

**Comment by davesworking** [comment]
[config.log](https://github.com/microsoft/vcpkg/files/10025400/config.log)

**Comment by dg0yt** [comment]
~~~
configure:18955: checking for library containing GEOSDelaunayTriangulation
configure:18986: /usr/bin/cc -o conftest -fPIC -g  -L/Developer/teamcity/work/8b343da6c721ac3e/Components/Library/Version/Linux-ARM64/arm64-linux/debug/lib conftest.c -lsqlite3 -lsqlite3 -lsqlite3 -L/Developer/teamcity/work/8b343da6c721ac3e/Components/Library/Version/Linux-ARM64/arm64-linux/debug/lib/pkgconfig/../../lib -lgeos_c -lxml2 -lproj -lstdc++ -ltiffd -ljpeg -llzma -pthread -lcurl-d -lsqlite3 -ldl -lpthread -lz -lfreexl -lm  >&5
/usr/bin/ld: warning: libgeos.so.3.11.0, needed by /Developer/teamcity/work/8b343da6c721ac3e/Components/Library/Version/Linux-ARM64/arm64-linux/debug/lib/libgeos_c.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /Developer/teamcity/work/8b343da6c721ac3e/Components/Library/Version/Linux-ARM64/arm64-linux/debug/lib/libgeos_c.so: undefined reference to `geos::triangulate::VoronoiDiagramBuilder::setTolerance(double)'
~~~
libgeos.so.3.11.0, needed by libgeos_c.so, but building libspatialite ` --disable-shared --enable-static`? Maybe you check first if pure static or shared builds work.

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
