### ISSUE TITLE
Generating a "credits" file with licenses and copyright notices

### ISSUE THREAD

**Issue by vrbhartiya** [microsoft/vcpkg#27841]
Many open-source licenses require the reproduction of text and copyright notices as part of compliance. A lot of libraries have copyright notices strewn about various source files, which complicates this further. I'm wondering if there are any mechanisms within vcpkg (existing or planned) for generating a consolidated "credits" file that contains notices from all dependencies within the `vcpkg.json` file? A good example of the end result would be the Chrome credits page (chrome://credits), though obviously the file generated by vcpkg doesn't need to be html.

**Comment by FrankXie05** [comment]
@vrbhartiya Thank you for submitting the issue. At present, vcpkg does not have the function like chrome://credits, and you cannot view all licenses. You can only view the license through `vcpkg.json`.

**Comment by dg0yt** [comment]
Well, in particular in manifest mode, you could collect the installed `copyright` files in `/share`. But in general, this won't be precise. These files need to cover all installed features, not just the features you use and redistribute. For a number of popular packages, this includes tools covered by GPL in addition to the library which is covered by LGPL.
