### ISSUE TITLE
How do I install harfbuzz[ucdn]:x86-windows

### ISSUE THREAD

**Issue by 747728775** [microsoft/vcpkg#27844]
Package harfbuzz does not have a ucdn feature.

.\vcpkg install harfbuzz[ucdn]:x86-windows
Computing installation plan...
Could not find ucdn in harfbuzz.
note: updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.

**Comment by 747728775** [comment]
this note is not used

**Comment by 747728775** [comment]
this note is useless

**Comment by JackBoosY** [comment]
> this note is useless

It's a common notice.

Request a new feature.

**Comment by 747728775** [comment]
> > this note is useless
> 
> It's a common notice.
> 
> Request a new feature.

what do you mean? I just need  harfbuzz[ucdn]:x86-windows

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Could you please provide more information about feature `ucdn`, I can't search related codes about `ucdn` in the source of [`harfbuzz`](https://github.com/harfbuzz/harfbuzz).

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
