### ISSUE TITLE
[mysql-connector-cpp] Use vcpkg's protobuf and other dependencies

### ISSUE THREAD

**Issue by tntxtnt** [microsoft/vcpkg#27873]
Currently `mysql-connector-cpp` use a "builtin" `protobuf` library, which cause multiple definitions error when using with vcpkg's `protobuf`. `mysql-connector-cpp` also uses other builtin libraries that vcpkg's has like `rapidjson`, `zlib`, `zstd` , `lz4`, etc. and may causes conflicts as well.

Example of multiple definition error when builing with vcpkg's `protobuf`:
```
/usr/bin/ld: vcpkg_installed/x64-linux/debug/lib/libprotobufd.a(message_lite.cc.o): in function `google::protobuf::MessageLite::LogInitializationErrorMessage() const':
/home/balebom/vcpkg/buildtrees/protobuf/src/v3.21.8-b162a26f57.clean/src/google/protobuf/message_lite.cc:132: multiple definition of `google::protobuf::MessageLite::LogInitializationErrorMessage() const'; vcpkg_installed/x64-linux/debug/lib/libmysqlcppconn8-static.a(libprotobuf-lited_message_lite.cc.o):/home/balebom/vcpkg/buildtrees/mysql-connector-cpp/x64-linux-dbg/cdk/protocol/mysqlx/protobuf/./protobuf-3.19.4/src/google/protobuf/message_lite.cc:133: first defined here
```
As you can see it says `google::protobuf::MessageLite::LogInitializationErrorMessage() const` first defined in `vcpkg/buildtrees/mysql-connector-cpp/x64-linux-dbg/cdk/protocol/mysqlx/protobuf/./protobuf-3.19.4/src/google/protobuf/message_lite.cc` which is `mysql-connector-cpp`'s baked-in `protobuf`.

**Proposed solution**
Patch `mysql-connector-cpp`'s build/CMakeLists so that it uses vcpkg's packages for its dependencies.

**Comment by N08I40K** [comment]
I have the same problem. Too bad it hasn't changed yet :(

**Comment by FrankXie05** [comment]
@tntxtnt @N08I40K Thank for posting this issue, 
The way to use third-party libraries upstream is to use customized header files instead of link libraries.
eg: https://github.com/mysql/mysql-connector-cpp/tree/8.0.32/cdk/extra/rapidjson/include/rapidjson

Therefore, we cannot replace it with the library provided by vcpkg (This is designed).
The current solution is to remove these ports downloaded by vcpkg `./vcpkg remove protobuf:x64-linux`

Or: Feed back to the upstream to get the accurate reply from the upstream about whether the usage of the third-party library is consistent with vcpkg, so that we can change it. :)

**Comment by zxffffffff** [comment]
I got the same problem on arm64-osx, but it's ok on x64-windows and x64-linux

libmysqlcppconn8-static.a
libprotobuf.a

```
duplicate symbol 'google::protobuf::internal::WireFormatLite::EnumSize(google::protobuf::RepeatedField<int> const&)' in:
    ../../vcpkg_installed/arm64-osx/debug/lib/libmysqlcppconn8-static.a(wire_format_lite.cc.o)
    ../../vcpkg_installed/arm64-osx/lib/libprotobuf.a(wire_format_lite.cc.o)
duplicate symbol 'google::protobuf::internal::WireFormatLite::SInt32Size(google::protobuf::RepeatedField<int> const&)' in:
    ../../vcpkg_installed/arm64-osx/debug/lib/libmysqlcppconn8-static.a(wire_format_lite.cc.o)
    ../../vcpkg_installed/arm64-osx/lib/libprotobuf.a(wire_format_lite.cc.o)
duplicate symbol 'google::protobuf::internal::WireFormatLite::Int32Size(google::protobuf::RepeatedField<int> const&)' in:
    ../../vcpkg_installed/arm64-osx/debug/lib/libmysqlcppconn8-static.a(wire_format_lite.cc.o)
    ../../vcpkg_installed/arm64-osx/lib/libprotobuf.a(wire_format_lite.cc.o)
duplicate symbol 'google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >**)' in:
    ../../vcpkg_installed/arm64-osx/debug/lib/libmysqlcppconn8-static.a(wire_format_lite.cc.o)
    ../../vcpkg_installed/arm64-osx/lib/libprotobuf.a(wire_format_lite.cc.o)
duplicate symbol 'google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)' in:
    ../../vcpkg_installed/arm64-osx/debug/lib/libmysqlcppconn8-static.a(wire_format_lite.cc.o)
    ../../vcpkg_installed/arm64-osx/lib/libprotobuf.a(wire_format_lite.cc.o)
ld: 146 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/sample-dynamic-lib/libsample-dynamic-lib.dylib] Error 1
make[1]: *** [src/sample-dynamic-lib/CMakeFiles/sample-dynamic-lib.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by kotori2** [comment]
In #30869 I've changed the port to use vcpkg's flavor of OpenSSL/lz4/zlib/zstd/protobuf/Boost.
For rapidjson I think [MySQL didn't provide a way to specify the path](https://dev.mysql.com/doc/connector-cpp/8.0/en/connector-cpp-source-configuration-options.html) and like @FrankXie05 said, it uses customized header files.
