### ISSUE TITLE
gtk3 is constantly hanging x86-windows builds.

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/vcpkg#27904]
We are seeing gtk3 responsible for a lot of recent failures.

* https://dev.azure.com/vcpkg/public/_build/results?buildId=80806 (Last Friday, failed)
* https://dev.azure.com/vcpkg/public/_build/results?buildId=80953 (Monday, succeeded)
* https://dev.azure.com/vcpkg/public/_build/results?buildId=81079 (Wednesday, failed)

Perhaps this is related to the recent X-on-Windows work @Neumann-A ?

Because when this happens the run is toast we do not have logs.

**Comment by Neumann-A** [comment]
> Perhaps this is related to the recent X-on-Windows work @Neumann-A ?

According to the raw port build logs none of the libx* ports are installed before the gtk3 port (81079). So unlikely.

**Comment by BillyONeal** [comment]
Makes sense. Hmmmmm....

**Comment by Adela0814** [comment]
This issue has not recurred on CI recently.
