### ISSUE TITLE
[directxsdk] build failure

### ISSUE THREAD

**Issue by qichen1336** [microsoft/vcpkg#27913]
**Host Environment**

- OS: [Windows]
- Compiler: MSVC

**To Reproduce**

`./vcpkg install directxsdk`

**Failure logs**
```
Computing installation plan...
The following packages will be built and installed:
    directxsdk[core]:x86-windows -> jun10#5
Detecting compiler hash for triplet x86-windows...
error: while detecting compiler information:
The log file content at "D:\vcpkg\buildtrees\detect_compiler\stdout-x86-windows.log" is:
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: D:/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe -v
    Working Directory: D:/vcpkg/buildtrees/detect_compiler/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\detect_compiler\config-x86-windows-CMakeCache.txt.log
      D:\vcpkg\buildtrees\detect_compiler\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:311 (vcpkg_execute_required_process)
  scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:147 (include)
```

**Additional context**
1.According to "config-x86-windows-out.log", I set environment variable CC ="cl.exe" and Path has included "D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x86"
2. I added "SET (CMAKE_C_COMPILER_WORKS 1)  SET (CMAKE_CXX_COMPILER_WORKS 1)" to line 24 of "vcpkg/scripts/buildsystems/vcpkg.cmake" but it doesn't work.
3. Re-install VS 2019 and vcpkg.
[config-x86-windows-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10046553/config-x86-windows-CMakeCache.txt.log)
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/10046554/config-x86-windows-out.log)

**Comment by Cheney-W** [comment]
1. What components are installed on your VS and can you send me a screenshot?
2. Have you modified the local file: `\vcpkg\triplets\x86-windows.cmake`?
3. Could you please run `./vcpkg install directxsdk --debug` and send the log to me?

**Comment by qichen1336** [comment]
1. I send screen shots indicating what I have ticked when installing.
![1](https://user-images.githubusercontent.com/95479296/203068778-11c3c179-6904-419c-a89f-744dc5f41623.png)
![2](https://user-images.githubusercontent.com/95479296/203068788-35ed3ed9-643f-4414-882c-2dfc08a2b8e9.png)
![3](https://user-images.githubusercontent.com/95479296/203068796-807d9ff9-42b5-4c3f-977d-e5d88b2828ff.png)

3. I didn't modify it and now the content in that file is:

set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic).

4. The log is as follows:
PS D:\vcpkg> ./vcpkg install directxsdk --debug
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Failed to open: D:\vcpkg\vcpkg-bundle.json
[DEBUG] Using scripts-root: D:\vcpkg\scripts
[DEBUG] Bundle config: readonly=0, usegitregistry=0, embeddedsha=nullopt
[DEBUG] Using builtin-ports: D:\vcpkg\ports
[DEBUG] Using installed-root: D:\vcpkg\installed
[DEBUG] Using buildtrees-root: D:\vcpkg\buildtrees
[DEBUG] Using packages-root: D:\vcpkg\packages
[DEBUG] Using vcpkg-root: D:\vcpkg
[DEBUG] Using scripts-root: D:\vcpkg\scripts
[DEBUG] Using builtin-registry: D:\vcpkg\versions
[DEBUG] Using downloads-root: D:\vcpkg\downloads
[DEBUG] Detecting host with IsWow64Process2
[DEBUG] Default binary cache path is: C:\Users\lenovo\AppData\Local\vcpkg\archives
Computing installation plan...
[DEBUG] CreateProcessW("D:\vcpkg\downloads\tools\cmake-3.24.0-windows\cmake-3.24.0-windows-i386\bin\cmake.exe" --version)
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 1000: cmd_execute_and_stream_data() returned 0 after   232750 us
[DEBUG] CreateProcessW("D:\vcpkg\downloads\tools\cmake-3.24.0-windows\cmake-3.24.0-windows-i386\bin\cmake.exe" -DVCPKG_ROOT_DIR=D:/vcpkg -DPACKAGES_DIR=D:/vcpkg/packages -DBUILDTREES_DIR=D:/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=D:/vcpkg/installed -DDOWNLOADS=D:/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "D:\vcpkg\buildtrees\0.vcpkg_dep_info.cmake")
[DEBUG] Read
File() finished with GetLastError(): 109
[DEBUG] 1001: cmd_execute_and_stream_data() returned 0 after    36130 us
[DEBUG] CreateProcessW("D:\vcpkg\downloads\tools\cmake-3.24.0-windows\cmake-3.24.0-windows-i386\bin\cmake.exe" -DVCPKG_ROOT_DIR=D:/vcpkg -DPACKAGES_DIR=D:/vcpkg/packages -DBUILDTREES_DIR=D:/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=D:/vcpkg/installed -
DDOWNLOADS=D:/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "D:\vcpkg\buildtrees\0.vcpkg_tags.cmake")
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 1002: cmd_execute_and_stream_data() returned 0 after    32811 us
The following packages will be built and installed:
    directxsdk[core]:x86-windows -> jun10#5
[DEBUG] CreateProcessW("C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease -legacy -products * -format xml)
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 1003: cmd_execute_and_stream_data() returned 0 after    52430 us
Detecting compiler hash for triplet x86-windows...
[DEBUG] Found path: D:\Program Files\Git\cmd\git.exe
[DEBUG] CreateProcessW("D:\Program Files\Git\cmd\git.exe" --version)
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 1004: cmd_execute_and_stream_data() returned 0 after   549731 us
[DEBUG] Detecting host with IsWow64Process2
[DEBUG] CreateProcessW("D:\vcpkg\downloads\tools\powershell-core-7.2.6-windows\pwsh.exe" --version)
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 1005: cmd_execute_and_stream_data() returned 0 after  2487051 us
[DEBUG] command line: cmd /c "D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary/Build\vcvarsall.bat" -vcvars_ver=14.29.30133 amd64_x86   2>&1 <NUL  & echo cdARN4xjKueKScMy9C6H & set
[DEBUG] CreateProcessW(cmd /c "D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary/Build\vcvarsall.bat" -vcvars_ver=14.29.30133 amd64_x86   2>&1 <NUL  & echo cdARN4xjKueKScMy9C6H & set)
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 1006: cmd_execute_and_stream_data() returned 0 after  1256072 us
[DEBUG] 'vswhere.exe -property catalog_productSemanticVersion -path "D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat"' is not recognized as an internal or external command,
operable program or batch file.
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.0
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
'dir "D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\vsdevcmd\ext\*.bat" /b /a-d-h /on' is not recognized as an internal or external command,
operable program or batch file.
[vcvarsall.bat] Environment initialized for: 'x64_x86'
cdARN4xjKueKScMy9C6H
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\lenovo\AppData\Roaming
CommonProgramFiles=C:\Program Files (x86)\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=DESKTOP-GCBU4B9
ComSpec=C:\WINDOWS\system32\cmd.exe;
DevEnvDir=D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\
Framework40Version=v4.0
FrameworkDir=C:\Windows\Microsoft.NET\Framework64\
FrameworkDir32=C:\Windows\Microsoft.NET\Framework\
FrameworkDir64=C:\Windows\Microsoft.NET\Framework64\
FrameworkVersion=v4.0.30319
FrameworkVersion32=v4.0.30319
FrameworkVersion64=v4.0.30319
HOMEDRIVE=C:
HOMEPATH=\Users\lenovo
LIBPATH=C:\Windows\Microsoft.NET\Framework64\v4.0.30319
LOCALAPPDATA=C:\Users\lenovo\AppData\Local
LOGONSERVER=\\DESKTOP-GCBU4B9
NUMBER_OF_PROCESSORS=8
OS=Windows_NT
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
PROCESSOR_ARCHITECTURE=x86
PROCESSOR_ARCHITEW6432=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=9e09
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files (x86)
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Users\lenovo\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\lenovo\AppData\Local\Temp
TMP=C:\Users\lenovo\AppData\Local\Temp
USERDOMAIN=DESKTOP-GCBU4B9
USERDOMAIN_ROAMINGPROFILE=DESKTOP-GCBU4B9
USERNAME=lenovo
USERPROFILE=C:\Users\lenovo
VisualStudioVersion=16.0
VS160COMNTOOLS=D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\
VSCMD_ARG_app_plat=Desktop
VSCMD_ARG_HOST_ARCH=x64
VSCMD_ARG_TGT_ARCH=x86
VSCMD_ARG_VCVARS_VER=14.29.30133
VSCMD_VER=16.0
VSINSTALLDIR=D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\
windir=C:\WINDOWS
CUDA_PATH=D:\Program Files\NAVID GPU Computing Tookit\CUDA\V10.2
CUDA_PATH_V10_2=D:\Program Files\NAVID GPU Computing Tookit\CUDA\V10.2
NVCUDASAMPLES_ROOT=D:\Program Files\NAVID GPU Computing Tookit\CUDA\V10.2
NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
PATH=D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\;D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\;D:\vcpkg\downloads\tools\powershell-core-7.2.6-windows;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\Wbem;C:\WINDOWS\system32\WindowsPowerShell\v1.0\
VSLANG=1033
VSCMD_SKIP_SENDTELEMETRY=1
VCPKG_COMMAND=D:/vcpkg/vcpkg.exe
WindowsLibPath=References\CommonConfiguration\Neutral
WindowsSDKLibVersion=winv6.3\
WindowsSDKVersion=\
X_VCPKG_RECURSIVE_DATA={}

__DOTNET_ADD_32BIT=1
__DOTNET_ADD_64BIT=1
__DOTNET_PREFERRED_BITNESS=64
__VSCMD_PREINIT_PATH=D:\vcpkg\downloads\tools\powershell-core-7.2.6-windows;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\Wbem;C:\WINDOWS\system32\WindowsPowerShell\v1.0\

[DEBUG] CreateProcessW("D:\vcpkg\downloads\tools\cmake-3.24.0-windows\cmake-3.24.0-windows-i386\bin\cmake.exe" -DCURRENT_PORT_DIR=D:/vcpkg/scripts/detect_compiler -DCURRENT_BUILDTREES_DIR=D:/vcpkg/buildtrees/detect_compiler -DCURRENT_PACKAGES_DIR=D:/vcpkg/packages/detect_compiler_x86-windows -D_HOST_TRIPLET=x86-windows -DCMD=BUILD -DDOWNLOADS=D:/vcpkg/downloads -DTARGET_TRIPLET=x86-windows -DTARGET_TRIPLET_FILE=D:/vcpkg/triplets/x86-windows.cmake -DVCPKG_BASE_VERSION=2022-11-10 -DVCPKG_CONCURRENCY=9 -DVCPKG_PLATFORM_TOOLSET=v142 "-DGIT=D:/Program Files/Git/cmd/git.exe" -DVCPKG_ROOT_DIR=D:/vcpkg -DPACKAGES_DIR=D:/vcpkg/packages -DBUILDTREES_DIR=D:/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=D:/vcpkg/installed -DDOWNLOADS=D:/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "D:\vcpkg\scripts\ports.cmake")
[DEBUG] -- Configuring x86-windows
[DEBUG] CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
[DEBUG]     Command failed: D:/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe -v
[DEBUG]     Working Directory: D:/vcpkg/buildtrees/detect_compiler/x86-windows-rel/vcpkg-parallel-configure
[DEBUG]     Error code: 1
[DEBUG]     See logs for more information:
[DEBUG]       D:\vcpkg\buildtrees\detect_compiler\config-x86-windows-CMakeCache.txt.log
[DEBUG]       D:\vcpkg\buildtrees\detect_compiler\config-x86-windows-out.log
[DEBUG]
[DEBUG] Call Stack (most recent call first):
[DEBUG]   scripts/cmake/vcpkg_configure_cmake.cmake:311 (vcpkg_execute_required_process)
[DEBUG]   scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
[DEBUG]   scripts/ports.cmake:147 (include)
[DEBUG]
[DEBUG]
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 1007: cmd_execute_and_stream_data() returned 1 after  3548320 us
[DEBUG]
[DEBUG] Compiler information tracking can be disabled by passing --feature-flags=-compilertracking
error: while detecting compiler information:
The log file content at "D:\vcpkg\buildtrees\detect_compiler\stdout-x86-windows.log" is:
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: D:/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe -v
    Working Directory: D:/vcpkg/buildtrees/detect_compiler/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\detect_compiler\config-x86-windows-CMakeCache.txt.log
      D:\vcpkg\buildtrees\detect_compiler\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:311 (vcpkg_execute_required_process)
  scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:147 (include)



error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.
[DEBUG] D:\a\_work\1\s\src\vcpkg\build.cpp(697):
[DEBUG] Time in subprocesses: 8195295 us
[DEBUG] Time in parsing JSON: 88 us
[DEBUG] Time in JSON reader: 1197 us
[DEBUG] Time in filesystem: 65607 us
[DEBUG] Time in loading ports: 44898 us
[DEBUG] Exiting after 8.687 s (8649917 us)
[config-x86-windows-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10056941/config-x86-windows-CMakeCache.txt.log)
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/10056943/config-x86-windows-out.log)
