### ISSUE TITLE
CUDA: Host compiler targets unsupported OS.

### ISSUE THREAD

**Issue by cmpute** [Microsoft/vcpkg#2791]
I meet this error when build all packages with cuda feature including `opencv[cuda]` and `dlib[cuda]`. The error occured during building process: `nvcc fatal   : Host compiler targets unsupported OS.`

My installations are CUDA 8.0 and VS2017 (with VC141 and VC140), and the problem occured because CUDA 8.0 doesn't support default compiler VC141. I found my solution [here at StackOverflow](https://stackoverflow.com/questions/42003849/nvcc-host-compiler-targets-unsupported-os). However, when I am trying to fix this problem in `pcl[cuda]`, I cannot find `VS140COMNTOOLS` (environment variable) in portfile [as said in my pull request](https://github.com/Microsoft/vcpkg/pull/2775#issuecomment-365175798).

So there are two proposes:
1. Add `VS140COMNTOOLS` or even `VS{XX}COMNTOOLS` to [environment setting](https://github.com/Microsoft/vcpkg/blob/master/toolsrc/src/vcpkg/base/system.cpp#L140) for building process.
2. Add an helper file to cuda installation (like boost-vcpkg-helpers) that contains a helper function, which will check the CUDA version with MSVC version, and fix possible conflicts. With this function, any similar problems can be solved when building with cuda feature.

If the two proposes are reasonable, I will implemented them in my pull request, since I'm in demand of pcl and caffe a.s.a.p

**Comment by jasjuang** [comment]
I think if we can somehow do a check when we do `vcpkg install cuda` and see whether the current version of visual studio supports the currrent version of cuda that will be good enough.

**Comment by cmpute** [comment]
@jasjuang Currently, CUDA 9.0 supports VC140 and VC141, but CUDA 8.0 only supports VC140 which could also be delivered by VS2017. I would suggest reserve the possibility to use CUDA 8.0 with VS2017, for that many modified versions of Caffe need certain version of CUDA, and we could easily achieve this by notify user to install VC140 in VS2017. (If they use VS2015, then there'll be no problem).

Emmm, I'm going to implement this is my PR for an example.

**Comment by ras0219-msft** [comment]
Would simply requiring CUDA 9.0 fix this issue then? If so, we should do that since it is the current latest stable.

**Comment by jasjuang** [comment]
@ras0219-msft I agree, all the major libraries (OpenCV, PCL) supports CUDA 9 and 9.1 now.

**Comment by cmpute** [comment]
It fixes this indeed, but I just wonder if there is a way to prevent me from reinstalling CUDA lol

**Comment by ras0219-msft** [comment]
Sorry :) At least we can make it as easy as possible by giving you a direct link to the MSI!
