### ISSUE TITLE
How do I  limit the max concurrency compile threads num?

### ISSUE THREAD

**Issue by ashesofdream** [microsoft/vcpkg#27926]
When I compile pcl.It seems that memory is not enough that use 30GB of 30GB. How can i limit threads num.

**Comment by ashesofdream** [comment]
i try export  VCPKG_MAX_CONCURRENCY=1. But it seems make no sense.  
![115c74f1e502f2aa01c1636019eb781](https://user-images.githubusercontent.com/53961395/202900310-387b66ad-5e13-46c5-8e67-13c6b23ea9fc.png)

**Comment by dg0yt** [comment]
Evnvironment variable `VCPKG_MAX_CONCURRENCY` is the right input to control concurrency, and I don't see why port pcl shouldn't use it if it is set in the current process scope.
In addition, for common error message related to memory pressure, the build should already restart without concurrency.

**Comment by ashesofdream** [comment]
> Evnvironment variable `VCPKG_MAX_CONCURRENCY` is the right input to control concurrency, and I don't see why port pcl shouldn't use it if it is set in the current process scope. In addition, for common error message related to memory pressure, the build should already restart without concurrency.

`
......./vcpkg/downloads/tools/cmake-3.24.0-linux/cmake-3.24.0-linux-x86_64/bin/cmake --build . --config Release --target install -- -v -j33
`
but the output show that it still use -j33.

**Comment by ashesofdream** [comment]
And the in the `vcpkg/buildtrees/pcl/install-x64-linux-rel-out.log` . 
the only useful message is that `c++: fatal error: Killed signal terminated program cc1plus` . It is very common when memory not enough.

**Comment by dg0yt** [comment]
> but the output show that it still use -j33.

Then you probably didn't set the variable in the right process context.
~~~
export VCPKG_MAX_CONCURRENCY=1
./vcpkg install pcl
~~~

> the only useful message is that `c++: fatal error: Killed signal terminated program cc1plus`. It is very common when memory not enough.

That's why it is in the list of patters which trigger a rebuild without concurrency:
https://github.com/microsoft/vcpkg/blob/4cb4a5c5ddcb9de0c83c85837ee6974c8333f032/scripts/cmake/vcpkg_execute_build_process.cmake#L1-L9

But we only see fragments of your console and log output.
