### ISSUE TITLE
Package [qtwebengine] Build Failure

### ISSUE THREAD

**Issue by charlieJ107** [microsoft/vcpkg#27927]
**Host Environment**

- OS: Windows 11 22H2
- Compiler: MSVC 14.34.31933

**To Reproduce**

`./vcpkg install  qt:x64-windows --x-buildtrees-root=D:\`

**Failure logs**
```
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: D:/Code/vcpkg/downloads/tools/cmake-3.24.0-windows/cmake-3.24.0-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j21
    Working Directory: D:/temp/qtwebengine/x64-windows-dbg
    See logs for more information:
      D:\temp\qtwebengine\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/qtwebengine/portfile.cmake:111 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)


error: building qtwebengine:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qtwebengine
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[qtwebengine]+Build+error
Include '[qtwebengine] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: 4cb4a5c5d 2022-11-18 (2 days
```

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/10049760/install-x64-windows-dbg-out.log)

**Additional context**

Same error occurred when trying `vcpkg install  qtwebengine[core,default-features,geolocation,spellchecker,webchannel]:x64-windows --x-buildtrees-root=./`.

**Comment by Neumann-A** [comment]
> D:\temp\qtwebengine\src\here-src-6-16142a6d06.clean\src\3rdparty\chromium\third_party\skia\src/core/SkShaderCodeDictionary.h(34): error C2039: 'string': is not a member of 'std'

looks like a include is probably missing.

**Comment by charlieJ107** [comment]
> > D:\temp\qtwebengine\src\here-src-6-16142a6d06.clean\src\3rdparty\chromium\third_party\skia\src/core/SkShaderCodeDictionary.h(34): error C2039: 'string': is not a member of 'std'
> 
> looks like a include is probably missing.

Is that a problem with the source code?

**Comment by Neumann-A** [comment]
> Is that a problem with the source code?

Yes. A simple `#include <string>` is probably missing in `SkShaderCodeDictionary.h`

You can add it after you run 
`vcpkg install qtwebengine[core,default-features,geolocation,spellchecker,webchannel]:x64-windows --x-buildtrees-root=D:\ --editable` once and it extracted the archives. (After that CTRL+C to abort building)
Than edit the file (make sure you are not editting in `src/*.clean`) and than rerun.
`vcpkg install qtwebengine[core,default-features,geolocation,spellchecker,webchannel]:x64-windows --x-buildtrees-root=D:\`

**Comment by BillyONeal** [comment]
Fixed by https://github.com/microsoft/vcpkg/pull/27972

**Comment by charlieJ107** [comment]
Great! Installed successfully after pulling the latest changes. Thank you very much for your hard work.
