### ISSUE TITLE
Using sdl2-image doesn't automatically copy webp.dll and used the wrong version.

### ISSUE THREAD

**Issue by harrynull** [microsoft/vcpkg#2792]
vcpkg version used:
0.0.103-2018-01-26-5c9c1bde53f562c11a5248090ad2c63e7e481633

Package related to this issue:
sdl2-image:x86-windows      2.0.2-1
libwebp:x86-windows           0.6.1

There actually are a lot issues with this library. The first issue I went into was:
**1. Using sdl2-image doesn't automatically copy webp.dll**
I used sdl2-image, but webp.dll doesn't automatically be copied into the output directory. However, other dependencies such as tiff.dll, SDL2_image.dll are copied correctly.

I found another issue when I spent a good 3 hours debugging a memory corruption and turned out it was vcpkg that cause the issue --
**2. Sometimes the release version of webp.lib is linked even though I am using debug configuration.**
However, other libraries are linked in their debug version correctly so I believe it is not a issue of my project configuration. That being said, I cannot reproduce this issue by creating another new project -- it's gone in the new project. The debug version is somehow linked correctly.

Moreover,
**3. Is there an option that we can choose not to link some libraries?**
My current workaround is to remove that `webp.lib` file from `vcpkg\installed` and the program links just fine. Clearly webp isn't a necessary dependency of sdl2-image, and I don't use it in my program, but it is linked anyway because of vcpkg attempt to link all possible libraries (as described in #306). I understand the necessity but still it would be nice to have an option to exclude some libraries.

**Comment by JackBoosY** [comment]
Hi @harrynull, thanks for reporting this issue!
I can't reproduce this issue on the latest vcpkg version. Can you update vcpkg, install sdl2-image and reproduce it?

Thanks.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
