### ISSUE TITLE
[openssl] Build error

### ISSUE THREAD

**Issue by chr1stobald** [microsoft/vcpkg#27929]
**Host Environment**

- OS: [e.g. Windows/Linux etc...]: Rocky Linux WSL2/Windows 11
- Compiler: g++ (GCC) 8.5.0 20210514 (Red Hat 8.5.0-15)

**To Reproduce**

`./vcpkg install cpr`

**Failure logs**

Computing installation plan...
The following packages will be built and installed:
    cpr[core,ssl]:x64-linux -> 1.9.2
  * curl[core,non-http,openssl,ssl]:x64-linux -> 7.84.0#2
  * openssl[core]:x64-linux -> 3.0.7#1
  * zlib[core]:x64-linux -> 1.2.13
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Restored 0 package(s) from /home/myuser/.cache/vcpkg/archives in 1.085 ms. Use --debug to see more details.
Installing 1/4 openssl:x64-linux...
Building openssl[core]:x64-linux...
CMake Warning at ports/openssl/portfile.cmake:8 (message):
  openssl currently requires the following library from the system package
  manager:

      linux-headers

  It can be installed on alpine systems via apk add linux-headers.
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)

-- Using cached openssl-openssl-openssl-3.0.7.tar.gz.
-- Cleaning sources at /home/myuser/vcpkg/buildtrees/openssl/src/nssl-3.0.7-96d825e305.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/myuser/vcpkg/downloads/openssl-openssl-openssl-3.0.7.tar.gz
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Using source at /home/myuser/vcpkg/buildtrees/openssl/src/nssl-3.0.7-96d825e305.clean
-- Configuring x64-linux
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: /home/myuser/vcpkg/downloads/tools/cmake-3.24.0-linux/cmake-3.24.0-linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j5
    Working Directory: /home/myuser/vcpkg/buildtrees/openssl/x64-linux-dbg
    See logs for more information:
      /home/myuser/vcpkg/buildtrees/openssl/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/openssl/unix/portfile.cmake:21 (vcpkg_cmake_install)
  ports/openssl/portfile.cmake:33 (include)
  scripts/ports.cmake:147 (include)

error: building openssl:x64-linux failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openssl]+Build+error
Include '[openssl] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: 4cb4a5c5d 2022-11-18 (2 days ago)

Please use the prefilled template from /home/myuser/vcpkg/installed/vcpkg/issue_body.md when reporting your issue.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Cheney-W** [comment]
Please send `/home/myuser/vcpkg/buildtrees/openssl/install-x64-linux-dbg-out.log` to us, thank you!

**Comment by chr1stobald** [comment]
Hello,

Find below the information requested:

cat vcpkg/buildtrees/openssl/install-x64-linux-dbg-out.log
[1/3] cd /mnt/c/Users/Christophe/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.7-96d825e305.clean && export "PATH=/usr/bin:/home/chouchou/.local/bin:/home/chouchou/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files (x86)/VMware/VMware Player/bin/:/mnt/c/VulkanSDK/1.3.211.0/Bin:/mnt/c/Program Files/Microsoft/jdk-11.0.12.7-hotspot/bin:/mnt/c/Python310/Scripts/:/mnt/c/Python310/:/mnt/c/Program Files/Common Files/Oracle/Java/javapath:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/Program Files (x86)/Razer Chroma SDK/bin:/mnt/c/Program Files/Razer Chroma SDK/bin:/mnt/c/Program Files (x86)/Razer/ChromaBroadcast/bin:/mnt/c/Program Files/Razer/ChromaBroadcast/bin:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Windows/system32/config/systemprofile/AppData/Local/Microsoft/WindowsApps:/mnt/c/Program Files/nodejs/:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files (x86)/QuickTime/QTSystem/:/mnt/c/Program Files/CMake/bin:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/PuTTY/:/mnt/c/Users/Christophe/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Christophe/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Program Files/JetBrains/IntelliJ IDEA Community Edition 2021.3.2/bin:/mnt/c/Users/Christophe/AppData/Roaming/npm:/mnt/c/Users/Christophe/vcpkg:/usr/bin:/mnt/c/Users/Christophe/vcpkg/downloads/tools/ninja/1.10.2-linux" && export CC=/usr/bin/cc && export AR=/usr/bin/ar && export LD=/usr/bin/ld && export RANLIB=/usr/bin/ranlib && export MAKE=/usr/bin/make && export MAKEDEPPROG=/usr/bin/cc && export WINDRES= && /usr/bin/perl Configure no-shared no-module enable-static-engine no-zlib no-ssl2 no-idea no-cast no-seed no-md2 no-tests linux-x86_64 --prefix=/mnt/c/Users/Christophe/vcpkg/packages/openssl_x64-linux/debug --libdir=/mnt/c/Users/Christophe/vcpkg/packages/openssl_x64-linux/debug/lib --openssldir=/etc/ssl "-fPIC -g" && /mnt/c/Users/Christophe/vcpkg/downloads/tools/cmake-3.24.0-linux/cmake-3.24.0-linux-x86_64/bin/cmake -DDIR=/mnt/c/Users/Christophe/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.7-96d825e305.clean -P /mnt/c/Users/Christophe/vcpkg/ports/openssl/unix/remove-deps.cmake
FAILED: nssl-3.0.7-96d825e305.clean/Makefile /mnt/c/Users/Christophe/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.7-96d825e305.clean/Makefile
cd /mnt/c/Users/Christophe/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.7-96d825e305.clean && export "PATH=/usr/bin:/home/chouchou/.local/bin:/home/chouchou/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files (x86)/VMware/VMware Player/bin/:/mnt/c/VulkanSDK/1.3.211.0/Bin:/mnt/c/Program Files/Microsoft/jdk-11.0.12.7-hotspot/bin:/mnt/c/Python310/Scripts/:/mnt/c/Python310/:/mnt/c/Program Files/Common Files/Oracle/Java/javapath:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/Program Files (x86)/Razer Chroma SDK/bin:/mnt/c/Program Files/Razer Chroma SDK/bin:/mnt/c/Program Files (x86)/Razer/ChromaBroadcast/bin:/mnt/c/Program Files/Razer/ChromaBroadcast/bin:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Windows/system32/config/systemprofile/AppData/Local/Microsoft/WindowsApps:/mnt/c/Program Files/nodejs/:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files (x86)/QuickTime/QTSystem/:/mnt/c/Program Files/CMake/bin:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/PuTTY/:/mnt/c/Users/Christophe/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Christophe/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Program Files/JetBrains/IntelliJ IDEA Community Edition 2021.3.2/bin:/mnt/c/Users/Christophe/AppData/Roaming/npm:/mnt/c/Users/Christophe/vcpkg:/usr/bin:/mnt/c/Users/Christophe/vcpkg/downloads/tools/ninja/1.10.2-linux" && export CC=/usr/bin/cc && export AR=/usr/bin/ar && export LD=/usr/bin/ld && export RANLIB=/usr/bin/ranlib && export MAKE=/usr/bin/make && export MAKEDEPPROG=/usr/bin/cc && export WINDRES= && /usr/bin/perl Configure no-shared no-module enable-static-engine no-zlib no-ssl2 no-idea no-cast no-seed no-md2 no-tests linux-x86_64 --prefix=/mnt/c/Users/Christophe/vcpkg/packages/openssl_x64-linux/debug --libdir=/mnt/c/Users/Christophe/vcpkg/packages/openssl_x64-linux/debug/lib --openssldir=/etc/ssl "-fPIC -g" && /mnt/c/Users/Christophe/vcpkg/downloads/tools/cmake-3.24.0-linux/cmake-3.24.0-linux-x86_64/bin/cmake -DDIR=/mnt/c/Users/Christophe/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.7-96d825e305.clean -P /mnt/c/Users/Christophe/vcpkg/ports/openssl/unix/remove-deps.cmake
Can't locate IPC/Cmd.pm in @INC (you may need to install the IPC::Cmd module) (@INC contains: /mnt/c/Users/Christophe/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.7-96d825e305.clean/util/perl /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 /mnt/c/Users/Christophe/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.7-96d825e305.clean/external/perl/Text-Template-1.56/lib) at /mnt/c/Users/Christophe/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.7-96d825e305.clean/util/perl/OpenSSL/config.pm line 19.
BEGIN failed--compilation aborted at /mnt/c/Users/Christophe/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.7-96d825e305.clean/util/perl/OpenSSL/config.pm line 19.
Compilation failed in require at Configure line 23.
BEGIN failed--compilation aborted at Configure line 23.
ninja: build stopped: subcommand failed.

**Comment by Cheney-W** [comment]
This is a known issue of openssl, please install `perl-IPC-Cmd` by system package manager.

**Comment by JonLiu1993** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
