### ISSUE TITLE
[osgearth] doesn't bulid for arm64-osx 

### ISSUE THREAD

**Issue by coderc264** [microsoft/vcpkg#27921]
**Host Environment**

- OS: macOS Ventura 13.0
- Compiler: Apple clang version 14.0.0 (clang-1400.0.29.202)

**To Reproduce**

`./vcpkg install osgearth`

**Failure logs**

Computing installation plan...
x265[core]:arm64-osx is only supported on '!(uwp | arm)'

**Comment by JonLiu1993** [comment]
@coderc264, Thanks for posting this issue, please provide the whole error log.

**Comment by coderc264** [comment]
Where is located? Because in the "buildtrees" i didn't find it

**Comment by dg0yt** [comment]
> x265[core]:arm64-osx is only supported on '!(uwp | arm)'

There can't be a log because the build didn't start.
The x265 dependency comes via libheif via openimageio via the openimageio feature of osg.
So the workaround is to build `osg[core,...your desired features...]`.

**Comment by JackBoosY** [comment]
@MonicaLiu0311 Label should be port feature and community triplet.

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
