### ISSUE TITLE
`pyton3` build failure

### ISSUE THREAD

**Issue by goodguysoft** [microsoft/vcpkg#27940]
**Host Environment**

- OS: Windows 11 Pro
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31630 for x64

**To Reproduce**

`./vcpkg --triplet=x64-windows-static install python3`

**Failure logs**

Computing installation plan...
The following packages will be built and installed:
  * python3[core]:x64-windows -> 3.10.5#4
    python3[core]:x64-windows-static -> 3.10.5#4
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x64-windows-static...
Restored 0 package(s) from C:\Users\Vitaliy\AppData\Local\vcpkg\archives in 583.1 us. Use --debug to see more details.
Installing 1/2 python3:x64-windows...
Building python3[core]:x64-windows...
-- Using cached python-cpython-v3.10.5.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/python3/src/v3.10.5-763741728b.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/python-cpython-v3.10.5.tar.gz
-- Applying patch 0002-use-vcpkg-zlib.patch
-- Applying patch 0003-devendor-external-dependencies.patch
-- Applying patch 0004-dont-copy-vcruntime.patch
-- Applying patch 0005-only-build-required-projects.patch
-- Applying patch 0009-python.pc.patch
-- Applying patch 0010-bz2d.patch
-- Applying patch 0011-dont-skip-rpath.patch
-- Using source at C:/vcpkg/buildtrees/python3/src/v3.10.5-763741728b.clean
-- Building PCbuild/pcbuild.proj for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: msbuild C:/vcpkg/buildtrees/python3/x64-windows-rel/v3.10.5-763741728b.clean/PCbuild/pcbuild.proj /p:Configuration=Release /p:IncludeExtensions=true /p:IncludeExternals=true /p:IncludeCTypes=true /p:IncludeSSL=true /p:IncludeTkinter=false /p:IncludeTests=false /p:ForceImportBeforeCppTargets=C:/vcpkg/buildtrees/python3/src/v3.10.5-763741728b.clean/PCbuild/python_vcpkg.props /p:IncludeUwp=false /p:_VcpkgPythonLinkage=DynamicLibrary /t:Rebuild /p:Platform=x64 /p:PlatformToolset=v143 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.19041.0 /p:VcpkgTriplet=x64-windows /p:VcpkgInstalledDir=C:/vcpkg/installed /p:VcpkgManifestInstall=false /p:UseMultiToolTask=true /p:MultiProcMaxCount=1 /p:EnforceProcessCountAcrossBuilds=true /m:1
    Working Directory: C:/vcpkg/buildtrees/python3/x64-windows-rel/v3.10.5-763741728b.clean
    Error code: Access violation
    See logs for more information:
      C:\vcpkg\buildtrees\python3\build-x64-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_msbuild.cmake:79 (vcpkg_execute_required_process)
  ports/python3/portfile.cmake:145 (vcpkg_install_msbuild)
  scripts/ports.cmake:147 (include)

error: building python3:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+python3
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[python3]+Build+error
Include '[python3] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: 6f7ffeb18 2022-11-11 (10 days ago)

**Additional context**

This is Hyper-V virtual machine. The hard drive is physical one dedicated to this machine. Mother OS is Windows Server 2022.

Log file is an empty one.

[build-x64-windows-rel-err.log](https://github.com/microsoft/vcpkg/files/10057793/build-x64-windows-rel-err.log)

**Comment by Cheney-W** [comment]
You can try to open Powershell with administrator privileges and reinstall the port, or you can clone vcpkg to another drive letter, like E or F.

**Comment by goodguysoft** [comment]
> You can try to open Powershell with administrator privileges and reinstall the port, or you can clone vcpkg to another drive letter, like E or F.

1. There is disk `C` only on this computer. 
2. Building as administrator doesn't help. I also ensured that I gave required file system access permissions before I submitted this report.
3. About other possible advises, no, disabling antivirus doesn't help.

**Comment by dg0yt** [comment]
> You can try to open Powershell with administrator privilege

Most of the times, this is wrong.
