### ISSUE TITLE
[llvm] Build error 

### ISSUE THREAD

**Issue by red-patriot** [microsoft/vcpkg#27943]
**Host Environment**

- OS: Windows 10
- Compiler: MSVC v143

**To Reproduce**

1. Open a powershell window (I am using PS version 7.1.3).
2. Run the command `vcpkg install llvm`
3. The command will run for about 2 hr 45 min and then produce an error with the attached error log
- In the above step, it looks like the debug build completes successfully, but the release build fails.
- In the log file, it looks like there is a linker error but I am unsure how to resolve it.

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.
[install-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/10052773/install-x86-windows-rel-out.log)

**Additional context**

From what I see in the log file, it looks like the linker is complaining about a lack of memory to link LLVMCore. My system has 16GB of RAM and when the error happens, I am nowhere near running out (usually I am sitting at or below 50% usage, but it has varied a little bit between runs).

Add any other context about the problem here, such as what you have already tried to resolve the issue.

I have tried upgrading vcpkg and running `git pull` and `vcpgk update` in the appropriate directory like the error message suggests, but that doesn't help.

**Comment by StarGate-One** [comment]
> lib\LLVMCore.lib : fatal error LNK1180: insufficient disk space to complete link

The process ran out of sufficient disk space to complete the linking process - need to cleanup the hard drive where vcpkg instance resides.

**Comment by Adela0814** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
