### ISSUE TITLE
Ceres applying patch fails

### ISSUE THREAD

**Issue by patrikhuber** [Microsoft/vcpkg#2797]
This probably shouldn't fail:
```
Building package ceres[core]:x64-windows...
-- CURRENT_INSTALLED_DIR=C:/Users/Patrik/vcpkg/installed/x64-windows
-- DOWNLOADS=C:/Users/Patrik/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/Patrik/vcpkg/packages/ceres_x64-windows
-- CURRENT_BUILDTREES_DIR=C:/Users/Patrik/vcpkg/buildtrees/ceres
-- CURRENT_PORT_DIR=C:/Users/Patrik/vcpkg/ports/ceres/.
-- Downloading https://github.com/ceres-solver/ceres-solver/archive/1.13.0.tar.gz...
-- Downloading https://github.com/ceres-solver/ceres-solver/archive/1.13.0.tar.gz... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting source C:/Users/Patrik/vcpkg/downloads/ceres-solver-ceres-solver-1.13.0.tar.gz
-- Extracting done
-- Applying patch C:/Users/Patrik/vcpkg/ports/ceres/fix-find-packages.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/Users/Patrik/vcpkg/ports/ceres/fix-find-packages.patch done
```

**Comment by KindDragon** [comment]
> This probably shouldn't fail:

Only for the first build ` This is expected if this patch was previously applied.`

**Comment by patrikhuber** [comment]
It was my first time installing ceres.

**Comment by KindDragon** [comment]
Perhaps it was installed as a dependence for something

**Comment by patrikhuber** [comment]
None of the packages that I've installed in vcpkg would pull in Ceres as a dependency. And I think I would've noticed, the build takes over half an hour.

Are you saying you're not getting the error?

If you tell me how to do a complete clean of the Ceres package and reinstall, to check if the error occurs again, I'm happy to do that.

**Comment by jasjuang** [comment]
OpenCV could be pulling ceres if you are compiling with the `sfm` feature package. Try remove ceres in the `buildtree` folder and install again.

**Comment by patrikhuber** [comment]
Nope I was definitely not pulling `opencv[sfm]`, and I would've noticed if it had pulled in Ceres and all its vcpkg dependencies.
As a matter of fact I was starting with an empty `buildtrees` folder today. But I deleted it again and installed Ceres anew - the patch still fails.

**Comment by vicroms** [comment]
Latest port (Ceres 1.14) doesn't require patches.

**Comment by patrikhuber** [comment]
@vicroms Shouldn't the patch be removed then? Is there an associated commit that fixes this?

**Comment by vicroms** [comment]
It is removed on master, here's the [commit that removes the patch](https://github.com/Microsoft/vcpkg/commit/18be859328565eec58b6eb5952b585f66cb6b6fd).

And here's the [latest commit](https://github.com/Microsoft/vcpkg/commit/64ab9dc274c352f9999f2cc4e8f7f6830cc56c42) using Ceres 1.14.

**Comment by patrikhuber** [comment]
Awesome! The first commit was actually three days after I reported this problem, so it seems it just was never referenced :-) Thank you!
