### ISSUE TITLE
[eve]  port can't use after installed.

### ISSUE THREAD

**Issue by jiayuehua** [microsoft/vcpkg#27989]
**Describe the bug**
after ./vcpkg install eve
add this line  find_package(eve CONFIG REQUIRED) to CMakeLists.txt
and when configure , report can't find eve-config.cmake.

**Environment**
- OS: Linux
- Compiler: gcc 11.2

**To Reproduce**
1. ./vcpkg install eve
2. add  find_package(eve CONFIG REQUIRED) 
3. configure add see configure error
Repro code when

**Expected behavior**
Should can use find_package to find eve port.

**Failure logs**
-(please attached failure logs)
1> [CMake] CMake Error at /home/rob/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package):
1> [CMake]   Could not find a package configuration file provided by "eve" with any of
1> [CMake]   the following names:
1> [CMake] 
1> [CMake]     eveConfig.cmake
1> [CMake]     eve-config.cmake
1> [CMake] 
1> [CMake]   Add the installation prefix of "eve" to CMAKE_PREFIX_PATH or set "eve_DIR"
1> [CMake]   to a directory containing one of the above files.  If "eve" provides a
1> [CMake]   separate development package or SDK, be sure it has been installed.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   clang_rename/CMakeLists.txt:8 (find_package)
**Additional context**

**Comment by FrankXie05** [comment]
@jiayuehua `eve` is not exporting cmake config correctly, it's a port bug and I will fix it by adding or exporting usage. :)
