### ISSUE TITLE
[mpfr] Avoid using mulx on Windows

### ISSUE THREAD

**Issue by fkonvick** [microsoft/vcpkg#28005]
I built mpfr for x64-windows-static and then deployed code linking the resulting library to a virtualized WS 2008 R2 server.  The application that linked the binary crashed within MPFR's implementation of `sqrt` with "illegal instruction".  It turned out that the mpfr port configured MPFR to use build machine's CPU features, which included the `mulx` instruction, which isn't available on the host where it crashed.

OS: Windows 11 x64 (build), Windows Server 2008 R2 (host)
Compiler: Visual Studio 2019 16.10

I have discussed this with the MPFR developers.  I tried building MPFR by hand using the same compiler, but via Cygwin.  The first option that worked was compiling with the flag `CFLAGS=/D_mulx_u64=not_working__mulx_u64`, which fools `configure` into believing that `mulx` isn't available.  This of course is a hack.  The preferred option should be cross-compiling for the generic x64 Windows host.  What worked for me was using `./configure --build=x86_64-pc-cygwin --host=amd64-pc-cygwin`.  This causes that any host-specific optimization checks are skipped.

I believe that this mpfr port should be doing something similar.  I was discussing this here https://github.com/microsoft/vcpkg/issues/27957 - based on the discussion, it looks like the gmp port is using a customized `config.guess` and `config.sub` to reach similar goals.

A simple indicator that the configuration is correct for a generic build is that `HAVE_MULX_U64` is not included in the generated Makefile `DEFS` (provided that the build machine actually does support `mulx`).

**Comment by Neumann-A** [comment]
This is a case for a overlay triplet with `VCPKG_CONFIGURE_MAKE_OPTIONS` set to disable the problematic configure check (by controlling the associated variable).

**Comment by fkonvick** [comment]
Thanks!

My point is that the default mpfr package build results in something that may crash when run on another computer.  I for one did not expect this.  Maybe others are fine with this.  I'm not sure what the standard behavior should be, I'm rather new to using vcpkg.

As for the variable - just to make sure, I believe the correct spelling is `VCPKG_MAKE_CONFIGURE_OPTIONS`.
I already tried `set(VCPKG_MAKE_CONFIGURE_OPTIONS "--build=x86_64-pc-cygwin --host=amd64-pc-cygwin")` but that didn't work (I guess because vcpkg uses mingw rather than cygwin for building the package).  I tried several other combinations, incuding `VCPKG_MAKE_CONFIGURE_OPTIONS=--host=amd64-pc-mingw32`, but none seem to have worked.  `config.log` keeps saying `configure --build=x86_64-pc-mingw32` with no mention of 'host', and the ac checks get run, resulting in the `mulx` instruction being used.  Basically I'm trying to build on `x86_64-pc-mingw32` for `x86_64-pc-mingw32`, but as a cross-compile.  On Cygwin I succeeded replacing `x86_64` with `amd64` for the host spec, but this does not seem to work here.  Any ideas?

**Comment by Neumann-A** [comment]
the config.log contains a list of variables near its end. You need to find the variable which you need to control. Otherwise if you want to keep your `--build/host` stuff use `VCPKG_MAKE_BUILD_TRIPLET`

**Comment by fkonvick** [comment]
I have discussed with the MPFR team and I was clearly advised to use cross-compilation for producing the binary rather than deal with individual flags; that is not a stable long-term solution.

Sorry but my point remains unchanged - the built package crashes.  It's as simple as running `vcpkg install mpfr:x64-windows-static` and then running your compiled app on another PC.  Is the average user of vcpkg expected to be aware of this?

Regarding `VCPKG_MAKE_BUILD_TRIPLET`, the only info I found on this is [here](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_configure_make.md), but this looks to me like this is meant for port authors/maintainers rather than vcpkg end users.  I still do not see how I should invoke vcpkg to produce the cross-compile.  Again, I'm basically targetting the same platform as I'm building on, but this does not seem to be detected as a cross-compile.  But it is the cross-compilation mode that causes the dangerous optimizations to be skipped by MPFR's configure script.

**Comment by Neumann-A** [comment]
>  that is not a stable long-term solution.

I see upstream knowing nothing. I also see upstream being stupid and not supporting cross-compling correctly and giving no option to control the behavior of the required define o.O. What if I want to crosscompile from a platform without BMI2 to a platform with BMI2? -> simply not supported by upstream ......

>  but this looks to me like this is meant for port authors/maintainers rather than vcpkg end users.

If it is `VCPKG_` prefixed it is meant for users. Otherwise it would be `Z_VCPKG_` for internal stuff. In this case it is a triplet variable. 
You can just do `set(VCPKG_MAKE_BUILD_TRIPLET "--build=x86_64-pc-cygwin --host=amd64-pc-cygwin")` as per port customization for mpfr. 

> Is the average user of vcpkg expected to be aware of this?

Something needs to be host so `x64-windows` is host. It will assume this to be a native triplet. Also BMI2 is nearly ten years old by now.

**Comment by fkonvick** [comment]
Apparently this is getting frustrating, so I'll try to keep it short: the gmp port actively prevents including build machine specific CPU instructions.  I believe that this is in-line with the `vcpkg export` idea - "...quickly and reliably shared with build servers...".  The mpfr port is not doing this.  This is why I opened this issue.  If I misunderstood please feel free to close this issue.

I have additional information but at this point I'm not sure whether it's welcome.

**Comment by fkonvick** [comment]
@sfhacker Thank you!  That's very kind of you.

I am trying to help build a new binary release of [Gecode](https://www.gecode.org/).  The original main author passed away a couple years back and some of the packaging scripts are no longer available.  I thought I would contribute back by recreating the missing pieces and I was looking for different ways of building the dependencies.  I tried vcpkg and it looked good, but half by accident I ran into this issue and I was then looking for other options.

Since Cygwin has been used for building the Gecode binaries previsouly this seemed like the natural next choice, and I'm sure that it does work properly.  In this setup we're using the MSVC toolchain together with the usual 'configure & make'.  It works well and it does produce native MSVC toolchain compatible binaries.  Thanks to this I was able to build with debug symbols and pinpoint the exact location of the bug (I first thought that the more probable culprit was GMP) and then I found out which MPFR's configure checks were causing this.  I was then discussing over at the MPFR mailing list with the authors regarding the best approach to avoid CPU-specific code so that when someone gets the binary they won't get crashes (the previous Gecode release did not crash in the same spot, but I suspect that this is because at that point MPFR did not yet employ this particular optimization).  I also switched to using MPIR instead of GMP as a part of this (which is consistent with the previous Gecode release).

So, I don't really need to use vcpkg now because I have another way of producing what I need.  What I thought was that other people could get hurt by the same issue and I though that I'd report this here.  Just trying to contribute my findings back to the community.

**Comment by dg0yt** [comment]
@fkonvick I'm thankful that you reported it here so that it can be fixed in vcpkg.

**Comment by fkonvick** [comment]
Based on the above suggestions I have already tried many combinations but none seem to have any effect on the configuration process.  I tried setting `VCPKG_MAKE_BUILD_TRIPLET` and `VCPKG_MAKE_CONFIGURE_OPTIONS` to combinations of `amd64-pc-mingw32`, `x86_64-pc-windows-msvc`, and `x86_64-pc-mingw32`.  It only ever shows `--build=x86_64-pc-mingw32` in `config.log`.  Setting `VCPKG_CROSSCOMPILING=1` adds `--target=x86_64-pc-windows-msvc` but again does not change anything important.

So I'm running out of ideas.  It looks to me like some mechanism is overriding my settings.

**Comment by fkonvick** [comment]
And one other thing that I noticed: installing `mpfr:x64-windows-static-md` builds both `gmp:x64-windows` and `gmp:x64-windows-static-md`.  This looks like a separate issue to me; if I noticed correctly this could be related to the 'host' setting somewhere in the port settings.

**Comment by dg0yt** [comment]
> And one other thing that I noticed: installing `mpfr:x64-windows-static-md` builds both `gmp:x64-windows` and `gmp:x64-windows-static-md`.

This normal when target triplet != host triplet, in vcpkg terminology.

**Comment by fkonvick** [comment]
> > And one other thing that I noticed: installing `mpfr:x64-windows-static-md` builds both `gmp:x64-windows` and `gmp:x64-windows-static-md`.
> 
> This is normal when target triplet != host triplet, in vcpkg terminology, and the build needs tools which run on the host machine and OS.

OK, I'll take your word for it :)  It surprised me as I can't see what for does it need the `x64-windows` variant; GMP is just a library, not a tool, after all.  I'm sure I can manually build the equivalent of `x64-windows-static-md` of GMP and MPFR without the `x64-windows` extra step.  But this just slows down the process a bit and does not cause other issues.  I found a "dependecy on self" in `ports/gmp/vcpkg.json`  saying `{ "name": gmp "host": true }`, so this is probably what is triggering this step.

**Comment by Neumann-A** [comment]
> I can't see what for does it need the x64-windows variant; 

code generators. Pass `--host-triplet=x64-windows-static-md` or pass `VCPKG_HOST_TRIPLET` in cmake to avoid it.

**Comment by fkonvick** [comment]
So, after countless hours of trial and error :D, I succeeded in the end by using the following 2 approaches.

Number 1:

```
vcpkg install mpfr:x64-windows-static-md --overlay-triplets=custom-triplets --host-triplet=x64-windows-static-md
```

My custom triplet being a copy of `x64-windows-static-md` with the following line added:
```
set(VCPKG_MAKE_BUILD_TRIPLET "--host=x64 --build=x86_64-pc-mingw32")
```

It does not suffice to set the `--host=x64` alone.  I also tried adding `DETERMINE_BUILD_TRIPLET` to the port instead of explicitly setting `--build` but this didn't work.  In any case this caused `configure` to switch to the cross-compilation mode and refrain from using `mulx`, preventing the crash.

I don't even remember how I arrived at the value of `VCPKG_MAKE_BUILD_TRIPLET` that finally worked (I swear I did not resort to dark magic; it was probably just a lot of Google + code/log research), but I'm certain it was not thanks to documented examples/how-tos.

The second approach that worked was adding the following to the port (I used a port overlay):

```
if(VCPKG_TARGET_IS_WINDOWS)
  set(VCPKG_C_FLAGS "-UHAVE_MULX_U64 ${VCPKG_C_FLAGS}")
  set(VCPKG_CXX_FLAGS "-UHAVE_MULX_U64 ${VCPKG_CXX_FLAGS}")
endif()
```

just prior to `vcpkg_configure_make`.  As I said before this may not be the preferred approach, but it does work for this particular optimization.

I leave it up to you guys whether or not to use it to make any modifications to the port.

Thanks for all the help everyone.  It's been a long thread and I think a lengthy discussion such as this belongs in a users' discussion list, but I haven't been able to find one quickly enough.

**Comment by Neumann-A** [comment]
`-UHAVE_MULX_U64` hmm I might have misread the documentation then because somehow it stated it can only remove `-D` cmd lines defines but not `#define` in a header

**Comment by fkonvick** [comment]
> `-UHAVE_MULX_U64` hmm I might have misread the documentation then because somehow it stated it can only remove `-D` cmd lines defines but not `#define` in a header

I had a similar remark when this was advised to me.  Apparently configure puts the define in the Makefile DEFS and the CFLAGS take precedence.  In any case it did work, I tested it to make sure.

**Comment by fkonvick** [comment]
> Number 1:

P.S. - only later I found out that the gmp port fails to build with the first method.  So the host/build specification has to be put in a port overlay of mpfr instead, as such:

```
vcpkg_configure_make(
    SOURCE_PATH "${SOURCE_PATH}"
    BUILD_TRIPLET "--host=x64 --build=x86_64-pc-mingw32"
    AUTOCONFIG
    ADDITIONAL_MSYS_PACKAGES autoconf-archive
)
```

**Comment by Neumann-A** [comment]
You can have per port customization in the triplet via `if(PORT MATCHES "something")`

**Comment by fkonvick** [comment]
I am becoming more educated by the day.

Apparently, the configure process on Linux, and perhaps with MSys (cc @sfhacker ) on Windows as well, is not assuming that the non-standard x86_64 instructions are available, unless specific flags such as `-mbmi2` are provided.  This seems to be broken when MSVC gets involved.  MSVC's CL defaults to using SSE2 and `/arch` only accepts `AVX`, `AVX2` and `AVX512` as options for x64.  But unlike on Linux, `#include <immintrin.h>` unconditionally contains all intrinsics and happily compiles this with any host architecture specification:
```
#include <immintrin.h>
int main() {
  unsigned long long x;
  _mulx_u64 (0, 0, &x);
}
```
The [docs](https://learn.microsoft.com/en-us/cpp/intrinsics/x64-amd64-intrinsics-list) says one should use `__cpuid()` to check for instruction availability at runtime.  So the autotools/configure are mislead into believing that they are fine to use `_mulx_u64`.  So it looks to me like the combination of autotools + MSVC toolchain is fundamentally dangerous.

I think that the mpfr port should reflect this by using the workaround that I suggested [above](https://github.com/microsoft/vcpkg/issues/28005#issuecomment-1328130524) when building for x64 using MSVC.

**Comment by fkonvick** [comment]
FWIW, as a followup to this issue, MPFR has just gotten rid of `mulx` on its master branch [here](https://gitlab.inria.fr/mpfr/mpfr/-/commit/001d4561ba6fa702f49eb40609f5e51c34db3213); but this will only be available in one of the following releases.

**Comment by fkonvick** [comment]
@Cheney-W Hi, I'm not sure what the next step is here.  This issue is labeled "question", IMHO this should be "port bug".

I have been discussing this extensively here and with the MPFR library developers.  The conclusion is that using the library's configure script with the MSVC toolchain leads to dangerous results and the resulting binary may indeed contain unexpected CPU instructions, which may result in crashes.  Since this port is using this very approach (combining _configure_ and MSVC), it should take appropriate measures to work around known issues.  The comments above show how this could be done.

Please let me know if anything is unclear.
