### ISSUE TITLE
[openssl] Build error 0xc0000409, but maybe a generic problem for new pwsh

### ISSUE THREAD

**Issue by fakeboboliu** [microsoft/vcpkg#28025]
Package: openssl[core]:arm64-windows -> 3.0.7#1

**Host Environment**

- Host: arm64-windows (Windows Dev Kit 2023, 25247.1000)
- Compiler: MSVC 19.34.31933.0
-    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: 62d01b70d 2022-11-25 (30 hours ago)

**To Reproduce**

Use the latest version of vcpkg with pwsh 7.3.0, and

`vcpkg install openssl:arm64-windows`

**To Mitigate for now**

`git checkout -f 6f7ffeb` to use 2022.11.14 Release with pwsh 7.2.6

**Failure logs**

```
-- Using cached openssl-openssl-openssl-3.0.7.tar.gz.
-- Cleaning sources at C:/dev/vcpkg/buildtrees/openssl/src/nssl-3.0.7-96d825e305.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/openssl-openssl-openssl-3.0.7.tar.gz
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Using source at C:/dev/vcpkg/buildtrees/openssl/src/nssl-3.0.7-96d825e305.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for arm64-windows
-- Getting CMake variables for arm64-windows
-- Prerunning arm64-windows-dbg
-- Building arm64-windows-dbg
-- Prerunning arm64-windows-rel
-- Building arm64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: C:/dev/vcpkg/downloads/tools/powershell-core-7.3.0-windows/pwsh.exe -noprofile -executionpolicy Bypass -nologo -file C:/dev/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/dev/vcpkg/packages/openssl_arm64-windows/tools/openssl/openssl.exe -installedDir C:/dev/vcpkg/packages/openssl_arm64-windows/bin -verbose
    Working Directory: C:/dev/vcpkg
    Error code: Exit code 0xc0000409

  

    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:9 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:41 (z_vcpkg_copy_tool_dependencies_search)
  scripts/cmake/vcpkg_copy_tools.cmake:48 (vcpkg_copy_tool_dependencies)
  ports/openssl/windows/portfile.cmake:111 (vcpkg_copy_tools)
  ports/openssl/portfile.cmake:30 (include)
  scripts/ports.cmake:147 (include)
```

**Additional context**

It seems like a pwsh problem,
but I can't reproduce it by just running the failed command.
This problem only occurs with `vcpkg install`.

**Comment by fakeboboliu** [comment]
It seems pwsh is bumped in 62d01b7, so it should also be mitigated by checkout 22bb9aa.

**Comment by sglvladi** [comment]
I'm experiencing the same on x86-windows

**Comment by JackBoosY** [comment]
@MonicaLiu0311 Should be a vcpkg bug, please tag it after you can reproduce this issue using the same powershell version.

**Comment by MonicaLiu0311** [comment]
It was successful on win10 and finally reproduced on win11.
Internal fixing: https://github.com/microsoft/vcpkg/pull/28058.
Upstream related: https://github.com/PowerShell/PowerShell/issues/18545.
(Please use pwsh 7.2.6 for the time being.)
