### ISSUE TITLE
[vcpkg-tool-meson] Build error

### ISSUE THREAD

**Issue by likui** [microsoft/vcpkg#28039]
**Host Environment**
Windows
- Compiler: vs 2022

**To Reproduce**

`./vcpkg install paraview`

**Failure logs**

Building vcpkg-tool-meson[core]:x64-windows...
-- Downloading https://www.python.org/ftp/python/3.10.5/python-3.10.5-embed-amd64.zip -> python-3.10.5-embed-amd64.zip...
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: E:/Dev/tools/vcpkg/vcpkg-2022.11.14/downloads/python-3.10.5-embed-amd64.zip
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" -E rm python310._pth
    Working Directory: E:/Dev/tools/vcpkg/vcpkg-2022.11.14/downloads/tools/python/python-3.10.5-x64
    Error code: 1
    See logs for more information:
      E:\Dev\tools\vcpkg\vcpkg-2022.11.14\buildtrees\vcpkg-tool-meson\ [PYTHON3-tool-post-install-err.log](https://github.com/microsoft/vcpkg/files/10102703/PYTHON3-tool-post-install-err.log)

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:685 (vcpkg_execute_required_process)
  ports/vcpkg-tool-meson/portfile.cmake:23 (vcpkg_find_acquire_program)
  scripts/ports.cmake:147 (include)

error: building vcpkg-tool-meson:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+vcpkg-tool-meson
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[vcpkg-tool-meson]+Build+error
Include '[vcpkg-tool-meson] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: unknown

**Comment by Cheney-W** [comment]
What's the version of your local cmake: `C:/Program Files/CMake/bin/cmake.exe`?
Could you try removing the local cmake path from the environment variable PATH and reinstalling the port?

**Comment by likui** [comment]
> What's the version of your local cmake: `C:/Program Files/CMake/bin/cmake.exe`? 

3.25.0

> Could you try removing the local cmake path from the environment variable PATH and reinstalling the port?

Installing 1/5 yasm:x64-windows...
Building yasm[core,tools]:x64-windows...
-- Using cached yasm-yasm-009450c7ad4d425fa5a10ac4bd6efbd25248d823.tar.gz.
-- Cleaning sources at E:/Dev/tools/vcpkg/vcpkg/buildtrees/yasm/src/d25248d823-c7caeb1623.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/Dev/tools/vcpkg/vcpkg/downloads/yasm-yasm-009450c7ad4d425fa5a10ac4bd6efbd25248d823.tar.gz
-- Applying patch add-feature-tools.patch
-- Applying patch fix-arm-cross-build.patch
-- Using source at E:/Dev/tools/vcpkg/vcpkg/buildtrees/yasm/src/d25248d823-c7caeb1623.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: E:/Dev/tools/vcpkg/vcpkg/downloads/tools/cmake-3.24.0-windows/cmake-3.24.0-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j17
    Working Directory: E:/Dev/tools/vcpkg/vcpkg/buildtrees/yasm/x64-windows-dbg
    See logs for more information:
      E:\Dev\tools\vcpkg\vcpkg\buildtrees\yasm\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/yasm/portfile.cmake:41 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)


error: building yasm:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+yasm
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[yasm]+Build+error
Include '[yasm] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: unknown


[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/10112970/install-x64-windows-dbg-out.log)

**Comment by Cheney-W** [comment]
I can't reproduce this issue with latest vcpkg, could you please try the following commands:
```
1. git pull
2. .\bootstrap-vcpkg.bat
3. .\vcpkg.exe install yasm:x64-windows --editable --binarysource=clear
```

**Comment by JackBoosY** [comment]
```
[50/128] cmd.exe /C "cd /D E:\Dev\tools\vcpkg\vcpkg\buildtrees\yasm\x64-windows-dbg\frontends\yasm && E:\Dev\tools\vcpkg\vcpkg\downloads\tools\python\python-3.10.5-x64\python.exe E:/Dev/tools/vcpkg/vcpkg/buildtrees/yasm/src/d25248d823-c7caeb1623.clean/frontends/yasm/genstring.py license_msg E:/Dev/tools/vcpkg/vcpkg/buildtrees/yasm/x64-windows-dbg/frontends/yasm/license.c E:/Dev/tools/vcpkg/vcpkg/buildtrees/yasm/src/d25248d823-c7caeb1623.clean/COPYING"
```
Please remove folder `E:\Dev\tools\vcpkg\vcpkg\downloads\tools\python\python-3.10.5-x64\` then try again.

**Comment by likui** [comment]
> I can't reproduce this issue with latest vcpkg, could you please try the following commands:
> 
> ```
> 1. git pull
> 2. .\bootstrap-vcpkg.bat
> 3. .\vcpkg.exe install yasm:x64-windows --editable --binarysource=clear
> ```

PS E:\Dev\tools\vcpkg\vcpkg-git\vcpkg> .\vcpkg.exe install yasm:x64-windows --editable --binarysource=clear
Computing installation plan...
The following packages will be built and installed:
  * vcpkg-cmake[core]:x64-windows -> 2022-10-30
  * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06#1
    yasm[core,tools]:x64-windows -> 1.3.0#5
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
-- Automatically setting HTTP(S)_PROXY environment variables to "127.0.0.1:30822".
A suitable version of powershell-core was not found (required v7.2.7) Downloading portable powershell-core 7.2.7...
Extracting powershell-core...
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: E:\Dev\tools\vcpkg\vcpkg-git\vcpkg\downloads\PowerShell-7.2.7-win-x86.zip
'CMake' failed while extracting E:\Dev\tools\vcpkg\vcpkg-git\vcpkg\downloads\PowerShell-7.2.7-win-x86.zip.

**Comment by likui** [comment]
> ```
> [50/128] cmd.exe /C "cd /D E:\Dev\tools\vcpkg\vcpkg\buildtrees\yasm\x64-windows-dbg\frontends\yasm && E:\Dev\tools\vcpkg\vcpkg\downloads\tools\python\python-3.10.5-x64\python.exe E:/Dev/tools/vcpkg/vcpkg/buildtrees/yasm/src/d25248d823-c7caeb1623.clean/frontends/yasm/genstring.py license_msg E:/Dev/tools/vcpkg/vcpkg/buildtrees/yasm/x64-windows-dbg/frontends/yasm/license.c E:/Dev/tools/vcpkg/vcpkg/buildtrees/yasm/src/d25248d823-c7caeb1623.clean/COPYING"
> ```
> 
> Please remove folder `E:\Dev\tools\vcpkg\vcpkg\downloads\tools\python\python-3.10.5-x64\` then try again.

PS E:\Dev\tools\vcpkg\vcpkg> .\vcpkg.exe install paraview
Computing installation plan...
The following packages will be built and installed:
  * harfbuzz[core]:x64-windows -> 5.0.1#3
  * icu[core]:x64-windows -> 71.1
  * jasper[core,default-features,opengl]:x64-windows -> 2.0.33#6
  * jsoncpp[core]:x64-windows -> 1.9.5
  * libharu[core]:x64-windows -> 2.4.2
  * libiconv[core]:x64-windows -> 1.17
  * libogg[core]:x64-windows -> 1.3.5
  * libtheora[core]:x64-windows -> 1.2.0alpha1-20170719#5
  * libxml2[core]:x64-windows -> 2.9.14#1
  * lz4[core]:x64-windows -> 1.9.3#4
  * netcdf-c[core,dap,hdf5,nczarr,netcdf-4,platform-default-features]:x64-windows -> 4.8.1#2
  * nlohmann-json[core]:x64-windows -> 3.11.2
    paraview[core]:x64-windows -> 5.9.1#2
  * pegtl-2[core]:x64-windows -> 2.8.3#1
  * pkgconf[core]:x64-windows -> 1.8.0#3
  * proj[core,net,tiff]:x64-windows -> 9.1.0
  * pugixml[core]:x64-windows -> 1.12.1#1
  * qt5-activeqt[core]:x64-windows -> 5.15.7
  * qt5-base[core]:x64-windows -> 5.15.7#1
  * qt5-declarative[core]:x64-windows -> 5.15.7
  * qt5-imageformats[core]:x64-windows -> 5.15.7
  * qt5-svg[core]:x64-windows -> 5.15.7
  * qt5-tools[core]:x64-windows -> 5.15.7
  * qt5-xmlpatterns[core]:x64-windows -> 5.15.7
  * sqlite3[core,tool]:x64-windows -> 3.39.2
  * utfcpp[core]:x64-windows -> 3.2.1#1
  * vcpkg-pkgconfig-get-modules[core]:x64-windows -> 2022-02-10#1
  * vtk[atlmfc,core,paraview,qt]:x64-windows -> 9.0.3-pv5.9.1#12
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
-- Automatically setting HTTP(S)_PROXY environment variables to "127.0.0.1:30822".
Restored 0 package(s) from C:\Users\likui\AppData\Local\vcpkg\archives in 1.675 ms. Use --debug to see more details.
Installing 1/28 harfbuzz:x64-windows...
Building harfbuzz[core]:x64-windows...
-- Using cached harfbuzz-harfbuzz-5.0.1.tar.gz.
-- Cleaning sources at E:/Dev/tools/vcpkg/vcpkg/buildtrees/harfbuzz/src/5.0.1-abd09462bc.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/Dev/tools/vcpkg/vcpkg/downloads/harfbuzz-harfbuzz-5.0.1.tar.gz
-- Applying patch fix-win32-build.patch
-- Using source at E:/Dev/tools/vcpkg/vcpkg/buildtrees/harfbuzz/src/5.0.1-abd09462bc.clean
CMake Warning at scripts/cmake/vcpkg_configure_meson.cmake:305 (message):
  Options ADDITIONAL_(NATIVE|CROSS)_BINARIES have been deprecated.  Only use
  ADDITIONAL_BINARIES!
Call Stack (most recent call first):
  ports/harfbuzz/portfile.cmake:40 (vcpkg_configure_meson)
  scripts/ports.cmake:147 (include)


-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Using cached python-3.10.5-embed-amd64.zip.
-- Configuring x64-windows-dbg
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at E:/Dev/tools/vcpkg/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: E:/Dev/tools/vcpkg/vcpkg/downloads/tools/python/python-3.10.5-x64/python.exe E:/Dev/tools/vcpkg/vcpkg/installed/x64-windows/tools/meson/meson.py -Dicu=disabled -Dgraphite=disabled -Dcoretext=disabled -Dglib=disabled -Dgobject=disabled -Dfreetype=enabled -Dcairo=disabled -Dintrospection=disabled -Ddocs=disabled -Dtests=disabled -Dbenchmark=disabled --buildtype plain --backend ninja --wrap-mode nodownload --libdir lib --native E:/Dev/tools/vcpkg/vcpkg/buildtug --includedir ../include -Dcmake_prefix_path=['E:/Dev/tools/vcpkg/vcpkg/installed/x64-windows/debug','E:/Dev/tools/vcpkg/vcpkg/installed/x64-windows','E:/Dev/tools/vcpkg/vcpkg/installed/x64-windows/share'] E:/Dev/tools/vcpkg/vcpkg/buildtrees/harfbuzz/src/5.0.1-abd09462bc.clean
    Working Directory: E:/Dev/tools/vcpkg/vcpkg/buildtrees/harfbuzz/x64-windows-dbg
    Error code: 1
    See logs for more information:
      E:\Dev\tools\vcpkg\vcpkg\buildtrees\harfbuzz\config-x64-windows-dbg-meson-log.txt.log
      E:\Dev\tools\vcpkg\vcpkg\buildtrees\harfbuzz\config-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:432 (vcpkg_execute_required_process)
  ports/harfbuzz/portfile.cmake:40 (vcpkg_configure_meson)
  scripts/ports.cmake:147 (include)


error: building harfbuzz:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+harfbuzz
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[harfbuzz]+Build+error
Include '[harfbuzz] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: unknown

**Comment by JackBoosY** [comment]
@likui Can you please provide _E:\Dev\tools\vcpkg\vcpkg\buildtrees\harfbuzz\config-x64-windows-dbg-out.log_?

**Comment by likui** [comment]
> 

[config-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/10132420/config-x64-windows-dbg-out.log)

**Comment by dg0yt** [comment]
> CMake Error: Problem with archive_write_finish_entry(): Can't restore time
> CMake Error: Problem extracting tar: E:\Dev\tools\vcpkg\vcpkg-git\vcpkg\downloads\PowerShell-7.2.7-win-x86.zip
'CMake' failed while extracting E:\Dev\tools\vcpkg\vcpkg-git\vcpkg\downloads\PowerShell-7.2.7-win-x86.zip.

> ERROR: Clock skew detected. File E:\Dev\tools\vcpkg\vcpkg\buildtrees\harfbuzz\x64-windows-dbg\meson-private/coredata.dat has a time stamp 0.8182s in the future.

also #28108:

> CMake Error: Problem with archive_write_header(): Can't create '\\?\E:\Dev\tools\vcpkg\vcpkg\downloads\tools\msys2\583ad6e4115a307a.tmp\usr\bin\uncompress'

Maybe your drive E: is not healthy, or it is using a stone-age file system.

**Comment by likui** [comment]
> Maybe your drive E: is not healthy, or it is using a stone-age file system.
That is indeed the reason. I changed the vcpkg to drive C: , it is OK.
Thank you.
