### ISSUE TITLE
no installed libraries in visual studio after vcpkg integrate install

### ISSUE THREAD

**Issue by Eric7997** [microsoft/vcpkg#28035]
After installing vcpkg and gumbo library successfully (including integrate install,) gumbo library is not available in Visual Studio 2022.
I have followed the resolution steps in issue #10534 and tried moving/installing the file into different directories with no success.
![Screenshot (25)](https://user-images.githubusercontent.com/119247883/204154640-04217804-1925-4120-969f-ffe80eafd458.png)

- OS: Windows 11
- Compiler: Visual Studio 2022

**Comment by FrankXie05** [comment]
Sorry I can't reproduce your problem. 
You can try the following steps: :)
1.  git clone https://github.com/microsoft/vcpkg (in the root directory)
2.  cd vcpkg/
3.  ./vcpkg install gumbo:x64-windows(Corresponding system architecture)
4.  ./vcpkg integrate install

![image](https://user-images.githubusercontent.com/65999885/204211825-41faeb54-fcf1-4efa-8ab5-a234f3eafa3c.png)

**Comment by JackBoosY** [comment]
Please check your project properties for vcpkg tag.

**Comment by MonicaLiu0311** [comment]
Win10
VS 2022
```
PS E:\vcpkg02> ./vcpkg version
vcpkg package management program version 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75

See LICENSE.txt for license information.
```

I still can't reproduce your issue with the latest vcpkg.

We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
