### ISSUE TITLE
[harfbuzz] Build error

### ISSUE THREAD

**Issue by likui** [microsoft/vcpkg#28040]
**Host Environment**

- OS: Windows 10
- Compiler: vs 2022

**To Reproduce**

`./vcpkg install paraview`

**Failure logs**
-- Using source at E:/Dev/tools/vcpkg/vcpkg/buildtrees/harfbuzz/src/5.0.1-abd09462bc.clean
CMake Warning at scripts/cmake/vcpkg_configure_meson.cmake:305 (message):
  Options ADDITIONAL_(NATIVE|CROSS)_BINARIES have been deprecated.  Only use
  ADDITIONAL_BINARIES!
Call Stack (most recent call first):
  ports/harfbuzz/portfile.cmake:40 (vcpkg_configure_meson)
  scripts/ports.cmake:147 (include)

-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Configuring x64-windows-dbg
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at E:/Dev/tools/vcpkg/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: E:/Dev/tools/vcpkg/vcpkg/downloads/tools/python/python-3.10.5-x64/python.exe E:/Dev/tools/vcpkg/vcpkg/installed/x64-windows/tools/meson/meson.py -Dicu=disabled -Dgraphite=disabled -Dcoretext=disabled -Dglib=disabled -Dgobject=disabled -Dfreetype=enabled -Dcairo=disabled -Dintrospection=disabled -Ddocs=disabled -Dtests=disabled -Dbenchmark=disabled --buildtype plain --backend ninja --wrap-mode nodownload --libdir lib --native E:/Dev/tools/vcpkg/vcpkg/buildtrees/harfbuzz/meson-x64-windows-dbg.log -Ddebug=true --prefix E:/Dev/tools/vcpkg/vcpkg/packages/harfbuzz_x64-windows/debug --includedir ../include -Dcmake_prefix_path=['E:/Dev/tools/vcpkg/vcpkg/installed/x64-windows/debug','E:/Dev/tools/vcpkg/vcpkg/installed/x64-windows','E:/Dev/tools/vcpkg/vcpkg/installed/x64-windows/share'] E:/Dev/tools/vcpkg/vcpkg/buildtrees/harfbuzz/src/5.0.1-abd09462bc.clean
    Working Directory: E:/Dev/tools/vcpkg/vcpkg/buildtrees/harfbuzz/x64-windows-dbg
    Error code: Exit code 0xc0000135

    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:432 (vcpkg_execute_required_process)
  ports/harfbuzz/portfile.cmake:40 (vcpkg_configure_meson)
  scripts/ports.cmake:147 (include)

error: building harfbuzz:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+harfbuzz
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[harfbuzz]+Build+error
Include '[harfbuzz] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: unknown

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please provide the error log.

**Comment by likui** [comment]
[meson-x64-windows-dbg.log](https://github.com/microsoft/vcpkg/files/10109795/meson-x64-windows-dbg.log)

**Comment by JackBoosY** [comment]
Please remove folder _E:/Dev/tools/vcpkg/vcpkg/downloads/tools/python/python-3.10.5-x64_ then try again.

**Comment by likui** [comment]
> Please remove folder _E:/Dev/tools/vcpkg/vcpkg/downloads/tools/python/python-3.10.5-x64_ then try again.

Building harfbuzz[core]:x64-windows...
-- Using cached harfbuzz-harfbuzz-5.0.1.tar.gz.
-- Cleaning sources at E:/Dev/tools/vcpkg/vcpkg/buildtrees/harfbuzz/src/5.0.1-abd09462bc.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/Dev/tools/vcpkg/vcpkg/downloads/harfbuzz-harfbuzz-5.0.1.tar.gz
-- Applying patch fix-win32-build.patch
-- Using source at E:/Dev/tools/vcpkg/vcpkg/buildtrees/harfbuzz/src/5.0.1-abd09462bc.clean
CMake Warning at scripts/cmake/vcpkg_configure_meson.cmake:305 (message):
  Options ADDITIONAL_(NATIVE|CROSS)_BINARIES have been deprecated.  Only use
  ADDITIONAL_BINARIES!
Call Stack (most recent call first):
  ports/harfbuzz/portfile.cmake:40 (vcpkg_configure_meson)
  scripts/ports.cmake:147 (include)


-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Using cached python-3.10.5-embed-amd64.zip.
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: E:/Dev/tools/vcpkg/vcpkg/downloads/python-3.10.5-embed-amd64.zip
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" -E -f rm python310._pth
    Working Directory: E:/Dev/tools/vcpkg/vcpkg/downloads/tools/python/python-3.10.5-x64
    Error code: 1
    See logs for more information:
      E:\Dev\tools\vcpkg\vcpkg\buildtrees\harfbuzz\PYTHON3-tool-post-install-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:685 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_find_acquire_program.cmake:81 (vcpkg_find_acquire_program)
  scripts/cmake/vcpkg_find_acquire_program.cmake:596 (z_vcpkg_find_acquire_program_find_internal)
  scripts/cmake/vcpkg_configure_meson.cmake:322 (vcpkg_find_acquire_program)
  ports/harfbuzz/portfile.cmake:40 (vcpkg_configure_meson)
  scripts/ports.cmake:147 (include)


error: building harfbuzz:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+harfbuzz
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[harfbuzz]+Build+error
Include '[harfbuzz] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: unknown

**Comment by likui** [comment]
[Uploading PYTHON3-tool-post-install-err.log…]()

**Comment by JackBoosY** [comment]
> Uploading PYTHON3-tool-post-install-err.log…

This file wasn't uploaded successfully, can you please also remove port `python3` then try again?

**Comment by likui** [comment]
Installing 1/43 harfbuzz:x64-windows...
Building harfbuzz[core]:x64-windows...
-- Using cached harfbuzz-harfbuzz-5.0.1.tar.gz.
-- Cleaning sources at E:/Dev/tools/vcpkg/vcpkg/buildtrees/harfbuzz/src/5.0.1-abd09462bc.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/Dev/tools/vcpkg/vcpkg/downloads/harfbuzz-harfbuzz-5.0.1.tar.gz
-- Applying patch fix-win32-build.patch
-- Using source at E:/Dev/tools/vcpkg/vcpkg/buildtrees/harfbuzz/src/5.0.1-abd09462bc.clean
CMake Warning at scripts/cmake/vcpkg_configure_meson.cmake:305 (message):
  Options ADDITIONAL_(NATIVE|CROSS)_BINARIES have been deprecated.  Only use
  ADDITIONAL_BINARIES!
Call Stack (most recent call first):
  ports/harfbuzz/portfile.cmake:40 (vcpkg_configure_meson)
  scripts/ports.cmake:147 (include)


-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Using cached python-3.10.5-embed-amd64.zip.
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: E:/Dev/tools/vcpkg/vcpkg/downloads/python-3.10.5-embed-amd64.zip
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" -E -f rm python310._pth
    Working Directory: E:/Dev/tools/vcpkg/vcpkg/downloads/tools/python/python-3.10.5-x64
    Error code: 1
    See logs for more information:
      E:\Dev\tools\vcpkg\vcpkg\buildtrees\harfbuzz\PYTHON3-tool-post-install-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:685 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_find_acquire_program.cmake:81 (vcpkg_find_acquire_program)
  scripts/cmake/vcpkg_find_acquire_program.cmake:596 (z_vcpkg_find_acquire_program_find_internal)
  scripts/cmake/vcpkg_configure_meson.cmake:322 (vcpkg_find_acquire_program)
  ports/harfbuzz/portfile.cmake:40 (vcpkg_configure_meson)
  scripts/ports.cmake:147 (include)


error: building harfbuzz:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+harfbuzz
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[harfbuzz]+Build+error
Include '[harfbuzz] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: unknown

**Comment by likui** [comment]
[PYTHON3-tool-post-install-err.log](https://github.com/microsoft/vcpkg/files/10110297/PYTHON3-tool-post-install-err.log)

**Comment by JackBoosY** [comment]
@LilyWangLL Please try to repro this issue using cmake 3.25.0.

**Comment by likui** [comment]
I changed the vcpkg to drive C: , it is OK.
Thank you.
