### ISSUE TITLE
[cudnn] Build error

### ISSUE THREAD

**Issue by XiaoXian99** [microsoft/vcpkg#28059]
**Host Environment**

- OS: Windows

**Failure logs**

error: building cudnn:x64-windows-release failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: 4e368f639 2022-11-28 (10 hours ago)

-- Running vcpkg install - failed
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:869 (message):
  vcpkg install failed.  See logs for more information:
  C:\Users\HP\darknet\build_release\vcpkg-manifest-install.log
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.25/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:109 (project)

CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
Config failed! Exited with error code 1.

**Additional context**

Tried git pull, already up to date.
Already included vcpkg, cmake\bin, and ninja in path.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. `cudnn` is only searching for a package that must be installed manually by the user, did you install `cudnn` manually on your machine?

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
