### ISSUE TITLE
[leptonica] build failure

### ISSUE THREAD

**Issue by an1018** [microsoft/vcpkg#28064]
**Host Environment**

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"

**To Reproduce**

`./vcpkg integrate install`
`./vcpkg install leptonica`

**Failure logs**

![image](https://user-images.githubusercontent.com/19808900/204557989-c61bf34f-921b-4d4c-a509-18e05b073eb6.png)

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by rinechran** [comment]
i don't know what the problem is.

**Comment by an1018** [comment]
I want to install  leptonica with the following code, 
```
    git clone https://github.com/Microsoft/vcpkg.git
    cd vcpkg
    ./bootstrap-vcpkg.sh # "./bootstrap-vcpkg.bat" for powershell
    ./vcpkg integrate install
    ./vcpkg install leptonica
```

but when I run `./vcpkg integrate install`,  the console output：
![image](https://user-images.githubusercontent.com/19808900/204560337-701806ed-e95a-42ad-a13e-f9f9b32726a2.png)

Could you give me some suggestions? Thanks very much

**Comment by Neumann-A** [comment]
According to yourself you are on Ubuntu.
Why are you running: 
`./vcpkg integrate install` ?

**Comment by an1018** [comment]
Yes, Ubuntu16.04. 
I refer to [this installation tutorial](https://github.com/DanBloomberg/leptonica#installing-leptonica-vcpkg)

**Comment by Neumann-A** [comment]
> And when I running ./vcpkg install leptonica, the console output：

Without logs hard to tell why it is failing. It could very well be that gcc in Ubuntu16.04 is too old or some system library is missing.

**Comment by FrankXie05** [comment]
@an1018 Could you please provide your error log?

**Comment by an1018** [comment]
@FrankXie05 Hi, this is my error log, [letonica_error.log](https://github.com/microsoft/vcpkg/files/10120270/letonica_error.log), thanks

**Comment by rinechran** [comment]
connect https from curl to recive data however , it appears that you to recieve the giflib-5.2.1.tar.gz file due to a curl certificate error. I think it would be better to update the curl.

**Comment by FrankXie05** [comment]
@an1018 Have you tried this? Update your local curl tool. :)

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
