### ISSUE TITLE
openssl build failure

### ISSUE THREAD

**Issue by markdhenning** [microsoft/vcpkg#28071]
See logs for more information:
      /opt/vcpkg/buildtrees/openssl/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/openssl/unix/portfile.cmake:21 (vcpkg_cmake_install)
  ports/openssl/portfile.cmake:33 (include)
  scripts/ports.cmake:147 (include)

```
<details><summary>/opt/vcpkg/buildtrees/openssl/install-x64-linux-dbg-out.log</summary>

```
[1/3] cd /opt/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.7-96d825e305.clean && export PATH=/usr/bin:/opt/Fortify/Fortify_SCA_and_Apps_22.1.1/bin:/opt
/Fortify/Fortify_SCA_and_Apps_22.1.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/Fortify/Fortify_SCA_and_Apps_22.1.1/bin:/opt/vcpkg:/root/b
in:/usr/bin:/opt/vcpkg/downloads/tools/ninja/1.10.2-linux && export CC=/usr/bin/cc && export AR=/usr/bin/ar && export LD=/usr/bin/ld && export RANLIB=/usr
/bin/ranlib && export MAKE=/usr/bin/make && export MAKEDEPPROG=/usr/bin/cc && export WINDRES= && /usr/bin/perl Configure no-shared no-module enable-static
-engine no-zlib no-ssl2 no-idea no-cast no-seed no-md2 no-tests linux-x86_64 --prefix=/opt/vcpkg/packages/openssl_x64-linux/debug --libdir=/opt/vcpkg/pack
ages/openssl_x64-linux/debug/lib --openssldir=/etc/ssl "-fPIC -g" && /opt/vcpkg/downloads/tools/cmake-3.25.0-linux/cmake-3.25.0-linux-x86_64/bin/cmake -DD
IR=/opt/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.7-96d825e305.clean -P /opt/vcpkg/ports/openssl/unix/remove-deps.cmake
FAILED: nssl-3.0.7-96d825e305.clean/Makefile /opt/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.7-96d825e305.clean/Makefile 
cd /opt/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.7-96d825e305.clean && export PATH=/usr/bin:/opt/Fortify/Fortify_SCA_and_Apps_22.1.1/bin:/opt/Forti
fy/Fortify_SCA_and_Apps_22.1.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/Fortify/Fortify_SCA_and_Apps_22.1.1/bin:/opt/vcpkg:/root/bin:/us
r/bin:/opt/vcpkg/downloads/tools/ninja/1.10.2-linux && export CC=/usr/bin/cc && export AR=/usr/bin/ar && export LD=/usr/bin/ld && export RANLIB=/usr/bin/r
anlib && export MAKE=/usr/bin/make && export MAKEDEPPROG=/usr/bin/cc && export WINDRES= && /usr/bin/perl Configure no-shared no-module enable-static-engin
e no-zlib no-ssl2 no-idea no-cast no-seed no-md2 no-tests linux-x86_64 --prefix=/opt/vcpkg/packages/openssl_x64-linux/debug --libdir=/opt/vcpkg/packages/o
penssl_x64-linux/debug/lib --openssldir=/etc/ssl "-fPIC -g" && /opt/vcpkg/downloads/tools/cmake-3.25.0-linux/cmake-3.25.0-linux-x86_64/bin/cmake -DDIR=/op
t/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.7-96d825e305.clean -P /opt/vcpkg/ports/openssl/unix/remove-deps.cmake
Can't locate IPC/Cmd.pm in @INC (you may need to install the IPC::Cmd module) (@INC contains: /opt/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.7-96d82
5e305.clean/util/perl /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/
perl5 /opt/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.7-96d825e305.clean/external/perl/Text-Template-1.56/lib) at /opt/vcpkg/buildtrees/openssl/x64-l
inux-dbg/nssl-3.0.7-96d825e305.clean/util/perl/OpenSSL/config.pm line 19.
BEGIN failed--compilation aborted at /opt/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.7-96d825e305.clean/util/perl/OpenSSL/config.pm line 19.
Compilation failed in require at Configure line 23.
BEGIN failed--compilation aborted at Configure line 23.
ninja: build stopped: subcommand failed.
```
</details>

**Additional context**

[mhenning@rocky85 ~]$ clear;cat /opt/vcpkg/installed/vcpkg/issue_body.md

Package: openssl[core]:x64-linux -> 3.0.7#1

**Host Environment**

- Host: x64-linux
- Compiler: GNU 8.5.0
-    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: be736ae19 2022-11-29 (18 minutes ago)

**To Reproduce**

`vcpkg install openssl`

**Failure logs**

```
CMake Warning at ports/openssl/portfile.cmake:8 (message):
  openssl currently requires the following library from the system package
  manager:

      linux-headers

  It can be installed on alpine systems via apk add linux-headers.
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)

-- Using cached openssl-openssl-openssl-3.0.7.tar.gz.
-- Cleaning sources at /opt/vcpkg/buildtrees/openssl/src/nssl-3.0.7-96d825e305.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /opt/vcpkg/downloads/openssl-openssl-openssl-3.0.7.tar.gz
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Using source at /opt/vcpkg/buildtrees/openssl/src/nssl-3.0.7-96d825e305.clean
-- Configuring x64-linux
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: /opt/vcpkg/downloads/tools/cmake-3.25.0-linux/cmake-3.25.0-linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j9
    Working Directory: /opt/vcpkg/buildtrees/openssl/x64-linux-dbg
    See logs for more information:
      /opt/vcpkg/buildtrees/openssl/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/openssl/unix/portfile.cmake:21 (vcpkg_cmake_install)
  ports/openssl/portfile.cmake:33 (include)
  scripts/ports.cmake:147 (include)

```
<details><summary>/opt/vcpkg/buildtrees/openssl/install-x64-linux-dbg-out.log</summary>

```
[1/3] cd /opt/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.7-96d825e305.clean && export PATH=/usr/bin:/opt/Fortify/Fortify_SCA_and_Apps_22.1.1/bin:/opt/Fortify/Fortify_SCA_and_Apps_22.1.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/Fortify/Fortify_SCA_and_Apps_22.1.1/bin:/opt/vcpkg:/root/bin:/usr/bin:/opt/vcpkg/downloads/tools/ninja/1.10.2-linux && export CC=/usr/bin/cc && export AR=/usr/bin/ar && export LD=/usr/bin/ld && export RANLIB=/usr/bin/ranlib && export MAKE=/usr/bin/make && export MAKEDEPPROG=/usr/bin/cc && export WINDRES= && /usr/bin/perl Configure no-shared no-module enable-static-engine no-zlib no-ssl2 no-idea no-cast no-seed no-md2 no-tests linux-x86_64 --prefix=/opt/vcpkg/packages/openssl_x64-linux/debug --libdir=/opt/vcpkg/packages/openssl_x64-linux/debug/lib --openssldir=/etc/ssl "-fPIC -g" && /opt/vcpkg/downloads/tools/cmake-3.25.0-linux/cmake-3.25.0-linux-x86_64/bin/cmake -DDIR=/opt/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.7-96d825e305.clean -P /opt/vcpkg/ports/openssl/unix/remove-deps.cmake
FAILED: nssl-3.0.7-96d825e305.clean/Makefile /opt/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.7-96d825e305.clean/Makefile 
cd /opt/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.7-96d825e305.clean && export PATH=/usr/bin:/opt/Fortify/Fortify_SCA_and_Apps_22.1.1/bin:/opt/Fortify/Fortify_SCA_and_Apps_22.1.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/Fortify/Fortify_SCA_and_Apps_22.1.1/bin:/opt/vcpkg:/root/bin:/usr/bin:/opt/vcpkg/downloads/tools/ninja/1.10.2-linux && export CC=/usr/bin/cc && export AR=/usr/bin/ar && export LD=/usr/bin/ld && export RANLIB=/usr/bin/ranlib && export MAKE=/usr/bin/make && export MAKEDEPPROG=/usr/bin/cc && export WINDRES= && /usr/bin/perl Configure no-shared no-module enable-static-engine no-zlib no-ssl2 no-idea no-cast no-seed no-md2 no-tests linux-x86_64 --prefix=/opt/vcpkg/packages/openssl_x64-linux/debug --libdir=/opt/vcpkg/packages/openssl_x64-linux/debug/lib --openssldir=/etc/ssl "-fPIC -g" && /opt/vcpkg/downloads/tools/cmake-3.25.0-linux/cmake-3.25.0-linux-x86_64/bin/cmake -DDIR=/opt/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.7-96d825e305.clean -P /opt/vcpkg/ports/openssl/unix/remove-deps.cmake
Can't locate IPC/Cmd.pm in @INC (you may need to install the IPC::Cmd module) (@INC contains: /opt/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.7-96d825e305.clean/util/perl /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 /opt/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.7-96d825e305.clean/external/perl/Text-Template-1.56/lib) at /opt/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.7-96d825e305.clean/util/perl/OpenSSL/config.pm line 19.
BEGIN failed--compilation aborted at /opt/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.7-96d825e305.clean/util/perl/OpenSSL/config.pm line 19.
Compilation failed in require at Configure line 23.
BEGIN failed--compilation aborted at Configure line 23.
ninja: build stopped: subcommand failed.
```
</details>

**Additional context**

**Comment by markdhenning** [comment]
sudo dnf install gcc make perl kernel-devel kernel-headers bzip2 dkms

appears to work around this error.

**Comment by Cheney-W** [comment]
Glad to know you solved the problem locally.
