### ISSUE TITLE
vcpkg_install_msbuild PLATFORM incorrect default parameter

### ISSUE THREAD

**Issue by Elite-stay** [microsoft/vcpkg#28076]
Default parameter of vcpkg_install_msbuild PLATFORM is not ${TRIPLET_SYSTEM_ARCH}.

https://github.com/microsoft/vcpkg/blob/266e4910c6c6a2fe1b20a1bdb5cec4e16f190f01/scripts/cmake/vcpkg_install_msbuild.cmake#L23

**Comment by Cheney-W** [comment]
Could you please describe your problem in detail, such as which port you encountered unexpected results when installing, and what are your expected results?
If it is not the problem encountered during installation, what do you think is the problem with the script content and what are the expected results?

**Comment by Elite-stay** [comment]
[mytestlib_2.zip](https://github.com/microsoft/vcpkg/files/10133079/mytestlib_2.zip)

**Comment by BillyONeal** [comment]
> Default parameter of vcpkg_install_msbuild PLATFORM is not ${TRIPLET_SYSTEM_ARCH}.

That's because the default for what Visual Studio stamps into `vcxproj`es on creation is `Win32`. See the survey of existing ports I did in my reply to Cheney-W's PR here: https://github.com/microsoft/vcpkg/pull/28119#issuecomment-1336270264

**Comment by Elite-stay** [comment]
> > Default parameter of vcpkg_install_msbuild PLATFORM is not ${TRIPLET_SYSTEM_ARCH}.
> 
> That's because the default for what Visual Studio stamps into `vcxproj`es on creation is `Win32`. See the survey of existing ports I did in my reply to Cheney-W's PR here: [#28119 (comment)](https://github.com/microsoft/vcpkg/pull/28119#issuecomment-1336270264)

See the [document](https://vcpkg.io/en/docs/maintainers/vcpkg_install_msbuild.html).

**Comment by BillyONeal** [comment]
> See the [document](https://vcpkg.io/en/docs/maintainers/vcpkg_install_msbuild.html).

PR out to fix the doc to match reality https://github.com/microsoft/vcpkg/pull/28189

**Comment by MonicaLiu0311** [comment]
Fixed by https://github.com/microsoft/vcpkg-docs/pull/21.
