### ISSUE TITLE
Have log4cxx have different character size depending on platform.

### ISSUE THREAD

**Issue by dulsi** [microsoft/vcpkg#28082]
On windows log4cxx defaults to wchar for strings. On linux log4cxx defaults to utf8 for strings. We are currently using utf8 on all platforms.

Is there some way to tell vcpkg to build it with utf8? When building log4cxx you can specify an option to override the default character size.

You can see how it is set in:
https://github.com/apache/logging-log4cxx/blob/master/src/main/include/CMakeLists.txt

**Comment by FrankXie05** [comment]
Have you tried the method provided by @Cheney-W?
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
