### ISSUE TITLE
[portaudio] Only finds devices in classic, not manifest, mode

### ISSUE THREAD

**Issue by bramtayl** [microsoft/vcpkg#28088]
PortAudio can't find any audio devices when I load it in manifest mode, but it works fine in classic mode. I'm on ubuntu. I'm assuming it has to do with PortAudio not being able to find an ALSA config file or something? Maybe ALSA_CONFIG_DIR or ALSA_PLUGIN_DIR?

**Comment by FrankXie05** [comment]
@bramtayl In terms of build content and process, there is no difference between classic mode and manifest mode. Can you provide error log and reproduction steps? (Additional note: You can refer to the official instructions for use http://portaudio.com/docs/v19-doxydocs/compile_linux.html) :)

**Comment by bramtayl** [comment]
Sure.

CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.24)
project(Test VERSION 0.1.0 LANGUAGES CXX)
find_package(portaudio REQUIRED)
add_executable(Test main.cpp)
target_link_libraries(Test PUBLIC portaudio_static)
```

main.cpp:
```
#include <portaudio.h>
#include <iostream>

auto main(int number_of_arguments, char* arguments[]) -> int {
    Pa_Initialize();
    std::cout << Pa_GetDeviceCount() << std::endl;
    return 0;
}
```

vcpkg.json:
```
#include <portaudio.h>
#include <iostream>

auto main(int number_of_arguments, char* arguments[]) -> int {
    Pa_Initialize();
    std::cout << Pa_GetDeviceCount() << std::endl;
    return 0;
}
```

If I have a folder will all three files, I get an output of zero. But if I delete the vcpkg.json file, I get an output of 9

**Comment by FrankXie05** [comment]
@bramtayl 
1. Please use the correct usage in `CmakeLists.txt`.
```
find_package(portaudio CONFIG REQUIRED)
target_link_libraries(main PRIVATE portaudio)
```
2. Add `CMAKE_TOOLCHAIN_FILE`(Run the command `./vcpkg integrate install` under the `vcpkg` folder) when building the cmake project. ` cmake .. -DCMAKE_TOOLCHAIN_FILE=xxx/vcpkg/scripts/buildsystems/vcpkg.cmake`
3.  vcpkg.json :
```
{
  "name": "test",
  "version-string": "0.0.1",
  "dependencies": [
    "portaudio"
  ]
}
```

**Comment by bramtayl** [comment]
1)

I had to keep portaudio_static instead of portaudio, because otherwise it errors. But I made the other changes, and the issue is still there.

Since I'm new to cmake, could you explain this a bit more? From the cmake docs, it looks like we can make portaudio `PRIVATE` because I didn't use it in a header file. But I'm having trouble understanding why you would add the `CONFIG` part to the the `find_package` call. I get that we're looking for the `PortAudioConfig.cmake` file, so is it just to make the search faster?


2) I have the cmake toolchain file set through vs code:

```
"cmake.configureSettings": {
  "CMAKE_TOOLCHAIN_FILE": "/home/brandon/vcpkg/scripts/buildsystems/vcpkg.cmake"
}
```


3)

Oh shoot sorry I copied the wrong vcpkg.json file. My vcpkg json file looks like pretty much the same:

```
{
  "name": "justly",
  "version-string": "0.1.0",
  "dependencies": [
    "portaudio"
  ]
}
```

**Comment by FrankXie05** [comment]
Please provide the error log. :)

**Comment by FrankXie05** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!

**Comment by bramtayl** [comment]
@FrankXie05 which logs are you referring to? Happy to provide whatever information you need.
