### ISSUE TITLE
[skia] Skia breaks dependent builds by exporting WIN32_MEAN_AND_LEAN 

### ISSUE THREAD

**Issue by ulfllorenz** [microsoft/vcpkg#28080]
**Describe the bug**
The generated configuration file for importing Skia into a project creates the new target skia::skia and attaches the INTERFACE_COMPILE_DEFINITION WIN32_MEAN_AND_LEAN to it. This macro then breaks code that expects to include the non-lean windows headers from <windows.h>. It also defined NOMINMAX, but propagating this macro may be acceptable.

**Environment**
- OS: Windows
- Compiler: any

**To Reproduce**

Install the skia port under Windows and look under share/skia/skiaConfig.cmake. Or directly in skiaConfig.cmake.in in the port directory.

**Expected behavior**
WIN32_MEAN_AND_LEAN only excludes certain rarely-used headers from windows.h to speed up compilation. It is therefore a macro that should never be set in an interface property.

I can see how this specific issue came to be: Skia is built with whatever google uses, and the CMake configure script is added by the vcpkg port, which essentially pastes all the definitions. The simplest fix is then t just remove this definition from the skia source. This would only slow down the build, but should not have any further ramifications. Grepping through the source, the definition seems to enter in gn/skia/BUILD.gn, It is also defined in src/core/SkLeanWindows.h, but this header file seems not to be installed.

**Comment by dg0yt** [comment]
Please test #28007.

**Comment by ulfllorenz** [comment]
#28007 does not exhibit the problem.
