### ISSUE TITLE
[qtdeclarative] build failure

### ISSUE THREAD

**Issue by unbored** [microsoft/vcpkg#28083]
**Host Environment**

- OS: Windows11
- Compiler: MSVC 14.29.30133
- vcpkg-tool version: 2022-10-12-b586c2752f75bcc3f6a243749e9a0d94d0d93ccd
- vcpkg-scripts version: 266e4910c 2022-11-29 (14 hours ago)

**To Reproduce**

`./vcpkg install qtdeclarative`

**Failure logs**
```
-- Using cached qtdeclarative-everywhere-src-6.4.1.tar.xz.
-- Extracting source C:/Users/unbored/Softwares/vcpkg/downloads/qtdeclarative-everywhere-src-6.4.1.tar.xz
-- Using source at C:/Users/unbored/Softwares/vcpkg/buildtrees/qtdeclarative/src/here-src-6-d3218afd1e.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: C:/Users/unbored/Softwares/vcpkg/downloads/tools/cmake-3.25.0-windows/cmake-3.25.0-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: C:/Users/unbored/Softwares/vcpkg/buildtrees/qtdeclarative/x64-windows-dbg
    See logs for more information:
      C:\Users\unbored\Softwares\vcpkg\buildtrees\qtdeclarative\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  installed/x64-windows/share/qtbase/qt_install_submodule.cmake:337 (vcpkg_cmake_install)
  ports/qtdeclarative/portfile.cmake:22 (qt_install_submodule)
  scripts/ports.cmake:147 (include)
```
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/10124586/install-x64-windows-dbg-out.log)

**Additional context**
Tried to remove the qtdeclarative buildtree directory to make a clean build.
The error log says some files are not found, but I'm pretty sure the files are just right there.
Most times one missing file `qquickfolderbreadcrumbbar_p.h` is reported. But this time the log shows two.

**Comment by Neumann-A** [comment]
Use `--x-buildtrees-root=<shortpath>`. `C:\Users\unbored\Softwares\vcpkg\buildtrees\` is too long

**Comment by unbored** [comment]
> Use `--x-buildtrees-root=<shortpath>`. `C:\Users\unbored\Softwares\vcpkg\buildtrees\` is too long

It works. Thank you.
