### ISSUE TITLE
`#include <GL/gl.h>` is ambiguous on case-insensitve file systems

### ISSUE THREAD

**Issue by dg0yt** [microsoft/vcpkg#28087]
**Describe the bug**

osg:x64-windows-static-md currently fails in CI during the build step because `GLint64` and `GLuint64` appear as undefined:
~~~
D:\buildtrees\osg\src\raph-3.6.5-41fa3cfd98.clean\include\osg/GLExtensions(323): error C2061: syntax error: identifier 'GLint64'
D:\buildtrees\osg\src\raph-3.6.5-41fa3cfd98.clean\include\osg/GLExtensions(325): error C2061: syntax error: identifier 'GLuint64'
~~~
But during the configure step, the types are found:
~~~
-- Found OpenGL: opengl32   
-- Found EGL: D:/installed/x64-windows-static-md/debug/lib/libEGL.lib  
-- Performing Test GL_HEADER_HAS_GLINT64
-- Performing Test GL_HEADER_HAS_GLINT64 - Success
-- Performing Test GL_HEADER_HAS_GLUINT64
-- Performing Test GL_HEADER_HAS_GLUINT64 - Success
~~~
with the following header:
~~~
//#include<> line for OpenGL Header
OPENGL_HEADER1:STRING=#include <GL/gl.h>

//#include<> line for additional OpenGL Headers if required
OPENGL_HEADER2:STRING=
~~~

Further investigation showed that both ports opengl and mesa provide this header, only differing in case, from the top-level dir:
~~~
mesa:x64-windows-static-md:/include/GL/gl.h
opengl:x64-windows-static-md:/include/gl/GL.h
~~~
I have no idea if they are identical or differ.

FTR additional matches do exist in subdirs, possibly becoming available via the include path:
~~~
pangolin:x64-windows-static-md:/include/pangolin/gl/gl.h
glbinding:x64-windows-static-md:/include/glbinding/gl/gl.h
gstreamer:x64-windows-static-md:/include/gstreamer-1.0/gst/gl/gl.h
magnum:x64-windows-static-md:/include/Magnum/GL/GL.h
~~~~

**Environment**
vcpkg CI, x64-mingw-static-md

**Failure logs**
https://dev.azure.com/vcpkg/public/_build/results?buildId=81637&view=artifacts&pathAsName=false&type=publishedArtifacts

CC @Neumann-A

**Comment by Neumann-A** [comment]
> opengl:x64-windows-static-md:/include/gl/GL.h

are the windows headers. Probably wrong to copy them out of the SDK (same for the libs which would also avoid colliding with mesa as a software renderer). WinSDK version should probably be a hardcoded part of the abi hash. also those gl.h headers should more ore less define the same symbols if they know about all newer opengl versions. The windows header seems a bit out of date here. 

What I see however is that GLint64 GLuint64 are in the `glext.h` header which is included by mesa `gl.h`. So simply consistently including `glext.h` should solve the problem.

**Comment by dg0yt** [comment]
In any case, the conflict between mesa and opengl-registry must be resolved.

**Comment by dg0yt** [comment]
> GLint64 GLuint64 are in the `glext.h` header which is included by mesa `gl.h`

... if `GL_GLEXT_LEGACY` is not defined.

**Comment by Neumann-A** [comment]
> ... if GL_GLEXT_LEGACY is not defined.

Did somebody define it ?

**Comment by dg0yt** [comment]
The osg error may come from opencascade. It install anothers `glext.h` without the ...int64 types which isn't in a `gl` dir but uses the same header guard `__gl_glext_h_` :angry:

**Comment by dg0yt** [comment]
... and the current version of opencascade in vcpkg also defines GL_GLEXT_LEGACY, in
https://git.dev.opencascade.org/gitweb/?p=occt.git;a=blob;f=src/OpenGl/OpenGl_GlFunctions.hxx;h=fd361983d415db0273d02655601c9af0506bea15;hb=bb368e271e24f63078129283148ce83db6b9670a#l38

**Comment by Neumann-A** [comment]
looks like they do some shenanigans with the gl headers in general to detect what gl functions to use although that should be done via runtime checks.

**Comment by dg0yt** [comment]
At least, osg in vcpkg doesn't offer an opencascade feature so I will just disable it there, after another CI run for tracing. (Hey, VCPKG_TRACE_FIND_PACKAGE was just merged :tada:)
opencascade 7.7.0 has changes to opengl stuff, but the github mirrro is lagging behind, and updating the opencascade port is more work.

**Comment by dg0yt** [comment]
Hm, overwriting files is not an error in CI?

~~~
warning: File D:\installed\x64-windows-static-md\debug/lib/opengl32.lib was already present and will be overwritten
warning: File D:\installed\x64-windows-static-md\include/GL/gl.h was already present and will be overwritten
warning: File D:\installed\x64-windows-static-md\lib/opengl32.lib was already present and will be overwritten
Elapsed time to handle mesa:x64-windows-static-md: 2.452 min
~~~

This include the ambiguous `GL/gl.h`.
