### ISSUE TITLE
[protobuf] Build error- Cannot dot-source this command because it was defined in a different language mode. To invoke this command without importing its contents, omit the '.' operator.

### ISSUE THREAD

**Issue by fengmiaomiao** [microsoft/vcpkg#28098]
**Host Environment**

- OS: Windows
- Compiler: MSVC 19.34.31933.0

**To Reproduce**
'In Powershell 7.3.0 execute listed below command:'
`$Env:__PSLockdownPolicy = 0`
`Set-ExecutionPolicy Unrestricted`
`vcpkg install protobuf[zlib] protobuf[zlib]:x64-windows
`

**Failure logs**

Computing installation plan...
The following packages will be built and installed:
    protobuf[core,zlib]:x64-windows -> 3.21.8
    protobuf[core,zlib]:x86-windows -> 3.21.8
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
Restored 0 package(s) from C:\Users\miaomiaofeng\AppData\Local\vcpkg\archives in 450.4 us. Use --debug to see more details.
Installing 1/2 protobuf:x64-windows...
Building protobuf[core,zlib]:x64-windows...
-- Using cached protocolbuffers-protobuf-v3.21.8.tar.gz.
-- Cleaning sources at D:/Program Files (x86)/vcpkg/buildtrees/protobuf/src/v3.21.8-b162a26f57.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Program Files (x86)/vcpkg/downloads/protocolbuffers-protobuf-v3.21.8.tar.gz
-- Applying patch fix-static-build.patch
-- Applying patch fix-default-proto-file-path.patch
-- Applying patch compile_options.patch
-- Using source at D:/Program Files (x86)/vcpkg/buildtrees/protobuf/src/v3.21.8-b162a26f57.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: "D:/Program Files (x86)/vcpkg/downloads/tools/powershell-core-7.2.7-windows/pwsh.exe" -noprofile -executionpolicy Bypass -nologo -file "D:/Program Files (x86)/vcpkg/scripts/buildsystems/msbuild/applocal.ps1" -targetBinary "D:/Program Files (x86)/vcpkg/packages/protobuf_x64-windows/tools/protobuf/protoc.exe" -installedDir "D:/Program Files (x86)/vcpkg/packages/protobuf_x64-windows/bin" -verbose
    Working Directory: D:/Program Files (x86)/vcpkg
    Error code: 1
    See logs for more information:
      D:\Program Files (x86)\vcpkg\buildtrees\protobuf\copy-tool-dependencies-0-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:9 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:41 (z_vcpkg_copy_tool_dependencies_search)
  scripts/cmake/vcpkg_copy_tools.cmake:48 (vcpkg_copy_tool_dependencies)
  ports/protobuf/portfile.cmake:81 (vcpkg_copy_tools)
  scripts/ports.cmake:147 (include)

error: building protobuf:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+protobuf
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[protobuf]+Build+error
Include '[protobuf] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: 251741475 2022-11-30 (11 hours ago)

**Additional context**
[copy-tool-dependencies-0-err.log](https://github.com/microsoft/vcpkg/files/10129579/copy-tool-dependencies-0-err.log)

**Comment by Cheney-W** [comment]
What's the result when you run below command on PowerShell?
`$ExecutionContext.SessionState.LanguageMode`

**Comment by fengmiaomiao** [comment]
ConstrainedLanguage
It seems the windows operation problem. Do you have any good solutions that can work? I have tried some, but now work.

**Comment by JonLiu1993** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
