### ISSUE TITLE
[New Port Request] otfcc

### ISSUE THREAD

**Issue by wyzdwdz** [microsoft/vcpkg#28094]
Library name:  otfcc

Library description:  A C library and utility used for parsing and writing OpenType font files

Source repository URL:  https://github.com/caryll/otfcc

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

There are 5 projects in total: deps, libotfcc, otfccdump, otfccbuild, otfccdll
deps: a static library including all dependencies for building
libotfcc: a static library for core function
otfccdump: an executable file coverting otf font to json
otfccbuild: an executable file to build otf font from json
otfccdll: a shared library version of otfccbuild

**Comment by wyzdwdz** [comment]
New Port Request: otfcc

**Comment by autoantwort** [comment]
The repo is archived and not maintained anymore

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
