### ISSUE TITLE
[speex] Build error on Windows

### ISSUE THREAD

**Issue by netheril96** [microsoft/vcpkg#28096]
**Host Environment**

- OS: Windows 10 x64
- Compiler: VS 2022

**To Reproduce**

`./vcpkg install speex`

**Failure logs**

    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: 251741475 2022-11-30 (6 hours ago)

   [speex-all-logs.zip](https://github.com/microsoft/vcpkg/files/10128515/speex-all-logs.zip)

Probable direct error:

> ../libtool: line 1774:  2342 Segmentation fault      compile cl.exe -DHAVE_CONFIG_H -I. -I.././../src/8fd6c18e01-bdacefbfef.clean/libspeex -I.. -I.././../src/8fd6c18e01-bdacefbfef.clean/include -I../include/speex -I.. -DWIN32 -D_WINDOWS -D_DEBUG -nologo -W3 -utf-8 -MP -MDd -Z7 -Ob0 -RTC1 -Od -Wall -c .././../src/8fd6c18e01-bdacefbfef.clean/libspeex/stereo.c -DDLL_EXPORT -DPIC -o .libs/stereo.obj

**Additional context**

**Comment by JackBoosY** [comment]
```
“C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64\cl.exe”中的内部编译器错误
  请选择 Visual C++ 
“帮助”菜单上的“技术支持”命令，或打开技术支持帮助文件来获得详细信息
```
Compiler bug.

**Comment by netheril96** [comment]
Ha, indeed it is solved after I upgrade Visual Studio. It has a minor version bump.
