### ISSUE TITLE
Disable automatic integration for a particuar VS project

### ISSUE THREAD

**Issue by MikeGitb** [Microsoft/vcpkg#281]
When I call `vcpkg integrate install` Is there a way to disable integration for a specific project? I e.g. use the vcpkg version of microsoft's gsl in some of my projects, but every now and then I also contribute something to the library repository and when I build my patches for testing, VS picks up the vcpkg version of the headers instead of the local ones.

**Comment by ras0219-msft** [comment]
Yes, we do have that!

We respect a suite of MSBuild variables (https://github.com/Microsoft/vcpkg/blob/master/scripts/buildsystems/msbuild/vcpkg.targets):
- VcpkgEnabled can be set to false to completely disable vcpkg (`/p:VcpkgEnabled=false`)
- VcpkgTriplet can be used to override the triplet (`/p:VcpkgTriplet=x86-windows-static`)
- VcpkgRoot can be used to redirect or disable the user-wide integration (`/p:VcpkgRoot=C:\my\alt\vcpkg`)

These can be specified on the MSBuild command line by the switches above, or you can add them to the project itself inside the `<PropertyGroup Label="Globals">` at the top of your `.vcxproj`.
