### ISSUE TITLE
[harfbuzz] Build error

### ISSUE THREAD

**Issue by sorrowfeng** [microsoft/vcpkg#28103]
**Host Environment**

- Windows 10 x64
- Compiler: VS2015

**To Reproduce**

`./vcpkg install libqglviewer`

**Failure logs**

PS C:\src\vcpkg> vcpkg install libqglviewer
Computing installation plan...
The following packages will be built and installed:
  * harfbuzz[core]:x64-windows -> 5.0.1#3
  * harfbuzz[core]:x86-windows -> 5.0.1#3
  * icu[core]:x64-windows -> 71.1
  * icu[core]:x86-windows -> 71.1
  * libjpeg-turbo[core]:x64-windows -> 2.1.4
  * libjpeg-turbo[core]:x86-windows -> 2.1.4
    libqglviewer[core]:x86-windows -> 2.7.2#4
  * openssl[core]:x86-windows -> 3.0.7#1
  * openssl[core]:x64-windows -> 3.0.7#1
  * pcre2[core]:x86-windows -> 10.40#1
  * pcre2[core]:x64-windows -> 10.40#1
  * pkgconf[core]:x64-windows -> 1.8.0#3
  * qt5-base[core]:x64-windows -> 5.15.7#2
  * qt5-base[core]:x86-windows -> 5.15.7#2
  * sqlite3[core]:x64-windows -> 3.40.0#1
  * sqlite3[core]:x86-windows -> 3.40.0#1
  * vcpkg-cmake-get-vars[core]:x64-windows -> 2022-09-04
  * vcpkg-pkgconfig-get-modules[core]:x64-windows -> 2022-02-10#1
  * zstd[core]:x64-windows -> 1.5.2#1
  * zstd[core]:x86-windows -> 1.5.2#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
-- Automatically setting HTTP(S)_PROXY environment variables to "127.0.0.1:7890".
Detecting compiler hash for triplet x86-windows...
Restored 0 package(s) from C:\Users\plf\AppData\Local\vcpkg\archives in 715.4 us. Use --debug to see more details.
Installing 1/20 harfbuzz:x64-windows...
Building harfbuzz[core]:x64-windows...
-- Using cached harfbuzz-harfbuzz-5.0.1.tar.gz.
-- Cleaning sources at C:/src/vcpkg/buildtrees/harfbuzz/src/5.0.1-abd09462bc.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/src/vcpkg/downloads/harfbuzz-harfbuzz-5.0.1.tar.gz
-- Applying patch fix-win32-build.patch
-- Using source at C:/src/vcpkg/buildtrees/harfbuzz/src/5.0.1-abd09462bc.clean
CMake Warning at scripts/cmake/vcpkg_configure_meson.cmake:305 (message):
  Options ADDITIONAL_(NATIVE|CROSS)_BINARIES have been deprecated.  Only use
  ADDITIONAL_BINARIES!
Call Stack (most recent call first):
  ports/harfbuzz/portfile.cmake:40 (vcpkg_configure_meson)
  scripts/ports.cmake:147 (include)

-- Getting CMake variables for x64-windows
-- Configuring x64-windows-dbg
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at C:/src/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Configuring x64-windows-dbg done
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Package x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: C:/src/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe install -v
    Working Directory: C:/src/vcpkg/buildtrees/harfbuzz/x64-windows-dbg
    Error code: 1
    See logs for more information:
      C:\src\vcpkg\buildtrees\harfbuzz\package-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
  ports/harfbuzz/portfile.cmake:55 (vcpkg_install_meson)
  scripts/ports.cmake:147 (include)

error: building harfbuzz:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+harfbuzz
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[harfbuzz]+Build+error
Include '[harfbuzz] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: 251741475 2022-11-30 (13 hours ago)

Please use the prefilled template from C:\src\vcpkg\installed\vcpkg\issue_body.md when reporting your issue.

**Comment by sorrowfeng** [comment]
[https://github.com/microsoft/vcpkg/issues/28039#issuecomment-1331958303](url)

I implemented all this fine and vcpkg is the latest version

**Comment by autoantwort** [comment]
> Please use the prefilled template from C:\src\vcpkg\installed\vcpkg\issue_body.md when reporting your issue.

Please do this.

**Comment by Adela0814** [comment]
Is your error consistent with this issue? https://github.com/microsoft/vcpkg/issues/28115

**Comment by Adela0814** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
