### ISSUE TITLE
[libiconv] Build error

### ISSUE THREAD

**Issue by likui** [microsoft/vcpkg#28108]
**Host Environment**

- OS: Windows 10

**To Reproduce**
.\vcpkg.exe install libiconv

`./vcpkg install xxxx`

**Failure logs**
PS E:\Dev\tools\vcpkg\vcpkg> .\vcpkg.exe install libiconv
Computing installation plan...
The following packages will be built and installed:
    libiconv[core]:x64-windows -> 1.17
Detecting compiler hash for triplet x64-windows...
-- Automatically setting HTTP(S)_PROXY environment variables to "127.0.0.1:30822".
Restored 0 package(s) from C:\Users\likui\AppData\Local\vcpkg\archives in 282.9 us. Use --debug to see more details.
Installing 1/1 libiconv:x64-windows...
Building libiconv[core]:x64-windows...
-- Using cached libiconv-1.17.tar.gz.
-- Cleaning sources at E:/Dev/tools/vcpkg/vcpkg/buildtrees/libiconv/src/1.17-e2a53830aa.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/Dev/tools/vcpkg/vcpkg/downloads/libiconv-1.17.tar.gz
-- Applying patch 0002-Config-for-MSVC.patch
-- Applying patch 0003-Add-export.patch
-- Applying patch 0004-ModuleFileName.patch
-- Using source at E:/Dev/tools/vcpkg/vcpkg/buildtrees/libiconv/src/1.17-e2a53830aa.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Using cached msys-gzip-1.11-1-x86_64.pkg.tar.zst.
-- Using cached msys-bash-5.1.008-1-x86_64.pkg.tar.zst.
-- Using cached msys-autoconf-2.71-3-any.pkg.tar.zst.
-- Using cached msys-diffutils-3.8-2-x86_64.pkg.tar.zst.
-- Using cached msys-binutils-2.37-5-x86_64.pkg.tar.zst.
-- Using cached msys-libtool-2.4.6-9-x86_64.pkg.tar.xz.
-- Using cached msys-file-5.41-2-x86_64.pkg.tar.zst.
-- Using cached msys-zlib-1.2.11-1-x86_64.pkg.tar.xz.
-- Using cached msys-libbz2-1.0.8-3-x86_64.pkg.tar.zst.
-- Using cached msys-coreutils-8.32-2-x86_64.pkg.tar.zst.
-- Using cached msys-grep-3.0-2-x86_64.pkg.tar.xz.
-- Using cached msys-sed-4.8-2-x86_64.pkg.tar.zst.
-- Using cached msys-libpcre-8.45-1-x86_64.pkg.tar.zst.
-- Using cached msys-m4-1.4.19-2-x86_64.pkg.tar.zst.
-- Using cached msys-automake-wrapper-11-4-any.pkg.tar.zst.
-- Using cached msys-gawk-5.1.0-2-x86_64.pkg.tar.zst.
-- Using cached msys-mpfr-4.1.0-1-x86_64.pkg.tar.zst.
-- Using cached msys-gmp-6.2.1-1-x86_64.pkg.tar.zst.
-- Using cached msys-libreadline-8.1.001-1-x86_64.pkg.tar.zst.
-- Using cached msys-ncurses-6.2-2-x86_64.pkg.tar.zst.
-- Using cached msys-automake1.16-1.16.3-3-any.pkg.tar.zst.
-- Using cached msys-perl-5.32.1-2-x86_64.pkg.tar.zst.
-- Using cached msys-libcrypt-2.1-3-x86_64.pkg.tar.zst.
-- Using cached msys-pkg-config-0.29.2-4-x86_64.pkg.tar.zst.
-- Using cached msys-make-4.3-3-x86_64.pkg.tar.zst.
-- Using cached msys-findutils-4.8.0-1-x86_64.pkg.tar.zst.
-- Using cached msys-libintl-0.21-1-x86_64.pkg.tar.zst.
-- Using cached msys-libiconv-1.16-2-x86_64.pkg.tar.zst.
-- Using cached msys-gcc-libs-11.2.0-3-x86_64.pkg.tar.zst.
-- Using cached msys-msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst.
-- Using cached msys-which-2.21-4-x86_64.pkg.tar.zst.
    Command failed: E:/Dev/tools/vcpkg/vcpkg/downloads/tools/cmake-3.24.0-windows/cmake-3.24.0-windows-i386/bin/cmake.exe -E tar xzf E:/Dev/tools/vcpkg/vcpkg/downloads/msys-gzip-1.11-1-x86_64.pkg.tar.zst
    Working Directory: E:/Dev/tools/vcpkg/vcpkg/downloads/tools/msys2/583ad6e4115a307a.tmp
    Error code: 1
    See logs for more information:
      [msys-x64-windows-0-err.log](https://github.com/microsoft/vcpkg/files/10132390/msys-x64-windows-0-err.log)

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:509 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_configure_make.cmake:212 (vcpkg_acquire_msys)
  ports/libiconv/portfile.cmake:29 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)

error: building libiconv:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libiconv
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libiconv]+Build+error
Include '[libiconv] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: unknown

**Comment by autoantwort** [comment]
The folder `/dev/` could be the problem

**Comment by likui** [comment]
> The folder `/dev/` could be the problem

 I changed the vcpkg to drive C: , it is OK.
Thank you.
