### ISSUE TITLE
[vtk] Build error. CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message)

### ISSUE THREAD

**Issue by likui** [microsoft/vcpkg#28114]
**Host Environment**

- OS: Windows 10
- Compiler: Visual Studio

**To Reproduce**
`./vcpkg install vtk`

**Failure logs**

PS C:\vcpkg> .\vcpkg.exe install vtk
Computing installation plan...
The following packages will be built and installed:
    vtk[core]:x64-windows -> 9.0.3-pv5.9.1#12
Detecting compiler hash for triplet x64-windows...
-- Automatically setting HTTP(S)_PROXY environment variables to "127.0.0.1:30822".
Restored 0 package(s) from C:\Users\likui\AppData\Local\vcpkg\archives in 436.3 us. Use --debug to see more details.
Installing 1/1 vtk:x64-windows...
Building vtk[core]:x64-windows...
-- Using cached Kitware-VTK-2959413ff190bc6e3ff40f5b6c1342edd2e5233f.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/vtk/src/edd2e5233f-7ddc60dbb8.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/Kitware-VTK-2959413ff190bc6e3ff40f5b6c1342edd2e5233f.tar.gz
-- Applying patch FindLZMA.patch
-- Applying patch FindLZ4.patch
-- Applying patch Findproj.patch
-- Applying patch pegtl.patch
-- Applying patch pythonwrapper.patch
-- Applying patch NoUndefDebug.patch
-- Applying patch python_debug.patch
-- Applying patch fix-using-hdf5.patch
-- Applying patch FindExpat.patch
-- Applying patch vtkm.patch
-- Applying patch 1f00a0c9.patch
-- Applying patch 156fb524.patch
-- Applying patch d107698a.patch
-- Applying patch fix-gdal.patch
-- Applying patch missing-limits.patch
-- Applying patch UseProj5Api.patch
-- Applying patch fix-find-libharu.patch
-- Applying patch fix-libharu2.4-compat.patch
-- Using source at C:/vcpkg/buildtrees/vtk/src/edd2e5233f-7ddc60dbb8.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
CMake Warning at installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:311 (message):
  The following variables are not used in CMakeLists.txt:

      VTK_MODULE_ENABLE_VTK_PythonContext2D

  Please recheck them and remove the unnecessary options from the
  `vcpkg_cmake_configure` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):
  ports/vtk/portfile.cmake:153 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)

-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.25.0-windows/cmake-3.25.0-windows-i386/bin/cmake.exe --build . --config Release --target install -- -v -j17
    Working Directory: C:/vcpkg/buildtrees/vtk/x64-windows-rel
    See logs for more information:
      C:\vcpkg\buildtrees\vtk\install-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/vtk/portfile.cmake:176 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building vtk:x64-windows failed with: BUILD_FAILED

[install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/10137289/install-x64-windows-rel-out.log)

**Comment by Neumann-A** [comment]
> mt.exe : general error c101008d: Failed to write the updated manifest to the resource of file "bin\vtkCommonDataModel-9.0.dll". 另一个程序正在使用此文件，进程无法访问。

**Comment by FrankXie05** [comment]
@likui Make sure you turn off firewall and other protective software.
