### ISSUE TITLE
vs的集成出现了问题

### ISSUE THREAD

**Issue by chriscp-cat** [microsoft/vcpkg#28128]
![image](https://user-images.githubusercontent.com/68489543/205329299-aa540d3b-fe17-4fbe-8326-d3ee51684f0e.png)
像这样 我已经在配置里吧use vcpkg关闭了 vcpkg还是在include路径中可以搜索 编译也是正常的  如图  
![image](https://user-images.githubusercontent.com/68489543/205329524-8cf6c8f7-7ad1-4cd5-9cd3-c67e8fb4bed0.png)
我不知道这是vs的问题还是vcpkg的问题   vs版本是2022 17.4.2

**Comment by sfhacker** [comment]
Embarrassing!

**Comment by chriscp-cat** [comment]
> Embarrassing!

I think it may not be the problem of vcpkg
The problem may be in vs

**Comment by chriscp-cat** [comment]
![image](https://user-images.githubusercontent.com/68489543/205888996-a7554eed-ed47-4a76-a426-2f9d055be0aa.png)
![image](https://user-images.githubusercontent.com/68489543/205889029-fa12504c-d09d-4630-9dc6-1aa415d6b91b.png)
I set the project’s use vcpkg to false
However, the installed directory of vcpkg is still in the includes
