### ISSUE TITLE
[New Port Request] webview

### ISSUE THREAD

**Issue by jonverrier** [microsoft/vcpkg#28125]
Library name: webview

Library description: A tiny cross-platform webview library for C/C++/Go to build modern cross-platform GUIs.

Source repository URL: https://github.com/webview/webview

Project homepage (if different from the source repository): https://webview.dev/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): C++ only for vcpkg

**Comment by Adela0814** [comment]
We already have a port named `zserge-webview`. https://github.com/microsoft/vcpkg/blob/1ddafcb6f62ee3488b6e32621d6aa343038a8ccc/ports/zserge-webview/vcpkg.json
