### ISSUE TITLE
[vcpkg-gfortran] Build error on Windows 11, ARM64 & emulation 

### ISSUE THREAD

**Issue by kiroecke** [microsoft/vcpkg#28132]
Package: vcpkg-gfortran[core]:x86-windows -> 3#2

**Host Environment**

- Host: arm64-windows
- Compiler: MSVC 19.34.31935.0
-    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
-    vcpkg-scripts version: e46521db0 2022-12-01 (20 hours ago)

**To Reproduce**

`vcpkg install lapack`

**Failure logs**

Installing 1/3 vcpkg-gfortran:x86-windows...
Building vcpkg-gfortran[core]:x86-windows...
[DEBUG] Detecting host with IsWow64Process2
[DEBUG] CreateProcessW("C:\dev\vcpkg\downloads\tools\cmake-3.25.0-windows\cmake-3.25.0-windows-i386\bin\cmake.exe" -DALL_FEATURES= -DCURRENT_PORT_DIR=C:/dev/vcpkg/ports/vcpkg-gfortran -D_HOST_TRIPLET=arm64-windows -DFEATURES=core -DPORT=vcpkg-gfortran -DVERSION=3 -DVCPKG_USE_HEAD_VERSION=0 -D_VCPKG_DOWNLOAD_TOOL=BUILT_IN -D_VCPKG_EDITABLE=0 -D_VCPKG_NO_DOWNLOADS=0 -DZ_VCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/dev/vcpkg/scripts/toolchains/windows.cmake -DCMD=BUILD -DDOWNLOADS=C:/dev/vcpkg/downloads -DTARGET_TRIPLET=x86-windows -DTARGET_TRIPLET_FILE=C:/dev/vcpkg/triplets/x86-windows.cmake -DVCPKG_BASE_VERSION=2022-11-10 -DVCPKG_CONCURRENCY=5 -DVCPKG_PLATFORM_TOOLSET=v143 "-DGIT=C:/Program Files (x86)/Git/cmd/git.exe" -DVCPKG_ROOT_DIR=C:/dev/vcpkg -DPACKAGES_DIR=C:/dev/vcpkg/packages -DBUILDTREES_DIR=C:/dev/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=C:/dev/vcpkg/installed -DDOWNLOADS=C:/dev/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\dev\vcpkg\scripts\ports.cmake")
-- The Fortran compiler identification is unknown
-- No Fortran compiler found on the PATH. Using MinGW gfortran!
-- Using cached msys-mingw-w64-i686-gcc-fortran-11.2.0-8-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-gcc-libgfortran-11.2.0-8-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-gcc-libs-11.2.0-8-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-gmp-6.2.1-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-winpthreads-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-mpc-1.2.1-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-mpfr-4.1.0.p13-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-gcc-11.2.0-8-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-binutils-2.37-4-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-crt-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-headers-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libiconv-1.16-2-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-windows-default-manifest-6.4-3-any.pkg.tar.xz.
-- Using cached msys-mingw-w64-i686-zlib-1.2.11-9-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-zstd-1.5.2-1-any.pkg.tar.zst.
-- Using cached msys-gzip-1.11-1-x86_64.pkg.tar.zst.
-- Using cached msys-bash-5.1.008-1-x86_64.pkg.tar.zst.
-- Using cached msys-diffutils-3.8-2-x86_64.pkg.tar.zst.
-- Using cached msys-coreutils-8.32-2-x86_64.pkg.tar.zst.
-- Using cached msys-grep-3.0-2-x86_64.pkg.tar.xz.
-- Using cached msys-sed-4.8-2-x86_64.pkg.tar.zst.
-- Using cached msys-libpcre-8.45-1-x86_64.pkg.tar.zst.
-- Using cached msys-gawk-5.1.0-2-x86_64.pkg.tar.zst.
-- Using cached msys-mpfr-4.1.0-1-x86_64.pkg.tar.zst.
-- Using cached msys-gmp-6.2.1-1-x86_64.pkg.tar.zst.
-- Using cached msys-libreadline-8.1.001-1-x86_64.pkg.tar.zst.
-- Using cached msys-ncurses-6.2-2-x86_64.pkg.tar.zst.
-- Using cached msys-pkg-config-0.29.2-4-x86_64.pkg.tar.zst.
-- Using cached msys-make-4.3-3-x86_64.pkg.tar.zst.
-- Using cached msys-libintl-0.21-1-x86_64.pkg.tar.zst.
-- Using cached msys-libiconv-1.16-2-x86_64.pkg.tar.zst.
-- Using cached msys-gcc-libs-11.2.0-3-x86_64.pkg.tar.zst.
-- Using cached msys-msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst.
-- Using msys root at C:/dev/vcpkg/downloads/tools/msys2/2b29df0583c528a8
CMake Error at ports/vcpkg-gfortran/portfile.cmake:19 (message):
  Unsupported host architecture ARM64!
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)

[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 1010: cmd_execute_and_stream_data() returned 1 after  1490611 us
error: building vcpkg-gfortran:x86-windows failed with: BUILD_FAILED
[DEBUG] CreateProcessW("C:\Program Files (x86)\Git\cmd\git.exe" "--git-dir=C:\dev\vcpkg\.git" "--work-tree=C:\dev\vcpkg\.git" -c core.autocrlf=false show "--pretty=format:%h %cd (%cr)" -s --date=short HEAD)
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 1011: cmd_execute_and_stream_data() returned 0 after    60814 us
[DEBUG] Detecting host with IsWow64Process2
[DEBUG] CreateProcessW("C:\Program Files (x86)\Git\cmd\git.exe" "--git-dir=C:\dev\vcpkg\.git" "--work-tree=C:\dev\vcpkg\.git" -c core.autocrlf=false show "--pretty=format:%h %cd (%cr)" -s --date=short HEAD)
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 1012: cmd_execute_and_stream_data() returned 0 after    60331 us
    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: e46521db0 2022-12-01 (20 hours ago)

```

**Additional context**
vcpkg says that there would be no Fortran compiler "found on the PATH". But this wasn't true: "gfortran.exe" is 
available and running well from my Powershell at any location. Anyway, I tried to install lapack or dlib that prerequisites 
the gfortran compiler here. Any other installation (e.g., curl:x86-windows or sqlite3:x86-windows) worked without any 
problems using the emulation. 


How can I imply that vcpkg uses the x86-emulator for gfortran (and, yes, it works fine standalone) instead pushing it to 
the arm64 native architecture?

Thanks!
K.

**Comment by Neumann-A** [comment]
vcpkg isolates windows builds so it wont see whatever gfortran you have on path

**Comment by kiroecke** [comment]
I found a quick-and-dirty workaround by editing \vcpkg\ports\vcpkg-gfortran\portfile.cmake line 12ff:

```
    if(HOST_ARCH MATCHES "(amd|AMD)64")
        set(MINGW_W w64)
        set(MSYS_HOST x86_64)
    elseif(HOST_ARCH MATCHES "(x|X)86")
        set(MINGW_W w32)
        set(MSYS_HOST i686)
    elseif(HOST_ARCH MATCHES "ARM64")
        set(MINGW_W w32)
        set(MSYS_HOST i686)
    else()
        message(FATAL_ERROR "Unsupported host architecture1 ${HOST_ARCH}!" )
    endif()
```

This manipulation directs the MinGW gfortran compiler to the x86-emulation (because a native seems not to exist). It works ... but slow.
