### ISSUE TITLE
[quazip-qt5] CMake cannot find the package

### ISSUE THREAD

**Issue by mtnpke** [microsoft/vcpkg#28131]
****

**Is your feature request related to a problem? Please describe.**
When trying to use the quazip-qt5 port from a CMake project, the package is not found.
Example:

```
find_package(QuaZip-Qt5 CONFIG REQUIRED)
```

-> 

```
1> [CMake] CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:829 (_find_package):
1> [CMake]   Could not find a package configuration file provided by "QuaZip-Qt5" with
1> [CMake]   any of the following names:
1> [CMake] 
1> [CMake]     QuaZip-Qt5Config.cmake
1> [CMake]     quazip-qt5-config.cmake
1> [CMake] 
1> [CMake]   Add the installation prefix of "QuaZip-Qt5" to CMAKE_PREFIX_PATH or set
1> [CMake]   "QuaZip-Qt5_DIR" to a directory containing one of the above files.  If
1> [CMake]   "QuaZip-Qt5" provides a separate development package or SDK, be sure it has
1> [CMake]   been installed.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   src/CMakeLists.txt:7 (find_package)
```

**Proposed solution**
The find_package line should work without issue and find quazip.

**Describe alternatives you've considered**

**Additional context**
It works when setting CMAKE_PREFIX_PATH as the message suggests:
`set(CMAKE_PREFIX_PATH "${CMAKE_PREFIX_PATH};${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/share/quazip")`

**Comment by Neumann-A** [comment]
https://github.com/microsoft/vcpkg/blob/163fe7bd3d67c41200617caaa245b5ba2ba854e6/ports/quazip/portfile.cmake#L13

needs to be changed to read 

`vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/QuaZip-Qt5-1.3 PACKAGE_NAME QuaZip-Qt5)`

**Comment by mtnpke** [comment]
Works like a charm. Thanks!
