### ISSUE TITLE
[boost-config] Build error

### ISSUE THREAD

**Issue by RainbowTaro2022** [microsoft/vcpkg#28141]
**Host Environment**

- OS:windows 11 22h2
- Compiler: cmake 3.25.0

**To Reproduce**

Steps to reproduce the behavior:null
As soon as I run cmake, I report an error

**Failure logs**

G:\Cone\cemu-latest\build>cmake ..
-- Running vcpkg install
Detecting compiler hash for triplet x64-windows-static...
Detecting compiler hash for triplet x64-windows...
The following packages will be rebuilt:
  * boost-uninstall[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-uninstall\e2d05f10364104d9b7de2383bcb105a1fd3fe975
  * boost-vcpkg-helpers[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-vcpkg-helpers\0e96a2cb3400bcafd55070d18bdcab64808ada01
The following packages will be built and installed:
    boost-algorithm[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-algorithm\20d7a665b493f8b9816d56125e83928e41dcaa98
  * boost-align[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-align\5bc0b7d28ff47bf04454dde5d3ab3eeed5a113b2
  * boost-any[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-any\6382a90fffe32ec65147d579e28f05604eaeef46
  * boost-array[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-array\11a6869eb0c7b2efa3e92b2c36795ef9873c6537
    boost-asio[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-asio\39b1b86ce2c331ab31d001308b6a71fc6fbebf5c
  * boost-assert[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-assert\2e4adae40df44f3927978bba397b60f18ad8e919
  * boost-atomic[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-atomic\ba96ddc357592c3644f666fbc68d052ad3f0f397
  * boost-bind[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-bind\c27b66c8e195ce97685c409c0821f907bae83d80
  * boost-build[core]:x64-windows -> 1.79.0#1 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-build\a5ddae928a30fbcc9d5cb01906a7ee846b1b6c62
  * boost-chrono[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-chrono\dd168284e43a057a5775444c07f11f99a96053c0
  * boost-circular-buffer[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-circular-buffer\c8a97f3e2854ffb2064635bada5cfac2230a7590
  * boost-concept-check[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-concept-check\493a1b5ae991a9c7b2643e649329de16bcd0fa48
  * boost-config[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-config\22c6532dcc9c24fd85febb93dc936e68c031043a
    boost-container[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-container\c29fd09bc12ad31bd796ba90682fcbd242090cc0
  * boost-container-hash[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-container-hash\09168c62619e569c7b6b2799aa39c361a1afff22
  * boost-context[core]:x64-windows-static -> 1.79.0#1 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-context\24210ac19518ca74072938e9569a9e9f5b3476ba
  * boost-conversion[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-conversion\1e3552c53e2ef9bcfa7159f2f06079c30dfa53ac
  * boost-core[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-core\a22eddd8a3121063f8ef94eb4e0ae64021d0369a
  * boost-coroutine[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-coroutine\b953ff17be4b4da2bb6b898c80b12c4185b3a821
  * boost-date-time[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-date-time\bc3460f55739fad6ef0e548bc084bade32985683
  * boost-detail[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-detail\65c1cfff48ea4ead86b7db6d20401fbfef4e1022
    boost-dll[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-dll\0243143e2c2bea8e3579aadfc735b56c40ad5491
  * boost-dynamic-bitset[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-dynamic-bitset\e2ea8d91791c627d016c69aa73d36d3622ba0df0
  * boost-endian[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-endian\24a5162a544f251df6387a1d5bb70ba53497e4c3
  * boost-exception[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-exception\6d7250e9806392fc38643fb7c069ba18fcec2350
  * boost-filesystem[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-filesystem\3ad60cdb4b5114cda754f4b15d96d72c9615b271
  * boost-foreach[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-foreach\e8948df8fb3d54f6bcca0c5fee45f13406683a3e
  * boost-format[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-format\365fbda5a5fe624367c049e4c118945c0142d0eb
  * boost-function[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-function\7057b960d6b790eb30f51ef17d67aa958230e100
  * boost-function-types[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-function-types\53ad331d5cdedab7b40eebaf15d9f8081a5d9eed
    boost-functional[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-functional\d8fd2c72eb4f3c8d501a44f7a5f8ecfe608cc3b4
  * boost-fusion[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-fusion\10c27fdbefb33b57367582e1a8f262db9d94d807
  * boost-integer[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-integer\7970a7ba822ac5e6a8a9f98ba5ee3631b3ccff3c
  * boost-intrusive[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-intrusive\5162285659ad371e022c242481e20414c8b23e2b
  * boost-io[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-io\a248d3f95d95973f63b5be92c81747165ca0319c
  * boost-iterator[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-iterator\a9b329add024642bef5338c963bdfeee41bb60df
  * boost-lexical-cast[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-lexical-cast\78f269516df3662fbb3417faba5a8983936de604
  * boost-modular-build-helper[core]:x64-windows -> 1.79.0#8 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-modular-build-helper\e22ad8dde44513f2fa1a9b38c71818aaaee52120
  * boost-move[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-move\957381b3c5ac7d2b563b2563ca8a78d49f034e68
  * boost-mp11[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-mp11\b741f7087023927b8345779b9a30575e1dee383f
  * boost-mpl[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-mpl\1fa673fcec0135c3a144d90528f719b281d29043
  * boost-multi-index[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-multi-index\bccc5117c54e12afbd300458b25ec698ae860db4
    boost-nowide[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-nowide\8013e5dd702b7f4c9973872435060812981af2f8
  * boost-numeric-conversion[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-numeric-conversion\33a349e75f738b735e678de319469c0f9009a413
    boost-optional[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-optional\9480f61fee5df6864a425964bd13ee783a7572a9
  * boost-parameter[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-parameter\94340499eaf0d204a8000b09a4b7f58eeb12c84d
  * boost-phoenix[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-phoenix\571d5f1a068664b1f31dddd3541b6a19bfdbec2d
  * boost-pool[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-pool\a75a80498bfc1134bb8d5808b5f8b457e4032908
  * boost-predef[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-predef\c17a7256c1f86eab749e10b451dbf53d317afaf9
  * boost-preprocessor[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-preprocessor\1790581b89b5cf96bd870854b2bc4b256032a9c9
    boost-program-options[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-program-options\ad5cb3defd7e6f0f2be69f7090d2f996e4d4d885
    boost-property-tree[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-property-tree\f05a46d069778748274ff28002994e04d3654286
  * boost-proto[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-proto\26184f2fdf2a6c15a79964befeba82802d7d6afd
    boost-ptr-container[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-ptr-container\879641e4ff9cfca37db16a03f72b04afeed909c6
    boost-random[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-random\6c02cc8343df9ea692504b16db286eba1fc320a6
    boost-range[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-range\fff762e26af0f46863606c7fd088491dfcc84599
  * boost-ratio[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-ratio\3c85cac76a643d538a52553a54353fbb818b3169
  * boost-rational[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-rational\bd0b9e457fc969fdac6b9ee36b77a26b3c680ad5
  * boost-regex[core]:x64-windows-static -> 1.79.0#1 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-regex\49b26b133e2b9eb16d917930b2c697b58eff5530
  * boost-serialization[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-serialization\aef44ba080120ebe8f5af25a6d019781323a5206
    boost-signals2[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-signals2\f6ab0c163ef679f14f84b6510c8508a90facf986
  * boost-smart-ptr[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-smart-ptr\b94b3b41ab4bb281041f40d876baf221c05818ce
  * boost-spirit[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-spirit\6a4bdffc6ef22bfee8942319cb5a69b2e85fe231
  * boost-static-assert[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-static-assert\673cf82169b2b1696d993477d47b2f94d4350a7f
    boost-static-string[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-static-string\575a5fac2b96da2ff39038a733fea5455f91caf4
  * boost-system[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-system\e5bca2d39362ef3978473a1d184f017ed277d1e5
  * boost-thread[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-thread\d40c962d08c08d397520ace757ef7aab055a59be
  * boost-throw-exception[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-throw-exception\1607edf60f1243503820e06b4d3e16c385aa691d
    boost-tokenizer[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-tokenizer\7e5682fee6727bada3b88221bd416edaa80f6a34
  * boost-tuple[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-tuple\c3b718eea1f62e7b4918b3c4f6a4be731d4085ce
  * boost-type-index[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-type-index\b4e2eff6204ba68938a99059b23d3abbd2e1dc55
  * boost-type-traits[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-type-traits\7969a397a6c03205ec1c118834272183ff4201c7
  * boost-typeof[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-typeof\81216888498f3c8f6563b991a1d601af139da128
  * boost-uninstall[core]:x64-windows -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-uninstall\e2d05f10364104d9b7de2383bcb105a1fd3fe975
  * boost-unordered[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-unordered\b73d98ab77d4de1a3e4f12bdd84869dfc3adedc0
  * boost-utility[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-utility\8eb91c7a3ad14393219ba020d3d26c39a325c626
  * boost-variant[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-variant\33b3da200705df22017f639acdc1e2eade79606e
  * boost-variant2[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-variant2\b9af9e4791e65b001bbfb107eeecf819369a06b3
  * boost-winapi[core]:x64-windows-static -> 1.79.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-winapi\7f82a0041bb3b4ac1f3721afe5ba4e24e27c3a3c
    curl[core,openssl]:x64-windows-static -> 7.84.0#1 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\curl\4d64a4ac7f080159be045ccbf0a7fa81ef859cfa
  * expat[core]:x64-windows-static -> 2.4.8#1 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\expat\18754c99766e364a887a08bbf85c7fae06185f36
    fmt[core]:x64-windows-static -> 7.1.3#2 -- G:/Cone/cemu-latest/dependencies/vcpkg_overlay_ports\fmt
    glm[core]:x64-windows-static -> 0.9.9.8#1 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\glm\4aafac80f39a72fadaf6a31afb961790678062de
    glslang[core]:x64-windows-static -> 11.8.0 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\glslang\4d7780995e9523d16a56714fcef0159f18ecfa52
  * libjpeg-turbo[core]:x64-windows-static -> 2.1.4 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\libjpeg-turbo\07c9848d16ee346b314e87e6c0d856bfb0745af9
  * liblzma[core]:x64-windows-static -> 5.2.5#6 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\liblzma\96b6aac6211ad3fd3da29508a519c3cd5f09716d
    libpng[core]:x64-windows-static -> 1.6.37#18 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\libpng\5e3ec787e7c6f09dd162648b700aeb712af0ffd2
    libzip[core]:x64-windows-static -> 1.9.2 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\libzip\ec8e48c035f43c65ce9f0f5b455affaa92aa477e
    openssl[core]:x64-windows-static -> 3.0.5#4 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\openssl\557ff31f9a64f01cd0d98dd44793ce3c7fd32893
    pugixml[core]:x64-windows-static -> 1.12.1#1 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\pugixml\0af6c22cb58a218893ca193a5f5d29d7d1753355
    rapidjson[core]:x64-windows-static -> 2022-06-28#3 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\rapidjson\b33122751fc9d722f05cc50538aa9b6d08e2d105
    sdl2[core]:x64-windows-static -> 2.0.22#3 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\sdl2\69c64474577715f87366d9374b0483256f305f1e
  * tiff[core,jpeg,lzma,zip]:x64-windows-static -> 4.4.0#1 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\tiff\7d5e9083d0072a4370b44f434cd4dac7b3bee7bc
  * vcpkg-cmake[core]:x64-windows -> 2022-07-18 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\vcpkg-cmake\a7b618b7782f3c841d7fd2d84a6ba3619815362a
  * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06#1 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\vcpkg-cmake-config\8d54cc4f487d51b655abec5f9c9c3f86ca83311f
  * vcpkg-cmake-get-vars[core]:x64-windows -> 2022-05-10#1 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\vcpkg-cmake-get-vars\b50ca3d20736304215fbd82c102d4552457255bb
    wxwidgets[core]:x64-windows-static -> 3.2.0#1 -- G:/Cone/cemu-latest/dependencies/vcpkg_overlay_ports\wxwidgets
    zlib[core]:x64-windows-static -> 1.2.12#1 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\zlib\ecc4c064d4911faf12d8bf5fd6bcd5c556d89774
    zstd[core]:x64-windows-static -> 1.5.2#1 -- G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\zstd\2f8a5da3f925dc994500dabb2d3b5c7e11df0afd
Additional packages (*) will be modified to complete this operation.
Removing 1/103 boost-vcpkg-helpers:x64-windows-static
Elapsed time to handle boost-vcpkg-helpers:x64-windows-static: 104.3 ms
Removing 2/103 boost-uninstall:x64-windows-static
Elapsed time to handle boost-uninstall:x64-windows-static: 32.75 ms
Restored 1 package(s) from C:\Users\灏忕帀\AppData\Local\vcpkg\archives in 167.6 ms. Use --debug to see more details.
Installing 3/103 boost-uninstall:x64-windows-static...
Building boost-uninstall[core]:x64-windows-static...
-- Installing port from location: G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-uninstall\e2d05f10364104d9b7de2383bcb105a1fd3fe975
--
Please use the following command when you need to remove all boost ports/components:
    "./vcpkg remove boost-uninstall:x64-windows-static --recurse"

-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: "C:\Users\灏忕帀\AppData\Local\vcpkg\archives\b0\b0119bc855472c7b2916c96ad98bb4b57a83acafde0706ad5ad968686815fb71.zip"
Elapsed time to handle boost-uninstall:x64-windows-static: 253.3 ms
Installing 4/103 boost-vcpkg-helpers:x64-windows-static...
Building boost-vcpkg-helpers[core]:x64-windows-static...
-- Installing port from location: G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-vcpkg-helpers\0e96a2cb3400bcafd55070d18bdcab64808ada01
-- Installing: G:/Cone/cemu-latest/dependencies/vcpkg/packages/boost-vcpkg-helpers_x64-windows-static/share/boost-vcpkg-helpers/boost-modular-headers.cmake
-- Installing: G:/Cone/cemu-latest/dependencies/vcpkg/packages/boost-vcpkg-helpers_x64-windows-static/share/boost-vcpkg-helpers/usage
-- Using cached boost_LICENSE_1_0.txt.
-- Installing: G:/Cone/cemu-latest/dependencies/vcpkg/packages/boost-vcpkg-helpers_x64-windows-static/share/boost-vcpkg-helpers/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: "C:\Users\灏忕帀\AppData\Local\vcpkg\archives\0f\0f4271551c977d01f428c5e3a5d0c2626fdb78af383d4f762cce492b5100d7aa.zip"
Elapsed time to handle boost-vcpkg-helpers:x64-windows-static: 282.9 ms
Installing 5/103 boost-config:x64-windows-static...
Building boost-config[core]:x64-windows-static...
-- Installing port from location: G:\Cone\cemu-latest\dependencies\vcpkg\buildtrees\versioning_\versions\boost-config\22c6532dcc9c24fd85febb93dc936e68c031043a
-- Using cached boostorg-config-boost-1.79.0.tar.gz.
-- Extracting source G:/Cone/cemu-latest/dependencies/vcpkg/downloads/boostorg-config-boost-1.79.0.tar.gz
error: building boost-config:x64-windows-static failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-config
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-config]+Build+error
Include '[boost-config] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-10-17-3247920fbdd47d08f36cbd480addd9890d3c2435
    vcpkg-scripts version: aac6b3ca8 2022-11-10 (3 weeks ago)

Please use the prefilled template from G:\Cone\cemu-latest\build\vcpkg_installed\vcpkg\issue_body.md when reporting your issue.
-- Running vcpkg install - failed
CMake Error at dependencies/vcpkg/scripts/buildsystems/vcpkg.cmake:868 (message):
  vcpkg install failed.  See logs for more information:
  G:\Cone\cemu-latest\build\vcpkg-manifest-install.log
Call Stack (most recent call first):
  G:/tools/mingw64/share/cmake-3.25/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:31 (project)

-- Configuring incomplete, errors occurred!

- Attach ***every failure log file*** mentioned in the console output.
- [vcpkg-manifest-install.log](https://github.com/microsoft/vcpkg/files/10146752/vcpkg-manifest-install.log)

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by FrankXie05** [comment]
@RainbowTaro2022 Please make sure that you have installed vs and the corresponding complete components locally.

**Comment by RainbowTaro2022** [comment]
![image](https://user-images.githubusercontent.com/42478088/205674916-85798a00-c87c-4f36-853d-3dbc6cda911e.png)
Which component have I not installed

**Comment by RainbowTaro2022** [comment]
Config is ready. This time, the assert compilation is wrong again

**Comment by JackBoosY** [comment]
Please double confirm you have enough disk space, and close anti-virus then try again.

**Comment by RainbowTaro2022** [comment]
Why can't I compile when I've turned off antivirus

**Comment by JackBoosY** [comment]
> Why can't I compile when I've turned off antivirus

I don't know what you mean. Did you build successful?

**Comment by JackBoosY** [comment]
```
-- Extracting source G:/Cone/cemu-latest/dependencies/vcpkg/downloads/boostorg-config-boost-1.79.0.tar.gz
error: building boost-config:x64-windows-static failed with: BUILD_FAILED
```
From your log, it seems that the archive extract failed. Maybe some process such as anti-virus stop this operation.

Can you please provide the full log?

**Comment by FrankXie05** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
