### ISSUE TITLE
CUDA 9.0 compilation issues

### ISSUE THREAD

**Issue by cmpute** [microsoft/vcpkg#2814]
I don't know whether some one has encountered any problems when using CUDA 9 with VS2017, but I actually haven't successfully built packages with cuda feature onec. Many packages which contain CUDA support haven't completely finished CUDA 9 support.

Here are messages of four major kinds of errors:
1. `Error generating XXXXX.cu.obj`: This might occurred when the package source haven't implemented VS2017 support, since the compiler path is [changed from VS2015 to VS2017](https://stackoverflow.com/questions/45918446/compiling-opencv-3-3-with-cuda-9-0rc).
1. `Host compiler targets unsupported OS`: MSVC compiler is (so new that) no supported by CUDA, as #2791 stated.
1. `unsupported Microsoft Visual Studio version! Only the versions 2012, 2013, 2015 and 2017 are supported`: MSVC compiler is not in proper range given by CUDA. Edit `<CUDA-Path>/include/crt/host_config.h` can temporarily fix this.
1. `expression must have a constant value`: If you have the these issues above fixed, you will meet this problem when using CUDA 9 with VS2017. This seems to be an API corruption. Rolling back to VS version older than 2017 15.4 or using toolset v140 may be able to fix this. Two ways to use v140 in VS2017:
    - Define `-T v140` in `vcpkg_configure_cmake`
    - Use `vsvarall.bat` to set shell environment to use v140, and then use vcpkg to build. (For ports using ninja)

Related issues in other repositories are collected here:
1. https://github.com/fireice-uk/xmr-stak/issues/91
2. https://github.com/fireice-uk/xmr-stak/issues/606
3. [CUDA 9.0 does not work with the latest VS 2017 update](https://devtalk.nvidia.com/default/topic/1027209/cuda-9-0-does-not-work-with-the-latest-vs-2017-update/)
4. [CUDA 9 failed to support the latest Visual Studio 2017 version 15.5](https://devtalk.nvidia.com/default/topic/1027299/cuda-setup-and-installation/cuda-9-failed-to-support-the-latest-visual-studio-2017-version-15-5/1)

I open this issue here to track the avaliability of CUDA support, and provide solution for ones who has faced similar problems.

**Comment by cmpute** [comment]
Actually, use `vsvarall.bat` proved to be ineffective because of the `cmd_execute_clean` in vcpkg codes. I'm now wondering is there any method to pass custom environment variable into the actual build environment?

**Comment by cenit** [comment]
Even latest CUDA release does not seem to support 14.12 compiler, so it's not so easy to have it working with the latest VS 15.5 update... unfortunately.

**Comment by jasjuang** [comment]
Unfortunately it will only work with VS2017 15.4

See https://devtalk.nvidia.com/default/topic/1027299/cuda-setup-and-installation/cuda-9-failed-to-support-the-latest-visual-studio-2017-version-15-5/

The download link is here https://docs.microsoft.com/en-us/visualstudio/productinfo/installing-an-earlier-release-of-vs2017

**Comment by cenit** [comment]
it's better to install older toolchain with newer vs ;)
in the manual install inside the vs installer (also the latest one, 15.5.5) you can find v141 and v14.11, working with cuda

**Comment by cmpute** [comment]
How about downgrade to use v140? I ran `vcpkg install opencv[cuda]` just now with v140 but failed. However, I directly opened the generated solution file and built using VS2017 15.6, it succeeded.....

**Comment by ras0219-msft** [comment]
We don't currently have a way to pass _multiple_ toolsets into a build, which could explain the difference.

>Edit `<CUDA-Path>/include/crt/host_config.h` can temporarily fix this.

I want to see what we can do around this -- since we have quite a bit of control when building libraries inside vcpkg, we can likely work around any issues that occur due to the newer compiler+libraries (such as using macros to disable parts of the STL that are problematic for that particular build).

**Comment by cmpute** [comment]
@ras0219-msft It's a bit different from disable parts of a package inside vcpkg, since CUDA is installed globally, and modification is not recommended in my opinion.

Besides, I don't mentioned this issue for multiple toolsets in one build, but how can I use vcpkg to specify the buildchain I used in the whole build process? When I look through the issues, I only found `VCPKG_PLATFORM_TOOLSET` may be able to do this. But this variable behaves beyond my expectation, it sets the generator version instead of compiler version. I'm unable to use v140 toolset within VS2017 with this variable. However, `vsvarall.bat` is expected to set the buildchain within the commandline.

**Comment by ras0219-msft** [comment]
`set(VCPKG_PLATFORM_TOOLSET v140)` inside the triplet file _should_ run the correct vsvarsall.bat -- if it doesn't, that's a bug!

Adding `--debug` to the install command line will print more diagnostic information (including the vsvars we're running!), and you can use `vcpkg env --triplet <triplet>` to get the cmd prompt we build libraries inside.

**Comment by cmpute** [comment]
I made a mistake that I thought VCPKG_PLATFORM_TOOLSET can be set in portfile. I set in triplet file and now it works! Thanks! But the issue should be open until CUDA 9 can be compiled with VS2017

**Comment by JackBoosY** [comment]
Hi everyone, I can't reproduce this issue on the latest version, maybe someone has fixed it.
Please update vcpkg and rebuild cuda.

Thanks.
