### ISSUE TITLE
[harfbuzz] Build error with visual studio 2015

### ISSUE THREAD

**Issue by gisnewbird** [microsoft/vcpkg#28156]
**Host Environment**

- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**

`./vcpkg install xxxx`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Adela0814** [comment]
@gisnewbird  Please provide the repro steps and failure logs.
