### ISSUE TITLE
[qt5-webglplugin] qwebgl.dll is not included in the installation file 

### ISSUE THREAD

**Issue by WangZP10969** [microsoft/vcpkg#28154]
**Host Environment**

- OS: Windows10
- Compiler: visual studio 2022 17.4.2

**To Reproduce**

branch: https://github.com/microsoft/vcpkg/pull/24683
`.\vcpkg install qt5[activeqt,core,declarative,essentials,imageformats,multimedia,networkauth,quickcontrols2,svg,tools,webglplugin,websockets,xmlpatterns,webview]:x64-windows`

**Failure logs**
qwebgl.dll is not included in the installation file, but qwebgl.dll is included in the file installed directly using the QT online installer.
vcpkg:
![image](https://user-images.githubusercontent.com/47802547/205474755-55092e1f-f5ab-4beb-ac72-429bcf4a6a03.png)
QT installer
![image](https://user-images.githubusercontent.com/47802547/205474738-1739413d-71b9-4f2d-9c25-323abf1bf1a4.png)

**Comment by WangZP10969** [comment]
I just tried the main branch and the result is the same

**Comment by Neumann-A** [comment]
seems like it needs more dependencies. Otherwise it won't build anything
