### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by PellTheTabber1** [microsoft/vcpkg#28151]
error: building harfbuzz:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+harfbuzz
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[harfbuzz]+Build+error
Include '[harfbuzz] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: 163fe7bd3 2022-12-02 (30 hours ago)

**Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
1. ./vcpkg install xxxx
2. See error
Repro code when

**Expected behavior**

**Failure logs**
-(please attached failure logs)

**Additional context**

**Comment by Adela0814** [comment]
@PellTheTabber1  Please provide the failure logs.

**Comment by Adela0814** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
