### ISSUE TITLE
[harfbuzz] Build error

### ISSUE THREAD

**Issue by PellTheTabber1** [microsoft/vcpkg#28168]
[package-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/10150516/package-x64-windows-dbg-out.log)

**Host Environment**

- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**

`./vcpkg install xxxx`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**
C:\VSEN15U3\VC\INCLUDE\xstddef(377): error C2338: The C++ Standard doesn't provide a hash for this type.

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by FrankXie05** [comment]
Please update Visual Studio to 2017 or newer. https://github.com/harfbuzz/harfbuzz/issues/3451

**Comment by PellTheTabber1** [comment]
Thank you for assigning someone, I've been out of the Powertab loop for many years, but I'm back and hopefully will start writing some good code again.  I will help improve it but I have NO idea why I  can't get the QT stuff to run.

**Comment by FrankXie05** [comment]
The upstream cannot adapt to the VS2015 C++standard. Please use a version later than 2017. :)

**Comment by PellTheTabber1** [comment]
I have VS 2015 and 2017.  My 2015 version is a nice piece due to features I added almost 10 years ago.  It will never die! But I posted a thread to get help with why Qt and Qt tools aren't installing.  Should I just download the binaries? Did you look at the error?

**Comment by PellTheTabber1** [comment]
iS IT A cmAKE VERSION ISSUE?

**Comment by dg0yt** [comment]
> iS IT A cmAKE VERSION ISSUE?

AFAIU it is an upstream (harfbuzz) requirement with regard to the Visual Studio version. Not a vcpkg issue.

**Comment by FrankXie05** [comment]
@PellTheTabber1 does the issue still occur?

**Comment by PellTheTabber1** [comment]
Yes, I need to look in detail at vcpkg and try to feed it something to make the build go more as planned, perhaps some vvariables need to be set.  I don';t yet know which ones.  Perhaps the entire set of tools has to be rebuilt and forced to use a certain compiler.

**Comment by PellTheTabber1** [comment]
> @PellTheTabber1 does the issue still occur?

Issue resolved.

**Comment by PellTheTabber1** [comment]
The make isn't going well, it seems to be using Microsoft's cmake which is version 3.12, while my own install is version 3.25.  So I've tried to change that.  Not sure if I can have Microsoft's CMake.  ASnd it can't find the boost header files.  2 errors so far in the build process - it's set to run CMake automatically when I open the project in Team Explorer.  I accidentally installed CMake under my Users directory, something I absolutely cannot stand about the install.  It never asked me where I wanted to install it, thanks a lot.  I set my environment variable for the BOOST_DIR but I'm not sure it's right.  And one other thing, the install by vcpkg has 212, 553 files which takes up 31GB.  That's too much when we only use a little of the boost libs.  I need to pare that down.

**Comment by dg0yt** [comment]
The more you move towards a non-standard environment, and the more issues you start to mix, the less likely you will get quick and good support.

 > My 2015 version is a nice piece due to features I added almost 10 years ago. It will never die! 

Fine. But vcpkg won't magically resolve the tool version requirements of the packages you want to use. It provides tested configurations, cross-platform.

 >  perhaps some vvariables need to be set. I don';t yet know which ones.

For windows triplets, vcpkg will clean most environment variables, to avoid even more problems. 

 > the install by vcpkg has 212, 553 files which takes up 31GB. That's too much when we only use a little of the boost libs. I need to pare that down. Perhaps I need to install the boost stuff separately to what is in vcpkg directory?

Too general to provide precise hints.
vcpkg doesn't take much action to clean certain build directories unless explicitly asked to do it. 
It builds debug and release configurations, and it may build packages for the host triplet in addition to the target triplet if they differ. This can take up a lot of space, in particular if you want to build Qt.

**Comment by PellTheTabber1** [comment]
I would guess that my CMake has not been set up at all yet - the CATCH_INCLUDES etc..  It's all unset as I've checked.  I did not use any "external" tools in the previous builds I had done in Visual Studio 2015U3.  I have to set up CMake to work properly.  I also wonder why the vcpkg builds do NOT include header files, I don't see any .hpp files so I'm using my separate install of boost for that.  Not much I can do without the headers.  My old builds were with boost version 1.56 and I had an environment variable set for that.

**Comment by dg0yt** [comment]
I can't help you much at that point but 

> my CMake is still using the old settings 

... successful problem tracing in Cmake starts with a fresh build directory. Caching settings is a key feature of CMake, but it may miss changes to the environment.

**Comment by PellTheTabber1** [comment]
> I can't help you much at that point but
> 
> > my CMake is still using the old settings
> 
> ... successful problem tracing in Cmake starts with a fresh build directory. Caching settings is a key feature of CMake, but it may miss changes to the environment.

I need to stop in my tracks and simply configure Microsoft's CMake, not the one I installed as CMake is not easily changed to external (other than with hard to manage symbolic links).  So I need to close the CMake GUI and simply work with Microsoft's CMake.  There are just some settings that need to be set up correctly.  It doesn't find the Boost libs date_time, iostreams, and it doesn't find some doctest file or something.  I need to simply figure out why the internal CMake cannot find the perfectly built libraries for date_time and iostreams.

**Comment by dg0yt** [comment]
Just to help separate different cases:
- Building ports: If you use `vcpkg install`, vcpkg tool will take care of CMake and toolchain (based on target triplet).
- Building your user project: You can choose which CMake to use, but you must use vcpkg's cmake toolchain file (but you can chainload another toolchain file). This is how vcpkg's install locations and CMake wrappers get into your build.
- If your project is coming with a `vcpkg.json`, vcpkg's cmake toolchain file will enable "manifest mode" and implicitly call `vcpkg install` with additional parameters. (In contrast to the first bullet point, it will consider the toolchain and binary dir settings, and it will choose another installation directory.)

**Comment by PellTheTabber1** [comment]
> Just to help separate different cases:
> 
> * Building ports: If you use `vcpkg install`, vcpkg tool will take care of CMake and toolchain (based on target triplet).
> * Building your user project: You can choose which CMake to use, but you must use vcpkg's cmake toolchain file (but you can chainload another toolchain file). This is how vcpkg's install locations and CMake wrappers get into your build.
> * If your project is coming with a `vcpkg.json`, vcpkg's cmake toolchain file will enable "manifest mode" and implicitly call `vcpkg install` with additional parameters. (In contrast to the first bullet point, it will consider the toolchain and binary dir settings, and it will choose another installation directory.)

I am going to change my environment settings to use the packages I've already buillt which I now realize DO have the headers - it's just the headers are not in the root directory.  I'll try to find date_time and iostreams using the vcpkg stuff which kind of makes sense.  I'll stick to the Microsoft CMake for now as it's the default.  I can try the other CMake once the CMake finds the boost libs.  I have no idea why it finds some boost stuff and not others.

**Comment by PellTheTabber1** [comment]
This is the problem: I am using a version of Boost 1.81 that is later than the files in the build and there are no lines to check the build even in the below snippet (I need to hand-code some lines in there to get it all started):

  if(NOT Boost_VERSION VERSION_LESS 106900)
      message(WARNING "New Boost version may have incorrect or missing dependencies and imported targets")
    endif()

**Comment by luzpaz** [comment]
What's the verdict of this ticket ?
(JFYI, [harfbuzz 8.0](https://github.com/harfbuzz/harfbuzz/releases/tag/8.0.0) was just released)

**Comment by luzpaz** [comment]
bump

**Comment by FrankXie05** [comment]
I think this issue can be closed, it just involves some configuration issues using `vcpkg` and `harfbuzz`.

>All the build does is warn me that I have a newer version, I'm not sure about this.

And about new version, I can submit a PR to close this issue.
