### ISSUE TITLE
Make `name` and `version` optional in the json-schema

### ISSUE THREAD

**Issue by NekkoDroid** [microsoft/vcpkg#28164]
**Describe the bug:**
When creating a `vcpkg.json` for manifest-mode and setting the schema for it, it complains about missing `name` and `version` fields even though they have not been necessary for a while.

**Environment**
- OS: Windows 11
- IDE: CLion 2022.3

**To Reproduce:**
1. Create a `vcpkg.json`
2. Set `$schema` to the current schema

(this will also show that `$schema` isn't an allowed field)

**Expected behavior:**
For end-applications `name` and `version` are not as necessary. And for the tool itself these fields are also not required anymore, so this would just bring the schema up-to-date to the tool.

Might also be worth allowing `$schema` at the top of the file to allow completion in IDEs where the file doesn't have a schema associated with it.

**Comment by MonicaLiu0311** [comment]
Would you like to provide `vcpkg.json` and `specific` logs?

**Comment by NekkoDroid** [comment]
Well, it's not the vpcpkg-tool that compains, it's the IDE that complains that the current json doesn't fulfill the schema specified

```json
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json"
}
```

> One of the following property sets is required: properties 'name', 'version-string', properties 'name', 'version', properties 'name', 'version-semver', or properties 'name', 'version-date'

and

> Property '$schema' is not allowed

**Comment by NekkoDroid** [comment]
So I now that the `microsoft/vcpkg-tool` has a separate schema file to this repos schema file where this isn't an issue.

**Comment by GavinRay97** [comment]
The JSON schema has been deleted and the docs haven't been updated, FYI

**Comment by MattRyder** [comment]
Thanks @NekkoDroid for turning me onto the new location. Quick enough fix, innit.

```diff
{
-   "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json",
+   "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg.schema.json",

```
