### ISSUE TITLE
Add Gamma library - generic synthesis and filtering of signals

### ISSUE THREAD

**Issue by dirkju** [Microsoft/vcpkg#2816]
Requesting a package for Gamma, a generic signal library.
[http://w2.mat.ucsb.edu/gamma/](http://w2.mat.ucsb.edu/gamma/) 

Source on Github: [https://github.com/LancePutnam/Gamma](https://github.com/LancePutnam/Gamma)

**Comment by NancyLi1013** [comment]
This PR has been merged  now. So close it.
