### ISSUE TITLE
How can I install the cgal with vcpkg with the following Error?

### ISSUE THREAD

**Issue by Sajad86** [microsoft/vcpkg#28182]
I want to install CGAL with ".\vcpckg install cgal:x64-windows" command on my win10 system and Visual Studio 2019. but I have the following error.

error: building gmp:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with git pull and vcpkg update.
Then check for known issues at:
https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+gmp
You can submit a new issue at:
[https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[gmp]+Build+error](https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=%5Bgmp%5D+Build+error)
Include '[gmp] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
vcpkg-scripts version: 4cb4a5c5d 2022-11-18 (2 weeks ago)

and the error log is:
0 [main] perl (9080) C:\src\vcpkg\downloads\tools\msys2\583ad6e4115a307a\usr\bin\perl.exe: *** fatal error - cygheap base mismatch detected - 0x11E2408/0x1282408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version. The most recent version should
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution. Rebooting is also suggested if you
are unable to find another cygwin DLL.

    Operating system (Windows/Mac/Linux, 32/64 bits): win 10
    Compiler:
    Release or debug mode:
    Specific flags used (if any):
    CGAL version: 5.5.1
    Boost version:
    Other libraries versions if used (Eigen, TBB, etc.):

**Comment by MonicaLiu0311** [comment]
```
PS E:\vcpkg06> ./vcpkg install cgal:x64-windows
Computing installation plan...
The following packages are already installed:
    cgal[core]:x64-windows -> 5.5.1
cgal:x64-windows is already installed
Restored 0 package(s) from C:\Users\monica\AppData\Local\vcpkg\archives in 147.6 us. Use --debug to see more details.
Total install time: 1.109 ms
The package cgal provides CMake targets:

    find_package(CGAL CONFIG REQUIRED)
    target_link_libraries(main PRIVATE CGAL::CGAL)
```
I can't reproduce your issue, `cygwin1.dll` is a Windows system file, could you try following the prompts?
(If the issue is not solved after trying, please attach the complete error log, thank you.)

**Comment by Sajad86** [comment]
@MonicaLiu0311
I have sent you the full text of the log, which is too long.

**Comment by JackBoosY** [comment]
Is there any documentation upstream about this matching requirement?

**Comment by MonicaLiu0311** [comment]
>This problem is probably due to using incompatible versions of the cygwin DLL. Search for cygwin1.dll using the Windows Start->Find/Search facility and delete all but the most recent version. The most recent version should reside in x:\cygwin\bin, where 'x' is the drive on which you have installed the cygwin distribution. Rebooting is also suggested if you are unable to find another cygwin DLL.

Please search for `cygwin1.dll` to see if there is any result.

**Comment by dg0yt** [comment]
The failed port is gmp, not cgal.
But it is not a particular gmp or cgal issue.

I'm surprised to see the error mention `cygwin1.dll`. `C:\src\vcpkg\downloads\tools\msys2\583ad6e4115a307a\usr\bin\perl.exe` actually needs `C:\src\vcpkg\downloads\tools\msys2\583ad6e4115a307a\usr\bin\msys-2.0.dll`. 
But *I can reproduce the error message*  in my (up-to-date) msys2 bash when I run `downloads/tools/msys2/583ad6e4115a307a/usr/bin/perl.exe`.

Vcpkg needs msys2 for building ports that require tools usually found on Unix systems. It is a general [rule for msys2](https://www.msys2.org/wiki/MSYS2-introduction/#path) that you must not mix different versions of their runtime. Unfortunately, vpckg bypasses msys2's  dependency management and updates its package references only occasionally.

**Comment by MonicaLiu0311** [comment]
>I'm surprised to see the error mention cygwin1.dll. `C:\src\vcpkg\downloads\tools\msys2\583ad6e4115a307a\usr\bin\perl.exe` actually needs `C:\src\vcpkg\downloads\tools\msys2\583ad6e4115a307a\usr\bin\msys-2.0.dll`.
But I can reproduce the error message in my (up-to-date) msys2 bash when I run `downloads/tools/msys2/583ad6e4115a307a/usr/bin/perl.exe`.

You are right, the file is actually called msys-2.0.dll. When I investigated the issue, it turned out that most of the time MSYS2 was failing due to some kind of antivirus scanner or other real-time security protection, which installed without issue. But I'm not sure if it's the same this time...
Or do you have a better suggestion? That would be greatly appreciated.
@dg0yt

**Comment by MonicaLiu0311** [comment]
>Is there any documentation upstream about this matching requirement?

I did not find it.
@JackBoosY

**Comment by JackBoosY** [comment]
The cygwin path to perl or other related tools should be set using the path in _downloads/tools_ to avoid this.

Upstream reply: https://github.com/CGAL/cgal/issues/7104#issuecomment-1337049342

**Comment by dg0yt** [comment]
> When I investigated the issue, it turned out that most of the time MSYS2 was failing due to some kind of antivirus scanner or other real-time security protection, which installed without issue. But I'm not sure if it's the same this time...

I can't answer this quickly, but I can say that my regular MSYS2 installation works fine.
Maybe it is necessary to add a CI check of vcpkg's particular configuration of MSYS2 packages.

**Comment by Sajad86** [comment]
@dg0yt
I'm new in vcpkg
How can I add a cl check?

**Comment by dg0yt** [comment]
> I'm new in vcpkg
> How can I add a cl check?

You probably don't want to do it then ;-)

**Comment by Sajad86** [comment]
@dg0yt 
I wanted to install cgal with vcpkg but I got the above Error!
I excluded the msys2 install directory in antivirus program but it was not succesful.
Do you have any idea to solve this issue?
