### ISSUE TITLE
[harfbuzz] Build error

### ISSUE THREAD

**Issue by PellTheTabber1** [microsoft/vcpkg#28184]
**Host Environment**

- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**

`./vcpkg install xxxx`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by PellTheTabber1** [comment]
I now have Visual Studio 2017 installed and I want to open a solution in the master directory, I downloaded the code but i can't find a solutioin or prj files

**Comment by Adela0814** [comment]
Can you provide your requirements and the failure logs?

**Comment by PellTheTabber1** [comment]
> Can you provide your requirements and the failure logs?

[package-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/10178378/package-x64-windows-dbg-err.log)
[package-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/10178379/package-x64-windows-dbg-out.log)

Plese let me know if you need more I was just tyring to install the Qt stuff.  Command I ran was:
vcpkg install --triplet x64-windows qt5-base qt5-tools

**Comment by Adela0814** [comment]
@PellTheTabber1 Please pull the latest vcpkg(`harfbuzz` v6.0.0) and try again, thanks.

**Comment by Cheney-W** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
