### ISSUE TITLE
[lz4] Provide find_package versioning info for CMake integration

### ISSUE THREAD

**Issue by lioncash** [microsoft/vcpkg#28191]
****

**Is your feature request related to a problem? Please describe.**
Hi! Over at our repository ([yuzu](https://github.com/yuzu-emu/yuzu)) we use vcpkg for handling several dependencies. One such dependency is lz4.

In a recent commit, our dependencies were decoupled a little bit to allow for use of system libraries on Linux, if available ([commit](https://github.com/yuzu-emu/yuzu/commit/3b19f741bd6a19f603858e6cdf8db41516c7075f#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR205))

which as part of the change, adds the following line to one of our CMakeLists files:

```cmake
find_package(lz4 1.8 REQUIRED)
```

This seems to unfortunately break configuring on Windows however and the following output is generated.

![image](https://user-images.githubusercontent.com/712067/205757035-ec754a02-f926-4629-b817-fa16be9e70c1.png)

If the added lz4 line is instead changed to:

```cpp
find_package(lz4 REQUIRED)
```

then the problem goes away and CMake generates files successfully. So it's just me gathering that somehow the provided version info is malformed or not present given the `version: unknown` line in the diagnostic.

**Proposed solution**
Versioning info is provided for the lz4 port

**Describe alternatives you've considered**
We can currently just opt to not specify a version in the `find_package` call, but this loses the ability to enforce required versions.
 
**Additional context**
I think I covered everything. But feel free to ask for more context if you need it!

**Comment by abouvier** [comment]
This only seems to happen when compiling in debug mode: https://github.com/yuzu-emu/yuzu/pull/8640

**Comment by dg0yt** [comment]
The lz4 cmake config exists only in vcpkg. (And it should be in the unofficial namespace by today's guidelines.)
So probably there isn't any other provider, and you already control the version via the vcpkg.json manifest.

OTOH lz4 supports pkg-config officially. If you need versioning without vcpkg lock-in, can you use something like:
~~~cmake
    find_package(PkgConfig)
    pkg_check_modules(LZ4 REQUIRED IMPORTED_TARGET liblz4>=1.8)
    
    target_link_libraries(main PRIVATE PkgConfig::LZ4)
~~~
But this need some extra setup for windows.
