### ISSUE TITLE
[libtheora] incorrect build output

### ISSUE THREAD

**Issue by cspanier** [microsoft/vcpkg#28197]
Package: libtheora

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.34.31935.0

**To Reproduce**

`./vcpkg install libtheora`

**Failure logs**

none

**Additional context**

The build successfully completes. However, the generated CMake find scripts get installed to `vcpkg/installed/x64-windows/share/libtheora/unofficial-theora-config.cmake`. Due to the name mismatch they cannot be found by my project's CMake. Neither `find_package(libtheora CONFIG REQUIRED)` nor `find_package(unofficial-theora CONFIG REQUIRED)` work.

**Comment by cspanier** [comment]
I fixed the issue for me by editing libtheora's portfile:

```patch
-vcpkg_cmake_install()
-vcpkg_cmake_config_fixup(CONFIG_PATH "lib/unofficial-theora")
+vcpkg_install_cmake()
+vcpkg_cmake_config_fixup(CONFIG_PATH "lib/unofficial-theora" PACKAGE_NAME "unofficial-theora")
```

This brings the portfile in line with other "nonofficial" ones. However, this changes the name of the target to `unofficial-theora`, thus potentially breaking existing code that uses libtheora (even though I don't know how anyone would get it to work using the import target).

**Comment by dg0yt** [comment]
> However, this changes the name of the target to unofficial-theora

Don't worry, it only changes the name of the target directory. Without the proposed change, the config is really unusable.

**Comment by Osyotr** [comment]
Sorry, I broke this in https://github.com/microsoft/vcpkg/commit/f0815eb528f8d2bddff9d9184520c35747f8ea9d

**Comment by dg0yt** [comment]
> Sorry, I broke this in [f0815eb](https://github.com/microsoft/vcpkg/commit/f0815eb528f8d2bddff9d9184520c35747f8ea9d)

It would not have happened if vpckg had proper validation...
