### ISSUE TITLE
[vcpkg] Set VCPKG_CHAINLOAD_TOOLCHAIN_FILE in triplet not working

### ISSUE THREAD

**Issue by xiaozhuai** [microsoft/vcpkg#28195]
https://github.com/microsoft/vcpkg/blob/d7c68eea3888e285e4e51b028c13efa1c5229029/triplets/community/wasm32-emscripten.cmake#L1-L24

```cmake
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${EMSCRIPTEN_ROOT}/cmake/Modules/Platform/Emscripten.cmake")
```
Not working at all.
I need to add this option to make it work
`-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE="${EMSCRIPTEN_ROOT}/cmake/Modules/Platform/Emscripten.cmake"`

Include chainload toolchain is early than choose triplet

https://github.com/microsoft/vcpkg/blob/d7c68eea3888e285e4e51b028c13efa1c5229029/scripts/buildsystems/vcpkg.cmake#L208-L337

**Comment by xiaozhuai** [comment]
> The triplet file is included in script mode for portfiles, not in project mode for CMake projects.
> 
> https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#portfiles-are-run-in-script-mode

Does this have anything to do with this question?

**Comment by dg0yt** [comment]
> Does this have anything to do with this question?

There was no clear question. So I can't answer that particular question.

However, there were some statements. So lets validate them.

> Not working at all.

This is wrong. It is working as intented: Being used by maintainer functions in script mode, e.g. here.
https://github.com/microsoft/vcpkg/blob/d7c68eea3888e285e4e51b028c13efa1c5229029/ports/vcpkg-cmake/vcpkg_cmake_configure.cmake#L154-L156

> I need to add this option to make it work
-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE="${EMSCRIPTEN_ROOT}/cmake/Modules/Platform/Emscripten.cmake"

This is right, for building your user project. I think this is also working as intented.

> Include chainload toolchain is early than choose triplet

This is right. I think this also working as intented.

**Comment by xiaozhuai** [comment]
> > Include chainload toolchain is early than choose triplet
> 
> This is right. I think this also working as intented.

Is it possible to include triplet first and then include chainload toolchain? So I don't need to specify `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` for my user project.

**Comment by xiaozhuai** [comment]
> I wouldn't recommend to mix the two worlds. Basically, no project shall be locked into vpckg. And there other ways to feed presets into CMake projects if you want to use them regularly.

Yes, if so, why this line `set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${EMSCRIPTEN_ROOT}/cmake/Modules/Platform/Emscripten.cmake")` exists in `wasm32-emscripten` triplet. It should be remove I guess?

**Comment by dg0yt** [comment]
> why this line `set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${EMSCRIPTEN_ROOT}/cmake/Modules/Platform/Emscripten.cmake")` exists in `wasm32-emscripten` triplet. It should be remove I guess?

See above: It sets a value which is used in script mode (portfiles) in maintainer functions which eventually build ports with CMake. It avoids having to go through `z_vcpkg_select_default_vcpkg_chainload_toolchain`, and it avoids having to change `z_vcpkg_select_default_vcpkg_chainload_toolchain`. (Other triplets probably could do the same, but any change to a triplet file will invalidate all binary artifacts for this triplet.)

**Comment by xiaozhuai** [comment]
> See above: It sets a value which is used in script mode (portfiles) in maintainer functions which eventually build ports with CMake. It avoids having to go through `z_vcpkg_select_default_vcpkg_chainload_toolchain`, and it avoids having to change `z_vcpkg_select_default_vcpkg_chainload_toolchain`. (Other triplets probably could do the same, but any change to a triplet file will invalidate all binary artifacts for this triplet.)

Got it : )
