### ISSUE TITLE
[New Port Request] cadQuery

### ISSUE THREAD

**Issue by sethhillbrand** [microsoft/vcpkg#28209]
Library name: cadQuery

Library description: A python parametric CAD scripting framework based on Open Cascade

Source repository URL: https://github.com/CadQuery/cadquery/

Project homepage (if different from the source repository): https://github.com/CadQuery/cadquery/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
