### ISSUE TITLE
Why do I compile in debug mode,then the library copied is release mode?

### ISSUE THREAD

**Issue by zzandyc** [microsoft/vcpkg#28210]
Why do I compile in debug mode,then the library copied is release mode?

**Comment by JackBoosY** [comment]
Yeah, vcpkg only supports 2 modes:
- debug / release
- release only

**Comment by zzandyc** [comment]
I don't understand. before I update vcpkg,it is ok,but when I updated, debug and release mode the library both release mode?

**Comment by JackBoosY** [comment]
Please provide a reproducible step first.

**Comment by lovelyFan** [comment]
I get this problem too! In Windows 11. I just set "vcpkg integrate install". then I set CMAKE_TOOL_CLAIN at CMakeList.txt.  When I used Ninja to compile,  vcpkg.cmake did not copy. When I used Visual studio 2019 to compile. It copied released ".dll" to bin folder  whether project was release or debug!

**Comment by LilyWangLL** [comment]
> I get this problem too! In Windows 11. I just set "vcpkg integrate install". then I set CMAKE_TOOL_CLAIN at CMakeList.txt. When I used Ninja to compile, vcpkg.cmake did not copy. When I used Visual studio 2019 to compile. It copied released ".dll" to bin folder whether project was release or debug!

Could you please provide a simple project to repro this issue?

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
