### ISSUE TITLE
How do I install a specified version library？

### ISSUE THREAD

**Issue by zzandyc** [microsoft/vcpkg#28211]
In my project，we need openssl1.1，buf vcpkg installed is 3.0.7 default，how do I install the openssl1.1.1?

**Comment by JackBoosY** [comment]
1. Use manifest mode and set the required openssl version: https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md#version-field
2. Find openssl 1.1.1 commit id, then reset your vcpkg to that commit id.
