### ISSUE TITLE
[openssl] Install openssl1.1.1 failed？

### ISSUE THREAD

**Issue by zzandyc** [microsoft/vcpkg#28213]
step：
1.use latest version of vcpkg

2.modify port/openssl/vcpkg.json to
{
  "name": "openssl",
  "version": "1.1.1",
  "builtin-baseline": "06b9e0464af9c7c73227ba9f0fa93c77ef62496e"
}

3.vcpkg install openssl 

error log：
error: building openssl:x86-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openssl]+Build+error
Include '[openssl] Build error' in your bug report title, the following version information in your bug description, and
 attach any relevant failure logs from above.
    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: d7c68eea3 2022-12-05 (32 hours ago)

**Comment by Cheney-W** [comment]
Could you please provide the error log to me?

**Comment by zzandyc** [comment]
> Could you please provide the error log to me?

error: building openssl:x86-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with git pull and vcpkg update.
Then check for known issues at:
https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
[https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openssl]+Build+error](https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=%5Bopenssl%5D+Build+error)
Include '[openssl] Build error' in your bug report title, the following version information in your bug description, and
attach any relevant failure logs from above.
vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
vcpkg-scripts version: https://github.com/microsoft/vcpkg/commit/d7c68eea3888e285e4e51b028c13efa1c5229029 2022-12-05 (32 hours ago)

**Comment by zzandyc** [comment]
PS C:\Projects\vcpkg> .\vcpkg.exe install openssl
Computing installation plan...
The following packages will be built and installed:
    openssl[core]:x86-windows -> 1.1.1
Detecting compiler hash for triplet x86-windows...
Restored 0 package(s) from C:\Users\Charlie\AppData\Local\vcpkg\archives in 201.4 us. Use --debug to see more details.
Installing 1/1 openssl:x86-windows...
Building openssl[core]:x86-windows...
-- Downloading https://github.com/openssl/openssl/archive/openssl-1.1.1.tar.gz -> openssl-openssl-openssl-1.1.1.tar.gz..
.
-- Cleaning sources at C:/Projects/vcpkg/buildtrees/openssl/src/nssl-1.1.1-96d825e305.clean. Use --editable to skip clea
ning for the packages you specify.
-- Extracting source C:/Projects/vcpkg/downloads/openssl-openssl-openssl-1.1.1.tar.gz
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Using source at C:/Projects/vcpkg/buildtrees/openssl/src/nssl-1.1.1-96d825e305.clean
CMake Error at ports/openssl/windows/portfile.cmake:53 (vcpkg_cmake_get_vars):
  Unknown CMake command "vcpkg_cmake_get_vars".
Call Stack (most recent call first):
  ports/openssl/portfile.cmake:30 (include)
  scripts/ports.cmake:147 (include)


error: building openssl:x86-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openssl]+Build+error
Include '[openssl] Build error' in your bug report title, the following version information in your bug description, and
 attach any relevant failure logs from above.
    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: 30a20e8f1 2022-12-07 (4 hours ago)


Please use the prefilled template from C:\Projects\vcpkg\installed\vcpkg\issue_body.md when reporting your issue.

**Comment by Cheney-W** [comment]
`https://github.com/openssl/openssl/archive/openssl-1.1.1.tar.gz` is an invalid url, so where is your `C:/Projects/vcpkg/buildtrees/openssl/src/nssl-1.1.1-96d825e305.clean` come from? 

Could you please provide me with the complete log?

Could you please provide me with the files which you modified in your vcpkg folder?

**Comment by zzandyc** [comment]
> `https://github.com/openssl/openssl/archive/openssl-1.1.1.tar.gz` is an invalid url, so where is your `C:/Projects/vcpkg/buildtrees/openssl/src/nssl-1.1.1-96d825e305.clean` come from?
> 
> Could you please provide me with the complete log?
> 
> Could you please provide me with the files which you modified in your vcpkg folder?

I only modifed the file : vcpkg/ports/openssl/vcpkg.json, vcpkg.json content is：
{
  "name": "openssl",
  "version": "1.1.1",
  "builtin-baseline": "06b9e0464af9c7c73227ba9f0fa93c77ef62496e"
}
I use git blame -l versions/o-/openssl.json to get builtin-baseline

**Comment by zzandyc** [comment]
I failed to use another method:
step:
1.download openssl-1.1.1s.tar.gz
2.put openssl-1.1.1s.tar.gz to vcpkg/downloads directory
3.use command vcpkg hash downloads/openssl-1.1.1s.tar.gz to generate hash
4.modify ports/openssl/vcpkg.json as
{
  "name": "openssl",
  "version": "1.1.1",
  "port-version": 1,
  "description": "OpenSSL is an open source project that provides a robust, commercial-grade, and full-featured toolkit for the Transport Layer Security (TLS) and Secure Sockets Layer (SSL) protocols. It is also a general-purpose cryptography library.",
  "homepage": "https://www.openssl.org",
  "license": "Apache-2.0",
  "dependencies": [
    {
      "name": "vcpkg-cmake",
      "host": true
    },
    {
      "name": "vcpkg-cmake-config",
      "host": true
    },
    {
      "name": "vcpkg-cmake-get-vars",
      "host": true,
      "platform": "windows & !mingw"
    }
  ]
}

5.replace hash value in ports/openssl/portfile.cmake
6.use command vcpkg install openssl --no-downloads

The error log is as follows:
PS D:\vcpkg> .\vcpkg.exe install openssl --no-downloads
Computing installation plan...
The following packages will be built and installed:
    openssl[core]:x86-windows -> 1.1.1#1
Detecting compiler hash for triplet x86-windows...
Restored 0 package(s) from C:\Users\Charlie\AppData\Local\vcpkg\archives in 136.1 us. Use --debug to see more details.
Installing 1/1 openssl:x86-windows...
Building openssl[core]:x86-windows...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:215 (message):
  Downloads are disabled, but
  'D:/vcpkg/downloads/openssl-openssl-openssl-1.1.1.tar.gz' does not exist.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/openssl/portfile.cmake:15 (vcpkg_from_github)
  scripts/ports.cmake:147 (include)


error: building openssl:x86-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openssl]+Build+error
Include '[openssl] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: 5402d24c7 2022-12-08 (3 hours ago)


Please use the prefilled template from D:\vcpkg\installed\vcpkg\issue_body.md when reporting your issue.

**Comment by dg0yt** [comment]
Re-read https://github.com/microsoft/vcpkg/issues/28211#issuecomment-1340402268.
You didn't follow proposal 2 correctly. You need the whole `ports/openssl` directory for given point in history, not just selected modifications.
