### ISSUE TITLE
[usockets] update to 0.8.3

### ISSUE THREAD

**Issue by nbkolchin** [microsoft/vcpkg#28225]
Library name: usockets

New version number: 0.8.3

With 0.8.2 uwebsockets 20.31 doesn't build.

release note: https://github.com/uNetworking/uSockets/releases/tag/v0.8.3

uWebSockets >= 20.31.0 depends on uSockets 0.8.3.
Current vcpkg has uWS v20.31.0 and uSockets 0.8.2, which results in compile error.

**Comment by dg0yt** [comment]
> Current vcpkg has uWS v20.31.0 and uSockets 0.8.2, which results in compile error.

Can you tell more about this error? In vcpkg CI, both ports compile without error.

**Comment by JonLiu1993** [comment]
@nbkolchin, please try to git clone my branch and try if it solves your error.
