### ISSUE TITLE
How do I can build JDBC?

### ISSUE THREAD

**Issue by PoweredByAndrox** [microsoft/vcpkg#28220]
Hello, i added Mysql Connector but it hasn't jdbc binaries. How do i can include it to build?
I didn't find out how i can provide command option to CMake where use "vcpkg install".
Here's says make this to build with jdbc: https://dev.mysql.com/doc/connector-cpp/8.0/en/connector-cpp-source-configuration-options.html#option_cmake_with_jdbc

**Comment by FrankXie05** [comment]
Fixed by PR https://github.com/microsoft/vcpkg/pull/30869
