### ISSUE TITLE
[SDL] update to 2.26.1

### ISSUE THREAD

**Issue by jz315** [microsoft/vcpkg#28223]
Library name:SDL

New version number:2.26.1

Other information that may be useful (release notes, etc...)
https://github.com/libsdl-org/SDL/releases/tag/release-2.26.1

**Comment by quyykk** [comment]
[sdl2] is already at 2.26.1: https://github.com/microsoft/vcpkg/blob/master/ports/sdl2/vcpkg.json#L3

**Comment by JonLiu1993** [comment]
Fixed by https://github.com/microsoft/vcpkg/pull/28113, please git pull your latest vcpkg and use it.
