### ISSUE TITLE
[fontconfig] file not found by [qtbase]

### ISSUE THREAD

**Issue by bramtayl** [microsoft/vcpkg#28229]
I'm on ubuntu. When I build Qt with fontconfig, and run an application, I get 

```
Fontconfig error: Cannot load default config file: No such file: (null)
```

To solve it, I can

```
export FONTCONFIG_PATH="/home/brandon/vcpkg/installed/x64-linux/etc/fonts/"
```

But I think this should be set during build time.

**Comment by dg0yt** [comment]
> To solve it, I can
> 
> ```
> export FONTCONFIG_PATH="/home/brandon/vcpkg/installed/x64-linux/etc/fonts/"
> ```
> 
> But I think this should be set during build time.

It cannot be set like this at built time: vcpkg's binary artifacts must be relocatable. Such settings must be made by the user, library or application when resulting application is executed.

**Comment by Neumann-A** [comment]
Still vcpkg needs to configure fontconfig a bit different and use `/etc/fonts/`, `/usr/etc/fonts/` and maybe `~/etc/fonts/` as default search paths. 

e.g. https://github.com/chromium/chromium/blob/main/third_party/fontconfig/BUILD.gn#L56-L58

relevant source code:
https://github.com/freedesktop/fontconfig/blob/e291fda7d42e5d64379555097a066d9c2c4efce3/src/fcinit.c#L39-L51
