### ISSUE TITLE
[glfw3] Add Wayland support as a Library Feature

### ISSUE THREAD

**Issue by marinedalek** [microsoft/vcpkg#28230]
****

**Is your feature request related to a problem? Please describe.**
When compiling glfw3 on Fedora 37, compilation fails because the default display server in Fedora is new Wayland, but by default glfw3 expects the X Window system on Linux. However, glfw3 does have a config flag which builds it with Wayland support.

**Proposed solution**
I propose the addition of `wayland` as a Library Feature so that this flag can be selected through the usual install / manifest mechanism.

**Describe alternatives you've considered**
I'm not aware of a way to work around this, certainly not in manifest mode.

**Additional context**
I've modified my local copies of `portfile.cmake` and `vcpkg.json` to implement this feature. If people think it sounds like a good idea, I'll be happy to create a pull request.

**Comment by Adela0814** [comment]
@marinedalek Please feel free to open a new PR.
