### ISSUE TITLE
The translation of Chinese(maybe) become mojibake

### ISSUE THREAD

**Issue by Elite-stay** [microsoft/vcpkg#28248]
**Describe the bug**
Using manifest mode, mojibake appears in the output of Visual Studio about vcpkg like:
```
1>姝ｅ湪妫€娴嬩笁鍏冪粍 x64-windows 鐨勭紪璇戝櫒鍝堝笇...
```
I think it is the translation but I'm not sure.

**Environment**
- OS: Windows Simplified Chinese
- Compiler: Visual Studio 17.4.2 Simplified Chinese

**To Reproduce**
1. Add a vcpkg.json with some dependencies
2. Enable manifest mode
3. Compile
4. See output

**Expected behavior**
Show normally

**Comment by JackBoosY** [comment]
It looks like a charset issue.

**Comment by JonLiu1993** [comment]
@Elite-stay, Are the Chinese characters in your output added in your own project? Can you provide me with specific reproduction files?

**Comment by Elite-stay** [comment]
> @Elite-stay, Are the Chinese characters in your output added in your own project? Can you provide me with specific reproduction files?

With any solution. cpp files are utf8 with bom. `vcpkg.json` is utf8.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Did you install English language package in your Visual Studio?

**Comment by Elite-stay** [comment]
> Thanks for posting this issue. Did you install English language package in your Visual Studio?

Yes, I did.

**Comment by LilyWangLL** [comment]
We suggest you use only have English language package in Visual Studio, other language packages log maybe have translation error like this issue. 
https://github.com/microsoft/vcpkg#:~:text=Visual%20Studio%202015%20Update%203%20or%20greater%20with%20the%20English%20language%20pack

**Comment by JackBoosY** [comment]
This maybe caused by the outdated vcpkg executable version, please rerun bootstrap script and try again.

**Comment by Elite-stay** [comment]
> This maybe caused by the outdated vcpkg executable version, please rerun bootstrap script and try again.

I updated. still happened.

> Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2023-03-29/vcpkg.exe

**Comment by Elite-stay** [comment]
Why don't you just find a computer installing Windows OS with zh-CN then debug it? It happens in any machine.

**Comment by Elite-stay** [comment]
I find it why you can't repro it.

In CMake mode, no problem because it set the codepage utf8.
In normal Visual Studio mode, the problem appears.
