### ISSUE TITLE
[open62541] current port is not conforming to the vcpkg maintainer guide

### ISSUE THREAD

**Issue by JulZimmermann** [microsoft/vcpkg#28265]
Hello,

I want to update the `open62541` port to the current release. This seems straightforward, except for the fact that the current port implementation is not conforming to the maintainer guide. I'm unsure if I should keep it this way or fix it and break backward compatibility. But let's look at the problem:

The maintainer guide states ["Do not use features to implement alternatives"](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-use-features-to-implement-alternatives). It even gives `open62541` as an example of a library which can use different crypto backends for TLS and states that in such cases no feature, but instead a fixed default should be used which a user could override via overlay ports.

Ironically, the `open62541` port does exactly the opposite of this and uses the features `openssl` and `mbedtls` for selecting the crypto backend.

To make things even more complicated, the current release of `open62541` doesn't use two different CMake options (`UA_ENABLE_ENCRYPTION_OPENSSL` and `UA_ENABLE_ENCRYPTION_MBEDTLS`) for selecting the crypto backend anymore but instead uses only one option (`UA_ENABLE_ENCRYPTION`) which can be not set (no encryption) or be set to `OPENSSL`,  `MBEDTLS` or `LIBRESSL`. I guess this is better because it doesn't make sense to set multiple crypto providers.

I would now update the port to the current version and implement it conforming to the maintainer guide:
- Continue to support the (default) feature `openssl`, which sets `UA_ENABLE_ENCRYPTION` to `OPENSSL`
- Remove the feature `mbedtls`

This would break the port for users using the current `mbedtls` feature. Is this OK?

The alternative to this approach would probably be to keep both features and to define `mbedtls` to override `openssl`. This would mean:
- no feature enabled: `UA_ENABLE_ENCRYPTION` not set
- `openssl` enabled: `UA_ENABLE_ENCRYPTION` set to `OPENSSL`
- `mbedtls` enabled: `UA_ENABLE_ENCRYPTION` set to `MBEDTLS`
- `openssl` and `mbedtls` enabled: `UA_ENABLE_ENCRYPTION` set to `MBEDTLS`

What is the preferred solution here?

Thanks!

**Comment by FrankXie05** [comment]
@JulZimmermann Thanks for posting this issue.
For policies, `If port [featureA] installations and port [featureB] installations, then port [featureA, featureB] must install.`

Upstream: They only allow one encryption method or no encryption method, which indicates that features are mutually exclusive
https://github.com/open62541/open62541/blob/e2165f5c3f7b5c04f84008412ded2a8e407466bc/CMakeLists.txt#L187
```
if(UA_ENABLE_ENCRYPTION STREQUAL "OFF" OR ${_tmp} GREATER -1)
    set(UA_ENABLE_ENCRYPTION_OPENSSL OFF)
    set(UA_ENABLE_ENCRYPTION_MBEDTLS OFF)
    set(UA_ENABLE_ENCRYPTION_LIBRESSL OFF)
    if(UA_ENABLE_ENCRYPTION STREQUAL "MBEDTLS")
        set(UA_ENABLE_ENCRYPTION_MBEDTLS ON)
    elseif(UA_ENABLE_ENCRYPTION STREQUAL "OPENSSL")
        set(UA_ENABLE_ENCRYPTION_OPENSSL ON)
    elseif(UA_ENABLE_ENCRYPTION STREQUAL "LIBRESSL")
        set(UA_ENABLE_ENCRYPTION_LIBRESSL ON)
    endif()
  ```
Vcpkg: We want to provide all encryption methods for users to choose.

I think we can adopt special methods to meet the requirements of upstream and vcpkg for specific ports 🤔:

1. Provide all encryption methods (satisfying vcpkg).

2. Add feature mutual exclusion judgment in portfile.cmake (satisfying upstream requirements).

@BillyONeal What do you think?

**Comment by JulZimmermann** [comment]
From the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md#do-not-use-features-to-implement-alternatives): `"Existing examples we would not accept today retained for backwards compatibility: [...] open62541"`

So this answers this question.
