### ISSUE TITLE
How do I install GRPC built with c++17?

### ISSUE THREAD

**Issue by marcopiuma** [microsoft/vcpkg#28274]
I have been trying to setup grpc in my environment using vcpkg. I need to build with C++17 and the default installation fails to link to abseil. Reading past posts, I have been trying to install the c++17 feature of absl, but I still get the same linker error.
This is how I install grpc in my environment (docker container):

-----------------------------------------------------------------------------
```
export VCPKG_TARGET_TRIPLET=x64-linux
export vcpkg_install_packages="flatbuffers gtest nlohmann-json yaml-cpp range-v3 fmt"
export vcpkg_grpc_packages="protobuf grpc"

# install open source packages listed in vcpkg_install_packages
cd / && \
    rm -rf /vcpkg && rm -rf vcpkg_grpc && \
    git clone -b 2022.03.10 https://github.com/Microsoft/vcpkg.git /vcpkg && \
    cd /vcpkg/ && \
    ./bootstrap-vcpkg.sh && \
    ./vcpkg update && \
    ./vcpkg install --triplet ${VCPKG_TARGET_TRIPLET} ${vcpkg_install_packages} && \
    ./vcpkg export ${vcpkg_install_packages} --raw --output=../vcpkg_exported && \
    ./vcpkg install --triplet ${VCPKG_TARGET_TRIPLET} abseil[cxx17] ${vcpkg_grpc_packages} --recurse && \
    ./vcpkg export ${vcpkg_install_packages} abseil ${vcpkg_grpc_packages} --raw --output=../vcpkg_grpc_exported && \
mv /vcpkg_exported/ /vcpkg/ && \
mv /vcpkg_grpc_exported/ /vcpkg_grpc/ 
```
-------------------------------------------------------------------------
After this I can find protobuf, grpc and abseil under /vcpkg_grpc/installed/x64-linux. but when I try to build a grpc client, it fails to link to abseil symbols.

----------------------------------------------------------------------------
```
#I also tried with a custom triplet that looks like below, but got the same error.
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_CXX_FLAGS "-std=c++17")
set(ABSL_USE_CXX17 1)
```
-----------------------------------------------------------------------------

<details>
<summary><b>here is the linker output:</b></summary>

-- Configuring done
-- Generating done
-- Build files have been written to: /go/src/RaaS.PerceptionEngine.Core/grpc/build
[1/34] Linking CXX static library videoStreaming/streaming/client/lib/libArchonCloudStreamClient.a
[2/34] Linking CXX executable videoStreaming/restreaming/sampleServer/videoRestreamSampleServer
FAILED: videoStreaming/restreaming/sampleServer/videoRestreamSampleServer
: && /usr/bin/clang++  -Wall -Wextra -Werror -fPIC  -Wl,-z,now -Wl,-z,relro -fPIE -pie videoStreaming/restreaming/sampleServer/CMakeFiles/videoRestreamSampleServer.dir/videoRestreamServer.cpp.o videoStreaming/restreaming/sa
mpleServer/CMakeFiles/videoRestreamSampleServer.dir/__/__/gencpp/operation.pb.cc.o videoStreaming/restreaming/sampleServer/CMakeFiles/videoRestreamSampleServer.dir/__/__/gencpp/operation.grpc.pb.cc.o videoStreaming/restream
ing/sampleServer/CMakeFiles/videoRestreamSampleServer.dir/__/__/gencpp/video_streaming_ffmpeg.pb.cc.o videoStreaming/restreaming/sampleServer/CMakeFiles/videoRestreamSampleServer.dir/__/__/gencpp/video_streaming_ffmpeg.grpc
.pb.cc.o videoStreaming/restreaming/sampleServer/CMakeFiles/videoRestreamSampleServer.dir/__/__/gencpp/video_streaming_common_messages.pb.cc.o videoStreaming/restreaming/sampleServer/CMakeFiles/videoRestreamSampleServer.dir
/__/__/gencpp/video_streaming_common_messages.grpc.pb.cc.o videoStreaming/restreaming/sampleServer/CMakeFiles/videoRestreamSampleServer.dir/__/__/gencpp/video_restreaming_insights.pb.cc.o videoStreaming/restreaming/sampleSe
rver/CMakeFiles/videoRestreamSampleServer.dir/__/__/gencpp/video_restreaming_insights.grpc.pb.cc.o  -o videoStreaming/restreaming/sampleServer/videoRestreamSampleServer -L/vcpkg_grpc/installed/x64-linux/lib   -L/vcpkg/insta
lled/x64-linux/lib -Wl,-rpath,/vcpkg_grpc/installed/x64-linux/lib:/vcpkg/installed/x64-linux/lib  /vcpkg_grpc/installed/x64-linux/lib/libprotobuf.a  /vcpkg_grpc/installed/x64-linux/lib/libgrpc++.a  /vcpkg_grpc/installed/x64
-linux/lib/libgrpc.a  /vcpkg_grpc/installed/x64-linux/lib/libgpr.a  /vcpkg_grpc/installed/x64-linux/lib/libcares.a  /vcpkg_grpc/installed/x64-linux/lib/libaddress_sorting.a  /vcpkg_grpc/installed/x64-linux/lib/libz.a  /vcpk
g_grpc/installed/x64-linux/lib/libssl.a  /vcpkg_grpc/installed/x64-linux/lib/libupb.a  /vcpkg_grpc/installed/x64-linux/lib/libcrypto.a  /vcpkg_grpc/installed/x64-linux/lib/libabsl_bad_optional_access.a  /vcpkg_grpc/installe
d/x64-linux/lib/libabsl_base.a  /vcpkg_grpc/installed/x64-linux/lib/libabsl_str_format_internal.a  /vcpkg_grpc/installed/x64-linux/lib/libabsl_int128.a  /vcpkg_grpc/installed/x64-linux/lib/libabsl_strings.a  /vcpkg_grpc/ins
talled/x64-linux/lib/libabsl_time.a  /vcpkg_grpc/installed/x64-linux/lib/libabsl_time_zone.a  /vcpkg_grpc/installed/x64-linux/lib/libabsl_throw_delegate.a  /vcpkg_grpc/installed/x64-linux/lib/libabsl_raw_logging_internal.a
 -lpthread  -ldl && :
/usr/bin/ld: /vcpkg_grpc/installed/x64-linux/lib/libgrpc++.a(server_builder.cc.o): in function `grpc::CompletionQueue::~CompletionQueue()':
server_builder.cc:(.text._ZN4grpc15CompletionQueueD2Ev[_ZN4grpc15CompletionQueueD5Ev]+0x56): undefined reference to `absl::lts_20211102::Mutex::~Mutex()'
/usr/bin/ld: /vcpkg_grpc/installed/x64-linux/lib/libgrpc++.a(server_builder.cc.o): in function `grpc::ServerCompletionQueue::~ServerCompletionQueue()':
server_builder.cc:(.text._ZN4grpc21ServerCompletionQueueD2Ev[_ZN4grpc21ServerCompletionQueueD5Ev]+0x55): undefined reference to `absl::lts_20211102::Mutex::~Mutex()'
/usr/bin/ld: /vcpkg_grpc/installed/x64-linux/lib/libgrpc++.a(server_builder.cc.o): in function `grpc::CompletionQueue::~CompletionQueue()':
server_builder.cc:(.text._ZN4grpc15CompletionQueueD0Ev[_ZN4grpc15CompletionQueueD5Ev]+0x55): undefined reference to `absl::lts_20211102::Mutex::~Mutex()'
/usr/bin/ld: /vcpkg_grpc/installed/x64-linux/lib/libgrpc++.a(server_builder.cc.o): in function `grpc::ServerCompletionQueue::~ServerCompletionQueue()':
server_builder.cc:(.text._ZN4grpc21ServerCompletionQueueD0Ev[_ZN4grpc21ServerCompletionQueueD5Ev]+0x55): undefined reference to `absl::lts_20211102::Mutex::~Mutex()'
/usr/bin/ld: /vcpkg_grpc/installed/x64-linux/lib/libgrpc++.a(server_builder.cc.o): in function `std::_Sp_counted_ptr_inplace<grpc::internal::ExternalConnectionAcceptorImpl, std::allocator<grpc::internal::ExternalConnectionA
cceptorImpl>, (__gnu_cxx::_Lock_policy)2>::_M_dispose()':
...
</details>

**Comment by JackBoosY** [comment]
Can you please provide grpc install log to check whether cxx 17 was enabled during the build process?

**Comment by marcopiuma** [comment]
[vcpkg-install.log](https://github.com/microsoft/vcpkg/files/10211495/vcpkg-install.log)

I was expecting to see this in the logs when building grpc: 
'Found absl uses CXX17, enable CXX17 feature.' based on patch 00012-fix-use-cxx17.patch, but I did not see it.

also tried to switch to C++14 and I get a bunch of errors in absl like this one:
'error: no type named 'string_view' in namespace 'absl'' which make sense, but none from grpc.

**Comment by marcopiuma** [comment]
[grpc.tar.gz](https://github.com/microsoft/vcpkg/files/10230010/grpc.tar.gz)

Ahh, yes. Now I see the log.
thank you.

**Comment by JackBoosY** [comment]
Copied one build log from install logs:
```
[16/1050] /usr/bin/c++  -I/vcpkg/buildtrees/grpc/src/2180080eb4-87c05d756b.clean/include -I/vcpkg/buildtrees/grpc/src/2180080eb4-87c05d756b.clean -I/vcpkg/buildtrees/grpc/src/2180080eb4-87c05d756b.clean/third_party/address_sorting/include -I/vcpkg/buildtrees/grpc/src/2180080eb4-87c05d756b.clean/src/core/ext/upb-generated -I/vcpkg/buildtrees/grpc/src/2180080eb4-87c05d756b.clean/src/core/ext/upbdefs-generated -I/vcpkg/buildtrees/grpc/src/2180080eb4-87c05d756b.clean/third_party/xxhash -isystem /vcpkg/installed/x64-linux/include -fPIC -std=c++17  -O3 -DNDEBUG -fPIC -std=c++17 -MD -MT CMakeFiles/gpr.dir/src/core/lib/gpr/atm.cc.o -MF CMakeFiles/gpr.dir/src/core/lib/gpr/atm.cc.o.d -o CMakeFiles/gpr.dir/src/core/lib/gpr/atm.cc.o -c /vcpkg/buildtrees/grpc/src/2180080eb4-87c05d756b.clean/src/core/lib/gpr/atm.cc
```
You can see `-std=c++17` was added to the build commands.

**Comment by MonicaLiu0311** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
