### ISSUE TITLE
[openssl] replace the flaky strawberry perl distribution

### ISSUE THREAD

**Issue by BurningEnlightenment** [microsoft/vcpkg#28288]
****

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to install the openssl port and it fails due to vcpkg not being able to download the Strawberry Perl distribution (on Windows®).

**Proposed solution**
> It would be neat if someone can get openssl to build with the perl that comes with git. 

@BillyONeal https://github.com/microsoft/vcpkg/issues/28249#issuecomment-1344875851

**Describe alternatives you've considered**
The strawberry perl distribution (or the necessary subset) could be mirrored, but this is not considered feasible due to licensing issues.

Obviously, there are other Perl-distributions for Windows® out there which could (should?) be evaluated. However, I don't know any one which fits our criterias (e.g. ActiveState Perl (which is recommended by [the OpenSSL wiki](https://wiki.openssl.org/index.php/Compilation_and_Installation#Windows)) requires an account to download).

**Additional context**
This is a follow-up on #28249 

> I took a look at their website issue tracker and it seems that similar [availability] issues have been reported there a few times within the last months:
> - https://github.com/StrawberryPerl/strawberryperl.com/issues/30
> - https://github.com/StrawberryPerl/strawberryperl.com/issues/29
> - https://github.com/StrawberryPerl/strawberryperl.com/issues/23

Solutions to this problem have previously been discussed here:
- https://github.com/microsoft/vcpkg/issues/14280#issuecomment-757547441
- https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/21

Regarding the use of the Perl distribution bundled with git, @dg0yt noted that: 
> For a general replacement, the one which comes with msys2 would be nice, to avoid mixing msys2 runtimes in other ports. But IIRC openssl didn't behave well with msys2 perl when I tried to use it for mingw.
From other issues we also know that openssl needs one particular Perl module, IPC/Cmd.pm.

**Comment by adamkennedy** [comment]
I am the original creator of Strawberry Perl, and although I'm no longer involved in it's maintenance I was just made aware of this issue and that it's distribution via a regular web hosting account has been causing problems for use cases like this.

With regards to licensing issues, I'm not sure what your problems are, but I'd be happy to help assist or give permission in any way I'm capable of that might help you fork/embed parts of it.

The build code that assembles the Strawberry Perl distribution is probably fairly easy to fork of sub-class, and I imagine it could be retooled to drop all the extra weight and just include the one module you need. There's an internal "Vanilla Perl" distro without all the extra bundled stuff that might serve as a suitable starting point.

**Comment by BurningEnlightenment** [comment]
Hi, thank you for the insights!

> With regards to licensing issues, I'm not sure what your problems are, but I'd be happy to help assist or give permission in any way I'm capable of that might help you fork/embed parts of it.

This can only be answered by @BillyONeal who investigated this initially (and hasn't explicitly written down the exact issues anywhere AFAIK). Sadly he is a rather busy person, so I would expect an answer later rather than sooner 😅 @Cheney-W would you mind pinging him?

**Comment by dg0yt** [comment]
AFAIU the issue is fairly clear: **Download.** The official download servers  were unavailable more often than expected. vcpkg has only private asset caching, i.e. each user needs to download assets from official sources at least once.

**Comment by BurningEnlightenment** [comment]
>AFAIU the issue is fairly clear: Download. The official download servers were unavailable more often than expected. vcpkg has only private asset caching, i.e. each user needs to download assets from official sources at least once.

Yes, that's the root issue. One proposed solution was to mirror the strawberry perl download with Microsoft / GitHub resources. This however was thought to be infeasible due to said licensing issues.

**Comment by xavier2k6** [comment]
>One proposed solution was to mirror the strawberry perl download with Microsoft / GitHub resources.

**Strawberry Perl 5.38.0 and 5.36.1** have already been released/hosted on GitHub (64 bit only)
https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases

(32 bit request) is noted in https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/96

The main site of https://strawberryperl.com/ hasn't been updated yet.
reference: https://github.com/StrawberryPerl/strawberryperl.com/issues/34#issuecomment-1642817144

@BillyONeal @Cheney-W Have a look through below links:

https://github.com/StrawberryPerl/strawberryperl.com/issues
https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues
