### ISSUE TITLE
zsh: command not found: vcpkg

### ISSUE THREAD

**Issue by I-am-Mohith** [microsoft/vcpkg#28283]
I am trying to install raylib pkg in my folder but it show zsh: command not found: vcpkg 
`vcpkg install raylib 
zsh: command not found: vcpkg`

**Comment by dg0yt** [comment]
vcpkg is in, and called from, the working directory. The current directory usually isn't in the seach `PATH` for executables. That's why you need to supply the path. On non-Windows systems, try  `./vcpkg`.

**Comment by JackBoosY** [comment]
https://github.com/microsoft/vcpkg#tab-completionauto-completion

**Comment by Adela0814** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
