### ISSUE TITLE
[asio] Prevent `add_library(asio::asio)` if target already exists.

### ISSUE THREAD

**Issue by lesomnus** [microsoft/vcpkg#28298]
****

**Is your feature request related to a problem? Please describe.**
Following CMakeLists.txt fails:
```
# Find twice
find_package(asio CONFIG REQUIRED)
find_package(asio CONFIG REQUIRED)
```
with error:
```
[cmake] CMake Error at /opt/vcpkg/scripts/buildsystems/vcpkg.cmake:618 (_add_library):
[cmake]   _add_library cannot create imported target "asio::asio" because another
[cmake]   target with the same name already exists.
[cmake] Call Stack (most recent call first):
[cmake]   /opt/vcpkg/installed/x64-linux/share/asio/asio-config.cmake:3 (add_library)
[cmake]   /opt/vcpkg/scripts/buildsystems/vcpkg.cmake:829 (_find_package)
[cmake]   CMakeLists.txt:25 (find_package)
```

**Proposed solution**
Do `add_library` only if target `asio::asio` is not already exists.

**Comment by lesomnus** [comment]
> I think this should be fixed in user project.

We usually don't expect "already exists" errors when doing `find_packege` on the same library in nested projects. isn't it?
I don't know who is responsible checking target duplicate, but it feels little bit clumsy doing `if(NOT TARGET ...)` for every `find_packge`.

**Comment by dg0yt** [comment]
> I think this should be fixed in user project.

@xiaozhuai The example was simplifed. The problem itself cannot be fixed in user projects: asio can be requested independently by multiple dependencies of the user project. The user has no control. E.g:
~~~cmake
find_package(A) # and A calls find_dependency(asio)
find_package(B) # and B calls find_dependency(asio)
~~~
