### ISSUE TITLE
[curl] with ssh feature (libssh2) - PDB was not found with libssh2.lib or linking object as if no debug info

### ISSUE THREAD

**Issue by MrGluck** [microsoft/vcpkg#28303]
After adding ssh feature to curl, compiler issue warnings about missing libssh2.pdb.

- OS: [Windows]
- Compiler: VS2022 (143 toolset), X64 Debug configuration

1. add ssh to default-features in ports/curl/vcpkg.json
2. vcpkg install curl:x64-windows-static
3. vcpkg export curl:x64-windows-static --nuget --output=vcpkg --nuget-version=1.0.0
4. add vcpkg.1.0.0.nupkg as package

**Expected behavior**
Compile and link without warnings.

If I copy vcpkg\buildtrees\libssh2\x64-windows-static-dbg\src\CMakeFiles\libssh2.dir\libssh2.pdb to vcpkg.1.0.0.nupkg\installed\x64-windows-static\debug\lib\
the problem is being solved.

**Comment by Adela0814** [comment]
@MrGluck Please provide failure logs. Thanks.

**Comment by MrGluck** [comment]
The installation goes through without errors. I attach the log from the installation.
But warnings are generated during the compilation of the project.

Build started...
1>------ Build started: Project: test, Configuration: Debug x64 ------
1>libssh2.lib(global.c.obj) : warning LNK4099: PDB 'libssh2.pdb' was not found with 'libssh2.lib(global.c.obj)' or at 'C:\Projects\Test\Bin\Debug\Test\libssh2.pdb'; linking object as if no debug info
1>libssh2.lib(session.c.obj) : warning LNK4099: PDB 'libssh2.pdb' was not found with 'libssh2.lib(session.c.obj)' or at 'C:\Projects\Test\Bin\Debug\Test\libssh2.pdb'; linking object as if no debug info
1>libssh2.lib(hostkey.c.obj) : warning LNK4099: PDB 'libssh2.pdb' was not found with 'libssh2.lib(hostkey.c.obj)' or at 'C:\Projects\Test\Bin\Debug\Test\libssh2.pdb'; linking object as if no debug info
1>libssh2.lib(kex.c.obj) : warning LNK4099: PDB 'libssh2.pdb' was not found with 'libssh2.lib(kex.c.obj)' or at 'C:\Projects\Test\Bin\Debug\Test\libssh2.pdb'; linking object as if no debug info
1>libssh2.lib(userauth.c.obj) : warning LNK4099: PDB 'libssh2.pdb' was not found with 'libssh2.lib(userauth.c.obj)' or at 'C:\Projects\Test\Bin\Debug\Test\libssh2.pdb'; linking object as if no debug info
1>libssh2.lib(channel.c.obj) : warning LNK4099: PDB 'libssh2.pdb' was not found with 'libssh2.lib(channel.c.obj)' or at 'C:\Projects\Test\Bin\Debug\Test\libssh2.pdb'; linking object as if no debug info
1>libssh2.lib(scp.c.obj) : warning LNK4099: PDB 'libssh2.pdb' was not found with 'libssh2.lib(scp.c.obj)' or at 'C:\Projects\Test\Bin\Debug\Test\libssh2.pdb'; linking object as if no debug info
1>libssh2.lib(version.c.obj) : warning LNK4099: PDB 'libssh2.pdb' was not found with 'libssh2.lib(version.c.obj)' or at 'C:\Projects\Test\Bin\Debug\Test\libssh2.pdb'; linking object as if no debug info
1>libssh2.lib(knownhost.c.obj) : warning LNK4099: PDB 'libssh2.pdb' was not found with 'libssh2.lib(knownhost.c.obj)' or at 'C:\Projects\Test\Bin\Debug\Test\libssh2.pdb'; linking object as if no debug info
1>libssh2.lib(agent.c.obj) : warning LNK4099: PDB 'libssh2.pdb' was not found with 'libssh2.lib(agent.c.obj)' or at 'C:\Projects\Test\Bin\Debug\Test\libssh2.pdb'; linking object as if no debug info
1>libssh2.lib(sftp.c.obj) : warning LNK4099: PDB 'libssh2.pdb' was not found with 'libssh2.lib(sftp.c.obj)' or at 'C:\Projects\Test\Bin\Debug\Test\libssh2.pdb'; linking object as if no debug info
1>libssh2.lib(openssl.c.obj) : warning LNK4099: PDB 'libssh2.pdb' was not found with 'libssh2.lib(openssl.c.obj)' or at 'C:\Projects\Test\Bin\Debug\Test\libssh2.pdb'; linking object as if no debug info
1>libssh2.lib(keepalive.c.obj) : warning LNK4099: PDB 'libssh2.pdb' was not found with 'libssh2.lib(keepalive.c.obj)' or at 'C:\Projects\Test\Bin\Debug\Test\libssh2.pdb'; linking object as if no debug info
1>libssh2.lib(misc.c.obj) : warning LNK4099: PDB 'libssh2.pdb' was not found with 'libssh2.lib(misc.c.obj)' or at 'C:\Projects\Test\Bin\Debug\Test\libssh2.pdb'; linking object as if no debug info
1>libssh2.lib(packet.c.obj) : warning LNK4099: PDB 'libssh2.pdb' was not found with 'libssh2.lib(packet.c.obj)' or at 'C:\Projects\Test\Bin\Debug\Test\libssh2.pdb'; linking object as if no debug info
1>libssh2.lib(transport.c.obj) : warning LNK4099: PDB 'libssh2.pdb' was not found with 'libssh2.lib(transport.c.obj)' or at 'C:\Projects\Test\Bin\Debug\Test\libssh2.pdb'; linking object as if no debug info
1>libssh2.lib(crypt.c.obj) : warning LNK4099: PDB 'libssh2.pdb' was not found with 'libssh2.lib(crypt.c.obj)' or at 'C:\Projects\Test\Bin\Debug\Test\libssh2.pdb'; linking object as if no debug info
1>libssh2.lib(comp.c.obj) : warning LNK4099: PDB 'libssh2.pdb' was not found with 'libssh2.lib(comp.c.obj)' or at 'C:\Projects\Test\Bin\Debug\Test\libssh2.pdb'; linking object as if no debug info
1>libssh2.lib(mac.c.obj) : warning LNK4099: PDB 'libssh2.pdb' was not found with 'libssh2.lib(mac.c.obj)' or at 'C:\Projects\Test\Bin\Debug\Test\libssh2.pdb'; linking object as if no debug info
1>libssh2.lib(agent_win.c.obj) : warning LNK4099: PDB 'libssh2.pdb' was not found with 'libssh2.lib(agent_win.c.obj)' or at 'C:\Projects\Test\Bin\Debug\Test\libssh2.pdb'; linking object as if no debug info
1>libssh2.lib(pem.c.obj) : warning LNK4099: PDB 'libssh2.pdb' was not found with 'libssh2.lib(pem.c.obj)' or at 'C:\Projects\Test\Bin\Debug\Test\libssh2.pdb'; linking object as if no debug info
1>libssh2.lib(bcrypt_pbkdf.c.obj) : warning LNK4099: PDB 'libssh2.pdb' was not found with 'libssh2.lib(bcrypt_pbkdf.c.obj)' or at 'C:\Projects\Test\Bin\Debug\Test\libssh2.pdb'; linking object as if no debug info
1>libssh2.lib(blowfish.c.obj) : warning LNK4099: PDB 'libssh2.pdb' was not found with 'libssh2.lib(blowfish.c.obj)' or at 'C:\Projects\Test\Bin\Debug\Test\libssh2.pdb'; linking object as if no debug info
1>   Creating library ..\Bin\Debug\Test\test.lib and object ..\Bin\Debug\Test\test.exp
1>test.vcxproj -> C:\Projects\Test\Bin\Debug\Test\test.exe
1>Done building project "test.vcxproj".

[install.log](https://github.com/microsoft/vcpkg/files/10216153/install.log)

**Comment by Adela0814** [comment]
The compiler directly writes the absolute path of the `.pdb` file in the obj file when compiling the static library. The linker can find the `.pdb` file of the static library through this information. This is by design.
![image](https://user-images.githubusercontent.com/95600143/220538155-581786fd-c12d-4ee1-86ed-93b72a7b3b00.png)

Your static library is exported, if the linker cannot find the `.pdb` file with the absolute path when linking, it will also search for the `.pdb` file with the same name as the original `.pdb` file that is put together with the static library lib file. so please copy the `.pdb` file manually.
