### ISSUE TITLE
CPR library  build failure

### ISSUE THREAD

**Issue by Chota22** [microsoft/vcpkg#28300]
- OS:  Windows 8
- Compiler:  mingw 

I'm fairly new to C++ and I've been trying to use cpr from  vcpkg but i can't get it to work when i lunch my code .
here is my CMakelists 

[CMakeLists.txt](https://github.com/microsoft/vcpkg/files/10208311/CMakeLists.txt)

and my code 

`#include <iostream>
#include <cpr/cpr.h>
int main(int, char**) {

    cpr::Response r = cpr::Get(cpr::Url{"https://api.github.com/repos/libcpr/cpr/contributors"});

    r.status_code;                  
    r.header["content-type"];     
    r.text;
    printf("Sa marche " );               
    return 0;
}
`

`./vcpkg install cpr`

the installation of cpr goes fine and i can link it to cmake with out a problem , but i can't manage to use it 
**Failure logs**

[OUTPUT.txt](https://github.com/microsoft/vcpkg/files/10208305/OUTPUT.txt)

**Comment by dg0yt** [comment]
Wrong usage of vcpkg.

From MakeLists.txt:
~~~
cmake_minimum_required(VERSION 3.0.0)
project(Scrapy VERSION 0.1.0)
set (CMAKE_CXX_STANDARD 11)
set(VCPKG_TARGET_TRIPLET x64-mingw-dynamic)
include(C:/msys64/vcpkg/scripts/buildsystems/vcpkg.cmake)
~~~

Key issue:
You must configure the toolchain by setting setting `CMAKE_TOOLCHAIN_FILE` and `VCPKG_TARGET_TRIPLET` before `project`, on the very first run of cmake for a given build dirctory.
(You can do it in CMakeLists.txt, but I would recommend to just pass them to cmake explicitly.

Minor issues:
You should require a more modern version of CMake, unless you depend on now-deprecated behaviours.

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
