### ISSUE TITLE
colmap gui error opening image

### ISSUE THREAD

**Issue by lunkyguy** [microsoft/vcpkg#28313]
os:ubuntu20.04
cuda:11.4
cudnn:8.7

When I use colmap gui set a new project and click "Processing" and "Feature Extraction",then loging "ERROR: Failed to read image file format."

**Comment by lunkyguy** [comment]
![Screenshot from 2022-12-13 19-08-25](https://user-images.githubusercontent.com/14260994/207302462-263ecc34-a7c3-4979-b1c2-5a3f7aba6de3.png)

**Comment by Cheney-W** [comment]
Does this issue only happen with `colmap` installed using **vcpkg** or does it also happen with `colmap` that you manually download and build from `https://github.com/colmap/colmap`?

**Comment by lunkyguy** [comment]
the error only happen using vcpkg. when i build from source code ，it works well

**Comment by Cheney-W** [comment]
Could you please give me a detailed reproduction step? 
For example, your version of vcpkg, the command to install colmap, and the specific process to use colmap. Thank you!

**Comment by lunkyguy** [comment]
> Could you please give me a detailed reproduction step? For example, your version of vcpkg, the command to install colmap, and the specific process to use colmap. Thank you!

vcpkg version is 2022-12-14. I install colmap using command "./vcpkg install colmap[cuda]:x64-linux",and I open the exe in tools dir "./colmap".and it works well in windows but wrong in linux.

**Comment by JonLiu1993** [comment]
@lunkyguy, I install `colmap[cuda]:x64-linux` on my local machine also failed, but I got the different error from your, could you please provide the latest error log for me? Thanks.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/63675417/218974485-f9f86c63-cfa6-48ab-8fc6-59ad8c703d79.png)

**Comment by lunkyguy** [comment]
> @lunkyguy, I install `colmap[cuda]:x64-linux` on my local machine also failed, but I got the different error from your, could you please provide the latest error log for me? Thanks. ![MicrosoftTeams-image](https://user-images.githubusercontent.com/63675417/218974485-f9f86c63-cfa6-48ab-8fc6-59ad8c703d79.png)

I forgot which one is right,you should install fortrain like this
![62332f766d2bb6ead19b9bb583347d7](https://user-images.githubusercontent.com/14260994/218977719-d11ebc04-3d74-4bcd-93c0-2a1673ad70fe.png)

sudo apt-get install gfortain
