### ISSUE TITLE
[opencv4] Patch 0018-fix-depend-tesseractis present, but unused

### ISSUE THREAD

**Issue by horenmar** [microsoft/vcpkg#28318]
****

We have a custom opencv4 port, that we sometimes rebase off the one in this repo. When updating to current version, I noticed that the patch file mentioned in title is present, but unused. I _think_ this is just a bug in the original PR, as the commit adding it, https://github.com/microsoft/vcpkg/commit/d3431006f27468065ef53f33254fac9a181337ef, changes opencv3 to use it, but does not change opencv4.

**Proposed solution**
Either the patch file should be applied, or it should be removed.

**Comment by JonLiu1993** [comment]
@horenmar, Thanks for posting this issue, 0018-fix-depend-tesseractis patch was added by this [commit ](https://github.com/microsoft/vcpkg/commit/69e4d02ce490741a0007375c26aefd6655c53baf#diff-cd0cc69c429a833349fdd828b871d440ef062b8f710831b71e69e8a7a4d024fd), and the [commit ](https://github.com/microsoft/vcpkg/commit/d3431006f27468065ef53f33254fac9a181337ef)you refer not add it, just remade this patch, so the patch is needed.

**Comment by Neumann-A** [comment]
@horenmar: close

https://github.com/microsoft/vcpkg/blob/56765209ec0e92c58a5fd91aa09c46a16d660026/ports/opencv4/portfile.cmake#L174

**Comment by horenmar** [comment]
@Neumann-A 🤦 Fair, thanks
