### ISSUE TITLE
'VisualStudio2022-WSL-vcpkg' related 'ncurses' bug

### ISSUE THREAD

**Issue by hihig2001** [microsoft/vcpkg#28310]
**Describe the bug**
ncurses that has built inside wsl should search terminfo directory filename with mixed-case not hexadecimal case, without explicit build flag.

**Environment**
- OS: windows, wsl-ubuntu22.04 lts, visual studio 2022 17.4.1 (17~17.4.1 would work, in 17.4.2, cmake-wsl is not because of vs bug) 
- Compiler: currently clang 15.0.6 but it will work in version below too

**To Reproduce**

1. Use VisaulStudio2022 cmake development setup
2. use below repo to reproduce
- https://github.com/JihwanKimA/rogue-cpp
- this repo is original 'rogue' using cmake environment that has buildable using VS2022 with WSL
- in widowns build, it uses 'PDCurses'
- in linux build, it uses 'ncurses'
3. execute builted 'rogue-cpp'

**Expected behavior**
should read "terminfo" from mixed-case filename folder, instead reading it from hexadecimal character filename folder

In ncurses, there are some kind of environment detecting in build script,
but the build script is somehow confused filename environment when it has built using vcpkg in wsl.
 
**Failure logs**
"Error opening terminal: xterm-256color."
when run this executable

**Additional context**
bug evasion modified port file
I had to add '--enable-mixed-case' build flag

              --enable-mixed-case
                      override   the   configure  script's  check  if  the
                      filesystem   supports   mixed-case  filenames.  This
                      allows one to control how the terminal database maps
                      to  the  filesystem.  For  filesystems  that  do not
                      support   mixed-case,   the  library  uses  generate
                      2-character  (hexadecimal) codes for the lower-level
                      of the filesystem terminfo database

https://lists.gnu.org/archive/html/info-gnu/2008-11/msg00002.html
<details>
  <summary>Full modified port script</summary>
 
```
set(NCURSES_VERSION_STR 6.3)
vcpkg_download_distfile(
    ARCHIVE_PATH
    URLS
        "https://invisible-mirror.net/archives/ncurses/ncurses-${NCURSES_VERSION_STR}.tar.gz"
        "ftp://ftp.invisible-island.net/ncurses/ncurses-${NCURSES_VERSION_STR}.tar.gz"
        "https://ftp.gnu.org/gnu/ncurses/ncurses-${NCURSES_VERSION_STR}.tar.gz"
    FILENAME "ncurses-${NCURSES_VERSION_STR}.tgz"
    SHA512 5373f228cba6b7869210384a607a2d7faecfcbfef6dbfcd7c513f4e84fbd8bcad53ac7db2e7e84b95582248c1039dcfc7c4db205a618f7da22a166db482f0105
)

vcpkg_extract_source_archive(
    SOURCE_PATH
    ARCHIVE "${ARCHIVE_PATH}"
)

set(OPTIONS
    --disable-db-install
    --enable-mixed-case
    --enable-pc-files
    --without-ada
    --without-manpages
    --without-progs
    --without-tack
    --without-tests
)
if(VCPKG_LIBRARY_LINKAGE STREQUAL "dynamic")
    list(APPEND OPTIONS
        --with-shared
        --with-cxx-shared
        --without-normal
    )
endif()
if(VCPKG_TARGET_IS_MINGW)
    list(APPEND OPTIONS
        --disable-home-terminfo
        --enable-term-driver
        --disable-termcap
    )
endif()

file(MAKE_DIRECTORY "${CURRENT_INSTALLED_DIR}/debug/lib/pkgconfig")
file(MAKE_DIRECTORY "${CURRENT_INSTALLED_DIR}/lib/pkgconfig")

set(OPTIONS_DEBUG
    "--with-pkg-config-libdir=${CURRENT_INSTALLED_DIR}/debug/lib/pkgconfig"
    --with-debug
    --without-normal
)
set(OPTIONS_RELEASE
    "--with-pkg-config-libdir=${CURRENT_INSTALLED_DIR}/lib/pkgconfig"
    --without-debug
    --with-normal
)

vcpkg_configure_make(
    SOURCE_PATH "${SOURCE_PATH}"
    DETERMINE_BUILD_TRIPLET
    OPTIONS ${OPTIONS}
    OPTIONS_DEBUG ${OPTIONS_DEBUG}
    OPTIONS_RELEASE ${OPTIONS_RELEASE}
    NO_ADDITIONAL_PATHS
)
vcpkg_install_make()

vcpkg_fixup_pkgconfig()

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/bin")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")

file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
file(INSTALL "${SOURCE_PATH}/COPYING" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```
</details>

**Comment by FrankXie05** [comment]
@hihig2001 Thanks for posting this issue, I will submit a PR to add the compiler option. :)
