### ISSUE TITLE
[qt5-base] Unnecessary cleaning slow down macOS build

### ISSUE THREAD

**Issue by xiaozhuai** [microsoft/vcpkg#28314]
https://github.com/microsoft/vcpkg/blob/8e3fbf662abe9df0422d4df9e97ca5076287287e/ports/qt5-base/cmake/install_qt.cmake#L81-L107

When building `qt5-base` on macOS, it do cleaning twice before and after building.
I didn't see any necessity, although comments says `For some reason there will be an error on MacOSX without this clean!`

And qt cleaning is very very slow!

What reason is it? 
Is this problem still here?
Can this be fixed in other way?

Since it slow down build process very much, I'm looking for a way to improve it.

----------

Update:

I just remove these cleaning, and it fails. here is the error log

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: warning: can't process non-object and non-archive file: /Users/xiaozhuai/vcpkg/vcpkg/packages/qt5-base_x64-osx-catalina-static-release/tools/qt5/bin/syncqt.pl
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: warning: can't process non-object and non-archive file: /Users/xiaozhuai/vcpkg/vcpkg/packages/qt5-base_x64-osx-catalina-static-release/tools/qt5/bin/fixqt4headers.pl
ld: load command #2 extends beyond the end of the load commands file 'metamakefile.o' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../qmake/qmake] Error 1
make[1]: *** [/Users/xiaozhuai/vcpkg/vcpkg/buildtrees/qt5-base/x64-osx-catalina-static-release-rel/qmake/qmake] Error 2
make: *** [sub-qmake-qmake-aux-pro-install_subtargets] Error 2
make: *** Waiting for unfinished jobs....

```

----------

Update:

Found a way to improve this. Cleaning `qmake` dir after build is enough. I'll make a pr.

----------

Update:

No idea why clean `qmake` works, need investigate the cause clearly.

**Comment by FrankXie05** [comment]
Fixed by PR https://github.com/microsoft/vcpkg/pull/28316
