### ISSUE TITLE
[cryptopp] build failure

### ISSUE THREAD

**Issue by smartnet-club** [microsoft/vcpkg#28319]
**Host Environment**

- OS: Ubuntu 22.04
- Compiler: GCC 11

**Failure logs**

#22 65.03 -- Using source at /cache/vcpkg-src/buildtrees/cryptopp/src/6df92864a6-b4419a9589.clean
#22 65.08 -- Configuring x64-linux-dynamic-release
#22 72.58 -- Building x64-linux-dynamic-release-rel
#22 91.21 CMake Error at buildtrees/versioning_/versions/cryptopp/7e3fcbde366bc4af8cc2082053b671352963410d/portfile.cmake:75 (file):
#22 91.21   file RENAME failed to rename
#22 91.21 
#22 91.21     /cache/vcpkg-src/packages/cryptopp_x64-linux-dynamic-release/debug/share/pkgconfig/cryptopp.pc
#22 91.21 
#22 91.21   to
#22 91.21 
#22 91.21     /cache/vcpkg-src/packages/cryptopp_x64-linux-dynamic-release/lib/pkgconfig/cryptopp.pc
#22 91.21 
#22 91.21   because: No such file or directory
#22 91.21 
#22 91.21 Call Stack (most recent call first):
#22 91.21   scripts/ports.cmake:147 (include)
#22 91.21 
#22 91.21 
#22 91.21 error: building cryptopp:x64-linux-dynamic-release failed with: BUILD_FAILED

**Additional context**

the problem in
`file(RENAME "${CURRENT_PACKAGES_DIR}/debug/share/pkgconfig/cryptopp.pc" "${CURRENT_PACKAGES_DIR}/lib/pkgconfig/cryptopp.pc")`

There is no ***debug*** folder in case of release only build

**Comment by MonicaLiu0311** [comment]
Confirmed, reproduced locally.
