### ISSUE TITLE
vcpkg_execute_required_process should configure the C compiler path

### ISSUE THREAD

**Issue by madhur4127** [microsoft/vcpkg#28320]
**Describe the bug**
`vcpkg_execute_required_process` fails to find compiler because `vcpkg` doesn't set up `CMAKE_C_COMPILER` and `$CC` doesn't exist in my system. This causes failure to configure cmake.

**Environment**
- **OS**: WSL2 + Ubuntu 22.04
- **Compiler**: `gcc-11 (Ubuntu 11.2.0-19ubuntu1) 11.2.0`
- **Cmake version**: `3.25.1`
- VS Code + Cmake extension

**To Reproduce**
1. Use this `CMakeLists.txt` to download vcpkg:
    ```cmake
    cmake_minimum_required(VERSION 3.22)
    include(FetchContent)
    FetchContent_Declare(vcpkg
        GIT_REPOSITORY https://github.com/microsoft/vcpkg/
        GIT_TAG 2022.11.14
        GIT_SHALLOW TRUE
    )
    FetchContent_MakeAvailable(vcpkg)

    set(CMAKE_TOOLCHAIN_FILE "${vcpkg_SOURCE_DIR}/scripts/buildsystems/vcpkg.cmake" CACHE FILEPATH "")
    project(temp LANGUAGES "CXX")
    ```
2. Use a vanilla vcpkg.json like:
    ```json 
    {
      "name": "temp",
      "version-string": "0.1.0",
      "dependencies": [ "fmt",  "benchmark", "boost-json", "boost-beast" ]
    }
    ```
3. Invoke cmake as: `/usr/local/bin/cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc-11 -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++-11 -S/home/madhur/playground/cpp "-B/home/madhur/playground/cpp/build_Ninja/Debug_GCC 11.2.0 x86_64-linux-gnu" -G Ninja`

**Expected behavior**
No error while cmake configure.

**Failure logs**
- `buildtrees/detect_compiler/config-x64-linux-rel-err.log`
```
CMake Error at CMakeLists.txt:11 (enable_language):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.
```
- `buildtrees/detect_compiler/stdout-x64-linux.log`
```
-- Found external ninja('1.11.1').
-- Configuring x64-linux-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: /usr/local/bin/cmake "/home/madhur/playground/cpp/build_Ninja/Debug_GCC 11.2.0 x86_64-linux-gnu/_deps/vcpkg-src/scripts/detect_compiler" -G Ninja -DCMAKE_BUILD_TYPE=Release "-DCMAKE_INSTALL_PREFIX=/home/madhur/playground/cpp/build_Ninja/Debug_GCC 11.2.0 x86_64-linux-gnu/_deps/vcpkg-src/packages/detect_compiler_x64-linux" -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/madhur/playground/cpp/build_Ninja/Debug_GCC 11.2.0 x86_64-linux-gnu/_deps/vcpkg-src/scripts/toolchains/linux.cmake" -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF "-DCMAKE_TOOLCHAIN_FILE=/home/madhur/playground/cpp/build_Ninja/Debug_GCC 11.2.0 x86_64-linux-gnu/_deps/vcpkg-src/scripts/buildsystems/vcpkg.cmake" -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin "-D_VCPKG_ROOT_DIR=/home/madhur/playground/cpp/build_Ninja/Debug_GCC 11.2.0 x86_64-linux-gnu/_deps/vcpkg-src" "-DZ_VCPKG_ROOT_DIR=/home/madhur/playground/cpp/build_Ninja/Debug_GCC 11.2.0 x86_64-linux-gnu/_deps/vcpkg-src" "-D_VCPKG_INSTALLED_DIR=/home/madhur/playground/cpp/build_Ninja/Debug_GCC 11.2.0 x86_64-linux-gnu/vcpkg_installed" -DVCPKG_MANIFEST_INSTALL=OFF -DFETCHCONTENT_FULLY_DISCONNECTED=ON
    Working Directory: /home/madhur/playground/cpp/build_Ninja/Debug_GCC 11.2.0 x86_64-linux-gnu/_deps/vcpkg-src/buildtrees/detect_compiler/x64-linux-rel
    Error code: 1
    See logs for more information:
      /home/madhur/playground/cpp/build_Ninja/Debug_GCC\ 11.2.0\ x86_64-linux-gnu/_deps/vcpkg-src/buildtrees/detect_compiler/config-x64-linux-rel-CMakeCache.txt.log
      /home/madhur/playground/cpp/build_Ninja/Debug_GCC\ 11.2.0\ x86_64-linux-gnu/_deps/vcpkg-src/buildtrees/detect_compiler/config-x64-linux-rel-out.log
      /home/madhur/playground/cpp/build_Ninja/Debug_GCC\ 11.2.0\ x86_64-linux-gnu/_deps/vcpkg-src/buildtrees/detect_compiler/config-x64-linux-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:339 (vcpkg_execute_required_process)
  scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:147 (include)
```

**Comment by madhur4127** [comment]
Fwiw, I started seeing this error when I updated my VSCode today to `1.74.0`. Everything worked as is before.

**Comment by Neumann-A** [comment]
That basically means that CMake is unable to find the compiler in the environment. This is not a vcpkg issue since it just uses whatever the environment provides on !windows. vcpk will also not mutate this environment unless you specify it in your triplet/toolchain which vcpkg should use.

**Comment by madhur4127** [comment]
I think that's not true because if I explicitly pass the compiler paths in the cmake configure:

`-DCMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc-11 -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++-11`

However these are not propaged to this command:

```cmake
            vcpkg_execute_required_process(
                COMMAND ${rel_command}
                WORKING_DIRECTORY "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel"
                LOGNAME "${arg_LOGNAME}-rel"
                SAVE_LOG_FILES CMakeCache.txt
            )
```

`
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):`
`  Command failed: /usr/local/bin/cmake "/home/madhur/playground/cpp/build_Ninja/Debug_GCC 11.2.0 x86_64-linux-gnu/_deps/vcpkg-src/scripts/detect_compiler" -G Ninja -DCMAKE_BUILD_TYPE=Release "-DCMAKE_INSTALL_PREFIX=/home/madhur/playground/cpp/build_Ninja/Debug_GCC 11.2.0 x86_64-linux-gnu/_deps/vcpkg-src/packages/detect_compiler_x64-linux" -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/madhur/playground/cpp/build_Ninja/Debug_GCC 11.2.0 x86_64-linux-gnu/_deps/vcpkg-src/scripts/toolchains/linux.cmake" -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF "-DCMAKE_TOOLCHAIN_FILE=/home/madhur/playground/cpp/build_Ninja/Debug_GCC 11.2.0 x86_64-linux-gnu/_deps/vcpkg-src/scripts/buildsystems/vcpkg.cmake" -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin "-D_VCPKG_ROOT_DIR=/home/madhur/playground/cpp/build_Ninja/Debug_GCC 11.2.0 x86_64-linux-gnu/_deps/vcpkg-src" "-DZ_VCPKG_ROOT_DIR=/home/madhur/playground/cpp/build_Ninja/Debug_GCC 11.2.0 x86_64-linux-gnu/_deps/vcpkg-src" "-D_VCPKG_INSTALLED_DIR=/home/madhur/playground/cpp/build_Ninja/Debug_GCC 11.2.0 x86_64-linux-gnu/vcpkg_installed" -DVCPKG_MANIFEST_INSTALL=OFF -DFETCHCONTENT_FULLY_DISCONNECTED=ON
`

**Comment by dg0yt** [comment]
Despite this message:

> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake

it is not the named function's responsibility. The compiler setup from your CMake project is lost on the way, IMO already quite early when the vcpkg tool is invoked from CMake in your project context.
(The target triplet is passed down as expected, but the stock triplet file doesn't carry the specific CMake setup details.)

**Comment by madhur4127** [comment]
thanks @dg0yt!

> The compiler setup from your CMake project is lost on the way

I am not a cmake expert so can you share some pointers as to how it can happen and how to fix it?

For now, I am living with a gross hack: `CC=gcc-11 CXX=g++-11 /usr/local/bin/cmake ...` 😭

**Comment by dg0yt** [comment]
> How it can happen and how to fix it?

- The vcpkg manifest magic happens when CMake reaches your project's `project` command. The vcpkg toolchain file is loaded and invokes vcpkg tool to deal with dependencies. But little more than the target triplet name is actively passed down to the port builds.

  If the vcpkg manifest magic could be triggered after CMake toolchain initialization, it should become possible to always pass down relevant CMake toolchain properties.

- Setting the compiler path is something which you could normally do in a `CMAKE_TOOLCHAIN_FILE`. With `vcpkg.cmake` taking this place, you would pass it in via `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` instead.

  Now somebody should correct me if I'm wrong: `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` is not passed down because the ports are meant to be built with vcpkg's internal toolchain files. Now I wonder if this should work differently.

> I am living with a gross hack: `CC=gcc-11 CXX=g++-11 /usr/local/bin/cmake ..`

Maybe it is a more convenient workaround to add this to your project's CMakeList.txt, before `project`:
~~~cmake
if(CMAKE_C_COMPILER)
    set(ENV{CC} "${CMAKE_C_COMPILER}")
endif()
if(CMAKE_CXX_COMPILER)
    set(ENV{CXX} "${CMAKE_CXX_COMPILER}")
endif()
~~~
So you would only need to set CC and CXX for the first run of CMake (or directly set them via parameters).

**Comment by madhur4127** [comment]
for posterity, I reinstalled by compilers and set the missing `cc`, `c++` links using `update alternatives`. Simple enough.
