### ISSUE TITLE
[vcpkg-tool] Embedded port version should accept 0 in version constraint

### ISSUE THREAD

**Issue by horenmar** [microsoft/vcpkg#28327]
****

**Is your feature request related to a problem? Please describe.**
Today I tried explicitly depending on port version 0 in `version>=` constraint (e.g. `"version>=": "5.0.0#0"`). This was rejected with

```
$.features.fingerprinters.dependencies[0] (a dependency): embedded port-version ('#') in the primary constraint ("version>=") must be a positive integer
$.features.fingerprinters.dependencies[1] (a dependency): embedded port-version ('#') in the primary constraint ("version>=") must be a positive integer
$.features.https-download.dependencies[0] (a dependency): embedded port-version ('#') in the primary constraint ("version>=") must be a positive integerExtended documentation available at 'https://github.com/Microsoft/vcpkg/tree/master/docs/users/manifests.md'.
```

(_Good job on the error reporting btw_), but I believe it should be accepted. There is no good reason to disallow explicitly depending on port version 0, rather than just implicitly (which is what happens when the port version is not embedded).

**Proposed solution**
Relax the check to be just "non-negative numbers"

**Comment by autoantwort** [comment]
Can be closed now :)
