### ISSUE TITLE
[New Port Request] TooN

### ISSUE THREAD

**Issue by bigmouth** [microsoft/vcpkg#28336]
Library name: TooN

Library description: Tom's Object-oriented numerics library - algorithms including matrix decompositions and optimizations

Source repository URL: https://github.com/edrosten/TooN

Project homepage (if different from the source repository): http://www.edwardrosten.com/cvd/toon.html

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
