### ISSUE TITLE
How to create .exe all package installed with vcpkg in VS2015

### ISSUE THREAD

**Issue by shahzadmuh** [microsoft/vcpkg#2833]
Hi,

I install package `vcpkg install curl` and i use `include <curl\curl.h>` and compiled, but i get in debug path many dlls, and an .exe that work with dlls, i am unable to use just .exe in any path if dlls file not exist,

Please help me, if everyone idea for resolve it?

![alt text](http://s9.picofile.com/file/8319694884/dlls.png "Logo Title Text 1")

**Comment by jasjuang** [comment]
The dlls has to be bundled with the exe, unless you add the folder that contains the dlls to the PATH environment variable which is not recommended

**Comment by JackBoosY** [comment]
@shahzadmuh If you want to build a library using vcpkg and get rid of vcpkg when using the library, you can use the command `vcpkg export <port>` to export the library and use the library in the traditional way.
