### ISSUE TITLE
[azure-iot-sdk-c:x64-windows] Could not locate a valid Visual Studio instance

### ISSUE THREAD

**Issue by fgheysels** [microsoft/vcpkg#28342]
**Host Environment**

- OS: Windows 11

**To Reproduce**

I'm following the steps that are defined [here](https://learn.microsoft.com/en-us/azure/iot-edge/how-to-visual-studio-develop-module?view=iotedge-1.4&pivots=iotedge-dev-cli#prerequisites) to prepare my system for IoT Edge development.
I have installed vcpkg and afterwards I need to execute this command:

```
.\vcpkg.exe install azure-iot-sdk-c:x64-windows --triplet=x64-windows
```
which results in this error:
![image](https://user-images.githubusercontent.com/3605786/207595456-b9eff849-34a9-4c2b-aa83-9a0eab562cc0.png)

`.\vcpkg.exe install vcpkg.exe install azure-iot-sdk-c:x64-windows`

**Failure logs**

```
Computing installation plan...
The following packages will be built and installed:
  * azure-c-shared-utility[core]:x64-windows -> 2022-09-15
    azure-iot-sdk-c[core]:x64-windows -> 2022-09-15#1
  * azure-macro-utils-c[core]:x64-windows -> 2022-01-21
  * azure-uamqp-c[core]:x64-windows -> 2022-09-15
  * azure-uhttp-c[core]:x64-windows -> 2022-09-15
  * azure-umqtt-c[core]:x64-windows -> 2022-09-15
  * parson[core]:x64-windows -> 2022-11-13
  * umock-c[core]:x64-windows -> 2022-01-21
  * vcpkg-cmake[core]:x64-windows -> 2022-10-30
  * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06#1
Additional packages (*) will be modified to complete this operation.
error: in triplet x64-windows: Unable to find a valid Visual Studio instance
Could not locate a complete Visual Studio instance
The following paths were examined for Visual Studio instances:
    C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary/Build\vcvarsall.bat
```

**Additional context**

I have VS.NET 2022 Enterprise installed on my system.   The directory `c:\program files\microsoft visual studio\2022\enterprise\VC\Auxiliary` exists on my system, but it has no subdirectory 'Build', nor can I find the `vcvarsall.bat` file on my system.

**Comment by Cheney-W** [comment]
Have you installed `Desktop development with C++`?
![image](https://user-images.githubusercontent.com/38240633/207804566-1a2cf8c0-f46e-4f19-adf8-c32c5666a82b.png)

**Comment by fgheysels** [comment]
Indeed, I didn't have that installed.  
After I installed that feature, it works.
Sorry for wasting your time.
