### ISSUE TITLE
[crashpad/vcpkg-tool-gn] build failure

### ISSUE THREAD

**Issue by cnSchwarzer** [microsoft/vcpkg#28358]
Package: crashpad[core]:x64-windows -> 2022-09-05#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.33.31630.0
- vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
  vcpkg-scripts version: 06071749b 2022-12-14 (32 hours ago)

**To Reproduce**

`vcpkg install `

**Failure logs**

```
-- Note: crashpad only supports static library linkage. Building static library.
-- Using cached C:/vcpkg/downloads/crashpad-261679b3d2f3336d8531ed38e110254c3e2d1c10.tar.gz
-- Cleaning sources at C:/vcpkg/buildtrees/crashpad/src/4c3e2d1c10-1c4f0a1e28.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/crashpad-261679b3d2f3336d8531ed38e110254c3e2d1c10.tar.gz
-- Using source at C:/vcpkg/buildtrees/crashpad/src/4c3e2d1c10-1c4f0a1e28.clean
-- Using cached C:/vcpkg/downloads/crashpad-5654edb4225bcad13901155c819febb5748e502b.tar.gz
-- Extracting source C:/vcpkg/downloads/crashpad-5654edb4225bcad13901155c819febb5748e502b.tar.gz
-- Using source at C:/vcpkg/buildtrees/crashpad/src/b5748e502b-44507d16bb.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows
-- Generating build (x64-windows-dbg)...
-- Generating build (x64-windows-rel)...
-- Building (x64-windows-dbg)...
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -C C:/vcpkg/buildtrees/crashpad/x64-windows-dbg client client:common util third_party/mini_chromium/mini_chromium/base handler:crashpad_handler
    Working Directory: C:/vcpkg/buildtrees/crashpad/src/4c3e2d1c10-1c4f0a1e28.clean
    See logs for more information:
      C:\vcpkg\buildtrees\crashpad\build-x64-windows-dbg-out.log
      C:\vcpkg\buildtrees\crashpad\build-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_ninja.cmake:3 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_build_ninja.cmake:24 (z_vcpkg_build_ninja_build)
  scripts/cmake/vcpkg_install_gn.cmake:95 (vcpkg_build_ninja)
  buildtrees/versioning_/versions/crashpad/f7ead3d493577856543add942c07776fe60ded9e/portfile.cmake:99 (vcpkg_install_gn)
  scripts/ports.cmake:147 (include)



```

<details><summary>C:\vcpkg\buildtrees\crashpad\build-x64-windows-dbg-out.log</summary>

```
ninja: Entering directory `C:/vcpkg/buildtrees/crashpad/x64-windows-dbg'
```

</details>

<details><summary>C:\vcpkg\buildtrees\crashpad\build-x64-windows-dbg-err.log</summary>

```
ninja: error: FindFirstFileExA(../../../../../e:/vtslink/client/build-debug/vcpkg_installed/x64-windows/debug/lib): 文件名、目录名或卷标语法不正确。


```

</details>

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "name": "vts-link-client",
  "version-string": "0.0.1",
  "dependencies": [
    "kcp",
    "libdatachannel",
    "brotli",
    "libyuv",
    "protobuf",
    "concurrentqueue",
    "crashpad",
    {
      "name": "ffmpeg",
      "default-features": true,
      "features": [
        "nvcodec",
        "qsv",
        "x264"
      ]
    }
  ],
  "overrides": [
    {
      "name": "openssl",
      "version-string": "1.1.1m#2"
    }
  ],
  "builtin-baseline": "06071749ba78c76f425765106a94b1832a2ae06e"
}

```

</details>

**Comment by cnSchwarzer** [comment]
For anyone who wants a workaround:
So the problem is for sure related to the `../../../../../E:/` path, and the solution is simple:
1. Clone the gn.exe upstream and modify file `src/gn/escape.cc` 
2. In function `EscapeStringToString`, add this code to remove leading `../`
```
// Escapes |str| into |dest| and returns the number of characters written.
size_t EscapeStringToString(std::string_view str,
                            const EscapeOptions& options,
                            char* dest,
                            bool* needed_quoting) {

  auto vol = str.find(":/");
  if (vol != std::string::npos) {
    str = str.substr(vol - 1, str.size() - vol + 1);
  }
```
3. Build the code with VS Developer console if you are using windows (or follow the gn document)
4. Replace the gn.exe in `vcpkg_installed\x64-windows\tools\gn` under your project's cmake folder
5. Regenerate the cmake and you are good to go.

**Comment by MonicaLiu0311** [comment]
Confirmed, reproduced locally.

**Comment by cnSchwarzer** [comment]
Related links:
https://bugs.chromium.org/p/gn/issues/detail?id=317
https://gn-review.googlesource.com/c/gn/+/14940

**Comment by cnSchwarzer** [comment]
Any suggestions? Could we build gn instead of download it and patch gn for this problem?

**Comment by dg0yt** [comment]
Some feedback based on my recent update to port skia.
(My changes are meant to be generalizable for other gn ports, but I would need more time to do it.)

## gn versioning

`gn` should be used in the version required by the actual package. However, it is a soft requirement: you may use a newer version with good success. 

vcpkg doesn't offer an interface to select a particular version. ATM vcpkg has three way to get gn:
- Port `vcpkg-gn` installs 1945 (4aa9bdfa).
- Port `vcpkg-tool-gn` installs 2014 (c114b7e0).
- `vcpkg_find_acquire_program` installs  2014 (c114b7e0).

crashpad wants gn 2ecd43a10266bd091c98e6dcde507c64f6a0dad3, but implicitly uses the third method. So the version it uses lags by app. 28  commits.

You might try to add a dependency on `vcpkg-tool-gn`, and update this port to a new version of gn.

## Dependency handling

vcpkg needs to de-vendor some dependencies which otherwise would be built by gn. Port crashpad has a function `replace_gn_dependency` to handle this for zlib. 

Please check that it is not this function which injects build code which breaks gn.

**Comment by cnSchwarzer** [comment]
Does that specific version of gn handles path correctly? Because I tried the latest port and it still failed.

**Comment by dg0yt** [comment]
> Does that specific version of gn handles path correctly? Because I tried the latest port and it still failed.

Please ensure you test with the requested version of gn. I don't understand what you actually tried.
I cannot test (MSVC) windows triplets, only mingw triplets which usually come with other problems (and alternative path syntax).

The point is: there is a ninja rule which looks strange. Why is it generated in this way, from which input? 
If already the input is invalid, we can't say that gn doesn't handle paths correctly. Garbage in, garbage out.
OTOH it seems to work for upstream, and it works in vcpkg CI.

**Comment by cnSchwarzer** [comment]
> The point is: there is a ninja rule which looks strange. Why is it generated in this way, from which input?

The strange path (../../../../../E$:/) seems generated by gn (It might comes from input cli, but I don't find any related pattern.) Resulting a corrupted ninja build file.

**Comment by cnSchwarzer** [comment]
> To make it explicit: Is E:\... the location of your user project?

Yes, that is my project using manifest mode. And my vcpkg root is C:\vcpkg

If I directly `vcpkg install crashpad` it will succeed, probably because buildtree and install path are not crossing disk and both on C:\.

**Comment by dg0yt** [comment]
Please test the changes from #28503. I could do some limited experimentation with mingw. It seems that the problem is indeed related to the injection of the zlib paths. With native Windows paths (`\` separator), I don't see the invalid zlib dependency, but the lib still appears in command lines as needed.

**Comment by cnSchwarzer** [comment]
@dg0yt Sadly no, this is not fixed and the error are same. The path still has leading ../../../../../E:/

**Comment by dg0yt** [comment]
Same for skia: #24719

**Comment by cnSchwarzer** [comment]
Does all google projects community like dead? Nobody checks issues...

**Comment by cnSchwarzer** [comment]
FYI: I managed to fix this issue in upstream, do we need to revert #29058 ?
https://gn-review.googlesource.com/c/gn/+/16620
