### ISSUE TITLE
Manifest docs point to JSON schema URL that no longer exists: 

### ISSUE THREAD

**Issue by GavinRay97** [microsoft/vcpkg#28366]
See: https://vcpkg.io/en/docs/users/manifests.html#simple-example-manifest

The `$schema` property is a 404:
```json
{
    "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json",
}
```

Where has this gone?

EDIT: Nevermind, it seems to be updated in the repo, so the website is just outdated

- https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md#simple-example-manifest
```json
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg.schema.json",
  "name": "my-application",
}
```

**Comment by MonicaLiu0311** [comment]
This has been fixed, so this issue will be closed now.
