### ISSUE TITLE
Documentation not updated with new vcpkg.schema.json location

### ISSUE THREAD

**Issue by Pentarctagon** [microsoft/vcpkg#28361]
https://learn.microsoft.com/en-us/vcpkg/users/manifests still points to https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json which gives a 404 error. It should use https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg.schema.json

**Comment by MonicaLiu0311** [comment]
This has been fixed, so this issue will be closed now.
