### ISSUE TITLE
[mp-units] depends on fmt<=8.1.1, but pulls in fmt>9.0.0 -> missing header

### ISSUE THREAD

**Issue by globberwops** [microsoft/vcpkg#28375]
**Describe the bug**
The current mp-units port pulls in the latest fmt port, which is missing the header `fmt/locale.h`, but `units/format.h` includes that header.
mp-units 0.7.0 depends on fmt<=8.1.1.

**Environment**
- OS: Linux
- Compiler: gcc 11.3.0

**To Reproduce**
1. `./vcpkg install mp-units`
2. `#include <units/format.h>`
3. `fatal error: fmt/locale.h: No such file or directory`

**Expected behavior**
Pin fmt version to 8.1.1 for mp-units 0.7.0

**Comment by Neumann-A** [comment]
> Pin fmt version to 8.1.1 for mp-units 0.7.0

Not going to happen. 

What is going to happen is that mp-units gets patch to correctly use newer fmt or that mp-units itself gets moved to a newer commit.

**Comment by globberwops** [comment]
@Neumann-A Even better, thanks!

**Comment by jiayuehua** [comment]
mp-units have update to 0.8.0 #32028, this issue should be fixed.
