### ISSUE TITLE
Forcing FETCHCONTENT_FULLY_DISCONNECTED is inappropriate and breaks projects using private registries

### ISSUE THREAD

**Issue by craigscott-crascit** [microsoft/vcpkg#28386]
**Describe the bug**

#26959 added a change which forced setting the `FETCHCONTENT_FULLY_DISCONNECTED` CMake variable to true when building any port. This breaks ports in private vcpkg registries that rely on using FetchContent to pull in private things that are not available as vcpkg ports (I am working with a client doing exactly that in a production setting, and for good reasons).

While I understand that philosophically vcpkg would like all dependencies to be provided through vcpkg alone, there are plenty of scenarios where that is simply not appropriate and perhaps not even possible (for a variety of reasons). I'll give one example, but it is certainly not the only case.

An increasingly common scenario is where a company collects common build-related logic in a separate git repository and shares that among various projects. This may include toolchain files, so it has to be obtained before the first `project()` call. The common git repo may also set up company-specific things for vcpkg, such as environment variables that need to be defined to access internal servers, locations of private registries, and so on. The canonical pattern for this can be condensed down to something like this:

```cmake
cmake_minimum_required(VERSION 3.24)

include(FetchContent)
FetchContent_Declare(myCompCommonStuff
    GIT_REPOSITORY git@blah.example.com:/some/thing.git
    GIT_TAG        abc123abc123abc123...
)
FetchContent_MakeAvailable(myCompCommonStuff)

project(CoolProject)

do_standard_company_setup_things()

# Add stuff to the project as usual...
```

With the change in #26959, this now breaks when such a project is being made available as a port. The call to `FetchContent_MakeAvailable()` will turn into a no-op, so all of the things the project expects to have been defined by that separate repo (like the `do_standard_company_setup_things()` command in the above example) won't exist.

I disagree with the discussion towards the end of #26959. Expecting projects to duplicate their already working logic by doing things like calling `vcpkg_download_distfile()` or other methods (because things might not be available as a straight archive download) is unreasonable. If you want to force it for the public vcpkg repository, that's your call, but it is highly inappropriate to force it on private registries where the constraints and requirements can be very different. Company projects may be more than happy to not have some things stored in the asset cache (and in some security-sensitive scenarios, might _require_ that they not be cached). The choice should not be taken out of the hands of the maintainer of private registry ports.

As a CMake maintainer and author of FetchContent, I'll also add that I view this as an abuse of `FETCHCONTENT_FULLY_DISCONNECTED`. That option is intended for people who need to work offline, but who would still first need to be online to populate the dependencies initially. Using it to prevent users from populating any dependencies through FetchContent at all is a pretty aggressive move. I'd urge you to reconsider and revert that change.

**Environment**
- OS: all
- Compiler: all

**To Reproduce**

See example given above

**Expected behavior**

`FetchContent_MakeAvailable()` calls should continue to work, at the very least for people maintaining private registries.

**Failure logs**
N/A

**Additional context**

**Comment by Thomas1664** [comment]
I think you're looking for script ports: https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/authoring-script-ports.md

**Comment by Thomas1664** [comment]
> As a CMake maintainer and author of FetchContent, I'll also add that I view this as an abuse of `FETCHCONTENT_FULLY_DISCONNECTED`. That option is intended for people who need to work offline, but who would still first need to be online to populate the dependencies initially. Using it to prevent users from populating any dependencies through FetchContent at all is a pretty aggressive move. I'd urge you to reconsider and revert that change.

We're not abusing this option because the main reason we use it is to support building ports on machines that are disconnected from the internet. Obviously, the assets must still be downloaded via `vcpkg install --only-downloads` on a machine that is connected to the internet. The assets have to be transferred to the offline machine where `vcpkg install --no-downloads` is used to build the ports. As a side effect, we catch vendored dependencies that are not obtained from a public/ private registry, which is also intentional and required to support offline builds and avoid abi issues.

**Comment by Neumann-A** [comment]
`VCPKG_CMAKE_CONFIGURE_OPTIONS` can be used to override whatever vcpkg sets.

**Comment by craigscott-crascit** [comment]
Thanks for the responses. I'm aware of registries and a few different ways to work around this new behavior. My whole point though is that this change breaks some uses of those registries. In the real world, there are projects that simply can't (for a variety of valid reasons!) have all their dependencies supplied by vcpkg. I find it hard to accept that vcpkg maintainers would willingly break projects to enforce a philosophy that is not something all users actually want or need to enforce. Yes, it makes sense for things in the default vcpkg registry. No, it doesn't make sense for all private registries.

**Comment by Thomas1664** [comment]
> In the real world, there are projects that simply can't (for a variety of valid reasons!) have all their dependencies supplied by vcpkg

Can you give some concrete examples where it isn't possible to use private registries?

**Comment by craigscott-crascit** [comment]
>> In the real world, there are projects that simply can't (for a variety of valid reasons!) have all their dependencies supplied by vcpkg

> Can you give some concrete examples where it isn't possible to use private registries?

I think you may be focusing on the wrong part of this issue, but I'll honour the question. But rather than picking specific technical examples and getting bogged down in discussions about those, I'll give a non-technical, more practical one. In large organisations with many teams, some of those teams may be unwilling to move their projects into a vcpkg registry and only be willing to provide them in some other form. This might be a temporary or permanent state. It can be due to lack of time, deadlines that need to take priority, lack of wanting to learn and maintain yet another software application, already supporting other packaging systems and don't want to support more, and the list goes on. In very large organisations, you have the added complication that you are very unlikely to be able to move all projects in one hit, so you will need to support a transitional period where only some projects might be available through a vcpkg registry (this is a situation I see in my consulting work). Regardless of whether it is possible to provide all dependencies through a vcpkg registry from a technical point of view, there are times when it isn't possible due to practical or behavioural constraints.

**Comment by Neumann-A** [comment]
- The idea behind setting `FETCHCONTENT_FULLY_DISCONNECTED` is to allow asset caching to work. To make asset caching work it is required that every download goes through vcpkg itself. Secondly setting `FETCHCONTENT_FULLY_DISCONNECTED` makes sure that ports are not incidentally vendoring their own dependencies. 

- Since there a ways to explicitly opt out of the default behavior vcpkg sets (via https://github.com/microsoft/vcpkg/issues/28386#issuecomment-1355371885 or https://github.com/microsoft/vcpkg/issues/28386#issuecomment-1355228524) I don't think this is really an issue.

- The CMake could look like:
```
cmake_minimum_required(VERSION 3.24)
include(StuffCoolProjectNeedsToFetch.cmake)
project(CoolProject)
do_standard_company_setup_things()
```
then the portfile.cmake can do: (requires that vcpkg setups a dependency provider which goes through vcpkgs download functions)
```
include(StuffCoolProjectNeedsToFetch.cmake)
<pass_required_folders_via_vcpkg_cmake_configure>
```
unless `FetchContent` doesn't work in script mode for some very strange reason

- In general, vcpkg does not checkout git submodules which is similar to the usage of `FetchContent` here

> because things might not be available as a straight archive download

it doesn't need to be an archive. Single files are also fine. 

> That option is intended for people who need to work offline, but who would still first need to be online to populate the dependencies initially

The docs explicitly state that the folders can be manually provided. So I don't see a reason to be online at all while running cmake.

**Comment by Thomas1664** [comment]
> Company projects may be more than happy to not have some things stored in the asset cache (and in some security-sensitive scenarios, might require that they not be cached). The choice should not be taken out of the hands of the maintainer of private registry ports.

There are ways to instruct [`vcpkg_download_distfile`](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_download_distfile.md) to not use asset caching.

**Comment by ras0219-msft** [comment]
> ... philosophically vcpkg would like all dependencies to be provided through vcpkg alone ...

As an aside, this is not strictly true. For example, we recently put out a blog post on how to use dependencies provided by the system (or another package manager) inside vcpkg[1], subject to some limitations.

However, we do intend to provide reliable and robust management for users that don't opt-in to advanced, less robust scenarios.

> The choice should not be taken out of the hands of the maintainer of private registry ports.

Agreed. As an immediate workaround, you can add `-DFETCHCONTENT_FULLY_DISCONNECTED=OFF` to `OPTIONS_RELEASE` and `OPTIONS_DEBUG` of the private port. In the future, we should support passing `-DFETCHCONTENT_FULLY_DISCONNECTED=OFF` directly to `OPTIONS` (though that does not work today).

You can also pin the version of `vcpkg-cmake` back to `2022-09-26` to revert this change, the same as you would pin back a major change in any other dependency:
```json
{
    "overrides": { "name": "vcpkg-cmake", "version": "2022-09-26" }
}
```

However, our current thought is that we still should continue to use `FETCHCONTENT_FULLY_DISCONNECTED=ON` as the default value in the future and to not allow any ports in the curated catalog to use the technique above (`OPTIONS -DFETCHCONTENT_FULLY_DISCONNECTED=OFF`).

[1]: https://devblogs.microsoft.com/cppblog/using-system-package-manager-dependencies-with-vcpkg/
