### ISSUE TITLE
[openssl] Build error

### ISSUE THREAD

**Issue by cbdj** [microsoft/vcpkg#28393]
**Host Environment**

- OS: Windows 11
- Compiler: MSVC 14.34.31933
- vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
- vcpkg-scripts version: f0a5a4515 2022-12-16
- 
**To Reproduce**

`.\vcpkg install openssl:x64-windows-static`

**Console output**
`Computing installation plan...
The following packages will be built and installed:
    openssl[core]:x64-windows-static -> 3.0.7#1
Detecting compiler hash for triplet x64-windows-static...
Installing 1/1 openssl:x64-windows-static...
Building openssl[core]:x64-windows-static...
-- Using cached openssl-openssl-openssl-3.0.7.tar.gz.
-- Cleaning sources at C:/Users/Clément/Desktop/workspace/vcpkg/buildtrees/openssl/src/nssl-3.0.7-96d825e305.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Clément/Desktop/workspace/vcpkg/downloads/openssl-openssl-openssl-3.0.7.tar.gz
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Using source at C:/Users/Clément/Desktop/workspace/vcpkg/buildtrees/openssl/src/nssl-3.0.7-96d825e305.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows-static
-- Getting CMake variables for x64-windows-static
-- Prerunning x64-windows-static-dbg
-- Building x64-windows-static-dbg
-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/nmake.exe" /NOLOGO /G /U /F makefile install_dev install_modules INSTALL_PDBS=OFF
    Working Directory: C:/Users/Clément/Desktop/workspace/vcpkg/buildtrees/openssl/x64-windows-static-dbg
    See logs for more information:
      C:\Users\Clément\Desktop\workspace\vcpkg\buildtrees\openssl\install-x64-windows-static-dbg-nmake-out.log
      C:\Users\Clément\Desktop\workspace\vcpkg\buildtrees\openssl\install-x64-windows-static-dbg-nmake-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_nmake.cmake:156 (vcpkg_execute_build_process)
  ports/openssl/windows/portfile.cmake:67 (vcpkg_build_nmake)
  ports/openssl/portfile.cmake:30 (include)
  scripts/ports.cmake:147 (include)`

**Content of C:\Users\Clément\Desktop\workspace\vcpkg\buildtrees\openssl\install-x64-windows-static-dbg-nmake-out.log**

	"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\Hostx64\x64\nmake.exe" /LU                 depend
	"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\Hostx64\x64\nmake.exe" /LU                 _build_libs
	"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\Hostx64\x64\cl.exe"  /Zi /Fdossl_static.pdb /MT /Zl /Gs0 /GF /Gy -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -MP  -D_DEBUG -MTd -Z7 -Ob0 -Od -RTC1 -I"." -I"include" -I"apps\include" -D"L_ENDIAN" -D"OPENSSL_PIC" -D"OPENSSLDIR=\"C:\\Users\\Clément\\Desktop\\workspace\\vcpkg\\packages\\openssl_x64-windows-static\\debug\"" -D"ENGINESDIR=\"C:\\Users\\Clément\\Desktop\\workspace\\vcpkg\\packages\\openssl_x64-windows-static\\debug\\lib\\engines-3\"" -D"MODULESDIR=\"C:\\Users\\Clément\\Desktop\\workspace\\vcpkg\\packages\\openssl_x64-windows-static\\debug\\bin\"" -D"OPENSSL_BUILDING_OPENSSL" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"DEBUG" -D"_DEBUG"   -c /Foapps\lib\libapps-lib-app_libctx.obj "apps\lib\app_libctx.c"
app_libctx.c
C:\Users\Clément\Desktop\workspace\vcpkg\buildtrees\openssl\x64-windows-static-dbg\include\openssl/macros.h(147): fatal error C1189: #error:  "OPENSSL_API_COMPAT expresses an impossible API compatibility level"

**Content of C:\Users\Clément\Desktop\workspace\vcpkg\buildtrees\openssl\install-x64-windows-static-dbg-nmake-out.log**

cl : Ligne de commande warning D9025 : substitution de '/MT' par '/MTd'
cl : Ligne de commande warning D9025 : substitution de '/Zi' par '/Z7'
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\Hostx64\x64\cl.exe"' : code retour '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\Hostx64\x64\nmake.exe"' : code retour '0x2'
Stop.

**Additional context**

I tried .\vcpkg install openssl:x64-windows and .\vcpkg install openssl:x86-windows-static, same problem

**Comment by FrankXie05** [comment]
Thanks for posting this issue.
Have you built this with Visual Studio 2015 or not?
I found this question on version 2015 https://github.com/Microsoft/vcpkg/issues/1689
BTW please install the latest windows SDK

**Comment by cbdj** [comment]
I built this with Visual Studio 2022.
Looks like the problem can be avoided by installing vcpkg in path without special character (the "Clément" in the path seems to be the culprit)

**Comment by Cheney-W** [comment]
I'm glad to know that you could built openssl successfully. Please try to avoid using special characters as part of the path.
