### ISSUE TITLE
The build of ffmpeg 5.1.2 will hang at linking avcodec

### ISSUE THREAD

**Issue by cnSchwarzer** [microsoft/vcpkg#28390]
The build of ffmpeg 5.1.2 will hang on triplet `x64-windows`, specifically, at linking `avcodec`.
This is an issue from a draft PR, and I don't know what caused the problem. Please help!

Update: I'm considering this an linker bug because the linker throws no error and hangs.
[MSVC Ticket](https://developercommunity.visualstudio.com/t/MSVC-Hangs-when-compiling-ffmpeg-When-l/10233953)
      
Update: 
- It probably caused by nasm. Because when I force x64 to use yasm it can be built without problem.
- It also build succeed if --disable-asm --disable-x86asm, so it should be related to assembly issue.
- It also build succeed if --enable-asm but --disable-x86asm.
- It failed if --disable-asm and --enable-x86asm by missing a symbol ff_tx_codelet_list_float_x86, so it should be related to x86 assembly issue.

Workarounds:
- Use `lld-link` as a preferred workaround.
- Fallback to `yasm` as a workaround.

**Comment by xiaozhuai** [comment]
Seems this PR #28387 block the CI...
See #28430 
```
Failure to remove_all_inside("D:\buildtrees") due to file "\\?\D:\buildtrees\ffmpeg": The process cannot access the file because it is being used by another process.
##[error]vcpkg clean failed
At C:\a\1\s\scripts\azure-pipelines\test-modified-ports.ps1:133 char:5
+     throw "vcpkg clean failed"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (vcpkg clean failed:String) [], RuntimeException
+ FullyQualifiedErrorId : vcpkg clean failed
##[error]PowerShell exited with code '1'.
```

**Comment by cnSchwarzer** [comment]
You are right, because this problem also stucks CI... Sorry for blocking, and I am not going to commit until I find a way to resolve the issue.

**Comment by cnSchwarzer** [comment]
It probably caused by nasm. Because when I force x64 to use yasm it can be built without problem.

**Comment by cnSchwarzer** [comment]
It also build succeed if `--disable-asm --disable-x86asm`, so it should be related to assembly issue.

**Comment by cnSchwarzer** [comment]
It also build succeed if `--enable-asm` but `--disable-x86asm`, 
It failed if `--disable-asm` and `--enable-x86asm` by missing a x86 symbol `ff_tx_codelet_list_float_x86`, so it should be related to x86 assembly issue.

**Comment by Sibras** [comment]
It does appear to be an issue the the microsoft linker and something being emitted by nasm. This may not be an issue with yasm as it is rather old and hasnt been updated in a while so it doesnt support newer instructions. So its possible that 1 or more of those newer instructions are causing issues for the linker. Using yasm isnt really a suitable fallback as its looses modern instruction support and has been deprecated by ffmpeg in favor of nasm.

The only main changes I know of between 5.0 and 5.1 were the removal of some old MMX code paths and the addition of avx512icl instructions. Disabling avx512icl though didnt fix the issue. So the only way to know which instructions are suddenly causing issues would be to step through and disable each asm file one by one until it links (something I dont have time to do).

Its also possible that its an issue with the flags that vcpkg is passing into ffmpeg as ffmpeg have msvc CI boxes (see ffmpegs [FATE](http://fate.ffmpeg.org/?query=cc:Microsoft%20%28R%29%20C%2FC%2B%2B%20Optimizing%20Compiler%20Version%2019.32.31332%20for%20x64%2F%2F)) that dont have this issue. I also have ffmpeg Visual Studio projects using nasm that dont have these issues either so it seems to be a vcpkg specific issue.
