### ISSUE TITLE
FAILED: src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_crop_layer.cu.obj 

### ISSUE THREAD

**Issue by JavierRuano** [Microsoft/vcpkg#2840]
Package: caffe:x64-windows
  Vcpkg version: 0.0.104-unknownhash

-- Build x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:129 (message):
    Command failed: C:/Users/LupinDefense/Caffe/vs2017/vcpkg/downloads/cmake-3.10.2-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: C:/Users/LupinDefense/Caffe/vs2017/vcpkg/buildtrees/caffe/x64-windows-dbg
    See logs for more information:
      C:\Users\LupinDefense\Caffe\vs2017\vcpkg\buildtrees\caffe\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/caffe/portfile.cmake:59 (vcpkg_install_cmake)
  scripts/ports.cmake:72 (include)

[install-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/1738139/install-x64-windows-dbg-out.log)

Regards

**Comment by themikem** [comment]
Likely related to this one: https://github.com/Microsoft/vcpkg/issues/2814

**Comment by LupinDefense** [comment]
Is it possible generate cmake configuration of another form?
Ninja caffe.lib, it is not prerequisites problem, isn't it?

**Comment by LupinDefense** [comment]
The issue CUDA 9.0 compilation issues #2814

It's different because the solution of that issue vcpkg has it, and the
trick doesn't work.
With CUDA 8.0 vcpkg requires CUDA 9.0.

About this solution:
    Error generating XXXXX.cu.obj: This might occurred when the package
source haven't implemented VS2017 support, since the compiler path is
changed from VS2015 to VS2017.

Regards

**Comment by LarryIII** [comment]
@JavierRuano Thanks for your report! VCPKG did not have the port 'caffe' here, just have a 'caffe2' port here. Did you try to build the new port 'caffe' and block by this issue? If yes, could you please submit a PR that we can test it and diagnose it. Thank you!
