### ISSUE TITLE
[Yoga] Tries to link android.lib when building with cmake on Windows.

### ISSUE THREAD

**Issue by lconn-dev** [microsoft/vcpkg#28416]
Building a blank project with Visual Studio 2022, x64-windows triplet. "fatal error LNK1104: cannot open file 'android.lib'".

**Proposed solution**
I believe the patch file "/ports/yoga/Export-unofficial-yoga-config.patch" should be modified and "target_link_libraries(yogacore android log)" should be removed or revised.
[CMakeLists.txt](https://github.com/microsoft/vcpkg/files/10253190/CMakeLists.txt)

**Comment by dg0yt** [comment]
Fixed upstream 2 months ago as part of https://github.com/facebook/yoga/pull/1129.

**Comment by Cheney-W** [comment]
Solved by https://github.com/microsoft/vcpkg/pull/29666
