### ISSUE TITLE
Building Blaze Fails

### ISSUE THREAD

**Issue by justwagle** [Microsoft/vcpkg#2841]
Building blaze fails with hash mismatch. 
  Package: blaze:x64-windows
  Vcpkg version: 0.0.104-2018-02-17-d4004c8ac9cd2c9df58495ed7e06566ed85a32d6
Log: https://gist.github.com/justwagle/1f469ad5af259f5ca087fbf16d57ae7e

**Comment by ras0219-msft** [comment]
Thanks for letting us know! I've replicated the issue and pushed an updated SHA to master. Please pull and try again!
