### ISSUE TITLE
HostX86 Toolchain used on X64 host

### ISSUE THREAD

**Issue by themikem** [microsoft/vcpkg#2842]
Using Windows 10 (1709 / 16299 ) x64, VS2017 & latest vcpkg pulled from Git
Have built a number of pacakges, but currently working through OpenCV issues.

However, I've noticed in the build logs that the system is running the Hostx86 toolchain instead of the Hostx64 chain.  In other words, on a 64-bit machine, I would expect to use the Hostx64 chain, and on a 32-bit machine, to use the Hostx86 chain.  For example, 
`ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.12.25827\bin\HostX86\x64\CL.exe`

I also notice that x86 is hardcoded on the vcpkg bootstrap script... 
`$arguments = (
"`"/p:VCPKG_VERSION=-$gitHash`"",
"`"/p:DISABLE_METRICS=$disableMetrics`"",
"/p:Configuration=Release",
"/p:Platform=x86",
"/p:PlatformToolset=$platformToolset",
"/p:TargetPlatformVersion=$windowsSDK",
"/m",
"`"$vcpkgSourcesPath\dirs.proj`"") -join " "`

This isn't what I would expect, but perhaps I'm wrong in expecting x64 for platform (vs target platform...)?  Is this an issue, by design, or none of the above?

**Comment by cenit** [comment]
When using MSBuild, to produce x64 builds it is preferred the crosscompilation from a compiler which runs on x86 (hostx86 --> x64, note the path).
While using Ninja, on the other hands, to produce x64 builds it is preferred the native compilation which runs on x64 (hostx64 --> x64).
In both case the executable is a 64 bit one and works perfectly. In the MSVC toolchain there are many more compilers and crosscompilers (x86->x86, x64->x86, x86->ARM, ...)

**Comment by MikeGitb** [comment]
Out of interest: Is there any reason to prefer the x86 hosted toolchain?

**Comment by cenit** [comment]
VS itself is an x86 executable. maybe [some decisions behind](https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/2255687-make-vs-scalable-by-switching-to-64-bit) can apply here too

**Comment by ras0219-msft** [comment]
The x86 hosted toolchain uses 32-bit pointers internally (obviously) which, since the internal data structures of compilers have a lot of pointers, can result in nearly half as much RAM used. Additionally, when PCHs are involved, the PCH file itself can be much smaller, which can result in real build throughput improvements.

However, there are obviously a lot of benefits for 64-bit as well. Overall, we'd prefer to use the x64 tools on x64 hosts. The discrepancy here isn't by design, it's just a lower priority issue compared to processing PRs, responding to issues, and other improvements in the tool :)

**Comment by themikem** [comment]
Interesting.  Wasn't expecting such a mixed answer.

@cenit So then it would seem the ideal case would be to set the host preference based on both the host platform and the build tool chosen, rather than just the host platform alone, correct?

@ras0219-msft I have already written code which does set the overall preference to x64 hosts when running on an x64 architecture.  I thought I was having some issues with the hostx86 side on x64, so I wrote the code to get around it.  Turns out that was just a mask of some other problems, but the code is still there...

So, what do you all think: is a global x64 preference is worth a PR now, or should we look at doing what @cenit suggests first and implement a per-build-system preference?

**Comment by NancyLi1013** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.

**Comment by MikeGitb** [comment]
Seems to be fixed. @themikem: Can you confirm?
