### ISSUE TITLE
[vcpkg] How do I force remove a package ignore dependencies

### ISSUE THREAD

**Issue by xiaozhuai** [microsoft/vcpkg#28438]
How do I force remove a package ignore dependencies?
I tried `vcpkg remove -f` with no luck.
I had to remove all downstream packages at the same time.
Suppose I change a little bit code of a port, then I need rebuild all downstream packages even that I'm pretty sure it won't break downstream packages.

**Comment by Osyotr** [comment]
Not possible.
If you build vcpkg yourself you might want to grab this https://github.com/microsoft/vcpkg-tool/pull/816

**Comment by lili2012** [comment]
You could delete file: {yourVcpkgFolder}/installed/vcpkg/status This file records vcpkg installed package dependency. Then you install you modified package or port
