### ISSUE TITLE
[OpenCV] Looking for installed/include/libpng/, but installed contains include/libpng16 only

### ISSUE THREAD

**Issue by themikem** [Microsoft/vcpkg#2843]
On Windows 10 (1709 / 16299), VS2017, latest vcpkg from git - 
Building OpenCV x64-windows - I have repeatedly observed an error where includes are looking for libpng/libpng.h, but the files are located in libpng16 after the libpng package is built. 

For example,
`D:\vcpkg\buildtrees\opencv\x64-windows-v140-dbg\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'D:/vcpkg/installed/x64-windows-v140/include/libpng/png.h': No such file or directory [D:\vcpkg\buildtrees\opencv\x64-windows-v140-dbg\CMakeFiles\CMakeTmp\cmTC_cd014.vcxproj]`

I can solve this by manually copying libpng16 to just installed/include/libpng, but a more permanent fix would be preferred...

**Comment by cenit** [comment]
it's not a problem for OpenCV. Inside the building scripts, it looks for that header first, but if not it looks into another position, which is the one used by vcpkg, and it succeeds!

**Comment by JackBoosY** [comment]
Hi @themikem  @cenit , this bug has been fixed, plz update vcpkg and reinstall opencv with command:
`vcpkg remove opencv`
`vcpkg install opencv[png]:x64-windows`
Thx.

**Comment by JackBoosY** [comment]
Hi @themikem , thanks for reporting this issue!
I cannot repro on my WM, do you?
Please open a new issue if this is still a problem for you.
Thx.

**Comment by peererror** [comment]
+1 having same issue

**Comment by JackBoosY** [comment]
@peererror please open an new issue.
Thanks.

**Comment by guybashan** [comment]
Having the same issue..
