### ISSUE TITLE
Why CI can find clang when building ffmpeg while I cannot find in my own PC

### ISSUE THREAD

**Issue by cnSchwarzer** [microsoft/vcpkg#28431]
I have clang installed in my computer and added to PATH, accessible from console
![image](https://user-images.githubusercontent.com/29846655/208354317-99a1ee71-b237-4f7b-b974-cc37c474a258.png)

However when I build ffmpeg on my own computer, it failed to find clang. So it automatically disabled some feature.
But when the ci pipeline build ffmpeg, it can find clang and result in different building behaviour.
Our parameters are same:
```
ffmpeg[amf,aom,ass,avcodec,avdevice,avfilter,avformat,avisynthplus,avresample,bzip2,core,fdk-aac,fontconfig,freetype,fribidi,gpl,iconv,ilbc,lzma,modplug,mp3lame,nonfree,nvcodec,opencl,opengl,openh264,openjpeg,openssl,opus,postproc,sdl2,snappy,soxr,speex,srt,ssh,swresample,swscale,tesseract,theora,vorbis,vpx,webp,x264,x265,xml2,zlib]:x86-windows
```

I have to explicitly set --nvcc=<Full Path To Clang> to make the build behaviour same as the ci, so I think there's some difference between azure and me about finding clang?

**Comment by cnSchwarzer** [comment]
Some context: I'm building ffmpeg 5.1.2 and propably 4.4.3 won't have this issue? As this problem seems occurs in 5.1.2 only.
But it still doesn't explain why CI can find clang though.

**Comment by Neumann-A** [comment]
Windows CI has LLVM from VS installed and it will be put on PATH by vcvars.

**Comment by cnSchwarzer** [comment]
OK, so this is a port bug.
