### ISSUE TITLE
[LLVM] How do I get the kaleidoscope example running?

### ISSUE THREAD

**Issue by DietmarSchulz** [microsoft/vcpkg#28445]
Chapter 4 of that LLVM tutorial https://llvm.org/docs/tutorial/MyFirstLanguageFrontend/LangImpl04.html doesn't work since InitializeNativeTarget does not support any target.
Requested triple: x86_64-pc-windows-msvc

  Registered Targets:
    (none)
Original source in https://github.com/llvm/llvm-project/tree/main/llvm/examples/Kaleidoscope/Chapter4 and https://github.com/llvm/llvm-project/tree/main/llvm/examples/Kaleidoscope/include

I'm using VS2022 with vcpkg and installed 
llvm                     14.0.4           The LLVM Compiler Infrastructure.
with default configuration

llc.exe --version 
shows:

LLVM (http://llvm.org/):
  LLVM version 14.0.4
  Optimized build.
  Default target: x86_64-pc-windows-msvc
  Host CPU: skylake

  Registered Targets:
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64

What do I miss?

**Comment by DietmarSchulz** [comment]
The kaleidoscope examples in the build tree work, but only if I open the whole llvm folder with visual studio, ..\vcpkg_llvm\buildtrees\llvm\src\org-14.0.4-df58f01928.clean\llvm in my case, and build in cmake targets view.

So, what is the difference?
How do I get a vcxproj for a single source file?
Usually cmake provides that, but in this case I found none. VS just compiles to exe targets in ...\vcpkg_llvm\buildtrees\llvm\src\org-14.0.4-df58f01928.clean\llvm\out\build\x64-Debug\bin

**Comment by Cheney-W** [comment]
Add `WINDOWS_USE_MSBUILD` option into the `vcpkg_cmake_configure()` function of `\vcpkg\ports\llvm\portfile.cmake`,
```
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}/llvm"
    WINDOWS_USE_MSBUILD
    OPTIONS
```
try to install `llvm` by vcpkg, after the config step, manually stop the install command, then you could find the `vcxproj` file in `\vcpkg\buildtrees\llvm\x64-windows-dbg` folder.
