### ISSUE TITLE
[libyuv] No avx/sse/etc... feature support on MSVC build

### ISSUE THREAD

**Issue by cnSchwarzer** [microsoft/vcpkg#28446]
Workaround:

vcpkg team refuses to mix compilers #29032, so if you want to enable these accelerations using `clang-cl` to compile `libyuv`, while don't want to switch to a custom triplet (keep using `x64-windows`) and continue to compile everything else use `MSVC`:
1. Fork vcpkg and use your repo as a registry
2. Edit `libyuv` portfile with https://gist.github.com/cnSchwarzer/751f0d3aa777ebd547ade912e33ca93f

Otherwise, you can use a custom community `clang-cl` triplet.

------

**Describe the bug**
Libyuv compiled by vcpkg does not enable advanced instructions optimizations under debug build (probably also release build, unable to breakpoint there)

**Environment**
- OS: Windows 11
- Compiler: Latest MSVC

**To Reproduce**
1. ./vcpkg install libyuv
4. Debug into any libyuv copy function and step into it. It jumped over all optimized instructions.

**Expected behavior**
The library should use best advanced instruction (avx,sse,qmemcpy) on debug build, as it makes no sense to disable it.
Moreover, the port should provide features to make user enable avx512, etc.

**Comment by Neumann-A** [comment]
arch dependent stuff needs to be toogled by the triplet/toolchain unless the library does a proper runtime detection of cpu functionality. SSE could probably be activated for x64 however.

**Comment by cnSchwarzer** [comment]
It does runtime cpuid detection, but some macro is not defined unless use clang. From this aspect we can see there's no point to stick with MSVC
