### ISSUE TITLE
Cannot install on Ubuntu - certificate issue

### ISSUE THREAD

**Issue by deroskarmodulo** [microsoft/vcpkg#28441]
**Describe the bug**

I tried to install vcpkg on my Ubuntu WSL. However ./bootstrap-vcpkg.sh results in

Downloading vcpkg-glibc...
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
How do I fix this?

(There have been some similar discussions, however I could not make head nor tail of them.)

**Environment**
- OS: Ubuntu 20.04.3 LTS

**Comment by FrankXie05** [comment]
Please check the URL: https://curl.se/docs/sslcerts.html and complete the `ssl` certificate verification.

**Comment by FrankXie05** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
