### ISSUE TITLE
[qtdeclarative] Build error

### ISSUE THREAD

**Issue by mknigh23** [microsoft/vcpkg#28451]
**Host Environment**

- OS: Windows
- Compiler: VS2022

**To Reproduce**

`./vcpkg install qt:x64-windows`

**Failure logs**
`Installing 38/41 qtwebengine:x64-windows...`
`Building qtwebengine[core,default-features,geolocation,spellchecker,webchannel]:x64-windows...`
`-- Setting up python virtual environmnent...`
`-- Installing python packages: html5lib`
`-- Setting up python virtual environmnent...finished.`
`CMake Warning at ports/qtwebengine/portfile.cmake:85 (message):`
  `Buildtree path 'C:/dev/vcpkg/buildtrees/qtwebengine' is too long.`

  `Consider passing --x-buildtrees-root=<shortpath> to vcpkg!`

  `Trying to use 'C:/dev/vcpkg/buildtrees/qtwebengine/../tmp'`
`Call Stack (most recent call first):`
  `scripts/ports.cmake:147 (include)`

`CMake Error at ports/qtwebengine/portfile.cmake:90 (message):`
  `Buildtree path is too long.  Build will fail! Pass`
  `--x-buildtrees-root=<shortpath> to vcpkg`
`Call Stack (most recent call first):`
  `scripts/ports.cmake:147 (include)`

`error: building qtwebengine:x64-windows failed with: BUILD_FAILED`
`error: Please ensure you're using the latest port files with 'git pull' and 'vcpkg update'.`
`Then check for known issues at:`
    `https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qtwebengine`
`You can submit a new issue at:`
    `https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[qtwebengine]+Build+error`
`Include '[qtwebengine] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.`
    `vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba`
    `vcpkg-scripts version: 30a20e8f1 2022-12-07 (11 days ago).`
`- Attach ***every failure log file*** mentioned in the console output.`

*The console output by itself is not enough to investigate a build failure.*
*Some hint to where the log files are located would help... VCPKG creates a **LOT** of files!*

**Additional context**

The command was run from the 'x64 Native Tools Command Prompt for VS 2022'. It failed on two (2) separate machines. `git pull` and `vcpkg update` had been run previously with zero changes, as it is a brand shiny new install on new laptops.

[stdout-x64-windows.log](https://github.com/microsoft/vcpkg/files/10263380/stdout-x64-windows.log)
[pip-install-virtualenv-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/10263399/pip-install-virtualenv-x64-windows-out.log)
[pip-install-packages-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/10263400/pip-install-packages-x64-windows-out.log)

**Comment by Neumann-A** [comment]
```
CMake Error at ports/qtwebengine/portfile.cmake:90 (message):
Buildtree path is too long.  Build will fail! Pass
--x-buildtrees-root=<shortpath> to vcpkg
```

It exactly tells you what the issue is.

**Comment by mknigh23** [comment]
Hi Alexander,

How short must it be? My path is C:\dev\vcpkg, 12 characters if you include the drive specification. To use the command line option, I’m assuming my install command would be…

C:\dev\vcpkg> .\vcpkg install qt:x64-windows --x-buildtrees-root=C:\dev\vcpkg

…or would I need to specify the actual buildtrees folder…

C:\dev\vcpkg> .\vcpkg install qt:x64-windows --x-buildtrees-root=C:\dev\vcpkg\buildtrees

…or just the qtwebengine?

C:\dev\vcpkg> .\vcpkg install qtwebengine:x64-windows --x-buildtrees-root=C:\dev\vcpkg\buildtrees

Your help in this matter is greatly appreciated, as vcpkg is all new to me.

Kind regards,

Micheal

**Comment by mknigh23** [comment]
Hi Alexander,

The first option worked for the qtwebengine; thank you.

However, if I try this with the second option to ensure the qt install is complete, I got (a) a page size error on one laptop (4GB page size on this laptop and 16GB on the other), and (b) both laptops now crash when I run the second command, with 16GB page sizes. No error log is produced… the laptops simply choke, then reboot!

One final question… do I need to maintain the C:\b folder, and if so, could you briefly explain why?

Regards,

Micheal

**Comment by Neumann-A** [comment]
>  do I need to maintain the C:\b folder, and if so, could you briefly explain why?

No the build folder is only required for building. After that you can delete it. There is also the option `--clean-after-build`

 ```
 --clean-after-build             Clean buildtrees, packages and downloads after building each
                                  package
  --clean-buildtrees-after-build  Clean buildtrees after building each package
  --clean-packages-after-build    Clean packages after building each package
  --clean-downloads-after-build   Clean downloads after building each package
```

> I got (a) a page size error on one laptop (4GB page size on this laptop and 16GB on the other), and (b) both laptops now crash when I run the second command, with 16GB page sizes.

I wouldn't try to build qtwebengine on a laptop. From the errors you describe I would assume you are running in a hefty RAM deficit and running a pagefile is not enough in this case.

**Comment by mknigh23** [comment]
Hi Alexander,

I have no interest in the qtwebengine and would be happy to build qt without it, but building Qt using .\vcpkg install qt:x64-windows always includes it. How do I omit it from the build, if I don’t know what other packages are required?

Regards,

Micheal

**Comment by Neumann-A** [comment]
> How do I omit it from the build, if I don’t know what other packages are required?

You should know which parts of Qt you are using. In general you should be able to infer that from the Qt classes/functionality you are using. Maybe just qtbase[gui,widgets] is already enough if you don't use qml stuff or need qtimageformts as a plugin.

**Comment by JonLiu1993** [comment]
@mknigh23, Did @Neumann-A 's answer help you solve this problem?

**Comment by JonLiu1993** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
