### ISSUE TITLE
Error in authorizing for installing vcpkg

### ISSUE THREAD

**Issue by Sahab-Mohamed** [microsoft/vcpkg#28453]
When I type:  git clone https://github.com/Microsoft/vcpkg.git
In VS terminal it asks me to select an authorization method from three methods
Whatever the method I choose, it result : Repository not found.

I use Visual Studio 2022
And it should install vcpkg

**Failure logs**
-(please attached failure logs)

**Additional context**

**Comment by FrankXie05** [comment]
@Sahab-Mohamed 
Please provide the error log. :)
1. Make sure your local git account is configured
2. You can try to use `powershell` to re-clone in the root directory and try again.

**Comment by dg0yt** [comment]
AFAICT authorization is not needed to clone the public repo via https. However, sometimes I had a similar problem when copy-and-paste from the GH web page to the command line inserted some invisible (!) characters.

**Comment by FrankXie05** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
