### ISSUE TITLE
Error: Building package zlib:x86-windows failed with: BUILD_FAILED 

### ISSUE THREAD

**Issue by dtamade** [Microsoft/vcpkg#2845]
how to do.
vs2015

**Comment by ras0219-msft** [comment]
Hi @dtamade, could you please post the log files for the failure? They should have displayed in the error message, something like "config-x86-windows-out.log"

**Comment by dtamade** [comment]
I think vcpkg should optimize the script for each platform. This is a problem that uses the platform related header files.

**Comment by miurahr** [comment]
It can be a same problem with https://github.com/Microsoft/vcpkg/issues/3122

**Comment by JackBoosY** [comment]
Hi @dtamade , thanks for reporting this issue.
Please open a new issue if this is still a problem for you.
Thx.
