### ISSUE TITLE
bootstrap-vcpkg.sh build failure

### ISSUE THREAD

**Issue by Dav00Arm** [microsoft/vcpkg#28461]
I want to install vcpkg on jetson nano (Ubuntu 18.04)

git clone https://github.com/microsoft/vcpkg

Clones everything correctly, then

./vcpkg/bootstrap-vcpkg.sh

The error I get

Unable to determine a binary release of vcpkg; attempting to build from source.
Downloading vcpkg tool sources
Building vcpkg-tool...
-- The CXX compiler identification is GNU 7.5.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting the C++ compiler in use
-- Detecting the C++ compiler in use - gcc
-- Module support is disabled.
-- Version: 9.1.0
-- Build type: Release
-- CXX_STANDARD: 17
-- Performing Test has_std_17_flag
-- Performing Test has_std_17_flag - Success
-- Performing Test has_std_1z_flag
-- Performing Test has_std_1z_flag - Success
-- Required features: cxx_variadic_templates
-- The C compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test CPP_ATOMIC_BUILTIN
-- Performing Test CPP_ATOMIC_BUILTIN - Success
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/ALPR_Cpp/vcpkg/buildtrees/_vcpkg/build
[0/2] Re-checking globbed directories...
[42/191] Building CXX object CMakeFile...glib.dir/src/vcpkg/binarycaching.cpp.o
FAILED: CMakeFiles/vcpkglib.dir/src/vcpkg/binarycaching.cpp.o 
/usr/bin/c++ -DVCPKG_BASE_VERSION=2999-12-31 -DVCPKG_VERSION=unknownhash -I/mnt/ALPR_Cpp/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2022-12-14/include -I_deps/fmt-src/include -I_cmrc/include -O3 -DNDEBUG -include /mnt/ALPR_Cpp/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2022-12-14/include/pch.h -pthread -std=c++1z -MD -MT CMakeFiles/vcpkglib.dir/src/vcpkg/binarycaching.cpp.o -MF CMakeFiles/vcpkglib.dir/src/vcpkg/binarycaching.cpp.o.d -o CMakeFiles/vcpkglib.dir/src/vcpkg/binarycaching.cpp.o -c /mnt/ALPR_Cpp/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2022-12-14/src/vcpkg/binarycaching.cpp
In file included from /usr/include/c++/7/bits/stl_tempbuf.h:60:0,
                 from /usr/include/c++/7/bits/stl_algo.h:62,
                 from /usr/include/c++/7/algorithm:62,
                 from /mnt/ALPR_Cpp/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2022-12-14/include/pch.h:25,
                 from <command-line>:0:
/usr/include/c++/7/bits/stl_construct.h: In instantiation of ‘void std::_Construct(_T1*, _Args&& ...) [with _T1 = std::unique_ptr<vcpkg::IBinaryProvider>; _Args = {const std::unique_ptr<vcpkg::IBinaryProvider, std::default_delete<vcpkg::IBinaryProvider> >&}]’:
/usr/include/c++/7/bits/stl_uninitialized.h:83:18:   required from ‘static _ForwardIterator std::__uninitialized_copy<_TrivialValueTypes>::__uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = __gnu_cxx::__normal_iterator<const std::unique_ptr<vcpkg::IBinaryProvider>*, std::vector<std::unique_ptr<vcpkg::IBinaryProvider> > >; _ForwardIterator = std::unique_ptr<vcpkg::IBinaryProvider>*; bool _TrivialValueTypes = false]’
/usr/include/c++/7/bits/stl_uninitialized.h:134:15:   required from ‘_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = __gnu_cxx::__normal_iterator<const std::unique_ptr<vcpkg::IBinaryProvider>*, std::vector<std::unique_ptr<vcpkg::IBinaryProvider> > >; _ForwardIterator = std::unique_ptr<vcpkg::IBinaryProvider>*]’
/usr/include/c++/7/bits/stl_uninitialized.h:289:37:   required from ‘_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = __gnu_cxx::__normal_iterator<const std::unique_ptr<vcpkg::IBinaryProvider>*, std::vector<std::unique_ptr<vcpkg::IBinaryProvider> > >; _ForwardIterator = std::unique_ptr<vcpkg::IBinaryProvider>*; _Tp = std::unique_ptr<vcpkg::IBinaryProvider>]’
/usr/include/c++/7/bits/stl_vector.h:331:31:   required from ‘std::vector<_Tp, _Alloc>::vector(const std::vector<_Tp, _Alloc>&) [with _Tp = std::unique_ptr<vcpkg::IBinaryProvider>; _Alloc = std::allocator<std::unique_ptr<vcpkg::IBinaryProvider> >]’
/mnt/ALPR_Cpp/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2022-12-14/include/vcpkg/base/expected.h:42:57:   required from ‘vcpkg::ExpectedHolder<T>::ExpectedHolder(Fwd&&) [with Fwd = std::vector<std::unique_ptr<vcpkg::IBinaryProvider> >&; typename std::enable_if<(! is_same_v<vcpkg::ExpectedHolder<T>, typename std::remove_cv<typename std::remove_reference<_SrcTuple>::type>::type>), int>::type <anonymous> = 0; T = std::vector<std::unique_ptr<vcpkg::IBinaryProvider> >]’
/mnt/ALPR_Cpp/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2022-12-14/include/vcpkg/base/expected.h:77:85:   required from ‘vcpkg::ExpectedT<T, Error>::ExpectedT(ConvToT&&) [with ConvToT = std::vector<std::unique_ptr<vcpkg::IBinaryProvider> >&; typename std::enable_if<(is_convertible_v<ConvToT, T> && (! is_same_v<typename std::remove_reference<_SrcTuple>::type, Error>)), int>::type <anonymous> = 0; T = std::vector<std::unique_ptr<vcpkg::IBinaryProvider> >; Error = std::__cxx11::basic_string<char>]’
/mnt/ALPR_Cpp/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2022-12-14/src/vcpkg/binarycaching.cpp:2312:12:   required from here
/usr/include/c++/7/bits/stl_construct.h:75:7: error: use of deleted function ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = vcpkg::IBinaryProvider; _Dp = std::default_delete<vcpkg::IBinaryProvider>]’
     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/7/memory:80:0,
                 from /mnt/ALPR_Cpp/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2022-12-14/include/pch.h:35,
                 from <command-line>:0:
/usr/include/c++/7/bits/unique_ptr.h:383:7: note: declared here
       unique_ptr(const unique_ptr&) = delete;
       ^~~~~~~~~~
[47/191] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/build.cpp.o
ninja: build stopped: subcommand failed.

ninja version I have installed 1.8.2

I have tried to reinstall ninja and tried to use --useSystemBinaries flag recommended [here](https://github.com/microsoft/vcpkg/issues/10955#issuecomment-617886569)

./bootstrap-vcpkg.sh --useSystemBinaries

but it said

Warning: -useSystemBinaries no longer has any effect; ignored. Note that the VCPKG_USE_SYSTEM_BINARIES environment variable behavior is not changed.

then continued the above process.

Please help to solve this problem.

If you need an additional information, just tell me.

**Comment by rinechran** [comment]
i wonder what the gcc version is

**Comment by Osyotr** [comment]
https://github.com/microsoft/vcpkg-tool/blob/ab767114e03632f020cf05e90e266a8db377f1c9/src/vcpkg/binarycaching.cpp#L2312
@BillyONeal IIUC, this code relies on NRVO which this particular compiler did not implement, so an explicit move is required.
https://godbolt.org/z/ddq4abK47

**Comment by Dav00Arm** [comment]
> Which version of gcc do you use?

gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by Dav00Arm** [comment]
> 

What do I need to do here?

**Comment by Osyotr** [comment]
> What do I need to do here?

Why do you even build vcpkg from source? Try running `./bootstrap-vcpkg.sh` directly from vcpkg directory.
If you absolutely sure you need to build vcpkg from source, see my previous post (e.g. patch sources). Don't forget to submit patch to vcpkg-tool repo.

**Comment by BillyONeal** [comment]
> https://github.com/microsoft/vcpkg-tool/blob/ab767114e03632f020cf05e90e266a8db377f1c9/src/vcpkg/binarycaching.cpp#L2312 @BillyONeal IIUC, this code relies on NRVO which this particular compiler did not implement, so an explicit move is required. https://godbolt.org/z/ddq4abK47

This is not NRVO: the return type and the returned value's type aren't the same, so there's a materialized temporary. The standard *allows* eliminating the *move* operation here, but returning an expression referencing a variable with automatic storage duration invokes a move. But GCC 7.5 has some form of bug where it tries to copy instead. I'm linking several examples here because this wording has changed a lot between versions of C++:

* In C++14: https://timsong-cpp.github.io/cppwp/n4140/class.copy#32  
  Note "id-expression that names an object with automatic storage duration declared in the body"
* In C++17: https://timsong-cpp.github.io/cppwp/n4659/class.copy#elision-3
* In C++20: https://timsong-cpp.github.io/cppwp/n4868/class#copy.elision-3

The C++23 will clarify this wording a bit: https://www.open-std.org/JTC1/SC22/WG21/docs/papers/2022/p2266r3.html

I don't know exactly what conditions trigger the bug; the unfortunate thing is that adding an explicit `std::move` here can pessimize all current compilers. We would be more than willing to accept that pessimization; performance doesn't matter here. The bigger problem is that GCC 7.5 is not one of our production targeted compilers, so any fix is going to rot fast as we are not testing it.

> > What do I need to do here?
> 
> Why do you even build vcpkg from source? Try running `./bootstrap-vcpkg.sh` directly from vcpkg directory. If you absolutely sure you need to build vcpkg from source, see my previous post (e.g. patch sources). Don't forget to submit patch to vcpkg-tool repo.

I believe:

>jetson nano

means arm-linux for which we do not have a prebuilt binary. We would be happy to provide such a prebuilt binary but don't have a great understanding of how to produce one that has a high likelihood of running on any given arm linux system. We produce the amd64 Linux binaries today by building on an extremely old copy of RHEL that supports GCC9 targeting ancient copies of glibc et al.

**Comment by Osyotr** [comment]
> We produce the amd64 Linux binaries today by building on an extremely old copy of RHEL that supports GCC9 targeting ancient copies of glibc et al.

Does it have Clang which can build vcpkg? The solution might be as easy as cross-compiling vcpkg and linking everything statically except `glibc`.

> We would be happy to provide such a prebuilt binary but don't have a great understanding of how to produce one that has a high likelihood of running on any given arm linux system.

There is one trick to make an executable portable, but it requires you to:
1) Build `libc++`, `libc++abi`, `libunwind` from sources together with vcpkg
2) Use fixed (old) version of standard C libraries (`pthread`, `m`, `dl`, etc.)

There is at least one vendor who does that quite successfully: https://github.com/ClickHouse/ClickHouse/tree/master/cmake/linux

**Comment by BillyONeal** [comment]
> Does it have Clang which can build vcpkg?

No.

> The solution might be as easy as cross-compiling vcpkg and linking everything statically except glibc.

The glibc version itself is a source of incompatibilities, hence the old Linux version.

> There is at least one vendor who does that quite successfully:

The question isn't whether it is possible, the question is can we get enough confidence in it to replace building from source as something we have confidence will work. With nothing to test with we do not have that confidence.

**Comment by Osyotr** [comment]
> The question isn't whether it is possible, the question is can we get enough confidence in it to replace building from source as something we have confidence will work. With nothing to test with we do not have that confidence.

Adding a check for glibc version into `bootstrap-vcpkg.sh` may boost one's confidence ;)

**Comment by Dav00Arm** [comment]
I needed curl and jsoncpp from vcpkg, so while waiting for your response I installed them separately from different sources. I'm trying to find links to share with you, will share when i find them. Now closing the issue. Thank you all ))).

**Comment by BillyONeal** [comment]
I created https://github.com/microsoft/vcpkg/issues/28570 to track the 'meta issue' here so that @Dav00Arm can avoid getting spammed with notifications.

**Comment by eladm-ultrawis** [comment]
In case someone is still looking for a workaround, if you upgrade the gcc / g++ version to 8 and set it as the system default, it works. I managed to install vcpkg on Jetson Nano.

```
sudo apt install -y g++-8 gcc-8
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-8
sudo update-alternatives --config gcc
```
