### ISSUE TITLE
  Package: liblzma:x64-windows   Vcpkg version: 0.0.89-unknownhash

### ISSUE THREAD

**Issue by ekfwndls** [Microsoft/vcpkg#2846]
Package: liblzma:x64-windows
  Vcpkg version: 0.0.89-unknownhash

**Comment by ras0219-msft** [comment]
Hi @ekfwndls, could you please post the log files for the failure? They should have displayed in the error message, something like "config-x86-windows-out.log"

**Comment by glachancecmaisonneuve** [comment]
When sourcegorge is in disaster mode downloads are redirected to a 652 byte html message that says that the site is down.  if you hash that 652 byte file, you get 3b53ccf0243cd4a6a731a898bfdba95c3d22342e7e64f9e9a4a2bce5f74ac809943f570ed92c9077101a178f82f49ece1d1c4bfee1f288ea61d99fb36f6a243e.


Closes https://github.com/Microsoft/vcpkg/issues/1881
Closes https://github.com/Microsoft/vcpkg/issues/1878
Closes https://github.com/Microsoft/vcpkg/issues/2871

**Comment by JackBoosY** [comment]
Hi @ekfwndls , liblzma had switch sources to github mirror. This question will not happen again.

**Comment by JackBoosY** [comment]
Please open a new issue if this is still a problem for you.
Thx.
