### ISSUE TITLE
[vcpkg] owns doesn't seem to be working properly

### ISSUE THREAD

**Issue by xiaozhuai** [microsoft/vcpkg#28464]
**Describe the bug**
```
$ vcpkg owns qt5-base
qt5-base:x64-osx: x64-osx/share/qt5-base/copyright
qt5-base:x64-osx: x64-osx/share/qt5-base/vcpkg.spdx.json
qt5-base:x64-osx: x64-osx/share/qt5-base/vcpkg_abi_info.txt
qt5-base:x64-osx: x64-osx/tools/qt5-base/bin/fixqt4headers.pl
qt5-base:x64-osx: x64-osx/tools/qt5-base/bin/moc
qt5-base:x64-osx: x64-osx/tools/qt5-base/bin/qdbuscpp2xml
qt5-base:x64-osx: x64-osx/tools/qt5-base/bin/qdbusxml2cpp
qt5-base:x64-osx: x64-osx/tools/qt5-base/bin/qlalr
qt5-base:x64-osx: x64-osx/tools/qt5-base/bin/qmake
qt5-base:x64-osx: x64-osx/tools/qt5-base/bin/qvkgen
qt5-base:x64-osx: x64-osx/tools/qt5-base/bin/rcc
qt5-base:x64-osx: x64-osx/tools/qt5-base/bin/syncqt.pl
qt5-base:x64-osx: x64-osx/tools/qt5-base/bin/tracegen
qt5-base:x64-osx: x64-osx/tools/qt5-base/bin/uic
```

Missing many files

**Comment by Neumann-A** [comment]
> Missing many files

It is: `vcpkg owns <dir/file>` and not `vcpkg owns <port>`  maybe that is the misunderstanding here? So you own get info which ports owns the directory or file called qt5-base

**Comment by xiaozhuai** [comment]
> > Missing many files
> 
> It is: `vcpkg owns <dir/file>` and not `vcpkg owns <port>` maybe that is the misunderstanding here? So you own get info which ports owns the directory or file called qt5-base

In fact, I need to list files owned by port.

**Comment by xiaozhuai** [comment]
Can this be added as a new feature? Something like `vcpkg owned <port>`? It's much meaningful than `vcpkg owns <dir/file>`

**Comment by xiaozhuai** [comment]
> list the files in `packages/${PORT}_<triplet>`

I install by adding `--clean-after-build`, this may not work.

**Comment by autoantwort** [comment]
See vcpkg_installed/vcpkg/info/qt5-base_5.15.7_x64-osx.list

**Comment by xiaozhuai** [comment]
Thanks! @Neumann-A @autoantwort
