### ISSUE TITLE
[physfs] cmake find_package fails with x86-windows-static triplet

### ISSUE THREAD

**Issue by ennorehling** [microsoft/vcpkg#28470]
**Describe the bug**
I'm using physfs in a project that's built with CMake, and want to build it for the x86-windows-static triplet. It seems that because the library is called physfs-static.lib, not physfs.lib, find_package does not detect it? Notably, if I manually rename the library to physfs.lib, it is found, and PHYSFS_LIBRARY gets set.

Error message from CMake is:
```
1> [CMake] -- Could NOT find PhysFS (missing: PHYSFS_LIBRARY) (Required is at least version "2.1")
```
My CMakeLists.txt contains this:
```
find_package(PhysFS 2.1)
```
This has always worked for the x86-windows triplet, where the library is called physfs.lib, and it works for other packages, e.g. libpng

**Environment**
- OS: Windows 7
- Compiler: Visual Studio 2019

**To Reproduce**
1. vcpkg install physfs:x86-windows-static
2. vcpkg install libpng:x86-windows-static
3. create CMakeLists.txt as below
4. run cmake -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x86-windows-static
5. See error: Could NOT find PhysFS (missing: PHYSFS_LIBRARY)

**Expected behavior**
I expect find_package to set the PHYSFS_LIBRARY variable.

**Failure logs**
```
$ "C:\vcpkg\downloads\tools\cmake-3.25.0-windows\cmake-3.25.0-windows-i386\bin\cmake.exe" -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 6.1.7601.
-- Could NOT find PhysFS (missing: PHYSFS_LIBRARY)
-- Found ZLIB: optimized;C:/vcpkg/installed/x86-windows-static/lib/zlib.lib;debug;C:/vcpkg/installed/x86-windows-static/debug/lib/zlibd.lib (found version "1.2.13")
-- Found PNG: optimized;C:/vcpkg/installed/x86-windows-static/lib/libpng16.lib;debug;C:/vcpkg/installed/x86-windows-static/debug/lib/libpng16d.lib (found version "1.6.39")
-- Configuring done
```
**Additional context**
This is my minimal CMakeLists.txt file that reproduces the issue:
```
cmake_minimum_required(VERSION 3.0)
project (repro C)
find_package(PhysFS)
find_package(PNG)
```

**Comment by Adela0814** [comment]
I'm not able to repro on x64-windows-static and x86-windows triplets. Tagged with `community-triplet`. 

Please try the following usage provided by the port:
```
    find_package(PhysFS CONFIG REQUIRED)
    target_link_libraries(main PRIVATE PhysFS::PhysFS-static)
```

**Comment by dg0yt** [comment]
You may want to set `CMAKE_FIND_DEBUG_MODE` to 1 before calling `find_package`, to get more insight.

> ~~~cmake
> find_package(PhysFS 2.1)

-  This signature will first try to find and use a `FindPhysFS.cmake` Find module. And the error message looks like from a Find module.
  Add `CONFIG` to enforce config mode. Use two calls if you want to try one after the other.
- This call asks for a particular version number. AFAICS the exported config doesn't provide version information.

**Comment by dg0yt** [comment]
> I expect find_package to set the PHYSFS_LIBRARY variable.

I assume the error is in the find module you use. It doesn't support the static lib. For static builds, the library's namespec is `physfs-static`, not  `physfs`. You probably need to add the alternative name (and `NAMES_PER_DIR`) to `find_library` calls in that find module.

Or you use the config. The target name varies with linkage, but this can be handled by a generator expression.

**Comment by dg0yt** [comment]
> I assume the error is in the find module you use.

I was wrong. There is a find module in CMake.
