### ISSUE TITLE
[gmp] build failure because of libtool version wrong

### ISSUE THREAD

**Issue by hushanjushi** [microsoft/vcpkg#28476]
**Host Environment**

- OS: Linux, Debian Sid
- Compiler: gcc-12.2

**To Reproduce**

`./vcpkg install gmp`

**Failure logs**
```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: /usr/bin/make V=1 -j 9 -f Makefile all
```
```
libtool: Version mismatch error.  This is libtool 2.4.6, but the
libtool: definition of this LT_INIT comes from libtool 2.4.7.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
libtool: and run autoconf again.
```

**Comment by dg0yt** [comment]
Please let us know the versions of gmp / vcpkg tool / vcpkg repo.

**Comment by hushanjushi** [comment]
> Please let us know the versions of gmp / vcpkg tool / vcpkg repo.

The vcpkg version is:

```
vcpkg package management program version 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
```

gmp version is `6.2.1#14`

The vcpkg repo version is newest.

**Comment by dg0yt** [comment]
Can you provide `autoconf-x64-linux-out.log`, `config-x64-linux-dbg-config.log`?
(Please use attachments for the latter, don't copy and paste to your post.)

**Comment by hushanjushi** [comment]
> Can you provide `autoconf-x64-linux-out.log`, `config-x64-linux-dbg-config.log`? (Please use attachments for the latter, don't copy and paste to your post.)

[autoconf-x64-linux-out.log](https://github.com/microsoft/vcpkg/files/10287338/autoconf-x64-linux-out.log)
[autoconf-x64-linux-err.log](https://github.com/microsoft/vcpkg/files/10287340/autoconf-x64-linux-err.log)

**Comment by hushanjushi** [comment]
> Can you provide `autoconf-x64-linux-out.log`, `config-x64-linux-dbg-config.log`? (Please use attachments for the latter, don't copy and paste to your post.)

sorry, I closed this issue accidently...

**Comment by dg0yt** [comment]
The config.log shows that `PATH` contains many entries, and I assume that some of them have the potential to construct an inconsistent mix of tool versions. You should try to start with a more standard set of directories in `PATH`, maybe as minimal as `/usr/bin:/bin`, i.e. just relying on stock Ubuntu packages.

**Comment by hushanjushi** [comment]
> The config.log shows that `PATH` contains many entries, and I assume that some of them have the potential to construct an inconsistent mix of tool versions. You should try to start with a more standard set of directories in `PATH`, maybe as minimal as `/usr/bin:/bin`, i.e. just relying on stock Ubuntu packages.

ok , it solved.
