### ISSUE TITLE
After vcpkg integrate install MSVS intellisence doesn't find header files

### ISSUE THREAD

**Issue by aPSopt** [microsoft/vcpkg#28477]
**Describe the bug**
After vcpkg integrate install MSVS intellisence doesn't find header files. 
I try to write `#include<boost/...` and any suggestion appears.
When I put headers ignoring fact that intellisence can't find it - the intellisence could give correct suggestion for classes in that header and anything compiles good.

**Environment**
- OS: Win10 (with last updates)
- Compiler: MSVS2022 with last updates + Visual assist (last version)

**To Reproduce**
0. clone vcpkg repo
1. ./vcpkg install boost
2. ./vcpkg integrate install
3. I try typing `#include<boost/...` and nothing appears in the suggestion

**Expected behavior**
When I typing `#include<boost/...` - there should appears suggestions for boost libraries

**Additional context**
When I put headers ignoring fact that intellisence can't find it - the intellisence could give correct suggestion for classes in that header and anything compiles good.

**Comment by FrankXie05** [comment]
@aPSopt Thanks for posting this issue, have you downloaded the build components? can you provide your project settings file? Is there a port for downloading the corresponding triplet?

**Comment by aPSopt** [comment]
I did the followed steps:

1) clone vcpkg in _c:/d/_ folder

2) set up followed environment variable for downloaded vcpkg:
![image](https://user-images.githubusercontent.com/10948931/209446424-b19468fe-5c1a-4994-8105-6971388e327c.png)

3) install boost

4) made 
vcpkg integrate install

3) made default msvs2022 console project
[ConsoleApplication4.zip](https://github.com/microsoft/vcpkg/files/10298981/ConsoleApplication4.zip)


And got the issue

**Comment by FrankXie05** [comment]
Can you provide the components content of your `Visual Studio Installer` download? 
for example: `MSbuild`、`MSVC ... build tools`、`.NET 6.0 Runtime` ...

**Comment by JackBoosY** [comment]
Can you find vcpkg label in the project property page?

**Comment by aPSopt** [comment]
> Can you provide the components content of your `Visual Studio Installer` download? for example: `MSbuild`、`MSVC ... build tools`、`.NET 6.0 Runtime` ...

![image](https://user-images.githubusercontent.com/10948931/209546466-a539bccc-9c55-4b93-ac36-901bd248cc6d.png)
![image](https://user-images.githubusercontent.com/10948931/209546503-898469f3-cde8-4da8-9849-eb23502ece46.png)
![image](https://user-images.githubusercontent.com/10948931/209546564-c17f3f5a-1d76-454b-8ec6-cb6455933acb.png)
![image](https://user-images.githubusercontent.com/10948931/209546657-b2954560-86ba-4d92-8d66-859deaf9baef.png)
![image](https://user-images.githubusercontent.com/10948931/209546696-48d02cd6-1a53-4c87-8bc1-fadab6b0c3e5.png)

Also I had installed 
![image](https://user-images.githubusercontent.com/10948931/209546753-6553adf6-85b1-4272-ac42-9ae0afa741be.png)
in scope of msvs2017


What else I can provide for help figure out issue?

**Comment by JackBoosY** [comment]
Which triplet did you use and which configuration do your project use?

**Comment by aPSopt** [comment]
Triplet: x64-windows
Configuration: x64, debug, default msvs console application

**Comment by JackBoosY** [comment]
Can you please complete a sample code, build it then provide the failure logs?

**Comment by aPSopt** [comment]
Test project you can find in attachment in my second comment from the top.
I note in initial message, that there are no any failure during build. 
It is intellisence issue - doesn't works completion of include headers

**Comment by JackBoosY** [comment]
> Test project you can find in attachment in my second comment from the top. I note in initial message, that there are no any failure during build. It is intellisence issue - doesn't works completion of include headers

So maybe report to VS community instead?

**Comment by aPSopt** [comment]
I think this is the installation bug of vcpkg, isn't it?

**Comment by JackBoosY** [comment]
If it builds and uses without any problems, it means that vcpkg has correctly set the additional include path. So this should be a VS intellisense issue.

**Comment by Cheney-W** [comment]
This issue should be a Visual Studio C++ Intellisense issue, please open a feedback ticket in https://developercommunity.visualstudio.com/cpp/report.
