### ISSUE TITLE
Issues sharing single install root between multiple projects in manifest mode

### ISSUE THREAD

**Issue by siilky** [microsoft/vcpkg#28497]
I'm running several visual studio projects using vcpkg in manifest mode. I have set same install directory in vcpkg project options.

The issues I'm observing are:
- packages aren't mixed properly between platforms/triplets (it is somehow related to #27106) - building any new triplet removes packages from any 'other' triplets while keeping `msbuildstamp-x86-windows.stamp` at install root making 'other' platform builds to fail until removing buildstamp
- packages between projects aren't mixed properly also for single same triplet: building with one set of packages removes any not listed in dependencies installed package of other projects, and not restored when building other project(s) back.

Is it expected behavior of install root option? 
Could I have any advice of how to share package installations for multiple projects with manifest mode?

**Comment by Osyotr** [comment]
`--x-install-root` vcpkg cmdline option might help.

**Comment by siilky** [comment]
> `--x-install-root` vcpkg cmdline option might help.

that's exactly how it used from VS and what am I talking about.

**Comment by Osyotr** [comment]
> Is it expected behavior of install root option?

Yes. Different triplets/manifests are separated from each other.

> Could I have any advice of how to share package installations for multiple projects with manifest mode?

Pass different folders via `--x-install-root` for each triplet/project (IIRC, this is default behavior without this option, at least with CMake). The packages will not be rebuilt because of binarycaching. It might take more storage space, but this is the price for consistency.

**Comment by autoantwort** [comment]
> I have set same install directory in vcpkg project options.

If you don't do that you don't get these problems

**Comment by siilky** [comment]
Okay, I have set different install roots for every project.

Here, I still have the issue when switching platforms x86-x64: every new platform removes packages from previous platform and switching back does not restores them because `msbuildstamp-*-windows.stamp` is still in place

**Comment by autoantwort** [comment]
> Here, I still have the issue when switching platforms x86-x64

You also need different install roots for every target triplet

**Comment by Kered13** [comment]
> > Is it expected behavior of install root option?
> 
> Yes. Different triplets/manifests are separated from each other.
> 
> > Could I have any advice of how to share package installations for multiple projects with manifest mode?
> 
> Pass different folders via `--x-install-root` for each triplet/project (IIRC, this is default behavior without this option, at least with CMake). The packages will not be rebuilt because of binarycaching. It might take more storage space, but this is the price for consistency.

This can be impractical when you have a lot of projects, significantly overlapping dependencies, and large dependencies. A practical solution to sharing dependencies between projects would be very helpful.

**Comment by autoantwort** [comment]
@Kered13 You could have one vcpkg.json with all the dependencies you need.

**Comment by Cheney-W** [comment]
Thanks for reporting this issue, please refer to the comments of autoantword to solve your issue.
