### ISSUE TITLE
vcpkg upgrade list crash

### ISSUE THREAD

**Issue by SamBum92** [microsoft/vcpkg#28496]
**Bug Description**
vcpkg unupgradable

.\vcpkg\vcpkg upgrade list
error: The following packages are not installed:
    list:x86-windows
error: The following packages do not have a valid CONTROL or vcpkg.json:
    list:x86-windows
internal error: D:\a\_work\1\s\src\vcpkg\commands.upgrade.cpp(192): vcpkg has crashed; no additional details are available.

**Environment**
Windows 10 Pro 22H2

**To Reproduce**
git clone https://github.com/microsoft/vcpkg
.\vcpkg\bootstrap-vcpkg.bat
.\vcpkg\vcpkg upgrade list

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. If you want update all your installed ports, you should use command `.\vcpkg\vcpkg upgrade`. If you want update one port which you installed, you should use command `.\vcpkg\vcpkg upgrade PORT_NAME: INSTALLED_TRIPLET`.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
