### ISSUE TITLE
Build command incorrectly handles dependencies

### ISSUE THREAD

**Issue by alexkaratarakis** [Microsoft/vcpkg#285]
`E:\workspace\vcpkg> vcpkg list`
boost:x86-windows-static    1.62-2           Peer-reviewed portable C++ source libraries
cpprestsdk:x86-windows-static 2.9.0-1          C++11 JSON, REST, and OAuth library The C++ RES...
openssl:x86-windows-static  1.0.2j           OpenSSL is an open source project that provides a...
zlib:x86-windows-static     1.2.8            A compression library

`E:\workspace\vcpkg> vcpkg build cpprestsdk:x86-windows-static`
The build command requires all dependencies to be already installed.
The following dependencies are missing:

    zlib:x86-windows-static
    boost:x86-windows-static
    openssl:x86-windows-static

**Comment by GeertVL** [comment]
Does they need to be installed automatically when you run the build command?

**Comment by alexkaratarakis** [comment]
The `install` command will handle dependencies automatically and you can specify multiple arguments. 
The `build` command is internal/undocumented, so the current intention was to have all dependencies installed before you run build, and there is a verification for it. Also `build` only allows 1 package to be specified. 

This is because, if (for example) you request for `cpprestsdk` which depends on zlib, boost, openssl, then `install` will result in:
`zlib` = installed
`openssl`= = installed
`boost` = installed
`cpprestsdk` = installed

and `build` would result in:
`zlib` = installed
`openssl`= = installed
`boost` = installed
`cpprestsdk` = built but not installed

This feels a bit unexpected. This is further complicated if you do something like:
`vcpkg build cpprestsdk zlib`
(Should zlib be installed or not?). 


Regarding the current bug: Fixed with 2584f3e3def7f09bc373117985013ac019aa76d6
