### ISSUE TITLE
cmake find_package cannot find boost

### ISSUE THREAD

**Issue by ei06125** [microsoft/vcpkg#28508]
**Describe the bug**

**Environment**
- OS: Windows
- Compiler: MSVC

**To Reproduce**
1. ./vcpkg install boost --triplet x64-windows
2. Use VS Code with CMakeTools and path to CMAKE_TOOLCHAIN_FILE=<path-to-vckpg.cmake>
3. See error when configuring the project

**Expected behavior**
Expected a clean build

**Failure logs**

** Console Output **

[cmake] CMake Error at C:/dev/src/Microsoft/vcpkg/installed/x64-windows/share/boost/vcpkg-cmake-wrapper.cmake:11 (_find_package):
[cmake]   Could not find a package configuration file provided by "Boost" with any of
[cmake]   the following names:
[cmake] 
[cmake]     BoostConfig.cmake
[cmake]     boost-config.cmake
[cmake] 
[cmake]   Add the installation prefix of "Boost" to CMAKE_PREFIX_PATH or set
[cmake]   "Boost_DIR" to a directory containing one of the above files.  If "Boost"
[cmake]   provides a separate development package or SDK, be sure it has been
[cmake]   installed.
[cmake] Call Stack (most recent call first):
[cmake]   C:/dev/src/Microsoft/vcpkg/scripts/buildsystems/vcpkg.cmake:797 (include)
[cmake]   CMakeLists.txt:6 (find_package)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "C:/dev/src/Microsoft/test_vcpkg/build/Windows/Debug/CMakeFiles/CMakeOutput.log".

** CMakeOutput.log **

The system is: Windows - 10.0.19045 - AMD64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler:  
Build flags: 
Id flags:  

The output was:
0
MSBuild version 17.4.0+18d5aef85 for .NET Framework
Build started 12/23/2022 4:30:20 PM.
Project "C:\dev\src\Microsoft\test_vcpkg\build\Windows\Debug\CMakeFiles\3.24.3\CompilerIdC\CompilerIdC.vcxproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "Debug\".
  Creating directory "Debug\CompilerIdC.tlog\".
InitializeBuildStatus:
  Creating "Debug\CompilerIdC.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
VcpkgTripletSelection:
  Using triplet "x64-windows" from "C:\dev\src\Microsoft\vcpkg\installed\x64-windows\"
  Using normalized configuration "Release"
ClCompile:
  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\CL.exe /c /I"C:\dev\src\Microsoft\vcpkg\installed\x64-windows\include" /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
  CMakeCCompilerId.c
Link:
  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO /LIBPATH:"C:\dev\src\Microsoft\vcpkg\installed\x64-windows\lib" /LIBPATH:"C:\dev\src\Microsoft\vcpkg\installed\x64-windows\lib\manual-link" kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib "C:\dev\src\Microsoft\vcpkg\installed\x64-windows\lib\*.lib" /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdC.lib" /MACHINE:X64 Debug\CMakeCCompilerId.obj
  CompilerIdC.vcxproj -> C:\dev\src\Microsoft\test_vcpkg\build\Windows\Debug\CMakeFiles\3.24.3\CompilerIdC\CompilerIdC.exe
AppLocalFromInstalled:
  pwsh.exe -ExecutionPolicy Bypass -noprofile -File "C:\dev\src\Microsoft\vcpkg\scripts\buildsystems\msbuild\applocal.ps1" "C:\dev\src\Microsoft\test_vcpkg\build\Windows\Debug\CMakeFiles\3.24.3\CompilerIdC\CompilerIdC.exe" "C:\dev\src\Microsoft\vcpkg\installed\x64-windows\bin" "Debug\CompilerIdC.tlog\CompilerIdC.write.1u.tlog" "Debug\vcpkg.applocal.log"
  'pwsh.exe' is not recognized as an internal or external command,
  operable program or batch file.
  The command "pwsh.exe -ExecutionPolicy Bypass -noprofile -File "C:\dev\src\Microsoft\vcpkg\scripts\buildsystems\msbuild\applocal.ps1" "C:\dev\src\Microsoft\test_vcpkg\build\Windows\Debug\CMakeFiles\3.24.3\CompilerIdC\CompilerIdC.exe" "C:\dev\src\Microsoft\vcpkg\installed\x64-windows\bin" "Debug\CompilerIdC.tlog\CompilerIdC.write.1u.tlog" "Debug\vcpkg.applocal.log"" exited with code 9009.
  "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -ExecutionPolicy Bypass -noprofile -File "C:\dev\src\Microsoft\vcpkg\scripts\buildsystems\msbuild\applocal.ps1" "C:\dev\src\Microsoft\test_vcpkg\build\Windows\Debug\CMakeFiles\3.24.3\CompilerIdC\CompilerIdC.exe" "C:\dev\src\Microsoft\vcpkg\installed\x64-windows\bin" "Debug\CompilerIdC.tlog\CompilerIdC.write.1u.tlog" "Debug\vcpkg.applocal.log"
PostBuildEvent:
  for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
  :VCEnd
  CMAKE_C_COMPILER=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\Hostx64\x64\cl.exe
FinalizeBuildStatus:
  Deleting file "Debug\CompilerIdC.tlog\unsuccessfulbuild".
  Touching "Debug\CompilerIdC.tlog\CompilerIdC.lastbuildstate".
Done Building Project "C:\dev\src\Microsoft\test_vcpkg\build\Windows\Debug\CMakeFiles\3.24.3\CompilerIdC\CompilerIdC.vcxproj" (default targets).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.95

Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"

Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"

The C compiler identification is MSVC, found in "C:/dev/src/Microsoft/test_vcpkg/build/Windows/Debug/CMakeFiles/3.24.3/CompilerIdC/CompilerIdC.exe"

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
Compiler:  
Build flags: 
Id flags:  

The output was:
0
MSBuild version 17.4.0+18d5aef85 for .NET Framework
Build started 12/23/2022 4:30:22 PM.
Project "C:\dev\src\Microsoft\test_vcpkg\build\Windows\Debug\CMakeFiles\3.24.3\CompilerIdCXX\CompilerIdCXX.vcxproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "Debug\".
  Creating directory "Debug\CompilerIdCXX.tlog\".
InitializeBuildStatus:
  Creating "Debug\CompilerIdCXX.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
VcpkgTripletSelection:
  Using triplet "x64-windows" from "C:\dev\src\Microsoft\vcpkg\installed\x64-windows\"
  Using normalized configuration "Release"
ClCompile:
  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\CL.exe /c /I"C:\dev\src\Microsoft\vcpkg\installed\x64-windows\include" /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
  CMakeCXXCompilerId.cpp
Link:
  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO /LIBPATH:"C:\dev\src\Microsoft\vcpkg\installed\x64-windows\lib" /LIBPATH:"C:\dev\src\Microsoft\vcpkg\installed\x64-windows\lib\manual-link" kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib "C:\dev\src\Microsoft\vcpkg\installed\x64-windows\lib\*.lib" /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdCXX.lib" /MACHINE:X64 Debug\CMakeCXXCompilerId.obj
  CompilerIdCXX.vcxproj -> C:\dev\src\Microsoft\test_vcpkg\build\Windows\Debug\CMakeFiles\3.24.3\CompilerIdCXX\CompilerIdCXX.exe
AppLocalFromInstalled:
  pwsh.exe -ExecutionPolicy Bypass -noprofile -File "C:\dev\src\Microsoft\vcpkg\scripts\buildsystems\msbuild\applocal.ps1" "C:\dev\src\Microsoft\test_vcpkg\build\Windows\Debug\CMakeFiles\3.24.3\CompilerIdCXX\CompilerIdCXX.exe" "C:\dev\src\Microsoft\vcpkg\installed\x64-windows\bin" "Debug\CompilerIdCXX.tlog\CompilerIdCXX.write.1u.tlog" "Debug\vcpkg.applocal.log"
  'pwsh.exe' is not recognized as an internal or external command,
  operable program or batch file.
  The command "pwsh.exe -ExecutionPolicy Bypass -noprofile -File "C:\dev\src\Microsoft\vcpkg\scripts\buildsystems\msbuild\applocal.ps1" "C:\dev\src\Microsoft\test_vcpkg\build\Windows\Debug\CMakeFiles\3.24.3\CompilerIdCXX\CompilerIdCXX.exe" "C:\dev\src\Microsoft\vcpkg\installed\x64-windows\bin" "Debug\CompilerIdCXX.tlog\CompilerIdCXX.write.1u.tlog" "Debug\vcpkg.applocal.log"" exited with code 9009.
  "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -ExecutionPolicy Bypass -noprofile -File "C:\dev\src\Microsoft\vcpkg\scripts\buildsystems\msbuild\applocal.ps1" "C:\dev\src\Microsoft\test_vcpkg\build\Windows\Debug\CMakeFiles\3.24.3\CompilerIdCXX\CompilerIdCXX.exe" "C:\dev\src\Microsoft\vcpkg\installed\x64-windows\bin" "Debug\CompilerIdCXX.tlog\CompilerIdCXX.write.1u.tlog" "Debug\vcpkg.applocal.log"
PostBuildEvent:
  for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
  :VCEnd
  CMAKE_CXX_COMPILER=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\Hostx64\x64\cl.exe
FinalizeBuildStatus:
  Deleting file "Debug\CompilerIdCXX.tlog\unsuccessfulbuild".
  Touching "Debug\CompilerIdCXX.tlog\CompilerIdCXX.lastbuildstate".
Done Building Project "C:\dev\src\Microsoft\test_vcpkg\build\Windows\Debug\CMakeFiles\3.24.3\CompilerIdCXX\CompilerIdCXX.vcxproj" (default targets).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.94

Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"

Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"

The CXX compiler identification is MSVC, found in "C:/dev/src/Microsoft/test_vcpkg/build/Windows/Debug/CMakeFiles/3.24.3/CompilerIdCXX/CompilerIdCXX.exe"

Detecting C compiler ABI info compiled with the following output:
Change Dir: C:/dev/src/Microsoft/test_vcpkg/build/Windows/Debug/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_089de.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:m && MSBuild version 17.4.0+18d5aef85 for .NET Framework

  Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31933 for x64

  CMakeCCompilerABI.c

  Copyright (C) Microsoft Corporation.  All rights reserved.

  cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_089de.dir\Debug\\" /Fd"cmTC_089de.dir\Debug\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\Program Files\CMake\share\cmake-3.24\Modules\CMakeCCompilerABI.c"

  cmTC_089de.vcxproj -> C:\dev\src\Microsoft\test_vcpkg\build\Windows\Debug\CMakeFiles\CMakeTmp\Debug\cmTC_089de.exe

Detecting CXX compiler ABI info compiled with the following output:
Change Dir: C:/dev/src/Microsoft/test_vcpkg/build/Windows/Debug/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_a8218.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:m && MSBuild version 17.4.0+18d5aef85 for .NET Framework

  Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31933 for x64

  CMakeCXXCompilerABI.cpp

  Copyright (C) Microsoft Corporation.  All rights reserved.

  cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_a8218.dir\Debug\\" /Fd"cmTC_a8218.dir\Debug\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\Program Files\CMake\share\cmake-3.24\Modules\CMakeCXXCompilerABI.cpp"

  cmTC_a8218.vcxproj -> C:\dev\src\Microsoft\test_vcpkg\build\Windows\Debug\CMakeFiles\CMakeTmp\Debug\cmTC_a8218.exe

**Additional context**

**Comment by MonicaLiu0311** [comment]
This is the same as another [issue](https://github.com/microsoft/vcpkg/issues/28507), both initiated by you.

Would you mind providing CMakeLists.txt, I'd like to see how you wrote it.

**Comment by ei06125** [comment]
`cmake_minimum_required(VERSION 3.21)
project(test_vcpkg)

find_package(Boost CONFIG REQUIRED)

add_executable(main main.cpp)
target_link_libraries(main PRIVATE Boost::Boost)
`

**Comment by ei06125** [comment]
Main file (from boost asio tutorial
```
//
// timer.cpp
// ~~~~~~~~~
//
// Copyright (c) 2003-2022 Christopher M. Kohlhoff (chris at kohlhoff dot com)
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//

#include <boost/asio.hpp>
#include <iostream>

int main() {
  boost::asio::io_context io;

  boost::asio::steady_timer t(io, boost::asio::chrono::seconds(5));
  t.wait();

  std::cout << "Hello, world!" << std::endl;

  return 0;
}
```

**Comment by ei06125** [comment]
VS Code workspace settings.json file:
```
{
    "cmake.configureArgs": [
        "-DCMAKE_TOOLCHAIN_FILE=C:/dev/src/microsoft/vcpkg/scripts/buildsystems/vcpkg.cmake"
    ]
}
```

**Comment by ei06125** [comment]
I have searched a bit about and found that I can provide BOOST_ROOT during configuration. But the problem is that vcpkg has different archives for each individual component in boost.

**Comment by autoantwort** [comment]
To find boost you have to use `find_package(Boost REQUIRED)`

**Comment by ei06125** [comment]
Tried with:
```
cmake_minimum_required(VERSION 3.21)
project(test_vcpkg)

find_package(Boost REQUIRED)

add_executable(main main.cpp)
target_link_libraries(main PRIVATE Boost::Boost)
```

Result:
```
[main] Configuring folder: test_vcpkg 
[driver] Removing c:/dev/src/microsoft/test_vcpkg/build/Windows/Debug/CMakeCache.txt
[driver] Removing c:\dev\src\microsoft\test_vcpkg\build\Windows\Debug\CMakeFiles
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --no-warn-unused-cli -DCMAKE_TOOLCHAIN_FILE=C:/dev/src/microsoft/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -Sc:/dev/src/microsoft/test_vcpkg -Bc:/dev/src/microsoft/test_vcpkg/build/Windows/Debug -G "Visual Studio 17 2022" -T host=x64 -A x64
[cmake] Not searching for unused variables given on the command line.
[cmake] -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22621.
[cmake] -- The C compiler identification is MSVC 19.34.31937.0
[cmake] -- The CXX compiler identification is MSVC 19.34.31937.0
[cmake] -- Detecting C compiler ABI info
[cmake] -- Detecting C compiler ABI info - done
[cmake] -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - skipped
[cmake] -- Detecting C compile features
[cmake] -- Detecting C compile features - done
[cmake] -- Detecting CXX compiler ABI info
[cmake] -- Detecting CXX compiler ABI info - done
[cmake] -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - skipped
[cmake] -- Detecting CXX compile features
[cmake] -- Detecting CXX compile features - done
[cmake] CMake Error at C:/Program Files/CMake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
[cmake]   Could NOT find Boost (missing: Boost_INCLUDE_DIR)
[cmake] Call Stack (most recent call first):
[cmake]   C:/Program Files/CMake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
[cmake]   C:/Program Files/CMake/share/cmake-3.23/Modules/FindBoost.cmake:2376 (find_package_handle_standard_args)
[cmake]   C:/dev/src/microsoft/vcpkg/installed/x64-windows/share/boost/vcpkg-cmake-wrapper.cmake:11 (_find_package)
[cmake]   C:/dev/src/microsoft/vcpkg/scripts/buildsystems/vcpkg.cmake:797 (include)
[cmake]   CMakeLists.txt:4 (find_package)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "C:/dev/src/microsoft/test_vcpkg/build/Windows/Debug/CMakeFiles/CMakeOutput.log".
[proc] The command: "C:\Program Files\CMake\bin\cmake.EXE" --no-warn-unused-cli -DCMAKE_TOOLCHAIN_FILE=C:/dev/src/microsoft/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -Sc:/dev/src/microsoft/test_vcpkg -Bc:/dev/src/microsoft/test_vcpkg/build/Windows/Debug -G "Visual Studio 17 2022" -T host=x64 -A x64 exited with code: 1 and signal: null
[visual-studio] Patch Windows SDK path from C:\Program Files (x86)\Windows Kits\10\bin\x64 to C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64 for C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat
```

**Comment by autoantwort** [comment]
Are you using manifest mode?

**Comment by ei06125** [comment]
What is manifest mode?

**Comment by autoantwort** [comment]
https://learn.microsoft.com/en-us/vcpkg/examples/manifest-mode-cmake

**Comment by ei06125** [comment]
I think I was using `vcpkg install boost` instead of `vcpkg install boost --triplet x64-windows`. But shouldn't that be the default behavior on a 64-bit Windows version?

**Comment by autoantwort** [comment]
> But shouldn't that be the default behavior on a 64-bit Windows version?

https://github.com/microsoft/vcpkg-tool/pull/640#issuecomment-1194431232

**Comment by ei06125** [comment]
Can I set `VCPKG_DEFAULT_TRIPLET` in the `vcpkg.json` (that's what sets the manifest mode right?)

**Comment by autoantwort** [comment]
> Can I set VCPKG_DEFAULT_TRIPLET in the vcpkg.json

You don't have to. 

> that's what sets the manifest mode right?

Yes

**Comment by ei06125** [comment]
Going to close this issue. I think the Getting Started page should be updated and at least have a warning about this there. But after diving into vcpkg, the solution is easy.
Thanks for the support.

**Comment by lxmedai** [comment]
> Going to close this issue. I think the Getting Started page should be updated and at least have a warning about this there. But after diving into vcpkg, the solution is easy. Thanks for the support.

So how did you solve the problem in the end? I've encountered the same problem during installation of CGAL which depends on boost using visual studio.

**Comment by ei06125** [comment]
I think (don't really remember now) that I just installed boost on my system.

My take with dependencies is that, in general, it is just easier and simpler to install common dependencies (spdlog, gtest, boost) and let vcpkg take care of minor dependencies (specific for each project). But maybe I will tackle this in the future.

Sorry I can't help.

**Comment by lxmedai** [comment]
> I think (don't really remember now) that I just installed boost on my system.
> 
> My take with dependencies is that, in general, it is just easier and simpler to install common dependencies (spdlog, gtest, boost) and let vcpkg take care of minor dependencies (specific for each project). But maybe I will tackle this in the future.
> 
> Sorry I can't help.

I solved this problem by installing the static version instead by `vcpkg install boost --triplet x64-windows-static`. Then CMake does not complain about missing **Boost_INCLUDE_DIR** any more. In case this can be helpful for others, I also share this solution here.

**Comment by yhyu13** [comment]
Here is my setup for boost linux x64.

I used vckplg.json along side with CmakeLists.txt

```
{
    "dependencies": [  
        "boost"
    ]
}
```
This installs all boost v1.83.0

Cmake
```
set(CMAKE_TOOLCHAIN_FILE "${PATH_TO_INSTALL_VCPKG}/vcpkg/scripts/buildsystems/vcpkg.cmake"
  CACHE STRING "Vcpkg toolchain file")

find_package(Boost REQUIRED)
if (Boost_FOUND)
    include_directories(${Boost_INCLUDE_DIRS})
    link_directories(${Boost_LIBRARY_DIRS})
endif ()

target_link_libraries(MyLib PUBLIC ${Boost_LIBRARIES})
```

Reference : 
https://zhuanlan.zhihu.com/p/454233496
https://learn.microsoft.com/en-us/vcpkg/consume/boost-versions

**Comment by dg0yt** [comment]
@yhyu13 Given the absence of a `project` command in your example, `set(CMAKE_TOOLCHAIN_FILE ...)` is probably coming too late. This variable must be set before the `project` is seen the first time. Literally, in the first run of cmake for a clean binary dir.
And better don't depend on all of boost, i.e. use specific`boost-<component>` ports in the manifest, and use boost `COMPONENTS` in CMake.

**Comment by chses9440611** [comment]
I recently encounter this problem too. I use VS2019. I change the cmake generator from "Ninja" to "Visual Studio 16 2019", and the error becomes a warning from FindBoost.cmake.
