### ISSUE TITLE
vcpkg doesn't build debug libraries for protobuf

### ISSUE THREAD

**Issue by jjpepper** [Microsoft/vcpkg#2850]
It's all in the title.   protobuf recommends using linking against the debug version of the library.

> To avoid conflicts between the MSVC debug and release runtime libraries, when compiling a debug build of your application, you may need to link against a debug build of libprotobufd.lib with "d" postfix. Similarly, release builds should link against release libprotobuf.lib library.

From [here](https://github.com/google/protobuf/blob/master/cmake/README.md)

Please also build the debug version or this is a showstopper for using vcpkg and libprotobuf and building in debug.

**Comment by ras0219-msft** [comment]
Hi @jjpepper, thanks for posting this issue!

Vcpkg always builds both release and debug -- the debug libraries are located under `debug\lib\`. If you use any of our recommended integration methods, the paths should be correctly set up based on your project configuration.
