### ISSUE TITLE
[New Port Request] <VulkanSceneGraph (VSG)>

### ISSUE THREAD

**Issue by exldna** [microsoft/vcpkg#28529]
Library name: VulkanSceneGraph

Library description: VulkanSceneGraph (VSG), is a modern, cross platform, high performance scene graph library built upon Vulkan graphics/compute API

Source repository URL: https://github.com/vsg-dev/VulkanSceneGraph

Project homepage (if different from the source repository): http://www.vulkanscenegraph.org/

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
