### ISSUE TITLE
[tiff] zstd 1.5.2#1 tiff feature config file name update

### ISSUE THREAD

**Issue by AbdulAbCellera** [microsoft/vcpkg#28523]
Since zstd 1.5.2#1, the zstd port has removed the renaming of CMake config files https://github.com/microsoft/vcpkg/pull/22822. This change causes tiff[zstd] to fail if zstd is not added as an override with pinned to zstd 1.5.2#1. I see this issue only on Linux though.

The error is
```
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:843 (_find_package):
[cmake]   Could not find a package configuration file provided by "ZSTD" with any of
[cmake]   the following names:
[cmake] 
[cmake]     ZSTDConfig.cmake
[cmake]     zstd-config.cmake
[cmake] 
[cmake]   Add the installation prefix of "ZSTD" to CMAKE_PREFIX_PATH or set
[cmake]   "ZSTD_DIR" to a directory containing one of the above files.  If "ZSTD"
[cmake]   provides a separate development package or SDK, be sure it has been
[cmake]   installed.
[cmake] Call Stack (most recent call first):
[cmake]   vcpkg_installed/x64-linux-<>/share/tiff/vcpkg-cmake-wrapper.cmake:33 (find_package)
[cmake]   vcpkg/scripts/buildsystems/vcpkg.cmake:797 (include)
[cmake]   CMakeLists.txt:50 (find_package)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
```

The fix is very easy. `find_package(ZSTD ...)` should be replaced with a lowercase `find_package(zstd ...)`.
https://github.com/microsoft/vcpkg/blob/6adca01a3fadca0cc0b80f03ec57c7c3a0be5c02/ports/tiff/vcpkg-cmake-wrapper.cmake.in#L33

**Comment by dg0yt** [comment]
On my x64-linux, tiff configures and builds as expected:
~~~
--   ZSTD support:                       Requested:ON Availability:TRUE Support:TRUE
~~~
Building the current version of tiff simply falls back on its own `FindZSTD.cmake`.

The actual problem is not building but using TIFF. That's where the wrapper currently tries to use the wrong config.
