### ISSUE TITLE
ffmpeg:arm-uwp failed

### ISSUE THREAD

**Issue by granoviter** [Microsoft/vcpkg#2853]
vcpkg install ffmpeg:x86-uwp ffmpeg:x64-uwp ffmpeg:arm-uwp

Error: Building package ffmpeg:arm-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ffmpeg:arm-uwp
  Vcpkg version: 0.0.104-unknownhash

:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
resolving dependencies...
looking for conflicting packages...
:: msys2-runtime and catgets are in conflict. Remove catgets? [y/N] 
:: msys2-runtime and catgets are in conflict

error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)

**Comment by PhoebeHui** [comment]
@granoviter, thank you for posting the issue, does the issue still occur?

ffmpeg:arm-uwp install successfully with vcpkg latest version and VS2017 15.9.7
Starting package 2/3: ffmpeg:arm-uwp
Building package ffmpeg[core]:arm-uwp...
-- Using cached F:/VCPKG/src/downloads/ffmpeg-4.1.tar.bz2
-- Applying patch F:/VCPKG/src/ports/ffmpeg/create-lib-libraries.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch F:/VCPKG/src/ports/ffmpeg/detect-openssl.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch F:/VCPKG/src/ports/ffmpeg/configure_opencv.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Downloading https://raw.githubusercontent.com/FFmpeg/gas-preprocessor/36bacb4cba27003c572e5bf7a9c4dfe3c9a8d40d/gas-preprocessor.pl...
-- Building Options: --enable-asm --enable-yasm --disable-doc --enable-debug --disable-ffmpeg --enable-runtime-cpudetect --disable-openssl --disable-ffplay --d
isable-ffprobe --disable-libx264 --disable-opencl --disable-lzma --disable-programs --enable-cross-compile --target-os=win32 --arch=arm --extra-cflags=-DWINAPI
_FAMILY=WINAPI_FAMILY_APP --extra-cflags=-D_WIN32_WINNT=0x0A00 --extra-cflags=-DHAVE_UNISTD_H=0 --disable-static --enable-shared --extra-ldflags=-APPCONTAINER
--extra-ldflags=WindowsApp.lib
-- Building ffmpeg for Release
-- Building ffmpeg for Debug
-- Generating F:\VCPKG\src\packages\ffmpeg_arm-uwp\debug\lib\avcodec.lib
-- Generating F:\VCPKG\src\packages\ffmpeg_arm-uwp\debug\lib\avdevice.lib
-- Generating F:\VCPKG\src\packages\ffmpeg_arm-uwp\debug\lib\avfilter.lib
-- Generating F:\VCPKG\src\packages\ffmpeg_arm-uwp\debug\lib\avformat.lib
-- Generating F:\VCPKG\src\packages\ffmpeg_arm-uwp\debug\lib\avutil.lib
-- Generating F:\VCPKG\src\packages\ffmpeg_arm-uwp\debug\lib\swresample.lib
-- Generating F:\VCPKG\src\packages\ffmpeg_arm-uwp\debug\lib\swscale.lib
-- Generating F:\VCPKG\src\packages\ffmpeg_arm-uwp\lib\avcodec.lib
-- Generating F:\VCPKG\src\packages\ffmpeg_arm-uwp\lib\avdevice.lib
-- Generating F:\VCPKG\src\packages\ffmpeg_arm-uwp\lib\avfilter.lib
-- Generating F:\VCPKG\src\packages\ffmpeg_arm-uwp\lib\avformat.lib
-- Generating F:\VCPKG\src\packages\ffmpeg_arm-uwp\lib\avutil.lib
-- Generating F:\VCPKG\src\packages\ffmpeg_arm-uwp\lib\swresample.lib
-- Generating F:\VCPKG\src\packages\ffmpeg_arm-uwp\lib\swscale.lib
-- Performing post-build validation
-- Performing post-build validation done
Building package ffmpeg[core]:arm-uwp... done
Installing package ffmpeg[core]:arm-uwp...
Installing package ffmpeg[core]:arm-uwp... done

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
