### ISSUE TITLE
How do I put sources directly in the port directory

### ISSUE THREAD

**Issue by asfernandes** [microsoft/vcpkg#28534]
In https://github.com/microsoft/vcpkg/blob/master/docs/about/faq.md#can-i-build-a-private-library-with-this-tool it mentions to put zip file in port's `downloads` directory, but there is no real example.

Also, for private ports it sometimes make sense to have (non-zipped) sources directly in the port directory.

I tried in many different ways and also asked questions, but I cannot make it work.

**Comment by JackBoosY** [comment]
Use `vcpkg_extract_source_archive` only since you've already put the zip file into _ports/<PORT_NAME>_.

**Comment by asfernandes** [comment]
I used this, apparently without problems, to put sources directly (not zipped) in ports directory. Is it ok?

```
file(REMOVE_RECURSE "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}")

file(
    COPY "${CMAKE_CURRENT_LIST_DIR}/src/project/"
    DESTINATION "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}"
)
```

**Comment by JackBoosY** [comment]
> I used this, apparently without problems, to put sources directly (not zipped) in ports directory. Is it ok?
> 
> ```
> file(REMOVE_RECURSE "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}")
> 
> file(
>     COPY "${CMAKE_CURRENT_LIST_DIR}/src/project/"
>     DESTINATION "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}"
> )
> ```

Don't need to remove target folder, just use `vcpkg_extract_source_archive_ex` such as:
```cmake
    vcpkg_extract_source_archive_ex(
        OUT_SOURCE_PATH SOURCE_PATH
        ARCHIVE "${CMAKE_CURRENT_LIST_DIR}/<ZIP_FILE_NAME>"
        PATCHES
            ...
    )
```

**Comment by asfernandes** [comment]
But as I said I want to put **unzipped** sources in the ports directory.

It's a custom registry embedded in another project's git.

**Comment by JackBoosY** [comment]
> But as I said I want to put **unzipped** sources in the ports directory.
> 
> It's a custom registry embedded in another project's git.

Okay, so please copy to _VCPKG_ROOT/buildtrees/<PORT_NAME>/src_.

**Comment by dg0yt** [comment]
... why not just pass `SOURCE_PATH "${CMAKE_CURRENT_LIST_DIR}"` to `vcpkg_cmake_configure` and friends?

**Comment by asfernandes** [comment]
The project do not use cmake, it uses standard `Makefile`.
And it builds inside the same source tree.

**Comment by dg0yt** [comment]
Then you have to copy, probably once for every build type (release, debug).

**Comment by LilyWangLL** [comment]
> ... why not just pass `SOURCE_PATH "${CMAKE_CURRENT_LIST_DIR}"` to `vcpkg_cmake_configure` and friends?

Thanks for posting this issue, please try this solution, if it is still an issue, please reopen.
