### ISSUE TITLE
vcpkg is trying to reinstall git.

### ISSUE THREAD

**Issue by jrfl** [Microsoft/vcpkg#2854]
I do not need duplicate installs. :)

I installed git with the Community 2017 (VSC hereafter) installer (these details are from that install)
I also removed the version installed by VSC and installed the version from git.org.
In all cases I tried, git was on my path.

This was done on 02/21/2018 with a fresh clone of the vcpkg repository from that day.

## Details:
D:\tmp\vcpkg>path
PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Users\redact\AppData\Local\Microsoft\WindowsApps;c:\util;C:\Program Files\CMake\bin

D:\tmp\vcpkg>vcpkg install cpr
The following packages will be built and installed:
    cpr[core]:x86-windows
  * curl[core]:x86-windows
  * libssh2[core]:x86-windows
  * nghttp2[core]:x86-windows
  * openssl[core]:x86-windows
  * zlib[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/6: zlib:x86-windows
Building package zlib[core]:x86-windows...
A suitable version of git was not found (required v2.16.2). Downloading portable git v2.16.2...

D:\tmp\vcpkg>which git
C:\Program Files\Git\cmd\git.exe

D:\tmp\vcpkg>git --version
git version 2.16.1.windows.4

**Comment by cmpute** [comment]
vcpkg is always trying to use the latest git and cmake.
(But indeed I don't think it's necessary)

**Comment by ras0219-msft** [comment]
Thanks for posting this issue!

In this case, it was caused by an insufficient version:

>A suitable version of git was not found (required **v2.16.2**)
>git version **2.16.1**.windows.4

According to the git website, version 2.16.2 was released on 2018-02-15 [1].

[1] https://git-scm.com/downloads

**Comment by jrfl** [comment]
I guess I should have been more clear and paid more attention.  I looked at that version number at least 50 times and didn't notice the difference.  I apologize for my lack of attention.

What motivated me to report is that a very recently downloaded git-scm.com (from within the last 8 days or so) and the one installed by the latest Microsoft VS Community 2017 installer were not sufficient...

It seems unnecessarily strict, especially given the much slower pace of updates to the compiler and associated tools.  At least let me override the strictness.

**Comment by alexkaratarakis** [comment]
Your concerns are perfectly valid and we did some work to improve the situation.

Latest `master` (after 7f5efbe14419412d8c24df836a0b3b5192661aa3) consolidates the tool versions in a single [file](https://github.com/Microsoft/vcpkg/blob/master/scripts/vcpkgTools.xml). Previously, the versions were hard-coded in a 2-3 places which was bad on its own accord and it also made the required vs auto-downloaded version a bit unclear, especially when different versions of `vcpkg.exe` were involved. 

With latest `master`, the required version and auto-downloaded version can be modified in an intuitive/obvious way in the `xml`. As a bonus, you can now override the version of a tool by modifying the `requiredVersion`:

```xml
    <tool name="git">
        <requiredVersion>2.16.2</requiredVersion>
        <exeRelativePath>MinGit-2.16.2-32-bit\cmd\git.exe</exeRelativePath>
        <url>https://github.com/git-for-windows/git/releases/download/v2.16.2.windows.1/MinGit-2.16.2-32-bit.zip</url>
        <sha256>322c727e482aa97522c64a5ac68bdda3780111e8670bcfb532beac8e11ece5da</sha256>
        <archiveRelativePath>MinGit-2.16.2-32-bit.zip</archiveRelativePath>
    </tool>
```

As for the update cadence, I am mostly the one pushing for aggressive updating, but I agree that the tools are pretty stable so sometimes it can be unnecessarily strict (I will reconsider!).

**Comment by jrfl** [comment]
Thanks folks. ;)

Now, if I can just get the ports quirks worked out.... :)

**Comment by ChocoMachine** [comment]
Any way of stopping vcpkg from downloading Git, I already have it installed, I'm also behind a proxy, so it's download is failing anyways. Is there an option anywhere to bypass this?
