### ISSUE TITLE
[glm] vcpkg package install failure

### ISSUE THREAD

**Issue by yeopgi** [microsoft/vcpkg#28548]
**Host Environment**

- OS: windows10
- Compiler: msvc

**To Reproduce**

vcpkg.exe install glm:x64-windows

**Failure logs**
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/workspace/vcpkg/buildtrees/glm/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\workspace\vcpkg\buildtrees\glm\config-x64-windows-CMakeCache.txt.log
      C:\workspace\vcpkg\buildtrees\glm\config-x64-windows-CMakeCache.txt.log
      C:\workspace\vcpkg\buildtrees\glm\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:311 (vcpkg_execute_required_process)
  ports/glm/portfile.cmake:11 (vcpkg_configure_cmake)
  scripts/ports.cmake:147 (include)

error: building glm:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+glm
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[glm]+Build+error
Include '[glm] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: 6adca01a3 2022-12-22 (4 days ago)

**Additional context**
i try to install glm package. but failed..... i don't have a idea why above process failed... please help me.
log file is attached :)

[config-x64-windows-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10302174/config-x64-windows-CMakeCache.txt.log)
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/10302175/config-x64-windows-out.log)

**Comment by yeopgi** [comment]
i retry vs2022 again again... but failed.
so i try to install vs2019 but also failed..

**Comment by MonicaLiu0311** [comment]
```
PS E:\vcpkg05> ./vcpkg install glm:x64-windows --binarysource=clear
Computing installation plan...
The following packages are already installed:
    glm[core]:x64-windows -> 0.9.9.8#1
glm:x64-windows is already installed
Total install time: 912.6 us
glm provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(glm CONFIG REQUIRED)
    target_link_libraries(main PRIVATE glm::glm)
```

Sorry, I can't reproduce your problem neither with VS2019 nor VS2022...

**Comment by JackBoosY** [comment]
Did you install the English Language pack using Visual Studio Installer before?

**Comment by yeopgi** [comment]
Did you install the English Language pack using Visual Studio Installer before? 
----------------------------------------------------------------------------------------
 i don't remeber that... now VS2019 is korean language.

maybe to install using english pakcage is affecting? so please let me know some solution to solve problem :)

**Comment by yeopgi** [comment]
> ```
> PS E:\vcpkg05> ./vcpkg install glm:x64-windows --binarysource=clear
> Computing installation plan...
> The following packages will be built and installed:
>     glm[core]:x64-windows -> 0.9.9.8#1
> Detecting compiler hash for triplet x64-windows...
> Installing 1/1 glm:x64-windows...
> Building glm[core]:x64-windows...
> -- Using cached g-truc-glm-bf71a834948186f4097caa076cd2663c69a10e1e.tar.gz.
> -- Cleaning sources at E:/vcpkg05/buildtrees/glm/src/3c69a10e1e-d8f71d3bef.clean. Use --editable to skip cleaning for the packages you specify.
> -- Extracting source E:/vcpkg05/downloads/g-truc-glm-bf71a834948186f4097caa076cd2663c69a10e1e.tar.gz
> -- Using source at E:/vcpkg05/buildtrees/glm/src/3c69a10e1e-d8f71d3bef.clean
> -- Found external ninja('1.10.2').
> -- Configuring x64-windows
> -- Building x64-windows-dbg
> -- Building x64-windows-rel
> -- Installing: E:/vcpkg05/packages/glm_x64-windows/share/glm/copyright
> -- Performing post-build validation
> Elapsed time to handle glm:x64-windows: 8.089 s
> Total install time: 13.77 s
> glm provides CMake targets:
> 
>     # this is heuristically generated, and may not be correct
>     find_package(glm CONFIG REQUIRED)
>     target_link_libraries(main PRIVATE glm::glm)
> ```
> 
> Sorry, I can't reproduce your problem neither with VS2019 nor VS2022...

**Comment by JackBoosY** [comment]
> maybe to install using english pakcage is affecting?

Yeah, the English Language pack is required.

Please make sure this issue is resolved before close it.

**Comment by yeopgi** [comment]
> > maybe to install using english pakcage is affecting?
> 
> Yeah, the English Language pack is required.
> 
> Please make sure this issue is resolved before close it.

i install vs2022 english language. but vcpkg install failed...

**Comment by yeopgi** [comment]
> > maybe to install using english pakcage is affecting?
> 
> Yeah, the English Language pack is required.
> 
> Please make sure this issue is resolved before close it.

**Comment by JackBoosY** [comment]
@yeopgi Please provide the failure logs again.

**Comment by yeopgi** [comment]
@JackBoosY 
PS C:\workspace\vcpkg> .\vcpkg.exe install glm:x64-windows
Computing installation plan...
The following packages will be built and installed:
    glm[core]:x64-windows -> 0.9.9.8#1
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\dmKim\AppData\Local\vcpkg\archives in 426.2 us. Use --debug to see more details.
Installing 1/1 glm:x64-windows...
Building glm[core]:x64-windows...
-- Using cached g-truc-glm-bf71a834948186f4097caa076cd2663c69a10e1e.tar.gz.
-- Cleaning sources at C:/workspace/vcpkg/buildtrees/glm/src/3c69a10e1e-d8f71d3bef.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/workspace/vcpkg/downloads/g-truc-glm-bf71a834948186f4097caa076cd2663c69a10e1e.tar.gz
-- Using source at C:/workspace/vcpkg/buildtrees/glm/src/3c69a10e1e-d8f71d3bef.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/workspace/vcpkg/buildtrees/glm/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\workspace\vcpkg\buildtrees\glm\config-x64-windows-CMakeCache.txt.log
      C:\workspace\vcpkg\buildtrees\glm\config-x64-windows-CMakeCache.txt.log
      C:\workspace\vcpkg\buildtrees\glm\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:311 (vcpkg_execute_required_process)
  ports/glm/portfile.cmake:11 (vcpkg_configure_cmake)
  scripts/ports.cmake:147 (include)


error: building glm:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+glm
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[glm]+Build+error
Include '[glm] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: 6adca01a3 2022-12-22 (4 days ago)

Please use the prefilled template from C:\workspace\vcpkg\installed\vcpkg\issue_body.md when reporting your issue.
PS C:\workspace\vcpkg>

please see above log. thanks.
It's nothing special, sorry to bother you 

[config-x64-windows-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10303762/config-x64-windows-CMakeCache.txt.log)
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/10303763/config-x64-windows-out.log)

**Comment by JackBoosY** [comment]
I have no idea with that.
DId you install Windows SDK and using Visual Studio Installer to install Desktop core features (not the VSCode one)?

**Comment by yeopgi** [comment]
what is meaning below log??

Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
