### ISSUE TITLE
[dstorage] dstoragecore.dll is missing 

### ISSUE THREAD

**Issue by Cheaterdev** [microsoft/vcpkg#28543]
Hi!
DStorage library uses dstorage.dll and dstoragecore.dll. But vcpkg copies only dstorage.dll.
dstoragecore.dll is being loaded by dstorage library dynamically so dumpbin does not show it. Using this library leads to E_NOINTERFACE errors. I have to manually copy dstoragecore.dll to make things work.

This is my dumpbin:
```
Dump of file .\spectrum.exe

File Type: EXECUTABLE IMAGE

  Image has the following dependencies:

    GFSDK_Aftermath_Lib.x64.dll
    d3d12.dll
    dxgi.dll
    USER32.dll
    api-ms-win-shcore-scaling-l1-1-1.dll
    ole32.dll
    COMDLG32.dll
    KERNEL32.dll
    GDI32.dll
    WinPixEventRuntime.dll
    assimp-vc143-mt.dll
    DSTORAGE.dll
    zlib1.dll
    MSVCP140.dll
    CONCRT140.dll
    DWrite.dll
    VCRUNTIME140.dll
    VCRUNTIME140_1.dll
    api-ms-win-crt-locale-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-utility-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll

```

**Comment by JonLiu1993** [comment]
@Cheaterdev, Thanks for posting this issue, can you post your error log? Another point, I want to know where you manually dstoragecore.dll can work normally

**Comment by JackBoosY** [comment]
Please provide a sample code to reproduce this issue first.

**Comment by Cheaterdev** [comment]
@JackBoosY Here is the slightly modified DirectStorage Sample:
https://github.com/Cheaterdev/vcpkg_dstorage_issue

Just run and it will throw "hresult_not_implemented". After adding dstoragecore.dll it will create IDStorageFactory object successfully and exit normally. No arguments needed.

**Comment by JackBoosY** [comment]
ping @JonLiu1993

**Comment by JonLiu1993** [comment]
> 

@Cheaterdev, Thanks for the example, I'll reproduce your error locally today after I'm done with my current job and fix it.

**Comment by JonLiu1993** [comment]
@Cheaterdev, 

1. I cloned your [repository ](https://github.com/Cheaterdev/vcpkg_dstorage_issue)locally 
2. Ran HelloDirectStorage.sln using VS2022
3. Used the resulting HelloDirectStorage.exe to run the command:
4. `HelloDirectStorage.exe HelloDirectStorageRender.png` 

got this error, looks different from your error：
![image](https://user-images.githubusercontent.com/63675417/213131517-787544e7-786f-4567-a072-6a9226df0eb2.png)

**Comment by Cheaterdev** [comment]
> @Cheaterdev,
> 
> 1. I cloned your [repository ](https://github.com/Cheaterdev/vcpkg_dstorage_issue)locally
> 2. Ran HelloDirectStorage.sln using VS2022
> 3. Used the resulting HelloDirectStorage.exe to run the command:
> 4. `HelloDirectStorage.exe HelloDirectStorageRender.png`
> 
> got this error, looks different from your error： 

With debugger being attached it breaks here: 
![image](https://user-images.githubusercontent.com/3388976/213170167-af83aba3-7d71-4174-8a37-d7b1b4f3a8cd.png)

Without debugger it just proceeds to assert and I have the same error as you have. Add dstoragecore.dll and it will run OK.

**Comment by dg0yt** [comment]
> Dump of file .\spectrum.exe

If `dstoragecore.dll` is not listed by this command, vcpkg will not include it in app-local deployment. This is typical for plugins aka modules. Only very few sources of plugins are handled explicitly (qt, magnum) at the moment.

**Comment by Cheaterdev** [comment]
@dg0yt dstoragecore.dll is being dynamically loaded in the library code.

From DirectStorage SDK docs:
https://github.com/microsoft/DirectStorage/blob/main/Docs/DeveloperGuidance.md#sdk-path

**Comment by dg0yt** [comment]
Yes, it is another "module". Not yet supported for app-local deployment.

**Comment by Cheaterdev** [comment]
@dg0yt dstoragecore.dll is already in portfile.cmake of dstorage port:
```
file(COPY "${PACKAGE_PATH}/native/bin/${VCPKG_TARGET_ARCHITECTURE}/dstorage.dll" DESTINATION "${CURRENT_PACKAGES_DIR}/bin")

file(COPY "${PACKAGE_PATH}/native/bin/${VCPKG_TARGET_ARCHITECTURE}/dstoragecore.dll" DESTINATION "${CURRENT_PACKAGES_DIR}/bin")
```

I copy exactly that file to make it work. There is no specific include or library files for dstoragecore.dll - this dll is being loaded somewhere from dstorage.dll.

**Comment by dg0yt** [comment]
@Cheaterdev We only describe the issue in more detail...

1. At `dstorage` port buildtime, `dstoragecore.dll` is installed into vcpkg's `installed` tree, by explicit command in `ports/dstorage/portfile.cmake`.
2. At your project's buildtime, this DLL is not deployed side by side to your project's app (aka app-local). For regular DLLs (linked via import libs at build time) this is done by the generic script `scripts/buildsystems/msbuild/applocal.ps1`. But this mechanism doesn't handle module DLLs which are not linked to at this point.
3. At your executable's runtime, the module DLL cannot being found. `spectrum.exe` fails.

The powershell script is going to be replaced by binary code in `vcpkg` tool soon. But until now, there is no observable work on improving module/plugin support. It is a known issue.

**Comment by Cheaterdev** [comment]
> The powershell script is going to be replaced by binary code in `vcpkg` tool soon. But until now, there is no observable work on improving module/plugin support. It is a known issue.

Ok, got it. Thanks!

**Comment by JackBoosY** [comment]
Can this issue be closed now?

**Comment by Cheaterdev** [comment]
> Can this issue be closed now?

From my point of view as a user - this port is kinda useless without all required dlls to make DirectStorage work. But for now I have a workaround - I have a custom build step with cmd that copies dstoragecore.dll from vcpkg bin folder.

Maybe there is any option to warn users that they have to do some additional work? Or maybe it's time to create another port with just dstoragecore.dll?

**Comment by dg0yt** [comment]
We need a single tracking issue for "Generally support app-local deployment of plugins". Then all these issue can be pointed to that "known issue", and hopefully it is not forgotten.
(IMO the deployment tool must define how it wants to get this information, and then maintainers can take care of providing it.)

**Comment by JonLiu1993** [comment]
No stale

**Comment by JackBoosY** [comment]
I think vcpkg bug issue shouldn't be closed by stale.
