### ISSUE TITLE
[blend2d] build failure

### ISSUE THREAD

**Issue by drspam1991** [microsoft/vcpkg#28549]
**Host Environment**

- OS: Windows x64
- Compiler: MSVC 19.0.24215.1

**To Reproduce**
`vcpkg.exe install blend2d:x64-windows`

**Failure logs**
C:\vcpkg-2022.06.15>vcpkg.exe install blend2d:x64-windows
Computing installation plan...
The following packages will be built and installed:
    blend2d[core,futex,jit,logging,tls]:x64-windows -> 2022-05-02
Detecting compiler hash for triplet "x64-windows"...
Restored 0 packages from C:\Users\mohsen\AppData\Local\vcpkg\archives in 142.7 us. Use --debug to see more details.
Installing 1/1 blend2d:x64-windows...
Building blend2d[core,futex,jit,logging,tls]:x64-windows...
-- Downloading https://github.com/blend2d/blend2d/archive/0ca46df1d8ec7d8bc5250329ce281d82cfc96b99.tar.gz -> blend2d-blend2d-0ca46df1d8ec7d8bc5250329ce281d82cfc96b99.tar.gz...
-- Cleaning sources at C:/vcpkg-2022.06.15/buildtrees/blend2d/src/82cfc96b99-6755b9491a.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg-2022.06.15/downloads/blend2d-blend2d-0ca46df1d8ec7d8bc5250329ce281d82cfc96b99.tar.gz
-- Using source at C:/vcpkg-2022.06.15/buildtrees/blend2d/src/82cfc96b99-6755b9491a.clean
-- Using cached asmjit-asmjit-a4e1e88374142f4a842892f9c4bd0b0776fdcd0a.tar.gz.
-- Cleaning sources at C:/vcpkg-2022.06.15/buildtrees/blend2d/src/0776fdcd0a-c4d283eda2.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg-2022.06.15/downloads/asmjit-asmjit-a4e1e88374142f4a842892f9c4bd0b0776fdcd0a.tar.gz
-- Using source at C:/vcpkg-2022.06.15/buildtrees/blend2d/src/0776fdcd0a-c4d283eda2.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: C:/vcpkg-2022.06.15/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j5
    Working Directory: C:/vcpkg-2022.06.15/buildtrees/blend2d/x64-windows-dbg
    See logs for more information:
      C:\vcpkg-2022.06.15\buildtrees\blend2d\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/blend2d/portfile.cmake:42 (vcpkg_cmake_install)
  scripts/ports.cmake:146 (include)

error: building blend2d:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+blend2d
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[blend2d]+Build+error
Include '[blend2d] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-06-15-b0f08e40f8e8752dd0b260138ee078bd9599559c
    vcpkg-scripts version: unknown

You can also use the prefilled template from C:\vcpkg-2022.06.15\installed\vcpkg\issue_body.md.

**Additional context**
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/10302836/config-x64-windows-out.log)
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/10302837/install-x64-windows-dbg-out.log)

**Comment by FrankXie05** [comment]
Please install MSVC build tools in Visual Studio Installer.
![image](https://user-images.githubusercontent.com/65999885/209633084-5a484fa7-111f-4107-b99c-da43c0d65f34.png)

`C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe`

**Comment by FrankXie05** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
