### ISSUE TITLE
[gmp] Build error

### ISSUE THREAD

**Issue by Sasinas-Alias-Haritha** [microsoft/vcpkg#28550]
Package: gmp[core]:x64-windows -> 6.2.1#14

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.34.31937.0
-    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: 6adca01a3 2022-12-22 (4 days ago)

**To Reproduce**

`vcpkg install cgal`

**Failure logs**

```
-- Using cached gmp-6.2.1.tar.xz.
-- Using cached gmp-arm64-asm-fix-5f32dbc41afc.patch.
-- Cleaning sources at C:/Users/Sasinas A Haritha/vcpkg/buildtrees/gmp/src/v6.2.1-0c723d4b6f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Sasinas A Haritha/vcpkg/downloads/gmp-6.2.1.tar.xz
-- Applying patch asmflags.patch
-- Applying patch cross-tools.patch
-- Applying patch subdirs.patch
-- Applying patch msvc_symbol.patch
-- Applying patch arm64-coff.patch
-- Applying patch C:/Users/Sasinas A Haritha/vcpkg/downloads/gmp-arm64-asm-fix-5f32dbc41afc.patch
-- Using source at C:/Users/Sasinas A Haritha/vcpkg/buildtrees/gmp/src/v6.2.1-0c723d4b6f.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Using cached LLVM-12.0.0-win64.7z.exe.
-- Using cached 7z1900.msi.
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:700 (message):
  Unable to find 7Z
Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:667 (vcpkg_find_acquire_program)
  ports/gmp/portfile.cmake:62 (vcpkg_find_acquire_program)
  scripts/ports.cmake:147 (include)

**Comment by MonicaLiu0311** [comment]
I can't reproduce your issue locally, please check whether `7Z/` exists in the `vcpkg/downloads/tools` directory.

**Comment by Sasinas-Alias-Haritha** [comment]
> 

Yes, 7z folder is there but it is empty.

**Comment by MonicaLiu0311** [comment]
Could you please delete `vcpkg/downloads/7z1900.msi` and `vcpkg/downloads/tools/7Z/`, then run the following command and try again?
`./vcpkg remove gmp --recurse`
`./vcpkg install gmp --binarysource=clear`

**Comment by Sasinas-Alias-Haritha** [comment]
Package: gmp[core]:x64-windows -> 6.2.1#14

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.34.31937.0
-    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: ecce05107 2022-12-28 (2 hours ago)

**To Reproduce**

`vcpkg install gmp`

**Failure logs**

```
-- Downloading http://gmplib.org/download/gmp/gmp-6.2.1.tar.xz -> gmp-6.2.1.tar.xz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
Downloading http://gmplib.org/download/gmp/gmp-6.2.1.tar.xz
warning: Download failed -- retrying after 1000ms
warning: Download failed -- retrying after 2000ms
warning: Download failed -- retrying after 4000ms
error: Failed to download from mirror set
error: http://gmplib.org/download/gmp/gmp-6.2.1.tar.xz: WinHttpReceiveResponse failed with exit code 12175
error: http://gmplib.org/download/gmp/gmp-6.2.1.tar.xz: WinHttpReceiveResponse failed with exit code 12175
error: http://gmplib.org/download/gmp/gmp-6.2.1.tar.xz: WinHttpReceiveResponse failed with exit code 12175
error: http://gmplib.org/download/gmp/gmp-6.2.1.tar.xz: WinHttpReceiveResponse failed with exit code 12175
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(956): 
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 3 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 5901 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 9.748 s (9727777 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. Your proxy's remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:273 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/gmp/portfile.cmake:7 (vcpkg_download_distfile)
  scripts/ports.cmake:147 (include)

**Comment by acgetchell** [comment]
I can confirm, all of my CI builds stopped working when the SSL cert for gmplib.org expired:

https://github.com/acgetchell/CDT-plusplus/actions

**Comment by MonicaLiu0311** [comment]
I successfully installed locally, please try https://github.com/microsoft/vcpkg/issues/28602 to solve your issue.

**Comment by FrankXie05** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
This issue hasn’t been updated a long time; if it is still an issue, please reopen it.

**Comment by X1ehua** [comment]
I fixed the boring 'Unable to find 7Z' by running the cmd terminal with Administrator

**Comment by dg0yt** [comment]
> I fixed the boring 'Unable to find 7Z' by running the cmd terminal with Administrator

@X1ehua I would clearly discourage running running vcpkg with Administrator for most tasks. And the original issue is that port gmp actually wants to use use clang-cl from Visual Studio, so LLVM/clang should be installed with the Visual Studio installer, not left for download with vcpkg.

**Comment by X1ehua** [comment]
> > I fixed the boring 'Unable to find 7Z' by running the cmd terminal with Administrator
> 
> @X1ehua I would clearly discourage running running vcpkg with Administrator for most tasks. And the original issue is that port gmp actually wants to use use clang-cl from Visual Studio, so LLVM/clang should be installed with the Visual Studio installer, not left for download with vcpkg.

I wasn't use from Visual Studio but vcpkg install in the cmd terminal. By the way, what is the potential harmness by Admin?

**Comment by dg0yt** [comment]
> By the way, what is the potential harmness by Admin?

Immediate security implications by running unknown downloaded build scripts.
Hiding actual bugs and proper solutions.
Potentially affecting permissions of newly created files and directories, thus adding admin privilege requirements for subsequent actions, proliferating the security problem.
