### ISSUE TITLE
vcpkg integrate breaks building of other C++ projects

### ISSUE THREAD

**Issue by rchiodo** [Microsoft/vcpkg#2855]
I get this error after integrate:

Error	C1083	Cannot open source file: '. /ZI /nologo /W3 /WX /diagnostics:classic /Od /Oy- /D _DEBUG /D WIN32 /D VSDEBUGENG_USE_CPP11_SCOPED_ENUMS /D GET_DEFINITION_OF_CLASS_NEEDED=0 /D EXTRA_SOURCE_POSITIONS_IN_IL=1 /D SUPPORT_NATIVE_EE=1 /D DEFAULT_ALLOW_DOLLAR_IN_ID_CHARS=1 /D DEFAULT_RVALUE_REFERENCES_ENABLED=1 /D DEFAULT_EXCEPTIONS_ENABLED=0 /D DEFAULT_RTTI_ENABLED=0 /D DEFAULT_ALLOW_NONCONST_CALL_ANACHRONISM=1 /D CPPCLI_SUPPORTED=1 /D GENERATE_SOURCE_SEQUENCE_LISTS=0 /D IL_SHOULD_BE_WRITTEN_TO_FILE=0 /D MAINTAIN_IL_IN_MEMORY_WHEN_WRITTEN_TO_FILE=0 /D DO_IL_LOWERING=0 /D DEFAULT_STRING_LITERALS_ARE_CONST=0 /D PARENS_IN_IL=1 /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t- /Zc:forScope /Zc:inline /Ycstdafx.h /FpD:\CppEE\src\..\intermediate\CppEELib\x86\Debug\CppEELib.pch /FoD:\CppEE\src\..\intermediate\CppEELib\x86\Debug\ /FdD:\CppEE\src\..\intermediate\CppEELib\x86\Debug\CppEELib.pdb /Gz /TP /analyze- /FC /errorReport:prompt lib\stdafx.cpp': No such file or directory	CppEELib	D:\CppEE\src\c1xx	1	

It looks like the include paths created by vcpkg are messing up the command line for any other project.

vcpkg integrate remove fixes the problem.

**Comment by JackBoosY** [comment]
Hi @rchiodo , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
