### ISSUE TITLE
[qt5-local] Build error

### ISSUE THREAD

**Issue by harishc3** [microsoft/vcpkg#28555]
I am getting the following error while I build through cmake and I am getting the command successful on cmd.exe normally

Can someone please help me on this issue.
@JackBoosY looking for your comment on this.

Package: qt5-local[core]:x86-windows -> 5.15.0
**Host Environment**
- Host: x64-windows
- Compiler: MSVC 19.29.30147.0
-    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: 3908a2e18 2022-08-17 (4 months ago)

**To Reproduce**
`vcpkg install `

**Failure logs**
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: az artifacts universal download --organization https://dev.azure.com/hexagonmi/ --project=VTD --scope project --feed Test-VTDFeed --name qt5_windows_10 --version 5.15.0 --path C:/Users/harish.chinthagindhi/CloneRepo/Vcpkg/buildtrees/qt5-local/qt5-local
    Working Directory: C:/Users/harish.chinthagindhi/CloneRepo/Vcpkg/buildtrees/qt5-local
    Error code: The system cannot find the file specified
    See logs for more information:

Call Stack (most recent call first):
  C:/Users/harish.chinthagindhi/AppData/Local/vcpkg/registries/git-trees/5b4f3bfa61e5b6227d709e23fcb2329d9d95e21b/portfile.cmake:41 (vcpkg_execute_required_process)
  scripts/ports.cmake:147 (include)

**Comment by JackBoosY** [comment]
cc @Neumann-A

**Comment by Neumann-A** [comment]
@JackBoosY there is no port with that name in vcpkg

**Comment by harishc3** [comment]
Created a new port file and calling from another repo and trying to installing it with cmake and vcpkg

**Comment by harishc3** [comment]
@Neumann-A 
while I am running this downloading feed successfully but getting the error only through **vcpkg.exe install --x-install-root=./vcpkg_installed** on this particular port file on the repo
 
---->.
az artifacts universal download --organization https://dev.azure.com/hexagonmi/ --project=VTD --scope project --feed Test-VTDFeed --name qt5_windows_10 --version 5.15.0 --path C:/Users/harish.chinthagindhi/CloneRepo/Vcpkg/buildtrees/qt5-local/qt5-local
{
  "Description": "QT 5 binaries for windows 10",
  "ManifestId": "096133FCD1612639605998F1E030410948C3B9AD5AFE0EF8F8B1C7959BBE135E02",
  "PackageSize": 675622961,
  "SuperRootId": "34924FA14F72B933B648F1F5B4BB4775201577734D3244F19C3BD2122315036802",
  "Version": "5.15.0"
}

**Comment by JackBoosY** [comment]
Provide the full portfile.cmake may get more helps.

**Comment by harishc3** [comment]
@JackBoosY,
#this is the profile.cmake file

file(REMOVE_RECURSE "${CURRENT_BUILDTREES_DIR}/nuget")

set(NUGET_PACKAGE_VERSION "5.15.0")

#windows setup
set(tool_subdirectory)
set(NUGET_EXE)
set(NUGET_PACKAGE_NAME)

set(SOURCE_FOLDER "${CURRENT_BUILDTREES_DIR}/qt5-local")
if(UNIX)
    find_program(LSB_RELEASE_EXEC lsb_release)
    execute_process(COMMAND ${LSB_RELEASE_EXEC} -is
        OUTPUT_VARIABLE LSB_RELEASE_ID_SHORT
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
    set(tool_subdirectory "5.11.0-linux")
    set(NUGET_EXE "${DOWNLOADS}/tools/nuget-${tool_subdirectory}/nuget.exe")
    if (LSB_RELEASE_ID_SHORT STREQUAL "openSUSE")
        set(NUGET_PACKAGE_NAME "qt5_opensuse")
    elseif(LSB_RELEASE_ID_SHORT STREQUAL "Ubuntu")
        execute_process(COMMAND ${LSB_RELEASE_EXEC} -rs
            OUTPUT_VARIABLE LSB_RELEASE_VERSION_SHORT
            OUTPUT_STRIP_TRAILING_WHITESPACE
        )
        set(NUGET_PACKAGE_NAME "qt5_ubuntu_${LSB_RELEASE_VERSION_SHORT}")
    endif()
    
    vcpkg_execute_required_process(
        COMMAND az artifacts universal download --organization https://dev.azure.com/hexagonmi/ --project=VTD --scope project --feed Test-VTDFeed --name ${NUGET_PACKAGE_NAME} --version ${NUGET_PACKAGE_VERSION} --path ${SOURCE_FOLDER}

        WORKING_DIRECTORY "${CURRENT_BUILDTREES_DIR}"
        LOGNAME nuget-${TARGET_TRIPLET}
    )
    
elseif(WIN32)
    set(tool_subdirectory "5.11.0-windows")
    set(NUGET_EXE "${DOWNLOADS}/tools/nuget-${tool_subdirectory}/nuget.exe")
    set(NUGET_PACKAGE_NAME "qt5_windows_10")
    
    vcpkg_execute_required_process(
        COMMAND az artifacts universal download --organization https://dev.azure.com/hexagonmi/ --project=VTD --scope project --feed Test-VTDFeed --name ${NUGET_PACKAGE_NAME} --version ${NUGET_PACKAGE_VERSION} --path ${SOURCE_FOLDER}

        WORKING_DIRECTORY "${CURRENT_BUILDTREES_DIR}"
        LOGNAME nuget-${TARGET_TRIPLET}
    )
endif()

# Here copy whatever you want from SOURCE_FOLDER (extracted package) into CURRENT_PACKAGES_DIR
file(COPY ${SOURCE_FOLDER}/  DESTINATION "${CURRENT_PACKAGES_DIR}")

**Comment by autoantwort** [comment]
You are using 
```
vcpkg_execute_required_process(
    COMMAND az artifacts universal download --organization https://dev.azure.com/hexagonmi/ --project=VTD --scope project --feed Test-VTDFeed --name ${NUGET_PACKAGE_NAME} --version ${NUGET_PACKAGE_VERSION} --path ${SOURCE_FOLDER}

    WORKING_DIRECTORY "${CURRENT_BUILDTREES_DIR}"
    LOGNAME nuget-${TARGET_TRIPLET}
)
```
and it complains that the commant `az` is unknown. You have to fix that on your end.

**Comment by harishc3** [comment]
@autoantwort ,

Please suggest what needs to be added to execute az commands and I am also similar issue on executing nuget command as well

COMMAND ${NUGET_EXE} install ${NUGET_PACKAGE_NAME} -Version ${NUGET_PACKAGE_VERSION} -OutputDirectory ${DIR} -Source Test-VTDFeed -packagesavemode nuspec

Please guide me on further things needed to fix this error.

**Comment by autoantwort** [comment]
Can you execute the command on the command line?

**Comment by harishc3** [comment]
yes, both are working fine on command line

**Comment by autoantwort** [comment]
Maybe print the path and check if it is correct

**Comment by harishc3** [comment]
validated the path and it is existing, no issue on variables

**Comment by autoantwort** [comment]
Then I don't know what the problem could be

**Comment by Neumann-A** [comment]
PATH gets cleaned on windows. Try to use 'vcpkg env' and execute the command in there.

**Comment by harishc3** [comment]
you mean to set VCPKG_BINARY_SOURCES ?

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
