### ISSUE TITLE
SPDX JSON output should include the documentDescribes property

### ISSUE THREAD

**Issue by goneall** [microsoft/vcpkg#28562]
**Describe the bug**
When using the `--x-json` option, the generated SPDX does not include the `documentDescribes` property nor a `DESCRIBES` relationship between the SPDX Document and the package described by the SPDX document as required by the spec.

**Environment**
- OS: all (Window 11 used in the generated examples)
- Compiler: any

**To Reproduce**
1. ./vcpkg install z3 --x-json
2. See attached SPDX JSON output [vcpkg.spdx.json.txt](https://github.com/microsoft/vcpkg/files/10304594/vcpkg.spdx.json.txt) and the following snippet:

```
...
  "creationInfo": {
    "creators": [
      "Tool: vcpkg-7ae0d8527fb488fde10a89c2813802dc9b03b6f9"
    ],
    "created": "2022-12-21T11:11:00Z"
  },
  "relationships": [
...
```

**Expected behavior**
See attached corrected SPDX JSON file [vcpkg-z3-with-describes.spdx.json.txt](https://github.com/microsoft/vcpkg/files/10304612/vcpkg-z3-with-describes.spdx.json.txt) and the following snippet:

```
...
  "creationInfo": {
    "creators": [
      "Tool: vcpkg-7ae0d8527fb488fde10a89c2813802dc9b03b6f9"
    ],
    "created": "2022-12-26T18:55:14Z"
  },
  "documentDescribes" : [ "SPDXRef-port" ],
  "relationships": [
...
```

**Additional context**

This is an admittedly confusing area of the SPDX Spec (which we plan to fix in SPDX 3.0).  The `DESCRIBES` relationship is necessary for some tools which need a starting point for package relationship analysis (see [this spdx-to-osv comment](https://github.com/spdx/spdx-to-osv/issues/16#issuecomment-1364574204) for an example).  The spec requires a `DESCRIBES` relationship between the SPDX Document and one or more packages and/or files if there is more than one package present in the SPDX document.

In October, we updated the JSON schema to have a `documentDescribes` property which can be used interchangeably with a describes relationship.

Spec Reference: See the `DESCRIBES` relationship in [Annex 11](https://github.com/spdx/spdx-spec/blob/development/v2.3.1/chapters/relationships-between-SPDX-elements.md).

JSON Schema Reference: https://github.com/spdx/spdx-spec/blob/efa69656db9db4fcc871de563cbbd104fc1e33c3/schemas/spdx-schema.json#L219

For an example - see https://github.com/spdx/spdx-spec/blob/efa69656db9db4fcc871de563cbbd104fc1e33c3/examples/SPDXJSONExample-v2.3.spdx.json#L59

**Comment by goneall** [comment]
Bump - if this issue is resolved, please close

**Comment by goneall** [comment]
Bump - if this issue is resolved, please close

**Comment by goneall** [comment]
Bump - if this issue is resolved, please close

**Comment by LilyWangLL** [comment]
Sorry for the late reply. There has been a significant change in the `vcpkg.spdx.json` files created after each port installation in vcpkg. These files are located in _[VCPKG_ROOT]/installed/x64-windows/share/${PORT}/vcpkg.spdx.json_ and include the following parameters. I believe this issue has been resolved, so I will close this issue.

```
  "spdxVersion": "SPDX-2.2",
  "dataLicense": "CC0-1.0",
  "SPDXID": "SPDXRef-DOCUMENT",
  "documentNamespace": "https://spdx.org/spdxdocs/zstd-x64-windows-1.5.6-11c390cc-7b44-4a2e-80d1-0b27e62d4b3a",
  "name": "zstd:x64-windows@1.5.6 f0ba06aed607b988f96daeddc8fdd3ce2b8dc396197b7d77a5a93a967a570dda",
......
  "packages": [
    {
      "name": "zstd",
      "SPDXID": "SPDXRef-port",
      "versionInfo": "1.5.6",
      "downloadLocation": "git+https://github.com/Microsoft/vcpkg#ports/zstd",
      "homepage": "https://facebook.github.io/zstd/",
      "licenseConcluded": "BSD-3-Clause OR GPL-2.0-only",
      "licenseDeclared": "NOASSERTION",
      "copyrightText": "NOASSERTION",
      "description": "Zstandard - Fast real-time compression algorithm",
      "comment": "This is the port (recipe) consumed by vcpkg."
    },
```
