### ISSUE TITLE
[ceres] Build error ceres in Linux Mint 21

### ISSUE THREAD

**Issue by mxhsnowy** [microsoft/vcpkg#28573]
Hi, I'm having a trouble installing ceres
**Host Environment**

- OS: Linux Mint 21
- Compiler: gcc 11.3.0

**To Reproduce**

`./vcpkg install ceres`

**Failure logs**

`CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
 Command failed: /home/hsxm/Libraries/vcpkg/downloads/tools/cmake-3.25.0-linux/cmake-3.25.0-linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j17
    Working Directory: /home/hsxm/Libraries/vcpkg/buildtrees/ceres/x64-linux-dbg
    See logs for more information:
      /home/hsxm/Libraries/vcpkg/buildtrees/ceres/install-x64-linux-dbg-out.log
`
`Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/ceres/portfile.cmake:60 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)
`

**Additional context**
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/10306836/install-x64-linux-dbg-out.log)

**Comment by FrankXie05** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
