### ISSUE TITLE
Restoring packages is slow in x64-osx CI

### ISSUE THREAD

**Issue by dg0yt** [microsoft/vcpkg#28582]
Restoring cached package in vcpkg CI takes much longer for x64-osx. E.g.
https://dev.azure.com/vcpkg/public/_build/results?buildId=82899&view=logs&j=7922e5c4-0103-5f8f-ad17-45ce9bb98e80&t=66eef212-08d6-5e6c-a560-7d01149d0188&l=6237 
 - x64-windows: Restored 64 package(s) from HTTP servers in 18.47 s.
 - x64-linux: Restored 115 package(s) from HTTP servers in 2.795 min.
 - x64-osx: Restored 60 package(s) from HTTP servers in 4.589 min.

**Comment by Thomas1664** [comment]
@dg0yt Unfortunately, there is nothing we can do about this. The previous approach was to run failed unzip operations again which didn't work well. See https://github.com/microsoft/vcpkg-tool/pull/842 and https://github.com/microsoft/vcpkg-tool/pull/695 for more details.

**Comment by autoantwort** [comment]
I don't think that it has something to do with the mutextes. I guess the osx ci machines are simply a lot slower because the hardware is worse

**Comment by dg0yt** [comment]
I didn't want to jump into conclusions.

> I guess the osx ci machines are simply a lot slower because the hardware is worse

Sounds reasonable. After reducing a `qt5` dependency to `qt5-base` for the same PR, I see
 - x64-windows: Restored 49 package(s) from HTTP servers in 12 s.
 - x64-linux: Restored 107 package(s) from HTTP servers in 2.518 min.
 - x64-osx: Restored 46 package(s) from HTTP servers in 40.6 s.

I would take this as an indication the the time scales more with the total size in bytes than with the number of packages.

**Comment by FrankXie05** [comment]
We really can't make changes for this new device in a short period of time. :(

> I don't think that it has something to do with the mutextes. I guess the osx ci machines are simply a lot slower because the hardware is worse

We really can't make changes for this new device in a short period of time.


> I would take this as an indication the the time scales more with the total size in bytes than with the number of packages.

Thanks for the data. Different systems are built and handle bytes differently and the way the port is built is determined upstream, even if we update the machine it won't solve the problem.

According to the time policy, I need to close it. Because I think you have found the answer. (even if it is not perfect)
