### ISSUE TITLE
[libigl] update to v2.4.0

### ISSUE THREAD

**Issue by Nosenzor** [microsoft/vcpkg#28584]
Library name: libigl

New version number: 2.4.0

Other information that may be useful (release notes, etc...)
https://github.com/libigl/libigl/releases/tag/v2.4.0
This version perfectly work on Mac ARM too so please enable the port on Mac ARM

**Comment by FrankXie05** [comment]
Will be fixed by PR https://github.com/microsoft/vcpkg/pull/27963

**Comment by FrankXie05** [comment]
Duplicate of issue: https://github.com/microsoft/vcpkg/issues/23354
