### ISSUE TITLE
static library linking and dynamic crt linking

### ISSUE THREAD

**Issue by DrPingy** [Microsoft/vcpkg#2858]
I will build openimageio lib with static library linking and dynamic crt linking.
So I made a new triplet "x64-windows-static-md.cmake":
  set(VCPKG_TARGET_ARCHITECTURE x64)
  set(VCPKG_CRT_LINKAGE dynamic)
  set(VCPKG_LIBRARY_LINKAGE static)

This was described in many issues and the doc.
All dependencies built fine, like boost.
But the library openimageio failed.
In openimageio CMakeLists.txt is hard coded: 
    if (WIN32)
        set (CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /MT")
        set (CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} /MTd")
    endif ()

I overwrite /MT with /MD and it works!

How can I set in a triplet this setting?
SET(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} "/MD"") doesn't work!

**Comment by ras0219-msft** [comment]
Thanks for posting!

We'll need to patch those lines out of the `CMakeLists.txt` entirely. Here's an example document for how to do that: https://github.com/Microsoft/vcpkg/blob/ef9d50ecb3a968062f1d7e47c3aa27e924eadf44/docs/examples/patching-libpng.md

I'd love to see a PR!

**Comment by DrPingy** [comment]
Thanks for the fast Reply!
I have used the example and got the patch "x64-windows-static-md.patch":
`diff --git a/CMakeLists.txt b/CMakeLists.txt
index 66eb14c..9098f89 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -334,8 +334,8 @@ if (BUILDSTATIC)
         set (USE_PYTHON3 OFF)
     endif ()
     if (WIN32)
-        set (CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /MT")
-        set (CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} /MTd")
+        set (CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /MD")
+        set (CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} /MDd")
     endif ()
 endif()
 `
In portfile cmake I insert:
`vcpkg_apply_patches(
	SOURCE_PATH ${CURRENT_BUILDTREES_DIR}/src/oiio-Release-1.7.15
	PATCHES "${CMAKE_CURRENT_LIST_DIR}/x64-windows-static-md.patch"
 )`

How can I use the patch only for static md?
I tried:
`if(VCPKG_LIBRARY_LINKAGE STREQUAL "static") 
	elseif(VCPKG_CRT_LINKAGE STREQUAL "dynamic")
		vcpkg_apply_patches(
			SOURCE_PATH ${CURRENT_BUILDTREES_DIR}/src/oiio-Release-1.7.15
			PATCHES "${CMAKE_CURRENT_LIST_DIR}/x64-windows-static-md.patch"
		)
endif()
`
or 
`if(VCPKG_LIBRARY_LINKAGE STREQUAL static) 
	elseif(VCPKG_CRT_LINKAGE STREQUAL dynamic)
		vcpkg_apply_patches(
			SOURCE_PATH ${CURRENT_BUILDTREES_DIR}/src/oiio-Release-1.7.15
			PATCHES "${CMAKE_CURRENT_LIST_DIR}/x64-windows-static-md.patch"
		)
endif()
`
but it doesn't work. The patch will never applied.
