### ISSUE TITLE
[Ceres] update to <2.2.0>

### ISSUE THREAD

**Issue by GJC1979** [microsoft/vcpkg#28588]
Library name: Ceres

New version number: 2.2.0

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. The [upstream](https://github.com/ceres-solver/ceres-solver) has not release version 2.2.0 of `Ceres`.

**Comment by LilyWangLL** [comment]
Since the upstream has not release version 2.2.0, so I am closing this issue for now.
