### ISSUE TITLE
[skia] build failure

### ISSUE THREAD

**Issue by xiaozhuai** [microsoft/vcpkg#28589]
*Host Environment**

- OS: macOS

When there is no python in the path. the error occured.
I have only python3 in my path.

Then I create a symbol link named python to python3, it works.

**Failure logs**
```
ERROR at //BUILD.gn:1050:7: Script returned non-zero exit code.
      exec_script("gn/checkpath.py",
      ^----------
Current dir: /Users/xiaozhuai/vcpkg/vcpkg/buildtrees/skia/x64-osx-dbg/
Command: python /Users/xiaozhuai/vcpkg/vcpkg/buildtrees/skia/src/40cd0870fd-9a1054ffad.clean/gn/checkpath.py ../src/40cd0870fd-9a1054ffad.clean/third_party/externals/libgifcodec/libgifcodec.gni
Returned 127.
```

**Comment by dg0yt** [comment]
This implies that in vcpkg CI, there is a python3 in the PATH.
The port already passes the python executable via an option (variable). IIRC, there is also a direct parameter to gn for setting the script executable.

**Comment by xiaozhuai** [comment]
> This implies that in vcpkg CI, there is a python3 in the PATH. The port already passes the python executable via an option (variable). IIRC, there is also a direct parameter to gn for setting the script executable.

If user has only `python3` in their path, it fails. It seems the problem is from `vcpkg-tool-gn`

**Comment by dg0yt** [comment]
~~~
$ gn help switches
[...]
  --script-executable: Set the executable used to execute scripts.
~~~
This is what should be set to the python3 executable when running `gn`. It even sets the global `script_exectutable` variable.

**Comment by xiaozhuai** [comment]
> ```
> $ gn help switches
> [...]
>   --script-executable: Set the executable used to execute scripts.
> ```
> 
> This is what should be set to the python3 executable when running `gn`. It even sets the global `script_exectutable` variable.

I didn't install gn. I think this should be handle by vcpkg.

**Comment by dg0yt** [comment]
> I didn't install gn. I think this should be handle by vcpkg.

Sure. I just take notes for someone who is willing to do the work.

**Comment by oouxx** [comment]
Any solution for this?
