### ISSUE TITLE
[libxml2] update to 2.10.3

### ISSUE THREAD

**Issue by comor86** [microsoft/vcpkg#28592]
Library name: libxml2

New version number: 2.10.3

Other information that may be useful (release notes, etc...)

https://gitlab.gnome.org/GNOME/libxml2/-/releases

**Comment by comor86** [comment]
The result of `vcpkg search libxml2` is ok now, but web search results still 2.9.14
![image](https://user-images.githubusercontent.com/17661301/209898001-2c09d0c3-4df4-43a8-83c9-10c4ce75be37.png)

**Comment by FrankXie05** [comment]
Thank you [dg0yt](https://github.com/dg0yt) for your answer. And @comor86 our November update plan is done, but temporarily blocked due to some other issues. We will fix it and update soon. :)

**Comment by JonLiu1993** [comment]
@comor86, libxml2 has been updated to 2.10.3 via PR https://github.com/microsoft/vcpkg/pull/28261, for https://gitlab.gnome.org/GNOME/libxml2/-/release 2.9. 14 is a known issue as we have some issues with our vcpkg.io pipeline, we will fix this and update the libxml2 version.
