### ISSUE TITLE
[grpc] build failure | failed to cross compile gRPC on macOS arm64 host

### ISSUE THREAD

**Issue by AbdulAbCellera** [microsoft/vcpkg#28595]
Package: grpc[codegen,core]:x64-osx-custom -> 1.50.1

**Host Environment**

- Host: arm64-osx
- Compiler: AppleClang 14.0.0.14000029
-    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: a0cd24633 2022-12-27 (29 hours ago)

**To Reproduce**

`vcpkg install `

**Failure logs**

```
-- Using cached grpc-grpc-v1.50.1.tar.gz.
-- Extracting source /<repo_root>/vcpkg_download/grpc-grpc-v1.50.1.tar.gz
-- Applying patch 00001-fix-uwp.patch
-- Applying patch 00002-static-linking-in-linux.patch
-- Applying patch 00003-undef-base64-macro.patch
-- Applying patch 00004-link-gdi32-on-windows.patch
-- Applying patch 00005-fix-uwp-error.patch
-- Applying patch 00009-use-system-upb.patch
-- Applying patch snprintf.patch
-- Applying patch 00012-fix-use-cxx17.patch
-- Applying patch 00014-pkgconfig-upbdefs.patch
-- Applying patch 00015-disable-download-archive.patch
-- Using source at /<repo_root>/vcpkg/buildtrees/grpc/src/v1.50.1-1b126aed1d.clean
-- Found external ninja('1.11.1').
-- Configuring x64-osx-custom
-- Building x64-osx-custom-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: /<repo_root>/vcpkg_download/tools/cmake-3.25.0-osx/cmake-3.25.0-macos-universal/CMake.app/Contents/bin/cmake --build . --config Debug --target install -- -v -j11
    Working Directory: /<repo_root>/vcpkg/buildtrees/grpc/x64-osx-custom-dbg
    See logs for more information:
      /<repo_root>/vcpkg/buildtrees/grpc/install-x64-osx-custom-dbg-err.log

Call Stack (most recent call first):
  /<repo_root>/vcpkg_installed/x64-osx-custom/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  /<repo_root>/vcpkg_installed/x64-osx-custom/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  buildtrees/versioning_/versions/grpc/13420572b45b2b5a5a3fb41eb383d0c62f1d7c51/portfile.cmake:69 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)



```
<details><summary>/<repo_root>/vcpkg/buildtrees/grpc/install-x64-osx-custom-dbg-err.log</summary>

```
ninja: error: '_gRPC_CPP_PLUGIN-NOTFOUND', needed by '/<repo_root>/vcpkg/buildtrees/grpc/x64-osx-custom-dbg/gens/src/proto/grpc/reflection/v1alpha/reflection.pb.cc', missing and no known rule to make it
```
</details>

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json",
  "name": "proj",
  "version": "1.0.0.0",
  "builtin-baseline": "a0cd246334a33107cdef4f701b0b532a71514b19",
  "dependencies": [
    {
      "name": "grpc",
      "version>=": "1.50.1",
      "features": [
        "codegen"
      ]
    }
  ]
}

```
</details>

also documented here  https://github.com/microsoft/vcpkg/discussions/28594

I have the following triplets:

x64-osx-custom triplet:
- `set(VCPKG_TARGET_ARCHITECTURE x64)`
- `set(VCPKG_OSX_ARCHITECTURES x86_64)`
- `set(VCPKG_CMAKE_SYSTEM_NAME Darwin)`
- `set(VCPKG_CRT_LINKAGE dynamic)`
- `set(VCPKG_LIBRARY_LINKAGE static)`

arm64-osx-custom triplet:
- `set(VCPKG_TARGET_ARCHITECTURE arm64)`
- `set(VCPKG_OSX_ARCHITECTURES arm64)`
- `set(VCPKG_CMAKE_SYSTEM_NAME Darwin)`
- `set(VCPKG_CRT_LINKAGE dynamic)`
- `set(VCPKG_LIBRARY_LINKAGE static)`

in the main CMakeLists.txt before any call to `project()` I set:
- `set(VCPKG_TARGET_TRIPLET x64-osx-custom)`
- `set(VCPKG_HOST_TRIPLET x64-osx-custom)` 
   - accourding to https://github.com/microsoft/vcpkg/issues/22476
   - and https://github.com/microsoft/vcpkg/issues/16504
   - and https://github.com/microsoft/vcpkg/issues/17436

When I set `VCPKG_HOST_TRIPLET` to `arm64-osx-custom` gRPC builds.

**Comment by Tradias** [comment]
I do not understand what the issue is. You of course cannot compile with a host triplet that does not match your host system because gRPC has to execute just-compiled binaries during its build process. If those binaries are compiled for x86 while you are on arm64 then they won't work. Well, they might work because of emulation but vcpkg and CMake do not make that assumption.
Therefore, the expected use is:
`set(VCPKG_TARGET_TRIPLET x64-osx-custom)`
`set(VCPKG_TARGET_TRIPLET arm64-osx-custom)`
which should result in a compilation of gRPC tools (like `protoc-gen-grpc`) for arm64 and everything else for x86 (like gRPC static library). Is that not what is happening?

**Comment by AbdulAbCellera** [comment]
> I do not understand what the issue is. You of course cannot compile with a host triplet that does not match your host system because gRPC has to execute just-compiled binaries during its build process. If those binaries are compiled for x86 while you are on arm64 then they won't work. Well, they might work because of emulation but vcpkg and CMake do not make that assumption. Therefore, the expected use is: `set(VCPKG_TARGET_TRIPLET x64-osx-custom)` `set(VCPKG_TARGET_TRIPLET arm64-osx-custom)` which should result in a compilation of gRPC tools (like `protoc-gen-grpc`) for arm64 and everything else for x86 (like gRPC static library). Is that not what is happening?

Thanks for clarifying. If I am not mistaken, I think you have a typo in one of the variable names.

**Comment by Tradias** [comment]
Indeed, I mean to write
`set(VCPKG_HOST_TRIPLET arm64-osx-custom)`
`set(VCPKG_TARGET_TRIPLET x64-osx-custom)`

**Comment by AbdulAbCellera** [comment]
related to https://github.com/microsoft/vcpkg/discussions/29386
