### ISSUE TITLE
Enable vcpkg to continue interrupted install

### ISSUE THREAD

**Issue by leg0** [microsoft/vcpkg#28603]
****

**Is your feature request related to a problem? Please describe.**
I'm trying to use llvm from vcpkg. Building this takes forever. The lengthy build itself is not the problem, but a problem is that when for example, the computer crashes during the build, or I shutdown the computer without remembering that I am running a lengthy build, I lose all the work that has been done. When next time I run `vcpkg install`, vcpkg is not able to pick up the work where it left off, instead it cleans up whatever it had produced, and starts from the beginning.

**Proposed solution**
When a build was interrupted for whatever reason other than build failure, it should be possible to continue the build from where it was interrupted. If not by default, then at least enable continuation with a command line flag.

**Comment by FrankXie05** [comment]
@leg0 Thanks for posting this issue. 
This is a good idea, but it can't be implemented. Because the build process of the port is implemented by the upstream code structure. Distributing the build means that a `lib` or `dll` build needs to be split, which is not allowed. :(

**Comment by FrankXie05** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
