### ISSUE TITLE
Vcpkg does not report about missing dependencies

### ISSUE THREAD

**Issue by pravic** [Microsoft/vcpkg#2861]
For example:

> Starting package 2/2: cpr:x86-windows
Building package cpr[core,winssl]:x86-windows...
Error: Building package cpr:x86-windows failed with: CASCADED_DUE_TO_MISSING_DEPENDENCIES

I am not sure about a proper way to fix this, may be print them inside the `perform_install_plan_action`:

```diff
diff --git a/toolsrc/src/vcpkg/install.cpp b/toolsrc/src/vcpkg/install.cpp
index 46c7c53b..f5c58bf9 100644
--- a/toolsrc/src/vcpkg/install.cpp
+++ b/toolsrc/src/vcpkg/install.cpp
@@ -299,6 +299,19 @@ namespace vcpkg::Install
 
             if (result.code != Build::BuildResult::SUCCEEDED)
             {
+                if (result.code == BuildResult::CASCADED_DUE_TO_MISSING_DEPENDENCIES)
+                {
+                    System::println(System::Color::error,
+                                    "The build command requires all dependencies to be already installed.");
+                    System::println("The following dependencies are missing:");
+                    System::println();
+                    for (const auto& p : result.unmet_dependencies)
+                    {
+                        System::println("    %s", p);
+                    }
+                    System::println();
+                }
+
                 System::println(System::Color::error, Build::create_error_message(result.code, action.spec));
                 return result;
             }
```

**Comment by Squareys** [comment]
@pravic The install command and the build command behave in different ways. `install` does *not* require the dependency to be installed already (as opposed to the build command, where you copied that code from...).

My guess is that you are currently updating the cpr port files (adding features, which are not currently there), and one of the features has a dependency to which there is no matching portfile (or a typo in the dependency name).

**Comment by pravic** [comment]
> `install` does not require the dependency to be installed already

But it has to install it, right? And during the install it fails with completely opaque for understanding `CASCADED_DUE_TO_MISSING_DEPENDENCIES` message.

> and one of the features has a dependency to which there is no matching portfile (or a typo in the dependency name).

I doubt about a typo. That story was described [here](https://github.com/Microsoft/vcpkg/pull/2862#issuecomment-367790675):

```
Source: cpr
Build-Depends: curl[core]
```

`core` is a meta-feature of a port, as I understand. So it sounds nonsense if it is missing. And as I said, that error message was not helpful until I added this patch and it became:

> Starting package 2/2: cpr:x86-windows
Building package cpr[core]:x86-windows...
The build command requires all dependencies to be already installed.
The following dependencies are missing:
**curl[core]:x86-windows**

**Comment by Squareys** [comment]
> But it has to install it, right?

Yes, definitely.

> core is a meta-feature of a port, as I understand.

Yes, it describes the base packages without features. 

> The build command requires all dependencies to be already installed.

That part is superfluous though, as the "install command" does *not* require all dependencies to be already installed.
Apart from that, such an error message does make sense. But if a dependency is not found this way, it's due to a portfile missing, or in this case probably a bug that occurs with the dependency on `[core]`.

**Comment by ras0219-msft** [comment]
>Starting package 2/2: cpr:x86-windows
Building package cpr[core]:x86-windows...
The build command requires all dependencies to be already installed.

Getting this message in this way definitely looks like a bug to me. Could you post more of the context above? Specifically all the non-cmake messages and the command line.

This message appears when our just-in-time checks fail (this should _never_ happen during an `install` command). I've recently pushed some fixes to master for these just-in-time checks, so could you make sure you're using the latest tool version and confirm it still repro's?

**Comment by pravic** [comment]
Yes, I'll try to reproduce it again with a fresh vcpkg version.

**Comment by ras0219-msft** [comment]
I was able to reproduce an _extremely similar_ set of issues due to https://github.com/Microsoft/vcpkg/issues/2891, which I've fixed in master.

Please try a commit greater than or equal to c267f32bd.

**Comment by pravic** [comment]
Well, I am able to reproduce the original issue with old source (Vcpkg version: 0.0.105-2018-02-22-17dd6b3e45baba07ae985e9425404f61e071d9ff-external). Now (25b8f25) it works smooth, so yes, your commit does fix the issue.

Thanks!
