### ISSUE TITLE
[uwebsockets] update to 20.34.0

### ISSUE THREAD

**Issue by r52** [microsoft/vcpkg#28611]
Library name: uwebsockets

New version number: 20.34.0

Other information that may be useful (release notes, etc...)

https://github.com/uNetworking/uWebSockets/releases/tag/v20.34.0

**Comment by nbkolchin** [comment]
v20.34.0 relies on unreleased uSockets version, so currently uWebSockets is completely broken.

```
vcpkg_installed/x64-linux/include/uwebsockets/App.h:254:9: error: there are no arguments to ‘us_socket_context_close’ that depend on a template parameter, so a declaration of ‘us_socket_context_close’ must be available [-fpermissive]
  254 |         us_socket_context_close(SSL, (struct us_socket_context_t *) httpContext);
```
