### ISSUE TITLE
applocal.ps1 fails in Visual Studio 2019 because of wildcard path in VcpkgAppLocalDLLs

### ISSUE THREAD

**Issue by nstrahl** [microsoft/vcpkg#28614]
**Describe the bug**
I have integrated vcpkg with my visual studio and installed openssl along with other packages in manifest mode.
My project compiles and links successfully in Visual Studio 2019, but when applocal.ps1 runs I get the error: 

1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4679,5):
error MSB3030: Could not copy the file "D:\Project\output\x64\bin\Debug\libssl-*-x64.dll" because it was not found.
error MSB3030: Could not copy the file "D:\Project\output\x64\bin\Debug\libcrypto-*-x64.dll" because it was not found.
error MSB3030: Could not copy the file "D:\Project\output\x64\bin\Debug\libssl-*.dll" because it was not found.
error MSB3030: Could not copy the file "D:\Project\output\x64\bin\Debug\libcrypto-*.dll" because it was not found.

VcpkgAppLocalDLLs =
1>            D:\Project\output\x64\bin\Debug\libcrypto-\*-x64.dll
1>            D:\Project\output\x64\bin\Debug\libssl-\*-x64.dll
1>            D:\Project\output\x64\bin\Debug\libcrypto-\*.dll
1>            D:\Project\output\x64\bin\Debug\libssl-\*.dll
1>            D:\Project\output\x64\bin\Debug\libssl-3-x64.dll
1>            D:\Project\output\x64\bin\Debug\libcrypto-3-x64.dll

VS does not seem to handle wildcards well. It is important to note that the correct paths for libssl-3-x64.dll and libcrypto-3-x64.dll are included. If I build the project a second time it succeeds because the files are all where they should be. AppLocalFromInstalled does not have to run. I get:

1>Target "AppLocalFromInstalled" skipped, due to false condition; ('$(VcpkgEnabled)' == 'true' and '$(VcpkgApplocalDeps)' == 'true' and '$(LinkSkippedExecution)' != 'true') was evaluated as ('true' == 'true' and 'true' == 'true' and 'True' != 'true').

**Environment**
- OS: Windows 10
- Compiler: MSVC 16.11.22
- vcpkg: commit ecce05107c8af10fa8f58b1dfc3e39e85a4f5832
- openssl version: 3.0.7#1

**To Reproduce**
1. ./vcpkg install openssl
2. start new VS project and compile 

**Expected behavior**
Everything is correct so the build should succeed. The wildcard paths trip VS up is my guess.

**Failure logs**
-(please attached failure logs)

**Additional context**
This might be a general vcpkg error, but It could be an openssl port error instead. It could even be MSVCs fault.

Thanks in advance!

**Comment by MonicaLiu0311** [comment]
Win10
VS 2019
```
PS E:\vcpkg02> ./vcpkg version
vcpkg package management program version 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75

See LICENSE.txt for license information.
```
Sorry for being late, I can't reproduce your issue. At present, powershell has been updated to [7.3.1](https://github.com/microsoft/vcpkg/blob/master/scripts/azure-pipelines/windows/deploy-pwsh.ps1#L8). Could you please use the latest vcpkg to restart?

**Comment by Adela0814** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.

**Comment by kuwana77499981** [comment]
Recently i encountered the same problem while i have also qt installed via vcpkg and here is my solution.
I am not sure if this should be handled by vcpkg team or qt team, hope someone could tell me. Thank you!

**Environment**

- visual studio 17.7.6
- PowerShell 7.3.8
- vcpkg ([213c01](https://github.com/microsoft/vcpkg/commit/213c01f8719e0f8bd48ec6285074a22a7fe5e5a3))
- qt 5.15.10 via vcpkg
- openssl 3.1.3 via vcpkg

**Symptoms**

Microsoft.Common.CurrentVersion.targets(5525,5): error MSB3541: Files has invalid value "some-paths\x64\Release\libcrypto-*-x64.dll". Illegal characters in path.

**Problem**

In _$env:VCPKG_ROOT_DIR\installed\\$env:VCPKG_TARGET_TRIPLET\plugins\qtdeploy.ps1_

        } elseif ($targetBinaryName -match "Qt5Networkd?.dll") {
        deployPlugins "bearer"
        if (Test-Path "$binDir\libcrypto-*-x64.dll")
        {
            deployBinary "$targetBinaryDir" "$binDir" "libcrypto-*-x64.dll"
            deployBinary "$targetBinaryDir" "$binDir" "libssl-*-x64.dll"
        }
        if (Test-Path "$binDir\libcrypto-*.dll")
        {
            deployBinary "$targetBinaryDir" "$binDir" "libcrypto-*.dll"
            deployBinary "$targetBinaryDir" "$binDir" "libssl-*.dll"
        }

it produces my _vcpkg.applocal.log_ and _project.write.1u.tlog_ in my intermediate folder with

target_dir\libcrypto-\*-x64.dll // generated by deployBinary "$targetBinaryDir" "$binDir" "libcrypto-\*-x64.dll"
target_dir\libssl-\*-x64.dll // generated by deployBinary "$targetBinaryDir" "$binDir" "libssl-\*-x64.dll"
target_dir\libcrypto-\*.dll // generated by deployBinary "$targetBinaryDir" "$binDir" "libcrypto-\*.dll"
target_dir\libssl-\*.dll // generated by deployBinary "$targetBinaryDir" "$binDir" "libssl-\*.dll"
target_dir\libssl-3-x64.dll // somewhere else
target_dir\libcrypto-3-x64.dll // somewhere else

There are 3 problems:

1. The if condition itself for x64 and x86 is incorrect, we should use elseif if we are using wildcard. We can change to libcrypto-?-x64.dll but i am not sure if all versions are using single number
2. The deployBinary function simply writes the combined path, resulting the .log/.tlog above
3. There are libcrpto-3-x64.dll and libssl-3-x64.dll being written to the .log/.tlog somewhere else

Changing to the code below produces 2 duplicated dll lines.

        if (Test-Path "$binDir\libcrypto-*-x64.dll")
        {
            Get-ChildItem "$binDir\libcrypto-*-x64.dll" | % {
                deployBinary "$targetBinaryDir" "$binDir" $_.Name
            }
            Get-ChildItem "$binDir\libssl-*-x64.dll" | % {
                deployBinary "$targetBinaryDir" "$binDir" $_.Name
            }
        }
        elseif (Test-Path "$binDir\libcrypto-*.dll")
        {
            Get-ChildItem "$binDir\libcrypto-*.dll" | % {
                deployBinary "$targetBinaryDir" "$binDir" $_.Name
            }
            Get-ChildItem "$binDir\libssl-*.dll" | % {
                deployBinary "$targetBinaryDir" "$binDir" $_.Name
            }
        }

**Solution**

Removing the two if conditions in _$env:VCPKG_ROOT_DIR\installed\\$env:VCPKG_TARGET_TRIPLET\plugins\qtdeploy.ps1_ works well.
