### ISSUE TITLE
how to make vcpkg build and install boost with asan support

### ISSUE THREAD

**Issue by njk42** [microsoft/vcpkg#28627]
I have a project which links boost and some other dependencies built and installed via vcpkg manifest mode which is building cleanly in Visual Studio 2022 (all IDE updates installed)... that is until I enabled Address Sanitizer for my debug build cfg according to [these instructions](https://devblogs.microsoft.com/cppblog/addresssanitizer-asan-for-windows-with-msvc/):   
and received the following linker error (building with either CMake or MSBuild):
LNK2038	mismatch detected for 'annotate_vector': value '0' doesn't match value '1' in file.obj	<path>\boost_thread-vc140-mt-gd.lib(thread.obj)
Apparently the boost dependency needs to also be built with asan support to avoid [this issue](https://learn.microsoft.com/en-us/answers/questions/864574/enabling-address-sanitizer-results-in-error-lnk203.html) and I would rather not punt and disable [container overflow checking](https://learn.microsoft.com/en-us/cpp/sanitizers/error-container-overflow?view=msvc-170) by declaring _DISABLE_VECTOR_ANNOTATION.

So my question is:  how do I configure vcpkg to rebuild boost with /fsanitize=address and install it (into vcpkg_installed folder), and how to I make this unique to Debug builds and not Release builds, and how do I accomplish this for both CMake and MSBuild projects?

Thanks!

**Comment by sanketsystems** [comment]
This can be done using VCPKG_CXX_FLAGS. Check out the relevant discussion [here](https://github.com/microsoft/vcpkg/discussions/25068)
