### ISSUE TITLE
[New Port Request] VIGRA

### ISSUE THREAD

**Issue by echoix** [microsoft/vcpkg#28631]
Library name: VIGRA

Library description: The VIGRA Computer Vision Library
VIGRA stands for "Vision with Generic Algorithms". It's an image processing and analysis library that puts its main emphasis on customizable algorithms and data structures. VIGRA is especially strong for multi-dimensional images, because many algorithms (e.g. filters, feature computation, superpixels) are implemented for arbitrary high dimensions. By using template techniques similar to those in the C++ [Standard Template Library](http://www.sgi.com/tech/stl/), you can easily adapt any VIGRA component to the needs of your application, without thereby giving up execution speed. As of version 1.7.1, VIGRA also provides extensive Python bindings on the basis of the popular numpy framework.

VIGRA is a computer vision library that puts its main emphasis on flexible algorithms, because algorithms represent the principal know-how of this field. The library was consequently built using generic programming as introduced by Stepanov and Musser and exemplified in the C++ Standard Template Library. By writing a few adapters (image iterators and accessors) you can use VIGRA's algorithms on top of your data structures, within your environment. Alternatively, you can also use the data structures provided within VIGRA, which can be easily adapted to a wide range of applications. VIGRA's flexibility comes almost for free: Since the design uses compile-time polymorphism (templates), performance of the compiled program approaches that of a traditional, hand tuned, inflexible, solution.

Source repository URL: https://github.com/ukoethe/vigra

Project homepage (if different from the source repository): https://ukoethe.github.io/vigra/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): I'm not sure to understand well, but maybe this?:

> ```
> -DWITH_VIGRANUMPY=1
> build VIGRA Python bindings (default: 1). Pass -DWITH_VIGRANUMPY=0 to suppress vigranumpy.
> -DWITH_HDF5=1
> build VIGRA with HDF5 support (default: 1). Pass -DDWITH_HDF5=0 to compile without HDF5.
> ```

Other notes: Is a dependency to build the SAGA GIS project, almost all of the other dependencies are already on vcpkg. It is already using cmake

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
