### ISSUE TITLE
Add section to README describing the integration of vcpkg into a project via FetchContent

### ISSUE THREAD

**Issue by globberwops** [microsoft/vcpkg#28645]
****

**Is your feature request related to a problem? Please describe.**
Although integrating vcpkg into a project via Git submodules is working just fine, it may create its own set of problems, such as:
* Split dependency information between CMake/vcpkg/Git
* Users have to remember to init the submodule
* Might lead to redundant copies of vcpkg
* ...

**Proposed solution**
Add a section to the README describing the integration of vcpkg into a project via CMake's FetchContent module (and ideally make it a best practice).

**Describe alternatives you've considered**
Integration via Git submodules

**Comment by FrankXie05** [comment]
https://github.com/microsoft/vcpkg/pull/27311#issue-1413908082

**Comment by MonicaLiu0311** [comment]
This issue will be closed now, please reopen it if you have other questions.
