### ISSUE TITLE
[New Port Request] <library name here>

### ISSUE THREAD

**Issue by dmunoz2019** [microsoft/vcpkg#28653]
Library name: pdftk

Library description: manage pdf files

Source repository URL: https://github.com/pinnymz/pdftk_ext/tree/master/pdftk

Project homepage (if different from the source repository): https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by dg0yt** [comment]
> Source repository URL: https://github.com/pinnymz/pdftk_ext/tree/master/pdftk

This is a fork. An official download URL can be found on this page: 
https://www.pdflabs.com/docs/pdftk-version-history/

Last release: 2013.

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
