### ISSUE TITLE
[bzip2] Build error

### ISSUE THREAD

**Issue by davtx30** [microsoft/vcpkg#28652]
**Host Environment**

- OS: Mac OS : 13.1 (22C65) ( Macbook Air M2 256 GB)
- Compiler: revision
   vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: dbd308118 2022-12-30 (15 hours ago)

**To Reproduce**

`./vcpkg install pcl`

**Failure logs**
error: building bzip2:arm64-osx failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Could you please provide the error log?

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
