### ISSUE TITLE
Port Request: libbpg

### ISSUE THREAD

**Issue by soroshsabz** [microsoft/vcpkg#2866]
ITNOA

Hi,

Please port libbpg from https://github.com/mirrorer/libbpg

BPG Image library and utilities

thx

**Comment by parsamoradi73** [comment]
I need libbpg too.
Please port it.

Thanks.

**Comment by farazpasha** [comment]
I need libbpg too.
It would be a great help if you ported it.

Thanks

**Comment by GreenCodeLine** [comment]
Hi
Please port it.
I need too.

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!

**Comment by soroshsabz** [comment]
@JackBoosY Please add [info:new-port-unresolved](https://github.com/microsoft/vcpkg/labels/info%3Anew-port-unresolved) tag for this issue

**Comment by JackBoosY** [comment]
cc @Cheney-W
