### ISSUE TITLE
Breakpad hash not correct.

### ISSUE THREAD

**Issue by wurui1994** [Microsoft/vcpkg#2867]
E:\GitHub\vcpkg>vcpkg install breakpad
The following packages will be built and installed:
    breakpad[core]:x86-windows
Starting package 1/1: breakpad:x86-windows
Building package breakpad[core]:x86-windows...
-- CURRENT_INSTALLED_DIR=E:/GitHub/vcpkg/installed/x86-windows
-- DOWNLOADS=E:/GitHub/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=E:/GitHub/vcpkg/packages/breakpad_x86-windows
-- CURRENT_BUILDTREES_DIR=E:/GitHub/vcpkg/buildtrees/breakpad
-- CURRENT_PORT_DIR=E:/GitHub/vcpkg/ports/breakpad/.
-- Downloading https://github.com/google/breakpad/archive/6bb6c9b26afd9844b9e35fcaa39fb24893e7abb5.tar.gz...
-- Downloading https://github.com/google/breakpad/archive/6bb6c9b26afd9844b9e35fcaa39fb24893e7abb5.tar.gz... OK
-- Testing integrity of downloaded file...
CMake Error at E:/GitHub/vcpkg/scripts/cmake/vcpkg_download_distfile.cmake:87 (message):

  File does not have expected hash:

          File path: [ E:/GitHub/vcpkg/downloads/google-breakpad-6bb6c9b26afd9844b9e35fcaa39fb24893e7abb5.tar.gz ]
      Expected hash: [ a6a786c2cabb1fd2749d79215c7a3024ae6d1a894166060b22869cd3ee3010edb3e0613c0aeea254580554f402d919ed630ee088c53a1f218e01a7280ad29fec ]
        Actual hash: [ af96ec1383cce40d6dd14cf105ff0ff66bbc68ffd8941b9e5da9cb3462bfb100aa66debf38a759c7fa41a1847f4ff90bca73c859a5e0b18d8e73b3c8a008576f ]

  The file may have been corrupted in transit.

Call Stack (most recent call first):
  E:/GitHub/vcpkg/scripts/cmake/vcpkg_download_distfile.cmake:129 (test_hash)
  E:/GitHub/vcpkg/scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  E:/GitHub/vcpkg/ports/breakpad/portfile.cmake:3 (vcpkg_from_github)
  E:/GitHub/vcpkg/scripts/ports.cmake:72 (include)

Error: Building package breakpad:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: breakpad:x86-windows
  Vcpkg version: 0.0.105-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by ras0219-msft** [comment]
Thanks for posting this issue! It should be corrected in the latest master.
