### ISSUE TITLE
[7zip] Build error

### ISSUE THREAD

**Issue by kdadmin** [microsoft/vcpkg#28676]
Package: 7zip[core]:x86-windows -> 22.01

**Host Environment**

- Host: x86-windows
- Compiler: MSVC 19.16.27048.0
-    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: f9bea5d58 2022-12-31 (2 days ago)

**To Reproduce**

`vcpkg install 7zip`

**Failure logs**

```
-- Downloading https://www.7-zip.org/a/7z2201-src.7z -> 7z2201-src.7z...
-- Extracting source C:/Dev/vcpkg/downloads/7z2201-src.7z
-- Using source at C:/Dev/vcpkg/buildtrees/7zip/src/7z2201-src-29a5a1119a.clean
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2017/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/Dev/vcpkg/buildtrees/7zip/x86-windows-rel/vcpkg-parallel-configure
    Error code: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher
    See logs for more information:

Call Stack (most recent call first):
  installed/x86-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:247 (vcpkg_execute_required_process)
  ports/7zip/portfile.cmake:17 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)



```

**Additional context**

2nd try with vcpkg (zlib and 7zip). Not much luck.

**Comment by Osyotr** [comment]
There's no prebuilt Ninja binary for x86. Right now `vcpkg_find_acquire_program` (in)correctly assumes that windows = x64.

Btw, any reason to use x86 as a host?

**Comment by kdadmin** [comment]
I'm using an x86 computer because I have an x86 computer.

I have a Ninga.exe here at:
C:\Program Files\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja

Did I miss a spec somewhere that vcpkg does not support x86?
7zip does.

**Comment by kdadmin** [comment]
I would copy ninja.exe as you suggest however there is no ninja.exe anywhere in the vcpkg instalation.

There is no vcpkg/downloads/tools/ninja/1.10.2-windows directory.

Note in the log above vcpkg is using my existing ninja.exe.:
Command failed: "C:/Program Files/Microsoft Visual Studio/2017/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    
As a hack, I created the directory:
vcpkg/downloads/tools/ninja/1.10.2-windows
and copied ninja.exe to it but it changed nothing - [install 7zip](c:\dev\vcpkg\vcpkg install 7zip) still fails.

**Comment by Osyotr** [comment]
Sorry, I'm being blind. Now I'm wondering why vcpkg does not use ninja from downloads...
Could you please run vcpkg with `--debug` and upload the output?
Also, are you able to execute `C:/Program Files/Microsoft Visual Studio/2017/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe` from terminal?

**Comment by dg0yt** [comment]
It is an x86 host so vcpkg cannot provide a dowloaded ninja.
vcpkg is willing to accept a system provided ninja. located via `find_program`, and would choose another build tool if ninja isn't found.
IIUC here the dead end is a system provided x64 ninja on an x86 host. I wonder how this can be mixed. But it might be resolved by removing/renaming the incompatible executable.

**Comment by kdadmin** [comment]
@Osyotr 
---------------------------------------------------------------------------
Test existing ninja.exe on 32bit Win10:
cd "C:/Program Files/Microsoft Visual Studio/2017/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja"
.\ninja.exe
Produces:
Program 'ninja.exe' failed to run: The specified executable is not a valid application for this OS
platform.At line:1 char:1
+ .\ninja.exe
+ ~~~~~~~~~~~.
At line:1 char:1
+ .\ninja.exe
+ ~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
PS C:\Program Files\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja>

--------------------------------------------------------------------------
Output from running:
c:\dev\vcpkg\vcpkg install 7zip --debug
in attached Debug_7zip_32bit.txt. - nope, won't let me upload. pasted below:

Run vcpkg install 7zip --debug:

c:\dev\vcpkg\vcpkg install 7zip --debug
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Failed to open: C:\Dev\vcpkg\vcpkg-bundle.json
[DEBUG] Using scripts-root: C:\Dev\vcpkg\scripts
[DEBUG] Bundle config: readonly=0, usegitregistry=0, embeddedsha=nullopt
[DEBUG] Using builtin-ports: C:\Dev\vcpkg\ports
[DEBUG] Using installed-root: C:\Dev\vcpkg\installed
[DEBUG] Using buildtrees-root: C:\Dev\vcpkg\buildtrees
[DEBUG] Using packages-root: C:\Dev\vcpkg\packages
[DEBUG] Using vcpkg-root: C:\Dev\vcpkg
[DEBUG] Using scripts-root: C:\Dev\vcpkg\scripts
[DEBUG] Using builtin-registry: C:\Dev\vcpkg\versions
[DEBUG] Using downloads-root: C:\Dev\vcpkg\downloads
[DEBUG] Detecting host with IsWow64Process2
[DEBUG] Default binary cache path is: C:\Users\gary\AppData\Local\vcpkg\archives
Computing installation plan...
[DEBUG] CreateProcessW("C:\Dev\vcpkg\downloads\tools\cmake-3.25.0-windows\cmake-3.25.0-windows-i386\bin\cmake.exe" --version)
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 1000: cmd_execute_and_stream_data() returned 0 after   160764 us
[DEBUG] CreateProcessW("C:\Dev\vcpkg\downloads\tools\cmake-3.25.0-windows\cmake-3.25.0-windows-i386\bin\cmake.exe" -DVCPKG_ROOT_DIR=C:/Dev/vcpkg -DPACKAGES_DIR=C:/Dev/vcpkg/packages -DBUILDTREES_DIR=C:/Dev/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=C:/Dev/vcpkg/installed -DDOWNLOADS=C:/Dev/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\Dev\vcpkg\buildtrees\0.vcpkg_dep_info.cmake")
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 1001: cmd_execute_and_stream_data() returned 0 after    43593 us
[DEBUG] CreateProcessW("C:\Dev\vcpkg\downloads\tools\cmake-3.25.0-windows\cmake-3.25.0-windows-i386\bin\cmake.exe" -DVCPKG_ROOT_DIR=C:/Dev/vcpkg -DPACKAGES_DIR=C:/Dev/vcpkg/packages -DBUILDTREES_DIR=C:/Dev/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=C:/Dev/vcpkg/installed -DDOWNLOADS=C:/Dev/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\Dev\vcpkg\buildtrees\0.vcpkg_tags.cmake")
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 1002: cmd_execute_and_stream_data() returned 0 after    46299 us
The following packages will be built and installed:
    7zip[core]:x86-windows -> 22.01
[DEBUG] CreateProcessW("C:\Program Files\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease -legacy -products * -format xml)
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 1003: cmd_execute_and_stream_data() returned 0 after    47504 us
Detecting compiler hash for triplet x86-windows...
[DEBUG] Found path: C:\Program Files\Git\cmd\git.exe
[DEBUG] CreateProcessW("C:\Program Files\Git\cmd\git.exe" --version)
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 1004: cmd_execute_and_stream_data() returned 0 after   158046 us
[DEBUG] Detecting host with IsWow64Process2
[DEBUG] CreateProcessW("C:\Dev\vcpkg\downloads\tools\powershell-core-7.3.1-windows\pwsh.exe" --version)
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 1005: cmd_execute_and_stream_data() returned 0 after   845836 us
[DEBUG] command line: cmd /c "C:\Program Files\Microsoft Visual Studio\2017\Professional\VC\Auxiliary/Build\vcvarsall.bat" -vcvars_ver=14.16.27023 x86   2>&1 <NUL  & echo cdARN4xjKueKScMy9C6H & set
[DEBUG] CreateProcessW(cmd /c "C:\Program Files\Microsoft Visual Studio\2017\Professional\VC\Auxiliary/Build\vcvarsall.bat" -vcvars_ver=14.16.27023 x86   2>&1 <NUL  & echo cdARN4xjKueKScMy9C6H & set)
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 1006: cmd_execute_and_stream_data() returned 0 after  1578898 us
[DEBUG] **********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.50
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86'
cdARN4xjKueKScMy9C6H
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\gary\AppData\Roaming
CommandPromptType=Native
CommonProgramFiles=C:\Program Files\Common Files
COMPUTERNAME=DESKTOP-237KF4B
ComSpec=C:\WINDOWS\system32\cmd.exe
DevEnvDir=C:\Program Files\Microsoft Visual Studio\2017\Professional\Common7\IDE\
ExtensionSdkDir=C:\Program Files\Microsoft SDKs\Windows Kits\10\ExtensionSDKs
Framework40Version=v4.0
FrameworkDir=C:\WINDOWS\Microsoft.NET\Framework\
FrameworkDIR32=C:\WINDOWS\Microsoft.NET\Framework\
FrameworkVersion=v4.0.30319
FrameworkVersion32=v4.0.30319
HOMEDRIVE=C:
HOMEPATH=\Users\gary
HTMLHelpDir=C:\Program Files\HTML Help Workshop
INCLUDE=C:\Program Files\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\ATLMFC\include;C:\Program Files\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include;C:\Program Files\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files\Windows Kits\10\include\10.0.17763.0\ucrt;C:\Program Files\Windows Kits\10\include\10.0.17763.0\shared;C:\Program Files\Windows Kits\10\include\10.0.17763.0\um;C:\Program Files\Windows Kits\10\include\10.0.17763.0\winrt;C:\Program Files\Windows Kits\10\include\10.0.17763.0\cppwinrt
LIB=C:\Program Files\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x86;C:\Program Files\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\lib\x86;C:\Program Files\Windows Kits\NETFXSDK\4.6.1\lib\um\x86;C:\Program Files\Windows Kits\10\lib\10.0.17763.0\ucrt\x86;C:\Program Files\Windows Kits\10\lib\10.0.17763.0\um\x86;
LIBPATH=C:\Program Files\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x86;C:\Program Files\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\lib\x86;C:\Program Files\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\lib\x86\store\references;C:\Program Files\Windows Kits\10\UnionMetadata\10.0.17763.0;C:\Program Files\Windows Kits\10\References\10.0.17763.0;C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319;
LOCALAPPDATA=C:\Users\gary\AppData\Local
LOGONSERVER=\\DESKTOP-237KF4B
NETFXSDKDir=C:\Program Files\Windows Kits\NETFXSDK\4.6.1\
NUMBER_OF_PROCESSORS=2
OS=Windows_NT
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
Platform=x86
PROCESSOR_ARCHITECTURE=x86
PROCESSOR_IDENTIFIER=x86 Family 6 Model 23 Stepping 10, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=170a
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Users\gary\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
PUBLIC=C:\Users\Public
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\gary\AppData\Local\Temp
TMP=C:\Users\gary\AppData\Local\Temp
UCRTVersion=10.0.17763.0
UniversalCRTSdkDir=C:\Program Files\Windows Kits\10\
USERDOMAIN=DESKTOP-237KF4B
USERDOMAIN_ROAMINGPROFILE=DESKTOP-237KF4B
USERNAME=gary
USERPROFILE=C:\Users\gary
VCIDEInstallDir=C:\Program Files\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\
VCINSTALLDIR=C:\Program Files\Microsoft Visual Studio\2017\Professional\VC\
VCToolsInstallDir=C:\Program Files\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\
VCToolsRedistDir=C:\Program Files\Microsoft Visual Studio\2017\Professional\VC\Redist\MSVC\14.16.27012\
VCToolsVersion=14.16.27023
VisualStudioVersion=15.0
VS150COMNTOOLS=C:\Program Files\Microsoft Visual Studio\2017\Professional\Common7\Tools\
VSCMD_ARG_app_plat=Desktop
VSCMD_ARG_HOST_ARCH=x86
VSCMD_ARG_TGT_ARCH=x86
VSCMD_ARG_VCVARS_VER=14.16.27023
VSCMD_VER=15.9.50
VSINSTALLDIR=C:\Program Files\Microsoft Visual Studio\2017\Professional\
windir=C:\WINDOWS
PATH=C:\Program Files\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86;C:\Program Files\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCPackages;C:\Program Files\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin\Roslyn;C:\Program Files\Microsoft Visual Studio\2017\Professional\Team Tools\Performance Tools;C:\Program Files\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\;C:\Program Files\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\;C:\Program Files\HTML Help Workshop;C:\Program Files\Windows Kits\10\bin\10.0.17763.0\x86;C:\Program Files\Windows Kits\10\bin\x86;C:\Program Files\Microsoft Visual Studio\2017\Professional\\MSBuild\15.0\bin;C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319;C:\Program Files\Microsoft Visual Studio\2017\Professional\Common7\IDE\;C:\Program Files\Microsoft Visual Studio\2017\Professional\Common7\Tools\;C:\Dev\vcpkg\downloads\tools\powershell-core-7.3.1-windows;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\Wbem;C:\WINDOWS\system32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
VSLANG=1033
VSCMD_SKIP_SENDTELEMETRY=1
VCPKG_COMMAND=c:/dev/vcpkg/vcpkg.exe
WindowsLibPath=C:\Program Files\Windows Kits\10\UnionMetadata\10.0.17763.0;C:\Program Files\Windows Kits\10\References\10.0.17763.0
WindowsSdkBinPath=C:\Program Files\Windows Kits\10\bin\
WindowsSdkDir=C:\Program Files\Windows Kits\10\
WindowsSDKLibVersion=10.0.17763.0\
WindowsSdkVerBinPath=C:\Program Files\Windows Kits\10\bin\10.0.17763.0\
WindowsSDKVersion=10.0.17763.0\
WindowsSDK_ExecutablePath_x86=C:\Program Files\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\
X_VCPKG_RECURSIVE_DATA={}

__DOTNET_ADD_32BIT=1
__DOTNET_PREFERRED_BITNESS=32
__VSCMD_PREINIT_PATH=C:\Dev\vcpkg\downloads\tools\powershell-core-7.3.1-windows;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\Wbem;C:\WINDOWS\system32\WindowsPowerShell\v1.0\

[DEBUG] CreateProcessW("C:\Dev\vcpkg\downloads\tools\cmake-3.25.0-windows\cmake-3.25.0-windows-i386\bin\cmake.exe" -DCURRENT_PORT_DIR=C:/Dev/vcpkg/scripts/detect_compiler -DCURRENT_BUILDTREES_DIR=C:/Dev/vcpkg/buildtrees/detect_compiler -DCURRENT_PACKAGES_DIR=C:/Dev/vcpkg/packages/detect_compiler_x86-windows -D_HOST_TRIPLET=x86-windows -DCMD=BUILD -DDOWNLOADS=C:/Dev/vcpkg/downloads -DTARGET_TRIPLET=x86-windows -DTARGET_TRIPLET_FILE=C:/Dev/vcpkg/triplets/x86-windows.cmake -DVCPKG_BASE_VERSION=2022-12-14 -DVCPKG_CONCURRENCY=3 -DVCPKG_PLATFORM_TOOLSET=v141 "-DGIT=C:/Program Files/Git/cmd/git.exe" -DVCPKG_ROOT_DIR=C:/Dev/vcpkg -DPACKAGES_DIR=C:/Dev/vcpkg/packages -DBUILDTREES_DIR=C:/Dev/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=C:/Dev/vcpkg/installed -DDOWNLOADS=C:/Dev/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\Dev\vcpkg\scripts\ports.cmake")
[DEBUG] -- Configuring x86-windows-rel
[DEBUG] -- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19045.
[DEBUG] -- The C compiler identification is MSVC 19.16.27048.0
[DEBUG] -- Detecting C compiler ABI info
[DEBUG] -- Detecting C compiler ABI info - done
[DEBUG] -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - skipped
[DEBUG] -- Detecting C compile features
[DEBUG] -- Detecting C compile features - done
[DEBUG] -- The CXX compiler identification is MSVC 19.16.27048.0
[DEBUG] -- Detecting CXX compiler ABI info
[DEBUG] -- Detecting CXX compiler ABI info - done
[DEBUG] -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - skipped
[DEBUG] -- Detecting CXX compile features
[DEBUG] -- Detecting CXX compile features - done
[DEBUG] -- Configuring done
[DEBUG] -- Generating done
[DEBUG] -- Build files have been written to: C:/Dev/vcpkg/buildtrees/detect_compiler/x86-windows-rel
[DEBUG]
[DEBUG] #COMPILER_HASH#1de5c7815183773710c912592cc4d74e0020ca40
[DEBUG] #COMPILER_C_HASH#af3509b16281fd6d221963ce422da4eb18bbf739
[DEBUG] #COMPILER_C_VERSION#19.16.27048.0
[DEBUG] #COMPILER_C_ID#MSVC
[DEBUG] #COMPILER_CXX_HASH#af3509b16281fd6d221963ce422da4eb18bbf739
[DEBUG] #COMPILER_CXX_VERSION#19.16.27048.0
[DEBUG] #COMPILER_CXX_ID#MSVC
[DEBUG] CMake Warning:
[DEBUG]   Manually-specified variables were not used by the project:
[DEBUG]
[DEBUG]     BUILD_SHARED_LIBS
[DEBUG]     CMAKE_INSTALL_BINDIR
[DEBUG]     CMAKE_INSTALL_LIBDIR
[DEBUG]     FETCHCONTENT_FULLY_DISCONNECTED
[DEBUG]     _VCPKG_ROOT_DIR
[DEBUG]
[DEBUG]
[DEBUG]
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 1007: cmd_execute_and_stream_data() returned 0 after 13215113 us
[DEBUG]
[DEBUG] Detected compiler hash for triplet x86-windows: 1de5c7815183773710c912592cc4d74e0020ca40
[DEBUG] <abientries for 7zip:x86-windows>
[DEBUG]   7zip-config.cmake.in|8e0e8689873acd75fafb0fc2f4624ae4f983e7c513fdcd9c4e43ceca71a95bf3
[DEBUG]   CMakeLists.txt|7485ec6ca6165e4de71c0e6a74a33e7a942092234000c1b281d2b49131a0326a
[DEBUG]   cmake|3.25.0
[DEBUG]   features|core
[DEBUG]   portfile.cmake|8eccc62147f474313f77b0209063dcb671381a7afba6cf203db64e8d5addd11b
[DEBUG]   ports.cmake|b4accc7941cb5ff993e1a0434cea6df3e99331137294958437b2b86b7216e2e2
[DEBUG]   post_build_checks|2
[DEBUG]   powershell|7.3.1
[DEBUG]   triplet|x86-windows
[DEBUG]   triplet_abi|3e71dd1d4afa622894ae367adbbb1ecbd42c57c51428a86b675fa1c8cad3a581-c0600b35e024ce0485ed253ef5419f3686f7257cfb58cb6a24febcb600fc4b4c-1de5c7815183773710c912592cc4d74e0020ca40
[DEBUG]   vcpkg-cmake|c7117dba14e224d4022a41d260892afc648454d1a3eba942de338154ea5f6bc5
[DEBUG]   vcpkg-cmake-config|94d4935aa65ce5f8c1ef71a251714020a097826911214ec58ce0ab8c65aba286
[DEBUG]   vcpkg.json|06e92c14c605eaded19f4336733e2751d4de7f1bb6e066afaa44c6bc0a400890
[DEBUG]   vcpkg_copy_pdbs|d57e4f196c82dc562a9968c6155073094513c31e2de475694143d3aa47954b1c
[DEBUG]   vcpkg_download_distfile|257c2c17449e740e4553a7adc37fdd80e811045957ff1d86f18c142a290b5865
[DEBUG]   vcpkg_extract_source_archive|a25e0132b36c30e9675f934042fb1164128864eeefa064ab8eabb1eb347aa381
[DEBUG] </abientries>
Restored 0 package(s) from C:\Users\gary\AppData\Local\vcpkg\archives in 307.5 us. Use --debug to see more details.
Installing 1/1 7zip:x86-windows...
Building 7zip[core]:x86-windows...
[DEBUG] Detecting host with IsWow64Process2
[DEBUG] CreateProcessW("C:\Dev\vcpkg\downloads\tools\cmake-3.25.0-windows\cmake-3.25.0-windows-i386\bin\cmake.exe" -DALL_FEATURES= -DCURRENT_PORT_DIR=C:/Dev/vcpkg/ports/7zip -D_HOST_TRIPLET=x86-windows -DFEATURES=core -DPORT=7zip -DVERSION=22.01 -DVCPKG_USE_HEAD_VERSION=0 -D_VCPKG_DOWNLOAD_TOOL=BUILT_IN -D_VCPKG_EDITABLE=0 -D_VCPKG_NO_DOWNLOADS=0 -DZ_VCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Dev/vcpkg/scripts/toolchains/windows.cmake -DCMD=BUILD -DDOWNLOADS=C:/Dev/vcpkg/downloads -DTARGET_TRIPLET=x86-windows -DTARGET_TRIPLET_FILE=C:/Dev/vcpkg/triplets/x86-windows.cmake -DVCPKG_BASE_VERSION=2022-12-14 -DVCPKG_CONCURRENCY=3 -DVCPKG_PLATFORM_TOOLSET=v141 "-DGIT=C:/Program Files/Git/cmd/git.exe" "-DVCPKG_PORT_CONFIGS=C:\Dev\vcpkg\installed\x86-windows\share\vcpkg-cmake\vcpkg-port-config.cmake;C:\Dev\vcpkg\installed\x86-windows\share\vcpkg-cmake-config\vcpkg-port-config.cmake" -DVCPKG_ROOT_DIR=C:/Dev/vcpkg -DPACKAGES_DIR=C:/Dev/vcpkg/packages -DBUILDTREES_DIR=C:/Dev/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=C:/Dev/vcpkg/installed -DDOWNLOADS=C:/Dev/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\Dev\vcpkg\scripts\ports.cmake")
-- Using cached 7z2201-src.7z.
-- Cleaning sources at C:/Dev/vcpkg/buildtrees/7zip/src/7z2201-src-29a5a1119a.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Dev/vcpkg/downloads/7z2201-src.7z
-- Using source at C:/Dev/vcpkg/buildtrees/7zip/src/7z2201-src-29a5a1119a.clean
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2017/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/Dev/vcpkg/buildtrees/7zip/x86-windows-rel/vcpkg-parallel-configure
    Error code: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher
    See logs for more information:

Call Stack (most recent call first):
  installed/x86-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:247 (vcpkg_execute_required_process)
  ports/7zip/portfile.cmake:17 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)


[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 1008: cmd_execute_and_stream_data() returned 1 after  4287019 us
error: building 7zip:x86-windows failed with: BUILD_FAILED
[DEBUG] CreateProcessW("C:\Program Files\Git\cmd\git.exe" "--git-dir=C:\Dev\vcpkg\.git" "--work-tree=C:\Dev\vcpkg\.git" -c core.autocrlf=false show "--pretty=format:%h %cd (%cr)" -s --date=short HEAD)
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 1009: cmd_execute_and_stream_data() returned 0 after   139461 us
[DEBUG] Detecting host with IsWow64Process2
[DEBUG] CreateProcessW("C:\Program Files\Git\cmd\git.exe" "--git-dir=C:\Dev\vcpkg\.git" "--work-tree=C:\Dev\vcpkg\.git" -c core.autocrlf=false show "--pretty=format:%h %cd (%cr)" -s --date=short HEAD)
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 1010: cmd_execute_and_stream_data() returned 0 after    77907 us
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+7zip
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[7zip]+Build+error
Include '[7zip] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: f9bea5d58 2022-12-31 (3 days ago)


Please use the prefilled template from C:\Dev\vcpkg\installed\vcpkg\issue_body.md when reporting your issue.
[DEBUG] D:\a\_work\1\s\src\vcpkg\install.cpp(558):
[DEBUG] Time in subprocesses: 20600440 us
[DEBUG] Time in parsing JSON: 175 us
[DEBUG] Time in JSON reader: 231 us
[DEBUG] Time in filesystem: 352102 us
[DEBUG] Time in loading ports: 58601 us
[DEBUG] Exiting after 21.13 s (20899963 us)
PS C:\Program Files\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja>

**Comment by MonicaLiu0311** [comment]
> The fix is to build your own ninja.exe for x86 from source.
Vcpkg only works on x64 by default.
See:
https://github.com/microsoft/vcpkg/issues/3142
Too bad MS does not make that clear at the start.

Thank you for your feedback, this issue will be closed.
