### ISSUE TITLE
[ceres] Build error

### ISSUE THREAD

**Issue by DarrenLu666888** [microsoft/vcpkg#28685]
**Host Environment**

- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**

`./vcpkg install xxxx`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Adela0814** [comment]
@DarrenLu666888 Please provide the repro steps and failure logs.

**Comment by DarrenLu666888** [comment]
build ceres in windows for :
vcpkg install ceres[eigensparse]:x64-mingw-static  --recurse

error:
error: building ceres:x64-mingw-static failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+ceres
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[ceres]+Build+error
Include '[ceres] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: ecce05107 2022-12-28 (5 days ago)

**Comment by Cheney-W** [comment]
This issue hasn’t been updated in 3 months, if it is still an issue, please reopen this issue.
