### ISSUE TITLE
New Port Request:md5

### ISSUE THREAD

**Issue by yaoyao-cn** [microsoft/vcpkg#28682]
Library name: md5

Library description: MD5 C++ class convert from Frank Thilo (thilo@unix-ag.org) for bzflag (http://www.bzflag.org)

Source repository URL: https://github.com/yaoyao-cn/md5

Project homepage (if different from the source repository): https://www.bzflag.org/

the library uses modern cmake and is easy to add to port, I have test this library on windows , linux and macOS platform

this is md5 port config file I use now: https://github.com/yaoyao-cn/vcpkg/tree/master/ports/md5

**Comment by yaoyao-cn** [comment]
I have move the md5 port code to this branch https://github.com/yaoyao-cn/vcpkg/tree/md5_port preparing for a pull request if you accept this library

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
