### ISSUE TITLE
[ffmpeg] videotoolbox unavailable on macOS

### ISSUE THREAD

**Issue by xiaozhuai** [microsoft/vcpkg#28706]
**Describe the bug**
videotoolbox is no longer available since ffmpeg upgrade to 5.0

**Environment**
- OS: macOS

**Comment by FrankXie05** [comment]
@xiaozhuai 
Can you explain in detail and provide steps to reproduce? Is `videotoolbox` a feature of `ffmpeg`?

**Comment by xiaozhuai** [comment]
@FrankXie05 `videotoolbox` is a hardware acceleration device support by ffmpeg on macOS. Use follow code to list all supported hwdevice.
```c++
AVHWDeviceType type = AV_HWDEVICE_TYPE_NONE;
while ((type = av_hwdevice_iterate_types(type)) != AV_HWDEVICE_TYPE_NONE) {
    printf("%s", av_hwdevice_get_type_name(type));
}
```

**Comment by Neumann-A** [comment]
Isn't that an upstream issue then?

**Comment by xiaozhuai** [comment]
> Isn't that an upstream issue then?

I have no idea of this. It's ok on ffmpeg 4.x.

**Comment by xiaozhuai** [comment]
> Isn't that an upstream issue then?

I have no idea of this. It's ok on ffmpeg 4.x.

**Comment by Sibras** [comment]
Some dependencies went from being implicitly selected to explicitly selected in the 5.0 version update.
The 5.0.2 version PR should fix this.

**Comment by xiaozhuai** [comment]
> Some dependencies went from being implicitly selected to explicitly selected in the 5.0 version update. The 5.0.2 version PR should fix this.

Thanks for clarification.
