### ISSUE TITLE
[New Port Request] xpack

### ISSUE THREAD

**Issue by Elite-stay** [microsoft/vcpkg#28703]
Library name:xpack

Library description:convert json/xml/bson to c++ struct

Source repository URL:https://github.com/xyz347/xpack

Project homepage (if different from the source repository):https://github.com/xyz347/xpack

Anything else that is useful to know when adding (such as optional features the library may have that should be included):header only, XPACK_SUPPORT_QT

**Comment by xyz347** [comment]
This is written in the [README](https://github.com/xyz347/xpack/blob/master/README-en.md#qt-support)

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This port has been added into vcpkg, you could install it by vcpkg now.
