### ISSUE TITLE
[New Port Request] dascript

### ISSUE THREAD

**Issue by Minecraft1248** [microsoft/vcpkg#28709]
Library name: dascript

Library description: daScript is high-level, statically strong typed scripting language, designed to be fast as embeddable ‘scripting’ language for C++ performance critical applications like games.

Source repository URL: https://github.com/GaijinEntertainment/daScript

Project homepage (if different from the source repository): https://dascript.org/

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
