### ISSUE TITLE
geographiclib x64

### ISSUE THREAD

**Issue by vasvladal** [Microsoft/vcpkg#2871]
h:\Repos\vcpkg-master>vcpkg.exe install geographiclib:x64-windows
The following packages will be built and installed:
    geographiclib[core]:x64-windows
Starting package 1/1: geographiclib:x64-windows
Building package geographiclib[core]:x64-windows...
-- CURRENT_INSTALLED_DIR=H:/Repos/vcpkg-master/installed/x64-windows
-- DOWNLOADS=H:/Repos/vcpkg-master/downloads
-- CURRENT_PACKAGES_DIR=H:/Repos/vcpkg-master/packages/geographiclib_x64-windows
-- CURRENT_BUILDTREES_DIR=H:/Repos/vcpkg-master/buildtrees/geographiclib
-- CURRENT_PORT_DIR=h:/Repos/vcpkg-master/ports/geographiclib/.
-- Downloading https://jaist.dl.sourceforge.net/project/geographiclib/distrib/GeographicLib-1.47-patch1.zip...
-- Downloading https://jaist.dl.sourceforge.net/project/geographiclib/distrib/GeographicLib-1.47-patch1.zip... OK
-- Testing integrity of downloaded file...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:87 (message):

  File does not have expected hash:

          File path: [ H:/Repos/vcpkg-master/downloads/geographiclib-1.47-patch1.zip ]
      Expected hash: [ d8fdfd7ae093057ec1a4ab922457fe71a3fb9975df5b673c276d62a0e9c4f212dc63652830b9d89e3890bc96aafd335992943cf6a1bce8260acf932d1eb7abfd ]
        Actual hash: [ 3b53ccf0243cd4a6a731a898bfdba95c3d22342e7e64f9e9a4a2bce5f74ac809943f570ed92c9077101a178f82f49ece1d1c4bfee1f288ea61d99fb36f6a243e ]

  The file may have been corrupted in transit.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:129 (test_hash)
  ports/geographiclib/portfile.cmake:15 (vcpkg_download_distfile)
  scripts/ports.cmake:72 (include)

Error: Building package geographiclib:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: geographiclib:x64-windows
  Vcpkg version: 0.0.105-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by ras0219-msft** [comment]
Thanks for reporting this issue!

I am unable to repro the bug -- my download matches the recorded hash. It is possible that you are behind a proxy that is causing issues during the download.

If this is the case, please set the `HTTPS_PROXY` variable to configure curl to use your proxy [1].

[1] https://stackoverflow.com/questions/9445489/performing-http-requests-with-curl-using-proxy
