### ISSUE TITLE
[docs] vcpkg-tool readme translations redirect to this repo

### ISSUE THREAD

**Issue by ninjaoflight** [microsoft/vcpkg#28723]
## Description

on the `vcpkg-tool` repo readme there is a list of translations links, however they seem to redirect to this main readme translations which have different contents and cause confusion for some users that may prefer those translations.

## proposal

I think that it should be better if an translation for some of those languages is made so any users can see the `vcpkg-tool` translated and tell the user if the other non yet translated languages redirect to this main readme, for example assuming that Spanish is not translated

[Español (readme principal)](https://github.com/microsoft/vcpkg/blob/master/README_es.md) 

----

I know that some of those translations may not be a priority or have an official translator, but any community contributor could help translate them as it was made on this repo, in my case I could help to translate it to Spanish and open a PR on the other repo so it can be properly reviewed, so I opened this issue to check if this is intentional or of there is any issue proposing this change.

please let me know what do you think

**Comment by FrankXie05** [comment]
cc @BillyONeal

**Comment by FrankXie05** [comment]
@ninjaoflight Do you mean: The homepage of `vcpkg-tool` should provide the same translations and redirection links to `README_xx.md` in different languages as `vcpkg`?

**Comment by ninjaoflight** [comment]
The languages section could be removed as it was copied from this repo readme, if this was intentional a link to the English readme should have been included

**Comment by FrankXie05** [comment]
We will provide an area to inform about various language support and redirect links for `vcpkg-tool` just like [vcpkg](https://github.com/microsoft/vcpkg#:~:text=%E4%B8%AD%E6%96%87%E6%80%BB%E8%A7%88%20Espa%C3%B1ol%20%ED%95%9C%EA%B5%AD%EC%96%B4%20Fran%C3%A7ais%20Ti%E1%BA%BFng%20Vi%E1%BB%87t). :)
