### ISSUE TITLE
[gmp] Build error on macOS with specified host triplet

### ISSUE THREAD

**Issue by ekilmer** [microsoft/vcpkg#28728]
**Host Environment**

- OS: macOS 12.3
- Compiler: Xcode 14.0.1 using Apple clang

I initially ran into this issue on my fully updated (x86, macOS 13.1, Xcode 14.2) but figured it might be worth reproducing on GitHub Actions runner, to make sure it wasn't something weird with my environment (and also GitHub Actions is where I will want it to run).

**To Reproduce**

`./vcpkg install --host-triplet=x64-osx-release gmp`

**Failure logs**

See here for full output and reproducing steps in this test repo https://github.com/ekilmer/vcpkg-gmp-test/actions/runs/3841836968/jobs/6542507117#step:4:75

```
Installing 4/4 gmp:x64-osx...
Building gmp[core]:x64-osx...
-- Using cached gmp-6.2.1.tar.xz.
-- Using cached gmp-arm64-asm-fix-5f32dbc41afc.patch.
-- Cleaning sources at /Users/runner/work/vcpkg-gmp-test/vcpkg-gmp-test/vcpkg/buildtrees/gmp/src/v6.2.1-0c723d4b6f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/runner/work/vcpkg-gmp-test/vcpkg-gmp-test/vcpkg/downloads/gmp-6.2.1.tar.xz
-- Applying patch asmflags.patch
-- Applying patch cross-tools.patch
-- Applying patch subdirs.patch
-- Applying patch msvc_symbol.patch
-- Applying patch arm64-coff.patch
-- Applying patch /Users/runner/work/vcpkg-gmp-test/vcpkg-gmp-test/vcpkg/downloads/gmp-arm64-asm-fix-5f32dbc41afc.patch
-- Using source at /Users/runner/work/vcpkg-gmp-test/vcpkg-gmp-test/vcpkg/buildtrees/gmp/src/v6.2.1-0c723d4b6f.clean
-- Getting CMake variables for x64-osx
-- Getting CMake variables for x64-osx-dbg
-- Getting CMake variables for x64-osx-rel
-- Generating configure for x64-osx
-- Finished generating configure for x64-osx
-- Configuring x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: /bin/bash -c "V=1 ./../src/v6.2.1-0c723d4b6f.clean/configure  \"CCAS=cc\" \"ASMFLAGS=-c\" \"--enable-cxx\" \"--with-pic\" \"--with-readline=no\" \"gmp_cv_prog_exeext_for_build=\" \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"--prefix=/Users/runner/work/vcpkg-gmp-test/vcpkg-gmp-test/vcpkg/installed/x64-osx/debug\" \"--bindir=\\${prefix}/../tools/gmp/debug/bin\" \"--sbindir=\\${prefix}/../tools/gmp/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/gmp\""
    Working Directory: /Users/runner/work/vcpkg-gmp-test/vcpkg-gmp-test/vcpkg/buildtrees/gmp/x64-osx-dbg
    Error code: 1
    See logs for more information:
      /Users/runner/work/vcpkg-gmp-test/vcpkg-gmp-test/vcpkg/buildtrees/gmp/config-x64-osx-dbg-config.log
      /Users/runner/work/vcpkg-gmp-test/vcpkg-gmp-test/vcpkg/buildtrees/gmp/config-x64-osx-dbg-out.log
      /Users/runner/work/vcpkg-gmp-test/vcpkg-gmp-test/vcpkg/buildtrees/gmp/config-x64-osx-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:808 (vcpkg_execute_required_process)
  ports/gmp/portfile.cmake:82 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)


error: building gmp:x64-osx failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+gmp
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[gmp]+Build+error
Include '[gmp] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: fa32c6acb 2023-01-04 (48 minutes ago)
```

[config-x64-osx-dbg-config.log](https://github.com/microsoft/vcpkg/files/10347722/config-x64-osx-dbg-config.log)
[config-x64-osx-dbg-err.log](https://github.com/microsoft/vcpkg/files/10347723/config-x64-osx-dbg-err.log)
[config-x64-osx-dbg-out.log](https://github.com/microsoft/vcpkg/files/10347724/config-x64-osx-dbg-out.log)

The relevant lines in the log file (`*-config.log`) seems to be this
```
configure: testlist sizeof-long-4
configure:7781: checking compiler /Applications/Xcode_14.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -isysroot /Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -fPIC -g -fPIC -g has sizeof(long)==4
configure:7794: /Applications/Xcode_14.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -isysroot /Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -fPIC -g -fPIC -g -c conftest.c >&5
conftest.c:4:26: error: 'test_array' declared as an array with a negative size
  static int test_array [1 - 2 * (long) (sizeof (long) != 4)];
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
configure:7797: $? = 1
configure:7802: result: no
configure:7844: error: could not find a working compiler, see config.log for details
```

which is odd 

**Additional context**

This seems to be an issue with how cross-compiling is handled because when I remove `--host-triplet=x64-osx-release` (`vcpkg install gmp`) it compiles fine.

I can compile fine on Linux with
```
./vcpkg install --host-triplet=x64-linux-release gmp
```

**Comment by Neumann-A** [comment]
Hmm what does `int main() { return sizeof(long); }`  return for you if you manually compile that similar to what the configure script does?

**Comment by ekilmer** [comment]
> Hmm what does `int main() { return sizeof(long); }` return for you if you manually compile that similar to what the configure script does?

On my local machine:

```
$ cat ./sizeof_long.c
int main() { return sizeof(long); }

$ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc \
    -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk \
    -fPIC -g ./sizeof_long.c -o sizeof_long

$ ./sizeof_long

$ echo $?
8
```

I've also attached the output log for the host triplet that passes [config-x64-osx-release-rel-config.log](https://github.com/microsoft/vcpkg/files/10348687/config-x64-osx-release-rel-config.log) and the first part of the diff `diff -u config-x64-osx-release-rel-config.log config-x64-osx-dbg-config.log`:
```diff
--- config-x64-osx-release-rel-config.log	2023-01-05 01:36:28
+++ config-x64-osx-dbg-config.log	2023-01-04 21:46:36
@@ -4,13 +4,13 @@
 It was created by GNU MP configure 6.2.1, which was
 generated by GNU Autoconf 2.71.  Invocation command line was
 
-  $ ./../src/v6.2.1-0c723d4b6f.clean/configure --enable-cxx --with-pic --with-readline=no gmp_cv_prog_exeext_for_build= --disable-silent-rules --verbose --disable-shared --enable-static --prefix=/Users/runner/work/vcpkg-gmp-test/vcpkg-gmp-test/vcpkg/installed/x64-osx-release '--bindir=${prefix}/tools/gmp/bin' '--sbindir=${prefix}/tools/gmp/sbin' '--libdir=${prefix}/lib' '--mandir=${prefix}/share/gmp' '--docdir=${prefix}/share/gmp' '--datarootdir=${prefix}/share/gmp'
+  $ ./../src/v6.2.1-0c723d4b6f.clean/configure CCAS=cc ASMFLAGS=-c --enable-cxx --with-pic --with-readline=no gmp_cv_prog_exeext_for_build= --disable-silent-rules --verbose --disable-shared --enable-static --prefix=/Users/runner/work/vcpkg-gmp-test/vcpkg-gmp-test/vcpkg/installed/x64-osx/debug '--bindir=${prefix}/../tools/gmp/debug/bin' '--sbindir=${prefix}/../tools/gmp/debug/sbin' '--libdir=${prefix}/lib' '--includedir=${prefix}/../include' '--datarootdir=${prefix}/share/gmp'
 
 ## --------- ##
 ## Platform. ##
 ## --------- ##
 
-hostname = Mac-1672881054616.local
+hostname = Mac-1672868594468.local
 uname -m = x86_64
 uname -r = 21.6.0
 uname -s = Darwin
@@ -30,8 +30,8 @@
 Processor type: i486 (Intel 80486)
 Processors active: 0 1 2
 Primary memory available: 14.00 gigabytes
-Default processor set: 387 tasks, 1235 threads, 3 processors
-Load average: 2.45, Mach factor: 0.89
+Default processor set: 328 tasks, 1160 threads, 3 processors
+Load average: 2.00, Mach factor: 1.19
 /bin/machine           = unknown
 /usr/bin/oslevel       = unknown
 /bin/universe          = unknown
@@ -57,6 +57,7 @@
 PATH: /Users/runner/.ghcup/bin/
 PATH: /Users/runner/hostedtoolcache/stack/2.9.1/x64/
 PATH: /Users/runner/work/vcpkg-gmp-test/vcpkg-gmp-test/vcpkg/downloads/tools/ninja/1.10.2-osx/
+PATH: /Applications/Xcode_14.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/
 PATH: /Users/runner/work/vcpkg-gmp-test/vcpkg-gmp-test/vcpkg/downloads/tools/ninja/1.10.2-osx/
 PATH: /usr/local/bin/
 
@@ -74,9 +75,9 @@
 configure:3432:   ./../src/v6.2.1-0c723d4b6f.clean/config.guess found
 configure:3432:   ./../src/v6.2.1-0c723d4b6f.clean/config.sub found
 configure:3592: checking build system type
-configure:3607: result: x86_64-apple-darwin21.6.0
+configure:3607: result: i386-apple-darwin21.6.0
 configure:3627: checking host system type
-configure:3641: result: x86_64-apple-darwin21.6.0
+configure:3641: result: i386-apple-darwin21.6.0
 configure:3679: checking for a BSD-compatible install
 configure:3752: result: /usr/bin/install -c
 configure:3763: checking whether build environment is sane
```
I'm not very familiar with GNU autoconfig, so I might be missing something obvious in this listing or the rest of the diff.

I've also run the CI with verbose logging. Maybe there's a clue there https://github.com/ekilmer/vcpkg-gmp-test/actions/runs/3843195889/jobs/6545236213

**Comment by Neumann-A** [comment]
```
-configure:3641: result: x86_64-apple-darwin21.6.0
+configure:3641: result: i386-apple-darwin21.6.0
```

is probably the problem.

**Comment by ekilmer** [comment]
> ```
> -configure:3641: result: x86_64-apple-darwin21.6.0
> +configure:3641: result: i386-apple-darwin21.6.0
> ```
> 
> is probably the problem. 

What's causing configure to choose i386 vs x86_64? Both triplets say x64-osx

**Comment by Neumann-A** [comment]
Are you running from the same shell? But I am wondering why vcpkg is not adding `--target=<vcpkg-target-triplet>|--host=<something>` to the configure call. x86 to x64 is basically a cross build.

**Comment by ekilmer** [comment]
> Are you running from the same shell?

Yes, same shell. You can see the command being run that generated the log files here
https://github.com/ekilmer/vcpkg-gmp-test/blob/913fddc176a91562b6ac342a1fb343d2532215cf/.github/workflows/ci.yml#L21

> But I am wondering why vcpkg is not adding `--target=<vcpkg-target-triplet>|--host=<something>` to the configure call.

I'm not sure.

> x86 to x64 is basically a cross build.

I'm not trying to build anything x86. I'm using `--host-triplet=x64-osx-release` in CI so that I don't build _both_ debug and release binaries for host tools (it wastes time)

**Comment by dg0yt** [comment]
We are talking about x64-release to x64....

From mingw I'm aware of these lines in the portfile:
https://github.com/microsoft/vcpkg/blob/12c2a93b4007612b5ffa980c9d2235eb0bcac10f/ports/gmp/portfile.cmake#L65-L66
This changes the behaviour for (vcpkg) cross builds only. But it doesn't make sense in its current form.

**Comment by dg0yt** [comment]
> I'm using `--host-triplet=x64-osx-release` in CI so that I don't build _both_ debug and release binaries for host tools (it wastes time)

OTOH this will need extra build time and disk space for ports needed in both host and target.

**Comment by ekilmer** [comment]
> > I'm using `--host-triplet=x64-osx-release` in CI so that I don't build _both_ debug and release binaries for host tools (it wastes time)
> 
> OTOH this will need extra build time and disk space for ports needed in both host and target.

You're right in this case, but if I was doing something like `--host-triplet=x64-osx-release` and `--target-triplet=x64-osx-asan` (or any other triplet where there might be a non-negligible overhead for host tools), then there could be a good reason to separate the builds and make up the extra build time at runtime for those host tools.

(my `x64-osx-asan` triplet is very experimental and doesn't actually work for GMP, but this was an example)

**Comment by dg0yt** [comment]
I can reproduce this on my x64 Mac. 
`vcpkg install gmp` works.
`vcpkg install amp --host=x64-osx-release` fails.
Let me see.

**Comment by dg0yt** [comment]
It is related to cross-build particularities in `vcpkg_configure_make`, with `VCPKG_CROSSCOMPILING` enabled which actually not doing a cross-build.
- `AUTOCONFIG` doesn't add `--host` when osx target and build arch are equal.
- `vcpkg_configure_make` sets `CC_FOR_BUILD` to a no-op for cross builds.
- `config.guess` relies on  a working `CC_FOR_BUILD` to determine host information.
  (It would use `CC` if `CC_FOR_BUILD` was unset.)

I'm unsure how to find out of this. I think we need to enable `--host` due to `VCPKG_CROSSCOMPILING`.
