### ISSUE TITLE
How do I can repeat install?

### ISSUE THREAD

**Issue by dbyoung720** [microsoft/vcpkg#28731]
Mistakenly delete a header file or a library file from installed directory, I want repeat install, Recover deleted files.
How do I can ?  
vcpkg install ... ，Doesn't work。

**Comment by MonicaLiu0311** [comment]
Please try the following commands:
```
./vcpkg remove portname --recurse
./vcpkg install portname
```

If the above command does not solve your problem, please describe the specific file under which port?

**Comment by MonicaLiu0311** [comment]
@dbyoung720 
Was the issue resolved?

**Comment by dbyoung720** [comment]
OK
