### ISSUE TITLE
Automatic clean up of old files?

### ISSUE THREAD

**Issue by OlafvdSpek** [microsoft/vcpkg#2874]
`vcpkg\downloads` and other maps are full of old files, is there a way to clean them up automatically?

Ideally, Windows would support a `Useful, but may be deleted` flag on files for purposes like this. Perhaps you could forward this feature request? ;)
A `Uesless, should be deleted` flag would be nice as well while we're at it.

**Comment by treigilbert** [comment]
One idea that might save a little space, have an option to remove the .obj files from the buildtrees folder for builds that successfully install. The source and build tools would still be available for reference or if a change is required. I don't see much value in keeping .obj files after a successful install and it may be a way to save some space. The more general issue of removing old files would probably require the need to track downloads and builds processes from older versions of the vcpkg and portfiles, making things less clean then the current vcpkg design. I sometimes do a clean build from an new vcpkg of the libraries I use. If successful and it passes some tests, I archive the older vcpkg directory and remove after a sufficient time.

**Comment by MikeGitb** [comment]
Iirc you can just delete the build trees folders without problems.

**Comment by JackBoosY** [comment]
Hi @OlafvdSpek, thanks for reporting this issue!
You can manually delete the port folder that is not required to be archived under **buildtrees** and the port source package that does not need to be archived under **downloads**.

**Comment by OlafvdSpek** [comment]
I know, but manual != automatic. ;)

**Comment by norlesh** [comment]
Just wanted to add my +1 to this issue - I'm currently installing the Point Cloud Library and my vcpkg repo is up to +14GB and still climbing. Out of that there is only around 750MB of downloads and another 1.7GB of built/installed binaries... Is it safe to prune the entire buildtrees directories once builds are completed assuming I'm not planning on reading through a couple hundred thousand lines of peripheral code?

**Comment by Rastaban** [comment]
I recommend using the `--clean-after-build` flag.

```
PS D:\vcpkg\vcpkg> .\vcpkg.exe help install
Example:
  vcpkg install zlib zlib:x64-windows curl boost

Options:
    --dry-run                                Do not actually build or install
    --head                                   Install the libraries on the command line using the latest upstream sources
    --no-downloads                           Do not download new sources
    --recurse                                Allow removal of packages as part of installation
    --keep-going                             Continue installing packages on failure
    --x-use-aria2                            Use aria2 to perform download tasks
    --clean-after-build                      Clean buildtrees, packages and downloads after building each package
    --x-xunit=...                            File to output results in XUnit format (Internal use)
    --triplet <t>                            Set the default triplet for unqualified packages
    --overlay-ports=<path>                   Specify directories to be used when searching for ports
    --overlay-triplets=<path>                Specify directories containing triplets files
    --vcpkg-root <path>                      Specify the vcpkg directory to use instead of current directory or tool directory
    --scripts-root=<path>                    Specify the scripts directory to use instead of default vcpkg scripts directory
```

**Comment by OlafvdSpek** [comment]
@Rastaban On every invocation of install / upgrade? Not a solution IMO.

**Comment by eugenesvk** [comment]
@OlafvdSpek, agree that there has to be an automatic solution, but in the meantime maybe this type of `vcpkg.ps1` script could help by adding `--clean-after-build` command at the end on every passing of `install`?
```
#vcpkg.ps1
for ( $i = 0; $i -lt $args.count; $i++ ) {
  if ($args[$i] -eq "install") { # add extra default options to install
    $args += "--clean-after-build"	# Clean buildtrees, packages and downloads after building each package
  }
}
&'\path\to\vcpkg.exe' $args
```

**Comment by neko-para** [comment]
> I recommend using the `--clean-after-build` flag.
> 
> ```
> PS D:\vcpkg\vcpkg> .\vcpkg.exe help install
> Example:
>   vcpkg install zlib zlib:x64-windows curl boost
> 
> Options:
>     --dry-run                                Do not actually build or install
>     --head                                   Install the libraries on the command line using the latest upstream sources
>     --no-downloads                           Do not download new sources
>     --recurse                                Allow removal of packages as part of installation
>     --keep-going                             Continue installing packages on failure
>     --x-use-aria2                            Use aria2 to perform download tasks
>     --clean-after-build                      Clean buildtrees, packages and downloads after building each package
>     --x-xunit=...                            File to output results in XUnit format (Internal use)
>     --triplet <t>                            Set the default triplet for unqualified packages
>     --overlay-ports=<path>                   Specify directories to be used when searching for ports
>     --overlay-triplets=<path>                Specify directories containing triplets files
>     --vcpkg-root <path>                      Specify the vcpkg directory to use instead of current directory or tool directory
>     --scripts-root=<path>                    Specify the scripts directory to use instead of default vcpkg scripts directory
> ```

As `--clean-after-build` would remove all downloaded files, it makes vcpkg download msys2 again and again 🤔
