### ISSUE TITLE
[darknet] Static builds expose symbols which conflict with getopt

### ISSUE THREAD

**Issue by ras0219-msft** [microsoft/vcpkg#28756]
**Host Environment**

x64-windows-static CI

**To Reproduce**

```
./vcpkg install getopt darknet --triplet=x64-windows-static
./vcpkg install ideviceinstaller --triplet=x64-windows-static
```

**Failure logs**

> "D:\buildtrees\ideviceinstaller\x64-windows-static-rel\1.1.2.23-68bdac5247.clean\ideviceinstaller.vcxproj" (Rebuild target) (1) ->
       (Link target) -> 
         getopt.lib(getopt.c.obj) : error LNK2005: optind already defined in darknet.lib(getopt.c.obj) [D:\buildtrees\ideviceinstaller\x64-windows-static-rel\1.1.2.23-68bdac5247.clean\ideviceinstaller.vcxproj]
         getopt.lib(getopt.c.obj) : error LNK2005: opterr already defined in darknet.lib(getopt.c.obj) [D:\buildtrees\ideviceinstaller\x64-windows-static-rel\1.1.2.23-68bdac5247.clean\ideviceinstaller.vcxproj]
         getopt.lib(getopt.c.obj) : error LNK2005: optopt already defined in darknet.lib(getopt.c.obj) [D:\buildtrees\ideviceinstaller\x64-windows-static-rel\1.1.2.23-68bdac5247.clean\ideviceinstaller.vcxproj]
         D:\buildtrees\ideviceinstaller\x64-windows-static-rel\1.1.2.23-68bdac5247.clean\x64\Release\ideviceinstaller.exe : fatal error LNK1169: one or more multiply defined symbols found [D:\buildtrees\ideviceinstaller\x64-windows-static-rel\1.1.2.23-68bdac5247.clean\ideviceinstaller.vcxproj]

**Additional context**

Found during https://github.com/microsoft/vcpkg/pull/28483

**Comment by dg0yt** [comment]
#28718

**Comment by ras0219-msft** [comment]
Duplicate of #28718
