### ISSUE TITLE
When to release the next released?

### ISSUE THREAD

**Issue by MikeKen-Ken** [microsoft/vcpkg#28761]
Can the package version update be independent from the vcpkg version update, so that the package version can be updated in time, instead of waiting for the vcpkg release. 

Thank you.

**Comment by FrankXie05** [comment]
You can clone the latest `vcpkg` locally and change the corresponding port `portfile.cmake` and `vcpkg` files to update the local version. Or re-forkr an own `vcpkg` github.

**Comment by MikeKen-Ken** [comment]
I  clone the latest `vcpkg`, and copy the corresponding file `portfile.cmake `and `vcpkg.json` to my `vcpkg/ports/TARGET_PAG` path?

**Comment by MikeKen-Ken** [comment]
> You can clone the latest `vcpkg` locally and change the corresponding port `portfile.cmake` and `vcpkg` files to update the local version. Or re-forkr an own `vcpkg` github.

 I upgraded to the latest version, and installed the files, but Cmake still reports that the files are not found, am I missing some steps to install the latest version?

**Comment by FrankXie05** [comment]
Does your updated port is provided by vcpkg? Or a custom port file? Is it convenient to provide it? :)

**Comment by MikeKen-Ken** [comment]
I cloned the latest project, then ran vcpkg install, and through the vcpkg list, I saw that I was installing the latest version of the package I wanted. But when I try find_package(DICOM CONFIG REQUIRED), Cmake gives me an error that the package is not found. Can you help me to see what is going on? The package I am using is vtk-dicom, the version is 0.8.14

![image](https://user-images.githubusercontent.com/40336793/210925382-95a87c63-df51-4faf-bdc5-81cc4711882f.png)
![image](https://user-images.githubusercontent.com/40336793/210925426-dc8b9bf2-7486-4a67-8996-5a90682e51cb.png)

**Comment by MikeKen-Ken** [comment]
> Does your updated port is provided by vcpkg? Or a custom port file? Is it convenient to provide it? :)

I use the port by vcpkg. From [here](https://github.com/microsoft/vcpkg/tree/master/ports/vtk-dicom).

**Comment by FrankXie05** [comment]
Please run command `./vcpkg install vtk-dicom:x64-windows` and use the provided usage.

**Comment by MikeKen-Ken** [comment]
> Please run command `./vcpkg install vtk-dicom:x64-windows` and use the provided usage.

It's not work. Still not find the package.

**Comment by MikeKen-Ken** [comment]
This problem only occurs with the vtk-dicom 0.8.14 package. I use manifest mode, and when I use find_package(DICOM CONFIG REQUIRED) in Cmakelist.txt, it reports an error. Can you help me to see what's wrong with this package? Or am I installing it incorrectly?

**Comment by FrankXie05** [comment]
@MikeKen-Ken This is not the same issue, please open a new one. :)
