### ISSUE TITLE
[libpng] Build error  Infected file detected 18 minutes ago  Feature: Antivirus  The file C:\vcpkg\buildtrees\libpng\x86-windows-dbg\png-fix-itxt.exe was removed from your system and couldn't be moved to quarantine. View attack timeline

### ISSUE THREAD

**Issue by jamescormchis** [microsoft/vcpkg#28768]
**Host Environment**

- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**

`./vcpkg install xxxx`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by jamescormchis** [comment]
A rather nasty virus is included in your download,   Please fix your work, and don't put viruses on other people's machines!

**Comment by Cheney-W** [comment]
I think this should be antivirus software false alarm.
`png-fix-itxt.exe` is not provided by vcpkg, but a tool provided by the port libpng to fix its own problems. Every user who uses the library `libpng` will build this tool, whether or not the port is built via vcpkg.

Information about this tool on upstream:
https://github.com/glennrp/libpng/blob/libpng16/libpng-manual.txt#:~:text=Libpng%2D1.6.0%20and,the%20libpng%20distribution.
https://github.com/glennrp/libpng/blob/5a0b7e9c29ec23f87c601622cb2db01781a6cbba/CMakeLists.txt#:~:text=add_executable(png%2Dfix,png%2Dfix%2Ditxt)

If you are not sure about its security, I think you should submit a question to https://github.com/glennrp/libpng to confirm if `png-fix-itxt.exe` is a virus.

**Comment by Neumann-A** [comment]
> A rather nasty virus is included in your download, Please fix your work, and don't put viruses on other people's machines!

If it is not a false positiv it is definitly not coming from vcpkg.....

**Comment by jamescormchis** [comment]
I do believe someone just has to submit the file to total virus website on
your end. It comes up as "The file
C:\vcpkg\buildtrees\libpng\x86-windows-dbg\png-fix-itxt.exe is infected
with *Gen:Variant.Fugrafa.270230*. The threat has been successfully
blocked, your device is safe."  I've a good antivirus package on my end, it
seems to be doing the job. Also, on the build, that file threw an error,
out of all the files that were built. I don't think it is a false positive
for a virus.

The total virus checker site is here:
https://www.virustotal.com/gui/home/upload

It will check with several dozen antiviral packages, if they all come up,
or the majority come up with the same message, than there is a virus.

Jim

**Comment by dg0yt** [comment]
> I do believe someone just has to submit the file to total virus website on your end.

It is a file which was created on your computer (during the build). I doubt that another computer will build the bitwise identical file.
Alternatively, the file may come from the artifact cache used in your personal vcpkg setup.
In any case, it is not "included in your download".

> I've a good antivirus package on my end, it seems to be doing the job.

It does the job to detect and remove (some) viruses. It won't tell how they got into a particular binary which was built on your computer. There might be infected tools that were invoked while building the file.
But the AV should print the name of the claimed threat.

**Comment by jamescormchis** [comment]
Thanks

Jim

**Comment by jimwang118** [comment]
I think this should be antivirus software false alarm.
png-fix-itxt.exe is not provided by vcpkg, but a tool provided by the port libpng to fix its own problems. Every user who uses the library libpng will build this tool, whether or not the port is built via vcpkg.

Information about this tool on upstream:
https://github.com/glennrp/libpng/blob/libpng16/libpng-manual.txt#:~:text=Libpng%2D1.6.0%20and,the%20libpng%20distribution.
https://github.com/glennrp/libpng/blob/5a0b7e9c29ec23f87c601622cb2db01781a6cbba/CMakeLists.txt#:~:text=add_executable(png%2Dfix,png%2Dfix%2Ditxt)

If you are not sure about its security, I think you should submit a question to https://github.com/glennrp/libpng to confirm if png-fix-itxt.exe is a virus.
I think this issue can be closed, if someone has new idea, please reopen this issue.
