### ISSUE TITLE
catch2 build failure

### ISSUE THREAD

**Issue by xbotuk** [microsoft/vcpkg#28762]
**Host Environment**
Windows 11 22H2
Visual Studio 2022 latest
cmake version 3.25.1

**To Reproduce**

vcpkg install catch2

**Failure logs**

Computing installation plan...
The following packages will be built and installed:
    catch2[core]:x64-windows -> 3.2.1
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\User\AppData\Local\vcpkg\archives in 202.8 us. Use --debug to see more details.
Installing 1/1 catch2:x64-windows...
Building catch2[core]:x64-windows...
-- Note: catch2 only supports static library linkage. Building static library.
CMake Error at scripts/cmake/vcpkg_minimum_required.cmake:29 (message):
  Your vcpkg executable is from 2022-10-17 which is older than required by
  the caller of vcpkg_minimum_required(VERSION 2022-11-10).  Please
  re-acquire vcpkg by running bootstrap-vcpkg.
Call Stack (most recent call first):
  ports/catch2/portfile.cmake:4 (vcpkg_minimum_required)
  scripts/ports.cmake:147 (include)

error: building catch2:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+catch2
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[catch2]+Build+error
Include '[catch2] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-10-17-3247920fbdd47d08f36cbd480addd9890d3c2435
    vcpkg-scripts version: 12c2a93b4 2023-01-05 (12 hours ago)

**Comment by dg0yt** [comment]
> CMake Error at scripts/cmake/vcpkg_minimum_required.cmake:29 (message): 
> Your vcpkg executable is from 2022-10-17 which is older than required by the caller of vcpkg_minimum_required(VERSION 2022-11-10). 
> Please re-acquire vcpkg by running bootstrap-vcpkg. 

Just that.

**Comment by JonLiu1993** [comment]
@xbotuk, thanks for posting this issue, please modify vcpkg_minimum_required(VERSION 2022-11-10) to vcpkg_minimum_required(VERSION 2022-10-12) in portfile.cmake file can solve this issue.

**Comment by dg0yt** [comment]
@xbotuk Just re-run bootstrap. You will have to do it anyways, sooner or later.

**Comment by quyykk** [comment]
Yet another reason to merge #27692 sooner rather than later

**Comment by xbotuk** [comment]
bootstrap-vcpkg seems to have resolved the issue. Thanks to @dg0yt
