### ISSUE TITLE
[opentelemetry] 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug'

### ISSUE THREAD

**Issue by bobsira** [microsoft/vcpkg#28776]
**Describe the bug**
I have installed OpenTelemetry using VCPKG. When I build my project via Visual Studio 2022 I am getting the following error:
`error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in ConfigFileParser.obj` I've attached the full error logs.

I had installed opentelemetry-cpp:x64-windows which was causing the errors above. I then installed opentelemetry-cpp:x64-windows-static-md  because it appears that the mismatch happens due to the compiler build options but I'm still getting the same errors when I buiild the project from Visual Studio 2022. 

**Environment**
- OS: Windows
- Compiler: Microsoft Visual C++ compiler

**To Reproduce**
I am trying to integrate OpenTelemetry to our tool, Log Monitor, https://github.com/microsoft/windows-container-tools/tree/main/LogMonitor/src/LogMonitor

I used the following commands to install OpenTelemetry on my machine via VCPKG

```
1. vcpkg install opentelemetry-cpp
2. vcpkg install opentelemetry-cpp:x64-windows
3. vcpkg install opentelemetry-cpp:x64-windows-static-md 
```

**Expected behavior**
Is there something that I'm missing to make Visual Studio pick opentelemetry-cpp:x64-windows-static-md  instead of opentelemetry-cpp:x64-windows so that I can build my project or what do I need to do to address these errors?

**Failure logs**
[otellinkerror.error.txt](https://github.com/microsoft/vcpkg/files/10361906/otellinkerror.error.txt)

**Comment by FrankXie05** [comment]
Please install the latest build tools in the `Visual Studio Installer`. 
![image](https://user-images.githubusercontent.com/65999885/211260059-4778d49e-8999-48a6-89c2-306b63c89fc2.png)
![image](https://user-images.githubusercontent.com/65999885/211260190-9e7ca5d1-c0f9-4856-8671-74eb886c7a00.png)
![image](https://user-images.githubusercontent.com/65999885/211260208-94a8a404-1f63-41c3-950e-dd58e1ea8bb0.png)
![image](https://user-images.githubusercontent.com/65999885/211260254-496ca89d-368e-4980-a0dd-43f382e7a3ed.png)

**Comment by FrankXie05** [comment]
@bobsira Upstream added the use of vcpkg to export dll builds, which conflicts with https://github.com/microsoft/vcpkg/blob/25f613278886a8055aded1bffb14daba98c39d6c/ports/opentelemetry-cpp/portfile.cmake#L2 If the upstream supports dynamic builds, this should be removed.
https://github.com/open-telemetry/opentelemetry-cpp/blob/4daca390e9ca672420a9fad05fb70cac993089d6/CMakeLists.txt#L272

**Comment by bobsira** [comment]
I'm leaving this comment here just incase it might help someone:

To sort the dynamic vs static linking error for me,

I installed the x64-windows-static triplet using  vcpkg install opentelemetry-cpp:x64-windows-static


//and add below to our <SolutionName>.vcxproj under <PropertyGroup Label="Globals">
<VcpkgTriplet Condition="'$(Platform)'=='Win32'">x86-windows-static</VcpkgTriplet>
<VcpkgTriplet Condition="'$(Platform)'=='x64'">x64-windows-static</VcpkgTriplet>


And had this working.

**Comment by dg0yt** [comment]
@FrankXie05 AFAIU your comments were targeted at the *library* linkage, but the issue is about the *CRT* linkage.

@bobsira The vcpkg triplet's CRT linkage must match you project's CRT linkage. You started with `x64-windows` which uses dynamic CRT linkage, as does `x64-windows-static-md`. If you want to use static CRT linkage, you must use x64-windows-static.
But I don't use MSVS and can't tell you why it didn't work well automatically, assuming proper integration.
https://learn.microsoft.com/en-us/vcpkg/users/buildsystems/msbuild-integration
