### ISSUE TITLE
[vtk-dicom] build failure

### ISSUE THREAD

**Issue by MikeKen-Ken** [microsoft/vcpkg#28781]
**Host Environment**

- OS: [Windows]
- Compiler: Visual Studio Community 2022 Release - amd64, in vscode

**Steps to reproduce the behavior:**

Use the `vcpkg.json` to install `vtk-dicom`

**Failure logs**

C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:843 (_find_package):
By not providing \"FindDICOM.cmake\" in CMAKE_MODULE_PATH this project has\nasked CMake to find a package configuration file provided by \"DICOM\", but\nCMake did not find one.

Could not find a package configuration file provided by \"DICOM-\" with any\nof the following names:

DICOM-Config.cmake
dicom-config.cmake

**Additional context**

I found someone who had a similar https://github.com/microsoft/vcpkg/pull/12839.

But I installed the latest version 0.8.14, and I found the corresponding file in the installation directory. I'm not sure if it's relevant to the above question.

**Comment by dg0yt** [comment]
Duplicates #12813.
