### ISSUE TITLE
REGRESSION: xxhash:* failed with FILE_CONFLICTS

### ISSUE THREAD

**Issue by cnSchwarzer** [microsoft/vcpkg#28783]
REGRESSION: xxhash:* failed with FILE_CONFLICTS and blocks this PR

_Originally posted by @cnSchwarzer in https://github.com/microsoft/vcpkg/issues/28467#issuecomment-1374364956_

**Comment by dg0yt** [comment]
#28748

**Comment by dg0yt** [comment]
Duplicates #28747.
