### ISSUE TITLE
[New Port Request] nappgui

### ISSUE THREAD

**Issue by ragsaq** [microsoft/vcpkg#28800]
Library name: nappgui

Library description: NAppGUI is a professional SDK to build cross-platform desktop applications using The C Programming Language (ANSI C90). NAppGUI has built as a lightweight layer on top of the operating system native APIs, that allows create portable programs extremelly fast and small without any external dependency.

Source repository URL: https://github.com/frang75/nappgui_src

Project homepage (if different from the source repository): https://www.nappgui.com/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
