### ISSUE TITLE
[icu] Build error  building icu:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Kruthika-21** [microsoft/vcpkg#28815]
**Host Environment**

- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**

`./vcpkg install xxxx`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by MonicaLiu0311** [comment]
Please provide detailed error logs.

**Comment by aizuon** [comment]
> Please provide detailed error logs.

```
/usr/bin/install: cannot create regular file 'E:/vcpkg/packages/icu_x64-windows/E/vcpkg/installed/x64-windows/debug/lib/icudtd72.dll': No such file or directory
-- return status = 1
Error installing library. Failed command: cd ../lib/ && /usr/bin/install -c icudtd72.dll E:/vcpkg/packages/icu_x64-windows/E/vcpkg/installed/x64-windows/debug/lib/icudtd72.dll
make[1]: *** [Makefile:185: install-local] Error 1
make: *** [Makefile:153: install-recursive] Error 2
```

Failure after https://github.com/microsoft/vcpkg/pull/28794, install path has issues

**Comment by dg0yt** [comment]
> `E:/vcpkg/packages/icu_x64-windows/E/vcpkg/installed/x64-windows/debug/lib/icudtd72.dll`

This looks like a bad interpretation of an absolute (MSYS) path `/E/vcpkg/installed/x64-windows/debug/lib/icudtd72.dll`, now prefixed with `E:/vcpkg/packages/icu_x64-windows`.

It would help to tell more about the setup where this happens. (I see `E:/vcpkg` and `x64-windows`.) The build passed CI, and there were no relevant portfile changes in #28794.

**Comment by nickdademo** [comment]
Possibly related: https://github.com/microsoft/vcpkg/issues/27419
