### ISSUE TITLE
error: building zlib:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by anshakeel** [microsoft/vcpkg#28811]
**Host Environment**

- OS: [Windows 10 Enterprise]
- Compiler: revision

**To Reproduce**

`./vcpkg install sqlite3[core,tool]:x64-windows tiff:x64-windows curl:x64-windows

**Failure logs**

error: building zlib:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+zlib
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[zlib]+Build+error
Include '[zlib] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: 739824a6d 2023-01-07 (2 days ago)

**Additional context**

Main goal is to Install Proj C++. Following this Guide : https://proj.org/install.html#compilation-and-installation-from-source-code. While installing Sqlite3, crul and other dependencies, this error occur.
Error results in command : vcpkg.exe install sqlite3[core,tool]:x64-windows tiff:x64-windows curl:x64-windows

**Comment by dg0yt** [comment]
> error: building zlib:x64-windows failed with: BUILD_FAILED

Your toolchain is incomplete.

**Comment by Adela0814** [comment]
@anshakeel  could you please provide the full failure logs? Thanks.
