### ISSUE TITLE
[atlmfc] build failure

### ISSUE THREAD

**Issue by Brooklyn2001** [microsoft/vcpkg#28814]
**Host Environment**

- OS: Windows 10
- Compiler: VS2019

**To Reproduce**

`./vcpkg install atlmfc:x64-windows`

**Failure logs**

C:\dev\vcpkg>vcpkg.exe install atlmfc:x64-windows                                                                       Computing installation plan...                                                                                     10:57The following packages will be built and installed:                                                                         atlmfc[core]:x64-windows -> 0#1                                                                                     Detecting compiler hash for triplet x64-windows...                                                                      Restored 0 package(s) from C:\Users\Sergey\AppData\Local\vcpkg\archives in 391.3 us. Use --debug to see more details.   Installing 1/1 atlmfc:x64-windows...                                                                                    Building atlmfc[core]:x64-windows...                                                                                    CMake Error at ports/atlmfc/portfile.cmake:7 (message):                                                                   Unable to locate 'afxres.h'.  Ensure you have installed the ATL/MFC                                                     component of Visual Studio.                                                                                           Call Stack (most recent call first):                                                                                      scripts/ports.cmake:147 (include) 

[stdout-x64-windows.log](https://github.com/microsoft/vcpkg/files/10371417/stdout-x64-windows.log)

**Comment by FrankXie05** [comment]
Could you please make sure you downloaded the install ATL/MFC component?  :)
![image](https://user-images.githubusercontent.com/95600143/176336710-29b88c13-b0cb-44a6-bf91-ba5a8768e066.png)

**Comment by FrankXie05** [comment]
See issue https://github.com/microsoft/vcpkg/issues/10460

**Comment by Brooklyn2001** [comment]
It turns out that you should have installed ATL/MFC for Visual Studio Build Tools, not for Visual Studio Community.
