### ISSUE TITLE
[quantlib] build failure at windows

### ISSUE THREAD

**Issue by KRJackLee** [microsoft/vcpkg#28838]
**Host Environment**

- OS: Windows10
- Compiler: MSVC (from Visual Studio 2019)

**To Reproduce**

`./vcpkg install quantlib:x64-windows`

**Failure logs**
```
Computing installation plan...
quantlib[core]:x64-windows is only supported on '!(windows & !staticcrt)'
```

**Additional context**
I raised a discussion #28826, with more details. 
It seems a modification QuantLib made at QuantLib/cmake/Platform.cmake, that disable .dll build for MSVC. But it shouldn't disable entire build for quantlib at MSVC. How can get it around?
```
// https://github.com/lballabio/QuantLib/blob/7bfe85c671a8fc4c5abe133032969c34d2e59963/cmake/Platform.cmake#L5-L14
    set(CMAKE_MSVC_RUNTIME_LIBRARY
        "MultiThreaded$<$<CONFIG:Debug>:Debug>$<$<BOOL:${BUILD_SHARED_LIBS}>:DLL>")

    # Export all symbols so MSVC can populate the .lib and .dll
    if (BUILD_SHARED_LIBS)
        # Temp: disable DLL builds on MSVC
        message(FATAL_ERROR
            "Shared library (DLL) builds for QuantLib on MSVC are not supported")
        set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)
    endif()
```

**Comment by MonicaLiu0311** [comment]
Thanks for your feedback, please report this issue upstream ([QuantLib](https://github.com/lballabio/QuantLib)).

**Comment by MonicaLiu0311** [comment]
Depend on: https://github.com/lballabio/QuantLib/issues/1556

**Comment by MonicaLiu0311** [comment]
Quantlib has been updated to the new version `v1.29` from upstream, has your problem been solved?

Related PR #29006.
