### ISSUE TITLE
libsndfile cmake install is broken

### ISSUE THREAD

**Issue by l0calh05t** [Microsoft/vcpkg#2883]
When using libsndfile via cmake, I get the following message:

```
CMake Error at D:/development/vcpkg/installed/x64-windows-static/share/libsndfile/cmake/LibSndFileTargets.cmake:77 (message):
  The imported target "sndfile-static" references the file

     "D:/development/vcpkg/installed/x64-windows-static/share/libsndfile/lib/libsndfile.lib"

  but this file does not exist.
```

The actual file location(s) are `D:\development\vcpkg\installed\x64-windows-static\lib\libsndfile.lib` and `D:\development\vcpkg\installed\x64-windows-static\debug\lib\libsndfile.lib`, respectively.

Furthermore, while `LibSndFileTargets-release.cmake` is present, `LibSndFileTargets-debug.cmake` is missing entirely.

**Comment by l0calh05t** [comment]
Similarly, the include directories are wrong.

**Comment by l0calh05t** [comment]
And the shared build includes the lib folder instead of the include folder

**Comment by ras0219-msft** [comment]
Thanks for reporting this issue! I've pushed a fix to master; please try it out and let us know if it fixes the problem :)

**Comment by l0calh05t** [comment]
Yes, everything seems to work fine now, thank you!
