### ISSUE TITLE
[wxwidgets] "webview" feature should be able to be used on Linux

### ISSUE THREAD

**Issue by fishnet37222** [microsoft/vcpkg#28833]
****

I'm currently unable to use the wxWebView control on Linux when using vcpkg to build wxWidgets.

**Proposed solution**
The currently existing "webview feature should be modified to work on Linux as well as Windows.  If running on Linux, only the "wxUSE_WEBVIEW" flag should be enabled since the Edge backend is not available on Linux.

**Describe alternatives you've considered**
The only alternative would be to build wxWidgets myself outside of vcpkg which defeats the purpose of using vcpkg.

**Additional context**
I've attached a sample project that demonstrates the issue.  When I try to build the project, I get an error about "libwx_gtk3u_webview-3.2.a" missing.  If I add "webview" to the list of wxWidgets features in "vcpkg.json", the configuration fails with an error about "webview" only being available on Windows.

[minesweeper.zip](https://github.com/microsoft/vcpkg/files/10375886/minesweeper.zip)

**Comment by FrankXie05** [comment]
The `WebView2` control uses Microsoft Edge as the rendering engine to display the web content in native apps.  It doesn't work on Linux. 
https://learn.microsoft.com/en-us/microsoft-edge/webview2/

**Comment by fishnet37222** [comment]
The "webview" feature should use WebView2 on Windows and WebKit2 on Linux.  Right now, if you don't specify the "webview" feature on Linux, you can't use the [wxWebView](https://docs.wxwidgets.org/3.2/classwx_web_view.html) control.  That control should be available on both Windows and Linux.

**Comment by FrankXie05** [comment]
We need port `WebKit2` or system package `libwebkit2gtk-4.0-dev`.

**Comment by FrankXie05** [comment]
Adding warning information is only a temporary solution, the best is to add port `WebKit2`.

**Comment by FrankXie05** [comment]
This issue hasn’t been updated for a long time; if it is still an issue, please reopen this issue.
