### ISSUE TITLE
[New Port Request] QGIS

### ISSUE THREAD

**Issue by HPDell** [microsoft/vcpkg#28847]
Library name: QGIS

Library description: QGIS is a full-featured, user-friendly, free-and-open-source (FOSS) geographical information system (GIS) that runs on Unix platforms, Windows, and MacOS.

Source repository URL: https://github.com/QGIS/QGIS

Project homepage (if different from the source repository): https://qgis.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

- Python Bindings
- Components based on Qt Quick
- Web Server

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
