### ISSUE TITLE
[ffmpeg] Build error x64-windows

### ISSUE THREAD

**Issue by massimobortolato** [microsoft/vcpkg#28841]
**Host Environment**

- OS: Windowws x64
- Compiler: MSVC 14.34.31933

**To Reproduce**

`./vcpkg install ffmpeg --triplet=x64-windows`

**Failure logs**

    -- Building Release Options:
    -- Building ffmpeg for Release
    CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
        Command failed: D:/vcpkg/downloads/tools/msys2/79d5b6b790550399/usr/bin/bash.exe ./build.sh
        Working Directory: D:/vcpkg/buildtrees/ffmpeg/x64-windows-rel
        Error code: 1
        See logs for more information:
          D:\vcpkg\buildtrees\ffmpeg\build-x64-windows-rel-out.log
    
    Call Stack (most recent call first):
      ports/ffmpeg/portfile.cmake:543 (vcpkg_execute_required_process)
      scripts/ports.cmake:147 (include)
    
    error: building ffmpeg:x64-windows failed with: BUILD_FAILED
    error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
    Then check for known issues at:
        https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+ffmpeg
    You can submit a new issue at:
        https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[ffmpeg]+Build+error
    Include '[ffmpeg] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
        vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
        vcpkg-scripts version: f14984af3 2023-01-09 (22 hours ago)

[build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/10380259/build-x64-windows-rel-out.log)
[cmake-get-vars-x64-windows-rel.cmake.log](https://github.com/microsoft/vcpkg/files/10380264/cmake-get-vars-x64-windows-rel.cmake.log)
[cmake-get-vars-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/10380272/cmake-get-vars-x64-windows-out.log)
[x64-windows.vcpkg_abi_info.txt](https://github.com/microsoft/vcpkg/files/10380274/x64-windows.vcpkg_abi_info.txt)

**Additional context**

I ran

    git pull

and

    vcpkg update

**Comment by Neumann-A** [comment]
`Include the log file "ffbuild/config.log" produced by configure as this will help`

a copy of that file should also be in the buildtree folder but slightly different named.

**Comment by massimobortolato** [comment]
[config.log](https://github.com/microsoft/vcpkg/files/10383167/config.log)

Here it is

**Comment by Neumann-A** [comment]
Looks strange. Seems like the compiler detection failed for some reason and it uses gnu syntax instead of msvc

**Comment by Neumann-A** [comment]
I also need a repo to fix it. In which shell was the build executed in?

**Comment by massimobortolato** [comment]
Windows Terminal
Version: 1.15.3466.0

**Comment by Neumann-A** [comment]
So you have:
```
END /c/Users/massi/AppData/Local/Temp/ffconf.QCvE3YMA/test.c
cl.exe @D:/vcpkg/buildtrees/ffmpeg/x64-windows-rel/cflags.rsp -nologo -DHAVE_UNISTD_H=0 -c -Fo/c/Users/massi/AppData/Local/Temp/ffconf.QCvE3YMA/test.o /c/Users/massi/AppData/Local/Temp/ffconf.QCvE3YMA/test.c
test.c
```
I have:
```
END ./ffconf.627ptmsz/test.c
cl.exe @E:/vcpkg_folders/master_clean/buildtrees/ffmpeg/x64-windows-rel/cflags.rsp -nologo -DHAVE_UNISTD_H=0 -c -Fo./ffconf.627ptmsz/test.o ./ffconf.627ptmsz/test.c
test.c
```

the additional `/c/Users/massi/AppData/Local/Temp/` looks wrong.

**Comment by massimobortolato** [comment]
Ok, any hints on how I can solve it?
Thanks

**Comment by Neumann-A** [comment]
> Ok, any hints on how I can solve it?

You need to manually debug the configure script to see where that extra `/c/Users/massi/AppData/Local/Temp/` might come from. Probably requires adding some `echo $<varname>` modifications

**Comment by massimobortolato** [comment]
Ok thank you

**Comment by k0zmo** [comment]
I have the same issue as OP on one of my machine.

FFmpeg port uses `vcpkg_cmake_get_vars` function which generates `cmake-get-vars-x64-windows-{dbg,rel}.cmake.log` files in buildtree with a list of `VCPKG_DETECTED_X` variables. One of these variables should be `VCPKG_DETECTED_MSVC`: https://github.com/microsoft/vcpkg/blob/036769f5d6da667391c9240bc7ca56e84cacd5b1/ports/vcpkg-cmake-get-vars/cmake_get_vars/CMakeLists.txt#L7-L14
In my case there's no MSVC there (as well as `VCPKG_DETECTED_CMAKE_SIZEOF_VOID_P` and `MSVC_VERSION`). The value of this variable is then used to optionally append `--toolchain=msvc` to FFmpeg's configure script.

The reason that there aren't these variables is at some point in the past this function was part of vcpkg-cmake port (before 54951282f33d1ffed5fa9fa9a73a6c0466ac246d): https://github.com/microsoft/vcpkg/blob/dd42206f86a7b9f7747ccb63fa0e36baaab5fa1e/ports/vcpkg-cmake/cmake_get_vars/CMakeLists.txt#L7-L11

Then the "missing" variables were added but OP and I haven't updated vcpkg itself and after that the function was moved to separate port - `vcpkg-cmake-get-vars` (bae8f8c7d837c631ca72daec4b14e243824135a5). That however caused the old files `vcpkg_cmake_get_vars.cmake` and `cmake_get_vars\CMakeLists.txt` from vcpkg-cmake port to stay in `${VCPKG_ROOT}\installed\x64-windows\share\vcpkg-cmake`. Somehow vcpkg picks that file and thus `cmake-get-vars-x64-windows-{dbg,rel}.cmake.log` misses proper variables.

**Comment by massimobortolato** [comment]
@k0zmo did you solve it? I still cannot build it.

**Comment by massimobortolato** [comment]
Ok, I commented the line
```
#if(VCPKG_DETECTED_MSVC)
```
and its relative ```#endif``` in ```${VCPKG_ROOT}\ports\ffmpeg\portfile.cmake```
This solved the issue for me

**Comment by Neumann-A** [comment]
With manifest mode this would not have happened. We could add a version constrain for vcpkg-cmake-get-vard but that will be ignored in classic mode. In general classic mode expects to be run from a clean start and not arbitary mixing vcpkg commits.
 Nothing to fix here -> user error in classic mode. If you want a simple fix instead of reinstalling everything consider simple copying the new files over into the installed tree.
