### ISSUE TITLE
undefined reference to `cv::imread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'

### ISSUE THREAD

**Issue by ezewu** [microsoft/vcpkg#28872]
vcpkg install opencv:x64-windows

```cmake
cmake_minimum_required(VERSION 3.24)
project(cpp1)

set(CMAKE_CXX_STANDARD 17)

add_executable(cpp1 main.cpp)

find_package(OpenCV CONFIG REQUIRED)

target_link_libraries(cpp1 PRIVATE opencv_ml opencv_dnn opencv_core opencv_flann)
```

```c++
#include <opencv2/opencv.hpp>

using namespace cv;
using namespace std;

int main() {
    Mat mat=imread("../001.jpg");
    return 0;
}
```

An error is reported when running in CLion

**Comment by xiaozhuai** [comment]
You need to link to `opencv_imgcodecs` too
change this line to
```
target_link_libraries(cpp1 PRIVATE opencv_ml opencv_dnn opencv_core opencv_flann opencv_imgcodecs)
```
or you can just link to all opencv libraries if you can't tell which lib you need
```
cmake_minimum_required(VERSION 3.24)
project(cpp1)

set(CMAKE_CXX_STANDARD 17)

add_executable(cpp1 main.cpp)

find_package(OpenCV CONFIG REQUIRED)

target_link_libraries(cpp1 PRIVATE opencv_ml opencv_dnn opencv_core opencv_flann)

target_include_directories(cpp1 PRIVATE ${OpenCV_INCLUDE_DIRS})
target_link_libraries(cpp1 PRIVATE ${OpenCV_LIBS})
```

**Comment by wzj219** [comment]
The version of opencv you installed is incorrect. You should install opencv2, for example: vcpkg install opencv2: x64-windows. In addition, in the CMakeList.txt file, Set the lookup path of opencv2 before the find_package() function, for example: set (OpenCV_DIR "${VCPKG_INSTALLED_DIR}/x64 windows/share/opencv2").

**Comment by ezewu** [comment]
It seems that the error generated by this library is not found
I also tried other libraries, it also reported an error

 undefined reference to `cv::imread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'

**Comment by ezewu** [comment]
![12143345](https://user-images.githubusercontent.com/22029449/211994843-646b55fa-8107-4c64-91bc-02db070a7a00.png)

jsoncpp

**Comment by xiaozhuai** [comment]
> The version of opencv you installed is incorrect. You should install opencv2, for example: vcpkg install opencv2: x64-windows. In addition, in the CMakeList.txt file, Set the lookup path of opencv2 before the find_package() function, for example: set (OpenCV_DIR "${VCPKG_INSTALLED_DIR}/x64 windows/share/opencv2").

No, this is not right.
```cpp
#include <opencv2/opencv.hpp>
```
this means api version is 2.
And opencv4 supports api version 2.
So this is not the case.

**Comment by xiaozhuai** [comment]
> cmake_minimum_required(VERSION 3.24)
> project(cpp1)
> 
> set(CMAKE_CXX_STANDARD 17)
> 
> add_executable(cpp1 main.cpp)
> 
> find_package(OpenCV CONFIG REQUIRED)
> 
> target_include_directories(cpp1 PRIVATE ${OpenCV_INCLUDE_DIRS})
> target_link_libraries(cpp1 PRIVATE ${OpenCV_LIBS})

Try this 
```
cmake_minimum_required(VERSION 3.24)
project(cpp1)

set(CMAKE_CXX_STANDARD 17)

add_executable(cpp1 main.cpp)

find_package(OpenCV CONFIG REQUIRED)

target_include_directories(cpp1 PRIVATE ${OpenCV_INCLUDE_DIRS})
target_link_libraries(cpp1 PRIVATE ${OpenCV_LIBS})
message("!!! ${OpenCV_LIBS}")
```
See what prints.

**Comment by xiaozhuai** [comment]
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/4773701/212018957-8924fcc2-d4b2-4b32-9fd4-a68ec9c25a96.png">

@ezewu You did not set `CMAKE_TOOLCHAIN_FILE` correctly

**Comment by xiaozhuai** [comment]
Add this to your cmake configure options
```
-DVCPKG_TARGET_TRIPLET=x64-windows
-DCMAKE_TOOLCHAIN_FILE="${your_vcpkg_path}\scripts\buildsystems\vcpkg.cmake"
```

**Comment by ezewu** [comment]
> <img alt="图片" width="1181" src="https://user-images.githubusercontent.com/4773701/212018957-8924fcc2-d4b2-4b32-9fd4-a68ec9c25a96.png">
> 
> @ezewu你没有设置`CMAKE_TOOLCHAIN_FILE`正确

-DCMAKE_TOOLCHAIN_FILE is set correctly, set for CLion according to the vcpkg document

**Comment by ezewu** [comment]
> 将此添加到您的 cmake 配置选项
> 
> ```
> -DVCPKG_TARGET_TRIPLET=x64-windows
> -DCMAKE_TOOLCHAIN_FILE="${your_vcpkg_path}\scripts\buildsystems\vcpkg.cmake"
> ```
> 
> 您可以在此页面上获得更多信息，请在提问之前阅读文档。
> 
> https://vcpkg.io/en/docs/users/buildsystems/cmake-integration.html

Or report undefined reference to

**Comment by xiaozhuai** [comment]
> > cmake_minimum_required(VERSION 3.24)
> > project(cpp1)
> > set(CMAKE_CXX_STANDARD 17)
> > add_executable(cpp1 main.cpp)
> > find_package(OpenCV CONFIG REQUIRED)
> > target_include_directories(cpp1 PRIVATE ${OpenCV_INCLUDE_DIRS})
> > target_link_libraries(cpp1 PRIVATE ${OpenCV_LIBS})
> 
> Try this
> 
> ```cmake
> cmake_minimum_required(VERSION 3.24)
> project(cpp1)
> 
> set(CMAKE_CXX_STANDARD 17)
> 
> add_executable(cpp1 main.cpp)
> 
> find_package(OpenCV CONFIG REQUIRED)
> 
> target_include_directories(cpp1 PRIVATE ${OpenCV_INCLUDE_DIRS})
> target_link_libraries(cpp1 PRIVATE ${OpenCV_LIBS})
> message("!!! ${OpenCV_LIBS}")
> ```
> 
> See what prints.

Then try this and see what prints

**Comment by xiaozhuai** [comment]
<img width="543" alt="image" src="https://user-images.githubusercontent.com/4773701/212023270-044cf1f1-78e8-4939-a771-a8c3f8f37f3d.png">

I got your problem, you are trying to build under mingw toolchains, but x64-windows use msvc toolchains.
You should reset your clion toolchain or use other triplet

**Comment by ezewu** [comment]
> <img alt="图片" width="543" src="https://user-images.githubusercontent.com/4773701/212023270-044cf1f1-78e8-4939-a771-a8c3f8f37f3d.png">
> 
> 我发现了你的问题，你正试图在 mingw 工具链下构建，但`x64-windows`triplet 使用 msvc 工具链。 您应该将 CLion 工具链重置为 msvc，或者您应该使用其他三元组，例如`x64-mingw-dynamic`.

Ok, thank you, I found the reason, I installed CLion without configuring anything else

**Comment by xiaozhuai** [comment]
> > <img alt="图片" width="543" src="https://user-images.githubusercontent.com/4773701/212023270-044cf1f1-78e8-4939-a771-a8c3f8f37f3d.png">
> > 我发现了你的问题，你正试图在 mingw 工具链下构建，但`x64-windows`triplet 使用 msvc 工具链。 您应该将 CLion 工具链重置为 msvc，或者您应该使用其他三元组，例如`x64-mingw-dynamic`.
> 
> Ok, thank you, I found the reason, I installed CLion without configuring anything else

If this solve your problem, please close this issue.

**Comment by xiaozhuai** [comment]
If this solve your problem, please close this issue.

**Comment by jiafuz** [comment]
may be incorrect opencv version
