### ISSUE TITLE
[New Port Request] xtensor-zarr

### ISSUE THREAD

**Issue by jaw** [microsoft/vcpkg#28875]
Library name: xtensor-zarr

Library description: ZARR implementation by/for Xtensor
ZARR is a storage format for multi-dimensional data.

Source repository URL: https://github.com/xtensor-stack/xtensor-zarr

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
There are already a bunch of xtensor-* libs in vcpkg.

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
