### ISSUE TITLE
[live555] build failure

### ISSUE THREAD

**Issue by eunsikNota** [microsoft/vcpkg#28870]
**Host Environment**

- OS: Windows
- Compiler: Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.4.4

**To Reproduce**

>vcpkg install  live555

**Failure logs**

![image](https://user-images.githubusercontent.com/85149224/211732398-dddee859-3dcf-4b3b-aaa5-8dc5050613ac.png)

**Additional context**

A linking error occurs.

**Comment by eunsikNota** [comment]
I also checked that the lib file is in the installed folder.

![image](https://user-images.githubusercontent.com/85149224/211733084-a3f7248c-236f-431d-93ae-6ae26b080e59.png)

**Comment by Cheney-W** [comment]
Could you please provide me with a detailed reproduction step? Focus on your operations in VS. Or you could send me the project you reproduce the problem. Thank you!

**Comment by BillyONeal** [comment]
This looks like you need to link with ws2_32.lib rather than a problem in live555.

**Comment by eunsikNota** [comment]
@BillyONeal  thank you. i solved the problem
