### ISSUE TITLE
[assimp] Add port with ASSIMP_DOUBLE_PRECISION defined

### ISSUE THREAD

**Issue by Nosenzor** [microsoft/vcpkg#28893]
****
assimp library offer the option to build it with ASSIMP_DOUBLE_PRECISION so we can have mesh defined with double instead of float.

**Is your feature request related to a problem? Please describe.**
I need to read meshes in double precision instead of single precision (float)

**Proposed solution**
Create assimp[double] port to offer a variant.

**Describe alternatives you've considered**
Cloned the assimp repo and built it myself with ASSIMP_DOUBLE_PRECISION on (ie not using vcpkg :-( )
 

**Additional context**
See instruction here : https://github.com/assimp/assimp/blob/master/Build.md

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Due to this option will change types in the API, so this is against the rules of vcpkg. This is the guideline: https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-use-features-to-control-alternatives-in-published-interfaces.
You could set it and open this option on your project like PR #28996.

**Comment by Nosenzor** [comment]
I am not sure to get it. Should I clone the assimp on my side and define ASSIMP_DOUBLE_PRECISION, compile assimp myself or I can use vcpkg through json  assimp[double] ?
BTW Is there a way to list features of a port ?

**Comment by dg0yt** [comment]
> Should I clone the assimp on my side

No.

> I can use vcpkg through json assimp[double] ?

No.

@LilyWangLL suggests that you modify `ports/assimp/portfile.cmake` locally (i.e. in your vcpkg checkout, or in a copy of this port's directory, to be used via overlay ports or registries.

However, this will decouple your copy from port updates. Alternative, you can use a custom overlay triplet (file) which adds the following CMake code to the standard content:
~~~cmake
if(PORT STREQUAL "assimp")
    list(APPEND VCPKGK_CMAKE_CONFIGURE_OPTIONS "-DASSIMP_DOUBLE_PRECISION=ON")
endif()
~~~

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
