### ISSUE TITLE
Can't install opencv on Windows 8.1, x64

### ISSUE THREAD

**Issue by NuclearRazor** [Microsoft/vcpkg#2889]
Hello everyone, i have some issue with installing opencv on my machine:

- **The machine setup:**

Windows 8.1 Pro, x64 (Intel N3540)

- **What i want:**

I want to install Opencv on my laptop and use it in my projects, but i have this errors:

> C:\Windows\system32>vcpkg install opencv
> The following packages will be built and installed:
>   * libjpeg-turbo[core]:x86-windows
>   * liblzma[core]:x86-windows
>   * libpng[core]:x86-windows
>     opencv[core]:x86-windows
>   * protobuf[core]:x86-windows
>   * tiff[core]:x86-windows
> Additional packages (*) will be modified to complete this operation.
> Starting package 1/6: liblzma:x86-windows
> Building package liblzma[core]:x86-windows...
> -- CURRENT_INSTALLED_DIR=C:/LIBS_ETC/vcpkg/installed/x86-windows
> -- DOWNLOADS=C:/LIBS_ETC/vcpkg/downloads
> -- CURRENT_PACKAGES_DIR=C:/LIBS_ETC/vcpkg/packages/liblzma_x86-windows
> -- CURRENT_BUILDTREES_DIR=C:/LIBS_ETC/vcpkg/buildtrees/liblzma
> -- CURRENT_PORT_DIR=C:/LIBS_ETC/vcpkg/ports/liblzma/.
> -- Using cached C:/LIBS_ETC/vcpkg/downloads/xz-5.2.3.tar.gz
> -- Testing integrity of cached file...
> CMake Error at C:/LIBS_ETC/vcpkg/scripts/cmake/vcpkg_download_distfile.cmake:87
> (message):
> 
> 
>   File does not have expected hash:
> 
>           File path: [ C:/LIBS_ETC/vcpkg/downloads/xz-5.2.3.tar.gz ]
>       Expected hash: [ a5eb4f707cf31579d166a6f95dbac45cf7ea181036d1632b4f123a407
> 2f502f8d57cd6e7d0588f0bf831a07b8fc4065d26589a25c399b95ddcf5f73435163da6 ]
>         Actual hash: [ 3b53ccf0243cd4a6a731a898bfdba95c3d22342e7e64f9e9a4a2bce5f
> 74ac809943f570ed92c9077101a178f82f49ece1d1c4bfee1f288ea61d99fb36f6a243e ]
> 
>   Please delete the file and retry if this file should be downloaded again.
> 
> Call Stack (most recent call first):
>   C:/LIBS_ETC/vcpkg/scripts/cmake/vcpkg_download_distfile.cmake:99 (test_hash)
>   C:/LIBS_ETC/vcpkg/ports/liblzma/portfile.cmake:7 (vcpkg_download_distfile)
>   C:/LIBS_ETC/vcpkg/scripts/ports.cmake:72 (include)
> 
> 
> Error: Building package liblzma:x86-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: liblzma:x86-windows
>   Vcpkg version: 0.0.102-2018-01-24-7d9f0a86974a85b94d9a903f130a933e44c76f43
> 
> Additionally, attach any relevant sections from the log files above.

- _If i want to install liblzma (as i understood by stack of calling errors) i get similar errors:_

> C:\Windows\system32>vcpkg install liblzma
> Your feedback is important to improve Vcpkg! Please take 3 minutes to complete o
> ur survey by running: vcpkg contact --survey
> The following packages will be built and installed:
>     liblzma[core]:x86-windows
> Starting package 1/1: liblzma:x86-windows
> Building package liblzma[core]:x86-windows...
> -- CURRENT_INSTALLED_DIR=C:/LIBS_ETC/vcpkg/installed/x86-windows
> -- DOWNLOADS=C:/LIBS_ETC/vcpkg/downloads
> -- CURRENT_PACKAGES_DIR=C:/LIBS_ETC/vcpkg/packages/liblzma_x86-windows
> -- CURRENT_BUILDTREES_DIR=C:/LIBS_ETC/vcpkg/buildtrees/liblzma
> -- CURRENT_PORT_DIR=C:/LIBS_ETC/vcpkg/ports/liblzma/.
> -- Using cached C:/LIBS_ETC/vcpkg/downloads/xz-5.2.3.tar.gz
> -- Testing integrity of cached file...
> CMake Error at C:/LIBS_ETC/vcpkg/scripts/cmake/vcpkg_download_distfile.cmake:87
> (message):
> 
> 
>   File does not have expected hash:
> 
>           File path: [ C:/LIBS_ETC/vcpkg/downloads/xz-5.2.3.tar.gz ]
>       Expected hash: [ a5eb4f707cf31579d166a6f95dbac45cf7ea181036d1632b4f123a407
> 2f502f8d57cd6e7d0588f0bf831a07b8fc4065d26589a25c399b95ddcf5f73435163da6 ]
>         Actual hash: [ 3b53ccf0243cd4a6a731a898bfdba95c3d22342e7e64f9e9a4a2bce5f
> 74ac809943f570ed92c9077101a178f82f49ece1d1c4bfee1f288ea61d99fb36f6a243e ]
> 
>   Please delete the file and retry if this file should be downloaded again.
> 
> Call Stack (most recent call first):
>   C:/LIBS_ETC/vcpkg/scripts/cmake/vcpkg_download_distfile.cmake:99 (test_hash)
>   C:/LIBS_ETC/vcpkg/ports/liblzma/portfile.cmake:7 (vcpkg_download_distfile)
>   C:/LIBS_ETC/vcpkg/scripts/ports.cmake:72 (include)
> 
> 
> Error: Building package liblzma:x86-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: liblzma:x86-windows
>   Vcpkg version: 0.0.102-2018-01-24-7d9f0a86974a85b94d9a903f130a933e44c76f43
> 
> Additionally, attach any relevant sections from the log files above.

P. S. vcpkg is the best what i see for rapid code developing on C++, i'am already install by this boost, boost beast and it's works fine. It will be a great job if anyone help me with that issue.

**Comment by ReyzalX** [comment]
download file does not have expected hash,this may be something wrong with you download file.
`you can delete the file and retry if this file should be downloaded again.`  or 
check if  `C:/LIBS_ETC/vcpkg/downloads/xz-5.2.3.tar.gz ` file is correct!

**Comment by NuclearRazor** [comment]
@ReyzalX thanks! It's helped me!

> Installing package opencv[core]:x86-windows... done
> Elapsed time for package opencv:x86-windows: 53.55 min
> 
> Total elapsed time: 1.194 h

Test project works well :)
