### ISSUE TITLE
[hiberlite] <C++ SQLite3 ORM >

### ISSUE THREAD

**Issue by Pantau123** [microsoft/vcpkg#28897]
****

**Is your feature request related to a problem? Please describe.**
It's a alternative to sqlite_orm which is problematicly to mock

**Proposed solution**
I want a good alternative to sqlite_orm.

**Describe alternatives you've considered**
I sometimes have problems that the linker dies when linking sqlite_orm because the header only solution has a lot of templates. It is impossible to create a mock from sqlite_orm. With hibelite is a little better.

**Additional context**
For the source see https://github.com/paulftw/hiberlite

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
