### ISSUE TITLE
Add ArrayFire

### ISSUE THREAD

**Issue by kryptan** [microsoft/vcpkg#289]
ArrayFire is a general-purpose library for developing software that targets parallel and massively-parallel architectures including CPUs, GPUs, and other hardware acceleration devices.

Repository: https://github.com/arrayfire/arrayfire

**Comment by Voskrese** [comment]
Depends: CUDA + FORTRAN ... hmm ...

CUDA ver 9.2 error MSVC 2017 >> 1913

edit `host_config.h`, my locations CUDA
`C:\Program Files\PGI\win64\2018\cuda\9.2\include\crt\host_config.h`

```
#if _MSC_VER < 1600 || _MSC_VER > 1913
#error -- unsupported Microsoft Visual Studio version! Only the versions 2012, 2013, 2015 and 2017 are supported!
```

to 
`#if _MSC_VER < 1600 || _MSC_VER > 1920`

1920 ... MSVC 2019 ?

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!

**Comment by jacobkahn** [comment]
fyi -- I've opened https://github.com/microsoft/vcpkg/pull/14240, cc @JackBoosY @LilyWangL @Voskrese @kryptan

**Comment by traversaro** [comment]
I think this is solved now that https://github.com/microsoft/vcpkg/pull/14240 is merged.

**Comment by JackBoosY** [comment]
@traversaro Yes, thanks!
