### ISSUE TITLE
[blend2d] Allow building on ARM platforms

### ISSUE THREAD

**Issue by cbrl** [microsoft/vcpkg#28909]
****

**Is your feature request related to a problem? Please describe.**
Blend2d is currently excluded from ARM platforms. However, it appears to support ARM since at least this commit: https://github.com/blend2d/blend2d/commit/da2b485c49536b594d9e2c029735c116d6ef45e6

I haven't done any extensive tests, but I can verify that this port compiles in Ubuntu 20.04 with an `arm64-linux-dynamic` triplet.

**Proposed solution**
Remove the restriction on ARM platforms from the blend2d port, and any dependent ports (e.g. [osgearth](https://github.com/microsoft/vcpkg/blob/4c5be28bfac45e53fa8c4100a1d759a8e5ee97fb/ports/osgearth/vcpkg.json#L57)).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by autoantwort** [comment]
You can test that with `--allow-unsupported`

**Comment by cbrl** [comment]
I actually didn't know about that argument, thanks. However, I had already tried it just by removing the ARM exclusion from the port. I had no problems compiling either Blend2D or the blend2d feature for osgEarth that I mentioned.

**Comment by autoantwort** [comment]
You you willing to create a PR for that? :)
