### ISSUE TITLE
vcpkg_download_distfile timeout

### ISSUE THREAD

**Issue by DanOlivier** [Microsoft/vcpkg#2890]
Hi. 
1. I was just trying to download, build, and install `assimp` dependency, but the download of the *distfile* (`downloads/assimp-assimp-v4.1.0.tar.gz`, in this case) from GitHub kept timing out (even though it only _weighs_ 45MB).
I can't be the only one to which this happens, so what are the work-arounds? 
Just to restart the install as often as it takes to get it to work once? 
If we were to set it explicitly, propagating a value down to `vcpkg_download_distfile`, wouldn't the timeout need to depend on the file size.
Is ti advisable to optionally force vcpkg to clone shallow from GitHub (`--depth=1`), rather than downloading distfiles (slower, but more reliable progress, and potentially restartable if interrupted?)?

2. Is there a more reliable and/or faster alternative to SourceForge?
I was also having problems with files coming from [SourceForge](sourceforge.net) (trying to install `libdisasm`, a dependency of `breakpad`), because the site was reporting errors, and `vcpkg` (cmake, via [file command](https://cmake.org/cmake/help/v3.2/command/file.html)) was then substituting the text of the HTML response into the expected archive (`downloads/libdisasm-0.23.tar.gz`). Adding `/download` to the `URL` parameter (of the call to `vcpkg_download_distfile`) in the portfile (`ports/libdisasm/portfile.cmake`) seemed to help, but that could be an illusion (the download just happened to succeed when I made that change). 
 
Thanks

**Comment by ras0219-msft** [comment]
Thanks for posting this issue!

>what are the work-arounds?

The core workaround is to download the file manually and put it inside the `downloads\` folder.

>Is there a more reliable and/or faster alternative to SourceForge?

I'd love to accept a PR changing the download link to a more reliable source! Unfortunately, the sourceforge link is the only one we're currently aware of for that library.

**Comment by DanOlivier** [comment]
Thanks for the comments.
