### ISSUE TITLE
[New Port Request] agones C++ server client sdk

### ISSUE THREAD

**Issue by hihig2001** [microsoft/vcpkg#28914]
Library name: agones C++ server client SDK

Library description:
Agones is a library for hosting, running and scaling [dedicated game servers](https://en.wikipedia.org/wiki/Game_server#Dedicated_server) on [Kubernetes](https://kubernetes.io/).

The SDKs are integration points for game servers with Agones itself.

and it is C++ SDK.

Source repository URL:
https://github.com/googleforgames/agones/tree/release-1.28.0/sdks/cpp

Project homepage (if different from the source repository):
https://agones.dev/site/
https://agones.dev/site/docs/guides/client-sdks/cpp/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
