### ISSUE TITLE
CASCADED_DUE_TO_MISSING_DEPENDENCIES

### ISSUE THREAD

**Issue by grandprixgp** [Microsoft/vcpkg#2891]
Hesitant to open an issue since I have my doubts that this is a vcpkg issue, mostly because the build is failing on one specific library/dependency - but lack of Google results and the prompt to open an issue at the end of the build error makes me think I might as well.

Building the [Magnum ](http://doc.magnum.graphics/magnum/) library.

Followed [quick start docs](https://github.com/Microsoft/vcpkg#quick-start) and [Magnum vcpkg build docs](http://doc.magnum.graphics/magnum/building.html#building-packages-vcpkg).

https://gist.github.com/grandprixgp/0e4df592550903b810c4f5037c031f54

**Comment by ras0219-msft** [comment]
Hi, thanks for posting this issue with the full logs :D

I was able to reproduce, fix, and confirm the fix locally. It's pushed to master with the tag c267f32b -- please `git pull` and re-run `bootstrap-vcpkg.bat` to get the fix!

**Comment by grandprixgp** [comment]
Sorry if there were some additional logs that I should've posted, I did a cursory search and couldn't find any that seemed relevant.

I can confirm this is fixed. [Full output here.](https://gist.github.com/grandprixgp/2349ccfd48ba472b802290239ef51818)

@mosra (Magnum developer) mentioned that it might be caused by the relatively bleeding edge nature of Magnum compared to other libraries. Thanks for such a quick fix.

**Comment by mosra** [comment]
@ras0219-msft Man, you're doing an amazing job. Thank you!! :)
