### ISSUE TITLE
[GMP] build failure The command line does not respond when installing GMP with vcpkg

### ISSUE THREAD

**Issue by EMILIIIIA** [microsoft/vcpkg#28912]
**Host Environment**

- OS: Windows 10 Family 21H2
- Laptop: Dell G15 5515
- CPU: AMD Ryzen 7 5800H
- RAM: 16GB
- Vcpkg version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
- CMake: cmake-3.25.0-windows-i386
- GMP: gmp-6.2.1

**To Reproduce**

I used `vcpkg install gmp:x64-windows` to install GMP. But after the download of 7z1900.msi was complete(or using cached 7z1900.msi) the CMD did not respond anymore. No crash, no error message and no next step. The task manager shows that vcpkg has no CPU or network usage so I don't think vcpkg is going to the next step. I also tried to install OpenCV and boost using vcpkg. They were installed correctly so I think vcpkg on my computer has no problems. 
I also found that even though my mouse focus was on the CMD window, the command line would lose focus after the command about 7z1900.msi.

**Failure logs**

C:\Users\DELL>vcpkg install gmp:x64-windows\
Computing installation plan...\
The following packages will be built and installed:\
gmp[core]:x64-windows -> 6.2.1#14\
Detecting compiler hash for triplet x64-windows...\
Restored 0 package(s) from C:\Users\DELL\AppData\Local\vcpkg\archives in 1.318 ms. Use --debug to see more details.\
Installing 1/1 gmp:x64-windows...\
Building gmp[core]:x64-windows...\
-- Using cached gmp-6.2.1.tar.xz.\
-- Using cached gmp-arm64-asm-fix-5f32dbc41afc.patch.\
-- Cleaning sources at E:/Program Files/vcpkg/buildtrees/gmp/src/v6.2.1-0c723d4b6f.clean. Use --editable to skip cleaning for the packages you specify.\
-- Extracting source E:/Program Files/vcpkg/downloads/gmp-6.2.1.tar.xz\
-- Applying patch asmflags.patch\
-- Applying patch cross-tools.patch\
-- Applying patch subdirs.patch\
-- Applying patch msvc_symbol.patch\
-- Applying patch arm64-coff.patch\
-- Applying patch E:/Program Files/vcpkg/downloads/gmp-arm64-asm-fix-5f32dbc41afc.patch\
-- Using source at E:/Program Files/vcpkg/buildtrees/gmp/src/v6.2.1-0c723d4b6f.clean\
-- Found external ninja('1.11.0').\
-- Getting CMake variables for x64-windows\
-- Using cached LLVM-12.0.0-win64.7z.exe.\
-- Using cached 7z1900.msi.

**Additional context**

I have tried the following steps but did not solve the problem.

- Delete the downloads fold and let vcpkg download everything again.
- I tried to update vcpkg but the vcpkg is already the latest version since I installed it recently.
- Use administrator CMD or PowerShell to install.
- Wait for almost a whole day.
- Download 7z1900.msi by myself.
- Change the download image.

**Comment by Cheney-W** [comment]
This should be a 7z related network issue. We couldn't reproduce it in our side, does it still exist in your side?

**Comment by EMILIIIIA** [comment]
> This should be a 7z related network issue. We couldn't reproduce it in our side, does it still exist in your side?

It still exists on my side. After seeing your reply, I tried using VPN but still didn't solve the issues.

**Comment by Cheney-W** [comment]
Is your vcpkg version 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75?

**Comment by Adela0814** [comment]
@EMILIIIIA  Please pull the latest vcpkg and try again, thanks.

**Comment by xrr-233** [comment]
After pulling, the problem still exists.
```
Installing 1/43 gmp:x64-windows...
Building gmp[core]:x64-windows...
-- Using cached gmp-6.2.1.tar.xz.
-- Using cached gmp-arm64-asm-fix-5f32dbc41afc.patch.
-- Cleaning sources at D:/Projects/20230317-COLMAP-3.8-windows-cuda/vcpkg/buildtrees/gmp/src/v6.2.1-0c723d4b6f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Projects/20230317-COLMAP-3.8-windows-cuda/vcpkg/downloads/gmp-6.2.1.tar.xz
-- Applying patch asmflags.patch
-- Applying patch cross-tools.patch
-- Applying patch subdirs.patch
-- Applying patch msvc_symbol.patch
-- Applying patch arm64-coff.patch
-- Applying patch D:/Projects/20230317-COLMAP-3.8-windows-cuda/vcpkg/downloads/gmp-arm64-asm-fix-5f32dbc41afc.patch
-- Using source at D:/Projects/20230317-COLMAP-3.8-windows-cuda/vcpkg/buildtrees/gmp/src/v6.2.1-0c723d4b6f.clean
-- Getting CMake variables for x64-windows
-- Using cached LLVM-15.0.6-win64.7z.exe.
-- Using cached 7z1900.msi.
```

**Comment by dg0yt** [comment]
Please update your vcpkg repo. The current download of 7z should be `7z2107.msi`, updated one year ago (!).

**Comment by dg0yt** [comment]
> -- Using cached LLVM-15.0.6-win64.7z.exe.
> -- Using cached 7z1900.msi.

I started to wonder why we see 7z at all here. Now I see that this is downloading LLVM. This is not really what is meant: It should use clang-cl which comes with modern versions of visual studio.

OTOH I wouldn't be surprised if extracting `LLVM-15.0.6-win64.7z.exe` takes very long.

**Comment by EMILIIIIA** [comment]
> > -- Using cached LLVM-15.0.6-win64.7z.exe.
> > -- Using cached 7z1900.msi.
> 
> I started to wonder why we see 7z at all here. Now I see that this is downloading LLVM. This is not really what is meant: It should use clang-cl which comes with modern versions of visual studio.
> 
> OTOH I wouldn't be surprised if extracting `LLVM-15.0.6-win64.7z.exe` takes very long.

The problem solved! But I encounter a new problem and I will create a new issue latter. I still don't understand how this problem emerged and was solved. Could you please explain it  more clearly?

**Comment by EMILIIIIA** [comment]
Also, for anyone else who has this problem, please follow this guidance published by Microsoft to install clang in Visual Studio.
https://learn.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-170
