### ISSUE TITLE
In vs2019, build project with vcpkg while the include directories are imported from additionaloptions.

### ISSUE THREAD

**Issue by chenkezhe** [microsoft/vcpkg#28920]
Please create a discussion in https://github.com/microsoft/vcpkg/discussions/new instead.
![image](https://user-images.githubusercontent.com/18652286/212270925-2cb244a6-c258-4de6-8101-bf6f55bb4347.png)
which as expected should be imported from here:
![image](https://user-images.githubusercontent.com/18652286/212271378-5aa290f5-3cf5-4941-9061-d302b872ae9e.png)
this problem cause that intellisence can't work for these includes.

**Comment by FrankXie05** [comment]
@chenkezhe For the integration of VS, every time vcpkg runs the command `integrate install`, it will redirect the location of the vcpkg file integrated within the user range. And External should be in the vcpkg option.
![image](https://user-images.githubusercontent.com/65999885/212827370-cd806b67-d968-448b-9c99-518cf01999aa.png)

**Comment by chenkezhe** [comment]
> @chenkezhe For the integration of VS, every time vcpkg runs the command `integrate install`, it will redirect the location of the vcpkg file integrated within the user range. And External should be in the vcpkg option. ![image](https://user-images.githubusercontent.com/65999885/212827370-cd806b67-d968-448b-9c99-518cf01999aa.png)

@FrankXie05 Thanks for your help. But i'm using vcpkg in another way, i.e. with cmake toolchain file of vcpkg, and all dependencies are installed in <project>/build directory, like this:
![image](https://user-images.githubusercontent.com/18652286/215374229-2e732e94-4674-4eff-afa9-2473fa860965.png)
The vcpkg's default installed folder do not contain these dependencies.

**Comment by MonicaLiu0311** [comment]
In this case, the dependencies are put into `\x64-Debug\vcpkg_installed\`, as shown in my sample project below:

![location](https://user-images.githubusercontent.com/110024546/218988517-c6dd09e8-c665-4a88-beb3-6a7007c1f1ef.png)


```
{
	"$schema": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json",
	"name": "test-manifest",
	"version": "1.0.0",
	"description": "Test manifest using the specified version. ",
	"builtin-baseline": "e2a71489b17ae1f5fd29d5fc74c2cdb03fd83f9e",
	"dependencies": [
		"fmt",
		{
			"name": "sqlite3",
			"version>=": "3.37.2#1"
		},
		{
			"name": "zlib",
			"version>=": "1.2.11#10"
		}
	],
	"overrides": [
		{ 
			"name": "zlib", "version": "1.2.11#11" 
		}
	]
}
```

**Comment by MonicaLiu0311** [comment]
If you still have problems, please provide the `CMakeLists.txt` file and `vcpkg.json` file and reopen it.
