### ISSUE TITLE
Is there a proper way to build GDAL with LibKML-driver?

### ISSUE THREAD

**Issue by romplo** [microsoft/vcpkg#28925]
Hello,

I want to build GDAL with LibKML-driver, but unfortunateley so far without success, allthough GDAL and LibKML are well built, I found no way to get the LibKML-driver working in GDAL.

Over the last few years I have repeatedly found ways by writing my own patches and modifications to the make files, but a lot has changed since I last did that, and currently I am stuck.

So my question is: is there already a working and suggested way to achieve this, or, if not, can someone give me a tip on how to work around this problem?

Thanks in advance, best regards,

romplo

**Comment by dg0yt** [comment]
There isn't much missing on the gdal side for adding a libkml feature ... except for getting the libkml link libraries, in proper order for static linkage. I can take a look if it is more feasible now.

**Comment by romplo** [comment]
Thanks for the response.

I'm not sure if this info helps, but maybe: when I did it the last time I manage to get it work by adding options in portfile.cmake (not all were related to LibKML), by adding something like this (I skipped the part for DEBUG-options):

```
list(APPEND NMAKE_OPTIONS
#LibKML
  	  LIBKMLDIR=libkml
	  LIBKML_INCLUDE=-I${LIBKML_INCLUDE}
	  LIBKMLOBJ=libkml\\*.obj
	  LIBKMLDEF=-DLIBKML_ENABLED
#OCI OGR driver
	  OCI_PLUGIN=YES
	  ORACLE_HOME=${ORA_HOME_NATIVE}\\x64
    )

    list(APPEND NMAKE_OPTIONS_REL
#LibKML
    "LIBKML_LIBS=${LIBKML_LIBRARY_REL}/kmlbase.lib ${LIBKML_LIBRARY_REL}/kmlconvenience.lib ${LIBKML_LIBRARY_REL}/kmldom.lib ${LIBKML_LIBRARY_REL}/kmlengine.lib ${LIBKML_LIBRARY_REL}/kmlregionator.lib ${LIBKML_LIBRARY_REL}/kmlxsd.lib ${LIBKML_LIBRARY_REL}/bz2.lib ${LIBKML_LIBRARY_REL}/minizip.lib ${LIBKML_LIBRARY_REL}/libexpat.lib ${LIBKML_LIBRARY_REL}/uriparser.lib ${LIBKML_LIBRARY_REL}/zlib.lib"
#OCI OGR driver
    PLUGINDIR="${CURRENT_PACKAGES_DIR}\\bin\\gdalplugins"
)
```

Unfortunateley this doesn't work anymore, and I'm far away from being familiar with cmake and the VCOKG build-system, so I'd appreciate every help.

**Comment by romplo** [comment]
Thank you very much, works very well.

And I would like to take this opportunity to praise everyone involved: VCPKG is great! Thank you very much for that ...

**Comment by dg0yt** [comment]
Thanks @romplo for validation and feedback.
