### ISSUE TITLE
[poppler] Build error

### ISSUE THREAD

**Issue by kossiLeBeau** [microsoft/vcpkg#28932]
**Host Environment**

- OS: Windows 10
- Compiler: VS 2017
- 
**To Reproduce**

`./vcpkg install poppler[qt5]:x86-windows-static-md --recurse

**Failure logs**
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:31 (message):
  E:/vcpkg/downloads/tools/msys2/9a1ec3f33446b195/mingw32/bin/pkg-config.exe
  --exists poppler-cpp failed with error code: 1

      ENV{PKG_CONFIG_PATH}: "E:/vcpkg/packages/poppler_x86-windows-static-md/lib
/pkgconfig;E:/vcpkg/packages/poppler_x86-windows-static-md/share/pkgconfig;E:/vc
pkg/installed/x86-windows-static-md/lib/pkgconfig;E:/vcpkg/installed/x86-windows
-static-md/share/pkgconfig"
      output: Package qt5 was not found in the pkg-config search path.

  Package 'qt5', required by 'poppler', not found
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:154 (z_vcpkg_fixup_pkgconfig_check_f
iles)
  ports/poppler/portfile.cmake:79 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:147 (include)

    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: 4c5be28bf 2023-01-12 (16 hours ago)

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.
[config-x86-windows-static-md-out.log](https://github.com/microsoft/vcpkg/files/10412947/config-x86-windows-static-md-out.log)
[config-x86-windows-static-md-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10412950/config-x86
[install-x86-windows-static-md-dbg-out.log](https://github.com/microsoft/vcpkg/files/10412952/install-x86-windows-static-md-dbg-out.log)
-windows-static-md-rel-CMakeCache.txt.log)
[install-x86-windows-static-md-rel-out.log](https://github.com/microsoft/vcpkg/files/10412957/install-x86-windows-static-md-rel-out.log)

**Comment by kossiLeBeau** [comment]
Qt5 static md was built before.
Qt5 x86-windows was built before.

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
