### ISSUE TITLE
[New Port Request] NDI SDK

### ISSUE THREAD

**Issue by cnSchwarzer** [microsoft/vcpkg#28959]
I'm here to ask if vcpkg is able to include such port which official SDK is provided through an installer, and end user has some agreement on SDK? 

[NDI SDK License Agreement.pdf](https://github.com/microsoft/vcpkg/files/10419661/NDI.SDK.License.Agreement.pdf)

If it is legal to add such port, I'm willing to create a PR, only if the license stuff let vcpkg to add it.

Library name: NDI SDK

Library description: NDI is an broadcast toolset

Source repository URL: `https://downloads.ndi.tv/SDK/NDI_SDK/NDI 5 SDK.exe`, however this link is emailed to users who clicked on their download page `https://www.ndi.tv/sdk/#download`

Project homepage (if different from the source repository): https://www.ndi.tv

**Comment by cnSchwarzer** [comment]
I think we can do the same thing like `cuda`, provide a cmake function to check the environment variable `NDI_SDK` exists?
Or we can use the implementation here: https://github.com/cnSchwarzer/vcpkg-registry/ports/ndi-sdk

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by cnSchwarzer** [comment]
Oh, the issue is hang because no one is answering the question about license...

**Comment by JonLiu1993** [comment]
> Oh, the issue is hang because no one is answering the question about license...

@cnSchwarzer, Thanks for submitting this issue, because this issue has no response from other users for a long time, so I closed it, do you need me to reopen it?
