### ISSUE TITLE
[ninja]Error: Building package zlib:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by ReyzalX** [Microsoft/vcpkg#2895]
Hello,everyone.
I got some error when I run command`.\vcpkg install zlib`.

> Building package zlib[core]:x86-windows...
-- CURRENT_INSTALLED_DIR=E:/openlib/vcpkg/installed/x86-windows
-- DOWNLOADS=E:/openlib/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=E:/openlib/vcpkg/packages/zlib_x86-windows
-- CURRENT_BUILDTREES_DIR=E:/openlib/vcpkg/buildtrees/zlib
-- CURRENT_PORT_DIR=E:/openlib/vcpkg/ports/zlib/.
-- Using cached E:/openlib/vcpkg/downloads/zlib1211.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch E:/openlib/vcpkg/ports/zlib/cmake_dont_build_more_than_needed.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch E:/openlib/vcpkg/ports/zlib/cmake_dont_build_more_than_needed.patch done
-- Configuring x86-windows
-- Configuring x86-windows done
-- Build x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:129 (message):
    Command failed: E:/openlib/vcpkg/downloads/cmake-3.10.2-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: E:/openlib/vcpkg/buildtrees/zlib/x86-windows-dbg
    See logs for more information:
      E:\openlib\vcpkg\buildtrees\zlib\install-x86-windows-dbg-out.log
Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/zlib/portfile.cmake:26 (vcpkg_install_cmake)
  scripts/ports.cmake:72 (include)
Error: Building package zlib:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x86-windows
  Vcpkg version: 0.0.105-unknownhash

My machine is Windows 10,VS2015 With Update 3, also installed VS2010.

I try to solve this problem.When I edit `\ports\zlib\portfile.cmake` file,delete `PREFER_NINJA` in this file, the error will disappear.

I found something wrong in build.ninja file.in this file we can find The following code.
> build CMakeFiles\zlib.dir\win32\zlib1.res: RC_COMPILER__zlib E$:\openlib\vcpkg\buildtrees\zlib\src\zlib-1.2.11\win32\zlib1.rc || cmake_object_order_depends_target_zlib
  DEFINES = -DNO_FSEEKO -DZLIB_DLL -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE
  DEP_FILE = CMakeFiles\zlib.dir\win32\zlib1.res.d
  FLAGS = /DWIN32 /D_DEBUG
  INCLUDES = -IE:\openlib\vcpkg\buildtrees\zlib\src\zlib-1.2.11 -IE:\openlib\vcpkg\buildtrees\zlib\x86-windows-dbg
  OBJECT_DIR = CMakeFiles\zlib.dir
  OBJECT_FILE_DIR = CMakeFiles\zlib.dir\win32
  TARGET_COMPILE_PDB = CMakeFiles\zlib.dir\
  TARGET_PDB = zlibd.pdb

in `zlib1.rc` file.it include <winver.h>,which i can find in `C:\Program Files (x86)\Windows Kits\8.1\Include\um` and `C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um`.
but ninja.build not include `C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um` or  `C:\Program Files (x86)\Windows Kits\8.1\Include\um`.so it will show build error:
> fatal error RC1015: cannot open include file 'winver.h'.

If I can add Includes to build.ninja, this error may fixed.
I do not know how to use ninja.
I hope someone can help me solve the problem.
Thanks.

**Comment by cmpute** [comment]
It could help a lot if you upload `E:\openlib\vcpkg\buildtrees\zlib\install-x86-windows-dbg-out.log`~

**Comment by ReyzalX** [comment]
[install-x86-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/1763419/install-x86-windows-dbg-out.log)
It seems that I got some error when build zlib1.rc.
if I delete `PREFER_NINJA` from `\ports\zlib\portfile.cmake`,It will success.

**Comment by crackedmind** [comment]
Did you install English language pack for Visual Studio?
Same problem [here](https://github.com/Microsoft/vcpkg/issues/1939#issuecomment-354644869) solved by installing english language pack

**Comment by ReyzalX** [comment]
Thank you all!
When I switch language to English for my Visual Studio,It works well.

**Comment by AnimeshP6** [comment]
Mine is in English version still its not working.
