### ISSUE TITLE
Should we build gn tool from source to patch the bug for following issues?

### ISSUE THREAD

**Issue by cnSchwarzer** [microsoft/vcpkg#28974]
#28358 #24719

Currently gn has bugs that will fail everything if buildtree location and manifest project is in different drive (on Windows)

It will generate a path like ../../../../E:/Path and is invalid when ninja use it.

The gn repository seems inactive, ignoring my PR and issue, so should we provide a port to build gn tool from scratch instead of prebuilt one to solve the issue?

**Comment by FrankXie05** [comment]
@cnSchwarzer Thanks for posting this issue. 
    Sorry, vcpkg doesn't build a tool. We only provide 3rd party tools needed for ports.

**Comment by FrankXie05** [comment]
We can only wait for `gn` to fix this bug. :(

**Comment by cnSchwarzer** [comment]
> We can only wait for `gn` to fix this bug. :(

Fine.. Although there's a workaround to patch ninja file.

**Comment by FrankXie05** [comment]
> > We can only wait for  to fix this bug. :(`gn`
> 
> Fine.. Although there's a workaround to patch ninja file.

But it's just a workaround and can't fix it.

**Comment by cnSchwarzer** [comment]
> But it's just a workaround and can't fix it.

Not a problem, there're many workarounds in many ports, and gn based projects are all suffer from this. Maybe I can provide such workaround and wait for gn to fix (gn repo seems inactive for long...)
