### ISSUE TITLE
How can I build gdal with ecw support option

### ISSUE THREAD

**Issue by drspam1991** [microsoft/vcpkg#28983]
Hi,
How can I enable --with-ecw option in gdal build to support ecw image files?

**Comment by dg0yt** [comment]
You can modify the port. This driver needs an external SDK, so it will need extra work. Licensing is not as permissive as desirable, making it more difficult to maintain it as an official port feature. 
https://gdal.org/drivers/raster/ecw.html

Alternatively, you can try to inject related CMake options from a custom triplet file via `VCPKG_CMAKE_CONFIGURE_OPTIONS`.

**Comment by MonicaLiu0311** [comment]
>You can modify the port. This driver needs an external SDK, so it will need extra work. Licensing is not as permissive as desirable, making it more difficult to maintain it as an official port feature.
https://gdal.org/drivers/raster/ecw.html
Alternatively, you can try to inject related CMake options from a custom triplet file via VCPKG_CMAKE_CONFIGURE_OPTIONS.

Hello, is this suggestion effective for you?

**Comment by Cheney-W** [comment]
Much thanks for dg0yt's comment.

**Comment by drspam1991** [comment]
> You can modify the port. This driver needs an external SDK, so it will need extra work. Licensing is not as permissive as desirable, making it more difficult to maintain it as an official port feature. https://gdal.org/drivers/raster/ecw.html
> 
> Alternatively, you can try to inject related CMake options from a custom triplet file via `VCPKG_CMAKE_CONFIGURE_OPTIONS`.

Thanks for your answer. But I don't know what I should change in the port. Can you tell the necessary changes?
