### ISSUE TITLE
[cairo] Static builds not linking in all functions?

### ISSUE THREAD

**Issue by rspeir** [microsoft/vcpkg#28994]
**Describe the bug**
When compiling code using static cairo libraries built from vcpkg, I get a linker error about unresolved external symbols that were apparently not linked in with the cairo.lib:
`LNK2019 unresolved external symbol __imp_GradientFill referenced in function _cairo_win32_printing_surface_paint_linear_pattern`

**Environment**
- OS: Windows 10 Pro
- Compiler: MSVC 2022 64 bit

**To Reproduce**
1. ./vcpkg install cairo:x64-windows-static
2. ./vcpkg integrate install
3. Create new empty C/C++ console project, change project properties -> vgpkg -> "Use Static Libraries" to Yes
4. Create main.c file with the following code:
```
#include "cairo/cairo.h"

int main()
{
	cairo_t* cr;
	cairo_surface_t* surface;

	surface = cairo_image_surface_create(CAIRO_FORMAT_ARGB32, 120, 120);
	cr = cairo_create(surface);

	return 0;
} 
```
5. Compiling yields the following error from the linker:
`LNK2019	unresolved external symbol __imp_GradientFill referenced in function _cairo_win32_printing_surface_paint_linear_pattern`

**Additional Information**
This code fails to compile in both debug and release mode. 
If I install the shared libraries and change project settings to use them, my code will compile, but I would rather use static libraries.

**Comment by Neumann-A** [comment]
You need to manually link `Msimg32.lib` as it seems (due to MSBuild.)

**Comment by Cheney-W** [comment]
I could reproduce this issue in my side and could workaround it by manually link Msimg32.lib in Visual Studio.
@Neumann-A  Is there anything vcpkg can do here?

**Comment by Neumann-A** [comment]
@Cheney-W add a `#pragma commet(lib,....)` with an `#ifdef _MSC_VER` in the header pulling in the windows deps? Otherwise vcpkg can do nothing here since the MSBuild integration is ..... I don't think i need to say more about it
