### ISSUE TITLE
[Docs] Json schema file no longer exists.

### ISSUE THREAD

**Issue by Elite-stay** [microsoft/vcpkg#28997]
Please update or remove the outdated information about schema json in [Manifest Mode Page](https://vcpkg.io/en/docs/users/manifests.html#manifest-syntax-reference).

**Comment by FrankXie05** [comment]
@Elite-stay Thanks for posting this issue. `vcpkg.io` is updated once a month. We are ready to update, but some technical problems are still being resolved. We will update as soon as the problem is resolved. 
You can temporarily use https://github.com/microsoft/vcpkg as the standard. :)

**Comment by jimwang118** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
