### ISSUE TITLE
update opencv to 3.4.1

### ISSUE THREAD

**Issue by jasjuang** [Microsoft/vcpkg#2900]
@cenit @patrikhuber @ras0219-msft Can one of you do a "controlled" upgrade for OpenCV to 3.4.1? It contains bug fixes so `vcpkg install opencv[sfm]` will actually compile without me having to manually apply one of the PR that was merged after the release of OpenCV 3.4.0 in the source. Thanks!

**Comment by patrikhuber** [comment]
Hi @jasjuang!
I'm relatively busy with a deadline this week but I'm happy to help and try something if it's relatively quick/straightforward. I don't fully understand what you'd like me to do though. What do you mean with a "controlled upgrade", and what patches do you mean?

Thanks for pushing on updating to 3.4.1! :-)

**Comment by patrikhuber** [comment]
Btw these seem to be quite unfortunate issue with 3.4.1 if confirmed...: https://github.com/opencv/opencv/issues/10950, https://github.com/opencv/opencv/issues/10943

**Comment by cenit** [comment]
@jasjuang working on that right now. As expected, they touched almost all of the source files, so all of the patchfiles have to be fixed otherwise they fail. Almost done, trying some building. I will open a PR in a few minutes, but let's request the merge only after some tests.

**Comment by cenit** [comment]
#2906 contains the update to 3.4.1, but it is incomplete and for now it does NOT fully work (the OpenCV_dnn_module is broken, it has received many updates from 3.4.0 to 3.4.1)

**Comment by cenit** [comment]
the PR has been updated with some fixes. Now the `dnn` module works.
In the meantime I am also opening other PR for related problems (gflags, etc).

**Comment by cenit** [comment]
@jasjuang could you please test my PR? Also, how to you use the `sfm` module on Windows? Because I am starting to use OpenCV more and more also on Windows and I am not able to solve in a clean way the linking to downstream projects of some external dependencies. In the PR I tried to explain the problem.

**Comment by jasjuang** [comment]
already updated to 3.4.1
