### ISSUE TITLE
[libiconv] Build error

### ISSUE THREAD

**Issue by jakob-ropers-snkeos** [microsoft/vcpkg#29012]
**Host Environment**

- OS: Windows 10
- Compiler: VS19

**To Reproduce**

`vcpkg install opencv[eigen,ffmpeg,webp,contrib,nonFree,cuda] --triplet x64-windows`

**Failure logs**
*Console Output*
Computing installation plan...
The following packages will be built and installed:
  * libarchive[bzip2,core,libxml2,lz4,lzma,openssl,zstd]:x64-windows -> 3.6.1#1
  * libiconv[core]:x64-windows -> 1.17
  * libxml2[core]:x64-windows -> 2.10.3
    opencv[contrib,core,cuda,default-features,eigen,ffmpeg,nonfree,webp]:x64-windows -> 4.6.0
  * opencv4[contrib,core,cuda,default-features,dnn,eigen,ffmpeg,jpeg,nonfree,png,quirc,tiff,webp]:x64-windows -> 4.6.0#10
  * openssl[core]:x64-windows -> 3.0.7#1
  * protobuf[core]:x64-windows -> 3.21.8
  * quirc[core]:x64-windows -> 1.1#3
  * tesseract[core]:x64-windows -> 5.2.0#3
  * vcpkg-get-python-packages[core]:x64-windows -> 2022-06-30
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\jakob.ropers\AppData\Local\vcpkg\archives in 2.224 ms. Use --debug to see more details.
Installing 1/10 libiconv:x64-windows...
Building libiconv[core]:x64-windows...
-- Using cached libiconv-1.17.tar.gz.
-- Cleaning sources at C:/CODING/MeshroomDepthMOD/vcpkg/buildtrees/libiconv/src/1.17-e2a53830aa.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/CODING/MeshroomDepthMOD/vcpkg/downloads/libiconv-1.17.tar.gz
-- Applying patch 0002-Config-for-MSVC.patch
-- Applying patch 0003-Add-export.patch
-- Applying patch 0004-ModuleFileName.patch
-- Using source at C:/CODING/MeshroomDepthMOD/vcpkg/buildtrees/libiconv/src/1.17-e2a53830aa.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows
-- Using cached msys-gzip-1.11-1-x86_64.pkg.tar.zst.
-- Using cached msys-bash-5.1.008-1-x86_64.pkg.tar.zst.
-- Using cached msys-autoconf-2.71-3-any.pkg.tar.zst.
-- Using cached msys-diffutils-3.8-2-x86_64.pkg.tar.zst.
-- Using cached msys-binutils-2.37-5-x86_64.pkg.tar.zst.
-- Using cached msys-libtool-2.4.6-9-x86_64.pkg.tar.xz.
-- Using cached msys-file-5.41-2-x86_64.pkg.tar.zst.
-- Using cached msys-zlib-1.2.11-1-x86_64.pkg.tar.xz.
-- Using cached msys-libbz2-1.0.8-3-x86_64.pkg.tar.zst.
-- Using cached msys-coreutils-8.32-2-x86_64.pkg.tar.zst.
-- Using cached msys-grep-3.0-2-x86_64.pkg.tar.xz.
-- Using cached msys-sed-4.8-2-x86_64.pkg.tar.zst.
-- Using cached msys-libpcre-8.45-1-x86_64.pkg.tar.zst.
-- Using cached msys-m4-1.4.19-2-x86_64.pkg.tar.zst.
-- Using cached msys-automake-wrapper-11-4-any.pkg.tar.zst.
-- Using cached msys-gawk-5.1.0-2-x86_64.pkg.tar.zst.
-- Using cached msys-mpfr-4.1.0-1-x86_64.pkg.tar.zst.
-- Using cached msys-gmp-6.2.1-1-x86_64.pkg.tar.zst.
-- Using cached msys-libreadline-8.1.001-1-x86_64.pkg.tar.zst.
-- Using cached msys-ncurses-6.2-2-x86_64.pkg.tar.zst.
-- Using cached msys-automake1.16-1.16.3-3-any.pkg.tar.zst.
-- Using cached msys-perl-5.32.1-2-x86_64.pkg.tar.zst.
-- Using cached msys-libcrypt-2.1-3-x86_64.pkg.tar.zst.
-- Using cached msys-pkg-config-0.29.2-4-x86_64.pkg.tar.zst.
-- Using cached msys-make-4.3-3-x86_64.pkg.tar.zst.
-- Using cached msys-findutils-4.8.0-1-x86_64.pkg.tar.zst.
-- Using cached msys-libintl-0.21-1-x86_64.pkg.tar.zst.
-- Using cached msys-libiconv-1.16-2-x86_64.pkg.tar.zst.
-- Using cached msys-gcc-libs-11.2.0-3-x86_64.pkg.tar.zst.
-- Using cached msys-msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst.
-- Using cached msys-which-2.21-4-x86_64.pkg.tar.zst.
-- Using msys root at C:/CODING/MeshroomDepthMOD/vcpkg/downloads/tools/msys2/583ad6e4115a307a
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at C:/CODING/MeshroomDepthMOD/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Warning at scripts/cmake/vcpkg_execute_build_process.cmake:62 (message):
  Please ensure your system has sufficient memory.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:149 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:2 (vcpkg_build_make)
  ports/libiconv/portfile.cmake:39 (vcpkg_install_make)
  scripts/ports.cmake:147 (include)

-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: C:/CODING/MeshroomDepthMOD/vcpkg/downloads/tools/msys2/583ad6e4115a307a/usr/bin/make.exe -j 17 --trace -f Makefile all
    Working Directory: C:/CODING/MeshroomDepthMOD/vcpkg/buildtrees/libiconv/x64-windows-dbg/
    See logs for more information:
      C:\CODING\MeshroomDepthMOD\vcpkg\buildtrees\libiconv\build-x64-windows-dbg-out.log
      C:\CODING\MeshroomDepthMOD\vcpkg\buildtrees\libiconv\build-x64-windows-dbg-err.log
      C:\CODING\MeshroomDepthMOD\vcpkg\buildtrees\libiconv\build-x64-windows-dbg-out-1.log
      C:\CODING\MeshroomDepthMOD\vcpkg\buildtrees\libiconv\build-x64-windows-dbg-err-1.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:149 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:2 (vcpkg_build_make)
  ports/libiconv/portfile.cmake:39 (vcpkg_install_make)
  scripts/ports.cmake:147 (include)

*build-x64-windows-dbg-out.log*
Makefile:41: target 'lib/localcharset.h' does not exist
builddir="`pwd`"; cd libcharset && /usr/bin/make all && /usr/bin/make install-lib libdir="$builddir/lib" includedir="$builddir/lib"
make[1]: Entering directory '/c/CODING/MeshroomDepthMOD/vcpkg/buildtrees/libiconv/x64-windows-dbg/libcharset'
Makefile:34: update target 'all' due to: force
cd lib && /usr/bin/make all
make[2]: Entering directory '/c/CODING/MeshroomDepthMOD/vcpkg/buildtrees/libiconv/x64-windows-dbg/libcharset/lib'
Makefile:58: update target 'localcharset.lo' due to: ../.././../src/1.17-e2a53830aa.clean/libcharset/lib/localcharset.c
/bin/sh ../libtool --mode=compile compile cl.exe -I. -I../.././../src/1.17-e2a53830aa.clean/libcharset/lib -I.. -I../.././../src/1.17-e2a53830aa.clean/libcharset/lib/.. -I../include -nologo -W3 -utf-8 -MP -MDd -Z7 -Ob0 -Od -Xcompiler -RTC1  -DWIN32 -D_WINDOWS -D_DEBUG -DBUILDING_LIBCHARSET -DHAVE_CONFIG_H -c ../.././../src/1.17-e2a53830aa.clean/libcharset/lib/localcharset.c
Makefile:61: update target 'relocatable-stub.lo' due to: ../.././../src/1.17-e2a53830aa.clean/libcharset/lib/relocatable-stub.c
/bin/sh ../libtool --mode=compile compile cl.exe -I. -I../.././../src/1.17-e2a53830aa.clean/libcharset/lib -I.. -I../.././../src/1.17-e2a53830aa.clean/libcharset/lib/.. -I../include -nologo -W3 -utf-8 -MP -MDd -Z7 -Ob0 -Od -Xcompiler -RTC1  -DWIN32 -D_WINDOWS -D_DEBUG -DBUILDING_LIBCHARSET -DHAVE_CONFIG_H -c ../.././../src/1.17-e2a53830aa.clean/libcharset/lib/relocatable-stub.c
libtool: compile:  compile cl.exe -I. -I../.././../src/1.17-e2a53830aa.clean/libcharset/lib -I.. -I../.././../src/1.17-e2a53830aa.clean/libcharset/lib/.. -I../include -nologo -W3 -utf-8 -MP -MDd -Z7 -Ob0 -RTC1 -Od -DWIN32 -D_WINDOWS -D_DEBUG -DBUILDING_LIBCHARSET -DHAVE_CONFIG_H -c ../.././../src/1.17-e2a53830aa.clean/libcharset/lib/localcharset.c  -DDLL_EXPORT -DPIC -o .libs/localcharset.obj
libtool: compile:  compile cl.exe -I. -I../.././../src/1.17-e2a53830aa.clean/libcharset/lib -I.. -I../.././../src/1.17-e2a53830aa.clean/libcharset/lib/.. -I../include -nologo -W3 -utf-8 -MP -MDd -Z7 -Ob0 -RTC1 -Od -DWIN32 -D_WINDOWS -D_DEBUG -DBUILDING_LIBCHARSET -DHAVE_CONFIG_H -c ../.././../src/1.17-e2a53830aa.clean/libcharset/lib/relocatable-stub.c  -DDLL_EXPORT -DPIC -o .libs/relocatable-stub.obj
relocatable-stub.c
localcharset.c
../.././../src/1.17-e2a53830aa.clean/libcharset/lib/localcharset.c(929): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
../.././../src/1.17-e2a53830aa.clean/libcharset/lib/localcharset.c(939): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
../.././../src/1.17-e2a53830aa.clean/libcharset/lib/localcharset.c(947): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
Makefile:55: update target 'libcharset.la' due to: localcharset.lo relocatable-stub.lo
/bin/sh ../libtool --mode=link compile cl.exe -Xlinker -Xlinker -Xlinker -LC:/CODING/MeshroomDepthMOD/vcpkg/installed/x64-windows/debug/lib -Xlinker -Xlinker -Xlinker -machine:x64 -Xlinker -Xlinker -Xlinker -nologo -Xlinker -Xlinker -Xlinker -debug -Xlinker -Xlinker -Xlinker -INCREMENTAL -nologo -W3 -utf-8 -MP -MDd -Z7 -Ob0 -Od -Xcompiler -RTC1  -o libcharset.la -rpath /C/CODING/MeshroomDepthMOD/vcpkg/installed/x64-windows/debug/lib -version-info 1:0:0 -no-undefined localcharset.lo relocatable-stub.lo
libtool: link: dumpbin.exe -symbols -headers  .libs/localcharset.obj .libs/relocatable-stub.obj   | gawk '     {last_section=section; section=$ 3};     /^COFF SYMBOL TABLE/{for(i in hide) delete hide[i]};     /Section length .*#relocs.*(pick any)/{hide[last_section]=1};     /^ *Symbol name *: /{split($ 0,sn,":"); si=substr(sn[2],2)};     /^ *Type *: code/{print "T",si,substr(si,length(prfx))};     /^ *Type *: data/{print "I",si,substr(si,length(prfx))};     $ 0!~/External *\|/{next};     / 0+ UNDEF /{next}; / UNDEF \([^|]\)*()/{next};     {if(hide[section]) next};     {f="D"}; $ 0~/\(\).*\|/{f="T"};     {split($ 0,a,/\||\r/); split(a[2],s)};     s[1]~/^[@?]/{print f,s[1],s[1]; next};     s[1]~prfx {split(s[1],t,"@"); print f,t[1],substr(t[1],length(prfx))}     ' prfx=^ | /usr/bin/sed '/ __gnu_lto/d' | /usr/bin/sed -e '/^[BCDGRS][ ]/s/.*[ ]\([^ ]*\)/\1,DATA/' | /usr/bin/sed -e '/^[AITW][ ]/s/.*[ ]//' | sort | uniq > .libs/charset.exp
libtool: link: if test DEF = "`/usr/bin/sed -n -e 's/^[	 ]*//' -e '/^\(;.*\)*$/d' -e 's/^\(EXPORTS\|LIBRARY\)\([	 ].*\)*$/DEF/p' -e q .libs/charset.exp`" ; then cp ".libs/charset.exp" ".libs/charset-1.dll.def"; echo "WARNING! VENV_PATH is not defined!!!
libtool: link: .libs\\charset-1.dll.def" > ".libs/charset-1.dll.exp"; else /usr/bin/sed -e 's/^/-link -EXPORT:/' < .libs/charset.exp > .libs/charset-1.dll.exp; fi
libtool: link:  compile cl.exe -o WARNING! VENV_PATH is not defined!!!
libtool: link: .libs\\charset-1.dll  .libs/localcharset.obj .libs/relocatable-stub.obj   -Xlinker -LC:/CODING/MeshroomDepthMOD/vcpkg/installed/x64-windows/debug/lib -Xlinker -machine:x64 -Xlinker -nologo -Xlinker -debug -Xlinker -INCREMENTAL -Ob0 -Od -RTC1    "@WARNING! VENV_PATH is not defined!!!
libtool: link: .libs\\charset-1.dll.exp" -Wl,-DLL,-IMPLIB:"WARNING! VENV_PATH is not defined!!!
libtool: link: .libs\\charset.lib"
LINK : fatal error LNK1104: cannot open file 'VENV_PATH.obj'
make[2]: Leaving directory '/c/CODING/MeshroomDepthMOD/vcpkg/buildtrees/libiconv/x64-windows-dbg/libcharset/lib'
make[1]: Leaving directory '/c/CODING/MeshroomDepthMOD/vcpkg/buildtrees/libiconv/x64-windows-dbg/libcharset'

*build-x64-windows-dbg-err.log*
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30147 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9024 : unrecognized source file type 'VENV_PATH', object file assumed
cl : Command line warning D9024 : unrecognized source file type 'is', object file assumed
cl : Command line warning D9024 : unrecognized source file type 'not', object file assumed
cl : Command line warning D9024 : unrecognized source file type 'defined!!!', object file assumed
../libtool: line 10858: .libs\charset-1.dll: No such file or directory
make[2]: *** [Makefile:55: libcharset.la] Error 127
make[1]: *** [Makefile:34: all] Error 2
make: *** [Makefile:41: lib/localcharset.h] Error 2

*build-x64-windows-dbg-out-1.log*
Makefile:41: target 'lib/localcharset.h' does not exist
builddir="`pwd`"; cd libcharset && /usr/bin/make all && /usr/bin/make install-lib libdir="$builddir/lib" includedir="$builddir/lib"
make[1]: Entering directory '/c/CODING/MeshroomDepthMOD/vcpkg/buildtrees/libiconv/x64-windows-dbg/libcharset'
Makefile:34: update target 'all' due to: force
cd lib && /usr/bin/make all
make[2]: Entering directory '/c/CODING/MeshroomDepthMOD/vcpkg/buildtrees/libiconv/x64-windows-dbg/libcharset/lib'
Makefile:55: update target 'libcharset.la' due to: localcharset.lo relocatable-stub.lo
/bin/sh ../libtool --mode=link compile cl.exe -Xlinker -Xlinker -Xlinker -LC:/CODING/MeshroomDepthMOD/vcpkg/installed/x64-windows/debug/lib -Xlinker -Xlinker -Xlinker -machine:x64 -Xlinker -Xlinker -Xlinker -nologo -Xlinker -Xlinker -Xlinker -debug -Xlinker -Xlinker -Xlinker -INCREMENTAL -nologo -W3 -utf-8 -MP -MDd -Z7 -Ob0 -Od -Xcompiler -RTC1  -o libcharset.la -rpath /C/CODING/MeshroomDepthMOD/vcpkg/installed/x64-windows/debug/lib -version-info 1:0:0 -no-undefined localcharset.lo relocatable-stub.lo
libtool: link: rm -fr  .libs/charset.exp
libtool: link: dumpbin.exe -symbols -headers  .libs/localcharset.obj .libs/relocatable-stub.obj   | gawk '     {last_section=section; section=$ 3};     /^COFF SYMBOL TABLE/{for(i in hide) delete hide[i]};     /Section length .*#relocs.*(pick any)/{hide[last_section]=1};     /^ *Symbol name *: /{split($ 0,sn,":"); si=substr(sn[2],2)};     /^ *Type *: code/{print "T",si,substr(si,length(prfx))};     /^ *Type *: data/{print "I",si,substr(si,length(prfx))};     $ 0!~/External *\|/{next};     / 0+ UNDEF /{next}; / UNDEF \([^|]\)*()/{next};     {if(hide[section]) next};     {f="D"}; $ 0~/\(\).*\|/{f="T"};     {split($ 0,a,/\||\r/); split(a[2],s)};     s[1]~/^[@?]/{print f,s[1],s[1]; next};     s[1]~prfx {split(s[1],t,"@"); print f,t[1],substr(t[1],length(prfx))}     ' prfx=^ | /usr/bin/sed '/ __gnu_lto/d' | /usr/bin/sed -e '/^[BCDGRS][ ]/s/.*[ ]\([^ ]*\)/\1,DATA/' | /usr/bin/sed -e '/^[AITW][ ]/s/.*[ ]//' | sort | uniq > .libs/charset.exp
libtool: link: if test DEF = "`/usr/bin/sed -n -e 's/^[	 ]*//' -e '/^\(;.*\)*$/d' -e 's/^\(EXPORTS\|LIBRARY\)\([	 ].*\)*$/DEF/p' -e q .libs/charset.exp`" ; then cp ".libs/charset.exp" ".libs/charset-1.dll.def"; echo "WARNING! VENV_PATH is not defined!!!
libtool: link: .libs\\charset-1.dll.def" > ".libs/charset-1.dll.exp"; else /usr/bin/sed -e 's/^/-link -EXPORT:/' < .libs/charset.exp > .libs/charset-1.dll.exp; fi
libtool: link:  compile cl.exe -o WARNING! VENV_PATH is not defined!!!
libtool: link: .libs\\charset-1.dll  .libs/localcharset.obj .libs/relocatable-stub.obj   -Xlinker -LC:/CODING/MeshroomDepthMOD/vcpkg/installed/x64-windows/debug/lib -Xlinker -machine:x64 -Xlinker -nologo -Xlinker -debug -Xlinker -INCREMENTAL -Ob0 -Od -RTC1    "@WARNING! VENV_PATH is not defined!!!
libtool: link: .libs\\charset-1.dll.exp" -Wl,-DLL,-IMPLIB:"WARNING! VENV_PATH is not defined!!!
libtool: link: .libs\\charset.lib"
LINK : fatal error LNK1104: cannot open file 'VENV_PATH.obj'
make[2]: Leaving directory '/c/CODING/MeshroomDepthMOD/vcpkg/buildtrees/libiconv/x64-windows-dbg/libcharset/lib'
make[1]: Leaving directory '/c/CODING/MeshroomDepthMOD/vcpkg/buildtrees/libiconv/x64-windows-dbg/libcharset'

*build-x64-windows-dbg-err-1.log*
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30147 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9024 : unrecognized source file type 'VENV_PATH', object file assumed
cl : Command line warning D9024 : unrecognized source file type 'is', object file assumed
cl : Command line warning D9024 : unrecognized source file type 'not', object file assumed
cl : Command line warning D9024 : unrecognized source file type 'defined!!!', object file assumed
../libtool: line 10858: .libs\charset-1.dll: No such file or directory
make[2]: *** [Makefile:55: libcharset.la] Error 127
make[1]: *** [Makefile:34: all] Error 2
make: *** [Makefile:41: lib/localcharset.h] Error 2

**Additional context**
As instructed, I tried "git pull" followed by "vcpkg update". This did not help.

**Comment by jakob-ropers-snkeos** [comment]
**vcpkg-tool version:** 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
**vcpkg-scripts version:** 71f51b100 2022-12-17 (4 weeks ago)

**Comment by Cheney-W** [comment]
Thanks for reporting this issue, but I can't reproduce it in my side with the latest vcpkg.
I see that the errors in your log are related to libtool. Because this tool has been [updated](https://github.com/microsoft/vcpkg/pull/28919) recently, could you please remove the `vcpkg/downloads` folder and run following command again? Thank you!
`.\vcpkg.exe install libiconv:x64-windows --bianrysource=clear`

**Comment by jakob-ropers-snkeos** [comment]
> 

Thank you for the quick reply Cheney. I am still getting an error after trying this...

**Comment by ooshlablu** [comment]
I am also running into an error building `libiconv`, but in my case it seems like it's trying to pull down deps that don't exist anymore, specifically an old version of `libtool`:
```
error: Failed to download from mirror set
error: https://repo.msys2.org/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: failed: status code 404
error: https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: failed: status code 404
error: https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: failed: status code 404
error: https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: failed: status code 404
error: https://mirrors.ustc.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: failed: status code 404
error: https://mirror.bit.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: WinHttpSendRequest failed with exit code 12007
error: https://mirror.bit.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: WinHttpSendRequest failed with exit code 12007
error: https://mirror.bit.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: WinHttpSendRequest failed with exit code 12007
error: https://mirror.bit.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: WinHttpSendRequest failed with exit code 12007
error: https://mirror.selfnet.de/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: failed: status code 404
error: https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: failed: status code 404
```
Version `2.4.6-9` does not exist on those mirrors...

**Comment by dg0yt** [comment]
@ooshlablu Update your vcpkg repo (git pull, bootstrap-vcpkg).

**Comment by ooshlablu** [comment]
I had my version pinned to the latest release (2023.01.09) which is why I wasn't getting the fix. The issue was identified and resolved a week after that release, so naturally changing to `master` fixed it for now. We will be able to pin to future releases.

Thanx!

**Comment by JackBoosY** [comment]
@Cheney-W can be closed now.
