### ISSUE TITLE
[gtk3] GTK3 causes CI to hang

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/vcpkg#29018]
Example: https://dev.azure.com/vcpkg/public/_build/results?buildId=83718&view=logs&j=7922e5c4-0103-5f8f-ad17-45ce9bb98e80

**Comment by dg0yt** [comment]
Single incident?
It would be nice is if failure logs would be uploaded even when the build task times out. We don't know precisely which portfile step actually caused the hang.

**Comment by BillyONeal** [comment]
>Single incident?

No, I've been seeing it fairly consistently.

I tended to assume such cases were the usual Azure Spot "we are taking your machine now thanks" behavior but it seems almost every time I see a build messed up like this it is gtk3 of some form.

I will update this issue if/when I see more occurrences.

**Comment by BillyONeal** [comment]
Again: https://dev.azure.com/vcpkg/public/_build/results?buildId=83848&view=logs&j=c2a18d2e-37ac-57b0-b2a5-926ff10fbe32

**Comment by BillyONeal** [comment]
Again: https://dev.azure.com/vcpkg/public/_build/results?buildId=83910&view=logs&j=c2a18d2e-37ac-57b0-b2a5-926ff10fbe32

**Comment by BillyONeal** [comment]
Again: https://dev.azure.com/vcpkg/public/_build/results?buildId=84104

**Comment by BillyONeal** [comment]
Again: https://dev.azure.com/vcpkg/public/_build/results?buildId=85076&view=results

**Comment by BillyONeal** [comment]
Again: https://dev.azure.com/vcpkg/public/_build/results?buildId=85882&view=logs&j=7b75bd19-17d3-53d4-00fd-23f1a49a8ba4

I think we need to strongly consider just skipping it given that we aren't seeing any rhyme/reason/pattern

**Comment by BillyONeal** [comment]
I managed to repro. glib-compile-resources.exe ran gdk-pixbuf-pixdata.exe, which hangs.

![image](https://user-images.githubusercontent.com/1544943/221392296-2e506fe4-76b7-4ab2-939f-80a7643b6d0e.png)

Turned on procmon to filter for this and rerunning to try to repro again.

**Comment by BillyONeal** [comment]
Unfortunately procmon doesn't work because the system runs out of memory :(

**Comment by BillyONeal** [comment]
Interestingly it ran the rest of the weekend in a loop without hanging. Perhaps this suggests some kind of escape of state between port builds?

**Comment by quyykk** [comment]
Another one: https://dev.azure.com/vcpkg/public/_build/results?buildId=86491&view=logs&j=878666d5-db33-5b27-9e7d-b0c7ee352005

**Comment by dg0yt** [comment]
Probably still there: https://dev.azure.com/vcpkg/public/_build/results?buildId=88994&view=logs&j=7922e5c4-0103-5f8f-ad17-45ce9bb98e80&t=66eef212-08d6-5e6c-a560-7d01149d0188

Repeating my suggestion: Let's pass timeouts into the build step, so that CI can return failure logs on error.
