### ISSUE TITLE
Error: Building package realsense2:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by adgbu** [Microsoft/vcpkg#2901]
Command:
$ vcpkg install realsense2 --triplet x64-windows

...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:87 (message):

File does not have expected hash:

File path: [ C:/local/vcpkg/downloads/IntelRealSense-librealsense-v2.10.0.tar.gz ]
Expected hash: [ b00cd4617d59197f7baa40d5a4833027c2b0c45e3e67047dce38e9415905ecf78c1ee9fe499c8e3292b54b8de8e96064001d0f154fdb10b2c64c19a8162db6d1 ]
Actual hash: [ af5f77eb69620e8485bbe0b7c82c405ed518c50b3319e4c174c002180c4842d5dbfaab354051ed4b287effac58ae93dd1160ebc27d35def58e685874a89c02ee ]

The file may have been corrupted in transit.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:129 (test_hash)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/realsense2/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:72 (include)

Error: Building package realsense2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: realsense2:x64-windows
  Vcpkg version: 0.0.105-2018-02-26-25b8f25dadcb2af28ae5be2e6d31884ca67f1b26

**Comment by ReyzalX** [comment]
It may be something wrong with your download file.
check if `C:/local/vcpkg/downloads/IntelRealSense-librealsense-v2.10.0.tar.gz` file is correct!

**Comment by adgbu** [comment]
I opened the file *IntelRealSense-librealsense-v2.10.0.tar.gz* in 7-zip and it appears to be ok. I also deleted the file, so it is downloaded again fresh, but it does not help. 

Obviously the *tar.gz* file or the hash is somehow wrong or broken because the hashes do not match.

**Comment by ReyzalX** [comment]
yes,file hash does not match the configuration file.
you can edit `C:/local/vcpkg/ports/realsense2/portfile.cmake`.
Change the SHA512 in line 7 from `b00cd4617d59197f7baa40d5a4833027c2b0c45e3e67047dce38e9415905ecf78c1ee9fe499c8e3292b54b8de8e96064001d0f154fdb10b2c64c19a8162db6d1 ` to `af5f77eb69620e8485bbe0b7c82c405ed518c50b3319e4c174c002180c4842d5dbfaab354051ed4b287effac58ae93dd1160ebc27d35def58e685874a89c02ee `.
After the change It will work fine.

**Comment by JackBoosY** [comment]
Hi @adgbu , this port can be build successful in latest version.
Plz update vcpkg and rebuild realsense2.
Thx.

**Comment by JackBoosY** [comment]
Please open a new issue if this is still a problem for you.
Thx.
