### ISSUE TITLE
[libyuv] update to 1857

### ISSUE THREAD

**Issue by Starbuck5** [microsoft/vcpkg#29023]
Library name: libyuv

New version number: 1857

Other information that may be useful (release notes, etc...):
This library seems to increment their "version number" every commit. The current version ported in vcpkg is 1786, which is from April of 2021.

My project is moving to use vcpkg, and our previous solution for libyuv (vendoring) had a more up to date copy of libyuv, which meant moving to vcpkg caused build failures.

**Comment by cnSchwarzer** [comment]
Hi, where do you get the version number?  I didn't find it in https://chromium.googlesource.com/libyuv/libyuv 
Also, take a look at #29032.  ;D

**Comment by Starbuck5** [comment]
Wow, thanks for such a quick response!

I found it in include/version.h

**Comment by cnSchwarzer** [comment]
Thanks, I will change version to that in the PR.

**Comment by Starbuck5** [comment]
There’s nothing special about that version, it was just the latest when I looked earlier. 🙂
