### ISSUE TITLE
cgal doesn't declare all necessary dependencies on boost

### ISSUE THREAD

**Issue by jjpepper** [Microsoft/vcpkg#2902]
It's all in the title.  There are a lot of dependencies missing.  I suggest making it depend on the whole of boost.

**Comment by jasjuang** [comment]
Thanks for reporting, can you let me know which boost dependencies are missing? I will update it accordingly. Depending on the whole boost might not be a good idea since @ras0219-msft makes a good effort to make boost modularized.

**Comment by jjpepper** [comment]
I went one by one and gave up after about 10.  I also imagine it depends on
which CGAL headers are used, so you may think you have everything you need
then you include a new CGAL header and then you get another problem.

**Comment by jasjuang** [comment]
@jjpepper Good point. When I created the port initially I made it depend on the whole boost, but then @ras0219-msft updated it with modularized boost. @ras0219-msft how did you pick out which boost module cgal should be depended on?

**Comment by jasjuang** [comment]
@ras0219-msft I didn't quite understand how the generate-ports.ps1 is used to generate the right boost module dependencies for cgal. I ran generate-ports.ps1 on powershell and it just generates a bunch of new boost portfile and control files.

**Comment by Cheney-W** [comment]
@jjpepper , I saw this PR:https://github.com/Microsoft/vcpkg/pull/3646 added some boost libraries in depends. If your issue was fixed by it, could you help closed this issue?

**Comment by jjpepper** [comment]
@Cheney-W yep this seems to be all fixed with a recent pull.
