### ISSUE TITLE
Build Failed - Libepoxy - LNK1104

### ISSUE THREAD

**Issue by henrikse55** [Microsoft/vcpkg#2903]
I'm trying to install gtkmm and when it's trying to build libepoxy it fails.
As far as I can see it's a Linker problem according to the meson-log.txt
`
"/out:D:\Program Files (x86)\vcpkg\buildtrees\libepoxy\x86-windows-rel\meson-private\sanitycheckc.exe" 
sanitycheckc.obj 
LINK : fatal error LNK1104: cannot open file 'D:\Program Files (x86)\vcpkg\buildtrees\libepoxy\x86-windows-rel\meson-private\sanitycheckc.exe'
`

The file that it can't open aren't there, there are a .c and .obj but no .exe

**Comment by JackBoosY** [comment]
Hi @henrikse55 , gtkmm is not depends libepoxy currently. Here is gtkmm depends port list:

> PS E:\vcpkg> .\vcpkg.exe install gtkmm
The following packages will be built and installed:
  * atk[core]:x86-windows
  * atkmm[core]:x86-windows
  * cairo[core]:x86-windows
  * cairomm[core]:x86-windows
  * fontconfig[core]:x86-windows
  * freetype[core]:x86-windows
  * gdk-pixbuf[core]:x86-windows
  * glib[core]:x86-windows
  * glibmm[core]:x86-windows
  * gtk[core]:x86-windows
    gtkmm[core]:x86-windows
  * harfbuzz[core,glib,ucdn]:x86-windows
  * libpng[core]:x86-windows
  * pango[core]:x86-windows
  * pangomm[core]:x86-windows
  * zlib[core]:x86-windows

And libepoxy can install correctly. Plz update vcpkg and rerun install command.
Thx.
