### ISSUE TITLE
cffi-lua can not be downloaded

### ISSUE THREAD

**Issue by DmitryOvsyannikov1978** [microsoft/vcpkg#29039]
PS C:\Users\79151\source\repos\vcpkg> .\vcpkg search cffi-lua
The result may be outdated. Run `git pull` to get the latest results.
If your port is not listed, please open an issue at and/or consider making a pull request.    -  https://github.com/Microsoft/vcpkg/issues
PS C:\Users\79151\source\repos\vcpkg>
PS C:\Users\79151\source\repos\vcpkg>
PS C:\Users\79151\source\repos\vcpkg>
PS C:\Users\79151\source\repos\vcpkg>
PS C:\Users\79151\source\repos\vcpkg>
PS C:\Users\79151\source\repos\vcpkg> .\vcpkg search libffi
libffi                   3.4.4            Portable, high level programming interface to various calling conventions
The result may be outdated. Run `git pull` to get the latest results.
If your port is not listed, please open an issue at and/or consider making a pull request.    -  https://github.com/Microsoft/vcpkg/issues
PS C:\Users\79151\source\repos\vcpkg>
PS C:\Users\79151\source\repos\vcpkg> .\vcpkg search cffi-lua
The result may be outdated. Run `git pull` to get the latest results.
If your port is not listed, please open an issue at and/or consider making a pull request.    -  https://github.com/Microsoft/vcpkg/issues
PS C:\Users\79151\source\repos\vcpkg> git pull
Already up to date.
PS C:\Users\79151\source\repos\vcpkg>
PS C:\Users\79151\source\repos\vcpkg> .\vcpkg search cffi-lua
The result may be outdated. Run `git pull` to get the latest results.
If your port is not listed, please open an issue at and/or consider making a pull request.    -  https://github.com/Microsoft/vcpkg/issues
PS C:\Users\79151\source\repos\vcpkg>

**Comment by autoantwort** [comment]
Because there is no port `cffi-lua`
