### ISSUE TITLE
[xlnt] build failure

### ISSUE THREAD

**Issue by johnco3** [microsoft/vcpkg#29049]
**Host Environment**

- OS: [Windows 10 21H2]
- Compiler: Visual Studio 2022 
- Microsoft Visual Studio Community 2022
Version 17.4.3
VisualStudio.17.Release/17.4.3+33205.214
Microsoft .NET Framework
Version 4.8.04084
Installed Version: Community
Visual C++ 2022   00482-90000-00000-AA942
Microsoft Visual C++ 2022
ASP.NET and Web Tools   17.4.326.54890
ASP.NET and Web Tools
Azure App Service Tools v3.0.0   17.4.326.54890
Azure App Service Tools v3.0.0
C# Tools   4.4.0-6.22580.4+d7a61210a88b584ca0827585ec6e871c6b1c5a14
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
Linux Core Dump Debugging   1.0.9.33020
Enables debugging of Linux core dumps.
Microsoft JVM Debugger   1.0
Provides support for connecting th
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/10451450/install-x64-windows-dbg-out.log)
e Visual Studio debugger to JDWP compatible Java Virtual Machines
NuGet Package Manager   6.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/
Qt Visual Studio Tools   2.10.1.2
The Qt Visual Studio Tools allow developers to use the standard development environment without having to worry about any Qt-related build steps or tools.
Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.
Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.
TypeScript Tools   17.0.10921.2001
TypeScript Tools for Microsoft Visual Studio
Visual Basic Tools   4.4.0-6.22580.4+d7a61210a88b584ca0827585ec6e871c6b1c5a14
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
Visual C++ for Linux Development   1.0.9.33020
Visual C++ for Linux Development
Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

**To Reproduce**

`./vcpkg install xlnt:x64-windows`

**Failure logs**
error: building xlnt:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+xlnt
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[xlnt]+Build+error
Include '[xlnt] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: a5f93b05d 2023-01-18 (48 minutes ago)

- Cut and paste the appropriate build messages from the console output.
C:\tools\vcpkg [master ≡ +2 ~2 -0 !]> .\vcpkg.exe install xlnt:x64-windows
Computing installation plan...
The following packages will be built and installed:
    xlnt[core]:x64-windows -> 1.5.0#4
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\jcoffey\AppData\Local\vcpkg\archives in 319.8 us. Use --debug to see more details.
Installing 1/1 xlnt:x64-windows...
Building xlnt[core]:x64-windows...
-- Using cached tfussell-xlnt-568ac85346bc37757b0cd16464e7e1ea7656df91.tar.gz.
-- Cleaning sources at C:/tools/vcpkg/buildtrees/xlnt/src/ea7656df91-01f12cf1a4.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/tools/vcpkg/downloads/tfussell-xlnt-568ac85346bc37757b0cd16464e7e1ea7656df91.tar.gz
-- Applying patch fix-not-found-include.patch
-- Applying patch fix-missing-include.patch
-- Using source at C:/tools/vcpkg/buildtrees/xlnt/src/ea7656df91-01f12cf1a4.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/tools/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: C:/tools/vcpkg/buildtrees/xlnt/x64-windows-dbg
    See logs for more information:
      C:\tools\vcpkg\buildtrees\xlnt\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/xlnt/portfile.cmake:31 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building xlnt:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+xlnt
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[xlnt]+Build+error
Include '[xlnt] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: a5f93b05d 2023-01-18 (79 minutes ago)

- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue. 
I did a clean install of the entire vcpkg folder and just built xlnt:x64-windows standalone and the failure persists.

After opening up the log file it appeas

**Comment by FrankXie05** [comment]
@johnco3 Please provide the error log. `C:\tools\vcpkg\buildtrees\xlnt\install-x64-windows-dbg-out.log`

**Comment by Cheney-W** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.

**Comment by d-ranjan** [comment]
got the same issue
vcpkg install xlnt:x64-mingw-dynamic

OS: [Windows 11 22H2]
Compiler: MinGW 14.2.0

**Comment by d-ranjan** [comment]
I was able to build after patching the source

Patch:
[fix-build-with-mingw1420.patch](https://github.com/user-attachments/files/16640740/fix-build-with-mingw1420.patch)

**Comment by sfhacker** [comment]
This issue is OVER a year OLD!

**Comment by d-ranjan** [comment]
Sorry if it causes some inconvenience, I put it here for reference. If I get this bug again.
