### ISSUE TITLE
[vcpkg-gn] Build failure

### ISSUE THREAD

**Issue by cnSchwarzer** [microsoft/vcpkg#29057]
I am fixing gn build on Windows, and while I'm trying to modify `vcpkg-gn`, I found `vcpkg-gn` is broken. 
It seems the `z_vcpkg_gn_real_path.cmake` is not installed at all.

By the way, is this port deprecated? Show we prefer use built-in `vcpkg_configure_gn` instead?

Package: crashpad[core]:x64-windows -> 2022-09-05#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.34.31937.0
-    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: 5908d702d 2023-01-17 (26 hours ago)

**To Reproduce**

`vcpkg install crashpad`

**Failure logs**

```
CMake Error at installed/x64-windows/share/vcpkg-gn/vcpkg_gn_configure.cmake:2 (include):
  include could not find requested file:

    C:/vcpkg/installed/x64-windows/share/vcpkg-gn/z_vcpkg_gn_real_path.cmake
Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-gn/vcpkg-port-config.cmake:1 (include)
  scripts/ports.cmake:134 (include)



```
<details><summary>E:\b\crashpad\build-x64-windows-dbg-out.log</summary>

```
ninja: Entering directory `E:/b/crashpad/x64-windows-dbg'
```
</details>
<details><summary>E:\b\crashpad\build-x64-windows-dbg-err.log</summary>

```
ninja: error: FindFirstFileExA(../../../../c:/vcpkg/installed/x64-windows/debug/lib): �ļ�����Ŀ¼��������﷨����ȷ��


```
</details>

**Additional context**

**Comment by dg0yt** [comment]
> By the way, is this port deprecated? Show we prefer use built-in vcpkg_configure_gn instead?

I suppose it was meant to be the future. But I found that it it is not used in vcpkg, and it did not really make any progress. This were I would move changes as I did to the skia port when I have enough confidence that I can generalize them.

**Comment by dg0yt** [comment]
BTW IMO building the gn tool from source is still an option if there are good reasons. vcpkg also build `qmake` and `pkgconf`.

**Comment by cnSchwarzer** [comment]
> BTW IMO building the gn tool from source is still an option if there are good reasons. vcpkg also build `qmake` and `pkgconf`. 

There're good reasons (like #29058) that we can apply patches, but #28974 said no.

**Comment by dg0yt** [comment]
> but #28974 said no.

... I know that answer. But is the first-level review, sometimes not deep enough. Second-level review may have a different opinion if it breaks manifest mode users in Visual Studio.

**Comment by cnSchwarzer** [comment]
> ... I know that answer. But this is the first-level review, sometimes not deep enough. Second-level review may have a different opinion, at least if it breaks manifest mode users in Visual Studio.

Agree, and let's first try the cmake patch, both way works.

**Comment by cnSchwarzer** [comment]
To follow up, I'm trying to patch this in gn upstream https://gn-review.googlesource.com/c/gn/+/16620.
I also confirmed this patch fixed the path issue. https://bugs.chromium.org/p/gn/issues/detail?id=317
