### ISSUE TITLE
[<port name>] build failure

### ISSUE THREAD

**Issue by BioGameWare** [microsoft/vcpkg#29073]
**Host Environment**

- OS: windows
- Compiler: revision

**To Reproduce**

PS D:\src\vcpkg> .\vcpkg search abseil

**Failure logs**

- access is denied

**Additional context**

I've been trying to download the C++ standard library and every time I try it, the only message i get is "access is denied"

**Comment by JonLiu1993** [comment]
@BioGameWare, Thanks for posting this issue, usually an Anti-Virus thing, does this problem still exist?

**Comment by Cheney-W** [comment]
We haven't been able to repro this, if more information comes up, or this issue appears again, please reopen.
