### ISSUE TITLE
cpr update to 1.6

### ISSUE THREAD

**Issue by phoenicyan** [microsoft/vcpkg#29076]
Library name: cpr

New version number: 1.6 (or later)

Current vcpkg version of libcpr is 1.3. Due to large adoption of OAuth, a newer version of cpr is needed that supports Bearer token, etc.

**Comment by cnSchwarzer** [comment]
You can try it yourself if you have time ;D, it is fun!

**Comment by chausner** [comment]
> Current vcpkg version of libcpr is 1.3.

The current version of cpr in vcpkg is 1.9.2, see https://github.com/microsoft/vcpkg/blob/master/ports/cpr/vcpkg.json.

**Comment by phoenicyan** [comment]
Thank you for the prompt responses! However, when I ran "vcpkg upgrade cpr:x86-windows-static" or "vcpkg install cpr:x86-windows-static", it still results in version 1.3. What am I missing? Should I build from the source? I need to use static library in a VS2019 C++ project. Thanks!

**Comment by dg0yt** [comment]
Update your vcpkg git checkout (git pull, re-run bootstrap).

**Comment by cnSchwarzer** [comment]
Maybe we should add a warning about not fetch vcpkg for too long?

**Comment by dg0yt** [comment]
Something like `vcpkg search`already does?
~~~
% ./vcpkg search cpr  
cpr                      1.9.2            C++ Requests is a simple wrapper around libcurl inspired by the excellent ...
cpr[ssl]                                  Enable SSL support
sleepy-discord[cpr]                       Use CPR library for handling HTTPS
The result may be outdated. Run `git pull` to get the latest results.
If your port is not listed, please open an issue at and/or consider making a pull request.    -  https://github.com/Microsoft/vcpkg/issues
~~~

**Comment by dg0yt** [comment]
Or something like the error message footer:
~~~
    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: 37f324184 2023-01-21 (22 hours ago)
~~~

**Comment by cnSchwarzer** [comment]
These are not very straight forward, maybe a yellow warning text like:

It has been 54 days since last time you update vcpkg, run git pull to update.

**Comment by phoenicyan** [comment]
The following worked:
vcpkg> git pull
vcpkg> bootstrap
vcpkg> vcpkg upgrade cpr:x86-windows-static --no-dry-run

Thank you very much for the help!
