### ISSUE TITLE
Suggestions for graph output

### ISSUE THREAD

**Issue by cmpute** [microsoft/vcpkg#2907]
I noticed that `vcpkg search` has an option `--graph`, and that's great for dependency analysing. However, I found two possible improvements for it
1. The description for `--graph` in `vcpkg help search` is wrong. (It's a copy of `vcpkg help edit`)
2. I think it would be great if there is a command like `vcpkg search <package> --dependency-graph` that could generate two graphs, one is a graph containing all ports that depends on the package and another one is a graph containing all ports that the package depends on.

    It's like, if there is a depend relationship as follows
    ```
    A<--B<--C<--E<--F
            ^----D<--|
    ```

    Then `vcpkg search C --dependency-graph` returns a graph with nodes E, F and a graph with nodes A, B in my expectation. Furthermore, there can be another command that output the graphs as plain lists.

This is a simple feature to add, I can help with it. I'm considering how to name the command.

**Comment by DeveloperPaul123** [comment]
I just tried the `--graph` option and it doesn't seem to be available for me. Am I missing something?

**Comment by Cheney-W** [comment]
1. --graph option should be removed from the search command.
2. .\vcpkg depend-info <port> could be used for checking the dependency.
3. @cmpute , you second point is great, if possible, please file a PR to us. Thank you.

**Comment by PhoebeHui** [comment]
--graph has been removed for a long time, please use '.\vcpkg depend-info xxx' to check the dependency instead.
