### ISSUE TITLE
libzip failing on Bzip2 link interface on linux

### ISSUE THREAD

**Issue by winterz** [microsoft/vcpkg#29080]
On llinux using this manifest vcpkg.json:

```
{
    "name": "application-framework",
    "version": "0.5.0",
    "dependencies": [
        "libzip",
        "boost-test",
        "nlohmann-json"
    ],
    "builtin-baseline": "5b8640fab18484ac0a7759123ebab37b04ffe1d9"
}
```

Then in my CMakeLists.txt I have `find_package(LibZip)` 

which fails with
```
CMake Error at build-clang-RelWithDebInfo/vcpkg_installed/x64-linux/share/libzip/libzip-targets.cmake:60 (set_target_properties):
  The link interface of target "libzip::zip" contains:

    BZip2::BZip2

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```

I tried adding bzip2 to the manifest but that didn't help.

**Comment by dg0yt** [comment]
Which version of CMake do you use for your project?

**Comment by winterz** [comment]
```
$ cmake --version
cmake version 3.25.1
```

**Comment by dg0yt** [comment]
Okay... Then you should at least share the error's call stack, if not a whole log with --trace-expand

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Could you please provide your CMakeLists.txt? If you use `find_package(libzip CONFIG REQUIRED)` provided by vcpkg in your project, does this error still exist?
```
CMake Error at build-clang-RelWithDebInfo/vcpkg_installed/x64-linux/share/libzip/libzip-targets.cmake:60 (set_target_properties):
  The link interface of target "libzip::zip" contains:

    BZip2::BZip2

  but the target was not found.  Possible reasons include:
```

**Comment by dg0yt** [comment]
The error is from `libzip-targets.cmake`. This implies the answer to your question @LilyWangLL: the error is with `libzip CONFIG`.

**Comment by winterz** [comment]
I'm not sure this is happening any longer.
will close this for now and re-open if I encounter again.

probably it was something in the project CMakeLists.txt
