### ISSUE TITLE
[aws-sdk-cpp] update to 1.10

### ISSUE THREAD

**Issue by prateek9623** [microsoft/vcpkg#29083]
Library name: aws-sdk-cpp

New version number: 1.10.55

The existing version has a bug after aws-c-io's https://github.com/awslabs/aws-c-io/pull/475, which is updated in vcpkg. This bug was fixed at this commit https://github.com/aws/aws-sdk-cpp/commit/0227ef625c2c53689c61cb9d09eeeea2a78611fb .

**Comment by JonLiu1993** [comment]
Fixed by PR #29236
