### ISSUE TITLE
Install qt5-base didnt support export feature properly

### ISSUE THREAD

**Issue by apattnaik0721013** [Microsoft/vcpkg#2908]
1. installing qt5-base in x64-windows triplet successful
2, used vcpkg export command for qt5-base and used it in different machine,
3. In different machine , try to run "qmake --version" from the exported folder/installed/x64-windows/tools/qt5

it shows the lib path of original system path where it is actually built

**Comment by glachancecmaisonneuve** [comment]
this is fixed in PR https://github.com/Microsoft/vcpkg/pull/2892.  You don't even have to rebuild to test out that PR, all you need to do is create the following qt.conf file in the tool's folder (so tools/qt5 for qmake & qml, and the same file again in tools/qt5-tools for designer & linguist):

```
[Paths]
Prefix = ../../
Documentation = share/qt5/doc
Headers = include
Libraries = lib
Binaries = tools/qt5
LibraryExecutables = tools/qt5
Plugins = plugins
Qml2Imports = qml
Data = share/qt5
ArchData = share/qt5
HostData = share/qt5
HostBinaries = tools/qt5
```

**Comment by glachancecmaisonneuve** [comment]
@apattnaik0721013 if you have a minute to add a qt.conf file with the content as described above to your exported vcpkg tools (vcpkg-export/installed/your-triplet/tools/qt5 in your case) and report in it would be greatly appreciated.

**Comment by JackBoosY** [comment]
Hi @apattnaik0721013 , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
