### ISSUE TITLE
[poco] Allow building for openssl on Windows platforms

### ISSUE THREAD

**Issue by MCJack123** [microsoft/vcpkg#29124]
****

**Is your feature request related to a problem? Please describe.**
My program uses Poco::NetSSL for HTTPS support, but it fails to compile by default on Windows with vcpkg because Poco's WinSSL-based version of NetSSL is incompatible API-wise with OpenSSL-based NetSSL. I have to patch the portfile to use OpenSSL on Windows to be able to build.

**Proposed solution**
Add an `openssl` feature to `poco` that will force OpenSSL-NetSSL on all platforms, allowing programs that rely on the OpenSSL API to be built on Windows.

**Describe alternatives you've considered**
There's also the possibility of removing the WinSSL backend entirely.

**Additional context**
Errors in the build log:
```
  D:\a\craftos2\craftos2\src\apis\http.cpp(282,51): error C2661: 'Poco::Net::Context::Context': no overloaded function takes 6 arguments [D:\a\craftos2\craftos2\CraftOS-PC 2.vcxproj]
  D:\a\craftos2\craftos2\src\apis\http.cpp(427,35): error C2661: 'Poco::Net::Context::Context': no overloaded function takes 6 arguments [D:\a\craftos2\craftos2\CraftOS-PC 2.vcxproj]
  D:\a\craftos2\craftos2\src\apis\http.cpp(1129,39): error C2661: 'Poco::Net::Context::Context': no overloaded function takes 6 arguments [D:\a\craftos2\craftos2\CraftOS-PC 2.vcxproj]
  D:\a\craftos2\craftos2\src\main.cpp(695,47): error C2661: 'Poco::Net::Context::Context': no overloaded function takes 6 arguments [D:\a\craftos2\craftos2\CraftOS-PC 2.vcxproj]
  D:\a\craftos2\craftos2\src\platform\win.cpp(21,10): fatal  error C1083: Cannot open include file: 'Poco/Crypto/X509Certificate.h': No such file or directory (compiling source file src\platform.cpp) [D:\a\craftos2\craftos2\CraftOS-PC 2.vcxproj]
```

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. According this comment https://github.com/microsoft/vcpkg/pull/16526#issuecomment-800498508, you should be controlled `OpenSSL-NetSSL` using [overlays](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/versioning.md#44-declaring-overrides) on Windows.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
