### ISSUE TITLE
Cannot install Opencv4 - libjpeg/ Need help ASAP

### ISSUE THREAD

**Issue by brusbcn** [microsoft/vcpkg#29136]
Building libjpeg-turbo[core]:x64-windows...
-- Downloading https://github.com/libjpeg-turbo/libjpeg-turbo/archive/2.1.4.tar.gz -> libjpeg-turbo-libjpeg-turbo-2.1.4.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
Downloading https://github.com/libjpeg-turbo/libjpeg-turbo/archive/2.1.4.tar.gz
warning: Download failed -- retrying after 1000ms
warning: Download failed -- retrying after 2000ms
warning: Download failed -- retrying after 4000ms
error: Failed to download from mirror set
error: https://github.com/libjpeg-turbo/libjpeg-turbo/archive/2.1.4.tar.gz: WinHttpReceiveResponse failed with exit code 12175
error: https://github.com/libjpeg-turbo/libjpeg-turbo/archive/2.1.4.tar.gz: WinHttpReceiveResponse failed with exit code 12175
error: https://github.com/libjpeg-turbo/libjpeg-turbo/archive/2.1.4.tar.gz: WinHttpReceiveResponse failed with exit code 12175
error: https://github.com/libjpeg-turbo/libjpeg-turbo/archive/2.1.4.tar.gz: WinHttpReceiveResponse failed with exit code 12175
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(956):
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 3 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 9381 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 8.099 s (8079598 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. Your proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:273 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/libjpeg-turbo/portfile.cmake:5 (vcpkg_from_github)
  scripts/ports.cmake:147 (include)

error: building libjpeg-turbo:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libjpeg-turbo
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libjpeg-turbo]+Build+error
Include '[libjpeg-turbo] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: e69dd972b 2023-01-20 (2 days ago)

I have all vcpkg updated, however, it cannot be installed Opencv4.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Could you please try to download https://github.com/libjpeg-turbo/libjpeg-turbo/archive/2.1.4.tar.gz manually and put the archive file into downloads folder, then rebuild this?
Please use proxy to download those files.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
