### ISSUE TITLE
[libmysql] build failure

### ISSUE THREAD

**Issue by baijiu1** [microsoft/vcpkg#29148]
- OS: 
- MacOS M1 Pro 13.0.1
- 
- Compiler: revision
➜  vcpkg git:(master) ./vcpkg --version
vcpkg package management program version 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9

See LICENSE.txt for license information.
---------

when I use c++ connect mysql, I will install libmysql library, get this error.
error log:

➜  vcpkg git:(master) ./vcpkg install libmysql
Computing installation plan...
The following packages will be built and installed:
  * icu[core]:arm64-osx -> 72.1
  * libevent[core,thread]:arm64-osx -> 2.1.12#7
    libmysql[core]:arm64-osx -> 8.0.20#9
  * lz4[core]:arm64-osx -> 1.9.4#1
  * ncurses[core]:arm64-osx -> 6.3#4
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet arm64-osx...
Restored 0 package(s) from /Users/haruhi/.cache/vcpkg/archives in 45.92 us. Use --debug to see more details.
Installing 1/5 icu:arm64-osx...
Building icu[core]:arm64-osx...
warning: -- Using community triplet arm64-osx. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /Users/haruhi/ClionProjects/vcpkg/triplets/community/arm64-osx.cmake
-- Using cached icu4c-72_1-src.tgz.
-- Cleaning sources at /Users/haruhi/ClionProjects/vcpkg/buildtrees/icu/src/c-72_1-src-507f6288e7.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/haruhi/ClionProjects/vcpkg/downloads/icu4c-72_1-src.tgz
-- Applying patch disable-escapestr-tool.patch
-- Applying patch remove-MD-from-configure.patch
-- Applying patch fix_parallel_build_on_windows.patch
-- Applying patch fix-extra.patch
-- Applying patch mingw-dll-install.patch
-- Applying patch disable-static-prefix.patch
-- Applying patch fix-win-build.patch
-- Using source at /Users/haruhi/ClionProjects/vcpkg/buildtrees/icu/src/c-72_1-src-507f6288e7.clean
-- Found external ninja('1.11.1').
-- Getting CMake variables for arm64-osx-dbg
-- Getting CMake variables for arm64-osx-rel
-- Generating configure for arm64-osx
-- Finished generating configure for arm64-osx
-- Configuring arm64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /bin/bash -c "V=1 ./../src/c-72_1-src-507f6288e7.clean/source/configure --host=aarch64-apple-darwin \"--disable-samples\" \"--disable-tests\" \"--disable-layoutex\" \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"--enable-debug\" \"--disable-release\" \"--prefix=/Users/haruhi/ClionProjects/vcpkg/installed/arm64-osx/debug\" \"--bindir=\\${prefix}/../tools/icu/debug/bin\" \"--sbindir=\\${prefix}/../tools/icu/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/icu\""
    Working Directory: /Users/haruhi/ClionProjects/vcpkg/buildtrees/icu/arm64-osx-dbg
    Error code: 1
    See logs for more information:
      /Users/haruhi/ClionProjects/vcpkg/buildtrees/icu/config-arm64-osx-dbg-config.log
      /Users/haruhi/ClionProjects/vcpkg/buildtrees/icu/config-arm64-osx-dbg-out.log
      /Users/haruhi/ClionProjects/vcpkg/buildtrees/icu/config-arm64-osx-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:811 (vcpkg_execute_required_process)
  ports/icu/portfile.cmake:50 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)

error: building icu:arm64-osx failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+icu
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[icu]+Build+error
Include '[icu] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: e69dd972b 2023-01-20 (3 days ago)

Please use the prefilled template from /Users/haruhi/ClionProjects/vcpkg/installed/vcpkg/issue_body.md when reporting your issue.

thanks!

**Comment by MonicaLiu0311** [comment]
```
vcpkg@VCPKGMM-12 vcpkg % ./vcpkg install libmysql
Computing installation plan...
The following packages are already installed:
    libmysql[core]:x64-osx -> 8.0.20#9
libmysql:x64-osx is already installed
Restored 0 package(s) from /Users/vcpkg/.cache/vcpkg/archives in 3.126 us. Use --debug to see more details.
Total elapsed time: 96.83 ms

The package libmysql provides CMake targets:

    find_package(libmysql REQUIRED)
    target_link_libraries(main PRIVATE ${MYSQL_LIBRARIES})
```

```
vcpkg@VCPKGMM-12 vcpkg % ./vcpkg --version
vcpkg package management program version 2022-10-17-3247920fbdd47d08f36cbd480addd9890d3c2435

See LICENSE.txt for license information.
```

I'm sorry that I can't reproduce your issue. I found that the `icu` version you installed is `72.1`, but there was a new update for `icu` yesterday, please run `git pull https://github.com/microsoft/vcpkg.git master` to update to the latest version and try again.

**Comment by baijiu1** [comment]
> ```
> vcpkg@VCPKGMM-12 vcpkg % ./vcpkg install libmysql
> Computing installation plan...
> The following packages are already installed:
>     libmysql[core]:x64-osx -> 8.0.20#9
> libmysql:x64-osx is already installed
> Restored 0 package(s) from /Users/vcpkg/.cache/vcpkg/archives in 3.126 us. Use --debug to see more details.
> Total elapsed time: 96.83 ms
> 
> The package libmysql provides CMake targets:
> 
>     find_package(libmysql REQUIRED)
>     target_link_libraries(main PRIVATE ${MYSQL_LIBRARIES})
> ```
> 
> 
>     
>  
>   
> 
> ```
> vcpkg@VCPKGMM-12 vcpkg % ./vcpkg --version
> vcpkg package management program version 2022-10-17-3247920fbdd47d08f36cbd480addd9890d3c2435
> 
> See LICENSE.txt for license information.
> ```
> 
> 
>      
>   
> 
> I'm sorry that I can't reproduce your issue. I found that the `icu` version you installed is `72.1`, but there was [a new update](https://github.com/microsoft/vcpkg/pull/29196) for `icu` yesterday, please run `git pull https://github.com/microsoft/vcpkg.git master` to update to the latest version and try again.


This is so strange. I update vcpkg package latest, but icu version is still 72.1.

this is my operate command:

➜  vcpkg git:(master) git pull https://github.com/microsoft/vcpkg.git master
From https://github.com/microsoft/vcpkg
 * branch                master     -> FETCH_HEAD
Already up to date.

➜  vcpkg git:(master) 
➜  vcpkg git:(master) ls
CONTRIBUTING.md     NOTICE_pt.txt       README_pt.md        buildtrees          ports               vcpkg
CONTRIBUTING_pt.md  README.md           README_zh_CN.md     docs                scripts             versions
CONTRIBUTING_zh.md  README_es.md        SECURITY.md         downloads           shell.nix
LICENSE.txt         README_fr.md        bootstrap-vcpkg.bat installed           toolsrc
NOTICE.txt          README_ko_KR.md     bootstrap-vcpkg.sh  packages            triplets

➜  vcpkg git:(master) ./bootstrap-vcpkg.sh 
Downloading vcpkg-macos...
Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
➜  vcpkg git:(master) ./vcpkg install libmysql                              
Computing installation plan...
The following packages will be built and installed:
  * icu[core,tools]:arm64-osx -> 72.1#1
  * libevent[core,thread]:arm64-osx -> 2.1.12#7
    libmysql[core]:arm64-osx -> 8.0.20#9
  * lz4[core]:arm64-osx -> 1.9.4#1
  * ncurses[core]:arm64-osx -> 6.4
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet arm64-osx...
Restored 0 package(s) from /Users/haruhi/.cache/vcpkg/archives in 19.29 us. Use --debug to see more details.
Installing 1/5 icu:arm64-osx...
Building icu[core,tools]:arm64-osx...
warning: -- Using community triplet arm64-osx. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /Users/haruhi/ClionProjects/vcpkg/triplets/community/arm64-osx.cmake
-- Using cached icu4c-72_1-src.tgz.
-- Cleaning sources at /Users/haruhi/ClionProjects/vcpkg/buildtrees/icu/src/c-72_1-src-507f6288e7.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/haruhi/ClionProjects/vcpkg/downloads/icu4c-72_1-src.tgz
-- Applying patch disable-escapestr-tool.patch
-- Applying patch remove-MD-from-configure.patch
-- Applying patch fix_parallel_build_on_windows.patch
-- Applying patch fix-extra.patch
-- Applying patch mingw-dll-install.patch
-- Applying patch disable-static-prefix.patch
-- Applying patch fix-win-build.patch
-- Using source at /Users/haruhi/ClionProjects/vcpkg/buildtrees/icu/src/c-72_1-src-507f6288e7.clean
-- Found external ninja('1.11.1').
-- Getting CMake variables for arm64-osx-dbg
-- Getting CMake variables for arm64-osx-rel
-- Generating configure for arm64-osx
-- Finished generating configure for arm64-osx
-- Configuring arm64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /bin/bash -c "V=1 ./../src/c-72_1-src-507f6288e7.clean/source/configure --host=aarch64-apple-darwin \"--disable-samples\" \"--disable-tests\" \"--disable-layoutex\" \"--enable-tools\" \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"--enable-debug\" \"--disable-release\" \"--prefix=/Users/haruhi/ClionProjects/vcpkg/installed/arm64-osx/debug\" \"--bindir=\\${prefix}/../tools/icu/debug/bin\" \"--sbindir=\\${prefix}/../tools/icu/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/icu\""
    Working Directory: /Users/haruhi/ClionProjects/vcpkg/buildtrees/icu/arm64-osx-dbg
    Error code: 1
    See logs for more information:
      /Users/haruhi/ClionProjects/vcpkg/buildtrees/icu/config-arm64-osx-dbg-config.log
      /Users/haruhi/ClionProjects/vcpkg/buildtrees/icu/config-arm64-osx-dbg-out.log
      /Users/haruhi/ClionProjects/vcpkg/buildtrees/icu/config-arm64-osx-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:811 (vcpkg_execute_required_process)
  ports/icu/portfile.cmake:55 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)


error: building icu:arm64-osx failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+icu
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[icu]+Build+error
Include '[icu] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 91dd61bd4 2023-01-27 (3 days ago)


Please use the prefilled template from /Users/haruhi/ClionProjects/vcpkg/installed/vcpkg/issue_body.md when reporting your issue.
------------
my vcpkg list:
➜  vcpkg git:(master) ./vcpkg list          
boost-algorithm:arm64-osx                         1.81.0              Boost algorithm module
boost-align:arm64-osx                             1.81.0              Boost align module
boost-any:arm64-osx                               1.81.0              Boost any module
boost-array:arm64-osx                             1.81.0              Boost array module
boost-assert:arm64-osx                            1.81.0              Boost assert module
boost-atomic:arm64-osx                            1.81.0              Boost atomic module
boost-bimap:arm64-osx                             1.81.0              Boost bimap module
boost-bind:arm64-osx                              1.81.0              Boost bind module
boost-build:arm64-osx                             1.81.0              Boost.Build
boost-chrono:arm64-osx                            1.81.0              Boost chrono module
boost-concept-check:arm64-osx                     1.81.0              Boost concept_check module
boost-config:arm64-osx                            1.81.0              Boost config module
boost-container-hash:arm64-osx                    1.81.0              Boost container_hash module
boost-container:arm64-osx                         1.81.0              Boost container module
boost-conversion:arm64-osx                        1.81.0              Boost conversion module
boost-core:arm64-osx                              1.81.0              Boost core module
boost-date-time:arm64-osx                         1.81.0              Boost date_time module
boost-describe:arm64-osx                          1.81.0              Boost describe module
boost-detail:arm64-osx                            1.81.0              Boost detail module
boost-dynamic-bitset:arm64-osx                    1.81.0              Boost dynamic_bitset module
boost-endian:arm64-osx                            1.81.0              Boost endian module
boost-exception:arm64-osx                         1.81.0              Boost exception module
boost-foreach:arm64-osx                           1.81.0              Boost foreach module
boost-format:arm64-osx                            1.81.0              Boost format module
boost-function-types:arm64-osx                    1.81.0              Boost function_types module
boost-function:arm64-osx                          1.81.0              Boost function module
boost-functional:arm64-osx                        1.81.0              Boost functional module
boost-fusion:arm64-osx                            1.81.0              Boost fusion module
boost-geometry:arm64-osx                          1.81.0              Boost geometry module
boost-graph:arm64-osx                             1.81.0              Boost graph module
boost-integer:arm64-osx                           1.81.0              Boost integer module
boost-intrusive:arm64-osx                         1.81.0              Boost intrusive module
boost-io:arm64-osx                                1.81.0              Boost io module
boost-iterator:arm64-osx                          1.81.0              Boost iterator module
boost-lambda:arm64-osx                            1.81.0              Boost lambda module
boost-lexical-cast:arm64-osx                      1.81.0              Boost lexical_cast module
boost-math:arm64-osx                              1.81.0              Boost math module
boost-modular-build-helper:arm64-osx              1.81.0              Internal vcpkg port used to build Boost libraries
boost-move:arm64-osx                              1.81.0              Boost move module
boost-mp11:arm64-osx                              1.81.0              Boost mp11 module
boost-mpl:arm64-osx                               1.81.0              Boost mpl module
boost-multi-index:arm64-osx                       1.81.0              Boost multi_index module
boost-multiprecision:arm64-osx                    1.81.0              Boost multiprecision module
boost-numeric-conversion:arm64-osx                1.81.0              Boost numeric_conversion module
boost-optional:arm64-osx                          1.81.0              Boost optional module
boost-parameter:arm64-osx                         1.81.0              Boost parameter module
boost-phoenix:arm64-osx                           1.81.0              Boost phoenix module
boost-polygon:arm64-osx                           1.81.0              Boost polygon module
boost-pool:arm64-osx                              1.81.0              Boost pool module
boost-predef:arm64-osx                            1.81.0              Boost predef module
boost-preprocessor:arm64-osx                      1.81.0              Boost preprocessor module
boost-property-map:arm64-osx                      1.81.0              Boost property_map module
boost-property-tree:arm64-osx                     1.81.0              Boost property_tree module
boost-proto:arm64-osx                             1.81.0              Boost proto module
boost-qvm:arm64-osx                               1.81.0              Boost qvm module
boost-random:arm64-osx                            1.81.0              Boost random module
boost-range:arm64-osx                             1.81.0              Boost range module
boost-ratio:arm64-osx                             1.81.0              Boost ratio module
boost-rational:arm64-osx                          1.81.0              Boost rational module
boost-regex:arm64-osx                             1.81.0              Boost regex module
boost-serialization:arm64-osx                     1.81.0              Boost serialization module
boost-smart-ptr:arm64-osx                         1.81.0              Boost smart_ptr module
boost-spirit:arm64-osx                            1.81.0              Boost spirit module
boost-static-assert:arm64-osx                     1.81.0              Boost static_assert module
boost-system:arm64-osx                            1.81.0              Boost system module
boost-thread:arm64-osx                            1.81.0              Boost thread module
boost-throw-exception:arm64-osx                   1.81.0              Boost throw_exception module
boost-tokenizer:arm64-osx                         1.81.0              Boost tokenizer module
boost-tti:arm64-osx                               1.81.0              Boost tti module
boost-tuple:arm64-osx                             1.81.0              Boost tuple module
boost-type-index:arm64-osx                        1.81.0              Boost type_index module
boost-type-traits:arm64-osx                       1.81.0              Boost type_traits module
boost-typeof:arm64-osx                            1.81.0              Boost typeof module
boost-uninstall:arm64-osx                         1.81.0              Internal vcpkg port used to uninstall Boost
boost-unordered:arm64-osx                         1.81.0              Boost unordered module
boost-utility:arm64-osx                           1.81.0              Boost utility module
boost-variant2:arm64-osx                          1.81.0              Boost variant2 module
boost-variant:arm64-osx                           1.81.0              Boost variant module
boost-vcpkg-helpers:arm64-osx                     1.81.0#1            Internal vcpkg port used to modularize Boost
boost-winapi:arm64-osx                            1.81.0              Boost winapi module
boost-xpressive:arm64-osx                         1.81.0              Boost xpressive module
vcpkg-cmake-config:arm64-osx                      2022-02-06#1        
vcpkg-cmake-get-vars:arm64-osx                    2022-12-16          
vcpkg-cmake:arm64-osx                             2022-12-22          
zlib:arm64-osx                                    1.2.13              A compression library

**Comment by MonicaLiu0311** [comment]
> This is so strange. I update vcpkg package latest, but icu version is still 72.1.

You have updated successfully, because icu changed from `72.1` to `72.1#1` in your latest comment.

```
Computing installation plan...
The following packages will be built and installed:
  * icu[core,tools]:arm64-osx -> 72.1#1
```

**Comment by baijiu1** [comment]
> > This is so strange. I update vcpkg package latest, but icu version is still 72.1.
> 
> You have updated successfully, because icu changed from `72.1` to `72.1#1` in your latest comment.
> 
> ```
> Computing installation plan...
> The following packages will be built and installed:
>   * icu[core,tools]:arm64-osx -> 72.1#1
> ```

sorry, I see this.
but still have error at icu component：
```shell
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /bin/bash -c "V=1 ./../src/c-72_1-src-507f6288e7.clean/source/configure --host=aarch64-apple-darwin \"--disable-samples\" \"--disable-tests\" \"--disable-layoutex\" \"--enable-tools\" \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"--enable-debug\" \"--disable-release\" \"--prefix=/Users/haruhi/ClionProjects/vcpkg/installed/arm64-osx/debug\" \"--bindir=\\${prefix}/../tools/icu/debug/bin\" \"--sbindir=\\${prefix}/../tools/icu/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/icu\""
    Working Directory: /Users/haruhi/ClionProjects/vcpkg/buildtrees/icu/arm64-osx-dbg
    Error code: 1
    See logs for more information:
      /Users/haruhi/ClionProjects/vcpkg/buildtrees/icu/config-arm64-osx-dbg-config.log
      /Users/haruhi/ClionProjects/vcpkg/buildtrees/icu/config-arm64-osx-dbg-out.log
      /Users/haruhi/ClionProjects/vcpkg/buildtrees/icu/config-arm64-osx-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:811 (vcpkg_execute_required_process)
  ports/icu/portfile.cmake:55 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)
```

**Comment by baijiu1** [comment]
> > This is so strange. I update vcpkg package latest, but icu version is still 72.1.
> 
> You have updated successfully, because icu changed from `72.1` to `72.1#1` in your latest comment.
> 
> ```
> Computing installation plan...
> The following packages will be built and installed:
>   * icu[core,tools]:arm64-osx -> 72.1#1
> ```

thank you!
I not install autoconf and autoconf-archive two soft.
