### ISSUE TITLE
[leptonica] update to 1.83.0

### ISSUE THREAD

**Issue by phoeniiix1203** [microsoft/vcpkg#29142]
Library name:[leptonica](https://github.com/DanBloomberg/leptonica)

New version number:1.83.0

Other information that may be useful (release notes, etc...)
[Fix jp2k header reader for header offset larger than assumed 44 bytes](https://github.com/DanBloomberg/leptonica/commit/a7bf5cc893637bb273534e260befc73727ba55c4)

**Comment by LilyWangLL** [comment]
This issue has been fixed by PR https://github.com/microsoft/vcpkg/pull/29266, please update your vcpkg and build new version of `leptonica`.
