### ISSUE TITLE
Unable to download qt:x86-windows-static

### ISSUE THREAD

**Issue by doctashay** [microsoft/vcpkg#29143]
**Describe the bug**
When attempting to install qt through vcpkg, I get a 404 not found error from the automatically selected download mirror.

**Environment**
- OS: Windows 11
- Compiler: MSVC++ 14.30 _MSC_VER == 1932 (Visual Studio 2022 version 17.2.2)

**To Reproduce**
1. ./vcpkg install qt:x86-windows-static
2. See error

**Expected behavior**
qt:x86-windows-static would complete with no error

**Failure logs**
[debug.log](https://github.com/microsoft/vcpkg/files/10486529/debug.log)

**Additional context**
First time attempting to use vcpkg to install Qt, not sure if I'm doing something wrong here.

**Comment by dg0yt** [comment]
Update your vcpkg repo. (git pull, bootstrap-vcpkg).

**Comment by doctashay** [comment]
I appreciate your knowledge and swift response!
