### ISSUE TITLE
error: building boost-filesystem:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Zerefs** [microsoft/vcpkg#29147]
**Host Environment**

- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**

`./vcpkg install xxxx`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JonLiu1993** [comment]
@Zerefs, Thanks for posting this issue, could you please provide the error log?

**Comment by Zerefs** [comment]
ah I have removed the vpckg and I reinstalled it and the problem is solved
