### ISSUE TITLE
[libvpx] Build error

### ISSUE THREAD

**Issue by sany1231** [microsoft/vcpkg#29166]
Hello, i am trying to install libvpx for arm-v7a arch but no luck, can someone halps me ? thx.
FYI: When i try to install other packages like libyum or opus with :arm-android it is successfully installed.

Package: libvpx[core]:arm-android -> 1.12.0

**Host Environment**

- Host: x64-linux
- Compiler: Clang 11.0.5
-    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: 136ad069f 2023-01-24 (25 hours ago)

**To Reproduce**

`vcpkg install libvpx:arm-android`

**Failure logs**

```
-- Using cached webmproject-libvpx-v1.12.0.tar.gz.
-- Cleaning sources at /home/ubuntu/vcpkg/buildtrees/libvpx/src/v1.12.0-2729413caf.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/ubuntu/vcpkg/downloads/webmproject-libvpx-v1.12.0.tar.gz
-- Applying patch 0002-Fix-nasm-debug-format-flag.patch
-- Applying patch 0003-add-uwp-v142-and-v143-support.patch
-- Applying patch 0004-remove-library-suffixes.patch
-- Using source at /home/ubuntu/vcpkg/buildtrees/libvpx/src/v1.12.0-2729413caf.clean
CMake Error at ports/libvpx/portfile.cmake:182 (message):
  libvpx does not support architecture arm
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)



```

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
