### ISSUE TITLE
Wrong path on Microsoft Visual Studio Tools for LLVM

### ISSUE THREAD

**Issue by pedroVRVIU** [microsoft/vcpkg#29163]
**Describe the bug**
I am using vcpkg (tag: 2023.01.09) 's toolchain file, which I noticed it has a different path for the compiler ("CXX": "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/Llvm/x64/bin/clang-cl.exe") than my current setup ("C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\bin\clang-cl.exe") - this might be due to Visual Studio Installer's latest update.

**Comment by Cheney-W** [comment]
When installing LLVM through Visual Studio Installer, Visual Studio Installer provides two versions of clang-cl, one is x86 and the other is x64. This situation has existed for a long time, and it is not the latest update.

> I am using vcpkg (tag: 2023.01.09) 's toolchain file

Which file is the toolchain file you mentioned above?

**Comment by pedroVRVIU** [comment]
Thank you for your clarification. You are right. Somehow, VS Code with CMake Tools is failing to use the `clang-cl` and is reverting to just `cl` so I thought it might be the path.
