### ISSUE TITLE
[Zlib] Building zlib error [BUILD_FAILED]

### ISSUE THREAD

**Issue by hharryz** [microsoft/vcpkg#29189]
OS : Mac
I'm trying to install vcpkg but with no luck.
it turned out that I can not install zilb successfully .
here is my failure log but I can not understand the error at all.

```
-- Installing: /Users/harryz/cs106L/cs106L-assignment1/vcpkg/packages/zlib_arm64-osx/share/zlib/vcpkg-cmake-wrapper.cmake
-- Fixing pkgconfig file: /Users/harryz/cs106L/cs106L-assignment1/vcpkg/packages/zlib_arm64-osx/lib/pkgconfig/zlib.pc
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:135 (message):
  /path/to/pkg-config --exists zlib failed with error code: No such file or
  directory

      ENV{PKG_CONFIG_PATH}: "/Users/harryz/cs106L/cs106L-assignment1/vcpkg/packages/zlib_arm64-osx/lib/pkgconfig:/Users/harryz/cs106L/cs106L-assignment1/vcpkg/packages/zlib_arm64-osx/share/pkgconfig:/Users/harryz/cs106L/cs106L-assignment1/vcpkg/installed/arm64-osx/lib/pkgconfig:/Users/harryz/cs106L/cs106L-assignment1/vcpkg/installed/arm64-osx/share/pkgconfig"
      output: 
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:200 (z_vcpkg_fixup_pkgconfig_check_files)
  ports/zlib/portfile.cmake:43 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:147 (include)


error: building zlib:arm64-osx failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+zlib
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[zlib]+Build+error
Include '[zlib] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 4efb7ed62 2023-01-25 (10 hours ago)


Please use the prefilled template from /Users/harryz/cs106L/cs106L-assignment1/vcpkg/installed/vcpkg/issue_body.md when reporting your issue.
```

It will be really appreciated if anyone can help me with the problem.

**Comment by keithglassford** [comment]
Having the same issue ... tried anything I could find on SO and gitHub. Any help would be greatly appreciated ... following is the issue md:

Package: zlib[core]:arm64-osx -> 1.2.13

**Host Environment**

- Host: arm64-osx
- Compiler: AppleClang 14.0.0.14000029
-    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 36fb23307 2023-02-10 (24 hours ago)

**To Reproduce**

`vcpkg install zlib`

**Failure logs**

```
-- Using cached madler-zlib-v1.2.13.tar.gz.
-- Extracting source /Users/keithmglassford/Development/vcpkg/downloads/madler-zlib-v1.2.13.tar.gz
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch 0002-skip-building-examples.patch
-- Applying patch 0003-build-static-or-shared-not-both.patch
-- Applying patch 0004-android-and-mingw-fixes.patch
-- Using source at /Users/keithmglassford/Development/vcpkg/buildtrees/zlib/src/v1.2.13-f30d2a168d.clean
-- Configuring arm64-osx
-- Building arm64-osx-dbg
-- Building arm64-osx-rel
-- Installing: /Users/keithmglassford/Development/vcpkg/packages/zlib_arm64-osx/share/zlib/vcpkg-cmake-wrapper.cmake
-- Fixing pkgconfig file: /Users/keithmglassford/Development/vcpkg/packages/zlib_arm64-osx/lib/pkgconfig/zlib.pc
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:617 (message):
  Could not find pkg-config.  Please install it via your package manager:

      brew install pkg-config
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:197 (vcpkg_find_acquire_program)
  ports/zlib/portfile.cmake:43 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:147 (include)



```


**Additional context**

**Comment by hharryz** [comment]
您好，您发送的邮件我已收到，谢谢！    I have received your e-mail,thank you!                                                                  ——Harry张

**Comment by zero-g-x** [comment]
> brew install pkg-config

install pkg-config,then it can work

**Comment by Maboulmagd** [comment]
Having same issue but with ```openal-soft_arm64-osx``` on my new M2 MBP. Trying to install SFML with Vcpkg manifest file, but I get the same error, even after installing pkg-config with brew.

**Comment by keithglassford** [comment]
Ok, figured it out ... I had already installed pkg-config using brew as the directions said, but still got the same problem. This led me to think that it was a path issue. Given that for the new M1 MacBook, brew moved the install location and so this could be the issue as I had migrated my disk from an Intel based system and the path could be pointing to the wrong version. I poked around the zlib install scripts and found that it can take an environment variable for pkg-config.

In addition, using a locate pkg-config revealed that there were multiple versions across the system from various installs and so I chose to first update the env to verify:

$ export PKG_CONFIG=/opt/homebrew/Cellar/pkg-config/... 

where ... is my local version and remainder of the path to the bin, and then ran the install:

$ vcpkg install zlib

and it compiled successfully. As such, it appears that either zlib hasn't been updated to look in the new homebrew location or my path was all messed up and the install was looking in the wrong place. Either way, I cleaned up my path, rebooted for fun, and all works now as before. 

Hope this helps someone else with the same issue ...

**Comment by pateruu** [comment]
@keithglassford  Hey I believe I have the same issue as you, and was wondering how you were able to fix your path so it worked properly.

**Comment by keithglassford** [comment]
@pateruu I just added the following line to my ~/.bash_profile

export PKG_CONFIG=/opt/homebrew/Cellar/pkg-config/0.29.2_3/bin/pkg-config

where you can find you actual version and associated path to put in the above using:

$ locate pkg-config

and then finding the correct version; just remember to either open a new shell or do a 

$ source ~/.bash_profile

As for the path, just examine your current path using:

$ echo $PATH

to see if there is any changes that you need to do in terms of ordering in you ~/.bashrc or ~/.bash_profile if you are setting any $PATH variables there.

... also, this depends up on you shell and environment as I am working on a Mac with the old bash shell.

**Comment by MangoLeFroot** [comment]
I am getting the same error when trying to build for windows, anyone know a fix for it?
Package is: zlib:x64-windows
