### ISSUE TITLE
[monkeys-audio] update to 9.04

### ISSUE THREAD

**Issue by vividos** [microsoft/vcpkg#29187]
Library name: monkeys-audio

New version number: 9.04

The port is still on the version 5.70

**Comment by vividos** [comment]
@JavierMatosD Thanks for the update. I just tried it out, and it seems the port still may download version 6.07. When I check the output folder, in `include\monkeys-audio\Version.h` it still has this version.

I think this change is not correct:
[ports/monkeys-audio/portfile.cmake](https://github.com/microsoft/vcpkg/pull/29556/files#diff-a5b7cdccb97431e45bf633d8dca4be8dbccb462580f3c6cb770e4a564e09413c)
the second `URLS` link points to version 6.07.

Also, for dynamic linking with MACDll.dll, the neader MACDll.h is missing, which is needed to get all exported functions. The header should be installed.

**Comment by dg0yt** [comment]
> the second `URLS` link points to version 6.07.

Indeed. However, I wonder if https://web.archive.org should be used as a mirror at all. What I find at https://archive.org/about/terms.php is:
> Access to the Archive’s Collections is provided at no cost to you and is granted for scholarship and research purposes only.
