### ISSUE TITLE
Error: Building package curl:x86-windows-static failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by zhgfly01** [Microsoft/vcpkg#2918]
Package: curl:x86-windows-static
Vcpkg version: 0.0.105-unknownhash

\vcpkg\buildtrees\curl\install-x86-windows-static-dbg-out.log

FAILED: lib/CMakeFiles/libcurl.dir/libcurl.rc.res
cl: 命令行 warning D9035 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000

**Comment by ReyzalX** [comment]
Install English language pack for visual studio.
same as #2895

**Comment by zhgfly01** [comment]
@ReyzalX thanks
