### ISSUE TITLE
error: building openblas:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by L4c79y** [microsoft/vcpkg#29197]
- OS: Windows 11
- Compiler: vcpkg package management program version 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75

**To Reproduce**

`vcpkg install gazebo:x64-windows`

![image](https://user-images.githubusercontent.com/115720193/214828390-c0adcdc5-88c6-43ab-ab3c-3a3fdf24a58f.png)
[issue_body.md](https://github.com/microsoft/vcpkg/files/10508886/issue_body.md)

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Do you install any Firewall or anti-virus software on your machine? This issue looks like antivirus interference.

**Comment by Adela0814** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
