### ISSUE TITLE
atk:x86-windows-static failed with : BUILD_FAILED

### ISSUE THREAD

**Issue by mathieusr** [Microsoft/vcpkg#2919]
Dear,

I met a problem when I want to install GTK.

The installation failed when it trying to install atk
![image](https://user-images.githubusercontent.com/29339406/36838460-7df7457c-1d3f-11e8-9d41-9e37c7e853f6.png)

I did all the recommandations, and try on another PC and same error.

Below the log file:
[install-x86-windows-static-dbg-out.log](https://github.com/Microsoft/vcpkg/files/1770656/install-x86-windows-static-dbg-out.log)

I have cmake 3.10.2 X86 and git installed

Many thanks for your help

**Comment by glachancecmaisonneuve** [comment]
I can repro in a clean tree with x86-windows-static or x64-windows-static or .  Some more information if someone is working on this:

- atk_marshal_VOID__STRING_BOOLEAN and others are declared in a generated atkobject.h file before the rest of the build happens.
- the utility used to generate atkobject comes from glib, it's called glib-genmarshal
- [the relevant code in the port's CMakeLists is here.](https://github.com/Microsoft/vcpkg/blob/d739a2aa7f4f2a05d923f8122d9c8736474af35a/ports/atk/CMakeLists.txt#L12-L24)

**Comment by ras0219-msft** [comment]
After investigating further, it looks like static builds are actually broken at a more fundamental level; glib's generator tools don't generate headers when built in static mode! Additionally, they both use `DllMain()` so they weren't even being built as static libraries anyway.

I've disabled both of these libraries when static linking to account for this; please use the DLL triplets if you'd like to use glib/atk.


Additionall, as @glachancecmaisonneuve

**Comment by mathieusr** [comment]
Thanks for your answser,

I tried to install atk in dynamic but I met an error with gettext

![image](https://user-images.githubusercontent.com/29339406/37002904-7cd98332-20cb-11e8-8d00-989789082f56.png)

Below the log file.
[install-x86-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/1782822/install-x86-windows-dbg-out.log)

Many thanks for your help

**Comment by webfolderio** [comment]
The problem still exist, i can not build the atk project.

**Comment by JackBoosY** [comment]
Hi @mathieusr , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
