### ISSUE TITLE
COFFFileReader::read_lib() fails on poorly generated yet correct .lib files

### ISSUE THREAD

**Issue by jjcamp** [Microsoft/vcpkg#292]
*By correct, I mean that they can be used without error.  The PE spec doesn't seem to cover this case.*

Synopsis
---
The `COFFFileReader::read_lib()` function currently reads the number of [archive] members from the second linker data member.  It then uses that number to loop through the remaining archive members and verify their headers.

However, it is apparently possible for some of those member to have offsets which point to 0.  When this happens, **vcpkg** will continue reading the `std::fstream` past EOF, and will end up calling exiting when `COFFFileReader::verify_equal_strings()` fails.

Example
---
When installing  `pdcurses:x86-windows`, vcpkg fails with error:
```
Incorrect string (LIB HEADER_END) found. Expected: `\n but found 
```
This is because the second archive member claims there are 479 members, and there are in fact 479 member *offsets*.  This is the end of dumpbin's member offset table:
```
      1D1    133F6
      1D2    14224
      1D3    142F0
      1D4        0
      1D5        0
      1D6        0
      1D7        0
      1D8        0
      1D9        0
      1DA        0
      1DB        0
      1DC        0
      1DD        0
      1DE        0
      1DF        0
```
This makes it so that the second linker member data section is technically correct, but there are actually only 467 remaining archive members.

Reproduced on two similar 64-bit Windows 10 Anniversity Update machines, each with VS2015 update 3.

Possible Fixes
---
- Use the second linker member's offset table to iterate over the archive members (difficult because it would require moving backwards in the file stream)
- Use the second linker member's offset table to count the number of archive members without an offset of 0.
- Check for `ios::eofbit` when reading the file stream.
- Patch link.exe (if this is undesirable behavior)

**Comment by GeertVL** [comment]
I fixed this in PR #288 where I check if there is actually a header. It is a quickfix but your possible fixes could do the trick. 
I will try your suggestions and PR if I come up with a better fix.

**Comment by jjcamp** [comment]
Figures there's a fix while I'm debugging.  I merged the latest master into my fork and this does fix my issue.

Your fix is pretty close to checking for the EOF, however I would suggest checking the eof bit after reading inside of `read()`, something like:
```c++
if (fs.eof() && ret.data[0] == '\0')
    return ret;
```
This would prevent members with incorrect data sizes from passing (they shouldn't).

And then in read_lib() after read():
```c++
if (fs.eof())
    break;
```
This way it doesn't try to read multiple empty headers.

**Comment by alexkaratarakis** [comment]
>Use the second linker member's offset table to iterate over the archive members (difficult because it would require moving backwards in the file stream)

I am not sure what you mean by moving backwards.
We could read the offset table and keep it in memory, sort it (although it *should* be sorted already), then remove the zeros. Then, we can use it to do the checks.

**Comment by jjcamp** [comment]
> I am not sure what you mean by moving backwards.
We could read the offset table and keep it in memory, sort it (although it should be sorted already), then remove the zeros. Then, we can use it to do the checks.

For some reason I didn't think of sorting the table, but in my example the the offsets were only *mostly* sorted, the following was common:
```
       B1    10338
       B2    10402
       B3    1039C
```
But yeah, reading the table, sorting it, and using that is likely the most reliable and long-term solution.

**Comment by alexkaratarakis** [comment]
Current implementation:
-Reads the offset table and stores them, ignoring those that point to 0
-Sorts them just in case. It wouldn't be wrong anyway, it would just move back and forth in the file stream.
-Use these offsets to go through the archive members and do the appropriate checks.

Also did a bit of refactoring in the file to improve clarity.
