### ISSUE TITLE
[harfbuzz] Build error

### ISSUE THREAD

**Issue by ZSWyummy** [microsoft/vcpkg#29211]
**Host Environment**

- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**

`./vcpkg install xxxx`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
<pre>(base) root@yummy-Lenovo-Legion-R9000P2021:/home/yummy# vcpkg install opencv3
Computing installation plan...
The following packages will be built and installed:
  * gtk[core]:x64-linux -&gt; 4.6.8#1
  * harfbuzz[core]:x64-linux -&gt; 6.0.0
  * libsass[core]:x64-linux -&gt; 3.6.5#1
  * libwebp[core,libwebpmux,nearlossless,simd]:x64-linux -&gt; 1.2.4#1
    opencv3[core,default-features,dnn,flann,gtk,jpeg,png,quirc,tiff,webp]:x64-linux -&gt; 3.4.18#6
  * pango[core]:x64-linux -&gt; 1.50.12#2
  * protobuf[core]:x64-linux -&gt; 3.21.12
  * quirc[core]:x64-linux -&gt; 1.1#3
  * sassc[core]:x64-linux -&gt; 3.6.2
  * vcpkg-get-python-packages[core]:x64-linux -&gt; 2022-06-30
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Restored 0 package(s) from /root/.cache/vcpkg/archives in 12.78 us. Use --debug to see more details.
Installing 1/10 harfbuzz:x64-linux...
Building harfbuzz[core]:x64-linux...
-- Downloading https://github.com/harfbuzz/harfbuzz/archive/6.0.0.tar.gz -&gt; harfbuzz-harfbuzz-6.0.0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag &apos;binarycaching&apos; unset
[DEBUG] Feature flag &apos;compilertracking&apos; unset
[DEBUG] Feature flag &apos;registries&apos; unset
[DEBUG] Feature flag &apos;versions&apos; unset
[DEBUG] 1000: popen( curl --fail -L https://github.com/harfbuzz/harfbuzz/archive/6.0.0.tar.gz --create-dirs --output /opt/VcpkgGit/vcpkg/downloads/harfbuzz-harfbuzz-6.0.0.tar.gz.148423.part 2&gt;&amp;1)
[DEBUG] 1000: cmd_execute_and_stream_data() returned 28 after 130973062 us
error: Failed to download from mirror set
error: https://github.com/harfbuzz/harfbuzz/archive/6.0.0.tar.gz: curl failed to download with exit code 28
[DEBUG] /mnt/vss/_work/1/s/src/vcpkg/base/downloads.cpp(956): 
[DEBUG] Time in subprocesses: 130973062 us
[DEBUG] Time in parsing JSON: 6 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 97 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 2.183 min (130973475 us)
</pre>
<pre>CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. Your proxy&apos;s remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:273 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/harfbuzz/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:147 (include)

</pre>
- Attach ***every failure log file*** mentioned in the console output.
<pre><font color="#F66151">error: building harfbuzz:x64-linux failed with: BUILD_FAILED</font>
<font color="#F66151">error: Please ensure you&apos;re using the latest port files with `git pull` and `vcpkg update`.</font>
<font color="#F66151">Then check for known issues at:</font>
<font color="#F66151">    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+harfbuzz</font>
<font color="#F66151">You can submit a new issue at:</font>
<font color="#F66151">    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&amp;title=[harfbuzz]+Build+error</font>
<font color="#F66151">Include &apos;[harfbuzz] Build error&apos; in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.</font>
<font color="#F66151">    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75</font>
<font color="#F66151">    vcpkg-scripts version: cdbcc0321 2023-01-26 (3 小时前)</font>

<font color="#E9AD0C">Please use the prefilled template from /opt/VcpkgGit/vcpkg/installed/vcpkg/issue_body.md when reporting your issue.</font>
</pre>

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JonLiu1993** [comment]
@public469, Thanks for posting this issue, could you please try to download https://github.com/harfbuzz/harfbuzz/archive/6.0.0.tar.gz manually and put the archive file into downloads folder, then rebuild this?
Please use proxy to download those files.

**Comment by Cheney-W** [comment]
Close this issue because it's a network issue.
