### ISSUE TITLE
[New Port Request] h265nal

### ISSUE THREAD

**Issue by amansinghsneha** [microsoft/vcpkg#29221]
Library name: h265nal

Library description: A Library and Tool to parse H265 NAL units

Source repository URL: https://github.com/chemag/h265nal

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
