### ISSUE TITLE
CMake Error when install liblzma with msvc + windows

### ISSUE THREAD

**Issue by PhoebeHui** [Microsoft/vcpkg#2922]
Failed to install liblzma with msvc + windows, this issue found when try to build Folly.

D:\Folly\vcpkg\src>vcpkg install liblzma:x64-windows
The following packages will be built and installed:
    liblzma[core]:x64-windows
Starting package 1/1: liblzma:x64-windows
Building package liblzma[core]:x64-windows...
-- CURRENT_INSTALLED_DIR=D:/Folly/vcpkg/src/installed/x64-windows
-- DOWNLOADS=D:/Folly/vcpkg/src/downloads
-- CURRENT_PACKAGES_DIR=D:/Folly/vcpkg/src/packages/liblzma_x64-windows
-- CURRENT_BUILDTREES_DIR=D:/Folly/vcpkg/src/buildtrees/liblzma
-- CURRENT_PORT_DIR=D:/Folly/vcpkg/src/ports/liblzma/.
-- Downloading http://tukaani.org/xz/xz-5.2.3.tar.gz...
-- Downloading http://tukaani.org/xz/xz-5.2.3.tar.gz... Failed. Status: 22;"HTTP response code said error"
CMake Error at D:/Folly/vcpkg/src/scripts/cmake/vcpkg_download_distfile.cmake:124 (message):

      Failed to download file.
      Add mirrors or submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  D:/Folly/vcpkg/src/ports/liblzma/portfile.cmake:7 (vcpkg_download_distfile)
  D:/Folly/vcpkg/src/scripts/ports.cmake:72 (include)

Error: Building package liblzma:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: liblzma:x64-windows
  Vcpkg version: 0.0.105

Additionally, attach any relevant sections from the log files above.

**Comment by ReyzalX** [comment]
It seems that vcpkg can't download file from `http://tukaani.org/xz/xz-5.2.3.tar.gz`.
you can can manually download from `http://tukaani.org/xz/xz-5.2.3.tar.gz`.
Then move `xz-5.2.3.tar.gz` file to `vcpkg\downloads`.
after do this.
try to run `vcpkg.exe install liblzma` again.
you will see something like `Using cached /vcpkg/downloads/xz-5.2.3.tar.gz` if configure right...
I am also a novice of vcpkg. I hope It will help you.

>PS D:\Code\vcpkg> .\vcpkg.exe install liblzma
The following packages will be built and installed:
    liblzma[core]:x86-windows
Starting package 1/1: liblzma:x86-windows
Building package liblzma[core]:x86-windows...
-- CURRENT_INSTALLED_DIR=D:/Code/vcpkg/installed/x86-windows
-- DOWNLOADS=D:/Code/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/Code/vcpkg/packages/liblzma_x86-windows
-- CURRENT_BUILDTREES_DIR=D:/Code/vcpkg/buildtrees/liblzma
-- CURRENT_PORT_DIR=D:/Code/vcpkg/ports/liblzma/.
-- Using cached D:/Code/vcpkg/downloads/xz-5.2.3.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting source D:/Code/vcpkg/downloads/xz-5.2.3.tar.gz
-- Extracting done
-- Configuring x86-windows
-- Configuring x86-windows done
-- Build x86-windows-dbg
-- Build x86-windows-dbg done
-- Build x86-windows-rel
-- Build x86-windows-rel done
-- Performing post-build validation
-- Performing post-build validation done
Building package liblzma[core]:x86-windows... done
Installing package liblzma[core]:x86-windows...
Installing package liblzma[core]:x86-windows... done
Elapsed time for package liblzma:x86-windows: 30.59 s
Total elapsed time: 30.59 s
The package liblzma is compatible with built-in CMake targets:
    find_package(LibLZMA REQUIRED)
    target_include_directories(main PRIVATE ${LIBLZMA_INCLUDE_DIRS})
    target_link_libraries(main PRIVATE ${LIBLZMA_LIBRARIES})

**Comment by ras0219-msft** [comment]
I've switched the download to use the xz-mirror/xz repo, which should help with these issues!
