### ISSUE TITLE
[boost] building a DLL or EXE causes boost library exports to be added to the final DLL or EXE

### ISSUE THREAD

**Issue by danyhm** [microsoft/vcpkg#29233]
Package: boost:serialization -> 1.81.0

**Environment**
- OS: x64 Windows 10 VS 2019 16.11.23
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30147 for x86
 vcpkg-tool version:2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9

**To Reproduce**
1. ./vcpkg install boost:x86-windows
2. create any Dynamic DLL library and use any boost header (i use serialization library here)
3. Finall DLL contains exports from boost library which is not desirable.

**Expected behavior**
program DLL should only contain exports from the exports.def file

**Comment by danyhm** [comment]
@LilyWangLL 
the issue also appears in non-static library builds. please update the labels

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Sorry for the wrong label, I have removed it.
About this issue, I have some questions.
1. Is this issue appears in a dynamic project use static `boost`? Is it will appears with dynamic `boost`?
2. Is the exports.def file created by yourself? Could you please provide a simple project and a export.def file which can reproduce this issue?

**Comment by danyhm** [comment]
Hello,

Thanks for following up. 
1- The issue appears in both DLL and EXE applications and in both static and dynamic boost configurations.
I've attached a sample solution that includes both DLL and EXE examples

2- I've created the exports.def file using visual studio "Add new item"

I think this has something to do with how vcpkg builds boost libraries.

sample project:
[test_boost_export.zip](https://github.com/microsoft/vcpkg/files/10543784/test_boost_export.zip)

**Comment by LilyWangLL** [comment]
Thanks for your reply, I will test this project locally.

**Comment by danyhm** [comment]
did you get the time to reproduce the issue?

**Comment by LilyWangLL** [comment]
> did you get the time to reproduce the issue?

I will do in this week. 😀

**Comment by LilyWangLL** [comment]
Hi, @danyhm, do you mean the following `boost_serialization-vc143-mt-gd-x64-1_81.dll` file is copied to the Debug folder? If yes, this is by design, because your project use the function provided by `boost-serialization` header file.

![image](https://user-images.githubusercontent.com/94091114/218048649-ed1811d8-e94f-4f16-b489-d5c5704905dc.png)

And do you want what contents export by the `exports.def` file? I saw your `exports.def` just have a function `save_a`, but I can't found this function in `test_boost_export.lib` which created by `test_boost_export` project. Maybe I misunderstood the role of `exports.def`.

**Comment by danyhm** [comment]
Hey @LilyWangLL 
Thanks for taking the time.
no that's not what I meant. I'm saying that the boost library exports are somehow added to the final DLL or EXE.
if you run `dumpbin /exports test_boost_export_dll.dll` from a visual studio command line you'll see the following

![image](https://user-images.githubusercontent.com/21024667/218119873-3c1299a2-8928-4a6d-ac0e-3156e24d62e4.png)
![image](https://user-images.githubusercontent.com/21024667/218119960-592bb47a-9c08-4c33-b459-4dca535e11c2.png)

whereas I only defined `save_a` to be exported in the def file! why are all the other exports being added?
somehow the linker is also adding the boost library exports to the final PE as well.
