### ISSUE TITLE
Error Building package asio x86 windows

### ISSUE THREAD

**Issue by lsalamon** [Microsoft/vcpkg#2923]
<b>A)</b>
C:\Library\VcPkg>vcpkg.exe install asio
The following packages will be built and installed:
    asio[core]:x86-windows
Starting package 1/1: asio:x86-windows
Building package asio[core]:x86-windows...
A suitable version of git was not found (required v2.16.2). Downloading portable git v2.16.2...
Fetching git version 2.16.2 (No sufficient installed version was found)
Could not run:
    'C:/Library/VcPkg/scripts/fetchtool.ps1'
Error message was:
    Extracting git...
Move-Item : 
<b>Access to path 'C: \ Library \ VcPkg \ downloads \ partially-extracted' was denied.</b>
No C:\Library\VcPkg\scripts\VcpkgPowershellUtils.ps1:206 caractere:9
         Move-Item -Path "$destinationPartial" -Destination $output
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : WriteError: (C:\Library\VcPk...ially-extracted:DirectoryInfo) [Move-Item], IOException
     FullyQualifiedErrorId : MoveDirectoryItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand

Extracting git has completed successfully.
Could not detect or download git
No C:\Library\VcPkg\scripts\fetchtool.ps1:67 caractere:9
         throw ("Could not detect or download " + $tool)
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : OperationStopped: (Could not detect or download git:String) [], RuntimeException
     FullyQualifiedErrorId : Could not detect or download git

<b>THIS ISSUE I SOLVE EXTRACTING PACKAGE 'MinGit-2.16.2-32-bit.zip' MANUALLY</b>

<b>B)</b>
C:\Library\VcPkg>vcpkg.exe install asio
The following packages will be built and installed:
    asio[core]:x86-windows
Starting package 1/1: asio:x86-windows
Building package asio[core]:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/Library/VcPkg/installed/x86-windows
-- DOWNLOADS=C:/Library/VcPkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Library/VcPkg/packages/asio_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/Library/VcPkg/buildtrees/asio
-- CURRENT_PORT_DIR=C:/Library/VcPkg/ports/asio/.
-- Downloading https://github.com/chriskohlhoff/asio/archive/asio-1-10-8.tar.gz...
-- Downloading https://github.com/chriskohlhoff/asio/archive/asio-1-10-8.tar.gz... Failed. Status: 7;"Couldn't connect to server"
CMake Error at C:/Library/VcPkg/scripts/cmake/vcpkg_download_distfile.cmake:124 (message):

      Failed to download file.
      Add mirrors or submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  C:/Library/VcPkg/scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  C:/Library/VcPkg/ports/asio/portfile.cmake:4 (vcpkg_from_github)
  C:/Library/VcPkg/scripts/ports.cmake:72 (include)

Error: Building package asio:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: asio:x86-windows
  Vcpkg version: 0.0.105-unknownhash

**Comment by cmpute** [comment]
Have you tried to download it again?

**Comment by lsalamon** [comment]
Today at my home it works.
Thanks.

**Comment by lsalamon** [comment]
No way. At my work via proxy do not download all. It does not matter if I create the http_proxy and https_proxy keys environment.
At browser all download work fine like:
https://github.com/boostorg/detail/archive/boost-1.66.0.tar.gz is downloaded at 
https://codeload.github.com/boostorg/detail/tar.gz/boost-1.66.0

**Comment by JackBoosY** [comment]
Hi @lsalamon ,  thanks for report this issue.

- The Question A shows you need permission to write file in disk. If you install vcpkg in C:\ , the system may prevent you from writing files to disk when you are not an administrator.

- The Question B shows your network maybe couldn't download source package. You can manually download this package and put it into C:\Library\VcPkg\downloads\, then rerun install command.

The latest version works fine yet.
Thx.
