### ISSUE TITLE
Prerequisites not clearly listed in Quick Start Guide

### ISSUE THREAD

**Issue by sivan-koren** [microsoft/vcpkg#29243]
### Discussed in https://github.com/microsoft/vcpkg/discussions/29237

<div type='discussions-op-text'>

<sup>Originally posted by **sivan-koren** January 28, 2023</sup>
Trying to use this with VS Code.
```
PS C:\Users\User\src\CAPITest> vcpkg install curl
Computing installation plan...
The following packages will be built and installed:
    curl[core,non-http,schannel,ssl,sspi]:x86-windows -> 7.87.0
  * vcpkg-cmake[core]:x64-windows -> 2022-12-22
  * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06#1
  * zlib[core]:x86-windows -> 1.2.13
Additional packages (*) will be modified to complete this operation.
error: in triplet x64-windows: Unable to find a valid Visual Studio instance
Could not locate a complete Visual Studio instance
The following paths were examined for Visual Studio instances:
    C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary/Build\vcvarsall.bat
```
Note that VS 2022 Community is installed with all defaults and English language pack. The above path is in fact not valid, there is no VC folder in actuality.

Side note, I don't use Visual Studio.

VS Code is using the Microsoft C/C++ extension which debugs with GDB/LLDB, it seems.

How can I get vcpkg to work with VS Code?</div>

---------------------------------------

I've resolved the above by adding "Desktop Development with C++" from the Visual Studio installer, but I'm converting this to an issue because this is notably missing from the Quick Start guide which lists only Visual Studio. A default Visual Studio installation doesn't include the Desktop Development with C++ packages unless the user selects them. Without any indication that we should, this was frustrating.

Also, the intention when using VS Code is to avoid a bulky IDE, so it would make a lot of sense to clearly list which specific components from the Visual Studio or Build Tools for Visual Studio installers are required for vcpkg (unless the whole C++ workload environment is required for C package management).

**Comment by sivan-koren** [comment]
Additional notes: the above only gets you beyond this error. I'm still not able to get VS Code to see the packages that vcpkg downloads even after modifying the settings.json as described.

It may simply be that a guide for setting up VS, VS Code, and vcpkg from scratch on Windows may be needed.

**Comment by Neumann-A** [comment]
If you want to compile something you need a compiler & toolchain to make it work. I don't think this needs explicit mentioning.

**Comment by sivan-koren** [comment]
I'm not sure what you mean. GCC is a compiler. More so, it's a compiler that VS Code's Microsoft C/C++ extension instructions recommend.
If vcpkg doesn't work with VS Code, why list it there?

**Comment by Neumann-A** [comment]
> If vcpkg doesn't work with VS Code, why list it there?

VS Code is an editor nothing more. It is not a compiler. 

In short, you need to provide the minimum to configure a cmake project. If you don't provide that vcpkg won't work. 
If you want to use GCC you are not going to use the `x64-windows` triplets and won't need the stuff installed by VS Installer at all.

**Comment by sivan-koren** [comment]
I think you've missed the issue. You should reread the OP.
1. VS Code is an editor by Microsoft
2. When users open a c file in VS Code it walks the user through installation of GCC via mingw.
3. At this point, the environment is functional for basic C development.
4. When you type include in a c file, it refers the user to vcpkg quick start guide. Note that we are still following a completely Microsoft guided recommendation to another Microsoft product.
5. When users follow the quick start guide, they then install Visual Studio (without the C/C++ add on).
6. Now the environment is no longer functional.
7. User will search around the docs to find what component is missing, what steps were missed, or search for issue reports on VS Code GitHub pages, vcpkg GitHub pages, etc.

Is it the goal to walk users through to create a functional development environment? If so, then Microsoft docs should be updated, either here, or on C/C++ VSCode extension, or elsewhere.

I believe that Microsoft's guided installations are not meant to guide users to a non-functional environment.

**Comment by sivan-koren** [comment]
Anyway, is there some reason that we shouldn't list dependencies?
I think software dependencies should be listed because users expect them to be. Among countless other reasons.

**Comment by Neumann-A** [comment]
> Now the environment is no longer functional.

The environment is still functional. The vcpkg guide is just simply written for VS and not Code. 
Switch your triplet to `x64-mingw-static` or `x64-mingw-dynamic`. 
Using mingw with vcpkg is already an advanced topic outside the responsibility of the quick guide. Especially since the mingw triplets are community triplets.
(of course somebody could add a section about it somewhere if coming from Code.)

**Comment by sivan-koren** [comment]
> The vcpkg guide is just simply written for VS and not Code.

Yes. Thank you. This is exactly the issue.

Microsoft VS Code C/C++ extension directs to the vcpkg Quick Start guide. If the Microsoft VCPKG team is not working in collaboration with the Microsoft VS Code C/C++ extension team, that's okay, but it's customary to tell them that.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.

**Comment by LilyWangLL** [comment]
> Microsoft VS Code C/C++ extension directs to the vcpkg Quick Start guide. If the Microsoft VCPKG team is not working in collaboration with the Microsoft VS Code C/C++ extension team, that's okay, but it's customary to tell them that.

We need to confirm this.
