### ISSUE TITLE
[folly] build failure

### ISSUE THREAD

**Issue by sunrongyi** [microsoft/vcpkg#29241]
**Host Environment**

- OS: [win11    10.0.22621]
- Compiler: revision

**To Reproduce**

`./vcpkg install folly:x64-windows`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- 
error: building folly:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+folly
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[folly]+Build+error
Include '[folly] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 91dd61bd4 2023-01-27 (35 hours ago)

- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Cheney-W** [comment]
Could you please provide the error log to us? Thank you!

**Comment by sunrongyi** [comment]
#> Could you please provide the error log to us? Thank you!
> where is the error log?

**Comment by Cheney-W** [comment]
All of the logs in `vcpkg\buildtrees\folly` folder.

**Comment by jimwang118** [comment]
This is the result of my installation
![image](https://user-images.githubusercontent.com/122244446/219253448-b6d91da2-be0d-4027-b444-69773ca90332.png)

ping [sunrongyi](https://github.com/sunrongyi)，You can try to reinstall，or could you please provide the error log to us? Thank you!

**Comment by sunrongyi** [comment]
> 
I compressed the folder
[folly.zip](https://github.com/microsoft/vcpkg/files/10752445/folly.zip)

**Comment by yudaichen** [comment]
I have the same problem

vcpkg.exe --version 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
```
config-x64-windows-out.log

CMake Error at CMake/FollyFunctions.cmake:95 (if):
  if given arguments:

    "E:/repository/c++/vcpkg/buildtrees/folly/src/183f5c2249-4b4661398b.clean/folly/Benchmark.cpp" "MATCHES" "^E:/repository/c++/vcpkg/buildtrees/folly/src/183f5c2249-4b4661398b.clean/folly/build/"

  Regular expression
  "^E:/repository/c++/vcpkg/buildtrees/folly/src/183f5c2249-4b4661398b.clean/folly/build/"
  cannot compile
Call Stack (most recent call first):
  CMakeLists.txt:163 (REMOVE_MATCHES_FROM_LISTS)
```
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/10939676/config-x64-windows-out.log)

**Comment by dg0yt** [comment]
~~~
"E:/repository/c++/...
~~~
Not a vcpkg bug.
Some buildscripts use unsanitized filepaths as regular expression. This results in the error.
Avoid directory names with special characters (`+`, ` `, non-latin1).

**Comment by Cheney-W** [comment]
Thanks for dg0yt's comment.
@sunrongyi   Could you please clone vcpkg to a new path or simply replace the folder name from c++ to cpp?
Thank you!

**Comment by Cheney-W** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
