### ISSUE TITLE
[New Port Request] boost-ext-mp

### ISSUE THREAD

**Issue by nofe1248** [microsoft/vcpkg#29269]
Library name: boost-ext-mp

Library description: C++ single header/single module C++20 Meta-Programming Library

Source repository URL: https://github.com/boost-ext/mp

Project homepage (if different from the source repository): https://boost-ext.github.io/mp/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): The boost-ext-mp library support using `import boost.mp` to import the library, it will be fantastic if the vcpkg can support the modules.

**Comment by JonLiu1993** [comment]
Fixing by PR #29975
