### ISSUE TITLE
[arduino-esp32-2-0-6] Build error

### ISSUE THREAD

**Issue by dickcummings** [microsoft/vcpkg#29265]
**Host Environment**

- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**

`./vcpkg install xxxx`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- 
C:\dev\vcpkg>vcpkg install arduino-esp32-2-0-6
Computing installation plan...
The following packages will be built and installed:
    arduino-esp32-2-0-6[core]:x86-windows -> 1.1.1
  * vcpkg-cmake[core]:x64-windows -> 2022-12-22
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
A suitable version of powershell-core was not found (required v7.2.8) Downloading portable powershell-core 7.2.8...
Downloading powershell-core...
https://github.com/PowerShell/PowerShell/releases/download/v7.2.8/PowerShell-7.2.8-win-x86.zip->C:\dev\vcpkg\downloads\PowerShell-7.2.8-win-x86.zip
Downloading https://github.com/PowerShell/PowerShell/releases/download/v7.2.8/PowerShell-7.2.8-win-x86.zip
Extracting powershell-core...
Detecting compiler hash for triplet x86-windows...
Restored 0 package(s) from C:\Users\dc\AppData\Local\vcpkg\archives in 193 us. Use --debug to see more details.
Installing 1/2 vcpkg-cmake:x64-windows...
Building vcpkg-cmake[core]:x64-windows...
-- Installing: C:/dev/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake
-- Installing: C:/dev/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake
-- Installing: C:/dev/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake
-- Installing: C:/dev/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg-port-config.cmake
-- Installing: C:/dev/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/copyright
-- Performing post-build validation
A suitable version of 7zip was not found (required v21.7.0) Downloading portable 7zip 21.7.0...
Downloading 7zip...
https://www.7-zip.org/a/7z2107-extra.7z->C:\dev\vcpkg\downloads\7z2107-extra.7z
Downloading https://www.7-zip.org/a/7z2107-extra.7z
Extracting 7zip...
Stored binary cache: "C:\Users\dc\AppData\Local\vcpkg\archives\8c\8cdbd397ceb9deebe6f4722cbd6205e749ab3c30b6e0c726c41557c01efc5392.zip"
Elapsed time to handle vcpkg-cmake:x64-windows: 1.204 s
Installing 2/2 arduino-esp32-2-0-6:x86-windows...
Building arduino-esp32-2-0-6[core]:x86-windows...
-- Using cached arduins_esp32_2_0_6.
-- Extracting source C:/dev/vcpkg/downloads/arduins_esp32_2_0_6
-- Using source at C:/dev/vcpkg/buildtrees/arduino-esp32-2-0-6/src/sp32_2_0_6-8088f930d6.clean
-- Found external ninja('1.10.2').
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/dev/vcpkg/buildtrees/arduino-esp32-2-0-6/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\dev\vcpkg\buildtrees\arduino-esp32-2-0-6\config-x86-windows-dbg-CMakeCache.txt.log
      C:\dev\vcpkg\buildtrees\arduino-esp32-2-0-6\config-x86-windows-rel-CMakeCache.txt.log
      C:\dev\vcpkg\buildtrees\arduino-esp32-2-0-6\config-x86-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:248 (vcpkg_execute_required_process)
  ports/arduino-esp32-2-0-6/portfile.cmake:65 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)

error: building arduino-esp32-2-0-6:x86-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+arduino-esp32-2-0-6
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[arduino-esp32-2-0-6]+Build+error
Include '[arduino-esp32-2-0-6] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 91dd61bd4 2023-01-27 (2 days ago)

- Attach ***every failure log file*** mentioned in the console output.

**Additional context**
[issue_body.md](https://github.com/microsoft/vcpkg/files/10530998/issue_body.md)

Add any other context about the problem here, such as what you have already tried to resolve the issue.
[issue_body.md](https://github.com/microsoft/vcpkg/files/10531001/issue_body.md)
[config-x86-windows-dbg-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10531006/config-x86-windows-dbg-CMakeCache.txt.log)
[config-x86-windows-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10531008/config-x86-windows-rel-CMakeCache.txt.log)

**Comment by Cheney-W** [comment]
1. This port `arduino-esp32-2-0-6` is not a vcpkg port.

2. According to the error log: 
```
CMake Error at CMakeLists.txt:213 (idf_component_register):
  Unknown CMake command "idf_component_register".
```
I think you should check the `CMakeLists.txt` file of `arduino-esp32-2-0-6` and fix this unknown command.

**Comment by jimwang118** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
