### ISSUE TITLE
[bzip2] Build error

### ISSUE THREAD

**Issue by BeneficialCode** [microsoft/vcpkg#29274]
**Host Environment**

- OS: [Windows 10]

vcpkg-tool version: 2022-10-17-3247920fbdd47d08f36cbd480addd9890d3c2435
vcpkg-scripts version: 2871ddd91 2022-11-10 (3 months ago)

**To Reproduce**

`vcpkg install poco:x86-windows-static`

**Failure logs**

CMake Error: Problem with archive_write_header(): Can't unlink already-existing object
CMake Error: Current file: bzip2-1.0.8/manual.pdf
CMake Error: Problem extracting tar: D:/vcpkg/downloads/bzip2-1.0.8.tar.gz

**Comment by FrankXie05** [comment]
@BeneficialCode Please re-install the unzip software. `Bandizip`

**Comment by BeneficialCode** [comment]
How can I do that? I don't know the bandizip install path.

**Comment by FrankXie05** [comment]
This is due to a issue with your local compression software [Bandizip](https://www.bandisoft.com/bandizip/), you need to uninstall and reinstall it.

**Comment by BeneficialCode** [comment]
I didn't install the Bandizip. I deleted the vcpkg, then I completely reinstalled the vcpkg. This issue disappeared.
