### ISSUE TITLE
[New Port Request] boost-ext-te

### ISSUE THREAD

**Issue by Minecraft1248** [microsoft/vcpkg#29270]
Library name: boost-ext-te

Library description: Your C++17 one header only run-time polymorphism (type erasure) library with no dependencies, macros and limited boilerplate

Source repository URL: https://github.com/boost-ext/te

**Comment by autoantwort** [comment]
Hm there are a lot of open issues and it seems that the library has some problems

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
