### ISSUE TITLE
[zlib] Build error

### ISSUE THREAD

**Issue by BeneficialCode** [microsoft/vcpkg#29278]
Package: zlib[core]:x86-windows-static -> 1.2.13

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.30.30706.0
-    vcpkg-tool version: 2022-10-17-3247920fbdd47d08f36cbd480addd9890d3c2435
    vcpkg-scripts version: 2871ddd91 2022-11-10 (3 months ago)

**To Reproduce**

`vcpkg install curl:x86-windows-static`

**Failure logs**

```
-- Using cached madler-zlib-v1.2.13.tar.gz.
-- Cleaning sources at D:/vcpkg/buildtrees/zlib/src/v1.2.13-f30d2a168d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/madler-zlib-v1.2.13.tar.gz
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: D:/vcpkg/downloads/tools/cmake-3.25.0-windows/cmake-3.25.0-windows-i386/bin/cmake.exe -E tar xjf D:/vcpkg/downloads/madler-zlib-v1.2.13.tar.gz
    Working Directory: D:/vcpkg/buildtrees/zlib/src/v1.2.13-f30d2a168d.clean.tmp
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\zlib\extract-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive.cmake:126 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:8 (vcpkg_extract_source_archive)
  scripts/cmake/vcpkg_from_github.cmake:113 (vcpkg_extract_source_archive_ex)
  ports/zlib/portfile.cmake:2 (vcpkg_from_github)
  scripts/ports.cmake:147 (include)



```
<details><summary>D:\vcpkg\buildtrees\zlib\extract-err.log</summary>

```
CMake Error: Problem with archive_write_header(): Can't unlink already-existing object
CMake Error: Current file: zlib-1.2.13/doc/crc-doc.1.0.pdf
CMake Error: Problem extracting tar: D:/vcpkg/downloads/madler-zlib-v1.2.13.tar.gz
```
</details>

**Additional context**

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This should be the tar file is broken, you could remove file **D:/vcpkg/downloads/madler-zlib-v1.2.13.tar.gz**, then rebuild `zlib`.

**Comment by BeneficialCode** [comment]
I follow your answer. But it doesn't work for me.

**Comment by dg0yt** [comment]
Similar to #29274, same user.

**Comment by LilyWangLL** [comment]
Vcpkg use tool 7zip to extract archive, could you please check the tool 7zip `D:/vcpkg/downloads/tools/7zip-21.07-windows` is complete？
![image](https://user-images.githubusercontent.com/94091114/215994433-524a5960-fe82-4d35-ba80-ef8644a9992f.png)

**Comment by BeneficialCode** [comment]
I completely reinstalled the vcpkg. This issue disappeared.
