### ISSUE TITLE
[upb] Build error (x64-windows)

### ISSUE THREAD

**Issue by WiestDaessle** [microsoft/vcpkg#29281]
**Host Environment**

- OS: Windows 10 Pro 
- Compiler: Visual Studio 2019

    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 91dd61bd4 2023-01-27 (3 days ago)

**To Reproduce**

`./vcpkg install  upb[codegen,core]:x64-windows`

**Failure logs**

Computing installation plan...
The following packages will be built and installed:
    upb[codegen,core]:x64-windows -> 2022-06-21
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\z127\AppData\Local\vcpkg\archives in 446.7 us. Use --debug to see more details.
Installing 1/1 upb:x64-windows...
Building upb[codegen,core]:x64-windows...
-- Note: upb only supports static library linkage. Building static library.
-- Using cached protocolbuffers-upb-e4635f223e7d36dfbea3b722a4ca4807a7e882e2.tar.gz.
-- Cleaning sources at D:/Checkout_2020/vcpkg/buildtrees/upb/src/07a7e882e2-67ea24d098.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Checkout_2020/vcpkg/downloads/protocolbuffers-upb-e4635f223e7d36dfbea3b722a4ca4807a7e882e2.tar.gz
-- Applying patch 0001-make-cmakelists-py.patch
-- Applying patch 0002-fix-uwp.patch
-- Using source at D:/Checkout_2020/vcpkg/buildtrees/upb/src/07a7e882e2-67ea24d098.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: D:/Checkout_2020/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe --build . --config Release --target install -- -v -j37
    Working Directory: D:/Checkout_2020/vcpkg/buildtrees/upb/x64-windows-rel
    See logs for more information:
      D:\Checkout_2020\vcpkg\buildtrees\upb\install-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/upb/portfile.cmake:39 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building upb:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+upb
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[upb]+Build+error
Include '[upb] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 91dd61bd4 2023-01-27 (3 days ago)

[install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/10535785/install-x64-windows-rel-out.log)

**Additional context**

Tested on 2 windows 10 computer with issues, worked on a windows 11 with similar configuration.

**Comment by WiestDaessle** [comment]
After seeking for a while on previous errors,
The issue is as following: 
protobuf library was locked due to some usage of the library by a running process server,
overwriting the file was then failing, but only yielding a warning message.
At the end of the day, running the protoc.exe was not possible due to library discrepancy.
I think that the protobuf package is faulty to let go when a library or exe file cannot be written/overwritten, as when a large update is ongoing this is hard to tackle.

The fact that windows is locking dll/exe file on runtime should be taken into account to have a build failure.

**Comment by JackBoosY** [comment]
> After seeking for a while on previous errors, The issue is as following: protobuf library was locked due to some usage of the library by a running process server, overwriting the file was then failing, but only yielding a warning message. At the end of the day, running the protoc.exe was not possible due to library discrepancy. I think that the protobuf package is faulty to let go when a library or exe file cannot be written/overwritten, as when a large update is ongoing this is hard to tackle.
> 
> The fact that windows is locking dll/exe file on runtime should be taken into account to have a build failure.

If the file was locked by some other software (system won't lock it!), I think it's not a vcpkg issue.

**Comment by mmerah** [comment]
I stumbled upon this error as well. My conclusion is that there is a set of configuration that make upb build fail. So, I agree that I don't think this is a vcpkg issue.

Host Environment
- OS: Ubuntu 22.04
- Compiler: gcc 12.2.0
- vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
- vcpkg-scripts version: 0ba60bfef 2023-02-03 (3 days ago)

To Reproduce
- docker image: 
```
FROM gcc:12.2.0 AS build

RUN apt-get update && \
    apt-get install -y curl unzip zip

ARG CMAKE_VERSION=3.22.1
RUN wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-Linux-x86_64.sh \
      -q -O /tmp/cmake-install.sh \
      && chmod u+x /tmp/cmake-install.sh \
      && mkdir /usr/bin/cmake \
      && /tmp/cmake-install.sh --skip-license --prefix=/usr/bin/cmake \
      && rm /tmp/cmake-install.sh
ENV PATH="/usr/bin/cmake/bin:${PATH}"

WORKDIR /app

RUN git clone https://github.com/microsoft/vcpkg
RUN cd vcpkg && \
    ./bootstrap-vcpkg.sh && \
    cd /app && \
    chmod -R 777 vcpkg && \
    cd vcpkg/ && \
    ./vcpkg install upb[codegen,core]
```

- If I don't manually add CMake at a specific version, it does not fail
- I cannot reproduce it on my host machine (Linux Ubuntu 22.04, using an environment with the same versions)

Failure logs
Exact same as the reporter

Additional context
Using a different base image and getting CMake through apt-get, I can avoid this error.

**Comment by JackBoosY** [comment]
```
--upb_out: protoc-gen-upb: Plugin failed with status code 3221225785.
```
3221225785 == 0xC0000139. Maybe missing / mismatched dependencies.

**Comment by jimwang118** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
