### ISSUE TITLE
Enhance downloading experience

### ISSUE THREAD

**Issue by cmpute** [Microsoft/vcpkg#2928]
Many users including me, has suffered from poor connection with Github server host (AWS) or SourceForge. And downloading which often fails sucks. Downloading fuction built in CMake is quite deficient.

I would suggest add an external tool for downloading such as `aria2`. And one can use `vcpkg install --enable-aria2` to download aria2 as a tool and use aria2 to download other tools or archives.

**Comment by traversaro** [comment]
Related issue: https://github.com/Microsoft/vcpkg/issues/932 .

**Comment by cmpute** [comment]
I'm starting working on this. There are several external downloading tools for chosen. Best choices comes to my mind are `curl`, `wget` and `aria2`. Which would you choose? There's a [comparison table](https://curl.haxx.se/docs/comparison-table.html). Only aria2 provides official binary download.

It's also an option to make all these tools available in vcpkg, but it's a big work.

**Comment by cmpute** [comment]
Tried to implement here: #2963

**Comment by martin-s** [comment]
Aria2 has problems with file URIs, see  #3230.

**Comment by cmpute** [comment]
@martin-s Could you use built-in downloader in this situation?

**Comment by martin-s** [comment]
Yes, I used the built-in downloader as a workaround. Meanwhile a fix is also available.
The point is that I'm surprised that aria2 doesn't support the file protocol. That shouldn't be.

**Comment by LarryIII** [comment]
This support should be merged in https://github.com/Microsoft/vcpkg/pull/2963, so closed it!
