### ISSUE TITLE
Usage with Qt creator

### ISSUE THREAD

**Issue by AnirudhPuligandla** [microsoft/vcpkg#29287]
I would be glad if someone could direct me how to use installed packages in Qt creator. I installed pcl:x64-windows and it works completely fine in visual studio 2022. The same code however is not working in Qt creator with Qt 6.4.2, qmake and MSVC 2019. As a usual procedure, I added paths to the include and lib directories from vcpkg\installed\x64-windows\ in my .pro file and also added the required libraries. But I get a file not found error in Qt when reading a PLY file while the same code executes withour errors in VS.

**Comment by JackBoosY** [comment]
Maybe @Neumann-A can help you here?

**Comment by longhuan2018** [comment]
Is it the path string encoding problem?

**Comment by AnirudhPuligandla** [comment]
It could be, because the error message displays strange characters in place of the filename. But I do not know if this is a Qt problem because the path strings in the format work fine with other libraries (vtk compiled from source for e.g.).
The error message I get is : [pcl::PLYReader::read] File ((òï}Â) not found! .

**Comment by longhuan2018** [comment]
try QString::toLocal8Bit().constData() 或 QString::toUtf8().constData()

**Comment by AnirudhPuligandla** [comment]
Still the same error.

**Comment by AnirudhPuligandla** [comment]
Everything is in english without any spaces in the names. I am wondering if i am using the vcpkg packages correctly in Qt. I added paths to include and lib directories as mentioned in my first post. Also copied the required DLLs into the project's build directory. Is that sufficient? Am I missing any depending packages in vcpkg that are specific to Qt use?

**Comment by longhuan2018** [comment]
> Everything is in english without any spaces in the names. I am wondering if i am using the vcpkg packages correctly in Qt. I added paths to include and lib directories as mentioned in my first post. Also copied the required DLLs into the project's build directory. Is that sufficient? Am I missing any depending packages in vcpkg that are specific to Qt use?

If the program can be compiled and run, there should be no problem with the configuration.
What I'm curious about now is why the English path prompts garbled code? Can you provide some code to see?

**Comment by dg0yt** [comment]
Are you sure the qmake build uses the same flags and macros (UNICODE, _UNICODE, etc.)?

**Comment by AnirudhPuligandla** [comment]
I do not know how to check that. In the build directory i found "Makefile.Debug" that mentions those flags in "DEFINES" variable. I am attaching a screenshot from that file, if that is what we are looking for.

<img width="711" alt="Screenshot 2023-01-31 213519" src="https://user-images.githubusercontent.com/18196482/215814883-1caab06b-6781-4f96-b6cd-af56f2618065.png">

**Comment by longhuan2018** [comment]
I tried Debug and Release compilation, and executed successfully in Release mode.
If you use the Debug library, you can also execute successfully in Debug mode.
However, in Debug mode, if the Release library is used, an error will be reported.
Maybe you can try whether the Release mode is successful?

In Release mode, you can also debug, just set the output debugging information.
![image](https://user-images.githubusercontent.com/8551701/216214570-0a332c83-2bbd-45e0-a9c8-ff150ce2c29c.png)

**Comment by AnirudhPuligandla** [comment]
It works in release mode. I installed pcl in vcpkg with the default settings and did not pay attention to the build_type. Thanks a lot for the help!
