### ISSUE TITLE
[New Port Request] ta-lib

### ISSUE THREAD

**Issue by kkqy** [microsoft/vcpkg#29328]
Library name:ta-lib

Library description: TA-Lib is widely used by trading software developers requiring to perform technical analysis of financial market data.

Source repository URL:https://ta-lib.org/hdr_dw.html

Project homepage (if different from the source repository):https://ta-lib.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
