### ISSUE TITLE
[icu] Regression - build fails for x64-linux-release

### ISSUE THREAD

**Issue by Chlumsky** [microsoft/vcpkg#29322]
**Host Environment**

- OS: Docker, debian:11-slim
- Compiler: clang (current from apt)

**To Reproduce**

`vcpkg --triplet x64-linux-release install icu`

**Failure logs**

```
-- Installing x64-linux-release-rel
CMake Error at scripts/cmake/vcpkg_copy_tools.cmake:36 (message):
  Couldn't find tool "icupkg":

      "/opt/vcpkg/packages/icu_x64-linux-release/tools/icu/sbin/icupkg" does not exist
Call Stack (most recent call first):
  ports/icu/portfile.cmake:162 (vcpkg_copy_tools)
  scripts/ports.cmake:147 (include)

    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: b4f29c544 2023-01-30 (11 hours ago)
```

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Broken by #29196 / cdbcc0321216fe46e4b20941f76ad21429d2a90c @m-kuhn 

The `x64-linux-release` is a "community triplet" but it is very useful to speed up automatic builds and CI.

**Comment by dg0yt** [comment]
This came almost expected: https://github.com/microsoft/vcpkg/pull/29196 is incomplete without actually feeding the host tool paths into the build.

@Chlumsky I assume you don't  set the host triplet to `x64-linux-release`, too. This would speed-up even more, and workaround the issue for a x64 linux machine.

**Comment by Chlumsky** [comment]
Never heard of a "host triplet". So I should do it like `vcpkg install --triplet x64-linux-release --host-triplet x64-linux-release install xy` ?

**Comment by m-kuhn** [comment]
Is https://github.com/microsoft/vcpkg/pull/19726 not sufficient?

**Comment by dg0yt** [comment]
> Never heard of a "host triplet". So I should do it like `vcpkg install --triplet x64-linux-release --host-triplet x64-linux-release install xy` ?

What should run of the host must come from the host triplet. If you only change the target triplet, you get a vcpkg cross-build. This may give you an extra full qtbase:x64-linux build if you ask for qtbase:x64-linux-release...

**Comment by dg0yt** [comment]
> Is #19726 not sufficient?

I'm sorry, I didn't pay enough attention to the error message. The actual problem is a different spot than what I assumed:

https://github.com/microsoft/vcpkg/blob/b4f29c54450ddfc7efd2989cb9d32158ae291b40/ports/icu/portfile.cmake#L160-L167

This is not guarded by the `tools` feature. And not covered in CI for cross-builds.

**Comment by m-kuhn** [comment]
@Chlumsky can you test https://github.com/microsoft/vcpkg/pull/29329 ?

**Comment by xiaozhuai** [comment]
This problem also occured on x86_64 macos when building icu:arm64-osx.
