### ISSUE TITLE
[rxcpp] `find_package(rxcpp "4.1.1" CONFIG REQUIRED)` fails because of wrong version info

### ISSUE THREAD

**Issue by mediumrarez** [microsoft/vcpkg#29339]
Library name: `rxcpp`
New version number: `4.1.1`

`find_package(rxcpp "4.1.1" CONFIG REQUIRED)` fails with the following error.

```
CMake Error at C:/opt/vcpkg/scripts/buildsystems/vcpkg.cmake:844 (_find_package):
  Could not find a configuration file for package "rxcpp" that is compatible
  with requested version "4.1.1".

  The following configuration files were considered but not accepted:

    C:/Users/User/hello/cmake-build-debug/vcpkg_installed/x64-windows/share/rxcpp/rxcppConfig.cmake, version: 2.2.4
```

It seems that `rxcppConfigVersion.cmake` hasn't been updated to match the new package version.

**Comment by FrankXie05** [comment]
@mediumrarez Please delete the local `rxcpp` cache and install `rxcpp` again.

**Comment by mediumrarez** [comment]
I deleted `cmake-build-debug`, and `vcpkg_installed`, then reinstalled everything but the error still persists.

I'm running in manifest mode. Do I need to delete the global vcpkg cache too?

**Comment by FrankXie05** [comment]
I have not reproduced it, could you please provide me with your sample project file? :)
![image](https://user-images.githubusercontent.com/65999885/215931994-e5983b1c-aae7-44c0-838c-e3045f519d61.png)
This is my example project :
```
# CMakeList.txt : CMake project for usage, include source and define
# project specific logic here.
#
cmake_minimum_required (VERSION 3.8)

project(test)
# Add source to this project's executable.
add_executable (usage "usage.cpp" "usage.h")

# TODO: Add tests and install targets if needed.
find_package(rxcpp CONFIG REQUIRED)
target_link_libraries(usage PRIVATE rxcpp)
```

**Comment by mediumrarez** [comment]
You're missing the version specifier. I can reproduce with your sample `CMakeLists.txt` by adding the version specifier.

```
find_package(rxcpp "4.1.1" CONFIG REQUIRED)
                    ^^^^^
```

**Comment by FrankXie05** [comment]
Do you want to specify the port version?

**Comment by FrankXie05** [comment]
> You're missing the version specifier. I can reproduce with your sample `CMakeLists.txt` by adding the version specifier.

I didn't add a version note because the default is looking for the latest version via `CMAKE_TOOLCHAIN_FILE`.

**Comment by mediumrarez** [comment]
No, just the version of the actual library. The idea is so I can let the user choose if he wants to use vcpkg or not. If he doesn't want to use vcpkg, `find_package()` will still find the right version from his system.

**Comment by FrankXie05** [comment]
@mediumrarez At present, vcpkg only provides the latest port version. You can achieve it through `manifest mode`. But we can't provide such a method as `find_package( xxx "version" CONFIG REQUIRED)`. :(
This will cause the project to find a version conflict between the config file provided by `cmake` and the config file provided by `vcpkg`.

**Comment by mediumrarez** [comment]
Ok, I think I found the real issue, which is that upstream hasn't been updating their `PROJECT_VERSION` in the `CMakeLists.txt` file. I will try to resolve this upstream. https://github.com/ReactiveX/RxCpp/issues/599

**Comment by FrankXie05** [comment]
@mediumrarez Regarding the last update upstream that happened nine months ago, I think we can only deal with it through patches. 🤔

**Comment by mediumrarez** [comment]
@FrankXie05 Yes, I think so too. It doesn't look too hopeful.

**Comment by dg0yt** [comment]
Not a vcpkg bug  IMO.

> I think we can only deal with it through patches

If upstream doesn't suppport versions in `find_package`, I don't see a good reason to add it though patches. vcpkg has versioning by manifests.

**Comment by mediumrarez** [comment]
@dg0yt The idea is to let the user choose whether or not to use vcpkg. If vcpkg isn't used, then `find_package` can still find the right version from the user's system.

**Comment by dg0yt** [comment]
> @dg0yt The idea is to let the user choose whether or not to use vcpkg. If vcpkg isn't used, then `find_package` can still find the right version from the user's system.

There is nothing wrong with choice. However, I don't think this is a strong argument here:
- The defect is on upstream's side, and a vendored fix in vcpkg doesn't change it: Until it is fixed upstream, `find_package` can't reliably find the right *pristine* config from the user's system.
- Version control is not explicit control over whether vcpkg is used or not.
- Version is just one single aspect for choice of actual CMake config.
  There are many ways to guide `find_package` search in config mode.
- In general, `find_package` cannot ensure that there are no transitive ABI-level dependencies on vcpkg's build of the package when the user still consumes other vcpkg ports. To really exclude a particular package, one would need to provide an empty overlay port, letting vcpkg use the system package, too.

**Comment by mediumrarez** [comment]
> Until it is fixed upstream, `find_package` can't reliably find the right _pristine_ config from the user's system.

Hmm... I guess you're right. Closing.
