### ISSUE TITLE
[stx] Upstream is gone

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/vcpkg#29382]
The port "stx" is looking for a ref "1.0.1", but upstream https://github.com/lamarrr/STX has removed it.

@jeanga You authored this port. Do you know what we should make it say now instead?
@lamarrr You are the upstream owner. Do you know what ref we should be using?

The problematic reference; I don't know what SHA to change it to.

https://github.com/microsoft/vcpkg/blob/a548ef52e5b6b4b92de09fd0efdeaa95c745e2a0/ports/stx/portfile.cmake#L3-L11

**Comment by lamarrr** [comment]
Let it use v0.0.1 in the meantime. As the build steps for v0.0.2 is a bit different and we’d need to submit a patch for it

**Comment by lamarrr** [comment]
Hi Billy, I've updated the port. It's my first time creating a port so there might be mistakes, here: https://github.com/microsoft/vcpkg/pull/29392
