### ISSUE TITLE
[libtool] Patches for cl

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#29397]
while doing some library research stuff I found: https://github.com/coin-or-tools/BuildTools/blob/stable/0.8/coin.m4#L1709

mentioned here: https://github.com/coin-or/CoinUtils/issues/117#issuecomment-590265314

@dg0yt Maybe you are interested in extracting those somehow

**Comment by Neumann-A** [comment]
Still relevant

**Comment by Cheney-W** [comment]
Stay active
