### ISSUE TITLE
[glew] CMake configuration problems on x64-linux-dynamic

### ISSUE THREAD

**Issue by cbrl** [microsoft/vcpkg#29402]
**Describe the bug**
GLEW compiles successfully on `x64-linux-dynamic`, but has some problems when included in a project. The cmake wrapper gets the values of the `GLEW_LIBRARY_[DEBUG|RELEASE]` variables from the `IMPORTED_IMPLIB_[DEBUG|RELEASE]` target properties, but these properties aren't defined in the corresponding `glew-targets-[debug|release].cmake` files. 

https://github.com/microsoft/vcpkg/blob/a548ef52e5b6b4b92de09fd0efdeaa95c745e2a0/ports/glew/vcpkg-cmake-wrapper.cmake#L11-L12 

Only the `IMPORTED_LOCATION_[DEBUG|RELEASE]` property is set on the target. Both of these imported library properties are defined in `x64-windows`, however.

This propagates up to `GLEW_LIBRARY` and `GLEW_LIBRARIES`, which will end up with a value of `*-NOTFOUND`. This can cause some issues in other ports. For example `osgearth[tools]:x64-linux-dynamic` fails at the configuration stage when it attempts to link `GLEW_LIBRARIES` to `osgearth_imgui`.

**Environment**
- OS: Linux
- Compiler: GCC 9.4.0

**To Reproduce**
1. `./vcpkg install glew:x64-linux-dynamic`
2. Create a simple CMake project which imports GLEW and prints the value of `GLEW_LIBRARIES`, which will not be valid.

Alternatively,
1. `./vcpkg install osgearth[tools]:x64-linux-dynamic`
2. The configuration stage will fail when it attempts to link `GLEW_LIBRARIES` to `osgearth_imgui`.

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
