### ISSUE TITLE
Run build everytime when Configuration name not start with Debug/Release

### ISSUE THREAD

**Issue by yumetodo** [microsoft/vcpkg#2940]
When I create the configuration that of the name is not start with Debug/Release(like `clang_Debug`), build command behave as if it was not cached.

![fafnir](https://user-images.githubusercontent.com/10869046/36931480-a3b93642-1ef9-11e8-881b-387215bff3e2.gif)

According to the investigation by @kazatsuyu,
https://twitter.com/kazatsuyu/status/969814280802525184?s=20

https://github.com/Microsoft/vcpkg/blob/a28138eb9ef8d2986227b7cd784be9ffa8492a46/scripts/buildsystems/msbuild/vcpkg.targets#L54-L55

Because of using `StartsWith`, `clang_Debug` is not detected by vcpkg as debug even if it contains Debug.`clang_Release` is also.

Do you have a plan to support the configuration name that is not start with Debug/Release but contain Debug/Release?

ref:
- https://github.com/kazatsuyu/fafnir/issues/5

**Comment by linquize** [comment]
Is it still valid with the latest vcpkg?

**Comment by BillyONeal** [comment]
Fixed by https://github.com/microsoft/vcpkg/pull/26177
