### ISSUE TITLE
Difference in binary outputs in openssl package between Linux and Windows

### ISSUE THREAD

**Issue by wesSTILMAN** [microsoft/vcpkg#29400]
We have observed a difference between the build artifacts produced for the openssl package between Linux and Windows. On windows, someone may type:

c:\vcpkg>vcpkg install openssl

And in this location:

C:\vcpkg\installed\x64-windows\tools\openssl

The following artifacts will be seen: 
openssl.exe
libcrypto-3-x64.dll
libssl-3-x64.dll

But on Linux, running:

./vcpkg install openssl

Does not even create an openssl folder in installed/x64-linux/tools.

Searching the entire drive I only see the openssl executable put there by the system repo manager. Is there a reason these things are not build on Linux?

Operating systems used: Windows 10 22H2, and RedHat 8 ( Linux 4.18.0-425.3.1.el8.x86_64).

**Comment by dg0yt** [comment]
Would this help? https://github.com/microsoft/vcpkg/pull/27261

My x64-linux installation has:
~~~~
$ find installed/x64-linux/tools/openssl
installed/x64-linux/tools/openssl
installed/x64-linux/tools/openssl/openssl
installed/x64-linux/tools/openssl/c_rehash

**Comment by wesSTILMAN** [comment]
> Would this help? #27261
> 
> My x64-linux installation has:
> 
> ```
> $ find installed/x64-linux/tools/openssl
> installed/x64-linux/tools/openssl
> installed/x64-linux/tools/openssl/openssl
> installed/x64-linux/tools/openssl/c_rehash
> ```

Indeed this does seem to help. The unified configuration also makes it much easier for us to synchronize instructions between platforms. Already, we have been able to confirm creation of the openssl executable using this PR. We have added `enable-fips` to CONFIGURE_OPTIONS and are currently trying to get that working, which was also failing in the trunk.

**Comment by MonicaLiu0311** [comment]
@wesSTILMAN 
#27261 has been merged, has your problem been resolved?

**Comment by wesSTILMAN** [comment]
We are still using the PR, but it all works very well. I’m glad this got merged in.

Wes

**Comment by dg0yt** [comment]
FYI FIPS support is coming: https://github.com/microsoft/vcpkg/pull/30916
