### ISSUE TITLE
All downloads from Sourceforge in vcpkg are currently failing

### ISSUE THREAD

**Issue by traversaro** [Microsoft/vcpkg#2942]
All the ports that download files from sourceforge are currently failing the hash check on my setup. 

As the status of the [`file(DOWNLOAD ...)`](https://github.com/Microsoft/vcpkg/blob/a0eece81c68faf9713441c3aeb283a16bc232c52/scripts/cmake/vcpkg_download_distfile.cmake#L108) cmake call is actually successful, and downloading the same files from the browser works fine, I inspected the files as downloaded from vcpkg to find the following message:
~~~
PS C:\src\vcpkg-new> cat .\downloads\temp\freeglut-3.0.0.tar.gz
<html><head>
<title>SourceForge</title>
<!-- <script src="/js/jquery.com/jquery-1.11.0.min.js"></script> -->
<script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="https://sourceforge.net/js/mirrors.js"></script>
<script src="/js/sf.js"></script>
<script>
var DR_loc = DR_parse_hash_url();
if (DR_loc) {
    DR_sf_main(DR_loc);
} else {
    window.location.href = 'https://sourceforge.net/home.html';
}
</script>
</head><body>
<noscript>
We're sorry -- the Sourceforge site is currently in Disaster Recovery mode, and currently requires
the use of javascript to function.  Please check back later.
</noscript>
</body></html>
~~~

I guess it is a temporary issue with sourceforge (see https://twitter.com/sfnet_ops/status/969743281922936832) for which it is difficult to do something on the vcpkg part, but it is worth to open an issue for confused users because the download on the website is working fine.

See https://github.com/Microsoft/vcpkg/issues/2928 for a related issue.

**Comment by traversaro** [comment]
Similar homebrew issue from 2015: https://github.com/Homebrew/legacy-homebrew/issues/41778 .

**Comment by cmpute** [comment]
Also #2924, #2890

**Comment by traversaro** [comment]
Thanks, I did not notice https://github.com/Microsoft/vcpkg/issues/2924 . So it is on-going from (at least) three days ago.

**Comment by traversaro** [comment]
The situation now evolved. Sourceforge reports everything should be back to normal https://twitter.com/sfnet_ops/status/970143157307559936 , but the vcpkg downloads are now failing with error 22: 
~~~
-- Downloading http://downloads.sourceforge.net/project/freeglut/freeglut/3.0.0/freeglut-3.0.0.tar.gz...
-- Downloading http://downloads.sourceforge.net/project/freeglut/freeglut/3.0.0/freeglut-3.0.0.tar.gz... Failed. Status: 22;"HTTP response code said error"
~~~

I opened an issue on their issue tracker : https://sourceforge.net/p/forge/site-support/17017/ .
But apparently it is not a problem related only to vcpkg : 
![snip-sourceforge](https://user-images.githubusercontent.com/1857049/36946742-ed74eaa6-1fc1-11e8-8da7-7a44f2f51451.PNG)

**Comment by traversaro** [comment]
The issue seems to be solved now : https://twitter.com/sfnet_ops/status/970316086959845382 . 
Closing the issue.
