### ISSUE TITLE
[minhook] Build error

### ISSUE THREAD

**Issue by DiTi19** [microsoft/vcpkg#29428]
Hey, can anyone help me with the installation of minhook. There seems to be an error while downloading.
the file:
[issue_body.md](https://github.com/microsoft/vcpkg/files/10577105/issue_body.md)
this is what it says in cmd:
error: building minhook:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+minhook
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[minhook]+Build+error
Include '[minhook] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: a548ef52e 2023-02-01 (29 hours ago)

**Comment by Cheney-W** [comment]
Please make sure you have installed the `English language package` and `Desktop development with C++` components from `Visual Studio Installer`.

**Comment by DiTi19** [comment]
> Please make sure you have installed the `English language package` and `Desktop development with C++` components from `Visual Studio Installer`.

I will try and inform you if I make it.
