### ISSUE TITLE
The NDK default to include android-legacy.toolchain.cmake

### ISSUE THREAD

**Issue by aa889788** [microsoft/vcpkg#29438]
The Android NDK default include `android-legacy.toolchain.cmake` to fix https://github.com/android/ndk/issues/1693

So I want to set `ANDROID_USE_LEGACY_TOOLCHAIN_FILE` in my own triplet

```cmake
set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_CMAKE_SYSTEM_NAME Android)
set(VCPKG_CMAKE_SYSTEM_VERSION 29)
set(VCPKG_BUILD_TYPE release)
set(ANDROID_USE_LEGACY_TOOLCHAIN_FILE false)

include(${CMAKE_CURRENT_LIST_DIR}/maa-linux-library-override.cmake.inc)

```

But not work, is there any solutions for that?

**Comment by dg0yt** [comment]
The triplet file is used in CMake script mode in vcpkg. You want an effect on CMake project mode. 
https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#portfiles-are-run-in-script-mode
The `VCPKG_CMAKE_CONFIGURE_OPTIONS` variable can be used to set options to be passed into project builds.

**Comment by Adela0814** [comment]
@aa889788  Have you tried variable `VCPKG_CMAKE_CONFIGURE_OPTIONS`? Does your problem still exist?
