### ISSUE TITLE
[freetype] Build error

### ISSUE THREAD

**Issue by kmjudah** [microsoft/vcpkg#29435]
**Host Environment**

- OS: Windows 10 Pro
- Compiler: revision

**To Reproduce**

`./vcpkg install osgearth:x64-windows`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:273 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_sourceforge.cmake:83 (vcpkg_download_distfile)
  ports/freetype/portfile.cmake:3 (vcpkg_from_sourceforge)
  scripts/ports.cmake:147 (include)

error: building freetype:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+freetype
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[freetype]+Build+error
Include '[freetype] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: a7c0f2b2b 2023-02-03 (25 minutes ago)

- Attach ***every failure log file*** mentioned in the console output.
[issue_body.md](https://github.com/microsoft/vcpkg/files/10582390/issue_body.md)

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by FrankXie05** [comment]
Please make sure your network is smooth and the proxy is available.
This link has been verified locally as valid. 
```
Downloading https://sourceforge.net/projects/freetype/files/freetype2/2.12.1/freetype-2.12.1.tar.xz/download
warning: Download failed -- retrying after 1000ms
warning: Download failed -- retrying after 2000ms
warning: Download failed -- retrying after 4000ms
```

**Comment by FrankXie05** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
