### ISSUE TITLE
[shader-slang] can't start the process on linux platform

### ISSUE THREAD

**Issue by wh1t3lord** [microsoft/vcpkg#29445]
**Host Environment**

- OS: Linux, Ubuntu 22.10 
- Compiler: idk (probably gcc)

**To Reproduce**

`./vcpkg install shader-slang:x64-linux`

**Failure logs**

 shader-slang[core]:x64-linux is only supported on '((x86 & windows) | (x64 & (windows | linux | osx)) | (arm64 & (linux | osx))) & !uwp & !static'

![image](https://user-images.githubusercontent.com/68504048/216756169-a9fc656e-5486-4758-b82d-5bf3f2d294a4.png)

**Additional context**

If you proceed to official https://github.com/shader-slang/slang of this port you can clearly see that it supports linux platform. So it is a bug and I hope you can fix it in short time.

**Comment by Osyotr** [comment]
`x64-linux` builds static libraries, and this library does not support static linkage. Either use `x64-linux-dynamic` or per-port customization.

**Comment by wh1t3lord** [comment]
It wasn't obvious for me, thanks. @Osyotr

**Comment by dg0yt** [comment]
Port bug.
