### ISSUE TITLE
[OpenImageIO] Fails to link

### ISSUE THREAD

**Issue by spectre-ns** [microsoft/vcpkg#29441]
**Host Environment**

- OS: Windows
- Compiler: Visual Studio 2019

**To Reproduce**
Run the following project
[xtesnor-png.zip](https://github.com/microsoft/vcpkg/files/10593796/xtesnor-png.zip)

run attached project in manifest mode

**Failure logs**

1>xtesnor-png.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl OpenImageIO_v2_3::string_view::string_view(char const *)" (__imp_??0string_view@OpenImageIO_v2_3@@QEAA@PEBD@Z) referenced in function main
1>xtesnor-png.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class std::unique_ptr<class OpenImageIO_v2_3::ImageOutput,struct std::default_delete<class OpenImageIO_v2_3::ImageOutput> > __cdecl OpenImageIO_v2_3::ImageOutput::create(class OpenImageIO_v2_3::string_view,class OpenImageIO_v2_3::Filesystem::IOProxy *,class OpenImageIO_v2_3::string_view)" (__imp_?create@ImageOutput@OpenImageIO_v2_3@@SA?AV?$unique_ptr@VImageOutput@OpenImageIO_v2_3@@U?$default_delete@VImageOutput@OpenImageIO_v2_3@@@std@@@std@@Vstring_view@2@PEAVIOProxy@Filesystem@2@0@Z) referenced in function main

**Comment by dg0yt** [comment]
Related: https://github.com/microsoft/vcpkg/issues/22528
Does this also occur with CMake?

**Comment by spectre-ns** [comment]
Not sure I don't use CMake in my workflow.

**Comment by spectre-ns** [comment]
Needed to define OIIO_STATIC_DEFINE  in the source. Closing. Documentation from OpenImageIO is lacking on this. I explored their documentation prior to posting here. Closing with comment.

**Comment by dg0yt** [comment]
Now the question is if this macro should be burned into the headers for static triplets.
