### ISSUE TITLE
[libtorch] build failure:zstd::libzstd_static

### ISSUE THREAD

**Issue by Bzz2745** [microsoft/vcpkg#29440]
**Host Environment**

- OS: Windows
- msvc: rvc143

**To Reproduce**

`./vcpkg install libtorch[core,dist,opencv,tbb,xnnpack,zstd]:x64-windows`

**Failure logs**

Computing installation plan...
The following packages will be built and installed:
    libtorch[core,dist,opencv,tbb,xnnpack,zstd]:x64-windows -> 1.12.1
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\BaZunzhi\AppData\Local\vcpkg\archives in 23.25 ms. Use --debug to see more details.
Installing 1/1 libtorch:x64-windows...
Building libtorch[core,dist,opencv,tbb,xnnpack,zstd]:x64-windows...
-- Using cached pytorch-pytorch-v1.12.1.tar.gz.
-- Extracting source D:/ProgramFiles/vcpkg/downloads/pytorch-pytorch-v1.12.1.tar.gz
-- Applying patch pytorch-pr-85958.patch
-- Applying patch fix-cmake.patch
-- Applying patch fix-fbgemm-include.patch
-- Applying patch fix-c10-glog.patch
-- Applying patch use-flatbuffers2.patch
-- Applying patch fix-windows.patch
-- Using source at D:/ProgramFiles/vcpkg/buildtrees/libtorch/src/v1.12.1-d15308d103.clean
-- Using flatc: D:/ProgramFiles/vcpkg/installed/x64-windows/tools/flatbuffers/flatc.exe
-- Using protoc: D:/ProgramFiles/vcpkg/installed/x64-windows/tools/protobuf/protoc.exe
-- Setting up python virtual environmnent...
-- Installing python packages: typing-extensions;pyyaml;numpy
-- Setting up python virtual environmnent...finished.
-- Using Python3: D:/ProgramFiles/vcpkg/buildtrees/libtorch/x64-windows-venv/Scripts/python.exe
-- Found external ninja('1.11.0').
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: D:/ProgramFiles/CMake/bin/cmake.exe D:/ProgramFiles/vcpkg/buildtrees/libtorch/src/v1.12.1-d15308d103.clean -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=D:/ProgramFiles/vcpkg/packages/libtorch_x64-windows/debug -DFETCHCONTENT_FULLY_DISCONNECTED=ON -DUSE_DISTRIBUTED=ON -DUSE_ZSTD=ON -DUSE_FFTW=OFF -DAT_FFTW_ENABLED=OFF -DUSE_FBGEMM=OFF -DUSE_OPENCV=ON -DUSE_TBB=ON -DAT_PARALLEL_NATIVE_TBB=ON -DUSE_OPENMP=OFF -DAT_PARALLEL_OPENMP=OFF -DUSE_LEVELDB=OFF -DUSE_OPENCL=OFF -DUSE_CUDA=OFF -DUSE_CUDNN=OFF -DUSE_NCCL=OFF -DUSE_SYSTEM_NCCL=OFF -DUSE_NVRTC=OFF -DAT_CUDA_ENABLED=OFF -DAT_CUDNN_ENABLED=OFF -DUSE_VULKAN=OFF -DUSE_VULKAN_WRAPPER=OFF -DUSE_VULKAN_SHADERC_RUNTIME=OFF -DUSE_VULKAN_RELAXED_PRECISION=OFF -DUSE_NNPACK=OFF -DAT_NNPACK_ENABLED=OFF -DUSE_XNNPACK=ON -DUSE_SYSTEM_XNNPACK=ON -DUSE_QNNPACK=OFF -DUSE_LIBUV=ON -DUSE_GLOO= -DMKLDNN_CPU_RUNTIME=TBB -DINTERN_BUILD_MOBILE=OFF -DProtobuf_PROTOC_EXECUTABLE:FILEPATH=D:/ProgramFiles/vcpkg/installed/x64-windows/tools/protobuf/protoc.exe -DCAFFE2_CUSTOM_PROTOC_EXECUTABLE:FILEPATH=D:/ProgramFiles/vcpkg/installed/x64-windows/tools/protobuf/protoc.exe -DPYTHON_EXECUTABLE:FILEPATH=D:/ProgramFiles/vcpkg/buildtrees/libtorch/x64-windows-venv/Scripts/python.exe -DPython3_EXECUTABLE:FILEPATH=D:/ProgramFiles/vcpkg/buildtrees/libtorch/x64-windows-venv/Scripts/python.exe -DCAFFE2_USE_MSVC_STATIC_RUNTIME=0 -DBUILD_CUSTOM_PROTOBUF=OFF -DUSE_LITE_PROTO=OFF -DBUILD_TEST=OFF -DATEN_NO_TEST=ON -DUSE_SYSTEM_LIBS=ON -DBUILD_PYTHON=OFF -DUSE_NUMPY=OFF -DUSE_METAL=OFF -DUSE_PYTORCH_METAL=OFF -DUSE_PYTORCH_METAL_EXPORT=OFF -DUSE_GFLAGS=ON -DUSE_GLOG=ON -DUSE_LMDB=ON -DUSE_ROCKSDB=OFF -DUSE_OBSERVERS=OFF -DUSE_PYTORCH_QNNPACK=OFF -DUSE_KINETO=OFF -DUSE_ROCM=OFF -DUSE_DEPLOY=OFF -DUSE_FFTW=OFF -DUSE_NUMA=OFF -DUSE_MPI= -DBUILD_JNI= -DUSE_NNAPI= -DBLAS=OpenBLAS -DUSE_BLAS=ON -DUSE_MKLDNN=OFF -DUSE_MKLDNN_CBLAS=OFF -DCAFFE2_USE_MKL=OFF -DCAFFE2_USE_MKLDNN=OFF -DAT_MKL_ENABLED=OFF -DAT_MKLDNN_ENABLED=OFF -DCMAKE_MAKE_PROGRAM=D:/ProgramFiles/Microsoft/VisualStudio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe -DBUILD_SHARED_LIBS=ON -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/ProgramFiles/vcpkg/scripts/toolchains/windows.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=v143 -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=D:/ProgramFiles/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=D:/ProgramFiles/vcpkg -D_VCPKG_INSTALLED_DIR=D:/ProgramFiles/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF
    Working Directory: D:/ProgramFiles/vcpkg/buildtrees/libtorch/x64-windows-dbg
    Error code: 1
    See logs for more information:
      D:\ProgramFiles\vcpkg\buildtrees\libtorch\config-x64-windows-dbg-CMakeCache.txt.log
      D:\ProgramFiles\vcpkg\buildtrees\libtorch\config-x64-windows-dbg-out.log
      D:\ProgramFiles\vcpkg\buildtrees\libtorch\config-x64-windows-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:263 (vcpkg_execute_required_process)
  ports/libtorch/portfile.cmake:108 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)

**Additional context**
D:\ProgramFiles\vcpkg\buildtrees\libtorch\config-x64-windows-dbg-err.log:
CMake Warning (dev) at torch/CMakeLists.txt:447:
  Syntax Warning in cmake code at column 107

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at torch/CMakeLists.txt:447:
  Syntax Warning in cmake code at column 115

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at caffe2/CMakeLists.txt:1419 (target_link_libraries):
  Target "torch_cpu" links to:

    zstd::libzstd_static

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_INSTALL_BINDIR
    FETCHCONTENT_FULLY_DISCONNECTED
    MKLDNN_CPU_RUNTIME
    USE_LIBUV
    USE_VULKAN_WRAPPER
    _VCPKG_ROOT_DIR

CMake Generate step failed.  Build files cannot be regenerated correctly.

PS:
One more thing,how can I enable libtorch build with CUDA and cudnn? In the file above :'disabling CUDA because USE_CUDA is set false ',which means I have tool set USE_CUDA:true to system environment values?

**Comment by mheyman** [comment]
To try to get a CUDA build, I added:
```json
  "cuda": {
      "description": "Use GPU",
      "dependencies": [
          "cudnn",
          "nccl"
      ]
    },
```
to the `features` section in `libtorch/vcpkg.json` but get a problem with caffe2 build requiring and not finding the CMake target `torch::magma`. I suspect the CUDA build is a work in progress. I'm poking at it as time permits but perhaps we need a separate issue.
