### ISSUE TITLE
Build failure with CMake

### ISSUE THREAD

**Issue by Snavellet** [microsoft/vcpkg#29457]
## Host Environment

- OS: [Windows 11 using WSL (Ubuntu-22.04)]
- Compiler: Clang 14.0.0

## The issue

Firstly, I did `vcpkg install fmt --triplet x64-Linux` and everything worked properly. After that, I wrote some configurations in the top-level CMakeLists.txt to find the FMT package. Then, I linked FMT to my executable, and it was built successfully. However, when I include fmt, an error immediately occured.

**Top-level CMakeLists.txt**
![1](https://user-images.githubusercontent.com/51810664/216830121-709f4aab-36f0-4b0f-9d1e-f6312cc59986.png)

**CMakeLists.txt in the `app` subdirectory**
![2](https://user-images.githubusercontent.com/51810664/216830067-9062473e-1498-4723-b495-71307de03ad0.png)

**Main.cpp, the executable that will be generated from; it also shows the error of including FMT**
![3](https://user-images.githubusercontent.com/51810664/216830070-41c74f71-35c3-4981-a8fb-5f6e346fb522.png)

**Even the IDE managed to suggest FMT, meaning that it knows it exists**
![4](https://user-images.githubusercontent.com/51810664/216830071-e571c95c-a12c-4250-a502-30baf5bfa15c.png)

**Further evidence of the package already installed**
![5](https://user-images.githubusercontent.com/51810664/216830072-2bc74663-da49-4268-be2a-f684f1320dbb.png)

## The zip file if you want to inspect
[hp_bot.zip](https://github.com/microsoft/vcpkg/files/10611495/hp_bot.zip)

**Comment by Cheney-W** [comment]
In vcpkg, fmt is a folder name instead of a header name, if you want to use the header files of fmt, please use as below:
`#include<fmt/xxx.h>`

**Comment by Cheney-W** [comment]
Hope your issue gets resolved.
