### ISSUE TITLE
[seacas] Build error

### ISSUE THREAD

**Issue by xhy576704731** [microsoft/vcpkg#29456]
**Host Environment**

- OS: Windows
- Compiler: revision

**To Reproduce**

`./vcpkg install seacas:x64-windows`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.
[issue_body.md](https://github.com/microsoft/vcpkg/files/10611378/issue_body.md)

**Comment by xhy576704731** [comment]
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/10611415/install-x64-windows-dbg-out.log)

**Comment by Neumann-A** [comment]
might just be a simple `include` missing. Port was tested with VS2022

```
e:\code\vcpkg\buildtrees\seacas\src\76a825bc51-907a76ce33.clean\packages\seacas\libraries\ioss\src\text_mesh\Iotm_TextMeshFuncs.h(66): error C2039: 'isspace': is not a member of 'std'
D:\Program Files\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\numeric(14): note: see declaration of 'std'
e:\code\vcpkg\buildtrees\seacas\src\76a825bc51-907a76ce33.clean\packages\seacas\libraries\ioss\src\text_mesh\Iotm_TextMeshFuncs.h(68): error C2039: 'isspace': is not a member of 'std'
D:\Program Files\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\numeric(14): note: see declaration of 'std'
e:\code\vcpkg\buildtrees\seacas\src\76a825bc51-907a76ce33.clean\packages\seacas\libraries\ioss\src\text_mesh\Iotm_TextMeshFuncs.h(106): error C2039: 'isdigit': is not a member of 'std'
D:\Program Files\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\numeric(14): note: see declaration of 'std'
```

**Comment by xhy576704731** [comment]
> 

So I should modify the file Iotm_TextMeshFuncs.h?

**Comment by Bzz2745** [comment]
other error appeared with vc143 :
OS:Windows11
complier:msvc vc143

To Reproduce

Steps to reproduce the behavior:

`.\vcpkg install seacas:x64-windows`

Failure logs

-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: D:/ProgramFiles/CMake/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: D:/vcpkg/buildtrees/seacas/x64-windows-dbg
    See logs for more information:
      D:\vcpkg\buildtrees\seacas\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/seacas/portfile.cmake:75 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)


error: building seacas:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+seacas
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[seacas]+Build+error
Include '[seacas] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 0ba60bfef 2023-02-03 (2 days ago)
Additional context
D:\vcpkg\buildtrees\seacas\src\76a825bc51-907a76ce33.clean\packages\seacas\libraries\ioss\src\exodus\Ioex_DecompositionData.C(1910): error C2039: 'MY_Alltoallv': is not a member of 'Ioss'
D:\vcpkg\buildtrees\seacas\src\76a825bc51-907a76ce33.clean\packages\seacas\libraries\ioss\src\exodus/Ioex_Utils.h(33): note: see declaration of 'Ioss'
D:\vcpkg\buildtrees\seacas\src\76a825bc51-907a76ce33.clean\packages\seacas\libraries\ioss\src\exodus\Ioex_DecompositionData.C(1838): note: while compiling class template member function 'void Ioex::DecompositionData<int>::create_implicit_global_map(const std::vector<int,std::allocator<int>> &,std::vector<int64_t,std::allocator<int64_t>> &,Ioss::Map &,int64_t *,int64_t *)'
D:\vcpkg\buildtrees\seacas\src\76a825bc51-907a76ce33.clean\packages\seacas\libraries\ioss\src\exodus\Ioex_DecompositionData.C(1910): error C3861: 'MY_Alltoallv': identifier not found
D:\vcpkg\buildtrees\seacas\src\76a825bc51-907a76ce33.clean\packages\seacas\libraries\ioss\src\exodus\Ioex_DecompositionData.C(1921): error C2039: 'MY_Alltoallv': is not a member of 'Ioss'
D:\vcpkg\buildtrees\seacas\src\76a825bc51-907a76ce33.clean\packages\seacas\libraries\ioss\src\exodus/Ioex_Utils.h(33): note: see declaration of 'Ioss'
D:\vcpkg\buildtrees\seacas\src\76a825bc51-907a76ce33.clean\packages\seacas\libraries\ioss\src\exodus\Ioex_DecompositionData.C(1921): error C3861: 'MY_Alltoallv': identifier not found
D:\vcpkg\buildtrees\seacas\src\76a825bc51-907a76ce33.clean\packages\seacas\libraries\ioss\src\exodus\Ioex_DecompositionData.C(1620): warning C4244: 'argument': conversion from 'T' to 'size_t', possible loss of data

**Comment by MonicaLiu0311** [comment]
@Bzz2745 
Thanks very much for your feedback🌻, can you please re-open an issue? We'd better do one process for one problem (or problems caused by the same reason).

**Comment by Bzz2745** [comment]
> @Bzz2745 Thanks very much for your feedback🌻, can you please re-open an issue? We'd better do one process for one problem (or problems caused by the same reason).

OK，I have already open an issue,thanks.

**Comment by MonicaLiu0311** [comment]
> So I should modify the file Iotm_TextMeshFuncs.h?

I can't reproduce your problem locally, can you please modify the `ctype.h` in `Iotm_TextMeshFuncs.h` to `cctype`, and try again?

`#include <ctype.h> // for toupper`
    ↓↓↓
`#include <cctype> // for toupper, isspace, isdigit`

You can use [`--editable`](https://github.com/microsoft/vcpkg/blob/master/docs/commands/install.md#--editable) in classic mode to preserve source code changes in `buildtree/`.

**Comment by xhy576704731** [comment]
> 

It did work!!! Thanks a lot!!!

**Comment by MonicaLiu0311** [comment]
Thanks for your verification, a request has been made upstream: https://github.com/sandialabs/seacas/issues/367

**Comment by Neumann-A** [comment]
> Thanks for your verification, a request has been made upstream: https://github.com/sandialabs/seacas/issues/367

Why are we waiting for upstream here ? As far as the maintainer rules are concerned simple include corrections are directly allowed.
