### ISSUE TITLE
add ismrmrd

### ISSUE THREAD

**Issue by congzhangzh** [Microsoft/vcpkg#2945]
https://github.com/ismrmrd/ismrmrd

ISMRM Raw Data Format (ISMRMRD):

A prerequisite for sharing magnetic resonance (imaging) reconstruction algorithms and code is a common raw data format. This document describes such a common raw data format and attempts to capture the data fields that are require to describe enough details about the magnetic resonance experiment to reconstruct images from the data. This standard was developed by a subcommittee of the ISMRM Sedona 2013 workshop. Please see the ISMRMRD Documentation for more information.

**Comment by ras0219-msft** [comment]
Thanks for making the PR!
