### ISSUE TITLE
[ seacas]:x64-windows build failure

### ISSUE THREAD

**Issue by Bzz2745** [microsoft/vcpkg#29462]
other error appeared with vc143 :
OS:Windows11
complier:msvc vc143

To Reproduce

.\vcpkg install seacas:x64-windows

Failure logs

-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
Command failed: D:/ProgramFiles/CMake/bin/cmake.exe --build . --config Debug --target install -- -v -j13
Working Directory: D:/vcpkg/buildtrees/seacas/x64-windows-dbg
See logs for more information:
D:\vcpkg\buildtrees\seacas\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
ports/seacas/portfile.cmake:75 (vcpkg_cmake_install)
scripts/ports.cmake:147 (include)

error: building failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with git pull and vcpkg update.
Then check for known issues at:
https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+seacas
You can submit a new issue at:
[https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[seacas]+Build+error](https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=%5Bseacas%5D+Build+error)
Include '[seacas] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
vcpkg-scripts version: https://github.com/microsoft/vcpkg/commit/0ba60bfef5dea4cb2599daa7ad8364e309835a68 2023-02-03 (2 days ago)

Additional context

D:\vcpkg\buildtrees\seacas\src\76a825bc51-907a76ce33.clean\packages\seacas\libraries\ioss\src\exodus\Ioex_DecompositionData.C(1910): error C2039: 'MY_Alltoallv': is not a member of 'Ioss'
D:\vcpkg\buildtrees\seacas\src\76a825bc51-907a76ce33.clean\packages\seacas\libraries\ioss\src\exodus/Ioex_Utils.h(33): note: see declaration of 'Ioss'
D:\vcpkg\buildtrees\seacas\src\76a825bc51-907a76ce33.clean\packages\seacas\libraries\ioss\src\exodus\Ioex_DecompositionData.C(1838): note: while compiling class template member function 'void Ioex::DecompositionData::create_implicit_global_map(const std::vector<int,std::allocator> &,std::vector<int64_t,std::allocator<int64_t>> &,Ioss::Map &,int64_t *,int64_t *)'
D:\vcpkg\buildtrees\seacas\src\76a825bc51-907a76ce33.clean\packages\seacas\libraries\ioss\src\exodus\Ioex_DecompositionData.C(1910): error C3861: 'MY_Alltoallv': identifier not found
D:\vcpkg\buildtrees\seacas\src\76a825bc51-907a76ce33.clean\packages\seacas\libraries\ioss\src\exodus\Ioex_DecompositionData.C(1921): error C2039: 'MY_Alltoallv': is not a member of 'Ioss'
D:\vcpkg\buildtrees\seacas\src\76a825bc51-907a76ce33.clean\packages\seacas\libraries\ioss\src\exodus/Ioex_Utils.h(33): note: see declaration of 'Ioss'
D:\vcpkg\buildtrees\seacas\src\76a825bc51-907a76ce33.clean\packages\seacas\libraries\ioss\src\exodus\Ioex_DecompositionData.C(1921): error C3861: 'MY_Alltoallv': identifier not found
D:\vcpkg\buildtrees\seacas\src\76a825bc51-907a76ce33.clean\packages\seacas\libraries\ioss\src\exodus\Ioex_DecompositionData.C(1620): warning C4244: 'argument': conversion from 'T' to 'size_t', possible loss of dataother error appeared with vc143 :
OS:Windows11
complier:msvc vc143

To Reproduce

.\vcpkg install seacas:x64-windows

Failure logs

-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
Command failed: D:/ProgramFiles/CMake/bin/cmake.exe --build . --config Debug --target install -- -v -j13
Working Directory: D:/vcpkg/buildtrees/seacas/x64-windows-dbg
See logs for more information:
D:\vcpkg\buildtrees\seacas\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
ports/seacas/portfile.cmake:75 (vcpkg_cmake_install)
scripts/ports.cmake:147 (include)

error: building seacas:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with git pull and vcpkg update.
Then check for known issues at:
https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+seacas
You can submit a new issue at:
[https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[seacas]+Build+error](https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=%5Bseacas%5D+Build+error)
Include '[seacas] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
vcpkg-scripts version: https://github.com/microsoft/vcpkg/commit/0ba60bfef5dea4cb2599daa7ad8364e309835a68 2023-02-03 (2 days ago)
Additional context
D:\vcpkg\buildtrees\seacas\src\76a825bc51-907a76ce33.clean\packages\seacas\libraries\ioss\src\exodus\Ioex_DecompositionData.C(1910): error C2039: 'MY_Alltoallv': is not a member of 'Ioss'
D:\vcpkg\buildtrees\seacas\src\76a825bc51-907a76ce33.clean\packages\seacas\libraries\ioss\src\exodus/Ioex_Utils.h(33): note: see declaration of 'Ioss'
D:\vcpkg\buildtrees\seacas\src\76a825bc51-907a76ce33.clean\packages\seacas\libraries\ioss\src\exodus\Ioex_DecompositionData.C(1838): note: while compiling class template member function 'void Ioex::DecompositionData::create_implicit_global_map(const std::vector<int,std::allocator> &,std::vector<int64_t,std::allocator<int64_t>> &,Ioss::Map &,int64_t *,int64_t *)'
D:\vcpkg\buildtrees\seacas\src\76a825bc51-907a76ce33.clean\packages\seacas\libraries\ioss\src\exodus\Ioex_DecompositionData.C(1910): error C3861: 'MY_Alltoallv': identifier not found
D:\vcpkg\buildtrees\seacas\src\76a825bc51-907a76ce33.clean\packages\seacas\libraries\ioss\src\exodus\Ioex_DecompositionData.C(1921): error C2039: 'MY_Alltoallv': is not a member of 'Ioss'
D:\vcpkg\buildtrees\seacas\src\76a825bc51-907a76ce33.clean\packages\seacas\libraries\ioss\src\exodus/Ioex_Utils.h(33): note: see declaration of 'Ioss'
D:\vcpkg\buildtrees\seacas\src\76a825bc51-907a76ce33.clean\packages\seacas\libraries\ioss\src\exodus\Ioex_DecompositionData.C(1921): error C3861: 'MY_Alltoallv': identifier not found
D:\vcpkg\buildtrees\seacas\src\76a825bc51-907a76ce33.clean\packages\seacas\libraries\ioss\src\exodus\Ioex_DecompositionData.C(1620): warning C4244: 'argument': conversion from 'T' to 'size_t', possible loss of data

**Comment by Adela0814** [comment]
@Bzz2745  Please provide the full failure log: `D:\vcpkg\buildtrees\seacas\install-x64-windows-dbg-out.log`. Thnaks.

**Comment by Bzz2745** [comment]
> @Bzz2745 Please provide the full failure log: `D:\vcpkg\buildtrees\seacas\install-x64-windows-dbg-out.log`. Thnaks.

It is too long,I can't upload it by commet.Could you provide me any email,thanks.

**Comment by Adela0814** [comment]
Attachments are supported here, just drag and drop your log files to the comment box.

**Comment by Bzz2745** [comment]
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/10671060/install-x64-windows-dbg-out.log)

**Comment by Bzz2745** [comment]
> Attachments are supported here, just drag and drop your log files to the comment box.

I have already uploaded it.

**Comment by Adela0814** [comment]
I'm not able to repro this issue in my local.

**Comment by Bzz2745** [comment]
> I'm not able to repro this issue in my local.

emmm,the error still existing......I really don't know anything wrong.
