### ISSUE TITLE
`HTTPS_PROXY` and `HTTP_PROXY` not working again on windows

### ISSUE THREAD

**Issue by shithappens2016** [microsoft/vcpkg#29469]
vcpkg can't download cmake through proxy.having to use `VCPKG_FORCE_SYSTEM_BINARIES` every time is very annoying.

**Comment by shithappens2016** [comment]
@FrankXie05
Even if HTTPS_PROXY and HTTPS_PROXY are set, vcpkg will not be downloaded through a proxy. This is not a question.

**Comment by FrankXie05** [comment]
@shithappens2016 Sorry for the wrong tag, could you  please provide the error log and steps to reproduce? :)

**Comment by JackBoosY** [comment]
Did you reboot your computer after set the environment vars?
