### ISSUE TITLE
[icu] Conflict feature

### ISSUE THREAD

**Issue by xiaozhuai** [microsoft/vcpkg#29463]
`icu` has a feature `tools` which is not default.
https://github.com/microsoft/vcpkg/blob/0ba60bfef5dea4cb2599daa7ad8364e309835a68/ports/icu/vcpkg.json#L1-L23

There are many downstream ports depends on `icu`. For example:

### qt5-base
https://github.com/microsoft/vcpkg/blob/0ba60bfef5dea4cb2599daa7ad8364e309835a68/ports/qt5-base/vcpkg.json#L16-L23

### skia
https://github.com/microsoft/vcpkg/blob/0ba60bfef5dea4cb2599daa7ad8364e309835a68/ports/skia/vcpkg.json#L126-L131

Some of them require `tools` feature (eg: `qt5-base`) and the others (eg: `skia`) don't.

This cause conflicts.

If I install `skia` first, and then install `qt5-base`, I must rebuild `icu` which makes no sense.

--------------------------------------------------------
**Update:**
I searched all ports, here is a list. (selected means require `tools`)
The result is the only one port require `icu[tools]` feature is `qt5-base`.
Can this be removed from `qt5-base`?

- [x] qt5-base
- [ ] qtbase
- [ ] xerces-c
- [ ] nuspell
- [ ] libphonenumber
- [ ] boost-regex
- [ ] mongo-c-driver
- [ ] mapnik
- [ ] libical
- [ ] itk
- [ ] libpq
- [ ] qtwebengine
- [ ] boost-locale
- [ ] dcmtk
- [ ] libmysql
- [ ] cppcms
- [ ] libe57
- [ ] tesseract
- [ ] harfbuzz
- [ ] skia
- [ ] v8

--------------------------------------------------------
**Update:**
This issue was introduced by #29196

**Comment by xiaozhuai** [comment]
@m-kuhn Could you please explain why `tools` feature is needed by `qt5-base`?

**Comment by m-kuhn** [comment]
Iirc it helped mitigate an issue with windows-x86 but that might be solved better by https://github.com/microsoft/vcpkg/pull/29329

**Comment by xiaozhuai** [comment]
> Iirc it helped mitigate an issue with windows-x86 but that might be solved better by #29329

#29329 is not same problem with this issue. We are talking about conflict feature for `qt5-base` and other ports.
If `icu[tools]` feature is not a hard dependencies for `qt5-base`, then it should be dropped to solve the conflicts.
Otherwise, please explain why `qt5-base` requires `icu[tools]`, then we could solve the conflicts in another better way.

**Comment by m-kuhn** [comment]
@xiaozhuai ci was failing for `windows-x86`, I assume it will also fail for https://github.com/microsoft/vcpkg/pull/29464 (if not, it's good to merge).

**Comment by xiaozhuai** [comment]
> @xiaozhuai ci was failing for `windows-x86`, I assume it will also fail for #29464 (if not, it's good to merge).

What are you talking about? #29464 is not a competitive pr with #29329. They solve diffrent problems. Please read this issue in details.

**Comment by dg0yt** [comment]
> Some of them require `tools` feature (eg: `qt5-base`) and the others (eg: `skia`) don't.
> 
> This cause conflicts.

Can you please explain where you see a "conflict"?

> If I install `skia` first, and then install `qt5-base`, I must rebuild `icu` which makes no sense.

This is how vcpkg is designed. If you request another feature from an already installed port, the port must be rebuild. And every port which depends on it.

---

This are valid problems:
- Most actual dependencies on icu[tools] will probably need to be marked `"host": true`.
- Maybe some ports don't really depend on icu[tools].

**Comment by xiaozhuai** [comment]
@autoantwort @dg0yt I did some research and `qt5-base` doesn't need icu[tools] at all. And I've update #29464. 
If I'm correct, CI will pass on `x86-windows`.

**Comment by xiaozhuai** [comment]
Files in `packages\icu_x86-windows\bin`
```
.
├── icudt72.dll
├── icudt72.pdb
├── icuin72.dll
├── icuin72.pdb
├── icuio72.dll
├── icuio72.pdb
├── icuuc72.dll
└── icuuc72.pdb
```

Files in `packages\icu_x64-windows\bin`
```
.
├── icudt72.dll
├── icudt72.pdb
├── icuin72.dll
├── icuin72.pdb
├── icuio72.dll
├── icuio72.pdb
├── icutu72.dll
├── icutu72.pdb
├── icuuc72.dll
└── icuuc72.pdb
```

`icu:x86-windows` didn't even install `icutu` because it's tool utilities library.

**Comment by xiaozhuai** [comment]
@autoantwort @dg0yt CI has passed `qt5-base:x86-windows` guys,  I don't think I need to say more to prove it
```
Installing 279/398 qt5-base:x86-windows...
Building qt5-base[core]:x86-windows...
-- Figuring out qt target mkspec. Target arch x86
-- Target mkspec set to: win32-msvc
-- Host mkspec not set. Qt's own buildsystem will try to figure out the host system
-- Using cached qtbase-everywhere-opensource-src-5.15.8.tar.xz.
-- Extracting source D:/downloads/qtbase-everywhere-opensource-src-5.15.8.tar.xz
-- Applying patch patches/winmain_pro.patch
-- Applying patch patches/windows_prf.patch
-- Applying patch patches/qt_app.patch
-- Applying patch patches/gui_configure.patch
-- Applying patch patches/icu.patch
-- Applying patch patches/xlib.patch
-- Applying patch patches/egl.patch
-- Applying patch patches/mysql_plugin_include.patch
-- Applying patch patches/mysql-configure.patch
-- Applying patch patches/cocoa.patch
-- Applying patch patches/Qt5BasicConfig.patch
-- Applying patch patches/Qt5PluginTarget.patch
-- Applying patch patches/create_cmake.patch
-- Applying patch patches/Qt5GuiConfigExtras.patch
-- Applying patch patches/fix_angle.patch
-- Using source at D:/buildtrees/qt5-base/src/5.15.8-de9fd08330.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x86-windows
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at D:/downloads/tools/msys2/9a1ec3f33446b195
-- Configuring x86-windows-dbg
-- Configuring x86-windows-dbg done
-- Configuring x86-windows-rel
-- Configuring x86-windows-rel done
-- Using cached python-3.10.7-embed-win32.zip.
-- Building x86-windows-dbg
-- Fixing makefile installation path x86-windows-dbg
-- Installing x86-windows-dbg
-- Package x86-windows-dbg done
-- Building x86-windows-rel
-- Fixing makefile installation path x86-windows-rel
-- Installing x86-windows-rel
-- Package x86-windows-rel done
-- Installing: D:/packages/qt5-base_x86-windows/share/qt5-base/copyright
-- Performing post-build validation
```

**Comment by dg0yt** [comment]
IIUC the whole noise settled down to qt5-base incorrectly depending on `icu[tools]`. 
#29464 is probably the right fix for qt5-base but I wouldn't say it is obvious unless familiar with ICU components.
Still, I don't see any conflict, just an excess dependency.

**Comment by xiaozhuai** [comment]
@dg0yt @autoantwort @m-kuhn 
Ok guys.
Maybe I didn't express my point clearly. I'm sorry for that.
And @dg0yt , help me a lot and give many good suggestion on my other pr too. I appreciate it.

So please let me explain my point of view in detail again.
What I'm trying to say is that the dependencies of the library should not diverge for the **default**.
The point of this problem is that the **default**.
`vcpkg` is a product for users, for C/C++ developers who love it, right?


> This is how vcpkg is designed. If you request another feature from an already installed port, the port must be rebuild. And every port which depends on it.

As @dg0yt said, I know it's by design, but that is just repeating my problem.
I knew it, you knew it, but I didn't like it. I'm just a user of `vcpkg` and also a contributor who wants to feed back `vcpkg`.
User want to install `skia` and then install `qt5-base`, but the second installation won't process because `icu` need to be rebuild. Please note that user did not configure any additional features. It's just as simple as
```
vcpkg install skia
vcpkg install qt5-base
```
But it will tell you, no you can't install `qt5-base` unless you rebuild icu. User may not even care `icu`.
If user are first to vcpkg, this gave the first feeling that vcpkg may not be handling dependencies correctly. 

What I understand about `This is how vcpkg is designed`.
1. For the default case, that is, when the user does not provide additional features, there should be no dependency divergence. That's what most package manger did.
2. For special cases, when users really need to provide some features, dependency divergence is inevitable. vcpkg won't stop you from doing this, but you need to rebuild `xxx`, that make sense. And that's what vcpkg bring us, more choice.

User does not customize any features by default, just installing two packages and it cause rebuilding of dependencies. That's why I think it's a **conflict**.

If the first point (default case) is not handled well, then the second point is meanless. This defeats the original intent.

People find problems and then they fix them. You can't fix a problem that you don't even think is a problem.
I ran into this problem, if I thought this was reasonable, I wouldn't have found out that the real problem was `just an excess dependency`.
My original intention was to resolve dependency divergence in the **default** case.

Much has been said here, of course, these are my personal opinions, some agree and some disagree. 
It's like Trump running for president.

I just want to make vcpkg great again.

**Comment by dg0yt** [comment]
I would really prefer if the discussion was kept technical.

What is great for one use case may be bad for others. Default features already are a hot topic in vcpkg. Some people would prefer vcpkg to not pull in too many features with all their dependencies, by default. OTOH starting with minimal features is more likely to cause rebuilds when installing more ports. You have to find a good balance. YMMV.

- In any case, there are situations where the default features of one package are not enough for building another package.
- vcpkg puts libraries first, tools second. This wasn't implemented in port icu until recently.
- And then there are port bugs. Here in qt5-base.

**Comment by xiaozhuai** [comment]
> I would really prefer if the discussion was kept technical.

Of course it is. The Trump part is just a joke. I myself do not have any political position. Take it easy.
