### ISSUE TITLE
[vcpkg-tool-gn] Build error

### ISSUE THREAD

**Issue by wuxianggujun** [microsoft/vcpkg#29465]
Elapsed time to handle vcpkg-cmake-get-vars:x64-windows: 103.5 ms
Installing 7/10 vcpkg-tool-gn:x64-windows...
Building vcpkg-tool-gn[core]:x64-windows...
-- Downloading https://chrome-infra-packages.appspot.com/dl/gn/gn/windows-amd64/+/q5ExVHmXyD34Q_Tzb-aRxsPipO-e37-csVRhVM7IJh0C -> gn-windows-amd64.zip...
[DEBUG] To include the environment variables in debug output, pass --debug-env
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:273 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/vcpkg-tool-gn/portfile.cmake:45 (vcpkg_download_distfile)
  scripts/ports.cmake:147 (include)

```
error: building vcpkg-tool-gn:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+vcpkg-tool-gn
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[vcpkg-tool-gn]+Build+error
Include '[vcpkg-tool-gn] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 0ba60bfef 2023-02-03 (2 days ago)
```

**Comment by Cheney-W** [comment]
Thanks for reporting this issue to us!
Could you please provide me with the error logs which saved in `\vcpkg\buildtrees\vcpkg-tool-gn` folder?

**Comment by Cheney-W** [comment]
Thanks for posting this issue. Please reopen this issue and provide us with the detailed info of this issue if it is still a problem for you.
