### ISSUE TITLE
[New Port Request] open-dis-cpp

### ISSUE THREAD

**Issue by wadehunk** [microsoft/vcpkg#29471]
Library name: open-dis-cpp

Library description: A C++ implementation of the Distributed Interactive Simulation (DIS) IEEE 1278 standard

Source repository URL: https://github.com/open-dis/open-dis-cpp

Project homepage (if different from the source repository): https://www.open-dis.org

Anything else that is useful to know when adding (such as optional features the library may have that should be included): Implementations for DISv6 and DISv7 standards definitions.

**Comment by ASxa86** [comment]
My team would definitely enjoy having this port in vcpkg.
