### ISSUE TITLE
Build Failed: building colmap:x64-windows

### ISSUE THREAD

**Issue by monadical** [microsoft/vcpkg#29486]
I'm building COLMAP via their vcpkg install instructions on Windows 11 with CUDA 12.0. I suspect they're expecting CUDA 10.x and that's the issue. If so, would be nice to detect that dependency issue. If not, let us know what might else be wrong. The associated error log file is attached. The main error is:

cmd.exe /C "cd /D C:\dev\vcpkg\buildtrees\colmap\x64-windows-dbg\lib\SiftGPU\CMakeFiles\sift_gpu.dir && "C:\Program Files\CMake\bin\cmake.exe" -E make_directory C:/dev/vcpkg/buildtrees/colmap/x64-windows-dbg/lib/SiftGPU/CMakeFiles/sift_gpu.dir//. && "C:\Program Files\CMake\bin\cmake.exe" -D verbose:BOOL=OFF -D build_configuration:STRING=Debug -D generated_file:STRING=C:/dev/vcpkg/buildtrees/colmap/x64-windows-dbg/lib/SiftGPU/CMakeFiles/sift_gpu.dir//./sift_gpu_generated_ProgramCU.cu.obj -D generated_cubin_file:STRING=C:/dev/vcpkg/buildtrees/colmap/x64-windows-dbg/lib/SiftGPU/CMakeFiles/sift_gpu.dir//./sift_gpu_generated_ProgramCU.cu.obj.cubin.txt -P C:/dev/vcpkg/buildtrees/colmap/x64-windows-dbg/lib/SiftGPU/CMakeFiles/sift_gpu.dir//sift_gpu_generated_ProgramCU.cu.obj.Debug.cmake"
ProgramCU.cu

[follwed by 100+ errors like:]
C:\dev\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\SiftGPU\ProgramCU.cu(101): error: texture is not a template

C:\dev\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\SiftGPU\ProgramCU.cu(102): error: texture is not a template

C:\dev\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\SiftGPU\ProgramCU.cu(103): error: texture is not a template

C:\dev\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\SiftGPU\ProgramCU.cu(104): error: texture is not a template

C:\dev\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\SiftGPU\ProgramCU.cu(105): error: texture is not a template

C:\dev\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\SiftGPU\ProgramCU.cu(106): error: texture is not a template

C:\dev\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\SiftGPU\ProgramCU.cu(133): error: no instance of overloaded function "tex1Dfetch" matches the argument list
            argument types are: (<error-type>, int)

C:\dev\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\SiftGPU\ProgramCU.cu(191): error: no instance of overloaded function "tex1Dfetch" matches the argument list
            argument types are: (<error-type>, int)

C:\dev\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\SiftGPU\ProgramCU.cu(235): error: no instance of overloaded function "tex1Dfetch" matches the argument list
            argument types are: (<error-type>, int)

C:\dev\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\SiftGPU\ProgramCU.cu(236): error: no instance of overloaded function "tex1Dfetch" matches the argument list
            argument types are: (<error-type>, int)

C:\dev\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\SiftGPU\ProgramCU.cu(238): error: no instance of overloaded function "tex1Dfetch" matches the argument list
            argument types are: (<error-type>, int)

C:\dev\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\SiftGPU\ProgramCU.cu(239): error: no instance of overloaded function "tex1Dfetch" matches the argument list
            argument types are: (<error-type>, int)

C:\dev\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\SiftGPU\ProgramCU.cu(253): error: no instance of overloaded function "tex1Dfetch" matches the argument list
            argument types are: (<error-type>, int)

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/10670465/install-x64-windows-dbg-out.log)

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This error looks like upstream issue, now colmap:x64-windows build failed with Visual Studio 2022 on vcpkg, this is a VS bug. Waiting for upstream response in https://github.com/colmap/colmap/issues/1795.

**Comment by monadical** [comment]
Yes, it's been tracked down over on the colmap project to be mostly a problem in their CUDA code where they're not up to date with 12.0. Also a minor bug in VS22 that is separately filed. So we can close this bug here.
