### ISSUE TITLE
ffmpeg[qsv] on linux

### ISSUE THREAD

**Issue by chuckypt** [microsoft/vcpkg#29489]
**Host Environment**

- OS:  linux centos stream 8
- Compiler:  x64-linux

**To Reproduce**

 ./vcpkg  install ffmpeg[qsv]:x64-linux

**Failure logs**

mfx-dispatch[core]:x64-linux is only supported on '!linux & !uwp & !osx'
 
**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

hi ,i can't build ffmpeg with qsv on linux ,  it's a bug??

[root@localhost ffmpeg]# cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 94
model name      : Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz

[root@localhost ffmpeg]# uname -ar
Linux localhost.localdomain 4.18.1 #3 SMP Fri May 20 14:42:13 CST 2022 x86_64 x86_64 x86_64 GNU/Linux

[root@localhost ffmpeg]# cat /etc/redhat-release
CentOS Stream release 8
 
[root@localhost ffmpeg]# vainfo
error: can't connect to X server!
libva info: VA-API version 1.13.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_13
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.13 (libva 2.5.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 22.1.1 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointStats
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointFEI
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointFEI
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointFEI
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointFEI
[root@localhost ffmpeg]# vainfo

**Comment by FrankXie05** [comment]
@cnSchwarzer what you think? The official display supports linux. Why add it? 
https://github.com/microsoft/vcpkg/blob/185a7aa23ac037d711a2a87d5e8d99e7131dbcd8/ports/mfx-dispatch/vcpkg.json#L8

**Comment by cnSchwarzer** [comment]
> @cnSchwarzer what you think? The official display supports linux. Why add it? 
> 
> https://github.com/microsoft/vcpkg/blob/185a7aa23ac037d711a2a87d5e8d99e7131dbcd8/ports/mfx-dispatch/vcpkg.json#L8

Oops, I will add it now.

**Comment by cnSchwarzer** [comment]
I reminded that I didn't ever test for linux, so I disabled linux support.

**Comment by chuckypt** [comment]
> I reminded that I didn't ever test for linux, so I disabled linux support.

 i guess on linux  ,ffmpeg[qsv] don't need  depend mfx-dispatch.

**Comment by chuckypt** [comment]
i  edit ffmpeg/vcpkg.json
before
 "qsv": {
      "description": "Intel QSV Codec",
      "dependencies": [
        "mfx-dispatch"
      ]
    },
after:
 "qsv": {
      "description": "Intel QSV Codec"
    },

finish  build success!
