### ISSUE TITLE
[libpq] Build error

### ISSUE THREAD

**Issue by KaiTang2** [microsoft/vcpkg#29490]
**Host Environment**

- OS:windows11 x64
- Compiler: revision

**To Reproduce**

vcpkg.exe install osg:x64-windows

**Failure logs**

vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 185a7aa23 2023-02-06 (6 hours ago)

CMake Deprecation Warning at scripts/ports.cmake:77 (message):
  vcpkg_apply_patches has been deprecated in favor of the `PATCHES` argument
  to `vcpkg_from_*`.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_apply_patches.cmake:2 (z_vcpkg_deprecation_message)
  ports/libpq/portfile.cmake:100 (vcpkg_apply_patches)
  scripts/ports.cmake:147 (include)

-- Applying patch patches/windows/Solution_RELEASE.patch
-- Applying patch patches/windows/python3_build_RELEASE.patch
-- Patches applied!
-- Building libpq x64-windows-RELEASE...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: E:/GitHub/vcpkg/downloads/tools/perl/5.32.1.1/perl/bin/perl.exe build.pl RELEASE libpq
    Working Directory: E:/GitHub/vcpkg/buildtrees/libpq/x64-windows-rel/src/tools/msvc
    Error code: 1
    See logs for more information:
      E:\GitHub\vcpkg\buildtrees\libpq\build-libpq-x64-windows-RELEASE-out.log

Call Stack (most recent call first):
  ports/libpq/portfile.cmake:199 (vcpkg_execute_required_process)
  scripts/ports.cmake:147 (include)

[build-libpq-x64-windows-RELEASE-out.log](https://github.com/microsoft/vcpkg/files/10670913/build-libpq-x64-windows-RELEASE-out.log)

**Comment by KaiTang2** [comment]
Is there somebody help me to solve it?

**Comment by KaiTang2** [comment]
Is there somebody help me to solve this issues?

**Comment by KaiTang2** [comment]
I changed the TMP and TEMP paths in the environment variables to pure English, then solved the problem

**Comment by tutorial19** [comment]
@KaiTang2 i dont understand what did you do ??

**Comment by tutorial19** [comment]
@KaiTang2 i dont understand how you fixed your issue ,what is it you changed about TEMP and TMP??

**Comment by KaiTang2** [comment]
@tutorial19 You can find TMP and TEMP in environment variable.
