### ISSUE TITLE
[<libyuv>] build failure

### ISSUE THREAD

**Issue by 291598912** [microsoft/vcpkg#29494]
D:\workspace\project\thirdparty\vcpkg>.\vcpkg install libyuv:x64-windows-static
Computing installation plan...
The following packages will be built and installed:
    libyuv[core]:x64-windows-static -> 1857
Detecting compiler hash for triplet x64-windows-static...
Restored 0 package(s) from C:\Users\58497\AppData\Local\vcpkg\archives in 142.3 us. Use --debug to see more details.
Installing 1/1 libyuv:x64-windows-static...
Building libyuv[core]:x64-windows-static...
-- Fetching https://chromium.googlesource.com/libyuv/libyuv 0faf8dd0e004520a61a603a4d2996d5ecc80dc3f...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files (x86)/Git/cmd/git.exe" fetch https://chromium.googlesource.com/libyuv/libyuv 0faf8dd0e004520a61a603a4d2996d5ecc80dc3f --depth 1 -n
    Working Directory: D:/workspace/project/thirdparty/vcpkg/downloads/git-tmp
    Error code: 128
    See logs for more information:
      D:\workspace\project\thirdparty\vcpkg\buildtrees\libyuv\git-fetch-x64-windows-static-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_git.cmake:86 (vcpkg_execute_required_process)
  ports/libyuv/portfile.cmake:3 (vcpkg_from_git)
  scripts/ports.cmake:147 (include)

error: building libyuv:x64-windows-static failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libyuv
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libyuv]+Build+error
Include '[libyuv] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 185a7aa23 2023-02-06 (13 hours ago)

**Comment by 291598912** [comment]
fatal: unable to access 'https://chromium.googlesource.com/libyuv/libyuv/': Failed to connect to chromium.googlesource.com port 443 after 21095 ms: Timed out

**Comment by Adela0814** [comment]
You may need to use proxy to download the source. 

Or try the following solution:
https://zhuanlan.zhihu.com/p/383683670
