### ISSUE TITLE
building qtdeclarative:x64-windows failed

### ISSUE THREAD

**Issue by dotNetTest** [microsoft/vcpkg#29513]
**Host Environment**

- OS: [Windows]
- Compiler: VS2022

`./vcpkg install qt`

**Failure logs**
larative-everywhere-src-6.4.2.tar.xz...
-- Extracting source G:/vcpkg/downloads/qtdeclarative-everywhere-src-6.4.2.tar.xz
-- Using source at G:/vcpkg/buildtrees/qtdeclarative/src/here-src-6-a31aea0fcd.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Release --target install -- -v -j17
    Working Directory: G:/vcpkg/buildtrees/qtdeclarative/x64-windows-rel
    See logs for more information:
      G:\vcpkg\buildtrees\qtdeclarative\install-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  installed/x64-windows/share/qtbase/qt_install_submodule.cmake:337 (vcpkg_cmake_install)
  ports/qtdeclarative/portfile.cmake:22 (qt_install_submodule)
  scripts/ports.cmake:147 (include)
error: building qtdeclarative:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qtdeclarative
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[qtdeclarative]+Build+error
Include '[qtdeclarative] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 17030920a 2023-01-31 (7 days ago)

**Comment by MonicaLiu0311** [comment]
Please provide the following log:
```
See logs for more information:
G:\vcpkg\buildtrees\qtdeclarative\install-x64-windows-rel-out.log
```

**Comment by MonicaLiu0311** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
