### ISSUE TITLE
How can I update a port myself?

### ISSUE THREAD

**Issue by FAKERINHEART** [microsoft/vcpkg#29517]
I have seen a lot of issues for update ports.
For example, the update issue of grpc: https://github.com/microsoft/vcpkg/pull/28964.
It has a lot of `diff cmakefiles`, 
![image](https://user-images.githubusercontent.com/13352188/217430031-22d7bce7-4937-490f-a0fb-16f727830003.png)

but I don't know how to generate them.

Is there any documentation to learn about it?

Thank you.

**Comment by xiaozhuai** [comment]
Just use `git diff`.
If you are in a git repo, you can make changes and then `git diff > /path/to/ports/xxxx.patch`.
If you are not in a git repo, you may need `git diff --no-index`.

**Comment by JackBoosY** [comment]
1. Remove patch usage in _portfile.cmake_.
2. Run install command with `--editable`
3. cd to _VCPKG_ROOT/buildtrees/<PORT>/src/<CODE_ROOT>_
4. `git init .`
5. `git add .`
6. make changes.
7. `git commit -m <COMMIT_MESSAGE>`
8. `git diff > ../../../ports/<PORT>/<PATCH_NAME>.patch`
9. restore changes about patch usage.

**Comment by FAKERINHEART** [comment]
> 1. Remove patch usage in _portfile.cmake_.
> 2. Run install command with `--editable`
> 3. cd to _VCPKG_ROOT/buildtrees//src/<CODE_ROOT>_
> 4. `git init .`
> 5. `git add .`
> 6. make changes.
> 7. `git commit -m <COMMIT_MESSAGE>`
> 8. `git diff > ../../../ports/<PORT>/<PATCH_NAME>.patch`
> 9. restore changes about patch usage.

Okay, moreover, such multi-patch files in a port, like `grpc`, are added one-by-one by **commit** and **diff** until the port is compiled successfully in the end. Am I right?

**Comment by JackBoosY** [comment]
> @JackBoosY Okay, moreover, such multi-patch files in a port, like `grpc`, are added one-by-one by **commit** and **diff** until the port is compiled successfully in the end. Am I right?

If there are multiple patches, you just need to remove `.git` folder in _CODE_ROOT_ then re-do step 4 to step 8.

**Comment by FAKERINHEART** [comment]
> > @JackBoosY Okay, moreover, such multi-patch files in a port, like `grpc`, are added one-by-one by **commit** and **diff** until the port is compiled successfully in the end. Am I right?
> 
> If there are multiple patches, you just need to remove `.git` folder in _CODE_ROOT_ then re-do step 4 to step 8.

@JackBoosY Thank you~
I think that I need not remove .git folder, only need re-do 6-7 and use `git show` to replace `git diff`.
