### ISSUE TITLE
[qt5-base] OSX_DEPLOYMENT_TARGET seems not correct

### ISSUE THREAD

**Issue by xiaozhuai** [microsoft/vcpkg#29521]
**Describe the bug**
See this code
https://github.com/microsoft/vcpkg/blob/1c48ec7f49d69bb753e6afefba51368e18263255/ports/qt5-base/portfile.cmake#L281-L310

It sets `QMAKE_MACOSX_DEPLOYMENT_TARGET` env variable.
If `VCPKG_OSX_DEPLOYMENT_TARGET` is set, it's all good.
If not, it will detect sdk version and system version,
and pick `Major.Minor OSX system Version` as `VCPKG_OSX_DEPLOYMENT_TARGET`. That's all good.

And then see these lines. The comments said max version supported by qt is `10.15`. It's not true.
What log said `only support OSX_DEPLOYMENT_TARGET up to 10.15` exactly the opposite of what it does.
https://github.com/microsoft/vcpkg/blob/1c48ec7f49d69bb753e6afefba51368e18263255/ports/qt5-base/portfile.cmake#L301-L304

The content of `mkspecs/common/macx.conf`, as you can see the max sdk version is 12.
```conf
#
# qmake configuration for common OS X
#

QMAKE_PLATFORM         += macos osx macx
QMAKE_MAC_SDK           = macosx

QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.13

# Should be 10.15, but as long as the CI builds with
# older SDKs we have to keep this.
QT_MAC_SDK_VERSION_MIN = 10.14

QT_MAC_SDK_VERSION_MAX = 12

device.sdk = macosx
device.target = device
device.dir_affix = $${device.sdk}
device.CONFIG = $${device.sdk}
device.deployment_identifier = $${device.sdk}

CONFIG += only_active_arch

QMAKE_LIBS_VULKAN =

include(mac.conf)
```

And these lines, since env variable is set, perhaps these could be removed.
https://github.com/microsoft/vcpkg/blob/1c48ec7f49d69bb753e6afefba51368e18263255/ports/qt5-base/portfile.cmake#L307-L309

This issue is to discuss what the correct behavior of `OSX_DEPLOYMENT_TARGET` should be.

I'm not sure if I am right, so if someone knows about this, please post your suggestion.

--------------

**Update:**

I think the right behavior woule be :
1. Pick Major.Minor OSX system Version as `VCPKG_OSX_DEPLOYMENT_TARGET`.
2. Clamp `VCPKG_OSX_DEPLOYMENT_TARGET` by `QT_MAC_SDK_VERSION_MIN` (shoud be 10.15) and `QT_MAC_SDK_VERSION_MAX` (should be 12)

**Environment**
- OS: macos

**Comment by Neumann-A** [comment]
I think the value was simply not updated since Qt 5.15.2 https://github.com/qt/qtbase/blob/40143c189b7c1bf3c2058b77d00ea5c4e3be8b28/mkspecs/common/macx.conf#L15

Maybe vcpkg should simply read that file instead to set the max.

**Comment by xiaozhuai** [comment]
> I think the value was simply not updated since Qt 5.15.2 https://github.com/qt/qtbase/blob/40143c189b7c1bf3c2058b77d00ea5c4e3be8b28/mkspecs/common/macx.conf#L15
> 
> Maybe vcpkg should simply read that file instead to set the max.

It's 10.15~12 on qt 5.15 branch
https://github.com/qt/qtbase/blob/4ee4fc18b4067b90efa46ca9baba74f53b54d9ec/mkspecs/common/macx.conf#L12-L14

**Comment by Neumann-A** [comment]
> It's 10.15~12 on qt 5.15 branch

I know..... that is why i directly mentioned the 5.15.2 tag..... which was the last direct open release before qt6
