### ISSUE TITLE
VCG Library needed

### ISSUE THREAD

**Issue by comsyspro** [Microsoft/vcpkg#2952]
For building the openMVS project (https://github.com/cdcseacave/openMVS) on Windows the VCG Library (http://vcg.isti.cnr.it/vcglib/) is required. Please add this to the vcpkg project. Thank you.

**Comment by traversaro** [comment]
Related issue: https://github.com/Microsoft/vcpkg/issues/2382 .

**Comment by JackBoosY** [comment]
Hi @comsyspro , vcglib has been added in vcpkg.
