### ISSUE TITLE
[crashpad] Build Successful, crashpad_handler.exe doesn't work

### ISSUE THREAD

**Issue by haileemiu** [microsoft/vcpkg#29539]
**Describe the bug**
The build for my project succeeds without issues, then I copy the `crashpad_handler.exe` to the build dir (to co-locate with the binary). However, the `crashpad_handler.exe` doesn't seem to actually work (SDK in C++ won't successfully start the handler and running `."crashpad_handler.exe" -h` from the build dir doesn't output anything).

**Environment**
- OS: Windows
- Compiler: VS 2022 (amd64)

**To Reproduce**
I created a [Sample Repo](https://github.com/haileemiu/testpad) to demonstrate this issue in a simple form.
1. Clone repo w/ vcpkg submodule
2. (Using VS Code) Configure, Build, and Run project.
3. Will not work:
        a. Output will show that crashpad failed to launch (from SDK to `crashpad_handler.exe`)
        b. Crashpad binary won't run properly.

**Expected behavior**
Crashpad SDK should load handler successfully.

**Failure logs**
- There are no failures for the build.

**Additional context**
I've also tried to run the `crashpad_handler.exe` from `vcpkg/packages/crashpad_x64-windows/tools/crashpad_handler.exe` as well as `vcpkg/packages/crashpad_x64-windows/debug/tools/crashpad_handler.exe` and neither of those seem to work.

Any help would be appreciated!

**Comment by Adela0814** [comment]
@haileemiu Please confirm the `crashpad_handler.exe` in the [path](https://github.com/haileemiu/testpad/blob/main/src/main.cpp#:~:text=base%3A%3AFilePath%20handler(getPathRelativeToBinary(L%22crashpad_handler.exe%22))%3B).

**Comment by Adela0814** [comment]
1. Please copy the exe and dependencies from `${CURRENT_PACKAGES_DIR}/tools` to your specified path.
2. Please make sure the folder `crashpad_database` exists.
3. Re-run your project.
![image](https://user-images.githubusercontent.com/95600143/217782736-80247cf2-ca81-40e7-bb67-5b0dc0b1401d.png)

**Comment by haileemiu** [comment]
CURRENT_PACKAGES_DIR is unset so I don’t know how to get to the newly generated tools through CMake.

I tried manually copying the newly generated crashpad_handler to the path and it worked. Seems the issue was the lack of the zlib dll.

So the only issue now is getting CMake to copy both the handler and the DLL.


On Feb 9, 2023, at 2:10 AM, Mengna Li ***@***.***> wrote:

﻿

  1.  Please copy the exe and dependencies from ${CURRENT_PACKAGES_DIR}/tools to your specified path.
  2.  Please make sure the folder crashpad_database exists.
  3.  Re-run your project.
[image]<https://user-images.githubusercontent.com/95600143/217782736-80247cf2-ca81-40e7-bb67-5b0dc0b1401d.png>

**Comment by haileemiu** [comment]
@Adela0814 I can not get to that tool programmatically because `CURRENT_PACKAGES_DIR` is not set. How am I supposed to move crashpad to my output directory?
