### ISSUE TITLE
Add FastCDR 

### ISSUE THREAD

**Issue by traversaro** [Microsoft/vcpkg#2953]
It would be great to have a port for the FastCDR library ( https://github.com/eProsima/Fast-CDR ).
Non-core homebrew formula: https://github.com/PX4/homebrew-px4/blob/master/fastcdr.rb .

**Comment by ReyzalX** [comment]
I have add fastcdr in this pull request #2949 .
Maybe in the near future can be used.

**Comment by ras0219-msft** [comment]
Fixed in #2949. Thanks again @ReyzalX!
