### ISSUE TITLE
[vtk] Build error

### ISSUE THREAD

**Issue by QiuYilin** [microsoft/vcpkg#29544]
**Host Environment**

- OS: Windows10
- Compiler: VS2019

**To Reproduce**

`./vcpkg install  vtk[opengl]:x64-windows`

**Failure logs**

```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/src/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: C:/src/vcpkg/buildtrees/vtk/x64-windows-dbg
    See logs for more information:
      C:\src\vcpkg\buildtrees\vtk\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/vtk/portfile.cmake:235 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)


error: building vtk:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+vtk
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[vtk]+Build+error
Include '[vtk] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 1c48ec7f4 2023-02-07 (25 hours ago)
```
In  C:\src\vcpkg\buildtrees\vtk\install-x64-windows-dbg-out.log
```
FAILED: bin/vtkCommonMisc-9.2d.dll lib/vtkCommonMisc-9.2d.lib 
cmd.exe /C "cd . && C:\src\vcpkg\downloads\tools\cmake-3.25.1-windows\cmake-3.25.1-windows-i386\bin\cmake.exe -E vs_link_dll --intdir=Common\Misc\CMakeFiles\CommonMisc.dir --rc=C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe  Common\Misc\CMakeFiles\CommonMisc.dir\vtkContourValues.cxx.obj Common\Misc\CMakeFiles\CommonMisc.dir\vtkErrorCode.cxx.obj Common\Misc\CMakeFiles\CommonMisc.dir\vtkExprTkFunctionParser.cxx.obj Common\Misc\CMakeFiles\CommonMisc.dir\vtkFunctionParser.cxx.obj Common\Misc\CMakeFiles\CommonMisc.dir\vtkHeap.cxx.obj Common\Misc\CMakeFiles\CommonMisc.dir\vtkPolygonBuilder.cxx.obj Common\Misc\CMakeFiles\CommonMisc.dir\vtkResourceFileLocator.cxx.obj  /out:bin\vtkCommonMisc-9.2d.dll /implib:lib\vtkCommonMisc-9.2d.lib /pdb:bin\vtkCommonMisc-9.2d.pdb /dll /version:9.2 /machine:x64  /nologo    /debug /INCREMENTAL  lib\vtkCommonMath-9.2d.lib  lib\vtkCommonCore-9.2d.lib  lib\vtksys-9.2d.lib  ws2_32.lib  dbghelp.lib  psapi.lib  lib\vtkkissfft-9.2d.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd ."
FINAL LINK: command "C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe Common\Misc\CMakeFiles\CommonMisc.dir\vtkContourValues.cxx.obj Common\Misc\CMakeFiles\CommonMisc.dir\vtkErrorCode.cxx.obj Common\Misc\CMakeFiles\CommonMisc.dir\vtkExprTkFunctionParser.cxx.obj Common\Misc\CMakeFiles\CommonMisc.dir\vtkFunctionParser.cxx.obj Common\Misc\CMakeFiles\CommonMisc.dir\vtkHeap.cxx.obj Common\Misc\CMakeFiles\CommonMisc.dir\vtkPolygonBuilder.cxx.obj Common\Misc\CMakeFiles\CommonMisc.dir\vtkResourceFileLocator.cxx.obj /out:bin\vtkCommonMisc-9.2d.dll /implib:lib\vtkCommonMisc-9.2d.lib /pdb:bin\vtkCommonMisc-9.2d.pdb /dll /version:9.2 /machine:x64 /nologo /debug /INCREMENTAL lib\vtkCommonMath-9.2d.lib lib\vtkCommonCore-9.2d.lib lib\vtksys-9.2d.lib ws2_32.lib dbghelp.lib psapi.lib lib\vtkkissfft-9.2d.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:Common\Misc\CMakeFiles\CommonMisc.dir/intermediate.manifest Common\Misc\CMakeFiles\CommonMisc.dir/manifest.res" failed (exit code 1168) with the following output:
LINK : fatal error LNK1168: cannot open bin\vtkCommonMisc-9.2d for writing
```

**Comment by LilyWangLL** [comment]
> LINK : fatal error LNK1168: cannot open bin\vtkCommonMisc-9.2d for writing

Could you please try clone vcpkg to other disks and rebuild `vtk`? I guess maybe a permission problem that caused the failure to write the file.

**Comment by QiuYilin** [comment]
> > LINK : fatal error LNK1168: cannot open bin\vtkCommonMisc-9.2d for writing
> 
> Could you please try clone vcpkg to other disks and rebuild `vtk`? I guess maybe a permission problem that caused the failure to write the file.

I have tried to give powershell manager permission. And just now I did as you advise,it still didn't work.

the terminal shows
```
CMake Warning at scripts/cmake/vcpkg_execute_build_process.cmake:65 (message):
  Please ensure your system has sufficient memory.
Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/vtk/portfile.cmake:235 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)
```


```
-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: D:/src/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: D:/src/vcpkg/buildtrees/vtk/x64-windows-dbg
    See logs for more information:
      D:\src\vcpkg\buildtrees\vtk\install-x64-windows-dbg-out.log
      D:\src\vcpkg\buildtrees\vtk\install-x64-windows-dbg-out-1.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/vtk/portfile.cmake:235 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)
```

And the log file:
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/10751040/install-x64-windows-dbg-out.log)

**Comment by LilyWangLL** [comment]
It still can't find `bin\vtkCommonSystem-9.2d.dll`, could you please try the following steps?
1. Open a x64 cmd as below:
![image](https://user-images.githubusercontent.com/94091114/219252690-a20c2d6c-7404-444d-b1fa-da921e22c843.png)

2. Run command `pushd D:\src\vcpkg\buildtrees\vtk\x64-windows-dbg`

3. Run command `C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe Common\System\CMakeFiles\CommonSystem.dir\vtkClientSocket.cxx.obj Common\System\CMakeFiles\CommonSystem.dir\vtkDirectory.cxx.obj Common\System\CMakeFiles\CommonSystem.dir\vtkExecutableRunner.cxx.obj Common\System\CMakeFiles\CommonSystem.dir\vtkServerSocket.cxx.obj Common\System\CMakeFiles\CommonSystem.dir\vtkSocket.cxx.obj Common\System\CMakeFiles\CommonSystem.dir\vtkSocketCollection.cxx.obj Common\System\CMakeFiles\CommonSystem.dir\vtkTimerLog.cxx.obj /out:bin\vtkCommonSystem-9.2d.dll /implib:lib\vtkCommonSystem-9.2d.lib /pdb:bin\vtkCommonSystem-9.2d.pdb /dll /version:9.2 /machine:x64 /nologo /debug /INCREMENTAL lib\vtkCommonCore-9.2d.lib lib\vtksys-9.2d.lib ws2_32.lib dbghelp.lib psapi.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:Common\System\CMakeFiles\CommonSystem.dir/intermediate.manifest Common\System\CMakeFiles\CommonSystem.dir/manifest.res`

Please provide the output content, thanks.

**Comment by QiuYilin** [comment]
> It still can't find `bin\vtkCommonSystem-9.2d.dll`, could you please try the following steps?
> 
> 1. Open a x64 cmd as below:
>    ![image](https://user-images.githubusercontent.com/94091114/219252690-a20c2d6c-7404-444d-b1fa-da921e22c843.png)
> 2. Run command `pushd D:\src\vcpkg\buildtrees\vtk\x64-windows-dbg`
> 3. Run command `C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe Common\System\CMakeFiles\CommonSystem.dir\vtkClientSocket.cxx.obj Common\System\CMakeFiles\CommonSystem.dir\vtkDirectory.cxx.obj Common\System\CMakeFiles\CommonSystem.dir\vtkExecutableRunner.cxx.obj Common\System\CMakeFiles\CommonSystem.dir\vtkServerSocket.cxx.obj Common\System\CMakeFiles\CommonSystem.dir\vtkSocket.cxx.obj Common\System\CMakeFiles\CommonSystem.dir\vtkSocketCollection.cxx.obj Common\System\CMakeFiles\CommonSystem.dir\vtkTimerLog.cxx.obj /out:bin\vtkCommonSystem-9.2d.dll /implib:lib\vtkCommonSystem-9.2d.lib /pdb:bin\vtkCommonSystem-9.2d.pdb /dll /version:9.2 /machine:x64 /nologo /debug /INCREMENTAL lib\vtkCommonCore-9.2d.lib lib\vtksys-9.2d.lib ws2_32.lib dbghelp.lib psapi.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:Common\System\CMakeFiles\CommonSystem.dir/intermediate.manifest Common\System\CMakeFiles\CommonSystem.dir/manifest.res`
> 
> Please provide the output content, thanks.

It seems there is no output.

![image](https://user-images.githubusercontent.com/26407388/219268322-4cb1e737-197b-4c87-b6bb-657bd9c3199f.png)

**Comment by LilyWangLL** [comment]
If there is no error after running command line, please try install `vtk` on x64 cmd as below:
1. Open a x64 cmd as previous comment.
2. Run command `pushd D:\src\vcpkg`.
3. Run command `vcpkg.exe install vtk[opengl]:x64-windows`.

**Comment by LilyWangLL** [comment]
Ping @QiuYilin for response, does this issue resolved?

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.

**Comment by QiuYilin** [comment]
I met this problem again. But this time I found "Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v -v -j9 install" in log. My computer use i7 7700HQ which only has 8 threads. Sometimes the build process will fail directly and sometimes it will suceess by restarting build without parallelism.
