### ISSUE TITLE
vcpkg env does not work on linux

### ISSUE THREAD

**Issue by soroshsabz** [microsoft/vcpkg#29559]
ITNOA

**Describe the bug**
I install vcpkg on clean linux with cloning from this repo and run `./vcpkg-bootstrap.sh`,

after I run `../vcpkg/vcpkg env` I got error like below

```
ssoroosh@ssoroosh-lap:~/test$ ../vcpkg/vcpkg env
A suitable version of cmake was not found (required v3.25.1) Downloading portable cmake 3.25.1...
Downloading cmake...
https://github.com/Kitware/CMake/releases/download/v3.25.1/cmake-3.25.1-linux-x86_64.tar.gz->/home/ssoroosh/vcpkg/downloads/cmake-3.25.1-linux-x86_64.tar.gz
Extracting cmake...
sh: 1: cmd: not found
```
**Environment**
- OS: WSL (Ubuntu 22.04)
- Compiler: ssoroosh@ssoroosh-lap:~/test$ g++ --version
g++ (Ubuntu 12.1.0-2ubuntu1~22.04) 12.1.0

**To Reproduce**
1. create directory
2. run ../vcpkg/vcpkg env

**Expected behavior**
I expect create env

**Failure logs**
```
ssoroosh@ssoroosh-lap:~/test$ ../vcpkg/vcpkg env
A suitable version of cmake was not found (required v3.25.1) Downloading portable cmake 3.25.1...
Downloading cmake...
https://github.com/Kitware/CMake/releases/download/v3.25.1/cmake-3.25.1-linux-x86_64.tar.gz->/home/ssoroosh/vcpkg/downloads/cmake-3.25.1-linux-x86_64.tar.gz
Extracting cmake...
sh: 1: cmd: not found
```

**Comment by autoantwort** [comment]
Afaik this command is only for windows

**Comment by soroshsabz** [comment]
So I expect the error is clear about that

**Comment by soroshsabz** [comment]
I create PR https://github.com/microsoft/vcpkg-tool/pull/891

**Comment by JackBoosY** [comment]
@FrankXie05 First label vcpkg bug, after the related fix PR merged, label vcpkg-tool-release.

**Comment by FrankXie05** [comment]
Thanks to @JackBoosY  for correcting the wrong label.

**Comment by soroshsabz** [comment]
So, why requires:vcpkg-tool-release removed?

**Comment by JackBoosY** [comment]
@FrankXie05 Add vcpkg-tool-release label.

**Comment by JackBoosY** [comment]
Why close this issue? Did the new vcpkg tool release published?

**Comment by FrankXie05** [comment]
Sorry, I thought the PR was merged by master. :)
