### ISSUE TITLE
Add simbody

### ISSUE THREAD

**Issue by traversaro** [microsoft/vcpkg#2955]
It would be great to have a port of the Simbody library ( https://github.com/simbody/simbody ).

Debian package : https://packages.debian.org/unstable/source/simbody .
Homebrew formula (not from core repository) : https://github.com/osrf/homebrew-simulation/blob/master/simbody.rb .
Arch package: https://aur.archlinux.org/packages/simbody/ . 
Repology page: https://repology.org/metapackage/simbody/versions .

**Comment by Fleischner** [comment]
Experimental port-files are here: https://github.com/simbody/simbody/issues/628

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
