### ISSUE TITLE
[boost-filesystem] WASM: libboost_filesystem.a: Unknown format, not a static library!

### ISSUE THREAD

**Issue by tobbi** [microsoft/vcpkg#29574]
Package: boost-filesystem[core]:wasm32-emscripten -> 1.81.0#1

**Host Environment**

- Host: x64-linux
- Compiler: Clang 17.0.0
-    vcpkg: https://github.com/microsoft/vcpkg/commit/37fce29a263a1546262eaed6af7ccac53b0094cd

**To Reproduce**

Link against the .a file generated by `vcpkg install boost-filesystem:wasm32-emscripten`

See https://github.com/SuperTux/supertux/pull/2298 for the CI build and link code.

**Comment by tobbi** [comment]
[supertux_build_log.zip](https://github.com/microsoft/vcpkg/files/10707530/supertux_build_log.zip)

**Comment by tobbi** [comment]
@Pospelove

**Comment by Pospelove** [comment]
see also https://github.com/emscripten-core/emscripten/issues/17052

**Comment by Pospelove** [comment]
it seems that it blocks me as well. I'll take a look

**Comment by Pospelove** [comment]
@tobbi can't reproduce for now. I was able to write hello world with boost-filesystem, build an executable (.js) and run with nodejs

```
#include <boost/filesystem.hpp>
#include <iostream>

int main() {
    boost::filesystem::path p("hello_world.txt");
    std::cout << p << std::endl;
    return 0;
}
```

I'll keep testing, just thought you'll be interested. I can provide more info if needed.

**Comment by tobbi** [comment]
Did you actually link against libboost_filesystem.a or just include its include files? I don't know to what extent knowing how you built your test project helps as I'm not too familiar with how linking works, especially in WASM.

**Comment by Pospelove** [comment]
@tobbi 
my cmakelists:
```cmake

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake")

set(VCPKG_TARGET_TRIPLET "wasm32-emscripten")

set(CMAKE_TOOLCHAIN_FILE "${CMAKE_SOURCE_DIR}/vcpkg/scripts/buildsystems/vcpkg.cmake")

cmake_minimum_required(VERSION 3.15)
project(openmw_web)

find_package(Boost REQUIRED)

file(GLOB_RECURSE src src/boost_hello_world/*)
add_executable(boost_hello_world ${src})

target_link_libraries(boost_hello_world PRIVATE Boost::boost)
```


my build command:

mkdir build \
    && cd build \
    && cmake .. \
    && cmake --build .

**Comment by tobbi** [comment]
Could you maybe check out the branch from that pull request? https://github.com/SuperTux/supertux/pull/2298 
https://github.com/SuperTux/supertux/tree/oh-my-vcpk-gee

The commands that we run are defined in the https://github.com/SuperTux/supertux/blob/49752bbf2329a37c8cdf07bdb9d8646f9f8b0825/.github/workflows/wasm.yml file under "steps".

**Comment by Pospelove** [comment]
@tobbi Taking a look. Could you please approve workflow runs for https://github.com/SuperTux/supertux/pull/2390

**Comment by tobbi** [comment]
Thank you! I've approved the workflow runs.

**Comment by Pospelove** [comment]
Waiting for workflow run :)

My theory is that it's not a vcpkg bug, just a question of modifying CMake flags a bit (-D...)

Since CMAKE_TOOLCHAIN_FILE is originally for cross-compiling and targeting wasm *is* cross-cdompiling, we should use Emscripten's toolchain file.

However vcpkg uses CMAKE_TOOLCHAIN_FILE to invoke its scripts.

But what do we do in case of cross-compiling with vcpkg onboard? vcpkg comes with a solution:
VCPKG_CHAINLOAD_TOOLCHAIN_FILE variable. The specified file will be used as a 'real' toolchain file. So I'm trying this:
```bash
-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/runner/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
-DCMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake\
```

As far as I know there is no need to specify EMSCRIPTEN=1, C_COMPILER and CXX_COMPILER manually so I removed these lines.

**Comment by Pospelove** [comment]
Let's see if it helps.

**Comment by Pospelove** [comment]
I think that we originally saw `Unknown format, not a static library!` error because of attempt to link wasm static libraries into linux executable

**Comment by Pospelove** [comment]
maybe related https://github.com/microsoft/vcpkg/issues/27416

**Comment by Pospelove** [comment]
@tobbi @FrankXie05 not a vcpkg bug
