### ISSUE TITLE
port depends on nothing when `BUILD_TESTING` but fails to build test dependency?!

### ISSUE THREAD

**Issue by SamuelMarks** [microsoft/vcpkg#29608]
**Describe the bug**
My port doesn't depend on anything https://github.com/offscale/vcpkg/tree/c-str-span/ports/c-str-span
```json
  "dependencies": [
    {
      "name": "vcpkg-cmake",
      "host": true
    }
  ]
```

But building depending on it gives:
```
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:843 (_find_package):
  Could not find a package configuration file provided by "cmocka" with any
  of the following names:

    cmockaConfig.cmake
    cmocka-config.cmake
```

However my `CMakeLists.txt` for c-str-span has:
```
include(CTest)
if (BUILD_TESTING)
    add_subdirectory("tests")
endif (BUILD_TESTING)
```

**Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
1. `./vcpkg install c-str-span` works but doing it from a dependent project fails
2. E.g., `git clone https://github.com/SamuelMarks/cdd-c`
3. `cd cdd-c`
4. `cmake -DCMAKE_TOOLCHAIN_FILE="..\vcpkg\scripts\buildsystems\vcpkg.cmake" -S . -B build`

**Expected behavior**
It shouldn't try and depend on the linked repos `vcpkg.json`. https://github.com/SamuelMarks/c-str-span/blob/master/vcpkg.json has this currently:
```json
  "dependencies": [
    "cmocka"
  ]
```

**Failure logs**
-(please attached failure logs)

**Additional context**
Unless I'm misusing vcpkg and it's not meant to list `cmocka` as a dependency like that but instead as some sort of feature?

**Comment by JackBoosY** [comment]
Because https://github.com/SamuelMarks/c-str-span/blob/3edcc6e747160cf7404ef5a371844d2f39717093/tests/CMakeLists.txt#L49-L51 calls `find_package(cmocka CONFIG REQUIRED)`.

**Comment by FrankXie05** [comment]
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. `./vcpkg install c-str-span` works but doing it from a dependent project fails

You shuold also run command `./vcpkg install cmocka`.

**Comment by SamuelMarks** [comment]
> Because https://github.com/SamuelMarks/c-str-span/blob/3edcc6e747160cf7404ef5a371844d2f39717093/tests/CMakeLists.txt#L49-L51 calls `find_package(cmocka CONFIG REQUIRED)`.

@JackBoosY Yes, but that `CMakeLists.txt` should never be read, due to https://github.com/SamuelMarks/c-str-span/blob/3edcc6e/CMakeLists.txt#L50-L53
```cmake
include(CTest)
if (BUILD_TESTING)
    add_subdirectory("tests")
endif (BUILD_TESTING)
```

**Comment by JackBoosY** [comment]
According to the official doc: https://cmake.org/cmake/help/latest/module/CTest.html
```
The module automatically creates a BUILD_TESTING option that selects whether to enable testing support (ON by default).
```
Did you pass `-DBUILD_TESTING=OFF`?

**Comment by FrankXie05** [comment]
We don't have enough information to solve this issue, unfortunately.  if it is still an issue, please ping me and I will reopen this issue.

> According to the official doc: https://cmake.org/cmake/help/latest/module/CTest.html
> 
> ```
> The module automatically creates a BUILD_TESTING option that selects whether to enable testing support (ON by default).
> ```
> 
> Also you didn't make an option to set `BUILD_TESTING` to `OFF` by default. And did you pass `-DBUILD_TESTING=OFF`? I didn't see it in the cmake command line.

**Comment by SamuelMarks** [comment]
@JackBoosY  Yes see here: https://github.com/offscale/vcpkg/blob/7fc89b6/ports/c-str-span/portfile.cmake
```cmake
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        "-DBUILD_TESTING=OFF"
)
```

@FrankXie05 This port should be buildable without requiring the test dependencies to be built with it.

**Comment by JackBoosY** [comment]
> @JackBoosY Yes see here: https://github.com/offscale/vcpkg/blob/7fc89b6/ports/c-str-span/portfile.cmake
> 
> ```cmake
> vcpkg_cmake_configure(
>     SOURCE_PATH "${SOURCE_PATH}"
>     OPTIONS
>         "-DBUILD_TESTING=OFF"
> )
> ```
> 
> @FrankXie05 This port should be buildable without requiring the test dependencies to be built with it.

I can't reproduce this failure when using you provided port `c-str-span`:
```
PS J:\vcpkg-test\vcpkg> .\vcpkg.exe install c-str-span
Computing installation plan...
The following packages will be built and installed:
    c-str-span[core]:x86-windows -> 2023-02-11
Detecting compiler hash for triplet x86-windows...
Restored 0 package(s) from C:\Users\JackBoos\AppData\Local\vcpkg\archives in 150.7 us. Use --debug to see more details.
Installing 1/1 c-str-span:x86-windows...
Building c-str-span[core]:x86-windows...
-- Downloading https://github.com/SamuelMarks/c-str-span/archive/5ca092771880914062494c14f72c64594b0d97e5.tar.gz -> SamuelMarks-c-str-span-5ca092771880914062494c14f72c64594b0d97e5.tar.gz...
-- Extracting source J:/vcpkg-test/vcpkg/downloads/SamuelMarks-c-str-span-5ca092771880914062494c14f72c64594b0d97e5.tar.gz
-- Using source at J:/vcpkg-test/vcpkg/buildtrees/c-str-span/src/594b0d97e5-3e15528cd8.clean
-- Found external ninja('1.10.2').
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: J:/vcpkg-test/vcpkg/packages/c-str-span_x86-windows/share/c-str-span/copyright
-- Performing post-build validation
Stored binary cache: "C:\Users\JackBoos\AppData\Local\vcpkg\archives\dc\dc7239e564680f57a448eda7d5dad5224a5a85e0305dff3d80f01a77a4622623.zip"
Elapsed time to handle c-str-span:x86-windows: 7.831 s
Total install time: 16.23 s
c-str-span provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(c_str_span CONFIG REQUIRED)
    target_link_libraries(main PRIVATE c_str_span c_str_span_compiler_flags)

PS J:\vcpkg-test\vcpkg>
```

**Comment by SamuelMarks** [comment]
@JackBoosY To replicate this bug, you'll want to revert to one before this commit https://github.com/offscale/vcpkg/commit/19dfd786932588262faef84d1b860145c6d627c1 ; i.e., `3a4009f2a064c8aa6d293c84fbaecf9d34ed1c84`

(I explicitly removed cmocka from my repos `vcpkg.json` here https://github.com/SamuelMarks/c-str-span/commit/5ca092771880914062494c14f72c64594b0d97e5 )

**Comment by JackBoosY** [comment]
> @JackBoosY To replicate this bug, you'll want to revert to one before this commit [offscale@19dfd78](https://github.com/offscale/vcpkg/commit/19dfd786932588262faef84d1b860145c6d627c1) ; i.e., `3a4009f2a064c8aa6d293c84fbaecf9d34ed1c84`
> 
> (I explicitly removed cmocka from my repos `vcpkg.json` here [SamuelMarks/c-str-span@5ca0927](https://github.com/SamuelMarks/c-str-span/commit/5ca092771880914062494c14f72c64594b0d97e5) )

As [I said](https://github.com/microsoft/vcpkg/issues/29608#issuecomment-1427222166), if `BUILD_TESTING` is `ON` or not defined `BUILD_TESTING`, this port will find `cmoka`. It's by design.

**Comment by dg0yt** [comment]
> ~~~
> CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:843 (_find_package):
>   Could not find a package configuration file provided by "cmocka" with any
>   of the following names:
> 
>     cmockaConfig.cmake
>     cmocka-config.cmake

It would have been good to add the CMake stack trace following these line.

**Comment by SamuelMarks** [comment]
@JackBoosY Yes but `BUILD_TESTING` is set to `OFF` in the `vcpkg.json`. Replicate by checking out at the aforementioned commit hash.

**Comment by dg0yt** [comment]
Add the CMake stack trace...
