### ISSUE TITLE
[sdl2] build failure

### ISSUE THREAD

**Issue by SimoneN64** [microsoft/vcpkg#29600]
Hi I'm trying to install sdl2[vulkan]:x64-windows.

**Host Environment**

- OS: Windows 11
- Compiler: Clang-cl 15.0.1

**To Reproduce**

`./vcpkg install sdl2[vulkan]:x64-windows`

**Failure logs**
```
./vcpkg install sdl2[vulkan]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    sdl2[base,core,vulkan]:x64-windows -> 2.26.3
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\simuuz\AppData\Local\vcpkg\archives in 187.6 us. Use --debug to see more details.
Installing 1/1 sdl2:x64-windows...
Building sdl2[base,core,vulkan]:x64-windows...
-- Using cached libsdl-org-SDL-release-2.26.3.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/sdl2/src/ase-2.26.3-ce66efab1c.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/libsdl-org-SDL-release-2.26.3.tar.gz
-- Applying patch deps.patch
-- Using source at C:/vcpkg/buildtrees/sdl2/src/ase-2.26.3-ce66efab1c.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/vcpkg/buildtrees/sdl2/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\sdl2\config-x64-windows-dbg-CMakeCache.txt.log
      C:\vcpkg\buildtrees\sdl2\config-x64-windows-rel-CMakeCache.txt.log
      C:\vcpkg\buildtrees\sdl2\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:248 (vcpkg_execute_required_process)
  ports/sdl2/portfile.cmake:35 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)


error: building sdl2:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+sdl2
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[sdl2]+Build+error
Include '[sdl2] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 36fb23307 2023-02-10 (22 hours ago)
```

**Additional context**

I simply installed Visual Studio Community, selected "Desktop development with C++" and also ticked "Clang" on the side. I have CMake installed. I also tried to run `git pull` and `vcpkg update`.
These are the logs:
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/10714409/config-x64-windows-out.log)
[config-x64-windows-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10714410/config-x64-windows-rel-CMakeCache.txt.log)
[config-x64-windows-dbg-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10714411/config-x64-windows-dbg-CMakeCache.txt.log)

**Comment by JackBoosY** [comment]
```
    cmd.exe /C "cd . && C:\vcpkg\downloads\tools\cmake-3.25.1-windows\cmake-3.25.1-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_2eb0d.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~1\MICROS~1\2022\COMMUN~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\link.exe /nologo CMakeFiles\cmTC_2eb0d.dir\testCCompiler.c.obj  /out:cmTC_2eb0d.exe /implib:cmTC_2eb0d.lib /pdb:cmTC_2eb0d.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /fo CMakeFiles\cmTC_2eb0d.dir/manifest.res CMakeFiles\cmTC_2eb0d.dir/manifest.rc" failed (exit code 0) with the following output:
    Impossibile trovare il file specificato
    ninja: build stopped: subcommand failed.
```
```
Cannot find the specified file
```

**Comment by Cheney-W** [comment]
Please make sure you have installed below contents:
1. English language packs.
2. 
![image](https://user-images.githubusercontent.com/38240633/218394299-9e1879b0-20ce-4d54-a0ab-d06c059230c1.png)

**Comment by CocoSimone** [comment]
Sorry for the late reply. I installed those components, rebooted my computer, and the error still happens. Same exact logs, too.

**Comment by Cheney-W** [comment]
The error in the new vcpkg is still the same as below?
```
CMake Error at C:/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/share/cmake-3.25/Modules/CMakeTestCCompiler.cmake:70 (message):
  The C compiler
    "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe"
  is not able to compile a simple test program.
```

**Comment by SimoneN64** [comment]
Looks like it:
[config-x64-windows-dbg-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10751693/config-x64-windows-dbg-CMakeCache.txt.log)
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/10751695/config-x64-windows-out.log)
[config-x64-windows-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10751696/config-x64-windows-rel-CMakeCache.txt.log)

**Comment by Cheney-W** [comment]
Could you please provide the screenshots of installed components in your Visual Studio Installer?

**Comment by SimoneN64** [comment]
![immagine](https://user-images.githubusercontent.com/91993281/219305047-9505d558-000e-4e7f-b758-ea3bd3f2343e.png)

**Comment by SimoneN64** [comment]
I figured out the problem. Visual Studio Installer was silently failing to install the Windows SDK because of some dirty registry keys from older versions that were essentially marking it as already installed, when it really wasn't. I removed them using msiexec /x {guid}. The guid can be found in the Windows SDK installation logs. Closing as solved.

**Comment by JackBoosY** [comment]
> I figured out the problem. Visual Studio Installer was silently failing to install the Windows SDK because of some dirty registry keys from older versions that were essentially marking it as already installed, when it really wasn't. I removed them using msiexec /x {guid}. The guid can be found in the Windows SDK installation logs. Closing as solved.

Yes, we know that. The best way is manually install Win SDK using the administrator permission.
