### ISSUE TITLE
[ICU] build failure - dependencies URLs not working

### ISSUE THREAD

**Issue by larshg** [microsoft/vcpkg#29617]
**Host Environment**

- OS: Windows
- Compiler: VS2019

**To Reproduce**

`./vcpkg install  icu`

**Failure logs**
https://dev.azure.com/PointCloudLibrary/pcl/_build/results?buildId=22750&view=logs&j=1d0d1847-c9f6-5bed-a0b6-1256ce54b612&t=3a44332a-b52e-58ca-3fc0-f33f70a901bb&l=3391

**Additional context**

Accessing the links directly also returns error 404 or the like

**Comment by dg0yt** [comment]
It is not an issue with port icu. You must use a more recent commit of vcpkg in order to get updated scripts.

**Comment by larshg** [comment]
Newer than the latest release?

**Comment by dg0yt** [comment]
Newer than
https://github.com/PointCloudLibrary/pcl/blob/aa864db6386e73931b443ca6f8216f84a042d01f/.ci/azure-pipelines/env.yml#L122.

**Comment by dg0yt** [comment]
FTR: Fix is https://github.com/microsoft/vcpkg/pull/28919.

**Comment by larshg** [comment]
I was trying out the latest release, but indeed the commit you linked to is newer than that.
Trying with the mentioned commit https://github.com/PointCloudLibrary/pcl/pull/5607/files

Thanks @dg0yt

**Comment by larshg** [comment]
Solved with newer checkout.
