### ISSUE TITLE
Build failure qhull lib

### ISSUE THREAD

**Issue by TalSomech** [microsoft/vcpkg#29613]
Hi i am using vcpkg and i've tried to install qhull lib with vcpkg and use it however i get the error : 
![Capture](https://user-images.githubusercontent.com/73115681/218313101-8493e761-7f53-48ae-bd1a-d4a769575170.PNG)
 i am using visual studio and my project is C++ windows forms

**Comment by JackBoosY** [comment]
Please provide the triplet you built qhull, and please provide your custom project's configuration type.

**Comment by TalSomech** [comment]
my triplet was x64-windows 
and my configuration is debug in visual studio
if you meant anything else and i misunderstood please clarify , and thank you

**Comment by JackBoosY** [comment]
Did your custom project is x64?

**Comment by TalSomech** [comment]
yes, and further information is that i've tried to download the source code for the qhull lib, and configure the path of additional lib to that of the qhull but i still got the same error

**Comment by JackBoosY** [comment]
@MonicaLiu0311 x64 dynamic library shouldn't contains symbol `__cdecl` and it should be `__declspec`, please check the pre-define macros in header files.

**Comment by MonicaLiu0311** [comment]
@TalSomech  Are you using the latest version of vcpkg?

**Comment by TalSomech** [comment]
> @TalSomech Are you using the latest version of vcpkg?

Yes, i've installed it yesterday ,
and as for qh_dllimport , i've found only one refrence to it in the code 

![Capture](https://user-images.githubusercontent.com/73115681/218418440-b6342046-2c02-4450-9a29-b7f30903e831.PNG)

**Comment by JackBoosY** [comment]
Let me fix it quickly.

**Comment by TalSomech** [comment]
i've used your fix but still the problem seems to persists,the only difference is that the first error change to LNK2028 instead of LNK2020
![Capture](https://user-images.githubusercontent.com/73115681/218434569-a716679b-d602-4086-8e5b-27affb520577.PNG)

**Comment by JackBoosY** [comment]
@TalSomech Can you please provide a sample code?

**Comment by TalSomech** [comment]
![Capture](https://user-images.githubusercontent.com/73115681/218435171-f6e1b014-a65f-42e2-a573-f54656db4f2b.PNG)
here, however i do not know if i should or not , but i havent used extern "C" in my code

**Comment by TalSomech** [comment]
plus , the indexer finds the function declerations in libqhull.h in vcpkg but it cannot find the function implementation in global.c

**Comment by JackBoosY** [comment]
Can you please directly plaste the code here instead of give me a cutshort?

**Comment by TalSomech** [comment]
`
    int script::Qhalf(int argc, char* argv[], char* inFilePath, char* outFilePath) {
        int curlong, totlong; /* used !qh_NOmem */
        int exitcode, numpoints, dim;
        coordT* points;
        boolT ismalloc;
        FILE* inFile = fopen(inFilePath, "r");
        FILE* outFile = fopen(outFilePath, "w");
        if (inFile == NULL || outFile == NULL)
        {
            printf("Error! Could not open file\n");
            return -1; // must include stdlib.h
        }
        QHULL_LIB_CHECK /* Check for compatible library */
            qh_init_A(inFile, outFile, stderr, argc, argv);  /* sets qh qhull_command */
        exitcode = setjmp(qh errexit); /* simple statement for CRAY J916 */
        if (!exitcode) {
            qh NOerrexit = False;
            qh_option("Halfspace", NULL, NULL);
            qh HALFspace = True;    /* 'H'   */
            qh_checkflags(qh qhull_command, hidden_options);
            qh_initflags(qh qhull_command);
            if (qh SCALEinput) {
                fprintf(qh ferr, "\
qhull error: options 'Qbk:n' and 'QBk:n' are not used with qhalf.\n\
             Use 'Qbk:0Bk:0 to drop dimension k.\n");
                qh_errexit(qh_ERRinput, NULL, NULL);
            }
            points = qh_readpoints(&numpoints, &dim, &ismalloc);
            qh_init_B(points, numpoints, dim, ismalloc);
            qh_qhull();
            qh_check_output();
            qh_produce_output();
            if (qh VERIFYoutput && !qh FORCEoutput && !qh STOPpoint && !qh STOPcone)
                qh_check_points();
            exitcode = qh_ERRnone;
        }
        qh NOerrexit = True;  /* no more setjmp */
#ifdef qh_NOmem
        qh_freeqhull(qh_ALL);
#else
        qh_freeqhull(!qh_ALL);
        qh_memfreeshort(&curlong, &totlong);
        if (curlong || totlong)
            qh_fprintf_stderr(7079, "qhull internal warning (main): did not free %d bytes of long memory(%d pieces)\n",
                totlong, curlong);
#endif
        return exitcode;

    }`

**Comment by JackBoosY** [comment]
I found `DEPRECATED.txt` in _include/libqhull_:
```

qhull/src/libqhull

    This directory contains the non-reentrant version of qhull, libqhull.
    
    New code should use the reentrant version of qhull (libqhull_r).
    It allows multiple instances of qhull to run at the same time. On 
    modern architectures, it is nearly as fast as libqhull.   
    
    Qhull programs may be built with either library.  Each program has a
    reentrant version (e.g., qconvex_r.c) and a non-reentrant 
    version (qconvex.c).   The programs, rbox, qconvex, qdelaunay, qhalf, 
    and qvoronoi, are built with libqhull.  The qhull program is built 
    with libqhull_r.

    Qhull's C++ interface requires libqhull_r.  If you previously used the 
    C++ interface with libqhull, you will need to update your code to libqhull_r.
    See qh-code.htm#convert and Changes.txt for suggestions.
     
    The C code in libqhull looks unusual because of the 'qh' macro.  The 'qh'
    macro controls access to Qhull's global data structure, qhT.  If 
    'qh_QHpointer' is defined, 'qh' is 'qh_qh->' and 'qh_qh' is defined as
    'qhT *qh_qh', otherwise 'qh' is 'qh_qh.' and 'qh_qh' is defined as
    'qhT qh_qh'.  This allows dynamic allocation of qh_qh without modifying
    the code.  Reentrant Qhull is a better solution.

    libqhull will be supported indefinitely.  The qh_QHpointer variation
    of libqhull will be not be retested each release.  It is replaced by 
    libqhull_r.
```

And I switch to use `#include <libqhull_r/libqhull_r.h>` when calling function `qh_freeqhull` didn't meet this issue.
Maybe the upstream deprecated this method?

**Comment by JackBoosY** [comment]
Okay, so please close this issue.
