### ISSUE TITLE
[boost-container] Build error

### ISSUE THREAD

**Issue by KaiTang2** [microsoft/vcpkg#29620]
**Host Environment**

- OS: windows x64
- Compiler: revision

**To Reproduce**
vcpkg.exe install poppler:x64-windows

**Failure logs**
Installing 5/8 boost-intrusive:x64-windows...
Building boost-intrusive[core]:x64-windows...
-- Downloading https://github.com/boostorg/intrusive/archive/boost-1.81.0.tar.gz -> boostorg-intrusive-boost-1.81.0.tar.gz...
-- Extracting source E:/GitHub/vcpkg/downloads/boostorg-intrusive-boost-1.81.0.tar.gz
-- Using source at E:/GitHub/vcpkg/buildtrees/boost-intrusive/src/ost-1.81.0-fbaebaca9b.clean
-- Copying headers
-- Copying headers done
-- Installing: E:/GitHub/vcpkg/packages/boost-intrusive_x64-windows/share/boost-intrusive/usage
-- Installing: E:/GitHub/vcpkg/packages/boost-intrusive_x64-windows/share/boost-intrusive/copyright
-- Performing post-build validation
Stored binary cache: "C:\Users\唐凯\AppData\Local\vcpkg\archives\9f\9fbfdbb7ba3ca0c5eb4b87f177befce321c6a22fd4d9f48b1286f693e629c271.zip"
Elapsed time to handle boost-intrusive:x64-windows: 1.226 s
Installing 6/8 boost-modular-build-helper:x64-windows...
Building boost-modular-build-helper[core]:x64-windows...
-- Performing post-build validation
Stored binary cache: "C:\Users\唐凯\AppData\Local\vcpkg\archives\94\948e7655c62ac299961bd0f0017031a6c11000a93f2bd78ba32f1b311f41279c.zip"
Elapsed time to handle boost-modular-build-helper:x64-windows: 110.1 ms
Installing 7/8 boost-container:x64-windows...
Building boost-container[core]:x64-windows...
-- Downloading https://github.com/boostorg/container/archive/boost-1.81.0.tar.gz -> boostorg-container-boost-1.81.0.tar.gz...
-- Extracting source E:/GitHub/vcpkg/downloads/boostorg-container-boost-1.81.0.tar.gz
-- Using source at E:/GitHub/vcpkg/buildtrees/boost-container/src/ost-1.81.0-adfb4cf690.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: E:/GitHub/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j21
    Working Directory: E:/GitHub/vcpkg/buildtrees/boost-container/x64-windows-dbg
    See logs for more information:
      E:\GitHub\vcpkg\buildtrees\boost-container\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:140 (vcpkg_cmake_install)
  ports/boost-container/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:147 (include)

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/10717914/install-x64-windows-dbg-out.log)

**Comment by Cheney-W** [comment]
```
file C:\Users\ÌÆ¿­\AppData\Local\Temp\jam6c1092cb.000

msvc.write-setup-script E:\GitHub\vcpkg\buildtrees\boost-container\x64-windows-dbg\boost\standalone\msvc\943897acc6555446e7558f53bf1a3e85\msvc-setup.bat

    type "C:\Users\ÌÆ¿­\AppData\Local\Temp\jam6c1092cb.000" > "E:\GitHub\vcpkg\buildtrees\boost-container\x64-windows-dbg\boost\standalone\msvc\943897acc6555446e7558f53bf1a3e85\msvc-setup.bat"

The system cannot find the file specified.
```
Your user name has been resolved to `ÌÆ¿­`. Maybe you can use an English user name, such as `tangkai`.

**Comment by KaiTang2** [comment]
Is there no other way?Windows 11 does not provide a method to modify the user folder,If it is changed, it may cause failure to start.And most software will not be available.

**Comment by Cheney-W** [comment]
I think you could modify the value of the user variable `TEMP` and `TMP`, you could do as below:
1. Right click This PC.
2. Open Properties -> Advanced system settings -> Environment Variables...

**Comment by KaiTang2** [comment]
Succeed,thanks for your help.

**Comment by dg0yt** [comment]
> modify the value of the user variable `TEMP` and `TMP`

Now that we know that this works, shouldn't this become part of the boost build scripts: Redirect tmp to a location in `buildtrees`?
