### ISSUE TITLE
[curl] build failure

### ISSUE THREAD

**Issue by leesureel** [microsoft/vcpkg#29631]
**Host Environment**

- OS: [Windows]
- Compiler: mingw gcc

**To Reproduce**

`./vcpkg install curl:x64-mingw-dynamic`

**Failure logs**

Computing installation plan...
The following packages will be built and installed:
    curl[core,non-http,schannel,ssl,sspi]:x64-mingw-dynamic -> 7.87.0#1
Detecting compiler hash for triplet x64-mingw-dynamic...
-- Automatically setting HTTP(S)_PROXY environment variables to "127.0.0.1:7890".
Restored 0 package(s) from C:\Users\SURE\AppData\Local\vcpkg\archives in 280.4 us. Use --debug to see more details.
Installing 1/1 curl:x64-mingw-dynamic...
Building curl[core,non-http,schannel,ssl,sspi]:x64-mingw-dynamic...
warning: -- Using community triplet x64-mingw-dynamic. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\vcpkg\triplets\community\x64-mingw-dynamic.cmake
-- Using cached curl-curl-curl-7_87_0.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/curl/src/url-7_87_0-f6082b4186.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/curl-curl-curl-7_87_0.tar.gz
-- Applying patch 0002_fix_uwp.patch
-- Applying patch 0005_remove_imp_suffix.patch
-- Applying patch 0012-fix-dependency-idn2.patch
-- Applying patch 0020-fix-pc-file.patch
-- Applying patch 0022-deduplicate-libs.patch
-- Applying patch mbedtls-ws2_32.patch
-- Applying patch export-components.patch
-- Applying patch 0023-fix-find-cares.patch
-- Using source at C:/vcpkg/buildtrees/curl/src/url-7_87_0-f6082b4186.clean
-- Configuring x64-mingw-dynamic
-- Building x64-mingw-dynamic-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j21
    Working Directory: C:/vcpkg/buildtrees/curl/x64-mingw-dynamic-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\curl\install-x64-mingw-dynamic-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/curl/portfile.cmake:77 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.
[config-x64-mingw-dynamic-out.log](https://github.com/microsoft/vcpkg
[config-x64-mingw-dynamic-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10723911/config-x64-mingw-dynamic-rel-CMakeCache.txt.log)
/files/10723908/config-x64-mingw-dynamic-out.log)
[config-x64-mingw-dynamic-dbg-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10723909/config-x64-mingw-dynamic-dbg-CMakeCache.txt.log)

**Comment by dg0yt** [comment]
The latest version of port curl is 7.88.1.

**Comment by JonLiu1993** [comment]
@leesureel, Thanks for posting this issue, could you please use command `git pull` get the latest vcpkg and try again?

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
