### ISSUE TITLE
[opencv4] build failure

### ISSUE THREAD

**Issue by leesureel** [microsoft/vcpkg#29632]
**Host Environment**

- OS: [Windows]
- Compiler: mingw

**To Reproduce**

`./vcpkg install opencv4:x64-mingw-dynamic`

**Failure logs**

Computing installation plan...
The following packages will be built and installed:
  * libjpeg-turbo[core]:x64-mingw-dynamic -> 2.1.5
  * liblzma[core]:x64-mingw-dynamic -> 5.4.1#1
  * libpng[core]:x64-mingw-dynamic -> 1.6.39
  * libwebp[core,libwebpmux,nearlossless,simd,unicode]:x64-mingw-dynamic -> 1.3.0
    opencv4[core,default-features,dnn,jpeg,png,quirc,tiff,webp]:x64-mingw-dynamic -> 4.7.0#2
  * protobuf[core]:x64-mingw-dynamic -> 3.21.12
  * quirc[core]:x64-mingw-dynamic -> 1.1#3
  * tiff[core,jpeg,lzma,zip]:x64-mingw-dynamic -> 4.5.0#2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-mingw-dynamic...
-- Automatically setting HTTP(S)_PROXY environment variables to "127.0.0.1:7890".
Restored 0 package(s) from C:\Users\SURE\AppData\Local\vcpkg\archives in 905.2 us. Use --debug to see more details.
Installing 1/8 libjpeg-turbo:x64-mingw-dynamic...
Building libjpeg-turbo[core]:x64-mingw-dynamic...
warning: -- Using community triplet x64-mingw-dynamic. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\vcpkg\triplets\community\x64-mingw-dynamic.cmake
-- Using cached libjpeg-turbo-libjpeg-turbo-2.1.5.tar.gz.
-- Extracting source C:/vcpkg/downloads/libjpeg-turbo-libjpeg-turbo-2.1.5.tar.gz
-- Applying patch add-options-for-exes-docs-headers.patch
-- Applying patch workaround_cmake_system_processor.patch
-- Using source at C:/vcpkg/buildtrees/libjpeg-turbo/src/2.1.5-7e27eb0e39.clean
-- Configuring x64-mingw-dynamic
-- Building x64-mingw-dynamic-dbg
-- Building x64-mingw-dynamic-rel
-- Fixing pkgconfig file: C:/vcpkg/packages/libjpeg-turbo_x64-mingw-dynamic/lib/pkgconfig/libjpeg.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/libjpeg-turbo_x64-mingw-dynamic/lib/pkgconfig/libturbojpeg.pc
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at C:/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Fixing pkgconfig file: C:/vcpkg/packages/libjpeg-turbo_x64-mingw-dynamic/debug/lib/pkgconfig/libjpeg.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/libjpeg-turbo_x64-mingw-dynamic/debug/lib/pkgconfig/libturbojpeg.pc
-- Installing: C:/vcpkg/packages/libjpeg-turbo_x64-mingw-dynamic/share/libjpeg-turbo/copyright
-- Performing post-build validation
The following files were built for an incorrect architecture:

    C:\vcpkg\packages\libjpeg-turbo_x64-mingw-dynamic\debug\bin\libjpeg-62.dll
Expected x64, but was: x86

    C:\vcpkg\packages\libjpeg-turbo_x64-mingw-dynamic\debug\bin\libturbojpeg.dll
Expected x64, but was: x86

    C:\vcpkg\packages\libjpeg-turbo_x64-mingw-dynamic\bin\libjpeg-62.dll
Expected x64, but was: x86

    C:\vcpkg\packages\libjpeg-turbo_x64-mingw-dynamic\bin\libturbojpeg.dll
Expected x64, but was: x86

Found 1 post-build check problem(s). To submit these ports to curated catalogs, please first correct the portfile:
    C:\vcpkg\ports\libjpeg-turbo\portfile.cmake
-- Performing post-build validation done
Stored binary cache: "C:\Users\SURE\AppData\Local\vcpkg\archives\98\989f5e49ce181bfb242539c91c4dfcf852c9ddd212ae2c0c8757a77b1ceb525d.zip"
Elapsed time to handle libjpeg-turbo:x64-mingw-dynamic: 10 s
Installing 2/8 liblzma:x64-mingw-dynamic...
Building liblzma[core]:x64-mingw-dynamic...
warning: -- Using community triplet x64-mingw-dynamic. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\vcpkg\triplets\community\x64-mingw-dynamic.cmake
-- Using cached xz-5.4.1.tar.xz.
-- Extracting source C:/vcpkg/downloads/xz-5.4.1.tar.xz
-- Applying patch fix_config_include.patch
-- Applying patch win_output_name.patch
-- Applying patch add_support_ios.patch
-- Applying patch build-tools.patch
-- Using source at C:/vcpkg/buildtrees/liblzma/src/f890ee5207-326fe62969.clean
-- Configuring x64-mingw-dynamic
-- Building x64-mingw-dynamic-dbg
-- Building x64-mingw-dynamic-rel
-- Fixing pkgconfig file: C:/vcpkg/packages/liblzma_x64-mingw-dynamic/lib/pkgconfig/liblzma.pc
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at C:/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Fixing pkgconfig file: C:/vcpkg/packages/liblzma_x64-mingw-dynamic/debug/lib/pkgconfig/liblzma.pc
-- Installing: C:/vcpkg/packages/liblzma_x64-mingw-dynamic/share/liblzma/copyright
-- Performing post-build validation
The following files were built for an incorrect architecture:

    C:\vcpkg\packages\liblzma_x64-mingw-dynamic\debug\bin\liblzma.dll
Expected x64, but was: x86

    C:\vcpkg\packages\liblzma_x64-mingw-dynamic\bin\liblzma.dll
Expected x64, but was: x86

Found 1 post-build check problem(s). To submit these ports to curated catalogs, please first correct the portfile:
    C:\vcpkg\ports\liblzma\portfile.cmake
-- Performing post-build validation done
Stored binary cache: "C:\Users\SURE\AppData\Local\vcpkg\archives\3e\3ef6b26dbdb3db5b3dc209a5ee46e7c2d8defe17f43431d29a55c8554e19127f.zip"
Elapsed time to handle liblzma:x64-mingw-dynamic: 9.867 s
Installing 3/8 libpng:x64-mingw-dynamic...
Building libpng[core]:x64-mingw-dynamic...
warning: -- Using community triplet x64-mingw-dynamic. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\vcpkg\triplets\community\x64-mingw-dynamic.cmake
-- Using cached glennrp-libpng-v1.6.39.tar.gz.
-- Extracting source C:/vcpkg/downloads/glennrp-libpng-v1.6.39.tar.gz
-- Applying patch cmake.patch
-- Applying patch fix-export-targets.patch
-- Applying patch pkgconfig.patch
-- Applying patch fix-msa-support-for-mips.patch
-- Using source at C:/vcpkg/buildtrees/libpng/src/v1.6.39-a77eb96d39.clean
-- Configuring x64-mingw-dynamic
-- Building x64-mingw-dynamic-dbg
-- Building x64-mingw-dynamic-rel
-- Installing: C:/vcpkg/packages/libpng_x64-mingw-dynamic/share/png/vcpkg-cmake-wrapper.cmake
-- Fixing pkgconfig file: C:/vcpkg/packages/libpng_x64-mingw-dynamic/lib/pkgconfig/libpng16.pc
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at C:/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Fixing pkgconfig file: C:/vcpkg/packages/libpng_x64-mingw-dynamic/debug/lib/pkgconfig/libpng16.pc
-- Installing: C:/vcpkg/packages/libpng_x64-mingw-dynamic/debug/lib/pkgconfig/libpng.pc
-- Installing: C:/vcpkg/packages/libpng_x64-mingw-dynamic/lib/pkgconfig/libpng.pc
-- Installing: C:/vcpkg/packages/libpng_x64-mingw-dynamic/share/libpng/usage
-- Installing: C:/vcpkg/packages/libpng_x64-mingw-dynamic/share/libpng/copyright
-- Performing post-build validation
The following files were built for an incorrect architecture:

    C:\vcpkg\packages\libpng_x64-mingw-dynamic\debug\bin\libpng16d.dll
Expected x64, but was: x86

    C:\vcpkg\packages\libpng_x64-mingw-dynamic\bin\libpng16.dll
Expected x64, but was: x86

Found 1 post-build check problem(s). To submit these ports to curated catalogs, please first correct the portfile:
    C:\vcpkg\ports\libpng\portfile.cmake
-- Performing post-build validation done
Stored binary cache: "C:\Users\SURE\AppData\Local\vcpkg\archives\ca\cae320666989fa4d7f3382ae754deb28504ad21d6825e1b76e3f03cf7eac0288.zip"
Elapsed time to handle libpng:x64-mingw-dynamic: 5.003 s
Installing 4/8 libwebp:x64-mingw-dynamic...
Building libwebp[core,libwebpmux,nearlossless,simd,unicode]:x64-mingw-dynamic...
warning: -- Using community triplet x64-mingw-dynamic. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\vcpkg\triplets\community\x64-mingw-dynamic.cmake
-- Using cached webmproject-libwebp-v1.3.0.tar.gz.
-- Extracting source C:/vcpkg/downloads/webmproject-libwebp-v1.3.0.tar.gz
-- Applying patch 0002-cmake-config.patch
-- Applying patch 0007-fix-arm-build.patch
-- Applying patch 0008-sdl.patch
-- Applying patch 0010-fix_build.patch
-- Using source at C:/vcpkg/buildtrees/libwebp/src/v1.3.0-907b664bb7.clean
-- Configuring x64-mingw-dynamic
-- Building x64-mingw-dynamic-dbg
-- Building x64-mingw-dynamic-rel
-- Fixing pkgconfig file: C:/vcpkg/packages/libwebp_x64-mingw-dynamic/lib/pkgconfig/libsharpyuv.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/libwebp_x64-mingw-dynamic/lib/pkgconfig/libwebp.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/libwebp_x64-mingw-dynamic/lib/pkgconfig/libwebpdecoder.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/libwebp_x64-mingw-dynamic/lib/pkgconfig/libwebpdemux.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/libwebp_x64-mingw-dynamic/lib/pkgconfig/libwebpmux.pc
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at C:/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Fixing pkgconfig file: C:/vcpkg/packages/libwebp_x64-mingw-dynamic/debug/lib/pkgconfig/libsharpyuv.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/libwebp_x64-mingw-dynamic/debug/lib/pkgconfig/libwebp.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/libwebp_x64-mingw-dynamic/debug/lib/pkgconfig/libwebpdecoder.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/libwebp_x64-mingw-dynamic/debug/lib/pkgconfig/libwebpdemux.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/libwebp_x64-mingw-dynamic/debug/lib/pkgconfig/libwebpmux.pc
-- Installing: C:/vcpkg/packages/libwebp_x64-mingw-dynamic/share/libwebp/usage
-- Installing: C:/vcpkg/packages/libwebp_x64-mingw-dynamic/share/libwebp/copyright
-- Performing post-build validation
The following files were built for an incorrect architecture:

    C:\vcpkg\packages\libwebp_x64-mingw-dynamic\debug\bin\libsharpyuv.dll
Expected x64, but was: x86

    C:\vcpkg\packages\libwebp_x64-mingw-dynamic\debug\bin\libwebp.dll
Expected x64, but was: x86

    C:\vcpkg\packages\libwebp_x64-mingw-dynamic\debug\bin\libwebpdecoder.dll
Expected x64, but was: x86

    C:\vcpkg\packages\libwebp_x64-mingw-dynamic\debug\bin\libwebpdemux.dll
Expected x64, but was: x86

    C:\vcpkg\packages\libwebp_x64-mingw-dynamic\debug\bin\libwebpmux.dll
Expected x64, but was: x86

    C:\vcpkg\packages\libwebp_x64-mingw-dynamic\bin\libsharpyuv.dll
Expected x64, but was: x86

    C:\vcpkg\packages\libwebp_x64-mingw-dynamic\bin\libwebp.dll
Expected x64, but was: x86

    C:\vcpkg\packages\libwebp_x64-mingw-dynamic\bin\libwebpdecoder.dll
Expected x64, but was: x86

    C:\vcpkg\packages\libwebp_x64-mingw-dynamic\bin\libwebpdemux.dll
Expected x64, but was: x86

    C:\vcpkg\packages\libwebp_x64-mingw-dynamic\bin\libwebpmux.dll
Expected x64, but was: x86

Found 1 post-build check problem(s). To submit these ports to curated catalogs, please first correct the portfile:
    C:\vcpkg\ports\libwebp\portfile.cmake
-- Performing post-build validation done
Stored binary cache: "C:\Users\SURE\AppData\Local\vcpkg\archives\b3\b3429eb8e9bfde15cf329c996bed13d5294df2feb22fab99c67ec770d997205d.zip"
Elapsed time to handle libwebp:x64-mingw-dynamic: 19.15 s
Installing 5/8 protobuf:x64-mingw-dynamic...
Building protobuf[core]:x64-mingw-dynamic...
warning: -- Using community triplet x64-mingw-dynamic. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\vcpkg\triplets\community\x64-mingw-dynamic.cmake
-- Using cached protocolbuffers-protobuf-v3.21.12.tar.gz.
-- Extracting source C:/vcpkg/downloads/protocolbuffers-protobuf-v3.21.12.tar.gz
-- Applying patch fix-static-build.patch
-- Applying patch fix-default-proto-file-path.patch
-- Applying patch compile_options.patch
-- Using source at C:/vcpkg/buildtrees/protobuf/src/v3.21.12-fdb7676342.clean
-- Configuring x64-mingw-dynamic
-- Building x64-mingw-dynamic-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j21
    Working Directory: C:/vcpkg/buildtrees/protobuf/x64-mingw-dynamic-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\protobuf\install-x64-mingw-dynamic-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/protobuf/portfile.cmake:48 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building protobuf:x64-mingw-dynamic failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+protobuf
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[protobuf]+Build+error
Include '[protobuf] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-10-17-3247920fbdd47d08f36cbd480addd9890d3c2435
    vcpkg-scripts version: 2137cb6c6 2023-02-13 (13 minutes ago)

Please use the prefilled template from C:\vcpkg\installed\vcpkg\issue_body.md when reporting your issue.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.
[config-x64-mingw-dynamic-out.log](https://github.com/microsoft/vcpkg/files/10723953/config-x64-mingw-dynamic-out.log)

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
