### ISSUE TITLE
[harfbuzz] failed - freetype (symbol png; symbol BZ2)

### ISSUE THREAD

**Issue by Voskrese** [microsoft/vcpkg#2964]
:x64-windows-static
```
LINK: command "C:\PROGRA~2\MIB055~1\2017\ENTERP~2\VC\Tools\MSVC\1412~1.258\bin\Hostx64\x64\link.exe CMakeFiles\test-would-substitute.dir\src\test-would-substitute.cc.obj /out:test-would-substitute.exe /implib:test-would-substitute.lib /pdb:test-would-substitute.pdb /version:0.0 /machine:x64 /DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF /subsystem:console harfbuzz.lib E:\tools\vcpkg\installed\x64-windows-static\lib\freetype.lib E:\tools\vcpkg\installed\x64-windows-static\lib\glib-2.0.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:test-would-substitute.exe.manifest" failed (exit code 1120) with the following output:
Microsoft (R) Incremental Linker Version 14.12.25835.0
Copyright (C) Microsoft Corporation.  All rights reserved.

freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_create_read_struct referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_set_longjmp_fn referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_create_info_struct referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_read_info referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_set_expand_gray_1_2_4_to_8 referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_set_palette_to_rgb referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_set_tRNS_to_alpha referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_set_gray_to_rgb referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_set_filler referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_set_packing referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_set_interlace_handling referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_set_strip_16 referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_read_update_info referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_read_image referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_read_end referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_destroy_read_struct referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_get_error_ptr referenced in function error_callback
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_set_read_fn referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_get_io_ptr referenced in function read_data_from_FT_Stream
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_set_read_user_transform_fn referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_error referenced in function read_data_from_FT_Stream
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_get_valid referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_get_IHDR referenced in function Load_SBit_Png
freetype.lib(ftgzip.c.obj) : error LNK2019: unresolved external symbol inflate referenced in function FT_Gzip_Uncompress
freetype.lib(ftgzip.c.obj) : error LNK2019: unresolved external symbol inflateEnd referenced in function FT_Gzip_Uncompress
freetype.lib(ftgzip.c.obj) : error LNK2019: unresolved external symbol inflateReset referenced in function ft_gzip_file_io
freetype.lib(ftgzip.c.obj) : error LNK2019: unresolved external symbol inflateInit2_ referenced in function FT_Gzip_Uncompress
freetype.lib(ftbzip2.c.obj) : error LNK2019: unresolved external symbol BZ2_bzDecompressInit referenced in function FT_Stream_OpenBzip2
freetype.lib(ftbzip2.c.obj) : error LNK2019: unresolved external symbol BZ2_bzDecompress referenced in function ft_bzip2_file_fill_output
freetype.lib(ftbzip2.c.obj) : error LNK2019: unresolved external symbol BZ2_bzDecompressEnd referenced in function ft_bzip2_file_done
test-would-substitute.exe : fatal error LNK1120: 30 unresolved externals
[65/83] cmd.exe /C "cd . && E:\tools\vcpkg\downloads\cmake-3.10.2-win32-x86\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\test-test.dir --manifests  -- C:\PROGRA~2\MIB055~1\2017\ENTERP~2\VC\Tools\MSVC\1412~1.258\bin\Hostx64\x64\link.exe  CMakeFiles\test-test.dir\src\test.cc.obj  /out:test-test.exe /implib:test-test.lib /pdb:test-test.pdb /version:0.0  /machine:x64 /DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF /subsystem:console  harfbuzz.lib E:\tools\vcpkg\installed\x64-windows-static\lib\freetype.lib E:\tools\vcpkg\installed\x64-windows-static\lib\glib-2.0.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
FAILED: test-test.exe 
```

**Comment by Voskrese** [comment]
сделал откат на vcpkg-db5a74c7d7c676a4b60284b0dae304ecad0b16f5 и сборка прошла успешно
в коде не разбирался

**Comment by JackBoosY** [comment]
When I installed qt5-declarative with x64-windows-static, errors occurred:
```
   Creating library ..\..\bin\qml.lib and object ..\..\bin\qml.exp
freetyped.lib(ftbzip2.c.obj) : error LNK2019: unresolved external symbol BZ2_bzDecompressInit referenced in function ft_bzip2_file_init
freetyped.lib(ftbzip2.c.obj) : error LNK2019: unresolved external symbol BZ2_bzDecompress referenced in function ft_bzip2_file_fill_output
freetyped.lib(ftbzip2.c.obj) : error LNK2019: unresolved external symbol BZ2_bzDecompressEnd referenced in function ft_bzip2_file_done
..\..\bin\qml.exe : fatal error LNK1120: 3 unresolved externals
   Creating library ..\..\bin\qmleasing.lib and object ..\..\bin\qmleasing.exp
freetyped.lib(ftbzip2.c.obj) : error LNK2019: unresolved external symbol BZ2_bzDecompressInit referenced in function ft_bzip2_file_init
freetyped.lib(ftbzip2.c.obj) : error LNK2019: unresolved external symbol BZ2_bzDecompress referenced in function ft_bzip2_file_fill_output
freetyped.lib(ftbzip2.c.obj) : error LNK2019: unresolved external symbol BZ2_bzDecompressEnd referenced in function ft_bzip2_file_done
..\..\bin\qmleasing.exe : fatal error LNK1120: 3 unresolved externals
```

**Comment by JackBoosY** [comment]
PR #5853 should fixed this issue, but it appears in qt5 now.

**Comment by JackBoosY** [comment]
This issue should be fixed by PR #7667.
Can you repro it now?

Thanks.

**Comment by Voskrese** [comment]
I believe you
close ))

**Comment by b762927** [comment]
> Hello，when I comply freetype and harfbuzz，I also meet these errors， how do you solve it？
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_create_read_struct referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_set_longjmp_fn referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_create_info_struct referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_read_info referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_set_expand_gray_1_2_4_to_8 referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_set_palette_to_rgb referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_set_tRNS_to_alpha referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_set_gray_to_rgb referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_set_filler referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_set_packing referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_set_interlace_handling referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_set_strip_16 referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_read_update_info referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_read_image referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_read_end referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_destroy_read_struct referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_get_error_ptr referenced in function error_callback
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_set_read_fn referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_get_io_ptr referenced in function read_data_from_FT_Stream
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_set_read_user_transform_fn referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_error referenced in function read_data_from_FT_Stream
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_get_valid referenced in function Load_SBit_Png
freetype.lib(sfnt.c.obj) : error LNK2019: unresolved external symbol png_get_IHDR referenced in function Load_SBit_Png
freetype.lib(ftgzip.c.obj) : error LNK2019: unresolved external symbol inflate referenced in function FT_Gzip_Uncompress
freetype.lib(ftgzip.c.obj) : error LNK2019: unresolved external symbol inflateEnd referenced in function FT_Gzip_Uncompress
freetype.lib(ftgzip.c.obj) : error LNK2019: unresolved external symbol inflateReset referenced in function ft_gzip_file_io
freetype.lib(ftgzip.c.obj) : error LNK2019: unresolved external symbol inflateInit2_ referenced in function FT_Gzip_Uncompress
freetype.lib(ftbzip2.c.obj) : error LNK2019: unresolved external symbol BZ2_bzDecompressInit referenced in function FT_Stream_OpenBzip2
freetype.lib(ftbzip2.c.obj) : error LNK2019: unresolved external symbol BZ2_bzDecompress referenced in function ft_bzip2_file_fill_output
freetype.lib(ftbzip2.c.obj) : error LNK2019: unresolved external symbol BZ2_bzDecompressEnd referenced in function ft_bzip2_file_done
test-would-substitute.exe : fatal error LNK1120: 30 unresolved externals

**Comment by JackBoosY** [comment]
@b762927 please open an new issue to report that.
