### ISSUE TITLE
`find_program(SHELL bash)` fail on win10

### ISSUE THREAD

**Issue by shithappens2016** [microsoft/vcpkg#29649]
```bash
vcpkg install ffmpeg:x64-android

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: SHELL-NOTFOUND ./build.sh
    Working Directory: C:/dev/vcpkg/buildtrees/ffmpeg/x64-android-rel

Call Stack (most recent call first):
  ports/ffmpeg/portfile.cmake:596 (vcpkg_execute_required_process)
  scripts/ports.cmake:147 (include)
```

**Comment by shithappens2016** [comment]
#27805

#23558

@LilyWangLL 

It looks like this issue has never been solved

**Comment by LilyWangLL** [comment]
`x64-android` is a community triplet, and I don't have the environment to test it. About community triplet, their codes are always provide by users.

**Comment by JackBoosY** [comment]
https://github.com/microsoft/vcpkg/blob/93895b28ea7bc8cda10f156c5d336f3fc070f8b1/ports/ffmpeg/portfile.cmake#L47-L54

Maybe this need to be fixed. cc @cenit @Sibras

**Comment by cenit** [comment]
sorry i don't have the environment to test it

**Comment by dg0yt** [comment]
This needs to be `VCPKG_HOST_IS_WINDOWS`.

**Comment by Sibras** [comment]
> This needs to be `VCPKG_HOST_IS_WINDOWS`.

I also dont have the environment to test, but it looks like a cross compiling issue so the above solution seems to be suitable

**Comment by dg0yt** [comment]
... it will be sufficiently tested in CI. The current code would also break mingw builds on linux.
