### ISSUE TITLE
vcpkg install opencv4:x64-linux  abort error:  [at-spi2-atk] Build error

### ISSUE THREAD

**Issue by HoMiGT** [microsoft/vcpkg#29648]
**centos7**

- OS: linux
- Compiler: 8.3

`vcpkg install opencv4:x64-linux`

**Failure logs**

Installing 1/26 at-spi2-atk:x64-linux...
Building at-spi2-atk[core]:x64-linux...
-- at-spi2-atk currently requires the following libraries from the system package manager:
    libdbus-1

These can be installed on Ubuntu systems via apt-get install libdbus-1-dev
-- Using cached GNOME-at-spi2-atk-AT_SPI2_ATK_2_38_0.tar.gz.
-- Cleaning sources at /home/wpwl/Softwares/vcpkg/buildtrees/at-spi2-atk/src/ATK_2_38_0-a131295237.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/wpwl/Softwares/vcpkg/downloads/GNOME-at-spi2-atk-AT_SPI2_ATK_2_38_0.tar.gz
-- Using source at /home/wpwl/Softwares/vcpkg/buildtrees/at-spi2-atk/src/ATK_2_38_0-a131295237.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Configuring x64-linux-dbg
-- Configuring x64-linux-dbg done
-- Configuring x64-linux-rel
-- Configuring x64-linux-rel done
-- Package x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/ninja install -v
    Working Directory: /home/wpwl/Softwares/vcpkg/buildtrees/at-spi2-atk/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /home/wpwl/Softwares/vcpkg/buildtrees/at-spi2-atk/package-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
  ports/at-spi2-atk/portfile.cmake:19 (vcpkg_install_meson)
  scripts/ports.cmake:147 (include)

error: building at-spi2-atk:x64-linux failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+at-spi2-atk
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[at-spi2-atk]+Build+error
Include '[at-spi2-atk] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 25f613278 2023-02-13 (13 hours ago)

Please use the prefilled template from /home/wpwl/Softwares/vcpkg/installed/vcpkg/issue_body.md when reporting your issue.

I don't know how to solve it. Has anyone ever encountered this problem?

**Comment by JackBoosY** [comment]
Provide _/home/wpwl/Softwares/vcpkg/buildtrees/at-spi2-atk/package-x64-linux-dbg-out.log_ first.

**Comment by HoMiGT** [comment]
Ok, thank you. I submitted a new issue and searched it all day, but it still hasn't been solved

**Comment by Adela0814** [comment]
You may have closed the issue by mistake. I reopened it. Please provide the full failure logs. Thanks.
`/home/wpwl/Softwares/vcpkg/buildtrees/at-spi2-atk/package-x64-linux-dbg-out.log`

**Comment by Adela0814** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
