### ISSUE TITLE
Fail to install chromium-base

### ISSUE THREAD

**Issue by SAURABHS1993** [microsoft/vcpkg#29676]
**Host Environment**

- OS: Windows
- Compiler: MSVC(Visual Studio 2019)

**To Reproduce**

`./vcpkg install chromium-base --triplet="x64-windows"`

**Failure logs**
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/tets/vcpkg/installed/x64-windows/tools/gn/gn.exe gen C:/tets/vcpkg/buildtrees/chromium-base/x64-windows-dbg "--args=     use_custom_libcxx=false     clang_use_chrome_plugins=false     forbid_non_component_debug_builds=false     treat_warnings_as_errors=false use_lld=false clang_base_path=\"C:/tets/vcpkg/downloads/tools/clang/clang-15.0.6\" is_component_build=true is_debug=true symbol_level=2"
    Working Directory: C:/tets/vcpkg/buildtrees/chromium-base/src/25ce732
    Error code: 1
    See logs for more information:
      C:\tets\vcpkg\buildtrees\chromium-base\generate-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-gn/vcpkg_gn_configure.cmake:11 (vcpkg_execute_required_process)
  installed/x64-windows/share/vcpkg-gn/vcpkg_gn_configure.cmake:35 (z_vcpkg_gn_configure_generate)
  ports/chromium-base/portfile.cmake:113 (vcpkg_gn_configure)
  scripts/ports.cmake:147 (include)

**generate-x64-windows-dbg-out.log**:
ERROR at //build/config/BUILDCONFIG.gn:401:1: Unknown function.
set_sources_assignment_filter(sources_assignment_filter)

**Additional context**

Currently vcpkg seems to be building very old version of Chromium-base(86.0.4199.1) we might need to update it to latest(112.0.5598.0)

**Comment by LilyWangLL** [comment]
cc @vejmartin, the latest source of `chromium` has no longer use `set_sources_assignment_filter`, but I am not very familiar with the code of `chromium-base` and `gn`, do you have some time to update port `chromium-base`?

The related source issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1018739

**Comment by SAURABHS1993** [comment]
Hi Team, is there any update on this issue.

**Comment by luleiray** [comment]
Hello, I got the same issue while building on Windows, please fix it.

**Comment by 0xC05StackOverflow** [comment]
您好，我在Windows上构建时遇到了同样的问题，请修复它。
