### ISSUE TITLE
[openssl] Build error

### ISSUE THREAD

**Issue by talal71** [microsoft/vcpkg#29679]
**Host Environment**

- OS: Windows
  vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 376362d3f 2023-02-15 (35 minutes ago)

**To Reproduce**

`./vcpkg install openssl:x64-windows`

**Failure logs**

error: building openssl:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by scobei** [comment]
Package: openssl[core]:x64-windows -> 3.0.8

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.34.31937.0
-    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 959f8e317 2023-02-15 (78 minutes ago)

**To Reproduce**

`vcpkg install libpq:x64-windows`

**Failure logs**

```
-- Downloading https://github.com/openssl/openssl/archive/openssl-3.0.8.tar.gz -> openssl-openssl-openssl-3.0.8.tar.gz...
-- Cleaning sources at C:/prj/tools/vcpkg/buildtrees/openssl/src/nssl-3.0.8-68504cf2ba.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/prj/tools/vcpkg/downloads/openssl-openssl-openssl-3.0.8.tar.gz
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch windows/umul128-arm64.patch
-- Using source at C:/prj/tools/vcpkg/buildtrees/openssl/src/nssl-3.0.8-68504cf2ba.clean
CMake Error at installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:99 (message):
  vcpkg_cmake_buildsystem_build was passed extra arguments:
  Z_CMAKE_GET_VARS_USAGE
Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake-get-vars/vcpkg_cmake_get_vars.cmake:15 (vcpkg_cmake_configure)
  ports/openssl/windows/portfile.cmake:55 (vcpkg_cmake_get_vars)
  ports/openssl/portfile.cmake:31 (include)
  scripts/ports.cmake:147 (include)



```


**Additional context**

**Comment by JonLiu1993** [comment]
@talal71, Thanks for posting this issue, please provide the detail error log.

**Comment by talal71** [comment]
Package: openssl[core]:x86-windows -> 3.0.8

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.34.31942.0
-    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 376362d3f 2023-02-15 (9 hours ago)

**To Reproduce**

`vcpkg install openssl:x86-windows`

**Failure logs**

```
-- Using cached openssl-openssl-openssl-3.0.8.tar.gz.
-- Cleaning sources at C:/Users/USER/Desktop/flywithlua/vcpkg/buildtrees/openssl/src/nssl-3.0.8-68504cf2ba.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/USER/Desktop/flywithlua/vcpkg/downloads/openssl-openssl-openssl-3.0.8.tar.gz
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch windows/umul128-arm64.patch
-- Using source at C:/Users/USER/Desktop/flywithlua/vcpkg/buildtrees/openssl/src/nssl-3.0.8-68504cf2ba.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x86-windows
-- Getting CMake variables for x86-windows
-- Prerunning x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/Users/USER/Desktop/flywithlua/vcpkg/downloads/tools/perl/5.32.1.1/perl/bin/perl.exe Configure enable-static-engine enable-capieng no-ssl2 no-ssl3 no-weak-ssl-ciphers no-tests shared no-makedepend debug-VC-WIN32 --prefix=C:\\Users\\USER\\Desktop\\flywithlua\\vcpkg\\packages\\openssl_x86-windows\\debug --openssldir=C:\\Users\\USER\\Desktop\\flywithlua\\vcpkg\\packages\\openssl_x86-windows\\debug AS=C:\\Users\\USER\\Desktop\\flywithlua\\vcpkg\\downloads\\tools\\nasm\\nasm-2.16.01\\nasm.exe "CC=C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\bin\\Hostx64\\x86\\cl.exe" "CFLAGS=  -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -MP  -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1  " "AR=C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\bin\\Hostx64\\x86\\lib.exe" "ARFLAGS=-machine:X86 -nologo" "LD=C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\bin\\Hostx64\\x86\\link.exe" "LDFLAGS= -machine:X86 -nologo    -debug -INCREMENTAL "
    Working Directory: C:/Users/USER/Desktop/flywithlua/vcpkg/buildtrees/openssl/x86-windows-dbg
    Error code: 2
    See logs for more information:
      C:\Users\USER\Desktop\flywithlua\vcpkg\buildtrees\openssl\prerun-specific-x86-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_nmake.cmake:125 (vcpkg_execute_required_process)
  ports/openssl/windows/portfile.cmake:69 (vcpkg_build_nmake)
  ports/openssl/portfile.cmake:31 (include)
  scripts/ports.cmake:147 (include)



```
<details><summary>C:\Users\USER\Desktop\flywithlua\vcpkg\buildtrees\openssl\prerun-specific-x86-windows-dbg-err.log</summary>

```
Can't locate strict.pm in @INC (you may need to install the strict module) (@INC contains: C:/Users/USER/Desktop/flywithlua/vcpkg/downloads/tools/perl/5.32.1.1/perl/lib) at Configure line 13.
BEGIN failed--compilation aborted at Configure line 13.
```
</details>

**Additional context**

**Comment by JonLiu1993** [comment]
@talal71, It's not a vcpkg problem, it's your lack of strict module, please try the command to see if it works for you:
`perl -e 'use strict; print "ok"'`

**Comment by talal71** [comment]
C:\Users\USER>perl -e "use strict; print 'ok'"
ok

**Comment by dg0yt** [comment]
> C:\Users\USER>perl -e "use strict; print 'ok'"

Are you sure this is the same `perl` as in `C:/Users/USER/Desktop/flywithlua/vcpkg/downloads/tools/perl...`? The latter normally isn't found via the `PATH`, but you can run it by using the full path to `perl.exe`.
`use strict` is a fundamental part of that language. Maybe a local installation interferes with vcpkg's downloaded perl.

**Comment by satvikpendem** [comment]
I'm getting the same issue on Windows. I don't have perl installed at all.

**Comment by JonLiu1993** [comment]
@satvikpendem, Could you confirm whether perl exists in your `vcpkg\downloads\tools\` path?

**Comment by satvikpendem** [comment]
Yes perl is in the tools path as you mentioned, so it should be using that perl, but not sure why it's not

**Comment by JonLiu1993** [comment]
@satvikpendem, did the command `perl -e ' use strict; print "ok"'` work for you?

**Comment by satvikpendem** [comment]
Yep it did work for me.

**Comment by JonLiu1993** [comment]
@talal71, does this problem still exist?

**Comment by JonLiu1993** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
This issue hasn’t been updated in a year; if it is still an issue, please reopen it.
