### ISSUE TITLE
WARNING: Github has dropped support for TLS versions prior to 1.2, which is not available on your system

### ISSUE THREAD

**Issue by OlafvdSpek** [Microsoft/vcpkg#2969]
I'm using Windows 7.. 
What HTTP client / TLS lib are you using? Chrome works fine for https://github.com/ even MSIE works..

Could you use a client that does support TLS 1.2?

**Comment by jingxa** [comment]
i am too ,that's bug for win7,how to deal it ?

**Comment by lazyhamster** [comment]
Update Powershell to the latest version. For me updating to PS 5.1 on Win7 resolved the problem.

**Comment by alexkaratarakis** [comment]
The error message should be accompanied with a url to manually download the file to work around the issue. I added Powershell 5.1 as another - more permanent - workaround.
fdf8d471ed553fa802db784e1b049cd77e721ce2

**Comment by OlafvdSpek** [comment]
Thx!
But damn, they don't make updating PS easy..

**Comment by ReyzalX** [comment]
I also encountered this problem at win7 and resolved after updating the visual studio to vs2017.

**Comment by OlafvdSpek** [comment]
@alexkaratarakis How is PS 5.1 a workaround? ;)

**Comment by alexkaratarakis** [comment]
@OlafvdSpek You are right; should have said "solution". :)

**Comment by OlafvdSpek** [comment]
Perhaps a link to download PS 5.1 would be helpful in the message.

Does it even make sense to suggest manually downloading stuff from github?

**Comment by alexkaratarakis** [comment]
@OlafvdSpek 
We have switched to using `aria2` for downloads in powershell. Of course, that means we have to first download aria2 in the old fashioned way, so for Windows 7 that means manually downloading it. But after that first download, subsequent downloads should just work.
