### ISSUE TITLE
[glib] Build error

### ISSUE THREAD

**Issue by galbro** [microsoft/vcpkg#29698]
vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 547c030 2023-02-16 (24 minutes ago)

**Host Environment**

- OS: Ubuntu 16.04 WSL on Windows 10
- Compiler: gcc version 5.5.0 20171010 (Ubuntu 5.5.0-12ubuntu1~16.04)

`./vcpkg install opencv

**Failure logs**

Building glib[core]:x64-linux...
-- Downloading https://download.gnome.org/sources/glib/2.75/glib-2.75.3.tar.xz -> glib-2.75.3.tar.xz...
-- Extracting source /mnt/g/Local/vcpkg-linux/downloads/glib-2.75.3.tar.xz
-- Applying patch use-libiconv-on-windows.patch
-- Applying patch libintl.patch
-- Using source at /mnt/g/Local/vcpkg-linux/buildtrees/glib/src/glib-2-8ca74e7d19.clean
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/python3 /mnt/c/src/Local/vcpkg-linux/installed/x64-linux/tools/meson/meson.py -Dselinux=disabled -Dlibmount=disabled -Dgtk_doc=false -Dinstalled_tests=false -Dlibelf=disabled -Dman=false -Dtests=false -Dxattr=false --buildtype plain --backend ninja --wrap-mode nodownload --libdir lib --native /mnt/g/Local/vcpkg-linux/buildtrees/glib/meson-x64-linux-dbg.log -Ddebug=true --prefix /mnt/g/Local/vcpkg-linux/packages/glib_x64-linux/debug --includedir ../include -Dcmake_prefix_path=['/mnt/g/Local/vcpkg-linux/installed/x64-linux/debug','/mnt/g/Local/vcpkg-linux/installed/x64-linux'] /mnt/g/Local/vcpkg-linux/buildtrees/glib/src/glib-2-8ca74e7d19.clean
    Working Directory: /mnt/g/Local/vcpkg-linux/buildtrees/glib/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /mnt/g/Local/vcpkg-linux/buildtrees/glib/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:433 (vcpkg_execute_required_process)
  ports/glib/portfile.cmake:31 (vcpkg_configure_meson)
  scripts/ports.cmake:147 (include)

- Attach ***every failure log file*** mentioned in the console output.

$ cat  /mnt/g/Local/vcpkg-linux/buildtrees/glib/config-x64-linux-dbg-err.log
Traceback (most recent call last):
  File "/mnt/c/src/Local/vcpkg-linux/installed/x64-linux/tools/meson/meson.py", line 26, in <module>
    from mesonbuild import mesonmain
  File "/mnt/g/Local/vcpkg-linux/installed/x64-linux/tools/meson/mesonbuild/mesonmain.py", line 205
    mlog.error(f'Error in {script_name} helper script:')
                                                      ^
SyntaxError: invalid syntax

**Comment by StarGate-One** [comment]
> - Attach **_every failure log file_** mentioned in the console output.
> /mnt/g/Local/vcpkg-linux/buildtrees/glib/config-x64-linux-dbg-err.log

**Comment by FrankXie05** [comment]
@galbro Have you installed python3？

**Comment by galbro** [comment]
> > * Attach **_every failure log file_** mentioned in the console output.
> >   /mnt/g/Local/vcpkg-linux/buildtrees/glib/config-x64-linux-dbg-err.log

The whole failure log was 7 lines, so I had inlined it. It's attached now.

**Comment by galbro** [comment]
> @galbro Have you installed python3？

Yes, that was the first thing I thought about. I even went back and set up the aliasing so that "python" launches "python3".

administrator@JALBRO:/mnt/c/src/Local/vcpkg-linux$ python
Python 3.5.2 (default, Jan 26 2021, 13:30:48)
[GCC 5.4.0 20160609] on linux

I was able to get past this on a WSL images of Ubuntu 20 and Ubuntu 22, which have Python 3.8.10 and Python 3.10.6 respectively.

I'm going to try to get a later Python on to my Ubuntu 16 image, that should do it.

**Comment by galbro** [comment]
I built Python 3.8 from source, then set it as the preferred alternative for python3 with "sudo update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.8 1"

This has resolved the issue. There must be a (inadvertant?) python language dependency in the build scripts somewhere.

**Comment by StarGate-One** [comment]
> > > * Attach **_every failure log file_** mentioned in the console output.
> > >   /mnt/g/Local/vcpkg-linux/buildtrees/glib/config-x64-linux-dbg-err.log
> 
> The whole failure log was 7 lines, so I had inlined it. It's attached now.

I apologize @galbro. Even though I read through the original post line-by-line I did not recognize it.

**Comment by galbro** [comment]
No problem

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dg0yt** [comment]
> There must be a (inadvertant?) python language dependency in the build scripts somewhere.

The python requirement is from the meson build system used by glib.
On my Ubuntu 18.04 machine I build and use the python3 port.

**Comment by FrankXie05** [comment]
> This has resolved the issue. There must be a (inadvertant?) python language dependency in the build scripts somewhere.

Maybe we should add a warning message about the python version request. 🤔

**Comment by FrankXie05** [comment]
@galbro 
>This has resolved the issue. There must be a (inadvertant?) python language dependency in the build scripts somewhere.

For the `meson` build of vcpkg, we will automatically detect and download the `python3` environment.
https://github.com/microsoft/vcpkg/blob/07da05c20c56d3df4b488a16d5bcfeebb761e754/scripts/cmake/vcpkg_configure_meson.cmake#L328

Close this issue by 
> This has resolved the issue.
