### ISSUE TITLE
SDL2:arm-uwp broken

### ISSUE THREAD

**Issue by janisozaur** [Microsoft/vcpkg#2970]
vcpkg: 6f5573e889c4125f15fff0ee63b60ebcb79fed2f

SDL2 fails to build with `arm-uwp` triplet.

Likely a regression from https://github.com/Microsoft/vcpkg/pull/2934, as I vaguely recall it building correctly earlier.

See the attached logs.

[config-arm-uwp-out.log](https://github.com/Microsoft/vcpkg/files/1782681/config-arm-uwp-out.log)

[install-arm-uwp-dbg-out.log](https://github.com/Microsoft/vcpkg/files/1782682/install-arm-uwp-dbg-out.log)

**Comment by janisozaur** [comment]
cf. https://github.com/Microsoft/vcpkg/issues/2239

**Comment by PhoebeHui** [comment]
@janisozaur, does the issue still occur?

./vcpkg install sdl2:arm-uwp installed successfully with vcpkg latest source and Visual studio 2017 15.9.7.

S F:\vcpkg\src> ./vcpkg version
Vcpkg package management program version 2018.11.23-nohash

PS F:\vcpkg\src> ./vcpkg install sdl2:arm-uwp
The following packages will be built and installed:
    sdl2[core]:arm-uwp
Starting package 1/1: sdl2:arm-uwp
Building package sdl2[core]:arm-uwp...
-- Downloading https://github.com/SDL-Mirror/SDL/archive/release-2.0.9.tar.gz...
-- Extracting source F:/VCPKG/src/downloads/SDL-Mirror-SDL-release-2.0.9.tar.gz
-- Applying patch export-symbols-only-in-shared-build.patch
-- Applying patch fix-x86-windows.patch
-- Applying patch enable-winrt-cmake.patch
-- Using source at F:/VCPKG/src/buildtrees/sdl2/src/ease-2.0.9-ad425106c1
-- Configuring arm-uwp
-- Building arm-uwp-dbg
-- Building arm-uwp-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package sdl2[core]:arm-uwp... done
Installing package sdl2[core]:arm-uwp...
Installing package sdl2[core]:arm-uwp... done
Elapsed time for package sdl2:arm-uwp: 1.96 min

Total elapsed time: 1.96 min

The package sdl2:arm-uwp provides CMake targets:
    find_package(SDL2 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE SDL2::SDL2)

**Comment by JackBoosY** [comment]
Hi @janisozaur , thanks for reporting this issue.
Please open a new issue if this is still a problem for you.
Thx.
