### ISSUE TITLE
[icu] Build error

### ISSUE THREAD

**Issue by sstarr-vadax** [microsoft/vcpkg#29706]
**Host Environment**

- OS: Fedors 37
- Compiler: gcc-12.2.1-4

**To Reproduce**
vcpkg install skia
or
vcpkg install icu

**Failure logs**
Logfile: autoconf-x64-linux-err.log

autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: /usr/bin/autoconf --force
configure.ac:13: warning: AC_INIT: unsafe as a filename: "International Components for Unicode"
configure.ac:1435: warning: AC_C_BIGENDIAN should be used with AC_CONFIG_HEADERS
autoreconf: configure.ac: not using Autoheader
autoreconf: configure.ac: not using Automake
autoreconf: './config.sub' is updated
autoreconf: './config.guess' is updated
autoreconf: './install-sh' is updated
autoreconf: Leaving directory '.'
t.

Terminal Error Message

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/bash -c "V=1 ./../src/c-72_1-src-deba61ed52.clean/source/configure  \"--disable-samples\" \"--disable-tests\" \"--disable-layoutex\" \"--enable-tools\" \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"--enable-debug\" \"--disable-release\" \"--prefix=/home/stevenstarr/Projects/Vadax/build/vcpkg/installed/x64-linux/debug\" \"--bindir=\\${prefix}/../tools/icu/debug/bin\" \"--sbindir=\\${prefix}/../tools/icu/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/icu\""
    Working Directory: /home/stevenstarr/Projects/Vadax/build/vcpkg/buildtrees/icu/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /home/stevenstarr/Projects/Vadax/build/vcpkg/buildtrees/icu/config-x64-linux-dbg-config.log
      /home/stevenstarr/Projects/Vadax/build/vcpkg/buildtrees/icu/config-x64-linux-dbg-out.log
      /home/stevenstarr/Projects/Vadax/build/vcpkg/buildtrees/icu/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:812 (vcpkg_execute_required_process)
  ports/icu/portfile.cmake:55 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)

error: building icu:x64-linux failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+icu
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[icu]+Build+error
Include '[icu] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 9aa0d6637 2023-02-16 (9 hours ago)

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Cheney-W** [comment]
Could you please provide the `/home/stevenstarr/Projects/Vadax/build/vcpkg/buildtrees/icu/config-x64-linux-dbg-err.log` file? Thank you!

**Comment by Cheney-W** [comment]
Thanks for posting this issue. Please reopen this issue and provide us with the detailed info of this issue if it is still a problem for you.
