### ISSUE TITLE
[zstd] build failure

### ISSUE THREAD

**Issue by hushanjushi** [microsoft/vcpkg#29718]
**Host Environment**

- OS: Debian Sid WSL
- Compiler: em++

**To Reproduce**

`./vcpkg install zstd --triplet=wasm32-emscripten`

-- [COMMUNITY] Loading triplet configuration from: /home/saltyfish/tools/vcpkg/triplets/community/wasm32-emscripten.cmake
-- Using cached facebook-zstd-v1.5.4.tar.gz.
-- Cleaning sources at /home/saltyfish/tools/vcpkg/buildtrees/zstd/src/v1.5.4-75b26c3dfe.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/saltyfish/tools/vcpkg/downloads/facebook-zstd-v1.5.4.tar.gz
-- Applying patch no-static-suffix.patch
-- Using source at /home/saltyfish/tools/vcpkg/buildtrees/zstd/src/v1.5.4-75b26c3dfe.clean
-- Found external ninja('1.11.1').
-- Configuring wasm32-emscripten
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/ninja -v
    Working Directory: /home/saltyfish/tools/vcpkg/buildtrees/zstd/wasm32-emscripten-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      /home/saltyfish/tools/vcpkg/buildtrees/zstd/config-wasm32-emscripten-dbg-CMakeCache.txt.log
      /home/saltyfish/tools/vcpkg/buildtrees/zstd/config-wasm32-emscripten-rel-CMakeCache.txt.log
      /home/saltyfish/tools/vcpkg/buildtrees/zstd/config-wasm32-emscripten-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:248 (vcpkg_execute_required_process)
  ports/zstd/portfile.cmake:15 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)

Additional context:
[config-wasm32-emscripten-out.log](https://github.com/microsoft/vcpkg/files/10908722/config-wasm32-emscripten-out.log)
[config-wasm32-emscripten-dbg-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10908732/config-wasm32-emscripten-dbg-CMakeCache.txt.log)
[config-wasm32-emscripten-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10908729/config-wasm32-emscripten-rel-CMakeCache.txt.log)

**Comment by hushanjushi** [comment]
The boost on emscripten broke again....

**Comment by hushanjushi** [comment]
Hello ,anyone see this?

**Comment by dg0yt** [comment]
It is a community triplet. Maybe the wasm community isn't really looking at vcpkg issues. Maybe it is simply unsupported upstream?
It also doesn't help to mix boost into a zstd issue. (boost-array "builds".)

**Comment by hushanjushi** [comment]
> It is a community triplet. Maybe the wasm community isn't really looking at vcpkg issues. Maybe it is simply unsupported upstream? It also doesn't help to mix boost into a zstd issue. (boost-array "builds".)

Ok, I have changed for it. I refer to zstd because boost depends on it
