### ISSUE TITLE
[Pango] build failure on docker while build snap package.

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#29729]
**Host Environment**
Docker image with x64 Linux docker while build snap package.
gcc 9.4.0

- OS: Linux x64
- Compiler: gcc 9.4.0

**To Reproduce**

`./vcpkg install pango`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

```
Building pango[core]:snap-linux-amd64...
-- [OVERLAY] Loading triplet configuration from: /data/parts/boinc/build/3rdParty/vcpkg_ports/triplets/ci/snap-linux-amd64.cmake
-- Downloading https://gitlab.gnome.org//GNOME/pango/-/archive/1.50.12/pango-1.50.12.tar.gz -> GNOME-pango-1.50.12.tar.gz...
-- Extracting source /data/parts/boinc/build/3rdParty/linux/vcpkg/downloads/GNOME-pango-1.50.12.tar.gz
-- Applying patch freetype2-pc.patch
-- Using source at /data/parts/boinc/build/3rdParty/linux/vcpkg/buildtrees/pango/src/1.50.12-653424b278.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for snap-linux-amd64-rel
-- Configuring snap-linux-amd64-rel
-- Configuring snap-linux-amd64-rel done
-- Package snap-linux-amd64-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /data/parts/boinc/build/3rdParty/buildCache/linux/ninja/ninja install -v
    Working Directory: /data/parts/boinc/build/3rdParty/linux/vcpkg/buildtrees/pango/snap-linux-amd64-rel
    Error code: 1
    See logs for more information:
      /data/parts/boinc/build/3rdParty/linux/vcpkg/buildtrees/pango/package-snap-linux-amd64-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
  ports/pango/portfile.cmake:51 (vcpkg_install_meson)
  scripts/ports.cmake:147 (include)
```

[parts.zip](https://github.com/microsoft/vcpkg/files/10773732/parts.zip)

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

the triplet file:
[snap-linux-amd64.cmake.txt](https://github.com/microsoft/vcpkg/files/10773736/snap-linux-amd64.cmake.txt)

`cc1: some warnings being treated as errors`
I don't sure why warnings being treated as errors.
Can you help?

**Comment by dg0yt** [comment]
pango (upstream) sets `-Werror` flags. This is a good idea for development but makes regular build from source fragile depending with regard to varying compiler versions etc.  Someone has to patch `meson.build`.

**Comment by talregev** [comment]
On what version of compiler it compile without warning? 
gcc 11?

**Comment by dg0yt** [comment]
AFAICS vcpkg CI is on Ubuntu 20.04, and it also builds on Ubuntu 18.04. Cf. packages.ubuntu.com for details.
Problems tend to occur with new compiler versions which produce more warnings which are then turned into errors.

**Comment by talregev** [comment]
How can we patch meson.build?

**Comment by dg0yt** [comment]
Example: https://learn.microsoft.com/en-us/vcpkg/examples/patching

**Comment by talregev** [comment]
I know how to patch. I am not sure what to patch.

**Comment by dg0yt** [comment]
Look for `-Werror...` flags and remove them?

**Comment by talregev** [comment]
I just turn off the warning instead. Thank you for your help!
I will leave this issue open, if you want to fix it on pango port. if not, I can close it.

**Comment by talregev** [comment]
I solve this issue by turning off the warning.
