### ISSUE TITLE
include file reference to the vcpkg installed directory name of library not included in all dependent uses of includes

### ISSUE THREAD

**Issue by KirkPen** [microsoft/vcpkg#29723]
I zipped up the visual studio project direcory and attached it so you can see.
Might just be doing  something wrong, but I installed these three and they all have dependencies.
vcpkg install vtk[vtk-qt,cuda,mpi] --recurse
vcpkg install pcl[vtk,visualization] --recurse
vcpkg install opencv[cuda,tbb] --recurse

The project includes have the path appended to include file name so it finds it, but so many other .h files that get used outside of the cpp file have there include files with no path appended to it so they don't find the file. What is the way to make it work please.

windows 10 pro visual studio community 2022

Severity	Code	Description	Line	Project	File	Suppression State
Error (active)	E1696	cannot open source file "vtkSmartPointer.h"	41	Ground-Point-Cloud	D:\Dev\vcpkg\installed\x64-windows\include\pcl\visualization\common\impl\shapes.hpp	

[SandBox2.zip](https://github.com/microsoft/vcpkg/files/10769489/SandBox2.zip)

**Comment by Neumann-A** [comment]
Please use the CMake integration if you use VTK.......

**Comment by KirkPen** [comment]
Is that the manifest mode per project with a json file?

**Comment by KirkPen** [comment]
I just want to be able to use what vcpkg has installed globaly in my d:\dev\vcpkg and not have to download and built install per project as it takes all day to do opencv, pcl, and vtk. The problem is the include files that have include files but no path appended to them like these:
#include <opencv2/opencv.hpp>
#include <librealsense2/rs.hpp>
#include <pcl/point_types.h>
#include <pcl/filters/passthrough.h>
#include <pcl/filters/voxel_grid.h>
#include <pcl/segmentation/sac_segmentation.h>
#include <pcl/filters/extract_indices.h>
#include <pcl/segmentation/extract_clusters.h>
#include <pcl/visualization/cloud_viewer.h>
#include <vtk-9.2/vtkSmartPointer.h>

**Comment by Neumann-A** [comment]
> The problem is the include files that have include files but no path appended to them like these:

again use CMake. CMake will add the correct include paths for those libraries and it will work. If you use MSBuild/Visual Studio integration with those deps you are going to need to add the folders to the Additional Include Directoy property manually. 

> Is that the manifest mode per project with a json file?

Not necessarily. You can use manifest or classic mode with CMake.

**Comment by KirkPen** [comment]
Any guide on how to do it with cmake and visual studio 2022?
I tried adding the additional includes manualy and it still does not see it.

**Comment by KirkPen** [comment]
My fix was to make a new solution/project in visual studio, add the additional include paths, one for vcpkg\include and vcpkg\include\vtk9.2, thanks
