### ISSUE TITLE
[monkeys-audio] Port 9.05 wrong hash + build error

### ISSUE THREAD

**Issue by vividos** [microsoft/vcpkg#29739]
**Describe the bug**

After #29592 was fixed, I wanted to try out that port in my [winLAME ](https://github.com/vividos/winLAME)project. Unfortunately, the AppVeyor build of my project fails:

```
Installing 1/5 monkeys-audio:x86-windows...
  Building monkeys-audio[core]:x86-windows...
  -- Downloading https://monkeysaudio.com/files/MAC_904_SDK.zip -> MAC_904_SDK.zip...
  [DEBUG] To include the environment variables in debug output, pass --debug-env
  [DEBUG] Feature flag 'binarycaching' unset
  [DEBUG] Feature flag 'compilertracking' unset
  [DEBUG] Feature flag 'registries' unset
  [DEBUG] Feature flag 'versions' unset
  Downloading https://monkeysaudio.com/files/MAC_904_SDK.zip
C:\Tools\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: Failed to download from mirror set [C:\projects\winlame\source\winlame\winlame_res0402.vcxproj]
C:\Tools\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: File does not have the expected hash: [C:\projects\winlame\source\winlame\winlame_res0402.vcxproj]
  url: https://monkeysaudio.com/files/MAC_904_SDK.zip
  File: C:\Tools\vcpkg\downloads\MAC_904_SDK.zip.7012.part
  Expected hash: c42c9bae6690a28a69137445c84d53ad7acbd242c2cfe20f329fda46b56812c60de68874301d99cf72ade3bced90fc5aaedacb6fdbca241d4bf4806f6e238219
  Actual hash: d104421e9bfa8c36dee89bd292c06629ff39a33e84569a5578f4a255432238a0cf09a7d03c5f7df3daf0e41d5cf3ac88f3b58581daf09a94935de91056334681
```
(build log available here: https://ci.appveyor.com/project/vividos/winlame)

When I manually correct the hash in the port file, I get a follow-up build error:

```
Building monkeys-audio[core]:x86-windows...
-- Using cached MAC_904_SDK.zip.
-- Extracting source C:/Projekte/Tools/vcpkg/downloads/MAC_904_SDK.zip
-- Applying patch fix-project-config.patch
CMake Error at scripts/cmake/z_vcpkg_apply_patches.cmake:34 (message):
  Applying patch failed: Checking patch
  Source/Projects/VS2019/MACDll/MACDll.vcxproj...

  error: Source/Projects/VS2019/MACDll/MACDll.vcxproj: No such file or
  directory
```

**Environment**
- OS: Windows
- Compiler: Visual Studio 2022 version 17.4.4

**To Reproduce**
1. Start with a fresh vcpkg clone and a clear %LocalAppData%\vcpkg
2. `./vcpkg install monkeys-audio`
3. See hash error
4. Fix the hash in the port file
5. Re-run step 2
6. See build error

**Expected behavior**
Install should work without hash error or build error.

**Failure logs**
See above.

**Additional context**
Hash error:
My guess: In the PR #29709 that fixed #29592, the second URLS line was removed, which still downloaded 6.07, the hash specified was for that older version, not for 9.05. Issue #29187 and PR #29556 was the original update to 9.05.

When I calculate the SHA512 with a manually downloaded zip archive of the SDK, it also calculates the hash as `d10442...`, not the one in the port file.

Build error: It seems the 9.05 version already migrated from VS2019 to VS2022, so the patches can't find the .vcxproj files anymore that they are supposed to patch. This oversight in the original port may come from the erroneous downloaded 6.07 zip that's stored in %LocalAppData%\vcpkg, which is cached as the newer 9.05 SDK.

**Comment by vividos** [comment]
Note: I actually had to clear the vcpkg binary archive under %LocalAppData%\vcpkg, since the wrong zip archive was already downloaded once and was reused at every `.\vcpkg install`.

**Comment by FrankXie05** [comment]
I will fix this today. :)
