### ISSUE TITLE
error: building zlib:x64-windows-static-md failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by tester0077** [microsoft/vcpkg#29742]
**Host Environment**

- OS: [e.g. Windows/Linux etc...]
- Compiler: revision
- Win 11
- MSVC 2022

**To Reproduce**

D:\pkg\vcpkg> ./vcpkg install curl:x64-windows-static-md

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

PS D:\pkg\vcpkg> ./vcpkg upgrade
All installed packages are up-to-date with the local portfile.
PS D:\pkg\vcpkg> ./vcpkg install curl:x86-windows-static-md
Computing installation plan...
The following packages will be built and installed:
    curl[core,non-http,schannel,ssl,sspi]:x86-windows-static-md -> 7.87.0#1
  * zlib[core]:x86-windows-static-md -> 1.2.13
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows-static-md...
Restored 0 package(s) from C:\Users\arnold\AppData\Local\vcpkg\archives in 1.971 ms. Use --debug to see more details.
Installing 1/2 zlib:x86-windows-static-md...
Building zlib[core]:x86-windows-static-md...
warning: -- Using community triplet x86-windows-static-md. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: D:\pkg\vcpkg\triplets\community\x86-windows-static-md.cmake
-- Using cached madler-zlib-v1.2.13.tar.gz.
-- Extracting source D:/pkg/vcpkg/downloads/madler-zlib-v1.2.13.tar.gz
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch 0002-skip-building-examples.patch
-- Applying patch 0003-build-static-or-shared-not-both.patch
-- Applying patch 0004-android-and-mingw-fixes.patch
-- Using source at D:/pkg/vcpkg/buildtrees/zlib/src/v1.2.13-f30d2a168d.clean
-- Configuring x86-windows-static-md
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: D:/pkg/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe -v
    Working Directory: D:/pkg/vcpkg/buildtrees/zlib/x86-windows-static-md-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\pkg\vcpkg\buildtrees\zlib\config-x86-windows-static-md-dbg-CMakeCache.txt.log
      D:\pkg\vcpkg\buildtrees\zlib\config-x86-windows-static-md-rel-CMakeCache.txt.log
      D:\pkg\vcpkg\buildtrees\zlib\config-x86-windows-static-md-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:248 (vcpkg_execute_required_process)
  ports/zlib/portfile.cmake:18 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)

error: building zlib:x86-windows-static-md failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+zlib
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[zlib]+Build+error
Include '[zlib] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: a32522820 2023-02-18 (2 days ago)

Please use the prefilled template from D:\pkg\vcpkg\installed\vcpkg\issue_body.md when reporting your issue.
PS D:\pkg\vcpkg> ./vcpkg install curl:x64-windows-static-md
Computing installation plan...
The following packages will be built and installed:
    curl[core,non-http,schannel,ssl,sspi]:x64-windows-static-md -> 7.87.0#1
  * zlib[core]:x64-windows-static-md -> 1.2.13
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows-static-md...
Restored 0 package(s) from C:\Users\arnold\AppData\Local\vcpkg\archives in 387.2 us. Use --debug to see more details.
Installing 1/2 zlib:x64-windows-static-md...
Building zlib[core]:x64-windows-static-md...
warning: -- Using community triplet x64-windows-static-md. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: D:\pkg\vcpkg\triplets\community\x64-windows-static-md.cmake
-- Using cached madler-zlib-v1.2.13.tar.gz.
-- Cleaning sources at D:/pkg/vcpkg/buildtrees/zlib/src/v1.2.13-f30d2a168d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/pkg/vcpkg/downloads/madler-zlib-v1.2.13.tar.gz
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch 0002-skip-building-examples.patch
-- Applying patch 0003-build-static-or-shared-not-both.patch
-- Applying patch 0004-android-and-mingw-fixes.patch
-- Using source at D:/pkg/vcpkg/buildtrees/zlib/src/v1.2.13-f30d2a168d.clean
-- Configuring x64-windows-static-md
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: D:/pkg/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe -v
    Working Directory: D:/pkg/vcpkg/buildtrees/zlib/x64-windows-static-md-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\pkg\vcpkg\buildtrees\zlib\config-x64-windows-static-md-dbg-CMakeCache.txt.log
      D:\pkg\vcpkg\buildtrees\zlib\config-x64-windows-static-md-rel-CMakeCache.txt.log
      D:\pkg\vcpkg\buildtrees\zlib\config-x64-windows-static-md-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:248 (vcpkg_execute_required_process)
  ports/zlib/portfile.cmake:18 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)

error: building zlib:x64-windows-static-md failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+zlib
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[zlib]+Build+error
Include '[zlib] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: a32522820 2023-02-18 (2 days ago)

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JonLiu1993** [comment]
@tester0077, Thanks for posting this issue, could you please provide this error?
`D:\pkg\vcpkg\buildtrees\zlib\config-x86-windows-static-md-out.log`

**Comment by dev-dakky** [comment]
Getting the same issue, nuked and reinstalled vcpkg, relinked, integrate install, etc.
Command line:
```C:\vcpkg>vcpkg install zlib[core]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    zlib[core]:x64-windows -> 1.2.13
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\dakky\AppData\Local\vcpkg\archives in 532.5 us. Use --debug to see more details.
Installing 1/1 zlib:x64-windows...
Building zlib[core]:x64-windows...
-- Using cached madler-zlib-v1.2.13.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/zlib/src/v1.2.13-f30d2a168d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/madler-zlib-v1.2.13.tar.gz
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch 0002-skip-building-examples.patch
-- Applying patch 0003-build-static-or-shared-not-both.patch
-- Applying patch 0004-android-and-mingw-fixes.patch
-- Using source at C:/vcpkg/buildtrees/zlib/src/v1.2.13-f30d2a168d.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/vcpkg/buildtrees/zlib/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\zlib\config-x64-windows-dbg-CMakeCache.txt.log
      C:\vcpkg\buildtrees\zlib\config-x64-windows-rel-CMakeCache.txt.log
      C:\vcpkg\buildtrees\zlib\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:248 (vcpkg_execute_required_process)
  ports/zlib/portfile.cmake:18 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)


error: building zlib:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+zlib
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[zlib]+Build+error
Include '[zlib] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: a32522820 2023-02-18 (3 days ago)```


[issue_body.md](https://github.com/microsoft/vcpkg/files/10788843/issue_body.md)
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/10788846/config-x86-windows-out.log)

**Comment by JonLiu1993** [comment]
Thanks for posting this issue. Please make sure you have the following installed.
````
Visual Studio English Language Pack.
Visual Studio Desktop development with C++.
Windows 10 SDK or Windows 11 SDK.
````

**Comment by dev-dakky** [comment]
@JonLiu1993 Thanks, I made sure to update all my VS related installations and checked that all relevant boxes were filled in, and restarted afterwards to be sure. Still the same result unfortunately. From what I can tell it looks like there's an issue with vcpkg's ninja command generation, because it seems to be creating what's effectively just "ninja -v", unless there's more to it that it won't even print with --debug-env added in 
I tried installing other libraries and have been having the same exact issue with all of them too, so it doesn't seem to be specific to any particular packages.
Adding extra logs from this run in case there's any extra info that could help.

Also what's up with that sfhacker dude thumbing down every post without giving any input, rude lmao.

[issue_body.md](https://github.com/microsoft/vcpkg/files/10799878/issue_body.md)
[config-x64-windows-dbg-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10799882/config-x64-windows-dbg-CMakeCache.txt.log)
[config-x64-windows-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10799886/config-x64-windows-rel-CMakeCache.txt.log)
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/10799889/config-x64-windows-out.log)
[config-x64-windows-err.log](https://github.com/microsoft/vcpkg/files/10799890/config-x64-windows-err.log)

**Comment by algaspar** [comment]
For what it's worth...  Had the same problem trying to install libxlsxwriter.  It got to the point that it wanted zlib and tried making it.  It erred out in cmake with the failure on ninja.exe -v.

**Comment by dev-dakky** [comment]
@JonLiu1993 what are the qualifications for repro being achieved? Seems like we have a few people hitting this issue.

**Comment by JonLiu1993** [comment]
@dev-dakky, Could you please provide me your VS installation details?
![image](https://user-images.githubusercontent.com/63675417/222389818-2f7ecc07-7b29-45ac-95b5-4de8292cebc6.png)

**Comment by JonLiu1993** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
This issue hasn’t been updated in a year; if it is still an issue, please reopen it.
