### ISSUE TITLE
[glib] build failure on docker while build snap package arm64

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#29757]
**Host Environment**

- OS: docker with build snap core22 (mean ubuntu22.04) **arm64**.
- Compiler: gcc 11.3.0

**To Reproduce**

`$VCPKG_ROOT/vcpkg install  --x-manifest-root=3rdParty/vcpkg_ports/configs/manager/linux --x-install-root=$VCPKG_ROOT/installed/ --overlay-ports=$VCPKG_PORTS/ports --overlay-triplets=$VCPKG_PORTS/triplets/ci --triplet=$TRIPLET --clean-after-build`

**Failure logs**
```
:: Building glib[core]:x64-linux...
:: -- [OVERLAY] Loading triplet configuration from: /root/parts/boinc/build/3rdParty/vcpkg_ports/triplets/ci/x64-linux.cmake
:: -- Downloading https://download.gnome.org/sources/glib/2.75/glib-2.75.3.tar.xz -> glib-2.75.3.tar.xz...
:: -- Extracting source /root/parts/boinc/build/3rdParty/linux/vcpkg/downloads/glib-2.75.3.tar.xz
:: -- Applying patch use-libiconv-on-windows.patch
:: -- Applying patch libintl.patch
:: -- Using source at /root/parts/boinc/build/3rdParty/linux/vcpkg/buildtrees/glib/src/glib-2-8ca74e7d19.clean
:: -- Getting CMake variables for x64-linux-rel
:: -- Configuring x64-linux-rel
:: -- Configuring x64-linux-rel done
:: -- Package x64-linux-rel
:: CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
::     Command failed: /root/.local/bin/ninja install -v
::     Working Directory: /root/parts/boinc/build/3rdParty/linux/vcpkg/buildtrees/glib/x64-linux-rel
::     Error code: 1
::     See logs for more information:
::       /root/parts/boinc/build/3rdParty/linux/vcpkg/buildtrees/glib/package-x64-linux-rel-out.log
::
:: Call Stack (most recent call first):
::   scripts/cmake/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
::   ports/glib/portfile.cmake:42 (vcpkg_install_meson)
::   scripts/ports.cmake:147 (include)
```
```
FAILED: gobject/gobject-query 
/usr/bin/cc  -o gobject/gobject-query gobject/gobject-query.p/gobject-query.c.o -L/root/parts/boinc/install/usr/lib -L/root/parts/boinc/install/usr/lib/aarch64-linux-gnu -L/root/parts/boinc/build/3rdParty/linux/vcpkg/installed/x64-linux/lib -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group glib/libglib-2.0.a glib/libcharset/libcharset.a glib/gnulib/libgnulib.a gobject/libgobject-2.0.a -lm /root/parts/boinc/build/3rdParty/linux/vcpkg/installed/x64-linux/lib/pkgconfig/../../lib/libpcre2-8.a -pthread /root/parts/boinc/build/3rdParty/linux/vcpkg/installed/x64-linux/lib/pkgconfig/../../lib/libffi.a -Wl,--end-group
/usr/bin/ld: gobject/libgobject-2.0.a(gclosure.c.o): in function `g_cclosure_marshal_generic':
gclosure.c:(.text+0x2514): undefined reference to `ffi_call'
/usr/bin/ld: gobject/libgobject-2.0.a(gclosure.c.o): in function `g_cclosure_marshal_generic_va':
gclosure.c:(.text+0x2a90): undefined reference to `ffi_call'
/usr/bin/ld: /root/parts/boinc/build/3rdParty/linux/vcpkg/installed/x64-linux/lib/pkgconfig/../../lib/libffi.a(prep_cif.c.o): in function `ffi_prep_cif_core':
prep_cif.c:(.text+0x248): undefined reference to `ffi_prep_cif_machdep'
/usr/bin/ld: /root/parts/boinc/build/3rdParty/linux/vcpkg/installed/x64-linux/lib/pkgconfig/../../lib/libffi.a(prep_cif.c.o): in function `ffi_prep_cif':
prep_cif.c:(.text+0x37c): undefined reference to `ffi_prep_cif_machdep'
/usr/bin/ld: /root/parts/boinc/build/3rdParty/linux/vcpkg/installed/x64-linux/lib/pkgconfig/../../lib/libffi.a(prep_cif.c.o): in function `ffi_prep_cif_var':
prep_cif.c:(.text+0x43c): undefined reference to `ffi_prep_cif_machdep'
/usr/bin/ld: /root/parts/boinc/build/3rdParty/linux/vcpkg/installed/x64-linux/lib/pkgconfig/../../lib/libffi.a(prep_cif.c.o): in function `ffi_prep_closure':
prep_cif.c:(.text+0x4d4): undefined reference to `ffi_prep_closure_loc'
```

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.
[parts.zip](https://github.com/microsoft/vcpkg/files/10787469/parts.zip)

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

It a custom triplet of arm64. (just different file name everything is the same). 
Also I notice it compile x64-linux. Is it ok? 

[snap-linux-arm64.cmake.txt](https://github.com/microsoft/vcpkg/files/10787491/snap-linux-arm64.cmake.txt)

**Comment by dg0yt** [comment]
Your setup destroys the required distinction between the x64 linux host and the arm64 linux target.
If you want an arm64 linux release triplet, you should also name the triplet file like that, and properly use the options for overlay triplets and target triplet name.

**Comment by talregev** [comment]
I already use triplets overlay.
How I should name the file?
I didn't know that triplets are sensitive to filename.

**Comment by dg0yt** [comment]
`arm64-linux-snap.cmake` is identicial with existing community triplet file `arm64-linux-release.cmake`. 

But wait. How do you set the target triplet? It is not part of the `./vcpkg install glib` command line.

~~~
/usr/bin/cc  ... -L/root/parts/boinc/install/usr/lib -L/root/parts/boinc/install/usr/lib/aarch64-linux-gnu -L/root/parts/boinc/build/3rdParty/linux/vcpkg/installed/x64-linux/lib ...
~~~

You are definitely mixing host and target lib dirs. I guess you set some environment variables for target purposes which now interfere with building some host dependencies.

**Comment by talregev** [comment]
I do it in manifest mode:
```
$VCPKG_ROOT/vcpkg install  --x-manifest-root=3rdParty/vcpkg_ports/configs/manager/linux --x-install-root=$VCPKG_ROOT/installed/ --overlay-ports=$VCPKG_PORTS/ports --overlay-triplets=$VCPKG_PORTS/triplets/ci --triplet=$TRIPLET --clean-after-build
```

**Comment by talregev** [comment]
> You are definitely mixing host and target lib dirs. I guess you set some environment variables for target purposes which now interfere with building some host dependencies.

I am not aware of such environment variable. Maybe the environment I compile vcpkg already set that. 
Can you tell what  environment variables I should check? I can print them for you.

**Comment by talregev** [comment]
I check now vcpkg help. there is an option with `--host-triplet` so I am now try to set it to the same triplet. 
```
--triplet=$TRIPLET
--host-triplet=$TRIPLET
```

**Comment by dg0yt** [comment]
> I do it in manifest mode:

... okay, this is not what you reported.

> I check now vcpkg help. there is an option with `--host-triplet` so I am now try to set it to the same triplet.
> 
> ```
> --triplet=$TRIPLET
> --host-triplet=$TRIPLET
> ```

Why?

**Comment by talregev** [comment]
> > I do it in manifest mode:
> 
> ... okay, this is not what you reported.
> 
> > I check now vcpkg help. there is an option with `--host-triplet` so I am now try to set it to the same triplet.
> > ```
> > --triplet=$TRIPLET
> > --host-triplet=$TRIPLET
> > ```
> 
> Why?

It solve the problem of the mixing.

**Comment by dg0yt** [comment]
> It solve the problem of the mixing.

But you want to do a cross-build. 
(Ignore the initial comment about mixing, they were based on confusion caused by the initial post.)

**Comment by talregev** [comment]
> > It solve the problem of the mixing.
> 
> But you want to do a cross-build. (Ignore the initial comment about mixing, they were based on confusion caused by the initial post.)

I don't want to do cross-build. I am compiling arm64 lib on arm64 machine. the docker is arm64 machine. 
I think you are right and there is a problem of mixing of the host that should investigate more. Now is workaround that will work for me.

**Comment by talregev** [comment]
maybe it also connected to `CMAKE_HOST_SYSTEM_PROCESSOR`
But I like the `--host-triplet` solution.

**Comment by talregev** [comment]
How vcpkg determent the host? Before it was ok.

**Comment by talregev** [comment]
I had a problem with mixing the host and the target triplet. I solve it by setting the correct host triplet with the flag. 
Thank you @dg0yt for pointing me to that direction!
