### ISSUE TITLE
[mpir] Build error

### ISSUE THREAD

**Issue by ElSayedMMostafa** [microsoft/vcpkg#29759]
**Host Environment**

- OS: Windows
- Compiler: revision

**To Reproduce**

`.\vcpkg install mpir mpir:x64-windows`

**Failure logs**

Computing installation plan...
The following packages will be built and installed:
    mpir[core]:x64-windows -> 2022-03-02#1
    mpir[core]:x86-windows -> 2022-03-02#1
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
Restored 0 package(s) from C:\Users\ict_3\AppData\Local\vcpkg\archives in 112.2 us. Use --debug to see more details.
Installing 1/2 mpir:x64-windows...
Building mpir[core]:x64-windows...
CMake Error at ports/mpir/portfile.cmake:2 (message):
  Can't build mpir if gmp is installed.  Please remove gmp, and try to
  install mpir again if you need it.
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)

error: building mpir:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.

**Additional context**

 vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
   vcpkg-scripts version: a32522820 2023-02-18 (3 days ago)

**Comment by FrankXie05** [comment]
@ElSayedMMostafa Please run command `./vcpkg remove gmp:x64-windows` and try again. :)
```
Can't build mpir if gmp is installed. Please remove gmp, and try to
install mpir again if you need it.
```

**Comment by ElSayedMMostafa** [comment]
Thanks a lot, it's solved.
