### ISSUE TITLE
Add more integration options

### ISSUE THREAD

**Issue by cmpute** [Microsoft/vcpkg#2975]
I think it would be convient if we have a command `vcpkg integrate current` to add paths to current shell (like vcvarsall.bat)
- `vcpkg integrate current --bin [--triplet <triplet>]`: Add `installed/<triplet>/bin` to `PATH` of current shell (#2768)
- `vcpkg integrate current --include [--triplet <triplet>]`: Add `installed/<triplet>/include` to `INCLUDE` of current shell
- `vcpkg integrate current --tool [--triplet <triplet>]`: Add `installed/<triplet>/tool` to `PATH` of current shell
- `vcpkg integrate current --python [--triplet <triplet>]`: Add `installed/<triplet>/python` to `PYTHONPATH` of current shell (#2974)
- ...

Moreover, we can invoke vcvarsall for users:
- `vcpkg integrate current --bin --dev`: Run vcvarsall.bat and add `installed/<triplet>/bin` to `PATH` of current shell.

This would be convenient to set up environment for other tools.

**Comment by ras0219-msft** [comment]
Thanks for the suggestion!

We do currently have the command `vcpkg env` which creates a shell inside the same environment we build packages in -- this will run vcvarsall, but it also clears out other environment variables in order to produce a "clean" state

**Comment by ras0219-msft** [comment]
Merged #3007. Thanks!
