### ISSUE TITLE
[colmap] Build error

### ISSUE THREAD

**Issue by MvWouden** [microsoft/vcpkg#29755]
**Host Environment**

- OS: Windows
- vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
- vcpkg-scripts version: a32522820 2023-02-18 (2 days ago)
- cmake version:  3.26.0-rc3

(not sure if relevant: "Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31942 for x64")

**To Reproduce**

```
git clone https://github.com/microsoft/vcpkg
cd vcpkg
.\bootstrap-vcpkg.bat
.\vcpkg install colmap[cuda,tests]:x64-windows
```

**Failure logs**

[install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/10786510/install-x64-windows-rel-out.log)

**Additional context**

Simply followed the installation instructions located [here](https://colmap.github.io/install.html#id3).

Seems similar/related to [this issue](https://github.com/microsoft/vcpkg/issues/29458) and [this issue](https://github.com/microsoft/vcpkg/issues/29369).

**Comment by JackBoosY** [comment]
```
C:\Projects\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\feature\utils.cc(81) : fatal error C1001: Internal compiler error.
(compiler file 'D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 224)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com 
Please choose the Technical Support command on the Visual C++ 
 Help menu, or open the Technical Support help file for more information
  cl!RaiseException()+0x69
  cl!RaiseException()+0x69
  cl!InvokeCompilerPassW()+0x87d1b
  cl!InvokeCompilerPassW()+0xf2a27
```
Please report this issue to Visual Studio feedback.

**Comment by MvWouden** [comment]
Update (21-02-2023): a fix was created to resolve a visual studio support ticket, and is currently pending release. See https://developercommunity.visualstudio.com/t/fatal-error-C1001:-Internal-compiler-err/10076899

**Comment by JackBoosY** [comment]
@JonLiu1993 can be closed now.

**Comment by MvWouden** [comment]
I have tested out the preview release of Visual Studio, and I can confirm that the issue is resolved.
The issue can indeed be closed.
