### ISSUE TITLE
[libass] build failure when trying to update the port

### ISSUE THREAD

**Issue by Masaiki** [microsoft/vcpkg#29752]
**Host Environment**

- OS: debian11
- Compiler: gcc10

**To Reproduce**

`git clone https://github.com/Masaiki/vcpkg.git --branch update-port-libass`
`./vcpkg install libass[asm]:x64-linux`

**Failure logs**

https://paste.ubuntu.com/p/vsDn4w4s8x/

**Additional context**

I am trying to update libass port and try to support more features. I encountered trouble compiling on linux platform, cmake generated ninja file added -pthread option to every compilation unit, even on assembly file, which caused compilation failure. I tried to find the reason but failed, suspecting that the problem may lie in cmake or vcpkg

**Comment by FrankXie05** [comment]
@Masaiki The port `libass` does not have the feature `asm`. Did you add it yourself? I didn't see it in your repo.
https://github.com/microsoft/vcpkg/blob/master/ports/libass/vcpkg.json
https://github.com/Masaiki/vcpkg/blob/master/ports/libass/vcpkg.json

**Comment by Masaiki** [comment]
> @Masaiki The port `libass` does not have the feature `asm`. Did you add it yourself? I didn't see it in your repo. 

Yes, in the `update-port-libass` branch

**Comment by FrankXie05** [comment]
@Masaiki You can submit a PR. :)

**Comment by Masaiki** [comment]
> @Masaiki You can submit a PR. :)

@FrankXie05 , Done in https://github.com/microsoft/vcpkg/pull/29767
