### ISSUE TITLE
qt(6)base is build twice when using a custom triplet

### ISSUE THREAD

**Issue by larshg** [microsoft/vcpkg#29769]
**Describe the bug**
PCL uses a custom triplet that should only build release versions of the libraries, however, currently qt(6)base is being build 1 times as debug and 2 times as release, since it builds both for x64-windows and x64-windows-rel.

How come its building for x64-windows?

**Environment**
- OS: Windows
- Compiler: VS2019

**To Reproduce**
1. ./vcpkg install qtbase:triplet_with_release_only
2. See qtbase be build twice
Repro code when

**Expected behavior**
Only build the release version once

**Failure logs**
<details>
   <summary>Build log </summary>

Installing 234/246 qtbase:x64-windows...
Building qtbase[brotli,concurrent,core,dbus,default-features,doubleconversion,freetype,gui,harfbuzz,icu,jpeg,network,opengl,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,thread,widgets,zstd]:x64-windows...
-- Downloading https://download.qt.io/archive/qt/6.4/6.4.2/submodules/qtbase-everywhere-src-6.4.2.tar.xz -> qtbase-everywhere-src-6.4.2.tar.xz...
-- Extracting source C:/vcpkg/downloads/qtbase-everywhere-src-6.4.2.tar.xz
-- Applying patch allow_outside_prefix.patch
-- Applying patch clang-cl_source_location.patch
-- Applying patch config_install.patch
-- Applying patch fix_cmake_build.patch
-- Applying patch harfbuzz.patch
-- Applying patch fix_egl.patch
-- Applying patch fix_egl_2.patch
-- Applying patch clang-cl_QGADGET_fix.diff
-- Applying patch installed_dir.patch
-- Applying patch GLIB2-static.patch
-- Applying patch env.patch
-- Applying patch dont_force_cmakecache_latest.patch
-- Using source at C:/vcpkg/buildtrees/qtbase/src/here-src-6-a23943cb65.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: C:/vcpkg/packages/qtbase_x64-windows/tools/Qt6/bin/qmake.debug.bat
-- Installing: C:/vcpkg/packages/qtbase_x64-windows/tools/Qt6/bin/qtpaths.debug.bat
-- Installing: C:/vcpkg/packages/qtbase_x64-windows/tools/Qt6/bin/windeployqt.debug.bat
-- Performing post-build validation
Stored binary cache: "C:\Users\ContainerAdministrator\AppData\Local\vcpkg\archives\cc\ccfbd2835f3cdb8939cf70b5b7499d211df12c317d59da342f92c3c25045dd26.zip"
Elapsed time to handle qtbase:x64-windows: 49.67 min
Installing 235/246 qtbase:x64-windows-rel...
Building qtbase[brotli,concurrent,core,dbus,default-features,doubleconversion,freetype,gui,harfbuzz,icu,jpeg,network,opengl,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,thread,widgets,zstd]:x64-windows-rel...
-- Downloading https://download.qt.io/archive/qt/6.4/6.4.2/submodules/qtbase-everywhere-src-6.4.2.tar.xz -> qtbase-everywhere-src-6.4.2.tar.xz...
-- Extracting source C:/vcpkg/downloads/qtbase-everywhere-src-6.4.2.tar.xz
-- Applying patch allow_outside_prefix.patch
-- Applying patch clang-cl_source_location.patch
-- Applying patch config_install.patch
-- Applying patch fix_cmake_build.patch
-- Applying patch harfbuzz.patch
-- Applying patch fix_egl.patch
-- Applying patch fix_egl_2.patch
-- Applying patch clang-cl_QGADGET_fix.diff
-- Applying patch installed_dir.patch
-- Applying patch GLIB2-static.patch
-- Applying patch env.patch
-- Applying patch dont_force_cmakecache_latest.patch
-- Using source at C:/vcpkg/buildtrees/qtbase/src/here-src-6-a23943cb65.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows-rel
-- Building x64-windows-rel-rel
-- Performing post-build validation
Stored binary cache: "C:\Users\ContainerAdministrator\AppData\Local\vcpkg\archives\ba\ba6648c47c6cff8f234950a7a455f52b8ff90cc89bd618eb5dac3df01bd3477a.zip"
Elapsed time to handle qtbase:x64-windows-rel: 29.45 min
</details>

**Additional context**
Latest build where we expand timeout for build:
https://dev.azure.com/PointCloudLibrary/pcl/_build/results?buildId=22831&view=logs&j=645d9b2d-e6a8-55a6-fe5b-40842942afe7&t=07185e79-ad4d-5c13-c1d1-201b01637442

**Comment by Neumann-A** [comment]
You also need to use/pass `--host-triplet <triplet_with_release_only>`

**Comment by Neumann-A** [comment]
or maybe in your case `-DVCPKG_HOST_TRIPLET=<triplet_with_release_only>` after looking at your ci setup.

**Comment by larshg** [comment]
We do so: https://github.com/PointCloudLibrary/pcl/blob/b551ee47b24e90cfb430ee4474f569e1411cd7bc/.dev/docker/windows/Dockerfile#L51

Also it works for most of the other pacakges.

There are several, that install both debug and release, but not installed twice.

**Comment by larshg** [comment]
Ahh, we do only triplet not host-triplet - does that make a difference?

**Comment by Neumann-A** [comment]
> Ahh, we do only triplet not host-triplet - does that make a difference?

Yes. The default host triplet is x64-windows. So if you have a host dependency like qtbase has it will build for the host triplet and the target triplet.

**Comment by larshg** [comment]
> > Ahh, we do only triplet not host-triplet - does that make a difference?
> 
> Yes. The default host triplet is x64-windows. So if you have a host dependency like qtbase has it will build for the host triplet and the target triplet.

So we would need to add both then?

**Comment by Neumann-A** [comment]
> So we would need to add both then?

Yes. That would have been always the case since vcpkg introduced host triplets ;) maybe you didn't notice it because qt5 is not setup for cross builds and always assumes a native build.

**Comment by larshg** [comment]
Testing it now at https://github.com/PointCloudLibrary/pcl/pull/5614/files - thanks for guidance @Neumann-A.

**Comment by Neumann-A** [comment]
@larshg close?

**Comment by larshg** [comment]
Yeah, that did it. Thanks.
