### ISSUE TITLE
release project using pkgconfig link with debug library

### ISSUE THREAD

**Issue by WiestDaessle** [microsoft/vcpkg#29762]
**Describe the bug**

I created a project that is using libjxl, 
The configuration in release mode is linking against the debug version of the libjxl library:

**Environment**
- OS: Windows
- Compiler: Visual Studio 2019

**To Reproduce**

find_package(PkgConfig)
pkg_check_modules(Jxl REQUIRED IMPORTED_TARGET libjxl)
pkg_check_modules(JxlThreads REQUIRED IMPORTED_TARGET libjxl_threads)

add_executable(CpTranscode mainCpTranscode.cpp)
target_link_libraries(CpTranscode PkgConfig::Jxl PkgConfig::JxlThreads)

from CMakeCache:

Jxl_LDFLAGS:INTERNAL=-LC:/Work/GitHub/buildRelease/vcpkg_installed/x64-windows/debug/lib/pkgconfig/../../lib;-ljxl

Configure step use the generator "Ninja Multi-Config":
cmake ..\App -DCMAKE_TOOLCHAIN_FILE=D:\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -G"Ninja Multi-Config"

build step:
cmake  --build . --config Release  --clean-first

**Expected behavior**

We are expected to link against release version not debug

**Comment by Neumann-A** [comment]
> Configure step use the generator "Ninja Multi-Config":

multi config with pkg-config won't work due to limitations of FindPkgConfig and vcpkg not currently re-implementing the behavior for multi config generators.  `Add -DCMAKE_BUILD_TYPE=Release` to the first configure call to always link release libs with pkg-config.

**Comment by MonicaLiu0311** [comment]
@WiestDaessle 
Does the above method work?

**Comment by dg0yt** [comment]
You could probably work around CMake's limitation by doing separate checks for debug and release config, merging the result in a single interface target. (Should vpckg offer this in another CMake module?)

**Comment by Neumann-A** [comment]
> You could probably work around CMake's limitation by doing separate checks for debug and release config, merging the result in a single interface target. (Should vpckg offer this in another CMake module?)

vcpkg could simply override `FindPkgConfig.cmake` and provide the correct information but  re-implementing `FindPkgConfig.cmake` is not an easy and fast task. Probably requires a lot of tries getting it 100% correct.

**Comment by dg0yt** [comment]
There is a reason why I suggested another module... The imported targets could work with little effort.

**Comment by MonicaLiu0311** [comment]
@WiestDaessle 
Again, please try the above method.

**Comment by MonicaLiu0311** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by dsvensson** [comment]
@MonicaLiu0311 This still seems to be an issue, pkg_check_modules in a multi-config build, even when passing configuration: Release via build-preset causes debug libraries to be found.

**Comment by lsolticDXO** [comment]
I ran into the same issue and ended up doing something like this:

```
find_package(PkgConfig REQUIRED) 
pkg_check_modules(
  JXL REQUIRED
  libjxl libjxl_threads
)
# If we add the "IMPORTED_TARGET GLOBAL" options to above pkg_check_modules call, it creates an incorrect imported target
# (uses debug libs in release) so we make our own target based on the provided variables
add_library(JXL INTERFACE)
target_include_directories(JXL INTERFACE ${JXL_INCLUDE_DIRS})
target_compile_definitions(JXL INTERFACE ${JXL_COMPILE_DEFINITIONS})
target_compile_options(JXL INTERFACE ${JXL_CFLAGS_OTHER})
target_link_options(JXL INTERFACE ${JXL_LDFLAGS_OTHER})
foreach(lib ${JXL_LIBRARIES})
  set(jxl_system_libs m c++)
  if (lib IN_LIST jxl_system_libs)
    target_link_libraries(JXL INTERFACE ${lib})
  else()
    if (WIN32)
      set(DEBUG_LIB_PATH "${VCPKG_ROOT}/debug/lib/${lib}.lib")
      set(RELEASE_LIB_PATH "${VCPKG_ROOT}/lib/${lib}.lib")
    else()
      set(DEBUG_LIB_PATH "${VCPKG_ROOT}/debug/lib/lib${lib}.a")
      set(RELEASE_LIB_PATH "${VCPKG_ROOT}/lib/lib${lib}.a")
    endif()
    target_link_libraries(JXL INTERFACE debug "${DEBUG_LIB_PATH}" optimized "${RELEASE_LIB_PATH}")
  endif()
endforeach()
add_library(PkgConfig::JXL ALIAS JXL) # Just to simulate what pkg_check_modules() would have provided
```

**Comment by smzahraee** [comment]
I have the same problem but if I add the following to my project it will be corrected
`link_directories(/opt/vcpkg/installed/x64-linux/lib /opt/vcpkg/installed/x64-linux/debug/lib)`

it seems that for `find_package(PkgConfig REQUIRED)` the cmake is unable to find the correct library path

**Comment by dg0yt** [comment]
@smzahraee The original problem was with the Visual Studio multi-config generator. `pkg_check_modules` doesn't support multi-config.
But your problem is on Linux, and probably with a single-config generator. In this case, first check that you set `CMAKE_BUILD_TYPE` before the `project` command. (Command line is early enough.)

**Comment by dg0yt** [comment]
@smzahraee In addition, CMake (`GNUInstallDirs`) has special handling for `/opt`, and this breaks some ports.
