### ISSUE TITLE
Issue with Registries in Manifest mode

### ISSUE THREAD

**Issue by diehard2** [microsoft/vcpkg#29771]
Sorry to cross post, I put this into General, but it appears that forum doesn't get much traction and I would like to solve this

I'm trying to create a registry for some projects local to my company as shown here - https://devblogs.microsoft.com/cppblog/registries-bring-your-own-libraries-to-vcpkg/

I'm more or less pattern matching and while I can get everything to build, cmake thinks the library is in the wrong place when I 

`find_package(StatsD CONFIG REQUIRED)`

in my main cmake file. All other libraries built by vcpkg directly are working as expected.

My portfile.cmake looks like 

``` 
find_program(GIT git)

set(GIT_URL "git@stuff.git")
set(GIT_REV "f9f136a9bb53616a04a4f299f16a6b2aa8c1f89f")
set(SOURCE_PATH ${CURRENT_BUILDTREES_DIR}/statsd-cpp-client)
message(STATUS "curr buildtree ${CURRENT_BUILDTREES_DIR}")

if(NOT EXISTS "${SOURCE_PATH}/.git")
    message(STATUS "Cloning")
    vcpkg_execute_required_process(
        COMMAND ${GIT} clone --sparse ${GIT_URL} 
        WORKING_DIRECTORY ${CURRENT_BUILDTREES_DIR}
        LOGNAME clone
    )


endif()

vcpkg_execute_required_process(
                               COMMAND ${GIT} reset --hard ${GIT_REV}
                               WORKING_DIRECTORY ${SOURCE_PATH}
                               LOGNAME reset
                               )

message(STATUS "Cloning done")

file(COPY "${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt" DESTINATION "${SOURCE_PATH}")

vcpkg_cmake_configure(
    SOURCE_PATH ${SOURCE_PATH}
    OPTIONS
        ${FEATURE_OPTIONS}
)

vcpkg_cmake_install()
vcpkg_copy_pdbs()

vcpkg_cmake_config_fixup()
vcpkg_fixup_pkgconfig()

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
```

and the cmake file its calling is 

``` 
cmake_minimum_required(VERSION 3.0)
include(GNUInstallDirs)

project(statsd-cpp-client)

find_package(Boost)
INCLUDE_DIRECTORIES( ${Boost_INCLUDE_DIR} )


add_library(statsd-cpp-client STATIC statsd_client.cpp)

set_target_properties(statsd-cpp-client PROPERTIES
    DEBUG_POSTFIX d
    VERSION 1.0.0
    SOVERSION 1.0)

install(TARGETS statsd-cpp-client
    EXPORT StatsDConfig
    RUNTIME DESTINATION bin
    ARCHIVE DESTINATION lib
    LIBRARY DESTINATION lib)

export(TARGETS statsd-cpp-client
       NAMESPACE StatsD::
       FILE "${CMAKE_CURRENT_BINARY_DIR}/statsdConfig.cmake"
)

install(FILES statsd_client.h DESTINATION include/statsd)

install(EXPORT StatsDConfig
        DESTINATION "${CMAKE_INSTALL_DATADIR}/statsd/cmake"
    NAMESPACE StatsD::
) 
```

I am using a custom triplet, but again, nothing fancy there

The error I'm getting when I try find_package is

/home/dev/myprogram/environment/vcpkg_installed/x64-linux-steve/**share**/debug/lib/libstatsd-cpp-clientd.a

If the word "share" wasn't there, this would all work as expected. I'm sure I'm doing something wrong, but can't figure it out for the life of me. I was under the impression that vcpkg_cmake_config_fixup() would correct the cmake paths in this case. Thanks for any help.

**Comment by dg0yt** [comment]
This is unrelated to manifest mode or registries.
You initially put the CMake config into `share/statsd/cmake`. `vcpkg_cmake_config_fixup()` won't handle this correctly without extra options. Just put the CMake config into `share/statsd`. Then `vcpkg_cmake_config_fixup()` should be happy if your port is named `statsd`. (Add `PACKAGE_NAME statsd` arguments if you chose a different port name.)

**Comment by jimwang118** [comment]
Hello, have you solved this problem according to dg0yt's solution?

**Comment by diehard2** [comment]
sorry for the late response. that was it, thanks @dg0yt.
