### ISSUE TITLE
llvm - takes forever to build

### ISSUE THREAD

**Issue by amansinghsneha** [microsoft/vcpkg#29778]
****

**Is your feature request related to a problem? Please describe.**
llvm library took 3 days to build for me.  I verified it with another colleague who ran the install for an hour and then ended up canceling the build job. Clang is a prereq for one of the new ports I would be requesting, but this seems like a blocking issue to me.

**Proposed solution**
I want a fix to be introduced, that can significantly speed up the build time of llvm

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered if applicable.

**Additional context**

**Comment by JackBoosY** [comment]
Yeah, llvm always spend our so much time.

**Comment by Neumann-A** [comment]
LLVM takes around 35~40 min on an AMD Ryzen 9 7900X with a M2 NVME drive if you also disabled defender correctly.

**Comment by JonLiu1993** [comment]
It seems that this is not a vcpkg problem, temporarily close this issue, if you have other questions, I can reopen it.
