### ISSUE TITLE
[draco] Patch for regex failure in cmake

### ISSUE THREAD

**Issue by MunWolf** [microsoft/vcpkg#29789]
****

**Is your feature request related to a problem? Please describe.**
When I was installing Ogre it failed due to draco erroring out during its cmake installation.
The underlying error was this line in cmake/draco_install.cmake
`list(TRANSFORM draco_api_includes REPLACE "${draco_src_root}/" "")`
where draco_src_root included a . in its version name `1.5.3-22404bd0ba.clean`
it failed because that parameter is parsed as a regex string, as shown here under TRANSFORM REPLACE
https://cmake.org/cmake/help/latest/command/list.html#transform

**Proposed solution**
```cmake
diff --git a/cmake/draco_install.cmake b/cmake/draco_install.cmake
index e15a054..e13961b 100644
--- a/cmake/draco_install.cmake
+++ b/cmake/draco_install.cmake
@@ -38,7 +38,8 @@ macro(draco_setup_install_target)
 
   # Strip $draco_src_root from the file paths: we need to install relative to
   # $include_directory.
-  list(TRANSFORM draco_api_includes REPLACE "${draco_src_root}/" "")
+  string(REGEX REPLACE "([][+.*()^])" "\\\\\\1" draco_src_root_regexed "${draco_src_root}/")
+  list(TRANSFORM draco_api_includes REPLACE "${draco_src_root_regexed}" "")
 
   foreach(draco_api_include ${draco_api_includes})
     get_filename_component(file_directory ${draco_api_include} DIRECTORY)
```
This is the patch I wrote to have it work on my end and the solution would be to include it.

**Describe alternatives you've considered**
An alternative would be to get draco to fix their cmake and make sure draco_src_root is a valid regex string.

**Comment by dg0yt** [comment]
> The underlying error was this line in cmake/draco_install.cmake
> `list(TRANSFORM draco_api_includes REPLACE "${draco_src_root}/" "")`
> where draco_src_root included a . in its version name `1.5.3-22404bd0ba.clean`
> it failed because that parameter is parsed as a regex string

I don't think the `.` is the problem. It will match a dot. Usually it is a `+` as in `D:/C++/vcpkg`. Then the workaround is to chose a different dir for vcpkg.

**Comment by FrankXie05** [comment]
This issue hasn’t been updated for a long time; if it is still an issue, please reopen this issue.
