### ISSUE TITLE
[at-spi2-core] build failure on cross compiling arm64-linux on x64-linux machine

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#29786]
**Host Environment**

- OS: wsl2 ubuntu 22.04
- Compiler: 11.3.0

**To Reproduce**

```
sudo apt install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

# This step is needed more pre step that I am not showing here. 
# This is for let you know that I have libdbus and other libs in arm64 that needed for at-spi2-core
sudo apt install -y libdbus-1-dev:arm64 libxi-dev:arm64 libxtst-dev:arm64

./vcpkg install wxwidgets --triplet=arm64-linux --host-triplet=x64-linux
```
**Failure logs**

Installing 20/59 at-spi2-core:arm64-linux...
Building at-spi2-core[core]:arm64-linux...
warning: -- Using community triplet arm64-linux. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /home/tal/vcpkg/triplets/community/arm64-linux.cmake
-- at-spi2-core currently requires the following libraries from the system package manager:
    libdbus-1-dev
    libxi-dev
    libxtst-dev

These can be installed on Ubuntu systems via apt-get install libdbus-1-dev libxi-dev libxtst-dev
-- Downloading https://gitlab.gnome.org/GNOME/at-spi2-core/-/archive/AT_SPI2_CORE_2_44_1/at-spi2-core-AT_SPI2_CORE_2_44_1.tar.gz -> GNOME-at-spi2-core-AT_SPI2_CORE_2_44_1.tar.gz...
-- Extracting source /home/tal/vcpkg/downloads/GNOME-at-spi2-core-AT_SPI2_CORE_2_44_1.tar.gz
-- Using source at /home/tal/vcpkg/buildtrees/at-spi2-core/src/ORE_2_44_1-fa40e2a5ad.clean
CMake Warning at scripts/cmake/vcpkg_configure_meson.cmake:306 (message):
  Options ADDITIONAL_(NATIVE|CROSS)_BINARIES have been deprecated.  Only use
  ADDITIONAL_BINARIES!
Call Stack (most recent call first):
  ports/at-spi2-core/portfile.cmake:13 (vcpkg_configure_meson)
  scripts/ports.cmake:147 (include)

-- Found external ninja('1.11.1.git.kitware.jobserver-1').
-- Getting CMake variables for arm64-linux-dbg
-- Getting CMake variables for arm64-linux-rel
-- Configuring arm64-linux-dbg
-- Configuring arm64-linux-dbg done
-- Configuring arm64-linux-rel
-- Configuring arm64-linux-rel done
-- Package arm64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /home/tal/.local/bin/ninja install -v
    Working Directory: /home/tal/vcpkg/buildtrees/at-spi2-core/arm64-linux-dbg
    Error code: 1
    See logs for more information:
      /home/tal/vcpkg/buildtrees/at-spi2-core/package-arm64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
  ports/at-spi2-core/portfile.cmake:25 (vcpkg_install_meson)
  scripts/ports.cmake:147 (include)

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

[at-spi2-core.zip](https://github.com/microsoft/vcpkg/files/10801885/at-spi2-core.zip)

**Additional context**

When compiling x64-linux wxwidgets  on x64 machine is working.
When compiling arm64-linux wxwidgets on arm64 machine is working. 
The problem is when doing cross compiling.

when build wxwidgets some of the ports are arm64-linux, and some are x64-linux
I am not sure what is responsible for that split.
```
The following packages will be built and installed:
  * at-spi2-atk[core]:arm64-linux -> 2.38.0
  * at-spi2-core[core]:arm64-linux -> 2.44.1#1
  * atk[core]:arm64-linux -> 2.38.0#5
  * brotli[core]:arm64-linux -> 1.0.9#5
  * bzip2[core,tool]:arm64-linux -> 1.0.8#3
  * bzip2[core,tool]:x64-linux -> 1.0.8#3
  * cairo[core,fontconfig,freetype,gobject,x11]:arm64-linux -> 1.17.6#5
  * curl[core,non-http,openssl,ssl]:arm64-linux -> 7.88.1
  * dirent[core]:arm64-linux -> 1.23.2#1
  * dirent[core]:x64-linux -> 1.23.2#1
  * egl-registry[core]:arm64-linux -> 2022-09-20
  * expat[core]:arm64-linux -> 2.5.0#3
  * fontconfig[core]:arm64-linux -> 2.14.1#1
  * freetype[brotli,bzip2,core,png,zlib]:arm64-linux -> 2.12.1#3
  * fribidi[core]:arm64-linux -> 1.0.12
  * fribidi[core]:x64-linux -> 1.0.12
  * gdk-pixbuf[core]:arm64-linux -> 2.42.9#5
  * gdk-pixbuf[core]:x64-linux -> 2.42.9#5
  * getopt[core]:arm64-linux -> 0#2
  * gettext[core,tools]:x64-linux -> 0.21.1
  * gettext[core]:arm64-linux -> 0.21.1
  * glib[core]:arm64-linux -> 2.75.3
  * glib[core]:x64-linux -> 2.75.3
  * gperf[core]:x64-linux -> 3.1#4
  * gtk3[core]:arm64-linux -> 3.24.34#2
  * harfbuzz[core]:arm64-linux -> 6.0.0
  * libepoxy[core]:arm64-linux -> 1.5.10#1
  * libffi[core]:arm64-linux -> 3.4.4
  * libffi[core]:x64-linux -> 3.4.4
  * libiconv[core]:arm64-linux -> 1.17
  * libiconv[core]:x64-linux -> 1.17
  * libjpeg-turbo[core]:x64-linux -> 2.1.5
  * libjpeg-turbo[core]:arm64-linux -> 2.1.5
  * liblzma[core]:x64-linux -> 5.4.1#1
  * liblzma[core]:arm64-linux -> 5.4.1#1
  * libpng[core]:arm64-linux -> 1.6.39
  * libpng[core]:x64-linux -> 1.6.39
  * libuuid[core]:arm64-linux -> 1.0.3#11
  * libxml2[core]:arm64-linux -> 2.10.3
  * lzo[core]:arm64-linux -> 2.10#7
  * nanosvg[core]:arm64-linux -> 2022-04-29
  * opengl[core]:arm64-linux -> 2022-12-04#1
  * opengl-registry[core]:arm64-linux -> 2022-09-29
  * openssl[core]:arm64-linux -> 3.0.8
  * pango[core]:arm64-linux -> 1.50.12#2
  * pcre2[core]:x64-linux -> 10.40#1
  * pcre2[core]:arm64-linux -> 10.40#1
  * pixman[core]:arm64-linux -> 0.42.2#2
  * pthread[core]:arm64-linux -> 3.0.0#1
  * pthreads[core]:arm64-linux -> 3.0.0#13
  * sdl2[base,core,ibus,wayland,x11]:arm64-linux -> 2.26.3#1
  * tiff[core,jpeg,lzma,zip]:x64-linux -> 4.5.0#2
  * tiff[core,jpeg,lzma,zip]:arm64-linux -> 4.5.0#2
  * vcpkg-cmake[core]:x64-linux -> 2022-12-22
  * vcpkg-cmake-config[core]:x64-linux -> 2022-02-06#1
  * vcpkg-tool-meson[core]:x64-linux -> 0.63
    wxwidgets[core,debug-support,sound]:arm64-linux -> 3.2.2.1
  * zlib[core]:arm64-linux -> 1.2.13
  * zlib[core]:x64-linux -> 1.2.13
```

@dg0yt Now I am doing cross compiling ;)

**Comment by talregev** [comment]
@dg0yt @mkhon
I understand the problem, but I don't know how to solve it.
When I do cross compiling: compile arm64-linux on x64-linux machine,
It looking for dbus lib of x64 in the config, then try to compile on arm64. It should look for arm64 lib.
How we can fix it?

**Comment by talregev** [comment]
Here is the logs when I have aarch64 libdbus without x64 libdbus:
`/usr/lib/aarch64-linux-gnu/libdbus-1.so`

It fail on the configure:
```
Installing 20/59 at-spi2-core:arm64-linux-release...
Building at-spi2-core[core]:arm64-linux-release...
warning: -- Using community triplet arm64-linux-release. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /home/runner/work/boinc/boinc/vcpkg/triplets/community/arm64-linux-release.cmake
-- at-spi2-core currently requires the following libraries from the system package manager:
    libdbus-1-dev
    libxi-dev
    libxtst-dev

These can be installed on Ubuntu systems via apt-get install libdbus-1-dev libxi-dev libxtst-dev
-- Downloading https://gitlab.gnome.org/GNOME/at-spi2-core/-/archive/AT_SPI2_CORE_2_44_1/at-spi2-core-AT_SPI2_CORE_2_44_1.tar.gz -> GNOME-at-spi2-core-AT_SPI2_CORE_2_44_1.tar.gz...
-- Extracting source /home/runner/work/boinc/boinc/vcpkg/downloads/GNOME-at-spi2-core-AT_SPI2_CORE_2_44_1.tar.gz
-- Using source at /home/runner/work/boinc/boinc/vcpkg/buildtrees/at-spi2-core/src/ORE_2_44_1-fa40e2a5ad.clean
CMake Warning at scripts/cmake/vcpkg_configure_meson.cmake:306 (message):
  Options ADDITIONAL_(NATIVE|CROSS)_BINARIES have been deprecated.  Only use
  ADDITIONAL_BINARIES!
Call Stack (most recent call first):
  ports/at-spi2-core/portfile.cmake:13 (vcpkg_configure_meson)
  scripts/ports.cmake:147 (include)


-- Getting CMake variables for arm64-linux-release-rel
-- Configuring arm64-linux-release-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/python3 /home/runner/work/boinc/boinc/vcpkg/installed/x64-linux-release/tools/meson/meson.py -Dintrospection=no --buildtype plain --backend ninja --wrap-mode nodownload --native /home/runner/work/boinc/boinc/vcpkg/scripts/buildsystems/meson/none.txt --libdir lib --cross /home/runner/work/boinc/boinc/vcpkg/buildtrees/at-spi2-core/meson-arm64-linux-release-rel.log -Ddebug=false --prefix /home/runner/work/boinc/boinc/vcpkg/packages/at-spi2-core_arm64-linux-release -Dcmake_prefix_path=['/home/runner/work/boinc/boinc/vcpkg/installed/arm64-linux-release','/home/runner/work/boinc/boinc/vcpkg/installed/arm64-linux-release/debug'] /home/runner/work/boinc/boinc/vcpkg/buildtrees/at-spi2-core/src/ORE_2_44_1-fa40e2a5ad.clean
    Working Directory: /home/runner/work/boinc/boinc/vcpkg/buildtrees/at-spi2-core/arm64-linux-release-rel
    Error code: 1
    See logs for more information:
      /home/runner/work/boinc/boinc/vcpkg/buildtrees/at-spi2-core/config-arm64-linux-release-rel-meson-log.txt.log
      /home/runner/work/boinc/boinc/vcpkg/buildtrees/at-spi2-core/config-arm64-linux-release-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:433 (vcpkg_execute_required_process)
  ports/at-spi2-core/portfile.cmake:13 (vcpkg_configure_meson)
  scripts/ports.cmake:147 (include)
```
[logs.zip](https://github.com/microsoft/vcpkg/files/10811057/logs.zip)

**Comment by dg0yt** [comment]
The port depends on system packages for the target system (aarch64-linux-gnu aka arm64-linux):
libdbus-1-dev, libxi-dev, libxtst-dev

Note that these are development packages. `/usr/lib/aarch64-linux-gnu/libdbus-1.so` is just the runtime.

**Comment by talregev** [comment]
> The port depends on system packages for the target system (aarch64-linux-gnu aka arm64-linux): libdbus-1-dev, libxi-dev, libxtst-dev
> 
> Note that these are development packages. `/usr/lib/aarch64-linux-gnu/libdbus-1.so` is just the runtime.

I installed the dev package and show the run time lib. 
I also have 
`/usr/lib/aarch64-linux-gnu/libdbus-1.a`
I will edit the comment

**Comment by talregev** [comment]
Even if install dbus from vcpkg, it still looking for system x64 dbus.

**Comment by talregev** [comment]
I solve the problem of dbus by installing dbus from vcpkg.
But I still I have a problem with libxtst then I guess with libxi.
First I install arm64 dependencies:
`sudo apt install -y libsystemd-dev:arm64 libxi-dev:arm64 libxtst-dev:arm64`
Then install vcpkg dependencies:
vcpkg/vcpkg install dbus libxtst libxi --triplet=arm64-linux-release --host-triplet=x64-linux-release
It not really install libxtst and libxi, it tell you to install it from the system as I did.
Then install wxwidgets:
vcpkg/vcpkg install wxwidgets --triplet=arm64-linux-release --host-triplet=x64-linux-release

And now it not find libxtst:

```
Installing 11/44 at-spi2-core:arm64-linux-release...
Building at-spi2-core[core]:arm64-linux-release...
warning: -- Using community triplet arm64-linux-release. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /home/runner/work/boinc/boinc/vcpkg/triplets/community/arm64-linux-release.cmake
-- at-spi2-core currently requires the following libraries from the system package manager:
    libdbus-1-dev
    libxi-dev
    libxtst-dev

These can be installed on Ubuntu systems via apt-get install libdbus-1-dev libxi-dev libxtst-dev
-- Downloading https://gitlab.gnome.org/GNOME/at-spi2-core/-/archive/AT_SPI2_CORE_2_44_1/at-spi2-core-AT_SPI2_CORE_2_44_1.tar.gz -> GNOME-at-spi2-core-AT_SPI2_CORE_2_44_1.tar.gz...
-- Extracting source /home/runner/work/boinc/boinc/vcpkg/downloads/GNOME-at-spi2-core-AT_SPI2_CORE_2_44_1.tar.gz
-- Using source at /home/runner/work/boinc/boinc/vcpkg/buildtrees/at-spi2-core/src/ORE_2_44_1-fa40e2a5ad.clean
CMake Warning at scripts/cmake/vcpkg_configure_meson.cmake:306 (message):
  Options ADDITIONAL_(NATIVE|CROSS)_BINARIES have been deprecated.  Only use
  ADDITIONAL_BINARIES!
Call Stack (most recent call first):
  ports/at-spi2-core/portfile.cmake:13 (vcpkg_configure_meson)
  scripts/ports.cmake:147 (include)


-- Getting CMake variables for arm64-linux-release-rel
-- Configuring arm64-linux-release-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/python3 /home/runner/work/boinc/boinc/vcpkg/installed/x64-linux-release/tools/meson/meson.py -Dintrospection=no --buildtype plain --backend ninja --wrap-mode nodownload --native /home/runner/work/boinc/boinc/vcpkg/scripts/buildsystems/meson/none.txt --libdir lib --cross /home/runner/work/boinc/boinc/vcpkg/buildtrees/at-spi2-core/meson-arm64-linux-release-rel.log -Ddebug=false --prefix /home/runner/work/boinc/boinc/vcpkg/packages/at-spi2-core_arm64-linux-release -Dcmake_prefix_path=['/home/runner/work/boinc/boinc/vcpkg/installed/arm64-linux-release','/home/runner/work/boinc/boinc/vcpkg/installed/arm64-linux-release/debug'] /home/runner/work/boinc/boinc/vcpkg/buildtrees/at-spi2-core/src/ORE_2_44_1-fa40e2a5ad.clean
    Working Directory: /home/runner/work/boinc/boinc/vcpkg/buildtrees/at-spi2-core/arm64-linux-release-rel
    Error code: 1
    See logs for more information:
      /home/runner/work/boinc/boinc/vcpkg/buildtrees/at-spi2-core/config-arm64-linux-release-rel-meson-log.txt.log
      /home/runner/work/boinc/boinc/vcpkg/buildtrees/at-spi2-core/config-arm64-linux-release-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:433 (vcpkg_execute_required_process)
  ports/at-spi2-core/portfile.cmake:13 (vcpkg_configure_meson)
  scripts/ports.cmake:147 (include)
```
[vcpkg.zip](https://github.com/microsoft/vcpkg/files/10811852/vcpkg.zip)

Any idea how to solve it?
Maybe redirect the mock libxi libxtst to redirect to correct system lib?
Maybe other creative idea?

**Comment by talregev** [comment]
Maybe this warning is related? 
```
CMake Warning at scripts/cmake/vcpkg_configure_meson.cmake:306 (message):
  Options ADDITIONAL_(NATIVE|CROSS)_BINARIES have been deprecated.  Only use
  ADDITIONAL_BINARIES!
```

**Comment by talregev** [comment]
When I compile libxi and libxtst I set in triplet:
```cmake
set(X_VCPKG_FORCE_VCPKG_X_LIBRARIES ON)
```
Then it fail on libx11 port. 
I think it not good approach to go this direction. I think it better to solve why at-spi2-core port don't recognize arm64 lib on cross build. Help will be appreciate.

**Comment by talregev** [comment]
I reconfigure the pkg-config search path that it will find the dbus and other dependencies.
Now I solve this, I move to the next problem.
@dg0yt Thank you for suggestions. I hope to see you in the next issue ;)
