### ISSUE TITLE
[liblzma] Build error

### ISSUE THREAD

**Issue by Xueqc** [microsoft/vcpkg#29783]
**Host Environment**

- OS: Windows 10
- Compiler: VC2019

**To Reproduce**

PS C:\src\vcpkg> ./vcpkg.exe install boost:x64-windows

**Failure logs**

Installing 1/44 liblzma:x64-windows...
Building liblzma[core]:x64-windows...
-- Using cached xz-5.4.1.tar.xz.
-- Extracting source C:/src/vcpkg/downloads/xz-5.4.1.tar.xz
-- Applying patch fix_config_include.patch
CMake Error at scripts/cmake/z_vcpkg_apply_patches.cmake:34 (message):
  Applying patch failed: Checking patch CMakeLists.txt...

  error: while searching for:

      if(BUILD_SHARED_LIBS)
          # Add the Windows resource file for liblzma.dll.
          target_sources(liblzma PRIVATE src/liblzma/liblzma_w32res.rc)

          set_target_properties(liblzma PROPERTIES
              LINK_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/src/common/common_w32res.rc"

  error: patch failed: CMakeLists.txt:413

  error: CMakeLists.txt: patch does not apply

Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive.cmake:153 (z_vcpkg_apply_patches)
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:8 (vcpkg_extract_source_archive)
  scripts/cmake/vcpkg_from_sourceforge.cmake:97 (vcpkg_extract_source_archive_ex)
  ports/liblzma/portfile.cmake:2 (vcpkg_from_sourceforge)
  scripts/ports.cmake:147 (include)

error: building liblzma:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+liblzma
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[liblzma]+Build+error
Include '[liblzma] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 703a8113f 2023-02-21 (13 hours ago)

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Adela0814** [comment]
@Xueqc  I'm not able to repro this issue, please remove your `liblzma` and try again with `.\vcpkg.exe install liblzma:x64-windows --binarysource=clear`.

**Comment by Adela0814** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
