### ISSUE TITLE
How to correctly use "find_library" in CMake when debug and release lib have the same name?

### ISSUE THREAD

**Issue by Ghabry** [Microsoft/vcpkg#2979]
I have the problem that the wrong library (debug library) is picked when I create a project file for Visual Studio with CMake. Because the wrong library is used for linking the release version I get build warnings that LIBCMT and LIBCMTD are conflicting.

For libraries that have a debug suffix ("d") this is trivial because I can simply detect them by name but how do I have to invoke find_library when both debug and release lib have the same name? For example expat.lib has this problem.

Is there a solution for this or is multi-target configuration currently not fully supported by vcpkg and I have to use "-DCMAKE_BUILD_TYPE" beforehand to pick one target?

**Comment by ras0219-msft** [comment]
Unfortunately, for libraries that use the same name in release and debug and don't provide `-config.cmake` files, there isn't a better option that I'm aware of (than just specifying the `CMAKE_BUILD_TYPE` and using separate solution files).

**Comment by Ghabry** [comment]
Okay. Thanks for the answer. As this appears to be a CMake limitation I will use the -DCMAKE_BUILD_TYPE workaround and close the issue.

**Comment by Mixaill** [comment]
You can you something like

```
if(NOT FOO_LIBRARY)
    FIND_LIBRARY(FOO_LIBRARY_RELEASE
        NAMES
            libfoo
        HINTS
            ${CMAKE_FIND_ROOT_PATH}
        PATHS
            ${CMAKE_FIND_ROOT_PATH}
        PATH_SUFFIXES
            "lib"
            "local/lib"
    ) 

    FIND_LIBRARY(FOO_LIBRARY_DEBUG
        NAMES
            libfoo
        HINTS
            ${CMAKE_FIND_ROOT_PATH}
        PATHS
            ${CMAKE_FIND_ROOT_PATH}
        PATH_SUFFIXES
            "debug/lib"
            "lib"
            "local/lib"
    ) 

    #fix debug/release libraries mismatch for vcpkg
    if(DEFINED VCPKG_TARGET_TRIPLET)
        set(FOO_LIBRARY_RELEASE ${FOO_LIBRARY_DEBUG}/../../../lib/libfoo.lib)
        get_filename_component(FOO_LIBRARY_RELEASE ${FOO_LIBRARY_RELEASE} REALPATH)
    endif()

    include(SelectLibraryConfigurations)
    select_library_configurations(FOO)
endif()
```

**Comment by mcraveiro** [comment]
For anyone that bumps into this in the future, my current solution/hack is as follows (using C++ Redis [1] here to demonstrate handling of dependencies):

```
find_path(CPP_REDIS_INCLUDE_DIR cpp_redis/cpp_redis)
get_filename_component(CPP_REDIS_INSTALL_DIR ${CPP_REDIS_INCLUDE_DIR} DIRECTORY)
set(CPP_REDIS_DEBUG_DIR ${CPP_REDIS_INSTALL_DIR}/debug/lib)
set(CPP_REDIS_RELEASE_DIR ${CPP_REDIS_INSTALL_DIR}/lib)

#
# tacopie
#
find_library(CPP_TACOPIE_RELEASE_LIBRARY libtacopie.a
    PATHS ${CPP_REDIS_RELEASE_DIR}
    NO_DEFAULT_PATH)
find_library(CPP_TACOPIE_DEBUG_LIBRARY libtacopie.a
    PATHS ${CPP_REDIS_DEBUG_DIR}
    NO_DEFAULT_PATH)

add_library(cpp-redis::libtacopie STATIC IMPORTED)
set_target_properties(cpp-redis::libtacopie PROPERTIES
    IMPORTED_LOCATION_DEBUG ${CPP_REDIS_DEBUG_DIR}/libtacopie.a
    IMPORTED_LOCATION_RELEASE ${CPP_REDIS_DEBUG_DIR}/libtacopie.a
    INTERFACE_INCLUDE_DIRECTORIES "${CPP_REDIS_INCLUDE_DIR}")

#
# cpp-redis
#
find_library(CPP_REDIS_RELEASE_LIBRARY libcpp_redis.a
    PATHS ${CPP_REDIS_RELEASE_DIR}/
    NO_DEFAULT_PATH)
find_library(CPP_REDIS_DEBUG_LIBRARY libcpp_redis.a
    PATHS ${CPP_REDIS_DEBUG_DIR}/
    NO_DEFAULT_PATH)

add_library(cpp-redis::libcpp_redis STATIC IMPORTED)
set_target_properties(cpp-redis::libcpp_redis PROPERTIES
    IMPORTED_LOCATION_DEBUG ${CPP_REDIS_DEBUG_DIR}/libcpp_redis.a
    IMPORTED_LOCATION_RELEASE ${CPP_REDIS_RELEASE_DIR}/libcpp_redis.a
    INTERFACE_INCLUDE_DIRECTORIES "${CPP_REDIS_INCLUDE_DIR}"
    INTERFACE_LINK_LIBRARIES cpp-redis::libtacopie)
```

Notes:

- that I'm not sure if this is the "right" way to handle it or not, but it works for me at present.
- I do a ```find_library``` first just to get an error if the library is missing during config. If you remove those lines, you will get a link error instead.
- with regards to ```find_library```: I could not get @Mixaill's approach to work for me with ```HINTS```, ```PATHS``` and ```PATH_SUFFIXES```. So instead I removed the existing paths (```NO_DEFAULT_PATH```) and hard-coded the path to the specific directories in vcpkg with debug and release binaries.

HTH

[1] https://github.com/cpp-redis/cpp_redis
