### ISSUE TITLE
[winpcap] Build error

### ISSUE THREAD

**Issue by wiresock** [microsoft/vcpkg#29795]
**Host Environment**

- OS: Windows 10
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31937 for x86

**To Reproduce**

`./vcpkg install pcapplusplus:arm64-windows`

**Failure logs**

Installing 2/3 winpcap:arm64-windows...
Building winpcap[core]:arm64-windows...
-- Using cached WpcapSrc_4_1_3.zip.
-- Extracting source C:/vcpkg/downloads/WpcapSrc_4_1_3.zip
-- Applying patch C:/vcpkg/buildtrees/winpcap/src/packetNtx.patch
-- Applying patch C:/vcpkg/buildtrees/winpcap/src/wpcap.patch
-- Applying patch C:/vcpkg/ports/winpcap/create_lib.patch
-- Applying patch C:/vcpkg/ports/winpcap/fix-create-lib-batch.patch
-- Using source at C:/vcpkg/buildtrees/winpcap/src/4_1_3-2020b05bdd.clean
-- Building C:/vcpkg/buildtrees/winpcap/src/4_1_3-2020b05bdd.clean/packetNtx/Dll/Project/Packet.sln for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: msbuild C:/vcpkg/buildtrees/winpcap/src/4_1_3-2020b05bdd.clean/packetNtx/Dll/Project/Packet.sln /p:Configuration=Release /t:Rebuild /p:Platform=arm64 /p:PlatformToolset=v143 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.22621.0 /p:VcpkgManifestInstall=false /p:VcpkgManifestEnabled=false /m /p:VcpkgEnabled=false
    Working Directory: C:/vcpkg/buildtrees/winpcap/arm64-windows-rel
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\winpcap\build-arm64-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:65 (vcpkg_execute_required_process)
  ports/winpcap/portfile.cmake:62 (vcpkg_build_msbuild)
  scripts/ports.cmake:147 (include)

error: building winpcap:arm64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+winpcap
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[winpcap]+Build+error
Include '[winpcap] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 36fb23307 2023-02-10 (12 days ago)

**Comment by jimwang118** [comment]
Please provide the details of the error log: C:\vcpkg\buildtrees\winpcap\build-arm64-windows-rel-out.log.

**Comment by wiresock** [comment]
Here it is:

MSBuild version 17.4.1+9a89d02ff for .NET Framework
Build started 2/22/2023 6:53:40 PM.
     1>Project "C:\vcpkg\buildtrees\winpcap\src\4_1_3-2020b05bdd.clean\packetNtx\Dll\Project\Packet.sln" on node 1 (Rebuild target(s)).
     1>C:\vcpkg\buildtrees\winpcap\src\4_1_3-2020b05bdd.clean\packetNtx\Dll\Project\Packet.sln.metaproj : error MSB4126: The specified solution configuration "Release|arm64" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [C:\vcpkg\buildtrees\winpcap\src\4_1_3-2020b05bdd.clean\packetNtx\Dll\Project\Packet.sln]
     1>Done Building Project "C:\vcpkg\buildtrees\winpcap\src\4_1_3-2020b05bdd.clean\packetNtx\Dll\Project\Packet.sln" (Rebuild target(s)) -- FAILED.

Build FAILED.

       "C:\vcpkg\buildtrees\winpcap\src\4_1_3-2020b05bdd.clean\packetNtx\Dll\Project\Packet.sln" (Rebuild target) (1) ->
       (ValidateSolutionConfiguration target) -> 
         C:\vcpkg\buildtrees\winpcap\src\4_1_3-2020b05bdd.clean\packetNtx\Dll\Project\Packet.sln.metaproj : error MSB4126: The specified solution configuration "Release|arm64" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [C:\vcpkg\buildtrees\winpcap\src\4_1_3-2020b05bdd.clean\packetNtx\Dll\Project\Packet.sln]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.06

**Comment by jimwang118** [comment]
You need to install an **arm build tools**, please install in **visual studio installer**.
![image](https://user-images.githubusercontent.com/122244446/220869482-3ee85369-60cd-4785-9e0e-bf7d2d9d0ddc.png)

**Comment by wiresock** [comment]
Wonder why would I need ARM build tools to build ARM64 version of the library, but I have ARM build tools (Latest) installed as well as ARM64, and x64/x86. I have tried to build `pcapplusplus:arm64-windows` on a couple of machines, always getting the same error. By the way, `vcpkg install pcapplusplus:arm-windows` also fails, x86/x64 configurations build ok.

**Comment by wiresock** [comment]
I've also tried to build it on an ARM64 machine (project Volterra) running native ARM64 VS 2022 with the same result.

**Comment by jimwang118** [comment]
> I've also tried to build it on an ARM64 machine (project Volterra) running native ARM64 VS 2022 with the same result.

Check the log above and find that `pcapplusplus` depends on the `winpcap` installation failure. Check the `vcpkg.json` file in `winpcap`, and you can find that `winpcap `only supports the `Windows` platform.

**Comment by wiresock** [comment]
Thank you for bringing up the limitation of WinPcap only supporting the Windows platform, Jim. To clarify, my objective is to build it for the Windows 10/11 ARM64 platform specifically, which is a version of Windows designed for ARM-based devices.

**Comment by jimwang118** [comment]
@wiresock Have you compiled winpcap on the arm64 platform now?

**Comment by dg0yt** [comment]
AFAICS winpcap is old and unmaintained, and it only supports x86 and x64.

**Comment by jimwang118** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
