### ISSUE TITLE
[New Port Request] ptlib

### ISSUE THREAD

**Issue by soroshsabz** [microsoft/vcpkg#29807]
ITNOA

Library name: ptlib

Library description: Open Phone Abstraction Library (OPAL) is a C++ multi-platform, multi-protocol library for Fax, Video & Voice over IP and other networks. Also included is the Portable Tool Library (PTLib) which is a C++ multi-platform abstraction library.

Source repository URL: https://sourceforge.net/p/opalvoip/ptlib/

Project homepage (if different from the source repository): http://wiki.opalvoip.org/index.php?n=Main.BuildingPTLib

**Comment by soroshsabz** [comment]
I create ticket in official repository of ptlib https://sourceforge.net/p/opalvoip/feature-requests/29/ but I do not have any hope to official team member work on it :(

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
