### ISSUE TITLE
[GDAL] Issue with exposing ogr_s57.h

### ISSUE THREAD

**Issue by MadsTrel** [microsoft/vcpkg#29813]
**Describe the bug**
When compiling and building GDAL with manifest:
`{ "name": "gdal", "version>=": "3.5.1", "features": [ "tools" ] }`
With a cmake file:
`find_package(GDAL CONFIG REQUIRED)`
`target_link_libraries(Test PRIVATE GDAL::GDAL)`

I can not include `#include "ogr_s57.h"` in my project.
I read it would be a part of the drivers - which is on by default in the `portfile.cmake`

1. Is this an error in the vcpkg GDAL?
2. Or do I need to enable some other feature to reach it?
   - If this is the case how can I find this? and couple it to the GDAL documentation?

I tried adding:
`if(PORT MATCHES "gdal")`
`     set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DOGR_BUILD_OPTIONAL_DRIVERS=ON")`
`endif()`
Until I saw it was on by default in the port-file.

**Setup**
- System: Windows x64
- Triplet: Windows-static

**Failure logs**
`C:\projects\testVcpkg\sources\msqTest.cpp(26,10): fatal error C1083: Cannot open include file: 'ogr_s57.h': No such file or directory [C:\projects\testVcpkg\build\sources\Test.vcxproj]`

**Comment by MadsTrel** [comment]
I'm experiencing the same issue with iso8211.h, shapefile.h.

**Comment by dg0yt** [comment]
Are you sure these headers are meant to be installed and not internal to gdal?
(Cannot check it myself at the moment.)

**Comment by MadsTrel** [comment]
I think your right. Even though I'm not entirely sure how to check it.

**Comment by dg0yt** [comment]
Basically we rely on gdal doing the right thing when callling `make install`.
And this is the public API:
https://gdal.org/api/index.html
