### ISSUE TITLE
[poco] Can't use JWT features on Windows 

### ISSUE THREAD

**Issue by mcgorias** [microsoft/vcpkg#29814]
Hi, here is a problem I have when trying to build an application that uses JWT feature of POCO on Windows.

**Describe the bug**
I am trying to use [JWT features of Poco library](https://docs.pocoproject.org/current/package-JWT.JWT.html). 
The current Poco port doesn't seem to manage Poco JWT package properly.

A minimal example is available [here](https://github.com/mcgorias/poco-jwt-test.git)

**Environment**
- OS: Windows 
- Compiler: `MSVC 19.16.27045.0`

**To Reproduce**

```
git clone --recurse-submodules https://github.com/mcgorias/poco-jwt-test.git
cd poco-jwt-test
mkdir build
cmake  -B build .   --toolchain ../vcpkg/scripts/buildsystems/vcpkg.cmake
```

**Expected behavior**
CMake should be able to find the `jwt` component of Poco

**Failure logs**
```
[...]
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:842 (_find_package):
  Could not find a package configuration file provided by "Pocojwt" with any
  of the following names:

    PocojwtConfig.cmake
    pocojwt-config.cmake

  Add the installation prefix of "Pocojwt" to CMAKE_PREFIX_PATH or set
  "Pocojwt_DIR" to a directory containing one of the above files.  If
  "Pocojwt" provides a separate development package or SDK, be sure it has
  been installed.
  
```` 

**Additional context**

However,
If I apply the following patch on Poco port, the CMake generation goes well, I am able to include Poco JWT features and the application compiles and link properly. (Of course, It's not a good solution)

```patch
diff --git a/ports/poco/portfile.cmake b/ports/poco/portfile.cmake
index c9e079bb5..7124bfdca 100644
--- a/ports/poco/portfile.cmake
+++ b/ports/poco/portfile.cmake
@@ -34,7 +34,7 @@ vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
 )
 
 if("netssl" IN_LIST FEATURES)
-    if(VCPKG_TARGET_IS_WINDOWS)
+    if(VCPKG_TARGET_IS_WINDOWS AND FALSE)
         list(APPEND FEATURE_OPTIONS
             -DENABLE_NETSSL_WIN=ON
             -DENABLE_NETSSL=OFF
diff --git a/ports/poco/vcpkg.json b/ports/poco/vcpkg.json
index a4f1e2fa8..c72f1c9dc 100644
--- a/ports/poco/vcpkg.json
+++ b/ports/poco/vcpkg.json
@@ -36,8 +36,7 @@
       "description": "NetSSL support for POCO",
       "dependencies": [
         {
-          "name": "openssl",
-          "platform": "!windows"
+          "name": "openssl"
         }
       ]
     },

```

You can try the patch :
```
git clone --recurse-submodules https://github.com/mcgorias/poco-jwt-test.git
cd poco-jwt-test
git apply --directory vcpkg poco.jwt.fixup.patch
mkdir build
cmake  -B build .   --toolchain ../vcpkg/scripts/buildsystems/vcpkg.cmake
cmake --build build
```

Thanks,
Regards,
Steven

**Comment by Adela0814** [comment]
Please use the `netssl` feature in a non-windows environment.
`vcpkg install poco[netssl]`

```
option(ENABLE_NETSSL_WIN "Enable NetSSL Windows" OFF)
option(FORCE_OPENSSL "Force usage of OpenSSL even under windows" OFF)

if(ENABLE_CRYPTO OR ENABLE_NETSSL OR ENABLE_JWT)
	find_package(OpenSSL REQUIRED)
else()
	find_package(OpenSSL)
endif()

if(OPENSSL_FOUND)
	option(ENABLE_NETSSL "Enable NetSSL" ON)
	option(ENABLE_CRYPTO "Enable Crypto" ON)
	option(ENABLE_JWT "Enable JWT" ON)
else()
	option(ENABLE_NETSSL "Enable NetSSL" OFF)
	option(ENABLE_CRYPTO "Enable Crypto" OFF)
	option(ENABLE_JWT "Enable JWT" OFF)
endif()
```

**Comment by mcgorias** [comment]
Hi @Adela0814, and thanks for your answer.

Do you mean that `netssl` should not be used with Windows ?

**Comment by dg0yt** [comment]
The netssl feature is somewhat broken on windows at the moment. #29754 tries to fix it.
IIRC JWT is enabled when openssl is available. With #29754, this will be controlled by a new feature "crypto".

**Comment by mcgorias** [comment]
> The netssl feature is somewhat broken on windows at the moment. #29754 tries to fix it. IIRC JWT is enabled when openssl is available. With #29754, this will be controlled by a new feature "crypto".

I see !
I observed the issue last week, posted only yesterday and didn't see your work. Great news ! Thank you !
