### ISSUE TITLE
vcpkg: Proxy variables don't allow ending slash and can require deleting vcpkg storage

### ISSUE THREAD

**Issue by froha** [microsoft/vcpkg#29815]
Hi,

we are using already vcpkg in our project.
The new version of this extension supports it, but the activation fails.

Environment variables:
HTTP_PROXY = "http://127.0.0.1:9000"
HTTPS_PROXY = "http://127.0.0.1:9000"
VCPKG_ROOT = "C:\folder1\vcpkg"

vcpkg output:

> Using vcpkg executable at "c:\Users\Abcdefghjkl.Mnopqrst\.vscode\extensions\ms-vscode.vscode-embedded-tools-0.6.0-win32-x64\assets\platform\win32-x64\vcpkg.exe".
> Using VCPKG_ROOT at "c:\Users\Abcdefghjkl.Mnopqrst\AppData\Roaming\Code\User\globalStorage\ms-vscode.vscode-embedded-tools\vcpkg\root".
> Activating environment at "c:\folder1\folder2\folder3\folder4\vcpkg-configuration.json".
> Version of vcpkg used to create VCPKG_ROOT: "2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75".
> Running vcpkg with arguments ["version"].
vcpkg package management program version 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75

See LICENSE.txt for license information.
> Bundled version of vcpkg: "2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75".
> Running vcpkg with arguments ["activate","--project","c:\\folder1\\folder2\\folder3\\folder4","--json","C:\\Users\\ABCDEF~1.MNO\\AppData\\Local\\Temp\\5498db1ee5c2b10b3d88c1dc7d0a2aa7"].
warning: vcpkg-ce ('configure environment') is experimental and may change at any time.
read_contents("C:\Users\Abcdefghjkl.Mnopqrst\AppData\Roaming\Code\User\globalStorage\ms-vscode.vscode-embedded-tools\vcpkg\root\scripts\vcpkgTools.xml"): no such file or directory
> Failed with exit code "1".
> Failed to activate environment at "c:\folder1\folder2\folder3\folder4\vcpkg-configuration.json".

The activation failed and the enviroment variable VCPKG_ROOT is ignored.
Using VCPKG_ROOT at "c:\Users\Abcdefghjkl.Mnopqrst\AppData\Roaming\Code\User\globalStorage\ms-vscode.vscode-embedded-tools\vcpkg\root".

And don't use the following environment variable wit a slash at the end:
HTTP_PROXY = "http://127.0.0.1:9000/"
HTTPS_PROXY = "http://127.0.0.1:9000/"
It will fail, that is also a problem with other tools/extension, because the need the slash at the end.

**Comment by LilyWangLL** [comment]
@dan-shaw Could you please take a look this issue? Thanks in advance.

**Comment by BillyONeal** [comment]
Part of the issue is that we don't really do anything with the proxy variables beyond forwarding them to the real HTTP implementations, such as WinHTTP here:

https://github.com/microsoft/vcpkg-tool/blob/0739c62652542f5af55eea9d248977c62d62cf55/src/vcpkg/base/downloads.cpp#LL249C24-L249C24

**Comment by BillyONeal** [comment]
> If the environment variable HTTP_PROXY has trailing slash (HTTP_PROXY = "http://127.0.0.1:9000/"), then it will fail.

For what it's worth I believe this is implied by the HTTP spec, as no directory component on the proxy is ever used. If there are extensions or tools requiring a trailing slash, that seems incorrect to me.

**Comment by froha** [comment]
PlatformIO IDE extension for Visual Studio Code needs the slash at the end.
[https://community.platformio.org/t/platformio-ide-in-vscode-cant-connect-to-the-internet-blocked-by-proxy/5449/3](https://community.platformio.org/t/platformio-ide-in-vscode-cant-connect-to-the-internet-blocked-by-proxy/5449/3)
