### ISSUE TITLE
vcpkg.cmake need to support FILESET for CXX_MODULE

### ISSUE THREAD

**Issue by monamimani** [microsoft/vcpkg#29826]
****

**Is your feature request related to a problem? Please describe.**
I was trying vcpkg+cmake 3.26.0-rc4+ninja+cxx_module and following that [blog post](https://www.kitware.com/import-cmake-c20-modules/) and during the configure step I got this error.

```
CMake Error at ****/vcpkg/scripts/buildsystems/vcpkg.cmake:585 (_add_executable):
  Cannot find source file:

    FILE_SET
```

**Proposed solution**
I am assuming it is an issue with vcpkg.cmake so it should support FILESET of types `CXX_MODULES` and `CXX_MODULE_HEADER_UNITS` and other FILESETS.

**Describe alternatives you've considered**
None the error is in vcpkg.cmake

**Additional context**
Thank you

**Comment by JackBoosY** [comment]
https://cmake.org/cmake/help/latest/release/3.23.html?highlight=file_set#id11

We should limit the cmake version to 3.23 or later.

**Comment by dg0yt** [comment]
> https://cmake.org/cmake/help/latest/release/3.23.html?highlight=file_set#id11
> 
> We should limit the cmake version to 3.23 or later.

I think this is unrelated to the problem.

IIUC `FILE_SET` can be used [`target_sources`](https://cmake.org/cmake/help/latest/command/target_sources.html#command:target_sources) but not with [`add_executable`](https://cmake.org/cmake/help/latest/command/add_executable.html). Not a vcpkg bug.

**Comment by JackBoosY** [comment]
> > https://cmake.org/cmake/help/latest/release/3.23.html?highlight=file_set#id11
> > We should limit the cmake version to 3.23 or later.
> 
> I think this is unrelated to the problem.
> 
> IIUC `FILE_SET` can be used [`target_sources`](https://cmake.org/cmake/help/latest/command/target_sources.html#command:target_sources) but not with [`add_executable`](https://cmake.org/cmake/help/latest/command/add_executable.html). Not a vcpkg bug.

Yes, after read the related code, I assume this is not a vcpkg bug.

**Comment by monamimani** [comment]
I am not sure I understand.

Are you saying that CMake refused FILESET for a target_source that is an executable. I doubt that, since they use FILESET to know what files are c++ modules, and that would mean we can't use c++ modules in executables. (Unless it is a bug with CMake, I'll open a bug on their side to see).

I guess the question is what refused the FILESET, vcpkg.cmake or CMake itself.

Thank you

**Comment by dg0yt** [comment]
CMake itself.
The error message indicates that you tried to use `FILE_SET` with `add_executable`.
AFAICT this CMake command doesn't understand this command. You must use this option with `target_sources`.

**Comment by monamimani** [comment]
That is what I do.

```
  add_executable(${targetNameTests})

  target_sources(${targetNameTests}
    PRIVATE
      ${ADD_TEST_TARGET_MAINFILE}
      ${ADD_TEST_TARGET_PRIVATEFILES}
      ${ADD_TEST_TARGET_TESTFILES}
    PUBLIC
      ${ADD_TEST_TARGET_PUBLICFILES}
      FILE_SET ${targetNameTests}_cxx_modules TYPE CXX_MODULES FILES ${ADD_TEST_TARGET_MODULEFILES}
      #FILE_SET ${targetNameTests}_cxx_header_unit TYPE CXX_MODULE_HEADER_UNITS FILES ${ADD_TEST_TARGET_HEADERUNITFILES}
    INTERFACE
      ${ADD_TEST_TARGET_INTERFACEFILES}
  )
```

I also opened an issue on their side.

**Comment by dg0yt** [comment]
> That is what I do.

... then the error reporting may be misleading. Some CMake errors are reported late (at "generation" time).

I still don't see hwo this could be related to vcpkg. And we know litte about your input files, output and CMake version. Maybe you try a small example without vcpkg. Make sure you do actually use a CMake version which supports this option.

**Comment by monamimani** [comment]
The CMake version is in the original bug report, 3.26.0-rc4.

If the error is with my use of CMake and file, then the error is really not clear.

Thanks for your help!

**Comment by bradking** [comment]
The error message is misleading in that it points to the line where the target was defined rather than the line that tried to add the missing source file.  I've opened [CMake Issue 24538](https://gitlab.kitware.com/cmake/cmake/-/issues/24538) for that.  The reason vcpkg appears involved is that it is abusing CMake's undocumented debugging feature to override `add_executable`.

The main problem reported in this issue is being discussed in [CMake Issue 24537](https://gitlab.kitware.com/cmake/cmake/-/issues/24537).  This issue can be closed on the vcpkg side.

**Comment by monamimani** [comment]
@bradking Thanks again for all your help.

For completeness, I'll write the solution here as well.

My issue was that: "The [target_source FILE_SET docs](https://cmake.org/cmake/help/v3.26/command/target_sources.html#file-sets) specify that FILE_SET must immediately follow the visibility specifier" and it wasn't

This is now working: `PUBLIC FILE_SET CXX_MODULES FILES ${ADD_TEST_TARGET_MODULEFILES}`
