### ISSUE TITLE
GSL dynamic libraries are not copied to dependent targets output folder

### ISSUE THREAD

**Issue by MathiasMagnus** [Microsoft/vcpkg#2982]
I recently uncovered that when dynamically linking to GSL built by Vcpkg, the executables fails to launch, because the DLLs are not next to the EXEs. This is all using CMake for consuming GSL.

Please fix.

**Comment by ras0219-msft** [comment]
Thanks for the bug report! It should be fixed in master (package version 2.4-3) :)
