### ISSUE TITLE
doesn't install package

### ISSUE THREAD

**Issue by Mathias-Fuchs** [Microsoft/vcpkg#2983]
Followed the instructions in https://github.com/Microsoft/vcpkg/blob/master/docs/examples/using-sqlite.md word-by-word but fails to install sqlite3 ... :
After running `.\vcpkg integrate install` with admin privilege, and asking vcpkg to install sqlite3, it still doesn't appear in the list.

![capture](https://user-images.githubusercontent.com/16633899/37117915-7977e190-224a-11e8-8579-dee5436b1453.PNG)

**Comment by ras0219-msft** [comment]
Hi @Mathias-Fuchs, sorry you're having this issue!

It looks like vcpkg is crashing during the configure step; a full install should look like:
![image](https://user-images.githubusercontent.com/12301622/37120855-68cd65f2-2210-11e8-8891-fc478a0b47c6.png)

Could you run `.\vcpkg install sqlite3 --debug` and post the line it's failing on?

**Comment by Mathias-Fuchs** [comment]
Hi @ras0219-msft , thanks for the answer. Here's what happens with `.\vcpkg install sqlite3 --debug`:
![capture2](https://user-images.githubusercontent.com/16633899/37149276-5a9be390-22c5-11e8-97a5-8576ffd5ade2.PNG)

Mathias

**Comment by JackBoosY** [comment]
Hi @Mathias-Fuchs , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
