### ISSUE TITLE
[ICU] ICU cannot be compiled with mingw in Windows environment.

### ISSUE THREAD

**Issue by dym21** [microsoft/vcpkg#29832]
- OS: Windows 11
- Compiler: gcc version 12.2.0 (Rev10, Built by MSYS2 project)

`./vcpkg install  icu:x86-mingw-dynamic`

-- Generating configure for x86-mingw-dynamic
-- Finished generating configure for x86-mingw-dynamic
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at D:/GitHub/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Configuring x86-mingw-dynamic-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: D:/GitHub/vcpkg/downloads/tools/msys2/18a5d10fcd7c4950/usr/bin/bash.exe --noprofile --norc --debug -c "V=1 CPP='i686-w64-mingw32-gcc.exe -E' CC='i686-w64-mingw32-gcc.exe' CC_FOR_BUILD='touch a.out | touch conftest.exe | true' CPP_FOR_BUILD='touch a.out | touch conftest.exe | true' CXX_FOR_BUILD='touch a.out | touch conftest.exe | true' CXX='i686-w64-mingw32-g++.exe' RC='windres.exe' WINDRES='windres.exe' AR='ar.exe' LD='ld.exe -verbose' RANLIB='ranlib.exe' OBJDUMP='objdump.exe' STRIP='strip.exe' NM='nm.exe' DLLTOOL='dlltool.exe' CCAS=':' AS=':' ./../src/c-72_1-src-deba61ed52.clean/source/configure --build=x86_64-pc-mingw32 --host=i686-pc-mingw32 \"--enable-icu-build-win\" \"--disable-samples\" \"--disable-tests\" \"--disable-layoutex\" \"--disable-tools\" \"gl_cv_double_slash_root=yes\" \"ac_cv_func_memmove=yes\" \"--disable-silent-rules\" \"--verbose\" \"--enable-shared\" \"--disable-static\" \"--enable-debug\" \"--disable-release\" \"--prefix=/D/GitHub/vcpkg/installed/x86-mingw-dynamic/debug\" \"--bindir=\\${prefix}/../tools/icu/debug/bin\" \"--sbindir=\\${prefix}/../tools/icu/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/icu\""
    Working Directory: D:/GitHub/vcpkg/buildtrees/icu/x86-mingw-dynamic-dbg
    Error code: 1
    See logs for more information:
      D:\GitHub\vcpkg\buildtrees\icu\config-x86-mingw-dynamic-dbg-config.log
      D:\GitHub\vcpkg\buildtrees\icu\config-x86-mingw-dynamic-dbg-out.log
      D:\GitHub\vcpkg\buildtrees\icu\config-x86-mingw-dynamic-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:812 (vcpkg_execute_required_process)
  ports/icu/portfile.cmake:55 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)

error: building icu:x86-mingw-dynamic failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+icu
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[icu]+Build+error
Include '[icu] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 54cc53c43 2023-02-23 (7 hours ago)

Please use the prefilled template from D:\GitHub\vcpkg\installed\vcpkg\issue_body.md when reporting your issue.

[config-x86-mingw-dynamic-dbg-config.log](https://github.com/microsoft/vcpkg/files/10821910/config-x86-mingw-dynamic-dbg-config.log)
[config-x86-mingw-dynamic-dbg-err.log](https://github.com/microsoft/vcpkg/files/10821911/config-x86-mingw-dynamic-dbg-err.log)

**Comment by JackBoosY** [comment]
```
configure: WARNING: unrecognized options: --disable-silent-rules
configure: error: Error! Cross compiling but no --with-cross-build option specified - please supply the path to an executable ICU's build root
```

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
