### ISSUE TITLE
[cudnn] Build error

### ISSUE THREAD

**Issue by KirkPen** [microsoft/vcpkg#29846]
Package: cudnn[core]:x64-windows -> 7.6.5#8

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.35.32215.0
-    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 703a8113f 2023-02-21 (3 days ago)

**To Reproduce**

`vcpkg install opencv4[contrib,cuda,default-features,dnn,jpeg,png,quirc,tbb,tiff,webp,vtk,tbb,sfm,python,opengl,nonfree,ipp,halide,eigen,cudnn]`

**Failure logs**

```
-- Found CUDA V12.0.140
-- CUDNN_INCLUDE_DIR: CUDNN_INCLUDE_DIR-NOTFOUND
-- CUDNN_LIBRARY: CUDNN_LIBRARY-NOTFOUND
CMake Error at ports/cudnn/portfile.cmake:59 (message):
  Please download CUDNN from official sources (such as
  https://developer.nvidia.com/rdp/cudnn-download ) and extract the zip into
  your CUDA_TOOLKIT_ROOT (C:/Program Files/NVIDIA GPU Computing
  Toolkit/CUDA/v12.0).  (For example: tar.exe -xvf
  cudnn-11.2-windows-x64-v8.1.1.33.zip --strip 1 --directory "C:/Program
  Files/NVIDIA GPU Computing Toolkit/CUDA/v12.0"
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)



```

**Additional context**

**Comment by StarGate-One** [comment]
>Please download CUDNN from official sources (such as
>  https://developer.nvidia.com/rdp/cudnn-download ) and extract the zip into
>  your CUDA_TOOLKIT_ROOT (C:/Program Files/NVIDIA GPU Computing
>  Toolkit/CUDA/v12.0)

You will need to signup/register for the NVIDIA developers access, then you can download and install CUDNN, then you can run `.\vcpkg.exe install cudnn` and it should install providing you have the CUDNN_BIN_DIR, CUDNN_INCLUDE_DIR and CUDNN_LIBRARY environment variables set accordingly.

**Comment by KirkPen** [comment]
yep that was it. Why is that not something vcpkg does for me? Nvidia not playing nice?
Thanks. 2 hr 36 min to build on i9 13900k 64 gig asrock lightning nvme.

**Comment by StarGate-One** [comment]
It is most likely because someone has to signup/register to get to the page where you can download cudnn.

**Comment by mvsg2** [comment]
> > Please download CUDNN from official sources (such as
> > https://developer.nvidia.com/rdp/cudnn-download ) and extract the zip into
> > your CUDA_TOOLKIT_ROOT (C:/Program Files/NVIDIA GPU Computing
> > Toolkit/CUDA/v12.0)
> 
> You will need to signup/register for the NVIDIA developers access, then you can download and install CUDNN, then you can run `.\vcpkg.exe install cudnn` and it should install providing you have the CUDNN_BIN_DIR, CUDNN_INCLUDE_DIR and CUDNN_LIBRARY environment variables set accordingly.


Hello, I have had the same issue. Can you help me through the solution that you provided here? I may need a little step-by-step  assistance with this procedure. Thanks a lot in advance and I apologize for any inconvenience caused.

**Comment by mvsg2** [comment]
![image](https://user-images.githubusercontent.com/89340753/230983073-179494af-9b5a-4bc7-975e-ff5f7c9e12f3.png)


For your reference, this is the error message I got.
