### ISSUE TITLE
[ffmpeg] Improve compile time

### ISSUE THREAD

**Issue by luizfernandonb** [microsoft/vcpkg#29851]
**Is your feature request related to a problem? Please describe.**
ffmpeg is taking too long to compile for both Release and Debug. (About 25 minutes, not sure)

**Proposed solution**
Put the -j$(NUMBER_OF_PROCESSORS [Windows]) flag when ninja is going to build ffmpeg, I manually injected it into the script and it practically compiled ffmpeg in less than 30 seconds, it just didn't complete the entire build process because the other steps gave an error for not recognizing the "-j" flag.

**Comment by StarGate-One** [comment]
Have you tried setting the `VCPKG_MAX_CONCURRENCY` environment variable?

**Comment by luizfernandonb** [comment]
> Have you tried setting the `VCPKG_MAX_CONCURRENCY` environment variable?

yes, the ninja build didn't change anything
![image](https://user-images.githubusercontent.com/42288418/221331414-e496637f-7aa3-4261-92fd-6ac6b501fa5c.png)

only CMake compilation changed
![image](https://user-images.githubusercontent.com/42288418/221331451-ce5ffa30-7d47-48d9-a6fe-7ef5c0092da9.png)

**Comment by StarGate-One** [comment]
> ->ninja --help
>usage: ninja [options] [targets...]
>
>if targets are unspecified, builds the 'default' target (see manual).
>
>options:
>  --version      print ninja version ("1.11.1")
> ...
>  -j N     run N jobs in parallel (0 means infinity) [default=26 on this system] **_(as my cpu has 24 logical cores)_**
> ...

By default ninja uses (number of processors + 2).
Not all tools used with vcpkg support parallel and/or a concurrency features/options.

**Comment by luizfernandonb** [comment]
> > ->ninja --help
> > usage: ninja [options] [targets...]
> > if targets are unspecified, builds the 'default' target (see manual).
> > options:
> > --version      print ninja version ("1.11.1")
> > ...
> > -j N     run N jobs in parallel (0 means infinity) [default=26 on this system] **_(as my cpu has 24 logical cores)_**
> > ...
> 
> By default ninja uses (number of processors + 2). Not all tools used with vcpkg support parallel and/or a concurrency features/options.

that's weird, so ninja compilation should be fast as if i put the "-j" flag manually since it uses number of processors + 2, but it's not, i don't know why, ninja compilation is only fast when i set the flag manually
