### ISSUE TITLE
[clapack] FindLAPACK.cmake assumes that a debug build was done

### ISSUE THREAD

**Issue by josch** [microsoft/vcpkg#29864]
Hi,

clapack ships a custom FindLAPACK.cmake with lines like:

    find_library(LAPACK_LIBRARY_RELEASE NAMES lapack)
    find_library(LAPACK_LIBRARY_DEBUG NAMES lapackd)

This means that even with `set(VCPKG_BUILD_TYPE release)` in my triplet file, `FindLAPACK.cmake` will try to find files that are only built when a debug build is done. As a result projects (gmt in this case) that need clapack fail with:

```
Using VCPKG FindLAPACK from package 'clapack'
[...]
Found LAPACK: optimized;D:/a/MB-System/MB-System/vcpkg/installed/x64-windows-release/lib/lapack.lib;optimized;D:/a/MB-System/MB-System/vcpkg/installed/x64-windows-release/lib/libf2c.lib;optimized;D:/a/MB-System/MB-System/vcpkg/installed/x64-windows-release/lib/openblas.lib;debug;LAPACK_LIBRARY_DEBUG-NOTFOUND;debug;F2C_LIBRARY_DEBUG-NOTFOUND;debug;D:/a/MB-System/MB-System/vcpkg/installed/x64-windows-release/bin/openblas.dll  
[...]
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
F2C_LIBRARY_DEBUG (ADVANCED)
    linked by target "gmtlib" in directory D:/a/MB-System/MB-System/vcpkg/buildtrees/gmt/src/6.4.0-e68f37c70c.clean/src
LAPACK_LIBRARY_DEBUG (ADVANCED)
    linked by target "gmtlib" in directory D:/a/MB-System/MB-System/vcpkg/buildtrees/gmt/src/6.4.0-e68f37c70c.clean/src
```

I had a look at other custom FindXXX.cmake files and was unable to find any that did **not** add both `_RELEASE` as well as `_DEBUG` libs independent of the `VCPKG_BUILD_TYPE`. Is this intended behaviour and are libraries like clapack just not supposed to work when setting `VCPKG_BUILD_TYPE` to `release`?

**Comment by Neumann-A** [comment]
a) CMake Generator?
b) vcpkg uses select_library_configurations to set the corresponding `_LIBRARIES` variable correctly.

**Comment by josch** [comment]
> a) CMake Generator? b) vcpkg uses select_library_configurations to set the corresponding `_LIBRARIES` variable correctly.

I'm sorry, your reply is way to brief for me to understand what you want to tell me.

a) what should use a CMake Generator? Should one be added to `FindLAPACK.cmake` to fill the variables correctly?
b) what should use `select_library_configurations`? Evidently `FindLAPACK.cmake` is doing the wrong thing. How does `select_library_configurations` help me?

**Comment by Neumann-A** [comment]
I want to know which CMake Generator you used.

>  Evidently FindLAPACK.cmake is doing the wrong thing. 

That depends on the answer of a). For me there is no evidence about that yet. There might be an issue but its not obvious from reading `FindLAPACK.cmake`

**Comment by josch** [comment]
Ah okay, sorry. The generator is Ninja. You can find a full build log here: https://github.com/josch/MB-System/actions/runs/4272305423/jobs/7437349307

The error happened as a result of attempting to add a new port for GMT (which needs clapack) with this portfile.cmake: https://github.com/josch/vcpkg/blob/67fde25e57858ee060eb0db12fbd0a2bcd13eabe/ports/gmt/portfile.cmake

**Comment by Neumann-A** [comment]
consider using `lapack` and `blas` as dependencies. 
consider bumping/patching `cmake_minimum_required (VERSION 2.8.12)` to like 3.7 and move it to the top of the `CMakeLists.txt`

**Comment by josch** [comment]
Thank you!

 - Patching `CMakeLists.txt` with this patch https://github.com/josch/vcpkg/blob/master/ports/gmt/cmake_minimum_required.patch as you suggested did not change the error: https://github.com/josch/MB-System/actions/runs/4275935451/jobs/7443669950
 - Replacing clapack with lapack and blas makes configuration work. The reason I chose clapack is because GMT uses clapack from vcpkg in their own git actions: https://github.com/GenericMappingTools/gmt/blob/master/ci/install-dependencies-windows.sh#L22

I though that clapack is broken when not doing a Debug build because GMT uses it but they build both Debug and Release binaries.

My immediate use-case is satisfied by switching out clapack for lapack and blas, so feel free to close this issue if you think that there is no problem with FindLAPACK.cmake from clapack.

Thanks a lot for your help!

**Comment by Neumann-A** [comment]
So there might be an issue with FindLAPACK.cmake from clapack in single config builds but i don't get why you get the output:

`Found LAPACK: optimized;D:/a/MB-System/MB-System/vcpkg/installed/x64-windows-release/lib/lapack.lib;optimized;D:/a/MB-System/MB-System/vcpkg/installed/x64-windows-release/lib/libf2c.lib;optimized;D:/a/MB-System/MB-System/vcpkg/installed/x64-windows-release/lib/openblas.lib;debug;LAPACK_LIBRARY_DEBUG-NOTFOUND;debug;F2C_LIBRARY_DEBUG-NOTFOUND;debug;D:/a/MB-System/MB-System/vcpkg/installed/x64-windows-release/bin/openblas.dll`

`select_library_configurations` should filter out the `-NOTFOUND` stuff and not add `optimized/debug` keywords if _DEBUG variables are not found. 

Nevermind. it is probably because `select_library_configurations(LAPACK)` is not directly after the `find_library` calls for lapack but after openblas gets appended to it.
