### ISSUE TITLE
[cpr] update to <1.10.0>

### ISSUE THREAD

**Issue by sornian** [microsoft/vcpkg#29863]
Library name:cpr

New version number:1.10.0

Other information that may be useful (release notes, etc...)

https://github.com/libcpr/cpr

**Comment by autoantwort** [comment]
It is already included

**Comment by Flordjam** [comment]
Hi,
When I use vcpkg on windows 10 , none x64 files are generated. Only x86. Have you got an idea ?
I did on Command prompt
`git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
bootstrap-vcpkg.sh
vcpkg integrate install
vcpkg install cpr`

**Comment by autoantwort** [comment]
`vcpkg install cpr:x64-windows`

**Comment by MonicaLiu0311** [comment]
Fixed by #30747.
