### ISSUE TITLE
[darknet] Build error

### ISSUE THREAD

**Issue by andreemidio** [microsoft/vcpkg#29878]
**Host Environment**

- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**

`./vcpkg install xxxx`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Cheney-W** [comment]
Please provide the information required on the question template.

**Comment by Cheney-W** [comment]
Thanks for posting this issue. Please reopen this issue and provide us with the detailed info of this issue if it is still a problem for you.
