### ISSUE TITLE
[sentencepiece]: x64-windows-static-md  Build failure

### ISSUE THREAD

**Issue by jerrypcl** [microsoft/vcpkg#29889]
D:\microsoft\vcpkg>vcpkg.exe  install sentencepiece  --triplet x64-windows-static-md
Computing installation plan...
The following packages will be built and installed:
    sentencepiece[core]:x64-windows-static-md -> 0.1.97#2
Detecting compiler hash for triplet x64-windows-static-md...
Restored 0 package(s) from C:\Users\pcl\AppData\Local\vcpkg\archives in 837 us. Use --debug to see more details.
Installing 1/1 sentencepiece:x64-windows-static-md...
Building sentencepiece[core]:x64-windows-static-md...
warning: -- Using community triplet x64-windows-static-md. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: D:\microsoft\vcpkg\triplets\community\x64-windows-static-md.cmake
CMake Error at scripts/cmake/vcpkg_check_linkage.cmake:34 (message):
  sentencepiece only supports static crt linkage
Call Stack (most recent call first):
  ports/sentencepiece/portfile.cmake:2 (vcpkg_check_linkage)
  scripts/ports.cmake:147 (include)

error: building sentencepiece:x64-windows-static-md failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+sentencepiece
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[sentencepiece]+Build+error
Include '[sentencepiece] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 223d33be7 2023-02-24 (2 days ago)

Please use the prefilled template from D:\microsoft\vcpkg\installed\vcpkg\issue_body.md when reporting your issue.

Package: sentencepiece[core]:x64-windows-static-md -> 0.1.97#2

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.29.30147.0
-    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 223d33be7 2023-02-24 (2 days ago)

**To Reproduce**

`vcpkg install sentencepiece`

**Failure logs**

```
CMake Error at scripts/cmake/vcpkg_check_linkage.cmake:34 (message):
  sentencepiece only supports static crt linkage
Call Stack (most recent call first):
  ports/sentencepiece/portfile.cmake:2 (vcpkg_check_linkage)
  scripts/ports.cmake:147 (include)



```

**Additional context**
 need to  build x64-windows-static-md instead of the default  x64-windows-static-mt

**Comment by autoantwort** [comment]
Please report this at sentencepiece

**Comment by FrankXie05** [comment]
It's a community triplet and we need upstream confirmation. :)
