### ISSUE TITLE
X_VCPKG_APPLOCAL_DEPS_INSTALL does not work with CMAKE_INSTALL_PREFIX without drive letter

### ISSUE THREAD

**Issue by jobor** [microsoft/vcpkg#29890]
**How to reproduce**
Consider the example project in [reproducer.zip](https://github.com/microsoft/vcpkg/files/10838707/reproducer.zip):

```
# CMakeLists.txt
cmake_minimum_required(VERSION 3.16)
project(vcpkg_prefix_issue)
find_package(fmt REQUIRED)
add_executable(myapp main.cpp)
target_link_libraries(myapp PRIVATE fmt::fmt)
install(TARGETS myapp)
```

```
// vcpkg.json
{
  "name": "myapp",
  "version-string": "1.2.3",
  "dependencies": [
    "fmt"
  ]
}
```

```
// main.cpp
#include <fmt/format.h>

int main(int argc, char *argv[])
{
    fmt::print("the magic number is {}\n", 192837);
    return 0;
}
```

configured with
```
cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/my-install-root -DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_TOOLCHAIN_FILE=D:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake ${source-dir}"
```

Note that `CMAKE_INSTALL_PREFIX` is specified without drive letter.

built and installed with
```
cmake --build . && cmake --install .
```

The installation directory's content is after the last step:
```
D:\MY-INSTALL-ROOT
└───bin
        myapp.exe
```

The fmt DLL is missing.

**Configuring with drive letter works**

Configuring with `CMAKE_INSTALL_PREFIX` starting with a drive letter fixes the issue:
```
cmake -G Ninja -DCMAKE_INSTALL_PREFIX=d:/my-install-root -DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_TOOLCHAIN_FILE=D:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake ${source-dir}"
```

After build and installation:
```
D:\MY-INSTALL-ROOT
└───bin
        fmtd.dll
        myapp.exe
```

Enabling verbose output in `scripts/buildsystems/msbuild/applocal.ps1` suggests that dependencies of the executable cannot be resolved. 

**Why don't I just specify the drive letter then?**

Our (Qt's) CI uses the `DESTDIR` environment variable to divert the install root. That only works reliably on Windows if there's no drive letter in the install root specified.

**Environment**
- OS: Windows
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31942 for x64

**Expected behavior**
Installation of app dependencies should work with and without drive letter in `CMAKE_INSTALL_PREFIX`.

**Comment by Neumann-A** [comment]
Have you tried:
`-DCMAKE_INSTALL_PREFIX=my-install-root` ?

paths with leading `/` are commonly regarded as absolute paths.

**Comment by jobor** [comment]
That won't work, because this will result in a `CMAKE_INSTALL_PREFIX` that is under `CMAKE_BINARY_DIR`.
Rerooting this via `DESTDIR` will install in `$ENV{DESTDIR}/${CMAKE_BINARY_DIR}/${CMAKE_INSTALL_PREFIX}`.

But I think I have a fix. Patch incoming.

**Comment by dg0yt** [comment]
> That won't work, because this will result in a `CMAKE_INSTALL_PREFIX` that is under `CMAKE_BINARY_DIR`.
> Rerooting this via `DESTDIR` will install in `$ENV{DESTDIR}/${CMAKE_BINARY_DIR}/${CMAKE_INSTALL_PREFIX}`.

AFAICT CMake support for `DESTDIR` is documented only for `UNIX`:
https://cmake.org/cmake/help/v3.26/variable/CMAKE_INSTALL_PREFIX.html?highlight=cmake_install_prefix
IMO it is expected to come with drive letter on Windows.

**Comment by jobor** [comment]
> AFAICT CMake support for `DESTDIR` is documented only for `UNIX`: https://cmake.org/cmake/help/v3.26/variable/CMAKE_INSTALL_PREFIX.html?highlight=DESTDIR IMO it is expected to come with drive letter on Windows.

DESTDIR is documented for Unix only, yes. Still, it works on Windows as well - even though this is a borderline hack, admittedly.

**Comment by Neumann-A** [comment]
Am I the only one concerned about Qt CI depending on an `X_VCPKG_` feature instead of using CMakes builtin file([GET_RUNTIME_DEPENDENCIES](https://cmake.org/cmake/help/latest/command/file.html#get-runtime-dependencies) [...]) or calling `windeployqt`?

**Comment by jobor** [comment]
> Am I the only one concerned about Qt CI depending on an `X_VCPKG_` feature instead of using CMakes builtin file([GET_RUNTIME_DEPENDENCIES](https://cmake.org/cmake/help/latest/command/file.html#get-runtime-dependencies) [...]) or calling `windeployqt`?

In the vcpkg bug tracker? Yes, you're the only one. :-)

It's just much easier to quickly set a variable than to use file(GRD) correctly. We will probably end up doing just that.

**Comment by Osyotr** [comment]
Hmm did Qt finally gave up on Conan and started using vcpkg? :-)
