### ISSUE TITLE
[dav1d] config for making find_package in cmake environment

### ISSUE THREAD

**Issue by wh1t3lord** [microsoft/vcpkg#29907]
****

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

Would be great to see the Dav1dConfig.cmake or any other file that will provide functionality for find_package in cmake for adding that package in my project. Currently there is no config 

Otherwise provide a clean and sane description how to connect it without config (e.g. without find_package), because I installed it through vcpkg but there is no text at all that will tell me how to connect that package to my library.

Sadly, but I didn't find any information about this problem, and specifically how to connect an installed package without config. 

![image](https://user-images.githubusercontent.com/68504048/221647606-8e170919-26ec-428c-94ce-ba9ee9488d9d.png)

Thanks for attention.

**Comment by wh1t3lord** [comment]
Hello again, but how to use it on windows? 
@Cheney-W 

![image](https://user-images.githubusercontent.com/68504048/225255132-aa778a07-d975-47bc-b19c-d2e66a73047f.png)

**Comment by Cheney-W** [comment]
Sorry, I forgot to add `pkgconf` as a dependency of `dav1d`, I will do it.
Please install `pkgconf` port and test the usage again.
