### ISSUE TITLE
[directx-dxc] update to 2022_12_16

### ISSUE THREAD

**Issue by jsobiers** [microsoft/vcpkg#29921]
Library name: [DirectXShaderCompiler](https://github.com/microsoft/DirectXShaderCompiler)

New version number: 1.7.2212

DX Compiler release for December 2022

**Comment by StarGate-One** [comment]
vcpkg is already at version 2022-12-16 on 2023-01-09 with this [commit](https://github.com/microsoft/vcpkg/commit/f14984af3738e69f197bf0e647a8dca12de92996)

>D:\vcpkg
>->vcpkg search directx-dxc
>directx-dxc              2022-12-16       DirectX Shader Compiler (LLVM/Clang)


You may need to update vcpkg with a `git pull`

**Comment by JonLiu1993** [comment]
Fixed by PR https://github.com/microsoft/vcpkg/pull/28780, please update vcpkg by command `git pull`
