### ISSUE TITLE
[llvm] Build error

### ISSUE THREAD

**Issue by ySion** [microsoft/vcpkg#29927]
C:\vcpkg>vcpkg install llvm[mlir,bolt,lld,lldb,openmp,polly]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    llvm[bolt,clang,compiler-rt,core,default-options,default-targets,disable-assertions,disable-clang-static-analyzer,enable-bindings,enable-terminfo,enable-threads,enable-zlib,lld,lldb,mlir,openmp,polly,target-spirv,target-x86,tools,utils]:x64-windows -> 14.0.6
Detecting compiler hash for triplet x64-windows...
-- Automatically setting HTTP(S)_PROXY environment variables to "127.0.0.1:7890".
Restored 0 package(s) from C:\Users\admin\AppData\Local\vcpkg\archives in 634.1 us. Use --debug to see more details.
Installing 1/1 llvm:x64-windows...
Building llvm[bolt,clang,compiler-rt,core,default-options,default-targets,disable-assertions,disable-clang-static-analyzer,enable-bindings,enable-terminfo,enable-threads,enable-zlib,lld,lldb,mlir,openmp,polly,target-spirv,target-x86,tools,utils]:x64-windows...
-- Note: llvm only supports static library linkage. Building static library.
-- Using cached llvm-llvm-project-llvmorg-14.0.6.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/llvm/src/org-14.0.6-07c830a6c0.clean. Use --editable to skip cleaning for the packages you specify.

C:\vcpkg>vcpkg install llvm[mlir,bolt,openmp]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    llvm[bolt,clang,compiler-rt,core,default-options,default-targets,disable-assertions,disable-clang-static-analyzer,enable-bindings,enable-terminfo,enable-threads,enable-zlib,lld,mlir,openmp,target-spirv,target-x86,tools,utils]:x64-windows -> 14.0.6
Detecting compiler hash for triplet x64-windows...
-- Automatically setting HTTP(S)_PROXY environment variables to "127.0.0.1:7890".
Restored 0 package(s) from C:\Users\admin\AppData\Local\vcpkg\archives in 397 us. Use --debug to see more details.
Installing 1/1 llvm:x64-windows...
Building llvm[bolt,clang,compiler-rt,core,default-options,default-targets,disable-assertions,disable-clang-static-analyzer,enable-bindings,enable-terminfo,enable-threads,enable-zlib,lld,mlir,openmp,target-spirv,target-x86,tools,utils]:x64-windows...
-- Note: llvm only supports static library linkage. Building static library.
-- Using cached llvm-llvm-project-llvmorg-14.0.6.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/llvm/src/org-14.0.6-07c830a6c0.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/llvm-llvm-project-llvmorg-14.0.6.tar.gz
-- Applying patch 0002-fix-install-paths.patch
-- Applying patch 0004-fix-dr-1734.patch
-- Applying patch 0005-fix-tools-path.patch
-- Applying patch 0007-fix-compiler-rt-install-path.patch
-- Applying patch 0009-fix-tools-install-path.patch
-- Applying patch 0010-fix-libffi.patch
-- Applying patch 0011-fix-install-bolt.patch
-- Using source at C:/vcpkg/buildtrees/llvm/src/org-14.0.6-07c830a6c0.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j33
    Working Directory: C:/vcpkg/buildtrees/llvm/x64-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\llvm\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/llvm/portfile.cmake:252 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building llvm:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+llvm
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[llvm]+Build+error
Include '[llvm] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: d5bc0e71e 2023-02-27 (15 hours ago)

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please provide the error log: _C:\vcpkg\buildtrees\llvm\install-x64-windows-dbg-out.log_.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
