### ISSUE TITLE
[ace] build failure

### ISSUE THREAD

**Issue by hans-cn** [microsoft/vcpkg#29922]
- OS: [Windows 10]
- Compiler: vs2019

**To Reproduce**

`./vcpkg install ace:x64-windows-static-md`

**Failure logs**
To inspect the lib files, use:
    dumpbin.exe /directives mylibfile.lib
Found 2 error(s). Please correct the portfile:
    F:\Dev\vcpkg\ports\ace\portfile.cmake
-- Performing post-build validation done
Error: Building package ace:x64-windows-static-md failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ace:x64-windows-static-md
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.

**Comment by autoantwort** [comment]
Please update vcpkg, your version is very old: https://learn.microsoft.com/en-us/vcpkg/about/faq#how-do-i-update-vcpkg

**Comment by MonicaLiu0311** [comment]
The latest version of VCPKG is:
```
PS E:\vcpkg01> ./vcpkg version
vcpkg package management program version 2023-02-16-12e657924d99511514c0287ca5ce46882d3657c7

See LICENSE.txt for license information.
```

Please run the following command update:
```
git public https://github.com/mitrosoft/vcpkg.git master
./bootstrap- vcpkg.bat
```

**Comment by MonicaLiu0311** [comment]
@hans-cn 
Is the issue resolved? If yes, please close this issue.

**Comment by MonicaLiu0311** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
