### ISSUE TITLE
Error Building Zlib x86 - Cannot install libxlsxwriter

### ISSUE THREAD

**Issue by JGITC** [microsoft/vcpkg#29926]
**Describe the bug**
Trying to do a completely fresh install of vcpkg to get the libxlsxwriter header library.  Vcpkg installs correctly and I can do git pull fine as well as update vcpkg.  When I try to install libxlsxwriter I get 'error: building zlib:x86-windows failed with: BUILD_FAILED'.   It seems that it fails when trying to 'Building zlib[core]:x86-windows'.   I also see a command error for the executable  'Command failed: F:/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe -v'

**Environment**
- OS: Windows 10
- Compiler: visual studio 2022

**To Reproduce**
1. ./vcpkg install libxlsxwriter
2. See error
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: F:/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe -v
    Working Directory: F:/vcpkg/buildtrees/zlib/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
also 
     error: building zlib:x86-windows failed with: BUILD_FAILED

**Expected behavior**
I expect to install libxlsxwriter

**Failure logs**
Here is the full error output from the cmd prompt
--
F:\vcpkg>vcpkg install libxlsxwriter
Computing installation plan...
The following packages will be built and installed:
    libxlsxwriter[core]:x86-windows -> 1.1.5
  * zlib[core]:x86-windows -> 1.2.13
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Restored 0 package(s) from C:\Users\jamesg\AppData\Local\vcpkg\archives in 344.2 us. Use --debug to see more details.
Installing 1/2 zlib:x86-windows...
Building zlib[core]:x86-windows...
-- Using cached madler-zlib-v1.2.13.tar.gz.
-- Cleaning sources at F:/vcpkg/buildtrees/zlib/src/v1.2.13-f30d2a168d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/vcpkg/downloads/madler-zlib-v1.2.13.tar.gz
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch 0002-skip-building-examples.patch
-- Applying patch 0003-build-static-or-shared-not-both.patch
-- Applying patch 0004-android-and-mingw-fixes.patch
-- Using source at F:/vcpkg/buildtrees/zlib/src/v1.2.13-f30d2a168d.clean
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: F:/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe -v
    Working Directory: F:/vcpkg/buildtrees/zlib/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      F:\vcpkg\buildtrees\zlib\config-x86-windows-dbg-CMakeCache.txt.log
      F:\vcpkg\buildtrees\zlib\config-x86-windows-rel-CMakeCache.txt.log
      F:\vcpkg\buildtrees\zlib\config-x86-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:248 (vcpkg_execute_required_process)
  ports/zlib/portfile.cmake:18 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)

error: building zlib:x86-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
-(please attached failure logs)

**Additional context**
This seems to be similar to the report Issue #29742

[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/10852185/config-x86-windows-out.log)
[error-logs-x86-windows.txt](https://github.com/microsoft/vcpkg/files/10852197/error-logs-x86-windows.txt)

**Comment by Cheney-W** [comment]
After checked the log you provided, I found two differences between your log and mine:
Yours:
```
1. "-DCMAKE_MAKE_PROGRAM=F:/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe"
2. "-DVCPKG_PLATFORM_TOOLSET=v140"
```
Mine:
```
1. "-DCMAKE_MAKE_PROGRAM=E:/VS2022/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe"
2. "-DVCPKG_PLATFORM_TOOLSET=v143"
```
You said above that your VS is Visual Studio 2022. Do you have the following components installed?
```
1. Visual Studio English Language Pack.
2. Visual Studio Desktop development with C++.
3. Windows 10 SDK or Windows 11 SDK.
```

**Comment by Cheney-W** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
