### ISSUE TITLE
[boost-regex] Build error

### ISSUE THREAD

**Issue by RainbowTaro2022** [microsoft/vcpkg#29937]
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: G:/tools/mingw64/bin/cmake.exe --build . --config Debug --target install -- -v -j7
    Working Directory: G:/Cone/yuzu/externals/vcpkg/buildtrees/boost-regex/x64-windows-dbg
    See logs for more information:
      G:\Cone\yuzu\externals\vcpkg\buildtrees\boost-regex\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  G:/Cone/yuzu/buld/vcpkg_installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  G:/Cone/yuzu/buld/vcpkg_installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  G:/Cone/yuzu/buld/vcpkg_installed/x64-windows/share/boost-build/boost-modular-build.cmake:136 (vcpkg_cmake_install)
  buildtrees/versioning_/versions/boost-regex/49b26b133e2b9eb16d917930b2c697b58eff5530/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:147 (include)

error: building boost-regex:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-regex
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-regex]+Build+error
Include '[boost-regex] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-02-16-12e657924d99511514c0287ca5ce46882d3657c7
    vcpkg-scripts version: 9b22b40c6 2022-08-06 (7 months ago)
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/10855629/install-x64-windows-dbg-out.log)

[files.zip](https://github.com/microsoft/vcpkg/files/10855656/files.zip)

**Comment by dg0yt** [comment]
>  Please ensure you're using the latest port files with git pull and vcpkg update.
> ...
> vcpkg-scripts version: [9b22b40](https://github.com/microsoft/vcpkg/commit/9b22b40c6c61bf0da2d46346dd44a11e90972cc9) 2022-08-06 (7 months ago)

Too old.

**Comment by RainbowTaro2022** [comment]
> > Please ensure you're using the latest port files with git pull and vcpkg update.
> > ...
> > vcpkg-scripts version: [9b22b40](https://github.com/microsoft/vcpkg/commit/9b22b40c6c61bf0da2d46346dd44a11e90972cc9) 2022-08-06 (7 months ago)
> 
> Too old.

I downloaded it directly from the project of vcpkg-tool

**Comment by RainbowTaro2022** [comment]
G:\Cone\vcpkg>vcpkg install folly --allow-unsupported
warning: Starting with the September 2023 release, the default triplet for vcpkg libraries will change from x86-windows to the detected host triplet (x64-windows). To resolve this message, add --triplet x86-windows to keep the same behavior.
Computing installation plan...
warning: folly is only supported on '(windows & x64 & !uwp) | (!windows & (x64 | arm64))', which does not match x86-windows. This usually means that there are known build failures, or runtime problems, when building other platforms. Proceeding anyway due to `--allow-unsupported`.
The following packages will be built and installed:
  * boost-algorithm[core]:x86-windows -> 1.81.0#2
  * boost-align[core]:x86-windows -> 1.81.0#2
  * boost-any[core]:x86-windows -> 1.81.0#2
  * boost-atomic[core]:x86-windows -> 1.81.0#2
  * boost-chrono[core]:x86-windows -> 1.81.0#2
  * boost-container[core]:x86-windows -> 1.81.0#2
  * boost-context[core]:x86-windows -> 1.81.0#2
  * boost-crc[core]:x86-windows -> 1.81.0#2
  * boost-date-time[core]:x86-windows -> 1.81.0#2
  * boost-endian[core]:x86-windows -> 1.81.0#2
  * boost-exception[core]:x86-windows -> 1.81.0#2
  * boost-filesystem[core]:x86-windows -> 1.81.0#2
  * boost-foreach[core]:x86-windows -> 1.81.0#2
  * boost-intrusive[core]:x86-windows -> 1.81.0#2
  * boost-lexical-cast[core]:x86-windows -> 1.81.0#2
  * boost-multi-index[core]:x86-windows -> 1.81.0#2
  * boost-numeric-conversion[core]:x86-windows -> 1.81.0#2
  * boost-phoenix[core]:x86-windows -> 1.81.0#2
  * boost-program-options[core]:x86-windows -> 1.81.0#2
  * boost-proto[core]:x86-windows -> 1.81.0#2
  * boost-range[core]:x86-windows -> 1.81.0#2
  * boost-ratio[core]:x86-windows -> 1.81.0#2
  * boost-rational[core]:x86-windows -> 1.81.0#2
  * boost-regex[core]:x86-windows -> 1.81.0#2
  * boost-serialization[core]:x86-windows -> 1.81.0#2
  * boost-spirit[core]:x86-windows -> 1.81.0#2
  * boost-system[core]:x86-windows -> 1.81.0#2
  * boost-thread[core]:x86-windows -> 1.81.0#2
  * boost-tokenizer[core]:x86-windows -> 1.81.0#2
  * boost-unordered[core]:x86-windows -> 1.81.0#2
    folly[core,zlib]:x86-windows -> 2022.10.31.00#4
  * glog[core]:x86-windows -> 0.6.0#2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
-- Setting "HTTP_PROXY" environment variables to "http://127.0.0.1:31181".
-- Setting "HTTPS_PROXY" environment variables to "http://127.0.0.1:31181".
Restored 0 package(s) from C:\Users\小玉\AppData\Local\vcpkg\archives in 83.3 ms. Use --debug to see more details.
Installing 1/32 boost-exception:x86-windows...
Building boost-exception[core]:x86-windows...
-- Using cached boostorg-exception-boost-1.81.0.tar.gz.
-- Cleaning sources at G:/Cone/vcpkg/buildtrees/boost-exception/src/ost-1.81.0-55a9487305.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source G:/Cone/vcpkg/downloads/boostorg-exception-boost-1.81.0.tar.gz
-- Using source at G:/Cone/vcpkg/buildtrees/boost-exception/src/ost-1.81.0-55a9487305.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x86-windows
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: G:/tools/mingw64/bin/cmake.exe --build . --config Debug --target install -- -v -j7
    Working Directory: G:/Cone/vcpkg/buildtrees/boost-exception/x86-windows-dbg
    See logs for more information:
      G:\Cone\vcpkg\buildtrees\boost-exception\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:140 (vcpkg_cmake_install)
  ports/boost-exception/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:147 (include)

**Comment by RainbowTaro2022** [comment]
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/10909582/install-x86-windows-dbg-out.log)
[boost-modular-build.zip](https://github.com/microsoft/vcpkg/files/10909615/boost-modular-build.zip)

**Comment by RainbowTaro2022** [comment]
G:\Cone\vcpkg>vcpkg install qt --allow-unsupported
warning: Starting with the September 2023 release, the default triplet for vcpkg libraries will change from x86-windows to the detected host triplet (x64-windows). To resolve this message, add --triplet x86-windows to keep the same behavior.
Computing installation plan...
warning: qtwebengine is only supported on '!static & !((x86 | arm) & windows)', which does not match x86-windows. This usually means that there are known build failures, or runtime problems, when building other platforms. Proceeding anyway due to `--allow-unsupported`.
The following packages will be built and installed:
  * angle[core]:x86-windows -> chromium_5414#1
  * assimp[core]:x86-windows -> 5.2.5
  * draco[core]:x86-windows -> 1.5.3
  * egl[core]:x86-windows -> 2022-12-04
  * ffmpeg[avcodec,avdevice,avfilter,avformat,core,swresample,swscale]:x86-windows -> 5.1.2#5
  * freeglut[core]:x86-windows -> 3.4.0
  * glib[core]:x64-windows -> 2.75.3
  * gstreamer[core,plugins-base]:x86-windows -> 1.20.5#1
  * gumbo[core]:x86-windows -> 0.10.1#6
  * gumbo[core]:x64-windows -> 0.10.1#6
  * hunspell[core]:x86-windows -> 1.7.1#2
  * jasper[core,default-features,opengl]:x86-windows -> 4.0.0#1
  * kubazip[core]:x86-windows -> 0.2.4
  * libarchive[bzip2,core,crypto,libxml2,lz4,lzma,zstd]:x64-windows -> 3.6.2
  * libarchive[bzip2,core,crypto,libxml2,lz4,lzma,zstd]:x86-windows -> 3.6.2
  * libwebp[core,libwebpmux,nearlossless,simd,unicode]:x86-windows -> 1.3.0
  * libxml2[core]:x64-windows -> 2.10.3
  * libyaml[core]:x64-windows -> 0.2.5#3
  * libyaml[core]:x86-windows -> 0.2.5#3
  * litehtml[core]:x64-windows -> 0.6.0#2
  * litehtml[core]:x86-windows -> 0.6.0#2
  * minizip[core]:x86-windows -> 1.2.13
  * open62541[amalgamation,core,historizing,openssl]:x86-windows -> 1.2.3#1
  * poly2tri[core]:x86-windows -> 2020-07-21#3
    qt[core,default-features]:x86-windows -> 6.4.2#1
  * qt3d[animation,assimp,core,extras,input,logic,qml,render,rhi]:x86-windows -> 6.4.2
  * qt5compat[big-codecs,codecs,core,default-features,qml,textcodec]:x86-windows -> 6.4.2
  * qtactiveqt[core]:x64-windows -> 6.4.2
  * qtactiveqt[core,qml]:x86-windows -> 6.4.2
  * qtapplicationmanager[core]:x86-windows -> 6.4.2
  * qtapplicationmanager[core]:x64-windows -> 6.4.2
  * qtbase[brotli,concurrent,core,dbus,default-features,doubleconversion,freetype,gui,harfbuzz,icu,jpeg,network,opengl,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,thread,widgets,zstd]:x64-windows -> 6.4.2
  * qtbase[brotli,concurrent,core,dbus,default-features,doubleconversion,freetype,gui,harfbuzz,icu,jpeg,network,opengl,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,thread,widgets,zstd]:x86-windows -> 6.4.2
  * qtcharts[core,designer,qml]:x86-windows -> 6.4.2
  * qtcoap[core]:x86-windows -> 6.4.2
  * qtconnectivity[core]:x86-windows -> 6.4.2
  * qtdatavis3d[core]:x86-windows -> 6.4.2
  * qtdeclarative[core]:x64-windows -> 6.4.2#1
  * qtdeclarative[core]:x86-windows -> 6.4.2#1
  * qtdoc[core]:x86-windows -> 6.4.2
  * qtimageformats[core,default-features,jasper,tiff,webp]:x86-windows -> 6.4.2
  * qtinterfaceframework[core]:x64-windows -> 6.4.2
  * qtinterfaceframework[core]:x86-windows -> 6.4.2
  * qtlanguageserver[core]:x86-windows -> 6.4.2
  * qtlocation[core]:x86-windows -> 6.4.2
  * qtlottie[core,qml]:x86-windows -> 6.4.2
  * qtmqtt[core]:x86-windows -> 6.4.2
  * qtmultimedia[core,widgets]:x64-windows -> 6.4.2
  * qtmultimedia[core,ffmpeg,gstreamer,qml,widgets]:x86-windows -> 6.4.2
  * qtnetworkauth[core]:x86-windows -> 6.4.2
  * qtopcua[core,default-features,gds,ns0idnames,open62541,qml]:x86-windows -> 6.4.2
  * qtpositioning[core,qml]:x86-windows -> 6.4.2
  * qtquick3d[core,default-features]:x64-windows -> 6.4.2
  * qtquick3d[core,default-features]:x86-windows -> 6.4.2
  * qtquicktimeline[core]:x64-windows -> 6.4.2
  * qtquicktimeline[core]:x86-windows -> 6.4.2
  * qtremoteobjects[core]:x64-windows -> 6.4.2
  * qtremoteobjects[core,qml]:x86-windows -> 6.4.2
  * qtscxml[core]:x64-windows -> 6.4.2
  * qtscxml[core,qml]:x86-windows -> 6.4.2
  * qtsensors[core,qml]:x86-windows -> 6.4.2
  * qtserialbus[core,default-features]:x64-windows -> 6.4.2
  * qtserialbus[core,default-features]:x86-windows -> 6.4.2
  * qtserialport[core]:x86-windows -> 6.4.2
  * qtserialport[core]:x64-windows -> 6.4.2
  * qtshadertools[core]:x64-windows -> 6.4.2
  * qtshadertools[core]:x86-windows -> 6.4.2
  * qtsvg[core]:x86-windows -> 6.4.2
  * qttools[assistant,core,designer,linguist,qml]:x86-windows -> 6.4.2#2
  * qttools[assistant,core,designer,linguist]:x64-windows -> 6.4.2#2
  * qttranslations[core,default-features]:x86-windows -> 6.4.2
  * qtvirtualkeyboard[core,default-features,hunspell]:x86-windows -> 6.4.2
  * qtwebchannel[core,qml]:x86-windows -> 6.4.2
  * qtwebengine[core,default-features]:x64-windows -> 6.4.2
  * qtwebengine[core,default-features,geolocation,spellchecker,webchannel]:x86-windows -> 6.4.2
  * qtwebsockets[core,qml]:x86-windows -> 6.4.2
  * qtwebview[core,qml,webengine]:x86-windows -> 6.4.2
  * stb[core]:x86-windows -> 2022-09-09
  * taglib[core]:x64-windows -> 1.13.0#1
  * taglib[core]:x86-windows -> 1.13.0#1
  * vcpkg-get-python-packages[core]:x64-windows -> 2022-06-30
  * vcpkg-tool-lessmsi[core]:x64-windows -> 1.10.0#1
  * vcpkg-tool-nodejs[core]:x64-windows -> 16.18.0#1
  * vcpkg-tool-python2[core]:x64-windows -> 2.7.18#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
-- Setting "HTTP_PROXY" environment variables to "http://127.0.0.1:31181".
-- Setting "HTTPS_PROXY" environment variables to "http://127.0.0.1:31181".
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\小玉\AppData\Local\vcpkg\archives in 5.796 ms. Use --debug to see more details.
Installing 1/84 angle:x86-windows...
Building angle[core]:x86-windows...
-- Using cached google-angle-aa63ea230e0c507e7b4b164a30e502fb17168c17.tar.gz.
-- Extracting source G:/Cone/vcpkg/downloads/google-angle-aa63ea230e0c507e7b4b164a30e502fb17168c17.tar.gz
-- Applying patch 001-fix-uwp.patch
-- Applying patch 002-fix-builder-error.patch
-- Applying patch 003-fix-mingw.patch
-- Using source at G:/Cone/vcpkg/buildtrees/angle/src/fb17168c17-081a7ef021.clean
-- Downloading https://github.com/WebKit/WebKit/raw/bb1da00b9ba878d228a5e9834a0767dbca2fee43/Source/ThirdParty/ANGLE/gni-to-cmake.py -> gni-to-cmake.py...
-- Downloading https://github.com/WebKit/WebKit/raw/bb1da00b9ba878d228a5e9834a0767dbca2fee43/Source/ThirdParty/ANGLE/include/CMakeLists.txt -> include_CMakeLists.txt...
-- Downloading https://github.com/WebKit/WebKit/raw/bb1da00b9ba878d228a5e9834a0767dbca2fee43/Source/cmake/WebKitCompilerFlags.cmake -> WebKitCompilerFlags.cmake...
-- Downloading https://github.com/WebKit/WebKit/raw/bb1da00b9ba878d228a5e9834a0767dbca2fee43/Source/cmake/WebKitMacros.cmake -> WebKitMacros.cmake...
-- Fetching https://chromium.googlesource.com/chromium/src/third_party/zlib 44d9b490c721abdb923d5c6c23ac211e45ffb1a5...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files/Git/cmd/git.exe" fetch https://chromium.googlesource.com/chromium/src/third_party/zlib 44d9b490c721abdb923d5c6c23ac211e45ffb1a5 --depth 1 -n
    Working Directory: G:/Cone/vcpkg/downloads/git-tmp
    Error code: 128
    See logs for more information:
      G:\Cone\vcpkg\buildtrees\angle\git-fetch-x86-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_git.cmake:86 (vcpkg_execute_required_process)
  ports/angle/portfile.cmake:138 (vcpkg_from_git)
  ports/angle/portfile.cmake:147 (checkout_in_path)
  scripts/ports.cmake:147 (include)


error: building angle:x86-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+angle
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[angle]+Build+error
Include '[angle] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-03-01-538539c4e364dd6f14f5e36f6704144254845159
    vcpkg-scripts version: dd1b57240 2023-03-09 (3 hours ago)
