### ISSUE TITLE
[paho-mqttpp3] Linux ODR violation

### ISSUE THREAD

**Issue by tripleslash** [microsoft/vcpkg#29931]
**Host Environment**

- OS: Ubuntu 22.04
- Compiler: GCC 12.2.1

**To Reproduce**

`./vcpkg install paho-mqtt paho-mqttpp3 libuuid`

**Failure logs**

```
/vcpkg/buildtrees/paho-mqtt/src/adf3e3a08f-6410ea1ad2.clean/src/WebSocket.c:107: multiple definition of `uuid_generate'; ../../vcpkg_installed/x64-linux/debug/lib/libuuid.a(gen_uuid.c.o):/vcpkg/buildtrees/libuuid/src/77488caccc-f5e8f5589c.clean/gen_uuid.c:590: first defined here
```

**More info:**

It appears that Paho MQTT redefines uuid_generate from libuuid when it doesn't detect that libuuid was used when building paho. The problem is that paho now violates ODR when libuuid is required by another library in the program.

Possible fix: Add portfile option to let paho know about libuuid or add patch to fix libuuid detection

**Comment by jimwang118** [comment]
We haven't been able to repro this. My running results are as follows, please check.
![image](https://user-images.githubusercontent.com/122244446/222106809-d237e82d-4708-4513-9b11-c9c3957c655c.png)

**Comment by tripleslash** [comment]
Did you try to link the resulting binary? I got the error indirectly from using paho-mqttpp3 together with drogon (and drogon has a FindUUID.cmake which adds the uuid dependency)

**Comment by jimwang118** [comment]
I added the code according to the method you said, and the running results are as follows.

**Environment**

- ubuntu 22.04
- gcc 9.5.0

**Code 1**
```
#include <mqtt/async_client.h>
#include <uuid/uuid.h>

int main()
{
    mqtt::async_client client{ "", "" };
    uuid_t id;
    uuid_generate(id);
}
```
**Result**
```
:/app/test$ cmake -DCMAKE_TOOLCHAIN_FILE=/app/vcpkg/scripts/buildsystems/vcpkg.cmake CMakeLists.txt
-- Configuring done
-- Generating done
-- Build files have been written to: /app/test
:/app/test$ cmake --build .
Consolidate compiler generated dependencies of target mqt5
[ 50%] Building CXX object CMakeFiles/mqt5.dir/testmtqq3.cpp.o
[100%] Linking CXX executable mqt5
/usr/bin/ld: CMakeFiles/mqt5.dir/testmtqq3.cpp.o: in function `main':
testmtqq3.cpp:(.text+0x95): undefined reference to `mqtt::async_client::async_client(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, mqtt::iclient_persistence*)'
/usr/bin/ld: testmtqq3.cpp:(.text+0xf1): undefined reference to `mqtt::async_client::~async_client()'
/usr/bin/ld: testmtqq3.cpp:(.text+0x181): undefined reference to `mqtt::async_client::~async_client()'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/mqt5.dir/build.make:104: mqt5] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/mqt5.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
```
This means that class `async_client` does not define a destructor.
**Code 2**
```
#include <mqtt/async_client.h>
#include <uuid/uuid.h>

int main()
{
    //mqtt::async_client client{ "", "" };
    uuid_t id;
    uuid_generate(id);
}
```
**Result**
```
:/app/test$ vi testmtqq3.cpp
:/app/test$ cmake -DCMAKE_TOOLCHAIN_FILE=/app/vcpkg/scripts/buildsystems/vcpkg.cmake CMakeLists.txt
-- Configuring done
-- Generating done
-- Build files have been written to: /app/test
:/app/test$ cmake --build .
Consolidate compiler generated dependencies of target mqt5
[ 50%] Building CXX object CMakeFiles/mqt5.dir/testmtqq3.cpp.o
[100%] Linking CXX executable mqt5
[100%] Built target mqt5
:/app/test$: 
```

**Comment by tripleslash** [comment]
@jimwang118 
This here is specifically the location where the ODR violation happens:

https://github.com/eclipse/paho.mqtt.c/blob/master/src/WebSocket.c#L106

In vcpkg the package is built without #define LIBUUID=1 this means paho falls back to its own symbol. When paho is built statically this way it means there is now the uuid_generate and uuid_unparse C function defined in paho-mqtt3-static as well as libuuid. To fix this I suggest editing the portfile to define -DLIBUUID when building paho or patching uuid_generate/uuid_unparse in paho-mqtt-c to have static linkage (add static keyword in https://github.com/eclipse/paho.mqtt.c/blob/master/src/WebSocket.c#L106 and https://github.com/eclipse/paho.mqtt.c/blob/master/src/WebSocket.c#L124)
