### ISSUE TITLE
Azure pipelines are stuck

### ISSUE THREAD

**Issue by braindigitalis** [microsoft/vcpkg#29932]
**Describe the bug**
It seems the x64_linux azure pipelines are not starting for any PRs over the past ~12 hours. There are a bunch of PRs stuck in waiting to start state, there is nothing us as developers can do to nudge this process.

**Environment**
- OS: GitHub Actions/Azure Pipelines

**To Reproduce**
1. Submit a PR

**Expected behavior**
PR Completes eventually

**Additional context**
Noticed this with my own PR and decided to go back to the list and check, they're all hung. Can someone with the power please give it a gentle kick in the shin? 😄

**Comment by FrankXie05** [comment]
@braindigitalis Thanks for posting this issue, I see that your PR runs on `Linux` from two hours ago, while others start from seven hours. But now that it works normally, I may be blocked due to performance reasons. 🤔 Sorry, I can't view the error. :)

**Comment by FrankXie05** [comment]
I can restart a pipline for a PR. If you need Ping me. :)
