### ISSUE TITLE
"remove feature" feature

### ISSUE THREAD

**Issue by Tryum** [microsoft/vcpkg#2994]
The idea is to provide features that will remove some dependencies :  

To keep the default package building with it's default dependencies, but provide a way to disable some dependencies (if for instance they're not building on a specific platform).

**Comment by Cheney-W** [comment]
@Tryum , thanks for reporting this issue.
This feature has be implemented, you could use it by modifying the control file of port, see [here ](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/control-files.md#build-depends)for details. Thank you!
