### ISSUE TITLE
[restbed] Unable to configure simple project

### ISSUE THREAD

**Issue by matthewcpp** [microsoft/vcpkg#29940]
I have tried searching for other restbed related issues as well as across other sites with no luck.  The library seemingly builds fine, however I am not able to configure a simple project using restbed on both my mac and windows development machines.

CMake configuration fails at the `find_package(restbed CONFIG REQUIRED)` line.  From what i could tell this should be the correct way to find the package.

I have tried searching though the restbed folder in the vcpkg `packages` folder for some hint at what target to use with no luck.

I have attached a simple project which just tries to build the example in the main readme from the restbed repo as well as the build output from my windows machine.

I apologize if i am missing something obvious here.

vcpkg version:
vcpkg package management program version 2023-02-16-12e657924d99511514c0287ca5ce46882d3657c7

Reproduction Steps:
1. Download and extract the attached zip file containing a minimal project
2. Modify the line in CMakeLists.txt to set the toolchain file to the relevant path on your system
3. Attempt to configure the project and observe the error.

[restbed.zip](https://github.com/microsoft/vcpkg/files/10857166/restbed.zip)
[build_output.txt](https://github.com/microsoft/vcpkg/files/10857168/build_output.txt)
[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/10857412/CMakeOutput.log)

**Comment by gituliar** [comment]
Not sure if the issues are related, but I still get this

```
  Could not find a package configuration file provided by "restbed" with any
  of the following names:

    restbedConfig.cmake
    restbed-config.cmake

  Add the installation prefix of "restbed" to CMAKE_PREFIX_PATH or set
  "restbed_DIR" to a directory containing one of the above files.  If
  "restbed" provides a separate development package or SDK, be sure it has
  been installed.
```

With `cmake -LAH` I see

```
// The directory containing a CMake configuration file for restbed.
restbed_DIR:PATH=restbed_DIR-NOTFOUND
```

Could you advice, please ?

**Comment by matthewcpp** [comment]
@gituliar after pulling in the change, i was able to get the cmake configure step to work on my macOS machine using the following CMake code:

```
find_package(unofficial-restbed CONFIG REQUIRED)
target_link_libraries(restbed-test PRIVATE unofficial::restbed::restbed-static)
```

**Comment by dg0yt** [comment]
@gituliar Please note that upstream restbed doesn't offer cmake config (`find_package(restbed CONFIG)`).
In such cases, vcpkg may add config in the `unoffcial` namespace (`find_package(unofficial-restbed CONFIG)`).

vcpkg also doesn't modify upstream target names. If you need to cover both static and shared linkage, you would need to use:
~~~cmake
find_package(unofficial-restbed CONFIG REQUIRED)
target_link_libraries(main PRIVATE $<IF:$<TARGET_EXISTS:unofficial::restbed::restbed-static>,unofficial::restbed::restbed-static,unofficial::restbed::restbed-shared>)
~~~

**Comment by matthewcpp** [comment]
@dg0yt thank you for the detailed explanation. I wasn't sure exactly why I needed to call find package the way I did, but your explanation makes it very clear.

I appreciate all the time and work that has gone into this issue!

**Comment by gituliar** [comment]
@matthewcpp @dg0yt thanks for the feedback. Eventually, I ended with what usually works when package provides provides no CMake config:

```
find_path(RESTBED_INCLUDE_DIRS "restbed")
find_library(RESTBED_LIBRARY NAMES "librestbed.a" "restbed.lib")

target_include_directories(main PRIVATE ${RESTBED_INCLUDE_DIRS})
target_link_libraries(main PRIVATE ${RESTBED_LIBRARY})
```
