### ISSUE TITLE
[openssl] build failure on Android

### ISSUE THREAD

**Issue by AenBleidd** [microsoft/vcpkg#29947]
Before 9ccc64ca98b320404d059df4349220bd2c1b4a46 I was able to build OpenSSL for Android with no issues: https://github.com/BOINC/boinc-apps/actions/runs/4288278917/jobs/7470102534
Now it's failing with the next error:
```
Configuring OpenSSL version 3.0.8 for target android-arm
Using os-specific seed configuration
+ /usr/bin/perl /home/runner/work/boinc-apps/boinc-apps/vcpkg/buildtrees/openssl/src/nssl-3.0.8-d9622695f9.clean/Configure android-arm enable-static-engine enable-capieng no-ssl3 no-weak-ssl-ciphers no-tests no-shared no-module --openssldir=/etc/ssl --libdir=lib --prefix=/home/runner/work/boinc-apps/boinc-apps/build/boinc-autodock-vina/arm-android-static/vcpkg_installed/arm-android-static

Failure!  build file wasn't produced.
Please read INSTALL.md and associated NOTES-* files.  You may also have to
look over your available compiler tool chain or change your configuration.

no NDK arm-linux-androideabi-gcc on $PATH at (eval 10) line 142.
```
Ref: https://github.com/BOINC/boinc-apps/actions/runs/4302690901/jobs/7501498224

**Comment by AenBleidd** [comment]
@dg0yt, could be interesting for you since this was your change https://github.com/microsoft/vcpkg/pull/27261

**Comment by dg0yt** [comment]
https://github.com/openssl/openssl/blob/master/NOTES-ANDROID.md#configuration
IIUC we need to adjust `PATH` and `ANDROID_NDK_ROOT` in addition to common autotools environment.
(This could also be the workaround until fixed.)

**Comment by AenBleidd** [comment]
@dg0yt,l I can try that, but I have other thing that worries me more:
script tries to locate `arm-linux-androideabi-gcc` but I set to use `armv7a-linux-androideabi21-clang` instead (because it's smth that is now used to build Android stuff on the latest NDKs).
So is there really an issue with the PATH not set or it's looking for a wrong tool?

**Comment by dg0yt** [comment]
I'm looking into it, but I can't say so much right now. Basically, it is meant to use the same tools and flags as CMake does (i.e. consistent with what other ports do). But openssl has it is own ideas.

**Comment by AenBleidd** [comment]
Ok, thank you. This is not very urgent for me, so please take your time to look into this issue and fix it properly.
If you need any help with it (testing, investigating, etc), just let me know.

**Comment by ahmedyarub** [comment]
@dg0yt yesterday's PR broke building OpenSSL at least for Android and Emscripten for me. I did configure the env variables correctly but it still fails. It looks like the env variables are not reaching OpenSSL build scripts anymore. Once I checkout the previous version it builds without any problem.

**Comment by dg0yt** [comment]
FTR this isn't "yesterday's" PR but started in October, with this comment: "This change would benefit from independent testing wrt to all the target triplet particularities."
I tried to reach out to others in the context of openssl issues, but the response was minimal.

**Comment by dg0yt** [comment]
@ahmedyarub Could you open a separate issue for emscripten, with clear information and logs?

**Comment by dg0yt** [comment]
Quick test with NDK r23c.

- `ANDROID_NDK_ROOT`: 
  vcpkg doesn't deal with variable. `scripts/toolchains/android.cmake` is built on (env) `ANDROID_NDK_HOME`. This (CMake) variable is set in CMake project context but not yet available via `vcpkg_cmake_get_vars`.
  Not directly related to the *reported* issue, but an issue for port openssl anyways. Workaround: set env ANDROID_NDK_ROOT before running vcpkg.
- C compiler:
  - from CMake in `buildtrees/openssl/cmake-vars-arm-android-dbg.cmake.log`:
    ~~~CMake
    set(VCPKG_DETECTED_CMAKE_C_COMPILER "<ANDROID_NDK_HOME>/toolchains/llvm/prebuilt/linux-x86_64/bin/clang")
    ~~~
  - This full path is passed via environment variable `CC`, and CFLAGS for debug are set to:
    ~~~
    -g -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mthumb -mfpu=vfpv3-d16 -Wformat -Werror=format-security -fPIC -fno-limit-debug-info
    ~~~
  - No Makefile is generated due to error `no NDK arm-linux-androideabi-gcc on $PATH at (eval 12) line 142.`
  - Even with `<ANDROID_NDK_HOME>/toolchains/llvm/prebuilt/linux-x86_64/bin` added to path, `Configure` fails.
    In fact, there is no such `arm-linux-androideabi-gcc` in this whole NDK, only clang with various wrappers under alternative names.

**Comment by dg0yt** [comment]
After adding `<ANDROID_NDK_HOME>/toolchains/llvm/prebuilt/linux-x86_64/bin` to the `PATH`, openssl:arm-android builds with these makefile vars:
~~~
CROSS_COMPILE=
CC=$(CROSS_COMPILE)armv7a-linux-androideabi31-clang
~~~
Note the `31`.

**Comment by dg0yt** [comment]
FTR #29947 is ready for testing.
Makefile for arm-neon-android release has now:
~~~
CROSS_COMPILE...
CC=$(CROSS_COMPILE)/<NDK_HOME>/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
CPPFLAGS=--target=armv7-none-linux-androideabi21 -DANDROID -D_FORTIFY_SOURCE=2 -march=armv7-a -DNDEBUG
CFLAGS=-g -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mthumb -Wformat -Werror=format-security -fPIC "--sysroot=<NDK_HOME>/toolchains/llvm/prebuilt/linux-x86_64/sysroot" -O3
LDFLAGS= -avoid-version -L<vcpkg-installed>/arm-neon-android/lib --target=armv7-none-linux-androideabi21 -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments  "--sysroot=<NDK_HOME>/toolchains/llvm/prebuilt/linux-x86_64/sysroot" -Wl,--gc-sections
~~~

**Comment by AenBleidd** [comment]
#29966 successfully tested for Android, Linux, OSX and Windows.
Everything looks fine. 
Thank you for the fix, @dg0yt!
