### ISSUE TITLE
[openssl] now requires pwsh on mingw/linux for no good reason

### ISSUE THREAD

**Issue by flichtenheld** [microsoft/vcpkg#29948]
**Host Environment**

- OS: Ubuntu 20.04
- Compiler: x86_64-w64-mingw32-g++ (GCC) 9.3-win32 20200320

**To Reproduce**

`./vcpkg install openssl --triplet=x64-mingw-dynamic`

**Failure logs**

``` 
CMake Error at scripts/cmake/vcpkg_copy_tool_dependencies.cmake:31 (message):
  Could not find PowerShell Core; please open an issue to report this.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_copy_tools.cmake:48 (vcpkg_copy_tool_dependencies)
  ports/openssl/unix/portfile.cmake:118 (vcpkg_copy_tools)
  ports/openssl/portfile.cmake:60 (include)
  scripts/ports.cmake:147 (include)
```
This worked fine until 9ccc64ca98b320404d059df4349220bd2c1b4a46

**Additional context**

Probably we shouldn't actually install the tool when cross-compiling? It is unusable anyway, right?

**Comment by dg0yt** [comment]
For the record, the powershell script for app-local deployment of DLLs works also on Linux:
~~~
$ ls packages/openssl_x64-mingw-dynamic/tools/openssl/
c_rehash  libcrypto-3-x64.dll  libssl-3-x64.dll  openssl.exe
$ wine packages/openssl_x64-mingw-dynamic/tools/openssl/openssl.exe version
OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)
~~~

**Comment by flichtenheld** [comment]
Okay, yes. I meant "natively unusable". You can run it with emulation or virtualization. Would still be nice to be able to run the build without having to install a 3rd-party dependency outside of vcpkg.

**Comment by dg0yt** [comment]
Well, powershell comes from the same vendor as vcpkg, so it is not so much 3rd-party.
I'm currently preparing another OpenSSL PR for Android fixes. I could try to integrate the tools feature, however I don't see a switch to turn it off during the build.
