### ISSUE TITLE
PCL installation fails post-build validation

### ISSUE THREAD

**Issue by claudiofantacci** [Microsoft/vcpkg#2995]
OS Name: `Microsoft Windows 10 Pro`
Version: `10.0.16299 Build 16299`
System Type: `x64-based PC`

Package: `pcl:x64-windows`
Vcpkg version: `0.0.105-2018-03-08-965e99cf268b32cc32e0599d99e6c9a1991e95f4`

Issuing `vcpkg install pcl[qt,tools,cuda] --head`

the following error occurs:
```
/debug/share should not exist. Please reorganize any important files, then use
    file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/share)
Found 1 error(s). Please correct the portfile:
    C:\Users\<user>\vcpkg\ports\pcl\portfile.cmake
-- Performing post-build validation done
Error: Building package pcl:x64-windows failed with: POST_BUILD_CHECKS_FAILED
```

Trying to fix it.

**Comment by claudiofantacci** [comment]
[This change](https://github.com/Microsoft/vcpkg/commit/f625230452b7b37adeb60c45622c817dfb68c362#diff-d5369056a1605db1524659ef89bc907aL73) is probably the cause of error, as correctly reported by the error log.

**Comment by ras0219-msft** [comment]
Thanks again!
