### ISSUE TITLE
implemnt package "Nlohmann Json"

### ISSUE THREAD

**Issue by jcat18** [microsoft/vcpkg#29959]
Please implemet package "Nlohman Json" in VCPKG

**Comment by FrankXie05** [comment]
@jcat18 
Do you mean port `nlohmann-json`? It has been implemented in vcpkg.
https://github.com/microsoft/vcpkg/tree/master/ports/nlohmann-json

 If not, can you provide details of this port (Link, official website?)

**Comment by FrankXie05** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please Ping me and I will reopen!
