### ISSUE TITLE
[ffmpeg] Build error

### ISSUE THREAD

**Issue by xengine-qyt** [microsoft/vcpkg#29963]
vcpkg.exe install ffmpeg:x86-windows it's ok
but ffmpeg[all]:x86-windows is failure

**Host Environment**

- OS: Windows10 x64
- Compiler: vs2022 

`

```
D:\vcpkg>vcpkg.exe install ffmpeg[all]:x86-windows
Computing installation plan...
The following packages will be built and installed:
  * aom[core]:x86-windows -> 3.5.0#1
  * brotli[core]:x86-windows -> 1.0.9#5
  * bzip2[core,tool]:x86-windows -> 1.0.8#3
  * dirent[core]:x86-windows -> 1.23.2#1
  * egl-registry[core]:x86-windows -> 2022-09-20
  * expat[core]:x86-windows -> 2.5.0#3
    ffmpeg[all,amf,aom,ass,avcodec,avdevice,avfilter,avformat,bzip2,core,fontconfig,freetype,fribidi,iconv,ilbc,lzma,modplug,mp3lame,nvcodec,opencl,opengl,openh264,openjpeg,openmpt,opus,qsv,sdl2,snappy,soxr,speex,srt,ssh,swresample,swscale,tesseract,theora,vorbis,vpx,webp,xml2,zlib]:x86-windows -> 5.1.2#4
  * ffnvcodec[core]:x86-windows -> 11.1.5.0#1
  * fontconfig[core]:x86-windows -> 2.14.1#1
  * freetype[brotli,bzip2,core,png,zlib]:x86-windows -> 2.12.1#3
  * fribidi[core]:x64-windows -> 1.0.12
  * fribidi[core]:x86-windows -> 1.0.12
  * getopt[core]:x86-windows -> 0#2
  * getopt-win32[core]:x86-windows -> 0.1#7
  * gettext[core]:x86-windows -> 0.21.1
  * giflib[core]:x86-windows -> 5.2.1#3
  * gperf[core]:x64-windows -> 3.1#4
  * harfbuzz[core]:x86-windows -> 6.0.0#1
  * leptonica[core]:x86-windows -> 1.83.1
  * libarchive[bzip2,core,crypto,libxml2,lz4,lzma,zstd]:x86-windows -> 3.6.2
  * libass[core]:x86-windows -> 0.16.0
  * libilbc[core]:x86-windows -> 3.0.4
  * libjpeg-turbo[core]:x86-windows -> 2.1.5.1
  * liblzma[core]:x86-windows -> 5.4.1#1
  * libmodplug[core]:x86-windows -> 0.8.9.0#10
  * libogg[core]:x86-windows -> 1.3.5#1
  * libopenmpt[core]:x86-windows -> 0.6.7
  * libpng[core]:x86-windows -> 1.6.39
  * libsrt[core]:x86-windows -> 1.5.0#2
  * libssh[core,crypto,mbedtls]:x86-windows -> 0.10.4+20221123#3
  * libtheora[core]:x86-windows -> 1.2.0alpha1-20170719#6
  * libvorbis[core]:x86-windows -> 1.3.7#2
  * libvpx[core]:x86-windows -> 1.12.0
  * libwebp[core,libwebpmux,nearlossless,simd,unicode]:x86-windows -> 1.3.0
  * libxml2[core]:x86-windows -> 2.10.3
  * mbedtls[core,pthreads]:x86-windows -> 2.28.1
  * mfx-dispatch[core]:x86-windows -> 1.35.1#1
  * mp3lame[core]:x86-windows -> 3.100#10
  * mpg123[core]:x86-windows -> 1.31.2
  * opencl[core]:x86-windows -> v2022.09.30
  * opengl[core]:x86-windows -> 2022-12-04#1
  * opengl-registry[core]:x86-windows -> 2022-09-29
  * openh264[core]:x86-windows -> 2021-03-16#3
  * openjpeg[core]:x86-windows -> 2.5.0
  * opus[core]:x86-windows -> 1.3.1#9
  * pthread[core]:x86-windows -> 3.0.0#1
  * pthreads[core]:x86-windows -> 3.0.0#13
  * snappy[core]:x86-windows -> 1.1.9#5
  * soxr[core]:x86-windows -> 0.1.3#7
  * speex[core]:x86-windows -> 1.2.1#1
  * tesseract[core]:x86-windows -> 5.3.0
  * tiff[core,jpeg,lzma,zip]:x86-windows -> 4.5.0#2
  * yasm[core,tools]:x64-windows -> 1.3.0#5
  * yasm-tool-helper[core]:x86-windows -> 2020-03-11#1
  * zstd[core]:x86-windows -> 1.5.4
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
-- Automatically setting HTTP(S)_PROXY environment variables to "127.0.0.1:7890".
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\48617\AppData\Local\vcpkg\archives in 8.888 ms. Use --debug to see more details.
Installing 1/55 aom:x86-windows...
Building aom[core]:x86-windows...
-- Using cached D:/vcpkg/downloads/aom-9a83c6a5a55c176adbce740e47d3512edfc9ae71.tar.gz
-- Cleaning sources at D:/vcpkg/buildtrees/aom/src/2edfc9ae71-336de0ab24.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/aom-9a83c6a5a55c176adbce740e47d3512edfc9ae71.tar.gz
-- Applying patch aom-rename-static.diff
-- Applying patch aom-uninitialized-pointer.diff
-- Applying patch aom-install.diff
-- Using source at D:/vcpkg/buildtrees/aom/src/2edfc9ae71-336de0ab24.clean
-- Found external ninja('1.11.0').
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: D:/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe --build . --config Release --target install -- -v -j13
    Working Directory: D:/vcpkg/buildtrees/aom/x86-windows-rel
    See logs for more information:
      D:\vcpkg\buildtrees\aom\install-x86-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/aom/portfile.cmake:40 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)


error: building aom:x86-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+aom
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[aom]+Build+error
Include '[aom] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-02-16-12e657924d99511514c0287ca5ce46882d3657c7
    vcpkg-scripts version: 8e82d67b7 2023-03-01 (4 hours ago)

Please use the prefilled template from D:\vcpkg\installed\vcpkg\issue_body.md when reporting your issue

`
```

**Comment by Adela0814** [comment]
@xengine-qyt  Please provide the failure log.` D:\vcpkg\buildtrees\aom\install-x86-windows-rel-out.log`

**Comment by xengine-qyt** [comment]
Compiler running out of heap space.....
cpu:i5 10500 
memory ddr4 16GB..

`
\buildtrees\aom\x86-windows-rel -ID:\vcpkg\buildtrees\aom\src\2edfc9ae71-336de0ab24.clean\apps -ID:\vcpkg\buildtrees\aom\src\2edfc9ae71-336de0ab24.clean\common -ID:\vcpkg\buildtrees\aom\src\2edfc9ae71-336de0ab24.clean\examples -ID:\vcpkg\buildtrees\aom\src\2edfc9ae71-336de0ab24.clean\stats -ID:\vcpkg\buildtrees\aom\src\2edfc9ae71-336de0ab24.clean\third_party\libyuv\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /MD /O2 /Oi /Gy /DNDEBUG /Z7  -D_WIN32_WINNT=0x0601 -DNOMINMAX /W3 /wd4996 /wd4703 /showIncludes /FoCMakeFiles\aom_av1_common_sse4_intrinsics.dir\av1\common\x86\cdef_block_sse4.c.obj /FdCMakeFiles\aom_av1_common_sse4_intrinsics.dir\ /FS -c D:\vcpkg\buildtrees\aom\src\2edfc9ae71-336de0ab24.clean\av1\common\x86\cdef_block_sse4.c
D:\vcpkg\buildtrees\aom\src\2edfc9ae71-336de0ab24.clean\aom_dsp\simd\v64_intrinsics_c.h(782) : fatal error C1002: 在第 2 遍中编译器的堆空间不足
D:\vcpkg\buildtrees\aom\src\2edfc9ae71-336de0ab24.clean\av1\common\cdef_block_simd.h(269) : fatal error C1002: 在第 2 遍中编译器的堆空间不足
[349/402] C:\PROGRA~1\MICROS~2\2022\COMMUN~1\VC\Tools\MSVC\1435~1.322\bin\Hostx64\x86\cl.exe    -ID:\vcpkg\buildtrees\aom\src\2edfc9ae71-336de0ab24.clean -ID:\vcpkg\buildtrees\aom\x86-windows-rel -ID:\vcpkg\buildtrees\aom\src\2edfc9ae71-336de0ab24.clean\apps -ID:\vcpkg\buildtrees\aom\src\2edfc9ae71-336de0ab24.clean\common -ID:\vcpkg\buildtrees\aom\src\2edfc9ae71-336de0ab24.clean\examples -ID:\vcpkg\buildtrees\aom\src\2edfc9ae71-336de0ab24.clean\stats -ID:\vcpkg\buildtrees\aom\src\2edfc9ae71-336de0ab24.clean\third_party\libyuv\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /MD /O2 /Oi /Gy /DNDEBUG /Z7  -D_WIN32_WINNT=0x0601 -DNOMINMAX /W3 /wd4996 /wd4703 /arch:AVX2 /showIncludes /FoCMakeFiles\aom_av1_common_avx2_intrinsics.dir\av1\common\x86\cdef_block_avx2.c.obj /FdCMakeFiles\aom_av1_common_avx2_intrinsics.dir\ /FS -c D:\vcpkg\buildtrees\aom\src\2edfc9ae71-336de0ab24.clean\av1\common\x86\cdef_block_avx2.c
FAILED: CMakeFiles/aom_av1_common_avx2_intrinsics.dir/av1/common/x86/cdef_block_avx2.c.obj 
C:\PROGRA~1\MICROS~2\2022\COMMUN~1\VC\Tools\MSVC\1435~1.322\bin\Hostx64\x86\cl.exe    -ID:\vcpkg\buildtrees\aom\src\2edfc9ae71-336de0ab24.clean -ID:\vcpkg\buildtrees\aom\x86-windows-rel -ID:\vcpkg\buildtrees\aom\src\2edfc9ae71-336de0ab24.clean\apps -ID:\vcpkg\buildtrees\aom\src\2edfc9ae71-336de0ab24.clean\common -ID:\vcpkg\buildtrees\aom\src\2edfc9ae71-336de0ab24.clean\examples -ID:\vcpkg\buildtrees\aom\src\2edfc9ae71-336de0ab24.clean\stats -ID:\vcpkg\buildtrees\aom\src\2edfc9ae71-336de0ab24.clean\third_party\libyuv\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /MD /O2 /Oi /Gy /DNDEBUG /Z7  -D_WIN32_WINNT=0x0601 -DNOMINMAX /W3 /wd4996 /wd4703 /arch:AVX2 /showIncludes /FoCMakeFiles\aom_av1_common_avx2_intrinsics.dir\av1\common\x86\cdef_block_avx2.c.obj /FdCMakeFiles\aom_av1_common_avx2_intrinsics.dir\ /FS -c D:\vcpkg\buildtrees\aom\src\2edfc9ae71-336de0ab24.clean\av1\common\x86\cdef_block_avx2.c
D:\vcpkg\buildtrees\aom\src\2edfc9ae71-336de0ab24.clean\aom_dsp\simd\v64_intrinsics_c.h(754) : fatal error C1002: 在第 2 遍中编译器的堆空间不足
D:\vcpkg\buildtrees\aom\src\2edfc9ae71-336de0ab24.clean\av1\common\cdef_block_simd.h(269) : fatal error C1002: 在第 2 遍中编译器的堆空间不足
ninja: build stopped: subcommand failed.
`

**Comment by Adela0814** [comment]
It looks like you don't have enough disk space.

**Comment by xengine-qyt** [comment]
> It looks like you don't have enough disk space.

I have 32GB disk space. error message is compiler running out of heap space

**Comment by xengine-qyt** [comment]
32G Memory and 13700KF  40GB Disk Space,.
ffmpeg build ok ,ffmpeg[all] build error
