### ISSUE TITLE
[boost-contract] Build error

### ISSUE THREAD

**Issue by navyverma** [microsoft/vcpkg#29968]
**Host Environment**

- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**

`./vcpkg install xxxx`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Cheney-W** [comment]
In order to investigate this issue, could you please provide me with following info:
1. The logs saved in `vcpkg\buildtrees\boost-contract folder.
2. The version of your VCPKG and Visual Studio.

**Comment by Cheney-W** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
