### ISSUE TITLE
False

### ISSUE THREAD

**Issue by NicWoo90** [microsoft/vcpkg#29971]
fixed by call `vm.version()` after launching the vm.

_Originally posted by @Eskibear in https://github.com/microsoft/java-debug/issues/23#issuecomment-330120276_

**Comment by LilyWangLL** [comment]
Could you please provide the more information about this issue? Which port is related with the following message?
> fixed by call `vm.version()` after launching the vm.

**Comment by Pospelove** [comment]
![image](https://user-images.githubusercontent.com/37947786/222822992-119ab313-c699-41ca-ba36-782536427710.png)

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
