### ISSUE TITLE
vcpkg/vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static

### ISSUE THREAD

**Issue by QYH2MMT4EVER** [microsoft/vcpkg#29985]
Please create a discussion in https://github.com/microsoft/vcpkg/discussions/new instead.
**I inputted “vcpkg/vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static
” in git bash ，console cast some problems as follow：** 

-- Building C:/Users/1/vcpkg/buildtrees/libvpx/x64-windows-static/vpx.vcxproj for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: msbuild C:/Users/1/vcpkg/buildtrees/libvpx/x64-windows-static/vpx.vcxproj /p:Configuration=Release /p:UseEnv=True /t:Rebuild /p:Platform=x64 /p:PlatformToolset=v143 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.22621.0 /p:VcpkgManifestInstall=false /p:VcpkgManifestEnabled=false /m /p:WholeProgramOptimization=false /p:VcpkgEnabled=false
    Working Directory: C:/Users/1/vcpkg/buildtrees/libvpx/x64-windows-static-rel
    Error code: 1
    See logs for more information:
      **C:\Users\1\vcpkg\buildtrees\libvpx\build-x64-windows-static-rel-out.log**

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:65 (vcpkg_execute_required_process)
  ports/libvpx/portfile.cmake:105 (vcpkg_build_msbuild)
  scripts/ports.cmake:147 (include)

error: building libvpx:x64-windows-static failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libvpx
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libvpx]+Build+error
Include '[libvpx] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-02-16-12e657924d99511514c0287ca5ce46882d3657c7
    vcpkg-scripts version: 64fabc940 2023-03-02 (6 hours ago)
Please use the prefilled template from C:\Users\1\vcpkg\installed\vcpkg\issue_body.md when reporting your issue.

----------------------------------------------- content in **C:\Users\1\vcpkg\buildtrees\libvpx\build-x64-windows-static-rel-out.log**-----------------------

MSBuild version 17.5.0+6f08c67f3 for .NET Framework
生成启动时间为 2023/3/3 11:53:22。
Included response file: D:\Q'S Production\C++\ide\MSBuild\Current\Bin\amd64\MSBuild.rsp

     1>项目“C:\Users\1\vcpkg\buildtrees\libvpx\x64-windows-static\vpx.vcxproj”在节点 1 上(Rebuild 个目标)。
     1>D:\Q'S Production\C++\ide\MSBuild\Microsoft\VC\v170\Microsoft.Cpp.Default.props(53,92): error MSB4092: 在条件“Exists('D:\Q'S Production\C++\ide\MSBuild\$(MSBuildToolsVersion)\Microsoft.Common.props')”中的字符位置 14 处发现意外标记“S”。 [C:\Users\1\vcpkg\buildtrees\libvpx\x64-windows-static\vpx.vcxproj]
     1>已完成生成项目“C:\Users\1\vcpkg\buildtrees\libvpx\x64-windows-static\vpx.vcxproj”(Rebuild 个目标)的操作 - 失败。

生成失败。

       “C:\Users\1\vcpkg\buildtrees\libvpx\x64-windows-static\vpx.vcxproj”(Rebuild 目标) (1) ->
         D:\Q'S Production\C++\ide\MSBuild\Microsoft\VC\v170\Microsoft.Cpp.Default.props(53,92): error MSB4092: 在条件“Exists('D:\Q'S Production\C++\ide\MSBuild\$(MSBuildToolsVersion)\Microsoft.Common.props')”中的字符位置 14 处发现意外标记“S”。 [C:\Users\1\vcpkg\buildtrees\libvpx\x64-windows-static\vpx.vcxproj]

    0 个警告
    1 个错误

已用时间 00:00:00.28

**Comment by QYH2MMT4EVER** [comment]
Anyone could help me？  this gross problem has tortured me for days ！

**Comment by MonicaLiu0311** [comment]
Please confirm the following actions and try again:
* Run VCPKG with Powershell instead of git bash
* Confirm that your VS installed English language package
![image](https://user-images.githubusercontent.com/110024546/222654099-568c7b49-5157-4dc2-b521-2d2986f0af51.png)


If you still fail, please provide the detailed log in the output desk, such as: 
```
See logs for more information:
C:\Users\1\vcpkg\buildtrees\libvpx\build-x64-windows-static-rel-out.log
```

**Comment by QYH2MMT4EVER** [comment]
> Please confirm the following actions and try again:
> 
> * Run VCPKG with Powershell instead of git bash
> * Confirm that your VS installed English language package
>   ![image](https://user-images.githubusercontent.com/110024546/222654099-568c7b49-5157-4dc2-b521-2d2986f0af51.png)
> 
> If you still fail, please provide the detailed log in the output desk, such as:
> 
> ```
> See logs for more information:
> C:\Users\1\vcpkg\buildtrees\libvpx\build-x64-windows-static-rel-out.log
> ```

Hello bro！Firstly ，thank for your help！but  the problems still exist after I  did all the actions as your advise ！i ran it in the powershell  ，and i indeed have the English language package ！ what's more , the detailed  log I will aattach in the end of my reply in the form of bond:
--------------------------------------------------------------detailed log---------------------------------------------------------------
**MSBuild version 17.5.0+6f08c67f3 for .NET Framework
生成启动时间为 2023/3/3 16:16:21。
Included response file: D:\Q'S Production\C++\ide\MSBuild\Current\Bin\amd64\MSBuild.rsp

     1>项目“C:\Users\1\vcpkg\buildtrees\libvpx\x64-windows-static\vpx.vcxproj”在节点 1 上(Rebuild 个目标)。
     1>D:\Q'S Production\C++\ide\MSBuild\Microsoft\VC\v170\Microsoft.Cpp.Default.props(53,92): error MSB4092: 在条件“Exists('D:\Q'S Production\C++\ide\MSBuild\$(MSBuildToolsVersion)\Microsoft.Common.props')”中的字符位置 14 处发现意外标记“S”。 [C:\Users\1\vcpkg\buildtrees\libvpx\x64-windows-static\vpx.vcxproj]
     1>已完成生成项目“C:\Users\1\vcpkg\buildtrees\libvpx\x64-windows-static\vpx.vcxproj”(Rebuild 个目标)的操作 - 失败。

生成失败。

       “C:\Users\1\vcpkg\buildtrees\libvpx\x64-windows-static\vpx.vcxproj”(Rebuild 目标) (1) ->
         D:\Q'S Production\C++\ide\MSBuild\Microsoft\VC\v170\Microsoft.Cpp.Default.props(53,92): error MSB4092: 在条件“Exists('D:\Q'S Production\C++\ide\MSBuild\$(MSBuildToolsVersion)\Microsoft.Common.props')”中的字符位置 14 处发现意外标记“S”。 [C:\Users\1\vcpkg\buildtrees\libvpx\x64-windows-static\vpx.vcxproj]

    0 个警告
    1 个错误

已用时间 00:00:00.05**

**Comment by QYH2MMT4EVER** [comment]
> Please confirm the following actions and try again:
> 
> * Run VCPKG with Powershell instead of git bash
> * Confirm that your VS installed English language package
>   ![image](https://user-images.githubusercontent.com/110024546/222654099-568c7b49-5157-4dc2-b521-2d2986f0af51.png)
> 
> If you still fail, please provide the detailed log in the output desk, such as:
> 
> ```
> See logs for more information:
> C:\Users\1\vcpkg\buildtrees\libvpx\build-x64-windows-static-rel-out.log
> ```

Package: libvpx[core]:x64-windows-static -> 1.12.0

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.35.32215.0
-    vcpkg-tool version: 2023-02-16-12e657924d99511514c0287ca5ce46882d3657c7
    vcpkg-scripts version: 64fabc940 2023-03-02 (12 hours ago)

**To Reproduce**

`vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static`

**Failure logs**

```
-- Using cached webmproject-libvpx-v1.12.0.tar.gz.
-- Cleaning sources at C:/Users/1/vcpkg/buildtrees/libvpx/src/v1.12.0-2729413caf.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/1/vcpkg/downloads/webmproject-libvpx-v1.12.0.tar.gz
-- Applying patch 0002-Fix-nasm-debug-format-flag.patch
-- Applying patch 0003-add-uwp-v142-and-v143-support.patch
-- Applying patch 0004-remove-library-suffixes.patch
-- Using source at C:/Users/1/vcpkg/buildtrees/libvpx/src/v1.12.0-2729413caf.clean
-- Using cached msys-gzip-1.11-1-x86_64.pkg.tar.zst.
-- Using cached msys-bash-5.1.008-1-x86_64.pkg.tar.zst.
-- Using cached msys-diffutils-3.8-2-x86_64.pkg.tar.zst.
-- Using cached msys-coreutils-8.32-2-x86_64.pkg.tar.zst.
-- Using cached msys-grep-3.0-2-x86_64.pkg.tar.xz.
-- Using cached msys-sed-4.8-2-x86_64.pkg.tar.zst.
-- Using cached msys-libpcre-8.45-1-x86_64.pkg.tar.zst.
-- Using cached msys-gawk-5.1.0-2-x86_64.pkg.tar.zst.
-- Using cached msys-mpfr-4.1.0-1-x86_64.pkg.tar.zst.
-- Using cached msys-gmp-6.2.1-1-x86_64.pkg.tar.zst.
-- Using cached msys-libreadline-8.1.001-1-x86_64.pkg.tar.zst.
-- Using cached msys-ncurses-6.2-2-x86_64.pkg.tar.zst.
-- Using cached msys-pkg-config-0.29.2-4-x86_64.pkg.tar.zst.
-- Using cached msys-make-4.3-3-x86_64.pkg.tar.zst.
-- Using cached msys-libintl-0.21-1-x86_64.pkg.tar.zst.
-- Using cached msys-libiconv-1.16-2-x86_64.pkg.tar.zst.
-- Using cached msys-gcc-libs-11.2.0-3-x86_64.pkg.tar.zst.
-- Using cached msys-msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst.
-- Using msys root at C:/Users/1/vcpkg/downloads/tools/msys2/79d5b6b790550399
-- Generating makefile
-- Generating MSBuild projects
-- Building C:/Users/1/vcpkg/buildtrees/libvpx/x64-windows-static/vpx.vcxproj for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: msbuild C:/Users/1/vcpkg/buildtrees/libvpx/x64-windows-static/vpx.vcxproj /p:Configuration=Release /p:UseEnv=True /t:Rebuild /p:Platform=x64 /p:PlatformToolset=v143 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.22621.0 /p:VcpkgManifestInstall=false /p:VcpkgManifestEnabled=false /m /p:WholeProgramOptimization=false /p:VcpkgEnabled=false
    Working Directory: C:/Users/1/vcpkg/buildtrees/libvpx/x64-windows-static-rel
    Error code: 1
    See logs for more information:
      C:\Users\1\vcpkg\buildtrees\libvpx\build-x64-windows-static-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:65 (vcpkg_execute_required_process)
  ports/libvpx/portfile.cmake:105 (vcpkg_build_msbuild)
  scripts/ports.cmake:147 (include)



```
<details><summary>C:\Users\1\vcpkg\buildtrees\libvpx\build-x64-windows-static-rel-out.log</summary>

```
MSBuild version 17.5.0+6f08c67f3 for .NET Framework
生成启动时间为 2023/3/3 16:34:34。
Included response file: D:\Q'S Production\C++\ide\MSBuild\Current\Bin\amd64\MSBuild.rsp

     1>项目“C:\Users\1\vcpkg\buildtrees\libvpx\x64-windows-static\vpx.vcxproj”在节点 1 上(Rebuild 个目标)。
     1>D:\Q'S Production\C++\ide\MSBuild\Microsoft\VC\v170\Microsoft.Cpp.Default.props(53,92): error MSB4092: 在条件“Exists('D:\Q'S Production\C++\ide\MSBuild\$(MSBuildToolsVersion)\Microsoft.Common.props')”中的字符位置 14 处发现意外标记“S”。 [C:\Users\1\vcpkg\buildtrees\libvpx\x64-windows-static\vpx.vcxproj]
     1>已完成生成项目“C:\Users\1\vcpkg\buildtrees\libvpx\x64-windows-static\vpx.vcxproj”(Rebuild 个目标)的操作 - 失败。

生成失败。

       “C:\Users\1\vcpkg\buildtrees\libvpx\x64-windows-static\vpx.vcxproj”(Rebuild 目标) (1) ->
         D:\Q'S Production\C++\ide\MSBuild\Microsoft\VC\v170\Microsoft.Cpp.Default.props(53,92): error MSB4092: 在条件“Exists('D:\Q'S Production\C++\ide\MSBuild\$(MSBuildToolsVersion)\Microsoft.Common.props')”中的字符位置 14 处发现意外标记“S”。 [C:\Users\1\vcpkg\buildtrees\libvpx\x64-windows-static\vpx.vcxproj]

    0 个警告
    1 个错误

已用时间 00:00:00.02
```
</details>

**Additional context**

**Comment by QYH2MMT4EVER** [comment]
HELLO  GUYS ！ I have solved this problem！ The  problem is  on my VS ! I uninstalled VS and installed again ,then the problem is gone !

**Comment by MonicaLiu0311** [comment]
Problem solved, will close this issue.
