### ISSUE TITLE
How do I resolve this error: building metis:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by mrprashant96** [microsoft/vcpkg#29988]
Please create a discussion in https://github.com/microsoft/vcpkg/discussions/new instead.

**Comment by Adela0814** [comment]
@mrprashant96  please provide the repro steps and failure logs, thanks.

**Comment by mrprashant96** [comment]
Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  buildtrees/versioning_/versions/metis/f3670208e9dc0b726c3c009e37f2398b7f2acca3/portfile.cmake:6 (vcpkg_download_distfile)
  scripts/ports.cmake:147 (include)

**Comment by mrprashant96** [comment]
PS D:\RealtimeFaceCapture> cmake --preset "win64-vs-msvc-d”
Preset CMake variables:

  CMAKE_BUILD_TYPE="Debug"
  VCPKG_MANIFEST_INSTALL:BOOL="TRUE"
  VCPKG_MANIFEST_MODE:BOOL="TRUE"
  VCPKG_TARGET_ARCHITECTURE="x64"
  VCPKG_TARGET_TRIPLET="x64-windows"

Preset environment variables:

  MKLROOT="C:/Program Files (x86)/Intel/oneAPI/mkl/latest"
  QT_INSTALLATION_PREFIX="C:/Qt/6.4.2"
  VCPKG_DIR="D:/vcpkg"
  VCPKG_OVERLAY_TRIPLETS="./Scripts/vcpkg-triplet-configs/"

-- Running vcpkg install
Detecting compiler hash for triplet x64-windows...
The following packages will be built and installed:
  * blas[core]:x64-windows -> 1#1 -- D:\vcpkg\buildtrees\versioning_\versions\blas\0d105be9337f4a6f294a7eced2da18e8cdb99051
  * bzip2[core]:x64-windows -> 1.0.8#2 -- D:\vcpkg\buildtrees\versioning_\versions\bzip2\a1ea352502e69888a565563d9151d3f7ab609fb1
    cereal[core]:x64-windows -> 1.3.0#1 -- D:\vcpkg\buildtrees\versioning_\versions\cereal\7229804bbf716bbefe8052d650fc94687b6dae42
    ceres[core]:x64-windows -> 2.0.0#6 -- D:\vcpkg\buildtrees\versioning_\versions\ceres\af54888fc010404793ba51c862147575c09a988b
    dlib[core,fftw3,sqlite3]:x64-windows -> 19.23 -- D:\vcpkg\buildtrees\versioning_\versions\dlib\825d6117ba43320dd5969535320b8be3144ea9de
    eigen3[core]:x64-windows -> 3.4.0 -- D:\vcpkg\buildtrees\versioning_\versions\eigen3\0475ed327bda734cad0acd35978cde9379bc8619
  * fftw3[core]:x64-windows -> 3.3.10#3 -- D:\vcpkg\buildtrees\versioning_\versions\fftw3\2bd307eb2dafcd4938d16fc484fbbb731228f4c3
  * gflags[core]:x64-windows -> 2.2.2#5 -- D:\vcpkg\buildtrees\versioning_\versions\gflags\7c1fe35b0a7e9b5b9f58b16c6cc08caa108fb945
  * giflib[core]:x64-windows -> 5.2.1#1 -- D:\vcpkg\buildtrees\versioning_\versions\giflib\14178ec83d76a40e314adcf9bba75b63e99bc56d
    glfw3[core]:x64-windows -> 3.3.6 -- D:\vcpkg\buildtrees\versioning_\versions\glfw3\8a41aae4fb04023a3a94bf3aa66196b0aee2cc8e
    glm[core]:x64-windows -> 0.9.9.8#1 -- D:\vcpkg\buildtrees\versioning_\versions\glm\4aafac80f39a72fadaf6a31afb961790678062de
  * glog[core]:x64-windows -> 0.4.0#4 -- D:\vcpkg\buildtrees\versioning_\versions\glog\27503732c21f2d6652d12d62b1e9c180c1d33c47
  * hdf5[core,szip,zlib]:x64-windows -> 1.12.1#4 -- D:\vcpkg\buildtrees\versioning_\versions\hdf5\1000a70aefebfdd856715d265c3421c80157b773
  * lapack[core]:x64-windows -> 3#2 -- D:\vcpkg\buildtrees\versioning_\versions\lapack\e52f9dc39357e3e7224273a21c0efaf275f15ae6
  * lapack-reference[blas-select,core,noblas]:x64-windows -> 3.8.0#6 -- D:\vcpkg\buildtrees\versioning_\versions\lapack-reference\10799c7ec42f8369179ba7a8e927235596cb8bb7
  * leptonica[core]:x64-windows -> 1.81.1 -- D:\vcpkg\buildtrees\versioning_\versions\leptonica\215a8a32b41e1561998ac840c3c35404707186a2
  * libarchive[bzip2,core,libxml2,lz4,lzma,openssl,zstd]:x64-windows -> 3.5.2#3 -- D:\vcpkg\buildtrees\versioning_\versions\libarchive\2408bfca781ee9e5add6e674043e5f8ccca73a1b
    libiconv[core]:x64-windows -> 1.16#11 -- D:\vcpkg\buildtrees\versioning_\versions\libiconv\f82980bff6c23bcccd043300679ebf8afa3e0a22
  * libjpeg-turbo[core]:x64-windows -> 2.1.2 -- D:\vcpkg\buildtrees\versioning_\versions\libjpeg-turbo\b37f789a1bb562a1469e0c30cf195c641ab824a6
  * liblzma[core]:x64-windows -> 5.2.5#4 -- D:\vcpkg\buildtrees\versioning_\versions\liblzma\273eaeff533f90bc42394cca9f1ea23ff6b49534
  * libpng[core]:x64-windows -> 1.6.37#16 -- D:\vcpkg\buildtrees\versioning_\versions\libpng\b082585ac20aefc27150af5386b6a8a15473e93a
  * libwebp[core,nearlossless,simd,unicode]:x64-windows -> 1.2.1 -- D:\vcpkg\buildtrees\versioning_\versions\libwebp\ca5a8b2ed264617e8a35d22e1e6ac18ebe99900f
  * libxml2[core]:x64-windows -> 2.9.12#4 -- D:\vcpkg\buildtrees\versioning_\versions\libxml2\5cb8ed61786fdd081204880cd02d9376b17130eb
  * lz4[core]:x64-windows -> 1.9.3#3 -- D:\vcpkg\buildtrees\versioning_\versions\lz4\43957fa49e865966b52c6729db11aa067f790d49
  * metis[core]:x64-windows -> 5.1.0#8 -- D:\vcpkg\buildtrees\versioning_\versions\metis\f3670208e9dc0b726c3c009e37f2398b7f2acca3
    nanoflann[core]:x64-windows -> 1.3.2#1 -- D:\vcpkg\buildtrees\versioning_\versions\nanoflann\481ec544fb82ec73f6f0e01d1333f412d3e82d2d
  * openblas[core]:x64-windows -> 0.3.19 -- D:\vcpkg\buildtrees\versioning_\versions\openblas\631541b0dcf2ea300f96829885d9bc0282d38a65
    opencv[contrib,core,default-features]:x64-windows -> 4.5.4#1 -- D:\vcpkg\buildtrees\versioning_\versions\opencv\c120b015f37bc79900712d64e8ca612d71be22cc
  * opencv4[contrib,core,default-features,dnn,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.5.4#4 -- D:\vcpkg\buildtrees\versioning_\versions\opencv4\ce474a40e6572ced8dd1229f22f6cbed9cc74212
  * openjpeg[core]:x64-windows -> 2.4.0 -- D:\vcpkg\buildtrees\versioning_\versions\openjpeg\ffb3c981c0026662feded28db73c177a739773d2
  * openssl[core]:x64-windows -> 3.0.2#2 -- D:\vcpkg\buildtrees\versioning_\versions\openssl\66e7ff434d21a4fc00cab9bbe6167db295ffefd3
  * protobuf[core]:x64-windows -> 3.18.0#1 -- D:\vcpkg\buildtrees\versioning_\versions\protobuf\5f6aa04d94e184b89c1887946fb4684bc51c4611
  * quirc[core]:x64-windows -> 1.1#3 -- D:\vcpkg\buildtrees\versioning_\versions\quirc\85b17d675bbbb05448d16af79d434bc5fca51f7b
  * sqlite3[core]:x64-windows -> 3.37.2#1 -- D:\vcpkg\buildtrees\versioning_\versions\sqlite3\f49ad405225c6326558adb79f2082814002a8cda
    stb[core]:x64-windows -> 2020-09-14#1 -- D:\vcpkg\buildtrees\versioning_\versions\stb\fa6d7e998f98f122efa37f456ffa498d546185b9
    suitesparse[core]:x64-windows -> 5.8.0#1 -- D:\vcpkg\buildtrees\versioning_\versions\suitesparse\4c709290c9cc6e7635c120dbd5cd9d227408a0ab
  * szip[core]:x64-windows -> 2.1.1#7 -- D:\vcpkg\buildtrees\versioning_\versions\szip\6f810fcedf9469940a80e5c343d983a55134332b
  * tesseract[core]:x64-windows -> 4.1.1#10 -- D:\vcpkg\buildtrees\versioning_\versions\tesseract\ac84bef93d2709f28bf4ab8341a80dab949a8cf1
  * tiff[core,jpeg,lzma,zip]:x64-windows -> 4.3.0#5 -- D:\vcpkg\buildtrees\versioning_\versions\tiff\29af46222dc88425d734288253d807f1a9b96419
    tinyobjloader[core]:x64-windows -> 2.0.0-rc9 -- D:\vcpkg\buildtrees\versioning_\versions\tinyobjloader\c1e6a1c3ddc75a72ea801b5d0980a73e14358e5e
    toml11[core]:x64-windows -> 3.7.0 -- D:\vcpkg\buildtrees\versioning_\versions\toml11\ab8e69aef0551e2e862e74ec70b5c2dd58aac36b
  * vcpkg-cmake[core]:x64-windows -> 2022-12-22 -- D:\vcpkg\buildtrees\versioning_\versions\vcpkg-cmake\1913f86defd2140d0a6751be2d51952e4090efa4
  * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06#1 -- D:\vcpkg\buildtrees\versioning_\versions\vcpkg-cmake-config\8d54cc4f487d51b655abec5f9c9c3f86ca83311f
  * vcpkg-gfortran[core]:x64-windows -> 3#2 -- D:\vcpkg\buildtrees\versioning_\versions\vcpkg-gfortran\5fa617d0b37f47f7f19210be936e25914d6f64c6
    vulkan[core]:x64-windows -> 1.1.82.1#3 -- D:\vcpkg\buildtrees\versioning_\versions\vulkan\bb172f7bc0075f17c4b1c9f1068adfbb2bc4b3a8
  * zlib[core]:x64-windows -> 1.2.11#13 -- D:\vcpkg\buildtrees\versioning_\versions\zlib\92cfe30c807d343c6359d272242f0765ad906740
  * zstd[core]:x64-windows -> 1.5.2#1 -- D:\vcpkg\buildtrees\versioning_\versions\zstd\2f8a5da3f925dc994500dabb2d3b5c7e11df0afd
Additional packages (*) will be modified to complete this operation.
Restored 43 package(s) from C:\Users\prash\AppData\Local\vcpkg\archives in 27.23 s. Use --debug to see more details.
Installing 1/47 cereal:x64-windows...
Elapsed time to handle cereal:x64-windows: 118.7 ms
Installing 2/47 vcpkg-cmake-config:x64-windows...
Elapsed time to handle vcpkg-cmake-config:x64-windows: 14.9 ms
Installing 3/47 vcpkg-cmake:x64-windows...
Elapsed time to handle vcpkg-cmake:x64-windows: 18.41 ms
Installing 4/47 gflags:x64-windows...
Elapsed time to handle gflags:x64-windows: 55.63 ms
Installing 5/47 glog:x64-windows...
Elapsed time to handle glog:x64-windows: 47.9 ms
Installing 6/47 eigen3:x64-windows...
Elapsed time to handle eigen3:x64-windows: 1.199 s
Installing 7/47 ceres:x64-windows...
Elapsed time to handle ceres:x64-windows: 1.65 s
Installing 8/47 sqlite3:x64-windows...
Elapsed time to handle sqlite3:x64-windows: 66.06 ms
Installing 9/47 fftw3:x64-windows...
Elapsed time to handle fftw3:x64-windows: 233.9 ms
Installing 10/47 zlib:x64-windows...
Elapsed time to handle zlib:x64-windows: 39.32 ms
Installing 11/47 libpng:x64-windows...
Elapsed time to handle libpng:x64-windows: 143.4 ms
Installing 12/47 libjpeg-turbo:x64-windows...
Elapsed time to handle libjpeg-turbo:x64-windows: 74.33 ms
Installing 13/47 openblas:x64-windows...
Elapsed time to handle openblas:x64-windows: 254.5 ms
Installing 14/47 blas:x64-windows...
Elapsed time to handle blas:x64-windows: 11.39 ms
Installing 15/47 vcpkg-gfortran:x64-windows...
Elapsed time to handle vcpkg-gfortran:x64-windows: 115.6 ms
Installing 16/47 lapack-reference:x64-windows...
Elapsed time to handle lapack-reference:x64-windows: 73.06 ms
Installing 17/47 lapack:x64-windows...
Elapsed time to handle lapack:x64-windows: 17.2 ms
Installing 18/47 dlib:x64-windows...
Elapsed time to handle dlib:x64-windows: 1.423 s
Installing 19/47 glfw3:x64-windows...
Elapsed time to handle glfw3:x64-windows: 82.42 ms
Installing 20/47 glm:x64-windows...
Elapsed time to handle glm:x64-windows: 323.1 ms
Installing 21/47 libiconv:x64-windows...
Elapsed time to handle libiconv:x64-windows: 55.84 ms
Installing 22/47 nanoflann:x64-windows...
Elapsed time to handle nanoflann:x64-windows: 44.28 ms
Installing 23/47 libwebp:x64-windows...
Elapsed time to handle libwebp:x64-windows: 75.5 ms
Installing 24/47 liblzma:x64-windows...
Elapsed time to handle liblzma:x64-windows: 56.03 ms
Installing 25/47 tiff:x64-windows...
Elapsed time to handle tiff:x64-windows: 55.03 ms
Installing 26/47 quirc:x64-windows...
Elapsed time to handle quirc:x64-windows: 28.29 ms
Installing 27/47 protobuf:x64-windows...
Elapsed time to handle protobuf:x64-windows: 588 ms
Installing 28/47 zstd:x64-windows...
Elapsed time to handle zstd:x64-windows: 49.75 ms
Installing 29/47 openssl:x64-windows...
Elapsed time to handle openssl:x64-windows: 429.2 ms
Installing 30/47 lz4:x64-windows...
Elapsed time to handle lz4:x64-windows: 38.3 ms
Installing 31/47 libxml2:x64-windows...
Elapsed time to handle libxml2:x64-windows: 348.6 ms
Installing 32/47 bzip2:x64-windows...
Elapsed time to handle bzip2:x64-windows: 38.84 ms
Installing 33/47 libarchive:x64-windows...
Elapsed time to handle libarchive:x64-windows: 62.14 ms
Installing 34/47 openjpeg:x64-windows...
Elapsed time to handle openjpeg:x64-windows: 54.78 ms
Installing 35/47 giflib:x64-windows...
Elapsed time to handle giflib:x64-windows: 29.79 ms
Installing 36/47 leptonica:x64-windows...
Elapsed time to handle leptonica:x64-windows: 90.57 ms
Installing 37/47 tesseract:x64-windows...
Elapsed time to handle tesseract:x64-windows: 296.1 ms
Installing 38/47 szip:x64-windows...
Elapsed time to handle szip:x64-windows: 45.29 ms
Installing 39/47 hdf5:x64-windows...
Elapsed time to handle hdf5:x64-windows: 278.2 ms
Installing 40/47 opencv4:x64-windows...
Elapsed time to handle opencv4:x64-windows: 2.593 s
Installing 41/47 opencv:x64-windows...
Elapsed time to handle opencv:x64-windows: 22.67 ms
Installing 42/47 stb:x64-windows...
Elapsed time to handle stb:x64-windows: 52.87 ms
Installing 43/47 metis:x64-windows...
Building metis[core]:x64-windows...
-- Installing port from location: D:\vcpkg\buildtrees\versioning_\versions\metis\f3670208e9dc0b726c3c009e37f2398b7f2acca3
-- Note: metis only supports static library linkage. Building static library.
-- Downloading http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.1.0.tar.gz -> metis-5.1.0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
Downloading http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.1.0.tar.gz
warning: Download failed -- retrying after 1000ms
warning: Download failed -- retrying after 2000ms
warning: Download failed -- retrying after 4000ms
error: Failed to download from mirror set
error: http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.1.0.tar.gz: WinHttpSendRequest failed with exit code 12002
error: http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.1.0.tar.gz: WinHttpSendRequest failed with exit code 12002
error: http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.1.0.tar.gz: WinHttpSendRequest failed with exit code 12002
error: http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.1.0.tar.gz: WinHttpSendRequest failed with exit code 12002
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(956):
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 11 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 3440 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 1.521 min (91259462 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.


Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  buildtrees/versioning_/versions/metis/f3670208e9dc0b726c3c009e37f2398b7f2acca3/portfile.cmake:6 (vcpkg_download_distfile)
  scripts/ports.cmake:147 (include)


error: building metis:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+metis
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[metis]+Build+error
Include '[metis] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-02-16-12e657924d99511514c0287ca5ce46882d3657c7
    vcpkg-scripts version: d5bc0e71e 2023-02-27 (3 days ago)


Please use the prefilled template from D:\RealtimeFaceCapture\out\win64-vs-msvc-d\vcpkg_installed\vcpkg\issue_body.md when reporting your issue.
-- Running vcpkg install - failed
CMake Error at D:/vcpkg/scripts/buildsystems/vcpkg.cmake:886 (message):
  vcpkg install failed.  See logs for more information:
  D:\RealtimeFaceCapture\out\win64-vs-msvc-d\vcpkg-manifest-install.log
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:148 (include)
  CMakeLists.txt:31 (project)


-- Configuring incomplete, errors occurred!

**Comment by Adela0814** [comment]
@mrprashant96  Please make sure your network is smooth and the proxy is available.

**Comment by Adela0814** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
