### ISSUE TITLE
[glbinding] Update to latest version

### ISSUE THREAD

**Issue by patrikhuber** [Microsoft/vcpkg#2998]
The glbinding (https://github.com/cginternals/glbinding/releases) version in vcpkg is 2.1.1-3 from June 2016. It would be awesome to have it updated to the most recent version.

**Comment by NancyLi1013** [comment]
Hi @patrikhuber ，the glbinding has updated to 3.0.2-4. So I close this issue. If you have any other requests or problems, please fill a new issue. 
Thanks!
