### ISSUE TITLE
Crash when using vcpkg with pybind11 + opencv-python

### ISSUE THREAD

**Issue by clejacquet-rokken** [microsoft/vcpkg#29991]
**Describe the bug**
I am working on a C++ program that uses pybind11 to call Python scripts. The program crashes in one of the Python scripts when importing OpenCV with the line `import cv2`. This crash only occurs when using VCPKG to install pybind11 and building in Release mode. It runs successfully in Debug mode. 

**Environment**
- OS: Windows 11 Home
- Compiler: MSVC (Visual Studio Community 2022 17.5.1 - amd64)
- CMake version 3.25.1-msvc1
- Python 3.10.10
- Pybind11 2.9.1
- Latest version of VCPKG 64fabc9401d9296273ed67cd8c39f92c113f9ea5

**To Reproduce**

1. Install the `pybind11` v2.9.1 port
2. Install `opencv-python-headless==4.6.0.66` with pip
3. Write a C++ program that initializes a Python interpreter with Pybind11 and calls a Python script containing the line `import cv2`
4. Build with CMake using VCPKG's toolchain and run in Release mode
5. See the error

A minimal reproducible example is provided in this repository: https://github.com/clejacquet-rokken/vcpkg-pybind-cv-test

**Expected behavior**
The import should succeed with no error raised.

**Failure logs**
```
ImportError: DLL load failed while importing cv2: The specified module could not be found.

At:
  C:\Program Files\Python310\Lib\importlib\__init__.py(126): import_module
  [...]/.virtualenvs/rtvr/Lib/site-packages\cv2\__init__.py(153): bootstrap
  [...]/.virtualenvs/rtvr/Lib/site-packages\cv2\__init__.py(181): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
```

**Additional context**
- This error only occurs when using VCPKG's CMake toolchain. When manually cloning Pybind11 it works.
- I've tested different versions of OpenCV's Python packages and several packages (e.g. `opencv-python` or `opencv-contrib-python`) to no effect.
- It seems that setting the env var `PYTHONPATH` to the path of an external installation of OpenCV fixes this issue (see the minimal reproducible example).

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. I will test this issue locally soon.

**Comment by LilyWangLL** [comment]
Hi @clejacquet-rokken, there is a `opencv` upstream issue https://github.com/opencv/opencv/issues/19972 about this error, could you please confirm it is useful for you?

**Comment by clejacquet-rokken** [comment]
Hi, sorry for the delay, I finally found the reason why this error happens.

I use a virtual environment. In my program, I add the path to this virtual environment's `site-packages` folder to the Python `sys.path` variable, so that my program could use my virtual environment's packages. However, I did not realize that the pybind11 port actually depends on the Python3 port which has its own binaries, and that my program is linked against those binaries instead of my system Python binaries.

_More details about how the error occurs:_
When I run the program, the `opencv-python` package located in my virtual env tries to load the `python310.dll`. I noticed that the Python's port `python310.dll` is copied into the build folder next to the .exe, so `opencv-python` finds this one and loads it but fails because the versions do not match (virtual env Python: 3.10.10, VCPKG Python port: 3.10.7).

After reading some issues (#23796 and #11060), it seems that this is expected behavior. This becomes more of a question about the Pybind and Python ports, but let's say I want to use a Python environment with package requirements, what is the recommended way to go? Install the packages inside the VCPKG's port build files with something like below?

```cmake
add_custom_command(
  TARGET myExe POST_BUILD
  COMMAND /path/to/python/port/pip install -r ${CMAKE_CURRENT_SOURCE_DIR}/pip_requirements.txt)
```

This would attempt to re-install the packages every time `myExe` is built, so it's not optimal. I could not find any information about this, do you recommend another method?

**Comment by LilyWangLL** [comment]
```
if (VCPKG_TARGET_IS_WINDOWS)
    set(EXECUTABLE_SUFFIX ".exe")
    set(PYTHON_OPTION "")
else()
    set(EXECUTABLE_SUFFIX "")
    set(PYTHON_OPTION "--user")
endif()

vcpkg_find_acquire_program(PYTHON2)
get_filename_component(PYTHON2_DIR "${PYTHON2}" DIRECTORY)
vcpkg_add_to_path("${PYTHON2_DIR}")

if(NOT EXISTS "${PYTHON2_DIR}/easy_install${EXECUTABLE_SUFFIX}")
    if(NOT EXISTS "${PYTHON2_DIR}/Scripts/pip${EXECUTABLE_SUFFIX}")
        vcpkg_from_github(
            OUT_SOURCE_PATH PYFILE_PATH
            REPO pypa/get-pip
            REF 309a56c5fd94bd1134053a541cb4657a4e47e09d #2019-08-25
            SHA512 bb4b0745998a3205cd0f0963c04fb45f4614ba3b6fcbe97efe8f8614192f244b7ae62705483a5305943d6c8fedeca53b2e9905aed918d2c6106f8a9680184c7a
            HEAD_REF master
        )
        execute_process(COMMAND ${PYTHON2_DIR}/python${EXECUTABLE_SUFFIX} ${PYFILE_PATH}/get-pip.py ${PYTHON_OPTION})
    endif()
    execute_process(COMMAND ${PYTHON2_DIR}/Scripts/pip${EXECUTABLE_SUFFIX} install pyyaml ${PYTHON_OPTION})
else()
    execute_process(COMMAND ${PYTHON2_DIR}/easy_install${EXECUTABLE_SUFFIX} pyyaml)
endif()
```
The above codes are from port [duktape](https://github.com/microsoft/vcpkg/blob/master/ports/duktape/portfile.cmake), you could refer to this port to judge the files of the package that need to be installed.

**Comment by JackBoosY** [comment]
Remove you manually installed python3 may fix this issue since the dependency chain is broken.
