### ISSUE TITLE
Add FreeImage

### ISSUE THREAD

**Issue by corporateshark** [Microsoft/vcpkg#3]
http://freeimage.sourceforge.net

**Comment by traversaro** [comment]
I looked a bit into this (it is a required dep for https://github.com/Microsoft/vcpkg/issues/14).
Apparently freeimage ships a lot of its dependencies as part of their repo. To use the version of this libraries provided by `vcpkg`, the best strategy is probably to roll our own CMake-based build system, as done for `zziplib` and `fastlz`. 

Required dependencies (ticked if they are already present in vcpkg):
* [x] `zlib` 
* [x] `libjpeg` (provided by the header-compatible  `libjpeg-turbo`)
* [x] `libpng`
* [x] `tiff`
* [ ] `openexr` https://github.com/openexr/openexr
* [ ] `openjpg` https://github.com/uclouvain/openjpeg
* [ ] `libjxr` https://jxrlib.codeplex.com/ (not sure if this is the official upstream repository)
* [ ] `libwebp` https://github.com/webmproject/libwebp
* [ ] `libraw` http://www.libraw.org/ 

Related links : 
* https://sourceforge.net/p/freeimage/bugs/232/
* https://anonscm.debian.org/cgit/debian-science/packages/freeimage.git/tree/debian
