### ISSUE TITLE
Fail building openblas while installing blaze.

### ISSUE THREAD

**Issue by rtohid** [Microsoft/vcpkg#3000]
I get the following error trying to install Blaze:

PS C:\Users\u\source\repos\vcpkg> .\vcpkg.exe install blaze:x64-windows --head
The following packages will be built and installed:
    blaze[core]:x64-windows (from HEAD)
  * clapack[core]:x64-windows
  * openblas[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: openblas:x64-windows
Building package openblas[core]:x64-windows...
-- CURRENT_INSTALLED_DIR=C:/Users/u/source/repos/vcpkg/installed/x64-windows
-- DOWNLOADS=C:/Users/u/source/repos/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/u/source/repos/vcpkg/packages/openblas_x64-windows
-- CURRENT_BUILDTREES_DIR=C:/Users/u/source/repos/vcpkg/buildtrees/openblas
-- CURRENT_PORT_DIR=C:/Users/u/source/repos/vcpkg/ports/openblas/.
-- Using cached C:/Users/u/source/repos/vcpkg/downloads/xianyi-OpenBLAS-v0.2.20.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch C:/Users/u/source/repos/vcpkg/ports/openblas/install-openblas.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/Users/u/source/repos/vcpkg/ports/openblas/install-openblas.patch done
-- Applying patch C:/Users/u/source/repos/vcpkg/ports/openblas/whitespace.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/Users/u/source/repos/vcpkg/ports/openblas/whitespace.patch done
-- Configuring x64-windows
-- Configuring x64-windows done
-- Build x64-windows-dbg
CMake Error at repos/vcpkg/scripts/cmake/vcpkg_build_cmake.cmake:129 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No
    Working Directory: C:/Users/u/source/repos/vcpkg/buildtrees/openblas/x64-windows-dbg
    See logs for more information:
      C:\Users\u\source\repos\vcpkg\buildtrees\openblas\install-x64-windows-dbg-out.log
      C:\Users\u\source\repos\vcpkg\buildtrees\openblas\install-x64-windows-dbg-err.log

Call Stack (most recent call first):
  repos/vcpkg/scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  repos/vcpkg/ports/openblas/portfile.cmake:93 (vcpkg_install_cmake)
  repos/vcpkg/scripts/ports.cmake:72 (include)

Error: Building package openblas:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openblas:x64-windows
  Vcpkg version: 0.0.105-2018-03-09-6dbc38d3a0c4bb93431f8be74d0a024c3e1d8b4e

**Comment by ras0219-msft** [comment]
Thanks for posting this issue!

I'm able to build the library, so could you post the log files for us to investigate further?

>C:\Users\u\source\repos\vcpkg\buildtrees\openblas\install-x64-windows-dbg-out.log
C:\Users\u\source\repos\vcpkg\buildtrees\openblas\install-x64-windows-dbg-err.log

**Comment by rtohid** [comment]
Thanks for your prompt response. 
I updated my windows and pulled the latest this morning, and the issue is resolved.

**Comment by Voskrese** [comment]
@rtohid я незнаю как он у вас скомпилировался потому как.
так как между прочем ;) , Blaze не компануется, жалуется на API, надо добавить
`set(LAPACK_lapack_WORKS TRUE)`

```
#==================================================================================================
# Configure LAPACK
#==================================================================================================

set(LAPACK_lapack_WORKS TRUE)
find_package(LAPACK REQUIRED)
target_link_libraries(blaze INTERFACE ${LAPACK_LIBRARIES})
target_compile_options(blaze INTERFACE ${LAPACK_LINKER_FLAGS})
```
