### ISSUE TITLE
[boost-build] Build error: Unable to install boost from vcpkg

### ISSUE THREAD

**Issue by 7vidhan** [microsoft/vcpkg#30003]
Package: boost-compatibility:x64-windows

**Host Environment**

Host: x64-windows
Compiler: MSVC 19.35.32215.0
vcpkg-tool version: 2023-02-16-12e657924d99511514c0287ca5ce46882d3657c7
vcpkg-scripts version: 64fabc940 2023-03-02 (17 hours ago)

**To Reproduce**

`.\vcpkg install boost:x64-windows `

**Failure logs**

```
Installing 38/162 boost-build:x64-windows...
Building boost-build[core]:x64-windows...
-- Using cached boostorg-build-boost-1.81.0.tar.gz.
-- Cleaning sources at C:/dev/VCPKG/vcpkg/buildtrees/boost-build/src/ost-1.81.0-e13308f6b4.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/VCPKG/vcpkg/downloads/boostorg-build-boost-1.81.0.tar.gz
-- Applying patch 0002-fix-get-version.patch
-- Applying patch 0003-fix-emscripten.patch
-- Using source at C:/dev/VCPKG/vcpkg/buildtrees/boost-build/src/ost-1.81.0-e13308f6b4.clean
-- Using cached boost_LICENSE_1_0.txt.
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.81.0/boostcpp.jam -> boost-1.81.0-boostcpp.jam...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.81.0/boostcpp.jam
warning: Download failed -- retrying after 1000ms
warning: Download failed -- retrying after 2000ms
warning: Download failed -- retrying after 4000ms
error: Failed to download from mirror set
error: https://raw.githubusercontent.com/boostorg/boost/boost-1.81.0/boostcpp.jam: WinHttpSendRequest failed with exit code 12030
error: https://raw.githubusercontent.com/boostorg/boost/boost-1.81.0/boostcpp.jam: WinHttpSendRequest failed with exit code 12030
error: https://raw.githubusercontent.com/boostorg/boost/boost-1.81.0/boostcpp.jam: WinHttpSendRequest failed with exit code 12002
error: https://raw.githubusercontent.com/boostorg/boost/boost-1.81.0/boostcpp.jam: WinHttpSendRequest failed with exit code 12030
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(956):
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 3 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 4526 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 26.68 s (26646861 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.


Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/boost-build/portfile.cmake:26 (vcpkg_download_distfile)
  scripts/ports.cmake:147 (include)


error: building boost-build:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-build
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-build]+Build+error
Include '[boost-build] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-02-16-12e657924d99511514c0287ca5ce46882d3657c7
    vcpkg-scripts version: 64fabc940 2023-03-02 (17 hours ago)

```

**Comment by 7vidhan** [comment]
Installing 38/162 boost-build:x64-windows...
Building boost-build[core]:x64-windows...
-- Using cached boostorg-build-boost-1.81.0.tar.gz.
-- Cleaning sources at C:/dev/VCPKG/vcpkg/buildtrees/boost-build/src/ost-1.81.0-e13308f6b4.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/VCPKG/vcpkg/downloads/boostorg-build-boost-1.81.0.tar.gz
-- Applying patch 0002-fix-get-version.patch
-- Applying patch 0003-fix-emscripten.patch
-- Using source at C:/dev/VCPKG/vcpkg/buildtrees/boost-build/src/ost-1.81.0-e13308f6b4.clean
-- Using cached boost_LICENSE_1_0.txt.
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.81.0/boostcpp.jam -> boost-1.81.0-boostcpp.jam...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.81.0/boostcpp.jam
warning: Download failed -- retrying after 1000ms
warning: Download failed -- retrying after 2000ms
warning: Download failed -- retrying after 4000ms
error: Failed to download from mirror set
error: https://raw.githubusercontent.com/boostorg/boost/boost-1.81.0/boostcpp.jam: WinHttpSendRequest failed with exit code 12030
error: https://raw.githubusercontent.com/boostorg/boost/boost-1.81.0/boostcpp.jam: WinHttpSendRequest failed with exit code 12030
error: https://raw.githubusercontent.com/boostorg/boost/boost-1.81.0/boostcpp.jam: WinHttpSendRequest failed with exit code 12002
error: https://raw.githubusercontent.com/boostorg/boost/boost-1.81.0/boostcpp.jam: WinHttpSendRequest failed with exit code 12030
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(956):
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 3 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 4526 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 26.68 s (26646861 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.


Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/boost-build/portfile.cmake:26 (vcpkg_download_distfile)
  scripts/ports.cmake:147 (include)


error: building boost-build:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-build
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-build]+Build+error
Include '[boost-build] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-02-16-12e657924d99511514c0287ca5ce46882d3657c7
    vcpkg-scripts version: 64fabc940 2023-03-02 (17 hours ago)

**Comment by MonicaLiu0311** [comment]
```
PS E:\vcpkg02> .\vcpkg install boost-build:x64-windows --binarysource=clear
Computing installation plan...
Found a constraint violation:
    warning: dependency boost-uninstall:x64-windows was expected to be at least version 1.81.0#2, but is currently 1.80.0#1.
The following packages will be built and installed:
    boost-build[core]:x64-windows -> 1.81.0#3
Detecting compiler hash for triplet x64-windows...
Installing 1/1 boost-build:x64-windows...
Building boost-build[core]:x64-windows...
-- Downloading https://github.com/boostorg/build/archive/boost-1.81.0.tar.gz -> boostorg-build-boost-1.81.0.tar.gz...
-- Extracting source E:/vcpkg02/downloads/boostorg-build-boost-1.81.0.tar.gz
-- Applying patch 0002-fix-get-version.patch
-- Applying patch 0003-fix-emscripten.patch
-- Using source at E:/vcpkg02/buildtrees/boost-build/src/ost-1.81.0-e13308f6b4.clean
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.81.0/LICENSE_1_0.txt -> boost_LICENSE_1_0.txt...
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.81.0/boostcpp.jam -> boost-1.81.0-boostcpp.jam...
-- Installing: E:/vcpkg02/packages/boost-build_x64-windows/share/boost-build/copyright
-- Bootstrapping...
-- Performing post-build validation
Elapsed time to handle boost-build:x64-windows: 24.17 s
Total install time: 29.47 s
The package boost is compatible with built-in CMake targets:

    find_package(Boost REQUIRED [COMPONENTS <libs>...])
    target_link_libraries(main PRIVATE Boost::boost Boost::<lib1> Boost::<lib2> ...)
```

Sorry I can't reproduce your issue, installed successfully locally. Please follow the command below to update your vcpkg to the latest and restart:
```
git pull https://github.com/microsoft/vcpkg.git master
./bootstrap-vcpkg.bat
.\vcpkg remove boost-build:x64-windows --recurse
.\vcpkg install boost-build:x64-windows --binarysource=clear
```

If the problem persists, please make sure your network is smooth and the proxy is available.

**Comment by 7vidhan** [comment]
@MonicaLiu0311 Thank you, it worked.
There were no network issues and the proxy setting was set available.
I got errors because my ISP blocked it, but VPN did the job.
