### ISSUE TITLE
[vtk] build failure with vcpkg

### ISSUE THREAD

**Issue by xzhao99** [microsoft/vcpkg#30002]
**Host Environment**

- OS: Laptop, WSL Linux, Ubuntu 22.04.2 LTS
- Compiler: gcc/g++  11.3.0

**To Reproduce**

`./vcpkg install vtk[core]`

**Failure logs**

Computing installation plan...
The following packages will be built and installed:
    vtk[core]:x64-linux -> 9.2.0-pv5.11.0#4
Detecting compiler hash for triplet x64-linux...
Restored 0 package(s) from /home/xzhao/.cache/vcpkg/archives in 10.05 us. Use --debug to see more details.
Installing 1/1 vtk:x64-linux...
Building vtk[core]:x64-linux...
CMake Warning at ports/vtk/portfile.cmake:3 (message):
  You will need to install Xorg dependencies to build vtk:

  apt-get install libxt-dev

Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)

-- Using cached vtk-string-bfa3e4.diff.
-- Using cached Kitware-VTK-66143ef041b980a51e41ee470d053e67209150f8.tar.gz.
-- Cleaning sources at /home/xzhao/workdir/vcpkg/buildtrees/vtk/src/67209150f8-d445939f42.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/xzhao/workdir/vcpkg/downloads/Kitware-VTK-66143ef041b980a51e41ee470d053e67209150f8.tar.gz
-- Applying patch FindLZMA.patch
-- Applying patch FindLZ4.patch
-- Applying patch Findproj.patch
-- Applying patch pegtl.patch
-- Applying patch pythonwrapper.patch
-- Applying patch NoUndefDebug.patch
-- Applying patch fix-using-hdf5.patch
-- Applying patch FindExpat.patch
-- Applying patch cgns.patch
-- Applying patch vtkm.patch
-- Applying patch afxdll.patch
-- Applying patch vtkioss.patch
-- Applying patch jsoncpp.patch
-- Applying patch iotr.patch
-- Applying patch /home/xzhao/workdir/vcpkg/downloads/vtk-string-bfa3e4.diff
-- Applying patch 9690.diff
-- Using source at /home/xzhao/workdir/vcpkg/buildtrees/vtk/src/67209150f8-d445939f42.clean
-- Configuring x64-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /home/xzhao/workdir/vcpkg/downloads/tools/ninja/1.10.2-linux/ninja -v
    Working Directory: /home/xzhao/workdir/vcpkg/buildtrees/vtk/x64-linux-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      /home/xzhao/workdir/vcpkg/buildtrees/vtk/config-x64-linux-dbg-CMakeCache.txt.log
      /home/xzhao/workdir/vcpkg/buildtrees/vtk/config-x64-linux-rel-CMakeCache.txt.log
      /home/xzhao/workdir/vcpkg/buildtrees/vtk/config-x64-linux-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:248 (vcpkg_execute_required_process)
  ports/vtk/portfile.cmake:203 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)

error: building vtk:x64-linux failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+vtk
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[vtk]+Build+error
Include '[vtk] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-02-16-12e657924d99511514c0287ca5ce46882d3657c7
    vcpkg-scripts version: 64fabc940 2023-03-02 (12 hours ago)

Please use the prefilled template from /home/xzhao/workdir/vcpkg/installed/vcpkg/issue_body.md when reporting your issue.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by xzhao99** [comment]
run ``` sudo apt-get install libxt-dev```, installed the lib. Re-run vcpkg install, it still fails with the same building errors.

**Comment by JonLiu1993** [comment]
@xzhao99, Thanks for posting this issue, I can't repo your error on my linux mahcine:
````
-- Applying patch afxdll.patch
-- Applying patch vtkioss.patch
-- Applying patch jsoncpp.patch
-- Applying patch iotr.patch
-- Applying patch /home/vzhli17/vcpkg/downloads/vtk-string-bfa3e4.diff
-- Applying patch 9690.diff
-- Using source at /home/vzhli17/vcpkg/buildtrees/vtk/src/67209150f8-d445939f42
-- Configuring x64-linux
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Installing: /home/vzhli17/vcpkg/packages/vtk_x64-linux/tools/vtk/vtkWrapPythonInit-9.2
-- Installing: /home/vzhli17/vcpkg/packages/vtk_x64-linux/tools/vtk/vtkWrapPython-9.2
-- Installing: /home/vzhli17/vcpkg/packages/vtk_x64-linux/tools/vtk/vtkWrapJava-9.2
-- Installing: /home/vzhli17/vcpkg/packages/vtk_x64-linux/tools/vtk/vtkWrapHierarchy-9.2
-- Installing: /home/vzhli17/vcpkg/packages/vtk_x64-linux/tools/vtk/vtkParseJava-9.2
-- Installing: /home/vzhli17/vcpkg/packages/vtk_x64-linux/tools/vtk/vtkProbeOpenGLVersion-9.2
-- Installing: /home/vzhli17/vcpkg/packages/vtk_x64-linux/share/vtk/copyright
-- Performing post-build validation
Elapsed time to handle vtk:x64-linux: 27.89 min
Total install time: 40.16 min
The package vtk provides CMake targets:

    find_package(VTK REQUIRED)
    include("${VTK_USE_FILE}")
    target_link_libraries(main PRIVATE ${VTK_LIBRARIES})

````
could you please provide this error log?
````
/home/xzhao/workdir/vcpkg/buildtrees/vtk/config-x64-linux-out.log
````

**Comment by xzhao99** [comment]
Hi @JonLiu1993,

Please see the file attached. It seems like something wrong with ninja.
[config-x64-linux-out.log](https://github.com/microsoft/vcpkg/files/10899705/config-x64-linux-out.log)

I noticed vcpkg dowload the most recent ninja into the download/tools/ninja (--version 1.10.2), and the version check with "-v" failed. This is just from my screen print information, may not be the root cause. Thank you very much for your help.

![image](https://user-images.githubusercontent.com/8794047/223153290-4c3cdf48-cb38-4261-9207-9e4b05547dc5.png)

**Comment by dg0yt** [comment]
Your log is quite clear:
~~~
CMake Error at ThirdParty/hdf5/CMakeLists.txt:21 (message):
  An external MPI-aware HDF5 requires that VTK be built with MPI support as
  well.
~~~
So either don't install the `parallel` feature of port `hdf5`, or install `vtk[mpi]`.

Until I have feedback on #29724 and/or #29731.

**Comment by xzhao99** [comment]
@dg0yt @JonLiu1993 
This does solve my problems. Sorry that I just missed the MPI error message. Thank you again for your help.
