### ISSUE TITLE
[New Port Request] rdkit

### ISSUE THREAD

**Issue by j-horner-c4x** [microsoft/vcpkg#30007]
Library name: rdkit

Library description: RDKit is a collection of cheminformatics and machine-learning software written in C++ and Python.

Source repository URL: https://github.com/rdkit/rdkit

Project homepage (if different from the source repository):  https://www.rdkit.org/docs/index.html

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
 - requires Boost 1.58 and is not obviously overridable

**Comment by LuigiPagani** [comment]
It would be wxtremely useful

**Comment by j-horner-c4x** [comment]
This would still be useful to have if possible.

**Comment by LuigiPagani** [comment]
👀

**Comment by j-horner-c4x** [comment]
👀
