### ISSUE TITLE
Test for MSVC(-ish toolchains) fails in `vcpkg_configure_make`

### ISSUE THREAD

**Issue by jre-lsft** [microsoft/vcpkg#30009]
While investigating #29983, I happened to notice that there is an `if` clause in the macro `z_vcpkg_setup_make_linker_flags_vars` that matches `VCPKG_DETECTED_CMAKE_C_COMPILER_ID` with `cl\.exe$`:
https://github.com/microsoft/vcpkg/blob/39f3c5c343b71069c7e7197d1ad9ea288e2076e1/scripts/cmake/vcpkg_configure_make.cmake#L662

However, this condition should never actually evaluate to `true`, because `VCPKG_DETECTED_CMAKE_C_COMPILER_ID` is supposed to contain the same range of values as [`CMAKE_C_COMPILER_ID`](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_ID.html).
Looks like it used to be `VCPKG_DETECTED_CMAKE_C_COMPILER`, but was changed in 624f1b4ecaf652e074f4cc547f9a4679a28d2222.
Unfortunately, I haven't been able to dig up the motivation for this change, maybe it's just a typo?

I won't open a pull request at this time because I want to double-check if the intention of this change was to exclude toolchains pretending to be MSVC, like `clang-cl`.
In other words: should it be `VCPKG_DETECTED_CMAKE_C_COMPILER MATCHES [[cl\.exe$]]` or `VCPKG_DETECTED_CMAKE_C_COMPILER_ID STREQUAL "MSVC"`?
It seems that Clang's `lld-link` supports `_LINK_`, which is the environment variable that is ultimately controlled by the condition in question (haven't actually tested this though).
If this is in fact just a typo, and the condition is supposed to evaluate to `true` for toolchains pretending to be MSVC, wouldn't it be, and this is just a thought, an option to extend `z_vcpkg_get_cmake_vars` to provide the value of [`MSVC`](https://cmake.org/cmake/help/latest/variable/MSVC.html)?

Another thing to consider is consistency: other conditions involving `VCPKG_DETECTED_CMAKE_C_COMPILER` seem to test for `MATCHES "cl.exe"` (note that the `.` is not escaped and the expression is not anchored).

Please note that the above is just an observation from reading the source code, I have not done any further research or practical tests to evaluate its impact.

**Comment by JackBoosY** [comment]
cc @Neumann-A

**Comment by JackBoosY** [comment]
`cl.exe` is for mingW build.
