### ISSUE TITLE
[fftwpp] Improve Integration/Documentation

### ISSUE THREAD

**Issue by natecheadle** [microsoft/vcpkg#30010]
****

**Is your feature request related to a problem? Please describe.**
fftwpp is not truly a header only project and requires you manually build fftw++.cc (or other files depending on the features you want to use.)

vcpkg places these files in the include directory so you have access to them but there is no documentation that you need to build them manually.

**Proposed solution**
Ideal solution is that vcpkg builds these files into a static or dynamic library that I can automatically link to.

**Describe alternatives you've considered**
The way I got around this was adding a cpp file to my project that included the implementation files.

ex. #include <fftwpp/fftw++.cc>

(You also have to define _CRT_SECURE_NO_WARNINGS, but that isn't a vcpkg issue)

This is sort of an ugly solution, but was the easiest way I could see getting around files that needed to be built to use the port without manually copying files into my project.

**Additional context**
My guess is that it is out of scope for vcpkg to build these files, so probably updating the documentation for the port is the best solution. 

For example the current output after install is:
fftwpp is header-only and can be used from CMake via:

    find_path(FFTWPP_INCLUDE_DIRS "fftwpp/Array.cc")
    target_include_directories(main PRIVATE ${FFTWPP_INCLUDE_DIRS})

I am not using cmake so can't easily test this, but with Visual Studio integration it doesn't work to simply include the header file.

**Comment by jimwang118** [comment]
Sorry, the upstream of this port only provides the source code, not the compilation process. We are also unable to provide compilation for the time being, and currently need to use the method provided below. 
```
find_path(FFTWPP_INCLUDE_DIRS "fftwpp/Array.cc")
target_include_directories(main PRIVATE ${FFTWPP_INCLUDE_DIRS})
```

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
