### ISSUE TITLE
CMake integration stop working when "CMAKE_TOOLCHAIN_FILE" is replaced with "toolchainFile" (as recommended for presets version 3 or above)

### ISSUE THREAD

**Issue by netcorefan1** [microsoft/vcpkg#30018]
**Describe the bug**
In VSCODE I get the following message when using "CMAKE_TOOLCHAIN_FILE" in a preset file:
`Use "toolchainFile" property instead when using presets version 3 or higher`. Tne CMake [documentation](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html#manual:cmake-presets(7)) also states about this option for such presets versions. 

![vscode](https://user-images.githubusercontent.com/63934725/222903690-b22fb70d-b6e5-45e2-ba4f-2b5012ca71a3.png)

However, when I do this, the linkage does not work anymore and it's just like passing an empty string. 

**Environment**
- OS: Windows 11
- Compiler: MSVC vc143

**To Reproduce**
In a CMake preset file (version higher than 3) replace:
```
{
    "version": 6,
    "configurePresets": [
        {
            "name": "x64-release",
            "cacheVariables": {
                "CMAKE_TOOLCHAIN_FILE": "<VCPKG_ROOT>/scripts/buildsystems/vcpkg.cmake",
                "CMAKE_BUILD_TYPE": "Release"
            }
        }
    ]
}
```
With:
```
{
    "version": 6,
    "toolchainFile": "<VCPKG_ROOT>/scripts/buildsystems/vcpkg.cmake",
    "configurePresets": [
        {
            "name": "x64-release",
            "cacheVariables": {
                "CMAKE_BUILD_TYPE": "Release"
            }
        }
    ]
}
```

**Expected behavior**
The same behavior of "CMAKE_TOOLCHAIN_FILE"'.

**Failure logs**
Even in debug mode, cmake Log does not show anything related to the tool chain file, but the issue is immediately noticeable from plenty of "not found" errors which does not happens when "CMAKE_TOOLCHAIN_FILE" is used.

**Additional context**
I'm just ignoring and continuing to use "CMAKE_TOOLCHAIN_FILE", but I wanted to report such issue because there must be a valid reason if they recommend to switch from "CMAKE_TOOLCHAIN_FILE" to "toolchainFile" property.

**Comment by dg0yt** [comment]
I think `vcpkg` is the wrong repository to report this VS Code (CMake plugin?) issue.

**Comment by netcorefan1** [comment]
I was not sure on where to report this, but I decided here because even without Vs code and its CMake plugin, the issue persists. May be vcpkg has not the required implementation to handle a "toolchainFile" property?

**Comment by dg0yt** [comment]
vcpkg itself "handles" none of it. AFAICS it is CMake, and the documentation you linked indicates that `toolchainFile` is a json property which belongs  to the `configurePresets` array.
So your example should be (untested):
~~~
{
    "version": 6,
    "configurePresets": [
        {
            "name": "x64-release",
            "toolchainFile": "<VCPKG_ROOT>/scripts/buildsystems/vcpkg.cmake",
            "cacheVariables": {
                "CMAKE_BUILD_TYPE": "Release"
            }
        }
    ]
}
~~~
