### ISSUE TITLE
[sdl2-mixer] installed but the target was not found

### ISSUE THREAD

**Issue by e7** [microsoft/vcpkg#30026]
**Describe the bug**
I installed sdl2pp，it depends on sdl2-mixer, so install it but cmake failed on macos and linux, windows works fine.

**Environment**
- OS: macos 12.6, ubuntu 20.04
- Compiler: gcc

**To Reproduce**
1. ./vcpkg install sdl2-mixer sdl2pp sdl2
2. write demo use sdl2pp
3. cmake -S . -B cmake-build-debug
4. see error

**Expected behavior**

**Failure logs**
Target "demo" links to target "SDL2_mixer::SDL2_mixer" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

**Additional context**

**Comment by jimwang118** [comment]
You should use a command like this to compile:`cmake -DCMAKE_TOOLCHAIN_FILE=/app/vcpkg/scripts/buildsystems/vcpkg.cmake CMakeLists.txt`. In the command you need to set the direct `DCMAKE_TOOLCHAIN_FILE `path.

**Comment by e7** [comment]
I use this in my CMakeLists.txt
`cmake_minimum_required(VERSION 3.16)

if(DEFINED ENV{VCPKG_ROOT} AND NOT DEFINED CMAKE_TOOLCHAIN_FILE)
    set(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
            CACHE STRING "")
endif()`

and also tried your way, still not work, other dependencies is ok except sdl2-mixer

**Comment by e7** [comment]
-- The C compiler identification is AppleClang 14.0.0.14000029
-- The CXX compiler identification is AppleClang 14.0.0.14000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: optimized;/xxx/vcpkg/installed/x64-osx/lib/libz.a;debug;/xxx/vcpkg/installed/x64-osx/debug/lib/libz.a (found version "1.2.13")
-- Found PNG: optimized;/xxx/vcpkg/installed/x64-osx/lib/libpng16.a;debug;/xxx/vcpkg/installed/x64-osx/debug/lib/libpng16d.a (found version "1.6.38")
-- Found Freetype: optimized;/xxx/vcpkg/installed/x64-osx/lib/libfreetype.a;debug;/xxx/vcpkg/installed/x64-osx/debug/lib/libfreetyped.a (found version "2.12.1")
-- Found BZip2: optimized;/xxx/vcpkg/installed/x64-osx/lib/libbz2.a;debug;/xxx/vcpkg/installed/x64-osx/debug/lib/libbz2d.a (found version "1.0.8")
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found SDL2PP: /xxx/vcpkg/installed/x64-osx/include
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Configuring done
CMake Error at CMakeLists.txt:43 (target_link_libraries):
  Target "kunf_sdl" links to:

    SDL2_mixer::SDL2_mixer

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.



-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by jimwang118** [comment]
> I use this in my CMakeLists.txt `cmake_minimum_required(VERSION 3.16)
> 
> if(DEFINED ENV{VCPKG_ROOT} AND NOT DEFINED CMAKE_TOOLCHAIN_FILE) set(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake" CACHE STRING "") endif()`
> 
> and also tried your way, still not work, other dependencies is ok except sdl2-mixer

You can add a `massage("xxxxx")` inside the `if()` to make sure `CMAKE_TOOLCHAIN_FILE` is indeed set when compiling.

**Comment by e7** [comment]
Yes, `CMAKE_TOOLCHAIN_FILE ` is set properly. And I found that only use sdl2 and sdl2-xxx stuffs, every thing is fine, when using sdl2pp, that error appears again.
`#target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE ${SDL2PP_LIBRARIES})`
`target_link_libraries(main PRIVATE SDL2::SDL2 SDL2::SDL2main SDL2::SDL2-static)`
`target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE $<IF:$<TARGET_EXISTS:SDL2_mixer::SDL2_mixer>,SDL2_mixer::SDL2_mixer,SDL2_mixer::SDL2_mixer-static>)`
