### ISSUE TITLE
[gettext] build failure

### ISSUE THREAD

**Issue by Sharpe49** [microsoft/vcpkg#30025]
GetText build is failing at the start of the building phase with an autoconf syntax error (on AC_SUBST).

autoconf, automake, autoconf-archive, libtool and m4 have been installed with homebrew.
I don't know if I am missing any other tool.

**Host Environment**

- OS: macOS 11.7.4
- Compiler: Clang 13.0

**To Reproduce**

`./vcpkg install gettext`

**Failure logs**

> Building gettext[core]:x64-osx...
> -- Using cached gettext-0.21.1.tar.gz.
> -- Extracting source /Volumes/ExtremeSSD/actions-runner/_work/altitude/altitude/vcpkg/downloads/gettext-0.21.1.tar.gz
> -- Applying patch android.patch
> -- Applying patch uwp.patch
> -- Applying patch win-gethostname.patch
> -- Applying patch 0003-Fix-win-unicode-paths.patch
> -- Applying patch rel_path.patch
> -- Using source at /Volumes/ExtremeSSD/actions-runner/_work/altitude/altitude/vcpkg/buildtrees/gettext/src/gettext-0-de39ca5451.clean
> -- Found external ninja('1.11.1').
> -- Getting CMake variables for x64-osx-dbg
> -- Getting CMake variables for x64-osx-rel
> -- Configuring x64-osx-dbg
> -- Configuring x64-osx-rel
> -- Building x64-osx-dbg
> CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
>     Command failed: /usr/bin/make V=1 -j 5 -f /Volumes/ExtremeSSD/actions-runner/_work/altitude/altitude/vcpkg/ports/gettext/Makefile build-intl
>     Working Directory: /Volumes/ExtremeSSD/actions-runner/_work/altitude/altitude/vcpkg/buildtrees/gettext/x64-osx-dbg/
>     See logs for more information:
>       /Volumes/ExtremeSSD/actions-runner/_work/altitude/altitude/vcpkg/buildtrees/gettext/build-x64-osx-dbg-out.log
>       /Volumes/ExtremeSSD/actions-runner/_work/altitude/altitude/vcpkg/buildtrees/gettext/build-x64-osx-dbg-err.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_build_make.cmake:149 (vcpkg_execute_build_process)
>   scripts/cmake/vcpkg_install_make.cmake:2 (vcpkg_build_make)
>   ports/gettext/portfile.cmake:85 (vcpkg_install_make)
>   ports/gettext/portfile.cmake:134 (build_libintl_only)

>   scripts/ports.cmake:147 (include)

[build-x64-osx-dbg-err.log](https://github.com/microsoft/vcpkg/files/10891317/build-x64-osx-dbg-err.log)
[build-x64-osx-dbg-out.log](https://github.com/microsoft/vcpkg/files/10891318/build-x64-osx-dbg-out.log)
[config-x64-osx-dbg-out.log](https://github.com/microsoft/vcpkg/files/10891319/config-x64-osx-dbg-out.log)

**Comment by dg0yt** [comment]
Any other package managers installed? Can you disclose `PATH`?

**Comment by Sharpe49** [comment]
No. Here's the PATH :

> /usr/local/opt/bison/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Users/IVAO/.local/bin

**Comment by dg0yt** [comment]
Hm, I'm surprised that it re-run confiure during build. This isn't normal.
~~~
/Library/Developer/CommandLineTools/usr/bin/make -C intl all
cd .. && /Library/Developer/CommandLineTools/usr/bin/make  am--refresh
CDPATH="${ZSH_VERSION+.}:" && cd ./../src/gettext-0-de39ca5451.clean/gettext-runtime && /bin/sh '/Volumes/ExtremeSSD/actions-runner/_work/altitude/altitude/vcpkg/buildtrees/gettext/src/gettext-0-de39ca5451.clean/build-aux/missing' autoconf
~~~
And it somehow reads like it considers autoconf missing. Is this an ARM mac?

**Comment by Sharpe49** [comment]
Nope, x86

**Comment by LilyWangLL** [comment]
Could you please check this file _[VCPKG_ROOT]/buildtrees/gettext/src/gettext-0-de39ca5451.clean/Makefile.am_ is exist?
```
automake-1.16: error: no 'Makefile.am' found for any configure output
automake-1.16: Did you forget AC_CONFIG_FILES([Makefile]) in configure.ac?
```

**Comment by Sharpe49** [comment]
Yes, it exists.

**Comment by dg0yt** [comment]
@Abs-nth You are facing a different issue.

**Comment by debangsha-versatile** [comment]
I am getting the same error on Linux:
error: building gettext:x64-linux failed with: BUILD_FAILED
Has anyone ever managed to install COLMAP from source? It doesn't build on Windows or Linux or MacOS for me. 🤬🤬🤬🤬

**Comment by dg0yt** [comment]
> And it somehow reads like it considers autoconf missing

Did you try to install autoconf from brew?
(It may appear unexpecte at this point, but many ports need it. This might explain why the problem doesn't appear e.g. in CI.)
