### ISSUE TITLE
Intel MKL DLLs are not copied to the build folder when dealing with a CMake project

### ISSUE THREAD

**Issue by AdelCraftZ** [microsoft/vcpkg#30036]
**Describe the bug**
Intel MKL DLLs are not copied to the build folder when dealing with a CMake project

**Environment**
- OS: Windows 11
- Compiler: MSVC

**To Reproduce**
1. Install Intel oneMKL from [here](https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl-download.html).
2. ./vcpkg install intel-mkl:windows:x64.
3. Create a CMake project with with MKL (`find_package`, `target_link_libraries`, etc.).
4. Compile and run.

**Expected behavior**
The required MKL DLLs should be automatically copied to the build folder containing the executable, like with any other package.

**Failure logs**
Application crash or reporting missing DLLs.

**Workaround**
For now, I am manually copying the DLLs to the build folder.

**Comment by JonLiu1993** [comment]
Confirmed.
![image](https://user-images.githubusercontent.com/63675417/223075728-8ec7402a-3cea-4b8f-a787-3888b5a8b5f1.png)

**Comment by polortiz4** [comment]
I'm having the same issue

**Comment by FrankXie05** [comment]
Fixed by PR https://github.com/microsoft/vcpkg/pull/29437, it provided the new usage.
