### ISSUE TITLE
[boost-exception] Build error

### ISSUE THREAD

**Issue by vicaren95** [microsoft/vcpkg#30033]
**Host Environment**

- OS: Windows 10
- Compiler: 
**To Reproduce**

./vcpkg install boost-iostreams:x64-windows boost-asio:x64-windows boost-system:x64-windows boost-variant:x64-windows boost-lockfree:x64-windows luajit:x64-windows glew:x64-windows boost-filesystem:x64-windows boost-uuid:x64-windows physfs:x64-windows openal-soft:x64-windows libogg:x64-windows libvorbis:x64-windows zlib:x64-windows opengl:x64-windows

**Failure logs**

```
error: building boost-exception:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-exception
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-exception]+Build+error
Include '[boost-exception] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-02-16-12e657924d99511514c0287ca5ce46882d3657c7
    vcpkg-scripts version: 8daf70c56 2023-03-03 (2 days ago)

```
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/10893233/install-x64-windows-dbg-out.log)

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Did this port provide other log like ***dbg-err.log**? I can't get any error message in your provided log file.
```
[1/2] cmd.exe /C "cd /D C:\vcpkg\buildtrees\boost-exception\x64-windows-dbg && C:\vcpkg\downloads\tools\cmake-3.24.0-windows\cmake-3.24.0-windows-i386\bin\cmake.exe -P cmake_install.cmake"
-- Install configuration: "Debug"
-- Installing: C:/vcpkg/packages/boost-exception_x64-windows/debug/lib/libboost_exception-vc143-mt-gd-x64-1_80.lib

```
And which version of Visual Studio you used?

**Comment by vicaren95** [comment]
All my err.log on that folder are completely empty
[cmake-get-vars-x64-windows-err.log](https://github.com/microsoft/vcpkg/files/10894140/cmake-get-vars-x64-windows-err.log)
[config-x64-windows-err.log](https://github.com/microsoft/vcpkg/files/10894141/config-x64-windows-err.log)
[install-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/10894142/install-x64-windows-dbg-err.log)
[install-x64-windows-rel-err.log](https://github.com/microsoft/vcpkg/files/10894143/install-x64-windows-rel-err.log)

**Comment by LilyWangLL** [comment]
Please provide the log file: **stdout-x64-windows.log**. Thanks.

**Comment by vicaren95** [comment]
[stdout-x64-windows.log](https://github.com/microsoft/vcpkg/files/10901908/stdout-x64-windows.log)
Here it is

**Comment by LilyWangLL** [comment]
> -- Downloading https://github.com/boostorg/exception/archive/boost-1.80.0.tar.gz -> boostorg-exception-boost-1.80.0.tar.gz...
> -- Extracting source C:/vcpkg/downloads/boostorg-exception-boost-1.80.0.tar.gz
> -- Using source at C:/vcpkg/buildtrees/boost-exception/src/ost-1.80.0-dffd4d0ef9.clean
> -- Found external ninja('1.10.2').
> -- Getting CMake variables for x64-windows
> -- Configuring x64-windows
> -- Building x64-windows-dbg
> -- Building x64-windows-rel
> -- Copying headers
> -- Copying headers done
> -- Installing: C:/vcpkg/packages/boost-exception_x64-windows/share/boost-exception/usage
> -- Installing: C:/vcpkg/packages/boost-exception_x64-windows/share/boost-exception/copyright

The log shows you have succeed installed `boost-exception`, I am wondering why there is the above error output. Could you please rebuild `boost-exception`, if it still install failed, please provide the full output on powershell window.

**Comment by vicaren95** [comment]
I wasn't able to rebuild, but I ended up uninstalling the whole vcpkg folder and installing it on another drive, and everything is working correctly now.
