### ISSUE TITLE
error: building detours:x64-windows-static failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by thepoladov13** [microsoft/vcpkg#30048]
**Describe the bug**

**Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
1. ./vcpkg install xxxx
2. See error
Repro code when

**Expected behavior**

**Failure logs**
-(please attached failure logs)

**Additional context**

**Comment by JackBoosY** [comment]
Please provide the **full** output.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
