### ISSUE TITLE
[libiconv] build failure - Package is missing from the download source

### ISSUE THREAD

**Issue by alexiaizenberg** [microsoft/vcpkg#30047]
**Host Environment**

- OS: [windows-server-2019-dc-v20220314 ]
- Compiler: 19.35.32215

**To Reproduce**

`./vcpkg install libiconv` from a **_2021.06.31_** tag 

**Failure logs**

    Computing installation plan...
    The following packages will be built and installed:
      * libiconv[core]:x64-windows -> 1.16#11
        libxml2[core]:x64-windows -> 2.9.12#4
    Additional packages (*) will be modified to complete this operation.
    Detecting compiler hash for triplet x64-windows...
    Restored 0 packages from C:\Windows\system32\config\systemprofile\AppData\Local\vcpkg\archives in 124.1 ms. Use --debug to see more details.
    Starting package 1/2: libiconv:x64-windows
    Building package libiconv[core]:x64-windows...
    -- Downloading https://ftp.gnu.org/gnu/libiconv/libiconv-1.16.tar.gz;https://www.mirrorservice.org/sites/ftp.gnu.org/gnu/libiconv/libiconv-1.16.tar.gz -> libiconv-1.16.tar.gz...
    -- Extracting source C:/vcpkg/downloads/libiconv-1.16.tar.gz
    -- Applying patch 0002-Config-for-MSVC.patch
    -- Applying patch 0003-Add-export.patch
    -- Applying patch 0004-ModuleFileName.patch
    -- Using source at C:/vcpkg/buildtrees/libiconv/src/1.16-b0c41d3469.clean
    -- Getting CMake variables for x64-windows
    -- Downloading https://repo.msys2.org/msys/x86_64/gzip-1.11-1-x86_64.pkg.tar.zst;https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/gzip-1.11-1-x86_64.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/gzip-1.11-1-x86_64.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/gzip-1.11-1-x86_64.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/msys/x86_64/gzip-1.11-1-x86_64.pkg.tar.zst;https://mirror.bit.edu.cn/msys2/msys/x86_64/gzip-1.11-1-x86_64.pkg.tar.zst;https://mirror.selfnet.de/msys2/msys/x86_64/gzip-1.11-1-x86_64.pkg.tar.zst;https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/gzip-1.11-1-x86_64.pkg.tar.zst -> msys-gzip-1.11-1-x86_64.pkg.tar.zst...
    -- Downloading https://repo.msys2.org/msys/x86_64/bash-5.1.008-1-x86_64.pkg.tar.zst;https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/bash-5.1.008-1-x86_64.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/bash-5.1.008-1-x86_64.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/bash-5.1.008-1-x86_64.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/msys/x86_64/bash-5.1.008-1-x86_64.pkg.tar.zst;https://mirror.bit.edu.cn/msys2/msys/x86_64/bash-5.1.008-1-x86_64.pkg.tar.zst;https://mirror.selfnet.de/msys2/msys/x86_64/bash-5.1.008-1-x86_64.pkg.tar.zst;https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/bash-5.1.008-1-x86_64.pkg.tar.zst -> msys-bash-5.1.008-1-x86_64.pkg.tar.zst...
    -- Downloading https://repo.msys2.org/msys/x86_64/autoconf-2.71-3-any.pkg.tar.zst;https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/autoconf-2.71-3-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/autoconf-2.71-3-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/autoconf-2.71-3-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/msys/x86_64/autoconf-2.71-3-any.pkg.tar.zst;https://mirror.bit.edu.cn/msys2/msys/x86_64/autoconf-2.71-3-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/msys/x86_64/autoconf-2.71-3-any.pkg.tar.zst;https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/autoconf-2.71-3-any.pkg.tar.zst -> msys-autoconf-2.71-3-any.pkg.tar.zst...
    -- Downloading https://repo.msys2.org/msys/x86_64/diffutils-3.8-2-x86_64.pkg.tar.zst;https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/diffutils-3.8-2-x86_64.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/diffutils-3.8-2-x86_64.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/diffutils-3.8-2-x86_64.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/msys/x86_64/diffutils-3.8-2-x86_64.pkg.tar.zst;https://mirror.bit.edu.cn/msys2/msys/x86_64/diffutils-3.8-2-x86_64.pkg.tar.zst;https://mirror.selfnet.de/msys2/msys/x86_64/diffutils-3.8-2-x86_64.pkg.tar.zst;https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/diffutils-3.8-2-x86_64.pkg.tar.zst -> msys-diffutils-3.8-2-x86_64.pkg.tar.zst...
    -- Downloading https://repo.msys2.org/msys/x86_64/binutils-2.37-5-x86_64.pkg.tar.zst;https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/binutils-2.37-5-x86_64.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/binutils-2.37-5-x86_64.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/binutils-2.37-5-x86_64.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/msys/x86_64/binutils-2.37-5-x86_64.pkg.tar.zst;https://mirror.bit.edu.cn/msys2/msys/x86_64/binutils-2.37-5-x86_64.pkg.tar.zst;https://mirror.selfnet.de/msys2/msys/x86_64/binutils-2.37-5-x86_64.pkg.tar.zst;https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/binutils-2.37-5-x86_64.pkg.tar.zst -> msys-binutils-2.37-5-x86_64.pkg.tar.zst...
    -- Downloading https://repo.msys2.org/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz;https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz;https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz;https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz;https://mirrors.ustc.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz;https://mirror.bit.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz;https://mirror.selfnet.de/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz;https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz -> msys-libtool-2.4.6-9-x86_64.pkg.tar.xz...
    [DEBUG] Feature flag 'binarycaching' unset
    [DEBUG] Feature flag 'manifests' = off
    [DEBUG] Feature flag 'compilertracking' unset
    [DEBUG] Feature flag 'registries' unset
    [DEBUG] Feature flag 'versions' unset
    [DEBUG] Downloading https://repo.msys2.org/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz
    [DEBUG] Downloading https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz
    [DEBUG] Downloading https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz
    [DEBUG] Downloading https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz
    [DEBUG] Downloading https://mirrors.ustc.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz
    [DEBUG] Downloading https://mirror.bit.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz
    [DEBUG] Download failed -- retrying after 1000 ms.
    [DEBUG] Download failed -- retrying after 2000 ms.
    [DEBUG] Download failed -- retrying after 4000 ms.
    [DEBUG] Downloading https://mirror.selfnet.de/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz
    [DEBUG] Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz
    Error: Failed to download from mirror set:
    https://repo.msys2.org/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: failed: status code 404
    https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: failed: status code 404
    https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: failed: status code 404
    https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: failed: status code 404
    https://mirrors.ustc.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: failed: status code 404
    https://mirror.bit.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: WinHttpSendRequest() failed: 12007
    https://mirror.bit.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: WinHttpSendRequest() failed: 12007
    https://mirror.bit.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: WinHttpSendRequest() failed: 12007
    https://mirror.bit.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: WinHttpSendRequest() failed: 12007
    https://mirror.selfnet.de/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: failed: status code 404
    https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: failed: status code 404
    
    [DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(705)
    [DEBUG] Time in subprocesses: 0 us
    [DEBUG] Time in parsing JSON: 6 us
    [DEBUG] Time in JSON reader: 0 us
    [DEBUG] Time in filesystem: 1608 us
    [DEBUG] Time in loading ports: 0 us
    [DEBUG] Exiting after 14.95 s (14944495 us)
    
    CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. Your proxy's remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

    Call Stack (most recent call first):
      scripts/cmake/vcpkg_download_distfile.cmake:309 (z_vcpkg_download_distfile_show_proxy_and_fail)
      scripts/cmake/vcpkg_acquire_msys.cmake:84 (vcpkg_download_distfile)
      scripts/cmake/vcpkg_acquire_msys.cmake:123 (z_vcpkg_acquire_msys_download_package)
      scripts/cmake/vcpkg_acquire_msys.cmake:233 (z_vcpkg_acquire_msys_declare_package)
      scripts/cmake/vcpkg_configure_make.cmake:307 (vcpkg_acquire_msys)
      ports/libiconv/portfile.cmake:29 (vcpkg_configure_make)
      scripts/ports.cmake:145 (include)
    
    
    Error: Building package libiconv:x64-windows failed with: BUILD_FAILED
    Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
    Then check for known issues at:
      https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libiconv
    You can submit a new issue at:
      https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libiconv]+Build+error
    including:
      package: libiconv[core]:x64-windows -> 1.16#11
        vcpkg-tool version: 2022-02-11-dac008bf9b55ef48e10bcc81e273b97a82bbf72d
        vcpkg-scripts version: b86c0c35b 2022-02-24 (1 year ago)

**Additional context**

libtool-2.4.6-9-x86_64.pkg.tar.xz is missing from the mirrors. Other versions are available not the one that being downloaded.
For example the below screen shot is from `https://repo.msys2.org/msys/x86_64/`

![image](https://user-images.githubusercontent.com/78923316/223210850-a93665ef-3941-453d-af2f-9dfeac286c36.png)

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by StarGate-One** [comment]
You need to run a `git pull` on the vcpkg clone and run `.\bootstrap-vcpkg.bat` to update the vcpkg and its related tools.
You are using a vcpkg clone from over a year ago and the tools have been updated many times since.
The current libtool used by vcpkg is https://repo.msys2.org/msys/x86_64/libtool-2.4.7-3-x86_64.pkg.tar.zst

**Comment by alexiaizenberg** [comment]
Did not help:

    ************* git clone vcpkg start *************
    C:\Program Files\PowerShell\7;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\GooGet;C:\Program Files\Google\Compute Engine\metadata_scripts;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files\PowerShell\7\;C:\Program Files\Google\Compute Engine\sysprep;C:\ProgramData\chocolatey\bin;;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;;C:\ProgramData\chocolatey\bin;;C:\Program Files\Git\bin;C:\Program Files (x86)\Microsoft Visual Studio\2022\
    Cloning into 'vcpkg'...
    Updating files:  15% (1503/9821)
    Updating files:  16% (1572/9821)
    Updating files:  17% (1670/9821)
    Updating files:  18% (1768/9821)
    Updating files:  19% (1866/9821)
    Updating files:  20% (1965/9821)
    Updating files:  21% (2063/9821)
    Updating files:  22% (2161/9821)
    Updating files:  23% (2259/9821)
    Updating files:  24% (2358/9821)
    Updating files:  25% (2456/9821)
    Updating files:  26% (2554/9821)
    Updating files:  27% (2652/9821)
    Updating files:  28% (2750/9821)
    Updating files:  29% (2849/9821)
    Updating files:  30% (2947/9821)
    Updating files:  31% (3045/9821)
    Updating files:  32% (3143/9821)
    Updating files:  32% (3200/9821)
    Updating files:  33% (3241/9821)
    Updating files:  34% (3340/9821)
    Updating files:  35% (3438/9821)
    Updating files:  36% (3536/9821)
    Updating files:  37% (3634/9821)
    Updating files:  38% (3732/9821)
    Updating files:  39% (3831/9821)
    Updating files:  40% (3929/9821)
    Updating files:  41% (4027/9821)
    Updating files:  42% (4125/9821)
    Updating files:  43% (4224/9821)
    Updating files:  44% (4322/9821)
    Updating files:  45% (4420/9821)
    Updating files:  46% (4518/9821)
    Updating files:  47% (4616/9821)
    Updating files:  48% (4715/9821)
    Updating files:  49% (4813/9821)
    Updating files:  50% (4911/9821)
    Updating files:  51% (5009/9821)
    Updating files:  51% (5016/9821)
    Updating files:  52% (5107/9821)
    Updating files:  53% (5206/9821)
    Updating files:  54% (5304/9821)
    Updating files:  55% (5402/9821)
    Updating files:  56% (5500/9821)
    Updating files:  57% (5598/9821)
    Updating files:  58% (5697/9821)
    Updating files:  59% (5795/9821)
    Updating files:  60% (5893/9821)
    Updating files:  61% (5991/9821)
    Updating files:  61% (6068/9821)
    Updating files:  62% (6090/9821)
    Updating files:  63% (6188/9821)
    Updating files:  64% (6286/9821)
    Updating files:  65% (6384/9821)
    Updating files:  66% (6482/9821)
    Updating files:  67% (6581/9821)
    Updating files:  68% (6679/9821)
    Updating files:  69% (6777/9821)
    Updating files:  70% (6875/9821)
    Updating files:  71% (6973/9821)
    Updating files:  72% (7072/9821)
    Updating files:  73% (7170/9821)
    Updating files:  74% (7268/9821)
    Updating files:  75% (7366/9821)
    Updating files:  76% (7464/9821)
    Updating files:  77% (7563/9821)
    Updating files:  78% (7661/9821)
    Updating files:  79% (7759/9821)
    Updating files:  79% (7820/9821)
    Updating files:  80% (7857/9821)
    Updating files:  81% (7956/9821)
    Updating files:  82% (8054/9821)
    Updating files:  83% (8152/9821)
    Updating files:  84% (8250/9821)
    Updating files:  85% (8348/9821)
    Updating files:  86% (8447/9821)
    Updating files:  87% (8545/9821)
    Updating files:  88% (8643/9821)
    Updating files:  89% (8741/9821)
    Updating files:  90% (8839/9821)
    Updating files:  91% (8938/9821)
    Updating files:  92% (9036/9821)
    Updating files:  93% (9134/9821)
    Updating files:  94% (9232/9821)
    Updating files:  95% (9330/9821)
    Updating files:  96% (9429/9821)
    Updating files:  97% (9527/9821)
    Updating files:  98% (9625/9821)
    Updating files:  99% (9723/9821)
    Updating files: 100% (9821/9821)
    Updating files: 100% (9821/9821), done.
    ************* git clone vcpkg end *************
    Switched to a new branch '2021.06.31'
    From https://github.com/Microsoft/vcpkg
     * tag                   2021.06.31 -> FETCH_HEAD
    Already up to date.
    Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2022-02-11/vcpkg.exe -> C:\vcpkg\vcpkg.exe... done.
    Validating signature... done.
    
    Telemetry
    ---------
    vcpkg collects usage data in order to help us improve your experience.
    The data collected by Microsoft is anonymous.
    You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
    passing --disable-metrics to vcpkg on the command line,
    or by setting the VCPKG_DISABLE_METRICS environment variable.
    
    Read more about vcpkg telemetry at docs/about/privacy.md
    Using local portfile versions. To update the local portfiles, use `git pull`.
    No packages need updating.
    Computing installation plan...
    A suitable version of cmake was not found (required v3.21.1). Downloading portable cmake v3.21.1...
    Downloading cmake...
      https://github.com/Kitware/CMake/releases/download/v3.21.1/cmake-3.21.1-windows-i386.zip -> C:\vcpkg\downloads\cmake-3.21.1-windows-i386.zip
    Extracting cmake...
    A suitable version of 7zip was not found (required v19.0.0). Downloading portable 7zip v19.0.0...
    Downloading 7zip...
      https://www.7-zip.org/a/7z1900-x64.msi -> C:\vcpkg\downloads\7z1900-x64.msi
    Extracting 7zip...
    The following packages will be built and installed:
      * boost-algorithm[core]:x64-windows -> 1.78.0
      * boost-align[core]:x64-windows -> 1.78.0
      * boost-any[core]:x64-windows -> 1.78.0
      * boost-array[core]:x64-windows -> 1.78.0

Here is the script:

    git clone https://github.com/Microsoft/vcpkg.git
    Write-Host "************* git clone vcpkg end *************"
    cd c:/vcpkg
    git fetch --all --tags
    git checkout 2021.06.31 -b 2021.06.31 
    git pull origin 2021.06.31
    ./bootstrap-vcpkg.bat
    ./vcpkg.exe update
    ./vcpkg.exe install boost-log --triplet x64-windows
    ....
    shortening the list

**Comment by StarGate-One** [comment]
Doing the `git checkout 2021.06.31 -b 2021.06.31` sets the whole repo back to that commit, including vcpkg scripts and tools, hence all the tools like cmake, 7zip, etc have all been updated to newer versions.
The ports are at the version you want but vcpkg scripts and tools are not.
You may need to use registry or manifest to get the port versions you want and have vcpkg with the most current scripts and tools.
As I only use vcpkg in classic mode, I would not be able to suggest how to setup.
Hopefully someone else can give you help/guidance on setting up vcpkg with manifests and/or registries.

**Comment by Cheney-W** [comment]
@alexiaizenberg 
The main reason for this problem is that the old version of `libtool` on `https://repo.msys2.org/msys/x86_64/` has been removed, resulting in download failure. This is the setting of msys website, there is no effective solution in vcpkg to this problem at present.

In order to workaround this issue, I think you could replace the old version of `libtool` with the new version. The specific operation is as follows:
Manually modify the line 233~237 of `vcpkg\scripts\cmake\vcpkg_acquire_msys.cmake` from 
```
    z_vcpkg_acquire_msys_declare_package(
        URL "https://repo.msys2.org/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz"
        SHA512 b309799e5a9d248ef66eaf11a0bd21bf4e8b9bd5c677c627ec83fa760ce9f0b54ddf1b62cbb436e641fbbde71e3b61cb71ff541d866f8ca7717a3a0dbeb00ebf
        DEPS grep sed coreutils file findutils
    )
```
to 
```
    z_vcpkg_acquire_msys_declare_package(
        URL "https://repo.msys2.org/msys/x86_64/libtool-2.4.7-3-x86_64.pkg.tar.zst"
        SHA512 a202ddaefa93d8a4b15431dc514e3a6200c47275c5a0027c09cc32b28bc079b1b9a93d5ef65adafdc9aba5f76a42f3303b1492106ddf72e67f1801ebfe6d02cc
        DEPS grep sed coreutils file findutils
    )
```
Finally, I want to know why you want to use the old version of vcpkg. If you just want to install the old version of port, you can use [versioning feature](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/users/examples/versioning.getting-started.md) instead of using the old version of vcpkg.
