### ISSUE TITLE
[msmpi] Build error

### ISSUE THREAD

**Issue by DifferentFusion** [microsoft/vcpkg#30043]
**Host Environment**

- OS: Windows 10
- Compiler: revision

**To Reproduce**

1. Run command 'vcpkg install msmpi:x64-windows' in directory of vkpkg

**Failure logs**

error: building msmpi:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.

There weren't any additional log files, so I feel like this issue must have an obvious solution that I'm somehow not seeing.

**Additional context**

I've already ensured I'm using the latest port files, but I still keep getting this error message.

**Comment by alexiaizenberg** [comment]
Have a similar issue

**Comment by StarGate-One** [comment]
I do not know if you have same issue, but my issue installing after creating a new vcpkg clone (note I have many vcpkg instances) where each `<vcpkg-root>\downloads` directory/folder is a symlink `mklink /j D:\vcpkg\downloads D:\vcpkg-downloads` instead of each cloned instance having its own downloads directory/folder. 
I was getting a `msmpi sdk - msi cannot open file - error code 1620`.
I fixed by setting the environment variable  `set VCPKG_DOWNLOADS=D:\vcpkg-downloads` to override vcpkg to not use the symlink in its own tree structure.

**Comment by jimwang118** [comment]
My installation prompt is like this: 
```
Computing installation plan...
The following packages will be built and installed:
    msmpi[core]:x64-windows -> 10.1.12498#4
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\vwangjim\AppData\Local\vcpkg\archives in 46.75 ms. Use --debug to see more details.
Installing 1/1 msmpi:x64-windows...
Building msmpi[core]:x64-windows...
-- Downloading https://download.microsoft.com/download/a/5/2/a5207ca5-1203-491a-8fb8-906fd68ae623/msmpisdk.msi -> msmpisdk-10.1.12498-b0087dfd.msi...
-- Downloading https://download.microsoft.com/download/a/5/2/a5207ca5-1203-491a-8fb8-906fd68ae623/msmpisetup.exe -> msmpisetup-10.1.12498.exe...
CMake Error at ports/msmpi/portfile.cmake:57 (message):
    Could not find:
      C:\Program Files/Microsoft MPI/Bin/mpiexec.exe
    Please install the MSMPI redistributable package before trying to install this port.
    The appropriate installer has been downloaded to:
      E:/vcpkg/downloads/msmpisetup-10.1.12498.exe

Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)


error: building msmpi:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+msmpi
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[msmpi]+Build+error
Include '[msmpi] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 8daf70c56 2023-03-03 (3 days ago)
```
I installed `E:/vcpkg/downloads/msmpisetup-10.1.12498.exe`, and recompiled vcpkg to be normal.
If your installation prompts are different, please provide details.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
