### ISSUE TITLE
[glib] Build error --triplet=x64-osx

### ISSUE THREAD

**Issue by DavidStorm** [microsoft/vcpkg#30069]
**Host Environment**

OS: arm64-ios on macOS Ventura
Compiler: Apple clang version 14.0.0 (clang-1400.0.29.202)
vcpkg-tool version: 2023-02-16-12e657924d99511514c0287ca5ce46882d3657c7
vcpkg-scripts version: 93bb67170 2023-03-04 (3 days ago)warning: exhaustive rename detection was skipped due to too many files.

**To Reproduce**

`./vcpkg install glib --triplet=x64-osx`

**Failure logs**

- Console output:
"CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/python3 /Users/developer/Documents/Projectes-Git/neovcpkg/installed/arm64-osx/tools/meson/meson.py -Dselinux=disabled -Dlibmount=disabled -Dgtk_doc=false -Dinstalled_tests=false -Dlibelf=disabled -Dman=false -Dtests=false -Dxattr=false --buildtype plain --backend ninja --wrap-mode nodownload --native /Users/developer/Documents/Projectes-Git/neovcpkg/scripts/buildsystems/meson/none.txt --libdir lib --cross /Users/developer/Documents/Projectes-Git/neovcpkg/buildtrees/glib/meson-x64-osx-dbg.log -Ddebug=true --prefix /Users/developer/Documents/Projectes-Git/neovcpkg/packages/glib_x64-osx/debug --includedir ../include -Dcmake_prefix_path=['/Users/developer/Documents/Projectes-Git/neovcpkg/installed/x64-osx/debug','/Users/developer/Documents/Projectes-Git/neovcpkg/installed/x64-osx'] /Users/developer/Documents/Projectes-Git/neovcpkg/buildtrees/glib/src/glib-2-8ca74e7d19.clean
    Working Directory: /Users/developer/Documents/Projectes-Git/neovcpkg/buildtrees/glib/x64-osx-dbg
    Error code: 1
    See logs for more information:
      /Users/developer/Documents/Projectes-Git/neovcpkg/buildtrees/glib/config-x64-osx-dbg-meson-log.txt.log
      /Users/developer/Documents/Projectes-Git/neovcpkg/buildtrees/glib/config-x64-osx-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:433 (vcpkg_execute_required_process)
  ports/glib/portfile.cmake:31 (vcpkg_configure_meson)
  scripts/ports.cmake:147 (include)

error: building glib:x64-osx failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+glib
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[glib]+Build+error
Include '[glib] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-02-16-12e657924d99511514c0287ca5ce46882d3657c7
    vcpkg-scripts version: 93bb67170 2023-03-04 (3 days ago)warning: exhaustive rename detection was skipped due to too many files.
warning: you may want to set your diff.renameLimit variable to at least 2350 and retry the command.
"

- Attach ***every failure log file*** mentioned in the console output.
[config-x64-osx-dbg-meson-log.txt.log](https://github.com/microsoft/vcpkg/files/10906963/config-x64-osx-dbg-meson-log.txt.log)
[config-x64-osx-dbg-out.log](https://github.com/microsoft/vcpkg/files/10906970/config-x64-osx-dbg-out.log)

**Additional context**

Executed git pull and vcpkg update without problems.
Previous installation triplet=arm64-osx-dynamic works without problems.
./vcpkg install glib --triplet=arm64-osx-dynamic

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
