### ISSUE TITLE
Assistance required in getting PRs merged into vcpkg

### ISSUE THREAD

**Issue by ArashPartow** [microsoft/vcpkg#30078]
**Describe the bug**
Trying unsuccessfully to get the following PR merged for the last two months: https://github.com/microsoft/vcpkg/pull/29955

There seems to be an implicit cyclic dependency between this library which depends on nothing else other than the C++ standard library and downstream libraries that have ports in vcpkg.

----------------------

Would it be possible to have someone from vcpkg look into this issue. I have tried several times to get a PR through to resolve the VTK side of things, however have not been successful. Suggestions and recommendations from reviewers leave the associated "fix" PR in a worst state: https://github.com/microsoft/vcpkg/pull/30058. I'm sure whatever the correct solution is will be extremely trivial and effortless for the MS wizards to complete.

An alternate solution would be that I can recommend the users that require the https://github.com/microsoft/vcpkg/pull/29955 PR to move off vcpkg for this particular dependency, and when in the future the VTK version requires upgrading in vcpkg, to have that PR resolve this and any other issues.

If there is no forward progress within the next week I'm happy to close this PR: https://github.com/microsoft/vcpkg/pull/30058  👍

**Comment by PhoebeHui** [comment]
Hi @ArashPartow, thank you for your contribution and Sorry for the delay of merging the PR! We will help address the issues in related 2 PRs, please don't open a fresh PR for the changes, our team members are taking look at the PRs and CI blocking issues now, and we'll get back to you soon in the PR.
