### ISSUE TITLE
[openssl] Build error

### ISSUE THREAD

**Issue by chr1stobald** [microsoft/vcpkg#30088]
Package: openssl[core]:x64-linux -> 3.0.8#1

**Host Environment**

- Host: x64-linux
- Compiler: GNU 11.3.1
-    vcpkg-tool version: 2023-03-01-538539c4e364dd6f14f5e36f6704144254845159
    vcpkg-scripts version: 02ad673d3 2023-03-07 (17 hours ago)

**To Reproduce**

`vcpkg install boost`

**Failure logs**

```
-- Using cached openssl-openssl-openssl-3.0.8.tar.gz.
-- Cleaning sources at /home/chouchou/vcpkg/buildtrees/openssl/src/nssl-3.0.8-d9622695f9.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/chouchou/vcpkg/downloads/openssl-openssl-openssl-3.0.8.tar.gz
-- Applying patch disable-install-docs.patch
-- Applying patch script-prefix.patch
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch windows/umul128-arm64.patch
-- Applying patch unix/move-openssldir.patch
-- Applying patch unix/no-empty-dirs.patch
-- Applying patch unix/no-static-libs-for-shared.patch
-- Using source at /home/chouchou/vcpkg/buildtrees/openssl/src/nssl-3.0.8-d9622695f9.clean
openssl requires Linux kernel headers from the system package manager.
   They can be installed on Alpine systems via `apk add linux-headers`.
   They can be installed on Ubuntu systems via `apt install linux-libc-dev`.

-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/bash -c "V=1 ./../src/nssl-3.0.8-d9622695f9.clean/vcpkg/configure  \"/usr/bin/perl\" \"/home/chouchou/vcpkg/buildtrees/openssl/src/nssl-3.0.8-d9622695f9.clean/Configure\" \"linux-x86_64\" \"enable-static-engine\" \"enable-capieng\" \"no-ssl3\" \"no-weak-ssl-ciphers\" \"no-tests\" \"no-shared\" \"no-module\" \"--openssldir=/etc/ssl\" \"--libdir=lib\" \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"--debug\" \"--prefix=/home/chouchou/vcpkg/installed/x64-linux/debug\""
    Working Directory: /home/chouchou/vcpkg/buildtrees/openssl/x64-linux-dbg
    Error code: 2
    See logs for more information:
      /home/chouchou/vcpkg/buildtrees/openssl/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:812 (vcpkg_execute_required_process)
  ports/openssl/unix/portfile.cmake:98 (vcpkg_configure_make)
  ports/openssl/portfile.cmake:60 (include)
  scripts/ports.cmake:147 (include)



```
<details><summary>/home/chouchou/vcpkg/buildtrees/openssl/config-x64-linux-dbg-err.log</summary>

```
+ /usr/bin/perl /home/chouchou/vcpkg/buildtrees/openssl/src/nssl-3.0.8-d9622695f9.clean/Configure linux-x86_64 enable-static-engine enable-capieng no-ssl3 no-weak-ssl-ciphers no-tests no-shared no-module --openssldir=/etc/ssl --libdir=lib --debug --prefix=/home/chouchou/vcpkg/installed/x64-linux/debug
Can't locate FindBin.pm in @INC (you may need to install the FindBin module) (@INC contains: /usr/local/lib64/perl5/5.32 /usr/local/share/perl5/5.32 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /home/chouchou/vcpkg/buildtrees/openssl/src/nssl-3.0.8-d9622695f9.clean/Configure line 15.
BEGIN failed--compilation aborted at /home/chouchou/vcpkg/buildtrees/openssl/src/nssl-3.0.8-d9622695f9.clean/Configure line 15.
```
</details>

**Additional context**

**Comment by dg0yt** [comment]
We can't add all package managers. I recently added Ubuntu here because is referenced in many other ports and because the Alpine example wasn't really a useful hint. Anyways, your issue is unrelated to that.

You need to fix your incomplete perl installation. I already add a check for `IPC::Cmd`, but your installation lacks an even more basic module, `FindBin`. A quick internet search gives:
https://github.com/openssl/openssl/issues/13761
which has
~~~
dnf install perl-FindBin
# or: dnf install perl
~~~

**Comment by silverqx** [comment]
You are right `perl-FindBin` was needed that message about Linux headers is confusing, I'm trying Fedora now and got this issue too. Thx @dg0yt I could never figure this out.

**Comment by Stastez** [comment]
Just ran into this same issue but with `perl-Time-Piece`. May I suggest reconsidering adding the perl dependencies to the dependency printout?

**Comment by dg0yt** [comment]
> the perl dependencies

May I suggest to give use the names? And translate to distro packages?

**Comment by Stastez** [comment]
@dg0yt Naturally!
This is mostly according to https://github.com/openssl/openssl/blob/master/NOTES-PERL.md#general-notes, which says that OpenSSL uses many Perl core modules.

In all three cases I have verified via a clean container that vcpkg OpenSSL builds with the respective package installed.

On Fedora, the `perl` package is supposed to contain all core modules, as required in the above link. I have verified that it contains both `perl-Time-Piece` and `perl-FindBin`.
On Ubuntu, `perl` is the meta-package according to OpenSSL (above link). Funnily enough, I wasn't even able to install the required packages for vcpkg + gcc in the container WITHOUT having `perl` pulled in somewhere.
On Alpine, `perl` also contains the core modules as far as I can tell. At least it contains Time-Piece and FindBin. One more thing of note here: `pkg-config` is called `pkgconf` on Alpine.

**Comment by dg0yt** [comment]
> [Kai Pastor (@dg0yt)](https://github.com/dg0yt) Naturally! This is mostly according to https://github.com/openssl/openssl/blob/master/NOTES-PERL.md#general-notes, which says that OpenSSL uses many Perl core modules.

And even they do not give names apart from `Text::Template`. We know only from failures that IPC::Cmd, FindBin, and now Time(::?)Piece might be required and not be part of a core installation.

> One more thing of note here: `pkg-config` is called `pkgconf` on Alpine.

pkgconf provides pkg-config in every modern distro.

People who use such distros are in a good starting position to create PRs for improving experience with that distro...

**Comment by Stastez** [comment]
The "problem" with Fedora here is that some Perl packages automatically get pulled when installing build dependencies (i.e., the vcpkg dependencies, git or gcc/g++), but not the `perl` metapackage which **is** a full core installation and IPC::Cmd, FindBin and Time::Piece are contained in it.
I understand that maybe people don't want to install 200 MiB of Perl, some of which is not actually necessary for building OpenSSL. However, from what I understand, OpenSSL essentially use anything they want out of the core packages and provide fallbacks for anything not contained therein.
Therefore, I would suggest a message here in vcpkg such as this:

```
You are likely missing a Perl package. You may install your distro's full metapackage or look at the error log to find the specifically missing one.
Metapackage installation:
Ubuntu: apt install perl
Alpine: apk add perl
Fedora: dnf install perl
```

I'm not claiming that this is a perfect solution, but it should help people do the OpenSSL build without having to find this git issue.
