### ISSUE TITLE
Issues using boost-interprocess on UWP

### ISSUE THREAD

**Issue by Tryum** [microsoft/vcpkg#3008]
Not sure if the library should be flagged for not being compatible with UWP, but for now I'm looking for work around about boost-interprocess using CreateFileMapping & MapViewOfFile.

**Comment by NancyLi1013** [comment]
Hi @Tryum, thanks for posting this issue. CreateFileMapping & MapViewOfFile currently don't support UWP. And they can only work on desktop apps. Please refer to the following docs:

[1] https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createfilemappinga#Requirements
[2] https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-mapviewoffile#REquiremnets

If you want to use in UWP, you can use CreateFileMappingFromApp and MapViewOfFileFromApp.
"**In UWP, CreateFileMapping and MapViewOfFile has been replaced by CreateFileMappingFromApp and MapViewOfFileFromApp, and the latter has gained a hideous restriction - suddenly we can’t specify where in the address space we want the mapping anymore!"**
The reference from http://blog.henrikrydgard.com/porting-to-uwp

**Comment by autoantwort** [comment]
I think this question is not vcpkg related
