### ISSUE TITLE
[ArrayFire] build failure

### ISSUE THREAD

**Issue by Bzz2745** [microsoft/vcpkg#30094]
**Host Environment**

- OS:Linux
- Compiler: gcc11.3

**To Reproduce**

`./vcpkg install flashlight-cuda[core,asr,fl,imgclass,lib,lm,objdet]:x64-linux --clean-after-build   `

**Failure logs**

Installing 1/18 arrayfire:x64-linux...
Building arrayfire[core,cpu,cuda,unified]:x64-linux...
-- Using cached arrayfire-arrayfire-d99887ae431fcd58168b653a1e69f027f04d5188.tar.gz.
-- Extracting source /home/bazunzhi/vcpkg/downloads/arrayfire-arrayfire-d99887ae431fcd58168b653a1e69f027f04d5188.tar.gz
-- Applying patch build.patch
-- Applying patch Fix-constexpr-error-with-vs2019-with-half.patch
-- Applying patch fix-dependency-clfft.patch
-- Using source at /home/bazunzhi/vcpkg/buildtrees/arrayfire/src/27f04d5188-e800439fec.clean
-- Using cached arrayfire-threads-b666773940269179f19ef11c8f1eb77005e85d9a.tar.gz.
-- Extracting source /home/bazunzhi/vcpkg/downloads/arrayfire-threads-b666773940269179f19ef11c8f1eb77005e85d9a.tar.gz
-- Using source at /home/bazunzhi/vcpkg/buildtrees/arrayfire/src/7005e85d9a-64aebcce4b.clean
-- Using cached arrayfire-forge-1a0f0cb6371a8c8053ab5eb7cbe3039c95132389.tar.gz.
-- Extracting source /home/bazunzhi/vcpkg/downloads/arrayfire-forge-1a0f0cb6371a8c8053ab5eb7cbe3039c95132389.tar.gz
-- Using source at /home/bazunzhi/vcpkg/buildtrees/arrayfire/src/9c95132389-511398ace8.clean
-- Configuring x64-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /home/bazunzhi/vcpkg/downloads/tools/ninja/1.10.2-linux/ninja -v
    Working Directory: /home/bazunzhi/vcpkg/buildtrees/arrayfire/x64-linux-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      /home/bazunzhi/vcpkg/buildtrees/arrayfire/config-x64-linux-dbg-CMakeCache.txt.log
      /home/bazunzhi/vcpkg/buildtrees/arrayfire/config-x64-linux-rel-CMakeCache.txt.log
      /home/bazunzhi/vcpkg/buildtrees/arrayfire/config-x64-linux-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:248 (vcpkg_execute_required_process)
  ports/arrayfire/portfile.cmake:70 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)

**Additional context**
[config-x64-linux-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10926422/config-x64-linux-rel-CMakeCache.txt.log)

[config-x64-linux-dbg-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10926421/config-x64-linux-dbg-CMakeCache.txt.log)

**Comment by Cheney-W** [comment]
Could you please provide me with `/home/bazunzhi/vcpkg/buildtrees/arrayfire/config-x64-linux-out.log`?

**Comment by drremo1** [comment]
> Could you please provide me with `/home/bazunzhi/vcpkg/buildtrees/arrayfire/config-x64-linux-out.log`? Thank you!

Also have this error. The file log contains this:

[config-x64-linux-out.log](https://github.com/microsoft/vcpkg/files/10942419/config-x64-linux-out.log)

**Comment by Bzz2745** [comment]
> Could you please provide me with `/home/bazunzhi/vcpkg/buildtrees/arrayfire/config-x64-linux-out.log`? Thank you!

Maybe It was cleaned by '--clean-after-build",but after I build without that it appeared:
[config-x64-linux-dbg-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10947497/config-x64-linux-dbg-CMakeCache.txt.log)
[config-x64-linux-out.log](https://github.com/microsoft/vcpkg/files/10947498/config-x64-linux-out.log)
[config-x64-linux-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10947499/config-x64-linux-rel-CMakeCache.txt.log)

**Comment by dg0yt** [comment]
~~~
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_lapack_static_LIBRARY (ADVANCED)
    linked by target "af_cuda_static_cuda_library" in directory /home/bazunzhi/vcpkg/buildtrees/arrayfire/src/27f04d5188-e800439fec.clean/src/backend/cuda
~~~

**Comment by Bzz2745** [comment]
> ```
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> CUDA_lapack_static_LIBRARY (ADVANCED)
>     linked by target "af_cuda_static_cuda_library" in directory /home/bazunzhi/vcpkg/buildtrees/arrayfire/src/27f04d5188-e800439fec.clean/src/backend/cuda
> ```

So what should I do to solve this issue?

**Comment by seanfarley** [comment]
FWIW, I have this exact same error. Is this an arrayfire issue? Should `CUDA_lapack_static_LIBRARY` be `CUDA_cusolver_static_LIBRARY`?

**Comment by Bzz2745** [comment]
> FWIW, I have this exact same error. Is this an arrayfire issue? Should `CUDA_lapack_static_LIBRARY` be `CUDA_cusolver_static_LIBRARY`?

I am also waiting for fixing this bug but now nobady ansower this, maybe we can have a try

**Comment by BillyONeal** [comment]
This is https://github.com/arrayfire/arrayfire/issues/3349 , please follow up with arrayfire folks.
