### ISSUE TITLE
[glog] Problems when using a glog installed in vcpkg with a shared library in cmake.

### ISSUE THREAD

**Issue by recsater** [microsoft/vcpkg#30112]
I created a simple example.

### Environments

OS: Ubuntu 22.04, 20.04 x86_64

### Command

```bash
$ vcpkg install glog
$ mkdir build && cd build
$ cmake ..
$ make -j
$ ./capture
```

### Result
```bash
ERROR: something wrong with flag 'timestamp_in_logfile_name' in file '/vcpkg/buildtrees/glog/src/v0.6.0-1e4356b0ac.clean/src/logging.cc'.  One possibility: file '/vcpkg/buildtrees/glog/src/v0.6.0-1e4356b0ac.clean/src/logging.cc' is being linked both statically and dynamically into this executable.
```

### Files

CMakeLists.txt (You may need to change CMAKE_TOOLCHAIN_FILE)
```cmake
cmake_minimum_required(VERSION 3.16)
set(CMAKE_TOOLCHAIN_FILE /vcpkg/scripts/buildsystems/vcpkg.cmake CACHE STRING "Vcpkg toolchain file")
project(scanner LANGUAGES CXX)
set(CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_MODULE_PATH})
set(CMAKE_VERBOSE_MAKEFILE no)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_FLAGS "-g -O3 -DNDEBUG -fPIC")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-deprecated-declarations")  # Ceres v2.1

add_library(t3 SHARED t3.cc)

find_package(glog CONFIG REQUIRED)

target_link_libraries(t3 glog::glog)

add_executable(capture test.cc)
target_link_libraries(capture t3)

set(INSTALL_TARGETS capture)

install(
        TARGETS capture
        DESTINATION .)
```
test.cc
```cpp
#include <glog/logging.h>
int main(int argc, char** argv) {

    google::ParseCommandLineFlags(&argc, &argv, true);
    google::InitGoogleLogging(argv[0]);
    return 0;
}
```
t3.cc
```cpp
#include "glog/logging.h"

class Capture2 {
};

void test(Capture2 *out) {
    CHECK_NOTNULL(out);
}
```

If you try any of the following, no error occurs:
1. Remove SHARED from cmake
2. Replace out with any string in CHECK_NOTNULL(out) in t3.cc file
3. Remove either Google::ParseCommandLineFlags or Google::InitGoogleLogging from the test.cc file

I want t3 to be a shared library How shall I do it?

**Comment by FrankXie05** [comment]
You need to do this for your `CMakeLists.txt`:

```
add_library(t3 SHARED t3.cc)
add_executable(capture test.cc)

find_package(glog CONFIG REQUIRED)
target_link_libraries(capture PRIVATE glog::glog)
target_link_libraries(t3 PRIVATE glog::glog)

set(INSTALL_TARGETS capture)

install(
        TARGETS capture
        DESTINATION .)
```

**Comment by recsater** [comment]
> You need to do this for your `CMakeLists.txt`:
> 
> ```
> add_library(t3 SHARED t3.cc)
> add_executable(capture test.cc)
> 
> find_package(glog CONFIG REQUIRED)
> target_link_libraries(capture PRIVATE glog::glog)
> target_link_libraries(t3 PRIVATE glog::glog)
> 
> set(INSTALL_TARGETS capture)
> 
> install(
>         TARGETS capture
>         DESTINATION .)
> ```

Have you tried it? There's still an error.

**Comment by dg0yt** [comment]
> ```shell
> $ vcpkg install glog

This creates files in `installed/<triplet>`

> ```shell
> $ mkdir build && cd build
> $ cmake ..

How does cmake know to use `../scripts/buildsystems/vcpkg.cmake`? Without the toolchain, cmake may pick libs from your system, but not from `../installed/<triplet>`.

> ```shell
> $ make -j

Unlimited concurrency. Don't try this on a real project.

**Comment by recsater** [comment]
> ```cmake
> cmake_minimum_required(VERSION 3.16)
> set(CMAKE_TOOLCHAIN_FILE /vcpkg/scripts/buildsystems/vcpkg.cmake CACHE STRING "Vcpkg toolchain file")
> ```


Take a closer look at my CMakeLists.txt. I'm setting the path to the toolchain file at the top.

```cmake
cmake_minimum_required(VERSION 3.16)
set(CMAKE_TOOLCHAIN_FILE /vcpkg/scripts/buildsystems/vcpkg.cmake CACHE STRING "Vcpkg toolchain file")
...
```

**Comment by trileyinvicro** [comment]
@recsater I'm running into this as well with the `ceres` library (which depends on `glog`). Were you able to fix it?

**Comment by PHILO-HE** [comment]
I encountered this issue recently. In our case,  glog is statically linked to both libA.so & libB.so. And libB.so is dynamically linked to libA.so. Then, a runtime error is reported: xxx is being linked both statically and dynamically into this executable. I use `--version-script` to make glog symbols local-visible during linking to libB.so.
In the CMakeLists.txt for libB, the below is added.
```
  target_link_options(gluten PRIVATE -Wl,--version-script=${CMAKE_CURRENT_SOURCE_DIR}/symbols.map)
```
A file named symbols.map needs to be created to tell linker which symbols are global and which symbols are local. Here is an example.

```
{
  global:
    extern "C++" {
      *protobuf::*;
      *substrait::*;
    };

  local:
    extern "C++" {
      # Hide symbols of glog, gflags (protobuf is made global at above).
      *google::*;
      fL*::FLAGS_*;
      gflags_mutex_namespace::*;
      glog_internal_namespace_::*;
    };
};
```
