### ISSUE TITLE
error: Unrecognized identifer name xbox. Add to override list in triplet file.

### ISSUE THREAD

**Issue by cnSchwarzer** [microsoft/vcpkg#30122]
It will gone after `git pull + ./bootstrap.bat`, however, I just leave this issue here. Shouldn't it force user to bootstrap vcpkg.exe?

**Comment by JonLiu1993** [comment]
@cnSchwarzer, Thanks for posting this issue, could you give steps to reproduce your error? Forgive me for not fully understanding your question.

**Comment by JonLiu1993** [comment]
@cnSchwarzer, Are you referring to this error?
````
PS F:\test\vcpkg> ./vcpkg install qtdeclarative --editable
Computing installation plan...
error: Unrecognized identifer name xbox. Add to override list in triplet file.
error: Unrecognized identifer name xbox. Add to override list in triplet file.
error: Unrecognized identifer name xbox. Add to override list in triplet file.
error: Unrecognized identifer name xbox. Add to override list in triplet file.
The following packages will be built and installed:
````

**Comment by cnSchwarzer** [comment]
Yes

**Comment by walbourn** [comment]
That error should not as long as you are using vcpkg.exe versioned 2023-02-16 or later. [this PR](https://github.com/microsoft/vcpkg/pull/29664).

Next time you hit it, try `vcpkg --version`` to see what version is running.

**Comment by JonLiu1993** [comment]
@cnSchwarzer, This issue has been resolved, and using the current version will no longer produce these error.
