### ISSUE TITLE
Versioning overrides do not work as documented for recently added ports

### ISSUE THREAD

**Issue by sakra** [microsoft/vcpkg#30120]
**Describe the bug**
When using an "overrides" entry for a recently added port, vcpkg does not find the dependency in the baseline.

**Environment**
- OS: macOS
- Compiler: Xcode 14.2
- vcpkg tool version 2023-03-01-538539c4e364dd6f14f5e36f6704144254845159

**To Reproduce**
Using manifest mode, I have a vcpkg-configuration with the following contents:

    {
        "default-registry": {
            "kind": "builtin",
            "baseline": "2023.02.24"
        }
    }

I tried to add the recently added port `x86-simd-sort` to my project in the `vcpkg.json` dependencies.  Upon running, vcpkg gives me error message:

    -- Running vcpkg install
    Cannot resolve a minimum constraint for dependency x86-simd-sort from helloworld:x64-osx.
    The dependency was not found in the baseline, indicating that the package did not exist at that time. This may be fixed by providing an explicit override version via the "overrides" field or by updating the baseline.
    See `vcpkg help versioning` for more information.
    -- Running vcpkg install - failed

This seem reasonable, as the port was not available in the baseline release "2023.02.24". Thus I added an overrides section to my `vcpkg.json`:

    "overrides": [
         { "name": "x86-simd-sort", "version": "2023-03-04" }
    ]

Running vcpkg install again then results in the following error:

    -- Running vcpkg install
    error: the baseline does not contain an entry for port x86-simd-sort
    -- Running vcpkg install - failed

**Expected behavior**

vcpkg should obey the version override and perform the installation of the specified version.

**Failure logs**

**Additional context**

**Comment by FrankXie05** [comment]
@sakra Please add the `baseline` and `builtin-baseline`. see https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/users/registries.md

**Comment by sakra** [comment]
According to the documentation https://learn.microsoft.com/en-us/vcpkg/reference/vcpkg-json#builtin-baseline
adding a `builtin-baseline` has the same effect as having a default-registry in `vcpkg-configuration`, which I have.

**Comment by FrankXie05** [comment]
Follow the standard format if you are looking for libraries in the vcpkg public admin registry. :) https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/users/registries.md?plain=1
eg:
```
{
  "default-registry": {
    "kind": "git",
    "repository": "https://internal/mirror/of/github.com/Microsoft/vcpkg",
    "baseline": "cfdeb75bb67fee475b517a2f45d8f93f2b46bdb4"
  },
 ```
 If you use the manifest mode, please output the value of baseline correctly, which represents the latest submission number of vcpkg.
 eg:
 ```
 {
  "default-registry": {
    "kind": "builtin",
    "baseline": "cfdeb75bb67fee475b517a2f45d8f93f2b46bdb4"
  }
}
 ```
`cfdeb75bb67fee475b517a2f45d8f93f2b46bdb4`: Make sure this commit contains the libraries you requested to download.
https://github.com/microsoft/vcpkg/commit/cfdeb75bb67fee475b517a2f45d8f93f2b46bdb4
