### ISSUE TITLE
[<vcpkg.cmake>] compile miniocpp but cmake failed

### ISSUE THREAD

**Issue by xuyiqun-learner** [microsoft/vcpkg#30133]
**Host Environment**

- OS: [Win10-WSL1-Ubuntu20.04.5]
- Compiler: gcc-9.4.0

**To Reproduce**

`git clone https://github.com/minio/minio-cpp`
`cd minio-cpp`
`wget --quiet -O vcpkg-master.zip https://github.com/microsoft/vcpkg/archive/refs/heads/master.zip`
`unzip -qq vcpkg-master.zip`
`./vcpkg-master/bootstrap-vcpkg.sh`
`./vcpkg integrate install`
`cmake -B ./build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=./vcpkg-master/scripts/buildsystems/vcpkg.cmake`

**Failure logs**
-- Running vcpkg install
-- Running vcpkg install - failed
CMake Error at vcpkg-master/scripts/buildsystems/vcpkg.cmake:892 (message):
  vcpkg install failed.  See logs for more information:
  /home/xyq/minio-cpp/build/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:16 (project)

CMake Warning (dev) in vcpkg-master/scripts/buildsystems/vcpkg.cmake:
  Policy CMP0011 is not set: Included scripts do automatic cmake_policy PUSH
  and POP.  Run "cmake --help-policy CMP0011" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  The included script
    /home/xyq/minio-cpp/vcpkg-master/scripts/buildsystems/vcpkg.cmake
  affects policy settings.  CMake is implying the NO_POLICY_SCOPE option for
  compatibility, so the effects are applied to the including context.
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:16 (project)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!

**Additional context**
I am sure that I had install nessary development tool. like 'make build-essential tar curl zip unzip ninja' and so on
I try set CMAKE_MAKE_PROGRAM in the CMakeCache.txt(build), but still failed (CMAKE_BUILD_PROGRAM=/usr/bin/make)
Output log:
-- Running vcpkg install
-- Running vcpkg install - failed
CMake Error at vcpkg-master/scripts/buildsystems/vcpkg.cmake:892 (message):
  vcpkg install failed.  See logs for more information:
  /home/xyq/minio-cpp/build/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:16 (project)

CMake Warning (dev) in vcpkg-master/scripts/buildsystems/vcpkg.cmake:
  Policy CMP0011 is not set: Included scripts do automatic cmake_policy PUSH
  and POP.  Run "cmake --help-policy CMP0011" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  The included script
    /home/xyq/minio-cpp/vcpkg-master/scripts/buildsystems/vcpkg.cmake

  affects policy settings.  CMake is implying the NO_POLICY_SCOPE option for
  compatibility, so the effects are applied to the including context.
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:16 (project)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!

**Comment by dg0yt** [comment]
> I am sure that I had install nessary development tool. like 'make build-essential tar curl zip unzip ninja' and so on
> I try set CMAKE_MAKE_PROGRAM in the CMakeCache.txt(build), but still failed (CMAKE_BUILD_PROGRAM=/usr/bin/make)

Which variable did you really set?
Did you check that /usr/bin/make exists?

**Comment by xuyiqun-learner** [comment]
> > I am sure that I had install nessary development tool. like 'make build-essential tar curl zip unzip ninja' and so on
> > I try set CMAKE_MAKE_PROGRAM in the CMakeCache.txt(build), but still failed (CMAKE_BUILD_PROGRAM=/usr/bin/make)
> 
> Which variable did you really set? Did you check that /usr/bin/make exists?
I am sure that make is existent, and use find command to get its path

**Comment by dg0yt** [comment]
> > > I am sure that I had install nessary development tool. like 'make build-essential tar curl zip unzip ninja' and so on
> > > I try set CMAKE_MAKE_PROGRAM in the CMakeCache.txt(build), but still failed (CMAKE_BUILD_PROGRAM=/usr/bin/make)
> > 
> > 
> > Which variable did you really set? Did you check that /usr/bin/make exists?
> > I am sure that make is existent, and use find command to get its path

AFAIU you didn't check.
~~~~
ls -l /usr/bin/make
which make
make --version

**Comment by dg0yt** [comment]
> but still failed (CMAKE_BUILD_PROGRAM=/usr/bin/make)

Note that this isn't the right variable.

**Comment by xuyiqun-learner** [comment]
> make --version
![image](https://user-images.githubusercontent.com/63037112/224550800-6dce9d98-b11b-412a-af94-16cb32f6c916.png)

**Comment by xuyiqun-learner** [comment]
I can't wait for help by yours ,then I spent some time to modify miniocpp's CMakeLists.txt and install it's dependencies manually in ubuntu20 of win10 this morning.  I completed compilation by luck.

**Comment by dg0yt** [comment]
Luck, indeed. As the error probably isn't related to vcpkg.

**Comment by xuyiqun-learner** [comment]
> Luck, indeed. As the error probably isn't related to vcpkg.

it's really werid, I retry to use vckpkg to compile the originial CMakeLists. compilation witout any problem

**Comment by xuyiqun-learner** [comment]
I recur the issue in Windows 10 IoT Enterprise LTSC(Version 21H2, OS build19044.1288) Ubuntu20.04 LTS-WSL2 
![image](https://user-images.githubusercontent.com/63037112/226097944-87a989f0-569e-457c-85e0-6831e97f56c7.png)

**Comment by xuyiqun-learner** [comment]
Solution:
sudo apt-get install pkg-config -y
