### ISSUE TITLE
[cminpack] not providing a config for debug target 

### ISSUE THREAD

**Issue by MangoSister** [microsoft/vcpkg#30139]
**Describe the bug**
The cminpack port does not provide a config for debug target. This causes downstream projects to always link to the release library, and vcpkg fails to copy the correct dll to build folder.

**Environment**
- OS: Windows 11
- Compiler: MSVC

**To Reproduce**
1. ./vcpkg install cminpack:x64-windows
2.  Observe that there is only CMinpackConfig-release.cmake in vcpkg/packages/cminpack_x64-windows/share/cminpack.
3. Create a CMake project with find_package(CMinpack CONFIG REQUIRED) and link cminpack with target_link_libraries(main PRIVATE cminpack::cminpack).
4. Observe that for debug configuration, the generated VS sln still tries to link the release cminpack library cminpack.lib (in lib/) instead of the debug variant cminpack_d.lib (in debug/lib/)
5. Build the project in debug and observe that no dll is copied to the build folder.
6. However, everything works in release.

**Expected behavior**
There should also be a CMinpackConfig-debug.cmake so that downstream projects can correctly link the debug library when in debug configuration.

**Failure logs**
Applications reports missing the correct cminpack dll and crashes.

**Comment by dg0yt** [comment]
Try #30141.

**Comment by MangoSister** [comment]
> Try #30141.

I think it works. Thanks for the quick fix.
