### ISSUE TITLE
[angle] copy libEGL.dll

### ISSUE THREAD

**Issue by wh1t3lord** [microsoft/vcpkg#30142]
For simplicity.

I use glfw and I want to create EGL context. For this I need to use 

```cpp
glfwWindowHint(GLFW_CLIENT_API, GLFW_OPENGL_ES_API);
glfwWindowHint(GLFW_CONTEXT_CREATION_API, GLFW_EGL_CONTEXT_API);
```

But GLFW returns error with description: "EGL: Library not found"

I use in cmake the suggested heuristic for integration

```cmake	
target_link_libraries(${PROJECT_NAME} PUBLIC 
		 unofficial::angle::libEGL
		 unofficial::angle::libANGLE
		 unofficial::angle::libGLESv2
		 unofficial::angle::angle_common)
``` 

But it copies only one library from angle it is libGLESv2.dll and there is no libEGL and as the result I can't run my solution successfully.

**Comment by FrankXie05** [comment]
vcpkg provides the `libEGL.lib`. Could you please make sure you have added `CMAKE_TOOLCHAIN_FILE`  and the lib exists in `vcpkg/packages/angle_x86-windows(x64-windows)/lib` locally ?
![image](https://user-images.githubusercontent.com/65999885/224616801-0d4f5d66-97a9-43a9-bd4c-87d63d010e8b.png)

**Comment by dg0yt** [comment]
@FrankXie05 AFAIU it is not a core build issue but an issue with app-local deployment.

**Comment by wh1t3lord** [comment]
@FrankXie05 the lib exists, but it doesn't copy all necessary binaries (.dll). CMAKE_TOOLCHAIN_FILE  I passed. You can try to reproduce by your own. Or do you want to say that everything works fine?

**Comment by FrankXie05** [comment]
@wh1t3lord Could you pleae provide a simple cmake project to reproduce ? :) 
![image](https://user-images.githubusercontent.com/65999885/224661154-93380f26-a40b-4fdd-8f2c-99ac3f6c3f5c.png)

@dg0yt I want to make sure that there is no problem with the local provided, and then considering the use of it.

**Comment by wh1t3lord** [comment]
@FrankXie05 maybe I didn't explain the situation correctly. 

I set output dir in cmake in order to collect all dlls and exe of my solution.

Many of dependencies that were built as dlls through vcpkg are copied (x64-windows configuration), but angle's libraries are not copied. For that case I said that libEGL.dll is not in my output folder while other libraries are. Is it error on vcpkg side?

**Comment by xiaozhuai** [comment]
It was because glfw didn't link to libEGL at all. It open libEGL dynamic library on runtime.
libGLESv2 is link to your project, so it was copied.
See https://github.com/glfw/glfw/issues/2114

**Comment by dg0yt** [comment]
This is what I expected: DLL used as a module/plugin. This is not handled by vcpkg's app-local deployment, except for qt and magnum plugins.

**Comment by FrankXie05** [comment]
@xiaozhuai @dg0yt @wh1t3lord 
We can go to issue https://github.com/microsoft/vcpkg/issues/29622 . I asked whether the upstream supports it If we don't reply in a short time, we will solve it.

**Comment by xiaozhuai** [comment]
@FrankXie05 #29622 and #30142 are not the same problem.
#29622 already link to libEGL but it crash after angle update to 5414 (after https://github.com/microsoft/vcpkg/pull/27444), before that, it work well.
#30142 is a design behavior, by default, glfw didn't link to libEGL, so it wouldn't deploy libEGL.dll.
