### ISSUE TITLE
[gstreamer] update to 1.22.1

### ISSUE THREAD

**Issue by elejke** [microsoft/vcpkg#30145]
Library name: **Gstreamer**

New version number: **1.22.1**

Other information that may be useful:

Important features on Mac OS:
* GStreamer.framework and all libraries in it are now **relocatable**
* Various fixes were made to make static linking to gstreamer libraries and plugins **work correctly on macOS**
* **osxaudiosrc**: Support a device as both input and output
* **osxaudio**: support hidden devices on macOS

Release notes:
https://gstreamer.freedesktop.org/releases/1.22/#1.22.1

**Comment by MonicaLiu0311** [comment]
Fixed by https://github.com/microsoft/vcpkg/pull/33863.
