### ISSUE TITLE
[glfw3] Build error

### ISSUE THREAD

**Issue by muhammadmoizulhaq** [microsoft/vcpkg#30144]
**Host Environment**
x64-linux
- OS: [e.g. Windows/Linux etc...]
Linux
- Compiler: revision
gcc 11.3.0

**To Reproduce**
I install 

'git clone https://github.com/Microsoft/vcpkg.git'
'cd vcpkg'
'./bootstrap-vcpkg.sh'
'./vcpkg install glfw3'

**Failure logs**

error: building glfw3:x64-linux failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+glfw3
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[glfw3]+Build+error
Include '[glfw3] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-03-01-538539c4e364dd6f14f5e36f6704144254845159
    vcpkg-scripts version: 716c3524a 2023-03-10 (2 days ago)

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

it did not producing any log file.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by dg0yt** [comment]
Did you check the output lines before `error: building glfw3:x64-linux failed with: BUILD_FAILED`?
In particular, did you see the following:
~~~
GLFW3 currently requires the following libraries from the system package manager:
    xinerama
    xcursor
    xorg
    libglu1-mesa
    pkg-config

These can be installed on Ubuntu systems via sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config

Alternatively, when targeting the Wayland display server, use the packages listed in the GLFW documentation here:

https://www.glfw.org/docs/3.3/compile.html#compile_deps_wayland
~~~

**Comment by muhammadmoizulhaq** [comment]
yes,
I did

**Comment by dg0yt** [comment]
You really need to provide more information.

**Comment by muhammadmoizulhaq** [comment]
It works on Windows properly but for Linux, it did not work properly. 
It looks like
I install the ImGUI library on Linux it installed properly.
But when I install any other library is not installed properly and gives me this error.
and also it did tell me to 'git pull' to update the repo.
I did but the repo is also fully updated.
it just install ImGUI every time but it did not install any other library.

**Comment by JonLiu1993** [comment]
@muhammadmoizulhaq, Thanks for posting this issue, I can successfully install glfw3 in my linux machine, pleasae provide your error log:
````
test@test001:~/vcpkg$ ./vcpkg install glfw3
Computing installation plan...
The following packages will be built and installed:
    glfw3[core]:x64-linux -> 3.3.8#2
Detecting compiler hash for triplet x64-linux...
Restored 0 package(s) from /home/test/.cache/vcpkg/archives in 57.66 ms. Use --debug to see more details.
Installing 1/1 glfw3:x64-linux...
Building glfw3[core]:x64-linux...
-- Downloading https://github.com/glfw/glfw/archive/7482de6071d21db77a7236155da44c172a7f6c9e.tar.gz -> glfw-glfw-7482de6071d21db77a7236155da44c172a7f6c9e.tar.gz...
-- Extracting source /home/test/vcpkg/downloads/glfw-glfw-7482de6071d21db77a7236155da44c172a7f6c9e.tar.gz
-- Using source at /home/test/vcpkg/buildtrees/glfw3/src/172a7f6c9e-7678776297.clean
GLFW3 currently requires the following libraries from the system package manager:
    xinerama
    xcursor
    xorg
    libglu1-mesa
    pkg-config

These can be installed on Ubuntu systems via sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config

Alternatively, when targeting the Wayland display server, use the packages listed in the GLFW documentation here:

https://www.glfw.org/docs/3.3/compile.html#compile_deps_wayland
-- Configuring x64-linux
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Fixing pkgconfig file: /home/test/vcpkg/packages/glfw3_x64-linux/lib/pkgconfig/glfw3.pc
-- Fixing pkgconfig file: /home/test/vcpkg/packages/glfw3_x64-linux/debug/lib/pkgconfig/glfw3.pc
-- Installing: /home/test/vcpkg/packages/glfw3_x64-linux/share/glfw3/copyright
-- Performing post-build validation
Stored binary cache: "/home/test/.cache/vcpkg/archives/e2/e231dcaa2655728c7eb01a608945ca5a2993023702b25f641f7efed9d913a2c8.zip"
Elapsed time to handle glfw3:x64-linux: 3.351 s
Total install time: 3.74 s
glfw3 provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(glfw3 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE glfw)


````

**Comment by muhammadmoizulhaq** [comment]
let find it

**Comment by muhammadmoizulhaq** [comment]
and one more thing it just download the Imgui properly but did not download any other library.

**Comment by muhammadmoizulhaq** [comment]
[config-x64-linux-dbg-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10963899/config-x64-linux-dbg-CMakeCache.txt.log)
[config-x64-linux-out.log](https://github.com/microsoft/vcpkg/files/10963900/config-x64-linux-out.log)
[config-x64-linux-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10963901/config-x64-linux-rel-CMakeCache.txt.log)
[stdout-x64-linux.log](https://github.com/microsoft/vcpkg/files/10963902/stdout-x64-linux.log)




these are the log files I found!

**Comment by JonLiu1993** [comment]
@muhammadmoizulhaq, please try this command `sudo apt-get install libx11-dev` then install glfw3 again.

**Comment by muhammadmoizulhaq** [comment]
I try this command but it is not only problematic with glfw3.
It also gives errors with raylib, qt, sfml, and every single one I am installing.

**Comment by dg0yt** [comment]
Most GUI-related ports in vcpkg depend on system X11 development packages for linux. 
Note the `-dev` suffix in the last comment: This also applies to other system libraries required by `glfw`. We don't need only the runtime, but also the devlopment stuff.

**Comment by muhammadmoizulhaq** [comment]
I try this 
If some thing happens again.
get back

**Comment by JonLiu1993** [comment]
@muhammadmoizulhaq, I found the same error as you in the upstream issue, there are many detailed discussions in it, you can refer to it :https://github.com/glfw/glfw/issues/1957

**Comment by dg0yt** [comment]
That glfw issue was reprorted to disappear with CMake 3.24. vcpkg uses CMake 3.25.

**Comment by muhammadmoizulhaq** [comment]
do I need to install  libx11 on the root directory?

**Comment by JonLiu1993** [comment]
> do I need to install libx11 on the root directory?

I recommend trying it out on your command line using the command.

**Comment by muhammadmoizulhaq** [comment]
I mean using the terminal I need to install this libx11 in a specific folder or on the root path.

**Comment by dg0yt** [comment]
You need to install the system package. It will be installed in a location determined by the system package manager.

**Comment by muhammadmoizulhaq** [comment]
ok

**Comment by muhammadmoizulhaq** [comment]
Computing installation plan...
The following packages will be built and installed:
    glfw3[core]:x64-linux -> 3.3.8#2
Detecting compiler hash for triplet x64-linux...
Restored 0 package(s) from /home/pc/.cache/vcpkg/archives in 9.198 us. Use --debug to see more details.
Installing 1/1 glfw3:x64-linux...
Building glfw3[core]:x64-linux...
-- Downloading https://github.com/glfw/glfw/archive/7482de6071d21db77a7236155da44c172a7f6c9e.tar.gz -> glfw-glfw-7482de6071d21db77a7236155da44c172a7f6c9e.tar.gz...
-- Extracting source /home/pc/Desktop/cpp/IMGUI_Test/vcpkg/downloads/glfw-glfw-7482de6071d21db77a7236155da44c172a7f6c9e.tar.gz
-- Using source at /home/pc/Desktop/cpp/IMGUI_Test/vcpkg/buildtrees/glfw3/src/172a7f6c9e-7678776297.clean
GLFW3 currently requires the following libraries from the system package manager:
    xinerama
    xcursor
    xorg
    libglu1-mesa
    pkg-config

These can be installed on Ubuntu systems via sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config

Alternatively, when targeting the Wayland display server, use the packages listed in the GLFW documentation here:

https://www.glfw.org/docs/3.3/compile.html#compile_deps_wayland
-- Configuring x64-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /home/pc/Desktop/cpp/IMGUI_Test/vcpkg/downloads/tools/ninja/1.10.2-linux/ninja -v
    Working Directory: /home/pc/Desktop/cpp/IMGUI_Test/vcpkg/buildtrees/glfw3/x64-linux-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      /home/pc/Desktop/cpp/IMGUI_Test/vcpkg/buildtrees/glfw3/config-x64-linux-dbg-CMakeCache.txt.log
      /home/pc/Desktop/cpp/IMGUI_Test/vcpkg/buildtrees/glfw3/config-x64-linux-rel-CMakeCache.txt.log
      /home/pc/Desktop/cpp/IMGUI_Test/vcpkg/buildtrees/glfw3/config-x64-linux-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:248 (vcpkg_execute_required_process)
  ports/glfw3/portfile.cmake:40 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)


error: building glfw3:x64-linux failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+glfw3
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[glfw3]+Build+error
Include '[glfw3] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-03-01-538539c4e364dd6f14f5e36f6704144254845159
    vcpkg-scripts version: cfdeb75bb 2023-03-13 (19 hours ago)


Please use the prefilled template from /home/pc/Desktop/cpp/IMGUI_Test/vcpkg/installed/vcpkg/issue_body.md when reporting your issue.

**Comment by muhammadmoizulhaq** [comment]
> Computing installation plan... The following packages will be built and installed: glfw3[core]:x64-linux -> 3.3.8#2 Detecting compiler hash for triplet x64-linux... Restored 0 package(s) from /home/pc/.cache/vcpkg/archives in 9.198 us. Use --debug to see more details. Installing 1/1 glfw3:x64-linux... Building glfw3[core]:x64-linux... -- Downloading https://github.com/glfw/glfw/archive/7482de6071d21db77a7236155da44c172a7f6c9e.tar.gz -> glfw-glfw-7482de6071d21db77a7236155da44c172a7f6c9e.tar.gz... -- Extracting source /home/pc/Desktop/cpp/IMGUI_Test/vcpkg/downloads/glfw-glfw-7482de6071d21db77a7236155da44c172a7f6c9e.tar.gz -- Using source at /home/pc/Desktop/cpp/IMGUI_Test/vcpkg/buildtrees/glfw3/src/172a7f6c9e-7678776297.clean GLFW3 currently requires the following libraries from the system package manager: xinerama xcursor xorg libglu1-mesa pkg-config
> 
> These can be installed on Ubuntu systems via sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config
> 
> Alternatively, when targeting the Wayland display server, use the packages listed in the GLFW documentation here:
> 
> https://www.glfw.org/docs/3.3/compile.html#compile_deps_wayland -- Configuring x64-linux CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message): Command failed: /home/pc/Desktop/cpp/IMGUI_Test/vcpkg/downloads/tools/ninja/1.10.2-linux/ninja -v Working Directory: /home/pc/Desktop/cpp/IMGUI_Test/vcpkg/buildtrees/glfw3/x64-linux-rel/vcpkg-parallel-configure Error code: 1 See logs for more information: /home/pc/Desktop/cpp/IMGUI_Test/vcpkg/buildtrees/glfw3/config-x64-linux-dbg-CMakeCache.txt.log /home/pc/Desktop/cpp/IMGUI_Test/vcpkg/buildtrees/glfw3/config-x64-linux-rel-CMakeCache.txt.log /home/pc/Desktop/cpp/IMGUI_Test/vcpkg/buildtrees/glfw3/config-x64-linux-out.log
> 
> Call Stack (most recent call first): installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:248 (vcpkg_execute_required_process) ports/glfw3/portfile.cmake:40 (vcpkg_cmake_configure) scripts/ports.cmake:147 (include)
> 
> error: building glfw3:x64-linux failed with: BUILD_FAILED error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`. Then check for known issues at: https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+glfw3 You can submit a new issue at: [https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[glfw3]+Build+error](https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=%5Bglfw3%5D+Build+error) Include '[glfw3] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above. vcpkg-tool version: 2023-03-01-538539c4e364dd6f14f5e36f6704144254845159 vcpkg-scripts version: [cfdeb75](https://github.com/microsoft/vcpkg/commit/cfdeb75bb67fee475b517a2f45d8f93f2b46bdb4) 2023-03-13 (19 hours ago)
> 
> Please use the prefilled template from /home/pc/Desktop/cpp/IMGUI_Test/vcpkg/installed/vcpkg/issue_body.md when reporting your issue.

this is the complete error every time I try and this time i run that command before
``` bash
sudo apt-get install libx11-dev
```

**Comment by JonLiu1993** [comment]
This error log is same as before?
````
/home/pc/Desktop/cpp/IMGUI_Test/vcpkg/buildtrees/glfw3/config-x64-linux-out.log
````

**Comment by muhammadmoizulhaq** [comment]
I run the command first and then reconfigure the vcpkg and then install the glfw3.
but still this error.

**Comment by muhammadmoizulhaq** [comment]
cmake version 3.26.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).

 this is cmake version

**Comment by muhammadmoizulhaq** [comment]
pc@pc:~$ sudo apt-get install libx11-dev
[sudo] password for pc: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libx11-dev is already the newest version (2:1.7.5-1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

**Comment by dg0yt** [comment]
And the other packages? 
> ~~~
> These can be installed on Ubuntu systems via sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config
> ~~~

**Comment by muhammadmoizulhaq** [comment]
> And the other packages?
> 
> > ```
> > These can be installed on Ubuntu systems via sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config
> > ```

This works fine and it help me a lot to learn new things.
thanks for the help.
