### ISSUE TITLE
[zstd] build failure in emscripten lose '-pthread'

### ISSUE THREAD

**Issue by LeenHawk** [microsoft/vcpkg#30146]
**Host Environment**

- OS: Linux Debian Sid
- Compiler: emcc 3.1.32

**To Reproduce**

` ./vcpkg install zstd --triplet=wasm32-emscripten`

**Failure logs**

-- [COMMUNITY] Loading triplet configuration from: /home/leen/tools/vcpkg/triplets/community/wasm32-emscripten.cmake
-- Using cached facebook-zstd-v1.5.4.tar.gz.
-- Cleaning sources at /home/leen/tools/vcpkg/buildtrees/zstd/src/v1.5.4-75b26c3dfe.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/leen/tools/vcpkg/downloads/facebook-zstd-v1.5.4.tar.gz
-- Applying patch no-static-suffix.patch
-- Using source at /home/leen/tools/vcpkg/buildtrees/zstd/src/v1.5.4-75b26c3dfe.clean
-- Found external ninja('1.11.1').
-- Configuring wasm32-emscripten
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/ninja -v
    Working Directory: /home/leen/tools/vcpkg/buildtrees/zstd/wasm32-emscripten-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      /home/leen/tools/vcpkg/buildtrees/zstd/config-wasm32-emscripten-dbg-CMakeCache.txt.log
      /home/leen/tools/vcpkg/buildtrees/zstd/config-wasm32-emscripten-rel-CMakeCache.txt.log
      /home/leen/tools/vcpkg/buildtrees/zstd/config-wasm32-emscripten-out.log

[config-wasm32-emscripten-dbg-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10953909/config-wasm32-emscripten-dbg-CMakeCache.txt.log)
[config-wasm32-emscripten-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10953914/config-wasm32-emscripten-rel-CMakeCache.txt.log)
[config-wasm32-emscripten-out.log](https://github.com/microsoft/vcpkg/files/10953918/config-wasm32-emscripten-out.log)

**Additional context**

According to emscripten [doc](https://emscripten.org/docs/porting/pthreads.html), emcc use pthread only in use "-pthread" compiler flag. It seems that vcpkg doesn't use "-pthread".

**Comment by LeenHawk** [comment]
Really strange. If vcpkg use cmake and input 'Emscripten.cmake' and replace with 'emmake make' instead of 'make', zstd should work..

**Comment by dg0yt** [comment]
It is a community triplet, and maybe it is not yet implemented properly.
The only places where vcpkg calls `emconfigure` and `emmake` is in `ports/openssl/unix/portfile.cmake`. I already wondered why it is not used in central scripts.
And there is no single spot in central scripts which evaluates `VCPKG_TARGET_IS_EMSCRIPTEN`.

**Comment by LeenHawk** [comment]
> `wasm32-emscripten` is a community triplet, and maybe it is not yet implemented properly. The only places where vcpkg calls `emconfigure` and `emmake` is in `ports/openssl/unix/portfile.cmake`. I already wondered why it is not used in central scripts. And there is no single spot in central scripts which evaluates `VCPKG_TARGET_IS_EMSCRIPTEN`.

It seems an emscripten probleam...

**Comment by LeenHawk** [comment]
> `wasm32-emscripten` is a community triplet, and maybe it is not yet implemented properly. The only places where vcpkg calls `emconfigure` and `emmake` is in `ports/openssl/unix/portfile.cmake`. I already wondered why it is not used in central scripts. And there is no single spot in central scripts which evaluates `VCPKG_TARGET_IS_EMSCRIPTEN`.

I have test zstd official build method - 'emake make' can work. Maybe I should ask zstd author...

**Comment by LeenHawk** [comment]
> `wasm32-emscripten` is a community triplet, and maybe it is not yet implemented properly. The only places where vcpkg calls `emconfigure` and `emmake` is in `ports/openssl/unix/portfile.cmake`. I already wondered why it is not used in central scripts. And there is no single spot in central scripts which evaluates `VCPKG_TARGET_IS_EMSCRIPTEN`.

But does vcpkg must use cmake?

**Comment by dg0yt** [comment]
IMO it is a vcpkg issue with the wasm32-emscripten triplet, not an issue for zstd upstream.

vcpkg prefers uniform build recipes across platforms. The CMake buildsystem also offers exported CMake config for downstream usage.

**Comment by LeenHawk** [comment]
> IMO it is a vcpkg issue with the wasm32-emscripten triplet, not an issue for zstd upstream.
> 
> vcpkg prefers uniform build recipes across platforms. The CMake buildsystem also offers exported CMake config for downstream usage.

In my view, I remember zstd can be built in a period. I just want to define where is problem between vcpkg or zstd...

**Comment by LeenHawk** [comment]
> > I just want to define where is problem between vcpkg or zstd...
> 
> ... or emscripten which provides the chainloaded cmake toolchain file. Someone from the community will have to investigate. But AFAICS there should be an indication of using `emconfigure` and `emmake` in addition to the toolchain file, in order to implement the recommendations: https://emscripten.org/docs/compiling/Building-Projects.html?highlight=cmake#integrating-with-a-build-system

I have found `emcmake cmake ..` can't work like in vcpkg and `emmake make` can work. I just delay emscripten investigation

**Comment by dg0yt** [comment]
A quick investigation with the `--trace-expand` CMake option disclosed that emscripten doesn't understand the `-z noexecstack` linker flags added by zstd. Please report this upstream for a permanet fix. #30174 has a minimal patch.

**Comment by LeenHawk** [comment]
> A quick investigation with the `--trace-expand` CMake option disclosed that emscripten doesn't understand the `-z noexecstack` linker flags added by zstd. Please report this upstream for a permanet fix. #30174 has a minimal patch.

They seems to have found it, [in this issue](https://github.com/emscripten-core/emscripten/issues/18948#issue-1620841922)

**Comment by dg0yt** [comment]
That's a fix in Emscripten, and it just turns the error into a warning. This means users need to update the SDK, and #30174 is a good solution for vcpkg which doesn't remove a relevant behaviour.

**Comment by LeenHawk** [comment]
> That's a fix in Emscripten, and it just turns the error into a warning. This means users need to update the SDK, and #30174 is a good solution for vcpkg which doesn't remove a relevant behaviour.

Thanks.

**Comment by dg0yt** [comment]
Duplicates #29718.
