### ISSUE TITLE
[geogram] update to 1.8.3

### ISSUE THREAD

**Issue by Dizww** [microsoft/vcpkg#30150]
Library name: geogram (https://github.com/BrunoLevy/geogram)

New version number: v1.8.3

**Comment by MonicaLiu0311** [comment]
Thank you for your reminder, I found that the download source of `geogram` is [alicevision/geogram](https://github.com/alicevision/geogram), but it was only updated to `v1.7.7` (2021.10.23) and did not continue, while [BrunoLevy/geogram](https://github.com/BrunoLevy/geogram) was updated from `v1.8.1` to `v1.8.3` (2023.03.03), so can you confirm they are the same and the `geogram` migrated to the new place?

**Comment by Dizww** [comment]
[alicevision/geogram](https://github.com/alicevision/geogram) is a Git mirror of the geogram library by INRIA.And you can look at [Initial import of geogram 1.7.8 to git](https://github.com/BrunoLevy/geogram/commit/5adf8c1eb6155f254da247b079862d24d0027b0e)

**Comment by MonicaLiu0311** [comment]
So [BrunoLevy/geogram](https://github.com/BrunoLevy/geogram) is the official source of geogram right?

We have this request:
- [ ] Check that the source code comes from the upstream project's authoritative source.

**Comment by Dizww** [comment]
yes,[Bruno Levy](https://github.com/BrunoLevy) is Researcher in computational physics, Chargé de mission Inria France 2030, 2018-2022 director of centre Inria Nancy Grand-Est, ERC GOODSHAPE and VORPALINE
