### ISSUE TITLE
libpq vs2022 vcpkg install err

### ISSUE THREAD

**Issue by DaXiaWei** [microsoft/vcpkg#30155]
**Host Environment**

- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**

`./vcpkg install libpq`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.
[issue_body.md](https://github.com/microsoft/vcpkg/files/10957411/issue_body.md)

**Comment by DaXiaWei** [comment]
i install english pack but 。。。

**Comment by FrankXie05** [comment]
@DaXiaWei  Duplicate of https://github.com/microsoft/vcpkg/issues/26416

**Comment by DaXiaWei** [comment]
update VS problem solved think you @FrankXie05 and @JonLiu1993
