### ISSUE TITLE
bootstrap.sh downloads x64 binary when run under arm64 Alpine Linux 

### ISSUE THREAD

**Issue by linustan** [microsoft/vcpkg#30170]
**Describe the bug**
When bootstrap-vcpkg.sh is executed on an arm64 Alpine Linux host, a `vcpkg` binary for the x86-64 architecture is downloaded.

**Environment**
- OS: Alpine Linux (arm64)
- Compiler: N/A

**To Reproduce**
1. `./bootstrap-vcpkg.sh`
2. `./file vcpkg`
Result:
`vcpkg: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), static-pie linked, stripped`

**Expected behavior**
A vcpkg executable built for ARM aarch64 should be downloaded or built.

**Additional context**
The problem appears to be caused by the following lines in the bootstrap script:
```shell
if [ -e /etc/alpine-release ]; then                                        
    vcpkgUseSystem="ON"                                                                    
    vcpkgUseMuslC="ON"                                                
fi   
```

When `vcpkgUseMuslC` is `ON`, then the following branch is taken:
```shell
elif [ "$vcpkgUseMuslC" = "ON" ]; then                                     
    echo "Downloading vcpkg-muslc..."                                                      
    vcpkgToolReleaseSha="e8e439126c410dd39f4df2fdfc389e0e9e01df6789bfd3e5a16bf88c11a90439a14f84575badfe4f969db6e5c01040207073dc8b93d4f99d6dd18d1b372d9549"
    vcpkgToolName="vcpkg-muslc"  
```

This downloads an x86-64 binary for vcpkg, which can't be run on the aarch64 host platform.

**Comment by jimwang118** [comment]
```
./file vcpkg
Result:
vcpkg: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), static-pie linked, stripped
```
Doesn't this result mean that this file is an executable program, which can be executed on both x64 and x86_64, and can be statically linked?
