### ISSUE TITLE
include not found

### ISSUE THREAD

**Issue by yywd6** [microsoft/vcpkg#30189]
**Describe the bug**

I installed VS2019 and installed Opencv2 with vcpkg and have vcpkg integrate install successfully, but #include <opencv2/opencv.hpp >
#include < opencv2/imgproc/types_c.h>, 
both of which will report an error saying not found, I have been bothered by this problem for a long time, it would be really good if someone answered me, here are the relevant images

**To Reproduce**
![DO818K3ENO0}605{MINF DU](https://user-images.githubusercontent.com/101700971/225191730-eb705af4-062a-43ef-8587-f8e8d0c39a01.png)
![(){LQTXE4P)(S6E7F3}I~SB](https://user-images.githubusercontent.com/101700971/225191875-8c58b3aa-dd44-4acf-86d0-337d3b3e6671.png)

**Environment**
- windows 10
- vs2019:

**Comment by Adela0814** [comment]
Could you please replace `opencv2` to `opencv2.4\opencv2` and try again.
![image](https://user-images.githubusercontent.com/95600143/225234111-2ca2d004-8a5f-48be-833a-a2b76bdabbc0.png)

**Comment by Adela0814** [comment]
I'm not able to repro this issue, could you please provide your sample project.

Please make sure you use the usage provided by cmake:
```
set(OpenCV_DIR "${VCPKG_INSTALLED_DIR}/x64-windows/share/opencv2")
find_package(OpenCV REQUIRED)
```

**Comment by Adela0814** [comment]
Please replace `opencv2` to `opencv2.4\opencv2` and try again, thanks.
![image](https://user-images.githubusercontent.com/95600143/225236975-03e5f8cd-db40-48a1-900e-32f26ba519bf.png)

**Comment by dg0yt** [comment]
> Please replace `opencv2` to `opencv2.4\opencv2` and try again, thanks.

Isn't the proper solution to manually add `include\opencv2.4` to the include dirs when not using CMake?

**Comment by yywd6** [comment]
> Please replace to and try again, thanks.`opencv2``opencv2.4\opencv2`
> 
> The installed path of the header files is as follows:`opencv2` ![image](https://user-images.githubusercontent.com/95600143/225236975-03e5f8cd-db40-48a1-900e-32f26ba519bf.png)

Really thank you very much, I think I've solved this problem with your help, it's the header file path that is wrong

**Comment by yywd6** [comment]
Really thank you very much, I think I've solved this problem with your help, it's the header file path that is wrong @Adela0814

**Comment by yywd6** [comment]
Really thank you very much, too.I think I've solved this problem with your help, it's the header file path that is wrong @dg0yt
