### ISSUE TITLE
error: building openblas:arm64-osx failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by sjb048** [microsoft/vcpkg#30188]
**Host Environment**

- OS: [mac]
- Compiler: revision

**To Reproduce**

`./vcpkg install xxxx`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JonLiu1993** [comment]
@sjb048, thanks for posting this issue, please provide more information so we can check your error.

**Comment by sjb048** [comment]
trying to install blaze 
error: building openblas:arm64-osx failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openblas
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openblas]+Build+error
Include '[openblas] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-03-01-538539c4e364dd6f14f5e36f6704144254845159
    vcpkg-scripts version: 2256cc983 2023-03-14 (2 hours ago)

**Comment by luciferblaze007** [comment]
Trying to install This:

C:\Devlopment\vcpkg>.\vcpkg install thrift
warning: Starting with the September 2023 release, the default triplet for vcpkg libraries will change from x86-windows to the detected host triplet (x64-windows). To resolve this message, add --triplet x86-windows to keep the same behavior.
Computing installation plan...


with the Error:
error: building sqlite3:x86-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+sqlite3
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[sqlite3]+Build+error
Include '[sqlite3] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454
    vcpkg-scripts version: 20759c873 2023-03-14 (4 hours ago)

**Comment by JonLiu1993** [comment]
@sjb048, @luciferblaze007, could you please provide the error log?

**Comment by ZJL-0422** [comment]
How can I solve the following problems：
error: building openblas:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openblas
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openblas]+Build+error
Include '[openblas] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454
    vcpkg-scripts version: 8875aa3cd 2023-03-22 (10 hours ago)

**Comment by JonLiu1993** [comment]
@luciferblaze007, I can successfully install `thrift:x64-windows` locally, please use command `.\vcpkg install thrift:x64-windows --debug` try again and put up the complete install log.

````
PS F:\test\vcpkg> .\vcpkg install thrift:x64-windows
Computing installation plan...
The following packages will be built and installed:
    thrift[core]:x64-windows -> 0.16.0
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\test\AppData\Local\vcpkg\archives in 249.1 us. Use --debug to see more details.
Installing 1/1 thrift:x64-windows...
Building thrift[core]:x64-windows...
-- Note: thrift only supports static library linkage. Building static library.
-- Using cached apache-thrift-2a93df80f27739ccabb5b885cb12a8dc7595ecdf.tar.gz.
-- Cleaning sources at F:/test/vcpkg/buildtrees/thrift/src/dc7595ecdf-fb32ebd2bc.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/test/vcpkg/downloads/apache-thrift-2a93df80f27739ccabb5b885cb12a8dc7595ecdf.tar.gz
-- Applying patch correct-paths.patch
-- Applying patch pc-suffix.patch
-- Using source at F:/test/vcpkg/buildtrees/thrift/src/dc7595ecdf-fb32ebd2bc.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig file: F:/test/vcpkg/packages/thrift_x64-windows/lib/pkgconfig/thrift-nb.pc
-- Fixing pkgconfig file: F:/test/vcpkg/packages/thrift_x64-windows/lib/pkgconfig/thrift-z.pc
-- Fixing pkgconfig file: F:/test/vcpkg/packages/thrift_x64-windows/lib/pkgconfig/thrift.pc
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at F:/test/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Fixing pkgconfig file: F:/test/vcpkg/packages/thrift_x64-windows/debug/lib/pkgconfig/thrift-nb.pc
-- Fixing pkgconfig file: F:/test/vcpkg/packages/thrift_x64-windows/debug/lib/pkgconfig/thrift-z.pc
-- Fixing pkgconfig file: F:/test/vcpkg/packages/thrift_x64-windows/debug/lib/pkgconfig/thrift.pc
-- Installing: F:/test/vcpkg/packages/thrift_x64-windows/share/thrift/copyright
-- Performing post-build validation
Stored binary cache: "C:\Users\test\AppData\Local\vcpkg\archives\ab\ab07d94efd5276529304c40681c2040b25bf9db917e1c4ec5dd9832c1f013319.zip"
Elapsed time to handle thrift:x64-windows: 1.7663466233333334 min
Total install time: 1.815017195 min
thrift provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(Thrift CONFIG REQUIRED)
    target_link_libraries(main PRIVATE thrift::thrift thriftz::thriftz thriftnb::thriftnb)
````

**Comment by sjb048** [comment]
this issue is happening in mac , since visual studio in mac doesn't have all the supported compliers

**Comment by dg0yt** [comment]
Can someone hide the distracting  thrift:x64-windows posts?

For openblas:arm64-osx

> * Attach _**every failure log file**_ mentioned in the console output.

**Comment by JonLiu1993** [comment]
@luciferblaze00, Please resubmit an issue and attach the error log. This issue only discusses the issue of `openblas:arm64-osx`.

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
