### ISSUE TITLE
Libxml2 port 'bug' with xmlversion.h

### ISSUE THREAD

**Issue by Fleischner** [microsoft/vcpkg#3019]
Libxml2 has a generator file src\libxml2-2.9.4\include\libxml\xmlversion.h.in that gets normally converted to src\libxml2-2.9.4\include\libxml\xmlversion.h by the original build system.

The vcpkg port generates adds an cmake file that leaves this file untouched. Thus libxml2 uses the xmlversion.h that got checked into github randomly.

Normally this file sets the build options, and is different between debug and release.
We need to decide which options to choose, as vcpkg uses the same headers for debug and release.

Anyways I suggest to copy xmlversion.h to the port directory and apply it as an patch

-----

For documentation, xmlversion.h lets you choose:
- a lot of debug build settings
- dependencies (allows to build livxml2 without deps. Eg. disable libiconv, liblzma if you prefer only BSD licensed deps)

**Comment by JackBoosY** [comment]
Hi @Fleischner , thanks for reporting this issue!
Now installing libxml2 will copy xmlversion.h to the include folder. Do you mean to use it as a feature? Or is the debug version different from the .h file generated by the release version? Vcpkg can only save one copy of the header files now.

**Comment by JackBoosY** [comment]
What do you mean by using _source\include\libxml\xmlversion.h_ instead of using **xmlversion.h.in** to generate **xmlversion.h**?

**Comment by Fleischner** [comment]
With the port version from last year, xmlversion.h.in wasn't used at all. So the used xmlversion.h had the wrong defines in it, not matching port dependencies.

Also the contents are different between debug and release (?) So with parallel configure it's undefined if you will end up with the release or debug version in the install header directory.

**Comment by JackBoosY** [comment]
@Fleischner  In _ports/libxml2/CMakeLists.txt_, there is a line:
line100:
> configure_file(include/libxml/xmlversion.h.in include/libxml/xmlversion.h)

that generated xmlversion.h instead of the old xmlversion.h.
So the only problem is that we need to separate the debug and release configuration in the xml2version.h.in file. Right?

**Comment by LilyWangL** [comment]
Ping @Fleischner

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
