### ISSUE TITLE
libmikmod default installation missing dll

### ISSUE THREAD

**Issue by plbpietrz** [Microsoft/vcpkg#3020]
Hi,

after normal installation of libmikmod `vcpkg install libmikmod` (no errors), the bin folder is missing `mikmod.dll` in spite of it being build during the compilation (dll is present in the build folder).

**Comment by JackBoosY** [comment]
Hi @plbpietrz , thanks for reporting this issue!
I've fixed this issue just now. Please update and rebuild libmikmod.
Thanks.
