### ISSUE TITLE
Exporting triplet x64-osx-release does not include scripts/buildsystems/osx/applocal.py

### ISSUE THREAD

**Issue by ahmedyarub** [microsoft/vcpkg#30219]
The file scripts/buildsystems/osx/applocal.py is not included when exporting x64-osx-release's builds. I know that this is a community triplet but it looks like there is a bug somewhere in vcpkg.

**Environment**
- OS: MacOS 11.7
- Compiler: XCode 13.2.1

**To Reproduce**
1. `./vcpkg install [ports] --triplet=x64-osx-release` && `./vcpkg export [ports] --7zip --triplet=x64-osx-release `
2. Use the extracted archive in a project
3. The build scripts through an error stating that the file `scripts/buildsystems/osx/applocal.py` is missing
Repro code when

**Expected behavior**
The file is included in the exported archive and can be used to build projects.

**Comment by romanp-nexusgroup** [comment]
applocal.py is not copied any more. Long time ago it was copied in toolsrc/src/vcpkg/export.cpp alongside with applocal.ps1. But now it seems that the logic for applocal.ps1 was moved to scripts/cmake/vcpkg_copy_tool_dependencies.cmake

And applocal.py was left out
