### ISSUE TITLE
[libtorch] update to 2.1.2

### ISSUE THREAD

**Issue by LeenHawk** [microsoft/vcpkg#30224]
Library name: libtorch

New version number: 2.1.0

Other information that may be useful

[https://github.com/pytorch/pytorch/releases/tag/v2.1.0](https://github.com/pytorch/pytorch/releases/tag/v2.1.0)

A major version update.

**Comment by LeenHawk** [comment]
Hello, any progress?

**Comment by Adela0814** [comment]
I encountered an error while updating `libtorch`, which has been submitted to the upstream and is awaiting a response.
See https://github.com/pytorch/pytorch/issues/97009.

**Comment by LilyWangLL** [comment]
The latest version of `libtorch` is 2.0.1, please update it to 2.0.1.

**Comment by LeenHawk** [comment]
So, any progress?

**Comment by TeSheng93** [comment]
Any update on this? The latest is now 2.1.0

**Comment by russelltg** [comment]
This does not seem completed?

**Comment by LilyWangLL** [comment]
The latest version of `libtorch` is 2.1.2, please update it to 2.1.2.
https://github.com/pytorch/pytorch/releases/tag/v2.1.2

**Comment by TeSheng93** [comment]
Seems to be updated in https://github.com/microsoft/vcpkg/pull/36246

**Comment by LilyWangLL** [comment]
Closed as fixed by #36246.
