### ISSUE TITLE
Another level of indirection: Proposing ports-selected and ports-conflicts directories

### ISSUE THREAD

**Issue by Fleischner** [microsoft/vcpkg#3022]
First the most important point!: Please NEVER NEVER add features to vcpkg that allow to have multiple port versions in one vcpkg instance at a time! 
- Vcpkg is ALL about building a consistent set of libraries for your company. Focus on this key feature!
- Allowing multiple port versions only makes things way more complicated and slows down community effort to fix problems on the head versions!
- The correct way to handle different port versions are multiple vcpkg instances.

However vcpkg is currently lacking features for:
- Easy way to freeze ports to a certain version
- Dealing with temporary port conflicts

I propose an extended vcpkg api that builds around two new directories: 
- ports-selected
- ports-conflicts (part of the git repo)

---

The ports-selected directory adds an easy way to select and freeze ports. 

The ports directory has a couple of problems:
- git works on file basis. vcpkg ports on directory basis
- freezing ports is difficult and requires to use git
- vcpkg has no concept to mark ports as 'selected'

The ports-selected directory solves these issues:
- the ports directory always 'lives' untouched at the git master branch
- the user selects a port by coping the whole port-directory from 'ports' to 'ports-selected'
- User can freeze a port to enable custom changes or to stay at a certain port version (e.g: this could be marked by adding a freeze sub-directory in the port in ports-selected)
- Add infrastructure to vcpkg for selection: (Sample api)
	- vcpkg select portname
	- vcpkg select portname --remove
	- vcpkg select portname --upgrade
	- vcpkg select portname --freeze
	- vcpkg select portname --freeze-remove
- Deprecate direct use of vcpkg install,remove,upgrade
- Add infrastructure to vcpkg to resolve selected ports:
	- vcpkg resolve -> ensures installed ports match selected ports (by automatically using vcpkg install,remove,upgrade)

---

The ports-conflicts directory adds an easy way to bridge library conflicts without slowing down port upgrades

The ports directory has a couple of problems:
- vcpkg need to have the newest library versions as fast as possible to be attractive
- vcpkg cannot upgrade ports until all dependent libraries work with the newest version
- this will become an problem as soon as a large library upgrades to an incompatible major version (api)

The ports-conflicts directory solves these issues:
- ports-conflicts allows two major versions of the same port to coexist (for a limited timeframe)
- ports-conflicts is NOT(!) about adding a 'vcpkg with multiple port versions' feature! The name already states that ports in the ports-conflicts directory only exist for the time until all conflicts with dependent ports are solved. Then the port is removed.
- Its the users need to ensure that all ports he is interested in (selected ports) either work with the head version, or with the conflicted version.
- Add infrastructure to vcpkg: (Sample api)
	- vcpkg select portname --use-conflicted-port

**Comment by claudiofantacci** [comment]
I stumbled upon this issue while looking for a somewhat related problem.

I don't understand the reasons to why when I install a new port, say PCL, and a dependency port has been updated to a new version, say Boost, I am **forced** to update such dependencies in order to install the new port. This starts a chain reaction an all the dependencies, disrupting the workflow of a developer, potentially for hours.

@Fleischner, your proposal is interesting, it is unfortunate that we had no response from the maintainers.
I reckon that a first step towards a better version port management would be to remove the above-described requirement of mandatorily upgrading ports even for installing a new port.  
Maybe I'm missing something here, what do you think about it?

cc @ras0219-msft

**Comment by Neumann-A** [comment]
is this still an issue with [ports-overlay](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md)?

**Comment by PhoebeHui** [comment]
I think the ports-overlay feature solve the issue, please reopen this issue if I misundersteand something.
