### ISSUE TITLE
vcpkg adds target rather than host paths to CMAKE_PROGRAM_PATH

### ISSUE THREAD

**Issue by craigscott-crascit** [microsoft/vcpkg#30220]
**Describe the bug**
Calls to `find_program()` are generally going to want to find executables that can run on the host, not on the target architecture. At the moment, vcpkg adds the `tools` directory of the target triplet install area to `CMAKE_PROGRAM_PATH`, but not the `tools` directory of the host triplet's install area. When adding a host dependency that provides a tool (in my case the motivating example are things like `ccache` and `sccache`, which we are experimenting with providing via a private vcpkg registry), those tools are not able to be found due to `CMAKE_PROGRAM_PATH` not including the subdirectories under the host triplet's `tools` area.

I think adding the target triplet's `tools` subdirectories to `CMAKE_PROGRAM_PATH` is questionable, but not adding the host triplet's `tools` subdirectories definitely looks like a bug to me. It is currently breaking some of our projects that want to provide command line tools when using a custom target triplet.

Don't focus on the `ccache` and `sccache` part of this, I only use those as examples. There are other problems we are uncovering with trying to have those as host dependencies, but we will follow that up in separate issues and discussions. The bug report here is focused on incorrect population of the `CMAKE_PROGRAM_PATH` variable.

**Environment**
- OS: all
- Compiler: all

**To Reproduce**

1. Create a manifest file that lists at least one host dependency that provides a command line tool.
2. In the project, add a `find_program()` call for that command line tool.
3. Run CMake generation with the host triplet being different to the target triplet. In our case, we use a custom target triplet and the default triplet for the host.

Observe that the tool will not be found, even though vcpkg provides it in the host triplet's install area.

**Expected behavior**

Calls to `find_program()` should succeed when a host dependency provides the requested tool.

**Comment by craigscott-crascit** [comment]
It would appear that this bug only occurs if you let vcpkg determine the host triplet. If you explicitly set `VCPKG_HOST_TRIPLET`, then vcpkg adds the host triplet's `tools` subdirectories to `CMAKE_PROGRAM` path _instead_ of those from the target triplet, which is the correct behavior.

**Comment by craigscott-crascit** [comment]
The relevant logic appears to be https://github.com/microsoft/vcpkg/blob/a7b6122f6b6504d16d96117336a0562693579933/scripts/buildsystems/vcpkg.cmake#L544-L556 which was added by #23322. The logic before that change was still wrong though (looks like previously the host tools were never being added to `CMAKE_PROGRAM_PATH`).

CC: @Neumann-A

**Comment by dg0yt** [comment]
Related: #25529

**Comment by Neumann-A** [comment]
> It would appear that this bug only occurs if you let vcpkg determine the host triplet.

So I assume it works ;)
Not defining a host triplet just assumes old behavior. 

In the end it comes down to CMake itself being ambiguous what `find_program` really means and vcpkg being undecided about it. There was also somewhere a long discussion about it but i am currently unable to find it.

**Comment by autoantwort** [comment]
So a solution would be to rebuilt the host triplet selection in vcpkg.cmake or call ` vcpkg z-print-config` to get the host triplet?

**Comment by ColoredCarrot** [comment]
I just stumbled on this today, still seems as relevant as ever. Please consider re-opening this issue.

FWIW, here's the CMake code I'm using to set `VCPKG_HOST_TRIPLET` in my custom toolchain file (which calls the vcpkg one):

```cmake
# ${vcpkg_dir} must point to the vcpkg installation here

function(get_vcpkg_host_triplet target_var)
    execute_process(
            COMMAND "${vcpkg_dir}/vcpkg.exe" "z-print-config" "--x-wait-for-lock"
            OUTPUT_VARIABLE vcpkg_config
            COMMAND_ERROR_IS_FATAL ANY
    )
    string(JSON "${target_var}" GET "${vcpkg_config}" "host-triplet")
    return(PROPAGATE "${target_var}")
endfunction()

if (NOT VCPKG_HOST_TRIPLET)
    get_vcpkg_host_triplet(VCPKG_HOST_TRIPLET)
    message(STATUS "Using auto-discovered host triplet: ${VCPKG_HOST_TRIPLET}")
endif ()
```
