### ISSUE TITLE
[ffmpeg] Build error

### ISSUE THREAD

**Issue by lsl330** [microsoft/vcpkg#30221]
**Host Environment**

- OS: win11
- Compiler: revision

**To Reproduce**

`./vcpkg.exe install ffmpeg:arm64-windows`

**Failure logs**

error: building ffmpeg:arm64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+ffmpeg
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[ffmpeg]+Build+error
Include '[ffmpeg] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454
    vcpkg-scripts version: 07da05c20 2023-03-15 (5 minutes ago)

**Comment by lsl330** [comment]
-- Building Release Options: --enable-optimizations
-- Building ffmpeg for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/Users/lsl330/vcpkg/downloads/tools/msys2/893f8801e7c30cbd/usr/bin/bash.exe ./build.sh
    Working Directory: C:/Users/lsl330/vcpkg/buildtrees/ffmpeg/arm64-windows-rel
    Error code: 2
    See logs for more information:
      C:\Users\lsl330\vcpkg\buildtrees\ffmpeg\build-arm64-windows-rel-config.log
      C:\Users\lsl330\vcpkg\buildtrees\ffmpeg\build-arm64-windows-rel-out.log
      C:\Users\lsl330\vcpkg\buildtrees\ffmpeg\build-arm64-windows-rel-err.log

Call Stack (most recent call first):
  ports/ffmpeg/portfile.cmake:596 (vcpkg_execute_required_process)
  scripts/ports.cmake:147 (include)

**Comment by lsl330** [comment]
cl: 鍛戒护琛?warning D9002 :蹇界暐鏈煡閫夐」鈥?g鈥?
vf_nlmeans_neon.S
.\config.h(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
.\config.h(9): error C2001: 常量中有换行符
make: *** [/c/Users/lsl330/vcpkg/buildtrees/ffmpeg/src/n5.1.2-f31542651f.clean/ffbuild/common.mak:93: libavfilter/aarch64/vf_nlmeans_neon.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by JonLiu1993** [comment]
@lsl330, Thanks for posting this issue, does your vs have an English language installation package? If not, please restart VS after installation and run` ./vcpkg integrate install` and try again.

**Comment by JonLiu1993** [comment]
@lsl330, does this issue still exist

**Comment by JonLiu1993** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
