### ISSUE TITLE
Registry download fails because vcpkg replaces = with %3D in URL

### ISSUE THREAD

**Issue by Overlap0190** [microsoft/vcpkg#30232]
**Describe the bug**
I would like to use a custom vcpkg registry in my project but I cannot make it work with my registry being a private repository hosted on GitLab. vcpkg replaces a = with %3D in the URL I'm using and that makes the URL not working.
For authentication purposes I generated an access token and added the token to the URL where you can download the zip archive like described in GitLab documentation.

The URL looks something like this:
https://gitlab.com/api/v4/projects/PROJECT_ID/repository/archive.zip?private_token=PRIVATE_TOKEN

vcpkg changes the = in the URL so it doesn't work, like this:
https://gitlab.com/api/v4/projects/PROJECT_ID/repository/archive.zip?private_token%3DPRIVATE_TOKEN

**Environment**
- OS: Windows 11 22H2 (Build 22621.1413)

**Expected behavior**
I would expect that the URL I provide is used and that the download doesn't fail.

**Failure logs**
````
Updating registry data from https://gitlab.com/api/v4/projects/PROJECT_ID/repository/archive.zip?private_token%3DPRIVATE_TOKEN
warning: failed to download from https://gitlab.com/api/v4/projects/PROJECT_ID/repository/archive.zip?private_token%3DPRIVATE_TOKEN
error: Error: failed to download PATH_TO_REGISTRY_ZIP from any source
````

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Could you please provide your local file `vcpkg-configuration.json`? I use the following `vcpkg-configuration.json` and can't repro this issue. I only got fetch error and there is no **replaces = with %3D in URL**.
```
{
  "default-registry": null,
  "registries": [
    {
      "kind": "git",
      "repository": "https://gitlab.com/api/v4/projects/PROJECT_ID/repository/archive.zip?private_token=PRIVATE_TOKEN",
	  "baseline": "b51f391cd8f1f5a406b3baf9b014acff61702dc3",
      "packages": ["api"]
    }
  ]
}
```

```
PS E:\Lily\30232> .\vcpkg.exe install --triplet=x64-windows
Fetching registry information from https://gitlab.com/api/v4/projects/PROJECT_ID/repository/archive.zip?private_token=PRIVATE_TOKEN (HEAD)...
info: please complete authentication in your browser...
error: failed to fetch ref HEAD from repository https://gitlab.com/api/v4/projects/PROJECT_ID/repository/archive.zip?private_token=PRIVATE_TOKEN
failed to execute: "C:\Program Files\Git\cmd\git.exe" "--git-dir=C:\Users\UserName\AppData\Local\vcpkg\registries\git\.git" "--work-tree=C:\Users\UserName\AppData\Local\vcpkg\registries\git" -c core.autocrlf=false fetch --update-shallow -- https://gitlab.com/api/v4/projects/PROJECT_ID/repository/archive.zip?private_token=PRIVATE_TOKEN HEAD
error: git failed with exit code: (128).
fatal: Authentication failed for 'https://gitlab.com/api/v4/projects/PROJECT_ID/repository/archive.zip?private_token=PRIVATE_TOKEN/'
```

**Comment by Overlap0190** [comment]
Thanks for the response!

This is how my `vcpkg-confiugration.json` looks like:
````
{
  "default-registry": {
    "kind": "git",
    "baseline": "ec96844b8b1515d8982b134c73d7bc2b248d2c42",
    "repository": "https://github.com/microsoft/vcpkg"
  },
  "registries": [
    {
      "kind": "artifact",
      "location": "https://aka.ms/vcpkg-ce-default",
      "name": "microsoft"
    },
    {
      "kind": "artifact",
      "location": "https://gitlab.com/api/v4/projects/PROJECT_ID/repository/archive.zip?private_token=PRIVATE_TOKEN",
      "name": "myregistry"
    }
  ],
  "requires": {
    "myregistry:compilers/arm-none-eabi-gcc": "* 6.3.1-2017q1"
  }
}
````

You used the `install` command but I followed this article to setup my `vcpkg-configuration.json` and they use the activate command there.
https://devblogs.microsoft.com/cppblog/vcpkg-artifacts/

I noticed a difference to your `vcpkg-configuration.json` the `kind` property is different. I got `artifact` and you have `git`.

**Comment by LilyWangLL** [comment]
Thanks for your reply. I can reproduce this issue locally.
```
Updating registry data from https://gitlab.com/api/v4/projects/PROJECT_ID/repository/archive.zip?private_token%3DPRIVATE_TOKEN
warning: failed to download from https://gitlab.com/api/v4/projects/PROJECT_ID/repository/archive.zip?private_token%3DPRIVATE_TOKEN

Error: failed to download e:\Lily\30232\downloads\fbe2b5ea-registry.zip from any source
```

**Comment by Overlap0190** [comment]
The issue still persists.
