### ISSUE TITLE
[octomap] cmake config has wrong _LIBRARIES information

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#30273]
```
set(OCTOMAP_LIBRARIES
  "${PACKAGE_PREFIX_DIR}/lib/octomap.lib"
  "${PACKAGE_PREFIX_DIR}/lib/octomath.lib"
)
```

Either patch that out or redirect to the targets `octomap, octomath` instead. An alternative could also be to inject a generator expression but the target approach is probably easier to do.

**Comment by JonLiu1993** [comment]
@Neumann-A, Thanks for posting this issue, could you please describe in detail the reasons for the _LIBRARIES information error? I installed octomap locally, and checked the location of these two libs, and tested that its usage is correct, forgive me for not understanding what you mean

**Comment by JonLiu1993** [comment]
@Neumann-A, Could you explain to me your purpose of this issue in detail? I don't quite understand what you mean by this issue. Thanks.

**Comment by jimwang118** [comment]
Are you saying that I should redirect` octomap, octomath` like below?
```
find_package(unofficial-angle CONFIG)
    if(TARGET unofficial::angle::libEGL)
        set(EGL_LIBRARY unofficial::angle::libEGL)
        if(NOT TARGET EGL::EGL)
            add_library(EGL::EGL INTERFACE IMPORTED)
            set_target_properties(EGL::EGL PROPERTIES
                INTERFACE_LINK_LIBRARIES unofficial::angle::libEGL
            )
        endif()
    endif()
```
