### ISSUE TITLE
[vcpkg-docs] original specs are gone

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#30274]
Folder `docs/specifications`  was removed without a proper replacement in `vcpkg-docs`. (especially `ports-overlay.md`)

**Comment by MonicaLiu0311** [comment]
Issues related to the documentation of vcpkg now need to be reported at https://github.com/microsoft/vcpkg-docs. I have transferred this issue for you.

**Comment by Neumann-A** [comment]
Ah ok didn't know that vckg-docs had its own issue board. Thought it would be handled like vcpkg-tool
