### ISSUE TITLE
build_failed

### ISSUE THREAD

**Issue by PriyaAarthi** [microsoft/vcpkg#30281]
**Describe the bug**
error: building fontconfig:x64-linux failed with: BUILD_FAILED
when installing qt5-mqtt

**Environment**
- OS: linux-ubuntu 18.04
- Compiler: revision

**To Reproduce**
1. ./vcpkg install xxxx
2. See error
Repro code when

**Expected behavior**

**Failure logs**
-(please attached failure logs)

**Additional context**

**Comment by autoantwort** [comment]
Please close this issues and create a new one and fill out the issue template.

**Comment by Cheney-W** [comment]
Unfortunately, we don't have enough information to solve this issue, if you have any more information to help us solve it, please reopen!
