### ISSUE TITLE
vcpkg crash when integrate powershell

### ISSUE THREAD

**Issue by Logiase** [microsoft/vcpkg#30283]
**Describe the bug**
executing `.\vcpkg integrate powershell` on PowerShell 7.3.3 crashed.

**Environment**
- OS: Windows 22H2 (22621.1413)
- PowerShell: 7.3.3 installed from winget

**To Reproduce**
1. clone vcpkg and bootstrap
2. run `.\vcpkg integrate powershell`

**Failure logs**
```text
vcpkg has crashed. Please create an issue at https://github.com/microsoft/vcpkg containing a brief summary of what you were trying to do and the following information.

Version=2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454
EXCEPTION=invalid format string
CMD=
C:\dev\vcpkg\vcpkg.exe|
integrate|
powershell|
```

**Comment by FrankXie05** [comment]
It should be `vcpkg-bug`.
