### ISSUE TITLE
[icu] Build error

### ISSUE THREAD

**Issue by Moresteck** [microsoft/vcpkg#30284]
Even though I have autoconf installed and working, it's not detected by vcpkg. It worked just a month ago. I came back to the project yesterday, and it turned out to have this issue. I made no changes at all to my code, or my IDE (Qt Creator).
So I decided to update vcpkg, brew packages and QtCreator, but that didn't help. Then I've reinstalled vcpkg and Qt Creator — also no luck.
I did a brew update some time ago, I suspect that could've broken vcpkg.

Package: icu[core,tools]:arm64-osx -> 72.1#3

**Host Environment**

- Host: arm64-osx
- Compiler: AppleClang 14.0.0.14000029
-    vcpkg-tool version: 2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454
    vcpkg-scripts version: ffe7360e0 2023-03-17 (2 days ago)

**To Reproduce**

`vcpkg install `

**Failure logs**

```
-- Using cached icu4c-72_1-src.tgz.
-- Cleaning sources at /Users/moresteck/Documents/vcpkg/buildtrees/icu/src/c-72_1-src-deba61ed52.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/moresteck/Documents/vcpkg/downloads/icu4c-72_1-src.tgz
-- Applying patch disable-escapestr-tool.patch
-- Applying patch remove-MD-from-configure.patch
-- Applying patch fix_parallel_build_on_windows.patch
-- Applying patch fix-extra.patch
-- Applying patch mingw-dll-install.patch
-- Applying patch disable-static-prefix.patch
-- Applying patch fix-win-build.patch
-- Using source at /Users/moresteck/Documents/vcpkg/buildtrees/icu/src/c-72_1-src-deba61ed52.clean
-- Getting CMake variables for arm64-osx-dbg
-- Getting CMake variables for arm64-osx-rel
CMake Error at scripts/cmake/vcpkg_configure_make.cmake:618 (message):
  icu requires autoconf from the system package manager (example: "sudo
  apt-get install autoconf")
Call Stack (most recent call first):
  ports/icu/portfile.cmake:55 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)



```

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "name": "betacraft",
  "version-string": "2.0",
  "dependencies": [
    "curl",
    "json-c",
    "libzip",
    "qtbase"
  ]
}

```
</details>

**Comment by autoantwort** [comment]
Afaik QtCreator deletes brew from the PATH and therefore brew packages are not found. In the _Project_ -> _Build_ Settings you have to restore the system PATH by manually setting it.

**Comment by Moresteck** [comment]
Found a workaround — run the command which QtCreator executes in terminal, and it should install everything properly. Once that's done, QtC builds the project as it should.

Thanks nonetheless, @autoantwort, your solution seems to work when I add brew path to PATH in QtC manually.
I'd consider the issue solved.
