### ISSUE TITLE
libiconv:arm64-android fail with `/bin/sh: line 1: gcc: command not found`

### ISSUE THREAD

**Issue by shithappens2016** [microsoft/vcpkg#30280]
Somehow, the script tries to call gcc.
### build-arm64-android-rel-err.log ⇩
```
libtool: warning: remember to run 'libtool --finish /C/dev/vcpkg/installed/arm64-android/lib'
/bin/sh: line 1: gcc: command not found
windres: preprocessing failed.
make[1]: *** [Makefile:99: libiconv.res.lo] Error 1
```

```bash
-- Configuring arm64-android-rel
-- Building arm64-android-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/dev/vcpkg/downloads/tools/msys2/ca907ea16f6f2ba5/usr/bin/make.exe -j 5 --trace -f Makefile all
    Working Directory: C:/dev/vcpkg/buildtrees/libiconv/arm64-android-rel/
    See logs for more information:
      C:\dev\vcpkg\buildtrees\libiconv\build-arm64-android-rel-out.log
      C:\dev\vcpkg\buildtrees\libiconv\build-arm64-android-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:151 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:2 (vcpkg_build_make)
  ports/libiconv/portfile.cmake:39 (vcpkg_install_make)
  scripts/ports.cmake:147 (include)
```

**Comment by dg0yt** [comment]
Add more logs: The two ones being explicitly mentioned, and maybe also `config-arm64-android-dbg-config.log`.

**Comment by shithappens2016** [comment]
@dg0yt 

Is your system unable to reproduce this bug?

[config-arm64-android-rel-config.log](https://github.com/microsoft/vcpkg/files/11014946/config-arm64-android-rel-config.log)

[build-arm64-android-rel-err.log](https://github.com/microsoft/vcpkg/files/11014979/build-arm64-android-rel-err.log)

[build-arm64-android-rel-out.log](https://github.com/microsoft/vcpkg/files/11014948/build-arm64-android-rel-out.log)

[get-cmake-vars-arm64-android-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/11014958/get-cmake-vars-arm64-android-rel-CMakeCache.txt.log)

[Makefile.zip](https://github.com/microsoft/vcpkg/files/11014969/Makefile.zip)

**Comment by dg0yt** [comment]
> @dg0yt
> 
> Is your system unable to reproduce this bug?

I spent only part of my free time on a windows host, so you cannot expect me to reproduce it immediately. And to reproduce it reliably, we need to know the NDK you are using.

**Comment by dg0yt** [comment]
From `config.log`:
~~~
  $ ./../src/v1.17-84a471678e.clean/configure --build=x86_64-pc-mingw32 --host=aarch64-pc-mingw32 ... --prefix=/C/dev/vcpkg/installed/arm64-android ...
...
configure:5039: clang.exe --version >&5
Android (9352603, based on r450784d1) clang version 14.0.7 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0cca074e9238af8b4106c30add4418f6)
...
configure:6206: checking build system type
configure:6221: result: x86_64-pc-mingw32
configure:6241: checking host system type
configure:6255: result: aarch64-pc-mingw32
~~~
This is inconsistent. This is the desired compiler (clang from NDK), but not the desired "host" (autotools term) / target (vcpkg term). For arm64-android, the required option `--host=aarch64-linux-android` normally comes directly from the triplet:
https://github.com/microsoft/vcpkg/blob/12e66720d237142dfa01cd7b277dad220c13e19f/triplets/community/arm64-android.cmake#L5

**Comment by shithappens2016** [comment]
@dg0yt

the latest vcpkg solves this bug. thanks for taking the time to focus on this issue.
