### ISSUE TITLE
building openssl:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by zhaoh008** [microsoft/vcpkg#30292]
can't build x86-windows|x86-windows
-- Prerunning x86-windows-dbg
-- Building x86-windows-dbg
-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x86/nmake.exe" /NOLOGO /G /U /F makefile install_dev install_modules INSTALL_PDBS=ON
    Working Directory: D:/Tools/vcpkg/buildtrees/openssl/x86-windows-dbg
    See logs for more information:
      D:\Tools\vcpkg\buildtrees\openssl\install-x86-windows-dbg-nmake-out.log
      D:\Tools\vcpkg\buildtrees\openssl\install-x86-windows-dbg-nmake-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_nmake.cmake:156 (vcpkg_execute_build_process)
  ports/openssl/windows/portfile.cmake:50 (vcpkg_build_nmake)
  ports/openssl/portfile.cmake:63 (include)
  scripts/ports.cmake:147 (include)
[install-x86-windows-dbg-nmake-err.log](http
[install-x86-windows-dbg-nmake-out.log](https://github.com/microsoft/vcpkg/files/11013503/install-x86-windows-dbg-nmake-out.log)
s://github.com/microsoft/vcpkg/files/11013502/install-x86-windows-dbg-nmake-err.log)

**Comment by Cheney-W** [comment]
I can't reproduce this issue in my side, I can't even find a log named `install-x86-windows-dbg-nmake` locally.
I think you could run below commands: 
```
git pull
.\bootstrap-vcpkg.bat
.\vcpkg.exe install openssl:x86-windows --editable --binarysource=clear
```
If this issue still exists in your side, please provide me with the error logs. Thank you!

**Comment by dg0yt** [comment]
`nmake` is only used as a fallback. The default build tool is `jom`.

**Comment by Cheney-W** [comment]
@zhaoh008 Does this issue still occur in your side?

**Comment by zhaoh008** [comment]
I'm sorry, this was caused by the encryption software on my computer. The problem has been resolved now. Thank you for your answer
