### ISSUE TITLE
Error: Building package vtk:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by maorptz** [Microsoft/vcpkg#3030]
tried to install pcl[core]:x64-windows  and failed with:
Error: Building package vtk:x64-windows failed with: BUILD_FAILED

Package: vtk:x64-windows
 Vcpkg version: 0.0.105-2018-03-13-94360c2c65c6b38844ee75890d2be4632cdb4514

**Comment by miurahr** [comment]
Could you try a solution described in [another issue](https://github.com/Microsoft/vcpkg/issues/1797#issuecomment-377559384)?

**Comment by miurahr** [comment]
Similar to #2772 ?

**Comment by NancyLi1013** [comment]
Hi @maorptz , thanks for posting this issue. I can install the package successfully on my machine with the latest vcpkg now. Please open a new issue if this is still a problem for you.
