### ISSUE TITLE
B5cxx11 strings included in the installed lib

### ISSUE THREAD

**Issue by maitpate** [microsoft/vcpkg#30301]
Please create a discussion in https://github.com/microsoft/vcpkg/discussions/new instead.
I am trying to install vcpkg with gcc 11.3.0 version where in the installed library libjsoncpp.a , I am seeing these extra  strings B5cxx11 , I am using this package in another package which works on the older gcc only , hence I am getting undefined symbol error . generally passing ABI=0 works for packages like protocol buffer , but in this case it's not able to recognize the argument -D_GLIBCXX_USE_CXX11_ABI=0.  How can I solve this issue ?

**Comment by FrankXie05** [comment]
You can add this in your local corresponding triplet file.
```
set(VCPKG_C_FLAGS "-D_GLIBCXX_USE_CXX11_ABI=0")
set(VCPKG_CXX_FLAGS "-D_GLIBCXX_USE_CXX11_ABI=0")
```

**Comment by maitpate** [comment]
How do I pass them while installing the vcpkg itself so the installed lib itself doesn't get the strings B5cxx11 . Can we pass them with the below step ? 
./vcpkg install

**Comment by maitpate** [comment]
thanks for providing the pointer about the triplet file. I tried adding the above setting in the custom-triplets file and tried installing with this cmd  : 1) sudo vcpkg/vcpkg install sqlite3:x64-linux-dynamic --overlay-triplets=custom-triplets 
                                          2) sudo vcpkg/vcpkg install json
 
I am still getting the extra string "B5cxx11" in the installed library libjsoncpp.a . How can I verify that the given settings of ABI has taken place ?

**Comment by maitpate** [comment]
the issue has been solved by the following steps : 
sudo ./vcpkg install --triplet=x64-linux-dynamic zlib
sudo ./vcpkg install --triplet=x64-linux-dynamic jsoncpp
Thanks!

**Comment by dg0yt** [comment]
Do not use `sudo` here.
And please use https://github.com/microsoft/vcpkg/discussions/ for pure questions, as indicated in the issue template.
