### ISSUE TITLE
[libvpx] Build error

### ISSUE THREAD

**Issue by davistsin** [microsoft/vcpkg#30323]
**Host Environment**

- OS: Ubuntu20.04
- Compiler: revision

**To Reproduce**

`./vcpkg install libvpx:arm-android`

**Failure logs**
WUYING\admin_10486533464787@b7rwkrq1tit9zm6:~/vcpkg$ ./vcpkg install libvpx:arm-android
Computing installation plan...
The following packages will be built and installed:
    libvpx[core]:arm-android -> 1.12.0
Detecting compiler hash for triplet arm-android...
Restored 0 package(s) from /home/WUYING_admin_10486533464787/.cache/vcpkg/archives in 8.379 us. Use --debug to see more details.
Installing 1/1 libvpx:arm-android...
Building libvpx[core]:arm-android...
warning: -- Using community triplet arm-android. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /home/WUYING_admin_10486533464787/vcpkg/triplets/community/arm-android.cmake
-- Using cached webmproject-libvpx-v1.12.0.tar.gz.
-- Cleaning sources at /home/WUYING_admin_10486533464787/vcpkg/buildtrees/libvpx/src/v1.12.0-2729413caf.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/WUYING_admin_10486533464787/vcpkg/downloads/webmproject-libvpx-v1.12.0.tar.gz
-- Applying patch 0002-Fix-nasm-debug-format-flag.patch
-- Applying patch 0003-add-uwp-v142-and-v143-support.patch
-- Applying patch 0004-remove-library-suffixes.patch
-- Using source at /home/WUYING_admin_10486533464787/vcpkg/buildtrees/libvpx/src/v1.12.0-2729413caf.clean
CMake Error at ports/libvpx/portfile.cmake:182 (message):
  libvpx does not support architecture arm
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)

error: building libvpx:arm-android failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libvpx
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libvpx]+Build+error
Include '[libvpx] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-03-01-538539c4e364dd6f14f5e36f6704144254845159
    vcpkg-scripts version: e249dfb52 2023-03-20 (12 hours ago)

Please use the prefilled template from /home/WUYING_admin_10486533464787/vcpkg/installed/vcpkg/issue_body.md when reporting your issue.

**Additional context**

**Comment by freedbrt** [comment]
Try to build using 'arm-neon-android' triplet.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. `libvpx` doesn't support arm, please build it on `arm64-android`.
```
CMake Error at ports/libvpx/portfile.cmake:182 (message):
libvpx does not support architecture arm
```
