### ISSUE TITLE
[qtbase] Should have msg to install the correct dependencies for ubuntu

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#30329]
I install `qtbase` port from part to install gazebo port.
And I encounter the error: 
```
ERROR: Feature "xcb": Forcing to "ON" breaks its condition:
    QT_FEATURE_thread AND TARGET XCB::XCB AND TEST_xcb_syslibs AND QT_FEATURE_xkbcommon_x11
Condition values dump:
    QT_FEATURE_thread = "ON"
    TARGET XCB::XCB found
    TEST_xcb_syslibs = "FALSE"
    QT_FEATURE_xkbcommon_x11 not evaluated
```
I found the solution in old issue:
https://github.com/microsoft/vcpkg/issues/16486
We should tell the user to install this like we do in many ports:
We should put msg inside `qtbase` and `qt5-base` in portfile.cmake and let the user to install the correct dependencies in ubuntu:
`sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
`

**Comment by Cheney-W** [comment]
@talregev Do below tips in `qt5-base/portfile.cmake` meet your expectations?
```
CMake Warning at ports/qt5-base/portfile.cmake:4 (message):
  qt5-base currently requires some packages from the system package manager,
  see https://doc.qt.io/qt-5/linux-requirements.html

CMake Warning at ports/qt5-base/portfile.cmake:5 (message):
  qt5-base for qt5-x11extras requires several libraries from the system
  package manager.  Please refer to
    https://github.com/microsoft/vcpkg/blob/master/scripts/azure-pipelines/linux/provision-image.sh
    for a complete list of them.
```

**Comment by talregev** [comment]
> @talregev Do below tips in `qt5-base/portfile.cmake` meet your expectations?
> 
> ```
> CMake Warning at ports/qt5-base/portfile.cmake:4 (message):
>   qt5-base currently requires some packages from the system package manager,
>   see https://doc.qt.io/qt-5/linux-requirements.html
> 
> CMake Warning at ports/qt5-base/portfile.cmake:5 (message):
>   qt5-base for qt5-x11extras requires several libraries from the system
>   package manager.  Please refer to
>     https://github.com/microsoft/vcpkg/blob/master/scripts/azure-pipelines/linux/provision-image.sh
>     for a complete list of them.
> ```

@Cheney-W Thank you for the replay! I prefer that it tell me which packages I need to install other just send me to run the script. Because in this script there many stuff that not connected to the qt5-base nor qtbase.
Can you change it to the line I wrote?

**Comment by Cheney-W** [comment]
'^libxcb.*-dev' include 34 packages, are they all necessary?

**Comment by talregev** [comment]
> '^libxcb.*-dev' include 34 packages, are they all necessary?

I try some of them and it didn't work. I am not sure if needed all, but all is working.
Also it all the 34 packages is a small size.

**Comment by talregev** [comment]
this line:
`sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev`
Should be on qt5-base and qtbase ports.
