### ISSUE TITLE
[sqlite3] Build error

### ISSUE THREAD

**Issue by mitiops** [microsoft/vcpkg#30338]
**Host Environment**

- OS:  Windows
- Compiler: revision

**To Reproduce**

`./vcpkg install xxxx`

 cd ..
 git clone https://github.com/microsoft/vcpkg.git
 cd vcpkg
 clear
.\bootstrap-vcpkg.bat
.\vcpkg integrate install
.\vcpkg search sqlite3
.\vcpkg install sqlite3

**Failure logs**
error: building sqlite3:x86-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+sqlite3
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[sqlite3]+Build+error
Include '[sqlite3] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454
    vcpkg-scripts version: e249dfb52 2023-03-20 (19 hours ago)

**Additional context**
PS C:\src\vcpkg> .\bootstrap-vcpkg.bat
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2023-03-14/vcpkg.exe -> C:\src\vcpkg\vcpkg.exe... done.
Validating signature... done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md

**Comment by autoantwort** [comment]
Please attach the log files (Out of curiosity is there a reason why you haven't done that?)

**Comment by mitiops** [comment]
Even when I try to install other package I get the error : 
error: building boost-build:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-build
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-build]+Build+error
Include '[boost-build] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454
    vcpkg-scripts version: e249dfb52 2023-03-20 (20 hours ago)

**Comment by autoantwort** [comment]
You have to install an windows SDK

**Comment by FrankXie05** [comment]
@mitiops Thanks for posting this issue. Please make sure you have the following installed.

1. Visual Studio English Language Pack.
2. Visual Studio Desktop development with C++.
3. Windows 10 SDK or Windows 11 SDK.

**Comment by mitiops** [comment]
<img width="327" alt="Capture d’écran 2023-03-22 à 09 14 15" src="https://user-images.githubusercontent.com/128496442/226840214-896c07cd-9adc-48af-8583-38d8fb7b70c8.png">
<img width="327" alt="Capture d’écran 2023-03-22 à 09 14 07" src="https://user-images.githubusercontent.com/128496442/226840229-f73846c1-93a5-449f-9844-fbb5e943e588.png">
<img width="865" alt="Capture d’écran 2023-03-22 à 09 13 52" src="https://user-images.githubusercontent.com/128496442/226840238-43aa7299-1430-489e-8127-d18b0d8e82fc.png">
<img width="743" alt="Capture d’écran 2023-03-22 à 09 13 28" src="https://user-images.githubusercontent.com/128496442/226840818-d67e81b9-5f32-49bb-a54e-85c14ea8edae.png">

Hello, thank you for helping me. Here I put you in screenshot what I installed, I think I have installed everything.

**Comment by mitiops** [comment]
<img width="893" alt="Capture d’écran 2023-03-22 à 09 43 41" src="https://user-images.githubusercontent.com/128496442/226847851-ff515f87-a311-4dc1-8032-bd8464e19353.png">

**Comment by FrankXie05** [comment]
@mitiops Did you try again `./vcpkg install sqlite3:x64-windows` after you installed？

**Comment by mitiops** [comment]
<img width="838" alt="Capture d’écran 2023-03-22 à 12 09 34" src="https://user-images.githubusercontent.com/128496442/226886900-0f5276d6-cab2-44fc-858f-1b4e0ddeaacd.png">

yes still the same problem unfortunately

**Comment by mitiops** [comment]
I'm still stck ...
[config-x86-windows-dbg-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/11048462/config-x86-windows-dbg-CMakeCache.txt.log)
[config-x86-windows-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/11048463/config-x86-windows-rel-CMakeCache.txt.log)

**Comment by FrankXie05** [comment]
Sorry, one more thing to confirm. Did you install this component?
![cmake-install-2019](https://user-images.githubusercontent.com/65999885/227150469-801c6589-e8a8-47f8-9a55-31935480bbe0.png)

**Comment by mitiops** [comment]
it is installed fine, i found this forum, do you think it is from registry editor ?  https://developercommunity.visualstudio.com/t/resource-compiler-rcexe-is-not-recognized-as-an-in/1676970

**Comment by FrankXie05** [comment]
According to your log, your component has been broken. 🤔
```
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x86/cl.exe - broken
```

**Comment by mitiops** [comment]
How to fix it...? I uninstalled and reinstalled VS at least 3 times.

**Comment by FrankXie05** [comment]
Ah, I see. `Visual Studio Installer` was silently failing to install the `Windows SDK` because of some dirty registry keys from older versions that were essentially marking it as already installed, when it really wasn't. 

You can use removed them using`msiexec /x {guid}`. The guid can be found in the Windows SDK installation logs. 

The best way is manually install `Win SDK` using the administrator permission.

**Comment by mitiops** [comment]
It's good my problem is solved thank you I can see sqlite3 which is downloading without error but now when I try to use the packages on Visual Studio, Visual Studio does not find them...

**Comment by mitiops** [comment]
Yes it was indeed an administrative access problem with the registry editor. My problem is solved thank you!
