### ISSUE TITLE
[log4cxx] build failure

### ISSUE THREAD

**Issue by fcc315** [microsoft/vcpkg#30349]
**Host Environment**

- OS: Windows
- Compiler: MSVC 19.16.27048.0
vcpkg-tool version: 2023-03-01-538539c4e364dd6f14f5e36f6704144254845159
vcpkg-scripts version: dd1b57240 2023-03-09 (12 days ago)

**To Reproduce**

`vcpkg.exe install log4cxx:x64-windows`

**Failure logs**

- Console output:
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: D:/tools/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: D:/tools/vcpkg/buildtrees/log4cxx/x64-windows-dbg
    See logs for more information:
      D:\tools\vcpkg\buildtrees\log4cxx\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/log4cxx/portfile.cmake:23 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building log4cxx:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.

- Log output
D:\tools\vcpkg\buildtrees\log4cxx\src\-log4cxx-0-d45ab276bd.clean\src\main\cpp\threadutility.cpp(68): error C2065: 'ThreadConfigurationType': undeclared identifier
D:\tools\vcpkg\buildtrees\log4cxx\src\-log4cxx-0-d45ab276bd.clean\src\main\cpp\threadutility.cpp(68): error C2146: syntax error: missing ')' before identifier 'type'
D:\tools\vcpkg\buildtrees\log4cxx\src\-log4cxx-0-d45ab276bd.clean\src\main\cpp\threadutility.cpp(68): error C2143: syntax error: missing ';' before '{'
D:\tools\vcpkg\buildtrees\log4cxx\src\-log4cxx-0-d45ab276bd.clean\src\main\cpp\threadutility.cpp(68): error C2447: '{': missing function header (old-style formal list?)
D:\tools\vcpkg\buildtrees\log4cxx\src\-log4cxx-0-d45ab276bd.clean\src\main\cpp\threadutility.cpp(94): error C2065: 'ThreadStartPre': undeclared identifier
D:\tools\vcpkg\buildtrees\log4cxx\src\-log4cxx-0-d45ab276bd.clean\src\main\cpp\threadutility.cpp(94): error C2146: syntax error: missing ')' before identifier 'pre_start'
D:\tools\vcpkg\buildtrees\log4cxx\src\-log4cxx-0-d45ab276bd.clean\src\main\cpp\threadutility.cpp(96): error C2143: syntax error: missing ';' before '{'
D:\tools\vcpkg\buildtrees\log4cxx\src\-log4cxx-0-d45ab276bd.clean\src\main\cpp\threadutility.cpp(96): error C2447: '{': missing function header (old-style formal list?)
D:\tools\vcpkg\buildtrees\log4cxx\src\-log4cxx-0-d45ab276bd.clean\src\main\cpp\threadutility.cpp(115): error C2065: 'LogString': undeclared identifier
D:\tools\vcpkg\buildtrees\log4cxx\src\-log4cxx-0-d45ab276bd.clean\src\main\cpp\threadutility.cpp(115): error C2146: syntax error: missing ')' before identifier 'threadName'
D:\tools\vcpkg\buildtrees\log4cxx\src\-log4cxx-0-d45ab276bd.clean\src\main\cpp\threadutility.cpp(117): error C2143: syntax error: missing ';' before '{'
D:\tools\vcpkg\buildtrees\log4cxx\src\-log4cxx-0-d45ab276bd.clean\src\main\cpp\threadutility.cpp(117): error C2447: '{': missing function header (old-style formal list?)

**Comment by Adela0814** [comment]
@fcc315  Please provide the full failure log `D:\tools\vcpkg\buildtrees\log4cxx\install-x64-windows-dbg-out.log`, thanks.

**Comment by Adela0814** [comment]
This is a VS issue and will only recur in `vs2017`. Please upgrade your VS version to `vs2019` or `vs2022`.
