### ISSUE TITLE
The overrides field of the port's vcpkg.json as well as the top level vcpkg.json should be applied.

### ISSUE THREAD

**Issue by recsater** [microsoft/vcpkg#30346]
****

**Is your feature request related to a problem? Please describe.**
https://github.com/microsoft/vcpkg/discussions/30328

The link above provides a detailed explanation, but to make it simpler, it's as follows.

If I overrides to use the implot 0.12 version in a project, I get an error.

This is because the implot 0.12 version is compatible with versions less than imgui 1.86.

The build fails because the latest version of imgui is 1.89.3, and packages with dependencies described on the port always get the latest version.

In order for me to build a project correctly, I need to know that the implot 0.12 version is compatible with less than imgui 1.86, and I need to override imgui 1.85 on my vcpkg.json.

But this doesn't seem ideal. I think it is ideal to impose version constraints on port files.

**Proposed solution**
The overrides field of the port's vcpkg.json as well as the top level vcpkg.json should be applied.

**Comment by autoantwort** [comment]
The idea is that you use a baseline where the implot version is 0.12, then you also get an compatible imgui version. If you use the baseline `31c711c68ec5c46500c00e30d6f9cbbe5376e87f` everything should be fine without using any override

**Comment by recsater** [comment]
> The idea is that you use a baseline where the implot version is 0.12, then you also get an compatible imgui version. If you use the baseline `31c711c68ec5c46500c00e30d6f9cbbe5376e87f` everything should be fine without using any override

In that case, there is a problem when using other packages together.
