### ISSUE TITLE
[bzip2] Build error - Error trying to install wxwidgets package on MacOS Ventura

### ISSUE THREAD

**Issue by piyushraju** [microsoft/vcpkg#30354]
vcpkg-tool version: 2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454
    vcpkg-scripts version: ae59b93af 2023-03-21 (10 hours ago)
[issue_body.md](https://github.com/microsoft/vcpkg/files/11037169/issue_body.md)

**Comment by jimwang118** [comment]
```
Could not find pkg-config.  Please install it via your package manager:

      brew install pkg-config
```
You need to have pkg-config installed on your system, use the command suggested above.

**Comment by piyushraju** [comment]
Hi Jim,

Thanks so much for you help!

I could install pkg-config successfully using brew. However when I tried to
install wxwidgets package I got this new error message:

***@***.*** Includes % sudo ./vcpkg/vcpkg install
wxwidgets

Password:

Computing installation plan...

The following packages will be built and installed:

  * bzip2[core,tool]:arm64-osx -> 1.0.8#3

  * egl-registry[core]:arm64-osx -> 2022-09-20

  * expat[core]:arm64-osx -> 2.5.0#3

  * libiconv[core]:arm64-osx -> 1.17#1

  * libjpeg-turbo[core]:arm64-osx -> 2.1.5.1

  * liblzma[core]:arm64-osx -> 5.4.1#1

  * libpng[core]:arm64-osx -> 1.6.39#1

  * nanosvg[core]:arm64-osx -> 2022-12-04

  * opengl[core]:arm64-osx -> 2022-12-04#3

  * opengl-registry[core]:arm64-osx -> 2022-09-29#1

  * pcre2[core]:arm64-osx -> 10.40#1

  * tiff[core,jpeg,lzma,zip]:arm64-osx -> 4.5.0#2

    wxwidgets[core,debug-support,sound]:arm64-osx -> 3.2.2.1#1

  * zlib[core]:arm64-osx -> 1.2.13

Additional packages (*) will be modified to complete this operation.

Detecting compiler hash for triplet arm64-osx...

Restored 0 package(s) from /Users/piyushraju/.cache/vcpkg/archives in
428.333 us. Use --debug to see more details.

Installing 1/14 bzip2:arm64-osx...

Building bzip2[core,tool]:arm64-osx...

warning: -- Using community triplet arm64-osx. This triplet configuration
is not guaranteed to succeed.

-- [COMMUNITY] Loading triplet configuration from:
/Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/triplets/community/arm64-osx.cmake

-- Using cached bzip2-1.0.8.tar.gz.

-- Cleaning sources at /Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/buildtrees/bzip2/src/bzip2-1-336d4794a3.clean.
Use --editable to skip cleaning for the packages you specify.

-- Extracting source /Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/downloads/bzip2-1.0.8.tar.gz

-- Applying patch fix-import-export-macros.patch

-- Using source at /Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/buildtrees/bzip2/src/bzip2-1-336d4794a3.clean

-- Configuring arm64-osx

-- Building arm64-osx-dbg

-- Building arm64-osx-rel

-- Fixing pkgconfig file:
/Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/packages/bzip2_arm64-osx/lib/pkgconfig/bzip2.pc

-- Fixing pkgconfig file:
/Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/packages/bzip2_arm64-osx/debug/lib/pkgconfig/bzip2.pc

-- Installing: /Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/packages/bzip2_arm64-osx/share/bzip2/copyright

-- Performing post-build validation

Stored binary cache:
"/Users/piyushraju/.cache/vcpkg/archives/82/82bf5825072f24241484e4977c0114944d387bb6bd5da85b602a6a572482227b.zip"

Elapsed time to handle bzip2:arm64-osx: 2.461391583 s

Installing 2/14 egl-registry:arm64-osx...

Building egl-registry[core]:arm64-osx...

warning: -- Using community triplet arm64-osx. This triplet configuration
is not guaranteed to succeed.

-- [COMMUNITY] Loading triplet configuration from:
/Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/triplets/community/arm64-osx.cmake

-- Downloading
https://github.com/KhronosGroup/EGL-Registry/archive/af97e2c27b49a090a335fc6ed5040c780ad9fec8.tar.gz
->
KhronosGroup-EGL-Registry-af97e2c27b49a090a335fc6ed5040c780ad9fec8.tar.gz...

-- Extracting source /Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/downloads/KhronosGroup-EGL-Registry-af97e2c27b49a090a335fc6ed5040c780ad9fec8.tar.gz

-- Using source at /Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/buildtrees/egl-registry/src/780ad9fec8-51aa70c4bd.clean

-- Installing: /Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/packages/egl-registry_arm64-osx/share/egl-registry/copyright

-- Performing post-build validation

Stored binary cache:
"/Users/piyushraju/.cache/vcpkg/archives/cb/cbaa46d5de56d013a3b9df6a1d494cdf3fe245e2105497bf9f90cea75335c524.zip"

Elapsed time to handle egl-registry:arm64-osx: 2.117635125 s

Installing 3/14 expat:arm64-osx...

Building expat[core]:arm64-osx...

warning: -- Using community triplet arm64-osx. This triplet configuration
is not guaranteed to succeed.

-- [COMMUNITY] Loading triplet configuration from:
/Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/triplets/community/arm64-osx.cmake

-- Downloading https://github.com/libexpat/libexpat/archive/R_2_5_0.tar.gz
-> libexpat-libexpat-R_2_5_0.tar.gz...

-- Extracting source /Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/downloads/libexpat-libexpat-R_2_5_0.tar.gz

-- Using source at /Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/buildtrees/expat/src/R_2_5_0-56671c0753.clean

-- Configuring arm64-osx

-- Building arm64-osx-dbg

-- Building arm64-osx-rel

-- Fixing pkgconfig file:
/Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/packages/expat_arm64-osx/lib/pkgconfig/expat.pc

-- Fixing pkgconfig file:
/Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/packages/expat_arm64-osx/debug/lib/pkgconfig/expat.pc

-- Installing: /Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/packages/expat_arm64-osx/share/expat/copyright

-- Performing post-build validation

Stored binary cache:
"/Users/piyushraju/.cache/vcpkg/archives/cd/cd0c79fd73cae25632ea28466ac96a3b8486d774756b03ca2248f1dba9f4a22d.zip"

Elapsed time to handle expat:arm64-osx: 7.185792042 s

Installing 4/14 libiconv:arm64-osx...

Building libiconv[core]:arm64-osx...

warning: -- Using community triplet arm64-osx. This triplet configuration
is not guaranteed to succeed.

-- [COMMUNITY] Loading triplet configuration from:
/Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/triplets/community/arm64-osx.cmake

-- Performing post-build validation

Stored binary cache:
"/Users/piyushraju/.cache/vcpkg/archives/92/92ba370bd10cd9e7e38d5aa8a856154b08d12468f4f581f14577edcb2eaf7b42.zip"

Elapsed time to handle libiconv:arm64-osx: 36.008708 ms

Installing 5/14 libjpeg-turbo:arm64-osx...

Building libjpeg-turbo[core]:arm64-osx...

warning: -- Using community triplet arm64-osx. This triplet configuration
is not guaranteed to succeed.

-- [COMMUNITY] Loading triplet configuration from:
/Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/triplets/community/arm64-osx.cmake

-- Downloading
https://github.com/libjpeg-turbo/libjpeg-turbo/archive/2.1.5.1.tar.gz ->
libjpeg-turbo-libjpeg-turbo-2.1.5.1.tar.gz...

-- Extracting source /Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/downloads/libjpeg-turbo-libjpeg-turbo-2.1.5.1.tar.gz

-- Applying patch add-options-for-exes-docs-headers.patch

-- Applying patch workaround_cmake_system_processor.patch

-- Using source at /Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/buildtrees/libjpeg-turbo/src/2.1.5.1-f411453282.clean

-- Configuring arm64-osx

-- Building arm64-osx-dbg

-- Building arm64-osx-rel

-- Fixing pkgconfig file:
/Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/packages/libjpeg-turbo_arm64-osx/lib/pkgconfig/libjpeg.pc

-- Fixing pkgconfig file:
/Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/packages/libjpeg-turbo_arm64-osx/lib/pkgconfig/libturbojpeg.pc

-- Fixing pkgconfig file:
/Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/packages/libjpeg-turbo_arm64-osx/debug/lib/pkgconfig/libjpeg.pc

-- Fixing pkgconfig file:
/Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/packages/libjpeg-turbo_arm64-osx/debug/lib/pkgconfig/libturbojpeg.pc

-- Installing: /Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/packages/libjpeg-turbo_arm64-osx/share/libjpeg-turbo/copyright

-- Performing post-build validation

Stored binary cache:
"/Users/piyushraju/.cache/vcpkg/archives/13/13bc4cce93b84fc75062180ca5e73ea3651be49a8e096a300c69f9cae49113fc.zip"

Elapsed time to handle libjpeg-turbo:arm64-osx: 11.870267333 s

Installing 6/14 liblzma:arm64-osx...

Building liblzma[core]:arm64-osx...

warning: -- Using community triplet arm64-osx. This triplet configuration
is not guaranteed to succeed.

-- [COMMUNITY] Loading triplet configuration from:
/Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/triplets/community/arm64-osx.cmake

-- Downloading
https://sourceforge.net/projects/lzmautils//files/xz-5.4.1.tar.xz/download;https://sourceforge.net/projects/lzmautils//files/xz-5.4.1.tar.xz/download?use_mirror=cfhcable;https://sourceforge.net/projects/lzmautils//files/xz-5.4.1.tar.xz/download?use_mirror=pilotfiber;https://sourceforge.net/projects/lzmautils//files/xz-5.4.1.tar.xz/download?use_mirror=gigenet;https://sourceforge.net/projects/lzmautils//files/xz-5.4.1.tar.xz/download?use_mirror=versaweb;https://sourceforge.net/projects/lzmautils//files/xz-5.4.1.tar.xz/download?use_mirror=ayera;https://sourceforge.net/projects/lzmautils//files/xz-5.4.1.tar.xz/download?use_mirror=netactuate;https://sourceforge.net/projects/lzmautils//files/xz-5.4.1.tar.xz/download?use_mirror=phoenixnap;https://sourceforge.net/projects/lzmautils//files/xz-5.4.1.tar.xz/download?use_mirror=astuteinternet;https://sourceforge.net/projects/lzmautils//files/xz-5.4.1.tar.xz/download?use_mirror=freefr;https://sourceforge.net/projects/lzmautils//files/xz-5.4.1.tar.xz/download?use_mirror=netcologne;https://sourceforge.net/projects/lzmautils//files/xz-5.4.1.tar.xz/download?use_mirror=deac-riga;https://sourceforge.net/projects/lzmautils//files/xz-5.4.1.tar.xz/download?use_mirror=excellmedia;https://sourceforge.net/projects/lzmautils//files/xz-5.4.1.tar.xz/download?use_mirror=iweb;https://sourceforge.net/projects/lzmautils//files/xz-5.4.1.tar.xz/download?use_mirror=jaist;https://sourceforge.net/projects/lzmautils//files/xz-5.4.1.tar.xz/download?use_mirror=jztkft;https://sourceforge.net/projects/lzmautils//files/xz-5.4.1.tar.xz/download?use_mirror=managedway;https://sourceforge.net/projects/lzmautils//files/xz-5.4.1.tar.xz/download?use_mirror=nchc;https://sourceforge.net/projects/lzmautils//files/xz-5.4.1.tar.xz/download?use_mirror=netix;https://sourceforge.net/projects/lzmautils//files/xz-5.4.1.tar.xz/download?use_mirror=ufpr;https://sourceforge.net/projects/lzmautils//files/xz-5.4.1.tar.xz/download?use_mirror=tenet
-> xz-5.4.1.tar.xz...

-- Extracting source /Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/downloads/xz-5.4.1.tar.xz

-- Applying patch fix_config_include.patch

-- Applying patch win_output_name.patch

-- Applying patch add_support_ios.patch

-- Applying patch build-tools.patch

-- Using source at /Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/buildtrees/liblzma/src/f890ee5207-326fe62969.clean

-- Configuring arm64-osx

-- Building arm64-osx-dbg

-- Building arm64-osx-rel

-- Fixing pkgconfig file:
/Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/packages/liblzma_arm64-osx/lib/pkgconfig/liblzma.pc

-- Fixing pkgconfig file:
/Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/packages/liblzma_arm64-osx/debug/lib/pkgconfig/liblzma.pc

-- Installing: /Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/packages/liblzma_arm64-osx/share/liblzma/copyright

-- Performing post-build validation

Stored binary cache:
"/Users/piyushraju/.cache/vcpkg/archives/7c/7ce8114df6ba766710281c9e0a8ef0900dceffcb7609c5cb69144b753e78e604.zip"

Elapsed time to handle liblzma:arm64-osx: 8.635625666 s

Installing 7/14 zlib:arm64-osx...

Building zlib[core]:arm64-osx...

warning: -- Using community triplet arm64-osx. This triplet configuration
is not guaranteed to succeed.

-- [COMMUNITY] Loading triplet configuration from:
/Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/triplets/community/arm64-osx.cmake

-- Downloading https://github.com/madler/zlib/archive/v1.2.13.tar.gz ->
madler-zlib-v1.2.13.tar.gz...

-- Extracting source /Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/downloads/madler-zlib-v1.2.13.tar.gz

-- Applying patch
0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch

-- Applying patch 0002-skip-building-examples.patch

-- Applying patch 0003-build-static-or-shared-not-both.patch

-- Applying patch 0004-android-and-mingw-fixes.patch

-- Using source at /Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/buildtrees/zlib/src/v1.2.13-f30d2a168d.clean

-- Configuring arm64-osx

-- Building arm64-osx-dbg

-- Building arm64-osx-rel

-- Installing: /Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/packages/zlib_arm64-osx/share/zlib/vcpkg-cmake-wrapper.cmake

-- Fixing pkgconfig file:
/Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/packages/zlib_arm64-osx/lib/pkgconfig/zlib.pc

-- Fixing pkgconfig file:
/Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/packages/zlib_arm64-osx/debug/lib/pkgconfig/zlib.pc

-- Installing: /Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/packages/zlib_arm64-osx/share/zlib/copyright

-- Performing post-build validation

Stored binary cache:
"/Users/piyushraju/.cache/vcpkg/archives/17/17125fe29d1020b982b19bb4e6084f486449c2786faca9daa3b23c2e09813470.zip"

Elapsed time to handle zlib:arm64-osx: 3.933592042 s

Installing 8/14 libpng:arm64-osx...

Building libpng[core]:arm64-osx...

warning: -- Using community triplet arm64-osx. This triplet configuration
is not guaranteed to succeed.

-- [COMMUNITY] Loading triplet configuration from:
/Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/triplets/community/arm64-osx.cmake

-- Downloading https://github.com/glennrp/libpng/archive/v1.6.39.tar.gz ->
glennrp-libpng-v1.6.39.tar.gz...

-- Extracting source /Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/downloads/glennrp-libpng-v1.6.39.tar.gz

-- Applying patch cmake.patch

-- Applying patch fix-export-targets.patch

-- Applying patch pkgconfig.patch

-- Applying patch fix-msa-support-for-mips.patch

-- Using source at /Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/buildtrees/libpng/src/v1.6.39-a77eb96d39.clean

-- Configuring arm64-osx

-- Building arm64-osx-dbg

CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134
(message):

    Command failed: "/Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/downloads/tools/cmake-3.25.1-osx/cmake-3.25.1-macos-universal/CMake.app/Contents/bin/cmake"
--build . --config Debug --target install -- -v -j9

    Working Directory: /Users/piyushraju/Library/CloudStorage/Dropbox/Mac
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/buildtrees/libpng/arm64-osx-dbg

    See logs for more information:

      /Users/piyushraju/Library/CloudStorage/Dropbox/Mac\
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/buildtrees/libpng/install-arm64-osx-dbg-out.log


Call Stack (most recent call first):

  installed/arm64-osx/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74
(vcpkg_execute_build_process)

  installed/arm64-osx/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16
(vcpkg_cmake_build)

  ports/libpng/portfile.cmake:85 (vcpkg_cmake_install)

  scripts/ports.cmake:147 (include)



error: building libpng:arm64-osx failed with: BUILD_FAILED

read_contents("/Users/piyushraju/Library/CloudStorage/Dropbox/Mac\
(2)/Documents/PR_Programs/Cpp_Programs/Includes/vcpkg/buildtrees/libpng/install-arm64-osx-dbg-out.log"):
No such file or directory

***@***.*** Includes %

I really appreciate any help in this regard.

Kind regards
Piyush

**Comment by jimwang118** [comment]
I am very sorry, the underlying architecture of the notebook you are using is `arm64`. At present, our `vcpkg` has not adapted this triplet yet. It is expected that we can install it normally after the version adaptation of our `vcpkg-tool`.

**Comment by piyushraju** [comment]
Hi Jim,

Thanks for the update. I wanted to know a couple of things:
- When can I approximately expect support for arm64 in the vcpkg-tool?
- OR is there a way I can be notified when the support for arm64 comes
through?

Thanks for your help!
Kind regards
Piyush

**Comment by pateruu** [comment]
@jimwang118 I also keep getting errors when trying to download cpr, etc. is it because I also have arm64 and its not supported?

**Comment by jimwang118** [comment]
> @jimwang118 I also keep getting errors when trying to download cpr, etc. is it because I also have arm64 and its not supported?

Yes, currently we do not adapt to the arm platform.

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
