### ISSUE TITLE
[boost-rational] Build error

### ISSUE THREAD

**Issue by zhangguochang** [microsoft/vcpkg#30351]
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Restored 0 package(s) from /home/maiyuan/.cache/vcpkg/archives in 90.285 us. Use --debug to see more details.
Installing 1/110 boost-rational:x64-linux...
Building boost-rational[core]:x64-linux...
-- Downloading https://github.com/boostorg/rational/archive/boost-1.81.0.tar.gz -> boostorg-rational-boost-1.81.0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from /maiyuan/software/vcpkg/vcpkg-bundle.json
[DEBUG] Failed to open: /maiyuan/software/vcpkg/vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] 1000: popen( curl --fail -L https://github.com/boostorg/rational/archive/boost-1.81.0.tar.gz --create-dirs --output /maiyuan/software/vcpkg/downloads/boostorg-rational-boost-1.81.0.tar.gz.2486667.part 2>&1)
[DEBUG] 1000: cmd_execute_and_stream_data() returned 35 after  5123292 us
error: Failed to download from mirror set
error: https://github.com/boostorg/rational/archive/boost-1.81.0.tar.gz: curl failed to download with exit code 35
 
 
%
 
T
o
t
a
l
 
 
 
 
%
 
R
e
c
e
i
v
e
d
 
%
 
X
f
e
r
d
 
 
A
v
e
r
a
g
e
 
S
p
e
e
d
 
 
 
T
i
m
e
 
 
 
 
T
i
m
e
 
 
 
 
 
T
i
m
e
 
 
C
u
r
r
e
n
t

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
D
l
o
a
d
 
 
U
p
l
o
a
d
 
 
 
T
o
t
a
l
 
 
 
S
p
e
n
t
 
 
 
 
L
e
f
t
 
 
S
p
e
e
d

c
u
r
l
:
 
(
3
5
)
 
O
p
e
n
S
S
L
 
S
S
L
_
c
o
n
n
e
c
t
:
 

¿
 

 
¥

¢
«

¯
¹

 
¹

 
 

®
¾
 
i
n
 
c
o
n
n
e
c
t
i
o
n
 
t
o
 
g
i
t
h
u
b
.
c
o
m
:
4
4
3
 

[DEBUG] /mnt/vss/_work/1/s/src/vcpkg/base/downloads.cpp(960): 
[DEBUG] Time in subprocesses: 5123292us
[DEBUG] Time in parsing JSON: 2us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 56us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 5.123777707 s (5123585us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
      

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/boost-rational/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:147 (include)

error: building boost-rational:x64-linux failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-rational
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-rational]+Build+error
Include '[boost-rational] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454
    vcpkg-scripts version: ae59b93af 2023-03-21 (7 小时前)

Please use the prefilled template from /maiyuan/software/vcpkg/installed/vcpkg/issue_body.md when reporting your issue.

the command line is:./vcpkg install colmap[cuda,tests]:x64-linux

**Comment by Cheney-W** [comment]
I can't reproduce this issue in my side. I could download the `https://github.com/boostorg/rational/archive/boost-1.81.0.tar.gz` successfully whether it is downloaded in vcpkg or manually.

This may be a temporary network fluctuation issue, or it may be affected by a firewall. If you still cannot download this package through vcpkg, you can download it manually, and then put it under `vcpkg\downloads` folder.

Or you can use this package: 
[rational-boost-1.81.0.tar.gz](https://github.com/microsoft/vcpkg/files/11037421/rational-boost-1.81.0.tar.gz)

**Comment by Cheney-W** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
