### ISSUE TITLE
[New Port Request] <CEF>

### ISSUE THREAD

**Issue by WangHHY19931001** [microsoft/vcpkg#30352]
Library name:CEF

Library description:Chromium Embedded Framework (CEF). A simple framework for embedding Chromium-based browsers in other applications.

Source repository URL:https://bitbucket.org/chromiumembedded/cef/src/master/

Project homepage (if different from the source repository):https://bitbucket.org/chromiumembedded/cef/src/master/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by wh1t3lord** [comment]
A

**Comment by wh1t3lord** [comment]
A

**Comment by renaud-sc** [comment]
Having CEF in vcpkg would be very valuable indeed. But Microsoft is pushing WebView2 so CEF is probably not a priority. I guess it needs to come from the community.

**Comment by renaud-sc** [comment]
This issue relates to/is a duplicate of [this one](https://github.com/microsoft/vcpkg/issues/332)

**Comment by WangHHY19931001** [comment]
> Having CEF in vcpkg would be very valuable indeed. But Microsoft is pushing WebView2 so CEF is probably not a priority. I guess it needs to come from the community.

if WebView2 can work in linux or mac i will not ask add it

**Comment by renaud-sc** [comment]
I am not sure WebView2 provides any benefits on mac and Linux. Users are unlikely to use Edge on these platforms so you probably want to bundle WebView2 with your application installer making it as big as CEF or Electron.

**Comment by wh1t3lord** [comment]
It is reasonable to use CEF and add it to vcpkg, but I hope someone or some group of people will add a such support in some time. 

Better to create another issue related to WebView2 and its adding to vcpkg @renaud-sc

**Comment by wh1t3lord** [comment]
sas

**Comment by wh1t3lord** [comment]
a

**Comment by wh1t3lord** [comment]
a

**Comment by sfhacker** [comment]
This open issue is over a year old!
Let’s keep insisting/praying.
