### ISSUE TITLE
安装colmap的gpu版本，报错/usr/bin/bash: ./../src/nssl-3.1.0-1ebd9e680e.clean/vcpkg/configure: 权限不够How do I ...

### ISSUE THREAD

**Issue by zhangguochang** [microsoft/vcpkg#30357]
安装colmap的gpu版本，报错/usr/bin/bash: ./../src/nssl-3.1.0-1ebd9e680e.clean/vcpkg/configure: 权限不够How do I ...

**Comment by FrankXie05** [comment]
@zhangguochang Could you please provide a complete error log?

**Comment by zhangguochang** [comment]
> @zhangguochang能否请您提供完整的错误日志？
all log is as follow:
/usr/bin/bash: ./../src/nssl-3.1.0-1ebd9e680e.clean/vcpkg/configure: 权限不够

the command line is:

sudo ./vcpkg install colmap[cuda]:x64-linux

**Comment by zhangguochang** [comment]
> > @zhangguochang
> > 能不能请
> > 您提供完整的错误日志？
> 
> 命令行是：
> 
> sudo ./vcpkg install colmap[cuda]:x64-linux
 
whole error log is:

/usr/bin/bash: ./../src/nssl-3.1.0-1ebd9e680e.clean/vcpkg/configure: 权限不够

**Comment by FrankXie05** [comment]
@zhangguochang Could you please try command `sudo echo "hello"` ?

**Comment by FrankXie05** [comment]
The command `sudo` only grants some permissions to the current user, please switch to the root user.

**Comment by zhangguochang** [comment]
> 

sudo su root
the error still exist

**Comment by dg0yt** [comment]
Please write this 100 times:
"I shall use `sudo` only for system maintenance, not for running `vcpkg`."

**Comment by longhuan2018** [comment]
Add executable permissions to file "ports/openssl/unix/configure"
![image](https://github.com/microsoft/vcpkg/assets/8551701/7f7b767b-7fb9-4a6c-acad-1f2876a8c4c5)
