### ISSUE TITLE
[wxwidgets] now depends on NanoSVG, but it doesn't have it in the wx-config file

### ISSUE THREAD

**Issue by AenBleidd** [microsoft/vcpkg#30361]
After #29998 wxWidgets depends on NanoSVG, but when build with it, there is no NanoSVG dependency (libnanosvg.a and libnanosvgrast.a) library in the wx-config file that leads to build error when linking to wx-widgets

@Neumann-A, might be interesting to you

**Comment by AenBleidd** [comment]
Additional note: before #29998 `nanosvg` was used in `wxwidgets` as a header-only library, so there was no need to provide a `nanosvg` library for linkage. Now this has been changed, so either `nanosvg` should generate pkgconfig or wx-congig should include this dependency

**Comment by Neumann-A** [comment]
> wx-config should include this dependency

This but it is really an upstream issue.

**Comment by AenBleidd** [comment]
> > wx-config should include this dependency
> 
> 
> 
> This but it is really an upstream issue. 
> 
> 

Ok, I'll try to fix this upstream and patch it here while waiting for it to be approved and released.
