### ISSUE TITLE
Detect cross compiles

### ISSUE THREAD

**Issue by donny-dont** [microsoft/vcpkg#3036]
Currently vcpkg does not provide a mechanism to detect whether a cross compile is happening. There are certain libraries that use `try_run`, such as curl, which attempts to compile and run source code to detect functionality. CMake docs are [here](https://cmake.org/cmake/help/v3.11/command/try_run.html).

Within the portfile.cmake the `CMAKE_CROSSCOMPILING` variable is not set so there's no way to detect it within a portfile.

Perhaps there should be a `VCPKG_CROSSCOMPILING` variable?

**Comment by ras0219-msft** [comment]
Thanks for posting this issue!

Can you give more concrete details about your scenario? Ideally, something like `vcpkg install curl:<something>` fails because xyz and knowing `CMAKE_CROSSCOMPILING` fixes it.

**Comment by donny-dont** [comment]
@ras0219-msft thanks for the speedy reply.

So as an example curl uses `try_run` in [here](https://github.com/curl/curl/blob/curl-7_59_0/CMakeLists.txt#L976-L981)

If you are cross compiling then you get a message like this.
```
-- Performing Curl Test HAVE_GLIBC_STRERROR_R
CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
   HAVE_GLIBC_STRERROR_R (advanced)
   HAVE_GLIBC_STRERROR_R__TRYRUN_OUTPUT (advanced)
```

So ideally in the portfile it would be nice to check if its a cross compile and if so then do something like this.

```
if (VCPKG_CROSSCOMPILING)
    list(APPEND BUILD_OPTIONS HAVE_GLIBC_STRERROR_R=0)
    ...
endif ()
```

**Comment by MikeGitb** [comment]
Can't you get that information from the target triple? I assume cross compilation e.g. means e.g. arm-windows

**Comment by donny-dont** [comment]
Yes in the standard triplets that would be arm but its also potentially useful for custom triplets with different toolchains.

**Comment by Tryum** [comment]
About CMAKE_CROSSCOMPILING, you can build any cmake based port as x**-uwp
which will be considered as cross compiling.
Some packages are not "uwp compatible" because of that, as some header
generating binaries are built as UWP binaries, and cannot be executed.

I have some fixes for some packages I need to clean, commit and send PRs.

Thibault Jochem
Software Engineer
EFREI Promo 2007

**Comment by NancyLi1013** [comment]
Similar issue #9390. Seems to be inactive for a long time. So let's move the discussion there.
