### ISSUE TITLE
[ogre] Don't have all the includes

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#30376]
**Describe the bug**

I try compile gazebo that use ogre library. 
It use this include file:
https://github.com/OGRECave/ogre/blob/v13.6.2/Components/RTShaderSystem/src/OgreShaderGLSLProgramWriter.h
But this include file is missing. 

**Environment**
- OS: wsl2 ubuntu 22.04
- Compiler: gcc 11.3

**To Reproduce**
1. `./vcpkg install ogre[assimp,freeimage,overlay,zip]`
2. missing `OgreShaderGLSLProgramWriter.h`

**Expected behavior**
Have the include `OgreShaderGLSLProgramWriter.h`

**Failure logs**
No failure logs

**Additional context**
For this bug missing more includes then just this include. It an example. I don't have the full list of all the include that missing. 

If regular logs are needed, I will happy provided them. Just ask on the comment.

**Comment by talregev** [comment]
@autoantwort This is a private header that gazebo use it. Should I patch and add the header and that cpp file for compile gazebo?

**Comment by Adela0814** [comment]
> @autoantwort This is a private header that gazebo use it. Should I patch and add the header and that cpp file for compile gazebo? Path and add ogre header and cpp file when I compile gazebo.

You can do this during your local testing.

**Comment by Adela0814** [comment]
Closed due to not an issue.
