### ISSUE TITLE
[New Port Request] opencore-amr

### ISSUE THREAD

**Issue by pedoc** [microsoft/vcpkg#30375]
Library name:
opencore-amr

Library description:
Library of OpenCORE Framework implementation of Adaptive Multi Rate Narrowband and Wideband (AMR-NB and AMR-WB) speech codec. Library of VisualOn implementation of Adaptive Multi Rate Wideband (AMR-WB) encoder and Advanced Audio Coding (AAC) encoder. Modified library of Fraunhofer AAC decoder and encoder.

Source repository URL:
https://sourceforge.net/projects/opencore-amr/

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

[vo-aacenc](https://sourceforge.net/projects/opencore-amr/files/vo-aacenc/)
[vo-amrwbenc](https://sourceforge.net/projects/opencore-amr/files/vo-amrwbenc/)

**Comment by pedoc** [comment]
ping 😄

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
