### ISSUE TITLE
[opencv4[cuda]] Build error

### ISSUE THREAD

**Issue by ReFantasy** [microsoft/vcpkg#30384]
Computing installation plan...
The following packages will be built and installed:
    opencv4[contrib,core,cuda,cudnn,default-features,dnn,gtk,jpeg,png,quirc,tiff,webp]:x64-linux -> 4.7.0#3
Detecting compiler hash for triplet x64-linux...
Restored 0 package(s) from /home/tdl/.cache/vcpkg/archives in 10.86 us. Use --debug to see more details.
Installing 1/1 opencv4:x64-linux...
Building opencv4[contrib,core,cuda,cudnn,default-features,dnn,gtk,jpeg,png,quirc,tiff,webp]:x64-linux...
-- Using cached opencv-opencv-4.7.0-1.tar.gz.
-- Cleaning sources at /home/tdl/Software/vcpkg/buildtrees/opencv4/src/4.7.0-34a2240496.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/tdl/Software/vcpkg/downloads/opencv-opencv-4.7.0-1.tar.gz
-- Applying patch 0001-disable-downloading.patch
-- Applying patch 0002-install-options.patch
-- Applying patch 0003-force-package-requirements.patch
-- Applying patch 0004-fix-eigen.patch
-- Applying patch 0005-fix-policy-CMP0057.patch
-- Applying patch 0006-fix-uwp.patch
-- Applying patch 0008-devendor-quirc.patch
-- Applying patch 0009-fix-protobuf.patch
-- Applying patch 0010-fix-uwp-tiff-imgcodecs.patch
-- Applying patch 0011-remove-python2.patch
-- Applying patch 0012-fix-zlib.patch
-- Applying patch 0015-fix-freetype.patch
-- Using source at /home/tdl/Software/vcpkg/buildtrees/opencv4/src/4.7.0-34a2240496.clean
-- Using cached opencv-cache/tiny_dnn/adb1c512e09ca2c7a6faef36f9c53e59-v1.0.0a3.tar.gz.
-- Using cached opencv-cache/nvidia_optical_flow/a73cd48b18dcc0cc8933b30796074191-edb50da3cf849840d680249aa6dbef248ebce2ca.zip.
-- Using cached opencv-opencv_contrib-4.7.0.tar.gz.
-- Cleaning sources at /home/tdl/Software/vcpkg/buildtrees/opencv4/src/4.7.0-20e285eb9b.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/tdl/Software/vcpkg/downloads/opencv-opencv_contrib-4.7.0.tar.gz
-- Applying patch 0007-fix-hdf5.patch
-- Applying patch 0016-fix-freetype-contrib.patch
-- Applying patch 0018-fix-depend-tesseract.patch
-- Using source at /home/tdl/Software/vcpkg/buildtrees/opencv4/src/4.7.0-20e285eb9b.clean
-- Using cached opencv-cache/wechat_qrcode/238e2b2d6f3c18d6c3a30de0c31e23cf-detect.caffemodel.
-- Using cached opencv-cache/wechat_qrcode/cbfcd60361a73beb8c583eea7e8e6664-sr.caffemodel.
-- Using cached opencv-cache/wechat_qrcode/6fb4976b32695f9f5c6305c19f12537d-detect.prototxt.
-- Using cached opencv-cache/wechat_qrcode/69db99927a70df953b471daaba03fbef-sr.prototxt.
-- Using cached opencv-cache/xfeatures2d/boostdesc/0ea90e7a8f3f7876d450e4149c97c74f-boostdesc_bgm.i.
-- Using cached opencv-cache/xfeatures2d/boostdesc/232c966b13651bd0e46a1497b0852191-boostdesc_bgm_bi.i.
-- Using cached opencv-cache/xfeatures2d/boostdesc/324426a24fa56ad9c5b8e3e0b3e5303e-boostdesc_bgm_hd.i.
-- Using cached opencv-cache/xfeatures2d/boostdesc/202e1b3e9fec871b04da31f7f016679f-boostdesc_binboost_064.i.
-- Using cached opencv-cache/xfeatures2d/boostdesc/98ea99d399965c03d555cef3ea502a0b-boostdesc_binboost_128.i.
-- Using cached opencv-cache/xfeatures2d/boostdesc/e6dcfa9f647779eb1ce446a8d759b6ea-boostdesc_binboost_256.i.
-- Using cached opencv-cache/xfeatures2d/boostdesc/0ae0675534aa318d9668f2a179c2a052-boostdesc_lbgm.i.
-- Using cached opencv-cache/xfeatures2d/vgg/e8d0dcd54d1bcfdc29203d011a797179-vgg_generated_48.i.
-- Using cached opencv-cache/xfeatures2d/vgg/7126a5d9a8884ebca5aea5d63d677225-vgg_generated_64.i.
-- Using cached opencv-cache/xfeatures2d/vgg/7cd47228edec52b6d82f46511af325c5-vgg_generated_80.i.
-- Using cached opencv-cache/xfeatures2d/vgg/151805e03568c9f490a5e3a872777b75-vgg_generated_120.i.
-- Using cached opencv-cache/data/7505c44ca4eb54b4ab1e4777cb96ac05-face_landmark_model.dat.
-- Configuring x64-linux
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: /home/tdl/Software/vcpkg/downloads/tools/cmake-3.25.1-linux/cmake-3.25.1-linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j21
    Working Directory: /home/tdl/Software/vcpkg/buildtrees/opencv4/x64-linux-dbg
    See logs for more information:
      /home/tdl/Software/vcpkg/buildtrees/opencv4/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/opencv4/portfile.cmake:450 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building opencv4:x64-linux failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+opencv4
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[opencv4]+Build+error
Include '[opencv4] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454
    vcpkg-scripts version: 8875aa3cd 2023-03-22 (15 hours ago)

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please provide the error log: **/home/tdl/Software/vcpkg/buildtrees/opencv4/install-x64-linux-dbg-out.log**.
