### ISSUE TITLE
[assimp] Fix UWP support

### ISSUE THREAD

**Issue by ckarrer** [microsoft/vcpkg#30385]
**Host Environment**
OS: Windows
Compiler: MSVC 14.28
vcpkg-tool version: 2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454
vcpkg-scripts version: 8875aa3cd 2023-03-22 (15 hours ago)

**To Reproduce**
`vcpkg install assimp --triplet=arm-uwp`

assimp should be able to build on UWP, according to their documentation (https://github.com/assimp/assimp/blob/master/Build.md) 

But the build through vcpkg leads to the following error:

`
poly2tri is only supported on '!uwp', which does not match arm-uwp. This usually means that there are known build failures, or runtime problems, when building other platforms. To ignore this and attempt to build poly2tri anyway, rerun vcpkg with --allow-unsupported.
`

When forcing the build with --allow-unsupported, both poly2tri and minizip are marked as unsupported on uwp, and minizip leads to a failed build.

[install-arm-uwp-dbg-out.log](https://github.com/microsoft/vcpkg/files/11051978/install-arm-uwp-dbg-out.log)

**Comment by jimwang118** [comment]
Assimp installation depends on the internal poly2tri, but poly2tri does not support uwp, so assimp installation fails. Therefore, assimp does not support uwp in vcpkg.

**Comment by ckarrer** [comment]
Hello,

Thanks for the answer,
My point is that AssImp should be able to build on UWP (https://github.com/assimp/assimp/blob/master/Build.md)

Does vcpkg intend to support it?

**Comment by jimwang118** [comment]
`AssImp `itself compiles to support `uwp`, but `AssImp `build in `vcpkg `depends on `poly2tri` and `poly2tri `in `vcpkg `does not support `uwp`, so currently `asslmp `in `vcpkg `does not support `uwp`. If there are changes later, I will notify you in time.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
