### ISSUE TITLE
[New Port Request] pjsip

### ISSUE THREAD

**Issue by pedoc** [microsoft/vcpkg#30391]
Library name:
pjsip

Library description:
PJSIP is a free and open source multimedia communication library written in C with high level API in C, C++, Java, C#, and Python languages. It implements standard based protocols such as SIP, SDP, RTP, STUN, TURN, and ICE. It combines signaling protocol (SIP) with rich multimedia framework and NAT traversal functionality into high level API that is portable and suitable for almost any type of systems ranging from desktops, embedded systems, to mobile handsets.

Source repository URL:
https://github.com/pjsip/pjproject

Project homepage (if different from the source repository):

There were 2 similar requests before again, but they were closed for unknown reasons

issues:
#8298(included PR https://github.com/microsoft/vcpkg/pull/8697) #12840

Since this library is very common and popular (star 1.4K), I request to add it to vcpkg again.Thanks

**Comment by pedoc** [comment]
ping 😄

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
