### ISSUE TITLE
[New Port Request] yalantinglibs

### ISSUE THREAD

**Issue by gsygsygsyd** [microsoft/vcpkg#30393]
Library name:
yalantinglibs 

Library description:
yaLanTingLibs is a collection of C++20 libraries, now it contains struct_pack, struct_json, struct_pb, coro_rpc, coro_http and [async_simple](https://github.com/alibaba/async_simple), more and more cool libraries will be added into yaLanTingLibs(such as http.) in the future.

The target of yaLanTingLibs: provide very easy and high performance C++20 libraries for C++ developers, it can help to quickly build high performance applications.

Source repository URL:
https://github.com/alibaba/yalantinglibs

**Comment by MonicaLiu0311** [comment]
> i need https://github.com/alibaba/yalantinglibs, how to add?

1. You can create the yalantinglibs folder in `vcpkg/ports/` and add `portfile.cmake` and `vcpkg.json`:
```
vcpkg/ports/yalantinglibs/
    portfile.cmake
    vcpkg.json
```
Then run `./vcpkg install yalantinglibs`, if the installation is successful, it proves that there is no problem with the files you added.

2. Next, run `./vcpkg x-add-verison yalantinglibs`, the `vcpkg/verisons/y-/yalantinglibs.josn` file will be added automatically, and a record will be added in `vcpkg/verisons/baseline.json`.
```
vcpkg/versions/
    y-/
        yalantinglibs.josn (automatically generated)
    baseline.json (automatically add records)
```

The modification needs to meet the requirements: [maintainer-guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)

For more frequently asked questions, see: [faq](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/about/faq.md#how-do-i-get-more-libraries)

You can refer to the library that has been added to vcpkg in the past: [new port request](https://github.com/Microsoft/vcpkg/issues?q=is%3Aissue+label%3Acategory%3Anew-port+is%3Aclosed)

**Comment by poor-circle** [comment]
I will add it later. async_simple is now in vcpkg, we need add iguana & cinatra to vcpkg first, then yalantinglibs.
