### ISSUE TITLE
[opencv4] build failure

### ISSUE THREAD

**Issue by eunsikNota** [microsoft/vcpkg#30399]
**Host Environment**

- OS: Linux
- Compiler:  gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu

**To Reproduce**

`./vcpkg install --allow-unsupported --overlay-ports="hai-vcpkg-registry/ports" --overlay-triplets="hai-vcpkg-registry/triplets" --triplet rpi4-linux  spdlog opencv4[core,jpeg,opengl,gtk] --recurse

**Failure logs**

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/python3 /opt/eunsik/Utility/vcpkg/installed/x64-linux/tools/meson/meson.py -Dselinux=disabled -Dlibmount=disabled -Dgtk_doc=false -Dinstalled_tests=false -Dlibelf=disabled -Dman=false -Dtests=false -Dxattr=false --buildtype plain --backend ninja --wrap-mode nodownload --libdir lib --native /opt/eunsik/Utility/vcpkg/buildtrees/glib/meson-rpi4-linux-dbg.log -Ddebug=true --prefix /opt/eunsik/Utility/vcpkg/packages/glib_rpi4-linux/debug --includedir ../include -Dcmake_prefix_path=['/opt/eunsik/Utility/vcpkg/installed/rpi4-linux/debug','/opt/eunsik/Utility/vcpkg/installed/rpi4-linux'] /opt/eunsik/Utility/vcpkg/buildtrees/glib/src/glib-2-572622187a.clean
    Working Directory: /opt/eunsik/Utility/vcpkg/buildtrees/glib/rpi4-linux-dbg
    Error code: 1
    See logs for more information:
      /opt/eunsik/Utility/vcpkg/buildtrees/glib/config-rpi4-linux-dbg-meson-log.txt.log
      /opt/eunsik/Utility/vcpkg/buildtrees/glib/config-rpi4-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:431 (vcpkg_execute_required_process)
  ports/glib/portfile.cmake:31 (vcpkg_configure_meson)
  scripts/ports.cmake:147 (include)

error: building glib:rpi4-linux failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+glib
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[glib]+Build+error
Include '[glib] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: bc671eb90 2023-03-23 (6 hours ago)

Main binary: /usr/bin/python3
Build Options: -Dselinux=disabled -Dlibmount=disabled -Dgtk_doc=false -Dinstalled_tests=false -Dlibelf=disabled -Dman=false -Dtests=false -Dxattr=false -Ddebug=true '-Dcmake_prefix_path=['"'"'/opt/eunsik/Utility/vcpkg/installed/rpi4-linux/debug'"'"','"'"'/opt/eunsik/Utility/vcpkg/installed/rpi4-linux'"'"']' -Dprefix=/opt/eunsik/Utility/vcpkg/packages/glib_rpi4-linux/debug -Dincludedir=../include -Dlibdir=lib -Dbackend=ninja -Dbuildtype=plain -Dwrap_mode=nodownload '--native-file /opt/eunsik/Utility/vcpkg/buildtrees/glib/meson-rpi4-linux-dbg.log'
Python system: Linux
The Meson build system
Version: 0.62.1
Source dir: /opt/eunsik/Utility/vcpkg/buildtrees/glib/src/glib-2-572622187a.clean
Build dir: /opt/eunsik/Utility/vcpkg/buildtrees/glib/rpi4-linux-dbg
Build type: native build
Project name: glib
Project version: 2.76.0
Sanity testing C compiler: /home/ubuntu/toolchains/gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc
Is cross compiler: False.
Sanity check compiler command line: /home/ubuntu/toolchains/gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc sanitycheckc.c -o sanitycheckc.exe -fPIC -funsafe-math-optimizations -g -I/opt/eunsik/Utility/vcpkg/installed/rpi4-linux/include -D_FILE_OFFSET_BITS=64 -L/opt/eunsik/Utility/vcpkg/installed/rpi4-linux/debug/lib
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /opt/eunsik/Utility/vcpkg/buildtrees/glib/rpi4-linux-dbg/meson-private/sanitycheckc.exe

../src/glib-2-572622187a.clean/meson.build:1:0: ERROR: Could not invoke sanity test executable: [Errno 8] Exec format error: '/opt/eunsik/Utility/vcpkg/buildtrees/glib/rpi4-linux-dbg/meson-private/sanitycheckc.exe'.

**Additional context**

Opencv gtk cross build not working.

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
