### ISSUE TITLE
Flag UWP builds as not supported by default ?

### ISSUE THREAD

**Issue by Tryum** [microsoft/vcpkg#3040]
Some packages will build with a UWP triplet, but are not really UWP compatible as they use forbidden system calls from C files, which are not catched by the compiler. ( `warning C4013: 'getenv' undefined; assuming extern returning int` ...)

What about setting UWP builds as not supported by default so that the maintainer has to flag the package as supported for UWP platform once it has been tested ?

**Comment by JackBoosY** [comment]
In fact, the supported triplets are set under vcpkg/triplets/, you can even add custom settings, so disabling uwp by default is not a good idea.
For the above problem, we recommend declaring unsupported triplets when creating a new port, and when we find that a port does not support some triplets, we will modify its portfile.cmake to add warnings.
