### ISSUE TITLE
Failing to `include` packages when starting a project with the CUDA Toolkit project template

### ISSUE THREAD

**Issue by ElemarJR** [microsoft/vcpkg#3041]
I am using Windows 10 and VS2017 (version 15.6.0). Also, I installed CUDA toolkit (9.1).

I started a new project using the `CUDA 9.1` template (from CUDA Toolkit). Then, I installed freeglut. 

**The integration with VS2017 is working when using VC++ templates**. But it is not working with CUDA 9.1 template. When I try to include `GL/freeglut.h`, it is not available.

I know it is problem something basic. But, I have no ideia how to get it working.

**Comment by JackBoosY** [comment]
Hi @ElemarJR, here is [documentation](https://vcpkg.readthedocs.io/en/latest/users/integration/).
And if you want to use static library, this [documentation](https://devblogs.microsoft.com/cppblog/vcpkg-updates-static-linking-is-now-available/) will answer your question.

Thanks.
