### ISSUE TITLE
[opencv] build failure

### ISSUE THREAD

**Issue by Bzz2745** [microsoft/vcpkg#30437]
**Host Environment**

- OS: Windows 11
- Compiler: MSVC vc143,CUDA 12.1

**To Reproduce**

` ./vcpkg install opencv4[ade,contrib,cuda,cudnn,default-features,dnn,dnn-cuda,eigen,ffmpeg,freetype,gdcm,gstreamer,ipp,jasper,jpeg,nonfree,openexr,opengl,ovis,png,qt,quirc,tbb,tiff,vtk,webp,world]:x64-windows --clean-after-build`

**Failure logs**

-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe -v
    Working Directory: C:/vcpkg/buildtrees/opencv4/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\opencv4\config-x64-windows-dbg-CMakeCache.txt.log
      C:\vcpkg\buildtrees\opencv4\config-x64-windows-rel-CMakeCache.txt.log
      C:\vcpkg\buildtrees\opencv4\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:248 (vcpkg_execute_required_process)
  ports/opencv4/portfile.cmake:354 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)

**Additional context**

[config-x64-windows-dbg-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/11070699/config-x64-windows-dbg-CMakeCache.txt.log)

[config-x64-windows-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/11070700/config-x64-windows-rel-CMakeCache.txt.log)

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/11070702/config-x64-windows-out.log)

**Comment by autoantwort** [comment]
Maybe try to run `install` with `--x-abi-tools-use-exact-versions`

**Comment by Bzz2745** [comment]
> Maybe try to run `install` with `--x-abi-tools-use-exact-versions`

I have try it just now, but it still didn't work.

**Comment by MonicaLiu0311** [comment]
Blocked by other dependencies during reproduction, further confirmation will follow.
```
PS E:\vcpkg02>  ./vcpkg install opencv4[ade,contrib,cuda,cudnn,default-features,dnn,dnn-cuda,eigen,ffmpeg,freetype,gdcm,gstreamer,ipp,jasper,jpeg,nonfree,openexr,opengl,ovis,png,qt,quirc,tbb,tiff,vtk,webp,world]:x64-windows --clean-after-build
Computing installation plan...
The following packages will be built and installed:
  * cudnn[core]:x64-windows -> 7.6.5#9
  * gdcm[core]:x64-windows -> 3.0.12#1
  * gstreamer[core,plugins-base]:x64-windows -> 1.20.5#6
    opencv4[ade,contrib,core,cuda,cudnn,default-features,dnn,dnn-cuda,eigen,ffmpeg,freetype,gdcm,gstreamer,ipp,jasper,jpeg,nonfree,openexr,opengl,ovis,png,qt,quirc,tbb,tiff,vtk,webp,world]:x64-windows -> 4.7.0#6
  * pegtl[core]:x64-windows -> 3.2.7
  * qt5compat[big-codecs,codecs,core,default-features,qml,textcodec]:x64-windows -> 6.5.0
  * qtbase[brotli,concurrent,core,dbus,default-features,doubleconversion,freetype,gui,harfbuzz,icu,jpeg,network,opengl,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,thread,widgets,zstd]:x64-windows -> 6.5.0#1
  * qtdeclarative[core]:x64-windows -> 6.5.0
  * qtshadertools[core]:x64-windows -> 6.5.0
  * seacas[core]:x64-windows -> 2022-11-22#3
  * vtk[core]:x64-windows -> 9.2.0-pv5.11.0#6
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\v-liumonica\AppData\Local\vcpkg\archives in 24.4 ms. Use --debug to see more details.
Installing 1/11 cudnn:x64-windows...
Building cudnn[core]:x64-windows...
-- Found CUDA V12.0.140
-- CUDNN_INCLUDE_DIR: CUDNN_INCLUDE_DIR-NOTFOUND
-- CUDNN_LIBRARY: CUDNN_LIBRARY-NOTFOUND
CMake Error at ports/cudnn/portfile.cmake:58 (message):
  Please download CUDNN from official sources (such as
  https://developer.nvidia.com/rdp/cudnn-download ) and extract the zip into
  your CUDA_TOOLKIT_ROOT (C:/Program Files/NVIDIA GPU Computing
  Toolkit/CUDA/v12.0).  (For example: tar.exe -xvf
  cudnn-11.2-windows-x64-v8.1.1.33.zip --strip 1 --directory "C:/Program
  Files/NVIDIA GPU Computing Toolkit/CUDA/v12.0"
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)
```

**Comment by MonicaLiu0311** [comment]
Sorry I'm late, blocked by other dependencies.


* Win 11
* VS 2022
Vcpkg version: 
```
PS F:\Monica\vcpkg> ./vcpkg version
vcpkg package management program version 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895

See LICENSE.txt for license information.
```

Confirm, reproduce locally.
