### ISSUE TITLE
Error: Building package giflib:x64-uwp failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by kasperbalink** [Microsoft/vcpkg#3043]
Error: Building package giflib:x64-uwp failed with: BUILD_FAILED
  Package: giflib:x64-uwp
  Vcpkg version: 0.0.105-2018-03-14-3a056235b85f34573903a7dc325d45e66549b6ff

Same issue for `giflib:arm-uwp` and `giflib:x86-uwp`.
This error occured while installing `tesseract:x64-uwp`

patch-x64-uwp-0-err.log:

> Checking patch lib/dgif_lib.c...
error: while searching for:
#include <limits.h>
#include <stdint.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdio.h>
#include <string.h>
>
> error: patch failed: lib/dgif_lib.c:12
error: lib/dgif_lib.c: patch does not apply
Checking patch lib/egif_lib.c...
error: while searching for:
>
> *****************************************************************************/
>
> #include <unistd.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
>
> error: patch failed: lib/egif_lib.c:8
error: lib/egif_lib.c: patch does not apply
Checking patch lib/gif_hash.c...
error: while searching for:
>
> *****************************************************************************/
>
> #include <unistd.h>
#include <stdint.h>
#include <stdlib.h>
#include <fcntl.h>
>
> error: patch failed: lib/gif_hash.c:11
error: lib/gif_hash.c: patch does not apply
Checking patch lib/gif_hash.h...
error: while searching for:
#ifndef _GIF_HASH_H_
#define _GIF_HASH_H_
>
> #include <unistd.h>
#include <stdint.h>
>
> #define HT_SIZE			8192	   /* 12bits = 4096 or twice as big! */
>
> error: patch failed: lib/gif_hash.h:7
error: lib/gif_hash.h: patch does not apply

**Comment by JackBoosY** [comment]
Hi @kasperbalink , thanks for reporting this issue!
I've fixed this issue just now. Please update and rebuild giflib.
Thanks.

**Comment by gerwalk** [comment]
Looks like the commit that resolved this bug has been reverted. I'm getting this same build failure (caused by "unsafe" warnings in x86-uwp (I am also trying to install tesseract). If I try x64 instead the build errors are ADDITIONAL errors: 
>giflib\src\giflib-5.1.4\lib\egif_lib.c(63): error C4996: 'open': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _open.
