### ISSUE TITLE
How do I download bit/stdc++.h?

### ISSUE THREAD

**Issue by lichenyichay** [microsoft/vcpkg#30441]
bit/stdc++.h is not in the vcpkg. But I use the Dev-C++,it have this library。

**Comment by autoantwort** [comment]
Is this a request for a new library?

**Comment by PhoebeHui** [comment]
@lichenyichay, if this is a new library request, please 'Request a new port' issue instead and providing the information mentioned in autogenerated issue body.

![image](https://user-images.githubusercontent.com/20694052/228491080-310dce7b-560e-4b90-b5ac-f62188eabaa4.png)
