### ISSUE TITLE
ffmpeg[all] need fix

### ISSUE THREAD

**Issue by WangHHY19931001** [microsoft/vcpkg#30451]
ffmpeg[all] for any arm plantform not need amd-amf

amd-amf only used by amd plantform, and amd not have arm device

**Comment by FrankXie05** [comment]
@WangHHY19931001 Do you mean that only `ffmpeg[amd-amf]` only supports `amd`? Or does it mean that this port `amd-amf` supports `amd`?

**Comment by WangHHY19931001** [comment]
just arm not need it
