### ISSUE TITLE
vcpkg error: Failed to provision vcpkg-artifacts

### ISSUE THREAD

**Issue by anderwm** [microsoft/vcpkg#30474]
Type: Bug Report

**Describe the bug**
- OS and Version: Ubuntu 20.04
- VS Code Version: 1.76.2
- Embedded Tools Extension Version: 1.0.0
- Target embedded device: N/A

**To Reproduce**
1. Attempt to load any workspace with the STM32 VS Code Extension
2. Note that vcpkg has failed with output:
```
> Using vcpkg executable at "/home/redact/.vscode/extensions/ms-vscode.vscode-embedded-tools-0.7.230323001-linux-x64/assets/platform/linux-x64/vcpkg-glibc.app".
> Using VCPKG_ROOT at "/home/redact/.config/Code/User/globalStorage/ms-vscode.vscode-embedded-tools/vcpkg/root".
> Activating environment at "/home/redact/STM32CubeIDE/workspace_1.8.0/redactredact/vcpkg-configuration.json".
> Version of vcpkg used to create VCPKG_ROOT: "2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454".
> Running vcpkg with arguments ["version"].
vcpkg package management program version 2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454

See LICENSE.txt for license information.
> Bundled version of vcpkg: "2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454".
> Running vcpkg with arguments ["activate","--project","/home/redact/STM32CubeIDE/workspace_1.8.0/redactredact","--json","/tmp/0cbf6b4eb2531ea7c4a1e4a69595a744"].
warning: vcpkg-artifacts is experimental and may change at any time.
Downloading vcpkg-artifacts bundle 2023-03-14...
error: Failed to provision vcpkg-artifacts.
> Failed with exit code "1".
```

**Expected behavior**
I believe it is trying to find an artifacts bundle in ~/.cache/vcpkg but in fact that directory is empty. I'm not sure why it doesn't try to download and extract the bundle.

I have tried the same thing on an Ubuntu 22.04 machine and it works as expected without this error

**Comment by FrankXie05** [comment]
@anderwm Thanks for posting this issue. Could you please provide the file `vcpkg-bundle.json`? 
```
[DEBUG] Trying to load bundleconfig from /home/user_a/.vscode/extensions/ms-vscode.vscode-embedded-tools-0.7.0-linux-x64/assets/platform/linux-x64/vcpkg-bundle.json
[DEBUG] Failed to open: /home/user_a/.vscode/extensions/ms-vscode.vscode-embedded-tools-0.7.0-linux-x64/assets/platform/linux-x64/vcpkg-bundle.json
```

**Comment by anderwm** [comment]
It isn't there...The only things in that directory are placeholder.txt and vcpkg-glibc.app

There is a vcpkg-bundle.json in /home/user_a/.config/Code/User/globalStorage/ms-vscode.vscode-embedded-tools/vcpkg/root/vcpkg-bundle.json

**Comment by ecneb85** [comment]
I have the same Issue:
> Using vcpkg executable at "c:\Portable\VSCode-win32-x64-1.76.2\data\extensions\ms-vscode.vscode-embedded-tools-0.7.0-win32-x64\assets\platform\win32-x64\vcpkg.exe".
> Using VCPKG_ROOT at "c:\Portable\VSCode-win32-x64-1.76.2\data\user-data\User\globalStorage\ms-vscode.vscode-embedded-tools\vcpkg\root".
> Activating environment at "c:\UserData\firmware\bms\vcpkg-configuration.json".
> Version of vcpkg used to create VCPKG_ROOT: "2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454".
> Running vcpkg with arguments ["version","--debug"].
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from c:\Portable\VSCode-win32-x64-1.76.2\data\extensions\ms-vscode.vscode-embedded-tools-0.7.0-win32-x64\assets\platform\win32-x64\vcpkg-bundle.json
[DEBUG] Failed to open: c:\Portable\VSCode-win32-x64-1.76.2\data\extensions\ms-vscode.vscode-embedded-tools-0.7.0-win32-x64\assets\platform\win32-x64\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
vcpkg package management program version 2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454

**Comment by Cheney-W** [comment]
@anderwm What's the content of `/home/redact/STM32CubeIDE/workspace_1.8.0/redactredact/vcpkg-configuration.json`?

**Comment by anderwm** [comment]
```
