### ISSUE TITLE
[opencascade] usage requires include(CMakeFindDependencyMacro)

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#30476]
OpenCascade uses find_dependency in its config file but is missing the "required" `include(CMakeFindDependencyMacro)`

(Maybe `vcpkg.cmake` should just include that file no matter what since everybody uses it.)

**Comment by jimwang118** [comment]
After I installed `opencascade`, I searched for `find_dependency `globally in its config file, but found no place to use it. Can you tell what it is used in that file?

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
