### ISSUE TITLE
error regex in scripts/cmake/vcpkg_configure_make.cmake

### ISSUE THREAD

**Issue by Joker2387089590** [microsoft/vcpkg#30479]
https://github.com/microsoft/vcpkg/blob/d1e2ff0c340f89cc14ca67883dd069c6ada93582/scripts/cmake/vcpkg_configure_make.cmake#L65
Before this line, CXXFLAG is matched by regex to split flags, then the flags is used for next regex, but when I added my include paths in toolchain files such as `-isystem/usr/include/c++/v1`, which including symbol `+`, it made an illegal regex.
So, it is necessary to escape the regex before 
https://github.com/microsoft/vcpkg/blob/d1e2ff0c340f89cc14ca67883dd069c6ada93582/scripts/cmake/vcpkg_configure_make.cmake#L63
I haven't found a function that escape strings for regex in CMake, so just submit this issue. By the way my solution is creating a symbol link to rename my flags, obviously it is just a workground...

**Comment by huffman** [comment]
I've also run into this issue. We have a fork with a change to escape the `+` characters. This isn't a complete solution (I also didn't find a build-in way to escape strings for regex), but it's sufficient for our use-case. It would be great to see a general fix for this.

https://github.com/saleae/vcpkg/commit/14e8fbc5d18b4d4b5cae20a8a4982fd0cd6648ab
