### ISSUE TITLE
Error: building python3 on rs4 sdk fails in winnt.h: No target architecture

### ISSUE THREAD

**Issue by nerdile** [Microsoft/vcpkg#3047]
Repro steps:
* VS 2017 15.6 latest stable public release
* Windows Insider SDK 17115 (latest Insider preview release)
vcpkg install python3

The usual cause of this failure is failing to include Windows.h before other Windows platform SDK headers, I’m trying to see if I can find the specific compilation unit that’s failing.

**Comment by nerdile** [comment]
Note: including file: d:\src\vcpkg\buildtrees\python3\src-x86-windows\cpython-3.6.4\modules\_io\_iomodule.h
Note: including file: D:\ProgramFiles\WindowsKits\10\include\10.0.17115.0\um\consoleapi.h
Note: including file:  D:\ProgramFiles\WindowsKits\10\include\10.0.17115.0\shared\apiset.h
Note: including file:  D:\ProgramFiles\WindowsKits\10\include\10.0.17115.0\shared\apisetcconv.h
Note: including file:  D:\ProgramFiles\WindowsKits\10\include\10.0.17115.0\shared\minwindef.h
Note: including file:   D:\ProgramFiles\WindowsKits\10\include\10.0.17115.0\shared\specstrings.h
Note: including file:    D:\ProgramFiles\WindowsKits\10\include\10.0.17115.0\shared\specstrings_strict.h
Note: including file:     D:\ProgramFiles\WindowsKits\10\include\10.0.17115.0\shared\specstrings_undef.h
Note: including file:    D:\ProgramFiles\WindowsKits\10\include\10.0.17115.0\shared\driverspecs.h
Note: including file:     d:\programfiles\windowskits\10\include\10.0.17115.0\shared\sdv_driverspecs.h
Note: including file:   D:\ProgramFiles\WindowsKits\10\include\10.0.17115.0\shared\winapifamily.h
Note: including file:    D:\ProgramFiles\WindowsKits\10\include\10.0.17115.0\shared\winpackagefamily.h
Note: including file:   D:\ProgramFiles\WindowsKits\10\include\10.0.17115.0\um\winnt.h
Note: including file:    D:\ProgramFiles\WindowsKits\10\include\10.0.17115.0\shared\kernelspecs.h
d:\programfiles\windowskits\10\include\10.0.17115.0\um\winnt.h(154): fatal error C1189: #error:  "No Target Architecture"

**Comment by nerdile** [comment]
modules/_io/_iomodule.c just needs one tweak:

#ifdef MS_WINDOWS
**#include <windows.h>**
#include <consoleapi.h>
#endif

What is the best way to go about this - start with a patch for vcpkg and then try to request the change upstream?

**Comment by nerdile** [comment]
Ok, I have a patch for the python3 port in vcpkg; this is my first time updating a portfile with a patch like this, so please let me know if I did this correctly.

**Comment by illera88** [comment]
That is a problem with python itself right?
Did you make a PR to fix it in Python? 

Thanks!

**Comment by LarryIII** [comment]
PR merged, so closed this issue.
