### ISSUE TITLE
OpenSSL build failure

### ISSUE THREAD

**Issue by AFOEK** [microsoft/vcpkg#30484]
**Host Environment**

- OS: FreeBSD x64 (Run on VirtualBox)
- Compiler: CC / Clang 13.0.0

**To Reproduce**

./vcpkg install openssl

**Failure logs**

CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:617 (message):
  Could not find pkg-config.  Please install it via your package manager.
Call Stack (most recent call first):
  scripts/cmake/z_vcpkg_setup_pkgconfig_path.cmake:19 (vcpkg_find_acquire_program)
  scripts/cmake/vcpkg_configure_make.cmake:769 (z_vcpkg_setup_pkgconfig_path)
  ports/openssl/unix/portfile.cmake:111 (vcpkg_configure_make)
  ports/openssl/portfile.cmake:65 (include)
  scripts/ports.cmake:147 (include)

error: building openssl:x64-freebsd failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openssl]+Build+error
Include '[openssl] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2999-12-31-unknownhash
    vcpkg-scripts version: bc671eb90 2023-03-23 (4 days ago)

**Additional context**

I trying to install some packages, which some of them requiring openssl to work. Since openssl require `pkg-config` it always failed because FreeBSD already changed tools name to `pkgconf`, but I try invoke `pkgconf` or `pkg-config` from command line it's call same tools.

**Comment by dg0yt** [comment]
It is not related to openssl, but a general vcpkg script.
Try setting environment variable `PKG_CONFIG` to pkgconf (or to its full filepath).

https://github.com/microsoft/vcpkg/blob/d1e2ff0c340f89cc14ca67883dd069c6ada93582/scripts/cmake/vcpkg_find_acquire_program.cmake#L511-L528

**Comment by AFOEK** [comment]
Just export the variable ? I will try it

**Comment by AFOEK** [comment]
I have declared the environment variable, it's work... But it's gave me new error:
```
-- Configuring x64-freebsd-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/local/bin/bash -c "V=1 ./../src/nssl-3.1.0-1ebd9e680e.clean/vcpkg/configure  \"/usr/local/bin/perl\" \"/usr/home/Afoek/vcpkg/buildtrees/openssl/src/nssl-3.1.0-1ebd9e680e.clean/Configure\" \"BSD-generic64\" \"enable-static-engine\" \"enable-capieng\" \"no-ssl3\" \"no-weak-ssl-ciphers\" \"no-tests\" \"no-shared\" \"no-module\" \"no-apps\" \"--openssldir=/etc/ssl\" \"--libdir=lib\" \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"--debug\" \"--prefix=/usr/home/Afoek/vcpkg/installed/x64-freebsd/debug\""
    Working Directory: /usr/home/Afoek/vcpkg/buildtrees/openssl/x64-freebsd-dbg
    Error code: 127
    See logs for more information:
      /usr/home/Afoek/vcpkg/buildtrees/openssl/config-x64-freebsd-dbg-err.log
```

For the log file:
```
/usr/local/bin/bash: line 1: ./../src/nssl-3.1.0-1ebd9e680e.clean/vcpkg/configure: cannot execute: required file not found
```

**Comment by dg0yt** [comment]
`./../src/nssl-3.1.0-1ebd9e680e.clean/vcpkg/configure` (i.e.  `/usr/home/Afoek/vcpkg/buildtrees/openssl/src/nssl-3.1.0-1ebd9e680e.clean/vcpkg/configure`) should really exist at this point. It is copied from the port dir:
https://github.com/microsoft/vcpkg/blob/c9f906558f9bb12ee9811d6edc98ec9255c6cda5/ports/openssl/unix/portfile.cmake#L102-L104

Can you please check if the exectable bit is set on that script (in `ports/openssl/unix` and in the `buildtrees` path)?

**Comment by AFOEK** [comment]
> `./../src/nssl-3.1.0-1ebd9e680e.clean/vcpkg/configure` (i.e. `/usr/home/Afoek/vcpkg/buildtrees/openssl/src/nssl-3.1.0-1ebd9e680e.clean/vcpkg/configure`) should really exist at this point. It is copied from the port dir:
> 
> https://github.com/microsoft/vcpkg/blob/c9f906558f9bb12ee9811d6edc98ec9255c6cda5/ports/openssl/unix/portfile.cmake#L102-L104
> 
> Can you please check if the exectable bit is set on that script (in `ports/openssl/unix` and in the `buildtrees` path)?

From I check on `ports/openssl/unix` it's exist and `/usr/home/Afoek/vcpkg/buildtrees/openssl/src/nssl-3.1.0-1ebd9e680e.clean/vcpkg/configure` exist too

**Comment by dg0yt** [comment]
The question was if the executable bit is set on the existing files, i.e.
~~~
ls -l ports/openssl/unix
ls -l /usr/home/Afoek/vcpkg/buildtrees/openssl/src/nssl-3.1.0-1ebd9e680e.clean/vcpkg/configure
~~~

**Comment by AFOEK** [comment]
> The question was if the executable bit is set on the existing files, i.e. check the output of
> ~~~
> ls -l ports/openssl/unix
> ls -l /usr/home/Afoek/vcpkg/buildtrees/openssl/src/nssl-3.1.0-1ebd9e680e.clean/vcpkg/configure
> ~~~

It's work as charm, thanks
