### ISSUE TITLE
[boost-exception] Build error

### ISSUE THREAD

**Issue by RainbowTaro2022** [microsoft/vcpkg#30486]
G:\Cone\vcpkg>vcpkg install libdeflate libodb-pgsql libodb-sqlite libodb-mysql libsoundio mapbox-wagyu mapbox-geojson-vt-cpp mapbox-geojson-cpp magnum-extras magnum-integration mesa --allow-unsupported
warning: Starting with the September 2023 release, the default triplet for vcpkg libraries will change from x86-windows to the detected host triplet (x64-windows). To resolve this message, add --triplet x86-windows to keep the same behavior.
Computing installation plan...
warning: libmysql is only supported on '!(windows & x86) & !uwp', which does not match x86-windows. This usually means that there are known build failures, or runtime problems, when building other platforms. Proceeding anyway due to `--allow-unsupported`.
The following packages will be built and installed:
  * boost-algorithm[core]:x86-windows -> 1.81.0#2
  * boost-align[core]:x86-windows -> 1.81.0#2
  * boost-any[core]:x86-windows -> 1.81.0#2
  * boost-atomic[core]:x86-windows -> 1.81.0#2
  * boost-bimap[core]:x86-windows -> 1.81.0#2
  * boost-chrono[core]:x86-windows -> 1.81.0#2
  * boost-container[core]:x86-windows -> 1.81.0#2
  * boost-container-hash[core]:x86-windows -> 1.81.0#2
  * boost-conversion[core]:x86-windows -> 1.81.0#2
  * boost-date-time[core]:x86-windows -> 1.81.0#2
  * boost-describe[core]:x86-windows -> 1.81.0#2
  * boost-detail[core]:x86-windows -> 1.81.0#2
  * boost-dynamic-bitset[core]:x86-windows -> 1.81.0#2
  * boost-endian[core]:x86-windows -> 1.81.0#2
  * boost-exception[core]:x86-windows -> 1.81.0#2
  * boost-foreach[core]:x86-windows -> 1.81.0#2
  * boost-format[core]:x86-windows -> 1.81.0#2
  * boost-function[core]:x86-windows -> 1.81.0#2
  * boost-function-types[core]:x86-windows -> 1.81.0#2
  * boost-functional[core]:x86-windows -> 1.81.0#2
  * boost-fusion[core]:x86-windows -> 1.81.0#2
  * boost-geometry[core]:x86-windows -> 1.81.0#2
  * boost-graph[core]:x86-windows -> 1.81.0#2
  * boost-integer[core]:x86-windows -> 1.81.0#2
  * boost-intrusive[core]:x86-windows -> 1.81.0#2
  * boost-io[core]:x86-windows -> 1.81.0#2
  * boost-iterator[core]:x86-windows -> 1.81.0#2
  * boost-lambda[core]:x86-windows -> 1.81.0#2
  * boost-lexical-cast[core]:x86-windows -> 1.81.0#2
  * boost-math[core]:x86-windows -> 1.81.0#2
  * boost-mp11[core]:x86-windows -> 1.81.0#2
  * boost-mpl[core]:x86-windows -> 1.81.0#2
  * boost-multi-index[core]:x86-windows -> 1.81.0#2
  * boost-multiprecision[core]:x86-windows -> 1.81.0#2
  * boost-numeric-conversion[core]:x86-windows -> 1.81.0#2
  * boost-optional[core]:x86-windows -> 1.81.0#2
  * boost-parameter[core]:x86-windows -> 1.81.0#2
  * boost-phoenix[core]:x86-windows -> 1.81.0#2
  * boost-polygon[core]:x86-windows -> 1.81.0#2
  * boost-pool[core]:x86-windows -> 1.81.0#2
  * boost-property-map[core]:x86-windows -> 1.81.0#2
  * boost-property-tree[core]:x86-windows -> 1.81.0#2
  * boost-proto[core]:x86-windows -> 1.81.0#2
  * boost-qvm[core]:x86-windows -> 1.81.0#2
  * boost-random[core]:x86-windows -> 1.81.0#2
  * boost-range[core]:x86-windows -> 1.81.0#2
  * boost-ratio[core]:x86-windows -> 1.81.0#2
  * boost-rational[core]:x86-windows -> 1.81.0#2
  * boost-regex[core]:x86-windows -> 1.81.0#2
  * boost-serialization[core]:x86-windows -> 1.81.0#2
  * boost-spirit[core]:x86-windows -> 1.81.0#2
  * boost-system[core]:x86-windows -> 1.81.0#2
  * boost-thread[core]:x86-windows -> 1.81.0#2
  * boost-tokenizer[core]:x86-windows -> 1.81.0#2
  * boost-tti[core]:x86-windows -> 1.81.0#2
  * boost-type-index[core]:x86-windows -> 1.81.0#2
  * boost-typeof[core]:x86-windows -> 1.81.0#2
  * boost-unordered[core]:x86-windows -> 1.81.0#2
  * boost-utility[core]:x86-windows -> 1.81.0#2
  * boost-variant[core]:x86-windows -> 1.81.0#2
  * boost-variant2[core]:x86-windows -> 1.81.0#2
  * boost-xpressive[core]:x86-windows -> 1.81.0#2
  * corrade[core,interconnect,pluginmanager,testsuite,utility]:x64-windows -> 2020.06#5
  * corrade[core,interconnect,pluginmanager,testsuite,utility]:x86-windows -> 2020.06#5
    libdeflate[compression,core,decompression,gzip,zlib]:x86-windows -> 1.17
  * libevent[core,thread]:x86-windows -> 2.1.12+20230128
  * libmysql[core]:x86-windows -> 8.0.20#10
  * libodb[core]:x86-windows -> 2.4.0#10
    libodb-mysql[core]:x86-windows -> 2.4.0#11
    libodb-pgsql[core]:x86-windows -> 2.4.0#6
    libodb-sqlite[core]:x86-windows -> 2.4.0#11
    libsoundio[core]:x86-windows -> 2.0.0#7
  * magnum[anyaudioimporter,anyimageconverter,anyimageimporter,anysceneconverter,anysceneimporter,anyshaderconverter,audio,core,debugtools,gl,meshtools,primitives,scenegraph,sdl2application,shaders,shadertools,text,texturetools,trade]:x86-windows -> 2020.06#12
    magnum-extras[core]:x86-windows -> 2020.06#2
    magnum-integration[core]:x86-windows -> 2020.06#2
    mapbox-geojson-cpp[core]:x86-windows -> 0.5.1#1
    mapbox-geojson-vt-cpp[core]:x86-windows -> 6.6.5
    mapbox-wagyu[core]:x86-windows -> 0.5.0
    mesa[core,default-features,gles1,gles2,opengl]:x86-windows -> 22.1.7#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Detecting compiler hash for triplet x64-windows...
Restored 25 package(s) from C:\Users\小玉\AppData\Local\vcpkg\archives in 11.7399025 s. Use --debug to see more details.
Installing 1/79 boost-exception:x86-windows...
Building boost-exception[core]:x86-windows...
-- Using cached boostorg-exception-boost-1.81.0.tar.gz.
-- Cleaning sources at G:/Cone/vcpkg/buildtrees/boost-exception/src/ost-1.81.0-55a9487305.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source G:/Cone/vcpkg/downloads/boostorg-exception-boost-1.81.0.tar.gz
-- Using source at G:/Cone/vcpkg/buildtrees/boost-exception/src/ost-1.81.0-55a9487305.clean
-- Getting CMake variables for x86-windows
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: G:/python310/Lib/site-packages/cmake/data/bin/cmake.exe --build . --config Debug --target install -- -v -j7
    Working Directory: G:/Cone/vcpkg/buildtrees/boost-exception/x86-windows-dbg
    See logs for more information:
      G:\Cone\vcpkg\buildtrees\boost-exception\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:140 (vcpkg_cmake_install)
  ports/boost-exception/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:147 (include)

**Comment by RainbowTaro2022** [comment]
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/11088501/install-x86-windows-dbg-out.log)

**Comment by jimwang118** [comment]
```
The system cannot find the path specified.
...removing G:\Cone\vcpkg\buildtrees\boost-exception\x86-windows-dbg\boost\standalone\msvc\fabbfd46c2a4e30dd1594f96c4cd44b2\msvc-setup.bat
...skipped <pG:\Cone\vcpkg\buildtrees\boost-exception\x86-windows-dbg\boost\build\db5497286695e61e9683f2d8d953854d>clone_current_exception_non_intrusive.obj for lack of <pG:\Cone\vcpkg\buildtrees\boost-exception\x86-windows-dbg\boost\standalone\msvc\fabbfd46c2a4e30dd1594f96c4cd44b2>msvc-setup.nup...
...failed updating 1 target...
ninja: build stopped: subcommand failed.
```
The error prompts that the system path cannot be found, can you check whether the system path exists? `G:\Cone\vcpkg\buildtrees\boost-exception\x86-windows-dbg\boost\standalone\msvc\fabbfd46c2a4e30dd1594f96c4cd44b2\msvc-setup.bat`

**Comment by PhoebeHui** [comment]
@RainbowTaro2022, the Chinese characters cause this issue, See https://github.com/microsoft/vcpkg/issues/15201#issuecomment-750804866.

**Comment by jimwang118** [comment]
@the Chinese characters cause this issue, See #15201 (comment). You should create a file path without Chinese characters to solve this problem.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
