### ISSUE TITLE
[boost-vcpkg-helpers] Build error

### ISSUE THREAD

**Issue by 732175344** [microsoft/vcpkg#30480]
**Host Environment**

- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**

`./vcpkg install xxxx`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JonLiu1993** [comment]
@732175344, thanks for posting this question, can you provide your error log and steps to reproduce?

**Comment by 732175344** [comment]
Thank you very much for your reply, I followed the steps in the official documentation, and after installing OpenCV, Ceres, SuiteSparse and LAPACK (vcpkg install opencv4 ceres ceres[suitesparse] lapack suitesparse --triplet x64-windows) I got an error in the picture



&nbsp;


以喋以喋以喋喋
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月28日(星期二) 下午2:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [microsoft/vcpkg] [boost-vcpkg-helpers] Build error (Issue #30480)





 
@732175344, thanks for posting this question, can you provide your error log and steps to reproduce?

**Comment by JonLiu1993** [comment]
@732175344, I can't see your error log picture.

**Comment by 732175344** [comment]
This is the code that reported the error, and I put the screenshot in the attachment：


CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):


&nbsp; &nbsp; &nbsp; Failed to download file with error: 1
&nbsp; &nbsp; &nbsp; If you are using a proxy, please check your proxy setting. Possible causes are:


&nbsp; &nbsp; &nbsp; 1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;to `https://address:port`. This is not correct, because `https://` prefix
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;, etc..) is an HTTP proxy. Try setting `http://address:port` to both
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;HTTP_PROXY and HTTPS_PROXY instead.


&nbsp; &nbsp; &nbsp; 2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;The value set by your proxy might be wrong, or have same `https://` prefix issue.


&nbsp; &nbsp; &nbsp; 3. Your proxy's remote server is out of service.


&nbsp; &nbsp; &nbsp; If you've tried directly download the link, and believe this is not a temporary
&nbsp; &nbsp; &nbsp; download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
&nbsp; &nbsp; &nbsp; to report this upstream download server failure.




Call Stack (most recent call first):
&nbsp; scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
&nbsp; scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
&nbsp; ports/gklib/portfile.cmake:2 (vcpkg_from_github)
&nbsp; scripts/ports.cmake:147 (include)




error: building gklib:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
&nbsp; &nbsp; https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+gklib
You can submit a new issue at:
&nbsp; &nbsp; https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&amp;title=[gklib]+Build+error
Include '[gklib] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
&nbsp; &nbsp; vcpkg-tool version: 2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454
&nbsp; &nbsp; vcpkg-scripts version: unknown



以喋以喋以喋喋
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vcpkg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 下午4:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/vcpkg] [boost-vcpkg-helpers] Build error (Issue #30480)





 
@732175344, I can't see your error log picture.

**Comment by JonLiu1993** [comment]
@732175344, I can't reproduce this issue in my side. Could you provide me which package you failed to download?

**Comment by 732175344** [comment]
I tried to reinstall again, this time there seems to be no error, but I did not respond when executing the next code "python3 setup.py build", so I changed it to "python setup.py build", it reports the same error as directly executing the setup.py program in pycharm as shown in the attachment, have you seen this error




以喋以喋以喋喋
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vcpkg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 下午5:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/vcpkg] [boost-vcpkg-helpers] Build error (Issue #30480)





 
@732175344, I can't reproduce this issue in my side. Could you provide me which package you failed to download?

**Comment by JonLiu1993** [comment]
@732175344, sorry, I can't see your mistake in your reply.

**Comment by 732175344** [comment]
G:\anaconda3\envs\openmgv1\python.exe G:/Code/OpenSfM/setup.py
Configuring for python 3.8...
['cmake', '../opensfm/src', '-DPYTHON_EXECUTABLE=G:\\anaconda3\\envs\\openmgv1\\python.exe', '-DVCPKG_TARGET_TRIPLET=x64-windows', '-DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake']
Traceback (most recent call last):
&nbsp; File "G:/Code/OpenSfM/setup.py", line 60, in <module&gt;
&nbsp; &nbsp; configure_c_extension()
&nbsp; File "G:/Code/OpenSfM/setup.py", line 44, in configure_c_extension
&nbsp; &nbsp; subprocess.check_call(cmake_command, cwd="cmake_build")
&nbsp; File "G:\anaconda3\envs\openmgv1\lib\subprocess.py", line 359, in check_call
&nbsp; &nbsp; retcode = call(*popenargs, **kwargs)
&nbsp; File "G:\anaconda3\envs\openmgv1\lib\subprocess.py", line 340, in call
&nbsp; &nbsp; with Popen(*popenargs, **kwargs) as p:
&nbsp; File "G:\anaconda3\envs\openmgv1\lib\subprocess.py", line 858, in __init__
&nbsp; &nbsp; self._execute_child(args, executable, preexec_fn, close_fds,
&nbsp; File "G:\anaconda3\envs\openmgv1\lib\subprocess.py", line 1311, in _execute_child
&nbsp; &nbsp; hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。


Process finished with exit code 1





以喋以喋以喋喋
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vcpkg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月29日(星期三) 上午9:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/vcpkg] [boost-vcpkg-helpers] Build error (Issue #30480)





 
@732175344, sorry, I can't see your mistake in your reply.

**Comment by JonLiu1993** [comment]
@732175344, Have you considered @FrankXie05 's suggestion? Does this problem still exist
