### ISSUE TITLE
Port Request: TensorFlow

### ISSUE THREAD

**Issue by KindDragon** [microsoft/vcpkg#3048]
https://github.com/tensorflow/tensorflow.

How build with CMake https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cmake#step-by-step-windows-build

**Comment by Vigilans-Yea** [comment]
There is an unofficial cmake build solution for linux: [tensorflow_cc](https://github.com/FloopCZ/tensorflow_cc), which will fall back to bazel when building with GPU support. 

It seems that the solution provided by tensorflow already fully supports such features, so it may be worth the effort to port it to vcpkg 😄   
  
Looking forward to seeing my tf Graph easily running on C++👏

**Comment by nartes** [comment]
1. Yeah, this is awfull! Everybody is using tensorflow, yet no one has provided a convient package for it.
Even archlinux provides some idiotic libtensorflow.so library which contains 2K C header. You can't use that for any development at all.
2. [tensorflow_cc](https://github.com/FloopCZ/tensorflow_cc) seems to be a good starting point. Although [tensorflow(archlinux)](https://www.archlinux.org/packages/community/x86_64/tensorflow/) is good as well.

**Comment by nartes** [comment]
A request for packaging standalone C++ library with headers at tensorflow issue tracker. [1](https://github.com/tensorflow/tensorflow/issues/24885)

**Comment by NancyLi1013** [comment]
Hi @KindDragon  thanks for posting this request. The PR #7568 has been merged to master. Please try to update vcpkg and use it.
