### ISSUE TITLE
[ngspice] build failure because of broken download link

### ISSUE THREAD

**Issue by applicate2628** [microsoft/vcpkg#30488]
**Host Environment**

- OS: Windows 11
- Compiler: msvc2022

**To Reproduce**

`./vcpkg install ngspice`

**Failure logs**

```
error: Failed to download from mirror set
error: https://sourceforge.net/projects/ngspice/files/ng-spice-rework/37/ngspice-37.tar.gz/download: failed: status code 404
```

**Additional context**

I found that actual link differ and it should be:
https://sourceforge.net/projects/ngspice/files/ng-spice-rework/old-releases/37/ngspice-37.tar.gz/download

I solved the problem temporary for myself by changing the line 9 of the portfile.cmake:
    `REF 37` -> `REF old-releases/37`

But the better solution is expected as vcpkg port update to actual version 39.

**Comment by bhpeng21** [comment]
I noticed that the ngspice library has been updated to 41. Could you please update the port?
