### ISSUE TITLE
Install head command with `--no-downloads` return error

### ISSUE THREAD

**Issue by KindDragon** [Microsoft/vcpkg#3049]
`vcpkg install folly --head --no-downloads`
Return error:
```
-- Using cached D:/Work/vcpkg/downloads/facebook-folly-master.tar.gz
CMake Error at scripts/cmake/vcpkg_extract_source_archive.cmake:36 (message):
  Must specify ARCHIVE parameter to vcpkg_extract_source_archive_ex()
Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:153 (vcpkg_extract_source_archive_ex)
  ports/folly/portfile.cmake:17 (vcpkg_from_github)
  scripts/ports.cmake:72 (include)
```

**Comment by JackBoosY** [comment]
@KindDragon  The latest version build result here:

> PS E:\vcpkg> .\vcpkg.exe install folly:x64-windows --head --no-downloads
The following packages will be built and installed:
    folly[core,zlib]:x64-windows (from HEAD)
Starting package 1/1: folly:x64-windows
Building package folly[core,zlib]:x64-windows from HEAD...
-- Warning: Dynamic building not supported yet. Building static.
CMake Error at scripts/cmake/vcpkg_from_github.cmake:133 (message):
  Downloads are disabled, but
  'E:/vcpkg/downloads/facebook-folly-master.tar.gz' does not exist.
Call Stack (most recent call first):
  ports/folly/portfile.cmake:17 (vcpkg_from_github)
  scripts/ports.cmake:71 (include)
Error: Building package folly:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: folly:x64-windows
  Vcpkg version: 2018.11.23-nohash
Additionally, attach any relevant sections from the log files above.

Could you repro this question after update vcpkg?

**Comment by JackBoosY** [comment]
Hi @KindDragon , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
