### ISSUE TITLE
[vcpkg fails to install grpc after trying to download zlib] build failure

### ISSUE THREAD

**Issue by andresjimenezni** [microsoft/vcpkg#30494]
**Host Environment**

- OS: Windows 10
- Compiler: revision

**To Reproduce**

`./vcpkg install grpc`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

Restored 0 package(s) from C:\Users\andjimen\AppData\Local\vcpkg\archives in 483.7 us. Use --debug to see more details.
Installing 1/8 zlib:x64-windows...
Building zlib[core]:x64-windows...
-- Downloading https://github.com/madler/zlib/archive/v1.2.13.tar.gz -> madler-zlib-v1.2.13.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from C:\protobufTest3\Helloworld\protobuf\protobuf-3.14.0\src\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: C:\protobufTest3\Helloworld\protobuf\protobuf-3.14.0\src\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
Downloading https://github.com/madler/zlib/archive/v1.2.13.tar.gz
warning: Download failed -- retrying after 1000ms
warning: Download failed -- retrying after 2000ms
warning: Download failed -- retrying after 4000ms
error: Failed to download from mirror set
error: https://github.com/madler/zlib/archive/v1.2.13.tar.gz: WinHttpSendRequest failed with exit code 12002
error: https://github.com/madler/zlib/archive/v1.2.13.tar.gz: WinHttpSendRequest failed with exit code 12002
error: https://github.com/madler/zlib/archive/v1.2.13.tar.gz: WinHttpSendRequest failed with exit code 12002
error: https://github.com/madler/zlib/archive/v1.2.13.tar.gz: WinHttpSendRequest failed with exit code 12002
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(960):
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 6us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 4577us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 1.5254362066666667 min (91434600us)

When I try go to https://github.com/madler/zlib/archive I can´t access it because the page does not exist anymore, so I went to https://github.com/madler/zlib and there is no archive folder anymore, I think that there is where it fails since the folder it is trying to access is not there anymore. 

Add any other context about the problem here, such as what you have already tried to resolve the issue.
I was able to download zlib-1.2.13.zip from the releases (https://github.com/madler/zlib/releases/tag/v1.2.13) but I am not so sure what files I have to use and where and if I have to point it locally.

**Comment by JonLiu1993** [comment]
@andresjimenezni, Thanks for posting this issue, please make sure your network is smooth and the proxy is available.

**Comment by andresjimenezni** [comment]
Hi @JonLiu1993 , I checked the recommendations of having an stable connection and having the proxy available but the problem seems to be when it tries to download the v1.2.13.tar.gz file (https://github.com/madler/zlib/archive/v1.2.13.tar.gz).
If you go to the URL you will get an 404 error and if you visit (https://github.com/madler/zlib) you will find that there is no _archive_ folder anymore; so the vcpkg package manager keeps on trying this and will always return an error because the folder does not exist.

**Comment by dg0yt** [comment]
https://github.com/madler/zlib/archive/v1.2.13.tar.gz can be downloaded here.
https://github.com/madler/zlib/archive isn't a source code code folder but an API endpoint which generates tarballs. It needs extra parameters.

**Comment by JonLiu1993** [comment]
@andresjimenezni, As @dg0yt said https://github.com/madler/zlib/archive/v1.2.13.tar.gz can be downloaded normally, it is a whole, open https://github.com/madler alone /zlib/archive is not feasible, you can't succeed when downloading https://github.com/madler/zlib/archive/v1.2.13.tar.gz now, so we think it's your network or anti-virus software or firewall Other reasons have organized you to download this package

**Comment by andresjimenezni** [comment]
Hello @dg0yt @JonLiu1993 , thank you so much, I checked my protections and there was one of them that was preventing me from downloading the file and from accessing the API endpoint.
