### ISSUE TITLE
[librdkafka] Build error

### ISSUE THREAD

**Issue by mortezabayat** [microsoft/vcpkg#30516]
**Host Environment**

- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**

`./vcpkg install xxxx`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by autoantwort** [comment]
Please close this issue or fill out the issue template :)

**Comment by LilyWangLL** [comment]
@mortezabayat Please provide the error log.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue with more info if this is still a problem for you.

**Comment by mortezabayat** [comment]
I build librckafka for android but, there is not libsasel2 configuration in
vcpkg.

**Comment by LilyWangLL** [comment]
Please refer to this issue https://github.com/microsoft/vcpkg/issues/30604 to provide the error log and your environment information.
