### ISSUE TITLE
Clarify where to run vcpkg integrate install from

### ISSUE THREAD

**Issue by mloskot** [microsoft/vcpkg#3052]
Is it required to run `integrate install` from Vcpkg installation folder

```bat
cd c:\vcpkg
vcpkg integrate install
```
or is it correct to run it from any location

```bat
set PATH=c:\vcpkg;%PATH%
vcpkg integrate install
```

it is not cleared up in the docs, AFAICT.

## References

#1874

**Comment by ras0219-msft** [comment]
Thanks for posting this issue!

Either way should work identically* for general usage.

*(we do take current directory into account if you have multiple vcpkg instances -- if your current path is inside a vcpkg repo, we will use that as the root instead of the one containing the vcpkg.exe you are running)

**Comment by Voskrese** [comment]
@mloskot так не проще?
c:\vcpkg\vcpkg.exe integrate install

**Comment by mloskot** [comment]
@Voskrese 
> @mloskot так не проще?

I wish, but I can't read it, sorry.

> c:\vcpkg\vcpkg.exe integrate install

That makes the third option, indeed.


@ras0219-msft Does this summary express the correct behaviours?

1. `cd c:\vcpkg && vcpkg.exe integrate install` - integrates `c:\vcpkg` repo

2. `set PATH=c:\vcpkg;%PATH% && cd \ && vcpkg.exe integrate install` - integrates `vcpkg.exe`'s directory `c:\vcpkg` as Vcpkg repo

3. `cd \ && c:\vcpkg\vcpkg.exe integrate install` - same as 2.

4. `cd c:\secondary-vcpkg && c:\main-vcpkg\vcpkg.exe integrate install` - integrates *current directory* `c:\secondary-vcpkg` as Vcpk repo, regardless where of `vcpkg.exe` location.

**Comment by ras0219-msft** [comment]
Yes, that's correct. The steps are simply:
1. Determine the vcpkg root to execute in (via the process above)
2. Set this as the user-wide instance

**Comment by mloskot** [comment]
I sense it is worth to include such explanation in the docs, but I'm not seeing how to document it neatly, without making the docs too overwhelming with too many examples really.

**Comment by mloskot** [comment]
@ras0219-msft If you could point location where such info would belong best in the docs (FAQ?), then I will try to prepare PR, so we can get it closed :)

**Comment by NancyLi1013** [comment]
Hi @mloskot 

Personally speaking,  where to run vcpkg integrate install has been clarified in [README.md ](https://github.com/microsoft/vcpkg/blob/master/README.md) and you can also refer to this [doc ](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md) to learn the detailed introduction about this command.
