### ISSUE TITLE
[gmp] build failure

### ISSUE THREAD

**Issue by applicate2628** [microsoft/vcpkg#30528]
**Host Environment**

- OS: Windows
- Compiler: msvc2022

**To Reproduce**

`./vcpkg install gmp:x64-windows`

**Failure logs**

```
-- Using cached msys-gcc-libs-11.2.0-3-x86_64.pkg.tar.zst.
-- Using cached msys-msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst.
-- Using cached msys-which-2.21-4-x86_64.pkg.tar.zst.
-- Using msys root at c:/vcpkg/downloads/tools/msys2/ca907ea16f6f2ba5
CMake Error at scripts/cmake/vcpkg_configure_make.cmake:616 (message):
  gmp requires autoconf from the system package manager (example: "sudo
  apt-get install autoconf")
Call Stack (most recent call first):
  ports/gmp/portfile.cmake:85 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)
```

**Additional context**

Also there were some problems with downloading msys-msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst and msys-which-2.21-4-x86_64.pkg.tar.zst at the new environment so i used cached from previous.

**Comment by AnthonyMastrean** [comment]
I'm having the same problem installing `icu` (#30588)! The msys2-runtime package seems to be legitimately missing from every mirror. I'm not familiar enough with msys2-runtime to go figure out if this was planned or not... do you have any advice?

**Comment by applicate2628** [comment]
> I'm having the same problem installing `icu` (#30588)! The msys2-runtime package seems to be legitimately missing from every mirror. I'm not familiar enough with msys2-runtime to go figure out if this was planned or not... do you have any advice?

There is already pull request for msys update https://github.com/microsoft/vcpkg/pull/30546 so wait or use cached ones.

**Comment by dg0yt** [comment]
#30546 was just merged.
