### ISSUE TITLE
[luajit] Build error

### ISSUE THREAD

**Issue by Zyraff** [microsoft/vcpkg#30524]
Package: luajit[core]:x64-windows -> 2023-01-04

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.35.32216.1
-    vcpkg-tool version: 2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454
    vcpkg-scripts version: 1271068e1 2023-03-28 (16 hours ago)

**To Reproduce**

`vcpkg install luajit:x64-windows`

**Failure logs**

```
-- Using cached LuaJIT-LuaJIT-d0e88930ddde28ff662503f9f20facf34f7265aa.tar.gz.
-- Cleaning sources at E:/Repo/vcpkg/buildtrees/luajit/src/f34f7265aa-d28f2f5801.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/Repo/vcpkg/downloads/LuaJIT-LuaJIT-d0e88930ddde28ff662503f9f20facf34f7265aa.tar.gz
-- Applying patch 003-do-not-set-macosx-deployment-target.patch
-- Applying patch 004-fix-build-path-and-crt-linkage.patch
-- Using source at E:/Repo/vcpkg/buildtrees/luajit/src/f34f7265aa-d28f2f5801.clean
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process_repeat.cmake:65 (message):
    Command failed: "E:/Repo/vcpkg/buildtrees/luajit/src/f34f7265aa-d28f2f5801.clean/src/msvcbuild.bat" "E:/Repo/vcpkg/buildtrees/luajit/src/f34f7265aa-d28f2f5801.clean/src" dynamic debug
    Working Directory: E:/Repo/vcpkg/buildtrees/luajit/x64-windows-dbg
    See logs for more information:
      E:\Repo\vcpkg\buildtrees\luajit\build-x64-windows-dbg-out-1.log
      E:\Repo\vcpkg\buildtrees\luajit\build-x64-windows-dbg-out-1.log

Call Stack (most recent call first):
  ports/luajit/portfile.cmake:43 (vcpkg_execute_required_process_repeat)
  scripts/ports.cmake:147 (include)



```

**Additional context**
[build-x64-windows-dbg-out-1.log](https://github.com/microsoft/vcpkg/files/11102736/build-x64-windows-dbg-out-1.log)

**Comment by dg0yt** [comment]
https://github.com/microsoft/vcpkg/blob/1271068e139c1fc30bae405c0bca0e379e155bd2/ports/luajit/004-fix-build-path-and-crt-linkage.patch#L41

This (upstream) line and similar ones may need to be patched to use `"%~1"` instead of `"%1"` in order to remove quotes in incoming arguments.

**Comment by FrankXie05** [comment]
This is an upstream bug, and I will report it to the upstream and submit a PR .

**Comment by dg0yt** [comment]
Does the error really occur for a regular working dir? It doesn't fail in vcpkg CI.

FTR the initial post used a working direcory with space in working dir:
~~~
-- Cleaning sources at E:/OTS Repo/vcpkg/buildtrees/luajit/src/f34f7265aa-d28f2f5801.clean. Use --editable to skip cleaning for the packages you specify.
~~~
In this case, quotes are necessary to pass parameters,

**Comment by Zyraff** [comment]
Sorry for the confusion, original working directory indeed contains a space and after changing it, it worked.
before: E:/OTS Repo/vcpkg 
after: E:/Repo/vcpkg

**Comment by FrankXie05** [comment]
The path parameter should not have been passed.  Draft my PR, and waiting for Upstream repair. 
https://github.com/LuaJIT/LuaJIT/pull/976#issuecomment-1489861287

**Comment by dg0yt** [comment]
This first parameter is from the massive vcpkg patch for out of source builds.
This should be revised to be less invasive. Use `shift`, or use `%4`, or simply avoid patching and copy the source instead.

**Comment by dg0yt** [comment]
#30608 is ready for testing. It removed the pattern which caused this issue, but I did not check if other spots continue to block paths with spaces.

**Comment by FrankXie05** [comment]
Has been fixed by PR https://github.com/microsoft/vcpkg/pull/30608
