### ISSUE TITLE
[gmp] Build error: Failed to download from mirror set

### ISSUE THREAD

**Issue by silentstranger5** [microsoft/vcpkg#30530]
**Host Environment**

OS: Windows

**Steps to reproduce the behavior:**

`./vcpkg install gmp`

**Failure logs:**

    error: Failed to download from mirror set
    error: https://repo.msys2.org/msys/x86_64/msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst: failed: status code 404
    error: https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst: failed: status code 404
    error: https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst: failed: status code 404
    error: https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst: failed: status code 404
    error: https://mirrors.ustc.edu.cn/msys2/msys/x86_64/msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst: failed: status code 404
    error: https://mirror.bit.edu.cn/msys2/msys/x86_64/msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst: WinHttpSendRequest failed with exit code 12007
    error: https://mirror.bit.edu.cn/msys2/msys/x86_64/msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst: WinHttpSendRequest failed with exit code 12007
    error: https://mirror.bit.edu.cn/msys2/msys/x86_64/msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst: WinHttpSendRequest failed with exit code 12007
    error: https://mirror.bit.edu.cn/msys2/msys/x86_64/msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst: WinHttpSendRequest failed with exit code 12007
    error: https://mirror.selfnet.de/msys2/msys/x86_64/msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst: failed: status code 404
    error: https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst: failed: status code 404
    [DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(960):
    [DEBUG] Time in subprocesses: 0us
    [DEBUG] Time in parsing JSON: 5us
    [DEBUG] Time in JSON reader: 0us
    [DEBUG] Time in filesystem: 13983us
    [DEBUG] Time in loading ports: 0us
    [DEBUG] Exiting after 13.7187489 s (13680878us)

    CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

    Failed to download file with error: 1
    If you are using a proxy, please check your proxy setting. Possible causes are:

    1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
    to `https://address:port`. This is not correct, because `https://` prefix
    claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
    , etc..) is an HTTP proxy. Try setting `http://address:port` to both
    HTTP_PROXY and HTTPS_PROXY instead.

    2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
    set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
    The value set by your proxy might be wrong, or have same `https://` prefix issue.

    3. Your proxy's remote server is out of service.

    If you've tried directly download the link, and believe this is not a temporary download server failure, please submit an issue at 
    https://github.com/Microsoft/vcpkg/issues to report this upstream download server failure.

    Call Stack (most recent call first):
    scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
    scripts/cmake/vcpkg_acquire_msys.cmake:26 (vcpkg_download_distfile)
    scripts/cmake/vcpkg_acquire_msys.cmake:67 (z_vcpkg_acquire_msys_download_package)
    scripts/cmake/vcpkg_acquire_msys.cmake:345 (z_vcpkg_acquire_msys_declare_package)
    scripts/cmake/vcpkg_configure_make.cmake:224 (vcpkg_acquire_msys)
    ports/gmp/portfile.cmake:85 (vcpkg_configure_make)
    scripts/ports.cmake:147 (include)

    error: building gmp:x64-windows failed with: BUILD_FAILED
    error: Please ensure you're using the latest port files with `git pull` and `vcpkg update.
    Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+gmp
    You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[gmp]+Build+error
    Include '[gmp] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454
    vcpkg-scripts version: 23f0707b1 2023-03-29 (2 hours ago)

**Additional context:**

It seems like gmp is using msys2-runtime-3.2.0-8-x86_64, which is no longer available.

URL for package download (https://mirror.bit.edu.cn/msys2/msys/x86_64/msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst) is not available with WinHttpSendRequest exit code 12007

**Comment by jimwang118** [comment]
Can your network access https://repo.msys2.org/msys/x86_64/? Please make sure the network is normal.

**Comment by jimwang118** [comment]
This address can be accessed normally. (https://mirror.bit.edu.cn/msys2/msys/x86_64/msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst) The download of msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst is tried in multiple urls, as long as there is one that can be downloaded, there is no problem.

**Comment by silentstranger5** [comment]
Okay, I got it, thanks. It looks like the only available url to download this package is not available with WinHttpSendRequest exit code 12007. This is indeed a network issue. Last question. Can I get a solution to this problem?

**Comment by jimwang118** [comment]
You can set up a proxy or go through a VPN to access that url. This is not a vcpkg problem, I will close this issue. If you have other questions about vcpkg, you can resubmit an issue.

**Comment by jasonbeverage** [comment]
We are running into this issue as well, it looks like msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst is also no longer available in any of the mirrors so it can't be downloaded.

**Comment by brandon-kohn** [comment]
This is still happening from a clean install of vcpkg.

**Comment by dg0yt** [comment]
No fix merged yet, but you know now which change to cherry-pick. vcpkg Ci must rebuild a lot of ports for msys2 changes.

**Comment by silentstranger5** [comment]
I actually accessed this old package (from what appears to be an internal Chinese URL) using a Singapore VPN. But I found another problem. Is it normal that the setup and build of the package takes a really, I mean very long time (it takes about an hour and continues)???

**Comment by dg0yt** [comment]
> Is it fine that the configure and build of the package takes a really, I mean really long time (it takes about an hour and continues)

It is not normal, but such cases exist. This issue has gmp in its subject. For this particular port, you should install clang-cl from Visual Studio. Otherwise it will download and extract the official clang. I assume that this takes very long: Some people reported vcpkg would "hang" on downloading 7Z but nobody actually verified that it was slow extracting of llvm using the quickly downloaded 7Z...

**Comment by konglingxue123** [comment]
@jimwang118 你好，https://mirror.bit.edu.cn/msys2/msys/x86_64/msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst这个网址现在应该是没有这个msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst文件了，可以将这个文件传输到git上吗？或者发送邮箱到1505072581@qq.com，谢谢！

**Comment by jimwang118** [comment]
> @jimwang118 你好，[https://mirror.bit.edu.cn/msys2/msys/x86_64/msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst这个网址现在应该是没有这个msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst文件了，可以将这个文件传输到git上吗？或者发送邮箱到1505072581@qq.com吗，谢谢！](https://mirror.bit.edu.cn/msys2/msys/x86_64/msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst%E8%BF%99%E4%B8%AA%E7%BD%91%E5%9D%80%E7%8E%B0%E5%9C%A8%E5%BA%94%E8%AF%A5%E6%98%AF%E6%B2%A1%E6%9C%89%E8%BF%99%E4%B8%AAmsys2-runtime-3.2.0-8-x86_64.pkg.tar.zst%E6%96%87%E4%BB%B6%E4%BA%86%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%B0%86%E8%BF%99%E4%B8%AA%E6%96%87%E4%BB%B6%E4%BC%A0%E8%BE%93%E5%88%B0git%E4%B8%8A%E5%90%97%EF%BC%9F%E6%88%96%E8%80%85%E5%8F%91%E9%80%81%E9%82%AE%E7%AE%B1%E5%88%B01505072581@qq.com%E5%90%97%EF%BC%8C%E8%B0%A2%E8%B0%A2%EF%BC%81)

We have fixed this issue in PR https://github.com/microsoft/vcpkg/pull/30546, you can try to update `vcpkg `to fix your issue.

**Comment by konglingxue123** [comment]
> 

Thanks for your reply! I download the recent vcpkg-master and fixed it! THX
