### ISSUE TITLE
[CURL] error on find_package(CURL CONFIG)

### ISSUE THREAD

**Issue by miurahr** [Microsoft/vcpkg#3053]
When testing with simple project, it fails building with error on find_package(CURL CONFIG)

test project: https://github.com/miurahr/vcpkg_curl_testcase
test result: https://ci.appveyor.com/project/miurahr/vcpkg-curl-testcase

```
CMake Error at C:/Tools/vcpkg/installed/x86-windows/share/curl/libcurl-target.cmake:78 (message):
  The imported target "CURL::libcurl" references the file
     "C:/Tools/vcpkg/installed/x86-windows/debug/lib/libcurl-d_imp.lib"
  but this file does not exist.  Possible reasons include:
  * The file was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and contained
     "C:/Tools/vcpkg/installed/x86-windows/share/curl/libcurl-target.cmake"
  but not all the files it references.
Call Stack (most recent call first):
  C:/Tools/vcpkg/installed/x86-windows/share/curl/curl-config.cmake:15 (include)
  C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake:263 (_find_package)
  CMakeLists.txt:3 (find_package)
-- Configuring incomplete, errors occurred!
See also "C:/Tools/vcpkg/build/CMakeFiles/CMakeOutput.log".
Command exited with code 1
```

**Comment by miurahr** [comment]
It happens because  just moving the file but not updating cmake target exports; 
ports/curl/portfile.cmake#L123 
```file(RENAME ${CURRENT_PACKAGES_DIR}/debug/lib/libcurl-d_imp.lib ${CURRENT_PACKAGES_DIR}/debug/lib/libcurl.lib)```

**Comment by miurahr** [comment]
I've checked a blame.
@pravic @ras0219-msft Is a change https://github.com/Microsoft/vcpkg/commit/f272a872d40edc2714f0b326e211e9b181aa65cc (#2862) make a degrade?

**Comment by miurahr** [comment]
@codicodi https://github.com/Microsoft/vcpkg/commit/ce452195c89df9f9a93e98bf27701a093d1550f1 introduced a library file renaming.

**Comment by miurahr** [comment]
I've reported to CMake project requesting fix for the issue in FindCURL.cmake
https://gitlab.kitware.com/cmake/cmake/issues/17887

**Comment by miurahr** [comment]
I've proposed a fix for the issue in CMake project.
https://gitlab.kitware.com/cmake/cmake/merge_requests/1940

**Comment by JasonDictos** [comment]
I've basically given up on trying to use the config for curl in vcpkg, instead we just look for the libs manually and we force a debug prefix so we can associate the libs properly per config. On windows I noticed the uppercase use of CURL breaks it too, lower case works even though the usage says otherwise.

**Comment by JackBoosY** [comment]
Hi Everyone, thanks for reporting this issue!
It seems to have fixed a near version. So I closed it.
Thx.
