### ISSUE TITLE
[New Port Request] JKQTPlotter

### ISSUE THREAD

**Issue by applicate2628** [microsoft/vcpkg#30545]
Library name: JKQTPlotter

Library description: This is an extensive C++ library for data visualization, plotting and charting for Qt.

Source repository URL: https://github.com/jkriege2/JKQtPlotter

Project homepage (if different from the source repository): https://marketplace.qt.io/products/jkqtplotter

Anything else that is useful to know when adding (such as optional features the library may have that should be included): qt5, qt6 support

**Comment by flexorx** [comment]
We need that port.
