### ISSUE TITLE
[openxr-loader] build failure

### ISSUE THREAD

**Issue by OBess** [microsoft/vcpkg#30540]
**x64**

- OS: Windows]
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31629 for x64

**vcpkg install openxr-loader:x64-windows-static**

![image](https://user-images.githubusercontent.com/34779566/228761587-c68b8890-694a-4ab1-bfd6-3c0421346386.png)

**Failure logs**

-- Installing: C:/My/Projects/vcpkg/packages/openxr-loader_x64-windows-static/share/openxr-loader/copyright
-- Performing post-build validation
warning: The following binaries should use the Static Debug (/MTd) CRT.
    C:\My\Projects\vcpkg\packages\openxr-loader_x64-windows-static\debug\lib\openxr_loaderd.lib links with: Dynamic Debug (/MDd)
To inspect the lib files, use:
    dumpbin.exe /directives mylibfile.lib
warning: The following binaries should use the Static Release (/MT) CRT.
    C:\My\Projects\vcpkg\packages\openxr-loader_x64-windows-static\lib\openxr_loader.lib links with: Dynamic Release (/MD)
To inspect the lib files, use:
    dumpbin.exe /directives mylibfile.lib
error: Found 2 post-build check problem(s). To submit these ports to curated catalogs, please first correct the portfile: C:\My\Projects\vcpkg\ports\openxr-loader\portfile.cmake
Stored binary cache: "C:\Users\NITRO\AppData\Local\vcpkg\archives\75\7523e80ab579c863c743d3340a26cc1b6c7d92d53591b9d69573d3044061032e.zip"
Elapsed time to handle openxr-loader:x64-windows-static: 38.834091 s
Total install time: 41.6955924 s

![image](https://user-images.githubusercontent.com/34779566/228761520-43d26fed-0b10-4ced-8c9c-5a872a163b2c.png)

**Additional context**

Hello. I want to build openxr-loader in static mode, but when I do that I get problem about CRT, because I am linking all libs in static mode and that's why I use 
![image](https://user-images.githubusercontent.com/34779566/228761865-d2576cc5-197b-48d4-b264-a9e8816230a8.png)
- therefore I changed some script lines in port (screenshot above), and then I get this problem. Can you help me with this? Thx!

**Comment by FrankXie05** [comment]
@OBess
>Hello. I want to build openxr-loader in static mode

Just run command `./vcpkg install openxr-loader:x64-windows-static`, do not modify any code.
