### ISSUE TITLE
[polyhook2] update to 2023-02-24

### ISSUE THREAD

**Issue by SNMetamorph** [microsoft/vcpkg#30549]
Library name: PolyHook2

New version number: 2023-02-24

Other information that may be useful (release notes, etc...)
Commit that matches this version: https://github.com/stevemk14ebr/PolyHook_2_0/commit/71d273463a3c4e30ec0a4031c4b477b85ea773fb

**Comment by SNMetamorph** [comment]
Hello guys, any plans for this?

**Comment by FrankXie05** [comment]
Today I will complete this issue with a new PR. :)

**Comment by FrankXie05** [comment]
Will be fixed by PR https://github.com/microsoft/vcpkg/pull/27683
