### ISSUE TITLE
Could not locate a complete toolset.

### ISSUE THREAD

**Issue by daoqiang** [Microsoft/vcpkg#3055]
PS D:\soft\vcpkg> ./vcpkg install sqlite3:x86-windows-static
The following packages will be built and installed:
    sqlite3[core]:x86-windows-static
Starting package 1/1: sqlite3:x86-windows-static
Building package sqlite3[core]:x86-windows-static...
A suitable version of cmake was not found (required v3.10.2). Downloading portable cmake v3.10.2...
A suitable version of git was not found (required v2.16.2). Downloading portable git v2.16.2...
Warning: The following VS instances are excluded because the English language pack is unavailable.
    D:\Develop\Microsoft Visual Studio\2017\Professional
Please install the English language pack.
Could not locate a complete toolset.
The following paths were examined:
    D:\Develop\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\Build\vcvarsall.bat
    D:\Develop\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.13.26128\bin\HostX86\x86\dumpbin.exe
    D:\Develop\Microsoft Visual Studio 14.0\VC\vcvarsall.bat

**Comment by ras0219-msft** [comment]
Thanks for posting this issue!

>Warning: The following VS instances are excluded because the English language pack is unavailable.
D:\Develop\Microsoft Visual Studio\2017\Professional
Please install the English language pack.

Due to misbehavior on the part of some buildsystems, we require the English language pack to be installed.

**Comment by jingxa** [comment]
i install english pack, but it doesnt work! how to solve this problem?

**Comment by jingxa** [comment]
install english pack! it works!
