### ISSUE TITLE
[libmesh] Build error

### ISSUE THREAD

**Issue by kamirow** [microsoft/vcpkg#30561]
**Host Environment**

- OS: Windows
- Compiler: revision

**To Reproduce**

vcpkg install libmesh:x86-windows

Computing installation plan...
warning: vcpkg appears to be in a Visual Studio prompt targeting x64 but installing for x86-windows. Consider using --triplet x64-windows or --triplet x64-uwp.
The following packages will be built and installed:
    libmesh[core]:x86-windows -> 1.5.0#4
Detecting compiler hash for triplet x86-windows...
Restored 0 package(s) from C:\Users\dongwon\AppData\Local\vcpkg\archives in 292.3 us. Use --debug to see more details.
Installing 1/1 libmesh:x86-windows...
Building libmesh[core]:x86-windows...
-- Using cached libMesh-libmesh-21f623c837b3865ed65ec9608b357bdb1935d428.tar.gz.
-- Cleaning sources at C:/Library_Out/vcpkg/buildtrees/libmesh/src/db1935d428-7b6bc82081.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Library_Out/vcpkg/downloads/libMesh-libmesh-21f623c837b3865ed65ec9608b357bdb1935d428.tar.gz
-- Using source at C:/Library_Out/vcpkg/buildtrees/libmesh/src/db1935d428-7b6bc82081.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x86-windows
-- Using cached msys-gzip-1.11-1-x86_64.pkg.tar.zst.
-- Using cached msys-bash-5.1.008-1-x86_64.pkg.tar.zst.
-- Using cached msys-autoconf-2.71-3-any.pkg.tar.zst.
-- Using cached msys-diffutils-3.8-2-x86_64.pkg.tar.zst.
-- Using cached msys-binutils-2.37-5-x86_64.pkg.tar.zst.
-- Using cached msys-libtool-2.4.7-3-x86_64.pkg.tar.zst.
-- Using cached msys-file-5.41-2-x86_64.pkg.tar.zst.
-- Using cached msys-zlib-1.2.11-1-x86_64.pkg.tar.xz.
-- Using cached msys-libbz2-1.0.8-3-x86_64.pkg.tar.zst.
-- Using cached msys-coreutils-8.32-2-x86_64.pkg.tar.zst.
-- Using cached msys-grep-3.0-2-x86_64.pkg.tar.xz.
-- Using cached msys-sed-4.8-2-x86_64.pkg.tar.zst.
-- Using cached msys-libpcre-8.45-1-x86_64.pkg.tar.zst.
-- Using cached msys-m4-1.4.19-2-x86_64.pkg.tar.zst.
-- Using cached msys-automake-wrapper-11-4-any.pkg.tar.zst.
-- Using cached msys-gawk-5.1.0-2-x86_64.pkg.tar.zst.
-- Using cached msys-mpfr-4.1.0-1-x86_64.pkg.tar.zst.
-- Using cached msys-gmp-6.2.1-1-x86_64.pkg.tar.zst.
-- Using cached msys-libreadline-8.1.001-1-x86_64.pkg.tar.zst.
-- Using cached msys-ncurses-6.2-2-x86_64.pkg.tar.zst.
-- Using cached msys-automake1.16-1.16.3-3-any.pkg.tar.zst.
-- Using cached msys-perl-5.32.1-2-x86_64.pkg.tar.zst.
-- Using cached msys-libcrypt-2.1-3-x86_64.pkg.tar.zst.
-- Using cached msys-pkg-config-0.29.2-4-x86_64.pkg.tar.zst.
-- Using cached msys-make-4.3-3-x86_64.pkg.tar.zst.
-- Using cached msys-findutils-4.8.0-1-x86_64.pkg.tar.zst.
-- Using cached msys-libintl-0.21-1-x86_64.pkg.tar.zst.
-- Using cached msys-libiconv-1.16-2-x86_64.pkg.tar.zst.
-- Using cached msys-gcc-libs-11.2.0-3-x86_64.pkg.tar.zst.
-- Using cached msys-msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst.
-- Using cached msys-which-2.21-4-x86_64.pkg.tar.zst.
-- Using msys root at C:/Library_Out/vcpkg/downloads/tools/msys2/ca907ea16f6f2ba5
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at C:/Library_Out/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Configuring x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/Library_Out/vcpkg/downloads/tools/msys2/ca907ea16f6f2ba5/usr/bin/bash.exe --noprofile --norc --debug -c "V=1 CPP='cl.exe -E' CC='cl.exe' CC_FOR_BUILD='touch a.out | touch conftest.exe | true' CPP_FOR_BUILD='touch a.out | touch conftest.exe | true' CXX_FOR_BUILD='touch a.out | touch conftest.exe | true' CXX='cl.exe' RC='rc.exe' WINDRES='rc.exe' AR='lib.exe' LD='link.exe -verbose' RANLIB=':' STRIP=':' NM='dumpbin.exe -symbols -headers' DLLTOOL='link.exe -verbose -dll' CCAS=':' AS=':' ./../src/db1935d428-7b6bc82081.clean/configure --build=x86_64-pc-mingw32 --host=i686-pc-mingw32 \"--disable-qhull\" \"ac_cv_prog_ac_ct_STRIP=:\" \"gl_cv_double_slash_root=yes\" \"ac_cv_func_memmove=yes\" \"--disable-silent-rules\" \"--verbose\" \"--enable-shared\" \"--disable-static\" \"--with-methods=dbg\" \"--prefix=/C/Library_Out/vcpkg/installed/x86-windows/debug\" \"--bindir=\\${prefix}/../tools/libmesh/debug/bin\" \"--sbindir=\\${prefix}/../tools/libmesh/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/libmesh\""
    Working Directory: C:/Library_Out/vcpkg/buildtrees/libmesh/x86-windows-dbg
    Error code: 1
    See logs for more information:
      C:\Library_Out\vcpkg\buildtrees\libmesh\config-x86-windows-dbg-config.log
      C:\Library_Out\vcpkg\buildtrees\libmesh\config-x86-windows-dbg-out.log
      C:\Library_Out\vcpkg\buildtrees\libmesh\config-x86-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:829 (vcpkg_execute_required_process)
  ports/libmesh/portfile.cmake:18 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)

error: building libmesh:x86-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libmesh
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libmesh]+Build+error
Include '[libmesh] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-02-16-12e657924d99511514c0287ca5ce46882d3657c7
    vcpkg-scripts version: c9f906558 2023-03-30 (82 minutes ago)

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Adela0814** [comment]
Confirmed.
config-x86-windows-dbg-err.log
`configure: error: cannot check for file existence when cross compiling.`

**Comment by Adela0814** [comment]
Currently, libmesh  doesn't support windows. Duplicated to https://github.com/microsoft/vcpkg/issues/11835. Let's track this issue there.
