### ISSUE TITLE
[vcpkg] More documentation needed for --vcpkg-root

### ISSUE THREAD

**Issue by Tryum** [microsoft/vcpkg#3056]
I wanted to integrate a subset of ports directly in my project to keep them in sync.

It's not clear what is needed in the vcpkg-root specified directory. I assumed *wrongly* that ports and triplets would be sufficient, and all the other files are taken directly from the binary folder.

**Comment by codewiz** [comment]
I'm using vcpkg for the first time, and I'm also baffled by this error message. What should I do?

I installed vcpkg from the Fedora rpm packages, and I expected to be able to type "vcpkg install <package>" right away. The top-level documentation of vcpkg does not mention the need to setup anything.

**Comment by Thomas1664** [comment]
@vicroms I think this issue can be closed because `--vcpkg-root` is already documented: https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/commands/common-options.md#---vcpkg-rootpath

**Comment by Thomas1664** [comment]
@LilyWangLL I think this issue can be closed.
