### ISSUE TITLE
Using CMake with vcpkg: Is it idiomatic to use FetchContent to obtain vcpkg?

### ISSUE THREAD

**Issue by dantamont** [microsoft/vcpkg#30572]
I have a strong preference to not use git submodules (they are a hot mess), and noticed that the README.md [used to have instructions for how to use FetchContent to obtain/use vcpkg in a CMake project.](https://github.com/microsoft/vcpkg/pull/27158/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

Is there a reason these instructions were removed? I really like the look of this approach.

**Comment by Cheney-W** [comment]
https://github.com/microsoft/vcpkg/pull/27311
Here is the reason why the document was deleted.

**Comment by Neumann-A** [comment]
@dantamont: Do as you like. Might want to also read https://discourse.cmake.org/t/built-in-package-manager-for-cmake-modules/7513/6. 
Basically passing `SOURCE_DIR` would fix the issue mentioned in #27311

**Comment by dantamont** [comment]
Cool, I suspected that the motivation was something similar to that thread, but I was going to do exactly as you've suggested @Neumann-A . Thanks!
