### ISSUE TITLE
Fail to build opencv: 'file problem creating directory'

### ISSUE THREAD

**Issue by embeh** [Microsoft/vcpkg#3057]
While trying to build opencv:x64-windows, vcpkg repeatedly errors out with this error:
```
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:72 (file):
  file problem creating directory:
  D:/downloads/code/visual_studio/vcpkg/downloads/temp
Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/eigen3/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:72 (include)

```
This has happened for several dependency of opencv, starting with libjpeg-turbo[core]:x64-windows. Restarting the process, the build will actually succeed for the offending package, only to fail on the next one. 

Note that the folder in question is just fine, plenty of space, write permissions etc.

Here's the full list of dependencies that failed on first attempt, and worked on second (in the order the errors occurred):
libjpeg-turbo[core]:x64-windows
tiff[core]:x64-windows
eigen3[core]:x64-windows
opencv[core,eigen,flann,jpeg,opengl,png,tiff]:x64-windows

FWIW, restarting the vcpkg command after the error succeeds after a very long time (~ 10 min., the line 'Building package...' just sits there for many minutes), not sure this is to be expected?

System details:
Win7 x64 english
Command used: vcpkg.exe install opencv:x64-windows
Vcpkg version: 0.0.105-2018-03-16-7528c4d525419a418e8e0046f6650b833ad75fd7

**Comment by alexkaratarakis** [comment]
The `Building package...` is expected to take some time, that is where the main part of the build is taking place.
However, the failure is unexpected. 
Can you try deleting the `buildtrees\` directory and see if the issue persists?
Alternatively, you can try using a fresh clone of `vcpkg` in another directory.

**Comment by embeh** [comment]
Weird. Deleting the buildtrees folder, and also 'remove''ing all installed packages, I re-ran the 'opencv:x64-windows' install, and now it seems to simply work, including all dependencies, and also a lot faster (one package is now 2min instead of 10min).... no idea, what is different now. Maybe network problems?

**Comment by NancyLi1013** [comment]
Please open a new issue if this is still a problem for you.
