### ISSUE TITLE
[New Port Request] bit7z

### ISSUE THREAD

**Issue by Nosenzor** [microsoft/vcpkg#30586]
Library name: bit7z

Library description:A C++ static library offering a clean and simple interface to the 7-zip shared libraries

Source repository URL: https://github.com/rikyoz/bit7z

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
Latest version is 3.2.0 https://github.com/rikyoz/bit7z/releases/tag/v3.2.0

**Comment by JonLiu1993** [comment]
Fixed by #31729

**Comment by Nosenzor** [comment]
Thx

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
