### ISSUE TITLE
gRPC++ reflection library is missing for x86-windows triplet

### ISSUE THREAD

**Issue by ATN-44** [microsoft/vcpkg#30587]
**Environment**
- OS: [Windows 10]
- Compiler: [CMAKE]

**To Reproduce**
1. Install gRPC using vcpkg: `.\vcpkg install grpc:x86-windows`
2. Check the installed libraries in the `F:\vcpkg\installed\x86-windows\lib` directory.

**Expected behavior**
The `grpc++_reflection.lib` library should be present in the `F:\vcpkg\installed\x86-windows\lib` directory, but it is missing.

**Additional context**
I have tried reinstalling the package, but the issue persists. The `grpc++_reflection.lib` library is present for the x64-windows triplet but not for the x86-windows triplet. Here is the list of files in the `F:\vcpkg\installed\x86-windows\lib` directory after the installation:

PS F:\vcpkg\installed\x86-windows\lib> dir
Directory: F:\vcpkg\installed\x86-windows\lib
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         3/31/2023   1:20 PM                pkgconfig
-a----         3/31/2023  10:05 AM        3814952 abseil_dll.lib
-a----         3/31/2023  10:05 AM         202856 absl_cordz_functions.lib
-a----         3/31/2023  10:05 AM         501376 absl_cordz_handle.lib
-a----         3/31/2023  10:05 AM         571146 absl_cordz_info.lib
-a----         3/31/2023  10:05 AM         291274 absl_cordz_sample_token.lib
-a----         3/31/2023  10:05 AM        2708176 absl_cord_internal.lib
-a----         3/31/2023  10:05 AM         497396 absl_crc_cord_state.lib
-a----         3/31/2023  10:05 AM         266630 absl_flags.lib
-a----         3/31/2023  10:05 AM         149774 absl_flags_commandlineflag.lib
-a----         3/31/2023  10:05 AM          10424 absl_flags_commandlineflag_internal.lib
-a----         3/31/2023  10:05 AM         701732 absl_flags_config.lib
-a----         3/31/2023  10:05 AM         821938 absl_flags_internal.lib
-a----         3/31/2023  10:05 AM        1068656 absl_flags_marshalling.lib
-a----         3/31/2023  10:05 AM        2294740 absl_flags_parse.lib
-a----         3/31/2023  10:05 AM         176688 absl_flags_private_handle_accessor.lib
-a----         3/31/2023  10:05 AM         376298 absl_flags_program_name.lib
-a----         3/31/2023  10:05 AM        1897520 absl_flags_reflection.lib
-a----         3/31/2023  10:05 AM         354714 absl_flags_usage.lib
-a----         3/31/2023  10:05 AM        2201402 absl_flags_usage_internal.lib
-a----         3/31/2023  10:05 AM         680224 absl_log_flags.lib
-a----         3/31/2023  10:05 AM          65094 absl_low_level_hash.lib
-a----         3/31/2023  10:05 AM         682856 absl_random_internal_distribution_test_util.lib
-a----         3/31/2023  10:05 AM         678400 absl_statusor.lib
-a----         3/31/2023  10:05 AM         242958 absl_strerror.lib
-a----         3/31/2023  10:14 AM         192742 address_sorting.lib
-a----         3/31/2023  10:06 AM          14608 cares.lib
-a----         3/31/2023  10:11 AM          53724 descriptor_upb_proto.lib
-a----         3/31/2023  10:14 AM        5932028 gpr.lib
-a----         3/31/2023  10:17 AM      108105486 grpc++.lib
-a----         3/31/2023  10:17 AM        1551706 grpc++_alts.lib
-a----         3/31/2023  10:17 AM         134412 grpc++_error_details.lib
-a----         3/31/2023  10:17 AM       49964296 grpc++_unsecure.lib
-a----         3/31/2023  10:16 AM      897735718 grpc.lib
-a----         3/31/2023  10:17 AM       15773568 grpc_plugin_support.lib
-a----         3/31/2023  10:17 AM      617668444 grpc_unsecure.lib
-a----         3/31/2023  10:09 AM        1257642 libcrypto.lib
-a----         3/31/2023  10:10 AM        1081668 libprotobuf-lite.lib
-a----         3/31/2023  10:10 AM        4020006 libprotobuf.lib
-a----         3/31/2023  10:10 AM         384094 libprotoc.lib
-a----         3/31/2023  10:09 AM         126770 libssl.lib
-a----         3/31/2023  10:11 AM        3052950 re2.lib
-a----         3/31/2023  10:11 AM         494810 upb.lib
-a----         3/31/2023  10:11 AM          75838 upb_collections.lib
-a----         3/31/2023  10:11 AM          23328 upb_extension_registry.lib
-a----         3/31/2023  10:11 AM          10446 upb_fastdecode.lib
-a----         3/31/2023  10:11 AM         303362 upb_json.lib
-a----         3/31/2023  10:11 AM         122696 upb_mini_table.lib
-a----         3/31/2023  10:11 AM         527370 upb_reflection.lib
-a----         3/31/2023  10:11 AM          82036 upb_textformat.lib
-a----         3/31/2023  10:11 AM          10716 upb_utf8_range.lib
-a----         3/31/2023  10:11 AM          17156 zlib.lib
PS F:\vcpkg\installed\x86-windows\lib>

Please help me identify and resolve this issue. Thank you.

**Comment by jimwang118** [comment]
After checking the compiled generation path and compilation log, the upstream compilation script under x86-windows did not generate grpc++_reflection.lib, so it cannot be found under lib.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.

**Comment by ATN-44** [comment]
the same problem.

**Comment by sergeibobyr** [comment]
Was anything every fixed? I see the same issue on my system. 'vcpkg update' shows no updates available as of 5/15/23. grpc++_reflection.lib is not in vcpkg\installed\x86-windows\lib. As a result, gRPC projects cannot be built.

**Comment by ATN-44** [comment]
Sorry. It looks like nothing was changed. I found a way around but cannot
help at this moment. Andrew.

**Comment by matteolazzarotto** [comment]
I have the same porblem too

**Comment by lsadehaan** [comment]
I have the same problem. The x64 version has the grpc++_reflection lib (and also the grpcpp_channelz.lib) which the x86 version doesn't have for some reason. Can somebody please look into this? @ATN-44 what was your workaround?

**Comment by lsadehaan** [comment]
To anybody else having this problem, it seems adding [codegen] to the install command fixes it:
vcpkg install grpc[codegen]:x86-windows
See: https://github.com/microsoft/vcpkg/issues/31467

**Comment by jimwang118** [comment]
If you need grpc++_reflection.lib and grpcpp_channelz.lib, please install `codegen` feature.
