### ISSUE TITLE
Error boost

### ISSUE THREAD

**Issue by elliottdu17** [microsoft/vcpkg#30596]
I'm trying to run this command : 
.\vcpkg.exe install boost:x64-windows boost:x86-windows
but I keep getting an error message : 

error: building boost-exception:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-exception
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[boost-exception]+Build+error&body=Copy+issue+body+from+C%3A%2FUsers%2Fellio%2F.vcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

What am i doing wrong ?
![Capture d'écran 2023-04-01 140257](https://user-images.githubusercontent.com/77096763/229287550-fb0a1b4e-c092-4503-8ab5-e6bd246ffa2d.png)

**Comment by autoantwort** [comment]
Please post the generated issue body :)

**Comment by autoantwort** [comment]
You only have to click on the last link and follow the steps

**Comment by Adela0814** [comment]
@elliottdu17 Please provide the full repro steps and failure logs, thanks.

**Comment by Adela0814** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
