### ISSUE TITLE
boost-exception build failed

### ISSUE THREAD

**Issue by YunchengLiu** [microsoft/vcpkg#30597]
**OS**: windows 11
**Toolchain**: VS2022 with LLVM tools

I try a clang-cl [triplets](https://github.com/Neumann-A/my-vcpkg-triplets) to build for clang-cl packages using vcpkg.

but i got a build failed message when use **x64-win-llvm-lto** and **x64-win-llvm** both.

**x64-win-llvm-lto** failed at boost.regex (log file: [install-x64-win-llvm-lto-rel-out.log](https://github.com/microsoft/vcpkg/files/11129801/install-x64-win-llvm-lto-rel-out.log))

**x64-win-llvm**  failed at boost.exception (log file: [install-x64-win-llvm-dbg-out.log](https://github.com/microsoft/vcpkg/files/11129803/install-x64-win-llvm-dbg-out.log) )

The second error seems to be an abnormal command call caused by spaces in the path. Of course, I don't know if there will be follow-up problems after this problem is solved.

![image](https://user-images.githubusercontent.com/40971483/229296280-0c73fa61-18d6-44ee-8da8-00fed1467795.png)

I'm really not very proficient in cmake, and I can't figure out how to troubleshoot the problem. Is this a problem caused by triplets? Or some problem with clang-cl toolchain?

**Comment by MonicaLiu0311** [comment]
Could you please provide an example and steps to reproduce it?

**Comment by YunchengLiu** [comment]
I just use '.\vcpkg.exe install boost:x64-win-llvm-lto --overlay-triplets="path/to/triplets_dir"'.

My vcpkg is just pulled from github, and only installed default **x64-windows** packages(boost and etc..), LLVM tooltain is installed with VS2022 (shipped with MSVC 17.5.3 version).

Everything works fine when using the default MSVC, only now I want to migrate the work to the clang-cl compiler. 

Thank you for your help!

**Comment by YunchengLiu** [comment]
Hi, any progress on this issue?
