### ISSUE TITLE
Update msgpack-cpp

### ISSUE THREAD

**Issue by PhilippPaetzold** [microsoft/vcpkg#30615]
The current version of msgpack-cpp 3.3.0 in VCPKG has an annoying issue so compilation under windows fails due to redefinition of a struct: 

https://github.com/msgpack/msgpack-c/issues/1059#issue-1649754375

The latest version 6.6.0 fixes the issue. As 3.3.0 is pretty outdated anyway, it would be great, if vcpkg could be update to the latest version.

**Comment by Adela0814** [comment]
Fixed by https://github.com/microsoft/vcpkg/pull/30401.
