### ISSUE TITLE
[qt5-base] Build error

### ISSUE THREAD

**Issue by RainbowTaro2022** [microsoft/vcpkg#30619]
G:\Cone\vcpkg>vcpkg install kf5kcmutils
warning: Starting with the September 2023 release, the default triplet for vcpkg libraries will change from x86-windows to the detected host triplet (x64-windows). To resolve this message, add --triplet x86-windows to keep the same behavior.
Computing installation plan...
The following packages will be built and installed:
  * atlmfc[core]:x86-windows -> 0#1
  * ecm[core]:x86-windows -> 5.98.0
  * freeglut[core]:x86-windows -> 3.4.0
  * jasper[core,default-features,opengl]:x86-windows -> 4.0.0#1
  * kf5archive[bzip2,core]:x86-windows -> 5.98.0
  * kf5bookmarks[core]:x86-windows -> 5.98.0
  * kf5codecs[core]:x86-windows -> 5.98.0
  * kf5completion[core]:x86-windows -> 5.98.0
  * kf5config[core]:x86-windows -> 5.98.0
  * kf5configwidgets[core]:x86-windows -> 5.98.0
  * kf5coreaddons[core]:x86-windows -> 5.98.0
  * kf5crash[core]:x86-windows -> 5.98.0
  * kf5dbusaddons[core]:x86-windows -> 5.98.0
  * kf5declarative[core]:x86-windows -> 5.98.0
  * kf5guiaddons[core,defaults]:x86-windows -> 5.98.0
  * kf5i18n[core]:x86-windows -> 5.98.0
  * kf5iconthemes[core]:x86-windows -> 5.98.0
  * kf5itemviews[core]:x86-windows -> 5.98.0
  * kf5jobwidgets[core]:x86-windows -> 5.98.0
    kf5kcmutils[core]:x86-windows -> 5.98.0
  * kf5kio[core]:x86-windows -> 5.98.0
  * kf5notifications[core]:x86-windows -> 5.98.0
  * kf5package[core]:x86-windows -> 5.98.0
  * kf5service[core]:x86-windows -> 5.98.0
  * kf5solid[core,platform-default-features]:x86-windows -> 5.98.0#1
  * kf5sonnet[core]:x86-windows -> 5.98.0
  * kf5textwidgets[core]:x86-windows -> 5.98.0
  * kf5widgetsaddons[core]:x86-windows -> 5.98.0
  * kf5windowsystem[core]:x86-windows -> 5.98.0
  * kf5xmlgui[core]:x86-windows -> 5.98.0
  * libsnoretoast[core]:x86-windows -> 0.8.0#2
  * libwebp[core,libwebpmux,nearlossless,simd,unicode]:x86-windows -> 1.3.0
  * pkgconf[core]:x64-windows -> 1.8.0#5
  * qt5-activeqt[core]:x86-windows -> 5.15.8
  * qt5-base[core]:x86-windows -> 5.15.8#5
  * qt5-base[core]:x64-windows -> 5.15.8#5
  * qt5-declarative[core]:x86-windows -> 5.15.8
  * qt5-imageformats[core]:x86-windows -> 5.15.8#1
  * qt5-svg[core]:x86-windows -> 5.15.8
  * qt5-tools[core]:x86-windows -> 5.15.8
  * qt5-winextras[core]:x86-windows -> 5.15.8
  * vcpkg-pkgconfig-get-modules[core]:x64-windows -> 2022-02-10#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Detecting compiler hash for triplet x64-windows...
Restored 7 package(s) from C:\Users\小玉\AppData\Local\vcpkg\archives in 1.8 s. Use --debug to see more details.
Installing 1/42 atlmfc:x86-windows...
Elapsed time to handle atlmfc:x86-windows: 50.6 ms
Installing 2/42 ecm:x86-windows...
Elapsed time to handle ecm:x86-windows: 975 ms
Installing 3/42 freeglut:x86-windows...
Elapsed time to handle freeglut:x86-windows: 117 ms
Installing 4/42 jasper:x86-windows...
Elapsed time to handle jasper:x86-windows: 128 ms
Installing 5/42 pkgconf:x64-windows...
Elapsed time to handle pkgconf:x64-windows: 102 ms
Installing 6/42 vcpkg-pkgconfig-get-modules:x64-windows...
Elapsed time to handle vcpkg-pkgconfig-get-modules:x64-windows: 66.3 ms
Installing 7/42 qt5-base:x64-windows...
Building qt5-base[core]:x64-windows...
-- Figuring out qt target mkspec. Target arch x64
-- Target mkspec set to: win32-msvc
-- Host mkspec not set. Qt's own buildsystem will try to figure out the host system
-- Downloading https://download.qt.io/official_releases/qt/5.15/5.15.8/submodules/qtbase-everywhere-opensource-src-5.15.8.tar.xz;https://mirrors.ocf.berkeley.edu/qt/official_releases/qt/5.15/5.15.8/submodules/qtbase-everywhere-opensource-src-5.15.8.tar.xz -> qtbase-everywhere-opensource-src-5.15.8.tar.xz...
-- Extracting source G:/Cone/vcpkg/downloads/qtbase-everywhere-opensource-src-5.15.8.tar.xz
-- Applying patch patches/winmain_pro.patch
-- Applying patch patches/windows_prf.patch
-- Applying patch patches/qt_app.patch
-- Applying patch patches/gui_configure.patch
-- Applying patch patches/xlib.patch
-- Applying patch patches/egl.patch
-- Applying patch patches/mysql_plugin_include.patch
-- Applying patch patches/mysql-configure.patch
-- Applying patch patches/cocoa.patch
-- Applying patch patches/Qt5BasicConfig.patch
-- Applying patch patches/Qt5PluginTarget.patch
-- Applying patch patches/create_cmake.patch
-- Applying patch patches/Qt5GuiConfigExtras.patch
-- Applying patch patches/fix_angle.patch
-- Applying patch patches/mingw9.patch
-- Using source at G:/Cone/vcpkg/buildtrees/qt5-base/src/5.15.8-eca47ce012.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at G:/Cone/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Configuring x64-windows-dbg
-- Configuring x64-windows-dbg done
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Using cached win_flex_bison-2.5.25.zip.
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: G:/Cone/vcpkg/downloads/tools/jom/jom-1.1.3/jom.exe /J 7
    Working Directory: G:/Cone/vcpkg/buildtrees/qt5-base/x64-windows-dbg
    See logs for more information:
      G:\Cone\vcpkg\buildtrees\qt5-base\build-x64-windows-dbg-out.log
      G:\Cone\vcpkg\buildtrees\qt5-base\build-x64-windows-dbg-err.log

Call Stack (most recent call first):
  ports/qt5-base/cmake/install_qt.cmake:86 (vcpkg_execute_build_process)
  ports/qt5-base/portfile.cmake:383 (install_qt)
  scripts/ports.cmake:147 (include)

**Comment by RainbowTaro2022** [comment]
[build-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/11132707/build-x64-windows-dbg-out.log)
[build-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/11132708/build-x64-windows-dbg-err.log)

**Comment by autoantwort** [comment]
Please try to install vcpkg at a location without special characters in the path like `C:/vcpkg`

**Comment by MonicaLiu0311** [comment]
> I tried switching to G:/vcpkg I will give you the answer later

Is there any result?

**Comment by RainbowTaro2022** [comment]
没有

**Comment by MonicaLiu0311** [comment]
> vcpkg怎么样才能改变binary cache

Are you using the `Binary Caching` provided by vcpkg? Please describe your needs in detail.

**Comment by RainbowTaro2022** [comment]
我想把binary cache缓存换到G盘，这样C盘就不会满了

**Comment by FrankXie05** [comment]
@RainbowTaro2022 
Set the cache for vcpkg:
```
$envName = 'VCPKG_DEFAULT_BINARY_CACHE'
$envValue = 'E:\BC'
$regPath = 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment'
Set-ItemProperty -Path $regPath -Name $envName -Value $envValue
```
If you want to add this environment variable to the user environment variable, 
you can change the value of `$regPath` to `Registry:: HKEY_ CURRENT_ USER\Environment`。

Note: use administrator privileges.
`E:\BC`: Modify to the cache directory you want to set

Then: Open a new `Powershell` and enter command 
```
PS E:\vcpkg> $env:VCPKG_DEFAULT_BINARY_CACHE
E:\BC
```
Ensure successful setup

BTW: Delete the cache directory and delete the installed binary files (it is possible to go back and find the previous cache location).

Last: run command `vcpkg install <port_name>`:
```
The following packages will be built and installed:
    abseil[core]:x86-windows -> 20230125.0#1
Detecting compiler hash for triplet x86-windows...
Restored 0 package(s) from E:\BC in 261 us. Use --debug to see more details.
Installing 1/1 abseil:x86-windows...
Building abseil[core]:x86-windows...
```
Display priority read and create cache in directory `E:\BC`
```
Restored 0 package(s) from E:\BC in 261 us. Use --debug to see more details.
```
![image](https://user-images.githubusercontent.com/65999885/231685936-6aba6de4-b776-4c79-ab5c-044570eaabd7.png)

**Comment by RainbowTaro2022** [comment]
难道我要改什么吗？

**Comment by FrankXie05** [comment]
```
c1xx: fatal error C1083: 无法打开编译器中间文件: “C:\Users\e???¿¬®©\AppData\Local\Temp\_CL_1f0eadacex”: Invalid argument
```
Please standardize the path to recognizable ASCII characters.

**Comment by RainbowTaro2022** [comment]
我更改了环境变量，现在应该可以了

**Comment by RainbowTaro2022** [comment]
[build-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/11234424/build-x64-windows-dbg-out.log)
[build-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/11234425/build-x64-windows-dbg-err.log)
为什么我改了还是这样啊

**Comment by RainbowTaro2022** [comment]
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/11234498/install-x86-windows-dbg-out.log)

还有boost的regex

**Comment by MonicaLiu0311** [comment]
> c1xx: fatal error C1083: 无法打开编译器中间文件: “C:\Users\e???¿¬®©\AppData\Local\Temp\_CL_1f0eadacex”: Invalid argument

Please tell me what is the name of `e???¿¬®©` in your path?

**Comment by FrankXie05** [comment]
```
Error: cannot open C:\Users\e???¨ª©¸\AppData\Local\Temp\qlatincodec.obj.7120.718.jom for write
```

**Comment by dg0yt** [comment]
IIRC `jom` also wants Western encodings for the TEMP dir filepath... and Qt5 relies on `jom` for windows.

**Comment by RainbowTaro2022** [comment]
我不知道怎么解决

**Comment by MonicaLiu0311** [comment]
> > c1xx: fatal error C1083: 无法打开编译器中间文件: “C:\Users\e???¿¬®©\AppData\Local\Temp_CL_1f0eadacex”: Invalid argument
> 
> Please tell me what is the name of `e???¿¬®©` in your path?

Please answer my question, what is this string of unrecognized gibberish?

**Comment by MonicaLiu0311** [comment]
> IIRC jom also wants Western encodings for the TEMP dir filepath... and Qt5 relies on jom for windows.

@dg0yt Do you mean the system's "default charset encoding"? The one set through the regional options in the control panel?

**Comment by RainbowTaro2022** [comment]
> 是用户的名字，我改成了LuLujiang

**Comment by MonicaLiu0311** [comment]
> 是用户的名字，我改成了LuLujiang

Please restart the computer, check the relevant path settings, and re-clone vcpkg and try again.

**Comment by MonicaLiu0311** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by biggiantpigeon** [comment]
I have the same issue, but I installed vcpkg in E:\. Dunno why.
