### ISSUE TITLE
Failing to find PhysX in my CMake project, even after workarounds.

### ISSUE THREAD

**Issue by dantamont** [microsoft/vcpkg#30629]
Some ports seem to be working for me just fine, and have usage documentation, like SDL2. Others, not so much, like PhysX.

I'm using MSVC with Visual Studio. Currently, I have PhysX  getting downloaded and built just fine through vcpkg. I have also successfully integrated the vcpkg toolchain in my `CMakePresets.json` (at least, I think I have):

```
	"CMAKE_TOOLCHAIN_FILE": {
	  "type": "PATH",
	  "value": "${sourceDir}/tools/extern/vcpkg/_deps/scripts/buildsystems/vcpkg.cmake"
	},
	
	...
	//Automatically copy dependencies into the output directory for
	// executables.
	VCPKG_APPLOCAL_DEPS:BOOL=ON
	
	//The directory which contains the installed libraries for each
	// triplet
	VCPKG_INSTALLED_DIR:PATH=C:/Users/.../tools/extern/vcpkg/_deps/installed
	
	//The path to the vcpkg manifest directory.
	VCPKG_MANIFEST_DIR:PATH=
	
	//Use manifest mode, as opposed to classic mode.
	VCPKG_MANIFEST_MODE:BOOL=OFF
	
	//Appends the vcpkg paths to CMAKE_PREFIX_PATH, CMAKE_LIBRARY_PATH
	// and CMAKE_FIND_ROOT_PATH so that vcpkg libraries/packages are
	// found after toolchain/system libraries/packages.
	VCPKG_PREFER_SYSTEM_LIBS:BOOL=OFF
	
	//Enable the setup of CMAKE_PROGRAM_PATH to vcpkg paths
	VCPKG_SETUP_CMAKE_PROGRAM_PATH:BOOL=ON
	
	//Vcpkg target triplet (ex. x86-windows)
	VCPKG_TARGET_TRIPLET:STRING=x64-windows
	
	//Trace calls to find_package()
	VCPKG_TRACE_FIND_PACKAGE:BOOL=OFF
	
	//Enables messages from the VCPKG toolchain for debugging purposes.
	VCPKG_VERBOSE:BOOL=OFF
```

To verify that vcpkg is being used to find packages, my `CMakeCache.txt` contains the following:

```
CMAKE_TOOLCHAIN_FILE:PATH=C:/Users/.../tools/extern/vcpkg/_deps/scripts/buildsystems/vcpkg.cmake
...

```

However, the following does not work for me:

```
find_package(PhysX REQUIRED)
```

I get the following error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at tools/extern/vcpkg/_deps/scripts/buildsystems/vcpkg.cmake:846 (_find_package):
  By not providing "FindPhysX.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "PhysX", but
  CMake did not find one.

  Could not find a package configuration file provided by "PhysX" with any of
  the following names:

    PhysXConfig.cmake
    physx-config.cmake

  Add the installation prefix of "PhysX" to CMAKE_PREFIX_PATH or set
  "PhysX_DIR" to a directory containing one of the above files.  If "PhysX"
  provides a separate development package or SDK, be sure it has been
  installed.		C:\Users\...\tools/extern/vcpkg/_deps/scripts/buildsystems/vcpkg.cmake	846	
```

I also tried with the package name `Physx_64`, since I'm building for 64-bit windows and that is the name of the library under the vcpkg install path, but that didn't work either.

**Comment by dantamont** [comment]
So, I did find a helpful thread on this topic](https://stackoverflow.com/questions/66956713/finding-vcpkg-packages-that-dont-have-find-package-documentation). Not ideal, but it is helpful to know that I can't just assume that `find_package` will work out of the box with all ports. My `CMakeLists.txt` now contains the following:

# Check if 64-bit build
set(BUILD_64 CMAKE_SIZEOF_VOID_P EQUAL 8 CACHE INTERNAL "")
if(${BUILD_64})
    set(PHYSX_NAME_SUFFIX "_64")
else()
    set(PHYSX_NAME_SUFFIX "")
endif()

find_path(PHYSX_INCLUDE_DIR "PxPhysicsAPI.h" REQUIRED)
find_library(PHYSX_LIBRARY_PATH "PhysX${PHYSX_NAME_SUFFIX}" REQUIRED)

message(STATUS "Physx include dir: ${PHYSX_INCLUDE_DIR}")
message(STATUS "Physx library: ${PHYSX_LIBRARY_PATH}")

set(PHYSX_TARGET_LIBRARIES
    "PhysX${PHYSX_NAME_SUFFIX }"
    "PhysXPvdSDK${PHYSX_NAME_SUFFIX }"
    "PhysXVehicle${PHYSX_NAME_SUFFIX }"
    "PhysXCharacterKinematic${PHYSX_NAME_SUFFIX }"
    "PhysXCooking${PHYSX_NAME_SUFFIX }"
    "PhysXCommon${PHYSX_NAME_SUFFIX }"
    "PhysXFoundation${PHYSX_NAME_SUFFIX }"
    "PhysXExtensions${PHYSX_NAME_SUFFIX }"
)

Unfortunately, I am still unable to link to PhysX. I make it all the way through my build step, and am then faced with:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'PhysX_64.lib'	C:\Users\...\builds\x64_debug\<my_project>	C:\Users\...\builds\x64_debug\LINK	1	
```

**Comment by dpogue** [comment]
@dantamont If it's helpful as a reference, https://github.com/H-uru/Plasma/blob/master/cmake/FindPhysX.cmake is known to work with both vcpkg PhysX and manually-built PhysX libraries (on Windows, Linux, and macOS).

**Comment by dantamont** [comment]
Not only is this a helpful reference, it's a solution! This plugs and plays easily and perfectly. I just built with no problems.

I don't know anything about how ports are set up, but how difficult would it be to integrate this functionality into the port itself?
