### ISSUE TITLE
[assimp] CMake usage of assimp fails to copy the dll to the binary folder

### ISSUE THREAD

**Issue by Stof25** [Microsoft/vcpkg#3062]
The assimp library doesn't seem to integrate with vcpkg FindPackages judging by the fact we get no instructions on how to include the lib at install. We can use FindPackage(assimp) then target_link_libraries(MyProject PRIVATE ${ASSIMP_LIBRARIES}) to use it but the dll (or it's dependencies) isn't copied at build time though.

Edit: no, it doesn't even work much because it doesn't link the debug version of the lib in debug using those directives.

**Comment by JackBoosY** [comment]
Same with #3193.
Plz importing assimp::assimp instead of ${ASSIMP_LIBRARIES}.

**Comment by JackBoosY** [comment]
, thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.

**Comment by JackBoosY** [comment]
Hi @Stof25 , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
