### ISSUE TITLE
Proposal/feature request: option to dump cmake build log file on failure

### ISSUE THREAD

**Issue by ihnorton** [microsoft/vcpkg#30622]
As far as I can tell, there is currently no option for [verbose build logging](
https://github.com/Microsoft/vcpkg/issues/6191), which makes CI debugging quite difficult. Dumping all logs in the build tree unconditionally doesn't really sense, so I end up needing to push an extra commit to dump a specific logfile path for a failing build, waiting for build cycle time, etc. Here's a concrete example:

<details>

```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: /opt/_internal/pipx/venvs/cmake/lib/python3.10/site-packages/cmake/data/bin/cmake --build . --config Debug --target install -- -v -j3
    Working Directory: /__w/1/s/external/vcpkg/buildtrees/openssl/x64-linux-dbg
    See logs for more information:
      /__w/1/s/external/vcpkg/buildtrees/openssl/install-x64-linux-dbg-out.log
```

</details>

I'd like to see the contents of `install-x64-linux-dbg-out.log` automatically, at least on a CI system.

**Proposed solution**

I would like to add (or at least request) a vcpkg option to automatically dump cmake build log files.

It looks reasonably straightforward to dump a build log file here: https://github.com/microsoft/vcpkg/blob/69efe9cc2df0015f0bb2d37d55acde4a75c9a25b/scripts/cmake/vcpkg_execute_build_process.cmake#L120-L140

If that would be an acceptable solution, some questions:
- what should the option be called?
- are there other cmake driver files where this should be implemented?
- does vcpkg have any existing "indented print" function? ([not implemented by cmake, yet](https://gitlab.kitware.com/cmake/cmake/-/issues/19418))
  

**Describe alternatives you've considered**

Not aware of any (other than unconditional or manual dumping), would be grateful for any suggestions.

**Additional context**

n/a

**Comment by jimwang118** [comment]
Our CI provides a detailed build log, you can directly access the detailed build log through the link in the PR. For example: https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/87665/artifacts?artifactName=file%20lists%20for%20arm-uwp&api-version=7.0&%24format=zip

**Comment by ihnorton** [comment]
Hi @jimwang118, thanks -- however, I am looking for detailed cmake and compiler sub-process logs, which are currently captured into files like `install-x64-linux-dbg-out.log`, and which are identified by the log message `See logs for more information:`.

(the zip file you linked to is empty, btw. if I look at another recent arm-uwp run, the log files do not show any more detail than what I see in my own builds -- only vcpkg top-level output: https://dev.azure.com/vcpkg/public/_build/results?buildId=87657&view=logs&jobId=705ccf51-b0e6-52fa-daea-1be2c9a8756e&j=705ccf51-b0e6-52fa-daea-1be2c9a8756e&t=f57fa769-2dc7-5c67-ef93-fc457e4c0d20)

**Comment by ihnorton** [comment]
The file you linked looks like exactly what I need. If I am following correctly, the suggestion here is:
- use `vcpkg --failure-logs=<path>` option (like [this](https://github.com/microsoft/vcpkg/blob/b619a233fbf7b2c9765fb4458f3ecb05bd3166e3/scripts/azure-pipelines/test-modified-ports.ps1#L166))
- the logs will be written or moved to that target path
- then the path can be archived from CI for each run

However:  how can we set `--failure-logs` for a toolchain mode build?

**Comment by jimwang118** [comment]
You can see the running status in the CI result at the bottom of the PR, and then click on the details of the running error, and you can find the corresponding error log details in the link.
![image](https://user-images.githubusercontent.com/122244446/229699037-f271a9c0-8923-4f1d-822f-9eba59a68a77.png)
![image](https://user-images.githubusercontent.com/122244446/229699619-b95eeecf-bf84-4847-87d5-ff0c5b038f14.png)
![image](https://user-images.githubusercontent.com/122244446/229699708-7b397dde-37da-4ff7-85a9-3e6a0ffc88fd.png)
![image](https://user-images.githubusercontent.com/122244446/229699824-24c53118-76cc-4408-9f42-a7abc6d0e712.png)
![image](https://user-images.githubusercontent.com/122244446/229700673-2c2fc0e8-ed0e-4012-a4cc-90087716ecbe.png)

**Comment by ihnorton** [comment]
Yes, I understand that part, thank you very much.

My question is:
- we integrate with vcpkg using [cmake toolchain mode](https://learn.microsoft.com/en-us/vcpkg/users/buildsystems/cmake-integration)
- how can I do the equivalent of `--failure-logs` when using `-DCMAKE_TOOLCHAIN_FILE` to activate vcpkg?

**Comment by autoantwort** [comment]
`--failure-logs` is only available for the `ci` command. This is not possible with the `install` command.

**Comment by fwcd** [comment]
Perhaps the `--failure-logs` flag (copying the log files to some specific directory) could simply be added to the `install` command too? The reason I am a bit hesistant to use `vcpkg ci` is that it, according to `--help`, is an internal command and subject to change.

My current solution is to just export [the entire tree of build logs](https://github.com/fwcd/m1xxx/blob/6ce4247d932472b20ecfe1d53dd1adc5e66f487f/.github/workflows/build.yml#L108-L113), which of course is useful, but adds a few extra steps every time there is a problem. The `--failure-logs` program would e.g. make it easy to add a CI step that just dumps all of the relevant log files.

**Comment by kafeg** [comment]
Just to note a gist here, I automated print of error logging in my private vcpkg fork by adding next little part after the `z_vcpkg_prettify_command_line(pretty_command ${arg_COMMAND})` in the files `vcpkg\scripts\cmake\vcpkg_execute_build_process.cmake` and `vcpkg\scripts\cmake\vcpkg_execute_required_process.cmake`

```
        # --- Try to print error logs
        # Split the string by newline characters
        string(REGEX MATCHALL "[^\n]+" file_list ${stringified_logs})

        # Iterate over the list and print content of each file
        foreach(file IN LISTS file_list)
            string(STRIP "${file}" file_stripped)

            # Print filename
            message(STATUS "Build Failed. Content of ${file_stripped}:")

            # Read the content of the file
            file(READ ${file_stripped} file_content)

            # Print the content
            message(STATUS "${file_content}")
        endforeach()
        # ---
```

**Comment by pitrou** [comment]
Can someone please explain me how I'm supposed to read the error logs in this case:
https://github.com/ursacomputing/crossbow/actions/runs/17045279226/job/48319324336#step:7:710

Note this is:
- a `vcpkg install` command
- running from a Windows Dockerfile (therefore the build directory is presumably ephemeral)
- running on a public GitHub Actions runner image

```
-- Configuring amd64-windows-static-md-release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/vcpkg/buildtrees/boost-headers/amd64-windows-static-md-release-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\boost-headers\config-amd64-windows-static-md-release-rel-CMakeCache.txt.log
      C:\vcpkg\buildtrees\boost-headers\config-amd64-windows-static-md-release-rel-CMakeConfigureLog.yaml.log
      C:\vcpkg\buildtrees\boost-headers\config-amd64-windows-static-md-release-out.log
Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:269 (vcpkg_execute_required_process)
  installed/x64-windows/share/vcpkg-boost/boost-install.cmake:55 (vcpkg_cmake_configure)
  ports/boost-headers/portfile.cmake:12 (boost_configure_and_install)
  scripts/ports.cmake:191 (include)
error: building boost-headers:amd64-windows-static-md-release failed with: BUILD_FAILED
```

cc @jimwang118 @autoantwort
