### ISSUE TITLE
[New Port Request] Physx 5.1

### ISSUE THREAD

**Issue by dantamont** [microsoft/vcpkg#30624]
Library name: PhysX

Library description: The latest release version of the PhysX SDK, which is a physics engine used in a number of industries.

Source repository URL: https://github.com/NVIDIA-Omniverse/PhysX

Project homepage (if different from the source repository): https://nvidia-omniverse.github.io/PhysX/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
I don't know anything about how to create a port, but hopefully this should be straightforward since there already is one for Physx 4~

**Comment by dantamont** [comment]
[It'd also be neat to set it up ](https://github.com/microsoft/vcpkg/issues/30629#issuecomment-1494667539)such that `find_package` works right out of the box.

**Comment by MasterDrake** [comment]
Is there no intention to add a PhysX5 port?
Especially considering how lengthy is the posted alternative?

**Comment by autoantwort** [comment]
Feel free to add it. But if no one wants to do it issues are closed after 60 days. There is no value in having hundreds of these issues that are stale.

**Comment by MasterDrake** [comment]
> Feel free to add it. But if no one wants to do it issues are closed after 60 days. There is no value in having hundreds of these issues that are stale.

I would but I have no experience or knowledge to maintain or help if any problem comes up
So I rather not take responsibility :/

**Comment by autoantwort** [comment]
As a starting point you can copy paste an other port. If you have questions you can ask me.

**Comment by dg0yt** [comment]
There is #31506.

**Comment by MasterDrake** [comment]
> There is #31506.

Thank you, you saved me a lot of time trying to do something way above my pay grade

**Comment by marcodiiga** [comment]
FYI: https://github.com/microsoft/vcpkg/pull/31506

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This issue has been fixed in #31506, so I am closing this issue for now.
