### ISSUE TITLE
[libigl] v2.4.0 broken due to port and upstream problems

### ISSUE THREAD

**Issue by FabienPean** [microsoft/vcpkg#30621]
There are numerous issues with the newer version 2.4.0 merged in #26942, most introduced by upstream regressions. While it seemingly "compiles", v2.4.0 is botched. Upstream has been notified https://github.com/libigl/libigl/issues/2186

**To Reproduce**

`./vcpkg install libigl`

### A. Library when using vcpkg with static linkage

Detailed here #30617

### B. CMake config files are broken

1. Naming inconsistent 
![image](https://user-images.githubusercontent.com/9134757/229367148-69e46315-c00a-40e3-82ac-78334607af5d.png)
2. Main config file not including target file, i.e., missing `include(${CMAKE_CURRENT_LIST_DIR}/LibiglConfigTargets.cmake)`
3. It means the include folder of igl cannot be found on a simple test case, because it cannot find the target, making the port basically useless.

### C. Features have no effects

Upstream repository does not install the targets containing the options, only the core target, see https://github.com/search?q=repo%3Alibigl%2Flibigl%20igl_install&type=code. Moreover, installing does not include copyleft targets https://github.com/libigl/libigl/blob/a05865e2650f22057fcdc0b77c40d2458922f5d8/CMakeLists.txt#L150. So libigl[cgal] has no effects.

**Comment by FrankXie05** [comment]
Fixed by PR https://github.com/microsoft/vcpkg/pull/30617
