### ISSUE TITLE
[gettext] Build error

### ISSUE THREAD

**Issue by codeflorist** [microsoft/vcpkg#30627]
Package: gettext[core]:x64-linux -> 0.21.1

**Host Environment**

- Host: x64-linux
- Compiler: GNU 10.2.1
-    vcpkg-tool version: 2023-03-29-664f8bb619b752430368d0f30a8289b761f5caba
    vcpkg-scripts version: 69efe9cc2 2023-03-31 (2 days ago)

**To Reproduce**

`vcpkg install fluidsynth:x86-mingw-dynamic`

**Failure logs**

```
-- Downloading https://ftp.gnu.org/pub/gnu/gettext/gettext-0.21.1.tar.gz;https://www.mirrorservice.org/sites/ftp.gnu.org/gnu/gettext/gettext-0.21.1.tar.gz -> gettext-0.21.1.tar.gz...
-- Extracting source /mnt/c/dev/tools/vcpkg-wsl/downloads/gettext-0.21.1.tar.gz
-- Applying patch android.patch
-- Applying patch uwp.patch
-- Applying patch win-gethostname.patch
-- Applying patch 0003-Fix-win-unicode-paths.patch
-- Applying patch rel_path.patch
-- Using source at /mnt/c/dev/tools/vcpkg-wsl/buildtrees/gettext/src/gettext-0-de39ca5451.clean
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:617 (message):
  Could not find bison.  Please install it via your package manager:

      sudo apt-get install bison
Call Stack (most recent call first):
  ports/gettext/portfile.cmake:26 (vcpkg_find_acquire_program)
  scripts/ports.cmake:147 (include)



```

**Additional context**

**Comment by autoantwort** [comment]
I suggest reading the error message :)

**Comment by FrankXie05** [comment]
@codeflorist Please run command `sudo apt-get install bison` and try again.

**Comment by codeflorist** [comment]
thanks for your help! after installing bison (and powershell), the installation succeeded in the end, but several times a windows system error by `conftest.exe` popped up stating that code execution could not be continued due to a missing `libiconf-2.dll`. i'm using Debian WSL v1 btw.

**Comment by FrankXie05** [comment]
@codeflorist Please provide the error log.

**Comment by codeflorist** [comment]
here is a screenshot with the error (the popup is in german): https://imgur.com/a/EWkJRzL

**Comment by codeflorist** [comment]
mmkay. thanks for the downvotes, though!
