### ISSUE TITLE
[kinectsdk2] cannot find vcpkg-tool-lessmsi at 1.10#1

### ISSUE THREAD

**Issue by blueiso** [microsoft/vcpkg#30639]
**Host Environment**

- OS: x64-windows
- Compiler: vc143 studio 2022

**To Reproduce**

`./vcpkg install kinectsdk2 --triplet x64-windows`

**Failure logs**

error: no version database entry for vcpkg-tool-lessmsi at 1.10#1.
Available versions:
    1.10.0#1
    1.10.0
See `vcpkg help versioning` for more information.
note: updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.

**Additional context**

Modifying 
vcpkg\buildtrees\versioning_\versions\kinectsdk2\e703f6797d85c9d99a150e4325c67bf7f3a7ea3f\vcpkg.json
to target "version>=": "1.10.0#1" instead of "version>=": "1.10#1" fixes the issue.

**Comment by dg0yt** [comment]
> note: updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.

Did you try this already?

**Comment by blueiso** [comment]
Yes, didn't help. Also erased all my buildtrees and downloads to start from scratch.

**Comment by dg0yt** [comment]
The buildtrees dir doesn't matter. It is only the `vcpkg` tool which is responsible for resolving versions, based on your clone of the vcpkg git repo. Can you show the output of `.\vcpkg --version`?

FTR I can resolve the versions here (even on linux):
~~~
$ ./vcpkg install --dry-run kinectsdk2 --allow-unsupported
Computing installation plan...
...<unsupported on linux>...
The following packages will be built and installed:
    kinectsdk2[core]:x64-linux -> 2.0#6
  * vcpkg-tool-lessmsi[core]:x64-linux -> 1.10.0#1
Additional packages (*) will be modified to complete this operation.
$ ./vcpkg --version
vcpkg package management program version 2023-03-29-664f8bb619b752430368d0f30a8289b761f5caba

See LICENSE.txt for license information.

**Comment by blueiso** [comment]
I started from a new folder and it works.

```
vcpkg install kinectsdk2 --triplet x64-windows
Computing installation plan...
A suitable version of cmake was not found (required v3.25.1) Downloading portable cmake 3.25.1...
Downloading cmake...
https://github.com/Kitware/CMake/releases/download/v3.25.1/cmake-3.25.1-windows-i386.zip->D:\devel\vcpkg2\downloads\cmake-3.25.1-windows-i386.zip
Downloading https://github.com/Kitware/CMake/releases/download/v3.25.1/cmake-3.25.1-windows-i386.zip
Extracting cmake...
The following packages will be built and installed:
    kinectsdk2[core]:x64-windows -> 2.0#6
  * vcpkg-tool-lessmsi[core]:x64-windows -> 1.10.0#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
A suitable version of powershell-core was not found (required v7.2.8) Downloading portable powershell-core 7.2.8...
Downloading powershell-core...
```

I was using the latest git master. Not sure what was causing the unexisting version of lessmsi to be requested. I happened after an updated and the error message wasn't helping.

```
vcpkg package management program version 2023-03-29-664f8bb619b752430368d0f30a8289b761f5caba

See LICENSE.txt for license information.
```

**Comment by blueiso** [comment]
Ok, managed to reproduce it using the following manifest. And calling

`vcpkg.exe install --triplet=x64-windows`

`{
  "name": "project",
  "version": "1.1.1",
  "description": "A utility...",
  "dependencies": [
    {
      "name": "vtk",
      "features": [
        "qt",
        "opengl"
      ]
    },
    {
      "name": "pcl",
      "features": [
        "qt",
        "opengl",
        "visualization",
        "vtk"
      ]
    },
    "kinectsdk2",
    "boost-log",
    "nlohmann-json"
  ],
  "builtin-baseline": "19af97cba8ca48474e4ad15a24ed50271a9ecdac"
}
`

**Comment by dg0yt** [comment]
The error is reproducible in manifest mode. Thanks :+1:

**Comment by Neumann-A** [comment]
Is this now a tool bug or a port bug is the question?

**Comment by dg0yt** [comment]
At least the specific issue could be quickly fixed in port kinectsdk2.
There is a tool issue in any case: It must either learn to deal with this input in manifest mode, or it must complain when running the `ci` command.

**Comment by PhoebeHui** [comment]
@blueiso, thanks for reporting this issue! this should be a vcpkg bug.

**Comment by jimwang118** [comment]
Not stale

**Comment by jimwang118** [comment]
This issue has been fixed by PR https://github.com/microsoft/vcpkg/pull/33948.
