### ISSUE TITLE
[openssl] build failure

### ISSUE THREAD

**Issue by khayk** [microsoft/vcpkg#30645]
Package: openssl[core]:x64-windows -> 3.1.0#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.35.32216.1
-    vcpkg-tool version: 2023-03-29-664f8bb619b752430368d0f30a8289b761f5caba
    vcpkg-scripts version: b619a233f 2023-04-03 (6 hours ago)

**To Reproduce**

`./vcpkg.exe install openssl:x64-windows`

**Failure logs**

```
-- Using cached openssl-openssl-openssl-3.1.0.tar.gz.
-- Cleaning sources at C:/Code/repo/github/microsoft/vcpkg/buildtrees/openssl/src/nssl-3.1.0-1ebd9e680e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Code/repo/github/microsoft/vcpkg/downloads/openssl-openssl-openssl-3.1.0.tar.gz
-- Applying patch disable-apps.patch
-- Applying patch disable-install-docs.patch
-- Applying patch script-prefix.patch
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch unix/android-cc.patch
-- Applying patch unix/move-openssldir.patch
-- Applying patch unix/no-empty-dirs.patch
-- Applying patch unix/no-static-libs-for-shared.patch
-- Using source at C:/Code/repo/github/microsoft/vcpkg/buildtrees/openssl/src/nssl-3.1.0-1ebd9e680e.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Getting CMake variables for x64-windows
-- Downloading https://download.qt.io/official_releases/jom/jom_1_1_3.zip;https://mirrors.ocf.berkeley.edu/qt/official_releases/jom/jom_1_1_3.zip -> jom_1_1_3.zip...
-- Prerunning x64-windows-dbg
-- Building x64-windows-dbg
-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/nmake.exe" /NOLOGO /G /U /F makefile install_dev install_modules INSTALL_PDBS=ON
    Working Directory: C:/Code/repo/github/microsoft/vcpkg/buildtrees/openssl/x64-windows-dbg
    See logs for more information:
      C:\Code\repo\github\microsoft\vcpkg\buildtrees\openssl\install-x64-windows-dbg-nmake-out.log
      C:\Code\repo\github\microsoft\vcpkg\buildtrees\openssl\install-x64-windows-dbg-nmake-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_nmake.cmake:156 (vcpkg_execute_build_process)
  ports/openssl/windows/portfile.cmake:50 (vcpkg_build_nmake)
  ports/openssl/portfile.cmake:62 (include)
  scripts/ports.cmake:147 (include)
```

[install-x64-windows-dbg-nmake-err.log](https://github.com/microsoft/vcpkg/files/11142964/install-x64-windows-dbg-nmake-err.log)
[install-x64-windows-dbg-nmake-out.log](https://github.com/microsoft/vcpkg/files/11142966/install-x64-windows-dbg-nmake-out.log)

**Additional context**

- Operating system: Win 11, Version 22H2 (OS Build 22621.1485)
- Visual Studio 2022: 17.5.3 (Did clean installation)
- Windows 11 SDK (10.0.22000.0). Tried also (10.0.22621.0), and the same thing happened.
- Tried to apply almost every suggested solution for  `openssl` issues on `github`, which I find relative. Nothing helped. Still getting an error as listed above.
- Uninstalled the global `CMake` version by allowing `vcpkg` to download and use its CMake version. Ran the build on a new windows terminal. I tried with default Powersell, the latest Powersell, and from cmd.
- I have issues only with building openssl. I can successfully build, for example, `gtest`, `spdlog`, `boost`.
- Every time before execution of `vcpkg install ...`  command, I have deleted everything generated previously.

**Comment by dg0yt** [comment]
openssl has its own build system...
The error is with an assembler step, and the input file is generated with Perl. Maybe something is going wrong already earlier, during config or in jom-driven install steps. This would be logged in other files.

**Comment by khayk** [comment]
Please, let me know what additional information I can provide to be able to figure out what is the real cause of this issue.

**Comment by dg0yt** [comment]
As I said, there are other log files (next to the mentioned log): config, build (jom).
(Where do I see which Perl is used? :thinking:)

**Comment by khayk** [comment]
Please find the requested log files below.

[install-x64-windows-dbg-jom-err.log](https://github.com/microsoft/vcpkg/files/11156508/install-x64-windows-dbg-jom-err.log)
[install-x64-windows-dbg-jom-out.log](https://github.com/microsoft/vcpkg/files/11156510/install-x64-windows-dbg-jom-out.log)

**Comment by khayk** [comment]
[prerun-specific-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/11186499/prerun-specific-x64-windows-dbg-out.log)

**Comment by khayk** [comment]
[cmake-get-vars-x64-windows-rel.cmake.log](https://github.com/microsoft/vcpkg/files/11186508/cmake-get-vars-x64-windows-rel.cmake.log)
[cmake-get-vars-x64-windows-dbg.cmake.log](https://github.com/microsoft/vcpkg/files/11186509/cmake-get-vars-x64-windows-dbg.cmake.log)
[cmake-vars-x64-windows-dbg.cmake.log](https://github.com/microsoft/vcpkg/files/11186511/cmake-vars-x64-windows-dbg.cmake.log)
[cmake-vars-x64-windows-rel.cmake.log](https://github.com/microsoft/vcpkg/files/11186512/cmake-vars-x64-windows-rel.cmake.log)

[files-list.txt](https://github.com/microsoft/vcpkg/files/11186522/files-list.txt)

I have attached all the files which are non empty and are related to config or build (jom).
Also attached a file containing list of all files under the buildtree for openssl. Let me know please if you need any file from that list.

**Comment by dg0yt** [comment]
`prerun` is the config step for the openssl name build.
- The build targets `VC-WIN64A` :heavy_check_mark: 
- The build uses vcpkg's `downloads\tools\perl\5.32.1.1\perl\bin\perl.exe` :heavy_check_mark:
- The build uses vcpkg's `downloads\tools\nasm\nasm-2.16.01\nasm.exe` :heavy_check_mark:

What is going on here?

The error log has
~~~
Use of uninitialized value in join or string at C:/Code/repo/github/microsoft/vcpkg/downloads/tools/perl/5.32.1.1/perl/lib/re.pm line 45.
...
crypto\aes\aes-x86_64.asm:1: error: parser: instruction expected
crypto\aes\aes-x86_64.asm:5: error: parser: instruction expected
...
~~~
The warnings from perl are unexpected,  and the asm file is bad already on the first line...
Did you already try to get rid of perl assets in `downloads`?

But with the error message, I also found this:
https://github.com/microsoft/msquic/issues/3425
https://github.com/microsoft/msquic/issues/3425#issuecomment-1455198709 points at the `TERM` environment variable.

**Comment by khayk** [comment]
I tried building from scratch with `TERM=dumb` or `TERM=windows` environment variables defined in the sys env vars.
In both cases the warning "Use of uninitialized value in join ..." is there and the build is failing.
The errors is pretty much the same, only on the other file, I guess it is because of parralel build. New log files are attached.

[install-x64-windows-dbg-jom-err.log](https://github.com/microsoft/vcpkg/files/11193688/install-x64-windows-dbg-jom-err.log)
[install-x64-windows-dbg-jom-out.log](https://github.com/microsoft/vcpkg/files/11193689/install-x64-windows-dbg-jom-out.log)
[install-x64-windows-dbg-nmake-err.log](https://github.com/microsoft/vcpkg/files/11193690/install-x64-windows-dbg-nmake-err.log)
[install-x64-windows-dbg-nmake-out.log](https://github.com/microsoft/vcpkg/files/11193691/install-x64-windows-dbg-nmake-out.log)

I had another PC, which is running the same Windows 11 version as the one where I have a build error, the only difference is that on the other machine I have VS 2019 installed instead of VS2022.
On the machine with VS 2019 the build of openssl is successful, so the difference is the version of VS.
It is interesting, have you tried to build openssl with VS2022 on Win11?

**Comment by LilyWangLL** [comment]
Did you install any Firewall or anti-virus software on your machine? The installation of `OpenSSL` is often interfered with by antivirus software. You can also check if your computer has set to use Unicode UTH-8, as issue https://github.com/microsoft/vcpkg/issues/27267 was able to successfully install it using this solution https://stackoverflow.com/questions/56419639/what-does-beta-use-unicode-utf-8-for-worldwide-language-support-actually-do.

**Comment by CatalinSerafimescu** [comment]
@LilyWangLL , @khayk
I used to build openssl with VS2019 successfully, too (previous version). I can replicate the problem with VS2022, on 2 machines, the original one, and a newly installed one (both Windows 11, VS2022). I also tried the UTF-8 setting, no luck, Antivirus is BitDefender on old machine and WithSecure (new machine), none of them complains of anything. I can't go back to VS2019, but it might worth trying

**Comment by CatalinSerafimescu** [comment]
I did a test: on a new VM, installed VS2019, build was successful. Uninstalled openssl and VS2019, installed VS2022, build was successful
Tried again on regular PC, it still fails.

**Comment by CatalinSerafimescu** [comment]
I see there's no progress on this, is anybody investigating?

**Comment by dg0yt** [comment]
Given the error message, the next step is to look at the _broken_ `crypto\aes\aes-x86_64.asm` or similar, but I don't have it.

**Comment by CatalinSerafimescu** [comment]
> Given the error message, the next step is to look at the _broken_ `crypto\aes\aes-x86_64.asm` or similar, but I don't have it.

Here it is
[aes-x86_64.asm.txt](https://github.com/microsoft/vcpkg/files/12060342/aes-x86_64.asm.txt)

**Comment by dg0yt** [comment]
... the code seems to look for `ENV{ASM}` instead ...

**Comment by dg0yt** [comment]
Does #32957 help?

**Comment by khayk** [comment]
@dg0yt, WOW, that perfectly fixes an error. Confirming that the build is now successful (checked on your fork, openssl branch),
Thank you so much !!!

**Comment by mfellows** [comment]
@dg0yt I hate to clutter the comments, but couldn't not thank you for this - solved my intermittent build problem! You're the best! How weird that it would eventually generate the correct asm with enough retries though; anyway, it works every time now.
