### ISSUE TITLE
[pybind11:x64-windows] debug link failure

### ISSUE THREAD

**Issue by jimellert** [microsoft/vcpkg#30642]
**Host Environment**
- OS:  Windows10
- Compiler:   Microsoft Visual Studio Community 2022 (64-bit) - Current,   Version 17.5.3

**To Reproduce**
CMakeLists.txt file vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
cmake_minimum_required (VERSION 3.16)
project (firestoreTest)

set (CMAKE_CXX_STANDARD 11)
set (CMAKE_CXX_STANDARD_REQUIRED True)
set (CMAKE_TOOLCHAIN_FILE c:/projects/github/microsoft/vcpkg/scripts/buildsystems/vcpkg.cmake)

find_package (pybind11 REQUIRED)

add_executable (firestoreTest
	"firestoreTest.cpp" "firestoreTest.h"
	"pythonTest.cpp" "pythonTest.h"
	"main.cpp"
)

target_link_libraries (firestoreTest
	PRIVATE pybind11::embed
)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Steps to reproduce the behavior**
vcpkg install pybind11:x64-windows
Build with above CMakeLists.txt.
Reported error:   vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
>------ Build All started: Project: firestoreTest, Configuration: x64-Debug ------
  [1/1] Linking CXX executable firestoreTest.exe
  FAILED: firestoreTest.exe 
  cmd.exe /C "cd . && "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\firestoreTest.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\10.0.19041.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\10.0.19041.0\x64\mt.exe --manifests  -- "C:\PROGRA~1\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64\link.exe" /nologo CMakeFiles\firestoreTest.dir\firestoreTest.cpp.obj CMakeFiles\firestoreTest.dir\pythonTest.cpp.obj CMakeFiles\firestoreTest.dir\main.cpp.obj  /out:firestoreTest.exe /implib:firestoreTest.lib /pdb:firestoreTest.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console  C:\Projects\github\microsoft\vcpkg\installed\x64-windows\debug\lib\python310_d.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cmd.exe /C "cd /D "C:\Projects\trials\28.2 - Firestore test\firestoreTest\out\build\x64-debug" && C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noprofile -executionpolicy Bypass -file C:/Projects/github/microsoft/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary "C:/Projects/trials/28.2 - Firestore test/firestoreTest/out/build/x64-debug/firestoreTest.exe" -installedDir C:/Projects/github/microsoft/vcpkg/installed/x64-windows/debug/bin -OutVariable out""
  LINK Pass 1: command "C:\PROGRA~1\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64\link.exe /nologo CMakeFiles\firestoreTest.dir\firestoreTest.cpp.obj CMakeFiles\firestoreTest.dir\pythonTest.cpp.obj CMakeFiles\firestoreTest.dir\main.cpp.obj /out:firestoreTest.exe /implib:firestoreTest.lib /pdb:firestoreTest.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console C:\Projects\github\microsoft\vcpkg\installed\x64-windows\debug\lib\python310_d.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\firestoreTest.dir/intermediate.manifest CMakeFiles\firestoreTest.dir/manifest.res" failed (exit code 1104) with the following output:
C:\Projects\trials\28.2 - Firestore test\firestoreTest\out\build\x64-Debug\LINK : fatal error LNK1104: cannot open file 'python310.lib'
  ninja: build stopped: subcommand failed.
Build All failed.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

- Apparently pybind11 finds dependent libraries on it's own, insisting on using the release version of python310.lib/dll.  But cmake insists on a particular use of debug/release directories.  Thus when the project is building a debug version, only python310_d.lib/dll will be managed and found.
- If I provide CMakeLists.txt the path to the python310.lib, it will link, but execution of the program will not find the python310.dll (because python310_d.dll has been copied to my executable directory).
- I'm not savy enough with ports to fix this.
- In my mind, pybind11 should not force the release version of python.    vcpkg install pybind11:x64-windows should work with a debug or release build.

**Comment by Osyotr** [comment]
I think you should manually define `Py_DEBUG` to force pybind11 to use debug build of python. See https://github.com/pybind/pybind11/pull/2025

**Comment by jimellert** [comment]
Sounds like a good plan.   I changed my CMakeLists.txt as follows:
```
cmake_minimum_required (VERSION 3.16)
project (firestoreTest)

set (CMAKE_CXX_STANDARD 11)
set (CMAKE_CXX_STANDARD_REQUIRED True)
set (CMAKE_TOOLCHAIN_FILE c:/projects/github/microsoft/vcpkg/scripts/buildsystems/vcpkg.cmake)
set (Py_DEBUG ON)

find_package (Python3 COMPONENTS Interpreter Development REQUIRED)
find_package (pybind11 REQUIRED)

add_executable (firestoreTest
	firestoreTest.cpp firestoreTest.h
	pythonTest.cpp pythonTest.h
	main.cpp
)

target_link_libraries (firestoreTest
	PUBLIC Python3::Python
	PUBLIC pybind11::embed
)
```

Unfortunately I get the same link error:
    C:\Projects\trials\28.2 - Firestore test\firestoreTest\out\build\x64-Debug\LINK : fatal error LNK1104: cannot open file 'python310.lib'

Have I not defined Py_DEBUG correctly?

**Comment by Osyotr** [comment]
Add it as define via `target_compile_definitions`, not as a cmake variable.

**Comment by Osyotr** [comment]
Also `CMAKE_TOOLCHAIN_FILE` should be set before `project()` call

**Comment by jimellert** [comment]
That did it!  I can now compile with Visual Studio 2022 on Windows10 and Ubuntu 20.04 LTS.  To install I used:
Windows:   vcpkg install pybind11:x64-windows
Ubuntu:      vcpkg install pybind11:x64-linux
My final CMakeLists.txt:
'''
# Top level CMakeList.txt
# See:   https://pybind11.readthedocs.io/en/stable/cmake/index.html
# Notes about compiling pybind11.
# https://pybind11.readthedocs.io/en/stable/compiling.html

cmake_minimum_required (VERSION 3.16)
set (CMAKE_CXX_STANDARD 11)
set (CMAKE_CXX_STANDARD_REQUIRED True)

if (WIN32)
	set (CMAKE_TOOLCHAIN_FILE c:/projects/github/microsoft/vcpkg/scripts/buildsystems/vcpkg.cmake)
endif()

project (firestoreTest)

find_package (Python3 COMPONENTS Interpreter Development REQUIRED)
find_package (pybind11 REQUIRED)

add_executable (firestoreTest
	firestoreTest.cpp firestoreTest.h
	pythonTest.cpp pythonTest.h
	main.cpp
)

target_compile_definitions (firestoreTest
	PRIVATE Py_DEBUG
)

target_include_directories (firestoreTest
	PUBLIC ${PYTHON_INCLUDE_DIR}
	PUBLIC ${pybind11_INCLUDE_DIR}
)

target_link_libraries (firestoreTest
	PUBLIC Python3::Python
	PUBLIC pybind11::embed
)
'''

Thank you very much for your help.  -Jim

**Comment by JonLiu1993** [comment]
@jimellert, Could you please provide the .cpp and .h files that reproduce your problem? I need to confirm locally if this issue is resolved.

**Comment by jimellert** [comment]
Latest zip file posted.

Jim

**Comment by JonLiu1993** [comment]
@jimellert, Thank you for the example you provided. I tried to reproduce your error locally yesterday, and submitted a PR to solve this bug. You can test whether your problem is solved locally. I tried it successfully locally.
