### ISSUE TITLE
[libvpx] Build error

### ISSUE THREAD

**Issue by ArtisWorld** [microsoft/vcpkg#30640]
**Host Environment**
[x86_64-pc-windows-msvc (windows-2019)](https://github.com/ArtisWorld/rustdesk/actions/runs/4597075088/jobs/8119318756#logs)

error: building libvpx:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libvpx
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libvpx]+Build+error
Include '[libvpx] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: 14e7bb4ae 2022-05-10 (11 months ago)
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**

`./vcpkg install xxxx`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by MonicaLiu0311** [comment]
Related to #30546, but it has been merged, please update to the latest vcpkg.
