### ISSUE TITLE
why can not build gdal:x64-windows now?

### ISSUE THREAD

**Issue by how0723** [Microsoft/vcpkg#3065]
why can not build gdal:x64-windows now? last month , i can build gdal ,but now why can not build.
my evn is win10 64bit pro

**Comment by MikeGitb** [comment]
I few more details (like the error message) might be helpful.

**Comment by ras0219-msft** [comment]
Thanks for reporting! This looks like a duplicate of #3046.

This was due to breaking changes in the new version of `libmysql` -- I've pushed a fix to master.
