### ISSUE TITLE
[New Port Request] vala

### ISSUE THREAD

**Issue by RainbowTaro2022** [microsoft/vcpkg#30662]
Library name:vala

Library description:

Source repository URL:https://gitlab.gnome.org/GNOME/vala

Project homepage (if different from the source repository):https://gitlab.gnome.org/GNOME

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by autoantwort** [comment]
Why this should be in vcpkg?

**Comment by autoantwort** [comment]
But is gnome a library?

**Comment by RainbowTaro2022** [comment]
vala没加吗？

**Comment by RainbowTaro2022** [comment]
Vala is a programming language
你明白了吗？

**Comment by autoantwort** [comment]
Yes I understand this. And because of that I don't understand why it should be added to vcpkg. vcpkg is a package manager for c++ libraries and vala is not a c++ library.

**Comment by autoantwort** [comment]
I don't know, you'll have to ask the Vala people.

**Comment by jiayuehua** [comment]
please close all your new port request that not about C and C++lib, @RainbowTaro2022
