### ISSUE TITLE
[opentelemetry-cpp] otlp-http feature downloads not required gRPC dependency

### ISSUE THREAD

**Issue by jacogasp** [microsoft/vcpkg#30678]
****

**Is your feature request related to a problem? Please describe.**

The [CMakeLists.txt](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/exporters/otlp/CMakeLists.txt) file from `opentelemetry-cpp` offers two options for OTLP: `WITH_OTLP_GRPC` and `WITH_OTLP_HTTP`, while this port offers two features: `otlp` and `otlp-http`, as shown at [#29483](https://github.com/microsoft/vcpkg/pull/29483).
To be able to compile the `otlp-http` version, also the generic `otlp` is required, and as shown in the [vcpkg.json](https://github.com/microsoft/vcpkg/blob/19af97cba8ca48474e4ad15a24ed50271a9ecdac/ports/opentelemetry-cpp/vcpkg.json#L41), gRPC is a dependency.

This, of course, forces gRPC to be compiled, which takes a very long time to build (+40 min on a quad core machine), wasting a lot of resources for nothing, since the library is not used.

Looking at the `opentelemetry-cpp`'s [CMakeLists.txt#L29](https://github.com/open-telemetry/opentelemetry-cpp/blob/9bcfcb99ffb7e03f9f8d502ccc3c7991bc35fcef/exporters/otlp/CMakeLists.txt#L29), gRPC is required with `OTLP_WITH_GRPC` only, and not with `OTLP_WITH_HTTP`.

**Proposed solution**
Make a clear distinction between the two options, hypothetically having two vcpkg features called `otlp-grpc` and `otlp-http`, avoiding to download and build unused dependencies.

@ThomsonTan

**Comment by ThomsonTan** [comment]
@jacogasp thanks for the reporting. Just want to to check if have verified the attached PR. Seems I cannot get the otlp-http feature installed now while updating opentelemetry-cpp to v1.9.0.

**Comment by jacogasp** [comment]
Hey @ThomsonTan, sorry for the late response. 

Just tried right now with the last available commit/baseline which downloads and builds opentelemetry-cpp v1.8.3 and it works perfectly with the new fix.

Here my `vcpkg.json`:

```
{
  "name": "otel-http-test",
  "version": "0.1.0",
  "builtin-baseline": "2b1757dd1d5ed7d9d5bb65fd8316631b157e7afc",
  "dependencies": [
    "crow",
    {
      "name": "opentelemetry-cpp",
      "features": [
        "otlp-http",
        "otlp"
      ]
    }
  ]
}
```

Let me know if you wish I do more tests.
