### ISSUE TITLE
[qtdeclarative]+Build+error

### ISSUE THREAD

**Issue by Talaqalotaibipmp** [microsoft/vcpkg#30670]
**Host Environment**

- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**

`./vcpkg install xxxx`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Neumann-A** [comment]
duplicate: see https://github.com/microsoft/vcpkg/issues/30446#issuecomment-1484247259

**Comment by JonLiu1993** [comment]
@Talaqalotaibipmp, Thanks for posting this issue, could you please provide the full failure logs?

**Comment by JonLiu1993** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
