### ISSUE TITLE
[harfbuzz] Build error

### ISSUE THREAD

**Issue by mlevis** [microsoft/vcpkg#30697]
**Host Environment**

- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**

`./vcpkg install  harfbuzz:x86-windows-static`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

D:\vcpkg\5962cf\vcpkg>vcpkg install harfbuzz:x86-windows-static
Computing installation plan...
The following packages will be built and installed:
    harfbuzz[core]:x86-windows-static -> 3.2.0#1
Detecting compiler hash for triplet x86-windows-static...
Restored 0 packages from C:\Users\MarkLevis\AppData\Local\vcpkg\archives in 225.1 us. Use --debug to see more details.
Starting package 1/1: harfbuzz:x86-windows-static
Building package harfbuzz[core]:x86-windows-static...
-- Using community triplet x86-windows-static. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: D:\vcpkg\5962cf\vcpkg\triplets\community\x86-windows-static.cmake
-- Using cached harfbuzz-harfbuzz-3.2.0.tar.gz.
-- Cleaning sources at D:/vcpkg/5962cf/vcpkg/buildtrees/harfbuzz/src/3.2.0-8c7a14e743.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/5962cf/vcpkg/downloads/harfbuzz-harfbuzz-3.2.0.tar.gz
-- Applying patch 0001-circumvent-samefile-error.patch
-- Applying patch 0002-fix-uwp-build.patch
-- Using source at D:/vcpkg/5962cf/vcpkg/buildtrees/harfbuzz/src/3.2.0-8c7a14e743.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x86-windows-static
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at D:/vcpkg/5962cf/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Configuring x86-windows-static-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: D:/vcpkg/5962cf/vcpkg/downloads/tools/python/python-3.10.1-x86/python.exe D:/vcpkg/5962cf/vcpkg/installed/x64-windows/tools/meson/meson.py -Dicu=disabled -Dgraphite=disabled -Dcoretext=disabled -Dglib=disabled -Dgobject=disabled -Dfreetype=enabled -Dcairo=disabled -Dintrospection=disabled -Ddocs=disabled -Dtests=disabled -Dbenchmark=disabled --buildtype plain --backend ninja --wrap-mode nodownload --native D:/vcpkg/5962cf/vcpkg/buildtrees/harfbuzz/meson-native-x86-windows-static.log --default-library static --libdir lib --native D:/vcpkg/5962cf/vcpkg/buildtrees/harfbuzz/meson-native-x86-windows-static-debug.log -Ddebug=true --prefix D:/vcpkg/5962cf/vcpkg/packages/harfbuzz_x86-windows-static/debug --includedir ../include -Dcmake_prefix_path=['D:/vcpkg/5962cf/vcpkg/installed/x86-windows-static/debug','D:/vcpkg/5962cf/vcpkg/installed/x86-windows-static','D:/vcpkg/5962cf/vcpkg/installed/x86-windows-static/share'] D:/vcpkg/5962cf/vcpkg/buildtrees/harfbuzz/src/3.2.0-8c7a14e743.clean
    Working Directory: D:/vcpkg/5962cf/vcpkg/buildtrees/harfbuzz/x86-windows-static-dbg
    Error code: 2
    See logs for more information:
      D:\vcpkg\5962cf\vcpkg\buildtrees\harfbuzz\config-x86-windows-static-dbg-out.log
      D:\vcpkg\5962cf\vcpkg\buildtrees\harfbuzz\config-x86-windows-static-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:492 (vcpkg_execute_required_process)
  ports/harfbuzz/portfile.cmake:48 (vcpkg_configure_meson)
  scripts/ports.cmake:145 (include)

Error: Building package harfbuzz:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+harfbuzz
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[harfbuzz]+Build+error
including:
  package: harfbuzz[core]:x86-windows-static -> 3.2.0#1
    vcpkg-tool version: 2022-02-24-7efe7f2b04912a7d674f86a406f9f2711c0221c6
    vcpkg-scripts version: 5962cf5a3 2022-03-07 (1 year, 1 month ago)

Additionally, attach any relevant sections from the log files above.

D:\vcpkg\5962cf\vcpkg>

**Additional context**
[config-x86-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/11171381/config-x86-windows-dbg-err.log)
[config-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/11171382/config-x86-windows-dbg-out.log)

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by dg0yt** [comment]
> harfbuzz[core]:x86-windows-static -> 3.2.0#1 
> vcpkg-tool version: 2022-02-24-7efe7f2b04912a7d674f86a406f9f2711c0221c6 
> vcpkg-scripts version: [5962cf5](https://github.com/microsoft/vcpkg/commit/5962cf5a3bfc2124e8de991a4e45a8edcb3b4c69) 2022-03-07 (1 year, 1 month ago)

You must update vcpkg.

**Comment by Cheney-W** [comment]
Thanks for dg0yt's suggestion.
