### ISSUE TITLE
vcpkg.json: Dependency is installed with full features instead of only required ones

### ISSUE THREAD

**Issue by patrikhuber** [microsoft/vcpkg#30695]
**Describe the bug**
My `vcpkg.json` looks like this:

```
{
  "name": "mylib",
  "version": "1.0.0",
  "dependencies": [
    "boost-filesystem",
    "boost-program-options",
    { "name": "opencv4", "features": ["jpeg", "png"] }
  ]
}
```

I then do "Open => CMake" in VS 2022, click my CMakeLists. And vcpkg goes ahead installing OpenCV4 with *all* its default features:

```
1> [CMake]     opencv4[core,default-features,dnn,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.7.0#3
```

**Environment**
- OS: Windows
- Compiler: Latest VS 2022
- vcpkg master from 20 March 2023

**To Reproduce**
See description.

**Expected behavior**
I would expect vcpkg to fetch the opencv4 dependency with only the features that I've specified that mylib depends on, i.e. I would expect it to do:

```
1> [CMake]     opencv4[core,jpeg,png]:x64-windows -> 4.7.0#3
```

With larger packages like OpenCV, this has significant implications. A lightweight OpenCV4 can be built in under minute, whereas an OpenCV build with more features can take 5 to 10 minutes and upwards.

In my view, the existing behaviour is a bug. If it is intended behaviour, then 1) can I accomplish what I want to accomplish? I believe it is an important use case. And 2) I think the docs (https://learn.microsoft.com/en-us/vcpkg/users/manifests) need updating, as this is really not clear.

Thanks!

**Comment by autoantwort** [comment]
Use
```cmake
{
  "name": "mylib",
  "version": "1.0.0",
  "dependencies": [
    "boost-filesystem",
    "boost-program-options",
    { "name": "opencv4", "features": ["jpeg", "png"], "default-features": false }
  ]
}
```

**Comment by patrikhuber** [comment]
Also I can confirm it works as intended now, after adding `"default-features": false`, and re-running cmake, vcpkg now actually removed the unnecessary packages and is rebuilding opencv4.
