### ISSUE TITLE
Have all ports generate debug libs without 'd' suffix?

### ISSUE THREAD

**Issue by AachoLoya** [microsoft/vcpkg#30700]
My project uses several vcpkg ports. Currently, each port has different suffix policy i.e. some ports have identical .lib filename in lib and debug\lib folders. Whereas others e.g. icu have 'd' suffix added to lib filename in debug\lib folder. 

I'd like to having naming consistency across the project to simplify build process and would like to have all port's lib files in debug folder without the 'd' suffix. Is it possible via vcpkg setting?

**Comment by Neumann-A** [comment]
> I'd like to having naming consistency across the project to simplify build process and would like to have all port's lib files in debug folder without the 'd' suffix. Is it possible via vcpkg setting?

upstream mandates the library name in debug builds. 
An no consistent naming is not possible. It will severely brake cmake. 
However what you could do is to have a e.g. `x64-windows-debug` triplet/toolchain combo where you simply adjust the Release flags to actually be the Debug flags. This way you get Release naming but Debug build flags. Combine this with the `x64-windows-release` triplet and you get what you want. However you can never use both at the same time.
