### ISSUE TITLE
Documentation / Example needed for find_program

### ISSUE THREAD

**Issue by mizvekov** [microsoft/vcpkg#3070]
So, currently, installing tools with vcpkg and then trying to find them with 'find_program' isn't as straightforward as on traditional unix packaging systems.

For example, installing 'glslang' package on a typical system would put wherever 'glslangValidator' is in 'PATH', and then 'find_program(glsval glslangValidator)' would work with no additional setup.

Not so with vcpkg as far as I could find out.

The examples here are all about using libraries, not tools, so that is a problem as well.

**Comment by miurahr** [comment]
It seems be not only a documentation issue but a issue on vcpkg tweaks for cmake, that is good for find_package but not enough for find_program.

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen this issue.
