### ISSUE TITLE
xalan-c package missing

### ISSUE THREAD

**Issue by Lubart** [microsoft/vcpkg#30719]
**Describe the bug**
Missing package in repository: xalan-c

**Environment**
Windows 10

Version:
PS C:\vcpkg> .\vcpkg version
vcpkg package management program version 2023-03-29-664f8bb619b752430368d0f30a8289b761f5caba

**To Reproduce**
PS C:\vcpkg> .\vcpkg.exe install xalan-c:x64-windows
Computing installation plan...
error: while looking for xalan-c:x64-windows:
error: while loading xalan-c:
error: xalan-c does not exist

**Comment by dg0yt** [comment]
Not missing in vcpkg history, but delisted on upstream request: #27401.

**Comment by Lubart** [comment]
It was used in development.  It can be marked as deprecated but be present in dictionary.

**Comment by dg0yt** [comment]
This was already proposed by community members in #27401. The vcpkg owners responded with
https://github.com/microsoft/vcpkg/pull/27401#issuecomment-1302626402
"Customers who want to still use this can pin an older version as older versions will still be present in the versions database."

**Comment by MonicaLiu0311** [comment]
> This was already proposed by community members in https://github.com/microsoft/vcpkg/pull/27401. The vcpkg owners responded with
https://github.com/microsoft/vcpkg/pull/27401#issuecomment-1302626402
"Customers who want to still use this can pin an older version as older versions will still be present in the versions database."

Thanks for @dg0yt's commet.
This issue will be closed soon, please reopen if your question is not answered satisfactorily.
