### ISSUE TITLE
[libmysql] include "udf_registration_types.h" error

### ISSUE THREAD

**Issue by jmin911** [Microsoft/vcpkg#3071]
ver 8.0.4 builds the lib, but app compile fails:
cannot find the include file udf_registration_types.h
In mysql_com.h file, line 1007, the code is
#include <mysql/udf_registration_types.h>

It should be
#include "mysql/udf_registration_types.h"

**Comment by ras0219-msft** [comment]
Thanks for posting this issue!

Which app compilation are you talking about? Could you please provide detailed repro steps?

**Comment by ras0219-msft** [comment]
Actually, I see the issue now. Thanks! A fix should be in master.

**Comment by kuskovrodion** [comment]
@ras0219-msft Hey ! Can u tell me how did u fix that problem?
