### ISSUE TITLE
luajit isn't detected correctly.

### ISSUE THREAD

**Issue by deadlocklogic** [microsoft/vcpkg#30727]
**Describe the bug**
luajit is installed but can't be detected correctly.

**Environment**
- OS: Windows 11
- Compiler: MSVC

**To Reproduce**
1. ./vcpkg install luajit
2. in `CMakeLists.txt` `find_package(luajit REQUIRED)`

**Expected behavior**
`laujit::luajit` target should be available.

**Failure logs**
```
CMake Error at C:/Users/user/OneDrive/Documents/Development/vcpkg/scripts/buildsystems/vcpkg.cmake:852 (_find_package):
  By not providing "Findluajit.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "luajit", but
  CMake did not find one.

  Could not find a package configuration file provided by "luajit" with any
  of the following names:

    luajitConfig.cmake
    luajit-config.cmake

  Add the installation prefix of "luajit" to CMAKE_PREFIX_PATH or set
  "luajit_DIR" to a directory containing one of the above files.  If "luajit"
  provides a separate development package or SDK, be sure it has been
  installed.		C:/Users/user/OneDrive/Documents/Development/vcpkg/scripts/buildsystems/vcpkg.cmake	852	

```

**Comment by FrankXie05** [comment]
The `luajit` currently provided by `vcpkg` is not export cmake configurations, but is only built using MSVC. 

https://github.com/microsoft/vcpkg/blob/217194cea7e3491c14779c763beec50b6a4575d6/ports/luajit/portfile.cmake#L45
https://luajit.org/install.html#:~:text=Copy%20luajit.exe,luaconf.h).

**Comment by FrankXie05** [comment]
You can use the function `FIND_LIBRARY`.

**Comment by FrankXie05** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
