### ISSUE TITLE
[libmysql] ver 8.0.4 link error

### ISSUE THREAD

**Issue by jmin911** [Microsoft/vcpkg#3072]
There are multiple definitions of symbols related to SSL and fails the link.

mysqlclient.lib(ssl.cpp.obj) : error LNK2005: ERR_remove_thread_state already defined in libeay32.lib(err.obj)
1>mysqlclient.lib(ssl.cpp.obj) : error LNK2005: RSA_private_decrypt already defined in libeay32.lib(rsa_crpt.obj)
1>mysqlclient.lib(ssl.cpp.obj) : error LNK2005: RSA_public_encrypt already defined in libeay32.lib(rsa_crpt.obj)
1>mysqlclient.lib(ssl.cpp.obj) : error LNK2005: RSA_size already defined in libeay32.lib(rsa_crpt.obj)
1>libeay32.lib(pem_all.obj) : error LNK2005: PEM_read_RSAPrivateKey already defined in mysqlclient.lib(ssl.cpp.obj)
1>libeay32.lib(pem_all.obj) : error LNK2005: PEM_read_RSA_PUBKEY already defined in mysqlclient.lib(ssl.cpp.obj)

**Comment by ras0219-msft** [comment]
Thanks for posting this issue! I've pushed a fix to master that causes libmysql to use our versions of libraries (which also makes the build _much_ faster :))
