### ISSUE TITLE
[openblas] armadillo build failure

### ISSUE THREAD

**Issue by baobabtree** [microsoft/vcpkg#30723]
### Operating system

Windows 10

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
C:\dev\vcpkg>git pull
C:\dev\vcpkg>bootstrap-vcpkg.bat
C:\dev\vcpkg>vcpkg upgrade --no-dry-run 

I got:
    openblas:x64-windows: BUILD_FAILED: 1.9 min
    blas:x64-windows: CASCADED_DUE_TO_MISSING_DEPENDENCIES: 2.78 ms
    lapack-reference:x64-windows: CASCADED_DUE_TO_MISSING_DEPENDENCIES: 3.13 ms
    lapack:x64-windows: CASCADED_DUE_TO_MISSING_DEPENDENCIES: 3.05 ms
    armadillo:x64-windows: CASCADED_DUE_TO_MISSING_DEPENDENCIES: 2.28 ms

C:\dev\vcpkg>vcpkg install armadillo
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
    armadillo[core]:x64-windows -> 12.0.1
  * blas[core]:x64-windows -> 2023-03-25
  * lapack[core]:x64-windows -> 2022-02-22
  * lapack-reference[blas-select,core,noblas]:x64-windows -> 3.11.0#1
  * openblas[core]:x64-windows -> 0.3.21#2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
-- Automatically setting HTTP(S)_PROXY environment variables to "127.0.0.1:1080".
Restored 0 package(s) from C:\Users\qr\AppData\Local\vcpkg\archives in 320 us. Use --debug to see more details.
Installing 1/5 openblas:x64-windows...
Building openblas[core]:x64-windows...
-- Using cached xianyi-OpenBLAS-b89fb708caa5a5a32de8f4306c4ff132e0228e9a.tar.gz.
-- Cleaning sources at C:/dev/vcpkg/buildtrees/openblas/src/32e0228e9a-ba8c0c7bab.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/xianyi-OpenBLAS-b89fb708caa5a5a32de8f4306c4ff132e0228e9a.tar.gz
-- Applying patch uwp.patch
-- Applying patch fix-space-path.patch
-- Applying patch fix-redefinition-function.patch
-- Applying patch fix-uwp-build.patch
-- Applying patch install-tools.patch
-- Using source at C:/dev/vcpkg/buildtrees/openblas/src/32e0228e9a-ba8c0c7bab.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Warning at scripts/cmake/vcpkg_execute_build_process.cmake:65 (message):
  Please ensure your system has sufficient memory.
Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/openblas/portfile.cmake:71 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: D:/CMake/bin/cmake.exe --build . --config Release --target install -- -v -j65
    Working Directory: C:/dev/vcpkg/buildtrees/openblas/x64-windows-rel
    See logs for more information:
      C:\dev\vcpkg\buildtrees\openblas\install-x64-windows-rel-out.log
      C:\dev\vcpkg\buildtrees\openblas\install-x64-windows-rel-out-1.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/openblas/portfile.cmake:71 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building openblas:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openblas
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[openblas]+Build+error&body=Copy+issue+body+from+C%3A%2Fdev%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

The logs are below:

[1/3] cmd.exe /C "cd . && D:\CMake\bin\cmake.exe -E vs_link_exe --intdir=ctest\CMakeFiles\xccblat1.dir --rc="E:\Windows Kits\10\bin\10.0.22621.0\x64\rc.exe" --mt="E:\Windows Kits\10\bin\10.0.22621.0\x64\mt.exe" --manifests  -- "D:\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64\link.exe"  ctest\CMakeFiles\xccblat1.dir\c_cblat1c.c.obj ctest\CMakeFiles\xccblat1.dir\c_cblas1.c.obj  /out:ctest\xccblat1.exe /implib:lib\Release\xccblat1.lib /pdb:ctest\xccblat1.pdb /version:0.0 /machine:x64 /nologo /DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF   /subsystem:console  lib\Release\openblas.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
FAILED: ctest/xccblat1.exe 
cmd.exe /C "cd . && D:\CMake\bin\cmake.exe -E vs_link_exe --intdir=ctest\CMakeFiles\xccblat1.dir --rc="E:\Windows Kits\10\bin\10.0.22621.0\x64\rc.exe" --mt="E:\Windows Kits\10\bin\10.0.22621.0\x64\mt.exe" --manifests  -- "D:\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64\link.exe"  ctest\CMakeFiles\xccblat1.dir\c_cblat1c.c.obj ctest\CMakeFiles\xccblat1.dir\c_cblas1.c.obj  /out:ctest\xccblat1.exe /implib:lib\Release\xccblat1.lib /pdb:ctest\xccblat1.pdb /version:0.0 /machine:x64 /nologo /DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF   /subsystem:console  lib\Release\openblas.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
LINK: command "D:\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64\link.exe ctest\CMakeFiles\xccblat1.dir\c_cblat1c.c.obj ctest\CMakeFiles\xccblat1.dir\c_cblas1.c.obj /out:ctest\xccblat1.exe /implib:lib\Release\xccblat1.lib /pdb:ctest\xccblat1.pdb /version:0.0 /machine:x64 /nologo /DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF /subsystem:console lib\Release\openblas.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:ctest\xccblat1.exe.manifest" failed (exit code 1104) with the following output:
LINK : fatal error LNK1104: cannot open file 'ctest\xccblat1.exe'

ninja: build stopped: subcommand failed.

[install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/11182256/install-x64-windows-rel-out.log)
[install-x64-windows-rel-out-1.log](https://github.com/microsoft/vcpkg/files/11182257/install-x64-windows-rel-out-1.log)

**Comment by dg0yt** [comment]
Antivirus pain.

**Comment by baobabtree** [comment]
> 

Thank you for your reply. 
The Avira antivirus did pop up when installing the boost library. I turned it off and the boost library was installed successfully. However, the openblas library was not.
So how to fix it now? Turn off the antivirus and reinstall every library?

**Comment by baobabtree** [comment]
I reinstalled vcpkg at a different location and turned off the antivirus software. This time everything works fine.

**Comment by jimwang118** [comment]
Thanks for posting this issue. This issue has been Solved. So I am closing this issue for now.
