### ISSUE TITLE
[gstreamer] HEAD_REF should be main, not master

### ISSUE THREAD

**Issue by comex** [microsoft/vcpkg#30734]
**Describe the bug**
`gstreamer/portfile.cmake` has `HEAD_REF master`, but [the upstream repo](https://gitlab.freedesktop.org/gstreamer/gstreamer) switched the default branch name to `main` at some point, leaving the `master` branch pointing to a now-outdated version.  This causes issues when building with `--head`.

**Comment by jimwang118** [comment]
Need to wait for PR [30203](https://github.com/microsoft/vcpkg/pull/30203) to be merged.

**Comment by dg0yt** [comment]
> Need to wait for PR [30203](https://github.com/microsoft/vcpkg/pull/30203) to be merged.

That PR is obsolete.

**Comment by jimwang118** [comment]
> > Need to wait for PR [30203](https://github.com/microsoft/vcpkg/pull/30203) to be merged.
> 
> That PR is obsolete.

Yes, it's fixed in this PR [34345](https://github.com/microsoft/vcpkg/pull/34345).
