### ISSUE TITLE
[libphonenumber] Add osx and linux support

### ISSUE THREAD

**Issue by AachoLoya** [microsoft/vcpkg#30731]
### Is your feature request related to a problem? Please describe.

Current libphonenumber port is marked as not supported on linux and osx. Couldn't find in issues whether that's a limitation of the library or port issue that can be fixed.

### Proposed solution

Test and Add support for linux and osx. 

### Describe alternatives you've considered

Seems like someone was working on it but left: https://github.com/microsoft/vcpkg/pull/10088

**Comment by autoantwort** [comment]
You can run with `--allow-unsupported` to see what is the problem.

**Comment by Adela0814** [comment]
`libphonenumber` can't find `icuin.lib` in Linux, so it is currently not supported. In order to support Linux, the build error need to be resolved first:
```
CMake Error at CMakeLists.txt:43 (message):
  Can't find ICU: can't locate icuin.  Please read the README.
Call Stack (most recent call first):
  CMakeLists.txt:63 (print_error)
  CMakeLists.txt:151 (find_required_library)
```

**Comment by Adela0814** [comment]
I will try to fix this issue, and we welcome you to submit PR if you are more familiar with this library,

**Comment by Adela0814** [comment]
The real reason is that the library names generated by `icu` on `Windows` and `Linux` are different, so `icuin` cannot be found.
It is named `libicui18n.a` on `Linux`.

**Comment by dg0yt** [comment]
At the vcpkg it is possible to add patches. But switching to a canonical patterns like `find_package(ICU)` should really be done upstream.
(Maybe it is even possible to mitigate part of the problem without patching, e.g. using a `CMAKE_PROJECT_INCLUDE` which seeds the cache variables.)

**Comment by dg0yt** [comment]
I looked at it in the past, and I decided to leave it to those who want to use it.

**Comment by xiaozhuai** [comment]
@AachoLoya 
Please try #32899 to see if it works or not.

---

You can use following commands to get and apply patches and then install it.

```
curl -Ls https://github.com/microsoft/vcpkg/pull/32854.patch | git apply
vcpkg install libphonenumber:x64-linux
```

---

After this pr got merged, you may want to drop your local changes via
```
git checkout .
git clean -f
```

**Comment by xiaozhuai** [comment]
> when will your changes be merged with master branch?

Will be soon.

**Comment by xiaozhuai** [comment]
@JavierMatosD Close as completed by #32899
