### ISSUE TITLE
[nccl] build failure

### ISSUE THREAD

**Issue by Bzz2745** [microsoft/vcpkg#30733]
### Operating system

Linux(rhel 9)

### Compiler

GCC

### Steps to reproduce the behavior

```Shell
sudo ./vcpkg install flashlight-cuda[core,asr,fl,imgclass,lib,lm,objdet]:x64-linux --clean-after-build                                                        1 ✘  base    at 11:39:54
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
    flashlight-cuda[asr,core,fl,imgclass,lib,lm,objdet]:x64-linux -> 0.3#4
  * nccl[core]:x64-linux -> 2.4.6#2
  * openmpi[core]:x64-linux -> 4.1.3#1
  * stb[core]:x64-linux -> 2022-09-09
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Restored 0 package(s) from /root/.cache/vcpkg/archives in 66.8 us. Use --debug to see more details.
Installing 1/4 nccl:x64-linux...
Building nccl[core]:x64-linux...
-- Could NOT find NCCL (missing: NCCL_LIBRARIES) (found suitable version "2.17.1", minimum required is "2.4.6.1")
CMake Error at ports/nccl/portfile.cmake:15 (message):
  Please install NCCL using your system package manager (the same way you
  installed CUDA).  For example: apt install libnccl2 libnccl-dev.
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)

error: building nccl:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+nccl
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[nccl]+Build+error&body=Copy+issue+body+from+%2Fhome%2Fbazunzhi%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by autoantwort** [comment]
> Please install NCCL using your system package manager (the same way you
installed CUDA). For example: apt install libnccl2 libnccl-dev.

?

**Comment by Bzz2745** [comment]
> 

I have already installed it with yum and even build it from source cloned from github(put it in CUDA_HOME,where cuda11.8 installed), but the error still exist.

**Comment by Bzz2745** [comment]
> > Please install NCCL using your system package manager (the same way you
> > installed CUDA). For example: apt install libnccl2 libnccl-dev.
> 
> ?

I have already installed it with yum and even build it from source cloned from github(put it in CUDA_HOME,where cuda11.8 installed), but the error still exist.

**Comment by dg0yt** [comment]
It is a strange result, a "suitable version" (by headers) but "missing: NCCL_LIBRARIES". 
config logs could provide more information.

**Comment by Bzz2745** [comment]
> It is a strange result, a "suitable version" (maybe by headers?) but "missing: NCCL_LIBRARIES". config logs could provide more information.
Did it generated in vcpkg/buildtrees/nccl ? I can't find it through I run without "--clean-after-build"

**Comment by dg0yt** [comment]
> Did it generated in vcpkg/buildtrees/nccl ? I can't find it through I run without "--clean-after-build"

Good point. This port is just to check for the package, and it comes with its own find module. But it does so in script mode, not in project mode, so there are no other logs. It uses some environment variables and known paths to look for certain name patterns.
https://github.com/microsoft/vcpkg/blob/master/ports/nccl/FindNCCL.cmake

Where is you NCCL? Which libraries are installed? Which environment variables did you set?

**Comment by Bzz2745** [comment]
> > Did it generated in vcpkg/buildtrees/nccl ? I can't find it through I run without "--clean-after-build"
> 
> Good point. This port is just to check for the package, and it comes with its own find module. But it does so in script mode, not in project mode, so there are no other logs. It uses some environment variables and known paths to look for certain name patterns. https://github.com/microsoft/vcpkg/blob/master/ports/nccl/FindNCCL.cmake
> 
> Where is you NCCL? Which libraries are installed? Which environment variables did you set?

Here is the nccl I build:
![2023-04-09 19-04-07 的屏幕截图](https://user-images.githubusercontent.com/68807654/230769503-c79ba37e-457b-41f1-be5c-8840f610cef0.png)
Paths I using:
![2023-04-09 19-04-53 的屏幕截图](https://user-images.githubusercontent.com/68807654/230769615-ea42cac4-5958-4514-b58b-95bd5f042eec.png)
Information from yum:
![2023-04-09 19-06-39 的屏幕截图](https://user-images.githubusercontent.com/68807654/230769812-82075ece-1e38-4187-83c4-5829a7bdd696.png)
The first libnccl is installed by yum but it is for cuda-12.1,so I built and installed it from source.

**Comment by dg0yt** [comment]
What I do see is that 
- your local build is in `/usr/local/cuda-11.8`,
  (can be okay)
- `CUDA_HOME` is set to `${CUDA_HOME}:/usr/local/cuda`,
  (Is this meant to be a list of dirs, or just a single dir such as `/usr/local/cuda-11.8` [!]?)
- vcpkg doesn't look at `CUDA_HOME`.
  (For the libs, it looks at `CUDA_PATH`, `CUDNN_ROOT_DIR`, `CUDA_TOOLKIT_ROOT_DIR`, `NCCL`.)

**Comment by Bzz2745** [comment]
> What I do see is that
> 
> * your local build is in `/usr/local/cuda-11.8`,
>   (can be okay)
> * `CUDA_HOME` is set to `${CUDA_HOME}:/usr/local/cuda`,
>   (Is this meant to be a list of dirs, or just a single dir such as `/usr/local/cuda-11.8` [!]?)
> * vcpkg doesn't look at `CUDA_HOME`.
>   (For the libs, it looks at `CUDA_PATH`, `CUDNN_ROOT_DIR`, `CUDA_TOOLKIT_ROOT_DIR`, `NCCL`.)

I have tried add $ENV{CUDA_HOME} to FINDNCCL.cmake but it still useless,what should I do?

**Comment by dg0yt** [comment]
Not sure if you edited the right `FINDNCCL.cmake` but you shouldn't do it anyways. `CUDA_HOME` is an environment variable.

**Comment by Bzz2745** [comment]
> Not sure if you edited the right `FINDNCCL.cmake` but you shouldn't do it anyways. `CUDA_HOME` is an environment variable.

I just want to have a try to solve it through it did not work.

**Comment by autoantwort** [comment]
> what should I do?

Maybe set one of the supported env variables?
