### ISSUE TITLE
libdatachannel needs RTC_STATIC definition when built as a static library

### ISSUE THREAD

**Issue by jamal** [microsoft/vcpkg#30738]
**Describe the bug**
Building libdatachannel with the x64-windows-static triplet doesn't set the RTC_STATIC definition. This causes headers to include `__declspec(dllimport)`, which causes linking to fail. This is because the following defined in `common.hpp`:

```
#ifdef RTC_STATIC
#define RTC_CPP_EXPORT
#else // dynamic library
#ifdef _WIN32
#ifdef RTC_EXPORTS
#define RTC_CPP_EXPORT __declspec(dllexport) // building the library
#else
#define RTC_CPP_EXPORT __declspec(dllimport) // using the library
#endif
#else // not WIN32
#define RTC_CPP_EXPORT
#endif
#endif
```

I was able to bypass the linker failures by manually adding RTC_STATIC to my build.

**Comment by FrankXie05** [comment]
Need to export static cmake targets.

**Comment by dg0yt** [comment]
Needs patching which respects upstreams targets. 
(I had to look up where I applied a suitable strategy: `ports/mathgl/linkage.patch`)

**Comment by FrankXie05** [comment]
Upstream does not seem to want to build `STATIC` (default), so `RTC_STATIC` will not be set.
```
add_library(datachannel-static STATIC EXCLUDE_FROM_ALL
```
https://github.com/paullouisageneau/libdatachannel/blob/4df86b6ccbb348731ad4ba1e9045944cc77498bc/CMakeLists.txt#L237
```
target_compile_definitions(datachannel-static PRIVATE RTC_EXPORTS)
target_compile_definitions(datachannel-static PUBLIC RTC_STATIC)
```
https://github.com/paullouisageneau/libdatachannel/blob/v0.18.2/CMakeLists.txt#LL245C1-L246C65
