### ISSUE TITLE
mongocxx 3.2.0 :  mongocxx::options::index operator() call failed

### ISSUE THREAD

**Issue by leo-zhu** [Microsoft/vcpkg#3073]
error: no match for call to '(const mongocxx::v_noabi::options::index) ()

I have a function input argument defined as
const mongocxx::options::index& indexOpts;

With 3.2.0, I am now calling create_index() as
myCollection.create_index(keys, indexOpts());

indexOpts() failed with the error message mentioned above.

**Comment by JackBoosY** [comment]
Hi @leo-zhu ,  can you give me more code to repro it?

**Comment by wangli28** [comment]
Please open a new issue if this is still a problem for you.
