### ISSUE TITLE
[libiconv] build failure

### ISSUE THREAD

**Issue by KCenti** [microsoft/vcpkg#30739]
### Operating system

Windows

### Compiler

Visual Studio 2022

### Steps to reproduce the behavior

```Shell
./vcpkg.exe install libiconv:x64-windows
```

### Failure logs

Using cached msys-gzip-1.11-1-x86_64.pkg.tar.zst.
-- Using cached msys-bash-5.1.008-1-x86_64.pkg.tar.zst.
-- Using cached msys-autoconf-2.71-3-any.pkg.tar.zst.
-- Using cached msys-diffutils-3.8-2-x86_64.pkg.tar.zst.
-- Using cached msys-binutils-2.37-5-x86_64.pkg.tar.zst.
-- Using cached msys-libtool-2.4.7-3-x86_64.pkg.tar.zst.
-- Using cached msys-file-5.41-2-x86_64.pkg.tar.zst.
-- Using cached msys-zlib-1.2.11-1-x86_64.pkg.tar.xz.
-- Using cached msys-libbz2-1.0.8-3-x86_64.pkg.tar.zst.
-- Using cached msys-coreutils-8.32-2-x86_64.pkg.tar.zst.
-- Using cached msys-grep-3.0-2-x86_64.pkg.tar.xz.
-- Using cached msys-sed-4.8-2-x86_64.pkg.tar.zst.
-- Using cached msys-libpcre-8.45-1-x86_64.pkg.tar.zst.
-- Using cached msys-m4-1.4.19-2-x86_64.pkg.tar.zst.
-- Using cached msys-automake-wrapper-11-4-any.pkg.tar.zst.
-- Using cached msys-gawk-5.1.0-2-x86_64.pkg.tar.zst.
-- Using cached msys-mpfr-4.1.0-1-x86_64.pkg.tar.zst.
-- Using cached msys-gmp-6.2.1-1-x86_64.pkg.tar.zst.
-- Using cached msys-libreadline-8.1.001-1-x86_64.pkg.tar.zst.
-- Using cached msys-ncurses-6.2-2-x86_64.pkg.tar.zst.
-- Using cached msys-automake1.16-1.16.3-3-any.pkg.tar.zst.
-- Using cached msys-perl-5.32.1-2-x86_64.pkg.tar.zst.
-- Using cached msys-libcrypt-2.1-3-x86_64.pkg.tar.zst.
-- Using cached msys-pkg-config-0.29.2-4-x86_64.pkg.tar.zst.
-- Using cached msys-make-4.3-3-x86_64.pkg.tar.zst.
-- Using cached msys-findutils-4.8.0-1-x86_64.pkg.tar.zst.
-- Using cached msys-libintl-0.21-1-x86_64.pkg.tar.zst.
-- Using cached msys-libiconv-1.16-2-x86_64.pkg.tar.zst.
-- Using cached msys-gcc-libs-11.2.0-3-x86_64.pkg.tar.zst.
-- Using cached msys-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using cached msys-which-2.21-4-x86_64.pkg.tar.zst.
-- Using msys root at H:/github/vcpkg/downloads/tools/msys2/e6f7ae10db8f00f6
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at H:/github/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Warning at scripts/cmake/vcpkg_execute_build_process.cmake:65 (message):
  Please ensure your system has sufficient memory.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:151 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:2 (vcpkg_build_make)
  ports/libiconv/portfile.cmake:39 (vcpkg_install_make)
  scripts/ports.cmake:147 (include)

-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: H:/github/vcpkg/downloads/tools/msys2/e6f7ae10db8f00f6/usr/bin/make.exe -j 7 --trace -f Makefile all
    Working Directory: H:/github/vcpkg/buildtrees/libiconv/x64-windows-dbg/
    See logs for more information:
      H:\github\vcpkg\buildtrees\libiconv\build-x64-windows-dbg-out.log
      H:\github\vcpkg\buildtrees\libiconv\build-x64-windows-dbg-err.log
      H:\github\vcpkg\buildtrees\libiconv\build-x64-windows-dbg-out-1.log
      H:\github\vcpkg\buildtrees\libiconv\build-x64-windows-dbg-err-1.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:151 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:2 (vcpkg_build_make)
  ports/libiconv/portfile.cmake:39 (vcpkg_install_make)
  scripts/ports.cmake:147 (include)

error: building libiconv:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libiconv
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[libiconv]+Build+error&body=Copy+issue+body+from+H%3A%2Fgithub%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

[build-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/11185835/build-x64-windows-dbg-err.log)
[build-x64-windows-dbg-err-1.log](https://github.com/microsoft/vcpkg/files/11185836/build-x64-windows-dbg-err-1.log)
[build-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/11185837/build-x64-windows-dbg-out.log)
[build-x64-windows-dbg-out-1.log](https://github.com/microsoft/vcpkg/files/11185838/build-x64-windows-dbg-out-1.log)

**Comment by JonLiu1993** [comment]
@KCenti, Thanks for reporting this issue, but I can't reproduce it in my side with the latest vcpkg, please update your vcpkg repo (git pull, bootstrap-vcpkg).
````
PS F:\test\vcpkg> ./vcpkg install libiconv:x64-windows --editable
Computing installation plan...
The following packages are already installed:
    libiconv[core]:x64-windows -> 1.17#1
libiconv:x64-windows is already installed
Restored 0 package(s) from C:\Users\test\AppData\Local\vcpkg\archives in 198.3 us. Use --debug to see more details.
Total install time: 951.4 us
The package libiconv provides CMake targets:

    find_package(Iconv)
    target_link_libraries(main PRIVATE Iconv::Iconv)

````

**Comment by KCenti** [comment]
Thanks for the reply, the build was successful after reinstalling and using the latest windowsSDK
