### ISSUE TITLE
[cairo] build failure

### ISSUE THREAD

**Issue by Wedge009** [microsoft/vcpkg#30745]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
`vcpkg install cairo:x64-windows`
```

### Failure logs

[config-x64-windows-dbg-meson-log.txt.log](https://github.com/microsoft/vcpkg/files/11186820/config-x64-windows-dbg-meson-log.txt.log)
[config-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/11186822/config-x64-windows-dbg-out.log)
[stdout-x64-windows.log](https://github.com/microsoft/vcpkg/files/11186823/stdout-x64-windows.log)
[issue_body.md](https://github.com/microsoft/vcpkg/files/11186824/issue_body.md)

### Additional context

vcpkg @ 217194cea7e3491c14779c763beec50b6a4575d6

Recurring message seems to be `ERROR: Automatic wrap-based subproject downloading is disabled`

**Comment by Cheney-W** [comment]
I can't reproduce this issue in my side, I used the latest vcpkg and VS2022. I think you could remove the `vcpkg/downloads` folder and then run below command:
`.\vcpkg.exe install cairo:x64-windows --editable --binarysource=clear`

**Comment by dg0yt** [comment]
> Recurring message seems to be `ERROR: Automatic wrap-based subproject downloading is disabled`

The message appears because meson fails to find a dependency of cairo, here: fontconfig.
It is neither found with pkg-config nor with cmake. This is strange.

**Comment by Wedge009** [comment]
Yeah, I tried on another Windows system and didn't appear to have issues there, plus I didn't see any other relevant Cairo reports so I wondered if it was just me. I really haven't seen that sub-project downloading error message before so I had no idea what to do.

There's been an update to vcpkg master since I reported this, so I tried using that and also removed the download cache. Still seem to get the same error, even with the editable and binary source arguments. I am also using an up-to-date VS2022.

**Comment by Wedge009** [comment]
> > Recurring message seems to be `ERROR: Automatic wrap-based subproject downloading is disabled`
> 
> The message appears because meson fails to find a dependency of cairo, here: fontconfig. It is neither found with pkg-config nor with cmake. This is strange.

Interesting. I already have `fontconfig:x64-windows` installed. And I'm actually running into this issue trying to reinstall `pango:x64-windows`, which is stuck at this Cairo installation.

**Comment by dg0yt** [comment]
> -- Cleaning sources at C:/Users/[user]/Documents/vcpkg/buildtrees/cairo/src/1.17.8-13a78b6e7b.clean. Use --editable to skip cleaning for the packages you specify.

Special and non-latin characters in the user name may cause problems, too. (I mean the word which is replaced with `[user]` here.)

**Comment by Wedge009** [comment]
Thanks. In my case only using ASCII characters, no spaces or other special characters.

**Comment by Wedge009** [comment]
This seems to be resolved with recent vcpkg updates. Managed to build successfully at f0b5a6b60ad6d7aed68062371bfb886331206d70.
