### ISSUE TITLE
[<port name>] build failure

### ISSUE THREAD

**Issue by UredNuubjuz** [microsoft/vcpkg#30744]
### Operating system

Windows 10 Home

### Steps to reproduce the behavior

```Shell
vcpkg install opencv:x64-windows-static
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
    opencv[core,default-features]:x64-windows-static -> 4.7.0#1
  * opencv4[core,default-features,dnn,jpeg,png,quirc,tiff,webp]:x64-windows-static -> 4.7.0#3
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows-static...
Restored 0 package(s) from C:\Users\josel\AppData\Local\vcpkg\archives in 192 us. Use --debug to see more details.
Installing 1/2 opencv4:x64-windows-static...
Building opencv4[core,default-features,dnn,jpeg,png,quirc,tiff,webp]:x64-windows-static...
-- Using cached opencv-opencv-4.7.0-1.tar.gz.
-- Cleaning sources at C:/Users/josel/Documents/Vcpkg/vcpkg-master/buildtrees/opencv4/src/4.7.0-34a2240496.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/josel/Documents/Vcpkg/vcpkg-master/downloads/opencv-opencv-4.7.0-1.tar.gz
-- Applying patch 0001-disable-downloading.patch
-- Applying patch 0002-install-options.patch
-- Applying patch 0003-force-package-requirements.patch
-- Applying patch 0004-fix-eigen.patch
-- Applying patch 0005-fix-policy-CMP0057.patch
-- Applying patch 0006-fix-uwp.patch
-- Applying patch 0008-devendor-quirc.patch
-- Applying patch 0009-fix-protobuf.patch
-- Applying patch 0010-fix-uwp-tiff-imgcodecs.patch
-- Applying patch 0011-remove-python2.patch
-- Applying patch 0012-fix-zlib.patch
-- Applying patch 0015-fix-freetype.patch
-- Using source at C:/Users/josel/Documents/Vcpkg/vcpkg-master/buildtrees/opencv4/src/4.7.0-34a2240496.clean
-- Using cached opencv-cache/tiny_dnn/adb1c512e09ca2c7a6faef36f9c53e59-v1.0.0a3.tar.gz.
-- Found external ninja('1.11.0').
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Release --target install -- -v -j25
    Working Directory: C:/Users/josel/Documents/Vcpkg/vcpkg-master/buildtrees/opencv4/x64-windows-static-rel
    See logs for more information:
      C:\Users\josel\Documents\Vcpkg\vcpkg-master\buildtrees\opencv4\install-x64-windows-static-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/opencv4/portfile.cmake:450 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building opencv4:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+opencv4
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[opencv4]+Build+error&body=Copy+issue+body+from+C%3A%2FUsers%2Fjosel%2FDocuments%2FVcpkg%2Fvcpkg-master%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

i also tried "vcpkg install opencv:x64-windows-static --x-use-aria2" but it didnt work.

**Comment by Adela0814** [comment]
I'm not able to repro this issue. Please provide the failure log: `C:\Users\josel\Documents\Vcpkg\vcpkg-master\buildtrees\opencv4\install-x64-windows-static-rel-out.log`.

**Comment by UredNuubjuz** [comment]
> I'm not able to repro this issue. Please provide the failure log: `C:\Users\josel\Documents\Vcpkg\vcpkg-master\buildtrees\opencv4\install-x64-windows-static-rel-out.log`.

[install-x64-windows-static-rel-out.log](https://github.com/microsoft/vcpkg/files/11190093/install-x64-windows-static-rel-out.log)

Thanks for your help.

**Comment by dg0yt** [comment]
~~~
lib\opencv_flann4.lib : fatal error LNK1180: insufficient disk space to complete link
~~~

**Comment by UredNuubjuz** [comment]
> ```
> lib\opencv_flann4.lib : fatal error LNK1180: insufficient disk space to complete link
> ```

oh, that took the error away, thanks. I try it later if it works within vscode as a library.
