### ISSUE TITLE
[grpc] build failure when specifying custom compiler path

### ISSUE THREAD

**Issue by abdelmaged** [microsoft/vcpkg#30755]
### Operating system

x64-linux

### Compiler

GNU 10.2.0

### Steps to reproduce the behavior

```Shell
- Create custom triplet, with name "gcc10"
- Set VCPKG_CHAINLOAD_TOOLCHAIN_FILE to a custom toolchain file
- In the toolchain file set custom locations for CMAKE_C_COMPILER & CMAKE_CXX_COMPILER
- Create vcpkg-configuration.json and add directory of the triplet in overlay-triplets
- Create vcpkg.jsos, and grpc as a dependency
- Configure CMake like:
  cmake -B build -S . -G Ninja -DCMAKE_TOOLCHAIN_FILE=<path>/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=gcc10 -DVCPKG_HOST_TRIPLET=gcc10
```

### Failure logs

```
-- Using cached grpc-grpc-v1.51.1.tar.gz.
-- Cleaning sources at <path>/vcpkg/buildtrees/grpc/src/v1.51.1-1066d25324.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source <path>/vcpkg/downloads/grpc-grpc-v1.51.1.tar.gz
-- Applying patch 00001-fix-uwp.patch
-- Applying patch 00002-static-linking-in-linux.patch
-- Applying patch 00003-undef-base64-macro.patch
-- Applying patch 00004-link-gdi32-on-windows.patch
-- Applying patch 00005-fix-uwp-error.patch
-- Applying patch 00009-use-system-upb.patch
-- Applying patch snprintf.patch
-- Applying patch 00012-fix-use-cxx17.patch
-- Applying patch 00014-pkgconfig-upbdefs.patch
-- Applying patch 00015-disable-download-archive.patch
-- Using source at <path>/vcpkg/buildtrees/grpc/src/v1.51.1-1066d25324.clean
-- Configuring gcc10
-- Building gcc10-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: <path>/cmake/3.25.2/bin/cmake --build . --config Debug --target install -- -v -j21
    Working Directory: <path>/vcpkg/buildtrees/grpc/gcc10-dbg
    See logs for more information:
      <path>/vcpkg/buildtrees/grpc/install-gcc10-dbg-err.log

Call Stack (most recent call first):
  <path>/test_grpc/build/vcpkg_installed/gcc10/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  <path>/test_grpc/build/vcpkg_installed/gcc10/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/grpc/portfile.cmake:69 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)
```

<details><summary>/vcpkg/buildtrees/grpc/install-gcc10-dbg-err.log</summary>

```
ninja: error: '_gRPC_CPP_PLUGIN-NOTFOUND', needed by '<path>/vcpkg/buildtrees/grpc/gcc10-dbg/gens/src/proto/grpc/reflection/v1alpha/reflection.pb.cc', missing and no known rule to make it
```
</details>

### Additional context

<details><summary>vcpkg.json</summary>

```
{
  "name": "test-grpc",
  "version-string": "0.1.0",
  "dependencies": [
    "grpc"
  ]
}
```
</details>

<details><summary>gcc10.json</summary>

```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_DIR}/gcc10.toolchain.cmake")
```
</details>

<details><summary>gcc10.toolchain.json</summary>

```
set(CMAKE_C_COMPILER "<path>/gcc/10.2.0-static/bin/gcc" CACHE PATH "")
set(CMAKE_CXX_COMPILER "<path>/gcc/10.2.0-static/bin/g++" CACHE PATH "")
```
</details>

<details><summary>vcpkg-configuration.json</summary>

```
{
  "overlay-triplets": [
    "custom_triplets"
  ]
}
```
</details>

Project Structture
.
├── CMakeLists.txt
├── custom_triplets
│   ├── gcc10.cmake
│   └── gcc10.toolchain.cmake
├── vcpkg-configuration.json
└── vcpkg.json

**Comment by FrankXie05** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by abdelmaged** [comment]
@FrankXie05 I did not get how the issue was fixed ?

**Comment by FrankXie05** [comment]
@abdelmaged You need add the feature `grpc_cpp_plugin` to your `vcpkg.json`.
see: https://learn.microsoft.com/en-us/vcpkg/users/manifests#example-1-multiple-file-formats

**Comment by abdelmaged** [comment]
ok, I'll try this.
But, I remember I did not need that when using classic mode and setting CC & CXX paths.

Also, from 
https://github.com/microsoft/vcpkg/blob/187712658b806926b30b63473b42a628d3225c9a/ports/grpc/vcpkg.json#L38 feature grpc_cpp_plugin does not exist

**Comment by FrankXie05** [comment]
The feature `codegen` build the tools you need. `grpc_cpp_plugin`.
https://github.com/microsoft/vcpkg/blob/4f9d25a7f299db656c376af402637819ee2caba0/ports/grpc/portfile.cmake#L40
https://github.com/microsoft/vcpkg/blob/4f9d25a7f299db656c376af402637819ee2caba0/ports/grpc/portfile.cmake#L73

**Comment by abdelmaged** [comment]
I tried added this feature explicitly in vcpkg.json as:
```
  "dependencies": [
    { "name" : "grpc", "features": "codegen" }
  ],
```
but still got the same error.

Also, I think this feature is already enabled by default, so I don't need to explicitly specify it.

**Comment by FrankXie05** [comment]
@abdelmaged Sorry, do you have an executable program `grpc_cpp_plugin` in the `vcpkg\packages\grpc_x64-linux\tools\grpc` directory?  And could you please provide the project file `CMakeLists.txt`? :)
