### ISSUE TITLE
[msys2] Failed to download from mirror set build failure

### ISSUE THREAD

**Issue by dpieve** [microsoft/vcpkg#30761]
### Operating system

Windows 11

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
"VCPKG_PATH\vcpkg.exe" install  --x-wait-for-lock --triplet "x64-windows" --vcpkg-root "VCPKG_PATH\\" "--x-manifest-root=ProjectPath\\" "--x-install-root=C:\dev\ProjectName\vcpkg_installed\x64-windows\\
```

### Failure logs

vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161, 5) : warning: error: Failed to download from mirror set
vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161, 5) : warning: error: https://repo.msys2.org/msys/x86_64/msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst: failed: status code 404
vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161, 5) : warning: error: https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst: failed: status code 404
vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161, 5) : warning: error: https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst: failed: status code 404
vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161, 5) : warning: error: https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst: failed: status code 404
vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161, 5) : warning: error: https://mirrors.ustc.edu.cn/msys2/msys/x86_64/msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst: failed: status code 404
vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161, 5) : warning: error: https://mirror.bit.edu.cn/msys2/msys/x86_64/msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst: failed: status code 404
vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161, 5) : warning: error: https://mirror.selfnet.de/msys2/msys/x86_64/msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst: failed: status code 404
vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161, 5) : warning: error: https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst: failed: status code 404
vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161, 5) : warning:       Failed to download file with error : 1
vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161, 5) : warning: error: building vcpkg - gfortran : x64 - windows failed with : BUILD_FAILED
vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161, 5) : warning: error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161, 5) : error MSB3073 : The command ""vcpkg\vcpkg.exe" install  --x-wait-for-lock --triplet "x64 - windows" --vcpkg-root "vcpkg\\" "--x - manifest - root = ProjectPath\\" "--x - install - root = ProjectPath\vcpkg_installed\x64 - windows\\" " exited with code 1.

### Additional context

`vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161, 5) : error MSB3073 : The command ""vcpkg\vcpkg.exe" install  --x-wait-for-lock --triplet "x64 - windows" --vcpkg-root "vcpkg\\" "--x - manifest - root = ProjectPath\\" "--x - install - root = ProjectPath\vcpkg_installed\x64 - windows\\" " exited with code 1.`

This line goes to this code in the `vcpkg.targets`:

```
<Exec Command="%22$(_ZVcpkgExecutable)%22 install $(_ZVcpkgHostTripletParameter) --x-wait-for-lock --triplet %22$(VcpkgTriplet)%22 --vcpkg-root %22$(_ZVcpkgRoot)\%22 %22--x-manifest-root=$(_ZVcpkgManifestRoot)\%22 %22--x-install-root=$(_ZVcpkgInstalledDir)\%22 $(VcpkgAdditionalInstallOptions)"
          StandardOutputImportance="High"
          IgnoreStandardErrorWarningFormat="true"
          CustomWarningRegularExpression="([Ee]rror|[Ww]arning):" />
```

Visual Studio - Version 17.5.3

**Comment by Adela0814** [comment]
As @dg0yt said, this issue has been fixed by https://github.com/microsoft/vcpkg/pull/30546.
