### ISSUE TITLE
[New Port Request] gcc

### ISSUE THREAD

**Issue by abdelmaged** [microsoft/vcpkg#30782]
### Library name

gcc

### Library description

The GNU Compiler Collection includes front ends for C, C++, Objective-C, Fortran, Ada, Go, and D, as well as libraries for these languages (libstdc++,...). GCC was originally written as the compiler for the GNU operating system. The GNU system was developed to be 100% free software, free in the sense that it respects the user's freedom.

### Source repository URL

git://gcc.gnu.org/git/gcc.git

### Project homepage (if different from the source repository)

https://gcc.gnu.org/

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

I'm surprised this is not ported yet, gcc installation could be a hassle, and vcpkg can help in this process.

Installation instructions:
https://gcc.gnu.org/install/index.html

**Comment by autoantwort** [comment]
vcpkg is not a package manager for tools, it is a package manager for c++ libraries.

**Comment by abdelmaged** [comment]
I think libstdc++ is a c++ library, it contains other libraries as well.
