### ISSUE TITLE
[mapnik] does not generate plugins

### ISSUE THREAD

**Issue by MoeSzyslak98** [microsoft/vcpkg#30793]
### Operating system

Manjaro Linux 22.1.0 Talos

### Compiler

GCC, Clang

### Steps to reproduce the behavior

```Shell
In an attempt to build https://github.com/mathisloge/mapnik-vcpkg-test
I ran "cmake . -B build -DCMAKE_TOOLCHAIN_FILE=$VCPKG_TOOLCHAIN_FILE"
[$VCPKG_TOOLCHAIN_FILE is path to vcpkg.cmake file in vcpkg/scripts/buildsystems/ folder]
vcpkg build and installs every thing smoothly an shows regular message:

The package mapnik provides CMake targets:

    find_package(mapnik CONFIG REQUIRED)
    target_link_libraries(main PRIVATE mapnik::mapnik mapnik::json mapnik::wkt)
    
If you only need the compile definitions without any sources, use target mapnik::core.
If any plugins were installed, call the function `mapnik_find_plugin_dir(MAPNIK_PLUGIN_DIR)` to get the plugin installation folder for the currently used configuration. See the docs for more information.

but the it give the following error.
```

### Failure logs

CMake Error at build/vcpkg_installed/x64-linux/share/mapnik/mapnikConfig.cmake:71 (list):
  list sub-command FIND requires three arguments.
Call Stack (most recent call first):
  CMakeLists.txt:7 (mapnik_find_plugin_dir)

CMake Error at build/vcpkg_installed/x64-linux/share/mapnik/mapnikConfig.cmake:73 (if):
  if given arguments:

    "GREATER_EQUAL" "0"

  Unknown arguments specified
Call Stack (most recent call first):
  CMakeLists.txt:7 (mapnik_find_plugin_dir)

-- Configuring incomplete, errors occurred!

### Additional context

it does not even build input plugins.

**Comment by dg0yt** [comment]
> CMake Error at build/vcpkg_installed/x64-linux/share/mapnik/mapnikConfig.cmake:73 (if):
> if given arguments:

What is the content of  `build/vcpkg_installed/x64-linux/share/mapnik/mapnikConfig.cmake` line 73`?

What is the `cmake_minimum_required(VERSION ...)` your project uses *before* calling `project(...)`?

**Comment by dg0yt** [comment]
I guess you must set `CMAKE_BUILD_TYPE` to use `mapnik_find_plugin_dir`:
https://github.com/mapnik/mapnik/blob/c4aa24496a0cc044e753a09ce4314957e2e3e237/cmake/mapnikConfig.cmake.in#L31-L39

**Comment by MoeSzyslak98** [comment]
thank you for your immediate response.
I added `-DCMAKE_BUILD_TYPE=Release` in command and the error disappeared and a new message added in new output:
-- DIR /home/user/projects/mapnik-vcpkg-test/build/vcpkg_installed/x64-linux/lib/mapnik/input
this is the address of where input plugins should be normally but when I tried to list the content of the folder `ls` command couldn't find it and returned "No such file or directory"

**Comment by MoeSzyslak98** [comment]
I tried building the latest commit [Mar 20, 2023], hoping the problem to be solved by that, but it didn't.
I also did some poor man's debugging in vcpkg/ports/mapnik/porfile.cmake
I said to myself, "Maybe they changed something that don't pass the input options], but everything was OK.

**Comment by MoeSzyslak98** [comment]
I found there was somebody else who had the same problem in Windows about 2 months ago [this](https://github.com/mapnik/mapnik/issues/4381) is the issue thread [has no specific detail].

**Comment by mathisloge** [comment]
could you tell the vcpkg install options?

**Comment by jimwang118** [comment]
I used the example you provided, and then compiled it locally and the result was successful.

```
vwangjim@vwangjim001:/data/testmapnik$ cmake -DCMAKE_BUILD_TYPE=release -DCMAKE_TOOLCHAIN_FILE=/data/vcpkg/scripts/buildsystems/vcpkg.cmake CMakeLists.txt
-- Running vcpkg install
Detecting compiler hash for triplet x64-linux...
All requested packages are currently installed.
Restored 0 package(s) from /home/vwangjim/.cache/vcpkg/archives in 1.3 us. Use --debug to see more details.
Total install time: 8.1 us
The package mapnik provides CMake targets:

    find_package(mapnik CONFIG REQUIRED)
    target_link_libraries(main PRIVATE mapnik::mapnik mapnik::json mapnik::wkt)

If you only need the compile definitions without any sources, use target mapnik::core.
If any plugins were installed, call the function `mapnik_find_plugin_dir(MAPNIK_PLUGIN_DIR)` to get the plugin installation folder for the currently used configuration. See the docs for more information.

-- Running vcpkg install - done
-- Found the following ICU libraries:
--   uc (required)
--   i18n (required)
--   data (required)
CMake Warning at /usr/share/cmake-3.22/Modules/FindBoost.cmake:1369 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindBoost.cmake:1492 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.22/Modules/FindBoost.cmake:2102 (_Boost_MISSING_DEPENDENCIES)
  vcpkg_installed/x64-linux/share/boost/vcpkg-cmake-wrapper.cmake:11 (_find_package)
  /data/vcpkg/scripts/buildsystems/vcpkg.cmake:806 (include)
  /usr/share/cmake-3.22/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  vcpkg_installed/x64-linux/share/mapnik/mapnikConfig.cmake:31 (find_dependency)
  /data/vcpkg/scripts/buildsystems/vcpkg.cmake:852 (_find_package)
  CMakeLists.txt:5 (find_package)


CMake Warning at /usr/share/cmake-3.22/Modules/FindBoost.cmake:1369 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindBoost.cmake:1492 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.22/Modules/FindBoost.cmake:2102 (_Boost_MISSING_DEPENDENCIES)
  vcpkg_installed/x64-linux/share/boost/vcpkg-cmake-wrapper.cmake:11 (_find_package)
  /data/vcpkg/scripts/buildsystems/vcpkg.cmake:806 (include)
  /usr/share/cmake-3.22/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  vcpkg_installed/x64-linux/share/mapnik/mapnikConfig.cmake:31 (find_dependency)
  /data/vcpkg/scripts/buildsystems/vcpkg.cmake:852 (_find_package)
  CMakeLists.txt:5 (find_package)


CMake Warning at /usr/share/cmake-3.22/Modules/FindBoost.cmake:1369 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindBoost.cmake:1492 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.22/Modules/FindBoost.cmake:2102 (_Boost_MISSING_DEPENDENCIES)
  vcpkg_installed/x64-linux/share/boost/vcpkg-cmake-wrapper.cmake:11 (_find_package)
  /data/vcpkg/scripts/buildsystems/vcpkg.cmake:806 (include)
  /usr/share/cmake-3.22/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  vcpkg_installed/x64-linux/share/mapnik/mapnikConfig.cmake:31 (find_dependency)
  /data/vcpkg/scripts/buildsystems/vcpkg.cmake:852 (_find_package)
  CMakeLists.txt:5 (find_package)


-- Found Freetype: optimized;/data/testmapnik/vcpkg_installed/x64-linux/lib/libfreetype.a;debug;/data/testmapnik/vcpkg_installed/x64-linux/debug/lib/libfreetyped.a (found version "2.12.1")
-- Found ZLIB: optimized;/data/testmapnik/vcpkg_installed/x64-linux/lib/libz.a;debug;/data/testmapnik/vcpkg_installed/x64-linux/debug/lib/libz.a (found version "1.2.13")
-- Found BZip2: optimized;/data/testmapnik/vcpkg_installed/x64-linux/lib/libbz2.a;debug;/data/testmapnik/vcpkg_installed/x64-linux/debug/lib/libbz2d.a (found version "1.0.8")
-- Found PNG: optimized;/data/testmapnik/vcpkg_installed/x64-linux/lib/libpng16.a;debug;/data/testmapnik/vcpkg_installed/x64-linux/debug/lib/libpng16d.a (found version "1.6.39")
-- Found JPEG: optimized;/data/testmapnik/vcpkg_installed/x64-linux/lib/libjpeg.a;debug;/data/testmapnik/vcpkg_installed/x64-linux/debug/lib/libjpeg.a (found version "62")
-- Found TIFF: optimized;/data/testmapnik/vcpkg_installed/x64-linux/lib/libtiff.a;debug;/data/testmapnik/vcpkg_installed/x64-linux/debug/lib/libtiffd.a (found version "4.5.0")
-- Found LibLZMA: optimized;/data/testmapnik/vcpkg_installed/x64-linux/lib/liblzma.a;debug;/data/testmapnik/vcpkg_installed/x64-linux/debug/lib/liblzma.a (found version "5.4.1")
-- DIR /data/testmapnik/vcpkg_installed/x64-linux/lib/mapnik/input
-- Configuring done
-- Generating done
-- Build files have been written to: /data/testmapnik
vwangjim@vwangjim001:/data/testmapnik$ cmake --build .
[ 50%] Building CXX object CMakeFiles/mapnik-demo.dir/rundemo.cpp.o
[100%] Linking CXX executable mapnik-demo
[100%] Built target mapnik-demo
vwangjim@vwangjim001:/data/testmapnik$ ls
CMakeCache.txt  CMakeLists.txt  README.md            config.hpp.in  demo         rundemo.cpp                 vcpkg.json      vcpkg_installed
CMakeFiles      Makefile        cmake_install.cmake  data           mapnik-demo  vcpkg-manifest-install.log  vcpkg_config.h

```

**Comment by dg0yt** [comment]
IIUC dynamic plugins are only built for shared linkage (x64-linux-dynamic), not for static linkage (x64-linux).
But is there installation code for anything but `*.DLL`?

**Comment by mathisloge** [comment]
Yes indeed, the plugins are statically linked into the library with x64-linux.

With dynamic they should be deployed. At least that worked with Ubuntu

**Comment by MoeSzyslak98** [comment]
@jimwang118 the project build and compile smoothly but in runtime mapnik looks for some ".input" plugin files that it must be built in installing process after you add "input-[name]" option in vcpkg. the problem is they are not getting build.

**Comment by mathisloge** [comment]
> @jimwang118 the project build and compile smoothly but in runtime mapnik looks for some ".input" plugin files that it must be built in installing process after you add "input-[name]" option in vcpkg. the problem is they are not getting build.

As previously mentioned, the linux triplet will compile the plugins into the shared library.
If you use the vcpkg-mapnik-test (which is usually only a test project for me to check and nothing else) you might need to comment out the https://github.com/mathisloge/mapnik-vcpkg-test/blob/1b8957faf3fa6f91f0e35cd8c353ff46a85535d8/rundemo.cpp#L64

But be aware that the static build might currently have still some problems. It was only recently re-added to the project and I didn't have had the time to track down all remaining issues.

**Comment by MoeSzyslak98** [comment]
thank you all for your patience, i added the `-DVCPKG_TARGET_TRIPLET=x64-linux-dynamic` and it worked perfectly.
but if its possible add these little things in a message or something, like there may be a problem building static and you should build the project in release.

thank you all, once more and have a good time.

**Comment by dg0yt** [comment]
The first thing you reported (config error) needs to be fixed upstream. TBH it is not unusual that project expect `CMAKE_BUILD_TYPE` to be set, but it should tolerate it nevertheless. (Note: You don't to build in release, you just have to set the variable.)

For the second thing you reported (no plugins), you never made it clear if you observe functional limitations. So we still don't know if there is a problem.

**Comment by MoeSzyslak98** [comment]
What do you mean by functional limitations? plugins provide functions for parsing certain files like shape(.shp) for geojson files, if they are not there, we can't use certain functionality and  get runtime errors.

IDK whether I got the question right or not.

**Comment by mathisloge** [comment]
> The first thing you reported (config error) needs to be fixed upstream. TBH it is not unusual that project expect CMAKE_BUILD_TYPE to be set, but it should tolerate it nevertheless. (Note: You don't to build in release, you just have to set the variable.)

Mapnik itself don't expect the build type. The dependend project (in this case the test project, independent repository) does expect a build type through the use of a helper function which uses the installed targets to locate the plugins.

**Comment by dg0yt** [comment]
> a helper function which uses the installed targets to locate the plugins.

... and which is provided by Mapnik. IMO it doesn't need to cause a config error (as it does handle unkown configs), or it could at least provide better diagnostics.

**Comment by dg0yt** [comment]
> What do you mean by functional limitations? plugins provide functions for parsing certain files like shape(.shp) for geojson files, if they are not there, we can't use certain functionality and get runtime errors.

The functions can be part of the main binaries if not compiled as a plugin. So the question was if you were actually unable to read shp or geojson files, or if you were just concerned that this might be the case.

**Comment by MoeSzyslak98** [comment]
IDK what it(mapnik) called professionally , but I say its a graphical engine for a very special use (creating maps and visualizing geospatial data), One can  use it by hand and creating lines and points and with them polygons, but I don't think anybody do that most of people use data formats like shape files geojson files and etc.

>  So the question was if you were actually unable to read shp or geojson files, or if you were just concerned that this might be the case.

and for your question the core library just gives the lines and points and their masks (lines being dashed and/or bold or something like railways mark on maps). for creating professional maps one should download the map data one wants in formats like (the input formats in mapnik shape, ogr , etc. ) and give them to the library the way it understands this is where they made our work easy and created plugins, and I don't think we can use this data without plugins.

more information and examples are in mapnik's test folder.

I hope I was able to answer your question.

**Comment by dg0yt** [comment]
> I hope I was able to answer your question.

No. Your explanations sound theoretical again, *as if based on assumptions* of which files should exist after the build. I still don't know if you *actually tested* whether the desired formats where simply available with the main library in the statical build.
