### ISSUE TITLE
Add yaml-cpp

### ISSUE THREAD

**Issue by Wakusei** [Microsoft/vcpkg#308]
I'd like to add yaml-cpp.
https://github.com/jbeder/yaml-cpp

**Comment by ras0219-msft** [comment]
We'd be happy to accept a PR for yaml-cpp 👍

**Comment by Wakusei** [comment]
PR was merged.

**Comment by yamcenutzer** [comment]
Unfortunately, the way yaml-cpp is built here seems not correct.
simple two-liners will havve unresolved externals.

Currently yaml-cpp seems only to be usable as static lib with dynamic rt.
