### ISSUE TITLE
[bullet3] build failure

### ISSUE THREAD

**Issue by DanSJohnson** [microsoft/vcpkg#30802]
### Operating system

x64-linux (WSL)

### Compiler

GNU 7.5.0

### Steps to reproduce the behavior

```Shell
**To Reproduce**

`vcpkg install bullet3`
```

### Failure logs
```
**Failure logs**
-- Using cached bulletphysics-bullet3-3.25.tar.gz.
-- Extracting source /home/daniel/vcpkg/downloads/bulletphysics-bullet3-3.25.tar.gz
-- Applying patch cmake-fix.patch
CMake Error at scripts/cmake/vcpkg_extract_source_archive.cmake:159 (file):
  file RENAME failed to rename

    /home/daniel/vcpkg/buildtrees/bullet3/src/3.25-98f155ca90.clean.tmp/bullet3-3.25

  to

    /home/daniel/vcpkg/buildtrees/bullet3/src/3.25-98f155ca90.clean

  because: Permission denied

Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:8 (vcpkg_extract_source_archive)
  scripts/cmake/vcpkg_from_github.cmake:113 (vcpkg_extract_source_archive_ex)
  ports/bullet3/portfile.cmake:4 (vcpkg_from_github)
  scripts/ports.cmake:147 (include)
```
### Additional context

Hi everyone, sorry if this is a noob problem but I'm struggling to get Bullet3 to install properly. 

I'm following the instructions in Bullet's page [here](https://github.com/bulletphysics/bullet3). 

My vcpkg is up to date to my knowledge. The following was generated as part of `issue_body.md` :
```
vcpkg-tool version: 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895
    vcpkg-scripts version: 203383666 2023-04-11 (9 hours ago)
```

I have tried executing `sudo vcpkg install bullet3` without success, and have also tried using `sudo chown -R 777 ./vcpkg` prior to installation, but that hasn't helped either.

Any assistance would be appreciated.

**Comment by DanSJohnson** [comment]
As an update, I have also tried opening a terminal as root and then doing it and i get the same `Permission denied` issue.

**Comment by Cheney-W** [comment]
I can't reproduce this issue with latest vcpkg, I am considering whether it could be an antivirus software issue.

**Comment by DanSJohnson** [comment]
is there anything I could try to test that theory?

**Comment by Cheney-W** [comment]
I'm sure all the steps you've executed are correct, which is the normal process of using vcpkg.

As for the issue you're currently facing, it seems to be a permission problem with your account. I'm not sure which Linux system you're using. Could you try manually creating a folder and then changing its name? If you're unable to do so, you may need to use an account with administrator privileges to use vcpkg.

**Comment by DanSJohnson** [comment]
I am able to create and change folder names, and I have tried this process as root and encountered the same problem, so I'm not sure why this is happening. 

That said, I have now sidestepped this problem by building Bullet3 from source instead.

**Comment by dg0yt** [comment]
FTR bullet3 builds in vcpkg CI.
I assume that the "Permission denied" on rename is the result of some process still blocking the original location. Given that you are reporting WSL, the usual suspect is anti-virus software. Checking deeper, I find that the bullet3 source archive includes several EXEs in the bullet3 dir. So there is work to do for AV.
