### ISSUE TITLE
[raylib] CMake cannot access the library directory because of Permission denied

### ISSUE THREAD

**Issue by KhiemGOM** [microsoft/vcpkg#30803]
**Describe the bug**
I tried to build a C++ program installed with raylib 4.5.0 x64-mingw-dynamic and x64-mingw-static (both produce the same error) using vcpkg on CLion. I installed the library manually with MSYS because CLion integrated vcpkg was having troubles. After that, I tried to run it with MinGW Makefiles and it produces this error: 
```
Could not find a package configuration file provided by "raylib" with any
  of the following names:

    raylibConfig.cmake
    raylib-config.cmake

  Add the installation prefix of "raylib" to CMAKE_PREFIX_PATH or set
  "raylib_DIR" to a directory containing one of the above files.  If "raylib"
  provides a separate development package or SDK, be sure it has been
  installed.
```

After manually set the raylib_DIR with `set(raylib_DIR "C:\\Users\\Admin\\.clion-vcpkg\\vcpkg\\packages\\raylib_x64-mingw-static\\share\\raylib")` it proceeds but now with a different error:
```
[ 50%] Linking CXX executable Try_Things_Out.exe
D:\Programmes App\JetBrains\apps\CLion\ch-0\231.8109.222\bin\mingw\bin/ld.exe: cannot find C:/Users/Admin/.clion-vcpkg/vcpkg/packages/raylib_x64-mingw-static/lib: Permission denied
collect2.exe: error: ld returned 1 exit status
mingw32-make[3]: *** [CMakeFiles\Try_Things_Out.dir\build.make:100: Try_Things_Out.exe] Error 1
mingw32-make[2]: *** [CMakeFiles\Makefile2:82: CMakeFiles/Try_Things_Out.dir/all] Error 2
mingw32-make[1]: *** [CMakeFiles\Makefile2:89: CMakeFiles/Try_Things_Out.dir/rule] Error 2
mingw32-make: *** [Makefile:123: Try_Things_Out] Error 2
```

I ran CLion with administrator status, check the permission for the folders, turn off Window Defender firewall but to no avail. 
I tried to install another library but it was having its own trouble, if anyone know a library that is similar to raylib in term of installation process, please recommend so I can test it. 

Here's my CMakeList.txt:
```
cmake_minimum_required(VERSION 3.25)
project(Try_Things_Out)

set(CMAKE_CXX_STANDARD 23)
set(raylib_DIR "C:\\Users\\Admin\\.clion-vcpkg\\vcpkg\\packages\\raylib_x64-mingw-static\\share\\raylib")
set(CMAKE_TOOLCHAIN_FILE "C:\\Users\\Admin\\.clion-vcpkg\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake")
find_package(raylib CONFIG REQUIRED)

add_executable(Try_Things_Out main.cpp)
target_link_libraries(Try_Things_Out PRIVATE raylib)
```

**Environment**
- OS: Windows 10
- Compiler: Clion's MinGW Makefiles (also tried Ninja but also failed due to permission denied)
- IDE: CLion 2023.1.1

**To Reproduce**
1. export VCPKG_DEFAULT_HOST_TRIPLET=x64-mingw-static
2. export VCPKG_DEFAULT_TRIPLET=x64-mingw-static (shown in the tutorial [here](https://learn.microsoft.com/vi-vn/vcpkg/users/platforms/mingw))
3. ./vcpkg install raylib:x64-mingw-static
4. Set the CMakeList.txt up
5. Build
6. See the error

**Expected behavior**
It should have been compiled successfully

**Failure logs**
First error (resolved but still weird that I have to set it up manually so I added it just in case):
```
Could not find a package configuration file provided by "raylib" with any
  of the following names:

    raylibConfig.cmake
    raylib-config.cmake

  Add the installation prefix of "raylib" to CMAKE_PREFIX_PATH or set
  "raylib_DIR" to a directory containing one of the above files.  If "raylib"
  provides a separate development package or SDK, be sure it has been
  installed.
```
  
  Second error:
```
  [ 50%] Linking CXX executable Try_Things_Out.exe
D:\Programmes App\JetBrains\apps\CLion\ch-0\231.8109.222\bin\mingw\bin/ld.exe: cannot find C:/Users/Admin/.clion-vcpkg/vcpkg/packages/raylib_x64-mingw-static/lib: Permission denied
collect2.exe: error: ld returned 1 exit status
mingw32-make[3]: *** [CMakeFiles\Try_Things_Out.dir\build.make:100: Try_Things_Out.exe] Error 1
mingw32-make[2]: *** [CMakeFiles\Makefile2:82: CMakeFiles/Try_Things_Out.dir/all] Error 2
mingw32-make[1]: *** [CMakeFiles\Makefile2:89: CMakeFiles/Try_Things_Out.dir/rule] Error 2
mingw32-make: *** [Makefile:123: Try_Things_Out] Error 2
```

**Additional context**
I don't want to download MVSC or its CMake tools so I opted for vcpkg with MinGW instead.

**Things I have tried**
- Run CLion with administrator status.
- Check the permission for the folders. 
- Turn off Window Defender firewall. 
- Install another library but it was having its own trouble. (still not sure if it's raylib specific)
- After trying to manually pass toolchain path, the compiler now says that I need to provide it with raylib_LIBRARY and raylib_INCLUDE_DIR so I did:
```
set(raylib_LIBRARY "C:\\Users\\Admin\\.clion-vcpkg\\vcpkg\\packages\\raylib_x64-mingw-static\\lib")
set(raylib_INCLUDE_DIR "C:\\Users\\Admin\\.clion-vcpkg\\vcpkg\\packages\\raylib_x64-mingw-static\\include")
```
After that, it still give the same permission error.
- Try different paths with the raylib_LIBRARY and found out that a non-existence path will produce a different error so my path provided definitely exists. 
- Try to delete the path, just reduce the path into `"C:\"` and "`D:\"` but it still gives permission denied. So it's universal to the whole Volumes.

**Comment by FrankXie05** [comment]
Could you please try to remove these:
```
set(raylib_DIR "C:\\Users\\Admin\\.clion-vcpkg\\vcpkg\\packages\\raylib_x64-mingw-static\\share\\raylib")
set(CMAKE_TOOLCHAIN_FILE "C:\\Users\\Admin\\.clion-vcpkg\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake")
```
and manually pass in `CMAKE_TOOLCHAIN_FILE`? :)
eg: `cmake .. -DCMAKE_TOOLCHAIN_FILE "C:\\Users\\Admin\\.clion-vcpkg\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake"`

**Comment by KhiemGOM** [comment]
> Could you please try to remove these:
> ```
> set(raylib_DIR "C:\\Users\\Admin\\.clion-vcpkg\\vcpkg\\packages\\raylib_x64-mingw-static\\share\\raylib")
> set(CMAKE_TOOLCHAIN_FILE "C:\\Users\\Admin\\.clion-vcpkg\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake")
> ```
> and manually pass in `CMAKE_TOOLCHAIN_FILE`? :)
> eg: `cmake .. -DCMAKE_TOOLCHAIN_FILE "C:\\Users\\Admin\\.clion-vcpkg\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake"`
> 
> 

I tried pass it manually to CMake profiles setting but it also didn't work, same error.

**Comment by dg0yt** [comment]
`CMAKE_TOOLCHAIN_FILE` must be set before the first time `project` is seen. 
BTW you can `/` as a path separator with CMake.

**Comment by KhiemGOM** [comment]
> `CMAKE_TOOLCHAIN_FILE` must be set before the first time `project` is seen. BTW you can `/` as a path separator with CMake.

I have passed `CMAKE_TOOLCHAIN_FILE` path into the CMake options and it still produce the same error. However, I made some interesting observation when I changed it. Please refer to my previous comment for it.

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.

**Comment by hung-dt** [comment]
@KhiemGOM Did you put `raylib` in file `vcpkg.json`?
```json
{
    "dependencies": [
        "raylib"
    ]
}
```
