### ISSUE TITLE
[libpq] build failure

### ISSUE THREAD

**Issue by diehard2** [microsoft/vcpkg#30812]
### Operating system

CentOS 8 /AlmaLinux 8

### Compiler

GCC 8.5.0 20210514

### Steps to reproduce the behavior

```Shell
Build and run the following docker container

FROM almalinux:8.7-20230407

RUN dnf update -y \
    && dnf groupinstall -y "Development Tools" \
    && yum install -y perl-CPAN \
    && cpan IPC::Cmd \
    && git clone https://github.com/Microsoft/vcpkg.git \
    && vcpkg/bootstrap-vcpkg.sh

RUN vcpkg/vcpkg install openssl:x64-linux-dynamic

RUN vcpkg/vcpkg install libpq:x64-linux-dynamic
```

### Failure logs

-- Getting CMake variables for x64-linux-dynamic-rel
-- Generating configure for x64-linux-dynamic
-- Finished generating configure for x64-linux-dynamic
-- Configuring x64-linux-dynamic-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/bash -c "V=1 ././configure  \"--disable-nls\" \"--with-openssl\" \"--with-zlib\" \"--without-zstd\" \"--without-icu\" \"--with-lz4\" \"--without-readline\" \"--without-libxml\" \"--without-libxslt\" \"--without-python\" \"--disable-silent-rules\" \"--verbose\" \"--enable-shared\" \"--disable-static\" \"--enable-debug\" \"DYLD_FALLBACK_LIBRARY_PATH=/vcpkg/installed/x64-linux-dynamic/debug/lib:/vcpkg/installed/x64-linux-dynamic/lib\" \"--prefix=/vcpkg/installed/x64-linux-dynamic/debug\" \"--bindir=\\${prefix}/../tools/libpq/debug/bin\" \"--sbindir=\\${prefix}/../tools/libpq/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/libpq\""
    Working Directory: /vcpkg/buildtrees/libpq/x64-linux-dynamic-dbg
    Error code: 1
    See logs for more information:
      /vcpkg/buildtrees/libpq/config-x64-linux-dynamic-dbg-config.log
      /vcpkg/buildtrees/libpq/config-x64-linux-dynamic-dbg-out.log
      /vcpkg/buildtrees/libpq/config-x64-linux-dynamic-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:829 (vcpkg_execute_required_process)
  ports/libpq/portfile.cmake:307 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)

the error log is

configure: WARNING: unrecognized options: --disable-silent-rules, --enable-shared, --disable-static
configure: error:
Could not execute a simple test program.  This may be a problem
related to locating shared libraries.  Check the file 'config.log'
for the exact reason.

### Additional context

This is for the dynamic linux triplet. This is working in ubuntu. In CentOS8 or AlmaLinux 8 it is failing. The static build works. The dockerfile reproduces the error.

**Comment by dg0yt** [comment]
~~~
See logs for more information:
/vcpkg/buildtrees/libpq/config-x64-linux-dynamic-dbg-config.log
/vcpkg/buildtrees/libpq/config-x64-linux-dynamic-dbg-out.log
/vcpkg/buildtrees/libpq/config-x64-linux-dynamic-dbg-err.log
~~~

Would help to see which runtime library is missing.

**Comment by diehard2** [comment]
[config-x64-linux-dynamic-dbg-config.log](https://github.com/microsoft/vcpkg/files/11228725/config-x64-linux-dynamic-dbg-config.log)

[config-x64-linux-dynamic-dbg-err.log](https://github.com/microsoft/vcpkg/files/11228731/config-x64-linux-dynamic-dbg-err.log)
[config-x64-linux-dynamic-dbg-out.log](https://github.com/microsoft/vcpkg/files/11228733/config-x64-linux-dynamic-dbg-out.log)

There's nothing obvious in the logs about it missing anything (that I can see). but things look to be going horribly wrong in the configuration

**Comment by dg0yt** [comment]
~~~
configure:18002: checking test program
configure:18012: /usr/bin/cc -o conftest -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -fPIC -g  -D_GNU_SOURCE -I/vcpkg/installed/x64-linux-dynamic/debug/lib/pkgconfig/../../../include  -L/vcpkg/installed/x64-linux-dynamic/debug/lib -L/vcpkg/installed/x64-linux-dynamic/debug/lib/pkgconfig/../../lib  conftest.c -L/vcpkg/installed/x64-linux-dynamic/debug/lib/pkgconfig/../../lib -llz4d  -L/vcpkg/installed/x64-linux-dynamic/debug/lib/pkgconfig/../../lib -lssl  -L/vcpkg/installed/x64-linux-dynamic/debug/lib/pkgconfig/../../lib -lcrypto  -L/vcpkg/installed/x64-linux-dynamic/debug/lib/pkgconfig/../../lib -lz  -lpthread -lrt -ldl -lm  >&5
configure:18012: $? = 0
configure:18012: ./conftest
./conftest: error while loading shared libraries: liblz4d.so: cannot open shared object file: No such file or directory
~~~
I expected something like this. There is already `DYLD_FALLBACK_LIBRARY_PATH` for osx. We either need something similar for other non-windows, or simply always force libpq into cross-build mode.

**Comment by cbrl** [comment]
I'm seeing the same error in CentOS Stream 8.

@diehard2, you can fix the compiler version issue by exporting the CC and CXX environment variables so that they point to the correct compiler. E.g.
```bash
scl enable gcc-toolset-12 bash
export CC=$(which gcc)
export CXX=$(which g++)
```

**Comment by cbrl** [comment]
As a temporary fix, adding `$VCPKG_ROOT/installed/x64-linux-dynamic/lib` and `$VCPKG_ROOT/installed/x64-linux-dynamic/debug/lib` to `LD_LIBRARY_PATH` will prevent the error.

**Comment by dg0yt** [comment]
The lz4d.so is covered in #30099.
