### ISSUE TITLE
vcpkg/vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static CMake Error 

### ISSUE THREAD

**Issue by z171262221** [microsoft/vcpkg#30814]
### Operating system

Windows 11 Git Bash

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
vcpkg/vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static
```

### Failure logs

$ vcpkg/vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static
Computing installation plan...
The following packages will be built and installed:
  * libjpeg-turbo[core]:x64-windows-static -> 2.0.6#2
    libvpx[core]:x64-windows-static -> 1.10.0#2
    libyuv[core]:x64-windows-static -> 2021-04-15
    opus[core]:x64-windows-static -> 1.3.1#6
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows-static...
Restored 0 packages from C:\Users\zhaoyg\AppData\Local\vcpkg\archives in 254.2 us. Use --debug to see more details.
Starting package 1/4: libjpeg-turbo:x64-windows-static
Building package libjpeg-turbo[core]:x64-windows-static...
-- Using cached libjpeg-turbo-libjpeg-turbo-10ba6ed3365615ed5c2995fe2d240cb2d5000173.tar.gz.
-- Cleaning sources at D:/RustDesk/vcpkg/buildtrees/libjpeg-turbo/src/b2d5000173-96baffe5bc.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/RustDesk/vcpkg/downloads/libjpeg-turbo-libjpeg-turbo-10ba6ed3365615ed5c2995fe2d240cb2d5000173.tar.gz
-- Applying patch add-options-for-exes-docs-headers.patch
-- Applying patch workaround_cmake_system_processor.patch
-- Applying patch fix-incompatibility-for-c11-c17.patch
-- Using source at D:/RustDesk/vcpkg/buildtrees/libjpeg-turbo/src/b2d5000173-96baffe5bc.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Fixing pkgconfig file: D:/RustDesk/vcpkg/packages/libjpeg-turbo_x64-windows-static/lib/pkgconfig/libjpeg.pc
-- Fixing pkgconfig file: D:/RustDesk/vcpkg/packages/libjpeg-turbo_x64-windows-static/lib/pkgconfig/libturbojpeg.pc
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst;https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst;https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst;https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst -> msys-mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst...
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst
[DEBUG] Downloading https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst
[DEBUG] Downloading https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst
[DEBUG] Downloading https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst
[DEBUG] Downloading https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst
[DEBUG] Downloading https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst
[DEBUG] Download failed -- retrying after 1000 ms.
[DEBUG] Download failed -- retrying after 2000 ms.
[DEBUG] Download failed -- retrying after 4000 ms.
[DEBUG] Downloading https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst
[DEBUG] Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst
Error: Failed to download from mirror set:
https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: failed: status code 404
https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: failed: status code 404
https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: failed: status code 404
https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: failed: status code 404
https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: failed: status code 404
https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: WinHttpSendRequest() failed: 12007
https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: WinHttpSendRequest() failed: 12007
https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: WinHttpSendRequest() failed: 12007
https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: WinHttpSendRequest() failed: 12007
https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: failed: status code 404
https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: failed: status code 404

[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(656)
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 4 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 5282 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 16.92 s (16813397 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):

      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. You proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:309 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_acquire_msys.cmake:84 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_acquire_msys.cmake:174 (z_vcpkg_acquire_msys_download_package)
  scripts/cmake/vcpkg_find_acquire_program.cmake:547 (vcpkg_acquire_msys)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:198 (vcpkg_find_acquire_program)
  ports/libjpeg-turbo/portfile.cmake:74 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:142 (include)

Error: Building package libjpeg-turbo:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libjpeg-turbo
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libjpeg-turbo]+Build+error
including:
  package: libjpeg-turbo[core]:x64-windows-static -> 2.0.6#2
    vcpkg-tool version: 2021-11-24-48b94a6946b8a70abd21529218927fd478d02b6c
    vcpkg-scripts version: 5ddd7f026 2021-12-01 (1 year, 4 months ago)

Additionally, attach any relevant sections from the log files above.

### Additional context

Vcpkg support is required when compiling Rustdesk, and his official requirements are as follows：
  git clone https://github.com/microsoft/vcpkg
  cd vcpkg
  git checkout 2021.12.01
  cd ..
  vcpkg/bootstrap-vcpkg.bat
  export VCPKG_ROOT=$PWD/vcpkg
  vcpkg/vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static

**Comment by dg0yt** [comment]
mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst is gone.

vcpkg needs #29067.

**Comment by JonLiu1993** [comment]
This issue could be reproduced with vcpkg 2021-11-24-48b94a6946b8a70abd21529218927fd478d02b6c and VS2022 17.5.4

````
[DEBUG] Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst
Error: Failed to download from mirror set:
https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: failed: status code 404
https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: failed: status code 404
https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: failed: status code 404
https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: failed: status code 404
https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: failed: status code 404
https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: WinHttpSendRequest() failed: 12007
https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: WinHttpSendRequest() failed: 12007
https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: WinHttpSendRequest() failed: 12007
https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: WinHttpSendRequest() failed: 12007
https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: failed: status code 404
https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst: failed: status code 404

[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(656)
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 2 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 1936 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 15.7 s (15696090 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):

      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. You proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
````

**Comment by dg0yt** [comment]
It will affect all new builds of ports using `vcpkg_fixup_pkgconfig` unless the msys2 package is already in assets cache. 
It will be a major problem for users...

**Comment by dg0yt** [comment]
> git checkout 2021.12.01

> This issue could be reproduced with vcpkg 2021-11-24-48b94a6946b8a70abd21529218927fd478d02b6c

So the actual problem is an outdated vcpkg repo: The current version of the scripts fetches mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.

**Comment by JonLiu1993** [comment]
> > git checkout 2021.12.01
> 
> > This issue could be reproduced with vcpkg 2021-11-24-48b94a6946b8a70abd21529218927fd478d02b6c
> 
> So the actual problem is an outdated vcpkg repo: The current version of the scripts fetches mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.

Yes, these ports can be installed normally in the latest vcpkg.
````
Stored binaries in 1 destinations.
Elapsed time to handle opus:x64-windows-static: 20 s
Total install time: 5.8 min
libvpx provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(unofficial-libvpx CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::libvpx::libvpx)

libyuv provides CMake targets:

    find_package(libyuv CONFIG REQUIRED)
    target_link_libraries(main PRIVATE yuv)

    # WARNING
    # You are using MSVC to compile libyuv, which results in a very slow library.
    # MSVC won't compile any of the acceleration codes.
    # See workarounds: https://github.com/microsoft/vcpkg/issues/28446

opus provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(Opus CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Opus::opus)

PS F:\test\vcpkg> ./vcpkg --version
vcpkg package management program version 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895

See LICENSE.txt for license information.
````

**Comment by z171262221** [comment]
> > > git checkout 2021.12.01
> > 
> > 
> > > This issue could be reproduced with vcpkg 2021-11-24-48b94a6946b8a70abd21529218927fd478d02b6c
> > 
> > 
> > So the actual problem is an outdated vcpkg repo: The current version of the scripts fetches mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
> 
> Yes, these ports can be installed normally in the latest vcpkg.
> 
> ```
> Stored binaries in 1 destinations.
> Elapsed time to handle opus:x64-windows-static: 20 s
> Total install time: 5.8 min
> libvpx provides CMake targets:
> 
>     # this is heuristically generated, and may not be correct
>     find_package(unofficial-libvpx CONFIG REQUIRED)
>     target_link_libraries(main PRIVATE unofficial::libvpx::libvpx)
> 
> libyuv provides CMake targets:
> 
>     find_package(libyuv CONFIG REQUIRED)
>     target_link_libraries(main PRIVATE yuv)
> 
>     # WARNING
>     # You are using MSVC to compile libyuv, which results in a very slow library.
>     # MSVC won't compile any of the acceleration codes.
>     # See workarounds: https://github.com/microsoft/vcpkg/issues/28446
> 
> opus provides CMake targets:
> 
>     # this is heuristically generated, and may not be correct
>     find_package(Opus CONFIG REQUIRED)
>     target_link_libraries(main PRIVATE Opus::opus)
> 
> PS F:\test\vcpkg> ./vcpkg --version
> vcpkg package management program version 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895
> 
> See LICENSE.txt for license information.
> ```



> > > git checkout 2021.12.01
> > 
> > 
> > > This issue could be reproduced with vcpkg 2021-11-24-48b94a6946b8a70abd21529218927fd478d02b6c
> > 
> > 
> > So the actual problem is an outdated vcpkg repo: The current version of the scripts fetches mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
> 
> Yes, these ports can be installed normally in the latest vcpkg.
> 
> ```
> Stored binaries in 1 destinations.
> Elapsed time to handle opus:x64-windows-static: 20 s
> Total install time: 5.8 min
> libvpx provides CMake targets:
> 
>     # this is heuristically generated, and may not be correct
>     find_package(unofficial-libvpx CONFIG REQUIRED)
>     target_link_libraries(main PRIVATE unofficial::libvpx::libvpx)
> 
> libyuv provides CMake targets:
> 
>     find_package(libyuv CONFIG REQUIRED)
>     target_link_libraries(main PRIVATE yuv)
> 
>     # WARNING
>     # You are using MSVC to compile libyuv, which results in a very slow library.
>     # MSVC won't compile any of the acceleration codes.
>     # See workarounds: https://github.com/microsoft/vcpkg/issues/28446
> 
> opus provides CMake targets:
> 
>     # this is heuristically generated, and may not be correct
>     find_package(Opus CONFIG REQUIRED)
>     target_link_libraries(main PRIVATE Opus::opus)
> 
> PS F:\test\vcpkg> ./vcpkg --version
> vcpkg package management program version 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895
> 
> See LICENSE.txt for license information.
> ```

$ git checkout 48b94a6946b8a70abd21529218927fd478d02b6c
fatal: reference is not a tree: 48b94a6946b8a70abd21529218927fd478d02b6c
I didn't get this version, what do I need to do? Thank you!

**Comment by JonLiu1993** [comment]
@z171262221, Your vcpkg is out of date, use the `git pull` command to get the latest version in vcpkg and try again.
````
vcpkg-tool version: 2021-11-24-48b94a6946b8a70abd21529218927fd478d02b6c
vcpkg-scripts version: https://github.com/microsoft/vcpkg/commit/5ddd7f02689b7c5aab78711d77f61db5d2e5e79c 2021-12-01 (1 year, 4 months ago)
````

**Comment by z171262221** [comment]
Okay, the installation was successful, and the target program has been compiled successfully. Thank you very much!

**Comment by jiangshunke** [comment]
> @jiangshunke, Yes, use command "git pull" get the latest vcpkg.

I've also been distracted by this question; Now I re-pull VCPKG latest git I don't switch branches to try! Thank you!
