### ISSUE TITLE
[imgui] build with `#define IMGUI_API __declspec( dllimport )`

### ISSUE THREAD

**Issue by robbiefish** [microsoft/vcpkg#30837]
### Is your feature request related to a problem? Please describe.

I would like to build imgui into a dll and then allow the functions to be accessed from another dll (along with my own functions). Uncommenting [this line](https://github.com/ocornut/imgui/blob/a1b8457cb5c9238f47fc7616e84c0775412ce556/imconfig.h#L26) in `imconfig.h` before build and then recommenting it after installation allows me to acheive the desired behavior because the resulting `.lib` file will have the required exported symbols

### Proposed solution

I have implemented this as a feature named `dllexport` in my fork [here](https://github.com/LORD-MicroStrain/vcpkg/commit/ba602d76772528f8f0b238f1b6d036c2ffb63d77)

### Describe alternatives you've considered

Compiling imgui as a shared library with `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` set to `ON`, would also solve this problem, but after messing around with this, it appeared to breakd several downstream packages

### Additional context

I have only recently become familiar with how the Windows linker works, and I may be missing a simpler solution.

If this is acceptable, I would also be interested in implementing something similar for `implot`

**Comment by JonLiu1993** [comment]
@robbiefish, Thanks for posting this issue, Could you please submit a PR to solve this issue?
