### ISSUE TITLE
[curl] build failure due to download failed

### ISSUE THREAD

**Issue by Teylusu** [microsoft/vcpkg#30841]
### Operating system

Windows 11

### Steps to reproduce the behavior

```Shell
./vcpkg install teemo:x86-windows
```

### Failure logs

error: Failed to download from mirror set
error: https://github.com/curl/curl/archive/curl-8_0_1.tar.gz: WinHttpSendRequest failed with exit code 12002
error: https://github.com/curl/curl/archive/curl-8_0_1.tar.gz: WinHttpSendRequest failed with exit code 12002
error: https://github.com/curl/curl/archive/curl-8_0_1.tar.gz: WinHttpSendRequest failed with exit code 12002
error: https://github.com/curl/curl/archive/curl-8_0_1.tar.gz: WinHttpSendRequest failed with exit code 12002
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(961):
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 6us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 2066us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 2.4 min (145260879us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/curl/portfile.cmake:2 (vcpkg_from_github)
  scripts/ports.cmake:147 (include)

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Could you work around this issue as following steps:

1. Download https://github.com/curl/curl/archive/curl-8_0_1.tar.gz manually.
2. Rename it to curl-curl-curl-8_0_1.tar.gz, and put it to .\vcpkg\downloads\
3. Try to build again.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
