### ISSUE TITLE
[New Port Request] IUP

### ISSUE THREAD

**Issue by bauripalash** [microsoft/vcpkg#30843]
### Library name

IUP 

### Library description

IUP is a multi-platform toolkit for building graphical user interfaces

### Source repository URL

https://sourceforge.net/p/iup/iup/

### Project homepage (if different from the source repository)

https://www.tecgraf.puc-rio.br/iup/

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

IUP is an easy to use lightweight GUI framework for building cross platform GUIs.
Works perfectly fine on windows as well as linux, I have tested both on windows MSVC, MinGW as well linux gcc and clang, it is quite easy to setup and easy to write GUI projects in.

**Comment by ethindp** [comment]
I also would like to see this added.

**Comment by nilsantonsson** [comment]
Yes, please add IUP! 👍
