### ISSUE TITLE
[New Port Request] OpenXR-Toolkit

### ISSUE THREAD

**Issue by RainbowTaro2022** [microsoft/vcpkg#30877]
### Library name

OpenXR-Toolkit

### Library description

A collection of useful features to customize and improve existing OpenXR applications.

### Source repository URL

https://github.com/mbucchia/OpenXR-Toolkit

**Comment by mbucchia** [comment]
I'm the author of that tool. I don't understand what bringing it to vcpkg would do at all?

OpenXR toolkit is a standalone application, not a library.

**Comment by RainbowTaro2022** [comment]
哦，好吧
