### ISSUE TITLE
[poco] build failure

### ISSUE THREAD

**Issue by heheda123123** [microsoft/vcpkg#30885]
### Operating system

windows 11

### Steps to reproduce the behavior

```Shell
`vcpkg install 'poco[mysql]:x64-windows-static'`
```

### Failure logs

```
(base) PS C:\Users\Administrator> vcpkg install 'poco[mysql]:x64-windows-static'
Computing installation plan...
The following packages will be built and installed:
    poco[core,mysql]:x64-windows-static -> 1.12.4#4
Detecting compiler hash for triplet x64-windows-static...
Restored 0 package(s) from C:\Users\Administrator\AppData\Local\vcpkg\archives in 225 us. Use --debug to see more details.
Installing 1/1 poco:x64-windows-static...
Building poco[core,mysql]:x64-windows-static...
-- Using cached pocoproject-poco-1211613642269b7d53bea58b02de7fcd25ece3b9.tar.gz.
-- Cleaning sources at C:/vcpkg-dir/vcpkg/buildtrees/poco/src/cd25ece3b9-089ebeb171.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg-dir/vcpkg/downloads/pocoproject-poco-1211613642269b7d53bea58b02de7fcd25ece3b9.tar.gz
-- Applying patch 0001-static-pcre.patch
-- Applying patch 0002-arm64-pcre.patch
-- Applying patch 0003-fix-dependency.patch
-- Applying patch 0004-fix-feature-sqlite3.patch
-- Applying patch 0005-fix-error-c3861.patch
-- Applying patch 0007-find-pcre2.patch
-- Using source at C:/vcpkg-dir/vcpkg/buildtrees/poco/src/cd25ece3b9-089ebeb171.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/vcpkg-dir/vcpkg/buildtrees/poco/x64-windows-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg-dir\vcpkg\buildtrees\poco\config-x64-windows-static-dbg-CMakeCache.txt.log
      C:\vcpkg-dir\vcpkg\buildtrees\poco\config-x64-windows-static-rel-CMakeCache.txt.log
      C:\vcpkg-dir\vcpkg\buildtrees\poco\config-x64-windows-static-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:248 (vcpkg_execute_required_process)
  ports/poco/portfile.cmake:52 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)


error: building poco:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+poco
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[poco]+Build+error&body=Copy+issue+body+from+C%3A%2Fvcpkg-dir%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
```

**Comment by jimwang118** [comment]
I have not reproduced this issue locally. Can you provide the detailed config-x64-windows-static-out.log?

**Comment by jimwang118** [comment]
Is the issue I reproduced locally the same as yours?
[config-x64-windows-static-out.log](https://github.com/microsoft/vcpkg/files/11340758/config-x64-windows-static-out.log)

**Comment by heheda123123** [comment]
不好意思忘记回复了，因为这个每次复现都太费时间了，需要把openssl boost全部编译一次
看起来是一样的错误
[config-x64-windows-static-out.log](https://github.com/microsoft/vcpkg/files/11340805/config-x64-windows-static-out.log)

**Comment by jimwang118** [comment]
After checking the upstream compilation script, `libmysql` can only compile dynamic libraries, not static libraries, so if you use triplet `x64-windows-static` to compile, delete the dynamic library and lib of `libmysql` in `vcpkg portfile.cmake`. Failed because libmysql.lib could not be found.

**Comment by heheda123123** [comment]
可以编译静态库把，我看conan和xrepo都有对应的编译脚本，也可以编译成功
https://github.com/xmake-io/xmake-repo/blob/master/packages/m/mysql/xmake.lua
![image](https://github.com/microsoft/vcpkg/assets/97490782/431a7d9d-78b2-4ea8-9390-6e663826451e)
![image](https://github.com/microsoft/vcpkg/assets/97490782/0172c0b4-280d-47fc-824e-21692c31fb5b)

**Comment by jimwang118** [comment]
`mysqlclient `and `libmysql `are not the same library, you can check `libmysql/cmakelists.txt`, where to compile `mysqlclient` call `MERGE_CONVENIENCE_LIBRARIES(mysqlclient ${LIBS_TO_MERGE}`, the function is always statically compiled, and when compiling `libmysql `call `MERGE_LIBRARIES_SHARED(libmysql ${LIBS_TO_MERGE}` , this macro function has always been dynamically compiled, so the compiled `libmysql `has always been a dynamic library, and `mysqlclient `has always been a static library.
