### ISSUE TITLE
[openssl] Use x86-windows-static to test RSA for errors.

### ISSUE THREAD

**Issue by nblwdlt** [microsoft/vcpkg#30917]
**Environment**
-Operating system: windows10 x64
-Compiler: Visual Studio Community 2022: Version 17.5.4

**Copy**
Steps to reproduce behavior:
1. vcpkg install openssl:x86-windows-static
2. Create a console application using vs2022.
3. Directly using EVP_ PKEY_ RSA_ Compile keygen. c and applink. c
4. Prompt error message:

```c++
Rebuild started...
1>------ Rebuild All started: Project: ConsoleApplication1, Configuration: Release Win32 ------
1>applink.c
1>EVP_PKEY_RSA_keygen.c
1>   Creating library D:\Codes\vs\ConsoleApplication1\Release\ConsoleApplication1.lib and object D:\Codes\vs\ConsoleApplication1\Release\ConsoleApplication1.exp
1>libcrypto.lib(libcrypto-lib-e_capi.obj) : error LNK2001: unresolved external symbol __imp__CertOpenStore@20
1>libcrypto.lib(libcrypto-lib-e_capi.obj) : error LNK2001: unresolved external symbol __imp__CertCloseStore@8
1>libcrypto.lib(libcrypto-lib-e_capi.obj) : error LNK2001: unresolved external symbol __imp__CertEnumCertificatesInStore@8
1>libcrypto.lib(libcrypto-lib-e_capi.obj) : error LNK2001: unresolved external symbol __imp__CertFindCertificateInStore@24
1>libcrypto.lib(libcrypto-lib-e_capi.obj) : error LNK2001: unresolved external symbol __imp__CertDuplicateCertificateContext@4
1>libcrypto.lib(libcrypto-lib-e_capi.obj) : error LNK2001: unresolved external symbol __imp__CertFreeCertificateContext@4
1>libcrypto.lib(libcrypto-lib-e_capi.obj) : error LNK2001: unresolved external symbol __imp__CertGetCertificateContextProperty@16
1>D:\Codes\vs\ConsoleApplication1\Release\ConsoleApplication1.exe : fatal error LNK1120: 7 unresolved externals
1>Done building project "ConsoleApplication1.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
========== Rebuild started at 6:32 PM and took 00.633 seconds ==========
```

**Comment by nblwdlt** [comment]
If I use x86 windows, there will be no generation errors。

**Comment by 6ziv** [comment]
@nblwdlt Maybe we should let the project use "/MT" instead of "/MD", or use community triplet x86-windows-static-md?

**Comment by nblwdlt** [comment]
I am using Multi-threaded (/MT)。
![2](https://user-images.githubusercontent.com/28042864/232471908-e50c27a3-f807-41d4-aed3-ede6d120d29f.png)
![3](https://user-images.githubusercontent.com/28042864/232471927-8ab395e0-4763-40ef-9773-55632a547286.png)
![1](https://user-images.githubusercontent.com/28042864/232471969-e3b8229c-79a5-4da3-b987-b88f839fcf15.png)
![4](https://user-images.githubusercontent.com/28042864/232471988-68fb0d13-da83-493f-b954-ef6d01353e7f.png)

**Comment by 6ziv** [comment]
> @6ziv I am using Multi-threaded (/MT)。 ![2](https://user-images.githubusercontent.com/28042864/232471908-e50c27a3-f807-41d4-aed3-ede6d120d29f.png) ![3](https://user-images.githubusercontent.com/28042864/232471927-8ab395e0-4763-40ef-9773-55632a547286.png) ![1](https://user-images.githubusercontent.com/28042864/232471969-e3b8229c-79a5-4da3-b987-b88f839fcf15.png) ![4](https://user-images.githubusercontent.com/28042864/232471988-68fb0d13-da83-493f-b954-ef6d01353e7f.png)

Oh i see. Just find a seat and tested.
Seems vcpkg with VS cannot auto detect used compenents, so it cannot automatically link ws2_32.lib and Crypt32.lib.
(And we can simply merge them into openssl library, or there may be tons of conflicts.)
Guess we should add them into linker inputs, or use pragma(lib,"library_name.lib") in any cpp file to direct the linker?

**Comment by nblwdlt** [comment]
@6ziv Thank you.非常感谢

**Comment by jimwang118** [comment]
@nblwdlt Does the suggested method of using 6ziv solve your problem? Let me know if it can be solved and I will close this issue.

**Comment by nblwdlt** [comment]
@jimwang118 I have solved the problem using the 6ziv method, thank you very much.
