### ISSUE TITLE
Missing osx folder when export on MacOS

### ISSUE THREAD

**Issue by ahmedyarub** [microsoft/vcpkg#30910]
vcpkg/scripts/buildsystems/osx is not copied to exported archive which results in build failures when building an application that uses vcpkg libraries. Copying the folder manually fixes the problem. I also noticed that msbuild folder is copied and I'm not sure whether that behavior is correct.

**Environment**

- OS: MacOS
- Compiler: AppleClang 13

**To Reproduce**
1. Install some libraries and export them on MacOS.
2. Attempting to use the exported version of vcpkg throws an error related to not finding osx folder contents.

**Expected behavior**
The folder is included and building should be successfull.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Could you please provide the related error message?
According to [export](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/commands/export.md#description) documentation, the scripts folder is for storing integration files, it contains [CMake toolchain](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/users/buildsystems/cmake-integration.md) or [MSBuild props/targets](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/users/buildsystems/msbuild-integration.md).

**Comment by ahmedyarub** [comment]
Here is the exact error message:

> /Library/Frameworks/Python.framework/Versions/3.11/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/runner/work/cloud_companion/cloud_companion/x64-osx-shared-release/vcpkg/scripts/buildsystems/osx/applocal.py': [Errno 2] No such file or directory

> According to [export](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/commands/export.md#description) documentation, the scripts folder is for storing integration files, it contains [CMake toolchain](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/users/buildsystems/cmake-integration.md) or [MSBuild props/targets](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/users/buildsystems/msbuild-integration.md).

Well that seems to be wrong. There is a folder called osx as you can see above and it is not being exported. Once I add it manually everything works. Btw I'm working on a cross-platform application which targets Windows, Linux, MacOS, Emscripten, Android, and iOS and so far I'm only facing this problem with the OSX version.

**Comment by FrankXie05** [comment]
@ahmedyarub Could you please test my PR https://github.com/microsoft/vcpkg-tool/pull/1028 ?

**Comment by FrankXie05** [comment]
Fixed by PR https://github.com/microsoft/vcpkg-tool/pull/1028

**Comment by FrankXie05** [comment]
Waiting for `vcpkg-tool` update.
