### ISSUE TITLE
[gstreamer] does not play video with current version

### ISSUE THREAD

**Issue by DougRogers** [microsoft/vcpkg#30934]
I recently updated gstreamer and videos no longer play. 
The "playbin" plugin does not get loaded which causes the videos to fail.

This test case shows the issue.  It will call __debugbreak if it fails.

`int main(int argc, char *argv[])
{

    GstBus *bus;
    GstStateChangeReturn ret;
    gint flags;
    GIOChannel *io_stdin;

    /* Initialize GStreamer */
    gst_init(&argc, &argv);

    /* Create the elements */
    auto playbin = gst_element_factory_make("playbin", "playbin");

    if (!playbin)
    {
        __debugbreak();
    }
    return 0;
}`

My install is 

`vcpkg install gstreamer[core,dtls,gpl,libde265,mpg123,speex,vpx,taglib,webp,faad,openh264,openmpt,plugins-base,plugins-bad,plugins-good,plugins-ugly,openjpeg,jpeg,png]:x64-windows  --recurse
`

**Comment by Cheney-W** [comment]
Thanks for reporting this issue. About your repro code, what header files do you include?
Also, do you directly create tests in a C++project in Visual Studio after run `vcpkg integrate install` or do you use cmake project for testing?

**Comment by DougRogers** [comment]
`#include <gst/gst.h>`

I am using code directly in Visual Studio.

**Comment by DougRogers** [comment]
`vcpkg integrate install` had no effect

**Comment by Cheney-W** [comment]
After installed `gstreamer` by vcpkg, the header files saved in vcpkg\installed\{triplet}\include\gstreamer-1.0\gst, this means that if `vcpkg integrate install` is executed, then `vcpkg\installed\{triplet}\include` will be added into the Include Directories. This causes `fatal  error C1083: Cannot open include file: 'gst/gst.h'` occurs when using `#include <gst/gst.h>`.
So I want to know, did you manually add the corresponding include, lib, and DLL paths to your project?
If possible, could you please send me your reproduction project? Thank you!

**Comment by DougRogers** [comment]
Attach is a complete repro project   Only debug mode is setup.
[tstGstreamer.zip](https://github.com/microsoft/vcpkg/files/11268764/tstGstreamer.zip)

**Comment by Cheney-W** [comment]
Thanks for your reply! I could reproduce this issue in my side now. 
Could you please provide the specific version of this port or the date when it was previously available?
Additionally, is this issue present in the upstream?

**Comment by DougRogers** [comment]
Here is a simple test case that could be added to the validation suite for gstreamer.

https://gstreamer.freedesktop.org/documentation/tutorials/basic/hello-world.html

**Comment by DougRogers** [comment]
The gst-inspect tool, should be listing all the plugins, but they are not.

https://gstreamer.freedesktop.org/documentation/tools/gst-inspect.html

```
>gst-inspect-1.0.exe
staticelements:  bin: Generic bin
staticelements:  pipeline: Pipeline object

Total count: 1 plugin, 2 features
```

**Comment by DougRogers** [comment]
My application is dependent on this library, so I hope this can be resolved soon.

**Comment by DougRogers** [comment]
It looks like libraries are not being created.
Here is a snapshot of my app from before and the current version.  I copy the contents of the release build library to my executable path.  The old version has more libraries that are not created currently.

[oldBuild.txt](https://github.com/microsoft/vcpkg/files/11290737/oldBuild.txt)

[newBuild.txt](https://github.com/microsoft/vcpkg/files/11290738/newBuild.txt)

**Comment by DougRogers** [comment]
Some  if not all, of the plugins are not being built

Source is here:
\vcpkg\buildtrees\gstreamer\src\1.20.5-a6a8a0db6f.clean\subprojects\gst-plugins-good\gst

\vcpkg\buildtrees\gstreamer\src\1.20.5-a6a8a0db6f.clean\subprojects\gst-plugins-base\gst

**Comment by DougRogers** [comment]
gstmatroska.dll is built, but copied to a subdirectory, `vcpkg\installed\x64-windows\debug\plugins\gstreamer` not the expected `vcpkg\installed\x64-windows\debug\bin`

**Comment by Cheney-W** [comment]
> gstmatroska.dll is built, but copied to a subdirectory, vcpkg\installed\x64-windows\debug\plugins\gstreamer not the expected vcpkg\installed\x64-windows\debug\bin

This change is due to the PR https://github.com/microsoft/vcpkg/pull/30817.

Can adding `vcpkg\installed\x64-windows\debug\plugins\gstreamer` manually to the APTH environment variable of your project solve this problem?

**Comment by DougRogers** [comment]
Location of libraries has changed and I didn’t realize it.  I can copy libs from new location  and it works.
