### ISSUE TITLE
Filesystem registry schema is missing baseline property

### ISSUE THREAD

**Issue by davidmatson** [microsoft/vcpkg#30939]
**Describe the bug**
The [JSON schema for a custom filesystem registry](https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg-schema-definitions.schema.json) is missing a property for "baseline". [Docs](https://learn.microsoft.com/en-us/vcpkg/reference/vcpkg-configuration-json#registry) indicate that this property is required. I assume the docs are correct - without this property, it's not clear how vcpkg would know which baseline to choose from the baseline.json file.

**Comment by LilyWangLL** [comment]
This [vcpkg-schema-definitions.schema.json](https://github.com/microsoft/vcpkg-tool/blob/main/docs/vcpkg-schema-definitions.schema.json) file added by Billy. cc @BillyONeal Could you please take a look this issue? Thanks in advance.

**Comment by davidmatson** [comment]
I tested to confirm, and the "baseline" property is indeed required for filesystem registries, as the docs indicate. Without it, I get this error:
```
1>The dependency was not found in the baseline, indicating that the package did not exist at that time. This may be fixed by providing an explicit override version via the "overrides" field or by updating the baseline.
```

**Comment by BillyONeal** [comment]
Code: Optional: https://github.com/microsoft/vcpkg-tool/blob/785af0d180135ea93077c364445e879eb75dd1b4/src/vcpkg/configuration.cpp#L258

Schema: Not Allowed: https://github.com/microsoft/vcpkg-tool/blob/785af0d180135ea93077c364445e879eb75dd1b4/docs/vcpkg-schema-definitions.schema.json#L354-L375

Docs: Required: https://learn.microsoft.com/en-us/vcpkg/reference/vcpkg-configuration-json#registry-baseline

**Comment by BillyONeal** [comment]
> I tested to confirm, and the "baseline" property is indeed required for filesystem registries, as the docs indicate. Without it, I get this error:
> 
> ```
> 1>The dependency was not found in the baseline, indicating that the package did not exist at that time. This may be fixed by providing an explicit override version via the "overrides" field or by updating the baseline.
> ```

This can be avoided as long as there is some other constraint to choose the version to use, or `overrides`. It is clearly better to require it, but filesystem registries have been shipping in optional form for long enough that I think at this point the right thing to do is to just fix the docs to say what the product actually does

**Comment by BillyONeal** [comment]
> Schema: Not Allowed: https://github.com/microsoft/vcpkg-tool/blob/785af0d180135ea93077c364445e879eb75dd1b4/docs/vcpkg-schema-definitions.schema.json#L354-L375

Fixed in https://github.com/microsoft/vcpkg-tool/pull/1463

> Docs: Required: https://learn.microsoft.com/en-us/vcpkg/reference/vcpkg-configuration-json#registry-baseline

Clarified to be optional in https://github.com/microsoft/vcpkg-docs/pull/372

**Comment by davidmatson** [comment]
Thanks, @BillyONeal!
