### ISSUE TITLE
[<port name>] build failure

### ISSUE THREAD

**Issue by baruaole** [microsoft/vcpkg#30947]
### Operating system

Linux ubuntu 20.04

### Steps to reproduce the behavior

```Shell
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
./bootstrap-vcpkg.sh
./vcpkg integrate install
./vcpkg install pangolin
```

### Failure logs

![Screenshot from 2023-04-18 05-02-40](https://user-images.githubusercontent.com/104236475/232728510-488e10c1-619a-4f0a-a6c2-32c29a88f841.png)

**Comment by autoantwort** [comment]
I suggest reading the error message ;)

**Comment by JonLiu1993** [comment]
@baruaole, Thanks for posting this issue, please use `command sudo apt-get install nasm` then try again.

**Comment by JonLiu1993** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
