### ISSUE TITLE
`"."` as a relative ports directory does not work

### ISSUE THREAD

**Issue by vadi2** [microsoft/vcpkg#30942]
**Describe the bug**
My port is located in the same folder as my `vcpkg.json` file and using `"overlay-ports": ["."]` as a relative directory was not recognised:

```
  error: while loading /home/runner/work/Mudlet/Mudlet/3rdparty/our-vcpkg-dependencies/./vcpkg.json:
  $ (a manifest): missing required field 'name' (an identifier)
  $ (a manifest): expected a versioning field (one of version, version-date, version-semver, or version-string)Failed to load port hunspell from /home/runner/work/Mudlet/Mudlet/3rdparty/our-vcpkg-dependencies/.
```
 

**Environment**
- vcpkg commit d4acc3c3f2db0b9fa7fc47b4751ec5778331f996

**To Reproduce**
1. create a port directory
2. create vcpkg.json as a sibling to the port directory
3. specify `"overlay-ports": ["."]` for all ports in the current directory to be found

**Expected behavior**
Vcpkg finds the ports specified in the same directory as the `vcpkg.json` file is.

**Additional context**
I was able to work around it by specifying just the 1 port I have in the same directory as `"./portname"`

**Comment by FrankXie05** [comment]
Using "." to represent the current directory can have different meanings in different operating systems and terminal environments. 

To avoid confusion and errors, we just allow to use explicit relative or absolute paths instead of "." when specifying the path to the overlay ports directory. 

Example: 
https://github.com/microsoft/vcpkg-docs/blob/69039427fc5fb9e9310618d1e0765bd3b20fe7f0/vcpkg/reference/vcpkg-json.md#example-3

**Comment by vadi2** [comment]
> Using "." to represent the current directory can have different meanings in different operating systems and terminal environments.

Can you give examples? Pretty much everywhere I know "." means current directory, and since you already accept it in **.**/port-name I'm not grasping where the confusion could be.

**Comment by dg0yt** [comment]
IMO  `.` is a valid, explicit, relative path.

**Comment by FrankXie05** [comment]
Explain two points:

1. Regarding your question: 
>I was able to work around it by specifying just the 1 port I have in the same directory as "./portname"

We are unable to determine what you passed in when using `overlay-ports` Is there a folder or port file after (representing the current directory of the relative path) （`./my-ports/fmt` or `./team-ports`).

Therefore, a complete name must be provided.

2. Regarding the issue with.: 
>Can you give examples? Pretty much everywhere I know "." means current directory, and since you already accept it in ./port-name I'm not grasping where the confusion could be.

Yes, usually in a computer's operating system,. represents the current directory.

However, there are still some slight differences or special uses between different operating systems. 
We try to avoid encountering such situations as much as possible (Although there is a small chance of encountering it 🫤):

- The use of path separators. 

- It can also represent script files in Linux

-  In certain special cases: 
    `Windows`: Represents a hidden directory 
    `Linux`: regular directory

**Comment by dg0yt** [comment]
In the context of directory paths, `.` is a relative path pointing to the current directory.
There might be good reason to exclude the current directory, no matter how it written. But I really don't get why you want to drag a clear, non-ambiguous fact into the land of uncertainty.

> * It can also represent script files in Linux

`.` does not "represent script files in Linux".
However, `.` is also a *command* in `bash` -- and also in `powershell`. But this is another context.
There is no policy to forbid command names (e.g. `ls`) for overlay port dir names.

> * In certain special cases:
>   `Windows`: Represents a hidden directory.
>   `Linux`: regular directory

I don't know if this is wrong or if it is meant in another way.
Windows uses attributes to mark hidden files. (But I don't know how it handles `.` internally.)
On Linux and similar systems, a dot at the beginning of a filename marks a hidden file/dir. 
There is no policy to forbid hidden overlay port dirs (`e.g. .overlays`).

**Comment by BillyONeal** [comment]
This is actually intended behavior but it is somewhat unfortunate. The issue is that overlay ports can refer to one of:

1. A directory, containing other directories of port names, which are themselves overlay ports.
2. The overlay port directory itself.

You are falling into case 2: the vcpkg.json that itself is attempting to declare `overlay-ports: .`, is itself being interpreted as the overlay port. 

Put another way,

```
x/vcpkg.json # name = foo
x/a/vcpkg.json # name = a
x/b/vcpkg.json # name = b
x/c/vcpkg.json # name = c
```

setting `--overlay-ports=x` brings in the overlay port `foo`, not `a`, `b`, or `c`.

Unfortunately I think this means you need the overlays to be in a subdirectory.

**Comment by BillyONeal** [comment]
https://github.com/microsoft/vcpkg-tool/pull/1534 adds a new `"overlay-port-dirs"` option, which never considers the provided directory itself to the port, meaning `"overlay-port-dirs": ["."]` will have the effect you wanted as soon as there is a tool release with this change.

**Comment by BillyONeal** [comment]
After feedback there seems to be strong opposition to allowing `"."` here. At least we're adding a warning to prevent the going in circles.
