### ISSUE TITLE
I am trying to make a CMake configuration where I dont need to link the vcpkg manually, so I need to use VCPKG_ROOT.

### ISSUE THREAD

**Issue by doomroep5** [microsoft/vcpkg#30967]
I am trying to make a CMake configuration where I dont need to link the vcpkg manually, so I need to use VCPKG_ROOT.

However it seems that this variable cannot be found. I am using a WSL Unbuntu 20.04, do I need to manually set VCPKG_ROOT or is it something that `vcpkg integrate install` should do?

_Originally posted by @igorgsouza in https://github.com/microsoft/vcpkg/discussions/25394_

**Comment by autoantwort** [comment]
For an answer see https://github.com/microsoft/vcpkg/discussions/25394

**Comment by jimwang118** [comment]
You can solve the problem according to the solutions provided in https://github.com/microsoft/vcpkg/discussions/25394.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
