### ISSUE TITLE
[etcd-cpp-apiv3] build failure

### ISSUE THREAD

**Issue by sdeastis** [microsoft/vcpkg#30965]
### Operating system

Windows 10

### Steps to reproduce the behavior

```Shell
vcpkg install etcd-cpp-apiv3:x64-windows
```

### Failure logs

Package: abseil[core]:x64-windows -> 20230125.0#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.29.30147.0
-    vcpkg-tool version: 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895
    vcpkg-scripts version: eb8e75bb4 2023-04-18 (7 hours ago)

**To Reproduce**

`vcpkg install etcd-cpp-apiv3:x64-windows`

**Failure logs**

```
-- Using cached abseil-abseil-cpp-20230125.0.tar.gz.
-- Cleaning sources at C:/TFS/DiagnosticSW/Third-Party/vcpkg/buildtrees/abseil/src/20230125.0-ef0a6f1f30.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/TFS/DiagnosticSW/Third-Party/vcpkg/downloads/abseil-abseil-cpp-20230125.0.tar.gz
-- Applying patch fix-dll-support.patch
-- Using source at C:/TFS/DiagnosticSW/Third-Party/vcpkg/buildtrees/abseil/src/20230125.0-ef0a6f1f30.clean
CMake Error at ports/abseil/portfile.cmake:28 (vcpkg_cmake_configure):
  Unknown CMake command "vcpkg_cmake_configure".
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)



```

**Additional context**

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Did you use latest vcpkg to install `abseil`?

> CMake Error at ports/abseil/portfile.cmake:28 (vcpkg_cmake_configure):
>   Unknown CMake command "vcpkg_cmake_configure".

Missing dependency `vcpkg-cmake` will cause this error, but the dependency of `abseil` is correct.

**Comment by dg0yt** [comment]
You must update the installed port `vcpkg-cmake`. This error may come from having installed an outdated version.

**Comment by sdeastis** [comment]
I did "git pull" to update but was not working. I solved by doing a "git clean -xffd" then again "git pull". After that it compiled.
