### ISSUE TITLE
Link to static boost build

### ISSUE THREAD

**Issue by martin-s** [Microsoft/vcpkg#3097]
I have built modular boost statically (triplet x86-windows-static). Hence, installed folder links to x86-windows-static. Now, another library X is built dynamically (triplet x86-windows) which itself has a build-dependency to boost-system.

Build scenario is as follows:
`X (dynamic) -> boost-system (static)`

But if I try to build library X, there is no way to tell that boost-system should be linked statically. There are some hints to change the triplet file (_if port matches boost-system..._), but that doesn't help.
Is there any way to accomplish the build scenario? 
I would prefer a solution that works on the actual installations in installed folder. So, if there are some static libraries, they should be used. Or as another solution, in CONTROL file the "Build-Depends" allows to write it like that "boost-system (static)".

**Comment by alexkaratarakis** [comment]
>There are some hints to change the triplet file (if port matches boost-system...), but that doesn't help.

What issue do you encounter with this? If I understand your issue correctly, you can make a triplet that defaults to dynamic, and special-cases boost to build statically. 

```
# MyCustomTriplet.cmake
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_CRT_LINKAGE dynamic)
if(PORT MATCHES "boost-")
    set(VCPKG_LIBRARY_LINKAGE static)
endif()
```

**Comment by martin-s** [comment]
Starting with command:
`vcpkg install boost-thread:x86-windows-static`
I get an output in folder "x86-windows-static".

Following with next command and modified triple file:
`vcpkg install libcds:x86-windows`
I was irritated why the static folder is not used and the boost libraries are build another time. Now into folder "x86-windows". Output is finally ok, as boost is linked statically.

The open question is why the lib-files are different in size when I compare x86-windows-static vs. x86-windows folder.
For example:
- boost_chrono-vc140-mt.lib (x86-windows-static\lib) -> 1.75MB
- boost_chrono-vc140-mt.lib (x86-windows\lib) -> 1.95MB
