### ISSUE TITLE
[boost-build] build failure

### ISSUE THREAD

**Issue by unerr** [microsoft/vcpkg#30989]
### Operating system

Windows

### Steps to reproduce the behavior

```Shell
vcpkg install tgbot-cpp --triplet=x64-mingw-dynamic --host-triplet=x64-mingw-dynamic
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
    vcpkg-cmake[core]:x64-mingw-dynamic -> 2022-12-22
Detecting compiler hash for triplet x64-mingw-dynamic...
Restored 0 package(s) from C:\Users\фвьшт\AppData\Local\vcpkg\archives in 249 us. Use --debug to see more details.
Installing 1/1 vcpkg-cmake:x64-mingw-dynamic...
Building vcpkg-cmake[core]:x64-mingw-dynamic...
warning: -- Using community triplet x64-mingw-dynamic. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: F:\vcpkg\triplets\community\x64-mingw-dynamic.cmake
-- Installing: F:/vcpkg/packages/vcpkg-cmake_x64-mingw-dynamic/share/vcpkg-cmake/vcpkg_cmake_configure.cmake
-- Installing: F:/vcpkg/packages/vcpkg-cmake_x64-mingw-dynamic/share/vcpkg-cmake/vcpkg_cmake_build.cmake
-- Installing: F:/vcpkg/packages/vcpkg-cmake_x64-mingw-dynamic/share/vcpkg-cmake/vcpkg_cmake_install.cmake
-- Installing: F:/vcpkg/packages/vcpkg-cmake_x64-mingw-dynamic/share/vcpkg-cmake/vcpkg-port-config.cmake
-- Installing: F:/vcpkg/packages/vcpkg-cmake_x64-mingw-dynamic/share/vcpkg-cmake/copyright
-- Performing post-build validation
Stored binaries in 1 destinations.
Elapsed time to handle vcpkg-cmake:x64-mingw-dynamic: 222 ms
Total install time: 2.7 s

G:\Telegram Bot\tgbot-cpp>vcpkg install tgbot-cpp --triplet=x64-mingw-dynamic --host-triplet=x64-mingw-dynamic
Computing installation plan...
The following packages will be built and installed:
  * boost-algorithm[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-align[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-any[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-asio[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-atomic[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-build[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-chrono[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-container[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-container-hash[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-context[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-conversion[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-coroutine[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-date-time[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-describe[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-detail[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-endian[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-exception[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-format[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-function[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-function-types[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-functional[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-fusion[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-integer[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-intrusive[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-io[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-iterator[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-lexical-cast[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-modular-build-helper[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-move[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-mp11[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-mpl[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-multi-index[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-numeric-conversion[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-optional[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-phoenix[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-pool[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-predef[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-property-tree[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-proto[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-range[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-ratio[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-rational[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-regex[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-serialization[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-smart-ptr[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-spirit[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-system[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-test[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-thread[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-tokenizer[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-tuple[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-type-index[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-typeof[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-unordered[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-utility[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-variant[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-variant2[core]:x64-mingw-dynamic -> 1.82.0#1
  * boost-winapi[core]:x64-mingw-dynamic -> 1.82.0#1
  * curl[core,non-http,schannel,ssl,sspi]:x64-mingw-dynamic -> 8.0.1
  * openssl[core]:x64-mingw-dynamic -> 3.1.0#1
    tgbot-cpp[core]:x64-mingw-dynamic -> 1.6
  * vcpkg-cmake-config[core]:x64-mingw-dynamic -> 2022-02-06#1
  * vcpkg-cmake-get-vars[core]:x64-mingw-dynamic -> 2023-03-02
  * zlib[core]:x64-mingw-dynamic -> 1.2.13
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-mingw-dynamic...
Restored 0 package(s) from C:\Users\фвьшт\AppData\Local\vcpkg\archives in 2.26 ms. Use --debug to see more details.
Installing 1/64 boost-build:x64-mingw-dynamic...
Building boost-build[core]:x64-mingw-dynamic...
warning: -- Using community triplet x64-mingw-dynamic. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: F:\vcpkg\triplets\community\x64-mingw-dynamic.cmake
-- Using cached boostorg-build-boost-1.82.0.tar.gz.
-- Cleaning sources at F:/vcpkg/buildtrees/boost-build/src/ost-1.82.0-e88c66a4cd.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/vcpkg/downloads/boostorg-build-boost-1.82.0.tar.gz
-- Applying patch 0002-fix-get-version.patch
-- Applying patch 0003-fix-emscripten.patch
-- Applying patch 0004-workaround-MSVC-codegen-bug-in-17.5-on-ARM64.patch
-- Using source at F:/vcpkg/buildtrees/boost-build/src/ost-1.82.0-e88c66a4cd.clean
-- Using cached boost_LICENSE_1_0.txt.
-- Using cached boost-1.82.0-boostcpp.jam.
-- Installing: F:/vcpkg/packages/boost-build_x64-mingw-dynamic/share/boost-build/copyright
-- Bootstrapping...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: F:/vcpkg/packages/boost-build_x64-mingw-dynamic/tools/boost-build/bootstrap.bat mingw
    Working Directory: F:/vcpkg/packages/boost-build_x64-mingw-dynamic/tools/boost-build
    Error code: 1
    See logs for more information:
      F:\vcpkg\buildtrees\boost-build\bootstrap-x64-mingw-dynamic-out.log
      F:\vcpkg\buildtrees\boost-build\bootstrap-x64-mingw-dynamic-err.log

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:65 (vcpkg_execute_required_process)
  scripts/ports.cmake:147 (include)

error: building boost-build:x64-mingw-dynamic failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-build
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[boost-build]+Build+error&body=Copy+issue+body+from+F%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

Package: boost-build[core]:x64-mingw-dynamic -> 1.82.0#1

**Host Environment**

- Host: x64-windows
- Compiler:  
-    vcpkg-tool version: 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895
    vcpkg-scripts version: eb8e75bb4 2023-04-18 (2 days ago)

**Failure logs**

```
-- Using cached boostorg-build-boost-1.82.0.tar.gz.
-- Cleaning sources at F:/vcpkg/buildtrees/boost-build/src/ost-1.82.0-e88c66a4cd.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/vcpkg/downloads/boostorg-build-boost-1.82.0.tar.gz
-- Applying patch 0002-fix-get-version.patch
-- Applying patch 0003-fix-emscripten.patch
-- Applying patch 0004-workaround-MSVC-codegen-bug-in-17.5-on-ARM64.patch
-- Using source at F:/vcpkg/buildtrees/boost-build/src/ost-1.82.0-e88c66a4cd.clean
-- Using cached boost_LICENSE_1_0.txt.
-- Using cached boost-1.82.0-boostcpp.jam.
-- Installing: F:/vcpkg/packages/boost-build_x64-mingw-dynamic/share/boost-build/copyright
-- Bootstrapping...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: F:/vcpkg/packages/boost-build_x64-mingw-dynamic/tools/boost-build/bootstrap.bat mingw
    Working Directory: F:/vcpkg/packages/boost-build_x64-mingw-dynamic/tools/boost-build
    Error code: 1
    See logs for more information:
      F:\vcpkg\buildtrees\boost-build\bootstrap-x64-mingw-dynamic-out.log
      F:\vcpkg\buildtrees\boost-build\bootstrap-x64-mingw-dynamic-err.log

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:65 (vcpkg_execute_required_process)
  scripts/ports.cmake:147 (include)



```
<details><summary>F:\vcpkg\buildtrees\boost-build\bootstrap-x64-mingw-dynamic-out.log</summary>

```
Building the B2 engine..
###
### Using 'mingw' toolset.
###

F:\vcpkg\packages\boost-build_x64-mingw-dynamic\tools\boost-build\src\engine>"g++" -x c++ -std=c++11 -s -O3 -o b2.exe   -DNDEBUG  builtins.cpp class.cpp command.cpp compile.cpp constants.cpp cwd.cpp debug.cpp debugger.cpp execcmd.cpp execnt.cpp execunix.cpp filent.cpp filesys.cpp fileunix.cpp frames.cpp function.cpp glob.cpp hash.cpp hcache.cpp hdrmacro.cpp headers.cpp jam.cpp jamgram.cpp lists.cpp make.cpp make1.cpp md5.cpp mem.cpp modules.cpp native.cpp object.cpp option.cpp output.cpp parse.cpp pathnt.cpp pathsys.cpp pathunix.cpp regexp.cpp rules.cpp scan.cpp search.cpp jam_strings.cpp startup.cpp subst.cpp sysinfo.cpp timestamp.cpp variable.cpp w32_getreg.cpp modules/order.cpp modules/path.cpp modules/property-set.cpp modules/regex.cpp modules/sequence.cpp modules/set.cpp  

F:\vcpkg\packages\boost-build_x64-mingw-dynamic\tools\boost-build\src\engine>dir *.exe 
 Volume in drive F has no label.
 Volume Serial Number is F86C-BA02

 Directory of F:\vcpkg\packages\boost-build_x64-mingw-dynamic\tools\boost-build\src\engine


Failed to build the B2 engine.

```
</details>
<details><summary>F:\vcpkg\buildtrees\boost-build\bootstrap-x64-mingw-dynamic-err.log</summary>

```
File Not Found
```
</details>

**Comment by mike192025** [comment]
Same problem here
Got fixed after downloading from within Visual Studio Installer
1st.   Visual Studio Installer  ->  Desktop Development with C++  ->  C++ CMake tools for Windows
2nd.  Visual Studio Installer  ->  Universal Windows: Platform build tools

Download at least both otherwise other build errors emerge!

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
