### ISSUE TITLE
[libtorch] build failure

### ISSUE THREAD

**Issue by morebtcg** [microsoft/vcpkg#30995]
### Operating system

Ubuntu22.04 @ Windows 11 WSL2

### Compiler

GCC-12

### Steps to reproduce the behavior

```Shell
./vcpkg install libtorch
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
    libtorch[core,xnnpack]:x64-linux -> 1.12.1#2
Detecting compiler hash for triplet x64-linux...
Restored 0 package(s) from /home/more/.cache/vcpkg/archives in 40.4 us. Use --debug to see more details.
Installing 1/1 libtorch:x64-linux...
Building libtorch[core,xnnpack]:x64-linux...
-- Note: libtorch only supports dynamic library linkage. Building dynamic library.
-- Using cached pytorch-pytorch-v1.12.1.tar.gz.
-- Cleaning sources at /home/more/vcpkg/buildtrees/libtorch/src/v1.12.1-d15308d103.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/more/vcpkg/downloads/pytorch-pytorch-v1.12.1.tar.gz
-- Applying patch pytorch-pr-85958.patch
-- Applying patch fix-cmake.patch
-- Applying patch fix-fbgemm-include.patch
-- Applying patch fix-c10-glog.patch
-- Applying patch use-flatbuffers2.patch
-- Applying patch fix-windows.patch
-- Using source at /home/more/vcpkg/buildtrees/libtorch/src/v1.12.1-d15308d103.clean
-- Using flatc: /home/more/vcpkg/installed/x64-linux/tools/flatbuffers/flatc
-- Using protoc: /home/more/vcpkg/installed/x64-linux/tools/protobuf/protoc
-- Setting up python virtual environmnent...
-- Installing python packages: typing-extensions;pyyaml;numpy
-- Setting up python virtual environmnent...finished.
-- Using Python3: /home/more/vcpkg/buildtrees/libtorch/x64-linux-venv/bin/python
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: /home/more/vcpkg/downloads/tools/cmake-3.25.1-linux/cmake-3.25.1-linux-x86_64/bin/cmake --build . --config Debug --target torch_cpu -- -v -j25
    Working Directory: /home/more/vcpkg/buildtrees/libtorch/x64-linux-dbg
    See logs for more information:
      /home/more/vcpkg/buildtrees/libtorch/build-torch_cpu-x64-linux-dbg-out.log[build-torch_cpu-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/11292863/build-torch_cpu-x64-linux-dbg-out.log)

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  ports/libtorch/portfile.cmake:157 (vcpkg_cmake_build)
  scripts/ports.cmake:147 (include)

error: building libtorch:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libtorch
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[libtorch]+Build+error&body=Copy+issue+body+from+%2Fhome%2Fmore%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by jimwang118** [comment]
Looking at the error message in the log, it should be that we used the `-Werror` compilation option to convert the warning into an error, so a warning that did not return at the end of the function was converted into an error.
