### ISSUE TITLE
opencv/hdf5/Iconv

### ISSUE THREAD

**Issue by UredNuubjuz** [microsoft/vcpkg#30992]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
-cd build
-cmake ..
```

### Failure logs

```
CMake Error at C:/src/vcpkg/installed/x64-windows-static/share/opencv4/OpenCVModules.cmake:109 (set_target_properties):
  The link interface of target "opencv_hdf" contains:

    hdf5::hdf5-static

  but the target was not found.
```

```
CMake Error at CMakeLists.txt:32 (target_link_libraries):
  Target "IMO" links to:

    hdf5::hdf5-static

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```

```
CMake Error at C:/src/vcpkg/installed/x64-windows-static/share/opencv4/OpenCVModules.cmake:369 (set_target_properties):
  The link interface of target "opencv_wechat_qrcode" contains:

    Iconv::Iconv

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```

### Additional context

I am really unsure if i should ask here or in a cmake forum since i dont know if my issue is with the installation via vcpkg, or if its a problem with cmake. i did search a bunch of forums and i dont understand most of it. From my understanding the target "IMO" (my project name) cannot link to the target hdf5-static and iconv.
[cmakelists.txt](https://github.com/microsoft/vcpkg/files/11291996/cmakelists.txt)

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. If you use manifest mode, could you also provide your `vcpkg.json` file?

**Comment by UredNuubjuz** [comment]
i cant find a vcpkg.json file, but besides that, i think i solved it somewhat. my problem was, that i was not able to call my toolchain file (vcpkg.cmake) after i call my project in my cmakelists.txt file. the error message disappeared after i changed it.
i still have an issue tho. i suspect that the issue is cmake but i will describe it as good as possible. 
right now cmake is confusing the dynamic and static library of hdf5. i wasnt aware of the difference between the two and just installed the dynamic library. after trying to build my project, i figured out that it does not work. i then installed the static library and uninstalled the dynamic library. right now cmake is looking for a file in the dynamic installation but it should search for it in the static installation. long story short i think there is an issue with my hdf5 config file but it could also be an issue with vcpkg not installing it correctly.
```
CMake Error at C:/src/vcpkg/installed/x64-windows-static/share/hdf5/hdf5-config.cmake:150 (include):
  include could not find requested file:

    C:/src/vcpkg/installed/x64-windows/share/hdf5/hdf5-targets.cmake
```
as you can see, its searching for a file in the dynamic directory.

i think the best thing i can do is ask if my installation is correct. this is my directory of hdf5-static:
```
packages\hdf5_x64-windows-static
			├───debug
			│   └───lib
			│       ├───pkgconfig
			│       │   ├───hdf5.pc
			│       │   └───hdf5_hl.pc
			│       ├───libhdf5.settings
			│       ├───libhdf5_D.lib
			│       ├───libhdf5_hl_D.lib
			│       └───libhdf5_tools_D.lib
			├───include
			│       ├───
			│       ├───
			│       ├───
			│       ├───
			│       ├───
			│       ├───
			│       ├───
			├───lib
			├───share
			└───tools
```


I link all files in question down bellow (i had to change vcpkg.cmake to a .txt file since github does not accept cmake files)
[cmakelists.txt](https://github.com/microsoft/vcpkg/files/11333312/cmakelists.txt)
[vcpkg.cmake.txt](https://github.com/microsoft/vcpkg/files/11333358/vcpkg.cmake.txt)

i want to mention again that the issue is most likely cmake and not vcpkg.


thanks for your help anyway.
