### ISSUE TITLE
Add harfbuzz

### ISSUE THREAD

**Issue by ebraminio** [Microsoft/vcpkg#31]
HarfBuzz is a cross-platform opentype text shaping library which is popular among opensource projects and it would be nice if be added to vcpkg.
Repo: https://github.com/behdad/harfbuzz
Releases: https://www.freedesktop.org/software/harfbuzz/release/

**Comment by vlj** [comment]
I agree.

**Comment by ebraminio** [comment]
Fixed on #132 by @vlj :)
