### ISSUE TITLE
OpenCL build failure

### ISSUE THREAD

**Issue by term-est** [microsoft/vcpkg#31001]
### Operating system

Windows

### Compiler

GCC/MinGW

### Steps to reproduce the behavior

```Shell
vcpkg install opencl --triplet=x64-mingw-static
```

### Failure logs

```
CMake Error at ports/opencl/portfile.cmake:43 (file):
  file INSTALL cannot find
  "C:/src/vcpkg/buildtrees/opencl/x64-mingw-static-rel/libOpenCL.a": File
  ```

### Additional context

The directory has `OpenCL.a` file. From what I understand `{VCPKG_TARGET_STATIC_LIBRARY_PREFIX}` adds `lib` prefix, which causes the build to fail as it can't file the said file.

```
set(VCPKG_TARGET_STATIC_LIBRARY_PREFIX "")

if (VCPKG_LIBRARY_LINKAGE STREQUAL static)
  if (NOT DEFINED VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "release")
    file(INSTALL "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/${VCPKG_TARGET_STATIC_LIBRARY_PREFIX}OpenCL${VCPKG_TARGET_STATIC_LIBRARY_SUFFIX}" DESTINATION ${CURRENT_PACKAGES_DIR}/lib)
  endif()
  ```
  
  I did this quick workaround in my port file, which solved the issue, but I am not sure if this is the right way to go about this.

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
