### ISSUE TITLE
how to build static lib for qt5.9.2 ?

### ISSUE THREAD

**Issue by how0723** [microsoft/vcpkg#3101]
how to build static lib for qt5.9.2 ?

**Comment by ReyzalX** [comment]
do you try `vcpkg  install qt5:x86-windows-static` ?

**Comment by Voskrese** [comment]
@ReyzalX 
`https://github.com/Microsoft/vcpkg/blob/master/ports/qt5-base/portfile.cmake`
```
if(VCPKG_LIBRARY_LINKAGE STREQUAL static)
    message(FATAL_ERROR "Qt5 doesn't currently support static builds. Please use a dynamic triplet instead.")
endif()
```

**Comment by JackBoosY** [comment]
Related to #4560

**Comment by PhoebeHui** [comment]
QT5 currently support static build, now one of its component failed with static build, duplicated to issue https://github.com/microsoft/vcpkg/issues/4560
