### ISSUE TITLE
[gtk] build failure

### ISSUE THREAD

**Issue by DougRogers** [microsoft/vcpkg#31039]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
'C:\Users\Roger\source\repos\vcpkg>vcpkg install gtk:x64-windows --recurse'
```

### Failure logs

Computing` installation plan...
The following packages will be rebuilt:
  * gettext[core,tools]:x64-windows -> 0.21.1
  * glib[core]:x64-windows -> 2.76.1
  * gstreamer[core,dtls,faad,gpl,jpeg,libav,libde265,mpg123,openh264,openjpeg,openmpt,plugins-bad,plugins-base,plugins-good,plugins-ugly,png,speex,taglib,vpx,webp,x265]:x64-windows -> 1.20.5#5
The following packages will be built and installed:
  * atk[core]:x64-windows -> 2.38.0#5
  * brotli[core]:x64-windows -> 1.0.9#5
  * cairo[core,fontconfig,freetype,gobject]:x64-windows -> 1.17.8
  * fontconfig[core]:x64-windows -> 2.14.2
  * freetype[brotli,bzip2,core,png,zlib]:x64-windows -> 2.12.1#3
  * fribidi[core]:x64-windows -> 1.0.12
  * gdk-pixbuf[core]:x64-windows -> 2.42.10
  * getopt[core]:x64-windows -> 0#3
  * getopt-win32[core]:x64-windows -> 0.1#7
  * gperf[core]:x64-windows -> 3.1#5
  * graphene[core]:x64-windows -> 1.10.8#2
    gtk[core]:x64-windows -> 4.6.8#2
  * harfbuzz[core]:x64-windows -> 7.1.0
  * libepoxy[core]:x64-windows -> 1.5.10#1
  * libsass[core]:x64-windows -> 3.6.5#1
  * lzo[core]:x64-windows -> 2.10#9
  * pango[core]:x64-windows -> 1.50.14
  * pixman[core]:x64-windows -> 0.42.2#2
  * pthread[core]:x64-windows -> 3.0.0#2
  * pthreads[core]:x64-windows -> 3.0.0#13
  * sassc[core]:x64-windows -> 3.6.2
Additional packages (*) will be modified to complete this operation.
Removing 1/27 gstreamer:x64-windows
Elapsed time to handle gstreamer:x64-windows: 429 ms
Removing 2/27 glib:x64-windows
Elapsed time to handle glib:x64-windows: 94.4 ms
Removing 3/27 gettext:x64-windows
Elapsed time to handle gettext:x64-windows: 7.3 ms
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\Roger\AppData\Local\vcpkg\archives in 1.72 ms. Use --debug to see more details.
Installing 4/27 gettext:x64-windows...
Building gettext[core,tools]:x64-windows...
-- Using cached gettext-0.21.1.tar.gz.
-- Cleaning sources at C:/Users/Roger/source/repos/vcpkg/buildtrees/gettext/src/gettext-0-de39ca5451.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Roger/source/repos/vcpkg/downloads/gettext-0.21.1.tar.gz
-- Applying patch android.patch
-- Applying patch uwp.patch
-- Applying patch win-gethostname.patch
-- Applying patch 0003-Fix-win-unicode-paths.patch
-- Applying patch rel_path.patch
-- Using source at C:/Users/Roger/source/repos/vcpkg/buildtrees/gettext/src/gettext-0-de39ca5451.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Using cached msys-gzip-1.11-1-x86_64.pkg.tar.zst.
-- Using cached msys-bash-5.1.008-1-x86_64.pkg.tar.zst.
-- Using cached msys-autoconf-2.71-3-any.pkg.tar.zst.
-- Using cached msys-diffutils-3.8-2-x86_64.pkg.tar.zst.
-- Using cached msys-binutils-2.37-5-x86_64.pkg.tar.zst.
-- Using cached msys-libtool-2.4.7-3-x86_64.pkg.tar.zst.
-- Using cached msys-file-5.41-2-x86_64.pkg.tar.zst.
-- Using cached msys-zlib-1.2.11-1-x86_64.pkg.tar.xz.
-- Using cached msys-libbz2-1.0.8-3-x86_64.pkg.tar.zst.
-- Using cached msys-coreutils-8.32-2-x86_64.pkg.tar.zst.
-- Using cached msys-grep-3.0-2-x86_64.pkg.tar.xz.
-- Using cached msys-sed-4.8-2-x86_64.pkg.tar.zst.
-- Using cached msys-libpcre-8.45-1-x86_64.pkg.tar.zst.
-- Using cached msys-m4-1.4.19-2-x86_64.pkg.tar.zst.
-- Using cached msys-automake-wrapper-11-4-any.pkg.tar.zst.
-- Using cached msys-gawk-5.1.0-2-x86_64.pkg.tar.zst.
-- Using cached msys-mpfr-4.1.0-1-x86_64.pkg.tar.zst.
-- Using cached msys-gmp-6.2.1-1-x86_64.pkg.tar.zst.
-- Using cached msys-libreadline-8.1.001-1-x86_64.pkg.tar.zst.
-- Using cached msys-ncurses-6.2-2-x86_64.pkg.tar.zst.
-- Using cached msys-automake1.16-1.16.3-3-any.pkg.tar.zst.
-- Using cached msys-perl-5.32.1-2-x86_64.pkg.tar.zst.
-- Using cached msys-libcrypt-2.1-3-x86_64.pkg.tar.zst.
-- Using cached msys-pkg-config-0.29.2-4-x86_64.pkg.tar.zst.
-- Using cached msys-make-4.3-3-x86_64.pkg.tar.zst.
-- Using cached msys-findutils-4.8.0-1-x86_64.pkg.tar.zst.
-- Using cached msys-libintl-0.21-1-x86_64.pkg.tar.zst.
-- Using cached msys-libiconv-1.16-2-x86_64.pkg.tar.zst.
-- Using cached msys-gcc-libs-11.2.0-3-x86_64.pkg.tar.zst.
-- Using cached msys-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using cached msys-which-2.21-4-x86_64.pkg.tar.zst.
-- Using msys root at C:/Users/Roger/source/repos/vcpkg/downloads/tools/msys2/e6f7ae10db8f00f6
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at C:/Users/Roger/source/repos/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Configuring x64-windows-rel
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/Users/Roger/source/repos/vcpkg/downloads/tools/msys2/e6f7ae10db8f00f6/usr/bin/make.exe -j 17 --trace -f C:/Users/Roger/source/repos/vcpkg/ports/gettext/Makefile all
    Working Directory: C:/Users/Roger/source/repos/vcpkg/buildtrees/gettext/x64-windows-rel/
    See logs for more information:
      C:\Users\Roger\source\repos\vcpkg\buildtrees\gettext\build-x64-windows-rel-out.log
      C:\Users\Roger\source\repos\vcpkg\buildtrees\gettext\build-x64-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:151 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:2 (vcpkg_build_make)
  ports/gettext/portfile.cmake:69 (vcpkg_install_make)
  ports/gettext/portfile.cmake:99 (build_libintl_and_tools)
  scripts/ports.cmake:147 (include)

**Comment by DougRogers** [comment]
[build-x64-windows-rel-err.log](https://github.com/microsoft/vcpkg/files/11299532/build-x64-windows-rel-err.log)
[build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/11299533/build-x64-windows-rel-out.log)

**Comment by dg0yt** [comment]
I guess vcpkg suggested to use a different issue title.
Duplicates #30579.
Workaround: Remove libxml2 before installing gettext[tools].

**Comment by DougRogers** [comment]
@dg0yt Looks like it.  Thanks.

**Comment by DougRogers** [comment]
It was resolved by removing libxml2 first

**Comment by DougRogers** [comment]
Duplicate
