### ISSUE TITLE
[zlib] build failure

### ISSUE THREAD

**Issue by AN3Orik** [microsoft/vcpkg#31043]
### Operating system

x64-windows

### Compiler

MSVC 19.35.32217.1

### Steps to reproduce the behavior

```Shell
vcpkg install cpr:x64-windows-static
```

### Failure logs

-- Using cached madler-zlib-v1.2.13.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/zlib/src/v1.2.13-f30d2a168d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/madler-zlib-v1.2.13.tar.gz
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch 0002-skip-building-examples.patch
-- Applying patch 0003-build-static-or-shared-not-both.patch
-- Applying patch 0004-android-and-mingw-fixes.patch
-- Using source at C:/vcpkg/buildtrees/zlib/src/v1.2.13-f30d2a168d.clean
CMake Error at ports/zlib/portfile.cmake:18 (vcpkg_cmake_configure):
  Unknown CMake command "vcpkg_cmake_configure".
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)

**Comment by DougRogers** [comment]
Did you uninstall this before?  You could try deleting the build tree (C:/vcpkg/buildtrees/zlib) and the archive.

**Comment by autoantwort** [comment]
same as https://github.com/microsoft/vcpkg/issues/30965

**Comment by AN3Orik** [comment]
git clean -xffd and pull again helps
Ty
