### ISSUE TITLE
[opencv3] build failure

### ISSUE THREAD

**Issue by ZhaoH-H** [microsoft/vcpkg#31046]
### Operating system

Windows10

### Compiler

PowerShell7

### Steps to reproduce the behavior

```Shell
vcpkg install opencv3:x64-windows
```

### Failure logs

`CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: F:/ChengXu/XueXi/cmake/bin/cmake.exe --build . --config Release --target install -- -v -j9
    Working Directory: C:/Users/ZhaoHan/vcpkg/buildtrees/opencv3/x64-windows-rel
    See logs for more information:
      C:\Users\ZhaoHan\vcpkg\buildtrees\opencv3\install-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/opencv3/portfile.cmake:404 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building opencv3:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.`

**Comment by autoantwort** [comment]
See https://github.com/microsoft/vcpkg/issues/30604 for how to probably report an issue.

**Comment by Cheney-W** [comment]
Unfortunately, we don't have enough information to solve this issue, if you have any more information to help us solve it, please reopen!
