### ISSUE TITLE
[vcpkg-tool] add fetch command to manual

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#31058]
>### Is your feature request related to a problem? Please describe.

No information how to fetch tools with vcpkg.

>### Proposed solution

add fetch command to manual.

>### Describe alternatives you've considered

I didn't think of any.

>### Additional context

_No response_

**Comment by PhoebeHui** [comment]
@talregev, if I understand correctly, you mean these tools in https://github.com/microsoft/vcpkg/blob/master/scripts/vcpkgTools.xml which used by vcpkg, right? The vcpkg would download them if needed, but you want to fetch them manually, like 'vcpkg fetch git', right?

**Comment by talregev** [comment]
@PhoebeHui You miss understand me.
I want you update the documentation inside vcpkg:
When I type: `vcpkg --help`
I want to show explanation about fetch command.

**Comment by talregev** [comment]
vpckg-tool is the repo name where the change need to happen.

**Comment by jimwang118** [comment]
Related:https://github.com/microsoft/vcpkg-tool/pull/1169

**Comment by talregev** [comment]
Thanks! it already merge.
