### ISSUE TITLE
Read the Docs links to non-existent files

### ISSUE THREAD

**Issue by cjdb** [microsoft/vcpkg#31059]
**Describe the bug**
The [Read the Docs](https://vcpkg.readthedocs.io/en/latest/README/) advice to see the latest documentation links to https://github.com/Microsoft/vcpkg/tree/master/docs/README.md, which doesn't seem to exist anymore.

**Comment by MonicaLiu0311** [comment]
This website has been deprecated, please go to the new website, thank you.

https://github.com/microsoft/vcpkg/issues/29019#issuecomment-1419686967

**Comment by cjdb** [comment]
Would it be possible to get a depreciation notice on the Read the Docs documentation in that case? It isn't apparent that it's been deprecated.

**Comment by MonicaLiu0311** [comment]
> Would it be possible to get a depreciation notice on the Read the Docs documentation in that case? It isn't apparent that it's been deprecated.

Thanks for your feedback, work in progress.
