### ISSUE TITLE
[glad] update to glad2

### ISSUE THREAD

**Issue by jasperdrescher** [microsoft/vcpkg#31061]
### Library name

glad

### New version number

glad2

### Other information that may be useful (release notes, etc...)

Hi, this is not exactly a version update, but it doesn't look like the glad package in vcpkg uses the default branch glad2 of the glad repository. The functionality and include seem different between the master (glad) and glad2 branch. Can this somehow be updated please?

**Comment by jasperdrescher** [comment]
@LilyWangLL do you think it would be better to introduce a new package called glad2, similar to glfw3? Or is it possible to switch the branch from master to glad2 for this package, although that could break existing project?

**Comment by LilyWangLL** [comment]
I noticed that the upstream has been releasing version 2.0 since last year and is no longer updating version 0.1. Therefore, my point is to upgrade `glad` to version 2.0, and I am trying to update glad locally.

**Comment by LilyWangLL** [comment]
@jasperdrescher
I found that `glad2` no longer provides complete CMake build files, the related links: https://github.com/Dav1dde/glad/issues/244. `Glad2` only has one file `CMakeLists.txt` under the subdirectory cmake, which just provides functions. If we want to update `glad` to `glad2`, we need to write new `CMakeLists.txt`. I'm not very familiar with the use of `glad`, would you be interested in doing this?

**Comment by jasperdrescher** [comment]
This repo uses glad2 with CMake and it uses the glad_add_library function for CMakeLists: https://github.com/jasperdrescher/HelloOpenGL/blob/main/CMake/glad.cmake. If needed I can try to update the package.

**Comment by jasperdrescher** [comment]
@LilyWangLL I'll try to update the port to glad2 on a fork and see how far I get today 😄

**Comment by jasperdrescher** [comment]
@LilyWangLL trying to add a CMakeLists.txt to the glad port and testing that locally is more complicated/vague than I expected. It would be appreciated if you could help out, as I'm not as familiar with Vcpkg and the required steps when modifying a port.

**Comment by LilyWangLL** [comment]
You could submit a PR to do this, our team and other contributors could give the suggestions for this update.
