### ISSUE TITLE
[New Port Request] TinyOrm

### ISSUE THREAD

**Issue by kunpen** [microsoft/vcpkg#31087]
### Library name

TinyOrm

### Library description

TinyORM is a modern c++ ORM library that makes interacting with a database extremely simple. It depends on the QtCore and QtSql libraries.

### Source repository URL

https://github.com/silverqx/TinyORM

**Comment by SchaichAlonso** [comment]
The TinyORM project actually has vcpkg overlay files [here](https://github.com/silverqx/TinyORM/tree/0558c2fda0253d090477e36cc8aeb1054ab93049/cmake/vcpkg/ports), which could be copy-pasted into vcpkg mainline.

**Comment by silverqx** [comment]
Last 10 days WIP still.

**Comment by SchaichAlonso** [comment]
comment
