### ISSUE TITLE
Cmake package config files all wrong

### ISSUE THREAD

**Issue by Fleischner** [microsoft/vcpkg#3108]
Do not allow Package Config Files (*.pc). 
They are all wrong! (Assimp, ccd, fcl, flann, freeglut, glew, tinyxml2, and i assume many more)
And indistinguishable between release and debug.

There should be either:
1) an rule checker to prevent having these files
2) require them in a certain location and check the content
3) require them in a certain location and create them with a fixed pattern by vcpkg

**Comment by JackBoosY** [comment]
Since #9861 merged, the only thing we need to do is to fix these ports.

**Comment by JackBoosY** [comment]
Related: #6045.

**Comment by JonLiu1993** [comment]
@Fleischner ,What are the ports in the latest library that still have these problems? can you give a list

**Comment by JackBoosY** [comment]
Now I think we can close this issue, since we have `vcpkg_fixup_pkgconfig`, this issue has been fixed.
