### ISSUE TITLE
can't install cuda

### ISSUE THREAD

**Issue by developernew123** [microsoft/vcpkg#3109]
I want to install cuda via vcpk but I can't , I get these errors : 

CMake Error at ports/cuda/portfile.cmake:26 (message):
  Could not find CUDA.  Before continuing, please download and install CUDA
  (V9.0.0 or higher) from:

      https://developer.nvidia.com/cuda-downloads

  Also ensure vcpkg has been rebuilt with the latest version (v0.0.104 or
  later)
Call Stack (most recent call first):
  scripts/ports.cmake:72 (include)

Error: Building package cuda:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cuda:x86-windows
  Vcpkg version: 0.0.106-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by Voskrese** [comment]
@developernew123 
http://developer.download.nvidia.com/compute/cuda/9.1/secure/Prod/local_installers/cuda_9.1.85_win10.exe

**Comment by NancyLi1013** [comment]
Hi @developernew123, thanks for posting this issue. please try to install CUDA toolkit 10 in your machine first. Then install CUDA via vcpkg. I have tested on my local and it can be installed successfully.

**Comment by PhoebeHui** [comment]
Please reopen this issue if the problem persist for you after install CUDA toolkit 10.
