### ISSUE TITLE
[pkgconf] Build error on linux arm64 (as: unrecognized option '--gdwarf-4')

### ISSUE THREAD

**Issue by jorisvandenbossche** [microsoft/vcpkg#31091]
Originally trying to install GDAL (see included vcpkg.json at the bottom), but can be reproduced with just installing `vcpkg install pkgconf` 
Below is the automatically generated issue body. I got the error running this in a docker container derived from `amd64/almalinux` (https://hub.docker.com/r/amd64/almalinux/)

---

Package: pkgconf[core]:arm64-linux -> 1.8.0#5

**Host Environment**

- Host: arm64-linux
- Compiler: GNU 12.1.1
-    vcpkg-tool version: 2999-12-31-unknownhash
    vcpkg-scripts version: b3e0a1e62 2023-04-21 (2 days ago)

**To Reproduce**

`vcpkg install`

**Failure logs**

```
-- Downloading https://github.com/pkgconf/pkgconf/archive/cef30268e1a3f79efd607c26abcf556aa314c9c4.tar.gz -> pkgconf-pkgconf-cef30268e1a3f79efd607c26abcf556aa314c9c4.tar.gz...
-- Extracting source /opt/vcpkg/downloads/pkgconf-pkgconf-cef30268e1a3f79efd607c26abcf556aa314c9c4.tar.gz
-- Using source at /opt/vcpkg/buildtrees/pkgconf/src/6aa314c9c4-8bd74a463d.clean
-- Getting CMake variables for arm64-linux-dbg
-- Getting CMake variables for arm64-linux-rel
-- Configuring arm64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/python3 /opt/vcpkg/installed/arm64-linux/tools/meson/meson.py -Dtests=false --buildtype plain --backend ninja --wrap-mode nodownload --libdir lib --native /opt/vcpkg/buildtrees/pkgconf/meson-arm64-linux-dbg.log -Ddebug=true --prefix /opt/vcpkg/packages/pkgconf_arm64-linux/debug --includedir ../include -Dcmake_prefix_path=['/opt/vcpkg/installed/arm64-linux/debug','/opt/vcpkg/installed/arm64-linux'] /opt/vcpkg/buildtrees/pkgconf/src/6aa314c9c4-8bd74a463d.clean
    Working Directory: /opt/vcpkg/buildtrees/pkgconf/arm64-linux-dbg
    Error code: 1
    See logs for more information:
      /opt/vcpkg/buildtrees/pkgconf/config-arm64-linux-dbg-meson-log.txt.log
      /opt/vcpkg/buildtrees/pkgconf/config-arm64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:431 (vcpkg_execute_required_process)
  buildtrees/versioning_/versions/pkgconf/8848e56b32837456dfb872f6ca3cc9953558d453/portfile.cmake:9 (vcpkg_configure_meson)
  scripts/ports.cmake:147 (include)



```
<details><summary>/opt/vcpkg/buildtrees/pkgconf/config-arm64-linux-dbg-meson-log.txt.log</summary>

```
Build started at 2023-04-24T14:57:26.945693
Main binary: /usr/bin/python3
Build Options: -Dtests=false -Ddebug=true '-Dcmake_prefix_path=['"'"'/opt/vcpkg/installed/arm64-linux/debug'"'"','"'"'/opt/vcpkg/installed/arm64-linux'"'"']' -Dprefix=/opt/vcpkg/packages/pkgconf_arm64-linux/debug -Dincludedir=../include -Dlibdir=lib -Dbackend=ninja -Dbuildtype=plain -Dwrap_mode=nodownload '--native-file /opt/vcpkg/buildtrees/pkgconf/meson-arm64-linux-dbg.log'
Python system: Linux
The Meson build system
Version: 0.62.1
Source dir: /opt/vcpkg/buildtrees/pkgconf/src/6aa314c9c4-8bd74a463d.clean
Build dir: /opt/vcpkg/buildtrees/pkgconf/arm64-linux-dbg
Build type: native build
Project name: pkgconf
Project version: 1.8.0
Sanity testing C compiler: /opt/rh/gcc-toolset-12/root/usr/bin/cc
Is cross compiler: False.
Sanity check compiler command line: /opt/rh/gcc-toolset-12/root/usr/bin/cc sanitycheckc.c -o sanitycheckc.exe -fPIC -g -I/opt/vcpkg/installed/arm64-linux/include -D_FILE_OFFSET_BITS=64 -L/opt/vcpkg/installed/arm64-linux/debug/lib
Sanity check compile stdout:

-----
Sanity check compile stderr:
as: unrecognized option '--gdwarf-4'

-----

../src/6aa314c9c4-8bd74a463d.clean/meson.build:1:0: ERROR: Compiler /opt/rh/gcc-toolset-12/root/usr/bin/cc can not compile programs.
```
</details>
<details><summary>/opt/vcpkg/buildtrees/pkgconf/config-arm64-linux-dbg-out.log</summary>

```
WARNING: Recommend using either -Dbuildtype or -Doptimization + -Ddebug. Using both is redundant since they override each other. See: https://mesonbuild.com/Builtin-options.html#build-type-options
The Meson build system
Version: 0.62.1
Source dir: /opt/vcpkg/buildtrees/pkgconf/src/6aa314c9c4-8bd74a463d.clean
Build dir: /opt/vcpkg/buildtrees/pkgconf/arm64-linux-dbg
Build type: native build
Project name: pkgconf
Project version: 1.8.0

../src/6aa314c9c4-8bd74a463d.clean/meson.build:1:0: ERROR: Compiler /opt/rh/gcc-toolset-12/root/usr/bin/cc can not compile programs.

A full log can be found at /opt/vcpkg/buildtrees/pkgconf/arm64-linux-dbg/meson-logs/meson-log.txt
```
</details>

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "name": "pyogrio",
  "version": "0.4.0",
  "dependencies": [
    {
      "name": "gdal",
      "default-features": false,
      "features": [
        "recommended-features",
        "curl",
        "geos"
      ]
    }
  ],
  "builtin-baseline": "fe2d921cd5e1c8721e8e2385c35fb3a4ea65e559"
}

```
</details>

**Comment by dg0yt** [comment]
I cannot reproduces this in cross builds (Ubuntu 18.04 x64 host).

I also don't see why `as` should be run with that particular option. It is not passed to gcc on the command line. Is it coming from environment variables? Is the basic toolchain (gcc, as, binutils) known to work on this machine?

**Comment by jorisvandenbossche** [comment]
I created a minimal repo with small Dockerfile that reproduces it on CircleCI: https://github.com/jorisvandenbossche/test-vcpkg-arm64 ([logs](https://app.circleci.com/pipelines/github/jorisvandenbossche/test-vcpkg-arm64/2/workflows/fc1218e9-0cdb-4093-abe9-99b2b69061d4/jobs/2)). 
Now, this still uses the quay.io/pypa/manylinux_2_28_aarch64:latest image, which installs some custom build tooling and utils, so I should maybe try it with a plain linux container to see if it might be caused by some of the manylinux modifications.

**Comment by jorisvandenbossche** [comment]
A more minimal variant (without using the manylinux image): https://github.com/jorisvandenbossche/test-vcpkg-arm64/blob/no-manylinux/Dockerfile 
This installs `gcc-toolchain-12` in the `arm64v8/almalinux:8` image and reproduces it as well. It only happens when doing `vcpkg install pkgconf:arm64-linux` (which by default builds a debug build, and it's one of the debug flags that triggers the error) and not when doing `vcpkg install pkgconf:arm64-linux-release`. 
However, in my original GDAL install in manifest mode, I am actually installing in release mode via a custom triplet, but the `pkgconf` gets installed through another dependency and for some reason doesn't use the custom triplet but uses "arm64-linux" instead.

**Comment by jorisvandenbossche** [comment]
FWIW, I solved it for my original use case (installing GDAL) by defining an `arm64-linux` overlay triplet (overruling the default one) that forces a release build also for those tooling packages (i.e. essentially redefining it to `arm64-linux-release`).  
That then passes for the pkgconf install, and also the full GDAL install works fine.

**Comment by Neumann-A** [comment]
> pkgconf gets installed through another dependency and for some reason doesn't use the custom triplet but uses "arm64-linux"

missing `--host-triplet` .....

**Comment by jorisvandenbossche** [comment]
Ah, thanks for the pointer, that's indeed an much easier workaround instead of overlaying the default arm64-linux triplet with a release one.

**Comment by dg0yt** [comment]
Of course the host triplet should match the host... Doesn't vcpkg detect arm64-linux on an arm64 host?

**Comment by Neumann-A** [comment]
> Doesn't vcpkg detect arm64-linux on an arm64 host?

it does but it does not detect the `-release` suffix ;)

**Comment by dg0yt** [comment]
I see.

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
