### ISSUE TITLE
Platform expression "static-crt" doesn't work

### ISSUE THREAD

**Issue by bold84** [microsoft/vcpkg#31115]
**Describe the bug**
According to the documentation at https://learn.microsoft.com/en-us/vcpkg/reference/vcpkg-json#platform-expression , the expression "static-crt" exists. When used in the vcpkg.json file, the following error is displayed on the console:

<img width="946" alt="Screenshot 2023-04-26 at 03 50 58" src="https://user-images.githubusercontent.com/21118257/234400796-c925b311-a526-44d1-ae6e-706cb496a810.png">

<img width="735" alt="Screenshot 2023-04-26 at 03 53 08" src="https://user-images.githubusercontent.com/21118257/234401074-711bb79f-9560-4b60-b1bc-d4e179c751f1.png">

It doesn't matter in what combination static-crt is used.

**Environment**
- OS: N/A
- Compiler: N/A

**To Reproduce**
self-explanatory

**Expected behavior**
That static-crt expression works as documented.

**Failure logs**
see above

**Comment by Osyotr** [comment]
It's `staticcrt`, not `static-crt`

**Comment by bold84** [comment]
@Osyotr Thanks!
