### ISSUE TITLE
[lapack-reference] build failure

### ISSUE THREAD

**Issue by RainbowTaro2022** [microsoft/vcpkg#31129]
### Operating system

windows

### Compiler

msvc

### Steps to reproduce the behavior

```Shell
vcpkg install libtorch[dist] libtorch[leveldb] libtorch[opencv] libtorch[vulkan] libtorch[xnnpack] --allow-unsupported qtbase qt rtabmap[gui] quazip[bzip2] qtwebengine[geolocation] qtvirtualkeyboard[hunspell] qttools[qdoc] qttools[qdbus] qtbase[xlib] qtbase[appstore-compliant] qtbase[network] qtbase[framework] vtk itk
```

### Failure logs

[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/11333497/install-x86-windows-dbg-out.log)

**Comment by Adela0814** [comment]
I'm not able to repro this issue, could you please provide a simple reproduction step?
