### ISSUE TITLE
Don't store the `qt5-declarative` port in the GitHub Action cache

### ISSUE THREAD

**Issue by wy-luke** [microsoft/vcpkg#31132]
**Describe the bug**
When  running in github action `macos-latest` environment, vcpkg don't store the `qt5-declarative` port in the GitHub Action cache. Every time it will be rebuilt and took much time to finish.

The logs:
```
-- Installing: ......./vcpkg/packages/qt5-declarative_x64-osx/share/qt5-declarative/copyright
-- Performing post-build validation
Stored binaries in 0 destinations.
Elapsed time to handle qt5-declarative:x64-osx: 33 min
```

All other packages were cached except the `qt5-declarative`.

But it could be cached locally in `.cache/vcpkg` folder in my mac.

I used the `run-vcpkg` action and the author think it's `vcpkg` issue. So I report it here.
https://github.com/lukka/run-vcpkg/issues/200

**Environment**
- OS: Github action `macos-latest` environment. My local environment is OSX_13

**To Reproduce**
[My github action workflow](https://github.com/CopyPlusPlus/CopyPlusPlus-Qt/actions/runs/4772412380/workflow)

**Expected behavior**
Create and store cache for `qt5-declarative` and use that cache in later actions.

**Failure logs**
After installed the log shows:
```
Stored binaries in 0 destinations.
```

[My workflow full log](https://github.com/CopyPlusPlus/CopyPlusPlus-Qt/actions/runs/4772412380/jobs/8514571273)

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. The issue title and your description show `qt5-declarative` created cache after install succeed. But your  **Expected behavior** is **Vcpkg don't store the `qt5-declarative` port in the GitHub Action cache.** 

Which is your expected result? Do you want `qt5-declarative` to generate cache after installation?

**Comment by wy-luke** [comment]
> Thanks for posting this issue. The issue title and your description show `qt5-declarative` created cache after install succeed. But your **Expected behavior** is **Vcpkg don't store the `qt5-declarative` port in the GitHub Action cache.**
> 
> Which is your expected result? Do you want `qt5-declarative` to generate cache after installation?

@LilyWangLL  My fault. The expected result is to create cache for `qt5-declarative` and use that cache in later actions.

I have edited it. Thanks.

**Comment by autoantwort** [comment]
Sounds like https://github.com/microsoft/vcpkg/issues/31072 since both packages are large.

**Comment by wy-luke** [comment]
> Sounds like #31072 since both packages are large.

@autoantwort Yeah, I also strongly suspect that this is the reason. This package is 2GB or so.

However, I couldn't find any error message or log to confirm it.
