### ISSUE TITLE
[<port name>] build failure

### ISSUE THREAD

**Issue by onoss98** [microsoft/vcpkg#31140]
### Operating system

Windows

### Steps to reproduce the behavior

```Shell
vcpkg install crow
```

### Failure logs

arning: Starting with the September 2023 release, the default triplet for vcpkg libraries will change from x86-windows to the detected host triplet (x64-windows). To resolve this message, add --triplet x86-windows to keep the same behavior.
Computing installation plan...
The following packages will be built and installed:
  * boost-algorithm[core]:x86-windows -> 1.82.0#1
  * boost-align[core]:x86-windows -> 1.82.0#1
  * boost-asio[core]:x86-windows -> 1.82.0#1
  * boost-build[core]:x64-windows -> 1.82.0#1
  * boost-chrono[core]:x86-windows -> 1.82.0#1
  * boost-container[core]:x86-windows -> 1.82.0#1
  * boost-container-hash[core]:x86-windows -> 1.82.0#1
  * boost-context[core]:x86-windows -> 1.82.0#1
  * boost-conversion[core]:x86-windows -> 1.82.0#1
  * boost-coroutine[core]:x86-windows -> 1.82.0#1
  * boost-date-time[core]:x86-windows -> 1.82.0#1
  * boost-describe[core]:x86-windows -> 1.82.0#1
  * boost-detail[core]:x86-windows -> 1.82.0#1
  * boost-exception[core]:x86-windows -> 1.82.0#1
  * boost-function[core]:x86-windows -> 1.82.0#1
  * boost-function-types[core]:x86-windows -> 1.82.0#1
  * boost-functional[core]:x86-windows -> 1.82.0#1
  * boost-fusion[core]:x86-windows -> 1.82.0#1
  * boost-integer[core]:x86-windows -> 1.82.0#1
  * boost-intrusive[core]:x86-windows -> 1.82.0#1
  * boost-io[core]:x86-windows -> 1.82.0#1
  * boost-iterator[core]:x86-windows -> 1.82.0#1
  * boost-lexical-cast[core]:x86-windows -> 1.82.0#1
  * boost-modular-build-helper[core]:x64-windows -> 1.82.0#1
  * boost-move[core]:x86-windows -> 1.82.0#1
  * boost-mp11[core]:x86-windows -> 1.82.0#1
  * boost-mpl[core]:x86-windows -> 1.82.0#1
  * boost-numeric-conversion[core]:x86-windows -> 1.82.0#1
  * boost-optional[core]:x86-windows -> 1.82.0#1
  * boost-pool[core]:x86-windows -> 1.82.0#1
  * boost-predef[core]:x86-windows -> 1.82.0#1
  * boost-range[core]:x86-windows -> 1.82.0#1
  * boost-ratio[core]:x86-windows -> 1.82.0#1
  * boost-rational[core]:x86-windows -> 1.82.0#1
  * boost-regex[core]:x86-windows -> 1.82.0#1
  * boost-smart-ptr[core]:x86-windows -> 1.82.0#1
  * boost-system[core]:x86-windows -> 1.82.0#1
  * boost-tokenizer[core]:x86-windows -> 1.82.0#1
  * boost-tuple[core]:x86-windows -> 1.82.0#1
  * boost-typeof[core]:x86-windows -> 1.82.0#1
  * boost-unordered[core]:x86-windows -> 1.82.0#1
  * boost-utility[core]:x86-windows -> 1.82.0#1
  * boost-variant2[core]:x86-windows -> 1.82.0#1
  * boost-winapi[core]:x86-windows -> 1.82.0#1
    crow[core]:x86-windows -> 1.0-5
  * vcpkg-cmake[core]:x64-windows -> 2022-12-22
  * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06#1
  * vcpkg-cmake-get-vars[core]:x64-windows -> 2023-03-02
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
Restored 0 package(s) from C:\Users\omaro\AppData\Local\vcpkg\archives in 2.11 ms. Use --debug to see more details.
Installing 1/48 boost-build:x64-windows...
Building boost-build[core]:x64-windows... 
-- Using cached boostorg-build-boost-1.82.0.tar.gz.
-- Cleaning sources at C:/Users/omaro/Repositories/College/quantumdb/cs180-23-quantum/vcpkg/buildtrees/boost-build/src/ost-1.82.0-e88c66a4cd.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/omaro/Repositories/College/quantumdb/cs180-23-quantum/vcpkg/downloads/boostorg-build-boost-1.82.0.tar.gz
-- Applying patch 0002-fix-get-version.patch
-- Applying patch 0003-fix-emscripten.patch
-- Applying patch 0004-workaround-MSVC-codegen-bug-in-17.5-on-ARM64.patch
-- Using source at C:/Users/omaro/Repositories/College/quantumdb/cs180-23-quantum/vcpkg/buildtrees/boost-build/src/ost-1.82.0-e88c66a4cd.clean
-- Using cached boost_LICENSE_1_0.txt.
-- Using cached boost-1.82.0-boostcpp.jam.
-- Installing: C:/Users/omaro/Repositories/College/quantumdb/cs180-23-quantum/vcpkg/packages/boost-build_x64-windows/share/boost-build/copyright
-- Bootstrapping...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/Users/omaro/Repositories/College/quantumdb/cs180-23-quantum/vcpkg/packages/boost-build_x64-windows/tools/boost-build/bootstrap.bat msvc
    Working Directory: C:/Users/omaro/Repositories/College/quantumdb/cs180-23-quantum/vcpkg/packages/boost-build_x64-windows/tools/boost-build
    Error code: 1
    See logs for more information:
      C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-out.log
      C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-err.log

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:65 (vcpkg_execute_required_process)
  scripts/ports.cmake:147 (include)

error: building boost-build:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-build
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[boost-build]+Build+error&body=Copy+issue+body+from+C%3A%2FUsers%2Fomaro%2FRepositories%2FCollege%2Fquantumdb%2Fcs180-23-quantum%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by JonLiu1993** [comment]
@onoss98, Thanks for posting this issue, please provide the error log:
````
See logs for more information:
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-out.log
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-err.log
````

**Comment by onoss98** [comment]
@JonLiu1993,

Thank you for the quick response please see error log below:

Building the B2 engine..
Call_If_Exists "bin\VCVARS32.BAT"
###
### Using 'msvc' toolset.
###

C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine>"cl" /nologo /MP /MT /TP /Feb2 /wd4996 /O2 /GL /EHsc   -DNDEBUG  builtins.cpp class.cpp command.cpp compile.cpp constants.cpp cwd.cpp debug.cpp debugger.cpp execcmd.cpp execnt.cpp execunix.cpp filent.cpp filesys.cpp fileunix.cpp frames.cpp function.cpp glob.cpp hash.cpp hcache.cpp hdrmacro.cpp headers.cpp jam.cpp jamgram.cpp lists.cpp make.cpp make1.cpp md5.cpp mem.cpp modules.cpp native.cpp object.cpp option.cpp output.cpp parse.cpp pathnt.cpp pathsys.cpp pathunix.cpp regexp.cpp rules.cpp scan.cpp search.cpp jam_strings.cpp startup.cpp subst.cpp sysinfo.cpp timestamp.cpp variable.cpp w32_getreg.cpp modules/order.cpp modules/path.cpp modules/property-set.cpp modules/regex.cpp modules/sequence.cpp modules/set.cpp /link kernel32.lib advapi32.lib user32.lib 
builtins.cpp
class.cpp
command.cpp
compile.cpp
constants.cpp
cwd.cpp
debug.cpp
debugger.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\yvals.h(17): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file class.cpp)
execcmd.cpp
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file debug.cpp)
execnt.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\yvals.h(17): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file cwd.cpp)
execunix.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\yvals.h(17): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file constants.cpp)
filent.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\yvals.h(17): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file debugger.cpp)
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file builtins.cpp)
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file command.cpp)
filesys.cpp
fileunix.cpp
frames.cpp
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file compile.cpp)
function.cpp
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file filent.cpp)
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file execunix.cpp)
glob.cpp
hash.cpp
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file execnt.cpp)
hcache.cpp
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file execcmd.cpp)
hdrmacro.cpp
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file fileunix.cpp)
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file frames.cpp)
headers.cpp
jam.cpp
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file function.cpp)
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file filesys.cpp)
jamgram.cpp
lists.cpp
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file glob.cpp)
make.cpp
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file hcache.cpp)
make1.cpp
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file hash.cpp)
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file headers.cpp)
md5.cpp
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file hdrmacro.cpp)
mem.cpp
modules.cpp
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file jam.cpp)
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file jamgram.cpp)
native.cpp
object.cpp
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\md5.h(53): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory (compiling source file md5.cpp)
option.cpp
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file make1.cpp)
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file make.cpp)
output.cpp
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file lists.cpp)
parse.cpp
pathnt.cpp
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file mem.cpp)
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file modules.cpp)
pathsys.cpp
pathunix.cpp
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file object.cpp)
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file option.cpp)
regexp.cpp
rules.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\yvals.h(17): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file native.cpp)
scan.cpp
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file output.cpp)
search.cpp
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file pathnt.cpp)
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file parse.cpp)
jam_strings.cpp
startup.cpp
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file pathsys.cpp)
subst.cpp
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file regexp.cpp)
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file scan.cpp)
sysinfo.cpp
timestamp.cpp
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file pathunix.cpp)
variable.cpp
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file search.cpp)
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file jam_strings.cpp)
w32_getreg.cpp
order.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\yvals.h(17): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file startup.cpp)
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file rules.cpp)
path.cpp
property-set.cpp
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file subst.cpp)
regex.cpp
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file sysinfo.cpp)
sequence.cpp
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file w32_getreg.cpp)
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file timestamp.cpp)
set.cpp
C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(69): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file variable.cpp)
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\yvals.h(17): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file modules/order.cpp)
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\yvals.h(17): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file modules/property-set.cpp)
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\yvals.h(17): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file modules/path.cpp)
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\cstdlib(12): fatal error C1083: Cannot open include file: 'math.h': No such file or directory (compiling source file modules/regex.cpp)
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\yvals.h(17): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file modules/sequence.cpp)
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\yvals.h(17): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file modules/set.cpp)

C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine>dir *.exe 
 Volume in drive C has no label.
 Volume Serial Number is DE33-585B

 Directory of C:\Users\omaro\Repositories\College\quantumdb\cs180-23-quantum\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine


Failed to build the B2 engine.

**Comment by JonLiu1993** [comment]
````
Volume in drive C has no label.
Volume Serial Number is DE33-585B
````
This is not a vcpkg problem, it is that your computer C drive has no label, please refer to this suggestion to try to solve it.
https://stackoverflow.com/questions/60422938/calling-dir-in-cmd-prints-out-volume-in-drive-c-has-no-label

**Comment by JonLiu1993** [comment]
@onoss98, did my suggestion solve your problem?

**Comment by JonLiu1993** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
