### ISSUE TITLE
ITK install fails

### ISSUE THREAD

**Issue by phueac** [Microsoft/vcpkg#3115]
The machine setup: I'm using Windows 10 Anniversary Update. 
The steps to reproduce: run vcpkg install itk
The outcome you expected: Install successful
The actual outcome: Install fails due to CMake error

Here is the error log:

Starting package 8/8: itk:x86-windows
Building package itk[core]:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/vcpkg/packages/itk_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/vcpkg/buildtrees/itk
-- CURRENT_PORT_DIR=C:/vcpkg/ports/itk/.
-- Downloading https://github.com/InsightSoftwareConsortium/ITK/archive/d92873e33e8a54e933e445b92151191f02feab42.tar.gz...
-- Downloading https://github.com/InsightSoftwareConsortium/ITK/archive/d92873e33e8a54e933e445b92151191f02feab42.tar.gz... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting source C:/vcpkg/downloads/InsightSoftwareConsortium-ITK-d92873e33e8a54e933e445b92151191f02feab42.tar.gz
-- Extracting done
-- Configuring x86-windows
CMake Error at C:/vcpkg/scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: C:/vcpkg/buildtrees/itk/x86-windows-rel/vcpkg-parallel-configure
    See logs for more information:
      C:\vcpkg\buildtrees\itk\config-x86-windows-out.log

Call Stack (most recent call first):
  C:/vcpkg/scripts/cmake/vcpkg_configure_cmake.cmake:235 (vcpkg_execute_required_process)
  C:/vcpkg/ports/itk/portfile.cmake:15 (vcpkg_configure_cmake)
  C:/vcpkg/scripts/ports.cmake:72 (include)

Error: Building package itk:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: itk:x86-windows
  Vcpkg version: 0.0.106-2018-03-22-637c9bc0f012e402f5cff5e5f9ac1ca993f89ab8

**Comment by cmpute** [comment]
It helps a lot if you can provide `C:\vcpkg\buildtrees\itk\config-x86-windows-out.log`

**Comment by phueac** [comment]
Hi, I've attached that file to this reply.

[config-x86-windows-out.log](https://github.com/Microsoft/vcpkg/files/1841633/config-x86-windows-out.log)

**Comment by pgrison** [comment]
Same things here. VS2015, ActiveState perl 5.26.1.
Clean "git clone" directly followed by a "vcpkg install itk".

[config-x86-windows-out.log](https://github.com/Microsoft/vcpkg/files/1852710/config-x86-windows-out.log)

> -- Found ZLIB: optimized;D:/Dev/vcpkg/installed/x86-windows/lib/zlib.lib;debug;D:/Dev/vcpkg/installed/x86-windows/debug/lib/zlibd.lib (found version "1.2.11") 
-- Found PNG: optimized;D:/Dev/vcpkg/installed/x86-windows/lib/libpng16.lib;debug;D:/Dev/vcpkg/installed/x86-windows/debug/lib/libpng16d.lib (found version "1.6.34") 
-- Found Perl: C:/Perl64/bin/perl.exe (found version "5.26.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: D:/Dev/vcpkg/buildtrees/itk/x86-windows-dbg
ninja: build stopped: subcommand failed.

**Comment by pgrison** [comment]
After toying around, the git clone of ITKSTLMeshIO might fail due to long path names (one or two d92873e33e8a54e933e445b92151191f02feab42 killing the path length limit). 
Not sure about it.

**Comment by pgrison** [comment]
In the end, i had to disable all "cloned" modules in the portfile, and compile with VS2017.

**Comment by sarthakpati** [comment]
The issue #3684 might be related to this. After searching around for a bit, it might be useful to try the following to increase the **MAX_PATH** length on Windows:

https://msdn.microsoft.com/en-us/library/aa365247(v=vs.85).aspx#maxpath

**Comment by MarkIanHolland** [comment]
I have had the same issue, but I can build successfully after adding `DISABLE_PARALLEL_CONFIGURE` as a parameter of `vcpkg_configure_cmake`.

**Comment by phueac** [comment]
Adding DISABLE_PARALLEL_CONFIGURE to vcpkg_configure_cmake macro in portfile.cmake also fixes this issue for me. Should we make this the default for the ITK portfile?

**Comment by sarthakpati** [comment]
I believe this is an acceptable fix to this problem.

**Comment by phueac** [comment]
I opened PR #3896 for this issue.

**Comment by NancyLi1013** [comment]
Hi @phueac, thanks for posting this issue. It should be fixed now. I can install it successfully on my machine with the latest vcpkg. Please feel free to reopen it or open a new issue. 
@dzenanz, thanks for your PR.
