### ISSUE TITLE
x264 build failure

### ISSUE THREAD

**Issue by duggaraju** [microsoft/vcpkg#31154]
### Operating system

Windows

### Compiler

MinGW

### Steps to reproduce the behavior

```Shell
create a triplet file by copying communit\x64-windows-release.cmake and name it as x64-windows-debug:cmake (change VCPKG_BUILD_TYPE from release to debug).
Alternatively you can just add set(VCPKG_BUILD_TYPE debug) in x64-windows.cmake but change the comman dline accordingly.

vcpkg install x264:x64-windows-debug
```

### Failure logs

-- Building x64-windows-debug-dbg
-- Installing x64-windows-debug-dbg
CMake Error at scripts/cmake/vcpkg_replace_string.cmake:2 (file):
  file failed to open for reading (No such file or directory):

    D:/GitHub/vcpkg/packages/x264_x64-windows-debug/lib/pkgconfig/x264.pc
Call Stack (most recent call first):
  ports/x264/portfile.cmake:127 (vcpkg_replace_string)
  scripts/ports.cmake:147 (include)

error: building x264:x64-windows-debug failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+x264
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[x264]+Build+error
Include '[x264] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454
    vcpkg-scripts version: 5971b7043 2023-04-27 (2 hours ago)

**Comment by dg0yt** [comment]
- x64-windows toolchains are for MSVC, not for MinGW
- The only supported single-config setting is "release".
  However, you are free to modify flags for this configuration. YMMV.

**Comment by dg0yt** [comment]
... so entirely unrelated to x264.

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
