### ISSUE TITLE
vcpkg getting stuck at installing package ("Building x64-windows-dbg")

### ISSUE THREAD

**Issue by BullyWiiPlaza** [microsoft/vcpkg#31181]
**Describe the bug**
I'm trying to install a package, e.g. `vcpkg install opencv[cuda]:x64-windows`.

**Environment**
- OS: `Windows 11 Pro`
- Compiler: `Microsoft (R) C/C++ Optimizing Compiler Version 19.35.32217.1 for x64`

**To Reproduce**
1. `vcpkg install opencv[cuda]:x64-windows`
2. Execution gets stuck at e.g. `-- Building x64-windows-dbg`. I let it run the whole night and it didn't finish so I had to abort it.
**Note:** I was not able to reproduce this on a fresh installation of vcpkg, only on my existing one.

**Expected behavior**
The port installs successfully and does not get stuck on any step.

**Additional context**
I recently deleted the vcpkg `archives` directory, upgraded all ports via `git pull` and `bootstrap-vcpkg.bat` and I also ran the command `vcpkg install opencv[cuda]:x64-windows --recurse` or `vcpkg install opencv[cuda]:x64-windows-static --recurse`.

I already tried a few things to remedy the problem such as deleting the `buildtrees` or `downloads` directory, running `vcpkg clear cache`, running vcpkg with `--clean-after-build` or running vcpkg with the `--debug` flag but neither seems to have helped. What could be the problem?

**Comment by Osyotr** [comment]
What might help is enabling "command line" column in windows task manager and then see what specific command stuck.

**Comment by BullyWiiPlaza** [comment]
I ran it again and enabled the "Command Line" column in the task manager, this is what I saw:

![image](https://user-images.githubusercontent.com/7620135/235344367-0e903059-b126-4eea-9a4d-97ed1281868d.png)

Note that my vcpkg folder is at `C:\vcpkg_old` and in the command line it was stuck at `-- Building x64-windows-rel`:
![image](https://user-images.githubusercontent.com/7620135/235344396-d06f6310-3fe7-4b37-8668-56cc1ab128b1.png)

**Comment by BullyWiiPlaza** [comment]
> @BullyWiiPlaza I'm not able to repro this issue, but it also took a long time for me to build locally(more than 8 hours).

Hi, I downloaded a fresh copy of vcpkg and re-installed the package which worked (it took ~ 3h). Somehow my old installation really got corrupted and stopped installing packages. I was hoping to resolve that instead of spending a whole day/night re-installing but I suppose the issue can be closed now since it's not reproducible.

**Comment by Kichma91** [comment]
Hi, im having the same issue at the moment. Is it normal that it stays on Building x64-windows-dbg for more than 4 hours?

**Comment by freedomtowin** [comment]
It is also getting stuck at  x64-windows-dbg for me, the vcpkg folder storage size is also getting to be very large >10GB after 20min.

**Comment by Osyotr** [comment]
IIRC opencv uses its own nvcc-cmake integration which does not support parallelism so the slow build times are kinda expected.

**Comment by Kichma91** [comment]
It worked out for me. Turns out i had not enough disk space. Consider freeing around 200gb before installation.

Ive seen on other issue thread progress bar was to be implemented few years ago. Still nothing on that tho, would come handy
