### ISSUE TITLE
[feature] vcpkg install package to certain folder

### ISSUE THREAD

**Issue by xiaoyifang** [microsoft/vcpkg#31191]
### Is your feature request related to a problem? Please describe.

I currently work with qmake ,
vcpkg does not work easily with qmake .
I'd like a feature to install the package to certain folders ,so I can include them in the qmake project file.

### Proposed solution

`vcpkg install zlib:x64-windows --dest-dir=xxxxx`

### Describe alternatives you've considered

`vcpkg export ` without generate random folder name should also be ok.

**Comment by Osyotr** [comment]
`--x-install-root`?

**Comment by xiaoyifang** [comment]
> `--x-install-root`?

this is not what I expect , when used this option ,there will be an extra triplet folder in the `install-root`.  I do not want this extra triplet folder.

**Comment by xiaoyifang** [comment]
I think this feature  should make it more easier to integrate with  the automate workflow such as github's

**Comment by dg0yt** [comment]
> this is not what I expect , when used this option ,there will be an extra triplet folder in the `install-root`. I do not want this extra triplet folder.

The triplet folders are needed to separate the host installation from the target installation.

> I think this feature would make it more easier to integrate with the automate workflow such as github's

Can you be more specific?

> I'd like a feature to install the package to certain folders ,so I can include them in the qmake project file.

Doesn't qmake allow you to configure the locations where to find dependencies?
