### ISSUE TITLE
[geos] build failure geos:x64-linux with gcc-13 

### ISSUE THREAD

**Issue by ankurvdev** [microsoft/vcpkg#31197]
### Operating system

Linux (fedora-38)

### Compiler

GCC-13.0.1

### Steps to reproduce the behavior

```Shell
`./vcpkg install geos`
```

### Failure logs

[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/11363547/install-x64-linux-dbg-out.log)

**Comment by dg0yt** [comment]
Upstream: https://github.com/libgeos/geos/issues/860
