### ISSUE TITLE
Change CMAKE_CROSSCOMPILING from ON/OFF to TRUE/FALSE

### ISSUE THREAD

**Issue by SunBlack** [microsoft/vcpkg#31209]
**Describe the bug**

Some projects burn the content of the variable of CMAKE_CROSSCOMPILING into their generated code, so that when using the library it can be recognized whether the library was cross compiled or not.

**To Reproduce**
E.g., see issues here::
- https://github.com/microsoft/vcpkg/pull/30950#issuecomment-1520832119
- https://github.com/microsoft/vcpkg/issues/8104

**Expected behavior**
VCPKG should behave like CMake it does, so patches should not be necessary.

**Additional context**

CMake is using always `TRUE` or `FALSE` for `CMAKE_CROSSCOMPILING ` within their code (not within their tests, but this doesn't matter), see [here](https://gitlab.kitware.com/cmake/cmake/-/blob/v3.26.3/Modules/CMakeDetermineSystem.cmake?ref_type=tags#L162-181). Therefore all projects which using something like `configure_file` to store `CMAKE_CROSSCOMPILING` into a file, a storing `TRUE` or `FALSE`.

In comparison, vcpkg always sets `ON` or `OFF` for this variable in the toolchain files, e.g., here:
https://github.com/microsoft/vcpkg/blob/a5d91f7d264786b42b0d6bb7b1d31a3f2842a39c/scripts/toolchains/windows.cmake#L22-L30

This leads to the issue that the libraries that previously had `FALSE` baked in now have comparisons like `if ("OFF" STREQUAL "FALSE")` (Note: CMake has no inbuild command to compare boolean values for equality, as `STREQUAL` is for strings and `EQUAL` only for numeric values).

To avoid the need for patches in the ports to adjust the baked-in value, it would make sense for vcpkg to adjust to how CMake behaves when invoked without vcpkg.

**Comment by dg0yt** [comment]
Note that changing the toolchain files would invalidate all cached artifacts.

These cases are rare, and IMO the mentioned projects are already broken
- by relying on a particular literal representation of "true" when CMake language actually allows alternatives. 
- by assuming that a cross-built package cannot be re-used in a native context and vice-versa. (Packages can be transferred between machines.)

**Comment by Neumann-A** [comment]
> This leads to the issue that the libraries that previously had FALSE baked in now have comparisons like if ("OFF" STREQUAL "FALSE") (Note: CMake has no in-build command to compare boolean values for equality, as STREQUAL is for strings and EQUAL only for numeric values).

So much nonsense. Use `if("@CMAKE_CROSSCOMPILING@")`. There is no reason to use a "boolean" comparison. `CMAKE_CROSSCOMPILING` can be an input variable to CMake itself so assuming CMake itself sets it is just wrong.

**Comment by SunBlack** [comment]
> So much nonsense. Use `if("@CMAKE_CROSSCOMPILING@")`.

As noted above: It is about comparing boolean values for equality and not about checking which value it has. So it is not about `if("@CMAKE_CROSSCOMPILING@")`, but something like `if("@CMAKE_CROSSCOMPILING@" STREQUAL "FALSE")`.

> `CMAKE_CROSSCOMPILING` can be an input variable to CMake itself so assuming CMake itself sets it is just wrong.

CMake is not wrong at this case as a true constant may be `1`, `ON`, `YES`, `TRUE`, `Y` and a false constant `0`, `OFF`, `NO`, `FALSE`, `N`, `IGNORE`, `NOTFOUND` (see [here](https://cmake.org/cmake/help/latest/command/if.html#basic-expressions)). From the point of view both projects are correct, because both `FALSE` and `OFF` are correct for false constants. Technically, it is also correct that you could set the value from the outside as well - but not in this case. As linked above (to their source code), CMake sets this variable within the determine system step - meaning when `project` is called for the first time, their code is called.

You try it yourself with following CMake code:
```cmake
cmake_minimum_required(VERSION 3.15)
message("CMAKE_CROSSCOMPILING Pre: ${CMAKE_CROSSCOMPILING}")

project(test)
message("CMAKE_CROSSCOMPILING Test: ${CMAKE_CROSSCOMPILING}")

set(CMAKE_CROSSCOMPILING ON)
project(test2)
message("CMAKE_CROSSCOMPILING Test2: ${CMAKE_CROSSCOMPILING}")
```

When calling this via `cmake . -DCMAKE_CROSSCOMPILING=ON` you will get e.g.,:
```
-- Building for: Visual Studio 17 2022
CMAKE_CROSSCOMPILING Pre: ON
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19045.
-- The C compiler identification is MSVC 19.35.32217.1
-- The CXX compiler identification is MSVC 19.35.32217.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMAKE_CROSSCOMPILING Test: FALSE
CMAKE_CROSSCOMPILING Test2: ON
-- Configuring done (2.4s)
```

How you can see: CMake is ignoring basically the externally set value (Ignoring = From the perspective that most projects have the `project` command almost at the beginning of their CMake code). From there, all CMake projects will work with `TRUE` or `FALSE` for this one specific variable unless they manually modify the value.

**Comment by Neumann-A** [comment]
> As noted above: It is about comparing boolean values for equality and not about checking which value it has. So it is not about if("@CMAKE_CROSSCOMPILING@"), but something like if("@CMAKE_CROSSCOMPILING@" STREQUAL "FALSE")

It is about testing `CMAKE_CROSSCOMPILING`. The only way to do that correctly is via:
`if("@CMAKE_CROSSCOMPILING@")`
or
`if("@CMAKE_CROSSCOMPILING@" MATCHES"^(OFF|FALSE|0|NO|<other false criteria>)$")`
using `STREQUAL` assumes an implementation detail of how `CMAKE_CROSSCOMPILING` is set by CMake without taking into account what actual valid `FALSE` values are.

**Comment by SunBlack** [comment]
@Neumann-A I agree that depending on a specific boolean value in CMake is not the best idea. However, since `CMAKE_CROSSCOMPILING` is one of those CMake predefined variables that you don't normally change, I can't really blame the authors of the projects that are based on a fixed value, since unfortunately there is no `BOOL_EQUAL` in CMake and before toolchains became more popular in CMake, it was probably never a issue either.

Btw: I would never using a regex to check for an boolean value in CMake, as the regex engine of CMake is slow. And in this case your alternative suggestion doesn't make much sense either, because it is again only about checking a single value and not about comparing two values (apart from the fact that I think such a list is quite error-prone).

Maybe it would help to understand the problem if I explain the lines that caused the problem in the two referenced projects (geographiclib and liblas) - and who knows how many other projects use that:

These libraries have a line like the following within a file, which will be passed to `configure_file` (see [liblas](https://github.com/libLAS/libLAS/blob/1.8.1/cmake/liblas-config-version.cmake.in#L25)):

```cmake
if (NOT CMAKE_CROSSCOMPILING STREQUAL "@CMAKE_CROSSCOMPILING@")
```

So during `configure_file`, so the "@CMAKE_CROSSCOMPILING@" will replaced by a boolean value. As it seems that the toolchain files of VCPKG will be only used when including an already installed target, but not during `vcpkg install` (or the value will be overwritten by an `project` call there - didn't debugged it), the value will be replaced by `TRUE` or `FALSE`, so you have e.g.,
```cmake
if (NOT CMAKE_CROSSCOMPILING STREQUAL "FALSE")
```

This line will be executed, when you including this project (e.g., `find_package(liblas)`). Usually it works - except you are using VCPKG, as VCPKG is setting the value to `ON` or `OFF`.

Apart from the fact that I don't know if the projects really need to catch the cross compile case, the question now would be which way to go:
- All projects are forced to adapt their code for VCPKG (i.e. a patch for the port is usually added first until it is merged and released upstream), so they are using sth like `if((varA AND @varB@) OR (NOT varA AND NOT @varB@))` instead of `if(varA STREQUAL @varB@)`
- Adapt it vcpkg, which would also benefit other (possibly future) ports that they do not have to patch.

@autoantwort The issue is not about checking for a single value, it is about comparing two boolean values.

@dg0yt 
> Note that changing the toolchain files would invalidate all cached artifacts.

I agree that invalidating a cache is not so wanted. However, it feels like everything is already rebuilt every time I update the manifest file on our project every 1-2 months, since some project gets updated and so do all the ones based on it (even if it wouldn't be necessary, since it's just an ABI compatible update). Or such cases as recently, when arm64ec was added, although one does nothing at all with the ARM architecture. From there I don't see the cache invalidation as a knockout criterion. And since vcpkg also has no major releases, but only date-based version numbers, there is also no perfect time to adjust central changes bundled.

So I would summarize the discussion so far by saying that the decision would be whether to invalidate the cache once or to make all 3rd party projects adapt their code so that the value of `CMAKE_CROSSCOMPILING ` can be represented by different boolean representations, which probably can only happen currently when using toolchains (I have not tested alternatives to vcpkg now).
