### ISSUE TITLE
Add documentation for vcpkg artifacts 

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vcpkg#31204]
**Describe the bug**
There is currently no documentation how to use vcpkg artifacts. 

**Expected behavior**
Add documentation how to use vcpkg artifacts to https://learn.microsoft.com/en-us/vcpkg/. 

**Additional context**
There are blog posts like https://devblogs.microsoft.com/cppblog/vcpkg-artifacts/ and https://devblogs.microsoft.com/cppblog/vcpkg-may-2022-release-is-now-available/ and kind of https://github.com/microsoft/vcpkg-tool#vcpkg-artifacts

**Comment by JonLiu1993** [comment]
As part of our transition to learn.microsoft.com, all new documentation-related PRs / issues should be closed and reopened against the vcpkg-docs repo.
