### ISSUE TITLE
[gtk3] build failure when `gobject-introspection` is installed

### ISSUE THREAD

**Issue by AenBleidd** [microsoft/vcpkg#31222]
### Operating system

Linux

### Compiler

GCC

### Steps to reproduce the behavior

```Shell
sudo apt-get install gobject-introspection
./vcpkg install gtk3
```

### Failure logs

When `gobject-introspection` is installed and is reachable:

```
/snap/gnome-42-2204-sdk/current/usr/bin/g-ir-scanner
```

then even if in the port configuration it's set to not use introspection:

```
Build Options: -Dintrospection=false -Dwayland_backend=false -Ddemos=false -Dexamples=false -Dtests=false -Dgtk_doc=false -Dman=false -Dxinerama=no -Dcloudproviders=false -Dprofiler=false -Dtracker3=false -Dcolord=no -Ddebug=false '-Dcmake_prefix_path=['"'"'/root/parts/boinc/build/3rdParty/linux/vcpkg/installed/snap-linux-amd64'"'"','"'"'/root/parts/boinc/build/3rdParty/linux/vcpkg/installed/snap-linux-amd64/debug'"'"']' -Dprefix=/root/parts/boinc/build/3rdParty/linux/vcpkg/packages/gtk3_snap-linux-amd64 -Dlibdir=lib -Dbackend=ninja -Dbuildtype=plain -Dwrap_mode=nodownload '--native-file /root/parts/boinc/build/3rdParty/linux/vcpkg/buildtrees/gtk3/meson-snap-linux-amd64-rel.log'
```

This tool is found from the `meson.build` file (`git.found()` is true because this tool is found in the system paths even if we don't set them in the port configuration):

```
# Introspection
gir = find_program('g-ir-scanner', required : get_option('introspection'))
build_gir = gir.found() and (not meson.is_cross_build() or get_option('introspection'))
```

And then this build is failed with the next error (probably because our `pkg-config` located within vcpkg directory knows nothing about this tool installed):

```
Determining dependency 'gobject-introspection-1.0' with pkg-config executable '/bin/pkg-config'
env[PKG_CONFIG_PATH]: /root/parts/boinc/build/3rdParty/linux/vcpkg/installed/snap-linux-amd64/lib/pkgconfig/:/root/parts/boinc/build/3rdParty/linux/vcpkg/installed/snap-linux-amd64/share/pkgconfig/
env[PKG_CONFIG]: /bin/pkg-config
Called `/bin/pkg-config --modversion gobject-introspection-1.0` -> 1

CMake binary for 1 is cached.
Preliminary CMake check failed. Aborting.
Run-time dependency gobject-introspection-1.0 found: NO (tried pkgconfig and cmake)

../src/3.24.36-4cf901097d.clean/gdk/meson.build:328:2: ERROR: Dependency "gobject-introspection-1.0" not found, tried pkgconfig and cmake
```

### Additional context

I'm not completely sure this is an issue with the port or with the `meson.build` file itself.

**Comment by AenBleidd** [comment]
Forgot to mention: this is broken after #31047

**Comment by dg0yt** [comment]
That's a a variant fo #31128.

**Comment by AenBleidd** [comment]
@dg0yt, yeah, looks like, just the different error message

**Comment by dg0yt** [comment]
I had to make adjustment because gtk3 changed in some way with regard to gobject-introspection. The bug seems to appear only when there is another source of the tools than just vcpkg.

**Comment by AenBleidd** [comment]
@dg0yt,
what if just change `meson.buil` from this:
```
gir = find_program('g-ir-scanner', required : get_option('introspection'))
build_gir = gir.found() and (not meson.is_cross_build() or get_option('introspection'))
```
to this:
```
gir = find_program('g-ir-scanner', required : get_option('introspection'))
build_gir = gir.found() and (not meson.is_cross_build() and get_option('introspection'))
```
?

**Comment by dg0yt** [comment]
Something like this.  I think we need to remove the cross_build part. It interfers with the explicit option.

https://gitlab.gnome.org/GNOME/gtk/-/commit/7e4a2a5724a184c418314f4fdbd7a065ba9e203d

**Comment by AenBleidd** [comment]
@dg0yt, that's exactly the change that should be added to vcpkg port while waiting for the new release.
Do you want to handle this by yourself or you prefer me to do that?

**Comment by dg0yt** [comment]
> @dg0yt, that's exactly the change that should be added to vcpkg port while waiting for the new release. 

... if there would have been any indication of the problem of gtk3 enabling introspection due to external tools... 
I had to solve a different problem, gtk3 looking for tools which were *not* installed.

> Do you want to handle this by yourself or you prefer me to do that?

You can go ahead if you want: Update to 3.24.37 and maybe revise the changes to additional tools.

**Comment by jerrywrice** [comment]
I'm encountering what appears to be a related build bug for gtk4 on Windows 10. I just brought down and experience the following error for the visual studio build when executing 'gvsbuild build --enable-gi --py-wheel gtk4 pygobject' 
Error log is =>

Building project msys2 (undefined)
(tar) Exporting gobject-introspection
Building project gobject-introspection (1.74.0)
usage: meson [-h]
             {setup,configure,dist,install,introspect,init,test,wrap,subprojects,rewrite,compile,devenv,env2mfile,help}
             ...
meson: error: unrecognized arguments: W. Rice\.local\pipx\venvs\gvsbuild\Scripts\python.exe
Traceback (most recent call last):
  File "C:\Users\Jerry W. Rice\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 520, in build
    if self.__build_one(p):
       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jerry W. Rice\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 656, in __build_one
    skip_deps = proj.build()
                ^^^^^^^^^^^^
  File "C:\Users\Jerry W. Rice\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\projects\gobject_introspection.py", line 62, in build
    Meson.build(
  File "C:\Users\Jerry W. Rice\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\base_builders.py", line 49, in build
    self._setup_meson_and_ninja(ninja_build, meson_params, add_path)
  File "C:\Users\Jerry W. Rice\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\base_builders.py", line 81, in _setup_meson_and_ninja
    self.exec_vs(cmd, add_path=add_path)
  File "C:\Users\Jerry W. Rice\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\base_project.py", line 195, in exec_vs
    self.builder.exec_vs(
  File "C:\Users\Jerry W. Rice\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 930, in exec_vs
    self.__execute(
  File "C:\Users\Jerry W. Rice\.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py", line 1032, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python311\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '"C:\Users\Jerry W. Rice\.local\pipx\venvs\gvsbuild\Scripts\python.exe" C:\gtk-build\tools\meson-1.0.1\meson.py C:\gtk-build\build\x64\release\gobject-introspection C:\gtk-build\build\x64\release\gobject-introspection\_gvsbuild-meson --prefix C:\gtk-build\gtk\x64\release --buildtype debugoptimized -Dpython=C:\Users\Jerry W. Rice\.local\pipx\venvs\gvsbuild\Scripts\python.exe -Dcairo_libname=cairo-gobject-2.dll' returned non-zero exit status 2.
Error: gobject-introspection build failed

**Comment by dg0yt** [comment]
@jerrywrice Unrelated. Avoid space in paths. Including your user name.
~~~
meson: error: unrecognized arguments: W. Rice.local\pipx\venvs\gvsbuild\Scripts\python.exe
...
File "C:\Users\Jerry W. Rice.local\pipx\venvs\gvsbuild\Lib\site-packages\gvsbuild\utils\builder.py"
Note:                ^
