### ISSUE TITLE
[vulkan] Can't build vulkan

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [microsoft/vcpkg#31225]
### Operating system

Windows 10 Pro x64 Bits

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
./vcpkg install vulkan
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
    vulkan[core]:x86-windows -> 1.1.82.1#6
Detecting compiler hash for triplet x86-windows...
Restored 0 package(s) from C:\Users\Krispy\AppData\Local\vcpkg\archives in 542 us. Use --debug to see more details.
Installing 1/1 vulkan:x86-windows...
Building vulkan[core]:x86-windows...
-- Found external ninja('1.11.0').
-- Configuring x86-windows
CMake Error at ports/vulkan/portfile.cmake:30 (message):
  The Vulkan SDK wasn't found.  Refer to Getting Started with the Windows
  Vulkan SDK:
  https://vulkan.lunarg.com/doc/sdk/latest/windows/getting_started.html
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)

error: building vulkan:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+vulkan
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[vulkan]+Build+error&body=Copy+issue+body+from+C%3A%2FUsers%2FKrispy%2FDocuments%2FGithub%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

I Wanted to use vulkan has part of my vcpkg build system using the vcpkg.json file, i added vulkan port in the file and once i ran CMake on my project i found out that it can't build vulkan because of the port not finding the vulkan sdk

**Comment by autoantwort** [comment]
Have you installed the vulkan SDK?

**Comment by FriskTheFallenHuman** [comment]
> Have you installed the vulkan SDK?

nope

**Comment by autoantwort** [comment]
Yeah you have to install it
