### ISSUE TITLE
[opencascade] build failure: GL/gl.h: no such file or directory

### ISSUE THREAD

**Issue by huangdade** [microsoft/vcpkg#31238]
### Operating system

Linux docker

### Steps to reproduce the behavior

```Shell
./vcpkg install opencascade[core]:x64-linux
```

### Failure logs

![图片](https://user-images.githubusercontent.com/4537048/236079404-91dfbebd-e966-4fd2-907d-2e55912e7911.png)

**Comment by huangdade** [comment]
Cloud I set HAVE_OPENGL to OFF?

**Comment by LilyWangLL** [comment]
`opencascade` requires the system library `libgl`, please install it by command `sudo apt install libgl-dev`

**Comment by PhoebeHui** [comment]
@huangdade, does this still be a problem for you?

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
