### ISSUE TITLE
Incomparable version schemes. How do you specify the scheme?

### ISSUE THREAD

**Issue by varunsh-xilinx** [microsoft/vcpkg#31237]
**Describe the bug**
I'm trying to install a port but there doesn't seem to be a way to specify the version scheme when specifying a minimum version.

**Environment**
- OS: Ubuntu 20.04
- Compiler: GCC 9

**To Reproduce**
I'm using the 2023.04.15 release of vcpkg in manifest mode with CMake. Here's my vcpkg.json:

```json
{
    "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg.schema.json",
    "dependencies": [
        {
            "name": "cxxopts",
            "version>=": "2.2.1"
        }
    ],
    "vcpkg-configuration": {
        "default-registry": {
            "kind": "git",
            "repository": "https://github.com/microsoft/vcpkg",
            "baseline": "501db0f17ef6df184fcdbfbe0f87cde2313b6ab1"
        }
    }
}
```

The error that I see during the build:

```
error: version conflict on cxxopts:x64-linux: baseline required 3.1.1 but vcpkg could not compare it to 2.2.1.
The two versions used incomparable schemes:
    "2.2.1" was of scheme string
    "3.1.1" was of scheme semver
This can be resolved by adding an explicit override to the preferred version, for example:
    "overrides": [
        { "name": "cxxopts", "version": "2.2.1" }
    ]
```

I can work around the error by adding an explicit override as it suggests (and I confirmed it works) but I shouldn't need to. I understand it won't compare different version schemes but how do I tell it that this version I'm providing is actually a semver? Is the JSON schema incomplete or is this a missing feature?

**Expected behavior**
You should be able to specify the version correctly in the right scheme without needing an override.

**Comment by Cheney-W** [comment]
This issue could be reproduced with the latest vcpkg. And this issue exists in all ports where the `"version"` attribute in `vcpkg.json` has changed.

**Comment by dg0yt** [comment]
> I understand it won't compare different version schemes but how do I tell it that this version I'm providing is actually a semver?

It is not about the version *you*  are providing. It is about the version *recorded* here:
https://github.com/microsoft/vcpkg/blob/master/versions/c-/cxxopts.json

As you can see, vcpkg used `version-string` up to `2.2.1`. You can only do exact matches for the old versions. You can use `version>=` for values starting at `3.0.0`.

**Comment by BillyONeal** [comment]
The version scheme is that declared by the port. If the port declares schemes that are incomparable the only option is to tell vcpkg which one you want with an override.
