### ISSUE TITLE
[qt5-webengine] build failure

### ISSUE THREAD

**Issue by RainbowTaro2022** [microsoft/vcpkg#31241]
### Operating system

windows

### Compiler

msvc

### Steps to reproduce the behavior

```Shell
vcpkg install qt5-webengine:x64-windows
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
    qt5-webengine[core]:x64-windows -> 5.15.9
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from G:\Users\LuLujiang\AppData\Local\vcpkg\archives in 235 us. Use --debug to see more details.
Installing 1/1 qt5-webengine:x64-windows...
Building qt5-webengine[core]:x64-windows...
CMake Warning at scripts/cmake/vcpkg_buildpath_length_warning.cmake:4 (message):
  qt5-webengine's buildsystem uses very long paths and may fail on your
  system.

  We recommend moving vcpkg to a short path such as 'C:\src\vcpkg' or using
  the subst command.
Call Stack (most recent call first):
  ports/qt5-webengine/portfile.cmake:4 (vcpkg_buildpath_length_warning)
  scripts/ports.cmake:147 (include)

CMake Warning at ports/qt5-webengine/portfile.cmake:5 (message):
  The qt5-webengine source was will be extracted to
  G:/Cone/vcpkg/buildtrees/qt5-webengine , which has more then 35 characters
  in length.
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)

CMake Error at ports/qt5-webengine/portfile.cmake:6 (message):
  terminating due to G:/Cone/vcpkg/buildtrees/qt5-webengine being too long.
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)

### Additional context

MITK requires a web engine of qt5 to compile, but I was about to install it when suddenly it stopped working. My request is that the directory remain unchanged, just provide me with an accurate solution

**Comment by autoantwort** [comment]
> We recommend moving vcpkg to a short path such as 'C:\src\vcpkg' or using
the subst command.

**Comment by RainbowTaro2022** [comment]
可以了，但是

**Comment by RainbowTaro2022** [comment]
warning: The vcpkg G:\vcpkg\vcpkg.exe is using detected vcpkg root G:\vcpkg and ignoring mismatched VCPKG_ROOT environment value G:\Cone\vcpkg. To suppress this message, unset the environment variable or use the --vcpkg-root command line switch.
Computing installation plan...
The following packages will be built and installed:
    qt5-webengine[core]:x64-windows -> 5.15.9
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from G:\Users\LuLujiang\AppData\Local\vcpkg\archives in 250 us. Use --debug to see more details.
Installing 1/1 qt5-webengine:x64-windows...
Building qt5-webengine[core]:x64-windows...
-- qt5-webengine requires a lot of free disk space (>100GB), ram (>8 GB) and time (>2h per configuration) to be successfully build.
-- As such qt5-webengine is currently experimental.
-- If qt5-webengine fails post build validation please try manually reducing VCPKG_MAX_CONCURRENCY and open up an issue if it still cannot build.
-- If it fails due to post validation the successfully installed files can be found in G:/vcpkg/packages/qt5-webengine_x64-windows
-- and just need to be copied into G:/vcpkg/installed/x64-windows
-- Downloading https://sourceforge.net/projects/gnuwin32/files/gperf/3.0.1/gperf-3.0.1-bin.zip/download -> gperf-3.0.1-bin.zip...
-- Using cached python-2.7.18.amd64.msi.
-- Found external ninja('1.11.0').
-- Downloading https://download.qt.io/official_releases/qt/5.15/5.15.9/submodules/qtwebengine-everywhere-opensource-src-5.15.9.tar.xz;https://mirrors.ocf.berkeley.edu/qt/official_releases/qt/5.15/5.15.9/submodules/qtwebengine-everywhere-opensource-src-5.15.9.tar.xz -> qtwebengine-everywhere-opensource-src-5.15.9.tar.xz...
-- Extracting source G:/vcpkg/downloads/qtwebengine-everywhere-opensource-src-5.15.9.tar.xz
-- Applying patch common.pri.patch
-- Applying patch gl.patch
-- Applying patch build_1.patch
-- Applying patch build_2.patch
-- Applying patch build_3.with_missing_stdbool_include.patch
-- Applying patch workaround-msvc2022-ice.patch
-- Applying patch workaround-msvc2022-missing-include-in-chromium-ui-accessability.patch
CMake Error at scripts/cmake/vcpkg_extract_source_archive.cmake:159 (file):
  file RENAME failed to rename

    G:/vcpkg/buildtrees/qt5-webengine/src/5.15.9-f5cb7722d8.clean.tmp/qtwebengine-everywhere-src-5.15.9

  to

    G:/vcpkg/buildtrees/qt5-webengine/src/5.15.9-f5cb7722d8.clean

  because: �ܾ����ʡ�



Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:8 (vcpkg_extract_source_archive)
  installed/x64-windows/share/qt5/qt_download_submodule.cmake:32 (vcpkg_extract_source_archive_ex)
  installed/x64-windows/share/qt5/qt_submodule_installation.cmake:5 (qt_download_submodule)
  ports/qt5-webengine/portfile.cmake:69 (qt_submodule_installation)
  scripts/ports.cmake:147 (include)

**Comment by autoantwort** [comment]
> because: �ܾ����ʡ�

??

**Comment by jimwang118** [comment]
You can try to clear this folder (`G:/vcpkg/buildtrees/qt5-webengine/src`), and then recompile.

**Comment by jimwang118** [comment]
> > You can try to clear this folder (`G:/vcpkg/buildtrees/qt5-webengine/src`), and then recompile.
> 
> 你的建议我采纳了

Can recompilation be successful after clearing the files from the previous installation?
