### ISSUE TITLE
[libmysql] build failure

### ISSUE THREAD

**Issue by cd606** [microsoft/vcpkg#31251]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
`./vcpkg install libmysql[core]:x64-windows`
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
    libmysql[core]:x64-windows -> 8.0.32#2
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\<user>\AppData\Local\vcpkg\archives in 176 us. Use --debug to see more details.
Installing 1/1 libmysql:x64-windows...
Building libmysql[core]:x64-windows...
-- Downloading https://github.com/mysql/mysql-server/archive/mysql-8.0.32.tar.gz -> mysql-mysql-server-mysql-8.0.32.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from C:\Users\<user>\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: C:\Users\<user>\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
Downloading https://github.com/mysql/mysql-server/archive/mysql-8.0.32.tar.gz
[DEBUG] Trying to hash C:\Users\<user>\vcpkg\downloads\mysql-mysql-server-mysql-8.0.32.tar.gz.38604.part
[DEBUG] C:\Users\<user>\vcpkg\downloads\mysql-mysql-server-mysql-8.0.32.tar.gz.38604.part has hash 8b9f15b301b158e6ffc99dd916b9062968d36f6bdd7b898636fa61badfbe68f7328d4a39fa3b8b3ebef180d3aec1aee353bd2dac9ef1594e5772291390e17ac0
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/mysql/mysql-server/archive/mysql-8.0.32.tar.gz
File: C:\Users\<user>\vcpkg\downloads\mysql-mysql-server-mysql-8.0.32.tar.gz.38604.part
Expected hash: 1233abe4fe055f62cc28c847e77bcfc37e03e77ee68b8606e5ad722e0b6d1ae30b95bbe623a88cecdfa0b5868b61eabaf4b99e78cb6fbb9cf3627c91d17feb0e
Actual hash: 8b9f15b301b158e6ffc99dd916b9062968d36f6bdd7b898636fa61badfbe68f7328d4a39fa3b8b3ebef180d3aec1aee353bd2dac9ef1594e5772291390e17ac0
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(961):
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 2us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 2948us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 36 s (36244576us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/libmysql/portfile.cmake:9 (vcpkg_from_github)
  scripts/ports.cmake:147 (include)

error: building libmysql:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libmysql
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[libmysql]+Build+error&body=Copy+issue+body+from+C%3A%2FUsers%2F<user>%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by autoantwort** [comment]
Fixed by https://github.com/microsoft/vcpkg/pull/31243
