### ISSUE TITLE
[qtbase] Avoid absolute paths in .pc-files (yields to incorrect binary caching)

### ISSUE THREAD

**Issue by RealLitb** [microsoft/vcpkg#31259]
### Is your feature request related to a problem? Please describe.

The PC files generated by the qtbase recipe contains absolute paths such as:

    prefix=/home/jschaub/git/vcpkg/packages/qtbase_x64-mingw-dynamic

Other pkgconfig files solve that by using 

    prefix=${pcfiledir}/../..

Maybe they can be patched before installing? Otherwise, the caching is wrong. I installed qtbase to a different `--x-install-root`, but got incorrect (cached) PC files that contain the old install root.

### Proposed solution

I would propose patching the PC files before installing, to remove the absolute path from the PC files. Or simply not installing the files. They appear to be not installed when compiling for `x64-linux` triplet. But for `x64-mingw-dynamic`, they are. The official Qt-installer does not ship them anymore for Qt6.

### Describe alternatives you've considered

I don't use the PC files, so I didn't need to consider alternatives.

**Comment by Neumann-A** [comment]
> Maybe qtbase needs a vcpkg_fixup_pkgconfig call.

Qt needs a `vcpkg_fixup_pkgconfig` call but none of the official CI triplets even generates pc files.

**Comment by dg0yt** [comment]
> but none of the official CI triplets even generates pc files.

... vcpkg still lacks CI tests for any non-MSVC triplet with dynamic linkage.

**Comment by Neumann-A** [comment]
To add further details to this: Since the .pc files are cmake generated and the build scripts have all the infos needed to actually generated relocatable .pc files I consider this an upstream issue and didn't add `vcpkg_fixup_pkgconfig` to the build of the qt modules.

**Comment by dg0yt** [comment]
`vcpkg_fixup_pkgconfig` does more now than just fixing up paths. IMO it should always be used when there are pc files, as long as vcpkg has no better checks.

It is CMake itself which provides a very inconsistent user experience with regard to pkg-config. As with Qt or vcpkg, quality is very much dependent on ... contributors.

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.

**Comment by RealLitb** [comment]
> This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.

My coworker hit this issue independently today and some time was wasted to investigate the cause of the warning. I still consider it an issue.

Maybe some ports in VCPKG use GNU autoconf and pkgconfig to find Qt and those will then fail if a binary cache artifact of qtbase is used and the install directory is different (very likely in manifest mode).
