### ISSUE TITLE
[numcpp] update to 2.10.1

### ISSUE THREAD

**Issue by CCXXXI** [microsoft/vcpkg#31268]
### Library name

numcpp

### New version number

2.10.1

### Other information that may be useful (release notes, etc...)

- https://github.com/dpilger26/NumCpp
- #26476
- #26482

**Comment by jimwang118** [comment]
Duplicate https://github.com/microsoft/vcpkg/issues/26476, being fixed by PR https://github.com/microsoft/vcpkg/pull/26482.
