### ISSUE TITLE
[log4cpp] incorrect upstream & version

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#31273]
https://stackoverflow.com/questions/76091004/does-vcpkg-incorrectly-delivers-an-old-version-of-log4cpp

From that post it seems the current port should be `orcos-log4cpp` while the correct upstream for `log4cpp` is https://sourceforge.net/projects/log4cpp/

https://repology.org/project/log4cpp/versions
https://repology.org/project/log4cpp-orocos/versions

Fixing this probably requires purging the whole version database for `log4cpp`

**Comment by JonLiu1993** [comment]
Thanks for posting this issue, I've identified this bug locally, and I'll investigate whether removing the whole version database for `log4cpp` will have an impact on the use of previous versions of ports that depend on it.
