### ISSUE TITLE
[vcpkg-tool] Allow to link Spectre-mitigated MSVC runtime libraries

### ISSUE THREAD

**Issue by AntonLapounov** [microsoft/vcpkg#31283]
In order to link Spectre-mitigated MSVC runtime libraries (e.g., `msvcrt.lib` and `vcruntime.lib`), `vcpkg` tool needs to run `vcvarsall.bat` script with `-vcvars_spectre_libs=spectre` option.  At present, that is not configurable with VCPKG variables.  A possible hacky workaround is to `set __VCVARSALL_SPECTRE=spectre` in the environment and `set(VCPKG_ENV_PASSTHROUGH "__VCVARSALL_SPECTRE")` in a triplet file.  That is far from perfect, because variables starting with `__` are meant to be internal to `vcvarsall.bat`.

Please provide a clean way to link Spectre-mitigated MSVC runtime libraries.

**Comment by Neumann-A** [comment]
> Please provide a clean way to link Spectre-mitigated MSVC runtime libraries.

What is unclean about running vcvarsall.bat manually and defining a toolchain with the correct flags? As soon as you define a toolchain file vcpkg won't load  `vcvarsall` itself (unless told to do that)

**Comment by AntonLapounov** [comment]
@Neumann-A Could you please elaborate on the steps required or provide an example?

**Comment by Neumann-A** [comment]
- make a copy of `scripts/toolchains/windows.cmake` and rename it to `windows-spectre.cmake`
- add required compiler flags to `windows-spectre.cmake` (this is the toolchain)
- create a copy of `triplets/x64-windows.cmake` and rename it to `x64-windows-spectre.cmake`
- add `set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "<wherever you put windows-spectre.cmake>")` to the triplet (this deactivates loading of vcvars inside vcpkg unless `VCPKG_LOAD_VCVARS_ENV` is set to `ON`)

Run vcpkg with the `x64-windows-spectre.cmake` triplet in an environment where vcvars was manually called.

**Comment by AntonLapounov** [comment]
Thank you a lot.  That works for me only if I also `set(VCPKG_ENV_PASSTHROUGH "INCLUDE;LIB;PATH")` in the triplet file.  Some other variables that `vcvarsall.bat` sets might also be needed for a build.  At this point, it doesn't look like a perfect approach.

**Comment by AntonLapounov** [comment]
Is there a chance to add configuration for linking Spectre-mitigated MSVC runtime libraries?
