### ISSUE TITLE
Error: Building package sdl2:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by lirenjiang548** [Microsoft/vcpkg#3128]
I'm sure vcpkg is the latest portfiles, but it also show error as:
Error: Building package sdl2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sdl2:x86-windows
  Vcpkg version: 0.0.106-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by miurahr** [comment]
Could you try a solution described in [another issue](https://github.com/Microsoft/vcpkg/issues/1797#issuecomment-377559384)?

**Comment by JackBoosY** [comment]
Hi @lirenjiang548 , thanks for reporting this issue.
Please open a new issue if this is still a problem for you.
Thx.
