### ISSUE TITLE
Binary caching with AWS fails with message: Could not fetch aws

### ISSUE THREAD

**Issue by matusnovak** [microsoft/vcpkg#31292]
**Describe the bug**

I am trying to set up binary caching with AWS S3. The `vcpkg install` step fails with:

```
Attempting to fetch 1 package(s) from AWS
[DEBUG] Found path: /usr/bin/aws
[DEBUG] 1004: popen( /usr/bin/aws --version 2>&1)
[DEBUG] 1004: cmd_execute_and_stream_data() returned 0 after   238149 us
error: Could not fetch aws. You may be able to install this tool via your system package manager.
note: updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
```

(an entire debug log attached below)

However, I do have aws CLI installed in my system at `/usr/bin/aws`. When looking into the debug log, I can see that vcpkg tries to `popen` the correct `/usr/bin/aws` and returns code 0.

Running `/usr/bin/aws --version 2>&1` manually does run successfully and returns exit code 0:

```
~$ /usr/bin/aws --version 2>&1
aws-cli/1.27.89 Python/3.10.10 Linux/6.1.25-1-MANJARO botocore/1.29.84
```

I do have the correct AWS credentials (with `AmazonS3FullAccess`) and I am able to list bucket, get objects, etc, with the bucket when running `/usr/bin/aws` from the command line.

The binary caching is configured as:

```
export VCPKG_BINARY_SOURCES=x-aws,s3://mnovak-vcpkg-test-bucket/vcpkg-cache/,readwrite
```

The `/usr/bin/aws` appears as a Python script (this is to be expected):

```
~$ file /usr/bin/aws
/usr/bin/aws: Python script, ASCII text executable
```

**Environment**
- vcpkg: 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895
- OS: Linux 6.1.25-1-MANJARO
- AWS CLI: aws-cli/1.27.89 Python/3.10.10 Linux/6.1.25-1-MANJARO botocore/1.29.84

**The exact same setup was also tried on the `ubuntu:22.04` Docker image and it produced the exact same error.**

**To Reproduce**

1. Install the latest vcpkg from the master branch.
2. Install the latest AWS CLI.
3. Create a S3 bucket and an IAM user with full S3 access.
4. Configure credentials on your system.
5. Do `export VCPKG_BINARY_SOURCES=x-aws,s3://some-s3-bucket-name/vcpkg-cache/,readwrite`
6. Run `vcpkg install --triplet x64-linux stb --debug`
7. The command will fail with the message: `error: Could not fetch aws.`

**Expected behavior**
Vcpkg will upload the binary cache to the AWS S3 bucket.

**Failure logs**

[failure-vcpkg-aws-s3.log](https://github.com/microsoft/vcpkg/files/11412954/failure-vcpkg-aws-s3.log)

**Additional context**
None.

**Comment by autoantwort** [comment]
The minimum version you must provide is `2.4.4`

**Comment by matusnovak** [comment]
Oh! I understand now. Thank you very much.

The error message was a bit confusing. Fixed by installing AWS CLI v2 via `sudo pacman -S aws-cli-v2` on Manjaro.
