### ISSUE TITLE
[python3] build failure

### ISSUE THREAD

**Issue by yonamine** [microsoft/vcpkg#31296]
### Operating system

MacOS

### Compiler

AppleClang

### Steps to reproduce the behavior

```Shell
`./vcpkg install python3`
```

### Failure logs

Package: python3[core]:x64-osx -> 3.10.7#5

**Host Environment**

- Host: x64-osx
- Compiler: AppleClang 14.0.3.14030022
-    vcpkg-tool version: 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895
    vcpkg-scripts version: 501db0f17 2023-04-15 (3 weeks ago)

**To Reproduce**

`vcpkg install python3`

**Failure logs**

```
-- Using cached python-cpython-v3.10.7.tar.gz.
-- Cleaning sources at /Users/developer/Projects/vcpkg/buildtrees/python3/src/v3.10.7-a83fe77705.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/developer/Projects/vcpkg/downloads/python-cpython-v3.10.7.tar.gz
-- Applying patch 0001-only-build-required-projects.patch
-- Applying patch 0003-use-vcpkg-zlib.patch
-- Applying patch 0004-devendor-external-dependencies.patch
-- Applying patch 0005-dont-copy-vcruntime.patch
-- Applying patch 0008-python.pc.patch
-- Applying patch 0009-bz2d.patch
-- Applying patch 0010-dont-skip-rpath.patch
-- Applying patch 0012-force-disable-curses.patch
-- Applying patch 0013-configure-no-libcrypt.patch
-- Applying patch 0002-static-library.patch
-- Using source at /Users/developer/Projects/vcpkg/buildtrees/python3/src/v3.10.7-a83fe77705.clean
-- Found external ninja('1.11.1').
-- Getting CMake variables for x64-osx-dbg
-- Getting CMake variables for x64-osx-rel
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
-- Installing x64-osx-dbg
-- Building x64-osx-rel
-- Installing x64-osx-rel
-- Installing: /Users/developer/Projects/vcpkg/packages/python3_x64-osx/share/python3/copyright
-- Fixing pkgconfig file: /Users/developer/Projects/vcpkg/packages/python3_x64-osx/lib/pkgconfig/python-3.10-embed.pc
-- Fixing pkgconfig file: /Users/developer/Projects/vcpkg/packages/python3_x64-osx/lib/pkgconfig/python-3.10.pc
-- Fixing pkgconfig file: /Users/developer/Projects/vcpkg/packages/python3_x64-osx/debug/lib/pkgconfig/python-3.10-embed.pc
-- Fixing pkgconfig file: /Users/developer/Projects/vcpkg/packages/python3_x64-osx/debug/lib/pkgconfig/python-3.10.pc
CMake Error at ports/python3/portfile.cmake:272 (message):
  There should be no modules with "_failed" suffix:


  /Users/developer/Projects/vcpkg/packages/python3_x64-osx/debug/lib/python3.10/lib-dynload/_hashlib.cpython-310d-darwin_failed.so



  /Users/developer/Projects/vcpkg/packages/python3_x64-osx/debug/lib/python3.10/lib-dynload/_ssl.cpython-310d-darwin_failed.so



  /Users/developer/Projects/vcpkg/packages/python3_x64-osx/debug/lib/python3.10/lib-dynload/_tkinter.cpython-310d-darwin_failed.so



  /Users/developer/Projects/vcpkg/packages/python3_x64-osx/lib/python3.10/lib-dynload/_hashlib.cpython-310-darwin_failed.so



  /Users/developer/Projects/vcpkg/packages/python3_x64-osx/lib/python3.10/lib-dynload/_ssl.cpython-310-darwin_failed.so



  /Users/developer/Projects/vcpkg/packages/python3_x64-osx/lib/python3.10/lib-dynload/_tkinter.cpython-310-darwin_failed.so
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)



```

**Additional context**

**Comment by jimwang118** [comment]
I did not reproduce this issue locally, and the compilation result is as shown in the figure below.
![image](https://user-images.githubusercontent.com/122244446/236719340-647eb6aa-a481-4ddf-8094-1cd4d4deff65.png)

**Comment by yonamine** [comment]
It's still reproducing here:
- master not compiling
- tags:
  - 2022.06.15 : compiling
  - 2022.07.25 : compiling
  - 2022.08.15 : not compiling
  - 2022.09.27 and later : not compiling

**Comment by yonamine** [comment]
Same error.

I am supposing that your suggestion is for MacOS (replacing ".\" to "./" and ".bat" to ".sh")

It's weird... In case of Windows 11 + VS toolchain, for the same tag, it's built successfully.

**Comment by jimwang118** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.

**Comment by yonamine** [comment]
I found a workaround. It's similar to https://github.com/microsoft/vcpkg/issues/28273 but in the author's case, the issue is _curses_ library.
Also, there's this issue https://github.com/microsoft/vcpkg/issues/31633. The library is _tkinter_ which is the same as I reported.
Maybe it has overlap or conflict with brew (I have it installed on my machine as well) but not sure. I cannot break my environment.
My patch is located in https://github.com/yonamine/vcpkg/tree/master/ports/python3 but I am checking how I can create a PR. (I don't know how to do)
