### ISSUE TITLE
 [opencv] or [opencv4] build failure

### ISSUE THREAD

**Issue by J2Sky** [microsoft/vcpkg#31308]
### Operating system

win110

### Compiler

vs2019

### Steps to reproduce the behavior

```Shell
vcpkg install opencv:x64-windows
or
vcpkg install opencv4:x64-windows
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
  * libjpeg-turbo[core]:x64-windows -> 2.1.5.1#1
    opencv4[core,default-features,dnn,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.7.0#6
  * tiff[core,jpeg,lzma,zip]:x64-windows -> 4.5.0#3
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\pan\AppData\Local\vcpkg\archives in 655 us. Use --debug to see more details.
Installing 1/3 libjpeg-turbo:x64-windows...
Building libjpeg-turbo[core]:x64-windows...
-- Using cached libjpeg-turbo-libjpeg-turbo-2.1.5.1.tar.gz.
-- Cleaning sources at F:/runMVGMVS/vcpkg/buildtrees/libjpeg-turbo/src/2.1.5.1-f411453282.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/runMVGMVS/vcpkg/downloads/libjpeg-turbo-libjpeg-turbo-2.1.5.1.tar.gz
-- Applying patch add-options-for-exes-docs-headers.patch
-- Applying patch workaround_cmake_system_processor.patch
-- Using source at F:/runMVGMVS/vcpkg/buildtrees/libjpeg-turbo/src/2.1.5.1-f411453282.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Warning at scripts/cmake/vcpkg_execute_build_process.cmake:65 (message):
  Please ensure your system has sufficient memory.
Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/libjpeg-turbo/portfile.cmake:56 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "E:/Program Files/CMake/bin/cmake.exe" --build . --config Release --target install -- -v -j9
    Working Directory: F:/runMVGMVS/vcpkg/buildtrees/libjpeg-turbo/x64-windows-rel
    See logs for more information:
      F:\runMVGMVS\vcpkg\buildtrees\libjpeg-turbo\install-x64-windows-rel-out.log
      F:\runMVGMVS\vcpkg\buildtrees\libjpeg-turbo\install-x64-windows-rel-out-1.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/libjpeg-turbo/portfile.cmake:56 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building libjpeg-turbo:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libjpeg-turbo
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[libjpeg-turbo]+Build+error&body=Copy+issue+body+from+F%3A%2FrunMVGMVS%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by jimwang118** [comment]
`-- Restarting build without parallelism`
This error message appears because the memory space of the compiler is insufficient, resulting in compilation failure.

**Comment by J2Sky** [comment]
Successfully built：Close the 360 antivirus software and recovery the quarantined files！

**Comment by dg0yt** [comment]
> This error message appears because the memory space of the compiler is insufficient, resulting in compilation failure.

No. This message also appears for cases which indicate concurrent access. Restarting helps if the concurrent access is within the build system. But antivirus race conditions between link and mt can't be resolved this way.

**Comment by jimwang118** [comment]
> Successfully built：Close the 360 antivirus software and recovery the quarantined files！

Ok, then by turning off the 360 antivirus, it can be compiled normally, then this issue can be resolved, and I will close this issue.
