### ISSUE TITLE
[grpc] build failure

### ISSUE THREAD

**Issue by undici77** [microsoft/vcpkg#31302]
### Operating system

ARM64 Windows 

### Compiler

Microsoft Visual Studio 2022 (ARM 64-bit) - Preview Version 17.6.0 Preview 6.0

### Steps to reproduce the behavior

```Shell
./vcpkg install grpc
```

### Failure logs

Package: grpc[codegen,core]:arm64-windows -> 1.51.1

**Host Environment**

- Host: arm64-windows
- Compiler: MSVC 19.36.32530.0
-    vcpkg-tool version: 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895
    vcpkg-scripts version: 6a3dd0874 2023-05-05 (2 days ago)

**To Reproduce**

`vcpkg install grpc[codegen]`

**Failure logs**

```
-- Note: grpc only supports static library linkage. Building static library.
-- Downloading https://github.com/grpc/grpc/archive/v1.51.1.tar.gz -> grpc-grpc-v1.51.1.tar.gz...
-- Extracting source C:/Tools/vcpkg/downloads/grpc-grpc-v1.51.1.tar.gz
-- Applying patch 00001-fix-uwp.patch
-- Applying patch 00002-static-linking-in-linux.patch
-- Applying patch 00003-undef-base64-macro.patch
-- Applying patch 00004-link-gdi32-on-windows.patch
-- Applying patch 00005-fix-uwp-error.patch
-- Applying patch 00009-use-system-upb.patch
-- Applying patch snprintf.patch
-- Applying patch 00012-fix-use-cxx17.patch
-- Applying patch 00014-pkgconfig-upbdefs.patch
-- Applying patch 00015-disable-download-archive.patch
-- Using source at C:/Tools/vcpkg/buildtrees/grpc/src/v1.51.1-1066d25324.clean
-- Configuring arm64-windows
-- Building arm64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
    Working Directory: C:/Tools/vcpkg/buildtrees/grpc/arm64-windows-dbg
    See logs for more information:
      C:\Tools\vcpkg\buildtrees\grpc\install-arm64-windows-dbg-err.log

Call Stack (most recent call first):
  installed/arm64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/arm64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/grpc/portfile.cmake:69 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)



```
<details><summary>C:\Tools\vcpkg\buildtrees\grpc\install-arm64-windows-dbg-err.log</summary>

```
ninja: error: '_gRPC_CPP_PLUGIN-NOTFOUND', needed by 'C:/Tools/vcpkg/buildtrees/grpc/arm64-windows-dbg/gens/src/proto/grpc/reflection/v1alpha/reflection.pb.cc', missing and no known rule to make it
```
</details>

**Additional context**

### Additional context

git rev-parse HEAD
6a3dd0874f153f8b375ec26210ea6d41dee3bb26

**Comment by undici77** [comment]
@JonLiu1993:
I'm compiling in arm64-windows and not x64-windows, and that's the key!
And https://github.com/microsoft/vcpkg/discussions/29386 is for OSX (community repo) and not arm64-windows! So please reopen it!

**Comment by JonLiu1993** [comment]
@undici77, I investigated before I closed it. Although the issues submitted by users for grpc are not the same triplet, they are all errors about grpc, and the errors are the same, but I am still willing to reopen this issue.

**Comment by undici77** [comment]
Thanks! 
I compile successfully grpc in OSX 13.1 (arm64-osx triplet) and it works for me! Let me know if you need more info about!

**Comment by JonLiu1993** [comment]
@undici77, Could you please re-clone a vcpkg in a non-C drive and try again?

**Comment by undici77** [comment]
It looks the same:

Package: grpc[codegen,core]:arm64-windows -> 1.51.1

**Host Environment**

- Host: arm64-windows
- Compiler: MSVC 19.36.32530.0
-    vcpkg-tool version: 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895
    vcpkg-scripts version: 6a3dd0874 2023-05-05 (3 days ago)

**To Reproduce**

`vcpkg install grpc`

**Failure logs**

```
-- Note: grpc only supports static library linkage. Building static library.
-- Using cached grpc-grpc-v1.51.1.tar.gz.
-- Extracting source E:/vcpkg/downloads/grpc-grpc-v1.51.1.tar.gz
-- Applying patch 00001-fix-uwp.patch
-- Applying patch 00002-static-linking-in-linux.patch
-- Applying patch 00003-undef-base64-macro.patch
-- Applying patch 00004-link-gdi32-on-windows.patch
-- Applying patch 00005-fix-uwp-error.patch
-- Applying patch 00009-use-system-upb.patch
-- Applying patch snprintf.patch
-- Applying patch 00012-fix-use-cxx17.patch
-- Applying patch 00014-pkgconfig-upbdefs.patch
-- Applying patch 00015-disable-download-archive.patch
-- Using source at E:/vcpkg/buildtrees/grpc/src/v1.51.1-1066d25324.clean
-- Configuring arm64-windows
-- Building arm64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
    Working Directory: E:/vcpkg/buildtrees/grpc/arm64-windows-dbg
    See logs for more information:
      E:\vcpkg\buildtrees\grpc\install-arm64-windows-dbg-err.log

Call Stack (most recent call first):
  installed/arm64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/arm64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/grpc/portfile.cmake:69 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)



```
<details><summary>E:\vcpkg\buildtrees\grpc\install-arm64-windows-dbg-err.log</summary>

```
ninja: error: '_gRPC_CPP_PLUGIN-NOTFOUND', needed by 'E:/vcpkg/buildtrees/grpc/arm64-windows-dbg/gens/src/proto/grpc/reflection/v1alpha/reflection.pb.cc', missing and no known rule to make it
```
</details>

**Additional context**

**Comment by dg0yt** [comment]
`_gRPC_CPP_PLUGIN-NOTFOUND` comes `find_program` which is only used with `CMAKE_CROSSCOMPILING`. 
https://github.com/grpc/grpc/blob/7df0e11755d6eb8a91cf7b60eefda9021b357287/CMakeLists.txt#L503-L508

Do you actually set the right host triplet?

**Comment by undici77** [comment]
No It's not set:
<img width="1177" alt="Screenshot 2023-05-09 at 09 32 19" src="https://user-images.githubusercontent.com/3197601/237026521-67f814e4-323c-440c-a683-8e91d4e69667.png">

**Comment by undici77** [comment]
Could be PowerShell issue due to x64 emulator in arm64-windows?

**Comment by dg0yt** [comment]
`CMAKE_CROSSCOMPILING` is a cmake variable, not an environment variable.

The host triplet could be set as a command line option or via environment variable `VCPKG_DEFAULT_HOST_TRIPLET`.

**Comment by undici77** [comment]
VCPKG_DEFAULT_HOST_TRIPLET is not set.

But I found the issue! 
I made a mistake downloading and installing CMake for x64 and not Arm64. 
Windows for Arm emulate x64 so looks fine. 
I installed many packages without errors but not grpc.
Now I installed CMake Arm64 and grpc now compile correctly.

Is this reasonable?
