### ISSUE TITLE
[qtbase] build failure

### ISSUE THREAD

**Issue by KCenti** [microsoft/vcpkg#31303]
### Operating system

Windows

### Compiler

MSVC 14.35.32215

### Steps to reproduce the behavior

```Shell
./vcpkg install install qthttpserver:x64-windows-static --clean-after-build
```

### Failure logs

Detecting compiler hash for triplet x64-windows-static...
Restored 0 package(s) from C:\Users\KCenti\AppData\Local\vcpkg\archives in 2.28 ms. Use --debug to see more details.
Installing 1/4 qtbase:x64-windows...
Building qtbase[brotli,concurrent,core,dbus,default-features,doubleconversion,freetype,gui,harfbuzz,icu,jpeg,network,opengl,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,thread,widgets,zstd]:x64-windows...
-- Downloading https://download.qt.io/archive/qt/6.5/6.5.0/submodules/qtbase-everywhere-src-6.5.0.tar.xz -> qtbase-everywhere-src-6.5.0.tar.xz...
-- Extracting source H:/dev/vcpkg/downloads/qtbase-everywhere-src-6.5.0.tar.xz
-- Applying patch allow_outside_prefix.patch
-- Applying patch config_install.patch
-- Applying patch fix_cmake_build.patch
-- Applying patch harfbuzz.patch
-- Applying patch fix_egl.patch
-- Applying patch fix_egl_2.patch
-- Applying patch installed_dir.patch
-- Applying patch GLIB2-static.patch
-- Applying patch clang-cl_source_location.patch
-- Applying patch clang-cl_QGADGET_fix.diff
-- Applying patch env.patch
-- Applying patch dont_force_cmakecache_latest.patch
-- Using source at H:/dev/vcpkg/buildtrees/qtbase/src/here-src-6-7ac6c280cb.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: H:/CMake/bin/cmake.exe --build . --config Debug --target install -- -v -j7
    Working Directory: H:/dev/vcpkg/buildtrees/qtbase/x64-windows-dbg
    See logs for more information:
      H:\dev\vcpkg\buildtrees\qtbase\install-x64-windows-dbg-out.log
Detecting compiler hash for triplet x64-windows-static...
Restored 0 package(s) from C:\Users\KCenti\AppData\Local\vcpkg\archives in 494 us. Use --debug to see more details.
Installing 1/4 qtbase:x64-windows...
Building qtbase[brotli,concurrent,core,dbus,default-features,doubleconversion,freetype,gui,harfbuzz,icu,jpeg,network,opengl,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,thread,widgets,zstd]:x64-windows...
-- Using cached qtbase-everywhere-src-6.5.0.tar.xz.
-- Extracting source H:/dev/vcpkg/downloads/qtbase-everywhere-src-6.5.0.tar.xz
-- Applying patch allow_outside_prefix.patch
-- Applying patch config_install.patch
-- Applying patch fix_cmake_build.patch
-- Applying patch harfbuzz.patch
-- Applying patch fix_egl.patch
-- Applying patch fix_egl_2.patch
-- Applying patch installed_dir.patch
-- Applying patch GLIB2-static.patch
-- Applying patch clang-cl_source_location.patch
-- Applying patch clang-cl_QGADGET_fix.diff
-- Applying patch env.patch
-- Applying patch dont_force_cmakecache_latest.patch
-- Using source at H:/dev/vcpkg/buildtrees/qtbase/src/here-src-6-7ac6c280cb.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: H:/CMake/bin/cmake.exe --build . --config Release --target install -- -v -j7
    Working Directory: H:/dev/vcpkg/buildtrees/qtbase/x64-windows-rel
    See logs for more information:
      H:\dev\vcpkg\buildtrees\qtbase\install-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/qtbase/cmake/qt_install_submodule.cmake:338 (vcpkg_cmake_install)
  ports/qtbase/portfile.cmake:284 (qt_install_submodule)
  scripts/ports.cmake:147 (include)

error: building qtbase:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qtbase
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[qtbase]+Build+error&body=Copy+issue+body+from+H%3A%2Fdev%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

PS H:\dev\vcpkg> git pull
Already up to date.

### Additional context

When installing qthttpserver, must first install the qtbase x64-windows version. The qtbase often fails to build, either dbg or rel.

[config-x64-windows-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/11414464/config-x64-windows-rel-CMakeCache.txt.log)
[install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/11414465/install-x64-windows-rel-out.log)

**Comment by autoantwort** [comment]
Looks like your antivirus locked files and then the build failed. Try again with antivirus disabled.

**Comment by KCenti** [comment]
I disabled antivirus, but the build still failed.

**Comment by Adela0814** [comment]
I'm trying to reproduce this issue, it may take some time.

**Comment by Adela0814** [comment]
I'm not able to repro this issue. 
My vcpkg version: `vcpkg package management program version 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895`

Generally, it is caused by antivirus software. Do you still get the same error after you turn off the antivirus software?

**Comment by KCenti** [comment]
Thanks Reply, I still get the same error after turn off the antivirus software, and finally I found the problem, it was a rogue software called "alilbabaprotect" that caused the build to fail, it would take up a lot of memory, must pass a special method can completely delete. After the deletion is successful, qtbase build is successful
