### ISSUE TITLE
error: building openssl:arm64-osx failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by seonpilme** [microsoft/vcpkg#31312]
### Operating system

Mac OS

### Steps to reproduce the behavior

```Shell
./vcpkg/vcpkg install cpprestsdk
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
    cpprestsdk[compression,core,default-features]:arm64-osx -> 2.10.18#2
  * openssl[core]:arm64-osx -> 3.1.0#4
  * zlib[core]:arm64-osx -> 1.2.13
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet arm64-osx...
Restored 0 package(s) from /Users/macpeel/.cache/vcpkg/archives in 7.33 us. Use --debug to see more details.
Installing 1/3 openssl:arm64-osx...
Building openssl[core]:arm64-osx...
warning: -- Using community triplet arm64-osx. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /Users/macpeel/Documents/vcpkg/triplets/community/arm64-osx.cmake
-- Downloading https://github.com/openssl/openssl/archive/openssl-3.1.0.tar.gz -> openssl-openssl-openssl-3.1.0.tar.gz...
-- Cleaning sources at /Users/macpeel/Documents/vcpkg/buildtrees/openssl/src/nssl-3.1.0-1ebd9e680e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/macpeel/Documents/vcpkg/downloads/openssl-openssl-openssl-3.1.0.tar.gz
-- Applying patch disable-apps.patch
-- Applying patch disable-install-docs.patch
-- Applying patch script-prefix.patch
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch unix/android-cc.patch
-- Applying patch unix/move-openssldir.patch
-- Applying patch unix/no-empty-dirs.patch
-- Applying patch unix/no-static-libs-for-shared.patch
-- Using source at /Users/macpeel/Documents/vcpkg/buildtrees/openssl/src/nssl-3.1.0-1ebd9e680e.clean
-- Getting CMake variables for arm64-osx
-- Getting CMake variables for arm64-osx-dbg
-- Getting CMake variables for arm64-osx-rel
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:163 (message):
  Could not find pkg-config.  Please install it via your package manager:

      brew install pkg-config
Call Stack (most recent call first):
  scripts/cmake/z_vcpkg_setup_pkgconfig_path.cmake:19 (vcpkg_find_acquire_program)
  scripts/cmake/vcpkg_configure_make.cmake:773 (z_vcpkg_setup_pkgconfig_path)
  ports/openssl/unix/portfile.cmake:104 (vcpkg_configure_make)
  ports/openssl/portfile.cmake:71 (include)
  scripts/ports.cmake:147 (include)

error: building openssl:arm64-osx failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[openssl]+Build+error&body=Copy+issue+body+from+%2FUsers%2Fmacpeel%2FDocuments%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

vcpkg is also up to date. Please tell me how to solve it.

**Comment by dg0yt** [comment]
> Please tell me how to solve it.

As written in output:

~~~
brew install pkg-config

**Comment by seonpilme** [comment]
> r

thanks :) have a good day.

**Comment by FrankXie05** [comment]
@seonpilme Does the issue still occur?

**Comment by Ralumbi** [comment]
This occurs on windows as well, I am looking for a fix.

**Comment by dg0yt** [comment]
> This occurs on windows as well, I am looking for a fix.

@Ralumbi Building on Windows for Windows should not lead into 
~~~
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:163 (message):
Could not find pkg-config. Please install it via your package manager:

brew install pkg-config
~~~

**Comment by eliasbauer1** [comment]
> > Please tell me how to solve it.
> 
> As written in output:
> 
> ```
> brew install pkg-config
> ```

thank you, worked for me

**Comment by JonLiu1993** [comment]
It seems that the issue has been resolved, if it is still an issue, please reopen this issue.

**Comment by shive1807** [comment]
Issue still exist,  `brew install pkg-config` this doesn't seems to resolve the problem.

**Comment by FrankXie05** [comment]
@shive1807 Please open a new issue.
