### ISSUE TITLE
[pybind11] messes with python3 autolink

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#31311]
seen in a few PRs trying to link `python3.lib` in **debug** builds.
This is due to pybind11 undefining `_DEBUG` on line 228 in `pybind11/detail/common.h` which messes how python3 autolinks. 
(Maybe we need to force `Py_DEBUG` somewhere?)

**Comment by JonLiu1993** [comment]
Related issue #30642.
