### ISSUE TITLE
[mongo-c-driver] support for ENABLE_CLIENT_SIDE_ENCRYPTION

### ISSUE THREAD

**Issue by Jahrenski** [microsoft/vcpkg#31327]
### Is your feature request related to a problem? Please describe.

I need a new feature in [mongo-cxx-driver] to support the cmake flag ENABLE_CLIENT_SIDE_ENCRYPTION=ON. 
It does not currently exists.

This is required in order to use Client-Side Field Level Encryption in MongoDB.

### Proposed solution

This feature would require a new Package called libmongocrypt that is built using [libbson] as a dependency. 
(see #31329)

[https://mongoc.org/libmongoc/current/using_client_side_encryption.html](https://mongoc.org/libmongoc/current/using_client_side_encryption.html)

Then, it would add this new package as a dependency for [mongo-c-driver].
A feature should be set to enable Client-Side Field Level Encryption.

[mongo-cxx-driver] would then use that same feature.

### Describe alternatives you've considered

I've tried compiling the whole suite myself using the right flags but had so much problem that I used vcpkg in the end.
There are no features in vcpkg at the moment to use client-side encryption.

### Additional context

[https://github.com/mongodb/libmongocrypt](https://github.com/mongodb/libmongocrypt)
[https://mongocxx.org/mongocxx-v3/client-side-encryption](https://mongocxx.org/mongocxx-v3/client-side-encryption)

Hope I wrote this request correctly!

**Comment by Jahrenski** [comment]
Indeed, would it be better to create different entries then?
1 new Package for libmongocrypt
1 new Feature for [mongo-c-driver]
And this one as a new feature to forward to its dependency?

**Comment by dg0yt** [comment]
Yes for the new port and feature
AFAIU the "forwarding" to the cxx port should not take any extra code, https://mongocxx.org/mongocxx-v3/client-side-encryption/#libmongocrypt
This is also how the other mongo features are implemented: control via the c port, and the cxx port follows.

**Comment by Jahrenski** [comment]
Thanks!
I created this new port request : #31329 
This feature request was modified per your suggestion.
