### ISSUE TITLE
Unable build qt5-base under windows 

### ISSUE THREAD

**Issue by alexander-smyslov** [Microsoft/vcpkg#3133]
Unable build qt5-base under windows 

Enable fix-system-pcre2.patch again for successful build 
 
diff --git a/ports/qt5-base/portfile.cmake b/ports/qt5-base/portfile.cmake
index 39498b4a..c398b437 100644
--- a/ports/qt5-base/portfile.cmake
+++ b/ports/qt5-base/portfile.cmake
@@ -42,7 +42,7 @@ file(REMOVE_RECURSE ${SOURCE_PATH}/include/QtZlib)
 vcpkg_apply_patches(
     SOURCE_PATH ${SOURCE_PATH}
     PATCHES
-#        "${CMAKE_CURRENT_LIST_DIR}/fix-system-pcre2.patch"
+        "${CMAKE_CURRENT_LIST_DIR}/fix-system-pcre2.patch"
         "${CMAKE_CURRENT_LIST_DIR}/fix-system-freetype.patch"
 )

**Comment by alexander-smyslov** [comment]
@ras0219-msft Please see. I can provide more logs.

**Comment by ras0219-msft** [comment]
Thanks a ton for catching this regression and providing the fix! I've added it back in on master :)
