### ISSUE TITLE
[SFML] build failure

### ISSUE THREAD

**Issue by milen-prg** [microsoft/vcpkg#31346]
### Operating system

Windows 10 Pro 64bit

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
set(VCPKG_BUILD_TYPE release)

vcpkg>vcpkg install --triplet x64-windows-static sfml:x64-windows-static --clean-after-build
```

### Failure logs

.....................................................................................................................
.....................................................................................................................
.....................................................................................................................
Elapsed time to handle opengl:x64-windows-static: 1.2 s
Installing 13/14 stb:x64-windows-static...
Building stb[core]:x64-windows-static...
-- Downloading https://github.com/nothings/stb/archive/5736b15f7ea0ffb08dd38af21067c314d6a3aae9.tar.gz -> nothings-stb-5736b15f7ea0ffb08dd38af21067c314d6a3aae9.tar.gz...
-- Extracting source C:/vcpkg/downloads/nothings-stb-5736b15f7ea0ffb08dd38af21067c314d6a3aae9.tar.gz
-- Using source at C:/vcpkg/buildtrees/stb/src/14d6a3aae9-dc9b68ccde.clean
-- Installing: C:/vcpkg/packages/stb_x64-windows-static/share/stb/FindStb.cmake
-- Installing: C:/vcpkg/packages/stb_x64-windows-static/share/stb/vcpkg-cmake-wrapper.cmake
-- Installing: C:/vcpkg/packages/stb_x64-windows-static/share/stb/usage
-- Installing: C:/vcpkg/packages/stb_x64-windows-static/share/stb/copyright
-- Performing post-build validation
Stored binaries in 0 destinations.
Elapsed time to handle stb:x64-windows-static: 2 s
Installing 14/14 sfml:x64-windows-static...
Building sfml[core]:x64-windows-static...
-- Downloading https://github.com/SFML/SFML/archive/2.5.1.tar.gz -> SFML-SFML-2.5.1.tar.gz...
-- Extracting source C:/vcpkg/downloads/SFML-SFML-2.5.1.tar.gz
-- Applying patch fix-dependencies.patch
-- Applying patch arm64.patch
-- Using source at C:/vcpkg/buildtrees/sfml/src/2.5.1-606b8d4033.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-static
-- Building x64-windows-static-rel
CMake Error at ports/sfml/portfile.cmake:35 (file):
  file COPY cannot find
  "C:/vcpkg/packages/sfml_x64-windows-static/debug/lib/sfml-main-d.lib": File
  exists.
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)

error: building sfml:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+sfml
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[sfml]+Build+error&body=Copy+issue+body+from+C%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

The vcpkg is fresh installed, the Visual Studio 2022 is updated, also updated is the Windows.

**Comment by dg0yt** [comment]
So the message is that the port needs to be fixed to support release-only triplets.

**Comment by MonicaLiu0311** [comment]
I'll fix it to support release-only as soon as possible.
