### ISSUE TITLE
GLM not working correctly with CMake after installing with vcpkg

### ISSUE THREAD

**Issue by brucedjones** [Microsoft/vcpkg#3134]
I have installed GLM with vcpkg, the output of the install command states:

```
The package glm:x64-windows provides CMake targets:

    find_package(glm REQUIRED)
    target_link_libraries(main PRIVATE glm)
```
However this does not work and results in the following when compiling:

```
fatal error C1083: Cannot open include file: 'glm/glm.hpp': No such file or directory
```

GLM itself does export an interface and the include directory *should* be correctly set this way. If I do `include_directories(${GLM_INCLUDE_DIRS})` instead it does work, but "modern cmake" suggests that this approach should be avoided.

Is this a problem with the way vcpkg handles header only libraries more generally? or a problem with GLM specifically?

**Comment by jasjuang** [comment]
It seems to be working properly for me, below is the minimal to reproduce it

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.9)

project(Example LANGUAGES CXX)

set(PROJECT_SRCS ${PROJECT_SOURCE_DIR}/mycpp.cpp)

find_package( glm REQUIRED )

add_executable(${PROJECT_NAME} ${PROJECT_SRCS})

target_link_libraries(${PROJECT_NAME} glm)
```
mycpp.cpp
```
#include "glm/glm.hpp"

int main(){
  return 0;
}
```

`msbuild Example.sln` and it compiles sucessfully.

**Comment by brucedjones** [comment]
Ah thanks this pointed me int he right direction. `include_directories` was including the glm header globally for all targets, but switching to using `target_link_libraries` I had to link it explicitly to each target (makes so much sense in hindsight). Further, I was previously relying on cmake's recursive linking, but had not really understood the implications of linking something as PRIVATE/PUBLIC.

**Comment by yoavmil** [comment]
I had the same problem. 
to solve it I hade to replace 
`target_link_libraries(my_lib PRIVATE glm)`
with  
`target_link_libraries(my_lib PRIVATE glm::glm)`

why is it?
