### ISSUE TITLE
[freetype:x86-windows] build failure

### ISSUE THREAD

**Issue by yoonteak** [microsoft/vcpkg#31343]
### Operating system

Windows 10

### Compiler

cmd

### Steps to reproduce the behavior

```Shell
D:\SVN\lib\vcpkg>.\vcpkg install freetype
```

### Failure logs

The following packages will be built and installed:
    freetype[core]:x86-windows
Starting package 1/1: freetype:x86-windows
Building package freetype[core]:x86-windows...
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    C:\Program Files (x86)\Microsoft Visual Studio 12.0\
Please install the English language pack.
-- Using cached D:/SVN/lib/vcpkg/downloads/freetype-2.10.1.tar.xz
-- Using source at D:/SVN/lib/vcpkg/buildtrees/freetype/src/2.10.1-ea10bbeefe
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: D:/SVN/lib/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: D:/SVN/lib/vcpkg/buildtrees/freetype/x86-windows-dbg
    See logs for more information:
      D:\SVN\lib\vcpkg\buildtrees\freetype\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/freetype/portfile.cmake:40 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package freetype:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: freetype:x86-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.

### Additional context

vcpkg update

**Comment by yoonteak** [comment]
git update issue. .. :(

**Comment by JonLiu1993** [comment]
@yoonteak, Thanks for posting this issue, please provide error log:
````
D:\SVN\lib\vcpkg\buildtrees\freetype\install-x86-windows-dbg-out.log
````

**Comment by trusna** [comment]
> @yoonteak, Thanks for posting this issue, please use command "git pull" get latest vcpkg try again. if still error, please provide error log:
> 
> ```
> D:\SVN\lib\vcpkg\buildtrees\freetype\install-x86-windows-dbg-out.log
> ```

I am facing the same issue even after installing the latest vcpkg.

**Comment by yoonteak** [comment]
> @yoonteak, 이 문제를 게시해 주셔서 감사합니다. "git pull" 명령을 사용하여 최신 vcpkg 가져오기를 다시 시도하십시오. 여전히 오류가 있는 경우 오류 로그를 제공하십시오.
> 
> ```
> D:\SVN\lib\vcpkg\buildtrees\freetype\install-x86-windows-dbg-out.log
> ```

> log content
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/11437135/install-x86-windows-dbg-out.log)

**Comment by yoonteak** [comment]
solutions : ..\vcpkg\ports\freetype\portfile.cmake 
PREFER NINJA
comments remove.

**Comment by JonLiu1993** [comment]
@trusna, pleasae provide your error log, thanks.

**Comment by JonLiu1993** [comment]
@trusna, We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
