### ISSUE TITLE
Feature Request: custom command for generating doxygen documents for ports

### ISSUE THREAD

**Issue by jasjuang** [microsoft/vcpkg#3135]
Would it be possible to add an option to generate doxygen documents for ports individually? A lot of the ports like opencv, pcl, tinyxml2 all has doxygen style comments, I am imagining something like `vcpkg install --doc tinyxml` and bind it to a custom target along the lines of

```
find_package(Doxygen)

if(DOXYGEN_FOUND AND NOT TARGET doc)
  configure_file(${CMAKE_CURRENT_SOURCE_DIR}/Doxyfile.in
    ${CMAKE_CURRENT_BINARY_DIR}/Doxyfile @ONLY)
  add_custom_target(doc
                    ${DOXYGEN_EXECUTABLE} ${CMAKE_CURRENT_BINARY_DIR}/Doxyfile
                    WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
                    COMMENT "Generating API documentation with Doxygen"
                    VERBATIM)
endif()
```

**Comment by ras0219-msft** [comment]
I looked into doing this before, but I couldn't get doxygen to generate _linked_ documentation (so, having `#include <zlib.h>` inside a boost header jump you to the generated zlib docs) in a reasonable timespan. It seemed like the performance was O(N^2) or worse as the number of lines processed increased. As long as each set of docs was generated completely independently, it was acceptable.

If someone could figure out how to do this reasonably, I'd love to have it!

**Comment by jasjuang** [comment]
Ah I wasn't even thinking about linked documentation. I agree it will be a lot harder to do it. I think we can start with unlinked documentation first at some point.

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen this issue.
