### ISSUE TITLE
ports/qtbase/clang-cl_source_location.patch causes compile error on Clang++-16

### ISSUE THREAD

**Issue by RealLitb** [microsoft/vcpkg#31354]
**Describe the bug**
That line causes a compile error in file `include/Qt6/QtCore/qproperty.h`, because the check in the patch insufficiently catches the later use in the same file of `std::source_location` at line 91 which does not also check  for `__cpp_consteval` as the patch does:

```
#ifdef __cpp_lib_source_location
    constexpr QPropertyBindingSourceLocation(const std::source_location &cppLocation)
```

**Environment**
- OS: Linux
- Compiler: A toolchain file based on linux, with CMAKE_CXX/C_COMPILER set to clang++ and clang respectively.

**To Reproduce**
1. ./vcpkg install qtbase

Use a chainload toolchain file where you override the compiler to use Clang as specified above, and compile a simple program that uses Qt properties. 

**Expected behavior**
Expected the build with clang to succeed.

**Failure logs**
```
[build] In file included from /workspaces/.out/build/debug-clang-vcpkg/vcpkg_installed/x64-linux-dynamic/include/Qt6/QtWidgets/QtWidgets:3:
[build] In file included from /workspaces/.out/build/debug-clang-vcpkg/vcpkg_installed/x64-linux-dynamic/include/Qt6/QtWidgets/QtWidgetsDepends:3:
[build] In file included from /workspaces/.out/build/debug-clang-vcpkg/vcpkg_installed/x64-linux-dynamic/include/Qt6/QtCore/QtCore:179:
[build] /workspaces/.out/build/debug-clang-vcpkg/vcpkg_installed/x64-linux-dynamic/include/Qt6/QtCore/qproperty.h:91:52: error: no type named 'source_location' in namespace 'std'; did you mean 'std::experimental::source_location'?
[build]     constexpr QPropertyBindingSourceLocation(const std::source_location &cppLocation)
[build]                                                    ^~~~~

```

**Comment by Neumann-A** [comment]
So the logic needs to be a bit less constrained and only check for `__cpp_consteval` if `_MSC_VER` is also defined
```
#if __has_include(<source_location>) && __cplusplus >= 202002L && !defined(Q_QDOC) && ((defined(__cpp_consteval) && defined(_MSC_VER)) || !defined(_MSC_VER))
```

**Comment by Neumann-A** [comment]
__cpp_consteval | Immediate functions | 201811L | (C++20)
__cpp_lib_source_location | Source-code information capture | 201907L |<source_location> | (C++20)

hmm with which C++ standard are you compiling? (Qt only forces c++17 not 20)
So `__cpp_lib_source_location` should only be defined with c++20

**Comment by RealLitb** [comment]
I compile with cxx_std_20. I wasn't aware that Qt might break with that. Previously before we changed to VCPKG we used Qt6.4 packages from the official Qt installer and those headers are compatible with cxx_std_20.

**Comment by Neumann-A** [comment]
> I compile with cxx_std_20

hmm shouldn't `__cpp_consteval` be defined then? Ok I see there was some back and forth about if clang should define it or not o.O  https://reviews.llvm.org/D147717 .

**Comment by Neumann-A** [comment]
Can you hand edit the file and check if the new logic solves the problem (manually editing the already installed file is probably faster than rebuilding with #31360)

**Comment by RealLitb** [comment]
> Can you hand edit the file and check if the new logic solves the problem (manually editing the already installed file is probably faster than rebuilding with #31360)

Yes that works for me.
