### ISSUE TITLE
Vcpkg fails to activate because `tar` was not found

### ISSUE THREAD

**Issue by benmcmorran** [microsoft/vcpkg#31355]
_(reposting from feedback on Facebook)_

> Try to do it on 2 differents computer : same error , Vcpkg error. "globalStorage\ms-vscode.vscode-embedded-tools\vcpkg\root\scripts\vcpkgTools.xml"): no such file or directory

> Failed with exit code "1"."

**Comment by BR38** [comment]
tar.exe is in windows/system32 directory  but tar command is unknown. I am investigating...
