### ISSUE TITLE
[boost-url] build failure

### ISSUE THREAD

**Issue by sunnywang537** [microsoft/vcpkg#31366]
### Operating system

win10

### Compiler

vs2015Community

### Steps to reproduce the behavior

```Shell
.\vcpkg install boost-url[core]:x64-windows
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
    boost-url[core]:x64-windows -> 1.82.0#1
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\top\AppData\Local\vcpkg\archives in 121 us. Use --debug to see more details.
Installing 1/1 boost-url:x64-windows...
Building boost-url[core]:x64-windows...
-- Using cached boostorg-url-boost-1.82.0.tar.gz.
-- Cleaning sources at D:/vcpkg2015/vcpkg/buildtrees/boost-url/src/ost-1.82.0-125968c34f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg2015/vcpkg/downloads/boostorg-url-boost-1.82.0.tar.gz
-- Using source at D:/vcpkg2015/vcpkg/buildtrees/boost-url/src/ost-1.82.0-125968c34f.clean
-- Getting CMake variables for x64-windows
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j25
    Working Directory: D:/vcpkg2015/vcpkg/buildtrees/boost-url/x64-windows-dbg
    See logs for more information:
      D:\vcpkg2015\vcpkg\buildtrees\boost-url\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:140 (vcpkg_cmake_install)
  ports/boost-url/portfile.cmake:17 (boost_modular_build)
  scripts/ports.cmake:147 (include)

error: building boost-url:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-url
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[boost-url]+Build+error&body=Copy+issue+body+from+D%3A%2Fvcpkg2015%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

“ Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j25” 
is this normal ?  " ... --target install -- -v -j25 "

**Comment by Cheney-W** [comment]
Could you please provide us with `D:\vcpkg2015\vcpkg\buildtrees\boost-url\install-x64-windows-dbg-out.log`? Thank you!

**Comment by sunnywang537** [comment]
using VisualStudio2019Community , " boost-url[core]:x64-windows -> 1.82.0#1" can be installed successfully.

**Comment by Cheney-W** [comment]
I'm glad to hear that this issue has been resolved on higher versions of VS.
