### ISSUE TITLE
Unable to build Caffe2-GPU with vcpkg toolchain file

### ISSUE THREAD

**Issue by wdx04** [Microsoft/vcpkg#3136]
Hi,

I'm trying to build Caffe2 from source, while using certain third party libraries(lmdb, leveldb, glog, gflags, etc) provided by vcpkg(specify the vcpkg.cmake toolchain file for cross-compiling). The CPU version of Caffe2 can be built without a problem. But when I build the GPU version, I get lots of compiling errors on the CUDA files:

```
1>C:/Develop/vcpkg/installed/x64-windows/include\google/protobuf/extension_set.h(640): warning : field of class type without a DLL interface used in a class with a DLL interface
1>
1>C:/Develop/Caffe2/build\caffe2/proto/caffe2.pb.h(227): error : member "caffe2::TensorProto_Segment::kIndexInFileMessages" may not be initialized
1>
1>C:/Develop/Caffe2/build\caffe2/proto/caffe2.pb.h(299): warning : field of class type without a DLL interface used in a class with a DLL interface
1>
1>C:/Develop/Caffe2/build\caffe2/proto/caffe2.pb.h(300): warning : field of class type without a DLL interface used in a class with a DLL interface
1>
1>C:/Develop/Caffe2/build\caffe2/proto/caffe2.pb.h(350): error : member "caffe2::TensorProto::kIndexInFileMessages" may not be initialized
1>
1>C:/Develop/Caffe2/build\caffe2/proto/caffe2.pb.h(598): warning : field of class type without a DLL interface used in a class with a DLL interface
```

Likely some of the compiler options are not passed to the NVCC compiler.  If I use the normal "Visual Studio 14 2015 win64" generator without specifying the toolchain file, I can compile these CUDA files without errors.

**Comment by wdx04** [comment]
Successfully built Caffe2-GPU as a static library. The problem is unrelated to the vcpkg toolchain file. Closing this issue.

**Comment by paul-michalik** [comment]
Which version of CUDA and MSVC have you used?

**Comment by wdx04** [comment]
CUDA toolkit version 8.0 with cuDNN v5.1
MSVC 2015 with Update 3

**Comment by icedream2linxi** [comment]
这个问题似乎是 NVCC 不支持 dllexport，使用静态版 protobuf 就不会有此问题。

> The problem seems to be that NVCC does not support dllexport, and this problem will not occur with the static version of protobuf.

**Comment by rakidedigama** [comment]
Hi, I am getting a list of the same error 
` error : member "caffe2::TensorProto_Segment::kIndexInFileMessages" may not be initialized`
What was the problem here? How did you solve it?

**Comment by wdx04** [comment]
@rakidedigama Just replace all "constexpr" with "const" in caffe2.pb.h will solve the problem. Also you may need to patch Eigen3's Half.h if you are using CUDA 9.x, see http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1526
