### ISSUE TITLE
[zlib] build failure

### ISSUE THREAD

**Issue by Jrojro728** [microsoft/vcpkg#31373]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
./vcpkg install zlib
```

### Failure logs

warning: Starting with the September 2023 release, the default triplet for vcpkg libraries will change from x86-windows to the detected host triplet (x64-windows). To resolve this message, add --triplet x86-windows to keep the same behavior.
Computing installation plan...
The following packages will be built and installed:
  * vcpkg-cmake[core]:x64-windows -> 2022-12-22
    zlib[core]:x86-windows -> 1.2.13
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
error: while detecting compiler information:
The log file content at "C:\src\vcpkg\buildtrees\detect_compiler\stdout-x64-windows.log" is:
CMake Error at C:/src/vcpkg/scripts/ports.cmake:110 (message):
  Cannot find port:

    Directory does not exist: C;/src/vcpkg/scripts/detect_compiler

error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.

**Comment by jimwang118** [comment]
> * Directory does not exist: `C;/src/vcpkg/scripts/detect_compiler`

This path does not look correct, you can change the directory to pull the code and compile it again.

**Comment by Jrojro728** [comment]
> > * Directory does not exist: `C;/src/vcpkg/scripts/detect_compiler`
> 
> This path does not look correct, you can change the directory to pull the code and compile it again.

I'm already change the directory to pull the code and compile again, but is not work too.

**Comment by dg0yt** [comment]
You must get msys2 subsystem cmake (`<msys2 root>/usr/bin/cmake`) out of your PATH. It doesn't support Windows paths.

**Comment by Jrojro728** [comment]
> You must get msys2 subsystem cmake (`<msys2 root>/usr/bin/cmake`) out of your PATH. It doesn't support Windows paths.

Thankyou my vcpkg is working. :)
