### ISSUE TITLE
Run error 'create_or_get_temp_directory(): Read-only file system' on Android termux.

### ISSUE THREAD

**Issue by masx200** [microsoft/vcpkg#31375]
**Describe the bug**
Run error 'create_or_get_temp_directory(): Read-only file system' on Android termux.

**Environment**
- OS: linux aarch64 termux
- Compiler: clang16

**To Reproduce**
```

vcpkg version

```

**Expected behavior**
no error

**Failure logs**
```
vcpkg package management program version 2999-12-31-unknownhash

See LICENSE.txt for license information.
create_or_get_temp_directory(): Read-only file system
Aborted
```

**Additional context**

**Comment by FrankXie05** [comment]
`vcpkg` needs to be able to write files and directories on the system, please make sure the attribute of the file system is writable.

**Comment by masx200** [comment]
@FrankXie05 
Could you consider using environment variables to set up temporary directories?

**Comment by FrankXie05** [comment]
@masx200 Of course it is possible, but also make sure that the alternative environment variable `TMP` or `TEMP` is writable. :)

**Comment by masx200** [comment]
https://github.com/microsoft/vcpkg-tool/blob/f4ff80d74de6194ccdfb457ba7ced6c1c458080d/src/vcpkg/base/files.cpp#L2939

**Comment by masx200** [comment]
```
env|grep TMP
TMPDIR=/data/data/com.termux/files/usr/tmp
```
