### ISSUE TITLE
[<liblzma>] build failure

### ISSUE THREAD

**Issue by Ocean-ZHY** [microsoft/vcpkg#31385]
### Operating system

windows10

### Compiler

MSVC 2019

### Steps to reproduce the behavior

```Shell
vcpkg install zlib:x64-windows boost:x64-windows eigen3:x64-windows ceres:x64-windows opencv:x64-windows cgal:x64-windows glew:x64-windows glfw3:x64-windows
```

### Failure logs

CreateProcess failed. Command attempted:
"D:/Program Files/CMake/bin/cmcldeps.exe RC D:\vcpkg\buildtrees\liblzma\src\f890ee5207-326fe62969.clean\src\liblzma\liblzma_w32res.rc CMakeFiles\liblzma.dir\src\liblzma\liblzma_w32res.rc.res.d CMakeFiles\liblzma.dir\src\liblzma\liblzma_w32res.rc.res "注意: 包含文件:  " "D:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe" "D:\Windows Kits\10\bin\10.0.19041.0\x64\rc.exe" -DDLL_EXPORT -DHAVE_CHECK_CRC32 -DHAVE_CHECK_CRC64 -DHAVE_CHECK_SHA256 -DHAVE_DECODERS -DHAVE_DECODER_ARM -DHAVE_DECODER_ARM64 -DHAVE_DECODER_ARMTHUMB -DHAVE_DECODER_DELTA -DHAVE_DECODER_IA64 -DHAVE_DECODER_LZMA1 -DHAVE_DECODER_LZMA2 -DHAVE_DECODER_POWERPC -DHAVE_DECODER_SPARC -DHAVE_DECODER_X86 -DHAVE_ENCODERS -DHAVE_ENCODER_ARM -DHAVE_ENCODER_ARM64 -DHAVE_ENCODER_ARMTHUMB -DHAVE_ENCODER_DELTA -DHAVE_ENCODER_IA64 -DHAVE_ENCODER_LZMA1 -DHAVE_ENCODER_LZMA2 -DHAVE_ENCODER_POWERPC -DHAVE_ENCODER_SPARC -DHAVE_ENCODER_X86 -DHAVE_IMMINTRIN_H -DHAVE_INTTYPES_H -DHAVE_LZIP_DECODER -DHAVE_MF_BT2 -DHAVE_MF_BT3 -DHAVE_MF_BT4 -DHAVE_MF_HC3 -DHAVE_MF_HC4 -DHAVE_STDBOOL_H -DHAVE_STDINT_H -DHAVE_USABLE_CLMUL -DHAVE_VISIBILITY=1 -DHAVE__BOOL -DHAVE__MM_MOVEMASK_EPI8 -DHAVE___BUILTIN_ASSUME_ALIGNED -DMYTHREAD_VISTA -DPACKAGE_BUGREPORT=\"xz@tukaani.org\" -DPACKAGE_NAME="\"XZ Utils\"" -DPACKAGE_URL=\"https://tukaani.org/xz/\" -DTUKLIB_FAST_UNALIGNED_ACCESS -DTUKLIB_SYMBOL_PREFIX=lzma_ -Dliblzma_EXPORTS -I D:\vcpkg\buildtrees\liblzma\src\f890ee5207-326fe62969.clean\src\liblzma\api -I D:\vcpkg\buildtrees\liblzma\src\f890ee5207-326fe62969.clean\src\liblzma\common -I D:\vcpkg\buildtrees\liblzma\src\f890ee5207-326fe62969.clean\src\liblzma\check -I D:\vcpkg\buildtrees\liblzma\src\f890ee5207-326fe62969.clean\src\liblzma\lz -I D:\vcpkg\buildtrees\liblzma\src\f890ee5207-326fe62969.clean\src\liblzma\rangecoder -I D:\vcpkg\buildtrees\liblzma\src\f890ee5207-326fe62969.clean\src\liblzma\lzma -I D:\vcpkg\buildtrees\liblzma\src\f890ee5207-326fe62969.clean\src\liblzma\delta -I D:\vcpkg\buildtrees\liblzma\src\f890ee5207-326fe62969.clean\src\liblzma\simple -I D:\vcpkg\buildtrees\liblzma\src\f890ee5207-326fe62969.clean\src\common -I D:\vcpkg\buildtrees\liblzma\src\f890ee5207-326fe62969.clean\windows\vs2019 -c65001 /DWIN32 -D_DEBUG /fo CMakeFiles\liblzma.dir\src\liblzma\liblzma_w32res.rc.res D:\vcpkg\buildtrees\liblzma\src\f890ee5207-326fe62969.clean\src\liblzma\liblzma_w32res.rc"
ninja: fatal: CreateProcess: %1 不是有效的 Win32 应用程序。

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. I can't repro this issue locally. 
```
liblzma is compatible with built-in CMake targets:

    find_package(LibLZMA REQUIRED)
    target_link_libraries(main PRIVATE LibLZMA::LibLZMA)
liblzma provides CMake targets:

    find_package(liblzma CONFIG REQUIRED)
    target_link_libraries(main PRIVATE liblzma::liblzma)
PS E:\Lily\0504> .\vcpkg.exe --version
vcpkg package management program version 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895
```
Could you please the full log file?

**Comment by dg0yt** [comment]
Likely to be caused by antivirus and/or alibabaprotect.

**Comment by Ocean-ZHY** [comment]
> Thanks for posting this issue. I can't repro this issue locally.
> 
> ```
> liblzma is compatible with built-in CMake targets:
> 
>     find_package(LibLZMA REQUIRED)
>     target_link_libraries(main PRIVATE LibLZMA::LibLZMA)
> liblzma provides CMake targets:
> 
>     find_package(liblzma CONFIG REQUIRED)
>     target_link_libraries(main PRIVATE liblzma::liblzma)
> PS E:\Lily\0504> .\vcpkg.exe --version
> vcpkg package management program version 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895
> ```
> 
> Could you please the full log file?

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/11468693/install-x64-windows-dbg-out.log)
[patch-x64-windows-0-err.log](https://github.com/microsoft/vcpkg/files/11468694/patch-x64-windows-0-err.log)

**Comment by LilyWangLL** [comment]
> Likely to be caused by antivirus and/or alibabaprotect.

Thanks for your reply. But I can't find any error in your log. Did you install antivirus or alibabaprotect?

**Comment by Ocean-ZHY** [comment]
> 



> > Likely to be caused by antivirus and/or alibabaprotect.
> 
> Thanks for your reply. But I can't find any error in your log. Did you install antivirus or alibabaprotect?

Thank you for your efforts. My computer did not download the files you mentioned. It is a newly installed system on this computer.

**Comment by Ocean-ZHY** [comment]
-- Using cached xz-5.4.1.tar.xz.
-- Cleaning sources at D:/vcpkg/buildtrees/liblzma/src/f890ee5207-326fe62969.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/xz-5.4.1.tar.xz
-- Applying patch fix_config_include.patch
-- Applying patch win_output_name.patch
-- Applying patch add_support_ios.patch
-- Applying patch build-tools.patch
-- Using source at D:/vcpkg/buildtrees/liblzma/src/f890ee5207-326fe62969.clean
-- Found external ninja('1.10.2').
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "D:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j5
    Working Directory: D:/vcpkg/buildtrees/liblzma/x86-windows-dbg
    See logs for more information:
      D:\vcpkg\buildtrees\liblzma\install-x86-windows-dbg-out.log
      D:\vcpkg\buildtrees\liblzma\install-x86-windows-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/liblzma/portfile.cmake:35 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

**Comment by LilyWangLL** [comment]
> D:\vcpkg\buildtrees\liblzma\install-x86-windows-dbg-err.log

Does this file have any contents? If it does, could you please provide it?

**Comment by Ocean-ZHY** [comment]
> > D:\vcpkg\buildtrees\liblzma\install-x86-windows-dbg-err.log
> 
> Does this file have any contents? If it does, could you please provide it?

[install-x86-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/11497830/install-x86-windows-dbg-err.log)

**Comment by cr3881** [comment]
i am having similar problem. 
the log shows:
C:\vcpkg\buildtrees\liblzma\src\v5.2.5-d69c6caafe.clean\src\common\common_w32res.rc(9): fatal error C1083: Cannot open include file: 'config.h': No such file or directory
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/11549725/install-x64-windows-dbg-out.log)

**Comment by LilyWangLL** [comment]
> i am having similar problem. the log shows: C:\vcpkg\buildtrees\liblzma\src\v5.2.5-d69c6caafe.clean\src\common\common_w32res.rc(9): fatal error C1083: Cannot open include file: 'config.h': No such file or directory [install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/11549725/install-x64-windows-dbg-out.log)

Could you try cloning vcpkg to a different disk and then rebuild `liblzma`?

**Comment by LilyWangLL** [comment]
> D:/Program Files/CMake/bin/cmcldeps.exe

@Ocean-ZHY Could you please remove the CMake which installed by yourself and rebuild this port? It is possible that this error is caused by the locally installed CMake on your machine.

**Comment by dg0yt** [comment]
> C:\vcpkg\buildtrees\liblzma\src\v5.2.5-d69c6caafe.clean\src\common\common_w32res.rc(9): fatal error C1083: Cannot open include file: 'config.h': No such file or directory

@cr3881 Update your vcpkg repo. We are at 5.4.1.

**Comment by dg0yt** [comment]
@Ocean-ZHY's build has `-c65001` in the cl options, @LilyWangLL's build hasn't.

**Comment by LilyWangLL** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
