### ISSUE TITLE
GFlags on Windows x64 fails

### ISSUE THREAD

**Issue by Andyjk1406** [Microsoft/vcpkg#3138]
Not sure why - seems like it can't find a debug file ?

C:\Repos\vcpkg>.\vcpkg install gflags:x64-windows
The following packages will be built and installed:
    gflags[core]:x64-windows
Starting package 1/1: gflags:x64-windows
Building package gflags[core]:x64-windows...
-- CURRENT_INSTALLED_DIR=C:/Repos/vcpkg/installed/x64-windows
-- DOWNLOADS=C:/Repos/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Repos/vcpkg/packages/gflags_x64-windows
-- CURRENT_BUILDTREES_DIR=C:/Repos/vcpkg/buildtrees/gflags
-- CURRENT_PORT_DIR=C:/Repos/vcpkg/ports/gflags/.
-- Using cached C:/Repos/vcpkg/downloads/gflags-gflags-v2.2.1.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch C:/Repos/vcpkg/ports/gflags/0001-patch-dir.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/Repos/vcpkg/ports/gflags/0001-patch-dir.patch done
-- Configuring x64-windows
-- Configuring x64-windows done
-- Build x64-windows-dbg
-- Build x64-windows-dbg done
-- Build x64-windows-rel
-- Build x64-windows-rel done
CMake Error at C:/Repos/vcpkg/scripts/cmake/vcpkg_fixup_cmake_targets.cmake:36 (message):
  'C:/Repos/vcpkg/packages/gflags_x64-windows/debug/lib/cmake/gflags' does
  not exist.
Call Stack (most recent call first):
  C:/Repos/vcpkg/ports/gflags/portfile.cmake:32 (vcpkg_fixup_cmake_targets)
  C:/Repos/vcpkg/scripts/ports.cmake:72 (include)

Error: Building package gflags:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: gflags:x64-windows
  Vcpkg version: 0.0.106-2018-03-27-72758773321476dcbb7b9d18f11bf57134bb4545

**Comment by JackBoosY** [comment]
Hi @Andyjk1406 , thanks for reporting this issue.
Please open a new issue if this is still a problem for you.
Thx.
