### ISSUE TITLE
opencv4 visual studio 2022 missing lib

### ISSUE THREAD

**Issue by TalSomech** [microsoft/vcpkg#31386]
**Describe the bug**
Hi just installed opencv4 using vcpkg and before running i got the message
1>LINK : fatal error LNK1104: cannot open file 'opencv_world460d.lib'
i've looked into the files in vcpkg however this specific file is missing , wanted to know if i could create it myself
but since im new to vcpkg i wouldnt want to ruin anything

**Environment**
- OS:windows
- Compiler:visual studio

**To Reproduce**
1. ./vcpkg install opencv
2. See error

**Comment by jimwang118** [comment]
According to the reproduction steps you provided, I reproduced it, but the reproduction result was normal and there was no problem.
![image](https://github.com/microsoft/vcpkg/assets/122244446/89711eab-169f-4413-9ac0-ebc05d7e19f1)

**Comment by TalSomech** [comment]
well i also had opencv2 and opencv4 installed ,
i fixed the bug by installing normally opencv (not through vcpkg) and taking this specific file and put in the lib folder of the opencv ,but still weird

**Comment by lukase** [comment]
Did you enable the 'world' feature for opencv, i.e. './vcpkg install opencv[world]'?

**Comment by jimwang118** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
