### ISSUE TITLE
Error installing pcl 1.8

### ISSUE THREAD

**Issue by Goodvirus** [Microsoft/vcpkg#3139]
Hello everyone,
      I want to install pcl 1.8.1. After running .\vcpkg install pcl:x64-windows, all other packages are installed except pcl[core]. when i try to install it, nothing happens after Build x64-windows-dbg. Setup gets stuck there. 
![error vcpkg](https://user-images.githubusercontent.com/31311332/37964669-ee80f838-31df-11e8-9ee5-9aa4de789da1.png)

Can anyone knows why this is happening?  @UnaNancyOwen 
Thank you

**Comment by Goodvirus** [comment]
@

**Comment by UnaNancyOwen** [comment]
In general, It would take a long time to build the PCL.
It will take several hours depending on your environment.

**Comment by Goodvirus** [comment]
Hi UnaNancyOwen,
        Thanks for reply. I used Cmake to build PCL project in visual studio using [this](https://gist.github.com/UnaNancyOwen/f4dcd74ab870a0fc9e7a#file-cmakelists-txt) CMakeLists.
