### ISSUE TITLE
Two copies of the Eigen headers are installed

### ISSUE THREAD

**Issue by patrikhuber** [Microsoft/vcpkg#3140]
I noticed today that there are two copies of the Eigen headers in my `vcpkg\installed\x64-windows\include` directory. One directly in the "root" of that directory, the other one in the subdirectory `eigen3/`.

I've got the following packages installed (and boost, but I'm not pasting these here, as they should have nothing to do with it and make the list very long):

```
bzip2:x64-windows                                  1.0.6-2          High-quality data compressor.
clapack:x64-windows                                3.2.1-1          CLAPACK (f2c'ed version of LAPACK)
eigen3:x64-windows                                 3.3.4-2          C++ template library for linear algebra: matrice...
fftw3:x64-windows                                  3.3.7-2          FFTW is a C subroutine library for computing the...
liblzma:x64-windows                                5.2.3-2          Compression library with an API similar to that ...
metis:x64-windows                                  5.1.0-1          Serial Graph Partitioning and Fill-reducing Matr...
openblas:x64-windows                               0.2.20-2         OpenBLAS is an optimized BLAS library based on G...
opengl:x64-windows                                 0.0-5            Open Graphics Library (OpenGL)[3][4][5] is a cro...
pugixml:x64-windows                                1.8.1-3          C++ XML processing library
sqlite3:x64-windows                                3.21.0-1         SQLite is a software library that implements a s...
suitesparse:x64-windows                            4.5.5-4          algebra library
zlib:x64-windows                                   1.2.11-3         A compression library
```

What I'll be doing now is uninstalling everything, maybe I can find out more.

**Comment by patrikhuber** [comment]
Ok: `.\vcpkg.exe remove eigen3:x64-windows` removed both copies. So it seems like the eigen3 package installs itself twice into two different directories...

In my opinion the `eigen3` directory should be removed. Eigen should be used by including e.g. `Eigen/Core`, and not `eigen3/Eigen/Core`: http://eigen.tuxfamily.org/dox/GettingStarted.html.

**Comment by Fleischner** [comment]
I think this is still a hack to solve the problem that different dependent packages have different rules on the eigen3 base directory. https://github.com/Microsoft/vcpkg/issues/1284

Would be better to decide for one path and patch all includes in packages that do not respect this rule. However this is currently errorprone, as this problem does not show up during port build as the required include pathes are added by cmake, while once installed by vcpck it is assumed to find all includes from the base include directory and build will break.

**Comment by patrikhuber** [comment]
Ok, I'm closing this in favour of #1284.
