### ISSUE TITLE
LNK2038 when open AddressSanitizer

### ISSUE THREAD

**Issue by linjiahao962889027** [microsoft/vcpkg#31411]
**Describe the bug**
As with the title, when I opened AddressSanitizer, the MSVC compiler encountered error LNK2038. But close AddressSanitizer, the compiler is working properly.

**Environment**
- OS: Windows 11
- Compiler: Visual Studio 2022 （17.5.5）

**To Reproduce**
Compile the project only.

**Expected behavior**
Compilation succeeded and ran.

**Failure logs**
![image](https://github.com/microsoft/vcpkg/assets/46292984/f93e5206-3f89-4422-bd1c-39ec9e9b0e3b)

**Comment by LilyWangLL** [comment]
Closed as duplicate of https://github.com/microsoft/vcpkg/issues/28627.
