### ISSUE TITLE
Fail to execute ninja on 32 bit system

### ISSUE THREAD

**Issue by mojofunk** [microsoft/vcpkg#3142]
I installed vcpkg today on a Windows 7 32bit system and tried to install gtkmm.

It failed to build libepoxy that is built with meson/ninja as it couldn't execute the ninja executable (sorry errors lost in scrollback on another machine)

A quick search brought up this issue https://github.com/ninja-build/ninja/issues/1339
That suggests the ninja binary that is downloaded by vcpkg is 64bit and to build your own if you need 32bit.
So I then:
1. installed downloaded ninja source
2. installed the official python distribution (and added it to PATH)
3. launched a Developer Command Prompt and navigated to the ninja source directory
4. built ninja with $ .\configure.py --bootstrap
5. Moved the resulting executable into the vcpkg root directory

It was then able to complete the build successfully.

I hope integrating a fix for this process into the vcpkg build system is somewhat trivial, as otherwise vcpkg seems like a great tool so far.

**Comment by miurahr** [comment]
IMHO, because vcpkg is a developer tool, a limitation for 32-bit systems is reasonable.
Even when build on vcpkg tool set, resulted binary can run on 32-bit systems.

It is necessary to document it and warn users to use 64-bit systems or solve it with your procedure.

**Comment by Switjoseph** [comment]
its a pity we that have a 32bit machine can't even get to try it

**Comment by linquize** [comment]
Official ninja.exe is 64-bit only.
On Windows, `vcpkg` no longer downloads `ninja`. To use ninja, use the binary from Visual Studio, or download your own copy.

**Comment by PhoebeHui** [comment]
I agree with linquize, please try above suggestions.
