### ISSUE TITLE
error: building boost-vcpkg-helpers:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Angelyatou** [microsoft/vcpkg#31429]
### Operating system

Win

### Compiler

MinGW

### Steps to reproduce the behavior

```Shell
vcpkg install boost-iostreams:x64-windows
```

### Failure logs

![image](https://github.com/microsoft/vcpkg/assets/68850599/2ac01b21-12d4-4d6c-a84a-603a32da7c84)

**Comment by Angelyatou** [comment]
![image](https://github.com/microsoft/vcpkg/assets/68850599/a260481f-8e76-4999-a47c-c7f7702bcc5e)

**Comment by Angelyatou** [comment]
Thanks ,I was able to download it after I opened the web proxy.
![image](https://github.com/microsoft/vcpkg/assets/68850599/bbc6340e-da67-4918-9cba-3efe9659c886)

**Comment by Adela0814** [comment]
I'm glad your problem has been resolved.
