### ISSUE TITLE
[icu] build failure

### ISSUE THREAD

**Issue by LeenHawk** [microsoft/vcpkg#31423]
### Operating system

Linux(Debian Sid)

### Compiler

GCC 12

### Steps to reproduce the behavior

```Shell
vcpkg install icu
```

### Failure logs

[config-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/11469283/config-x64-linux-dbg-out.log)
[config-x64-linux-dbg-config.log](https://github.com/microsoft/vcpkg/files/11469284/config-x64-linux-dbg-config.log)
[config-x64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/11469285/config-x64-linux-dbg-err.log)

**Comment by dg0yt** [comment]
From config.log:
~~~
configure:5067: error: 'autoconf-archive' is missing
~~~

Please install autoconf-archive with your system package manager.
