### ISSUE TITLE
[readline-(unix|win32)] Unify targets

### ISSUE THREAD

**Issue by lionkor** [microsoft/vcpkg#31425]
### Is your feature request related to a problem? Please describe.

On Linux, there is no `readline` target installed by the vcpkg port, which is quite unusual. The way to get `readline` is to depend on `PkgConfig`, then call that to get a `PkgConfig::readline` target. This sucks.

On Windows, there is no `readline` target either. PkgConfig doesn't exist, obviously, so I'm not sure how to get the target at all.

### Proposed solution

On Linux and Windows, a `readline` target should exist, like for almost all other simple libraries like this.

### Describe alternatives you've considered

The alternative is to document what one is supposed to do on each platform, during the configuration step, like most other libraries do, too.

**Comment by dg0yt** [comment]
The windows port offers an `unofficial-readline-win32` CMake package. But the source is an old, unmaintained fork - *this* sucks.
It is not so obvious why pkg-config is missing for Windows. There are many packages which offer and use pkgconfig across all platforms.

**Comment by lionkor** [comment]
As far as I understand, pkg-config would have to be installed on the target system. Maybe a workaround would be to fetch the pkg-config executable first, then use `find_package(PkgConfig...)`. It's just hacky. I sadly have no experience with making or maintaining vcpkg ports, but I'll take a look at it if nobody else responds in the next few days

**Comment by dg0yt** [comment]
pkg-config is less hacky then cmake find modules (or config which is implemented like find modules). It is used as glue between vcpkg ports even for windows triplets. Apart from the msys2 version available via port maintainer functions (but not for user projects), there is also the `pkgconf` port. On non-windows hosts, the system (or brew) package is usually good enough.

If you want uniform cmake config instead, you might add an `unofficial-readline` config to the `readline` port, setting up an interface target which either delegates to the win32 config/target or to the imported target from the non-win32 pkgconfig information.
