### ISSUE TITLE
vcpkg crash

### ISSUE THREAD

**Issue by DougRogers** [microsoft/vcpkg#31433]
Full transcript attached

`C:\vcpkg>vcpkg upgrade --no-dry-run option
warning: Starting with the September 2023 release, the default triplet for vcpkg libraries will change from x86-windows to the detected host triplet (x64-windows). To resolve this message, add --triplet x86-windows to keep the same behavior.
error: The following packages are not installed:
    option:x86-windows
error: The following packages do not have a valid CONTROL or vcpkg.json:
    option:x86-windows
internal error: D:\a\_work\1\s\src\vcpkg\commands.upgrade.cpp(180): vcpkg has crashed; no additional details are available.
Please open an issue at https://github.com/microsoft/vcpkg/issues/new?template=other-type-of-bug-report.md&labels=category:vcpkg-bug with detailed steps to reproduce the problem.
`

[crash.txt](https://github.com/microsoft/vcpkg/files/11472832/crash.txt)

**Comment by DougRogers** [comment]
Accidentally had the word 'option' cut and pasted into the command line

**Comment by autoantwort** [comment]
Even if you provide wrong arguments, vcpkg should not crash.

**Comment by autoantwort** [comment]
I have created #31440
