### ISSUE TITLE
[gmp] build failure on arm64-android

### ISSUE THREAD

**Issue by LeenHawk** [microsoft/vcpkg#31444]
### Operating system

Linux (Debian Sid)

### Compiler

GCC 12

### Steps to reproduce the behavior

```Shell
./vcpkg install gmp:arm64-android
```

### Failure logs

[config-arm64-android-dbg-out.log](https://github.com/microsoft/vcpkg/files/11478589/config-arm64-android-dbg-out.log)
[config-arm64-android-dbg-config.log](https://github.com/microsoft/vcpkg/files/11478590/config-arm64-android-dbg-config.log)
[config-arm64-android-dbg-err.log](https://github.com/microsoft/vcpkg/files/11478591/config-arm64-android-dbg-err.log)

### Additional context

It can work on x64-android, but on arm64-android can't.

**Comment by dg0yt** [comment]
What is meant to avoid issues with whitespace in compiler path leads to the wrong `clang` being used for assembler. Manually adjusting PATH can help as a workaround. The clang dir (`/opt/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/`) is cuurently at the 53rd position...

There are a few other things to get right in the port. I will try to keep this in mind for #31228.

**Comment by LeenHawk** [comment]
It works now.

**Comment by dg0yt** [comment]
> It works now.

As in "I didn't change anything, and suddenly it works"?

**Comment by LeenHawk** [comment]
> > It works now.
> 
> As in "I didn't change anything, and suddenly it works"?

Emm, I find it work suddenly in June, after a vcpkg update. I thought someone fixed it before you refer...

**Comment by JonLiu1993** [comment]
I haven't reproduced the issue locally and it looks like it's been resolved：
````
-- Installing arm64-android-rel
-- Fixing pkgconfig file: /home/test/Jon/vcpkg/packages/gmp_arm64-android/lib/pkgconfig/gmp.pc
-- Fixing pkgconfig file: /home/test/Jon/vcpkg/packages/gmp_arm64-android/lib/pkgconfig/gmpxx.pc
-- Fixing pkgconfig file: /home/test/Jon/vcpkg/packages/gmp_arm64-android/debug/lib/pkgconfig/gmp.pc
-- Fixing pkgconfig file: /home/test/Jon/vcpkg/packages/gmp_arm64-android/debug/lib/pkgconfig/gmpxx.pc
-- Installing: /home/test/Jon/vcpkg/packages/gmp_arm64-android/share/gmp/usage
-- Performing post-build validation
Elapsed time to handle gmp:arm64-android: 45 s
Total install time: 2 min
The package gmp can be imported via CMake FindPkgConfig module:

    #  gmp
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(gmp REQUIRED IMPORTED_TARGET gmp)
    target_link_libraries(main PkgConfig::gmp)

    # gmpxx
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(gmpxx REQUIRED IMPORTED_TARGET gmpxx)
    target_link_libraries(main PkgConfig::gmpxx)

````
