### ISSUE TITLE
Could not find entry for tool [cmake]

### ISSUE THREAD

**Issue by nlappas** [Microsoft/vcpkg#3144]
I downloaded the latest master 12d862ab2b6e387b596e680d334daa212b77fb32 in latest W10 pro.

Ran ` .\bootstrap-vcpkg.bat` and then `.\vcpkg.exe install curl`
and I get `Could not find entry for tool [cmake] in C:/Users/MYUSERNAME/Documents/vcpkg-master/scripts/vcpkgTools.xml`

**Comment by omnisip** [comment]
I'm definitely getting the same issue.

**Comment by alexkaratarakis** [comment]
Should be fixed now! Sorry about that.

**Comment by nlappas** [comment]
Thank you Aleko
