### ISSUE TITLE
[vcpkgtest] error C2039: 'iota': is not a member of 'std'

### ISSUE THREAD

**Issue by gvanem** [microsoft/vcpkg#31454]
I do not know if this is the correct place to report this compiler error for `vcpkgtest.exe`.
But since there are no *Issue* tab for *vcpkg-tool*, I'll do it here:
Plain and simply, it's this compile error when trying to build this test-program using MSVC cl ver. 14.36.32530 (x64):
```c
vcpkg-test/util.cpp(278): error C2039: 'iota': is not a member of 'std'
f:\gv\VC_2022\VC\Tools\MSVC\14.36.32530\include\iomanip(23): note: see declaration of 'std'
vcpkg-test/util.cpp(278): error C3861: 'iota': identifier not found
```

Similar to this [issue](https://github.com/Yishun99/vrp-espprc/issues/1). 
AFAICS, this header if **not** included for `vcpkg-test/util.cpp` in any way. Not in `include/pch.h` where it should perhaps?
So simply adding a `#include <numeric>` to that compilation unit, this error goes away. 

I've also built everything using clang-cl ver. 16.0.0 and had no issues with these things.
But I prefer using `cl -MP ...` for it's amazing speed compared to clang-cl.
Except that with `cl`, I've had to add `-Zc:externConstexpr` to my `CFLAGS` (!).
Build timings for `vcpkg.exe`, `vcpkgfuzz.exe` and `vcpkgtest.exe` using a hacked-up GNU-makefile:
 * `cl -MP ...` 39 sec.
 * `clang-cl`: 10 minutes!
  
BTW, I'm on Win-10.

**Comment by dg0yt** [comment]
> using a hacked-up GNU-makefile

Why? Everybody is using `ninja`.

**Comment by gvanem** [comment]
> Everybody is using ninja.

You mean a hand-edited ninja build-file. You have to be joking. 

What I like about GNU-make is it's clear and concise recipes. No obfuscated CMake, ninja, XML-crap like in VStudio.

**Comment by LilyWangLL** [comment]
This issue has been fixed in https://github.com/microsoft/vcpkg-tool/pull/1069, so I am closing this issue for now. It doesn't need to wait tool release.

**Comment by dg0yt** [comment]
> > using a hacked-up GNU-makefile
> 
> Why? Everybody is using `ninja`.

No, I mean to use the `Ninja' CMake generator.

BTW did you actually run `make` with parallel jobs? 
Or did you actually run `nmake`?

**Comment by gvanem** [comment]
> BTW did you actually run make with parallel jobs?
> Or did you actually run nmake?

Neither, I used a single CPU with GNU-make. Like I wrote, the speed was due due to `cl -MP24 ...`.

**Comment by dg0yt** [comment]
Then the comparison isn't fair. You would need to run with `make -j25`.

**Comment by gvanem** [comment]
> . You would need to run with make -j25

OK. Trying `make -j24 CC=clang-cl`, clocked in at 52 sec.
But the `cl -MP...` is so much more elegant.

**Comment by dg0yt** [comment]
> But the `cl -MP...` is so much more elegant.

I don't see how `cl -MP...` is more elegant than `make -j...` or just `cmake --build`.
`cl -MP` parallelizes only one type of activities. `make` or `ninja` would parallelize all activities (subject to proper dependencies). 
YMMV.
