### ISSUE TITLE
[< zlib:x64-windows>] build failure

### ISSUE THREAD

**Issue by qinghua1995** [microsoft/vcpkg#31455]
### Operating system

Windows

### Compiler

MSVC2015

### Steps to reproduce the behavior

```Shell
./vcpkg.exe install  zlib:x64-windows
```

### Failure logs

$ vcpkg.exe install  zlib:x64-windows
Computing installation plan...
The following packages will be built and installed:
    zlib[core]:x64-windows -> 1.2.13
Detecting compiler hash for triplet x64-windows...
-- Automatically setting HTTP(S)_PROXY environment variables to "127.0.0.1:53958".
Restored 0 package(s) from C:\Users\admin\AppData\Local\vcpkg\archives in 264 us. Use --debug to see more details.
Installing 1/1 zlib:x64-windows...
Building zlib[core]:x64-windows...
-- Using cached madler-zlib-v1.2.13.tar.gz.
-- Cleaning sources at D:/vcpkg/buildtrees/zlib/src/v1.2.13-f30d2a168d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/madler-zlib-v1.2.13.tar.gz
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch 0002-skip-building-examples.patch
-- Applying patch 0003-build-static-or-shared-not-both.patch
-- Applying patch 0004-android-and-mingw-fixes.patch
-- Using source at D:/vcpkg/buildtrees/zlib/src/v1.2.13-f30d2a168d.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: D:/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: D:/vcpkg/buildtrees/zlib/x64-windows-dbg
    See logs for more information:
      D:\vcpkg\buildtrees\zlib\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/zlib/portfile.cmake:26 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building zlib:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+zlib
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[zlib]+Build+error&body=Copy+issue+body+from+D%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

I need to use the zlib library during the compilation of gdal, but found that the installation of zlib failed, so I tried to install zlib separately and found that the above error was printed when installing the zlib library.

**Comment by jimwang118** [comment]
Please provide the following detailed log files. `D:\vcpkg\buildtrees\zlib\install-x64-windows-dbg-out.log`

**Comment by qinghua1995** [comment]
> Please provide the following detailed log files. `D:\vcpkg\buildtrees\zlib\install-x64-windows-dbg-out.log`
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/11504615/install-x64-windows-dbg-out.log)

**Comment by jimwang118** [comment]
The error log shows the following, there is a Chinese path in your path or the anti-virus software has affected your compiler.
![image](https://github.com/microsoft/vcpkg/assets/122244446/b4d9bc28-af7e-4d96-990c-4b4d12f1662a)

**Comment by qinghua1995** [comment]
> 错误日志显示如下，你的路径中有中文路径或者杀毒软件影响了你的编译器。 ![图像](https://user-images.githubusercontent.com/122244446/239177548-b4d9bc28-af7e-4d96-990c-4b4d12f1662a.png)

The vcpkg directory is the root directory of the D drive, and my computer does not have anti-virus software turned on, so I don't know the specific reason for the garbled characters.

**Comment by jimwang118** [comment]
Is the `VS` you installed in English? If not, please install the English language pack and set it to English.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
