### ISSUE TITLE
[<qt] cannot load laugnage translator

### ISSUE THREAD

**Issue by zj951555793** [microsoft/vcpkg#31457]
### Operating system

windows

### Compiler

MSVC 2022

### Steps to reproduce the behavior

```Shell
bool ret = translator->load(":/res/trans/zh_CN.qm");
        qDebug() << "translator" << ret;
        qApp->installTranslator(translator);
        ui->retranslateUi(this);

        QString s = QCoreApplication::translate("MainWindow", "Open", nullptr);
```

### Failure logs

fail

**Comment by FrankXie05** [comment]
Could you please provide the error logs? @zj951555793

**Comment by zj951555793** [comment]
Currently resolved, it is an issue with the translation tool version. I will close this issue，thanks
