### ISSUE TITLE
Update doc guidance for MSBuild to get vcpkg via submodule

### ISSUE THREAD

**Issue by davidmatson** [microsoft/vcpkg#31466]
The homepage currently recommends getting VCPkg via a submodule for CMake projects but installing it globally for MSBuild.

Can this recommendation be updated to recommend a submodule for all cases? MSBuild integration (adding the targets file) works with a submodule, and is much cleaner than having to reference something outside the repository.

**Comment by LilyWangLL** [comment]
https://github.com/microsoft/vcpkg#:~:text=In%20order%20to,continue%20here.
> In order to use vcpkg with Visual Studio, run the following command (may require administrator elevation):
> 
> > .\vcpkg\vcpkg integrate install
> After this, you can now create a New non-CMake Project (or open an existing one). All installed libraries are immediately ready to be #include'd and used in your project without additional configuration.
> 
> If you're using CMake with Visual Studio, continue [here](https://github.com/microsoft/vcpkg#vcpkg-with-visual-studio-cmake-projects).

Thanks for posting this issue. The README has content related to MSBuild integration, the above is it. It separates from the introduction of CMake.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by davidmatson** [comment]
@LilyWangLL - I'd like to see us update the README not to say that submodules are for CMake only - if submodules are the best answer for CMake because they keep the repo self-contained, I think the same is true for MSBuild, and we shouldn't recommend a global install for MSBuild users.

Could we update the readme to recommend using a submodule regardless of which build system you're using?

**Comment by davidmatson** [comment]
Also, I don't seem to have a way to re-open this issue - could you please do so for me?

**Comment by Cheney-W** [comment]
@davidmatson 
> MSBuild integration (adding the targets file) works with a submodule

I'm sorry, I'm not quite clear about the specific operation here. Could you please provide more details? For example, what exactly is meant by a "submodule" in this context?

**Comment by davidmatson** [comment]
> @davidmatson
> 
> > MSBuild integration (adding the targets file) works with a submodule
> 
> I'm sorry, I'm not quite clear about the specific operation here. Could you please provide more details? For example, what exactly is meant by a "submodule" in this context?

A git submodule. I submitted a PR with the proposed fixes here - let me know if that clarifies.
