### ISSUE TITLE
protobuf 

### ISSUE THREAD

**Issue by LemonHopeAT** [Microsoft/vcpkg#3146]
Hello!
I'm trying to install protobuf, but I get an error

`
>vcpkg install protobuf protobuf:x64-windows
The following packages will be built and installed:
    protobuf[core]:x86-windows
    protobuf[core]:x64-windows
Starting package 1/2: protobuf:x86-windows
Building package protobuf[core]:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/vcpkg/packages/protobuf_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/vcpkg/buildtrees/protobuf
-- CURRENT_PORT_DIR=C:/vcpkg/ports/protobuf/.
-- Using cached C:/vcpkg/downloads/protobuf-cpp-3.5.1.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch C:/vcpkg/ports/protobuf/001-add-compiler-flag.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/vcpkg/ports/protobuf/001-add-compiler-flag.patch done
-- Applying patch C:/vcpkg/ports/protobuf/export-ParseGeneratorParameter.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/vcpkg/ports/protobuf/export-ParseGeneratorParameter.patch done
-- Applying patch C:/vcpkg/ports/protobuf/js-embed.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/vcpkg/ports/protobuf/js-embed.patch done
-- Using cached C:/vcpkg/downloads/protoc-3.5.1-win32.zip
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: C:/vcpkg/buildtrees/protobuf/x86-windows-rel/vcpkg-parallel-configure
    See logs for more information:
      C:\vcpkg\buildtrees\protobuf\config-x86-windows-out.log
Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:235 (vcpkg_execute_required_process)
  ports/protobuf/portfile.cmake:61 (vcpkg_configure_cmake)
  scripts/ports.cmake:72 (include)
Error: Building package protobuf:x86-windows failed with: BUILD_FAILED
`

**Comment by JackBoosY** [comment]
Hi @LemonHopeAT , thanks for reporting this issue.
Please open a new issue if this is still a problem for you.
Thx.
