### ISSUE TITLE
[qt] qtdeclarative build failure

### ISSUE THREAD

**Issue by freestriker** [microsoft/vcpkg#31463]
### Operating system

Windows 11 22H2 22621.1635

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
cmake -B ./build

use those in cmakelist:
set(CMAKE_TOOLCHAIN_FILE $ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake)
set(VCPKG_TARGET_TRIPLET x64-windows-static)

vcpkg-configuration.json:
{
    "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg-configuration.schema.json",
    "default-registry": {
        "kind": "git",
        "repository": "https://github.com/microsoft/vcpkg",
        "baseline": "d4d39d71b3e6dd7536592c36ab2f7e84a8a64942"
    },
    "registries": [
        {
            "kind": "git",
            "repository": "https://github.com/freestriker/vcpkg-registry",
            "baseline": "e7113602a69c98d5b68447e6fe882778f6cd597f",
            "packages": [ "opencv4" ]
        }
    ]
}

vcpkg.json:
{
    "name": "cmaketest",
    "dependencies": [
        {
            "name": "opencv4", 
            "features": ["openexr"]
        },
        {
            "name": "vulkan"
        },
        {
            "name": "qt"
        }
    ]
}
```

### Failure logs

PS D:\Project\CmakeTest> cmake -B ./build
-- Running vcpkg install
Fetching registry information from https://github.com/microsoft/vcpkg (HEAD)...
Detecting compiler hash for triplet x64-windows...
-- Automatically setting HTTP(S)_PROXY environment variables to "127.0.0.1:20081".
Detecting compiler hash for triplet x64-windows-static...
The following packages will be built and installed:
  * assimp[core]:x64-windows-static -> 5.2.5 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\bdd963b2ef327bf5e8533689aff4707226e22851
  * draco[core]:x64-windows-static -> 1.5.6 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\bed378402e689e540a924f99869f7134d74bbdfb
  * freeglut[core]:x64-windows-static -> 3.4.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\51a55df4538f3ecdeeb6d9846afd156ec3255630
  * gumbo[core]:x64-windows -> 0.10.1#6 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\b0b57c7286bdadcc64d0e4b2f5b5aca951bb1749
  * gumbo[core]:x64-windows-static -> 0.10.1#6 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\b0b57c7286bdadcc64d0e4b2f5b5aca951bb1749
  * hunspell[core]:x64-windows-static -> 1.7.1#3 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\798ac2e490d16afc2713b95740101c03fa555f84
  * jasper[core,default-features,opengl]:x64-windows-static -> 4.0.0#2 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\d7f51c26899ba9433a5a3ab92fc5b5887d5c764c
  * kubazip[core]:x64-windows-static -> 0.2.4 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\14bf9d5b15ecf5769d10e5000e74167e97b0ade1
  * libarchive[bzip2,core,crypto,libxml2,lz4,lzma,zstd]:x64-windows -> 3.6.2 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\693a99004af1e09acaf76026eaf23218b00c6661
  * libarchive[bzip2,core,crypto,libxml2,lz4,lzma,zstd]:x64-windows-static -> 3.6.2 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\693a99004af1e09acaf76026eaf23218b00c6661
  * libiconv[core]:x64-windows -> 1.17#1 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\4226589d5d658f4d96df83f8539de54dc57a5996
  * libiconv[core]:x64-windows-static -> 1.17#1 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\4226589d5d658f4d96df83f8539de54dc57a5996
  * liblzma[core]:x64-windows -> 5.4.1#1 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\9a3ebbf75e1c3adb76d7e71717c1f03bb291036a
  * libxml2[core,iconv,lzma,zlib]:x64-windows -> 2.10.3#1 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\fd1e750ce7851d72bf39c0b6d30a4a8d1d717c45
  * libxml2[core,iconv,lzma,zlib]:x64-windows-static -> 2.10.3#1 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\fd1e750ce7851d72bf39c0b6d30a4a8d1d717c45
  * libyaml[core]:x64-windows -> 0.2.5#4 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\ae6fcd42cb9d1448913be2c7eb536df813601230
  * libyaml[core]:x64-windows-static -> 0.2.5#4 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\ae6fcd42cb9d1448913be2c7eb536df813601230
  * litehtml[core]:x64-windows-static -> 0.6.0#2 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\fbbd4d593d570ec75f5a02fea10a236aecc810d4
  * litehtml[core]:x64-windows -> 0.6.0#2 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\fbbd4d593d570ec75f5a02fea10a236aecc810d4
  * minizip[core]:x64-windows-static -> 1.2.13#2 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\48d519ab0025623c54756c482453f8405d2646bd
  * open62541[amalgamation,core,historizing,openssl]:x64-windows-static -> 1.3.5 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\e7412d5c63f5b77eb06f485b7fb89bb718b2f712
  * pkgconf[core]:x64-windows -> 1.8.0#5 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\8848e56b32837456dfb872f6ca3cc9953558d453
  * poly2tri[core]:x64-windows-static -> 2020-07-21#3 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\6f490bcfed9bb8b55036006a4389bfa7e94c73ff
  * pugixml[core]:x64-windows-static -> 1.13.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\4547c4ff9371f06f34f087f2989f884ab3ef7b71
    qt[core,default-features]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\ecd656220f58ebf6651801b9fc439ba5d8f6b62b
  * qt3d[animation,assimp,core,extras,input,logic,qml,render,rhi]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\56a3a7a27a022640d0f965aeb1d56ece4c63006d
  * qt5compat[big-codecs,codecs,core,default-features,qml,textcodec]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\b4a3c116018e4b6f97e056193c82af718bda10b3
  * qtactiveqt[core,qml]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\906e0b257af28f5690907f94ad79bc95f3a34f5c
  * qtactiveqt[core]:x64-windows -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\906e0b257af28f5690907f94ad79bc95f3a34f5c
  * qtapplicationmanager[core]:x64-windows -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\02767f9ffe5a4a96fa2555440e17e92d1795548d
  * qtapplicationmanager[core]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\02767f9ffe5a4a96fa2555440e17e92d1795548d
  * qtcharts[core,designer,qml]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\a9cb7b445154fb5957aec5455428d0bde929fcda
  * qtcoap[core]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\f5c864cedd1698478c95617d82ba56b1dd240ab2
  * qtconnectivity[core]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\4e87723595352e8637721bea77ffc9c1ad73c031
  * qtdatavis3d[core]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\55f14b0a4149603a1d171ebf4cc99d8dfb2739c3
  * qtdeclarative[core]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\c0d4c48a9b7ef8047bb2068271fb433deddd3ffb
  * qtdoc[core]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\54a7e5b497830856aad12dec08b7bb01c37b4999
  * qtimageformats[core,default-features,jasper,tiff,webp]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\6a6f759bf37a0bbc86ccdac3eccbfa40816cbd79
  * qtinterfaceframework[core]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\3c0fac0141ef882b26d1904189a1aafd4dc4540f
  * qtinterfaceframework[core]:x64-windows -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\3c0fac0141ef882b26d1904189a1aafd4dc4540f
  * qtlanguageserver[core]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\248be805b9a3c9d95efa723392d374a9c94a5c27
  * qtlottie[core,qml]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\5c8d01536a9c595ddc58327caac428c86ffe2262
  * qtmqtt[core]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\3129ca4a0ba4f6e94550a56d32228560cb3483f9
  * qtmultimedia[core,qml,widgets]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\a10258ebedf8a3f71b8d761b58933e40bf70fac3
  * qtmultimedia[core,widgets]:x64-windows -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\a10258ebedf8a3f71b8d761b58933e40bf70fac3
  * qtnetworkauth[core]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\767609a9d9713dae6a4c0fd2696a1ec994e28e21
  * qtopcua[core,default-features,gds,ns0idnames,open62541,qml]:x64-windows-static -> 6.5.0#1 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\efe3fbd8d37c121fbb7758de82fac9bd4b315a77
  * qtpositioning[core,qml]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\0da142e2b032f345e88aed41ef444684523be056
  * qtquick3d[core,default-features]:x64-windows -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\ab3f7bbf20de8d370d5ac8711f2190d96db87f7e
  * qtquick3d[core,default-features]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\ab3f7bbf20de8d370d5ac8711f2190d96db87f7e
  * qtquicktimeline[core]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\3f9caf40f1987be65ca3ce699cd176c4453bea14
  * qtquicktimeline[core]:x64-windows -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\3f9caf40f1987be65ca3ce699cd176c4453bea14
  * qtremoteobjects[core,qml]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\cce29bbf6dbad6125ffd59ca29bbc0fd8f9d1108
  * qtremoteobjects[core]:x64-windows -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\cce29bbf6dbad6125ffd59ca29bbc0fd8f9d1108
  * qtscxml[core,qml]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\a900efa4d344d886cba9d538ecee24346957a76f
  * qtscxml[core]:x64-windows -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\a900efa4d344d886cba9d538ecee24346957a76f
  * qtsensors[core,qml]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\2520f438dda2ec0a8b244be6e1b0fc839e26948d
  * qtserialbus[core,default-features]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\8a3dea63a3bfc75f36c32fffd27ff7e300febc8f
  * qtserialbus[core,default-features]:x64-windows -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\8a3dea63a3bfc75f36c32fffd27ff7e300febc8f
  * qtserialport[core]:x64-windows -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\e16e52bb2baeb3a3af3d096cf6357e2494b325d6
  * qtserialport[core]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\e16e52bb2baeb3a3af3d096cf6357e2494b325d6
  * qtspeech[core]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\6407a70cfbb2ced50ed116bd1e51b8f3a7e54c8a
  * qtsvg[core]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\816b0eb532cf6901c8448ccba8363cfe9938ef5b
  * qttools[assistant,core,designer,linguist,qml]:x64-windows-static -> 6.5.0#1 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\98c6a3ef4410b89a77895592986355c43674a881
  * qttools[assistant,core,designer,linguist]:x64-windows -> 6.5.0#1 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\98c6a3ef4410b89a77895592986355c43674a881
  * qttranslations[core,default-features]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\b75cda024ccc8c8ba3f9a196a9a6149309d93425
  * qtvirtualkeyboard[core,default-features,hunspell]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\2591b11ad8fe48bb353ece5a06c8c27492cb1c1d
  * qtwebchannel[core,qml]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\40d6a94591187d5fdfb57beebbbad45aa26a1859
  * qtwebsockets[core,qml]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\c325d5163eea00256739eb59ac084c0c386c2b0d
  * qtwebview[core]:x64-windows-static -> 6.5.0 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\250bcb4eb32ec73ee4376ec7af6a365c8f8f61f1
  * rapidjson[core]:x64-windows-static -> 2023-04-27 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\ea1032a866631acc7d63b4804be4ece09baeb47f
  * stb[core]:x64-windows-static -> 2023-04-11#1 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\acd9c2bf96a3e32fbf629b1bfd6cba4827761069
  * taglib[core]:x64-windows-static -> 1.13.0#1 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\a3ab8e6485aab876d06d0e43ab29372b54863467
  * taglib[core]:x64-windows -> 1.13.0#1 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\a3ab8e6485aab876d06d0e43ab29372b54863467
  * utfcpp[core]:x64-windows-static -> 3.2.3 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\6871a843dce2e99e0973ca0a2a837ea78c3add39
    vulkan[core]:x64-windows-static -> 1.1.82.1#6 -- C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\ea62236a3c91051f5ccb340442b60a026bf160c6
Additional packages (*) will be modified to complete this operation.
Restored 0 package(s) from C:\Users\FREEstriker\AppData\Local\vcpkg\archives in 37.9 ms. Use --debug to see more details.
Installing 1/76 qtdeclarative:x64-windows-static...
Building qtdeclarative[core]:x64-windows-static...
-- Installing port from location: C:\Users\FREEstriker\AppData\Local\vcpkg\registries\git-trees\c0d4c48a9b7ef8047bb2068271fb433deddd3ffb
-- Using cached qtdeclarative-everywhere-src-6.5.0.tar.xz.
-- Cleaning sources at D:/Project/vcpkg/buildtrees/qtdeclarative/src/here-src-6-b6137c37a7.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Project/vcpkg/downloads/qtdeclarative-everywhere-src-6.5.0.tar.xz
-- Using source at D:/Project/vcpkg/buildtrees/qtdeclarative/src/here-src-6-b6137c37a7.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: E:/Software/CMake/bin/cmake.exe --build . --config Debug --target install -- -v -j17
    Working Directory: D:/Project/vcpkg/buildtrees/qtdeclarative/x64-windows-static-dbg
    See logs for more information:
      D:\Project\vcpkg\buildtrees\qtdeclarative\install-x64-windows-static-dbg-out.log

Call Stack (most recent call first):
  D:/Project/CmakeTest/build/vcpkg_installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  D:/Project/CmakeTest/build/vcpkg_installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  D:/Project/CmakeTest/build/vcpkg_installed/x64-windows-static/share/qtbase/qt_install_submodule.cmake:348 (vcpkg_cmake_install)
  C:/Users/FREEstriker/AppData/Local/vcpkg/registries/git-trees/c0d4c48a9b7ef8047bb2068271fb433deddd3ffb/portfile.cmake:25 (qt_install_submodule)
  scripts/ports.cmake:147 (include)

error: building qtdeclarative:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qtdeclarative
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[qtdeclarative]+Build+error&body=Copy+issue+body+from+D%3A%2FProject%2FCmakeTest%2Fbuild%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md

-- Running vcpkg install - failed
CMake Error at D:/Project/vcpkg/scripts/buildsystems/vcpkg.cmake:893 (message):
  vcpkg install failed.  See logs for more information:
  D:\Project\CmakeTest\build\vcpkg-manifest-install.log
Call Stack (most recent call first):
  build/CMa
[install-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/11487956/install-x64-windows-static-dbg-out.log)
keFiles/3.26.3/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:25 (project)

-- Configuring incomplete, errors occurred!

### Additional context

before i add the qt package in vcpkg.json, it works, so i think the error occurs when install qt

**Comment by Osyotr** [comment]
Duplicate of https://github.com/microsoft/vcpkg/issues/28083?
BTW, you don't need to add whole `qt` into your dependency list. Usually qtbase is all you need.

**Comment by Adela0814** [comment]
@freestriker  Please use `--x-buildtrees-root=<shortpath>`.
