### ISSUE TITLE
error trying to update vcpkg in CLION

### ISSUE THREAD

**Issue by TalSomech** [microsoft/vcpkg#31475]
**Describe the bug**
cant use vcpkg in clion
**Environment**
- OS: windows
-IDE: CLION

**To Reproduce**
install vcpkg
try to update

**Failure logs**
error: Your local changes to the following files would be overwritten by merge:
	versions/baseline.json
Please commit your changes or stash them before you merge.
Updating 36fb23307..b3e0a1e62
Aborting

**Additional context**

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Did you change the `versions/baseline.json` file before run update command?

**Comment by TalSomech** [comment]
nope
