### ISSUE TITLE
[New Port Request] <wireshark>

### ISSUE THREAD

**Issue by WangHHY19931001** [microsoft/vcpkg#31470]
### Library name

wireshark

### Source repository URL

https://gitlab.com/wireshark/wireshark

### Project homepage (if different from the source repository)

https://www.wireshark.org/

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

Wireshark is a network traffic analyzer, or "sniffer", for Linux, macOS, \*BSD and other Unix and Unix-like operating systems and for Windows. It uses Qt, a graphical user interface library, and libpcap and npcap as packet capture and filtering libraries.

The Wireshark distribution also comes with TShark, which is a line-oriented sniffer (similar to Sun's snoop or tcpdump) that uses the same dissection, capture-file reading and writing, and packet filtering code as Wireshark, and with editcap, which is a program to read capture files and write the packets from that capture file, possibly in a different capture file format, and with some packets possibly removed from the capture.

The official home of Wireshark is https://www.wireshark.org.

The latest distribution can be found in the subdirectory https://www.wireshark.org/downloadWireshark is a network traffic analyzer, or "sniffer", for Linux, macOS,
*BSD and other Unix and Unix-like operating systems and for Windows.
It uses Qt, a graphical user interface library, and libpcap and npcap as
packet capture and filtering libraries.
The Wireshark distribution also comes with TShark, which is a
line-oriented sniffer (similar to Sun's snoop or tcpdump) that uses the
same dissection, capture-file reading and writing, and packet filtering
code as Wireshark, and with editcap, which is a program to read capture
files and write the packets from that capture file, possibly in a
different capture file format, and with some packets possibly removed
from the capture.
The official home of Wireshark is https://www.wireshark.org/.
The latest distribution can be found in the subdirectory https://www.wireshark.org/download

**Comment by WangHHY19931001** [comment]
is this port can be add?

**Comment by WangHHY19931001** [comment]
can't add？

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
