### ISSUE TITLE
[vcpkg-tool] Windows Defender finds a "Win32/Casur.A!cl" trojan in vcpkg-tool repository

### ISSUE THREAD

**Issue by eao197** [microsoft/vcpkg#31476]
I'm sorry, this issue relates to https://github.com/microsoft/vcpkg-tool repository, not to the package collection. However, vcpkg-tool repository has no Issue section so I don't know how to report this problem another way.

I just cloned https://github.com/microsoft/vcpkg-tool to my Windows 10 machine and Windows Defender found a treat inside vcpkg-tool files. See the attached screenshot for more details.
![Screenshot-20230517-1242](https://github.com/microsoft/vcpkg/assets/11836621/16e29e1e-4189-4f35-8bc0-43f9f4e9f15b)

**Comment by jimwang118** [comment]
This is a false positive of the system antivirus software, which sometimes exists for some executable programs. But it does not affect the use of `vcpkg-tool`.

**Comment by eao197** [comment]
Thanks. Is there any way to report this case to the antivirus team to aviod such false positives in the future?
