### ISSUE TITLE
FR: Push already installed packages to binary cache

### ISSUE THREAD

**Issue by huangqinjin** [microsoft/vcpkg#31472]
Use cases:
- Add new binary sources
- Re-push due to network failed during installation.

**Comment by Adela0814** [comment]
@huangqinjin  Which binary source are you using? Please provide your commands and failure log. Thanks.

**Comment by huangqinjin** [comment]
I am using NuGet. No failure log since it is expected to fail due to network issue.

This is feature request rather than an issue need to debug.

**Comment by huangqinjin** [comment]
I am still looking for this feature. Kindly reopen.
