### ISSUE TITLE
[glib] build failure ?

### ISSUE THREAD

**Issue by RainbowTaro2022** [microsoft/vcpkg#31486]
### Operating system

windows

### Steps to reproduce the behavior

```Shell
G:\vcpkg>vcpkg install glib --triplet=x64-android
Computing installation plan...
The following packages will be built and installed:
  * bzip2[core,tool]:x64-android -> 1.0.8#4
  * dirent[core]:x64-android -> 1.23.2#2
  * gettext[core]:x64-android -> 0.21.1
    glib[core]:x64-android -> 2.76.1#1
  * libffi[core]:x64-android -> 3.4.4#1
  * libiconv[core]:x64-android -> 1.17#1
  * pcre2[core,jit,platform-default-features]:x64-android -> 10.40#2
  * zlib[core]:x64-android -> 1.2.13
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-android...
error: while detecting compiler information:
The log file content at "G:\vcpkg\buildtrees\detect_compiler\stdout-x64-android.log" is:
-- Configuring x64-android
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: G:/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe -v
    Working Directory: G:/vcpkg/buildtrees/detect_compiler/x64-android-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      G:\vcpkg\buildtrees\detect_compiler\config-x64-android-rel-CMakeCache.txt.log
      G:\vcpkg\buildtrees\detect_compiler\config-x64-android-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:310 (vcpkg_execute_required_process)
  scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:147 (include)



error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.
```

### Failure logs

[stdout-x86-android.log](https://github.com/microsoft/vcpkg/files/11500491/stdout-x86-android.log)
[config-x64-freebsd-out.log](https://github.com/microsoft/vcpkg/files/11500492/config-x64-freebsd-out.log)
[config-x64-osx-release-out.log](https://github.com/microsoft/vcpkg/files/11500493/config-x64-osx-release-out.log)
[config-x86-android-out.log](https://github.com/microsoft/vcpkg/files/11500495/config-x86-android-out.log)
[stdout-x64-android.log](https://github.com/microsoft/vcpkg/files/11500496/stdout-x64-android.log)
[stdout-x64-freebsd.log](https://github.com/microsoft/vcpkg/files/11500497/stdout-x64-freebsd.log)
[stdout-x64-osx-release.log](https://github.com/microsoft/vcpkg/files/11500498/stdout-x64-osx-release.log)

### Additional context

windows不能跨平台编译吗？

**Comment by RainbowTaro2022** [comment]
我只是设置了ANDROID_NDK，结果还是不行
NDK在G:

还有cmake支持IOS跨平台编译吗？
我知道OSX的软件包管理器是homebrew
但你们这里没有homebrew，那怎么编译啊

还有Android的编译器应该是gradie

我还有一个建议，能不能把gentoo的emerge移植过来
我知道你们这里是支持跨平台的，你们可以和gentoo的社区联系一下

**Comment by RainbowTaro2022** [comment]
其实你们可以把swift移植过来，我已经提交了issues

**Comment by RainbowTaro2022** [comment]
[https://github.com/apple/swift/issues/65382](url)

**Comment by dg0yt** [comment]
https://learn.microsoft.com/en-us/vcpkg/users/platforms/android

**Comment by RainbowTaro2022** [comment]
知道了

**Comment by RainbowTaro2022** [comment]
D:\vcpkg>vcpkg install kf5windowsystem kf5sonnet kf5sonnet[hunspell] kf5kio[kf5wallet] kf5kio[kf5notifications] kf5kio[unixkf5notifications] kf5i18n kf5diagram kf5declarative kf5config --triplet=x64-windows --recurse
Computing installation plan...
The following packages will be built and installed:
  * gettext[core,tools]:x64-windows -> 0.21.1
  * hunspell[core]:x64-windows -> 1.7.1#3
  * kf5archive[bzip2,core]:x64-windows -> 5.98.0
  * kf5bookmarks[core]:x64-windows -> 5.98.0
  * kf5codecs[core]:x64-windows -> 5.98.0
  * kf5completion[core]:x64-windows -> 5.98.0
    kf5config[core]:x64-windows -> 5.98.0
  * kf5configwidgets[core]:x64-windows -> 5.98.0
  * kf5coreaddons[core]:x64-windows -> 5.98.0
  * kf5crash[core]:x64-windows -> 5.98.0
  * kf5dbusaddons[core]:x64-windows -> 5.98.0
    kf5declarative[core]:x64-windows -> 5.98.0
    kf5diagram[core]:x64-windows -> 2.8.0#1
  * kf5guiaddons[core,defaults]:x64-windows -> 5.98.0
    kf5i18n[core]:x64-windows -> 5.98.0
  * kf5iconthemes[core]:x64-windows -> 5.98.0
  * kf5itemviews[core]:x64-windows -> 5.98.0
  * kf5jobwidgets[core]:x64-windows -> 5.98.0
    kf5kio[core,kf5notifications,kf5wallet,unixkf5notifications]:x64-windows -> 5.98.0
  * kf5notifications[core]:x64-windows -> 5.98.0
  * kf5package[core]:x64-windows -> 5.98.0
  * kf5service[core]:x64-windows -> 5.98.0
  * kf5solid[core,platform-default-features]:x64-windows -> 5.98.0#1
    kf5sonnet[core,hunspell]:x64-windows -> 5.98.0
  * kf5textwidgets[core]:x64-windows -> 5.98.0
  * kf5wallet[core]:x64-windows -> 5.98.0
  * kf5widgetsaddons[core]:x64-windows -> 5.98.0
    kf5windowsystem[core]:x64-windows -> 5.98.0
  * kf5xmlgui[core]:x64-windows -> 5.98.0
  * libsnoretoast[core]:x64-windows -> 0.8.0#2
  * qt5-activeqt[core]:x64-windows -> 5.15.9
  * qt5-base[core]:x64-windows -> 5.15.9#2
  * qt5-declarative[core,d3d12,platform-default-features]:x64-windows -> 5.15.9#1
  * qt5-imageformats[core,tiff,webp]:x64-windows -> 5.15.9#1
  * qt5-svg[core]:x64-windows -> 5.15.9
  * qt5-tools[core]:x64-windows -> 5.15.9
  * qt5-winextras[core]:x64-windows -> 5.15.9
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\Lenovo\AppData\Local\vcpkg\archives in 2.18 ms. Use --debug to see more details.
Installing 1/37 gettext:x64-windows...
Building gettext[core,tools]:x64-windows...
-- Using cached gettext-0.21.1.tar.gz.
-- Cleaning sources at D:/vcpkg/buildtrees/gettext/src/gettext-0-de39ca5451.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/gettext-0.21.1.tar.gz
-- Applying patch android.patch
-- Applying patch uwp.patch
-- Applying patch win-gethostname.patch
-- Applying patch 0003-Fix-win-unicode-paths.patch
-- Applying patch rel_path.patch
-- Using source at D:/vcpkg/buildtrees/gettext/src/gettext-0-de39ca5451.clean
-- Getting CMake variables for x64-windows
-- Using cached msys-gzip-1.11-1-x86_64.pkg.tar.zst.
-- Using cached msys-bash-5.1.008-1-x86_64.pkg.tar.zst.
-- Using cached msys-autoconf-2.71-3-any.pkg.tar.zst.
-- Using cached msys-diffutils-3.8-2-x86_64.pkg.tar.zst.
-- Using cached msys-binutils-2.37-5-x86_64.pkg.tar.zst.
-- Using cached msys-libtool-2.4.7-3-x86_64.pkg.tar.zst.
-- Using cached msys-file-5.41-2-x86_64.pkg.tar.zst.
-- Using cached msys-zlib-1.2.11-1-x86_64.pkg.tar.xz.
-- Using cached msys-libbz2-1.0.8-3-x86_64.pkg.tar.zst.
-- Using cached msys-coreutils-8.32-2-x86_64.pkg.tar.zst.
-- Using cached msys-grep-3.0-2-x86_64.pkg.tar.xz.
-- Using cached msys-sed-4.8-2-x86_64.pkg.tar.zst.
-- Using cached msys-libpcre-8.45-1-x86_64.pkg.tar.zst.
-- Using cached msys-m4-1.4.19-2-x86_64.pkg.tar.zst.
-- Using cached msys-automake-wrapper-11-4-any.pkg.tar.zst.
-- Using cached msys-gawk-5.1.0-2-x86_64.pkg.tar.zst.
-- Using cached msys-mpfr-4.1.0-1-x86_64.pkg.tar.zst.
-- Using cached msys-gmp-6.2.1-1-x86_64.pkg.tar.zst.
-- Using cached msys-libreadline-8.1.001-1-x86_64.pkg.tar.zst.
-- Using cached msys-ncurses-6.2-2-x86_64.pkg.tar.zst.
-- Using cached msys-automake1.16-1.16.3-3-any.pkg.tar.zst.
-- Using cached msys-perl-5.32.1-2-x86_64.pkg.tar.zst.
-- Using cached msys-libcrypt-2.1-3-x86_64.pkg.tar.zst.
-- Using cached msys-pkg-config-0.29.2-4-x86_64.pkg.tar.zst.
-- Using cached msys-make-4.3-3-x86_64.pkg.tar.zst.
-- Using cached msys-findutils-4.8.0-1-x86_64.pkg.tar.zst.
-- Using cached msys-libintl-0.21-1-x86_64.pkg.tar.zst.
-- Using cached msys-libiconv-1.16-2-x86_64.pkg.tar.zst.
-- Using cached msys-gcc-libs-11.2.0-3-x86_64.pkg.tar.zst.
-- Using cached msys-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using cached msys-which-2.21-4-x86_64.pkg.tar.zst.
-- Using msys root at D:/vcpkg/downloads/tools/msys2/e6f7ae10db8f00f6
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at D:/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Configuring x64-windows-rel
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: D:/vcpkg/downloads/tools/msys2/e6f7ae10db8f00f6/usr/bin/make.exe -j 13 --trace -f D:/vcpkg/ports/gettext/Makefile all
    Working Directory: D:/vcpkg/buildtrees/gettext/x64-windows-rel/
    See logs for more information:
      D:\vcpkg\buildtrees\gettext\build-x64-windows-rel-out.log
      D:\vcpkg\buildtrees\gettext\build-x64-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:151 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:2 (vcpkg_build_make)
  ports/gettext/portfile.cmake:69 (vcpkg_install_make)
  ports/gettext/portfile.cmake:99 (build_libintl_and_tools)
  scripts/ports.cmake:147 (include)

**Comment by RainbowTaro2022** [comment]
[config-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/11506152/config-x64-windows-rel-out.log)
[config-x64-windows-rel-err.log](https://github.com/microsoft/vcpkg/files/11506154/config-x64-windows-rel-err.log)

**Comment by RainbowTaro2022** [comment]
[build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/11506162/build-x64-windows-rel-out.log)
[build-x64-windows-rel-err.log](https://github.com/microsoft/vcpkg/files/11506164/build-x64-windows-rel-err.log)

**Comment by RainbowTaro2022** [comment]
可以把swift移植到vcpkg吗？

**Comment by RainbowTaro2022** [comment]
CMake Error at G:/python310/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:67 (message):
  The C compiler

    "G:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: G:/Cone/embree-3.13.5/build/CMakeFiles/CMakeScratch/TryCompile-txebo1

    Run Build Command(s):G:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_e3112.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && MSBuild version 17.6.3+07e294721 for .NET Framework
    生成启动时间为 2023/5/20 16:36:25。

    节点 1 上的项目“G:\Cone\embree-3.13.5\build\CMakeFiles\CMakeScratch\TryCompile-txebo1\cmTC_e3112.vcxproj”(默认目标)。
    PrepareForBuild:
      正在创建目录“cmTC_e3112.dir\Debug\”。
      正在创建目录“G:\Cone\embree-3.13.5\build\CMakeFiles\CMakeScratch\TryCompile-txebo1\Debug\”。
      正在创建目录“cmTC_e3112.dir\Debug\cmTC_e3112.tlog\”。
    InitializeBuildStatus:
      正在创建“cmTC_e3112.dir\Debug\cmTC_e3112.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
    ClCompile:
      G:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_e3112.dir\Debug\\" /Fd"cmTC_e3112.dir\Debug\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "G:\Cone\embree-3.13.5\build\CMakeFiles\CMakeScratch\TryCompile-txebo1\testCCompiler.c"
      用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.36.32532 版
      testCCompiler.c
      版权所有(C) Microsoft Corporation。保留所有权利。
      cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_e3112.dir\Debug\\" /Fd"cmTC_e3112.dir\Debug\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "G:\Cone\embree-3.13.5\build\CMakeFiles\CMakeScratch\TryCompile-txebo1\testCCompiler.c"
    Link:
      G:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE /OUT:"G:\Cone\embree-3.13.5\build\CMakeFiles\CMakeScratch\TryCompile-txebo1\Debug\cmTC_e3112.exe" /INCREMENTAL /ILK:"cmTC_e3112.dir\Debug\cmTC_e3112.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"G:/Cone/embree-3.13.5/build/CMakeFiles/CMakeScratch/TryCompile-txebo1/Debug/cmTC_e3112.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"G:/Cone/embree-3.13.5/build/CMakeFiles/CMakeScratch/TryCompile-txebo1/Debug/cmTC_e3112.lib" /MACHINE:X64  /machine:x64 cmTC_e3112.dir\Debug\testCCompiler.obj
      cmTC_e3112.vcxproj -> G:\Cone\embree-3.13.5\build\CMakeFiles\CMakeScratch\TryCompile-txebo1\Debug\cmTC_e3112.exe
    PostBuildEvent:
      setlocal
      C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noprofile -executionpolicy Bypass -file G:/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary G:/Cone/embree-3.13.5/build/CMakeFiles/CMakeScratch/TryCompile-txebo1/Debug/cmTC_e3112.exe -installedDir G:/vcpkg/installed/x64-windows/debug/bin -OutVariable out
      if %errorlevel% neq 0 goto :cmEnd
      :cmEnd
      endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
      :cmErrorLevel
      exit /b %1
      :cmDone
      if %errorlevel% neq 0 goto :VCEnd
      :VCEnd
      -File 形式参数的实际参数“G:/vcpkg/scripts/buildsystems/msbuild/applocal.ps1”不存在。请提供现有“.ps1”文件的路径，作为 -File 形式参数的一个实际参数。
      Windows PowerShell
      版权所有（C） Microsoft Corporation。保留所有权利。

      安装最新的 PowerShell，了解新功能和改进！https://aka.ms/PSWindows

    G:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: 命令“setlocal [G:\Cone\embree-3.13.5\build\CMakeFiles\CMakeScratch\TryCompile-txebo1\cmTC_e3112.vcxproj]
    G:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noprofile -executionpolicy Bypass -file G:/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary G:/Cone/embree-3.13.5/build/CMakeFiles/CMakeScratch/TryCompile-txebo1/Debug/cmTC_e3112.exe -installedDir G:/vcpkg/installed/x64-windows/debug/bin -OutVariable out [G:\Cone\embree-3.13.5\build\CMakeFiles\CMakeScratch\TryCompile-txebo1\cmTC_e3112.vcxproj]
    G:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [G:\Cone\embree-3.13.5\build\CMakeFiles\CMakeScratch\TryCompile-txebo1\cmTC_e3112.vcxproj]
    G:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: :cmEnd [G:\Cone\embree-3.13.5\build\CMakeFiles\CMakeScratch\TryCompile-txebo1\cmTC_e3112.vcxproj]
    G:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [G:\Cone\embree-3.13.5\build\CMakeFiles\CMakeScratch\TryCompile-txebo1\cmTC_e3112.vcxproj]
    G:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: :cmErrorLevel [G:\Cone\embree-3.13.5\build\CMakeFiles\CMakeScratch\TryCompile-txebo1\cmTC_e3112.vcxproj]
    G:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: exit /b %1 [G:\Cone\embree-3.13.5\build\CMakeFiles\CMakeScratch\TryCompile-txebo1\cmTC_e3112.vcxproj]
    G:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: :cmDone [G:\Cone\embree-3.13.5\build\CMakeFiles\CMakeScratch\TryCompile-txebo1\cmTC_e3112.vcxproj]
    G:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [G:\Cone\embree-3.13.5\build\CMakeFiles\CMakeScratch\TryCompile-txebo1\cmTC_e3112.vcxproj]
    G:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: :VCEnd”已退出，代码为 -196608。 [G:\Cone\embree-3.13.5\build\CMakeFiles\CMakeScratch\TryCompile-txebo1\cmTC_e3112.vcxproj]
    已完成生成项目“G:\Cone\embree-3.13.5\build\CMakeFiles\CMakeScratch\TryCompile-txebo1\cmTC_e3112.vcxproj”(默认目标)的操作 - 失败。

    生成失败。

    “G:\Cone\embree-3.13.5\build\CMakeFiles\CMakeScratch\TryCompile-txebo1\cmTC_e3112.vcxproj”(默认目标) (1) ->
    (PostBuildEvent 目标) ->
      G:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: 命令“setlocal [G:\Cone\embree-3.13.5\build\CMakeFiles\CMakeScratch\TryCompile-txebo1\cmTC_e3112.vcxproj]
    G:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noprofile -executionpolicy Bypass -file G:/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary G:/Cone/embree-3.13.5/build/CMakeFiles/CMakeScratch/TryCompile-txebo1/Debug/cmTC_e3112.exe -installedDir G:/vcpkg/installed/x64-windows/debug/bin -OutVariable out [G:\Cone\embree-3.13.5\build\CMakeFiles\CMakeScratch\TryCompile-txebo1\cmTC_e3112.vcxproj]
    G:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [G:\Cone\embree-3.13.5\build\CMakeFiles\CMakeScratch\TryCompile-txebo1\cmTC_e3112.vcxproj]
    G:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: :cmEnd [G:\Cone\embree-3.13.5\build\CMakeFiles\CMakeScratch\TryCompile-txebo1\cmTC_e3112.vcxproj]
    G:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [G:\Cone\embree-3.13.5\build\CMakeFiles\CMakeScratch\TryCompile-txebo1\cmTC_e3112.vcxproj]
    G:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: :cmErrorLevel [G:\Cone\embree-3.13.5\build\CMakeFiles\CMakeScratch\TryCompile-txebo1\cmTC_e3112.vcxproj]
    G:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: exit /b %1 [G:\Cone\embree-3.13.5\build\CMakeFiles\CMakeScratch\TryCompile-txebo1\cmTC_e3112.vcxproj]
    G:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: :cmDone [G:\Cone\embree-3.13.5\build\CMakeFiles\CMakeScratch\TryCompile-txebo1\cmTC_e3112.vcxproj]
    G:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [G:\Cone\embree-3.13.5\build\CMakeFiles\CMakeScratch\TryCompile-txebo1\cmTC_e3112.vcxproj]
    G:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(160,5): error MSB3073: :VCEnd”已退出，代码为 -196608。 [G:\Cone\embree-3.13.5\build\CMakeFiles\CMakeScratch\TryCompile-txebo1\cmTC_e3112.vcxproj]

**Comment by RainbowTaro2022** [comment]
这是什么回事

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
