### ISSUE TITLE
Failures when vcpkg install gflags:x64-windows

### ISSUE THREAD

**Issue by PhoebeHui** [Microsoft/vcpkg#3149]
This issue found when I build Folly by VCPKG 'vcpkg install folly:x64-windows --head', it failed when build gflags.

Failures:
vcpkg install gflags:x64-windows
The following packages will be built and installed:
    gflags[core]:x64-windows
Starting package 1/1: gflags:x64-windows
Building package gflags[core]:x64-windows...
Unsupported toolchain combination x64

**Comment by ras0219-msft** [comment]
Thanks for posting this issue! I'm not able to reproduce it locally.

Could you let us know the results of:
```
>vcpkg version
Vcpkg package management program version 0.0.107

See LICENSE.txt for license information.
```

Also, are you running on a 32-bit OS and do you have VS 2013/2015/2017 installed?

**Comment by PhoebeHui** [comment]
I installed VS2017 and running on a 64 bit OS, also I use x64 compiler. But the VCPKG that I use is built on x86 mode, is that related? I will have a try.

**Comment by PhoebeHui** [comment]
I tried, still repro when I use VCPKG which build under x64 mode.

**Comment by PhoebeHui** [comment]
vcpkg version
Vcpkg package management program version 0.0.106

See LICENSE.txt for license information.

**Comment by PhoebeHui** [comment]
The issue has gone after I use latest VCPKG revision, but  boost-vcpkg-helpers:x64-windows failed currently. See

vcpkg install boost-vcpkg-helpers:x64-windows
The following packages will be built and installed:
    boost-vcpkg-helpers[core]:x64-windows
Starting package 1/1: boost-vcpkg-helpers:x64-windows
Building package boost-vcpkg-helpers[core]:x64-windows...
Unsupported toolchain combination x64

D:\Folly\vcpkg\src>vcpkg version
Vcpkg package management program version 0.0.107

See LICENSE.txt for license information.

D:\Folly\vcpkg\src>

**Comment by PhoebeHui** [comment]
Create https://github.com/Microsoft/vcpkg/issues/3199 to track the above issue, since the issue not repro on VCPKG latest revision, close this one.
