### ISSUE TITLE
Failure trying to add port for zstd

### ISSUE THREAD

**Issue by saulthu** [Microsoft/vcpkg#315]
Zstandard - Fast real-time compression algorithm http://www.zstd.net
https://github.com/facebook/zstd

I would submit a pull request but I cannot work out how to build via vcpkg. The `portfile.cmake` that I have made for zstd so far is:

```
include(vcpkg_common_functions)
set(SOURCE_PATH ${CURRENT_BUILDTREES_DIR}/src/zstd-1.1.1)
vcpkg_download_distfile(ARCHIVE
    URLS "https://github.com/facebook/zstd/archive/v1.1.1.zip"
    FILENAME "zstd-1.1.1.zip"
    SHA512 c96a97519202a759c62f661c7bbaeaa0d48e4e78588a8232ad23fd78fe7c3440f1f07d996dcf07daa652569e1c5e39cb7b93103b9ec7845db05b161ec29a8dde
)
vcpkg_extract_source_archive(${ARCHIVE})

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}/build/cmake
)

vcpkg_build_msbuild(
	PROJECT_PATH ALL_BUILD.vcxproj
	RELEASE_CONFIGURATION RelWithDebInfo
	DEBUG_CONFIGURATION Debug
)

vcpkg_install_cmake()
```

Opening `ALL_BUILD.vcxproj` in Visual Studio will build correctly, but running `.\vcpkg.exe build zstd` fails with error log containing:

```
[...]\zstd_common.c(15): fatal error C1083: Cannot open include file: 'stdlib.h': No such file or directory
```

**Comment by ras0219-msft** [comment]
Generally, you will want to use `vcpkg_build_cmake()` instead of `vcpkg_build_msbuild()`. I'm not sure how the ones you've used will interact, but it's definitely not a tested case.

**Comment by saulthu** [comment]
Brilliant, instant fix in seconds :smiley:  I'm a cmake noob, so thanks for the tip. I guess I copied the vcpkg_build_msbuild() command from another port.

Now the package stage fails with `package-x64-windows-rel-out.log`:

```
MSBUILD : error MSB1009: Project file does not exist.
Switch: install.vcxproj
```

I'll try to figure it out.

BTW, thanks so much for this tool, exactly what I've been wanting/needing :smiley:

**Comment by ras0219-msft** [comment]
This probably indicates that the library doesn't have install commands. Looking at the sources, it seems they've guarded all their installation functions behind an `if (UNIX)` :( [1].

One option is to patch the sources, but the easiest fix here is probably to replace the `vcpkg_install_cmake()` with explicit file copying commands that lay out the files correctly [2]. Here are a few examples that might be useful:
- https://github.com/Microsoft/vcpkg/blob/master/ports/boost/portfile.cmake#L123
- https://github.com/Microsoft/vcpkg/blob/master/ports/constexpr/portfile.cmake#L16
- https://github.com/Microsoft/vcpkg/blob/master/ports/sdl2/portfile.cmake#L19

[1] https://github.com/facebook/zstd/blob/dev/build/cmake/lib/CMakeLists.txt#L159
[2] https://cmake.org/cmake/help/v3.0/command/file.html

**Comment by saulthu** [comment]
Thanks for the help. The following portfile now works and I've tested in with a simple program in VS2015 and VS2017 RC -- both work seamlessly. Awesome! 😀

The [contrib guidelines](https://github.com/Microsoft/vcpkg/blob/master/CONTRIBUTING.md) recommend to "discuss whether the PR you're thinking about making will be acceptable". So, should I submit a PR for this package? I'm not certain of the quality, but it works to build debug and release on x64 in vs2015/2017.

```
include(vcpkg_common_functions)
set(SOURCE_PATH ${CURRENT_BUILDTREES_DIR}/src/zstd-1.1.1)
vcpkg_download_distfile(ARCHIVE
    URLS "https://github.com/facebook/zstd/archive/v1.1.1.zip"
    FILENAME "zstd-1.1.1.zip"
    SHA512 c96a97519202a759c62f661c7bbaeaa0d48e4e78588a8232ad23fd78fe7c3440f1f07d996dcf07daa652569e1c5e39cb7b93103b9ec7845db05b161ec29a8dde
)
vcpkg_extract_source_archive(${ARCHIVE})

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}/build/cmake
    OPTIONS -DZSTD_LEGACY_SUPPORT=1
)

vcpkg_build_cmake()

# Manual install since zstd guarded all their installation functions behind an if (UNIX)
message(STATUS "Installing")

file(COPY ${SOURCE_PATH}/lib/zstd.h DESTINATION ${CURRENT_PACKAGES_DIR}/include)

# Copy the command-line zstd exe
file(INSTALL ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/programs/Release/
    DESTINATION ${CURRENT_PACKAGES_DIR}/tools
    FILES_MATCHING PATTERN "zstd.exe")

if (VCPKG_LIBRARY_LINKAGE STREQUAL dynamic)
    # Dynamic libs of zstd appear to start with "zstdlib."
    file(INSTALL ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/lib/Release/
        DESTINATION ${CURRENT_PACKAGES_DIR}/lib
        FILES_MATCHING PATTERN "zstdlib.*.lib")
    file(INSTALL ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/lib/Release/
        DESTINATION ${CURRENT_PACKAGES_DIR}/bin
        FILES_MATCHING PATTERN "zstdlib.*.dll")
    file(INSTALL ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-dbg/lib/Debug/
        DESTINATION ${CURRENT_PACKAGES_DIR}/debug/lib
        FILES_MATCHING PATTERN "zstdlib.*.lib")
    file(INSTALL ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-dbg/lib/Debug/
        DESTINATION ${CURRENT_PACKAGES_DIR}/debug/bin
        FILES_MATCHING PATTERN "zstdlib.*.dll")
else()
    # Static libs of zstd appear to start with "zstdlib_"
    file(INSTALL ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/lib/Release/
        DESTINATION ${CURRENT_PACKAGES_DIR}/lib
        FILES_MATCHING PATTERN "zstdlib_*.lib")
    file(INSTALL ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-dbg/lib/Debug/
        DESTINATION ${CURRENT_PACKAGES_DIR}/debug/lib
        FILES_MATCHING PATTERN "zstdlib_*.lib")
endif()

# Handle copyright
file(COPY ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/zstd)
file(RENAME ${CURRENT_PACKAGES_DIR}/share/zstd/LICENSE ${CURRENT_PACKAGES_DIR}/share/zstd/copyright)

vcpkg_copy_pdbs()
message(STATUS "Installing done")
```

**Comment by Orvid** [comment]
The zstd CMake files also install `common/zbuff.h` `dictBuilder/zdict.h` as `includes/zbuff.h` and `includes/zdict.h` respectively.

**Comment by saulthu** [comment]
Thanks @Orvid for spotting that oversight, I have not used those headers. I've updated the portfile to contain two more lines

```
# ...
message(STATUS "Installing")

file(COPY ${SOURCE_PATH}/lib/zstd.h DESTINATION ${CURRENT_PACKAGES_DIR}/include)
file(COPY ${SOURCE_PATH}/lib/common/zbuff.h DESTINATION ${CURRENT_PACKAGES_DIR}/include)
file(COPY ${SOURCE_PATH}/lib/dictBuilder/zdict.h DESTINATION ${CURRENT_PACKAGES_DIR}/include)

# ...
```
