### ISSUE TITLE
[libiconv] Build error

### ISSUE THREAD

**Issue by nelsonrios** [microsoft/vcpkg#31508]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
vcpkg install libspatialite:x64-windows-static
```

### Failure logs

-- Configuring x64-windows-static-dbg
-- Configuring x64-windows-static-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: R:/dev/vcpkg/downloads/tools/msys2/ca907ea16f6f2ba5/usr/bin/bash.exe --noprofile --norc --debug -c "V=1 CPP='compile cl.exe -E' CC='compile cl.exe' CC_FOR_BUILD='compile cl.exe' CPP_FOR_BUILD='compile cl.exe -E' CXX_FOR_BUILD='compile cl.exe' CXX='compile cl.exe' RC='windres-rc rc.exe' WINDRES='windres-rc rc.exe' AR='ar-lib lib.exe' LD='link.exe -verbose' RANLIB=':' STRIP=':' NM='dumpbin.exe -symbols -headers' DLLTOOL='link.exe -verbose -dll' CCAS=':' AS=':' ./../src/v1.17-84a471678e.clean/configure --build=x86_64-pc-mingw32 \"--enable-extra-encodings\" \"--without-libiconv-prefix\" \"--without-libintl-prefix\" \"--enable-relocatable\" \"ac_cv_prog_ac_ct_STRIP=:\" \"gl_cv_double_slash_root=yes\" \"ac_cv_func_memmove=yes\" \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"--prefix=/R/dev/vcpkg/installed/x64-windows-static\" \"--bindir=\\${prefix}/tools/libiconv/bin\" \"--sbindir=\\${prefix}/tools/libiconv/sbin\" \"--libdir=\\${prefix}/lib\" \"--mandir=\\${prefix}/share/libiconv\" \"--docdir=\\${prefix}/share/libiconv\" \"--datarootdir=\\${prefix}/share/libiconv\""
    Working Directory: R:/dev/vcpkg/buildtrees/libiconv/x64-windows-static-rel
    Error code: 77
    See logs for more information:
      R:\dev\vcpkg\buildtrees\libiconv\config-x64-windows-static-rel-config.log
      R:\dev\vcpkg\buildtrees\libiconv\config-x64-windows-static-rel-out.log
      R:\dev\vcpkg\buildtrees\libiconv\config-x64-windows-static-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:829 (vcpkg_execute_required_process)
  ports/libiconv/portfile.cmake:29 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)

error: building libiconv:x64-windows-static failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libiconv
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libiconv]+Build+error
Include '[libiconv] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454
    vcpkg-scripts version: 524ddae8f 2023-05-18 (3 hours ago)

**Comment by JonLiu1993** [comment]
@nelsonrios, Thanks for posting this issue, please use command "git pull" get the latest vcpkg and try again.

**Comment by nelsonrios** [comment]
It now builds. Thanks!
