### ISSUE TITLE
[arrow:x64-windows-static] Arrow 12 issue with acero

### ISSUE THREAD

**Issue by davesworking** [microsoft/vcpkg#31505]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
.\vcpkg\vcpkg.exe install "arrow[core,csv,dataset,filesystem,json,parquet]" --triplet=x64-windows-static  --recurse
```

### Failure logs

CMake Error at C:/Program Files/CMake/share/cmake-3.24/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "FindArrowAcero.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "ArrowAcero", but CMake did not find one.

  Could not find a package configuration file provided by "ArrowAcero" with
  any of the following names:

    ArrowAceroConfig.cmake
    arrowacero-config.cmake

  Add the installation prefix of "ArrowAcero" to CMAKE_PREFIX_PATH or set
  "ArrowAcero_DIR" to a directory containing one of the above files.  If
  "ArrowAcero" provides a separate development package or SDK, be sure it has
  been installed.

### Additional context

is FindArrowAcero.cmake supposed to be generated?

**Comment by jimwang118** [comment]
Where did the `ArrowAcero `come from? There is no `ArrowAcero`in `arrow's` dependencies and features.
I run the command you provided and the result is normal.
![image](https://github.com/microsoft/vcpkg/assets/122244446/473bf660-4cfe-4608-90e5-8e12e6fe58cf)

**Comment by davesworking** [comment]
Arrow does build successfully but when we try and build the library into our product we see the error above.

**Comment by jimwang118** [comment]
> Arrow does build successfully but when we try and build the library into our product we see the error above.

How do you use it in your project? What is the error message?

**Comment by jimwang118** [comment]
> I have the same problem on Linux. ArrowAcero is a dependency of ArrowDataset (ArrowDatasetConfig.cmake calls `find_dependency(ArrowAcero)`) but in the vcpkg installation of Arrow there is no ArrowAceroConfig.cmake nor FindArrowAcero.cmake, hence the error.
> 
> I think this is a bug in the vcpkg port of Arrow 12 and ArrowAceroConfig.cmake should be included in the port.

Yes this is indeed a problem, it is caused by the `ArrowAceroConfig.cmake` file not being exported, I will fix it.
