### ISSUE TITLE
[opencv4>] build failure

### ISSUE THREAD

**Issue by leeyunhome** [microsoft/vcpkg#31514]
### Operating system

Linux

### Compiler

GCC

### Steps to reproduce the behavior

```Shell
./vcpkg install opencv4
```

### Failure logs

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/python3 /media/aiserver/data1/coding/github_repository/vcpkg/installed/x64-linux/tools/meson/meson.py -Dselinux=disabled -Dlibmount=disabled -Dgtk_doc=false -Dinstalled_tests=false -Dlibelf=disabled -Dman=false -Dtests=false -Dxattr=false --buildtype plain --backend ninja --wrap-mode nodownload --libdir lib --native /media/aiserver/data1/coding/github_repository/vcpkg/buildtrees/glib/meson-x64-linux-dbg.log -Ddebug=true --prefix /media/aiserver/data1/coding/github_repository/vcpkg/packages/glib_x64-linux/debug --includedir ../include -Dcmake_prefix_path=['/media/aiserver/data1/coding/github_repository/vcpkg/installed/x64-linux/debug','/media/aiserver/data1/coding/github_repository/vcpkg/installed/x64-linux'] /media/aiserver/data1/coding/github_repository/vcpkg/buildtrees/glib/src/glib-2-2f2db3ea41.clean
    Working Directory: /media/aiserver/data1/coding/github_repository/vcpkg/buildtrees/glib/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /media/aiserver/data1/coding/github_repository/vcpkg/buildtrees/glib/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:431 (vcpkg_execute_required_process)
  ports/glib/portfile.cmake:38 (vcpkg_configure_meson)
  scripts/ports.cmake:147 (include)

error: building glib:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+glib
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[glib]+Build+error&body=Copy+issue+body+from+%2Fmedia%2Faiserver%2Fdata1%2Fcoding%2Fgithub_repository%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

[config-x64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/11513605/config-x64-linux-dbg-err.log)

### Additional context

aiserver@aiserver-H110-D3:/media/aiserver/data1/coding/github_repository/vcpkg (master)$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0

Could you tell me how to install opencv4 (support CUDA 11.5).

Thank you.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue, the reason should be your Python3 version is lower, please try Python>=3.7.

**Comment by leeyunhome** [comment]
I don't know how to try Python >=3.7.

Could you tell me more detail?

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
