### ISSUE TITLE
[<port name>] build failure

### ISSUE THREAD

**Issue by itachi-gf** [microsoft/vcpkg#31516]
### Operating system

windows 11

### Steps to reproduce the behavior

```Shell
vcpkg>vcpkg install casacore:x86-windows lua:x86-windows fftw3:x86-windows boost:x86-windows lapack:x86-windows cfitsio:x86-windows gtkmm3:x86-windows
```

### Failure logs

Computing installation plan...
error: while looking for casacore:x86-windows:
error: while loading casacore:
error: casacore does not exist

**Comment by jimwang118** [comment]
`error: casacore does not exist`
There is no `casacore `port in `vcpkg`.

**Comment by jimwang118** [comment]
Do you still have problems installing and compiling now?

**Comment by PhoebeHui** [comment]
Hi @itachi-gf, vcpkg doesn't support casacore now, please open an new port issue with details or consider making a pull request.
