### ISSUE TITLE
SDL2-image build error

### ISSUE THREAD

**Issue by Wysepka** [microsoft/vcpkg#31511]
**Describe the bug**
So when trying to install SDL2-image package there is an error saying that vcpkg cant build the package.
Tried git pull, .\vcpkg update, .\vcpkg reintegrate install nothing helps

**Environment**
- OS: Windows 11
- Compiler: MS Visual Studio 2019

**To Reproduce**
1. ./vcpkg install sdl2-image:x64-windows
2. 
`Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+sdl2-image
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[sdl2-image]+Build+error&body=Copy+issue+body+from+C%3A%2Fdev%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md`

**Expected behavior**
It should build properly ? Not much changes in my computer since installing SDL2 like month ago
[DebugLogSDL2Image.txt](https://github.com/microsoft/vcpkg/files/11511822/DebugLogSDL2Image.txt)

**Failure logs**
-attached debug log is not full i think this is not neccesary, please correct me if wrong

**Additional context**
Maybe after updating sdl-image to the newest version you did not include SDL2main.lib name change in lowercase style ?
[install-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/11511816/install-x64-windows-dbg-err.log)

**Comment by Adela0814** [comment]
I'm not able to repro this in my side, my vcpkg version:
```
vcpkg package management program version 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895
```

**Comment by Wysepka** [comment]
vcpkg package management program version 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895

Mine is the same:

Try following repro on x64 architecture:
Install SDL2 core x86
Delete SDL2 core x86
Install SDL2 core x64
Install SDL2-image[core] x86 - then error

**Comment by Tapptastic** [comment]
For anyone else having this issue, the cause for me was a missing target for `SDL2main.lib` inside of the `manual-link` folder that should in your vcpkg install path.

**Comment by dg0yt** [comment]
> a missing target for `SDL2main.lib` inside of the `manual-link` folder

This doesn't seem related to the error message
~~~
ninja: error: FindFirstFileExA(c:/dev/vcpkg/installed/x64-windows/lib/manual-link/sdl2main.lib;c:/dev/vcpkg/installed/x64-windows/lib): The filename, directory name, or volume label syntax is incorrect.
~~~

**Comment by Tapptastic** [comment]
> > a missing target for `SDL2main.lib` inside of the `manual-link` folder
> 
> This doesn't seem related to the error message
> 
> ```
> ninja: error: FindFirstFileExA(c:/dev/vcpkg/installed/x64-windows/lib/manual-link/sdl2main.lib;c:/dev/vcpkg/installed/x64-windows/lib): The filename, directory name, or volume label syntax is incorrect.
> ```

You sure, from the error that you just pasted it is trying to find a file called `sdl2main.lib` inside of `x64-windows/lib/manual-link folder`
