### ISSUE TITLE
[boost-serialization] build failure

### ISSUE THREAD

**Issue by Abdalslam-Alromimah** [microsoft/vcpkg#31536]
### Operating system

windows 10

### Compiler

MSVC 2017

### Steps to reproduce the behavior

```Shell
vcpkg install boost:x64-windows
```

### Failure logs

CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: E:/dev/vcpkg/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: E:/dev/vcpkg/vcpkg/buildtrees/boost-serialization/x64-windows-dbg
    See logs for more information:
      E:\dev\vcpkg\vcpkg\buildtrees\boost-serialization\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:140 (vcpkg_cmake_install)
  ports/boost-serialization/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:147 (include)

error: building boost-serialization:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-serialization
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[boost-serialization]+Build+error&body=Copy+issue+body+from+E%3A%2Fdev%2Fvcpkg%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by LilyWangLL** [comment]
Please provide the error log: `E:\dev\vcpkg\vcpkg\buildtrees\boost-serialization\install-x64-windows-dbg-out.log`.

**Comment by LilyWangLL** [comment]
This issue can't reproduce on latest vcpkg.
```
.\vcpkg.exe install boost-serialization:x64-windows --binarysource=clear
Building boost-serialization[core]:x64-windows...
-- Downloading https://github.com/boostorg/serialization/archive/boost-1.82.0.tar.gz -> boostorg-serialization-boost-1.82.0.tar.gz...
-- Extracting source E:/Lily/0516/downloads/boostorg-serialization-boost-1.82.0.tar.gz
-- Using source at E:/Lily/0516/buildtrees/boost-serialization/src/ost-1.82.0-841a4be867.clean
......
Elapsed time to handle boost-serialization:x64-windows: 32 s
Total install time: 5.1 min
The package boost is compatible with built-in CMake targets:

    find_package(Boost REQUIRED [COMPONENTS <libs>...])
    target_link_libraries(main PRIVATE Boost::boost Boost::<lib1> Boost::<lib2> ...)

PS E:\Lily\0516> .\vcpkg.exe --version
vcpkg package management program version 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895

See LICENSE.txt for license information.
```

**Comment by LilyWangLL** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.

**Comment by Abdalslam-Alromimah** [comment]
Hello LIlyWangLL,

The issue does not solve by use follow command :
\vcpkg.exe install boost-serialization:x64-windows --binarysource=clear


Thanks.

**Comment by Abdalslam-Alromimah** [comment]
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/11612699/install-x64-windows-dbg-out.log)

**Comment by LilyWangLL** [comment]
```
CreateProcessA() Windows API failed: 225 - Operation did not complete successfully because the file contains a virus or potentially unwanted software.
```
There are the above error message in your log. It due to `b2.exe` is treated as a virus by anti-virus software. Duplicated to https://github.com/microsoft/vcpkg/issues/13353.
