### ISSUE TITLE
PayPal: إرسال مدفوعات

### ISSUE THREAD

**Issue by Xx111xxx** [microsoft/vcpkg#31556]
https://www.paypal.com/myaccount/transfer/homepage

**Comment by MonicaLiu0311** [comment]
Hi, I don't know what your issue is, please see #30604 for how to report a issue.

**Comment by Neumann-A** [comment]
@MonicaLiu0311 This is simply spam. I don't understand why you did not simply close it and reported the user.

**Comment by MonicaLiu0311** [comment]
This issue will be closed soon, if you have problems please re-report as #30604.
