### ISSUE TITLE
[podofo] update to 0.10.0

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#31578]
### Library name

podofo

### New version number

0.10.0

### Other information that may be useful (release notes, etc...)

current version 0.9.8
0.10.0 is not compatible with 0.9.8

**Comment by FrankXie05** [comment]
@playgithub Currently `podofo` has two sources, one is [`sourceforge`](https://podofo.sourceforge.net/download.html) and the other is [`Github`](https://github.com/podofo/podofo). 
Only `Github` has been updated to version `0.10.0`, and `vcpkg` currently uses `sourceforge`. 
https://github.com/microsoft/vcpkg/blob/0ccb3d11406922bef1dcc29002f68f633a321f19/ports/podofo/portfile.cmake#L7
Is `giehub` official? Is there any difference between these two?

**Comment by playgithub** [comment]
It says
```
Development of PoDoFo has been moved to GitHub: https://github.com/podofo/podofo
```
at https://sourceforge.net/projects/podofo/

**Comment by FrankXie05** [comment]
@playgithub Thanks, I will transfer `podofo` to `vcpkg_from_github`. :)

**Comment by playgithub** [comment]
Thanks

BTW, it might break many applications that depend on 0.9.x, because the API in 0.10.0 changes a lot.

**Comment by FrankXie05** [comment]
@playgithub I'll submit a PR to see if we can fix these dependencies.

**Comment by FrankXie05** [comment]
All right, thanks for your answer. :)
A small question: should we stop updating this port due to downstream dependencies.
Can you clarify which applications depend on 0.9 and consider whether it can be migrated? 🫤

**Comment by playgithub** [comment]
> A small question: should we stop updating this port due to downstream dependencies.

I'm going to use podojo, but not yet, so my choice is to update it.

> Can you clarify which applications depend on 0.9 and consider whether it can be migrated?

I think almost every application thtat depend on 0.9 will fail to build with 0.10.0

https://github.com/podofo/podofo/releases
```
The release is complete re-imagination of PoDoFo 0.9.x API in C++17, and it's API/ABI incompatible with the previous releases.
```

**Comment by FrankXie05** [comment]
@playgithub In order to ensure the `api` problem, I will ask the upstream whether the api will be fixed in the future. If the migration of the api is something that must be done, the downstream must also make changes.  🫤
https://github.com/podofo/podofo/wiki/PoDoFo-API-migration-guide/#098---0100

**Comment by FrankXie05** [comment]
Reopen this issue for update.

**Comment by playgithub** [comment]
Fine
