### ISSUE TITLE
[pango] build failure

### ISSUE THREAD

**Issue by Beafantles** [microsoft/vcpkg#31573]
### Operating system

Linux

### Compiler

GCC

### Steps to reproduce the behavior

```Shell
`./vcpkg install pango`
```

### Failure logs

`/home/beafantles/src/vcpkg/buildtrees/pango/package-x64-linux-rel-out.log`:
[package-x64-linux-rel-out.log](https://github.com/microsoft/vcpkg/files/11537486/package-x64-linux-rel-out.log)

### Additional context

`/usr/bin/cc --version` is `cc (GCC) 13.1.1 20230429`
`ninja --version` is `1.11.1`

**Comment by LilyWangLL** [comment]
This is an upstream issue, this error occurs when compiling `Pango` 1.50.14 with gcc13. The related upstream link: https://gitlab.gnome.org/GNOME/pango/-/issues/740

**Comment by Beafantles** [comment]
Ok, thank you!
