### ISSUE TITLE
[New Port Request] tcmalloc

### ISSUE THREAD

**Issue by Nosenzor** [microsoft/vcpkg#31593]
### Library name

tcmalloc

### Library description

TCMalloc is Google's customized implementation of C's malloc() and C++'s operator new used for memory allocation within our C and C++ code. TCMalloc is a fast, multi-threaded malloc implementation.

### Source repository URL

https://github.com/google/tcmalloc

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

It seems that some attempt to create this port have done already some years ago (https://github.com/microsoft/vcpkg/issues/4353 , https://github.com/microsoft/vcpkg/issues/3536) but I can't see the port listed.

This PR https://github.com/google/tcmalloc/pull/104 can be interesting to replace Bazel build with Cmake.

**Comment by Polepoint** [comment]
same reqeust

**Comment by zhouniandi** [comment]
same reqeust

**Comment by sfhacker** [comment]
This is over a year old!
