### ISSUE TITLE
[qt] Allow building without thirdparty libs by using features

### ISSUE THREAD

**Issue by jpfeuffer** [microsoft/vcpkg#31590]
### Is your feature request related to a problem? Please describe.

I don't need zlib, libpng, pcre.. whatever features. I just want the most basic QtCore. Please let me disable it in the port.
https://doc.qt.io/qt-5/configure-options.html#third-party-libraries
https://github.com/microsoft/vcpkg/blob/master/ports/qt5-base/portfile.cmake#L95

### Proposed solution

Use a feature for each thirdparty library.

**Comment by Osyotr** [comment]
Do you want to completely disable them or to use bundled versions? The former is achievable, but nobody cared to implement it. The latter is not possible until options are implemented.
Either way you can create an overlay port and pass `-no-...` instead of `-system-...`.

**Comment by jpfeuffer** [comment]
Correct. Completely disable. I agree that using the internal libraries is not the right approach for a pkg manager like vcpkg.
Yes I might override the recipe for the time being.

**Comment by jimwang118** [comment]
If you implement the functionality you want to use by overriding the port, please let me know and I will close this issue at that time.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
