### ISSUE TITLE
Git subtree (instead of git submodule) prevents the override mechanism from working.

### ISSUE THREAD

**Issue by photex** [microsoft/vcpkg#31598]
I thought I would be clever and use git subtree instead of git submodule. Things seemed to work fine right up until I needed to override the OpenSSL version (I need 1.1.1t and not 3.x).

**Environment**
- OS: MacOS
- Compiler: clang-16

**To Reproduce**
1. Setup a test repo to use manifest mode.
2. Include vcpkg as a subtree instead of a submodule 
3. Try to override a dependency

**Expected behavior**
I thought things would just magically work I guess, I didn't really understand how this mechanism actually functioned though.

**Failure logs**
```
-- Running vcpkg install
error: while checking out baseline from commit '879710ab02723140ea45abcf2ce6890c6ad371b0', failed to `git show` versions/baseline.json. This may be fixed by fetching commits with `git fetch`.
error: git failed with exit code: (128).
fatal: not a git repository: '/Users/photex/workspaces/personal/spectre/third_party/vcpkg/.git'

Failed to determine the current commit:
error: git failed with exit code: (128).
fatal: not a git repository: '/Users/photex/workspaces/personal/spectre/third_party/vcpkg/.git'

-- Running vcpkg install - failed
```

**Additional context**
I don't think this is a bug with vcpkg. Perhaps just a bug for the documentation?

**Comment by autoantwort** [comment]
Versioning needs the full git history of the vcpkg repo :)
