### ISSUE TITLE
[libtorch] update to <2.0.1>

### ISSUE THREAD

**Issue by WangHHY19931001** [microsoft/vcpkg#31601]
### Library name

libtorch

### New version number

2.0.1

### Other information that may be useful (release notes, etc...)

https://pytorch.org/get-started/locally/

**Comment by russelltg** [comment]
Related to #30224

**Comment by LilyWangLL** [comment]
Closed as duplicate of #30224.

**Comment by WangHHY19931001** [comment]
can u push a plat for this?
