### ISSUE TITLE
[upb] build failure

### ISSUE THREAD

**Issue by EntiumZ** [microsoft/vcpkg#31620]
### Operating system

Windows 10 19045.2846

### Compiler

MSVC 19.36.32532.0
vcpkg-tool version: 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895
    vcpkg-scripts version: 357604e84 2023-05-24 (7 hours ago)

### Steps to reproduce the behavior

```Shell
vcpkg install upb:x64-windows
```

### Failure logs

D:\work\Garage\vcpkg>vcpkg install upb:x64-windows
Computing installation plan...
The following packages will be built and installed:
    upb[codegen,core]:x64-windows -> 2022-06-21
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\Oak\AppData\Local\vcpkg\archives in 277 us. Use --debug to see more details.
Installing 1/1 upb:x64-windows...
Building upb[codegen,core]:x64-windows...
-- Note: upb only supports static library linkage. Building static library.
-- Using cached protocolbuffers-upb-e4635f223e7d36dfbea3b722a4ca4807a7e882e2.tar.gz.
-- Extracting source D:/work/Garage/vcpkg/downloads/protocolbuffers-upb-e4635f223e7d36dfbea3b722a4ca4807a7e882e2.tar.gz
-- Applying patch 0001-make-cmakelists-py.patch
-- Applying patch 0002-fix-uwp.patch
-- Using source at D:/work/Garage/vcpkg/buildtrees/upb/src/07a7e882e2-67ea24d098.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
    Working Directory: D:/work/Garage/vcpkg/buildtrees/upb/x64-windows-dbg
    See logs for more information:
      D:\work\Garage\vcpkg\buildtrees\upb\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/upb/portfile.cmake:39 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building upb:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+upb
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[upb]+Build+error&body=Copy+issue+body+from+D%3A%2Fwork%2FGarage%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

<b>install-x64-windows-dbg-out.log detail:</b>
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/11560780/install-x64-windows-dbg-out.log)

**Comment by Adela0814** [comment]
`--upb_out: protoc-gen-upb: Plugin failed with status code 3221225785.`
DEC: 3221225785 <-> HEX: C000 0139
0xC0000139 error message: The dependency dll not found.

`protoc-gen-up.exe` requires the following dlls:
```
    libprotoc.dll
    abseil_dll.dll
    libprotobuf.dll
    MSVCP140.dll
    VCRUNTIME140.dll
    VCRUNTIME140_1.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-utility-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-locale-l1-1-0.dll
    KERNEL32.dll
```
Please check and install Windows SDK 10 using Visual Studio Installer or the official installer.

**Comment by EntiumZ** [comment]
> 

Thank you so much!

**Comment by EntiumZ** [comment]
I searched those dlls in my system and here is what I found:
    abseil_dll.dll ---------- This dll comes from the package abseil, which has been installed by vcpkg.
    libprotoc.dll
    libprotobuf.dll ---------- These 2 dlls come from protobuf, which have been installed by vcpkg.
    MSVCP140.dll
    VCRUNTIME140.dll
    VCRUNTIME140_1.dll ---------- These 3 dlls are located in ...\\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64\
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-utility-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-locale-l1-1-0.dll ---------- These dll are available under C:\Windows\SysWOW64
    KERNEL32.dll ---------- available in the system.

All related folders have been added to PATH.
I also installed MSVC v140, v141, v142 just in case. In addition, I installed Windows 10 SDK, 10.0.15063.0, 10.0.16299.0, 10.0.17134.0,  10.0.17763.0, 10.0.18362.0, 10.0.19041.0, 10.0.20348.0. All installation were done through Visual Studio Installer. However, I still got failed message from upb building. 
The error message is almost the same:
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/11568683/install-x64-windows-dbg-out.log)

I am wondering if there is any method to check the particular denpendency dll of particular version missing?
Thanks!

**Comment by Adela0814** [comment]
Can you please run the following command and provide the output?

Using Visual Studio Developer Command Prompt:
```
cd C:\vcpkg\packages\upb_x64-windows\tools\upb\
dumpbin /DEPENDENTS protoc-gen-upb.exe
```

**Comment by EntiumZ** [comment]
It is so strange that I don't have the "tools" folder under \\vcpkg\packages\upb_x64-windows\tools\upb\
Here is the details:

D:\work\Garage\vcpkg\packages\upb_x64-windows>dir
 Volume in drive D has no label.
 Volume Serial Number is C4BB-CB79

 Directory of D:\work\Garage\vcpkg\packages\upb_x64-windows

05/30/2023  11:00 AM    <DIR>          .
05/30/2023  11:00 AM    <DIR>          ..
05/30/2023  11:00 AM    <DIR>          share
               0 File(s)              0 bytes
               3 Dir(s)  381,377,572,864 bytes free
I only found protoc-gen-upb.exe under \\vcpkg\buildtrees\upb\x64-windows-dbg

D:\work\Garage\vcpkg\buildtrees\upb\x64-windows-dbg>dumpbin /DEPENDENTS protoc-gen-upb.exe
Microsoft (R) COFF/PE Dumper Version 14.36.32532.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file protoc-gen-upb.exe

File Type: EXECUTABLE IMAGE

  Image has the following dependencies:

    libprotocd.dll
    abseil_dll.dll
    libprotobufd.dll
    MSVCP140D.dll
    VCRUNTIME140D.dll
    VCRUNTIME140_1D.dll
    ucrtbased.dll
    KERNEL32.dll

  Summary

        1000 .00cfg
        4000 .data
        5000 .idata
        8000 .pdata
       1D000 .rdata
        1000 .reloc
        1000 .rsrc
       5D000 .text

**Comment by dg0yt** [comment]
Don't look at the `packages` folder, it is a staging area. The real thing is in `installed/<triplet>`.

**Comment by EntiumZ** [comment]
I didn't see the folder you mentioned.

D:\work\Garage\vcpkg\installed>dir /a
 Volume in drive D has no label.
 Volume Serial Number is C4BB-CB79

 Directory of D:\work\Garage\vcpkg\installed

05/24/2023  07:21 PM    /<DIR/>          .
05/24/2023  07:21 PM    /<DIR/>          ..
05/25/2023  09:44 AM    /<DIR/>          vcpkg
05/24/2023  07:41 PM    /<DIR/>          x64-windows
               0 File(s)              0 bytes
               4 Dir(s)  381,379,592,192 bytes free

**Comment by dg0yt** [comment]
So your triplet is x64-windows, and you should look into `installed\x64-windows`.

**Comment by EntiumZ** [comment]
Thanks for the guidance. I did a search, there is no "protoc-gen-upb.exe" in any folders under installed\x64-windows or any sub folders.

**Comment by dg0yt** [comment]
The error is in attempt to use `protoc-gen-upbdefs.exe` immediately after its generation. This might be an anti-virus issue.

**Comment by EntiumZ** [comment]
I don't have any anti-virus software running, including the Windows Defender Advanced Threat Protection Service. Windows Defender Firewall is running, is this related?
