### ISSUE TITLE
Qwt is no more available fot Qt 5

### ISSUE THREAD

**Issue by embeddedmz** [microsoft/vcpkg#31625]
**Describe the bug**
Qwt is no longer available fot Qt 5

**Environment**
- OS: Win 10

**To Reproduce**
1. ./vcpkg install qwt
2. If you don't have Qt 6, it will install it

**Expected behavior**
A version that can be compiled with Qt 5

**Comment by embeddedmz** [comment]
I have a link error when I use Qwt with a Qt 5 application.

**Comment by jimwang118** [comment]
> I have a link error when I use Qwt with a Qt 5 application. I have successfully built the application with vcpkg in the past.
> 
> > 1>Ui.lib(ValveDiagnosticWidgetItem.obj) : error LNK2019: symbole externe non résolu "__declspec(dllimport) public: void __cdecl QwtPlotCurve::setSamples(class QVector const &,class QVector const &)" (__imp_?setSamples@QwtPlotCurve@@QEAAXAEBV?$QVector@N@@0@Z) référencé dans la fonction "public: void __cdecl ValveDiagnosticWidgetItem::setPlotData(struct DiagnosisDataItem const &)" (?setPlotData@ValveDiagnosticWidgetItem@@QEAAXAEBUDiagnosisDataItem@@@z)
> > 1>D:\DevBuilds\PH66\Debug\ph66-tester.exe : fatal error LNK1120: 1 externes non résolus
> 
> These libraries are built with Qt 6 : D:\vcpkg\installed\x64-windows\debug\lib\qwtd.lib D:\vcpkg\installed\x64-windows\lib\qwt.lib D:\vcpkg\installed\x64-windows\debug\bin\qwtd.dll D:\vcpkg\installed\x64-windows\bin\qwt.dll

`qwt` compilation depends on `qtbase`. In the past,` qtbase` used `QT5`, but now `qtbase `uses `QT6`, so when you install and compile `qwt`, it will automatically install the `QT6 `library. So you used to compile successfully with `QT5`, but now you need to use `QT6`.

**Comment by dg0yt** [comment]
You don't have to use Qt6, but you must either go back to qwt 6.2.0#2 (i.e. use manifest mode), or you must provide your own variant as an overlay port or via registries.

**Comment by embeddedmz** [comment]
@dg0yt how can I do that ?

**Comment by jimwang118** [comment]
> @dg0yt how can I do that ?

You can refer to this [example](https://github.com/microsoft/vcpkg-docs/blob/2c24d3143de56a6f26864062ba00380c7040ba82/vcpkg/users/manifests.md#manifest-mode).

**Comment by jimwang118** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
