### ISSUE TITLE
[icu] build failure on Linux and Mac

### ISSUE THREAD

**Issue by davesworking** [microsoft/vcpkg#31636]
### Operating system

Mac

### Compiler

clang

### Steps to reproduce the behavior

```Shell
./vcpkg install xerces-c[icu]

(Windows builds successfully)
```

### Failure logs

**config-x64-osx-dbg-err.log**
configure: WARNING: unrecognized options: --disable-silent-rules
configure: error: 'autoconf-archive' is missing

**config-x64-osx-dbg-config.log**
uname -m = x86_64
uname -r = 21.6.0
uname -s = Darwin
uname -v = Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64
...
configure:4483: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -c -fPIC -mmacosx-version-min=10.15 -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk conftest.cpp >&5
conftest.cpp:55:3: error: "Compiler does not advertise C++11 conformance"
# error "Compiler does not advertise C++11 conformance"
  ^
conftest.cpp:60:3: error: unknown type name 'constexpr'
  constexpr int get_val() { return 20; }
  ^
conftest.cpp:72:17: error: delegating constructors are permitted only in C++11
    delegate(): delegate(2354) {}
                ^~~~~~~~
conftest.cpp:83:26: warning: 'override' keyword is a C++11 extension [-Wc++11-extensions]
    virtual int getval() override final { return this->n * 2; }
                         ^
conftest.cpp:83:35: warning: 'final' keyword is a C++11 extension [-Wc++11-extensions]
    virtual int getval() override final { return this->n * 2; }
                                  ^
conftest.cpp:90:16: warning: defaulted function definitions are a C++11 extension [-Wc++11-extensions]
    nocopy() = default;
               ^
conftest.cpp:91:29: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
    nocopy(const nocopy&) = delete;
                            ^
conftest.cpp:92:41: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
    nocopy & operator=(const nocopy&) = delete;
                                        ^
conftest.cpp:104:25: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  template <typename V> auto sum(V first) -> V
                        ^
conftest.cpp:104:25: error: 'auto' not allowed in function return type
  template <typename V> auto sum(V first) -> V
                        ^~~~
conftest.cpp:104:42: error: expected ';' at end of declaration
  template <typename V> auto sum(V first) -> V
                                         ^
                                         ;
conftest.cpp:104:43: error: cannot use arrow operator on a type
  template <typename V> auto sum(V first) -> V
                                          ^
conftest.cpp:108:33: warning: variadic templates are a C++11 extension [-Wc++11-extensions]
  template <typename V, typename... Args> auto sum(V first, Args... rest) -> V
                                ^
conftest.cpp:108:43: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  template <typename V, typename... Args> auto sum(V first, Args... rest) -> V
                                          ^
conftest.cpp:108:43: error: 'auto' not allowed in function return type
  template <typename V, typename... Args> auto sum(V first, Args... rest) -> V
                                          ^~~~
conftest.cpp:108:74: error: expected ';' at end of declaration
  template <typename V, typename... Args> auto sum(V first, Args... rest) -> V
                                                                         ^
                                                                         ;
conftest.cpp:108:75: error: cannot use arrow operator on a type
  template <typename V, typename... Args> auto sum(V first, Args... rest) -> V
                                                                          ^
conftest.cpp:132:3: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  auto a1 = 6538;
  ^
conftest.cpp:133:3: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  auto a2 = 48573953.4;
  ^
conftest.cpp:134:3: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  auto a3 = "String literal";
  ^
conftest.cpp:137:8: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  for (auto i = a3; *i; ++i) { total += *i; }
       ^
conftest.cpp:153:8: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  for (auto &x : array) { x += 23; }
       ^
conftest.cpp:153:16: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
  for (auto &x : array) { x += 23; }
               ^
conftest.cpp:158:17: error: expected expression
  assert (eval ([](int x) { return x*2; }, 21) == 42);
                ^
conftest.cpp:160:17: error: expected expression
  assert (eval ([&](double x) { return d += x; }, 3.0) == 5.0);
                ^
conftest.cpp:162:17: error: expected expression
  assert (eval ([=](double x) mutable { return d += x; }, 4.0) == 9.0);
                ^
conftest.cpp:168:3: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  auto a = sum(1);
  ^
conftest.cpp:168:12: error: no matching function for call to 'sum'
  auto a = sum(1);
           ^~~
conftest.cpp:169:3: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  auto b = sum(1, 2);
  ^
conftest.cpp:169:12: error: no matching function for call to 'sum'
  auto b = sum(1, 2);
           ^~~
conftest.cpp:170:3: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  auto c = sum(1.0, 2.0, 3.0);
  ^
conftest.cpp:170:12: error: no matching function for call to 'sum'
  auto c = sum(1.0, 2.0, 3.0);
           ^~~
conftest.cpp:175:25: warning: empty parentheses interpreted as a function declaration [-Wvexing-parse]
  cxx11test::delegate d2();
                        ^~
conftest.cpp:175:25: note: remove parentheses to declare a variable
  cxx11test::delegate d2();
                        ^~
conftest.cpp:188:16: error: found '<::' after a template name which forms the digraph '<:' (aka '[') and a ':', did you mean '< ::'?
  test_template<::test_template<int>> v(test_template<int>(12));
               ^~~
               < ::
conftest.cpp:188:36: error: a space is required between consecutive right angle brackets (use '> >')
  test_template<::test_template<int>> v(test_template<int>(12));
                                   ^~
                                   > >
conftest.cpp:192:22: error: use of undeclared identifier 'u8'
  char const *utf8 = u8"UTF-8 string \u2500";
                     ^
conftest.cpp:192:24: error: expected ';' at end of declaration
  char const *utf8 = u8"UTF-8 string \u2500";
                       ^
                       ;
fatal error: too many errors emitted, stopping now [-ferror-limit=]
18 warnings and 20 errors generated.

### Additional context

remove the icu feature from the command line allows xerces-c to build correctly

**Comment by dg0yt** [comment]
~~~
configure: error: 'autoconf-archive' is missing
~~~

**Comment by Adela0814** [comment]
Dup to https://github.com/microsoft/vcpkg/issues/24870
