### ISSUE TITLE
[opencv4[cuda]] build failure

### ISSUE THREAD

**Issue by Data-Adventure** [microsoft/vcpkg#31632]
### Operating system

ubuntu22.04

### Compiler

gnu

### Steps to reproduce the behavior

```Shell
vcpkg install "opencv4[cuda]:x64-linux" --recurse
```

### Failure logs

<img width="1274" alt="image" src="https://github.com/microsoft/vcpkg/assets/83524608/411db367-b616-4813-9289-d1c747b102f7">

[config-x64-linux-dbg-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/11566035/config-x64-linux-dbg-CMakeCache.txt.log)
[config-x64-linux-out.log](https://github.com/microsoft/vcpkg/files/11566036/config-x64-linux-out.log)
[config-x64-linux-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/11566037/config-x64-linux-rel-CMakeCache.txt.log)

**Comment by nightvoyager-xxs** [comment]
In fact, I think the problem is this, but I don't know how to solve it through VCPKG
<img width="974" alt="image" src="https://github.com/microsoft/vcpkg/assets/83524608/d1d0f6e1-12d9-4a15-a1dc-18d0028f2a79">

**Comment by MonicaLiu0311** [comment]
Will verify as soon as possible.

**Comment by MonicaLiu0311** [comment]
* x64-linux
* Ubuntu 22.04
* Vcpkg version:
    ```
    root@monica003:/home/monica/vcpkg# ./vcpkg version
    vcpkg package management program version 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895
    ```

Sorry I didn't repro your issue.

```
root@monica003:/home/monica/vcpkg# ./vcpkg install "opencv4[cuda]:x64-linux" --recurse --binarysource=clear
Computing installation plan...
The following packages will be built and installed:
    opencv4[contrib,core,cuda,default-features,dnn,gtk,jpeg,png,quirc,tiff,webp]:x64-linux -> 4.7.0#6

...

-- Configuring x64-linux
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Performing post-build validation
Stored binaries in 0 destinations.
Elapsed time to handle opencv4:x64-linux: 2.8 h
Total install time: 2.8 h
If you do not install the meta-port *opencv*, the package opencv4 is compatible with CMake
if you set the OpenCV_DIR *before* the find_package call

    set(OpenCV_DIR "${VCPKG_INSTALLED_DIR}/x64-linux/share/opencv4")
    find_package(OpenCV REQUIRED)
```

**Comment by MonicaLiu0311** [comment]
Are you using the latest version of vcpkg?

refer to: 
https://github.com/microsoft/vcpkg/issues/7913#issuecomment-525040221
https://github.com/opencv/opencv/issues/16460

**Comment by Data-Adventure** [comment]
I used the latest vcpkg
`vcpkg package management program version 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895`
in my ubuntu, i have 
`Cuda compilation tools, release 12.1, V12.1.105`
cuda-12.1 cuda-12.0
i'm  using cuda-12.1 in my .zshrc.
but my nvidia-smi shows my cuda version is 12.0 which i install it through ubuntu driver

**Comment by MonicaLiu0311** [comment]
Multiple cuda versions can be installed, I also have 12.0 and 12.1.

Please try the following command to check if your `.zshrc` is valid:
```
root@monica003:/home/monica# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
```

**Comment by Data-Adventure** [comment]
emmmmm......
```
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
```

**Comment by FrankXie05** [comment]
@Data-Adventure 
For the special processing we do with [`cuda`](https://github.com/microsoft/vcpkg/blob/1c5a340f6e10985e2d92af174a68dbd15c1fa4e1/ports/opencv2/0005-fix-cuda.patch#L79), please make sure that you have checked the installation of the library during the manual installation of `cuda`.
```
//"cufft" library
CUDA_cufft_LIBRARY:FILEPATH=CUDA_cufft_LIBRARY-NOTFOUND

//"cupti" library
CUDA_cupti_LIBRARY:FILEPATH=CUDA_cupti_LIBRARY-NOTFOUND

//"curand" library
CUDA_curand_LIBRARY:FILEPATH=CUDA_curand_LIBRARY-NOTFOUND

//"cusolver" library
CUDA_cusolver_LIBRARY:FILEPATH=CUDA_cusolver_LIBRARY-NOTFOUND
...
...
```

**Comment by Data-Adventure** [comment]
thank you all, i reinstall cuda, it's work !
