### ISSUE TITLE
There should be a better way to download vcpkg-tool for offline development environments

### ISSUE THREAD

**Issue by sweemer** [microsoft/vcpkg#31641]
I understand that vcpkg itself is not really designed for offline development environments because it downloads packages from the internet, but if necessary it can be made to work in an offline development environment by setting up the binary cache in a remote source that the offline development environment has access to, and then push to that remote source from an internet-connected machine.

However, there is one problem with this approach, which is that the offline development environment still needs to access the internet in order to download `vcpkg-tool` during bootstrapping. Currently the location of `vcpkg-tool` is [hardcoded](https://github.com/microsoft/vcpkg/blob/c6592ce60ff394049905365865f59e3a4d93d35b/scripts/bootstrap.sh#L197) in the bootstrap script and is not configurable in any way as far as I can tell.

I can think of the following potential solutions to resolve this issue:

1. Clone the `vcpkg` and `vcpkg-tool` repositories to an internal git server and modify `bootstrap.sh` to point to that address instead of github.com.
2. Add back a way to build the `vcpkg` executable from source, like there used to be a few years ago.
3. Add a new environment variable called `VCPKG_TOOL_URL` or `VCPKG_TOOL_PATH` or something like that to tell `bootstrap.sh` where to pull `vcpkg-tool` from.
4. Somehow upload the `vcpkg` executable itself to the remote source as part of the binary caching step, and retrieve from the CMake toolchain file as the first step of the offline bootstrapping process.
5. Something else?

Which is these is the best solution to the problem, and what would be the timeline for implementing it?

**Comment by FrankXie05** [comment]
cc @BillyONeal

**Comment by BillyONeal** [comment]
All the bootstrap script does is download an appropriate exe. All the solutions you describe sound vastly more complicated than simply arranging for the appropriate exes to be copied into the right place in your air gapped environment?

> 2. Add back a way to build the vcpkg executable from source, like there used to be a few years ago.

That doesn't fix the download problem because you would have to download the sources. Notably, bootstrap *does* have a way to build from source we use when we can't detect that one of the binaries will work, but it needs to download a source tarball, so it doesn't fix your problem.

**Comment by sweemer** [comment]
The solutions I propose may be more complicated than copying files by hand, but that's equivalent to saying that vcpkg itself is more complicated than managing project dependencies by hand. Isn't the whole point of vcpkg to make dependency management less manual? If I have to manage everything by myself then why use vcpkg at all? That's why I proposed some solutions that will get an offline development environment up and running right after cloning a repo containing vcpkg as a submodule with no manual steps or custom images required.

To clarify my point about building from source, the idea was that I would make vcpkg-tool another submodule of my project, and build it as part of the vcpkg bootstrapping. It's not a problem for me to clone source code into my offline git server, but it's a problem when repos try to access the internet from my clone. 

Now that I've hopefully explained my constraints a bit better, could you take another look at my proposed solutions and see what can be done to adopt at least one of them?

**Comment by Trider12** [comment]
@sweemer I don't get your point.
> the idea was that I would make vcpkg-tool another submodule of my project, and build it as part of the vcpkg bootstrapping. It's not a problem for me to clone source code into my offline git server

What's stopping you from doing that? I.e. something like this in a script:
```
git clone https://yourserverurl/vcpkg
git clone https://yourserverurl/vcpkg-tool
cmake -Svcpkg-tool -Bvcpkg-tool/build -DCMAKE_BUILD_TYPE=Release
cmake --build vcpkg-tool/build
cp vcpkg-tool/build/vcpkg vcpkg/vcpkg
```

**Comment by sweemer** [comment]
> as part of the vcpkg bootstrapping.

@Trider12 You may have missed or skimmed over this part of my point.

Nothing is stopping me from running that script, but nothing is making is run as part of the vcpkg bootstrapping.

The vcpkg bootstrapping process knows how to retrieve the vcpkg executable from the internet during bootstrapping but why is internet access a prerequisite for bootstrapping out of the box? More integrated support for offline bootstrapping would be immensely valuable in my work, which unfortunately is constrained to an offline development environment.

**Comment by Trider12** [comment]
> You may have missed or skimmed over this part of my point.

I didn't. I mean that if you already have to call the vcpkg bootstrap script, why not just call another script instead? The bootstrap script does nothing but download the binary. 

Even if you call the bootstrap script indirectly via a `vcpkg.cmake` toolchain file passed to CMake, you can just override this toolchain. At the end of day you still have to pass a toolchain file to CMake, so what difference does it make what toolchain that is?

**Comment by sweemer** [comment]
> if you already have to call the vcpkg bootstrap script

I don't call it directly - as you have correctly guessed, I'm passing the vcpkg toolchain file to my CMake build, and the toolchain drives the bootstrapping, building, and installing.

> you can just override this toolchain

That's exactly right, and that's what this issue is all about. If I can figure out how to make offline bootstrapping work with a new toolchain file, then I will submit a pull request to close this issue. Or someone else who has already figured it out is welcome to submit a pull request to close this issue too. Open source software development is all about upstreaming improvements from the community whenever possible.

> what difference does it make what toolchain that is?

It makes a very big difference indeed to me that I'm using vcpkg in a supported way. If the official stance of the vcpkg project is that offline bootstrapping is not supported, then this issue can be closed as not planned, but if the vcpkg project is open to the idea of supporting offline bootstrapping, then there should be an official way to do it. @BillyONeal Could I ask you to clarify again where you stand on this issue?

**Comment by BillyONeal** [comment]
> The solutions I propose may be more complicated than copying files by hand, but that's equivalent to saying that vcpkg itself is more complicated than managing project dependencies by hand.

No, I think you are misunderstanding my meaning. All the solutions you propose are increasingly complicated ways to get a vcpkg.exe on the build machine, and I'm just saying I don't understand who the customer is that can arrange any of those things but can't arrange some way to get vcpkg.exe onto the build machine *more easily* than any of those.

bootstrap doesn't do anything other than download the exe.

> Isn't the whole point of vcpkg to make dependency management less manual? If I have to manage everything by myself then why use vcpkg at all? That's why I proposed some solutions that will get an offline development environment up and running right after cloning a repo containing vcpkg as a submodule with no manual steps or custom images required.

Your proposed solutions have manual steps (in order to configure where the relevant vcpkg parts are in your internal air gapped environment).

> To clarify my point about building from source, the idea was that I would make vcpkg-tool another submodule of my project, and build it as part of the vcpkg bootstrapping. It's not a problem for me to clone source code into my offline git server, but it's a problem when repos try to access the internet from my clone.

If you can make an internal repo with the vcpkg-tool sources you can make a repo with the vcpkg-tool exe.

> Now that I've hopefully explained my constraints a bit better, could you take another look at my proposed solutions and see what can be done to adopt at least one of them?

>(1) Clone the vcpkg and vcpkg-tool repositories to an internal git server and modify bootstrap.sh to point to that address instead of github.com.

If you can make an internal server with content you can just:

```
curl -L -o vcpkg.exe https://path-to-internal-server/vcpkg.exe
```

or

```
git clone git@internal-server repo-with-a-vcpkg-exe
cp repo-with-a-vcpkg-exe/vcpkg.exe .
```

>(2) Add back a way to build the vcpkg executable from source, like there used to be a few years ago.

For that to work you need to get the sources on the box, and if you can get the sources on the box, you can get the exe on the box too.

>(3) Add a new environment variable called VCPKG_TOOL_URL or VCPKG_TOOL_PATH or something like that to tell bootstrap.sh where to pull vcpkg-tool from.

You don't need bootstrap.sh or bootstrap to do that. If you have a URL with the tool, `curl -L -o vcpkg.exe your-fancy-url`

>(4) Somehow upload the vcpkg executable itself to the remote source as part of the binary caching step, and retrieve from the CMake toolchain file as the first step of the offline bootstrapping process.

I don't even know what this means, since we need the executable in order to talk to binary caching providers.

**Comment by Neumann-A** [comment]
@BillyONeal: I think the point here is that `vcpkg.cmake` is bootstraping automatically and if you could simply set some magic variables in the environment it could automatically pull from wherever and make it work. But i also see that a simple clone of vcpkg with modifications to the bootstrap script would achieve the same. however, it seems that setting a magic env variable is easier than meddling with some shell script. The whole idea here is simply re-using an already existing script instead of havin to come up with a different solution (e.g. some other script copying vcpkg.exe to a location where `vcpkg.cmake` can see it and won't call the bootstrap script. ).

**Comment by sweemer** [comment]
@Neumann-A Yes that's exactly what I'm proposing. Thanks for helping to elucidate the idea.

**Comment by BillyONeal** [comment]
Ohhhhh, so this isn't about bootstrap at all, but the CMake integration.

I'm still not convinced that there exists an interface here that is less work or complication than just "do whatever you need to your internal things to get a vcpkg.exe" but at least that makes more sense. At a minimum we could document it with a "curl -L -o vcpkg.exe https://example.com/stuff".

**Comment by sweemer** [comment]
Great, glad we're now all on the same page, and sorry for not making it more clear that I'm talking about bootstrapping through the CMake integration.

> an interface here that is less work or complication

Again, my proposal is not intended to reduce complication - it is intended to upstream the complication instead of forcing it on users. I want "do whatever you need to your internal things to get a vcpkg.exe" to mean that the CMake integration handles this automatically based on some mechanism such as an environment variable.

There is some precedent for this idea with the `VCPKG_FORCE_SYSTEM_BINARIES` and `VCPKG_FORCE_DOWNLOADED_BINARIES` environment variables. These control whether vcpkg uses internal or external binaries, so why not allow the same kind of control over where vcpkg itself comes from?

**Comment by sweemer** [comment]
@BillyONeal It has taken me a while, but I have finally made a PR for these changes. Can you please help review https://github.com/microsoft/vcpkg/pull/36947 for me?
