### ISSUE TITLE
[libxml2] build failure

### ISSUE THREAD

**Issue by sdsjb** [microsoft/vcpkg#31646]
### Operating system

Windows 8.1

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
./vcpkg install libxml2
```

### Failure logs

<...>
Downloading https://gitlab.gnome.org//GNOME/libxml2/-/archive/f507d167f1755b7eaea09fb1a44d29aab828b6d1/libxml2-f507d167f
1755b7eaea09fb1a44d29aab828b6d1.tar.gz
warning: Download failed -- retrying after 1000ms
warning: Download failed -- retrying after 2000ms
warning: Download failed -- retrying after 4000ms
error: Failed to download from mirror set
error: https://gitlab.gnome.org//GNOME/libxml2/-/archive/f507d167f1755b7eaea09fb1a44d29aab828b6d1/libxml2-f507d167f1755b
7eaea09fb1a44d29aab828b6d1.tar.gz: WinHttpSendRequest failed with exit code 12175
error: https://gitlab.gnome.org//GNOME/libxml2/-/archive/f507d167f1755b7eaea09fb1a44d29aab828b6d1/libxml2-f507d167f1755b
7eaea09fb1a44d29aab828b6d1.tar.gz: WinHttpSendRequest failed with exit code 12175
error: https://gitlab.gnome.org//GNOME/libxml2/-/archive/f507d167f1755b7eaea09fb1a44d29aab828b6d1/libxml2-f507d167f1755b
7eaea09fb1a44d29aab828b6d1.tar.gz: WinHttpSendRequest failed with exit code 12175
error: https://gitlab.gnome.org//GNOME/libxml2/-/archive/f507d167f1755b7eaea09fb1a44d29aab828b6d1/libxml2-f507d167f1755b
7eaea09fb1a44d29aab828b6d1.tar.gz: WinHttpSendRequest failed with exit code 12175
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(961):
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 13us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 3478us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 9.4 s (9380015us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_gitlab.cmake:118 (vcpkg_download_distfile)
  ports/libxml2/portfile.cmake:1 (vcpkg_from_gitlab)
  scripts/ports.cmake:147 (include)

error: building libxml2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libxml2
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[libxml2]+Build+error&body=Copy+issue+body+from+C%3A%2Fdev%2Fvcp
kg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by Cheney-W** [comment]
Were you able to successfully download `https://gitlab.gnome.org//GNOME/libxml2/-/archive/f507d167f1755b7eaea09fb1a44d29aab828b6d1/libxml2-f507d167f1755b7eaea09fb1a44d29aab828b6d1.tar.gz` manually to your local machine?

If not, please download this file
[libxml2-f507d167f1755b7eaea09fb1a44d29aab828b6d1.tar.gz](https://github.com/microsoft/vcpkg/files/11590912/libxml2-f507d167f1755b7eaea09fb1a44d29aab828b6d1.tar.gz)
into the `vcpkg/downloads` and rename as `GNOME-libxml2-f507d167f1755b7eaea09fb1a44d29aab828b6d1.tar.gz`, then please install libxml2 again,

**Comment by sdsjb** [comment]
> Were you able to successfully download `https://gitlab.gnome.org//GNOME/libxml2/-/archive/f507d167f1755b7eaea09fb1a44d29aab828b6d1/libxml2-f507d167f1755b7eaea09fb1a44d29aab828b6d1.tar.gz` manually to your local machine?
> 
> If not, please download this file [libxml2-f507d167f1755b7eaea09fb1a44d29aab828b6d1.tar.gz](https://github.com/microsoft/vcpkg/files/11590912/libxml2-f507d167f1755b7eaea09fb1a44d29aab828b6d1.tar.gz) into the `vcpkg/downloads` and rename as `GNOME-libxml2-f507d167f1755b7eaea09fb1a44d29aab828b6d1.tar.gz`, then please install libxml2 again,

Thank you. It works  ( I did it before, but I didn't add the prefix "GNOME" (I didn't know it should have been added)).

p.s. I'm a novice in vcpkging, so my question - is this common workaround to download inaccessible packages manually and add to their names some prefixes? If yes, how to know what prefix to add?

**Comment by Cheney-W** [comment]
In general, manually downloads file is used as temporary solutions to address issues where individual machines cannot access the files to be downloaded. 
After manually downloading the file, the file is typically named as follows: `"${org_name}-${repo_name}-${sanitized_ref}.tar.gz"`

Taking the port `libxml2` as an example, in the repository `REPO GNOME/libxml2`, `GNOME` represents the `org_name`, `libxml2` represents the `repo_name`, and the value of `REF` is the `sanitized_ref`. Therefore, the downloaded file is named `GNOME-libxml2-f507d167f1755b7eaea09fb1a44d29aab828b6d1.tar.gz`.
```
vcpkg_from_gitlab(
    GITLAB_URL https://gitlab.gnome.org/
    OUT_SOURCE_PATH SOURCE_PATH
    REPO GNOME/libxml2
    REF f507d167f1755b7eaea09fb1a44d29aab828b6d1
    ...
)
```

**Comment by Cazadorro** [comment]
Hey I had the same exact issue, not sure what the deal is, there are alternative download places for these files too, I cannot access this file directly either

**Comment by Cheney-W** [comment]
@Cazadorro  Could you please send the failure logs to us?

**Comment by easymoney322** [comment]
I had the same issue just now.
For some reason, I wasn't able to open gnome.org, or their gitlab subdomain in IE. All the other browsers were working fine.
I've disabled secure mode in IE, added website to intranet, manually installed website certificate for the user and machine into a personal folder. And yet I wasn't able to open website in IE.
IE's troubleshooter was unable to find anything.
Unable to load the page with Edge emulation and v10.
No proxies. All other browsers are able to open the site. Other websites are openning in IE too.

OS: Windows 8.1
IE Version: 11.0.9600.17416 with patch KB3003057. SSL/TLS is on up to 1.2 (including)

Libxml2 was the only package I've had such problem with. 
I've installed Cuda, Pthreads, boost and opencv4 libraries today using vcpkg with no problem. Vcpkg is up to date, and so is the packages data.

Here is a thing:
Http version of the website redirects to https. **Maybe their webserver opted to only allow TLS1.3, which looks like unsupported in IE11**

I'm able to recreate it with powershell as well:
```
PS C:\Users\MikhailWin8> Invoke-WebRequest -uri "https://gitlab.gnome.org//GNOME/libxml2/-/archive/v2.11.5/libxml2-v2.11
.5.tar.gz"
Invoke-WebRequest : Запрос был прерван: Не удалось создать защищенный канал SSL/TLS.
строка:1 знак:1
+ Invoke-WebRequest -uri "https://gitlab.gnome.org//GNOME/libxml2/-/archive/v2.11. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
PS C:\Users\MikhailWin8> Invoke-WebRequest -Uri google.com
StatusCode        : 200
StatusDescription : OK
Content           : <!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="ru"><head><meta conten
                    t="Поиск информации в интернете: веб страницы, картинки, видео и многое другое." name="description"
                    ><...
RawContent        : HTTP/1.1 200 OK
                    Content-Security-Policy-Report-Only: object-src 'none';base-uri 'self';script-src 'nonce-auF94M2ta_
                    J0wF12i8FZYw' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: ...
...
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 53233
```

And my vcpkg stdout log looks like this:
```
-- Downloading https://gitlab.gnome.org//GNOME/libxml2/-/archive/v2.11.5/libxml2-v2.11.5.tar.gz -> GNOME-libxml2-v2.11.5.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from M:\vcpckg\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: M:\vcpckg\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://gitlab.gnome.org//GNOME/libxml2/-/archive/v2.11.5/libxml2-v2.11.5.tar.gz
warning: Download failed -- retrying after 1000ms
warning: Download failed -- retrying after 2000ms
warning: Download failed -- retrying after 4000ms
error: Failed to download from mirror set
error: https://gitlab.gnome.org//GNOME/libxml2/-/archive/v2.11.5/libxml2-v2.11.5.tar.gz: WinHttpSendRequest failed with exit code 12175
error: https://gitlab.gnome.org//GNOME/libxml2/-/archive/v2.11.5/libxml2-v2.11.5.tar.gz: WinHttpSendRequest failed with exit code 12175
error: https://gitlab.gnome.org//GNOME/libxml2/-/archive/v2.11.5/libxml2-v2.11.5.tar.gz: WinHttpSendRequest failed with exit code 12175
error: https://gitlab.gnome.org//GNOME/libxml2/-/archive/v2.11.5/libxml2-v2.11.5.tar.gz: WinHttpSendRequest failed with exit code 12175
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1053): 
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 9us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 334us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 8.5 s (8466486us)
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      3. Your proxy's remote server is out of service.
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_gitlab.cmake:118 (vcpkg_download_distfile)
  ports/libxml2/portfile.cmake:1 (vcpkg_from_gitlab)
  scripts/ports.cmake:147 (include)
```

**Comment by easymoney322** [comment]
I've checked gnome.org with ssllabs and it looks like there are handshake failures for some combinations of browsers and OS:
```
Firefox 31.3.0 ESR / Win 7 | RSA 2048 (SHA256) | TLS 1.2 | TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256   ECDH secp256r1  FS
Firefox 47 / Win 7  R | RSA 2048 (SHA256) | TLS 1.2 > h2 | TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256   ECDH secp256r1  FS
IE 11 / Win 7  R | Server sent fatal alert: handshake_failure
IE 11 / Win 8.1  R | Server sent fatal alert: handshake_failure
IE 11 / Win Phone 8.1  R | Server sent fatal alert: handshake_failure
IE 11 / Win Phone 8.1 Update  R | Server sent fatal alert: handshake_failure
IE 11 / Win 10  R | RSA 2048 (SHA256) | TLS 1.2 > h2 | TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256   ECDH secp256r1  FS
Edge 15 / Win 10  R | RSA 2048 (SHA256) | TLS 1.2 > h2 | TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256   ECDH x25519  FS
Safari 6 / iOS 6.0.1 | Server sent fatal alert: handshake_failure
Safari 7 / iOS 7.1  R | Server sent fatal alert: handshake_failure
Safari 7 / OS X 10.9  R | Server sent fatal alert: handshake_failure
Safari 8 / iOS 8.4  R | Server sent fatal alert: handshake_failure
Safari 8 / OS X 10.10  R | Server sent fatal alert: handshake_failure
OpenSSL 1.0.1l  R | RSA 2048 (SHA256) | TLS 1.2 | TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256   ECDH secp256r1  FS
```

**Comment by dg0yt** [comment]
AFAIU it is not a vcpkg issue.
