### ISSUE TITLE
[libtins] live packet capture not supported on this system

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [microsoft/vcpkg#31642]
**Describe the bug**
I cant live capture traffic with the libtins library installed through vckg on windows 11 22h2. 
winpcap / npcap dlls installed. Binary compiles, it runs.  Except for live packet capture. 

Note: Wireshark works on my system.

**Environment**
- OS: Windows 11 22H2
- Compiler: MSBuild version 17.5.0+6f08c67f3 for .NET Framework

**To Reproduce**
1. ./vcpkg install libtins:x64-
2. See error
Repro code when

**Expected behavior**
To capture live packets.

**Failure logs**
![image](https://github.com/microsoft/vcpkg/assets/7256303/e9f7f9d1-598f-408b-ae1b-923de1f16fea)

**Additional context**
Other functionality of the libtins library does work as expected. It seems the something with the depency with libpcap is broken or working incorrectly?

**Comment by Adela0814** [comment]
I noticed that you submitted the same issue to the upstream. Let's wait for the upstream's response first.

**Comment by maordadush** [comment]
@Adela0814 @MathiasDeWeerdt 

Confirmed, I can repro this on my side.

**Comment by MathiasDeWeerdt** [comment]
> @Adela0814 @MathiasDeWeerdt
> 
> Confirmed, I can repro this on my side.

Are you using VCPKG?

**Comment by maordadush** [comment]
> > @Adela0814 @MathiasDeWeerdt
> > Confirmed, I can repro this on my side.
> 
> Are you using VCPKG?

Yes

**Comment by MathiasDeWeerdt** [comment]
> > > @Adela0814 @MathiasDeWeerdt
> > > Confirmed, I can repro this on my side.
> > 
> > 
> > Are you using VCPKG?
> 
> Yes

I figured out that by default vcpkg is not compiling the package with live packet capture support. 
Adding the following to its portfile resolves this: 

```-DPacket_ROOT="C:/npcap-sdk"```

Npcap SDK source: https://npcap.com/dist/npcap-sdk-1.13.zip
And recompile everything.

There are also references to:
```DISABLE_PACKET "Disable Packet support" OFF```

Adjust this accordingly.

**Comment by maordadush** [comment]
@MathiasDeWeerdt could you please share your libtins and libpcap portfile.cmake files with me?

**Comment by MathiasDeWeerdt** [comment]
> @MathiasDeWeerdt could you please share your libtins and libpcap portfile.cmake files with me?

Ill look into posting it later this week.

**Comment by maordadush** [comment]
> > @MathiasDeWeerdt could you please share your libtins and libpcap portfile.cmake files with me?
> 
> Ill look into posting it later this week.

can you check please, where you defined the` DPacket_ROOT`?

> https://github.com/the-tcpdump-group/libpcap/issues/1238

**Comment by maordadush** [comment]
@MathiasDeWeerdt can you check, please?
