### ISSUE TITLE
json-schema-validator build failure

### ISSUE THREAD

**Issue by mark-99** [microsoft/vcpkg#31648]
### Operating system

Windows

### Compiler

MSVC /c++:latest

### Steps to reproduce the behavior

```Shell
Breaks after updating to VS 17.6.2.
Updated vcpkg to latest but it didn't help.

Error seems to be in nlohmann, although we use that separately and it's ok (maybe embedded version is old?).
```

### Failure logs

```
Using source at C:/Temp/MdpCpp/vcpkg/buildtrees/json-schema-validator/src/2.2.0-e87f98a2b7.clean
``` 
```
 C:\Temp\MdpCpp\vcpkg\buildtrees\json-schema-validator\src\2.2.0-e87f98a2b7.clean\src\json-validator.cpp(606): error C7692: 'bool nlohmann::json_abi_v3_11_2::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::json_abi_v3_11_2::adl_serializer,std::vector<uint8_t,std::allocator<uint8_t>>>::operator ==(const nlohmann::json_abi_v3_11_2::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::json_abi_v3_11_2::adl_serializer,std::vector<uint8_t,std::allocator<uint8_t>>> &) noexcept const': rewritten candidate function was excluded from overload resolution because a corresponding operator!= declared in the same scope
```

**Comment by mark-99** [comment]
/c++20 is the same, so it's not just C++23 mode.

**Comment by FrankXie05** [comment]
It seems that in the new version, [operator==](https://json.nlohmann.me/api/json_pointer/operator_eq/) and [operator!=](https://json.nlohmann.me/api/json_pointer/operator_ne/) has been deprecated . Please use teh latest version and try again. 
vcpkg has updated the version. :)

https://github.com/nlohmann/json/releases/tag/v3.11.2#:~:text=%F0%9F%94%A5,.%20%233684

**Comment by marcodsantia** [comment]
Same issue for me. It works fine when installing json-schema-validator standalone without vcpkg (still using vcpkg for nlohmann_json)

**Comment by lufi0401** [comment]
There's a workaround according to https://github.com/nlohmann/json/issues/3868#issuecomment-1563726354

by adding following to the overlay-triplet:
```cmake
if(${PORT} MATCHES "json-schema-validator")
    set(VCPKG_CXX_FLAGS ${VCPKG_CXX_FLAGS} "-DJSON_HAS_THREE_WAY_COMPARISON=0")
endif()
```
