### ISSUE TITLE
VS solutions/projects in the ports folder pollute VS targets list

### ISSUE THREAD

**Issue by Trider12** [microsoft/vcpkg#31652]
**Describe the bug**
When using vcpkg as a submodule, various `.sln` and `.vcxproj` files located in the `vcpkg/ports/` directory pollute the targets list of Visual Studio:

![image](https://github.com/microsoft/vcpkg/assets/47952308/839b8cf8-9c04-4b1a-97cd-82a7697bd055)

**Environment**
- OS: Windows
- IDE: VS2022

**To Reproduce**
1. Create a CMake project (not sure whether the same problem occurs with VS projects)
2. Have vcpkg cloned somewhere inside the project directory

**Expected behavior**
* Solution 1: remove these types of files from vcpkg
* Solution 2: some way to tell VS to ignore the vcpkg folder

**Additional context**
The `Show/Hide Debug Targets` feature is helpful, but requires to manually select every target imported by vcpkg and is reset when VS project cache is deleted.

**Comment by Trider12** [comment]
The same problem occurs in the `Solution Explorer` window, but there's no filtering functionality there:
![image](https://github.com/microsoft/vcpkg/assets/47952308/4ac26247-da5a-4347-9b6c-786a10e1df1d)

**Comment by MonicaLiu0311** [comment]
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Create a CMake project (not sure whether the same problem occurs with VS projects)
> 2. Have vcpkg cloned somewhere inside the project directory

Are there some steps to reproduce? May I ask how you use vcpkg in cmake?

**Comment by Trider12** [comment]
> May I ask how you use vcpkg in cmake?

You don't even need to "use" vcpkg to observe this issue. Just have vcpkg cloned inside a CMake project folder and then open that project in VS.

**Comment by MonicaLiu0311** [comment]
I did this, but sorry I didn't reproduce your issue. After the build, there are only original files in the `ports/` directory, without `.sln` and `.vcxproj`.
![image](https://github.com/microsoft/vcpkg/assets/110024546/09751c0c-9b28-4e63-973b-86e1064c8037)

**Comment by Trider12** [comment]
> After the build, there are only original files in the ports/ directory

I didn't mean the `ports/` directory literally. I meant that _ports_ inside that directory have these files. Just open the targets list like in the screenshot I provided.
