### ISSUE TITLE
[<portname>] <short description of feature>

### ISSUE THREAD

**Issue by JimmyyHilmmyyyy** [microsoft/vcpkg#31653]
### Is your feature request related to a problem? Please describe.

get_id()

### Proposed solution

git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
git checkout 1b1ae50e1a69f7c659bd7d731e80b358d21c86ad
.\bootstrap-vcpkg.bat
.\vcpkg.exe install gperf:x86-windows openssl:arm-uwp openssl:arm64-uwp openssl:x64-uwp openssl:x86-uwp zlib:arm-uwp zlib:arm64-uwp zlib:x64-uwp zlib:x86-uwp

**Comment by Adela0814** [comment]
Please refer to [#30604](https://github.com/microsoft/vcpkg/issues/30604) to provide error details.

**Comment by Adela0814** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
