### ISSUE TITLE
[sqlite3] Provide cmake target SQLite::SQLite3

### ISSUE THREAD

**Issue by huangqinjin** [microsoft/vcpkg#31659]
CMake 3.14+ provides a official [`FindSQLite3`](https://cmake.org/cmake/help/latest/module/FindSQLite3.html) module and `SQLite::SQLite3` target. 

It would be good that vcpkg also provides the same name instead of `unofficial::sqlite3::sqlite3`. The `FindSQLite3` module does not support multi-config generators well.

**Comment by dg0yt** [comment]
IMO the official target doesn't belong into the unofficial config. 
But it could make sense to add a wrapper for cmake package  `SQLite3` which takes care of vcpkg's multi-config setup.

However, there are many official find modules which poorly support multi-config or static usage requirements. I just refreshed #27408 which tests some common modules incl. SQLite3.

**Comment by huangqinjin** [comment]
Wonderful work in #27408 . Adding wrappers for all official find modules is great. As the maintainer of CMake states that they rarely add find modules anymore https://gitlab.kitware.com/cmake/cmake/-/issues/24607#note_1335831.

**Comment by dg0yt** [comment]
Well, #27408 is only the (modified) test port. It doesn't fix a single package for multi-config.
What is usually fixed quickly is broken single-config usage. (This is covered by the current version of the `cmake-user` test port.)

**Comment by SchaichAlonso** [comment]
vcpkg's sqlite3 package does provide the `SQLite::SQLite3` target.

See https://github.com/SchaichAlonso/vcpkg-sqlite-demo for a minimal project using that target. The github CI [can find_package(SQLite3)](https://github.com/SchaichAlonso/vcpkg-sqlite-demo/actions/runs/5099814105/jobs/9167737400#step:3:75) and [set it up to be used at run-time](https://github.com/SchaichAlonso/vcpkg-sqlite-demo/actions/runs/5099814105/jobs/9167737400#step:4:7), too.

**Comment by huangqinjin** [comment]
@SchaichAlonso Please build your demo with `cmake --build . --config Release -- -v:n`, you will see it links to debug version of `sqlite3`. (Though vcpkg will copy release version next to the built executable.)

**Comment by SchaichAlonso** [comment]
`... "vcpkg_installed\x64-windows\debug\lib\sqlite3.lib" ...` from https://github.com/SchaichAlonso/vcpkg-sqlite-demo/actions/runs/5100058804/jobs/9168112436#step:3:109 is the (mis)behaviour you're refering to I guess

**Comment by dg0yt** [comment]
> vcpkg's sqlite3 package does provide the `SQLite::SQLite3` target.

This is not the point. The point is that it is not setup to provide multi-config info.
https://github.com/Kitware/CMake/blob/master/Modules/FindSQLite3.cmake
