### ISSUE TITLE
Using vcpkg and opencv in cmake in a docker environment

### ISSUE THREAD

**Issue by ferjif** [microsoft/vcpkg#31661]
I tried to use opencv with vcpkg in a docker environment with an ubuntu 20.04 base image. but the problem is when i try to link my executable to ${OpenCV_LIBS} the cmake generator complains at me. it gives the error i attached below. the problem is even when i use libarchive and add the find_package at top of the file and add the target_link_libraries(main PUBLIC libarchive::libarchive) i still get the error.

**Environment**
- OS: ubuntu 20.04 docker

**To Reproduce**
1. docker run -it ubuntu:20.04 /bin/bash
2. install vcpkg in docker container using the bash you entered
3. ./vcpkg install opencv4
4. create test project
5. create CMakeLists.txt with code:
```
cmake_minimum_required(VERSION 3.14)

project(test VERSION 0.1 LANGUAGES CXX)

set(CMAKE_INCLUDE_CURRENT_DIR ON)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(OpenCV_DIR "${VCPKG_INSTALLED_DIR}/x64-linux/share/opencv4")
find_package(OpenCV REQUIRED)

add_executable(test main.cpp)
target_link_libraries(test PUBLIC ${OpenCV_LIBS})
```

**Expected behavior**
i expected the project to generate and build without any hassle.

**Failure logs**
```
CMake Error at /data/vcpkg/scripts/buildsystems/vcpkg.cmake:592 (_add_executable):
  Target "test" links to target "LibArchive::LibArchive" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:13 (add_executable)
```

**Comment by dg0yt** [comment]
vcpkg uses CMake 3.25 internally. `LibArchive::LibArchive` is documented since CMake 3.17. Ubuntu 20.04 has CMake 3.16. 
Which version of CMake do you use for your project?

**Comment by ferjif** [comment]
i use the cmake package provided in ubuntu 20.04. i checked it's 3.16. you're right.

**Comment by Adela0814** [comment]
Using the cmake provided by vcpkg to run can solve your problem.
`./../vcpkg/downloads/tools/cmake-3.25.1-linux/cmake-3.25.1-linux-x86_64/bin/cmake CMakeLists.txt -DCMAKE_TOOLCHAIN_FILE=/home/user/vcpkg/scripts/buildsystems/vcpkg.cmake`

**Comment by ferjif** [comment]
_**Thank you**_ for all your comments. the first answer solved my issue.
**the solution was to either use the cmake that came with vcpkg or download and install a cmake version >= 3.17.** 
i will close the issue here.
