### ISSUE TITLE
[qtdeclarative] build failure

### ISSUE THREAD

**Issue by Gabryoo3** [microsoft/vcpkg#31682]
### Operating system

Windows 11

### Compiler

GCC (WSL) but vcpkg is installed on Windows

### Steps to reproduce the behavior

```Shell
Install 'qt' using vcpkg from CLion
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
    qt[core,default-features]:x64-windows-static -> 6.5.1
  * qt3d[animation,assimp,core,extras,input,logic,qml,render,rhi]:x64-windows-static -> 6.5.1
  * qt5compat[big-codecs,codecs,core,default-features,qml,textcodec]:x64-windows-static -> 6.5.1
  * qtactiveqt[core]:x64-windows -> 6.5.1
  * qtactiveqt[core,qml]:x64-windows-static -> 6.5.1
  * qtapplicationmanager[core]:x64-windows-static -> 6.5.1
  * qtapplicationmanager[core]:x64-windows -> 6.5.1
  * qtcharts[core,designer,qml]:x64-windows-static -> 6.5.1
  * qtcoap[core]:x64-windows-static -> 6.5.1
  * qtconnectivity[core]:x64-windows-static -> 6.5.1
  * qtdatavis3d[core]:x64-windows-static -> 6.5.1
  * qtdeclarative[core]:x64-windows-static -> 6.5.1
  * qtdoc[core]:x64-windows-static -> 6.5.1
  * qtimageformats[core,default-features,jasper,tiff,webp]:x64-windows-static -> 6.5.1
  * qtinterfaceframework[core]:x64-windows-static -> 6.5.1
  * qtinterfaceframework[core]:x64-windows -> 6.5.1
  * qtlanguageserver[core]:x64-windows-static -> 6.5.1
  * qtlottie[core,qml]:x64-windows-static -> 6.5.1
  * qtmqtt[core]:x64-windows-static -> 6.5.1
  * qtmultimedia[core,widgets]:x64-windows -> 6.5.1
  * qtmultimedia[core,qml,widgets]:x64-windows-static -> 6.5.1
  * qtnetworkauth[core]:x64-windows-static -> 6.5.1
  * qtopcua[core,default-features,gds,ns0idnames,open62541,qml]:x64-windows-static -> 6.5.1
  * qtpositioning[core,qml]:x64-windows-static -> 6.5.1
  * qtquick3d[core,default-features]:x64-windows -> 6.5.1
  * qtquick3d[core,default-features]:x64-windows-static -> 6.5.1
  * qtquicktimeline[core]:x64-windows -> 6.5.1
  * qtquicktimeline[core]:x64-windows-static -> 6.5.1
  * qtremoteobjects[core,qml]:x64-windows-static -> 6.5.1
  * qtremoteobjects[core]:x64-windows -> 6.5.1
  * qtscxml[core]:x64-windows -> 6.5.1
  * qtscxml[core,qml]:x64-windows-static -> 6.5.1
  * qtsensors[core,qml]:x64-windows-static -> 6.5.1
  * qtserialbus[core,default-features]:x64-windows -> 6.5.1
  * qtserialbus[core,default-features]:x64-windows-static -> 6.5.1
  * qtserialport[core]:x64-windows-static -> 6.5.1
  * qtserialport[core]:x64-windows -> 6.5.1
  * qtspeech[core]:x64-windows-static -> 6.5.1
  * qtsvg[core]:x64-windows-static -> 6.5.1
  * qttools[assistant,core,designer,linguist]:x64-windows -> 6.5.1
  * qttools[assistant,core,designer,linguist,qml]:x64-windows-static -> 6.5.1
  * qttranslations[core,default-features]:x64-windows-static -> 6.5.1
  * qtvirtualkeyboard[core,default-features,hunspell]:x64-windows-static -> 6.5.1
  * qtwebchannel[core,qml]:x64-windows-static -> 6.5.1
  * qtwebsockets[core,qml]:x64-windows-static -> 6.5.1
  * qtwebview[core]:x64-windows-static -> 6.5.1
  * taglib[core]:x64-windows-static -> 1.13.0#1
  * taglib[core]:x64-windows -> 1.13.0#1
  * tiff[core,jpeg,lzma,zip]:x64-windows-static -> 4.5.0#3
  * vcpkg-get-python-packages[core]:x64-windows -> 2022-06-30
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows-static...
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\Utente\AppData\Local\vcpkg\archives in 4.53 ms. Use --debug to see more details.
Installing 1/50 qtdeclarative:x64-windows-static...
Building qtdeclarative[core]:x64-windows-static...
-- Using cached qtdeclarative-everywhere-src-6.5.1.tar.xz.
-- Cleaning sources at C:/libraries/vcpkg/buildtrees/qtdeclarative/src/here-src-6-02b224fed5.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/libraries/vcpkg/downloads/qtdeclarative-everywhere-src-6.5.1.tar.xz
-- Using source at C:/libraries/vcpkg/buildtrees/qtdeclarative/src/here-src-6-02b224fed5.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/libraries/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: C:/libraries/vcpkg/buildtrees/qtdeclarative/x64-windows-static-dbg
    See logs for more information:
      C:\libraries\vcpkg\buildtrees\qtdeclarative\install-x64-windows-static-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  installed/x64-windows-static/share/qtbase/qt_install_submodule.cmake:348 (vcpkg_cmake_install)
  ports/qtdeclarative/portfile.cmake:25 (qt_install_submodule)
  scripts/ports.cmake:147 (include)

error: building qtdeclarative:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qtdeclarative
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[qtdeclarative]+Build+error&body=Copy+issue+body+from+C%3A%2Flibraries%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

I tried a lot of things: putting rc.exe path, moving vcpkg in another folder with shorter name but still nothing work. Here log file:
[install-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/11585438/install-x64-windows-static-dbg-out.log)
Should I change compiler to MSVC?

**Comment by dg0yt** [comment]
> Should I change compiler to MSVC?

The x64-windows-static compiler is MSVC.
And the current build location file path is too long for qtdeclarative.

**Comment by Gabryoo3** [comment]
> @Gabryoo3 Does this issue still persist when you use a shorter vcpkg path? For example: use `C:\vcpkg` instead of `C:\libraries\vcpkg`

I installed it in another SSD and it works now
