### ISSUE TITLE
[rocksdb] optional dependencies regression

### ISSUE THREAD

**Issue by kobykahane** [Microsoft/vcpkg#3168]
In commit c4457ea6a70d890ceae0b81a89d677eee28f7645, lz4 and snappy were removed as a rocksdb dependencies and there's apparently no way to build rocksdb with those anymore.
We depend on support for those compression methods in our usage of RocksDB so this is a substantial regression for us. Ideally, these compression methods should be available as optional features of the rocksdb port.

**Comment by ras0219-msft** [comment]
Thanks for posting!

I've added lz4 and snappy back in as optional features in master. Please let us know if they work correctly for you :)

**Comment by kobykahane** [comment]
Thanks, seems to work. See also PR #3189 where I made zlib optional as well (in our case we don't need it).
