### ISSUE TITLE
install error with Poco

### ISSUE THREAD

**Issue by gzuroy** [Microsoft/vcpkg#3169]
When I execute this command in the console:

> PS > .\vcpkg.exe install poco

I got error message:

> -- Build x86-windows-dbg
> CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:136 (message):
>     Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
>     Working Directory: D:/royiluo/vcpkg/buildtrees/zlib/x86-windows-dbg
>     See logs for more information:
>       D:\royiluo\vcpkg\buildtrees\zlib\install-x86-windows-dbg-out.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
>   ports/zlib/portfile.cmake:29 (vcpkg_install_cmake)
>   scripts/ports.cmake:72 (include)
> 
> 
> Error: Building package zlib:x86-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: zlib:x86-windows
>   Vcpkg version: 0.0.107-2018-03-28-10e77be9fa5a4d6bb132c8d56ee8426de36ab449
> 
> Additionally, attach any relevant sections from the log files above.
>

**Comment by ras0219-msft** [comment]
Hi gzuroy, could you please attach the log file

>D:\royiluo\vcpkg\buildtrees\zlib\install-x86-windows-dbg-out.log

**Comment by gzuroy** [comment]
[install-x86-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/1866927/install-x86-windows-dbg-out.log)

The log file has some Chinese characters, because I installed Chinese version of VS2015. Sorry for the language hope it could help you find out the error.

**Comment by gzuroy** [comment]
After I change the proxy of my network setting then run the install poco again,  it was fixed. thank you for your help.
