### ISSUE TITLE
[colmap] build failure 

### ISSUE THREAD

**Issue by nsry123** [microsoft/vcpkg#31745]
### Operating system

Windows 10

### Steps to reproduce the behavior

```Shell
vcpkg install colmap[cuda,tests]:x64-windows
```

### Failure logs

C:\Users\nsry123\vcpkg>vcpkg install colmap[cuda,tests]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    colmap[core,cuda,tests]:x64-windows -> 2023-03-12#1
Detecting compiler hash for triplet x64-windows...
-- Automatically setting HTTP(S)_PROXY environment variables to "127.0.0.1:4780".
Restored 0 package(s) from C:\Users\nsry123\AppData\Local\vcpkg\archives in 154 us. Use --debug to see more details.
Installing 1/1 colmap:x64-windows...
Building colmap[core,cuda,tests]:x64-windows...
-- Using cached colmap-colmap-33e26924f950172751f044a89b964129b3728db8.tar.gz.
-- Extracting source C:/Users/nsry123/vcpkg/downloads/colmap-colmap-33e26924f950172751f044a89b964129b3728db8.tar.gz
-- Applying patch fix-dependencies.patch
CMake Error at scripts/cmake/z_vcpkg_apply_patches.cmake:34 (message):
  Applying patch failed: Checking patch CMakeLists.txt...

  error: while searching for:

  find_package(Eigen3 REQUIRED)

  find_package(FreeImage REQUIRED)

  find_package(FLANN REQUIRED)

  find_package(LZ4 REQUIRED)

  find_package(Metis REQUIRED)

  find_package(Glog REQUIRED)

  find_package(SQLite3 REQUIRED)

  error: patch failed: CMakeLists.txt:99

  error: CMakeLists.txt: patch does not apply

Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive.cmake:153 (z_vcpkg_apply_patches)
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:8 (vcpkg_extract_source_archive)
  scripts/cmake/vcpkg_from_github.cmake:113 (vcpkg_extract_source_archive_ex)
  ports/colmap/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:147 (include)

error: building colmap:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+colmap
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[colmap]+Build+error&body=Copy+issue+body+from+C%3A%2FUsers%2Fnsry123%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

According to the log, it seems that some packages such as Eigen3 that are bracketed in the find_package() are not installed. However, when trying to use vckpg install to install any of them, it says that they are already installed.

**Comment by JonLiu1993** [comment]
@nsry123, thanks for posting this issue, it looks like your error is because the patch is not applied, could you please update your vcpkg with the command `git pull` and try again?

````
Applying patch failed: Checking patch CMakeLists.txt...
````

**Comment by nsry123** [comment]
After updating, the same error still occurs. Thank you very much for your reply.

**Comment by nsry123** [comment]
> @nsry123, thanks for posting this issue, it looks like your error is because the patch is not applied, could you please update your vcpkg with the command `git pull` and try again?
> 
> ```
> Applying patch failed: Checking patch CMakeLists.txt...
> ```
After updating, the same error still occurs. Thank you very much for your reply.

**Comment by JonLiu1993** [comment]
@nsry123, Your error shows that the application of the colmap patch `fix-dependencies.patch` failed. I can no longer reproduce your error locally. can you clone a vcpkg to try again?

**Comment by JonLiu1993** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
