### ISSUE TITLE
wxwidgets:x64-uwp requires expat:x64-uwp, which does not exist

### ISSUE THREAD

**Issue by thehetz** [microsoft/vcpkg#3174]
I am trying to install wxwidgets:x64-uwp which does exist, however it has a dependency on expat:x64-uwp which does not exist yet.  Any thoughts on when it will be available?

Package: expat:x64-uwp
Vcpkg version: 0.0.107-2018-03-28-10e77be9fa5a4d6bb132c8d56ee8426de36ab449

Thank you.

**Comment by NancyLi1013** [comment]
Hi @thehetz, thanks for posting this issue. I have checked expat source code, it currently does't support uwp. Let's wait for the update of the source code.

**Comment by christianparpart** [comment]
*bump* still no update here, I guess? freetype/harfbuzz also both depend on expat, and I'd like to make my app UWP-aware, but fail due to such dependencies.  ;-(

**Comment by NancyLi1013** [comment]
@christianparpart 
Please keep this issue open until we have fixed it.

**Comment by NancyLi1013** [comment]
Hi @christianparpart 
Now `expat `has supported uwp. Sorry for the long waiting.
Please update vcpkg to the latest version and try to use it.

But for `wxiwdgests`, it still cannot support uwp now.

**Comment by christianparpart** [comment]
Many thanks
