### ISSUE TITLE
[<zlib>] build failure

### ISSUE THREAD

**Issue by MadhusudhanaHV** [microsoft/vcpkg#31757]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
'./vcpkg install zlib'
```

### Failure logs

D:\Madhusudhana H V\Madhu\C++\remoteDesktopTimeZone\vcpkg>vcpkg install zlib
warning: Starting with the September 2023 release, the default triplet for vcpkg
 libraries will change from x86-windows to the detected host triplet (x64-window
s). To resolve this message, add --triplet x86-windows to keep the same behavior
.
Computing installation plan...
The following packages will be built and installed:
    zlib[core]:x86-windows -> 1.2.13
Detecting compiler hash for triplet x86-windows...
Restored 0 package(s) from C:\Users\madhusudhana.hv.DELOPT\AppData\Local\vcpkg\a
rchives in 143 us. Use --debug to see more details.
Installing 1/1 zlib:x86-windows...
Building zlib[core]:x86-windows...
-- Using cached madler-zlib-v1.2.13.tar.gz.
-- Cleaning sources at D:/Madhusudhana H V/Madhu/C++/remoteDesktopTimeZone/vcpkg
/buildtrees/zlib/src/v1.2.13-f30d2a168d.clean. Use --editable to skip cleaning f
or the packages you specify.
-- Extracting source D:/Madhusudhana H V/Madhu/C++/remoteDesktopTimeZone/vcpkg/d
ownloads/madler-zlib-v1.2.13.tar.gz
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch 0002-skip-building-examples.patch
-- Applying patch 0003-build-static-or-shared-not-both.patch
-- Applying patch 0004-android-and-mingw-fixes.patch
-- Using source at D:/Madhusudhana H V/Madhu/C++/remoteDesktopTimeZone/vcpkg/bui
ldtrees/zlib/src/v1.2.13-f30d2a168d.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "D:/Madhusudhana H V/Madhu/C++/remoteDesktopTimeZone/vcpkg/d
ownloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe" --b
uild . --config Debug --target install -- -v -j5
    Working Directory: D:/Madhusudhana H V/Madhu/C++/remoteDesktopTimeZone/vcpkg
/buildtrees/zlib/x86-windows-dbg
    See logs for more information:
      D:\Madhusudhana H V\Madhu\C++\remoteDesktopTimeZone\vcpkg\buildtrees\zlib\
install-x86-windows-dbg-out.log
      D:\Madhusudhana H V\Madhu\C++\remoteDesktopTimeZone\vcpkg\buildtrees\zlib\
install-x86-windows-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_exec
ute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cm
ake_build)
  ports/zlib/portfile.cmake:26 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building zlib:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg upda
te`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+
zlib
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[zlib]+Build+error&body=
Copy+issue+body+from+D%3A%2FMadhusudhana%20H%20V%2FMadhu%2FC%2B%2B%2FremoteDeskt
opTimeZone%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by Adela0814** [comment]
@MadhusudhanaHV  Please provide the failure logs:
```
D:\Madhusudhana H V\Madhu\C++\remoteDesktopTimeZone\vcpkg\buildtrees\zlib
install-x86-windows-dbg-out.log
D:\Madhusudhana H V\Madhu\C++\remoteDesktopTimeZone\vcpkg\buildtrees\zlib
install-x86-windows-dbg-err.log
```

**Comment by MadhusudhanaHV** [comment]
Please refer the attachments.

[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/11624047/install-x86-windows-dbg-out.log)
[install-x86-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/11624061/install-x86-windows-dbg-err.log)

**Comment by dg0yt** [comment]
> `D:\Madhusudhana H V\Madhu\C++\remoteDesktopTimeZone\vcpkg`....

Move to a path
- without space
- without the special character `+`.

**Comment by MadhusudhanaHV** [comment]
Thanks. It worked.
