### ISSUE TITLE
[<libssh>] build failure

### ISSUE THREAD

**Issue by MadhusudhanaHV** [microsoft/vcpkg#31759]
### Operating system

Windows 8.1

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
'.\vcpkg install libssh'
```

### Failure logs

[git-fetch-x86-windows-err.log](https://github.com/microsoft/vcpkg/files/11624575/git-fetch-x86-windows-err.log)

### Additional context

D:\remoteDesktopTimeZone\vcpkg>.\vcpkg install libssh
warning: Starting with the September 2023 release, the default triplet for vcpkg
 libraries will change from x86-windows to the detected host triplet (x64-window
s). To resolve this message, add --triplet x86-windows to keep the same behavior
.
Computing installation plan...
The following packages will be built and installed:
    libssh[core,crypto,mbedtls]:x86-windows -> 0.10.4+20221123#3
Detecting compiler hash for triplet x86-windows...
Restored 0 package(s) from C:\Users\madhusudhana.hv.DELOPT\AppData\Local\vcpkg\a
rchives in 17.6 ms. Use --debug to see more details.
Installing 1/1 libssh:x86-windows...
Building libssh[core,crypto,mbedtls]:x86-windows...
-- Fetching https://git.libssh.org/projects/libssh.git master...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):

    Command failed: "C:/Program Files/Git/cmd/git.exe" fetch https://git.libssh.
org/projects/libssh.git master -n
    Working Directory: D:/remoteDesktopTimeZone/vcpkg/downloads/git-tmp
    Error code: 128
    See logs for more information:
      D:\remoteDesktopTimeZone\vcpkg\buildtrees\libssh\git-fetch-x86-windows-err
.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_git.cmake:86 (vcpkg_execute_required_process)
  ports/libssh/portfile.cmake:1 (vcpkg_from_git)
  scripts/ports.cmake:147 (include)

error: building libssh:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg upda
te`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+
libssh
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[libssh]+Build+error&bod
y=Copy+issue+body+from+D%3A%2FremoteDesktopTimeZone%2Fvcpkg%2Finstalled%2Fvcpkg%
2Fissue_body.md

D:\remoteDesktopTimeZone\vcpkg>

**Comment by autoantwort** [comment]
https://stackoverflow.com/questions/69387175/git-for-windows-ssl-certificate-problem-certificate-has-expired

Maybe you have to update your git version
