### ISSUE TITLE
How to recover from `vcpkg upgrade` failure

### ISSUE THREAD

**Issue by itsuhane** [microsoft/vcpkg#3176]
I think `vcpkg upgrade` needs some fail-safe.

Currently `vcpkg upgrade` will remove old packages then install new.

If install fail, those packages already gone will be lost. Retrying `upgrade` won't consider them hence not upgrading them. I have to re-install them again. If I'm already working with a huge vcpkg repository, trying to recall each one of them is really painful.

**Comment by Cheney-W** [comment]
@itsuhane, thanks for posting this issue. It's the similar issue with https://github.com/microsoft/vcpkg/issues/3023. Let's track this issue here.
