### ISSUE TITLE
provide support for making only release library in vcpkg

### ISSUE THREAD

**Issue by ghost** [microsoft/vcpkg#3179]
sighting some observation, which will help to understand this issue.
currenly tensorflow support on release build in c++ cmake mode as python.exe and python3.6.lib is only available. 
So in this case , if vcpkg allows to provide release library support, tensorflow will be more handy to the developer to use.
Note: In latter case if tensorflow support debug mode , both release and debug version can be provided.

Doubt: Let me know if any body tied to make tensorflow as vcpkg package before. 
I have tried , but only it support release mode, but vcpkg failed the validation , as there is no debug libraries for tensorflow .

**Comment by apattnaik0721013** [comment]
@ras0219-msft 
I need python 3 for both release and debug mode along with numpy and wheel which means I need python.exe and python3.6.lib for release mode and python.exe and python3.6d.lib for debug mode.

I am currently using the changes https://github.com/Microsoft/vcpkg/pull/3105
It has python-setuptool as port which install python along with pips in both release and debug mode and the executable(python.exe) in the tools which can be used for installing any python module.

Let me know if it is a good idea or not.

One more doubt. post validation failed for tensorflow if I am able to make tensorflow only in release mode. Do you have a idea how to handle this.

**Comment by kareemsayed** [comment]
Can I ask what is the progress with this one?

I've been really needing this feature because with the ASSIMP library. 
The loading times are really slow for me when in debug mode, so I wanted to use the release binaries while debugging my project.

**Comment by Osyotr** [comment]
You should set `VCPKG_BUILD_TYPE` to `release` in triplet file.
For example, https://github.com/microsoft/vcpkg/blob/314018fef43c7e3a52a3e46599313b70ace3977a/triplets/community/x64-windows-release.cmake#L4

**Comment by Neumann-A** [comment]
@JackBoosY close?
