### ISSUE TITLE
Add Ceres Solver

### ISSUE THREAD

**Issue by crmoore** [Microsoft/vcpkg#318]
> [Ceres Solver](http://ceres-solver.org/) is an open source C++ library for modeling and solving large, complicated optimization problems. It is a feature rich, mature and performant library which has been used in production at Google since 2010. Ceres Solver can solve two kinds of problems.
>
>    Non-linear Least Squares problems with bounds constraints.
>    General unconstrained optimization problems.

**Comment by zwn** [comment]
There are [instructions how to build ceres on windows](http://ceres-solver.org/installation.html#windows). According to that SuiteSparse and/or CXSparse are of most concern (both currently missing in vcpkg).

**Comment by KindDragon** [comment]
@ras0219-msft Can be closed
