### ISSUE TITLE
[gdal] build failure

### ISSUE THREAD

**Issue by MoeSzyslak98** [microsoft/vcpkg#31804]
### Operating system

Manjaro Linux 22.1.0 Talos (6.1.31-1 kernel)

### Compiler

gcc 12.2.1 20230201

### Steps to reproduce the behavior

```Shell
vcpkg install gdal
vcpkg install
```

### Failure logs

vcpkg console output:
```
~  vcpkg install gdal                                                                                                               
Computing installation plan...
The following packages will be built and installed:
    gdal[core,curl,default-features,expat,geos,gif,hdf5,iconv,jpeg,lerc,libkml,libspatialite,libxml2,lzma,netcdf,openjpeg,openssl,pcre2,png,postgresql,qhull,recommended-features,sqlite3,webp,zstd]:x64-linux -> 3.7.0#2
Detecting compiler hash for triplet x64-linux...
Restored 0 package(s) from /home/kian/.cache/vcpkg/archives in 6.54 us. Use --debug to see more details.
Installing 1/1 gdal:x64-linux...
Building gdal[core,curl,default-features,expat,geos,gif,hdf5,iconv,jpeg,lerc,libkml,libspatialite,libxml2,lzma,netcdf,openjpeg,openssl,pcre2,png,postgresql,qhull,recommended-features,sqlite3,webp,zstd]:x64-linux...
-- Using cached OSGeo-gdal-v3.7.0.tar.gz.
-- Cleaning sources at /home/kian/.local/vcpkg/buildtrees/gdal/src/v3.7.0-9fd58c78bf.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/kian/.local/vcpkg/downloads/OSGeo-gdal-v3.7.0.tar.gz
-- Applying patch find-link-libraries.patch
-- Applying patch fix-gdal-target-interfaces.patch
-- Applying patch libkml.patch
-- Using source at /home/kian/.local/vcpkg/buildtrees/gdal/src/v3.7.0-9fd58c78bf.clean
-- Found external ninja('1.11.1').
-- Configuring x64-linux
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: /usr/bin/cmake --build . --config Debug --target install -- -v -j5
    Working Directory: /home/kian/.local/vcpkg/buildtrees/gdal/x64-linux-dbg
    See logs for more information:
      /home/kian/.local/vcpkg/buildtrees/gdal/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/gdal/portfile.cmake:97 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)
```
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/11643382/install-x64-linux-dbg-out.log)

### Additional context

for manifest mode i was installing mapnik with `input-gdal` feature in `x64-linux-dynamic` triplet and i got the same errors.

**Comment by MoeSzyslak98** [comment]
and I am in master branch and #31753 issue's problem fixed with #31314 pull now i have this issue.
also in my search for the fix I saw that the flatbuffers had a new release so i updated it in #31780 but the update didn't fixed the problem.

**Comment by dg0yt** [comment]
> ~~~
> /usr/include/absl/base/policy_checks.h:79:2: error: #error "C++ versions less than C++14 are not supported."

This is unexpected use of system libraries. Neither abseil nor flatbuffers are in the dependencies of port gdal. I would like to see the config logs to see how it became part of the configuration.

**Comment by dg0yt** [comment]
So flatbuffers is a vendored copy in gdal, and abseil is selected because it exists.
https://github.com/OSGeo/gdal/blob/ab9cb1a1d4928cdcf2877d8e0c6ad9fc2c79fbc9/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/base.h#L236-L237

**Comment by dg0yt** [comment]
Newer flatbuffers code seems to be more careful:
https://github.com/google/flatbuffers/blob/72b56fd0810c9a6cd38ea1c8f40feaa1bb4916b1/include/flatbuffers/base.h#L237-L239

**Comment by dg0yt** [comment]
Reported upstream.

@MoeSzyslak98 Can you test #31816?

**Comment by jimwang118** [comment]
I tested the PR https://github.com/microsoft/vcpkg/pull/31816 on Ubuntu 22 and the result is normal.

**Comment by MoeSzyslak98** [comment]
#31816 fixed the problem, THANK YOU.
