### ISSUE TITLE
[curl] how to enable SMTP and rebuild lib

### ISSUE THREAD

**Issue by jmin911** [Microsoft/vcpkg#3182]
The [curl] lib has SMTP / SMTPS disabled by default.  How to enable it and rebuild the library?

**Comment by Voskrese** [comment]
@jmin911  https://github.com/Microsoft/vcpkg/blob/master/ports/curl/portfile.cmake

**Comment by jmin911** [comment]
Thanks for the info.
The command to build libcurl with non-http support is
./vcpkg.exe install curl[non-http]:x86-windows-static
