### ISSUE TITLE
aom:x86-windows-static build failure

### ISSUE THREAD

**Issue by hiroyukki** [microsoft/vcpkg#31823]
### Operating system

windows 11

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
vcpkg install aom:x86-windows-static
```

### Failure logs

In order to install this module, I reserved 32GB memory, but it is still not enough.
I tried reducing concurrent compilation by setting environment variable with `VCPKG_MAX_CONCURRENCY=1`, but it still didn't work.
but `vcpkg install aom:x64-windows-static` seems ok.

Output and install log file bellow:

K:\vcpkg>vcpkg install aom:x86-windows-static
Computing installation plan...
The following packages will be built and installed:
    aom[core]:x86-windows-static -> 3.5.0#1
Detecting compiler hash for triplet x86-windows-static...
-- Automatically setting HTTP(S)_PROXY environment variables to "127.0.0.1:1080".
Restored 0 package(s) from C:\Users\jiayi\AppData\Local\vcpkg\archives in 307 us. Use --debug to see more details.
Installing 1/1 aom:x86-windows-static...
Building aom[core]:x86-windows-static...
warning: -- Using community triplet x86-windows-static. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: K:\vcpkg\triplets\community\x86-windows-static.cmake
-- Using cached K:/vcpkg/downloads/aom-9a83c6a5a55c176adbce740e47d3512edfc9ae71.tar.gz
-- Cleaning sources at K:/vcpkg/buildtrees/aom/src/2edfc9ae71-486f3907c9.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source K:/vcpkg/downloads/aom-9a83c6a5a55c176adbce740e47d3512edfc9ae71.tar.gz
-- Applying patch aom-rename-static.diff
-- Applying patch aom-uninitialized-pointer.diff
-- Applying patch aom-install.diff
-- Using source at K:/vcpkg/buildtrees/aom/src/2edfc9ae71-486f3907c9.clean
-- Configuring x86-windows-static
-- Building x86-windows-static-dbg
-- Building x86-windows-static-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: K:/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe --build . --config Release --target install -- -v -j1
    Working Directory: K:/vcpkg/buildtrees/aom/x86-windows-static-rel
    See logs for more information:
      K:\vcpkg\buildtrees\aom\install-x86-windows-static-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/aom/portfile.cmake:40 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building aom:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+aom
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[aom]+Build+error&body=Copy+issue+body+from+K%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

[install-x86-windows-static-rel-out.log](https://github.com/microsoft/vcpkg/files/11648348/install-x86-windows-static-rel-out.log)

**Comment by hiroyukki** [comment]
[install-x86-windows-static-rel-out.log](https://github.com/microsoft/vcpkg/files/11648345/install-x86-windows-static-rel-out.log)

**Comment by FrankXie05** [comment]
```
fatal error C1002: compiler is out of heap space in pass 2
```
Please make sure you have sufficient memory when running `vcpkg`. 
https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1002?view=msvc-170
Related issue: https://github.com/microsoft/vcpkg/issues/28389

**Comment by hiroyukki** [comment]
> Please make sure you have sufficient memory when running `vcpkg`.

Of course I do that, I reserved 32GB memory, it's exhausted, **aom:x86-windows-static** failed and aom:x64-windows-static ok.
I try install aom:x86-windows-static on 2 computers, sames problem occurred.

**Comment by gooxion** [comment]
Is anyone can help?

**Comment by FrankXie05** [comment]
@hiroyukki @gooxion 

Could you please try setting the number of parallels and adjusting the stack size?
`VCPKG_MAX_CONCURRENCY=1`
```
-DCMAKE_C_FLAGS="/Zm2000"
-DCMAKE_CXX_FLAGS="/Zm2000"
```
https://github.com/microsoft/vcpkg/issues/28389#issuecomment-1555426138

**Comment by hiroyukki** [comment]
> VCPKG_MAX_CONCURRENCY=1

yes I do this.


> ```
> -DCMAKE_C_FLAGS="/Zm2000"
> -DCMAKE_CXX_FLAGS="/Zm2000"
> ```

how can i set cmake flags in vcpkg command line? The command line is: **vcpkg install aom:x86-windows-static**

**Comment by FrankXie05** [comment]
>how can i set cmake flags in vcpkg command line?

This belongs to the environment variable. There are two methods in `PowerShell`:
1. Temporary (only for the currently open `PowerShell`):
```
$env: VCPKG_ MAX_ CONCURRENCY=1
```
2. Permanent:
```
[Environment]:: SetEnvironmentVariable ("VCPKG-MAX-CONCURRENCY", "1", "Machine")
```

After setting up, run `$env: VCPKG_ MAX_ CONCURRENCY` to verify if success.

**Comment by hiroyukki** [comment]
> This belongs to the environment variable. There are two methods in `PowerShell`:
> 
> 1. Temporary (only for the currently open `PowerShell`):
> 
> ```
> $env: VCPKG_ MAX_ CONCURRENCY=1
> ```
> 
> 2. Permanent:
> 
> ```
> [Environment]:: SetEnvironmentVariable ("VCPKG-MAX-CONCURRENCY", "1", "Machine")
> ```
> 
> After setting up, run `$env: VCPKG_ MAX_ CONCURRENCY` to verify if success.

I known how to set env vars, and I set it at first, I said that in the original post:
> ### Failure logs
> In order to install this module, I reserved 32GB memory, but it is still not enough. I tried reducing concurrent compilation by setting environment variable with `VCPKG_MAX_CONCURRENCY=1`, but it still didn't work. but `vcpkg install aom:x64-windows-static` seems ok.


What i need to know is how to set CMAKE_C_FLAGS in command line (or env var?), and whether it is affected on **vcpkg install**
> -DCMAKE_C_FLAGS="/Zm2000"
> -DCMAKE_CXX_FLAGS="/Zm2000"

I'm pretty sure everything ok in my environment, because I tried more than one environment to do this. In these evnironments, cl.exe cost more than 30GB memory (contains pagefile).
Maybe you can try **vcpkg install aom:x86-windows-static** in you environment.

**Comment by hiroyukki** [comment]
is this issues dead?

**Comment by FrankXie05** [comment]
>Maybe you can try vcpkg install aom:x86-windows-static in you environment.

This is a `community-triplet` , I do not have this environment and `VCPKG` currently does not support it.
Maybe you can use `x64-windows-static`. :)

**Comment by dg0yt** [comment]
> What i need to know is how to set CMAKE_C_FLAGS in command line (or env var?), and whether it is affected on **vcpkg install**
> 
> > -DCMAKE_C_FLAGS="/Zm2000"
> > -DCMAKE_CXX_FLAGS="/Zm2000"

You would need to set VCPKG_C_FLAGS etc. in the custom triplet file,
cf. https://learn.microsoft.com/en-us/vcpkg/users/triplets#vcpkg_cxx_flags
This can be even targeted at individual ports,
cf. https://learn.microsoft.com/en-us/vcpkg/users/triplets#per-port-customization.

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
