### ISSUE TITLE
[curl] x64 build fails with ninja error

### ISSUE THREAD

**Issue by jmin911** [Microsoft/vcpkg#3183]
When building [curl]:x64-windows-static, the build fails.  Building [curl]:x86-windows-static is OK.

Content of "C:\src\vcpkg\buildtrees\curl\install-x64-windows-static-dbg-err.log":
ninja: fatal: CreateProcess: The parameter is incorrect.

Screen output:

-- Configuring x64-windows-static done
-- Build x64-windows-static-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:136 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: C:/src/vcpkg/buildtrees/curl/x64-windows-static-dbg
    See logs for more information:
      C:\src\vcpkg\buildtrees\curl\install-x64-windows-static-dbg-out.log
      C:\src\vcpkg\buildtrees\curl\install-x64-windows-static-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/curl/portfile.cmake:96 (vcpkg_install_cmake)
  scripts/ports.cmake:72 (include)

**Comment by miurahr** [comment]
Duplicated with #1797  ?

**Comment by jmin911** [comment]
This seems to be fixed by CMake 3.11.1.
