### ISSUE TITLE
[pthreads] Build error

### ISSUE THREAD

**Issue by RylanVWVermeer** [microsoft/vcpkg#31837]
Package: pthreads[core]:x86-windows -> 3.0.0#14

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.32.31336.0
-    vcpkg-tool version: 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895
    vcpkg-scripts version: 662dbb50e 2023-06-02 (3 days ago)

**To Reproduce**

`vcpkg install libssh`

**Failure logs**

```
-- Using cached pthreads4w-code-v3.0.0.zip.
-- Cleaning sources at C:/dev/vcpkg/buildtrees/pthreads/src/49e541b66c-a9b0a36b2a.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/pthreads4w-code-v3.0.0.zip
-- Applying patch fix-arm-macro.patch
-- Applying patch fix-arm64-version_rc.patch
-- Applying patch fix-pthread_getname_np.patch
-- Applying patch fix-install.patch
-- Applying patch whitespace_in_path.patch
-- Applying patch use-md.patch
-- Using source at C:/dev/vcpkg/buildtrees/pthreads/src/49e541b66c-a9b0a36b2a.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/dev/vcpkg/buildtrees/pthreads/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\dev\vcpkg\buildtrees\pthreads\get-cmake-vars-x86-windows-dbg-CMakeCache.txt.log
      C:\dev\vcpkg\buildtrees\pthreads\get-cmake-vars-x86-windows-rel-CMakeCache.txt.log
      C:\dev\vcpkg\buildtrees\pthreads\get-cmake-vars-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:310 (vcpkg_execute_required_process)
  scripts/cmake/z_vcpkg_get_cmake_vars.cmake:18 (vcpkg_configure_cmake)
  scripts/cmake/vcpkg_build_nmake.cmake:46 (z_vcpkg_get_cmake_vars)
  scripts/cmake/vcpkg_install_nmake.cmake:52 (vcpkg_build_nmake)
  ports/pthreads/portfile.cmake:45 (vcpkg_install_nmake)
  scripts/ports.cmake:147 (include)
```
[get-cmake-vars-x86-windows-dbg-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/11655232/get-cmake-vars-x86-windows-dbg-CMakeCache.txt.log)
[get-cmake-vars-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/11655234/get-cmake-vars-x86-windows-out.log)
[get-cmake-vars-x86-windows-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/11655236/get-cmake-vars-x86-windows-rel-CMakeCache.txt.log)

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Did you install the following components in Visual Studio?
![image](https://github.com/microsoft/vcpkg/assets/94091114/d121e282-8a0d-4d25-9f89-095adae3d038)

**Comment by RylanVWVermeer** [comment]
> @RylanVWVermeer, could you please install windows sdk via VS installer, and try again?

I did not have the Windows 10 SDK installed, but I do now.  After retrying, I am still facing the same error, unfortunately.

**Comment by RylanVWVermeer** [comment]
I have now fully uninstalled Visual Studio 2022 Professional and reinstalled with these options:

![image](https://github.com/microsoft/vcpkg/assets/97973566/992eed3a-0c66-4a22-8749-824be0ac7e02)

After doing so, I get this result (sorry for the additional image, but it's not within `issue_body.md`:

![image](https://github.com/microsoft/vcpkg/assets/97973566/e2d43cbf-9e66-4bb8-913b-1b44d25dd9c6)

It certainly looks like the problem is CMake, so I will pursue that as a separate install.  I would happily entertain any other suggestions.

**Comment by RylanVWVermeer** [comment]
I just want to confirm this is the correct place the portable CMake in the output above should be finally extracted to:

![image](https://github.com/microsoft/vcpkg/assets/97973566/0bb21350-8d2a-4788-9f38-0970dd480e88)

**Comment by RylanVWVermeer** [comment]
After installing CMake from https://cmake.org/download/, I am still getting the same error.

I figure the get-cmake-vars logs will be helpful again, so I am attaching them here - I switched to the x64 triplet to see if I had any luck there.  I notice that there is no reference to Visual Studio pathing for the internal cache entries.  They are all pointing at the download above:

```//Path to CMake executable.
CMAKE_COMMAND:INTERNAL=C:/dev/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe
//Path to cpack program executable.
CMAKE_CPACK_COMMAND:INTERNAL=C:/dev/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cpack.exe
//Path to ctest program executable.
CMAKE_CTEST_COMMAND:INTERNAL=C:/dev/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/ctest.exe
```

I am not sure that's relevant as it points to VS's ninja.exe, but `windows-i386` certainly has a smell here.

[get-cmake-vars-x64-windows-dbg-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/11681033/get-cmake-vars-x64-windows-dbg-CMakeCache.txt.log)
[get-cmake-vars-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/11681034/get-cmake-vars-x64-windows-out.log)
[get-cmake-vars-x64-windows-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/11681037/get-cmake-vars-x64-windows-rel-CMakeCache.txt.log)

**Comment by LilyWangLL** [comment]
Thanks for your reply, please also install the following components.
![image](https://github.com/microsoft/vcpkg/assets/94091114/fff3b668-07a6-467d-a3c4-c648c9577a0d)

**Comment by LilyWangLL** [comment]
Pinging @RylanVWVermeer for response, does this issue resolved?

**Comment by RylanVWVermeer** [comment]
![image](https://github.com/microsoft/vcpkg/assets/97973566/008b85cc-3f15-490e-b22f-6452a714f532)

Unfortunately, after installing those 2 build tools, the problem still persists.

[get-cmake-vars-x86-windows-dbg-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/11805435/get-cmake-vars-x86-windows-dbg-CMakeCache.txt.log)
[get-cmake-vars-x86-windows-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/11805436/get-cmake-vars-x86-windows-rel-CMakeCache.txt.log)
[get-cmake-vars-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/11805450/get-cmake-vars-x86-windows-out.log)

**Comment by RylanVWVermeer** [comment]
@LilyWangLL, do you have any further suggestions?

**Comment by PhoebeHui** [comment]
Failures:
--mt=CMAKE_MT-NOTFOUND 

Hi @RylanVWVermeer, it looks mt.exe not found in your machine. However, you have installed windows SDK from the picture, Could you help double check?

1.Open x86 or x64 Native Tools command
2 where mt

For me:
![image](https://github.com/microsoft/vcpkg/assets/20694052/8ab82db8-a2e3-465d-880a-70f3aa1eb0fb)

**Comment by RylanVWVermeer** [comment]
You are absolutely correct that mt.exe isn't getting found.

![image](https://github.com/microsoft/vcpkg/assets/97973566/60c04eeb-8bc6-4191-b94e-6890aa759151)

**Comment by RylanVWVermeer** [comment]
However, it is at the path your output indicated (Directory of C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64):

![image](https://github.com/microsoft/vcpkg/assets/97973566/1e7b544a-adba-42e9-99ff-4e68f694bb6f)

I also have C:\Program Files (x86)\Windows Kits\10\bin\10.0.20348.0\x64, and mt.exe exists there as well.

**Comment by PhoebeHui** [comment]
It looks the windows SDK have something wrong in setup, could you uninstall all windows sdks and reinstall one of them by VS installer again, and try 'where mt' in x64 native command tool, if it shows mt.exe directory correctly, you can try to install pthreads via vcpkg again.

**Comment by RylanVWVermeer** [comment]
I have uninstalled each SDK and reinstalled them each by itself.  It is still not finding mt.exe.

**Comment by RylanVWVermeer** [comment]
After some more digging, I believe you're on to something with this.  There are multiple, potentially conflicting, mt.exe files on my system.  I am unsure where the 10.0.20348.0 version came from... possibly the .NET 7 SDK?  I installed that separately back when .NET 7 was new.  

Also, I see no set path in my environment variables for mt.exe.  Is that necessary as well?  I can add it if so.

**Comment by PhoebeHui** [comment]
We usually installed windows sdk by Visual Studio Installer, and do not need to set any extra window sdk enviroment variables again. now you have multiple versions and conflicts, if you don't need all of them, I recommand that install one of them.

>I see no set path in my environment variables for mt.exe. Is that necessary as well? I can add it if so.
>
I suspect it doesn't work even you set the environment variables for mt.exe,  you need to resolve windows sdk environment variables, mt.exe is just one of the tools, like rc.exe or midl.exe still need during the build.

**Comment by RylanVWVermeer** [comment]
I removed the .NET 7 SDK and modified my C# installation as well to not include the SDK involved there to limit my machine down to 10.0.19041.0 as the only version containing mt.exe.  That did not help.  I went so far as to uninstall then reinstall everything via the Visual Studio installer... again, and still my system does not find mt.exe.

I included it as an environment after all of that for the sake of it, but I still get no where.  I am happy to entertain any suggestions.

**Comment by PhoebeHui** [comment]
...\VC\Auxiliary\Build\vcvarsall.bat normally puts a Windows SDK in the PATH, it also reads related values from the registry, could you see if https://discourse.cmake.org/t/rc-rc-mt-cmake-mt-notfound/5089 helps?

**Comment by RylanVWVermeer** [comment]
I tried the workaround on the linked on the linked Visual Studio developer website (https://developercommunity.visualstudio.com/t/resource-compiler-rcexe-is-not-recognized-as-an-in/1676970) by explicitly stating where the Windows SDK is, and I am now facing this error from the file you mentioned:

![image](https://github.com/microsoft/vcpkg/assets/97973566/b964573c-517c-4497-a5d5-72cceab3f595)

**Comment by RylanVWVermeer** [comment]
And yes, registry editing is blocked at my company.  I am also pursuing an avenue to get registry editing allowed on my machine.

**Comment by PhoebeHui** [comment]
> And yes, registry editing is blocked at my company. I am also pursuing an avenue to get registry editing allowed on my machine.

@RylanVWVermeer, sorry for my lately response,  have you solved the enviroment issue finally?

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
