### ISSUE TITLE
[boost-vcpkg-helpers] Build error

### ISSUE THREAD

**Issue by LightForU** [microsoft/vcpkg#31846]
error: building boost-vcpkg-helpers:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.

**Comment by JonLiu1993** [comment]
@LightForU, Thanks for posting this issue, please provide your reproduction environment, `windows10` or `windows11`? VS version？and provide your error log.

**Comment by JonLiu1993** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!

**Comment by mike192025** [comment]
got fixed after downloading from within Visual Studio Installer
1st.   Visual Studio Installer  ->  Desktop Development with C++  ->  C++ CMake tools for Windows
2nd.  Visual Studio Installer  ->  Universal Windows: Platform build tools

Download at least both otherwise other build errors emerge!
