### ISSUE TITLE
[cryptopp] Pem-pack not being compiled in when selected as an option

### ISSUE THREAD

**Issue by grafster** [microsoft/vcpkg#31849]
**Host Environment**

Host: x64-windows
Compiler: MSVC 19.36.32532
vcpkg-tool version: 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895

**To Reproduce**

vcpkg install cryptopp[pem-pack]

Then inspect the .lib file produced with dumpbin. It does not contain PEM_Load etc

dumpbin /all cryptopp-static.lib |findstr PEM_Load

Looking at the portfile.cmake file, it looks like it's been changed to copy the PEM pack headers to the destination but it's not including the source flies from the pem pack into the library.

**Comment by grafster** [comment]
Having delved into this one a bit more, it seems like it might be a change in the cryptopp-cmake project https://github.com/abdes/cryptopp-cmake that means that it's not picking up the PEM Pack files when they are copied across to the main source directory

**Comment by Adela0814** [comment]
Could you please submit an issue to the upstream?

**Comment by SpaceCheetah** [comment]
abdes/cryptopp-cmake#108 fixes this in upstream, so it can be fixed here. They added the CRYPTOPP_USE_PEM_PACK cmake option to enable it.
