### ISSUE TITLE
[pthreads] Build error

### ISSUE THREAD

**Issue by qn757275373** [microsoft/vcpkg#31852]
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: F:/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe F:/vcpkg/buildtrees/colmap/src/b221bdabb2-a77d7326e5.clean -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=F:/vcpkg/packages/colmap_x64-windows/debug -DFETCHCONTENT_FULLY_DISCONNECTED=ON -DCUDA_ENABLED=ON -DCMAKE_CUDA_ARCHITECTURES=native -DTESTS_ENABLED=ON -DGIT_COMMIT_ID=30da037ce19bdceb6d239c45342fadb221bdabb2 -DGIT_COMMIT_DATE=2023-06-07 -DOPENMP_ENABLED=ON "-DCMAKE_MAKE_PROGRAM=C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -DBUILD_SHARED_LIBS=ON -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=F:/vcpkg/scripts/toolchains/windows.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=v143 -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=F:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=F:/vcpkg -D_VCPKG_INSTALLED_DIR=F:/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF
    Working Directory: F:/vcpkg/buildtrees/colmap/x64-windows-dbg
    Error code: 1
    See logs for more information:
      F:\vcpkg\buildtrees\colmap\config-x64-windows-dbg-CMakeCache.txt.log
      F:\vcpkg\buildtrees\colmap\config-x64-windows-dbg-out.log
      F:\vcpkg\buildtrees\colmap\config-x64-windows-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:263 (vcpkg_execute_required_process)
  ports/colmap/portfile.cmake:49 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please provide the error log:
```
F:\vcpkg\buildtrees\colmap\config-x64-windows-dbg-CMakeCache.txt.log
F:\vcpkg\buildtrees\colmap\config-x64-windows-dbg-out.log
F:\vcpkg\buildtrees\colmap\config-x64-windows-dbg-err.log
```

**Comment by LilyWangLL** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
