### ISSUE TITLE
[Linking] Static Linking still produces .dll Files

### ISSUE THREAD

**Issue by Uhrwerk7** [Microsoft/vcpkg#3187]
Hello, 

I've installed the cpprestsdk in x64-windows-static Mode and in the Property Globals in my Project.vcxproj, I did set the triplet to x64-windows-static. When building, there are still 6 .dll's generated in my Project Folder. 

![Image](https://i.imgur.com/kcGA85G.png)

I even tried explicitly deleting the "normal" x64-windows (non-static) folders from vcpkg/installed, and then building just fails. Is there something else you need todo to get static linking to work or this an issue with cpprestsdk?

**Comment by ras0219-msft** [comment]
Hi @Uhrwerk7,

This definitely sounds like the x64-windows triplet is getting selected for your project. If you set the MSBuild verbosity to Normal or higher [1], we'll output a message saying which vcpkg triplet was selected.

Did you make sure to follow the integration documentation[2] and put the settings inside the `"Globals"` PropertyGroup?

[1] https://blogs.msdn.microsoft.com/saraford/2008/10/07/did-you-know-you-can-configure-the-msbuild-verbosity-in-the-output-window-329/
[2] https://github.com/Microsoft/vcpkg/blob/master/docs/users/integration.md#with-msbuild

**Comment by Uhrwerk7** [comment]
Hello @ras0219-msft 

Thanks for your Answer. I set the MSBuild verbosity to Normal. 
1>Target VcpkgTripletSelection:
1>  Using triplet "x64-windows-static" from "C:\Development\vcpkg\installed\x64-windows-static\"

This is the output error log: 
`1>Build FAILED.
1>
1>networking.obj : warning LNK4217: locally defined symbol ??0value@json@web@@QEAA@XZ (public: __cdecl web::json::value::value(void)) imported in function "public: __cdecl Concurrency::details::_ResultHolder<class web::json::value>::_ResultHolder<class web::json::value>(void)" (??0?$_ResultHolder@Vvalue@json@web@@@details@Concurrency@@QEAA@XZ)
1>networking.obj : warning LNK4217: locally defined symbol ??0value@json@web@@QEAA@AEBV012@@Z (public: __cdecl web::json::value::value(class web::json::value const &)) imported in function "public: class web::json::value __cdecl Concurrency::details::_ResultHolder<class web::json::value>::Get(void)" (?Get@?$_ResultHolder@Vvalue@json@web@@@details@Concurrency@@QEAA?AVvalue@json@web@@XZ)
1>networking.obj : warning LNK4217: locally defined symbol ??4value@json@web@@QEAAAEAV012@AEBV012@@Z (public: class web::json::value & __cdecl web::json::value::operator=(class web::json::value const &)) imported in function "public: void __cdecl Concurrency::details::_ResultHolder<class web::json::value>::Set(class web::json::value const &)" (?Set@?$_ResultHolder@Vvalue@json@web@@@details@Concurrency@@QEAAXAEBVvalue@json@web@@@Z)
1>networking.obj : warning LNK4217: locally defined symbol ??0uri@web@@QEAA@PEB_W@Z (public: __cdecl web::uri::uri(wchar_t const *)) imported in function "public: struct reesecheats::loader::networking::Authentification __cdecl reesecheats::loader::networking::Networker::Authenticate(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?Authenticate@Networker@networking@loader@reesecheats@@QEAA?AUAuthentification@234@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z)
1>networking.obj : warning LNK4217: locally defined symbol ??0http_msg_base@details@http@web@@QEAA@XZ (public: __cdecl web::http::details::http_msg_base::http_msg_base(void)) imported in function "public: __cdecl web::http::details::_http_response::_http_response(unsigned short)" (??0_http_response@details@http@web@@QEAA@G@Z)
1>networking.obj : warning LNK4217: locally defined symbol ?_extract_json@http_msg_base@details@http@web@@QEAA?AVvalue@json@4@_N@Z (public: class web::json::value __cdecl web::http::details::http_msg_base::_extract_json(bool)) imported in function "public: class web::json::value __cdecl <lambda_07dca83f9489825032bd549be3168602>::operator()(unsigned __int64)const " (??R<lambda_07dca83f9489825032bd549be3168602>@@QEBA?AVvalue@json@web@@_K@Z)
1>networking.obj : warning LNK4217: locally defined symbol ??0_http_request@details@http@web@@QEAA@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z (public: __cdecl web::http::details::_http_request::_http_request(class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> >)) imported in function "public: __cdecl std::_Ref_count_obj<class web::http::details::_http_request>::_Ref_count_obj<class web::http::details::_http_request><class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > >(class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > &&)" (??$?0V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@?$_Ref_count_obj@V_http_request@details@http@web@@@std@@QEAA@$$QEAV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@1@@Z)
1>networking.obj : warning LNK4049: locally defined symbol ?GET@methods@http@web@@2V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@B (public: static class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const web::http::methods::GET) imported
1>networking.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl web::http::client::http_client::http_client(class web::uri const &)" (__imp_??0http_client@client@http@web@@QEAA@AEBVuri@3@@Z) referenced in function "public: struct reesecheats::loader::networking::Authentification __cdecl reesecheats::loader::networking::Networker::Authenticate(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?Authenticate@Networker@networking@loader@reesecheats@@QEAA?AUAuthentification@234@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z)
1>networking.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl web::http::client::http_client::~http_client(void)" (__imp_??1http_client@client@http@web@@QEAA@XZ) referenced in function "public: struct reesecheats::loader::networking::Authentification __cdecl reesecheats::loader::networking::Networker::Authenticate(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?Authenticate@Networker@networking@loader@reesecheats@@QEAA?AUAuthentification@234@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z)
1>networking.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class Concurrency::task<class web::http::http_response> __cdecl web::http::client::http_client::request(class web::http::http_request,class Concurrency::cancellation_token const &)" (__imp_?request@http_client@client@http@web@@QEAA?AV?$task@Vhttp_response@http@web@@@Concurrency@@Vhttp_request@34@AEBVcancellation_token@6@@Z) referenced in function "public: class Concurrency::task<class web::http::http_response> __cdecl web::http::client::http_client::request(class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class Concurrency::cancellation_token const &)" (?request@http_client@client@http@web@@QEAA?AV?$task@Vhttp_response@http@web@@@Concurrency@@AEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@AEBVcancellation_token@6@@Z)
1>C:\Reversing\Generous\Loader\Build\Debug\x64\Loader.exe : fatal error LNK1120: 3 unresolved externals`

It seems like the static library is trying to import from a .dll file ("__declspec(dllimport)").

**Comment by Uhrwerk7** [comment]
Hello @ras0219-msft,

Where you able to make any progress on this issue? I manually compiled the cpprestsdk now, which is working, but an automatic solution would be preferable for the future :-)

**Comment by JackBoosY** [comment]
Hi @Uhrwerk7 , thanks for reporting this issue!
I think this issue has been fixed. I checked it.
Thx.
