### ISSUE TITLE
[boost-build] Build error

### ISSUE THREAD

**Issue by iskiselev** [microsoft/vcpkg#31883]
Package: boost-build[core]:x64-linux -> 1.82.0#1

**Host Environment**

- Host: x64-linux
- Compiler: Clang 16.0.4
-    vcpkg-tool version: 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895
    vcpkg-scripts version: d163f9d5f 2023-05-10 (4 weeks ago)

**To Reproduce**

`vcpkg install `

**Failure logs**

```
-- Using cached boostorg-build-boost-1.82.0.tar.gz.
-- Extracting source /mnt/c/VSExclude/agent-dotnet-3/vcpkg/downloads/boostorg-build-boost-1.82.0.tar.gz
-- Applying patch 0002-fix-get-version.patch
-- Applying patch 0003-fix-emscripten.patch
-- Applying patch 0004-workaround-MSVC-codegen-bug-in-17.5-on-ARM64.patch
-- Using source at /mnt/c/VSExclude/agent-dotnet-3/vcpkg/buildtrees/boost-build/src/ost-1.82.0-e88c66a4cd.clean
-- Using cached boost_LICENSE_1_0.txt.
-- Using cached boost-1.82.0-boostcpp.jam.
-- Installing: /mnt/c/VSExclude/agent-dotnet-3/vcpkg/packages/boost-build_x64-linux/share/boost-build/copyright
-- Bootstrapping...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /mnt/c/VSExclude/agent-dotnet-3/vcpkg/packages/boost-build_x64-linux/tools/boost-build/bootstrap.sh
    Working Directory: /mnt/c/VSExclude/agent-dotnet-3/vcpkg/packages/boost-build_x64-linux/tools/boost-build
    Error code: 1
    See logs for more information:
      /mnt/c/VSExclude/agent-dotnet-3/vcpkg/buildtrees/boost-build/bootstrap-x64-linux-out.log
      /mnt/c/VSExclude/agent-dotnet-3/vcpkg/buildtrees/boost-build/bootstrap-x64-linux-err.log

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:71 (vcpkg_execute_required_process)
  scripts/ports.cmake:147 (include)



```
<details><summary>/mnt/c/VSExclude/agent-dotnet-3/vcpkg/buildtrees/boost-build/bootstrap-x64-linux-out.log</summary>

```
Building the B2 engine..

###
###
### Using 'cxx' toolset.
###
###

cpp (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


###
###

> cpp -DNDEBUG builtins.cpp class.cpp command.cpp compile.cpp constants.cpp cwd.cpp debug.cpp debugger.cpp execcmd.cpp execnt.cpp execunix.cpp filesys.cpp filent.cpp fileunix.cpp frames.cpp function.cpp glob.cpp hash.cpp hcache.cpp hdrmacro.cpp headers.cpp jam_strings.cpp jam.cpp jamgram.cpp lists.cpp make.cpp make1.cpp md5.cpp mem.cpp modules.cpp native.cpp object.cpp option.cpp output.cpp parse.cpp pathnt.cpp pathsys.cpp pathunix.cpp regexp.cpp rules.cpp scan.cpp search.cpp startup.cpp subst.cpp sysinfo.cpp timestamp.cpp variable.cpp w32_getreg.cpp modules/order.cpp modules/path.cpp modules/property-set.cpp modules/regex.cpp modules/sequence.cpp modules/set.cpp -o b2
```
</details>
<details><summary>/mnt/c/VSExclude/agent-dotnet-3/vcpkg/buildtrees/boost-build/bootstrap-x64-linux-err.log</summary>

```
cpp: fatal error: too many input files
compilation terminated.
Failed to build the B2 engine.
```
</details>

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "dependencies": [
    "boost-algorithm",
    "boost-asio",
    "boost-chrono",
    "boost-dll",
    "boost-filesystem",
    "boost-function",
    "boost-interprocess",
    "boost-locale",
    "boost-smart-ptr",
    "boost-move",
    "boost-predef",
    "boost-property-tree",
    "boost-ptr-container",
    "boost-thread",
    "boost-unordered",
    "boost-core",
    "boost-foreach",
    "boost-format",
    "boost-lexical-cast",
    "boost-log",
    "boost-phoenix",
    "boost-regex",
    "boost-container",
    "boost-container-hash",
    "boost-lockfree",
    "boost-optional",
    "boost-accumulators",
    "boost-circular-buffer",
    "boost-test",
    "protobuf"
  ],
  "vcpkg-configuration": {
    "overlay-ports": [
      "../build_scripts/vcpkg-overlay/ports"
    ],
    "overlay-triplets": [
      "../build_scripts/vcpkg-overlay/triplets"
    ]
  }
}

```
</details>

The issue happens on linux, where compiler provided though CC / CXX environment variables (in my case, it is clang-16 / clang++-16). But that compiler is not passed into boos-build bootstrap. I can workaround issue by adding ` --cxx=$ENV{CXX}` to [boost-build\portfile.cmake line 73.](https://github.com/microsoft/vcpkg/blob/master/ports/boost-build/portfile.cmake#L72).
Looks like there is an error in boost build around https://github.com/boostorg/build/blob/7ee3b0dfa2905b439ca458ab1fcd514adfb9b444/src/engine/build.sh#L285 - per comment, it should use CXX, but B2_CXX_OPT at that point would be empty.

**Comment by FrankXie05** [comment]
I think `B2` wants `gcc` more than `clang`. `-std=c++11`

**Comment by iskiselev** [comment]
It is not about `-std=c++11` or gcc vs clang. It works for me, if I do `COMMAND "${CURRENT_PACKAGES_DIR}/tools/boost-build/bootstrap.sh" --cxx=clang++-16` (or `--cxx=$ENV{CXX}` in my case).
Currently, if CXX is not standard (that can come from toolset or environment variable), it should be passed into bootstrap.sh - which, can also be a bug in boost-build itself.

**Comment by iskiselev** [comment]
Looks that b2 bootstrap.sh will use CXX environment variable only if it is explicitly asked about it: `"${CURRENT_PACKAGES_DIR}/tools/boost-build/bootstrap.sh" cxx`. I'm still not sure what should be passed inside from VCPKG - as it should path same compiler, used in other libraries builds.

**Comment by FrankXie05** [comment]
If manual input is useful, we need to modify the `bootstrap.sh` again.

**Comment by iskiselev** [comment]
@FrankXie05 , currently it is not detecting clang when clang with version suffix is used. It most probably will work if just `clang++` is available, but is not working when `clang++-16` only available.
And, honestly, vcpkg should use compiler configured with host triplet (or CXX environment variable) - and not try to guess best toolchain.
It may be good idea even always set cxx (and corresponding environment variables) and pass cxx argument to sh.

**Comment by iskiselev** [comment]
@FrankXie05, is there anything I can help reproduce the issue or advice what should be proper fix?
