### ISSUE TITLE
[libusb] Build error

### ISSUE THREAD

**Issue by laojunyan2003** [microsoft/vcpkg#31882]
### i use ubuntu 22.04 ,to vcpkg  install the realsen2 ,but fail 
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/autoreconf -vfi
    Working Directory: /home/pinkykiller/ws/vcpkg/buildtrees/libusb/src/89f6f14e8a-1dccf18d37.clean/
    Error code: 1
    See logs for more information:
      /home/pinkykiller/ws/vcpkg/buildtrees/libusb/autoconf-x64-linux-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:630 (vcpkg_execute_required_process)
  ports/libusb/portfile.cmake:58 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)


error: building libusb:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libusb
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[libusb]+Build+error&body=Copy+issue+body+from+%2Fhome%2Fpinkykiller%2Fws%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
```

**Comment by jimwang118** [comment]
Please provide log details. `/home/pinkykiller/ws/vcpkg/buildtrees/libusb/autoconf-x64-linux-err.log`

**Comment by pushan2001** [comment]
<pre>linux-err.log
autoreconf: export WARNINGS=
autoreconf: Entering directory &apos;.&apos;
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
aclocal: warning: couldn&apos;t open directory &apos;m4&apos;: No such file or directory
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:23: installing &apos;./compile&apos;
configure.ac:26: installing &apos;./install-sh&apos;
configure.ac:26: installing &apos;./missing&apos;
Makefile.am: installing &apos;./INSTALL&apos;
examples/Makefile.am: installing &apos;./depcomp&apos;
libusb/Makefile.am:6: error: Libtool library used but &apos;LIBTOOL&apos; is undefined
libusb/Makefile.am:6:   The usual way to define &apos;LIBTOOL&apos; is to add &apos;LT_INIT&apos;
libusb/Makefile.am:6:   to &apos;configure.ac&apos; and run &apos;aclocal&apos; and &apos;autoconf&apos; again.
libusb/Makefile.am:6:   If &apos;LT_INIT&apos; is in &apos;configure.ac&apos;, make sure
libusb/Makefile.am:6:   its definition is in aclocal&apos;s search path.
autoreconf: error: automake failed with exit status: 1
</pre>

The person above and i seem to have the exact same issue and the same error message. This is what I have in the autoconf error log.

**Comment by dg0yt** [comment]
This is my version, from a successfull build:
~~~
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
aclocal: warning: couldn't open directory 'm4': No such file or directory
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:23: installing './compile'
configure.ac:27: installing './config.guess'
configure.ac:27: installing './config.sub'
configure.ac:26: installing './install-sh'
configure.ac:26: installing './missing'
Makefile.am: installing './INSTALL'
examples/Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'
~~~
A key difference is that my system offers `libtoolize`. Please install the system package which provides the tool (Ubuntu: `libtool`).

**Comment by jimwang118** [comment]
Is the issue solved after installing the system package?

**Comment by pushan2001** [comment]
Oh. Yes the issue is solved for me.
