### ISSUE TITLE
[bzip2] Build error

### ISSUE THREAD

**Issue by SigmaAdrich** [microsoft/vcpkg#31885]
Package: bzip2[core,tool]:x64-mingw-static -> 1.0.8#4

**Host Environment**

- Host: x64-windows
- Compiler: GNU 8.1.0
-    vcpkg-tool version: 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895
    vcpkg-scripts version: 1e334d770 2023-06-07 (12 hours ago)

**To Reproduce**

`vcpkg install wxwidgets:x64-mingw-static`

**Failure logs**

```
-- Using cached bzip2-1.0.8.tar.gz.
-- Cleaning sources at C:/Users/xp/.clion-vcpkg/vcpkg/buildtrees/bzip2/src/bzip2-1-336d4794a3.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/xp/.clion-vcpkg/vcpkg/downloads/bzip2-1.0.8.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Using source at C:/Users/xp/.clion-vcpkg/vcpkg/buildtrees/bzip2/src/bzip2-1-336d4794a3.clean
CMake Error at ports/bzip2/portfile.cmake:21 (vcpkg_cmake_configure):
  Unknown CMake command "vcpkg_cmake_configure".
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)



```

**Additional context**

**Comment by dg0yt** [comment]
First guess: Run `vcpkg upgrade --no-dry-run` to update the installed ports.

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
