### ISSUE TITLE
[<realsense2>] build failure

### ISSUE THREAD

**Issue by laojunyan2003** [microsoft/vcpkg#31884]
### Operating system

ubuntu22.04

### Steps to reproduce the behavior

```Shell
./vcpkg install relsense2
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
  * libusb[core]:x64-linux -> 1.0.26.11791
    realsense2[core]:x64-linux -> 2.53.1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Restored 0 package(s) from /home/pinkykiller/.cache/vcpkg/archives in 9.5 us. Use --debug to see more details.
Installing 1/2 libusb:x64-linux...
Building libusb[core]:x64-linux...
libusb currently requires the following tools and libraries from the system package manager:
    autoreconf
    libudev

These can be installed on Ubuntu systems via apt-get install autoreconf libudev-dev
-- Using cached libusb-libusb-fcf0c710ef5911ae37fbbf1b39d48a89f6f14e8a.tar.gz.
-- Cleaning sources at /home/pinkykiller/.clion-vcpkg/vcpkg/buildtrees/libusb/src/89f6f14e8a-1dccf18d37.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/pinkykiller/.clion-vcpkg/vcpkg/downloads/libusb-libusb-fcf0c710ef5911ae37fbbf1b39d48a89f6f14e8a.tar.gz
-- Using source at /home/pinkykiller/.clion-vcpkg/vcpkg/buildtrees/libusb/src/89f6f14e8a-1dccf18d37.clean
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Generating configure for x64-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/autoreconf -vfi
    Working Directory: /home/pinkykiller/.clion-vcpkg/vcpkg/buildtrees/libusb/src/89f6f14e8a-1dccf18d37.clean/
    Error code: 1
    See logs for more information:
      /home/pinkykiller/.clion-vcpkg/vcpkg/buildtrees/libusb/autoconf-x64-linux-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:630 (vcpkg_execute_required_process)
  ports/libusb/portfile.cmake:58 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)

error: building libusb:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libusb
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[libusb]+Build+error&body=Copy+issue+body+from+%2Fhome%2Fpinkykiller%2F.clion-vcpkg%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by JonLiu1993** [comment]
@laojunyan2003, Thanks for posting this issue, please provide your error log:
````
/home/pinkykiller/.clion-vcpkg/vcpkg/buildtrees/libusb/autoconf-x64-linux-err.log
````

**Comment by JonLiu1993** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
