### ISSUE TITLE
[libjpeg-turbo] build failure

### ISSUE THREAD

**Issue by wulabaquan** [microsoft/vcpkg#31903]
### Operating system

Win10 x64

### Compiler

MSVC 2013

### Steps to reproduce the behavior

```Shell
$ ./vcpkg.exe install opencv2 --triplet=x86-windows-v120
```

### Failure logs

$ ./vcpkg.exe install opencv2 --triplet=x86-windows-v120
Computing installation plan...
The following packages will be built and installed:
  * libjpeg-turbo[core]:x86-windows-v120 -> 2.1.5.1#1
  * liblzma[core]:x86-windows-v120 -> 5.4.1#1
  * libpng[core]:x86-windows-v120 -> 1.6.39#1
    opencv2[core,default-features,eigen,jpeg,png,tiff]:x86-windows-v120 -> 2.4.13.7#18
  * tiff[core,jpeg,lzma,zip]:x86-windows-v120 -> 4.5.0#3
  * zlib[core]:x86-windows-v120 -> 1.2.13
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows-v120...
Restored 0 package(s) from C:\Users\xcy\AppData\Local\vcpkg\archives in 522.8 us. Use --debug to see more details.
Installing 1/6 libjpeg-turbo:x86-windows-v120...
Building libjpeg-turbo[core]:x86-windows-v120...
warning: -- Using community triplet x86-windows-v120. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: D:\xcy\vcpkg\vcpkg\triplets\community\x86-windows-v120.cmake
-- Using cached libjpeg-turbo-libjpeg-turbo-2.1.5.1.tar.gz.
-- Cleaning sources at D:/xcy/vcpkg/vcpkg/buildtrees/libjpeg-turbo/src/2.1.5.1-f411453282.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/xcy/vcpkg/vcpkg/downloads/libjpeg-turbo-libjpeg-turbo-2.1.5.1.tar.gz
-- Applying patch add-options-for-exes-docs-headers.patch
-- Applying patch workaround_cmake_system_processor.patch
-- Using source at D:/xcy/vcpkg/vcpkg/buildtrees/libjpeg-turbo/src/2.1.5.1-f411453282.clean
-- Configuring x86-windows-v120
-- Building x86-windows-v120-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: D:/xcy/vcpkg/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j57
    Working Directory: D:/xcy/vcpkg/vcpkg/buildtrees/libjpeg-turbo/x86-windows-v120-dbg
    See logs for more information:
      D:\xcy\vcpkg\vcpkg\buildtrees\libjpeg-turbo\install-x86-windows-v120-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/libjpeg-turbo/portfile.cmake:56 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building libjpeg-turbo:x86-windows-v120 failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libjpeg-turbo
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libjpeg-turbo]+Build+error
Include '[libjpeg-turbo] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-03-01-538539c4e364dd6f14f5e36f6704144254845159
    vcpkg-scripts version: 638b1588b 2023-06-08 (11 hours ago)

Please use the prefilled template from D:\xcy\vcpkg\vcpkg\installed\vcpkg\issue_body.md when reporting your issue.

### Additional context

[install-x86-windows-v120-dbg-out.log](https://github.com/microsoft/vcpkg/files/11702386/install-x86-windows-v120-dbg-out.log)

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
