### ISSUE TITLE
[x264] Fail to build x264:arm64ec-windows but arm64-windows is passed.

### ISSUE THREAD

**Issue by shijunz** [microsoft/vcpkg#31904]
C:\tools\vcpkg>vcpkg install x264:arm64ec-windows
Computing installation plan...
The following packages will be built and installed:
    x264[core,default-features]:arm64ec-windows -> 0.164.3095#4
Detecting compiler hash for triplet arm64ec-windows...
Restored 0 package(s) from C:\Users\shijunz\AppData\Local\vcpkg\archives in 180 us. Use --debug to see more details.
Installing 1/1 x264:arm64ec-windows...
Building x264[core,default-features]:arm64ec-windows...
warning: -- Using community triplet arm64ec-windows. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\tools\vcpkg\triplets\community\arm64ec-windows.cmake
-- Using cached mirror-x264-baee400fa9ced6f5481a728138fed6e867b0ff7f.tar.gz.
-- Cleaning sources at C:/tools/vcpkg/buildtrees/x264/src/e867b0ff7f-fb2486f1d0.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/tools/vcpkg/downloads/mirror-x264-baee400fa9ced6f5481a728138fed6e867b0ff7f.tar.gz
-- Applying patch uwp-cflags.patch
-- Applying patch parallel-install.patch
-- Applying patch allow-clang-cl.patch
-- Applying patch configure-as.patch
-- Using source at C:/tools/vcpkg/buildtrees/x264/src/e867b0ff7f-fb2486f1d0.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for arm64ec-windows
-- Getting CMake variables for arm64ec-windows
-- Using cached msys2-autoconf-wrapper-20221207-1-any.pkg.tar.zst.
-- Using cached msys2-automake-wrapper-20221207-1-any.pkg.tar.zst.
-- Using cached msys2-binutils-2.40-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libtool-2.4.7-3-x86_64.pkg.tar.zst.
-- Using cached msys2-make-4.4.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-pkgconf-1.9.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-which-2.21-4-x86_64.pkg.tar.zst.
-- Using cached msys2-bash-5.2.015-1-x86_64.pkg.tar.zst.
-- Using cached msys2-coreutils-8.32-5-x86_64.pkg.tar.zst.
-- Using cached msys2-file-5.44-5-x86_64.pkg.tar.zst.
-- Using cached msys2-gawk-5.2.1-2-x86_64.pkg.tar.zst.
-- Using cached msys2-grep-1~3.0-6-x86_64.pkg.tar.zst.
-- Using cached msys2-gzip-1.12-2-x86_64.pkg.tar.zst.
-- Using cached msys2-diffutils-3.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-sed-4.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using cached msys2-autoconf2.71-2.71-1-any.pkg.tar.zst.
-- Using cached msys2-automake1.16-1.16.5-1-any.pkg.tar.zst.
-- Using cached msys2-libiconv-1.17-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libintl-0.21-2-x86_64.pkg.tar.zst.
-- Using cached msys2-zlib-1.2.13-1-x86_64.pkg.tar.zst.
-- Using cached msys2-tar-1.34-3-x86_64.pkg.tar.zst.
-- Using cached msys2-findutils-4.9.0-3-x86_64.pkg.tar.zst.
-- Using cached msys2-gmp-6.2.1-2-x86_64.pkg.tar.zst.
-- Using cached msys2-gcc-libs-11.3.0-3-x86_64.pkg.tar.zst.
-- Using cached msys2-libbz2-1.0.8-4-x86_64.pkg.tar.zst.
-- Using cached msys2-liblzma-5.4.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libzstd-1.5.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libreadline-8.2.001-3-x86_64.pkg.tar.zst.
-- Using cached msys2-mpfr-4.2.0-2-x86_64.pkg.tar.zst.
-- Using cached msys2-libpcre-8.45-3-x86_64.pkg.tar.zst.
-- Using cached msys2-m4-1.4.19-2-x86_64.pkg.tar.zst.
-- Using cached msys2-perl-5.36.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-ncurses-6.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libcrypt-2.1-4-x86_64.pkg.tar.zst.
-- Using msys root at C:/tools/vcpkg/downloads/tools/msys2/d7266db249278763
CMake Error at scripts/cmake/vcpkg_configure_make.cmake:34 (message):
  Unsupported VCPKG_TARGET_ARCHITECTURE architecture arm64ec in
  z_vcpkg_determine_autotools_target_cpu!
Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:310 (z_vcpkg_determine_autotools_target_cpu)
  ports/x264/portfile.cmake:96 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)

error: building x264:arm64ec-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+x264
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[x264]+Build+error&body=Copy+issue+body+from+C%3A%2Ftools%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by dg0yt** [comment]
If you know the autotools triplet for arm64ec windows, you can add
~~~cmake
set(VCPKG_MAKE_BUILD_TRIPLET <autotools tripet>)
~~~
to your custom triplet file.

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.

**Comment by Nick7K** [comment]
Has anyone resolved this?

**Comment by shijunz** [comment]
diff --git a/scripts/cmake/vcpkg_configure_make.cmake b/scripts/cmake/vcpkg_configure_make.cmake
index 73d94f956..ee4495f1b 100644
--- a/scripts/cmake/vcpkg_configure_make.cmake
+++ b/scripts/cmake/vcpkg_configure_make.cmake
@@ -30,6 +30,8 @@ macro(z_vcpkg_determine_autotools_target_cpu out_var)
        set(${out_var} aarch64)
    elseif(VCPKG_TARGET_ARCHITECTURE MATCHES "^(ARM|arm)$")
        set(${out_var} arm)
+    elseif(VCPKG_TARGET_ARCHITECTURE MATCHES "^(ARM|arm)64ec$")^M
+        set(${out_var} arm64ec)^M
    else()
        message(FATAL_ERROR "Unsupported VCPKG_TARGET_ARCHITECTURE architecture ${VCPKG_TARGET_ARCHITECTURE} in z_vcpkg_determine_autotools_target_cpu!" )
    endif()

**Comment by shijunz** [comment]
> Has anyone resolved this?

could you try it?

diff --git a/scripts/cmake/vcpkg_configure_make.cmake b/scripts/cmake/vcpkg_configure_make.cmake
index 73d94f956..ee4495f1b 100644
--- a/scripts/cmake/vcpkg_configure_make.cmake
+++ b/scripts/cmake/vcpkg_configure_make.cmake
@@ -30,6 +30,8 @@ macro(z_vcpkg_determine_autotools_target_cpu out_var)
        set(${out_var} aarch64)
    elseif(VCPKG_TARGET_ARCHITECTURE MATCHES "^(ARM|arm)$")
        set(${out_var} arm)
+    elseif(VCPKG_TARGET_ARCHITECTURE MATCHES "^(ARM|arm)64ec$")^M
+        set(${out_var} arm64ec)^M
    else()
        message(FATAL_ERROR "Unsupported VCPKG_TARGET_ARCHITECTURE architecture ${VCPKG_TARGET_ARCHITECTURE} in z_vcpkg_determine_autotools_target_cpu!" )
    endif()
