### ISSUE TITLE
[libjpeg-turbo] jpeglib.h(1122,10): fatal error C1083: Cannot open include file: 'jpegint.h'

### ISSUE THREAD

**Issue by malaterre** [microsoft/vcpkg#31913]
### Is your feature request related to a problem? Please describe.

libjpeg-turbo current port install the "jpeglib.h" header. In some case (advanced users) we want to use the entire API. In particular:

```
$ head -n 1122 ./vcpkg_installed/x64-windows-static/include/jpeglib.h | tail -1
#include "jpegint.h"            /* fetch private declarations */
```

Would you be able to also install "jpegint.h" next to jpeglib.h

### Proposed solution

install "jpegint.h" next to jpeglib.h

### Describe alternatives you've considered

I could copy/paste portion of interest "jpegint.h" in my application but that is difficult to maintain.

### Additional context

You may want to have a peak look at transupp.c source code:

* https://github.com/cloudflare/jpegtran/blob/master/transupp.c#L18-L21

**Comment by MonicaLiu0311** [comment]
So upstream clearly says no: https://github.com/libjpeg-turbo/libjpeg-turbo/pull/695#issuecomment-1591383190
