### ISSUE TITLE
[Protobuf]    Protobuf 3.21.12  Link Error:  libprotobuf.dll : fatal error LNK1107

### ISSUE THREAD

**Issue by yulinxx** [microsoft/vcpkg#31916]
**Describe the bug**
When I use  **protobuf 3.19.4** + **pencv  4.5.5**      
everything is OK, 

but  when  install  protobuf to 3.21.12, 
and opencv upgrade from 4.5.5 to 4.7.0,

then, compiler my C++ code,  have error:

`C:\Install\vcpkg\installed\x64-windows\bin\libprotobuf.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x300 `

My code is not changed.....

Thanks

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Could you please provide a simple repro project?

**Comment by yulinxx** [comment]
I'm sorry, the code is part of a larger project and cannot be easily separated.

I have been using both my personal computer and the company's computer with an older version,   

and everything was fine.   

However, recently I upgraded the vcpkg library and encountered an issue with protobuf.   
Interestingly, the same problem occurred on both computers.

The code itself hasn't been modified, only the protobuf library has been upgraded.   
Therefore, we can rule out any issues with the code.   

Since the problem occurs on both computers, I can conclude that the issue is not specific to my setup.
  
Error:  
10>C:\Install\vcpkg_ProtobufLInkError\installed\x64-windows\debug\bin\libprotobufd.dll : fatal error LNK1107: 文件无效或损坏: 无法在 0x378 处读取   

---  

实在抱歉，代码是在一个大工程里面，不好分出来  


用了自己的电脑 和公司的电脑 ，用旧的版本一直没问题，
然后最近升级vcpkg的库，然后就提示protobuf 出问题了，
而且两台电脑的情况一模一样。

代码未修改，仅升级protobouf库，所以可以排除代码的问题，
然而两台电脑情况也一样，所以我 确定，应该不是我这里的问题

**Comment by BisonLeo** [comment]
I got the same error. It looks like the Cmake used the .dll file as .lib file for linking. 
Interesting...

**Comment by dg0yt** [comment]
@BisonLeo opencv4 is at 4.8.0 now. If you can provide a reproducible example for the current versions, you could open a new issue. But I don't see anything suspicious w.r.t. libprotobuf and opencv4 at least for x64-mingw-dynamic. The target properties seem okay.
