### ISSUE TITLE
[glib] vcpkg does not copy glib helper executables

### ISSUE THREAD

**Issue by Febbe** [microsoft/vcpkg#31911]
**Describe the bug**
When compiling any program, which requires the "win32 session dbus binary" A warning is raised:
```
(xournalpp.exe:22024): GLib-GIO-WARNING **: 14:33:22.753: win32 session dbus binary not found
```
**Environment**
- OS: [Windows]
- Compiler: revision The CXX compiler identification is MSVC 19.35.32217.1

**To Reproduce**
I have no easy example, because this is a warning raised from a xournalpp build

1. `./vcpkg install gtk3:x64-windows glib:x64-windows poppler[glib]:x64-windows portaudio:x64-windows libzip:x64-windows zlib:x64-windows libxml2:x64-windows sndfile:x64-windows librsvg:x64-windows libsndfile:x64-windows`
2. install pkg-config and add to path
3. install [rsvg-convert](https://sourceforge.net/projects/pkgconfiglite/files/0.28-1/pkg-config-lite-0.28-1.tar.gz/download) & add to path
4. install imagemagick
5. copy
```
prefix=${pcfiledir}/../..
exec_prefix=${prefix}
bindir=${prefix}/bin
libdir=${prefix}/lib
includedir=${prefix}/include

Name: librsvg-2.0
Description: library for handling rsvg files
Version: 2.40.2
Requires: glib-2.0 gio-2.0 gdk-pixbuf-2.0 cairo
Libs:  "-L${libdir}" -lrsvg-2.40
Cflags: "-I${includedir}"
``` 
to `C:\vcpkg\installed\x64-windows\lib\pkgconfig\librsvg-2.0.pc`

7. Add adwaita theme (
I could not find a way to install it, but adding it to the build dir works)
8. `cd mywd`
9. `git clone https://github.com/xournalpp/xournalpp.git`
10. `mkdir build && cd build && cmake -GNinja .. && cmake --build .`
11. `./xournalpp.exe`

**Expected behavior**
That the gdbus executable is found, and no warning is raised.

**Failure logs**
See above

**Additional context**
Adding `C:\vcpkg\installed\x64-windows\tools\glib` to the path will fix it, but is undesirable, because it may break other tool chains.

The to be copied executables are: 

```
"C:\vcpkg\installed\x64-windows\tools\glib\gspawn-win64-helper-console.exe"
"C:\vcpkg\installed\x64-windows\tools\glib\gio.exe"
"C:\vcpkg\installed\x64-windows\tools\glib\gspawn-win64-helper.exe"
```

**Comment by dg0yt** [comment]
How to tell if it is needed or not?

**Comment by Neumann-A** [comment]
That probably requires manual deployment.

**Comment by Febbe** [comment]
> That probably requires manual deployment.

Yes, that may be required, but when a deployment over vcpkg is not possible (or with an overwhelming amount of work), you may close it.
In that case me, and others would be glad to have some better ideas as to add them to the path/or copy them manually.

**Comment by Febbe** [comment]
> How to tell if it is needed or not?

Currently, I can't actually, because I have other issues with the provided gtk version (even with 3.24.38).

**Comment by Neumann-A** [comment]
> In that case me, and others would be glad to have some better ideas as to add them to the path/or copy them manually.

The same way you would do it without vcpkg.
