### ISSUE TITLE
CGAL debug library not found via CMake

### ISSUE THREAD

**Issue by jjpepper** [Microsoft/vcpkg#3192]
When building a CMake Debug build that has a dependency on CGAL, the <vcpkg_dir>\installed\x64-windows\debug\lib directory is not added to the link path.

The error received is:

`LINK : fatal error LNK1104: cannot open file 'CGAL-vc140-mt-gd-4.11-I-900.lib'`

The workaround is to add:

```
if (${CMAKE_BUILD_TYPE} STREQUAL "Debug")
    link_directories(<vcpkg_dir>/installed/x64-windows/debug/lib)
endif() 
```

where <vcpkg_dir> is the path to the vcpkg root.

By the way it would be really nice if this was available in CMake and CMakeSettings.json as a macro or something so that we can be independent of where vcpkg is installed.

**Comment by jasjuang** [comment]
It works for me. Here is a minimal setup to demonstrate it works:

CMakeLists
```
cmake_minimum_required(VERSION 3.9)

project(Example LANGUAGES CXX)

set(PROJECT_SRCS ${PROJECT_SOURCE_DIR}/mycpp.cpp)

find_package( CGAL REQUIRED )

add_executable(${PROJECT_NAME} ${PROJECT_SRCS})

target_link_libraries(${PROJECT_NAME}
                      CGAL::CGAL)
```

mycpp.cpp

```
int main(){
return 0;
}
```

`msbuild Example.sln` shows build succeeded

**Comment by jjpepper** [comment]
Silly question but does MSBuild use the CMakeLists.txt?  I thought you
didn’t use a solution file with CMake for windows.  Or are you generating
the solution from CMake?  I’m using visual studio’s built in CMake tools.

**Comment by jasjuang** [comment]
The solution file is generated by CMake. `cmake -A x64 -DCMAKE_TOOLCHAIN_FILE=whereyourtoolchainfileis ..`

**Comment by JackBoosY** [comment]
Hi @jjpepper , thanks for reporting this issue.
Please open a new issue if this is still a problem for you.
Thx.
