### ISSUE TITLE
error: Failed to download ogg from mirror set.

### ISSUE THREAD

**Issue by AlvinKimata** [microsoft/vcpkg#31927]
I am tring to install the `ogg` package using the command below. 

```
C:\vcpkg>vcpkg --triplet x64-windows install sfml tclap glm
```

Here's the error message that I am getting below.
```
C:\vcpkg>vcpkg --triplet x64-windows install sfml tclap glm
Computing installation plan...
The following packages are already installed:
    glm:x64-windows -> 0.9.9.8#2
The following packages will be built and installed:
  * libflac:x64-windows -> 1.4.2
  * libogg:x64-windows -> 1.3.5#1
  * libvorbis:x64-windows -> 1.3.7#2
  * openal-soft:x64-windows -> 1.23.0
  * opengl:x64-windows -> 2022-12-04#3
  * opengl-registry:x64-windows -> 2022-09-29#1
    sfml:x64-windows -> 2.5.1#15
  * stb:x64-windows -> 2023-04-11#1
    tclap:x64-windows -> 1.2.5
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
-- Using HTTP(S)_PROXY in environment variables.
Restored 0 package(s) from C:\Users\debonair\AppData\Local\vcpkg\archives in 413 us. Use --debug to see more details.
glm:x64-windows is already installed
Installing 1/9 libogg:x64-windows...
Building libogg:x64-windows...
-- Downloading https://gitlab.xiph.org/xiph/ogg/-/archive/v1.3.5/ogg-v1.3.5.tar.gz -> xiph-ogg-v1.3.5.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from C:\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: C:\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
Downloading https://gitlab.xiph.org/xiph/ogg/-/archive/v1.3.5/ogg-v1.3.5.tar.gz
warning: Download failed -- retrying after 1000ms
warning: Download failed -- retrying after 2000ms
warning: Download failed -- retrying after 4000ms
error: Failed to download from mirror set
error: https://gitlab.xiph.org/xiph/ogg/-/archive/v1.3.5/ogg-v1.3.5.tar.gz: WinHttpSendRequest failed with exit code 12029
error: https://gitlab.xiph.org/xiph/ogg/-/archive/v1.3.5/ogg-v1.3.5.tar.gz: WinHttpSendRequest failed with exit code 12029
error: https://gitlab.xiph.org/xiph/ogg/-/archive/v1.3.5/ogg-v1.3.5.tar.gz: WinHttpSendRequest failed with exit code 12029
error: https://gitlab.xiph.org/xiph/ogg/-/archive/v1.3.5/ogg-v1.3.5.tar.gz: WinHttpSendRequest failed with exit code 12029
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(962):
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 13us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 1495us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 15 s (15107070us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.


Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_gitlab.cmake:118 (vcpkg_download_distfile)
  ports/libogg/portfile.cmake:1 (vcpkg_from_gitlab)
  scripts/ports.cmake:147 (include)
```

How can I change the download link from the original one to the one provided in the ogg github repository: `https://github.com/xiph/ogg/releases/tag/v1.3.5`

**Comment by Baklap4** [comment]
It can be downloaded from ftp: https://ftp.osuosl.org/pub/xiph/releases/ogg/libogg-1.3.5.tar.gz
But after putting it in `$VCPKG_ROOT/downloads` it still doesn't work any chance this can work?

**Comment by dg0yt** [comment]
https://ftp.osuosl.org/pub/xiph/releases/ogg/libogg-1.3.5.tar.gz is not the same file. The SHA512 sum differs.

**Comment by Baklap4** [comment]
Releases on github also differ so cannot be used either -.-" already opened ticket there

**Comment by dg0yt** [comment]
As a workaround, you can try to update the SHA512 in the portfile if you trust the source.

**Comment by StarGate-One** [comment]
[xiph-ogg-v1.3.5.tar.gz](https://github.com/microsoft/vcpkg/files/11713337/xiph-ogg-v1.3.5.tar.gz)

I normally keep the current version of the ports I install in vcpkg-downloads folder until the next version comes out.

**Comment by AlvinKimata** [comment]
> As a workaround, you can try to update the SHA512 in the portfile if you trust the source.

How did you go about it?

**Comment by JackBoosY** [comment]
Should update the SHA value.
The upstream updated the current package without updating the version field?

**Comment by dg0yt** [comment]
> Should update the SHA value. The upstream updated the current package without updating the version field?

The current download is a tarball (generated on the fly) from gitlab. Similar to what is used with most github ports. Now this gitlab instance isn't working at the moment.

The other downloads are not from gitlab. They may have been in  created in another way. They are not the same files. Some sources might be official.

So you bascially have to decide if you want to switch from the official gitlab instance to official release tarballs.

**Comment by JackBoosY** [comment]
> The current download is a tarball (generated on the fly) from gitlab. Similar to what is used with most github ports. Now this gitlab instance isn't working at the moment.
> 
> The other downloads are not from gitlab. They may have been in created in another way. They are not the same files. Some sources might be official.
> 
> So you bascially have to decide if you want to switch from the official gitlab instance to official release tarballs.

We need to ensure that the package at the primary download address is the same as the package at other alternative addresses I think.

**Comment by jimwang118** [comment]
Please make sure you can download directly using the [URL](https://gitlab.xiph.org/xiph/ogg/-/archive/v1.3.5/ogg-v1.3.5.tar.gz). 
I am testing locally, using the command you provided and installing `libogg` separately can be downloaded and compiled successfully.
![image](https://github.com/microsoft/vcpkg/assets/122244446/338ba299-e533-47be-8708-41f31ed58a5d)

**Comment by Baklap4** [comment]
The gitlab instance was down (it returned 500 internal server error). This has now been fixed, the original portfile should just work again (issue can probably be closed)

**Comment by AlvinKimata** [comment]
> The gitlab instance was down (it returned 500 internal server error). This has now been fixed, the original portfile should just work again (issue can probably be closed)
> 
> Though it'd be nice to add a mirror to github

The 500 internal server error has been fixed. Please feel free to open this issue if the issue arises again.

**Comment by monophonicspace** [comment]
Looks like there's been another internal server error 500.

**Comment by pierr3** [comment]
Occurred again as of today 10pm CET.
