### ISSUE TITLE
assimp doesn't copy it's dll

### ISSUE THREAD

**Issue by daef** [Microsoft/vcpkg#3193]
I'm used to the linked .dlls showing up in the output directory.
This doesn't seem to happen for assimp.
I have no idea whether I'm calling things wrong,
this is a problem in assimps .cmake or a packaging/porting issue in vcpkg.

I've attached a small repro project - you'll probably have to adapt build.cmd for things to work.
[repro.zip](https://github.com/Microsoft/vcpkg/files/1871309/repro.zip)

build.log contains the output build.cmd produces on my machine.

EDIT:
the test project depends on protobuf:x64-windows assimp:x64-windows to be installed.

**Comment by daef** [comment]
I seem to have gotten it working. The culprit seems to have been that debug builds would still reference the optimized library. To change this behaviour I've edited my `VCPKG_ROOT\installed\x64-windows\share\assimp\assimp-config.cmake`

from

```
set( ASSIMP_LIBRARY_DIRS "${ASSIMP_ROOT_DIR}/lib")
set( ASSIMP_INCLUDE_DIRS "${ASSIMP_ROOT_DIR}/include")
set( ASSIMP_LIBRARIES assimp${ASSIMP_LIBRARY_SUFFIX}.lib)
set( ASSIMP_LIBRARIES ${ASSIMP_LIBRARY_DIRS_RELEASE}/${ASSIMP_LIBRARIES})
```

to

```
set( ASSIMP_LIBRARY_DIRS_RELEASE "${ASSIMP_ROOT_DIR}/lib")
set( ASSIMP_LIBRARY_DIRS_DEBUG "${ASSIMP_ROOT_DIR}/debug/lib")
set( ASSIMP_INCLUDE_DIRS "${ASSIMP_ROOT_DIR}/include")
set( ASSIMP_LIBRARIES_RELEASE ${ASSIMP_LIBRARY_DIRS_RELEASE}/assimp${ASSIMP_LIBRARY_SUFFIX}.lib)
set( ASSIMP_LIBRARIES_DEBUG ${ASSIMP_LIBRARY_DIRS_DEBUG}/assimp${ASSIMP_LIBRARY_SUFFIX}d.lib)
set( ASSIMP_LIBRARIES optimized ${ASSIMP_LIBRARIES_RELEASE} debug ${ASSIMP_LIBRARIES_DEBUG})
```

But I have no Idea how idiomatic this is or how I would do this in the portfile.

**Comment by lerppana** [comment]
Fix that @daef posted fixed the issue for me also. Can someone confirm if this is issue with assimp cmake config file or should it be fixed in vcpkg port files? I have no deeper knowledge weither either one of those is better, or if fixing the assimp-config.cmake as instructed earlier would break on other OS than windows.

**Comment by ja3067** [comment]
bump

**Comment by daef** [comment]
referencing https://github.com/assimp/assimp/issues/1517 for completeness.

**Comment by daef** [comment]
All my problems went away when I stared using the current version and importing assimp::assimp instead of ${ASSIMP_LIBRARIES}

**Comment by perefm** [comment]
Seems that this issue is apprearing again with the new assimp 5.0 version
