### ISSUE TITLE
Inability to build only debug libraries

### ISSUE THREAD

**Issue by ilya-lavrenov** [microsoft/vcpkg#31947]
### Is your feature request related to a problem? Please describe.

I want to debug some application, which uses vcpkg as a dependency manager.
Currently I have to:
- build `tools` for debug and release. Any reason to build tools with x64-linux on Linux? Why do you spend machine time with debug version of tools?
- Build `libraries` for debug and release. I have tried to add `set(VCPKG_BUILD_TYPE Debug)` to build only debug libraries, but a lot of libraries were because, because ports.cmake files remove developments files (cmake config files, includes, etc) for debug and expect release ones to be installed (but I have no release files, because build type is `Debug`).

Example of failure is TBB:
```
CMake Error at buildtrees/versioning_/versions/tbb/d050b3a84687479bb03134f98f6360bfb72e64a8/portfile.cmake:47 (file):
  file failed to open for reading (No such file or directory):

    /mnt/data3_1878/ilya/Documents/Programming/git_repo/vcpkg/packages/tbb_arm64-android/share/tbb/TBBConfig.cmake
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)
```

Expectations:
- Automatically use build type `Release` for tools.
- If I want to build only `Debug` libraries and I mentioned it in triplets, I want the ports to work instead of fail.

### Proposed solution

No simple idea how to make port files to be debug / release independent.

Most likely you need to write cmake common functions like `vcpkg_cmake_config_fixup` which understand what build type is currently used and copy `lib/cmake/TBB` or `debug/lib/cmake/gfx` depending on build type.

```[tasklist]
### Tasks
```

**Comment by Neumann-A** [comment]
The trick is to use a (release only|single config) triplet and adjust the build flags in the toolchain accordingly.

**Comment by ilya-lavrenov** [comment]
> The trick is to use a (release only|single config) triplet and adjust the build flags in the toolchain accordingly.

Please, see what I have wrote:
- I already did it.
- Ports fail with error because they remove debug headers / cmake files and expect release one to be present

**Comment by Neumann-A** [comment]
Again:
`set(VCPKG_BUILD_TYPE Debug)` is unsupported. So you simply use `set(VCPKG_BUILD_TYPE Release)` and change the release build flags in the toolchain to the ones of the debug build. The only ports you need to adjust are ports which do not build from source or do not respect the toolchain setting. Basically make a new triplet `x64-linux-release-as-debug` for your target and specify  `x64-linux-release` as the host triplet.

> Any reason to build tools with x64-linux on Linux?  

Change your host triplet to `x64-linux-release`?

>Why do you spend machine time with debug version of tools?

To avoid spending time rebuilding common dependencies. (Some refinement could probably be done by building some tools as release only or only build them for release.)
