### ISSUE TITLE
[opencv4] Build error

### ISSUE THREAD

**Issue by chenkael** [microsoft/vcpkg#31956]
Copy issue body from C:/vcpkg/vcpkg/vcpkg_installed/vcpkg/issue_body.md

C:\vcpkg\vcpkg>vcpkg install
warning: The vcpkg C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg\vcpkg.exe is using detected vcpkg root C:\vcpkg\vcpkg and ignoring mismatched VCPKG_ROOT environment value c:\vcpkg. To suppress this message, unset the environment variable or use the --vcpkg-root command line switch.
Detecting compiler hash for triplet x64-windows...
The following packages will be built and installed:
    opencv4[contrib,core,default-features,dnn,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.5.5 -- C:\Users\chen\AppData\Local\vcpkg\registries\git-trees\afed148d21295bf99e8ac657fdb808ed82467871
Restored 0 package(s) from C:\Users\chen\AppData\Local\vcpkg\archives in 135 us. Use --debug to see more details.
Installing 1/1 opencv4:x64-windows...
Building opencv4[contrib,core,default-features,dnn,jpeg,png,quirc,tiff,webp]:x64-windows...
-- Installing port from location: C:\Users\chen\AppData\Local\vcpkg\registries\git-trees\afed148d21295bf99e8ac657fdb808ed82467871
-- Using cached opencv-opencv-4.5.5.tar.gz.
-- Cleaning sources at C:/vcpkg/vcpkg/vcpkg_installed/vcpkg/blds/opencv4/src/4.5.5-f2b5f31c0d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/chen/AppData/Local/vcpkg/downloads/opencv-opencv-4.5.5.tar.gz
-- Applying patch 0001-disable-downloading.patch
-- Applying patch 0002-install-options.patch
-- Applying patch 0003-force-package-requirements.patch
-- Applying patch 0004-fix-policy-CMP0057.patch
-- Applying patch 0005-fix-eigen.patch
-- Applying patch 0006-fix-uwp.patch
-- Applying patch 0008-devendor-quirc.patch
-- Applying patch 0009-fix-protobuf.patch
-- Applying patch 0010-fix-uwp-tiff-imgcodecs.patch
-- Applying patch 0011-remove-python2.patch
-- Applying patch 0012-fix-zlib.patch
-- Applying patch 0013-fix-opengl.patch
-- Applying patch 0014-fix-gstreamer.patch
-- Applying patch 0015-fix-freetype.patch
-- Using source at C:/vcpkg/vcpkg/vcpkg_installed/vcpkg/blds/opencv4/src/4.5.5-f2b5f31c0d.clean
-- Using cached opencv-cache/tiny_dnn/adb1c512e09ca2c7a6faef36f9c53e59-v1.0.0a3.tar.gz.
-- Using cached opencv-opencv_contrib-4.5.5.tar.gz.
-- Cleaning sources at C:/vcpkg/vcpkg/vcpkg_installed/vcpkg/blds/opencv4/src/4.5.5-c35cb8696d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/chen/AppData/Local/vcpkg/downloads/opencv-opencv_contrib-4.5.5.tar.gz
-- Applying patch 0007-fix-hdf5.patch
-- Applying patch 0016-fix-freetype-contrib.patch
-- Using source at C:/vcpkg/vcpkg/vcpkg_installed/vcpkg/blds/opencv4/src/4.5.5-c35cb8696d.clean
-- Using cached opencv-cache/wechat_qrcode/238e2b2d6f3c18d6c3a30de0c31e23cf-detect.caffemodel.
-- Using cached opencv-cache/wechat_qrcode/cbfcd60361a73beb8c583eea7e8e6664-sr.caffemodel.
-- Using cached opencv-cache/wechat_qrcode/6fb4976b32695f9f5c6305c19f12537d-detect.prototxt.
-- Using cached opencv-cache/wechat_qrcode/69db99927a70df953b471daaba03fbef-sr.prototxt.
-- Using cached opencv-cache/xfeatures2d/boostdesc/0ea90e7a8f3f7876d450e4149c97c74f-boostdesc_bgm.i.
-- Using cached opencv-cache/xfeatures2d/boostdesc/232c966b13651bd0e46a1497b0852191-boostdesc_bgm_bi.i.
-- Using cached opencv-cache/xfeatures2d/boostdesc/324426a24fa56ad9c5b8e3e0b3e5303e-boostdesc_bgm_hd.i.
-- Using cached opencv-cache/xfeatures2d/boostdesc/202e1b3e9fec871b04da31f7f016679f-boostdesc_binboost_064.i.
-- Using cached opencv-cache/xfeatures2d/boostdesc/98ea99d399965c03d555cef3ea502a0b-boostdesc_binboost_128.i.
-- Using cached opencv-cache/xfeatures2d/boostdesc/e6dcfa9f647779eb1ce446a8d759b6ea-boostdesc_binboost_256.i.
-- Using cached opencv-cache/xfeatures2d/boostdesc/0ae0675534aa318d9668f2a179c2a052-boostdesc_lbgm.i.
-- Using cached opencv-cache/xfeatures2d/vgg/e8d0dcd54d1bcfdc29203d011a797179-vgg_generated_48.i.
-- Using cached opencv-cache/xfeatures2d/vgg/7126a5d9a8884ebca5aea5d63d677225-vgg_generated_64.i.
-- Using cached opencv-cache/xfeatures2d/vgg/7cd47228edec52b6d82f46511af325c5-vgg_generated_80.i.
-- Using cached opencv-cache/xfeatures2d/vgg/151805e03568c9f490a5e3a872777b75-vgg_generated_120.i.
-- Using cached opencv-cache/data/7505c44ca4eb54b4ab1e4777cb96ac05-face_landmark_model.dat.
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Warning at scripts/cmake/vcpkg_execute_build_process.cmake:65 (message):
  Please ensure your system has sufficient memory.
Call Stack (most recent call first):
  vcpkg_installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  vcpkg_installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  C:/Users/chen/AppData/Local/vcpkg/registries/git-trees/afed148d21295bf99e8ac657fdb808ed82467871/portfile.cmake:498 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j21
    Working Directory: C:/vcpkg/vcpkg/vcpkg_installed/vcpkg/blds/opencv4/x64-windows-dbg
    See logs for more information:
      C:\vcpkg\vcpkg\vcpkg_installed\vcpkg\blds\opencv4\install-x64-windows-dbg-out.log
      C:\vcpkg\vcpkg\vcpkg_installed\vcpkg\blds\opencv4\install-x64-windows-dbg-out-1.log

Call Stack (most recent call first):
  vcpkg_installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  vcpkg_installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  C:/Users/chen/AppData/Local/vcpkg/registries/git-trees/afed148d21295bf99e8ac657fdb808ed82467871/portfile.cmake:498 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building opencv4:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+opencv4
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[opencv4]+Build+error&body=Copy+issue+body+from+C%3A%2Fvcpkg%2Fvcpkg%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md

**Comment by chenkael** [comment]
this is json file:
{
  "name": "my-opencv-project",
  "version-semver": "1.0.0",
  "builtin-baseline": "6f7ffeb18f99796233b958aaaf14ec7bd4fb64b2",
  "dependencies": [
    { "name": "opencv4", "features": ["contrib"], "version>=": "4.5.5" }
  ],
  "overrides": [
    { "name": "opencv4", "version": "4.5.5" }
  ]
}

**Comment by chenkael** [comment]
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/11740272/install-x64-windows-dbg-out.log)
[install-x64-windows-dbg-out-1.log](https://github.com/microsoft/vcpkg/files/11740274/install-x64-windows-dbg-out-1.log)
there are plenty of information in the 2 files. thanks for reading

**Comment by JonLiu1993** [comment]
Thanks for posting this issue. I can not reproduce this issue locally.
````
-- Installing: F:/Feature-test/usd/vcpkg/packages/opencv4_x64-windows/share/opencv4/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 14 s.
Elapsed time to handle opencv4:x64-windows: 12 min
Total install time: 19 min
If you do not install the meta-port *opencv*, the package opencv4 is compatible with CMake
if you set the OpenCV_DIR *before* the find_package call

    set(OpenCV_DIR "${VCPKG_INSTALLED_DIR}/x64-windows/share/opencv4")
    find_package(OpenCV REQUIRED)
````
It's possible that they were deleted by antivirus software. You can try disabling the antivirus software and then try again.

**Comment by JonLiu1993** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
