### ISSUE TITLE
[angle] Missing definition for building the GL backend on Windows causes libEGL crash

### ISSUE THREAD

**Issue by amyspark** [microsoft/vcpkg#31954]
**Describe the bug**

The GL backend requires a few definitions on Windows, which are specified here:

https://github.com/microsoft/vcpkg/blob/1ba9a2591f15af5900f2ce2b3e2bf31771e3ac48/ports/angle/cmake-buildsystem/PlatformWin.cmake#L62-L64

However, there's a critical one missing: https://github.com/google/angle/blob/main/src/libANGLE/renderer/gl/BUILD.gn#L19

This causes the attempt to initialize libEGL to crash with a nonsensical null pointer dereference, because the functions' addresses are never retrieved to begin with:  https://bugs.chromium.org/p/angleproject/issues/detail?id=8195

**Environment**
- OS: [e.g. Windows/Linux etc...] Windows 10 22H2
- Compiler: MSVC 17.6.2

**To Reproduce**
1. ./vcpkg install angle
2.  Build Qt 6 with patched ANGLE support from: https://github.com/amyspark/qtbase/tree/amyspark/angle.
3. Build the hellogles3 example against the Qt and ANGLE libraries.

**Expected behavior**

When the app is launched with the `QT_ANGLE_PLATFORM` set to `opengl`, the app should pass libEGL initialization, but be unable to initialize a context. (The latter is a separate ANGLE bug).

**Failure logs**

See the associated crash on the ANGLE bug tracker.

**Additional context**

Currently, the app will crash in libEGL initialization.

**Comment by FrankXie05** [comment]
@amyspark Could you please provide a minimal repro example? 
I'll add these options to the GL backend to make sure it works. :)
