### ISSUE TITLE
CTRL+C during vcpkg command causes console to get "stuck"

### ISSUE THREAD

**Issue by patrikhuber** [Microsoft/vcpkg#3197]
Hi,

This is somewhat weird to describe and doesn't always happen but it's somewhat 100% reproducible, it happens every time, at least after a few tries.
If you press `CTRL+C` after just entering e.g. `.\vcpkg install opencv`, hit enter, and then `CTRL+C` right away as soon as it starts downloading/installing, then this (most of the time) pretty much completely messes up your powershell terminal. It's not reliably possible to press CTRL+C anymore (to abort and get an empty line on the next line) or even enter any text - some characters sometimes still work, sometimes, but the window really gets stuck and you can't do anything with it anymore. Only solution is to close and re-open powershell.

What may be relevant is that I have a default poshgit installation active, with the line `Import-Module posh-git` in my `C:\Users\Patrik\Documents\WindowsPowerShell\profile.ps1`. I also got a file `C:\Users\Patrik\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1` with the line `Import-Module 'C:\Users\Patrik\vcpkg\scripts\posh-vcpkg'` in it - not sure what that is.
But what I do to start powershell is press the Windows key and then type "po" and then hit "Enter" - I think this opens `"C:\Users\Patrik\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Windows PowerShell\Windows PowerShell.lnk"`.

I am not sure whether this could possibly be related to #2396.

**Comment by ras0219-msft** [comment]
It's been a while, but I think I've actually fixed this with 56e1d2f696169.

If it still reproduces after this commit, please let us know!
