### ISSUE TITLE
[ASIO] port now depends on boost

### ISSUE THREAD

**Issue by adam4813** [Microsoft/vcpkg#3198]
For some reason in commit da9c2e7 `Build-Depends: boost-config, boost-throw-exception, boost-utility, boost-date-time` was added to the ASIO CONTROL  file therefore adding boost back to the stand-alone library. ASIO in this form is meant to NOT require boost. This change increases build times as well as installing unneeded libraries.

**Comment by nicole9456** [comment]
Thanks for your issue! 
I closed the issue, because it fixed in commit [d953c78](https://github.com/Microsoft/vcpkg/commit/d953c7869d5a7feac938aef14bcb5ceb8cd4b175#diff-91a3d9a6883a83c31b763d48a94755b1).
