### ISSUE TITLE
[icu] Build error

### ISSUE THREAD

**Issue by SI-Lab** [microsoft/vcpkg#31987]
Building Qfield master using cmake under arm64-android. Tools used MSVS2019/Android Studio/Qt installed 
Reaching icu depandency i got the error below. Any solution?

error: building icu:arm64-android failed with: BUILD_FAILED

**Comment by autoantwort** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report a proper issue.

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
