### ISSUE TITLE
[icu>] Build error

### ISSUE THREAD

**Issue by SI-Lab** [microsoft/vcpkg#31988]
### Operating system

Windows 11 Pro

### Compiler

Cmake/MSVS2019/Android Studio/Qt installed

### Steps to reproduce the behavior

```Shell
Installing 1/39 icu:arm64-android...
Building icu[core]:arm64-android...

-- [OVERLAY] Loading triplet configuration from: C:\Project\QField-master\vcpkg\triplets\arm64-android.cmake

-- Using cached icu4c-72_1-src.tgz.
```

### Failure logs

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:151 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:2 (vcpkg_build_make)
  ports/icu/portfile.cmake:145 (vcpkg_install_make)
  scripts/ports.cmake:147 (include)

error: building icu:arm64-android failed with: BUILD_FAILED

Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+icu
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[icu]+Build+error&body=Copy+issue+body+from+D%3A%2FBuild%2FQfield4%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md

Running vcpkg install - failed

**Comment by autoantwort** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report a proper issue.

**Comment by whisper-bye** [comment]
@SI-Lab how did you fix it?

**Comment by ericwait** [comment]
I was able to get `icu` to install by first installing additional compiler tools like so:
`brew install autoconfig autoconfig-archive automake`

I hope this helps you too!

**Comment by SI-Lab** [comment]
> compiler tools like so:

Thank you for your reply.
Guide me on how to install this kindly.

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
