### ISSUE TITLE
Failures when vcpkg install boost-vcpkg-helpers:x64-windows

### ISSUE THREAD

**Issue by QuellaZhang** [Microsoft/vcpkg#3199]
This issue found when I build Folly by VCPKG 'vcpkg install boost-vcpkg-helpers:x64-windows'.

**Failures：**
D:\Folly\vcpkg\src>vcpkg install boost-vcpkg-helpers:x64-windows
 The following packages will be built and installed:
 boost-vcpkg-helpers[core]:x64-windows
 Starting package 1/1: boost-vcpkg-helpers:x64-windows
 Building package boost-vcpkg-helpers[core]:x64-windows...
 Unsupported toolchain combination x64

D:\Folly\vcpkg\src>vcpkg version
 Vcpkg package management program version 0.0.107
 
 See LICENSE.txt for license information.

**Comment by KindDragon** [comment]
Try `vcpkg upgrade --no-dry-run --triplet x64-windows` to update all libraries before installing `boost-vcpkg-helpers:x64-windows`

**Comment by QuellaZhang** [comment]
I tried what you suggested but it's still failed.

**Failures：**

**D:\Folly\vcpkg\src>vcpkg upgrade --no-dry-run --triplet x64-windows**
All installed packages are up-to-date with the local portfiles.

**D:\Folly\vcpkg\src>vcpkg install boost-vcpkg-helpers:x64-windows**
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be built and installed:
    boost-vcpkg-helpers[core]:x64-windows
Starting package 1/1: boost-vcpkg-helpers:x64-windows
Building package boost-vcpkg-helpers[core]:x64-windows...
Unsupported toolchain combination x64

**D:\Folly\vcpkg\src>vcpkg version**
Vcpkg package management program version 0.0.107

See LICENSE.txt for license information.

**Comment by PhoebeHui** [comment]
Any updates?

**Comment by PhoebeHui** [comment]
This block us for a long time, anyone who can help take a look?

**Comment by Sithdown** [comment]
I'm in the same situation. Any news?

**Comment by KindDragon** [comment]
You can try clean installation

**Comment by QuellaZhang** [comment]
Thank you very much! Folly build is clean now.
