### ISSUE TITLE
Please add the GSL

### ISSUE THREAD

**Issue by MikeGitb** [Microsoft/vcpkg#32]
The *Guideline Support Library* (https://github.com/Microsoft/GSL) would be a small, but invaluable  addition.

**Comment by ras0219-msft** [comment]
Fixed in 744144381187bfa5c4aaf83878f0147c3ce99a8e!

**Comment by ras0219-msft** [comment]
Notice: the GSL port has been renamed to `ms-gsl`, since the name `gsl` is widely used to refer to the GNU Scientific Library.

**Comment by MikeGitb** [comment]
Yeah, that conflict is really troublesome. I'd like to see something brought forward from the ms-gsl or cpp core guideline maintainers that could then be consistently adopted by all packet manager, but in the past there was a lot of resistance, so this is probably the best we can do for the moment.
