### ISSUE TITLE
[angelscript] not include addons cpp file to lib

### ISSUE THREAD

**Issue by PeacefulWindy** [microsoft/vcpkg#32024]
### Is your feature request related to a problem? Please describe.

I use it config in vcpkg.json:
```
        {
            "name":"angelscript",
            "features":[
                "addons"
            ]
        },

```
But I find addons's option,*.cpp not include it.
Example,scriptstdstring.cpp,scriptbuilder.cpp and more.

### Proposed solution

add the *.cpp file to include it.

**Comment by MonicaLiu0311** [comment]
https://github.com/microsoft/vcpkg/blob/5d2a0a9814db499f6ba2e847ca7ab5912badcdbf/ports/angelscript/portfile.cmake#L25-L28

After I try it locally, the header files have been installed to the specified location. It should be noted that in the `manifests` mode, the installed files are placed in the `vcpkg/vcpkg_installed/` directory.

![image](https://github.com/microsoft/vcpkg/assets/110024546/a7230e9b-b700-41f6-9b81-b9e348c874af)

**Comment by PeacefulWindy** [comment]
So I use aux_source_directory to add *.cpp instead target_link_libraries?
More habit to use target_link_libraries as for me.
