### ISSUE TITLE
no classic mode since last update

### ISSUE THREAD

**Issue by bcolombet** [microsoft/vcpkg#32026]
**error: Could not locate a manifest (vcpkg.json) above the current working directory.
This vcpkg distribution does not have a classic mode instance.**

I just did a git pull to update my vcpkg installation.

**Environment**
- OS: Windows
- Compiler: VS2019

**To Reproduce**
1. git pull
2. vcpkg install <package>

**Expected behavior**

**Failure logs**
error: Could not locate a manifest (vcpkg.json) above the current working directory.
This vcpkg distribution does not have a classic mode instance

**Additional context**

**Comment by NeoxyCN** [comment]
> ok... after closing and reponing my terminal it seems ok..

I have the same question.
And open a new terminal is only okay for once, the next command still has the same question...
