### ISSUE TITLE
Can't use WebP with GraphicsMagick

### ISSUE THREAD

**Issue by josuegomes** [Microsoft/vcpkg#3202]
I'm trying to use WebP in the GraphicsMagick port. In CMakeLists.txt I have added:

`find_package(WebP REQUIRED)`

However CMake fails to detect WebP. See config log:

```CMake Error at D:/vcpkg-dev/scripts/buildsystems/vcpkg.cmake:272 (_find_package):
  By not providing "FindWebP.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "WebP", but
  CMake did not find one.

  Could not find a package configuration file provided by "WebP" with any of
  the following names:

    WebPConfig.cmake
    webp-config.cmake

  Add the installation prefix of "WebP" to CMAKE_PREFIX_PATH or set
  "WebP_DIR" to a directory containing one of the above files.  If "WebP"
  provides a separate development package or SDK, be sure it has been
  installed.
```

However file FindWebP.cmake can be found at under installed/_tripplet_/share/libwebp directory.

Is this a bug on libwebp port?

**Comment by JackBoosY** [comment]
Hi @josuegomes , thanks for reporting this issue!
WebP seems to have been fixed. You can find "**WebPConfig.cmake**" with the command "**find_package(WebP CONFIG REQUIRED)**" now.
Please open a new issue if this is still a problem for you.
Thx.
