### ISSUE TITLE
[New Port Request] libcsnd6

### ISSUE THREAD

**Issue by bramtayl** [microsoft/vcpkg#32030]
### Library name

libcsnd6

### Library description

C++ bindings for the Csound API

### Source repository URL

https://github.com/csound/csound

### Project homepage (if different from the source repository)

https://csound.com/

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

There's also libcsound64, the C API, which should be a dependency I think. There are also csound plugins, the one I'm using is the [STK plugin](https://csound.com/docs/manual/STKTop.html), having a way to install that would be helpful too.

**Comment by JonLiu1993** [comment]
No stale
