### ISSUE TITLE
[concurrencpp] build failure

### ISSUE THREAD

**Issue by gotnone** [microsoft/vcpkg#32035]
### Operating system

Windows

### Compiler

MSVC and Clang

### Steps to reproduce the behavior

```Shell
add the following lines to your CMakeLists.txt and adjust the target as appropriate

find_package(concurrencpp CONFIG REQUIRED)
target_link_libraries(main PRIVATE concurrencpp::concurrencpp)
```

### Failure logs

[cmake] CMake Error in CMakeLists.txt:
[cmake]   Imported target "concurrencpp::concurrencpp" includes non-existent path
[cmake] 
[cmake]     "C:/src/crcpp/build/vcpkg_installed/x64-windows/COMPONENT"
[cmake] 
[cmake]   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
[cmake] 
[cmake]   * The path was deleted, renamed, or moved to another location.
[cmake] 
[cmake]   * An install or uninstall procedure did not complete successfully.
[cmake] 
[cmake]   * The installation package was faulty and references files it does not
[cmake]   provide.
[cmake] 
[cmake] 
[cmake] 
[cmake] CMake Error in CMakeLists.txt:
[cmake]   Imported target "concurrencpp::concurrencpp" includes non-existent path
[cmake] 
[cmake]     "C:/src/crcpp/build/vcpkg_installed/x64-windows/COMPONENT"
[cmake] 
[cmake]   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
[cmake] 
[cmake]   * The path was deleted, renamed, or moved to another location.
[cmake] 
[cmake]   * An install or uninstall procedure did not complete successfully.
[cmake] 
[cmake]   * The installation package was faulty and references files it does not
[cmake]   provide.
[cmake] 
[cmake] 
[cmake] 
[cmake] CMake Error in CMakeLists.txt:
[cmake]   Imported target "concurrencpp::concurrencpp" includes non-existent path
[cmake] 
[cmake]     "C:/src/crcpp/build/vcpkg_installed/x64-windows/COMPONENT"
[cmake] 
[cmake]   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
[cmake] 
[cmake]   * The path was deleted, renamed, or moved to another location.
[cmake] 
[cmake]   * An install or uninstall procedure did not complete successfully.
[cmake] 
[cmake]   * The installation package was faulty and references files it does not
[cmake]   provide.
[cmake] 
[cmake] 
[cmake] 
[cmake] CMake Error in CMakeLists.txt:
[cmake]   Imported target "concurrencpp::concurrencpp" includes non-existent path
[cmake] 
[cmake]     "C:/src/crcpp/build/vcpkg_installed/x64-windows/COMPONENT"
[cmake] 
[cmake]   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
[cmake] 
[cmake]   * The path was deleted, renamed, or moved to another location.
[cmake] 
[cmake]   * An install or uninstall procedure did not complete successfully.
[cmake] 
[cmake]   * The installation package was faulty and references files it does not
[cmake]   provide.
[cmake] 
[cmake] 
[cmake] 
[cmake] CMake Error in CMakeLists.txt:
[cmake]   Imported target "concurrencpp::concurrencpp" includes non-existent path
[cmake] 
[cmake]     "C:/src/crcpp/build/vcpkg_installed/x64-windows/COMPONENT"
[cmake] 
[cmake]   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
[cmake] 
[cmake]   * The path was deleted, renamed, or moved to another location.
[cmake] 
[cmake]   * An install or uninstall procedure did not complete successfully.
[cmake] 
[cmake]   * The installation package was faulty and references files it does not
[cmake]   provide.
[cmake] 
[cmake] 
[cmake] 
[cmake] CMake Error in CMakeLists.txt:
[cmake]   Imported target "concurrencpp::concurrencpp" includes non-existent path
[cmake] 
[cmake]     "C:/src/crcpp/build/vcpkg_installed/x64-windows/COMPONENT"
[cmake] 
[cmake]   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
[cmake] 
[cmake]   * The path was deleted, renamed, or moved to another location.
[cmake] 
[cmake]   * An install or uninstall procedure did not complete successfully.
[cmake] 
[cmake]   * The installation package was faulty and references files it does not
[cmake]   provide.
[cmake] 
[cmake] 
[cmake] 
[cmake] CMake Error in CMakeLists.txt:
[cmake]   Imported target "concurrencpp::concurrencpp" includes non-existent path
[cmake] 
[cmake]     "C:/src/crcpp/build/vcpkg_installed/x64-windows/COMPONENT"
[cmake] 
[cmake]   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
[cmake] 
[cmake]   * The path was deleted, renamed, or moved to another location.
[cmake] 
[cmake]   * An install or uninstall procedure did not complete successfully.
[cmake] 
[cmake]   * The installation package was faulty and references files it does not
[cmake]   provide.
[cmake] 
[cmake] 
[cmake] 
[cmake] CMake Error in CMakeLists.txt:
[cmake]   Imported target "concurrencpp::concurrencpp" includes non-existent path
[cmake] 
[cmake]     "C:/src/crcpp/build/vcpkg_installed/x64-windows/COMPONENT"
[cmake] 
[cmake]   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
[cmake] 
[cmake]   * The path was deleted, renamed, or moved to another location.
[cmake] 
[cmake]   * An install or uninstall procedure did not complete successfully.
[cmake] 
[cmake]   * The installation package was faulty and references files it does not
[cmake]   provide.
[cmake] 
[cmake] 
[cmake] 
[cmake] CMake Error in CMakeLists.txt:
[cmake]   Imported target "concurrencpp::concurrencpp" includes non-existent path
[cmake] 
[cmake]     "C:/src/crcpp/build/vcpkg_installed/x64-windows/COMPONENT"
[cmake] 
[cmake]   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
[cmake] 
[cmake]   * The path was deleted, renamed, or moved to another location.
[cmake] 
[cmake]   * An install or uninstall procedure did not complete successfully.
[cmake] 
[cmake]   * The installation package was faulty and references files it does not
[cmake]   provide.
[cmake] 
[cmake] 
[cmake] 
[cmake] CMake Error in CMakeLists.txt:
[cmake]   Imported target "concurrencpp::concurrencpp" includes non-existent path
[cmake] 
[cmake]     "C:/src/crcpp/build/vcpkg_installed/x64-windows/COMPONENT"
[cmake] 
[cmake]   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
[cmake] 
[cmake]   * The path was deleted, renamed, or moved to another location.
[cmake] 
[cmake]   * An install or uninstall procedure did not complete successfully.
[cmake] 
[cmake]   * The installation package was faulty and references files it does not
[cmake]   provide.
[cmake] 
[cmake] 
[cmake] 
[cmake] CMake Error in CMakeLists.txt:
[cmake]   Imported target "concurrencpp::concurrencpp" includes non-existent path
[cmake] 
[cmake]     "C:/src/crcpp/build/vcpkg_installed/x64-windows/COMPONENT"
[cmake] 
[cmake]   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
[cmake] 
[cmake]   * The path was deleted, renamed, or moved to another location.
[cmake] 
[cmake]   * An install or uninstall procedure did not complete successfully.
[cmake] 
[cmake]   * The installation package was faulty and references files it does not
[cmake]   provide.
[cmake] 
[cmake] 
[cmake] 
[cmake] CMake Error in CMakeLists.txt:
[cmake]   Imported target "concurrencpp::concurrencpp" includes non-existent path
[cmake] 
[cmake]     "C:/src/crcpp/build/vcpkg_installed/x64-windows/COMPONENT"
[cmake] 
[cmake]   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
[cmake] 
[cmake]   * The path was deleted, renamed, or moved to another location.
[cmake] 
[cmake]   * An install or uninstall procedure did not complete successfully.
[cmake] 
[cmake]   * The installation package was faulty and references files it does not
[cmake]   provide.
[cmake] 
[cmake] 
[cmake] 
[cmake] -- Generating done (0.1s)
[cmake] CMake Generate step failed.  Build files cannot be regenerated correctly.

### Additional context

It seems that vcpkg and cmake are having an issue with the install commands in concurrencpp's CMakeLists.txt.  The resulting `vcpkg_installed/x64-windows/share/concurrencpp/concurrencppTargets.cmake` file has improperly added `COMPONENT`, which is part of the install function's optional parameters, to the INTERFACE_INCLUDE_DIRECTORIES.

The install command in `CMakeLists.txt` that seems to be causing the problem:
````
install(
  TARGETS concurrencpp
  EXPORT concurrencppTargets
  ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}"
          COMPONENT concurrencpp_Development
  INCLUDES
  DESTINATION "${concurrencpp_include_directory}"
  COMPONENT concurrencpp_Development
  LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}"
          COMPONENT concurrencpp_Runtime
          NAMELINK_COMPONENT concurrencpp_Development
  RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}" COMPONENT concurrencpp_Runtime)
````

The offending line in `concurrencppTargets.cmake`:
````
INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;${_IMPORT_PREFIX}/COMPONENT;${_IMPORT_PREFIX}/concurrencpp_Development"
````

see the full output of `concurrencppTargets.cmake`:
````
# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.24)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS concurrencpp::concurrencpp)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target concurrencpp::concurrencpp
add_library(concurrencpp::concurrencpp SHARED IMPORTED)

set_target_properties(concurrencpp::concurrencpp PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<STREQUAL:\$<TARGET_PROPERTY:concurrencpp::concurrencpp,TYPE>,SHARED_LIBRARY>:CRCPP_IMPORT_API>"
  INTERFACE_COMPILE_FEATURES "cxx_std_20"
  INTERFACE_COMPILE_OPTIONS "/permissive-"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;${_IMPORT_PREFIX}/COMPONENT;${_IMPORT_PREFIX}/concurrencpp_Development"
  INTERFACE_LINK_LIBRARIES "Threads::Threads;\$<\$<BOOL:LIBRT-NOTFOUND>:LIBRT-NOTFOUND>"
)

if(CMAKE_VERSION VERSION_LESS 2.8.12)
  message(FATAL_ERROR "This file relies on consumers using CMake 2.8.12 or greater.")
endif()

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/concurrencppTargets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
    if(NOT EXISTS "${_cmake_file}")
      message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
````

**Comment by dg0yt** [comment]
I have seen this in another package recently:
~~~
install(...
    INCLUDES DESTINATION "${concurrencpp_include_directory}"
    COMPONENT concurrencpp_Development
...
~~~~
COMPONENT can't be used after INCLUDES (as nothing is installed, only added to target properties).
https://cmake.org/cmake/help/latest/command/install.html#targets

Maybe another case for post-build checks.

**Comment by gotnone** [comment]
@dg0yt Does this mean that an issue should be opened upstream with concurrencpp?

**Comment by dg0yt** [comment]
Yes.
