### ISSUE TITLE
Install pcl:x86-windows fails on boost-regex

### ISSUE THREAD

**Issue by GoranDubajic** [Microsoft/vcpkg#3203]
Repro command: vcpkg install pcl:x86-windows
Please let me know if you need anything else.
Error output:
Elapsed time for package boost-smart-ptr:x86-windows: 3.974 s
Starting package 32/110: boost-regex:x86-windows
Building package boost-regex[core]:x86-windows...
-- CURRENT_INSTALLED_DIR=D:/source/vcpkg/0/installed/x86-windows
-- DOWNLOADS=D:/source/vcpkg/0/downloads
-- CURRENT_PACKAGES_DIR=D:/source/vcpkg/0/packages/boost-regex_x86-windows
-- CURRENT_BUILDTREES_DIR=D:/source/vcpkg/0/buildtrees/boost-regex
-- CURRENT_PORT_DIR=D:/source/vcpkg/0/ports/boost-regex/.
-- Using cached D:/source/vcpkg/0/downloads/boostorg-regex-boost-1.66.0.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Building x86-windows-rel
CMake Error at D:/source/vcpkg/0/scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: D:/source/vcpkg/0/installed/x86-windows/tools/boost-build/b2.exe;--stagedir=D:/source/vcpkg/0/buildtrees/boost-regex/x86-windows-rel/stage;--build-dir=D:/source/vcpkg/0/buildtrees/boost-regex/x86-windows-rel;--user-config=D:/source/vcpkg/0/buildtrees/boost-regex/x86-windows-rel/user-config.jam;-j8;--debug-configuration;--debug-building;--debug-generators;--disable-icu;--ignore-site-config;--hash;-q;-sZLIB_INCLUDE="D:/source/vcpkg/0/installed/x86-windows/include";-sBZIP2_INCLUDE="D:/source/vcpkg/0/installed/x86-windows/include";threading=multi;threadapi=win32;runtime-link=shared;link=shared;address-model=32;architecture=x86;toolset=msvc-14.1;-sZLIB_BINARY=zlib;-sZLIB_LIBPATH="D:/source/vcpkg/0/installed/x86-windows/lib";-sBZIP2_BINARY=bz2;-sBZIP2_LIBPATH="D:/source/vcpkg/0/installed/x86-windows/lib";variant=release;debug-symbols=on
    Working Directory: D:/source/vcpkg/0/buildtrees/boost-regex/src/regex-boost-1.66.0
    See logs for more information:

Call Stack (most recent call first):
  D:/source/vcpkg/0/installed/x86-windows/share/boost-build/boost-modular-build.cmake:236 (vcpkg_execute_required_process)
  D:/source/vcpkg/0/ports/boost-regex/portfile.cmake:20 (boost_modular_build)
  D:/source/vcpkg/0/scripts/ports.cmake:72 (include)

Error: Building package boost-regex:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-regex:x86-windows
  Vcpkg version: 0.0.107-2018-04-02-79a77a0bb761168b24ad3d1e897200f443b6287b

Additionally, attach any relevant sections from the log files above.

**Comment by Voskrese** [comment]
>  See logs for more information:

> Additionally, attach any relevant sections from the log files above.

**Comment by JackBoosY** [comment]
@GoranDubajic  could you upload more logs?

**Comment by JackBoosY** [comment]
Hi @GoranDubajic , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
