### ISSUE TITLE
protobuf:x86-windows

### ISSUE THREAD

**Issue by bidekani** [Microsoft/vcpkg#3205]
I am trying to install protobuf for windows,
I had set my HTTP_PROXY, and HTTPS_PROXY but still have error:

vcpkg install protobuf protobuf:x64-windows
The following packages will be built and installed:
    protobuf[core]:x86-windows
    protobuf[core]:x64-windows
Starting package 1/2: protobuf:x86-windows
Building package protobuf[core]:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/Users/a257885/tmp/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/Users/a257885/tmp/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/a257885/tmp/vcpkg/packages/protobuf_x86-windows

-- CURRENT_BUILDTREES_DIR=C:/Users/a257885/tmp/vcpkg/buildtrees/protobuf
-- CURRENT_PORT_DIR=C:/Users/a257885/tmp/vcpkg/ports/protobuf/.
-- Downloading https://github.com/google/protobuf/releases/download/v3.5.1/proto
buf-cpp-3.5.1.tar.gz...
-- Downloading https://github.com/google/protobuf/releases/download/v3.5.1/proto
buf-cpp-3.5.1.tar.gz... Failed. Status: 4;"A requested feature, protocol or opti
on was not found built-in in this libcurl due to a build-time decision."
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:155 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/is
sues

Call Stack (most recent call first):
  ports/protobuf/portfile.cmake:6 (vcpkg_download_distfile)
  scripts/ports.cmake:72 (include)

---
C:\Users\a257885\tmp\vcpkg>set HTTP_PROXY
HTTP_PROXY=http://myuser:mypass...@ourproxyserver:8080/
HTTPS_PROXY=https://myuser:mypass...@ourproxyserver:8080/

C:\Users\a257885\tmp\vcpkg>vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

C:\Users\a257885\tmp\vcpkg>git pull
fatal: UriFormatException encountered.
   actualUrl
Already up to date.

**Comment by Voskrese** [comment]
вручную скачайте и скопируйте в папку download, как временный вариант

> manually download and copy to the download folder as a temporary option

**Comment by JackBoosY** [comment]
Hi @bidekani , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.

**Comment by dkford6704** [comment]
Hello,

Where do we add the HTTP_PROXY and  HTTPS_PROXY variables to which files?

**Comment by JackBoosY** [comment]
@dkford6704 Just set them in  you console.

**Comment by dkford6704** [comment]
Hello @JackBoosY,

Where is the console?

**Comment by JackBoosY** [comment]
@dkford6704 you can use command to set it. Example:
```
set http_proxy=http://localhost:1080
set http_proxy_user=user
set http_proxy_pass=pwd
```

**Comment by dkford6704** [comment]
Nope, could not get it working still

**Comment by JackBoosY** [comment]
@dkford6704 Please download the source package manually and put it into _VCPKG_PATH/downloads_ and rebuild protobuf.

Thanks.
