### ISSUE TITLE
[New Port Request] apache datasketches

### ISSUE THREAD

**Issue by SimonC-Audigent** [microsoft/vcpkg#32060]
### Library name

apache datasketches

### Library description

A software library of [stochastic](https://en.wikipedia.org/wiki/Stochastic) [streaming algorithms](https://en.wikipedia.org/wiki/Streaming_algorithm).

### Source repository URL

https://github.com/apache/datasketches-cpp

### Project homepage (if different from the source repository)

https://datasketches.apache.org/

**Comment by xiaozhuai** [comment]
@SimonC-Audigent 
Please try #32786
