### ISSUE TITLE
[New Port Request] SDL3 prerelease 

### ISSUE THREAD

**Issue by apachaihop** [microsoft/vcpkg#32062]
### Library name

SDL3

### Source repository URL

https://github.com/libsdl-org/SDL.git

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by briaguya-ai** [comment]
This would be great to see! There are some exciting changes in SDL3 and it'd be wonderful to start testing them out without moving away from vcpkg!
