### ISSUE TITLE
tbb:x64-windows fails

### ISSUE THREAD

**Issue by micham1111** [Microsoft/vcpkg#3206]
Repro command: .\vcpkg install tbb:x64-windows
     Please let me know if you need anything else.
     Error output:
	 The following packages will be built and installed:
                tbb[core]:x64-windows
Starting package 1/1: tbb:x64-windows
Building package tbb[core]:x64-windows...
-- CURRENT_INSTALLED_DIR=C:/Installation/vcpkg_dir/vcpkg/installed/x64-windows
-- DOWNLOADS=C:/Installation/vcpkg_dir/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Installation/vcpkg_dir/vcpkg/packages/tbb_x64-windows
-- CURRENT_BUILDTREES_DIR=C:/Installation/vcpkg_dir/vcpkg/buildtrees/tbb
-- CURRENT_PORT_DIR=C:/Installation/vcpkg_dir/vcpkg/ports/tbb/.
-- Downloading https://github.com/01org/tbb/archive/2018_U3.tar.gz...
-- Downloading https://github.com/01org/tbb/archive/2018_U3.tar.gz... OK
-- Testing integrity of downloaded file...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:87 (message):

  File does not have expected hash:

          File path: [ C:/Installation/vcpkg_dir/vcpkg/downloads/temp/01org-tbb-2018_U3.tar.gz ]
      Expected hash: [ e92a2aabcdd456c1676eb9ce20653908a867ea18ff118f5f039823f5a10a0da3de61d0044774ad38b137e636fa8602af009dfeb59c84005fe90c6206aa3306ab ]
        Actual hash: [ 7ac74e714122e25f7704630d3d52992dbea54d1e761b5e487251a771f401aa864f78b8ddf11d78f38758088df387abb6987f6a2db562c86cbb28ba8f33a25680 ]

  The file may have been corrupted in transit.  This can be caused by
  proxies.  If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
  environment variables to
  "https://user:password@your-proxy-ip-address:port/".

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:162 (test_hash)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/tbb/portfile.cmake:10 (vcpkg_from_github)
  scripts/ports.cmake:72 (include)

**Comment by Voskrese** [comment]
не валидный хеш файл
`e92a2aabcdd456c1676eb9ce20653908a867ea18ff118f5f039823f5a10a0da3de61d0044774ad38b137e636fa8602af009dfeb59c84005fe90c6206aa3306ab `
новый правильный
`7ac74e714122e25f7704630d3d52992dbea54d1e761b5e487251a771f401aa864f78b8ddf11d78f38758088df387abb6987f6a2db562c86cbb28ba8f33a25680 `

**just edit the hash file**

**Comment by ras0219-msft** [comment]
I've change the port in master to use the exact commit hash (and updated the file hash) which should resolve this issue.
