### ISSUE TITLE
[gdal/shp] duplicate symbol link error SASetupDefaultHooks

### ISSUE THREAD

**Issue by michaeladamkatz** [microsoft/vcpkg#32070]
**Describe the bug**
I built both `gdal.lib` and `shp.lib`. When linking my program with both libraries I get an error that `SASetupDefaultHooks` is defined twice, in `shp.lib(safileio.c.obj)` and in `gdal.lib(shp_vsi.c.obj)`. If I remove `shp.lib` from the link I get 22 unresolved symbols, including `SHPCreateObject`, `DBFOpenLL`, etc. So it seems `gdal` doesn't offer those functions alone, but apparently it does offer `SASetupDefaultHooks`. Note that I get this linker error whether or not I call `SASetupDefaultHooks` in my code.

**Environment**
Windows 10 Enterprise
Visual Studio 2022

**To Reproduce**
1. `./vcpkg install gdal`, `./vcpkg install shapelib`, link a project with both
2. See error
```
1>shp.lib(safileio.c.obj) : error LNK2005: _SASetupDefaultHooks already defined in gdal.lib(shp_vsi.c.obj)
1>C:\Users\michael.katz\Documents\desktop-marplot-2\build\windows\ReleaseOptimized\MARPLOT Server.exe : fatal error LNK1169: one or more multiply defined symbols found
```

**Expected behavior**
No duplicate symbol.

**Comment by dg0yt** [comment]
I think it is not in our hands: We cannot devendor the shapelib copy in GDAL. 
https://github.com/OSGeo/gdal/issues/5711

But maybe you can help GDAL with that?

**Comment by michaeladamkatz** [comment]
See also https://github.com/OSGeo/gdal/pull/7973
