### ISSUE TITLE
[skia] include files duplicated

### ISSUE THREAD

**Issue by michaeladamkatz** [microsoft/vcpkg#32071]
**Describe the bug**
The include files for `Skia` are duplicated on the outer level (as well as in the `include` subfolder).

**Environment**
Windows 10 Enterprise
Visual Studio 2022

**To Reproduce**
1. ./vcpkg install skia
2. See image below. From what I can tell the folders in the outer level contain the same content as those in the inner level.

**Expected behavior**
I believe all of the content should be inside the inner `include` folder. This matches with how `Skia` includes the files in its C++ code. Except for the `modules` and `src` folders, which I believe belong on the outer level, peers to `include`.

**Additional context**
![Untitled](https://github.com/microsoft/vcpkg/assets/358023/81f1f0a0-8e7e-4443-9ad2-d381da9fff30)

**Comment by dg0yt** [comment]
> I believe all of the content should be inside the inner `include` folder. This matches with how `Skia` includes the files in its C++ code. Except for the `modules` and `src` folders, which I believe belong on the outer level, peers to `include`.

This is the situation with skia.
- skia itself doesn't install anything. 
- We don't the canonical spelling of `include` statements. It is not documented.
- We even don't know which includes to install.
- We do have a test port which builds the included example for CI purposes and which helps to keep an eye on the internal dependencies of the headers.

IIRC the current duplication was a deliberate decision to not break existing vcpkg users while transitioning to upstream's layout.

**Comment by michaeladamkatz** [comment]
Thanks for the info.

**Comment by jimwang118** [comment]
@michaeladamkatz Does this currently need modification?

**Comment by michaeladamkatz** [comment]
@jimwang118 No, it can be closed. It might be nice to document in some place that the .h folders are duplicated, and the right ones to use are the inner ones. But I'm not sure where that could be documented so someone like me would see it.
