### ISSUE TITLE
vcpkg_fixup_pkgconfig.cmake misbehaves when running under /tmp on macOS

### ISSUE THREAD

**Issue by comex** [microsoft/vcpkg#32087]
**Describe the bug**
(I have vcpkg checked out in `/tmp/vcpkg`.)
After installing `zlib`, `/tmp/vcpkg/installed/arm64-osx/debug/lib/pkgconfig/zlib.pc` contains:
```
includedir=/tmp/vcpkg/packages/zlib_arm64-osx/debug/include
```
This is strange for two reasons.  First, normally .pc files in vcpkg installs contain only relative paths.  Second, the path in question doesn't exist.

Why does this happen?  Well, I tracked it down…

`vcpkg_fixup_pkgconfig.cmake` attempts to edit the pkg-config file to convert absolute paths to prefix-relative ones – in this case by replacing the string `/private/tmp/vcpkg/packages/zlib_arm64-osx` with the literal string `${prefix}`.

However, the absolute paths in `zlib.pc` start with `/tmp`, not `/private/tmp`.

On macOS, `/tmp` is a symlink to `/private/tmp`.  But this behavior doesn't occur with just any symlink, nor does it depend on whether `$PWD` starts with `/tmp` or `/private/tmp` when invoking `vcpkg`.

It turns out that during the build process, CMake has actively converted `/private/tmp` to `/tmp`.  For example, `/tmp/vcpkg/buildtrees/zlib/arm64-osx-rel/cmake_install.cmake` contains:
```
set(CMAKE_INSTALL_PREFIX "/tmp/vcpkg/packages/zlib_arm64-osx")
```

This happens in `cmSystemTools::CollapseFullPath`, because the list of "translation paths" contains a mapping from `/private/tmp` to `/tmp`, because of this from `SystemTools.cxx`:
```cpp
  // The tmp path is frequently a logical path so always keep it:
  SystemTools::AddKeepPath("/tmp/");
```
`AddKeepPath` calls `realpath` and then adds a translation from the real path to the original path.

(There is also logic there that tries to add a translation if `$PWD` includes a symlink, but that doesn't seem to make a difference here; perhaps something in vcpkg is changing `$PWD` to the real path before executing cmake, I haven't checked.)

I'm not really sure of the best way to deal with this, but one possibility is for `vcpkg_fixup_pkgconfig.cmake` to check the prefix specified in the .pc file:
```
prefix=/tmp/vcpkg/packages/zlib_arm64-osx
```
and using that in addition to (or instead of) the existing replacements (`${CURRENT_PACKAGES_DIR}` and `${CURRENT_INSTALLED_DIR}`).

**Environment**
- OS: macOS 13.3 (22E252)
- Compiler: Apple clang version 14.0.3 (clang-1403.0.22.14.1)
- vcpkg: 80ecf32496c3806c5bb79bb80f029f83d058930e

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
