### ISSUE TITLE
[New Port Request] RMM [RAPIDS Memory Manager]

### ISSUE THREAD

**Issue by aavbsouza** [microsoft/vcpkg#32089]
### Library name

RMM [RAPIDS Memory Manager]

### Library description

RMM is a package that enables you to allocate device memory in a highly configurable way. For example, it enables you to allocate and use pools of GPU memory, or to use managed memory for allocations.

### Source repository URL

https://github.com/rapidsai/rmm

### Project homepage (if different from the source repository)

https://docs.rapids.ai/api/rmm/stable/

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

It is a C++/Python library from Nvidia (under the umbrela of the RAPIDS suite of software). Used to manage allocators and allocations for GPU programs.

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
