### ISSUE TITLE
[pdcurses] Incorrect link behavior

### ISSUE THREAD

**Issue by Arcnor** [microsoft/vcpkg#32094]
**Describe the bug**
Trying to use pdcurses gives the following error:

```
vcpkg_installed\x64-windows\debug\bin\pdcurses.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x338
```

This is the same problem as issue #8662, the `dll` is being added to the list of dependencies, rather than the `lib`.

**Environment**
- OS: Windows
- Compiler: MSVC 2022 14.35.32215

**To Reproduce**
1. ./vcpkg install pdcurses
2. Add `find_package(unofficial-pdcurses CONFIG REQUIRED)` and `target_link_libraries(main PRIVATE unofficial::pdcurses::pdcurses)`
3. See error

**Comment by Adela0814** [comment]
Thanks for posting this issue. I'm not able to repro this issue. Could you please provide a simple repro project?

**Comment by Arcnor** [comment]
I've created a repo on https://github.com/Arcnor/TestPDCurses but there is not much more than what I explained above...

**Comment by Adela0814** [comment]
I can repro this now. This is a port bug, I will try to fix it.
