### ISSUE TITLE
Error when trying to install a package

### ISSUE THREAD

**Issue by Robert-House** [Microsoft/vcpkg#321]
<img width="584" alt="sketch 4" src="https://cloud.githubusercontent.com/assets/7016789/20526281/ff9bbe7a-b088-11e6-9d68-fffd93a0b264.png">

Running insider pro build 14971. Successfully ran bootstrap.ps1, but when I try to install packages, I get the above error. I aliased vcpkg to my_source_dir/vcpkg/vcpkg.exe

I had no issues on the previous build and I don't know if this is related to some of the changes they have made to powershell in this build. I'll also put in a report in the feedback hub.

**Comment by ras0219-msft** [comment]
This is quite curious. I'm unable to reproduce this on 14974, so I doubt it's a windows issue. Most likely, it looks like we're not changing directory correctly [2] before calling our script to fetch required dependencies [1]. I would guess that we aren't properly detecting the vcpkg root folder.

First, what do you get as a result of `vcpkg version`? Could you confirm that you have a `.vcpkg-root` file in the root of your enlistment, along with a `scripts\fetchDependency.ps1` script from that directory?

Finally, the immediate workaround is to either:
- Run `./vcpkg.exe install sdl2` directly from the enlistment root once. That should pull down all the core dependencies and then you shouldn't hit this issue for installing other packages.
- Install CMake 3.5+ from https://cmake.org/download/. You may need to also install git.

[1] https://github.com/Microsoft/vcpkg/blob/master/toolsrc/src/vcpkg_Environment.cpp#L74
[2] https://github.com/Microsoft/vcpkg/blob/master/toolsrc/src/main.cpp#L66

**Comment by Robert-House** [comment]
Reinstalling CMake fixed it. Something must have transferred wrong when upgrading from the last build.

Thanks for the quick reply! I think you all have something great here and I am looking forward to contributing to the packages after I mess around with it some more.

Have a good holiday.
