### ISSUE TITLE
[liburing] Fails with an incorrectly installed symlink (absolute path)

### ISSUE THREAD

**Issue by RealLitb** [microsoft/vcpkg#32102]
**Describe the bug**
The liburing port creates a dev symlink for the liburing.so.2.2 symlink as follows, within the "lib/" directory:

    liburing.so -> /tmp/vcpkg-installed/vcpkg_installed/x64-linux-dynamic/lib/liburing.so.2.2                                                                   

This is incorrect, as such a package's cached binary content will be invalid when relocated. In my case, it causes linking errors since `liburing` cannot be resolved at link time. In the portfile, I don't see that the symlink is explicitly created. Maybe the bug is in the upstreams Makefile. As long as the bug persists in upstream, the port should probably have a workaround. 

**Environment**
- OS: Linux

**Comment by RealLitb** [comment]
This would indicate a nice feature request for the absolute-paths checker warning: Check not only file contents, but also where symlinks point to. I can't think of any valid usecase offhand that warrants absolute-path symlinks. Symlinks that absolutely point to vcpkg-installed-dir are most definitely always wrong.

**Comment by FrankXie05** [comment]
I think this absolute path is the result of parsing. 
```
/tmp/vcpkg-installed/vcpkg_installed/x64-linux-dynamic/lib/liburing.so.2.2    
```
https://github.com/axboe/liburing/blob/298c083d75ecde5a8833366167b3b6abff0c8d39/liburing.pc.in#L11
Make sure that vcpkg can find the lib provided by `liburing`.

May I ask if you have used the more usage we provide in your project.
https://github.com/microsoft/vcpkg/blob/master/ports/liburing/usage 

And could you please provide the error log? :)

**Comment by dg0yt** [comment]
I have difficulties to understand the response.
The root of the problem seems to be here:
https://github.com/axboe/liburing/blob/298c083d75ecde5a8833366167b3b6abff0c8d39/src/Makefile#L98-L101

... `relativelibdir` isn't relative when called as part of the vcpkg build process.

**Comment by RealLitb** [comment]
I created a port overlay and added the following to the `if(VCPKG_LIBRARY_LINKAGE STREQUAL "dynamic")` if-statement

    # JS: Fix .so dev symlink. See https://github.com/microsoft/vcpkg/issues/32102
    execute_process(
      COMMAND ln -sf liburing.so.2 ${CURRENT_PACKAGES_DIR}/lib/liburing.so
      COMMAND ln -sf liburing.so.2 ${CURRENT_PACKAGES_DIR}/debug/lib/liburing.so
    )

And it works for me. Probably it should use one of the logged execute_process variants of vcpkg though. I don't know where to fix it in the Makefiles or Configure files, so I forced my way through there.

**Comment by RealLitb** [comment]
> I think this absolute path is the result of parsing.
> 
> ```
> /tmp/vcpkg-installed/vcpkg_installed/x64-linux-dynamic/lib/liburing.so.2.2    
> ```
> 
> https://github.com/axboe/liburing/blob/298c083d75ecde5a8833366167b3b6abff0c8d39/liburing.pc.in#L11 Make sure that vcpkg can find the lib provided by `liburing`.
> 
> May I ask if you have used the more usage we provide in your project. https://github.com/microsoft/vcpkg/blob/master/ports/liburing/usage
> 
> And could you please provide the error log? :)

There is no error when building within vcpkg, because nothing depends on liburing within vcpkg itself in my case.

The error happens when I build my software. It is something like "can't find liburing" from the linker, because while pkg-config specifies "-luring", there is no suitable "liburing.so" that satisfies the linker, because it's a symlink that points to a non-existing file.  See my above "hotfix" for how it might be fixed. 

Apparently the convention is that it points to the final .so file, not to the potential soname symlink, so the correct way is to point to "liburing.so.2.2" here instead of just to "liburing.2" as I did above. Beware while the .so file has ".2.2" suffix, the port version is "2.3".

**Comment by dg0yt** [comment]
It is enough to add
~~~
    OPTIONS
        [[--libdevdir=\${prefix}/lib]]
~~~
to `vcpkg_configure_make`.
