### ISSUE TITLE
[docs] Add an example how create a custom triplet with architecture specific compiler flags (e.g. SSE, AVX)

### ISSUE THREAD

**Issue by yurybura** [microsoft/vcpkg#32111]
Discussed [here](https://github.com/microsoft/vcpkg/pull/29093#issuecomment-1522882019) and [here](https://github.com/microsoft/vcpkg/pull/29093#issuecomment-1465969155).

**Comment by JackBoosY** [comment]
I think we do need this doc.

**Comment by jimwang118** [comment]
As part of our transition to learn.microsoft.com, all new documentation-related PRs / issues should be closed and reopened against the vcpkg-docs repo. I've created a issue in the vcpkg-docs:https://github.com/microsoft/vcpkg-docs/issues/92
