### ISSUE TITLE
vcpkg copied the release dll to the debug .the cause some error !

### ISSUE THREAD

**Issue by JaosonMa** [microsoft/vcpkg#32122]
**Describe the bug**
i have install vcpkg, 
vcpkg install opencv:x64-windows
succ! 
step1: use qt-online installer install QT
step1: vs2022 create a new QT project
step2: Nuget package  install vcpkg
step3: 
`#inlucde <opencv2/opencv.hpp>

int main(){
cv::Mat = imread(R"(xxx.jpg)")
}
` 
x64-debug:
error : [ WARN:0@1.545] global loadsave.cpp:244 cv::findDecoder imread_(''): can't open/read file: check file path/integrity
x64-release:
succ
i checkd the debug dir: 
the vcpkg copied the opencv-release dll to the debug dir, then got the error.
![image](https://github.com/microsoft/vcpkg/assets/23551774/3cc6cd0c-0ee9-4c2e-b35b-4d126f9e4e3b)

**Environment**
- OS: [e.g. Windows]
- Compiler: vs2022，msvc19, c++17

i also tried other way;
stpe1: create a win32 project,not qt project
step2: then run same code , all succ

**Comment by JaosonMa** [comment]
@JackBoosY  do you have time to see what happed?

**Comment by JackBoosY** [comment]
Can you please provide all the vcpkg related logs when build your project?

**Comment by JaosonMa** [comment]
> Can you please provide all the vcpkg related logs when build your project?

where should i got the logs?
我要去那里找这个log?

**Comment by JackBoosY** [comment]
> > Can you please provide all the vcpkg related logs when build your project?
> 
> where should i got the logs? 我要去那里找这个log?

In your project build output.

**Comment by JaosonMa** [comment]
this is what i done:
step1: create a new vs2022 qt project, named vcpkg-debugerror-test
step2: add opencv code ,just cv::Mat image = cv::imread(path)
step3:build the debug x64 
step4:zip the debug log [https://github.com/JaosonMa/for-models-download/blob/master/x64.zip](url)
this is debug.exe dir 
![image](https://github.com/microsoft/vcpkg/assets/23551774/c9227c58-63c4-4742-bcd5-a02240a647bd)
this x64.zip is from here
![image](https://github.com/microsoft/vcpkg/assets/23551774/99870e93-03a5-403c-aa4e-a50f84686936)

**Comment by JackBoosY** [comment]
@Adela0814 Please verify this issue.

**Comment by Adela0814** [comment]
@JaosonMa  Could you please provide a simple reproduction project?

**Comment by JaosonMa** [comment]
I zip the qt-5.15.2-msvc2019_64.zip and the vcpkg-debugerror-test project. here[https://drive.google.com/drive/folders/1KesKIPpMnuDbA696UMUp7Eo-4TcSkgou?usp=sharing](url)
step1: install QT vs tools in the vs2022
step2: config the QT version msvc_2019_64 
step3: create an QT widgets app project 
step4: add nugets install vcpkg 
step5: add code in the main.cpp 
step6: run debugx64 -error copy the release dll to debug 
step7: run releasex64 -succ 
![4b7c5ca979c35f32442ab0e9c21d2499](https://github.com/microsoft/vcpkg/assets/23551774/fc568883-82d5-4880-9b01-2186d211ca0b)
![0abd04682bafd3dda06cedcd5ebddf98](https://github.com/microsoft/vcpkg/assets/23551774/6417e003-91b5-4020-93be-7588b78de2c2)

**Comment by JaosonMa** [comment]
@Adela0814  do you verify this Q?  i can‘t debug the code which Slow down the development speed.

**Comment by JaosonMa** [comment]
> @Adela0814 do you verify this Q? i can‘t debug the code which Slow down the development speed.

May I ask if it can be resolved soon? If not, I will temporarily use another solution and will not continue to wait. If possible, I can wait for a moment
请问近期能解决吗？ 如果不能我就暂时使用其他方案，不会继续等待，如果可以我可以等待一下

**Comment by dg0yt** [comment]
I don't know much about Visual Studio, but the logs in the zip file indicate that you are building a debug configuration (`/MDd` et al.) against the release libs from vcpkg (`/LIBPATH:"E:\PROJECT\VCPKG\VCPKG_VS2022\VCPKG\INSTALLED\X64-WINDOWS\LIB" /LIBPATH:"E:\PROJECT\VCPKG\VCPKG_VS2022\VCPKG\INSTALLED\X64-WINDOWS\LIB\MANUAL-LINK"`).

**Comment by Adela0814** [comment]
@JaosonMa In order not to affect your project progress, you can try other solutions first, and I will also investigate this issue when I have time.

**Comment by dg0yt** [comment]
@Adela0814 Can't you explain how to fix a Visual Studio debug build which is using the wrong vcpkg build type?
