### ISSUE TITLE
[icu] Build error

### ISSUE THREAD

**Issue by SI-Lab** [microsoft/vcpkg#32131]
**Operating System**= Windows 11 pro
Compiler=cmake/android sdk with ndk(\AppData\Local\Android\Sdk\ndk\25.2.9519653)/qt6 for android

**Qfield version**= 2.8.2

**triplet**=x86-android

**Failure log**

Installing 111/163 icu:x86-android...
Building icu[core]:x86-android...
-- [OVERLAY] Loading triplet configuration from: C:\Project\QField-master\vcpkg\triplets\x86-android.cmake

-- Using cached icu4c-72_1-src.tgz.

-- Cleaning sources at D:/Build/Qfield1/_deps/vcpkg-src/buildtrees/icu/src/c-72_1-src-deba61ed52.clean. Use --editable to skip cleaning for the packages you specify.

-- Extracting source D:/Build/Qfield1/_deps/vcpkg-src/downloads/icu4c-72_1-src.tgz

-- Applying patch disable-escapestr-tool.patch

-- Applying patch remove-MD-from-configure.patch

-- Applying patch fix_parallel_build_on_windows.patch

-- Applying patch fix-extra.patch

-- Applying patch mingw-dll-install.patch

-- Applying patch disable-static-prefix.patch

-- Applying patch fix-win-build.patch

-- Using source at D:/Build/Qfield1/_deps/vcpkg-src/buildtrees/icu/src/c-72_1-src-deba61ed52.clean

-- Getting CMake variables for x86-android

-- Using cached msys2-autoconf-wrapper-20221207-1-any.pkg.tar.zst.

-- Using cached msys2-automake-wrapper-20221207-1-any.pkg.tar.zst.

-- Using cached msys2-binutils-2.40-1-x86_64.pkg.tar.zst.

-- Using cached msys2-libtool-2.4.7-3-x86_64.pkg.tar.zst.

-- Using cached msys2-make-4.4.1-1-x86_64.pkg.tar.zst.

-- Using cached msys2-pkgconf-1.9.4-1-x86_64.pkg.tar.zst.

-- Using cached msys2-which-2.21-4-x86_64.pkg.tar.zst.

-- Using cached msys2-autoconf-archive-2022.09.03-1-any.pkg.tar.zst.

-- Using cached msys2-bash-5.2.015-1-x86_64.pkg.tar.zst.

-- Using cached msys2-coreutils-8.32-5-x86_64.pkg.tar.zst.

-- Using cached msys2-file-5.44-5-x86_64.pkg.tar.zst.

-- Using cached msys2-gawk-5.2.1-2-x86_64.pkg.tar.zst.

-- Using cached msys2-grep-1~3.0-6-x86_64.pkg.tar.zst.

-- Using cached msys2-gzip-1.12-2-x86_64.pkg.tar.zst.

-- Using cached msys2-diffutils-3.9-1-x86_64.pkg.tar.zst.

-- Using cached msys2-sed-4.9-1-x86_64.pkg.tar.zst.

-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.

-- Using cached msys2-autoconf2.71-2.71-1-any.pkg.tar.zst.

-- Using cached msys2-automake1.16-1.16.5-1-any.pkg.tar.zst.

-- Using cached msys2-libiconv-1.17-1-x86_64.pkg.tar.zst.

-- Using cached msys2-libintl-0.21-2-x86_64.pkg.tar.zst.

-- Using cached msys2-zlib-1.2.13-1-x86_64.pkg.tar.zst.

-- Using cached msys2-tar-1.34-3-x86_64.pkg.tar.zst.

-- Using cached msys2-findutils-4.9.0-3-x86_64.pkg.tar.zst.

-- Using cached msys2-gmp-6.2.1-2-x86_64.pkg.tar.zst.

-- Using cached msys2-gcc-libs-11.3.0-3-x86_64.pkg.tar.zst.

-- Using cached msys2-libbz2-1.0.8-4-x86_64.pkg.tar.zst.

-- Using cached msys2-liblzma-5.4.1-1-x86_64.pkg.tar.zst.

-- Using cached msys2-libzstd-1.5.4-1-x86_64.pkg.tar.zst.

-- Using cached msys2-libreadline-8.2.001-3-x86_64.pkg.tar.zst.

-- Using cached msys2-mpfr-4.2.0-2-x86_64.pkg.tar.zst.

-- Using cached msys2-libpcre-8.45-3-x86_64.pkg.tar.zst.

-- Using cached msys2-m4-1.4.19-2-x86_64.pkg.tar.zst.

-- Using cached msys2-perl-5.36.0-1-x86_64.pkg.tar.zst.

-- Using cached msys2-ncurses-6.4-1-x86_64.pkg.tar.zst.

-- Using cached msys2-libcrypt-2.1-4-x86_64.pkg.tar.zst.

-- Using msys root at D:/Build/Qfield1/_deps/vcpkg-src/downloads/tools/msys2/87962f0d86055c95

-- Generating configure for x86-android

-- Finished generating configure for x86-android

-- Using cached mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.

-- Using cached mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.

-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.

-- Using msys root at D:/Build/Qfield1/_deps/vcpkg-src/downloads/tools/msys2/5b9374e6ec2c4e17

-- Configuring x86-android-rel

-- Building x86-android-rel

CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):

    Command failed: D:/Build/Qfield1/_deps/vcpkg-src/downloads/tools/msys2/87962f0d86055c95/usr/bin/make.exe -j 5 --trace -f Makefile all
    Working Directory: D:/Build/Qfield1/_deps/vcpkg-src/buildtrees/icu/x86-android-rel/
    See logs for more information:
      D:\Build\Qfield1\_deps\vcpkg-src\buildtrees\icu\build-x86-android-rel-out.log
      D:\Build\Qfield1\_deps\vcpkg-src\buildtrees\icu\build-x86-android-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:151 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:2 (vcpkg_build_make)
  ports/icu/portfile.cmake:145 (vcpkg_install_make)
  scripts/ports.cmake:147 (include)

error: building icu:x86-android failed with: BUILD_FAILED

Someone who could help me solve this error.
Note: I have also tried triplet arm64-android with same error.

**Comment by StarGate-One** [comment]
> See logs for more information:
>  D:\Build\Qfield1\_deps\vcpkg-src\buildtrees\icu\build-x86-android-rel-out.log
>  D:\Build\Qfield1\_deps\vcpkg-src\buildtrees\icu\build-x86-android-rel-err.log

See also: https://github.com/microsoft/vcpkg/issues/30604

**Comment by dg0yt** [comment]
> clang: error: no such file or directory: 'uconvmsguconvmsg_dat.S'
> ...
> ... uconvmsg\uconvmsg_dat.S

That is an issue specific to icu on windows hosts: Not getting all `\` converted to `/` before entering the msys2/posix world which is needed to do the build. IIUC we have workarounds for certain windows-to-windows builds. Now this needs a real fix for windows-to-android builds.

**Comment by SI-Lab** [comment]
> > > > See logs for more information:
> > > > D:\Build\Qfield1_deps\vcpkg-src\buildtrees\icu\build-x86-android-rel-out.log
> > > > D:\Build\Qfield1_deps\vcpkg-src\buildtrees\icu\build-x86-android-rel-err.log
> > 
> > 
> > Thank you. I didnt fully understand the logs but bellow are the logs
> > [build-x86-android-rel-err.log](https://github.com/microsoft/vcpkg/files/11814899/build-x86-android-rel-err.log) [build-x86-android-rel-out.log](https://github.com/microsoft/vcpkg/files/11814891/build-x86-android-rel-out.log)
> 
> Were you able to fix the issue? I'm having exact same build error with arm64-android on windows

No. I am still stuck at that point. I hope we will get help.

**Comment by ASxa86** [comment]
For what it is worth. I am getting this error when attempting to build x64-android on windows.

```shell
.././../src/c-74_1-src-8ca76704fa.clean/source/common/putil.cpp:1070:55: warning: unused parameter 'name' [-Wunused-parameter]
static void u_property_read(void* cookie, const char* name, const char* value,
                                                      ^
.././../src/c-74_1-src-8ca76704fa.clean/source/common/putil.cpp:1071:38: warning: unused parameter 'serial' [-Wunused-parameter]
                            uint32_t serial) {
                                     ^
2 warnings generated.
clang: error: no such file or directory: 'uconvmsguconvmsg_dat.S'
clang: error: no input files
-- return status = 1
Error creating with assembly code. Failed command: C:/Qt/android/sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe --target=x86_64-none-linux-android21 -DANDROID -D_FORTIFY_SOURCE=2 --sysroot=C:/Qt/android/sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/windows-x86_64/sysroot -DNDEBUG -D_REENTRANT  -DU_HAVE_ELF_H=1 -DU_HAVE_STRTOD_L=0 -DU_HAVE_STRING_VIEW=1  -DU_ATTRIBUTE_DEPRECATED= -g -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wformat -Werror=format-security -fPIC -O3 -std=c11 -Wall -pedantic -Wshadow -Wpointer-arith -Wmissing-prototypes -Wwrite-strings   -c -I../.././../src/c-74_1-src-8ca76704fa.clean/source/common -I../../common -DPIC -fPIC -o uconvmsg\uconvmsg_dat.o uconvmsg\uconvmsg_dat.S
Error generating assembly code for data.
make[2]: *** [Makefile:158: uconvmsg/libuconvmsg.a] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:49: all-recursive] Error 2
make: *** [Makefile:153: all-recursive] Error 2

```

**Comment by pfhgil** [comment]
has the problem been solved?

**Comment by dg0yt** [comment]
@pfhgil The original issue was for building icu for android on windows. This is not solved AFAICT, and nobody is working on it. Use another host OS, or at least use WSL.
