### ISSUE TITLE
[qtbase] Build Failure on x64-Linux

### ISSUE THREAD

**Issue by tornupnegatives** [microsoft/vcpkg#32135]
### Operating system

Linux (Ubuntu 23.04, x86_64)

### Steps to reproduce the behavior

```Shell
1. Install dependencies from vcpkg's provision-image.sh script:
https://github.com/microsoft/vcpkg/blob/master/scripts/azure-pipelines/linux/provision-image.sh

`sudo apt install at libxt-dev gperf libxaw7-dev cifs-utils \
  build-essential g++ gfortran libx11-dev libxkbcommon-x11-dev libxi-dev \
  libgl1-mesa-dev libglu1-mesa-dev mesa-common-dev libxinerama-dev libxxf86vm-dev \
  libxcursor-dev yasm libnuma1 libnuma-dev libtool-bin \
  flex bison libbison-dev autoconf libudev-dev libncurses5-dev libtool libxrandr-dev \
  xutils-dev dh-autoreconf autoconf-archive libgles2-mesa-dev ruby-full \
  pkg-config meson nasm cmake ninja-build libxext-dev libxfixes-dev libxrender-dev \
  libxcb1-dev libx11-xcb-dev libxcb-glx0-dev libxcb-util0-dev libxcb-cursor-dev`

2. Install
`./vcpkg/vcpkg install qtbase`
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
    qtbase[brotli,concurrent,core,dbus,default-features,doubleconversion,egl,fontconfig,freetype,gui,harfbuzz,icu,jpeg,network,opengl,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,thread,widgets,xcb,xcb-xlib,xkb,xkbcommon-x11,xlib,xrender,zstd]:x64-linux -> 6.4.3#1
    qtmultimedia[core,widgets]:x64-linux -> 6.4.3
  * qtshadertools[core]:x64-linux -> 6.4.3
Additional packages (*) will be modified to complete this operation.
libsamplerate:x64-linux is already installed
libsndfile:x64-linux is already installed
Detecting compiler hash for triplet x64-linux...
Restored 0 package(s) from /home/joe/.cache/vcpkg/archives in 15.9 us. Use --debug to see more details.
Installing 1/3 qtbase:x64-linux...
Building qtbase[brotli,concurrent,core,dbus,default-features,doubleconversion,egl,fontconfig,freetype,gui,harfbuzz,icu,jpeg,network,opengl,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,thread,widgets,xcb,xcb-xlib,xkb,xkbcommon-x11,xlib,xrender,zstd]:x64-linux...
-- Using cached qtbase-everywhere-src-6.4.3.tar.xz.
-- Cleaning sources at /home/joe/Documents/Programming/TMS-Express/vcpkg/buildtrees/qtbase/src/here-src-6-645061974f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/joe/Documents/Programming/TMS-Express/vcpkg/downloads/qtbase-everywhere-src-6.4.3.tar.xz
-- Applying patch allow_outside_prefix.patch
-- Applying patch clang-cl_source_location.patch
-- Applying patch config_install.patch
-- Applying patch fix_cmake_build.patch
-- Applying patch harfbuzz.patch
-- Applying patch fix_egl.patch
-- Applying patch fix_egl_2.patch
-- Applying patch clang-cl_QGADGET_fix.diff
-- Applying patch installed_dir.patch
-- Applying patch GLIB2-static.patch
-- Applying patch dont_force_cmakecache_latest.patch
-- Using source at /home/joe/Documents/Programming/TMS-Express/vcpkg/buildtrees/qtbase/src/here-src-6-645061974f.clean
-- Configuring x64-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /home/joe/Documents/Programming/TMS-Express/vcpkg/downloads/tools/ninja/1.10.2-linux/ninja -v
    Working Directory: /home/joe/Documents/Programming/TMS-Express/vcpkg/buildtrees/qtbase/x64-linux-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      /home/joe/Documents/Programming/TMS-Express/vcpkg/buildtrees/qtbase/config-x64-linux-dbg-CMakeCache.txt.log
      /home/joe/Documents/Programming/TMS-Express/vcpkg/buildtrees/qtbase/config-x64-linux-rel-CMakeCache.txt.log
      /home/joe/Documents/Programming/TMS-Express/vcpkg/buildtrees/qtbase/config-x64-linux-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:248 (vcpkg_execute_required_process)
  ports/qtbase/cmake/qt_install_submodule.cmake:147 (vcpkg_cmake_configure)
  ports/qtbase/cmake/qt_install_submodule.cmake:330 (qt_cmake_configure)
  ports/qtbase/portfile.cmake:272 (qt_install_submodule)
  scripts/ports.cmake:147 (include)

error: building qtbase:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qtbase
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[qtbase]+Build+error&body=Copy+issue+body+from+%2Fhome%2Fjoe%2FDocuments%2FProgramming%2FTMS-Express%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by JonLiu1993** [comment]
@tornupnegatives, Please provide error log:
````
/home/joe/Documents/Programming/TMS-Express/vcpkg/buildtrees/qtbase/config-x64-linux-out.log
````

**Comment by tornupnegatives** [comment]
I was able to resolve this issue by installing the additional required packages for qt5base (although I am targeting q6) and X11

```shell
## required by qt5-base for qt5-x11extras
APT_PACKAGES="$APT_PACKAGES libxkbcommon-dev libxcb-keysyms1-dev \
  libxcb-image0-dev libxcb-shm0-dev libxcb-icccm4-dev libxcb-sync-dev \
  libxcb-xfixes0-dev libxcb-shape0-dev libxcb-randr0-dev \
  libxcb-render-util0-dev libxcb-xinerama0-dev libxcb-xkb-dev libxcb-xinput-dev"
```

[Source](https://github.com/microsoft/vcpkg/blob/master/scripts/azure-pipelines/linux/provision-image.sh)

**Comment by postmdk** [comment]
**in gentoo with libxkbcommon version 1.6.0 don`t build!**

FAILED: src/gui/CMakeFiles/Gui.dir/platform/unix/qxkbcommon.cpp.o
/usr/bin/c++ -DENABLE_PIXMAN_DRAWHELPERS -DMD4C_USE_UTF8 -DQT_ASCII_CAST_WARNINGS -DQT_BUILDING_QT -DQT_BUILD_GUI_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRE>
/home/mdk/vcpkg/buildtrees/qtbase/src/here-src-6-a9c1a5d8fb.clean/src/gui/platform/unix/qxkbcommon.cpp:242:16: error: ‘XKB_KEY_dead_lowline’ was not declared in this scope; did you mean ‘XK>
  242 |         Xkb2Qt<XKB_KEY_dead_lowline,            Qt::Key_Dead_Lowline>,
      |                ^~~~~~~~~~~~~~~~~~~~
      |                XKB_KEY_dead_belowring
/home/mdk/vcpkg/buildtrees/qtbase/src/here-src-6-a9c1a5d8fb.clean/src/gui/platform/unix/qxkbcommon.cpp:242:69: error: template argument 1 is invalid
  242 |         Xkb2Qt<XKB_KEY_dead_lowline,            Qt::Key_Dead_Lowline>,
      |                                                                     ^
/home/mdk/vcpkg/buildtrees/qtbase/src/here-src-6-a9c1a5d8fb.clean/src/gui/platform/unix/qxkbcommon.cpp:243:16: error: ‘XKB_KEY_dead_aboveverticalline’ was not declared in this scope; did yo>
  243 |         Xkb2Qt<XKB_KEY_dead_aboveverticalline,  Qt::Key_Dead_Aboveverticalline>,
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                XKB_KEY_dead_abovering
/home/mdk/vcpkg/buildtrees/qtbase/src/here-src-6-a9c1a5d8fb.clean/src/gui/platform/unix/qxkbcommon.cpp:243:79: error: template argument 1 is invalid
  243 |         Xkb2Qt<XKB_KEY_dead_aboveverticalline,  Qt::Key_Dead_Aboveverticalline>,
      |                                                                               ^
/home/mdk/vcpkg/buildtrees/qtbase/src/here-src-6-a9c1a5d8fb.clean/src/gui/platform/unix/qxkbcommon.cpp:244:16: error: ‘XKB_KEY_dead_belowverticalline’ was not declared in this scope; did yo>
  244 |         Xkb2Qt<XKB_KEY_dead_belowverticalline,  Qt::Key_Dead_Belowverticalline>,
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                XKB_KEY_dead_belowtilde
/home/mdk/vcpkg/buildtrees/qtbase/src/here-src-6-a9c1a5d8fb.clean/src/gui/platform/unix/qxkbcommon.cpp:244:79: error: template argument 1 is invalid
  244 |         Xkb2Qt<XKB_KEY_dead_belowverticalline,  Qt::Key_Dead_Belowverticalline>,
      |                                                                               ^
/home/mdk/vcpkg/buildtrees/qtbase/src/here-src-6-a9c1a5d8fb.clean/src/gui/platform/unix/qxkbcommon.cpp:245:16: error: ‘XKB_KEY_dead_longsolidusoverlay’ was not declared in this scope
  245 |         Xkb2Qt<XKB_KEY_dead_longsolidusoverlay, Qt::Key_Dead_Longsolidusoverlay>,
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mdk/vcpkg/buildtrees/qtbase/src/here-src-6-a9c1a5d8fb.clean/src/gui/platform/unix/qxkbcommon.cpp:245:80: error: template argument 1 is invalid
  245 |         Xkb2Qt<XKB_KEY_dead_longsolidusoverlay, Qt::Key_Dead_Longsolidusoverlay>,
      |                                                                                ^
/home/mdk/vcpkg/buildtrees/qtbase/src/here-src-6-a9c1a5d8fb.clean/src/gui/platform/unix/qxkbcommon.cpp:392:5: error: template argument 157 is invalid
  392 |     >::Data{}
      |     ^
/home/mdk/vcpkg/buildtrees/qtbase/src/here-src-6-a9c1a5d8fb.clean/src/gui/platform/unix/qxkbcommon.cpp:392:5: error: template argument 158 is invalid
/home/mdk/vcpkg/buildtrees/qtbase/src/here-src-6-a9c1a5d8fb.clean/src/gui/platform/unix/qxkbcommon.cpp:392:5: error: template argument 159 is invalid
/home/mdk/vcpkg/buildtrees/qtbase/src/here-src-6-a9c1a5d8fb.clean/src/gui/platform/unix/qxkbcommon.cpp:392:5: error: template argument 160 is invalid

**with libxkbcommon version 1.5.0 build is OK!**
