### ISSUE TITLE
cgicc link error in VS2015 - LNK2019

### ISSUE THREAD

**Issue by edras** [microsoft/vcpkg#3213]
Hi,

I am trying to build the examples [here](https://www.tutorialspoint.com/cplusplus/cpp_web_programming.htm). The installation of cgicc by vcpkg was fine without errors.

I just copied the example named "Simple URL Example: Get Method" in a new c++ project in VS2015 and during the linking I got lots of errors like:

`Error	LNK2019	
unresolved external symbol "__declspec(dllimport) public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall cgicc::FormEntry::operator*(void)const " (__imp_??DFormEntry@cgicc@@QBE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) referenced in function _main`

Searching for the generated cgicc.lib, it is pointed correctly by the MACRO variable:
$(VcpkgRoot)debug\lib located at Project Properties -> Linker -> General -> Additional Library Directories

What could be wrong? The compilation of cgicc was succesful without errors nor warnings.

**Comment by JackBoosY** [comment]
same in vs2017. details:
1>c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\xstring(4373): note: see declaration of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall cgicc::FormEntry::operator*(void)const " (__imp_??DFormEntry@cgicc@@QBE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) referenced in function _main
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: bool __thiscall cgicc::FormEntry::isEmpty(void)const " (__imp_?isEmpty@FormEntry@cgicc@@QBE_NXZ) referenced in function _main
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::_Vector_const_iterator<class std::_Vector_val<struct std::_Simple_types<class cgicc::FormEntry> > > __thiscall std::vector<class cgicc::FormEntry,class std::allocator<class cgicc::FormEntry> >::end(void)const " (__imp_?end@?$vector@VFormEntry@cgicc@@V?$allocator@VFormEntry@cgicc@@@std@@@std@@QBE?AV?$_Vector_const_iterator@V?$_Vector_val@U?$_Simple_types@VFormEntry@cgicc@@@std@@@std@@@2@XZ) referenced in function _main
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall cgicc::Cgicc::Cgicc(class cgicc::CgiInput *)" (__imp_??0Cgicc@cgicc@@QAE@PAVCgiInput@1@@Z) referenced in function _main
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall cgicc::Cgicc::~Cgicc(void)" (__imp_??1Cgicc@cgicc@@QAE@XZ) referenced in function _main
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::_Vector_iterator<class std::_Vector_val<struct std::_Simple_types<class cgicc::FormEntry> > > __thiscall cgicc::Cgicc::getElement(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (__imp_?getElement@Cgicc@cgicc@@QAE?AV?$_Vector_iterator@V?$_Vector_val@U?$_Simple_types@VFormEntry@cgicc@@@std@@@std@@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@@Z) referenced in function _main
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::vector<class cgicc::FormEntry,class std::allocator<class cgicc::FormEntry> > const & __thiscall cgicc::Cgicc::operator*(void)const " (__imp_??DCgicc@cgicc@@QBEABV?$vector@VFormEntry@cgicc@@V?$allocator@VFormEntry@cgicc@@@std@@@std@@XZ) referenced in function _main
1>c:\users\vzay\source\repos\ConsoleApplication1\Debug\ConsoleApplication1.exe : fatal error LNK1120: 7 unresolved externals

**Comment by JackBoosY** [comment]
Hi @edras, thanks for reporting this issue!
I've fixed it, please update vcpkg and rebuild cgicc.

Thanks.
