### ISSUE TITLE
Installing boost:x64-windows-static uses openssl dynamic libs instead of static ones

### ISSUE THREAD

**Issue by RicardoCapurro** [microsoft/vcpkg#32154]
**Describe the bug**
When compiling a visual c++ project using vcpkg static boost libs the final executable uses and requires openssl dynamic libs instead of the static ones.

**Environment**
- OS: Windows 10
- Compiler: Visual C++ 2022 Community

**To Reproduce**
git clone https://github.com/Microsoft/vcpkg.git
.\vcpkg\bootstrap-vcpkg.bat
.\vcpkg\vcpkg install boost:x64-windows-static

**Expected behavior**
.\vcpkg\vcpkg list
should return openssl:x64-windows-static being installed, instead it returns  openssl:x64-windows. Also if you compile one of the boost beast ssl examples and run dumpbin /DEPENDENTS on the final executable you will see that libcrypto-3-x64.dll and libssl-3-x64.dll dynamic libs are required.

**Comment by autoantwort** [comment]
openssl:x64-windows is installed because it is needed by python3:x64-windows, which is needed because the python3 port needs a python3 version that runs on the host system and the host triplet is `x64-windows` by default. python3:x64-windows-static does not need openssl, because of that openssl is only installed for x64-windows

**Comment by autoantwort** [comment]
> Also if you compile one of the boost beast ssl examples

I don't know how you build them, but if you want that they use a static version of openssl you first have to install a static version of openssl and use that.

**Comment by autoantwort** [comment]
> Please try to install static openssl libs also and compile the project

What is "the project"

**Comment by RicardoCapurro** [comment]
any project you compile using the static libs installed.

**Comment by jimwang118** [comment]
Can you provide an example to test?

**Comment by RicardoCapurro** [comment]
My understanding is that as a consequence of installing boost some other libraries are being compiled together with boost, but those libraries have the following consequences:
1. The target triplet of the dependent libraries is not the same of the boost target triplet
2. The libraries are exposed to the end user and take precedence over the static ones, specially if you install the static libraries too.

It is not so complicated to reproduce this problem, you only have to compile one easy main with a single call to an openssl function like OPENSSL_cleanup();, then look at the dumpbin /DEPENDENTS {executable.exe} and you will see the dynamic libs being used instead of the static ones.

I already waste too much time on this, and switched to Conan instead and have no time to contribute on this any more.
