### ISSUE TITLE
Package update fails, process attempts to use non-existent path, the package is deleted as a result

### ISSUE THREAD

**Issue by QwazyWabbitWOS** [microsoft/vcpkg#32188]
I use this PowerShell script to perform automatic updates on demand and it's been working fine for the past couple of years.

git pull
.\bootstrap-vcpkg.bat
.\vcpkg.exe update
.\vcpkg.exe upgrade --no-dry-run
.\vcpkg.exe remove --outdated

This month, the last couple of updates have failed. Here is a dump of the most recent.

remote: Enumerating objects: 459, done.
remote: Counting objects: 100% (454/454), done.
remote: Compressing objects: 100% (277/277), done.
remote: Total 459 (delta 248), reused 309 (delta 177), pack-reused 5
Receiving objects: 100% (459/459), 300.62 KiB | 1.67 MiB/s, done.
Resolving deltas: 100% (248/248), completed with 14 local objects.
From https://github.com/microsoft/vcpkg
   80ecf3249..1286cac87  master     -> origin/master
 * [new branch]          revert-32162-wolfssl_usockets -> origin/revert-32162-wolfssl_usockets
 * [new tag]             2023.06.20 -> 2023.06.20
Updating 80ecf3249..1286cac87
Fast-forward
 ports/angle/cmake-buildsystem/CMakeLists.txt       |  74 ++++++++++---
 ports/angle/portfile.cmake                         |  36 +++----
 ports/angle/vcpkg.json                             |   2 +-
 ports/async-mqtt/portfile.cmake                    |   2 +-
 ports/async-mqtt/vcpkg.json                        |   2 +-
 ports/bond/portfile.cmake                          |   8 +-
 ports/bond/vcpkg.json                              |   1 +
 ports/breakpad/CMakeLists.txt                      |   2 +-
 ports/breakpad/vcpkg.json                          |   2 +-
 ports/catch2/portfile.cmake                        |   5 +-
 ports/catch2/vcpkg.json                            |   1 +
 ports/cgns/portfile.cmake                          |   5 +-
 ports/cgns/vcpkg.json                              |   2 +-
 ports/collada-dom/use-vcpkg-minizip.patch          |  29 ++++++
 ports/collada-dom/vcpkg.json                       |   2 +-
 ports/concurrencpp/fix-missing-limits.patch        |  12 +++
 ports/concurrencpp/portfile.cmake                  |   3 +-
 ports/concurrencpp/vcpkg.json                      |   1 +
 ports/dataframe/portfile.cmake                     |   2 +-
 ports/dataframe/vcpkg.json                         |   2 +-
 ports/directxmesh/portfile.cmake                   |   9 +-
 ports/directxmesh/usage                            |   8 ++
 ports/directxmesh/vcpkg.json                       |  12 ++-
 ports/directxtex/portfile.cmake                    |  17 +--
 ports/directxtex/usage                             |   4 +
 ports/directxtex/vcpkg.json                        |  13 ++-
 ports/directxtk/portfile.cmake                     |  11 +-
 ports/directxtk/usage                              |   4 +
 ports/directxtk/vcpkg.json                         |   2 +-
 ports/directxtk12/portfile.cmake                   |  11 +-
 ports/directxtk12/usage                            |   4 +
 ports/directxtk12/vcpkg.json                       |   4 +-
 .../0001-Add-extern-C-to-avcodec.patch             |  26 -----
 ports/discordcoreapi/portfile.cmake                |   5 +-
 ports/discordcoreapi/vcpkg.json                    |   6 +-
 ports/dxut/portfile.cmake                          |   7 +-
 ports/dxut/usage                                   |   4 +
 ports/dxut/vcpkg.json                              |   2 +-
 ports/effects11/portfile.cmake                     |   7 +-
 ports/effects11/usage                              |   4 +
 ports/effects11/vcpkg.json                         |   2 +-
 ports/fluidsynth/portfile.cmake                    |   2 +-
 ports/fluidsynth/vcpkg.json                        |   3 +-
 ports/folly/openssl.patch                          |  14 +++
 ports/folly/portfile.cmake                         |   1 +
 ports/folly/vcpkg.json                             |   1 +
 ports/gul14/portfile.cmake                         |   4 +-
 ports/gul14/vcpkg.json                             |   3 +-
 ports/icu/portfile.cmake                           |   5 +-
 ports/icu/vcpkg.json                               |   3 +-
 ports/libeventheader-decode/portfile.cmake         |   4 +-
 ports/libeventheader-decode/vcpkg.json             |  10 +-
 ports/libeventheader-tracepoint/portfile.cmake     |   4 +-
 ports/libeventheader-tracepoint/vcpkg.json         |   6 +-
 ports/libhsplasma/portfile.cmake                   |   4 +-
 ports/libhsplasma/vcpkg.json                       |   3 +-
 ports/libjpeg-turbo/usage                          |   2 +-
 ports/libjpeg-turbo/vcpkg.json                     |   2 +-
 ports/libnice-gst/portfile.cmake                   |   5 +-
 ports/libnice-gst/vcpkg.json                       |   2 +-
 ports/libosmscout/portfile.cmake                   |   2 +-
 ports/libosmscout/vcpkg.json                       |   6 +-
 ports/libprotobuf-mutator/portfile.cmake           |   4 +-
 ports/libprotobuf-mutator/vcpkg.json               |   7 +-
 ports/libressl/portfile.cmake                      |   2 +
 ports/libressl/vcpkg.json                          |   1 +
 ports/libtracepoint-control/portfile.cmake         |  21 ++++
 ports/libtracepoint-control/vcpkg.json             |  22 ++++
 ports/libtracepoint-decode/portfile.cmake          |   4 +-
 ports/libtracepoint-decode/vcpkg.json              |   4 +-
 ports/libtracepoint/portfile.cmake                 |   4 +-
 ports/libtracepoint/vcpkg.json                     |   4 +-
 ports/liburing/portfile.cmake                      |   2 +
 ports/liburing/vcpkg.json                          |   1 +
 ports/libxmp/fix-uwp-build.patch                   |  26 -----
 ports/libxmp/portfile.cmake                        |   5 +-
 ports/libxmp/vcpkg.json                            |   3 +-
 ports/mp-units/config.patch                        |  15 +--
 ports/mp-units/portfile.cmake                      |  17 ++-
 ports/mp-units/vcpkg.json                          |  36 ++++++-
 ports/nanoflann/portfile.cmake                     |  10 +-
 ports/nanoflann/vcpkg.json                         |   2 +-
 ports/openblas/fix-uwp-build.patch                 |  35 -------
 ports/openblas/portfile.cmake                      |  12 +--
 ports/openblas/uwp.patch                           |  41 +++++++-
 ports/openblas/vcpkg.json                          |   3 +-
 ports/opencascade/fix-dependence.patch             |  26 +++++
 ports/opencascade/portfile.cmake                   |   1 +
 ports/opencascade/vcpkg.json                       |   2 +-
 ports/openexr/fix-arm64-windows-build.patch        |  13 +++
 ports/openexr/portfile.cmake                       |   6 +-
 ports/openexr/vcpkg.json                           |   2 +-
 .../002-typo-in-default-option-value.patch         |  13 +++
 ports/openvino/portfile.cmake                      |   3 +-
 ports/openvino/vcpkg.json                          |   1 +
 ports/palsigslot/portfile.cmake                    |   6 +-
 ports/palsigslot/vcpkg.json                        |   3 +-
 ports/pdal/fix-dependency.patch                    |  82 ++++++++++++++-
 ports/pdal/portfile.cmake                          |   2 +
 ports/pdal/vcpkg.json                              |   2 +-
 ports/qtbase/clang-cl_source_location.patch        |   2 +-
 ports/qtbase/vcpkg.json                            |   2 +-
 ports/quill/portfile.cmake                         |   2 +-
 ports/quill/vcpkg.json                             |   2 +-
 ports/redis-plus-plus/portfile.cmake               |  19 ++--
 ports/redis-plus-plus/vcpkg.json                   |  15 ++-
 ports/tabulate/portfile.cmake                      |   4 +-
 ports/tabulate/vcpkg.json                          |   2 +-
 ports/tinyexr/fix-uwp.patch                        |  12 +++
 ports/tinyexr/portfile.cmake                       |   5 +-
 ports/tinyexr/vcpkg.json                           |   2 +-
 ports/uvatlas/portfile.cmake                       |   7 +-
 ports/uvatlas/usage                                |   4 +
 ports/uvatlas/vcpkg.json                           |   4 +-
 scripts/azure-pipelines/azure-pipelines.yml        |   8 +-
 scripts/azure-pipelines/linux/create-image.ps1     |   4 +-
 scripts/azure-pipelines/linux/provision-image.sh   |  18 ++--
 scripts/ci.baseline.txt                            |  29 +++---
 .../vcpkg-find-acquire-program/portfile.cmake      |   6 +-
 versions/a-/angle.json                             |   5 +
 versions/a-/async-mqtt.json                        |   5 +
 versions/b-/bond.json                              |   5 +
 versions/b-/breakpad.json                          |   5 +
 versions/baseline.json                             | 116 +++++++++++----------
 versions/c-/catch2.json                            |   5 +
 versions/c-/cgns.json                              |   5 +
 versions/c-/collada-dom.json                       |   5 +
 versions/c-/concurrencpp.json                      |   5 +
 versions/d-/dataframe.json                         |   5 +
 versions/d-/directxmesh.json                       |   5 +
 versions/d-/directxtex.json                        |   5 +
 versions/d-/directxtk.json                         |   5 +
 versions/d-/directxtk12.json                       |   5 +
 versions/d-/discordcoreapi.json                    |   5 +
 versions/d-/dxut.json                              |   5 +
 versions/e-/effects11.json                         |   5 +
 versions/f-/fluidsynth.json                        |   5 +
 versions/f-/folly.json                             |   5 +
 versions/g-/gul14.json                             |   5 +
 versions/i-/icu.json                               |   5 +
 versions/l-/libeventheader-decode.json             |   5 +
 versions/l-/libeventheader-tracepoint.json         |   5 +
 versions/l-/libhsplasma.json                       |   5 +
 versions/l-/libjpeg-turbo.json                     |   5 +
 versions/l-/libnice-gst.json                       |   5 +
 versions/l-/libosmscout.json                       |   5 +
 versions/l-/libprotobuf-mutator.json               |   5 +
 versions/l-/libressl.json                          |   5 +
 versions/l-/libtracepoint-control.json             |   9 ++
 versions/l-/libtracepoint-decode.json              |   5 +
 versions/l-/libtracepoint.json                     |   5 +
 versions/l-/liburing.json                          |   5 +
 versions/l-/libxmp.json                            |   5 +
 versions/m-/mp-units.json                          |   5 +
 versions/n-/nanoflann.json                         |   5 +
 versions/o-/openblas.json                          |   5 +
 versions/o-/opencascade.json                       |   5 +
 versions/o-/openexr.json                           |   5 +
 versions/o-/openvino.json                          |   5 +
 versions/p-/palsigslot.json                        |   5 +
 versions/p-/pdal.json                              |   5 +
 versions/q-/qtbase.json                            |   5 +
 versions/q-/quill.json                             |   5 +
 versions/r-/redis-plus-plus.json                   |   5 +
 versions/t-/tabulate.json                          |   5 +
 versions/t-/tinyexr.json                           |   5 +
 versions/u-/uvatlas.json                           |   5 +
 167 files changed, 986 insertions(+), 400 deletions(-)
 create mode 100644 ports/concurrencpp/fix-missing-limits.patch
 create mode 100644 ports/directxmesh/usage
 create mode 100644 ports/directxtex/usage
 create mode 100644 ports/directxtk/usage
 create mode 100644 ports/directxtk12/usage
 delete mode 100644 ports/discordcoreapi/0001-Add-extern-C-to-avcodec.patch
 create mode 100644 ports/dxut/usage
 create mode 100644 ports/effects11/usage
 create mode 100644 ports/folly/openssl.patch
 create mode 100644 ports/libtracepoint-control/portfile.cmake
 create mode 100644 ports/libtracepoint-control/vcpkg.json
 delete mode 100644 ports/libxmp/fix-uwp-build.patch
 delete mode 100644 ports/openblas/fix-uwp-build.patch
 create mode 100644 ports/opencascade/fix-dependence.patch
 create mode 100644 ports/openexr/fix-arm64-windows-build.patch
 create mode 100644 ports/openvino/002-typo-in-default-option-value.patch
 create mode 100644 ports/tinyexr/fix-uwp.patch
 create mode 100644 ports/uvatlas/usage
 create mode 100644 versions/l-/libtracepoint-control.json
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2023-06-15/vcpkg.exe -> E:\developer\vcpkg\vcpkg.exe... done.
Validating signature... done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
Using local portfile versions. To update the local portfiles, use `git pull`.
The following packages differ from their port versions:
        libjpeg-turbo:x64-windows        2.1.5.1#1 -> 2.1.5.1#2
To update these packages and all dependencies, run
.\vcpkg upgrade'
To only remove outdated packages, run
.\vcpkg remove --outdated
The following packages will be rebuilt:
  * libjpeg-turbo:x64-windows -> 2.1.5.1#2
  * libjpeg-turbo:x86-windows -> 2.1.5.1#2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
Restored 0 package(s) from C:\Users\Geoff\AppData\Local\vcpkg\archives in 1.08 ms. Use --debug to see more details.
Removing 1/4 libjpeg-turbo:x64-windows
Elapsed time to handle libjpeg-turbo:x64-windows: 9.7 ms
Removing 2/4 libjpeg-turbo:x86-windows
Elapsed time to handle libjpeg-turbo:x86-windows: 9.98 ms
Installing 3/4 libjpeg-turbo:x64-windows...
Building libjpeg-turbo:x64-windows...
-- Using cached libjpeg-turbo-libjpeg-turbo-2.1.5.1.tar.gz.
-- Cleaning sources at E:/developer/vcpkg/buildtrees/libjpeg-turbo/src/2.1.5.1-f411453282.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/developer/vcpkg/downloads/libjpeg-turbo-libjpeg-turbo-2.1.5.1.tar.gz
-- Applying patch add-options-for-exes-docs-headers.patch
-- Applying patch workaround_cmake_system_processor.patch
-- Using source at E:/developer/vcpkg/buildtrees/libjpeg-turbo/src/2.1.5.1-f411453282.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig file: E:/developer/vcpkg/packages/libjpeg-turbo_x64-windows/lib/pkgconfig/libjpeg.pc
-- Fixing pkgconfig file: E:/developer/vcpkg/packages/libjpeg-turbo_x64-windows/lib/pkgconfig/libturbojpeg.pc
-- Using cached mingw-w64-i686-pkgconf-1~1.8.0-2-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using msys root at E:/developer/vcpkg/downloads/tools/msys2/6f3fa1a12ef85a6f
-- Fixing pkgconfig file: E:/developer/vcpkg/packages/libjpeg-turbo_x64-windows/debug/lib/pkgconfig/libjpeg.pc
-- Fixing pkgconfig file: E:/developer/vcpkg/packages/libjpeg-turbo_x64-windows/debug/lib/pkgconfig/libturbojpeg.pc
-- Installing: E:/developer/vcpkg/packages/libjpeg-turbo_x64-windows/share/libjpeg-turbo/copyright
-- Performing post-build validation
internal error: D:\a\_work\1\s\src\vcpkg\commands.build.cpp(888): Value was null
Please open an issue at https://github.com/microsoft/vcpkg/issues/new?template=other-type-of-bug-report.md&labels=category:vcpkg-bug with detailed steps to reproduce the problem.
There are no outdated packages.
PS E:\Developer\vcpkg>

**Comment by QwazyWabbitWOS** [comment]
Subsequent re-installation of the lost package triplets succeeds.

**Comment by autoantwort** [comment]
Duplicate of https://github.com/microsoft/vcpkg/issues/31908

**Comment by QwazyWabbitWOS** [comment]
Yep. Sure seems like it. That issue is closed as fixed but it appears it still isn't fixed.

Today:
remote: Enumerating objects: 73, done.
remote: Counting objects: 100% (46/46), done.
remote: Total 73 (delta 46), reused 46 (delta 46), pack-reused 27
Unpacking objects: 100% (73/73), 55.74 KiB | 422.00 KiB/s, done.
From https://github.com/microsoft/vcpkg
   1286cac87..288e8bebf  master     -> origin/master
Updating 1286cac87..288e8bebf
Fast-forward
 ports/baresip-libre/portfile.cmake                 |  34 +++++
 ports/baresip-libre/usage                          |   5 +
 ports/baresip-libre/vcpkg.json                     |  20 +++
 ports/baresip-libre/wip.patch                      | 154 +++++++++++++++++++++
 ports/jsonifier/portfile.cmake                     |   2 +-
 ports/jsonifier/vcpkg.json                         |   5 +-
 ports/onednn/portfile.cmake                        |   8 +-
 ports/onednn/vcpkg.json                            |   2 +-
 ports/sentry-native/portfile.cmake                 |   2 +-
 ports/sentry-native/vcpkg.json                     |   2 +-
 ports/sfml/arm64.patch                             |  21 ---
 ports/sfml/fix-dependencies.patch                  |  34 ++---
 ports/sfml/portfile.cmake                          |   5 +-
 ports/sfml/vcpkg.json                              |   6 +-
 ports/vcpkg-msbuild/portfile.cmake                 |  10 ++
 ports/vcpkg-msbuild/vcpkg-port-config.cmake        |   5 +
 ports/vcpkg-msbuild/vcpkg.json                     |  25 ++++
 ports/vcpkg-msbuild/vcpkg_msbuild.props.in         |  22 +++
 ports/vcpkg-msbuild/vcpkg_msbuild.targets.in       |  64 +++++++++
 ports/vcpkg-msbuild/vcpkg_msbuild_install.cmake    | 152 ++++++++++++++++++++
 .../z_vcpkg_msbuild_create_props.cmake             |  76 ++++++++++
 ports/vcpkg-pkgconfig-get-modules/copyright        |  23 ---
 ports/vcpkg-pkgconfig-get-modules/portfile.cmake   |   3 +-
 ports/vcpkg-pkgconfig-get-modules/vcpkg.json       |   3 +-
 .../x_vcpkg_pkgconfig_get_modules.cmake            |  36 +++--
 versions/b-/baresip-libre.json                     |   9 ++
 versions/baseline.json                             |  24 ++--
 versions/j-/jsonifier.json                         |   5 +
 versions/o-/onednn.json                            |   5 +
 versions/s-/sentry-native.json                     |   5 +
 versions/s-/sfml.json                              |   5 +
 versions/v-/vcpkg-msbuild.json                     |   9 ++
 versions/v-/vcpkg-pkgconfig-get-modules.json       |   5 +
 33 files changed, 686 insertions(+), 100 deletions(-)
 create mode 100644 ports/baresip-libre/portfile.cmake
 create mode 100644 ports/baresip-libre/usage
 create mode 100644 ports/baresip-libre/vcpkg.json
 create mode 100644 ports/baresip-libre/wip.patch
 delete mode 100644 ports/sfml/arm64.patch
 create mode 100644 ports/vcpkg-msbuild/portfile.cmake
 create mode 100644 ports/vcpkg-msbuild/vcpkg-port-config.cmake
 create mode 100644 ports/vcpkg-msbuild/vcpkg.json
 create mode 100644 ports/vcpkg-msbuild/vcpkg_msbuild.props.in
 create mode 100644 ports/vcpkg-msbuild/vcpkg_msbuild.targets.in
 create mode 100644 ports/vcpkg-msbuild/vcpkg_msbuild_install.cmake
 create mode 100644 ports/vcpkg-msbuild/z_vcpkg_msbuild_create_props.cmake
 delete mode 100644 ports/vcpkg-pkgconfig-get-modules/copyright
 create mode 100644 versions/b-/baresip-libre.json
 create mode 100644 versions/v-/vcpkg-msbuild.json
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2023-06-15/vcpkg.exe -> E:\developer\vcpkg\vcpkg.exe... done.
Validating signature... done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
Using local portfile versions. To update the local portfiles, use `git pull`.
The following packages differ from their port versions:
        vcpkg-pkgconfig-get-modules:x64-windows 2022-02-10#1 -> 2023-02-25
To update these packages and all dependencies, run
.\vcpkg upgrade'
To only remove outdated packages, run
.\vcpkg remove --outdated
The following packages will be rebuilt:
  * vcpkg-pkgconfig-get-modules:x64-windows -> 2023-02-25
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\Geoff\AppData\Local\vcpkg\archives in 515 us. Use --debug to see more details.
Removing 1/2 vcpkg-pkgconfig-get-modules:x64-windows
Elapsed time to handle vcpkg-pkgconfig-get-modules:x64-windows: 8.25 ms
Installing 2/2 vcpkg-pkgconfig-get-modules:x64-windows...
Building vcpkg-pkgconfig-get-modules:x64-windows...
-- Installing: E:/developer/vcpkg/packages/vcpkg-pkgconfig-get-modules_x64-windows/share/vcpkg-pkgconfig-get-modules/copyright
-- Performing post-build validation
internal error: D:\a\_work\1\s\src\vcpkg\commands.build.cpp(888): Value was null
Please open an issue at https://github.com/microsoft/vcpkg/issues/new?template=other-type-of-bug-report.md&labels=category:vcpkg-bug with detailed steps to reproduce the problem.

**Comment by autoantwort** [comment]
If you read the last messages of the issue you notice the issue was closed by accident because it is fixed in the not yet released version of vcpkg

**Comment by QwazyWabbitWOS** [comment]
Nothing left to do but wait for the next release then.
