### ISSUE TITLE
[protobuf] Build error

### ISSUE THREAD

**Issue by ravivaghasiya1998** [microsoft/vcpkg#32190]
During the installation of  [protobuf](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/interface/setup/installing_prerequisites.html 
) , I am getting this error. Couldn't  any solution.

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/Users/I010795/vcpkg/buildtrees/protobuf/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\I010795\vcpkg\buildtrees\protobuf\config-x64-windows-dbg-CMakeCache.txt.log
      C:\Users\I010795\vcpkg\buildtrees\protobuf\config-x64-windows-rel-CMakeCache.txt.log
      C:\Users\I010795\vcpkg\buildtrees\protobuf\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:252 (vcpkg_execute_required_process)
  ports/protobuf/portfile.cmake:36 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)

error: building protobuf:x64-windows failed with: BUILD_FAILED
Elapsed time to handle protobuf:x64-windows: 9.4 s

**Comment by autoantwort** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report an issue.

**Comment by ravivaghasiya1998** [comment]
Step 1: Clone the vcpkg repo

git clone https://github.com/Microsoft/vcpkg.git

Make sure you are in the directory you want the tool installed to before doing this.

Step 2: Run the bootstrap script to build vcpkg

.\vcpkg\bootstrap-vcpkg.bat

Install libraries for your project
vcpkg install [packages to install]

Using vcpkg with MSBuild / Visual Studio (may require elevation)
vcpkg integrate install

## steps to install protobuf and OSI library on windows. [protobuf & OSI](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/interface/setup/installing_prerequisites.html)

Dynamic Linking (NOT RECOMMENDED)
Since on Windows symbols are not exported per default, it can be kind of annoying to deal with this during protobuf header generation (see for example https://groups.google.com/g/protobuf/c/PDR1bqRazts). That is an important reason to use static linking.

Static Linking
Static linking might require to manually build protobuf. It is important to notice that on Windows you can also specify how to link against the C runtime. Basically, this can be set in CMake, e.g. https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html

Therefore, it could make sense to still dynamically link against the C Runtime when statically linking protobuf / OSI. (This is important e.g. when building shared libraries, since a static C runtime will create an isolated heap for your dll, which can lead to segfaults depending on what you expose on your public interfaces.)

The easiest way to achieve static linking on Windows without setting all the stuff manually in Cmake and building protobuf is to actually install static protobuf with dynamic c-runtime with vcpkg:

Install vcpkg as per the vcpkg documentation. Create a new triplet file for the required combination of static library linking with dynamic runtime (usually needed for dynamic linking to still work): Create a file named x64-windows-static-md.cmake in the triplets directory with the following content:

set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
Now the protobuf libraries can be built automatically using:

vcpkg install --triplet=x64-windows-static-md protobuf

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
