### ISSUE TITLE
Compiling libraries + copying dll's

### ISSUE THREAD

**Issue by razor85** [Microsoft/vcpkg#3219]
Hello there, first of all, thanks for vcpkg, it makes our (developers) life a lot easier!
I am using vcpkg toolchain (with cmake) on one of our projects to find libraries and include directories. Although it works quite well, there is one undesired side effect: Every time I compile my solution (which is composed of many, many projects), vcpkg (as a post build step) copies every library .dll to that project folder, making compilation veeeery slow (As I have too many dependencies). I believe this is a bug, since I can't control which dll's are copied to which directories and the ability to choose or not to include post/pre build events. Am I correct? There is any workaround for this? Thanks once again.

**Comment by ras0219-msft** [comment]
Thanks for the kind words!

You can change whether dependencies will be copied by setting `VCPKG_APPLOCAL_DEPS`[1] to `ON` or `OFF` before calling `add_executable` or `add_library`.

[1] https://github.com/Microsoft/vcpkg/blob/15e4f46b45c432a41ee6a962609039bc2497ec19/scripts/buildsystems/vcpkg.cmake#L139

**Comment by razor85** [comment]
Thanks for the comment. The flag did it!
