### ISSUE TITLE
[libtorch] <cuda>

### ISSUE THREAD

**Issue by WangHHY19931001** [microsoft/vcpkg#32209]
### Is your feature request related to a problem? Please describe.

libtorch need include cuda and other gpu support

### Proposed solution

add cuda & opencl & dml in features

**Comment by jimwang118** [comment]
The two features of `cuda` and `opencl` are found in the code of `libtorch`, but `dml` is not found.

**Comment by eidetic-av** [comment]
> The two features of `cuda` and `opencl` are found in the code of `libtorch`, but `dml` is not found.

Both `cuda` and `opencl` are found in the libtorch portfile but not in the vcpkg.json.

**Comment by jimwang118** [comment]
> > The two features of `cuda` and `opencl` are found in the code of `libtorch`, but `dml` is not found.
> 
> Both `cuda` and `opencl` are found in the libtorch portfile but not in the vcpkg.json.

Yes, these two features have not been added to `libtorch` yet.

**Comment by jimwang118** [comment]
No stale

**Comment by jimwang118** [comment]
The cuda feature has been added to libtorch, and this issue is now closed.
