### ISSUE TITLE
vcpkg，并没有用github下载

### ISSUE THREAD

**Issue by RainbowTaro2022** [microsoft/vcpkg#32210]
我刚刚在用vcpkg的时候，发现并没有在用github下载，是不是哪里出错了

**Comment by JonLiu1993** [comment]
@RainbowTaro2022, Thanks for posting this issue, could you please provide me a screenshot of your issue?

**Comment by LeenHawk** [comment]
In fact, partial packages are downloaded from github, like fmt or gsl.

**Comment by RainbowTaro2022** [comment]
![image](https://github.com/microsoft/vcpkg/assets/42478088/816aacad-f64f-4af0-aa16-4ecff09a6c13)

**Comment by RainbowTaro2022** [comment]
右边是我正在进行的任务，左边没有显示
我用的是fastgithub

**Comment by LeenHawk** [comment]
> 右边是我正在进行的任务，左边没有显示
> 
> 我用的是fastgithub

It's normal,gsl is downloaded from gnu for everyone

**Comment by JonLiu1993** [comment]
This is normal, not all vcpkg libraries are downloaded from github, and some libraries are downloaded from gitlab or other official websites.
