### ISSUE TITLE
[libuv] Build error

### ISSUE THREAD

**Issue by ExASN** [microsoft/vcpkg#32221]
Copy issue body from /Users/expeditoavelinodasilvaneto/MeusProjetos/WebSockets/VCPKG/vcpkg/installed/vcpkg/issue_body.md

**Comment by autoantwort** [comment]
> Copy issue body from /Users/expeditoavelinodasilvaneto/MeusProjetos/WebSockets/VCPKG/vcpkg/installed/vcpkg/issue_body.md

**Comment by JonLiu1993** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report an issue.

**Comment by JonLiu1993** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
