### ISSUE TITLE
[<port name>] build failure

### ISSUE THREAD

**Issue by ravivaghasiya1998** [microsoft/vcpkg#32230]
### Operating system

Windows

### Steps to reproduce the behavior

```Shell
Install vcpkg as per the vcpkg documentation. Create a new triplet file for the required combination of static library linking with dynamic runtime (usually needed for dynamic linking to still work): Create a file named x64-windows-static-md.cmake in the triplets directory with the following content:

set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

Now the protobuf libraries can be built automatically using:

vcpkg install --triplet=x64-windows-static-md protobuf
```

### Failure logs

C:\Users\vcpkg>vcpkg install --triplet=x64-windows-static-md protobuf

Computing installation plan...
The following packages will be built and installed:
  * protobuf:x64-windows -> 3.21.12
    protobuf:x64-windows-static-md -> 3.21.12
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
-- Using HTTP(S)_PROXY in environment variables.
Detecting compiler hash for triplet x64-windows-static-md...
Restored 0 package(s) from C:\Users\I010795\AppData\Local\vcpkg\archives in 301 us. Use --debug to see more details.
Installing 1/2 protobuf:x64-windows...
Building protobuf:x64-windows...
-- Using cached protocolbuffers-protobuf-v3.21.12.tar.gz.
-- Cleaning sources at C:/Users/I010795/vcpkg/buildtrees/protobuf/src/v3.21.12-fdb7676342.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/I010795/vcpkg/downloads/protocolbuffers-protobuf-v3.21.12.tar.gz
-- Applying patch fix-static-build.patch
-- Applying patch fix-default-proto-file-path.patch
-- Applying patch compile_options.patch
-- Using source at C:/Users/I010795/vcpkg/buildtrees/protobuf/src/v3.21.12-fdb7676342.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/Users/I010795/vcpkg/buildtrees/protobuf/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\vcpkg\buildtrees\protobuf\config-x64-windows-dbg-CMakeCache.txt.log
      C:\Users\vcpkg\buildtrees\protobuf\config-x64-windows-rel-CMakeCache.txt.log
      C:\Users\vcpkg\buildtrees\protobuf\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:252 (vcpkg_execute_required_process)
  ports/protobuf/portfile.cmake:36 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)

error: building protobuf:x64-windows failed with: BUILD_FAILED
Elapsed time to handle protobuf:x64-windows: 7.6 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.

### Additional context

_I am getting above error during installation of protobuf via vcpkg_

**Comment by FrankXie05** [comment]
Please provide the error logs:
```
C:\Users\vcpkg\buildtrees\protobuf\config-x64-windows-dbg-CMakeCache.txt.log
C:\Users\vcpkg\buildtrees\protobuf\config-x64-windows-rel-CMakeCache.txt.log
C:\Users\vcpkg\buildtrees\protobuf\config-x64-windows-out.log
```

**Comment by lixinye666** [comment]
mt.exe : general error c101008d: Failed to write the updated manifest to the resource of file "libprotoc.dll". The system cannot open the device or file specified.
ninja: build stopped: subcommand failed.
