### ISSUE TITLE
`vcpkg activate` failing in GitHub Action since April 2023

### ISSUE THREAD

**Issue by JonatanAntoni** [microsoft/vcpkg#32234]
**Describe the bug**
We are using `vcpkg activate` to install required tools into a GitHub Action Runner (ubuntu-22.04) like the following
```
 - run: |
     . <(curl https://aka.ms/vcpkg-init.sh -L)
     vcpkg activate
```

Until somewhen in April 2023 this worked as expected. Since then, the activation process is failing without any serious error message. Whatever dependency is listed first in `vcpkg-configuration.json` seems to be downloaded and extracted. But instead of proceeding the second dependency vcpkg terminates. Subsequent commands in `workflow.yml` fail due to missing tools.

**Environment**
- GitHub Action Runner `linux-latest`
- OS: Ubuntu 22.04 (same happens with 20.04)
  - last known working image ubuntu-22.04 version 20230402.1 
  - first known not working image ubuntu-22.04 version 20230426.1

**To Reproduce**
- Clone https://github.com/Open-CMSIS-Pack/vscode-get-started into GitHub Action Runner
- Run `. <(curl https://aka.ms/vcpkg-init.sh -L); vcpkg activate`

**Expected behavior**
It is expected that all dependencies from `vcpkg-configuration.json` get installed and exposed to the current environment.

**Failure logs**
https://github.com/Open-CMSIS-Pack/vscode-get-started/actions/runs/5376514960

**Comment by jimwang118** [comment]
I did not reproduce the issue locally according to the reproduction steps you provided.
1. Run the command: . <(curl https://aka.ms/vcpkg-init.sh -L)
2. Clone project: git clone https://github.com/Open-CMSIS-Pack/vscode-get-started
3. Enter the cloned project directory: cd vscode-get-started
4. Execute the command: vcpkg activate
![image](https://github.com/microsoft/vcpkg/assets/122244446/e681eb31-e394-4b49-9a49-9647235ab0b3)

**Comment by JonatanAntoni** [comment]
Hi @jimwang118,

Thanks for picking this up. I should have mentioned that we can't reproduce it on our local machines as well. It solely happens when executed as part of a GitHub Action workflow running on the default GitHub-hosted runner. So, there might be something special (or strange) when running vcpkg in a non-interactive way.

**Comment by JonatanAntoni** [comment]
I am trying to reproduce this on a code space. `vcpkg activate` starts installing cmake. During extraction it freezes at 92% (doc/cmake/html/_sources/manual/cmake-toolchains.7.rst.txt).
When I move up ninja, this one seems to be installed successfully. Again, the progress freezes again in cmake, same file.

**Comment by JonatanAntoni** [comment]
I just hit another artefact that has a similar issue: `compilers/arm/armclang` from https://artifacts.keil.arm.com/vcpkg-ce-registry/registry.zip

**Comment by VladimirUmek** [comment]
Simple reproducer can be found [by following this link](https://github.com/VladimirUmek/AVH_Project/actions/runs/5551469686/jobs/10137642354#step:3:50). Its [workflow](https://github.com/VladimirUmek/AVH_Project/actions/runs/5551469686/workflow) doesn't do anything useful, but it does show vcpkg failing.

**Comment by JonatanAntoni** [comment]
Any news here? Are we the only ones trying to activate vcpkg envs in GitHub CI?

**Comment by JonatanAntoni** [comment]
Any news? Are we the only ones running vcpkg in a GitHub CI env?

I retested in a latest code space container and there the issue doesn't occur anymore. But in a GitHub hosted runner the issue is still existent. Hence we are blocked in running CI workflows relying on vcpkg.

**Comment by JonatanAntoni** [comment]
I tested with recent 2023-08-09 and it is now working as expected.

**Comment by jimwang118** [comment]
OK, if this problem has been solved, I will close this issue.
