### ISSUE TITLE
[Visual Studio Installer] Update vcpkg version with VS Installer

### ISSUE THREAD

**Issue by TsukiZh** [microsoft/vcpkg#32236]
### Operating system

Windows

### Compiler

msvc

### Steps to reproduce the behavior

```Shell
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1825119
1. The latest version of vcpkg has been solved, but its integrated version in VS is different, causing this issue.
2. Appeared in VS 17.7 preview 3.
```

### Failure logs

Building libiconv[core]:x86-windows...
-- Installing port from location: C:\Users\bm1682\AppData\Local\vcpkg\registries\git-trees\4226589d5d658f4d96df83f8539de54dc57a5996
-- Using cached libiconv-1.17.tar.gz.
-- Extracting source C:/Users/bm1682/AppData/Local/vcpkg/downloads/libiconv-1.17.tar.gz
-- Applying patch 0002-Config-for-MSVC.patch
-- Applying patch 0003-Add-export.patch
-- Applying patch 0004-ModuleFileName.patch
-- Applying patch clang-fortify.patch
-- Using source at D:/Projekte/D0519/PCSW/Quellcode/vcpkg_installed/vcpkg/blds/libiconv/src/v1.17-84a471678e.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x86-windows
-- Using cached msys-gzip-1.11-1-x86_64.pkg.tar.zst.
-- Using cached msys-bash-5.1.008-1-x86_64.pkg.tar.zst.
-- Using cached msys-autoconf-2.71-3-any.pkg.tar.zst.
-- Using cached msys-diffutils-3.8-2-x86_64.pkg.tar.zst.
-- Using cached msys-binutils-2.37-5-x86_64.pkg.tar.zst.
-- Using cached msys-libtool-2.4.7-3-x86_64.pkg.tar.zst.
-- Using cached msys-file-5.41-2-x86_64.pkg.tar.zst.
-- Using cached msys-zlib-1.2.11-1-x86_64.pkg.tar.xz.
-- Using cached msys-libbz2-1.0.8-3-x86_64.pkg.tar.zst.
-- Using cached msys-coreutils-8.32-2-x86_64.pkg.tar.zst.
-- Using cached msys-grep-3.0-2-x86_64.pkg.tar.xz.
-- Using cached msys-sed-4.8-2-x86_64.pkg.tar.zst.
-- Using cached msys-libpcre-8.45-1-x86_64.pkg.tar.zst.
-- Using cached msys-m4-1.4.19-2-x86_64.pkg.tar.zst.
-- Using cached msys-automake-wrapper-11-4-any.pkg.tar.zst.
-- Using cached msys-gawk-5.1.0-2-x86_64.pkg.tar.zst.
-- Using cached msys-mpfr-4.1.0-1-x86_64.pkg.tar.zst.
-- Using cached msys-gmp-6.2.1-1-x86_64.pkg.tar.zst.
-- Using cached msys-libreadline-8.1.001-1-x86_64.pkg.tar.zst.
-- Using cached msys-ncurses-6.2-2-x86_64.pkg.tar.zst.
-- Using cached msys-automake1.16-1.16.3-3-any.pkg.tar.zst.
CMake Error at scripts/cmake/vcpkg_acquire_msys.cmake:79 (file):
file SHA512 failed to read file "C:/Program Files/Microsoft Visual
Studio/2022/Enterprise/VC/vcpkg/scripts/msys/compile_wrapper_consider_clang-cl.patch":
No such file or directory
Call Stack (most recent call first):
scripts/cmake/vcpkg_acquire_msys.cmake:274 (z_vcpkg_acquire_msys_declare_package)
scripts/cmake/vcpkg_configure_make.cmake:224 (vcpkg_acquire_msys)
C:/Users/bm1682/AppData/Local/vcpkg/registries/git-trees/4226589d5d658f4d96df83f8539de54dc57a5996/portfile.cmake:29 (vcpkg_configure_make)
scripts/ports.cmake:147 (include)

error: building libiconv:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with git pull and vcpkg update.
Then check for known issues at:
https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libiconv
You can submit a new issue at:
[https://github.com/microsoft/vcpkg/issues/new?title=[libiconv]+Build+error&body=Copy+issue+body+from+D%3A%2FProjekte%2FD0519%2FPCSW%2FQuellcode%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md](https://github.com/microsoft/vcpkg/issues/new?title=%5Blibiconv%5D+Build+error&body=Copy+issue+body+from+D%3A%2FProjekte%2FD0519%2FPCSW%2FQuellcode%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md)

**Comment by PhoebeHui** [comment]
Duplicated of https://github.com/microsoft/vcpkg/issues/31565.
