### ISSUE TITLE
Make binary packages available

### ISSUE THREAD

**Issue by cup** [microsoft/vcpkg#3224]
For example, Debian has a cURL source package:

http://packages.debian.org/source/buster/curl

and a cURL binary package:

http://packages.debian.org/buster/curl

it appears that VcPkg offers neither. This is somewhat acceptable with the
source package as you can just download that from the vendor directly. However
the binary packages should be made available for those who cant or wont set up
their own development environment.

**Comment by miurahr** [comment]
vcpkg is a BSD ports style project, not as same style as debian.

**Comment by patrikhuber** [comment]
> for those who cant or wont set up their own development environment.

I would argue that in that case vcpkg is not the right tool for you anyway. It is for developers, to manage dependencies. And it doesn't require admin rights, so there shouldn't be a scenario where you can't set it up.

The only thing I can think of is that vcpkg would be immensely useful to have on AppVeyor, but there, it is obviously impractical to build everything every time.

**Comment by JackBoosY** [comment]
We hope the library to match his code, because it's safe. 
And if you want use these binary packages, you also need development environment. Isn't it?
