### ISSUE TITLE
FreeType port: please vet my upstream changes

### ISSUE THREAD

**Issue by madig** [Microsoft/vcpkg#3228]
Hi!
I want to make the lives of CMake FreeType users easier: https://github.com/madig/freetype2/commits/modernize-cmake-further

Compared to 2.8, you can trim your patches already (0001 can go, 0002 can go, too, or at least the variable can be changed from the outside, 0003 can lose the `if (MSVC)`). Dependency defines need to be prefixed with `FT_`, as in `-DFT_USE_HarfBuzz=ON` or disabled with `-DCMAKE_DISABLE_FIND_PACKAGE_HarfBuzz=TRUE`.

These changes will potentially go into 2.9.1. Please have a look and review the changes from a third-party user, Windows perspective.

**Comment by alexkaratarakis** [comment]
Hi!
Removing the patches would be great!

The CMake changes look find, so I modified the freetype portfile to take them into account in this branch:
https://github.com/Microsoft/vcpkg/tree/dev/alkarata/freetype

> -DFT_USE_HarfBuzz=ON

I am guessing this should be `-DFT_WITH_HarfBuzz=ON`.

The build fails for me though, with:
```CMake Error at cmake_install.cmake:40 (file):
  file INSTALL cannot find "D:/workspace/vcpkg/buildtrees/freetype/x86-windows-dbg/include/freetype/config/ftconfig.h".```

I am looking into the reason for the failure.

**Comment by madig** [comment]
It was an oversight. Fixed in git master.
