### ISSUE TITLE
[halide] ci build failure

### ISSUE THREAD

**Issue by yurybura** [microsoft/vcpkg#32300]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
vcpkg install halide:x86-windows
```

### Failure logs
https://dev.azure.com/vcpkg/public/_build/results?buildId=91277&view=results
https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/91277/logs/118

### Additional context

Many PR have been blocked by this build error.

**Comment by jimwang118** [comment]
I reproduced this issue locally, I will try to fix it.

**Comment by dg0yt** [comment]
In vcpkg.ci failing since [20230622.1](https://dev.azure.com/vcpkg/public/_build/results?buildId=91111),  
https://dev.azure.com/vcpkg/public/_build/results?buildId=91328&view=ms.vss-test-web.build-test-results-tab&runId=151662&resultId=100746&paneView=history

**Comment by jimwang118** [comment]
An issue https://github.com/halide/Halide/issues/7667 has been created upstream to track.

**Comment by dg0yt** [comment]
Halide was updated in #32661, but the upstream issue doesn't indicate a resolution.

**Comment by jimwang118** [comment]
Halide has been updated to 17.0.1 in [36914](https://github.com/microsoft/vcpkg/pull/36914) and the issue has been fixed.
