### ISSUE TITLE
[qtwebengine] Missing nss dependency

### ISSUE THREAD

**Issue by RealLitb** [microsoft/vcpkg#32303]
### Operating system

linux

### Compiler

gcc-10

### Steps to reproduce the behavior

```Shell
./vcpkg install qtwebengine
```

### Failure logs

```
cat buildtrees/qtwebengine/config-x64-linux-dynamic-dbg-err.log

-- Support check for QtWebEngine failed: Build requires nss >= 3.26.
...
WARNING: QtWebEngine won't be built. Build requires nss >= 3.26.

```

### Additional context

It will not build QtWebEngine but only the QtPdf module. VCPKG provides a port "nss" itself. But does not specify it as a dependency for qtwebengine.

**Comment by FrankXie05** [comment]
It might just be a warning, but there is no dependency on `nss` provided by `vcpkg`. 
Could you please provide the log? I want to see if there are other detection cases?

https://github.com/qt/qtwebengine/blob/v6.5.0/configure.cmake#L543-L546:
```
add_check_for_support(
   MODULES QtWebEngine
   CONDITION NOT LINUX OR NSS_FOUND
   MESSAGE "Build requires nss >= 3.26."
)
```

**Comment by RealLitb** [comment]
I was subsequently able to build qtwebengine (it takes very long.. definitely longer than 5 hours.. ). It ran out of memory on my 32GB RAM, 12-threads CPU system (worth printing a warning before building the port..).  Here's the path to success:

- Path FFMPEG with https://aur.archlinux.org/cgit/aur.git/tree/040-ffmpeg-add-av_stream_get_first_dts-for-chromium.patch?h=ffmpeg-intel-full-git
- Build libxml2 with ICU
- Add PKG_CONFIG_PATH to point to lib/pkgconfig resp debug/lib/pkgconfig during the configure and build steps. Unfortunately, QtWebEngine is not only a CMake project but has third-party dependencies whose build systems rely on PKG_CONFIG_PATH (so CMAKE_PREFIX_PATH is not sufficient for pkgconfig to work). 
- Add lib resp debug/lib to LD_LIBRARY_PATH similar to what VCPKG does on Windows with ADD_BIN_TO_PATH. The vendored chromium build system executes built programs that were linked against target-libraries and fails otherwise. Check https://github.com/microsoft/vcpkg/issues/25475
- Install nss3-dev, cups2-dev and various X packages (like libxkbfile-dev). Just attempt building and it will helpfully point out at the very start by saying "skipping build of QtWebEngine because ..." or less helpfully on compiling ".o" file ten-thousand-x when missing some header or when running pkg-config and it fails finding the ".pc" file. Worth printing a message in the portfile with all the debian package names needed, like VCPKG does for qtbase before it starts the build. 
- There's a final issue I haven't worked-around, but I don't needed fixed personally: qtwebengine installs a designer-plugin in the wrong folder (tools/qt6/bin/designer/someso.so), thereby overwriting the "qt designer"  binary installed by qttools...).
