### ISSUE TITLE
[qt5-webengine] Build error

### ISSUE THREAD

**Issue by liuzhongyou** [microsoft/vcpkg#32311]
**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.36.32535.0
-    vcpkg-tool version: 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895
    vcpkg-scripts version: a293ce589 2023-06-28 (30 hours ago)

**To Reproduce**

`vcpkg install qt5-webengine:x64-windows`

**Failure logs**

```
-- qt5-webengine requires a lot of free disk space (>100GB), ram (>8 GB) and time (>2h per configuration) to be successfully build.
-- As such qt5-webengine is currently experimental.
-- If qt5-webengine fails post build validation please try manually reducing VCPKG_MAX_CONCURRENCY and open up an issue if it still cannot build. 
-- If it fails due to post validation the successfully installed files can be found in D:/vcpkg/packages/qt5-webengine_x64-windows 
-- and just need to be copied into D:/vcpkg/installed/x64-windows
-- Found external ninja('1.11.0').
-- Using cached qtwebengine-everywhere-opensource-src-5.15.10.tar.xz.
-- Cleaning sources at D:/vcpkg/buildtrees/qt5-webengine/src/5.15.10-979e898a31.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/qtwebengine-everywhere-opensource-src-5.15.10.tar.xz
-- Applying patch common.pri.patch
-- Applying patch gl.patch
-- Applying patch build_1.patch
-- Applying patch build_2.patch
-- Applying patch workaround-msvc2022-missing-include-in-chromium-ui-accessability.patch
-- Using source at D:/vcpkg/buildtrees/qt5-webengine/src/5.15.10-979e898a31.clean
-- Getting CMake variables for x64-windows
-- Using cached mingw-w64-i686-pkgconf-1~1.8.0-2-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using msys root at D:/vcpkg/downloads/tools/msys2/6f3fa1a12ef85a6f
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Configuring x64-windows-dbg
-- Configuring x64-windows-dbg done
-- Package build-x64-windows-dbg

```

**Additional context**

**Comment by liuzhongyou** [comment]
Last line of package-build-x64-windows-dbg-out.log is : ninja: build stopped: subcommand failed.

**Comment by FrankXie05** [comment]
```
-- qt5-webengine requires a lot of free disk space (>100GB), ram (>8 GB) and time (>2h per configuration) to be successfully build.
```
And could you please provide the error log?

**Comment by liuzhongyou** [comment]
> 

jom: D:\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\core\Makefile.gn_run.Debug [run_ninja] Error 1
jom: D:\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\core\Makefile.gn_run [debug] Error 2
jom: D:\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\core\Makefile [sub-gn_run-pro-make_first] Error 2
jom: D:\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\Makefile [sub-core-make_first] Error 2
jom: D:\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\Makefile [sub-src-make_first] Error 2

**Comment by liuzhongyou** [comment]
The problem has been resolved  because my compilation environment and OS is not in English

**Comment by FrankXie05** [comment]
Closed this issue due to https://github.com/microsoft/vcpkg/issues/32311#issuecomment-1631734417
