### ISSUE TITLE
Attempt to get cpprest fails getting zlib - MS Visual Studio 2015 professional

### ISSUE THREAD

**Issue by nigence** [Microsoft/vcpkg#3231]
I am using Windows 10 Pro, version 1709 (OS Build 16299.309)

I have Visual Studio Pro 2015.

Command 
vcpkg install cpprestsdk cpprestsdk:x64-windows 

failed with
Error: Building package zlib:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x86-windows
  Vcpkg version: 0.0.107-unknownhash

Relevant logfile is attached. It seems the Visual Studio C compiler cannot build their simple test program.

Thanks,
[config-x86-windows-out.log](https://github.com/Microsoft/vcpkg/files/1889278/config-x86-windows-out.log)

**Comment by Voskrese** [comment]
@nigence 
attach
See also "`C:/nh/vcpkg/exe-only-from-matt/vcpkg-master/buildtrees/zlib/x86-windows-rel/CMakeFiles/CMakeError.log`".

**Comment by JackBoosY** [comment]
Hi @nigence , if you still have problem, plz create a new issue.
Thx.
