### ISSUE TITLE
[python3] modules linking failure using lld-9

### ISSUE THREAD

**Issue by stepanm-aparavi** [microsoft/vcpkg#32322]
### Operating system

Ubuntu 18.04

### Compiler

clang9, libc++, lld-9

### Steps to reproduce the behavior

```Shell
`cp x64-linux-clang9-custom.cmake vcpkg/triplets/`
`./vcpkg/bootstrap-vcpkg.sh`
`./vcpkg/vcpkg install python3 --recurse --triplet x64-linux-clang9-custom`
```

### Failure logs

[build-x64-linux-clang9-custom-dbg-err.log](https://github.com/microsoft/vcpkg/files/11918014/build-x64-linux-clang9-custom-dbg-err.log)
[build-x64-linux-clang9-custom-rel-err.log](https://github.com/microsoft/vcpkg/files/11918015/build-x64-linux-clang9-custom-rel-err.log)

```
ld.lld-9: error: undefined symbol: PyModuleDef_Init
>>> referenced by _contextvarsmodule.c:65 (/home/stepan/vcpkg_python3/vcpkg/buildtrees/python3/src/v3.10.7-d76da6766d.clean/Modules/_contextvarsmodule.c:65)
>>>               build/temp.linux-x86_64-3.10-pydebug/home/stepan/vcpkg_python3/vcpkg/buildtrees/python3/src/v3.10.7-d76da6766d.clean/Modules/_contextvarsmodule.o:(PyInit__contextvars)

ld.lld-9: error: undefined symbol: PyContext_CopyCurrent
>>> referenced by _contextvarsmodule.c:19 (/home/stepan/vcpkg_python3/vcpkg/buildtrees/python3/src/v3.10.7-d76da6766d.clean/Modules/_contextvarsmodule.c:19)
>>>               build/temp.linux-x86_64-3.10-pydebug/home/stepan/vcpkg_python3/vcpkg/buildtrees/python3/src/v3.10.7-d76da6766d.clean/Modules/_contextvarsmodule.o:(_contextvars_copy_context_impl)

...
``` 

### Additional context

Custom triplet [x64-linux-clang9-custom.cmake.tar.gz](https://github.com/microsoft/vcpkg/files/11918085/x64-linux-clang9-custom.cmake.tar.gz)

**Comment by stepanm-aparavi** [comment]
I found that building python built-in modules failed because of static CRT linking. Building is ok with dynamic CRT linking. Is that a valid behavior? Is static CRT not supported by python3 package any more?
```cmake
set(VCPKG_CRT_LINKAGE dynamic)
```

**Comment by Osyotr** [comment]
> Is static CRT not supported by python3 package any more?

It is not well supported by pretty much any package on linux.
Just a guess: ` -Wl,--no-export-dynamic` in your triplet might cause this issue.

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
