### ISSUE TITLE
[boost] Can't override Boost_COMPILER when building with clang-cl

### ISSUE THREAD

**Issue by lemourin** [microsoft/vcpkg#32336]
vcpkg overrides Boost_COMPILER [here](https://github.com/microsoft/vcpkg/blob/master/ports/boost-uninstall/vcpkg-cmake-wrapper.cmake#L9) regardless of whether user tries to set this flag in either toolchain file or cmake cache. This is a problem when trying to build with clang-cl, for which the Boost_COMPILER flag should be "-clangw143". When this flag is not set correctly then cmake can't find boost libraries.

I'm trying to build a library that depends on boost-regex using x64-win-llvm-static triplet from [here](https://github.com/Neumann-A/my-vcpkg-triplets).

**Comment by Neumann-A** [comment]
Use `boost-uninstall` and `boost-modular-build-helper` from https://github.com/Neumann-A/my-vcpkg-ports or #27694

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.

**Comment by lemourin** [comment]
No plans to upstream the fix?

**Comment by JonLiu1993** [comment]
@lemourin, If there is an update to this issue I will reopen it.

**Comment by DKGH** [comment]
> Use `boost-uninstall` and `boost-modular-build-helper` from https://github.com/Neumann-A/my-vcpkg-ports or #27694

This solution is no longer working.

**Comment by Neumann-A** [comment]
What exactly is not working? Logs please.

**Comment by DKGH** [comment]
Similar error as here. I logged the issue here #35369 without referring to your ports. But you can test with your ports with the same result for `boost-coroutine`.

**Comment by DKGH** [comment]
I retested it. If I keep only the following of your ports, it doesn't work: `boost-all`, `boost-modular-build-helper`, and `boost-uninstall`. If I use the whole of your folder, it does. Which other ports are necessary for boost-coroutine to compile?

**Comment by Neumann-A** [comment]
ah probably `vcpkg-cmake-get-vars`

**Comment by DKGH** [comment]
This worked.
