### ISSUE TITLE
[atlmfc] Build error

### ISSUE THREAD

**Issue by AymanAliH1** [microsoft/vcpkg#32345]
Package: atlmfc:x86-windows -> 0#2

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.24.28314.0
-    vcpkg-tool version: 2023-06-22-f19f3d9939100085fe2f7e41502d60b08e2083b6
    vcpkg-scripts version: 4a3c366f2 2023-06-30 (26 hours ago)

**To Reproduce**

`vcpkg install llvm opencv4[contrib,nonfree]`

**Failure logs**
```
CMake Error at ports/atlmfc/portfile.cmake:7 (message):
  Unable to locate 'afxres.h'.  Ensure you have installed the ATL/MFC
  component of Visual Studio.
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)
```
**Additional context**

**Comment by dg0yt** [comment]
> Ensure you have installed the ATL/MFC
>   component of Visual Studio.

Didn't this help?

**Comment by Adela0814** [comment]
@AymanAliH1 Please install ATL/MFC component of Visual Studio first. 
If this doesn't solve your problem, please use this command: `.\vcpkg.exe install atlmfc:x64-windows --debug` and send the complete log to us.

**Comment by Adela0814** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
