### ISSUE TITLE
[New Port Request] boost-redis

### ISSUE THREAD

**Issue by cthulhu-irl** [microsoft/vcpkg#32353]
### Library name

boost-redis

### Library description

An async redis client designed for performance and scalability.

### Source repository URL

https://github.com/boostorg/redis

### Project homepage (if different from the source repository)

https://boostorg.github.io/redis

**Comment by jbrezina** [comment]
The issue [Integrate Boost.Redis in the Boost build system](https://github.com/boostorg/redis/issues/118) in the library is still open, so it looks like it will take a while yet

**Comment by jbrezina** [comment]
Now waiting for version 1.84 of boost libraries, which is currently in beta

**Comment by jbrezina** [comment]
boost 1.84 is released and contains redis library, so everything is ready, I suppose

**Comment by jbrezina** [comment]
This one should be resolved by [[boost] update to 1.84.0](https://github.com/microsoft/vcpkg/issues/35685)

**Comment by cthulhu-irl** [comment]
It's been added since this merge: https://github.com/microsoft/vcpkg/pull/35693
