### ISSUE TITLE
[mysql-connector-cpp] Build failure

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vcpkg#32356]
Package: mysql-connector-cpp[core,jdbc]:arm64-osx -> 8.0.32

**Host Environment**

- Host: arm64-osx
- Compiler: AppleClang 14.0.3.14030022
-    vcpkg-tool version: 2999-12-31-unknownhash
    vcpkg-scripts version: 64adda19c 2023-07-02 (7 hours ago)

**To Reproduce**

`vcpkg install --enforce-port-checks --allow-unsupported`

**Failure logs**

```
-- Using cached mysql-mysql-connector-cpp-8.0.32.tar.gz.
-- Extracting source /Users/leanderSchulten/git_projekte/vcpkg/downloads/mysql-mysql-connector-cpp-8.0.32.tar.gz
-- Applying patch fix-static-build8.patch
-- Applying patch export-targets.patch
-- Applying patch dependencies.patch
-- Using source at /Users/leanderSchulten/git_projekte/vcpkg/buildtrees/mysql-connector-cpp/src/8.0.32-0039c1a6e0.clean
-- Configuring arm64-osx
-- Building arm64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: /Users/leanderSchulten/git_projekte/vcpkg/downloads/tools/cmake-3.25.1-osx/cmake-3.25.1-macos-universal/CMake.app/Contents/bin/cmake --build . --config Debug --target install -- -v -j11
    Working Directory: /Users/leanderSchulten/git_projekte/vcpkg/buildtrees/mysql-connector-cpp/arm64-osx-dbg
    See logs for more information:
      /Users/leanderSchulten/git_projekte/vcpkg/buildtrees/mysql-connector-cpp/install-arm64-osx-dbg-err.log

Call Stack (most recent call first):
  vcpkg_installed/arm64-osx/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  vcpkg_installed/arm64-osx/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/mysql-connector-cpp/portfile.cmake:45 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)



```
<details><summary>/Users/leanderSchulten/git_projekte/vcpkg/buildtrees/mysql-connector-cpp/install-arm64-osx-dbg-err.log</summary>

```
ninja: error: 'MYSQL_LIB-NOTFOUND', needed by 'jdbc/libconnector-jdbc-deps.dylib', missing and no known rule to make it
```
</details>

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg.schema.json",
  "name": "lichtsteuerung",
  "version-string": "2.0 $.0",
  "dependencies": [
    {
      "name": "mysql-connector-cpp",
      "default-features": false,
      "features": [
        "jdbc"
      ]
    }
  ],
  "$overrides": [
    {
      "name": "capstone",
      "version": "4.0.1-120373dc"
    }
  ],
  "$builtin-baseline": "338f99eed499b6df1628829e40695b396a70a1f7"
}

```
</details>

**Comment by jimwang118** [comment]
The same problem occurs under x64-osx, this is an issue.

**Comment by dg0yt** [comment]
... and x64-linux. 

However, not unexpected. Recently [I wrote](https://github.com/microsoft/vcpkg/pull/30869#issuecomment-1515769362)

> As an extra note, IMO the port deserves more work. For example it should really use a standard `find_package(ZLIB REQUIRED)` instead of custom zlib lookup code.

[and](https://github.com/microsoft/vcpkg/pull/30869#issuecomment-1588564332)

> Oh, they really circumvent canonical find_package(...) calls even for zlib and openssl?
If not restoring find_package, this port will be hard to maintain and use: duplicating what we already maintain in wrappers and still not delivering imported targets which CMake can identify with canonical targets such as ZLIB::ZLIB or OpenSSL::SSL.

**Comment by jimwang118** [comment]
@kotori2 Do you have any good solution?

**Comment by kotori2** [comment]
I observed really weird results. It seems that arguments after `MAYBE_UNUSED_VARIABLES` are all ignored. It leads to incorrect `MYSQL_LIB` result. 
If I move everything before `MAYBE_UNUSED_VARIABLES`, everything will works fine. 
```cmake
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    WINDOWS_USE_MSBUILD
    OPTIONS
        -DWITH_SSL=${CURRENT_INSTALLED_DIR}
        -DWITH_LZ4=${CURRENT_INSTALLED_DIR}
        -DWITH_ZLIB=${CURRENT_INSTALLED_DIR}
        -DWITH_ZSTD=${CURRENT_INSTALLED_DIR}
        -DWITH_PROTOBUF=${CURRENT_INSTALLED_DIR}
        -DBUILD_STATIC=${BUILD_STATIC}
        -DSTATIC_MSVCRT=${STATIC_MSVCRT}
        -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}
        -DWITH_JDBC=${WITH_JDBC}  # the following variables are only used by jdbc
        -DMYSQL_INCLUDE_DIR="${CURRENT_INSTALLED_DIR}/include/mysql"
        -DMYSQL_LIB_DIR=${CURRENT_INSTALLED_DIR}
    MAYBE_UNUSED_VARIABLES  # and they are windows only
        -DWITH_BOOST=${CURRENT_INSTALLED_DIR}
)
```
Am I doing anything wrong?
