### ISSUE TITLE
libffi patch for Windows and MinGW is incorrect for x64-mingw-static

### ISSUE THREAD

**Issue by comex** [microsoft/vcpkg#32358]
**Describe the bug**
`ports/libffi/portfile.cmake` contains:
```cmake
if(VCPKG_TARGET_IS_WINDOWS OR VCPKG_TARGET_IS_MINGW)
    if(NOT DEFINED VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "release")
        vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/lib/pkgconfig/libffi.pc"
            "-lffi" "-llibffi")
    endif()
    if(NOT DEFINED VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "debug")
        vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/debug/lib/pkgconfig/libffi.pc"
            "-lffi" "-llibffi")
    endif()
endif()
```

This seems to make sense for `x64-mingw-dynamic`; the relevant installed contents are as follows (where the library you have to link to has an extra `lib` in its filename):
```
installed/x64-mingw-dynamic/debug/bin/libffi.dll
installed/x64-mingw-dynamic/debug/lib/liblibffi.dll.a
```

But it's surely wrong for `x64-mingw-static`, where the library does not have a doubled `lib`:
```
installed/x64-mingw-static/debug/lib/libffi.a
```

As for native Windows targets, #19655 changed the string replacement to also apply to them, whereas previously they applied only to MinGW.  But I don't understand why this would be necessary, since for both `x64-windows` and `x64-windows-static`, there is no doubled `lib`:
```
installed/x64-windows/debug/bin/libffi.dll
installed/x64-windows/debug/lib/libffi.lib
installed/x64-windows-static/debug/lib/libffi.lib
```

Then again, I don't understand how or where these pkg-config files are even used with MSVC.

**Environment**
- OS: Windows (also reproducible when cross-compiling to Windows)
- Compiler: MinGW-w64 [whatever version came with Git version `2.41.0.windows.1`]; MSVC 2022
- vcpkg: 64adda19c86e89526b5e27703a193c14477cce07

**Comment by dg0yt** [comment]
> But I don't understand why this would be necessary, since for both `x64-windows` and `x64-windows-static`, there is no doubled `lib`

For MSVC, `lib` isn't an implicit prefix. To link to `libffi.lib`, the pc file really needs `-llibffi`.

For mingw-static, the issue is real. I would prefer if the `liblib` was completely avoided, and the text replacement could be limited to non-mingw.

**Comment by dg0yt** [comment]
> Then again, I don't understand how or where these pkg-config files are even used with MSVC.

FTR they can be used easily with pkg-config or pkgconf with `--msvc-syntax`, or even via CMake `FindPkgConfig.cmake`. In contrast to the port's CMake config, these files are supported upstream, i.e. expected to work without vcpkg lock-in.
