### ISSUE TITLE
Misnamed library pthreadsVC2.dll, should be pthreadVC2.dll (without 's')

### ISSUE THREAD

**Issue by ProjectManagement17** [Microsoft/vcpkg#3236]
I'm no expert, but the software I was trying to compile (libfreenect) searches for pthreadVC2.dll without an 's' in the name. A google search suggests this is the correct name. After running `vcpkg install pthreads`, I only get pthreadsVC2.dll/.lib. Should this be changed?

**Comment by carlo-bramini** [comment]
I discovered that too and I confirm the issue.
At the moment, it seems that these files also need to be updated if the correct library name will be restored:

ports\mosquitto\0001-win64-cmake.patch
ports\mosquitto\cmake.patch
ports\mosquitto\cmake-2.patch
ports\flint\dll_flint.patch

in addition to these ones:

ports\pthreads\CMakeLists.txt
ports\pthreads\portfile.cmake

**Comment by JackBoosY** [comment]
@ProjectManagement17 I found port "libfreenect2"  instead of "libfreenect", and I built it successful. Is these same port what your said?

**Comment by vicroms** [comment]
I confirmed that the correct name should not contain an **'s'**, `pthread` not `pthreads`.

Modifying the `CMakeLists.txt` in the pthreads port to produce the correct names should fix it.

@carlo-bramini it looks like you already went through the trouble of making this change, can you submit a PR with your modifications?

**Comment by carlo-bramini** [comment]
In my opinion, the current port of pthread-win32 included into vcpkg should be abandoned because it is quite old and `pthread4w` should be used instead, which is made by the same author. The new libraries improved and they also include support for ARM64 in the code into the repository.

https://sourceforge.net/projects/pthreads4w/

**Comment by JackBoosY** [comment]
Hi @ProjectManagement17  @carlo-bramini , Thanks for reporting this issue!
This bug has been fixed. Plz update and rebuild it.
Thx.
