### ISSUE TITLE
[live555] build failure

### ISSUE THREAD

**Issue by chenpei2** [microsoft/vcpkg#32387]
### Operating system

linux

### Steps to reproduce the behavior

```Shell
./vcpkg install live555:x64-linux
```

### Failure logs

error: Failed to download from mirror set
error: http://live555.com/liveMedia/public/live.2023.06.10.tar.gz: curl failed to download with exit code 22
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

curl: (22) The requested URL returned error: 404 Not Found

### Additional context

The newest version from this source is http://live555.com/liveMedia/public/live.2023.06.20.tar.gz. However I'm afraid that would be invalid after some time.Maybe it should be replaced with other source for good.

**Comment by jimwang118** [comment]
This issue could be reproduced with vcpkg 2023-06-22-f19f3d9939100085fe2f7e41502d60b08e2083b6. I will try to fix it.
