### ISSUE TITLE
Binary caching does not work for machines using different cmake & powershell versions

### ISSUE THREAD

**Issue by jonathanou** [microsoft/vcpkg#32407]
**Describe the bug**
Currently, the cmake and powershell version numbers affects the ABI hash.  This means if a developer uses a different cmake or powershell version than the machine used to build the cached binaries, the developer cannot take advantage of binary caching.

At the same time, though vcpkg lists the versions of cmake and powershell it wants to use in `vcpkgTools.xml`, it seems to [treat them as *minimum* versions](https://github.com/microsoft/vcpkg-tool/blob/776e6bbb67c07e777aeea8f8504c874b4bc62703/src/vcpkg/tools.cpp#L756).  Thus if a developer's cmake and powershell version is newer than vcpkg, then binary caching basically stops working for them unless another developer has the exact same cmake/powershell versions.

This issue doesn't just occur between different machines, it can happen on the same machine when building in Visual Studio versus building in the command line.  Visual Studio ships with its own cmake and the version can change when updating Visual Studio.

It seems to me there is an inconsistency here.  If the version of cmake and powershell can potentially affect ABI, then vcpkg should always use the exact version as specified by `vcpkgTools.xml`;  if the cmake/powershell versions don't matter for reproducible builds, then the version numbers shouldn't participate in ABI hash generation.

I realize there is `VCPKG_FORCE_DOWNLOADED_BINARIES` environment variable that can force cmake and powershell versions to be consistent, but this is off by default.  This makes binary caching unusable for large team deployments *by default*.

**Environment**
- OS: Windows
- Compiler: any

**To Reproduce**
1. Install cmake 3.25 and powershell 7.3.5
2. Install vcpkg
3. Install latest Visual Studio (which installs a local cmake 3.26)
4. Create cmakelists.txt that has `find_package(zlib)`
5. Go to Visual Studio and generate the cmake cache from cmakelists.txt.  Zlib will be built and cached in `%appdata%/local/vcpkg/archive`
6. Delete the cmake cache.
7. Go to powershell and generate the cmake cache.  Note that zlib is rebuilt again;  the cached binary is not reused.

**Expected behavior**
Cached binary is used for both Visual Studio and powershell cmake cache generation.

**Failure logs**
None.

**Comment by Neumann-A** [comment]
You are looking for the option called: `--x-abi-tools-use-exact-versions`

**Comment by jonathanou** [comment]
> You are looking for the option called: `--x-abi-tools-use-exact-versions`

Thanks for the info, I will give that a shot!  I'm a little concerned about relying on an experimental option, but hopefully this option becomes the default behavior once a non-default binary caching (e.g. nuget) is enabled.

I noticed from #29090 that I will also need to make sure the vcpkg commit is the same across all developers as well, so that the cmake and powershell versions are all the same.  It would be nicer if the baseline commit in `vcpkg.json` is also used for determining cmake and powershell versions.

**Comment by jimwang118** [comment]
No stale

**Comment by jimwang118** [comment]
This issue has been fixed by PR [234](https://github.com/microsoft/vcpkg-tool/pull/234).
