### ISSUE TITLE
Bootstrap bash script fails on path with spaces on Windows

### ISSUE THREAD

**Issue by Arcnor** [microsoft/vcpkg#32405]
**Describe the bug**
When running the bootstrap script on a path with spaces while using git for Windows's bash, you get a failure. I'm assuming this is supported given that the script itself references "git for Windows".

**Environment**
- OS: Windows 10

**To Reproduce**
1. Create a path with spaces like "/c/super project"
2. Clone vcpkg
3. Call `./vcpkg/bootstrap-vcpkg.sh` from a bash terminal (using git for Windows)
4. Get an error about "super" not being a valid command (from my current example)

**Expected behavior**
Should bootstrap correctly, like when using Powershell.

**Comment by Neumann-A** [comment]
You will automatically run in problems building stuff with spaces in path. Just avoid it. As soon as you hit a port with `vcpkg_configure_make` you'll probably get build failures.

**Comment by Adela0814** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
