### ISSUE TITLE
[boost-build] build failure

### ISSUE THREAD

**Issue by NocturnesLK** [microsoft/vcpkg#32400]
### Operating system

Windows10

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
vcpkg install pcl:x64-windows --only-downloads
vcpkg install pcl:x64-windows
```

### Failure logs

vcpkg install pcl:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * boost-algorithm:x64-windows -> 1.82.0#2
  * boost-asio:x64-windows -> 1.82.0#3
  * boost-atomic:x64-windows -> 1.82.0#3
  * boost-build:x64-windows -> 1.82.0#2
  * boost-chrono:x64-windows -> 1.82.0#2
  * boost-container:x64-windows -> 1.82.0#2
  * boost-context:x64-windows -> 1.82.0#2
  * boost-coroutine:x64-windows -> 1.82.0#2
  * boost-date-time:x64-windows -> 1.82.0#2
  * boost-exception:x64-windows -> 1.82.0#2
  * boost-filesystem:x64-windows -> 1.82.0#2
  * boost-foreach:x64-windows -> 1.82.0#2
  * boost-graph:x64-windows -> 1.82.0#2
  * boost-interprocess:x64-windows -> 1.82.0#2
  * boost-iostreams[bzip2,core,lzma,zlib,zstd]:x64-windows -> 1.82.0#2
  * boost-lexical-cast:x64-windows -> 1.82.0#2
  * boost-math:x64-windows -> 1.82.0#2
  * boost-phoenix:x64-windows -> 1.82.0#2
  * boost-property-map:x64-windows -> 1.82.0#2
  * boost-property-tree:x64-windows -> 1.82.0#2
  * boost-proto:x64-windows -> 1.82.0#2
  * boost-ptr-container:x64-windows -> 1.82.0#2
  * boost-random:x64-windows -> 1.82.0#2
  * boost-range:x64-windows -> 1.82.0#2
  * boost-regex:x64-windows -> 1.82.0#2
  * boost-serialization:x64-windows -> 1.82.0#2
  * boost-sort:x64-windows -> 1.82.0#2
  * boost-spirit:x64-windows -> 1.82.0#2
  * boost-system:x64-windows -> 1.82.0#2
  * boost-thread:x64-windows -> 1.82.0#2
  * boost-uuid:x64-windows -> 1.82.0#2
  * boost-xpressive:x64-windows -> 1.82.0#2
  * bzip2[core,tool]:x64-windows -> 1.0.8#4
  * eigen3:x64-windows -> 3.4.0#2
  * flann:x64-windows -> 2019-04-07#6
  * liblzma:x64-windows -> 5.4.3
  * libpng:x64-windows -> 1.6.39#1
  * lz4:x64-windows -> 1.9.4#1
    pcl:x64-windows -> 1.13.0#3
  * qhull:x64-windows -> 8.0.2#4
  * zlib:x64-windows -> 1.2.13
  * zstd:x64-windows -> 1.5.5
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\pengyunsheng\AppData\Local\vcpkg\archives in 1.18 ms. Use --debug to see more details.
Installing 1/42 boost-build:x64-windows...
Building boost-build:x64-windows...
-- Using cached boostorg-build-boost-1.82.0.tar.gz.
-- Extracting source D:/Code/Repo/vcpkg/downloads/boostorg-build-boost-1.82.0.tar.gz
-- Applying patch 0002-fix-get-version.patch
-- Applying patch 0003-fix-emscripten.patch
-- Applying patch 0004-workaround-MSVC-codegen-bug-in-17.5-on-ARM64.patch
CMake Error at scripts/cmake/z_vcpkg_apply_patches.cmake:34 (message):
  Applying patch failed: Checking patch src/engine/glob.cpp...

  error: while searching for:

   * globchars() - build a bitlist to check for character group match.
   */

  static void globchars( const char * s, const char * e, char * b )

  {

      int neg = 0;

  error: patch failed: src/engine/glob.cpp:111

  error: src/engine/glob.cpp: patch does not apply

Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive.cmake:153 (z_vcpkg_apply_patches)
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:8 (vcpkg_extract_source_archive)
  scripts/cmake/vcpkg_from_github.cmake:113 (vcpkg_extract_source_archive_ex)
  ports/boost-build/portfile.cmake:9 (vcpkg_from_github)
  scripts/ports.cmake:147 (include)

error: building boost-build:x64-windows failed with: BUILD_FAILED
Elapsed time to handle boost-build:x64-windows: 1.3 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-build
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[boost-build]+Build+error&body=Copy+issue+body+from+D%3A%2FCode%2FRepo%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by jimwang118** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
