### ISSUE TITLE
[ismrmrd|rbdl]  probably wrong boost dependencies in manifest

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#32411]
### Is your feature request related to a problem? Please describe.

CI error logs show:
```
Building ismrmrd:x64-windows...
error: building ismrmrd:x64-windows failed with: CASCADED_DUE_TO_MISSING_DEPENDENCIES
    due to the following missing dependencies:
        boost[core]:x64-windows
Building rbdl:x64-windows...
error: building rbdl:x64-windows failed with: CASCADED_DUE_TO_MISSING_DEPENDENCIES
    due to the following missing dependencies:
        boost[core]:x64-windows
```
which means those two ports depend on all of boost. I highly doubt they really do that. 

### Proposed solution

Correct the boost dependency to the truely used parts of boost,

**Comment by FrankXie05** [comment]
Could you confirm which `ci` is the result? The latest ci results show normal:
```
Installing 1051/2110 ismrmrd:x64-windows...
Building ismrmrd:x64-windows...
-- Downloading https://github.com/ismrmrd/ismrmrd/archive/v1.13.2.tar.gz -> ismrmrd-ismrmrd-v1.13.2.tar.gz...
-- Extracting source D:/downloads/ismrmrd-ismrmrd-v1.13.2.tar.gz
-- Applying patch fix-depends-hdf5.patch
-- Using source at D:/buildtrees/ismrmrd/src/v1.13.2-56f09aa684.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/packages/ismrmrd_x64-windows/share/ismrmrd/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 553 ms.
Elapsed time to handle ismrmrd:x64-windows: 15 s
```

https://dev.azure.com/vcpkg/public/_build/results?buildId=91468&view=logs&j=7922e5c4-0103-5f8f-ad17-45ce9bb98e80&t=66eef212-08d6-5e6c-a560-7d01149d0188#:~:text=Building%20ismrmrd%3Ax64,windows%3A%2015%20s

**Comment by Neumann-A** [comment]
@FrankXie05 I am not speaking of the build being successful or unsuccessful. I speaking of the dependency graph pulling **all** of boost although it looks like it only needs `program_options` and `random`  which are also only used in the utilities (https://github.com/ismrmrd/ismrmrd/blob/595bd68d9138087f17ac792e972178af768dbab1/utilities/CMakeLists.txt#L34) if that is even build as part of vcpkg. Although they are using vcpkg themself the manifest in vcpkg doesn't agree with upstream: https://github.com/ismrmrd/ismrmrd/blob/master/vcpkg.json
