### ISSUE TITLE
[openvdb] build failure

### ISSUE THREAD

**Issue by Jhonve** [microsoft/vcpkg#32417]
### Operating system

Windows

### Compiler

MSVC 19.36.32535.0

### Steps to reproduce the behavior

```Shell
`vcpkg install openvdb:x64-windows`
```

### Failure logs

# Error when run install command

-- Found external ninja('1.11.0').
-- Configuring x64-windows
CMake Warning at installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:311 (message):
  The following variables are not used in CMakeLists.txt:

      OPENVDB_ENABLE_3_ABI_COMPATIBLE
      USE_GLFW3

  Please recheck them and remove the unnecessary options from the
  `vcpkg_cmake_configure` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):
  ports/openvdb/portfile.cmake:33 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)

-- Building x64-windows-dbg
CMake Warning at scripts/cmake/vcpkg_execute_build_process.cmake:65 (message):
  Please ensure your system has sufficient memory.
Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/openvdb/portfile.cmake:52 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: D:/externalLibs/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: D:/externalLibs/vcpkg/buildtrees/openvdb/x64-windows-dbg
    See logs for more information:
      D:\externalLibs\vcpkg\buildtrees\openvdb\install-x64-windows-dbg-out.log
      D:\externalLibs\vcpkg\buildtrees\openvdb\install-x64-windows-dbg-out-1.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/openvdb/portfile.cmake:52 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

# Log in install-x64-windows-dbg-out.log
[78/79] cmd.exe /C "cd . && D:\externalLibs\vcpkg\downloads\tools\cmake-3.25.1-windows\cmake-3.25.1-windows-i386\bin\cmake.exe -E vs_link_dll --intdir=openvdb\openvdb\CMakeFiles\openvdb_shared.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1436~1.325\bin\Hostx64\x64\link.exe  @CMakeFiles\openvdb_shared.rsp  /out:openvdb\openvdb\openvdb.dll /implib:openvdb\openvdb\openvdb.lib /pdb:openvdb\openvdb\openvdb.pdb /dll /version:10.0 /machine:x64 /nologo    /debug /INCREMENTAL  && cd ."
FAILED: openvdb/openvdb/openvdb.dll openvdb/openvdb/openvdb.lib 
cmd.exe /C "cd . && D:\externalLibs\vcpkg\downloads\tools\cmake-3.25.1-windows\cmake-3.25.1-windows-i386\bin\cmake.exe -E vs_link_dll --intdir=openvdb\openvdb\CMakeFiles\openvdb_shared.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1436~1.325\bin\Hostx64\x64\link.exe  @CMakeFiles\openvdb_shared.rsp  /out:openvdb\openvdb\openvdb.dll /implib:openvdb\openvdb\openvdb.lib /pdb:openvdb\openvdb\openvdb.pdb /dll /version:10.0 /machine:x64 /nologo    /debug /INCREMENTAL  && cd ."
LINK Pass 1: command "C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1436~1.325\bin\Hostx64\x64\link.exe @CMakeFiles\openvdb_shared.rsp /out:openvdb\openvdb\openvdb.dll /implib:openvdb\openvdb\openvdb.lib /pdb:openvdb\openvdb\openvdb.pdb /dll /version:10.0 /machine:x64 /nologo /debug /INCREMENTAL /MANIFEST /MANIFESTFILE:openvdb\openvdb\CMakeFiles\openvdb_shared.dir/intermediate.manifest openvdb\openvdb\CMakeFiles\openvdb_shared.dir/manifest.res" failed (exit code 1104) with the following output:
LINK : fatal error LNK1104: cannot open file 'blosc_shared.lib'

ninja: build stopped: subcommand failed.

# Additional context

It seems to be an error between the blosc lib and the openvdb lib.
I tried to remove the blosc, and re-install openvdb without pre-install blosc. Finally, the problem gone.

I am curious about the reason for this error.

**Comment by MonicaLiu0311** [comment]
```
CMake Warning at scripts/cmake/vcpkg_execute_build_process.cmake:65 (message):
Please ensure your system has sufficient memory.
```

Please make sure the machine has enough space.

**Comment by Jhonve** [comment]
> ```
> CMake Warning at scripts/cmake/vcpkg_execute_build_process.cmake:65 (message):
> Please ensure your system has sufficient memory.
> ```
> 
> Please make sure the machine has enough space.

Thanks for your quick response! I do have enough space for building openvdb (150GB remaining).

**Comment by MonicaLiu0311** [comment]
```
PS E:\vcpkg01> ./vcpkg version
vcpkg package management program version 2023-06-22-f19f3d9939100085fe2f7e41502d60b08e2083b6

See LICENSE.txt for license information.
```

Sorry I can't repro your issue.
```
PS E:\vcpkg01> ./vcpkg install openvdb:x64-windows --binarysource=clear

...

Building openvdb:x64-windows...
-- Downloading https://github.com/AcademySoftwareFoundation/openvdb/archive/be0e7a78861d2b7d9643f7a0cab04f3ab5951686.tar.gz -> AcademySoftwareFoundation-openvdb-be0e7a78861d2b7d9643f7a0cab04f3ab5951686.tar.gz...
-- Extracting source E:/vcpkg01/downloads/AcademySoftwareFoundation-openvdb-be0e7a78861d2b7d9643f7a0cab04f3ab5951686.tar.gz
-- Applying patch 0003-fix-cmake.patch
-- Using source at E:/vcpkg01/buildtrees/openvdb/src/3ab5951686-1c7a23646f.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
CMake Warning at installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:311 (message):
  The following variables are not used in CMakeLists.txt:

      OPENVDB_ENABLE_3_ABI_COMPATIBLE
      USE_GLFW3

  Please recheck them and remove the unnecessary options from the
  `vcpkg_cmake_configure` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):
  ports/openvdb/portfile.cmake:33 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)


-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: E:/vcpkg01/packages/openvdb_x64-windows/share/openvdb/usage
-- Installing: E:/vcpkg01/packages/openvdb_x64-windows/share/openvdb/copyright
-- Performing post-build validation
Elapsed time to handle openvdb:x64-windows: 13 min
Total install time: 13 min
The package openvdb provides CMake targets:

    find_package(OpenVDB CONFIG REQUIRED)
    target_link_libraries(main PRIVATE OpenVDB::openvdb)
```
