### ISSUE TITLE
[Imath] vcpkg clean failed

### ISSUE THREAD

**Issue by sukeya** [microsoft/vcpkg#32428]
Hello,

I tried to update Imath, but CI failed because of failing vcpkg clean.
The details is following:
- [x64_windows](https://dev.azure.com/vcpkg/public/_build/results?buildId=90650&view=logs&jobId=afe306fb-88a0-5d5e-2934-71aa01507316&j=7922e5c4-0103-5f8f-ad17-45ce9bb98e80&t=66eef212-08d6-5e6c-a560-7d01149d0188)
- [x64_uwp](https://dev.azure.com/vcpkg/public/_build/results?buildId=90650&view=logs&jobId=afe306fb-88a0-5d5e-2934-71aa01507316&j=7922e5c4-0103-5f8f-ad17-45ce9bb98e80&t=66eef212-08d6-5e6c-a560-7d01149d0188)

I’d appreciate it if you can.

**Comment by FrankXie05** [comment]
@sukeya For the exception thrown by the cleanup operation, it is possible that the load caused the command to fail. I have re-run the ci. :)

**Comment by FrankXie05** [comment]
Related PR https://github.com/microsoft/vcpkg/pull/31944

**Comment by sukeya** [comment]
Thank you!

**Comment by FrankXie05** [comment]
Closed this issue due to https://github.com/microsoft/vcpkg/pull/31944.
