### ISSUE TITLE
Cannot install MSMPI with not default msmpisdk way

### ISSUE THREAD

**Issue by AJIOB** [Microsoft/vcpkg#3242]
I'm trying to install msmpi from vcpkg with command `vcpkg install msmpi:x64-windows`, but I get an error:
```
PS D:\Alex\Documents\SourceTree\vcpkg> .\vcpkg.exe install msmpi:x64-windows
The following packages will be built and installed:
    msmpi[core]:x64-windows
Starting package 1/1: msmpi:x64-windows
Building package msmpi[core]:x64-windows...
A suitable version of cmake was not found (required v3.10.2). Downloading portable cmake v3.10.2...
-- CURRENT_INSTALLED_DIR=D:/Alex/Documents/SourceTree/vcpkg/installed/x64-windows
-- DOWNLOADS=D:/Alex/Documents/SourceTree/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/Alex/Documents/SourceTree/vcpkg/packages/msmpi_x64-windows
-- CURRENT_BUILDTREES_DIR=D:/Alex/Documents/SourceTree/vcpkg/buildtrees/msmpi
-- CURRENT_PORT_DIR=D:/Alex/Documents/SourceTree/vcpkg/ports/msmpi/.
-- Using cached D:/Alex/Documents/SourceTree/vcpkg/downloads/msmpisdk-9.0.msi
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Using cached D:/Alex/Documents/SourceTree/vcpkg/downloads/msmpisetup-9.0.exe
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
CMake Error at ports/msmpi/portfile.cmake:56 (message):
    Could not find:
      C:\Program Files/Microsoft MPI/Bin/mpiexec.exe
    Please install the MSMPI redistributable package before trying to install this port.
    The appropriate installer has been downloaded to:
      D:/Alex/Documents/SourceTree/vcpkg/downloads/msmpisetup-9.0.exe

Call Stack (most recent call first):
  scripts/ports.cmake:72 (include)


Error: Building package msmpi:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: msmpi:x64-windows
  Vcpkg version: 0.0.108-2018-04-10-b4aad86642c50afcbaa4e348dba2b8f86c28ad56

Additionally, attach any relevant sections from the log files above.
```

I have Windows 10 x64 Pro v1709.

![MPI installed](https://image.ibb.co/mnbZGc/image.png)

![MPI variables](https://image.ibb.co/mqVuGc/image.png)

How can I install this library without reinstalling MSMPI?

**Comment by jasjuang** [comment]
vcpkg is not going to actually install msmpi, it's just going to download the installer, and once you install it check whether it is installed.

Looks like you have msmpi installed already, did you verify whether this file `C:\Program Files/Microsoft MPI/Bin/mpiexec.exe` exist?

**Comment by AJIOB** [comment]
This file does not exist, because I was changed the destination folder when I was installing it. It exists by `D:\Program Files\Microsoft MPI\Bin\mpiexec.exe` way (other, not system installed drive)

**Comment by Voskrese** [comment]
@AJIOB просто распакуй и скопируй с заменой по тем путям, которые имеются
`just unpack and copy with a replacement on the paths that are available`

**Comment by AJIOB** [comment]
@Voskrese которые требует `vcpkg`?
`Unpack in that way, that vcpkg tool require for MSMPI installing?`

**Comment by Voskrese** [comment]
@AJIOB да, девятую версию, vcpkg проверяет из строки версии
D:\Program Files\Microsoft MPI\Bin - сюда исполняемые и со скриншота либы и хидеры
могу посоветовать прошрамму распаковке всяких разных архивов  Universal Extractor (UniExtractor)

**Comment by AJIOB** [comment]
@Voskrese файлы лежат на `D`, но он их на `C` все равно ищет. Почему? Цель этого issue, чтобы это и поправили (и брали пути из переменных среды)

**Comment by Voskrese** [comment]
@AJIOB хмм.. из реестра первой установки, либо в скрипте поиско жеско пути прописаны.
ок, вопрос ясен

**Comment by JackBoosY** [comment]
Hi @AJIOB , thanks for reporting this issue!
It seems to have fixed a near version. So I closed it.
Please open a new issue if this is still a problem for you.
Thx.
