### ISSUE TITLE
[upb] Build error

### ISSUE THREAD

**Issue by davidyancich** [microsoft/vcpkg#32424]
Copy issue body from C:/source/vcpkg/installed/vcpkg/issue_body.md
[issue_body.md](https://github.com/microsoft/vcpkg/files/11968920/issue_body.md)

**Comment by davidyancich** [comment]
I have tried solutions from previous bug reports, but nothing is working.

**Comment by JonLiu1993** [comment]
@davidyancich, Thanks for posting this issue, This issue is duplicate of https://github.com/microsoft/vcpkg/issues/31620, Please track this issue in another issue.
