### ISSUE TITLE
VCPKG installs plugin directories to tools/Qt6/bin that override existing binaries (designer)

### ISSUE THREAD

**Issue by RealLitb** [microsoft/vcpkg#32422]
**Describe the bug**

Qt has a "plugins" directory that contains all sorts of functionality not only for handling windowing system but also for tools like designer to provide widgets. 

These plugins apparently get installed to `Qt6/plugins` and there is a `qt.conf` file in `tools/Qt6/bin` that specifies this location so that the tools can find them. But unfortunately, the content of `Qt6/plugins/*` is also installed into `tools/Qt6/bin`. This conflicts with binaries. For example the `designer` tool has its plugin directory called "designer", and one overrides the other.

**Comment by RealLitb** [comment]
Apparently this conflict happened with "qtdeclarative" previously, and a workaround was applied in https://github.com/microsoft/vcpkg/blob/master/ports/qtbase/cmake/qt_install_submodule.cmake#L284C101-L284C101

`if(EXISTS "${CURRENT_PACKAGES_DIR}/${qt_plugindir}" AND NOT PORT STREQUAL "qtdeclarative") #qmllint conflict`

Please add a workaround for `qtwebengine` aswell.

**Comment by twiddli** [comment]
Issue still exists. Getting the same conflict error with `qtshadertools` when trying to install `qtmultimedia` after `qtbase`
