### ISSUE TITLE
[poco] Features for all poco components

### ISSUE THREAD

**Issue by tomwatson1024** [microsoft/vcpkg#32434]
### Is your feature request related to a problem? Please describe.

I'm porting a legacy build system to vcpkg. 
The legacy build system disables all but a few poco components as we don't need them.
This improves build times and helps with e.g. regulatory compliance.

### Proposed solution

Add vcpkg features for poco components that are currently always enabled by vcpkg, e.g. Encodings, Xml, Json etc.
Having such features will allow us to disable the components we don't use.

### Describe alternatives you've considered

We could build the components we don't need.
Undesirable for compliance reasons.

We could write an overlay port.
Undesirable as it means maintaining a separate port file. 

We currently copy only the shared objects we need when packaging the binary, but this is less auditable than vcpkg features and doesn't improve build times.

### Additional context

I looked at submitting a PR - adding a feature for each component listed in the portfile, and setting those options accordingly, seems easy enough, but I'm not sure:

- how to identify interdependencies (e.g. the existing `netssl` feature depends on `crypto`)
- how vcpkg tends to handle them.

**Comment by jimwang118** [comment]
In `vpckg`, we define additional components as features. If we do not actively call them during the installation process, we will not compile additional components, but only compile `poco`.

**Comment by dg0yt** [comment]
More options:
- You disable the undesired components via options supplied in per-port customization in a custom triplet file.
- You contribute the desired port features to control the package features you don't want.
  Note that vcpkg CI will only test one representative feature set (default features plus requested dependencies).

**Comment by tomwatson1024** [comment]
> In `vpckg`, we define additional components as features. If we do not actively call them during the installation process, we will not compile additional components, but only compile `poco`.

These are all components that make up the Poco library - see e.g. https://docs.pocoproject.org/current/00100-GuidedTour.html. If you consider "additional components" to be "optional components that may not be needed", then there are lots of additional components unconditionally compiled by the vcpkg port:

https://github.com/microsoft/vcpkg/blob/79a6c094989d1952da01a7bc3abf30198f8da860/ports/poco/portfile.cmake#L52-L82

e.g. the JSON component is always enabled even though it's not a core Poco component.
