### ISSUE TITLE
[libusb] Build error

### ISSUE THREAD

**Issue by J-YAA-i50-L** [microsoft/vcpkg#32437]
Copy issue body from /home/anton/vcpkg/installed/vcpkg/issue_body.md

**Comment by FrankXie05** [comment]
@J-YAA-i50-L Please provide the error log and steps to reproduce.

**Comment by FrankXie05** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please ping me and I will reopen this!
