### ISSUE TITLE
[flann] 'pop_t'：Undefined type

### ISSUE THREAD

**Issue by Bzz2745** [microsoft/vcpkg#32448]
### Is your feature request related to a problem? Please describe.

In file flann/algorithm/dist.h:
![image](https://github.com/microsoft/vcpkg/assets/68807654/3c8b99c6-03d3-4df2-ad58-30d3e4715c65)
![image](https://github.com/microsoft/vcpkg/assets/68807654/d35a389f-f3aa-4907-a87d-18a80cc9b648)
It is obvious that the 'pop_t' type is defined under the GNUC platform, but is still used on other platforms that do not define the 'pop_t' type (see line 522 in Figure 2).

### Proposed solution

I just want it can be use.

### Describe alternatives you've considered

I don't know how the type 'pop_t' differs between platforms, but if not, the definition of 'pop_t' should be moved to the top of the line that distinguishes between different platforms (move to the next line of 479 lines) or change the sizeof (pop_t) of line 522 below to sizeof (unsigned long long).

**Comment by StarGate-One** [comment]
This is an upstream issue already documented [Flann Throws Error Regarding "pop_t': Identifier not found in dist.h file #386](https://github.com/flann-lib/flann/issues/386)

**Comment by jimwang118** [comment]
This problem was raised in the upstream issue, but it seems that it has not been fixed for a long time. Looking at the reply in the upstream issue, someone mentioned the definition of` pop_t` outside the platform judgment to fix this problem. I will make a patch like this to fix it .
