### ISSUE TITLE
[RocksDB] port cmake error

### ISSUE THREAD

**Issue by jkammerland** [microsoft/vcpkg#32458]
**Describe the bug**
(In Manifest mode) Port is not self-contained and will produce a CMake error, i.e

[cmake] CMake Error at build/vcpkg_installed/x64-linux/share/rocksdb/RocksDBTargets.cmake:60 (set_target_properties):
[cmake]   The link interface of target "RocksDB::rocksdb" contains:
[cmake] 
[cmake]     uring::uring
[cmake] 
[cmake]   but the target was not found.  Possible reasons include:
[cmake] 
[cmake]     * There is a typo in the target name.
[cmake]     * A find_package call is missing for an IMPORTED target.
[cmake]     * An ALIAS target is missing.
[cmake] 

Also, I do have liburing installed on my system.

**Environment**
Linux Fedora 38
Clang16 gcc13

**Expected behavior**
CMake should succeed, and I can link to RocksDB::rocksdb :)

**Comment by jkammerland** [comment]
I have to remove the "liburing" feature AND add
-DWITH_LIBURING=OFF
to the options in the port file

**Comment by yurybura** [comment]
@jkammerland For workaround please specify in your manifest `rocksdb[core,zlib]` without default features. I'll try to fix RocksDB CMake.

**Comment by MonicaLiu0311** [comment]
Confirm, repro locally.

```
root@monica003:/home/monica/vcpkg# ./vcpkg version
vcpkg package management program version 2023-06-22-f19f3d9939100085fe2f7e41502d60b08e2083b6

See LICENSE.txt for license information.
```

**Comment by yurybura** [comment]
Related to https://github.com/facebook/rocksdb/issues/11626
