### ISSUE TITLE
[zeromq] Why not use a release version?

### ISSUE THREAD

**Issue by LazyWolfLin** [microsoft/vcpkg#3245]
https://github.com/Microsoft/vcpkg/blob/9ccad4304edc3ac452b3c295d5ee203c861fcc6f/ports/zeromq/portfile.cmake#L6

I find zeromq often use a nightly version. Why not use a release version.

**Comment by PhoebeHui** [comment]
@LazyWolfLin, we usually use release version, except there is no release for a long time, or the dev version contains specify fix for the issue which blocked user in release version. Please reopen this if it still be an problem for you.
