### ISSUE TITLE
[New Port Request] <gegle>

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#32464]
### Library name

gegl

### Library description

GEGL (Generic Graphics Library) is a data flow based image processing framework, providing floating point processing and non-destructive image processing capabilities to GNU Image Manipulation Program and other projects (imgflo, GNOME Photos, iconographer, …)

### Source repository URL

https://gitlab.gnome.org/GNOME/gegl/

### Project homepage (if different from the source repository)

https://gegl.org/

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by talregev** [comment]
You can close. Thank you.
