### ISSUE TITLE
spirv_cross_reflect in spirv-cross link error

### ISSUE THREAD

**Issue by freestriker** [microsoft/vcpkg#32460]
i install the "spirv-cross" in vcpkg.json, and use spirv_cross_reflect in cmakelist.txt, when i build the exe, it always show the lnh2019 and lnk1120 error.

**Environment**
- OS: win11 22H2
- Compiler: vs2022

**To Reproduce**
1. add 
        {
            "name": "spirv-cross"
        }
in the vcpkg.json
2. add
find_package(spirv_cross_reflect CONFIG REQUIRED)
target_link_libraries(Test PUBLIC spirv-cross-reflect)
in the cmakelist.txt
3. add main.cpp

#include <fstream>
#include <vector>
#include <spirv_reflect.hpp>
int main(int argc, char* argv[])
{

    std::ifstream file("..\\../Resources\\Shader/Present.vert.spv", std::ios::ate | std::ios::binary);

    size_t fileSize = (size_t)file.tellg();
    std::vector<char> buffer(fileSize);
    file.seekg(0);
    file.read(buffer.data(), fileSize);
    file.close();

    auto compiler = new spirv_cross::Compiler(reinterpret_cast<const uint32_t*>(buffer.data()), buffer.size() / 4);

    return 0;
}
5. build, then show as blows:
main.obj : error LNK2019: unresolved external symbol "public: __cdecl spirv_cross::Compiler::Compiler(unsigned int const *,unsigned __int64)" (??0Compiler@spirv_cross@@QEAA@PEBI_K@Z) referenced in function main
2>E:\Project\AirEngine\Build\Test\Debug\Test.exe : fatal error LNK1120: 1 unresolved externals

**Expected behavior**
it should link with no error

**Failure logs**
2>main.cpp
2>main.obj : error LNK2019: unresolved external symbol "public: __cdecl spirv_cross::Compiler::Compiler(unsigned int const *,unsigned __int64)" (??0Compiler@spirv_cross@@QEAA@PEBI_K@Z) referenced in function main
2>E:\Project\AirEngine\Build\Test\Debug\Test.exe : fatal error LNK1120: 1 unresolved externals
2>Done building project "Test.vcxproj" -- FAILED.
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Additional context**
i install the vulkan sdk in system, so i use the #include <spirv_reflect.hpp>, it is the vcpkg installed file, not the local vulkan file.

**Comment by jimwang118** [comment]
Add the following references to `cmakelist.txt`:
```
find_package(spirv_cross_reflect CONFIG REQUIRED)
find_package(spirv_cross_core CONFIG REQUIRED)
target_link_libraries(testspirv-cross PRIVATE spirv-cross-reflect spirv-cross-core)
```
Add the header file` #include <spirv_cross.hpp>` in CPP, and then recompile the result is normal.

**Comment by Adela0814** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
