### ISSUE TITLE
Error: Building package theia:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by donesaricameverest** [Microsoft/vcpkg#3246]
I tried to setup theia the got the error what can I do?(I wrote command line >vcpkg install theia:x64-windows)

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: C:/Users/AB-Solution_01/Downloads/vcpkg-master/buildtrees/theia/x64-windows-rel/vcpkg-parallel-configure
    See logs for more information:
      C:\Users\AB-Solution_01\Downloads\vcpkg-master\buildtrees\theia\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:233 (vcpkg_execute_required_process)
  ports/theia/portfile.cmake:25 (vcpkg_configure_cmake)
  scripts/ports.cmake:72 (include)

Error: Building package theia:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: theia:x64-windows
  Vcpkg version: 0.0.105-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by brucejee** [comment]
I also run into this error, and i uninstall cmake 3.11 and reinstall cmake 3.10.2, It's ok now.
You can see this [issue](https://github.com/Microsoft/vcpkg/issues/2985), may help you.

**Comment by antithing** [comment]
Hi, I have tried reinstalling cmake, and i get the same issue. I have also tried `choco install ninja` as referenced here:

https://github.com/Microsoft/vcpkg/issues/2758

and i still see the error.  Did you manage to get Theia built?

**Comment by donesaricameverest** [comment]
Unfortunately I didn't

**Comment by JackBoosY** [comment]
Hi @donesaricameverest , thanks for reporting this issue.
Please open a new issue if this is still a problem for you.
Thx.
