### ISSUE TITLE
[Port Request] Enchant

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/vcpkg#3247]
Would be lovely to get a port for the https://github.com/AbiWord/enchant library. They recently removed their stale MSVC build files https://github.com/AbiWord/enchant/issues/70.

**Comment by NancyLi1013** [comment]
Hi @Stanzilla thanks for posting this request. This port requires to depend on `gunlib`. So we need to add `gunlib `first.

**Comment by Stanzilla** [comment]
For reference, that's https://github.com/gundb/gun, right?

**Comment by NancyLi1013** [comment]
@Stanzilla 
Sorry, I am not sure if the link you provided above is an unofficial source.
