### ISSUE TITLE
[leptonica] vcpkg Build error

### ISSUE THREAD

**Issue by YXY1988** [microsoft/vcpkg#32488]
When I install tesseract using vcpkg using `vcpkg install tesseract:arm64-uwp` it stucks at building the leptnoica. Details are at follow:

```shell
error: building leptonica:arm64-uwp failed with: BUILD_FAILED
Elapsed time to handle leptonica:arm64-uwp: 18 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.

```

**Comment by MonicaLiu0311** [comment]
Tip, `tesseract` does not support uwp: [tesseract/vcpkg.json#L7](https://github.com/microsoft/vcpkg/blob/master/ports/tesseract/vcpkg.json#L7)

Please attach detailed log of `leptonica` failure.

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
