### ISSUE TITLE
openssl build failed

### ISSUE THREAD

**Issue by vanarova** [Microsoft/vcpkg#3249]
Additional packages (*) will be modified to complete this operation.
Starting package 1/112: openssl:x86-windows
Building package openssl[core]:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/Sources/vcpkg-master/vcpkg-master/installed/x86-wind
ows
-- DOWNLOADS=C:/Sources/vcpkg-master/vcpkg-master/downloads
-- CURRENT_PACKAGES_DIR=C:/Sources/vcpkg-master/vcpkg-master/packages/openssl_x8
6-windows
-- CURRENT_BUILDTREES_DIR=C:/Sources/vcpkg-master/vcpkg-master/buildtrees/openss
l
-- CURRENT_PORT_DIR=C:/Sources/vcpkg-master/vcpkg-master/ports/openssl/.
-- Downloading https://www.openssl.org/source/openssl-1.0.2o.tar.gz...
-- Downloading https://www.openssl.org/source/openssl-1.0.2o.tar.gz... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting done
-- Applying patch C:/Sources/vcpkg-master/vcpkg-master/ports/openssl/ConfigureIn
cludeQuotesFix.patch
-- Applying patch failed. This is expected if this patch was previously applied.

-- Applying patch C:/Sources/vcpkg-master/vcpkg-master/ports/openssl/ConfigureIn
cludeQuotesFix.patch done
-- Applying patch C:/Sources/vcpkg-master/vcpkg-master/ports/openssl/STRINGIFYPa
tch.patch
-- Applying patch failed. This is expected if this patch was previously applied.

-- Applying patch C:/Sources/vcpkg-master/vcpkg-master/ports/openssl/STRINGIFYPa
tch.patch done
-- Applying patch C:/Sources/vcpkg-master/vcpkg-master/ports/openssl/EmbedSymbol
sInStaticLibsZ7.patch
-- Applying patch failed. This is expected if this patch was previously applied.

-- Applying patch C:/Sources/vcpkg-master/vcpkg-master/ports/openssl/EmbedSymbol
sInStaticLibsZ7.patch done
-- Configure x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: C:/Windows/PERL;Configure;enable-static-engine;enable-capien
g;no-ssl2;-utf-8;VC-WIN32;--prefix=C:/Sources/vcpkg-master/vcpkg-master/packages
/openssl_x86-windows;--openssldir=C:/Sources/vcpkg-master/vcpkg-master/packages/
openssl_x86-windows;-FS
    Working Directory: C:/Sources/vcpkg-master/vcpkg-master/buildtrees/openssl/x
86-windows-rel/openssl-1.0.2o
    See logs for more information:

Call Stack (most recent call first):
  ports/openssl/portfile.cmake:71 (vcpkg_execute_required_process)
  scripts/ports.cmake:72 (include)

Error: Building package openssl:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl:x86-windows
  Vcpkg version: 0.0.108-unknownhash

Additionally, attach any relevant sections from the log files above.

I have already ran update command.
Could you please help.

**Comment by vanarova** [comment]
Just to add, I am trying to install rest sdk from github and running below command -

vcpkg install cpprestsdk cpprestsdk:x64-windows

**Comment by JackBoosY** [comment]
Hi @vanarova , thanks for reporting this issue!
Openssl built successfully on the latest version. Plz update and rebuild.
Please open a new issue if this is still a problem for you.
Thx.
