### ISSUE TITLE
Error: building package curl:x64-windows failed ( Resolved )

### ISSUE THREAD

**Issue by bangusi** [Microsoft/vcpkg#325]
It is my very first attempt to use vcpkg. Just built it and tried to install first package.

Package: curl:x64-windows
  Vcpkg version: 0.0.51-c4af75153435a36353077e2f631b0703e969e1b5

It turns out I can't install any package. Here is my attempt to install sqlite3
Error: building package sqlite3:x64-windows failed
Please ensure sure you're using the latest portfiles with `vcpkg update`,

Note: I am only interested in 64-bit builds. Is this the problem?

Using VS 2015 Commuity Edition and also have VS 17 RC installed

Resolved: Looks like I needed Powershell in may path. Not quite sure but I did manipulate the path quite a bit

**Comment by alexkaratarakis** [comment]
Glad it was sorted out 👍 .
Though I believe powershell is in the path by default.
