### ISSUE TITLE
[New Port Request] <brainflow>

### ISSUE THREAD

**Issue by miyanyan** [microsoft/vcpkg#32505]
### Library name

brainflow

### Library description

BrainFlow is a library intended to obtain, parse and analyze EEG, EMG, ECG and other kinds of data from biosensors

### Source repository URL

https://github.com/brainflow-dev/brainflow

### Project homepage (if different from the source repository)

https://brainflow.org/

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
