### ISSUE TITLE
[qt5-base] Build error

### ISSUE THREAD

**Issue by handianping** [microsoft/vcpkg#32514]
Copy issue body from /var/jenkins/workspace/vcpkg/installed/vcpkg/issue_body.md

**Comment by JonLiu1993** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report an issue.

**Comment by JonLiu1993** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
