### ISSUE TITLE
[<port name>] build failure for libheif

### ISSUE THREAD

**Issue by windrh** [microsoft/vcpkg#32517]
### Operating system

Windows 

### Compiler

Git Bash 

### Steps to reproduce the behavior

```Shell
download git, run git bash as admin. 
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
./bootstrap-vcpkg.sh
./vcpkg integrate install
./vcpkg install libheif

NOTE: I HAVE ALREADY INSTALLED LIBde265
```

### Failure logs

willh@WillDRH MINGW64 /vcpkg (master)
$ ./vcpkg install libheif
warning: Starting with the September 2023 release, the default triplet for vcpkg libraries will change from x86-windows to the detected host triplet (x64-windows). To resolve this message, add --triplet x86-windows to keep the same behavior.
Computing installation plan...
The following packages will be built and installed:
    libheif:x86-windows -> 1.16.2
  * x265:x86-windows -> 3.4#9
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Restored 0 package(s) from C:\Users\willh\AppData\Local\vcpkg\archives in 108 us. Use --debug to see more details.
Installing 1/2 x265:x86-windows...
Building x265:x86-windows...
-- Using cached videolan-x265-07295ba7ab551bb9c1580fdaee3200f1b45711b7.tar.gz.
-- Cleaning sources at C:/Program Files/Git/vcpkg/buildtrees/x265/src/f1b45711b7-a1ec8d932a.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Program Files/Git/vcpkg/downloads/videolan-x265-07295ba7ab551bb9c1580fdaee3200f1b45711b7.tar.gz
-- Applying patch disable-install-pdb.patch
-- Applying patch fix-pkgconfig-version.patch
-- Using source at C:/Program Files/Git/vcpkg/buildtrees/x265/src/f1b45711b7-a1ec8d932a.clean
-- Found external ninja('1.11.0').
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/Git/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe" --build . --config Debug --target install -- -v -j13
    Working Directory: C:/Program Files/Git/vcpkg/buildtrees/x265/x86-windows-dbg
    See logs for more information:
      C:\Program Files\Git\vcpkg\buildtrees\x265\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/x265/portfile.cmake:33 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building x265:x86-windows failed with: BUILD_FAILED
Elapsed time to handle x265:x86-windows: 8.6 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+x265
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[x265]+Build+error&body=Copy+issue+body+from+C%3A%2FProgram%20Files%2FGit%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by Adela0814** [comment]
@windrh  Please provide the failure log:
`C:\Program Files\Git\vcpkg\buildtrees\x265\install-x86-windows-dbg-out.log`

**Comment by windrh** [comment]
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/12030395/install-x86-windows-dbg-out.log)

**Comment by dg0yt** [comment]
> `C:/Program Files/Git/vcpkg/...`

Do not use a path with space for vcpkg. Too many packages are not ready for this.

(And using "C:/Program Files" should need administrative privilege, while using vcpkg shouldn't.)

**Comment by windrh** [comment]
Thank you!
