### ISSUE TITLE
[ffmpeg] Build error

### ISSUE THREAD

**Issue by tzukpolinsky** [microsoft/vcpkg#32539]
Copy issue body from <dir path>/vcpkg_installed/vcpkg/issue_body.md

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_acquire_msys.cmake:26 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_acquire_msys.cmake:67 (z_vcpkg_acquire_msys_download_package)
  scripts/cmake/vcpkg_acquire_msys.cmake:216 (z_vcpkg_acquire_msys_declare_package)
  C:/Users/tzuk9/AppData/Local/vcpkg/registries/git-trees/14577b12f56accfce4428caf17e4b47542f365ec/portfile.cmake:48 (vcpkg_acquire_msys)
  scripts/ports.cmake:147 (include)

error: building ffmpeg:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+ffmpeg
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[ffmpeg]+Build+error&body=Copy+issue+body+from+C%3A%2FUsers%2Ftzuk9%2FDocuments%2FsimulatorMapping%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md

**Comment by FrankXie05** [comment]
Please check if your firewall isolates vcpkg.
