### ISSUE TITLE
[New Port Request] JavaScriptCore

### ISSUE THREAD

**Issue by jviotti** [microsoft/vcpkg#32555]
### Library name

JavaScriptCore

### Library description

WebKit's JavaScript engine

### Source repository URL

https://github.com/webkit/webkit

### Project homepage (if different from the source repository)

https://webkit.org

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

JavaScriptCore is a component of the bigger WebKit project, but can be compiled standalone. JavaScriptCore is offered standalone on GNU/Linux distributions (i.e. https://packages.debian.org/bookworm/libjavascriptcoregtk-6.0-1) and by default on Apple systems (https://developer.apple.com/documentation/javascriptcore/c_javascriptcore_api)

**Comment by Osyotr** [comment]
Can standalone JSC and JSC that is a part of WebKit be used separately?
IIUC Debian splits WebKit into JSC and WebCore.
I think the same approach is not desirable in vcpkg.

**Comment by jviotti** [comment]
@Osyotr It can. The WebKit build system supports the `JSCOnly` port for only building JavaScriptCore standalone as either a static or shared library. 

I've done some early experiments on this here: https://github.com/jviotti/libjsc, but only got it to work on Linux so far. If you type `make` (or `nmake` on Windows), it will use CMake to build the JSCOnly port from a trimmed `vendor` version of WebKit, build it as a static library, and create a sample program that uses it.

Let me know what you think, and happy to help making the port.

**Comment by jviotti** [comment]
To be more precise, the project above builds and links fine on Windows 11 with Visual studio 2022, but fails to run for some reason.

**Comment by jviotti** [comment]
Still interested in this. We'll come to it soon.

**Comment by bavulapati** [comment]
We are actively working on this. We are still interested in this.

**Comment by bavulapati** [comment]
The PR is WIP. We are finalizing the PR.
