### ISSUE TITLE
[luajit] Different build artefacts under Linux (clang) and Windows (msvc)

### ISSUE THREAD

**Issue by ulfllorenz** [microsoft/vcpkg#32552]
### Is your feature request related to a problem? Please describe.

The luajit package uses two different builds for Windows/MSVC (.bat file + installation make file by vcpkg) and Linux (Makefile). One rather unsurprising consequence is that the build artefacts differ. In particular:

* include directories are different. luajit installs its headers under "luajit-2.1", while the Windows port installs under "luajit".
* libraries have different names. These are "libluajit-5.1.a" under Linux, while Windows has "lua51.dll".
* The Windows port just copies all files into the include directory. There are far too many files included, including the source code and other build artefacts.

The defects are not critical, but rather annoying, as they require manual work to portably set up the luajit target. In particular the include paths also have the midly annoying effect that you include luajit.h directly, instead of adding the directory prefix.

### Proposed solution

* Align the Windows and the Linux installation.
* Remove the garbarge from the include directory in the Windows installation.

### Describe alternatives you've considered

We could of course also use the pkginfo files, which are also different for Linux and Windows with the corresponding CMake module, AFAIR FindPkgConfig. This has the mildly annoying problem that all (Windows) developers would be required to install pkgconfig before they can start developing, but this would be another option of aligning the Windows and Linux builds.

### Additional context

also partially reported upstream: https://github.com/LuaJIT/LuaJIT/issues/1032

**Comment by ChaseCarlson** [comment]
Also experiencing this. Would love a fix but for now I will settle for #ifdef declarations instead.

**Comment by dg0yt** [comment]
https://github.com/LuaJIT/LuaJIT/issues/1032#issuecomment-1634228295

We may reduced the number of headers installed.
Which other changes can be done within of upstream's naming and "Lua packaging and naming"?

Many vcpkg ports use and provide pkgconfig pc files also for windows. And with `pkgconf`, we do have a port which builds the tool.
