### ISSUE TITLE
[New Port Request] valhalla

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#32565]
### Library name

valhalla

### Library description

Open Source Routing Engine for OpenStreetMap

### Source repository URL

https://github.com/valhalla/valhalla

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

As the comparison (https://gis-ops.com/open-source-routing-engines-and-algorithms-an-overview/#user-content-tldr-overview) shows, it's a first-class library for map routing.

**Comment by playgithub** [comment]
As "https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=valhalla" shows
It depends on  'prime_server' 'boost-libs' 'protobuf' 'python' 'libspatialite' 'luajit' 'chrono-date',
among which 'prime_server' and 'chrono-date' are not in vcpkg now.

**Comment by endingly** [comment]
This job will take some time.

**Comment by nilsnolde** [comment]
I think I'll look into this over the next weeks/months. I just really start to get the hang of vcpkg tbh and it'd help me tremendously to manage dependencies for quite a few C++-binding Python projects, including the bindings to Valhalla. 

So the plan would approx be:
- build libvalhalla.so
- build most executables for data building, **except** for  `valhalla_service`

`valhalla_service` depends on https://github.com/kevinkreiser/prime_server, which isn't Win compatible (yet). The rest is though. And it's still very valuable for downstream C++ projects to use libvalhalla. I suppose it might be possible to build/install executables conditionally, depending on the platform/distro?

I never wrote vcpkg recipes, so it'll take a while. One thing I'm a bit unsure about: Valhalla vendors a lot of header-only libraries, most notably `rapidjson` and Howard Hinnant's `date` library (we're not even fully C++17 yet), which are installed as well i.e. they're public API. Both are also available in vcpkg and rapidjson thankfully with a recent commit. So 2 questions:
- I guess it's required to patch our CMakeLists.txt in the recipe to use the vcpkg distros?
- I hope it's fine to use vendored libraries to compile Valhalla, i.e. libs that won't be installed bcs it's not public API?

**Comment by m-kuhn** [comment]
I would enjoy seeing this land.

- If you can upstream the patch to switch to unvendored deps, that would be nice.
- As far as I can tell from other ports, vendored deps that are not available in vcpkg seem to be accepted, and it can be reacted upon at a later stage when it should become problematic (I would prefer to have a valhalla port with vendored libs over not having it at all)

**Comment by m-kuhn** [comment]
> Thanks for the feedback @m-kuhn :)
> 
> > If you can upstream the patch to switch to unvendored deps, that would be nice.
> 
> You mean change upstream valhalla to not use vendored libs? I think I'd keep it as a patch for the vcpkg recipe, to avoid a lengthy discussion which I know will come:)

I was thinking about something like a `-D WITH_INTERNAL_[XYZ]=OFF` directive, to be able to opt out of vendored libs, that should be completely backwards compatible.

> I understand the need for public API, but what about header-only deps needed only for compilation? That should be fine to use right? I don't think it matters much, we're very up-to-date on all deps, just for my own curiosity in package managing best practices:)

Quoting from [stackoverflow](https://stackoverflow.com/a/55140588/2319028)

> The C++ standard states that if in a program there is multiple definitions of an inline function (or class template, or variable, etc.) and all the definitions are not the same, then you have UB.

Read: we are on thin ice regarding ODR violations as soon as a consumer of valhalla uses the same library in a different version

**Comment by nilsnolde** [comment]
Or maybe I'm not understanding some basic C++ compilation stuff? If the headers are compiled into an executable/the library, it doesn't matter if there's any other installations of some dependencies flying around when executing it does it?

**Comment by m-kuhn** [comment]
You may be lucky depending on what the headers do and what valhalla and its downstream applications do, but the linked stackoverflow answer seems to quite clearly suggest that it's not safe by definition.

**Comment by nilsnolde** [comment]
Ah sorry, of course, using libvalhalla as a dependency in another project that also depends on the same compile-time libraries! Thanks for the eye openers!

**Comment by playgithub** [comment]
As a dependency, `prime_server` is only for services. And as a lib, the services are not necessary. As the cmake code shows below, services are optional, so `prime_server` is an optional dependency. I think it's ok to disable the services to make it easier to port.

```cmake
if(ENABLE_SERVICES)
  pkg_check_modules(libprime_server REQUIRED libprime_server>=0.6.3)
  # workaround for https://gitlab.kitware.com/cmake/cmake/issues/15804
  find_library(libprime_server_LIBRARY
    NAME ${libprime_server_LIBRARIES}
    HINTS ${libprime_server_LIBRARY_DIRS})
  set_target_properties(libprime_server PROPERTIES
    INTERFACE_LINK_LIBRARIES "${libprime_server_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${libprime_server_INCLUDE_DIRS}"
    INTERFACE_COMPILE_DEFINITIONS HAVE_HTTP)
endif()
```

**Comment by nilsnolde** [comment]
slowly moving towards having valhalla as a port. I cleaned up much of the cmake stuff to make the port easier, including being able to use external header-only dependencies, both compile-only/public API. at least those which are present in vcpkg, I'll document the remaining ones in the port itself, they're very unlikely to be used by any consuming project.

I quickly tried compiling `prime_server` with MVSC which fails bcs it relies on POSIX signals (not available on Win). it's indeed only used in some service executables and eventually just means one wouldn't be able to run a full-fledged HTTP server using the vcpkg port, which is more than fine.
