### ISSUE TITLE
lapack fails to build on windows when using a networked drive for vcpkg downloads dir

### ISSUE THREAD

**Issue by charlie-x** [microsoft/vcpkg#32573]
FYI on windows building lapack seems to use the gfortran compiler which fails in compiling when its set to a mapped network drive for the vcpkg download dir, it replaces the drive letter with a unc path and is unable to find all of the files, seems to be an issue with the fortran compiler build

- OS: [windows]
- Compiler: mingw/VC2022

1. set your vcpkg environment variables for the download dir to mapped network drive or unc path
2. use anything that requires lapack/fortran 
3. attempt to build

o: is a network drive
VCPKG_DEFAULT_BINARY_CACHE=o:\vcpkg\
VCPKG_DOWNLOADS=o:\vcpkg\downloads

**Expected behavior**
expected it to build just as if vcpkg was using a local drive

**Solution** 
use a local path for the cache

    Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_0d797 && [1/4] Building Fortran preprocessed CMakeFiles/cmTC_0d797.dir/testFortranCompiler.f-pp.f
    [2/4] Generating Fortran dyndep file CMakeFiles/cmTC_0d797.dir/Fortran.dd
    [3/4] Building Fortran object CMakeFiles/cmTC_0d797.dir/testFortranCompiler.f.obj
    [4/4] Linking Fortran executable cmTC_0d797.exe
    FAILED: cmTC_0d797.exe 
    cmd.exe /C "cd . && O:\vcpkg\downloads\tools\msys2\30c737b9af355d42\mingw64\bin\gfortran.exe -mabi=ms -m64  CMakeFiles/cmTC_0d797.dir/testFortranCompiler.f.obj -o cmTC_0d797.exe -Wl,--out-implib,libcmTC_0d797.dll.a -Wl,--major-image-version,0,--minor-image-version,0   && cd ."
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../lib/crt2.o: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/crtbegin.o: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgfortran: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmingw32: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgcc_s: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgcc: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmoldname: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmingwex: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmsvcrt: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lkernel32: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lquadmath: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lm: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmingw32: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgcc_s: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgcc: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmoldname: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmingwex: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmsvcrt: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lkernel32: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lpthread: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -ladvapi32: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lshell32: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -luser32: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lkernel32: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmingw32: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgcc_s: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgcc: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmoldname: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmingwex: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmsvcrt: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lkernel32: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../lib/default-manifest.o: Invalid argument
    //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find //oooo/vol1/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/crtend.o: Invalid argument

    collect2.exe: error: ld returned 1 exit status
    ninja: build stopped: subcommand failed.

**Comment by autoantwort** [comment]
This has nothing to do with the binary cache but with `VCPKG_DOWNLOADS=o:\vcpkg\downloads`. So the title should be 
`lapack fails to build on windows when using a networked drive for the vcpkg downloads dir`

**Comment by MonicaLiu0311** [comment]
```
PS E:\vcpkg01> ./vcpkg version
vcpkg package management program version 2023-06-22-f19f3d9939100085fe2f7e41502d60b08e2083b6

See LICENSE.txt for license information.
```
Confirm, repro locally.
* Create a network drive
  ![image](https://github.com/microsoft/vcpkg/assets/110024546/64eeb1bf-aa58-4bea-b853-1ebad87e984e)
* Run `./vcpkg install lapack:x64-windows --binarysource=clear --downloads-root="Z:/vcpkg/downloads"`


```
PS E:\vcpkg01> ./vcpkg install lapack:x64-windows --binarysource=clear --downloads-root="Z:/vcpkg/downloads"
Computing installation plan...
The following packages will be built and installed:
    lapack:x64-windows -> 2022-02-22#2
  * lapack-reference[blas-select,core,noblas]:x64-windows -> 3.11.0#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Installing 1/2 lapack-reference:x64-windows...
Building lapack-reference[blas-select,core,noblas]:x64-windows...
-- Using cached Reference-LAPACK-lapack-v3.11.0.tar.gz.
-- Cleaning sources at E:/vcpkg01/buildtrees/lapack-reference/src/v3.11.0-5e6de67bfb.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source Z:/vcpkg/downloads/Reference-LAPACK-lapack-v3.11.0.tar.gz
-- Applying patch cmake-config.patch
-- Applying patch lapacke.patch
-- Using source at E:/vcpkg01/buildtrees/lapack-reference/src/v3.11.0-5e6de67bfb.clean
-- The Fortran compiler identification is unknown
-- No Fortran compiler found on the PATH. Using MinGW gfortran!
-- Downloading https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-gcc-fortran-13.1.0-6-any.pkg.tar.zst;https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-gcc-fortran-13.1.0-6-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/mingw64/mingw-w64-x86_64-gcc-fortran-13.1.0-6-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-gcc-fortran-13.1.0-6-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-gcc-fortran-13.1.0-6-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/mingw64/mingw-w64-x86_64-gcc-fortran-13.1.0-6-any.pkg.tar.zst -> mingw-w64-x86_64-gcc-fortran-13.1.0-6-any.pkg.tar.zst...
...

-- Using msys root at Z:/vcpkg/downloads/tools/msys2/30c737b9af355d42
-- Found external ninja('1.11.0').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: E:/vcpkg01/buildtrees/lapack-reference/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      E:\vcpkg01\buildtrees\lapack-reference\config-x64-windows-CMakeCache.txt.log
      E:\vcpkg01\buildtrees\lapack-reference\config-x64-windows-CMakeCache.txt.log
      E:\vcpkg01\buildtrees\lapack-reference\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:247 (vcpkg_execute_required_process)
  ports/lapack-reference/portfile.cmake:66 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)
```
**config-x64-windows-out.log:**
```
CMake Error at //monica001/share_path/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/share/cmake-3.25/Modules/CMakeTestFortranCompiler.cmake:62 (message):
  The Fortran compiler

    "Z:/vcpkg/downloads/tools/msys2/30c737b9af355d42/mingw64/bin/gfortran.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: E:/vcpkg01/buildtrees/lapack-reference/x64-windows-rel/CMakeFiles/CMakeScratch/TryCompile-cljecu
    
    Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_c34c1 && [1/4] Building Fortran preprocessed CMakeFiles/cmTC_c34c1.dir/testFortranCompiler.f-pp.f
    [2/4] Generating Fortran dyndep file CMakeFiles/cmTC_c34c1.dir/Fortran.dd
    [3/4] Building Fortran object CMakeFiles/cmTC_c34c1.dir/testFortranCompiler.f.obj
    [4/4] Linking Fortran executable cmTC_c34c1.exe
    FAILED: cmTC_c34c1.exe 
```

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/12067598/config-x64-windows-out.log)
[config-x64-windows-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/12067600/config-x64-windows-CMakeCache.txt.log)


Currently, there are two ports using `vcpkg_find_fortran()` in vcpkg, both of which will fail to build under the above premise.
```
arpack-ng
lapack-reference
```
