### ISSUE TITLE
[fmt] Add C++20 module feature

### ISSUE THREAD

**Issue by sharadhr** [microsoft/vcpkg#32572]
### Is your feature request related to a problem? Please describe.

`fmt` may now be built as a C++20 module, as detailed [here](https://github.com/fmtlib/fmt/releases/tag/10.0.0#:~:text=allows%20building%20%7Bfmt%7D%20as%20a%20C%2B%2B20%20module%20with%20clang). Although vcpkg has updated it to v10.0.0, the feature to build it as a module is missing, and requires a custom port overlay.

### Proposed solution

Add in a vcpkg feature to build fmt as a C++ module, so consumers may use it as `import fmt;` in their codebases. This will require accounting for the `FMT_MODULE` CMake option for the fmt build, as mentioned above.

**Comment by autoantwort** [comment]
I guess this is not additive and requires https://github.com/microsoft/vcpkg/pull/22216?

**Comment by sharadhr** [comment]
> I guess this is not additive and requires #22216?

Really? I was under the impression the features functionality would have sufficed:

```json
...
"dependencies": [
  ...
  {
    "name": "fmt",
    "features": ["cppmodule"] // example
  },
]
```

**Comment by autoantwort** [comment]
The question is: Does a port that depends on `fmt` also works when `fmt[cppmodule]` gets installed?

**Comment by sharadhr** [comment]
I would think that given fmt is a header-only library, the default feature should still imply that all fmt headers are copied to the relevant `*/include` directory, whereas the `fmt[cppmodule]` feature would mean that it is built separately as a module, and would live in the `*/lib` directory.

**Comment by autoantwort** [comment]
But if then liba depends on fmt and libb on fmt[cppmodule] and you install liba and libb it must work

**Comment by JonLiu1993** [comment]
@sharadhr, Thanks for posting this issue, add feature `cppmodule` will change C++ build stander. -std:c++20:
````
[1/3] C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1436~1.325\bin\Hostx64\x64\cl.exe   /TP -DFMT_LIB_EXPORT -Dfmt_EXPORTS -IF:\test\vcpkg\buildtrees\fmt\src\10.0.0-cbbdb219f9\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++20 -MDd /interface /ifcOutput F:/test/vcpkg/buildtrees/fmt/x64-windows-dbg/fmt.ifc /showIncludes /FoCMakeFiles\fmt.dir\src\fmt.cc.obj /FdCMakeFiles\fmt.dir\ /FS -c F:\test\vcpkg\buildtrees\fmt\src\10.0.0-cbbdb219f9\src\fmt.cc

````

This is not allowed in our policy: https://learn.microsoft.com/en-us/vcpkg/contributing/maintainer-guide#do-not-use-features-to-control-alternatives-in-published-interfaces
