### ISSUE TITLE
[boost-exception] Build error

### ISSUE THREAD

**Issue by derossm** [microsoft/vcpkg#32588]
Package: boost-exception:x64-windows -> 1.82.0#2

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.37.32820.0
-    vcpkg-tool version: 2023-06-22-f19f3d9939100085fe2f7e41502d60b08e2083b6
    vcpkg-scripts version: fba81a6a5 2023-07-14 (2 days ago)

**To Reproduce**

`vcpkg install boost`

**Failure logs**

```
-- Using cached boostorg-exception-boost-1.82.0.tar.gz.
-- Cleaning sources at F:/dev/vcpkg/buildtrees/boost-exception/src/ost-1.82.0-efb4d34eb1.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/dev/vcpkg/downloads/boostorg-exception-boost-1.82.0.tar.gz
-- Using source at F:/dev/vcpkg/buildtrees/boost-exception/src/ost-1.82.0-efb4d34eb1.clean
CMake Error at installed/x64-windows/share/boost-build/boost-modular-build.cmake:39 (message):
  Could not find b2 in F:/dev/vcpkg/installed/x64-windows/tools/boost-build
Call Stack (most recent call first):
  ports/boost-exception/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:147 (include)



```

**Additional context**
Windows 11 Security is quarantining "vcpkg\installed\x64-windows\tools\boost-build\b2.exe" (for 1.82.0#2) as a threat detected "Trojan:Win32/Bearfoos.A!ml"

1.82.0#1 was fine. I don't know if this is a false positive from 1.82.0#2 being new (I also don't know when 1.82.0#2 came out) or an actual issue.

**Comment by JonLiu1993** [comment]
@derossm, Thanks for posting this issue, I can not repoduce your error with latest vcpkg package(boost-exeption version is 1.82.0#2)
````
PS F:\test\vcpkg> ./vcpkg install boost
warning: Starting with the September 2023 release, the default triplet for vcpkg libraries will change from x86-windows to the detected host triplet (x64-windows). To resolve this message, add --triplet x86-windows to keep the same behavior.
Computing installation plan...
The following packages are already installed:
    boost:x86-windows -> 1.82.0#2
boost:x86-windows is already installed
Total install time: 2.11 ms
PS F:\test\vcpkg>
````
Do you have antivirus software installed on your computer? I suspect that the problem may be due to antivirus software mistakenly blocking `vcpkg\installed\x64-windows\tools\boost-build\b2.exe`.

**Comment by derossm** [comment]
@JonLiu1993 the default Windows Security anti-virus (windows 11) is blocking b2.exe as "Trojan:Win32/Bearfoos.A!ml"

I suspect it is a false positive, but I don't actually know how vcpkg verifies new packages are authentic, so I made the ticket just in case someone who knows more can determine if it's something to worry about or safe to ignore.

**Comment by JonLiu1993** [comment]
@derossm, I investigated the modification of [1.82.0#2](https://github.com/microsoft/vcpkg/pull/31572/files), its modification has nothing to do with the error we reported, I think it is a false positive of antivirus software

**Comment by JonLiu1993** [comment]
@andreamartini, does this problem still exist?

**Comment by andreamartini** [comment]
Unfortunally this problema still exists, even of i have followed all your
suggestions. The error message Is the same.


Il gio 10 ago 2023, 09:04 JonLiu1993 ***@***.***> ha scritto:

**Comment by JonLiu1993** [comment]
@derossm, sorry reply you so late, could you please use the latest vcpkg try again?

**Comment by JonLiu1993** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
