### ISSUE TITLE
[New Port Request] <kirigami>

### ISSUE THREAD

**Issue by ilongshan** [microsoft/vcpkg#32592]
### Library name

kirigami

### Library description

A QtQuick based components set

### Source repository URL

https://github.com/KDE/kirigami.git

### Project homepage (if different from the source repository)

https://develop.kde.org/frameworks/kirigami/

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

Kirigami is a set of [QtQuick](https://doc.qt.io/qt-6/qtquick-index.html) components for building adaptable user interfaces based on [QtQuick Controls 2](https://doc.qt.io/qt-6/qtquickcontrols-index.html). Kirigami makes it easy to create applications that look and feel great on [Plasma Mobile](https://plasma-mobile.org/), Desktop Linux, Android, MacOS, and Windows.

**Comment by vserdyuk** [comment]
Comment to keep issue open. Personally, I would prefer a Qt6-based version when Plasma 6 gets released.

**Comment by ilongshan** [comment]
Comment to keep issue open

**Comment by vserdyuk** [comment]
bump

**Comment by ilongshan** [comment]
bump
