### ISSUE TITLE
[openssl] Build failure due to nasm.us being down

### ISSUE THREAD

**Issue by Morph1984** [microsoft/vcpkg#32600]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
`./vcpkg install openssl`
```

### Failure logs

```
Installing 80/81 openssl:x64-windows...
Building openssl:x64-windows...
-- Installing port from location: D:\a\yuzu\yuzu\externals\vcpkg\buildtrees\versioning_\versions\openssl\dc8edd2b6e1e1552688c29dc46d5cd5c9183804b
-- Downloading https://github.com/openssl/openssl/archive/openssl-3.1.1.tar.gz -> openssl-openssl-openssl-3.1.1.tar.gz...
-- Extracting source D:/a/yuzu/yuzu/externals/vcpkg/downloads/openssl-openssl-openssl-3.1.1.tar.gz
-- Applying patch disable-apps.patch
-- Applying patch disable-install-docs.patch
-- Applying patch script-prefix.patch
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch unix/android-cc.patch
-- Applying patch unix/move-openssldir.patch
-- Applying patch unix/no-empty-dirs.patch
-- Applying patch unix/no-static-libs-for-shared.patch
-- Using source at D:/a/yuzu/yuzu/externals/vcpkg/buildtrees/openssl/src/nssl-3.1.1-53a8e40f57.clean
-- Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip -> nasm-2.16.01-win64.zip...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from D:\a\yuzu\yuzu\externals\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: D:\a\yuzu\yuzu\externals\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip
warning: Download failed -- retrying after 1000ms
warning: Download failed -- retrying after 2000ms
warning: Download failed -- retrying after 4000ms
error: Failed to download from mirror set
error: https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip: WinHttpSendRequest failed with exit code 12002
error: https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip: WinHttpSendRequest failed with exit code 12002
error: https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip: WinHttpSendRequest failed with exit code 12002
error: https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip: WinHttpSendRequest failed with exit code 12002
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(962): 
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 15us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 1211us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 1.5 min (91186431us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
      

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_find_acquire_program.cmake:172 (vcpkg_download_distfile)
  buildtrees/versioning_/versions/openssl/dc8edd2b6e1e1552688c29dc46d5cd5c9183804b/windows/portfile.cmake:1 (vcpkg_find_acquire_program)
  buildtrees/versioning_/versions/openssl/dc8edd2b6e1e1552688c29dc46d5cd5c9183804b/portfile.cmake:68 (include)
  scripts/ports.cmake:147 (include)


error: building openssl:x64-windows failed with: BUILD_FAILED
Elapsed time to handle openssl:x64-windows: 1.6 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[openssl]+Build+error&body=Copy+issue+body+from+D%3A%2Fa%2Fyuzu%2Fyuzu%2Fbuild%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md
You can also sumbit an issue by running (GitHub cli must be installed):
    gh issue create -R microsoft/vcpkg --title "[openssl] Build failure" --body-file D:/a/yuzu/yuzu/build/vcpkg_installed/vcpkg/issue_body.md
-- Running vcpkg install - failed
CMake Error at externals/vcpkg/scripts/buildsystems/vcpkg.cmake:893 (message):
  vcpkg install failed.  See logs for more information:
  D:\a\yuzu\yuzu\build\vcpkg-manifest-install.log
Call Stack (most recent call first):
  CMakeLists.txt:149 (include)
  ```

### Additional context

nasm.us is down, and no additional mirrors are provided.

**Comment by StarGate-One** [comment]
I have a cached copy in my vcpkg/downloads folder, hope this helps, just drop into your vcpkg/downloads folder:
[nasm-2.16.01-win64.zip](https://github.com/microsoft/vcpkg/files/12073957/nasm-2.16.01-win64.zip)

**Comment by jimwang118** [comment]
The download of `nasm-2.16.01-win64.zip` failed. Please check the network proxy and check whether there is a firewall or anti-virus software blocking the download.

**Comment by xengine-qyt** [comment]
cant open nasm web

**Comment by v-mkmiecik** [comment]
Shouldn't there be a mirror in case the main source is down? I can't use a cached copy like StarGate-One suggested since I'm using automation.

**Comment by lintrust** [comment]
> I have a cached copy in my vcpkg/downloads folder, hope this helps, just drop into your vcpkg/downloads folder: [nasm-2.16.01-win64.zip](https://github.com/microsoft/vcpkg/files/12073957/nasm-2.16.01-win64.zip)

it works, thanks~

**Comment by berkayozcan** [comment]
> I have a cached copy in my vcpkg/downloads folder, hope this helps, just drop into your vcpkg/downloads folder: [nasm-2.16.01-win64.zip](https://github.com/microsoft/vcpkg/files/12073957/nasm-2.16.01-win64.zip)

Thanks! It works, but need to fix that

**Comment by BillyONeal** [comment]
> Shouldn't there be a mirror in case the main source is down?

The vcpkg team doesn't currently operate such mirrors because it involves licensing mess.

**Comment by maxseg2021** [comment]
somebody has the mac zip file for this? it is still down.

**Comment by pavelzw** [comment]
They are up again so this issue can be closed.

**Comment by SethBe** [comment]
@jimwang118  this issue seems to be back.

**Comment by jimwang118** [comment]
> @jimwang118 this issue seems to be back.

Yes, the upstream website can’t be opened again, so we need to wait for the upstream website to recover.

**Comment by Alexufo** [comment]
today
https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip: 
WinHttpSendRequest failed with exit code 12002

**Comment by juanmalm** [comment]
This is happening again...

**Comment by retifrav** [comment]
> again

Something new happened over the [past 7 hours](#issuecomment-1648871059)?

**Comment by 0x0ACB** [comment]
Maybe switch over to https://fossies.org/windows/misc/nasm-2.16.01-win64.zip ?

**Comment by TheNetos** [comment]
Why not use the [mirror](https://github.com/netwide-assembler/nasm)?

**Comment by blackliner** [comment]
> Why not use the [mirror](https://github.com/netwide-assembler/nasm)?

The content seems to be different
```
  "2.15.05":
    sha256: "3caf6729c1073bf96629b57cee31eeb54f4f8129b01902c73428836550b30a3f"
    url: "https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/nasm-2.15.05.tar.xz"
```
becoms
```
    sha256: "f575c516b5c1c28d5d64efdc26ed52b137ad36bfbd2d855d4782f050ca964245"
    url: "https://github.com/netwide-assembler/nasm/archive/refs/tags/nasm-2.15.05.tar.gz"
```

**Comment by dg0yt** [comment]
> Maybe switch over to https://fossies.org/windows/misc/nasm-2.16.01-win64.zip ?

fossies.org's Terms of Use forbid "regular automated accesses" so AFAIU it cannot be used as part of build recipes or CI. 
Cf. https://fossies.org/about.html 

> Why not use the [mirror](https://github.com/netwide-assembler/nasm)?

vcpkg fails to download binaries (nasm-2.16.01-win64.zip). The github repo doesn't provide them AFAICS.

---

MSYS2 has nasm binaries, but these are independent builds.
https://packages.msys2.org/base/mingw-w64-nasm

**Comment by TheNetos** [comment]
> > Why not use the [mirror](https://github.com/netwide-assembler/nasm)?
> 
> The content seems to be different
> 
> ```
>   "2.15.05":
>     sha256: "3caf6729c1073bf96629b57cee31eeb54f4f8129b01902c73428836550b30a3f"
>     url: "https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/nasm-2.15.05.tar.xz"
> ```
> 
> becoms
> 
> ```
>     sha256: "f575c516b5c1c28d5d64efdc26ed52b137ad36bfbd2d855d4782f050ca964245"
>     url: "https://github.com/netwide-assembler/nasm/archive/refs/tags/nasm-2.15.05.tar.gz"
> ```

Different algorithms for compressing archives give different hashes, it looks like this

**Comment by TheNetos** [comment]
> vcpkg fails to download binaries (nasm-2.16.01-win64.zip). The github repo doesn't provide them AFAICS.

Well, by tag `nasm-2.16.01` i see only `https://github.com/netwide-assembler/nasm/archive/refs/tags/nasm-2.16.01.zip`, non-windows-specific version

thats sad

**Comment by BillyONeal** [comment]
Anyone have contact info for the nasm.us folks? If they would put the content on github we would love to add mirrors. We have historically not operated our own mirrors because licensing scary, not because we don't think it would be an improvement.

**Comment by mc-nv** [comment]
I'm keep seeing issue by trying to reach given mirror.

**Comment by dg0yt** [comment]
> Anyone have contact info for the nasm.us folks?

Maybe https://lists.nasm.us/nasm-devel/, [nasm-devel@nasm.us](mailto:nasm-devel@nasm.us)?

**Comment by TheNetos** [comment]
[nasm.us](nasm.us) is available (at the time of writing this comment).

**Comment by yisonPylkita** [comment]
Its down again :( 
![image](https://github.com/microsoft/vcpkg/assets/8435296/f8f63762-1899-4779-bb69-2eb89e1fb745)

**Comment by theduckrules** [comment]
> I have a cached copy in my vcpkg/downloads folder, hope this helps, just drop into your vcpkg/downloads folder: [nasm-2.16.01-win64.zip](https://github.com/microsoft/vcpkg/files/12073957/nasm-2.16.01-win64.zip)

Thank you!  I was stumped until I read your solution.

**Comment by stephengtuggy** [comment]
So https://nasm.us is back up. Their homepage indicates that their source code is already on GitHub, at https://github.com/netwide-assembler/nasm

**Comment by StarGate-One** [comment]
The source code is, but at this time vcpkg does not build `nasm` - it just downloads the appropriate pre-built binaries from https://nasm.us...

**Comment by jmevel** [comment]
> So https://nasm.us is back up. Their homepage indicates that their source code is already on GitHub, at https://github.com/netwide-assembler/nasm

And....... It's back down again 🙄

**Comment by stephengtuggy** [comment]
Is there any compelling reason not to build from source? This is becoming kind of a nuisance.

**Comment by StarGate-One** [comment]
A mirror was added in commit https://github.com/microsoft/vcpkg/commit/fe1369ae9008da49a0b65e1fd26abeff2f257c71 today, so you may need to do a `git pull` to update `scripts/cmake/vcpkg_find_acquire_program(NASM).cmake` script.

**Comment by jimwang118** [comment]
This PR [32806](https://github.com/microsoft/vcpkg/pull/32806) adds a different `nasm` download address, update `vcpkg` to get it if you need it.
