### ISSUE TITLE
[libp11] Build error

### ISSUE THREAD

**Issue by CharlieZhBEP** [microsoft/vcpkg#32612]
Building package libp11[core]:arm64-linux...
-- Using community triplet arm64-linux. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /build/vcpkg/triplets/community/arm64-linux.cmake
-- Installing port from location: /root/.cache/vcpkg/registries/git-trees/3e1dfab09a42b5321a76f7df1f131f66aa06ac24
-- Note: libp11 only supports dynamic library linkage. Building dynamic library.
-- Using cached /build/vcpkg/downloads/libp11-9ca6a71c890b5583c8af3b4900172626bca55e72.tar.gz
-- Cleaning sources at /build/vcpkg/buildtrees/libp11/src/26bca55e72-1572b0719a.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /build/vcpkg/downloads/libp11-9ca6a71c890b5583c8af3b4900172626bca55e72.tar.gz
-- Applying patch store_key_cert.patch
-- Using source at /build/vcpkg/buildtrees/libp11/src/26bca55e72-1572b0719a.clean
-- Getting CMake variables for arm64-linux-dbg
-- Getting CMake variables for arm64-linux-rel
-- Generating configure for arm64-linux
-- Finished generating configure for arm64-linux
-- Prerun shell with arm64-linux
-- Configuring arm64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: /bin/bash -c "V=1 ./../src/26bca55e72-1572b0719a.clean/configure  \"--disable-silent-rules\" \"--verbose\" \"--enable-shared\" \"--disable-static\" \"--prefix=/build/europa/build-debug-arm64/vcpkg_installed/arm64-linux/debug\" \"--bindir=\\${prefix}/../tools/libp11/debug/bin\" \"--sbindir=\\${prefix}/../tools/libp11/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/libp11\""
    Working Directory: /build/vcpkg/buildtrees/libp11/arm64-linux-dbg
    Error code: Subprocess killed
    See logs for more information:
      /build/vcpkg/buildtrees/libp11/config-arm64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:796 (vcpkg_execute_required_process)
  /root/.cache/vcpkg/registries/git-trees/3e1dfab09a42b5321a76f7df1f131f66aa06ac24/portfile.cmake:11 (vcpkg_configure_make)
  scripts/ports.cmake:142 (include)

Error: Building package libp11:arm64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libp11
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libp11]+Build+error
including:
  package: libp11[core]:arm64-linux -> 3.4.3#3
    vcpkg-tool version: 2021-11-24-unknownhash
    vcpkg-scripts version: 5ddd7f026 2021-12-01 (1 year, 7 months ago)

**Comment by CharlieZhBEP** [comment]
root@5c59eb86fbbb:/build/vcpkg/buildtrees/libp11# cat config-arm64-linux-dbg-out.log 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking build system type... aarch64-unknown-linux-gnu
checking host system type... aarch64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... root@5c59eb86fbbb:/build/vcpkg/buildtrees/libp11#

**Comment by CharlieZhBEP** [comment]
> Could you please provide the error log? `/build/vcpkg/buildtrees/libp11/config-arm64-linux-dbg-out.log`

**Comment by autoantwort** [comment]
> vcpkg-tool version: 2021-11-24-unknownhash
vcpkg-scripts version: https://github.com/microsoft/vcpkg/commit/5ddd7f02689b7c5aab78711d77f61db5d2e5e79c 2021-12-01 (1 year, 7 months ago)

You are using a very old vcpkg version. Maybe try to update vcpkg first: https://learn.microsoft.com/en-us/vcpkg/about/faq#how-do-i-update-vcpkg

**Comment by CharlieZhBEP** [comment]
> > vcpkg-tool version: 2021-11-24-unknownhash
> > vcpkg-scripts version: [5ddd7f0](https://github.com/microsoft/vcpkg/commit/5ddd7f02689b7c5aab78711d77f61db5d2e5e79c) 2021-12-01 (1 year, 7 months ago)
> 
> You are using a very old vcpkg version. Maybe try to update vcpkg first: https://learn.microsoft.com/en-us/vcpkg/about/faq#how-do-i-update-vcpkg

doesn't resolve the issue. The building was successful in last week.

**Comment by FrankXie05** [comment]
> root@5c59eb86fbbb:/build/vcpkg/buildtrees/libp11# cat config-arm64-linux-dbg-out.log checking for a BSD-compatible install... /usr/bin/install -c checking whether build environment is sane... yes checking for a thread-safe mkdir -p... /bin/mkdir -p checking for gawk... no checking for mawk... mawk checking whether make sets $(MAKE)... yes checking whether make supports nested variables... yes checking whether make supports nested variables... (cached) yes checking build system type... aarch64-unknown-linux-gnu checking host system type... aarch64-unknown-linux-gnu checking for gcc... gcc checking whether the C compiler works... yes checking for C compiler default output file name... a.out checking for suffix of executables... checking whether we are cross compiling... root@5c59eb86fbbb:/build/vcpkg/buildtrees/libp11#

Please provide the complete file, I don't see the error message

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
