### ISSUE TITLE
install leveldb failed?

### ISSUE THREAD

**Issue by BlackTrace** [Microsoft/vcpkg#3261]
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: D:/src/vcpkg/buildtrees/leveldb/x86-windows-rel/vcpkg-parallel-configure
    See logs for more information:
      D:\src\vcpkg\buildtrees\leveldb\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:237 (vcpkg_execute_required_process)
  ports/leveldb/portfile.cmake:24 (vcpkg_configure_cmake)
  scripts/ports.cmake:72 (include)

Error: Building package leveldb:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: leveldb:x86-windows
  Vcpkg version: 0.0.108-2018-04-13-4e48a1c235d776b5099a61252ff726edb5b6a6b7

**Comment by BlackTrace** [comment]
boost
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: D:/src/vcpkg/packages/boost-build_x86-windows/tools/boost-build/bootstrap.bat;msvc
    Working Directory: D:/src/vcpkg/packages/boost-build_x86-windows/tools/boost-build
    See logs for more information:
      D:\src\vcpkg\buildtrees\boost-build\bootstrap-x86-windows-out.log
      D:\src\vcpkg\buildtrees\boost-build\bootstrap-x86-windows-err.log

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:53 (vcpkg_execute_required_process)
  scripts/ports.cmake:72 (include)


Error: Building package boost-build:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-build:x86-windows
  Vcpkg version: 0.0.108-2018-04-13-4e48a1c235d776b5099a61252ff726edb5b6a6b7

**Comment by jenokizm** [comment]
Hi, the setup works for me. The problem is different, after the program is not compiled and gives an error when using this library. [Here is my topic](https://github.com/Microsoft/vcpkg/issues/2909) which is already very long hanging and no one answers me! I am angry.

**Comment by NancyLi1013** [comment]
Please open a new issue if this is still a problem for you.
