### ISSUE TITLE
Compiler error when install opencv through vcpkg

### ISSUE THREAD

**Issue by zpw6106** [microsoft/vcpkg#32616]
I get the following compiler error when run vcpkg install opencv4[contrib,world]:x64-windows 
compiler version: visual studio 2022 MSVC 1436~1.325

E:\vcpkg\buildtrees\opencv4\src\4.7.0-87379d1df6.clean\modules\core\include\opencv2\core\mat.inl.hpp(822) : fatal error C1001: Internal compiler error.
(compiler file 'D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 225)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com 
Please choose the Technical Support command on the Visual C++ 
 Help menu, or open the Technical Support help file for more information

**Comment by autoantwort** [comment]
You have to report this to https://developercommunity.visualstudio.com/. 
Try to update your compiler version or downgrade to an older version.

**Comment by zpw6106** [comment]
@autoantwort I try to downgrade an older version, but the vcpkg will not find the vistual studio instances. It seems that the latest version can be used, but Opencv and OpenImageIO have the same compilation issue, which appears to be a compiler optimization issue.

**Comment by zpw6106** [comment]
@JonLiu1993 Thank you for your feedback，I will report this issue into [Visual Studio feedback](https://developercommunity.visualstudio.com/cpp/report).
