### ISSUE TITLE
cpprestsdk missing pplx threadpool.h

### ISSUE THREAD

**Issue by Chrys4lisfag** [microsoft/vcpkg#32624]
**Describe the bug**

**Environment**
- OS: winodws 10
- VS22, all latest

**To Reproduce**
1. ./vcpkg cpprestsdk:x64-windows-static
2. Visit installed\x64-windows-static\include\pplx and see not threadpool.h
Only have:
pplx.h
pplxcancellation_token.h
pplxconv.h
pplxinterface.h
pplxlinux.h
pplxtasks.h
pplxwin.h

cpprestsdk:x64-windows-static                            2.10.18#2              C++11 JSON, REST, and OAuth library
cpprestsdk[brotli]:x64-windows-static                                               Brotli compression support
cpprestsdk[compression]:x64-windows-static                                   HTTP Compression support
cpprestsdk[default-features]:x64-windows-static                              Features installed by default

**Comment by jimwang118** [comment]
This issue could be reproduced with vcpkg 2023-06-22-f19f3d9939100085fe2f7e41502d60b08e2083b6. I will try to fix it.

**Comment by Chrys4lisfag** [comment]
> After checking the compilation logic in the upstream `cmakelists.txt`, the header file `threadpool.h` is only referenced when the `websockets` feature is enabled.

Thanks!

**Comment by jimwang118** [comment]
If my reply can solve your problem, I will close this issue.
