### ISSUE TITLE
where is opencv dnn module ?

### ISSUE THREAD

**Issue by how0723** [Microsoft/vcpkg#3262]
where is opencv dnn module ?
there is no dnn module when using vcpkg to build opencv ? why ?

how to config HAVE_OPENCV_DNN

**Comment by arthur-tacca** [comment]
You can find the answer to this question by checking the OpenCV package:

    c:\src\vcpkg>vcpkg search opencv
    opencv               3.4.1            computer vision library
    opencv[opengl]                        opengl support for opencv
    opencv[dnn]                           opencv_dnn module
    opencv[ovis]                          opencv_ovis module
    opencv[flann]                         opencv_flann module
    opencv[sfm]                           opencv_sfm module
    opencv[contrib]                       opencv_contrib module
    opencv[cuda]                          CUDA support for opencv
    opencv[ffmpeg]                        prebuilt ffmpeg support for opencv
    opencv[ipp]                           Enable Intel Integrated Performance Primitives
    opencv[qt]                            Qt GUI support for opencv
    opencv[vtk]                           vtk support for opencv
    opencv[gdcm]                          GDCM support for opencv
    opencv[webp]                          WebP support for opencv
    opencv[openexr]                       OpenEXR support for opencv
    opencv[tiff]                          TIFF support for opencv
    opencv[png]                           PNG support for opencv
    opencv[jpeg]                          JPEG support for opencv
    opencv[jasper]                        JPEG 2000 support for opencv
    opencv[eigen]                         Eigen support for opencv

    If your library is not listed, please open an issue at and/or consider making a pull request:
        https://github.com/Microsoft/vcpkg/issues


Notice that `dnn` is an optional module and so `vcpkg install opencv` won't install it by default. You need to run:

    vcpkg install opencv[dnn]

**Comment by MikePelton** [comment]
Is it just me or does the dnn library not actually get built? OpenCV 3.4.3, Win 10 x64 - it all appears to have run fine but there's no opencv_dnn343.lib resulting at the end of the process.

**Comment by MikePelton** [comment]
Nope, not just me, this has been picked up as an issue from 7 days ago. Pls disregard this.

**Comment by PhoebeHui** [comment]
Thanks arthur-tacca for the information! Looks the issue solved, and vcpkg install opencv[dnn] successfully installed.

Building package opencv[core,dnn,eigen,flann,jpeg,opengl,png,tiff]:x86-windows... done
Installing package opencv[core,dnn,eigen,flann,jpeg,opengl,png,tiff]:x86-windows...
Installing package opencv[core,dnn,eigen,flann,jpeg,opengl,png,tiff]:x86-windows... done
Elapsed time for package opencv:x86-windows: 12.51 min

Total elapsed time: 17.19 min

The package opencv provides CMake integration:

    find_package(OpenCV REQUIRED)
    target_include_directories(main PRIVATE ${OpenCV_INCLUDE_DIRS})
    target_link_libraries(main PRIVATE ${OpenCV_LIBS})

**Comment by HungMingWu** [comment]
I got problems at linux x64.
On Windows 10 x64, it works. But cannot generate libopencv_dnn.a
Does anyone  have similar issue?

**Comment by axayjain** [comment]
Got same problem in ubuntu. dnn library is missing from "/usr/include/opencv2/"
