### ISSUE TITLE
[qt5-base] Build error

### ISSUE THREAD

**Issue by berkayozcan** [microsoft/vcpkg#32636]
error: building qt5-base:x64-windows-static-md failed with: BUILD_FAILED
Elapsed time to handle qt5-base:x64-windows-static-md: 3 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.

**Comment by autoantwort** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report an issue.

**Comment by MonicaLiu0311** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
