### ISSUE TITLE
error: building protobuf:x64-windows failed with: BUILD_FAILED Elapsed time to handle protobuf:x64-windows: 2.8 min

### ISSUE THREAD

**Issue by lixinye666** [microsoft/vcpkg#32632]
### Operating system

windows

### Steps to reproduce the behavior

```Shell
error: building protobuf:x64-windows failed with: BUILD_FAILED
Elapsed time to handle protobuf:x64-windows: 2.8 min
```

### Failure logs

error: building protobuf:x64-windows failed with: BUILD_FAILED
Elapsed time to handle protobuf:x64-windows: 2.8 min

mt.exe : general error c101008d: Failed to write the updated manifest to the resource of file "libprotoc.dll". The system cannot open the device or file specified.
ninja: build stopped: subcommand failed.

-- Installing: D:/segment-anything-cpp-wrapper-1.4.1/cpp/segment-anything-cpp-wrapper-1.4.1/segment-anything-cpp-wrapper-1.4.1/vcpkg/packages/protobuf_x64-windows/debug/share/protobuf/protobuf-module.cmake
-- Installing: D:/segment-anything-cpp-wrapper-1.4.1/cpp/segment-anything-cpp-wrapper-1.4.1/segment-anything-cpp-wrapper-1.4.1/vcpkg/packages/protobuf_x64-windows/debug/share/protobuf/protobuf-options.cmake

**Comment by JonLiu1993** [comment]
@lixinye666, Thanks for posting this issue, I can install protobuf:x64-windows on my machine, This issue may be caused by antivirus software. You can try closing the antivirus software before installing this port.
````
mt.exe : general error c101008d: Failed to write the updated manifest to the resource of file "libprotoc.dll". The system cannot open the device or file specified.
````

**Comment by JonLiu1993** [comment]
@lixinye666, Does this issue still exist?

**Comment by JonLiu1993** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
