### ISSUE TITLE
[skia] Include Path should point to include/ instead of include/skia

### ISSUE THREAD

**Issue by ulfllorenz** [microsoft/vcpkg#32657]
### Is your feature request related to a problem? Please describe.

The described problem was encountered on a Windows dev machine with Visual Studio 22 as build environment and CMake 3.21.4.  

We include skia vcpkg port in own projects using CMake. When including it the recommended way ...

```
...
find_package(unofficial-skia CONFIG REQUIRED)
...
target_link_libraries(myProject PRIVATE unofficial::skia::skia)
```
then CMake generates visual studio projects with an additional include files directory pointing to  
`...\vcpkg\installed\x64-windows\include\skia`.

So in cpp source code using skia we have to include skia header files like this:

```
#include <core/SkSurface.h>
```

A better way would be to be able to include skia header files like this 
```
#include <skia/core/SkSurface.h>
```
This is also the way other vcpkg ports like gtest do it. This would require the aforementioned additional include directory to point to `...\vcpkg\installed\x64-windows\include\`. Please consider updating the port in this way.

**Additonal Note**
When using the "skia"-package instead of "unofficial-skia", e.g. 
```
find_package(skia CONFIG REQUIRED)
...
target_link_libraries(myProject PRIVATE skia::skia)
```
then the include directory points to  `...\vcpkg\installed\x64-windows\include\` as desired. But CMake generates warnings with that configuration:
```
  find_package(skia) is deprecated.
  skia provides CMake targets:
      find_package(unofficial-skia CONFIG REQUIRED)
      target_link_libraries(main PRIVATE unofficial::skia::skia)
```

### Proposed solution

When integration skia vcpkg port in CMake via

```
...
find_package(unofficial-skia CONFIG REQUIRED)
...
target_link_libraries(myProject PRIVATE unofficial::skia::skia)
```

please make the include directory in CMake-generated C++ projects point to `...\vcpkg\installed\x64-windows\include\` instead of `...\vcpkg\installed\x64-windows\include\skia\`.

### Describe alternatives you've considered

Including skia header files like this
```
#include <core/SkSurface.h>
```

which makes it hard to understand to which library the included file belongs to.

**Comment by xiaozhuai** [comment]
This problem was once reported by #28591. But it was not accepted.
I vote for this change, again.
