### ISSUE TITLE
[libepoxy] build failure

### ISSUE THREAD

**Issue by yanxiang-wang** [microsoft/vcpkg#32651]
### Operating system

Ubuntu 22.04

### Compiler

GCC

### Steps to reproduce the behavior

```Shell
find_package(libepoxy CONFIG REQUIRED)
```

### Failure logs

Could not find a package configuration file provided by "libepoxy" with any of the following name:
```
libepoxyConfig.cmake
libepoxy-config.cmake
```

### Additional context

What is the correct way to specify library names in `Cmake` files?
E.g. `sdl2` or `SDL2`，`libepoxy` or `epoxy`?

**Comment by yanxiang-wang** [comment]
Also, there is no hint on how to include it in `CmakeLists.txt` when installing this library.

**Comment by MonicaLiu0311** [comment]
You cannot use `find_package`, because the upstream does not provide a CMake configuration files, you can only use the cmake basic search method:
```
find_path(TEST_INCLUDE_PATH "epoxy/" REQUIRED)
find_library(TEST_LIBRARY_PATH NAMES epoxy REQUIRED) 
target_include_directories(main PRIVATE ${TEST_INCLUDE_PATH})
target_link_libraries(main PRIVATE ${TEST_LIBRARY_PATH})
```

> Also, there is no hint on how to include it in `CmakeLists.txt` when installing this library.

When the upstream does not provide a CMake configuration file, we generally do not provide usage.

**Comment by MonicaLiu0311** [comment]
If you have no other questions, please close the issue.
