### ISSUE TITLE
Create a batch file pull_upstream.cmd to merge microsoft's repo into own's fork

### ISSUE THREAD

**Issue by pgrison** [microsoft/vcpkg#3266]
For contributers, since you have to work from a fork, i propose to introduce a .cmd:
'
@echo off
git pull
git checkout master
git pull https://github.com/Microsoft/vcpkg.git
rem git commit
rem git push origin master
`

Does it makes sense for many of you ?

**Comment by jasjuang** [comment]
Are you sure this will work? When I do it I have to do it this way

```
git remote add upstream https://github.com/Microsoft/vcpkg
git fetch upstream
git checkout whateverlocalbranchinmyfork
git merge upstream/master
```

**Comment by pgrison** [comment]
The first one assume only a local master branch while the second one allows to work on a specific local branch. Depends on the initial choice to work on your personal fork master or not i would say.
(perhaps i'm wrong)

https://help.github.com/articles/syncing-a-fork/
https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/
https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen this issue.
