### ISSUE TITLE
[openssl] Build error windows use mingw64

### ISSUE THREAD

**Issue by a980374208** [microsoft/vcpkg#32668]
vcpkg install openssl --triplet=x64-mingw-dynamic
Computing installation plan...
The following packages will be built and installed:
    openssl:x64-mingw-dynamic -> 3.1.1#1
Detecting compiler hash for triplet x64-mingw-dynamic...
Restored 0 package(s) from C:\Users\bin\AppData\Local\vcpkg\archives in 178 us. Use --debug to see more details.
Installing 1/1 openssl:x64-mingw-dynamic...
Building openssl:x64-mingw-dynamic...
warning: -- Using community triplet x64-mingw-dynamic. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: D:\softWare\vcpkg-master\triplets\community\x64-mingw-dynamic.cmake
-- Using cached openssl-openssl-openssl-3.1.1.tar.gz.
-- Cleaning sources at D:/softWare/vcpkg-master/buildtrees/openssl/src/nssl-3.1.1-53a8e40f57.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/softWare/vcpkg-master/downloads/openssl-openssl-openssl-3.1.1.tar.gz
-- Applying patch disable-apps.patch
-- Applying patch disable-install-docs.patch
-- Applying patch script-prefix.patch
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch unix/android-cc.patch
-- Applying patch unix/move-openssldir.patch
-- Applying patch unix/no-empty-dirs.patch
-- Applying patch unix/no-static-libs-for-shared.patch
-- Using source at D:/softWare/vcpkg-master/buildtrees/openssl/src/nssl-3.1.1-53a8e40f57.clean
-- Using cached msys2-make-4.4.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-perl-5.36.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-bash-5.2.015-1-x86_64.pkg.tar.zst.
-- Using cached msys2-coreutils-8.32-5-x86_64.pkg.tar.zst.
-- Using cached msys2-file-5.44-5-x86_64.pkg.tar.zst.
-- Using cached msys2-gawk-5.2.1-2-x86_64.pkg.tar.zst.
-- Using cached msys2-grep-1~3.0-6-x86_64.pkg.tar.zst.
-- Using cached msys2-gzip-1.12-2-x86_64.pkg.tar.zst.
-- Using cached msys2-diffutils-3.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-pkgconf-1.9.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-sed-4.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libintl-0.21-2-x86_64.pkg.tar.zst.
-- Using cached msys2-libcrypt-2.1-4-x86_64.pkg.tar.zst.
-- Using cached msys2-libiconv-1.17-1-x86_64.pkg.tar.zst.
-- Using cached msys2-gmp-6.2.1-2-x86_64.pkg.tar.zst.
-- Using cached msys2-gcc-libs-11.3.0-3-x86_64.pkg.tar.zst.
-- Using cached msys2-libbz2-1.0.8-4-x86_64.pkg.tar.zst.
-- Using cached msys2-liblzma-5.4.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libzstd-1.5.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-zlib-1.2.13-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libreadline-8.2.001-3-x86_64.pkg.tar.zst.
-- Using cached msys2-mpfr-4.2.0-2-x86_64.pkg.tar.zst.
-- Using cached msys2-libpcre-8.45-3-x86_64.pkg.tar.zst.
-- Using cached msys2-ncurses-6.4-1-x86_64.pkg.tar.zst.
-- Using msys root at D:/softWare/vcpkg-master/downloads/tools/msys2/7695e693b092e6c7
-- Getting CMake variables for x64-mingw-dynamic
-- Getting CMake variables for x64-mingw-dynamic
-- Using cached msys2-autoconf-wrapper-20221207-1-any.pkg.tar.zst.
-- Using cached msys2-automake-wrapper-20221207-1-any.pkg.tar.zst.
-- Using cached msys2-binutils-2.40-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libtool-2.4.7-3-x86_64.pkg.tar.zst.
-- Using cached msys2-make-4.4.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-pkgconf-1.9.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-which-2.21-4-x86_64.pkg.tar.zst.
-- Using cached msys2-bash-5.2.015-1-x86_64.pkg.tar.zst.
-- Using cached msys2-coreutils-8.32-5-x86_64.pkg.tar.zst.
-- Using cached msys2-file-5.44-5-x86_64.pkg.tar.zst.
-- Using cached msys2-gawk-5.2.1-2-x86_64.pkg.tar.zst.
-- Using cached msys2-grep-1~3.0-6-x86_64.pkg.tar.zst.
-- Using cached msys2-gzip-1.12-2-x86_64.pkg.tar.zst.
-- Using cached msys2-diffutils-3.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-sed-4.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using cached msys2-autoconf2.71-2.71-1-any.pkg.tar.zst.
-- Using cached msys2-automake1.16-1.16.5-1-any.pkg.tar.zst.
-- Using cached msys2-libiconv-1.17-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libintl-0.21-2-x86_64.pkg.tar.zst.
-- Using cached msys2-zlib-1.2.13-1-x86_64.pkg.tar.zst.
-- Using cached msys2-tar-1.34-3-x86_64.pkg.tar.zst.
-- Using cached msys2-findutils-4.9.0-3-x86_64.pkg.tar.zst.
-- Using cached msys2-gmp-6.2.1-2-x86_64.pkg.tar.zst.
-- Using cached msys2-gcc-libs-11.3.0-3-x86_64.pkg.tar.zst.
-- Using cached msys2-libbz2-1.0.8-4-x86_64.pkg.tar.zst.
-- Using cached msys2-liblzma-5.4.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libzstd-1.5.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libreadline-8.2.001-3-x86_64.pkg.tar.zst.
-- Using cached msys2-mpfr-4.2.0-2-x86_64.pkg.tar.zst.
-- Using cached msys2-libpcre-8.45-3-x86_64.pkg.tar.zst.
-- Using cached msys2-m4-1.4.19-2-x86_64.pkg.tar.zst.
-- Using cached msys2-perl-5.36.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-ncurses-6.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libcrypt-2.1-4-x86_64.pkg.tar.zst.
-- Using msys root at D:/softWare/vcpkg-master/downloads/tools/msys2/d7266db249278763
-- Using cached mingw-w64-i686-pkgconf-1~1.8.0-2-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using msys root at D:/softWare/vcpkg-master/downloads/tools/msys2/6f3fa1a12ef85a6f
-- Configuring x64-mingw-dynamic-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: D:/softWare/vcpkg-master/downloads/tools/msys2/d7266db249278763/usr/bin/bash.exe --noprofile --norc --debug -c "V=1 CPP='gcc.exe -E' CC='gcc.exe' CC_FOR_BUILD='gcc.exe' CPP_FOR_BUILD='gcc.exe -E' CXX_FOR_BUILD='c++.exe' CXX='c++.exe' RC='windres.exe' WINDRES='windres.exe' AR='ar.exe' LD='ld.exe -verbose' RANLIB='ranlib.exe' OBJDUMP='objdump.exe' STRIP='strip.exe' NM='nm.exe' DLLTOOL='dlltool.exe' CCAS=':' AS=':' ./../src/nssl-3.1.1-53a8e40f57.clean/vcpkg/configure --build=x86_64-pc-mingw32 \"D:/softWare/vcpkg-master/downloads/tools/msys2/7695e693b092e6c7/usr/bin/perl.exe\" \"D:/softWare/vcpkg-master/buildtrees/openssl/src/nssl-3.1.1-53a8e40f57.clean/Configure\" \"mingw64\" \"enable-static-engine\" \"enable-capieng\" \"no-ssl3\" \"no-weak-ssl-ciphers\" \"no-tests\" \"shared\" \"no-apps\" \"--openssldir=/etc/ssl\" \"--libdir=lib\" \"gl_cv_double_slash_root=yes\" \"ac_cv_func_memmove=yes\" \"--disable-silent-rules\" \"--verbose\" \"--enable-shared\" \"--disable-static\" \"--debug\" \"--prefix=/D/softWare/vcpkg-master/installed/x64-mingw-dynamic/debug\""
    Working Directory: D:/softWare/vcpkg-master/buildtrees/openssl/x64-mingw-dynamic-dbg
    Error code: 127
    See logs for more information:
      D:\softWare\vcpkg-master\buildtrees\openssl\config-x64-mingw-dynamic-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:833 (vcpkg_execute_required_process)
  ports/openssl/unix/portfile.cmake:104 (vcpkg_configure_make)
  ports/openssl/portfile.cmake:71 (include)
  scripts/ports.cmake:147 (include)

error: building openssl:x64-mingw-dynamic failed with: BUILD_FAILED
Elapsed time to handle openssl:x64-mingw-dynamic: 10 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[openssl]+Build+error&body=Copy+issue+body+from+D%3A%2FsoftWare%2Fvcpkg-master%2Finstalled%2Fvcpkg%2Fissue_body.md

+ D:/softWare/vcpkg-master/downloads/tools/msys2/7695e693b092e6c7/usr/bin/perl.exe D:/softWare/vcpkg-master/buildtrees/openssl/src/nssl-3.1.1-53a8e40f57.clean/Configure mingw64 enable-static-engine enable-capieng no-ssl3 no-weak-ssl-ciphers no-tests shared no-apps --openssldir=D:/softWare/vcpkg-master/downloads/tools/msys2/d7266db249278763/etc/ssl --libdir=lib --debug --prefix=D:/softWare/vcpkg-master/installed/x64-mingw-dynamic/debug
./../src/nssl-3.1.1-53a8e40f57.clean/vcpkg/configure: line 31: D:/softWare/vcpkg-master/downloads/tools/msys2/7695e693b092e6c7/usr/bin/perl.exe: No such file or directory

[config-x64-mingw-dynamic-dbg-err.log](https://github.com/microsoft/vcpkg/files/12111594/config-x64-mingw-dynamic-dbg-err.log)

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
