### ISSUE TITLE
[New Port Request] libfins

### ISSUE THREAD

**Issue by BA7LYA** [microsoft/vcpkg#32667]
### Library name

libfins

### Library description

Libfins is a multi platform library with routines to communicate with Omron PLCs over the FINS protocol.

### Source repository URL

https://github.com/lammertb/libfins.git

### Project homepage (if different from the source repository)

https://www.libfins.org

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

Libfins is a multi platform library with routines to communicate with Omron PLCs over the FINS protocol. FINS is an inter-PLC protocol which allows hardware layer independent exchange of data between PLCs. Omron PLCs support the exchange of data over serial lines, TCP, UDP and bus systems. This library currently implements the FINS/TCP communication.

FINS is a client server protocol where a client sends requests to a remote server and processes their answer. The libfins library contains almost all of the publically documented functionality. The only functionality currently missing is using a PLC as gateway to execute Compoway/F and Modbus commands over SCU serial units. These features will be implemented and tested in the near future though.

The libfins library is licensed with the MIT license. This should give maximum flexibility when using the library in both open en closed source applications.

**Comment by endingly** [comment]
- [ ] add cmak support (ing)
       https://github.com/lammertb/libfins/pull/19
- [ ] add vcpkg port

**Comment by endingly** [comment]
no uwp, no osx and no android 🤣

**Comment by lammertb** [comment]
> 

Given that the FINS communication is running in the background without a user interface and only needs a network connection, what would be the challenges to add uwp, osx and android support?

**Comment by BA7LYA** [comment]
@lammertb What a surprise, glad to meet you :)

**Comment by dg0yt** [comment]
@lammertb You may get CI failure logs here: https://dev.azure.com/vcpkg/public/_build/results?buildId=92230&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by endingly** [comment]
I am observing these logs.

**Comment by endingly** [comment]
@lammertb The error occurs on the following platforms: 
* x64-osx
* x64-uwp
* arm-uwp
* arm-neon-android
* arm64-android

But there are only three reasons: 
1. Compile Error (`x64-osx`)
   
   The compilation log is as follows
     ```
     FAILED: CMakeFiles/fins.dir/src/fins_utils.c.o /Library/Developer/CommandLineTools/usr/bin/cc  -I/Users/vagrant/Data/buildtrees/fins/src/f27ee7c714-84fae67962.clean/include -fPIC -g -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -Wall -Wstrict-prototypes -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wwrite-strings -Wnested-externs -Wredundant-decls -Werror -funsigned-char -MD -MT CMakeFiles/fins.dir/src/fins_utils.c.o -MF CMakeFiles/fins.dir/src/fins_utils.c.o.d -o CMakeFiles/fins.dir/src/fins_utils.c.o -c /Users/vagrant/Data/buildtrees/fins/src/f27ee7c714-84fae67962.clean/src/fins_utils.c
     /Users/vagrant/Data/buildtrees/fins/src/f27ee7c714-84fae67962.clean/src/fins_utils.c:522:2: error: implicit declaration of function 'usleep' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        usleep( 1000 * msec );
        ^
        1 error generated.
     ```
     Accroding to [Stackoverflow issue](https://stackoverflow.com/questions/29370813/implicit-declaration-of-function-usleep), we can use `-std=gnu99` instead of `-std=c99` to resolve the problem.

2. Compile Error (`x64-uwp`/`arm-uwp`)
   
   The following is an excerpt from the compilation log
    ```
    [1/68] C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1436~1.325\bin\Hostx64\arm\cl.exe    -ID:\buildtrees\fins\src\f27ee7c714-84fae67962.clean\include /DWIN32 /D_WINDOWS /D_UNICODE /DUNICODE /DWINAPI_FAMILY=WINAPI_FAMILY_APP /D__WRL_NO_DEFAULT_LIB__ /nologo /Z7 /MP /GS /Gd /Gm- /W3 /WX- /Zc:wchar_t /Zc:inline /Zc:forScope /fp:precise /Oy- /EHsc  /utf-8  /D_DEBUG /MDd /Od /RTC1  -MDd -Ot -GT -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 -volatile:iso -nologo -J -sdl -Wall -WX -wd4464 -wd4668 -wd4710 -wd4711 -wd4201 -wd4820 -Wv:18 /showIncludes /FoCMakeFiles\fins.dir\src\fins_04_02.c.obj /FdCMakeFiles\fins.dir\fins.pdb /FS -c D:\buildtrees\fins\src\f27ee7c714-84fae67962.clean\src\fins_04_02.c
    FAILED: CMakeFiles/fins.dir/src/fins_04_02.c.obj 
    C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1436~1.325\bin\Hostx64\arm\cl.exe    -ID:\buildtrees\fins\src\f27ee7c714-84fae67962.clean\include /DWIN32 /D_WINDOWS /D_UNICODE /DUNICODE /DWINAPI_FAMILY=WINAPI_FAMILY_APP /D__WRL_NO_DEFAULT_LIB__ /nologo /Z7 /MP /GS /Gd /Gm- /W3 /WX- /Zc:wchar_t /Zc:inline /Zc:forScope /fp:precise /Oy- /EHsc  /utf-8  /D_DEBUG /MDd /Od /RTC1  -MDd -Ot -GT -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 -volatile:iso -nologo -J -sdl -Wall -WX -wd4464 -wd4668 -wd4710 -wd4711 -wd4201 -wd4820 -Wv:18 /showIncludes /FoCMakeFiles\fins.dir\src\fins_04_02.c.obj /FdCMakeFiles\fins.dir\fins.pdb /FS -c D:\buildtrees\fins\src\f27ee7c714-84fae67962.clean\src\fins_04_02.c
    cl : Command line warning D9025 : overriding '/WX-' with '/WX'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\ws2def.h(360): error C2061: syntax error: identifier 'SOCKADDR_STORAGE'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\ws2def.h(360): error C2059: syntax error: ';'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\ws2def.h(361): error C2143: syntax error: missing '{' before '*'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\ws2def.h(361): warning C4431: missing type specifier - int assumed. Note: C no longer supports default-int
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\ws2def.h(361): warning C4431: missing type specifier - int assumed. Note: C no longer supports default-int
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\ws2def.h(361): warning C4218: nonstandard extension used: must specify at least a storage class or a type
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\ws2ipdef.h(845): error C2061: syntax error: identifier 'SOCKADDR_STORAGE'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\ws2ipdef.h(846): error C2059: syntax error: '}'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\ws2ipdef.h(854): error C2061: syntax error: identifier 'SOCKADDR_STORAGE'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\ws2ipdef.h(855): error C2061: syntax error: identifier 'gsr_source'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\ws2ipdef.h(855): error C2059: syntax error: ';'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\ws2ipdef.h(856): error C2059: syntax error: '}'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\ws2ipdef.h(864): error C2061: syntax error: identifier 'SOCKADDR_STORAGE'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\ws2ipdef.h(867): error C2061: syntax error: identifier 'gf_slist'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\ws2ipdef.h(867): error C2059: syntax error: ';'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\ws2ipdef.h(867): error C2059: syntax error: '['
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared\ws2ipdef.h(868): error C2059: syntax error: '}'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\ws2tcpip.h(832): warning C4431: missing type specifier - int assumed. Note: C no longer supports default-int
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\ws2tcpip.h(832): error C2143: syntax error: missing ')' before '*'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\ws2tcpip.h(832): error C2143: syntax error: missing '{' before '*'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\ws2tcpip.h(833): error C2059: syntax error: ')'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\ws2tcpip.h(834): warning C4431: missing type specifier - int assumed. Note: C no longer supports default-int
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\ws2tcpip.h(834): error C2054: expected '(' to follow 'SourceList'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\ws2tcpip.h(880): error C2143: syntax error: missing ')' before '*'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\ws2tcpip.h(880): error C2081: 'SOCKADDR_STORAGE': name in formal parameter list illegal
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\ws2tcpip.h(880): error C2143: syntax error: missing '{' before '*'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\ws2tcpip.h(881): error C2059: syntax error: ')'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\ws2tcpip.h(882): warning C4431: missing type specifier - int assumed. Note: C no longer supports default-int
    C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\ws2tcpip.h(882): error C2054: expected '(' to follow 'SourceList'
    ```
    At present, I don't have time to solve this problem, but the initial guess may be that the macro definition and the system header file have collided.

3. CI host network problem
   
   The following is an excerpt from the compilation log

   ```
   # arm-neon-andorid

   ERROR: The command failed with an unexpected error. Here is the traceback:
   ERROR: HTTPSConnectionPool(host='andcontainerregistry.azurecr.io', port=443): Max retries exceeded with url: /oauth2/exchange (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8ec176bd60>: Failed to establish a new connection: [Errno 111] Connection refused'))
   Traceback (most recent call last):
   File "/opt/az/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn 
        conn = connection.create_connection
   File "/opt/az/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection 
        raise err
   File "/opt/az/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection 
        sock.connect(sa)
   ConnectionRefusedError: [Errno 111] Connection refused
   ```
   ```
   # arm64-andorid

   WARNING: Uppercase characters are detected in the registry name. When using its server url in docker commands, to avoid authentication errors, use all lowercase.
   WARNING: Error response from daemon: Get "https://andcontainerregistry.azurecr.io/v2/": dial tcp 20.187.196.99:443: connect: connection refused
   ERROR: Login failed.
   ```

**Comment by dg0yt** [comment]
> * Accroding to [Stackoverflow issue](https://stackoverflow.com/questions/29370813/implicit-declaration-of-function-usleep), we can use `-std=gnu99` instead of `-std=c99` to resolve the problem.

Given Apple clang, I wouldn't bet on gnu99. But there is the mention of `_XOPEN_SOURCE`.


> 3\. CI host network problem

The android build seems to be scripted in a different way.
All network access should be in the portfile via maintainer functions (implying proper asset caching), and dependencies should be acquired via vcpkg.

**Comment by lammertb** [comment]
Better to fix the problem where it occurs and not playing around with compiler settings until compilation accidentally succeeds.

The compiler stops at the usleep() call because the proper include file is not loaded. I have now included <unistd.h> for OS-X compilation. That should fix the usleep issue. I have no OS-X system to test it, so maybe the macro __OSX__ is not the right one but if another macro is needed, it is pretty easy to fix.

**Comment by lammertb** [comment]
Regarding the x63-uwp /arm-uwp compiler problem, I have a VS2022 envirnonment available here. Will spend some a few spare hours on it today to try to trace the problem and fix it.

**Comment by lammertb** [comment]
The uwp compilation issue is not unique to this library, looking at https://github.com/godotengine/godot/issues/16830 
Currently scanning that issue to find a solution.

**Comment by lammertb** [comment]
Removed the macro definition upstream https://github.com/lammertb/libfins/commit/03a9afaf5bff1134dd0b8da729a2cbf62b4908c3

**Comment by lammertb** [comment]
Had a few happy hours with Visual Studio hacking the code to get it smoothly running without a single issue for 32 and 64 bit targets.

- Added a Visual Studio 2022 project file to the repository.
- Suppression of non-maskable warnings is now done with compiler pragmas in the source
- Code compiles for Debug and Release for x86 and x64 without warning with warning setting -Wall
- All warning suppression options in the CMake file have been deleted
- Reduced warning level to -W3 for the CMake and VS Release builds
- Debug mode in the Visual Studio project is still -Wall to catch problems while developing
- Removed the "treat warning as errors" flag for CMake to let it happily compile in slightly different environments

**Comment by lammertb** [comment]
The code compiles now without warnings on
- Windows x86 and x64
- Ubuntu 20.04 and 22.04
- MacOS 11,12 and 13
- Android ARM, ARM64, x86 and x64.

MacOS and Android builds use MS-build as I don't have enough knowledge of CMake yet to add cross-platform compilation.

MS-Build configurations and YAML files are all included in the repository and CI Github Actions for all platforms have been set up.

**Comment by dg0yt** [comment]
@lammertb It would be good to add a CMake setup to your CI. It can generate msbuild files, and it supports multiple platforms and and cross builds. For vcpkg, it is better to use the same build system for all platforms, to ensure the same set of artifacts.

**Comment by endingly** [comment]
@lammertb Today, I directly incorporated the current cmake project into the CI workflow and found that it can compile normally. Previous compilation errors may have been caused by compilation flags. In other words, perhaps we don't need to add Msbuild. I'm very sorry for wasting your valuable time. 🥺

Perhaps we can delete the msbuild file sometime.

![image](https://github.com/microsoft/vcpkg/assets/38353844/c7e14f1b-bfa8-43dd-844c-0403d11fda3d)

**Comment by BA7LYA** [comment]
PR #32795 is merged, nice work, thanks you all.
