### ISSUE TITLE
vcpkg install cppzmq does not include CMake files for find_package

### ISSUE THREAD

**Issue by michael-hart** [Microsoft/vcpkg#3267]
Files that ought to be in <vcpkg>/installed/<install_type>/share/cppzmq do not exist, so find_package(cppzmq REQUIRED) causes the build to fail.

**Comment by PhoebeHui** [comment]
@michael-hart, please try it with latest vcpkg revision, currently cppzmqConfig.cmake put to .\VCPKG\src\installed\x86-windows\share\cppzmq\ after it installed.
