### ISSUE TITLE
[rocksdb] Link errors on x64-windows

### ISSUE THREAD

**Issue by cbrl** [microsoft/vcpkg#32675]
**Describe the bug**
As of 4c397835c472e1a49b47ca5172c71fa56e497796, `rocksdb` no longer exports the `RocksDB::rocksdb` target on `x64-windows`, instead exporting the `RocksDB::rocksdb-shared` target. The problem with the shared library is that it only seems to expose the C API, causing linker errors if you use the C++ API.

**Environment**
- OS: Windows
- Compiler: MSVC 19.37.32820.0 (Visual Studio 17.7.0 Preview 4.0)

**To Reproduce**
1. ./vcpkg install rocksdb:x64-windows
2. Compile any program that uses the RocksDB C++ API

**Expected behavior**
The project compiles without linker errors.

**Failure logs**
```
[main] Building folder: test 
[build] Starting build
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --build d:/test/build --config Debug --target ALL_BUILD -j 18 --
[build] MSBuild version 17.7.1+971bf70db for .NET Framework
[build] 
[build]   Checking Build System
[build]   Building Custom Rule D:/test/CMakeLists.txt
[build]   main.cpp
[build] main.obj : error LNK2019: unresolved external symbol "public: __cdecl rocksdb::ColumnFamilyOptions::ColumnFamilyOptions(void)" (??0ColumnFamilyOptions@rocksdb@@QEAA@XZ) referenced in function "public: __cdecl rocksdb::Options::Options(void)" (??0Options@rocksdb@@QEAA@XZ) [D:\test\build\test.vcxproj]
[build] main.obj : error LNK2019: unresolved external symbol "public: __cdecl rocksdb::DBOptions::DBOptions(void)" (??0DBOptions@rocksdb@@QEAA@XZ) referenced in function "public: __cdecl rocksdb::Options::Options(void)" (??0Options@rocksdb@@QEAA@XZ) [D:\test\build\test.vcxproj]
[build] main.obj : error LNK2019: unresolved external symbol "public: static class rocksdb::Status __cdecl rocksdb::DB::Open(struct rocksdb::Options const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class rocksdb::DB * *)" (?Open@DB@rocksdb@@SA?AVStatus@2@AEBUOptions@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAPEAV12@@Z) referenced in function main [D:\test\build\test.vcxproj]
[build] D:\test\build\Debug\test.exe : fatal error LNK1120: 3 unresolved externals [D:\test\build\test.vcxproj]
[proc] The command: "C:\Program Files\CMake\bin\cmake.EXE" --build d:/test/build --config Debug --target ALL_BUILD -j 18 -- exited with code: 1
[driver] Build completed: 00:00:01.148
[build] Build finished with exit code 1
```

**Additional context**
The error log above comes from the following test program. Changing `builtin-baseline` to `f6a5d4e8eb7476b8d7fc12a56dff300c1c986131` (2023.06.20 release) and linking `RocksDB::rocksdb` instead of `RocksDB::rocksdb-shared` will make the project compile without error.

**CMakeLists.txt:**
```CMake
set(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake")

cmake_minimum_required(VERSION 3.12)
project(test)

find_package(RocksDB CONFIG REQUIRED)

add_executable(test main.cpp)
target_compile_features(test PRIVATE cxx_std_17)
target_link_libraries(test PRIVATE RocksDB::rocksdb-shared)
```

**main.cpp**
```cpp
#include <rocksdb/db.h>

int main() {
	rocksdb::DB* db;
	rocksdb::DB::Open(rocksdb::Options{}, "./database", &db);
}
```

**vcpkg.json**
```json
{
	"name": "test",
	"version-semver": "0.1.0",
	"dependencies": [
		"rocksdb"
	],
	"builtin-baseline": "4c397835c472e1a49b47ca5172c71fa56e497796"
}
```

**Comment by Cheney-W** [comment]
This issue could be reproduced with the latest vcpkg 2023-06-22-f19f3d9939100085fe2f7e41502d60b08e2083b6.

**Comment by yurybura** [comment]
@cbrl @Cheney-W 
Support for RocksDB shared libraries was introduced in https://github.com/microsoft/vcpkg/commit/4c397835c472e1a49b47ca5172c71fa56e497796. Prior to this change, static library export was forced for all triplets. The RocksDB port now matches the value defined by the `VCPKG_LIBRARY_LINKAGE` variable.

The target `RocksDB::rocksdb` is still exported on `x64-windows-static`. You can use `x64-windows-static` if you need a static library.

VCPKG supports per-port customization if you need to mix different communication types for ports: https://learn.microsoft.com/en-us/vcpkg/users/triplets#per-port-customization.

**Comment by cbrl** [comment]
I would normally agree that it makes sense to export the shared library in this case, but the shared library doesn't expose the main interface to RocksDB. I would almost say it's a different library at that point, like `msgpack` vs `msgpack-c`. This could probably be considered a defect with RocksDB itself though.

In any case, if this is the desired behavior, it might be helpful to add a note in the usage file that mentions how most users will need to override the linkage setting in order to use the library.

**Comment by reder2000** [comment]
Even though, the library name has changed to RockSD-shared, which should not be needed and brings in complication.
.

**Comment by cbrl** [comment]
The library name `rocksdb-shared` is set by the RocksDB project itself. It is a needless complication, but it's actually the correct name for vcpkg to use.

The main issue is that the shared library doesn't seem usable for most people. Vcpkg used to only compile the static library because of this (discussed in #2411 and implemented in #7452). It's very unexpected to be required to override linkage settings in order to use the main API of a port.

Depending on the official stance for this issue, I think the behavior should either be reverted, or a notice should be added to the usage file that warns users about this.

**Comment by dg0yt** [comment]
Which library name implements the C++ API for static linkage?

**Comment by cbrl** [comment]
> Which library name implements the C++ API for static linkage?

`rocksdb` is the name of the library when using static linkage [^1]. Technically the C++ API exists in the shared library as well, but the shared library only exports a C API implemented in terms of the C++ API, almost as if it were a separate project entirely.

[^1]: https://github.com/facebook/rocksdb/blob/4fa2c017190a99a9ad44562b12aeef6f6d2a1d16/CMakeLists.txt#L1036
