### ISSUE TITLE
[libguarded] update to 1.4.1

### ISSUE THREAD

**Issue by Kicer86** [microsoft/vcpkg#32672]
### Library name

libguarded 

### New version number

1.4.1

**Comment by xiaozhuai** [comment]
It looks like the official library name is now `CsLibGuarded`, in vcpkg it's `libguarded `. Should we change it? @jimwang118 @FrankXie05

**Comment by FrankXie05** [comment]
@xiaozhuai 
For the `Header-only` port without dependencies, I think it should be consistent with the upstream.
BTW, the `homepage` of your PR does not seem to be correct. Shuold be `copperspice/cs_libguarded`. :)
```
"homepage": "https://github.com/copperspice/libguarded",
```
