### ISSUE TITLE
path too long

### ISSUE THREAD

**Issue by wjiangsheng** [microsoft/vcpkg#32684]
**Describe the bug**

**Environment**
- Windows

**To Reproduce**
1. ./vcpkg install qt
2. See error：
Installing 1/4 qtwebengine:x64-windows...
Building qtwebengine[core,default-features,geolocation,spellchecker,webchannel]:x64-windows...
-- Setting up python virtual environmnent...
-- Installing python packages: html5lib
-- Setting up python virtual environmnent...finished.
CMake Warning at ports/qtwebengine/portfile.cmake:83 (message):
  Buildtree path 'C:/src/vcpkg/buildtrees/qtwebengine' is too long.

  Consider passing --x-buildtrees-root=<shortpath> to vcpkg!

  Trying to use 'C:/src/vcpkg/buildtrees/qtwebengine/../tmp'
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)

CMake Error at ports/qtwebengine/portfile.cmake:88 (message):
  Buildtree path is too long.  Build will fail! Pass
  --x-buildtrees-root=<shortpath> to vcpkg!
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)

error: building qtwebengine:x64-windows failed with: BUILD_FAILED
Elapsed time to handle qtwebengine:x64-windows: 3.7 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qtwebengine
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[qtwebengine]+Build+error&body=Copy+issue+body+from+C%3A%2Fsrc%2Fvcpkg%2Finst

**Comment by wjiangsheng** [comment]
> ，当您使用较短的 vcpkg 路径时，此问题是否仍然存在？例如：使用代替`C:\vcpkg``C:\src\vcpkg`

Sure, no problem anymore.

**Comment by bzisl** [comment]
I have the same problem, but moving vcpkg to c:\ doesn't solve it

**Comment by JonLiu1993** [comment]
> I have the same problem, but moving vcpkg to c:\ doesn't solve it

Please provide your error log.

**Comment by SchaichAlonso** [comment]
`c:\x` should do the trick.

You can also attempt enabling long path support on your system and then removing [the line aborting the build](https://github.com/microsoft/vcpkg/blob/16eeb024de901eb84cde966f656027beaad8b450/ports/qtwebengine/portfile.cmake#L88C10-L88C10) from the the vcpkg port and giving it a try. When I tried it the last time it failed though as something in the build toolchain failed to generate / extract a file properly even if the filesystem would have supported it.

**Comment by JonLiu1993** [comment]
@wjiansheng, does this problem still exist?

**Comment by bzisl** [comment]
Still exists. I'm downloading latest version every day, and it is exists. When I remove the long path check to follow the compilation, it fails also. It is weird, because it is supposed that QT is compiling their code in a similar way, isn't it?

**Comment by dg0yt** [comment]
From the initial message:

> Consider passing --x-buildtrees-root= to vcpkg!

Did anyone try that proposal...

**Comment by JonLiu1993** [comment]
@wjiangsheng, could you please try @dg0yt's suggesstion?

**Comment by JonLiu1993** [comment]
Ping @wjiangsheng for response.

**Comment by JonLiu1993** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by xahon** [comment]
Buildtree path 'E:/vc/buildtrees/qtwebengine' is too long.

**Comment by xahon** [comment]
What kind of issue does this warning warns of? Some CI can't handle paths more than 22 characters long seems like a problem with this CI itself rather than a problem for a lot of users to bother with renaming/moving vcpkg installation, updating environment variables and removing vcpkg/downloads folder (because it caches scripts with old vcpkg path). For me, it seems like a local issue being resolved with a hack in product core that affects a lot of users and makes a bad feeling about vcpkg product in general. Keeping in mind that this limitation exists is not good, I probably will forgot how to install a package in a half-year if won't use vcpkg on daily basis

**Comment by sfhacker** [comment]
We are getting nowhere!
