### ISSUE TITLE
[skia] Using the package produces lots of CMake warnings

### ISSUE THREAD

**Issue by ulfllorenz** [microsoft/vcpkg#32691]
### Is your feature request related to a problem? Please describe.

When using the skia package via find_package (Windows, x64), I get lots of warnings of the form

CMake Warning at <vcpkg_install>/share/unofficial-skia/unofficial-skia-config.cmake:14 (message):
Omitting 'User32.lib' from link libraries.

On inspection, it turns out that unofficial-skia-config.cmake has a line of the form

    z_vcpkg_skia_get_link_libraries(
        z_vcpkg_skia_link_libs_release
        "${z_vcpkg_skia_root}/lib;${z_vcpkg_skia_root}/debug/lib"
        "turbojpeg.lib;jpeg.lib;harfbuzz-subset.lib;harfbuzz.lib;freetype.lib;bz2.lib;brotlidec.lib;brotlicommon.lib;libpng16.lib;zlib.lib;libwebpdecoder.lib;libwebpdemux.lib;libwebpmux.lib;libwebp.lib;libsharpyuv.lib;libexpat.lib;OpenGL32.lib;Ole32.lib;OleAut32.lib;FontSub.lib;User32.lib;Usp10.lib;Gdi32.lib"
    )

Of particular interest here are the last entries in the list of libraries, which are standard Windows libraries. These cause the warnings. It seems as if this library list is filled at installation by the list of library dependencies of skia. Everything is fine so far, except that these libraries are, of course, not found in the standard CMake paths.

### Proposed solution

Various. You could try to filter out standard libraries during the packaging in get_link_libs(). Or you could search in the config.cmake also for standard system include files.

### Additional context

It might be relevant that we relocate our vcpkg install folder during our build (essentially the build system builds all vcpkg packages and uploads the installation dir, others download this bundle), although I doubt that this problem is caused by the relocation.

**Comment by MonicaLiu0311** [comment]
@ulfllorenz 
Fixing by #33254. I filter the system library in the following way, but if a new system library is added and the code needs to be modified repeatedly, do you have a better suggestion?
```
        # Filter out standard system libraries
        if(NOT lib MATCHES "^(User32|OpenGL32|Ole32|OleAut32|FontSub|Usp10|Gdi32)[.]lib$")
            vcpkg_list(APPEND output "${lib}")
        endif()
```

**Comment by ulfllorenz** [comment]
You could put this code inside a function like "remove_system_libraries" in skia-functions.cmake, then the code flow is a bit more explicit. The solution is a bit of a hack, but then again the problem is not pretty to start with.

A better alternative would be to look at the full paths and exclude those in the Windows/System* directories, but as far as I can see, you get the list of libraries from get_link_libs() and this function probably already lacks the required information.

**Comment by dg0yt** [comment]
You might use the implicit link libraries information from CMake - this should be the list which is used to create the warning. Note that you would have to do a case-insensitive match on Windows.

**Comment by dg0yt** [comment]
I added a fix to #34951, but I didn't verify the result. Please test.

**Comment by ulfllorenz** [comment]
First, I apologize for the late posting. We had a longer, uhm, internet outage at the company when I finally wanted to test it.

Unfortunately, the fix mitigates the problem, but does not fix it entirely

* Originally, I got warnings for Ole32.lib, OleAut32.lib, FontSub.lib, User32.lib, Usp10.lib, Gdi32.lib
* With the latest 0.38.2#3, I still get warnings for FontSub.lib and Usp10.lib

Formality question: Should this issue be reopened, or should I open another one?

**Comment by dg0yt** [comment]
I suggest reopening.
The fix which was merged isn't so bad, but we actually need another change:  
Accept as-is the libs which can be found in implicit link *directories*.
