### ISSUE TITLE
[mongo-*-driver] Should we rename to libmongo*?

### ISSUE THREAD

**Issue by sdcb** [Microsoft/vcpkg#327]
I created the mongo-c-driver and mongo-cxx-driver, this name is taken from the official github name. 
But now I think maybe we rename it to libmongoc and libmongocxx would be a better idea, since the actual dll/lib file name is like libmongoc-1.0.lib.

@MSFT vcpkg maintainer and @all mongo-* user: 
please put your idea here.

**Comment by ras0219-msft** [comment]
I would first recommend names that will be familiar to users coming from other platforms.
- Archlinux uses "libmongoc": https://www.archlinux.org/packages/community/i686/libmongoc/
- Ubuntu and Debian also use "libmongoc": http://packages.ubuntu.com/yakkety/libmongoc-dev
- Homebrew uses "libmongoclient" for c++ https://github.com/Homebrew/homebrew-core/blob/bd4a5e88436985d05b1e2b5d82b96b02297636ef/Formula/libmongoclient.rb
- Homebrew uses "mongo-c" for the C driver https://github.com/Homebrew/homebrew-core/blob/db352626240aba47b4707443c2eec954f509f532/Formula/mongo-c.rb

So, the current names seem fine, but other good names would be:
- `libmongoc`/`libmongocxx`
- `mongoc`/`mongocxx`
- `mongo-c`/`mongo-cxx`

**Comment by sdcb** [comment]
Current names seem fine, but there is other good names, I see it.
So you suggest rename or not?

**Comment by ras0219-msft** [comment]
I would not suggest a rename.
