### ISSUE TITLE
[New Port Request] <library name here>

### ISSUE THREAD

**Issue by gabrielemucho** [microsoft/vcpkg#32709]
### Library name

vcpkg

### Source repository URL

https://github.com/microsoft/vcpkg

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

I'm trying to train my custom dataset on nerfstudio, but it requires to install COLMAP. I'm using this code for Windows as available from here: https://colmap.github.io/install.html

`git clone https://github.com/microsoft/vcpkg
cd vcpkg
.\bootstrap-vcpkg.bat
.\vcpkg install colmap[cuda,tests]:x64-windows`

But it fails suggesting that there might be new ports. Pls see attached the screenshot of the error that I get on my terminal

<img width="1272" alt="failure to install vcpgk 2023-07-23 131433" src="https://github.com/microsoft/vcpkg/assets/19440557/0b756d76-2841-4cbc-8193-5ad14da21cf0">

**Comment by BA7LYA** [comment]
I think you might could:
1) change your issue's title to "[New Port Request] colmap" and
2) Library name to "colmap" and
3) and something similar that help to deal with this new port.

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
