### ISSUE TITLE
[arm-windows] build failure

### ISSUE THREAD

**Issue by kd-boss** [microsoft/vcpkg#32714]
### Operating system

Windows

### Compiler

MingGW

### Steps to reproduce the behavior

```Shell
./vcpkg --triplet arm-windows install Qt5
```

### Failure logs

Bootstrapping qmake ...
        cl -c -Fo./ -Fdqmake.pdb  -W2 -nologo -O2  /MP /wd4577   -IC:\srcvcpkg\vcpkg\buildtrees\qt5-base\src\5.15.10-6bae14788b.clean\qmake -IC:\srcvcpkg\vcpkg\buildtrees\qt5-base\src\5.15.10-6bae14788b.clean\qmake\library -IC:\srcvcpkg\vcpkg\buildtrees\qt5-base\src\5.15.10-6bae14788b.clean\qmake\generators -IC:\srcvcpkg\vcpkg\buildtrees\qt5-base\src\5.15.10-6bae14788b.clean\qmake\generators\unix -IC:\srcvcpkg\vcpkg\buildtrees\qt5-base\src\5.15.10-6bae14788b.clean\qmake\generators\win32 -IC:\srcvcpkg\vcpkg\buildtrees\qt5-base\src\5.15.10-6bae14788b.clean\qmake\generators\mac  -IC:\srcvcpkg\vcpkg\buildtrees\qt5-base\src\5.15.10-6bae14788b.clean/src/3rdparty/tinycbor/src  -IC:\srcvcpkg\vcpkg\buildtrees\qt5-base\src\5.15.10-6bae14788b.clean/include -IC:\srcvcpkg\vcpkg\buildtrees\qt5-base\src\5.15.10-6bae14788b.clean/include\QtCore -IC:\srcvcpkg\vcpkg\buildtrees\qt5-base\src\5.15.10-6bae14788b.clean/include\QtCore\5.15.10 -IC:\srcvcpkg\vcpkg\buildtrees\qt5-base\src\5.15.10-6bae14788b.clean/include\QtCore\5.15.10\QtCore  -I..\src\corelib\global  -IC:\srcvcpkg\vcpkg\buildtrees\qt5-base\src\5.15.10-6bae14788b.clean\mkspecs\win32-msvc   -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS  -DQT_VERSION_STR=\"5.15.10\" -DQT_VERSION_MAJOR=5 -DQT_VERSION_MINOR=15 -DQT_VERSION_PATCH=10  -DQT_BUILD_QMAKE -DQT_BOOTSTRAPPED -DPROEVALUATOR_FULL  -DQT_NO_FOREACH -DUNICODE -D_ENABLE_EXTENDED_ALIGNED_STORAGE -c -Yc -Fpqmake_pch.pch -TP C:\srcvcpkg\vcpkg\buildtrees\qt5-base\src\5.15.10-6bae14788b.clean\qmake\qmake_pch.h
qmake_pch.h
C:\srcvcpkg\vcpkg\buildtrees\qt5-base\src\5.15.10-6bae14788b.clean\include\QtCore\../../src/corelib/global/qprocessordetection.h(364): fatal error C1189: #error:  "Unable to determine byte order!"

### Additional context

Microsoft (R) Program Maintenance Utility Version 14.36.32537.0
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1077: 'cl -c -Fo./ -Fdqmake.pdb  -W2 -nologo -O2  /MP /wd4577   -IC:\srcvcpkg\vcpkg\buildtrees\qt5-base\src\5.15.10-6bae14788b.clean\qmake -IC:\srcvcpkg\vcpkg\buildtrees\qt5-base\src\5.15.10-6bae14788b.clean\qmake\library -IC:\srcvcpkg\vcpkg\buildtrees\qt5-base\src\5.15.10-6bae14788b.clean\qmake\generators -IC:\srcvcpkg\vcpkg\buildtrees\qt5-base\src\5.15.10-6bae14788b.clean\qmake\generators\unix -IC:\srcvcpkg\vcpkg\buildtrees\qt5-base\src\5.15.10-6bae14788b.clean\qmake\generators\win32 -IC:\srcvcpkg\vcpkg\buildtrees\qt5-base\src\5.15.10-6bae14788b.clean\qmake\generators\mac  -IC:\srcvcpkg\vcpkg\buildtrees\qt5-base\src\5.15.10-6bae14788b.clean/src/3rdparty/tinycbor/src  -IC:\srcvcpkg\vcpkg\buildtrees\qt5-base\src\5.15.10-6bae14788b.clean/include -IC:\srcvcpkg\vcpkg\buildtrees\qt5-base\src\5.15.10-6bae14788b.clean/include\QtCore -IC:\srcvcpkg\vcpkg\buildtrees\qt5-base\src\5.15.10-6bae14788b.clean/include\QtCore\5.15.10 -IC:\srcvcpkg\vcpkg\buildtrees\qt5-base\src\5.15.10-6bae14788b.clean/include\QtCore\5.15.10\QtCore  -I..\src\corelib\global  -IC:\srcvcpkg\vcpkg\buildtrees\qt5-base\src\5.15.10-6bae14788b.clean\mkspecs\win32-msvc   -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS  -DQT_VERSION_STR=\"5.15.10\" -DQT_VERSION_MAJOR=5 -DQT_VERSION_MINOR=15 -DQT_VERSION_PATCH=10  -DQT_BUILD_QMAKE -DQT_BOOTSTRAPPED -DPROEVALUATOR_FULL  -DQT_NO_FOREACH -DUNICODE -D_ENABLE_EXTENDED_ALIGNED_STORAGE -c -Yc -Fpqmake_pch.pch -TP C:\srcvcpkg\vcpkg\buildtrees\qt5-base\src\5.15.10-6bae14788b.clean\qmake\qmake_pch.h' : return code '0x2'
Stop.

**Comment by dg0yt** [comment]
> ### Compiler
> 
> MingGW

`arm-windows`, `cl`: not "MinGW".

But this error is in bootstrapping of host tools. Maybe it is x64-windows, the default host triplet... The bug report doesn't provide enough information.

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
