### ISSUE TITLE
[New Port Request] Effekseer

### ISSUE THREAD

**Issue by lihao273077334** [microsoft/vcpkg#32729]
### Library name

Effekseer

### Library description

 Effekseer--Particle Effect Creation tool

### Source repository URL

https://github.com/effekseer/Effekseer

### Project homepage (if different from the source repository)

https://effekseer.github.io/en/

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

This software is a particle effect editing tool. By incorporating runtimes and plug-ins, effects created in Effekseer can be played back in your application. Effekseer is intended to be used primarily for games, allowing the designer, not the programmer, to be in charge of editing particle effects.

**Comment by MasterDrake** [comment]
I'm trying to make a port but I'm encountering some issues and I don't think I can cover all the platforms.
A help would be much appreciated!

**Comment by lihao273077334** [comment]
You can tell me what's wrong with you in detail, but I'm afraid can't help more. I'm not very familar with this problem either, let me try to deal with it, too.

**Comment by MasterDrake** [comment]
> You can tell me what's wrong with you in detail, but I'm afraid can't help more. I'm not very familiar with this problem either, let me try to deal with it, too.

Basically I'm trying to run my little example using Vulkan and shaderc keeps mismatching linking options with effekseer
if I choose one, effekseer doesn't work, if I choose the other shaderc doesn't link
Effekseer has too many dependencies so it's not easy
I should try using a DirectX application to see if at least the port works.

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
