### ISSUE TITLE
[llvm] build failure

### ISSUE THREAD

**Issue by 18930215187** [microsoft/vcpkg#32753]
### Operating system

Windows

### Steps to reproduce the behavior

```Shell
vcpkg.json:
{
  "name": "ambriel",
  "version-string": "0.1.0",
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg.schema.json",
  "dependencies": [
    {
      "name": "llvm"
    },
    {
      "name": "opencv4",
      "features": [
        "contrib",
        "nonfree"
      ]
    }
  ],
  "builtin-baseline": "9d47b24eacbd1cd94f139457ef6cd35e5d92cc84"
}

vcpkg install --triplet=x64-windows
```

### Failure logs

terminal:
PS G:\Project\PC\OD-AutoAim\Ambriel\src-tauri> vcpkg install --triplet=x64-windows
Detecting compiler hash for triplet x64-windows...
-- Automatically setting HTTP(S)_PROXY environment variables to "127.0.0.1:7890".
The following packages will be built and installed:
  * bzip2[core,tool]:x64-windows -> 1.0.8#4 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\6165360d15e6de08dff3a5f079d51e69908cc55d
  * curl[core,non-http,schannel,ssl,sspi]:x64-windows -> 8.2.0 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\c82d0a822ec7d4044a58c18f2e198df681822cf6
  * giflib:x64-windows -> 5.2.1#3 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\8ba54b2de43f1fe619e5a7e554f108fc01a771da
  * hdf5[core,szip,zlib]:x64-windows -> 1.14.0#1 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\1266e52ebeeb58e015af053d4e87e5356efe130e
  * leptonica:x64-windows -> 1.83.1 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\90d009f9febb130cbecc48c89cdc309563f85621
  * libarchive[bzip2,core,crypto,libxml2,lz4,lzma,zstd]:x64-windows -> 3.6.2 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\693a99004af1e09acaf76026eaf23218b00c6661
  * libiconv:x64-windows -> 1.17#1 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\4226589d5d658f4d96df83f8539de54dc57a5996
  * libjpeg-turbo:x64-windows -> 2.1.5.1#2 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\a54bb2bec4dfc177249e2c10b31a665c249c660c
  * liblzma:x64-windows -> 5.4.3#1 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\3f97f6a0904a3add9c3273f8ab1993902d75d5ef
  * libpng:x64-windows -> 1.6.39#1 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\af144fe56e6e4c08cd8089d2e1dd46bae60a5062
  * libwebp[core,libwebpmux,nearlossless,simd,unicode]:x64-windows -> 1.3.0#1 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\519daa6213a5995a860ed724c465adf9ff83b52a
  * libxml2[core,iconv,lzma,zlib]:x64-windows -> 2.10.3#1 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\fd1e750ce7851d72bf39c0b6d30a4a8d1d717c45
    llvm[clang,core,default-options,default-targets,disable-assertions,disable-clang-static-analyzer,enable-bindings,enable-terminfo,enable-threads,enable-zlib,enable-zstd,lld,target-spirv,target-x86,tools]:x64-windows -> 15.0.7#3 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\1ba26e4d72f4d6112c483a09d9a2dd0aa42067f3
  * lz4:x64-windows -> 1.9.4#1 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\d7704e3869f579ffdf927b5419579473e9d702d4
    opencv4[contrib,core,default-features,dnn,jpeg,nonfree,png,quirc,tiff,webp]:x64-windows -> 4.7.0#6 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\d435a87c7a3f4dd38d623503d5200abe65c249d1
  * openjpeg:x64-windows -> 2.5.0 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\3451436f9bb5f5ad8946b45868929488fe2c39dd
  * openssl:x64-windows -> 3.1.1#1 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\da3981b5b899f4e74db269ca4854f4bf05d9d387
  * protobuf:x64-windows -> 3.21.12 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\3b145508ba614fe26989b23f6317f15bf6467be4
  * quirc:x64-windows -> 1.1#3 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\85b17d675bbbb05448d16af79d434bc5fca51f7b
  * szip:x64-windows -> 2.1.1#11 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\d70141a3b02fbaec47b0aae75b6abdee3502a0b7
  * tesseract:x64-windows -> 5.3.1#1 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\d0b39327eee123cac1611afe9d88303822fedbdf
  * tiff[core,jpeg,lzma,zip]:x64-windows -> 4.5.1#2 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\68f4ecc87b5ddce6c328c0f600a4c8b81d967d4c
  * vcpkg-get-python-packages:x64-windows -> 2022-06-30 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\e65762bfef05a4d380bb171409c48a694fb35435
Additional packages (*) will be modified to complete this operation.
Restored 0 package(s) from C:\Users\dongf\AppData\Local\vcpkg\archives in 1.22 ms. Use --debug to see more details.
Installing 1/23 llvm:x64-windows...
Building llvm[clang,core,default-options,default-targets,disable-assertions,disable-clang-static-analyzer,enable-bindings,enable-terminfo,enable-threads,enable-zlib,enable-zstd,lld,target-spirv,target-x86,tools]:x64-windows...
-- Installing port from location: C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\1ba26e4d72f4d6112c483a09d9a2dd0aa42067f3
-- Note: llvm only supports static library linkage. Building static library.
-- Using cached llvm-llvm-project-llvmorg-15.0.7.tar.gz.
-- Cleaning sources at G:/Project/PC/OD-AutoAim/Ambriel/src-tauri/vcpkg_installed/vcpkg/blds/llvm/src/org-15.0.7-26832cabce.clean. Use --editable to skip cleaning for the packages you specify.
PS G:\Project\PC\OD-AutoAim\Ambriel\src-tauri> vcpkg install --triplet=x64-windows
Detecting compiler hash for triplet x64-windows...
-- Automatically setting HTTP(S)_PROXY environment variables to "127.0.0.1:7890".
The following packages will be built and installed:
  * bzip2[core,tool]:x64-windows -> 1.0.8#4 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\6165360d15e6de08dff3a5f079d51e69908cc55d
  * curl[core,non-http,schannel,ssl,sspi]:x64-windows -> 8.2.0 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\c82d0a822ec7d4044a58c18f2e198df681822cf6
  * giflib:x64-windows -> 5.2.1#3 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\8ba54b2de43f1fe619e5a7e554f108fc01a771da
  * hdf5[core,szip,zlib]:x64-windows -> 1.14.0#1 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\1266e52ebeeb58e015af053d4e87e5356efe130e
  * leptonica:x64-windows -> 1.83.1 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\90d009f9febb130cbecc48c89cdc309563f85621
  * libarchive[bzip2,core,crypto,libxml2,lz4,lzma,zstd]:x64-windows -> 3.6.2 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\693a99004af1e09acaf76026eaf23218b00c6661
  * libiconv:x64-windows -> 1.17#1 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\4226589d5d658f4d96df83f8539de54dc57a5996
  * libjpeg-turbo:x64-windows -> 2.1.5.1#2 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\a54bb2bec4dfc177249e2c10b31a665c249c660c
  * liblzma:x64-windows -> 5.4.3#1 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\3f97f6a0904a3add9c3273f8ab1993902d75d5ef
  * libpng:x64-windows -> 1.6.39#1 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\af144fe56e6e4c08cd8089d2e1dd46bae60a5062
  * libwebp[core,libwebpmux,nearlossless,simd,unicode]:x64-windows -> 1.3.0#1 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\519daa6213a5995a860ed724c465adf9ff83b52a
  * libxml2[core,iconv,lzma,zlib]:x64-windows -> 2.10.3#1 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\fd1e750ce7851d72bf39c0b6d30a4a8d1d717c45
    llvm[clang,core,default-options,default-targets,disable-assertions,disable-clang-static-analyzer,enable-bindings,enable-terminfo,enable-threads,enable-zlib,enable-zstd,lld,target-spirv,target-x86,tools]:x64-windows -> 15.0.7#3 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\1ba26e4d72f4d6112c483a09d9a2dd0aa42067f3
  * lz4:x64-windows -> 1.9.4#1 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\d7704e3869f579ffdf927b5419579473e9d702d4
    opencv4[contrib,core,default-features,dnn,jpeg,nonfree,png,quirc,tiff,webp]:x64-windows -> 4.7.0#6 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\d435a87c7a3f4dd38d623503d5200abe65c249d1
  * openjpeg:x64-windows -> 2.5.0 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\3451436f9bb5f5ad8946b45868929488fe2c39dd
  * openssl:x64-windows -> 3.1.1#1 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\da3981b5b899f4e74db269ca4854f4bf05d9d387
  * protobuf:x64-windows -> 3.21.12 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\3b145508ba614fe26989b23f6317f15bf6467be4
  * quirc:x64-windows -> 1.1#3 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\85b17d675bbbb05448d16af79d434bc5fca51f7b
  * szip:x64-windows -> 2.1.1#11 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\d70141a3b02fbaec47b0aae75b6abdee3502a0b7
  * tesseract:x64-windows -> 5.3.1#1 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\d0b39327eee123cac1611afe9d88303822fedbdf
  * tiff[core,jpeg,lzma,zip]:x64-windows -> 4.5.1#2 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\68f4ecc87b5ddce6c328c0f600a4c8b81d967d4c
  * vcpkg-get-python-packages:x64-windows -> 2022-06-30 -- C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\e65762bfef05a4d380bb171409c48a694fb35435
Additional packages (*) will be modified to complete this operation.
Restored 0 package(s) from C:\Users\dongf\AppData\Local\vcpkg\archives in 230 us. Use --debug to see more details.
Installing 1/23 llvm:x64-windows...
Building llvm[clang,core,default-options,default-targets,disable-assertions,disable-clang-static-analyzer,enable-bindings,enable-terminfo,enable-threads,enable-zlib,enable-zstd,lld,target-spirv,target-x86,tools]:x64-windows...
-- Installing port from location: C:\Users\dongf\AppData\Local\vcpkg\registries\git-trees\1ba26e4d72f4d6112c483a09d9a2dd0aa42067f3
-- Note: llvm only supports static library linkage. Building static library.
-- Using cached llvm-llvm-project-llvmorg-15.0.7.tar.gz.
-- Cleaning sources at G:/Project/PC/OD-AutoAim/Ambriel/src-tauri/vcpkg_installed/vcpkg/blds/llvm/src/org-15.0.7-26832cabce.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/dongf/AppData/Local/vcpkg/downloads/llvm-llvm-project-llvmorg-15.0.7.tar.gz
-- Applying patch 0001-Fix-install-paths.patch
-- Applying patch 0002-Fix-DR-1734.patch
-- Applying patch 0003-Fix-tools-path.patch
-- Applying patch 0004-Fix-compiler-rt-install-path.patch
-- Applying patch 0005-Fix-tools-install-path.patch
-- Applying patch 0006-Fix-libffi.patch
-- Applying patch 0007-Fix-install-bolt.patch
-- Applying patch 0008-llvm_assert.patch
-- Applying patch 0009-disable-libomp-aliases.patch
-- Using source at G:/Project/PC/OD-AutoAim/Ambriel/src-tauri/vcpkg_installed/vcpkg/blds/llvm/src/org-15.0.7-26832cabce.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Configuring x64-windows
CMake Warning at G:/Project/PC/OD-AutoAim/Ambriel/src-tauri/vcpkg_installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:318 (message):
  The following variables are not used in CMakeLists.txt:

      BOLT_TOOLS_INSTALL_DIR
      LIBOMP_INSTALL_ALIASES

  Please recheck them and remove the unnecessary options from the
  `vcpkg_cmake_configure` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):
  C:/Users/dongf/AppData/Local/vcpkg/registries/git-trees/1ba26e4d72f4d6112c483a09d9a2dd0aa42067f3/portfile.cmake:238 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)

-- Building x64-windows-dbg
CMake Warning at scripts/cmake/vcpkg_execute_build_process.cmake:65 (message):
  Please ensure your system has sufficient memory.
Call Stack (most recent call first):
  G:/Project/PC/OD-AutoAim/Ambriel/src-tauri/vcpkg_installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  G:/Project/PC/OD-AutoAim/Ambriel/src-tauri/vcpkg_installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  C:/Users/dongf/AppData/Local/vcpkg/registries/git-trees/1ba26e4d72f4d6112c483a09d9a2dd0aa42067f3/portfile.cmake:271 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: G:/Environment/C/cmake/bin/cmake.exe --build . --config Debug --target install -- -v -j25
    Working Directory: G:/Project/PC/OD-AutoAim/Ambriel/src-tauri/vcpkg_installed/vcpkg/blds/llvm/x64-windows-dbg
    See logs for more information:
      G:\Project\PC\OD-AutoAim\Ambriel\src-tauri\vcpkg_installed\vcpkg\blds\llvm\install-x64-windows-dbg-out.log
      G:\Project\PC\OD-AutoAim\Ambriel\src-tauri\vcpkg_installed\vcpkg\blds\llvm\install-x64-windows-dbg-out-1.log

Call Stack (most recent call first):
  G:/Project/PC/OD-AutoAim/Ambriel/src-tauri/vcpkg_installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  G:/Project/PC/OD-AutoAim/Ambriel/src-tauri/vcpkg_installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  C:/Users/dongf/AppData/Local/vcpkg/registries/git-trees/1ba26e4d72f4d6112c483a09d9a2dd0aa42067f3/portfile.cmake:271 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building llvm:x64-windows failed with: BUILD_FAILED
Elapsed time to handle llvm:x64-windows: 19 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+llvm
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[llvm]+Build+error&body=Copy+issue+body+from+G%3A%2FProject%2FPC%2FOD-AutoAim%2FAmbriel%2Fsrc-tauri%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md

G:\Project\PC\OD-AutoAim\Ambriel\src-tauri\vcpkg_installed\vcpkg\blds\llvm\install-x64-windows-dbg-out.log:

**Comment by 18930215187** [comment]
I can't seem to upload my detailed log content, can you help me fix this problem just by using the uploaded information? If you need more detailed information from me, I can send you all the tools and environment variables.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Could you please provide the following log files? You can attach them here.
```
G:\Project\PC\OD-AutoAim\Ambriel\src-tauri\vcpkg_installed\vcpkg\blds\llvm\install-x64-windows-dbg-out.log
G:\Project\PC\OD-AutoAim\Ambriel\src-tauri\vcpkg_installed\vcpkg\blds\llvm\install-x64-windows-dbg-out-1.log
```

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
