### ISSUE TITLE
[Request] asmjit and asmtk

### ISSUE THREAD

**Issue by blaquee** [microsoft/vcpkg#3275]
Hi! asmjit is a JIT remote assembler engine and asmtk is a sister project and is an assembler. Both of these are very useful projects and would be a great addition to the package library!

asmtk
https://github.com/asmjit/asmtk

asmjit
https://github.com/asmjit/asmjit

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
