### ISSUE TITLE
Draco package x86-uwp

### ISSUE THREAD

**Issue by WeersProductions** [Microsoft/vcpkg#3276]
Hi all,

I have a problem installing the Draco package. The Draco does not build for x86-uwp:

```
Error: Building package draco:x86-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: draco:x86-uwp
  Vcpkg version: 0.0.108-2018-04-13-4e48a1c235d776b5099a61252ff726edb5b6a6b7
```

I have the latest version from Github. 

Some of the log:
```
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Configuring x86-uwp
-- Configuring x86-uwp done
-- Build x86-uwp-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:164 (message):
    Command failed: C:/Users/user/Documents/GithubClone/vcpkg/downloads/tools/cmake-3.10.2-windows/cmake-3.10.2-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No
    Working Directory: C:/Users/user/Documents/GithubClone/vcpkg/buildtrees/draco/x86-uwp-dbg
    See logs for more information:
      C:\Users\user\Documents\GithubClone\vcpkg\buildtrees\draco\install-x86-uwp-dbg-out.log
```

I'm running Microsoft Windows [Version 10.0.17133.73].
Installing the default Draco version using `vcpkg install draco` works fine though.

Do you have any clue what I am doing wrong? Don't hesitate to send me a message if you need more information!

Thank you!

**Comment by KindDragon** [comment]
You can post install-x86-uwp-dbg-out.log here, but probably Draco just not support UWP and better report directly to them https://github.com/google/draco

**Comment by WeersProductions** [comment]
@KindDragon this is the log file I have, [install-x86-uwp-dbg-out.log](https://github.com/Microsoft/vcpkg/files/1932850/install-x86-uwp-dbg-out.log).

It seems like the error: `error C4146: unary minus operator applied to unsigned type, result still unsigned` is the main reason it doesn't compile. I think when compiling for non-uwp platforms, this is considered a warning and not an error. Where could I disable this error?

Thanks!

**Comment by WeersProductions** [comment]
Hi,
Thanks for your help! I compiled it without vcpkg (simply disabling the error fixed it), but good to know!

**Comment by JackBoosY** [comment]
Hi @WeersProductions , thanks for reporting this issue!
This issue has been fixed. Plz update and rebuild draco.
Thx.
