### ISSUE TITLE
[openimageio] Build error

### ISSUE THREAD

**Issue by TPassmore00** [microsoft/vcpkg#32776]
[issue_body.md](https://github.com/microsoft/vcpkg/files/12174540/issue_body.md)

**Comment by FrankXie05** [comment]
```
LINK : fatal error LNK1104: cannot open file 'python310_d.lib'
```

**Comment by FrankXie05** [comment]
Should be fixed by PR https://github.com/microsoft/vcpkg/pull/31318.
Please remove the dependent cache and try again. :)

**Comment by TPassmore** [comment]
Hi, thanks for looking at this. However, I just tried on a new PC that hasn’t had vcpkg before and got the same error.

**Comment by JackBoosY** [comment]
Provide the full logs.

**Comment by FrankXie05** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
