### ISSUE TITLE
internal error: D:\a\_work\1\s\src\vcpkg\commands.build.cpp(1510): Value was null

### ISSUE THREAD

**Issue by BullyWiiPlaza** [microsoft/vcpkg#32770]
**Describe the bug**
By installing an editable port, I'm running into the error `internal error: D:\a\_work\1\s\src\vcpkg\commands.build.cpp(1510): Value was null`. I made sure to run `git pull` and `bootstrap-vcpkg.bat` but to no avail.

**Environment**
- OS: Windows 11 Pro 64-bit
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32535 for x64
- vcpkg version: vcpkg package management program version 2023-07-19-814b7ec837b59f1c8778f72351c1dd7605983cd2

**To Reproduce**
1. Extract the following .zip file into the buildtrees folder (e.g. `C:\vcpkg\buildtrees`): [polyhook2.zip](https://github.com/microsoft/vcpkg/files/12161860/polyhook2.zip)
2. Run the command `vcpkg install polyhook2:x64-windows-static --editable`
3. The following error happens:
```
Computing installation plan...
The following packages will be built and installed:
    polyhook2[core,detours,exception,inlinentd,pe,virtuals]:x64-windows-static -> 2023-05-16#1
Installing 1/1 polyhook2:x64-windows-static...
Building polyhook2[core,detours,exception,inlinentd,pe,virtuals]:x64-windows-static...
-- Using cached stevemk14ebr-PolyHook_2_0-1ff1d0285fc28bfd206aa0a38ae93022a5ad9be1.tar.gz.
-- Using source at C:/vcpkg/buildtrees/polyhook2/src/22a5ad9be1-860c6aa174
-- Found external ninja('1.11.0').
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: C:/vcpkg/buildtrees/polyhook2/x64-windows-static-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\polyhook2\install-x64-windows-static-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/polyhook2/portfile.cmake:37 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)


error: building polyhook2:x64-windows-static failed with: BUILD_FAILED
Elapsed time to handle polyhook2:x64-windows-static: 11 s
internal error: D:\a\_work\1\s\src\vcpkg\commands.build.cpp(1510): Value was null
Please open an issue at https://github.com/microsoft/vcpkg/issues/new?template=other-type-of-bug-report.md&labels=category:vcpkg-bug with detailed steps to reproduce the problem.
```
Strangely enough, the same command worked before, it seems like my port source code edits caused a compilation error but there's no indication of that in the output. Which value was null?

**Expected behavior**
The error message clearly indicates the problem in an understandable fashion (e.g. compilation error details) or the command works without errors.

**Comment by BillyONeal** [comment]
Repros for me, thanks!
