### ISSUE TITLE
opengl:arm-uwp Error

### ISSUE THREAD

**Issue by todorokis** [microsoft/vcpkg#3278]
Would you have a look at this?  Thank you in advance.

PS C:\vcpkg> vcpkg install opencv:arm-uwp
....
Starting package 5/7: opengl:arm-uwp
Building package opengl[core]:arm-uwp...
-- CURRENT_INSTALLED_DIR=C:/vcpkg/installed/arm-uwp
-- DOWNLOADS=C:/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/vcpkg/packages/opengl_arm-uwp
-- CURRENT_BUILDTREES_DIR=C:/vcpkg/buildtrees/opengl
-- CURRENT_PORT_DIR=C:/vcpkg/ports/opengl/.
CMake Error at ports/opengl/portfile.cmake:20 (message):
  Cannot find Windows 10.0.16299.0 SDK.  File does not exist: C:\Program
  Files (x86)\Windows Kits\10\Lib\10.0.16299.0\um\arm\OpenGL32.Lib
Call Stack (most recent call first):
  scripts/ports.cmake:72 (include)

Error: Building package opengl:arm-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opengl:arm-uwp
  Vcpkg version: 0.0.108-2018-04-19-4f52f53b99f6a5465157958bc99f79cc0b2712ad

Additionally, attach any relevant sections from the log files above.

**Comment by todorokis** [comment]
I confirmed that Windows 10.0.16299.0 SDK (C++) for UWP is already Installed but 
"File does not exist: C:\Program
Files (x86)\Windows Kits\10\Lib\10.0.16299.0\um\arm\OpenGL32.Lib"

Thanks.

**Comment by mariusz102102** [comment]
@cenit Is it possible to fix `vcpkg install opencv:arm-uwp` or it is not repairable? Will opencv on ARM work without opengl32.lib?

**Comment by cenit** [comment]
OpenCV will work on ARM/ARM64 UWP. It will just work without opengl (which to be honest I still am not sure what will remove from the table). Tomorrow I will try to prepare a PR with the fixes, sorry for the delay

**Comment by gilbdev** [comment]
@cenit any update on this ?

still failing with opencv4 and sdk 18362

**Comment by gilbdev** [comment]
the errors above comes from contrib modules.
so it's possible to disable those modules by editing `ports\opencv4\portfile.cmake`

add:
```
set(DISABLED_CONTRIB_MODULES "")
if("contrib" IN_LIST FEATURES)
  if(VCPKG_TARGET_ARCHITECTURE STREQUAL "arm" OR VCPKG_TARGET_ARCHITECTURE STREQUAL "arm64")
    list(APPEND DISABLED_CONTRIB_MODULES "-DBUILD_opencv_saliency=OFF")
    list(APPEND DISABLED_CONTRIB_MODULES "-DBUILD_opencv_bgsegm=OFF")
    list(APPEND DISABLED_CONTRIB_MODULES "-DBUILD_opencv_line_descriptor=OFF")
  endif()
endif()
```
and `${DISABLED_CONTRIB_MODULES}` in the vcpkg_configure_cmake OPTIONS list

doing this, disabling opengl and webp and you'll be able to build opencv for uwp-arm

**Comment by cenit** [comment]
@gilbdev please do a PR for that
just put the opengl feature disabled for arm (!arm), then add also the snippet from above

**Comment by gilbdev** [comment]
will do the PR.

i can disable opengl for arm but i will have to remove opengl and webp from the default feature for all platforms : is this ok ? (seems i can't use `(!arm)` for features)

regarding the 3 modules not compiling, i will also make an issue on opencv-contrib, as it's only the use of `popcnt` that make it not compile and this could be fixed. os it's more a temp fix here right now.

**Comment by cenit** [comment]
> (seems i can't use (!arm) for features)

mmm really? is it only for dependencies? might be worth a ping to @ras0219-msft to ask what are his thoughts. Because removing opengl/webp for everyone from the features might not be very nice (i fear automated scripts that just install opencv sure about the default features coming down...)

**Comment by PhilLab** [comment]
I am also trying to build OpenCV for arm, more specifically:  
`.\vcpkg.exe install opencv4:arm64-uwp` but It failed. These were the steps I did:

1. Testing if a less obscure architecture, `opencv:x64-uwp` works:
```ps
.\vcpkg.exe install opencv4:x64-uwp
```
it failed  due to protobuf not being available
2.  Installing protobuf (but strangely, x86 was requested)
```ps
\vcpkg.exe install protobuf:x86-windows
```
3. Tryping opencv again, now it worked :tada:
```ps
.\vcpkg.exe install opencv4:x64-uwp
```
4. opencv:arm64-uwp does not work because of the opengl problems mentioned here
```ps
.\vcpkg.exe install opencv4:arm64-uwp
```
The error in the powershell is:
>  Cannot find Windows 10.0.18362.0 SDK.  File does not exist: C:\Program
  Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\arm64\OpenGL32.Lib

5. Trying to find a configuration without opengl:
```
.\vcpkg.exe install opencv4[dnn,jpeg,png,tiff,core]:arm64-uwp
```
fails. The error from the .log file is:

> C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.25.28610\include\emmintrin.h(24,1): fatal error C1189: #error:  This header is specific to X86 and X64 targets [D:\DEVELOPMENT\vcpkg-uwp\buildtrees\opencv4\arm64-uwp-dbg\modules\core\opencv_core.vcxproj]

**Comment by JonLiu1993** [comment]
@todorokis ,Thanks for posting this issue. opencv:arm-uwp can install successfully, please reopen this issue if it still be a problem for you.
````
PS F:\test9\vcpkg> ./vcpkg install opencv:arm-uwp --editable
Computing installation plan...
The following packages are already installed:
    opencv[core,default-features]:arm-uwp -> 4.5.4#1
Package opencv:arm-uwp is already installed
Restored 0 packages from C:\Users\vzhli17\AppData\Local\vcpkg\archives in 142.6 us. Use --debug to see more details.

Total elapsed time: 118.8 ms
````
