### ISSUE TITLE
[New Port Request] libmapper

### ISSUE THREAD

**Issue by luzpaz** [microsoft/vcpkg#32828]
### Library name

libmapper

### Library description

libmapper is an open-source, cross-platform software library for declaring data signals on a shared network and enabling arbitrary connections to be made between them. libmapper creates a distributed mapping system/network, with no central points of failure, the potential for tight collaboration and easy parallelization of media synthesis. The main focus of libmapper development is to provide tools for creating and using systems for interactive control of media synthesis.

### Source repository URL

https://github.com/libmapper/libmapper

### Project homepage (if different from the source repository)

http://libmapper.github.io/

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

Documentation: http://libmapper.github.io/api/index.html

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
