### ISSUE TITLE
[New Port Request] rtosc

### ISSUE THREAD

**Issue by luzpaz** [microsoft/vcpkg#32827]
### Library name

rtosc

### Library description

Realtime Open Sound Control

### Source repository URL

https://github.com/fundamental/rtosc

### Project homepage (if different from the source repository)

http://fundamental-code.com/wiki/rtosc/

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

Docs: http://fundamental-code.com/wiki/rtosc/Guide/
API Docs: http://fundamental-code.com/rtosc/api/index.html

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
