### ISSUE TITLE
[ffmpeg] build failure

### ISSUE THREAD

**Issue by MadDeCoDeR** [microsoft/vcpkg#32823]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
cmake -B ${{github.workspace}}/build --preset=linux-${{env.BUILD_TYPE}}
```

### Failure logs

Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip
warning: Download failed -- retrying after 1000ms
warning: Download failed -- retrying after 2000ms
warning: Download failed -- retrying after 4000ms
error: Failed to download from mirror set
error: https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip: WinHttpSendRequest failed with exit code 12002
error: https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip: WinHttpSendRequest failed with exit code 12002
error: https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip: WinHttpSendRequest failed with exit code 12002
error: https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip: WinHttpSendRequest failed with exit code 12002
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1045): 
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 10us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 1070us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 1.5 min (91307930us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
      

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:[270](https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG/actions/runs/5701467127/job/15452664686#step:6:271) (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_find_acquire_program.cmake:172 (vcpkg_download_distfile)
  ports/ffmpeg/portfile.cmake:31 (vcpkg_find_acquire_program)
  scripts/ports.cmake:147 (include)

error: building ffmpeg:x64-windows-static-md failed with: BUILD_FAILED
Elapsed time to handle ffmpeg:x64-windows-static-md: 1.6 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+ffmpeg
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[ffmpeg]+Build+error&body=Copy+issue+body+from+D%3A%2Fa%2FClassic-RBDOOM-3-BFG%2FClassic-RBDOOM-3-BFG%2Fbuild%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md
You can also submit an issue by running (GitHub CLI must be installed):
    gh issue create -R microsoft/vcpkg --title "[ffmpeg] Build failure" --body-file D:/a/Classic-RBDOOM-3-BFG/Classic-RBDOOM-3-BFG/build/vcpkg_installed/vcpkg/issue_body.md
-- Running vcpkg install - failed
CMake Error at D:/a/Classic-RBDOOM-3-BFG/Classic-RBDOOM-3-BFG/vcpkg/scripts/buildsystems/vcpkg.cmake:895 (message):
  vcpkg install failed.  See logs for more information:
  D:\a\Classic-RBDOOM-3-BFG\Classic-RBDOOM-3-BFG\build\vcpkg-manifest-install.log
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:148 (include)
  CMakeLists.txt:4 (project)

-- Configuring incomplete, errors occurred!

### Additional context

The build was executed through Github Actions

**Comment by cnmade** [comment]
nasm down. you need download file by your self:
https://gstreamer.freedesktop.org/src/mirror/

**Comment by MadDeCoDeR** [comment]
nasm website is up again and it works. Closing issue
