### ISSUE TITLE
[gmp] build failure on wasm32-emscripten 

### ISSUE THREAD

**Issue by LeenHawk** [microsoft/vcpkg#32820]
### Operating system

Linux (Debian Sid WSL)

### Compiler

Emscripten emcc 3.1.43

### Steps to reproduce the behavior

```Shell
`./vcpkg install gmp --triplet=wasm32-emscripten`
```

### Failure logs

[config-wasm32-emscripten-dbg-out.log](https://github.com/microsoft/vcpkg/files/12207307/config-wasm32-emscripten-dbg-out.log)
[config-wasm32-emscripten-dbg-config.log](https://github.com/microsoft/vcpkg/files/12207308/config-wasm32-emscripten-dbg-config.log)
[config-wasm32-emscripten-dbg-err.log](https://github.com/microsoft/vcpkg/files/12207309/config-wasm32-emscripten-dbg-err.log)

### Additional context

build gmp with emscripten works well like below:
```shell
wget https://gmplib.org/download/gmp/gmp-6.2.1.tar.xz
tar -xf gmp-6.2.1.tar.xz
cd gmp-6.2.1
emconfigure ./configure --disable-assembly --enable-cxx --host=none --with-pic --with-readline=no --disable-silent-rules --verbose --disable-shared --enable-static
emmake make
```
So, I guess it failed because vcpkg use `configure` but not set well with emscripten env variable. (I have tried add `--host=none` and change `enable-assembly=no` in `profile.cmake`, it doesn't work.)

**Comment by LeenHawk** [comment]
I think wasm32-emscripten setting is not same to `emconfigure` setting for `configure` project...

**Comment by xiaozhuai** [comment]
Reproduced on macOS with EMSDK 3.1.44

**Comment by dg0yt** [comment]
I'm not convinced that `emconfigure` adds a lot which we don't already have. But we have a `vcpkg_configure_make` which is known to not pass enough flags for some targets. And fixing that isn't accept yet, #31228.
