### ISSUE TITLE
[curl] Default features not getting disabled, using a specific SSL backend is basically impossible

### ISSUE THREAD

**Issue by glorantq** [microsoft/vcpkg#32838]
### Is your feature request related to a problem? Please describe.

When in manifest mode, default features cannot be disabled. Having this as a dependency in my vcpkg.json:
`{
    "name": "curl",
    "default-features": false
},`
I see that curl is getting build with the default options still enabled: `curl[core,non-http,sectransp,ssl]`. This makes it impossible to build only for http usage, and to select a custom SSL backend.

Furthermore, the http2 option also forces the default ssl backend, which again, makes it impossible to use a specific backend exclusively.

### Proposed solution

The expected behaviour would be that the default-features switch works, and the http2 option shouldn't depend on the default ssl backend feature, when a custom ssl backend is enabled.

### Additional context

Building with options: `"mbedtls", "http2", "brotli", "zstd", "tool"`, output of `curl -V`
Actual:
```
curl 8.2.0-DEV (Darwin) libcurl/8.2.0-DEV SecureTransport (mbedTLS/2.28.1) zlib/1.2.13 brotli/1.0.9 zstd/1.5.5 nghttp2/1.55.1
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IPv6 Largefile libz MultiSSL NTLM SSL threadsafe UnixSockets zstd
```

Expected (with modified vcpkg.json for the port):
```
curl 8.2.0-DEV (Darwin) libcurl/8.2.0-DEV mbedTLS/2.28.1 zlib/1.2.13 brotli/1.0.9 zstd/1.5.5 nghttp2/1.55.1
Release-Date: [unreleased]
Protocols: http https
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM SSL threadsafe UnixSockets zstd
```

**Comment by jimwang118** [comment]
The content of the local test file is as follows:
vcpkg.json
```
{
  "name": "test",
  "version-string": "no-version",
  "dependencies": [
    {
      "name": "curl",
      "default-features": false   
    }
  ]
}
```
test.cpp
```
#include <iostream>
#include <fstream>
#include <sstream>
#include <curl/curl.h>

int main()
{
    cout << "verions:" << endl;
    return 0;
}
```
cmakelists.txt
cmake_minimum_required(VERSION 3.8)

project(test)

```
# Add source to this project's executable.
add_executable (test "test.cpp")

find_package(CURL CONFIG REQUIRED)
    target_link_libraries(test PRIVATE CURL::libcurl)
```
After compiling, the result is as expected, and only the curl library is installed locally. The default-features: `non-http` and `ssl `will not be installed.
![image](https://github.com/microsoft/vcpkg/assets/122244446/9981f751-f319-49b7-80ca-265303a72f34)

**Comment by glorantq** [comment]
You will not see library files for non-http and ssl features. Please see the build log, or in the test application, please verify the output of `curl_version()`.

**Comment by glorantq** [comment]
Upon further investigation, I see that another dependency, curlpp is causing the mentioned features to be enabled. While it's weird for a cURL wrapper to directly request features for cURL, it's not a bug with the cURL port, sorry. 

The issues with the http2 feature forcing the default ssl backend still stand.
