### ISSUE TITLE
opencv4[freetype]:arm64-android    build error

### ISSUE THREAD

**Issue by MCSQNXA** [microsoft/vcpkg#32846]
### Operating system

Windows

### Compiler

Clang

### Steps to reproduce the behavior

```Shell
vcpkg install opencv4[freetype]:arm-android
vcpkg install opencv4[freetype]:arm64-android
vcpkg install opencv4[freetype]:x86-android
vcpkg install opencv4[freetype]:x64-android
```

### Failure logs

I used the latest version of vcpkg 2023-07-21 for compilation. Although it can be successfully compiled, it cannot enable the freetype module, resulting in libopencv_freetype4. a file cannot be generated. In my project, I will be prompted with a symbol issue that cannot be found. Similarly, I compiled x64 windows static, which is a platform that can compile and generate this file normally

Installing 14/14 opencv4:arm64-android...
Building opencv4[core,default-features,dnn,freetype,jpeg,png,quirc,tiff,webp]:arm64-android...
warning: -- Using community triplet arm64-android. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\Vcpkg\triplets\community\arm64-android.cmake
-- Downloading https://github.com/opencv/opencv/archive/4.7.0.tar.gz -> opencv-opencv-4.7.0-1.tar.gz...
-- Extracting source C:/Vcpkg/downloads/opencv-opencv-4.7.0-1.tar.gz
-- Applying patch 0001-disable-downloading.patch
-- Applying patch 0002-install-options.patch
-- Applying patch 0003-force-package-requirements.patch
-- Applying patch 0004-fix-eigen.patch
-- Applying patch 0005-fix-policy-CMP0057.patch
-- Applying patch 0006-fix-uwp.patch
-- Applying patch 0008-devendor-quirc.patch
-- Applying patch 0009-fix-protobuf.patch
-- Applying patch 0010-fix-uwp-tiff-imgcodecs.patch
-- Applying patch 0011-remove-python2.patch
-- Applying patch 0012-fix-zlib.patch
-- Applying patch 0015-fix-freetype.patch
-- Using source at C:/Vcpkg/buildtrees/opencv4/src/4.7.0-87379d1df6.clean
CMake Warning at ports/opencv4/portfile.cmake:83 (message):
  The dnn module cannot be enabled on Android
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)

-- Downloading https://github.com/tiny-dnn/tiny-dnn/archive/v1.0.0a3.tar.gz -> opencv-cache/tiny_dnn/adb1c512e09ca2c7a6faef36f9c53e59-v1.0.0a3.tar.gz...
-- Configuring arm64-android
-- Building arm64-android-dbg
-- Building arm64-android-rel
-- Using cached mingw-w64-i686-pkgconf-1~1.8.0-2-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using msys root at C:/Vcpkg/downloads/tools/msys2/6f3fa1a12ef85a6f
-- Installing: C:/Vcpkg/packages/opencv4_arm64-android/share/opencv4/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 32 s.
Elapsed time to handle opencv4:arm64-android: 13 min
Total install time: 33 min
If you do not install the meta-port *opencv*, the package opencv4 is compatible with CMake
if you set the OpenCV_DIR *before* the find_package call

    set(OpenCV_DIR "${VCPKG_INSTALLED_DIR}/arm64-android/share/opencv4")
    find_package(OpenCV REQUIRED)

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
