### ISSUE TITLE
[eigen3] build failure

### ISSUE THREAD

**Issue by dsl2501** [microsoft/vcpkg#32844]
### Operating system

Windows

### Compiler

Windows powershell

### Steps to reproduce the behavior

```Shell
.\vcpkg\vcpkg install eigen3
```

### Failure logs

warning: Starting with the September 2023 release, the default triplet for vcpkg libraries will change from x86-windows to the detected host triplet (x64-windows). To resolve this message, add --triplet x86-windows to keep the same behavior.
Computing installation plan...
The following packages will be built and installed:
    eigen3:x86-windows -> 3.4.0#2
  * vcpkg-cmake:x64-windows -> 2023-05-04
  * vcpkg-cmake-config:x64-windows -> 2022-02-06#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
error: while detecting compiler information:
The log file content at "C:\Users\이동수\vcpkg\buildtrees\detect_compiler\stdout-x64-windows.log" is:
-- Found external ninja('1.11.0').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/Users/이동수/vcpkg/buildtrees/detect_compiler/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\이동수\vcpkg\buildtrees\detect_compiler\config-x64-windows-rel-CMakeCache.txt.log
      C:\Users\이동수\vcpkg\buildtrees\detect_compiler\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:314 (vcpkg_execute_required_process)
  scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:147 (include)

error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.

**Comment by MonicaLiu0311** [comment]
```
See logs for more information:
C:\Users\이동수\vcpkg\buildtrees\detect_compiler\config-x64-windows-rel-CMakeCache.txt.log
C:\Users\이동수\vcpkg\buildtrees\detect_compiler\config-x64-windows-out.log
```

Please provide the above log files.

**Comment by dsl2501** [comment]
[config-x64-windows-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/12212170/config-x64-windows-rel-CMakeCache.txt.log)
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/12212171/config-x64-windows-out.log)

**Comment by MonicaLiu0311** [comment]
I didn't repro you issue.
 
```
 file failed to open for reading (Permission denied):

    C:/Users/이동수/vcpkg/buildtrees/detect_compiler/x64-windows-rel/CMakeFiles/3.25.1/CompilerIdC/CMakeCCompilerId.exe
```
This may be related to the permission setting. The guess is that there are special characters or non-ASCII characters in the file path, which causes the file path to be parsed incorrectly. Can you change `이동수` to ASCII characters.

**Comment by JackBoosY** [comment]
Re-clone vcpkg in a path which DO NOT contains non-ascii characters.

**Comment by MonicaLiu0311** [comment]
Ping @dsl2501

**Comment by MonicaLiu0311** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by algoqt** [comment]
I have the same issue , after download and run  ./bootstrap-vcpkg.bat ,  the CMakeCCompilerId.exe is missing and come to install any package , it go error like this: 

CMake Error at C:/minGW64/mingw32/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:864 (file):
  file STRINGS file
  "C:/vcpkg/buildtrees/detect_compiler/x64-windows-rel/CMakeFiles/3.27.1/CompilerIdC/CMakeCCompilerId.exe"
  cannot be read.
Call Stack (most recent call first):

**Comment by JackBoosY** [comment]
> I have the same issue , after download and run ./bootstrap-vcpkg.bat , the CMakeCCompilerId.exe is missing and come to install any package , it go error like this:
> 
> CMake Error at C:/minGW64/mingw32/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:864 (file): file STRINGS file "C:/vcpkg/buildtrees/detect_compiler/x64-windows-rel/CMakeFiles/3.27.1/CompilerIdC/CMakeCCompilerId.exe" cannot be read. Call Stack (most recent call first):

Maybe permission issue, please clone vcpkg in another partition.
