### ISSUE TITLE
[protobuf] protobuf:arm64-windows fail

### ISSUE THREAD

**Issue by shijunz** [microsoft/vcpkg#32849]
U:\>vcpkg install opencv:arm64-windows
Computing installation plan...
The following packages will be built and installed:
  * libjpeg-turbo[core]:arm64-windows -> 2.1.5.1#1
  * liblzma[core]:arm64-windows -> 5.4.1#1
  * libpng[core]:arm64-windows -> 1.6.39#1
  * libwebp[core,libwebpmux,nearlossless,simd,unicode]:arm64-windows -> 1.3.0
    opencv[core,default-features]:arm64-windows -> 4.7.0#1
  * opencv4[core,default-features,dnn,jpeg,png,quirc,tiff,webp]:arm64-windows -> 4.7.0#6
  * protobuf[core]:arm64-windows -> 3.21.12
  * quirc[core]:arm64-windows -> 1.1#3
  * tiff[core,jpeg,lzma,zip]:arm64-windows -> 4.5.0#3
  * vcpkg-get-python-packages[core]:arm64-windows -> 2022-06-30
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet arm64-windows...
Restored 0 package(s) from C:\Users\shijunz\AppData\Local\vcpkg\archives in 1.23 ms. Use --debug to see more details.
Installing 1/10 libjpeg-turbo:arm64-windows...
Building libjpeg-turbo[core]:arm64-windows...
-- Using cached libjpeg-turbo-libjpeg-turbo-2.1.5.1.tar.gz.
-- Cleaning sources at C:/tools/vcpkg/buildtrees/libjpeg-turbo/src/2.1.5.1-f411453282.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/tools/vcpkg/downloads/libjpeg-turbo-libjpeg-turbo-2.1.5.1.tar.gz
-- Applying patch add-options-for-exes-docs-headers.patch
-- Applying patch workaround_cmake_system_processor.patch
-- Using source at C:/tools/vcpkg/buildtrees/libjpeg-turbo/src/2.1.5.1-f411453282.clean
-- Found external ninja('1.11.0').
-- Configuring arm64-windows
-- Building arm64-windows-dbg
-- Building arm64-windows-rel
-- Fixing pkgconfig file: C:/tools/vcpkg/packages/libjpeg-turbo_arm64-windows/lib/pkgconfig/libjpeg.pc
-- Fixing pkgconfig file: C:/tools/vcpkg/packages/libjpeg-turbo_arm64-windows/lib/pkgconfig/libturbojpeg.pc
-- Using cached mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using msys root at C:/tools/vcpkg/downloads/tools/msys2/5b9374e6ec2c4e17
-- Fixing pkgconfig file: C:/tools/vcpkg/packages/libjpeg-turbo_arm64-windows/debug/lib/pkgconfig/libjpeg.pc
-- Fixing pkgconfig file: C:/tools/vcpkg/packages/libjpeg-turbo_arm64-windows/debug/lib/pkgconfig/libturbojpeg.pc
-- Installing: C:/tools/vcpkg/packages/libjpeg-turbo_arm64-windows/share/libjpeg-turbo/copyright
-- Performing post-build validation
Stored binaries in 1 destinations.
Elapsed time to handle libjpeg-turbo:arm64-windows: 41 s
Installing 2/10 liblzma:arm64-windows...
Building liblzma[core]:arm64-windows...
-- Using cached xz-5.4.1.tar.xz.
-- Cleaning sources at C:/tools/vcpkg/buildtrees/liblzma/src/f890ee5207-326fe62969.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/tools/vcpkg/downloads/xz-5.4.1.tar.xz
-- Applying patch fix_config_include.patch
-- Applying patch win_output_name.patch
-- Applying patch add_support_ios.patch
-- Applying patch build-tools.patch
-- Using source at C:/tools/vcpkg/buildtrees/liblzma/src/f890ee5207-326fe62969.clean
-- Found external ninja('1.11.0').
-- Configuring arm64-windows
-- Building arm64-windows-dbg
-- Building arm64-windows-rel
-- Fixing pkgconfig file: C:/tools/vcpkg/packages/liblzma_arm64-windows/lib/pkgconfig/liblzma.pc
-- Using cached mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using msys root at C:/tools/vcpkg/downloads/tools/msys2/5b9374e6ec2c4e17
-- Fixing pkgconfig file: C:/tools/vcpkg/packages/liblzma_arm64-windows/debug/lib/pkgconfig/liblzma.pc
-- Installing: C:/tools/vcpkg/packages/liblzma_arm64-windows/share/liblzma/copyright
-- Performing post-build validation
Stored binaries in 1 destinations.
Elapsed time to handle liblzma:arm64-windows: 32 s
Installing 3/10 libpng:arm64-windows...
Building libpng[core]:arm64-windows...
-- Using cached glennrp-libpng-v1.6.39.tar.gz.
-- Cleaning sources at C:/tools/vcpkg/buildtrees/libpng/src/v1.6.39-a77eb96d39.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/tools/vcpkg/downloads/glennrp-libpng-v1.6.39.tar.gz
-- Applying patch cmake.patch
-- Applying patch fix-export-targets.patch
-- Applying patch pkgconfig.patch
-- Applying patch fix-msa-support-for-mips.patch
-- Using source at C:/tools/vcpkg/buildtrees/libpng/src/v1.6.39-a77eb96d39.clean
-- Found external ninja('1.11.0').
-- Configuring arm64-windows
-- Building arm64-windows-dbg
-- Building arm64-windows-rel
-- Installing: C:/tools/vcpkg/packages/libpng_arm64-windows/share/png/vcpkg-cmake-wrapper.cmake
-- Fixing pkgconfig file: C:/tools/vcpkg/packages/libpng_arm64-windows/lib/pkgconfig/libpng16.pc
-- Using cached mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using msys root at C:/tools/vcpkg/downloads/tools/msys2/5b9374e6ec2c4e17
-- Fixing pkgconfig file: C:/tools/vcpkg/packages/libpng_arm64-windows/debug/lib/pkgconfig/libpng16.pc
-- Installing: C:/tools/vcpkg/packages/libpng_arm64-windows/debug/lib/pkgconfig/libpng.pc
-- Installing: C:/tools/vcpkg/packages/libpng_arm64-windows/lib/pkgconfig/libpng.pc
-- Installing: C:/tools/vcpkg/packages/libpng_arm64-windows/share/libpng/usage
-- Installing: C:/tools/vcpkg/packages/libpng_arm64-windows/share/libpng/copyright
-- Performing post-build validation
Stored binaries in 1 destinations.
Elapsed time to handle libpng:arm64-windows: 14 s
Installing 4/10 libwebp:arm64-windows...
Building libwebp[core,libwebpmux,nearlossless,simd,unicode]:arm64-windows...
-- Downloading https://github.com/webmproject/libwebp/archive/v1.3.0.tar.gz -> webmproject-libwebp-v1.3.0.tar.gz...
-- Extracting source C:/tools/vcpkg/downloads/webmproject-libwebp-v1.3.0.tar.gz
-- Applying patch 0002-cmake-config.patch
-- Applying patch 0007-fix-arm-build.patch
-- Applying patch 0008-sdl.patch
-- Applying patch 0010-fix_build.patch
-- Using source at C:/tools/vcpkg/buildtrees/libwebp/src/v1.3.0-907b664bb7.clean
-- Found external ninja('1.11.0').
-- Configuring arm64-windows
-- Building arm64-windows-dbg
-- Building arm64-windows-rel
-- Fixing pkgconfig file: C:/tools/vcpkg/packages/libwebp_arm64-windows/lib/pkgconfig/libsharpyuv.pc
-- Fixing pkgconfig file: C:/tools/vcpkg/packages/libwebp_arm64-windows/lib/pkgconfig/libwebp.pc
-- Fixing pkgconfig file: C:/tools/vcpkg/packages/libwebp_arm64-windows/lib/pkgconfig/libwebpdecoder.pc
-- Fixing pkgconfig file: C:/tools/vcpkg/packages/libwebp_arm64-windows/lib/pkgconfig/libwebpdemux.pc
-- Fixing pkgconfig file: C:/tools/vcpkg/packages/libwebp_arm64-windows/lib/pkgconfig/libwebpmux.pc
-- Using cached mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using msys root at C:/tools/vcpkg/downloads/tools/msys2/5b9374e6ec2c4e17
-- Fixing pkgconfig file: C:/tools/vcpkg/packages/libwebp_arm64-windows/debug/lib/pkgconfig/libsharpyuv.pc
-- Fixing pkgconfig file: C:/tools/vcpkg/packages/libwebp_arm64-windows/debug/lib/pkgconfig/libwebp.pc
-- Fixing pkgconfig file: C:/tools/vcpkg/packages/libwebp_arm64-windows/debug/lib/pkgconfig/libwebpdecoder.pc
-- Fixing pkgconfig file: C:/tools/vcpkg/packages/libwebp_arm64-windows/debug/lib/pkgconfig/libwebpdemux.pc
-- Fixing pkgconfig file: C:/tools/vcpkg/packages/libwebp_arm64-windows/debug/lib/pkgconfig/libwebpmux.pc
-- Installing: C:/tools/vcpkg/packages/libwebp_arm64-windows/share/libwebp/usage
-- Installing: C:/tools/vcpkg/packages/libwebp_arm64-windows/share/libwebp/copyright
-- Performing post-build validation
Stored binaries in 1 destinations.
Elapsed time to handle libwebp:arm64-windows: 1.4 min
Installing 5/10 protobuf:arm64-windows...
Building protobuf[core]:arm64-windows...
-- Downloading https://github.com/protocolbuffers/protobuf/archive/v3.21.12.tar.gz -> protocolbuffers-protobuf-v3.21.12.tar.gz...
-- Extracting source C:/tools/vcpkg/downloads/protocolbuffers-protobuf-v3.21.12.tar.gz
-- Applying patch fix-static-build.patch
-- Applying patch fix-default-proto-file-path.patch
-- Applying patch compile_options.patch
-- Using source at C:/tools/vcpkg/buildtrees/protobuf/src/v3.21.12-fdb7676342.clean
-- Found external ninja('1.11.0').
-- Configuring arm64-windows
-- Building arm64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
    Working Directory: C:/tools/vcpkg/buildtrees/protobuf/arm64-windows-dbg
    See logs for more information:
      C:\tools\vcpkg\buildtrees\protobuf\install-arm64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/arm64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/arm64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/protobuf/portfile.cmake:48 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building protobuf:arm64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+protobuf
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[protobuf]+Build+error&body=Copy+issue+body+from+C%3A%2Ftools%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by Cheney-W** [comment]
Could you please provide us with the `C:\tools\vcpkg\buildtrees\protobuf\install-arm64-windows-dbg-out.log` file? Thank you!

**Comment by Cheney-W** [comment]
We don't have enough information to solve this issue, if you have any more information to help us solve this, please contact us again.
