### ISSUE TITLE
 atlmfc

### ISSUE THREAD

**Issue by taneshgyr** [microsoft/vcpkg#32894]
```[tasklist]
### Tasks
```

**Comment by taneshgyr** [comment]
error: building atlmfc:x64-windows failed with: BUILD_FAILED
Elapsed time to handle atlmfc:x64-windows: 122 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.

**Comment by taneshgyr** [comment]
how to solve this matter?

**Comment by Neumann-A** [comment]
> how to solve this matter?

Install ATL/MFC via the Visual Studio installer. The port just checks if it is installed.

**Comment by FrankXie05** [comment]
@taneshgyr Could you pelase provide the error log?

**Comment by taneshgyr** [comment]
[57/73] "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/link.exe" @src/harfbuzz.dll.rsp
FAILED: src/harfbuzz.dll 
"C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/link.exe" @src/harfbuzz.dll.rsp
LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/RELEASE' specification
LINK : fatal error LNK1181: cannot open input file 'NITRO\OneDrive\Desktop\DEV\vcpkg\installed\x64-windows\debug\lib\pkgconfig\\..\..\lib.obj'
[58/73] "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/cl.exe" "-Isrc\harfbuzz-subset.dll.p" "-Isrc" "-I..\src\8.0.0-a57fbf2423.clean\src" "-I." "-I..\src\8.0.0-a57fbf2423.clean" "-IC:/Users/ACER NITRO/OneDrive/Desktop/DEV/vcpkg/installed/x64-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W2" "/EHs-c-" "/GR-" "/std:c++14" "/permissive-" "/Od" "/wd4244" "/utf-8" "-DHAVE_CONFIG_H" "-nologo" "-DWIN32" "-D_WINDOWS" "-W3" "-utf-8" "-GR" "-EHsc" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DHB_DLL_EXPORT" "/Fdsrc\harfbuzz-subset.dll.p\hb-ot-cff1-table.cc.pdb" /Fosrc/harfbuzz-subset.dll.p/hb-ot-cff1-table.cc.obj "/c" ../src/8.0.0-a57fbf2423.clean/src/hb-ot-cff1-table.cc
cl : Command line warning D9025 : overriding '/W2' with '/W3'
cl : Command line warning D9025 : overriding '/GR-' with '/GR'
cl : Command line warning D9025 : overriding '/EHs-' with '/EHs'
cl : Command line warning D9025 : overriding '/EHc-' with '/EHc'
C:\Users\ACER NITRO\OneDrive\Desktop\DEV\vcpkg\buildtrees\harfbuzz\src\8.0.0-a57fbf2423.clean\src\hb-debug.hh(101): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
C:\Users\ACER NITRO\OneDrive\Desktop\DEV\vcpkg\buildtrees\harfbuzz\src\8.0.0-a57fbf2423.clean\src\hb-font.hh(422): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
C:\Users\ACER NITRO\OneDrive\Desktop\DEV\vcpkg\buildtrees\harfbuzz\src\8.0.0-a57fbf2423.clean\src\hb-font.hh(665): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
C:\Users\ACER NITRO\OneDrive\Desktop\DEV\vcpkg\buildtrees\harfbuzz\src\8.0.0-a57fbf2423.clean\src\hb-ot-cff1-table.hh(1403): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
C:\Users\ACER NITRO\OneDrive\Desktop\DEV\vcpkg\buildtrees\harfbuzz\src\8.0.0-a57fbf2423.clean\src\hb-ot-cff1-table.hh(1404): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Users\ACER NITRO\OneDrive\Desktop\DEV\vcpkg\buildtrees\harfbuzz\src\8.0.0-a57fbf2423.clean\src\hb-ot-cff1-table.hh(1414): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
C:\Users\ACER NITRO\OneDrive\Desktop\DEV\vcpkg\buildtrees\harfbuzz\src\8.0.0-a57fbf2423.clean\src\hb-vector.hh(48): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
C:\Users\ACER NITRO\OneDrive\Desktop\DEV\vcpkg\buildtrees\harfbuzz\src\8.0.0-a57fbf2423.clean\src\hb-vector.hh(46): note: while compiling class template member function 'hb_vector_t<unsigned int,false>::hb_vector_t(std::initializer_list<Type>)'
        with
        [
            Type=unsigned int
        ]
C:\Users\ACER NITRO\OneDrive\Desktop\DEV\vcpkg\buildtrees\harfbuzz\src\8.0.0-a57fbf2423.clean\src\hb-multimap.hh(54): note: see the first reference to 'hb_vector_t<unsigned int,false>::hb_vector_t' in 'hb_multimap_t::add'
C:\Users\ACER NITRO\OneDrive\Desktop\DEV\vcpkg\buildtrees\harfbuzz\src\8.0.0-a57fbf2423.clean\src\hb-bit-set.hh(285): note: see reference to class template instantiation 'hb_vector_t<unsigned int,false>' being compiled
C:\Users\ACER NITRO\OneDrive\Desktop\DEV\vcpkg\buildtrees\harfbuzz\src\8.0.0-a57fbf2423.clean\src\hb-serialize.hh(628): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
C:\Users\ACER NITRO\OneDrive\Desktop\DEV\vcpkg\buildtrees\harfbuzz\src\8.0.0-a57fbf2423.clean\src\hb-serialize.hh(581): note: see reference to function template instantiation 'Type *hb_serialize_context_t::allocate_size<void>(size_t,bool)' being compiled
        with
        [
            Type=void
        ]
C:\Users\ACER NITRO\OneDrive\Desktop\DEV\vcpkg\buildtrees\harfbuzz\src\8.0.0-a57fbf2423.clean\src\hb-algs.hh(371): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
C:\Users\ACER NITRO\OneDrive\Desktop\DEV\vcpkg\buildtrees\harfbuzz\src\8.0.0-a57fbf2423.clean\src\hb-algs.hh(376): note: see reference to function template instantiation 'unsigned int <unnamed-type-hb_hash>::impl<T>(const T &,hb_priority<0>) const' being compiled
        with
        [
            T=float
        ]
C:\Users\ACER NITRO\OneDrive\Desktop\DEV\vcpkg\buildtrees\harfbuzz\src\8.0.0-a57fbf2423.clean\src\hb-subset-instancer-solver.hh(58): note: see reference to function template instantiation 'unsigned int <unnamed-type-hb_hash>::operator ()<float>(const T &) const' being compiled
        with
        [
            T=float
        ]

**Comment by taneshgyr** [comment]
I have Installed ATL/MFC via the Visual Studio installer.

**Comment by dg0yt** [comment]
What I can say is that 
~~~
C:\Users\ACER NITRO
~~~
will not work with some ports. Avoid vcpkg paths with special characters (` `, `+`, maybe a few more).

**Comment by PhoebeHui** [comment]
Failures:
>
LINK : fatal error LNK1181: cannot open input file 'NITRO\OneDrive\Desktop\DEV\vcpkg\installed\x64-windows\debug\lib\pkgconfig\....\lib.obj'

@taneshgyr, does the problem still persist? have you tried above suggestion?

**Comment by FrankXie05** [comment]
This issue hasn’t been updated for a long time; if it is still an issue, please ping me and I will reopen this issue.
