### ISSUE TITLE
[New Port Request] <morganstanley/modern-cpp-kafka>

### ISSUE THREAD

**Issue by zlojvavan** [microsoft/vcpkg#32897]
### Library name

morganstanley/modern-cpp-kafka

### Library description

The modern-cpp-kafka API is a layer of C++ wrapper based on librdkafka (the C part only), with high quality, but more friendly to users

### Source repository URL

https://github.com/morganstanley/modern-cpp-kafka

**Comment by xiaozhuai** [comment]
Please try #32903 to see if it works or not.

---

You can use following commands to get and apply patches and then install it.

```
curl -Ls https://github.com/microsoft/vcpkg/pull/32903.patch | git apply
vcpkg install libphonenumber:x64-linux
```

---

After this pr got merged, you may want to drop your local changes via
```
git checkout .
git clean -f
```

**Comment by zlojvavan** [comment]
@xiaozhuai 
not quite there yet
I successfully installed it and had to replace kafka includes in my own code by prepending 'modern-cpp-kafka/" there as in #include <modern-cpp-kafka/kafka/Error.h> (was: #include <kafka/Error.h>) but still got numerous compilation errors such as

C:\Project\Libs\vcpkg\installed\x64-windows-static\include\modern-cpp-kafka\kafka\Error.h(3,10): fatal  error C1083: Cannot open include file: 'kafka/Project.h': No such file or directory 

on line 3 (#include <kafka/Project.h>) in Error.h file etc.

**Comment by xiaozhuai** [comment]
@zlojvavan 

Do you use cmake?

**Comment by zlojvavan** [comment]
@xiaozhuai 
not in this project, no
visual studio based project here

**Comment by xiaozhuai** [comment]
@zlojvavan 

> not in this project

Cmake is recommened.

Nevermind, I've update this pr.

Please exec these commands 
```
cd /path/to/vcpkg
vcpkg remove modern-cpp-kafka
git checkout .
git clean -fd
curl -Ls https://github.com/microsoft/vcpkg/pull/32903.patch | git apply
vcpkg install modern-cpp-kafka
```

**Comment by xiaozhuai** [comment]
> never had such problems in several years of using vcpkg though

It did happen.
For example: `libusb`.
The official way (use cmake) is `#include <libusb.h>`
The VS based you need `#include <libusb-1.0/libusb.h>`

**Comment by xiaozhuai** [comment]
> I'm not that fond of idea of manually creating all those projects for cmake

Yes, it would certainly be better to have a unified include path for cmake based and VS based project, but sometimes it requires extra effort, or may not be possible.

**Comment by xiaozhuai** [comment]
> much appreciated

You are welcome!
I'm a vcpkg user like you, and vcpkg solved the package management problems I had in the project very well, so I felt like doing something to give back to the community.
I go through the issue list in my free time and then help people solve problems.

**Comment by xiaozhuai** [comment]
BTW, the CI is much slow. Sometimes it annoys me a little.

**Comment by zlojvavan** [comment]
wonder whether there is any detailed documentation for dummies on creating new vcpkg ports...

btw do you think it's time to close both solved issues now?

**Comment by xiaozhuai** [comment]
> wonder whether there is any detailed documentation for dummies on creating new vcpkg ports...

See https://github.com/microsoft/vcpkg#contributing

> btw do you think it's time to close both solved issues now?

They will be automatic closed once the linked pr got merged.
