### ISSUE TITLE
Add QCA (Qt Cryptographic Architecture)

### ISSUE THREAD

**Issue by gnome71** [Microsoft/vcpkg#329]
[Qt Cryptographic Architecture](http://delta.affinix.com/docs/qca/) QCA aims to provide a straightforward and cross-platform cryptographic API, using Qt datatypes and conventions.

**Comment by gnome71** [comment]
@alexkaratarakis Hello! Could someone explain how I'm supposed to make the PR. I've never done this before, because I'm using my own git server, so I never had to make PRs.
Thanks a lot
Alex

**Comment by sdcb** [comment]
@gnome71 I think there is a tutorial to create new port here:

https://github.com/Microsoft/vcpkg/blob/master/docs/EXAMPLES.md#user-content-example-2-package-a-remote-project-zlib

**Comment by gnome71** [comment]
thanks a lot. I have the port, but to which branch do i have to git push to be able to create the PR here on github.

**Comment by sdcb** [comment]
@gnome71 I submit a PR by: 

Forking the vcpkg (my example here: https://github.com/sdcb/vcpkg)
Make a branch from master
Commit the code and push to github
Make the Pull Request(PR)

There is a detailed document here(MSFT write it):
https://github.com/Microsoft/cppwinrt#user-content-contributing-code

**Comment by gnome71** [comment]
That helps me a lot.
Thank you! :-)

**Comment by ras0219-msft** [comment]
Fixed by #341. Thanks again, @gnome71!
