### ISSUE TITLE
[New Port Request] libaudec

### ISSUE THREAD

**Issue by luzpaz** [microsoft/vcpkg#32905]
### Library name

libaudec

### Library description

ibaudec (lib audio decoder) is a wrapper library over minimp3, sndfile and libsamplerate for reading and resampling audio files

### Source repository URL

https://github.com/zrythm/libaudec

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

> libaudec supports all formats supported by sndfile, in addition to MP3.

> This library is meant to be linked in statically to larger projects.

Tags: https://github.com/zrythm/libaudec/tags
Building: https://github.com/zrythm/libaudec#building

**Comment by luzpaz** [comment]
bump

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
