### ISSUE TITLE
[bzip2] Build error

### ISSUE THREAD

**Issue by sbrosgol** [microsoft/vcpkg#32902]
Copy issue body from /vcpkg/installed/vcpkg/issue_body.md

**Comment by MonicaLiu0311** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report an issue.

**Comment by MonicaLiu0311** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
