### ISSUE TITLE
[New Port Request] opencv4

### ISSUE THREAD

**Issue by TalSomech** [microsoft/vcpkg#32917]
### Library name

opencv4

### Library description

an image-proccessing library

### Source repository URL

https://github.com/opencv/opencv

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

while installing and using opencv i noticed , even in the download files , that the opencv/2/3/4 does not contain the file ximgproc.hpp , but the github file does indeed have it.

**Comment by xiaozhuai** [comment]
Is `#include <opencv2/imgproc/imgproc.hpp>` what you need?

**Comment by dg0yt** [comment]
Try `vcpkg install opencv4[contrib]`.
`opencv2/imgproc.hpp` is in the opencv GH repo and probably part of the `core` feature.
`opencv2/ximgproc.hpp` is in the opencv_contrib GH repo and probably part of the `contrib` feature. It is installed in vcpkg CI.

**Comment by JackBoosY** [comment]
cc @Cheney-W , I think this issue can be closed.
