### ISSUE TITLE
[etcd-cpp-apiv3] build failure

### ISSUE THREAD

**Issue by andreamartini** [microsoft/vcpkg#32918]
### Operating system

Windows 10 Enterprise

### Steps to reproduce the behavior

```Shell
.\vcpkg.exe install etcd-cpp-apiv3:x64-windows
```

### Failure logs

c:\MyPath\vcpkg\vcpkg> .\vcpkg.exe install etcd-cpp-apiv3:x64-windows
Computing installation plan...
A suitable version of cmake was not found (required v3.27.1) Downloading portable cmake 3.27.1...
Downloading cmake...
https://github.com/Kitware/CMake/releases/download/v3.27.1/cmake-3.27.1-windows-i386.zip->C:\MyPath\vcpkg\vcpkg\downloads\cmake-3.27.1-windows-i386.zip
Downloading https://github.com/Kitware/CMake/releases/download/v3.27.1/cmake-3.27.1-windows-i386.zip
Extracting cmake...
The following packages will be built and installed:
    etcd-cpp-apiv3:x64-windows -> 0.15.3
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\myusername\AppData\Local\vcpkg\archives in 668 us. Use --debug to see more details.
Installing 1/1 etcd-cpp-apiv3:x64-windows...
Building etcd-cpp-apiv3:x64-windows...
-- Using cached etcd-cpp-apiv3-etcd-cpp-apiv3-v0.15.3.tar.gz.
-- Cleaning sources at C:/MyPath/vcpkg/vcpkg/buildtrees/etcd-cpp-apiv3/src/v0.15.3-a41b23c27e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/MyPath/vcpkg/vcpkg/downloads/etcd-cpp-apiv3-etcd-cpp-apiv3-v0.15.3.tar.gz
-- Using source at C:/MyPath/vcpkg/vcpkg/buildtrees/etcd-cpp-apiv3/src/v0.15.3-a41b23c27e.clean
CMake Error at ports/etcd-cpp-apiv3/portfile.cmake:9 (vcpkg_cmake_configure):
  Unknown CMake command "vcpkg_cmake_configure".
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)

error: building etcd-cpp-apiv3:x64-windows failed with: BUILD_FAILED
Elapsed time to handle etcd-cpp-apiv3:x64-windows: 746 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+etcd-cpp-apiv3
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[etcd-cpp-apiv3]+Build+error&body=Copy+issue+body+from+C%3A%2FTools%2FWorkspaces%2FDiagnosticSW%2FThird-Party%2Fvcpkg%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

About compiler, on my pc has been installed Visual Studio 2019 (MSVC) but i don't know if vcpkg use other compilers.

**Comment by JonLiu1993** [comment]
The function `vcpkg_cmake_config` depends on `vcpkg-cmake` in `vcpkg.json`, please make sure your json file has not changed.
And please run command `git pull` 、`.\bootstrap-vcpkg.bat`.

```
  Unknown CMake command "vcpkg_cmake_configure".
```
https://github.com/microsoft/vcpkg/blob/980ec0f49d81f794778386f7bd518b2cc9c092f0/ports/etcd-cpp-apiv3/vcpkg.json#L17

**Comment by andreamartini** [comment]
Thank you for your answer.
Unfortunally i have got the same error:

_PS C:\MyPath\vcpkg\vcpkg> .\vcpkg.exe install etcd-cpp-apiv3:x64-windows
Computing installation plan...
The following packages will be built and installed:
    etcd-cpp-apiv3:x64-windows -> 0.15.3
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\MyUserName\AppData\Local\vcpkg\archives in 700 us. Use --debug to see more details.
Installing 1/1 etcd-cpp-apiv3:x64-windows...
Building etcd-cpp-apiv3:x64-windows...
-- Using cached etcd-cpp-apiv3-etcd-cpp-apiv3-v0.15.3.tar.gz.
-- Cleaning sources at C:/MyPath/vcpkg/vcpkg/buildtrees/etcd-cpp-apiv3/src/v0.15.3-a41b23c27e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/MyPath/vcpkg/vcpkg/downloads/etcd-cpp-apiv3-etcd-cpp-apiv3-v0.15.3.tar.gz
-- Using source at C:/MyPath/vcpkg/vcpkg/buildtrees/etcd-cpp-apiv3/src/v0.15.3-a41b23c27e.clean
CMake Error at ports/etcd-cpp-apiv3/portfile.cmake:9 (vcpkg_cmake_configure):
  Unknown CMake command "vcpkg_cmake_configure".
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)


error: building etcd-cpp-apiv3:x64-windows failed with: BUILD_FAILED
Elapsed time to handle etcd-cpp-apiv3:x64-windows: 593 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+etcd-cpp-apiv3
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[etcd-cpp-apiv3]+Build+error&body=Copy+issue+body+from+C%3A%2FTools%2FWorkspaces%2FDiagnosticSW%2FThird-Party%2Fvcpkg%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md_


I checked for vcpkg.json and for line 17. It appears as following:

```
{
  "name": "etcd-cpp-apiv3",
  "version": "0.15.3",
  "description": "The etcd-cpp-apiv3 is a C++ API for etcd's v3 client API, i.e., ETCDCTL_API=3.",
  "homepage": "https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3",
  "license": "BSD-3-Clause",
  "dependencies": [
    "boost-asio",
    "boost-random",
    "boost-system",
    "boost-thread",
    "cpprestsdk",
    "grpc",
    "openssl",
    "protobuf",
    {
      "name": "vcpkg-cmake",
      "host": true
    },
    {
      "name": "vcpkg-cmake-config",
      "host": true
    }
  ]
}

```
I executed both "git pull" and ".\bootstrap-vcpkg.bat":

_PS C:\MyPath\vcpkg\vcpkg> git pull
Already up to date.
PS C:\MyPath\vcpkg\vcpkg> .\bootstrap-vcpkg.bat
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2023-07-19/vcpkg.exe -> C:\MyPath\vcpkg\vcpkg\vcpkg.exe... done.
Validating signature... done.

vcpkg package management program version 2023-07-19-814b7ec837b59f1c8778f72351c1dd7605983cd2

See LICENSE.txt for license information.
Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md_

**Comment by dg0yt** [comment]
> The function `vcpkg_cmake_config` depends on `vcpkg-cmake` in `vcpkg.json`, please make sure your json file has not changed.

This isn't helpful.

> And please run command `git pull` 、`.\bootstrap-vcpkg.bat`.

What you really need to run is:
~~~
.\vcpkg upgrade
~~~
and when you are happy with it:
~~~
.\vcpkg upgrade --no-dry-run
~~~
Alternatively, you can try:
~~~
.\vcpkg remove --recurse vcpkg-cmake
~~~

Long story short, the error indicates that your *installed* `vcpkg-cmake` is outdated.

**Comment by JonLiu1993** [comment]
@andreamartini, does this problem still exist?

**Comment by JonLiu1993** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
