### ISSUE TITLE
[g2o] build failure

### ISSUE THREAD

**Issue by yinchi447** [microsoft/vcpkg#32911]
### Operating system

x64-Windows

### Compiler

VS2019

### Steps to reproduce the behavior

```Shell
build with "vcpkg.json":

{
  "name": "project",
  "version-semver": "1.0.0",
  "dependencies": [
    "g2o"
  ],
  "builtin-baseline": "0895a813036f4d189e2bdd1b62741744614347b4",
  "overrides": [
    {
      "name": "g2o",
      "version-string": "20170730_git"
    }
  ]
}
```

### Failure logs

Build started...
1>------ Build started: Project: pose_graph_g2o_SE3, Configuration: Debug x64 ------
1>Installing vcpkg dependencies to C:\Users\10986\Desktop\pose_graph\pose_graph_g2o_SE3\pose_graph_g2o_SE3\vcpkg_installed\x64-windows\
1>"D:\vcpkg\vcpkg\vcpkg.exe" install  --x-wait-for-lock --triplet "x64-windows" --vcpkg-root "D:\vcpkg\vcpkg\\" "--x-manifest-root=C:\Users\10986\Desktop\pose_graph\pose_graph_g2o_SE3\pose_graph_g2o_SE3\\" "--x-install-root=C:\Users\10986\Desktop\pose_graph\pose_graph_g2o_SE3\pose_graph_g2o_SE3\vcpkg_installed\x64-windows\\"
1>Detecting compiler hash for triplet x64-windows...
1>-- Automatically setting HTTP(S)_PROXY environment variables to "127.0.0.1:7890".
1>The following packages will be built and installed:
1>  * ceres:x64-windows -> 2.1.0#4 -- D:\vcpkg\vcpkg\buildtrees\versioning_\versions\ceres\b2ebeb85c8833b2631210c4b790204151e402981
1>  * clapack:x64-windows -> 3.2.1#22 -- D:\vcpkg\vcpkg\buildtrees\versioning_\versions\clapack\0736bfcd19b6aaa7f1c75c10122433d4b4cc50a9
1>    g2o:x64-windows -> 20170730_git -- D:\vcpkg\vcpkg\buildtrees\versioning_\versions\g2o\72ea0e28f85e20e62aa30a045d9672c6c50b595d
1>  * gflags:x64-windows -> 2.2.2#7 -- D:\vcpkg\vcpkg\buildtrees\versioning_\versions\gflags\1c57a920065312afe80b1b8a3595f82005da61ee
1>  * glog:x64-windows -> 0.6.0#2 -- D:\vcpkg\vcpkg\buildtrees\versioning_\versions\glog\cce45164ee522a505686c1794e7c228e44f52d76
1>  * lapack:x64-windows -> 2022-02-22#2 -- D:\vcpkg\vcpkg\buildtrees\versioning_\versions\lapack\7c892b58c70ebc7d83444c4e727272cad40e28c2
1>  * lapack-reference[blas-select,core,noblas]:x64-windows -> 3.11.0#1 -- D:\vcpkg\vcpkg\buildtrees\versioning_\versions\lapack-reference\d71a74d50d88f3cf337d7cefccadcb192e7d12ab
1>  * suitesparse:x64-windows -> 5.8.0#2 -- D:\vcpkg\vcpkg\buildtrees\versioning_\versions\suitesparse\fb26833d46e56ee2e9986294be860acc1e81c074
1>Additional packages (*) will be modified to complete this operation.
1>Restored 4 package(s) from D:\vcpkg\BinaryCache in 283 ms. Use --debug to see more details.
1>Installing 1/8 lapack-reference:x64-windows...
1>Elapsed time to handle lapack-reference:x64-windows: 30.8 ms
1>Installing 2/8 lapack:x64-windows...
1>Elapsed time to handle lapack:x64-windows: 21.3 ms
1>Installing 3/8 suitesparse:x64-windows...
1>Elapsed time to handle suitesparse:x64-windows: 78.1 ms
1>Installing 4/8 clapack:x64-windows...
1>D:\vcpkg\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(183,5): warning : error: The following files are already installed in C:/Users/10986/Desktop/pose_graph/pose_graph_g2o_SE3/pose_graph_g2o_SE3/vcpkg_installed/x64-windows/x64-windows and are in conflict with clapack:x64-windows
1>Installed by lapack-reference:x64-windows
1>lib/lapack.lib
1>    share/lapack/FindLAPACK.cmake
1>    share/lapack/vcpkg-cmake-wrapper.cmake
1>
1>Elapsed time to handle clapack:x64-windows: 18 ms
1>Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
1>Then check for known issues at:
1>    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+clapack
1>You can submit a new issue at:
1>    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[clapack]+Build+error
1>Include '[clapack] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
1>    vcpkg-tool version: 2023-07-19-814b7ec837b59f1c8778f72351c1dd7605983cd2
1>    vcpkg-scripts version: 0895a8130 2023-08-01 (33 hours ago)
1>
1>
1>D:\vcpkg\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(183,5): error MSB3073: The command ""D:\vcpkg\vcpkg\vcpkg.exe" install  --x-wait-for-lock --triplet "x64-windows" --vcpkg-root "D:\vcpkg\vcpkg\\" "--x-manifest-root=C:\Users\10986\Desktop\pose_graph\pose_graph_g2o_SE3\pose_graph_g2o_SE3\\" "--x-install-root=C:\Users\10986\Desktop\pose_graph\pose_graph_g2o_SE3\pose_graph_g2o_SE3\vcpkg_installed\x64-windows\\" " exited with code 1.
1>Done building project "pose_graph_g2o_SE3.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

### Additional context

When I built g2o-20170730_git, vcpkg would build clapck and lapck-reference which are conflict with the other. I'd like to know what can I do to solve this problem and bulid g2o-20170730_git.

**Comment by xiaozhuai** [comment]
> 1>D:\vcpkg\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(183,5): warning : error: The following files are already installed in C:/Users/10986/Desktop/pose_graph/pose_graph_g2o_SE3/pose_graph_g2o_SE3/vcpkg_installed/x64-windows/x64-windows and are in conflict with clapack:x64-windows
1>Installed by lapack-reference:x64-windows
1>lib/lapack.lib
1> share/lapack/FindLAPACK.cmake
1> share/lapack/vcpkg-cmake-wrapper.cmake

**Comment by LilyWangLL** [comment]
> When I built g2o-20170730_git, vcpkg would build clapck and lapck-reference which are conflict with the other. I'd like to know what can I do to solve this problem and bulid g2o-20170730_git.

If you want use `g2o-20170730_git`, please also use old `suitesparse`. Due to `g2o-20170730_git` depends on `clapack`, but the latest `suitesparse` depends on `lapck-reference`. So your project will install `clapack` and `lapck-reference` at the same time.

Please use old `suitesparse` as below:
```
{
  "name": "project",
  "version-semver": "1.0.0",
  "dependencies": [
    "g2o",
    "suitesparse"
  ],
  "builtin-baseline": "0895a813036f4d189e2bdd1b62741744614347b4",
  "overrides": [
    {
      "name": "g2o",
      "version-string": "20170730_git"
    },
    {
        "name": "suitesparse",
        "version": "5.4.0-3"
    }
  ]
}

```

**Comment by yinchi447** [comment]
Thank you very much for your eager help, my problem was solved.
