### ISSUE TITLE
[gmp] Build error

### ISSUE THREAD

**Issue by pvsantos999** [microsoft/vcpkg#32910]
Copy issue body from C:/progs/dev/vcpkg/installed/vcpkg/issue_body.md

Error during installation of gmp:x64-windows using vcpkg

PS C:\progs\dev\vcpkg> ./vcpkg install --triplet x64-windows gmp
Computing installation plan...
The following packages will be built and installed:
    gmp[core]:x64-windows -> 6.2.1#20
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\Santos\AppData\Local\vcpkg\archives in 733 us. Use --debug to see more details.
Installing 1/1 gmp:x64-windows...
Building gmp[core]:x64-windows...
-- Using cached gmp-6.2.1.tar.xz.
-- Cleaning sources at C:/progs/dev/vcpkg/buildtrees/gmp/src/v6.2.1-0c723d4b6f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/progs/dev/vcpkg/downloads/gmp-6.2.1.tar.xz
-- Applying patch asmflags.patch
-- Applying patch cross-tools.patch
-- Applying patch subdirs.patch
-- Applying patch msvc_symbol.patch
-- Applying patch arm64-coff.patch
-- Applying patch gmp-arm64-asm-fix-5f32dbc41afc.patch
-- Using source at C:/progs/dev/vcpkg/buildtrees/gmp/src/v6.2.1-0c723d4b6f.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Using cached LLVM-15.0.6-win64.7z.exe.
-- Using cached 7z1900.msi.
T?h?i?s? ?i?n?s?t?a?l?l?a?t?i?o?n? ?p?a?c?k?a?g?e? ?c?o?u?l?d? ?n?o?t? ?b?e? ?o?p?e?n?e?d?.? ? ?C?o?n?t?a?c?t? ?t?h?e? ?a?p?p?l?i?c?a?t?i?o?n? ?v?e?n?d?o?r? ?t?o? ?v?e?r?i?f?y? ?t?h?a?t? ?t?h?i?s? ?i?s? ?a? ?v?a?l?i?d? ?W?i?n?d?o?w?s? ?I?n?s?t?a?l?l?e?r? ?p?a?c?k?a?g?e?.?
?CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:244 (message):
  Unable to find 7Z
Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:211 (vcpkg_find_acquire_program)
  ports/gmp/portfile.cmake:57 (vcpkg_find_acquire_program)
  scripts/ports.cmake:147 (include)

error: building gmp:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+gmp
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[gmp]+Build+error&body=Copy+issue+body+from+C%3A%2Fprogs%2Fdev%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by Cheney-W** [comment]
I can't reproduce this issue with latest `vcpkg 2023-07-19-814b7ec837b59f1c8778f72351c1dd7605983cd2`.
```
PS F:\vcpkg> .\vcpkg.exe install gmp:x64-windows --editable
Computing installation plan...
The following packages will be built and installed:
    gmp:x64-windows -> 6.2.1#20
Installing 1/1 gmp:x64-windows...
Building gmp:x64-windows...
-- Downloading https://ftpmirror.gnu.org/gmp/gmp-6.2.1.tar.xz;https://ftp.gnu.org/gnu/gmp/gmp-6.2.1.tar.xz;https://gmplib.org/download/gmp/gmp-6.2.1.tar.xz -> gmp-6.2.1.tar.xz...
-- Extracting source F:/vcpkg/downloads/gmp-6.2.1.tar.xz
-- Applying patch asmflags.patch
-- Applying patch cross-tools.patch
-- Applying patch subdirs.patch
-- Applying patch msvc_symbol.patch
-- Applying patch arm64-coff.patch
-- Applying patch gmp-arm64-asm-fix-5f32dbc41afc.patch
-- Using source at F:/vcpkg/buildtrees/gmp/src/v6.2.1-0c723d4b6f
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Getting CMake variables for x64-windows
-- Using cached msys2-autoconf-wrapper-20221207-1-any.pkg.tar.zst.
-- Using cached msys2-automake-wrapper-20221207-1-any.pkg.tar.zst.
-- Using cached msys2-binutils-2.40-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libtool-2.4.7-3-x86_64.pkg.tar.zst.
-- Using cached msys2-make-4.4.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-pkgconf-1.9.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-which-2.21-4-x86_64.pkg.tar.zst.
-- Using cached msys2-bash-5.2.015-1-x86_64.pkg.tar.zst.
-- Using cached msys2-coreutils-8.32-5-x86_64.pkg.tar.zst.
-- Using cached msys2-file-5.44-5-x86_64.pkg.tar.zst.
-- Using cached msys2-gawk-5.2.1-2-x86_64.pkg.tar.zst.
-- Using cached msys2-grep-1~3.0-6-x86_64.pkg.tar.zst.
-- Using cached msys2-gzip-1.12-2-x86_64.pkg.tar.zst.
-- Using cached msys2-diffutils-3.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-sed-4.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using cached msys2-autoconf2.71-2.71-1-any.pkg.tar.zst.
-- Using cached msys2-automake1.16-1.16.5-1-any.pkg.tar.zst.
-- Using cached msys2-libiconv-1.17-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libintl-0.21-2-x86_64.pkg.tar.zst.
-- Using cached msys2-zlib-1.2.13-1-x86_64.pkg.tar.zst.
-- Using cached msys2-tar-1.34-3-x86_64.pkg.tar.zst.
-- Using cached msys2-findutils-4.9.0-3-x86_64.pkg.tar.zst.
-- Using cached msys2-gmp-6.2.1-2-x86_64.pkg.tar.zst.
-- Using cached msys2-gcc-libs-11.3.0-3-x86_64.pkg.tar.zst.
-- Using cached msys2-libbz2-1.0.8-4-x86_64.pkg.tar.zst.
-- Using cached msys2-liblzma-5.4.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libzstd-1.5.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libreadline-8.2.001-3-x86_64.pkg.tar.zst.
-- Using cached msys2-mpfr-4.2.0-2-x86_64.pkg.tar.zst.
-- Using cached msys2-libpcre-8.45-3-x86_64.pkg.tar.zst.
-- Using cached msys2-m4-1.4.19-2-x86_64.pkg.tar.zst.
-- Using cached msys2-perl-5.36.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-ncurses-6.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libcrypt-2.1-4-x86_64.pkg.tar.zst.
-- Using msys root at F:/vcpkg/downloads/tools/msys2/d7266db249278763
-- Generating configure for x64-windows
-- Finished generating configure for x64-windows
-- Using cached mingw-w64-i686-pkgconf-1~1.8.0-2-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using msys root at F:/vcpkg/downloads/tools/msys2/6f3fa1a12ef85a6f
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
-- Installing x64-windows-dbg
-- Building x64-windows-rel
-- Installing x64-windows-rel
-- Fixing pkgconfig file: F:/vcpkg/packages/gmp_x64-windows/lib/pkgconfig/gmp.pc
-- Fixing pkgconfig file: F:/vcpkg/packages/gmp_x64-windows/lib/pkgconfig/gmpxx.pc
-- Fixing pkgconfig file: F:/vcpkg/packages/gmp_x64-windows/debug/lib/pkgconfig/gmp.pc
-- Fixing pkgconfig file: F:/vcpkg/packages/gmp_x64-windows/debug/lib/pkgconfig/gmpxx.pc
-- Installing: F:/vcpkg/packages/gmp_x64-windows/manual-tools/gmp/gen-bases.exe
-- Installing: F:/vcpkg/packages/gmp_x64-windows/manual-tools/gmp/gen-fac.exe
-- Installing: F:/vcpkg/packages/gmp_x64-windows/manual-tools/gmp/gen-fib.exe
-- Installing: F:/vcpkg/packages/gmp_x64-windows/manual-tools/gmp/gen-jacobitab.exe
-- Installing: F:/vcpkg/packages/gmp_x64-windows/manual-tools/gmp/gen-psqr.exe
-- Installing: F:/vcpkg/packages/gmp_x64-windows/manual-tools/gmp/gen-trialdivtab.exe
-- Installing: F:/vcpkg/packages/gmp_x64-windows/share/gmp/usage
-- Performing post-build validation
Elapsed time to handle gmp:x64-windows: 32 min
Total install time: 32 min
The package gmp can be imported via CMake FindPkgConfig module:

    #  gmp
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(gmp REQUIRED IMPORTED_TARGET gmp)
    target_link_libraries(main PkgConfig::gmp)

    # gmpxx
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(gmpxx REQUIRED IMPORTED_TARGET gmpxx)
    target_link_libraries(main PkgConfig::gmpxx)
```

**Comment by dg0yt** [comment]
No matter why the 7zip msi installation failed:
The gmp port wants to use the llvm clang which you can add with the Visual Studio installer, not the original llvm.

**Comment by pvsantos999** [comment]
Hi,
thanks for the tip: it now works after the installation of the C++ Clang
compiler and of MSbuild Support for LLVM in visual studio.
Best regards

**Comment by Cheney-W** [comment]
Thanks for dg0yt's comment.
