### ISSUE TITLE
Memory leak while developing Vcpkg

### ISSUE THREAD

**Issue by MathiasMagnus** [microsoft/vcpkg#3292]
### Brief Issue Summary

There is memory leak I suspect somewhere in the way `vcpkg.exe` invokes CMake. Memory consumption of a `cmake.exe` process grows without limit to a point where it takes Windows with it. This only happens when I'm developing Vcpkg portfiles. Can be an issue with Vcpkg or just the workflow.

### Reproduce:

![image](https://user-images.githubusercontent.com/9763499/39123734-07cb2290-46f9-11e8-9fb8-f47c89b19de2.png)

_(Important bits are Task Manager and the Task Bar)_

Notice how there's no VS Code window open, it's already been closed, but there is both a `code.exe` and a `cmake.exe` process running and it's gobbling up memory. If I kill off CMake VS Code terminates as well, so apparently that is what's keeping Code alive.

Standard workflow is:

1. Create a branch (to cook up a branch)
2. Start modifying one of the gazillion CMake scripts (`portfile.cmake` inside the `ports` dir)
3. From the integrated terminal (I'm using PowerShell, but that should really not matter) issue vcpkg commands. This is usually testing the portfile that is under development. (install/remove/install/remove)
4. If one wants a clean rebuild, one has to delete the `buildtrees/<packagename>` folder after `vcpkg.exe remove` and before `vcpkg.exe install`.

At this point, it often happens that one cannot delete the buildtrees folder, because some process is holding it open. I suspect this is the rogue `cmake.exe` process that takes down the system in time.

How would you got about debugging this?

**Comment by linquize** [comment]
Is it still valid with the latest vcpkg?

**Comment by MathiasMagnus** [comment]
The issue is most likely linked to the cmake-tools extension anyway, so feel free to close the issue. I've not had to update portfiles in a while (I ported largely abandoned projects), but will reopen if the issue persists.
