### ISSUE TITLE
[xerces-c] Build error : NOTFOUND transcoder unavailable on Android

### ISSUE THREAD

**Issue by davesworking** [microsoft/vcpkg#32964]
CMake Error at cmake/XercesTranscoderSelection.cmake:97 (message):
  NOTFOUND transcoder unavailable
Call Stack (most recent call first):
  CMakeLists.txt:114 (include)

-- Configuring incomplete, errors occurred!
See also "/Build/Android/android-23-clang11.0/vcpkg/buildtrees/xerces-c/arm64-android-rel/CMakeFiles/CMakeOutput.log".
See also "/Build/Android/android-23-clang11.0/vcpkg/buildtrees/xerces-c/arm64-android-rel/CMakeFiles/CMakeError.log".
ninja: build stopped: subcommand failed.

**Comment by dg0yt** [comment]
`vcpkg install xerces-c:arm64-android` works with NDK 23, arm64-android, up-to-date vcpkg repo.
Can't do more for the sparse bug report. #30604

**Comment by davesworking** [comment]
vcpkg/issue_body.md doesn't exist after running the build
however, I picked up the latest SHA with a Xerces-c fix and the build is working (6359494ca1b34423786da18365f9d79963b0340a)

**Comment by dg0yt** [comment]
> I picked up the latest SHA with a Xerces-c fix and the build is working ([6359494](https://github.com/microsoft/vcpkg/commit/6359494ca1b34423786da18365f9d79963b0340a))

... and that's the port update which enabled android support.

> vcpkg/issue_body.md doesn't exist after running the build

Run `vcpkg-bootstrap.sh` after repo updates.
