### ISSUE TITLE
[LibRaw] Linking error with libraw--undefined symbol

### ISSUE THREAD

**Issue by jurplel** [microsoft/vcpkg#32967]
**Describe the bug**
When building an external project, there are linking errors when linking with `libraw` from `vcpkg`. 

**Environment**
- OS: Linux/macOS
- Compiler: clang 14.0.3 on macOS, also happening on 4:9.3.0-1ubuntu2 and other versions

**To Reproduce**
1. ./vcpkg install libraw
2. Attempt to build `kimageformats` (which depends on `libraw`).
3. Encounter linking errors.

To streamline reproducing this, [clone this repo](https://github.com/jurplel/kimageformats-binaries), checkout `eceda664c72af86e18fa778d1435a10cec745b9b`, and run `pwsh/buildkimageformats.ps1`  I was able to reproduce this locally on macOS with this method.

**Expected behavior**
Linking without errors.

**Failure logs**
https://pastebin.mozilla.org/TSiLaG4k
Or you can find the full log on Github Actions below as linked below.

**Additional context**
Looks like the same issue as https://github.com/microsoft/vcpkg/issues/22298.

This is [occuring on Github Actions](https://github.com/jurplel/kimageformats-binaries/actions/runs/5765030773/job/15630187249) as I am trying to make build scripts.

**Comment by dg0yt** [comment]
This isn't a vcpkg issue but a limitation of kimageformats `cmake/find-modules/FindLibRaw.cmake`: It is unable to provide the link libraries needed to use vcpg's `libraw.a` for the static x64-linux triplet.
Port libraw provides cmake config and pkgconfig pc files. You need to make kimageformats use one of this, during build and in exported config.

**Comment by jurplel** [comment]
Okay, I made [this patch](https://github.com/jurplel/kimageformats-binaries/blob/f3a043913419ebd1ac4d059e5a99bf005d5c656a/util/kimageformats-find-libraw-vcpkg.patch) for the cmake file and was able to fix this. The include path was wrong though--it was `vcpkg/installed/arm64-osx/libraw` instead of `vcpkg/installed/arm64-osx/lib/libraw`. Not sure if that is because of `vcpkg` or not.

**Comment by dg0yt** [comment]
> Okay, I made [this patch](https://github.com/jurplel/kimageformats-binaries/blob/f3a043913419ebd1ac4d059e5a99bf005d5c656a/util/kimageformats-find-libraw-vcpkg.patch) for the cmake file and was able to fix this. The include path was wrong though--it was `vcpkg/installed/arm64-osx/libraw` instead of `vcpkg/installed/arm64-osx/lib/libraw`. Not sure if that is because of `vcpkg` or not.

The patch looks good, similar to what we often use in vcpkg. You may use
~~~
find_package(LibRaw NAMES libraw REQUIRED)
~~~
to get the exected `LibRaw_FOUND`.

The include path issue is a real bug IMO and needs to be fixed in the port.

**Comment by jurplel** [comment]
Thank you for your work fixing the issue upstream!
