### ISSUE TITLE
[vulkan-hpp] make vulkan-hpp actually fetch all of Vulkan-Hpp

### ISSUE THREAD

**Issue by qbojj** [microsoft/vcpkg#32970]
### Is your feature request related to a problem? Please describe.

It looks like [vulkan-hpp] is only copying `vulkan/vulkan.hpp` into the package but in reality it consists of multiple files, and the only reason why including other files from Vulkan-Hpp works is that VulkanSDK is (most probably) in default include path (/usr/lib/include/ or such) and it itself contains other Vulkan-Hpp headers.

Also those headers require <vulkan/vulkan.h> to be visible, but the package doesn't guaranee it (again... relaying on VulkanSDK being in some default include path).

Also [vulkan-headers] already have contents of Vulkan-Hpp repository (linking to Vulkan::Headers) (same with [vulkan]) so why would this package even exist?

### Proposed solution

Just deprecate this package to reduce possible problems.

All packages that are currently dependent on this package should depend on [vulkan-headers] or [vulkan] and link to Vulkan::Headers which already contains Vulkan-Hpp headers and doesn't cause problems with VulkanSDK already installed on the system.

There are no packages currently in vcpkg that depend on [vulkan-hpp] so no changes in vcpkg ports are needed to be made.

I will make it a forwarder to [vulkan-headers] (to guarantee a correct header version) and message users when installing this package.

### Describe alternatives you've considered

1. Just doing no-op because Vulkan-Hpp is already in VulkanSDK and so [vulkan] package and just changing the `usage` file, but than again why would this package even exist, VulkanSDK from FindVulkan already has Vulkan::Headers.

### Additional context

You can see what I am talking about just by doing:
```cmake
cmake_minimum_required(VERSION 3.8)
set(CMAKE_TOOLCHAIN_FILE "${CMAKE_CURRENT_SOURCE_DIR}/vcpkg/scripts/buildsystems/vcpkg.cmake" CACHE STRING "Vcpkg toolchain file")
project(test CXX)

find_path(VULKAN_HPP_INCLUDE_DIRS "vulkan/vulkan.hpp")
find_path(VULKAN_HPP_RAII_INCLUDE_DIRS "vulkan/vulkan_raii.hpp")
find_path(VULKAN_H_INCLUDE_DIRS "vulkan/vulkan.h")

message("Vulkan hpp path: ${VULKAN_HPP_INCLUDE_DIRS}")
message("Vulkan hpp-raii path: ${VULKAN_HPP_RAII_INCLUDE_DIRS}")
message("Vulkan h path: ${VULKAN_H_INCLUDE_DIRS}")
```

note that `vulkan/vulkan.hpp` requires `vulkan/vulkan.h` to be present and that vulkan_raii.hpp is also a part of Vulkan-Hpp

**Comment by traversebitree** [comment]
Please add something like "`vulkan-headers` already contains `vulkan-hpp`" to the description of `vulkan-hpp`, instead of just showing `deprecated`.
![image](https://github.com/microsoft/vcpkg/assets/30373236/aed5ebc3-f050-4449-ae1d-e87761b57bef)
