### ISSUE TITLE
[gtk-3] [gtk] glib-compile-schemas should run after install 

### ISSUE THREAD

**Issue by Febbe** [microsoft/vcpkg#33037]
### Is your feature request related to a problem? Please describe.

When installing gtk and gtk-3 the file `gschemas.compiled` is not correctly generated and only those schemes are integrated, which are installed by gtk4 (gtk package).

### Proposed solution

 `glib-compile-schemas` should run at the integrate step, after all files are copied (from both gtk-3 and gtk4)

### Describe alternatives you've considered

Run it by myself after `.\vcpkg.exe integrate install`

**Comment by dg0yt** [comment]
https://github.com/microsoft/vcpkg/pull/33253#pullrequestreview-1586207522

**Comment by dg0yt** [comment]
FTR the bug reports is valid, but I believe that the resolution is to not install any `gschemas.compiled`.

**Comment by Febbe** [comment]
You mean, because there is no hook for the integrate step, and it is not solvable in a well-defined manner?

**Comment by dg0yt** [comment]
It is not about the "integrate" step which is unrelated to package installation.
It would need a hook *after* package installations. But installations from cached artifacts are basically just unpacking some ZIP.

**Comment by Febbe** [comment]
Right, after any installation, the cache must be updated.
Btw. `$<install_dir>\lib\gdk-pixbuf-2.0\2.10.0` `\` `loaders\*` and `loaders.cache` is also affected.
I recently opened an issue, that gtk-3 does not load svg's the reason is, that the contents of the loader directory was empty (`pixbufloader-svg.dll` has been istalled to bin, instead of `$<install_dir>\lib\gdk-pixbuf-2.0\2.10.0\loaders\`) and the corresponding `loaders.cache` was not recreated _at_ the installation step.

**Comment by LilyWangLL** [comment]
> FTR the bug reports is valid, but I believe that the resolution is to not install any `gschemas.compiled`.

I updated my change and disable install `gschemas.compiled` by gtk.

**Comment by dg0yt** [comment]
BTW if vcpkg would use `DESTDIR` with meson install, `gnome.post_install()` would not run any of the cache update scripts.
https://mesonbuild.com/Gnome-module.html#gnomepost_install
