### ISSUE TITLE
./bootstrap-vcpkg.sh  does not build vcpkg on  WSL

### ISSUE THREAD

**Issue by rajnishc8** [Microsoft/vcpkg#3303]
Below is the output of ./bootstrap-vcpkg.sh 

rajnish@Audi-A10:/mnt/c/proj/vcpkg$  ./bootstrap-vcpkg.sh
Downloading cmake...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 32.6M  100 32.6M    0     0  1140k      0  0:00:29  0:00:29 --:--:-- 1494k
Downloading cmake... done.
Extracting cmake...
Extracting cmake... done.
Downloading ninja...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   604    0   604    0     0    270      0 --:--:--  0:00:02 --:--:--   270
100 77854  100 77854    0     0  18950      0  0:00:04  0:00:04 --:--:--  172k
Downloading ninja... done.
Extracting ninja...
Extracting ninja... done.
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-6
-- Check for working CXX compiler: /usr/bin/g++-6 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/c/proj/vcpkg/toolsrc/build.rel
[10/59] Building CXX object CMakeFiles/vcpkg.dir/src/vcpkg/binaryparagraph.cpp.o
FAILED: CMakeFiles/vcpkg.dir/src/vcpkg/binaryparagraph.cpp.o
/usr/bin/g++-6  -DDISABLE_METRICS=0 -I../include -O3 -DNDEBUG   -std=c++1z -pthread -MD -MT CMakeFiles/vcpkg.dir/src/vcpkg/binaryparagraph.cpp.o -MF CMakeFiles/vcpkg.dir/src/vcpkg/binaryparagraph.cpp.o.d -o CMakeFiles/vcpkg.dir/src/vcpkg/binaryparagraph.cpp.o -c ../src/vcpkg/binaryparagraph.cpp
../src/vcpkg/binaryparagraph.cpp:27:5: error: function ‘vcpkg::BinaryParagraph::BinaryParagraph()’ defaulted on its redeclaration with an exception-specification that differs from the implicit exception-specification ‘’
     BinaryParagraph::BinaryParagraph() noexcept = default;
     ^~~~~~~~~~~~~~~
[15/59] Building CXX object CMakeFiles/vcpkg.dir/src/vcpkg/commands.autocomplete.cpp.o
ninja: build stopped: subcommand failed.
cp: cannot stat ‘/mnt/c/proj/vcpkg/toolsrc/build.rel/vcpkg’: No such file or directory
rajnish@Audi-A10:/mnt/c/proj/vcpkg$ 

Thanks,
--Rajnish Chauhan

**Comment by jclay** [comment]
I was able to build successfully on Ubuntu just now. I'm using GCC 7 as compared to your GCC 6, but I doubt that is causing the issue.

It looks like you're building on the "mounted" windows volume. What if you try building on the Linux filesystem? The Linux user's home folder for instance.

You may also try `git pull && git reset HEAD --hard` and try the build again. I know the Microsoft team fixed a few things in the bootstrap script earlier.

**Comment by alexkaratarakis** [comment]
I can't seem to repro this issue with g++-6 or g++-7.

Since the compiler seems to be complaining, you can try installing g++-7 like this:
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
sudo apt-get update -y
sudo apt-get install g++-7 -y
```
(this is in fact suggested by bootstrap if no g++ >= 6 is found, but in your case something was found)

Then run bootstrap again (g++-7 will be preferred over g++-6).

**Comment by rajnishc8** [comment]
Update to g++-7 using steps below , still got error.
sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
sudo apt-get update -y
sudo apt-get install g++-7 -y

rajnish@Audi-A10:/mnt/c/proj/vcpkg$ ./bootstrap-vcpkg.sh
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-7
-- Check for working CXX compiler: /usr/bin/g++-7 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/c/proj/vcpkg/toolsrc/build.rel
[11/59] Building CXX object CMakeFiles/vcpkg.dir/src/vcpkg/binaryparagraph.cpp.o
FAILED: CMakeFiles/vcpkg.dir/src/vcpkg/binaryparagraph.cpp.o
/usr/bin/g++-7  -DDISABLE_METRICS=0 -I../include -O3 -DNDEBUG   -std=c++1z -pthread -MD -MT CMakeFiles/vcpkg.dir/src/vcpkg/binaryparagraph.cpp.o -MF CMakeFiles/vcpkg.dir/src/vcpkg/binaryparagraph.cpp.o.d -o CMakeFiles/vcpkg.dir/src/vcpkg/binaryparagraph.cpp.o -c ../src/vcpkg/binaryparagraph.cpp
../src/vcpkg/binaryparagraph.cpp:27:5: error: function ‘vcpkg::BinaryParagraph::BinaryParagraph()’ defaulted on its redeclaration with an exception-specification that differs from the implicit exception-specification ‘’
     BinaryParagraph::BinaryParagraph() noexcept = default;
     ^~~~~~~~~~~~~~~
[16/59] Building CXX object CMakeFiles/vcpkg.dir/src/vcpkg/commands.ci.cpp.o
ninja: build stopped: subcommand failed.
cp: cannot stat ‘/mnt/c/proj/vcpkg/toolsrc/build.rel/vcpkg’: No such file or directory

Thanks.

**Comment by rajnishc8** [comment]
Did 'git pull' again. Then build was successful.

rajnish@Audi-A10:/mnt/c/proj/vcpkg$ ./bootstrap-vcpkg.sh
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-7
-- Check for working CXX compiler: /usr/bin/g++-7 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/c/proj/vcpkg/toolsrc/build.rel
[59/59] Linking CXX executable vcpkg

Thanks.
