### ISSUE TITLE
vcpkg creates multiple triplets for packages with no reason.

### ISSUE THREAD

**Issue by kreuzerkrieg** [microsoft/vcpkg#33040]
Added a custom triplet and toolchain to build with clang and now I see in the CLion the following output

> /snap/clion/248/bin/cmake/linux/x64/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=/snap/clion/248/bin/ninja/linux/x64/ninja -DCMAKE_C_COMPILER=/usr/bin/clang-16 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-16 -DCMAKE_INSTALL_PREFIX=./install -DENABLE_TESTS=ON -DUSE_GTEST=ON -DVCPKG_TARGET_TRIPLET=x64-linux-clang16 -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/user/.clion-vcpkg/vcpkg/scripts/toolchains/linux-clang16.cmake -DCMAKE_TOOLCHAIN_FILE=/home/user/.clion-vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake -G Ninja -S /home/user/Development/project -B /home/user/Development/project/cmake-build-debug-clang16
> -- Running vcpkg install
> Loading dependency information for 113 packages...
> Detecting compiler hash for triplet x64-linux...
> Detecting compiler hash for triplet x64-linux-clang16...

and it created some of the packages for x64-linux triplet and some for x64-linux-clang16

**Environment**
- OS: Ubuntu 22.04
- Compiler: clang-16

**Additional context**
Not sure it is related, but I see the output when running package restoration from CLion. When executing the same command from command line I see the same problem, so I guess CLion is not related to it. Rerun with system `cmake` instead of CLion bundled and got the same

> Loading dependency information for 113 packages...
> Detecting compiler hash for triplet x64-linux...
> Detecting compiler hash for triplet x64-linux-clang16...

So, I guess it some vcpkg bug. Just let me know if you need any additional input
This problem may be related to this [issue](https://github.com/microsoft/vcpkg/issues/14956)

EDIT001: Ok, it is down to executing ` ~/.clion-vcpkg/vcpkg/vcpkg install --triplet=x64-linux-clang16` with the same outcome

**Comment by Osyotr** [comment]
Some packages have host dependencies which are built with `VCPKG_HOST_TRIPLET`. If you're sure that your triplet can produce executables that are runnable on host, then you can set `VCPKG_HOST_TRIPLET` == `VCPKG_TARGET_TRIPLET`.

**Comment by kreuzerkrieg** [comment]
> `VCPKG_HOST_TRIPLET` == `VCPKG_TARGET_TRIPLET`

like `set(VCPKG_HOST_TRIPLET ${VCPKG_TARGET_TRIPLET})` in the custom triplet file?

**Comment by Osyotr** [comment]
No just pass it in the same way you passed `VCPKG_TARGET_TRIPLET`.
I.e. `-DVCPKG_TARGET_TRIPLET=x64-linux-clang16 -DVCPKG_HOST_TRIPLET=x64-linux-clang16`

**Comment by kreuzerkrieg** [comment]
> No just pass it in the same way you passed `VCPKG_TARGET_TRIPLET`. I.e. `-DVCPKG_TARGET_TRIPLET=x64-linux-clang16 -DVCPKG_HOST_TRIPLET=x64-linux-clang16`

yup, looks like it solves the problem. thanks!
