### ISSUE TITLE
geographiclib fails to build in linux (WSL)

### ISSUE THREAD

**Issue by RobertSpir** [microsoft/vcpkg#3308]
`  Package: geographiclib:x64-linux
  Vcpkg version: 0.0.110-unknownhash`

`CMake Error: The source directory "vcpkg/buildtrees/geographiclib/src/geographiclib-1.47" does not exist.`

source is extracted in `vcpkg/buildtrees/geographiclib/src/GeographicLib-1.47` so it is issue of case sensitive filesystem

**Comment by jmalmari** [comment]
After fixing the path name, there are more issues:
- previous port patch removed man target, must also remove reference to distrib-man (broken with newer CMake)
- option COMMON_INSTALL_PATH=ON pathway is broken; setting to OFF allows the build to succeed, although this is probably not a proper way to fix it. After installation, CMake did find the config but rejected using it.

At this point I gave up. Don't have the time now to dig further.

**Comment by JackBoosY** [comment]
Hi @RobertSpir, thanks for reporting this issue!
I've fix this issue. Please update vcpkg and rebuild geographiclib.

Thanks.
