### ISSUE TITLE
[python3] Build error

### ISSUE THREAD

**Issue by markdhenning** [microsoft/vcpkg#33080]
Package: python3:x64-linux -> 3.11.4

**Host Environment**

- Host: x64-linux
- Compiler: GNU 8.5.0
-    vcpkg-tool version: 2023-08-02-6d13efa755f9b5e101712d210199e4139b4c29f6
    vcpkg-scripts version: 247662ef3 2023-08-08 (19 hours ago)

**To Reproduce**

`vcpkg install boost`

**Failure logs**

```
-- Using cached python-cpython-v3.11.4.tar.gz.
-- Cleaning sources at /opt/vcpkg/buildtrees/python3/src/v3.11.4-c76ea88c37.clean. Use --editabl
e to skip cleaning for the packages you specify.
-- Extracting source /opt/vcpkg/downloads/python-cpython-v3.11.4.tar.gz
-- Applying patch 0001-only-build-required-projects.patch
-- Applying patch 0003-use-vcpkg-zlib.patch
-- Applying patch 0004-devendor-external-dependencies.patch
-- Applying patch 0005-dont-copy-vcruntime.patch
-- Applying patch 0008-python.pc.patch
-- Applying patch 0010-dont-skip-rpath.patch
-- Applying patch 0012-force-disable-curses.patch
-- Applying patch 0014-fix-get-python-inc-output.patch
-- Applying patch 0002-static-library.patch
-- Applying patch 0011-gcc-ldflags-fix.patch
-- Using source at /opt/vcpkg/buildtrees/python3/src/v3.11.4-c76ea88c37.clean
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Generating configure for x64-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/autoreconf -vfi
    Working Directory: /opt/vcpkg/buildtrees/python3/src/v3.11.4-c76ea88c37.clean/
    Error code: 1
    See logs for more information:
      /opt/vcpkg/buildtrees/python3/autoconf-x64-linux-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:635 (vcpkg_execute_required_process)
  ports/python3/portfile.cmake:249 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)



```
<details><summary>/opt/vcpkg/buildtrees/python3/autoconf-x64-linux-err.log</summary>

```
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:18: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```
</details>

**Additional context**

**Comment by markdhenning** [comment]
The problem happened sometime after 3.10.7#5 
Python 3 is being installed as part of one of the sub-packages of vcpkg install boost with current pull.

**Comment by Osyotr** [comment]
What is your OS and what versions of `autoconf` and `autoconf-archive` do you have?
Also note that `vcpkg install boost` installs all of the Boost so if you want smaller builds use `vcpkg install boost-*` (e.g. `vcpkg install boost-gil boost-iostreams ...`).

**Comment by markdhenning** [comment]
Good Morning,

 

/etc/redhat-release states reports: Rocky Linux release 8.8 (Green Obsidian)

Uname -a reports 4.18.0-477.15.1.el8_8.x86_64

Autoconf (GNU Autoconf) 2.69

I don’t seem to have an autoconf-archive in the path.

 

I would love to use smaller builds, but I’m using boost-serialize which is dependent on tons of subpackages.  I will be refactoring to a manifest vcpkg project implementation, but the current version uses the /opt/vcpkg with CMake.

 

I have worked around the issue on this latest VM by copying the /opt/vcpkg from a machine that was pulled from an earlier date, so I’m not dead in the water… but I thought it would be good community behavior to report the port break.

 

Very Respectfully,

 

 

Mark D. Henning (he/him/his)

Systems Engineer III

Defense Solutions Sector

Nuclear Science & Engineering

Mobile: (612) 703-8563



This is a Safe Space.

 

 

From: Osyotr ***@***.***> 
Sent: Wednesday, August 9, 2023 10:59 AM
To: microsoft/vcpkg ***@***.***>
Cc: Henning, Mark (PERATON) ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/vcpkg] [python3] Build error (Issue #33080)

 

What is your OS and what versions of autoconf and autoconf-archive do you have?
Also note that vcpkg install boost installs all of the Boost so if you want smaller builds use vcpkg install boost-* (e.g. vcpkg install boost-gil boost-iostreams ...).

**Comment by byxrolland** [comment]
I encountered similar issues: #33068

**Comment by anjolaoluwaakindipe** [comment]
I got the same error and after looking at the logs It had a problem performing an aclocal command. After googling it, I just had to install `automake` on my system to get the python dependency to install.

**Comment by nebulabox** [comment]
Met same issue on arm64-osx

**Comment by jiangwenming27488** [comment]
I have the same problem,and I install autoconf,automake,autoconf-archive three packages and solve the problem

**Comment by ellutionist** [comment]
> I have the same problem,and I install autoconf,automake,autoconf-archive three packages and solve the problem

`autoconf-archive` helps, thanks.

**Comment by connorjak** [comment]
Adding `sudo apt-get install autoconf-archive` to my github actions solved this problem on `ubuntu-latest` runner, for both gcc and clang compile with vcpkg manifest mode.

**Comment by PhoebeHui** [comment]
@Cheney-W, we probably need to add a warning into the portfile.

**Comment by Cheney-W** [comment]
Stay active

**Comment by ChetTaylor-hub** [comment]
> I have the same problem,and I install autoconf,automake,autoconf-archive three packages and solve the problem

`autoconf-archive` works!

**Comment by Juddd** [comment]
> I have the same problem,and I install autoconf,automake,autoconf-archive three packages and solve the problem

Your comment helped me a lot. May I know how you came up with it? Or is it just a guess?
