### ISSUE TITLE
[tesseract] Build error

### ISSUE THREAD

**Issue by emxcode** [microsoft/vcpkg#33094]
When i want to compile tesseract with vcpkg i get this error:

Copy issue body from C:/Users/Desktop/vcpkg-master/installed/vcpkg/issue_body.md

Computing installation plan...
The following packages will be built and installed:
    tesseract:x86-windows -> 5.3.1#1
Detecting compiler hash for triplet x86-windows...
Restored 0 package(s) from C:\Users\AppData\Local\vcpkg\archives in 129 us. Use --debug to see more details.
Installing 1/1 tesseract:x86-windows...
Building tesseract:x86-windows...
-- Using cached tesseract-ocr-tesseract-5.3.1.tar.gz.
-- Cleaning sources at C:/Users/Desktop/vcpkg-master/buildtrees/tesseract/src/5.3.1-b7e70178d8.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Desktop/vcpkg-master/downloads/tesseract-ocr-tesseract-5.3.1.tar.gz
-- Applying patch fix_static_link_icu.patch
-- Applying patch fix-aarch64-mfpu-not-available.patch
-- Using source at C:/Users/Desktop/vcpkg-master/buildtrees/tesseract/src/5.3.1-b7e70178d8.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j13
    Working Directory: C:/Users/Desktop/vcpkg-master/buildtrees/tesseract/x86-windows-dbg
    See logs for more information:
      C:\Users\Desktop\vcpkg-master\buildtrees\tesseract\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/tesseract/portfile.cmake:36 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building tesseract:x86-windows failed with: BUILD_FAILED
Elapsed time to handle tesseract:x86-windows: 12 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+tesseract
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[tesseract]+Build+error&body=Copy+issue+body+from+C%3A%2FUsers%2F%2FDesktop%2Fvcpkg-master%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by JonLiu1993** [comment]
@emxcode, Thanks for posting this issue, please provide error log:
````
C:\Users\Desktop\vcpkg-master\buildtrees\tesseract\install-x86-windows-dbg-out.log
````

**Comment by jimwang118** [comment]
I could install this port successfully with the latest vcpkg 2023-08-09-9990a4c9026811a312cb2af78bf77f3d9d288416, could you please run following commands in your vcpkg folder:

```
1. git pull
2. .\bootstrap-vcpkg.bat
3. .\vcpkg install tesseract:x86-windows --binarysource=clear
```

**Comment by JonLiu1993** [comment]
Ping @emxcode  for response.

**Comment by JonLiu1993** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!

**Comment by emxcode** [comment]
Hello dear friend I'm sorry for late answer; i move my project to Linux and i tried to compile my code on different OS. i did not have problem with compiling tesseract in Ubuntu but tesseract does not execute my command correctly with Persian language if you have solution for me please help me.
i get unknown character as output when i use images.....

**Comment by JonLiu1993** [comment]
@emxcode, Could you send me your error log? Or you can take a screenshot, thanks
