### ISSUE TITLE
[abseil] update to LTS 20230802

### ISSUE THREAD

**Issue by honeway** [microsoft/vcpkg#33097]
### Library name

abseil

### Library description

Abseil LTS 20230802

### Source repository URL

https://github.com/abseil/abseil-cpp.git

**Comment by xiaozhuai** [comment]
@honeway 
Please try #33099 to see if it works or not.

---

You can use following commands to get and apply patches and then install it.

```
curl -Ls https://github.com/microsoft/vcpkg/pull/33099.patch | git apply
vcpkg install abseil
```

---

After this pr got merged, you may want to drop your local changes via
```
git checkout .
git clean -fd
```
