### ISSUE TITLE
poco[mysql] build failure

### ISSUE THREAD

**Issue by zirid** [microsoft/vcpkg#33093]
### Operating system

Windows 10

### Compiler

MSVG

### Steps to reproduce the behavior

```Shell
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
bootstrap-vcpkg.sh
vcpkg integrate install
vcpkg install poco[core,netssl,crypto,mysql]
```

### Failure logs

`libmysql is only supported on '!(windows & x86) & !uwp & !xbox', which does not match x86-windows. This usually means that there are known build failures, or runtime problems, when building other platforms. To ignore this and attempt to build libmysql anyway, rerun vcpkg with `--allow-unsupported`.`

**Comment by autoantwort** [comment]
Use `vcpkg install poco[core,netssl,crypto,mysql]:x64-windows`

**Comment by zirid** [comment]
vcpkg install poco[core,netssl,crypto,mysql]  installed only x86 And i had to  "Use vcpkg install poco[core,netssl,crypto,mysql]:x64-windows" but got that error . After removing "mysql"  the other packages were installed without error.

**Comment by MonicaLiu0311** [comment]
> `libmysql is only supported on '!(windows & x86) & !uwp & !xbox', which does not match x86-windows. This usually means that there are known build failures, or runtime problems, when building other platforms. To ignore this and attempt to build libmysql anyway, rerun vcpkg with --allow-unsupported.`

You can try to install x86-windows with --allow-unsupported parameter, but it is not guaranteed to be successful, x64-windows is supported.

Below is my installation process.

```
PS G:\vcpkg> ./vcpkg install poco[core,netssl,crypto,mysql]:x86-windows --allow-unsupported
warning: Starting with the September 2023 release, the default triplet for vcpkg libraries will change from x86-windows to the detected host triplet (x64-windows). To resolve this message, add --triplet x86-windows to keep the same behavior.
Computing installation plan...
warning: libmysql is only supported on '!(windows & x86) & !uwp & !xbox', which does not match x86-windows. This usually means that there are known build failures, or runtime problems, when building other platforms. Proceeding anyway due to `--allow-unsupported`.
The following packages will be built and installed:
    poco[core,crypto,mysql,netssl]:x86-windows -> 1.12.4#4
Detecting compiler hash for triplet x86-windows...
Restored 1 package(s) from C:\Users\v-liumonica\AppData\Local\vcpkg\archives in 4.2 s. Use --debug to see more details.
Installing 1/1 poco:x86-windows...
Elapsed time to handle poco:x86-windows: 3.1 s
Total install time: 3.1 s
The package poco is compatible with built-in CMake targets:

    find_package(Poco REQUIRED [COMPONENTS <libs>...])
    target_link_libraries(main PRIVATE Poco::<libs>)
```
```
PS G:\vcpkg> ./vcpkg install poco[core,netssl,crypto,mysql]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    poco[core,crypto,mysql,netssl]:x64-windows -> 1.12.4#4
Detecting compiler hash for triplet x64-windows...
Restored 1 package(s) from C:\Users\v-liumonica\AppData\Local\vcpkg\archives in 3.9 s. Use --debug to see more details.
Installing 1/1 poco:x64-windows...
Elapsed time to handle poco:x64-windows: 634 ms
Total install time: 635 ms
The package poco is compatible with built-in CMake targets:

    find_package(Poco REQUIRED [COMPONENTS <libs>...])
    target_link_libraries(main PRIVATE Poco::<libs>)
```

**Comment by dg0yt** [comment]
I think the default triplet was changed from x86-windows to native windows, so the default UX (i.e. this issue) should be fixed.

**Comment by MonicaLiu0311** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
