### ISSUE TITLE
fmt:x64-windows built and installed but still getting link errors

### ISSUE THREAD

**Issue by bangusi** [Microsoft/vcpkg#331]
.\vcpkg install fmt:x64-windows
Package fmt:x64-windows is installed

.\vcpkg integrate install
Applied user-wide integration for this vcpkg root.

I am not sure if this is the reason.  My platform is Windows 7 and in vcpkg.targets file I don't see SDK 8.1 has a target. I only see SDK 10

**Comment by alexkaratarakis** [comment]
Hi,
as referenced above, there was a fix in the latest master branch that might be affecting you.
Can you try rebuilding fmt?:
`vcpkg remove --purge fmt:x64-windows`
`vcpkg install fmt:x64-windows`

**Comment by bangusi** [comment]
I just did and am still getting link errors.

e.g. error LNK2019: unresolved external symbol "public: virtual __cdecl fmt::FormatError::~FormatError(void)" (??1FormatError@fmt@@UEAA@XZ) referenced in function "public: virtual void * __cdecl fmt::

What do you have to say about vcpkg.targets though. Is it OK that there is no 8.1 target. None of my programs will be on Windows 10 any time soon. Support for Windows 7 is crucial

**Comment by ras0219-msft** [comment]
Don't worry, we definitely understand that Windows 7 support is absolutely required :). The references to 10.0 in `vcpkg.targets` are entirely for UWP and shouldn't affect your scenario.

It looks like prior to #333, fmt was not exporting `~FormatError`
```
PS D:\src\vcpkg\installed\x86-windows\lib> dumpbin /exports .\fmt.lib | select-string FormatError
<no output>
```
After #333, it is:
```
PS D:\src\vcpkg\installed\x64-windows\lib> dumpbin /exports .\fmt.lib | select-string FormatError

                  ??0FormatError@fmt@@QEAA@AEBV01@@Z (public: __cdecl fmt::FormatError::FormatError(class fmt::FormatError const &))
                  ??1FormatError@fmt@@UEAA@XZ (public: virtual __cdecl fmt::FormatError::~FormatError(void))
                  ??_R0?AVFormatError@fmt@@@8 (class fmt::FormatError `RTTI Type Descriptor')
```

To check if this change was correctly applied, could you run `vcpkg list fmt`?
```
PS D:\src\vcpkg\installed\x86-windows\lib> vcpkg list fmt
fmt:x64-windows             3.0.1-1          Formatting library for C++. It can be used as a s...
fmt:x86-windows             3.0.0            Formatting library for C++. It can be used as a s...
```
If you have 3.0.0 installed, that would explain the issue (you'll need to do `git pull` before the above steps that Alex posted).

Otherwise, it looks like there's an issue in the MSBuild integration. However, this seems really unlikely since the include directory is correctly being added.

**Comment by codicodi** [comment]
I had similar problem as you. Cmake below version 3.4 does not support WINDOWS_EXPORT_ALL_SYMBOLS option. Try to install the [latest release](https://cmake.org/download/).

**Comment by bangusi** [comment]
I have the lates fmt see:
vcpkg list fmt
D:\vcpkg>vcpkg list fmt
fmt:x64-windows             3.0.1-1
fmt:x64-windows-static      3.0.1-1

**Comment by codicodi** [comment]
Ok I got it working now. It turned out there was a problem with symbols not being **imported**.
@bangusi you probably need to perform these steps:
1) Install [latest CMake](https://cmake.org/download/).
2) Rebuild fmt as mentioned before.
3) Add `#define FMT_SHARED` before including fmt headers.

**Comment by bangusi** [comment]
I do have the latest cmake already.
D:\vcpkg>cmake --version
cmake version 3.7.0

**Comment by ras0219-msft** [comment]
Sorry, this issue got a bit lost. To pick up where we left off:

Could you try running the dumpbin expression I posted above on the produced library?
1. Open a 2015 developer prompt
2. `powershell`
3. `cd C:\path\to\vcpkg`
4. `dumpbin /exports installed\x64-windows\lib\fmt.lib | select-string FormatError`

If this comes up with results, then we've conclusively narrowed it down to an issue with the buildsystem integration.

**Comment by bangusi** [comment]
This is the output:

                  ??0FormatError@fmt@@QEAA@AEBV01@@Z (public: __cdecl fmt::Form
atError::FormatError(class fmt::FormatError const &))
                  ??1FormatError@fmt@@UEAA@XZ (public: virtual __cdecl fmt::For
matError::~FormatError(void))
                  ??_R0?AVFormatError@fmt@@@8 (class fmt::FormatError `RTTI Typ
e Descriptor')

**Comment by ras0219-msft** [comment]
Ok, so the library itself is definitely fine (as is the installation).

Could you post a minimal source file that doesn't link correctly? If you'd prefer to zip up the whole project, you can send the whole thing to `vcpkg@microsoft.com`.

**Comment by bangusi** [comment]
I have never used fmt for anything before. It just happened that is the first library I decided to test my first installation of vcpkg with. 
This is the piece of code.

```
#include"fmt\format.h"
void f0()
{
	fmt::format("{0}, {1}, {2}", 'a', 'b', 'c');
}
int main()
{
	f0();
	return 0;
}
```

**Comment by codicodi** [comment]
Reproduced - as I said before it's a problem with importing symbols. With this change:
```
#define FMT_SHARED
#include"fmt/format.h"
```
everything works fine.
It's not FormatError that is problematic, but some static data tables. As CMake's documentation states for WINDOWS_EXPORT_ALL_SYMBOLS option:

> For global data symbols, __declspec(dllimport) must still be used when compiling against the code in the .dll.

We could probably patch fmt headers in dynamic builds to avoid this problem in the future.

**Comment by barcharcraz** [comment]
I reproduced this in my own project. Seems things are super temperamental. there is a FMT_EXPORT define you can add to get fmt to export symbols, but I don't think they define it on widnows. Maybe we should try and fix this upstream.

**Comment by ras0219-msft** [comment]
Thanks to @codicodi for the root cause!

I've modified the fmt package in `3.0.1-4` to edit the installed headers and always act as though `FMT_SHARED` is defined, which fixes my local repro.
