### ISSUE TITLE
[openimageio] Build error

### ISSUE THREAD

**Issue by mousssse** [microsoft/vcpkg#33112]
Hello,
When installing OpenImageIO with vcpkg, if I include the pybind11, the build fails with this message:  `Please ensure you're using the latest port files with git pull and vcpkg update`.
But when I git pull vcpkg / run vcpkg update, I see that everything is up to date.

[issue_body.md](https://github.com/microsoft/vcpkg/files/12319827/issue_body.md)

**Comment by FrankXie05** [comment]
```
-- Could NOT find Python (missing: Python_EXECUTABLE Python_LIBRARIES Python_INCLUDE_DIRS Interpreter Development Development.Module Development.Embed) 
-- Python library not found 
--     Try setting Python_ROOT ? 
CMake Error at src/cmake/checked_find_package.cmake:177 (message):
  Python is required, aborting.
Call Stack (most recent call first):
  src/cmake/pythonutils.cmake:35 (checked_find_package)
  src/cmake/externalpackages.cmake:162 (find_python)
  CMakeLists.txt:166 (include)
```
Please make sure that you have download the python and add it to your local `{ENV}`.

**Comment by mousssse** [comment]
Thanks for the quick answer!
I tried having PYTHONPATH set to the directory that has the python executable and it didn't work. I then tried to have a concatenation of this directory plus all the subfolders (Lib, include, etc.) and it still didn't work. I did the same with Python_ROOT. I still have the same error in the command line and the issue body still states this "could not find python" error.

**Comment by FrankXie05** [comment]
@mousssse Maybe you need to re-install python form https://www.python.org/.
