### ISSUE TITLE
[ogre] Unable to load plugin

### ISSUE THREAD

**Issue by dzylikecode** [microsoft/vcpkg#33111]
**Describe the bug**

I have used `vcpkg` to install the package. However, it always reports an error in the picture below when I run the sample code. I tried to install `x64-windows-static` to bypass this error, another error about building is waiting for me. I have no idea to solve it

![image](https://github.com/OGRECave/ogre/assets/71511961/e2796608-f004-48aa-a8d0-ddb8d0e65860)

```cpp
// This file is part of the OGRE project.
// It is subject to the license terms in the LICENSE file found in the top-level
// directory of this distribution and at https://www.ogre3d.org/licensing.
// SPDX-License-Identifier: MIT

#include "Ogre.h"
#include "OgreApplicationContext.h"

//! [key_handler]
class KeyHandler : public OgreBites::InputListener {
  bool keyPressed(const OgreBites::KeyboardEvent& evt) override {
    if (evt.keysym.sym == OgreBites::SDLK_ESCAPE) {
      Ogre::Root::getSingleton().queueEndRendering();
    }
    return true;
  }
};
//! [key_handler]

int main(int argc, char* argv[]) {
  //! [constructor]
  OgreBites::ApplicationContext ctx("OgreTutorialApp");
  ctx.initApp();
  //! [constructor]

  //! [setup]
  // get a pointer to the already created root
  Ogre::Root* root = ctx.getRoot();
  Ogre::SceneManager* scnMgr = root->createSceneManager();

  // register our scene with the RTSS
  Ogre::RTShader::ShaderGenerator* shadergen =
      Ogre::RTShader::ShaderGenerator::getSingletonPtr();
  shadergen->addSceneManager(scnMgr);

  // without light we would just get a black screen
  Ogre::Light* light = scnMgr->createLight("MainLight");
  Ogre::SceneNode* lightNode =
      scnMgr->getRootSceneNode()->createChildSceneNode();
  lightNode->setPosition(0, 10, 15);
  lightNode->attachObject(light);

  // also need to tell where we are
  Ogre::SceneNode* camNode = scnMgr->getRootSceneNode()->createChildSceneNode();
  camNode->setPosition(0, 0, 15);
  camNode->lookAt(Ogre::Vector3(0, 0, -1), Ogre::Node::TS_PARENT);

  // create the camera
  Ogre::Camera* cam = scnMgr->createCamera("myCam");
  cam->setNearClipDistance(5);  // specific to this sample
  cam->setAutoAspectRatio(true);
  camNode->attachObject(cam);

  // and tell it to render into the main window
  ctx.getRenderWindow()->addViewport(cam);

  // finally something to render
  Ogre::Entity* ent = scnMgr->createEntity("Sinbad.mesh");
  Ogre::SceneNode* node = scnMgr->getRootSceneNode()->createChildSceneNode();
  node->attachObject(ent);
  //! [setup]

  //! [main]
  // register for input events
  KeyHandler keyHandler;
  ctx.addInputListener(&keyHandler);

  ctx.getRoot()->startRendering();
  ctx.closeApp();
  //! [main]
  return 0;
}
```

**Environment**
- OS: Win11
- Compiler: Visual Studio 2022
- IDE: VSCode, CMake Tools

**To Reproduce**

1. git clone the repos: https://github.com/dzylikecode/game-3D-tutorial-env
2. copy the file `CMakeUserPresets.json` to the root path of the project
3. click the button `build` provided by CMake Tools
4. run the fifth demo

**Expected behavior**

The demo should work correctly.

**Failure logs**
-(please attached failure logs)

```txt
Ogre: Installing plugin: Octree Scene Manager
Installing plugin: Octree Scene Manager
Ogre: Plugin successfully installed
Plugin successfully installed
Ogre: Loading library C:/Users/Z/Desktop/Dz/fishing/game-3D-tutorial-env/build/vcpkg_installed/x64-windows/debug/etc/ogre/../../plugins/ogre\Plugin_DotScene_d.dll
Loading library C:/Users/Z/Desktop/Dz/fishing/game-3D-tutorial-env/build/vcpkg_installed/x64-windows/debug/etc/ogre/../../plugins/ogre\Plugin_DotScene_d.dll
Loaded 'C:\Users\Z\Desktop\Dz\fishing\game-3D-tutorial-env\build\vcpkg_installed\x64-windows\debug\plugins\ogre\Plugin_DotScene_d.dll'. Symbols loaded.
Unloaded 'C:\Users\Z\Desktop\Dz\fishing\game-3D-tutorial-env\build\vcpkg_installed\x64-windows\debug\plugins\ogre\Plugin_DotScene_d.dll'.
Exception thrown at 0x00007FF8548C2BDC in 05-ogre.exe: Microsoft C++ exception: Ogre::InternalErrorException at memory location 0x00000054750FE1A0.
```

**Additional context**
The error occurs when loading the plugin  `DotScene` during the calling of the function `ctx.initApp();`. I skipped loading the plugin `DotScene`  by deleting it in the configuration file `plugins.cfg`. Then it failed again when loading the plugin `Codec_Assimp`. Finally, I deleted both to make the function `ctx.initApp();` work right, but the error caught me again when executing `Ogre::Entity* ent = scnMgr->createEntity("Sinbad.mesh");`

**Comment by dzylikecode** [comment]
Now I know the error occurring in `Ogre::Entity* ent = scnMgr->createEntity("Sinbad.mesh");`  is that resource is not found and solved it. But still, I don't know how to load the plugin correctly.

**Comment by Adela0814** [comment]
You may need to submit an issue to upstream. Let's wait for the upstream response first.

**Comment by dzylikecode** [comment]
The example `Sample Browser` offered by [SDK](https://dl.cloudsmith.io/public/ogrecave/ogre/raw/versions/v14.0.1/ogre-sdk-v14.0.1-msvc142-x64.zip) starts up fine with the plugin.

![image](https://github.com/microsoft/vcpkg/assets/71511961/c4bb6dbf-8aa4-4adf-bb9f-123851295f53)

It seems something is wrong with `vcpkg`
