### ISSUE TITLE
[New Port Request] mfem

### ISSUE THREAD

**Issue by lmdiazangulo** [microsoft/vcpkg#33114]
### Library name

mfem

### Library description

MFEM is a free, lightweight, scalable C++ library for finite element methods.

### Source repository URL

https://github.com/mfem/mfem/

### Project homepage (if different from the source repository)

https://mfem.org/

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

MFEM supports a significant amount of options to allow interaction with other projects. However, possibly the ones more useful are: 
- MFEM_USE_METIS
- MFEM_USE_HYPRE
- MFEM_USE_MPI

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
