### ISSUE TITLE
liblemon does not include header files

### ISSUE THREAD

**Issue by Vincent-bin** [microsoft/vcpkg#33115]
**Describe the bug**

fatal error: 'lemon/list_graph.h' file not found
seems liblemon headers are not included
but if add another library, it can be used, because other lib include correct vcpkg fiels

**Environment**
- OS: Mac Intel
- Compiler: clang16

**To Reproduce**
1. ./vcpkg install liblemon

add_executable(test_lemon "src/test_lemon.cc")
target_link_libraries(test_lemon PRIVATE unofficial::lemon::lemon)

**Expected behavior**
headers should be included

**Comment by xiaozhuai** [comment]
@Vincent-bin 
Please try #33130 to see if it works or not.

---

You can use following commands to get and apply patches and then install it.

```
curl -Ls https://github.com/microsoft/vcpkg/pull/33130.patch | git apply
vcpkg install libphonenumber
```

---

After this pr got merged, you may want to drop your local changes via
```
git checkout .
git clean -fd
```

**Comment by Vincent-bin** [comment]
> @Vincent-bin Please try #33130 to see if it works or not.
> 
> You can use following commands to get and apply patches and then install it.
> 
> ```
> curl -Ls https://github.com/microsoft/vcpkg/pull/33130.patch | git apply
> vcpkg install liblemon
> ```
> 
> After this pr got merged, you may want to drop your local changes via
> 
> ```
> git checkout .
> git clean -fd
> ```

I add target include files explicitly, it works now still thank you  very much

**Comment by xiaozhuai** [comment]
@Vincent-bin 
> I add target include files explicitly, it works now still thank you very much

Glad to hear you work it out. 
But there is stiil a bug in this port. And #33130 will fix it.
I would appreciate it if you could test this pr and give feedback.

**Comment by LilyWangLL** [comment]
https://github.com/microsoft/vcpkg/pull/33130 will fix this issue.
