### ISSUE TITLE
x86_64 linux下使用 clang 交叉编译 python3:arm64-linux 错误

### ISSUE THREAD

**Issue by kxgy** [microsoft/vcpkg#33121]
configure:5932: checking whether it is safe to define __EXTENSIONS__
configure:5951: /usr/bin/clang -c -g --target=aarch64-linux-gnu --sysroot=/opt/sysroot/kylin.v10.aarch64 conftest.c >&5
configure:5951: $? = 0
configure:5959: result: yes
configure:5962: checking whether _XOPEN_SOURCE should be defined
configure:5984: /usr/bin/clang -c -g --target=aarch64-linux-gnu --sysroot=/opt/sysroot/kylin.v10.aarch64 conftest.c >&5
configure:5984: $? = 0
configure:6011: result: no
configure:6070: checking for --with-cxx-main=<compiler>
configure:6097: result: no
configure:6674: checking for the platform triplet based on compiler characteristics
configure:6845: result: aarch64-linux-gnu
configure:6853: checking for multiarch
configure:6865: result: x86_64-linux-gnu
configure:6870: error: internal configure error for the platform triplet, please file a bug report

**Comment by JackBoosY** [comment]
Full log plz.

**Comment by dg0yt** [comment]
`python3` cross builds... I fixed/tested some aspects with #31621, blocked by vcpkg maintainers via #31228, but I need to test again with regard to arm64-linux.
