### ISSUE TITLE
Can't send post requests to https websites using libcurl

### ISSUE THREAD

**Issue by Sightem** [microsoft/vcpkg#33120]
**Describe the bug**
Using libcurl in visual studio (without CMake) simply refuses to work with post requests sent to https websites. `curl_easy_perform` hangs. This is not present on CMake.

**Environment**
- OS: [e.g. Windows 10 22H2]
- Compiler: MSVC

**To Reproduce**
1. vcpkg.exe install curl:x64-windows
2. Create a console app on visual studio
3. Try to send a post request to a https website

**Expected behavior**
`curl_easy_perform` not hanging

**Failure logs**
callstack:
```
 	libcurl-d.dll!Curl_fillreadbuffer(Curl_easy * data, unsigned __int64 bytes, unsigned __int64 * nreadp) Line 237	C
 	libcurl-d.dll!readwrite_upload(Curl_easy * data, connectdata * conn, int * didwhat) Line 886	C
 	libcurl-d.dll!Curl_readwrite(connectdata * conn, Curl_easy * data, bool * done, bool * comeback) Line 1127	C
 	libcurl-d.dll!multi_runsingle(Curl_multi * multi, curltime * nowp, Curl_easy * data) Line 2459	C
 	libcurl-d.dll!curl_multi_perform(Curl_multi * multi, int * running_handles) Line 2756	C
 	libcurl-d.dll!easy_transfer(Curl_multi * multi) Line 666	C
 	libcurl-d.dll!easy_perform(Curl_easy * data, bool events) Line 756	C
 	libcurl-d.dll!curl_easy_perform(Curl_easy * data) Line 776	C
```

**Additional context**

**Comment by kehrazy** [comment]
Are you sure this is a vcpkg issue?

**Comment by JackBoosY** [comment]
Maybe your anti-virus blocked the network connection?

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
