### ISSUE TITLE
[at-spi2-core] Build error

### ISSUE THREAD

**Issue by olcayatilla** [microsoft/vcpkg#33127]
Copy issue body from /home/atilla/vcpkg/installed/vcpkg/issue_body.md

**Comment by kirby-mimic** [comment]
See #4882

**Comment by jimwang118** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report an issue.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
