### ISSUE TITLE
[azure-kinect-sensor-sdk] Build error

### ISSUE THREAD

**Issue by thundercarrot** [microsoft/vcpkg#33137]
Package: azure-kinect-sensor-sdk[core,tool]:x64-windows -> 1.4.1#5

Building with "tool" feature fails. ImGui's SetNextTreeNodeOpen was previously deprecated and now has been removed. Call SetNextItemOpen instead.

see https://github.com/ocornut/imgui/blob/1362fc0c56d8742167379661a353d8342f7c4a86/imgui.h#L3131

As an aside, I was on the way to creating a patch and PR for it, but without --editable support in manifest mode, this seems pretty onerous. Is there a recommended way to do this?

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.37.32822.0
-    vcpkg-tool version: 2023-06-15-8c254a5fb6c503615834fc66bd0717664a339a2e
    vcpkg-scripts version: 0fa8459cf 2023-08-11 (2 days ago)

**To Reproduce**

`vcpkg install `

**Failure logs**

buildtrees\azure-kinect-sensor-sdk\src\v1.4.1-4fd9fcd081.clean\tools\k4aviewer\k4adevicedockcontrol.cpp(336): error C2039: 'SetNextTreeNodeOpen': is not a member of 'ImGui'
buildtrees\azure-kinect-sensor-sdk\src\v1.4.1-4fd9fcd081.clean\tools\k4aviewer\k4asourceselectiondockcontrol.cpp(37): error C2039: 'SetNextTreeNodeOpen': is not a member of 'ImGui'

**Comment by Adela0814** [comment]
Confirmd, I can repro this in my side.

**Comment by jimwang118** [comment]
This issue has been fixed by PR [40812](https://github.com/microsoft/vcpkg/pull/40812).
