### ISSUE TITLE
[OpenCASCADE]dependen on eigen3 and miss "OpenGl_khrplatform.h".

### ISSUE THREAD

**Issue by SHIHUAMarryMe** [microsoft/vcpkg#33138]
**Environment**
OS: Win11,  VS2022 latest

**Describe the bug**
1) I just want use OpenCASCADE, so I specify OpenCASCADE in vcpkg.json. like this:
```json
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg.schema.json",
  "name": "occtest",
  "version-string": "0.1.0",
  "dependencies": [
    {
      "name": "opencascade",
      "version>=": "7.6.2#6"
    },
    {
      "name": "eigen3",
      "version>=": "3.4.0#2"
    }
  ],
  "builtin-baseline": "b51f391cd8f1f5a406b3baf9b014acff61702dc3"
}
```

**If I do not speficy eigen3 in above json and my CMakeLists.txt, cmake notify that can not find eigen3!**
```cmake
find_package(Eigen3 CONFIG REQUIRED);
...
...
target_link_libraries(${PROJECT_NAME} PRIVATE Eigen3::Eigen)
```

2) When I added eigen3, it's ok. Then I compiled my demo. code like this:
```c++
#include <opencascade/V3d.hxx>
#include <opencascade/V3d_Viewer.hxx>
#include <opencascade/OpenGl_GraphicDriver.hxx>
int main()
{

	// create a graphic driver
	Handle(OpenGl_GraphicDriver) aGraphicDriver = new OpenGl_GraphicDriver(Handle(Aspect_DisplayConnection)());
	// create a viewer
	Handle(V3d_Viewer) a3DViewer = new V3d_Viewer(aGraphicDriver);
	// set parameters for V3d_Viewer
	// defines default lights -
	//   positional-light 0.3 0.0 0.0
	//   directional-light V3d_XnegYposZpos
	//   directional-light V3d_XnegYneg
	//   ambient-light
	a3DViewer->SetDefaultLights();
	// activates all the lights defined in this viewer
	a3DViewer->SetLightOn();
	// set background color to black
	a3DViewer->SetDefaultBackgroundColor(Quantity_NOC_BLACK);
}
```

**It notify that: “OpenGl_khrplatform.h”: No such file or directory. But there is OpenGl_khrplatform.h in "include/opencascade". So I include OpenCASCADE_DIR still not work.**
```
target_include_directories(${PROJECT_NAME} PUBLIC ${OpenCASCADE_DIR}
```
And there is value in OpenCASCADE_DIR, it points to "include/opencascade".

**Comment by Cheney-W** [comment]
Could you please provide your reproducible project for me? Also, what is the version of the vcpkg you used?

**Comment by Cheney-W** [comment]
Thanks for your reply! I could reproduce this issue in my side and I will fix it soon.

**Comment by Cheney-W** [comment]
@SHIHUAMarryMe Could you please try the change of my PR? This time, there's no need to specifically install `eigen3`.

**Comment by Cheney-W** [comment]
**find_package(Eigen3 CONFIG REQUIRED)** (Please remove)
.....
target_link_libraries(${PROJECT_NAME} PRIVATE TKBO TKBin TKCAF TKCDF
                                              **Eigen3::Eigen**(please remove))

**Comment by Cheney-W** [comment]
After modified the contents of CMakelists.txt file, please run below command:
![image](https://github.com/microsoft/vcpkg/assets/38240633/acd3191e-eed0-47d8-9690-c894ccff6d30)

**Comment by Cheney-W** [comment]
Could you please send the `vcpkg_installed/x64-windows/share/opencascade/OpenCASCADEConfig.cmake` file to me? Thank you!

**Comment by Cheney-W** [comment]
Please remove the `opencascade:x64-windows` and reinstall it again. I saw you still use the old files.

**Comment by Cheney-W** [comment]
I usually delete it manually.

**Comment by Cheney-W** [comment]
Have you applied the changes from my PR to your local? That PR hasn't been merged yet, so you'll need to do it manually.

**Comment by Cheney-W** [comment]
I think below file should be changed. In my change, the port-version of opencascade has increased to 7.
```
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg.schema.json",
  "name": "occtest",
  "version-string": "0.1.0",
  "dependencies": [
    {
      "name": "opencascade",
      "version>=": "7.6.2#6" (need change)
    }
  ],
  "builtin-baseline": "b51f391cd8f1f5a406b3baf9b014acff61702dc3"
}
```

**Comment by Cheney-W** [comment]
Please waiting for the PR is merged.
