### ISSUE TITLE
[mimalloc] malloc redirection sometimes does not work in Windows

### ISSUE THREAD

**Issue by theoractice** [microsoft/vcpkg#33154]
**Describe the bug**
When used together with dlib or several other packages in vcpkg, mimalloc sometimes prints an error showing that "standard malloc is _not_ redirected".

**Environment**
- OS: Windows
- Compiler: Visual Studio 2022/preview x64 Debug

**To Reproduce**
1. vcpkg install mimalloc & dlib (x64-windows)
2. new project in VS2022, paste code below and run:
```
#include <mimalloc.h>
#include <mimalloc-new-delete.h>
#include <dlib/image_processing/frontal_face_detector.h>
#include <dlib/image_processing.h>
#include <iostream>

using namespace dlib;
using namespace std;

int main(int argc, char** argv)
{
	frontal_face_detector detector = get_frontal_face_detector();
	shape_predictor sp;
}
```

**Failure logs**

> mimalloc-redirect: error: mimalloc-redirect.dll seems to be initialized after ucrtbased.dll
  (hint: try to link with the mimalloc library earlier on the command line?)
mimalloc-redirect: warning: standard malloc is _not_ redirected! -- using regular malloc/free. (v1.1c)

However, if you comment out the first line in the main function, _clean_ the project and _rebuild_:
```frontal_face_detector detector = get_frontal_face_detector();```
The error log above disappears.

**Additional context**

- This error does not appear when I download mimalloc from the official repo and build and link to it by hand (without vcpkg). 
- The error log above suggests to "link with mimalloc earlier", maybe this will help?

**Comment by jimwang118** [comment]
How is your `cmakelists.txt` file written?

**Comment by jimwang118** [comment]
> The error log above suggests to "link with mimalloc earlier", maybe this will help?

When linking, put `mimalloc` at the top and the compilation result is correct.

**Comment by theoractice** [comment]
> How is your `cmakelists.txt` file written?

No, I am using Visual Studio the old way, which means, no `cmakelists.txt`, just a *.vcxproj project.

> > The error log above suggests to "link with mimalloc earlier", maybe this will help?
> 
> When linking, put `mimalloc` at the top and the compilation result is correct.

For *.vcxproj projects, normally I just install the package I need from vcpkg, and everything works out of the box. It's not a CMake project so I don't know how to change the link order. I think it's handled and should be handled by vcpkg automatically.

**Comment by Neumann-A** [comment]
@theoractice You probably need to manually link mimalloc then. E.g. by putting it in front of the "Additional Libraries" property

> I think it's handled and should be handled by vcpkg automatically.

Nope vcpkg can do nothing here since it just tells the linker to link `*.lib`. Using the MSBuild integration is cursed any way ;)

**Comment by jimwang118** [comment]
CC @dan-shaw. Do you have any good suggestions for this issue?

**Comment by Neumann-A** [comment]
> They even put a vcpkg section in the settings menu.

That was originally https://github.com/microsoft/vcpkg/pull/4361. There is no way for the MSBuild integration to provide link order requirements without a significantly redesign how the msbuild integration works.

**Comment by theoractice** [comment]
> > They even put a vcpkg section in the settings menu.
> 
> That was originally #4361. There is no way for the MSBuild integration to provide link order requirements without a significantly redesign how the msbuild integration works.

Oh thanks for your contribution.

**Comment by jimwang118** [comment]
@theoractice Does Neumann-A's answer solve your problem? If it can be solved, I will close this issue.

**Comment by theoractice** [comment]
> @theoractice Does Neumann-A's answer solve your problem? If it can be solved, I will close this issue.

Solved, but you know, not satisfied🤔
Never mind, you can close it.
