### ISSUE TITLE
[opencascade] update to 7.7.2

### ISSUE THREAD

**Issue by luzpaz** [microsoft/vcpkg#33155]
### Library name

opencascade

### New version number

7.7.2

### Other information that may be useful (release notes, etc...)

Blog announcement: https://dev.opencascade.org/content/open-cascade-technology-772-maintenance-release  
Release tag: https://git.dev.opencascade.org/gitweb/?p=occt.git;a=shortlog;h=refs/heads/OCCT-772

**Comment by paulbuechner** [comment]
@FrankXie05 Can be closed in favour of: https://github.com/microsoft/vcpkg/pull/33498
