### ISSUE TITLE
Linux [WSL] proj failed

### ISSUE THREAD

**Issue by Voskrese** [Microsoft/vcpkg#3316]
```
-- Build x64-linux-rel done
CMake Error at ports/proj4/portfile.cmake:63 (file):
  file RENAME failed to rename

    /root/tmp/vcpkg/packages/proj4_x64-linux/lib/proj_4_9.lib

  to

    /root/tmp/vcpkg/packages/proj4_x64-linux/lib/proj.lib

  because: No such file or directory

Call Stack (most recent call first):
  scripts/ports.cmake:72 (include)


Error: Building package proj4:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: proj4:x64-linux
  Vcpkg version: 0.0.110-unknownhash
```

`ls /root/tmp/vcpkg/packages/proj4_x64-linux/lib`
**libproj.a**

по моему мнению рановато выпустили в свет порт для линукс, ну и мое мнение он там и не нужен был. в unix системах изолированные библиотеки можно создать указав при инсталяции, хоть в /usr/local/local/local/..
в общем у портов много ошибок будет, в MSVC *.lib в UNIX *.a

> in my opinion rather early released a port for Linux, well, my opinion, he was not needed there. in unix systems, isolated libraries can be created by pointing at installation, even in / usr / local / local / local / ..
> in general, ports have a lot of errors, in MSVC *. lib on UNIX * .a

и еще одно замечание, зачем отдельно ставить Ninja и Cmake ? у меня Ninja не сразу скачался, с раза пятого, сбрасывало по таймауту
почему не подходит стандартное исполнение
apt-get install ninja - ну и выбрать версию, если она совместима и не конфликтует
для других систем аналогично

> and one more thing, why set Ninja and Cmake separately? At me Ninja not at once was downloaded, since time of the fifth, dumped on timeout
> why the standard execution is not suitable
> apt-get install ninja - well, choose the version if it is compatible and does not conflict
> for other systems is similar

**Comment by JimWest** [comment]
Can be fixed with adding `if(NOT VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Linux")`
before the renaming of the lib:
[portfile.cmake.zip](https://github.com/Microsoft/vcpkg/files/1966276/portfile.cmake.zip)

**Comment by fbudin69500** [comment]
I created a PR (#3425) in which I patch this file and this should solve this problem.
