### ISSUE TITLE
[opentelemetry-cpp] Update to v1.10.0

### ISSUE THREAD

**Issue by okhowang** [microsoft/vcpkg#33177]
### Library name

opentelemetry-cpp

### New version number

v1.10.0

### Other information that may be useful (release notes, etc...)

https://github.com/open-telemetry/opentelemetry-cpp/releases/tag/v1.10.0

**Comment by MonicaLiu0311** [comment]
Fixed by higher version https://github.com/microsoft/vcpkg/pull/33983.
