### ISSUE TITLE
[New Port Request] libcap

### ISSUE THREAD

**Issue by sabedevops** [microsoft/vcpkg#33216]
### Library name

libcap

### Source repository URL

https://git.kernel.org/pub/scm/libs/libcap/libcap.git

**Comment by sabedevops** [comment]
Bump.

**Comment by dg0yt** [comment]
libcap was added together with libsystemd on September 20.

**Comment by JonLiu1993** [comment]
Fixed by PR https://github.com/microsoft/vcpkg/pull/31150
