### ISSUE TITLE
[libjpeg-turbo] build failure

### ISSUE THREAD

**Issue by TonyWu-21474** [microsoft/vcpkg#33220]
### Operating system

Windows 11

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
vcpkg install libjpeg-turbo:x64-Windows
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
    libjpeg-turbo:x64-windows -> 2.1.5.1#2
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\吴\AppData\Local\vcpkg\archives in 110 us. Use --debug to see more details.
Installing 1/1 libjpeg-turbo:x64-windows...
Building libjpeg-turbo:x64-windows...
-- Using cached libjpeg-turbo-libjpeg-turbo-2.1.5.1.tar.gz.
error: building libjpeg-turbo:x64-windows failed with: BUILD_FAILED
Elapsed time to handle libjpeg-turbo:x64-windows: 370 ms

### Additional context

both x64 and x86 version are unavailable

**Comment by jimwang118** [comment]
Please provide the error log below. 
For example:
![image](https://github.com/microsoft/vcpkg/assets/122244446/c38e4388-d54d-4634-b63f-4ef912c33619)

**Comment by punk-floyd** [comment]
I think I'm running into this as well. Looks like a problem compiling the resource file. I've attached the referenced log.

![image](https://github.com/microsoft/vcpkg/assets/18149184/628d061e-77ea-4118-a481-69280a54efa3)
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/12422873/install-x64-windows-dbg-out.log)

**Comment by jimwang118** [comment]
I did not reproduce this issue locally, can you provide your system version and compiler version?
![image](https://github.com/microsoft/vcpkg/assets/122244446/9e8f1325-3714-4c92-9a11-fa883684c0bd)

**Comment by clearsky** [comment]
> 
x64-windows is ok, x64-windows-static fail.
![image](https://github.com/microsoft/vcpkg/assets/38609798/90a42076-2d4f-4687-8021-3e9daef99ff0)

**Comment by jimwang118** [comment]
```
CMakeFiles\turbojpeg-static.dir\rdppm.c.obj CMakeFiles\turbojpeg-static.dir\wrbmp.c.obj CMakeFiles\turbojpeg-static.dir\wrppm.c.obj  && cd ."
另一个程序正在使用此文件，进程无法访问。
```
There is the above prompt in the log, is there any other program occupying this compilation resource?

**Comment by clearsky** [comment]
> ```
> CMakeFiles\turbojpeg-static.dir\rdppm.c.obj CMakeFiles\turbojpeg-static.dir\wrbmp.c.obj CMakeFiles\turbojpeg-static.dir\wrppm.c.obj  && cd ."
> 另一个程序正在使用此文件，进程无法访问。
> ```
> 
> There is the above prompt in the log, is there any other program occupying this compilation resource?

I still encounter this error when I restart my computer and immediately compile, I don't know why. Then I set up single threaded compilation, and it works.

**Comment by jimwang118** [comment]
> > ```
> > CMakeFiles\turbojpeg-static.dir\rdppm.c.obj CMakeFiles\turbojpeg-static.dir\wrbmp.c.obj CMakeFiles\turbojpeg-static.dir\wrppm.c.obj  && cd ."
> > 另一个程序正在使用此文件，进程无法访问。
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > There is the above prompt in the log, is there any other program occupying this compilation resource?
> 
> I still encounter this error when I restart my computer and immediately compile, I don't know why. Then I set up single threaded compilation, and it works.

That should be that some files will be reused during multi-threaded compilation, and then this problem will occur when they are written at the same time.

**Comment by punk-floyd** [comment]
Apologies for the delayed response.

I'm running the latest Windows 10 Pro 64-bit:

Edition Windows 10 Pro
Version 22H2
Installed on ‎5/‎28/‎2020
OS build 19045.3324
Experience Windows Feature Experience Pack 1000.19041.1000.0


For the compiler, I assume that vcpkg is using my Visual Studio 2022
compiler, which is up to date as far as I know:

Microsoft Visual Studio Community 2022
Version 17.7.2
VisualStudio.17.Release/17.7.2+34018.315
Microsoft .NET Framework
Version 4.8.09037


Installed Version: Community


Visual C++ 2022   00482-90000-00000-AA410

Microsoft Visual C++ 2022


Ultimately, I'm trying to build the pcl library, which depends on
libjpeg-turbo. From Windows terminal in vcpkg root, I run: vcpkg install
pcl[...snip...]

For the time being, I've moved over to WSL, where I can pull in the PCL
package and build okay. This is fine for my development, but I am hoping to
have a Windows build for some other folks. Thanks for your help.

**Comment by jimwang118** [comment]
@clearsky Please tell me how to configure single-threaded compilation. I would like to know the specific process. Thank you so much.

**Comment by clearsky** [comment]
> @clearsky Please tell me how to configure single-threaded compilation. I would like to know the specific process. Thank you so much.

Use cmd  rather than powershell:
1.set VCPKG_MAX_CONCURRENCY=1
2.vcpkg install ...

**Comment by punk-floyd** [comment]
No, not trying to add a new feature. I just cut out the list of features for brevity. I think the full command was:

```
vcpkg install
pcl[apps, core, cuda, examples, libusb, opengl, openni2, pcap, qt, simulation, surface-on-nurbs, tools, visualization, vtk]
```

**Comment by jimwang118** [comment]
> No, not trying to add a new feature. I just cut out the list of features for brevity. I think the full command was:
> 
> ```
> vcpkg install
> pcl[apps, core, cuda, examples, libusb, opengl, openni2, pcap, qt, simulation, surface-on-nurbs, tools, visualization, vtk]
> ```

Can you provide a detailed error log?

**Comment by punk-floyd** [comment]
Again, apologies for delayed response. I've attached a few files. The full command and output of a x86 build I tried this morning and its corresponding error log. I've also included the error log for a x64 build I did last week. It looks like a problem compiling the resource file (turbojpeg.rc).

[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/12551600/install-x86-windows-dbg-out.log)
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/12551601/install-x64-windows-dbg-out.log)
[vcpkg-install-pcl.log](https://github.com/microsoft/vcpkg/files/12551603/vcpkg-install-pcl.log)

**Comment by dg0yt** [comment]
I always see errors around assembling sse2 stuff:
~~~
[81/166] C:\PROGRA~2\NASM\nasm.exe -D_CRT_NONSTDC_NO_WARNINGS -IC:\_SoftDev\tools\vcpkg\buildtrees\libjpeg-turbo\x86-windows-dbg -IC:\_SoftDev\tools\vcpkg\buildtrees\libjpeg-turbo\src\2.1.5.1-f411453282.clean -DWIN32 -I"C:/_SoftDev/tools/vcpkg/buildtrees/libjpeg-turbo/src/2.1.5.1-f411453282.clean/simd/nasm/" -I"C:/_SoftDev/tools/vcpkg/buildtrees/libjpeg-turbo/src/2.1.5.1-f411453282.clean/simd/i386/" -g -MD simd\CMakeFiles\simd.dir\i386\jchuff-sse2.asm.obj.d -MT simd\CMakeFiles\simd.dir\i386\jchuff-sse2.asm.obj -f win32 -o simd\CMakeFiles\simd.dir\i386\jchuff-sse2.asm.obj C:\_SoftDev\tools\vcpkg\buildtrees\libjpeg-turbo\src\2.1.5.1-f411453282.clean\simd\i386\jchuff-sse2.asm
FAILED: simd/CMakeFiles/simd.dir/i386/jchuff-sse2.asm.obj 
C:\PROGRA~2\NASM\nasm.exe -D_CRT_NONSTDC_NO_WARNINGS -IC:\_SoftDev\tools\vcpkg\buildtrees\libjpeg-turbo\x86-windows-dbg -IC:\_SoftDev\tools\vcpkg\buildtrees\libjpeg-turbo\src\2.1.5.1-f411453282.clean -DWIN32 -I"C:/_SoftDev/tools/vcpkg/buildtrees/libjpeg-turbo/src/2.1.5.1-f411453282.clean/simd/nasm/" -I"C:/_SoftDev/tools/vcpkg/buildtrees/libjpeg-turbo/src/2.1.5.1-f411453282.clean/simd/i386/" -g -MD simd\CMakeFiles\simd.dir\i386\jchuff-sse2.asm.obj.d -MT simd\CMakeFiles\simd.dir\i386\jchuff-sse2.asm.obj -f win32 -o simd\CMakeFiles\simd.dir\i386\jchuff-sse2.asm.obj C:\_SoftDev\tools\vcpkg\buildtrees\libjpeg-turbo\src\2.1.5.1-f411453282.clean\simd\i386\jchuff-sse2.asm
C:\_SoftDev\tools\vcpkg\buildtrees\libjpeg-turbo\src\2.1.5.1-f411453282.clean\simd\i386\jchuff-sse2.asm:606: error: parser: instruction expected
C:\_SoftDev\tools\vcpkg\buildtrees\libjpeg-turbo\src\2.1.5.1-f411453282.clean\simd\i386\jchuff-sse2.asm:626: error: symbol `tzcnt' redefined
C:\_SoftDev\tools\vcpkg\buildtrees\libjpeg-turbo\src\2.1.5.1-f411453282.clean\simd\i386\jchuff-sse2.asm:626: error: parser: instruction expected
C:\_SoftDev\tools\vcpkg\buildtrees\libjpeg-turbo\src\2.1.5.1-f411453282.clean\simd\i386\jchuff-sse2.asm:677: error: symbol `tzcnt' redefined
C:\_SoftDev\tools\vcpkg\buildtrees\libjpeg-turbo\src\2.1.5.1-f411453282.clean\simd\i386\jchuff-sse2.asm:677: error: parser: instruction expected
C:\_SoftDev\tools\vcpkg\buildtrees\libjpeg-turbo\src\2.1.5.1-f411453282.clean\simd\i386\jchuff-sse2.asm:736: error: symbol `tzcnt' redefined
C:\_SoftDev\tools\vcpkg\buildtrees\libjpeg-turbo\src\2.1.5.1-f411453282.clean\simd\i386\jchuff-sse2.asm:736: error: parser: instruction expected
C:\_SoftDev\tools\vcpkg\buildtrees\libjpeg-turbo\src\2.1.5.1-f411453282.clean\simd\i386\jchuff-sse2.asm:736: error: symbol `tzcnt' redefined
C:\_SoftDev\tools\vcpkg\buildtrees\libjpeg-turbo\src\2.1.5.1-f411453282.clean\simd\i386\jchuff-sse2.asm:736: error: parser: instruction expected
C:\_SoftDev\tools\vcpkg\buildtrees\libjpeg-turbo\src\2.1.5.1-f411453282.clean\simd\i386\jchuff-sse2.asm:757: error: symbol `tzcnt' redefined
C:\_SoftDev\tools\vcpkg\buildtrees\libjpeg-turbo\src\2.1.5.1-f411453282.clean\simd\i386\jchuff-sse2.asm:757: error: parser: instruction expected
C:\_SoftDev\tools\vcpkg\buildtrees\libjpeg-turbo\src\2.1.5.1-f411453282.clean\simd\i386\jchuff-sse2.asm:757: error: symbol `tzcnt' redefined
C:\_SoftDev\tools\vcpkg\buildtrees\libjpeg-turbo\src\2.1.5.1-f411453282.clean\simd\i386\jchuff-sse2.asm:757: error: parser: instruction expected
~~~
`C:\PROGRA~2\NASM\nasm.exe` isn't where vcpkg puts downloaded tools. Maybe this version of `nasm` is too old?

**Comment by jimwang118** [comment]
Can you provide detailed error logs? 
For example: config-x64-windows-err.log, config-x64-windows-out.log,install-x64-windows-dbg-err.log,install-x64-windows-dbg-out.log.

**Comment by dg0yt** [comment]
@jimwang118: @BrianMouncer has this problem: https://github.com/microsoft/vcpkg/issues/35359.

**Comment by dsewtz** [comment]
Hi, I had a similar issue (not sure if the same) and resolved it by deleting/renaming the vcpkg/downloads/tools/nasm folder:
It contained nasm-2.15.05 previously (directly after a git pull, update and upgrade) and the build failed.
After deleting the folder and running vcpkg install libjpeg-turbo:x86-windows again
it now contains nasm-2.16.01 and everything works fine.
Maybe there is a conflict with some other package with the nasm required version?

**Comment by punk-floyd** [comment]
Great! Thanks @jimwang118.
