### ISSUE TITLE
[boost-container] Build error

### ISSUE THREAD

**Issue by Na1usnuk** [microsoft/vcpkg#33238]
Copy issue body from C:/Users/Nazar/Documents/Visual Studio 2022/Projects/Crow111/Crow111/vcpkg_installed/x64-windows/vcpkg/issue_body.md

**Comment by MonicaLiu0311** [comment]
Please provide detailed error information.

**Comment by Na1usnuk** [comment]
> Please provide detailed error information.

I dont really know how to get more detailed error information, all i do to get this error is `git clone https://github.com/microsoft/vcpkg.git`, then `.\vcpkg\bootstrap-vcpkg.bat`, and `.\vcpkg\vcpkg integrate install` (all without any errors), do steps 5-11 (from https://crowcpp.org/master/getting_started/setup/windows/) and then run my Crow111 project in visual studio. Should i copy vcpkg.target`s code? If you need more information please tell me where and how get it.

**Comment by autoantwort** [comment]
You should copy the issue body from C:/Users/Nazar/Documents/Visual Studio 2022/Projects/Crow111/Crow111/vcpkg_installed/x64-windows/vcpkg/issue_body.md

**Comment by Na1usnuk** [comment]
> You should copy the issue body from C:/Users/Nazar/Documents/Visual Studio 2022/Projects/Crow111/Crow111/vcpkg_installed/x64-windows/vcpkg/issue_body.md

Okay, there it is:
Package: boost-container:x64-windows -> 1.75.0#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.37.32822.0
-    vcpkg-tool version: 2023-08-09-9990a4c9026811a312cb2af78bf77f3d9d288416
    vcpkg-scripts version: c7fc29984 2023-08-17 (10 hours ago)

**To Reproduce**

`vcpkg install `
**Failure logs**

```
-- Using cached boostorg-container-boost-1.75.0.tar.gz.
-- Cleaning sources at C:/dev/vcpkg/buildtrees/boost-container/src/ost-1.75.0-707de84ce8.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/boostorg-container-boost-1.75.0.tar.gz
-- Using source at C:/dev/vcpkg/buildtrees/boost-container/src/ost-1.75.0-707de84ce8.clean
CMake Error at C:/Users/Nazar/Documents/Visual Studio 2022/Projects/Crow111/Crow111/vcpkg_installed/x64-windows/x64-windows/share/boost-build/boost-modular-build.cmake:316 (message):
  Unsupported value for VCPKG_PLATFORM_TOOLSET: 'v143'
Call Stack (most recent call first):
  buildtrees/versioning_/versions/boost-container/5d351bf7c795d3dd8437d2beed167bd3cd66e10b/portfile.cmake:15 (boost_modular_build)
  scripts/ports.cmake:147 (include)



```
**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "name": "crow-examples",
  "version": "1.0.2",
  "dependencies": [
    {
      "name": "boost-array",
      "version>=": "1.70.0"
    },
    {
      "name": "boost-algorithm",
      "version>=": "1.70.0"
    },
    {
      "name": "boost-asio",
      "version>=": "1.70.0"
    },
    {
      "name": "boost-date-time",
      "version>=": "1.70.0"
    },
    {
      "name": "boost-functional",
      "version>=": "1.70.0"
    },
    {
      "name": "boost-lexical-cast",
      "version>=": "1.70.0"
    },
    {
      "name": "boost-optional",
      "version>=": "1.70.0"
    },
    {
      "name": "openssl"
    },
    {
      "name": "zlib"
    }
  ],
  "overrides": [
    {
      "name": "boost-array",
      "version": "1.70.0"
    },
    {
      "name": "boost-algorithm",
      "version": "1.70.0"
    },
    {
      "name": "boost-asio",
      "version-semver": "1.70.0-2"
    },
    {
      "name": "boost-date-time",
      "version": "1.70.0"
    },
    {
      "name": "boost-functional",
      "version": "1.70.0"
    },
    {
      "name": "boost-lexical-cast",
      "version": "1.70.0"
    },
    {
      "name": "boost-optional",
      "version": "1.70.0"
    }
  ],
  "builtin-baseline": "44d94c2edbd44f0c01d66c2ad95eb6982a9a61bc"
}

```
</details>

**Comment by autoantwort** [comment]
Finally. 
You use a very old baseline (Apr 30, 2021), back then `VCPKG_PLATFORM_TOOLSET` 143 was not supported (the new default one). So you can update your baseline or add 
```json

    {
      "name": "boost-modular-build-helper",
      "version": "1.82.0"
    }
```
to your overrides

**Comment by Na1usnuk** [comment]
Thanks, thats helped a little but now i have new issue:
Warning		error: cycle detected during boost-iterator:x64-windows:	Crow111	C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets	183

**Comment by autoantwort** [comment]
I think the best would be to start with an up to date baseline and remove the overrides.

**Comment by MonicaLiu0311** [comment]
Try changing the baseline to the latest and try again: 
```
PS G:\vcpkg> git rev-parse head
c7fc2998445046e8ba3a470eeb49ee1520fbd370
```

**Comment by Na1usnuk** [comment]
Sorry, nothing change. Base line up to date (
`PS C:\dev\vcpkg>  git rev-parse head 
c7fc2998445046e8ba3a470eeb49ee1520fbd370 c7fc2998445046e8ba3a470eeb49ee1520fbd370 
c7fc2998445046e8ba3a470eeb49ee1520fbd370`) 
and i create new project with updated baseline, there is same:
1. WARNING: error: cycle detected during boost-iterator:x64-windows:	Crow222	C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets	183	
2. ERROR: Error MSB3073	The command ""C:\dev\vcpkg\vcpkg.exe" install  --x-wait-for-lock --triplet "x64-windows" --vcpkg-root "C:\dev\vcpkg\\" "--x-manifest-root=C:\Users\Nazar\Documents\Visual Studio 2022\Projects\Crow222\Crow222\\" "--x-install-root=C:\Users\Nazar\Documents\Visual Studio 2022\Projects\Crow222\Crow222\vcpkg_installed\x64-windows\\" --feature-flags="versions"" exited with code 1.	Crow222	C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets	183

**Comment by autoantwort** [comment]
So your updated vcpkg.json looks like the following?
```json
{
  "name": "crow-examples",
  "version": "1.0.2",
  "dependencies": [
    {
      "name": "boost-array",
      "version>=": "1.70.0"
    },
    {
      "name": "boost-algorithm",
      "version>=": "1.70.0"
    },
    {
      "name": "boost-asio",
      "version>=": "1.70.0"
    },
    {
      "name": "boost-date-time",
      "version>=": "1.70.0"
    },
    {
      "name": "boost-functional",
      "version>=": "1.70.0"
    },
    {
      "name": "boost-lexical-cast",
      "version>=": "1.70.0"
    },
    {
      "name": "boost-optional",
      "version>=": "1.70.0"
    },
    {
      "name": "openssl"
    },
    {
      "name": "zlib"
    }
  ],
  "builtin-baseline": "c7fc2998445046e8ba3a470eeb49ee1520fbd370"
}
```

**Comment by Na1usnuk** [comment]
Sorry it wasnt, i forgot to delete overrides, now i do this and my vcpkg.json look exactly like this. Thanks now my previous problem solved, but there is another one:

Warning: error: version conflict on boost-algorithm:x64-windows: crow-examples required 1.70.0, which cannot be compared with the baseline version 1.82.0#2.	Crow222	C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets	183

**Comment by Na1usnuk** [comment]
It helped! No more errors, just some warnings (i thing its crow's issue) but its work and i finally create my first Hello World web site! I am very grateful to you, really thanks @autoantwort!
