### ISSUE TITLE
[qt5-base] Build error

### ISSUE THREAD

**Issue by daijicheng** [microsoft/vcpkg#33236]
Package: qt5-base:x64-windows -> 5.15.10#5

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.37.32822.0
-    vcpkg-tool version: 2023-08-09-9990a4c9026811a312cb2af78bf77f3d9d288416
    vcpkg-scripts version: 576f3f1ad 2023-08-14 (2 days ago)

**To Reproduce**

`vcpkg install colmap[tests]:x64-windows`
**Failure logs**

```
[build-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/12368060/build-x64-windows-dbg-err.log)
[build-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/12368062/build-x64-windows-dbg-out.log)

**Comment by FrankXie05** [comment]
Please provide the error log.

**Comment by daijicheng** [comment]
Here is the  error log.
[build-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/12368060/build-x64-windows-dbg-err.log)
[build-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/12368062/build-x64-windows-dbg-out.log)

**Comment by daijicheng** [comment]
The magic is that when I ran out of memory during compilation and started single-thread compilation, the problem disappeared. I still don't know where the problem is, but I can provide the [issue_body.md](https://github.com/microsoft/vcpkg/files/13037430/issue_body.md) where the last error occurred as a reference.
