### ISSUE TITLE
[llhttp] build failure

### ISSUE THREAD

**Issue by 1337328542** [microsoft/vcpkg#33237]
### Operating system

windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
vcpkg.json -> "llhttp",
```

### Failure logs

1> [CMake] CMake Error at out/build/x64-Debug/vcpkg_installed/x64-windows/share/llhttp/llhttp-config.cmake:75 (message):
1> [CMake]   The imported target "llhttp::llhttp_shared" references the file
1> [CMake] 
1> [CMake]      "E:/work_e/others/start-cpp-vcpkg/out/build/x64-Debug/vcpkg_installed/x64-windows/debug/lib/llhttp.lib"
1> [CMake] 
1> [CMake]   but this file does not exist.  Possible reasons include:
1> [CMake] 
1> [CMake]   * The file was deleted, renamed, or moved to another location.
1> [CMake] 
1> [CMake]   * An install or uninstall procedure did not complete successfully.
1> [CMake] 
1> [CMake]   * The installation package was faulty and contained
1> [CMake] 
1> [CMake]      "E:/work_e/others/start-cpp-vcpkg/out/build/x64-Debug/vcpkg_installed/x64-windows/share/llhttp/llhttp-config.cmake"
1> [CMake] 
1> [CMake]   but not all the files it references.
1> [CMake] 
1> [CMake] Call Stack (most recent call first):
1> [CMake]   vcpkg/scripts/buildsystems/vcpkg.cmake:852 (_find_package)
1> [CMake]   src/sample-net/CMakeLists.txt:18 (find_package)
1> [CMake] -- Configuring incomplete, errors occurred!
1> [CMake] See also "E:/work_e/others/start-cpp-vcpkg/out/build/x64-Debug/CMakeFiles/CMakeOutput.log".

### Additional context

I check the vcpkg_installed folder, and there is no "llhttp.lib" file, but the vcpkg folder had

maybe install script copy error?

**Comment by JonLiu1993** [comment]
This issue could be reproduced with vcpkg 2023-08-09-9990a4c9026811a312cb2af78bf77f3d9d288416 and VS2022 17.6.6
