### ISSUE TITLE
Openssl build fails on Ubuntu Linux - Docker

### ISSUE THREAD

**Issue by toki07** [microsoft/vcpkg#3324]
Environment variable PATH contains ';' as separators, that are invalid on Linux
Sample PATH from log : export "PATH=/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin;/usr/bin;/WORK/vcpkg/downloads/tools/ninja-1.8.2-linux" 

Issues come from : 
 - portfile.cmake(line 13)
 - portfile.cmake(line 36)
 - CMakeList.txt(line 48)

Attachments :
 - Dockerfile-without-correction : Dockerfile initial, doesn't compime openssl
 - Dockerfile-with-correction    : Dockerfile with with replacing ';' by ':', compiles openssl

[Dockerfile-with-correction.txt](https://github.com/Microsoft/vcpkg/files/1948298/Dockerfile-with-correction.txt)
[Dockerfile-without-correction.txt](https://github.com/Microsoft/vcpkg/files/1948299/Dockerfile-without-correction.txt)

**Comment by algorys** [comment]
Looks like this error only happens on Docker machines. 

When I tested on virtual machines without Docker (Ubuntu 16.04, Debian 9, Fedora), the compilation works for OpenSSL.

**Comment by PhoebeHui** [comment]
Closing in favor of https://github.com/microsoft/vcpkg/issues/14031
