### ISSUE TITLE
The image on the right on the website is possible to drag from the Browse Packages button

### ISSUE THREAD

**Issue by TheRedXD** [microsoft/vcpkg#33258]
**Describe the bug**
This is a bug with the vcpkg website at https://vcpkg.io/, I know this is the repo for the actual vcpkg software but I couldn't find any way to report issues with the website. The "Browse Packages" button at certain widths of the browser is overlayed by the image on the right the first thing you see when you open the website.

![image](https://github.com/microsoft/vcpkg/assets/56270596/dd8bfc70-d644-4294-9bdd-b6aeef3bd2c5)

I dragged the image from the button, where it's not supposed to be draggable

**Environment**
- OS: Linux
- Browser: Firefox

**To Reproduce**
1. Open https://vcpkg.io/en/
2. Scale your browser and glide with your cursor across the "Browse Packages" button on various scales
3. You will notice that the cursor is no longer a pointer and hovers over an image on the website.

**Expected behavior**
The button is always possible to click and is never overlayed

**Failure logs**
(it's a website issue so no logs)

**Additional context**
Fix this issue by making the images you're not supposed to click use `pointer-events: none;` and `user-select: none;` in their CSS

**Comment by StarGate-One** [comment]
Might want to let the folks here know [https://github.com/vcpkg/vcpkg.github.io/tree/main](https://github.com/vcpkg/vcpkg.github.io/tree/main).

**Comment by LilyWangLL** [comment]
![image](https://github.com/microsoft/vcpkg/assets/94091114/0df1b8a1-d92b-4d94-a874-c96cc17c5f4c)


Thanks for posting this issue, please submit this issue on https://github.com/vcpkg/vcpkg.github.io/issues.
