### ISSUE TITLE
[icu] Build error on Windows 10, unable unpack dependency 

### ISSUE THREAD

**Issue by VladlenPopolitov** [microsoft/vcpkg#33267]
Package: icu[core,tools]:x64-windows -> 73.1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.36.32535.0
-    vcpkg-tool version: 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895
    vcpkg-scripts version: c7fc29984 2023-08-17 (33 hours ago)

**To Reproduce**

`vcpkg install icu`

**Failure logs**

```
-- Using cached icu4c-73_1-src.tgz.
-- Cleaning sources at Z:/Development/src/vcpkg/buildtrees/icu/src/c-73_1-src-3575e21c7c.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source Z:/Development/src/vcpkg/downloads/icu4c-73_1-src.tgz
-- Applying patch disable-escapestr-tool.patch
-- Applying patch remove-MD-from-configure.patch
-- Applying patch fix_parallel_build_on_windows.patch
-- Applying patch fix-extra.patch
-- Applying patch mingw-dll-install.patch
-- Applying patch disable-static-prefix.patch
-- Applying patch fix-win-build.patch
-- Using source at Z:/Development/src/vcpkg/buildtrees/icu/src/c-73_1-src-3575e21c7c.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Using cached msys2-autoconf-wrapper-20221207-1-any.pkg.tar.zst.
-- Using cached msys2-automake-wrapper-20221207-1-any.pkg.tar.zst.
-- Using cached msys2-binutils-2.40-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libtool-2.4.7-3-x86_64.pkg.tar.zst.
-- Using cached msys2-make-4.4.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-pkgconf-1.9.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-which-2.21-4-x86_64.pkg.tar.zst.
-- Using cached msys2-autoconf-archive-2022.09.03-1-any.pkg.tar.zst.
-- Using cached msys2-bash-5.2.015-1-x86_64.pkg.tar.zst.
-- Using cached msys2-coreutils-8.32-5-x86_64.pkg.tar.zst.
-- Using cached msys2-file-5.44-5-x86_64.pkg.tar.zst.
-- Using cached msys2-gawk-5.2.1-2-x86_64.pkg.tar.zst.
-- Using cached msys2-grep-1~3.0-6-x86_64.pkg.tar.zst.
-- Using cached msys2-gzip-1.12-2-x86_64.pkg.tar.zst.
-- Using cached msys2-diffutils-3.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-sed-4.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using cached msys2-autoconf2.71-2.71-1-any.pkg.tar.zst.
-- Using cached msys2-automake1.16-1.16.5-1-any.pkg.tar.zst.
-- Using cached msys2-libiconv-1.17-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libintl-0.21-2-x86_64.pkg.tar.zst.
-- Using cached msys2-zlib-1.2.13-1-x86_64.pkg.tar.zst.
-- Using cached msys2-tar-1.34-3-x86_64.pkg.tar.zst.
-- Using cached msys2-findutils-4.9.0-3-x86_64.pkg.tar.zst.
-- Using cached msys2-gmp-6.2.1-2-x86_64.pkg.tar.zst.
-- Using cached msys2-gcc-libs-11.3.0-3-x86_64.pkg.tar.zst.
-- Using cached msys2-libbz2-1.0.8-4-x86_64.pkg.tar.zst.
-- Using cached msys2-liblzma-5.4.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libzstd-1.5.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libreadline-8.2.001-3-x86_64.pkg.tar.zst.
-- Using cached msys2-mpfr-4.2.0-2-x86_64.pkg.tar.zst.
-- Using cached msys2-libpcre-8.45-3-x86_64.pkg.tar.zst.
-- Using cached msys2-m4-1.4.19-2-x86_64.pkg.tar.zst.
-- Using cached msys2-perl-5.36.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-ncurses-6.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libcrypt-2.1-4-x86_64.pkg.tar.zst.
CMake Error: Problem with archive_write_header(): Can't create '\\?\Z:\Development\src\vcpkg\downloads\tools\msys2\87962f0d86055c95.tmp\usr\bin\ld.exe'
CMake Error: Current file: usr/bin/ld.exe
CMake Error at scripts/cmake/vcpkg_acquire_msys.cmake:229 (file):
  file failed to extract:
  Z:/Development/src/vcpkg/downloads/msys2-binutils-2.40-1-x86_64.pkg.tar.zst
Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:228 (vcpkg_acquire_msys)
  ports/icu/portfile.cmake:54 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)



```

**Additional context**
1) Windows 10 with Development mode switched on (Windows->Settings->Updates->For developers->Development mode on) and rebooted.
2) download folder deleted before icu install.
3) vcpkg installed cmake 3.27 after deleting of download folder (Downloading https://github.com/Kitware/CMake/releases/download/v3.27.1/cmake-3.27.1-windows-i386.zip)

During installation of icu dependencies cmake tries to unarchive msys2-binutils-2.40-1-x86_64.pkg.tar.zst and fails on ld.exe . If this archive unpacked by tar.exe under Windows, tar does not create ld.exe (only ld.bfd.exe). If this archive unpacked under Unix, tar creates ld.exe, it is the link of ld.bfd.exe and has the same inode, it is not symbolic link). Probably it is the reason of the error: archive msys2-binutils-2.40-1-x86_64.pkg.tar.zst has link, but cmake 3.27.1 cannot work with this type of files in tar archive. 

 As result icu cannot be build and installed. 
Can you help?

**Comment by Adela0814** [comment]
What is the partition format of Z:/ ?

**Comment by VladlenPopolitov** [comment]
Z: is network drive (attached MacOsX partition, Windows run as virtual machine in Parallels Desktop version 17 under Mac Os X Monterey 12.0.1), filesystem type PrlSF (Network drive).
I moved vcpkg to drive C: , that uses NTFS, and everything works, build is successful. I suppose, the problem in Cmake 3.27 (FILE ARCHIVE_EXTRACT relatively new feature) or in Parallels, though more then 10 years I did not have any issues with Parallels file access, it always worked like native Windows drive. 
Probably documentation of vcpkg have to include recommendation to use NTFS and other FS confirmed it is working.
The easy test: to run cmake on CMakeLists.txt:

```
cmake_minimum_required(VERSION 3.27) 
project(test_archive_exctract)
set(ARCHIVE_WITH_LINK_URL  https://mirror.msys2.org/msys/x86_64/binutils-2.40-1-x86_64.pkg.tar.zst)
set(ARCHIVE_WITH_LINK_PATH ${CMAKE_BINARY_DIR}/binutils-2.40-1-x86_64.pkg.tar.zst)
set(ARCHIVE_WITH_LINK_PATH_OUT ${CMAKE_BINARY_DIR}/binutils)
file(DOWNLOAD ${ARCHIVE_WITH_LINK_URL} ${ARCHIVE_WITH_LINK_PATH} INACTIVITY_TIMEOUT 10)
file(ARCHIVE_EXTRACT INPUT "${ARCHIVE_WITH_LINK_PATH}" DESTINATION "${ARCHIVE_WITH_LINK_PATH_OUT}" )

```

**Comment by SchaichAlonso** [comment]
can you manually extract the archive using

	&(${VCPKG_ROOT}/vcpkg fetch cmake) -E tar fx ${VCPKG_ROOT}/downloads/binutils-2.40-1-x86_64.pkg.tar.zst

using powershell somewhere within z: after setting VCPKG_ROOT to the top level vcpkg directory? It should provide the same behavior but doesn't need the icu build attempt stack.

Both windows and Mac OS X have native support for hardlinks, and windows won't get confused by network file shares over it, either, however [there are reports parallels doesn't support hardlinks on network shares](https://forum.parallels.com/threads/link-inside-shared-folders.283054/). Given the thread there seems to span a decade, a workaround would be to extract the file on the Mac OS X side before running vcpkg, as vcpkg only extracts the tools if they haven't been extracted before.

**Comment by VladlenPopolitov** [comment]
@SchaichAlonso I assigned VCPKG_ROOT in Powershell, but PS gives syntax error - not expected "vcpkg" after / . If I move vcpkg inside of th variable, PS blames the unexpected "fetch". Really I understood, that Parallels filesystem has long years problem with hard links, though it is first time, when it hits me.
I moved VCPKG to HPFS partition. Thanks for support.
