### ISSUE TITLE
DCMTK library

### ISSUE THREAD

**Issue by sarthakpati** [Microsoft/vcpkg#3326]
Hi, would it be possible to add [DCMTK ](https://github.com/DCMTK/dcmtk) to vcpkg? I have created a preliminary port for this ([dcmtk.zip](https://github.com/Microsoft/vcpkg/files/1948647/dcmtk.zip)) which could do with another set of eyes on it. Thanks.

**Comment by jclay** [comment]
You'll have more luck getting this merged in if you open it as a proper pull request based on a fork of the project. You'll also have to sign Microsoft's CLA to contribute, but that's quick and easy and if the port looks good, things are generally merged in quickly.

**Comment by sarthakpati** [comment]
Thanks; I will initiate a pull request soon.

**Comment by chaosgrass** [comment]
I'm waiting for DCMTK package too, thanks! @sarthakpati @jclay

**Comment by sarthakpati** [comment]
Pull request initiated. Further discussion can continue at #3491
