### ISSUE TITLE
[bootstrap-vcpkg] Add g++-11 support 

### ISSUE THREAD

**Issue by byxrolland** [microsoft/vcpkg#33280]
Please update `bootstrap.sh` to support g++-13. It stops at g++-12.

**Comment by dg0yt** [comment]
> Please update `bootstrap.sh` to support g++-13. It stops at g++-12.

Please elaborate. Does building with g++-13 fail?

**Comment by byxrolland** [comment]
> @byxrolland, I want to confirm with you that the issue you mentioned hopes that support g++-13 means that g++-13 can be used in the process of compiling vcpkg.exe in the script or g++-13 is supported when compiling port on linux or osx, because according to the Discussion about the code in my PR: The following code will no longer run and it would be meaningless if I added it.
> 
> ```
>     if [ "x$CXX" = "x" ]; then
>         if which g++-12 >/dev/null 2>&1; then
>         if which g++-13 >/dev/null 2>&1; then
>             CXX=g++-13
>         elif which g++-12 >/dev/null 2>&1; then
>             CXX=g++-12
>         elif which g++-11 >/dev/null 2>&1; then
>             CXX=g++-11
>         elif which g++-10 >/dev/null 2>&1; then
>             CXX=g++-10
>         elif which g++-9 >/dev/null 2>&1; then
>             CXX=g++-9
>         elif which g++-8 >/dev/null 2>&1; then
>             CXX=g++-8
>         elif which g++-7 >/dev/null 2>&1; then
>             CXX=g++-7
>         elif which g++-6 >/dev/null 2>&1; then
>             CXX=g++-6
>         elif which g++ >/dev/null 2>&1; then
>             CXX=g++
>         fi
>         # If we can't find g++, allow CMake to do the look-up
>     fi
> ```

I'm using vcpkg in WSL2 with g++13 installed via linuxbrew. It seems vcpkg can't find it and only use g++11 from Ubuntu.

The code in my `bootstrap.sh`:
```
if [ "$vcpkgDownloadTool" = "ON" ]; then
    vcpkgDownloadFile "https://github.com/microsoft/vcpkg-tool/releases/download/$VCPKG_TOOL_RELEASE_TAG/$vcpkgToolName" "$vcpkgRootDir/vcpkg" $vcpkgToolReleaseSha
else
    if [ "x$CXX" = "x" ]; then
        if which g++-12 >/dev/null 2>&1; then
            CXX=g++-12
        elif which g++-11 >/dev/null 2>&1; then
            CXX=g++-11
        elif which g++-10 >/dev/null 2>&1; then
            CXX=g++-10
        elif which g++-9 >/dev/null 2>&1; then
            CXX=g++-9
        elif which g++-8 >/dev/null 2>&1; then
            CXX=g++-8
        elif which g++-7 >/dev/null 2>&1; then
            CXX=g++-7
        elif which g++-6 >/dev/null 2>&1; then
            CXX=g++-6
        elif which g++ >/dev/null 2>&1; then
            CXX=g++
        fi
        # If we can't find g++, allow CMake to do the look-up
    fi
```

**Comment by dg0yt** [comment]
This is a misunderstanding.

`bootstrap.sh` is for downloading or building the vcpkg tool. It can use the `CXX` environment variable.

Building ports is controlled by triplet files and cmake toolchain files.  
https://learn.microsoft.com/en-us/vcpkg/users/triplets  
https://learn.microsoft.com/en-us/vcpkg/contributing/maintainer-guide#portfiles-are-run-in-script-mode  

If you don't want to customize the triplet/toolchain files for specific tool names (`g++13`), you can create a directory with with the expected names (`g++`) being symlinks to the specific names, and add this directory to the `PATH`.

**Comment by byxrolland** [comment]
Yes. I understand. I just don't want to change my global setting or add unnecessary symlinks whenever I build a library in vcpkg.

**Comment by dg0yt** [comment]
> Yes. I understand. I just don't want to change my global setting or add unnecessary symlinks whenever I build a library in vcpkg.

Again, the bootstrap script has *nothing* to do with the compiler used when you "build a library in vcpkg".

The ticket can be closed IMO.
