### ISSUE TITLE
I encountered an error while running the official PCL GPU version test code.

### ISSUE THREAD

**Issue by wanglei4396** [microsoft/vcpkg#33284]
### 严重性	代码	说明	项目	文件	行	`**禁止显示状态**`
错误	LNK2019	无法解析的外部符号 "void __cdecl pcl::detail::economical_download(struct pcl::gpu::NeighborIndices const &,class std::vector<int,class std::allocator<int> > const &,unsigned __int64,class std::vector<int,class std::allocator<int> > &)" (?economical_download@detail@pcl@@YAXAEBUNeighborIndices@gpu@2@AEBV?$vector@HV?$allocator@H@std@@@std@@_KAEAV56@@Z)，函数 "void __cdecl pcl::gpu::extractEuclideanClusters<struct pcl::PointXYZ>(class std::shared_ptr<class pcl::PointCloud<struct pcl::PointXYZ> > const &,class std::shared_ptr<class pcl::gpu::Octree> const &,float,class std::vector<struct pcl::PointIndices,class std::allocator<struct pcl::PointIndices> > &,unsigned int,unsigned int)" (??$extractEuclideanClusters@UPointXYZ@pcl@@@gpu@pcl@@YAXAEBV?$shared_ptr@V?$PointCloud@UPointXYZ@pcl@@@pcl@@@std@@AEBV?$shared_ptr@VOctree@gpu@pcl@@@3@MAEAV?$vector@UPointIndices@pcl@@V?$allocator@UPointIndices@pcl@@@std@@@3@II@Z) 中引用了该符号	pcl_test1	H:\vs_test\pcl_test\pcl_test1\pcl_test1\main.obj	1	
### ### 
```[tasklist]
### Tasks
```

**Comment by JackBoosY** [comment]
Please provide the repro step and full failure log.

**Comment by wanglei4396** [comment]
#include <pcl/ModelCoefficients.h>
#include <pcl/point_types.h>
#include <pcl/io/pcd_io.h>
#include <pcl/filters/extract_indices.h>
#include <pcl/filters/voxel_grid.h>
#include <pcl/features/normal_3d.h>
#include <pcl/kdtree/kdtree.h>
#include <pcl/sample_consensus/method_types.h>
#include <pcl/sample_consensus/model_types.h>
#include <pcl/segmentation/sac_segmentation.h>
#include <pcl/segmentation/extract_clusters.h>

// The GPU specific stuff here
#include <pcl/gpu/octree/octree.hpp>
#include <pcl/gpu/containers/device_array.hpp>
#include <pcl/gpu/segmentation/gpu_extract_clusters.h>
#include <pcl/gpu/segmentation/impl/gpu_extract_clusters.hpp>

#include <time.h>

int
main(int argc, char** argv)
{
    // Read in the cloud data
    pcl::PCDReader reader;
    pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_filtered(new pcl::PointCloud<pcl::PointXYZ>);
    pcl::PCDWriter writer;
    reader.read(".rabbit", *cloud_filtered);

    /////////////////////////////////////////////
    /// CPU VERSION
    /////////////////////////////////////////////

    std::cout << "INFO: PointCloud_filtered still has " << cloud_filtered->size() << " Points " << std::endl;
    clock_t tStart = clock();
    // Creating the KdTree object for the search method of the extraction
    pcl::search::KdTree<pcl::PointXYZ>::Ptr tree(new pcl::search::KdTree<pcl::PointXYZ>);
    tree->setInputCloud(cloud_filtered);

    std::vector<pcl::PointIndices> cluster_indices;
    pcl::EuclideanClusterExtraction<pcl::PointXYZ> ec;
    ec.setClusterTolerance(0.02); // 2cm
    ec.setMinClusterSize(100);
    ec.setMaxClusterSize(25000);
    ec.setSearchMethod(tree);
    ec.setInputCloud(cloud_filtered);
    ec.extract(cluster_indices);

    printf("CPU Time taken: %.2fs\n", (double)(clock() - tStart) / CLOCKS_PER_SEC);

    int j = 0;
    for (const pcl::PointIndices& cluster : cluster_indices)
    {
        pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_cluster(new pcl::PointCloud<pcl::PointXYZ>);
        for (const auto& index : (cluster.indices))
            cloud_cluster->push_back((*cloud_filtered)[index]); //*
        cloud_cluster->width = cloud_cluster->size();
        cloud_cluster->height = 1;
        cloud_cluster->is_dense = true;

        std::cout << "PointCloud representing the Cluster: " << cloud_cluster->size() << " data points." << std::endl;
        std::stringstream ss;
        ss << "cloud_cluster_" << j << ".pcd";
        writer.write<pcl::PointXYZ>(ss.str(), *cloud_cluster, false); //*
        j++;
    }

    /////////////////////////////////////////////
    /// GPU VERSION
    /////////////////////////////////////////////

    std::cout << "INFO: starting with the GPU version" << std::endl;

    tStart = clock();

    pcl::gpu::Octree::PointCloud cloud_device;
    cloud_device.upload(cloud_filtered->points);

    pcl::gpu::Octree::Ptr octree_device(new pcl::gpu::Octree);
    octree_device->setCloud(cloud_device);
    octree_device->build();

    std::vector<pcl::PointIndices> cluster_indices_gpu;
    pcl::gpu::EuclideanClusterExtraction<pcl::PointXYZ> gec;
    gec.setClusterTolerance(0.02); // 2cm
    gec.setMinClusterSize(100);
    gec.setMaxClusterSize(25000);
    gec.setSearchMethod(octree_device);
    gec.setHostCloud(cloud_filtered);
    gec.extract(cluster_indices_gpu);
    //  octree_device.clear();

    printf("GPU Time taken: %.2fs\n", (double)(clock() - tStart) / CLOCKS_PER_SEC);
    std::cout << "INFO: stopped with the GPU version" << std::endl;

    j = 0;
    for (const pcl::PointIndices& cluster : cluster_indices_gpu)
    {
        pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_cluster_gpu(new pcl::PointCloud<pcl::PointXYZ>);
        for (const auto& index : (cluster.indices))
        cloud_cluster_gpu->push_back((*cloud_filtered)[index]); //*
        cloud_cluster_gpu->width = cloud_cluster_gpu->size();
        cloud_cluster_gpu->height = 1;
        cloud_cluster_gpu->is_dense = true;

        std::cout << "PointCloud representing the Cluster: " << cloud_cluster_gpu->size() << " data points." << std::endl;
        std::stringstream ss;
        ss << "gpu_cloud_cluster_" << j << ".pcd";
        writer.write<pcl::PointXYZ>(ss.str(), *cloud_cluster_gpu, false); //*
        j++;
    }

    return (0);
}
![image](https://github.com/microsoft/vcpkg/assets/77763561/710958a9-051e-47e5-804f-1278b6d82618)

- pcl 1.13
-  cuda 11.6
- visual studio 2019

**Comment by MonicaLiu0311** [comment]
Sorry I have not reproduced this issue with your code:

![image](https://github.com/microsoft/vcpkg/assets/110024546/6e9fb415-5c5a-414d-a253-233bc558e8bb)

**Comment by MonicaLiu0311** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
