### ISSUE TITLE
[abseil] build failure

### ISSUE THREAD

**Issue by jalegido** [microsoft/vcpkg#33294]
### Operating system

Windows 10

### Compiler

MSVC 2019

### Steps to reproduce the behavior

```Shell
vcpkg.exe install abseil:x64-windows
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
    abseil:x64-windows -> 20230802.0
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\jjll\AppData\Local\vcpkg\archives in 275 us. Use --debug to see more details.
Installing 1/1 abseil:x64-windows...
Building abseil:x64-windows...
-- Using cached abseil-abseil-cpp-20230802.0.tar.gz.
-- Cleaning sources at C:/Desarrollo/vcpkg/buildtrees/abseil/src/20230802.0-d88f1acef0.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Desarrollo/vcpkg/downloads/abseil-abseil-cpp-20230802.0.tar.gz
-- Using source at C:/Desarrollo/vcpkg/buildtrees/abseil/src/20230802.0-d88f1acef0.clean
-- Found external ninja('1.11.1').
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/Desarrollo/vcpkg/downloads/tools/cmake-3.27.1-windows/cmake-3.27.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: C:/Desarrollo/vcpkg/buildtrees/abseil/x64-windows-dbg
    See logs for more information:
      C:\Desarrollo\vcpkg\buildtrees\abseil\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/abseil/portfile.cmake:32 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

### Additional context

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/12395452/install-x64-windows-dbg-out.log)
After investigating the problem I see that ninja generated PRE_LINK command:
cmd.exe /C "cmd.exe /C "C:\Desarrollo\vcpkg\downloads\tools\cmake-3.27.1-windows\cmake-3.27.1-windows-i386\bin\cmake.exe -E __create_def C:\Desarrollo\vcpkg\buildtrees\abseil\x64-windows-dbg\absl\CMakeFiles\abseil_dll.dir\.\exports.def C:\Desarrollo\vcpkg\buildtrees\abseil\x64-windows-dbg\absl\CMakeFiles\abseil_dll.dir\.\exports.def.objs && cd C:\Desarrollo\vcpkg\buildtrees\abseil\x64-windows-dbg" && C:\Desarrollo\vcpkg\downloads\tools\cmake-3.27.1-windows\cmake-3.27.1-windows-i386\bin\cmake.exe -E vs_link_dll --intdir=absl\CMakeFiles\abseil_dll.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MIB055~1\2019\PROFES~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe  @CMakeFiles\abseil_dll.rsp  /out:bin\abseil_dll.dll /implib:absl\abseil_dll.lib /pdb:bin\abseil_dll.pdb /dll /version:0.0 /machine:x64 /nologo    /debug /INCREMENTAL  /DEF:absl\CMakeFiles\abseil_dll.dir\.\exports.def  && cd ."
 is not in the valid order.
I think the first command must be:
cmd.exe /C "cmd.exe /C "cd C:\Desarrollo\vcpkg\buildtrees\abseil\x64-windows-dbg && C:\Desarrollo\vcpkg\downloads\tools\cmake-3.27.1-windows\cmake-3.27.1-windows-i386\bin\cmake.exe -E __create_def C:\Desarrollo\vcpkg\buildtrees\abseil\x64-windows-dbg\absl\CMakeFiles\abseil_dll.dir\.\exports.def C:\Desarrollo\vcpkg\buildtrees\abseil\x64-windows-dbg\absl\CMakeFiles\abseil_dll.dir\.\exports.def.objs"

First, ninja must change the current directory; and after ninja must execute cmake __create_def in this directory.
Currently the current directory is not changed, and so cmake returns with an error because it doesn't find the requested local files.

**Comment by dg0yt** [comment]
... or it is just an antivirus access race. No error in CI, and here the error message is:
~~~
FINAL LINK: command "C:\PROGRA~2\MIB055~1\2019\PROFES~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe @CMakeFiles\abseil_dll.rsp /out:bin\abseil_dll.dll /implib:absl\abseil_dll.lib /pdb:bin\abseil_dll.pdb /dll /version:0.0 /machine:x64 /nologo /debug /INCREMENTAL /DEF:absl\CMakeFiles\abseil_dll.dir\.\exports.def /MANIFEST /MANIFESTFILE:absl\CMakeFiles\abseil_dll.dir/intermediate.manifest absl\CMakeFiles\abseil_dll.dir/manifest.res" failed (exit code 1168) with the following output:
LINK : fatal error LNK1168: cannot open bin\abseil_dll.dll for writing
~~~

**Comment by jalegido** [comment]
Thank you, @dg0yt .
I've checked this log file with previous abseil version, and the line is similar. First, ninja execute cmake.exe -E __create_def .... and second it changes the directory.
It's possible I have a problem with my antivirus.
