### ISSUE TITLE
Error on multiple find_package calls for the same library

### ISSUE THREAD

**Issue by petersteneteg** [microsoft/vcpkg#33297]
**Describe the bug**
Calling find_package in cmake multiple times on the same library leads to cmake errors for trying to define the same library multiple times.

For example: 
* jsoncpp adds JsonCpp::JsonCpp without any checks for if it already exists.
* liblzma adds LibLZMA::LibLZMA without any checks for if it already exists.
* utf9cpp adds utf8::cpp without any checks for if it already exists.

I suppose I should report this upstream and not complain here in principle. But I think it would be great if there was a CI test for this in vcpkg to avoid this happening. It gets quite confusing for users of vcpkg to track down these problems. 

**To Reproduce**
1. ./vcpkg install jsoncpp 
2. in cmake run
> find_package(jsoncpp)
> find_package(jsoncpp)

**Comment by dg0yt** [comment]
CMake code generated by CMake (export) should show this problem, but hand-written CMake code can.
If the code isn't added by vcpkg, it should be fixed upstream.
- jsoncpp: There is a problem in `jsoncpp-namespaced-targets.cmake`.
- liblzma: There is a problem in `liblzma-config.cmake`.
- utfcpp: There is a problem `utf8cppConfig.cmake`.

Fixing it already in vcpkg shouldn't need to wait for upstream. But upstream should really be notified.



> I think it would be great if there was a CI test for this in vcpkg to avoid this happening. It gets quite confusing for users of vcpkg to track down these problems.

This needs special conditions to trigger, and so it is rare. There are some more frequent problems which should get CI tests (such as missing `find_dependency`). Unfortunately, build script solutions were rejected in the past, and nobody stepped up to add the desired hooks to the vcpkg tool.

**Comment by petersteneteg** [comment]
I think this is fixed in liblzma and utfcpp but still a issue in jsoncpp

**Comment by dg0yt** [comment]
> jsoncpp

... has a pure cmake-generated config and should be affected.

**Comment by dg0yt** [comment]
> > jsoncpp
> 
> ... has a pure cmake-generated config ...

Wait, it is still broken in "namespaced-targets" :facepalm:
