### ISSUE TITLE
poco static build is broken and installs older version

### ISSUE THREAD

**Issue by bangusi** [Microsoft/vcpkg#3331]
The command:
`vcpkg install poco:x65-windows-static`
does not build static libs. 
For example you get `PocoUtilmd.lib` instead of `PocoUtilmt.lib`

Also the latest Poco is 1.9.0
vcpkg still installs 1.8.1

**Comment by ras0219-msft** [comment]
Thanks for posting this issue! Both of the problems have been addressed in master :).
