### ISSUE TITLE
[glfw] installed pkg-config wrong on Windows

### ISSUE THREAD

**Issue by moritz-h** [microsoft/vcpkg#33337]
**Describe the bug**
The pkg-config files installed with GLFW refers to "-lglfw3", but the installed lib file is called `lib/glfw3dll.lib`. GLFW seems to use a suffix for building a shared lib, see https://github.com/glfw/glfw/blob/3.3.8/src/CMakeLists.txt#L169

**Environment**
- OS: Windows

**Expected behavior**
pkg-config file to be correct.

**Additional context**
This problem was observed while trying to migrate `tracy` to use `vcpkg_msbuild_install` in #33098. It seems correct pkg-config files are required for this. (Ping @Neumann-A for status of this issue)

**Comment by jimwang118** [comment]
You can call this port using the following usage.
```
find_package (PkgConfig REQUIRED)
pkg_check_modules (GLFW REQUIRED IMPORTED_TARGET glfw3)
target_link_libraries(testzstd PRIVATE PkgConfig::GLFW)
```

**Comment by Neumann-A** [comment]
The problem ist that the lib name in the pc file seems to be incorrect.

**Comment by jimwang118** [comment]
> The problem ist that the lib name in the pc file seems to be incorrect.

Is the lib name in PC should be `glfw3dll`?

**Comment by moritz-h** [comment]
> Is the lib name in PC should be `glfw3dll`?

Yes this. But only on Windows and only when built as shared lib. Otherwise the name glfw3 is correct. On Windows when building as shared lib they attach the suffix "dll" to the library name, but the suffix is not set in the PC file.
I tried GLFW directly without vcpkg and it seems to be an upstream bug already.

**Comment by moritz-h** [comment]
Made an upstream PR with a potential fix: https://github.com/glfw/glfw/pull/2386
