### ISSUE TITLE
[grpc] Build error

### ISSUE THREAD

**Issue by DavidDobreen** [microsoft/vcpkg#33342]
Package: grpc[codegen,core]:arm64-osx -> 1.51.1

**Host Environment**

- Host: arm64-osx
- Compiler: AppleClang 14.0.3.14030022
-    vcpkg-tool version: 2023-08-09-9990a4c9026811a312cb2af78bf77f3d9d288416
    vcpkg-scripts version: 417119555 2023-08-22 (21 hours ago)

**To Reproduce**

`vcpkg install grpc`
**Failure logs**

```
-- Using cached grpc-grpc-v1.51.1.tar.gz.
-- Cleaning sources at /Users/mac/.clion-vcpkg/vcpkg/buildtrees/grpc/src/v1.51.1-1066d25324.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/mac/.clion-vcpkg/vcpkg/downloads/grpc-grpc-v1.51.1.tar.gz
-- Applying patch 00001-fix-uwp.patch
-- Applying patch 00002-static-linking-in-linux.patch
-- Applying patch 00003-undef-base64-macro.patch
-- Applying patch 00004-link-gdi32-on-windows.patch
-- Applying patch 00005-fix-uwp-error.patch
-- Applying patch 00009-use-system-upb.patch
-- Applying patch snprintf.patch
-- Applying patch 00012-fix-use-cxx17.patch
-- Applying patch 00014-pkgconfig-upbdefs.patch
-- Applying patch 00015-disable-download-archive.patch
-- Using source at /Users/mac/.clion-vcpkg/vcpkg/buildtrees/grpc/src/v1.51.1-1066d25324.clean
-- Found external ninja('1.11.1').
-- Configuring arm64-osx
-- Building arm64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: /Users/mac/.clion-vcpkg/vcpkg/downloads/tools/cmake-3.27.1-osx/cmake-3.27.1-macos-universal/CMake.app/Contents/bin/cmake --build . --config Debug --target install -- -v -j11
    Working Directory: /Users/mac/.clion-vcpkg/vcpkg/buildtrees/grpc/arm64-osx-dbg
    See logs for more information:
      /Users/mac/.clion-vcpkg/vcpkg/buildtrees/grpc/install-arm64-osx-dbg-out.log
      /Users/mac/.clion-vcpkg/vcpkg/buildtrees/grpc/install-arm64-osx-dbg-err.log

Call Stack (most recent call first):
  installed/arm64-osx/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/arm64-osx/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/grpc/portfile.cmake:69 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)



```
<details><summary>/Users/mac/.clion-vcpkg/vcpkg/buildtrees/grpc/install-arm64-osx-dbg-out.log</summary>

```
Change Dir: '/Users/mac/.clion-vcpkg/vcpkg/buildtrees/grpc/arm64-osx-dbg'

Run Build Command(s): /usr/local/bin/ninja -v -v -j11 install
```
</details>
<details><summary>/Users/mac/.clion-vcpkg/vcpkg/buildtrees/grpc/install-arm64-osx-dbg-err.log</summary>

```
ninja: error: '_gRPC_CPP_PLUGIN-NOTFOUND', needed by '/Users/mac/.clion-vcpkg/vcpkg/buildtrees/grpc/arm64-osx-dbg/gens/src/proto/grpc/reflection/v1alpha/reflection.pb.cc', missing and no known rule to make it
```
</details>

**Comment by JonLiu1993** [comment]
This error cannot be reproduced on the "x64-osx" triplet, so I tagged `community-triplet`.

**Comment by bold84** [comment]
Can't reproduce on arm64-osx either:

Installing 8/8 grpc:arm64-osx...
Building grpc[codegen,core]:arm64-osx...
warning: -- Using community triplet arm64-osx. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /Users/ben/Development/bold84/vcpkg/triplets/community/arm64-osx.cmake
-- Downloading https://github.com/grpc/grpc/archive/v1.51.1.tar.gz -> grpc-grpc-v1.51.1.tar.gz...
-- Extracting source /Users/ben/Development/bold84/vcpkg/downloads/grpc-grpc-v1.51.1.tar.gz
-- Applying patch 00001-fix-uwp.patch
-- Applying patch 00002-static-linking-in-linux.patch
-- Applying patch 00003-undef-base64-macro.patch
-- Applying patch 00004-link-gdi32-on-windows.patch
-- Applying patch 00005-fix-uwp-error.patch
-- Applying patch 00009-use-system-upb.patch
-- Applying patch snprintf.patch
-- Applying patch 00012-fix-use-cxx17.patch
-- Applying patch 00014-pkgconfig-upbdefs.patch
-- Applying patch 00015-disable-download-archive.patch
-- Using source at /Users/ben/Development/bold84/vcpkg/buildtrees/grpc/src/v1.51.1-1066d25324.clean
-- Found external ninja('1.11.1').
-- Configuring arm64-osx
-- Building arm64-osx-dbg
-- Building arm64-osx-rel
-- Fixing pkgconfig file: /Users/ben/Development/bold84/vcpkg/packages/grpc_arm64-osx/lib/pkgconfig/gpr.pc
-- Fixing pkgconfig file: /Users/ben/Development/bold84/vcpkg/packages/grpc_arm64-osx/lib/pkgconfig/grpc++.pc
-- Fixing pkgconfig file: /Users/ben/Development/bold84/vcpkg/packages/grpc_arm64-osx/lib/pkgconfig/grpc++_unsecure.pc
-- Fixing pkgconfig file: /Users/ben/Development/bold84/vcpkg/packages/grpc_arm64-osx/lib/pkgconfig/grpc.pc
-- Fixing pkgconfig file: /Users/ben/Development/bold84/vcpkg/packages/grpc_arm64-osx/lib/pkgconfig/grpc_unsecure.pc
-- Fixing pkgconfig file: /Users/ben/Development/bold84/vcpkg/packages/grpc_arm64-osx/debug/lib/pkgconfig/gpr.pc
-- Fixing pkgconfig file: /Users/ben/Development/bold84/vcpkg/packages/grpc_arm64-osx/debug/lib/pkgconfig/grpc++.pc
-- Fixing pkgconfig file: /Users/ben/Development/bold84/vcpkg/packages/grpc_arm64-osx/debug/lib/pkgconfig/grpc++_unsecure.pc
-- Fixing pkgconfig file: /Users/ben/Development/bold84/vcpkg/packages/grpc_arm64-osx/debug/lib/pkgconfig/grpc.pc
-- Fixing pkgconfig file: /Users/ben/Development/bold84/vcpkg/packages/grpc_arm64-osx/debug/lib/pkgconfig/grpc_unsecure.pc
-- Installing: /Users/ben/Development/bold84/vcpkg/packages/grpc_arm64-osx/share/grpc/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 22 s.
Elapsed time to handle grpc:arm64-osx: 3.2 min
Total install time: 4 min
grpc provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(gRPC CONFIG REQUIRED)
    # note: 7 additional targets are not displayed.
    target_link_libraries(main PRIVATE gRPC::gpr gRPC::grpc gRPC::grpc++ gRPC::grpc++_alts)

**Comment by COMEBACKISREAL** [comment]
> Can't reproduce on arm64-osx either:
> 
> ```
> Installing 8/8 grpc:arm64-osx...
> Building grpc[codegen,core]:arm64-osx...
> warning: -- Using community triplet arm64-osx. This triplet configuration is not guaranteed to succeed.
> -- [COMMUNITY] Loading triplet configuration from: /Users/ben/Development/bold84/vcpkg/triplets/community/arm64-osx.cmake
> -- Downloading https://github.com/grpc/grpc/archive/v1.51.1.tar.gz -> grpc-grpc-v1.51.1.tar.gz...
> -- Extracting source /Users/ben/Development/bold84/vcpkg/downloads/grpc-grpc-v1.51.1.tar.gz
> -- Applying patch 00001-fix-uwp.patch
> -- Applying patch 00002-static-linking-in-linux.patch
> -- Applying patch 00003-undef-base64-macro.patch
> -- Applying patch 00004-link-gdi32-on-windows.patch
> -- Applying patch 00005-fix-uwp-error.patch
> -- Applying patch 00009-use-system-upb.patch
> -- Applying patch snprintf.patch
> -- Applying patch 00012-fix-use-cxx17.patch
> -- Applying patch 00014-pkgconfig-upbdefs.patch
> -- Applying patch 00015-disable-download-archive.patch
> -- Using source at /Users/ben/Development/bold84/vcpkg/buildtrees/grpc/src/v1.51.1-1066d25324.clean
> -- Found external ninja('1.11.1').
> -- Configuring arm64-osx
> -- Building arm64-osx-dbg
> -- Building arm64-osx-rel
> -- Fixing pkgconfig file: /Users/ben/Development/bold84/vcpkg/packages/grpc_arm64-osx/lib/pkgconfig/gpr.pc
> -- Fixing pkgconfig file: /Users/ben/Development/bold84/vcpkg/packages/grpc_arm64-osx/lib/pkgconfig/grpc++.pc
> -- Fixing pkgconfig file: /Users/ben/Development/bold84/vcpkg/packages/grpc_arm64-osx/lib/pkgconfig/grpc++_unsecure.pc
> -- Fixing pkgconfig file: /Users/ben/Development/bold84/vcpkg/packages/grpc_arm64-osx/lib/pkgconfig/grpc.pc
> -- Fixing pkgconfig file: /Users/ben/Development/bold84/vcpkg/packages/grpc_arm64-osx/lib/pkgconfig/grpc_unsecure.pc
> -- Fixing pkgconfig file: /Users/ben/Development/bold84/vcpkg/packages/grpc_arm64-osx/debug/lib/pkgconfig/gpr.pc
> -- Fixing pkgconfig file: /Users/ben/Development/bold84/vcpkg/packages/grpc_arm64-osx/debug/lib/pkgconfig/grpc++.pc
> -- Fixing pkgconfig file: /Users/ben/Development/bold84/vcpkg/packages/grpc_arm64-osx/debug/lib/pkgconfig/grpc++_unsecure.pc
> -- Fixing pkgconfig file: /Users/ben/Development/bold84/vcpkg/packages/grpc_arm64-osx/debug/lib/pkgconfig/grpc.pc
> -- Fixing pkgconfig file: /Users/ben/Development/bold84/vcpkg/packages/grpc_arm64-osx/debug/lib/pkgconfig/grpc_unsecure.pc
> -- Installing: /Users/ben/Development/bold84/vcpkg/packages/grpc_arm64-osx/share/grpc/copyright
> -- Performing post-build validation
> Stored binaries in 1 destinations in 22 s.
> Elapsed time to handle grpc:arm64-osx: 3.2 min
> Total install time: 4 min
> grpc provides CMake targets:
> 
>     # this is heuristically generated, and may not be correct
>     find_package(gRPC CONFIG REQUIRED)
>     # note: 7 additional targets are not displayed.
>     target_link_libraries(main PRIVATE gRPC::gpr gRPC::grpc gRPC::grpc++ gRPC::grpc++_alts)
> ```
> 
> @DavidDobreen maybe CLion does something funky to the environment or passing funny arguments to CMake...

Maybe this will help you
[install-arm64-osx-dbg-out.log](https://github.com/microsoft/vcpkg/files/12479944/install-arm64-osx-dbg-out.log)

``` ./vcpkg install grpc                               
Computing installation plan...
The following packages will be built and installed:
    grpc[codegen,core]:arm64-osx -> 1.51.1
Detecting compiler hash for triplet arm64-osx...
Restored 0 package(s) from /Users/minato/.cache/vcpkg/archives in 8.62 us. Use --debug to see more details.
Installing 1/1 grpc:arm64-osx...
Building grpc[codegen,core]:arm64-osx...
warning: -- Using community triplet arm64-osx. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /Users/minato/work/vcpkg/triplets/community/arm64-osx.cmake
-- Using cached grpc-grpc-v1.51.1.tar.gz.
-- Extracting source /Users/minato/work/vcpkg/downloads/grpc-grpc-v1.51.1.tar.gz
-- Applying patch 00001-fix-uwp.patch
-- Applying patch 00002-static-linking-in-linux.patch
-- Applying patch 00003-undef-base64-macro.patch
-- Applying patch 00004-link-gdi32-on-windows.patch
-- Applying patch 00005-fix-uwp-error.patch
-- Applying patch 00009-use-system-upb.patch
-- Applying patch snprintf.patch
-- Applying patch 00012-fix-use-cxx17.patch
-- Applying patch 00014-pkgconfig-upbdefs.patch
-- Applying patch 00015-disable-download-archive.patch
-- Using source at /Users/minato/work/vcpkg/buildtrees/grpc/src/v1.51.1-1066d25324.clean
-- Found external ninja('1.11.1').
-- Configuring arm64-osx
-- Building arm64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: /Users/minato/work/vcpkg/downloads/tools/cmake-3.27.1-osx/cmake-3.27.1-macos-universal/CMake.app/Contents/bin/cmake --build . --config Debug --target install -- -v -j11
    Working Directory: /Users/minato/work/vcpkg/buildtrees/grpc/arm64-osx-dbg
    See logs for more information:
      /Users/minato/work/vcpkg/buildtrees/grpc/install-arm64-osx-dbg-out.log

Call Stack (most recent call first):
  installed/arm64-osx/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/arm64-osx/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/grpc/portfile.cmake:69 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)


error: building grpc:arm64-osx failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+grpc
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[grpc]+Build+error&body=Copy+issue+body+from+%2FUsers%2Fminato%2Fwork%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md```
