### ISSUE TITLE
[darknet] Build error

### ISSUE THREAD

**Issue by qjrm2333** [microsoft/vcpkg#33355]
Package: darknet[core,cuda,cudnn,full,opencv-cuda]:x64-windows -> 2022-03-06#3

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.29.30151.0
-    vcpkg-tool version: 2023-08-09-9990a4c9026811a312cb2af78bf77f3d9d288416
    vcpkg-scripts version: 12640ddf0 2023-08-23 (3 hours ago)

**To Reproduce**

`vcpkg install darknet[full]:x64-windows`
**Failure logs**

```
-- Using cached AlexeyAB-darknet-8a0bf84c19e38214219dbd3345f04ce778426c57.tar.gz.
-- Cleaning sources at D:/Task/vcpkg/buildtrees/darknet/src/e778426c57-96aa9384e0.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Task/vcpkg/downloads/AlexeyAB-darknet-8a0bf84c19e38214219dbd3345f04ce778426c57.tar.gz
-- Applying patch fix-dependence-getopt.patch
-- Using source at D:/Task/vcpkg/buildtrees/darknet/src/e778426c57-96aa9384e0.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_copy_tools.cmake:36 (message):
  Couldn't find tool "uselib_track":

      "D:/Task/vcpkg/packages/darknet_x64-windows/bin/uselib_track.exe" does not exist
Call Stack (most recent call first):
  ports/darknet/portfile.cmake:45 (vcpkg_copy_tools)
  scripts/ports.cmake:147 (include)



```

**Comment by FrankXie05** [comment]
@qjrm2333 Sorry for the late reply, could you provide the contents of directory `D:/Task/vcpkg/packages/darknet_x64-windows/bin` and your console output? :)

**Comment by whynotAC** [comment]
.\vcpkg.exe install --recurse "darknet[opencv-cuda]"
warning: In the September 2023 release, the default triplet for vcpkg libraries changed from x86-windows to the detected host triplet (x64-windows). For the old behavior, add --triplet x86-windows . To suppress this message, add --triplet x64-windows .
Computing installation plan...
The following packages will be built and installed:
    darknet[core,opencv-cuda]:x64-windows -> 2022-03-06#3
Detecting compiler hash for triplet x64-windows...
-- Automatically setting %HTTP(S)_PROXY% environment variables to "127.0.0.1:51547".
Restored 0 package(s) from C:\Users\Admin\AppData\Local\vcpkg\archives in 103 us. Use --debug to see more details.
Installing 1/1 darknet:x64-windows...
Building darknet[core,opencv-cuda]:x64-windows...
-- Using cached AlexeyAB-darknet-8a0bf84c19e38214219dbd3345f04ce778426c57.tar.gz.
-- Cleaning sources at E:/github/vcpkg/buildtrees/darknet/src/e778426c57-96aa9384e0.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/github/vcpkg/downloads/AlexeyAB-darknet-8a0bf84c19e38214219dbd3345f04ce778426c57.tar.gz
-- Applying patch fix-dependence-getopt.patch
-- Using source at E:/github/vcpkg/buildtrees/darknet/src/e778426c57-96aa9384e0.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_copy_tools.cmake:36 (message):
  Couldn't find tool "uselib_track":

      "E:/github/vcpkg/packages/darknet_x64-windows/bin/uselib_track.exe" does not exist
Call Stack (most recent call first):
  ports/darknet/portfile.cmake:45 (vcpkg_copy_tools)
  scripts/ports.cmake:170 (include)

Path:E:\github\vcpkg\packages\darknet_x64-windows\bin
File: darknet.dll

**Comment by whynotAC** [comment]
./vcpkg install --recurse "darknet[opencv-cuda]"  success

`CMake Error at E:/github/vcpkg/installed/x64-windows/share/darknet/DarknetTargets.cmake:60 (set_target_properties):
  The link interface of target "Darknet::dark" contains:

    PThreads_windows::PThreads_windows

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  E:/github/vcpkg/installed/x64-windows/share/darknet/DarknetConfig.cmake:44 (include)
  E:/github/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  CMakeLists.txt:20 (find_package)`
  
  Which package should be installed？
@FrankXie05

**Comment by FrankXie05** [comment]
@whynotAC Please run connamd `./vcpkg install pthreads`.
