### ISSUE TITLE
libmysql:x86-windows BUILD_FAILED

### ISSUE THREAD

**Issue by orgot** [Microsoft/vcpkg#3335]
>vcpkg.exe install osg

The following packages will be built and installed:
  * expat[core]:x86-windows
  * freetype[core]:x86-windows
  * gdal[core]:x86-windows
  * giflib[core]:x86-windows
  * ilmbase[core]:x86-windows
  * jasper[core]:x86-windows
  * libiconv[core]:x86-windows
  * libjpeg-turbo[core]:x86-windows
  * libmysql[core]:x86-windows
  * libpq[core]:x86-windows
  * libwebp[core]:x86-windows
  * libxml2[core]:x86-windows
  * openexr[core]:x86-windows
  * openjpeg[core]:x86-windows
    osg[core]:x86-windows
  * sqlite3[core]:x86-windows
  * tiff[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/17: libmysql:x86-windows
Building package libmysql[core]:x86-windows...
-- CURRENT_INSTALLED_DIR=D:/Libs/vcpkg-master/installed/x86-windows
-- DOWNLOADS=D:/Libs/vcpkg-master/downloads
-- CURRENT_PACKAGES_DIR=D:/Libs/vcpkg-master/packages/libmysql_x86-windows
-- CURRENT_BUILDTREES_DIR=D:/Libs/vcpkg-master/buildtrees/libmysql
-- CURRENT_PORT_DIR=D:/Libs/vcpkg-master/ports/libmysql/.
CMake Error at D:/Libs/vcpkg-master/ports/libmysql/portfile.cmake:10 (message):
  Oracle has dropped support in libmysql for 32-bit Windows.
Call Stack (most recent call first):
  D:/Libs/vcpkg-master/scripts/ports.cmake:72 (include)

Error: Building package libmysql:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libmysql:x86-windows
  Vcpkg version: 0.0.110-unknownhash

**Comment by jimmysoda** [comment]
The Windows 32-bit libmysql problem is already reported under #3029. Note that `vcpkg` counter-intuitively builds 32-bit by default in Windows (`x86-windows`) instead of 64-bit as reported in #1254.  Try installing OSG for Windows 64-bit if you do not specifically need Windows 32-bit:

    > vcpkg.exe install osg:x64-windows

**Comment by EngineerZhang** [comment]
Hi，I try `vcpkg.exe install osg:x64-windows`and still got wrong 
`Elapsed time for package tiff:x64-windows: 3.383 min
Starting package 72/75: ilmbase:x64-windows
Building package ilmbase[core]:x64-windows...
-- Downloading http://download.savannah.nongnu.org/releases/openexr/ilmbase-2.2.1.tar.gz...
-- Downloading http://download.savannah.nongnu.org/releases/openexr/ilmbase-2.2.1.tar.gz... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:156 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/ilmbase/portfile.cmake:10 (vcpkg_download_distfile)
  scripts/ports.cmake:71 (include)


Error: Building package ilmbase:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ilmbase:x64-windows
  Vcpkg version: 2018.10.20-nohash`How can I do?Thanks a lot!

**Comment by JackBoosY** [comment]
Hi @orgot , thanks for reporting this issue!
Sorry, libmsql can only support x64 build now(official [here](https://github.com/mysql/mysql-server/blob/577fbcf856cd693434d554545d499559bcdd3695/cmake/os/Windows.cmake#L56-L57)). So we can not solve this problem.
You may be able to use libmariadb instead, which (iiuc) supports MySQL and still works for 32-bit.
Thanks.
