### ISSUE TITLE
[icu] building icu with x64-windows-static produces incomplete icudt.lib

### ISSUE THREAD

**Issue by IRebo** [microsoft/vcpkg#33358]
**Describe the bug**
The generated icudt.lib is not correct size and doesnt contain the icu databases if icu is built as static for x64 windows. (works fine for x86 static windows)

Seems to be connected

**Environment**
- OS: windows 10 10.0.19045.3324
- Compiler: VS2022 17.7.1

**To Reproduce**
1. ./vcpkg install icu:x64-windows-static
2. check .\installed\x64-windows-static\lib\icudt.lib

**Expected behavior**
the generated lib file should contain the database like the x86 one

**Additional context**
Running for example "vcpkg install icu:x64-windows-static --recurse --binarysource=clear" produces .\installed\x64-windows-static\lib\icudt.lib that is only 56kb and doesnt actually contain the icu database. Running the same command for x86 produces a correct 30mb lib file. Seems to be connected to #29196 since using icu[core,tools] generates a working lib file.

**Comment by Adela0814** [comment]
Confirmed. I can repro this issue in my side.

**Comment by dg0yt** [comment]
> The generated icudt.lib is not correct size and doesnt contain the icu databases if icu is built as static for x64 windows. (works fine for x86 static windows)

x64-windows `lib/icudtd.lib` is a Windows import lib. The actual binary artifact is `bin/icudtXX.dll`.
In contrast, for static library linkage, there is no DLL, and `lib/icudtd.lib` ist the actual binary artifact.

With that context, is there any real problem?

**Comment by IRebo** [comment]
Well it makes your application to not run correctly if using the x64 static build since the missing resources are not embedded. The x86 build does include them and the application works fine.

**Comment by dg0yt** [comment]
I think I was able to reproduce it with mingw, and I can prepare a PR.
