### ISSUE TITLE
[zlib] update to 1.3

### ISSUE THREAD

**Issue by RadonTRD** [microsoft/vcpkg#33357]
### Library name

zlib

### New version number

1.3

### Other information that may be useful (release notes, etc...)

zlib 1.3 from [zlib Home Site](https://www.zlib.net/)

Version 1.3 has these key updates from 1.2.13:
- Building using K&R (pre-ANSI) function definitions is no longer supported.
- Fixed a bug in deflateBound() for level 0 and memLevel 9.
- Fixed a bug when gzungetc() is used immediately after gzopen().
- Fixed a bug when using gzflush() with a very small buffer.
- Fixed a crash when gzsetparams() is attempted for a transparent write.
- Fixed test/example.c to work with FORCE_STORED.
- Fixed minizip to allow it to open an empty zip file.
- Fixed reading disk number start on zip64 files in minizip.
- Fixed a logic error in minizip argument processing.

**Comment by xavier2k6** [comment]
PR already open for this -> https://github.com/microsoft/vcpkg/pull/33310
