### ISSUE TITLE
 libbson:x64-osx: BUILD_FAILED

### ISSUE THREAD

**Issue by abirbasak** [microsoft/vcpkg#3336]
On Mac
./vcpkg install mongo-c-driver
CMake Error at ports/libbson/portfile.cmake:48 (file):
  file RENAME failed to rename

    /opt/vcpkg/packages/libbson_x64-osx/lib/bson-static-1.0.lib

  to

    /opt/vcpkg/packages/libbson_x64-osx/lib/bson-1.0.lib

  because: No such file or directory

Call Stack (most recent call first):
  scripts/ports.cmake:72 (include)

Error: Building package libbson:x64-osx failed with: BUILD_FAILED

**Comment by PhoebeHui** [comment]
@abirbasak, does the problem persist for you?

**Comment by PhoebeHui** [comment]
@abirbasak, please reopen this if it still be an problem for you.
