### ISSUE TITLE
OpenVINO Library Missing in Vcpkg

### ISSUE THREAD

**Issue by sdcb** [microsoft/vcpkg#33379]
**Describe the bug**
The OpenVINO library, previously available in Vcpkg, has unexpectedly disappeared. The `vcpkg search openvino` command used to list OpenVINO as an available library, now it's no longer listed.

**Environment**
- OS: Windows 10/Windows Server 2022
- Compiler: MSVC2022

**To Reproduce**
1. Run `vcpkg search openvino`
2. Observe that OpenVINO is no longer listed.

Previous command output:
```
PS C:\Users\Administrator> vcpkg search openvino
openvino                 2023-06-11#3     Intel® Distribution of OpenVINO™ toolkit is an open-source toolkit for ...
openvino[auto]                            Enables Auto plugin for inference
openvino[auto-batch]                      Enables Auto Batch plugin for inference, useful for throughput mode
openvino[cpu]                             Enables CPU plugin for inference
openvino[default-features]                Enables all default features
openvino[gpu]                             Enables GPU plugin for inference
openvino[hetero]                          Enables Hetero plugin for inference
openvino[ir]                              Enables IR frontend for reading models in OpenVINO IR format
openvino[onnx]                            Enables ONNX frontend for reading models in ONNX format
openvino[paddle]                          Enables PaddlePaddle frontend for reading models in PaddlePaddle format
openvino[pytorch]                         Enables PyTorch frontend to convert models in PyTorch format
openvino[tensorflow]                      Enables TensorFlow frontend for reading models in TensorFlow format
openvino[tensorflow-lite]                 Enables TensorFlow Lite frontend for reading models in TensorFlow Lite format
wasmedge[plugin-wasi-nn-backend-openvino] Build the OpenVINO backend plugin for the WasmEdge WASI-NN extension
The result may be outdated. Run `git pull` to get the latest results.
```

Current command output(after `git pull` to latest version):
```
PS C:\Users\Administrator> vcpkg search openvino
wasmedge[plugin-wasi-nn-backend-openvino] Build the OpenVINO backend plugin for the WasmEdge WASI-NN extension
The result may be outdated. Run `git pull` to get the latest results.
```

**Expected behavior**
The OpenVINO library should be listed as it previously was when running the `vcpkg search openvino` command.

**Failure logs**
-(No failure logs as this is an issue of missing library)

**Additional context**
Please help me understand why the OpenVINO library is no longer listed, and assist in resolving this issue. If the library has been intentionally removed, could you provide any documentation or discussion links explaining this decision?

**Comment by JonLiu1993** [comment]
@sdcb, Thanks for posting this issue, openvino is OpenVINO, and I didn't find OpenVINO in the vcpkg history record, if you use the command` ./vcpkg install OpenVINO`, it is equivalent to `./vcpkg install openvino`. Does the name OpenVINO have any special needs for you?

**Comment by Osyotr** [comment]
@JonLiu1993 non-lowercase port names are invalid!

**Comment by JonLiu1993** [comment]
> ./vcpkg install OpenVINO

Total install time: 14 s
PS F:\test\vcpkg> ./vcpkg install OpenVINO
warning: Starting with the September 2023 release, the default triplet for vcpkg libraries will change from x86-windows to the detected host triplet (x64-windows). To resolve this message, add --triplet x86-windows to keep the same behavior.
Computing installation plan...
The following packages will be built and installed:
  * ade:x86-windows -> 0.1.2
  * flatbuffers:x86-windows -> 23.5.26
  * hwloc:x86-windows -> 2.9.0
  * onnx:x86-windows -> 1.14.0
    openvino[auto,auto-batch,core,cpu,hetero,ir,onnx,paddle,pytorch,tensorflow,tensorflow-lite]:x86-windows -> 2023-06-11#6
  * protobuf:x86-windows -> 3.21.12
  * pugixml:x86-windows -> 1.13.0
  * snappy:x86-windows -> 1.1.10
  * tbb[core,hwloc]:x86-windows -> 2021.10.0#1

It will go to install lowercase `openvino`

**Comment by autoantwort** [comment]
>    Run vcpkg search openvino
    Observe that OpenVINO is no longer listed.

Hm I can not reproduce

**Comment by sdcb** [comment]
> > Run vcpkg search openvino
> > Observe that OpenVINO is no longer listed.
> 
> Hm I can not reproduce

Have you received most recent version before search openvino? I have 3 different machines all have this issue.

**Comment by sdcb** [comment]
@JonLiu1993 

> I didn't find OpenVINO in the vcpkg history record
Don't understand, this should be the openvino history right? https://github.com/microsoft/vcpkg/tree/master/ports/openvino

> OpenVINO vs openvino
Also seem unrelated to me, because I'm always using lowercase openvino that vcpkg supports.

anyway, openvino in vcpkg currently is not exists for reason unknown.

**Comment by Osyotr** [comment]
> anyway, openvino in vcpkg currently is not exists for reason unknown.

It does: https://github.com/microsoft/vcpkg/tree/master/ports/openvino
Maybe you have `VCPKG_ROOT` environment variable set somewhere that points to wrong vcpkg installation? What was the last revision of vcpkg you used that had openvino in it?

**Comment by sdcb** [comment]
Yes I never set `VCPKG_ROOT` before, but after I set it seems still the same:

```powershell
PS C:\Users\sdfly> $env:VCPKG_ROOT="C:\_\3rd\vcpkg"
PS C:\Users\sdfly> vcpkg search openvino
wasmedge[plugin-wasi-nn-backend-openvino] Build the OpenVINO backend plugin for the WasmEdge WASI-NN extension
The result may be outdated. Run `git pull` to get the latest results.
If your port is not listed, please open an issue at and/or consider making a pull request.    -  https://github.com/Microsoft/vcpkg/issues
PS C:\Users\sdfly> echo $env:VCPKG_ROOT
C:\_\3rd\vcpkg
```

**Comment by Osyotr** [comment]
Could you please upload `C:\_\3rd\vcpkg\vcpkg\versions\baseline.json`?

**Comment by sdcb** [comment]
[baseline.json.txt](https://github.com/microsoft/vcpkg/files/12449406/baseline.json.txt)

Noticed there is openvino in this json file:
![image](https://github.com/microsoft/vcpkg/assets/1317141/202933b9-3c70-4d40-af7d-ad67c256e0ae)


This is from: 
`C:\_\3rd\vcpkg\versions\baseline.json`
not from:
`C:\_\3rd\vcpkg\vcpkg\versions\baseline.json`

**Comment by Osyotr** [comment]
> vcpkg\vcpkg

Sorry, my mistake.

At this point I would build vcpkg-tool and debug this.
Just to clarify: does `vcpkg install openvino` works?

**Comment by sdcb** [comment]
it worked before, but not work now:

```powershell
C:\Users\ZhouJie>vcpkg install openvino
warning: Starting with the September 2023 release, the default triplet for vcpkg libraries will change from x86-windows to the detected host triplet (x64-windows). To resolve this message, add --triplet x86-windows to keep the same behavior.
Computing installation plan...
error: while looking for openvino:x86-windows:
error: while loading C:\_\3rd\vcpkg\ports\openvino\vcpkg.json:
$.dependencies[3].features[0]: mismatched type: expected an identifier
$.default-features[2]: mismatched type: expected an identifier
$.default-features[3]: mismatched type: expected an identifier

```

I just see some errors when parsing `openvino\vcpkg.json`, is that the issue?

**Comment by sdcb** [comment]
@Osyotr I think I just found the reason, my `vcpkg.exe` seems not up-to-date, if I using any version equals or lower than this release: https://github.com/microsoft/vcpkg-tool/releases/tag/2023-07-19

Then I cannot search `openvino`, will have this issue, if I upgrade to this version or latest, then problem will be disappeared:
```powershell
C:\Users\ZhouJie>vcpkg search openvino
wasmedge[plugin-wasi-nn-backend-openvino] Build the OpenVINO backend plugin for the WasmEdge WASI-NN extension
The result may be outdated. Run `git pull` to get the latest results.
If your port is not listed, please open an issue at and/or consider making a pull request.    -  https://github.com/Microsoft/vcpkg/issues

C:\Users\ZhouJie>bootstrap-vcpkg
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2023-08-09/vcpkg.exe -> C:\_\3rd\vcpkg\vcpkg.exe... done.
Validating signature... done.

vcpkg package management program version 2023-08-09-9990a4c9026811a312cb2af78bf77f3d9d288416

See LICENSE.txt for license information.
Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md

C:\Users\ZhouJie>vcpkg search openvino
openvino                 2023-06-11#6     Intel® Distribution of OpenVINO™ toolkit is an open-source toolkit for ...
openvino[auto]                            Enables Auto plugin for inference
openvino[auto-batch]                      Enables Auto Batch plugin for inference, useful for throughput mode
openvino[cpu]                             Enables CPU plugin for inference
openvino[gpu]                             Enables GPU plugin for inference
openvino[hetero]                          Enables Hetero plugin for inference
openvino[ir]                              Enables IR frontend for reading models in OpenVINO IR format
openvino[onnx]                            Enables ONNX frontend for reading models in ONNX format
openvino[paddle]                          Enables PaddlePaddle frontend for reading models in PaddlePaddle format
openvino[pytorch]                         Enables PyTorch frontend to convert models in PyTorch format
openvino[tensorflow]                      Enables TensorFlow frontend for reading models in TensorFlow format
openvino[tensorflow-lite]                 Enables TensorFlow Lite frontend for reading models in TensorFlow Lite format
wasmedge[plugin-wasi-nn-backend-openvino] Build the OpenVINO backend plugin for the WasmEdge WASI-NN extension
The result may be outdated. Run `git pull` to get the latest results.
If your port is not listed, please open an issue at and/or consider making a pull request.    -  https://github.com/Microsoft/vcpkg/issues

C:\Users\ZhouJie>
```

I think we should do better on `vcpkg.exe` toolset's backward compatibility.

**Comment by JonLiu1993** [comment]
@sdcb, This issue seems to be resolved now?

**Comment by Osyotr** [comment]
Yeah looks like it uses vcpkg-tool feature that has been added in August.
https://github.com/microsoft/vcpkg/blob/dd54d5e1d7a0d635afd4a0ef19326ffb3ea9c5c8/ports/openvino/vcpkg.json#L31C8-L31C8

**Comment by sdcb** [comment]
> @sdcb, This issue seems to be resolved now?

Yes, I don't have any further problem, thanks.
