### ISSUE TITLE
[New Port Request] nanobind

### ISSUE THREAD

**Issue by dantamont** [microsoft/vcpkg#33401]
### Library name

nanobind

### Library description

nanobind is a small binding library that exposes C++ types in Python and vice versa. It is reminiscent of Boost.Python and pybind11 and uses near-identical syntax. In contrast to these existing tools, nanobind is more efficient: bindings compile in a shorter amount of time, produce smaller binaries, and have better runtime performance.

### Source repository URL

https://github.com/wjakob/nanobind

**Comment by renefritze** [comment]
Not stale

**Comment by renefritze** [comment]
Still not stale

**Comment by renefritze** [comment]
There's an open PR for this now, right?
