### ISSUE TITLE
[fontconfig] Build error

### ISSUE THREAD

**Issue by Kiryuumaru** [microsoft/vcpkg#33408]
Using vcpkg.json with
```json
{
  "name": "appSample",
  "dependencies": [
    {
      "name": "opencv",
      "features": [
        "default-features",
        "ffmpeg"
      ]
    }
  ],
  "overrides": [
    {
      "name": "opencv",
      "version": "4.8.0"
    }
  ],
  "builtin-baseline": "9edb1b8e590cc086563301d735cae4b6e732d2d2"
}
```
It failed on the curl download part `fontconfig-2.14.2.tar.gz`: `curl: (22) The requested URL returned error: 504`

Building fontconfig:x64-linux...
-- Installing port from location: /home/vsts/work/1/s/vcpkg/buildtrees/versioning_/versions/fontconfig/26490bc4c9aa1377da98980ba6e1089525fdaa55
-- Downloading https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/2.14.2/fontconfig-2.14.2.tar.gz -> fontconfig-fontconfig-2.14.2.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from /home/vsts/work/1/s/vcpkg/vcpkg-bundle.json
[DEBUG] Failed to open: /home/vsts/work/1/s/vcpkg/vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
[DEBUG] Detected CI environment: Azure_Pipelines
[DEBUG] 1000: popen( curl --fail -L https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/2.14.2/fontconfig-2.14.2.tar.gz --create-dirs --output /home/vsts/work/1/s/vcpkg/downloads/fontconfig-fontconfig-2.14.2.tar.gz.59089.part 2>&1)
[DEBUG] 1000: cmd_execute_and_stream_data() returned 22 after 90933933 us
error: Failed to download from mirror set
error: https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/2.14.2/fontconfig-2.14.2.tar.gz: curl failed to download with exit code 22
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

curl: (22) The requested URL returned error: 504 

[DEBUG] /mnt/vss/_work/1/s/src/vcpkg/base/downloads.cpp(1053): 
[DEBUG] Time in subprocesses: 90933933us
[DEBUG] Time in parsing JSON: 4us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 312us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 1.5 min (90934503us)

**Comment by Osyotr** [comment]
https://gitlab.freedesktop.org is down, you have to wait or find a mirror and put it into downloads dir.

**Comment by Kiryuumaru** [comment]
https://gitlab.freedesktop.org/ is still currently inaccessible. Despite downgrading to opencv4.7.0, my azure pipeline remains unable to complete the build process. Do we have any workaround on this?

**Comment by xiaozhuai** [comment]
[fontconfig-fontconfig-2.14.2.tar.gz](https://github.com/microsoft/vcpkg/files/12454188/fontconfig-fontconfig-2.14.2.tar.gz)

I had the same issue today and luckily this file is cached on my CI.

You can download file above and place it into `/path/to/vcpkg/downloads`

**Comment by Kiryuumaru** [comment]
I appreciate your help with the fontconfig issue. However, I've encountered another problem with freedesktop packages, this time its the https://gitlab.freedesktop.org/pixman/pixman/-/archive/37216a32839f59e8dcaa4c3951b3fcfc3f07852c/pixman-37216a32839f59e8dcaa4c3951b3fcfc3f07852c.tar.gz package
Perhaps it would be advisable for me to hold off on further steps until freedesktop's maintenance has been fully concluded.

**Comment by christianparpart** [comment]
While gitlab.freedesktop.org seems to be up and online, I still cannot download either. What do you do if Github CI fails and I have no cached version of it apparently? Is there a way for vcpkg.json to specify an alternate download link?

**Comment by jimwang118** [comment]
> While gitlab.freedesktop.org seems to be up and online, I still cannot download either. What do you do if Github CI fails and I have no cached version of it apparently? Is there a way for vcpkg.json to specify an alternate download link?

Now `fontconfig` can be downloaded and you can try it locally.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
