### ISSUE TITLE
libuv:x64-osx failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by abirbasak** [Microsoft/vcpkg#3341]
Build failed on OSX for 
 Package: libuv:x64-osx
 Vcpkg version: 0.0.110-unknownhash
Command : `./vcpkg install libuv`
/opt/vcpkg/buildtrees/libuv/src/libuv-1.20.0/src/win/winapi.h:25:10: fatal error: 'windows.h' file not found
#include <windows.h>
         ^~~~~~~~~~~

**Comment by edmBernard** [comment]
related: https://github.com/Microsoft/vcpkg/issues/3396
I got the same error on linux.
in custom, CMakeList.txt there is an explicite use of windows source: https://github.com/Microsoft/vcpkg/issues/3396

**Comment by edmBernard** [comment]
I add a pull request for linux and darwin https://github.com/Microsoft/vcpkg/pull/3437
But I was not able test it on osx, if you have time to check it works for you you're welcome.

**Comment by NancyLi1013** [comment]
@abirbasak ，Could you please help have a test on osx?
The PR had been merged. And now I can install it on linux successfully.
If this issue has been solved, please close it. Thanks!

**Comment by abirbasak** [comment]
@NancyLi1013 This builds on mac without any problem. Thanks!
