### ISSUE TITLE
[sqlite3] link failure for android `arm64` and `x86`

### ISSUE THREAD

**Issue by nathan-stouffer-onx** [microsoft/vcpkg#33428]
### Operating system

Windows and Linux

### Compiler

clang (from the android ndk)

### Steps to reproduce the behavior

```Shell
`./vcpkg install sqlite3 --triplet=arm64-android`
link into a downstream application
```

### Failure logs

We utilize `vcpkg` to compile `sqlite3` as a static lib for our `x86-android` and `arm64-android` builds. Prior to commit 5787cfa699a75805ef41938ec66bc7492714d290, we compile `sqlite3` and successfully link the static lib into our application. Starting at 5787cfa699a75805ef41938ec66bc7492714d290, we still successfully compile `sqlite3` but our application can no longer link the static library.

We do get a message about how the existing lib is incompatible

`C:/dev/core/TestApps/Map3DAndroid/app/src/main/cpp/../../../../../..//deps/vcpkg_installed/arm64-android/lib/libsqlite3.a: error adding symbols: File in wrong format`

If I re-add the following to `scripts/toolchain/android.cmake` on line 12 (it was removed in 5787cfa699a75805ef41938ec66bc7492714d290), then we can successfully link `sqlite3`

```cmake
if (VCPKG_TARGET_TRIPLET MATCHES "arm64-android")
    set(ANDROID_ABI arm64-v8a CACHE STRING "")
elseif(VCPKG_TARGET_TRIPLET MATCHES "armv6-android")
    set(ANDROID_ABI armeabi CACHE STRING "")
    set(ANDROID_ARM_MODE arm CACHE STRING "")
elseif(VCPKG_TARGET_TRIPLET MATCHES "arm-neon-android")
    set(ANDROID_ABI armeabi-v7a CACHE STRING "")
    set(ANDROID_ARM_NEON ON CACHE BOOL "")
elseif(VCPKG_TARGET_TRIPLET MATCHES "arm-android")
    set(ANDROID_ABI armeabi-v7a CACHE STRING "")
    set(ANDROID_ARM_NEON OFF CACHE BOOL "")
elseif(VCPKG_TARGET_TRIPLET MATCHES "x64-android")
    set(ANDROID_ABI x86_64 CACHE STRING "")
elseif(VCPKG_TARGET_TRIPLET MATCHES "x86-android")
    set(ANDROID_ABI x86 CACHE STRING "")
else()
    message(FATAL_ERROR "Unknown ABI for target triplet ${VCPKG_TARGET_TRIPLET}")
endif()
```

Based on 5787cfa699a75805ef41938ec66bc7492714d290's diff, it looks like the above section was replaced by flags getting set in the individual port files for each android architecture. But (at least for us), those flags don't seem to have the same effect that the above block had.

As a test, I made a custom portfile for `x86-android`. Unfortunately, that didn't fix our linking problems.

```cmake
set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Android)
set(VCPKG_MAKE_BUILD_TRIPLET "--host=i686-linux-android")
set(VCPKG_CMAKE_CONFIGURE_OPTIONS -DANDROID_ABI=x86)
set(ANDROID_ABI x86 CACHE STRING "")
```

### Additional context

I have created a [discussion](https://github.com/microsoft/vcpkg/discussions/33361) as well, but the failure to link seems worthy of issue (sorry for the duplicate).

I would happily create a PR to re-add this to `android.cmake` if that is amenable. Though, given the fact that it looks like there as an attempt to replace it, is there another path I should take?

```cmake
if (VCPKG_TARGET_TRIPLET MATCHES "arm64-android")
    set(ANDROID_ABI arm64-v8a CACHE STRING "")
elseif(VCPKG_TARGET_TRIPLET MATCHES "armv6-android")
    set(ANDROID_ABI armeabi CACHE STRING "")
    set(ANDROID_ARM_MODE arm CACHE STRING "")
elseif(VCPKG_TARGET_TRIPLET MATCHES "arm-neon-android")
    set(ANDROID_ABI armeabi-v7a CACHE STRING "")
    set(ANDROID_ARM_NEON ON CACHE BOOL "")
elseif(VCPKG_TARGET_TRIPLET MATCHES "arm-android")
    set(ANDROID_ABI armeabi-v7a CACHE STRING "")
    set(ANDROID_ARM_NEON OFF CACHE BOOL "")
elseif(VCPKG_TARGET_TRIPLET MATCHES "x64-android")
    set(ANDROID_ABI x86_64 CACHE STRING "")
elseif(VCPKG_TARGET_TRIPLET MATCHES "x86-android")
    set(ANDROID_ABI x86 CACHE STRING "")
else()
    message(FATAL_ERROR "Unknown ABI for target triplet ${VCPKG_TARGET_TRIPLET}")
endif()
```

**Comment by nathan-stouffer-onx** [comment]
I see this has been assigned to @LilyWangLL. Is there anything I can do to help? I would really like to get this fixed because installing libraries with `vcpkg` prior to commit 5787cfa699a75805ef41938ec66bc7492714d290 results in 404s when downloading some tools (eg grep) on windows. So I currently have no way to build android from a windows machine

**Comment by dg0yt** [comment]
Did you verify that https://github.com/microsoft/vcpkg/commit/5787cfa699a75805ef41938ec66bc7492714d290 is the offending commit? There is no obvious error in that change.

vcpkg CI successfully builds packages which link to the android sqlite3 libs (proj, gdal). Locally I can easily build proj[core,tool]:arm64-android (with NDK r23c). And even sqlite3[tool] should given an indication:
~~~
$ file packages/sqlite3_arm64-android/tools/sqlite3 
packages/sqlite3_arm64-android/tools/sqlite3: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, BuildID[sha1]=8671fe8c66a202b493b5b585a0b5fbf00c9f942b, with debug_info, not stripped
~~~

So I cannot reproduce the issue.

**Comment by nathan-stouffer-onx** [comment]
Oh interesting, I didn't realize `vcpkg'`s CI built some packages that link in `sqlite3`.

> Did you verify that https://github.com/microsoft/vcpkg/commit/5787cfa699a75805ef41938ec66bc7492714d290 is the offending commit? There is no obvious error in that change.

I have CI runs (on linux) where I locked `vcpkg` to 5787cfa699a75805ef41938ec66bc7492714d290 and the its parent 80d08d2900147c864c17e4bdfc928699cb84b3f2. Our build failed to link on 5787cfa699a75805ef41938ec66bc7492714d290  and succeeded on 80d08d2900147c864c17e4bdfc928699cb84b3f2. Unfortunately, the CI builds are private so I can't send them your way.

We are on an older version of the android NDK (r21d). I hadn't thought to update that. I will kick off a build and give an update when it is done.

**Comment by dg0yt** [comment]
Locally there are also no problems with sqlite3 and proj with NDK r15c...
While vcpkg CI skip most packages' internal tests, it is strict about testing reverse dependencies - and sqlite3 is quite popular.

Does your project use the `scripts/buildsystems/vcpkg.cmake` toolchain and also use the default chainloaded toolchain file for android (`scripts/toolchains/android.cmake`)?

You can try to create a minimal reproducible example. Sometimes this is enough to spot the error ;-)
In any case, the steps to reproduce the problem probably aren't enough.

**Comment by dg0yt** [comment]
Note that if you use a custom triplet file, you must modify it in a similar way as the vcpkg android triplet files were modified in https://github.com/microsoft/vcpkg/commit/5787cfa699a75805ef41938ec66bc7492714d290. This is the difference made by this commit.

**Comment by nathan-stouffer-onx** [comment]
Update: I am hitting some build errors with our main project when upgrading to NDK r23c. I suspect they are unrelated to this and am working through them.

> Does your project use the `scripts/buildsystems/vcpkg.cmake` toolchain and also use the default chainloaded toolchain file for android (`scripts/toolchains/android.cmake`)?

We are definitely using `scripts/toolchains/android.cmake` because manual changes to it affect our ability to link `sqlite3`. I haven't tested whether we are using `scripts/buildsystems/vcpkg.cmake`. But if it is the default, I would expect that we are. We aren't providing any custom cmake files. We are just building the libraries in manifest mode with a `vcpkg.json` file.

> Note that if you use a custom triplet file, you must modify it in a similar way as the vcpkg android triplet files were modified in 5787cfa699a75805ef41938ec66bc7492714d290. This is the difference made by this commit.

We are not using any custom triplet files.

It seems like `set(ANDROID_ABI x86 CACHE STRING "")` and `set(VCPKG_CMAKE_CONFIGURE_OPTIONS -DANDROID_ABI=x86)` should have the same effect. Maybe this is an issue of when those values get set? Maybe in 80d08d2900147c864c17e4bdfc928699cb84b3f2, they were set earlier than 5787cfa699a75805ef41938ec66bc7492714d290?

**Comment by nathan-stouffer-onx** [comment]
I did some inspecting of the `.a` files that are produces. I used `readelf -h <arch>-android/lib/libsqlite3.a`

## arm

```
File: arm-android/lib/libsqlite3.a(sqlite3.c.o)
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              REL (Relocatable file)
  Machine:                           ARM
  Version:                           0x1
  Entry point address:               0x0
  Start of program headers:          0 (bytes into file)
  Start of section headers:          3835884 (bytes into file)
  Flags:                             0x5000000, Version5 EABI
  Size of this header:               52 (bytes)
  Size of program headers:           0 (bytes)
  Number of program headers:         0
  Size of section headers:           40 (bytes)
  Number of section headers:         8444
  Section header string table index: 1
```

## arm64

```
File: arm64-android/lib/libsqlite3.a(sqlite3.c.o)
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              REL (Relocatable file)
  Machine:                           ARM
  Version:                           0x1
  Entry point address:               0x0
  Start of program headers:          0 (bytes into file)
  Start of section headers:          3835884 (bytes into file)
  Flags:                             0x5000000, Version5 EABI
  Size of this header:               52 (bytes)
  Size of program headers:           0 (bytes)
  Number of program headers:         0
  Size of section headers:           40 (bytes)
  Number of section headers:         8444
  Section header string table index: 1
```

## x86

```
File: x86-android/lib/libsqlite3.a(sqlite3.c.o)
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              REL (Relocatable file)
  Machine:                           ARM
  Version:                           0x1
  Entry point address:               0x0
  Start of program headers:          0 (bytes into file)
  Start of section headers:          3835884 (bytes into file)
  Flags:                             0x5000000, Version5 EABI
  Size of this header:               52 (bytes)
  Size of program headers:           0 (bytes)
  Number of program headers:         0
  Size of section headers:           40 (bytes)
  Number of section headers:         8444
  Section header string table index: 1
```

I also tested this for other libs installed by vcpkg (eg `protobuf`) and the behavior was the same: the architecture is always set to `arm`, regardless of the intended architecture. So it seems that the link just stops when it encounters the first architecture issue on `sqlite3`.

**Comment by dg0yt** [comment]
I still think you should create a minimal reproducible example.

**Comment by nathan-stouffer-onx** [comment]
Will this work? 

1. create a new directory
2. use the below `vcpkg.json` (we will be using `vcpkg` in manifest mode)
3. run `vcpkg install --triplet=arm64-android`
4. run `readelf -h vcpkg_installed/arm64-android/lib/libsqlite3.a` and inspect output

```json
{
    "name": "broken-minimal-example",
    "version": "0.0.0",
    "builtin-baseline": "aefc4b01a49ea6f06aaece59245c5a19cd1e9af5",
    "dependencies": [
        "sqlite3"
    ],
    "overrides": [
        {
            "name": "sqlite3",
            "version": "3.39.2"
        }
    ]
}
```

When I do that, I get ARM architecture for the library.

```
File: vcpkg_installed/arm64-android/lib/libsqlite3.a(sqlite3.c.o)
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              REL (Relocatable file)
  Machine:                           ARM
  Version:                           0x1
  Entry point address:               0x0
  Start of program headers:          0 (bytes into file)
  Start of section headers:          3834152 (bytes into file)
  Flags:                             0x5000000, Version5 EABI
  Size of this header:               52 (bytes)
  Size of program headers:           0 (bytes)
  Number of program headers:         0
  Size of section headers:           40 (bytes)
  Number of section headers:         8444
  Section header string table index: 1
```

If I remove the version override, I revert back to a 64-bit build. The `vcpkg.json` and `readelf` output are below.

```json
{
    "name": "minimal-example",
    "version": "0.0.0",
    "builtin-baseline": "aefc4b01a49ea6f06aaece59245c5a19cd1e9af5",
    "dependencies": [
        "sqlite3"
    ]
}
```

```
File: vcpkg_installed/arm64-android/lib/libsqlite3.a(sqlite3.c.o)
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              REL (Relocatable file)
  Machine:                           AArch64
  Version:                           0x1
  Entry point address:               0x0
  Start of program headers:          0 (bytes into file)
  Start of section headers:          15289888 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           0 (bytes)
  Number of program headers:         0
  Size of section headers:           64 (bytes)
  Number of section headers:         2354
  Section header string table index: 1
```

**Comment by nathan-stouffer-onx** [comment]
@dg0yt Are you able to replicate that minimal example?

**Comment by dg0yt** [comment]
~~~
The following packages will be built and installed:
    sqlite3:arm64-android -> 3.39.2 -- (...)/sqlite3/b673cfda60055677c42fe66cdd0655ad4a1110dd
  * vcpkg-cmake:x64-linux -> 2021-02-28#1 -- (...)/vcpkg-cmake/4abdcc88bd5ec2c76e320eb2ff4db665ee9913ac
  * vcpkg-cmake-config:x64-linux -> 2021-02-26#1 -- (...)/vcpkg-cmake-config/46d60d4dd4297bedecdcd308167ad2492b269183
~~~~

2021-02-28's `vcpkg-cmake`? You must update your baseline...

**Comment by nathan-stouffer-onx** [comment]
Updating our baseline fixed it, thanks!
