### ISSUE TITLE
--x-json has non-json messages in stdout

### ISSUE THREAD

**Issue by petersteneteg** [microsoft/vcpkg#33444]
When embedding the vcpkg-configuration into a manifest the following warning is printed, to stdout not stderr
> warning: Embedding `vcpkg-configuration` in a manifest file is an EXPERIMENTAL feature.

Even if --x-json is given. With --x-json I expect the stdout output to be valid json

example:
vcpkg x-package-info --x-json --x-installed  --x-install-root=<installdir> zlib:arm64-osx-dynamic
with a manifest that uses zlib, and an embedded vcpkg-configuration

**Comment by JonLiu1993** [comment]
I reproduced it locally
vcpkg.json:
````
{
  "name": "test",
  "dependencies": [
    "zlib"
  ],
"vcpkg-configuration": {
    "overlay-ports": ["--x-json"]
  }
}

````
Output:
````
PS F:\test\vcpkg> ./vcpkg install
warning: Embedding `vcpkg-configuration` in a manifest file is an EXPERIMENTAL feature.
error: Ambiguous vcpkg configuration provided by both manifest and configuration file.
-- Delete configuration file F:\test\vcpkg\vcpkg-configuration.json
-- Or remove "vcpkg-configuration" from the manifest file F:\test\vcpkg\vcpkg.json.
````
