### ISSUE TITLE
[lz4] Build error

### ISSUE THREAD

**Issue by EvainGGbond** [microsoft/vcpkg#33441]
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[openssl]+Build+error&body=Copy+issue+body+from+D%3A%2Fvcpkg%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.mdpkg/installed/vcpkg/issue_body.md

**Comment by Cheney-W** [comment]
Please report your issue according to the steps here: https://github.com/microsoft/vcpkg/issues/30604.

**Comment by Cheney-W** [comment]
We don't have enough information to solve this issue, if you have any more information to help us solve this, please contact us again.
