### ISSUE TITLE
Add omniORB to the packages

### ISSUE THREAD

**Issue by ray42** [microsoft/vcpkg#3346]
Hi, can we add http://omniorb.sourceforge.net/ to the packages? I currently use omniORB-4.2.0-win32-vs10-py27.zip from https://sourceforge.net/projects/omniorb/files/omniORB/omniORB-4.2.0

Thanks

**Comment by NancyLi1013** [comment]
Related PR #8609.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue and continue related PR, but we're closing it for now.
