### ISSUE TITLE
[boost-system:x86] build failure on x64 machine

### ISSUE THREAD

**Issue by Zhukovdpua** [microsoft/vcpkg#33483]
### Operating system

x64-Linux, Ubuntu 20

### Compiler

gcc

### Steps to reproduce the behavior

```Shell
mkdir /tmp/manifest/
cat > /tmp/manifest/vcpkg.json << EOF
{
  "version": "7.5.0",
  "dependencies": [
    {
      "name": "boost-system",
      "version>=": "1.71.0"
    }
  ],
  "builtin-baseline": "2f6176ce98fee807a207dc9e8fec213f111c291b",
  "overrides": [
    {
      "name": "boost-system",
      "version": "1.71.0"
    }
  ]
}
EOF

vcpkg install --triplet x86-linux --x-manifest-root=/tmp/manifest
```

### Failure logs

CMake Warning at scripts/cmake/vcpkg_common_functions.cmake:3 (message):
  vcpkg_common_functions has been removed and all values are automatically
  provided in all portfile.cmake invocations.  Please remove
  `include(vcpkg_common_functions)`.
Call Stack (most recent call first):
  buildtrees/versioning_/versions/boost-system/4250413c5ce279a13b4c21ff6244a21fc8f13a50/portfile.cmake:3 (include)
  scripts/ports.cmake:147 (include)

-- Downloading https://github.com/boostorg/system/archive/boost-1.71.0.tar.gz -> boostorg-system-boost-1.71.0.tar.gz...
-- Extracting source /home/ibse/Projects/vcpkg/downloads/boostorg-system-boost-1.71.0.tar.gz
-- Using source at /home/ibse/Projects/vcpkg/buildtrees/boost-system/src/ost-1.71.0-c6a1ad9630.clean
CMake Error at /tmp/manifest/vcpkg_installed/x86-linux/share/boost-build/boost-modular-build.cmake:2 (include):
  include could not find requested file:

    /tmp/manifest/vcpkg_installed/x86-linux/share/boost-build/../vcpkg-cmake/vcpkg-port-config.cmake
Call Stack (most recent call first):
  buildtrees/versioning_/versions/boost-system/4250413c5ce279a13b4c21ff6244a21fc8f13a50/portfile.cmake:15 (include)
  scripts/ports.cmake:147 (include)

### Additional context

<details><summary>vcpkg.json</summary>

```
{
  "version": "7.5.0",
  "dependencies": [
    {
      "name": "boost-system",
      "version>=": "1.71.0"
    }
  ],
  "builtin-baseline": "2f6176ce98fee807a207dc9e8fec213f111c291b",
  "overrides": [
    {
      "name": "boost-system",
      "version": "1.71.0"
    }
  ]
}

```
</details>

**Comment by Osyotr** [comment]
For boost < 1.80 you must explicitly add overrides for each boost port.
