### ISSUE TITLE
error: building abseil:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by fonsekaa** [microsoft/vcpkg#33488]
I am having this error when trying to use this command:

.\vcpkg install --triplet x64-windows asio pugixml spdlog curl jsoncpp protobuf parallel-hashmap magic-enum mio luajit libmariadb mpir abseil argon2 eventpp bext-di

![image](https://github.com/microsoft/vcpkg/assets/99992237/75fd483f-5b16-44e5-b759-69f9321eedb8)

**Comment by jimwang118** [comment]
I could install this port successfully with the latest vcpkg 2023-08-09-9990a4c9026811a312cb2af78bf77f3d9d288416, could you please run following commands in your vcpkg folder:

```
1. git pull
2. .\bootstrap-vcpkg.bat
3. .\vcpkg install --triplet x64-windows asio pugixml spdlog curl jsoncpp protobuf parallel-hashmap magic-enum mio luajit libmariadb mpir abseil argon2 eventpp bext-di --binarysource=clear
```
![image](https://github.com/microsoft/vcpkg/assets/122244446/f4acfe9d-9ff6-41ec-9c66-3c0e57f6ece2)

**Comment by jimwang118** [comment]
> I had a similar error with `.\vcpkg install grpc`. Looking at the log file suggests the problem is due to my Visual Studio Version (2017):
> 
> ```
> C:\dev\vcpkg\buildtrees\abseil\src\20230802.0-d88f1acef0.clean\absl/base/policy_checks.h(50): fatal error C1189: #error:  "This package requires Visual Studio 2019 (MSVC++ 16.0) or higher."
> ninja: build stopped: subcommand failed.
> ```

The error message requires vs2019 or above, so versions below 2019 will cause compilation errors.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.

**Comment by dapeng17951** [comment]
> I am having this error when trying to use this command:
> 
> .\vcpkg install --triplet x64-windows asio pugixml spdlog curl jsoncpp protobuf parallel-hashmap magic-enum mio luajit libmariadb mpir abseil argon2 eventpp bext-di
> 
> ![image](https://github.com/microsoft/vcpkg/assets/99992237/75fd483f-5b16-44e5-b759-69f9321eedb8)

在 VS2022 开发人员命令提示符 中运行（最可靠）
