### ISSUE TITLE
[OpenVINO] Missing PDB Files in openvino After Compilation in vcpkg

### ISSUE THREAD

**Issue by sdcb** [microsoft/vcpkg#33492]
### Is your feature request related to a problem? Please describe.

After compiling the openvino package with vcpkg, I noticed that the PDB files are not being copied to the bin directory. This problem can be frustrating when debugging software.
![image](https://github.com/microsoft/vcpkg/assets/1317141/aa69c343-cf99-4516-bfc5-adf87e965e08)

### Proposed solution

I propose that the PDB files should be properly copied to the bin directory after the package's compilation, similar to how it works with opencv4.

### Describe alternatives you've considered

No alternatives have been considered as this seems to be an issue in the packaging process of openvino.

### Additional context

For context, here is my directory of the compiled `openvino` package:

```
C:\_\3rd\vcpkg\packages\openvino_x64-windows\debug\bin>tree /f
Volume in drive C: is Windows-SSD
Volume Serial Number is EEA2-D7AA

C:.
    cache.json
    openvinod.dll
    openvino_auto_batch_plugind.dll
    openvino_auto_plugind.dll
    openvino_cd.dll
    openvino_hetero_plugind.dll
    openvino_intel_cpu_plugind.dll
    openvino_intel_gpu_plugind.dll
    openvino_ir_frontendd.dll
    openvino_onnx_frontendd.dll
    openvino_paddle_frontendd.dll
    openvino_pytorch_frontendd.dll
    openvino_tensorflow_frontendd.dll
    openvino_tensorflow_lite_frontendd.dll
```
(Note the absence of any PDB files)

For comparison, here is the directory of the compiled `opencv4` package, which correctly includes PDB files:

```
C:\_\3rd\vcpkg\packages\opencv4_x64-windows\bin>tree /f
Volume in drive C: is Windows-SSD
Volume Serial Number is EEA2-D7AA

C:.
    opencv_calib3d4.dll
    opencv_calib3d4.pdb
    ...
```
(Note the presence of PDB files)

Finally, it's worth mentioning that the PDB files are actually generated in the `buildtrees\openvino` directory, but are not being copied to the `packages` directory. The issue appears to be related to packaging or a post-build process.

I have the English language pack for Visual Studio 2022 installed.

**Comment by JonLiu1993** [comment]
Fixing by PR https://github.com/microsoft/vcpkg/pull/33495
