### ISSUE TITLE
libmodplug:x64-linux fails to build

### ISSUE THREAD

**Issue by joonatoona** [Microsoft/vcpkg#3349]
```
  Package: libmodplug:x64-linux
  Vcpkg version: 0.0.110-unknownhash
```

[install-x64-linux-dbg-out.log](https://github.com/Microsoft/vcpkg/files/1953497/install-x64-linux-dbg-out.log)

**Comment by NancyLi1013** [comment]
@joonatoona , thank you for posting this issue.
The PR has been merged on the master. So this issue should be fixed now.
