### ISSUE TITLE
Add KDE Frameworks 5

### ISSUE THREAD

**Issue by barcharcraz** [Microsoft/vcpkg#335]
I came in my travels to want some Qt Widgets and models for networked resources (like WebDAV servers). KIO seems quite good at this, but it's super hard to build on windows, simply because it has a ton of dependencies. The actual build process is with cmake, and it's quite well laid out.

I'm working on this now, with the goal of getting kio and it's dependencies working.

**Comment by mattiascibien** [comment]
https://github.com/Microsoft/vcpkg/pull/4302 I am starting to add KDE Framework 5 starting from the KArchive library.

**Comment by NancyLi1013** [comment]
The kf5archive, kf5holidays,kf5plotting have been added to the master. @barcharcraz , please close this issue if they have met your demand.
Thanks.

**Comment by NancyLi1013** [comment]
Please open a new issue if you have new requests about this.
