### ISSUE TITLE
[vcpkg-cmake-get-vars] Build error

### ISSUE THREAD

**Issue by abdmo97** [microsoft/vcpkg#33511]
Copy issue body from C:/src/vcpkg/installed/vcpkg/issue_body.md

error: building vcpkg-cmake-get-vars:x64-windows failed with: BUILD_FAILED
Elapsed time to handle vcpkg-cmake-get-vars:x64-windows: 42.1 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+vcpkg-cmake-get-vars
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[vcpkg-cmake-get-vars]+Build+error&body=Copy+issue+body+from+C%3A%2Fsrc%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by dg0yt** [comment]
[How to report a package build failure [explanation video]](https://github.com/microsoft/vcpkg/issues/30604)

**Comment by Adela0814** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
