### ISSUE TITLE
[libpq] Build error

### ISSUE THREAD

**Issue by janhenke** [microsoft/vcpkg#33519]
Package: libpq[core,lz4,openssl,zlib]:x64-linux -> 15.3#1

**Host Environment**

- Host: x64-linux
- Compiler: GNU 12.3.1
-    vcpkg-tool version: 2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454
    vcpkg-scripts version: gpg: Signature made Sat Sep  2 00:34:33 2023 CEST
gpg:                using RSA key 4AEE18F83AFDEB23
gpg: Can't check signature: No public key
4a600e9fe 2023-09-01 (2 days ago)

**To Reproduce**

`vcpkg install `

**Failure logs**

```
-- Using cached postgresql-15.3.tar.bz2.
-- Cleaning sources at /home/jan/.clion-vcpkg/vcpkg/buildtrees/libpq/src/tgresql-15-fbbadfb3b2.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/jan/.clion-vcpkg/vcpkg/downloads/postgresql-15.3.tar.bz2
-- Applying patch unix/fix-configure.patch
-- Applying patch unix/single-linkage.patch
-- Applying patch unix/no-server-tools.patch
-- Applying patch unix/mingw-install.patch
-- Applying patch unix/python.patch
-- Applying patch windows/macro-def.patch
-- Applying patch windows/python_lib.patch
-- Applying patch windows/win_bison_flex.patch
-- Applying patch windows/msbuild.patch
-- Applying patch windows/spin_delay.patch
-- Using source at /home/jan/.clion-vcpkg/vcpkg/buildtrees/libpq/src/tgresql-15-fbbadfb3b2.clean
-- Found external ninja('1.11.1').
-- Getting CMake variables for x64-linux
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Generating configure for x64-linux
-- Finished generating configure for x64-linux
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Installing x64-linux-dbg
-- Building x64-linux-rel
-- Installing x64-linux-rel
CMake Error at scripts/cmake/vcpkg_replace_string.cmake:2 (file):
  file failed to open for reading (No such file or directory):

    /home/jan/.clion-vcpkg/vcpkg/packages/libpq_x64-linux/include/postgresql/server/pg_config.h
Call Stack (most recent call first):
  buildtrees/versioning_/versions/libpq/a62f65ad38aa981b6ff7474e16f739a3ffbc622b/portfile.cmake:141 (vcpkg_replace_string)
  scripts/ports.cmake:147 (include)



```

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "name": "postgresql-client",
  "version-string": "1.0.0",
  "builtin-baseline": "c95000e1b5bb62884de08d5e952993c8bced9db6",
  "dependencies": [
    {
      "name": "libpqxx",
      "version>=": "7.7.4"
    }
  ]
}

```
</details>

I have seen #33211 as well, but I am using another triplet (x64-linux). I have also seen the discussion happening in that bug report, but for me it boils down to: What can be done for this to work again? This is a hard blocker here.

**Comment by dg0yt** [comment]
Share you x64-linux config logs from `buildtrees/libpq`. I can't reproduce the issue, but maybe some system package (presence) makes a difference.

**Comment by LilyWangLL** [comment]
I can't reproduce this issue locally.
```
user@user002:~/lily/test/vcpkg$ ./vcpkg install --triplet=x64-linux --binarysource=clear
Detecting compiler hash for triplet x64-linux...
The following packages will be built and installed:
  * libpq[core,lz4,openssl,zlib]:x64-linux -> 15.3#1 -- /home/user/lily/test/vcpkg/buildtrees/versioning_/versions/libpq/a62f65ad38aa981b6ff7474e16f739a3ffbc622b
    libpqxx:x64-linux -> 7.7.4 -- /home/user/lily/test/vcpkg/buildtrees/versioning_/versions/libpqxx/7ddefb009a457fb899a8661e46ba79544da6b2df
  * lz4:x64-linux -> 1.9.4#1 -- /home/user/lily/test/vcpkg/buildtrees/versioning_/versions/lz4/d7704e3869f579ffdf927b5419579473e9d702d4
  * openssl:x64-linux -> 3.1.2#1 -- /home/user/lily/test/vcpkg/buildtrees/versioning_/versions/openssl/5a99562f8ac47a68a58efba5f0d40259fedeecc5
  * vcpkg-cmake:x64-linux -> 2023-05-04 -- /home/user/lily/test/vcpkg/buildtrees/versioning_/versions/vcpkg-cmake/88a7058fc7fa73a9c4c99cfcae9d79e2abf87a5a
  * vcpkg-cmake-config:x64-linux -> 2022-02-06#1 -- /home/user/lily/test/vcpkg/buildtrees/versioning_/versions/vcpkg-cmake-config/8d54cc4f487d51b655abec5f9c9c3f86ca83311f
  * vcpkg-cmake-get-vars:x64-linux -> 2023-03-02 -- /home/user/lily/test/vcpkg/buildtrees/versioning_/versions/vcpkg-cmake-get-vars/2e624c2cf12a97a7a802e31ff1d28b9fa6ba9bde
  * zlib:x64-linux -> 1.2.13 -- /home/user/lily/test/vcpkg/buildtrees/versioning_/versions/zlib/ad5a49006f73b45b715299515f31164131b51982
Additional packages (*) will be modified to complete this operation.
......
-- Fixing pkgconfig file: /home/user/lily/test/vcpkg/packages/libpqxx_x64-linux/lib/pkgconfig/libpqxx.pc
-- Fixing pkgconfig file: /home/user/lily/test/vcpkg/packages/libpqxx_x64-linux/debug/lib/pkgconfig/libpqxx.pc
-- Performing post-build validation
Elapsed time to handle libpqxx:x64-linux: 11 s
Total install time: 2.3 min
libpqxx provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(libpqxx CONFIG REQUIRED)
    target_link_libraries(main PRIVATE libpqxx::pqxx)
```

**Comment by janhenke** [comment]
Attached are all *.log files from the buildtree. I double checked the path throwing an error on install and it seems, the package directory does not contain any include/postgresql/ directory. But indeed I have a system installation (via the package manager) of postgresql, which includes the directory and file in question. So I would concur, that the issue is the configure script mixing the vcpkg version with the system wide version.

[libpq-logs.zip](https://github.com/microsoft/vcpkg/files/12509940/libpq-logs.zip)

**Comment by janhenke** [comment]
Unfortunately, removing the system installation of PostgreSQL does not fix the issue.

**Comment by janhenke** [comment]
I have rerun the bootstrap, no change.
I did find the file, but under a different path. The install script expects the file under `include/postgresql/server/pg_config.h`, but a file exists under `include/server/pg_config.h`. Somehow the `/postgresql/` in the path is lost somehwere.

**Comment by dg0yt** [comment]
> I did find the file, but under a different path. The install script expects the file under `include/postgresql/server/pg_config.h`, but a file exists under `include/server/pg_config.h`. Somehow the `/postgresql/` in the path is lost somehwere.

Hm, I see. This *is* different in my install log - I do have `/postgresql/` in the destination:
~~~
/usr/bin/install -c -m 644 pg_config.h     '/home/dg0yt/Projekte/vcpkg/vcpkg/packages/libpq_x64-linux/tmp/test/c++/vcpkg_installed/x64-linux/debug/../include/postgresql/server'
~~~

**Comment by dg0yt** [comment]
What I wrote:

> I do have `/postgresql/` in the destination

What I was thinking: "I do have *one* `/postgresql` in the destination"... 
if I build in `/tmp/Experimente/c++/postgresql-client/cmake-build-debug`, I can reproduce the problem. That is still just one `/postgresql`. A guess there is a bad pattern match somewhere.

Try choosing a working dir without `postgresql` as workaround. (But leave this issue open until it is fixed.)

**Comment by janhenke** [comment]
> Try choosing a working dir without `postgresql` as workaround. (But leave this issue open until it is fixed.)

That seems to be the trick. Indeed it is still broken and needs to be fixed in order to work with a `postgresql` anywhere in the path.

Thank you for making this work for me for now. I hope someone can fix the port proper.
