### ISSUE TITLE
curl:x86-mingw-static

### ISSUE THREAD

**Issue by qeweqradasf1231** [microsoft/vcpkg#33517]
i installed curl:x86-mingw-static with vcpkg
include it to my cmakelist, chose mingw i686 to compile project
###
find_package(CURL REQUIRED CONFIG PATHS "vcpkg/installed/x86-mingw-static/share/curl" )
find_package(cJSON REQUIRED CONFIG PATHS "vcpkg/installed/x86-mingw-static/share/cJSON" )
###
and got error 
CMake Error at CMakeLists.txt:13 (find_package):
  Could not find a configuration file for package "CURL" that is compatible
  with requested version "".

  The following configuration files were considered but not accepted:
  vcpkg/installed/x86-mingw-static/share/curl/CURLConfig.cmake, version: 8.2.1-DEV (64bit)

    ########
   if i comment curl find package
  and use only cjson its working 
 something wrong with package curl:x86-mingw-static

**Comment by dg0yt** [comment]
You should use the `vcpkg.cmake` toolchain file, and just `find_package(CURL CONFIG REQUIRED)`.
You can get more CMake tracing with `CMAKE_FIND_DEBUG_MODE` set to `1`.
