### ISSUE TITLE
[clipper2] update to 1.2.2

### ISSUE THREAD

**Issue by pinojojo** [microsoft/vcpkg#33510]
### Library name

Clipper2

### New version number

1.2.2

**Comment by xiaozhuai** [comment]
`clipper2` is already 1.2.2 in vcpkg. Did you forget to pull the latest commits?
https://github.com/microsoft/vcpkg/blob/4a600e9fea71bd7872080cbb716797e04d30e6d3/ports/clipper2/vcpkg.json#L2-L6

**Comment by MonicaLiu0311** [comment]
Duplicate of #32713.
