### ISSUE TITLE
[libffi]  cannot create ALIAS target "libffi" because another target   with the same name already exists.

### ISSUE THREAD

**Issue by Brucewu998** [microsoft/vcpkg#33529]
### Operating system

Ubuntu 20.04 LTS

### Compiler

gcc  9.4.0

### Steps to reproduce the behavior

```Shell
// Manifest mode vcpkg.json
{
    "name": "test",
    "version": "0.1.0",
    "dependencies": [
        "qt"
    ]
}

// cmake build command
sudo cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake
```

### Failure logs

CMake Error at /opt/vcpkg/scripts/buildsystems/vcpkg.cmake:639 (_add_library):
  _add_library cannot create ALIAS target "libffi" because another target
  with the same name already exists.
Call Stack (most recent call first):
  build/vcpkg_installed/x64-linux/share/libffi/libffiConfig.cmake:5 (add_library)
  /opt/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  build/vcpkg_installed/x64-linux/share/Qt6/FindGObject.cmake:20 (find_package)
  /opt/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  build/vcpkg_installed/x64-linux/share/Qt6/FindGStreamer.cmake:25 (find_package)
  /opt/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  /snap/cmake/1329/share/cmake-3.27/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
  build/vcpkg_installed/x64-linux/share/Qt6/QtPublicDependencyHelpers.cmake:36 (find_dependency)
  build/vcpkg_installed/x64-linux/share/Qt6Multimedia/Qt6QGstreamerMediaPluginDependencies.cmake:5 (_qt_internal_find_third_party_dependencies)
  build/vcpkg_installed/x64-linux/share/Qt6Multimedia/Qt6QGstreamerMediaPluginConfig.cmake:48 (include)
  build/vcpkg_installed/x64-linux/share/Qt6/QtPublicPluginHelpers.cmake:518 (include)
  build/vcpkg_installed/x64-linux/share/Qt6Multimedia/Qt6MultimediaPlugins.cmake:5 (__qt_internal_include_plugin_packages)
  build/vcpkg_installed/x64-linux/share/Qt6Multimedia/Qt6MultimediaConfig.cmake:123 (include)
  /opt/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  /snap/cmake/1329/share/cmake-3.27/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
  build/vcpkg_installed/x64-linux/share/Qt6/QtPublicDependencyHelpers.cmake:111 (find_dependency)
  build/vcpkg_installed/x64-linux/share/Qt6InterfaceFramework/Qt6MediaPluginDependencies.cmake:15 (_qt_internal_find_qt_dependencies)
  build/vcpkg_installed/x64-linux/share/Qt6InterfaceFramework/Qt6MediaPluginConfig.cmake:48 (include)
  build/vcpkg_installed/x64-linux/share/Qt6/QtPublicPluginHelpers.cmake:518 (include)
  build/vcpkg_installed/x64-linux/share/Qt6InterfaceFramework/Qt6InterfaceFrameworkPlugins.cmake:5 (__qt_internal_include_plugin_packages)
  build/vcpkg_installed/x64-linux/share/Qt6InterfaceFramework/Qt6InterfaceFrameworkConfig.cmake:123 (include)
  /opt/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  /snap/cmake/1329/share/cmake-3.27/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
  build/vcpkg_installed/x64-linux/share/Qt6/QtPublicDependencyHelpers.cmake:111 (find_dependency)
  build/vcpkg_installed/x64-linux/share/Qt6IfMedia/Qt6IfMediaDependencies.cmake:39 (_qt_internal_find_qt_dependencies)
  build/vcpkg_installed/x64-linux/share/Qt6IfMedia/Qt6IfMediaConfig.cmake:40 (include)
  /opt/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  /snap/cmake/1329/share/cmake-3.27/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
  build/vcpkg_installed/x64-linux/share/Qt6/QtPublicDependencyHelpers.cmake:111 (find_dependency)
  build/vcpkg_installed/x64-linux/share/Qt6Qml/QmlPlugins/Qt6IfMediapluginDependencies.cmake:15 (_qt_internal_find_qt_dependencies)
  build/vcpkg_installed/x64-linux/share/Qt6Qml/QmlPlugins/Qt6IfMediapluginConfig.cmake:48 (include)
  build/vcpkg_installed/x64-linux/share/Qt6Qml/Qt6QmlPlugins.cmake:18 (include)
  build/vcpkg_installed/x64-linux/share/Qt6Qml/Qt6QmlConfig.cmake:124 (include)
  /opt/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  build/vcpkg_installed/x64-linux/share/Qt6/Qt6Config.cmake:157 (find_package)
  /opt/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  modules/mqtt_client/CMakeLists.txt:17 (find_package)

**Comment by dg0yt** [comment]
Oops, missed an `if` guard in https://github.com/microsoft/vcpkg/blob/master/ports/libffi/libffiConfig.cmake.
Workaround: Pin the previous version of libffi in `vcpkg.json`.

**Comment by Brucewu998** [comment]
> Oops, missed an `if` guard in https://github.com/microsoft/vcpkg/blob/master/ports/libffi/libffiConfig.cmake. Workaround: Pin the previous version of libffi in `vcpkg.json`.
I tried the mr commit in https://github.com/microsoft/vcpkg/pull/33545, it work, thank you @dg0yt
