### ISSUE TITLE
[qtbase] vcpkg doesn't copy/deploy QtSql plugins in manifest mode

### ISSUE THREAD

**Issue by silverqx** [microsoft/vcpkg#33539]
I have the `vcpkg.json` file like this (I have stripped all unneeded fields for this example):

```json
{
  "name": "tinyorm-helloworld",
  "dependencies": [
    {
      "name": "qtbase",
      "default-features": false,
      "features": ["sql-sqlite"]
    }
  ]
}
```

Now I invoke the `CMake` configure and build and everything finishes as expected without any errors. 👍

Now I open the `CMake` build folder and I see my executable `HelloWorld.exe` and I also see that the `vcpkg` copied or deployed all the `DLL` dependencies inside this build folder next to the `HelloWorld.exe`. And these `dll-s` are:

 - double-conversion.dll
 - pcre2-16d.dll
 - Qt6Cored.dll
 - Qt6Sqld.dll
 - zlibd1.dll
 - TinyOrm0d.dll
 - HelloWorld.exe

And now, where the problem is, the `Qt6\plugins\sqldrivers\qsqlited.dll` **is missing**.

When I look to the `vcpkg_installed\x64-windows\` inside the build folder, then the `Qt6\plugins\sqldrivers\qsqlited.dll` is there and was correctly built.

I have also checked the `vcpkg_installed\x64-windows\share\Qt6Sql\Qt6QSQLiteDriverPluginTargets-debug.cmake` and all other related `Qt6QSQLiteDriverPlugin*.cmake` files if the paths inside them are correct, and they are.

Now what happens when I invoke the `HelloWorld.exe`, it of course throws the following exception:

```
TinyORM 0.34.1 (x86_64-little_endian-llp64 shared debug build; by MSVC 2022 (1937))
QSqlDatabase: QSQLITE driver not loaded
QSqlDatabase: available drivers:
QSqlDatabase: an instance of QCoreApplication is required for loading driver plugins

Caught 'Orm::Exceptions::SqlError' Exception:
Failed to open database connection in Connector::createQSqlDatabaseConnection().
QSqlError(Driver not loaded, Driver not loaded)
```

Now, If I manually copy the `Qt6\plugins\sqldrivers\qsqlited.dll` into the `CMake` build folder, where other `dll-s` were copied or deployed then everything works fine. 👌

So the expected `CMake` build folder structure should be like this:

 - Qt6\plugins\sqldrivers\qsqlited.dll
 - double-conversion.dll
 - pcre2-16d.dll
 - Qt6Cored.dll
 - Qt6Sqld.dll
 - zlibd1.dll
 - TinyOrm0d.dll
 - HelloWorld.exe

@Neumann-A @

**Comment by Neumann-A** [comment]
So where is your actual deployment code? If you are just using vcpkg's applocal deploy that is not going to work for qt since it cannot see through plugins.

**Comment by silverqx** [comment]
> So where is your actual deployment code? 

I don't have any deployment code. This copying of `dll-s` into the build folder is doing `vcpkg` somehow or somewhere. I never saw it in normal builds. This is only happening with the `vcpkg` in manifest mode.

Any other builds that I'm doing eg. `CMake` with `FetchContent` without `vcpkg`, or with `vcpkg` in manifest mode but with header libraries only like `range-v3` or `tabulate` doesn't copy `dll-s` into the build folder (is logical that header only libraries don't have `dll-s` so anything to deploy to build folder in this case).

I saw this first time yesterday.

**Comment by silverqx** [comment]
> If you are just using vcpkg's applocal deploy that is not going to work for qt since it cannot see through plugins.

You are right, the `Qt6Sqld.dll` doesn't really depends on these `QtSql` plugins like `qsqlite.dll` or `qsqlpsql.dll` if you look through the `dumpbin` or `ldd`.

I fastly looked who is responsible for this and it's done [here](https://github.com/microsoft/vcpkg/blob/4a600e9fea71bd7872080cbb716797e04d30e6d3/scripts/buildsystems/vcpkg.cmake#L605) and [here](https://github.com/microsoft/vcpkg/blob/master/scripts/buildsystems/msbuild/applocal.ps1#L84) and it looks there is also some logic for `Qt Plugins` [here](https://github.com/microsoft/vcpkg/blob/master/scripts/buildsystems/msbuild/applocal.ps1#L118) but it has to contain bug because is doing nothing. If I look at the `git blame` then all commit messages at these lines with the `deployPluginsIfQt` are talking about `Qt 5`, nothing about `Qt 6`, and were created by @ras0219-msft Maybe he can tell us something more.

Frankly, I don't care too much, I simply copy it manually to the build folder if I need to or I'm able to write my deploy logic, much bigger problem is with users that will use this and don't know how to fix it.

I don't understand this `vcpkg` deploy logic, these scripts are too complex to quickly dive in and propose a nice PR for foreigner.

**Comment by Neumann-A** [comment]
> I don't have any deployment code.

If you don't have deployment don't expect deployment. Qt6 has extra cmake modules for deployment which you should be using in your cmake code https://www.qt.io/blog/cmake-deployment-api

Secondly for debugging from the build folder simply setup a `qt.conf` or set the Qt environment variables for plugin lookup accordingly. 

Thirdly, this is not a vcpkg issue. This is either a downstream issue not setting it up correctly or an upstream issue not giving enough guidance to make it work.

**Comment by silverqx** [comment]
And who is deploying these files into the build folder?

```
 - double-conversion.dll
 - pcre2-16d.dll
 - Qt6Cored.dll
 - Qt6Sqld.dll
 - zlibd1.dll
 - TinyOrm0d.dll
```

**Comment by Neumann-A** [comment]
> If I don't have any deploy logic for this then who is deploying these files into the root build folder

vcpkg but that is a "feature" which only really works for simple cases which Qt is not. You can deactivate it by setting VCPKG_APPLOCAL_DEPS  to OFF.

**Comment by silverqx** [comment]
😂 man

**Comment by silverqx** [comment]
Thank you for the suggestions and clarification, I'm closing because it doesn't seem to be the `vcpkg` problem.

**Comment by autoantwort** [comment]
In the far future this would be fixed by https://github.com/microsoft/vcpkg-tool/pull/974

**Comment by Neumann-A** [comment]
I wouldnt consider this a fix but a reimplementation of upstreams deployment logic which might change with version updates. It would be better for vcpkg to directly run a post build command instead invoking windeployqt itself.
