### ISSUE TITLE
[g2o] <can't find Cholmod>

### ISSUE THREAD

**Issue by yinchi447** [microsoft/vcpkg#33534]
When I build g2o with vcpkg, cmake can't find Cholmod which has been already installed by suitesparse. This problem causes some of the important libraries of g2o not to be installed. I have been frustrated with this problem for several days. I would appreciate it if you could tell me how to deal with it.
I use vcpkg.json to build my project:

> {
  "name": "project",
  "version-semver": "1.0.0",
  "dependencies": [
    "g2o",
    "suitesparse"
  ],
  "builtin-baseline": "0895a813036f4d189e2bdd1b62741744614347b4",
  "overrides": [
    {
      "name": "g2o",
      "version-string": "20170730_git"
    },
    {
      "name": "suitesparse",
      "version": "5.4.0-3"
    }
  ]
}

Here is the CMakeLists.txt of g2o, the place about Cholmod is around line 122.
[CMakeLists.txt](https://github.com/microsoft/vcpkg/files/12514531/CMakeLists.txt)

**Comment by FrankXie05** [comment]
@yinchi447 Have you passed the `CMAKE_TOOLCHAIN_FILE` provided by vcpkg?

**Comment by yinchi447** [comment]
I don't know. I just built my project by visual studio 2019 with vcpkg.json.

**Comment by FrankXie05** [comment]
Please read this https://github.com/microsoft/vcpkg#visual-studio-code-with-cmake-tools

**Comment by yinchi447** [comment]
I don't use Vcpkg with Visual Studio CMake Projects, I just used Visual Studio.
When I want to use g2o, I found that some g2o header files, like "g2o/solvers/cholmod/linear_solver_cholmod.h",  are not installed. I think the reason for this is that cholmod can't be found when built g2o. But cholmod was installed by suitesparse. So I'm confused how to deal with it.

**Comment by FrankXie05** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can ping me with more info and I will reopen.
