### ISSUE TITLE
error: building gettext-libintl:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by omer150** [microsoft/vcpkg#33533]
Hi,

When trying to install glib on my laptop, I keep having an issue where a download fails. Not sure if this helps or not, but when I click onto the link it doesn't come up with anything to download.

![Screenshot 2023-09-04 123222](https://github.com/microsoft/vcpkg/assets/69389703/dbbca2c2-1a59-43e4-87d2-f0c808a8b058)

![image](https://github.com/microsoft/vcpkg/assets/69389703/c7255022-b97e-45a5-86a0-217db6828f9d)

**Comment by jimwang118** [comment]
I could install this port successfully with the latest vcpkg 2023-08-09-9990a4c9026811a312cb2af78bf77f3d9d288416, could you please run following commands in your vcpkg folder:

```
1. git pull
2. .\bootstrap-vcpkg.bat
3. .\vcpkg install gettext-libintl:x64-windows --binarysource=clear
```
![image](https://github.com/microsoft/vcpkg/assets/122244446/09fc1067-a967-4940-9790-2f5656bdcd75)

**Comment by omer150** [comment]
This has fixed the issue. Thank you very much.

**Comment by jimwang118** [comment]
> hi, I had issue with this lib during "vcpkg install glib", but I dont know if it was not caused by my long path ... as I moved folder to d:\vcpkd and tried the last @jimwang118 to build it separately, then it seems it continues... ![image](https://private-user-images.githubusercontent.com/10888697/332160207-821a50b7-faea-498e-8042-3c947e351f0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNTU5MzAsIm5iZiI6MTcxNjI1NTYzMCwicGF0aCI6Ii8xMDg4ODY5Ny8zMzIxNjAyMDctODIxYTUwYjctZmFlYS00OThlLTgwNDItM2M5NDdlMzUxZjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDAxNDAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMzRiZTljZWJkYWYyMWNkZmNmZjdlYzdhNzM1ZTc1MmU3NTEyZjMwMzRmMTczZWJmZTg4Zjk0YmM1MzUxMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GHsB9bluekrvwYT8osO8wcfBr1CRncLtrfylH2UuKiY)

Did you clone the vcpkg library to the D:/vcpkg directory and install it successfully?
