### ISSUE TITLE
ngspice update to 41

### ISSUE THREAD

**Issue by bhpeng21** [microsoft/vcpkg#33543]
### Library name

ngspice

### New version number

41

### Other information that may be useful (release notes, etc...)

https://sourceforge.net/projects/ngspice/files/ng-spice-rework/41/ngspice-41.tar.gz/download

**Comment by bhpeng21** [comment]
Hello, I’m a user of the ngspice library. I’m writing to ask for your help in updating the version. I’m currently solving this problem by modifying portfile.cmake to download the 39 version of the ngspice library, but I would be grateful if you could help me update the version.

**Comment by jimwang118** [comment]
Ok, I will update this port.

**Comment by bhpeng21** [comment]
Thank you so much! I really appreciate it.
