### ISSUE TITLE
issue installing duktape using vcpkg eror 

### ISSUE THREAD

**Issue by XorbiterGit** [microsoft/vcpkg#33541]
T?h?i?s? ?i?n?s?t?a?l?l?a?t?i?o?n? ?p?a?c?k?a?g?e? ?c?o?u?l?d? ?n?o?t? ?b?e? ?o?p?e?n?e?d?.? ? ?C?o?n?t?a?c?t? ?t?h?e? ?a?p?p?l?i?c?a?t?i?o?n? ?v?e?n?d?o?r? ?t?o? ?v?e?r?i?f?y? ?t?h?a?t? ?t?h?i?s? ?i?s? ?a? ?v?a?l?i?d? ?W?i?n?d?o?w?s? ?I?n?s?t?a?l?l?e?r? ?p?a?c?k?a?g?e?.?
?CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:244 (message):
  Unable to find PYTHON2
Call Stack (most recent call first):
  ports/duktape/portfile.cmake:25 (vcpkg_find_acquire_program)
  scripts/ports.cmake:147 (include)

**Comment by Adela0814** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report an issue.
