### ISSUE TITLE
AZP issue with microsoft.vcpkg.pr: "Pipeline not found"

### ISSUE THREAD

**Issue by dg0yt** [microsoft/vcpkg#33546]
When I click "microsoft.vcpkg.pr" on https://dev.azure.com/vcpkg/public/_build, I get to https://dev.azure.com/vcpkg/public/_build?definitionId=27, but there is now "Pipeline not found" instead of the list of Runs etc.
 - It used to work.
 - There is no such issue with "microsoft.vcpkg.ci" (https://dev.azure.com/vcpkg/public/_build?definitionId=29)
 - The Runs aren't really protected anyways.

Workaround: 
- For Runs, use the "Runs" tab on https://dev.azure.com/vcpkg/public/_build
- For Analytics, no workaround is known.

**Comment by FrankXie05** [comment]
Looks like something is wrong with the recent azure pipeline permissions. 
BTW, I can access it normally (external accounts cannot). 🫤

**Comment by FrankXie05** [comment]
cc @dan-shaw

**Comment by dg0yt** [comment]
Working again. Thanks to the one who solved it.

**Comment by BillyONeal** [comment]
I don't think we changed anything either way:

![image](https://github.com/microsoft/vcpkg/assets/1544943/1c92609c-15cb-4aa0-a884-2eee7763cc55)
