### ISSUE TITLE
[freexl] Build error. m1

### ISSUE THREAD

**Issue by chinaos2008** [microsoft/vcpkg#33548]
Copy issue body from /Users/agile/Downloads/gdal/vcpkg/installed/vcpkg/issue_body.md

error: building freexl:arm64-osx failed with: BUILD_FAILED
Elapsed time to handle freexl:arm64-osx: 1.8 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+freexl
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[freexl]+Build+error&body=Copy+issue+body+from+%2FUsers%2Fagile%2FDownloads%2Fgdal%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by autoantwort** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report an issue.

**Comment by JonLiu1993** [comment]
@chinaos2008, Please follow https://github.com/microsoft/vcpkg/issues/30604 to report an issue, thanks.

**Comment by JonLiu1993** [comment]
Ping @chinaos2008 for response.

**Comment by JonLiu1993** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!

**Comment by hummeltech** [comment]
GitHub has recently migrated their `macos-latest` runner image from using `macos-12` to using `macos-14-arm64`. There seems to be an issue building `freexl` on that platform. I am incuding the `issue_body.md` file as it was previously lacking from this issue.

---

Package: freexl:arm64-osx@2.0.0

**Host Environment**

- Host: arm64-osx
- Compiler: AppleClang 15.0.0.15000040
-    vcpkg-tool version: 2024-03-14-7d353e869753e5609a1f1a057df3db8fd356e49d
    vcpkg-scripts version: b4a3d89 2024-04-15 (11 days ago)

**To Reproduce**

`vcpkg install `
**Failure logs**

```
-- Downloading https://www.gaia-gis.it/gaia-sins/freexl-sources/freexl-2.0.0.tar.gz -> freexl-2.0.0.tar.gz...
-- Extracting source /Users/runner/work/mapnik/mapnik/vcpkg/downloads/freexl-2.0.0.tar.gz
-- Applying patch dependencies.patch
-- Applying patch subdirs.patch
-- Using source at /Users/runner/work/mapnik/mapnik/vcpkg/buildtrees/freexl/src/freexl-2-e1fdd02137.clean
-- Found external ninja('1.12.0').
-- Getting CMake variables for arm64-osx-dbg
-- Getting CMake variables for arm64-osx-rel
-- Generating configure for arm64-osx
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /opt/homebrew/bin/autoreconf -vfi
    Working Directory: /Users/runner/work/mapnik/mapnik/vcpkg/buildtrees/freexl/src/freexl-2-e1fdd02137.clean/
    Error code: 2
    See logs for more information:
      /Users/runner/work/mapnik/mapnik/vcpkg/buildtrees/freexl/autoconf-arm64-osx-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:728 (vcpkg_execute_required_process)
  ports/freexl/portfile.cmake:15 (vcpkg_configure_make)
  scripts/ports.cmake:175 (include)



```
<details><summary>/Users/runner/work/mapnik/mapnik/vcpkg/buildtrees/freexl/autoconf-arm64-osx-err.log</summary>

```
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: glibtoolize --copy --force
Can't exec "glibtoolize": No such file or directory at /opt/homebrew/Cellar/autoconf/2.72/share/autoconf/Autom4te/FileUtils.pm line 318.
autoreconf: error: glibtoolize failed with exit status: 2
```
</details>

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "name": "mapnik",
  "version-string": "master",
  "description": "Mapnik is an open source toolkit for developing mapping applications.",
  "homepage": "https://github.com/mapnik/mapnik",
  "dependencies": [
    "boost-assign",
    "boost-bimap",
    "boost-filesystem",
    "boost-format",
    "boost-geometry",
    "boost-gil",
    "boost-interprocess",
    {
      "name": "boost-locale",
      "features": [
        "icu"
      ]
    },
    "boost-msm",
    "boost-program-options",
    "boost-property-tree",
    {
      "name": "boost-regex",
      "features": [
        "icu"
      ]
    },
    "boost-spirit",
    "boost-system",
    "cairo",
    "cairomm",
    {
      "name": "freetype",
      "features": [
        "bzip2",
        "png"
      ]
    },
    "gdal",
    {
      "name": "harfbuzz",
      "features": [
        "icu"
      ]
    },
    {
      "name": "harfbuzz",
      "features": [
        "coretext"
      ],
      "platform": "osx"
    },
    "icu",
    "libjpeg-turbo",
    "libpng",
    "libpq",
    "libwebp",
    "libxml2",
    "mapbox-geometry",
    "mapbox-polylabel",
    "mapbox-variant",
    "proj",
    "protozero",
    {
      "name": "sqlite3",
      "features": [
        "rtree"
      ]
    },
    "tiff",
    "zlib"
  ]
}

```
</details>
