### ISSUE TITLE
OpenBlas failed compilation

### ISSUE THREAD

**Issue by hjmjohnson** [Microsoft/vcpkg#3354]
$ ./vcpkg.exe install --triplet x64-windows openblas
The following packages will be built and installed:
    openblas[core]:x64-windows
Starting package 1/1: openblas:x64-windows
Building package openblas[core]:x64-windows...
-- CURRENT_INSTALLED_DIR=D:/src/vcpkg/installed/x64-windows
-- DOWNLOADS=D:/src/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/src/vcpkg/packages/openblas_x64-windows
-- CURRENT_BUILDTREES_DIR=D:/src/vcpkg/buildtrees/openblas
-- CURRENT_PORT_DIR=D:/src/vcpkg/ports/openblas/.
-- Using cached D:/src/vcpkg/downloads/xianyi-OpenBLAS-v0.2.20.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch D:/src/vcpkg/ports/openblas/install-openblas.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/src/vcpkg/ports/openblas/install-openblas.patch done
-- Applying patch D:/src/vcpkg/ports/openblas/whitespace.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/src/vcpkg/ports/openblas/whitespace.patch done
-- Configuring x64-windows
-- Configuring x64-windows done
-- Build x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:170 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Debug;--targo
    Working Directory: D:/src/vcpkg/buildtrees/openblas/x64-windows-dbg
    See logs for more information:
      D:\src\vcpkg\buildtrees\openblas\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/openblas/portfile.cmake:93 (vcpkg_install_cmake)
  scripts/ports.cmake:72 (include)

Error: Building package openblas:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openblas:x64-windows
  Vcpkg version: 0.0.110-2018-04-26-bca1e780373864082fe7205a697b76a87508e2ae

Additionally, attach any relevant sections from the log files above.

**Comment by NancyLi1013** [comment]
Thanks a lot for posting this issue.
Please open a new issue if this is still a problem for you.
