### ISSUE TITLE
[vcpkg-cmake] vcpkg_copy_tools() doesn't copy/remove versioned tools/executables on Linux

### ISSUE THREAD

**Issue by silverqx** [microsoft/vcpkg#33551]
I'm creating a port for my `TinyORM` project, the final version can be found [here](https://github.com/silverqx/TinyORM/tree/silverqx-develop/cmake/vcpkg/ports/tinyorm) but it's not merged to the `vcpkg` repo yet.

One of the features that I have is the [`[tom-example]`](https://github.com/silverqx/TinyORM/blob/silverqx-develop/cmake/vcpkg/ports/tinyorm/vcpkg.json#L85) feature that builds the `tom` example console application and I'm using the [`vcpkg_copy_tools()`](https://github.com/silverqx/TinyORM/blob/silverqx-develop/cmake/vcpkg/ports/tinyorm/portfile.cmake#L40) to copy this executable to the `tools/tinyorm/` folder. (currently on the `WIN32` only because of this bug, I'm not installing this `tom` example application on `Linux` platforms)

I'm defining the `CMake` project for this executable like `project(VERSION 0.6.0.0)` (with the `VERSION` option).

> [!NOTE]
> The `bin/xyz -> bin/xyz-0.1.2.3` means the `bin/xyz` is a symlink that points to the `bin/xyz-0.1.2.3` file.

On `Windows` this works as expected because there is only the `tom.exe`.

But on `Linux` is this executable installed as two files, the first is the `bin/tom-0.6.0.0` and the second is a symlink to the first file `bin/tom -> bin/tom-0.6.0.0`.

The `vcpkg_copy_tools()` doesn't handle this, it copies the `bin/tom -> bin/tom-0.6.0.0` symlink to the `tools/tinyorm/tom -> tools/tinyorm/tom-0.6.0.0` (will be a dead symlink) and leaves the `bin/tom-0.6.0.0` file inside the `bin/` folder.

The `CMake` already has the option for this and it's the `file(COPY FOLLOW_SYMLINK_CHAIN)` that exists exactly for these scenarios as it's described in the [`file(COPY)`](https://cmake.org/cmake/help/latest/command/file.html#copy) documentation.

So I tried to add this `FOLLOW_SYMLINK_CHAIN` option to the `vcpkg_copy_tools()` exactly [here](https://github.com/Microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_copy_tools.cmake#L26) and it works as expected, both files were copied to the `tools/tinyorm/` folder. 👌

There are 2 problems.

##### First problem

Is it enough to simply add the `FOLLOW_SYMLINK_CHAIN` to this command? Will it interfere with other platforms or OS, I think that simply adding the `FOLLOW_SYMLINK_CHAIN` option is enough in this case.

##### Second Problem

This problem will not be so simple, after files are copied they also need to be deleted in the `bin/` folder. The [`vcpkg_clean_executables_in_bin()`](https://github.com/Microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_clean_executables_in_bin.cmake) is responsible for this. Deleting the file to which this symlink points to will not be so easy. I think the solution will be:

 - check if the current [`file_name`](https://github.com/Microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_clean_executables_in_bin.cmake#L29) is symlink using the [`if(IS_SYMLINK <path>)`](https://cmake.org/cmake/help/latest/command/if.html#is-symlink)
 - use the [`file(READ_SYMLINK)`](https://cmake.org/cmake/help/latest/command/file.html#read-symlink) to query the symlink and resolve it to the absolute path, whole example is in the [`file(READ_SYMLINK)`](https://cmake.org/cmake/help/latest/command/file.html#read-symlink) documentation
 - delete the real file `bin/tom-0.6.0.0`
 - delete the symlink `bin/tom`

**Comment by dg0yt** [comment]
General advice: Avoid symlinks for portable vcpkg packaging.

Do you really need an executable with version number in the name? vcpkg will install only one version at any time. And if there is an exported CMake target for this executable, it can only point to a single location.

For cleaning up in `bin`, it is often enough to rely on the `AUTO_CLEAN` feature of `vcpkg_copy_tools`. But scripts or symlinks need to be handled separately first.

**Comment by silverqx** [comment]
> General advice: Avoid symlinks for portable vcpkg packaging.

I wanted to but I didn't find any solution for this, this is controlled by the `CMake` `install(TARGETS)` command and it's doing this automatically.

I think there is a purpose for this or why is the `CMake` doing it this way and I probably have an idea why that is.

> Do you really need an executable with version number in the name? 

I don't and I can tell the same thing also for shared/dynamic libraries on Linux and they are installed by `vcpkg` with this version symlinks. I don't need them but this is how Linux is doing it.

> vcpkg will install only one version at any time. And if there is an exported CMake target for this executable, it can only point to a single location.

This is true.

> For cleaning up in `bin`, it is often enough to rely on the `AUTO_CLEAN` feature of `vcpkg_copy_tools`. But scripts or symlinks need to be handled separately first.

I know about this and I'm using it [here](https://github.com/silverqx/TinyORM/blob/silverqx-develop/cmake/vcpkg/ports/tinyorm/portfile.cmake#L41).

**Comment by silverqx** [comment]
This morning I looked if I can install a versioned executable on Linux without this symlink using the `install(TARGETS)` and I didn't find any `CMake` option or solution for this.

**Comment by dg0yt** [comment]
AFAIU the versioned symlink a side-effect of setting the `VERSION` property on executable targets.
Most CMake projects do that only for libraries.
