### ISSUE TITLE
"Waiting to take filesystem lock" takes a long time

### ISSUE THREAD

**Issue by man-in-black382** [microsoft/vcpkg#33557]
Very often vcpkg gets stuck trying to acquire the filesystem lock. Takes minutes at a time, maybe even forever sometimes, but I didn't have patience to wait long enough in some cases. 

**Environment**
- OS: [macOS]
- IDE: [Clion]

**To Reproduce**
1. Install vcpkg to /Users/username/.vcpkg
2. Add vcpkg toolchain file as project's toolchain file
3. Use manifest mode
4. Configure the project

**Expected behavior**
Lock is acquired quickly

**Failure logs**
```
-- Running vcpkg install
waiting to take filesystem lock on /Users/username/.vcpkg/.vcpkg-root...
```

**Additional context**
I can see two vcpkg processes in the Activity Monitor, launched each time I configure the project (after killing the processes, restarting the computer etc). Why exactly two are launched I do not know and also I don't know if that causes the problem, but it wouldn't be surprising. Overall, the wait time appears to be random. Sometimes it's not long, sometimes it is. Today (at the time of posting the issue) it's been especially bad.

**Comment by autoantwort** [comment]
A vcpkg instance can only be used by one process at a time. So the other processes have to wait and while they are waiting you see `waiting to take filesystem lock on /Users/username/.vcpkg/.vcpkg-root...`. If you use vcpkg as a submodule you don't have this problem. 
Or you determine why multiple vcpkg processes are started at the same time. If you open the information of a process in activity manager you see the parent process.

**Comment by man-in-black382** [comment]
So the issue was a bunch of `try_compile` calls that lead to numerous toolchain file inclusions. We have a custom toolchain file that includes the vcpkg toolchain. In any case, multiple inclusion like that lead to multiple runs and instantiations of vcpkg. To avoid this I check if a vcpkg.json file exists in the current cmake dir, if not, then return early.
