### ISSUE TITLE
Error in cppzmqConfig.cmake

### ISSUE THREAD

**Issue by jmpentney** [Microsoft/vcpkg#3356]
Trying to compile a project that uses ZeroMQ and cppzmq with cmake (version 3.11.1) and Visual Studio 2017. I get the following error:

CMake Error at C:/vcpkg/installed/x64-windows/share/cppzmq/cppzmqConfig.cmake:60 (get_target_property):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "LOCATION" is not allowed.
Call Stack (most recent call first):
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:247 (_find_package)
  CMakeLists.txt:28 (find_package)

I ran cmake with the following command:

PS> cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake ..

**Comment by sivabudh** [comment]
Same issue. Mine is on the Mac.

**Comment by JonBoyleCoding** [comment]
This is actually an issue stemming from the original repository: https://github.com/zeromq/cppzmq/issues/209

CMake removed the ability to use the LOCATION property around 3.6 with this usage. It hadn't updated yet. Perhaps a patch can be developed to modify this, although it might be worth waiting for the original repo to fix it.

**Comment by kurdybacha** [comment]
zeromq/cppzmq#209 is now fixed.

**Comment by sivabudh** [comment]
Sounds good. I should try this.

**Comment by ras0219-msft** [comment]
Should be fixed in #4822. Thanks everyone for chiming in!
