### ISSUE TITLE
[python3] Build error

### ISSUE THREAD

**Issue by tiagoeck** [microsoft/vcpkg#33583]
Copy issue body from /home/user/vcpkg/installed/vcpkg/issue_body.md
[package.txt](https://github.com/microsoft/vcpkg/files/12534941/package.txt)

**Comment by Osyotr** [comment]
You probably need to install autoconf-archive

I probably need to add a warning into the port file.

**Comment by PhoebeHui** [comment]
Duplicated of https://github.com/microsoft/vcpkg/issues/33080.
