### ISSUE TITLE
[ERROR macro is defined.] <ceres>

### ISSUE THREAD

**Issue by YingLiangJiang** [microsoft/vcpkg#33624]
### Library name

ceres2.1.0 x64-windows

### Source repository URL

ceres

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

I use ceres v2.1.0 library with vs2019 by vcpkg and built successfully ,but i got a problem when add head file “#include<ceres/ceres.h>" ,it display "ERROR macro is defined. Define GLOG_NO_ABBREVIATED_SEVERITIES before including logging.h. See the document for detail.".I place the macro definition in front of the header file:#define GOOGLE_GLOG_DLL_DECL #define GLOG_NO_ABBREVIATED_SEVERITIES
#include "glog/logging.h" ,strangely there are more errors.
I hope to get help ,thank you!

**Comment by itgo067** [comment]
I also encountered this problem when compiling ceres version 1.14.0, I installed the C++ components for vs2017 and vs2022 , vcpkg uses vs2022 for compilation.

**Comment by YingLiangJiang** [comment]
thank you,bro





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "microsoft/vcpkg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月26日(星期二) 晚上11:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/vcpkg] [ERROR macro is defined.] <ceres&gt; (Issue #33624)





 
I also encountered this problem when compiling ceres version 1.14.0, I installed the C++ components for vs2017 and vs2022 , vcpkg uses vs2022 for compilation.

**Comment by itgo067** [comment]
I solved the problem by lowering the glog version, which may help you.

**Comment by JonLiu1993** [comment]
Tested usage successfully by `ceres:x64-windows`:
````
ceres provides CMake targets:

  # this is heuristically generated, and may not be correct
  find_package(Ceres CONFIG REQUIRED)
  target_link_libraries(main PRIVATE Ceres::ceres)
````
