### ISSUE TITLE
Problems with freeglut static

### ISSUE THREAD

**Issue by vec4f** [Microsoft/vcpkg#3362]
freeglut-3.0.0-3:x86-windows-static and freeglut-3.0.0-3:x64-windows-static have a few problems that prevent them from being successfully linked into programs that attempt to use them. When including GL/glut.h and configuring vcpkg to use one of the above static triplets:

1. FREEGLUT_STATIC is not defined by default, so all the entry points are still marked __declspec(dllimport). The program then fails to link.
2. If FREEGLUT_STATIC is then defined manually, the program still fails to link successfully because the linker will go looking for either freeglut_static.lib or freeglut_staticd.lib. This appears to be due to the '#pragma comment (lib, "freeglut_static.lib")' and '#pragma comment (lib, "freeglut_staticd.lib")' lines that were present in freeglut_std.h when vcpkg built the package. The linker finds freeglut.lib, but then freeglut.lib tries to somehow point at freeglut_static.lib or freeglut_staticd.lib, regardless of what's in freeglut_std.h. 

The fix is to replace "#ifdef FREEGLUT_STATIC" with "#if 1" in the freeglut_std.h file and to ensure *both* pragma comment lib lines for the FREEGLUT_STATIC case are updated *prior* to building the static package, not after.

I'm running Windows 10 Fall Creators Update with VS2017 (15.6.0).

I can submit a pull request that addresses both of the above if there is interest? First time potential contributor here--let me know if I can clarify anything.

**Comment by NancyLi1013** [comment]
Thank you for posting this issue. The related PR #4243 has been merged to the master.
