### ISSUE TITLE
bootstrap-vcpkg.sh downloads cmake when it is installed

### ISSUE THREAD

**Issue by robotdad** [microsoft/vcpkg#3363]
Ubuntu 18.04

I have cmake installed through apt-get, and I built and installed the Microsoft CMake repo at version 3.10.2(unrelated to vcpkg, just that they are installed).

bootstrap-vcpkg.sh downloaded cmake anyway which seems wrong. Portable for vcpkg for consistency?

**Comment by Cheney-W** [comment]
If the path of thelocal cmake.exe has been added to the environment variable PATH, then vcpkg will not download cmake.

**Comment by PhoebeHui** [comment]
VCPKG also check if its version is greater than the needed version.

Duplicated to issue https://github.com/microsoft/vcpkg/issues/4699
