### ISSUE TITLE
macOS SDL2 build failed!

### ISSUE THREAD

**Issue by ryancheung** [Microsoft/vcpkg#3364]
$ vcpkg install sdl2
The following packages will be built and installed:
    sdl2[core]:x64-osx
Starting package 1/1: sdl2:x64-osx
Building package sdl2[core]:x64-osx...
-- CURRENT_INSTALLED_DIR=/Users/Ryan/vcpkg/installed/x64-osx
-- DOWNLOADS=/Users/Ryan/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=/Users/Ryan/vcpkg/packages/sdl2_x64-osx
-- CURRENT_BUILDTREES_DIR=/Users/Ryan/vcpkg/buildtrees/sdl2
-- CURRENT_PORT_DIR=/Users/Ryan/vcpkg/ports/sdl2/.
-- Using cached /Users/Ryan/vcpkg/downloads/SDL-Mirror-SDL-release-2.0.8.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch /Users/Ryan/vcpkg/ports/sdl2/export-symbols-only-in-shared-build.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch /Users/Ryan/vcpkg/ports/sdl2/export-symbols-only-in-shared-build.patch done
-- Applying patch /Users/Ryan/vcpkg/ports/sdl2/enable-winrt-cmake.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch /Users/Ryan/vcpkg/ports/sdl2/enable-winrt-cmake.patch done
-- Configuring x64-osx-dbg
-- Configuring x64-osx-dbg done
-- Configuring x64-osx-rel
-- Configuring x64-osx-rel done
-- Build x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:170 (message):
    Command failed: /Users/Ryan/vcpkg/downloads/tools/cmake-3.10.2-osx/cmake-3.10.2-Darwin-x86_64/CMake.app/Contents/bin/cmake;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: /Users/Ryan/vcpkg/buildtrees/sdl2/x64-osx-dbg
    See logs for more information:
      /Users/Ryan/vcpkg/buildtrees/sdl2/install-x64-osx-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/sdl2/portfile.cmake:33 (vcpkg_install_cmake)
  scripts/ports.cmake:72 (include)

Error: Building package sdl2:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sdl2:x64-osx
  Vcpkg version: 0.0.110-unknownhash

Additionally, attach any relevant sections from the log files above.

Error log /Users/Ryan/vcpkg/buildtrees/sdl2/install-x64-osx-dbg-out.log:
https://drive.google.com/file/d/1dSYf5uRmEu_xucmoA3kxxHKqeINDu6ka/view

**Comment by tosone** [comment]
Just now i test it, everything is ok on my osx.

```
vcpkg install sdl2
The following packages will be built and installed:
    sdl2[core]:x64-osx
Starting package 1/1: sdl2:x64-osx
Building package sdl2[core]:x64-osx...
-- CURRENT_INSTALLED_DIR=/Users/tosone/Downloads/vcpkg-master/installed/x64-osx
-- DOWNLOADS=/Users/tosone/Downloads/vcpkg-master/downloads
-- CURRENT_PACKAGES_DIR=/Users/tosone/Downloads/vcpkg-master/packages/sdl2_x64-osx
-- CURRENT_BUILDTREES_DIR=/Users/tosone/Downloads/vcpkg-master/buildtrees/sdl2
-- CURRENT_PORT_DIR=/Users/tosone/Downloads/vcpkg-master/ports/sdl2/.
-- Downloading https://github.com/SDL-Mirror/SDL/archive/release-2.0.8.tar.gz...
-- Downloading https://github.com/SDL-Mirror/SDL/archive/release-2.0.8.tar.gz... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting source /Users/tosone/Downloads/vcpkg-master/downloads/SDL-Mirror-SDL-release-2.0.8.tar.gz
-- Extracting done
-- Applying patch /Users/tosone/Downloads/vcpkg-master/ports/sdl2/export-symbols-only-in-shared-build.patch
-- Applying patch /Users/tosone/Downloads/vcpkg-master/ports/sdl2/export-symbols-only-in-shared-build.patch done
-- Applying patch /Users/tosone/Downloads/vcpkg-master/ports/sdl2/enable-winrt-cmake.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch /Users/tosone/Downloads/vcpkg-master/ports/sdl2/enable-winrt-cmake.patch done
-- Configuring x64-osx-dbg
-- Configuring x64-osx-dbg done
-- Configuring x64-osx-rel
-- Configuring x64-osx-rel done
-- Build x64-osx-dbg
-- Build x64-osx-dbg done
-- Build x64-osx-rel
-- Build x64-osx-rel done
-- Installing: /Users/tosone/Downloads/vcpkg-master/packages/sdl2_x64-osx/share/sdl2/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package sdl2[core]:x64-osx... done
Installing package sdl2[core]:x64-osx...
Installing package sdl2[core]:x64-osx... done
Elapsed time for package sdl2:x64-osx: 4.042 min

Total elapsed time: 4.042 min

The package sdl2:x64-osx provides CMake targets:

    find_package(sdl2 REQUIRED)
    target_link_libraries(main PRIVATE SDL2::SDL2-static SDL2::SDL2main)
```

**Comment by ryancheung** [comment]
@tosone Which version is your mac book?, Mine is macOS High Serria 10.13.4.

**Comment by ryancheung** [comment]
@tosone Do you use gcc6 to bootstrap vcpkg or clang?

**Comment by tosone** [comment]
MacOS 10.13.4 (17E199). No, All of them are default.

Just like this:

```
./bootstrap-vcpkg.sh
./vcpkg install sdl2
```

```
gcc --version 
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

```
clang --version 
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by ryancheung** [comment]
Mine is:

```
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

I use the CommandLineTools version of clang++

**Comment by ryancheung** [comment]
```
$ ./bootstrap-vcpkg.sh
-- The C compiler identification is AppleClang 9.1.0.9020039
-- The CXX compiler identification is AppleClang 9.1.0.9020039
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/g++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:8 (message):
  Building the vcpkg tool requires support for the C++ Filesystem TS.

  Apple clang versions 9 and below do not have support for it.

  Please install gcc6 or newer from homebrew (brew install gcc6).

  If you would like to try anyway, set VCPKG_ALLOW_APPLE_CLANG.


-- Configuring incomplete, errors occurred!
See also "/Users/Ryan/vcpkg/toolsrc/build.rel/CMakeFiles/CMakeOutput.log".
ninja: error: loading 'build.ninja': No such file or directory
cp: /Users/Ryan/vcpkg/toolsrc/build.rel/vcpkg: No such file or directory
```

**Comment by ryancheung** [comment]
@tosone Your Clang version seems to be the same as mine. But I got this notice to let me  use gcc.

**Comment by ryancheung** [comment]
So that the best practice in macOS is bootstrap vcpkg using gcc6/7 and install package with Apple Clang, right?

**Comment by tosone** [comment]
Do not use gcc-6 or gcc-7. But clang is more powerful on macOS.

**Comment by ryancheung** [comment]
Got it. The problem resolved.
