### ISSUE TITLE
[liblzma] Build error

### ISSUE THREAD

**Issue by hqho** [microsoft/vcpkg#33643]
Hello, I am getting the following build failure:

   vcpkg-tool version: 2022-10-17-3247920fbdd47d08f36cbd480addd9890d3c2435
    vcpkg-scripts version: 94ce0dab5 2022-10-19 (11 months ago)

Please use the prefilled template from /home/jenkins/azure-sdk-for-cpp/build.release/vcpkg_installed/vcpkg/issue_body.md when reporting your issue.
-- Running vcpkg install - failed
CMake Error at /home/jenkins/vcpkg/scripts/buildsystems/vcpkg.cmake:834 (message):
  vcpkg install failed.  See logs for more information:
  /home/jenkins/azure-sdk-for-cpp/build.release/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /home/jenkins/cmake-3.27.4-linux-x86_64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:148 (include)
  CMakeLists.txt:26 (project)

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

[issue_body.md](https://github.com/microsoft/vcpkg/files/12553239/issue_body.md)

Any help resolving this issue is appreciated.

**Comment by dg0yt** [comment]
> vcpkg-tool version: 2022-10-17-3247920fbdd47d08f36cbd480addd9890d3c2435 
> vcpkg-scripts version: [94ce0da](https://github.com/microsoft/vcpkg/commit/94ce0dab56f4d8ba6bd631ba59ed682b02d45c46) 2022-10-19 (11 months ago)

Update vcpkg.

**Comment by Adela0814** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
