### ISSUE TITLE
[openvino] Port version does not track upstream

### ISSUE THREAD

**Issue by RyanHir** [microsoft/vcpkg#33657]
### Is your feature request related to a problem? Please describe.

The version of the openvino port is greater than the current upstream releases. For example, the latest port on vcpkg is 2023.06.11, but the latest upstream release from a few days ago is 2023.0.2

### Proposed solution

On the next major release of OpenVINO, change the versioning of the port to match upstream.

**Comment by ilya-lavrenov** [comment]
Hi @RyanHir 
OpenVINO 2023.0.x does not have fixes for `vcpkg`. Only 2023.1.0 and newer releases will contain changes required for integration into vcpkg infrastructure.
2023.1.0 will be published soon and I already have a PR with publishing a new release https://github.com/microsoft/vcpkg/pull/33079

That PR refers to a commit, but once release a published, this commit will be turned into a tag and update in port file.

**Comment by JonLiu1993** [comment]
Fixing by PR #33079
