### ISSUE TITLE
python3 cmake build error

### ISSUE THREAD

**Issue by geeyef** [Microsoft/vcpkg#3365]
The following packages will be built and installed:
    python3[core]:x86-windows
Starting package 1/1: python3:x86-windows
Building package python3[core]:x86-windows...
-- CURRENT_INSTALLED_DIR=D:/Src/vcpkg/installed/x86-windows
-- DOWNLOADS=D:/Src/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/Src/vcpkg/packages/python3_x86-windows
-- CURRENT_BUILDTREES_DIR=D:/Src/vcpkg/buildtrees/python3
-- CURRENT_PORT_DIR=D:/Src/vcpkg/ports/python3/.
-- Using cached D:/Src/vcpkg/downloads/python-cpython-v3.6.4.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
CMake Error at scripts/cmake/vcpkg_from_github.cmake:88 (message):
  Could not determine source path:
  **'D:/Src/vcpkg/buildtrees/python3/src/cpython-v3.6.4' does not exist**
Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:112 (set_SOURCE_PATH)
  ports/python3/portfile.cmake:13 (vcpkg_from_github)
  scripts/ports.cmake:72 (include)

Error: Building package python3:x86-windows failed with: BUILD_FAILED

**Comment by NancyLi1013** [comment]
Thanks a lot for posting this issue.
Please open a new issue if this is still a problem for you.
