### ISSUE TITLE
[atlmfc] build failure

### ISSUE THREAD

**Issue by Nemirtingas** [microsoft/vcpkg#33658]
### Operating system

Linux

### Compiler

Clang/Clang-CL/Llvm 14

### Steps to reproduce the behavior

```Shell
docker run --name windows -it nemirtingas/windowscross_vcpkg:msvc2019_win10.0.18362.0 bash

cd /
git clone https://github.com/microsoft/vcpkg --branch=master vcpkg_microsoft
cd vcpkg_microsoft
cat >triplets/community/x86-windows-clangcl.cmake <<EOF
set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_BUILD_TYPE release)

set(ENV{HOST_ARCH} ${VCPKG_TARGET_ARCHITECTURE})

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE /clang_windows_sdk/clang-cl-msvc.cmake)

set(ENV{VCPKG_TOOLCHAIN} "/vcpkg/scripts/toolchains/windows.cmake")

set(VCPKG_POLICY_SKIP_ARCHITECTURE_CHECK enabled)
EOF
./bootstrap-vcpkg.sh
./vcpkg install atlmfc:x86-windows-clangcl
```

### Failure logs

Installing 1/1 atlmfc:x86-windows-nemirtingas...
Building atlmfc:x86-windows-nemirtingas...
warning: -- Using community triplet x86-windows-nemirtingas. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /vcpkg/triplets/community/x86-windows-nemirtingas.cmake
CMake Error at ports/atlmfc/portfile.cmake:7 (message):
  Unable to locate 'afxres.h'.  Ensure you have installed the ATL/MFC
  component of Visual Studio.
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)

error: building atlmfc:x86-windows-nemirtingas failed with: BUILD_FAILED
Elapsed time to handle atlmfc:x86-windows-nemirtingas: 25.7 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+atlmfc
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[atlmfc]+Build+error&body=Copy+issue+body+from+%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

I'm cross-compiling. The port seems to look for `afxres.h` without loading the `VCPKG_CHAINLOAD_TOOLCHAIN_FILE`

**Comment by autoantwort** [comment]
Have you set the toolchain file in your custom triplet? `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` is for your cmake project and not used when building ports.

**Comment by Nemirtingas** [comment]
My custom triplet is like so :
```
set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_BUILD_TYPE release)

set(ENV{HOST_ARCH} ${VCPKG_TARGET_ARCHITECTURE})

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE /clang_windows_sdk/clang-cl-msvc.cmake)

set(ENV{VCPKG_TOOLCHAIN} "/vcpkg/scripts/toolchains/windows.cmake")

set(VCPKG_POLICY_SKIP_ARCHITECTURE_CHECK enabled)
```

I've changed the port atlmfc on my for of vcpkg to something like this:
- CMakeLists.txt
```
cmake_minimum_required(VERSION 3.0)
project(Find_active_template_library)

try_compile(COMPILE_SUCCEEDED
  SOURCES ${CMAKE_SOURCE_DIR}/main.cpp
  OUTPUT_VARIABLE COMPILE_OUTPUT)
```

- main.cpp
```
#include <atlbase.h>

int main(int argc, char *argv[])
{
  return 0;
}
```

- portfile.cmake
```
SET(VCPKG_POLICY_EMPTY_PACKAGE enabled)

vcpkg_cmake_configure(
    SOURCE_PATH "${CURRENT_PORT_DIR}"
    OPTIONS
        "-DCMAKE_PREFIX_PATH=${CURRENT_PACKAGES_DIR}"
        "-DCMAKE_IGNORE_PATH=${CMAKE_IGNORE_PATH}"
)
```

- vcpkg.json
```
{
  "name": "active-template-library",
  "version": "0",
  "description": "a stub package that ensures VS has ATL installed.",
  "supports": "windows",
  "dependencies": [
    {
      "name": "vcpkg-cmake",
      "host": true
    }
  ]
}
```

**Comment by Nemirtingas** [comment]
The current atlmfc port just triies to find `afxres.h` but that is a cmake function, and cmake has no ways to use my cross-compilation toolchain. The easy way that always works that I found is to just compile a stupid program that uses the required file.
