### ISSUE TITLE
[thrift] update to v0.17.0

### ISSUE THREAD

**Issue by cartel1** [microsoft/vcpkg#33652]
### Library name

Apache Thrift

### New version number

v0.17.0

### Other information that may be useful (release notes, etc...)

Please provide update for Apache Thrift version 0.17.0.

Thanks.

**Comment by cartel1** [comment]
Hello,

What is the status of this PR? Can it be merged? 

Thanks.

**Comment by MonicaLiu0311** [comment]
Yes, it has been reviewed and we will remind the team to merge it as soon as possible.
