### ISSUE TITLE
using "--triplet <somelib>" when installing gives a weird bug

### ISSUE THREAD

**Issue by RealityTracer** [microsoft/vcpkg#33661]
**Describe the bug**
I have used vcpkg to installed lot of libs by using 'vcpkg install --triplet x64-windows-v142 <somelib>'. The x64-windows-v142.cmake is as follows:
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PLATFORM_TOOLSET "v142").
The x64-windows-v142.cmake  makes no sense, just tells vcpkg to use vs2019 to compile libs. 

After that, I used 'vcpkg integrate install'  and 'vcpkg integrate  --triplet x64-windows-v142  install' to make the installed libs be found in vs2019.  What a pity, it did not work. I have tried lots of ways to solve it, like https://learn.microsoft.com/en-us/vcpkg/users/buildsystems/msbuild-integration. It still made no sense. Finally, I use the command with default triplet name , 'vcpkg install <somelib> --triplet x64-windows'. It got work in vs2019.  Does it mean that users should not customize their own triplet.cmake files ?

**Environment**
- OS: [e.g. Windows..]
- Compiler: v142 vs2019 community

**Comment by StarGate-One** [comment]
Creating a triplet file with the only change of adding the toolset of v142 is really pointless, if you only have vs2019 installed.

Vcpkg is smart enough to know to use the default toolset for vs2019 which is toolset v142 even if you installed the v140 and v141 toolsets with vs2019, just as the default for vs2015 is v140, vs2017 is v141 and vs2022 v143.

You just need to run `vcpkg install <options><ports-features>` using the `x64-windows` triplet.

I am not aware of the, `vcpkg integrate install` on windows accepting a `triplet` option.

From my interpretation `vcpkg integrate install` it integrates all visual studio versions, 2015 through 2022 to the `vcpkg instance root` where the `vcpkg integrate install` is run; just as `vcpkg integrate remove` will remove integration from all the aforementioned visual studio installs.

I can see the `vcpkg integrate install` accepts the triplet options but it does not seem to do anything with it nor does it give any type of message stating it is not needed or is ignored?
Maybe someone more knowledgeable of vcpkg can weigh in on whether vcpkg does anything with the triplet option on the integrate command?

Note: After the September 2023 release of `vcpkg tool (vcpkg.exe)` the default triplet will be x64-windows instead of x86-windows.
Hope this helps and you have a wonderful day!

**Comment by RealityTracer** [comment]
> Creating a triplet file with the only change of adding the toolset of v142 is really pointless, if you only have vs2019 installed.
> 
> Vcpkg is smart enough to know to use the default toolset for vs2019 which is toolset v142 even if you installed the v140 and v141 toolsets with vs2019, just as the default for vs2015 is v140, vs2017 is v141 and vs2022 v143.
> 
> You just need to run `vcpkg install <options><ports-features>` using the `x64-windows` triplet.
> 
> I am not aware of the, `vcpkg integrate install` on windows accepting a `triplet` option.
> 
> From my interpretation `vcpkg integrate install` it integrates all visual studio versions, 2015 through 2022 to the `vcpkg instance root` where the `vcpkg integrate install` is run; just as `vcpkg integrate remove` will remove integration from all the aforementioned visual studio installs.
> 
> I can see the `vcpkg integrate install` accepts the triplet options but it does not seem to do anything with it nor does it give any type of message stating it is not needed or is ignored? Maybe someone more knowledgeable of vcpkg can weigh in on whether vcpkg does anything with the triplet option on the integrate command?
> 
> Note: After the September 2023 release of `vcpkg tool (vcpkg.exe)` the default triplet will be x64-windows instead of x86-windows. Hope this helps and you have a wonderful day!

Thanks for reply. Firstly, creating a triplet file with the name of 'x64-windows-v142'  is pointless if you only need the runtime of VS2019. In some case, I really need the binary built by VS2017 VS2015 VS2013 etc. As far as I know, vcpkg always uses the highest toolset.  Sencodly, in my previous comments, the words , "Finally, I use the command with default triplet name , 'vcpkg install '", have some errors. They should be "Finally, I use the command with default triplet name , 'vcpkg install --triplet x64-windows'". I missed the '-triplet x64-windows' and have updated the words. I also have used 'vcpkg install somelib' without any triplets in my x64 Native Tool Commond Prompt for VS2019. Unluckily, although vcpkg present the warning, like 'warning: Starting with the September 2023 release, the default triplet for vcpkg libraries will change from x86-windows to the detected host triplet (x64-windows). To resolve this message, add --triplet x86-windows to keep the same behavior', it still installs the x86-windows.

**Comment by StarGate-One** [comment]
>Does it mean that users should not customize their own triplet.cmake files ?

I am unable to answer this question as I do not have that knowledge available to me, that said after doing some research it looks as there is a direction to use either community triplets or overlay triplets:
1. Create the community triplet (as you have already done) and put it in the `<vcpkg-root>/triplets/community` folder and use the `--triplet <your triplet name>` as a command line option when invoking the vcpkg CLI.
2. Use an [overlay triplet](https://learn.microsoft.com/en-us/vcpkg/users/examples/overlay-triplets-linux-dynamic) and `set VCPKG_OVERLAY_TRIPLETS=<list of paths where your overlay triplets exist>`.

Maybe others from the community can chime in and suggest other ways to achieve the results you desire.

**Comment by dg0yt** [comment]
I'm not yet able to understand what is the "weird bug" here.

> 'vcpkg integrate install' and 'vcpkg integrate --triplet x64-windows-v142 install' 

AFAICT the `integrate` command doesn't use a triplet argument. It is ["user-wide integration"](https://learn.microsoft.com/en-us/vcpkg/users/buildsystems/msbuild-integration#user-wide-integration). Why should a user be restricted to one target triplet?

> 'vcpkg install --triplet x64-windows'

This is the `install` command, and it accepts target and host triplet in various ways (arguments, environment variables)`. For CMake and MSBuild build system, the documentation describes additional options how to set this for a particular build. Maybe this is what you look for with regard to manifest mode.

> Does it mean that users should not customize their own triplet.cmake files ?

No.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
