### ISSUE TITLE
[libiconv] Build error

### ISSUE THREAD

**Issue by Ran-gok** [microsoft/vcpkg#33675]
Copy issue body from D:/umum/vcpkg/installed/vcpkg/issue_body.md

building libiconv:x64-windows-static failed

I don't think it's a space error, but what on earth is it? Where can I show the error log?

vcpkg install tesseract:x64-windows-static > log.txt

**Comment by JonLiu1993** [comment]
@Ran-gok, Thanks for posting this issue, there is no error log in the error log you provided. please see #30604 for how to report an issue.

**Comment by Ran-gok** [comment]
I saw the video.
But what kind of program is that? I need to know what it is so I can use the command like in the #30604 video.
Can you tell me where to start?

**Comment by JonLiu1993** [comment]
> @JonLiu1993 , I saw the video. But what kind of program is that? I need to know what it is so I can use the command like in the #30604 video. Can you tell me where to start?

@Ran-gok, the program is Visual Studio Code.

**Comment by Ran-gok** [comment]
@JonLiu1993 , I'm sorry, but that's not very descriptive.
There is a VS2022 version, but it doesn't have a category like Video.
Or at least have some sort of order to the posts...
Where do you get the copy and paste text for videos?
git pull <-what is this...?
./bootstrap-vcpkg.bat(windows) <-- where am I typing this?

There may be some newbies who don't know anything.
Please explain in detail.

**Comment by JonLiu1993** [comment]
@Ran-gok, All you need to do is send me a screenshot of the error message you reported.

**Comment by Ran-gok** [comment]
@JonLiu1993 ,
![1](https://github.com/microsoft/vcpkg/assets/137247784/1c1665e0-4815-4e4e-bef7-af249a64da2f)
![2](https://github.com/microsoft/vcpkg/assets/137247784/a76c6a58-d1be-41b8-8dc9-d299b3c55eb6)
이렇게요?

**Comment by JonLiu1993** [comment]
@Ran-gok, please try use command `git pull` and `.\bootstrap-vcpkg.bat` then try again.

**Comment by JonLiu1993** [comment]
@newholder, Please provide your error log.

**Comment by Ran-gok** [comment]
![3](https://github.com/microsoft/vcpkg/assets/137247784/b2a1334a-edd8-4086-a45e-335ddd5c753e)
fatal, is this correct?
No response.

**Comment by newholder** [comment]
> @newholder, Please provide your error log.

I'm sorry @JonLiu1993 , I ragequit so hard I deleted my project along with the log and vcpkg installation. The good news is I get it to work by not using the vcpkg installed through Visual Studio Installer, but by cloning the repo directly and setting up the appropriate env variables manually. @Ran-gok , try uninstalling just the vcpkg in the Visual Studio Installer and install it from cloning the repo, like in the get started guide on the website. Only installation using the clone method has the `.\bootstrap-vcpkg.bat` and can use `git pull`

**Comment by JonLiu1993** [comment]
@Ran-gok, please try @newholder's suggestion, I can't reproduce your error on my local machine.

**Comment by Ran-gok** [comment]
@newholder , Can you explain the operation method in detail? I am a complete beginner.
For example, 1->2->3 and so on. There is vs2022. But I don't know where or what to do. Can you explain in detail?

**Comment by Ran-gok** [comment]
> > @newholder, Please provide your error log.
> 
> I'm sorry @JonLiu1993 , I ragequit so hard I deleted my project along with the log and vcpkg installation. The good news is I get it to work by not using the vcpkg installed through Visual Studio Installer, but by cloning the repo directly and setting up the appropriate env variables manually. @Ran-gok , try uninstalling just the vcpkg in the Visual Studio Installer and install it from cloning the repo, like in the get started guide on the website. Only installation using the clone method has the `.\bootstrap-vcpkg.bat` and can use `git pull`

@newholder , Can you explain the operation method in detail? I am a complete beginner.
For example, 1->2->3 and so on. There is vs2022. But I don't know where or what to do. Can you explain in detail?

**Comment by JonLiu1993** [comment]
@Ran-gok, 
````
Step 1: Clone the vcpkg repo

git clone https://github.com/Microsoft/vcpkg.git

Make sure you are in the directory you want the tool installed to before doing this.

Step 2: Run the bootstrap script to build vcpkg

.\vcpkg\bootstrap-vcpkg.bat

Install libraries for your project
vcpkg install [packages to install]

Using vcpkg with MSBuild / Visual Studio (may require elevation)
.\vcpkg integrate install

After this, you can create a new project or open an existing one in the IDE. All installed libraries should already be discoverable by IntelliSense and usable in code without additional configuration.

Step 3: Install libiconv 
.\vcpkg install  tesseract:x64-windows-static
````

**Comment by Ran-gok** [comment]
@JonLiu1993 , I'm sorry, but can you be more specific?
Is that typing a command in CMD?

Install libraries for your project <-is this the project I want to build?
vckg instalpl [packages to install] <- what is packages...?

.\vcpkg integrate install<- After that, open a new project in vs2022 and import the project you want to build,

.\vcpkg install tesseract:x64-windows-static and finally type it into CMD?

Thank you so much for the step by step, but I'm a complete beginner, so I don't really know what program to enter and where, sorry. I need a little more detail.

**Comment by JonLiu1993** [comment]
@Ran-gok, open powershell in the folder you created and enter the following commands in sequence:

1. git clone https://github.com/Microsoft/vcpkg.git
2. .\bootstrap-vcpkg.bat
3. .\vcpkg integrate install
4. .\vcpkg install  tesseract:x64-windows-static

![image](https://github.com/microsoft/vcpkg/assets/63675417/c65d71d7-9653-402d-a59c-a3326fdfddeb)

**Comment by Ran-gok** [comment]
@JonLiu1993 , I'm getting the same error as before......
It's hard.

**Comment by newholder** [comment]
@Ran-gok have you uninstall the vcpkg from the visual studio installer? you might be using that version.

go to start > search > type for visual studio installer and click > click modify > go to individual component > type vcpkg > untick > click modify.

after that, close cmd and open it again. type vcpkg. if ypu can't launch it you successfully uninstall it. Now reinstall using method provided by @JonLiu1993. Make sure you note the folder where you install it. the folder where you run the `git clone` command so we can add it to environment path later.

Now go to start again > search > type environment > click edit environment variables for your account > it will show 2 list > in a table labeled User variables click the row with the word 'Path' in it and click edit > it will open another window > click new > paste vcpkg installation path > now click ok till you close the window

close cmd and open again > successful install if you can run vcpkg

**Comment by Ran-gok** [comment]
@newholder Thank you.
But installing as provided by @JonLiu1993 ,
I'm getting the same error. I did the vcpkg uninstall you told me to do, but the
same thing.
Because my vcpkg install tesseract:x64-windows-static doesn't build,
The guy who wrote the codeprogram I was trying to build gave me a tarball that finished building tesseract:x64-windows-static,
Do you know where I can put this built file and use it?

**Comment by newholder** [comment]
@Ran-gok Can you provide the screenshoot of the error log please?

**Comment by Ran-gok** [comment]
@newholder  I'm not sure how to get the error logs separately.
I've attached a screenshot above.
The errors always come out like that.

**Comment by newholder** [comment]
@Ran-gok Can you provide what command you run and which directory it was run? Also, you can check which vcpkg binary you are using with the `where` command. so `where vcpkg`. To output the log file. You may pipe the output of your command to a log file using `> log.txt`. it will create a log file in your current directory.

So, let's debug it a bit:
1. Run `where vcpkg` and report here the output.
2. Run `vcpkg install tesseract:x64-windows-static > log.txt` and wait until it finished. it will look as if nothing happened because it no longer output to the console, instead it output to log.txt file. paste the content of that file here

**Comment by Ran-gok** [comment]
[log.txt](https://github.com/microsoft/vcpkg/files/12642554/log.txt)

I did it with CMD or Powershell, and put it in the directory where vcpkg is located. 
1. enter CD D:\umum\asdasd\vcpkg
2. enter vcpkg
3. enter vcpkg integrate install
(Applied user-wide integration for this vcpkg root.) OK
4. type vcpkg install tesseract:x64-windows-static
After that, it runs for a bit and then gives an error.
5. error: building libiconv:x64-windows-static failed with: BUILD_FAILED

And I've probably shown the log file to other people as well.
They all said they didn't know what it was....

**Comment by newholder** [comment]
@Ran-gok have you tried `git pull`

**Comment by newholder** [comment]
@Ran-gok I found the folder you might want to look into further: `vcpkg\buildtrees\libiconv`. Maybe inspect the log if there's any.

**Comment by dg0yt** [comment]
- Does the problem also occur if the username doesn't contain non-latin characters? 
  (I see that vcpkg is in a safe path, and binary artifacts are restored properly. But I wonder if libiconv's build properly deals with some environment variables (such as %TEMP%) pointing to the non-latin user paths.)
- What is in your %PATH%? Maybe there interference with vcpkg's MSYS runtime.

**Comment by Ran-gok** [comment]
@newholder D:\umum\asdasd\vcpkg>git pull
Already up to date. comes out.

What do you mean by Edit:? The translator doesn't seem to be working well...

edit2: what does it recognize as a space when there is no space?

**Comment by Ran-gok** [comment]
[libiconv.zip](https://github.com/microsoft/vcpkg/files/12644046/libiconv.zip)
@newholder I don't know which one applies, so I compressed the libiconv file into a bin. will it check?

**Comment by newholder** [comment]
> @newholder D:\umum\asdasd\vcpkg>git pull Already up to date. comes out.
> 
> What do you mean by Edit:? The translator doesn't seem to be working well...
> 
> edit2: what does it recognize as a space when there is no space?

Ignore that. That's the problem on my machine.

At this point I don't know what's the problem. I'm out of suggestion

**Comment by JonLiu1993** [comment]
Try shortening this path `D:\umum\asdasd\vcpkg` to `D:\vcpkg` and try my steps again.

**Comment by JonLiu1993** [comment]
> * Does the problem also occur if the username doesn't contain non-latin characters?
>   (I see that vcpkg is in a safe path, and binary artifacts are restored properly. But I wonder if libiconv's build properly deals with some environment variables (such as %TEMP%) pointing to the non-latin user paths.)
> * What is in your %PATH%? Maybe there interference with vcpkg's MSYS runtime.

Also thinking about that, thanks.

**Comment by Ran-gok** [comment]
@JonLiu1993 It's the same wherever you replace it. I don't have an answer, maybe I should give up...  Thanks.
@newholder UMUM is just a shortened name. I don't think I have an answer. I'll have to give up. Thanks.
