### ISSUE TITLE
[tbb] build failure

### ISSUE THREAD

**Issue by jkankiewicz** [microsoft/vcpkg#33670]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
`./vcpkg install tbb`
```

### Failure logs

```
Computing installation plan...
error: while looking for tbb:x64-windows:
error: while loading C:\vcpkg\ports\tbb\vcpkg.json:
$.default-features[0]: mismatched type: expected an identifier

```

### Additional context

This breakage is a side-effect of merging PR #33586.

Replacing the JSON object value of `$.default-features[0]` with `"hwloc"` enables vcpkg to build the "tbb" package again.

**Comment by Osyotr** [comment]
Do you have latest vcpkg? It also might help.

**Comment by jkankiewicz** [comment]
> Do you have latest vcpkg? It also might help.

No, I didn't.
```
.\vcpkg --version
vcpkg package management program version 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75

See LICENSE.txt for license information.

```

The "tbb" package builds in its current state after I upgraded vcpkg.exe itself.
```
.\vcpkg --version
vcpkg package management program version 2023-08-09-9990a4c9026811a312cb2af78bf77f3d9d288416

See LICENSE.txt for license information.

```
