### ISSUE TITLE
[glad] Build error

### ISSUE THREAD

**Issue by Guest-615695028** [microsoft/vcpkg#33680]
Copy issue body from C:/Users/zwj/vcpkg/installed/vcpkg/issue_body.md
System: Microsoft Windows Version 10.0.19045.3393
error: building glad:x64-windows failed with: BUILD_FAILED
I am using the latest port files with `git pull` and `vcpkg update`.

**Comment by StarGate-One** [comment]
[See #30604 on how to submit a failed port compile](https://github.com/microsoft/vcpkg/issues/30604)

**Comment by Guest-615695028** [comment]
Despite using the latest `vcpkg` version I still failed to build `vcpkg install glfw3 glad glm`.

**Comment by FrankXie05** [comment]
@Guest-615695028 Please provide the error log.

**Comment by FrankXie05** [comment]
This issue hasn’t been updated for a long time; if it is still an issue, please reopen this issue.
