### ISSUE TITLE
How to build curl with openssl

### ISSUE THREAD

**Issue by bangusi** [Microsoft/vcpkg#337]
Is there a swicth / setting I need to apply in order to build curl with openssl or this would be considered a new port?

**Comment by ras0219-msft** [comment]
We should modify the `curl` port to always use `openssl` -- this was an oversight on my part while performing the inital port!

I've fixed this in 7e4a57f, thanks for notifying us!

**Comment by bangusi** [comment]
Still on curl. Is there a reason static build for curl are not supported?
I see this in the portfile
 message(STATUS "Warning: Static building not supported yet. Building dynamic.")

**Comment by alexkaratarakis** [comment]
`vcpkg` only had dynamic builds in the beginning, so some older portfiles haven't been modified to support static building yet. 

However, I just ported this (56581e816a7129d99e25b592035e1de5a8801178) so curl now has static builds!
