### ISSUE TITLE
Segment fault while downloading vcpkg-glibc

### ISSUE THREAD

**Issue by tthres** [microsoft/vcpkg#33716]
**Describe the bug**
Hello I am trying to use vcpkg as my package manager.But when bootstrap-vcpkg.sh is run, I am getting Segmentation fault:

**Environment**
- OS: ubuntu22.04

**To Reproduce**
```bash
$ ./vcpkg/bootstrap-vcpkg.sh 
Downloading vcpkg-glibc...
Segmentation fault
```

**Expected behavior**
vcpkg-glibc should be downloaded successfully.

**Failure logs**
`Segmentation fault`

**Comment by jimwang118** [comment]
You can try to clone a `vcpkg` again, then run the `./bootstrap-vcpkg.bat` command in the `vcpkg` directory and check the results.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
