### ISSUE TITLE
[ffmpeg] Build error

### ISSUE THREAD

**Issue by daijicheng** [microsoft/vcpkg#33719]
Package: ffmpeg[avcodec,avdevice,avfilter,avformat,core,swresample,swscale]:x64-windows -> 5.1.2#7

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.37.32822.0
-    vcpkg-tool version: 2023-08-09-9990a4c9026811a312cb2af78bf77f3d9d288416
    vcpkg-scripts version: 576f3f1ad 2023-08-14 (4 weeks ago)

**To Reproduce**

`vcpkg install Pangolin:x64-windows`
**Failure logs**

```
CMake Error at ports/ffmpeg/portfile.cmake:875 (message):
  Failed to identify license ()
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)
```

[build-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/12582686/build-x64-windows-dbg-err.log)
[build-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/12582688/build-x64-windows-dbg-out.log)

**Comment by JonLiu1993** [comment]
@daijicheng, please use `git pull` get the latest vcpkg and try again.
````
vcpkg-scripts version: https://github.com/microsoft/vcpkg/commit/576f3f1ad13bf2c3bd06520adfe41b69448cc033 2023-08-14 (4 weeks ago)
````

**Comment by daijicheng** [comment]
Thanks for your help. Due to time constraints, I used a simple and crude method to temporarily skip this problem.
I commented the relevant parts in portfile.cmake: 
```
# Handle copyright
# file(STRINGS "${CURRENT_BUILDTREES_DIR}/build-${TARGET_TRIPLET}-rel-out.log" LICENSE_STRING REGEX "License: .*" LIMIT_COUNT 1)
# if(LICENSE_STRING STREQUAL "License: LGPL version 2.1 or later")
#     set(LICENSE_FILE "COPYING.LGPLv2.1")
# elseif(LICENSE_STRING STREQUAL "License: LGPL version 3 or later")
#     set(LICENSE_FILE "COPYING.LGPLv3")
# elseif(LICENSE_STRING STREQUAL "License: GPL version 2 or later")
#     set(LICENSE_FILE "COPYING.GPLv2")
# elseif(LICENSE_STRING STREQUAL "License: GPL version 3 or later")
#     set(LICENSE_FILE "COPYING.GPLv3")
# elseif(LICENSE_STRING STREQUAL "License: nonfree and unredistributable")
#     set(LICENSE_FILE "COPYING.NONFREE")
#     file(WRITE "${SOURCE_PATH}/${LICENSE_FILE}" "${LICENSE_STRING}")
# else()
#     message(FATAL_ERROR "Failed to identify license (${LICENSE_STRING})")
# endif()

configure_file("${CMAKE_CURRENT_LIST_DIR}/FindFFMPEG.cmake.in" "${CURRENT_PACKAGES_DIR}/share/${PORT}/FindFFMPEG.cm
```
 I will try to upgrade vcpkg and try compiling again in the future.

**Comment by JonLiu1993** [comment]
@daiji Cheng, did you update your vcpkg and try again?

**Comment by JonLiu1993** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
