### ISSUE TITLE
Incomplete feature: No ability to set "--no-print-usage" when vcpkg triggered by CMake

### ISSUE THREAD

**Issue by gamagan** [microsoft/vcpkg#33717]
**Describe the bug**
This is not a bug, just an incomplete feature.
Issue #27040 added support for `--no-print-usage` in manifest mode. That's good. However, I have found no way to set that flag on when vcpkg is triggered via CMake.

In file `scripts/buildsystems/vcpkg.cmake`, there should be a chunk of code like this to support passing that flag from CMake to vcpkg.

```
    if(NOT Z_VCPKG_HAS_FATAL_ERROR)
        message(STATUS "Running vcpkg install")

        set(Z_VCPKG_ADDITIONAL_MANIFEST_PARAMS)

        # Add this additional if statement
        if(VCPKG_NO_PRINT_USAGE)
            list(APPEND Z_VCPKG_ADDITIONAL_MANIFEST_PARAMS "--no-print-usage")
        endif()
```

This will make it possible to have a non-verbose vcpkg by doing this on the main `CMakeLists.txt`:

```
# Must be set before call to 'project()'
set(VCPKG_NO_PRINT_USAGE ON) 

project(MyApp VERSION 0.1.0 LANGUAGES CXX)
```

**Environment**
- OS: Windows
- Compiler: MSVC 2022

**Comment by dg0yt** [comment]
Try [VCPKG_INSTALL_OPTIONS](https://learn.microsoft.com/en-us/vcpkg/users/buildsystems/cmake-integration#vcpkg_install_options).

**Comment by gamagan** [comment]
> Try [VCPKG_INSTALL_OPTIONS](https://learn.microsoft.com/en-us/vcpkg/users/buildsystems/cmake-integration#vcpkg_install_options).

I tried that, initially, but didn't seem the correct variable to do that. I thought that was for CMake install phase. Though, that was just a guess. But, if that's the correct variable to use, then I'd be happy to use that.

**Comment by FrankXie05** [comment]
>However, I have found no way to set that flag on when vcpkg is triggered via CMake.

This option `--no-print-usage` is a vcpkg command, and its scope is only in the vcpkg command line.

```
PS F:\usage\manifest\vcpkg> ./vcpkg install --triplet=x64-windows --no-print-usage
Detecting compiler hash for triplet x64-windows...
All requested packages are currently installed.
Total install time: 300 ns
PS F:\usage\manifest\vcpkg>
```

**Comment by autoantwort** [comment]
Replace `set(VCPKG_NO_PRINT_USAGE ON) ` with `set(VCPKG_INSTALL_OPTIONS --no-print-usage)` and you are done.

**Comment by FrankXie05** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can ping me with more info and I will reopen.
