### ISSUE TITLE
[tool] Consider passing -DD flag to unzip when unzipping binarycached artifacts

### ISSUE THREAD

**Issue by russelltg** [microsoft/vcpkg#33714]
**Describe the bug**

When vcpkg extracts the contents of a binary cache artifact, it also extracts the mtime of the files. This is problematic for many build systems that rely on comparing mtimes to see if an action needs to be re-ran, so if you install a vcpkg port that was compiled _before_
 the one that is currently installed, many build systems (ninja in my case) will _not_ re-run steps that need to be re-run.

For me, this is manifesting in issues with PCH's, as clang stores exact mtimes in .pch files, and ninja just checks if the header is newer than the pch file, so we end up with pch's not being recompiled properly because ninja thinks they are up to date. 

The solution here would be to extract without mtimes. On linux, this can be done with the `-DD` flag to unzip. On windows, this is tricker as 7zip is used, which I did some quick looking and I don't see an equivalent option. Of course this could be fixed by traversing the tree and manually touching all the files.

**Environment**
- OS: Linux, but should apply to all OS's

**To Reproduce**
1. Install a dependency
2. Build a project that has a PCH that uses that dependency
3. Install a different version of that dependency that was compiled *before* the previous one
4. Build that project again, PCH will not be rebuilt

**Expected behavior**
PCH will be rebuilt because mtime is set to current time, not build time

I'm happy to open a PR, maybe under an experimental feature?

**Comment by Adela0814** [comment]
Please feel free to submit the PR to [vcpkg-tool](https://github.com/microsoft/vcpkg-tool). We'd like that very much.

**Comment by krf** [comment]
Hey. I'm hitting the same issue also w/o binary cache. For verification I disabled both local + remote binary caches and then did try to use gtest as an example dependency:

* Install gtest in version 1.14 via vcpkg => Produces gtest.h with a timestamp set to **Aug 2 2023**
* Install gtest in version 1.16 via vcpkg => Produces gtest.h with a timestamp set to **Feb 7 2025**

Now toggling between those two dependency version will NOT trigger a rebuild of sources including gtest.h which leads to problems further down the road.

Checking the vcpkg ouput I see:
```
Building gtest[core,cxx17]:x64-linux-dynamic-release@1.16.0#1...
-- Cleaning sources at [snip]/vcpkg/buildtrees/gtest/src/v1.16.0-a2e0b328c1.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source [snip]/vcpkg/downloads/google-googletest-v1.16.0.tar.gz
-- Using source at [snip]/vcpkg/buildtrees/gtest/src/v1.16.0-a2e0b328c1.clean
...
```

Checking the source dir I see:
> -rw-r--r-- 1 [snip] [snip] 92521 **Feb  7  2025** [snip]/vcpkg/buildtrees/gtest/src/v1.16.0-a2e0b328c1.clean/googletest/include/gtest/gtest.h

=> So the mtime of the extracted source is used and ends up in the vcpkg_installed install tree.

Question: Shouldn't we also set mtime to current time during this extraction?

**Comment by touraill-adobe** [comment]
> Hey. I'm hitting the same issue also w/o binary cache.

I don't know if this was the same issue but I had the same symptoms because of the use of hard links (see https://github.com/microsoft/vcpkg-tool/issues/1899).
