### ISSUE TITLE
Building package boost-regex:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by smhcpk** [Microsoft/vcpkg#3373]
C:\vcpkg>vcpkg install cpprestsdk:x64-windows
The following packages will be built and installed:
  * boost-algorithm[core]:x64-windows
  * boost-asio[core]:x64-windows
  * boost-atomic[core]:x64-windows
  * boost-chrono[core]:x64-windows
  * boost-container[core]:x64-windows
  * boost-context[core]:x64-windows
  * boost-coroutine[core]:x64-windows
  * boost-date-time[core]:x64-windows
  * boost-exception[core]:x64-windows
  * boost-intrusive[core]:x64-windows
  * boost-io[core]:x64-windows
  * boost-lambda[core]:x64-windows
  * boost-lexical-cast[core]:x64-windows
  * boost-math[core]:x64-windows
  * boost-numeric-conversion[core]:x64-windows
  * boost-pool[core]:x64-windows
  * boost-range[core]:x64-windows
  * boost-ratio[core]:x64-windows
  * boost-rational[core]:x64-windows
  * boost-regex[core]:x64-windows
  * boost-system[core]:x64-windows
  * boost-thread[core]:x64-windows
  * boost-tokenizer[core]:x64-windows
  * boost-unordered[core]:x64-windows
  * boost-winapi[core]:x64-windows
    cpprestsdk[core]:x64-windows
  * websocketpp[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/27: boost-regex:x64-windows
Building package boost-regex[core]:x64-windows...
-- CURRENT_INSTALLED_DIR=C:/vcpkg/installed/x64-windows
-- DOWNLOADS=C:/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/vcpkg/packages/boost-regex_x64-windows
-- CURRENT_BUILDTREES_DIR=C:/vcpkg/buildtrees/boost-regex
-- CURRENT_PORT_DIR=C:/vcpkg/ports/boost-regex/.
-- Using cached C:/vcpkg/downloads/boostorg-regex-boost-1.67.0.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: C:/vcpkg/installed/x64-windows/tools/boost-build/b2.exe;--stagedir=C:/vcpkg/buildtrees/boost-regex/x64-windows-rel/stage;--build-dir=C:/vcpkg/buildtrees/boost-regex/x64-windows-rel;--user-config=C:/vcpkg/buildtrees/boost-regex/x64-windows-rel/user-config.jam;-j4;--debug-configuration;--debug-building;--debug-generators;--disable-icu;--ignore-site-config;--hash;-q;-sZLIB_INCLUDE="C:/vcpkg/installed/x64-windows/include";-sBZIP2_INCLUDE="C:/vcpkg/installed/x64-windows/include";threading=multi;threadapi=win32;runtime-link=shared;link=shared;address-model=64;architecture=x86;toolset=msvc-14.1;-sZLIB_BINARY=zlib;-sZLIB_LIBPATH="C:/vcpkg/installed/x64-windows/lib";-sBZIP2_BINARY=bz2;-sBZIP2_LIBPATH="C:/vcpkg/installed/x64-windows/lib";variant=release;debug-symbols=on
    Working Directory: C:/vcpkg/buildtrees/boost-regex/src/ost-1.67.0-d36604157f/build
    See logs for more information:
      C:\vcpkg\buildtrees\boost-regex\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:231 (vcpkg_execute_required_process)
  ports/boost-regex/portfile.cmake:20 (boost_modular_build)
  scripts/ports.cmake:72 (include)

Error: Building package boost-regex:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-regex:x64-windows
  Vcpkg version: 0.0.110-2018-04-28-a9d989ec056246ea320a56ca7d02b161a6fee387

Additionally, attach any relevant sections from the log files above.

**Comment by jasonhung-work** [comment]
I have the same question and this is the log
[build-x86-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/2344248/build-x86-windows-rel-out.log)

**Comment by 478161648** [comment]
Have you solved this problem?

**Comment by NancyLi1013** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
