### ISSUE TITLE
[BUILD_FAILED] libsodium:x86-windows-static

### ISSUE THREAD

**Issue by Convery** [Microsoft/vcpkg#3374]
Do note: only the x86-windows-static triplet fails to build. x86-windows, x64-windows, and x64-windows-static all works.

* Library-version: `libsodium 1.0.16-60968e7afa`
* System: `Windows 7 Ultimate x64 SP1, en-gb locale, 96Gb DDR3 1333, 2x E5-2660v2 (10c + HT, 32Kb, 256Kb, 25Mb)`
* Relevant part: `1>LINK : warning LNK4068: /MACHINE not specified; defaulting to X64 [...] fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64'`

[cmd.log](https://github.com/Microsoft/vcpkg/files/1958529/cmd.log)
[build-x86-windows-static-rel-out.log](https://github.com/Microsoft/vcpkg/files/1958530/build-x86-windows-static-rel-out.log)

**Comment by dwcullop** [comment]
I'm having the exact same issue.  3 out of 4 build properly for `libsodium` but `x86-windows-static` fails in exactly the same way.  I tried cloning the VcPkg repo again, rebuilding, and I get exactly the same problem.

[build-x86-windows-static-rel-out.log](https://github.com/Microsoft/vcpkg/files/2669256/build-x86-windows-static-rel-out.log)

@Convery  You posted this issue over 7 months ago.  Were you able to find a solution or a workaround?

**Comment by Convery** [comment]
Didn't investigate a proper solution, I simply opened the generated vcxproj file (/buildtrees/libsodium/src/*/) in visual studio and hit compile. It defaulted to x86 for the machine-type.

> `1>LINK : warning LNK4068: /MACHINE not specified; defaulting to X86`

**Comment by myd7349** [comment]
https://github.com/Microsoft/vcpkg/issues/3385

**Comment by myd7349** [comment]
@dwcullop @Convery I figured out a solution. Would you like to give it a try?
