### ISSUE TITLE
[opencv] DNN feature not installed in UWP

### ISSUE THREAD

**Issue by antoine-fresse** [microsoft/vcpkg#33742]
### Is your feature request related to a problem? Please describe.

When targeting UWP, the DNN feature (which is a default feature) is supposedly available but is not actually installed (header/lib is not present). There is no error or warning indicating the feature is not supported . It works fine when targeting regular win x64

### Proposed solution

Fix installation of missing features in UWP or mark them unsupported

### Additional context

![image](https://github.com/microsoft/vcpkg/assets/5739266/c30b4214-fea2-4c98-a0fb-72e0db59941c)

Comparison of x64-uwp vs x64-windows vcpkg_installed include folder after installation

**Comment by JonLiu1993** [comment]
@antoine-fresse, Thanks for posting this issue, opencv is now an empty port, it has been ported to opencv4, please use the command `./vcpkg install opencv4[dnn]:x64-uwp` to use.

**Comment by MBSpie** [comment]
Hello, I am having the same issue here. 

After trying the advised solution by JonLiu, I get the message that opencv4:x64-uwp is already installed but I still don't find any mention of the "dnn" features under the include directory of opencv2. However, he is present under the "buildtrees" folder and there is mention of it in the "download" folder as well.

![image](https://github.com/microsoft/vcpkg/assets/104350832/908b48af-a380-4f54-80cb-7b54d9c2359b)
