### ISSUE TITLE
[miniz] CMake configuring error

### ISSUE THREAD

**Issue by SNMetamorph** [microsoft/vcpkg#33745]
### Operating system

Windows (host triplet x64-windows)

### Compiler

MSVC

### Steps to reproduce the behavior
Just add `miniz` to dependencies in vcpkg.json. Next, select `x86-windows-static` as target triplet.

### Failure logs
```
[CMake] CMake Error at external/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package):
[CMake]   Could not find a configuration file for package "miniz" that is compatible
[CMake]   with requested version "".
[CMake] 
[CMake]   The following configuration files were considered but not accepted:
[CMake] 
[CMake]     G:/Projects/abc/build/vcpkg_installed/x86-windows-static/share/miniz/minizConfig.cmake, version: 3.0.2 (32bit)
[CMake] 
[CMake] Call Stack (most recent call first):
[CMake]   utils/common/imagelib/CMakeLists.txt:76 (find_package)
[CMake] -- Configuring incomplete, errors occurred!
```
### Additional context

This error doesn't happens with `x64-windows-static` target triplet. Same with linux triplets too.

**Comment by dg0yt** [comment]
AFAIU the error message indicates that you are actually building a 64 bit configuration which of course rejects 32 bit packages. Did you try from a clean directory, to not stumble over CMake cache variables?

**Comment by SNMetamorph** [comment]
Sorry for inconvenience, it was some very strange problem on my side and it's gone now.
