### ISSUE TITLE
[poppler] Unable to generate images for Chinese invoices due to not adding a popper data dependency

### ISSUE THREAD

**Issue by heweisheng** [microsoft/vcpkg#33756]
### Is your feature request related to a problem? Please describe.

Unable to generate images for Chinese invoices due to not adding a popper data dependency
由于没有添加poppler-data依赖导致中文的发票无法生成图片

### Proposed solution

Add this dependency project (I tried to write a port patch, but there were many warnings and I didn't quite understand)
添加一下这个依赖项目（我尝试写了个port补丁，但是好多警告，不太明白）
https://poppler.freedesktop.org/poppler-data-0.4.12.tar.gz

### Describe alternatives you've considered

我尝试过自己写port 应该是可行的，也试过添加一个依赖路径
![image](https://github.com/microsoft/vcpkg/assets/37769332/91b8b50a-b5d2-447f-a075-bcd38d1c8f58)
![image](https://github.com/microsoft/vcpkg/assets/37769332/5eaae2a7-5301-4484-8b0b-ccad1d57bc1d)

**Comment by JonLiu1993** [comment]
@heweisheng, thanks for posting this issue, can you submit a PR? We can then review your changes and give you some suggestions.

**Comment by heweisheng** [comment]
> @heweisheng, thanks for posting this issue, can you submit a PR? We can then review your changes and give you some suggestions.

let me try

**Comment by dg0yt** [comment]
FTR: 
What is needed is providing the data (maybe a port), and *user code* providing the location of the data to the poppler lib.
What isn't needed is adding a dependency to poppler, and hardcoding a non-relocatable data location.

**Comment by heweisheng** [comment]
I use poppler::set_data_dir because the data can't be added by binaray（library）
