### ISSUE TITLE
[opentelemetry-cpp] update to 1.11.0

### ISSUE THREAD

**Issue by willie** [microsoft/vcpkg#33772]
### Library name

opentelemetry-cpp

### New version number

1.11.0

### Other information that may be useful (release notes, etc...)

vcpkg has 1.9.1, which is 2 releases behind.

https://github.com/open-telemetry/opentelemetry-cpp/releases/tag/v1.11.0

**Comment by PriitUring** [comment]
Title has typo: `opentelemtery-cpp`, correct would be `opentelemetry-cpp`?
