### ISSUE TITLE
separate LLVM and Clang ports

### ISSUE THREAD

**Issue by navidR** [microsoft/vcpkg#3377]
The overhead of building clang is way more than building simple LLVM. It does not make sense at all to have clang as part of LLVM. At least there should be an option to tell VCPKG to only build LLVM.  

When you have a port named LLVM it should be LLVM, not LLVM/Clang. You can have another package named Clang or you can add config to LLVM package to compile it with Clang.
Whose idea was that? Seriously?

**Comment by TheAifam5** [comment]
Actually I working on LLVM port, check it out here: https://github.com/Microsoft/vcpkg/pull/3987
It's highly customizable so you can install what you really want.

**Comment by degski** [comment]
@TheAifam5 

Am I right in understanding that the objective is to compile Clang (and LLVM) with VS15/17?

**Comment by TheAifam5** [comment]
@degski not only clang but everything from LLVM.

**Comment by ras0219-msft** [comment]
Currently, clang can't be built separate from LLVM (as I understand it); this is why there needs to be a single port. As for why it's named LLVM: it was originally only the llvm backened and clang was added later -- to avoid disruption, it seemed inappropriate to rename it.

If I'm correct that clang can't be built separately, then it seems like it would be best to move it into a "feature" like `llvm[clang]`.

**Comment by TheAifam5** [comment]
@ras0219-msft yup, that's correct. That's also why I making a PR https://github.com/Microsoft/vcpkg/pull/3987 :)

**Comment by degski** [comment]
@TheAifam5 

I fail to see though, why it would be a good idea to build clang/llvm with vc. IMHE. vc over the board produces inferior code [sometimes dramatically so, but definitely not always] as compared to clang (on native windows I'm talking). So the only use I see is to build clang with vc and than use the built clang to built clang properly thereafter. It seems simpler to grab a copy from the llvm web-site. The clang-team guarantees that trunk can always be built by stable.

**Comment by TheAifam5** [comment]
@degaki just for simple compilation the package from LLVM website is enough but the package does contains only limited clang-c or llvm-c headers so it’s not useful if you want do integrate the LLVM in your application or build something on top of it.

**Comment by MathiasMagnus** [comment]
Should you do a revamp of the LLVM package, could you also fix #4277? :)

**Comment by shrinktofit** [comment]
Any move on this?
