### ISSUE TITLE
--vcpkg-root does not work with subcommands

### ISSUE THREAD

**Issue by anordal** [microsoft/vcpkg#3378]
E.g, the *list* subcommand:

```
> vcpkg --vcpkg-root=$HOME/.cache/vcpkg list
Unknown option(s) for command 'list':
    --vcpkg-root

The argument should be a substring to search for, or no argument to display all installed libraries.
Example:
  vcpkg list png

Options:
    --x-full-desc                            Do not truncate long text
    --triplet <t>                            Set the default triplet for unqualified packages
    --vcpkg-root <path>                      Specify the vcpkg directory to use instead of current directory or tool directory
```

The VCPKG_ROOT environment variable seems to be a workable alternative. Just letting you know.

Reason for wanting to use this option: I'm exploring possible ways to package vcpkg as a linux distribution package. Obviously, the binary would go in /usr/bin/, and user-writable files somewhere else. Given that vcpkg doesn't work like this by default, I think a common approach would be to wrap it in a command that does:

```bash
#!/bin/bash
set -eu

if ! [[ -v XDG_CACHE_HOME ]]; then
    XDG_CACHE_HOME="$HOME"/.cache
fi
VCPKG_ROOT="$XDG_CACHE_HOME"/vcpkg

if test "$1" = --get-vcpkg-root; then
    echo "$VCPKG_ROOT"
else
    #BUG vcpkg:3378 exec vcpkg-bin --vcpkg-root="$VCPKG_ROOT" "$@"
    export VCPKG_ROOT
    exec vcpkg-bin "$@"
fi
```

**Comment by ras0219-msft** [comment]
Thanks for reporting this!

This is definitely a feature gap in the parser, however it should work if you use a space instead of equals. The "vcpkg-root" option is handled by a different parser than the rest of the "single argument" options and doesn't handle =

**Comment by martin-s** [comment]
I would always go with the argument approach, as environment variables can have side effects when they are used in different vcpkg instances. Hence, keep it as local as possible.

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen this issue.
