### ISSUE TITLE
OpenSSL Alpine docker build failure

### ISSUE THREAD

**Issue by AFOEK** [microsoft/vcpkg#33806]
### Operating system

Alpine Linux Docker

### Steps to reproduce the behavior

```Shell
alpine:latest
LABEL Description="WSGCC build env"

RUN apk update && apk upgrade && \
    apk add build-base ninja git cmake make curl zip tar unzip linux-headers perl pkgconfig && \
    cd ~ && \
    git clone https://github.com/Microsoft/vcpkg.git && cd vcpkg && \
    export VCPKG_FORCE_SYSTEM_BINARIES=1 && \
    ./bootstrap-vcpkg.sh && \
    ./vcpkg install cpr gumbo curl indicators argparse termcolor
```

### Failure logs

1135.4 Installing 5/11 openssl:x64-linux...
1135.4 Building openssl:x64-linux...
1135.4 -- Downloading https://github.com/openssl/openssl/archive/openssl-3.1.2.tar.gz -> openssl-openssl-openssl-3.1.2.tar.gz...
1193.2 -- Extracting source /root/vcpkg/downloads/openssl-openssl-openssl-3.1.2.tar.gz
1193.6 -- Applying patch arm64-asm.patch
1193.6 -- Applying patch disable-apps.patch
1193.6 -- Applying patch disable-install-docs.patch
1193.6 -- Applying patch script-prefix.patch
1193.6 -- Applying patch windows/install-layout.patch
1193.6 -- Applying patch windows/install-pdbs.patch
1193.6 -- Applying patch windows/perlasm-scheme.patch
1193.6 -- Applying patch unix/android-cc.patch
1193.6 -- Applying patch unix/move-openssldir.patch
1193.6 -- Applying patch unix/no-empty-dirs.patch
1193.6 -- Applying patch unix/no-static-libs-for-shared.patch
1193.6 -- Using source at /root/vcpkg/buildtrees/openssl/src/nssl-3.1.2-a1adf9ea87.clean
1193.6 openssl requires Linux kernel headers from the system package manager.
1193.6    They can be installed on Alpine systems via `apk add linux-headers`.
1193.6    They can be installed on Ubuntu systems via `apt install linux-libc-dev`.
1193.6 
1193.7 -- Getting CMake variables for x64-linux
1197.5 -- Getting CMake variables for x64-linux-dbg
1198.0 -- Getting CMake variables for x64-linux-rel
1198.3 CMake Error at scripts/cmake/vcpkg_configure_make.cmake:276 (find_program):
1198.3   Could not find base_cmd using the following names: bash
1198.3 Call Stack (most recent call first):
1198.3   ports/openssl/unix/portfile.cmake:104 (vcpkg_configure_make)
1198.3   ports/openssl/portfile.cmake:73 (include)
1198.3   scripts/ports.cmake:147 (include)
1198.3 
1198.3 
1198.3 error: building openssl:x64-linux failed with: BUILD_FAILED
1198.3 Elapsed time to handle openssl:x64-linux: 1 min
1198.3 Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
1198.3 Then check for known issues at:
1198.3     https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
1198.3 You can submit a new issue at:
1198.3     https://github.com/microsoft/vcpkg/issues/new?title=[openssl]+Build+error&body=Copy+issue+body+from+%2Froot%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
1198.3 

### Additional context

I tried to install package for my docker image but when it arrived building `OpenSSL`, it just give error.

**Comment by dg0yt** [comment]
> 1198.3 CMake Error at scripts/cmake/vcpkg_configure_make.cmake:276 (find_program):
> 1198.3 Could not find base_cmd using the following names: bash

Maybe you should install `bash`?

**Comment by AFOEK** [comment]
huh strange after I install it success. Thanks, last time when I build it isn't required `bash`.
