### ISSUE TITLE
[odb-sqlite] link failure

### ISSUE THREAD

**Issue by eyouyou** [microsoft/vcpkg#33805]
### Operating system

Windows/DEBIAN

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
`cmake -S . -B build -D CMAKE_TOOLCHAIN_FILE=D:\Code\vcpkg\scripts\buildsystems\vcpkg.cmake`
```

### Failure logs

1> [CMake] CMake Error at D:\Code\XXX\CMakeLists.txt:25 (target_link_libraries):

1> [CMake]   Target "XXX" links to:

1> [CMake] 

1> [CMake]     odb::libodb-sqlite

1> [CMake] 

1> [CMake]   but the target was not found.  Possible reasons include:

1> [CMake] 

1> [CMake]     * There is a typo in the target name.

1> [CMake]     * A find_package call is missing for an IMPORTED target.

1> [CMake]     * An ALIAS target is missing.

1> [CMake] 

1> [CMake] 

1> [CMake] 

### Additional context
odb stable 2.4.0
find_package(odb CONFIG REQUIRED)
target_link_libraries(XXX PRIVATE odb::libodb-sqlite)

**Comment by dg0yt** [comment]
AFAICS you need to be  more explicit to get this target:
~~~cmake
find_package(odb CONFIG REQUIRED COMPONENTS sqlite)

**Comment by eyouyou** [comment]
Thanks for solving my problem
