### ISSUE TITLE
libsodium x64-linux build failed on ubuntu 17.10:  Could not find Windows SDK

### ISSUE THREAD

**Issue by mattw-mega** [microsoft/vcpkg#3382]
fresh 64 bit ubuntu 17.10 in a virtualbox (under dell xps laptop running windows) (plus apt installed git, g++ etc)
used git to fetch vcpkg, built it with the bootstrap script

tried to build libsodium with: ./vcpkg install --triplet x64-linux libsodium

it reports error:

CMake Error at scripts/cmake/vcpkg_get_windows_sdk.cmake:10 (message): 
   Could not find Windows SDK

**Comment by pravic** [comment]
It's nt surprising: https://github.com/Microsoft/vcpkg/blob/e629afa182b146e9d1df79e939759af68a555289/ports/libsodium/portfile.cmake#L25

**Comment by fhajji** [comment]
My very ugly fix as vcpkg beginner:

[patch-libsodium-portfile.cmake.txt](https://github.com/Microsoft/vcpkg/files/2412633/patch-libsodium-portfile.cmake.txt)

**Comment by Rastaban** [comment]
It looks like this issue is fixed now.
