### ISSUE TITLE
 vcpkg/docs/about/faq.md is out of date

### ISSUE THREAD

**Issue by gclarkii** [Microsoft/vcpkg#3383]
Hi,

The file vcpkg/docs/about/faq.md is out of date.  You may want to update it to show support for Linux and MacOS.

**Comment by Cheney-W** [comment]
Thanks for pointing that out! 
This file has been updated by Robert's [commit](https://github.com/Microsoft/vcpkg/commit/2988f8577b8ee3e977c187401af544e9eae4ff7b#diff-fb47a447d16b1ba29ba890608c0f1308). So close this issue.
