### ISSUE TITLE
[harfbuzz] Build error

### ISSUE THREAD

**Issue by shukla226** [microsoft/vcpkg#33839]
error while installing :   **harfbuzz:x64-windows -> 8.2.0**
.
.
.
.
.
.
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" install -v
    Working Directory: C:/Users/vs/github/vcpkg/buildtrees/harfbuzz/x64-windows-dbg
    Error code: 1
    See logs for more information:
      C:\Users\vs\github\vcpkg\buildtrees\harfbuzz\package-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
  ports/harfbuzz/portfile.cmake:73 (vcpkg_install_meson)
  scripts/ports.cmake:147 (include)

**error: building harfbuzz:x64-windows failed with: BUILD_FAILED**

**Comment by autoantwort** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report an issue.

**Comment by shukla226** [comment]
Package: harfbuzz:x64-windows -> 8.2.0

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.28.29915.0
-    vcpkg-tool version: 2023-08-09-9990a4c9026811a312cb2af78bf77f3d9d288416
    vcpkg-scripts version: e8c2a04eb 2023-09-15 (3 days ago)

**To Reproduce**

`vcpkg install harfbuzz:x64-windows`
**Failure logs**

```
-- Using cached harfbuzz-harfbuzz-8.2.0.tar.gz.
-- Cleaning sources at C:/Users/vinayak.shukla/github/vcpkg/buildtrees/harfbuzz/src/8.2.0-52a1211f23.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/vinayak.shukla/github/vcpkg/downloads/harfbuzz-harfbuzz-8.2.0.tar.gz
-- Using source at C:/Users/vinayak.shukla/github/vcpkg/buildtrees/harfbuzz/src/8.2.0-52a1211f23.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows
-- Configuring x64-windows-dbg
-- Using cached mingw-w64-i686-pkgconf-1~1.8.0-2-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using msys root at C:/Users/vinayak.shukla/github/vcpkg/downloads/tools/msys2/6f3fa1a12ef85a6f
-- Configuring x64-windows-dbg done
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Package x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" install -v
    Working Directory: C:/Users/vinayak.shukla/github/vcpkg/buildtrees/harfbuzz/x64-windows-dbg
    Error code: 1
    See logs for more information:
      C:\Users\vinayak.shukla\github\vcpkg\buildtrees\harfbuzz\package-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
  ports/harfbuzz/portfile.cmake:73 (vcpkg_install_meson)
  scripts/ports.cmake:147 (include)

**Comment by LilyWangLL** [comment]
Please provide the error log: `C:\Users\vinayak.shukla\github\vcpkg\buildtrees\harfbuzz\package-x64-windows-dbg-out.log`.

**Comment by shukla226** [comment]
[package-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/12679709/package-x64-windows-dbg-out.log)

**Comment by LilyWangLL** [comment]
Duplicate issue: https://github.com/microsoft/vcpkg/issues/26202

**Comment by LilyWangLL** [comment]
But I cannot repro this issue both on Visual Studio 2019 and Visual Studio 2022.

**Comment by LilyWangLL** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
