### ISSUE TITLE
vcpkg crashes when installing curl with openssl (only) in manifest mode

### ISSUE THREAD

**Issue by igorsnunes** [microsoft/vcpkg#33845]
**Describe the bug**
vcpkg crashes when installing curl 
**Environment**
WSL environment.
```
Distributor ID: Ubuntu
Description: Ubuntu 20.04.3 LTS
Release: 20.04
Codename: focal

```
`Linux <machine name> 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

Vcpkg is checked out on e8c2a04eb7ca058b6e2f0e6e33c67fdbffeee846.

**To Reproduce**

1. Create an empty directory.
2. Write a vcpkj.json with the following content:

```
 {
     "name": "new-proj",
     "version": "0",
     "dependencies":
     [
         {
                 "name":"curl",
                 "features": ["core","openssl"]
         }
     ],
     "overrides":
     [
             { "name":"curl", "version":"8.1.2" }
     ]
 }
```

3. execute "vcpkg install"

**Expected behavior**
Vcpkg should not crash.

**Failure logs**
The following message is logged:

`internal error: /mnt/vss/_work/1/s/include/vcpkg/sourceparagraph.h(51): vcpkg has crashed; no additional details are available.`

**Comment by FrankXie05** [comment]
@igorsnunes Could you please provide the complete error message? :)
I think this is because the vcpkg baseline you downloaded does not have a `curl` version(`8.1.2`). It is recommended that you use the latest `curl` version(`8.2.1`).

**Comment by dg0yt** [comment]
Note that a feature named "core" doesn't exist. You can use it at the command line, but in manifests, you have to use `"default-features": false"`.

**Comment by igorsnunes** [comment]
Hi @dg0yt ,
Thanks, that solves my problem. The crash is still there though, so feel free to close this issue and track the crash on a different issue if needed.

**Comment by FrankXie05** [comment]
@igorsnunes Could you please re-run the script `bootstrap-vcpkg.bat` and try again? :)

**Comment by igorsnunes** [comment]
@FrankXie05 , I ran bootstrap-vcpkg.sh (not bootstrap-vcpkg.bat) again and the crash is still happening.

**Comment by dg0yt** [comment]
If you don't move your vcpkg checkout to a new state (`git pull`), bootstrap won't download a new version of the tool. Your posts don't show any version information.

**Comment by igorsnunes** [comment]
@dg0yt , I removed and cloned a new vcpkg on my environment, now pointing to be2d7f886aad895e282b59088a2dfca5f6e1c88a.

Here is vcpkg version string:

```
./vcpkg --version
vcpkg package management program version 2023-09-15-ac02a9f660977426b8ec6392919fbb1d51b10998

See LICENSE.txt for license information.
```
The problem still persists on this state.

**Comment by dg0yt** [comment]
If you refer to the crash from the invalid feature name: It is tracked in https://github.com/microsoft/vcpkg/issues/33973.

**Comment by BillyONeal** [comment]
@igorsnunes Can you try 2023-10-18 we just released?

**Comment by igorsnunes** [comment]
@BillyONeal , I tested again and it does seem fixed:

```
~/vcpkg/vcpkg  install
error: while loading /home/myhome/empty_proj/vcpkg.json:
$.dependencies[0].features[0] (a feature name): the feature "core" cannot be in a dependency's feature list. To turn off default features, add "default-features": false instead.

Extended documentation available at 'https://learn.microsoft.com/vcpkg/users/manifests'.

```
Instead of crashing, now an error is printed out pointing me to the right direction.

Thanks!
