### ISSUE TITLE
Boost.context missing .asm files in vcpkg.

### ISSUE THREAD

**Issue by yyzybb537** [Microsoft/vcpkg#3384]
The boost.context library, build without "asm files" in vcpkg,
So, I can't find 'make_fcontext', 'jump_fcontext', 'onto_fcontext' symbols in `libboost_context.a`

When I use boost.context, linker tell me some errors likes `undefined reference to `make_fcontext'`

**Comment by KindDragon** [comment]
I can confirm. Ubuntu 16.04.4 LTS.
I can't build folly because of that
[install-x64-linux-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2004088/install-x64-linux-dbg-out.log)

**Comment by ras0219-msft** [comment]
I have a fix prepared; we're testing it to ensure no regressions elsewhere and then we'll be merging it to master!

**Comment by ras0219-msft** [comment]
This should now be fixed on master. Please let us know if you still encounter this after upgrading!

**Comment by yyzybb537** [comment]
It's not fixed!

**Comment by KindDragon** [comment]
Issue fixed for me

**Comment by yyzybb537** [comment]
Yes, it's fixed, thank you!
