### ISSUE TITLE
[qt5-base] Build error

### ISSUE THREAD

**Issue by stodar** [microsoft/vcpkg#33849]
Detecting compiler hash for triplet x64-linux...
Detecting compiler hash for triplet arm64-android...
The following packages will be built and installed:
  * anyrpc[core]:arm64-android -> 2020-01-13#2 -- /home/saad/Bureau/QField/vcpkg/overlay/anyrpc
  * exiv2[core,xmp]:arm64-android -> 0.27.5#1 -- /home/saad/Bureau/QField/vcpkg/overlay/exiv2
  * freeglut[core]:arm64-android -> 3.4.0
  * gsl[core]:arm64-android -> 2.7.1#1
  * jasper[core,default-features,opengl]:arm64-android -> 4.0.0#1
  * libspatialindex[core]:arm64-android -> 1.9.3#3
  * libzip[bzip2,core,default-aes,openssl]:arm64-android -> 1.9.2#1
  * poly2tri[core]:arm64-android -> 2022-08-11 -- /home/saad/Bureau/QField/vcpkg/overlay/poly2tri
  * protobuf[core]:arm64-android -> 3.21.12
  * protobuf[core]:x64-linux -> 3.21.12
    qca[core]:arm64-android -> 2.3.4#2 -- /home/saad/Bureau/QField/vcpkg/overlay/qca
    qgis[core]:arm64-android -> current -- /home/saad/Bureau/QField/vcpkg/overlay/qgis
  * qt5-base[core]:arm64-android -> 5.15.8#5
    qt5-charts[core]:arm64-android -> 5.15.8
    qt5-connectivity[core]:arm64-android -> 5.15.8
    qt5-declarative[core]:arm64-android -> 5.15.8
  * qt5-graphicaleffects[core]:arm64-android -> 5.15.8
  * qt5-imageformats[core]:arm64-android -> 5.15.8#1
    qt5-location[core]:arm64-android -> 5.15.8
    qt5-multimedia[core]:arm64-android -> 5.15.8
  * qt5-quickcontrols[core]:arm64-android -> 5.15.8
    qt5-quickcontrols2[core]:arm64-android -> 5.15.8
    qt5-sensors[core]:arm64-android -> 5.15.8
    qt5-serialport[core]:arm64-android -> 5.15.8
  * qt5-svg[core]:arm64-android -> 5.15.8
  * qt5-tools[core]:arm64-android -> 5.15.8
    qt5-webview[core]:arm64-android -> 5.15.8
  * qtkeychain[core,translations]:arm64-android -> 0.13.2#1 -- /home/saad/Bureau/QField/vcpkg/overlay/qtkeychain
    spix[core]:arm64-android -> dev -- /home/saad/Bureau/QField/vcpkg/overlay/spix
Additional packages (*) will be modified to complete this operation.
Restored 0 package(s) from /home/saad/.cache/vcpkg/archives in 174 us. Use --debug to see more details.
Installing 1/29 qt5-base:arm64-android...
Building qt5-base[core]:arm64-android...
-- [OVERLAY] Loading triplet configuration from: /home/saad/Bureau/QField/vcpkg/triplets/arm64-android.cmake
-- Figuring out qt target mkspec. Target arch arm64
-- Target mkspec set to: 
-- Host mkspec not set. Qt's own buildsystem will try to figure out the host system
-- Using cached qtbase-everywhere-opensource-src-5-29e8877b.15.8.tar.xz.
-- Cleaning sources at /home/saad/Bureau/build/_deps/vcpkg-src/buildtrees/qt5-base/src/5.15.8-eca47ce012.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/saad/Bureau/build/_deps/vcpkg-src/downloads/qtbase-everywhere-opensource-src-5-29e8877b.15.8.tar.xz
-- Applying patch patches/winmain_pro.patch
-- Applying patch patches/windows_prf.patch
-- Applying patch patches/qt_app.patch
-- Applying patch patches/gui_configure.patch
-- Applying patch patches/xlib.patch
-- Applying patch patches/egl.patch
-- Applying patch patches/mysql_plugin_include.patch
-- Applying patch patches/mysql-configure.patch
-- Applying patch patches/cocoa.patch
-- Applying patch patches/Qt5BasicConfig.patch
-- Applying patch patches/Qt5PluginTarget.patch
-- Applying patch patches/create_cmake.patch
-- Applying patch patches/Qt5GuiConfigExtras.patch
-- Applying patch patches/fix_angle.patch
-- Applying patch patches/mingw9.patch
-- Using source at /home/saad/Bureau/build/_deps/vcpkg-src/buildtrees/qt5-base/src/5.15.8-eca47ce012.clean
CMake Error at ports/qt5-base/cmake/configure_qt.cmake:5 (message):
  configure_qt requires a TARGET_PLATFORM argument.
Call Stack (most recent call first):
  ports/qt5-base/portfile.cmake:376 (configure_qt)
  scripts/ports.cmake:147 (include)

error: building qt5-base:arm64-android failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qt5-base
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[qt5-base]+Build+error&body=Copy+issue+body+from+%2Fhome%2Fsaad%2FBureau%2Fbuild%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md

**Comment by dg0yt** [comment]
Qt5 cross builds don't work in vcpkg. (Except for limited cases...)

**Comment by stodar** [comment]
> Qt5 cross builds don't work in vcpkg. (Except for limited cases...)

it's the CMake script already present in Qfield that tries to install it via this method, is there a solution?

**Comment by stodar** [comment]
it's the CMake script already present in Qfield that tries to install it via this method, is there a solution?

**Comment by stodar** [comment]
> Qt5 cross builds don't work in vcpkg. (Except for limited cases...)

How to solve this problem ?!

**Comment by MonicaLiu0311** [comment]
> > Qt5 cross builds don't work in vcpkg. (Except for limited cases...)
> 
> How to solve this problem ?!


Currently in vcpkg, `qt5-base` is not supported on `arm64-android`： [ci.baseline.txt#L995](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt#L995)
