### ISSUE TITLE
libsodium for x86-windows-static fails with "module machine type 'x86' conflicts with target machine type 'x64'"

### ISSUE THREAD

**Issue by mattw-mega** [Microsoft/vcpkg#3385]
Package: libsodium:x86-windows-static
  Vcpkg version: 0.0.110-2018-04-28-a9d989ec056246ea320a56ca7d02b161a6fee387

-- Building C:/Users/MATTW/source/repos/3rdparty/vcpkg/buildtrees/libsodium/src/1.0.16-60968e7afa/libsodium.vcxproj for Release
CMake Error at repos/3rdparty/vcpkg/scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: msbuild;C:/Users/MATTW/source/repos/3rdparty/vcpkg/buildtrees/libsodium/src/1.0.16-60968e7afa/libsodium.vcxproj;/p:Configuration=Release;/t:Rebuild;/p:Platform=x86;/p:PlatformToolset=v141;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No;/p:WindowsTargetPlatformVersion=10.0.16299.0;/m;/p:WholeProgramOptimization=false
    Working Directory: C:/Users/MATTW/source/repos/3rdparty/vcpkg/buildtrees/libsodium/x86-windows-static-rel
    See logs for more information:
      C:\Users\MATTW\source\repos\3rdparty\vcpkg\buildtrees\libsodium\build-x86-windows-static-rel-out.log

     1>LINK : warning LNK4068: /MACHINE not specified; defaulting to X64 [C:\Users\MATTW\source\repos\3rdparty\vcpkg\buildtrees\libsodium\src\1.0.16-60968e7afa\libsodium.vcxproj]
     1>C:\Users\MATTW\source\repos\3rdparty\vcpkg\buildtrees\libsodium\src\1.0.16-60968e7afa\Build\Release\Win32\Intermediate\crypto_generichash.obj : fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64' [C:\Users\MATTW\source\repos\3rdparty\vcpkg\buildtrees\libsodium\src\1.0.16-60968e7afa\libsodium.vcxproj]
     1>Done Building Project "C:\Users\MATTW\source\repos\3rdparty\vcpkg\buildtrees\libsodium\src\1.0.16-60968e7afa\libsodium.vcxproj" (Rebuild target(s)) -- FAILED.

**Comment by notcdk** [comment]
Temporary solution
[libsodium-vcxproj.zip](https://github.com/Microsoft/vcpkg/files/1971237/libsodium-vcxproj.zip)
replace your vcxproj with this one in vcpkg\buildtrees\libsodium\src\1.0.16...
https://i.imgur.com/1Empbnw.png

**Comment by Cheney-W** [comment]
This issue has been fixed by PR: https://github.com/Microsoft/vcpkg/pull/5003, so close it.
