### ISSUE TITLE
[qt] build failure

### ISSUE THREAD

**Issue by savahmel** [microsoft/vcpkg#33891]
### Operating system

Windows 10

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
vcpkg install qt:x64-windows --x-buildtrees-root=short path
```

### Failure logs

Downloading https://gitlab.gnome.org//GNOME/libxml2/-/archive/v2.11.5/libxml2-v2.11.5.tar.gz
error: Failed to download from mirror set
error: https://gitlab.gnome.org//GNOME/libxml2/-/archive/v2.11.5/libxml2-v2.11.5.tar.gz: failed: status code 503

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_gitlab.cmake:118 (vcpkg_download_distfile)
  ports/libxml2/portfile.cmake:1 (vcpkg_from_gitlab)
  scripts/ports.cmake:147 (include)

**Comment by Neumann-A** [comment]
https://gitlab.gnome.org/ seems to be down.

**Comment by LeenHawk** [comment]
Work now.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This issue has been fixed, so I am closing this issue for now.
