### ISSUE TITLE
[libxml2] build failure

### ISSUE THREAD

**Issue by luodiweiyu** [microsoft/vcpkg#33894]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
.\vcpkg.exe install libxml2:x64-windows
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
    libxml2[core,iconv,lzma,zlib]:x64-windows -> 2.11.5#1
Detecting compiler hash for triplet x64-windows...
-- Automatically setting %HTTP(S)_PROXY% environment variables to "127.0.0.1:11285".
Restored 0 package(s) from C:\Users\ChenJ\AppData\Local\vcpkg\archives in 97 us. Use --debug to see more details.
Installing 1/1 libxml2:x64-windows...
Building libxml2[core,iconv,lzma,zlib]:x64-windows...
-- Downloading https://gitlab.gnome.org//GNOME/libxml2/-/archive/v2.11.5/libxml2-v2.11.5.tar.gz -> GNOME-libxml2-v2.11.5.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from D:\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: D:\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://gitlab.gnome.org//GNOME/libxml2/-/archive/v2.11.5/libxml2-v2.11.5.tar.gz
error: Failed to download from mirror set
error: https://gitlab.gnome.org//GNOME/libxml2/-/archive/v2.11.5/libxml2-v2.11.5.tar.gz: failed: status code 503
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1051):
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 3us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 953us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 1.1 s (1084803us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_gitlab.cmake:118 (vcpkg_download_distfile)
  ports/libxml2/portfile.cmake:1 (vcpkg_from_gitlab)
  scripts/ports.cmake:147 (include)

error: building libxml2:x64-windows failed with: BUILD_FAILED
Elapsed time to handle libxml2:x64-windows: 1.2 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libxml2
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[libxml2]+Build+error&body=Copy+issue+body+from+D%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by jimwang118** [comment]
The upstream `https://gitlab.gnome.org` website cannot be opened, causing the download to fail. You need to wait for the upstream website to be restored.

**Comment by ankurvdev** [comment]
The upstream is back online but the package (version) seems to be gone.

**Comment by m-kuhn** [comment]
Partially online, all projects are gone / not yet restored https://gitlab.gnome.org/explore/projects

**Comment by ankurvdev** [comment]
seems to be working now

**Comment by luodiweiyu** [comment]
> Partially online, all projects are gone / not yet restored https://gitlab.gnome.org/explore/projects

oh, yes
