### ISSUE TITLE
Add clockUtils

### ISSUE THREAD

**Issue by BonneCW** [Microsoft/vcpkg#339]
[clockUtils](https://github.com/ClockworkOrigins/clockUtils) is a collection of small libraries for commonly used tasks optimized for simplicity and speed.

**Comment by mattiascibien** [comment]
Is this fixed by #339?

**Comment by BonneCW** [comment]
Yes, it is (from my side). So can I close this issue?

**Comment by alexkaratarakis** [comment]
You probably mean #351 and yes, this is resolved now. Thanks!
