### ISSUE TITLE
[dcmtk] Build error : library names

### ISSUE THREAD

**Issue by davesworking** [microsoft/vcpkg#33906]
hi,
is it expected that the output libraries have "charls" in the name?
e.g.
libdcmtkcharls.so
libdcmtkcharls.dylib
dcmtkcharls.dll

**Comment by MonicaLiu0311** [comment]
This is decided upstream:
https://github.com/DCMTK/dcmtk/blob/DCMTK-3.6.7/dcmjpls/libcharls/Makefile.in#L22
https://github.com/DCMTK/dcmtk/blob/DCMTK-3.6.7/dcmjpls/libcharls/CMakeLists.txt#L5-L9
https://github.com/DCMTK/dcmtk/blob/master/docs/CHANGES.366#L340
https://github.com/DCMTK/dcmtk/blob/master/docs/CHANGES.366#L340

**Comment by dg0yt** [comment]
IIUC this is a vendored fork of the charls library (which also exists in port `charls`), "revision 55020 dated 2010-10-05." (!)
https://github.com/DCMTK/dcmtk/blob/d1c8190f3e1d2a3cadaef7a266efaa0f8d264255/dcmjpls/docs/readme.txt#L8

**Comment by davesworking** [comment]
So there should be no files named?
libdcmtk.so
libdcmtk.dylib
dcmtk.dll

**Comment by dg0yt** [comment]
Why do you think the installed names need renaming?
FTR these are all DLLs installed by this port for x64-windows:
~~~dcmtk:x64-windows:/bin/cmr.dll
dcmtk:x64-windows:/bin/dcmdata.dll
dcmtk:x64-windows:/bin/dcmdsig.dll
dcmtk:x64-windows:/bin/dcmect.dll
dcmtk:x64-windows:/bin/dcmfg.dll
dcmtk:x64-windows:/bin/dcmimage.dll
dcmtk:x64-windows:/bin/dcmimgle.dll
dcmtk:x64-windows:/bin/dcmiod.dll
dcmtk:x64-windows:/bin/dcmjpeg.dll
dcmtk:x64-windows:/bin/dcmjpls.dll
dcmtk:x64-windows:/bin/dcmnet.dll
dcmtk:x64-windows:/bin/dcmpmap.dll
dcmtk:x64-windows:/bin/dcmpstat.dll
dcmtk:x64-windows:/bin/dcmqrdb.dll
dcmtk:x64-windows:/bin/dcmrt.dll
dcmtk:x64-windows:/bin/dcmseg.dll
dcmtk:x64-windows:/bin/dcmsr.dll
dcmtk:x64-windows:/bin/dcmtkcharls.dll
dcmtk:x64-windows:/bin/dcmtls.dll
dcmtk:x64-windows:/bin/dcmtract.dll
dcmtk:x64-windows:/bin/dcmwlm.dll
dcmtk:x64-windows:/bin/i2d.dll
dcmtk:x64-windows:/bin/ijg12.dll
dcmtk:x64-windows:/bin/ijg16.dll
dcmtk:x64-windows:/bin/ijg8.dll
dcmtk:x64-windows:/bin/oflog.dll
dcmtk:x64-windows:/bin/ofstd.dll
~~~

**Comment by davesworking** [comment]
I want a single library file. I tried:
BUILD_SHARED_LIBS=ON
BUILD_SINGLE_SHARED_LIBRARY=ON

Now the build fails:
CMake Error at dcmtls/libsrc/CMakeLists.txt:13 (set_property):
  set_property could not find TARGET dcmtls.  Perhaps it has not yet been
  created.


CMake Error at dcmnet/libsrc/CMakeLists.txt:49 (set_property):
  set_property could not find TARGET dcmnet.  Perhaps it has not yet been
  created.


CMake Error at dcmsign/libsrc/CMakeLists.txt:26 (set_property):
  set_property could not find TARGET dcmdsig.  Perhaps it has not yet been
  created.


CMake Error at dcmpstat/libsrc/CMakeLists.txt:51 (set_property):
  set_property could not find TARGET dcmpstat.  Perhaps it has not yet been
  created.

**Comment by MonicaLiu0311** [comment]
> I want a single library file. I tried:
> BUILD_SHARED_LIBS=ON
> BUILD_SINGLE_SHARED_LIBRARY=ON

Even if I set it up like this, I can't reproduce your issue.
