### ISSUE TITLE
[log4cxx] Build error

### ISSUE THREAD

**Issue by maoqiangliu** [microsoft/vcpkg#33922]
Copy issue body from D:/hkxdr/client/hkcommons/source/log4cxx-0.11.0/vcpkg-2023.08.09/installed/vcpkg/issue_body.md

**Comment by JonLiu1993** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report an issue.

**Comment by JonLiu1993** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
