### ISSUE TITLE
[qtwebengine]  Failed to download from mirror

### ISSUE THREAD

**Issue by mknigh23** [microsoft/vcpkg#33921]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
.\vcpkg install qt[core,default-features]:x64-windows --x-buildtrees-root=C:\b\
```

### Failure logs

C:\dev\vcpkg>.\vcpkg install qt[core,default-features]:x64-windows --x-buildtrees-root=C:\b\
Computing installation plan...
The following packages will be built and installed:
    qt[core,default-features]:x64-windows -> 6.5.2
  * qtwebengine[core,default-features,geolocation,spellchecker,webchannel]:x64-windows -> 6.5.2
  * qtwebsockets[core,qml]:x64-windows -> 6.5.2
  * qtwebview[core,webengine]:x64-windows -> 6.5.2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\KnightM\AppData\Local\vcpkg\archives in 346 us. Use --debug to see more details.
Installing 1/4 qtwebengine:x64-windows...
Building qtwebengine[core,default-features,geolocation,spellchecker,webchannel]:x64-windows...
-- Setting up python virtual environmnent...
-- Installing python packages: html5lib
-- Setting up python virtual environmnent...finished.
-- Downloading https://download.qt.io/archive/qt/6.5/6.5.2/submodules/qtwebengine-everywhere-src-6.5.2.tar.xz -> qtwebengine-everywhere-src-6.5.2.tar.xz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from C:\dev\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: C:\dev\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://download.qt.io/archive/qt/6.5/6.5.2/submodules/qtwebengine-everywhere-src-6.5.2.tar.xz
warning: Download failed -- retrying after 1000ms
warning: Download failed -- retrying after 2000ms
warning: Download failed -- retrying after 4000ms
error: Failed to download from mirror set
error: https://download.qt.io/archive/qt/6.5/6.5.2/submodules/qtwebengine-everywhere-src-6.5.2.tar.xz: WinHttpReadData failed with exit code 12030
error: https://download.qt.io/archive/qt/6.5/6.5.2/submodules/qtwebengine-everywhere-src-6.5.2.tar.xz: WinHttpReadData failed with exit code 12030
error: https://download.qt.io/archive/qt/6.5/6.5.2/submodules/qtwebengine-everywhere-src-6.5.2.tar.xz: WinHttpReadData failed with exit code 12030
error: https://download.qt.io/archive/qt/6.5/6.5.2/submodules/qtwebengine-everywhere-src-6.5.2.tar.xz: WinHttpReadData failed with exit code 12030
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1051):
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 3us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 2671us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 7 min (422342048us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  installed/x64-windows/share/qtbase/qt_install_submodule.cmake:67 (vcpkg_download_distfile)
  installed/x64-windows/share/qtbase/qt_install_submodule.cmake:84 (qt_download_submodule_impl)
  ports/qtwebengine/portfile.cmake:97 (qt_download_submodule)
  scripts/ports.cmake:147 (include)

error: building qtwebengine:x64-windows failed with: BUILD_FAILED
Elapsed time to handle qtwebengine:x64-windows: 7.2 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qtwebengine
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[qtwebengine]+Build+error&body=Copy+issue+body+from+C%3A%2Fdev%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

Manual direct download from **https://download.qt.io/archive/qt/6.5/6.5.2/submodules/** gets to between 184-195MB of 393MB (different each time), then reports **Couldn't download - Network error**.

**Comment by FrankXie05** [comment]
@mknigh23 
Can you access it manually?
https://download.qt.io/archive/qt/6.5/6.5.2/submodules/qtwebengine-everywhere-src-6.5.2.tar.xz

**Comment by mknigh23** [comment]
Yes, but could not download, which is where the final message was from. However, I just kept trying the command-line, as it seemed to be a temporary network issue, and has finally downloaded the file. That should close this issue, though the installer seems to have hung, with it sitting at this point for the last hour...

C:\dev\vcpkg>.\vcpkg install qt[core]:x64-windows --x-buildtrees-root=C:\b\
Computing installation plan...
The following packages will be built and installed:
    qt:x64-windows -> 6.5.2
  * qtwebengine[core,default-features,geolocation,spellchecker,webchannel]:x64-windows -> 6.5.2
  * qtwebsockets[core,qml]:x64-windows -> 6.5.2
  * qtwebview[core,webengine]:x64-windows -> 6.5.2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\KnightM\AppData\Local\vcpkg\archives in 910 us. Use --debug to see more details.
Installing 1/4 qtwebengine:x64-windows...
Building qtwebengine[core,default-features,geolocation,spellchecker,webchannel]:x64-windows...
-- Setting up python virtual environmnent...
-- Installing python packages: html5lib
-- Setting up python virtual environmnent...finished.
-- Downloading https://download.qt.io/archive/qt/6.5/6.5.2/submodules/qtwebengine-everywhere-src-6.5.2.tar.xz -> qtwebengine-everywhere-src-6.5.2.tar.xz...
-- Extracting source C:/dev/vcpkg/downloads/qtwebengine-everywhere-src-6.5.2.tar.xz
-- Using source at C:/b/qtwebengine/src/here-src-6-50d75bb9a8.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
CMake Warning at installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:318 (message):
  The following variables are not used in CMakeLists.txt:

      FEATURE_webengine_v8_snapshot_support

  Please recheck them and remove the unnecessary options from the
  `vcpkg_cmake_configure` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):
  installed/x64-windows/share/qtbase/qt_install_submodule.cmake:147 (vcpkg_cmake_configure)
  ports/qtwebengine/portfile.cmake:102 (qt_cmake_configure)
  scripts/ports.cmake:147 (include)


-- Building x64-windows-dbg

**Comment by mknigh23** [comment]
I killed the stalled build and restarted, which is now working.
