### ISSUE TITLE
[gmsh] Gmsh fails to build with OpenCascade

### ISSUE THREAD

**Issue by Yanksi** [microsoft/vcpkg#33945]
### Is your feature request related to a problem? Please describe.

I tried to install `gmsh` with `OpenCasade` support with `vcpkg install gmsh[occ]`. When I tried to use the occ backend in my code, an error stating that `OpenCascade` is missing is raised during runtime. When using a debugger to trace into the `gmsh` library, the error was raised in this [file](https://gitlab.onelab.info/gmsh/gmsh/-/blob/master/src/geo/GModelIO_OCC.h). Seems that the `HAVE_OCC` macro was not defined while `gmsh` was built.

### Proposed solution

Find out how is `HAVE_OCC` defined in `gmsh`.

### Additional context

Sorry that this is basically all the information I can give. As I am working on a proprietary code base, I cannot show the code that caused the error here.

**Comment by JonLiu1993** [comment]
@Yanksi, Sorry to reply you so late, I can't see your error message, and I don't have the steps to reproduce your error. I can't try to fix this problem in the version. Could you please provide an error log and a simple reproduction example?

**Comment by dg0yt** [comment]
Opencascade is more healthy now, since #35119. 
But it is also an indication of how much work might be needed in the worst case...

**Comment by Yanksi** [comment]
> Ping @Yanksi for response.

Sorry that I forgot to reply previously. I was developing on someone else's code.  And I'm not familiar with how to use gmsh. I'll take a look at my current codebase and try to derive a minimal example for reproducing the error later.

**Comment by JonLiu1993** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
