### ISSUE TITLE
[Feature request for vcpkg-artifacts] Addition of a manifest validation command

### ISSUE THREAD

**Issue by nirmalsunny** [microsoft/vcpkg#33940]
This is a feature request for the vcpkg artifacts.

When the `vcpkg z-ce regenerate` command is run, the manifests are validated prior to adding them to the registry. The error messages are printed out and said to be skipping the broken manifests. With the validation performed internally, the existing validation checks may be exposed as a command to validate the manifests prior to registry regeneration.  It would be helpful to have a command such as `vcpkg z-ce validate-manifests <path-to-manifest>` which will validate the provided manifest files, and print out any validation errors.

It is particularly useful when there are numerous manifests and the regeneration is part of an unattended workflow. The developers who are responsible for their manifests can have immediate feedback rather than waiting for the regeneration command to fail and parsing the reason for failure.

My team is happy to contribute to the code. However, we wanted to discuss it prior to putting in the time.

**Comment by jimwang118** [comment]
I will try to add this feature.

**Comment by nirmalsunny** [comment]
Thank you for picking this up.

**Comment by nirmalsunny** [comment]
Hello, any update?
