### ISSUE TITLE
Build failing when building with x64-windows triplet because of "0.vcpkg_tags.cmake" file that doesn't exist

### ISSUE THREAD

**Issue by Murk42** [microsoft/vcpkg#33953]
### Discussed in https://github.com/microsoft/vcpkg/discussions/33952

<div type='discussions-op-text'>

<sup>Originally posted by **Murk42** September 23, 2023</sup>
Whenever I run "vcpkg install" (uses x64-windows triplet by default), configuring fails with message:
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
  Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
  Working Directory: D:/Programming/Projects/CMake-vcpkg-testring/MyProject/MyProject/vcpkg_installed/x64-windows/vcpkg/blds/mylibrary/x64-windows-rel/vcpkg-parallel-configure
  Error code: 1
  See logs for more information:
    D:\Programming\Projects\CMake-vcpkg-testring\MyProject\MyProject\vcpkg_installed\x64-windows\vcpkg\blds\mylibrary\config-x64-windows-dbg-CMakeCache.txt.log
    D:\Programming\Projects\CMake-vcpkg-testring\MyProject\MyProject\vcpkg_installed\x64-windows\vcpkg\blds\mylibrary\config-x64-windows-rel-CMakeCache.txt.log
    D:\Programming\Projects\CMake-vcpkg-testring\MyProject\MyProject\vcpkg_installed\x64-windows\vcpkg\blds\mylibrary\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:314 (vcpkg_execute_required_process)
  C:/Users/Marko/AppData/Local/vcpkg/registries/git-trees/3de21e01c3dd3b2d5e2b94fcfbe545db3963fbf2/portfile.cmake:9 (vcpkg_configure_cmake)
  scripts/ports.cmake:147 (include)
```

and here is [config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/12706220/config-x64-windows-out.log)

When I run x64-windows-release there are no problems. My guess is that the problem is configuring debug and release at the same time (thus fail at vcpkg-parallel-configure). 

When i look for the `0.vcpkg_tags.cmake` file, it isn't there.

I've been using vcpkg for a week now and don't know much. I hope someone could help me. Couldn't find anything similar on the internet.</div>

**Comment by Cheney-W** [comment]
Could you please provide below info:
1. The version of your vcpkg and Visual Studio.
2. You repro project or repro command.
