### ISSUE TITLE
fontconfig:x64-linux fails to install

### ISSUE THREAD

**Issue by sanxiyn** [Microsoft/vcpkg#3395]
How to reproduce: vcpkg install fontconfig

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ICONV_LIBRARY
    linked by target "fontconfig" in directory /home/sanxiyn/git/vcpkg/buildtrees/fontconfig/src/fontconfig-2.12.4
```

**Comment by PhoebeHui** [comment]
@sanxiyn, fontconfig installed successfully now, could you try to build it with latest vcpkg?

linux001@linuxtest01:~/vcpkg$ ./vcpkg install fontconfig
The following packages will be built and installed:
    fontconfig[core]:x64-linux
Starting package 1/1: fontconfig:x64-linux
Building package fontconfig[core]:x64-linux...
-- Using cached /home/linux001/vcpkg/downloads/fontconfig-2.12.4.tar.gz
-- Using source at /home/linux001/vcpkg/buildtrees/fontconfig/src/2.12.4-3074630478
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Performing CMake integration test
-- Performing post-build validation
-- Performing post-build validation done
Building package fontconfig[core]:x64-linux... done
Installing package fontconfig[core]:x64-linux...
Installing package fontconfig[core]:x64-linux... done
Elapsed time for package fontconfig:x64-linux: 5.882 s

Total elapsed time: 5.882 s

The package fontconfig:x64-linux provides CMake targets:

    find_package(unofficial-fontconfig CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::fontconfig::fontconfig)

**Comment by sanxiyn** [comment]
This seems fixed. Thanks!
