### ISSUE TITLE
Ubuntu 16.04 libuv

### ISSUE THREAD

**Issue by yangxingpping** [Microsoft/vcpkg#3396]
when I use vcpk to install libuv on Ubuntu16.04 64bit, it failed.
the log in buildtrees/libuv/install-x64-linux-dbg-out.log is 
‘vcpkg/buildtrees/libuv/src/v1.20.0-7de17b6267/src/win/winapi.h:25:21: fatal error: windows.h: No such file or directory’

**Comment by edmBernard** [comment]
I add a pull request for linux https://github.com/Microsoft/vcpkg/pull/3437

**Comment by yangxingpping** [comment]
Thank you very much. It's works for me.
May be 
+    file(GLOB UV_SOURCES_UNIX
+        src/unix/async.c
+        src/unix/core.c
+        src/unix/dl.c
+        src/unix/fs.c
+        src/unix/getaddrinfo.c
+        src/unix/getnameinfo.c
+        src/unix/loop.c
+        src/unix/loop-watcher.c
+        src/unix/pipe.c
+        src/unix/poll.c
+        src/unix/process.c
+        src/unix/signal.c
+        src/unix/stream.c
+        src/unix/tcp.c
+        src/unix/thread.c
+        src/unix/timer.c
+        src/unix/tty.c
+        src/unix/udp.c
+    )
can be replace by
file(GLOB UV_SOURCES_UNIX src/unix/*.c)  ?

**Comment by edmBernard** [comment]
There is android and osx file in unix folder :(
so we can't use unix/*.c

**Comment by PhoebeHui** [comment]
The issue looks solved and libuv installed successfully.

linux001@linuxtest01:~/vcpkg$ ./vcpkg install libuv
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be built and installed:
    libuv[core]:x64-linux
Starting package 1/1: libuv:x64-linux
Building package libuv[core]:x64-linux...
-- Downloading https://github.com/libuv/libuv/archive/v1.25.0.tar.gz...
-- Extracting source /home/linux001/vcpkg/downloads/libuv-libuv-v1.25.0.tar.gz
-- Using source at /home/linux001/vcpkg/buildtrees/libuv/src/v1.25.0-b119df65cf
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package libuv[core]:x64-linux... done
Installing package libuv[core]:x64-linux...
Installing package libuv[core]:x64-linux... done
Elapsed time for package libuv:x64-linux: 4.038 s

Total elapsed time: 4.038 s

The package libuv:x64-linux provides CMake targets:
    find_package(unofficial-libuv CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::libuv::libuv)

linux001@linuxtest01:~/vcpkg$ ./vcpkg version
Vcpkg package management program version 2018.11.23-unknownhash
