### ISSUE TITLE
[libiconv] build failure

### ISSUE THREAD

**Issue by LeenHawk** [microsoft/vcpkg#33965]
### Operating system

Linux (Debian Sid WSL)

### Compiler

Android ndk r26

### Steps to reproduce the behavior

```Shell
`./vcpkg install libiconv --triplet=x64-android`
```

### Failure logs

[config-x64-android-dbg-out.log](https://github.com/microsoft/vcpkg/files/12708325/config-x64-android-dbg-out.log)
[config-x64-android-dbg-config.log](https://github.com/microsoft/vcpkg/files/12708327/config-x64-android-dbg-config.log)
[config-x64-android-dbg-err.log](https://github.com/microsoft/vcpkg/files/12708328/config-x64-android-dbg-err.log)

### Additional context

Maybe:
```shell
configure: error: in `/home/leen/vcpkg/buildtrees/libiconv/x64-android-dbg':
configure: error: C compiler cannot create executables
```

**Comment by dg0yt** [comment]
At the moment, make-based vcpkg ports don't work with NDK r26.
#31332, #33179.

**Comment by jimwang118** [comment]
Can you use a lower version of NDK to complete the compilation?

**Comment by LeenHawk** [comment]
> Can you use a lower version of NDK to complete the compilation?

Yes, ndk 25.2 works well

**Comment by jimwang118** [comment]
> > Can you use a lower version of NDK to complete the compilation?
> 
> Yes, ndk r25.2 works well

OK, I will close this issue. If you have other questions, please submit a new issue later.
