### ISSUE TITLE
[eigen3] build failure on x64-android

### ISSUE THREAD

**Issue by LeenHawk** [microsoft/vcpkg#33979]
### Operating system

Linux (Debian Sid WSL)

### Compiler

Android ndk r25

### Steps to reproduce the behavior

```Shell
./vcpkg install eigen3:x64-android
```

### Failure logs

[config-x64-android-dbg-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/12710819/config-x64-android-dbg-CMakeCache.txt.log)
[config-x64-android-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/12710822/config-x64-android-rel-CMakeCache.txt.log)
[config-x64-android-out.log](https://github.com/microsoft/vcpkg/files/12710825/config-x64-android-out.log)

### Additional context

Similiar question like [windows build failed](https://github.com/microsoft/vcpkg/issues/4902#issue-387700893) and [g++: error: unrecognized command line option ‘-Qunused-arguments’](https://github.com/idaholab/moose/issues/2354)

**Comment by dg0yt** [comment]
~~~~
-- Looking for a Fortran compiler
-- Looking for a Fortran compiler - /usr/bin/f95
-- The Fortran compiler identification is GNU 13.2.0
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - failed
-- Check for working Fortran compiler: /usr/bin/f95
-- Check for working Fortran compiler: /usr/bin/f95 - broken
CMake Error at /usr/share/cmake-3.27/Modules/CMakeTestFortranCompiler.cmake:59 (message):
  The Fortran compiler

    "/usr/bin/f95"

  is not able to compile a simple test program.
~~~~
Hm, this doesn't look like a tool for android.

**Comment by LeenHawk** [comment]
> ```
> -- Looking for a Fortran compiler
> -- Looking for a Fortran compiler - /usr/bin/f95
> -- The Fortran compiler identification is GNU 13.2.0
> -- Detecting Fortran compiler ABI info
> -- Detecting Fortran compiler ABI info - failed
> -- Check for working Fortran compiler: /usr/bin/f95
> -- Check for working Fortran compiler: /usr/bin/f95 - broken
> CMake Error at /usr/share/cmake-3.27/Modules/CMakeTestFortranCompiler.cmake:59 (message):
>   The Fortran compiler
> 
>     "/usr/bin/f95"
> 
>   is not able to compile a simple test program.
> ```
> 
> Hm, this doesn't look like a tool for android.

But eigen3 is only headers  library. Why use fortran?

**Comment by dg0yt** [comment]
Sure. I guess it might be used for tests. But it is a port bug here.

**Comment by LeenHawk** [comment]
> Sure. I guess it might be used for tests. But it is a port bug here.

Guys, I uninstall all fortran compilers of my computer, eigen3 could be installed. Is there any options to close fortran check in vcpkg?
