### ISSUE TITLE
vcpkg install gdal:x86-windows-static fails, saying icu:x86-windows-static failed

### ISSUE THREAD

**Issue by gqphd** [Microsoft/vcpkg#3397]
Using VCPKG in Win10, x64 machine.
all libs that i am building is x86.
I am trying to get gdal package in vcpkg but emits error. 

Input :
 vcpkg install gdal:x86-windows-static

Output : 
Error: Building package icu:x86-windows-static failed with: BUILD_FAILED
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x86-windows-static
  Vcpkg version: 0.0.110-2018-04-25-f6530368eb31734734c0e1e7ce990c0cb93f0b24

CMake Error at D:/Dev/DevSpace/Utils/VCPKG/vcpkg_dev_A/scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: D:/Dev/DevSpace/Utils/VCPKG/vcpkg_dev_A/downloads/tools/msys2/msys64/usr/bin/bash.exe;--noprofile;--norc;-c;pacman -Sy --noconfirm --needed make automake1.15
    Working Directory: D:/Dev/DevSpace/Utils/VCPKG/vcpkg_dev_A/downloads/tools/msys2
    See logs for more information:
      D:\Dev\DevSpace\Utils\VCPKG\vcpkg_dev_A\buildtrees\icu\msys-pacman-x86-windows-static-out.log
      D:\Dev\DevSpace\Utils\VCPKG\vcpkg_dev_A\buildtrees\icu\msys-pacman-x86-windows-static-err.log

Call Stack (most recent call first):
  D:/Dev/DevSpace/Utils/VCPKG/vcpkg_dev_A/scripts/cmake/vcpkg_acquire_msys.cmake:104 (vcpkg_execute_required_process)
  D:/Dev/DevSpace/Utils/VCPKG/vcpkg_dev_A/ports/icu/portfile.cmake:34 (vcpkg_acquire_msys)
  D:/Dev/DevSpace/Utils/VCPKG/vcpkg_dev_A/scripts/ports.cmake:72 (include)

**Comment by seankain** [comment]
I am also seeing this issue for windows-x64-static. 

The msys-pacman-x64-windows-static-err.log reports

> error: key "5F92EFC1A47D45A1" could not be looked up remotely
> error: required key missing from keyring
> error: failed to commit transaction (unexpected error)

This appears to be an issue with any of the packages that use  vcpkg_acquire_msys

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
