### ISSUE TITLE
Add libxml2

### ISSUE THREAD

**Issue by nurse** [Microsoft/vcpkg#34]
libxml2 is famous xml library and widely used in C world. http://xmlsoft.org/
If we can use libxml2 by vcpkg, many other xml software will be open to vcpkg.

**Comment by ethanhs** [comment]
This would depend on libiconv. I may try to create ports for both. @ras0219-msft is that okay?

**Comment by ras0219-msft** [comment]
@ethanhs  We'd happily accept a PR for each of these. Please make them as separate PRs, however, to make it easier to review.

**Comment by Orvid** [comment]
This was added in https://github.com/Microsoft/vcpkg/pull/166.

**Comment by nurse** [comment]
thanks!
