### ISSUE TITLE
[luajit] unexpected files installed in include dir

### ISSUE THREAD

**Issue by Pospelove** [microsoft/vcpkg#34008]
Host:
Windows 11, MSVC (arm64-windows)

Target:
x64-windows

Steps to reproduce:
vcpkg install luajit:x64-windows

Expected result:
installed/x64-windows/luajit/include contains only header files

Real result:
many unexpected files such as
lib, pdb, exp, .gitignore, bar, Makefile etc
<img width="293" alt="image" src="https://github.com/microsoft/vcpkg/assets/37947786/8354e811-5799-43c9-93a2-150f7fe94833">

**Comment by dg0yt** [comment]
Hm. We only want to copy this:
https://github.com/microsoft/vcpkg/blob/08cc145ed5858faa83160986b3f27f37c499d6ad/ports/luajit/Makefile.nmake#L15-L20
