### ISSUE TITLE
Building package openblas:x64-linux failed

### ISSUE THREAD

**Issue by jakob1379** [Microsoft/vcpkg#3400]
I have the latest version installed on my system (Ubuntu 16.04) and when I try to install dlib with `vcpkg install dlib` I get an error when openblas is compiled

    Call Stack (most recent call first):
    scripts/cmake/vcpkg_configure_cmake.cmake:247 (vcpkg_execute_required_process)
    ports/openblas/portfile.cmake:81 (vcpkg_configure_cmake)
    scripts/ports.cmake:72 (include)

    Error: Building package openblas:x64-linux failed with: BUILD_FAILED
    Please ensure you're using the latest portfiles with `.\vcpkg update`, then
    submit an issue at https://github.com/Microsoft/vcpkg/issues including:
    Package: openblas:x64-linux
    Vcpkg version: 0.0.110-unknownhash

as well as the err-log
    CMake Warning at CMakeLists.txt:59 (message):
      CMake support is experimental.  This will not produce the same Makefiles
      that OpenBLAS ships with.  Only x86 support is currently available.

    CMake Error at cmake/c_check.cmake:63 (if):
      if given arguments:

        "STREQUAL" "AMD64"

      Unknown arguments specified
    Call Stack (most recent call first):
      cmake/prebuild.cmake:58 (include)
      cmake/system.cmake:81 (include)
      CMakeLists.txt:62 (include)

I'm not able to debug the many flags that's being

**Comment by stiv-yakovenko** [comment]
Same problems, how to fix it?

**Comment by Chen-Zhihui** [comment]
update cmake to 3.11 abover

**Comment by apattnaik0721013** [comment]
@Chen-Zhihui 
- i am using cmake version 3.11.4, still install failed.
- any idea how to resolve this?

**Comment by harshn05** [comment]
Still not solved?

**Comment by jakob1379** [comment]
> Still not solved?

No.
