### ISSUE TITLE
d3d12-memory-allocator generate wrong lib path in visual studio 2022

### ISSUE THREAD

**Issue by pancystar** [microsoft/vcpkg#34007]
**Describe the bug**
use vcpkg install d3d12-memory-allocator and link this lib to cmake，generate sln project find wrong lib path
![image](https://github.com/microsoft/vcpkg/assets/20381945/8af6a408-6b52-4d85-81bb-5cbd05b36c8c)
**Environment**
- OS: Windows11 cmake
- Compiler: visual studio 2022

**To Reproduce**
1. ./vcpkg install d3d12-memory-allocator
2. in cmake link the lib by using target_link_libraries(d3d12-memory-allocator)
3. find lib path is wrong, only have the lib name
Repro code when

**Expected behavior**
when link the lib in cmake and visual studio, full lib path should generate,such as X;/xxx/xxx/xxx/debug/lib/d3d12-memory-allocator or X;/xxx/xxx/xxx/release/lib/d3d12-memory-allocator

**Failure logs**
-(please attached failure logs)

**Additional context**

**Comment by MonicaLiu0311** [comment]
Could you please try #34086 to see if it fixes this issue? Below is my test code:

<details>
<summary><b>CMakeFindUsage.cpp</b></summary>
<pre>
#include &#60;iostream&#62;
#include "D3D12MemAlloc.h"

using namespace std;

int main()
{
        cout << "Hello CMake." << endl;
        return 0;
}
</pre></details>


<details>
<summary><b>CMakeLists.txt</b></summary>
<pre>
cmake_minimum_required (VERSION 3.8)

set(CMAKE_TOOLCHAIN_FILE "E:/vcpkg/scripts/buildsystems/vcpkg.cmake")

project ("CMakeFindUsage")

add_library (main "CMakeFindUsage.cpp")

find_package(d3d12-memory-allocator CONFIG REQUIRED)

target_link_libraries(main PRIVATE unofficial::d3d12-memory-allocator)
</pre></details>
