### ISSUE TITLE
[New Port Request] Version 6.2.5 of Qt

### ISSUE THREAD

**Issue by CompSciDude1** [microsoft/vcpkg#34015]
### Library name

Qt (all open source modules)

### Source repository URL

https://download.qt.io/official_releases/qt/6.2/6.2.5/single/

### Project homepage (if different from the source repository)

https://qt.io

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

Add version 6.2.5 of all available open source Qt modules.

**Comment by Neumann-A** [comment]
Qt is at 6.5.2. vcpkg won't backfill commercial LTS versions of Qt.

**Comment by xavier2k6** [comment]
@Neumann-A FYI - jom 1.1.4 was officially released by Qt Company.

https://download.qt.io/official_releases/jom/
https://mirrors.ukfast.co.uk/sites/qt.io/official_releases/jom/changelog.txt
