### ISSUE TITLE
[libgit2] Wrong CRT linkage

### ISSUE THREAD

**Issue by kjpus** [Microsoft/vcpkg#3402]
I tried to build libgit2 using static library but dynamic CRT linkage. I modified the triplet `x64-windows-static` with `set(VCPKG_CRT_LINKAGE dynamic)`. I got an error message:
```
Expected Debug,Dynamic crt linkage, but the following libs had invalid crt linkage:
    C:/Libraries/vcpkg/packages/libgit2_x64-windows-static/debug/lib/git2.lib
```
I'm using VS2015 on Win7.

**Comment by fcharlie** [comment]
libgit2 **port** current not support build static, you can fork and create PR fix.

**Comment by kjpus** [comment]
portfile.cmake update proposed in PR #4387
