### ISSUE TITLE
[opencascade] update to <7.7.0>

### ISSUE THREAD

**Issue by runarundheim** [microsoft/vcpkg#34089]
### Library name

Open CASCADE

### New version number

7.7.0

**Comment by runarundheim** [comment]
Close since duplicate: #33155

**Comment by dg0yt** [comment]
> Close since duplicate: #33155

Actually #33376.

**Comment by JonLiu1993** [comment]
Fixed by PR https://github.com/microsoft/vcpkg/pull/33498
