### ISSUE TITLE
Proj4 dll is not copied with gdal libraries, making some gdal functions nonfunctional

### ISSUE THREAD

**Issue by RobertSpir** [microsoft/vcpkg#3408]
for example, OCTTransform() function to transform coordinates from meters to lat/lon doesn't work. When I copied proj_4_9.dll to executable directory and renamed it to proj.dll, the transformation works.

**Comment by treigilbert** [comment]
See GDAL fails to load proj4_9.dll (#3258) for more details on where gdal attempts to load the wrong dll name.

**Comment by JackBoosY** [comment]
Hi @RobertSpir , when GDAL is exported, the headers and library of proj4 will also be exported. 
So, the only problem is that the library for proj4 needs to be renamed to proj.dll?

**Comment by JackBoosY** [comment]
GDAL loading proj dynamic library mode is **dynamically** loaded(using `load_library`), so the project using gdal can **NOT** add `proj.dll` to the list of libraries that **must** be dependent on the build, which caused vcpkg to fail to copy `proj.dll` to the build folder depending on the dependencies.

**Comment by JackBoosY** [comment]
Hi @RobertSpir, thanks for reporting this issue.
I've fixed this issue now, please update vcpkg and rebuild gdal.

Thanks.
