### ISSUE TITLE
glib:x64-windows-static failing

### ISSUE THREAD

**Issue by olilarkin** [microsoft/vcpkg#3409]
actually trying to install cairo x64 static, which previously worked

-- CURRENT_PORT_DIR=C:/Users/oli/Dev/vcpkg/ports/glib/.
Glib relies on DllMain and therefore cannot be built statically
CMake Error at C:/Users/oli/Dev/vcpkg/ports/glib/portfile.cmake:13 (message):
  Glib only supports dynamic library and crt linkage

Error: Building package glib:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glib:x64-windows-static
  Vcpkg version: 0.0.110-2018-05-02-1e41c4377f38512d1d6c0d65a2e7b9c7c8b03bea

**Comment by shirj** [comment]
Same issue while trying to install `pcl[openni2,qt,pcap]:x64-windows-static --featurepackages`

```
PS C:\Users\USERNAME> vcpkg install pcl[openni2,qt,pcap]:x64-windows-static --featurepackages
The following packages will be built and installed:
  * atlmfc[core]:x64-windows-static
  ...more * packages...
  * openssl[core]:x64-windows-static
    pcl[core,openni2,pcap,qt]:x64-windows-static
  * qhull[core]:x64-windows-static
  ...more * packages...
  * winpcap[core]:x64-windows-static
Additional packages (*) will be modified to complete this operation.
Starting package 1/90: glib:x64-windows-static
Building package glib[core]:x64-windows-static...
-- CURRENT_INSTALLED_DIR=C:/Users/USERNAME/Documents/vcpkg/installed/x64-windows-static
-- DOWNLOADS=C:/Users/USERNAME/Documents/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/USERNAME/Documents/vcpkg/packages/glib_x64-windows-static
-- CURRENT_BUILDTREES_DIR=C:/Users/USERNAME/Documents/vcpkg/buildtrees/glib
-- CURRENT_PORT_DIR=C:/Users/USERNAME/Documents/vcpkg/ports/glib
Glib relies on DllMain and therefore cannot be built statically
CMake Error at ports/glib/portfile.cmake:13 (message):
  Glib only supports dynamic library and crt linkage
Call Stack (most recent call first):
  scripts/ports.cmake:72 (include)


Error: Building package glib:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glib:x64-windows-static
  Vcpkg version: 0.0.110-2018-05-10-9a19dae13a0fa594245db2df45ec54a504bc82f3

Additionally, attach any relevant sections from the log files above.
```

**Comment by sykhro** [comment]
I'm running into the same issue when trying to build qt5-base. This is kind of a problem, since Qt *can* be built statically.

**Comment by stekyne** [comment]
This is a real pain point. Anybody with more information?

**Comment by sykhro** [comment]
Nothing really. I'll look into the build details when I have time and submit a PR for it

**Comment by stekyne** [comment]
The symbols: GLIB_STATIC_COMPILATION and GOBJECT_STATIC_COMPILATION seem to allow this? 
https://github.com/GNOME/glib/blob/4e1488eebb2129c6e39162b56275d311f24216ab/meson.build#L175-L178

**Comment by olilarkin** [comment]
any news from anyone? i have tried and failed to fix this

**Comment by sykhro** [comment]
I have tried but entered an endless rabbit hole, too many dependencies. Also gave up because other builds broke randomly.

**Comment by olilarkin** [comment]
it definitely worked in the past

**Comment by LilyWangL** [comment]
GLib doesn't support static build for Windows. See more information here:
https://bugzilla.gnome.org/show_bug.cgi?id=752837
https://github.com/microsoft/vcpkg/pull/529#issuecomment-272586906

**Comment by stekyne** [comment]
Should it fail the build though? I've seen other times it will force dynamic linking instead and continue. For instance, if you want to build a static version of fluidsynth i.e. fluidsynth:x64-windows-static. Glib is a dependency so it will try to build statically but fail due to the error above. Should it not continue but use it dynamically and the rest statically? Otherwise you need to create a custom triplet, which is a bit of a pain.

**Comment by JackBoosY** [comment]
@stekyne To build glib as a static library and link using a static CRT, we will get a `Dllmain` error:
```
gobject-2.0.lib(gtype.c.obj) : error LNK2005: DllMain already defined in glib-2.0.lib(glib-init.c.obj)
```

**Comment by proTerm** [comment]
ping

**Comment by JackBoosY** [comment]
@proTerm Since the official does not provide a method to build static in windows, and function `dllmain` does exist in these two libraries, can you accept that tools cannot be built in static?

Note to me: glib and gobject should be installed to the `manual-link` folder.

**Comment by proTerm** [comment]
> can you accept that tools cannot be built in static?

I hope that a solution would be found.

**Comment by proTerm** [comment]
Has the bug been fixed? Because Im still getting an error?
```
Starting package 6/15: glib:x64-windows-static
Building package glib[core]:x64-windows-static...
-- Note: glib only supports dynamic library linkage. Building dynamic library.
CMake Error at scripts/cmake/vcpkg_check_linkage.cmake:47 (message):
  Refusing to build unexpected dynamic library against the static CRT.  If
  this is desired, please configure your triplet to directly request this
  configuration.
Call Stack (most recent call first):
  ports/glib/portfile.cmake:6 (vcpkg_check_linkage)
  scripts/ports.cmake:142 (include)


Error: Building package glib:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glib:x64-windows-static
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9
```

**Comment by sykhro** [comment]
This is *not* a bug, GLib doesn't support static linking on Windows yet. There's a merge request upstream but GLib doesn't have many Windows maintainers, so it's just sitting there going stale

**Comment by proTerm** [comment]
> This is _not_ a bug,

Its not a bug, its a feature ;)

For a moment I had thought, this issue has been resolved ...  (On the other hand, its such a pity that this issue is not being prioritized by the vcpkg team).

Thanks for the answer!

**Comment by sykhro** [comment]
I mean, the vcpkg team can't do anything about this. GLib just doesn't work when linked statically, it has to be fixed upstream

**Comment by proTerm** [comment]
@JackBoosY Im surprised you close the issue, although it would never be resolved ... ?

**Comment by JackBoosY** [comment]
@proTerm  As you can see, the upstream doesn't support static build for such a long time.
And some contributors are trying to support static but waiting for the upstream approval.
