### ISSUE TITLE
 Building package boost-build:x64-windows failed

### ISSUE THREAD

**Issue by ruanwenfeng** [Microsoft/vcpkg#3412]
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: C:/Users/ruanwenfeng/Documents/GitHub/vcpkg/packages/boost-build_x64-windows/tools/boost-build/bootstrap.bat;msvc
    Working Directory: C:/Users/ruanwenfeng/Documents/GitHub/vcpkg/packages/boost-build_x64-windows/tools/boost-build
    See logs for more information:
      C:\Users\ruanwenfeng\Documents\GitHub\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-out.log
      C:\Users\ruanwenfeng\Documents\GitHub\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-err.log

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:53 (vcpkg_execute_required_process)
  scripts/ports.cmake:72 (include) 

Package: boost-build:x64-windows
 Vcpkg version: 0.0.110-2018-05-02-eb048e16a1e070829b5f61c5b344bc6b546db96c

**Comment by ruanwenfeng** [comment]
@Voskrese 
bootstrap-x64-windows-out.log
Bootstrapping the build engine

Failed to bootstrap the build engine
Please consult bootstrap.log for furter diagnostics.

bootstrap-x64-windows-err.log
![image](https://user-images.githubusercontent.com/27943586/39559945-9a56ccb0-4ecc-11e8-9570-391e528a4b3c.png)

**Comment by Voskrese** [comment]
@ruanwenfeng 
интересный скриншот, а сам текстовый лог файл не хотите приложить?

> an interesting screenshot, and the text file itself does not want to attach?

**Comment by fwosar** [comment]
I am experiencing the identical error:

```-- Bootstrapping...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: D:/Development/Sources/vcpkg/packages/boost-build_x86-windows-static/tools/boost-build/bootstrap.bat;msvc
    Working Directory: D:/Development/Sources/vcpkg/packages/boost-build_x86-windows-static/tools/boost-build
    See logs for more information:
      D:\Development\Sources\vcpkg\buildtrees\boost-build\bootstrap-x86-windows-static-out.log
      D:\Development\Sources\vcpkg\buildtrees\boost-build\bootstrap-x86-windows-static-err.log

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:53 (vcpkg_execute_required_process)
  scripts/ports.cmake:72 (include)```

[bootstrap-x86-windows-static-err.log](https://github.com/Microsoft/vcpkg/files/1977746/bootstrap-x86-windows-static-err.log)
[bootstrap-x86-windows-static-out.log](https://github.com/Microsoft/vcpkg/files/1977747/bootstrap-x86-windows-static-out.log)

There is no bootstrap.log file whatsoever in any of the boost-build folders. Using Visual Studio 15.6.7.

**Comment by Voskrese** [comment]
> cl : Command line warning D9035 : option 'GZ' has been deprecated and will be removed in a future release
> cl : Command line warning D9036 : use 'RTC1' instead of 'GZ'
> cl : Command line warning D9002 : ignoring unknown option '/MLd'
**/MLd ???** /MTd же

 bootstrap-x86-windows-static-out.log
`Please consult bootstrap.log for furter diagnostics.`
bootstrap.log

**Comment by LarryIII** [comment]
@ruanwenfeng Thanks for you feedback. I installed boost-build:x64-windows successfully. Please open a new issue if this is still a problem for you.
