### ISSUE TITLE
[tesseract] Build error

### ISSUE THREAD

**Issue by aakash-chakraborty1995** [microsoft/vcpkg#34137]
Computing installation plan...
The following packages will be built and installed:
    tesseract:x64-windows -> 5.3.2
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\Akash Chakraborty\AppData\Local\vcpkg\archives in 148 us. Use --debug to see more details.
Installing 1/1 tesseract:x64-windows...
Building tesseract:x64-windows...
-- Using cached tesseract-ocr-tesseract-5.3.2.tar.gz.
-- Cleaning sources at C:/Users/Akash Chakraborty/Downloads/Tess/vcpkg/buildtrees/tesseract/src/5.3.2-fe58d21975.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Akash Chakraborty/Downloads/Tess/vcpkg/downloads/tesseract-ocr-tesseract-5.3.2.tar.gz
-- Applying patch fix_static_link_icu.patch
-- Applying patch fix-aarch64-mfpu-not-available.patch
-- Using source at C:/Users/Akash Chakraborty/Downloads/Tess/vcpkg/buildtrees/tesseract/src/5.3.2-fe58d21975.clean
-- Configuring x64-windows
-- Building x64-windows-dbg

CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Users/Akash Chakraborty/Downloads/Tess/vcpkg/downloads/tools/cmake-3.27.1-windows/cmake-3.27.1-windows-i386/bin/cmake.exe" --build . --config Debug --target install -- -v -j13
    Working Directory: C:/Users/Akash Chakraborty/Downloads/Tess/vcpkg/buildtrees/tesseract/x64-windows-dbg
    See logs for more information:
      C:\Users\Akash Chakraborty\Downloads\Tess\vcpkg\buildtrees\tesseract\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/tesseract/portfile.cmake:37 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building tesseract:x64-windows failed with: BUILD_FAILED
Elapsed time to handle tesseract:x64-windows: 13 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at: 
https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+tesseract

**Open issues are not helpful enough.**
```[tasklist]
### Tasks
```

**Comment by aakash-chakraborty1995** [comment]
The only answer I could find is disabling the Security. Is there any other way we can build this. Build Tesseract for Visual Studio.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please provide the error log: `C:\Users\Akash Chakraborty\Downloads\Tess\vcpkg\buildtrees\tesseract\install-x64-windows-dbg-out.log`.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
