### ISSUE TITLE
[dp-thread-pool 0.6.2] The `include` folder name includes the version 

### ISSUE THREAD

**Issue by cosmin42** [microsoft/vcpkg#34140]
### Is your feature request related to a problem? Please describe.

When installing `dp-thread-pool` the include path is
`vcpkg\installed\x64-windows\include\thread-pool-0.6.2`
It should be:
`vcpkg\installed\x64-windows\include` 

When using the library, the include path has to be added manually which should not be necessary.

### Proposed solution

https://github.com/microsoft/vcpkg/blob/c6d6efed3e9b4242765bfe1b5c5befffd85f7b92/ports/dp-thread-pool/portfile.cmake#L23

Change `CONFIG_PATH lib/cmake/thread-pool-${VERSION}` to `CONFIG_PATH lib/cmake/thread-pool`

### Additional context

Machine: Reproduced on windows-x64, but it's not specific.

Steps to reproduce:

1. vcpkg install dp-thread-pool:x64-windows
2. Go to `vcpkg\installed\x64-windows\include`

Expected: `thread-pool` exists.
Actual: `thread-pool-0.6.2` exists.

**Comment by dg0yt** [comment]
> When installing `dp-thread-pool` the include path is
> `vcpkg\installed\x64-windows\include\thread-pool-0.6.2`
> It should be:
> `vcpkg\installed\x64-windows\include`

Upstream chose first.

> Change `CONFIG_PATH lib/cmake/thread-pool-${VERSION}` to `CONFIG_PATH lib/cmake/thread-pool`

This doesn't affect `include`.
But the CMake config has the full path:
~~~cmake
set_target_properties(dp::thread-pool PROPERTIES
  ...
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/thread-pool-0.6.2"
  ...
)
~~~
If you don't use CMake, you may need to configure manually,
