### ISSUE TITLE
[getopt-win32] should use official repo

### ISSUE THREAD

**Issue by jiayuehua** [microsoft/vcpkg#34158]
### Is your feature request related to a problem? Please describe.

https://github.com/microsoft/vcpkg/blob/c6d6efed3e9b4242765bfe1b5c5befffd85f7b92/ports/getopt-win32/portfile.cmake#L3 now the getopt-win32 not using offcial repo https://github.com/libimobiledevice-win32/getopt"

### Proposed solution

should using official repo. any change should use patch or summit pr to upstream.

**Comment by dg0yt** [comment]
Why do you think `libimobiledevice-win32/getopt`  is the official repo?
Are you aware of the problems with the past state of those libimobiledevice(-win32) ports?

**Comment by dg0yt** [comment]
In particular, read https://github.com/microsoft/vcpkg/pull/33246#issuecomment-1710785895 and following.

**Comment by JonLiu1993** [comment]
@jiayuehua, Thanks for posting this issue, I think @xiaozhuai has explained your question in [comment](https://github.com/microsoft/vcpkg/pull/33246#issuecomment-1706417751), so I will close this issue.
