### ISSUE TITLE
FAQ needs updating

### ISSUE THREAD

**Issue by jaydeflix** [Microsoft/vcpkg#3416]
Now that Linux and Mac is supported, time to update https://github.com/Microsoft/vcpkg/blob/master/docs/about/faq.md#does-vcpkg-run-on-linuxosx

I'd do a pr but figured there might be someone who knows what they want to put in there better than me putting in 'Yes!' as an answer.

**Comment by ras0219-msft** [comment]
Thanks for pointing that out! We really appreciate it!
