### ISSUE TITLE
[chakracore] stopped tolerate mixing CRTs after last portfile fix?

### ISSUE THREAD

**Issue by Pospelove** [microsoft/vcpkg#34167]
after https://github.com/microsoft/vcpkg/pull/33182, my app started crashing after a few seconds.

downgrading port-version from 4 to 3 helped: https://github.com/skyrim-multiplayer/skymp/pull/1712/files

Visual Studio debugger doesn't show call stack, only points at debugbreak/KernelBase.dll. Visual Studio shows that the crash occurs in the ChakraCore helper thread

I guess we should consider reverting #33182 and/or researching why could it happen

Host: arm64-windows
Target: an overlay triplet based on x64-windows-static with only exception to chakracore itself
```cmake
set(VCPKG_TARGET_ARCHITECTURE x64)

set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)

if(${PORT} MATCHES "chakracore")
  set(VCPKG_CRT_LINKAGE dynamic)
  set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()
```

**Comment by dg0yt** [comment]
Mixing static and dynamic crt linkage on Windows, really?

**Comment by Pospelove** [comment]
Not really, I guess

https://github.com/microsoft/vcpkg/blob/master/ports/chakracore/portfile.cmake#L18

**Comment by dg0yt** [comment]
Hm, so the triplet does specifically `set(VCPKG_CRT_LINKAGE dynamic)` for chacracore although "ChakraCore only supports static CRT linkage"?
Ant the portfile already enforces dynamic library linkage....

AFAIU one desired effect of the msbuild port is to better ensure passing toolchain settings. Maybe it is really successful here?

**Comment by Neumann-A** [comment]
I would assume https://github.com/microsoft/vcpkg/blame/c6d6efed3e9b4242765bfe1b5c5befffd85f7b92/ports/chakracore/portfile.cmake#L18 is just wrong. Nobody touched that in year and looking at https://github.com/chakra-core/ChakraCore/blob/c3ead3f8a6e0bb8e32e043adc091c68cba5935e9/Build/Common.Build.props#L72-L73 just shows that it doesn't seem to be correct.
