### ISSUE TITLE
[openimageio] Build error: File does not have the expected hash

### ISSUE THREAD

**Issue by Silverlan** [microsoft/vcpkg#34173]
Package: openimageio:x64-windows -> 2.4.14.0#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.36.32534.0
-    vcpkg-tool version: 2023-09-15-ac02a9f660977426b8ec6392919fbb1d51b10998
    vcpkg-scripts version: c6d6efed3 2023-09-28 (24 hours ago)

I have also tried it on a Linux GitHub runner with the same result.

**To Reproduce**

`vcpkg install openimageio`
**Failure logs**

```
-- Downloading https://github.com/OpenImageIO/oiio/archive/v2.4.14.0.tar.gz -> OpenImageIO-oiio-v2.4.14.0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Disabling metrics because vcpkg.disable-metrics exists
[DEBUG] Trying to load bundleconfig from C:\Users\******\Desktop\tmp5\pragma\deps\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: C:\Users\******\Desktop\tmp5\pragma\deps\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://github.com/OpenImageIO/oiio/archive/v2.4.14.0.tar.gz
[DEBUG] Trying to hash C:\Users\******\Desktop\tmp5\pragma\deps\vcpkg\downloads\OpenImageIO-oiio-v2.4.14.0.tar.gz.26904.part
[DEBUG] C:\Users\******\Desktop\tmp5\pragma\deps\vcpkg\downloads\OpenImageIO-oiio-v2.4.14.0.tar.gz.26904.part has hash 6b87c805907a2f7c98f40e987fb6ebf769f8519f5d8a8b7393bed62a41cee1118bb32d2bc4d23fd464973e237077d08771ff85f72073caa57799d71bd098038f
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/OpenImageIO/oiio/archive/v2.4.14.0.tar.gz
File: C:\Users\******\Desktop\tmp5\pragma\deps\vcpkg\downloads\OpenImageIO-oiio-v2.4.14.0.tar.gz.26904.part
Expected hash: 59c38667ae792f5c5cc6f7f9655159e9b0e048d99f1232766407c01ab635a319ad4ba28cd3c6a115924ea0e4ec994d4c1bdb2f6301fbb9ae11b2820768bd1ff1
Actual hash: 6b87c805907a2f7c98f40e987fb6ebf769f8519f5d8a8b7393bed62a41cee1118bb32d2bc4d23fd464973e237077d08771ff85f72073caa57799d71bd098038f
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1051): 
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 2us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 407us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 7.6 s (7649722us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
      

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/openimageio/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:147 (include)



```

**Comment by SlawekNowy** [comment]
It seems that archive download had changed hash. What.

**Comment by HughMacdonald** [comment]
(I was about to come and report the same thing)

They moved their repository on Friday (29th September) from OpenImageIO/oiio to AcademySoftwareFoundation/OpenImageIO. There is a forwarder, but I'm guessing they re-built the releases, which is why the hash has changed.

If this is updated, I would suggest changing the respository as well as the hash.

**Comment by dg0yt** [comment]
> They moved their repository on Friday (29th September) from OpenImageIO/oiio to AcademySoftwareFoundation/OpenImageIO.

... and such operations are known/documented to change the contents of the on-the-fly tarballs used by `vcpkg_from_github`.

**Comment by 0x779** [comment]
As a temporary workaround, you can replace the SHA512 in `vcpkg/ports/openimageio/portfile.cmake` with the SHA of the actual file it's referencing (in my case, it was `https://codeload.github.com/AcademySoftwareFoundation/OpenImageIO/tar.gz/refs/tags/v2.4.11.1`).

**Comment by BillyONeal** [comment]
> They moved their repository on Friday (29th September) from OpenImageIO/oiio to AcademySoftwareFoundation/OpenImageIO.

Is there somewhere where they actually say this officially? Their website still points to https://github.com/OpenImageIO/oiio/archives/master.zip

**Comment by HughMacdonald** [comment]
Should probably just connect in @lgritz here. 

It was mentioned on the official Slack at the end of last week, but I'm guessing that other sources of info haven't been updated yet.

**Comment by lgritz** [comment]
Sorry, yes, we moved the repo (all the github links should redirect automatically, allegedly), but we probably still have some straggler links that haven't been updated. Thanks for the alert about the link on the web site.

**Comment by BillyONeal** [comment]
> Sorry, yes, we moved the repo (all the github links should redirect automatically, allegedly)

Yesterday the links were just broken rather than redirecting.
