### ISSUE TITLE
OpenCV on Linux

### ISSUE THREAD

**Issue by patrikhuber** [microsoft/vcpkg#3418]
I installed `opencv:x64-linux`. During the installation, OpenCV downloads `opencv_ffmpeg.dll`, which is probably for Windows.
I didn't get any build errors afterwards, but ffmpeg doesn't appear to be working.

> Starting package 5/5: opencv:x64-linux
Building package opencv[core,ffmpeg,jpeg,png,tiff]:x64-linux...
[...]
-- Downloading https://raw.githubusercontent.com/opencv/opencv_3rdparty/0a0e88972a7ea97708378d0488a65f83e7cc5e69/ffmpeg/opencv_ffmpeg.dll...
-- Downloading https://raw.githubusercontent.com/opencv/opencv_3rdparty/0a0e88972a7ea97708378d0488a65f83e7cc5e69/ffmpeg/opencv_ffmpeg.dll... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Downloading https://raw.githubusercontent.com/opencv/opencv_3rdparty/0a0e88972a7ea97708378d0488a65f83e7cc5e69/ffmpeg/opencv_ffmpeg_64.dll...
-- Downloading https://raw.githubusercontent.com/opencv/opencv_3rdparty/0a0e88972a7ea97708378d0488a65f83e7cc5e69/ffmpeg/opencv_ffmpeg_64.dll... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Downloading https://raw.githubusercontent.com/opencv/opencv_3rdparty/0a0e88972a7ea97708378d0488a65f83e7cc5e69/ffmpeg/ffmpeg_version.cmake...
-- Downloading https://raw.githubusercontent.com/opencv/opencv_3rdparty/0a0e88972a7ea97708378d0488a65f83e7cc5e69/ffmpeg/ffmpeg_version.cmake... OK

**Comment by arthur-tacca** [comment]
Similarly `opencv[ipp]` downloads the Windows .dll even when building on Linux, and the build silently succeeds without IPP support.

**Comment by arthur-tacca** [comment]
Somewhat related: #2799 OpenCV should copy/install opencv_ffmpeg340_64.dll
