### ISSUE TITLE
[pkgconf] Build error

### ISSUE THREAD

**Issue by Kiran-Ledai** [microsoft/vcpkg#34205]
Copy issue body from C:/Ochno/instruction and useful materials/vcpkg/installed/vcpkg/issue_body.md

Computing installation plan...
The following packages will be built and installed:
    pkgconf:x64-windows -> 1.8.0#5
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\User\AppData\Local\vcpkg\archives in 82.6 us. Use --debug to see more details.
Installing 1/1 pkgconf:x64-windows...
Building pkgconf:x64-windows...
-- Using cached pkgconf-pkgconf-cef30268e1a3f79efd607c26abcf556aa314c9c4.tar.gz.
-- Cleaning sources at C:/Ochno/instruction and useful materials/vcpkg/buildtrees/pkgconf/src/6aa314c9c4-8bd74a463d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Ochno/instruction and useful materials/vcpkg/downloads/pkgconf-pkgconf-cef30268e1a3f79efd607c26abcf556aa314c9c4.tar.gz
-- Using source at C:/Ochno/instruction and useful materials/vcpkg/buildtrees/pkgconf/src/6aa314c9c4-8bd74a463d.clean
-- Getting CMake variables for x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Ochno/instruction and useful materials/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe" -v
    Working Directory: C:/Ochno/instruction and useful materials/vcpkg/buildtrees/pkgconf/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Ochno\instruction and useful materials\vcpkg\buildtrees\pkgconf\get-cmake-vars-x64-windows-dbg-CMakeCache.txt.log
      C:\Ochno\instruction and useful materials\vcpkg\buildtrees\pkgconf\get-cmake-vars-x64-windows-rel-CMakeCache.txt.log
      C:\Ochno\instruction and useful materials\vcpkg\buildtrees\pkgconf\get-cmake-vars-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:314 (vcpkg_execute_required_process)
  scripts/cmake/z_vcpkg_get_cmake_vars.cmake:18 (vcpkg_configure_cmake)
  scripts/cmake/vcpkg_configure_meson.cmake:317 (z_vcpkg_get_cmake_vars)
  ports/pkgconf/portfile.cmake:9 (vcpkg_configure_meson)
  scripts/ports.cmake:147 (include)

error: building pkgconf:x64-windows failed with: BUILD_FAILED
Elapsed time to handle pkgconf:x64-windows: 1.9 s

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please provide the error log:
```
C:\Ochno\instruction and useful materials\vcpkg\buildtrees\pkgconf\get-cmake-vars-x64-windows-dbg-CMakeCache.txt.log
C:\Ochno\instruction and useful materials\vcpkg\buildtrees\pkgconf\get-cmake-vars-x64-windows-rel-CMakeCache.txt.log
C:\Ochno\instruction and useful materials\vcpkg\buildtrees\pkgconf\get-cmake-vars-x64-windows-out.log
```

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
