### ISSUE TITLE
Metis fails to build x64-linux  

### ISSUE THREAD

**Issue by jma256** [microsoft/vcpkg#3422]
Package: metis:x64-linux   Vcpkg version: 0.0.110-unknownhash

Also from error logs
CMake Error: CMake can not determine linker language for target: cmTC_d529e
CMake Error at GKlib/GKlibSystem.cmake:110 (try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  CMakeLists.txt:16 (include)

**Comment by NancyLi1013** [comment]
Hi @jma256, thanks for posting this issue. This issue has been fixed now. Please try to update this port and use it.
