### ISSUE TITLE
Error: Building package boost-regex:x64-linux failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by nathan-prat** [Microsoft/vcpkg#3424]
Hello,

I can't build get Boost to build as a shared library(on Linux).
I have tried both replacing VCPKG_LIBRARY_LINKAGE to dynamic in `tripets/x64-linux.cmake` and adding a new triplet.
I could be related to  #3373 .

Also, not directly related to this, but I can't get to build shared library on Linux. The built libraries are always static(.a).

[vcpkg_log_boost_fail.txt](https://github.com/Microsoft/vcpkg/files/1974392/vcpkg_log_boost_fail.txt)

**Comment by NancyLi1013** [comment]
Thanks a lot for posting this issue.
Please open a new issue if this is still a problem four you.
