### ISSUE TITLE
[cryptopp] update to 8.9

### ISSUE THREAD

**Issue by Demonslay335** [microsoft/vcpkg#34242]
### Library name

cryptopp

### New version number

8.9

### Other information that may be useful (release notes, etc...)

Crypto++ 8.9 was released on October 1, 2023. The 8.9 release was a minor, unplanned release. There were no CVEs and one memory error.

The 8.9 release was driven by the fix for ProcessData, and the failures when inString==outString. Also see https://github.com/weidai11/cryptopp/issues/1231.

## Release notes
* minor release, recompile of programs required
* expanded community input and support
* 88 unique contributors as of this release
* add additional tests to datatest.cpp
* fix SIMON128 Asan finding on POWER8
* fix AES/CFB and AES/CTR modes self test failures when using Cryptogams AES on ARMv7
* fix ARIA/CTR mode self test failures when inString==outString
* fix HIGHT/CTR mode self test failures when inString==outString
* fix Rabbit/CTR mode self test failures when inString==outString
* fix HC128/CTR and HC256/CTR mode self test failures when inString==outString
* fix Prime Table and dangling reference to a temporary
* fix Singleton::Ref() when using C++11 memory fences
* remove unneeded call to Crop() in Randomize()

**Comment by shijunz** [comment]
Installing 1/1 cryptopp:arm64ec-windows@8.9.0#1...
Building cryptopp:arm64ec-windows@8.9.0#1...
C:\Users\Administrator\Downloads\vcpkg-master\vcpkg-master\triplets\community\arm64ec-windows.cmake: info: loaded community triplet from here. Community triplets are not built in the curated registry and are thus less likely to succeed.
-- Note: cryptopp only supports static library linkage. Building static library.
-- Using cached abdes-cryptopp-cmake-CRYPTOPP_8_9_0.tar.gz.
-- Cleaning sources at C:/Users/Administrator/Downloads/vcpkg-master/vcpkg-master/buildtrees/cryptopp/src/TOPP_8_9_0-6ad2bd2f3d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Administrator/Downloads/vcpkg-master/vcpkg-master/downloads/abdes-cryptopp-cmake-CRYPTOPP_8_9_0.tar.gz
-- Using source at C:/Users/Administrator/Downloads/vcpkg-master/vcpkg-master/buildtrees/cryptopp/src/TOPP_8_9_0-6ad2bd2f3d.clean
-- Using cached weidai11-cryptopp-CRYPTOPP_8_9_0.tar.gz.
-- Cleaning sources at C:/Users/Administrator/Downloads/vcpkg-master/vcpkg-master/buildtrees/cryptopp/src/TOPP_8_9_0-a1a9be497e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Administrator/Downloads/vcpkg-master/vcpkg-master/downloads/weidai11-cryptopp-CRYPTOPP_8_9_0.tar.gz
-- Applying patch patch.patch
-- Applying patch cryptopp.patch
-- Using source at C:/Users/Administrator/Downloads/vcpkg-master/vcpkg-master/buildtrees/cryptopp/src/TOPP_8_9_0-a1a9be497e.clean
-- Found external ninja('1.12.1').
-- Configuring arm64ec-windows
-- Building arm64ec-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/Users/Administrator/Downloads/vcpkg-master/vcpkg-master/downloads/tools/cmake-3.30.1-windows/cmake-3.30.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: C:/Users/Administrator/Downloads/vcpkg-master/vcpkg-master/buildtrees/cryptopp/arm64ec-windows-dbg
    See logs for more information:
      C:\Users\Administrator\Downloads\vcpkg-master\vcpkg-master\buildtrees\cryptopp\install-arm64ec-windows-dbg-out.log

Call Stack (most recent call first):
  installed/arm64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/arm64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/cryptopp/portfile.cmake:75 (vcpkg_cmake_install)[error-logs-arm64ec-windows.txt](https://github.com/user-attachments/files/18104222/error-logs-arm64ec-windows.txt)
[install-arm64ec-windows-dbg-out.log](https://github.com/user-attachments/files/18104221/install-arm64ec-windows-dbg-out.log)
[stdout-arm64ec-windows.log](https://github.com/user-attachments/files/18104223/stdout-arm64ec-windows.log)
and I pass on the arm64 but fail arm64ec, get the bellow error:



C:\PROGRA~1\MICROS~1\2022\COMMUN~1\VC\Tools\MSVC\1442~1.344\bin\HOSTAR~1\arm64\cl.exe   /TP -DCRYPTOPP_DISABLE_ASM=1 -D_WIN32_WINNT=0x0A00 -IC:\Users\Administrator\Downloads\vcpkg-master\vcpkg-master\buildtrees\cryptopp\src\TOPP_8_9_0-a1a9be497e.clean -IC:\Users\Administrator\Downloads\vcpkg-master\vcpkg-master\buildtrees\cryptopp\src /nologo /DWIN32 /D_WINDOWS /utf-8 /GR /EHsc /MP  /arm64EC /D_AMD64_ /DAMD64 /D_ARM64EC_ /DARM64EC /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -MDd /FIwinapifamily.h /showIncludes /Focryptopp\CMakeFiles\cryptopp.dir\__\integer.cpp.obj /Fdcryptopp\CMakeFiles\cryptopp.dir\cryptopp.pdb /FS -c C:\Users\Administrator\Downloads\vcpkg-master\vcpkg-master\buildtrees\cryptopp\src\TOPP_8_9_0-a1a9be497e.clean\integer.cpp
C:\Users\Administrator\Downloads\vcpkg-master\vcpkg-master\buildtrees\cryptopp\src\TOPP_8_9_0-a1a9be497e.clean\integer.cpp(1302): error C3861: '__shiftleft128': identifier not found
C:\Users\Administrator\Downloads\vcpkg-master\vcpkg-master\buildtrees\cryptopp\src\TOPP_8_9_0-a1a9be497e.clean\integer.cpp(1310): error C3861: '__shiftleft128': identifier not found
C:\Users\Administrator\Downloads\vcpkg-master\vcpkg-master\buildtrees\cryptopp\src\TOPP_8_9_0-a1a9be497e.clean\integer.cpp(1318): error C3861: '__shiftleft128': identifier not found
C:\Users\Administrator\Downloads\vcpkg-master\vcpkg-master\buildtrees\cryptopp\src\TOPP_8_9_0-a1a9be497e.clean\integer.cpp(1432): error C3861: '__shiftleft128': identifier not found
[5/154] C:\PROGRA~1\MICROS~1\2022\COMMUN~1\VC\Tools\MSVC\1442~1.344\bin\HOSTAR~1\arm64\cl.exe   /TP -DCRYPTOPP_DISABLE_ASM=1 -D_WIN32_WINNT=0x0A00
