### ISSUE TITLE
Enable port updates for outdated library versions

### ISSUE THREAD

**Issue by WKarel** [microsoft/vcpkg#34259]
### Discussed in https://github.com/microsoft/vcpkg/discussions/34241

<div type='discussions-op-text'>

<sup>Originally posted by **WKarel** October  3, 2023</sup>
I'd like to build Python 3.10 (on Windows x64 using MSVC 2019), while my built-in baseline has its Python version set to [3.11](https://github.com/microsoft/vcpkg/blob/38dd6b15ada368740b5047e4282cbd8395228f03/versions/baseline.json#L6680), already. I expected Python 3.10 to build nevertheless, using the following manifest:
`
{
  "dependencies": [ "python3" ],
  "overrides": [ { "name": "python3", "version": "3.10.7#7" } ],
  "builtin-baseline": "38dd6b15ada368740b5047e4282cbd8395228f03"
}
` 
However, this fails, because libffi's port [has been changed](https://github.com/microsoft/vcpkg/commit/edd3db2e3be3967073756cc83cd500135eaaae69) to produce "ffi.lib" insted of "libffi.lib" on Windows since the most recent port version (`#7`) for Python 3.10 has been released. A simple fix would be to apply the [changes to the port for Python 3.11](https://github.com/microsoft/vcpkg/commit/edd3db2e3be3967073756cc83cd500135eaaae69#diff-f682e6e46ef0d0dae2ceba81d191975da58a84cbdab4811a0e84683442265461) in that same commit also to port `#7` for Python 3.10, and commit that as port `#8` for Python 3.10.

But it seems to me that a minimalistic manifest
`{
  "dependencies": [ "python3" ]
}
`
without explicit baseline and version override simply uses what is there in ports/python3, instead of checking out the according git tree into buildtrees/versioning_/versions/python3/<hash>, as is done when using version overrides. So even for Python 3.11+, the revision of the port for Python 3.10 would be used.

Is it possible at all to update ports of "outdated" package versions? If so, how? Would a pull request be welcome?

Note that I am aware of alternatives to successfully build Python 3.10 (lower baseline and/or version override also for libffi).</div>

According to the linked discussion and my observations, it is currently impossible to update a port for a version of a library that is older than the one that vcpkg currently considers as baseline AND push the respective commit to the vcpkg repository. The problem I see is that if a manifest does not define a `builtin-baseline` (and when using classic mode?), then vcpkg does not check out the respective git tree into `buildtrees/versioning_/versions/<portname>/<hash>` (as is done when the manifest defines a `builtin-baseline`), but vcpkg then simply uses the contents of `ports/<portname>` of HEAD. Hence, when a port update for an outdated library were pushed into vcpkg, then other users whose manifests do not define a ``builtin-baseline` (or use classic mode?) would use the updated port of the outdated library version, too.

**Comment by Pospelove** [comment]
I'm not sure I fully understand the context, but here are possible workarounds:

- it should be possible to explicitly specify both Python and libffi versions. So you can use an older libffi version as well.
- you could make an overlay_ports directory in your project repo and use your own python/libffi ports (copied from vcpkg and patched)
- same as №2 but with custom vcpkg registry

**Comment by WKarel** [comment]
Thanks, I am aware of these work-arounds, which work for me locally.

But I am seeking for modifications such that an updated port for the now outdated Python 3.10 can be merged upstream. Users could then use the current vcpkg baseline to build Python 3.10 only by overriding the version for python3, but without overriding the version of libffi. Or is that out of the scope of vcpkg/vcpkg-tool?

How to create an updated port is documented. But if I follow these instructions to update the port for the now outdated Python 3.10, and the respective commit were merged into upstream vcpkg, then it seems to me that users that do not specify a `builtin-baseline` in their manifests would accidentally use my port for the outdated Python 3.10, instead of the existing port for Python 3.11. 

My guess is that vcpkg-tool would need to be changed such that it always checks out the respective git tree for the requested port, even if users do not specify a builtin-baseline.

**Comment by WKarel** [comment]
What works without modifications to vcpkg-tool is to commit an updated port for the outdated library version into its own branch, and reference the respective git-tree in the version database on the master branch:

1. Lookup the git-tree of the most recent port (7) of the outdated library version (3.10.7) in versions/p-/python3.json:
    ```
    {
      "git-tree": "a0f1ead9323b9521f3c3016469f028be712c0252",
      "version": "3.10.7",
      "port-version": 7
    }
    ```

2. Find the commit that added the git-tree above:
    ```
    $ git log --all --find-object=a0f1ead9323b9521f3c3016469f028be712c0252
    ...
    commit f84c18b6a5fb31983853b0d481b9de0263d6fc6c
    ```

3. Create and checkout a branch based on that commit:
    ```
    $ git checkout -b python3_3.10.7 f84c18b6a5fb31983853b0d481b9de0263d6fc6c
    ```

4. Apply the necessary changes:
    a. Edit ports/python3/portfile.cmake: replace `find_library(... libffi ...)` with `find_library(... ffi ...)`
    b. Edit ports/python3/vcpkg.json: increment the port version to 8

5. Commit these changes to the (non-master-) branch:
    ```
    $ git add .
    $ git commit -m "updated python 3.10 to match current libffi baseline"
    ```

6. Find the git-tree to be used in the version database:
    ```
    $ git rev-parse HEAD:ports/python3
    8b717a0b2a896832a1bf318a2e36ac4b6adf475a
    ```
7. Checkout the master branch, again:
    ```
    $ git checkout master
    ```
8. Edit versions/p-/python3.json: insert the updated port with the git-tree from above:
    ```
    {
      "git-tree": "8b717a0b2a896832a1bf318a2e36ac4b6adf475a",
      "version": "3.10.7",
      "port-version": 8
    },
    ```

9. Commit these changes to the master branch:
    ```
    git add .
    git commit -m "updated python 3.10 to match current libffi baseline"
    ```

Now to successfully build Python 3.10, it is enough to override the version of the `python3` port with "3.10.7#8" in a manifest. No more need to use a lower baseline (resulting in all ports being outdated), or to override the appropriate port version of `libffi` (which is not easy to find out).

Also, this should be acceptable as pull request for the upstream repository here, because the contents of  `ports/python3` are unchanged on the master branch. Hence, projects that use the contents of the port directory right away (because they do not define a baseline in their manifest, or when using classic mode), continue to use the latest port version of the current Python version, as defined in `versions/baseline.json`.

Still, would such a pull request be welcome? Does it fit into the idea of vcpkg about versioning (maintaining outdated library versions)? Is such a port-specific branch in the upstream repository acceptable?

**Comment by FrankXie05** [comment]
This issue hasn’t been updated for a long time; if it is still an issue, please ping me and I will reopen this issue.
