### ISSUE TITLE
new port pr check problem

### ISSUE THREAD

**Issue by nocanstillbb** [microsoft/vcpkg#34251]
### Discussed in https://github.com/microsoft/vcpkg/discussions/34250

<div type='discussions-op-text'>

<sup>Originally posted by **nocanstillbb** October  4, 2023</sup>
after i check step run `vcpkg x-add-version --all` 
>d:\source\repos\vcpkg>vcpkg.exe x-add-version --all
error: can't load port cpprestsdk
error: while loading D:\source\repos\vcpkg\ports\cpprestsdk\vcpkg.json:
$.default-features[0]: mismatched type: expected an identifierinternal error: D:\a\_work\1\s\src\vcpkg\commands.add-version.cpp(412): vcpkg has crashed; no additional details are available.
Please open an issue at https://github.com/microsoft/vcpkg/issues/new?template=other-type-of-bug-report.md&labels=category:vcpkg-bug with detailed steps to reproduce the problem.

I have not modified cpprestsdk, why does this error occur?
my pr at : https://github.com/microsoft/vcpkg/pull/34249
</div>

**Comment by autoantwort** [comment]
Try update your vcpkg-tool version by running `git pull` + `./bootstrap-vcpkg.bat`

**Comment by nocanstillbb** [comment]
> Try update your vcpkg-tool version by running `git pull` + `./bootstrap-vcpkg.bat`

```bash
kokbi@DESKTOP-E31FB3M MINGW64 /d/source/repos/vcpkg (master)
$ git remote -vv
hbb     git@github.com:nocanstillbb/vcpkg.git (fetch)
hbb     git@github.com:nocanstillbb/vcpkg.git (push)
ms      git@github.com:microsoft/vcpkg.git (fetch)
ms      git@github.com:microsoft/vcpkg.git (push)

kokbi@DESKTOP-E31FB3M MINGW64 /d/source/repos/vcpkg (master)
$ git fetch  ms master
From github.com:microsoft/vcpkg
 * branch                master     -> FETCH_HEAD

kokbi@DESKTOP-E31FB3M MINGW64 /d/source/repos/vcpkg (master)
$ git rebase ms/master
Current branch master is up to date.
```

**Comment by nocanstillbb** [comment]
> what is the result of `vcpkg.exe --version` ?

```bash
kokbi@DESKTOP-E31FB3M MINGW64 /d/source/repos/vcpkg (master)
$ ./vcpkg.exe  --version
vcpkg package management program version 2023-06-15-8c254a5fb6c503615834fc66bd0717664a339a2e

See LICENSE.txt for license information.

```

**Comment by autoantwort** [comment]
According to https://github.com/microsoft/vcpkg/pull/34249/files because the files are already there
