### ISSUE TITLE
[sfml] build failure

### ISSUE THREAD

**Issue by iamcharanrajjj** [microsoft/vcpkg#34260]
### Operating system

Debian 6.5.3-1kali2 (2023-10-03) x86_64 GNU/Linux

### Compiler

GCC

### Steps to reproduce the behavior

```Shell
./vcpkg install sfml glm glew tclap --triplet=x64-linux
```

### Failure logs

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/sfml/portfile.cmake:28 (vcpkg_cmake_install)
  scripts/ports.cmake:168 (include)

error: building sfml:x64-linux failed with: BUILD_FAILED
Elapsed time to handle sfml:x64-linux: 7.1 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.                                                                      
Then check for known issues at:                                              
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+sfml                                                                        
You can submit a new issue at:                                               
  https://github.com/microsoft/vcpkg/issues/new?title=[sfml]+Build+error&body=Copy+issue+body+from+%2Fhome%2Fkali%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by Cheney-W** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report an issue.
