### ISSUE TITLE
[libiffi] build failure

### ISSUE THREAD

**Issue by niclar** [microsoft/vcpkg#34261]
### Operating system

linux

### Compiler

clang

### Steps to reproduce the behavior

```Shell
using vcpkg master, HEAD 20231004, commit be2d7f886aad895e282b59088a2dfca5f6e1c88a,
clang 17.0.2, stdc++

export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
export CXXFLAGS=-stdlib=libc++
export LDFLAGS=-fuse-ld=lld

./vcpkg install libffi:x64-linux
```

### Failure logs

`cat /mnt/c/src/thirdparty/vcpkg/buildtrees/libffi/build-x64-linux-dbg-err.log
./../src/libffi-3-84fbdc7636.clean/src/java_raw_api.c:328:46: warning: 'ffi_java_raw_size' is deprecated [-Wdeprecated-declarations]
  328 |   ffi_java_raw *raw = (ffi_java_raw*)alloca (ffi_java_raw_size (cif));
      |                                              ^
include/ffi.h:326:56: note: 'ffi_java_raw_size' has been explicitly marked deprecated here
  326 | size_t ffi_java_raw_size (ffi_cif *cif) __attribute__((deprecated));
      |                                                        ^
./../src/libffi-3-84fbdc7636.clean/src/java_raw_api.c:331:3: warning: 'ffi_java_ptrarray_to_raw' is deprecated [-Wdeprecated-declarations]
  331 |   ffi_java_ptrarray_to_raw (cif, avalue, raw);
      |   ^
include/ffi.h:322:93: note: 'ffi_java_ptrarray_to_raw' has been explicitly marked deprecated here
  322 | void ffi_java_ptrarray_to_raw (ffi_cif *cif, void **args, ffi_java_raw *raw) __attribute__((deprecated));
      |                                                                                             ^
2 warnings generated.
./../src/libffi-3-84fbdc7636.clean/src/tramp.c:262:22: error: call to undeclared function 'open_temp_exec_file'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  262 |   tramp_globals.fd = open_temp_exec_file ();
      |                      ^
1 error generated.
make[2]: *** [Makefile:1320: src/tramp.lo] Error 1
make[2]: *** Waiting for unfinished jobs....`

**Comment by niclar** [comment]
fixed by declaring the function

`--- a/src/tramp.c	Wed Oct  4 16:38:04 2023
+++ b/src/tramp.c	Wed Oct  4 16:40:40 2023
@@ -255,2 +255,4 @@
 
+int open_temp_exec_file (void);
+
 static int
`

**Comment by dg0yt** [comment]
https://github.com/libffi/libffi/pull/764/files
