### ISSUE TITLE
[New Port Request] <xalan-c>

### ISSUE THREAD

**Issue by Molliqaj** [microsoft/vcpkg#34278]
### Library name

xalan-c

### Source repository URL

https://github.com/apache/xalan-c

### Project homepage (if different from the source repository)

https://github.com/microsoft/vcpkg

**Comment by dg0yt** [comment]
I'm afraid it won't come. It was delisted in vcpkg on upstream reuest (https://github.com/microsoft/vcpkg/pull/27401). Old port versions are still available in manifest mode (i.e. in vcpkg git history).
Similar: https://github.com/microsoft/vcpkg/issues/30719.
