### ISSUE TITLE
[azure-core] build failure with gcc 13

### ISSUE THREAD

**Issue by nrgiii** [microsoft/vcpkg#34272]
### Operating system

Linux (gentoo)

### Compiler

gcc 13.2.1

### Steps to reproduce the behavior

```Shell
git clone https://github.com/microsoft/vcpkg
./vcpkg/bootstrap-vcpkg.sh
/vcpkg/vcpkg install azure-core-cpp
```

### Failure logs

`Building azure-core-cpp[core,curl,http]:x64-linux...
-- Downloading https://github.com/Azure/azure-sdk-for-cpp/archive/azure-core_1.10.2.tar.gz -> Azure-azure-sdk-for-cpp-azure-core_1.10.2.tar.gz...
-- Extracting source /hey1/users/normg/vcpkg/downloads/Azure-azure-sdk-for-cpp-azure-core_1.10.2.tar.gz
-- Using source at /hey1/users/normg/vcpkg/buildtrees/azure-core-cpp/src/ore_1.10.2-d563a045e8.clean
-- Found external ninja('1.11.1').
-- Configuring x64-linux
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: /hey1/users/normg/vcpkg/downloads/tools/cmake-3.27.1-linux/cmake-3.27.1-linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j9
    Working Directory: /hey1/users/normg/vcpkg/buildtrees/azure-core-cpp/x64-linux-dbg
    See logs for more information:
      /hey1/users/normg/vcpkg/buildtrees/azure-core-cpp/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/azure-core-cpp/portfile.cmake:33 (vcpkg_cmake_install)
  scripts/ports.cmake:168 (include)

error: building azure-core-cpp:x64-linux failed with: BUILD_FAILED
Elapsed time to handle azure-core-cpp:x64-linux: 2.8 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+azure-core-cpp
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[azure-core-cpp]+Build+error&body=Copy+issue+bo
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/12810977/install-x64-linux-dbg-out.log)
dy+from+%2Fhey1%2Fusers%2Fnorm`

### Additional context

azure-core fails to build on gentoo linux with gcc 13. Builds on the same host with gcc 12 succeed. Adding this line:

`#include <stdint.h>`

to these two files

`sdk/core/azure-core/inc/azure/core/base64.hpp`
`sdk/core/azure-core/inc/azure/core/uuid.hpp`

fixes the problem.

**Comment by ahsonkhan** [comment]
@nrgii we are having trouble reproducing (and testing the fix). Could you provide some steps on repro-ing this issue? Is this occurring only on the gentoo distro, or on any platform that uses the gcc 13.2.1 compiler? How do I setup a gentoo environment myself?


Is there a version of compiler on godbolt that can repro the issue? I tried arm64 gcc 13.1.0 with this sample and it compiles:
```C++
#include <cstdint>

int main() {
    int8_t sum = 0;
    return 0;
} 
```

Lastly, does this issue only occur on installing `azure-core-cpp`?
