### ISSUE TITLE
On harfbuzz package install in vcpkg, ERROR: fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by oliVRqin** [microsoft/vcpkg#34295]
**How to reproduce issue:**

**Try to install with following commands in the command line:** 
git clone https://github.com/microsoft/vcpkg
cd vcpkg
.\bootstrap-vcpkg.bat
.\vcpkg install colmap[cuda]:x64-windows

@FrankXie05, I was able to reproduce this issue and have the exact same error as @LarsLive. I'm using the command line on Windows

Based on the log file (package-x64-windows-dbg-out.log), the final message was this:

C:\vcpkg\buildtrees\harfbuzz\src\8.2.1-63f9ae7085.clean\src\hb-subset.cc : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj
ninja: build stopped: subcommand failed.

Tracing this error type leads to this document (https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1128?view=msvc-170), seems like the solution is, in their words:

"To correct this error, divide your source file into multiple source code files, compile without /Gy, or compile with [/bigobj (Increase Number of Sections in .Obj file)](https://learn.microsoft.com/en-us/cpp/build/reference/bigobj-increase-number-of-sections-in-dot-obj-file?view=msvc-170). If you do not compile with /Gy, you will need to specify the optimizations individually, since /O2 and /O1 both imply /Gy."

Don't have time for a fix at the moment, could this get raised?

**Comment by FrankXie05** [comment]
If there are no special instructions, we should restore this patch.
https://github.com/microsoft/vcpkg/pull/26229/files#:~:text=)-,%2Bextra_hb_cpp_args%20%3D%20%5B%5D,%2B,-hb_subset_headers%20%3D%20files(

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This issue has been fixed in PR #34346, so I am closing this issue for now.
