### ISSUE TITLE
[<OpenSSL>] build failure

### ISSUE THREAD

**Issue by hqho** [microsoft/vcpkg#34294]
Package: openssl:x64-linux -> 1.1.1

**Host Environment**

- Host: x64-linux
- Compiler: GNU 9.3.1
-    vcpkg-tool version: 2023-08-09-9990a4c9026811a312cb2af78bf77f3d9d288416
    vcpkg-scripts version: 7827a2a05 2023-10-05 (32 minutes ago)

**To Reproduce**

`vcpkg install `
**Failure logs**

```
-- Downloading https://github.com/openssl/openssl/archive/openssl-1.1.1.tar.gz -> openssl-openssl-openssl-1.1.1.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from /var/opt/teradata/jenkins/vcpkg/vcpkg-bundle.json
[DEBUG] Failed to open: /var/opt/teradata/jenkins/vcpkg/vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
[DEBUG] 1000: popen( curl --fail -L https://github.com/openssl/openssl/archive/openssl-1.1.1.tar.gz --create-dirs --output /home/jenkins/vcpkg/downloads/openssl-openssl-openssl-1.1.1.tar.gz.17136.part 2>&1)
[DEBUG] 1000: cmd_execute_and_stream_data() returned 22 after   602036 us
error: Failed to download from mirror set
error: https://github.com/openssl/openssl/archive/openssl-1.1.1.tar.gz: curl failed to download with exit code 22
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed


curl: (22) The requested URL returned error: 404


[DEBUG] /mnt/vss/_work/1/s/src/vcpkg/base/downloads.cpp(1053): 
[DEBUG] Time in subprocesses: 602036us
[DEBUG] Time in parsing JSON: 3us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 256us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 603 ms (602621us)

CMake Error at /home/jenkins/vcpkg/scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
      

Call Stack (most recent call first):
  /home/jenkins/vcpkg/scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  /home/jenkins/vcpkg/scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  /home/jenkins/vcpkg/overlay-ports/openssl/portfile.cmake:18 (vcpkg_from_github)
  /home/jenkins/vcpkg/scripts/ports.cmake:168 (include)



```
**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "name": "google-cloud-cpp-development",
  "version": "2.16.0",
  "description": "Describes the vcpkg dependencies for vcpkg development.",
  "homepage": "https://github.com/googleapis/google-cloud-cpp",
  "license": "Apache-2.0",
  "supports": "!uwp",
  "dependencies": [
    "abseil",
    "crc32c",
    {
      "name": "curl",
      "features": [
        "ssl"
      ]
    },
    {
      "$description": "If cross-compiling, we need the gRPC protoc plugin on the 'host' environment.",
      "name": "grpc",
      "host": true
    },
    {
      "$description": "If cross-compiling, we need the protoc compiler on the 'host' environment.",
      "name": "protobuf",
      "host": true
    },
    "grpc",
    "protobuf",
    "nlohmann-json",
    "benchmark",
    "gtest",
    {
      "$description": "Only used for the opentelemetry feature.",
      "name": "opentelemetry-cpp"
    },
    {
      "$description": "Only used for the docfx feature.",
      "name": "pugixml"
    },
    {
      "$description": "Only used for the docfx feature.",
      "name": "yaml-cpp"
    }
  ]
}

```
</details>

**Comment by dg0yt** [comment]
OpenSSL 1.1.1, really? It is five years old.
I wouldn't expect a fix to the old port version, but the URL really doesn't work. There is https://github.com/openssl/openssl/archive/refs/tags/OpenSSL_1_1_1.tar.gz, but probably with a different SHA512.

**Comment by hqho** [comment]
I am getting the following build error after fixing the version number:

Package: openssl:x64-linux -> 1.1.1q

**Host Environment**

- Host: x64-linux
- Compiler: GNU 9.3.1
-    vcpkg-tool version: 2023-08-09-9990a4c9026811a312cb2af78bf77f3d9d288416
    vcpkg-scripts version: 7827a2a05 2023-10-05 (2 hours ago)

**To Reproduce**

`vcpkg install `
**Failure logs**

```
-- Downloading https://www.openssl.org/source/openssl-1.1.1q.tar.gz;https://www.openssl.org/source/old/1.1.1/openssl-1.1.1q.tar.gz -> openssl-1.1.1q.tar.gz...
openssl requires Linux kernel headers from the system package manager.
   They can be installed on Alpine systems via `apk add linux-headers`.
   They can be installed on Ubuntu systems via `apt install linux-libc-dev`.

CMake Error at /home/jenkins/vcpkg/overlay-ports/openssl/unix/portfile.cmake:33 (vcpkg_cmake_get_vars):
  Unknown CMake command "vcpkg_cmake_get_vars".
Call Stack (most recent call first):
  /home/jenkins/vcpkg/overlay-ports/openssl/portfile.cmake:24 (include)
  /home/jenkins/vcpkg/scripts/ports.cmake:168 (include)



```
**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "name": "google-cloud-cpp-development",
  "version": "2.16.0",
  "description": "Describes the vcpkg dependencies for vcpkg development.",
  "homepage": "https://github.com/googleapis/google-cloud-cpp",
  "license": "Apache-2.0",
  "supports": "!uwp",
  "dependencies": [
    "abseil",
    "crc32c",
    {
      "name": "curl",
      "features": [
        "ssl"
      ]
    },
    {
      "$description": "If cross-compiling, we need the gRPC protoc plugin on the 'host' environment.",
      "name": "grpc",
      "host": true
    },
    {
    {
      "$description": "If cross-compiling, we need the protoc compiler on the 'host' environment.",
      "name": "protobuf",
      "host": true
    },
    "grpc",
    "protobuf",
    "nlohmann-json",
    "benchmark",
    "gtest",
    {
      "$description": "Only used for the opentelemetry feature.",
      "name": "opentelemetry-cpp"
    },
    {
      "$description": "Only used for the docfx feature.",
      "name": "pugixml"
    },
    {
      "$description": "Only used for the docfx feature.",
      "name": "yaml-cpp"
    }
  ]
}

```
</details>

**Comment by dg0yt** [comment]
Your installed ports are outdated, too. In classic mode, check the impact with
~~~
./vcpkg upgrade
~~~
and do the actual reinstallation with
~~~
./vcpkg upgrade --no-dry-run
~~~
In manifest mode, update you baseline, and pin openssl with an override.

**Comment by hqho** [comment]
I am using manifest mode.  I am not sure how to update the baseline and pin the openssl with an override.  Can you tell me how to do this?

**Comment by dg0yt** [comment]
I think you need to start with this documentation page:
https://learn.microsoft.com/en-us/vcpkg/consume/lock-package-versions

**Comment by hqho** [comment]
I am getting the following error when I tried to force openssl version 1.1.1
-- Running vcpkg install
error: no version database entry for openssl at 1.1.1.
Available versions:
    3.1.2#1
    3.1.2
    3.1.1#1
    3.1.1
    3.1.0#4
    3.1.0#3
    3.1.0#2
    3.1.0#1
    3.1.0
    3.0.8#2
    3.0.8#1
    3.0.8
    3.0.7#2
    3.0.7#1
    3.0.7
    3.0.5#5
    3.0.5#4
    3.0.5#3
    3.0.5#2
    3.0.5#1
    3.0.5
    3.0.4
    3.0.3#2
    3.0.3#1
    3.0.3
    3.0.2#3
    3.0.2#2
    3.0.2#1
    3.0.2
    1.1.1n#1
    1.1.1n
    1.1.1m#2
    1.1.1m#1
    1.1.1m
    1.1.1l#4
    1.1.1l#3
    1.1.1l#2
    1.1.1l#1
    1.1.1l
    1.1.1k#8
    1.1.1k#7
    1.1.1k#6
    1.1.1k#5
    1.1.1k#4
    1.1.1k#3
    1.1.1k#2
    1.1.1k#1
    1.1.1k
    1.1.1j#2
    1.1.1j#1
    1.1.1j
    1.1.1i
    1.1.1h#5
    1.1.1h#4
    1.1.1h#3
    1.1.1h#2
    1.1.1h#1
    1.1.1g#1
    1.1.1g
    1.1.1d
    1
    0
    1.0.2o-3
    1.0.2o-2
    1.0.2o-1
    1.0.2o
    1.0.2n-3
    1.0.2n-2
    1.0.2n-1
    1.0.2n
    1.0.2m
    1.0.2l-3
    1.0.2l-2
    1.0.2l-1
    1.0.21-1
    1.0.2k-5
    1.0.2k-4
    1.0.2k-3
    1.0.2k-2
    1.0.2k-1
    1.0.2j-2
    1.0.2j-1
    1.0.2j
    1.0.2h-1
    1.0.2j
    1.0.2h-1
    1.0.2h
See `vcpkg help versioning` or https://learn.microsoft.com/vcpkg/users/versioning for more information.
note: updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
-- Running vcpkg install - failed
CMake Error at /home/jenkins/vcpkg/scripts/buildsystems/vcpkg.cmake:895 (message):
  vcpkg install failed.  See logs for more information:
  /home/jenkins/google-cloud-cpp/cmake-out/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/share/cmake/Modules/CMakeDetermineSystem.cmake:123 (include)
  CMakeLists.txt:22 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

Updated vcpkg.json with openssl 1.1.1n and get the following failure:

-- Running vcpkg install
error: while loading /home/jenkins/google-cloud-cpp/vcpkg.json:
$.overrides[0] (an override): error: `1.1.1n` is not a valid relaxed version (semver with arbitrary numeric element count).Extended documentation available at 'https://learn.microsoft.com/vcpkg/users/manifests'.
-- Running vcpkg install - failed
CMake Error at /home/jenkins/vcpkg/scripts/buildsystems/vcpkg.cmake:895 (message):
  vcpkg install failed.  See logs for more information:
  /home/jenkins/google-cloud-cpp/cmake-out/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/share/cmake/Modules/CMakeDetermineSystem.cmake:123 (include)
  CMakeLists.txt:22 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

[vcpkg.json.txt](https://github.com/microsoft/vcpkg/files/12842431/vcpkg.json.txt)

**Comment by dg0yt** [comment]
> CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles". CMAKE_MAKE_PROGRAM is not set. You probably need to select a different build tool.

Install `make` with your system package manager.

**Comment by hqho** [comment]
I think the problem is this failure:

$.overrides[0] (an override): error: 1.1.1n is not a valid relaxed version (semver with arbitrary numeric element count).Extended documentation available at 'https://learn.microsoft.com/vcpkg/users/manifests'.
-- Running vcpkg install - failed

The build work fine with 3.0.x, but not any of the 1.1.1<x> since it's not a relaxed version.  Not sure how to get around this.

**Comment by dg0yt** [comment]
According the vcpkg.json docs, the override spec must use the same version-scheme as the requested version, and `1.1.1n` is `version-string`.
https://learn.microsoft.com/en-us/vcpkg/reference/vcpkg-json#example-of-version-overrides

~~~diff
   "overrides": [
     {
       "name": "openssl",
-      "version": "1.1.1n"
+      "version-string": "1.1.1n"
     }
~~~

**Comment by hqho** [comment]
Thanks! This works.

**Comment by PhoebeHui** [comment]
Thanks @dg0yt! and Good to know the problem has been solved.
