### ISSUE TITLE
sync git ref and vcpkg.json from port's git repostory

### ISSUE THREAD

**Issue by nocanstillbb** [microsoft/vcpkg#34297]
### Is your feature request related to a problem? Please describe.

```cmake
vcpkg_from_github(
  OUT_SOURCE_PATH SOURCE_PATH
  REPO nocanstillbb/prism
    REF b9a1ce36948a02058be3bd57d64953bc6cfabf3e
  SHA512 12b26fa97cfbf0227a7dc057f100ff79df23880d1522aeed02e939fb6c9afccb092a264d78c08702dfb7cc30701d4ea48d9bdea29168be5751c8965e2011fb0d
  HEAD_REF master
)
```
each time i change prism repos code,  if i want to update vcpkg ports, It will be a complicated process

### Proposed solution

as we see, we have branch name master. full path of git repostroy url.
 should have a command such like `vcpkg x-sync-port  prism`  to auto update prism repo's master branch the best newst ref to ***ports/prism/portfile.cmake***, and cp -f  master:vcpkg.json to  ***ports/prism/vcpkg.json***,

then i only to do is , git commit -am "[prism] update port"   && vcpkg x-add-version --all && git commit -m "[prism] update versions" && git push.

**Comment by nocanstillbb** [comment]
also `vcpkg_from_git`

**Comment by FrankXie05** [comment]
@nocanstillbb Thanks for the advice. :)
But what we want is a stable release. And if possible a semantic release version number rather than a master commit.

**Comment by FrankXie05** [comment]
We're currently trying to make the update process as simple as possible. For example, the added `${VERSION}` function.

**Comment by nocanstillbb** [comment]
> We're currently trying to make the update process as simple as possible. For example, the added `${VERSION}` function.

Is there a document? I want to learn, but I can't find the relevant information

**Comment by FrankXie05** [comment]
@nocanstillbb All vcpkg related documents are here: https://github.com/microsoft/vcpkg-docs :)
