### ISSUE TITLE
vcpkg installs poco c++ but can't use in IDEs on Windows 10

### ISSUE THREAD

**Issue by STashakkori** [microsoft/vcpkg#34319]
Hello. Followed instructions to install vcpkg and configure to use with these three IDEs:
Visual Studio, VSCode, and Clion

Path to vcpkg.cmake is correct and running 'vcpkg list' I get:
C:\vcpkg>vcpkg.exe list
expat:x64-windows                                 2.5.0#3             XML parser library written in C
pcre2:x64-windows                                 10.42#1             Regular Expression pattern matching using the sa...
pcre2[jit]:x64-windows                                                Enable support for Just-In-Time compiling regex ...
pcre2[platform-default-features]:x64-windows                          Enable default features
poco:x64-windows                                  1.12.4#4            Modern, powerful open source C++ class libraries...
vcpkg-cmake-config:x64-windows                    2022-02-06#1
vcpkg-cmake:x64-windows                           2023-05-04
zlib:x64-windows                                  1.3                 A compression library

So package is obviously there. But I always get an error like this when trying to build:
fatal error: Poco/DateTimeFormatter.h: No such file or directory
    3 | #include <Poco/DateTimeFormatter.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

I've tried also with Visual Studio and MinGW toolchains and tried changing architectures from amd64 to x86 etc

Not sure why this isn't working. CMakeLists.txt file has these lines in it:
find_package(Poco REQUIRED)
target_link_libraries(EmbedNet PRIVATE Poco::Foundation)

Please advise

**Comment by FrankXie05** [comment]
Please try this `find_package(POCO REQUIRED)`
```
find_package(Poco REQUIRED)
```

**Comment by STashakkori** [comment]
Thank you Frank. Just tried POCO, Poco, and poco in all three IDEs with no success.

Open to more suggestions. Wondering if Poco c++ is incompatible with vcpkg

**Comment by dg0yt** [comment]
> Not sure why this isn't working. CMakeLists.txt file has these lines in it:
> find_package(Poco REQUIRED)

`Poco` need at least one component, otherwise it prints an error here. You probably want
~~~cmake
find_package(Poco REQUIRED Foundation)
~~~

> target_link_libraries(EmbedNet PRIVATE Poco::Foundation)

Is `EmbeddedNet` the target which compiles the failing source? It would be good to see the full command line.

I cannot reproduce the error with
~~~cmake
cmake_minimum_required(VERSION 3.16)
project("test")
add_library(main main.cpp)
find_package(Poco REQUIRED Foundation)
target_link_libraries(main PRIVATE Poco::Foundation)
~~~
main.cpp
~~~C++
#include <Poco/DateTimeFormatter.h>
~~~

**Comment by STashakkori** [comment]
I'm not building a library though. So the code builds when I change add_executable to add_library it builds with no errors but I need this to work as an executable. When I follow your exact steps, substituting main with EmbedNet, my arbitrary name for my code here, I no longer get the can't find headers error I posted above. So you have gotten me farther along I think

However, I do get this one new error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'PocoUtild.lib'	source\repos\EmbedNet\out\build\x64-debug\EmbedNet	source\repos\EmbedNet\out\build\x64-debug\EmbedNet\LINK	1

Also, I have this line added in my CMakePresets.json:
    "configurePresets": [
        {
            "name": "windows-base",
            "hidden": true,
            "generator": "Ninja",
            "binaryDir": "${sourceDir}/out/build/${presetName}",
            "installDir": "${sourceDir}/out/install/${presetName}",
          "cacheVariables": {
            "CMAKE_C_COMPILER": "cl.exe",
            "CMAKE_CXX_COMPILER": "cl.exe",
            "CMAKE_TOOLCHAIN_FILE": "C:/vcpkg/scripts/buildsystems/vcpkg.cmake"         <----- Added this *****
          },
          
Path is correct there but not sure if this is the way to add the toolchain file in Visual Studio 2022. This IDE does not have the CMakeSettings.json nor does it have project properties for cmake projects so theres not much applicable documentation. Trying my best here

Sorry for all the trouble my friends and thank you for the help with this
