### ISSUE TITLE
[dbus] Build error

### ISSUE THREAD

**Issue by kaomoneus** [microsoft/vcpkg#34329]
Package: dbus:x64-linux -> 1.15.8

**Host Environment**

- Host: x64-linux
- Compiler: GNU 10.2.1
-    vcpkg-tool version: 2023-09-15-ac02a9f660977426b8ec6392919fbb1d51b10998
    vcpkg-scripts version: cc97b45 2023-10-06 (16 hours ago)

**To Reproduce**
*(issue_body is too long, please find it in attachment)*
[vcpkg-sdl2-failure.md](https://github.com/microsoft/vcpkg/files/12838217/vcpkg-sdl2-failure.md)

**Long story short**
Start new docker container with following command:

```
docker run -ti quay.io/pypa/manylinux2014_x86_64 bash
```

NOTE: command above uses latest version of manylinux_2014_x86_64, consider using direct
image ID, which is 43f32dc5292e

Inside docker container run following commands:

```bash
yum install -y zip wget
git clone --depth=1 https://github.com/microsoft/vcpkg /vcpkg
cd /vcpkg
./bootstrap-vcpkg.sh -disableMetrics
./vcpkg install sdl2 # BOOM
```

**Comment by dg0yt** [comment]
~~~
-- Configuring done (13.2s)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
X11_Xdmcp_LIB (ADVANCED)
    linked by target "dbus-launch" in directory /vcpkg/buildtrees/dbus/src/bus-1.15.8-4cdd406cc7.clean/tools

-- Generating done (0.0s)
~~~
Hm, this port seems to ask for some X libs. But it shouldn't. The feature control history points at me, #27425 :facepalm:

**Comment by kaomoneus** [comment]
@dg0yt, it seems that sdl2 uses dbus, and dbus uses Xdmcp...

**Comment by glx22** [comment]
sdl2 requires dbus since #34013

**Comment by dg0yt** [comment]
Please test #34332.

**Comment by glx22** [comment]
#34332 works for me
