### ISSUE TITLE
[qt5-base] Build error

### ISSUE THREAD

**Issue by MagicianWu** [microsoft/vcpkg#34324]
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /home/jiaqi/software/vcpkg/buildtrees/qt5-base/src/5.15.11-13623e1e19.clean/configure -confirm-license -opensource -verbose -system-zlib -system-libjpeg -system-libpng -system-freetype -system-pcre -system-doubleconversion -system-sqlite -system-harfbuzz -no-angle -no-glib -openssl-linked -no-sql-psql -no-sql-mysql --vulkan=no -no-icu -fontconfig -xcb-xlib -xcb -linuxfb -nomake examples -nomake tests -static LIBJPEG_LIBS=/home/jiaqi/software/vcpkg/installed/x64-linux/debug/lib/libjpeg.a ZLIB_LIBS=/home/jiaqi/software/vcpkg/installed/x64-linux/debug/lib/libz.a "LIBPNG_LIBS=/home/jiaqi/software/vcpkg/installed/x64-linux/debug/lib/libpng16d.a /home/jiaqi/software/vcpkg/installed/x64-linux/debug/lib/libz.a" PCRE2_LIBS=/home/jiaqi/software/vcpkg/installed/x64-linux/debug/lib/libpcre2-16.a "FREETYPE_LIBS=/home/jiaqi/software/vcpkg/installed/x64-linux/debug/lib/libfreetyped.a /home/jiaqi/software/vcpkg/installed/x64-linux/debug/lib/libbz2d.a /home/jiaqi/software/vcpkg/installed/x64-linux/debug/lib/libpng16d.a /home/jiaqi/software/vcpkg/installed/x64-linux/debug/lib/libz.a /home/jiaqi/software/vcpkg/installed/x64-linux/debug/lib/libbrotlidec.a /home/jiaqi/software/vcpkg/installed/x64-linux/debug/lib/libbrotlicommon.a" QMAKE_LIBS_PRIVATE+=/home/jiaqi/software/vcpkg/installed/x64-linux/debug/lib/libbz2d.a "QMAKE_LIBS_PRIVATE+=/home/jiaqi/software/vcpkg/installed/x64-linux/debug/lib/libpng16d.a /home/jiaqi/software/vcpkg/installed/x64-linux/debug/lib/libz.a" QMAKE_LIBS_PRIVATE+=/home/jiaqi/software/vcpkg/installed/x64-linux/debug/lib/libzstd.a "SQLITE_LIBS=/home/jiaqi/software/vcpkg/installed/x64-linux/debug/lib/libsqlite3.a -ldl -lpthread" "HARFBUZZ_LIBS=-lharfbuzz -lm -lfreetyped -lbz2d -lpng16d -lz -lbrotlidec -lbrotlicommon -lm" "OPENSSL_LIBS=/home/jiaqi/software/vcpkg/installed/x64-linux/debug/lib/libssl.a /home/jiaqi/software/vcpkg/installed/x64-linux/debug/lib/libcrypto.a -ldl -lpthread" "FONTCONFIG_LIBS=/home/jiaqi/software/vcpkg/installed/x64-linux/debug/lib/libfontconfig.a /home/jiaqi/software/vcpkg/installed/x64-linux/debug/lib/libfreetyped.a /home/jiaqi/software/vcpkg/installed/x64-linux/debug/lib/libexpat.a -luuid" -debug -prefix /home/jiaqi/software/vcpkg/installed/x64-linux -hostprefix /home/jiaqi/software/vcpkg/installed/x64-linux/tools/qt5/debug -hostlibdir /home/jiaqi/software/vcpkg/installed/x64-linux/tools/qt5/debug/lib -hostbindir /home/jiaqi/software/vcpkg/installed/x64-linux/tools/qt5/debug/bin -archdatadir /home/jiaqi/software/vcpkg/installed/x64-linux/tools/qt5/debug -datadir /home/jiaqi/software/vcpkg/installed/x64-linux/share/qt5/debug -plugindir /home/jiaqi/software/vcpkg/installed/x64-linux/debug/plugins -qmldir /home/jiaqi/software/vcpkg/installed/x64-linux/debug/qml -headerdir /home/jiaqi/software/vcpkg/installed/x64-linux/include/qt5 -libexecdir /home/jiaqi/software/vcpkg/installed/x64-linux/tools/qt5/debug -bindir /home/jiaqi/software/vcpkg/installed/x64-linux/debug/bin -libdir /home/jiaqi/software/vcpkg/installed/x64-linux/debug/lib -I /home/jiaqi/software/vcpkg/installed/x64-linux/include -I /home/jiaqi/software/vcpkg/installed/x64-linux/include/qt5 -L /home/jiaqi/software/vcpkg/installed/x64-linux/debug/lib -L /home/jiaqi/software/vcpkg/installed/x64-linux/debug/lib/manual-link -platform linux-g++ QMAKE_CC=cc QMAKE_CXX=c++ QMAKE_AR=ar QMAKE_RANLIB=ranlib QMAKE_STRIP=strip QMAKE_NM=nm QMAKE_RC= QMAKE_MT= QMAKE_AR+=qc QMAKE_LINK=c++ QMAKE_LINK_SHLIB=c++ QMAKE_LINK_C=cc QMAKE_LINK_C_SHLIB=cc "QMAKE_CFLAGS_DEBUG+=-fPIC -g" "QMAKE_CXXFLAGS_DEBUG+=-fPIC -g"
    Working Directory: /home/jiaqi/software/vcpkg/buildtrees/qt5-base/x64-linux-dbg
    Error code: 3
    See logs for more information:
      /home/jiaqi/software/vcpkg/buildtrees/qt5-base/config-x64-linux-dbg-out.log
      /home/jiaqi/software/vcpkg/buildtrees/qt5-base/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  ports/qt5-base/cmake/configure_qt.cmake:186 (vcpkg_execute_required_process)
  ports/qt5-base/portfile.cmake:392 (configure_qt)
  scripts/ports.cmake:168 (include)

error: building qt5-base:x64-linux failed with: BUILD_FAILED

**Comment by Adela0814** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report an issue.

**Comment by Adela0814** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
