### ISSUE TITLE
[libspatialite] Build error

### ISSUE THREAD

**Issue by RetroFuturism7** [microsoft/vcpkg#34331]
Copy issue body from H:/C++/vcpkg/installed/vcpkg/issue_body.md

**Comment by RetroFuturism7** [comment]
![image](https://github.com/microsoft/vcpkg/assets/127582048/02b59cf0-fc29-4225-a904-f609f3ddff0c)

**Comment by RetroFuturism7** [comment]
**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.37.32824.0
- vcpkg-tool version: 2023-08-09-9990a4c9026811a312cb2af78bf77f3d9d288416
  vcpkg-scripts version: unknown

**To Reproduce**

`vcpkg install gdal:x64-windows`
**Failure logs**
-- Using cached libspatialite-5.0.1.tar.gz.
-- Cleaning sources at H:/C++/vcpkg/buildtrees/libspatialite/src/atialite-5-bc39e08d26.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source H:/C++/vcpkg/downloads/libspatialite-5.0.1.tar.gz
-- Applying patch fix-makefiles.patch
-- Applying patch fix-linux-configure.patch
-- Applying patch gaiaconfig-msvc.patch
-- Applying patch fix-mingw.patch
-- Using source at H:/C++/vcpkg/buildtrees/libspatialite/src/atialite-5-bc39e08d26.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Building and installing x64-windows-dbg
-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: H:/vs2022/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/nmake.exe /NOLOGO /G /U /F makefile.vc all install INSTALLDIR=H:\\C++\\vcpkg\\packages\\libspatialite_x64-windows\\debug "CL_FLAGS= /IH:/C++/vcpkg/installed/x64-windows/debug/../include /IH:/C++/vcpkg/installed/x64-windows/debug/../include/libxml2" INST_DIR=H:\\\\C++\\\\vcpkg\\\\packages\\\\libspatialite_x64-windows\\debug "LIBS_ALL=/LIBPATH:H:/C++/vcpkg/installed/x64-windows/debug/lib /libpath:H:/C++/vcpkg/installed/x64-windows/debug/lib geos_c.lib libxml2.lib /libpath:H:/C++/vcpkg/installed/x64-windows/debug/lib /libpath:H:/C++/vcpkg/installed/x64-windows/debug/lib zlibd.lib proj_d.lib /libpath:H:/C++/vcpkg/installed/x64-windows/debug/lib tiffd.lib /libpath:H:/C++/vcpkg/installed/x64-windows/debug/lib /libpath:H:/C++/vcpkg/installed/x64-windows/debug/lib jpeg.lib lzma.lib libcurl-d.lib sqlite3.lib zlibd.lib freexl.lib iconv.lib charset.lib iconv.lib charset.lib" LINK_FLAGS=/debug
    Working Directory: H:/C++/vcpkg/buildtrees/libspatialite/x64-windows-dbg
    See logs for more information:
      H:\C++\vcpkg\buildtrees\libspatialite\install-x64-windows-dbg-nmake-out.log
      H:\C++\vcpkg\buildtrees\libspatialite\install-x64-windows-dbg-nmake-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_nmake.cmake:156 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_nmake.cmake:52 (vcpkg_build_nmake)
  ports/libspatialite/portfile.cmake:83 (vcpkg_install_nmake)
  scripts/ports.cmake:147 (include)

**Comment by dg0yt** [comment]
> Working Directory: H:/C++/vcpkg/buildtrees/libspatialite/x64-windows-dbg

Start again in a path without `+`. It is a special character for regular expression and for plain DOS `copy`.

**Comment by jimwang118** [comment]
You can try rebuilding under a path without the "++" symbol.

**Comment by RetroFuturism7** [comment]
Indeed, it is the problem you mentioned. Thank you very much!
