### ISSUE TITLE
[pybind11] Py_DEBUG is defined, while interpreter does not support debug modules.

### ISSUE THREAD

**Issue by se7kn8** [microsoft/vcpkg#34338]
**Describe the bug**
When building a python module with `pybind11` in `Debug` configuration, the wrong symbols are linked into the modules.
This bug occurs under the following conditions:
 - The python interpreter that is used for compilation/linkage does not have debug features (check via [this method](https://stackoverflow.com/questions/646518/python-how-to-detect-debug-interpreter))
 - The module is compiled using a `Debug` configuration
 - Now, when building the module the wrong symbols are used, since vcpkg always sets `Py_DEBUG` to true ([since this PR](https://github.com/microsoft/vcpkg/pull/31318))

**Environment**
- OS: Linux - Fedora 38
- Compiler: gcc (GCC) 13.2.1 20230728 (Red Hat 13.2.1-1)
- Python: Python 3.11.5 (Non Debug Build, important!)

**To Reproduce**
Build a python module using pybind11 in debug configuration. The system python interpreter does not support any 

**Expected behavior**
A python module build in `Debug`-Configuration and with a non-Debug System interpreter should work.

**Failure logs**
When importing the module the following errors get thrown by the python interpreter
`ImportError: undefined symbol: _Py_RefTotal`

**Additional context**
By create a custom port of vcpkg without [this patch](https://github.com/microsoft/vcpkg/pull/31318) everything worked as expected. Maybe it would be a solution to only apply this patch on windows?

**Comment by FrankXie05** [comment]
cc @Osyotr

**Comment by Osyotr** [comment]
> Maybe it would be a solution to only apply this patch on windows?

That would be reasonable

**Comment by RealLitb** [comment]
Here we have a similar issue. We use the pybind11::embed target (no module, just embedding the interpreter).

I checked the build output from my colleague. We build in CMAKE_BUILD_TYPE=Debug, but it links against "vcpkg_installed/x64-linux-dynamic/lib/libpython3.11.so" instead of "vcpkg_installed/x64-linux-dynamic/lib/debug/libpython3.11d.so" and fails with above linker error too. I recommended to my colleague to disable the pybind11 python handling, and instead explicitly link against the Python::Python target. And then re-check things.

**Comment by RealLitb** [comment]
> Linux here, not Windows: We have a similar issue. We use the pybind11::embed target (no module, just embedding the interpreter).
> 
> I checked the build output from my colleague. We build in CMAKE_BUILD_TYPE=Debug, but it links against "vcpkg_installed/x64-linux-dynamic/lib/libpython3.11.so" instead of "vcpkg_installed/x64-linux-dynamic/lib/debug/libpython3.11d.so" and fails with above linker error too. I recommended to my colleague to disable the pybind11 python handling, and instead explicitly link against the Python::Python target. And then re-check things. Pybind11 does not appear to use "Python::" targets, but instead relies on find-module variables like PYHON_LIBRARIES. IMO this complicates the already complicated situation.
> 
> Maybe you have an idea, otherwise I will deep dive into the corresponding files to find the bug.
> 
> EDIT: What I said above about pybind11 using the variables instead of target based programming is _incorrect_. It has two modes, and in the modern mode, it actually uses the targets like Python::Python etc. So the bug maybe is in the find_python modules.. Will continue reporting here!

I now posted the narrowed-down reason in a separate issue report: https://github.com/microsoft/vcpkg/issues/34678
