### ISSUE TITLE
[gettext] Build error

### ISSUE THREAD

**Issue by BaiDXia** [microsoft/vcpkg#34349]
Copy issue body from /home/user/USER/vcpkg-master/installed/vcpkg/issue_body.md

**Comment by Adela0814** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report an issue.

**Comment by Adela0814** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
