### ISSUE TITLE
LNK2038: `MT_StaticRelease` doesn't match `MD_DynamicRelease` in main.obj

### ISSUE THREAD

**Issue by HappySeaFox** [microsoft/vcpkg#34355]
**Describe the bug**

**Environment**
- OS: Windows 7 x64
- Compiler: MSVC 2019
- vcpkg: 2023.08.09

**To Reproduce**
1. vcpkg install sail --triplet x64-windows-static
2. Compile the following client application:

```CMake
cmake_minimum_required(VERSION 3.12)

project(sail-test)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

add_executable(sail-test main.cpp)

find_package(SailC++ REQUIRED)
target_link_libraries(sail-test SAIL::sail-c++)
```

```C++
#include <string>
#include <sail-c++/sail-c++.h>

int main(int argc, char *argv[])
{
    std::string path = "F:/images/1.bmp";
    sail::image image(path);
    return 0;
}
```

```
cd build
cmake -DCMAKE_TOOLCHAIN_FILE=F:/projects/git.vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_BUILD_TYPE=Release ..
cmake --build . --config Release
```

**Failure logs**
<details>
  <summary>ERROR LOG</summary>
Microsoft (R) Build Engine версии 16.11.2+f32259642 для .NET Framework
(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

sail-c++.lib(image-c++.cpp.obj) : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MT_StaticRelease" не соответствует значению "MD_DynamicRelease" в main.obj [F:\projects\git.sail-test\build\sail-test.vcxproj]
sail-c++.lib(ostream-c++.cpp.obj) : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MT_StaticRelease" не соответствует значению "MD_DynamicRelease" в main.obj [F:\projects\git.sail-test\build\sail-test.vcxproj]
sail-c++.lib(conversion_options-c++.cpp.obj) : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MT_StaticRelease" не соответствует значению "MD_DynamicRelease" в main.obj [F:\projects\git.sail-test\build\sail-test.vcxproj]
sail-c++.lib(iccp-c++.cpp.obj) : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MT_StaticRelease" не соответствует значению "MD_DynamicRelease" в main.obj [F:\projects\git.sail-test\build\sail-test.vcxproj]
sail-c++.lib(palette-c++.cpp.obj) : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MT_StaticRelease" не соответствует значению "MD_DynamicRelease" в main.obj [F:\projects\git.sail-test\build\sail-test.vcxproj]
sail-c++.lib(source_image-c++.cpp.obj) : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MT_StaticRelease" не соответствует значению "MD_DynamicRelease" в main.obj [F:\projects\git.sail-test\build\sail-test.vcxproj]
sail-c++.lib(resolution-c++.cpp.obj) : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MT_StaticRelease" не соответствует значению "MD_DynamicRelease" в main.obj [F:\projects\git.sail-test\build\sail-test.vcxproj]
sail-c++.lib(image_input-c++.cpp.obj) : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MT_StaticRelease" не соответствует значению "MD_DynamicRelease" в main.obj [F:\projects\git.sail-test\build\sail-test.vcxproj]
sail-c++.lib(image_output-c++.cpp.obj) : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MT_StaticRelease" не соответствует значению "MD_DynamicRelease" в main.obj [F:\projects\git.sail-test\build\sail-test.vcxproj]
sail-c++.lib(meta_data-c++.cpp.obj) : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MT_StaticRelease" не соответствует значению "MD_DynamicRelease" в main.obj [F:\projects\git.sail-test\build\sail-test.vcxproj]
sail-c++.lib(save_features-c++.cpp.obj) : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MT_StaticRelease" не соответствует значению "MD_DynamicRelease" в main.obj [F:\projects\git.sail-test\build\sail-test.vcxproj]
sail-c++.lib(cmake_pch.cxx.obj) : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MT_StaticRelease" не соответствует значению "MD_DynamicRelease" в main.obj [F:\projects\git.sail-test\build\sail-test.vcxproj]
sail-c++.lib(variant-c++.cpp.obj) : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MT_StaticRelease" не соответствует значению "MD_DynamicRelease" в main.obj [F:\projects\git.sail-test\build\sail-test.vcxproj]
sail-c++.lib(utils_private-c++.cpp.obj) : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MT_StaticRelease" не соответствует значению "MD_DynamicRelease" в main.obj [F:\projects\git.sail-test\build\sail-test.vcxproj]
sail-c++.lib(codec_info-c++.cpp.obj) : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MT_StaticRelease" не соответствует значению "MD_DynamicRelease" в main.obj [F:\projects\git.sail-test\build\sail-test.vcxproj]
sail-c++.lib(abstract_io_adapter-c++.cpp.obj) : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MT_StaticRelease" не соответствует значению "MD_DynamicRelease" в main.obj [F:\projects\git.sail-test\build\sail-test.vcxproj]
sail-c++.lib(io_file-c++.cpp.obj) : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MT_StaticRelease" не соответствует значению "MD_DynamicRelease" в main.obj [F:\projects\git.sail-test\build\sail-test.vcxproj]
sail-c++.lib(io_memory-c++.cpp.obj) : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MT_StaticRelease" не соответствует значению "MD_DynamicRelease" в main.obj [F:\projects\git.sail-test\build\sail-test.vcxproj]
sail-c++.lib(load_options-c++.cpp.obj) : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MT_StaticRelease" не соответствует значению "MD_DynamicRelease" в main.obj [F:\projects\git.sail-test\build\sail-test.vcxproj]
sail-c++.lib(save_options-c++.cpp.obj) : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MT_StaticRelease" не соответствует значению "MD_DynamicRelease" в main.obj [F:\projects\git.sail-test\build\sail-test.vcxproj]
sail-c++.lib(compression_level-c++.cpp.obj) : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MT_StaticRelease" не соответствует значению "MD_DynamicRelease" в main.obj [F:\projects\git.sail-test\build\sail-test.vcxproj]
sail-c++.lib(load_features-c++.cpp.obj) : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MT_StaticRelease" не соответствует значению "MD_DynamicRelease" в main.obj [F:\projects\git.sail-test\build\sail-test.vcxproj]
sail-c++.lib(io_base-c++.cpp.obj) : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MT_StaticRelease" не соответствует значению "MD_DynamicRelease" в main.obj [F:\projects\git.sail-test\build\sail-test.vcxproj]
msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: int __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::sputc(char)" (?sputc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHD@Z) уже определен в sail-c++.lib(ostream-c++.cpp.obj) [F:\projects\git.sail-test\build\sail-test.vcxproj]
msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: __int64 __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::sputn(char const *,__int64)" (?sputn@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAA_JPEBD_J@Z) уже определен в sail-c++.lib(ostream-c++.cpp.obj) [F:\projects\git.sail-test\build\sail-test.vcxproj]
msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: void __cdecl std::basic_ios<char,struct std::char_traits<char> >::setstate(int,bool)" (?setstate@?$basic_ios@DU?$char_traits@D@std@@@std@@QEAAXH_N@Z) уже определен в sail-c++.lib(ostream-c++.cpp.obj) [F:\projects\git.sail-test\build\sail-test.vcxproj]
msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: void __cdecl std::basic_ostream<char,struct std::char_traits<char> >::_Osfx(void)" (?_Osfx@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAXXZ) уже определен в sail-c++.lib(ostream-c++.cpp.obj) [F:\projects\git.sail-test\build\sail-test.vcxproj]
msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::basic_ostream<char,struct std::char_traits<char> >::flush(void)" (?flush@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV12@XZ) уже определен в sail-c++.lib(ostream-c++.cpp.obj) [F:\projects\git.sail-test\build\sail-test.vcxproj]
     Создается библиотека F:/projects/git.sail-test/build/Release/sail-test.lib и объект F:/projects/git.sail-test/build/Release/sail-test.exp
LINK : warning LNK4098: библиотека по умолчанию "LIBCMT" конфликтует с использованием других библиотек; используйте /NODEFAULTLIB:library [F:\projects\git.sail-test\build\sail-test.vcxproj]
F:\projects\git.sail-test\build\Release\sail-test.exe : fatal error LNK1169: обнаружен многократно определенный символ - один или более [F:\projects\git.sail-test\build\sail-test.vcxproj]
</details>

It seems that the client application is compiled with `/MD` for some reason.

The following workaround helps, but it's just a workaround:

```CMake
if (POLICY CMP0091)
    cmake_policy(SET CMP0091 NEW) 
endif()

...

set_property(TARGET sail-test PROPERTY
        MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
```

**Comment by Osyotr** [comment]
> The following workaround helps, but it's just a workaround

No it's not. It's either this or you provide a custom toolchain file with /MT(d) to be used by both vcpkg and your project.

**Comment by FrankXie05** [comment]
@HappySeaFox Could you please make sure your Runtime Library is set to the correct `/MT` or `/MD`?
![image](https://github.com/microsoft/vcpkg/assets/65999885/d9519279-df73-44f0-bbda-1f1c55aa6deb)

**Comment by HappySeaFox** [comment]
I'm not an expert with MSVC, but I was totally sure that when I use CMake only to compile an app without the MSVS UI (`cmake --build . --config Release`) CMake or vcpkg handles this flag automatically somehow. Please correct me if I'm wrong. If I'm wrong and this flag was always needed for static builds, this would be a big surprise for me :confused:

**Comment by FrankXie05** [comment]
I believe it will be handled automatically if you don't actively specify it. `-config Release`

**Comment by HappySeaFox** [comment]
I've just figured out when CMake handles this automatically. This happens when I compile my CMake project (which contains libs and executables) with `-DBUILD_SHARED_LIBS=OFF` against vcpkg `x64-windows` triplet for example. CMake is smart enough to compile internal executables with `/MT` in this case.

But when I try to link my project against vcpkg `x64-windows-static`, the linking process fails.

**Comment by dg0yt** [comment]
> I've just figured out when CMake handles this automatically. This happens when I compile my CMake project (which contains libs and executables) with `-DBUILD_SHARED_LIBS=OFF` against vcpkg `x64-windows` triplet for example. CMake is smart enough to compile internal executables with `/MT` in this case.

There isn't much automatic except always assuming `x64-windows` on x64 Windows when it isn't already given.
Maybe the toolchain should consider `CMAKE_MSVC_RUNTIME_LIBRARY`.
