### ISSUE TITLE
[pcl] build failure

### ISSUE THREAD

**Issue by lalagis** [microsoft/vcpkg#34352]
### Operating system

macosx

### Steps to reproduce the behavior

```Shell
./vcpkg install pcl[visualization]
```

### Failure logs

zsh: no matches found: pcl[visualization]

### Additional context

`./vcpkg install pcl` is fine, how can I install the pcl visualization?

**Comment by dg0yt** [comment]
> zsh: no matches found: pcl[visualization]

Know you shell (`zsh`). Write `vcpkg install 'pcl[visualization]'`

**Comment by lalagis** [comment]
work, thx.
