### ISSUE TITLE
plplot build failure

### ISSUE THREAD

**Issue by tschoonj** [microsoft/vcpkg#34357]
### Operating system

macOS

### Compiler

clang

### Steps to reproduce the behavior

```Shell
`./vcpkg install plplot`
```

### Failure logs

error: Failed to download from mirror set
error: https://sourceforge.net/projects/plplot/files/plplot/5.15.0 Source/plplot-5.15.0.tar.gz/download: curl failed to download with exit code 3
curl: (3) URL rejected: Malformed input to a URL function

error: https://sourceforge.net/projects/plplot/files/plplot/5.15.0 Source/plplot-5.15.0.tar.gz/download?use_mirror=cfhcable: curl failed to download with exit code 3
curl: (3) URL rejected: Malformed input to a URL function

error: https://sourceforge.net/projects/plplot/files/plplot/5.15.0 Source/plplot-5.15.0.tar.gz/download?use_mirror=pilotfiber: curl failed to download with exit code 3
curl: (3) URL rejected: Malformed input to a URL function

error: https://sourceforge.net/projects/plplot/files/plplot/5.15.0 Source/plplot-5.15.0.tar.gz/download?use_mirror=gigenet: curl failed to download with exit code 3
curl: (3) URL rejected: Malformed input to a URL function

error: https://sourceforge.net/projects/plplot/files/plplot/5.15.0 Source/plplot-5.15.0.tar.gz/download?use_mirror=versaweb: curl failed to download with exit code 3
curl: (3) URL rejected: Malformed input to a URL function

error: https://sourceforge.net/projects/plplot/files/plplot/5.15.0 Source/plplot-5.15.0.tar.gz/download?use_mirror=ayera: curl failed to download with exit code 3
curl: (3) URL rejected: Malformed input to a URL function

error: https://sourceforge.net/projects/plplot/files/plplot/5.15.0 Source/plplot-5.15.0.tar.gz/download?use_mirror=netactuate: curl failed to download with exit code 3
curl: (3) URL rejected: Malformed input to a URL function

error: https://sourceforge.net/projects/plplot/files/plplot/5.15.0 Source/plplot-5.15.0.tar.gz/download?use_mirror=phoenixnap: curl failed to download with exit code 3
curl: (3) URL rejected: Malformed input to a URL function

error: https://sourceforge.net/projects/plplot/files/plplot/5.15.0 Source/plplot-5.15.0.tar.gz/download?use_mirror=astuteinternet: curl failed to download with exit code 3
curl: (3) URL rejected: Malformed input to a URL function

error: https://sourceforge.net/projects/plplot/files/plplot/5.15.0 Source/plplot-5.15.0.tar.gz/download?use_mirror=freefr: curl failed to download with exit code 3
curl: (3) URL rejected: Malformed input to a URL function

error: https://sourceforge.net/projects/plplot/files/plplot/5.15.0 Source/plplot-5.15.0.tar.gz/download?use_mirror=netcologne: curl failed to download with exit code 3
curl: (3) URL rejected: Malformed input to a URL function

error: https://sourceforge.net/projects/plplot/files/plplot/5.15.0 Source/plplot-5.15.0.tar.gz/download?use_mirror=deac-riga: curl failed to download with exit code 3
curl: (3) URL rejected: Malformed input to a URL function

error: https://sourceforge.net/projects/plplot/files/plplot/5.15.0 Source/plplot-5.15.0.tar.gz/download?use_mirror=excellmedia: curl failed to download with exit code 3
curl: (3) URL rejected: Malformed input to a URL function

error: https://sourceforge.net/projects/plplot/files/plplot/5.15.0 Source/plplot-5.15.0.tar.gz/download?use_mirror=iweb: curl failed to download with exit code 3
curl: (3) URL rejected: Malformed input to a URL function

error: https://sourceforge.net/projects/plplot/files/plplot/5.15.0 Source/plplot-5.15.0.tar.gz/download?use_mirror=jaist: curl failed to download with exit code 3
curl: (3) URL rejected: Malformed input to a URL function

error: https://sourceforge.net/projects/plplot/files/plplot/5.15.0 Source/plplot-5.15.0.tar.gz/download?use_mirror=jztkft: curl failed to download with exit code 3
curl: (3) URL rejected: Malformed input to a URL function

error: https://sourceforge.net/projects/plplot/files/plplot/5.15.0 Source/plplot-5.15.0.tar.gz/download?use_mirror=managedway: curl failed to download with exit code 3
curl: (3) URL rejected: Malformed input to a URL function

error: https://sourceforge.net/projects/plplot/files/plplot/5.15.0 Source/plplot-5.15.0.tar.gz/download?use_mirror=nchc: curl failed to download with exit code 3
curl: (3) URL rejected: Malformed input to a URL function

error: https://sourceforge.net/projects/plplot/files/plplot/5.15.0 Source/plplot-5.15.0.tar.gz/download?use_mirror=netix: curl failed to download with exit code 3
curl: (3) URL rejected: Malformed input to a URL function

error: https://sourceforge.net/projects/plplot/files/plplot/5.15.0 Source/plplot-5.15.0.tar.gz/download?use_mirror=ufpr: curl failed to download with exit code 3
curl: (3) URL rejected: Malformed input to a URL function

error: https://sourceforge.net/projects/plplot/files/plplot/5.15.0 Source/plplot-5.15.0.tar.gz/download?use_mirror=tenet: curl failed to download with exit code 3
curl: (3) URL rejected: Malformed input to a URL function

**Comment by JonLiu1993** [comment]
This issue could be reproduced with vcpkg 2023-09-15-ac02a9f660977426b8ec6392919fbb1d51b10998
