### ISSUE TITLE
SDL 2 Vulkan support

### ISSUE THREAD

**Issue by xgalaxy** [Microsoft/vcpkg#3435]
Pretty new to vcpkg. Going over docs there doesn’t appear to be a way to override cmake configurations. For some reason Vulkan support is explicitly disabled in the SDL2 port.

How can I enable it?

Thanks.

**Comment by past-due** [comment]
Can we please make this a feature? (vcpkg port FEATURES is available. For an example, see libcurl's port: [CONTROL](https://github.com/Microsoft/vcpkg/blob/master/ports/curl/CONTROL) & [portfile.cmake](https://github.com/Microsoft/vcpkg/blob/master/ports/curl/portfile.cmake).)

**Comment by cwfitzgerald** [comment]
This can most likely be closed via #5374
