### ISSUE TITLE
[minhook] Build error

### ISSUE THREAD

**Issue by aemiks666** [microsoft/vcpkg#34395]
Copy issue body from C:/Users/kacper/vcpkg/installed/vcpkg/issue_body.md

**Comment by JonLiu1993** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report an issue.

**Comment by JonLiu1993** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
