### ISSUE TITLE
Several packages fail to build on arm-windows

### ISSUE THREAD

**Issue by carlo-bramini** [microsoft/vcpkg#3439]
I tried to build some software for arm-windows and I found that some of the required libraries cannot be compiled. At the moment, these are the ones that I have found, but probably there are also others:

curl
fluidsynth
gettext
glib
libffi
mpir
openal-soft
openssl (see also #2971)
pcre
sdl2
sdl2-net

**Comment by paulmon** [comment]
libffi still fails to build with arm-windows.  Any updates?

**Comment by janisozaur** [comment]
curl fluidsynth libffi sdl2 sdl2-net
at least those packages build fine on arm**64**-windows now, no idea about arm-windows

Others likely build too already.

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated more than 3 months, if it is still an issue, please reopen this issue.
