### ISSUE TITLE
[Fontconfig]Release library can't locate program input point

### ISSUE THREAD

**Issue by RikiLee** [microsoft/vcpkg#34390]
The x64 debug library is okay, but when I compiler my program using the release library and run the app, a run time error appears and it shows: can't locate program input point FT_GET_BDF_Property in fontconfig-1.dll. 

**Environment**
- OS: Windows 11
- Compiler: MSVC 2022 

**To Reproduce**
1. ./vcpkg install fontconfig:x64-windows

**Expected behavior**

**Failure logs**
can't locate program input point FT_GET_BDF_Property in fontconfig-1.dll. 

**Additional context**
I already installed fontconfig and freetype, the Debug libs are fine! I'm sure I've set the right environment.

**Comment by RikiLee** [comment]
#include <iostream>
#include <fontconfig/fontconfig.h>

bool getFontFace(const std::string& utf8FontName, const int weight)
{
	FcPattern* pattern = FcPatternCreate();
	FcPatternAddString(pattern, FC_FAMILY, (FcChar8*)utf8FontName.c_str());
	if (weight >= 500)
	{
		FcPatternAddString(pattern, FC_STYLE, (FcChar8*)"bold");
	}
	FcConfigSubstitute(NULL, pattern, FcMatchPattern);
	FcDefaultSubstitute(pattern);

	FcResult result;
	std::string fontfile;
	FcPattern* patfont = FcFontMatch(NULL, pattern, &result);
	int fontfaceIndex{};
	if (patfont)
	{
		FcChar8* file = nullptr;
		if (FcPatternGetString(patfont, FC_FILE, 0, &file) == FcResultMatch)
		{
			fontfile = reinterpret_cast<char*>(file);
		}
		FcPatternGetInteger(patfont, FC_INDEX, 0, &fontfaceIndex);
		FcPatternDestroy(patfont);
	}
	if (fontfile.empty())
		return false;
	std::cout << fontfile << std::endl;
	return true;
}

int main()
{
	FcInit();

	if (!getFontFace("Times New Roman", 400)) 
	{
		std::cout << "Can't get the font file!" << std::endl;
	}
	return 0;
}

**Comment by jimwang118** [comment]
I used the code you provided and then compiled it using `cmake`, and the compilation result was correct.
```
cmakelists.txt
add_executable (testfontconfig "testfontconfig.cpp" "testfontconfig.h")
find_package(Fontconfig REQUIRED) # since CMake 3.14
target_link_libraries(testfontconfig PRIVATE Fontconfig::Fontconfig)
```

**Comment by RikiLee** [comment]
It can be compiled correctly. The problem is when I use the release mode to run the application, a run time error occurs: can't locate program input point.
![image](https://github.com/microsoft/vcpkg/assets/21985815/3cb1254b-46ff-453d-97b3-0b7281aa11f8)
The debug mode can run correctly.

**Comment by jimwang118** [comment]
The results of running my local program are as follows. 
![image](https://github.com/microsoft/vcpkg/assets/122244446/8559aa5e-1485-4e15-a6b1-400f79e05772)

You can try to delete the installed `fontconfig` and then reinstall it. Or re-clone `vcpkg `and use your test code to compile.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
