### ISSUE TITLE
Building package hunspell:x64-linux failed

### ISSUE THREAD

**Issue by CJCombrink** [microsoft/vcpkg#3440]
I am getting the following when trying to install hunspell:
```
CMake Error at ports/hunspell/portfile.cmake:38 (file):
  file must be called with at least two arguments.
Call Stack (most recent call first):
  scripts/ports.cmake:72 (include)

Error: Building package hunspell:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: hunspell:x64-linux
  Vcpkg version: 0.0.110-unknownhash
```
I have just cloned the vcpkg repo thus it should be up to date: 
vcpkg commit 1c49195f789b7b8d7eaeb2542730a1f72cfbefcf
Ubuntu 18.04

**Comment by sanxiyn** [comment]
The particular problem ("must be called with at least two arguments") is fixed, but hunspell:x64-linux still fails to build. Relevant log:

```
/usr/bin/ld: hunspell.cxx:(.text+0x15b0): undefined reference to `echo'
/usr/bin/ld: hunspell.cxx:(.text+0x15b7): undefined reference to `stdscr'
/usr/bin/ld: hunspell.cxx:(.text+0x15c7): undefined reference to `wgetnstr'
/usr/bin/ld: hunspell.cxx:(.text+0x15cc): undefined reference to `noecho'
```

**Comment by NancyLi1013** [comment]
Hi @CJCombrink , @sanxiyn,  thanks for posting this issue .Does this issue still exist on your machine now? I can install it successfully on my machine. Please provide the reproduce step and attach the detail logs.

**Comment by sanxiyn** [comment]
Yes, the problem still reproduces, with the same log. Steps to reproduce: run "./vcpkg install hunspell".

**Comment by NancyLi1013** [comment]
@sanxiyn, thanks for your quick reply. Here are my test results:

vruil@vruil001:~/vcpkg/vcpkg$ ./vcpkg install hunspell
The following packages will be built and installed:
    hunspell[core]:x64-linux
Starting package 1/1: hunspell:x64-linux
Building package hunspell[core]:x64-linux...
-- Using cached /home/vruil/vcpkg/vcpkg/downloads/hunspell-hunspell-v1.7.0.tar.gz
-- Using source at /home/vruil/vcpkg/vcpkg/buildtrees/hunspell/src/v1.7.0-658f8373e7
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package hunspell[core]:x64-linux... done
Installing package hunspell[core]:x64-linux...
Installing package hunspell[core]:x64-linux... done
Elapsed time for package hunspell:x64-linux: 10.44 s

Total elapsed time: 10.44 s
I install it on Ubuntu 16.04 with the latest vcpkg 2018.11.23-unknownhash. And the port hunspell has been updated to 1.7.0. Please help check these info and try it again. Thank you very much for your patience.

**Comment by NancyLi1013** [comment]
Update this port to the latest version and try it again. Please open a new issue if this is still a problem for you.
