### ISSUE TITLE
 Building package cuda:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by gaaguile** [Microsoft/vcpkg#3441]
Package: cuda:x64-windows
  Vcpkg version: 0.0.110-2018-05-04-ab58f531ccf6da9895502cb8ae7bd85b29823d1d

PS C:\src\vcpkg> ./vcpkg install cuda x64-windows
Error: Unable to install default features because can't find CONTROL for x64-windows:x86-windows
PS C:\src\vcpkg> ./vcpkg install cuda:x64-windows
The following packages will be built and installed:
    cuda[core]:x64-windows
Starting package 1/1: cuda:x64-windows
Building package cuda[core]:x64-windows...
A suitable version of git was not found (required v2.17.0). Downloading portable git v2.17.0...
-- CURRENT_INSTALLED_DIR=C:/src/vcpkg/installed/x64-windows
-- DOWNLOADS=C:/src/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/src/vcpkg/packages/cuda_x64-windows
-- CURRENT_BUILDTREES_DIR=C:/src/vcpkg/buildtrees/cuda
-- CURRENT_PORT_DIR=C:/src/vcpkg/ports/cuda
-- Found CUDA V8.0.60
CMake Error at ports/cuda/portfile.cmake:43 (message):
  CUDA V8.0.60 but V9.0.0 is required.  Please download and install a more
  recent version of CUDA from:

      https://developer.nvidia.com/cuda-downloads

Call Stack (most recent call first):
  scripts/ports.cmake:72 (include)

**Comment by Voskrese** [comment]
CUDA V8.0.60 but V9.0.0 is required. **Please download and install a more**

**Comment by gaaguile** [comment]
thank you.
