### ISSUE TITLE
[netcdf-c netcdf-cxx4] update to 4.9.2 and 4.3.1 respectively

### ISSUE THREAD

**Issue by dmeoli** [microsoft/vcpkg#34422]
pls update netcdf packages asap since they are not working under Win with MSYS

remark of #32942

**Comment by JonLiu1993** [comment]
@dmeoli, we already have an issue and PR about the update of netcdf-c, so I will close this issue, you can comment your needs below the [PR](https://github.com/microsoft/vcpkg/pull/32960) and we will respond immediately.
