### ISSUE TITLE
Add Loki Library

### ISSUE THREAD

**Issue by ghost** [microsoft/vcpkg#3443]
Please Add Latest Loki Library to vcpkg

**Comment by NancyLi1013** [comment]
Hi @gnu-lorien and @krqi thanks for posting this request.
Could you help provide homepage for Loki ?
I found this link address and the latest version is 0.1.7. Is this the one you need?
https://sourceforge.net/projects/loki-lib/files/Loki/

**Comment by gnu-lorien** [comment]
@NancyLi1013 I don't know how I got associated with this request?

**Comment by NancyLi1013** [comment]
@gnu-lorien thanks for your attention.
Do you mean you don't know how to submit a pull request on vcpkg?
Sorry, I am not clear about what your meaning is.

**Comment by gnu-lorien** [comment]
@NancyLi1013 I mean that I don't know why you did an @ for me. Before that my name wasn't associated with this request anywhere that I see. I don't know what Loki is.

**Comment by NancyLi1013** [comment]
@gnu-lorien thanks for your description about this.
I'm so sorry about this mistake that made you confused. I should have done @ for another person.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
