### ISSUE TITLE
[qtbase] Build error

### ISSUE THREAD

**Issue by xroot3** [microsoft/vcpkg#34437]
How to reproduce issue:
I Install Visual Studio 2017 inWindows10,
Try to install with following commands in the command line:
vcpkg install pcl[*]:x64-windows

Then I checked the file C:\vcpkg\buildtrees\qtbase\install-x64-windows-dbg-out.log,I get the reason:
fatal error C1189: #error:  "Qt requires at least Visual Studio 2019 version 16.7 (VC++ version 14.27). Please upgrade."

But if I don't want to install VS2019 or VS2022,just want to install a lower version of qtbase which is relied on PCL and   compatible  
in VS2017?
————————————————————————————————————————————————————————
Copy issue body from C:/Program Files/vcpkg-master/installed/vcpkg/issue_body.md
Computing installation plan...
The following packages will be built and installed:
    pcl[apps,core,cuda,examples,libusb,opengl,openni2,pcap,qt,simulation,surface-on-nurbs,tools,visualization,vtk]:x64-windows -> 1.13.1#1
  * qtbase[brotli,concurrent,core,dbus,default-features,doubleconversion,freetype,gui,harfbuzz,icu,jpeg,network,opengl,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,thread,widgets,zstd]:x64-windows -> 6.5.3
  * qtdeclarative:x64-windows -> 6.5.3
  * qtimageformats[core,default-features,jasper,tiff,webp]:x64-windows -> 6.5.3
  * qtshadertools:x64-windows -> 6.5.3
  * qttools[assistant,core,designer,linguist]:x64-windows -> 6.5.3
  * seacas:x64-windows -> 2022-11-22#5
  * utfcpp:x64-windows -> 3.2.5
  * verdict:x64-windows -> 1.4.0
  * vtk[core,opengl,qt]:x64-windows -> 9.2.0-pv5.11.0#10
  * winpcap:x64-windows -> 4.1.3#11
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\Administrator\AppData\Local\vcpkg\archives in 515 us. Use --debug to see more details.
Installing 1/11 qtbase:x64-windows...
Building qtbase[brotli,concurrent,core,dbus,default-features,doubleconversion,freetype,gui,harfbuzz,icu,jpeg,network,opengl,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,thread,widgets,zstd]:x64-windows...
-- Using cached qtbase-everywhere-src-6.5.3.tar.xz.
-- Cleaning sources at C:/vcpkg/buildtrees/qtbase/src/here-src-6-4031235931.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/qtbase-everywhere-src-6.5.3.tar.xz
-- Applying patch allow_outside_prefix.patch
-- Applying patch config_install.patch
-- Applying patch fix_cmake_build.patch
-- Applying patch harfbuzz.patch
-- Applying patch fix_egl.patch
-- Applying patch fix_egl_2.patch
-- Applying patch installed_dir.patch
-- Applying patch GLIB2-static.patch
-- Applying patch clang-cl_source_location.patch
-- Applying patch clang-cl_QGADGET_fix.diff
-- Applying patch env.patch
-- Applying patch dont_force_cmakecache_latest.patch
-- Using source at C:/vcpkg/buildtrees/qtbase/src/here-src-6-4031235931.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.27.1-windows/cmake-3.27.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j21
    Working Directory: C:/vcpkg/buildtrees/qtbase/x64-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\qtbase\install-x64-windows-dbg-out.log
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/12878473/install-x64-windows-dbg-out.log)

**Comment by Cheney-W** [comment]
I think you could use [versioning function](https://learn.microsoft.com/en-us/vcpkg/consume/lock-package-versions) to install an old version of qtbase.

**Comment by xroot3** [comment]
> I think you could use [versioning function](https://learn.microsoft.com/en-us/vcpkg/consume/lock-package-versions) to install an old version of qtbase.

I try to write a vcpkg.json file int the vcpkg path (I refer to the Official course you show me ,but I was not fully understand,may be the file is not Correct format)
[vcpkg.json](https://github.com/microsoft/vcpkg/files/12879122/vcpkg.json)
and then I run vcpkg install,next get the error like this:

C:\vcpkg>vcpkg install
warning: In the September 2023 release, the default triplet for vcpkg libraries changed from x86-windows to the detected host triplet (x64-windows). For the old behavior, add --triplet x86-windows . To suppress this message, add --triplet x64-windows .
error: failed to execute: "C:\vcpkg\downloads\tools\git-2.7.4-windows\mingw32\bin\git.exe" "--git-dir=C:\vcpkg\.git" "--work-tree=C:\vcpkg\buildtrees\versioning_\versions\qtbase\cb0ae3e8e3b92dc1272047ea709b83b93e0e880d_4804.tmp" -c core.autocrlf=false read-tree -m -u cb0ae3e8e3b92dc1272047ea709b83b93e0e880d
error: git failed with exit code: (128).
fatal: not a git repository: 'C:\vcpkg\.git'
note: while checking out port qtbase with git tree cb0ae3e8e3b92dc1272047ea709b83b93e0e880d

**Comment by Cheney-W** [comment]
Is the value of the `builtin-baseline` you used came from  the command of `git rev-parse HEAD`?

**Comment by xroot3** [comment]
> Is the value of the `builtin-baseline` you used came from the command of `git rev-parse HEAD`?

No,the value of the `builtin-baseline` I used came from "C:\vcpkg\versions\q-\qtbase.json",As follows:

{
  "versions": [
    {
      "git-tree": "8ff10ec91d1eda17f49dd867924e6e034a0abd5c",
      "version": "6.5.3",
      "port-version": 0
    },
    {
      "git-tree": "d3e2f2eea0533fae78469704453203038e8e838a",
      "version": "6.5.2",
      "port-version": 1
    },
    _**{
      "git-tree": "cb0ae3e8e3b92dc1272047ea709b83b93e0e880d",
      "version": "6.5.2",
      "port-version": 0
    },**_
    {
      "git-tree": "198ba2cfff57e3ccc7a2f6f40002127d8d0abb6e",
      "version": "6.5.1",
      "port-version": 3
    },
    {
      "git-tree": "384ddcfe175f58d6f498c91f6b8e790bb6ad70ac",
      "version": "6.5.1",
      "port-version": 2
    },
……………………

Because when I use the command of git rev-parse HEAD ,I get anoter error:
C:\vcpkg>git rev-parse HEAD
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD

**Comment by dg0yt** [comment]
[According to the documentation](https://learn.microsoft.com/en-us/vcpkg/reference/vcpkg-configuration-json#registry-baseline), `builtin-baseline` should be a "git commit sha", not a git tree ref.

**Comment by xroot3** [comment]
> [According to the documentation](https://learn.microsoft.com/en-us/vcpkg/reference/vcpkg-configuration-json#registry-baseline), `builtin-baseline` should be a "git commit sha", not a git tree ref.

Yes,I realized I was being fantastical.
But ,when I try to run the command of "vcpkg x-update-baseline --add-initial-baseline" to get the value of the builtin-baseline.
I get another error:
c:\vcpkg>vcpkg x-update-baseline --add-initial-baseline
————————————————————————————————————————
warning: registry 'https://github.com/microsoft/vcpkg' not updated: ''
git failed to parse HEAD for the local vcpkg registry at "C:\vcpkg"
error: git failed with exit code: (128).
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD

**Comment by Cheney-W** [comment]
Looks like the C:\vcpkg folder isn't a Git repository.

Ensure you're in the right directory. If C:\vcpkg is supposed to be a Git repository, there should be a .git subdirectory within it.
If you are indeed in a Git repository but still encounter this error, try cloning the repository to a new directory and execute your command there.

**Comment by xroot3** [comment]
> Looks like the C:\vcpkg folder isn't a Git repository.
> 
> Ensure you're in the right directory. If C:\vcpkg is supposed to be a Git repository, there should be a .git subdirectory within it. If you are indeed in a Git repository but still encounter this error, try cloning the repository to a new directory and execute your command there.

Thank you , the C:\vcpkg folder is really not a Git repository,and I download vcpkg by git command again ,Then the git rev-parse HEAD command go to effect.
