### ISSUE TITLE
[ace] does not respect VCPKG_BUILD_TYPE

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vcpkg#34446]
The port ace does not respect `set(VCPKG_BUILD_TYPE release)` in a triplet. So for example `arm64-osx-release` will also build the debug variants of the lib.

**Comment by MonicaLiu0311** [comment]
Reproduced on `linux` and `osx`, caused by this part of the code: [ports/ace/portfile.cmake#L277-L386](https://github.com/microsoft/vcpkg/blob/master/ports/ace/portfile.cmake#L277-L386)
