### ISSUE TITLE
Error: Building package libpqxx:x64-linux failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by cowabunga1** [Microsoft/vcpkg#3444]
Package: libpqxx:x64-linux
Vcpkg version: 0.0.110-unknownhash

# output

$ ./vcpkg install libpqxx
The following packages will be built and installed:
    libpqxx[core]:x64-linux
Starting package 1/1: libpqxx:x64-linux
Building package libpqxx[core]:x64-linux... 
-- CURRENT_INSTALLED_DIR=/home/vcpkg/installed/x64-linux
-- DOWNLOADS=/home/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=/home/vcpkg/packages/libpqxx_x64-linux
-- CURRENT_BUILDTREES_DIR=/home/vcpkg/buildtrees/libpqxx
-- CURRENT_PORT_DIR=/home/vcpkg/ports/libpqxx
-- Using cached /home/vcpkg/downloads/jtv-libpqxx-6.0.0.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: /home/vcpkg/downloads/tools/cmake-3.10.2-linux/cmake-3.10.2-Linux-x86_64/bin/cmake;/home/vcpkg/buildtrees/libpqxx/src/6.0.0-7173f5bba9;-DCMAKE_MAKE_PROGRAM=/home/vcpkg/downloads/tools/ninja-1.8.2-linux/ninja;-DCMAKE_SYSTEM_NAME=Linux;-DBUILD_SHARED_LIBS=OFF;-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/vcpkg/scripts/toolchains/linux.cmake;-DVCPKG_TARGET_TRIPLET=x64-linux;-DVCPKG_PLATFORM_TOOLSET=external;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=/home/vcpkg/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DVCPKG_CXX_FLAGS=;-DVCPKG_CXX_FLAGS_RELEASE=;-DVCPKG_CXX_FLAGS_DEBUG=;-DVCPKG_C_FLAGS=;-DVCPKG_C_FLAGS_RELEASE=;-DVCPKG_C_FLAGS_DEBUG=;-DVCPKG_CRT_LINKAGE=dynamic;-DVCPKG_LINKER_FLAGS=;-DCMAKE_INSTALL_LIBDIR:STRING=lib;-DCMAKE_INSTALL_BINDIR:STRING=bin;-G;Ninja;-DCMAKE_BUILD_TYPE=Debug;-DCMAKE_INSTALL_PREFIX=/home/vcpkg/packages/libpqxx_x64-linux/debug
    Working Directory: /home/vcpkg/buildtrees/libpqxx/x64-linux-dbg
    See logs for more information:
      /home/vcpkg/buildtrees/libpqxx/config-x64-linux-dbg-out.log
      /home/vcpkg/buildtrees/libpqxx/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:247 (vcpkg_execute_required_process)
  ports/libpqxx/portfile.cmake:15 (vcpkg_configure_cmake)
  scripts/ports.cmake:72 (include)

Error: Building package libpqxx:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libpqxx:x64-linux
  Vcpkg version: 0.0.110-unknownhash

Additionally, attach any relevant sections from the log files above.

### /home/vcpkg/buildtrees/libpqxx/config-x64-linux-dbg-out.log

-- The CXX compiler identification is GNU 5.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include poll.h
-- Looking for C++ include poll.h - found
-- Looking for C++ include sys/select.h
-- Looking for C++ include sys/select.h - found
-- Looking for C++ include sys/time.h
-- Looking for C++ include sys/time.h - found
-- Looking for C++ include sys/types.h
-- Looking for C++ include sys/types.h - found
-- Looking for C++ include unistd.h
-- Looking for C++ include unistd.h - found
-- Performing Test PQXX_HAVE_DEPRECATED
-- Performing Test PQXX_HAVE_DEPRECATED - Failed
-- Performing Test PQXX_HAVE_OPTIONAL
-- Performing Test PQXX_HAVE_OPTIONAL - Failed
-- Performing Test PQXX_HAVE_EXP_OPTIONAL
-- Performing Test PQXX_HAVE_EXP_OPTIONAL - Failed
-- Configuring incomplete, errors occurred!
See also "/home/vcpkg/buildtrees/libpqxx/x64-linux-dbg/CMakeFiles/CMakeOutput.log".
See also "/home/vcpkg/buildtrees/libpqxx/x64-linux-dbg/CMakeFiles/CMakeError.log".

### /home/vcpkg/buildtrees/libpqxx/x64-linux-dbg/CMakeFiles/CMakeError.log

Performing C++ SOURCE FILE Test PQXX_HAVE_DEPRECATED failed with the following output:
Change Dir: /home/vcpkg/buildtrees/libpqxx/x64-linux-dbg/CMakeFiles/CMakeTmp

Run Build Command:"/home/vcpkg/downloads/tools/ninja-1.8.2-linux/ninja" "cmTC_85846"
[1/2] Building CXX object CMakeFiles/cmTC_85846.dir/src.cxx.o
FAILED: CMakeFiles/cmTC_85846.dir/src.cxx.o 
/usr/bin/c++    -DPQXX_HAVE_DEPRECATED -o CMakeFiles/cmTC_85846.dir/src.cxx.o -c src.cxx
src.cxx:1:1: error: expected unqualified-id before ‘[’ token
 [[deprecated]] void f();
 ^
ninja: build stopped: subcommand failed.

Source file was:
[[deprecated]] void f();
int main() { return 0; }
Performing C++ SOURCE FILE Test PQXX_HAVE_OPTIONAL failed with the following output:
Change Dir: /home/vcpkg/buildtrees/libpqxx/x64-linux-dbg/CMakeFiles/CMakeTmp

Run Build Command:"/home/vcpkg/downloads/tools/ninja-1.8.2-linux/ninja" "cmTC_da707"
[1/2] Building CXX object CMakeFiles/cmTC_da707.dir/src.cxx.o
FAILED: CMakeFiles/cmTC_da707.dir/src.cxx.o 
/usr/bin/c++    -DPQXX_HAVE_OPTIONAL -o CMakeFiles/cmTC_da707.dir/src.cxx.o -c src.cxx
src.cxx:1:20: fatal error: optional: Нет такого файла или каталога
compilation terminated.
ninja: build stopped: subcommand failed.

Source file was:
#include <optional>
int main() { return std::optional<int>(0).value(); }
Performing C++ SOURCE FILE Test PQXX_HAVE_EXP_OPTIONAL failed with the following output:
Change Dir: /home/vcpkg/buildtrees/libpqxx/x64-linux-dbg/CMakeFiles/CMakeTmp

Run Build Command:"/home/vcpkg/downloads/tools/ninja-1.8.2-linux/ninja" "cmTC_0d11d"
[1/2] Building CXX object CMakeFiles/cmTC_0d11d.dir/src.cxx.o
FAILED: CMakeFiles/cmTC_0d11d.dir/src.cxx.o 
/usr/bin/c++    -DPQXX_HAVE_EXP_OPTIONAL -o CMakeFiles/cmTC_0d11d.dir/src.cxx.o -c src.cxx
In file included from /usr/include/c++/5/experimental/optional:45:0,
                 from src.cxx:1:
/usr/include/c++/5/bits/c++14_warning.h:32:2: error: #error This file requires compiler and library support for the forthcoming ISO C++ 2014 standard. This support is currently experimental, and must be enabled with the -std=c++1y or -std=gnu++1y compiler options.
 #error This file requires compiler and library support for the forthcoming \
  ^
src.cxx: In function ‘int main()’:
src.cxx:2:26: error: ‘std::experimental’ has not been declared
 int main() { return std::experimental::optional<int>(0).value(); }
                          ^
src.cxx:2:49: error: expected primary-expression before ‘int’
 int main() { return std::experimental::optional<int>(0).value(); }
                                                 ^
src.cxx:2:49: error: expected ‘;’ before ‘int’
src.cxx:2:52: error: expected unqualified-id before ‘>’ token
 int main() { return std::experimental::optional<int>(0).value(); }
                                                    ^
ninja: build stopped: subcommand failed.

Source file was:
#include <experimental/optional>
int main() { return std::experimental::optional<int>(0).value(); }

### /home/vcpkg/buildtrees/libpqxx/config-x64-linux-dbg-err.log

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBPQ
    linked by target "libpqxx_static" in directory /home/vcpkg/buildtrees/libpqxx/src/6.0.0-7173f5bba9

**Comment by tschabo** [comment]
libpq is not found. Following changes helped me.
`diff --git a/ports/libpqxx/portfile.cmake b/ports/libpqxx/portfile.cmake
index 2ba92b1c..122c6981 100644
--- a/ports/libpqxx/portfile.cmake
+++ b/ports/libpqxx/portfile.cmake
@@ -15,6 +15,9 @@ file(COPY ${CMAKE_CURRENT_LIST_DIR}/config-internal-compiler.h.in DESTINATION ${
 vcpkg_configure_cmake(
     SOURCE_PATH ${SOURCE_PATH}
     PREFER_NINJA
+    OPTIONS
+        -DLIBPQ=lib/debug/libpq.a
+        -DLIBPQD=debug/lib/libpqd.a
 )
`

**Comment by NancyLi1013** [comment]
Thanks a lot for posting this issue. I cannot reproduce it on the latest vcpkg now. 
Please open a new issue if this is still a problem for you.
