### ISSUE TITLE
[nifticlib] include path breaks app build

### ISSUE THREAD

**Issue by shangjiaxuan** [microsoft/vcpkg#34444]
### Is your feature request related to a problem? Please describe.

In installed `nifti/nifti2_io.h`, it references installed `nifti/znzlib.h` as `#include <znzlib.h>`, breaking build of dependent apps.

### Proposed solution

May require a patch to change the include or a change of installation location to fix.

### Describe alternatives you've considered

Currently manually edited the header file as workaround.

### Additional context

None needed.

**Comment by JonLiu1993** [comment]
@shangjiaxuan, thanks for posting this issue, I successfully tested the port nifticlib usage, I want to confirm with you
Do you want to channge `#include <znzlib.h>` to `#include <nifti/znzlib.h>`?

```` 
#include <stdio.h>
#include <znzlib.h>

int main()
{
    printf("%s\n", "HELLO WORLD");
    return 0;
}
````

**Comment by dg0yt** [comment]
IMO it sounds like it should change to `#include "znzlib.h"`.
(Assume side-by-side installation, not a particular parent path.)

**Comment by shangjiaxuan** [comment]
@JonLiu1993 It looks like `znzlib` is bundled within `nifticlib`, but it seems that it has a separate repo [here](https://github.com/neurolabusc/znzlib), which again includes part of `nifticlib` inside the repo. This kind of logic suggests separating them, but `znzlib` is just to small to be worth the effort (just a wrapper of gzip compression with with a toggle flag).

I'm not sure what the most typical setup is (like SDL had `#include <SDL2.h>` or `#include <SDL/SDL2.h>` difference). I'm okay with anything that builds without breaking internally.

**Comment by JonLiu1993** [comment]
@shangjiaxuan, I have submitted a [PR](https://github.com/microsoft/vcpkg/pull/34467) to allow users to include the znzlib.h header file using #include "znzlib.h", could you please test if the PR solves your bug?

**Comment by shangjiaxuan** [comment]
@JonLiu1993 comfirmed fixed.
