### ISSUE TITLE
"Path too long," error when installing QT, even with VCPKG installed in "C:/" and using "--x-buildtrees-root"

### ISSUE THREAD

**Issue by zachHixson** [microsoft/vcpkg#34479]
**Describe the bug**
When installing QT, it errors out telling me the path is too long however, I literally can't make it any shorter since it's already using `C:\vcpkcg\`. Even when passing `--x-buildtress-root` and providing either the VCPKG or buildtrees directory it still produces the same error.

**Environment**
- OS: Windows 10
- Compiler: MSVC 10.0.40219 (not sure if that's the correct version number though, latest VS community is installed).

**To Reproduce**
1. `./vcpkg install qt` or `./vcpkg install qtwebengine`
2. See error

**Expected behavior**
qt or qtwebengine to be installed

**Failure logs**
```
CMake Warning at ports/qtwebengine/portfile.cmake:83 (message):
  Buildtree path 'C:/vcpkg/buildtrees/qtwebengine' is too long.

  Consider passing --x-buildtrees-root=<shortpath> to vcpkg!`
```

**Comment by Osyotr** [comment]
`--x-buildtress-root=C:\b` doesn't work? Try using `subst b: c:\vcpkg\buildtrees` and `--x-buildtress-root=b:\` (saves one character).
Please note that it's not an error but a warning.

**Comment by zachHixson** [comment]
I tried `--x-buildtress-root="C:\vcpkg"` again and it worked for some reason this time, so I'm going to go ahead and close it. Thanks for your reply though.

**Comment by Melio-1** [comment]
> Buildtree path 'C:/vcpkg/buildtrees/qtwebengine' is too long.

I've do like you but stucking in building debug, how to solve it ?
