### ISSUE TITLE
Terminate vcpkg when upgrading and it show that all softwares are up-to-date

### ISSUE THREAD

**Issue by wby238** [microsoft/vcpkg#3448]
I run `vcpkg upgrade --no-dry-run` and terminate it carelessly.
When I try to run `vcpkg upgrade --no-dry-run`, it shows that `All installed packages are up-to-date with the local portfiles.`.
I use the latest version.
How to solve this problem?

**Comment by Cheney-W** [comment]
@wby238, You can do as below steps:
1. git branch (check your current branch, if your branch is master, do the next step)
2. git pull
3. .\vcpkg.exe upgrade --no-dry-run

Please close this issue once your issue is resolved.
