### ISSUE TITLE
matio - add CMake targets or show help text for find_package()

### ISSUE THREAD

**Issue by ctr** [microsoft/vcpkg#34488]
### Is your feature request related to a problem? Please describe.

I am using visual studio 2022 on windows with this vcpkg.json file:

{
  "dependencies": [
    "cxxopts",
    "fmt",
    "range-v3",
    "matio",
    "highfive"
  ]
}

The other packages explain the text needed in my project CMakeLists.txt to use them e.g. like:

1> [CMake] The package fmt provides CMake targets:
1> [CMake] 
1> [CMake]     find_package(fmt CONFIG REQUIRED)
1> [CMake]     target_link_libraries(main PRIVATE fmt::fmt)
1> [CMake] 
1> [CMake]     # Or use the header-only version
1> [CMake]     find_package(fmt CONFIG REQUIRED)
1> [CMake]     target_link_libraries(main PRIVATE fmt::fmt-header-only)
1> [CMake] 

But matio doesn't show any information about provided CMake targets; and I can't figure out the correct find_package syntax.

Here is a small repo demonstrating the issue
https://github.com/ctr/vcpkg-test1

### Proposed solution

Update matio so that it can be used with find_package(matio REQUIRED) in a CMakeLists.txt file.

### Describe alternatives you've considered

Not applicable.

**Comment by Osyotr** [comment]
Try using pkg-config (add a host dependency on `pkgconf` in your manifest file):
```cmake
find_package(PkgConfig REQUIRED)
pkg_check_modules(matio REQUIRED IMPORTED_TARGET matio)
target_link_libraries(my_target PRIVATE PkgConfig::matio)
```

**Comment by ctr** [comment]
Hi. Thanks for the advice on this. I tried adding the lines to my demo on Visual Studio 2022 on Windows 10 x64. But it won't build.

I also tried adding "PkgConfig", "pkgconfig" and "pkg-config" to my vcpkg.json but none of those was detected as a valid port.

1> [CMake] CMake Error at C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
1> [CMake]   Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
1> [CMake] Call Stack (most recent call first):
1> [CMake]   C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
1> [CMake]   C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.26/Modules/FindPkgConfig.cmake:99 (find_package_handle_standard_args)
1> [CMake]   C:/Program Files/Microsoft Visual Studio/2022/Community/VC/vcpkg/scripts/buildsystems/vcpkg.cmake:853 (_find_package)
1> [CMake]   CMakeLists.txt:12 (find_package)
1> [CMake] -- Configuring incomplete, errors occurred!

How should this work on Windows? Thanks. Chris.

**Comment by jimwang118** [comment]
> How should this work on Windows? Thanks. Chris.

You can install `pkgconf` in vcpkg and then use the following code in cmakelists.txt.
```
set(PKG_CONFIG_EXECUTABLE "${VCPKG_INSTALLED_DIR}/x64-windows/tools/pkgconf/pkgconf.exe")
find_package(PkgConfig REQUIRED)
pkg_check_modules(matio REQUIRED IMPORTED_TARGET matio)
target_link_libraries(main PRIVATE PkgConfig::matio)
```

**Comment by ctr** [comment]
I updated my demo to try this. It finds the pkgconf.exe binary. But this still doesn't find matio on my computer.

1> CMake generation started for default configuration: 'x64-Debug'.
1> Found and using vcpkg toolchain file (C:/Program Files/Microsoft Visual Studio/2022/Community/VC/vcpkg/scripts/buildsystems/vcpkg.cmake).
1> Command line: "C:\Windows\system32\cmd.exe" /c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\ctr28\Documents\VisualStudioSources\vcpkg-test1\out\install\x64-Debug" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe"   -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" -DCMAKE_TOOLCHAIN_FILE="C:/Program Files/Microsoft Visual Studio/2022/Community/VC/vcpkg/scripts/buildsystems/vcpkg.cmake" "C:\Users\ctr28\Documents\VisualStudioSources\vcpkg-test1" 2>&1"
1> Working directory: C:\Users\ctr28\Documents\VisualStudioSources\vcpkg-test1\out\build\x64-Debug
1> [CMake] -- Running vcpkg install
1> [CMake] Detecting compiler hash for triplet x64-windows...
1> [CMake] All requested packages are currently installed.
1> [CMake] Total install time: 200 ns
1> [CMake] cxxopts provides CMake targets:
1> [CMake] 
1> [CMake]     # this is heuristically generated, and may not be correct
1> [CMake]     find_package(cxxopts CONFIG REQUIRED)
1> [CMake]     target_link_libraries(main PRIVATE cxxopts::cxxopts)
1> [CMake] 
1> [CMake] The package fmt provides CMake targets:
1> [CMake] 
1> [CMake]     find_package(fmt CONFIG REQUIRED)
1> [CMake]     target_link_libraries(main PRIVATE fmt::fmt)
1> [CMake] 
1> [CMake]     # Or use the header-only version
1> [CMake]     find_package(fmt CONFIG REQUIRED)
1> [CMake]     target_link_libraries(main PRIVATE fmt::fmt-header-only)
1> [CMake] 
1> [CMake] highfive provides CMake targets:
1> [CMake] 
1> [CMake]   find_package(HighFive CONFIG REQUIRED)
1> [CMake]   target_link_libraries(main PRIVATE HighFive)
1> [CMake] 
1> [CMake] range-v3 provides CMake targets:
1> [CMake] 
1> [CMake]     # this is heuristically generated, and may not be correct
1> [CMake]     find_package(range-v3 CONFIG REQUIRED)
1> [CMake]     target_link_libraries(main PRIVATE range-v3::meta range-v3::concepts range-v3::range-v3)
1> [CMake] 
1> [CMake] -- Running vcpkg install - done
1> [CMake] -- HIGHFIVE 2.7.1: (Re)Detecting Highfive dependencies (HIGHFIVE_USE_INSTALL_DEPS=NO)
1> [CMake] -- C:/Users/ctr28/Documents/VisualStudioSources/vcpkg-test1/out/build/x64-Debug/vcpkg_installed/x64-windows/tools/pkgconf/pkgconf.exe
1> [CMake] -- Beforeset:PKG_CONFIG_EXECUTABLE=
1> [CMake] -- Afterset:PKG_CONFIG_EXECUTABLE=C:/Users/ctr28/Documents/VisualStudioSources/vcpkg-test1/out/build/x64-Debug/vcpkg_installed/x64-windows/tools/pkgconf/pkgconf.exe
1> [CMake] -- Checking for module 'matio'
1> [CMake] --   Package 'matio', required by 'virtual:world', not found
1> [CMake] CMake Error at C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.26/Modules/FindPkgConfig.cmake:607 (message):
1> [CMake]   A required package was not found
1> [CMake] Call Stack (most recent call first):
1> [CMake]   C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.26/Modules/FindPkgConfig.cmake:829 (_pkg_check_modules_internal)
1> [CMake]   CMakeLists.txt:16 (pkg_check_modules)
1> [CMake] -- Configuring incomplete, errors occurred!
1> 'C:\Windows\system32\cmd.exe' '/c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\ctr28\Documents\VisualStudioSources\vcpkg-test1\out\install\x64-Debug" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe"   -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" -DCMAKE_TOOLCHAIN_FILE="C:/Program Files/Microsoft Visual Studio/2022/Community/VC/vcpkg/scripts/buildsystems/vcpkg.cmake" "C:\Users\ctr28\Documents\VisualStudioSources\vcpkg-test1" 2>&1"' execution failed with error: ''C:\Windows\system32\cmd.exe' '/c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\ctr28\Documents\VisualStudioSources\vcpkg-test1\out\install\x64-Debug" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe"   -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" -DCMAKE_TOOLCHAIN_FILE="C:/Program Files/Microsoft Visual Studio/2022/Community/VC/vcpkg/scripts/buildsystems/vcpkg.cmake" "C:\Users\ctr28\Documents\VisualStudioSources\vcpkg-test1" 2>&1"' returned with exit code: 1'.

**Comment by ctr** [comment]
Also... digging a bit further, it seems that matio doesn't install a .pc file via vcpkg on my system so I don't think pkgconf could find it anyway?? And pkgconf seems to need an additional --with-dir argument to find its database.

C:\Users\ctr28\Documents\VisualStudioSources\vcpkg-test1>.\out\build\x64-Debug\vcpkg_installed\x64-windows\tools\pkgconf\pkgconf.exe --list-all

C:\Users\ctr28\Documents\VisualStudioSources\vcpkg-test1>.\out\build\x64-Debug\vcpkg_installed\x64-windows\tools\pkgconf\pkgconf.exe --list-all --with-path=.\out\build\x64-Debug\vcpkg_installed\x64-windows\debug\lib\pkgconfig
fmt                            fmt - A modern formatting library
hdf5                           hdf5 - HDF5 (Hierarchical Data Format 5) Software Library
hdf5_hl                        hdf5_hl - HDF5 (Hierarchical Data Format 5) Software Library
libpkgconf                     libpkgconf - a library for accessing and manipulating development framework configuration
szip                           szip - Szip compression software
zlib                           zlib - zlib compression library

C:\Users\ctr28\Documents\VisualStudioSources\vcpkg-test1>

NOTE that this doesn't list matio.

Here are the pkgconf.exe files and *.pc files installed by vcpkg:

ctr28@CTRXPS MINGW64 ~/Documents/VisualStudioSources/vcpkg-test1 (main)
$ find . -iname pkgconf.exe
./out/build/x64-Debug/vcpkg_installed/vcpkg/pkgs/pkgconf_x64-windows/tools/pkgconf/pkgconf.exe
./out/build/x64-Debug/vcpkg_installed/x64-windows/tools/pkgconf/pkgconf.exe

ctr28@CTRXPS MINGW64 ~/Documents/VisualStudioSources/vcpkg-test1 (main)
$ find . -iname '*.pc'
./out/build/x64-Debug/vcpkg_installed/vcpkg/pkgs/fmt_x64-windows/debug/lib/pkgconfig/fmt.pc
./out/build/x64-Debug/vcpkg_installed/vcpkg/pkgs/fmt_x64-windows/lib/pkgconfig/fmt.pc
./out/build/x64-Debug/vcpkg_installed/vcpkg/pkgs/hdf5_x64-windows/debug/lib/pkgconfig/hdf5.pc
./out/build/x64-Debug/vcpkg_installed/vcpkg/pkgs/hdf5_x64-windows/debug/lib/pkgconfig/hdf5_hl.pc
./out/build/x64-Debug/vcpkg_installed/vcpkg/pkgs/hdf5_x64-windows/lib/pkgconfig/hdf5.pc
./out/build/x64-Debug/vcpkg_installed/vcpkg/pkgs/hdf5_x64-windows/lib/pkgconfig/hdf5_hl.pc
./out/build/x64-Debug/vcpkg_installed/vcpkg/pkgs/pkgconf_x64-windows/debug/lib/pkgconfig/libpkgconf.pc
./out/build/x64-Debug/vcpkg_installed/vcpkg/pkgs/pkgconf_x64-windows/lib/pkgconfig/libpkgconf.pc
./out/build/x64-Debug/vcpkg_installed/vcpkg/pkgs/szip_x64-windows/debug/lib/pkgconfig/szip.pc
./out/build/x64-Debug/vcpkg_installed/vcpkg/pkgs/szip_x64-windows/lib/pkgconfig/szip.pc
./out/build/x64-Debug/vcpkg_installed/vcpkg/pkgs/zlib_x64-windows/debug/lib/pkgconfig/zlib.pc
./out/build/x64-Debug/vcpkg_installed/vcpkg/pkgs/zlib_x64-windows/lib/pkgconfig/zlib.pc
./out/build/x64-Debug/vcpkg_installed/x64-windows/debug/lib/pkgconfig/fmt.pc
./out/build/x64-Debug/vcpkg_installed/x64-windows/debug/lib/pkgconfig/hdf5.pc
./out/build/x64-Debug/vcpkg_installed/x64-windows/debug/lib/pkgconfig/hdf5_hl.pc
./out/build/x64-Debug/vcpkg_installed/x64-windows/debug/lib/pkgconfig/libpkgconf.pc
./out/build/x64-Debug/vcpkg_installed/x64-windows/debug/lib/pkgconfig/szip.pc
./out/build/x64-Debug/vcpkg_installed/x64-windows/debug/lib/pkgconfig/zlib.pc
./out/build/x64-Debug/vcpkg_installed/x64-windows/lib/pkgconfig/fmt.pc
./out/build/x64-Debug/vcpkg_installed/x64-windows/lib/pkgconfig/hdf5.pc
./out/build/x64-Debug/vcpkg_installed/x64-windows/lib/pkgconfig/hdf5_hl.pc
./out/build/x64-Debug/vcpkg_installed/x64-windows/lib/pkgconfig/libpkgconf.pc
./out/build/x64-Debug/vcpkg_installed/x64-windows/lib/pkgconfig/szip.pc
./out/build/x64-Debug/vcpkg_installed/x64-windows/lib/pkgconfig/zlib.pc

ctr28@CTRXPS MINGW64 ~/Documents/VisualStudioSources/vcpkg-test1 (main)
$

**Comment by jimwang118** [comment]
You can use the code from PR [34505](https://github.com/microsoft/vcpkg/pull/34505) for testing.

**Comment by ctr** [comment]
Ah, I see.

I'm new to vcpkg. I'm using the version integrated with Visual Studio. I looked at the docs, but I'm still confused.

Could you possibly tell me how I pull this PR 34505 version into my project? I think I need to add this as another registry in my vcpkg.json file?? But I don't know how.

Can I do this without having to switch away from the MSVC-integrated vcpkg for all other ports?

Thanks

Chris.

**Comment by jimwang118** [comment]
You click PR https://github.com/microsoft/vcpkg/pull/34505, then follow the steps as shown below to clone the code.
![image](https://github.com/microsoft/vcpkg/assets/122244446/487765a2-6aac-4484-a3d5-44c42642d5eb)
