### ISSUE TITLE
error: building boost-exception:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by AtosReis** [microsoft/vcpkg#34491]
PS C:\dev\vcpkg> git pull
Already up to date.

PS C:\dev\vcpkg> .\vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

error: building boost-exception:x64-windows failed with: BUILD_FAILED
Elapsed time to handle boost-exception:x64-windows: 484 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-exception
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[boost-exception]+Build+error&body=Copy+issue+body+from+C%3A%2Fdev%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

Log: 

Change Dir: 'C:/dev/vcpkg/buildtrees/boost-exception/x64-windows-dbg'

Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v -v -j17 install
[1/2] cmd.exe /C "cd /D C:\dev\vcpkg\buildtrees\boost-exception\src\ost-1.83.0-e0db41e4c0.clean\build && C:\dev\vcpkg\installed\x64-windows\tools\boost-build\b2.exe toolset=msvc --user-config=C:/dev/vcpkg/buildtrees/boost-exception/x64-windows-dbg/user-config.jam --stagedir=C:/dev/vcpkg/buildtrees/boost-exception/x64-windows-dbg/stage --build-dir=C:/dev/vcpkg/buildtrees/boost-exception/x64-windows-dbg runtime-link=shared link=shared address-model=64 architecture=x86 target-os=windows threadapi=win32 variant=debug --disable-icu --with-atomic --with-random --with-date_time --with-filesystem --with-system --with-thread --with-chrono -j 17 -sBOOST_ROOT=C:/dev/vcpkg/installed/x64-windows/tools/boost-build -sBOOST_BUILD_PATH=C:/dev/vcpkg/installed/x64-windows/tools/boost-build --debug-configuration --debug-building --debug-generators --ignore-site-config --hash -q debug-symbols=on -d +2 threading=multi stage"
FAILED: CMakeFiles/boost C:/dev/vcpkg/buildtrees/boost-exception/x64-windows-dbg/CMakeFiles/boost 
cmd.exe /C "cd /D C:\dev\vcpkg\buildtrees\boost-exception\src\ost-1.83.0-e0db41e4c0.clean\build && C:\dev\vcpkg\installed\x64-windows\tools\boost-build\b2.exe toolset=msvc --user-config=C:/dev/vcpkg/buildtrees/boost-exception/x64-windows-dbg/user-config.jam --stagedir=C:/dev/vcpkg/buildtrees/boost-exception/x64-windows-dbg/stage --build-dir=C:/dev/vcpkg/buildtrees/boost-exception/x64-windows-dbg runtime-link=shared link=shared address-model=64 architecture=x86 target-os=windows threadapi=win32 variant=debug --disable-icu --with-atomic --with-random --with-date_time --with-filesystem --with-system --with-thread --with-chrono -j 17 -sBOOST_ROOT=C:/dev/vcpkg/installed/x64-windows/tools/boost-build -sBOOST_BUILD_PATH=C:/dev/vcpkg/installed/x64-windows/tools/boost-build --debug-configuration --debug-building --debug-generators --ignore-site-config --hash -q debug-symbols=on -d +2 threading=multi stage"
O sistema não pode executar o programa especificado.
ninja: build stopped: subcommand failed.

**Comment by JonLiu1993** [comment]
@AtosReis, Thanks for posting this issue, plesae provide error log.

**Comment by JonLiu1993** [comment]
@KawaiiNahida, please provide the error log, thanks.
````
D:\vcpkg\buildtrees\boost-exception\install-x64-windows-dbg-out.log
````

**Comment by ClintonWeeYuan** [comment]
It happened to me too. Error log below:

```
Change Dir: 'C:/vcpkg/buildtrees/boost-exception/x64-windows-dbg'

Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v -v -j13 install
[1/2] C:\WINDOWS\system32\cmd.exe /C "cd /D C:\vcpkg\buildtrees\boost-exception\src\ost-1.83.0-e0db41e4c0.clean\build && C:\vcpkg\installed\x64-windows\tools\boost-build\b2.exe toolset=msvc --user-config=C:/vcpkg/buildtrees/boost-exception/x64-windows-dbg/user-config.jam --stagedir=C:/vcpkg/buildtrees/boost-exception/x64-windows-dbg/stage --build-dir=C:/vcpkg/buildtrees/boost-exception/x64-windows-dbg runtime-link=shared link=shared address-model=64 architecture=x86 target-os=windows threadapi=win32 variant=debug --disable-icu --with-atomic --with-random --with-date_time --with-filesystem --with-system --with-thread --with-chrono -j 13 -sBOOST_ROOT=C:/vcpkg/installed/x64-windows/tools/boost-build -sBOOST_BUILD_PATH=C:/vcpkg/installed/x64-windows/tools/boost-build --debug-configuration --debug-building --debug-generators --ignore-site-config --hash -q debug-symbols=on -d +2 threading=multi stage"
FAILED: CMakeFiles/boost C:/vcpkg/buildtrees/boost-exception/x64-windows-dbg/CMakeFiles/boost 
C:\WINDOWS\system32\cmd.exe /C "cd /D C:\vcpkg\buildtrees\boost-exception\src\ost-1.83.0-e0db41e4c0.clean\build && C:\vcpkg\installed\x64-windows\tools\boost-build\b2.exe toolset=msvc --user-config=C:/vcpkg/buildtrees/boost-exception/x64-windows-dbg/user-config.jam --stagedir=C:/vcpkg/buildtrees/boost-exception/x64-windows-dbg/stage --build-dir=C:/vcpkg/buildtrees/boost-exception/x64-windows-dbg runtime-link=shared link=shared address-model=64 architecture=x86 target-os=windows threadapi=win32 variant=debug --disable-icu --with-atomic --with-random --with-date_time --with-filesystem --with-system --with-thread --with-chrono -j 13 -sBOOST_ROOT=C:/vcpkg/installed/x64-windows/tools/boost-build -sBOOST_BUILD_PATH=C:/vcpkg/installed/x64-windows/tools/boost-build --debug-configuration --debug-building --debug-generators --ignore-site-config --hash -q debug-symbols=on -d +2 threading=multi stage"
The system cannot execute the specified program.
ninja: build stopped: subcommand failed.

```

**Comment by JonLiu1993** [comment]
@ClintonWeeYuan, 
Thanks for your error log. Please make sure you have the following installed.
- Visual Studio Desktop development with C++.
- Windows 10 SDK or Windows 11 SDK.

**Comment by ClintonWeeYuan** [comment]
Hi I'm not sure what these packages are. When doing a brief google search of them, there doesn't seem to be any clear way to (i) find out if I do have these packages OR (ii) to download them.

Could you provide me with some links to any instructions?

**Comment by ClintonWeeYuan** [comment]
Hmm..it looks like I already have it. But I reinstalled just in case. Still getting the same error.

<img width="248" alt="image" src="https://github.com/microsoft/vcpkg/assets/26379973/04f11cfd-47d6-4275-a81a-6b9754503a3d">

**Comment by JonLiu1993** [comment]
@AtosReis, It looks like you did install the necessary SDK. could you use the command `git pull` and run cmooand `.\bootstrap-vcpkg.bat` and try again?
![image](https://github.com/microsoft/vcpkg/assets/63675417/d20a890a-bbdd-4bf1-ac3e-2f86322352ba)

**Comment by KawaiiNahida** [comment]
After pulling the latest Vcpkg, the issue still persists. It appears that Boost.Build is incorrectly identifying MSVC as GCC, or it may have detected a GCC installation in the path, leading to this behavior.
```
Change Dir: 'D:/vcpkg/buildtrees/boost-exception/x64-windows-dbg'

Run Build Command(s): D:/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe -v -v -j33 install
[1/2] cmd.exe /C "cd /D D:\vcpkg\buildtrees\boost-exception\src\ost-1.83.0-e0db41e4c0.clean\build && D:\vcpkg\installed\x64-windows\tools\boost-build\b2.exe toolset=gcc --user-config=D:/vcpkg/buildtrees/boost-exception/x64-windows-dbg/user-config.jam --stagedir=D:/vcpkg/buildtrees/boost-exception/x64-windows-dbg/stage --build-dir=D:/vcpkg/buildtrees/boost-exception/x64-windows-dbg runtime-link=shared link=shared address-model=32 architecture=x86 target-os=windows threadapi=win32 variant=debug --disable-icu --with-atomic --with-random --with-date_time --with-filesystem --with-system --with-thread --with-chrono -j 33 -sBOOST_ROOT=D:/vcpkg/installed/x64-windows/tools/boost-build -sBOOST_BUILD_PATH=D:/vcpkg/installed/x64-windows/tools/boost-build --debug-configuration --debug-building --debug-generators --ignore-site-config --hash -q debug-symbols=on -d +2 threading=multi stage"
FAILED: CMakeFiles/boost D:/vcpkg/buildtrees/boost-exception/x64-windows-dbg/CMakeFiles/boost 
cmd.exe /C "cd /D D:\vcpkg\buildtrees\boost-exception\src\ost-1.83.0-e0db41e4c0.clean\build && D:\vcpkg\installed\x64-windows\tools\boost-build\b2.exe toolset=gcc --user-config=D:/vcpkg/buildtrees/boost-exception/x64-windows-dbg/user-config.jam --stagedir=D:/vcpkg/buildtrees/boost-exception/x64-windows-dbg/stage --build-dir=D:/vcpkg/buildtrees/boost-exception/x64-windows-dbg runtime-link=shared link=shared address-model=32 architecture=x86 target-os=windows threadapi=win32 variant=debug --disable-icu --with-atomic --with-random --with-date_time --with-filesystem --with-system --with-thread --with-chrono -j 33 -sBOOST_ROOT=D:/vcpkg/installed/x64-windows/tools/boost-build -sBOOST_BUILD_PATH=D:/vcpkg/installed/x64-windows/tools/boost-build --debug-configuration --debug-building --debug-generators --ignore-site-config --hash -q debug-symbols=on -d +2 threading=multi stage"
notice: loading B2 from D:/vcpkg/installed/x64-windows/tools/boost-build/src/kernel/bootstrap.jam
notice: Site configuration files will be ignored due to the
notice: --ignore-site-config command-line option.
notice: Loading explicitly specified user configuration file:
    D:\vcpkg\buildtrees\boost-exception\x64-windows-dbg\user-config.jam
notice: Searching 'D:\vcpkg\buildtrees\boost-exception\x64-windows-dbg' for user-config configuration file 'user-config.jam'.
notice: Loading user-config configuration file 'user-config.jam' from 'D:/vcpkg/buildtrees/boost-exception/x64-windows-dbg'.
Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31630 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '-dumpmachine'
cl : Command line error D8003 : missing source filename
Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31630 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '-dumpfullversion'
cl : Command line warning D9002 : ignoring unknown option '-dumpversion'
cl : Command line error D8003 : missing source filename
D:/vcpkg/installed/x64-windows/tools/boost-build/src/tools\common.jam:1164: in common.match-command-output from module common
error: '"C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe" -dumpfullversion -dumpversion' exited with error code 2
D:/vcpkg/installed/x64-windows/tools/boost-build/src/tools\gcc.jam:295: in get-full-version from module gcc
D:/vcpkg/installed/x64-windows/tools/boost-build/src/tools\gcc.jam:300: in get-short-version from module gcc
D:/vcpkg/installed/x64-windows/tools/boost-build/src/tools\gcc.jam:194: in gcc.init from module gcc
D:/vcpkg/installed/x64-windows/tools/boost-build/src/build\toolset.jam:44: in toolset.using from module toolset
D:/vcpkg/installed/x64-windows/tools/boost-build/src/build\project.jam:1260: in using from module project-rules
D:\vcpkg\buildtrees\boost-exception\x64-windows-dbg\user-config.jam:9: in modules.load from module user-config
D:/vcpkg/installed/x64-windows/tools/boost-build/src\build-system.jam:255: in load-config from module build-system
D:/vcpkg/installed/x64-windows/tools/boost-build/src\build-system.jam:449: in load-configuration-files from module build-system
D:/vcpkg/installed/x64-windows/tools/boost-build/src\build-system.jam:607: in load from module build-system
D:/vcpkg/installed/x64-windows/tools/boost-build/src/kernel\modules.jam:294: in import from module modules
D:/vcpkg/installed/x64-windows/tools/boost-build/src/kernel/bootstrap.jam:135: in module scope from module

ninja: build stopped: subcommand failed.
```

**Comment by JonLiu1993** [comment]
@KawaiiNahida, 
> toolset=gcc

`gcc` is chosen as toolset instead of `msvc`, it looks like your `vcpkg-cmake:x64-windows` package is out of date, please run the following command to try again:
`./vcpkg upgrade --no-dry-run`

**Comment by xiuer-1573** [comment]
hi, when i install pcl, it has error 
D:\vcpkg-master>vcpkg.exe install pcl
warning: In the September 2023 release, the default triplet for vcpkg libraries changed from x86-windows to the detected host triplet (x64-windows). For the old behavior, add --triplet x86-windows . To suppress this message, add --triplet x64-windows .
Computing installation plan...
The following packages will be built and installed:
  * boost-algorithm:x64-windows -> 1.83.0
  * boost-align:x64-windows -> 1.83.0
  * boost-any:x64-windows -> 1.83.0
  * boost-asio:x64-windows -> 1.83.0
  * boost-atomic:x64-windows -> 1.83.0
  * boost-bimap:x64-windows -> 1.83.0
  * boost-chrono:x64-windows -> 1.83.0
  * boost-circular-buffer:x64-windows -> 1.83.0
  * boost-container:x64-windows -> 1.83.0
  * boost-container-hash:x64-windows -> 1.83.0
  * boost-context:x64-windows -> 1.83.0
  * boost-conversion:x64-windows -> 1.83.0
  * boost-coroutine:x64-windows -> 1.83.0
  * boost-date-time:x64-windows -> 1.83.0
  * boost-describe:x64-windows -> 1.83.0
  * boost-detail:x64-windows -> 1.83.0
  * boost-dynamic-bitset:x64-windows -> 1.83.0
  * boost-endian:x64-windows -> 1.83.0
  * boost-exception:x64-windows -> 1.83.0
  * boost-filesystem:x64-windows -> 1.83.0
  * boost-foreach:x64-windows -> 1.83.0
  * boost-format:x64-windows -> 1.83.0
  * boost-function:x64-windows -> 1.83.0
  * boost-function-types:x64-windows -> 1.83.0
  * boost-functional:x64-windows -> 1.83.0
  * boost-fusion:x64-windows -> 1.83.0
  * boost-graph:x64-windows -> 1.83.0
  * boost-integer:x64-windows -> 1.83.0
  * boost-interprocess:x64-windows -> 1.83.0
  * boost-intrusive:x64-windows -> 1.83.0
  * boost-io:x64-windows -> 1.83.0
  * boost-iostreams[bzip2,core,lzma,zlib,zstd]:x64-windows -> 1.83.0#1
  * boost-iterator:x64-windows -> 1.83.0
  * boost-lambda:x64-windows -> 1.83.0
  * boost-lexical-cast:x64-windows -> 1.83.0
  * boost-math:x64-windows -> 1.83.0
  * boost-mp11:x64-windows -> 1.83.0
  * boost-mpl:x64-windows -> 1.83.0
  * boost-multi-array:x64-windows -> 1.83.0
  * boost-multi-index:x64-windows -> 1.83.0
  * boost-numeric-conversion:x64-windows -> 1.83.0
  * boost-optional:x64-windows -> 1.83.0
  * boost-parameter:x64-windows -> 1.83.0
  * boost-phoenix:x64-windows -> 1.83.0
  * boost-pool:x64-windows -> 1.83.0
  * boost-predef:x64-windows -> 1.83.0
  * boost-property-map:x64-windows -> 1.83.0
  * boost-property-tree:x64-windows -> 1.83.0
  * boost-proto:x64-windows -> 1.83.0
  * boost-ptr-container:x64-windows -> 1.83.0
  * boost-random:x64-windows -> 1.83.0
  * boost-range:x64-windows -> 1.83.0
  * boost-ratio:x64-windows -> 1.83.0
  * boost-rational:x64-windows -> 1.83.0
  * boost-regex:x64-windows -> 1.83.0
  * boost-serialization:x64-windows -> 1.83.0
  * boost-signals2:x64-windows -> 1.83.0
  * boost-sort:x64-windows -> 1.83.0
  * boost-spirit:x64-windows -> 1.83.0
  * boost-system:x64-windows -> 1.83.0
  * boost-thread:x64-windows -> 1.83.0
  * boost-tokenizer:x64-windows -> 1.83.0
  * boost-tti:x64-windows -> 1.83.0
  * boost-type-index:x64-windows -> 1.83.0
  * boost-typeof:x64-windows -> 1.83.0
  * boost-unordered:x64-windows -> 1.83.0
  * boost-utility:x64-windows -> 1.83.0
  * boost-uuid:x64-windows -> 1.83.0
  * boost-variant:x64-windows -> 1.83.0
  * boost-variant2:x64-windows -> 1.83.0
  * boost-winapi:x64-windows -> 1.83.0
  * boost-xpressive:x64-windows -> 1.83.0
  * flann:x64-windows -> 2019-04-07#7
    pcl:x64-windows -> 1.13.1#1
  * qhull:x64-windows -> 8.0.2#4
  * zstd:x64-windows -> 1.5.5#2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
-- Setting "%HTTP_PROXY%" environment variables to "127.0.0.1:3213".
-- Setting "%HTTPS_PROXY%" environment variables to "127.0.0.1:3213".
Restored 0 package(s) from C:\Users\陈家辉\AppData\Local\vcpkg\archives in 1.33 ms. Use --debug to see more details.
Installing 1/76 boost-exception:x64-windows...
Building boost-exception:x64-windows...
-- Using cached boostorg-exception-boost-1.83.0.tar.gz.
-- Cleaning sources at D:/vcpkg-master/buildtrees/boost-exception/src/ost-1.83.0-e0db41e4c0.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg-master/downloads/boostorg-exception-boost-1.83.0.tar.gz
-- Using source at D:/vcpkg-master/buildtrees/boost-exception/src/ost-1.83.0-e0db41e4c0.clean
-- Getting CMake variables for x64-windows
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: D:/vcpkg-master/downloads/tools/cmake-3.27.1-windows/cmake-3.27.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j17
    Working Directory: D:/vcpkg-master/buildtrees/boost-exception/x64-windows-dbg
    See logs for more information:
      D:\vcpkg-master\buildtrees\boost-exception\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:139 (vcpkg_cmake_install)
  ports/boost-exception/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:168 (include)


error: building boost-exception:x64-windows failed with: BUILD_FAILED
Elapsed time to handle boost-exception:x64-windows: 5.1 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-exception
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[boost-exception]+Build+error&body=Copy+issue+body+from+D%3A%2Fvcpkg-master%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by JonLiu1993** [comment]
@xiuer-1573, Please provide error log:
````
D:\vcpkg-master\buildtrees\boost-exception\install-x64-windows-dbg-out.log
````

**Comment by xiuer-1573** [comment]
of course ,thank you
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/13294529/install-x64-windows-dbg-out.log)

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/13294533/install-x64-windows-dbg-out.log)

**Comment by JonLiu1993** [comment]
@xiuer-1573, Could you try it with a later version of VS? VS2019 or VS2022.

**Comment by xiuer-1573** [comment]
Hi,
now，i install VS2022,but it also error
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j17
    Working Directory: D:/vcpkg/buildtrees/boost-exception/x64-windows-dbg
    See logs for more information:
      D:\vcpkg\buildtrees\boost-exception\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:139 (vcpkg_cmake_install)
  ports/boost-exception/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:168 (include)


error: building boost-exception:x64-windows failed with: BUILD_FAILED
Elapsed time to handle boost-exception:x64-windows: 5.3 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-exception
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[boost-exception]+Build+error&body=Copy+issue+body+from+D%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

i provide error log :
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/13304516/install-x64-windows-dbg-out.log)
 thank you

**Comment by JonLiu1993** [comment]
`\³Â¼Ò»Ô\` It looks like the system doesn't recognize the name of this folder. What did you name it after?
````
    type "C:\Users\³Â¼Ò»Ô\AppData\Local\Temp\jam36cc7c04.000" > "D:\vcpkg\buildtrees\boost-exception\x64-windows-dbg\boost\standalone\msvc\943897acc6555446e7558f53bf1a3e85\msvc-setup.bat"

The system cannot find the path specified.
````

**Comment by JonLiu1993** [comment]
Ping @xiuer-1573 for response.
