### ISSUE TITLE
error: building [ qtwebengine:x64-windows ] failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Melio-1** [microsoft/vcpkg#34503]
PS P:\dev\vcpkg> git pull
Already up to date.

PS P:\dev\vcpkg> .\vcpkg update
Using local portfile versions. To update the local portfiles, use git pull.
No packages need updating.

CMake Warning at ports/qtwebengine/portfile.cmake:83 (message):
  Buildtree path 'P:/dev/vcpkg/buildtrees/qtwebengine' is too long.

  Consider passing --x-buildtrees-root=<shortpath> to vcpkg!

  Trying to use 'P:/dev/vcpkg/buildtrees/qtwebengine/../tmp'
Call Stack (most recent call first):
  scripts/ports.cmake:168 (include)

CMake Error at ports/qtwebengine/portfile.cmake:88 (message):
  Buildtree path is too long.  Build will fail! Pass
  --x-buildtrees-root=<shortpath> to vcpkg!
Call Stack (most recent call first):
  scripts/ports.cmake:168 (include)

error: building qtwebengine:x64-windows failed with: BUILD_FAILED
Elapsed time to handle qtwebengine:x64-windows: 30 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qtwebengine
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[qtwebengine]+Build+error&body=Copy+issue+body+from+P%3A%2Fdev%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by Osyotr** [comment]
> CMake Error at ports/qtwebengine/portfile.cmake:88 (message):
Buildtree path is too long. Build will fail! Pass
--x-buildtrees-root= to vcpkg!

Does that help?

**Comment by Melio-1** [comment]
> > CMake Error at ports/qtwebengine/portfile.cmake:88 (message):
> > Buildtree path is too long. Build will fail! Pass
> > --x-buildtrees-root= to vcpkg!
> 
> Does that help?

I've been change the build tree length in portfile.cmake and make it 28 instead of 22

**Comment by Melio-1** [comment]
> > CMake Error at ports/qtwebengine/portfile.cmake:88 (message):
> > Buildtree path is too long. Build will fail! Pass
> > --x-buildtrees-root= to vcpkg!
> 
> Does that help?

I've change Portfil.cmake and make buildtree length 28 instead of 22 or 23 and error message to 29 and it's works the error doesn't shown again I've slow internet connection so it will be take a couple of time to install

**Comment by Melio-1** [comment]
> now is build x64-windows dbg

**Comment by Melio-1** [comment]
> > > CMake Error at ports/qtwebengine/portfile.cmake:88 (message):
> > > Buildtree path is too long. Build will fail! Pass
> > > --x-buildtrees-root= to vcpkg!
> > 
> > 
> > Does that help?
> 
> I've change Portfil.cmake and make buildtree length 28 instead of 22 or 23 and error message to 29 and it's works the error doesn't shown again I've slow internet connection so it will be take a couple of time to install

CMake Warning at ports/qtwebengine/portfile.cmake:89 (message):
  Buildtree path 'P:/dev/vcpkg/buildtrees/qtwebengine' is too long.

  Consider passing --x-buildtrees-root=<shortpath> to vcpkg!

  Trying to use 'P:/dev/vcpkg/buildtrees/qtwebengine/../tmp'
Call Stack (most recent call first):
  scripts/ports.cmake:168 (include)


-- Downloading https://download.qt.io/archive/qt/6.5/6.5.3/submodules/qtwebengine-everywhere-src-6.5.3.tar.xz -> qtwebengine-everywhere-src-6.5.3.tar.xz...
-- Extracting source P:/dev/vcpkg/downloads/qtwebengine-everywhere-src-6.5.3.tar.xz
-- Using source at P:/dev/vcpkg/buildtrees/tmp/src/here-src-6-7aee9b8c3c.clean
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
CMake Warning at installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:318 (message):
  The following variables are not used in CMakeLists.txt:

      FEATURE_webengine_v8_snapshot_support

  Please recheck them and remove the unnecessary options from the
  `vcpkg_cmake_configure` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):
  installed/x64-windows/share/qtbase/qt_install_submodule.cmake:147 (vcpkg_cmake_configure)
  ports/qtwebengine/portfile.cmake:111 (qt_cmake_configure)
  scripts/ports.cmake:168 (include)


-- Building x64-windows-dbg

**Comment by dg0yt** [comment]
> I've change Portfil.cmake and make buildtree length 28 instead of 22 or 23 and error message to 29 and it's works  the error doesn't shown again I've slow internet connection so it will be take a couple of time to install

.. or it will show late in the build instead of early, but you want it that way.

**Comment by Melio-1** [comment]
> > I've change Portfil.cmake and make buildtree length 28 instead of 22 or 23 and error message to 29 and it's works  the error doesn't shown again I've slow internet connection so it will be take a couple of time to install
> 
> .. or it will show late in the build instead of early, but you want it that way.

i didn't get it? what do you mean?

**Comment by Melio-1** [comment]
> It is not a successful build until it is finished.
> 
> The proposed solution was to use a shorter path. But you reported that you simply disabled the check for the path length instead. So your build passed that early barrier, but later it will probably run into the underlying problem which was the reason for adding the path length check. (As far as I remember the usual error message is that some header wasn't found, so it is not obvious that the problem is caused by the path length.)

you're right, but why this message shown the path is too long?
i'm new to programming so i didn't understand the problem

**Comment by Neumann-A** [comment]
use `--x-buildtrees-root=P:/b/` in classic mode or put it into `VCPKG_INSTALL_OPTIONS` if you use manifest mode from cmake

**Comment by Melio-1** [comment]
> use `--x-buildtrees-root=P:/b/` in classic mode or put it into `VCPKG_INSTALL_OPTIONS` if you use manifest mode from cmake

I'm not using mainfest mode but i put it in short path but stacking in windows-dbg so i open the folder it's 27.6 GB right now i don't how much the size of this folder

**Comment by Melio-1** [comment]
> > use `--x-buildtrees-root=P:/b/` in classic mode or put it into `VCPKG_INSTALL_OPTIONS` if you use manifest mode from cmake
> 
> I'm not using mainfest mode but i put it in short path but stacking in windows-dbg so i open the folder it's 27.3 GB right now i don't how much the size of this folder

windows-dbg it's > 44 GB
windows-rel > 9 GB
all qtwebengine buildtree it's about 60 GB

**Comment by Melio-1** [comment]
> > > use `--x-buildtrees-root=P:/b/` in classic mode or put it into `VCPKG_INSTALL_OPTIONS` if you use manifest mode from cmake
> > 
> > 
> > I'm not using mainfest mode but i put it in short path but stacking in windows-dbg so i open the folder it's 27.3 GB right now i don't how much the size of this folder
> 
> windows-dbg it's > 44 GB windows-rel > 9 GB all qtwebengine buildtree it's about 60 GB

I do mistake by this  .\vcpkg.exe install qt:x64-windows --recurse  😢
