### ISSUE TITLE
Issue with static linking duktape

### ISSUE THREAD

**Issue by planaria** [Microsoft/vcpkg#3450]
I ran the following command successfully.
`vcpkg install duktape:x64-windows-static`

The generated header-file "duk_config.h" has the following line.
`#define DUK_F_DLL_BUILD 0`

I think that this line expects a static linking, but this flag will be referenced by `#if defined(DUK_F_DLL_BUILD)` not `#if DUK_F_DLL_BUILD`, so it will not work as expected.

I would like to fix it by changing the following lines in "duktape/portfile.cmake".

old:
```
if(VCPKG_LIBRARY_LINKAGE STREQUAL dynamic)
    string(REPLACE "// #undef DUK_F_DLL_BUILD" "#undef DUK_F_DLL_BUILD\n#define DUK_F_DLL_BUILD 1" CONTENT "${CONTENT}")
else()
    string(REPLACE "// #undef DUK_F_DLL_BUILD" "#undef DUK_F_DLL_BUILD\n#define DUK_F_DLL_BUILD 0" CONTENT "${CONTENT}")
endif()
```
new:
```
if(VCPKG_LIBRARY_LINKAGE STREQUAL dynamic)
    string(REPLACE "// #undef DUK_F_DLL_BUILD" "#undef DUK_F_DLL_BUILD\n#define DUK_F_DLL_BUILD" CONTENT "${CONTENT}")
else()
    string(REPLACE "// #undef DUK_F_DLL_BUILD" "#undef DUK_F_DLL_BUILD" CONTENT "${CONTENT}")
endif()
```

Please let me know if something is wrong since I have never used cmake.

**Comment by ras0219-msft** [comment]
Should be fixed by 3454 -- thanks for the PR!
