### ISSUE TITLE
[openimageio] Separate feature flags for tools and viewer

### ISSUE THREAD

**Issue by jreichel-nvidia** [microsoft/vcpkg#34556]
### Is your feature request related to a problem? Please describe.

The viewer "iv" is the only tool that depends on Qt. This pulls in a large number of dependencies, which is completely unnecessary for users that are only interested in the other tools but don't need the viewer.

### Proposed solution

Add another feature flag, e.g. "viewer", that controls building of the viewer.

Since the remaining tools do not require any additonal dependencies, one could also remove the "tools" feature flag and build/install them unconditionally. (This would also solve the problem when calling vcpkg_check_features() where the "tools" OR the "viewer" feature flag should enable OIIO_BUILD_TOOLS.)

**Comment by dg0yt** [comment]
> This would also solve the problem when calling vcpkg_check_features() where the "tools" OR the "viewer" feature flag should enable OIIO_BUILD_TOOLS.

There is no such problem.
What I see is an indication that the new feature "viewer" should depend on the feature "tools".

**Comment by JonLiu1993** [comment]
> Ok, fine for me. Is there some documentation how to express "feature A depends on feature B" in vcpkg, or an example?

You can refer to this: https://github.com/microsoft/vcpkg-docs/blob/fb2987c5399286524aa9afd2f4819353cee7f3eb/vcpkg/contributing/maintainer-guide.md#do-not-use-features-to-implement-alternatives

**Comment by dg0yt** [comment]
Your question was clear. In-port dependencies are expressed just like inter-port dependencies: You name the port and the feature(s), i.e. you get
~~~json
    "viewer": {
      "description": "Build openimageio viewer",
      "dependencies": [
        "opengl",
        {
          "name": "openimageio",
          "features": [
            "tools"
          ]
        },
        {
          "name": "qtbase",
          "default-features": false
        }
      ]
    },
