### ISSUE TITLE
[OpenBlas] Add feature to allow building of LAPACK using builtin implementation

### ISSUE THREAD

**Issue by SPKorhonen** [microsoft/vcpkg#34562]
### Is your feature request related to a problem? Please describe.

Many projects using OpenBlas can also use LAPACK routines from the library if they are build into OpenBlas. This is controlled by option "BUILD_WITHOUT_LAPACK" which is turned on for vcpkg build, It can be a pain to add a separate LAPACK implementation and some projects need modifications to support this.

### Proposed solution

Add feature "lapack" into OpenBlas port which turns the option "BUILD_WITHOUT_LAPACK" ON/OFF depending whether the feature is included or not.

I have implemented this on custom fork of vcpkg and modification seems to be working. I could submit a PR for this.

Also the cblas interface is build by default. It can be turned ON/OFF by using BUILD_WITHOUT_CBLAS which could be also added as a feature

### Describe alternatives you've considered

Alternative is to add a separate LAPACK implementation to project being compiled and to edit build scripts to support this,

**Comment by Neumann-A** [comment]
Not possible currently since alternatives are yet to be implemented. And is the openblas lapack not just a copy of the netlib lapack anyway?
