### ISSUE TITLE
[boost-python] Feature to install pip/numpy for vcpkg installed python installation

### ISSUE THREAD

**Issue by SPKorhonen** [microsoft/vcpkg#34565]
### Is your feature request related to a problem? Please describe.

Currently boost-python build process pulls the numpy required to build boost-python the wrappers for numpy from external python installation which could incompatibilities.

### Proposed solution

One could add a feature "numpy" to boost-python which would use the vcpkg installed python to install pip via ensurepip and subsequently to install numpy via pip which can then be used to build boost-python.

By default we could install either latest version of numpy or a specific hard-coded version. There could also be an environmental variable like VCPKG_NUMPY_VERSION which can be used to specify the desired version.

I have implemented this in a fork of vcpkg and could submit a PR.

### Describe alternatives you've considered

The current work-around is to keep a compatible version of python and numpy so that the jam build system finds the required numpy installation from external source outside of vcpkg.

**Comment by Neumann-A** [comment]
I have an overlay for numpy: https://github.com/Neumann-A/my-vcpkg-ports/tree/master/numpy but you also need an overlay for boost pulling in it.
