### ISSUE TITLE
[intel-mkl] Add feature(s) to support installation of both ilp64 and lp64 versions of MKL

### ISSUE THREAD

**Issue by SPKorhonen** [microsoft/vcpkg#34564]
### Is your feature request related to a problem? Please describe.

Currently the intel-mkl port install only "ilp64" version of MKL. There are projects which require the "lp64" version which can't use intel-mkl without modifications.

Is there a particular reason why the intel-mkl port install only a small subset of ML versions available in packages downloaded from Intel? The main issue I would see is that some of the libraries are rather large and will significantly increase the install size.

### Proposed solution

The simplest solution would be to just install all versions of MKL provided by the packages downloaded from Intel. Alternatively the different versions could be gated using features like "ilp64" and "lp64".

### Describe alternatives you've considered

One may either install a stand-alone MKL outside of vcpkg. Alternatively one can modify the the project code and build scripts to support the "ilp64" interface.

**Comment by Neumann-A** [comment]
> Is there a particular reason why the intel-mkl port install only a small subset of ML versions available in packages downloaded from Intel?

Because you can only link one consistently. Allowing to select one of them requires the options PR. If you want to switch just provide an overlay and change the one line in the portfile which decides between ILP and LP version.

**Comment by SPKorhonen** [comment]
I'm not sure I follow...

The ilp64 and lp64 interfaces have different libraries and you can select one or the other to link. I can select one or the other using CMake find_package(BLAS/LAPACK) by setting the relevant BLA_SIZEOF_INTEGER and BLA_VENDOR variables

**Comment by Neumann-A** [comment]
> The ilp64 and lp64 interfaces have different libraries

different libs but same symbols.

**Comment by SPKorhonen** [comment]
Yes, but any project that already uses oneAPI needs to select which version of the installed MKL libs to link against. Is there a particular reason not to use already existing build tooling to handle this issue?

**Comment by Neumann-A** [comment]
> Yes, but any project that already uses oneAPI needs to select which version of the installed MKL libs to link against.

Be aware that the MSbuild integration links `*.lib`. vcpkg does not allow to install libs with conflicting symbols due to that. 

> For example the FindBLAS/FindLAPACK in CMake allow making this selection on the fly

vcpkg BLAS/LAPACK cannot allow that. There can only be one true implementation. (ODR)
