### ISSUE TITLE
[raygui] Improve on help text for header only ports

### ISSUE THREAD

**Issue by Andersama** [microsoft/vcpkg#34580]
### Is your feature request related to a problem? Please describe.

There appear to be a few packages / ports which report something like:
```
raygui is header-only and can be used from CMake via:

    find_path(RAYGUI_INCLUDE_DIRS "raygui.h")
    target_include_directories(main PRIVATE ${RAYGUI_INCLUDE_DIRS})
```

Unlike most packages which report something like:
```
raylib provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(raylib CONFIG REQUIRED)
    target_link_libraries(main PRIVATE raylib)
```

While the later after some modification generally tends to work, it's not so obvious what to modify for the former. I can only guess that there are additional CMake commands missing before the two lines would otherwise function, or that it requires configuring variables. It seems the correct approach for this port is to define the variable as vcpkg's include directory (which is where the headers appear to be kept).

### Proposed solution

If what I suspect is correct, consider adding a comment to make it clear that the vcpkg include directory needs to be added if possible rewrite the heuristics to include the additional commands that may do this automatically.

**Comment by dg0yt** [comment]
> If what I suspect is correct, consider adding a comment to make it clear that the vcpkg include directory needs to be added if possible rewrite the heuristics to include the additional commands that may do this automatically.

AFAICS the suggested usage does exactly that: add the desired include path for building target `main`. 
Of course it is assumed that you use the vcpkg cmake toolchain.

**Comment by Andersama** [comment]
Well that's the confusing aspect for me is that typically working with vcpkg and find_package and more complicated projects the hints work with minimal modification changing the target. Here `find_path` doesn't seem to do anything different than normal, I'd expect that with the vcpkg toolchain that find_path would be looking through vcpkg's include directory, but it doesn't seem to. Which means in addition to modifying the command a bit, the user needs to set a cmake variable manually which isn't nearly as smooth an experience, especially if you say didn't know how vcpkg organizes files.

**Comment by dg0yt** [comment]
>  I'd expect that with the vcpkg toolchain that find_path would be looking through vcpkg's include directory, but it doesn't seem to. 

`find_path` etc. do work. Otherwise vcpkg couldn't interact with any Find modules. 
Of course it is assumed that you use the vcpkg cmake toolchain.

**Comment by Andersama** [comment]
If `find_path`'s supposed to be like `find_package` and it's all just supposed to work smoothly then something went wrong in my project because I've got other things brought in via find_package and they're not causing problems.

I've got vcpkg integrated with MSVC so the toolchain's supposed to be incorporated for any cmake project.
