### ISSUE TITLE
qt5 include directories possibly not set properly for direct use in VS

### ISSUE THREAD

**Issue by elmewo** [microsoft/vcpkg#3460]
I installed qt5 via `vcpkg install qt5:x64-windows` on a Windows 10 1803 64bit machine after integrating vcpkg with `vcpkg integrate install`. 

Then I tried to test the install in a plain VS project straight away by trying to `#include <QApplication>` which couldn't be found, but `#include <QtWidgets/QApplication>` works. Point is that this breaks builds because the qt5-headers also e.g. `#include <QPointer>` instead of the file in the subfolder `#include <QtCore/QPointer>`. 

However, when generating a Visual Studio 2017 project with the respective CMake generator and providing the toolchain file, the includes work properly. 

That being said I guess the Qt include directories are not handled properly somwhere in the install process so that the subfolders need to be referenced in plain VS projects.

Correct behaviour should be to include the files directly instead of subfolders.

**Comment by JackBoosY** [comment]
Hi @elmewo, thanks for reporting this issue!
Since qt5 has been updated to 5.12.5, can you update vcpkg and repro this issue?

Thanks.

**Comment by Neumann-A** [comment]
@JackBoosY This cannot be solved in `vcpkg integrate install`. The Qt subdirs must be manually added to the include list if plain VS is used. It has nothing to do with the installation of the port itself. Alternatively tools like QtVSTools can be tried to add those subdirs automatically.

**Comment by JackBoosY** [comment]
@Neumann-A Yes, that's right.
@elmewo Please add the qt5 component subdirectory to your project.

Thanks.
