### ISSUE TITLE
apr-util port installs broken header which prevents static linking

### ISSUE THREAD

**Issue by gix** [Microsoft/vcpkg#3462]
The portfile for apr-util modifies `apu.h` and replaces `defined(APU_DECLARE_EXPORT)` or `defined(APU_DECLARE_STATIC)` with `1`. This modification makes its way into the installed header. As a consequence linking with `aprutil-1.lib` results in unresolved externals because the exported data is not marked `dllimport` and the linker does not pick them up automatically as is the case for functions.

**Comment by JackBoosY** [comment]
Hi @gix , thanks for reporting this issue!
I've fixed this issue, please update and rebuild apr-util.
Thanks.
