### ISSUE TITLE
vcpkg ignores overlay-ports in linux (maybe in CMake)

### ISSUE THREAD

**Issue by AndreyAlifanov** [microsoft/vcpkg#34626]
I try to use overlay-ports in my project with vcpkg in manifest mode.
I have vcpkg.json and vcpkg-configuration.json. I wrote relative path to my custom port. And it works like a charm in Windows (in MSBuild environment).
But when I try to use it in Linux with CMake, I've got error message `Overlay path "/home/user/Dev/src/overlays" must exist and must be a directory`.
What can I do to resolve this issue? Why vcpkg ignores my settings and tries to use default directory?

My json-configuration.json file is very simple:
```json
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg-configuration.schema.json",
  "overlay-ports": [
    "./vcpkg-custom-ports"
  ]
}
```
**Environment**
- OS: Based on Debian GNU/Linux x64_86
- vcpkg: 2023.10.19 Release

**Expected behavior**
I expect, vcpkg correctly uses custom ports directory/directories.

**Comment by MonicaLiu0311** [comment]
Please provide your vcpkg.json file.

**Comment by AndreyAlifanov** [comment]
```json
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg.schema.json",
  "builtin-baseline": "84296312ba9a00ab11a56ea210e3b14d061a9db3",
  "dependencies": [
    {
      "name": "boost-algorithm",
      "platform": "(windows & !static) | linux"
    },
    {
      "name": "boost-asio",
      "platform": "(windows & !static) | linux"
    },
    {
      "name": "boost-assign",
      "platform": "(windows & !static) | linux"
    },
    {
      "name": "boost-container"
    },
    {
      "name": "boost-format",
      "platform": "(windows & !static) | linux"
    },
    {
      "name": "boost-functional",
      "platform": "(windows & !static) | linux"
    },
    {
      "name": "boost-graph",
      "platform": "(windows & !static) | linux"
    },
    {
      "name": "boost-iostreams",
      "platform": "(windows & !static) | linux"
    },
    {
      "name": "boost-lexical-cast",
      "platform": "(windows & !static) | linux"
    },
    {
      "name": "boost-multi-index",
      "platform": "(windows & !static) | linux"
    },
    {
      "name": "boost-optional",
      "platform": "(windows & !static) | linux"
    },
    {
      "name": "boost-program-options",
      "platform": "(windows & !static) | linux"
    },
    {
      "name": "boost-regex"
    },
    {
      "name": "boost-spirit",
      "platform": "(windows & !static) | linux"
    },
    {
      "name": "boost-signals2",
      "platform": "(windows & !static) | linux"
    },
    {
      "name": "boost-utility",
      "platform": "(windows & !static) | linux"
    },
    {
      "name": "boost-uuid",
      "platform": "(windows & !static) | linux"
    },
    {
      "name": "boost-variant",
      "platform": "(windows & !static) | linux"
    },
    {
      "name": "curl",
      "platform": "(windows & !static) | linux",
      "default-features": false
    },
    {
      "name": "fmt"
    },
    {
      "name": "libgit2",
      "platform": "(windows & !static) | linux"
    },
    {
      "name": "libpng",
      "platform": "(windows & !static) | linux"
    },
    {
      "name": "minizip",
      "default-features": false
    },
    {
      "name": "openssl",
      "platform": "windows & !static"
    },
    {
      "name": "sqlite3",
      "platform": "(windows & !static) | linux"
    },
    {
      "name": "websocketpp",
      "platform": "(windows & !static) | linux",
      "default-features": false
    },
    {
      "name": "zlib"
    }
  ],
  "overrides": [
    {
      "name": "boost-algorithm",
      "version": "1.83.0"
    },
    {
      "name": "boost-asio",
      "version": "1.83.0"
    },
    {
      "name": "boost-assign",
      "version": "1.83.0"
    },
    {
      "name": "boost-bimap",
      "version": "1.83.0"
    },
    {
      "name": "boost-container",
      "version": "1.83.0"
    },
    {
      "name": "boost-format",
      "version": "1.83.0"
    },
    {
      "name": "boost-functional",
      "version": "1.83.0"
    },
    {
      "name": "boost-graph",
      "version": "1.83.0"
    },
    {
      "name": "boost-iostreams",
      "version": "1.83.0"
    },
    {
      "name": "boost-lexical-cast",
      "version": "1.83.0"
    },
    {
      "name": "boost-multi-index",
      "version": "1.83.0"
    },
    {
      "name": "boost-program-options",
      "version": "1.83.0"
    },
    {
      "name": "boost-regex",
      "version": "1.83.0"
    },
    {
      "name": "boost-signals2",
      "version": "1.83.0"
    },
    {
      "name": "boost-spirit",
      "version": "1.83.0"
    },
    {
      "name": "boost-variant",
      "version": "1.83.0"
    },
    {
      "name": "boost-utility",
      "version": "1.83.0"
    },
    {
      "name": "boost-uuid",
      "version": "1.83.0"
    },
    {
      "name": "curl",
      "version": "8.4.0"
    },
    {
      "name": "fmt",
      "version": "10.1.1"
    },
    {
      "name": "libgit2",
      "version": "1.6.4"
    },
    {
      "name": "libpng",
      "version": "1.6.39"
    },
    {
      "name": "minizip",
      "version-string": "1.3#2"
    },
    {
      "name": "openssl",
      "version-string": "1.1.1n#1"
    },
    {
      "name": "sqlite3",
      "version": "3.43.1"
    },
    {
      "name": "websocketpp",
      "version": "0.8.2"
    },
    {
      "name": "zlib",
      "version": "1.3"
    }
  ]
}
```

I have my custom port for minizip. It resides in `./vcpkg-custom-ports/minizip`

**Comment by AndreyAlifanov** [comment]
And what's next?

**Comment by MonicaLiu0311** [comment]
Sorry I'm late.

If your custom port directory `vcpkg-custom-ports/` and `vcpkg.json` and `vcpkg-configuration.json` are placed in the top-level directory of the source code (at the same level as `CMakeLists.txt`), you can use the following relative paths:
```
   "overlay-ports": [
     "./vcpkg-custom-ports"
   ]
```

If your custom port directory `vcpkg-custom-ports` is placed in the vcpkg top-level directory (at the same level as `vcpkg.exe`), it is best to use an absolute path, for example:
```
   "overlay-ports": [
     "/home/user/Dev/src/vcpkg/vcpkg-custom-ports"
   ]
```

**Comment by AndreyAlifanov** [comment]
I do exactly this thing.
My custom ports directory is placed in top-level directory of source code.
And it works only with default name: "vcpkg-custom-ports", but I want to use my own name.
It works with msbuild, but with cmake - not.

**Comment by MonicaLiu0311** [comment]
> I do exactly this thing.
> My custom ports directory is placed in top-level directory of source code.

I built it successfully according to the data you gave (there is no custom `minizip` port here, but a simple `jsoncpp` port is chosen as an example):
```
/mnt
    vcpkg/
        vcpkg-custom-ports/
            jsoncpp/
                vcpkg.json
                portfile.cmake
    test/
        vcpkg.json
        vcpkg-configuration.json
        CMakeLists.txt
        test.cpp
        build/
```
<details>
<summary><b>vcpkg.json</b></summary>
<pre>
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg.schema.json",
  "builtin-baseline": "84296312ba9a00ab11a56ea210e3b14d061a9db3",
  "dependencies": [
    {
      "name": "jsoncpp"
    },
    {
      "name": "zlib"
    }
  ],
  "overrides": [
    {
      "name": "jsoncpp",
      "version-string": "1.9.6"
    },
    {
      "name": "zlib",
      "version": "1.3"
    }
  ]
}
</pre></details>

<details>
<summary><b>vcpkg-configuration.json</b></summary>
<pre>
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg-configuration.schema.json",
  "overlay-ports": [
    "/mnt/vcpkg/vcpkg-custom-ports"
  ]
}
</pre></details>

![image](https://github.com/microsoft/vcpkg/assets/110024546/86485c6c-8e43-4a3d-b2a2-c16795142981)

> And it works only with default name: "vcpkg-custom-ports", but I want to use my own name.
> It works with msbuild, but with cmake - not.

You can rename it however you like, as follows:
![image](https://github.com/microsoft/vcpkg/assets/110024546/1afbc7b0-b334-4b20-a054-662f69e119bc)

**Comment by AndreyAlifanov** [comment]
Yes, now it works. With updated vcpkg version.
It didn't work at the moment of issue creation.

**Comment by dg0yt** [comment]
> Yes, now it works. With updated vcpkg version.
> It didn't work at the moment of issue creation.

Did you have to change 
~~~
"overlay-ports": [
     "./vcpkg-custom-ports"
   ]
~~~

IMO the proposed change to an absolute path is not acceptable.

**Comment by AndreyAlifanov** [comment]
> > Yes, now it works. With updated vcpkg version.
> > It didn't work at the moment of issue creation.
> 
> Did you have to change
> 
> ```
> "overlay-ports": [
>      "./vcpkg-custom-ports"
>    ]
> ```
> 
> IMO the proposed change to an absolute path is not acceptable.

Yes, I use relative path to my source code tree.
