### ISSUE TITLE
[SDL2] Running CMake configuration RelWithDebInfo causes error

### ISSUE THREAD

**Issue by jesta88** [microsoft/vcpkg#3463]
![image](https://user-images.githubusercontent.com/5116779/39781695-f7b4552a-52dd-11e8-9032-bef8d1a7fcdd.png)

Works fine in Debug and Release configurations.

**Comment by danganea** [comment]
This is also the case for me. I see SDL2d.dll is not copied in the binary directory in the case of RelWithDebInfo.

**Comment by danganea** [comment]
It seems that even if RelWithDebInfo is considered release, Additional Dependencies uses debug libs (\x64-windows\debug\lib\) for example.

      <AdditionalDependencies>C:\vcpkg\vcpkg\installed\x64-windows\debug\lib\imguid.lib;C:\vcpkg\vcpkg\installed\x64-windows\debug\lib\SDL2d.lib;C:\vcpkg\vcpkg\installed\x64-windows\debug\lib\manual-link\SDL2maind.lib;user32.lib;gdi32.lib;winmm.lib;imm32.lib;ole32.lib;oleaut32.lib;version.lib;uuid.lib;dinput8.lib;kernel32.lib;user32.lib;gdi32.lib;winspool.lib;shell32.lib;ole32.lib;oleaut32.lib;uuid.lib;comdlg32.lib;advapi32.lib</AdditionalDependencies>

**Comment by Neumann-A** [comment]
solved by #5543

**Comment by NancyLi1013** [comment]
Hi @jesta88, thanks for posting this issue. It's duplicated with #2559.
