### ISSUE TITLE
[openldap] Build error

### ISSUE THREAD

**Issue by RainbowTaro2022** [microsoft/vcpkg#34653]
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: G:/Cone/vcpkg/downloads/tools/msys2/d7266db249278763/usr/bin/bash.exe --noprofile --norc --debug -c "V=1 CPP='compile cl.exe -E' CC='compile cl.exe' CC_FOR_BUILD='compile cl.exe' CPP_FOR_BUILD='compile cl.exe -E' CXX_FOR_BUILD='compile cl.exe' CXX='compile cl.exe' RC='windres-rc rc.exe' WINDRES='windres-rc rc.exe' AR='ar-lib lib.exe' LD='link.exe -verbose' RANLIB=':' STRIP=':' NM='dumpbin.exe -symbols -headers' DLLTOOL='link.exe -verbose -dll' CCAS=':' AS=':' ./../src/openldap-2-83710ce236.clean/configure --build=x86_64-pc-mingw32 \"--without-cyrus-sasl\" \"--disable-cleartext\" \"--disable-mdb\" \"--disable-relay\" \"--disable-slapd\" \"--disable-syncprov\" \"--with-tls=openssl\" \"--without-systemd\" \"--without-fetch\" \"--without-argon2\" \"ac_cv_lib_iodbc_SQLDriverConnect=no\" \"ac_cv_lib_odbc_SQLDriverConnect=no\" \"ac_cv_lib_odbc32_SQLDriverConnect=no\" \"ac_cv_prog_ac_ct_STRIP=:\" \"gl_cv_double_slash_root=yes\" \"ac_cv_func_memmove=yes\" \"--enable-shared\" \"--disable-static\" \"--prefix=/G/Cone/vcpkg/installed/x64-windows/debug\" \"--bindir=\\${prefix}/../tools/openldap/debug/bin\" \"--sbindir=\\${prefix}/../tools/openldap/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/openldap\""
    Working Directory: G:/Cone/vcpkg/buildtrees/openldap/x64-windows-dbg
    Error code: 1
    See logs for more information:
      G:\Cone\vcpkg\buildtrees\openldap\config-x64-windows-dbg-config.log
      G:\Cone\vcpkg\buildtrees\openldap\config-x64-windows-dbg-out.log
      G:\Cone\vcpkg\buildtrees\openldap\config-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:838 (vcpkg_execute_required_process)
  ports/openldap/portfile.cmake:38 (vcpkg_configure_make)
  scripts/ports.cmake:168 (include)

**Comment by RainbowTaro2022** [comment]
[config-x64-windows-dbg-config.log](https://github.com/microsoft/vcpkg/files/13062320/config-x64-windows-dbg-config.log)
[config-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/13062321/config-x64-windows-dbg-err.log)
[config-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/13062322/config-x64-windows-dbg-out.log)

**Comment by dg0yt** [comment]
Works "as expected". x64-windows is not in the set of supported platforms.
https://github.com/microsoft/vcpkg/blob/830f86fb309ad7167468a433a890b7415fbb90a5/ports/openldap/vcpkg.json#L8

**Comment by RainbowTaro2022** [comment]
The window says' mingw 'after it,
This means that msys2 can be used for complete compilation

**Comment by dg0yt** [comment]
> The window says' mingw 'after it, This means that msys2 can be used for complete compilation

`mingw` means that a compiler based on the MinGW-w64 runtime (maybe even MinGW) can be used to compile this package. It is somewhat related to the msys2 tools. But `mingw` does not mean you can use a compiler which doesn't provide a mingw runtime, such as MSVC (x64-windows).

**Comment by RainbowTaro2022** [comment]
Can you port the complete msys2 to vcpkg?

**Comment by RainbowTaro2022** [comment]
I can't find the Windows package in openldap.org

**Comment by RainbowTaro2022** [comment]
![image](https://github.com/microsoft/vcpkg/assets/42478088/a3d63bed-6acb-4f68-95e9-4ee5e99e29ec)
I took a look and found that there is indeed openldap in vcpkg

However, no packages with Windows can be found on the official website

So, can we think of porting Openldap to Windows? This idea should be possible

**Comment by jimwang118** [comment]
You can consult the upstream official `openldap` whether it supports porting to windows.

**Comment by dg0yt** [comment]
mingw: provides some POSIX runtime functions on top of native windows.
msys2: provides some Unix tools on top of mingw.
vcpgk: Use msys tools for some builds on windows. Can use mingw with mingw triplets and toolchains.

> Can you port the complete msys2 to vcpkg?

No.

> I can't find the Windows package in openldap.org

Because openldap isn't supported on native Windows.

> So, can we think of porting Openldap to Windows? This idea should be possible

The idea is possible. But it needs work on the upstream source code. Once it upstream supports it, we can enable windows in the vcpkg port.

That's a lot to write down just to repeat what the vcpkg port has already declared.

**Comment by jimwang118** [comment]
@RainbowTaro2022 Do you want to adapt `openldap` yourself to compile on the windows platform?

**Comment by RainbowTaro2022** [comment]
> @RainbowTaro2022 Do you want to adapt `openldap` yourself to compile on the windows platform?

sure

**Comment by RainbowTaro2022** [comment]
i found an error

/usr/lib/gcc/x86_64-pc-msys/13.2.0/../../../../x86_64-pc-msys/bin/ld: libbackends.a(mdbmdb.o): in function `mdb_mutex_failed':
/g/Cone/openldap-2.6.6/servers/slapd/back-mdb/./../../../libraries/liblmdb/mdb.c:10311:(.text.unlikely+0x313): undefined reference to `pthread_mutex_consistent'
/usr/lib/gcc/x86_64-pc-msys/13.2.0/../../../../x86_64-pc-msys/bin/ld: libbackends.a(mdbmdb.o): in function `mdb_env_setup_locks':
/g/Cone/openldap-2.6.6/servers/slapd/back-mdb/./../../../libraries/liblmdb/mdb.c:4924:(.text.unlikely+0x734): undefined reference to `pthread_mutexattr_setrobust'

**Comment by RainbowTaro2022** [comment]
i use msys2

1. ./configure C=cl.exe CXX=cl.exe --prefix=/g/OpenLDAP-windows/
2. make depend
3. make

and an error

**Comment by dg0yt** [comment]
You are building binaries for the MSYS environment. This is not native windows, even less than mingw: It uses a cygwin-based CRT.  
https://www.msys2.org/docs/environments/

> MSYS2 comes with different environments and the first thing you have to decide is which one to use. The differences among the environments are mainly environment variables, default compilers/linkers, architecture, system libraries used etc. If you are unsure, go with UCRT64.
>
> The MSYS environment contains the unix-like/cygwin based tools, lives under /usr and is special in that it is always active. All the other environments inherit from the MSYS environment and add various things on top of it.

Even msys2 doesn't build openldap for the MSYS environment. They build openldap for mingw-w64 environments, with three patches.
https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-openldap

**Comment by RainbowTaro2022** [comment]
> You are building binaries for the MSYS environment. This is not native windows, even less than mingw: It uses a cygwin-based CRT. https://www.msys2.org/docs/environments/
> 
> Even msys2 doesn't build openldap for the MSYS environment. They build openldap for mingw-w64 environments, with three patches. https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-openldap

shouid i use cygwin?

**Comment by dg0yt** [comment]
I don't think that cygwin, msys or mingw is what you want to have openldap for. Unless you already know what these environments mean.

**Comment by RainbowTaro2022** [comment]
i sorry
i can make a idea

**Comment by RainbowTaro2022** [comment]
I've been planning my own game these days
This game is about people with disabilities
I can't think of a good way to handle this

**Comment by RainbowTaro2022** [comment]
I have always claimed to be a code wizard
But in fact, I'm just an ordinary person

**Comment by jimwang118** [comment]
@RainbowTaro2022 Will you continue to adapt this port to the Windows platform?

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
