### ISSUE TITLE
Installing PCL on Linux fails

### ISSUE THREAD

**Issue by semawah** [microsoft/vcpkg#3466]
Installation of PCL on Ubuntu fails on a number of issues.

Overcame some of them by modifying the port files of vtk Qhull and flann.

I do not manage to overcome the issue of the PCL CMake-file not being able to locate OpenGL.

Package: pcl:x64-linux
Vcpkg version: 0.0.110-unknownhash

Attaching logs.

[config-x64-linux-dbg-out.log](https://github.com/Microsoft/vcpkg/files/1987117/config-x64-linux-dbg-out.log)
[config-x64-linux-dbg-err.log](https://github.com/Microsoft/vcpkg/files/1987118/config-x64-linux-dbg-err.log)

Thankful for help.

**Comment by cbezault** [comment]
Hopefully #7413 fixed this.
