### ISSUE TITLE
[qtbase]unable to locate ICU library icuind73.dll using windeployqt.debug.bat

### ISSUE THREAD

**Issue by QiuYilin** [microsoft/vcpkg#34671]
**Describe the bug**
windeployqt.debug.bat failed to locate icuind73 but the dll already exists in the app dir.

**Environment**
- OS: Windows
- Compiler: MSVC 2022

**To Reproduce**
1. (path to vcpkg)/packages/qtbase_x64-windows/tools/Qt6/bin/windeployqt.debug.bat  app.exe

**Expected behavior**
windeployqt.exe should finish deploying .

**Failure logs**

```

[build] EXEC : warning : Translations will not be available due to the following error. [C:\program_on_git\APP\app.vcxproj]
[build]   Cannot open C:/program_on_git/SFR/sfr-vcpkg/packages/qtbase_x64-windows/translations/Qt6/catalogs.json
[build]   C:\program_on_git\APP\app\build\bin\Debug\app.exe 64 bit, debug executable
[build]   Unable to locate ICU library icuind73.dll

```

**Additional context**

But icuind73.dll has been copied to the app directory.

**Comment by Cheney-W** [comment]
@QiuYilin Could you provide an `app.exe` to reproduce the issue?

**Comment by taibai123abc** [comment]
I meet the same question.
