### ISSUE TITLE
[itk] build failure

### ISSUE THREAD

**Issue by sapaksa** [microsoft/vcpkg#34691]
### Operating system

Windows 10 home

### Compiler

MSVC++ 2019, cuda v11.7

### Steps to reproduce the behavior

```Shell
vcpkg install itk[rtk]:x64-windows
```

### Failure logs

E:\vcpkg>vcpkg install itk[rtk]:x64-windows --recurse
warning: The vcpkg E:\vcpkg\vcpkg.exe is using detected vcpkg root E:\vcpkg and ignoring mismatched VCPKG_ROOT environment value "E:\vcpkg". To suppress this message, unset the environment variable or use the --vcpkg-root command line switch.
Computing installation plan...
The following packages will be rebuilt:
    itk[core,cuda,opencl,rtk]:x64-windows -> 5.3rc02
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\sapak\AppData\Local\vcpkg\archives in 479 us. Use --debug to see more details.
Removing 1/2 itk:x64-windows
Elapsed time to handle itk:x64-windows: 900 ms
Installing 2/2 itk:x64-windows...
Building itk[core,cuda,opencl,rtk]:x64-windows...
-- Using cached InsightSoftwareConsortium-ITK-v5.3rc02.tar.gz.
-- Cleaning sources at E:/vcpkg/buildtrees/itk/src/v5.3rc02-2745f7bb96.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/vcpkg/downloads/InsightSoftwareConsortium-ITK-v5.3rc02.tar.gz
-- Applying patch double-conversion.patch
-- Applying patch openjpeg.patch
-- Applying patch openjpeg2.patch
-- Applying patch var_libraries.patch
-- Applying patch wrapping.patch
-- Applying patch opencl.patch
-- Applying patch use-the-lrintf-intrinsic.patch
-- Applying patch dont-build-gtest.patch
-- Applying patch cxx17.patch
-- Using source at E:/vcpkg/buildtrees/itk/src/v5.3rc02-2745f7bb96.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
CMake Warning at installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:318 (message):
  The following variables are not used in CMakeLists.txt:

      BUILD_PKGCONFIG_FILES
      DCMTK_USE_ICU
      INSTALL_GTEST
      ITK_USE_SYSTEM_GOOGLETEST
      ITK_USE_SYSTEM_ICU
      ITK_USE_SYSTEM_SWIG

  Please recheck them and remove the unnecessary options from the
  `vcpkg_cmake_configure` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):
  ports/itk/portfile.cmake:127 (vcpkg_cmake_configure)
  scripts/ports.cmake:168 (include)

CMake Deprecation Warning at scripts/ports.cmake:98 (message):
  vcpkg_apply_patches has been deprecated in favor of the `PATCHES` argument
  to `vcpkg_from_*`.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_apply_patches.cmake:2 (z_vcpkg_deprecation_message)
  ports/itk/portfile.cmake:189 (vcpkg_apply_patches)
  scripts/ports.cmake:168 (include)

-- Applying patch rtk/already_defined.patch
-- Applying patch rtk/unresolved.patch
-- Applying patch rtk/Add-missing-include-for-Cuda.patch
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
    Working Directory: E:/vcpkg/buildtrees/itk/x64-windows-dbg
    See logs for more information:
      E:\vcpkg\buildtrees\itk\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/itk/portfile.cmake:191 (vcpkg_cmake_install)
  scripts/ports.cmake:168 (include)

error: building itk:x64-windows failed with: BUILD_FAILED
Elapsed time to handle itk:x64-windows: 6.4 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+itk
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[itk]+Build+error&body=Copy+issue+body+from+E%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/13111857/install-x64-windows-dbg-out.log)

**Comment by jimwang118** [comment]
`nvcc fatal   : Unsupported gpu architecture 'compute_30'`
According to the error log, your GPU does not support the current version of `CUDA`. Please check the `CUDA` version supported by your GPU.

**Comment by sapaksa** [comment]
C:\Users\sapak>nvidia-smi
Wed Oct 25 12:51:46 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.84                 Driver Version: 545.84       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1050      WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   47C    P0              N/A / ERR! |      0MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

-gencode;arch=compute_30,code=sm_30;  <--- This item seems to be interfering with my build. Installing CUDA version 10.2 gives another error:
 The graphics card is using gtx1050.
 What is the exact installation environment?

**Comment by jimwang118** [comment]
The `GTX 1050` graphics card supports up to `CUDA` version `11.4`, so you should install a `CUDA` version less than or equal to `11.4` so that the GPU can be correctly identified.

**Comment by sapaksa** [comment]
Even if I reset the cuda version to 11.4, the same problem still appears.

Searching the Internet, I found that Compute_30 was removed from cuda 10.2 and later versions.

How can I install it?


E:\vcpkg\buildtrees\itk\src\v5.3rc02-2745f7bb96.clean\Modules\Remote\RTK\cmake\FindCUDA_wrap.cmake 

if("${CUDA_VERSION}" VERSION_LESS 8.0)
 set(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS}
     -gencode arch=compute_20,code=sm_20
     -gencode arch=compute_30,code=sm_30
     -gencode arch=compute_35,code=sm_35
     -gencode arch=compute_35,code=compute_35
     )
elseif("${CUDA_VERSION}" VERSION_LESS 9.0)
 set(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS}
     -Wno-deprecated-gpu-targets
     -gencode arch=compute_20,code=sm_20
     -gencode arch=compute_30,code=sm_30
     -gencode arch=compute_35,code=sm_35
     -gencode arch=compute_35,code=compute_35
     )
else()
 set(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS}
     -gencode arch=compute_30,code=sm_30                                           <<---------- This item seems to be problematic.
     -gencode arch=compute_35,code=sm_35
     -gencode arch=compute_35,code=compute_35
     )
endif()

**Comment by jimwang118** [comment]
You can download and install it from the `cuda` official website.

**Comment by sapaksa** [comment]
cuda has already been installed separately.
I was using version 12, but it didn't seem to work because the version was too high, so I reinstalled 11.4.

**Comment by jimwang118** [comment]
Can you compile normally if you install version 11.4 of `cuda` now?

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
