### ISSUE TITLE
Installing PCL on windows failed

### ISSUE THREAD

**Issue by flyingsalmon** [Microsoft/vcpkg#3470]
-- Downloading http://download.savannah.gnu.org/releases/freetype/freetype-2.8.1.tar.bz2...
-- Downloading http://download.savannah.gnu.org/releases/freetype/freetype-2.8.1.tar.bz2... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:155 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/freetype/portfile.cmake:4 (vcpkg_download_distfile)
  scripts/ports.cmake:72 (include)

Error: Building package freetype:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: freetype:x86-windows
  Vcpkg version: 0.0.110-2018-05-08-7e7958739ed7e87617465235f8f9306ae521e82e

Additionally, attach any relevant sections from the log files above.

**Comment by jasjuang** [comment]
The downloading link for freetype works for me. Do you want to try again?

**Comment by PhoebeHui** [comment]
It's a temporary issue, currently it download successfully, please open a new issue if it persists.
