### ISSUE TITLE
[zlib] Build error

### ISSUE THREAD

**Issue by T-Horikawa1992** [microsoft/vcpkg#34723]
Package: zlib:arm64-osx -> 1.3

**Host Environment**

- Host: arm64-osx
- Compiler: AppleClang 14.0.3.14030022
-    vcpkg-tool version: 2023-10-18-27de5b69dac4b6fe8259d283cd4011e6d20a84ce
    vcpkg-scripts version: 8eb57355a 2023-10-19 (5 days ago)

**To Reproduce**

`vcpkg install `
**Failure logs**

```
-- Using cached madler-zlib-v1.3.tar.gz.
-- Cleaning sources at /Users/takumihorikawa/Source/Inside/vera/bin/Debug/_deps/vcpkg-src/buildtrees/zlib/src/v1.3-8825ee792f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/takumihorikawa/Source/Inside/vera/bin/Debug/_deps/vcpkg-src/downloads/madler-zlib-v1.3.tar.gz
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch 0002-skip-building-examples.patch
-- Applying patch 0003-build-static-or-shared-not-both.patch
-- Applying patch 0004-android-and-mingw-fixes.patch
-- Using source at /Users/takumihorikawa/Source/Inside/vera/bin/Debug/_deps/vcpkg-src/buildtrees/zlib/src/v1.3-8825ee792f.clean
-- Found external ninja('1.10.2').
-- Configuring arm64-osx
-- Building arm64-osx-dbg
-- Building arm64-osx-rel
-- Installing: /Users/takumihorikawa/Source/Inside/vera/bin/Debug/_deps/vcpkg-src/packages/zlib_arm64-osx/share/zlib/vcpkg-cmake-wrapper.cmake
-- Fixing pkgconfig file: /Users/takumihorikawa/Source/Inside/vera/bin/Debug/_deps/vcpkg-src/packages/zlib_arm64-osx/lib/pkgconfig/zlib.pc
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:163 (message):
  Could not find pkg-config.  Please install it via your package manager:

      brew install pkg-config
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:203 (vcpkg_find_acquire_program)
  ports/zlib/portfile.cmake:43 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:168 (include)



```
**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg.schema.json",
  "dependencies": [
    "libzip"
  ]
}

```
</details>

I have installed pkg-config using brew, but I'm getting this error for some reason. Can anyone identify the cause?

**Comment by JonLiu1993** [comment]
````
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:163 (message):
  Could not find pkg-config.  Please install it via your package manager:

      brew install pkg-config
````

**Comment by T-Horikawa1992** [comment]
I've already executed that command, but I'm still encountering the error.

**Comment by JonLiu1993** [comment]
@T-Horikawa1992, you can try to clone a vcpkg again and run the command brew install pkg-config first and then try again.

**Comment by T-Horikawa1992** [comment]
@JonLiu1993 
Recloning didn't help. Is it an issue that pkg-config is installed in /opt/homebrew instead of /usr/local? The path to pkg-config is correctly set up.

**Comment by JonLiu1993** [comment]
My pkg-config is in the ./usr/local path after installation. You can install it to the ./usr/local path and try it.
````
./usr/local/bin/pkg-config
./usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config
./usr/local/var/homebrew/linked/pkg-config
./usr/local/opt/pkg-config
./usr/local/Cellar/pkg-config
./usr/local/Cellar/pkg-config/0.29.2_3/bin/pkg-config
./usr/local/Cellar/pkg-config/0.29.2_3/share/doc/pkg-config
./usr/local/share/doc/pkg-config
````

**Comment by dg0yt** [comment]
IIRC it is one location is used for x64, the other for arm64.

**Comment by T-Horikawa1992** [comment]
@JonLiu1993 @dg0yt 
The default installation location for Apple Silicon version of Homebrew is /opt/homebrew. Do you know how to change it to /usr/local? I've been researching it, but haven't succeeded yet. Also, is it possible that because pkg-config is installed in /opt/homebrew, vcpkg can't find it?

**Comment by dg0yt** [comment]
Don't move it!
The immediate workaround is to set environment variable `PKG_CONFIG`.

**Comment by dg0yt** [comment]
Can you please post the full path of the arm64 pkg-config?

**Comment by T-Horikawa1992** [comment]
@dg0yt 
oh,sry
I was able to install Homebrew in /usr/local by running Terminal in x86_64 mode.
After that, running brew install pkg-config resolved the vcpkg error.
It seems like it's working under the assumption that it should be in /usr/local.
Is there any potential issue with this solution?

**Comment by dg0yt** [comment]
Again, I want to verify the full path of `pkg-config` so that I can propose a permanent fix.

**Comment by T-Horikawa1992** [comment]
@dg0yt 
This is the full path.
`/opt/homebrew/bin/pkg-config`

**Comment by aabellagm** [comment]
I'm experiencing exactly the same problem the OP has, but, if possible, I would like to not use HomeBrew just only for a single package.

Is it possible to fix it with `vcpkg install pkgconf` in MacOS as suggested here https://github.com/microsoft/vcpkg/discussions/30365?
I've installed the `pkgconf` port and it continues failing, but it works if I use the tool installed by the `pkgconf` port like this:
```
PKG_CONFIG=$PWD/installed/arm64-osx/tools/pkgconf/pkgconf ./vcpkg install zlib
```
Shall the pkgconf tool be automatically detected?

**Comment by aabellagm** [comment]
Hi @dg0yt 
Do you know if what I wrote above about using pkgconf binary is expected to be working?
Thank you! :)

**Comment by dg0yt** [comment]
Using pkgconf from vcpkg via the PKG_CONFIG environment variable works for non-windows, and in some ways also for windows.

However, you need to trigger the build explicitly, before it is needed by a port. This may be okay for a single use, or in custom CI scripts, but it is clumsy as a general solution.  (And hopefully pkgconf 
 never gets a circular dependency on pkgconf.) You need brew as soon as you build the first port based on autotools.
