### ISSUE TITLE
[Freetype] LNK1107

### ISSUE THREAD

**Issue by skaarj1989** [microsoft/vcpkg#34725]
**Describe the bug**
A linker error **LNK1107**
Caused by: `target_link_libraries(Foo ${FREETYPE_LIBRARIES})`

**Environment**
- OS: Windows10
- Compiler: MSVC Version 17.8.0 Preview 5.0

**Expected behavior**
**${FREETYPE_LIBRARIES}** should point to **.lib** instead of **.dll**
https://cmake.org/cmake/help/latest/module/FindFreetype.html

**${FREETYPE_LIBRARIES}** on Linux:
`optimized;/vcpkg/installed/x64-linux/lib/libfreetype.a;debug;/vcpkg/installed/x64-linux/debug/lib/libfreetyped.a;optimized;/vcpkg/installed/x64-linux/lib/libz.a;debug;/vcpkg/installed/x64-linux/debug/lib/libz.a;optimized;/vcpkg/installed/x64-linux/lib/libbz2.a;debug;/vcpkg/installed/x64-linux/debug/lib/libbz2d.a;optimized;/vcpkg/installed/x64-linux/lib/libpng16.a;debug;/vcpkg/installed/x64-linux/debug/lib/libpng16d.a;optimized;/vcpkg/installed/x64-linux/lib/libz.a;debug;/vcpkg/installed/x64-linux/debug/lib/libz.a;m;optimized;/vcpkg/installed/x64-linux/lib/libbrotlidec.a;debug;/vcpkg/installed/x64-linux/debug/lib/libbrotlidec.a;optimized;/vcpkg/installed/x64-linux/lib/libbrotlicommon.a;debug;/vcpkg/installed/x64-linux/debug/lib/libbrotlicommon.a`

**Failure logs**
`E:\vcpkg\installed\x64-windows\debug\bin\freetyped.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x368`

**Comment by Adela0814** [comment]
@skaarj1989  I'm not able to repro this issue, could you please provide the repro steps?

**Comment by skaarj1989** [comment]
```cmake
project(issue34725)

find_package(Freetype REQUIRED)
message(STATUS "ft = ${FREETYPE_LIBRARIES}")

add_executable(issue34725 "main.cpp")
target_link_libraries(issue34725 PUBLIC
  ${FREETYPE_LIBRARIES} # LNK1107 
  # Freetype::Freetype  # This works
)
```

![image](https://github.com/microsoft/vcpkg/assets/34756939/74108bd9-2c94-42f1-8a9a-d9872e998455)

**Comment by faqeerhussain106** [comment]
***@***.***

**Comment by dg0yt** [comment]
Which version of CMake do you use? The 3.28 release candidates take properties from freetype config, and by looking up the `LOCATION` they will get the DLL instead of the import lib:
https://github.com/Kitware/CMake/blob/0715b17ddd64522d7973dd3b80d8c3f9000a02a7/Modules/FindFreetype.cmake#L113
You may run CMake with `--trace-expand` if you want to study what is going on.

**Comment by dg0yt** [comment]
Asking CMake: https://gitlab.kitware.com/cmake/cmake/-/merge_requests/8775#note_1437001

**Comment by skaarj1989** [comment]
Yeah, I recently upgraded to 3.28

**Comment by mathstuf** [comment]
What properties do you have with the `.lib`? Is it `IMPORTED_IMPLIB` or is it config-specific variants?

**Comment by mathstuf** [comment]
To clarify: I'm looking for the properties from `freetype-config.cmake` in freetype's prefix. Just posting the relevant file would be the most useful.

**Comment by dg0yt** [comment]
FTR, this is not freetype, but similar:
~~~
set_target_properties(pcre2::pcre2-posix-shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/libpcre2-posix.dll.a"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/libpcre2-posix.dll"
  )
~~~

**Comment by mathstuf** [comment]
I don't have a `vcpkg` setup handy to check it out myself.

**Comment by mathstuf** [comment]
Does this MR help? https://gitlab.kitware.com/cmake/cmake/-/merge_requests/8920

**Comment by dg0yt** [comment]
@skaarj1989 Can you test? Maybe download the full module from that MR and put it into CMAKE_MODULE_PATH.
I don't even have MSVC ;-)

**Comment by skaarj1989** [comment]
@mathstuf @dg0yt
It works. Thanks.

**${FREETYPE_LIBRARIES}** = `optimized;E:/vcpkg/installed/x64-windows/lib/freetype.lib;debug;E:/vcpkg/installed/x64-windows/debug/lib/freetyped.lib`
