### ISSUE TITLE
[vcpkg|python] python commands being broken by system installed python

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#34746]
Observed Error:; `pkgconf` fails to build or any python command fails. 

with something like:
```
G:\vcpkg_common\downloads\tools\python>G:\vcpkg_common\downloads\tools\python\python-3.11.5-x64\python.exe
Python 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
> import _ctypes
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: DLL load failed while importing _ctypes: Das angegebene Modul wurde nicht gefunden.
> >>>
```
(error only happens in CWD is different from where python lives)

Reason for failure is a globaly installed Python adding:
`HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\3.11\PythonPath`
modifying sys.path (dll lookup path) for the python used by vcpkg.

vcpkg probably should add `-I` (or at least `-E`) to all python calls to avoid modifications of any kind. (Unfortunatly this also deactivates using PYTHONPATH as an environment variable)

**Comment by Osyotr** [comment]
Normally, embeddable python package comes with `python3xy._pth` that makes it isolated from user environment. However, that file was removed in #7051.
