### ISSUE TITLE
[llvm] clang has wrong internal paths

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#34748]
`"-internal-isystem" "E:\\all\\vcpkg\\vcpkg_installed\\x64-windows-release\\tools\\llvm\\../tools/llvm/lib/clang/17\\include"`
`"-resource-dir" "E:\\all\\vcpkg\\vcpkg_installed\\x64-windows-release\\tools\\llvm\\../tools/llvm/lib/clang/17"`
cc @yurybura 

output generated with `clang -### dummy.c`

**Comment by Neumann-A** [comment]
I think the fix is simply changing `CLANG_RESOURCE_DIR` from `../tools/llvm/lib/clang/17` to `lib/clang/17` in the portfile

**Comment by yurybura** [comment]
> I think the fix is simply changing `CLANG_RESOURCE_DIR` from `../tools/llvm/lib/clang/17` to `lib/clang/17` in the portfile

Yeah, right. Should be fixed.
