### ISSUE TITLE
[vcpkg] String escaping issue in vcpkg_configure_cmake causes wrong compiler to be used

### ISSUE THREAD

**Issue by philjdf** [microsoft/vcpkg#3475]
I've been trying to create a port for Parquet-cpp. When I try to build my attempt with the x64-windows-static the triplet, CMAKE_CXX_COMPILER incorrectly points to the 32-bit compiler. I've created a simple package to investigate the problem.

Here's a CMakeLists.txt file:
```CMake
project(aaacompilertest)
message(STATUS "your compiler is ${CMAKE_CXX_COMPILER}")
```
which is zipped up and built (with x64-windows-static) with the following portfile:
```CMake
include(vcpkg_common_functions)

if(NOT VCPKG_TARGET_ARCHITECTURE STREQUAL "x64")
  message(FATAL_ERROR "Compiler test only supports x64")
endif()

vcpkg_extract_source_archive("${CMAKE_CURRENT_LIST_DIR}/code.zip")

vcpkg_configure_cmake(
    SOURCE_PATH ${CURRENT_BUILDTREES_DIR}/src/code
    PREFER_NINJA
)
```

It correctly identifies the compiler:
> -- your compiler is C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.13.26128/bin/Hostx64/x64/cl.exe

However, if I pass in an empty string to the vcpkg_configure_cmake command,
```CMake
vcpkg_configure_cmake(
    SOURCE_PATH ${CURRENT_BUILDTREES_DIR}/src/code
    PREFER_NINJA
    OPTIONS
    -DINNOCENT_LOOKING_STRING=""
)
```
everything goes south:
> -- your compiler is C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x86/cl.exe

Does anyone know what's going on please? Am I doing something wrong?

**Comment by Voskrese** [comment]
delete

> if(NOT VCPKG_TARGET_ARCHITECTURE STREQUAL "x64")
>   message(FATAL_ERROR "Compiler test only supports x64")
> endif()

**Comment by philjdf** [comment]
Done (and removed from post) but I still have the same problem. It chooses x64 if and only if I remove the definition for INNOCENT_LOOKING_STRING.

**Comment by Voskrese** [comment]
@philjdf 
I probably did not understand. but in the end what is needed? what hinders the x64 compiler
Hostx86/x64 ?

**Comment by philjdf** [comment]
So `vcpkg build aaacompilertest:x64-windows-static` works if the portfile contains
```
vcpkg_configure_cmake(
    SOURCE_PATH ${CURRENT_BUILDTREES_DIR}/src/code
    PREFER_NINJA
)
```
and doesn't work if we change that to
```
vcpkg_configure_cmake(
    SOURCE_PATH ${CURRENT_BUILDTREES_DIR}/src/code
    PREFER_NINJA
    OPTIONS
    -DINNOCENT_LOOKING_STRING=""
)
```
For some reason that results in `CMAKE_CXX_COMPILER` being set to x86. If I dig into the logs, Ninja gets called with
```
[1/2] cmd /c "cd ../../x64-windows-static-dbg && "C:/Program Files/CMake/bin/cmake.exe" "D:/Development/PhilipF/vcpkg/buildtrees/aaacompilertest/src/code" "-DINNOCENT_LOOKING_STRING=""" "-DCMAKE_MAKE_PROGRAM=D:/Development/PhilipF/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/Development/PhilipF/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows-static" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=D:/Development/PhilipF/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=static" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=D:/Development/PhilipF/vcpkg/packages/aaacompilertest_x64-windows-static/debug""
```
so my guess is `-DINNOCENT_LOOKING_STRING=""` is causing problems here with quote escapement.

So am I passing in args wrong? If so, the fact I don't get an error and get weird behaviour instead must mean in some cases this can be intended behaviour? Or is this a problem with Ninja or vcpkg or CMake escaping quotes?

**Comment by Voskrese** [comment]
`-DCMAKE_CL_64=1`
`-A x64 `
`-T v141,host=x64`

http://www.saoe.net/blog/778/
`(CMAKE_CL_64 OR ${PROJECTNAME_ARCHITECTURE} EQUAL "x64")`

**Comment by philjdf** [comment]
Shouldn't Vcpkg make sure CMake uses the right compiler based purely on the triple you call build/install with? Plus having different behaviour whether or not a dummy option is passed to vcpkg_configure_cmake doesn't seem right!

**Comment by philjdf** [comment]
Another different frustration is that in my CMAKE_BUILD_TYPE=DEBUG build of my port, `find_package` will find release binaries in `...\installed\x64-windows-static\lib` rather than the correct `...\installed\x64-windows-static\debug\lib` debug ones. For example `find_package(GTest REQUIRED)` will do this. Would greatly appreciate someone telling me what I'm doing wrong please!

**Comment by NancyLi1013** [comment]
Hi @philjdf, thanks for posting this issue.The port parquet has been added to vcpkg. I have tested and it can be installed successfully on my local.
```
Starting package 14/14: parquet:x64-windows-static
Building package parquet[core]:x64-windows-static...
-- Performing post-build validation
-- Performing post-build validation done
Building package parquet[core]:x64-windows-static... done
Installing package parquet[core]:x64-windows-static...
Installing package parquet[core]:x64-windows-static... done
Elapsed time for package parquet:x64-windows-static: 2.177 s
```
Please open a new issue if you have any problems when using this port.
