### ISSUE TITLE
[pthreads] Build error 

### ISSUE THREAD

**Issue by panyuQ** [microsoft/vcpkg#34766]
I found a problem: when installing other packages, `vspkg.exe` always gives a tar package, but this one gives a zip package, and there is no `CMakeLists.txt` file in it.
Is it not connected well?

Package: pthreads:x64-windows -> 3.0.0#14

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.37.32825.0
-    vcpkg-tool version: 2023-10-18-27de5b69dac4b6fe8259d283cd4011e6d20a84ce
    vcpkg-scripts version: unknown

**To Reproduce**

`vcpkg install pthreads:x64-windows`
**Failure logs**

```
-- Using cached pthreads4w-code-v3-49e541b6.0.0.zip.
-- Extracting source F:/tools/vcpkg/downloads/pthreads4w-code-v3-49e541b6.0.0.zip
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" -E tar xjf F:/tools/vcpkg/downloads/pthreads4w-code-v3-49e541b6.0.0.zip
    Working Directory: F:/tools/vcpkg/buildtrees/pthreads/src/49e541b66c-a9b0a36b2a.clean.tmp
    Error code: 1
    See logs for more information:
      F:\tools\vcpkg\buildtrees\pthreads\extract-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive.cmake:126 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:8 (vcpkg_extract_source_archive)
  scripts/cmake/vcpkg_from_sourceforge.cmake:97 (vcpkg_extract_source_archive_ex)
  ports/pthreads/portfile.cmake:20 (vcpkg_from_sourceforge)
  scripts/ports.cmake:168 (include)
  
```
<details><summary>F:\tools\vcpkg\buildtrees\pthreads\extract-err.log</summary>

```
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: F:/tools/vcpkg/downloads/pthreads4w-code-v3-49e541b6.0.0.zip
```
</details>

**Comment by MonicaLiu0311** [comment]
This should have been fixed by https://github.com/G-Research/ParquetSharp/issues/251#issuecomment-1481987296.

Same issue: https://github.com/microsoft/vcpkg/issues/19524.

Is your vcpkg up to date?
```
PS G:\vcpkg> ./vcpkg  version
vcpkg package management program version 2023-10-18-27de5b69dac4b6fe8259d283cd4011e6d20a84ce

See LICENSE.txt for license information.
```

**Comment by panyuQ** [comment]
> This should have been fixed by [G-Research/ParquetSharp#251 (comment)](https://github.com/G-Research/ParquetSharp/issues/251#issuecomment-1481987296).
> 
> Same issue: #19524.
> 
> Is your vcpkg up to date?
> 
> ```
> PS G:\vcpkg> ./vcpkg  version
> vcpkg package management program version 2023-10-18-27de5b69dac4b6fe8259d283cd4011e6d20a84ce
> 
> See LICENSE.txt for license information.
> ```

It is indeed the latest version, same as the one you have, and the vcpkg is on my sdcard, and the computer system is windows 1909 pro!

**Comment by PhoebeHui** [comment]
@panyuQ, can you please share the output for 'vcpkg install pthreads:x64-windows --debug' with us?

**Comment by panyuQ** [comment]
> @panyuQ，您能与我们分享“vcpkg install pthreads:x64-windows --debug”的输出吗？

My apologies, I solved the problem by upgrading my system to win11 and using the vcpkg that came with vs, so I no longer have the environment that was having the problem at the time.

**Comment by PhoebeHui** [comment]
Good to know it doesn't block you now!
