### ISSUE TITLE
[New Port Request] Emscripten

### ISSUE THREAD

**Issue by DougRogers** [microsoft/vcpkg#34774]
### Library name

Emscripten

### Library description

Emscripten is a complete Open Source compiler toolchain to WebAssembly. 

### Source repository URL

https://github.com/emscripten-core/emscripten

### Project homepage (if different from the source repository)

https://emscripten.org/docs/introducing_emscripten/index.html

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

Required for web assembly using Qt.

https://doc.qt.io/qt-6/wasm.html

_Building Qt applications for WebAssembly is similar to building Qt for other platforms. You need to install an SDK (Emscripten), install Qt (or build Qt from source), and finally, build the application._

**Comment by dg0yt** [comment]
Install the SDK, set environment variable `EMSCRIPTEN_ROOT`, and build for triplet `wasm32-emscripten`.
