### ISSUE TITLE
[qtmultimedia] build failure

### ISSUE THREAD

**Issue by bzisl** [microsoft/vcpkg#34780]
### Operating system

Windows 11

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
`vcpkg install  qt qtcharts qtserialport qttranslations qtbase[sql-mysql,concurrent,gui,widgets,network,thread,zstd,concurrent] qtsvg qtgrpc qtlocation quazip qtmultimedia[core,qml,widgets] --triplet x64-windows --recurse --x-buildtrees-root=c:\B
`
```

### Failure logs

qtbase:x64-windows is already installed
qtcharts:x64-windows is already installed
qtgrpc:x64-windows is already installed
Installing 1/30 qtmultimedia:x64-windows...
Building qtmultimedia[core,ffmpeg,gstreamer,qml,widgets]:x64-windows...
-- Using cached qtmultimedia-everywhere-src-6.6.0.tar.xz.
-- Cleaning sources at C:/B/qtmultimedia/src/here-src-6-2cf991993d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/git/vcpkg/downloads/qtmultimedia-everywhere-src-6.6.0.tar.xz
-- Applying patch remove_unistd.patch
-- Applying patch remove_export_macro.patch
-- Applying patch static_find_modules.patch
-- Applying patch fix_avfoundation_target.patch
-- Using source at C:/B/qtmultimedia/src/here-src-6-2cf991993d.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/git/vcpkg/downloads/tools/cmake-3.27.1-windows/cmake-3.27.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j17
    Working Directory: C:/B/qtmultimedia/x64-windows-dbg
    See logs for more information:
      C:\B\qtmultimedia\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  installed/x64-windows/share/qtbase/qt_install_submodule.cmake:348 (vcpkg_cmake_install)
  ports/qtmultimedia/portfile.cmake:77 (qt_install_submodule)
  scripts/ports.cmake:168 (include)

error: building qtmultimedia:x64-windows failed with: BUILD_FAILED
Elapsed time to handle qtmultimedia:x64-windows: 1.3 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qtmultimedia
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[qtmultimedia]+Build+error&body=Copy+issue+body+from+C%3A%2Fgit%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by autoantwort** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report an issue.

**Comment by FrankXie05** [comment]
Please provide the error log: `C:\B\qtmultimedia\install-x64-windows-dbg-out.log`.

**Comment by bzisl** [comment]
You can download the log from here:
https://drive.google.com/file/d/1ECgbDqaXu54PVgoUBdbNl-p7e2ENsd4u/view?usp=sharing

**Comment by FrankXie05** [comment]
```
C:\B\qtmultimedia\src\here-src-6-2cf991993d.clean\src\plugins\multimedia\ffmpeg\qffmpegwindowcapture_uwp.cpp(163): error C2065: 'IGraphicsCaptureSession3': undeclared identifier
C:\B\qtmultimedia\src\here-src-6-2cf991993d.clean\src\plugins\multimedia\ffmpeg\qffmpegwindowcapture_uwp.cpp(163): error C2672: 'winrt::Windows::Foundation::IUnknown::try_as': no matching overloaded function found
C:\B\qtmultimedia\src\here-src-6-2cf991993d.clean\src\plugins\multimedia\ffmpeg\qffmpegwindowcapture_uwp.cpp(163): error C2974: 'winrt::Windows::Foundation::IUnknown::try_as': invalid template argument for 'To', type expected
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt\winrt/base.h(2059): note: see declaration of 'winrt::Windows::Foundation::IUnknown::try_as'
C:\B\qtmultimedia\src\here-src-6-2cf991993d.clean\src\plugins\multimedia\ffmpeg\qffmpegwindowcapture_uwp.cpp(163): error C2737: 'session3': const object must be initialized
C:\B\qtmultimedia\src\here-src-6-2cf991993d.clean\src\plugins\multimedia\ffmpeg\qffmpegwindowcapture_uwp.cpp(163): error C3536: 'session3': cannot be used before it is initialized
```

**Comment by ASxa86** [comment]
I am experiencing this exact error as well. Just cloned and built from the latest commit `3135b990681223c46d2bce0793e04036d88f307c`. 

I'm using `Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.8.1` on Windows 11.

**Comment by FrankXie05** [comment]
@ASxa86 @bzisl 
>C:\B\qtmultimedia\src\here-src-6-2cf991993d.clean\src\plugins\multimedia\ffmpeg\qffmpegwindowcapture_uwp.cpp(163): error C2065: 'IGraphicsCaptureSession3': undeclared identifier

The definition of this function belongs to `Windows SDK`, please install the latest `Windows SDK`. If possible, install uwp components on `VS`.

**Comment by FrankXie05** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can ping me with more info and I will reopen.
