### ISSUE TITLE
[New Port Request] AMD HIP SDK

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#34785]
### Library name

AMD HIP SDK / ROCm

### Library description

The AMD HIP SDK is a software development kit (SDK) that allows developers that brings a subset of ROCm to Windows. It provides an API and tooling that allows users to enable computation on GPUs using HIP.

### Source repository URL

https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

a) Either provide a port like mkl where the SDK gets extracted into the installed tree (don't know if the license permits that)
or
b) provide a system test ports with additional env passthroughs like CUDA has.

**Comment by Neumann-A** [comment]
Not stale

**Comment by The-Lord-of-Owls** [comment]
Not stale
