### ISSUE TITLE
Request: write WaitingToTakeFilesystemLock output for vcpkg-tool to stderr not stdout

### ISSUE THREAD

**Issue by russelltg** [microsoft/vcpkg#34805]
I have a CI pipeline that has to run `vcpkg list --x-json` to get version numbers of packages. However, we were getting random CI failures because it would randomly fail to acquire the lock, so I added `--x-wait-for-lock` to our commandline. But now, the stdout that is supposed to be json is now tainted with `waiting to take filesystem lock on /workspaces/ars/ext/vcpkg/.vcpkg-root...`

I'm happy to open a PR if this is interesting

**Environment**
- OS: Linux

**To Reproduce**
1. `./vcpkg list --x-json --x-wait-for-lock` many times fast
2. See bad output!

**Expected behavior**
Messages like that go to stderr

**Comment by autoantwort** [comment]
There is https://github.com/microsoft/vcpkg-tool/pull/1175 to fix that :)

**Comment by FrankXie05** [comment]
This issue has been fixed by PR https://github.com/microsoft/vcpkg-tool/pull/1175
