### ISSUE TITLE
[libsimdjson] update to 14 (with support for .a/.lib in debug and release)

### ISSUE THREAD

**Issue by gf-eaton** [microsoft/vcpkg#34823]
### Library name

libsimdjson

### New version number

14

### Other information that may be useful (release notes, etc...)

Hello,

The library should now offer static capable linkage files `.a` / `.lib` --- it already support .dll or .so files

`arm64` and `x86_64` should also be supported.

Thanks

**Comment by JonLiu1993** [comment]
@gf-eaton, vcpkg don't have libsimdjson port, do you means port `simdjson`?

**Comment by gf-eaton** [comment]
Hello,

@JonLiu1993 simdjson yes indeed..
