### ISSUE TITLE
[expat] Build error

### ISSUE THREAD

**Issue by nagapraneethk** [microsoft/vcpkg#34827]
Copy issue body from /Users/nagapraneeth/vcpkg/installed/vcpkg/issue_body.md

**Comment by nagapraneethk** [comment]
[issue_body.md](https://github.com/microsoft/vcpkg/files/13220244/issue_body.md)

**Comment by autoantwort** [comment]
>   Could not find pkg-config.  Please install it via your package manager:

      brew install pkg-config
