### ISSUE TITLE
[gdal] Build error

### ISSUE THREAD

**Issue by KaiTang2** [microsoft/vcpkg#34836]
Copy issue body from E:/GitHub/vcpkg/installed/vcpkg/issue_body.md
[issue_body.md](https://github.com/microsoft/vcpkg/files/13222654/issue_body.md)

**Comment by jimwang118** [comment]
I tested it locally but didn't reproduce the problem. The vcpkg version I am using is 2023-10-18-27de5b69dac4b6fe8259d283cd4011e6d20a84ce.
![image](https://github.com/microsoft/vcpkg/assets/122244446/7f8090f6-1672-4747-8919-b4b108806664)

**Comment by KaiTang2** [comment]
OSGGeo 你那用的哪个版本？

**Comment by KaiTang2** [comment]
Which version of OSGGeo are you using?

**Comment by dg0yt** [comment]
This is vcpkg. No osgeo used at all.

**Comment by dg0yt** [comment]
~~~
-- Looking for sqlite3ext.h - found
CMake Error at cmake/helpers/CheckDependentLibraries.cmake:556 (message):
  E:/GitHub/vcpkg/installed/x64-windows/debug/lib/sqlite3.lib lacks the RTree
  extension! Spatialite will not behave properly.  Define the
  ACCEPT_MISSING_SQLITE3_RTREE:BOOL=ON CMake variable if you want to build
  despite this limitation.
Call Stack (most recent call first):
  ogr/ogrsf_frmts/sqlite/CMakeLists.txt:67 (check_sqlite3_rtree)
~~~
Unexoected. `gdal[sqlite3]` dendends on `sqlite3[rtree]`, and you have the current version of sqlite3.

**Comment by jimwang118** [comment]
The error prompts that `sqlite3` needs to install `rtree` feature, but `rtree `is not the default feature and needs to be actively installed. You install `sqlite3[rtree]` first, and then install `gdal`. The installation result is correct.

**Comment by dg0yt** [comment]
> The error prompts that `sqlite3` needs to install `rtree` feature, but `rtree `is not the default feature and needs to be actively installed. You install `sqlite3[rtree]` first, and then install `gdal`. The installation result is correct.

No. The dependencies already ensure that `sqlite3[rtree]` is installed before gdal. I made this clear in my previous comment,

But maybe the test picks an external sqlite install at some point.

**Comment by jimwang118** [comment]
> > The error prompts that `sqlite3` needs to install `rtree` feature, but `rtree `is not the default feature and needs to be actively installed. You install `sqlite3[rtree]` first, and then install `gdal`. The installation result is correct.
> 
> No. The dependencies already ensure that `sqlite3[rtree]` is installed before gdal. I made this clear in my previous comment,
> 
> But maybe the test picks an external sqlite install at some point.

OK, I understand.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
