### ISSUE TITLE
[angle] Class WebSwapCGLLayer is implemented in both WebKit.framework and angle on macOS

### ISSUE THREAD

**Issue by xiaozhuai** [microsoft/vcpkg#34843]
**Describe the bug**
When I use angle on macOS, it prints
```
objc[70246]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb469e5ec8) and /Users/xiaozhuai/work/glpp/cmake-build-x64-debug/tests/01_hello_triangle (0x104901dc8). One of the two will be used. Which one is undefined.
```

**Environment**
- OS: macOS
- Compiler: clang-1400.0.29.202

**To Reproduce**
```
vcpkg install angle:x64-osx
```
And then build and run this project
https://github.com/xiaozhuai/vcpkg_demo/tree/master/src/opengles_angle

**Expected behavior**
It should print nothing

**Comment by dpogue** [comment]
In up-to-date versions of ANGLE, there's a `ANGLE_OUTSIDE_WEBKIT` define that changes the class name at compile time: https://github.com/google/angle/blob/eaae3b4b01d9a04d7c8013c6e9da805e2a08ec2f/src/libANGLE/renderer/gl/cgl/WindowSurfaceCGL.mm#L23C8-L27

That change happened here, in case that's easier to pull as a patch: https://github.com/google/angle/commit/8875ba4e4cd28a8a08d51f60ea8bc967cb26659d

**Comment by xiaozhuai** [comment]
Just let it stay broken.
