### ISSUE TITLE
opencv dnn install failure

### ISSUE THREAD

**Issue by marekjaszuk** [Microsoft/vcpkg#3485]
The opencv install runs succesfully, but it does not install the dnn module by default. Thus I run the following command to install the dnn:
vcpkg install opencv[dnn] --recurse
Unfortunately it ends with failure. I get the following messages:

CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:170 (message):
    Command failed: D:/vcpkg/downloads/tools/cmake-3.10.2-windows/cmake-3.10.2-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: D:/vcpkg/buildtrees/opencv/x86-windows-dbg
    See logs for more information:
      D:\vcpkg\buildtrees\opencv\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/opencv/portfile.cmake:316 (vcpkg_install_cmake)
  scripts/ports.cmake:72 (include)

Error: Building package opencv:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv:x86-windows
  Vcpkg version: 0.0.111-2018-05-11-29d04b8b4005f5e2bfe61ccdc7a93d5c6c8a13d9

**Comment by lazylazypig** [comment]
@marekjaszuk 
hi, I met the same problem as I build dnn on x64-windows. have you solve this problem?  regards:)

**Comment by marekjaszuk** [comment]
Unfortunately I got no progress. Still the same error.

**Comment by emptyVoid** [comment]
Will this ever be fixed?

**Comment by NancyLi1013** [comment]
Hi @marekjaszuk, @lazylazypig, @emptyVoid , thanks for posting this issue. The package has been updated. I can install it successfully on my machine with the latest vcpkg. So it should be fixed now. Please try it again. If this is still a problem for you, please reopen it or open a new issue.
