### ISSUE TITLE
there are no gcc-8 or clang++-6 options on osx

### ISSUE THREAD

**Issue by aguai** [Microsoft/vcpkg#3486]
if [ "x$CXX" = "x" ]; then
        CXX=g++
        if which g++-8 >/dev/null 2>&1; then
            CXX=g++-8
        elif which g++-6 >/dev/null 2>&1; then
            CXX=g++-6
        fi
    fi

**Comment by ras0219-msft** [comment]
Thanks for this issue! It should be fixed on master.
