### ISSUE TITLE
[vcpkg] build failure

### ISSUE THREAD

**Issue by VladDREEMURR** [microsoft/vcpkg#34875]
### Operating system

Windows

### Compiler

Windows PowerShell

### Steps to reproduce the behavior

```Shell
.\vcpkg.exe install boost:x64-windows boost:x86-windows
```

### Failure logs

-- Downloading https://github.com/boostorg/config/archive/boost-1.83.0.tar.gz -> boostorg-config-boost-1.83.0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from C:\Users\HP\Documents\Git Files\vc\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: C:\Users\HP\Documents\Git Files\vc\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://github.com/boostorg/config/archive/boost-1.83.0.tar.gz
warning: Download failed -- retrying after 1000ms
warning: Download failed -- retrying after 2000ms
warning: Download failed -- retrying after 4000ms
error: Failed to download from mirror set
error: https://github.com/boostorg/config/archive/boost-1.83.0.tar.gz: WinHttpReceiveResponse failed with exit code 12175
error: https://github.com/boostorg/config/archive/boost-1.83.0.tar.gz: WinHttpReceiveResponse failed with exit code 12175
error: https://github.com/boostorg/config/archive/boost-1.83.0.tar.gz: WinHttpReceiveResponse failed with exit code 12175
error: https://github.com/boostorg/config/archive/boost-1.83.0.tar.gz: WinHttpReceiveResponse failed with exit code 12175
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1051):
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 3us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 2931us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 8.1 s (8100679us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/boost-config/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:168 (include)

error: building boost-config:x64-windows failed with: BUILD_FAILED
Elapsed time to handle boost-config:x64-windows: 8.2 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-config
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[boost-config]+Build+error&body=Copy+issue+body+from+C%3A%2FUsers%2FHP%2FDocuments%2FGit%20Files%2Fvc%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by Adela0814** [comment]
@VladDREEMURR Please pull the latest `vcpkg` and try again.

**Comment by VladDREEMURR** [comment]
@Adela0814 aaand... here it is again
Maybe I should send whole process after pull?
As far as I can see, the error hasn't changed

`PS C:\Users\HP\Documents\Git Files\vc\vcpkg> .\bootstrap-vcpkg.bat
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2023-10-18/vcpkg.exe -> C:\Users\HP\Documents\Git Files\vc\vcpkg\vcpkg.exe... done.
Validating signature... done.

vcpkg package management program version 2023-10-18-27de5b69dac4b6fe8259d283cd4011e6d20a84ce

See LICENSE.txt for license information.
Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
PS C:\Users\HP\Documents\Git Files\vc\vcpkg> .\vcpkg.exe install boost:x64-windows boost:x86-windows
Computing installation plan...
The following packages will be built and installed:
    boost:x64-windows -> 1.83.0#1
    boost:x86-windows -> 1.83.0#1
  * boost-accumulators:x64-windows -> 1.83.0
  * boost-accumulators:x86-windows -> 1.83.0
  * boost-algorithm:x86-windows -> 1.83.0
  * boost-algorithm:x64-windows -> 1.83.0
  * boost-align:x86-windows -> 1.83.0
  * boost-align:x64-windows -> 1.83.0
  * boost-any:x64-windows -> 1.83.0
  * boost-any:x86-windows -> 1.83.0
  * boost-array:x64-windows -> 1.83.0
  * boost-array:x86-windows -> 1.83.0
  * boost-asio:x86-windows -> 1.83.0
  * boost-asio:x64-windows -> 1.83.0
  * boost-assert:x64-windows -> 1.83.0
  * boost-assert:x86-windows -> 1.83.0
  * boost-assign:x86-windows -> 1.83.0
  * boost-assign:x64-windows -> 1.83.0
  * boost-atomic:x64-windows -> 1.83.0
  * boost-atomic:x86-windows -> 1.83.0
  * boost-beast:x64-windows -> 1.83.0
  * boost-beast:x86-windows -> 1.83.0
  * boost-bimap:x86-windows -> 1.83.0
  * boost-bimap:x64-windows -> 1.83.0
  * boost-bind:x64-windows -> 1.83.0
  * boost-bind:x86-windows -> 1.83.0
  * boost-build:x64-windows -> 1.83.0
  * boost-callable-traits:x64-windows -> 1.83.0
  * boost-callable-traits:x86-windows -> 1.83.0
  * boost-chrono:x86-windows -> 1.83.0
  * boost-chrono:x64-windows -> 1.83.0
  * boost-circular-buffer:x64-windows -> 1.83.0
  * boost-circular-buffer:x86-windows -> 1.83.0
  * boost-compat:x86-windows -> 1.83.0
  * boost-compat:x64-windows -> 1.83.0
  * boost-compatibility:x86-windows -> 1.83.0
  * boost-compatibility:x64-windows -> 1.83.0
  * boost-compute:x86-windows -> 1.83.0
  * boost-compute:x64-windows -> 1.83.0
  * boost-concept-check:x64-windows -> 1.83.0
  * boost-concept-check:x86-windows -> 1.83.0
  * boost-config:x86-windows -> 1.83.0
  * boost-config:x64-windows -> 1.83.0
  * boost-container:x64-windows -> 1.83.0
  * boost-container:x86-windows -> 1.83.0
  * boost-container-hash:x64-windows -> 1.83.0
  * boost-container-hash:x86-windows -> 1.83.0
  * boost-context:x86-windows -> 1.83.0
  * boost-context:x64-windows -> 1.83.0
  * boost-contract:x86-windows -> 1.83.0
  * boost-contract:x64-windows -> 1.83.0
  * boost-conversion:x86-windows -> 1.83.0
  * boost-conversion:x64-windows -> 1.83.0
  * boost-convert:x64-windows -> 1.83.0
  * boost-convert:x86-windows -> 1.83.0
  * boost-core:x64-windows -> 1.83.0
  * boost-core:x86-windows -> 1.83.0
  * boost-coroutine:x86-windows -> 1.83.0
  * boost-coroutine:x64-windows -> 1.83.0
  * boost-coroutine2:x64-windows -> 1.83.0
  * boost-coroutine2:x86-windows -> 1.83.0
  * boost-crc:x86-windows -> 1.83.0
  * boost-crc:x64-windows -> 1.83.0
  * boost-date-time:x86-windows -> 1.83.0
  * boost-date-time:x64-windows -> 1.83.0
  * boost-describe:x64-windows -> 1.83.0
  * boost-describe:x86-windows -> 1.83.0
  * boost-detail:x86-windows -> 1.83.0
  * boost-detail:x64-windows -> 1.83.0
  * boost-dll:x86-windows -> 1.83.0
  * boost-dll:x64-windows -> 1.83.0
  * boost-dynamic-bitset:x64-windows -> 1.83.0
  * boost-dynamic-bitset:x86-windows -> 1.83.0
  * boost-endian:x86-windows -> 1.83.0
  * boost-endian:x64-windows -> 1.83.0
  * boost-exception:x64-windows -> 1.83.0
  * boost-exception:x86-windows -> 1.83.0
  * boost-fiber:x86-windows -> 1.83.0#1
  * boost-fiber:x64-windows -> 1.83.0#1
  * boost-filesystem:x86-windows -> 1.83.0
  * boost-filesystem:x64-windows -> 1.83.0
  * boost-flyweight:x86-windows -> 1.83.0
  * boost-flyweight:x64-windows -> 1.83.0
  * boost-foreach:x64-windows -> 1.83.0
  * boost-foreach:x86-windows -> 1.83.0
  * boost-format:x86-windows -> 1.83.0
  * boost-format:x64-windows -> 1.83.0
  * boost-function:x86-windows -> 1.83.0
  * boost-function:x64-windows -> 1.83.0
  * boost-function-types:x64-windows -> 1.83.0
  * boost-function-types:x86-windows -> 1.83.0
  * boost-functional:x86-windows -> 1.83.0
  * boost-functional:x64-windows -> 1.83.0
  * boost-fusion:x86-windows -> 1.83.0
  * boost-fusion:x64-windows -> 1.83.0
  * boost-geometry:x86-windows -> 1.83.0
  * boost-geometry:x64-windows -> 1.83.0
  * boost-gil:x64-windows -> 1.83.0
  * boost-gil:x86-windows -> 1.83.0
  * boost-graph:x64-windows -> 1.83.0
  * boost-graph:x86-windows -> 1.83.0
  * boost-hana:x64-windows -> 1.83.0
  * boost-hana:x86-windows -> 1.83.0
  * boost-heap:x64-windows -> 1.83.0
  * boost-heap:x86-windows -> 1.83.0
  * boost-histogram:x64-windows -> 1.83.0
  * boost-histogram:x86-windows -> 1.83.0
  * boost-hof:x64-windows -> 1.83.0
  * boost-hof:x86-windows -> 1.83.0
  * boost-icl:x64-windows -> 1.83.0
  * boost-icl:x86-windows -> 1.83.0
  * boost-integer:x64-windows -> 1.83.0
  * boost-integer:x86-windows -> 1.83.0
  * boost-interprocess:x86-windows -> 1.83.0
  * boost-interprocess:x64-windows -> 1.83.0
  * boost-interval:x86-windows -> 1.83.0
  * boost-interval:x64-windows -> 1.83.0
  * boost-intrusive:x64-windows -> 1.83.0
  * boost-intrusive:x86-windows -> 1.83.0
  * boost-io:x64-windows -> 1.83.0
  * boost-io:x86-windows -> 1.83.0
  * boost-iostreams[bzip2,core,lzma,zlib,zstd]:x86-windows -> 1.83.0#1
  * boost-iostreams[bzip2,core,lzma,zlib,zstd]:x64-windows -> 1.83.0#1
  * boost-iterator:x64-windows -> 1.83.0
  * boost-iterator:x86-windows -> 1.83.0
  * boost-json:x64-windows -> 1.83.0
  * boost-json:x86-windows -> 1.83.0
  * boost-lambda:x64-windows -> 1.83.0
  * boost-lambda:x86-windows -> 1.83.0
  * boost-lambda2:x64-windows -> 1.83.0
  * boost-lambda2:x86-windows -> 1.83.0
  * boost-leaf:x64-windows -> 1.83.0
  * boost-leaf:x86-windows -> 1.83.0
  * boost-lexical-cast:x86-windows -> 1.83.0
  * boost-lexical-cast:x64-windows -> 1.83.0
  * boost-local-function:x64-windows -> 1.83.0
  * boost-local-function:x86-windows -> 1.83.0
  * boost-locale:x64-windows -> 1.83.0
  * boost-locale:x86-windows -> 1.83.0
  * boost-lockfree:x64-windows -> 1.83.0
  * boost-lockfree:x86-windows -> 1.83.0
  * boost-log:x64-windows -> 1.83.0
  * boost-log:x86-windows -> 1.83.0
  * boost-logic:x64-windows -> 1.83.0
  * boost-logic:x86-windows -> 1.83.0
  * boost-math:x86-windows -> 1.83.0
  * boost-math:x64-windows -> 1.83.0
  * boost-metaparse:x64-windows -> 1.83.0
  * boost-metaparse:x86-windows -> 1.83.0
  * boost-modular-build-helper:x64-windows -> 1.83.0#1
  * boost-move:x86-windows -> 1.83.0
  * boost-move:x64-windows -> 1.83.0
  * boost-mp11:x64-windows -> 1.83.0
  * boost-mp11:x86-windows -> 1.83.0
  * boost-mpl:x86-windows -> 1.83.0
  * boost-mpl:x64-windows -> 1.83.0
  * boost-msm:x86-windows -> 1.83.0
  * boost-msm:x64-windows -> 1.83.0
  * boost-multi-array:x86-windows -> 1.83.0
  * boost-multi-array:x64-windows -> 1.83.0
  * boost-multi-index:x64-windows -> 1.83.0
  * boost-multi-index:x86-windows -> 1.83.0
  * boost-multiprecision:x64-windows -> 1.83.0
  * boost-multiprecision:x86-windows -> 1.83.0
  * boost-mysql:x86-windows -> 1.83.0
  * boost-mysql:x64-windows -> 1.83.0
  * boost-nowide:x86-windows -> 1.83.0
  * boost-nowide:x64-windows -> 1.83.0
  * boost-numeric-conversion:x86-windows -> 1.83.0
  * boost-numeric-conversion:x64-windows -> 1.83.0
  * boost-odeint:x86-windows -> 1.83.0
  * boost-odeint:x64-windows -> 1.83.0
  * boost-optional:x64-windows -> 1.83.0
  * boost-optional:x86-windows -> 1.83.0
  * boost-outcome:x86-windows -> 1.83.0
  * boost-outcome:x64-windows -> 1.83.0
  * boost-parameter:x86-windows -> 1.83.0
  * boost-parameter:x64-windows -> 1.83.0
  * boost-parameter-python:x64-windows -> 1.83.0
  * boost-parameter-python:x86-windows -> 1.83.0
  * boost-pfr:x64-windows -> 1.83.0
  * boost-pfr:x86-windows -> 1.83.0
  * boost-phoenix:x64-windows -> 1.83.0
  * boost-phoenix:x86-windows -> 1.83.0
  * boost-poly-collection:x64-windows -> 1.83.0
  * boost-poly-collection:x86-windows -> 1.83.0
  * boost-polygon:x64-windows -> 1.83.0
  * boost-polygon:x86-windows -> 1.83.0
  * boost-pool:x86-windows -> 1.83.0
  * boost-pool:x64-windows -> 1.83.0
  * boost-predef:x86-windows -> 1.83.0
  * boost-predef:x64-windows -> 1.83.0
  * boost-preprocessor:x64-windows -> 1.83.0
  * boost-preprocessor:x86-windows -> 1.83.0
  * boost-process:x64-windows -> 1.83.0
  * boost-process:x86-windows -> 1.83.0
  * boost-program-options:x86-windows -> 1.83.0
  * boost-program-options:x64-windows -> 1.83.0
  * boost-property-map:x86-windows -> 1.83.0
  * boost-property-map:x64-windows -> 1.83.0
  * boost-property-tree:x64-windows -> 1.83.0
  * boost-property-tree:x86-windows -> 1.83.0
  * boost-proto:x64-windows -> 1.83.0
  * boost-proto:x86-windows -> 1.83.0
  * boost-ptr-container:x86-windows -> 1.83.0
  * boost-ptr-container:x64-windows -> 1.83.0
  * boost-python[core,python3]:x86-windows -> 1.83.0
  * boost-python[core,python3]:x64-windows -> 1.83.0
  * boost-qvm:x86-windows -> 1.83.0
  * boost-qvm:x64-windows -> 1.83.0
  * boost-random:x64-windows -> 1.83.0
  * boost-random:x86-windows -> 1.83.0
  * boost-range:x64-windows -> 1.83.0
  * boost-range:x86-windows -> 1.83.0
  * boost-ratio:x64-windows -> 1.83.0
  * boost-ratio:x86-windows -> 1.83.0
  * boost-rational:x86-windows -> 1.83.0
  * boost-rational:x64-windows -> 1.83.0
  * boost-regex:x64-windows -> 1.83.0
  * boost-regex:x86-windows -> 1.83.0
  * boost-safe-numerics:x64-windows -> 1.83.0
  * boost-safe-numerics:x86-windows -> 1.83.0
  * boost-scope-exit:x64-windows -> 1.83.0
  * boost-scope-exit:x86-windows -> 1.83.0
  * boost-serialization:x64-windows -> 1.83.0
  * boost-serialization:x86-windows -> 1.83.0
  * boost-signals2:x64-windows -> 1.83.0
  * boost-signals2:x86-windows -> 1.83.0
  * boost-smart-ptr:x64-windows -> 1.83.0
  * boost-smart-ptr:x86-windows -> 1.83.0
  * boost-sort:x64-windows -> 1.83.0
  * boost-sort:x86-windows -> 1.83.0
  * boost-spirit:x86-windows -> 1.83.0
  * boost-spirit:x64-windows -> 1.83.0
  * boost-stacktrace:x64-windows -> 1.83.0
  * boost-stacktrace:x86-windows -> 1.83.0
  * boost-statechart:x64-windows -> 1.83.0
  * boost-statechart:x86-windows -> 1.83.0
  * boost-static-assert:x64-windows -> 1.83.0
  * boost-static-assert:x86-windows -> 1.83.0
  * boost-static-string:x64-windows -> 1.83.0
  * boost-static-string:x86-windows -> 1.83.0
  * boost-stl-interfaces:x64-windows -> 1.83.0
  * boost-stl-interfaces:x86-windows -> 1.83.0
  * boost-system:x64-windows -> 1.83.0
  * boost-system:x86-windows -> 1.83.0
  * boost-test:x64-windows -> 1.83.0
  * boost-test:x86-windows -> 1.83.0
  * boost-thread:x86-windows -> 1.83.0
  * boost-thread:x64-windows -> 1.83.0
  * boost-throw-exception:x86-windows -> 1.83.0
  * boost-throw-exception:x64-windows -> 1.83.0
  * boost-timer:x64-windows -> 1.83.0
  * boost-timer:x86-windows -> 1.83.0
  * boost-tokenizer:x86-windows -> 1.83.0
  * boost-tokenizer:x64-windows -> 1.83.0
  * boost-tti:x64-windows -> 1.83.0
  * boost-tti:x86-windows -> 1.83.0
  * boost-tuple:x64-windows -> 1.83.0
  * boost-tuple:x86-windows -> 1.83.0
  * boost-type-erasure:x64-windows -> 1.83.0
  * boost-type-erasure:x86-windows -> 1.83.0
  * boost-type-index:x64-windows -> 1.83.0
  * boost-type-index:x86-windows -> 1.83.0
  * boost-type-traits:x86-windows -> 1.83.0
  * boost-type-traits:x64-windows -> 1.83.0
  * boost-typeof:x64-windows -> 1.83.0
  * boost-typeof:x86-windows -> 1.83.0
  * boost-ublas:x86-windows -> 1.83.0
  * boost-ublas:x64-windows -> 1.83.0
  * boost-uninstall:x86-windows -> 1.83.0
  * boost-units:x64-windows -> 1.83.0
  * boost-units:x86-windows -> 1.83.0
  * boost-unordered:x86-windows -> 1.83.0
  * boost-unordered:x64-windows -> 1.83.0
  * boost-url:x64-windows -> 1.83.0
  * boost-url:x86-windows -> 1.83.0
  * boost-utility:x86-windows -> 1.83.0
  * boost-utility:x64-windows -> 1.83.0
  * boost-uuid:x64-windows -> 1.83.0
  * boost-uuid:x86-windows -> 1.83.0
  * boost-variant:x86-windows -> 1.83.0
  * boost-variant:x64-windows -> 1.83.0
  * boost-variant2:x64-windows -> 1.83.0
  * boost-variant2:x86-windows -> 1.83.0
  * boost-vcpkg-helpers:x86-windows -> 1.83.0
  * boost-vmd:x86-windows -> 1.83.0
  * boost-vmd:x64-windows -> 1.83.0
  * boost-wave:x64-windows -> 1.83.0
  * boost-wave:x86-windows -> 1.83.0
  * boost-winapi:x64-windows -> 1.83.0
  * boost-winapi:x86-windows -> 1.83.0
  * boost-xpressive:x64-windows -> 1.83.0
  * boost-xpressive:x86-windows -> 1.83.0
  * boost-yap:x64-windows -> 1.83.0
  * boost-yap:x86-windows -> 1.83.0
  * bzip2[core,tool]:x64-windows -> 1.0.8#5
  * bzip2[core,tool]:x86-windows -> 1.0.8#5
  * expat:x64-windows -> 2.5.0#3
  * expat:x86-windows -> 2.5.0#3
  * libffi:x64-windows -> 3.4.4#6
  * libffi:x86-windows -> 3.4.4#6
  * liblzma:x86-windows -> 5.4.4
  * liblzma:x64-windows -> 5.4.4
  * openssl:x64-windows -> 3.1.4
  * openssl:x86-windows -> 3.1.4
  * pkgconf:x64-windows -> 1.8.0#5
  * python3:x86-windows -> 3.11.5
  * python3:x64-windows -> 3.11.5
  * sqlite3[core,json1]:x86-windows -> 3.43.1
  * sqlite3[core,json1]:x64-windows -> 3.43.1
  * vcpkg-cmake:x64-windows -> 2023-05-04
  * vcpkg-cmake-config:x64-windows -> 2022-02-06#1
  * vcpkg-cmake-get-vars:x64-windows -> 2023-03-02
  * vcpkg-msbuild:x64-windows -> 2023-08-08
  * vcpkg-pkgconfig-get-modules:x64-windows -> 2023-09-06
  * vcpkg-tool-meson:x64-windows -> 0.63
  * zlib:x86-windows -> 1.3
  * zlib:x64-windows -> 1.3
  * zstd:x64-windows -> 1.5.5#2
  * zstd:x86-windows -> 1.5.5#2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
Restored 0 package(s) from C:\Users\HP\AppData\Local\vcpkg\archives in 11.8 ms. Use --debug to see more details.
Installing 1/321 boost-config:x64-windows...
Building boost-config:x64-windows...
-- Downloading https://github.com/boostorg/config/archive/boost-1.83.0.tar.gz -> boostorg-config-boost-1.83.0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from C:\Users\HP\Documents\Git Files\vc\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: C:\Users\HP\Documents\Git Files\vc\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://github.com/boostorg/config/archive/boost-1.83.0.tar.gz
warning: Download failed -- retrying after 1000ms
warning: Download failed -- retrying after 2000ms
warning: Download failed -- retrying after 4000ms
error: Failed to download from mirror set
error: https://github.com/boostorg/config/archive/boost-1.83.0.tar.gz: WinHttpReceiveResponse failed with exit code 12175
error: https://github.com/boostorg/config/archive/boost-1.83.0.tar.gz: WinHttpReceiveResponse failed with exit code 12175
error: https://github.com/boostorg/config/archive/boost-1.83.0.tar.gz: WinHttpReceiveResponse failed with exit code 12175
error: https://github.com/boostorg/config/archive/boost-1.83.0.tar.gz: WinHttpReceiveResponse failed with exit code 12175
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1051):
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 3us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 8678us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 8.5 s (8523494us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.


Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/boost-config/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:168 (include)


error: building boost-config:x64-windows failed with: BUILD_FAILED
Elapsed time to handle boost-config:x64-windows: 8.6 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-config
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[boost-config]+Build+error&body=Copy+issue+body+from+C%3A%2FUsers%2FHP%2FDocuments%2FGit%20Files%2Fvc%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md`

**Comment by VladDREEMURR** [comment]
So it is the same error

**Comment by Adela0814** [comment]
Please try this link https://github.com/boostorg/config/archive/boost-1.83.0.tar.gz. Maybe there's a problem with your network.

**Comment by VladDREEMURR** [comment]
I can't try this link because of problems with confidentiality. It is on all browsers

**Comment by Adela0814** [comment]
Unfortunately, it seems that your network cannot access this resource, vcpkg cannot do more.
