### ISSUE TITLE
Package: vtk:x64-windows   Vcpkg version: 0.0.110-2018-05-10-9a19dae13a0fa594245db2df45ec54a504bc82f3

### ISSUE THREAD

**Issue by linapiao** [Microsoft/vcpkg#3487]
$ ./vcpkg.exe install vtk:x64-windows
The following packages will be built and installed:
    vtk[core]:x64-windows
Starting package 1/1: vtk:x64-windows
Building package vtk[core]:x64-windows...
-- CURRENT_INSTALLED_DIR=F:/git/vcpkg/installed/x64-windows
-- DOWNLOADS=F:/git/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=F:/git/vcpkg/packages/vtk_x64-windows
-- CURRENT_BUILDTREES_DIR=F:/git/vcpkg/buildtrees/vtk
-- CURRENT_PORT_DIR=F:/git/vcpkg/ports/vtk
-- Using cached F:/git/vcpkg/downloads/Kitware-VTK-v8.1.0.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Applying patch F:/git/vcpkg/ports/vtk/dont-define-ssize_t.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch F:/git/vcpkg/ports/vtk/dont-define-ssize_t.patch done
-- Applying patch F:/git/vcpkg/ports/vtk/use-fixed-find-hdf5.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch F:/git/vcpkg/ports/vtk/use-fixed-find-hdf5.patch done
-- Applying patch F:/git/vcpkg/ports/vtk/disable-workaround-findhdf5.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch F:/git/vcpkg/ports/vtk/disable-workaround-findhdf5.patch done
-- Applying patch F:/git/vcpkg/ports/vtk/fix-find-libproj4.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch F:/git/vcpkg/ports/vtk/fix-find-libproj4.patch done
-- Applying patch F:/git/vcpkg/ports/vtk/fix-find-libharu.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch F:/git/vcpkg/ports/vtk/fix-find-libharu.patch done
-- Applying patch F:/git/vcpkg/ports/vtk/fix-find-mysql.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch F:/git/vcpkg/ports/vtk/fix-find-mysql.patch done
-- Applying patch F:/git/vcpkg/ports/vtk/fix-find-odbc.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch F:/git/vcpkg/ports/vtk/fix-find-odbc.patch done
-- Configuring x64-windows
-- Configuring x64-windows done
-- Build x64-windows-dbg
CMake Error at F:/git/vcpkg/scripts/cmake/vcpkg_build_cmake.cmake:170 (message):
    Command failed: F:/git/vcpkg/downloads/tools/cmake-3.10.2-windows/cmake-3.10.2-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: F:/git/vcpkg/buildtrees/vtk/x64-windows-dbg
    See logs for more information:
      F:\git\vcpkg\buildtrees\vtk\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  F:/git/vcpkg/scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  F:/git/vcpkg/ports/vtk/portfile.cmake:172 (vcpkg_install_cmake)
  F:/git/vcpkg/scripts/ports.cmake:72 (include)

Error: Building package vtk:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: vtk:x64-windows
  Vcpkg version: 0.0.110-2018-05-10-9a19dae13a0fa594245db2df45ec54a504bc82f3

**Comment by Voskrese** [comment]
**See logs for more information:**

`F:\git\vcpkg\buildtrees\vtk\install-x64-windows-dbg-out.log`

**Comment by linapiao** [comment]
[install-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2011501/install-x64-windows-dbg-out.log)

**Comment by Voskrese** [comment]
there are no errors, the last line
`-- Installing: F:/git/vcpkg/packages/vtk_x64-windows/debug/include/vtkViewsGeovisModule.h`
It is necessary to look other logs

**Comment by wangli28** [comment]
Please open a new issue if this is still a problem for you.
Thanks.
