### ISSUE TITLE
vcpkg tool: format-manifest fails validation on fields starting with `$` having an array value.

### ISSUE THREAD

**Issue by antkmsft** [microsoft/vcpkg#34877]
Put the following in the port's vcpkg.json:
```json
  "$comment": "One line.",
  "name": ...
```

run `.\vcpkg format-manifest .\ports\...\vcpkg.json`. Everything succeeds as expected.

Now turn `$comment` into an array of strings:
```json
  "$comment": [
    "First line,",
    "Second line."
  ],
  "name": ...
```

run `.\vcpkg format-manifest .\ports\...\vcpkg.json`. It fails:
```
The serialized manifest was different from the original manifest. Please open an issue at https://github.com/microsoft/vcpkg, with the following output:
=== Original File ===
{
  "$comment": [
    "First line,",
    "Second line."
  ],
...

=== Serialized File ===
{
  "$comment": [
    "First line,",
    "Second line."
  ],
...

note: updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
```

Don't try to see the difference between "Original file" and "Serialized file" - it does not exist.

**Comment by antkmsft** [comment]
`vcpkg package management program version 2023-10-18-27de5b69dac4b6fe8259d283cd4011e6d20a84ce`

Maybe because I am on Windows? Could it be due to line endings?

**Comment by antkmsft** [comment]
I have a draft PR which reproduces the bug in the vcpkg CI: #34884 - you can see that "`Check For Common Mistakes / Check (pull_request)`" is failing - https://github.com/microsoft/vcpkg/actions/runs/6741679864/job/18326601999?pr=34884, with the exact error that I put in the bug description.

**Comment by LilyWangLL** [comment]
I can reproduce this issue localy.

**Comment by LilyWangLL** [comment]
My test vcpkg.json file: [vcpkg.json](https://github.com/microsoft/vcpkg/files/13247387/vcpkg.json).
The error message:
```
PS F:\test34877> .\vcpkg.exe format-manifest .\ports\lilytest\vcpkg.json
The serialized manifest was different from the original manifest. Please open an issue at https://github.com/microsoft/vcpkg, with the following output:
=== Original File ===
{
  "$comment": [
    "First line,",
    "Second line."
  ],
  "name": "azure-core-cpp"
}

=== Serialized File ===
{
  "$comment": [
    "First line,",
    "Second line."
  ],
  "name": "azure-core-cpp"
}


note: updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
```
cc @JavierMatosD @BillyONeal

**Comment by BillyONeal** [comment]
Fixed by https://github.com/microsoft/vcpkg/pull/35138
