### ISSUE TITLE
Cross-platform prefixes / suffixes (CMAKE_STATIC_LIBRARY_SUFFIX et al.)

### ISSUE THREAD

**Issue by terborg** [microsoft/vcpkg#3489]
Hey all, 

I'm trying to get started with vcpkg on Linux. One of the ports didn't build, due to having a hardcoded library suffix (.lib) in it (and more windows-specifics such as .exe). I've tried to fix the port, i.e., to replace the hardcoded string with variables such as CMAKE_STATIC_LIBRARY_SUFFIX. Unfortunately, those are not set when running through vcpkg. 

What would be the recommended set of variables to use for this?

Thanks!

**Comment by dereksbg** [comment]
I've resorted to defining them within the `CMakeList.txt` such as:
```
if (NOT DEFINED CMAKE_STATIC_LIBRARY_SUFFIX)
    if (WIN32)
        set(CMAKE_STATIC_LIBRARY_SUFFIX ".lib")
    else()
        set(CMAKE_STATIC_LIBRARY_PREFIX "lib")
        set(CMAKE_STATIC_LIBRARY_SUFFIX ".a")
    endif()
endif()
```

**Comment by Cheney-W** [comment]
Please refer to the reply of dereksbg.
