### ISSUE TITLE
[New Port Request] <GammaRay>

### ISSUE THREAD

**Issue by JoergAtGithub** [microsoft/vcpkg#34905]
### Library name

GammaRay

### Library description

Qt introspection tool (linked against specific Qt version)

### Source repository URL

https://github.com/KDAB/GammaRay

### Project homepage (if different from the source repository)

https://doc.qt.io/GammaRay/

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

The GammaRay Qt introspection tool must be build against a specific Qt build. Therefore it's not distributed as binary executable, just as source code.
A VCPKG-Tool-Port depending on the Qt-Port would perfectly fit here.

**Comment by JoergAtGithub** [comment]
Quote from the GammaRay documentation:
```
All of the following affect the compatibility of the [GammaRay](http://doc.qt.io/GammaRay) probe with the target application:

    Qt version
    Qt configuration
    system architecture (most prominently 32bit vs 64bit)
    compiler vendor (particularly on Windows)
    compiler settings (particularly debug or release mode, on Windows)
```

**Comment by JoergAtGithub** [comment]
Still needed!

**Comment by JoergAtGithub** [comment]
Still needed!

**Comment by JoergAtGithub** [comment]
Still needed!

**Comment by sfhacker** [comment]
@JoergAtGithub Keep praying!
