### ISSUE TITLE
[freeimage] build failure

### ISSUE THREAD

**Issue by inkfin** [microsoft/vcpkg#34926]
Compile error using vcpkg + Ninja + clang++

### Operating system

Windows 11

### Compiler

Clang

### Steps to reproduce the behavior

First, install the freeimage.

`vcpkg install freeimage`

I'm using the CMakeLists.txt and set the CMAKE_TOOLCHAIN_FILE variable to the local vcpkg.

Second, configure the CMake project using:
`cmake -S . -Bbuild -GNinja`

Third, try to build the project will pop error:
`cmake --build build`

Error: no such file or directory: `/EHsc`

Looks like an argument, but not properly setup for non-MSVC build systems. Can anyone help me with that?

### Failure logs

FAILED: CMakeFiles/FreeImageTest.dir/src/main.cpp.obj
......\clang++.exe -DGLFW_DLL -DIMATH_DLL -DNOMINMAX -DOPENEXR_DLL -D_USE_MATH_DEFINES -IC:/dev/Code/test/cpp/FreeImageTest/include -isystem C:/dev/Code/test/cpp/FreeImageTest/build-debug/vcpkg_installed/x64-windows/include -isystem C:/dev/Code/test/cpp/FreeImageTest/build-debug/vcpkg_installed/x64-windows/include/webp -isystem C:/dev/Code/test/cpp/FreeImageTest/build-debug/vcpkg_installed/x64-windows/include/OpenEXR -isystem C:/dev/Code/test/cpp/FreeImageTest/build-debug/vcpkg_installed/x64-windows/include/Imath -O0 -g -Xclang -gcodeview -std=c++14 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd /EHsc -MD -MT CMakeFiles/FreeImageTest.dir/src/main.cpp.obj -MF CMakeFiles\FreeImageTest.dir\src\main.cpp.obj.d -o CMakeFiles/FreeImageTest.dir/src/main.cpp.obj -c C:/dev/Code/test/cpp/FreeImageTest/src/main.cpp
clang++: error: no such file or directory: '/EHsc'
ninja: build stopped: subcommand failed.

**Comment by dg0yt** [comment]
So the toolchain used when building the package (MSVC) is not the same as when consuming the package (clang).

**Comment by inkfin** [comment]
> So the toolchain used when building the package (MSVC) is not the same as when consuming the package (clang).

Sorry for the late reply. Is this an issue on the user's side? Do I need to update some manifest parameters, or is it a problem with vcpkg?

**Comment by dg0yt** [comment]
I guess it is is a problem on the user side. If you are windows and don't use MSVC, you will have to inform the vcpkg CMake integration about the target triplet and chainloaded toolchain file.

**Comment by inkfin** [comment]
> I guess it is is a problem on the user side. If you are windows and don't use MSVC, you will have to inform the vcpkg CMake integration about the target triplet and chainloaded toolchain file.

I've tried to set CMAKE_TARGET_TRIPLET to "x64-windows-static" manually, but the result is the same, the flag is still `/EHsc` (MSVC kind).

**Comment by dg0yt** [comment]
AFAICT `x64-windows-static` means `windows.cmake` means MSVC.

**Comment by inkfin** [comment]
Ok, now I set how to set toolchains to llvm. I use custom triplets: ![my-vcpkg-triplets](https://github.com/Neumann-A/my-vcpkg-triplets) to build the required package.

```shell
# in vcpkg.json
  "vcpkg-configuration": {
    "overlay-triplets": ["./vcpkg-triplets"]
  }
# in CmakeLists.txt
set(VCPKG_HOST_TRIPLET "x64-win-llvm")
set(VCPKG_TARGET_TRIPLET "x64-win-llvm")
```
but it still has the wrong flag, what else could go wrong?
