### ISSUE TITLE
Can't build gdal on Ubuntu 18.04

### ISSUE THREAD

**Issue by razor85** [Microsoft/vcpkg#3493]
Trying to build gdal on Ubuntu 18.04 errors:

Building package libevent[core]:x64-linux... 
-- CURRENT_INSTALLED_DIR=/home/csr/Dev/vcpkg/installed/x64-linux
-- DOWNLOADS=/home/csr/Dev/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=/home/csr/Dev/vcpkg/packages/libevent_x64-linux
-- CURRENT_BUILDTREES_DIR=/home/csr/Dev/vcpkg/buildtrees/libevent
-- CURRENT_PORT_DIR=/home/csr/Dev/vcpkg/ports/libevent
-- Using cached /home/csr/Dev/vcpkg/downloads/libevent-libevent-release-2.1.8-stable.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Applying patch /home/csr/Dev/vcpkg/ports/libevent/fix-target-files.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch /home/csr/Dev/vcpkg/ports/libevent/fix-target-files.patch done
-- Configuring x64-linux-dbg
-- Configuring x64-linux-dbg done
-- Configuring x64-linux-rel
-- Configuring x64-linux-rel done
-- Build x64-linux-dbg
-- Build x64-linux-dbg done
-- Build x64-linux-rel
-- Build x64-linux-rel done
CMake Error at scripts/cmake/vcpkg_fixup_cmake_targets.cmake:42 (message):
  '/home/csr/Dev/vcpkg/packages/libevent_x64-linux/debug/cmake' does not
  exist.
Call Stack (most recent call first):
  ports/libevent/portfile.cmake:34 (vcpkg_fixup_cmake_targets)
  scripts/ports.cmake:72 (include)

Error: Building package libevent:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libevent:x64-linux
  Vcpkg version: 0.0.111-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by Voskrese** [comment]
**libevent Can't build**

**Comment by razor85** [comment]
Now building stops on openssl.
```
[1/4] cd /home/csr/Dev/vcpkg/buildtrees/openssl/x64-linux-dbg/openssl-1.0.2o && export CC=/usr/bin/cc && export AR=/usr/bin/ar && export LD=/usr/bin/ld && export RANLIB=/usr/bin/ranlib && export MAKE=/usr/bin/make && export MAKEDEPPROG=/usr/bin/cc && export "PATH=/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin;/usr/bin;/home/csr/Dev/vcpkg/downloads/tools/ninja-1.8.2-linux" && /usr/bin/perl Configure no-shared enable-static-engine no-ssl2 no-krb5 no-idea no-bf no-cast no-seed no-md2 linux-generic32 --prefix=/home/csr/Dev/vcpkg/packages/openssl_x64-linux/debug --openssldir=/home/csr/Dev/vcpkg/packages/openssl_x64-linux/debug " " && /home/csr/Dev/vcpkg/downloads/tools/cmake-3.10.2-linux/cmake-3.10.2-Linux-x86_64/bin/cmake -DDIR=/home/csr/Dev/vcpkg/buildtrees/openssl/x64-linux-dbg/openssl-1.0.2o -P /home/csr/Dev/vcpkg/ports/openssl/remove-deps.cmake
FAILED: openssl-1.0.2o/Makefile 
cd /home/csr/Dev/vcpkg/buildtrees/openssl/x64-linux-dbg/openssl-1.0.2o && export CC=/usr/bin/cc && export AR=/usr/bin/ar && export LD=/usr/bin/ld && export RANLIB=/usr/bin/ranlib && export MAKE=/usr/bin/make && export MAKEDEPPROG=/usr/bin/cc && export "PATH=/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin;/usr/bin;/home/csr/Dev/vcpkg/downloads/tools/ninja-1.8.2-linux" && /usr/bin/perl Configure no-shared enable-static-engine no-ssl2 no-krb5 no-idea no-bf no-cast no-seed no-md2 linux-generic32 --prefix=/home/csr/Dev/vcpkg/packages/openssl_x64-linux/debug --openssldir=/home/csr/Dev/vcpkg/packages/openssl_x64-linux/debug " " && /home/csr/Dev/vcpkg/downloads/tools/cmake-3.10.2-linux/cmake-3.10.2-Linux-x86_64/bin/cmake -DDIR=/home/csr/Dev/vcpkg/buildtrees/openssl/x64-linux-dbg/openssl-1.0.2o -P /home/csr/Dev/vcpkg/ports/openssl/remove-deps.cmake
target already defined - linux-generic32 (offending arg:  )
ninja: build stopped: subcommand failed.
```

**Comment by razor85** [comment]
Building today fails on openjpeg:
openjpeg:x64-linux
Vcpkg version: 0.0.113-unknownhash

CMake Error: INSTALL(EXPORT) given unknown export "OpenJPEGTargets"
CMake Warning:
  Manually-specified variables were not used by the project:
  
    CMAKE_INSTALL_BINDIR
    CMAKE_INSTALL_LIBDIR
    VCPKG_CRT_LINKAGE
    VCPKG_PLATFORM_TOOLSET

**Comment by suryakiran** [comment]
I'd like to reopen this ticket as I'm unable to build gdal on ubuntu 18.04 with latest vcpkg source. The failure happens to be in building sdl1 package. vcpkg is trying to build windows version of sdl1 (using msbuild command).

```bash
./vcpkg install gdal:x64-linux 
```
> The following packages will be built and installed:
>   * curl[core,openssl,ssl]:x64-linux
>   * freeglut[core]:x64-linux
>     gdal[core]:x64-linux
>   * giflib[core]:x64-linux
>   * hdf5[core]:x64-linux
>   * libwebp[all,core]:x64-linux
>   * netcdf-c[core]:x64-linux
>   * opengl[core]:x64-linux
>   * openjpeg[core]:x64-linux
>   * proj[core]:x64-linux
>   * proj4[core]:x64-linux
>   * sdl1[core]:x64-linux
>   * szip[core]:x64-linux
>   * tiff[core]:x64-linux
> Additional packages (*) will be modified to complete this operation.
> Starting package 1/14: sdl1:x64-linux
> Building package sdl1[core]:x64-linux... 
> -- Note: sdl1 only supports dynamic library linkage. Building dynamic library.
> -- Using cached /home/surya/Projects/SourceArea/vcpkg/downloads/SDL-Mirror-SDL-release-1.2.15.tar.gz
> -- Using source at /home/surya/Projects/SourceArea/vcpkg/buildtrees/sdl1/src/ase-1.2.15-2ca6426de6
> -- Building VisualC/SDL1_2017.sln for Release
> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
>     Command failed: msbuild;/home/surya/Projects/SourceArea/vcpkg/buildtrees/sdl1/x64-linux-rel/ase-1.2.15-2ca6426de6/VisualC/SDL1_2017.sln;/p:Configuration=Release;/t:Rebuild;/p:Platform=x64;/p:PlatformToolset=external;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No;/p:WindowsTargetPlatformVersion=;/m
>     Working Directory: /home/surya/Projects/SourceArea/vcpkg/buildtrees/sdl1/x64-linux-rel/ase-1.2.15-2ca6426de6
>     Error code: No such file or directory
>     See logs for more information:
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_install_msbuild.cmake:157 (vcpkg_execute_required_process)
>   ports/sdl1/portfile.cmake:23 (vcpkg_install_msbuild)
>   scripts/ports.cmake:71 (include)
> 
> 
> Error: Building package sdl1:x64-linux failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: sdl1:x64-linux
>   Vcpkg version: 2018.11.23-unknownhash
> 
> Additionally, attach any relevant sections from the log files above.
>

**Comment by NancyLi1013** [comment]
Hi @suryakiran , thank you for posting this issue. The problem you appeared is that sdl1 failed to build. So I open a new issue about this. Let's track this issue here #5813.
