### ISSUE TITLE
Unable to include the header files for x86-windows-static or x64-windows-static

### ISSUE THREAD

**Issue by xengine-qyt** [microsoft/vcpkg#34934]
**Describe the bug**
The library compiled with static linkage cannot be included in VS 2022, and it prompts that the header file cannot be found

**Environment**
- OS: windows
- Compiler: vs2022 17.7.6

**To Reproduce**

`
D:\vcpkg>vcpkg.exe integrate install
Applied user-wide integration for this vcpkg root.
CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=D:/vcpkg/scripts/buildsystems/vcpkg.cmake"

All MSBuild C++ projects can now #include any installed libraries. Linking will be handled automatically. Installing new libraries will make them instantly available.

D:\vcpkg>vcpkg.exe install openssl:x86-windows-static
Computing installation plan...
A suitable version of cmake was not found (required v3.27.1) Downloading portable cmake 3.27.1...
Downloading cmake...
https://github.com/Kitware/CMake/releases/download/v3.27.1/cmake-3.27.1-windows-i386.zip->D:\vcpkg\downloads\cmake-3.27.1-windows-i386.zip
Downloading https://github.com/Kitware/CMake/releases/download/v3.27.1/cmake-3.27.1-windows-i386.zip
Extracting cmake...
The following packages will be built and installed:
    openssl:x86-windows-static -> 3.1.4#1
  * vcpkg-cmake:x64-windows -> 2023-05-04
  * vcpkg-cmake-config:x64-windows -> 2022-02-06#1
  * vcpkg-cmake-get-vars:x64-windows -> 2023-03-02
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
-- Automatically setting %HTTP(S)_PROXY% environment variables to "127.0.0.1:7890".
A suitable version of powershell-core was not found (required v7.2.11) Downloading portable powershell-core 7.2.11...
Downloading powershell-core...
https://github.com/PowerShell/PowerShell/releases/download/v7.2.11/PowerShell-7.2.11-win-x86.zip->D:\vcpkg\downloads\PowerShell-7.2.11-win-x86.zip
Downloading https://github.com/PowerShell/PowerShell/releases/download/v7.2.11/PowerShell-7.2.11-win-x86.zip
Extracting powershell-core...
Detecting compiler hash for triplet x86-windows-static...
A suitable version of 7zip was not found (required v23.1.0) Downloading portable 7zip 23.1.0...
Downloading 7zip...
https://www.7-zip.org/a/7z2301-extra.7z->D:\vcpkg\downloads\7z2301-extra.7z
Downloading https://www.7-zip.org/a/7z2301-extra.7z
Extracting 7zip...
Restored 4 package(s) from C:\Users\qyt\AppData\Local\vcpkg\archives in 529 ms. Use --debug to see more details.
Installing 1/4 vcpkg-cmake:x64-windows...
Elapsed time to handle vcpkg-cmake:x64-windows: 3.18 ms
Installing 2/4 vcpkg-cmake-config:x64-windows...
Elapsed time to handle vcpkg-cmake-config:x64-windows: 15.1 ms
Installing 3/4 vcpkg-cmake-get-vars:x64-windows...
Elapsed time to handle vcpkg-cmake-get-vars:x64-windows: 9.39 ms
Installing 4/4 openssl:x86-windows-static...
Elapsed time to handle openssl:x86-windows-static: 26.9 ms
Total install time: 54.9 ms
The package openssl is compatible with built-in CMake targets:

    find_package(OpenSSL REQUIRED)
    target_link_libraries(main PRIVATE OpenSSL::SSL OpenSSL::Crypto)
`

include openssl header in vs2022 

#include <openssl/rsa.h>

and complie report error:fatal  error C1083: can not open file: “openssl/rsa.h”: No such file or directory
x64-windows-static is too...

**Comment by JonLiu1993** [comment]
@xengine-qyt, Thanks for posting this issue, I can successfully use `openssl:x64-windows-static`:
````
#include <stdio.h>
#include <openssl/rsa.h>

int main()
{
    printf("%s\n", "HELLO WORLD");
    return 0;
}
````
````
>------ Build All started: Project: usageTest, Configuration: x64-Debug ------
  MSBuild version 17.6.3+07e294721 for .NET Framework
  
    Checking Build System
    Building Custom Rule C:/Users/test/source/repos/usageTest/usageTest/CMakeLists.txt
    usageTest.cpp
    test.vcxproj -> C:\Users\test\source\repos\usageTest\out\build\x64-debug\usageTest\Debug\test.exe
    Building Custom Rule C:/Users/test/source/repos/usageTest/CMakeLists.txt

Build All succeeded.
````
This is my CMakeSettings.json:
````
{
  "configurations": [
    {
      "name": "x64-Debug",
      "generator": "Visual Studio 17 2022 Win64",
      "configurationType": "Debug",
      "inheritEnvironments": [ "msvc_x64_x64" ],
      "buildRoot": "${projectDir}\\out\\build\\${name}",
      "installRoot": "${projectDir}\\out\\install\\${name}",
      "cmakeCommandArgs": "-DCMAKE_TOOLCHAIN_FILE=F:/test/vcpkg/scripts/buildsystems/vcpkg.cmake",
      "buildCommandArgs": "",
      "ctestCommandArgs": "",
      "variables": [
        {
          "name": "VCPKG_TARGET_TRIPLET",
          "value": "x64-windows-static"
        }
      ]
    }
   ]
}
````
Please  checkout your CMakeSettings.json.

**Comment by xengine-qyt** [comment]
i used vs2022 c++，no cmake..How strange. It works fine when I use a dynamic library,may be i need to reinstall the system

**Comment by xengine-qyt** [comment]
o,..i know
