### ISSUE TITLE
I used git pull and vcpkg updata, but it still reported errors during download

### ISSUE THREAD

**Issue by dailuo124** [microsoft/vcpkg#34948]
![image](https://github.com/microsoft/vcpkg/assets/118441712/00a70fea-ba76-4572-b563-758762110c27)
![image](https://github.com/microsoft/vcpkg/assets/118441712/46609dad-e56e-44b2-82c5-1026e6f23818)
![image](https://github.com/microsoft/vcpkg/assets/118441712/dde71402-cb0c-40a1-a452-b3c7e8021127)
![image](https://github.com/microsoft/vcpkg/assets/118441712/1376c0c7-10b0-4151-b518-21c31d49d1ea)
So what should I do to solve this problem

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Firstly, please clone vcpkg in a full English path, then run command `git pull` and `.\bootstrap-vcpkg.bat`, then rebuild `boost-config:x64-windows`.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
