### ISSUE TITLE
[openssl] legacy load failed on Windows Server 2019

### ISSUE THREAD

**Issue by yuntong613** [microsoft/vcpkg#34949]
### Is your feature request related to a problem? Please describe.

cmd> vcpkg install openssl:x64-windows

legacy provider is installed as dynamic library in “vcpkg installed" directory on Windows，but static library on Linux。
Windows 2019 can not find legacy.dll path by default，I need to copy legacy.dll to target PC and set module search path 
by function OSSL_PROVIDER_set_default_search_path in my source code before I use OSSL_PROVIDER_load.

vcpkg integrate with vs2022, when projects build finished, file "legacy.dll" didn't copy to target output directory, but only libssl and libcrypto.

### Proposed solution

Could you please build openssl dynamic library  with static legacy provider library inside?  If not, could you please copy "legacy.dll” to target directory such as “[OutPutDir]/ossl-modules”

**Comment by dg0yt** [comment]
> legacy provider is installed as dynamic library in “vcpkg installed" directory on Windows，but static library on Linux。

I think it simply follows the triplet settings.

> Could you please build openssl dynamic library with static legacy provider library inside? 

Does OpenSSL officially provide this configuration (options)?

> If not, could you please copy "legacy.dll” to target directory such as “[OutPutDir]/ossl-modules”

vcpkg has no general solution to copy modules aka plugins.
