### ISSUE TITLE
[luajit] add CMake targets / usage

### ISSUE THREAD

**Issue by Arcnor** [microsoft/vcpkg#34954]
### Is your feature request related to a problem? Please describe.

`luajit` doesn't have targets or usage

### Proposed solution

* Add Cmake targets
* Add usage

**Comment by WangWeiLin-MV** [comment]
The package `luajit` can be imported via `CMake` `FindPkgConfig` module:

    find_package(PkgConfig REQUIRED)
    pkg_check_modules(LUAJIT REQUIRED IMPORTED_TARGET luajit)
    target_link_libraries(main PRIVATE PkgConfig::LUAJIT)
