### ISSUE TITLE
New ports: python2, boost-python2 and boost-python3

### ISSUE THREAD

**Issue by yurybura** [microsoft/vcpkg#3495]
With Boost v1.67 is possible to build variants for multiple Python versions in a single build process. For example, a variant compiled with Python 2.7 will produce library names boost_python27 and boost_numpy27, etc.

Unfortunately, vcpkg hasn't port for python2.

**Comment by Voskrese** [comment]
the port will not be compatible with python3, only as a library, and for now vcpkg takes variables from the registry for python2
it makes no sense to add a port

**Comment by yurybura** [comment]
There is not able to build boost_python27 library. Vcpkg can build only boost_python36.

**Comment by yurybura** [comment]
This is workaround. There no possible to mix python2 and python3 dependencies.

**Comment by Voskrese** [comment]
this is not a solution, it's an example that can be changed from 3 to 2
almost without difficulty

there would be a desire!

**Comment by cmpute** [comment]
I believe this should be a good case for #2823

**Comment by TheAifam5** [comment]
Here is port for python2: https://github.com/Microsoft/vcpkg/pull/3999

**Comment by yurybura** [comment]
> Here is port for python2: #3999

Thanks! It remains to do just boost-python2)

**Comment by dcnieho** [comment]
This is not working for me. On an up to date vcpkg, Windows 10, i have boost-python, not boost-python2 or boost-python3:
``vcpkg install boost-python2
Error: Unable to install default features because can't find CONTROL for boost-python2:x86-windows``

**Comment by dcnieho** [comment]
Sorry, I was a bit terse: that was a request for help. Am I doing something wrong? I'd like to install boost-python for python 2. The only package available for me (x86 or x64) is boost-python, which uses python 3. How do i get this boost-python2 package to show up?

**Comment by yurybura** [comment]
After merging #6639 Python2 will be supported as module. Command to install:
`vcpkg install boost-python[python2]`
