### ISSUE TITLE
[boost-regex] Build error

### ISSUE THREAD

**Issue by dailuo124** [microsoft/vcpkg#34959]
I don't know how to handle this problem. Please help
![image](https://github.com/microsoft/vcpkg/assets/118441712/9edbdc59-5089-4ca0-84ad-2f53ee03ef18)
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/13283844/install-x64-windows-dbg-out.log)

**Comment by LilyWangLL** [comment]
Duplicated of https://github.com/microsoft/vcpkg/issues/24473, https://github.com/microsoft/vcpkg/issues/26850. Did you install anti-virus software on your machine?

**Comment by dailuo124** [comment]
Yes,i did,thank you for your help.What should i do?







                       
原始邮件
                       
                     

发件人："Lily Wang"< ***@***.*** &gt;;

发件时间：2023/11/8 11:02

收件人："microsoft/vcpkg"< ***@***.*** &gt;;

抄送人："dailuo124"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [microsoft/vcpkg] [boost-regex] Build error (Issue #34959)




 
Duplicated of #24473, #26850. Did you install anti-virus software on your machine?

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
