### ISSUE TITLE
Could not find Visual Studio. VS2015 or VS2017 (with C++)

### ISSUE THREAD

**Issue by daoqiang** [Microsoft/vcpkg#3497]
I have installed vs2017 community 15.7.1
![default](https://user-images.githubusercontent.com/16305190/40028968-745a52b0-5814-11e8-8125-0aa234cad315.PNG)

**Comment by daoqiang** [comment]
The problem has been solved, and vs2015 platform tools need to be installed.

**Comment by alexkaratarakis** [comment]
Glad it is working!
