### ISSUE TITLE
issue about doc of "vcpkg env"

### ISSUE THREAD

**Issue by QiuYilin** [microsoft/vcpkg#34970]
In doc https://learn.microsoft.com/en-us/vcpkg/commands/env，the method of saving environment variables is described as follows:
```
PS C:\Users\vcpkg\vcpkg> $env:CLEARED_ENV_VAR="hello"
PS C:\Users\vcpkg\vcpkg> vcpkg env "set CLEARED_ENV_VAR"
Environment variable CLEARED_ENV_VAR not defined
PS C:\Users\vcpkg\vcpkg> $env:KEEP_ENV_VARS="CLEARED_ENV_VAR"
PS C:\Users\vcpkg\vcpkg> vcpkg env "set CLEARED_ENV_VAR"
CLEARED_ENV_VAR=hello
```
It does not work. Maybe it should be :
```
PS C:\Users\vcpkg\vcpkg> $env:VCPKG_KEEP_ENV_VARS="CLEARED_ENV_VAR"
```

**Comment by MonicaLiu0311** [comment]
Issues related to the documentation of vcpkg now need to be reported at https://github.com/microsoft/vcpkg-docs. I have transferred this issue for you. The new issue is: https://github.com/microsoft/vcpkg-docs/issues/208.
