### ISSUE TITLE
[dartsim] fail to use the usage in cmake.

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#34985]
**Describe the bug**
Cmake error while using the usage in dartsim
From [#34928](https://github.com/microsoft/vcpkg/pull/34928#issuecomment-1800918434)

**Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
1. ./vcpkg install dartsim
2. Try to use the usage.

**Expected behavior**
Should not reproduce error while using the port. 

**Failure logs**
The following error occurred when testing usage. CMakeLists.txt

```cmake
add_executable (testdartsim "testdartsim.cpp" "testdartsim.h")
find_package(DART CONFIG REQUIRED)
target_link_libraries(testdartsim PRIVATE ODE::ODE OpenGL::GL OpenGL::GLU Boost::system)
```

```cmake
Error		CMake Error at testdartsim/CMakeLists.txt:9 (target_link_libraries):
  Target "testdartsim" links to:

    ODE::ODE

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.		
```

**Additional context**
https://github.com/microsoft/vcpkg/pull/34928#issuecomment-1800918434

**Comment by FrankXie05** [comment]
This usage is incorrect，at least `dart` will not link with `ode` on version `6.12.2`. 
https://github.com/dartsim/dart/blob/1fe8fa2c53976d57003edb293b62eac747247d19/dart/collision/ode/CMakeLists.txt#L17
[dart-collision-ode](https://github.com/dartsim/dart/blob/1fe8fa2c53976d57003edb293b62eac747247d19/dart/collision/ode/CMakeLists.txt#L3)
```
target_link_libraries(testdartsim PRIVATE ODE::ODE OpenGL::GL OpenGL::GLU Boost::system)
```

**Comment by talregev** [comment]
> This usage is incorrect，at least `dart` will not link with `ode` on version `6.12.2`. https://github.com/dartsim/dart/blob/1fe8fa2c53976d57003edb293b62eac747247d19/dart/collision/ode/CMakeLists.txt#L17 [dart-collision-ode](https://github.com/dartsim/dart/blob/1fe8fa2c53976d57003edb293b62eac747247d19/dart/collision/ode/CMakeLists.txt#L3)
> 
> ```
> target_link_libraries(testdartsim PRIVATE ODE::ODE OpenGL::GL OpenGL::GLU Boost::system)
> ```

That why I opened this issue.
Can you fix it?

**Comment by FrankXie05** [comment]
@talregev Yes, I will do it. :)

**Comment by dg0yt** [comment]
> target_link_libraries(testdartsim PRIVATE ODE::ODE OpenGL::GL OpenGL::GLU Boost::system)

I guess this is a pure usage heuristics artifact, from reporting any target found in the package's directory. It even lacks a target for dartsim. Maybe the official cmake usage is via output variables?

**Comment by FrankXie05** [comment]
I don't think we completely disabled the `testing` and `examples`.
