### ISSUE TITLE
[zlib] Build error

### ISSUE THREAD

**Issue by Killershark9988** [microsoft/vcpkg#34988]
Copy issue body from /home/kali/New Folder/vcpkg/installed/vcpkg/issue_body.md
error: building zlib:x64-linux failed with: BUILD_FAILED
Elapsed time to handle zlib:x64-linux: 10 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.                                                        
Then check for known issues at:                                       
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+zlib                                                          
You can submit a new issue at:                                        
  https://github.com/microsoft/vcpkg/issues/new?title=[zlib]+Build+error&body=Copy+issue+body+from+%2Fhome%2Fkali%2FNew%20Folder%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by MonicaLiu0311** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report an issue.
