### ISSUE TITLE
[opencv4] Found system OpenJPEG

### ISSUE THREAD

**Issue by KOConchobhair** [microsoft/vcpkg#34986]
### Operating system

macOS (arm64-apple-darwin22.5.0)

### Compiler

Apple clang version 14.0.3 (clang-1403.0.22.14.1)

### Steps to reproduce the behavior

After #34961, I enabled the new `"openjpeg"` feature in my use of opencv4 in my project using the following `vcpkg.json` manifest.
```Shell
cmake -DCMAKE_TOOLCHAIN_FILE=~/Work/git/vcpkg/scripts/buildsystems/vcpkg.cmake ..

{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg.schema.json",
  "dependencies": [
    {
      "name": "opencv4",
      "default-features": false,
      "features": ["dnn", "jpeg", "png", "tiff", "webp", "openexr", "openjpeg"]
    }
  ],
  "overrides": [
    { "name": "opencv4", "version": "4.8.0", "port-version": 10 },
    { "name": "libwebp", "version": "1.3.2" },
    { "name": "protobuf", "version": "3.19.4" }
  ],
  "builtin-baseline": "4e5e6b3fa66f0c52be86f7034792f45f959ec582"
}
```
OpenJPEG gets built successfully - `vcpkg_installed/arm64-osx/lib/libopenjp2.a: current ar archive random library`
but my project cannot find it at link time...
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ <snip> -lopenjp2 ../../vcpkg_installed/arm64-osx/lib/libopencv_core4.a ../../vcpkg_installed/arm64-osx/lib/libz.a <snip>
ld: library not found for -lopenjp2
```

### Failure logs

I checked the configure from opencv (`~/Work/git/vcpkg/buildtrees/opencv4/config-arm64-osx-out.log`) and saw
`-- Found system OpenJPEG: openjp2 (found version "")`
the rest of the discovery is working, for example
```
-- Found ZLIB: /Users/koconnor/Work/git/build-vcpkg/vcpkg_installed/arm64-osx/lib/libz.a (found version "1.3.0")
-- Found system OpenJPEG: openjp2 (found version "")
-- Found PNG: /Users/koconnor/Work/git/build-vcpkg/vcpkg_installed/arm64-osx/lib/libpng16.a (found version "1.6.39")
-- Looking for /Users/koconnor/Work/git/build-vcpkg/vcpkg_installed/arm64-osx/include/libpng/png.h
-- Looking for /Users/koconnor/Work/git/build-vcpkg/vcpkg_installed/arm64-osx/include/libpng/png.h - not found
-- Found Protobuf: /Users/koconnor/Work/git/build-vcpkg/vcpkg_installed/arm64-osx/tools/protobuf/protoc-3.19.4.0 (found version "3.19.4.0")
```

### Additional context

I thought this change would already cover it
https://github.com/microsoft/vcpkg/blob/fe1e9f508ee13ed3d0a7d318beac7efe1ec4f9d7/ports/opencv4/0003-force-package-requirements.patch#L44

is there some difference in the naming since the build artifacts are named `libopenjp2` (`vcpkg_installed/arm64-osx/lib/pkgconfig/libopenjp2.pc`)
I'm happy to provide the PR for a fix just need some help. Any other example of a port using OpenJPEG and using `find_package` for the vcpkg-built version that you could point me to?

**Comment by Osyotr** [comment]
>  -- Found system OpenJPEG: openjp2 (found version "")

In find_package world "system" often means "vcpkg". Have you checked what files has been found? (hint: run with vcpkg with `--x-cmake-args=--trace-expand`)
The problem might be that opencv's cmake config is missing required `find_dependency(openjp2)` call.

**Comment by KOConchobhair** [comment]
Okay I'll try that command, thank you. 

Although it doesn't seem likely to mean "vcpkg" in this case since it ends up looking for a shared library instead of the static one that vcpkg built. Also, all the rest of the libraries opencv depends on shows their path as coming from the vcpkg_installed folder. 

I've built opencv outside of vcpkg and the openjpeg static dependency works fine so I guess there's another patch that needs to be applied or modified for the opencv4 port (maybe the one I linked above)

**Comment by JonLiu1993** [comment]
@KOConchobhair, Thanks for posting this issue, please provide your test project, I will try repro your error.

**Comment by KOConchobhair** [comment]
> In find_package world "system" often means "vcpkg". 

You are right @Osyotr !
```//The directory containing a CMake configuration file for OpenJPEG.
OpenJPEG_DIR:PATH=/Users/ko/Work/git/build-vcpkg/vcpkg_installed/arm64-osx/share/openjpeg
```

So vcpkg opencv is finding all the static image codecs from vcpkg installed properly. Not sure why it's resulting in an attempt to dynamically link `-lopenjp2`. Especially when all the cmake/pkgconfig files for openjpeg specify it as static library...

here's the repro @JonLiu1993 
```
gh repo clone biometrics/openbr
cd openbr
git submodule init
git submodule update
curl -O https://gist.githubusercontent.com/KOConchobhair/415e90a74c43d39fd2419afaa8c2f446/raw/e2be259fe17b5e9cd54f0f974f8d8363d53744c0/vcpkg.json
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install -DBR_INSTALL_DEPENDENCIES=ON -DBR_EMBEDDED=ON -DCMAKE_TOOLCHAIN_FILE=~/Work/git/vcpkg/scripts/buildsystems/vcpkg.cmake ..
```

the resulting warning may or may not be relevant:
```
CMake Warning (dev) at /Users/ko/Work/git/vcpkg/scripts/buildsystems/vcpkg.cmake:639 (_add_library):
  Policy CMP0003 should be set before this line.  Add code such as

    if(COMMAND cmake_policy)
      cmake_policy(SET CMP0003 NEW)
    endif(COMMAND cmake_policy)

  as early as possible but after the most recent call to
  cmake_minimum_required or cmake_policy(VERSION).  This warning appears
  because target "openbr" links to some libraries for which the linker must
  search:

    openjp2, m
```

`cmake version 3.26.4`

Thanks in advance!

**Comment by Osyotr** [comment]
I suspect that there's `target_link_libraries(target PRIVATE openjp2)` somewhere and it resorts to `-lopenjp2` because there's no `openjp2` target. What if you call `find_package(openjp2 REQUIRED)` manually in your project? If that succeeds then you definitely need to add `find_dependency(openjp2)` to opencv cmake config.

**Comment by JonLiu1993** [comment]
This issue could be reproduced with vcpkg 2023-09-15-ac02a9f660977426b8ec6392919fbb1d51b10998 and VS2022 17.6.6.
@KOConchobhair, could you please commit a PR to fix this issue, thanks.

**Comment by KOConchobhair** [comment]
> What if you call `find_package(openjp2 REQUIRED)` manually in your project?

Results in an error on cmake configure
```
CMake Error at /Users/ko/Work/git/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package):
  By not providing "Findopenjp2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "openjp2", but
  CMake did not find one.

  Could not find a package configuration file provided by "openjp2" with any
  of the following names:

    openjp2Config.cmake
    openjp2-config.cmake

  Add the installation prefix of "openjp2" to CMAKE_PREFIX_PATH or set
  "openjp2_DIR" to a directory containing one of the above files.  If
  "openjp2" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  openbr/CMakeLists.txt:94 (find_package)
```

However, adding `find_package(OpenJPEG REQUIRED)` to my project seems to fix the issue. 
So yeah, happy to put up a PR but not quite following what the correct solution should be.

Add `find_dependency(OpenJPEG)` to opencv via a patch in vcpkg?
Note that OpenCV in vcpkg is already patched to call `find_package(OpenJPEG REQUIRED)`

Thank you!

**Comment by Osyotr** [comment]
> So yeah, happy to put up a PR but not quite following what the correct solution should be.

The proper way is to call `find_dependency(...)` in opencv's cmake config file, but I couldn't find a place where other dependencies are searched.

Looks like static opencv does not support packaging yet (https://github.com/opencv/opencv/issues/18521#issuecomment-704529715).

**Comment by KOConchobhair** [comment]
Hmm okay. But that’s *really* interesting and weird then considering it
works for every other static library dependency (openexr, libpng, tiff,
libjpeg-turbo, etc.) except OpenJPEG. I wonder what the difference is…

**Comment by dg0yt** [comment]
The point with CMake package OpenJPEG is that it provides a target `openjp2` without a namespace prefix.

So `target_link_libraries(main PRIVATE openjp2)` has two alternative behaviours:
- Without `find_package`/`find_dependency`, it is just a namespec to be passed to the linker (`-lopenjp2`). It the linker doesn't find a matching lib in its search path, the build fails very late (`ld: library not found for -lopenjp2`).
- With `find_package`/`find_dependency`, it becomes a target name, and CMake inspects target properties for including directories, link lib filepaths, and transitive usage requirements.

If OpenJPEG would use a namespaced target, CMake could recognize a missing target definition in the generation step, and it would propose to add a missing `find_package`... That's why exported targets should use namespaces in Modern CMake.

But without namespace, detecting the problem must be left to the user.

**Comment by KOConchobhair** [comment]
hmm, maybe adding the `find_dependency` here for OpenJPEG just like OpenEXR might do the trick?
https://github.com/microsoft/vcpkg/blob/abe01a20d3652f9443eed96bc7ec888d5d194674/ports/opencv4/portfile.cmake#L537

**Comment by Osyotr** [comment]
> hmm, maybe adding the `find_dependency` here for OpenJPEG just like OpenEXR might do the trick?

Yeah, looks like it's the right place for now.
