### ISSUE TITLE
Linking to LCMS can't find debug DLL 

### ISSUE THREAD

**Issue by angelmixu** [Microsoft/vcpkg#3498]
Hi people!

I'm linking to LCMS in my application and when using it on release there's no problem, but when compiling and running on debug the application can't find the DLL file.

Maybe the error comes from this PR: https://github.com/Microsoft/vcpkg/pull/2187/commits/28aaced0f592796f65102c516627a939d9bd7fa8

The dll file is called lcms2d.dll, and when running the application it looks for lcms2.dll (without a d).

The easy fix is removing the 'd' extension on the DLL, but what I wanted to do is specify in CMakeLists.txt to create/link to lcms2d.dll instead of only renaming the output file, but I haven't found anything similar to edit the CMakeLists.txt or the portfile.

Anyone can point me to the right direction? I could create a PR once I have it.
Thanks! :)

**Comment by CharlesUnruh** [comment]
I wish I had a solution for you, but I can tie this in with another open issue:
https://github.com/Microsoft/vcpkg/issues/3447

SFML debug dependencies also feature the 'd' suffix, e.g. freetyped.dll, and are not copied for debug build targets.

**Comment by angelmixu** [comment]
Hi @CharlesUnruh !

The issue you pointed looks like something similar, but I think it's not the same.
In that issue, as I understand, the problem is that dll's are not being copied correctly to the destination directory, but if you manually copy the dll's, then the applications works correctly. So the libraries they're linking with have the correct naming, only that they're not being copied.

In my case, when the application links against debug freetyped.lib, this library is compiled for loading a DLL with "freetype.dll" filename, thus, as in the CMakeLists.txt change in PR https://github.com/Microsoft/vcpkg/commit/28aaced0f592796f65102c516627a939d9bd7fa8 , it is renamed to "freetyped.dll" so it's not found for loading. 
So, the .lib looks for an exact named .dll file which later has been renamed without telling the .lib it has been changed.

**Comment by IronicallySerious** [comment]
On my Windows 10 Home edition, lcms2.dll was not being copied to build destination directory. One solution was to add lcms2.dll to the builld destination but I added it to my system folder to remove any future hassle.

**Comment by Cheney-W** [comment]
@angelmixu , could you provide a repro project?

**Comment by angelmixu** [comment]
@Cheney-W hi! I just made a project and looks like it has been fixed :)
I'll close the issue.
Thanks!!
