### ISSUE TITLE
Add FlatBuffers

### ISSUE THREAD

**Issue by aardappel** [Microsoft/vcpkg#35]
FlatBuffers is an efficient zero-copy/parse/allocation serialization library.

repo: https://github.com/google/flatbuffers
docs: http://google.github.io/flatbuffers/

**Comment by ras0219-msft** [comment]
@aardappel I'd appreciate you taking a look over 9e43dbb if you get a chance!

**Comment by aardappel** [comment]
@ras0219-msft : Just did.. Thanks!
