### ISSUE TITLE
[qtwebengine] build failure (with solution)

### ISSUE THREAD

**Issue by WiestDaessle** [microsoft/vcpkg#35008]
git### Operating system

Windows 10 (22H2 / 19045.3570)

### Compiler

MSVC v17.7.5

### Steps to reproduce the behavior

(% git log | head -1 : 
commit fe1e9f508ee13ed3d0a7d318beac7efe1ec4f9d7 (HEAD -> master, origin/master, origin/HEAD))
```Shell
vcpkg install qtwebengine[geolocation,spellchecker,webchannel]  --triplet x64-windows  --x-buildtrees-root=d:/bt
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
    qtwebengine[core,default-features,geolocation,spellchecker,webchannel]:x64-windows -> 6.6.0
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from L:\Software\vcpkg_archives in 1.04 ms. Use --debug to see more details.
Installing 1/1 qtwebengine:x64-windows...
Building qtwebengine[core,default-features,geolocation,spellchecker,webchannel]:x64-windows...
-- Setting up python virtual environmnent...
-- Installing python packages: html5lib
-- Setting up python virtual environmnent...finished.
-- Using cached qtwebengine-everywhere-src-6.6.0.tar.xz.
-- Cleaning sources at D:/bt/qtwebengine/src/here-src-6-1e08092769.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Checkout_2020/vcpkg/downloads/qtwebengine-everywhere-src-6.6.0.tar.xz
-- Using source at D:/bt/qtwebengine/src/here-src-6-1e08092769.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: D:/Checkout_2020/vcpkg/downloads/tools/cmake-3.27.1-windows/cmake-3.27.1-windows-i386/bin/cmake.exe D:/bt/qtwebengine/src/here-src-6-1e08092769.clean -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=D:/Checkout_2020/vcpkg/packages/qtwebengine_x64-windows/debug -DFETCHCONTENT_FULLY_DISCONNECTED=ON -DQT_USE_DEFAULT_CMAKE_OPTIMIZATION_FLAGS:BOOL=ON -DCMAKE_FIND_PACKAGE_TARGETS_GLOBAL=ON -DQT_BUILD_EXAMPLES:BOOL=OFF -DQT_BUILD_TESTS:BOOL=OFF -DQT_BUILD_BENCHMARKS:BOOL=OFF -DHOST_PERL:PATH=D:/Checkout_2020/vcpkg/downloads/tools/perl/5.38.0.1/perl/bin/perl.exe -DINSTALL_BINDIR:STRING=bin -DINSTALL_LIBEXECDIR:STRING=bin -DINSTALL_PLUGINSDIR:STRING=Qt6/plugins -DINSTALL_QMLDIR:STRING=Qt6/qml -DFEATURE_webengine_proprietary_codecs=OFF -DFEATURE_webengine_spellchecker=ON -DFEATURE_webengine_geolocation=ON -DFEATURE_webengine_webchannel=ON -DCMAKE_REQUIRE_FIND_PACKAGE_Qt6Positioning=ON -DCMAKE_REQUIRE_FIND_PACKAGE_Qt6WebChannel=ON -DCMAKE_DISABLE_FIND_PACKAGE_Qt6Positioning=OFF -DCMAKE_DISABLE_FIND_PACKAGE_Qt6WebChannel=OFF -DFEATURE_webengine_webrtc_pipewire=OFF -DFEATURE_webengine_webrtc=ON -DFEATURE_webengine_v8_snapshot_support=ON -DGPerf_EXECUTABLE=D:/Checkout_2020/vcpkg/installed/x64-windows/tools/gperf/gperf.exe -DBISON_EXECUTABLE=D:/Checkout_2020/vcpkg/downloads/tools/win_flex/2.5.25/win_bison.exe -DFLEX_EXECUTABLE=D:/Checkout_2020/vcpkg/downloads/tools/win_flex/2.5.25/win_flex.exe -DNodejs_EXECUTABLE=D:/Checkout_2020/vcpkg/installed/x64-windows/tools/node/node.exe -DPython3_EXECUTABLE=D:/bt/qtwebengine/x64-windows-venv/Scripts/python.exe -DQT_FEATURE_webengine_jumbo_build=0 -DQT_SYNCQT:PATH=D:/Checkout_2020/vcpkg/installed/x64-windows/tools/Qt6/bin/syncqt.pl -DQT_NO_FORCE_SET_CMAKE_BUILD_TYPE:BOOL=ON -DQT_MKSPECS_DIR:PATH=D:/Checkout_2020/vcpkg/installed/x64-windows/share/Qt6/mkspecs "-DCMAKE_MAKE_PROGRAM=C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -DBUILD_SHARED_LIBS=ON -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/Checkout_2020/vcpkg/scripts/toolchains/windows.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=v143 -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=D:/Checkout_2020/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=D:/Checkout_2020/vcpkg -D_VCPKG_INSTALLED_DIR=D:/Checkout_2020/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -DINSTALL_DOCDIR:STRING=../doc/Qt6/ -DINSTALL_INCLUDEDIR:STRING=../include/Qt6/ -DINSTALL_TRANSLATIONSDIR:STRING=../translations/Qt6/ -DINSTALL_DESCRIPTIONSDIR:STRING=../share/Qt6/modules -DINSTALL_MKSPECSDIR:STRING=../share/Qt6/mkspecs
    Working Directory: D:/bt/qtwebengine/x64-windows-dbg
    Error code: 1
    See logs for more information:
      D:\bt\qtwebengine\config-x64-windows-dbg-CMakeCache.txt.log
      D:\bt\qtwebengine\config-x64-windows-dbg-out.log
      D:\bt\qtwebengine\config-x64-windows-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:267 (vcpkg_execute_required_process)
  installed/x64-windows/share/qtbase/qt_install_submodule.cmake:147 (vcpkg_cmake_configure)
  ports/qtwebengine/portfile.cmake:101 (qt_cmake_configure)
  scripts/ports.cmake:168 (include)

error: building qtwebengine:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qtwebengine
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[qtwebengine]+Build+error&body=Copy+issue+body+from+D%3A%2FCheckout_2020%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

The build log states to build QtWebEngineQuick, which required qtwebchannel[qml]  but is not an automatic dependency

### Additional context

installing qtwebchannel[qml] seems to be a pre-requisite to qtwebengine build.

Btw  i do not need the quick nor QML version in my code... so i wonder how/if this could be removed as a "default" dependency ?

**Comment by FrankXie05** [comment]
@WiestDaessle  Thanks for posting this issue, please provide the error logs:
```
D:\bt\qtwebengine\config-x64-windows-dbg-CMakeCache.txt.log
D:\bt\qtwebengine\config-x64-windows-dbg-out.log
D:\bt\qtwebengine\config-x64-windows-dbg-err.log
```
And 
>Btw i do not need the quick nor QML version in my code... so i wonder how/if this could be removed as a "default" dependency ?

You can just install the core, like: `./vcpkg install qtwebchannel[core] --triplet x64-windows

**Comment by WiestDaessle** [comment]
since i fixed the build issue by installing the qtwebchannel[qml] i do not have access anymore to the log files, as far as i recall it was searching of qtwebchannelquick.
