### ISSUE TITLE
[at-spi2-core] Build error on Rocky 8

### ISSUE THREAD

**Issue by davesworking** [microsoft/vcpkg#35001]
-- at-spi2-core currently requires the following libraries from the system package manager:
    libdbus-1-dev
    libxi-dev
    libxtst-dev

I have the following installed but still get the same error:
dbus-devel-1
libXi-devel
libXtst-devel

Please advise.

**Comment by Cheney-W** [comment]
What Linux distribution are you using? What version of vcpkg are you using? Could you please provide the commands you executed and the error messages you encountered?

**Comment by davesworking** [comment]
Rocky Linux release 8.6 (Green Obsidian)
Linux, version 4.18.0-372.26.1.el8_6.x86_64

The failure comes installing OpenCV via vcpkg. vcpkg is SHA 1c00eae503c78c308f1d1a412d5530eea5d18a31 from 2 weeks ago.

vcpkg install opencv[core,default-features,cuda,cudnn,ipp,openmp,tbb] --triplet=x64-linux --x-install-root=/builddir/installdir/Linux-x86-64

Building at-spi2-core:x64-linux...
-- at-spi2-core currently requires the following libraries from the system package manager:
    libdbus-1-dev
    libxi-dev
    libxtst-dev

These can be installed on Ubuntu systems via apt-get install libdbus-1-dev libxi-dev libxtst-dev
-- Downloading https://gitlab.gnome.org/GNOME/at-spi2-core/-/archive/AT_SPI2_CORE_2_44_1/at-spi2-core-AT_SPI2_CORE_2_44_1.tar.gz -> GNOME-at-spi2-core-AT_SPI2_CORE_2_44_1.tar.gz...
-- Extracting source /source/Linux-x86-64/nocona-glibc2.28/vcpkg/downloads/GNOME-at-spi2-core-AT_SPI2_CORE_2_44_1.tar.gz
-- Using source at /source/Linux-x86-64/nocona-glibc2.28/vcpkg/buildtrees/at-spi2-core/src/ORE_2_44_1-fa40e2a5ad.clean
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Configuring x64-linux-dbg
-- Configuring x64-linux-dbg done
-- Configuring x64-linux-rel
-- Configuring x64-linux-rel done
-- Package x64-linux-dbg

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /Build/Linux-x86-64/nocona-glibc2.28/vcpkg/downloads/tools/ninja/1.10.2-linux/ninja install -v
    Working Directory: /Build/Linux-x86-64/nocona-glibc2.28/vcpkg/buildtrees/at-spi2-core/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /Build/Linux-x86-64/nocona-glibc2.28/vcpkg/buildtrees/at-spi2-core/package-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
  ports/at-spi2-core/portfile.cmake:22 (vcpkg_install_meson)
  scripts/ports.cmake:168 (include)


error: building at-spi2-core:x64-linux failed with: BUILD_FAILED
Elapsed time to handle at-spi2-core:x64-linux: 8.7 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+at-spi2-core
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[at-spi2-core]+Build+error&body=Copy+issue+body+from+%2FDeveloper%2Fteamcity%2Fwork%2Fe7a9578bd49a8fa6%2FComponents%2FLibrary%2FVersion%2FLinux-x86-64%2Fvcpkg%2Fissue_body.md

vcpkg returned:  256

**Comment by dg0yt** [comment]
> See logs for more information:
> /Build/Linux-x86-64/nocona-glibc2.28/vcpkg/buildtrees/at-spi2-core/package-x64-linux-dbg-out.log

**Comment by davesworking** [comment]
[package-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/13452201/package-x64-linux-dbg-out.log)

I have tried installing these, via vcpkg, ahead of OpenCV:
dbus
libxi
libxtst

This does not help. Still get the same error.

**Comment by dg0yt** [comment]
You need to install system package at least for the X libs. Development packages, not just runtime. I think this is was also printed when you installed thos vpckg packages - that's all they do.

**Comment by dg0yt** [comment]
FTR the current problem is Xtst lib, and for some reason it is handle different from the others:
~~~
... /usr/lib64/libX11.so -L/usr/lib -lXtst /lib/../lib64/libXi.so ...
~~~
Bonus question: Does `libXtst.so` exist in `/lib64`?

**Comment by davesworking** [comment]
Since I don't have sudo access to the build machines, I use yumdownloader to get the devel packages:

`yumdownloader --resolve dbus-glib-devel libXi-devel libXtst-devel gtk3-devel`

This is where libXtest is located:

```
[]$ locate libXtst.so
/Build/Linux/glibc2.28/yum/usr/lib/libXtst.so
/Build/Linux/glibc2.28/yum/usr/lib/libXtst.so.6
/Build/Linux/glibc2.28/yum/usr/lib/libXtst.so.6.1.0
/Build/Linux/glibc2.28/yum/usr/lib64/libXtst.so
/usr/lib64/libXtst.so.6
/usr/lib64/libXtst.so.6.1.0
```
