### ISSUE TITLE
[vcpkg-tool] build failure

### ISSUE THREAD

**Issue by StarGate-One** [microsoft/vcpkg#35014]
### Operating system

Windows 11 10.0.22621.2506 x64 Enterprise

### Compiler

Visual Studio Community 2022 Version: [17.7.6]  VS Tools Version: [14.36.32532]  Microsoft (R) C/C++ Optimizing Compiler Version [19.36.32542] for x64   

### Steps to reproduce the behavior

```Shell
Local Build of vcpkg-tool fails after latest (20231109) commit [dfb60db5b9453d221dd585b8387c551b26c27dc7](https://github.com/microsoft/vcpkg-tool/commit/dfb60db5b9453d221dd585b8387c551b26c27dc7)
1. Sources built with CMake using almost the same parameters used by `<vcpkg-tool-root>/azure-pipelines/signing.yml` for amd64.
2. Run compile using CMake - fails with errors listed below.
3. Open vcpkg.sln in VS 2022 and compile - fails with same errors listed below.

Also I deleted my local copy of the vcpkg-tool repo and make a fresh cloned copy - same results.

Attached `vcpkg-tool-build.log` is complete vcpkg-tool build output, but only errors listed below.
```

### Failure logs

Build FAILED.

       "D:\Work\vcpkg\build\vcpkg.vcxproj" (default target) (1) ->
       "D:\Work\vcpkg\build\vcpkglib.vcxproj" (default target) (3) ->
       (ClCompile target) ->
         D:\vcpkg-tool\src\vcpkg\configure-environment.cpp(108,80): error C2146: syntax error: missing ';' before identifier 'V
       CPKG_BASE_VERSION_AS_STRING' [D:\Work\vcpkg\build\vcpkglib.vcxproj]
         D:\vcpkg-tool\src\vcpkg\configure-environment.cpp(108,80): error C2065: 'VCPKG_BASE_VERSION_AS_STRING': undeclared ide
       ntifier [D:\Work\vcpkg\build\vcpkglib.vcxproj]
         D:\vcpkg-tool\src\vcpkg\configure-environment.cpp(108,109): error C2143: syntax error: missing ';' before 'string' [D:
       \Work\vcpkg\build\vcpkglib.vcxproj]
         D:\vcpkg-tool\src\vcpkg\configure-environment.cpp(109,74): error C2065: 'VCPKG_BASE_VERSION_AS_STRING': undeclared ide
       ntifier [D:\Work\vcpkg\build\vcpkglib.vcxproj]
         D:\vcpkg-tool\src\vcpkg\configure-environment.cpp(109,14): error C2665: 'vcpkg::msg::println': no overloaded function
       could convert all the argument types [D:\Work\vcpkg\build\vcpkglib.vcxproj]
         D:\vcpkg-tool\src\vcpkg\configure-environment.cpp(111,74): error C2146: syntax error: missing ';' before identifier 'V
       CPKG_BASE_VERSION_AS_STRING' [D:\Work\vcpkg\build\vcpkglib.vcxproj]
         D:\vcpkg-tool\src\vcpkg\configure-environment.cpp(111,74): error C2065: 'VCPKG_BASE_VERSION_AS_STRING': undeclared ide
       ntifier [D:\Work\vcpkg\build\vcpkglib.vcxproj]
         D:\vcpkg-tool\src\vcpkg\configure-environment.cpp(112,13): error C2143: syntax error: missing ';' before 'string' [D:\
       Work\vcpkg\build\vcpkglib.vcxproj]
         D:\vcpkg-tool\src\vcpkg\configure-environment.cpp(114,65): error C2065: 'dfb60db5b9453d221dd585b8387c551b26c27dc7': un
       declared identifier [D:\Work\vcpkg\build\vcpkglib.vcxproj]
         D:\vcpkg-tool\src\vcpkg\configure-environment.cpp(114,49): error C3861: 'MACRO_TO_STRING': identifier not found [D:\Wo
       rk\vcpkg\build\vcpkglib.vcxproj]
         D:\vcpkg-tool\src\vcpkg\configure-environment.cpp(147,87): error C2065: 'VCPKG_BASE_VERSION_AS_STRING': undeclared ide
       ntifier [D:\Work\vcpkg\build\vcpkglib.vcxproj]
         D:\vcpkg-tool\src\vcpkg\configure-environment.cpp(164,65): error C2065: 'VCPKG_BASE_VERSION_AS_STRING': undeclared ide
       ntifier [D:\Work\vcpkg\build\vcpkglib.vcxproj]

    0 Warning(s)
    12 Error(s)
[vcpkg-tool-build.log](https://github.com/microsoft/vcpkg/files/13315420/vcpkg-tool-build.log)

### Additional context

/cc @BillyONeal - this is vcpkg-tool repo with latest commit as of 20231109.

If you need other info let me know... 
It could be there is something I need to change in my build script, but vcpkg tool has got really complicated beyond my level of C/C++, so any help would be greatly appreciated.

**Comment by StarGate-One** [comment]
Ok - I was able to fix temporality by adding back the 2 includes that were deleted in `D:\vcpkg-tool\src\vcpkg\configure-environment.cpp`
$ git diff
diff --git a/src/vcpkg/configure-environment.cpp b/src/vcpkg/configure-environment.cpp
index 579a437a..9814a356 100644
--- a/src/vcpkg/configure-environment.cpp
+++ b/src/vcpkg/configure-environment.cpp
@@ -6,11 +6,13 @@
 #include <vcpkg/base/json.h>
 #include <vcpkg/base/setup-messages.h>
 #include <vcpkg/base/system.debug.h>
+#include <vcpkg/base/system.h>
 #include <vcpkg/base/system.process.h>
 #include <vcpkg/base/util.h>
 #include <vcpkg/base/uuid.h>

 #include <vcpkg/archives.h>
+#include <vcpkg/commands.version.h>
 #include <vcpkg/configure-environment.h>
 #include <vcpkg/metrics.h>
 #include <vcpkg/tools.h>

**Comment by Adela0814** [comment]
@BillyONeal Please take a look, thanks.

**Comment by StarGate-One** [comment]
I have done some more testing:
I can remove this line `#include <vcpkg/base/system.h>`, but I must keep line `include <vcpkg/commands.version.h>` before it compiles. 

It may be because line 21 of  [<vcpkg-tool>/include/vcpkg/commands.version.h](https://github.com/microsoft/vcpkg-tool/blob/dfb60db5b9453d221dd585b8387c551b26c27dc7/include/vcpkg/commands.version.h#L21) is the only place the variable `VCPKG_BASE_VERSION_AS_STRING` is defined?

I hope this information helps out and thanks again for all the hard work you all put in to make the vcpkg work!!!

**Comment by StarGate-One** [comment]
Fixed by [vcpkg-tool 1278](https://github.com/microsoft/vcpkg-tool/pull/1278) by @BillyONeal .
Thanks.
