### ISSUE TITLE
Cannot build botan on any platform.

### ISSUE THREAD

**Issue by qis** [microsoft/vcpkg#3502]
Botan fails to build on Windows `VCPKG_CRT_LINKAGE dynamic` and `VCPKG_LIBRARY_LINKAGE static` with the following error:

```
Expected Debug,Dynamic crt linkage, but the following libs had invalid crt linkage:

    C:/Libraries/vcpkg/packages/botan_x64-windows-static-md/debug/lib/botand.lib: Debug,Static

To inspect the lib files, use:
    dumpbin.exe /directives mylibfile.lib
Expected Release,Dynamic crt linkage, but the following libs had invalid crt linkage:

    C:/Libraries/vcpkg/packages/botan_x64-windows-static-md/lib/botan.lib: Release,Static

To inspect the lib files, use:
    dumpbin.exe /directives mylibfile.lib
Found 2 error(s). Please correct the portfile:
    C:\Libraries\vcpkg\ports\botan\portfile.cmake
-- Performing post-build validation done
Error: Building package botan:x64-windows-static-md failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: botan:x64-windows-static-md
  Vcpkg version: 0.0.111-2018-05-11-29d04b8b4005f5e2bfe61ccdc7a93d5c6c8a13d9
```

Botan fails to build on Linux (WSL) and FreeBSD 12.0 CURRENT with the following error:

```
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:214 (message):
  Could not find jom.  Please install it via your package manager.
Call Stack (most recent call first):
  ports/botan/portfile.cmake:17 (vcpkg_find_acquire_program)
  scripts/ports.cmake:72 (include)


Error: Building package botan:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: botan:x64-linux
  Vcpkg version: 0.0.111-unknownhash-debug
```

Not sure why `jom` is required in the first place. There is no standalone package or port for it that I'm aware of.

**Comment by dana321** [comment]
Its broken, thats for sure.  jom is a multithreaded version of nmake which is a windows-only command for building projects.

Here is my terrible CMakeLists.txt file which works with botan for windows:

`
cmake_minimum_required (VERSION 3.5)

set(VCPKG_ROOT "D:/VCPKG")

project(BotanTest VERSION 1.0 LANGUAGES CXX)

if(NOT MSVC)
	add_compile_options(-Wpedantic -Wall -Wextra -Wsign-conversion -O1)
else()
	add_compile_options(/W1)
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /bigobj")
	set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} /MTd")
	set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /MT")
endif()

set(ADD_DEBUG "")

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
	set(ADD_DEBUG "Debug/")
endif()

add_executable (main main.cpp main.h)
include_directories("${VCPKG_ROOT}/installed/x64-windows-static/include")

target_link_libraries(main PRIVATE "${VCPKG_ROOT}/installed/x64-windows-static/${ADD_DEBUG}lib/botan.lib")
`

**Comment by dana321** [comment]
Just had a proper read through the ports/botan/portfile.cmake file and its definitely a windows-only build.

**Comment by NancyLi1013** [comment]
Hi @qis and @dana321, thanks for posing this issue. Botan has been upgraded. Does this issue still exist on your machines now? Could you please update the port to the latest version and try it again?

**Comment by AlvinZhangH** [comment]
Please reopen this issue if it still bothers you.
thanks.
