### ISSUE TITLE
[ceres] Build error

### ISSUE THREAD

**Issue by Ari-hant** [microsoft/vcpkg#35023]
[Copy issue body from C:/Users/Arihant/Desktop/Easiofy/vcpkg/installed/vcpkg/issue_body.md](https://github.com/microsoft/vcpkg/issues/new?title=[ceres]+Build+error&body=Copy+issue+body+from+C%3A%2FUsers%2FArihant%2FDesktop%2FEasiofy%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md)

**Comment by StarGate-One** [comment]
See "How to report a package build failure [explanation video] #30604".

**Comment by jimwang118** [comment]
See "How to report a package build failure [explanation video] https://github.com/microsoft/vcpkg/issues/30604". Resubmit issue.
