### ISSUE TITLE
[v8] Build error

### ISSUE THREAD

**Issue by liulilittle** [microsoft/vcpkg#35049]
Copy issue body from D:/dd/vcpkg/installed/vcpkg/issue_body.md

WinOS: Windows 11 x64
Build Tools: VS2022、VS2019
VCPKG-cli: ./vcpkg install v8:x86-windows-static --debug

Builld V8-Error-log.
########################
D:\dd\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\vs_toolchain.py:12: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  import pipes
D:\dd\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\vs_toolchain.py:12: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  import pipes
Traceback (most recent call last):
  File "D:\dd\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\vs_toolchain.py", line 573, in <module>
    sys.exit(main())
             ^^^^^^
  File "D:\dd\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\vs_toolchain.py", line 569, in main
    return commands[sys.argv[1]](*sys.argv[2:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dd\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\vs_toolchain.py", line 397, in CopyDlls
    _CopyRuntime(target_dir, runtime_dir, target_cpu, debug=False)
  File "D:\dd\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\vs_toolchain.py", line 372, in _CopyRuntime
    _CopyUCRTRuntime(target_dir, source_dir, target_cpu, suffix)
  File "D:\dd\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\vs_toolchain.py", line 313, in _CopyUCRTRuntime
    assert len(ucrt_files) > 0
           ^^^^^^^^^^^^^^^^^^^
AssertionError

#############################################
Not found according to the log: C:\Program Files (x86)\Windows Kits\10\Redist\10.0.19041.0\ucrt\DLLs\x86 directory api-ms-* dll file so asserted, in fact, I have this directory inside dll.

<img width="846" alt="2023-11-12 (1)" src="https://github.com/microsoft/vcpkg/assets/19451711/83a3e5ef-e766-4ea6-898a-33b2e90732b6">

So, how do I solve the problem of V8 not compiling, I have tried to compile the static version of x64, x86, dynamic DLL library is not working, and I have tried to manually modify the vs_toolchain.py file to cancel this assertion, so that the compilation can continue, However, once I continue to compile with vcpkg, the modified py script will be deleted and forcibly overwritten with the original script, which is difficult to deal with.

**Comment by dg0yt** [comment]
> However, once I continue to compile with vcpkg, the modified py script will be deleted and forcibly overwritten with the original script, which is difficult to deal with.

Build with `--editable` for work in progress, or  add a proper patch to the port for reproducible results.

**Comment by dg0yt** [comment]
`v8` is skipped in vcpkg CI for all windows triplets:
~~~
v8:x64-windows-static-md=fail
v8:x64-windows-static=fail
v8:x64-windows=fail
v8:x86-windows=fail
~~~
From my POV: expect it to be unusable.

**Comment by liulilittle** [comment]
thanks...

I just checked the vcpkg/ports directory for v8 configuration, and it does not support Windows platform compilation.
#########################
DD：vcpkg.json
#########################
{
  "name": "v8",
  "version": "9.1.269.39",
  "port-version": 6,
  "description": "Google Chrome's JavaScript engine",
  "homepage": "https://v8.dev",
  "license": "BSD-3-Clause",
  "supports": "!(arm | arm64 | uwp | osx | linux)",
  "dependencies": [
    {
      "name": "glib",
      "platform": "linux"
    },
    "icu",
    {
      "name": "pthread",
      "platform": "linux"
    },
    {
      "name": "vcpkg-gn",
      "host": true
    },
    {
      "name": "vcpkg-tool-python2",
      "host": true
    },
    "zlib"
  ]
}
