### ISSUE TITLE
[v8] Build error

### ISSUE THREAD

**Issue by liulilittle** [microsoft/vcpkg#35048]
The vcpkg compilation of the Google V8 JavaScript engine failed with the triplet set as "v8:x86-windows-static".
Is there something missing in my environment settings that prevents me from compiling it correctly using vcpkg on my computer?

###########################################################
Copy issue body from D:/dd/vcpkg/installed/vcpkg/issue_body.md
###########################################################

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: D:/dd/vcpkg/installed/x64-windows/tools/gn/gn.exe gen D:/dd/vcpkg/buildtrees/v8/x86-windows-static-dbg "--args=is_component_build=false target_cpu=\"x86\" v8_monolithic=true v8_use_external_startup_data=false use_sysroot=false is_clang=false use_custom_libcxx=false v8_enable_verify_heap=false icu_use_data_file=false is_debug=true enable_iterator_debugging=true pkg_config_libdir=\"/d/dd/vcpkg/installed/x86-windows-static/debug/lib/pkgconfig\""
    Working Directory: D:/dd/vcpkg/buildtrees/v8/src/a883683717-d6c82ef7bb.clean
    Error code: 1
    See logs for more information:
      D:\dd\vcpkg\buildtrees\v8\generate-x86-windows-static-dbg-out.log
      D:\dd\vcpkg\buildtrees\v8\generate-x86-windows-static-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-gn/vcpkg_gn_configure.cmake:11 (vcpkg_execute_required_process)
  installed/x64-windows/share/vcpkg-gn/vcpkg_gn_configure.cmake:35 (z_vcpkg_gn_configure_generate)
  ports/v8/portfile.cmake:150 (vcpkg_gn_configure)
  scripts/ports.cmake:168 (include)

error: building v8:x86-windows-static failed with: BUILD_FAILED
Elapsed time to handle v8:x86-windows-static: 27 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+v8
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[v8]+Build+error&body=Copy+issue+body+from+D%3A%2Fdd%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by faqeerhussain106** [comment]
My payment my account jaazcash.03078859040)send me Pakistan

**Comment by faqeerhussain106** [comment]
Pauneer account in jaazcash03078859040
