### ISSUE TITLE
[zeromq] Build failure

### ISSUE THREAD

**Issue by meclondrej** [microsoft/vcpkg#35059]
Package: zeromq:x64-mingw-static -> 2023-06-20#1

**Host Environment**

- Host: x64-windows
- Compiler: GNU 6.3.0
-    vcpkg-tool version: 2023-10-18-27de5b69dac4b6fe8259d283cd4011e6d20a84ce
    vcpkg-scripts version: 61f610845 2023-11-10 (2 days ago)

**To Reproduce**

`vcpkg install zeromq`
**Failure logs**

```
-- Using cached zeromq-libzmq-ecc63d0d3b0e1a62c90b58b1ccdb5ac16cb2400a.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/zeromq/src/c16cb2400a-3885a99186.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/zeromq-libzmq-ecc63d0d3b0e1a62c90b58b1ccdb5ac16cb2400a.tar.gz
-- Applying patch fix-arm.patch
-- Using source at C:/vcpkg/buildtrees/zeromq/src/c16cb2400a-3885a99186.clean
-- Configuring x64-mingw-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe -v
    Working Directory: C:/vcpkg/buildtrees/zeromq/x64-mingw-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\zeromq\config-x64-mingw-static-dbg-CMakeCache.txt.log
      C:\vcpkg\buildtrees\zeromq\config-x64-mingw-static-rel-CMakeCache.txt.log
      C:\vcpkg\buildtrees\zeromq\config-x64-mingw-static-out.log

Call Stack (most recent call first):
  installed/x64-mingw-static/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:252 (vcpkg_execute_required_process)
  ports/zeromq/portfile.cmake:28 (vcpkg_cmake_configure)
  scripts/ports.cmake:168 (include)



```
details at https://pastebin.com/qA9LScTz

**Comment by meclondrej** [comment]
I have VS2022 installed, not using it though, if it helps.

**Comment by MonicaLiu0311** [comment]
The code where the error occurred is as follows:
[ip_resolver.cpp#L637-L640](https://github.com/zeromq/libzmq/blob/master/src/ip_resolver.cpp#L637-L640): 
```
          GetAdaptersAddresses (AF_UNSPEC,
                                GAA_FLAG_SKIP_ANYCAST | GAA_FLAG_SKIP_MULTICAST
                                  | GAA_FLAG_SKIP_DNS_SERVER,
                                NULL, addresses, &out_buf_len);
```
[CMakeLists.txt#L559](https://github.com/zeromq/libzmq/blob/master/CMakeLists.txt#L559):
```
  check_cxx_symbol_exists(GetAdaptersAddresses "winsock2.h;iphlpapi.h" HAVE_IPHLAPI)
```
[CMakeLists.txt#L590-L592](https://github.com/zeromq/libzmq/blob/master/CMakeLists.txt#L590-L592):
```
  if(NOT HAVE_IPHLAPI)
    message(FATAL_ERROR "Cannot link to iphlapi")
  endif()
```

Could you please turn off your local anti-virus software and try again?
https://github.com/microsoft/vcpkg/issues/18582#issuecomment-866104333

**Comment by dg0yt** [comment]
> * Compiler: GNU 6.3.0

This indicates an outdated mingw toolchain.

**Comment by meclondrej** [comment]
@MonicaLiu0311
no local antivirus present,
switching windows defender realtime virus protection off does not change anything

@dg0yt
i will try updating mingw

**Comment by MonicaLiu0311** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
