### ISSUE TITLE
Build issue on ARM processor 

### ISSUE THREAD

**Issue by Aswin-coder** [microsoft/vcpkg#35066]
**Describe the bug**
I have built the vcpkg in ARM processor but when u try to install any package it is showing as **Environment variable VCPKG_FORCE_SYSTEM_BINARIES must be set on arm and s390x platforms.**

**Environment**
- OS: Linux ubuntu

**To Reproduce**
1. ./vcpkg install 

I tried to export the variable but still it is showing

**Comment by MonicaLiu0311** [comment]
Please try https://github.com/microsoft/vcpkg/issues/14140#issuecomment-713276010:
```
export VCPKG_FORCE_SYSTEM_BINARIES=1
./vcpkg install portName
```

**Comment by Aswin-coder** [comment]
> Please try [#14140 (comment)](https://github.com/microsoft/vcpkg/issues/14140#issuecomment-713276010):
> 
> ```
> export VCPKG_FORCE_SYSTEM_BINARIES=1
> ./vcpkg install portName
> ```

I tried but still is is not installing

**Comment by MonicaLiu0311** [comment]
Are there any query results using echo `%VCPKG_FORCE_SYSTEM_BINARIES%`?

**Comment by Aswin-coder** [comment]
> Are there any query results using `echo %VCPKG_FORCE_SYSTEM_BINARIES%`?

it has only 1 stored in the env var

**Comment by MonicaLiu0311** [comment]
Can you attach the log of the output console, for example: https://github.com/microsoft/vcpkg/issues/16040#issuecomment-781179718

**Comment by Aswin-coder** [comment]
> Can you attach the log of the output console, for example: [#16040 (comment)](https://github.com/microsoft/vcpkg/issues/16040#issuecomment-781179718)

ubuntu@dev_tx1b:/nfs_mount/flashlight$ sudo ./vcpkg/vcpkg install
[sudo] password for ubuntu:
Environment variable VCPKG_FORCE_SYSTEM_BINARIES must be set on arm, s390x, ppc64le and riscv platforms.
ubuntu@dev_tx1b:/nfs_mount/flashlight$ export VCPKG_FORCE_SYSTEM_BINARIES=1
ubuntu@dev_tx1b:/nfs_mount/flashlight$ echo $VCPKG_FORCE_SYSTEM_BINARIES
1
ubuntu@dev_tx1b:/nfs_mount/flashlight$ sudo ./vcpkg/vcpkg install
Environment variable VCPKG_FORCE_SYSTEM_BINARIES must be set on arm, s390x, ppc64le and riscv platforms.
ubuntu@dev_tx1b:/nfs_mount/flashlight$

**Comment by MonicaLiu0311** [comment]
Try this: `sudo export VCPKG_FORCE_SYSTEM_BINARIES=1`

**Comment by dg0yt** [comment]
> Try this: `sudo export VCPKG_FORCE_SYSTEM_BINARIES=1`

No.

**Comment by dg0yt** [comment]
> sudo ./vcpkg/vcpkg install

Please don't use sudo to run vcpkg.

**Comment by Aswin-coder** [comment]
thanks, its working
