### ISSUE TITLE
zlib / zlib1 binary and symbol filename mismatch - causes CI pipeline failures

### ISSUE THREAD

**Issue by asklar** [microsoft/vcpkg#35061]
**Describe the bug**
When using the **minizip** port, it brings in these 2 files among others:
- zlib1.dll
- zlib.pdb

Note the missing "1" in the pdb file. The two files differ in name, so tooling that expects a binary and its PDB file to have the same name, fails to find a match. This happens with e.g. binary security analysis running in microsoft (SDL analysis)

**Environment**
- OS: Windows
- Compiler: msvc

Microsoft people: please ping me on Teams for a link to the pipeline that fails because of this mismatch.

**Comment by dg0yt** [comment]
> When using the **minizip** port, it brings in these 2 files among others:
> 
> * zlib1.dll
> * zlib.pdb

FTR these artifacts are from port `zlib`, not `minizip`:
~~~
zlib:x64-windows:/bin/zlib.pdb
zlib:x64-windows:/bin/zlib1.dll
zlib:x64-windows:/debug/bin/zlibd.pdb
zlib:x64-windows:/debug/bin/zlibd1.dll
~~~

And the names are chosen by upstream.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
