### ISSUE TITLE
[qtbase] qt.conf.in should set Binaries to tools/Qt6/bin

### ISSUE THREAD

**Issue by RealLitb** [microsoft/vcpkg#35089]
**Describe the bug**
The qt.conf.in file specifies that binaries of Qt are in bin/.  But they actually are  in tools/Qt6/bin. This leads to failures in QtCreator. When I fixed the value of "Binaries=" to be the same as "LibraryExecutables", it worked fine. 

**To Reproduce**

QtCreator fails because it looks for binaries (namely the "qmlplugindump" tool) that upstream Qt puts into bin/ in the "Binaries" setting, which specifies bin/. But VCPKG puts all binaries into tools/Qt6/bin, despite declaring they are in bin/.

**Comment by JonLiu1993** [comment]
I checked locally and noticed the problem you mentioned. I will go to the upstream code to investigate the cause.

**Comment by JonLiu1993** [comment]
@Neumann-A, Could you please take a look? thanks.

**Comment by Neumann-A** [comment]
I don't mind this. The only reason I left it with bin is because I do not know if it influences dll lookup by Qt in some way.

**Comment by vserdyuk** [comment]
> But they actually are in tools/Qt6/bin

No, tools/Qt6/bin only has binaries that are needed for running Qt tools, such as windeployqt, lupdate, lrelease, etc. It does not contain debug binaries. Attempt to fix it (https://github.com/microsoft/vcpkg/pull/35392) broke windeployqt on debug configurations: https://github.com/microsoft/vcpkg/issues/17840

**Comment by Neumann-A** [comment]
If the fix interacts with the deployment then it should probably be reverted. QtCreator should be able to differentiate between HostBinaries and normal Binaries.

**Comment by vserdyuk** [comment]
> If the fix interacts with the deployment then it should probably be reverted. QtCreator should be able to differentiate between HostBinaries and normal Binaries.

I think, the root cause is that upstream Qt (and QtCreator) expects tools mixed with binaries in the same folder (see `BinariesPath` description in [QLibraryInfo docs](https://doc.qt.io/qt-6/qlibraryinfo.html#LibraryPath-enum)) while vcpkg tries to keep them separate. In my case, `HostBinaries` is the same as `Binaries` (`debug/bin`) and both obviously do not contain tools. I don't think that we can fix it here, it should be supported by the upstream.

**Comment by dg0yt** [comment]
> [Documentation](https://doc.qt.io/qt-6/qlibraryinfo.html#LibraryPath-enum) is confusing: on Windows, `BinariesPath` actually contain dll's in addition to "tools and applications".

But it is vcpkg which is non-standard here: It doesn't allow tools in `/bin`. Moving tools around easily breaks a lot of assumptions.

It would be nice to have a test port to verify that the result of windeployqt is executable, in native triplets, for both build types.
