### ISSUE TITLE
Best practice

### ISSUE THREAD

**Issue by edmBernard** [microsoft/vcpkg#3509]
To differentiate Windows, Linux and OSX build in CMake. 
Do you prefer : 
* The regular CMake variable MSVC, UNIX etc ...
* The vcpk variable from triplet configuration : VCPKG_CMAKE_SYSTEM_NAME (Windows, Linux, Darwin)

Note: to use VCPKG_CMAKE_SYSTEM_NAME we need to inject it in `portfile.cmake`

**Comment by Cheney-W** [comment]
Currently, VCPKG_CMAKE_SYSTEM_NAME have 6 values:
``````
VCPKG_CMAKE_SYSTEM_NAME    TOOLCHAIN

NOT DEFINED                Windows
WindowsStore               Windows(UWP)
Linux                      Linux
Android                    Android
Darwin                     Osx
FreeBSD                    Freebsd
``````

**Comment by edmBernard** [comment]
@Cheney-W I asked this question because `VCPKG_CMAKE_SYSTEM_NAME` was accessible in portfile but not in CMakeLists. 
for example my port for libuv have to inject it in vcpkg_configure_cmake : https://github.com/microsoft/vcpkg/pull/3437/commits/a64f5186d369bdf3201d005215a95b3df8640bf4#diff-2518762e404a460b0163cf80475362afR20
currently most of port use CMake variable MSVC, UNIX

Note: btw, I don't know if it's still the case.
