### ISSUE TITLE
undefined reference to box2d

### ISSUE THREAD

**Issue by weltauseis** [microsoft/vcpkg#35090]
**Describe the bug**
I'm trying to build a box2d project using vcpkg, but the library is not linking.
Exact same issue as #22879 , but this issue was closed without getting resolved.
In the same project, I am using vcpkg-provided raylib and it does not produce any linking error.

**Environment**
- OS: Windows 11
- Compiler: w64devkit gcc
- Build tool : CMake

**To Reproduce**
1. `./vcpkg install box2d`
2. `./vcpkg install raylib`
3. `./vcpkg integrate install`
4. Create a `main.cpp` file :
```c++
#include <raylib.h>
#include <box2d/box2d.h>

int main()
{
    // window init
    InitWindow(1280, 720, "raylib window");
    SetTargetFPS(60);

    // box2d
    b2Vec2 gravity(0.0f, -10.0f);
    b2World world(gravity);

    while (!WindowShouldClose())
    {
        BeginDrawing();
        ClearBackground(BLACK);
        DrawFPS(0, 0);
        EndDrawing();
    }
    return 0;
}
```
6. Create a CMakeLists.txt for the project :
```CMake
cmake_minimum_required(VERSION 3.7)
project(myProject VERSION 1.0 DESCRIPTION "Very nice project" LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)

INCLUDE_DIRECTORIES(
    C:/Users/Kevin/Desktop/vcpkg/installed/x64-windows/include/
)
  
LINK_DIRECTORIES(
    C:/Users/Kevin/Desktop/vcpkg/installed/x64-windows/lib/
)

add_executable(main main.cpp)

find_package(box2d CONFIG REQUIRED)
target_link_libraries(main PRIVATE raylib box2d::box2d)
```
8. Build project in a `build/` folder with `cmake ..` then `make`

**Expected behavior**
The linking succeeds.

**Failure logs**
```
PS $ make
[ 50%] Linking CXX executable main.exe
C:\w64devkit\bin/ld.exe: CMakeFiles/main.dir/objects.a(main.cpp.obj): in function `main':
C:/Users/Kevin/Desktop/raylib/orenji_game/main.cpp:12: undefined reference to `b2World::b2World(b2Vec2 const&)'
C:\w64devkit\bin/ld.exe: C:/Users/Kevin/Desktop/raylib/orenji_game/main.cpp:22: undefined reference to `b2World::~b2World()'
C:\w64devkit\bin/ld.exe: C:/Users/Kevin/Desktop/raylib/orenji_game/main.cpp:22: undefined reference to `b2World::~b2World()'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/main.dir/build.make:101: main.exe] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/main.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

**Additional context**
The project without the box2d code compiles and works as expected, so raylib is definitely getting linked without problems.
Also, note that the box2d headers are found, so it is only the lib part that causes issues.

**Comment by MonicaLiu0311** [comment]
Please add `find_package(raylib CONFIG REQUIRED)` to CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.7)
project(myProject VERSION 1.0 DESCRIPTION "Very nice project" LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)

INCLUDE_DIRECTORIES(
    C:/Users/Kevin/Desktop/vcpkg/installed/x64-windows/include/
)
  
LINK_DIRECTORIES(
    C:/Users/Kevin/Desktop/vcpkg/installed/x64-windows/lib/
)

add_executable(main main.cpp)

find_package(box2d CONFIG REQUIRED)
find_package(raylib CONFIG REQUIRED)
target_link_libraries(main PRIVATE raylib box2d::box2d)
```

**Comment by weltauseis** [comment]
Does not change anything. Same error. Raylib is already linked properly.

**Comment by dg0yt** [comment]
Thanks for reporting the issue. It points to a problem with box2d, so any comments which don't refer to box2d are just bonus...

> ```cmake
> INCLUDE_DIRECTORIES(
>     C:/Users/Kevin/Desktop/vcpkg/installed/x64-windows/include/
> )
>   
> LINK_DIRECTORIES(
>     C:/Users/Kevin/Desktop/vcpkg/installed/x64-windows/lib/
> )
> ```

Remove these lines, and use proper vcpkg CMake integration. That is: Use the `scripts/buildsystems/vcpkg.cmake` CMake toolchain file. Note that this must be set in the first run of CMake in a fresh build directory.
https://learn.microsoft.com/en-us/vcpkg/users/buildsystems/cmake-integration

> ```cmake
> target_link_libraries(main PRIVATE raylib box2d::box2d)
> ```

Without a target provided by `find_package`, this reference to `raylib` is a just a string which is passed as to the linker. Normally this is not what you want - the actual libname spec might need to vary by platform or buildtype. A target would also carry details such as include directory and library location.

**Comment by dg0yt** [comment]
I cannot reproduce this problem when building with the vcpkg toolchain.

**Comment by weltauseis** [comment]
Hi ! Thanks for the explanation, I'm still a beginner when it comes to build systems.
I have removed the lines, and I'm pretty sure I'm now using the proper vcpkg CMake integration in vscode, as the parameters that the CMake extension command is using seems to indicate : 
```
[main] Configuring project: myProject 
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_TOOLCHAIN_FILE:STRING=C:/Users/Kevin/Desktop/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=C:\w64devkit\bin\gcc.exe -DCMAKE_CXX_COMPILER:FILEPATH=C:\w64devkit\bin\g++.exe -SC:/Users/Kevin/Desktop/raylib/myProject -Bc:/Users/Kevin/Desktop/raylib/myProject/build -G "Unix Makefiles"
[cmake] Not searching for unused variables given on the command line.
[cmake] -- The CXX compiler identification is GNU 13.2.0
[cmake] -- Detecting CXX compiler ABI info
[cmake] -- Detecting CXX compiler ABI info - done
[cmake] -- Check for working CXX compiler: C:/w64devkit/bin/g++.exe - skipped
[cmake] -- Detecting CXX compile features
[cmake] -- Detecting CXX compile features - done
[cmake] -- Found raylib: C:/Users/Kevin/Desktop/vcpkg/installed/x64-windows/debug/lib/raylib.lib  
[cmake] -- Configuring done (3.0s)
[cmake] -- Generating done (0.0s)
[cmake] -- Build files have been written to: C:/Users/Kevin/Desktop/raylib/myProject/build
```
However, when trying to build, I'm still getting the same error :
```
[main] Building folder: myProject all
[build] Starting build
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --build c:/Users/Kevin/Desktop/raylib/myProject/build --config Debug --target all -j 10 --
[build] [ 50%] Building CXX object CMakeFiles/main.dir/main.cpp.obj
[build] [100%] Linking CXX executable main.exe
[build] C:\w64devkit\bin/ld.exe: CMakeFiles/main.dir/objects.a(main.cpp.obj): in function `main':
[build] C:/Users/Kevin/Desktop/raylib/myProject/main.cpp:12: undefined reference to `b2World::b2World(b2Vec2 const&)'
[build] C:\w64devkit\bin/ld.exe: C:/Users/Kevin/Desktop/raylib/myProject/main.cpp:22: undefined reference to `b2World::~b2World()'
[build] C:\w64devkit\bin/ld.exe: C:/Users/Kevin/Desktop/raylib/myProject/main.cpp:22: undefined reference to `b2World::~b2World()'
[build] collect2.exe: error: ld returned 1 exit status
[build] make[2]: *** [CMakeFiles/main.dir/build.make:103: main.exe] Error 1
[build] make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/main.dir/all] Error 2
[build] make: *** [Makefile:91: all] Error 2
[proc] The command: "C:\Program Files\CMake\bin\cmake.EXE" --build c:/Users/Kevin/Desktop/raylib/myProject/build --config Debug --target all -j 10 -- exited with code: 2
[driver] Build completed: 00:00:00.875
[build] Build finished with exit code 2
```

One thing maybe worth noting is that there is a "Found Raylib" line, but no "Found Box2d" or similar. Also, I am using `gcc` from w64devkit as the compiler, could that be the source of any issue ?

**Comment by dg0yt** [comment]
> One thing maybe worth noting is that there is a "Found Raylib" line, but no "Found Box2d" or similar. 

CMake doesn't complain, neither on `find_package(... REQUIRED)` nor on `target_link_libraries(... box2d::box2d)`. So the package and the target exist for CMake.

> Also, I am using `g++` from w64devkit as the compiler, could that be the source of any issue ?

This could be the key issue. `x64-windows` is for the MSVC toolchain. `g++` is probably part of a mingw toolchain, needing different vcpkg triplets. Normally you don't mix them.

I tested on x64-linux. Maybe I should repeat it at least for mingw.

**Comment by weltauseis** [comment]
Hey ! You were right. I've since installed the Microsoft Visual Studio Build Tools, and after switching the compiler, box2d doesn't seem to cause any issue anymore.
