### ISSUE TITLE
[Bug][CI Image][osx] fatal error: 'wchar.h' file not found

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#35114]
**Describe the bug**
When compile on osx ci image with `#include <wchar.h>` it create an error that it don't find the header file:
```
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__mbstate_t.h:29:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/wchar.h:123:15: fatal error: 'wchar.h' file not found
#include_next <wchar.h>
```

**Environment**
- OS: CI Image osx
- Compiler: not sure.

**To Reproduce**
1. git clone https://github.com/talregev/vcpkg -b TalR/ogre-next-osx
2. ./vcpkg install ogre-next
3. See error
Repro code when

**Expected behavior**
It will install ogre-next without the error

**Failure logs**
https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/96324/artifacts?artifactName=failure%20logs%20for%20x64-osx&api-version=7.1&%24format=zip

**Additional context**
I succeeded to recrate the error on osx github action and try to search the solution there.
I also change the location to the new location by
`sudo xcode-select --switch  /Library/Developer/CommandLineTools/`
I also try to find the `wchar.h` file. by command: `sudo find / -name "wchar.h"`
On github action it locate on `/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/` and more.

Also I read these:
https://stackoverflow.com/questions/46342411/wchar-h-file-not-found
https://github.com/AcademySoftwareFoundation/OpenShadingLanguage/issues/1055

I know it need to config xcode that it will see this include, not sure how to do it.

I hop these hints will give you a good start on the investigation. 

You can also look at the PR #34945

[failure logs for x64-osx.zip](https://github.com/microsoft/vcpkg/files/13355460/failure.logs.for.x64-osx.zip)

**Comment by JonLiu1993** [comment]
@talregev, thanks for posting this issue,ogre-next depends on openvr, which does not support OSX. Did you encounter any errors when installing it?
````
openvr is only supported on '!(arm | uwp | osx | android)', which does not match x64-osx. This usually means that there are known build failures, or runtime problems, when building other platforms. To ignore this and attempt to build openvr anyway, rerun vcpkg with `--allow-unsupported`.

````

**Comment by talregev** [comment]
@JonLiu1993 openvr is not mandatory for ogre-next. Can install it without the openvr.
On my branch I separated the openvr from osx installation.
As you can see from your ci I get the mention error. You can see it from my PR here in vcpkg. Also download the zip file I published here that generated from your CI.
I am not osx user and I don't have osx to try it on my local. I tried it also on GitHub action osx and get the same error. I don't know how to config osx compiler to find the wchar.h header file.
This is an issue of bug report and not a question. As I specify how to recreate the bug and give you all the logs.
Please change it to bug report.

**Comment by dg0yt** [comment]
I still suspect that there is a bug in ogre-next.

**Comment by talregev** [comment]
> I still suspect that there is a bug in ogre-next.

Why you think it a bug in ogre-next.
As I see it, they do `#include <wchar.h>` in their project that is total ok.

**Comment by talregev** [comment]
> The answer is easy:
> vcpkg CI is new enough. And the only recent occurrence of this error is ogre-next.

This is not about upgrade osx nor xcode inside the ci image. It about to configure xcode that it will recognize the wchar header.

I suspected on CI image because first I am not osx user, and I looked at the Internet and found how to config xcode (That I try myself and failed in GitHub action osx ci).
If you can say that it cmake configuration that also a possibility and I hope you will find the problem.

**Comment by dg0yt** [comment]
> it about to configure xcode that it will recognize the wchar header.

And this is sysroot.

**Comment by dg0yt** [comment]
From a quick search, it is this line:
https://github.com/OGRECave/ogre-next/blob/bb07baeb2994d37f994df90b469be9b9a8d6e5bf/CMakeLists.txt#L388

It overrides the toolchain setting (initialized during the `project` command) with `macosx` which is meant to be used as an input to the `project` command.

**Comment by talregev** [comment]
> From a quick search, it is this line: https://github.com/OGRECave/ogre-next/blob/bb07baeb2994d37f994df90b469be9b9a8d6e5bf/CMakeLists.txt#L388
> 
> It overrides the `CMAKE_OSX_SYSROOT` toolchain configuration (initialized during the `project` command) with `macosx` which is meant to be used as an input to the `project` command.

I will look at this line and figure out some fixing. 
Thank you a lot for you help 🙏🏻
