### ISSUE TITLE
[ms-quic] Build error

### ISSUE THREAD

**Issue by Johnparke888** [microsoft/vcpkg#35130]
Copy issue body from /usr2/vcpkg/installed/vcpkg/issue_body.md

Trying to build on Red Hat 7

Commands entered:

# **./bootstrap-vcpkg.sh**
Downloading vcpkg-glibc...
vcpkg package management program version 2023-10-18-27de5b69dac4b6fe8259d283cd4011e6d20a84ce

See LICENSE.txt for license information.
Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
**# ./vcpkg integrate install**
Applied user-wide integration for this vcpkg root.
CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=/usr2/vcpkg/scripts/buildsystems/vcpkg.cmake"
**./vcpkg install ms-quic**

Output from install step:
Computing installation plan...
The following packages will be built and installed:
    ms-quic:x64-linux -> 1.2.0
Detecting compiler hash for triplet x64-linux...
Restored 0 package(s) from /root/.cache/vcpkg/archives in 7.3 us. Use --debug to see more details.
Installing 1/1 ms-quic:x64-linux...
Building ms-quic:x64-linux...
-- Note: ms-quic only supports dynamic library linkage. Building dynamic library.
-- Using cached microsoft-msquic-v1.2.0.tar.gz.
-- Cleaning sources at /usr2/vcpkg/buildtrees/ms-quic/src/v1.2.0-19ce393c24.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /usr2/vcpkg/downloads/microsoft-msquic-v1.2.0.tar.gz
-- Applying patch fix-warnings.patch
-- Applying patch fix-platform.patch
-- Applying patch fix-install.patch
-- Using source at /usr2/vcpkg/buildtrees/ms-quic/src/v1.2.0-19ce393c24.clean
-- Using cached quictls-openssl-a6e9d76db343605dae9b59d71d2811b195ae7434.tar.gz.
-- Extracting source /usr2/vcpkg/downloads/quictls-openssl-a6e9d76db343605dae9b59d71d2811b195ae7434.tar.gz
-- Using source at /usr2/vcpkg/buildtrees/ms-quic/src/b195ae7434-aa88ae7c62.clean
-- Configuring x64-linux
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: /usr/local/bin/cmake --build . --config Debug --target install -- -v -j17
    Working Directory: /usr2/vcpkg/buildtrees/ms-quic/x64-linux-dbg
    See logs for more information:
      /usr2/vcpkg/buildtrees/ms-quic/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/ms-quic/portfile.cmake:64 (vcpkg_cmake_install)
  scripts/ports.cmake:170 (include)

error: building ms-quic:x64-linux failed with: BUILD_FAILED
Elapsed time to handle ms-quic:x64-linux: 54 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+ms-quic
You can submit a new issue at:
Attached is:  /usr2/vcpkg/installed/vcpkg/issue_body.md
[issue_body.md](https://github.com/microsoft/vcpkg/files/13366582/issue_body.md)

Is there any other information that you need?

Thanks,

John Parke

**Comment by autoantwort** [comment]
> /usr2/vcpkg/buildtrees/ms-quic/src/v1.2.0-19ce393c24.clean/src/platform/datapath_epoll.c:905:13: error: 'SO_ATTACH_REUSEPORT_CBPF' undeclared (first use in this function) 

From https://www.man7.org/linux/man-pages/man7/socket.7.html:
> SO_ATTACH_REUSEPORT_CBPF: UDP support for this feature is available since Linux 4.5;
              TCP support is available since Linux 4.6.
              
 From https://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux#RHEL_7
 > Red Hat Enterprise Linux 7.0 (Maipo), June 10, 2014; 9 years ago, uses Linux kernel 3.10.0-123

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
