### ISSUE TITLE
windeployqt6 difference between vcpkg and Qt versions

### ISSUE THREAD

**Issue by mickes27** [microsoft/vcpkg#35133]
**Describe the bug**
When calling `windeployqt6.exe --qmldir <path_to_qml_sources> <path_to_binary>` I found differences between using vcpkg version of windeployqt and the one installed from Qt installer. For Qt installer there are lot less not needed .dlls and application can be started (it founds all needed modules from `qml` dir). When using vcpkg version, I got a lot of garbage and my application cannot be started, because it cannot find Qt.Quick module.

**Environment**
- OS: Windows 10 64-bit
- Compiler: MSVC 19.37.32825.0
- vcpkg-tool version: 2023-10-18-27de5b69dac4b6fe8259d283cd4011e6d20a84ce
  vcpkg-scripts version: https://github.com/microsoft/vcpkg/commit/61f610845fb206298a69f708104a51d651872877 2023-11-10 (2 days ago)

**To Reproduce**
`windeployqt6.exe --qmldir <path_to_qml_sources> <path_to_binary>`

**Expected behavior**
Only needed dependencies are copied to deployment directory and application starts without any failure

**Failure logs**
-Logs from plugin tracing after vcpkg version deployment:
```
qt.qml.import: addImportPath: "<path_to_binary>/Qt6/qml"
qt.qml.import: locateLocalQmldir: QtQuick module's qmldir file not found
QQmlApplicationEngine failed to load component
qrc:/PonadNorme/Koralineo/imports/KoralineoUI/ui/main.qml:1:1: module "QtQuick" is not installed
```

-Logs from plugin tracing after Qt installer version deployment:
```
qt.qml.import: addImportPath: "<path_to_binary>/qml"
qt.qml.import: importExtension: qrc:/PonadNorme/Koralineo/imports/KoralineoUI/ui/main.qml loaded "C:/Users/Arfender/Desktop/Koralineo2/qml/QtQuick/qmldir"
```

**Additional info**
I am using `windeployqt6.exe`, not `windeployqt.debug.bat`, however result was the same for Debug builds.

**Comment by Neumann-A** [comment]
Would be relevant to know the resulting file layout in the binary dir after the windeployqt6 run.

**Comment by jimwang118** [comment]
No stale

**Comment by miss-programgamer** [comment]
I'm also encountering this problem and I'm confused as to how I should resolve it.

@mickes27 if I may ask, how did you obtain these "plugin tracing logs"? I assume it's a utility to see where Qt looks for QML imports but I can't find anything about it online, and I'd like to confirm if that's what's happening on my end.

**Comment by miss-programgamer** [comment]
Ok so I'm almost certain there's a bug in whichever cmake script is in charge of forwarding qml import paths to the build system. It's as if there's wires getting crossed at some point and instead of using `"qml"` as a suffix to the cmake binary path to generate the import path, it uses `"Qt6/qml"`, which is a value only relevant to where qml stuff is installed in vcpkg. In other words, it's erroneously constructing an import path from the project's binary directory and the vcpkg qml install suffix, or at least it must be doing that somewhere and then hardcoding that into executables.

**Comment by jobor** [comment]
Corresponding issue in Qt's bug tracker: https://bugreports.qt.io/browse/QTBUG-136454
I have a hard time reproducing this. Please see the comments in QTBUG-136454 on what I've tried.
