### ISSUE TITLE
Detecting compiler hash for triplet arm-android...error: while detecting compiler information:

### ISSUE THREAD

**Issue by WangHHY19931001** [microsoft/vcpkg#35142]
**Describe the bug**
Detecting compiler hash for triplet arm-android...error: while detecting compiler information:

**Environment**
- OS: windows 10 x64
with ndkVersion "25.2.9519653"

**To Reproduce**
-- Downloading https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-win.zip -> ninja-win-1.10.2.zip...
-- Configuring arm-android
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe -v
    Working Directory: C:/vcpkg/buildtrees/detect_compiler/arm-android-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\detect_compiler\config-arm-android-rel-CMakeCache.txt.log
      C:\vcpkg\buildtrees\detect_compiler\config-arm-android-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:314 (vcpkg_execute_required_process)
  scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:170 (include)

error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.

[detect_compiler.zip](https://github.com/microsoft/vcpkg/files/13371852/detect_compiler.zip)

**Comment by dg0yt** [comment]
~~~
CMake Error at C:/25c/25.2.9519653/build/cmake/android-legacy.toolchain.cmake:168 (message):
  Disabling Neon is no longer supported
~~~~

You  can no longer use arm-android with newer SDKs. But there is arm-neon-android.

**Comment by MonicaLiu0311** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
