### ISSUE TITLE
[live555] Build error

### ISSUE THREAD

**Issue by jskim0327** [microsoft/vcpkg#35148]
Copy issue body from C:/vcpkg/installed/vcpkg/issue_body.md

Package: live555:x64-windows -> 2023-07-24

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.35.32217.1
-    vcpkg-tool version: 2023-10-18-27de5b69dac4b6fe8259d283cd4011e6d20a84ce
    vcpkg-scripts version: ac2a14f35 2023-11-15 (4 hours ago)

**To Reproduce**

`vcpkg install live555:x64-windows live555:x64-windows-static`
**Failure logs**

```
-- Note: live555 only supports static library linkage. Building static library.
-- Downloading http://live555.com/liveMedia/public/live.2023.07.24.tar.gz -> live.2023.07.24.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from C:\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: C:\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading http://live555.com/liveMedia/public/live.2023.07.24.tar.gz
error: Failed to download from mirror set
error: http://live555.com/liveMedia/public/live.2023.07.24.tar.gz: failed: status code 404
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1051): 
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 3us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 2651us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 312 ms (276873us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
      

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/live555/portfile.cmake:3 (vcpkg_download_distfile)
  scripts/ports.cmake:170 (include)



```

Downloading http://live555.com/liveMedia/public/live.2023.07.24.tar.gz
error: Failed to download from mirror set
error: http://live555.com/liveMedia/public/live.2023.07.24.tar.gz: failed: status code 404
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1051):
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 3us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 2651us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 312 ms (276873us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/live555/portfile.cmake:3 (vcpkg_download_distfile)
  scripts/ports.cmake:170 (include)

**Comment by dg0yt** [comment]
They moved to 2023-11-08 and removed the last release, as usual.
http://live555.com/liveMedia/public/
Maybe the port should provide better reporting of this particular case? It happens app. three times a year. And vcpkg CI doesn't notice, due to asset caching.
