### ISSUE TITLE
[fmt] Build error with fmt on M1 

### ISSUE THREAD

**Issue by kevinsimper** [microsoft/vcpkg#35151]
I tried following the tutorial, but get this error with 
https://learn.microsoft.com/da-dk/vcpkg/get_started/get-started?pivots=shell-bash

Package: fmt:arm64-osx -> 10.1.1

**Host Environment**

- Host: arm64-osx
- Compiler: AppleClang 15.0.0.15000040
-    vcpkg-tool version: 2023-10-18-27de5b69dac4b6fe8259d283cd4011e6d20a84ce
    vcpkg-scripts version: ac2a14f35 2023-11-15 (6 hours ago)

**To Reproduce**

`vcpkg install `
**Failure logs**

```
-- Using cached fmtlib-fmt-10.1.1.tar.gz.
-- Cleaning sources at /Users/kevinsimper/projects/vcpkg/buildtrees/fmt/src/10.1.1-281bbdd8af.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/kevinsimper/projects/vcpkg/downloads/fmtlib-fmt-10.1.1.tar.gz
-- Applying patch fix-write-batch.patch
-- Applying patch fix-format-conflict.patch
-- Using source at /Users/kevinsimper/projects/vcpkg/buildtrees/fmt/src/10.1.1-281bbdd8af.clean
-- Configuring arm64-osx
-- Building arm64-osx-dbg
-- Building arm64-osx-rel
-- Fixing pkgconfig file: /Users/kevinsimper/projects/vcpkg/packages/fmt_arm64-osx/lib/pkgconfig/fmt.pc
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:162 (message):
  Could not find pkg-config.  Please install it via your package manager:

      brew install pkg-config
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:203 (vcpkg_find_acquire_program)
  /Users/kevinsimper/.cache/vcpkg/registries/git-trees/dfe9aa860f5a8317f341a21d317be1cf44e89f18/portfile.cmake:22 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:170 (include)



```
**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "dependencies": [
    "fmt"
  ]
}

```
</details>

**Comment by Cheney-W** [comment]
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:162 (message):
  Could not find pkg-config.  Please install it via your package manager:

      **brew install pkg-config**

**Comment by kevinsimper** [comment]
@Cheney-W Sorry, I did not even see that, that worked.

I did not read further than this line, but I should have
> Please ensure you're using the latest port files with `git pull` and `vcpkg update`.

Thank you
