### ISSUE TITLE
[gtk3] Build error : FAILED: gtk/gtk-builder-tool

### ISSUE THREAD

**Issue by davesworking** [microsoft/vcpkg#35178]
FAILED: gtk/gtk-builder-tool 
/opt/rh/gcc-toolset-10/root/usr/bin/ld: cannot find -lXtst
/opt/rh/gcc-toolset-10/root/usr/bin/ld: cannot find -lXtst
collect2: error: ld returned 1 exit status
FAILED: modules/input/im-am-et.so 
/opt/rh/gcc-toolset-10/root/usr/bin/ld: cannot find -lXtst
/opt/rh/gcc-toolset-10/root/usr/bin/ld: cannot find -lXtst
collect2: error: ld returned 1 exit status
FAILED: gtk/gtk-query-settings 
/opt/rh/gcc-toolset-10/root/usr/bin/ld: cannot find -lXtst
/opt/rh/gcc-toolset-10/root/usr/bin/ld: cannot find -lXtst
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by davesworking** [comment]
[Uploading package-x64-linux-dbg-out.log…]()

**Comment by dg0yt** [comment]
You must install additional development packages via your system package manager, providing libXtst.

**Comment by Adela0814** [comment]
@davesworking Please try to install  `libxtst-dev` and try again.
`sudo apt install libxtst-dev`
