### ISSUE TITLE
boost-pfr dependency isn't sufficient to use Boost::pfr

### ISSUE THREAD

**Issue by tonygould** [microsoft/vcpkg#35187]
**Describe the bug**
Add "boost-pfr" to vcpkg.json dependencies, can't use the library.

**Environment**
- OS: ubuntu 23.04
- Compiler: gcc 13.2
- OS: Windows 11
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32825 for x64

(note boost-pfr is header-only, so no compilation involved)

**To Reproduce**
1. Add "boost-pfr" to vcpkg.json dependencies for a project
2. Configure
3. `find_package(Boost)` fails with `Could NOT find Boost (missing: Boost_INCLUDE_DIR)`
4. Manually add "boost-config" to vcpkg.json dependencies
5.  `find_package(Boost)` now succeeds
6.  but `Boost::pfr` target not found (`Target links to: Boost::pfr but the target was not found`)

**Expected behavior**
Specify "boost-pfr" alone in vcpkg.json dependencies for a project,  `find_package(Boost)` succeeds and `Boost::pfr` target available for us in `target_link_libraries`

**Additional context**
Lack of `Boost::pfr` target can be worked around with

```
    if(NOT TARGET Boost::pfr)
        add_library(Boost::pfr INTERFACE IMPORTED)
        set_target_properties(Boost::pfr PROPERTIES INTERFACE_INCLUDE_DIRECTORIES ${Boost_INCLUDE_DIRS})
    endif()
```

Note also that a Fetch Content of the git repo https://github.com/boostorg/pfr.git works perfectly, providing the target `Boost::pfr` out-the-box, and this is in fact the easiest way to get Boost pfr at the moment.

It would be great for this to be fixed for the forthcoming Boost 1.84 release, as Boost::pfr includes the ability to automatically get field names; there is a lot of community interest.

**Comment by Osyotr** [comment]
> but Boost::pfr target not found (Target links to: Boost::pfr but the target was not found)

`find_package(Boost)` uses CMake's `FindBoost.cmake` which does not have `pfr` component because it's a header-only library.
You should link to `Boost::boost` instead.

**Comment by tonygould** [comment]
@Osyotr Thank you.

The first problem remains in that simply asking for "boost-pfr" doesn't bring in the "boost-config", which to me seems to be required.

**Comment by Osyotr** [comment]
Hmm the library is indeed a part of boost, but it does not use anything from boost. Maybe it's just that `FindBoost.cmake` doesn't know how to deal with it?

**Comment by BillyONeal** [comment]
`FindBoost.cmake` looks for `boost/version.h` or `boost/config.h`, both of which are owned by `boost-config`:

```
boost-config:x64-windows:/include/boost/version.hpp
boost-config:x64-windows:/include/boost/config.hpp
```

I think we should change all the other boost libraries to depend on boost-config so that `FindBoost.cmake` works. Alternately, setting various variables in the `vcpkg-cmake-wrapper.cmake` of `boost-uninstall` ( https://github.com/microsoft/vcpkg/blob/master/ports/boost-uninstall/vcpkg-cmake-wrapper.cmake ) such as `Boost_INCLUDE_DIR` might work instead.

**Comment by BillyONeal** [comment]
(This is because `FindBoost.cmake` does:

```cmake
  find_path(Boost_INCLUDE_DIR
    NAMES boost/version.hpp boost/config.hpp
    HINTS ${Boost_INCLUDE_DIRS}
    NO_DEFAULT_PATH
  )
```

)
