### ISSUE TITLE
VCPKG_APPLOCAL_DEPS should copy PDB files too

### ISSUE THREAD

**Issue by JoergAtGithub** [microsoft/vcpkg#35198]
Currently VCPKG_APPLOCAL_DEPS copies only the DLL files to the build directory, but for debugging also the PDB files need to be copied.

**Environment**
- OS: Windows

**Comment by jimwang118** [comment]
You can copy the `pdb` file to the directory by adding the `vcpkg_copy_pdbs()` function in the port `file.cmake` file.

**Comment by JoergAtGithub** [comment]
I mean the step to copy the files from `\installed\x64-windows\bin` to the build directory of my project, where I debug my code. Somehow CMake has to copy the PDB file next to the DLL file, otherwise the debugger will not find it.
The same applies for the install directory, if someone want to distribute the PDB files with his application.

**Comment by jimwang118** [comment]
> I mean the step to copy the files from `\installed\x64-windows\bin` to the build directory of my project, where I debug my code. Somehow CMake has to copy the PDB file next to the DLL file, otherwise the debugger will not find it. The same applies for the install directory, if someone want to distribute the PDB files with his application.

I understand, do you want to copy the pdb file to your project? However, this process requires the compiler or you to take the initiative to copy. vcpkg does not have the function to actively copy pdb to its own project.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.

**Comment by JoergAtGithub** [comment]
Of cause the issue still exist - and I do not have permissions to reopen this issue...
