### ISSUE TITLE
[feature request] Make an identifier to specify QNX as `platform` in vcpkg.json

### ISSUE THREAD

**Issue by Arech** [microsoft/vcpkg#35206]
vcpkg is being successfully used to cross-compile for aarm64 @ QNX, but a `platform` specifier in `vcpkg.json` manifest (as well as in classic mode) has no way to target QNX specifically. Given that this OS has lot's of distinctions from other *nix based OSes, probably it make sense to add an identifier for it.

**Comment by autoantwort** [comment]
What is the value of `CMAKE_SYSTEM_NAME` for QNX? Or how should it be detected? 
https://github.com/microsoft/vcpkg-tool/blob/4c1df40a3c5c5e18de299a99e9accb03c2a82e1e/src/vcpkg/platform-expression.cpp#L551

**Comment by Arech** [comment]
Ah, that's a good question.

We use `set(CMAKE_SYSTEM_NAME QNX)` in a toolchain file and `set(VCPKG_CMAKE_SYSTEM_NAME QNX)` in a triplet file for cross-compilation, but I'm not fully sure it's a general convention.
I can't check what would be the value on the device with QNX, since there's no CMake on it. If it's necessary, I could ask our DevOps if we could put CMake there to run the test...

**Comment by autoantwort** [comment]
CMake uses `uname -s` by default. Which should be `QNX` according to the documentation.

**Comment by Arech** [comment]
Awesome, it's the same on device:
```
# uname -s
QNX
```

**Comment by BillyONeal** [comment]
Fixed by https://github.com/microsoft/vcpkg/pull/35637
