### ISSUE TITLE
[ffmpeg] avformat's dependency is not copied to the build directory

### ISSUE THREAD

**Issue by emptyVoid** [microsoft/vcpkg#3521]
avformat-57.dll depends on libbz2.dll which is not being deployed to the build directory by VS/MSBuild.
The issue was spotted on x64 debug build (in x64 release build the library is deployed correctly).

**Comment by crackedmind** [comment]
I noticed that too. Debug version of avformat-57.dll linked with release version of libbz2

**Comment by JackBoosY** [comment]
waiting for pr #4250 to resolve.

**Comment by wangli28** [comment]
Thanks for posting this issue. PR #6570 has been merged. This issue has been fixed. So I am closing this issue for now.
