### ISSUE TITLE
Boost Static build error.

### ISSUE THREAD

**Issue by sdanfa** [microsoft/vcpkg#35214]
Hello,
I'm trying to use boost in a project statically, and it gives a build error.
LINK : warning LNK4286: symbol '??Aabstract_variables_map@program_options@boost@@QEBAAEBVvariable_value@12@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z (public: class boost::program_options::variable_value const & __cdecl boost::program_options::abstract_variables_map::operator[](class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const )' defined in 'boost_program_options-vc140-mt.lib(variables_map.obj)' is imported by 'libi2pd.lib(SSU2.obj)' [C:\Users\Ricebox\CLionProjects\i2PDServtest\cmake-build-release-visual-studio\i2PDServtest.vcxproj]
LINK : warning LNK4286: symbol '??Aabstract_variables_map@program_options@boost@@QEBAAEBVvariable_value@12@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z (public: class boost::program_options::variable_value const & __cdecl boost::program_options::abstract_variables_map::operator[](class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const )' defined in 'boost_program_options-vc140-mt.lib(variables_map.obj)' is imported by 'libi2pd.lib(Tunnel.obj)' [C:\Users\Ricebox\CLionProjects\i2PDServtest\cmake-build-release-visual-studio\i2PDServtest.vcxproj]

Thanks!

**Comment by jimwang118** [comment]
Can you provide more error information? There are only two link alarms here. Please provide the test code and the specific boost library used. Thank you.

**Comment by jimwang118** [comment]
From the error log, it seems that some boost libraries are missing when compiling the libi2pd.lib library. You can refer to the official [method](https://i2pd.readthedocs.io/en/latest/devs/building/windows/#building-on-windows) for compilation.

**Comment by sdanfa** [comment]
> From the error log, it seems that some boost libraries are missing when compiling the libi2pd.lib library. You can refer to the official [method](https://i2pd.readthedocs.io/en/latest/devs/building/windows/#building-on-windows) for compilation.

Hi, I'm using cmake toolchain file from vcpkg and I tried manually linking boost but it's giving me the same error. Do you know why?

**Comment by sdanfa** [comment]
Libi2pd is compiled fine, but then using the static built files of it the lib of libi2pd it fails with the error from link I gave you. Unresolved symbols.

**Comment by dg0yt** [comment]
If Libi2pd doesn't provide exported CMake config, your will have to add all required link libraries by hand. You may get an idea of what is required by inspecting that lib's build.

But the CMakeLists.txt you posted looks like ... a pile of hacks, probably from attempts to fix the problem. Try to get back to using plain `find_package` and imported CMake targets.

**Comment by sdanfa** [comment]
> If Libi2pd doesn't provide exported CMake config, your will have to add all required link libraries by hand. You may get an idea of what is required by inspecting that lib's build.
> 
> 
> 
> But the CMakeLists.txt you posted looks like ... a pile of hacks, probably from attempts to fix the problem. Try to get back to using plain `find_package` and imported CMake targets.

Hi,
It's already the libi2pd exported cmake config.

**Comment by dg0yt** [comment]
I see `install(TARGETS ... EXPORT ...)` in `build/CMakeLists`, but not how they create the main config file (which would have to do `find_dependency`).
And I see more strange CMake...
I guess the config isn't ready yet.

**Comment by sdanfa** [comment]
> I see `install(TARGETS ... EXPORT ...)` in `build/CMakeLists`, but not how they create the main config file (which would have to do `find_dependency`).
> 
> And I see more strange CMake...
> 
> I guess the config isn't ready yet.

Okay, what is the proper way to link boost static and its other libraries for my own blank c++ project for example? So I can test if it links or not properly.

**Comment by sdanfa** [comment]
I'm still getting the same linking issue. No matter what I try. Can someone help please? Thanks.

**Comment by jimwang118** [comment]
Will close issue because https://github.com/microsoft/vcpkg/pull/32309 and https://github.com/microsoft/vcpkg/issues/38533.
