### ISSUE TITLE
[simd] Bug when trying to build simd with configuration arm64-linux

### ISSUE THREAD

**Issue by TonyCongqianWang** [microsoft/vcpkg#35210]
I received the following output when trying to update my simd installation. The building part took almost an hour before failing

./vcpkg upgrade simd --no-dry-run
The following packages will be rebuilt:
  * simd:arm64-linux -> 5.3.128
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet arm64-linux...
Restored 0 package(s) from /home/pi/.cache/vcpkg/archives in 662 us. Use --debug to see more details.
Removing 1/2 simd:arm64-linux
Elapsed time to handle simd:arm64-linux: 3.76 ms
Installing 2/2 simd:arm64-linux...
Building simd:arm64-linux...
warning: -- Using community triplet arm64-linux. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /home/pi/Documents/vcpkg/triplets/community/arm64-linux.cmake
-- Downloading https://github.com/ermig1979/Simd/archive/v5.3.128.tar.gz -> ermig1979-Simd-v5.3.128.tar.gz...
-- Extracting source /home/pi/Documents/vcpkg/downloads/ermig1979-Simd-v5.3.128.tar.gz
-- Using source at /home/pi/Documents/vcpkg/buildtrees/simd/src/v5.3.128-d09ac2fee4.clean
-- Configuring arm64-linux
-- Building arm64-linux-dbg
^A -- Building arm64-linux-rel

-- Installing: /home/pi/Documents/vcpkg/packages/simd_arm64-linux/share/simd/copyright
-- Performing post-build validation
internal error: /home/pi/Documents/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2023-06-15/src/vcpkg/commands.build.cpp(888): Value was null

**Comment by Thomas1664** [comment]
Try updating the vcpkg tool by running `./bootstrap-vcpkg.sh` from the vcpkg root directory ( /home/pi/Documents/vcpkg )

**Comment by Thomas1664** [comment]
@Cheney-W I think the label is wrong. Although the title suggests something else, the issue is actually about an internal error in a previous version of the vcpkg tool but this error is already fixed. I think this should be tagged category:question

**Comment by TonyCongqianWang** [comment]
As always I am amazed by how fast you reply to issues! I am trying it right now and will update the comment
