### ISSUE TITLE
[sdl2-image] the install step doesn't copy the transitive dependencies

### ISSUE THREAD

**Issue by Raffaello** [microsoft/vcpkg#35226]
### Is your feature request related to a problem? Please describe.

when using sdl2-image and install the project,
libpng is not installed causing runtime error on the installed project.

### Proposed solution

install also the transitive dependencies with the sdl2-image target.

### Describe alternatives you've considered

i have tried installing the trasitive dependency but it is reported as not found.
I avoided to install explicitly the transitive dependency at the moment, but this should do the trick, but if it was meant to be in this way, than it should be forced to install libpng along side sdl2-image just for normal project build step.

**Comment by dg0yt** [comment]
This typically happens when DLLs are not linked via their import libs but loaded as modules/plugins.
vcpkg has no general solution for deploying modules/plugins.

**Comment by Raffaello** [comment]
> This typically happens when DLLs are not linked via their import libs but loaded as modules/plugins. vcpkg has no general solution for deploying modules/plugins.

@dg0yt thanks for the reply. This means it should be fixed eventually witihn the SDL2_image itself?

**Comment by dg0yt** [comment]
> This means it should be fixed eventually witihn the SDL2_image itself?

No. Using plugins is not a bug.

**Comment by Raffaello** [comment]
> > This means it should be fixed eventually witihn the SDL2_image itself?
> 
> No. Using plugins is not a bug.

i see.

Then i am rephrasing my question:
How can i copy the transitive dependency in a elegant way, without explicitly declaring it as a direct dependency? (as it is only needed for the install pacakge step in cmake)

**Comment by dg0yt** [comment]
Hm, sdl2-image was change to link the format libs directly, 11 months ago (2.6.2#1), just for convenient deployment.
So if you are using the latest version (now 2.6.3), you should see the DLLs being deployed...

**Comment by Raffaello** [comment]
@dg0yt 
my SDL2 version is: ` SDL2 Version: 2.26.5`.
sdl2 image: `SDL2 Image Version: 2.6.3`

there is no problem at all when building and doing execute the exe in the normal cmake build step.
The issue I am experiencing is only when running the `cmake install` that `libpng` is not copied over in the `bin/` folder along-side all the others DLLs/dependencies.

**Comment by dg0yt** [comment]
> there is no problem at all when building and doing execute the exe in the normal cmake build step.
> The issue I am experiencing is only when running the `cmake install` that `libpng` is not copied over in the `bin/` folder along-side all the others DLLs/dependencies.

I see...
You are interested in an experimental feature which must be activated via the `X_VCPKG_APPLOCAL_DEPS_INSTALL` cmake option.
Note that this seems to be limited to triplets with windows|uwp|xbox in the triplet name.
