### ISSUE TITLE
Mongocxx connection pool (Release version) has problem connecting to remote server

### ISSUE THREAD

**Issue by mbilal6** [microsoft/vcpkg#3524]
I've installed (and have been using it for a while now) mongocxx driver via vcpkg and everything installed correctly and runs perfectly in Debug version (I'm using Visual Studio 2017 and my application is a Windows Form c++ (CLR) application). In my application, I get a connection pool and acquire a client everytime I upload some data on the server. Typical interval of my automatic data upload is 10 minutes. 
My settings are 

```
mongocxx::uri uri_remote{ "mongodb://user:pwd@remote-host:PORT/database-name?minPoolSize=2&maxPoolSize=5" };
mongocxx::pool pool_remote{ uri_remote };
// Get a client from the pool
auto client_remote = pool_remote.acquire();
// The client is returned to the pool when it goes out of scope.
auto collection_remote = (*client_remote)["database-name"]["collection-1-name"];
auto collection_st_remote = (*client_remote)["database-name"]["collection-2-name"];
// And finally insert
try {
    // Insert remote. lines of code for doc1 and doc2 are skipped
    collection_remote.insert_one(doc1.view());
    collection_st_remote.insert_one(doc2.view());
    // I'm skipping the rest of the code section here
. . .
```

The problem, the database documents get uploaded every 10 minutes without a problem, but with the Release version (when I loaded the Release version of my application and started using that), the mongo insert doesn't work every time 10 minutes. It just misses/skips some entries (mostly one after a successful attempt according to what I observed).

With the release version loaded in a remote computer I'm unable to do any debugging even though I ran debug version which works perfectly with shorter intervals too (like 1 minute each).

Any help would be greatly appreciated as this is very urgent for me depending on the situation.

**Comment by PhoebeHui** [comment]
@mbilal6, thanks for posting this issue! Does it still be an issue for you?

**Comment by JackBoosY** [comment]
If this issue is still not resolved, please reopen it.
