### ISSUE TITLE
"./vcpkg install coolprop" fails

### ISSUE THREAD

**Issue by concolic** [Microsoft/vcpkg#3525]
- 64-bit Windows 10 Pro
- Package: coolprop:x86-windows
- Vcpkg version: 0.0.112-nohash

I did `./vcpkg update` at first, then both `./vcpkg install coolprop:x64-windows` and `./vcpkg install coolprop` fail with BUILD_FAILED.

vcpkg\coolprop\install-x64-windows-rel-out.log has the following output:

```
Microsoft (R) Incremental Linker Version 14.14.26428.1
Copyright (C) Microsoft Corporation.  All rights reserved.

   Creating library CoolProp.lib and object CoolProp.exp
MT: command "mt /nologo /manifest CoolProp.dll.manifest /outputresource:CoolProp.dll;#2" failed (exit code 0x1f) with the following output:

mt : general error c101008d: Failed to write the updated manifest to the resource of file "CoolProp.dll". The process cannot access the file because it is being used by another process.

ninja: build stopped: subcommand failed.
```

**Comment by concolic** [comment]
I tried the same process again, and this time `./vcpkg install coolprop:x64-windows` succeeded, but `./vcpkg install coolprop` fails. 

```
Microsoft (R) Incremental Linker Version 14.14.26428.1
Copyright (C) Microsoft Corporation.  All rights reserved.

   Creating library CoolProp.lib and object CoolProp.exp
MT: command "mt /nologo /manifest CoolProp.dll.manifest /outputresource:CoolProp.dll;#2" failed (exit code 0x1f) with the following output:

mt : general error c101008d: Failed to write the updated manifest to the resource of file "CoolProp.dll". The process cannot access the file because it is being used by another process.

ninja: build stopped: subcommand failed.
```

Is there any precaution I should know about when compiling code in vcpkg? I don't know what is "another process" here. How can I figure it out?

**Comment by NancyLi1013** [comment]
Thanks for posting this issue. I cannot reproduce it on the latest vcpkg now.
Please open a new issue if this is still a problem for you.
