### ISSUE TITLE
installing pangolin failed in vcpkg for linux platform.

### ISSUE THREAD

**Issue by apattnaik0721013** [Microsoft/vcpkg#3526]
- command - vcpkg install pangolin
- error - "could not find yasm" in vcpkg_find_acquire_program.cmake at line 44.

**Comment by apattnaik0721013** [comment]
@ras0219-msft 
can you guide me to address this issue?

**Comment by apattnaik0721013** [comment]
@ras0219-msft any help?

**Comment by LItwOK** [comment]
Hi, have you solved this problem? I've met the same problem as you. Any advice would help!
