### ISSUE TITLE
[llvm] adding patch to fix the bug of clang_getCursorKind

### ISSUE THREAD

**Issue by neko-para** [microsoft/vcpkg#35268]
### Is your feature request related to a problem? Please describe.

Please refer to [this llvm issue](https://github.com/llvm/llvm-project/issues/56687).
The patch is available from [this post](https://lists.llvm.org/pipermail/cfe-dev/2014-July/038198.html).

### Proposed solution

The solution is provided above.

**Comment by neko-para** [comment]
Actually I believe this IS a general bug of clang itself, which perhaps isn't really suitable to fix it here. But as this problem has been issued decade ago, simply adding a patch here could save quite of time if user decide to fix it (like via overlay port, which led to rebuilding).

**Comment by xgupta** [comment]
Fixed by https://github.com/llvm/llvm-project/commit/7091ca1ae3a87479b6febdf1c3a324d707c633d9.
