### ISSUE TITLE
Auto linking with lld-linker

### ISSUE THREAD

**Issue by DKGH** [microsoft/vcpkg#35275]
### Is your feature request related to a problem? Please describe.

As of Visual Studio Pro 2022, version 17, auto-linking of libraries is not supported with lld-linker. See [here](https://github.com/microsoft/vcpkg/issues/4359). Please see if it can be supported too.

### Proposed solution

Develop support for lld-linker.

**Comment by dg0yt** [comment]
Or better not?

**Comment by Neumann-A** [comment]
Auto-linking is a dangerous feature. Don't use it. Also wrong place to ask since it is a `link.exe` compatibility issue in `lld-link` not accepting wildcards and as such an issue for LLVM and not vcpkg.

**Comment by DKGH** [comment]
Convinced.
