### ISSUE TITLE
Target AppLocalFromInstalled: 'pwsh.exe' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by oleg-boulanov** [microsoft/vcpkg#35270]
**Describe the bug**
After installing vcpkg, new diagnostic output appeared while building existing projects

**Environment**
- OS: Windows 11
- Compiler: Visual Studio 2022/MSBuild

**To Reproduce**
1. Install vcpkg
2. Build existing static library C++ project in Visual Studio 2022
3. Check build output window

**Expected behavior**
No errors logged

**Failure logs**
Target AppLocalFromInstalled: 'pwsh.exe' is not recognized as an internal or external command, operable program or batch file.

---
On my Windows 11, PowerShell shortcut points to:
%SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe
and is included in 
Path=..;C:\Windows\System32\WindowsPowerShell\v1.0\;...

**Comment by StarGate-One** [comment]
vcpkg uses powershell-core `pwsh.exe` not windows powershell `powershell.exe`.
That said, vcpkg should have downloaded and installed the version of powershell core it requires - you can download/install [powershell-core from here](https://github.com/PowerShell/PowerShell). Just be sure to select `Add to Path for All Users` when installing.
[The version of powershell core used by vcpkg can be found here](https://github.com/microsoft/vcpkg/blob/11cbb6b57b502d4864fa3c51b36b1ec88527a036/scripts/vcpkgTools.xml#L185C81-L185C81), looks like the x86 version of 7.2.11.
I personally have [powershell-core 7.4 x64](https://github.com/PowerShell/PowerShell/releases/tag/v7.4.0) with its path added and vcpkg finds it just fine.

**Comment by oleg-boulanov** [comment]
Thank you for prompt response.
Maybe powershell-core should be listed as a prerequisite here: https://github.com/microsoft/vcpkg#quick-start-windows?

**Comment by StarGate-One** [comment]
vcpkg should download/install the tools needed by the ports/features selected while being transparent to the user.

Listing the dozens of supporting tools vcpkg uses as prerequisite would be formidable, long and overwhelming, especially for new users to install, not to mention most would not be needed.

In this case vcpkg failed to download/install powershell-core and I am unsure what information/logs would be required to duplicate the issue and then remedy. The maintainers or this area of vcpkg may be reaching out to you for more information.

**Comment by oleg-boulanov** [comment]
OK, thanks a lot!

**Comment by Adela0814** [comment]
@oleg-boulanov  Can you provide your simple reproduction project?

**Comment by oleg-boulanov** [comment]
@Adela0814 sorry, I can't.
StarGate-One already identified the issue - pwsh not installed during vcpkg installation:
`git clone https://github.com/microsoft/vcpkg.git`
`cd vcpkg && bootstrap-vcpkg.bat`
I had to install it manually to fix the issue.

**Comment by rislah** [comment]
Same. Manually installing fixed the issue.

**Comment by brett-rogers-twobulls** [comment]
The other possibly bigger problem is that this doesn't fail the build. Is this target necessary?
