### ISSUE TITLE
[openblas] Build error

### ISSUE THREAD

**Issue by XueXiJinBuShangShang** [microsoft/vcpkg#35288]
vcpkg>.\vcpkg install openblas --triplet=x64-windows --editable
Computing installation plan...
The following packages will be built and installed:
    openblas:x64-windows -> 0.3.25
Installing 1/1 openblas:x64-windows...
Building openblas:x64-windows...
-- Automatically setting %HTTP(S)_PROXY% environment variables to "127.0.0.1:33210".
-- Using cached xianyi-OpenBLAS-v0.3.25.tar.gz.
-- Using source at H:/vcpkg/buildtrees/openblas/src/v0.3.25-dc6d649124
-- Using cached strawberry-perl-5.38.0.1-64bit-portable.zip.
CMake Error at scripts/cmake/vcpkg_extract_archive.cmake:19 (message):
  H:/vcpkg/downloads/tools/perl/5.38.0.1 was an extraction
  target, but it already exists.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:199 (vcpkg_extract_archive)
  ports/openblas/portfile.cmake:20 (vcpkg_find_acquire_program)
  scripts/ports.cmake:170 (include)

error: building openblas:x64-windows failed with: BUILD_FAILED
Elapsed time to handle openblas:x64-windows: 6 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openblas
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[openblas]+Build+error&body=Copy+issue+body+from+H%3A%2FAlgorithm%2F3D%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by autoantwort** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report an issue.

**Comment by FrankXie05** [comment]
@XueXiJinBuShangShang Thanks for posting this issue, please remove this tool `H:/vcpkg/downloads/tools/perl/5.38.0.1` and try again.

**Comment by FrankXie05** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
