### ISSUE TITLE
[cxxopts] Build error

### ISSUE THREAD

**Issue by ayaka312** [microsoft/vcpkg#35304]
Copy issue body from C:/Users/Administrator/Downloads/adversary_emulation_library-master/turla/Resources/Snake/SnakeInstaller/build/x64-debug/vcpkg_installed/vcpkg/issue_body.md

**Comment by MonicaLiu0311** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report an issue.
