### ISSUE TITLE
CMake cannot find target "unofficial::sqlite3::sqlite3" when using port oatpp::oatpp-sqlite

### ISSUE THREAD

**Issue by Brouilles** [microsoft/vcpkg#35303]
**Describe the bug**
CMake cannot find target "unofficial::sqlite3::sqlite3" when using port oatpp::oatpp-sqlite.

**Environment**
- OS: Windows 11
- Compiler: Visual Studio 2022 17.7.6

**To Reproduce**

Create a CMake project with a vcpkg manifest that specifies "oatpp::oatpp-sqlite" as a dependency.
Configure the project.

Example: https://github.com/oatpp/example-crud

**Expected behavior**
CMake finds unofficial::sqlite3::sqlite3.

**Failure logs**
```
1> [CMake]   The link interface of target "oatpp::oatpp-sqlite" contains:
1> [CMake] 
1> [CMake]     unofficial::sqlite3::sqlite3
1> [CMake] 
1> [CMake]   but the target was not found.  Possible reasons include:
1> [CMake] 
1> [CMake]     * There is a typo in the target name.
1> [CMake]     * A find_package call is missing for an IMPORTED target.
1> [CMake]     * An ALIAS target is missing.
1> [CMake] 
1> [CMake] Call Stack (most recent call first):
1> [CMake]   C:/dev/vcpkg/installed/x64-windows/share/oatpp-sqlite/oatpp-sqliteConfig.cmake:18 (include)
1> [CMake]   C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
1> [CMake]   CMakeLists.txt:30 (find_package)
1> [CMake] -- Generating done (0.0s)
1> [CMake] CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by JonLiu1993** [comment]
@Brouilles, Thanks for posting this issue, this issue could be reproduced with vcpkg 2023-11-16-4c1df40a3c5c5e18de299a99e9accb03c2a82e1e and VS2022 17.6.6
