### ISSUE TITLE
Compiling gdal on windows(-static) does not create gdal_i.lib

### ISSUE THREAD

**Issue by kelteseth** [microsoft/vcpkg#35302]
**Describe the bug**
My goal is to build gdal so I can use it for georust/gdal. For this I need [gdal_i.lib](https://github.com/georust/gdal/blob/master/gdal-sys/build.rs#L123) (a stub library wrapping the GDAL DLL), that should come when installing via vcpkg. I have checked out multiple issue reports here and by the looks of it, this worked at some point? I was unable to find a feature flag to enable this: https://vcpkg.link/ports/gdal.

**Environment**
- OS: Windows 11
- Compiler: MSVC 2023 17.7
- Latest vcpkg master

**To Reproduce**
I have installed `gdal:x64-windows` and `gdal:x64-windows-static`, but both do not contain the needed `gdal_i.lib`
```
PS C:\Code\vcpkg> .\vcpkg.exe install gdal:x64-windows-static
Computing installation plan...
The following packages are already installed:
    gdal[core,zstd,webp,sqlite3,recommended-features,qhull,postgresql,png,pcre2,openssl,openjpeg,netcdf,lzma,libxml2,libspatialite,libkml,lerc,jpeg,iconv,hdf5,gif,geos,expat,default-features,curl]:x64-windows-static -> 3.8.0
gdal:x64-windows-static is already installed
Total install time: 112 us
The package GDAL provides CMake targets:

    find_package(GDAL CONFIG REQUIRED)
    target_link_libraries(main PRIVATE GDAL::GDAL)

PS C:\Code\vcpkg>

```
**Expected behavior**
![grafik](https://github.com/microsoft/vcpkg/assets/1071536/4ce233ad-bd16-4704-bca6-2567d08585a5)

![grafik](https://github.com/microsoft/vcpkg/assets/1071536/1a14ae19-0dbf-46c9-b4db-78d8d51e22da)

**Additional context**

**Comment by dg0yt** [comment]
> For this I need [gdal_i.lib](https://github.com/georust/gdal/blob/master/gdal-sys/build.rs#L123) (a stub library wrapping the GDAL DLL)

It is not missing, but the import libraries for the DLL are installed as `lib/gdal.lib` (release) / `debug/lib/gdald.lib` (debug).

**Comment by dg0yt** [comment]
> \vcpkg.exe install gdal:x64-windows-static

And this triplet doesn't build DLLs/import libs. You need `x64-windows`.

**Comment by kelteseth** [comment]
@dg0yt alright thanks! I think we can close it then :)
