### ISSUE TITLE
[libvpx] Build error

### ISSUE THREAD

**Issue by gbtech-org** [microsoft/vcpkg#35314]
Copy issue body from C:/Users/user/vcpkg/installed/vcpkg/issue_body.m
![Captureok](https://github.com/microsoft/vcpkg/assets/86320655/1fdc48f9-5088-4aec-b2c1-8f82ab10075a)

**Comment by dg0yt** [comment]
Update your baseline. The URLs have been updated months ago.

**Comment by gbtech-org** [comment]
How can i update the baseline?

**Comment by dg0yt** [comment]
On a regular checkout of github `master`, do `git pull`.
If using a particular revision or tag, move to a newer one.
And you should also re-run vcpkg-bootstrap again.

**Comment by gbtech-org** [comment]
Now it works thank you.
