### ISSUE TITLE
[boost-thread] build failure

### ISSUE THREAD

**Issue by LeenHawk** [microsoft/vcpkg#35316]
### Operating system

Linux Debian Sid

### Compiler

Emcc 3.1.49

### Steps to reproduce the behavior

```Shell
`./vcpkg install boost-thread --triplet=wasm32-emscripten`
```

### Failure logs

[install-wasm32-emscripten-dbg-out.log](https://github.com/microsoft/vcpkg/files/13463755/install-wasm32-emscripten-dbg-out.log)

**Comment by FrankXie05** [comment]
```
     trying generator unix.prebuilt ( -> LIB )
         property-requirements are not met: <toolset>unix
     trying generator gcc.prebuilt ( -> LIB )
         property-requirements are not met: <toolset>gcc
     trying generator emscripten.prebuilt ( -> LIB )
       is viable
```
`Build request: object(property-set)@307 <address-model>32 <link>static <threading>multi <toolset-emscripten:version>3.1.49 <toolset>emscripten <variant>debug
 `
 It seems that `boost` does not recognize the tool chain `emscripten`. It recognizes `wasm32-emscripten` as `toolset-emscripten`. 
 Does `boost` really support emscripten?🤔
 https://github.com/boostorg/boost/pull/110

**Comment by LeenHawk** [comment]
> ```
>      trying generator unix.prebuilt ( -> LIB )
>          property-requirements are not met: <toolset>unix
>      trying generator gcc.prebuilt ( -> LIB )
>          property-requirements are not met: <toolset>gcc
>      trying generator emscripten.prebuilt ( -> LIB )
>        is viable
> ```
> 
> `Build request: object(property-set)@307 <address-model>32 <link>static <threading>multi <toolset-emscripten:version>3.1.49 <toolset>emscripten <variant>debug ` It seems that `boost` does not recognize the tool chain `emscripten`. It recognizes `wasm32-emscripten` as `toolset-emscripten`. Does `boost` really support emscripten?🤔 [boostorg/boost#110](https://github.com/boostorg/boost/pull/110)

In July, it support. I think maybe some library is built after some fixes? In emscripten, people usually use boost header only...

**Comment by FrankXie05** [comment]
Is there a corresponding upstream issue or PR? Maybe it’s a problem with the boost version.

**Comment by LeenHawk** [comment]
> Is there a corresponding upstream issue or PR? Maybe it’s a problem with the boost version.

Maybe it's [this](https://github.com/microsoft/vcpkg/issues/29552#issue-1577440812)? Boost-thread seems to be fixed in Feburary...

**Comment by FrankXie05** [comment]
Are you using the latest vcpkg?

**Comment by LeenHawk** [comment]
> Are you using the latest vcpkg?

I installed fully freshed vcpkg yesterday...

**Comment by FrankXie05** [comment]
@Pospelove
