### ISSUE TITLE
[fontconfig] build failure - python 3.12 distutils removal meson problem

### ISSUE THREAD

**Issue by as-ascii** [microsoft/vcpkg#35332]
### Operating system

MacSOX 12 Github runner but all affected

### Steps to reproduce the behavior

```Shell
try to install fontconfig having python 3.12
```

### Failure logs

Traceback (most recent call last):
  File "/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/tmpbzagqcow.py", line 5, in <module>
    import distutils.command.install
ModuleNotFoundError: No module named 'distutils'

../src/2.14.2-7f52ee670b.clean/meson.build:47:0: ERROR: <PythonExternalProgram 'python' -> ['/usr/local/bin/python3']> is not a valid python or it is missing distutils

### Additional context

Python 3.12 removes deprecated distutils. Old Meson 0.63 available in vcpkg requires it. Needs probably to be updated to newest version 1.3.0.

**Comment by as-ascii** [comment]
It seems that upgrading Meson to 1.3.0 helped indeed.
Changes required:
```
sed -i -e 's/0.63/1.3.0/' ports/vcpkg-tool-meson/vcpkg.json
sed -i -e 's/0.63.0/1.3.0/' ports/vcpkg-tool-meson/portfile.cmake
sed -i -e 's/bb91cea0d66d8d036063dedec1f194d663399cdf/7368795d13081d4928a9ba04d48498ca2442624b/' ports/vcpkg-tool-meson/portfile.cmake
sed -i -e 's/e5888eb35dd4ab5fc0a16143cfbb5a7849f6d705e211a80baf0a8b753e2cf877a4587860a79cad129ec5f3474c12a73558ffe66439b1633d80b8044eceaff2da/b2dc940a8859d6b0af8cb762c896d3188cadc1e65e3c7d922d6cb9a4ed7a1be88cd4d51a8aa140319a75e467816e714c409cf74c71c830bbc5f96bb81c1845ce/' ports/vcpkg-tool-meson/portfile.cmake
sed -i -e "s/intl_factory/packages['intl'] = intl_factory/" ports/vcpkg-tool-meson/meson-intl.patch
```

**Comment by as-ascii** [comment]
For all users that encountered this problem: If you cannot patch port script like I described above or it cause other problems you can try to force github actions osx worker to use older version of python like described here:
Python version can be probably changed using setup-python action like described here:
https://docs.github.com/en/enterprise-server@3.10/actions/automating-builds-and-tests/building-and-testing-python#specifying-a-python-version
Available python versions are listed in workers readme files:
https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md
https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md

**Comment by MonicaLiu0311** [comment]
Fixing by #28084.
