### ISSUE TITLE
Semicolon appears instead of colon

### ISSUE THREAD

**Issue by VMCpp** [microsoft/vcpkg#35340]
**Describe the bug**
Semicolon appears instead of colon in path of detect_compiler causing an error

**Environment**
- OS: [e.g. Windows/Linux etc...] Windows 11
- Compiler: revision Latest

**To Reproduce**
1.  .\vcpkg\vcpkg install sdl2 --triplet x64-windows
2.   .\vcpkg\vcpkg install sdl2:x64-windows

3. See error
Repro code when
Right after

**Expected behavior**
I expected to install SDL2 properly without issues.

**Failure logs**
PS C:\Users\Hyper\Desktop\vcpkg> .\vcpkg\vcpkg install sdl2 --triplet x64-windows
Computing installation plan...
The following packages will be built and installed:
    sdl2[base,core]:x64-windows -> 2.28.4#1
  * vcpkg-cmake:x64-windows -> 2023-05-04
  * vcpkg-cmake-config:x64-windows -> 2022-02-06#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
error: while detecting compiler information:
The log file content at "C:\Users\Hyper\Desktop\vcpkg\vcpkg\buildtrees\detect_compiler\stdout-x64-windows.log" is:
CMake Error at C:/Users/Hyper/Desktop/vcpkg/vcpkg/scripts/ports.cmake:133 (message):
  Cannot find port:

    **Directory does not exist: C;/Users/Hyper/Desktop/vcpkg/vcpkg/scripts/detect_compiler**

error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.
PS C:\Users\Hyper\Desktop\vcpkg> .\vcpkg\vcpkg integrate install
Applied user-wide integration for this vcpkg root.
CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=C:/Users/Hyper/Desktop/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake"

All MSBuild C++ projects can now #include any installed libraries. Linking will be handled automatically. Installing new libraries will make them instantly available.

**Additional context**
A semicolon appears instead of a colon. I have no idea why.

**Comment by dg0yt** [comment]
Wrong cmake. You need a windows cmake, not the msys cmake.

**Comment by VMCpp** [comment]
Uninstalling msys2 indeed worked, it's like magic. Not sure why it doesn't use windows cmake as default however which I had already installed.

**Comment by dg0yt** [comment]
Probably it is only a problem when msys2's `/usr/bin` is in the `PATH`. It can provide tools like cmake and git, but it is based on POSIX paths. Calling windows programs will invoke path conversion heuristics which are a key feature for facilitating autotools builds on Windows.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This issue has been solved, so I am closing this issue for now.
