### ISSUE TITLE
[lapack-reference] Build failure on x64-linux

### ISSUE THREAD

**Issue by zhiyaot** [microsoft/vcpkg#35341]
Package: lapack-reference[blas-select,core,noblas]:x64-linux -> 3.11.0#1

**Host Environment**

- Host: x64-linux
- Compiler: GNU 11.4.0
-    vcpkg-tool version: 2023-11-16-4c1df40a3c5c5e18de299a99e9accb03c2a82e1e
    vcpkg-scripts version: cd5e746ec 2023-11-23 (3 days ago)

**To Reproduce**

`vcpkg install lapack`
**Failure logs**

```
-- Using cached Reference-LAPACK-lapack-v3.11.0.tar.gz.
-- Cleaning sources at /home/zhiyaot/vcpkg/buildtrees/lapack-reference/src/v3.11.0-5e6de67bfb.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/zhiyaot/vcpkg/downloads/Reference-LAPACK-lapack-v3.11.0.tar.gz
-- Applying patch cmake-config.patch
-- Applying patch lapacke.patch
-- Using source at /home/zhiyaot/vcpkg/buildtrees/lapack-reference/src/v3.11.0-5e6de67bfb.clean
-- The Fortran compiler identification is unknown
CMake Error at scripts/cmake/vcpkg_find_fortran.cmake:130 (message):
  Unable to find a Fortran compiler using 'CMakeDetermineFortranCompiler'.
  Please install one (e.g.  gfortran) and make it available on the PATH!
Call Stack (most recent call first):
  ports/lapack-reference/portfile.cmake:54 (vcpkg_find_fortran)
  scripts/ports.cmake:170 (include)



```

**Comment by zhiyaot** [comment]
resolved

**Comment by mybabyyh** [comment]
I have the same issue. May I ask how you solved it?

**Comment by dg0yt** [comment]
Maybe by installing gfortran with the system package manager?

> Unable to find a Fortran compiler using 'CMakeDetermineFortranCompiler'.
> Please install one (e.g.  gfortran) and make it available on the PATH!
