### ISSUE TITLE
[New Port Request] ncnn[vulkan]

### ISSUE THREAD

**Issue by hhxdestiny** [microsoft/vcpkg#35350]
### Library name

ncnn

### Source repository URL

https://github.com/Tencent/ncnn/tree/20231027

### Project homepage (if different from the source repository)

https://github.com/Tencent/ncnn

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

-DNCNN_VULKAN=ON
-DNCNN_SYSTEM_GLSLANG=ON

**Comment by ShirasawaSama** [comment]
Is there any progress on this issue? Pure CPU computing is too slow.
