### ISSUE TITLE
ICU not detected in boost-locale

### ISSUE THREAD

**Issue by mbikovitsky** [microsoft/vcpkg#3537]
# Setup
- Windows 10 17134.48 x64
- Visual Studio 2017 15.7.1
- Toolset v14.14
- vcpkg 0.0.112
- Boost 1.67.0

# Steps to Reproduce
`vcpkg install boost-locale[icu]:x64-windows`.

# Expected Outcome
boost-locale is built with ICU support.

# Actual Outcome
ICU is not detected during the build.
- The output log file states `icu : no`.
- `config.log` in the build tree states `LINK : fatal error LNK1181: cannot open input file 'icudt.lib'`.

There is a patch file named `0001-Fix-boost-ICU-support.patch` in the `boost` port which seems relevant to the issue, however it is never applied. Furthermore, it is strange that the patch resides inside the `boost` port, and not inside `boost-locale` and `boost-regex`.

**Comment by NancyLi1013** [comment]
Hi @mbikovitsky, thanks for posting this issue. ICU has been added to boost-locale in this PR #6141.

**Comment by mbikovitsky** [comment]
No, ICU is still not detected with the latest vcpkg (2019.06.26-nohash) and boost (1.70.0-2).

> ICU has been added to boost-locale in this PR #6141.

@NancyLi1013, the referenced PR does not, as far as I can tell, make any modifications pertaining to ICU at all. The problem is not that there is no support for ICU in boost - that has been there for a long time. The problem is that the ICU library is not detected during the build. vcpkg installs ICU, but the build of boost-locale does not detect it.

**Comment by cbezault** [comment]
This is a well documented issue compared to many on this repo, my apologies for it taking so long to get any attention. Unfortunately fixing this is going to have to be on the backlog for now but it sucks that we advertise boost as being built with icu support when it is not. This is now on our radar.

**Comment by mbikovitsky** [comment]
Thanks, @cbezault. Much appreciated.

**Comment by NancyLi1013** [comment]
@mbikovitsky 

Could you please try to rebuild this port based on #10943 and help confirm if this can work for you?

**Comment by mbikovitsky** [comment]
Builds fine with my Visual Studio 2019 16.5.4, and looks like it works. I didn't perform any extensive testing, just made sure that selecting the ICU backend in Boost.Locale works. Full system specs:

* Windows 10 18363.778 x64
* Visual Studio 2019 16.5.4
* Toolset v14.25
* vcpkg 2020.02.04-nohash-external
* Boost 1.72.0

Though it does look like the backend is still not detected with the `x86-windows-static` and `x64-windows-static` triplets (it does build, however), but perhaps it's just an issue with my configuration.
