### ISSUE TITLE
Updating to latest version of VCPKG seems to cause hour+ long hang just before restoring packages (on CentOS 7).

### ISSUE THREAD

**Issue by BrianMouncer** [microsoft/vcpkg#35383]
**Describe the bug**
For context, https://github.com/microsoft/vcpkg/issues/35359
libjpeg-turbo recently starting failing in our CiCd build on windows x64.
To resolve this I moved our vcpkg submodule to latest commit in your master.
That resolved the issue for the broken libjpeg-turbo port, however now nuget restore is failing on CentOS 7 build?

**Environment**
- OS: [Linux CentOS 7]
- Compiler: na

**To Reproduce**

We currently use CMake and VCPKG to install some dependencies.
The following packages will be built and installed:
    curl[core,non-http,openssl,ssl]:x64-linux -> 7.81.0
  * openssl[core]:x64-linux -> 1.1.1m#2
  * vcpkg-cmake[core]:x64-linux -> 2022-01-19
  * vcpkg-cmake-config[core]:x64-linux -> 2022-02-06
  * zlib[core]:x64-linux -> 1.2.11#13

**Expected behavior**
Prior to moving to the latest version of VCPkg, CMake would run and finish in less than 10 minutes.
After the update, CentOS builds Hang for over an hour just after VCPKG downloads nuget and attempting to restore the above packages. 

**Failure logs**
After the VCPKG update, we get to this point and hang.
The strange thing is, this only happens on CentOS 7, and is at a point in the logs just after downloading nuget and looks like it is between steps, just before I would expect VCPKG to fetch the 5 package and start installing them... our CiCd builds fro CentOS 7, Ubuntu 18.04 and 20.04.  The new updated VCPKG does not hang during restore on 18.04 or 20.04.  It seems to be only on CenstOS.

**Here is an example of the failed build output...**

Detecting compiler hash for triplet x64-linux...
The following packages will be built and installed:
    curl[core,non-http,openssl,ssl]:x64-linux -> 8.4.0
  * openssl:x64-linux -> 3.1.4#1
  * vcpkg-cmake:x64-linux -> 2023-05-04
  * vcpkg-cmake-config:x64-linux -> 2022-02-06#1
  * vcpkg-cmake-get-vars:x64-linux -> 2023-03-02
  * zlib:x64-linux -> 1.3
Additional packages (*) will be modified to complete this operation.
A suitable version of nuget was not found (required v6.2.1) Downloading portable nuget 6.2.1...
**Downloading nuget...
[https://dist.nuget.org/win-x86-commandline/v6.2.1/nuget.exe->/csspeech/external/vcpkg/downloads/dbb8c13d-nuget.exe](https://dist.nuget.org/win-x86-commandline/v6.2.1/nuget.exe-%3E/csspeech/external/vcpkg/downloads/dbb8c13d-nuget.exe)
Restored 0 package(s) from /root/.cache/vcpkg/archives in 37.4 us. Use --debug to see more details.**

"Then nothing after this for 57 minutes, where the 1 hour build timeout triggers build cancel.
This step usually takes 5-10 minutes max.

**Additional context**
An example **successful** build just before updating to latest version of VCPKG,

Detecting compiler hash for triplet x64-linux...
The following packages will be built and installed:
    curl[core,non-http,openssl,ssl]:x64-linux -> 7.81.0
  * openssl[core]:x64-linux -> 1.1.1m#2
  * vcpkg-cmake[core]:x64-linux -> 2022-01-19
  * vcpkg-cmake-config[core]:x64-linux -> 2022-02-06
  * zlib[core]:x64-linux -> 1.2.11#13
Additional packages (*) will be modified to complete this operation.
**Restored 0 packages from /root/.cache/vcpkg/archives in 31.67 us. Use --debug to see more details.
Attempting to fetch 5 packages from nuget.
A suitable version of nuget was not found (required v5.11.0). Downloading portable nuget v5.11.0...
Restored 5 packages from NuGet in 3.299 s. Use --debug for more information.**
Starting package 1/5: vcpkg-cmake-config:x64-linux
Installing package vcpkg-cmake-config[core]:x64-linux...
Elapsed time for package vcpkg-cmake-config:x64-linux: 754 us
Starting package 2/5: vcpkg-cmake:x64-linux
Installing package vcpkg-cmake[core]:x64-linux...
Elapsed time for package vcpkg-cmake:x64-linux: 804.8 us
Starting package 3/5: openssl:x64-linux
Installing package openssl[core]:x64-linux...
Elapsed time for package openssl:x64-linux: 14.63 ms
Starting package 4/5: zlib:x64-linux
Installing package zlib[core]:x64-linux...
Elapsed time for package zlib:x64-linux: 1.338 ms
Starting package 5/5: curl:x64-linux
Installing package curl[core,non-http,openssl,ssl]:x64-linux...
Elapsed time for package curl:x64-linux: 9.49 ms

Total elapsed time: 4.83 s

**Comment by dg0yt** [comment]
Downloading nuget.exe on linux? And possibly trying to execute it? 
(Do you use nuget for caching? I'm sure my local machine doesn't use it.)

**Comment by BrianMouncer** [comment]
> Downloading nuget.exe on linux? And possibly trying to execute it? (Do you use nuget for caching? I'm sure my local machine doesn't use it.)

It is just what CMake  and VCPKG do on their own...
aka, download the 5 packages and then VCPKG builds them???

The log doesn't give me much clue as to why it is hanging.
And after updating to the newer version of VCPKG, I see it is now requiring a slightly newer version of CMake and Nuget than it did before I updated VCPKG to fix the libjpeg-turbo build failure.

But it is 100 percent repro that it downloads nuget, and then hangs just before I would normally see the first log line about "Starting package 1/5: vcpkg-cmake-config:x64-linux".  but that line never comes for 57 minutes.

**Comment by Thomas1664** [comment]
The nuget.exe thing seems suspicious. Can you try running vcpkg with `--debug` so there's more information available to see where exactly it hang?

**Comment by dg0yt** [comment]
So nuget.exe has been there for a while, and `file` says it is a "Mono/.Net assembly".
So it depends on the mono runtime environment.
And I still think you use nuget for artifact caching...

**Comment by BrianMouncer** [comment]
Yes, I added "VCPKG_BINARY_SOURCES: clear;default,readwrite" to our pipeline, and that works around the vcpkg hanging for over an hour issue.

Now it seems that the updated port of OpenSSL is failing, where it was successful using the previous version of VCPKG.
From the loggs I initially though the "apk add linux-headers" package needed to be installed or updated, but I verified with YUM that both glibc-devel and kernel-headers packages are both installed and updated latest version.

"Package glibc-devel-2.17-326.el7_9.x86_64 already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package kernel-headers.x86_64 0:3.10.0-1160.66.1.el7 will be updated
---> Package kernel-headers.x86_64 0:3.10.0-1160.102.1.el7 will be an update
--> Finished Dependency Resolution"


------


"Building openssl:x64-linux...
-- Downloading https://github.com/openssl/openssl/archive/openssl-3.1.4.tar.gz -> openssl-openssl-openssl-3.1.4.tar.gz...
-- Extracting source /csspeech/external/vcpkg/downloads/openssl-openssl-openssl-3.1.4.tar.gz
-- Applying patch disable-apps.patch
-- Applying patch disable-install-docs.patch
-- Applying patch script-prefix.patch
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch unix/android-cc.patch
-- Applying patch unix/move-openssldir.patch
-- Applying patch unix/no-empty-dirs.patch
-- Applying patch unix/no-static-libs-for-shared.patch
-- Using source at /csspeech/external/vcpkg/buildtrees/openssl/src/nssl-3.1.4-c5488d00d9.clean
openssl requires Linux kernel headers from the system package manager.
   They can be installed on Alpine systems via `apk add linux-headers`.
   They can be installed on Ubuntu systems via `apt install linux-libc-dev`.

Can't locate IPC/Cmd.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at -e line 1.
BEGIN failed--compilation aborted at -e line 1.
CMake Error at ports/openssl/unix/portfile.cmake:27 (message):"

**Comment by BrianMouncer** [comment]
Ok, I found the missing package.
So if someone else upgrades VCPKG and nuget and openssl start failing after the update, I was able to get working again by...

I added "VCPKG_BINARY_SOURCES: clear;default,readwrite" to the matrix to disable binary caching when building on CentOS7.

Updating YUM and installing several new dependencies that where added by the VCPKG update.
"yum install -y glibc-devel kernel-headers perl-IPC-Cmd"

After those two updates, I was able to unblock our CiCd build.

Thanks for the help, and I hope this is helpfull to anyone else that hit this issue.

**Comment by clee704** [comment]
Not sure it's related, but binary caching with NuGet also hangs in CBL Mariner (Azure Linux) 2.0.

```
Additional packages (*) will be modified to complete this operation.
A suitable version of nuget was not found (required v6.2.1) Downloading portable nuget 6.2.1...
Downloading nuget...
https://dist.nuget.org/win-x86-commandline/v6.2.1/nuget.exe->/mnt/vss/_work/1/vcpkg/downloads/dbb8c13d-nuget.exe
```

CBL Mariner 2.0 doesn't support Mono, so I manually installed Mono 6.12.0 for Fedora. It used to work, but one day the image was updated, and it stopped working since then.

I asked the Mariner team and they said Mono is deprecated and you should use .NET CLI instead. I looked at the `dotnet` command line tool but it seems it's not a drop-in replacement for `nuget.exe`. Does vcpkg have a plan to support it instead of `nuget.exe` in Linux?

**Comment by Pravila00** [comment]
Hey, could we check this issue? I am facing the same issue as well

**Comment by jeff-kohn** [comment]
Is there really no plans to fix binary caching on Linux? This doesn't just affect Centos, it also affects RHEL. Not having binary caching for our ADO pipelines is killing build performance.
