### ISSUE TITLE
about vcpkg install ，Cmake error

### ISSUE THREAD

**Issue by daoqiang** [Microsoft/vcpkg#3539]
PS C:\Users\grit> vcpkg install curl:x86-windows-static
The following packages will be built and installed:
    curl[core,ssl]:x86-windows-static
  * openssl[core]:x86-windows-static
  * zlib[core]:x86-windows-static
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: zlib:x86-windows-static
Building package zlib[core]:x86-windows-static...
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
Please install the English language pack.
-- CURRENT_INSTALLED_DIR=D:/soft/vcpkg/installed/x86-windows-static
-- DOWNLOADS=D:/soft/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/soft/vcpkg/packages/zlib_x86-windows-static
-- CURRENT_BUILDTREES_DIR=D:/soft/vcpkg/buildtrees/zlib
-- CURRENT_PORT_DIR=D:/soft/vcpkg/ports/zlib
-- Using cached D:/soft/vcpkg/downloads/zlib1211.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch D:/soft/vcpkg/ports/zlib/cmake_dont_build_more_than_needed.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/soft/vcpkg/ports/zlib/cmake_dont_build_more_than_needed.patch done
-- Configuring x86-windows-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: D:/soft/vcpkg/buildtrees/zlib/x86-windows-static-rel/vcpkg-parallel-configure
    See logs for more information:
      D:\soft\vcpkg\buildtrees\zlib\config-x86-windows-static-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:237 (vcpkg_execute_required_process)
  ports/zlib/portfile.cmake:19 (vcpkg_configure_cmake)
  scripts/ports.cmake:72 (include)

Error: Building package zlib:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x86-windows-static
  Vcpkg version: 0.0.111-2018-05-11-29d04b8b4005f5e2bfe61ccdc7a93d5c6c8a13d9

Additionally, attach any relevant sections from the log files above.

**Comment by daoqiang** [comment]
hi？

**Comment by daoqiang** [comment]
Does the project have such a low heat

**Comment by churuxu** [comment]
toolsrc/src/vcpkg.cpp 中，这两句代码注释掉，
    //SetConsoleCP(CP_UTF8);
    //SetConsoleOutputCP(CP_UTF8);

再重新运行 bootstrap-vcpkg.bat
再试试

**Comment by daoqiang** [comment]
@churuxu ok,thank you.I have solved this problem by copying the previously installed vcpkg binary package to the new system.

**Comment by NancyLi1013** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
