### ISSUE TITLE
[boost] build failure

### ISSUE THREAD

**Issue by HunterZ** [microsoft/vcpkg#35408]
### Operating system

Windows 11

### Compiler

MinGW GCC 13.2.0

### Steps to reproduce the behavior

```Shell
VCPKG_DEFAULT_TRIPLET=x64-mingw-static VCPKG_DEFAULT_HOST_TRIPLET=x64-mingw-static PATH="${PATH/:\/usr\/bin:\/bin:/:}" ./vcpkg install boost
```

### Failure logs

```
Computing installation plan...
python3 is only supported on '!uwp & !mingw', which does not match x64-mingw-static. This usually means that there are known build failures, or runtime problems, when building other platforms. To ignore this and attempt to build python3 anyway, rerun vcpkg with `--allow-unsupported`.
```

### Additional context

I don't even care about python, so I don't understand what this is all about. I'm just trying to install Boost!

**Comment by dg0yt** [comment]
`boost` means all of boost, incl. `boost-python`. 
The immediate mitigation is to install only the boost ports which you actually need.

It might be possible to guard this particular dependency with `"platform": "!mingw"` - I don't see mingw support for (building) python coming soon.

**Comment by HunterZ** [comment]
Would be nice to get a separate boost metapackage that does not include the python module, given that it's apparently such a problematic outlier compared to the rest of the components.
