### ISSUE TITLE
libusb - does not work with static linking using dynamic CRT

### ISSUE THREAD

**Issue by carmangary** [microsoft/vcpkg#3540]
In my project I am set up for static linking but with a dynamic CRT.  I set this up by modifying the x86-windows-static triplet with 
      `set(VCPKG_CRT_LINKAGE dynamic)`

I get some errors when attempting to use libusb although it works with opencv.  
I was able to get past the issue with libusb by modifying the libusb .csprojx files so that they specify 
      `<RuntimeLibrary>MultiThreadedDLL</RuntimeLibrary>`
instead of 
      `<RuntimeLibrary>MultiThreaded</RuntimeLibrary>`

It would be nice if this worked out of the box, though.

**Comment by JackBoosY** [comment]
Hi @carmangary, thanks for reporting this issue.
I've fixed this issue, please update vcpkg and rebuild libusb.

Thanks.
