### ISSUE TITLE
[cnats] build failure

### ISSUE THREAD

**Issue by goumanghd** [microsoft/vcpkg#35421]
### Operating system

windows

### Compiler

gcc

### Steps to reproduce the behavior

```Shell
Please note that I have discovered the problem through debugging, and the following is a description of the problem and the solution to the problem. Please update it in time.

1.Observed behavior
e.g file cnats-targets-debug.cmake

list(APPEND _cmake_import_check_targets cnats::nats )
list(APPEND _cmake_import_check_files_for_cnats::nats "${_IMPORT_PREFIX}/debug/lib/natsd.lib" "${_IMPORT_PREFIX}/debug/ -->bin/natsd.lib<---" ) --->err<---

2.Expected behavior
list(APPEND _cmake_import_check_targets cnats::nats )
list(APPEND _cmake_import_check_files_for_cnats::nats "${_IMPORT_PREFIX}/debug/lib/natsd.lib" "${_IMPORT_PREFIX}/debug/ -->bin/natsd.dll<---" ) --->success<---

note: such err total two , you can search by [bin/natsd.lib] [lib/natsd.dll] , you will get the err point.

3.Server and client version
vcpkg
{
"name": "cnats",
"version": "3.7.0"
}

4.How to fix this bug
https://github.com/microsoft/vcpkg/blob/master/ports/cnats/portfile.cmake
line 49-51 62  lib/natsd.dll --> lib/natsd.dll

lib/nats.dll --> bin/nats.dll not in the file? I found in <cnats-targets.cmake> file
```

### Failure logs

CMake Error at vcpkg_installed/x64-windows/share/cnats/cnats-targets.cmake:85 (message):
  The imported target "cnats::nats" references the file

     "D:/code/quant/hello/vcpkg_installed/x64-windows/debug/lib/natsd.dll"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "D:/code/quant/hello/vcpkg_installed/x64-windows/share/cnats/cnats-targets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  vcpkg_installed/x64-windows/share/cnats/cnats-config.cmake:32 (include)
  D:/soft/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  src/md8-pub/CMakeLists.txt:4 (find_package)

**Comment by jimwang118** [comment]
This issue could be reproduced with vcpkg 2023-11-16-4c1df40a3c5c5e18de299a99e9accb03c2a82e1e. I will try to fix it.
