### ISSUE TITLE
jemalloc install error

### ISSUE THREAD

**Issue by yyzybb537** [microsoft/vcpkg#3542]
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: /home/ubuntu/git-third/vcpkg/downloads/tools/cmake-3.10.2-linux/cmake-3.10.2-Linux-x86_64/bin/cmake;/home/ubuntu/git-third/vcpkg/buildtrees/jemalloc/src/make.4.3.1-1ab87264ab;-DGIT_FOUND=OFF;-DCMAKE_DISABLE_FIND_PACKAGE_Git=ON;-DCMAKE_MAKE_PROGRAM=/home/ubuntu/git-third/vcpkg/downloads/tools/ninja-1.8.2-linux/ninja;-DCMAKE_SYSTEM_NAME=Linux;-DBUILD_SHARED_LIBS=ON;-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/ubuntu/git-third/vcpkg/scripts/toolchains/linux.cmake;-DVCPKG_TARGET_TRIPLET=x64-linux;-DVCPKG_PLATFORM_TOOLSET=external;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=/home/ubuntu/git-third/vcpkg/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DVCPKG_CXX_FLAGS=;-DVCPKG_CXX_FLAGS_RELEASE=;-DVCPKG_CXX_FLAGS_DEBUG=;-DVCPKG_C_FLAGS=;-DVCPKG_C_FLAGS_RELEASE=;-DVCPKG_C_FLAGS_DEBUG=;-DVCPKG_CRT_LINKAGE=dynamic;-DVCPKG_LINKER_FLAGS=;-DCMAKE_INSTALL_LIBDIR:STRING=lib;-DCMAKE_INSTALL_BINDIR:STRING=bin;-G;Ninja;-DCMAKE_BUILD_TYPE=Debug;-DCMAKE_INSTALL_PREFIX=/home/ubuntu/git-third/vcpkg/packages/jemalloc_x64-linux/debug
    Working Directory: /home/ubuntu/git-third/vcpkg/buildtrees/jemalloc/x64-linux-dbg
    See logs for more information:
      /home/ubuntu/git-third/vcpkg/buildtrees/jemalloc/config-x64-linux-dbg-out.log
      /home/ubuntu/git-third/vcpkg/buildtrees/jemalloc/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:247 (vcpkg_execute_required_process)
  ports/jemalloc/portfile.cmake:22 (vcpkg_configure_cmake)
  scripts/ports.cmake:72 (include)

Error: Building package jemalloc:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: jemalloc:x64-linux
  Vcpkg version: 0.0.112-unknownhash

Additionally, attach any relevant sections from the log files above.

OS: linux ubuntu 16.04

**Comment by Jackson-soft** [comment]
Mac os same issue

**Comment by jimwang118** [comment]
This issue has been fixed by PR [5829](https://github.com/microsoft/vcpkg/pull/5829).
