### ISSUE TITLE
Cannot install cuda with x86-windows-static or x64-windows-static

### ISSUE THREAD

**Issue by carmangary** [Microsoft/vcpkg#3543]
Works fine with x86-windows or x64-windows.  Since the port file is only searching for the version of cuda installed I don't understand why it doesn't work with the -static directive.  I have cuda version 9.2 installed.

The output is as follows:

PS D:\vcpkg-test> .\vcpkg install cuda:x86-windows-static
The following packages will be built and installed:
    cuda[core]:x86-windows-static
Starting package 1/1: cuda:x86-windows-static
Building package cuda[core]:x86-windows-static...
-- CURRENT_INSTALLED_DIR=D:/vcpkg-test/installed/x86-windows-static
-- DOWNLOADS=D:/vcpkg-test/downloads
-- CURRENT_PACKAGES_DIR=D:/vcpkg-test/packages/cuda_x86-windows-static
-- CURRENT_BUILDTREES_DIR=D:/vcpkg-test/buildtrees/cuda
-- CURRENT_PORT_DIR=D:/vcpkg-test/ports/cuda
CMake Error at ports/cuda/portfile.cmake:26 (message):
  Could not find CUDA.  Before continuing, please download and install CUDA
  (V9.0.0 or higher) from:

      https://developer.nvidia.com/cuda-downloads

  Also ensure vcpkg has been rebuilt with the latest version (v0.0.104 or
  later)
Call Stack (most recent call first):
  scripts/ports.cmake:72 (include)

Error: Building package cuda:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cuda:x86-windows-static
  Vcpkg version: 0.0.112-nohash

Additionally, attach any relevant sections from the log files above.
PS D:\vcpkg-test>

**Comment by Voskrese** [comment]
Написано же, и не на инди, скачать и установить. Тем более много кто с такой ошибкой был, пользуйтесь поиском

**Comment by Voskrese** [comment]
`https://github.com/Microsoft/vcpkg/blob/d5cb490fc02b9b0c26d869fabf3b37158586236f/ports/cuda/portfile.cmake`

```
find_program nvcc.exe
COMMAND ${NVCC} --version
set(CUDA_REQUIRED_VERSION "V9.0.0")
```
отредактировать, возможно поможет
set(CUDA_REQUIRED_VERSION "V9.5.0")

**Comment by carmangary** [comment]
Thank you for  your comment.  I don't think the problem is that because it fails prior to that.  In the preceding `if` block
```
if (NVCC)
    execute_process(
        COMMAND ${NVCC} --version
        OUTPUT_VARIABLE NVCC_OUTPUT
        RESULT_VARIABLE error_code)
endif()
```
ether NVCC is not set (or error_code is being set).  This is simply finding the nvcc and checking the version number, though.  When I run with the x86-windows flag there are no problems.  So, it seems like this file is fine but the environment in which it runs gets messed up when specifying x86-windows-static, but I don't see how/why.

**Comment by carmangary** [comment]
By some fashion this problem has solved itself so I cam closing this issue.
