### ISSUE TITLE
[libwebsockets] Build error on x64-mingw-static

### ISSUE THREAD

**Issue by zmj646409** [microsoft/vcpkg#35457]
Copy issue body from D:/vcpkg/installed/vcpkg/issue_body.md

**Comment by FrankXie05** [comment]
@zmj646409 Thanks for posting this issue, port `pthreads` not support `windows` and `mingw`.
https://github.com/microsoft/vcpkg/blob/1751f9f8c732c2e6f9e81ce56c10e4c4aa265b4a/ports/pthreads/portfile.cmake#L1
