### ISSUE TITLE
[sdl2-image] Building in Manifest mode failure (ninja: error: 'SDL2::SDL2-NOTFOUND', needed by 'SDL2_imaged.dll')

### ISSUE THREAD

**Issue by Joseph-Park-dev** [microsoft/vcpkg#35458]
**Describe the bug**
When trying to install SDL2-image package with Manifest mode, it fails with an error BUILD_FAILED

**Environment**

OS: Windows 10
IDE: MS Visual Studio 2022

**To Reproduce**
1) Write a vcpkg.json file for Manifest mode
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json",
  "name": "my-app",
  "version": "1.0.1",
  "dependencies": [
    "sdl2",
    "sdl2-image"
  ]
}
2) Try building the project, and it works fine with sdl2, but not with sdl2-image

**Failure logs**
I received a error log with this single message
 (install-x64-windows-dbg-err.log)
**ninja: error: 'SDL2::SDL2-NOTFOUND', needed by 'SDL2_imaged.dll', missing and no known rule to make it**

Please let me know if there is any additional info needed to identify the problem.
Thank you in advance!

**Comment by dg0yt** [comment]
Is ist possible to report the port versions, in particular of sdl2-image?
And if it is not `2.6.3#0`, then the next request is to update.

**Comment by Joseph-Park-dev** [comment]
> Is ist possible to report the port versions, in particular of sdl2-image? And if it is not `2.6.3#0`, then the next request is to update.

Hi, thanks for the comment.
May I ask the way to check the port versions?
I went to installed directory of vcpkg, ran "vcpkg list" command, and it says sdl2-image 2.6.3 was installed.
On the project directory however, I couldn't find the version of sdl2-image because it is not installed there yet.

**Comment by Cheney-W** [comment]
How is it set in your project folder? Did you use CMakeLists.txt? If so, can you send it to me? Thank you!

**Comment by Joseph-Park-dev** [comment]
> How is it set in your project folder? Did you use CMakeLists.txt? If so, can you send it to me? Thank you!

Hi, I haven't used CMakeList.txt but vcpkg gives me logs regarding cmake anyhow.
But I managed to solve problem by **deleting vcpkg manager from VisualStudio installer, and manuallly installing
the vcpkg again by cloning from gitHub.**
Then the problem is solved! now packages could be installed through manifest mode.
Although .dll files are not copied automatically, it's ok because I can copy them manually.
(But if you have information regarding auto-copying .dll files to output directory, please let me know)

Thanks for the help!
