### ISSUE TITLE
[harfbuzz] Harfbuzz with graphite2 feature generates references to dynamic imports when linking statically

### ISSUE THREAD

**Issue by CraftSpider** [microsoft/vcpkg#35455]
### Is your feature request related to a problem? Please describe.

After building `harfbuzz[graphite2]` with static library and crt linkage, then trying to use it in a project, I get linking errors like the following:
```
harfbuzz.lib(hb-graphite2.cc.obj) : error LNK2019: unresolved external symbol __imp_gr_face_featureval_for_lang referenced in function _hb_graphite2_shape
harfbuzz.lib(hb-graphite2.cc.obj) : error LNK2019: unresolved external symbol __imp_gr_face_find_fref referenced in function _hb_graphite2_shape
```

As far as I can tell, this is caused by not setting `GRAPHITE2_STATIC` even though the crate is actually building it statically.

### Proposed solution

When static libraries are enabled, set `GRAPHITE2_STATIC` for harfbuzz when the `graphite2` feature is active

### Describe alternatives you've considered

Trying to set it myself - as far as I can tell, this requires patching stuff awkwardly. I'm not a master of vcpkg, so please tell me if there's a better way to handle this.

### Additional context

OS: Windows 10

Using custom triplet:
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_BUILD_TYPE release)
```

**Comment by Adela0814** [comment]
I can repro this issue, this may be a `graphite2` bug.

**Comment by dg0yt** [comment]
> When static libraries are enabled, set `GRAPHITE2_STATIC` for harfbuzz when the `graphite2` feature is active

Or just burn the effect into the installed graphite headers. Common practice in vcpkg.

**Comment by jimwang118** [comment]
When using static compilation, the [-DGRAPHITE2_STATIC](https://github.com/search?q=repo%3Asilnrsi%2Fgraphite%20GRAPHITE2_STATIC&type=code#:~:text=add_definitions(%2DDGRAPHITE2_STATIC)) attribute is set upstream.

**Comment by CraftSpider** [comment]
The issue I'm seeing isn't the building of the upstream graphite2, but the build of harfbuzz which includes the graphite2 `.h` file without the definition, meaning the included functions are defined as dynamic instead of static in the harfbuzz object.
