### ISSUE TITLE
[boost-exception] Build error on x64-windows

### ISSUE THREAD

**Issue by Pupsik22877778292** [microsoft/vcpkg#35462]
Copy issue body from C:/Users/koro4/OneDrive/Рабочий стол/vcpkg-master/installed/vcpkg/issue_body.md

**Comment by Pupsik22877778292** [comment]
error: building boost-exception:x64-windows failed with: BUILD_FAILED
Elapsed time to handle boost-exception:x64-windows: 7.5 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
