### ISSUE TITLE
[ffmpeg] Build error on x64-linux

### ISSUE THREAD

**Issue by litongjava** [microsoft/vcpkg#35489]
Copy issue body from /root/code/whisper-cpp-server/cmake-build-release/vcpkg_installed/vcpkg/issue_body.md
```
Package: ffmpeg[avcodec,avdevice,avfilter,avformat,core,swresample,swscale]:x64-linux -> 6.1

**Host Environment**

- Host: x64-linux
- Compiler: GNU 9.4.0
-    vcpkg-tool version: 2023-11-16-4c1df40a3c5c5e18de299a99e9accb03c2a82e1e
    vcpkg-scripts version: 16ee2ecb3 2023-12-01 (3 days ago)

**To Reproduce**

`vcpkg install `
**Failure logs**

```
-- Downloading https://github.com/ffmpeg/ffmpeg/archive/n6.1.tar.gz -> ffmpeg-ffmpeg-n6.1.tar.gz...
-- Extracting source /root/vcpkg/downloads/ffmpeg-ffmpeg-n6.1.tar.gz
-- Applying patch 0001-create-lib-libraries.patch
-- Applying patch 0002-fix-msvc-link.patch
-- Applying patch 0003-fix-windowsinclude.patch
-- Applying patch 0004-fix-debug-build.patch
-- Applying patch 0005-fix-nasm.patch
-- Applying patch 0006-fix-StaticFeatures.patch
-- Applying patch 0007-fix-lib-naming.patch
-- Applying patch 0009-Fix-fdk-detection.patch
-- Applying patch 0011-Fix-x265-detection.patch
-- Applying patch 0012-Fix-ssl-110-detection.patch
-- Applying patch 0013-define-WINVER.patch
-- Applying patch 0015-Fix-xml2-detection.patch
-- Applying patch 0020-fix-aarch64-libswscale.patch
-- Applying patch 0022-fix-iconv.patch
-- Using source at /root/vcpkg/buildtrees/ffmpeg/src/n6.1-f7bac3f35b.clean
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:162 (message):
  Could not find nasm.  Please install it via your package manager:

      sudo apt-get install nasm
Call Stack (most recent call first):
  buildtrees/versioning_/versions/ffmpeg/e350faae831bb8d75c4ebcee81d9161484aecdba/portfile.cmake:30 (vcpkg_find_acquire_program)
  scripts/ports.cmake:170 (include)

```
**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "name": "whisper-cpp-server",
  "version-string": "1.0.0",
  "builtin-baseline": "0c20b2a97c390e106150837042d921b0939e7ecb",
  "dependencies": [
    {
      "name": "sdl2",
      "version>=": "2.28.4#1",
      "$comment": "    find_package(SDL2 CONFIG REQUIRED)\n\n    target_link_libraries(main\n\n        PRIVATE\n\n        $<TARGET_NAME_IF_EXISTS:SDL2::SDL2main>\n\n        $<IF:$<TARGET_EXISTS:SDL2::SDL2>,SDL2::SDL2,SDL2::SDL2-static>\n\n    )\n"
    },
    {
      "name": "uwebsockets",
      "version>=": "20.47.0"
    },
    {
      "name": "libsamplerate",
      "version>=": "0.2.2#1",
      "$comment": "  # this is heuristically generated, and may not be correct\n\n  find_package(SampleRate CONFIG REQUIRED)\n\n  target_link_libraries(main PRIVATE SampleRate::samplerate)\n"
    },
    {
      "name": "ffmpeg",
      "version>=": "6.1"
    },
    {
      "name": "speexdsp",
      "version>=": "1.2.1#1"
    }
  ]
}

```
</details>

```

**Comment by StarGate-One** [comment]
>Could not find nasm. Please install it via your package manager:
>
> sudo apt-get install nasm

**Comment by litongjava** [comment]
thanks

**Comment by StarGate-One** [comment]
You are most welcome!
