### ISSUE TITLE
[ICU/SKIA] packages can't be built for X64-android

### ISSUE THREAD

**Issue by vraziel** [microsoft/vcpkg#35487]
Env: WSL and regular Ubuntu.

Latest NDK which comes with Android Studio. Env variable ANDROID_NDK_HOME is set to \home\vk\Android\Sdk\ndk\26.1.10909125

sudo $VCPKG_ROOT/vcpkg install icu:x64-android - **fails**
sudo $VCPKG_ROOT/vcpkg install skia:x64-android -**fails**

sudo $VCPKG_ROOT/vcpkg install icu:x64-linux- works
sudo $VCPKG_ROOT/vcpkg install skia:x64-linux -works

At windows machine 
$VCPKG_ROOT/vcpkg install icu:x64-windows - works
$VCPKG_ROOT/vcpkg install icu:x64-windows - works

Skia can't be build because it depends on icu.

Logs:
 
[config-x64-android-dbg-config.log](https://github.com/microsoft/vcpkg/files/13550164/config-x64-android-dbg-config.log)
[config-x64-android-dbg-err.log](https://github.com/microsoft/vcpkg/files/13550165/config-x64-android-dbg-err.log)

[config-x64-android-dbg-out.log](https://github.com/microsoft/vcpkg/files/13550166/config-x64-android-dbg-out.log)

But package like opencv can be built with command sudo $VCPKG_ROOT/vcpkg install opencv:x64-android

**Comment by dg0yt** [comment]
NDK r26 support in vcpkg is limited - in particular not covering `configure`/`make` based ports like icu. Cf. #31228.
And this blocks many other ports.

**Comment by vraziel** [comment]
> NDK r26 support in vcpkg is limited - in particular not covering `configure`/`make` based ports like icu. Cf. #31228. And this blocks many other ports.

Thanks. Probably you know which NDK will work for skia? 21?

**Comment by dg0yt** [comment]
25 is used in vcpkg CI. 26 is the one which has breaking changes. (No standalone toolchains.)

**Comment by vraziel** [comment]
> [dg0yt](/dg0yt)

🙇‍♂️ 
🥇
