### ISSUE TITLE
[skia] Crash on user project

### ISSUE THREAD

**Issue by xiaozhuai** [microsoft/vcpkg#35499]
**Describe the bug**
Here are two simple function.

```c++
inline sk_sp<SkImage> loadSkImageFromFile(const std::string &file) {
    auto data = SkData::MakeFromFileName(file.c_str());
    // the data here is not nullptr, but the size is not equal to file.
    assert(data);
    return SkImages::DeferredFromEncodedData(data); // crash here
}

inline sk_sp<SkSurface> createSurface(int width, int height, uint8_t *framebuffer) {
    SkImageInfo info = SkImageInfo::MakeN32(width, height, SkAlphaType::kUnpremul_SkAlphaType);
    sk_sp<SkSurface> surface = SkSurfaces::WrapPixels(info, framebuffer, width * 4); // crash here
    return surface;
}
```

To reproduce it, please see https://github.com/xiaozhuai/vcpkg_demo/tree/master/src/skia
BTW, I customize my skia include path to `skia/*`, which is different with vcpkg's default `include/*`.

**Environment**
- OS: macOS 12.6.6 x86_64
- Compiler: Apple clang version 14.0.0 (clang-1400.0.29.202)  x86_64-apple-darwin21.6.0

**Comment by FrankXie05** [comment]
@xiaozhuai Could you please provide the error message?

**Comment by xiaozhuai** [comment]
@FrankXie05 There was no error message, it just crash. (interrupted by signal 10: SIGBUS)

**Comment by FrankXie05** [comment]
@xiaozhuai This is not a vcpkg problem, but more like a `skia` function usage problem. I can help you take a look at your code. Maybe you need to add some error checking mechanisms to analyze the specific cause of the crash. :)

**Comment by xiaozhuai** [comment]
@FrankXie05 @dg0yt @Osyotr 

The same code can run on windows, and can run on macos with release build type.

It crash on macos with debug build type.

So, it shouldn't be a usage problem. Maybe it's a upstream bug or something.

**Comment by Osyotr** [comment]
"It crashes" is a very vague statement. At least post call stack at the time of crash...
Also check whether manually built skia works as expected.

**Comment by dg0yt** [comment]
Is this dynamic linkage or static linkage? It could be picking of wrong link libs or runtime libs, as a port bug.

**Comment by xiaozhuai** [comment]
> Is this dynamic linkage or static linkage?

Static. I use `x64-osx` triplet

**Comment by xiaozhuai** [comment]
> At least post call stack at the time of crash...

Since I've already post the way to reproduce it, so I didn't provide the call stack.
![image](https://github.com/microsoft/vcpkg/assets/4773701/3e79466b-6d6d-4979-a22e-fcf2379e68f4)
