### ISSUE TITLE
[vcpkg tool] will not compile

### ISSUE THREAD

**Issue by StarGate-One** [microsoft/vcpkg#35496]
**Describe the bug**

**Environment**
- OS: [Windows 11][10.0.22631.2787] 23H2
- Compiler:
- Visual Studio Community 2022 Version: [17.8.2]  VS Tools Version: [14.38.33130] 
Microsoft (R) C/C++ Optimizing Compiler Version [19.38.33130] for x64 
- Vcpkg Version: [2023-12-01-4771b64dc88f8e40b62620d6565ca523fbc4ebe9]  (latest commit as of 20231204 22:28 Eastern US)

**To Reproduce**
1. Build vcpkg tool with CMake as follows:
"%_VCPKG_CMAKE_EXE%"                                           ^
   -A %VSCMD_ARG_TGT_ARCH%                                      ^
   -B "%_VCPKG_TOOL_BUILD_DIR%"                                 ^
   -S %_VCPKG_TOOL_DIR%                                         ^
   -G %_VCPKG_CMAKE_GEN%                                        ^
   -T %_VCPKG_PLATFORM_TOOLSET%                                 ^
   -DBUILD_TESTING=OFF                                          ^
   -DBUILD_TESTS=OFF                                            ^
   -DCMAKE_BUILD_TYPE=Release                                   ^
   -DCMAKE_VERBOSE_MAKEFILE=ON                                  ^
   -DCMAKE_INSTALL_PREFIX:PATH=%_VCPKG_ROOT_DIR%                ^
   -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded                   ^
   -DVCPKG_ARTIFACTS_DEVELOPMENT="OFF"                          ^
  "-DVCPKG_BASE_VERSION=%_VCPKG_TOOL_LATEST_TAG_REFNAME_DATE%"  ^
   -DVCPKG_BUILD_FUZZING=OFF                                    ^
   -DVCPKG_BUILD_TLS12_DOWNLOADER=OFF                           ^
  "-DVCPKG_CMAKERC_URL=%_VCPKG_CMAKERC_URL%"                    ^
   -DVCPKG_DEVELOPMENT_WARNINGS=ON                              ^
   -DVCPKG_EMBED_GIT_SHA=ON                                     ^
  "-DVCPKG_FMT_URL=%_VCPKG_FMT_URL%"                            ^
   -DVCPKG_MSVC_ANALYZE=OFF                                     ^
   -DVCPKG_OFFICIAL_BUILD=ON                                    ^
  "-DVCPKG_STANDALONE_BUNDLE_SHA=%_VCPKG_TOOL_CE_SHA%"          ^
   -DVCPKG_VERSION=%_VCPKG_TOOL_CE_SHA%                         ^
   -DVCPKG_WARNINGS_AS_ERRORS=ON
3. Compile vcpkg tool with CMake as follows:
"%_VCPKG_CMAKE_EXE%"                 ^
   --build %_VCPKG_TOOL_BUILD_DIR%    ^
   --clean-first                      ^
   --config release                   ^
   --parallel %VCPKG_MAX_CONCURRENCY% ^
   --target vcpkg                     ^
   --verbose
3. See error
>     3>Done Building Project "D:\vcpkg-work\build\vcpkglib.vcxproj" (default targets) -- FAILED.
>     1>Done Building Project "D:\vcpkg-work\build\vcpkg.vcxproj" (default targets) -- FAILED.
>
> Build FAILED.
>
>       "D:\vcpkg-work\build\vcpkg.vcxproj" (default target) (1) ->
>       "D:\vcpkg-work\build\vcpkglib.vcxproj" (default target) (3) ->
>       (ClCompile target) ->
>         D:\vcpkg-tool\src\vcpkg\commands.install.cpp(530,63): error C2039: 'displayname': is not a member of 'vcpkg::BinaryPar  agraph' [D:\vcpkg-work\build\vcpkglib.vcxproj]
>         D:\vcpkg-tool\src\vcpkg\commands.install.cpp(530,22): error C2665: 'vcpkg::msg::println': no overloaded function could         convert all the argument types [D:\vcpkg-work\build\vcpkglib.vcxproj]
>
>    0 Warning(s)
>    2 Error(s)
>
> Time Elapsed 00:00:58.03

**Expected behavior**
vcpkg tool should compile into executable binary.

**Failure logs**
-See attached [vcpkg-tool.log](https://github.com/microsoft/vcpkg/files/13554751/vcpkg-tool.log)

**Additional context**
None.

**Comment by jimwang118** [comment]
Sorry, I use cimmitID ebae9fc6c3cff1abb655619fcbc77d058024eeaf code, and the problem does not reproduce when I use the compilation command you provided locally.
![image](https://github.com/microsoft/vcpkg/assets/122244446/f825db1d-bd60-4ec9-b613-affa1b90f1a4)

**Comment by autoantwort** [comment]
Fixed by https://github.com/microsoft/vcpkg-tool/pull/1296

**Comment by StarGate-One** [comment]
Works as advertised - thank you @autoantwort @BillyONeal @LilyWangL @jimwang118 

You all do great work to keep vcpkg going.
