### ISSUE TITLE
Add Botan

### ISSUE THREAD

**Issue by bangusi** [Microsoft/vcpkg#355]
Botan is a cryptography library written in C++11 and released under the permissive Simplified BSD license.
https://github.com/randombit/botan

Botan’s goal is to be the best option for cryptography in new C++ code by offering the tools necessary to implement a range of practical systems, such as TLS/DTLS, PKIX certificate handling, PKCS#11 and TPM hardware support, password hashing, and post quantum crypto schemes.

**Comment by gnome71** [comment]
I just took a look at this lib too. Would be nice to have it.

**Comment by Mixaill** [comment]
Please check #773
