### ISSUE TITLE
[boost-exception] (and other Boost libs) fail to build with debug-only triplet: "No libraries were produced."

### ISSUE THREAD

**Issue by otto-liljalaakso-nt** [microsoft/vcpkg#35500]
Package: boost-exception:x64-windows-debug -> 1.83.0

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.29.30146.0
-    vcpkg-tool version: 2023-06-22-f19f3d9939100085fe2f7e41502d60b08e2083b6
    vcpkg-scripts version: 72010900b 2023-12-04 (5 hours ago)

**To Reproduce**
Save this triplet that only build debug configuration as `x64-windows-debug.cmake` in the current working directory:
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_BUILD_TYPE debug)
```

Try to build `boost-exception` with it:
`vcpkg --triplet=x64-windows-debug --host-triplet=x64-windows-debug --overlay-triplets=. install boost-exception`

**Failure logs**

```
-- Using cached boostorg-exception-boost-1.83.0.tar.gz.
-- Cleaning sources at D:/src/external/vcpkg/buildtrees/boost-exception/src/ost-1.83.0-e0db41e4c0.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/src/external/vcpkg/downloads/boostorg-exception-boost-1.83.0.tar.gz
-- Using source at D:/src/external/vcpkg/buildtrees/boost-exception/src/ost-1.83.0-e0db41e4c0.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows-debug
-- Configuring x64-windows-debug
-- Building x64-windows-debug-dbg
CMake Error at installed/x64-windows-debug/share/boost-build/boost-modular-build.cmake:198 (message):
  No libraries were produced.  This indicates a failure while building the
  boost library.
Call Stack (most recent call first):
  ports/boost-exception/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:170 (include)
```

**Additional context**
If I add an exception to triplet so that this particular library is also build as release, the build succeeds:
```
if(PORT STREQUAL "boost-exception")
    unset(VCPKG_BUILD_TYPE)
endif()
```
But there are many other Boost libraries that suffer from the same problem, for example `boost-regex`.

**Comment by otto-liljalaakso-nt** [comment]
Sorry, I got the bug report template from the build with our locked vcpkg version. But the same also happens when I use the newest `master`:

```
> .\vcpkg.exe version
vcpkg package management program version 2023-11-16-4c1df40a3c5c5e18de299a99e9accb03c2a82e1e
```

**Comment by JonLiu1993** [comment]
@otto-liljalaakso-nt, thanks for posting this issue, I saw that this error is designed like this. When you only compile for debug, it will definitely cause this error.
https://github.com/microsoft/vcpkg/blob/72010900b7cee36cea77aebb97695095c9358eaf/ports/boost-modular-build-helper/boost-modular-build.cmake#L197-L199

**Comment by Osyotr** [comment]
`VCPKG_BUILD_TYPE debug` is fundamentally broken; use `VCPKG_BUILD_TYPE release` with debug flags instead.

**Comment by otto-liljalaakso-nt** [comment]
Thank you for the responses. I gather what I attempted to do was a bad idea. This is regrettable, because building only debug would be very useful for development use cases: I would like to use debug builds in development, and hand responsibility for dependency rebuilds to vcpkg, and reduce build times by omitting the release build. Since this does not work, I will just keep building and not using the release builds.

Since it looks like this issue will not result in any action, I close this now.
