### ISSUE TITLE
[openssl] Build error on x64-windows

### ISSUE THREAD

**Issue by BKingB** [microsoft/vcpkg#35503]
Copy issue body from F:/WA/测试工具/Visual Studio/vcpkg-master/installed/vcpkg/issue_body.md

**Comment by autoantwort** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report an issue.

**Comment by Adela0814** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
