### ISSUE TITLE
[icu] Build error on x64-linux

### ISSUE THREAD

**Issue by PharaEthan** [microsoft/vcpkg#35514]
-- Running vcpkg install - failed
CMake Error at 3rd-party/Vcpkg/scripts/buildsystems/vcpkg.cmake:899 (message):
  vcpkg install failed.  See logs for more information:
  /home/Phara/Documents/Epitech/tek3/semester5/CPP/R-Type/build/vcpkg-manifest-install.log
Call Stack (most recent call first):
  build/CMakeFiles/3.27.20231001-g7ab8804/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:3 (project)

**Comment by autoantwort** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report an issue.
