### ISSUE TITLE
Adding SpaceLib (SL) library

### ISSUE THREAD

**Issue by ajaspe** [Microsoft/vcpkg#3551]
Hello! Spaceland Lib (sl) is a C++ template-based suite for geometric computation (specifically adapted to OpenGL). It is developed and maintained by ViC group in CRS4 since 2001 (http://www.crs4.it/vic/download/)

I would like to add a port for it, as we are releasing open source project based on this lib. I already have a port file for it, ready for a PR. Should I proceed?

**Comment by ras0219-msft** [comment]
Definitely!

`sl` is such a short name that it's likely to conflict, so please submit a longer name like `spacelib` or `spacelandlib` or `spaceland` :)

**Comment by ajaspe** [comment]
Ok! I will upload it as spaceland. But do you think it could be a problem installing all the header files on "include/sl" ? That is the way all the projects use to look for them.

**Comment by ajaspe** [comment]
The new port file for Spaceland Library has been submitted and merged.
