### ISSUE TITLE
[libmount] Build error on x64-linux

### ISSUE THREAD

**Issue by JuleProjects** [microsoft/vcpkg#35539]
Package: libmount:x64-linux -> 2.38#2

**Host Environment**

- Host: x64-linux
- Compiler: GNU 9.4.0
-    vcpkg-tool version: 2023-11-16-4c1df40a3c5c5e18de299a99e9accb03c2a82e1e
    vcpkg-scripts version: 45f6e57d3 2023-12-06 (2 hours ago)

**To Reproduce**

`vcpkg install sdl2`
**Failure logs**

```
-- Using cached util-linux-2.38.tar.xz.
-- Cleaning sources at /home/jule/lib/vcpkg/buildtrees/libmount/src/2.38-22af6c1200.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/jule/lib/vcpkg/downloads/util-linux-2.38.tar.xz
-- Using source at /home/jule/lib/vcpkg/buildtrees/libmount/src/2.38-22af6c1200.clean
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Generating configure for x64-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/autoreconf -vfi
    Working Directory: /home/jule/lib/vcpkg/buildtrees/libmount/src/2.38-22af6c1200.clean/
    Error code: 1
    See logs for more information:
      /home/jule/lib/vcpkg/buildtrees/libmount/autoconf-x64-linux-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:629 (vcpkg_execute_required_process)
  ports/libmount/portfile.cmake:19 (vcpkg_configure_make)
  scripts/ports.cmake:170 (include)



```
<details><summary>/home/jule/lib/vcpkg/buildtrees/libmount/autoconf-x64-linux-err.log</summary>

```
autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
Can't exec "autopoint": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 345.
autoreconf: failed to run autopoint: No such file or directory
autoreconf: autopoint is needed because this package uses Gettext
```
</details>

**Comment by FrankXie05** [comment]
@JuleProjects Please try run command `sudo apt-get install autopoint (maybe also need libtool)`.

**Comment by dg0yt** [comment]
> @JuleProjects Please try run command `sudo apt-get install autopoint (maybe also need libtool)`.

NO. Not autopoint. You need autoconf. And maybe automake. And maybe autoconf-archive.

**Comment by AenBleidd** [comment]
I had the same issue. Actually, only after installing `autopoint` this error disappeared

**Comment by dg0yt** [comment]
Indeed. However, this can be fragile for some ports. And it implies that the port has an issue with dependencies.

**Comment by geo-ant** [comment]
> @JuleProjects Please try run command `sudo apt-get install autopoint (maybe also need libtool)`.

I had to install `autoconf`, `autopoint`, and `libtool` as well. Thank you!
