### ISSUE TITLE
Cannot open source file when using toolset v140 in VS2017

### ISSUE THREAD

**Issue by ustcfdm** [Microsoft/vcpkg#3553]
I have installed [rapidjson](http://rapidjson.org/) with vcpkg.  In my vs2017, I add a C++ project, and include rapidjson library
`#include "rapidjson/document.h`
Everything works fine for now. However, if I change the project platform toolset into v140, the editor shows that it cannot open source file "rapidjson/document.h". 
![image](https://user-images.githubusercontent.com/12667807/40332851-431afcde-5d1b-11e8-8062-3e2bb952394f.png)

I tried to fix this problem. In folder triplets, I made a new file x64-windows-v140.cmake, the content is

    set(VCPKG_TARGET_ARCHITECTURE x64) 
    set(VCPKG_CRT_LINKAGE dynamic)
    set(VCPKG_LIBRARY_LINKAGE dynamic)
    set(VCPKG_PLATFORM_TOOLSET v140)

Then I install vcpkg by typing `vcpkg.exe install rapidjson:x64-windows-v140`
However, I found this method still did not work. Did I miss something?

**Comment by Voskrese** [comment]
Do not confuse vcpkg and Visual Studio

vcpkg.exe install rapidjson:x64-windows

triplets x64-windows\\MD and x64-windows-static\\MT

**Comment by ustcfdm** [comment]
@Voskrese Thanks for your help! But I don't get the point. What does `triplets x64-windows\MD\ and x64-windows-static\MT\` and how to use it? Could you please be more specific?

**Comment by Voskrese** [comment]
vcpkg integrate install

compile in Visual Studio

ok ))

**Comment by ustcfdm** [comment]
@Voskrese I have used command `vcpkg integrate install` when I installed vcpkg. It works well in my Visual C++ project. But this only works if my Visual C++ project uses toolset v141. If I changed it to v140, it cannot find rapidjson source file.

**Comment by Voskrese** [comment]
Strangely, overriding toolchain should not affect the integration of vkpkg. It is necessary to look through log files, their output

**Comment by carmangary** [comment]
Open up the vcproj file and with a text editor.  You will need to modify it so that it recognizes your new triplet.  vcpkg integrate install only adds the x86-windows and x64-windows integration.  Anything else must be done manually.

**Comment by ustcfdm** [comment]
@Voskrese This is output when I build the project.

    1>------ Build started: Project: Project2, Configuration: Debug x64 ------
    1>Source.cpp
    1>c:\users\mfeng\desktop\project2\project2\source.cpp(1): fatal error C1083: Cannot open include file: 'rapidjson/document.h': No such file or directory
    1>Done building project "Project2.vcxproj" -- FAILED.
    ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

The code is 

    #include "rapidjson/document.h"
    
    #include <iostream>
    
    int main()
    {
    	std::cout << "test" << std::endl;
    
    	getchar();
    	return 0;
    }

**Comment by carmangary** [comment]
Open up the .vcprojx file with notepad.  Look for "x86-windows" and replace it with your custom triplet.  vcpkg integrate install only adds support for x86-windows and x64-windows so you will need to manually modify the proj file for anything else.  That's all there is to it.  vcpkg team should make it so that integration works better.

**Comment by PhoebeHui** [comment]
@ustcfdm, does the issue persist? I tried an example, it looks everything works well. Is the steps you tried?

1. PS F:\vcpkg\src> .\vcpkg install rapidjson:x64-windows
2. PS F:\vcpkg\src> .\vcpkg integrate install
3. Create example folder and put example.cpp and CMakeLists.txt under it.
// example.cpp:
#include <iostream>
#include "rapidjson/document.h"

int main(int argc, char *argv[])
{
    return 0;
}

//CMakeLists.txt
cmake_minimum_required(VERSION 3.0)
project(example)
find_package(RapidJSON CONFIG REQUIRED)
add_executable(example example.cpp)
 target_include_directories(example PRIVATE ${RAPIDJSON_INCLUDE_DIRS})

4. Create build folder and execute 
cmake.exe -DCMAKE_TOOLCHAIN_FILE=F:/vcpkg/src/scripts/buildsystems/vcpkg.cmake   -G "Visual Studio 15 2017 Win64" ..\example
5. Open generated example.sln, and build it, it build successfully, then change Visual Studio 2017 (v141) 
 to Visual Studio 2015 (v140), and rebuild it, it also build successfully.

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
