### ISSUE TITLE
[tiff] build failure when not found liblzma::liblzma

### ISSUE THREAD

**Issue by Goreek** [microsoft/vcpkg#35554]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
`.\vcpkg.exe install tiff`
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
    tiff[core,jpeg,lzma,zip]:x64-windows -> 4.6.0#1
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\goree\AppData\Local\vcpkg\archives in 1.75 ms. Use --debug to see more details.
Installing 1/1 tiff:x64-windows...
Building tiff[core,jpeg,lzma,zip]:x64-windows...
-- Using cached libtiff-libtiff-v4.6.0.tar.gz.
-- Cleaning sources at C:/Develop/vcpkg/buildtrees/tiff/src/v4.6.0-ba2cf5b685.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Develop/vcpkg/downloads/libtiff-libtiff-v4.6.0.tar.gz
-- Applying patch FindCMath.patch
-- Using source at C:/Develop/vcpkg/buildtrees/tiff/src/v4.6.0-ba2cf5b685.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/Develop/vcpkg/buildtrees/tiff/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Develop\vcpkg\buildtrees\tiff\config-x64-windows-dbg-CMakeCache.txt.log
      C:\Develop\vcpkg\buildtrees\tiff\config-x64-windows-rel-CMakeCache.txt.log
      C:\Develop\vcpkg\buildtrees\tiff\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:252 (vcpkg_execute_required_process)
  ports/tiff/portfile.cmake:28 (vcpkg_cmake_configure)
  scripts/ports.cmake:170 (include)

### Additional context

In the file  .\buildtrees\tiff\config-x64-windows-out.log

```
CMake Error at libtiff/CMakeLists.txt:157 (target_link_libraries):
  Target "tiff" links to:

    liblzma::liblzma

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

```
I see that Liblzma port was build successfully.
It even installed the file `.\installed\x64-windows\share\liblzma\LibLZMAConfig.cmake`  that declares liblzma::liblzma presence.
But tiff port does not use it. It can find liblzma without namespace. But with namespace (liblzma::liblzma) it doesn't work.

**Comment by FrankXie05** [comment]
@Goreek Could you please run command ` ./vcpkg remove tiff:x64-windows --recurse `and try again?
