### ISSUE TITLE
Setting default-features with false does not work in a port's vcpkg.json

### ISSUE THREAD

**Issue by BewareMyPower** [microsoft/vcpkg#35555]
**Describe the bug**
I tried to contribute a new port and I'm testing it locally. In my project, the `curl` depends on `openssl` but in Vcpkg `curl` depends on `sectransp` by default on OSX. I tried setting `"default-features": "false"` but it does not work. 

**Environment**
- OS: macOS m1 Ventura 13.4.1
- Compiler: revision

**To Reproduce**

Create `port/xyz/vcpkg.json`:

```json
{
  "name": "xyz",
  "version": "1.0.0",
  "description": "...",
  "homepage": "https://github.com/microsoft/vcpkg-docs",
  "license": "Apache-2.0",
  "dependencies": [
    {
      "name": "vcpkg-cmake",
      "host": true
    },
    {
      "name": "vcpkg-cmake-config",
      "host": true
    },
    {
      "name": "curl",
      "default-features": false
    }
  ]
}
```

Then I ran `vcpkg install xyz`:

```
The following packages will be built and installed:
  * curl[core,non-http,sectransp,ssl]:arm64-osx -> 8.4.0
  * vcpkg-cmake:arm64-osx -> 2023-05-04
  * vcpkg-cmake-config:arm64-osx -> 2022-02-06#1
    xyz:arm64-osx -> 1.0.0
  * zlib:arm64-osx -> 1.3
```

As you can see, all the default features (`core,non-http,sectransp,ssl`) of curl were still installed.

**Expected behavior**
The default features should not be installed.

**Failure logs**
-(please attached failure logs)

**Additional context**

I tried a simple project with the similar vcpkg.json in manifest mode and it does not install the default features

**Comment by dg0yt** [comment]
Works as designed by the project owners.

The expected behaviour is supported for *manifests in user projects*.
But in a *port*, `"default-features": false` has a different meaning: It just enables control by the user, i.e.
- If the user doesn't specify anything (in command line or user project manifest), vcpkg installs default features.
- If the user specifies `"default-features": false` (in manifests) or `[core]` (in command line) for the respective port, the default features are no longer installed (unless required by another port).

**Comment by BewareMyPower** [comment]
I tried `./vcpkg install xyz[core]` but still saw default features were installed.

```
% ./vcpkg install 'xyz[core]'                                                                                
Computing installation plan...
The following packages will be built and installed:
  * curl[core,non-http,sectransp,ssl]:arm64-osx -> 8.4.0
  * vcpkg-cmake:arm64-osx -> 2023-05-04
  * vcpkg-cmake-config:arm64-osx -> 2022-02-06#1
    xyz:arm64-osx -> 1.0.0
  * zlib:arm64-osx -> 1.3
```

Is there any way to avoid installing default features of `curl`?

**Comment by dg0yt** [comment]
> I tried `./vcpkg install xyz[core]` but still saw default features were installed.

Your command line ("user") didn't specify anything about curl. What you need is:

~~~
./vcpkg install xyz[core] curl[core]
~~~

The effect of `curl[core]` is what is enabled by xyz's `vcpkg.json`. If it hadn't  `"default-features": false`, it would depend on the default features.
