### ISSUE TITLE
build a private library: Build Failed with POST_BUILD_CHECKS_FAILED

### ISSUE THREAD

**Issue by pankit7** [microsoft/vcpkg#3556]
I was building a private library (open-simulation-interface) using the vcpkg platform by creating a new portfile. 
While the entire build process went smoothly and built the required libraries, I still receive 1 error 
`Error: Building package open-simulation-interface:x64-windows failed with: POST_BUILD_CHECKS_FAILED`
`The following DLLs have no exports: xxxx.dll`
`DLLs without any exports are likely a bug in the build script.`

Is there any option which makes it generate the necessary dllexport option?

**Comment by NancyLi1013** [comment]
Hi @pankit7 

Thanks for posting this issue.
Could you please provide portfile.cmake and CONTROL files for this port?

**Comment by NancyLi1013** [comment]
Please feel free to reopen this or open a new issue if this is still a problem for you.
