### ISSUE TITLE
Building with Cygwin to build with MSVC

### ISSUE THREAD

**Issue by SamuelMarks** [microsoft/vcpkg#35573]
**Describe the bug**
Porting this GNU software https://www.gnu.org/software/libsigsegv and it requires GNU autotools to generate all the right files which can then be used to build with MSVC toolchain.

**Environment**
- OS: Windows
- Compiler: MSVC

---

What's the recommended way to get this port built using your CI/CD and regular vcpkg build toolchain?

**Comment by dg0yt** [comment]
Normally it is enough to use vcpkg_configure_make etc.
vcpkg uses msys2 instead of pristine cygwin.

**Comment by SamuelMarks** [comment]
Forgot to include the links

-  #35144
- https://git.savannah.gnu.org/gitweb/?p=libsigsegv.git;a=blob;f=INSTALL.windows;h=b41d0123592a89f33595f395625752fe103333dc;hb=HEAD

**Comment by SamuelMarks** [comment]
Forgot to include the links

-  #35144
- https://git.savannah.gnu.org/gitweb/?p=libsigsegv.git;a=blob;f=INSTALL.windows;h=b41d0123592a89f33595f395625752fe103333dc;hb=HEAD

Is there a good example port to work from?

Thanks

**Comment by dg0yt** [comment]
> Is there a good example port to work from?

Maybe port `attr` or `libexif`.
