### ISSUE TITLE
'integrate install' installs wrong triplet.

### ISSUE THREAD

**Issue by ShiftZ** [microsoft/vcpkg#35572]
I have packages installed with two different triplets: x64-windows and x64-windows-static-md.
The default triplet is set to x64-windows-static-md by env. variable.
When I 'integrate install' it always 'installs' the x64-windows triplet to MSBuild instead of x64-windows-static-md. 
If I provide the desired triplet explicitely as an argument to the command '--triplet=x64-windows-static-md' it still uses x64-windows triplet. 
It seems there's no way to force it to install the desired x64-windows-static-md triplet.

**Comment by autoantwort** [comment]
`x64-windows` is the host triplet. You can set the env var [`VCPKG_DEFAULT_HOST_TRIPLET`](https://learn.microsoft.com/en-us/vcpkg/users/config-environment#vcpkg_default_host_triplet)

**Comment by ShiftZ** [comment]
> `x64-windows` is the host triplet. You can set the env var [`VCPKG_DEFAULT_HOST_TRIPLET`](https://learn.microsoft.com/en-us/vcpkg/users/config-environment#vcpkg_default_host_triplet)
Why 'integrate install' uses host triplet while package installation uses target triplet?

**Comment by autoantwort** [comment]
`integrate install` does not use any triplet. It only integrates vcpkg in visual studio. 

Maybe set target triplet gets set in the settings in VS and the env var is not used.

**Comment by ShiftZ** [comment]
> `integrate install` does not use any triplet. It only integrates vcpkg in visual studio.
> 
> Maybe set target triplet gets set in the settings in VS and the env var is not used.

I'm confused. After 'integrate install' **only** includes from the host triplet folder (x64-windows) are available in VS. I'm struggling to see the reason why it's host triplet forlder instead of target triplet folder. Is it intended design?

**Comment by autoantwort** [comment]
Can you show an screenshot of the vcpkg settings in VS of your msbuild project?

**Comment by dg0yt** [comment]
The host triplet is always used for things that are needed once per host, or which must run on the host during for the build.

**Comment by ShiftZ** [comment]
> Can you show a screenshot of the vcpkg settings in VS of your msbuild project?

<img width="591" alt="image" src="https://github.com/microsoft/vcpkg/assets/3416569/c9e927d4-7d13-4257-b24c-38e14c51ae8c">


> The host triplet is always used for things that are needed once per host, or which must run on the host during for the build.
I don't see how it explains why 'integrate install' makes 'includes' avaialble only from packages in 'x64-windows' folder. Correct me if I'm wrong, 'integrate install''s primary objective is to make avaialble includes, libriaries and dynamic load binaries. Nothing of these things are supposed to run on the host.

**Comment by autoantwort** [comment]
I think if you don't set the triplet in the ui of the screenshot it defaults to `x64-windows` and don't uses the env var. So you have to set _Use Static Libraries_ to _Yes_ and _Use Dynamic CRT_ also to _Yes_

**Comment by jimwang118** [comment]
@ShiftZ Is your problem solved now?

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
