### ISSUE TITLE
[openssl] Build error on x64-windows

### ISSUE THREAD

**Issue by RainbowTaro2022** [microsoft/vcpkg#35588]
F:\vcpkg>vcpkg install openssl
warning: In the September 2023 release, the default triplet for vcpkg libraries changed from x86-windows to the detected host triplet (x64-windows). For the old behavior, add --triplet x86-windows . To suppress this message, add --triplet x64-windows .
Computing installation plan...
The following packages will be built and installed:
    openssl:x64-windows -> 3.1.4#1
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\zimin\AppData\Local\vcpkg\archives in 145 us. Use --debug to see more details.
Installing 1/1 openssl:x64-windows...
Building openssl:x64-windows...
CMake Error at installed/x64-windows/share/vcpkg-cmake-get-vars/vcpkg-port-config.cmake:1 (include):
  include could not find requested file:

    F:/vcpkg/installed/x64-windows/share/vcpkg-cmake-get-vars/../vcpkg-cmake/vcpkg-port-config.cmake
Call Stack (most recent call first):
  scripts/ports.cmake:163 (include)

error: building openssl:x64-windows failed with: BUILD_FAILED
Elapsed time to handle openssl:x64-windows: 491 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[openssl]+Build+error+on+x64-windows&body=Copy+issue+body+from+F%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

F:\vcpkg>vcpkg install openssl
Could not locate a manifest (vcpkg.json) above the current working directory.
This vcpkg distribution does not have a classic mode instance

**Comment by dg0yt** [comment]
Update the installed packages:
~~~
vcpkg upgrade
vcpkg upgrade --no-dry-run
~~~

**Comment by RainbowTaro2022** [comment]
error: Could not locate a manifest (vcpkg.json) above the current working directory.
This vcpkg distribution does not have a classic mode instance

**Comment by dg0yt** [comment]
> error: Could not locate a manifest (vcpkg.json) above the current working directory. This vcpkg distribution does not have a classic mode instance

By just typing `vcpkg`, you probaly run some limited variant from Visual Studio.
To run the latest tool bootstrapped into a git checkout of vpckg, you would type `.\vcpkg` in the Windows world.

**Comment by RainbowTaro2022** [comment]
CMake Error at installed/x64-windows/share/vcpkg-cmake-get-vars/vcpkg-port-config.cmake:1 (include):
  include could not find requested file:

    F:/vcpkg/installed/x64-windows/share/vcpkg-cmake-get-vars/../vcpkg-cmake/vcpkg-port-config.cmake
Call Stack (most recent call first):
  scripts/ports.cmake:163 (include)

**Comment by RainbowTaro2022** [comment]
CMake Error at ports/liblzma/portfile.cmake:23 (vcpkg_cmake_configure):
  Unknown CMake command "vcpkg_cmake_configure".
Call Stack (most recent call first):
  scripts/ports.cmake:170 (include)

**Comment by dg0yt** [comment]
https://github.com/microsoft/vcpkg/issues/35588#issuecomment-1848995637

**Comment by RainbowTaro2022** [comment]
Unknown CMake command "vcpkg_cmake_configure".

**Comment by RainbowTaro2022** [comment]
i don't know

**Comment by RainbowTaro2022** [comment]
sorry

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
