### ISSUE TITLE
[opencv4] Build error on x64-windows

### ISSUE THREAD

**Issue by cycmika0629** [microsoft/vcpkg#35590]
Copy issue body from D:/vcpkg/vcpkg/installed/vcpkg/issue_body.md

**Comment by jimwang118** [comment]
Please see [30604](https://github.com/microsoft/vcpkg/issues/30604) for how to report an issue.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
