### ISSUE TITLE
[qtbase] Add feature for gtk3 support on Linux

### ISSUE THREAD

**Issue by MB3hel** [microsoft/vcpkg#35594]
### Is your feature request related to a problem? Please describe.

Since QT 6.5, when running on gtk based Linux desktops (eg GNOME) QT apps will match the color scheme of the active gtk3 theme. This requires building QT with FEATURE_gtk3.

### Proposed solution

Add "gtk3" feature (available on Linux platforms) which builds with FEATURE_gtk3 cmake variable set. This would likely be good to include by default for Linux builds (as this matches official QT packages).

### Describe alternatives you've considered

Apps don't match color scheme. This is particularly noticeable if using a dark theme. QT apps built using QT from vcpkg will be light. Doesn't break functionality, but is not what is expected by end users or developers expecting behavior matching official packages.

### Additional context

If this is something that would be accepted, I can implement and make a PR.

**Comment by JonLiu1993** [comment]
@Neumann-A, I would like to ask, is it reasonable to add this function?
````
but is not what is expected by end users or developers expecting behavior matching official packages.
````

**Comment by MB3hel** [comment]
Perhaps my original phrasing is unclear. The official QT builds **are** built with gtk3 support. Vcpkg, however, does not build with this feature (not by default and there is no way to enable it).

Thus, building an example with official QT packages, the app matches gtk3 theme colors on GNOME
![image](https://github.com/microsoft/vcpkg/assets/13546893/fadd608f-8e26-432a-a4d3-46dd4d6f9e5d)

However, building the same example with QT from vcpkg results in no color matching on GNOME
![image](https://github.com/microsoft/vcpkg/assets/13546893/3271ed78-8e7d-4bf7-93b5-7ced9d03d186)

I can understand an argument for not enabling by default (as some users of the vcpkg builds may not expect this change, which can have a significant impact on unaware apps), however I feel there should at least be an option to enable this feature.

**Comment by Neumann-A** [comment]
You can just pass -DFEATURE_gtk3=ON or make a vcpkg feature for it if it requires additional dependency. I dont think vcpkg is controlling this feature currently and is only using the default qt sets it to.

**Comment by MB3hel** [comment]
Vcpkg is currently not controlling the feature. I'm not sure how QT decides to build with or without GTK3 support, but it can be enabled by setting the cmake variable mentioned.

My questions were mostly 

1. Would such a feature be accepted in a PR? If so I can add a feature named `gtk3` and make a PR.
2. Should such a feature be included in the default features for Linux? This would match what official builds of QT do, but introduce more dependencies (namely gtk3, glib, etc).

**Comment by Neumann-A** [comment]
Do as you like but don't make it the default.
