### ISSUE TITLE
Add libstudxml

### ISSUE THREAD

**Issue by bangusi** [microsoft/vcpkg#356]
libstudxml is a streaming XML pull parser and streaming XML serializer implementation for modern, standard C++. 
libstudxml is free, open-source software; you can use, distribute, and/or modify it under the terms of the MIT License.
http://www.codesynthesis.com/download/libstudxml/1.0/libstudxml-1.0.1.tar.gz

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
