### ISSUE TITLE
[expat] Build error on x64-linux

### ISSUE THREAD

**Issue by LeeHuangLe** [microsoft/vcpkg#35602]
Copy issue body from /home/lehuang/Poker/Poker/external/vcpkg/installed/vcpkg/issue_body.md

**Comment by autoantwort** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report an issue.

**Comment by MonicaLiu0311** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
