### ISSUE TITLE
[skia] missing webgpu headers when enabling dawn

### ISSUE THREAD

**Issue by abique** [microsoft/vcpkg#35606]
### Is your feature request related to a problem? Please describe.

Currently, it is possible to enable dawn for skia, but we don't have the corresponding headers used for webgpu.

### Proposed solution

Would it be possible to ship the web gpu headers used to compile dawn?

**Comment by dg0yt** [comment]
> Would it be possible to ship the web gpu headers used to compile dawn?

Are these headers a public dependency, i.e. needed to use dawn with skia?
(This would show as a downstream compile error.)
Or are they needed separately?
(Candidate for a separate port.)

**Comment by abique** [comment]
I think we'd need a [dawn](https://dawn.googlesource.com/dawn) dependency first.

If I understand well, dawn is a webgpu implementation. So maybe we'd [webgpu-header](https://github.com/webgpu-native/webgpu-headers) first.

When I wrote this issue I didn't understand well all these new graphic stack layers.

I think dawn and webgpu are very interesting as a cross platform gpu solution.

**Comment by abique** [comment]
Maybe if you are able to target vulkan/d3d/metal then there is no need for dawn.
Apparently skia did consider dropping d3d backend: https://groups.google.com/g/skia-discuss/c/WY7yzRjGGFA?pli=1
It is not clear to me which backend to use when rendering with skia.

**Comment by dg0yt** [comment]
> When I wrote this issue I didn't understand well all these new graphic stack layers.

I face similar difficulties...

What I can say is that skia is a difficult port from a vcpkg POV. skia and its vendored dawn use gn which helps to mitigate some problems of vendored dependencies. And so the skia port still uses a lot of vendored dependencies which should be de-vendored for vcpkg. Which is hard to do, with moving versions and local customizations.
I tried to make the skia port (and it is gn utility functions) more open for contributions and explicit about it is vendored dependencies... It seems to have users, but maybe this isn't enough to make it a good port.

**Comment by abique** [comment]
I totally get you, similar troubles with tensorflow I gess.
I wish cairo had an easy GPU accelerated backend.

**Comment by dg0yt** [comment]
> I totally get you, similar troubles with tensorflow I gess.

tensorflow is worse: It is building a lot of stuff also for host tools. It is close to impossible to sort this out correctly in particular for MSVC which needs a different runtime for debug... I considered rewriting that port from scratch, transferring utility functions from skia for devendoring what is already available.
