### ISSUE TITLE
[rapidjson] Build error on x64-windows

### ISSUE THREAD

**Issue by StephenMay-enchannel** [microsoft/vcpkg#35612]
This failure is seen on a build pipeline, so C:/a/1/s/vcpkg_installed/x64-windows/vcpkg/issue_body.md is not easily accessible.

This is the text from the pipeline's log:
>  Installing 3/192 rapidjson:x64-windows...
  Building rapidjson:x64-windows...
  -- Installing port from location: C:\Users\AzDevOps\AppData\Local\vcpkg\registries\git-trees\9da8fa409b1afef5674fe412237db0504cf6156e
  -- Using cached Tencent-rapidjson-a95e013b97ca6523f32da23f5095fcc9dd6067e5-2.tar.gz.
  -- Extracting source C:/Users/AzDevOps/AppData/Local/vcpkg/downloads/Tencent-rapidjson-a95e013b97ca6523f32da23f5095fcc9dd6067e5-2.tar.gz
  -- Using source at C:/a/1/s/vcpkg_installed/x64-windows/vcpkg/blds/rapidjson/src/c9dd6067e5-8a215fc499.clean
  -- Found external ninja('1.11.0').
  -- Configuring x64-windows
##[debug]Agent running environment resource - Disk:C:\ Windows available:90962.00MB out of 129481.00MB, Memory: used 27MB out of 14284MB, CPU: usage 4.05
  -- Building x64-windows-dbg
  -- Building x64-windows-rel
  -- Using cached mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
  -- Downloading https://mirror.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst -> mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst...
  [DEBUG] To include the environment variables in debug output, pass --debug-env
  [DEBUG] Trying to load bundleconfig from C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg\vcpkg-bundle.json
  [DEBUG] Bundle config: readonly=true, usegitregistry=true, embeddedsha=638b1588be3a265a9c7ad5b212cef72a1cad336a, deployment=VisualStudio, vsversion=17.0
  [DEBUG] VS telemetry opted in at SOFTWARE\WOW6432Node\Microsoft\VSCommon\17.0\SQM\\OptIn
  [DEBUG] Metrics enabled.
  [DEBUG] Feature flag 'binarycaching' unset
  [DEBUG] Feature flag 'compilertracking' unset
  [DEBUG] Feature flag 'registries' unset
  [DEBUG] Feature flag 'versions' unset
  [DEBUG] Feature flag 'dependencygraph' unset
  Downloading https://mirror.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst
  Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst
  Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst
  Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst
  Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst
  Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst
##[warning]C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(183,5): Warning : error: Failed to download from mirror set
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
    scripts/cmake/vcpkg_acquire_msys.cmake:25 (vcpkg_download_distfile)
    scripts/cmake/vcpkg_acquire_msys.cmake:124 (z_vcpkg_acquire_msys_download_package)
    scripts/cmake/vcpkg_acquire_msys.cmake:209 (z_vcpkg_acquire_msys_download_packages)
    scripts/cmake/vcpkg_find_acquire_program(PKGCONFIG).cmake:22 (vcpkg_acquire_msys)
    scripts/cmake/vcpkg_find_acquire_program.cmake:118 (include)
    scripts/cmake/vcpkg_fixup_pkgconfig.cmake:203 (vcpkg_find_acquire_program)
    C:/Users/AzDevOps/AppData/Local/vcpkg/registries/git-trees/9da8fa409b1afef5674fe412237db0504cf6156e/portfile.cmake:27 (vcpkg_fixup_pkgconfig)
    scripts/ports.cmake:147 (include)
> 
>
>##[warning]C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(183,5): Warning : error: building rapidjson:x64-windows failed with: BUILD_FAILED
##[debug]Processed: ##vso[task.logissue type=Warning;sourcepath=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets;linenumber=183;columnnumber=5;code=;]error: building rapidjson:x64-windows failed with: BUILD_FAILED
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(183,5): warning : error: building rapidjson:x64-windows failed with: BUILD_FAILED [C:\a\1\s\vendor\libEsf\libEsf.vcxproj]
  Elapsed time to handle rapidjson:x64-windows: 5.1 s
  Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
  Then check for known issues at:
      https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+rapidjson
  You can submit a new issue at:
      https://github.com/microsoft/vcpkg/issues/new?title=[rapidjson]+Build+error&body=Copy+issue+body+from+C%3A%2Fa%2F1%2Fs%2Fvcpkg_installed%2Fx64-windows%2Fvcpkg%2Fissue_body.md
>  
>##[error]C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(183,5): Error MSB3073: The command ""C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg\vcpkg.exe" install  --x-wait-for-lock --triplet "x64-windows" --vcpkg-root "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg\\" "--x-manifest-root=C:\a\1\s\\" "--x-install-root=C:\a\1\s\vcpkg_installed\x64-windows\\" " exited with code 1.
##[debug]Processed: ##vso[task.logissue type=Error;sourcepath=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets;linenumber=183;columnnumber=5;code=MSB3073;]The command ""C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg\vcpkg.exe" install  --x-wait-for-lock --triplet "x64-windows" --vcpkg-root "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg\\" "--x-manifest-root=C:\a\1\s\\" "--x-install-root=C:\a\1\s\vcpkg_installed\x64-windows\\" " exited with code 1.
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(183,5): error MSB3073: The command ""C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg\vcpkg.exe" install  --x-wait-for-lock --triplet "x64-windows" --vcpkg-root "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg\\" "--x-manifest-root=C:\a\1\s\\" "--x-install-root=C:\a\1\s\vcpkg_installed\x64-windows\\" " exited with code 1. [C:\a\1\s\vendor\libEsf\libEsf.vcxproj]
##[debug]Processed: ##vso[task.logdetail id=b6680fdf-c143-47e5-ba1f-f42330293f27;parentid=b0cf22cd-26eb-44f6-99d4-52ac1c7d22e4;type=Build;result=Failed;finishtime=2023-12-11T21:54:52.3768001Z;progress=100;state=Completed;parentid=b0cf22cd-26eb-44f6-99d4-52ac1c7d22e4;name=;]

Following the links and playing around a little, it seems the libwinpthread version depended upon has been removed.

**Comment by StarGate-One** [comment]
The vcpkg in the CI is out of date and requires it to be updated:
`cd <vcpkg-root>
`git pull
`vcpkg upgrade --no-dry-run

See [[opentelemetry-cpp] opentelemetry-cpp uses outdated vcpkg #35516](https://github.com/microsoft/vcpkg/issues/35516)

**Comment by StephenMay-enchannel** [comment]
> The vcpkg in the CI is out of date and requires it to be updated: `cd <vcpkg-root>` `git pull` `.\bootstrap-vcpkg.bat` `vcpkg upgrade --no-dry-run`
> 
> See [[opentelemetry-cpp] opentelemetry-cpp uses outdated vcpkg #35516](https://github.com/microsoft/vcpkg/issues/35516)

My pipeline uses vcpkg in manifest mode. Should updating the builtin-baseline be sufficient? I tried doing so and got the same error. Or is there something else I should be doing to update the vcpkg?

**Comment by StarGate-One** [comment]
The vcpkg-tool (vcpkg.exe) and the vcpkg scripts, those found in `<vcpkg-root>/scripts`  need to be updated - has nothing to do with the builtin-baseline - the repo itself needs to be updated as stated above.

**Comment by StephenMay-enchannel** [comment]
Thanks for the clarification! Once I was able to update our build agent the builds started succeeding.
