### ISSUE TITLE
[libraw] port fails if VCPKG_BUILD_TYPE set to release only

### ISSUE THREAD

**Issue by 9prady9** [Microsoft/vcpkg#3561]
This is pretty similar to the issue https://github.com/Microsoft/vcpkg/issues/2345

**Comment by 9prady9** [comment]
There are couple of other packages that are failing as well. Should I open separate issues or Can I add a check list to this issue ?

**Comment by LarryIII** [comment]
@9prady9 I installed glbinding port successfully if VCPKG_BUILD_TYPE set to release only, no mater with X 64-windows or X86-windows. Could you please try again and close this issue if it your issue was resolved?

**Comment by 9prady9** [comment]
@LarryIII Thanks for checking and notifying me. Among the packages that gave me the problem, glbinding's problem is definitely resolved. However the other package I was referring in one of my previous comments, freeimage, still fails if the build type is set to `release` explicitly in the triplet file. Any suggestions how should we proceed ? perhaps rename the issue to reflect freeimage issue.

FYI - the following is the error
```powershell
-- Building x64-windows-rel
CMake Error at ports/ilmbase/portfile.cmake:28 (file):
  file must be called with at least two arguments.
Call Stack (most recent call first):
  scripts/ports.cmake:71 (include)


Error: Building package ilmbase:x64-windows failed with: BUILD_FAILED
```

**Comment by LarryIII** [comment]
@9prady9 Thanks for your reply. I did not get any failure about **ilmbase**, but I got libraw failed when building freeimage for release only. I have submitted a PR https://github.com/Microsoft/vcpkg/pull/5484, it will fix this issue soon. By the way, I renamed the issue title with [libraw] to track current block issue.

**Comment by LarryIII** [comment]
PR merged!

**Comment by 9prady9** [comment]
@LarryIII Thank you for taking care of it.
