### ISSUE TITLE
[sdl2] build failure

### ISSUE THREAD

**Issue by AbyssalDrifter** [microsoft/vcpkg#35641]
### Operating system

Windows 10

### Compiler

Visual Studio 2022 Preview with CMake

### Steps to reproduce the behavior

```Shell
I'm using the vcpkg.json file in my project so this doesn't include explicit vcpkg installs
```

### Failure logs

```
<snip>
1> [CMake] -- Running vcpkg install
1> [CMake] error: while loading D:\dev\MysticMotion\vcpkg\buildtrees\versioning_\versions\sdl2\46ab8ddbed64fe98dab84eb0d95b8bb6e6d2d531\vcpkg.json:
1> [CMake] $.default-features[0]: mismatched type: expected an identifier
1> [CMake] $.default-features[1]: mismatched type: expected an identifier
1> [CMake] $.default-features[2]: mismatched type: expected an identifierFailed to load port sdl2 from D:\dev\MysticMotion\vcpkg\buildtrees\versioning_\versions\sdl2\46ab8ddbed64fe98dab84eb0d95b8bb6e6d2d531
1> [CMake] note: updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
<snip>
```

### Additional context

vcpkg.json:
```json
{
  "name": "mystic-motion",
  "version": "0.0.1",
  "dependencies": [
    { "name": "fmt", "version>=": "10.1.1" },
    {
      "name": "curl",
      "features": ["brotli", "http2", "openssl"],
      "version>=": "8.4.0"
    },
    { "name": "nlohmann-json", "version>=": "3.11.3" },
    { "name": "sdl2", "version>=": "2.28.5#1" }
  ],
  "builtin-baseline": "c8696863d371ab7f46e213d8f5ca923c4aef2a00"
}

```

**Comment by jimwang118** [comment]
You update the vcpkg library locally and then run .\bootstrap-vcpkg.bat. Recompile your code.

**Comment by AbyssalDrifter** [comment]
@jimwang118 The process I'm using is a bit different since the vcpkg repo is checked out as a sub-module in my repo. Everything is handled automatically through the vcpkg.json and CMake so the bootstrapping is done automatically as far as I know. This has always worked it just seems that with this version of sdl2 it failed.

I'm already using the latest commit of vcpkg

**Comment by jimwang118** [comment]
> @jimwang118 The process I'm using is a bit different since the vcpkg repo is checked out as a sub-module in my repo. Everything is handled automatically through the vcpkg.json and CMake so the bootstrapping is done automatically as far as I know. This has always worked it just seems that with this version of sdl2 it failed.
> 
> I'm already using the latest commit of vcpkg

I use the vcpkg.json you provided, and the compilation is normal after updating the latest vcpkg code base locally.

`cmake  -G "Visual Studio 17 2022" -A x64  -DVCPKG_TARGET_TRIPLET=x64-windows -DVCPKG_BUILD_TYPE=debug  -DCMAKE_TOOLCHAIN_FILE:STRING="F:\vcpkg\scripts\buildsystems\vcpkg.cmake" CMakeLists.txt`
![image](https://github.com/microsoft/vcpkg/assets/122244446/1d775ad1-715b-4061-9f1a-0dc8a3500502)

**Comment by AbyssalDrifter** [comment]
Ok thanks. Maybe some of my CMake configuration needs to change. I'll do some more tests

**Comment by AbyssalDrifter** [comment]
So I had to bootstrap the vcpkg submodule, which always seems to have happened automatically previously and that fixed the issue.

Thanks. Closing issue

**Comment by dg0yt** [comment]
Bootstrap has to be repeated sometimes. The vcpkg tool isn't updated automatically after the initial bootstrapping.
