### ISSUE TITLE
[zlib] Build error on arm64-osx

### ISSUE THREAD

**Issue by Darshil02** [microsoft/vcpkg#35652]
error: building zlib:arm64-osx failed with: BUILD_FAILED
Elapsed time to handle zlib:arm64-osx: 1.4 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.

Trying to add curl lib but the build failed in for Visual Studio (C)

**Comment by Cheney-W** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report an issue.
