### ISSUE TITLE
"expected 7za.exe to exist after fetching" when running in Docker with isolation mode Hyper-V

### ISSUE THREAD

**Issue by danielschenk** [microsoft/vcpkg#35656]
**Describe the bug**
When building a Visual Studio 2017 solution using vcpkg manifest mode, inside a Docker container with the project directory bind-mounted to it, we get the following issue:
```
A suitable version of 7zip was not found (required v23.1.0) Downloading portable 7zip 23.1.0...
  Downloading 7zip...
  https://www.7-zip.org/a/7z2301-extra.7z->C:\build\submodules\vcpkg\downloads\7z2301-extra.7z
  Downloading https://www.7-zip.org/a/7z2301-extra.7z
  Extracting 7zip...
EXEC : error : Expected C:\build\submodules\vcpkg\downloads\tools\7zip-23.01-windows\7za.exe to exist after fetching [C:\build\ProtoObjects\ProtoObjects.vcxproj]
```

Some additional notes:
- Might be related to #24585, however, as I'm not using Linux I decided to create a separate issue.
- We can work around this issue by using Docker's `process` isolation mode. Therefore it might also be a Docker bug, for which I already created a Docker issue: https://github.com/docker/for-win/issues/13502. However, I'm not sure as I also found a vcpkg issue which looks similar and is not Docker related (see above).

**Environment**
- OS: Windows 10 hosting a Docker container based on mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019
- Compiler: msbuild, C/C++ toolset, v141

**To Reproduce**
_Note: I don't know how critical it actually is to do this through msbuild, it might as well fail already when just using vcpkg alone._
1. Create a Visual Studio solution with at least one C/C++ project in it which uses vcpkg manifest mode and lists some packages in its vcpkg.json (we use fmt and grpc for example)
2. Build it using a Docker container (with aforementioned base) which has msbuild and the C/C++ build tools available, while providing the project to it via a bind mount, using Hyper-V process isolation (should be the default)

**Expected behavior**
7za.exe is downloaded and found by vcpkg as it should

**Failure logs**
-(please attached failure logs)

**Additional context**

**Comment by jimwang118** [comment]
Please provide which port you installed.

**Comment by danielschenk** [comment]
This is our vcpkg.json file.
```json
{
    "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg.schema.json",
    "name": "pqmt",
    "version": "0.2",
    "dependencies": [
        "grpc",
        "boost-program-options",
        "boost-date-time",
        "boost-algorithm",
        "fmt",
        "abseil",
        "re2"
    ],
    "$builtin-baseline-comment": "https://github.com/microsoft/vcpkg/tree/2023.11.20",
    "builtin-baseline": "a42af01b72c28a8e1d7b48107b33e4f286a55ef6",
    "overrides": [
        {
            "name": "fmt",
            "version": "9.1.0"
        },
        {
            "name": "abseil",
            "version": "20230125.3"
        },
        {
            "name": "re2",
            "version": "2023-02-01"
        }
    ],
    "vcpkg-configuration": {
        "overlay-triplets": [ "./vcpkg_triplets" ]
    }
}
```

**Comment by jaykrell** [comment]
I'm getting same error.

**Comment by jimwang118** [comment]
> I'm getting same error.

Please resubmit an issue.
