### ISSUE TITLE
[boost-vcpkg-helpers] Build error on x64-windows-static

### ISSUE THREAD

**Issue by qwfgw** [microsoft/vcpkg#35669]
[issue_body.md](https://github.com/microsoft/vcpkg/files/13667805/issue_body.md)

**Comment by Adela0814** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report an issue.

**Comment by Adela0814** [comment]
Duplicate of  https://github.com/microsoft/vcpkg/issues/35681.
