### ISSUE TITLE
vcpkg not copying required DLLs to debug folder

### ISSUE THREAD

**Issue by kerplatz** [microsoft/vcpkg#35664]
I am new to vcpkg and I am struggling to make it work, but I am learning. First question, can someone explain to me what is meant when they talk about a triplet? I always thought it meant 3 of something, but in vcpkg that does not seem correct. So on to the problem at hand. I have 2 libraries that I want to use in my project, fmt and sqlite3. My vcpkg. json file is included, along with my vcpkg-configuration.json file.
[vcpkg.json](https://github.com/microsoft/vcpkg/files/13666692/vcpkg.json)
[vcpkg-configuration.json](https://github.com/microsoft/vcpkg/files/13666693/vcpkg-configuration.json)
I believe that all is working correctly. I put vcpkg in Manifest mode by changing the properties of the project. I am using VS2019 ver 16.11.32, which means I am using MSBuild and not CMake as I never changed that in VS2019. I am not going to show my code as it is quite large and the vast majority has been working until I added these 2 libraries. Now intellisense is picking up the code in the 2 .h files I have included in my project for these libraries. That all seems good. But, when I compile I get a warning "Failed to gather app local DLL dependencies, program may not run." Sure enough, the project does not run for failure to load DLL and neither one is in the folder with the EXE. Here are those outputs.
[BuildOutput.txt](https://github.com/microsoft/vcpkg/files/13666743/BuildOutput.txt)
[Run Output.txt](https://github.com/microsoft/vcpkg/files/13666750/Run.Output.txt)
I figure this is something simple, but all the reading I have done so far as not solved this problem for me. Thanks for you help on this.

PS- I guess I could just include them in my project as a dependency, but unless I am wrong about that, I thought that was why we have vcpkg and manifest mode.

**Comment by kerplatz** [comment]
Update - I was able to figure out one of the errors (Build output). That was caused by having a space in the name of my project. This caused no DLL,s to be copied to the exe folder. Here is the clue -

1>KCam8 GUI.vcxproj -> C:\Users\Public\**SourceCode\KCam8 GUI**\x64\Debug\KCam8 GUI\KCam8 GUI.exe
1>[31;1mapplocal.ps1: [31;1mA positional parameter cannot be found that accepts argument 'C:\Users\Public\**SourceCode\KCam8**'.[0m
1>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(247,5): warning : [vcpkg] Failed to gather app local DLL dependencies, program may not run. Set __

The name of my project is KCam8 GUI. Got rid of the space and the problem was solved. I thought it did not matter, especially after having long name capability for well over 20 years. I am so disappointed. I suppose they will make us use a .3 name extension in the future for ALL our files. End of rant.

**Comment by MonicaLiu0311** [comment]
> First question, can someone explain to me what is meant when they talk about a triplet?

https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/concepts/triplets.md
https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/users/triplets.md

**Comment by MonicaLiu0311** [comment]
I have not repro your issue, the result are as follows:
```
Build started at 7:47 PM...
1>------ Build started: Project: MSBuildManifestTest, Configuration: Debug x64 ------
1>Installing vcpkg dependencies to C:\Users\monica\source\repos\MSBuildManifestTest\MSBuildManifestTest\vcpkg_installed\x64-windows\
1>"G:\vcpkg\vcpkg.exe" install  --x-wait-for-lock --triplet "x64-windows" --vcpkg-root "G:\vcpkg\\" "--x-manifest-root=C:\Users\monica\source\repos\MSBuildManifestTest\MSBuildManifestTest\\" "--x-install-root=C:\Users\monica\source\repos\MSBuildManifestTest\MSBuildManifestTest\vcpkg_installed\x64-windows\\"
1>Fetching registry information from https://github.com/microsoft/vcpkg (HEAD)...
1>Detecting compiler hash for triplet x64-windows...
1>Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe
1>The following packages will be built and installed:
1>    fmt:x64-windows@10.2.1#2 -- C:\Users\monica\AppData\Local\vcpkg\registries\git-trees\f6f4efa01a5e9ac627f0c6687af8b6b317fbbe42
1>    sqlite3[core,json1]:x64-windows@3.46.0#2 -- C:\Users\monica\AppData\Local\vcpkg\registries\git-trees\54f7fe82339d8c8d79ff2cffd1751084fef85bfc
1>  * vcpkg-cmake:x64-windows@2024-04-23 -- C:\Users\monica\AppData\Local\vcpkg\registries\git-trees\e74aa1e8f93278a8e71372f1fa08c3df420eb840
1>  * vcpkg-cmake-config:x64-windows@2024-05-23 -- C:\Users\monica\AppData\Local\vcpkg\registries\git-trees\97a63e4bc1a17422ffe4eff71da53b4b561a7841
1>Additional packages (*) will be modified to complete this operation.
1>Restored 4 package(s) from C:\Users\monica\AppData\Local\vcpkg\archives in 232 ms. Use --debug to see more details.
1>Installing 1/4 vcpkg-cmake-config:x64-windows@2024-05-23...
1>Elapsed time to handle vcpkg-cmake-config:x64-windows: 15.8 ms
1>vcpkg-cmake-config:x64-windows package ABI: f67f77c28488ce1cfcc8ef94dc13214aa48c5f8adcf8681f430cc14bc7f20f05
1>Installing 2/4 vcpkg-cmake:x64-windows@2024-04-23...
1>Elapsed time to handle vcpkg-cmake:x64-windows: 14.2 ms
1>vcpkg-cmake:x64-windows package ABI: ecea25762013db37d394368f1f4c8200ad7fbbd2cbcc61074ab93c95803d11d7
1>Installing 3/4 fmt:x64-windows@10.2.1#2...
1>Elapsed time to handle fmt:x64-windows: 107 ms
1>fmt:x64-windows package ABI: 4b220780336cd378ee955bee6a2aaced1f1ec443da616b087e23231180508dd7
1>Installing 4/4 sqlite3[core,json1]:x64-windows@3.46.0#2...
1>Elapsed time to handle sqlite3:x64-windows: 110 ms
1>sqlite3:x64-windows package ABI: 4ed3f8978be292f07807a1625cdfb08250b29235ef635e893aeb728dcd192970
1>Total install time: 248 ms
1>The package fmt provides CMake targets:
1>
1>    find_package(fmt CONFIG REQUIRED)
1>    target_link_libraries(main PRIVATE fmt::fmt)
1>
1>    # Or use the header-only version
1>    find_package(fmt CONFIG REQUIRED)
1>    target_link_libraries(main PRIVATE fmt::fmt-header-only)
1>
1>sqlite3 provides pkgconfig bindings.
1>sqlite3 provides CMake targets:
1>
1>    find_package(unofficial-sqlite3 CONFIG REQUIRED)
1>    target_link_libraries(main PRIVATE unofficial::sqlite3::sqlite3)
1>
1>MSBuildManifestTest.vcxproj -> C:\Users\monica\source\repos\MSBuildManifestTest\MSBuildManifestTest\x64\Debug\MSBuildManifestTest.exe
1>'pwsh.exe' is not recognized as an internal or external command,
1>operable program or batch file.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 7:47 PM and took 08.773 seconds ==========

```

![image](https://github.com/user-attachments/assets/fcb39d16-d632-40d5-86fc-80b8847374d2)
![image](https://github.com/user-attachments/assets/9b74e412-074d-4f13-b031-8c066730860f)


[vcpkg-configuration.json](https://github.com/user-attachments/files/16356491/vcpkg-configuration.json)
[vcpkg.json](https://github.com/user-attachments/files/16356492/vcpkg.json)
[MSBuildManifestTest.cpp.txt](https://github.com/user-attachments/files/16356498/MSBuildManifestTest.cpp.txt)

**Comment by MonicaLiu0311** [comment]
If you still have questions about this, please reopen this issue.
