### ISSUE TITLE
benchmark build failure

### ISSUE THREAD

**Issue by AlangabSistemi** [microsoft/vcpkg#35677]
### Operating system

Windows 

### Compiler

msvs 2022

### Steps to reproduce the behavior

```Shell
vcpkg.exe" install  --x-wait-for-lock --triplet "x64-windows" --vcpkg-root "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\vcpkg\\" "--x-manifest-root=C:\xxxx\\" "--x-install-root=C:\xxxx\vcpkg_installed\x64-windows\\
```

### Failure logs

Build started...
1>------ Build started: Project: bench1, Configuration: Debug x64 ------
1>Installing vcpkg dependencies to C:\Users\pierotti\source\repos\bench1\vcpkg_installed\x64-windows\
1>"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\vcpkg\vcpkg.exe" install  --x-wait-for-lock --triplet "x64-windows" --vcpkg-root "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\vcpkg\\" "--x-manifest-root=C:\Users\pierotti\source\repos\bench1\\" "--x-install-root=C:\Users\pierotti\source\repos\bench1\vcpkg_installed\x64-windows\\"
1>Detecting compiler hash for triplet x64-windows...
1>The following packages will be built and installed:
1>    benchmark:x64-windows -> 1.8.0 -- C:\Users\pierotti\AppData\Local\vcpkg\registries\git-trees\faeb0b56e68483860ab8cc468a6c594ac361167f
1>Restored 0 package(s) from C:\Users\pierotti\AppData\Local\vcpkg\archives in 312 us. Use --debug to see more details.
1>Installing 1/1 benchmark:x64-windows...
1>Building benchmark:x64-windows...
1>-- Installing port from location: C:\Users\pierotti\AppData\Local\vcpkg\registries\git-trees\faeb0b56e68483860ab8cc468a6c594ac361167f
1>-- Note: benchmark only supports static library linkage. Building static library.
1>-- Using cached google-benchmark-v1.8.0.tar.gz.
1>-- Cleaning sources at C:/Users/pierotti/source/repos/bench1/vcpkg_installed/x64-windows/vcpkg/blds/benchmark/src/v1.8.0-eeb87a0405.clean. Use --editable to skip cleaning for the packages you specify.
1>-- Extracting source C:/Users/pierotti/AppData/Local/vcpkg/downloads/google-benchmark-v1.8.0.tar.gz
1>-- Using source at C:/Users/pierotti/source/repos/bench1/vcpkg_installed/x64-windows/vcpkg/blds/benchmark/src/v1.8.0-eeb87a0405.clean
1>-- Found external ninja('1.11.0').
1>-- Configuring x64-windows
1>-- Building x64-windows-dbg
1>-- Building x64-windows-rel
1>-- Fixing pkgconfig file: C:/Users/pierotti/source/repos/bench1/vcpkg_installed/x64-windows/vcpkg/pkgs/benchmark_x64-windows/lib/pkgconfig/benchmark.pc
1>-- Using cached mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
1>-- Downloading https://mirror.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst -> mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst...
1>[DEBUG] To include the environment variables in debug output, pass --debug-env
1>[DEBUG] Trying to load bundleconfig from C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\vcpkg\vcpkg-bundle.json
1>[DEBUG] Bundle config: readonly=true, usegitregistry=true, embeddedsha=638b1588be3a265a9c7ad5b212cef72a1cad336a, deployment=VisualStudio, vsversion=17.0
1>[DEBUG] VS telemetry opted in at SOFTWARE\WOW6432Node\Microsoft\VSCommon\17.0\SQM\\OptIn
1>[DEBUG] Metrics enabled.
1>[DEBUG] Feature flag 'binarycaching' unset
1>[DEBUG] Feature flag 'compilertracking' unset
1>[DEBUG] Feature flag 'registries' unset
1>[DEBUG] Feature flag 'versions' unset
1>[DEBUG] Feature flag 'dependencygraph' unset
1>Downloading https://mirror.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst
1>Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst
1>Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst
1>Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst
1>Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst
1>Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(183,5): warning : error: Failed to download from mirror set
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(183,5): warning : error: https://mirror.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst: failed: status code 404
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(183,5): warning : error: https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst: failed: status code 404
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(183,5): warning : error: https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst: failed: status code 404
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(183,5): warning : error: https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst: failed: status code 404
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(183,5): warning : error: https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst: failed: status code 404
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(183,5): warning : error: https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst: failed: status code 404
1>[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1003):
1>[DEBUG] Time in subprocesses: 0us
1>[DEBUG] Time in parsing JSON: 20us
1>[DEBUG] Time in JSON reader: 0us
1>[DEBUG] Time in filesystem: 3317us
1>[DEBUG] Time in loading ports: 0us
1>[DEBUG] Exiting after 4.6 s (4452844us)
1>
1>CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
1>
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(183,5): warning :       Failed to download file with error: 1
1>      If you are using a proxy, please check your proxy setting. Possible causes are:
1>
1>      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
1>         to `https://address:port`. This is not correct, because `https://` prefix
1>         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
1>         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
1>         HTTP_PROXY and HTTPS_PROXY instead.
1>
1>      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
1>         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
1>         The value set by your proxy might be wrong, or have same `https://` prefix issue.
1>
1>      3. Your proxy's remote server is out of service.
1>
1>      If you've tried directly download the link, and believe this is not a temporary
1>      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
1>      to report this upstream download server failure.
1>
1>
1>Call Stack (most recent call first):
1>  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
1>  scripts/cmake/vcpkg_acquire_msys.cmake:25 (vcpkg_download_distfile)
1>  scripts/cmake/vcpkg_acquire_msys.cmake:124 (z_vcpkg_acquire_msys_download_package)
1>  scripts/cmake/vcpkg_acquire_msys.cmake:209 (z_vcpkg_acquire_msys_download_packages)
1>  scripts/cmake/vcpkg_find_acquire_program(PKGCONFIG).cmake:22 (vcpkg_acquire_msys)
1>  scripts/cmake/vcpkg_find_acquire_program.cmake:118 (include)
1>  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:203 (vcpkg_find_acquire_program)
1>  C:/Users/pierotti/AppData/Local/vcpkg/registries/git-trees/faeb0b56e68483860ab8cc468a6c594ac361167f/portfile.cmake:22 (vcpkg_fixup_pkgconfig)
1>  scripts/ports.cmake:147 (include)
1>
1>
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(183,5): warning : error: building benchmark:x64-windows failed with: BUILD_FAILED
1>Elapsed time to handle benchmark:x64-windows: 37 s
1>Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
1>Then check for known issues at:
1>    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+benchmark
1>You can submit a new issue at:
1>    https://github.com/microsoft/vcpkg/issues/new?title=[benchmark]+Build+error&body=Copy+issue+body+from+C%3A%2FUsers%2Fpierotti%2Fsource%2Frepos%2Fbench1%2Fvcpkg_installed%2Fx64-windows%2Fvcpkg%2Fissue_body.md
1>
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(183,5): error MSB3073: The command ""C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\vcpkg\vcpkg.exe" install  --x-wait-for-lock --triplet "x64-windows" --vcpkg-root "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\vcpkg\\" "--x-manifest-root=C:\Users\pierotti\source\repos\bench1\\" "--x-install-root=C:\Users\pierotti\source\repos\bench1\vcpkg_installed\x64-windows\\" " exited with code 1.
1>Done building project "bench1.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 08:34 and took 52,941 seconds ==========

### Additional context

mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst is missing from repositories

**Comment by MonicaLiu0311** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
