### ISSUE TITLE
Failed to build opencv with dnn

### ISSUE THREAD

**Issue by lazylazypig** [Microsoft/vcpkg#3567]
Hi, all
I have tried to build opencv 3.4.1 with dnn module enabled with following command:
.\vcpkg.exe install opencv[dnn]:x64-windows

After several minutes I got following errors in "vcpkg\buildtrees\opencv\install-x64-windows-dbg-out.log"：
  
 Creating library lib\opencv_dnn341d.lib and object lib\opencv_dnn341d.exp
caffe_importer.cpp.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl google::protobuf::internal::LogMessage::LogMessage(enum google::protobuf::LogLevel,char const *,int)" (__imp_??0LogMessage@internal@protobuf@google@@QEAA@W4LogLevel@23@PEBDH@Z)
caffe_io.cpp.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl google::protobuf::internal::LogMessage::LogMessage(enum google::protobuf::LogLevel,char const *,int)" (__imp_??0LogMessage@internal@protobuf@google@@QEAA@W4LogLevel@23@PEBDH@Z)
caffe_shrinker.cpp.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl google::protobuf::internal::LogMessage::LogMessage(enum google::protobuf::LogLevel,char const *,int)" (__imp_??0LogMessage@internal@protobuf@google@@QEAA@W4LogLevel@23@PEBDH@Z)
tf_importer.cpp.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl google::protobuf::internal::LogMessage::LogMessage(enum google::protobuf::LogLevel,char const *,int)" (__imp_??0LogMessage@internal@protobuf@google@@QEAA@W4LogLevel@23@PEBDH@Z)
tensor.pb.cc.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl google::protobuf::internal::LogMessage::LogMessage(enum google::protobuf::LogLevel,char const *,int)" (__imp_??0LogMessage@internal@protobuf@google@@QEAA@W4LogLevel@23@PEBDH@Z)
tensor_shape.pb.cc.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl google::protobuf::internal::LogMessage::LogMessage(enum google::protobuf::LogLevel,char const *,int)" (__imp_??0LogMessage@internal@protobuf@google@@QEAA@W4LogLevel@23@PEBDH@Z)
versions.pb.cc.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl google::protobuf::internal::LogMessage::LogMessage(enum google::protobuf::LogLevel,char const *,int)" (__imp_??0LogMessage@internal@protobuf@google@@QEAA@W4LogLevel@23@PEBDH@Z)
opencv-caffe.pb.cc.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl google::protobuf::internal::LogMessage::LogMessage(enum google::protobuf::LogLevel,char const *,int)" (__imp_??0LogMessage@internal@protobuf@google@@QEAA@W4LogLevel@23@PEBDH@Z)
attr_value.pb.cc.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl google::protobuf::internal::LogMessage::LogMessage(enum google::protobuf::LogLevel,char const *,int)" (__imp_??0LogMessage@internal@protobuf@google@@QEAA@W4LogLevel@23@PEBDH@Z)
function.pb.cc.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl google::protobuf::internal::LogMessage::LogMessage(enum google::protobuf::LogLevel,char const *,int)" (__imp_??0LogMessage@internal@protobuf@google@@QEAA@W4LogLevel@23@PEBDH@Z)
graph.pb.cc.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl google::protobuf::internal::LogMessage::LogMessage(enum google::protobuf::LogLevel,char const *,int)" (__imp_??0LogMessage@internal@protobuf@google@@QEAA@W4LogLevel@23@PEBDH@Z)
op_def.pb.cc.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl google::protobuf::internal::LogMessage::LogMessage(enum google::protobuf::LogLevel,char const *,int)" (__imp_??0LogMessage@internal@protobuf@google@@QEAA@W4LogLevel@23@PEBDH@Z)

...

I have also try to modify the CMakeLists.txt of dnn to add some instructions as follow:
if(MSVC)
  add_definitions( -D_CRT_SECURE_NO_WARNINGS=1 )
  **_if(BUILD_SHARED_LIBS)
    add_definitions(-DPROTOBUF_USE_DLLS)
  endif()_**
...
but unfortunately, the errors still existed. how can I solve this problem? thanks very much :)

**Comment by dreness** [comment]
+1. My build log is attached below.

[install-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2052577/install-x64-windows-dbg-out.log)

**Comment by treigilbert** [comment]
I was seeing the same issues. To build opencv with dnn, I had to comment out the protobuf patch on line 20 and PREFER_NINJA on line 240 in the opencv/portfile.cmake

#      "${CMAKE_CURRENT_LIST_DIR}/0005-remove-protobuf-target.patch"
     #PREFER_NINJA

after disabling those two lines, opencv compiled and I was able to use the library with other code. I am using Visual Studio 15.7.2 and cuda 9.2. The building of opencv did take some time.
Installing package opencv[contrib,core,cuda,dnn,eigen,ffmpeg,flann,jpeg,opengl,png,sfm,tiff]:x64-windows... done
Elapsed time for package opencv:x64-windows: 5.584 h

**Comment by lazylazypig** [comment]
@treigilbert  Thanks for your reply. I have try your solution, and the problem caused by protobuf seems to be resolved. But, unfortunately, I got other errors after a really long time:
 
       “D:\Development\Env\vcpkg\buildtrees\opencv\x64-windows-dbg\install.vcxproj”(Default Target) (1) ->
       “D:\Development\Env\vcpkg\buildtrees\opencv\x64-windows-dbg\ALL_BUILD.vcxproj”(Default Target) (3) ->
       “D:\Development\Env\vcpkg\buildtrees\opencv\x64-windows-dbg\modules\cudabgsegm\opencv_cudabgsegm.vcxproj”(Default Target) (31) ->
       (CustomBuild Target) -> 
         CUSTOMBUILD : CMake error : CMake can not determine linker language for target: cmTC_ee04f [D:\Development\Env\vcpkg\buildtrees\opencv\x64-windows-dbg\modules\cudabgsegm\opencv_cudabgsegm.vcxproj]


       “D:\Development\Env\vcpkg\buildtrees\opencv\x64-windows-dbg\install.vcxproj”(Default Target) (1) ->
       “D:\Development\Env\vcpkg\buildtrees\opencv\x64-windows-dbg\ALL_BUILD.vcxproj”(Default Target) (3) ->
       “D:\Development\Env\vcpkg\buildtrees\opencv\x64-windows-dbg\modules\cudaoptflow\opencv_cudaoptflow.vcxproj”(Default Target) (45) ->
         CUSTOMBUILD : CMake error : Parse error in cache file D:/Development/Env/vcpkg/buildtrees/opencv/x64-windows-dbg/CMakeCache.txt on line 3805. Offending entry: /nBrief description of opencv_rgbd module [D:\Development\Env\vcpkg\buildtrees\opencv\x64-windows-dbg\modules\cudaoptflow\opencv_cudaoptflow.vcxproj]
         CUSTOMBUILD : CMake error : Parse error in cache file D:/Development/Env/vcpkg/buildtrees/opencv/x64-windows-dbg/CMakeCache.txt on line 4185. Offending entry: module [D:\Development\Env\vcpkg\buildtrees\opencv\x64-windows-dbg\modules\cudaoptflow\opencv_cudaoptflow.vcxproj]
         CUSTOMBUILD : CMake error : Parse error in cache file D:/Development/Env/vcpkg/buildtrees/opencv/x64-windows-dbg/CMakeCache.txt on line 4296. Offending entry: _xLocation of opencv_ximgproc module sources [D:\Development\Env\vcpkg\buildtrees\opencv\x64-windows-dbg\modules\cudaoptflow\opencv_cudaoptflow.vcxproj]

    6545 Warnings
    4 Errors

Elapsed time 02:26:17.83

I‘m feeling very depressed ：（

**Comment by philipNoonan** [comment]
I've managed to get openCV building with visual studio 2017 15.7.1 and cuda 9.2 using

vcpkg install opencv[opengl,contrib,dnn,cuda] --featurepackages
...
...
Building package opencv[contrib,core,cuda,dnn,eigen,flann,jpeg,opengl,png,tiff]:x64-windows... done
Installing package opencv[contrib,core,cuda,dnn,eigen,flann,jpeg,opengl,png,tiff]:x64-windows...
Installing package opencv[contrib,core,cuda,dnn,eigen,flann,jpeg,opengl,png,tiff]:x64-windows... done
Elapsed time for package opencv:x64-windows: 50.12 min

Total elapsed time: 50.12 min

WOOOOOO!!!

To get this building I had to turn off a few things in portfile.cmake

-DBUILD_opencv_videostab=OFF
-DBUILD_opencv_cudafilters=OFF
-DBUILD_opencv_cudabgsegm=OFF
-DBUILD_opencv_stitching=OFF

I also added 

-DCUDA_GENERATION="Pascal" 

so that it only builds for my GPU (1080)

Also followed advice from @treigilbert above, with his edits.

Finally, I edited the C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\include\crt\host_config.h file to allow for 2017 
line 131 becomes -->  #if _MSC_VER < 1600 || _MSC_VER > 1919

**Comment by LarryIII** [comment]
@lazylazypig Thanks for you feedback. I installed opencv[dnn]:x64-windows successfully. Please open a new issue if this is still a problem for you.
