### ISSUE TITLE
[atl] Build error on x64-windows

### ISSUE THREAD

**Issue by boggle200** [microsoft/vcpkg#35686]
(error: building atl:x64-windows failed with: BUILD_FAILED)

could someone infer or find me why this matter happen?

**Comment by autoantwort** [comment]
The reason is printed before the line you pasted here :)

**Comment by LilyWangLL** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report an issue.

**Comment by boggle200** [comment]
i wrote "vcpkg install llvm opencv4[contrib,nonfree]" reading the url that "https://crates.io/crates/opencv". and under error has occurred.

error: building atl:x64-windows failed with: BUILD_FAILED
Elapsed time to handle atl:x64-windows: 62.9 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.

**Comment by LilyWangLL** [comment]
![image](https://github.com/microsoft/vcpkg/assets/94091114/a0a7d82c-8f0b-4f58-a4c7-9e2107695b6a)
Please install the above component in Visual Studio Installer.

**Comment by boggle200** [comment]
Oh! It's working! 😊 
Thank you, everyone

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This issue has been fixed, so I am closing this issue for now.
