### ISSUE TITLE
[New Port Request] embree4

### ISSUE THREAD

**Issue by swolter1701** [microsoft/vcpkg#35683]
### Library name

Embree4

### Library description

high-performance ray tracing library

### Source repository URL

https://github.com/embree/embree/releases/tag/v4.3.0

### Project homepage (if different from the source repository)

https://www.embree.org/

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

older version of embree v3.x is already in vcpkg: embree3 | Version: 3.13.5

**Comment by theblackunknown** [comment]
I am interested to tackle this in the future, however should we create yet another port or simply stop putting the version into the port name and just use the manifest version field ?

In a nutshell, I am proposing to deprecate the embree3 port - or making it a stub port - and create the `embree` port instead of `embree4`

**Comment by githubkusi** [comment]
please keep embree3 and create a new port for embree4. There are still many libraries which depend on embree3. Currently, it is cumbersome to install a specific version of a library from the command line. I believe proper versioning is only available in manifest mode

Having said that, thanks a lot for working on embree4, much appreciated!

**Comment by theblackunknown** [comment]
Indeed, I am used to manifest mode only those days but I understand this can be painful when it is not used at all and have to force people into doing custom overlay ports...

That said, and assuming we will have a `embree4` port. Would it be useful to have a `embree` meta port which simply point to the latest desired version (and which can also be either versioned and/or overlaid) ?

**Comment by dg0yt** [comment]
Such meta ports come with own maintenance issues: they have to mirror the actual port's features. Example: opencv vs. opencv4.

Having two ports can cause problems if they provide the same files (cf. opencv ports) or symbols (may break msbuild autolinking). It is possible to exclude the older version from vcpkg CI if the they provide the same files (cf. opencv3). But then it may break silently.

**Comment by zhai-xiao** [comment]
I'm also waiting for embree4. Thank you!

**Comment by patrikhuber** [comment]
I also need embree4 in vcpkg. Having this "closed as not planned" is disappointing - embree4 is a well-known and widely used library. If such libraries are not available in vcpkg (or only old versions like embree3 3.13), then what's the point of it?

/CC @dg0yt

**Comment by patrikhuber** [comment]
> Not my job [...]

"Not my job" and then he does it 😅🥳🥳 Thank you very much!

**Comment by dg0yt** [comment]
> contributing it is the fastest way to get it.

Took one more year.
