### ISSUE TITLE
cant build openssl:x64-linux on Ubuntu 16.4

### ISSUE THREAD

**Issue by Chen-Zhihui** [Microsoft/vcpkg#3569]
./vcpkg build openssl:x64-linux
  Package: openssl:x64-linux
  Vcpkg version: 0.0.113-unknownhash
[install-x64-linux-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2031438/install-x64-linux-dbg-out.log)

**Comment by navidR** [comment]
Same issue here.

**Comment by navidR** [comment]
FWIW after messing a little bit if openssl portfile. I find this line cause  the error : 
https://github.com/Microsoft/vcpkg/blob/master/ports/openssl/CMakeLists.txt#L104

CMake interprets "${CFLAGS}" as " " and Configure cannot understand it.

**Comment by alexkaratarakis** [comment]
Fix in 1d52df8140104a969699f774dbae4fe25d2f6d00.
