### ISSUE TITLE
Error: Building package openblas:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by celllaw** [Microsoft/vcpkg#3570]
(base) N:\InstalledPrograms\vcpkg>vcpkg install suitesparse:x86-windows
The following packages will be built and installed:
  * clapack[core]:x86-windows
  * openblas[core]:x86-windows
    suitesparse[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: openblas:x86-windows
Building package openblas[core]:x86-windows...
-- CURRENT_INSTALLED_DIR=N:/InstalledPrograms/vcpkg/installed/x86-windows
-- DOWNLOADS=N:/InstalledPrograms/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=N:/InstalledPrograms/vcpkg/packages/openblas_x86-windows
-- CURRENT_BUILDTREES_DIR=N:/InstalledPrograms/vcpkg/buildtrees/openblas
-- CURRENT_PORT_DIR=N:/InstalledPrograms/vcpkg/ports/openblas
CMake Error at N:/InstalledPrograms/vcpkg/ports/openblas/portfile.cmake:16 (message):
  openblas can only be built for x64 currently
Call Stack (most recent call first):
  N:/InstalledPrograms/vcpkg/scripts/ports.cmake:72 (include)

Error: Building package openblas:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openblas:x86-windows
  Vcpkg version: 0.0.113-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by Voskrese** [comment]
**openblas can only be built for x64 currently**

**Comment by celllaw** [comment]
Make Error at N:/InstalledPrograms/vcpkg/scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: N:/InstalledPrograms/vcpkg/buildtrees/blaze/x64-windows-rel/vcpkg-parallel-configure
    See logs for more information:
      N:\InstalledPrograms\vcpkg\buildtrees\blaze\config-x64-windows-out.log

Call Stack (most recent call first):
  N:/InstalledPrograms/vcpkg/scripts/cmake/vcpkg_configure_cmake.cmake:237 (vcpkg_execute_required_process)
  N:/InstalledPrograms/vcpkg/ports/blaze/portfile.cmake:16 (vcpkg_configure_cmake)
  N:/InstalledPrograms/vcpkg/scripts/ports.cmake:72 (include)


Error: Building package blaze:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: blaze:x64-windows
  Vcpkg version: 0.0.113-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by Voskrese** [comment]
N:\InstalledPrograms\vcpkg\buildtrees\blaze\config-x64-windows-out.log

**Comment by LarryIII** [comment]
Please see .\vcpkg\port\openblas\portfile.cmake： 
if(NOT VCPKG_TARGET_ARCHITECTURE STREQUAL "x64")
    message(FATAL_ERROR "openblas can only be built for x64 currently")
endif()
So close this issue!
