### ISSUE TITLE
how to use with clion?

### ISSUE THREAD

**Issue by oahzuw** [microsoft/vcpkg#3572]
how to use with clion?

**Comment by DukeOfErl** [comment]
Would very much like to have simple instructions on how to use vcpkg with clion.
I've tried following the instructions for vcpkg with cmake, but couldn't get it to work on clion

**Comment by masphei** [comment]
Using Windows, I was doing the steps below to link CLion with my vcpkg.
1. Go to File -> Settings -> Build, Execution, Deployment -> CMake
2. Choose one profile, and then find "CMake Options".
3. Insert value to the option: "-DCMAKE_TOOLCHAIN_FILE=<path to vcpkg>/scripts/buildsystems/vcpkg.cmake"

Please let me know if there is any better way to do this.

**Comment by NancyLi1013** [comment]
Hi @oahzuw, thanks for posing this issue. Hope the above instructions from masphei can help you. Please feel free to reopen it if this is still a problem for you.

**Comment by dsazonoff** [comment]
Small update: CLion already have a built in support for vcpkg, but it actually do the same for cmake based projects
