### ISSUE TITLE
Homebrew formula and default install location

### ISSUE THREAD

**Issue by xeoneux** [microsoft/vcpkg#3573]
Will there be a homebrew formula to directly install `vcpkg` from the command line?

Also, setting a default directory for all the installed ports would really help than setting the location of the cloned git repository.

**Comment by carmangary** [comment]
True.  It would be nice to avoid GIT and the bootstrap bat file if possible.

**Comment by DavidLudwig** [comment]
If anyone is wondering what HomeBrew is, it is a popular, 3rd-party, package manager for MacOS.  More info is at https://brew.sh

I, for one, would love to see this.  The MacOS bootstrap script can be finicky, especially with the current lack of support for boot-strapping vcpkg with Xcode 9.x, and the need to install (arguably nebulous versions of) gcc, and lack of documentation on how to install it in a PATH-accessible directory.

**Comment by xeoneux** [comment]
Is there anyone working on it? I could give it a try...

**Comment by dan-ryan** [comment]
Brew would make setting up projects much easier on Mac. @xeoneux I doubt anyone is working on it.

**Comment by xeoneux** [comment]
@dan-ryan definitely! I created a PR at homebrew-core https://github.com/Homebrew/homebrew-core/pull/36347

Currently, I cannot get it to build with gcc even after setting the env var. Could you take a look at it?

**Comment by dan-ryan** [comment]
"Currently, I cannot get it to build with gcc even after setting the env var."
What's the error you get?

**Comment by dan-ryan** [comment]
I see it now:
> CMake Error at CMakeLists.txt:10 (message):
>   Building the vcpkg tool requires support for the C++ Filesystem TS.
> 
>   Apple clang versions 9 and below do not have support for it.
> 
>   Please install gcc6 or newer from homebrew (brew install gcc6).
> 
>   If you would like to try anyway, set VCPKG_ALLOW_APPLE_CLANG.
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/36805/version=mojave/testReport/brew-test-bot/mojave/install_vcpkg/

Looks like they are using "Apple Clang 10.0.0.10001145". I'm not sure if this version has Filesystem TS support. Can you select GCC?

**Comment by xeoneux** [comment]
Yup, I'm now setting CC and CXX through env vars instead. That works 👍
I hope the PR's ready to be merged: https://github.com/Homebrew/homebrew-core/pull/36347 😄

**Comment by dgellow** [comment]
So I see that https://github.com/Homebrew/homebrew-core/pull/36347 has been closed with the following comment:

> HI and thanks for having a go at creating this Formula. The first issue here is that there are no released versions of this software nor any tags that would allow us to rebuild this formula reliably as is documented in https://docs.brew.sh/Acceptable-Formulae under the section of Stable versions. This means that we can't accept it into homebrew-core but you could of course set up your own tap.

Is there a plan to create tagged released of vcpkg?

**Comment by cbezault** [comment]
@grdowns @ras0219-msft we're going to start tagging once we start doing release notes right?

**Comment by karlhigley** [comment]
It looks like releases are now tagged, so it may now be possible to create a Homebrew formula that meets their guidelines.

**Comment by karlhigley** [comment]
Looks like there's [another PR on Homebrew](https://github.com/Homebrew/homebrew-core/pull/45002) to add a `vcpkg` formula.

**Comment by TonalidadeHidrica** [comment]
Seems that [it's been added recently](https://github.com/Homebrew/homebrew-core/pull/56259).  (I'm having a little trouble though...)
