### ISSUE TITLE
[opencascade] update to 7.8.0

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#35745]
### Library name

opencascade

### New version number

7.8.0

### Other information that may be useful (release notes, etc...)

https://dev.opencascade.org/content/open-cascade-technology-780-released

**Comment by paulbuechner** [comment]
Reminder to update Patches to account for:
- added 3rd_party `jemalloc` https://github.com/Open-Cascade-SAS/OCCT/commit/3aeea1e96edcafec9244e741eb48092bb05875c2
- added build optimizations https://github.com/Open-Cascade-SAS/OCCT/commit/7036facf10e5591ea93bb53d7e97097f82613729

**Comment by Neumann-A** [comment]
> added build optimizations https://github.com/Open-Cascade-SAS/OCCT/commit/7036facf10e5591ea93bb53d7e97097f82613729

Can be ignored. VCPKG mandates its own flags

**Comment by jimwang118** [comment]
> Reminder to update Patches to account for:
> 
> * added 3rd_party `jemalloc` [Open-Cascade-SAS/OCCT@3aeea1e](https://github.com/Open-Cascade-SAS/OCCT/commit/3aeea1e96edcafec9244e741eb48092bb05875c2)
> * added build optimizations [Open-Cascade-SAS/OCCT@7036fac](https://github.com/Open-Cascade-SAS/OCCT/commit/7036facf10e5591ea93bb53d7e97097f82613729)

I'll keep an eye out for updates.
