### ISSUE TITLE
[simonbrunel-qtpromise] QtPromise

### ISSUE THREAD

**Issue by carsten-grimm-at-ipolog** [microsoft/vcpkg#35752]
### Library name

QtPromise

### Library description

Promises/A+ implementation for Qt/C++

### Source repository URL

https://github.com/simonbrunel/qtpromise

### Project homepage (if different from the source repository)

https://qtpromise.netlify.app/

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

* This library is not an official part of Qt. 
* This is a header-only library. 
* It requires Qt5 or Qt6, specifically Qt5::Core or Qt6::Core. Hence, it should depend on `qt5-base` or `qtbase`. Perhaps, we need two variants of this port?
* It comes with CMake integration, as described [here](https://qtpromise.netlify.app/qtpromise/getting-started.html#cmake).

**Comment by Neumann-A** [comment]
name would be `simonbrunel-qtpromise`
