### ISSUE TITLE
[Broken Dependency Integration after new vcpkg release] build failure

### ISSUE THREAD

**Issue by R-Abbasi** [microsoft/vcpkg#35755]
### Operating system

Linux

### Compiler

GCC

### Steps to reproduce the behavior

```Shell
When trying to compile and build our project (https://github.com/skunkforce/OmniView) on Ubuntu, we faced the following `CMake` error:
```

### Failure logs

```
 _Could not find a package configuration file provided by "libusb" with any of the following names:
libusbConfig.cmake
libusb-config.cmake_
```

### Additional context

This is due to CMake not finding `libusb` via `find_package` which could also be reproduced in CI (https://github.com/skunkforce/omniview/actions/runs/7232145540/job/19706039412#step:9:1244)
After investigation, it was concluded, that CMake couldn't find `libusb`, since it was missing a `.cmake` file as is required for `Config Mode`. 

The last successful run appeared on 2023-12-12, which was the exact day of a new `vcpkg` release.
In that release which can be found here: https://github.com/microsoft/vcpkg/releases/tag/2023.12.12 a minor change happend.
Looking at the "updated ports" (https://github.com/microsoft/vcpkg/releases/tag/2023.12.12), `libusb` changed `1.0.26.11791#3` to `1.0.26.11791#5`.

Modifing `CMakeLists.txt` to clone the `2023.11.20` Release of `vcpkg` makes CMake happy:

```
FetchContent_Populate(
vcpkg
GIT_REPOSITORY https://github.com/microsoft/vcpkg.git
GIT_TAG        2023.11.20
SOURCE_DIR     "${CMAKE_SOURCE_DIR}/vcpkg"
)
```
Although this seems to be a possibility to mitigate the problem, it's, however, not clear what unintended consequences this might have for the future. 
Hopefully you fix this issue and we don't face such an error each time a new `vcpkg` releases.

**Comment by Osyotr** [comment]
Providing cmake config for `libusb` without `unofficial::` namespace was an error; fixed in #35498
Please read usage [ports/libusb/usage](https://github.com/microsoft/vcpkg/commit/8abeb71402ddb232304a53ceddf17f98a49cba9e#diff-420a9b4fcd2745f8b5f1529cbae82cd3aeae0d80952b3c6e2a325ce8551c230e)

**Comment by bjoekeldude** [comment]
Ahh, do I understand that correctly, that this happend on purpose and `PkgConfig` is the correct way to use it?
Is there a note or a discussion where I can read about why this was done?

**Comment by Osyotr** [comment]
> Ahh, do I understand that correctly, that this happend on purpose and PkgConfig is the correct way to use it?

If a library provides pkg-config files then it is correct way to use it.

> Is there a note or a discussion where I can read about why this was done?

Probably this https://github.com/microsoft/vcpkg/issues/35558#issuecomment-1846725980

**Comment by bjoekeldude** [comment]
Okay, got it. Thanks!

**Comment by Adela0814** [comment]
Please try the new usage:
```
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(libusb REQUIRED IMPORTED_TARGET libusb-1.0)

    target_link_libraries(main PRIVATE PkgConfig::libusb)
```

**Comment by pedroCX486** [comment]
> Please try the new usage:
> 
> ```
>     find_package(PkgConfig REQUIRED)
>     pkg_check_modules(libusb REQUIRED IMPORTED_TARGET libusb-1.0)
> 
>     target_link_libraries(main PRIVATE PkgConfig::libusb)
> ```

`CMake Error at CMakeLists.txt:13 (target_link_libraries):
  Cannot specify link libraries for target "main" which is not built by this
  project.

-- Configuring incomplete, errors occurred!
`

Sorry but these updates made things way more confusing than they should...

**Comment by Adela0814** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
