### ISSUE TITLE
Azure pipelines for PRs are broken

### ISSUE THREAD

**Issue by BewareMyPower** [microsoft/vcpkg#35757]
Example failures:

- https://dev.azure.com/vcpkg/public/_build/results?buildId=97804&view=logs&j=9676df49-6cba-5dc3-8ed9-3fbf18e9e6d5
- https://dev.azure.com/vcpkg/public/_build/results?buildId=97800&view=logs&j=d19a5126-c2c2-5341-7425-271d3c2e0d4c

```
 ##[error]The pipeline is not valid. Could not find a pool with name PrWin-2023-10-11. The pool does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.
```

**Comment by BillyONeal** [comment]
Fixed by https://github.com/microsoft/vcpkg/pull/35640 , sorry. :( (I thought I had merged that before getting rid of the vulnerable-from-October infrastructure...)
