### ISSUE TITLE
[_freeze_module_d.exe] build failure because of virus alert Gen:Variant.Lazy.417017

### ISSUE THREAD

**Issue by CplusplusB** [microsoft/vcpkg#35761]
### Operating system

Windows 10

### Steps to reproduce the behavior

```Shell
vcpkg install boost:x64-windows boost:x86-windows
```

### Failure logs

LINK : fatal error LNK1104: cannot open file 'C:\Users\XXXXXXX\Downloads\vcpkg-master\vcpkg-master\buildtrees\python3\x86-windows-dbg\PCbuild\win32\_freeze_module_d.exe'

-- Using cached python-cpython-v3.11.5.tar.gz.
-- Cleaning sources at C:/Users/XXXXXXX/Downloads/vcpkg-master/vcpkg-master/buildtrees/python3/src/v3.11.5-0fec99d163.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/XXXXXXX/Downloads/vcpkg-master/vcpkg-master/downloads/python-cpython-v3.11.5.tar.gz
-- Applying patch 0001-only-build-required-projects.patch
-- Applying patch 0003-use-vcpkg-zlib.patch
-- Applying patch 0004-devendor-external-dependencies.patch
-- Applying patch 0005-dont-copy-vcruntime.patch
-- Applying patch 0008-python.pc.patch
-- Applying patch 0010-dont-skip-rpath.patch
-- Applying patch 0012-force-disable-modules.patch
-- Applying patch 0014-fix-get-python-inc-output.patch
-- Applying patch 0015-dont-use-WINDOWS-def.patch
-- Applying patch 0018-fix-sysconfig-include.patch
-- Applying patch 0007-workaround-windows-11-sdk-rc-compiler-error.patch
-- Applying patch 0016-fix-win-cross.patch
-- Using source at C:/Users/XXXXXXX/Downloads/vcpkg-master/vcpkg-master/buildtrees/python3/src/v3.11.5-0fec99d163.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x86-windows
-- Building PCbuild/pcbuild.proj for Release
-- Building PCbuild/pcbuild.proj for Debug
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: msbuild C:/Users/XXXXXXX/Downloads/vcpkg-master/vcpkg-master/buildtrees/python3/x86-windows-dbg/PCbuild/pcbuild.proj /p:Configuration=Debug /p:IncludeExtensions=true /p:IncludeExternals=true /p:IncludeCTypes=true /p:IncludeSSL=true /p:IncludeTkinter=false /p:IncludeTests=false /p:ForceImportBeforeCppTargets=C:/Users/XXXXXXX/Downloads/vcpkg-master/vcpkg-master/buildtrees/python3/src/v3.11.5-0fec99d163.clean/PCbuild/python_vcpkg.props /p:IncludeUwp=false /p:_VcpkgPythonLinkage=DynamicLibrary /p:ForceImportAfterCppProps=C:/Users/XXXXXXX/Downloads/vcpkg-master/vcpkg-master/buildtrees/python3/x86-windows/vcpkg_msbuild.props /p:ForceImportAfterCppTargets=C:/Users/XXXXXXX/Downloads/vcpkg-master/vcpkg-master/buildtrees/python3/x86-windows/vcpkg_msbuild.targets /t:Rebuild /p:UseMultiToolTask=true /p:MultiProcMaxCount=13 /p:EnforceProcessCountAcrossBuilds=true /m:13 -maxCpuCount:13 /p:Platform=Win32 /p:PlatformTarget=x86 /p:PlatformToolset=v143 /p:WindowsTargetPlatformVersion=10.0.22621.0 /p:VcpkgApplocalDeps=false /p:VcpkgManifestInstall=false /p:VcpkgManifestEnabled=false /p:VcpkgEnabled=false /p:VcpkgTriplet=x86-windows /p:VcpkgInstalledDir=C:/Users/XXXXXXX/Downloads/vcpkg-master/vcpkg-master/installed
    Working Directory: C:/Users/XXXXXXX/Downloads/vcpkg-master/vcpkg-master/buildtrees/python3/x86-windows-dbg
    Error code: 1
    See logs for more information:
      C:\Users\XXXXXXX\Downloads\vcpkg-master\vcpkg-master\buildtrees\python3\build-x86-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-msbuild/vcpkg_msbuild_install.cmake:150 (vcpkg_execute_required_process)
  ports/python3/portfile.cmake:175 (vcpkg_msbuild_install)
  scripts/ports.cmake:170 (include)

error: building python3:x86-windows failed with: BUILD_FAILED
Elapsed time to handle python3:x86-windows: 4.9 min

### Additional context

As mentioned in the title, I want to compile vcpkg for windows 64 and 86, at some point I get an Virus alert for the _freeze_module_d.exe. Maybe it is an fake alert, can someone acknowledge this?
Addionally:
I noticed that the 64 build worked, its only in the x86 build at that point which is not working

**Comment by LilyWangLL** [comment]
Does your machine have firewall or anti-virus software? Maybe this affects the build.

**Comment by LilyWangLL** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
