### ISSUE TITLE
[openni2] Build error on x64-windows

### ISSUE THREAD

**Issue by herrwusel** [microsoft/vcpkg#35763]
Package: [openni2:x64-windows@2.2.0.33#15](mailto:openni2:x64-windows@2.2.0.33#15)

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.38.33133.0
-    vcpkg-tool version: 2023-12-12-1c9ec1978a6b0c2b39c9e9554a96e3e275f7556e
    vcpkg-scripts version: 0e47c1985 2023-12-15 (3 days ago)

**To Reproduce**

`vcpkg install openni2`
**Failure logs**

```
CMake Error at ports/openni2/portfile.cmake:3 (message):
  Could not find <cor.h>.  Ensure the NETFXSDK is installed.
Call Stack (most recent call first):
  scripts/ports.cmake:170 (include)



```

I found issue https://github.com/microsoft/vcpkg/issues/12039 with the difference that I have the SDK installed. `cor.h` can be found under `C:/Program File (x86)/Windows Kits/NETFXSDK/4.8.1/Include/um`. `vcpkg` is made available for the current, non-admin user only and the installation fails for said user.

I wrote a simple CMakeLists.txt that just contains the `find_path` part, and I could reproduce that CMake isn't able to find the `cor.h`. I could fix it by providing a `CMAKE_INCLUDE_PATH` environment variable. Is there something similar I could do for `vcpkg`?

**Comment by FrankXie05** [comment]
@herrwusel We recommend using vs to install `NETFXSDK` (`COR_H_PATH` is provided by default). 
Of course, you can manually pass in your locally installed `NETFXSDK` via `CMAKE_INCLUDE_PATH`.

**Comment by herrwusel** [comment]
Thank you for your reply! Interestingly enough I installed `NETFXSDK` via vs.
![hdRFbmoA54sb3W0X](https://github.com/microsoft/vcpkg/assets/8242787/022f610b-f9c7-48bf-a09f-84d82bfdab9c)
`COR_H_PATH` is not set though.

**Comment by herrwusel** [comment]
Manually setting `COR_H_PATH` and installing NET 4.7.2 solved this issue for me. Thanks!
