### ISSUE TITLE
can't install cmake 

### ISSUE THREAD

**Issue by z2665** [Microsoft/vcpkg#3576]
when run the vcpkg
Failed to do post-extract rename-in-place.
fs.rename(D:\vcpkg\vcpkg\downloads\tools\cmake-3.10.2-windows.partial, D:\vcpkg\vcpkg\downloads\tools\cmake-3.10.2-windows, operation not permitted)

**Comment by alvipeo** [comment]
same here

**Comment by repex** [comment]
Same here; a temporary workaround is to rename manually **cmake-3.10.2-windows.partial**
to **cmake-3.10.2-windows** and re-run the vcpkg command.

**Comment by d223chen** [comment]
same here, but for git instead of cmake...

**Comment by repex** [comment]
> @repex That worked for me! How did you figure that out?

The error message hinted that the rename operation was not successful, so i tried to perform it manually, and it worked.

**Comment by bowie7070** [comment]
I had this too (with cmake) and I simply repeated the install command (was trying to install boost-python) and it worked the second time.

**Comment by tzehetner** [comment]
In my case it was the virus scanner who blocked the operation. After disabling the virus scanner, it worked.

**Comment by NancyLi1013** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.

**Comment by sdustlhh** [comment]
> In my case it was the virus scanner that blocked the operation. After disabling the virus scanner, it worked.

This solve my problem.

**Comment by robertobernabe** [comment]
We also had this issue in our company. After adding an exception to our antivirus solution.
