### ISSUE TITLE
Set global compiler flag at the triplet level.

### ISSUE THREAD

**Issue by imback82** [microsoft/vcpkg#3577]
Hi,

Is there a way to set a global compiler flag at a triplet level?

For example, I want to set the -fPIC option and the following works:
vcpkg_configure_cmake(
     SOURCE_PATH ${SOURCE_PATH}
     -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=true)

If I want to set the flag for all the libraries I am installing, is there a way to do it at the triplet level?
I tried updating a triplet file with the following:
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
, but it is not honored.

Thanks,

**Comment by KindDragon** [comment]
You can try something like this https://github.com/KindDragon/vcpkg/blob/f35ff4c8bc0fbe52a3c5c78f74f7c33e550b12e1/ports/openexr/portfile.cmake#L22-L24

**Comment by Cheney-W** [comment]
Since KindDragon provided a good example, close this issue.

**Comment by retifrav** [comment]
I am late to the party, but for those who like me landed here from Google, if I got the current state of affairs right, then when not using `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` one can set the following variables in the triplet (*[vcpkg documentation](https://github.com/microsoft/vcpkg/blob/d8e60ef4741584f2957788ed0786dd365c92c4d9/docs/users/triplets.md#vcpkg_cxx_flags) on the matter*):

``` cmake
set(VCPKG_C_FLAGS   "-fPIC")
set(VCPKG_CXX_FLAGS "-fPIC")
# and so on for other flags
```

which in turn [should](https://github.com/microsoft/vcpkg/issues/11621#issuecomment-1120218812) get appended to `CMAKE_C_FLAGS_INIT` and `CMAKE_CXX_FLAGS_INIT` in the toolchain (*if the toolchain does that*), which then will be used to set `CMAKE_C_FLAGS` and `CMAKE_CXX_FLAGS` (*[CMake documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_FLAGS_INIT.html) on the matter*).

Now, I am not sure what "*when not using `VCPKG_CHAINLOAD_TOOLCHAIN_FILE`*" actually means, but I guess that in this case setting `VCPKG_*_FLAGS` won't have an effect (*certainly didn't for me*), and then one would need to set `CMAKE_*_FLAGS_INIT` in the chainloaded toolchain himself.

I encountered this when I was building for WASM with pthreads: I needed to set `-pthread` flag so it would apply to building all my dependencies, and the only way I've managed to make it work was by setting `CMAKE_*_FLAGS_INIT` in the chainloaded custom Emscripten toolchain.

**Comment by fwcd** [comment]
Regarding

> I needed to set -pthread flag so it would apply to building all my dependencies, and the only way I've managed to make it work was by setting CMAKE_*_FLAGS_INIT in the chainloaded custom Emscripten toolchain.

I've managed to make this work by adding

```cmake
set(ENV{EMCC_CFLAGS} "$ENV{EMCC_CFLAGS} -pthread")
```

to the triplet. See https://github.com/microsoft/vcpkg/discussions/30108.

**Comment by fwcd** [comment]
The inner `ENV{EMCC_FLAGS}` was to make sure that we append the flags instead of overriding them, in case we already set flags elsewhere. If unset, the substitution should just be empty. Though upon second thought outside env vars might not even be visible without adding them to `VCPKG_ENV_PASSTHROUGH_UNTRACKED`.

For other platforms replacing `EMCC_FLAGS` with `CFLAGS` and `CXXFLAGS` respectively might work, haven't tried it though.

All of this relies on the fact that environment variables set in the triplet will be visible during the build.

**Comment by retifrav** [comment]
> environment variables set in the triplet will be visible during the build

That part is clear, but what will get this variable value in the build (*or actually configuration*)? If I understood the way it would work is one would need to modify one's CMake project files, right? And so if I have 50+ dependencies, that are resolved with vcpkg, I would need to patch 50+ projects? :)

**Comment by fwcd** [comment]
These are standard flags that should be respected by all of the major compilers without tweaking the CMake configuration (at least I don't think CMake would override these?).

**Comment by retifrav** [comment]
> EMCC_FLAGS
> These are standard env vars

I don't see them in the [CMake documentation](https://cmake.org/cmake/help/latest/manual/cmake-env-variables.7.html). Are those documented elsewhere?

**Comment by fwcd** [comment]
https://emscripten.org/docs/tools_reference/emcc.html#environment-variables

**Comment by retifrav** [comment]
Oh, now I see. Should've checked the Emscripten documentation too.
Yes, that should work. And probably for other compilers too, as there seem to be environment variables for those as well, however, for instance for [CXXFLAGS](https://cmake.org/cmake/help/latest/envvar/CXXFLAGS.html) documentation says that:

> For any configuration run (including the first), the environment variable will be ignored if the [CMAKE_CXX_FLAGS](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_FLAGS.html#variable:CMAKE_%3CLANG%3E_FLAGS) variable is already defined
