### ISSUE TITLE
[qtwebengine] Build error on x64-windows

### ISSUE THREAD

**Issue by a980374208** [microsoft/vcpkg#35776]
vcpkg install qtwebengine[proprietary-codecs] --triplet x64-windows  --x-buildtrees-root=d:/web
Computing installation plan...
The following packages will be built and installed:
    qtwebengine[core,default-features,proprietary-codecs]:x64-windows@6.6.1#3
Detecting compiler hash for triplet x64-windows...
-- Automatically setting %HTTP(S)_PROXY% environment variables to "127.0.0.1:1080".
Restored 0 package(s) from C:\Users\Jiangbinbin\AppData\Local\vcpkg\archives in 99.7 us. Use --debug to see more details.
Installing 1/1 qtwebengine[core,default-features,proprietary-codecs]:x64-windows@6.6.1#3...
Building qtwebengine[core,default-features,proprietary-codecs]:x64-windows@6.6.1#3...
-- Setting up python virtual environmnent...
-- Installing python packages: html5lib
-- Setting up python virtual environmnent...finished.
-- Using cached qtwebengine-everywhere-src-6.6.1.tar.xz.
-- Cleaning sources at D:/web/qtwebengine/src/here-src-6-4f617c9365.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/qtwebengine-everywhere-src-6.6.1.tar.xz
-- Applying patch clang-cl.patch
-- Applying patch msvc-template.patch
-- Using source at D:/web/qtwebengine/src/here-src-6-4f617c9365.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j29
    Working Directory: D:/web/qtwebengine/x64-windows-dbg
    See logs for more information:
      D:\web\qtwebengine\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/qtwebengine/portfile.cmake:115 (vcpkg_cmake_install)
  scripts/ports.cmake:170 (include)

error: building qtwebengine:x64-windows failed with: BUILD_FAILED
Elapsed time to handle qtwebengine:x64-windows: 1.9 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qtwebengine
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[qtwebengine]+Build+error+on+x64-windows&body=Copy+issue+body+from+D%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/13715804/install-x64-windows-dbg-out.log)

**Comment by carsten-grimm-at-ipolog** [comment]
Hi @a980374208. 

Did you notice the link at the bottom of the error message in our post? When you access that link from your shell after the build, it will help you submit an issue here with all the relevant logs attached. That makes it much easier to help you.

**Comment by LilyWangLL** [comment]
Please provide the error log:
```
See logs for more information:
D:\web\qtwebengine\install-x64-windows-dbg-out.log
```

**Comment by a980374208** [comment]
Sorry may not be obvious D:webqtwebengineinstall-x64-windows-dbg-out.log download link at the bottom of the log

**Comment by a980374208** [comment]
> 请提供错误日志：
> 
> ```
> See logs for more information:
> D:\web\qtwebengine\install-x64-windows-dbg-out.log
> ```

Sorry may not be obvious D:webqtwebengineinstall-x64-windows-dbg-out.log download link at the bottom of the log

**Comment by a980374208** [comment]
> 嗨 [。]([Uploading install-x64-windows-dbg-out.log…]())
> 
> 您是否注意到我们帖子中错误消息底部的链接？当您在构建后从 shell 访问该链接时，它将帮助您在此处提交问题，并附加所有相关日志。这样一来，帮助您就容易多了。

Sorry may not be obvious D:webqtwebengineinstall-x64-windows-dbg-out.log download link at the bottom of the log

**Comment by a980374208** [comment]
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/13728253/install-x64-windows-dbg-out.log)
this is the error log

**Comment by LilyWangLL** [comment]
```
D:\web\qtwebengine\src\here-src-6-4f617c9365.clean\src\3rdparty\gn\src\gn\escape.h(1): error C2220: 以下警告被视为错误
D:\web\qtwebengine\src\here-src-6-4f617c9365.clean\src\3rdparty\gn\src\gn\escape.h(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
```

Please make sure you have the English language pack for VS installed.
And need set utf-8 locale in Windows settings, see https://www.cnblogs.com/walker-world/p/9548852.html.
![image](https://github.com/microsoft/vcpkg/assets/94091114/cf8916d7-635c-4d29-8c07-2d91dfcafdc8)

**Comment by a980374208** [comment]
> ```
> D:\web\qtwebengine\src\here-src-6-4f617c9365.clean\src\3rdparty\gn\src\gn\escape.h(1): error C2220: 以下警告被视为错误
> D:\web\qtwebengine\src\here-src-6-4f617c9365.clean\src\3rdparty\gn\src\gn\escape.h(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
> ```
> 
> Please make sure you have the English language pack for VS installed. And need set utf-8 locale in Windows settings, see https://www.cnblogs.com/walker-world/p/9548852.html. ![image](https://private-user-images.githubusercontent.com/94091114/292149604-cf8916d7-635c-4d29-8c07-2d91dfcafdc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNjU0MzksIm5iZiI6MTcwMzI2NTEzOSwicGF0aCI6Ii85NDA5MTExNC8yOTIxNDk2MDQtY2Y4OTE2ZDctNjM1Yy00ZDI5LThjMDctMmQ5MWRmY2FmZGM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDE3MTIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZTA4MWQxN2YyY2RmNDg5NGNmMTUxMjdkZTBlNWU1ZDE3YjdjNmIwNWFkNTJjZTY0ZjExYmMxYTRjZWJiOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1IsU5rYjPW7j32PwI8kqxOFNc4JK64xYzNE6KUBzLNE)

Thanks for following your tips, I have successfully compiled the debug version ,but when I compile the release version it is an error，please how to fix this error

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\xutility(1168): fatal error C1060: compiler is out of heap space

this  is  the  log:
[install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/13754613/install-x64-windows-rel-out.log)

**Comment by a980374208** [comment]
Thanks for following your tips, I have successfully compiled the debug version ,but when I compile the release version it is an error，please how to fix this error

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\xutility(1168): fatal error C1060: compiler is out of heap space

this  is  the  log:
[install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/13754613/install-x64-windows-rel-out.log)
