### ISSUE TITLE
[skia] build failure

### ISSUE THREAD

**Issue by StarGate-One** [microsoft/vcpkg#35784]
### Operating system

Windows 11 10.0.22631.2861 x64 Enterprise

### Compiler

Visual Studio Community 2022 Version: [17.8.3]  VS Tools Version: [14.37.32822]
Microsoft (R) C/C++ Optimizing Compiler Version [19.37.32826.1] for x64 

### Steps to reproduce the behavior

```Shell
PS D:\vcpkg>.\vcpkg.exe install skia[core,direct3d,fontconfig,freetype,gl,harfbuzz,vulkan]
```

### Failure logs

After the following PR changes:
[[vulkan] install required sdk parts (#35479)](https://github.com/microsoft/vcpkg/pull/35479)
Commit: 50bffcc62d7f6571eb32bc1a0b1807e77af1166c

The lines causing issue are found here [skia portfile.cmake](https://github.com/microsoft/vcpkg/blob/48e95d1aa3fedd24234f1d436226d07fc2b4f45f/ports/skia/portfile.cmake#L191-L203) but I am not able to find a correct solution?

Computing installation plan...
The following packages will be built and installed:
    skia[core,direct3d,fontconfig,freetype,gl,harfbuzz,vulkan]:x64-windows@0.38.2#1
Installing 1/1 skia[core,direct3d,fontconfig,freetype,gl,harfbuzz,vulkan]:x64-windows@0.38.2#1...
Building skia[core,direct3d,fontconfig,freetype,gl,harfbuzz,vulkan]:x64-windows@0.38.2#1...
-- Using cached google-skia-canvaskit_-0.38.2.tar.gz.
-- Extracting source D:/vcpkg/downloads/google-skia-canvaskit_-0.38.2.tar.gz
-- Applying patch disable-msvc-env-setup.patch
-- Applying patch uwp.patch
-- Applying patch disable-dev-test.patch
-- Applying patch skdebug-stdio.patch
-- Using source at D:/vcpkg/buildtrees/skia/src/it_-0.38.2-72617eb022.clean
>CMake Error at ports/skia/portfile.cmake:197 (file):
>  file COPY cannot find
>  "D:/vcpkg/installed/x64-windows/include/vk_mem_alloc.h": No error.
Call Stack (most recent call first):
  scripts/ports.cmake:170 (include)

error: building skia:x64-windows failed with: BUILD_FAILED
Elapsed time to handle skia:x64-windows: 2.8 s
Total install time: 2.8 s
RESULTS
  skia:x64-windows: BUILD_FAILED: 2.8 s

SUMMARY FOR x64-windows
  BUILD_FAILED: 1

### Additional context
Note 1: No other logs are produced except the `skia extract-err.log and extract-out.log` in `<vcpkg-root>\buildtrees\skia`.

Note 2: Omitting `feature vulkan` from the `vcpkg install` results in a successful build/install of port skia.

**Comment by Cheney-W** [comment]
I could reproduce this issue in my side with the latest vcpkg 2023-12-12-1c9ec1978a6b0c2b39c9e9554a96e3e275f7556e.

**Comment by StarGate-One** [comment]
Works great!!! 
Thank you very much @Cheney-W @dg0yt @vicroms!!!
