### ISSUE TITLE
[vcpkg-tool-meson] Install so many files

### ISSUE THREAD

**Issue by xiaozhuai** [microsoft/vcpkg#35795]
**Describe the bug**

It install so many files which seems useless, such as 
* `docs/*`
* `unittests/*`
* `manual tests/*`
* `ci/*`
* `.github/*`
* `test cases/*`
* ...

I don't know if this bebavior is by design.

When install it, it prints so many `-- Installing:` lines which almost flooded with installation logs.

Just  remind you guys. Close this issue if everything is fine.

[vcpkg-tool-meson_0.63_x64-osx.list.txt](https://github.com/microsoft/vcpkg/files/13726585/vcpkg-tool-meson_0.63_x64-osx.list.txt)

---

Note: 
Before #35003, it removed `test cases/*`.

**Comment by eli-schwartz** [comment]
https://github.com/microsoft/vcpkg/blob/master/ports/vcpkg-tool-meson/vcpkg-port-config.cmake
https://github.com/microsoft/vcpkg/blob/master/ports/vcpkg-tool-meson/portfile.cmake

It appears to copy the entire repository over, and then define a vcpkg "config" (SCRIPT_MESON) to the meson.py launcher script. No installation using distutils or anything.

This works fine, meson supports it quite well. But it should perhaps be noted that you are absolutely allowed to delete all the repository contents other than:
- mesonbuild/
- meson.py

Other options include creating a single-file "zipapp" script (a ZIP file with a python shebang) using `./packaging/create_zipapp.py`: https://mesonbuild.com/Getting-meson.html#packing-meson-into-a-zipapp

**Comment by dg0yt** [comment]
It is not just "many files". The port also seems to install symlinks which it fails to put into a ZIP, so there is no cacheable artifact. :angry:
