### ISSUE TITLE
[ERROR  RUN /opt/tools/entrypoint.sh ] entrypoint.sh File Not Found - build failure

### ISSUE THREAD

**Issue by ajithandro** [microsoft/vcpkg#35790]
### Operating system

Windows

### Compiler

MINGW64

### Steps to reproduce the behavior

```Shell
$ triplet=x64-android ./scripts/build.sh
```

### Failure logs

$ triplet=x64-android ./scripts/build.sh
[+] Building 0.0s (0/0)  docker:default
[+] Building 1721.4s (12/16)                                                                                                                                                                                          docker:default 
 => [internal] load .dockerignore                                                                                                                                                                                               0.6s 
 => => transferring context: 2B                                                                                                                                                                                                 0.2s 
 => [internal] load build definition from Dockerfile                                                                                                                                                                            0.7s 
 => => transferring dockerfile: 2.08kB                                                                                                                                                                                          0.4s 
 => [internal] load metadata for docker.io/library/ubuntu:22.04                                                                                                                                                                 3.6s 
 => [auth] library/ubuntu:pull token for registry-1.docker.io                                                                                                                                                                   0.0s 
 => CACHED [ 1/11] FROM docker.io/library/ubuntu:22.04@sha256:6042500cf4b44023ea1894effe7890666b0c5c7871ed83a97c36c76ae560bb9b                                                                                                  0.0s 
 => [internal] load build context                                                                                                                                                                                               0.3s 
 => => transferring context: 673B                                                                                                                                                                                               0.1s 
 => [ 2/11] RUN dpkg --add-architecture i386 && apt-get update -yqq && apt-get install -y   curl   expect   git   make   libc6:i386   libgcc1:i386   libncurses5:i386   libstdc++6:i386   zlib1g:i386   openjdk-11-jdk   wg  1711.2s 
 => [ 3/11] RUN groupadd android && useradd -d /opt/android-sdk-linux -g android -u 1000 android                                                                                                                        4.5s opt=> [ 4/11] COPY tools /opt/tools                                                                                                                                                                                       0.2s 
 => [ 5/11] COPY licenses /opt/licenses                                                                                                                                                                                 0.2s 
 => [ 6/11] WORKDIR /opt/android-sdk-linux                                                                                                                                                                              0.3s 
 => ERROR [ 7/11] RUN /opt/tools/entrypoint.sh built-in                                                                                                                                                                 0.8s 
------
 > [ 7/11] RUN /opt/tools/entrypoint.sh built-in:    
0.691 /bin/sh: 1: /opt/tools/entrypoint.sh: not found
------
Dockerfile:65
--------------------
  63 |     WORKDIR /opt/android-sdk-linux
  64 |
  65 | >>> RUN /opt/tools/entrypoint.sh built-in
  66 |
  67 |     RUN yes | /opt/android-sdk-linux/cmdline-tools/latest/bin/sdkmanager --licenses && /opt/android-sdk-linux/cmdline-tools/latest/bin/sdkmanager "ndk;${NDK_VERSION}"
--------------------
ERROR: failed to solve: process "/bin/sh -c /opt/tools/entrypoint.sh built-in" did not complete successfully: exit code: 127

View build details: docker-desktop://dashboard/build/default/default/bkyofns84t50xhnf0gww5jvnp

**Comment by FrankXie05** [comment]
```
=> [ 3/11] RUN groupadd android && useradd -d /opt/android-sdk-linux -g android -u 1000 android 4.5s opt=> [ 4/11] COPY tools /opt/tools 0.2s
```
It seems that there is a problem with your Docker image configuration. Please clear cache and use the latest sdk.

**Comment by ajithandro** [comment]
Hi @FrankXie05,
I need to build the **QField Android Platform Application Locally on my Windows Machine,** Once Build is Completed, Then I am Planning to Try Some Customization on this If Possible. 
I have tried the procedures mentioned in the dev document, but I keep getting different build failure issues on this.
Can you please share the procedure to build an Android application locally?

What I tried as of Now:
1. Installed **Docker**
2. Installed **Cmake**
3. To Install **aqtinstal**l Installed **pip3**  using [https://bootstrap.pypa.io/get-pip.py](https://bootstrap.pypa.io/get-pip.py)
4. Tried the `Cmake -S <SorucePath> -B <Build>`

[https://github.com/opengisch/QField/blob/master/doc/dev.md](https://github.com/opengisch/QField/blob/master/doc/dev.md)

**Comment by dg0yt** [comment]
The problem is unrelated to vcpkg. Ask for help at QField.

**Comment by FrankXie05** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can ping me with more info and I will reopen.
