### ISSUE TITLE
[liblzma] Build error on x64-windows   Please ensure you're using the latest port files with `git pull` and `vcpkg update`

### ISSUE THREAD

**Issue by CharleyHsiung** [microsoft/vcpkg#35807]
**install-x64-windows-dbg-out.log**
intdir=CMakeFiles\liblzma.dir --rc="D:\Windows Kits\10\bin\10.0.17763.0\x64\rc.exe" --mt="D:\Windows Kits\10\bin\10.0.17763.0\x64\mt.exe" --manifests  -- "D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\link.exe"  CMakeFiles\liblzma.dir\src\common\tuklib_physmem.c.obj CMakeFiles\liblzma.dir\src\liblzma\check\check.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\block_util.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\common.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\easy_preset.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\filter_common.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\hardware_physmem.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\index.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_flags_common.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\string_conversion.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\vli_size.c.obj CMakeFiles\liblzma.dir\src\liblzma\check\crc32_fast.c.obj CMakeFiles\liblzma.dir\src\liblzma\check\crc32_table.c.obj CMakeFiles\liblzma.dir\src\liblzma\check\crc64_fast.c.obj CMakeFiles\liblzma.dir\src\liblzma\check\crc64_table.c.obj CMakeFiles\liblzma.dir\src\liblzma\check\sha256.c.obj CMakeFiles\liblzma.dir\src\common\tuklib_cpucores.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\hardware_cputhreads.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\outqueue.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\alone_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\block_buffer_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\block_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\block_header_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\easy_buffer_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\easy_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\easy_encoder_memusage.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\filter_buffer_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\filter_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\filter_flags_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\index_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_buffer_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_flags_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\vli_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_encoder_mt.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\simple_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\lzma_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\lzma_encoder_optimum_fast.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\lzma_encoder_optimum_normal.c.obj CMakeFiles\liblzma.dir\src\liblzma\lz\lz_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\lz\lz_encoder_mf.c.obj CMakeFiles\liblzma.dir\src\liblzma\rangecoder\price_table.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\fastpos_table.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\lzma2_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\delta\delta_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\alone_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\auto_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\block_buffer_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\block_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\block_header_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\easy_decoder_memusage.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\file_info.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\filter_buffer_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\filter_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\filter_flags_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\index_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\index_hash.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_buffer_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_flags_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\vli_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_decoder_mt.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\simple_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\lzma_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\lz\lz_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\lzma2_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\delta\delta_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\lzma_encoder_presets.c.obj CMakeFiles\liblzma.dir\src\liblzma\delta\delta_common.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\simple_coder.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\x86.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\arm.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\armthumb.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\arm64.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\powerpc.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\ia64.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\sparc.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\microlzma_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\microlzma_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\lzip_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\liblzma_w32res.rc.res  /out:liblzma.dll /implib:lzma.lib /pdb:liblzma.pdb /dll /version:5.4 /machine:x64 /nologo    /debug /INCREMENTAL  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd ."
FAILED: liblzma.dll lzma.lib 
C:\WINDOWS\system32\cmd.exe /C "cd . && "D:\Program Files\CMake\bin\cmake.exe" -E vs_link_dll --intdir=CMakeFiles\liblzma.dir --rc="D:\Windows Kits\10\bin\10.0.17763.0\x64\rc.exe" --mt="D:\Windows Kits\10\bin\10.0.17763.0\x64\mt.exe" --manifests  -- "D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\link.exe"  CMakeFiles\liblzma.dir\src\common\tuklib_physmem.c.obj CMakeFiles\liblzma.dir\src\liblzma\check\check.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\block_util.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\common.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\easy_preset.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\filter_common.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\hardware_physmem.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\index.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_flags_common.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\string_conversion.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\vli_size.c.obj CMakeFiles\liblzma.dir\src\liblzma\check\crc32_fast.c.obj CMakeFiles\liblzma.dir\src\liblzma\check\crc32_table.c.obj CMakeFiles\liblzma.dir\src\liblzma\check\crc64_fast.c.obj CMakeFiles\liblzma.dir\src\liblzma\check\crc64_table.c.obj CMakeFiles\liblzma.dir\src\liblzma\check\sha256.c.obj CMakeFiles\liblzma.dir\src\common\tuklib_cpucores.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\hardware_cputhreads.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\outqueue.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\alone_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\block_buffer_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\block_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\block_header_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\easy_buffer_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\easy_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\easy_encoder_memusage.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\filter_buffer_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\filter_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\filter_flags_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\index_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_buffer_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_flags_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\vli_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_encoder_mt.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\simple_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\lzma_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\lzma_encoder_optimum_fast.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\lzma_encoder_optimum_normal.c.obj CMakeFiles\liblzma.dir\src\liblzma\lz\lz_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\lz\lz_encoder_mf.c.obj CMakeFiles\liblzma.dir\src\liblzma\rangecoder\price_table.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\fastpos_table.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\lzma2_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\delta\delta_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\alone_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\auto_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\block_buffer_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\block_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\block_header_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\easy_decoder_memusage.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\file_info.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\filter_buffer_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\filter_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\filter_flags_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\index_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\index_hash.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_buffer_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_flags_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\vli_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_decoder_mt.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\simple_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\lzma_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\lz\lz_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\lzma2_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\delta\delta_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\lzma_encoder_presets.c.obj CMakeFiles\liblzma.dir\src\liblzma\delta\delta_common.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\simple_coder.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\x86.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\arm.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\armthumb.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\arm64.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\powerpc.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\ia64.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\sparc.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\microlzma_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\microlzma_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\lzip_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\liblzma_w32res.rc.res  /out:liblzma.dll /implib:lzma.lib /pdb:liblzma.pdb /dll /version:5.4 /machine:x64 /nologo    /debug /INCREMENTAL  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd ."
LINK Pass 1: command "D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\link.exe CMakeFiles\liblzma.dir\src\common\tuklib_physmem.c.obj CMakeFiles\liblzma.dir\src\liblzma\check\check.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\block_util.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\common.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\easy_preset.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\filter_common.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\hardware_physmem.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\index.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_flags_common.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\string_conversion.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\vli_size.c.obj CMakeFiles\liblzma.dir\src\liblzma\check\crc32_fast.c.obj CMakeFiles\liblzma.dir\src\liblzma\check\crc32_table.c.obj CMakeFiles\liblzma.dir\src\liblzma\check\crc64_fast.c.obj CMakeFiles\liblzma.dir\src\liblzma\check\crc64_table.c.obj CMakeFiles\liblzma.dir\src\liblzma\check\sha256.c.obj CMakeFiles\liblzma.dir\src\common\tuklib_cpucores.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\hardware_cputhreads.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\outqueue.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\alone_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\block_buffer_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\block_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\block_header_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\easy_buffer_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\easy_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\easy_encoder_memusage.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\filter_buffer_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\filter_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\filter_flags_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\index_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_buffer_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_flags_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\vli_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_encoder_mt.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\simple_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\lzma_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\lzma_encoder_optimum_fast.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\lzma_encoder_optimum_normal.c.obj CMakeFiles\liblzma.dir\src\liblzma\lz\lz_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\lz\lz_encoder_mf.c.obj CMakeFiles\liblzma.dir\src\liblzma\rangecoder\price_table.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\fastpos_table.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\lzma2_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\delta\delta_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\alone_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\auto_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\block_buffer_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\block_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\block_header_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\easy_decoder_memusage.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\file_info.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\filter_buffer_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\filter_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\filter_flags_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\index_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\index_hash.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_buffer_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_flags_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\vli_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_decoder_mt.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\simple_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\lzma_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\lz\lz_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\lzma2_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\delta\delta_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\lzma_encoder_presets.c.obj CMakeFiles\liblzma.dir\src\liblzma\delta\delta_common.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\simple_coder.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\x86.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\arm.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\armthumb.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\arm64.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\powerpc.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\ia64.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\sparc.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\microlzma_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\microlzma_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\lzip_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\liblzma_w32res.rc.res /out:liblzma.dll /implib:lzma.lib /pdb:liblzma.pdb /dll /version:5.4 /machine:x64 /nologo /debug /INCREMENTAL kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\liblzma.dir/intermediate.manifest CMakeFiles\liblzma.dir/manifest.res" failed (exit code 1104) with the following output:
LINK : fatal error LNK1104: �޷����ļ���CMakeFiles\liblzma.dir\src\liblzma\liblzma_w32res.rc.res��
ninja: build stopped: subcommand failed.

**install-x64-windows-dbg-out-1.log**
LINK Pass 1: command "D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\link.exe CMakeFiles\liblzma.dir\src\common\tuklib_physmem.c.obj CMakeFiles\liblzma.dir\src\liblzma\check\check.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\block_util.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\common.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\easy_preset.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\filter_common.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\hardware_physmem.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\index.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_flags_common.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\string_conversion.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\vli_size.c.obj CMakeFiles\liblzma.dir\src\liblzma\check\crc32_fast.c.obj CMakeFiles\liblzma.dir\src\liblzma\check\crc32_table.c.obj CMakeFiles\liblzma.dir\src\liblzma\check\crc64_fast.c.obj CMakeFiles\liblzma.dir\src\liblzma\check\crc64_table.c.obj CMakeFiles\liblzma.dir\src\liblzma\check\sha256.c.obj CMakeFiles\liblzma.dir\src\common\tuklib_cpucores.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\hardware_cputhreads.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\outqueue.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\alone_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\block_buffer_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\block_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\block_header_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\easy_buffer_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\easy_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\easy_encoder_memusage.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\filter_buffer_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\filter_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\filter_flags_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\index_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_buffer_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_flags_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\vli_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_encoder_mt.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\simple_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\lzma_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\lzma_encoder_optimum_fast.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\lzma_encoder_optimum_normal.c.obj CMakeFiles\liblzma.dir\src\liblzma\lz\lz_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\lz\lz_encoder_mf.c.obj CMakeFiles\liblzma.dir\src\liblzma\rangecoder\price_table.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\fastpos_table.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\lzma2_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\delta\delta_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\alone_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\auto_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\block_buffer_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\block_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\block_header_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\easy_decoder_memusage.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\file_info.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\filter_buffer_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\filter_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\filter_flags_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\index_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\index_hash.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_buffer_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_flags_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\vli_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\stream_decoder_mt.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\simple_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\lzma_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\lz\lz_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\lzma2_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\delta\delta_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\lzma\lzma_encoder_presets.c.obj CMakeFiles\liblzma.dir\src\liblzma\delta\delta_common.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\simple_coder.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\x86.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\arm.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\armthumb.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\arm64.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\powerpc.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\ia64.c.obj CMakeFiles\liblzma.dir\src\liblzma\simple\sparc.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\microlzma_encoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\microlzma_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\common\lzip_decoder.c.obj CMakeFiles\liblzma.dir\src\liblzma\liblzma_w32res.rc.res /out:liblzma.dll /implib:lzma.lib /pdb:liblzma.pdb /dll /version:5.4 /machine:x64 /nologo /debug /INCREMENTAL kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\liblzma.dir/intermediate.manifest CMakeFiles\liblzma.dir/manifest.res" failed (exit code 1104) with the following output:
LINK : fatal error LNK1104: 锟睫凤拷锟斤拷锟侥硷拷锟斤拷CMakeFiles\liblzma.dir\src\liblzma\liblzma_w32res.rc.res锟斤拷
ninja: build stopped: subcommand failed.

**Comment by FrankXie05** [comment]
```
LINK : fatal error LNK1104: �޷����ļ���CMakeFiles\liblzma.dir\src\liblzma\liblzma_w32res.rc.res��
```
Please use English path.

**Comment by FrankXie05** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can ping me with more info and I will reopen.
