### ISSUE TITLE
grpc build fails.

### ISSUE THREAD

**Issue by navidR** [Microsoft/vcpkg#3580]
It seems [this](https://github.com/Microsoft/vcpkg/commit/5e754c1d44155821702233649dc28c44cb9342bd#diff-7666dcad813b2830b29473617ed910d5) commit causes the grpc build to fail on Linux.

> vcpkg install grpc
> The following packages will be built and installed:
>     grpc[core]:x64-linux
> Starting package 1/1: grpc:x64-linux
> Building package grpc[core]:x64-linux... 
> -- CURRENT_INSTALLED_DIR=/opt/vcpkg/installed/x64-linux
> -- DOWNLOADS=/opt/vcpkg/downloads
> -- CURRENT_PACKAGES_DIR=/opt/vcpkg/packages/grpc_x64-linux
> -- CURRENT_BUILDTREES_DIR=/opt/vcpkg/buildtrees/grpc
> -- CURRENT_PORT_DIR=/opt/vcpkg/ports/grpc
> -- Using cached /opt/vcpkg/downloads/grpc-grpc-v1.10.1.tar.gz
> -- Testing integrity of cached file...
> -- Testing integrity of cached file... OK
> -- Configuring x64-linux-dbg
> -- Configuring x64-linux-dbg done
> -- Configuring x64-linux-rel
> -- Configuring x64-linux-rel done
> -- Build x64-linux-dbg
> CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:170 (message):
>     Command failed: /opt/vcpkg/downloads/tools/cmake-3.10.2-linux/cmake-3.10.2-Linux-x86_64/bin/cmake;--build;.;--config;Debug;--target;install;--;-v;-j1
>     Working Directory: /opt/vcpkg/buildtrees/grpc/x64-linux-dbg
>     See logs for more information:
>       /opt/vcpkg/buildtrees/grpc/install-x64-linux-dbg-out.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
>   ports/grpc/portfile.cmake:61 (vcpkg_install_cmake)
>   scripts/ports.cmake:72 (include)
> 
> 
> Error: Building package grpc:x64-linux failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: grpc:x64-linux
>   Vcpkg version: 0.0.113-unknownhash
> 
> Additionally, attach any relevant sections from the log files above.
>

**Comment by sanxiyn** [comment]
grpc:x64-linux installs fine and this is unreproducible.

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
