### ISSUE TITLE
folly build fails.

### ISSUE THREAD

**Issue by navidR** [Microsoft/vcpkg#3581]
> The following packages will be built and installed:
>     folly[core,zlib]:x64-linux
> Starting package 1/1: folly:x64-linux
> Building package folly[core,zlib]:x64-linux... 
> -- CURRENT_INSTALLED_DIR=/opt/vcpkg/installed/x64-linux
> -- DOWNLOADS=/opt/vcpkg/downloads
> -- CURRENT_PACKAGES_DIR=/opt/vcpkg/packages/folly_x64-linux
> -- CURRENT_BUILDTREES_DIR=/opt/vcpkg/buildtrees/folly
> -- CURRENT_PORT_DIR=/opt/vcpkg/ports/folly
> -- Using cached /opt/vcpkg/downloads/facebook-folly-v2018.05.14.00.tar.gz
> -- Testing integrity of cached file...
> -- Testing integrity of cached file... OK
> -- Configuring x64-linux-dbg
> -- Configuring x64-linux-dbg done
> -- Configuring x64-linux-rel
> -- Configuring x64-linux-rel done
> -- Build x64-linux-dbg
> CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:170 (message):
>     Command failed: /opt/vcpkg/downloads/tools/cmake-3.10.2-linux/cmake-3.10.2-Linux-x86_64/bin/cmake;--build;.;--config;Debug;--target;install;--;-v;-j1
>     Working Directory: /opt/vcpkg/buildtrees/folly/x64-linux-dbg
>     See logs for more information:
>       /opt/vcpkg/buildtrees/folly/install-x64-linux-dbg-out.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
>   ports/folly/portfile.cmake:71 (vcpkg_install_cmake)
>   scripts/ports.cmake:72 (include)
> 
> 
> Error: Building package folly:x64-linux failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: folly:x64-linux
>   Vcpkg version: 0.0.113-unknownhash
> 
> Additionally, attach any relevant sections from the log files above.

It is interesting to look at the ninja out put too:

> cc1plus: all warnings being treated as errors
> [30/204] /usr/bin/c++  -DFOLLY_XLOG_STRIP_PREFIXES=\"/opt/vcpkg/buildtrees/folly/src/8.05.14.00-e96738be27:/opt/vcpkg/buildtrees/folly/x64-linux-dbg\" -DGFLAGS_DLL_DECLARE_FLAG="" -DGFLAGS_DLL_DEFINE_FLAG="" -DGFLAGS_IS_A_DLL=0 -DGOOGLE_GLOG_DLL_DECL="" -D_GNU_SOURCE -D_REENTRANT -I/opt/vcpkg/installed/x64-linux/include -I/opt/vcpkg/buildtrees/folly/src/8.05.14.00-e96738be27 -I. -g -Wall -Wextra   -g -std=gnu++14 -finput-charset=UTF-8 -fsigned-char -Werror -Wall -Wno-deprecated -Wdeprecated-declarations -Wno-error=deprecated-declarations -Wno-sign-compare -Wno-unused -Wunused-label -Wunused-result -Wnon-virtual-dtor -Wshadow-compatible-local -Wno-noexcept-type -faligned-new -fopenmp -MD -MT CMakeFiles/folly_base.dir/folly/json.cpp.o -MF CMakeFiles/folly_base.dir/folly/json.cpp.o.d -o CMakeFiles/folly_base.dir/folly/json.cpp.o -c /opt/vcpkg/buildtrees/folly/src/8.05.14.00-e96738be27/folly/json.cpp
> FAILED: CMakeFiles/folly_base.dir/folly/json.cpp.o 
> /usr/bin/c++  -DFOLLY_XLOG_STRIP_PREFIXES=\"/opt/vcpkg/buildtrees/folly/src/8.05.14.00-e96738be27:/opt/vcpkg/buildtrees/folly/x64-linux-dbg\" -DGFLAGS_DLL_DECLARE_FLAG="" -DGFLAGS_DLL_DEFINE_FLAG="" -DGFLAGS_IS_A_DLL=0 -DGOOGLE_GLOG_DLL_DECL="" -D_GNU_SOURCE -D_REENTRANT -I/opt/vcpkg/installed/x64-linux/include -I/opt/vcpkg/buildtrees/folly/src/8.05.14.00-e96738be27 -I. -g -Wall -Wextra   -g -std=gnu++14 -finput-charset=UTF-8 -fsigned-char -Werror -Wall -Wno-deprecated -Wdeprecated-declarations -Wno-error=deprecated-declarations -Wno-sign-compare -Wno-unused -Wunused-label -Wunused-result -Wnon-virtual-dtor -Wshadow-compatible-local -Wno-noexcept-type -faligned-new -fopenmp -MD -MT CMakeFiles/folly_base.dir/folly/json.cpp.o -MF CMakeFiles/folly_base.dir/folly/json.cpp.o.d -o CMakeFiles/folly_base.dir/folly/json.cpp.o -c /opt/vcpkg/buildtrees/folly/src/8.05.14.00-e96738be27/folly/json.cpp
> In file included from /opt/vcpkg/installed/x64-linux/include/boost/mpl/aux_/na_assert.hpp:23,
>                  from /opt/vcpkg/installed/x64-linux/include/boost/mpl/arg.hpp:25,
>                  from /opt/vcpkg/installed/x64-linux/include/boost/mpl/placeholders.hpp:24,
>                  from /opt/vcpkg/installed/x64-linux/include/boost/iterator/iterator_categories.hpp:16,
>                  from /opt/vcpkg/installed/x64-linux/include/boost/iterator/iterator_adaptor.hpp:12,
>                  from /opt/vcpkg/buildtrees/folly/src/8.05.14.00-e96738be27/folly/dynamic-inl.h:20,
>                  from /opt/vcpkg/buildtrees/folly/src/8.05.14.00-e96738be27/folly/dynamic.h:605,
>                  from /opt/vcpkg/buildtrees/folly/src/8.05.14.00-e96738be27/folly/json.h:48,
>                  from /opt/vcpkg/buildtrees/folly/src/8.05.14.00-e96738be27/folly/json.cpp:16:
> /opt/vcpkg/installed/x64-linux/include/boost/mpl/assert.hpp:188:21: error: unnecessary parentheses in declaration of ‘assert_arg’ [-Werror=parentheses]
>  failed ************ (Pred::************
>                      ^
> /opt/vcpkg/installed/x64-linux/include/boost/mpl/assert.hpp:193:21: error: unnecessary parentheses in declaration of ‘assert_not_arg’ [-Werror=parentheses]
>  failed ************ (boost::mpl::not_<Pred>::************
>                      ^
> cc1plus: all warnings being treated as errors
> ninja: build stopped: subcommand failed.
>

**Comment by KindDragon** [comment]
It's boost error with gcc 8 https://github.com/boostorg/mpl/pull/34

**Comment by navidR** [comment]
Yes, you are right. I haven't looked it up before posting the issue because of the time limit. This issue can be closed.
