### ISSUE TITLE
[gstreamer] Need a usage like other ports

### ISSUE THREAD

**Issue by Arlen-LT** [microsoft/vcpkg#35811]
### Is your feature request related to a problem? Please describe.

There is no usage in this port, please add one.

### Proposed solution

like `pkg_check_modules`

**Comment by autoantwort** [comment]
If you use the latest vcpkg-tool (`git pull` + `./bootstrap.sh`) you get a pkgconfig usage

**Comment by JonLiu1993** [comment]
@Arlen-LT, Use the latest vcpkg looks gstreamer already provide pkgconfig usage:
````
gstreamer provides pkg-config modules:

    # Streaming media framework
    gstreamer-1.0

    # Allocators implementation
    gstreamer-allocators-1.0

    # Helper functions and base classes for application integration
    gstreamer-app-1.0

    # Audio helper functions and base classes
    gstreamer-audio-1.0

    # Base classes for GStreamer elements
    gstreamer-base-1.0

    # Dynamic parameter control for GStreamer elements
    gstreamer-controller-1.0

    # FFT implementation
    gstreamer-fft-1.0

    # Streaming media framework, OpenGL plugins libraries
    gstreamer-gl-1.0

    # Streaming media framework, OpenGL plugins libraries (OpenGL Prototypes)
    gstreamer-gl-prototypes-1.0

    # Network-enabled GStreamer plug-ins and clocking
    gstreamer-net-1.0

    # General utility functions
    gstreamer-pbutils-1.0

    # Streaming media framework, base plugins libraries
    gstreamer-plugins-base-1.0

    # RIFF helper functions
    gstreamer-riff-1.0

    # RTP base classes and helper functions
    gstreamer-rtp-1.0

    # RTSP base classes and helper functions
    gstreamer-rtsp-1.0

    # SDP helper functions
    gstreamer-sdp-1.0

    # Tag base classes and helper functions
    gstreamer-tag-1.0

    # Video base classes and helper functions
    gstreamer-video-1.0
````

**Comment by Arlen-LT** [comment]
> @Arlen-LT, Use the latest vcpkg looks gstreamer already provide pkgconfig usage:
> 
> ```
> gstreamer provides pkg-config modules:
> 
>     # Streaming media framework
>     gstreamer-1.0
> 
>     # Allocators implementation
>     gstreamer-allocators-1.0
> 
>     # Helper functions and base classes for application integration
>     gstreamer-app-1.0
> 
>     # Audio helper functions and base classes
>     gstreamer-audio-1.0
> 
>     # Base classes for GStreamer elements
>     gstreamer-base-1.0
> 
>     # Dynamic parameter control for GStreamer elements
>     gstreamer-controller-1.0
> 
>     # FFT implementation
>     gstreamer-fft-1.0
> 
>     # Streaming media framework, OpenGL plugins libraries
>     gstreamer-gl-1.0
> 
>     # Streaming media framework, OpenGL plugins libraries (OpenGL Prototypes)
>     gstreamer-gl-prototypes-1.0
> 
>     # Network-enabled GStreamer plug-ins and clocking
>     gstreamer-net-1.0
> 
>     # General utility functions
>     gstreamer-pbutils-1.0
> 
>     # Streaming media framework, base plugins libraries
>     gstreamer-plugins-base-1.0
> 
>     # RIFF helper functions
>     gstreamer-riff-1.0
> 
>     # RTP base classes and helper functions
>     gstreamer-rtp-1.0
> 
>     # RTSP base classes and helper functions
>     gstreamer-rtsp-1.0
> 
>     # SDP helper functions
>     gstreamer-sdp-1.0
> 
>     # Tag base classes and helper functions
>     gstreamer-tag-1.0
> 
>     # Video base classes and helper functions
>     gstreamer-video-1.0
> ```

Thanks a lot, by updating 2023-12-12 vcpkg executable file I can see the usage

**Comment by vipcxj** [comment]
@Arlen-LT  Can anyone provide a real-world usable example? I've used the pkg_check_modules command and it compiles successfully, but at runtime it gives me an error due to missing DLLs!
