### ISSUE TITLE
Updated: Downloading vcpkg-glibc...

### ISSUE THREAD

**Issue by Sh3Ns** [microsoft/vcpkg#35816]
### Operating system

x64-ubuntu 20.4

### Steps to reproduce the behavior

```Shell
git clone https://github.com/Microsoft/vcpkg.git

When I excute second step 
./vcpkg/bootstrap-vcpkg.sh
```

### Failure logs

Downloading vcpkg-glibc...
vcpkg package management program version 2023-12-12-1c9ec1978a6b0c2b39c9e9554a96e3e275f7556e

See LICENSE.txt for license information.
Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md

### Additional context

I'm trying to download vcpkg and it doesn't get past this step.

**Comment by autoantwort** [comment]
Is there a vcpkg executable in your vcpkg folder?

**Comment by dg0yt** [comment]
Note that
~~~
vcpkg package management program version 2023-12-12-1c9ec1978a6b0c2b39c9e9554a96e3e275f7556e
~~~
is the output of the executable...

**Comment by autoantwort** [comment]
Well...

**Comment by Sh3Ns** [comment]
> Is there a vcpkg executable in your vcpkg folder?

Yes, there is.

**Comment by dg0yt** [comment]
Bootstrapping completed successfully.

**Comment by Sh3Ns** [comment]
> Bootstrapping completed successfully.

what to say ?

**Comment by autoantwort** [comment]
@Sh3Ns What is your question?

**Comment by Sh3Ns** [comment]
> @Sh3Ns What is your question?
I can't install the package (pkg). In this case, how can I resolve it?

**Comment by Sh3Ns** [comment]
> @Sh3Ns What is your question?

I can't install the package (pkg). In this case, how can I resolve it?

**Comment by autoantwort** [comment]
What package? Can you show an error message?

**Comment by Sh3Ns** [comment]
does not install the GNU dependencies when I run the command ```./bootstrap-vcpkg.sh ```and that msg appears and stops execution...

**Comment by Sh3Ns** [comment]
and here

```Downloading vcpkg-glibc...
vcpkg package management program version 2023-12-12-1c9ec1978a6b0c2b39c9e9554a96e3e275f7556e

See LICENSE.txt for license information.
Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.
```
Read more about vcpkg telemetry at docs/about/privacy.md

**Comment by autoantwort** [comment]
Yeah that is the normal expected output ....

**Comment by Sh3Ns** [comment]
Yes, now I understand that it's a way out, if I don't install the dependencies in GNU I can't compile it, you know. Why are you more of a layman than me asking the question...

**Comment by dg0yt** [comment]
It is really not clear what stops you now from doing a
~~~
cd vcpkg
./vcpkg install zlib
~~~
if you want to build zlib.
So that's why there is a need to ask what kind of success you expect to see, or what kind of error you actual see.

**Comment by Sh3Ns** [comment]
Follow how I'm doing my dear gentlemen

![install](https://github.com/microsoft/vcpkg/assets/50599143/e1614612-62a1-48e9-a8d5-4d4ea37d78af)

**Comment by Sh3Ns** [comment]
and second...



![install 2](https://github.com/microsoft/vcpkg/assets/50599143/9c51ac35-47eb-49be-880b-a976e1a2a97f)


> It is really not clear what stops you now from doing a
> 
> ```
> cd vcpkg
> ./vcpkg install zlib
> ```
> 
> if you want to build zlib. So that's why there is a need to ask what kind of success you expect to see, or what kind of error you actual see.

**Comment by Sh3Ns** [comment]
> It is really not clear what stops you now from doing a
> 
> ```
> cd vcpkg
> ./vcpkg install zlib
> ```
> 
> if you want to build zlib. So that's why there is a need to ask what kind of success you expect to see, or what kind of error you actual see.

I also tried this without success, I need to install it to compile, right?

**Comment by autoantwort** [comment]
In your video everything works as expected 👍

**Comment by Sh3Ns** [comment]
> In your video everything works as expected 👍

you should install dependencies of GNU dear

**Comment by Sh3Ns** [comment]
I thought this was an error, but note: I was able to compile and perform some steps. Thank you for your attention.
