### ISSUE TITLE
[vulkan-memory-allocator-hpp] use vulkan-headers

### ISSUE THREAD

**Issue by qbojj** [microsoft/vcpkg#35822]
### Is your feature request related to a problem? Please describe.

`vulkan-memory-allocator-hpp` uses whole `vulkan` but only uses parts of `vulkan-headers`

### Proposed solution

change dependency to `vulkan-headers`

**Comment by jimwang118** [comment]
This port only installs its own header files. If you want to use the header files of `vulkan-headers`, please install `vulkan-headers`.

**Comment by dg0yt** [comment]
Port vulkan was turned into a full SDK-like installation recently. I suggest to use the SDK stuff to a separate port: #35742.

**Comment by dg0yt** [comment]
> This port only installs its own header files. If you want to use the header files of `vulkan-headers`, please install `vulkan-headers`.

This probably misses the point.

**Comment by qbojj** [comment]
> This port only installs its own header files. If you want to use the header files of `vulkan-headers`, please install `vulkan-headers`.

This is just not true. This port sets `vulkan` as dependency
https://github.com/microsoft/vcpkg/blob/master/ports%2Fvulkan-memory-allocator-hpp%2Fvcpkg.json#L8-L11

**Comment by qbojj** [comment]
Fixed with #35742
