### ISSUE TITLE
[pybind11] Build error on x64-windows

### ISSUE THREAD

**Issue by lyly-vuongtu** [microsoft/vcpkg#35827]
Copy issue body from C:/Users/trant/OneDrive/Tài liệu/GitHub/python_beginner/pybind11/vcpkg/installed/vcpkg/issue_body.md

**Comment by JonLiu1993** [comment]
See https://github.com/microsoft/vcpkg/issues/30604 on how to properly create an issue.

**Comment by JonLiu1993** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
