### ISSUE TITLE
[imgui] imgui with vulkan-binding only uses headers but requires vulkan port

### ISSUE THREAD

**Issue by qbojj** [microsoft/vcpkg#35820]
### Is your feature request related to a problem? Please describe.

The `imgui[vulkan-binding]` port requires vulkan even when it only uses headers and possibly library.
It doesn't need the glslang/shaderc/sdl2 and other parts of `vulkan` port. 

### Proposed solution

There are 2 options:
- modify `vcpkg.json` so only `vulkan-headers` is added when `vulkan-binding` feature is set. Additionally `IMGUI_IMPL_VULKAN_NO_PROTOTYPES` should be added. This option is not backwards compatibile as it requires call to `ImGui_ImplVulkan_LoadFunctions`.
- alternatively use `vulkan-loader` with `vulkan-headers` without `IMGUI_IMPL_NO_PROTOTYPES`. (must link to `Vulkan::Loader` and `Vulkan::Headers`)

### Describe alternatives you've considered

Both of these options could be implemented not to create breaking changes, but allowing not linking to the loader.
The first option would be `vulkan-binding-loader` and the second `vulkan-binding`.

**Comment by dg0yt** [comment]
Again, I propose to move the SDK parts from `vulkan` to `vulkan-sdk`, #35742.
That "library" is `vulkan-loader - except for android where it comes with the NDK. This is what port `vulkan` should encode IMO, instead of the SDK composition.

**Comment by dg0yt** [comment]
This should be resolved now, following the second option from the list above. https://github.com/microsoft/vcpkg/pull/35742 was merged, and `vulkan` is now exactly what is needed to satisfy `find_package(Vulkan)` in `imgui`. This implies having a loader lib.

**Comment by qbojj** [comment]
LGTM
