### ISSUE TITLE
[curl] Support disabling IPv6

### ISSUE THREAD

**Issue by BewareMyPower** [microsoft/vcpkg#35834]
### Is your feature request related to a problem? Please describe.

When linking the static library of curl (`libcurl.a`) on macOS, some frameworks need to be linked.

Reproduce (on macOS m1 13.6.3):

```bash
./vcpkg install 'curl[core]'
```

Create a simple `main.c`:

```c
#include <curl/curl.h>
 
int main(void)
{
  curl_global_init(CURL_GLOBAL_ALL);
  curl_global_cleanup();
  return 0;
}
```

Then built it via `clang` directly:

```bash
$ clang main.c -I./installed/arm64-osx/include ./installed/arm64-osx/lib/libcurl.a -lz
Undefined symbols for architecture arm64:
  "_CFRelease", referenced from:
      _Curl_macos_init in libcurl.a(macos.c.o)
  "_SCDynamicStoreCopyProxies", referenced from:
      _Curl_macos_init in libcurl.a(macos.c.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I have to add the `-framework SystemConfiguration -framework CoreFoundation` flags to make it succeed.

### Proposed solution

Add an `ipv6` feature as a default feature.

Actually this feature is not supported on UWP, see https://github.com/microsoft/vcpkg/blob/f30434939d5516ce764c549ab04e3d23d312180a/ports/curl/portfile.cmake#L59C26-L59C26

**Comment by dg0yt** [comment]
> When linking the static library of curl (`libcurl.a`) on macOS, some frameworks need to be linked.

This is normal for static linkage.

> I have to add the -framework SystemConfiguration -framework CoreFoundation flags to make it succeed.

Right. Or you ask pkg-config for `libcurl` libs. Or you ask CMake for `CURL`. This is how the port is consumed by other ports in vcpkg.

> Proposed solution
> 
> Add an ipv6 feature as a default feature.

I don't think an ipv6 changes anything about the fact that you have to supply all direct and transitive link libraries when linking executables with static libs. In the right order.

**Comment by dg0yt** [comment]
@wucaizi https://github.com/microsoft/vcpkg/issues/35834#issuecomment-1868000518

**Comment by BewareMyPower** [comment]
> I don't think an ipv6 changes anything about the fact that you have to supply all direct and transitive link libraries when linking executables with static libs. In the right order.

The frameworks are only required when the IPv6 is enabled, that's one point. Another point is, if you're going to provide a fat bundled library that gathers all static libraries, you have to tell users to link the extra frameworks as well.

For example, I have to build the curl from source like:

```bash
cmake -B build \
  -DENABLE_IPV6=OFF \
  -DCURL_ENABLE_SSL=OFF \
  -DUSE_LIBIDN2=OFF \
  -DCURL_USE_LIBPSL=OFF \
  -DCURL_USE_LIBSSH2=OFF \
  -DENABLE_UNIX_SOCKETS=OFF \
  -DBUILD_TESTING=OFF \
  -DBUILD_CURL_EXE=OFF \
  -DBUILD_STATIC_LIBS=ON \
  -DBUILD_SHARED_LIBS=OFF
cmake --build build -j8
```

Then I can build an executable like:

```bash
g++ main.cc -I ./include build/lib/libcurl.a -lz
```

Only the ZLib dependency is required. This compile command works both for Linux and macOS.

However, if I installed curl via vcpkg, I have to add `-framework SystemConfiguration -framework CoreFoundation` on macOS, while it's not required on Linux.

**Comment by BewareMyPower** [comment]
I got your points now. From my perspective, the core point is that the frameworks are provided by the system and no extra dependencies are involved with the IPv6 support.

Let's close this issue.
