### ISSUE TITLE
--only-downloads is not only download!

### ISSUE THREAD

**Issue by UMU618** [microsoft/vcpkg#35833]
**Describe the bug**
When I type `vcpkg install xx --only-downloads`, it'll also detect installation status of VS.

**Environment**
- OS: Windows
- Compiler: None

**To Reproduce**
1. ./vcpkg install openssl --only-downloads
2. See error
<img width="603" alt="image" src="https://github.com/microsoft/vcpkg/assets/1729732/d9f6a07c-5a7c-464d-b7e1-945fd3bd7ae8">

**Expected behavior**
Able to download the package, even I don't install VS. I just wanna copy the downloaded package to another machine that has VS installed.

**Comment by Adela0814** [comment]
@UMU618 I'm not able to repro this issue, please pull the latest vcpkg and try again.
My vcpkg version: `vcpkg package management program version 2023-12-12-1c9ec1978a6b0c2b39c9e9554a96e3e275f7556e`
![image](https://github.com/microsoft/vcpkg/assets/95600143/e087dd17-4c71-473f-96d2-15d0c6847f57)

**Comment by UMU618** [comment]
@Adela0814 I just repro this issue on a newly installed Windows Server 2022. And my vcpkg version is the same as yours.

**Comment by LilyWangLL** [comment]
> Error: in triplet x64-windows: Unable to find a valid Visual Studio instance
> Could not locate a complete Visual Studio instance

Thanks for posting this issue. Please refer to the solution https://github.com/microsoft/vcpkg/issues/22548#issuecomment-1682963336, please reopen this issue if this is still a problem for you.
