### ISSUE TITLE
libffi:x64-windows-static fails

### ISSUE THREAD

**Issue by olilarkin** [Microsoft/vcpkg#3585]
Fresh vcpkg on Win 7 pro

.\vcpkg.exe install cairo:x64-windows-static

->>

1/2] cmd /c "cd .. && "D:/vcpkg/downloads/tools/cmake-3.10.2-windows/cmake-3.10.2-win32-x86/bin/cmake.exe" "D:/vcpkg/buildtrees/libffi/src/v3.1-206c189062" "-DFFI_CONFIG_FILE=D:/vcpkg/ports/libffi/fficonfig.h" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows-static" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=D:/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=static" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Visual Studio 15 2017 Win64" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=D:/vcpkg/packages/libffi_x64-windows-static""
FAILED: ../CMakeCache.txt 
cmd /c "cd .. && "D:/vcpkg/downloads/tools/cmake-3.10.2-windows/cmake-3.10.2-win32-x86/bin/cmake.exe" "D:/vcpkg/buildtrees/libffi/src/v3.1-206c189062" "-DFFI_CONFIG_FILE=D:/vcpkg/ports/libffi/fficonfig.h" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows-static" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=D:/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=static" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Visual Studio 15 2017 Win64" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=D:/vcpkg/packages/libffi_x64-windows-static""
CMake Warning at D:/vcpkg/scripts/buildsystems/vcpkg.cmake:89 (message):
  There are no libraries installed for the Vcpkg triplet x64-windows-static.
Call Stack (most recent call first):
  D:/vcpkg/downloads/tools/cmake-3.10.2-windows/cmake-3.10.2-win32-x86/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:94 (include)
  CMakeLists.txt:2 (project)

CMake Error at CMakeLists.txt:2 (project):
  Failed to run MSBuild command:

    C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 15.6.82.30579 for .NET Framework
    Copyright (C) Microsoft Corporation. All rights reserved.
    
    Build started 25/05/2018 20:28:12.
    Project "D:\vcpkg\buildtrees\libffi\x64-windows-static-rel\CMakeFiles\3.10.2\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Platforms\x64\PlatformToolsets\v141\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [D:\vcpkg\buildtrees\libffi\x64-windows-static-rel\CMakeFiles\3.10.2\VCTargetsPath.vcxproj]
    Done Building Project "D:\vcpkg\buildtrees\libffi\x64-windows-static-rel\CMakeFiles\3.10.2\VCTargetsPath.vcxproj" (default targets) -- FAILED.
    
    Build FAILED.

**Comment by Voskrese** [comment]
The Windows SDK version 8.1 was not found.

**Comment by olilarkin** [comment]
updating vs seems to have fixed it
