### ISSUE TITLE
[cairo] Link error on macOS

### ISSUE THREAD

**Issue by xiaozhuai** [microsoft/vcpkg#35859]
**Describe the bug**

```
: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -g -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=12.6 -Wl,-search_paths_first -Wl,-headerpad_max_install_names -framework CoreFoundation ApplicationServices src/cairo/CMakeFiles/vcpkg_demo_cairo.dir/src/main.cpp.o src/cairo/CMakeFiles/vcpkg_demo_cairo.dir/src/stb.cpp.o -o src/cairo/vcpkg_demo_cairo  /usr/local/vcpkg/installed/x64-osx/debug/lib/libminifb.a  /usr/local/vcpkg/installed/x64-osx/debug/lib/libcairomm-1.16.a  /usr/local/vcpkg/installed/x64-osx/debug/lib/libsigc-3.0.a  /usr/local/vcpkg/installed/x64-osx/debug/lib/libcairo.a  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/lib/libdl.tbd  -framework CoreFoundation  -framework ApplicationServices  /usr/local/vcpkg/installed/x64-osx/debug/lib/libfontconfig.a  /usr/local/vcpkg/installed/x64-osx/debug/lib/libexpat.a  /usr/local/vcpkg/installed/x64-osx/debug/lib/libfreetyped.a  /usr/local/vcpkg/installed/x64-osx/debug/lib/libbz2d.a  /usr/local/vcpkg/installed/x64-osx/debug/lib/libpng16d.a  /usr/local/vcpkg/installed/x64-osx/debug/lib/libz.a  /usr/local/vcpkg/installed/x64-osx/debug/lib/libbrotlidec.a  /usr/local/vcpkg/installed/x64-osx/debug/lib/libbrotlicommon.a  /usr/local/vcpkg/installed/x64-osx/debug/lib/libpixman-1.a  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/lib/libm.tbd  -framework Cocoa  -framework QuartzCore  -framework Metal  -framework MetalKit && :
clang: error: no such file or directory: 'ApplicationServices'
```

And here is the `cairo.pc` file.

```pkgconf
prefix=${pcfiledir}/../..
includedir=${prefix}/include
libdir=${prefix}/lib

Name: cairo
Description: Multi-platform 2D graphics library
Version: 1.17.8

Libs: "-L${libdir}" -lcairo -lm -ldl -framework CoreFoundation -framework ApplicationServices
Requires: zlib, libpng, fontconfig >=  2.2.95, freetype2 >=  9.7.3, pixman-1 >=  0.36.0
Cflags: "-I${includedir}/cairo"
```

To repro it, please see https://github.com/xiaozhuai/vcpkg_demo/tree/master/src/cairo.
Commnet out https://github.com/xiaozhuai/vcpkg_demo/blob/cc682ff5e34aa58f04c35b1387fc8ce269f2c516/CMakeLists.txt#L8-L21
and https://github.com/xiaozhuai/vcpkg_demo/blob/cc682ff5e34aa58f04c35b1387fc8ce269f2c516/CMakeLists.txt#L24-L47

Then install deps
```sh
vcpkg install minifb cairo cairomm --triplet=x64-osx
```

**Environment**
- OS: macOS
- Compiler: Apple clang version 14.0.0 (clang-1400.0.29.202)
- Triplet: x64-osx

**Comment by dg0yt** [comment]
Not a cairo bug.  
The pc file is right: `-framework CoreFoundation -framework ApplicationServices`  
The link comand isn't: `-framework CoreFoundation ApplicationServices`

This is a typical artifact of an uninformed `list(REMOVE_DUPLICATES some_libs_var)`.

**Comment by xiaozhuai** [comment]
> Not a cairo bug. The pc file is right: `-framework CoreFoundation -framework ApplicationServices` The link comand isn't: `-framework CoreFoundation ApplicationServices`
> 
> This is a typical artifact of an uninformed `list(REMOVE_DUPLICATES some_libs_var)`.

Can we fix it in vcpkg?

**Comment by dg0yt** [comment]
Could you please first report which project showed the broken linker command? This should have been in the initial report.

**Comment by xiaozhuai** [comment]
> https://github.com/xiaozhuai/vcpkg_demo/tree/master/src/cairo

**Comment by xiaozhuai** [comment]
@dg0yt @jimwang118 
Very odd. I can't repro it now.

**Comment by dg0yt** [comment]
Another FindPkgConfig.cmake bug. Study with `cmake --trace-expand`.  

Basically, it properly adds `-framework ApplicationServices` (one item!) to  `INTERFACE_LINK_LIBRARIES`. You can configure a fresh binary dir and build successfully.

However, on a second CMake run, it re-uses some cached variables which it did process and hide but not update during the initial framework processing. And then it also improperly adds `-framework;ApplicationServices` (two items!) to `INTERFACE_LINK_OPTIONS`. This is where it later removes the "duplicate option".

And this only happens on the second cmake configuration

**Comment by xiaozhuai** [comment]
> However, on a second CMake run

Yes, this is the key. I can repro it now.

**Comment by dg0yt** [comment]
Please try #35893.

**Comment by xiaozhuai** [comment]
> Please try #35893.

Thanks. On my vacation now. Will try it when I back to office.

**Comment by xiaozhuai** [comment]
> Please try https://github.com/microsoft/vcpkg/pull/35893.

It works

**Comment by xiaozhuai** [comment]
cmake 3.29 fix this.
