### ISSUE TITLE
[libmysql] Build error on arm64-osx-dynamic

### ISSUE THREAD

**Issue by MaxRev-Dev** [microsoft/vcpkg#35876]
Package: libmysql:arm64-osx-dynamic@8.0.34

**Host Environment**

- Host: arm64-osx (docker)
- Compiler: Clang 17.0.6
-    vcpkg-tool version: 2023-12-12-1c9ec1978a6b0c2b39c9e9554a96e3e275f7556e
    vcpkg-scripts version: c8696863d 2023-12-12 (11 days ago)

**To Reproduce**

`vcpkg install libmysql:arm64-osx-dynamic`

**Failure logs**

```
-- The C compiler identification is AppleClang 15.0.0.15000100
-- The CXX compiler identification is AppleClang 15.0.0.15000100
....
....
-- Performing Test HAVE_SUPPORTED_CLANG_VERSION
CMake Error: try_run() invoked in cross-compiling mode, please set the following cache variables appropriately:
   HAVE_SUPPORTED_CLANG_VERSION_EXITCODE (advanced)
For details see /Users/maxrev/dev/gdal.netcore/build-osx/vcpkg/buildtrees/libmysql/arm64-osx-dynamic-rel/TryRunResults.cmake
-- Performing Test HAVE_SUPPORTED_CLANG_VERSION - Failed
```

**Comment by FrankXie05** [comment]
@MaxRev-Dev This is the special behavior of cmake for the [try_run()](https://cmake.org/cmake/help/latest/command/try_run.html) command. 
You can add the following code to the corresponding triplet file and try to see if it can be built. 
In `vcpkg/triplets/community/arm64-osx-dynamic.cmake` or `arm64-linux-dynamic`:
```
if(PORT STREQUAL "libmysql")
    list(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS
        -DHAVE_SUPPORTED_CLANG_VERSION_EXITCODE=
    )
endif()
```

**Comment by MaxRev-Dev** [comment]
@FrankXie05 Now it fails with this. My Xcode and clang versions
```
Xcode 15.1
Build version 15C65
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: arm64-apple-darwin23.2.0
```
Log
```
-- Performing Test HAVE_SUPPORTED_CLANG_VERSION
-- Performing Test HAVE_SUPPORTED_CLANG_VERSION - Failed
CMake Error at cmake/os/Darwin.cmake:40 (MESSAGE):
  XCode 10.0 or newer is required!
Call Stack (most recent call first):
  CMakeLists.txt:709 (INCLUDE)
```

I looked into Darwin.cmake and it checks for `__clang_major__` is less than 10.

**Comment by FrankXie05** [comment]
Are you passing the correct clang version value? `HAVE_SUPPORTED_CLANG_VERSION_EXITCODE`

**Comment by MaxRev-Dev** [comment]
@FrankXie05 I didn't change it. The value should be populated from the pipeline. I'm using the default clang compiler from Xcode tools on Sonoma 14.2. 

<details><summary>Logs</summary>
<p>

-- Running cmake version 3.27.1
-- Found Git: /usr/bin/git (found version "2.39.3 (Apple Git-145)") 
-- CMAKE_MODULE_PATH is /Users/maxrev/dev/gdal.netcore/build-osx/vcpkg/buildtrees/libmysql/src/sql-8.0.34-ccf237e298.clean/cmake
-- MySQL 8.0.34
-- The C compiler identification is AppleClang 15.0.0.15000100
-- The CXX compiler identification is AppleClang 15.0.0.15000100
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Source directory /Users/maxrev/dev/gdal.netcore/build-osx/vcpkg/buildtrees/libmysql/src/sql-8.0.34-ccf237e298.clean
-- Binary directory /Users/maxrev/dev/gdal.netcore/build-osx/vcpkg/buildtrees/libmysql/arm64-osx-dynamic-rel
-- CMAKE_GENERATOR: Ninja
-- Performing Test HAVE_SUPPORTED_CLANG_VERSION
-- Performing Test HAVE_SUPPORTED_CLANG_VERSION - Failed
CMake Error at cmake/os/Darwin.cmake:40 (MESSAGE):
  XCode 10.0 or newer is required!
Call Stack (most recent call first):
  CMakeLists.txt:709 (INCLUDE)

</p>
</details>

**Comment by MaxRev-Dev** [comment]
It was a build cache, and it fails on boost-exception. When dependency is fixed, it should resolve this issue.
```
    "/usr/bin/c++"   -fPIC -O3 -DNDEBUG -m64 -pthread -O3 -finline-functions -Wno-inline -Wall -g  -DBOOST_ALL_NO_LIB=1 -DNDEBUG   -I"../include" -I"/build/build-unix/vcpkg/installed/arm64-linux/include"  -c -o "/build/build-unix/vcpkg/buildtrees/boost-exception/arm64-linux-rel/boost/build/b8421191efc14ad1df4c6b5e64656875/clone_current_exception_non_intrusive.o" "../src/clone_current_exception_non_intrusive.cpp"

c++: error: unrecognized command-line option ‘-m64’
...failed updating 1 target...
ninja: build stopped: subcommand failed.
```

**Comment by MaxRev-Dev** [comment]
@dg0yt Can confirm that Linux build works after fixing the triplets (https://github.com/microsoft/vcpkg/issues/35914#issuecomment-1872135260).
Still, it's required to handle the "try_run" and `HAVE_SUPPORTED_CLANG_VERSION` macro for this library on `arm64-osx`
