### ISSUE TITLE
[qtbase] Build time when cross-compiling

### ISSUE THREAD

**Issue by nadiaholmquist** [microsoft/vcpkg#35906]
### Is your feature request related to a problem? Please describe.

When cross compiling, the `qtbase` package needs a copy of itself built for the host as well, presumably to use the Qt build tools. This package is built with all the features of Qt enabled and so takes a significant amount of time to build, only to not use the majority of the features that were just built.

### Proposed solution

Use a more minimal set of features for the `qtbase` package built for the host if possible.

**Comment by dg0yt** [comment]
https://github.com/microsoft/vcpkg-tool/pull/177

**Comment by nadiaholmquist** [comment]
Looks pretty abandoned. Is there any chance this will actually happen?

Building all of qtbase for the host just to use its tools inflates our CI build times with a clean cache to 45 minutes...

**Comment by dg0yt** [comment]
It is not abandoned. The vcpkg owners just put priority on other issues.

Basically it is already possible to limit the host qtbase to `core` by adding this request to the command line or to the user project manifest. But it breaks if a reverse dependency forgot to declare the `"default-features": false`.

**Comment by nadiaholmquist** [comment]
Assuming it does work for qtbase, is it documented somewhere how I can change this in my manifest?

**Comment by dg0yt** [comment]
In the dependencies section:
~~~json
  {
    "name": "qtbase",
    "host": true,
    "default-features": false
  }
~~~

**Comment by nadiaholmquist** [comment]
Great, thanks for the tip! This speeds the builds up massively.

**Comment by jimwang118** [comment]
@nadiaholmquist Is your problem solved?

**Comment by nadiaholmquist** [comment]
Yes, for my specific use case it is - and with the linked PR already covering the more general case this issue can probably be closed.
