### ISSUE TITLE
Error LNK1104	cannot open file 'leptonica.lib'

### ISSUE THREAD

**Issue by lucivpav** [Microsoft/vcpkg#3590]
Hello, I tried using Tesseract in an CMake project. Unfortunately the linking fails with
`Error LNK1104	cannot open file 'leptonica.lib'`

I am using Visual Studo 2017 Community on Windows 10.

I installed tesseract using `vcpkg install tesseract:x64-windows` and it reported this usage:
```
The package tesseract:x64-windows provides CMake targets:

    find_package(tesseract REQUIRED)
    target_link_libraries(main PRIVATE libtesseract)
```

My CMakeLists.txt looks like this:
```
cmake_minimum_required (VERSION 3.8)

add_executable (SubtitleExtract "CommandLineParser.cpp" "CommandLineParser.h" "Detector.cpp" "Detector.h" "Extractor.cpp" "Extractor.h" "Recognizer.cpp" "Recognizer.h" "main.cpp")

find_package(OpenCV REQUIRED)
find_package(Tesseract REQUIRED)

target_include_directories(SubtitleExtract PRIVATE ${OpenCV_INCLUDE_DIRS} ${Tesseract_INCLUDE_DIRS})
target_link_libraries(SubtitleExtract PRIVATE ${OpenCV_LIBS} libtesseract)
```

I am also setting `CMAKE_TOOLCHAIN_FILE` to point to `vcpkg.cmake` file location.

When I take a look into `vcpkg\installed\x64-windows\lib` folder, a library `leptonica-1.74.4.lib` is there.

I have no problem when using a `.sln` project where the library is linked automatically.

Am I doing something wrong? I am new to vcpkg.

**Comment by LarryIII** [comment]
PR merged. So closed this issue.
