### ISSUE TITLE
[GMP] build failure

### ISSUE THREAD

**Issue by philoasd** [microsoft/vcpkg#35900]
### Operating system

windows

### Compiler

MSVS

### Steps to reproduce the behavior

```Shell
vcpkg install cgal
```

### Failure logs

warning: In the September 2023 release, the default triplet for vcpkg libraries changed from x86-windows to the detected host triplet (x64-windows). For the old behavior, add --triplet x86-windows . To suppress this message, add --triplet x64-windows .
Computing installation plan...
The following packages will be built and installed:
    cgal:x64-windows -> 5.6
  * gmp:x64-windows -> 6.2.1#21
  * mpfr:x64-windows -> 4.2.1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\Admin\AppData\Local\vcpkg\archives in 151 us. Use --debug to see more details.
Installing 1/3 gmp:x64-windows...
Building gmp:x64-windows...
-- Using cached gmp-6.2.1.tar.xz.
-- Cleaning sources at D:/property manager files/vcpkg/vcpkg/buildtrees/gmp/src/v6.2.1-0c723d4b6f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/property manager files/vcpkg/vcpkg/downloads/gmp-6.2.1.tar.xz
-- Applying patch asmflags.patch
-- Applying patch cross-tools.patch
-- Applying patch subdirs.patch
-- Applying patch msvc_symbol.patch
-- Applying patch arm64-coff.patch
-- Applying patch gmp-arm64-asm-fix-5f32dbc41afc.patch
-- Using source at D:/property manager files/vcpkg/vcpkg/buildtrees/gmp/src/v6.2.1-0c723d4b6f.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Using cached LLVM-15.0.6-win64.7z.exe.
-- Using cached 7z2301.msi.

### Additional context

When I installed cgal Using vcpkg, I stayed at using cached 7z2301.msi, which is in the Download folder

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Did you run command `git pull` and `.\bootstrap-vcpkg.bat` before installing port.

**Comment by philoasd** [comment]
Already solved, is my vcpkg file path has space cause

**Comment by JekxDevil** [comment]
> Already solved, is my vcpkg file path has space cause

I just happended to be in the same issue. I solved it thanks to you!
How is it possible in windows to be an issue, are spaces in paths not escaped?

**Comment by dg0yt** [comment]
> How is it possible in windows to be an issue, are spaces in paths not escaped?

It is a non-trivial problem due to several levels and types of scripting and environment variables involved. In particular not only Windows, but also a partial POSIX world, with different path syntax, quoting and escaping rules.
