### ISSUE TITLE
Determination of `VCPKG_CROSSCOMPILING` is insufficient

### ISSUE THREAD

**Issue by Krzmbrzl** [microsoft/vcpkg#35947]
**Describe the bug**

The value for `VCPKG_CROSSCOMPILING` seems to be determined here
https://github.com/microsoft/vcpkg/blob/83972272512ce4ede5fc3b2ba98f6468b179f192/scripts/cmake/vcpkg_common_definitions.cmake#L1
by comparing the target triplet with the host triplet.

This will pretend that cross-compilation is active simply because the triplet was named differently. However, simply using a variant of an existing triplet will trigger this (at least it does for `x64-osx-release`).

**Expected behavior**

Whether or not crosscompiling is active should be determined by checking the target architecture and OS (which are part of the triplet, but other things might be as well).

**Additional context**

The toolchain files (`scripts/toolchains`)  seem to do actual checking based on the target and host architecture but this doesn't seem to affect the main build (based on my tests this is only used for determining the compiler to use).

**Comment by Neumann-A** [comment]
Nope that is cross-compiling for vcpkg. If you don't want this behavior specify `--host-triplet` (with newer version of vcpkg specifying the host triplet is enough to get the wanted target triplet.)

**Comment by Krzmbrzl** [comment]
Ah okay. My bad

**Comment by commonbreed** [comment]
There seems to be general abuse of the triplet system in vcpkg. For example, linkage specifiers sometimes make their way into the triplet (`x64-mingw-dynamic` vs `x64-mingw-static`), which touches on the other major issue that static and dynamic libraries cannot be intermixed or specified in project files unless the port name is handled specially in the triplet file (https://github.com/microsoft/vcpkg/issues/906)
