### ISSUE TITLE
cpprestsdk static libraries...

### ISSUE THREAD

**Issue by Jasonkkk** [Microsoft/vcpkg#3594]
I need to get cpprestsdk static libraries. 

PS> vcpkg install cpprestsdk:x86-windows-static
The following packages will be built and installed:
  * boost-algorithm[core]:x86-windows-static
  * boost-array[core]:x86-windows-static
  * boost-asio[core]:x86-windows-static

....

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:72 (file):
  file problem creating directory: ~~~/vcpkg/downloads/temp
Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:217 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_configure_cmake.cmake:115 (vcpkg_find_acquire_program)
  ports/zlib/portfile.cmake:19 (vcpkg_configure_cmake)
  scripts/ports.cmake:72 (include)

**Error: Building package zlib:x86-windows-static failed with: BUILD_FAILED**
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x86-windows-static
  Vcpkg version: 0.0.113-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by NancyLi1013** [comment]
Thanks a lot for posting this issue. 
Please open a new issue if this is still a problem for you.
