### ISSUE TITLE
[gmp] build failure

### ISSUE THREAD

**Issue by leerh123** [microsoft/vcpkg#35955]
### Operating system

Windows11

### Steps to reproduce the behavior

```Shell
.\vcpkg\vcpkg install gmp
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
    gmp:x64-windows@6.2.1#21
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\李瑞涵\AppData\Local\vcpkg\archives in 170 us. Use --debug to see more details.
Installing 1/1 gmp:x64-windows@6.2.1#21...
Building gmp:x64-windows@6.2.1#21...
-- Using cached gmp-6.2.1.tar.xz.
error: building gmp:x64-windows failed with: BUILD_FAILED
Elapsed time to handle gmp:x64-windows: 369 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+gmp
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[gmp]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2FUsers%2F%E6%9D%8E%E7%91%9E%E6%B6%B5%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please clone vcpkg to a path that is all in English and does not contain spaces. If the build still fails, please provide the error logs.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
