### ISSUE TITLE
boostrap keep timing out

### ISSUE THREAD

**Issue by hakeem750** [microsoft/vcpkg#35952]
**Describe the bug**
After cloning the repo to bootstrap, it kept timing out for no apparent reason

**Environment**
Windows

**To Reproduce**
Steps to reproduce the behaviour:
1. ./vcpkg bootstrap-vcpkg.bat

**Comment by jimwang118** [comment]
Sorry, I have not reproduced this issue locally. You can update vcpkg and try again.
