### ISSUE TITLE
[sfml] can't use CMake to configure a VS2022 project

### ISSUE THREAD

**Issue by embeddedmz** [microsoft/vcpkg#35951]
### Operating system

Windows 11

### Compiler

Visual Studio 17 (2022)

### Steps to reproduce the behavior

```Shell
.\vcpkg install sfml --triplet=x64-windows
Open CMake-GUI to generate a solution for this project : https://github.com/embeddedmz/16-Games.git
Click on the button "Configure"
Select Visual Studio 17 2022
Select Specify toolchain file for cross-compiling
Click Next
Specify the toolchain file (e.g. "D:/DevTools/vcpkg/scripts/buildsystems/vcpkg.cmake")
Click Finish
```

### Failure logs

CMake Warning (dev) at CMakeLists.txt:1 (project):
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
The C compiler identification is MSVC 19.38.33133.0
The CXX compiler identification is MSVC 19.38.33133.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
CMake Deprecation Warning at CMakeLists.txt:3 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Warning (dev) at D:/DevTools/vcpkg/installed/x64-windows/share/sfml/SFMLConfig.cmake:2 (if):
  if given arguments:

    "NOT" "ON"

  An argument named "ON" appears in a conditional statement.  Policy CMP0012
  is not set: if() recognizes numbers and boolean constants.  Run "cmake
  --help-policy CMP0012" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.
Call Stack (most recent call first):
  D:/DevTools/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  01 Tetris/CMakeLists.txt:3 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at D:/DevTools/vcpkg/installed/x64-windows/share/sfml/SFMLConfig.cmake:144 (message):
  Requested SFML configuration (Static) was not found
Call Stack (most recent call first):
  D:/DevTools/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  01 Tetris/CMakeLists.txt:3 (find_package)

CMake Error at D:/DevTools/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package):
  Found package configuration file:

    D:/DevTools/vcpkg/installed/x64-windows/share/sfml/SFMLConfig.cmake

  but it set SFML_FOUND to FALSE so package "SFML" is considered to be NOT
  FOUND.
Call Stack (most recent call first):
  01 Tetris/CMakeLists.txt:3 (find_package)

Configuring incomplete, errors occurred!

**Comment by dg0yt** [comment]
> cmake_minimum_required() should be called prior to this top-level project()
> call. Please see the cmake-commands(7) manual for usage documentation of
> both commands.

Do that.

**Comment by dg0yt** [comment]
> CMake Error at D:/DevTools/vcpkg/installed/x64-windows/share/sfml/SFMLConfig.cmake:144 (message):
> Requested SFML configuration (Static) was not found

x64-windows is for dynamic linkage.

**Comment by embeddedmz** [comment]
Thank you @dg0yt
