### ISSUE TITLE
[ktx] update to v4.3.0-beta1

### ISSUE THREAD

**Issue by Pospelove** [microsoft/vcpkg#35964]
### Library name

ktx

### New version number

v4.3.0-beta1

### Other information that may be useful (release notes, etc...)

Upstream fixed https://github.com/microsoft/vcpkg/issues/33687

We can test and close it after port update

**When testing please install ktx[core,tools]:x64-uwp**

**Comment by jimwang118** [comment]
We should update the release version instead of the beta version, right?

**Comment by Pospelove** [comment]
> We should update the release version instead of the beta version, right?

Well at this moment it is alpha I guess won't be worse if it would be beta

also, it seems the upstream only releases alpha/beta for a long time but better check

**Comment by jimwang118** [comment]
> Well at this moment in vcpkg it is alpha I guess won't be worse if it would be beta
> 
> also, it seems the upstream only releases alpha/beta for a long time but better check

Okay, if the upstream always releases a beta version, then I will update it according to the released version.
