### ISSUE TITLE
[gettext-libintl] build failure

### ISSUE THREAD

**Issue by stekyne** [microsoft/vcpkg#35974]
### Operating system

Windows

### Compiler

MSVC 

### Steps to reproduce the behavior

```Shell
vcpkg install gettext-libintl
```

### Failure logs

![image](https://github.com/microsoft/vcpkg/assets/2091399/a657eb26-c41c-4396-93d5-cea5e03229b7)

This pops up and blocks progress of building. I have had this happen on CI and eventually the build times out and fails.

**Comment by StarGate-One** [comment]
I started getting this also -- If I click Retry or Ignore the port build continues normally and have not noticed in other side effects... but for the OP or anyone building on GitHub CI it is a show stopper as there is no way to respond to the message.
![Screenshot 2023-12-27 203714](https://github.com/microsoft/vcpkg/assets/68293825/a97b8b9a-dda2-4b03-b639-0f16b86f24b4)
I have been troubleshooting to see if I could figure out the problem, my first step was creating a completely new/vanilla vcpkg instance and building port `gettext-libintl` but the same results.

**Comment by nlogozzo** [comment]
https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/set-printf-count-output?view=msvc-170

Seems like `_set_printf_count_output(1)` should be called somewhere before building, maybe?

**Comment by nlogozzo** [comment]
Or maybe patch with this, https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/crtsetreportmode?view=msvc-170

**Comment by nlogozzo** [comment]
Actually, just tried with the latest vcpkg commit, and the issue seems to be gone...

fc3f61366102c1f0d4547c06d03c523bb18c13a7

**Comment by nlogozzo** [comment]
> Actually, just tried with the latest vcpkg commit, and the issue seems to be gone...
> 
> [fc3f613](https://github.com/microsoft/vcpkg/commit/fc3f61366102c1f0d4547c06d03c523bb18c13a7)

I take that back...running locally on the latest commit, I don't see this error anymore, however running the lastest commit on GitHub CI still has an infinite wait

**Comment by dg0yt** [comment]
Can you share the state of `x64-windows-dbg/config.log` at the time the window appears?

**Comment by dg0yt** [comment]
I guess this used to be addressed via
https://github.com/microsoft/vcpkg/pull/30429/files#diff-f615a394355e453bbaa9690a1cefd4315c055d94c41bbecfbb47dcd08173c61bL47
This line can restored in `gettext-libintl` and `gettext`. Do you feel able to try this locally?

(This `conftest` originally comes from `gnulib`. In the long term, it would be good to help them to adapt their code to the MSVC debug runtime.)

**Comment by nlogozzo** [comment]
> I guess this used to be addressed via https://github.com/microsoft/vcpkg/pull/30429/files#diff-f615a394355e453bbaa9690a1cefd4315c055d94c41bbecfbb47dcd08173c61bL47 This line can restored in `gettext-libintl` and `gettext`. Do you feel able to try this locally?

Can confirm restoring that line in `gettext-libintl` seems to build without issue.

**Comment by dg0yt** [comment]
Thanks!
`gettext[tools]` shouldn't be affected because it doesn't build a debug config.

**Comment by StarGate-One** [comment]
@dg0yt  - do you still need the logs?
If so I can remove port gettext-libintl and the other ports I have installed and then run the install along with these additional runtime parameters `--debug --debug-env --x-cmake-args=-DVCPKG_CMAKE_CONFIGURE_OPTIONS=--trace-expand` and wait for the message to pop-up and capture all the logs created at that moment in the buildtrees/gettext-libintl before answering with retry so it will continue installing. I can then zip them all up and post back here?
Just let me know.
Thanks everyone for all the hard work.

**Comment by nlogozzo** [comment]
> gettext[tools] shouldn't be affected because it doesn't build a debug config.

Yeah, gettext[tools] never caused any issue for me.

**Comment by dg0yt** [comment]
No logs needed. The research and test by @nlogozzo gave me enough confidence for (restoring) the immediate fix.

What I can't do (due to lack of MSVC) is preparing a permanent fix for gnulib. They do have `_set_invalid_parameter_handler` for that test:  
https://git.savannah.gnu.org/cgit/gnulib.git/tree/m4/printf.m4#n896  
but IIUC this must be complemented by `_CrtSetReportMode` for building against the debug runtime.

**Comment by StarGate-One** [comment]
I do not know one way or another - as I am still doing my C/C++ lessons, learning C/C++ is a very new direction for me, as most of my years in IT were - should I say it, COBOL, mainframes and distributed AIX/HP-UX servers.
