### ISSUE TITLE
Failed to build reference-lapack-3.8.0

### ISSUE THREAD

**Issue by JsuKya** [microsoft/vcpkg#3597]
**Environment**
Windows 10 x64 Pro 17134.48
Visual studio 2015 update3, version 14.0.25431.01
Intel fortran 2018, Package ID: w_comp_lib_2018.0.124

I get the following errors trying to install reference-lapack-3.8.0:

PS: C:\Users\JsuKya\Desktop\vcpkg>
PS>.\vcpkg install reference-lapack:x64-windows
The following packages will be built and installed:
    reference-lapack[core]:x64-windows
Starting package 1/1: reference-lapack:x64-windows
Building package reference-lapack[core]:x64-windows...
-- CURRENT_INSTALLED_DIR=C:/Users/JsuKya/Desktop/vcpkg/installed/x64-windows
-- DOWNLOADS=C:/Users/JsuKya/Desktop/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/JsuKya/Desktop/vcpkg/packages/reference-lapack_x64-windows
-- CURRENT_BUILDTREES_DIR=C:/Users/JsuKya/Desktop/vcpkg/buildtrees/reference-lapack
-- CURRENT_PORT_DIR=C:/Users/JsuKya/Desktop/vcpkg/ports/reference-lapack/.
-- Using cached C:/Users/JsuKya/Desktop/vcpkg/downloads/Reference-LAPACK-lapack-v3.8.0.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch C:/Users/JsuKya/Desktop/vcpkg/ports/reference-lapack/fix-include-order.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/Users/JsuKya/Desktop/vcpkg/ports/reference-lapack/fix-include-order.patch done
-- Applying patch C:/Users/JsuKya/Desktop/vcpkg/ports/reference-lapack/fix-try-compile-fortran-flags.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/Users/JsuKya/Desktop/vcpkg/ports/reference-lapack/fix-try-compile-fortran-flags.patch done
-- Applying patch C:/Users/JsuKya/Desktop/vcpkg/ports/reference-lapack/fix-unresolved-symbol.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/Users/JsuKya/Desktop/vcpkg/ports/reference-lapack/fix-unresolved-symbol.patch done
-- Using cached C:/Users/JsuKya/Desktop/vcpkg/downloads/ninja-1.8.2.g972a7.kitware.dyndep-1_i686-pc-windows-msvc.zip
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Using cached C:/Users/JsuKya/Desktop/vcpkg/downloads/ninja-1.8.2.g972a7.kitware.dyndep-1_i686-pc-windows-msvc.zip
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: C:/Users/JsuKya/Desktop/vcpkg/buildtrees/reference-lapack/x64-windows-rel/vcpkg-parallel-configure
    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:239 (vcpkg_execute_required_process)
  ports/reference-lapack/portfile.cmake:23 (vcpkg_configure_cmake)
  scripts/ports.cmake:72 (include)

Error: Building package reference-lapack:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: reference-lapack:x64-windows
  Vcpkg version: 0.0.108-2018-04-17-977e5315f21d920058932f17125d8470f4fb9ea3

**The build.ninja file:**
rule CreateProcess
  command = $process

build ../CMakeCache.txt: CreateProcess
  process = cmd /c "cd .. && "D:/Program Files/CMake/bin/cmake.exe" "C:/Users/JsuKya/Desktop/vcpkg/buildtrees/reference-lapack/src/lapack-3.8.0" "-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON" "-DBUILD_TESTING=OFF" "-DCBLAS=ON" "-DLAPACKE=ON" "-DCMAKE_MAKE_PROGRAM=NINJA-NOTFOUND" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/JsuKya/Desktop/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/JsuKya/Desktop/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-DVCPKG_FORTRAN_COMPILER=Intel" "-DVCPKG_FORTRAN_ENABLED=ON" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/Users/JsuKya/Desktop/vcpkg/packages/reference-lapack_x64-windows""

build ../../x64-windows-dbg/CMakeCache.txt: CreateProcess
  process = cmd /c "cd ../../x64-windows-dbg && "D:/Program Files/CMake/bin/cmake.exe" "C:/Users/JsuKya/Desktop/vcpkg/buildtrees/reference-lapack/src/lapack-3.8.0" "-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON" "-DBUILD_TESTING=OFF" "-DCBLAS=ON" "-DLAPACKE=ON" "-DCMAKE_MAKE_PROGRAM=NINJA-NOTFOUND" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/JsuKya/Desktop/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/JsuKya/Desktop/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-DVCPKG_FORTRAN_COMPILER=Intel" "-DVCPKG_FORTRAN_ENABLED=ON" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/Users/JsuKya/Desktop/vcpkg/packages/reference-lapack_x64-windows/debug""

**Comment by Voskrese** [comment]
"-DCMAKE_MAKE_PROGRAM=NINJA-NOTFOUND"

**Comment by JsuKya** [comment]
@Voskrese But I have ninja in the ".\vcpkg\downloads\tools\ninja" path.
w_comp_lib_2018.0.124 is the detailed version of intel fortran.

**Comment by Voskrese** [comment]
In the utility on the githab from Microsoft there is no support for Fortran

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
