### ISSUE TITLE
failed to build opencv arm-uwp 

### ISSUE THREAD

**Issue by fredstoolbox** [Microsoft/vcpkg#3598]
Hi, I've got this error while trying to build OpenCV using arm-uwp

the command I used:
vcpkg install opencv:arm-uwp

the error occurred:

Starting package 5/7: opengl:arm-uwp
Building package opengl[core]:arm-uwp...
-- CURRENT_INSTALLED_DIR=D:/Data/vcpkg/vcpkg-master/vcpkg-master/installed/arm-uwp
-- DOWNLOADS=D:/Data/vcpkg/vcpkg-master/vcpkg-master/downloads
-- CURRENT_PACKAGES_DIR=D:/Data/vcpkg/vcpkg-master/vcpkg-master/packages/opengl_arm-uwp
-- CURRENT_BUILDTREES_DIR=D:/Data/vcpkg/vcpkg-master/vcpkg-master/buildtrees/opengl
-- CURRENT_PORT_DIR=D:/Data/vcpkg/vcpkg-master/vcpkg-master/ports/opengl
CMake Error at ports/opengl/portfile.cmake:20 (message):
  Cannot find Windows 10.0.17134.0 SDK.  File does not exist: C:\Program
  Files (x86)\Windows Kits\10\Lib\10.0.17134.0\um\arm\OpenGL32.Lib
Call Stack (most recent call first):
  scripts/ports.cmake:72 (include)

Error: Building package opengl:arm-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opengl:arm-uwp
  Vcpkg version: 0.0.113-nohash

Is there a way to bypass this opengl thing? I don't really need it. and this lib does not exist in any of the SDK ARM lib folders anyway

**Comment by PhoebeHui** [comment]
This is a duplicated issue, see issue https://github.com/Microsoft/vcpkg/issues/3278.
