### ISSUE TITLE
[ffmpeg] Build error on x64-linux

### ISSUE THREAD

**Issue by iGwkang** [microsoft/vcpkg#36004]
`vcpkg install ffmpeg[all]`
> error: mfx-dispatch is only supported on '!linux & !uwp & !osx'

When compiling ffmpeg on the Linux platform, will qsv be supported?
Are there any plans to support qsv?

**Comment by MonicaLiu0311** [comment]
Because the dependency `mfx-dispatch` only supports Windows, it will be difficult to implement unless upstream starts supporting other platforms: https://github.com/lu-zero/mfx_dispatch?tab=readme-ov-file#windows

**Comment by iGwkang** [comment]
@lu-zero Hello, are there any plans to support Linux?

**Comment by lu-zero** [comment]
In theory you may rely on https://github.com/intel/libvpl nowadays.

**Comment by iGwkang** [comment]
@MonicaLiu0311 Hi, do you have any ideas? Is it possible to support the use of libvpl?

**Comment by iGwkang** [comment]
@MonicaLiu0311 Hi, do you have any ideas? Is it possible to support the use of libvpl?

**Comment by iGwkang** [comment]
@MonicaLiu0311 Please let me know if there is any progress, thanks!

**Comment by Hlongyu** [comment]
https://github.com/microsoft/vcpkg/issues/29489   
Can we remove mfx-dispatch dependency?

**Comment by MonicaLiu0311** [comment]
> #29489 Can we remove mfx-dispatch dependency?

https://github.com/FFmpeg/FFmpeg/blob/n7.0.2/configure#L3274
https://github.com/FFmpeg/FFmpeg/blob/n7.0.2/configure#L6895-L6899

`libmfx` is a dependency of feature `qsv`. Feature is optional and you can choose not to install qsv.

**Comment by iGwkang** [comment]
@MonicaLiu0311 
If qsv is not selected, how to use the hardware acceleration of Intel GPU?
The issus is that we want to be able to use qsv hardware acceleration on Linux.
Why is [jellyfin-ffmpeg](https://github.com/jellyfin/jellyfin-ffmpeg) able to use qsv on Linux?

**Comment by dg0yt** [comment]
> Because the dependency `mfx-dispatch` only supports Windows, it will be difficult to implement unless upstream starts supporting other platforms: https://github.com/lu-zero/mfx_dispatch?tab=readme-ov-file#windows

[This answer got 2 :+1:?](https://github.com/microsoft/vcpkg/issues/36004#issuecomment-1875120827) But it doesn't make sense.
Upstream has Linux support: https://github.com/lu-zero/mfx_dispatch?tab=readme-ov-file#linux
But vcpkg port `mfx-dispatch` is limited to `"!linux & !uwp & !osx"`
