### ISSUE TITLE
vcpkg deactivate does not unset environment variables

### ISSUE THREAD

**Issue by Zitrax** [microsoft/vcpkg#36025]
**Describe the bug**

In my registry I have this:

⋮
```json
"windows,linux": {
  "message": "Updated environment variable MYVAR",
  "exports": {
    "paths": {
      "MYVAR": ""
    }
  }
}
```
⋮

**Environment**
- OS: WSL on Windows 11 which reports: Ubuntu 22.04.2 LTS
- vcpkg version: vcpkg package management program version 2023-12-12-1c9ec1978a6b0c2b39c9e9554a96e3e275f7556e

**To Reproduce**
1. `vcpkg activate`
2. `echo $MYVAR`
3. `vcpkg deactivate`
4. `echo $MYVAR`

**Expected behavior**

After deactivation `MYVAR` should no longer be set but it is.

Notice that I only see this on WSL, not under Windows. (I have not tested non-WSL linux)

**Failure logs**

If I run `vcpkg deactivate --debug` I see this on WSL:

```
debug: [00:00.160] --------[START SHELL SCRIPT FILE]--------
unset M
unset Z


--------[END SHELL SCRIPT FILE]---------
```

but on Windows I see:

```
debug: [00:00.116] --------[START SHELL SCRIPT FILE]--------
${ENV:MYVAR}=$null
${ENV:Z_VCPKG_UNDO}=$null


--------[END SHELL SCRIPT FILE]---------
```

So for some reason it tries to unset env variables with the first letter only.

**Comment by Cheney-W** [comment]
Still present.

**Comment by Zitrax** [comment]
Thanks!
