### ISSUE TITLE
Can not install any package

### ISSUE THREAD

**Issue by TranTriDat** [microsoft/vcpkg#36048]
### Operating system

Wins 11

### Compiler

gcc 6.3

### Steps to reproduce the behavior

```Shell
./vcpkg install
See error
Repro code when
```

### Failure logs

Failure log:
![image](https://github.com/microsoft/vcpkg/assets/44765145/5a1f3ab2-ecb1-4e6e-b48a-a5744c9b97b5)
E:\vcpkg\buildtrees\detect_compiler\config-x64-windows-rel-CMakeCache.txt.log:
[config-x64-windows-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/13844279/config-x64-windows-rel-CMakeCache.txt.log)
E:\vcpkg\buildtrees\detect_compiler\config-x64-windows-out.log:
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/13844286/config-x64-windows-out.log)

### Additional context

I follow the instructions so far and I got an error when tried to install poco.
![image](https://github.com/microsoft/vcpkg/assets/44765145/763ba469-8f70-4669-a568-b837e1e68258)

I also read the old issues here but it no solutions worked.

**Comment by FrankXie05** [comment]
@TranTriDat Thanks for posting this issue,
```
  file failed to open for reading (Invalid argument):

    E:/vcpkg/buildtrees/detect_compiler/x64-windows-rel/CMakeFiles/3.27.1/CompilerIdC/CMakeCCompilerId.exe
```
Please make sure your current folder has write permissions.

**Comment by FrankXie05** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can ping me with more info and I will reopen.
