### ISSUE TITLE
Patchelf version is not recognized on Linux/OSX.

### ISSUE THREAD

**Issue by MaxRev-Dev** [microsoft/vcpkg#36046]
**Describe the bug**
The `patchelf` utility returns the utility's name with a version instead of a plain `x.y.z` version - `patchelf 0.18.2`.
This results in a string mismatch compared with the required version string. 

**Environment**
- OS: Linux/OSX
- Compiler: N/A

**To Reproduce**

`docker run -it --platform=linux/arm64 debian:11`              

Then in container
```
root@ce3d8e4b9c21:/# apt-get update
root@ce3d8e4b9c21:/# apt-get install patchelf -y
root@ce3d8e4b9c21:/# patchelf --version
patchelf 0.12 <---- here's the string
```

Or it can be reproduced when package is installed.
1. `./vcpkg install "icu[core,tools]:arm64-osx"`
2. See error. It tries to download `patchelf` but missing URLs.
```
-- Found patchelf('patchelf 0.18.0') but at least version 0.14.5 is required! Trying to use internal version if possible!
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:123 (message):
  vcpkg_download_distfile requires a URLS argument.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:626 (vcpkg_download_distfile)
  scripts/cmake/z_vcpkg_fixup_rpath.cmake:2 (vcpkg_find_acquire_program)
  scripts/cmake/z_vcpkg_fixup_rpath.cmake:57 (z_vcpkg_fixup_rpath_in_dir)
  scripts/ports.cmake:150 (include)
```
Repro code when

**Expected behavior**
The installed `patchelf` is correctly determined and used by the vcpkg pipeline.

**Comment by jimwang118** [comment]
This issue does not occur in `Linux` and `osx`.
