### ISSUE TITLE
[fmt] Build error

### ISSUE THREAD

**Issue by ARTH1S** [microsoft/vcpkg#36058]
Failure logs

`Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x64-windows-static...
The following packages will be built and installed:
    commonlibsse-ng:x64-windows-static -> 3.6.0 -- C:\Users\New\AppData\Local\vcpkg\registries\git-trees\3c7564a8339422b4e502188e3c48d19e629eac76
  * fmt:x64-windows-static -> 9.1.0#1 -- C:\Users\New\AppData\Local\vcpkg\registries\git-trees\3f452404270b508daf355b72031ad3ee7d0d5751
  * rapidcsv:x64-windows-static -> 8.64 -- C:\Users\New\AppData\Local\vcpkg\registries\git-trees\1842f5ea6077feea4ef5d07bb43e2fd648763718
  * spdlog:x64-windows-static -> 1.11.0 -- C:\Users\New\AppData\Local\vcpkg\registries\git-trees\296d78e54c14ce64474b66f60847026ddb1f576e
Additional packages (*) will be modified to complete this operation.
Restored 0 package(s) from C:\Users\New\AppData\Local\vcpkg\archives in 194 us. Use --debug to see more details.
Installing 1/4 fmt:x64-windows-static...
Building fmt:x64-windows-static...
-- Installing port from location: C:\Users\New\AppData\Local\vcpkg\registries\git-trees\3f452404270b508daf355b72031ad3ee7d0d5751
-- Using cached fmtlib-fmt-9.1.0.tar.gz.
-- Cleaning sources at C:/_MODDING/SKSE_Template_HelloWorld/build/debug/vcpkg_installed/vcpkg/blds/fmt/src/9.1.0-20bc1f56f3.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/New/AppData/Local/vcpkg/downloads/fmtlib-fmt-9.1.0.tar.gz
-- Applying patch fix-write-batch.patch
-- Applying patch fix-format-conflict.patch
-- Using source at C:/_MODDING/SKSE_Template_HelloWorld/build/debug/vcpkg_installed/vcpkg/blds/fmt/src/9.1.0-20bc1f56f3.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Installing: C:/_MODDING/SKSE_Template_HelloWorld/build/debug/vcpkg_installed/vcpkg/pkgs/fmt_x64-windows-static/share/fmt/copyright
-- Fixing pkgconfig file: C:/_MODDING/SKSE_Template_HelloWorld/build/debug/vcpkg_installed/vcpkg/pkgs/fmt_x64-windows-static/lib/pkgconfig/fmt.pc
-- Using cached mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Downloading https://mirror.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst -> mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=true, usegitregistry=true, embeddedsha=638b1588be3a265a9c7ad5b212cef72a1cad336a, deployment=VisualStudio, vsversion=17.0
[DEBUG] VS telemetry opted in at SOFTWARE\WOW6432Node\Microsoft\VSCommon\17.0\SQM\\OptIn
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://mirror.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst
Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst
Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst
Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst
Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst
Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst
error: Failed to download from mirror set
error: https://mirror.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst: failed: status code 404
error: https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst: failed: status code 404
error: https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst: failed: status code 404
error: https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst: failed: status code 404
error: https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst: failed: status code 404
error: https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst: failed: status code 404
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1003): 
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 13us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 792us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 931 ms (926125us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
      

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_acquire_msys.cmake:25 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_acquire_msys.cmake:124 (z_vcpkg_acquire_msys_download_package)
  scripts/cmake/vcpkg_acquire_msys.cmake:209 (z_vcpkg_acquire_msys_download_packages)
  scripts/cmake/vcpkg_find_acquire_program(PKGCONFIG).cmake:22 (vcpkg_acquire_msys)
  scripts/cmake/vcpkg_find_acquire_program.cmake:118 (include)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:203 (vcpkg_find_acquire_program)
  C:/Users/New/AppData/Local/vcpkg/registries/git-trees/3f452404270b508daf355b72031ad3ee7d0d5751/portfile.cmake:46 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:147 (include)

error: building fmt:x64-windows-static failed with: BUILD_FAILED
Elapsed time to handle fmt:x64-windows-static: 4.3 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+fmt
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[fmt]+Build+error&body=Copy+issue+body+from+C%3A%2F_MODDING%2FSKSE_Template_HelloWorld%2Fbuild%2Fdebug%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md

`

**Comment by peterpanning** [comment]
When you say FIX: had to be reinstalled mvs, do you mean you needed to reinstall visual studio?

**Comment by ARTH1S** [comment]
> When you say FIX: had to be reinstalled mvs, do you mean you needed to reinstall visual studio?

yes

**Comment by peterpanning** [comment]
This also fixed it for me--not even a full install, just uninstalling unused libraries and updating visual studio
