### ISSUE TITLE
[paho-mqttpp3] Build using HIGH_PERFORMANCE

### ISSUE THREAD

**Issue by mvccogo** [microsoft/vcpkg#36052]
### Is your feature request related to a problem? Please describe.

By default, Paho MQTT C++ should be built with the PAHO_HIGH_PERFORMANCE=ON setting. As specified in [here](https://github.com/eclipse/paho.mqtt.cpp):

> It also uses the "high performance" option of the C library to disable more extensive internal memory checks. Remove the PAHO_HIGH_PERFORMANCE option (i.e. turn it off) to debug memory issues, but for most production systems, leave it on for better performance.`

Every malloc/free call is burdened with extra debug operations that the end-user does not expect on a production environment.

### Proposed solution

Build with PAHO_HIGH_PERFORMANCE=ON, such as described in their docs:
`cmake -Bbuild -H. -DPAHO_ENABLE_TESTING=OFF -DPAHO_BUILD_STATIC=ON \
    -DPAHO_WITH_SSL=ON -DPAHO_HIGH_PERFORMANCE=ON`

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by carsten-grimm-at-ipolog** [comment]
My understanding from the readme and the corresponding `CMakeLists.txt`s is that this option must be set for the underlying c library `paho-mqtt`, not for `paho-mqttpp3`. I can prepare a pull request shortly adding this option to `paho-mqtt`.

Once that is merged, you would need to remove `paho-mqtt` with `--recurse` and then reinstall `paho-mqttpp3` to benefit from the change.
