### ISSUE TITLE
Ogre Build failed 

### ISSUE THREAD

**Issue by ThinkalVB** [Microsoft/vcpkg#3606]
C:\Program Files\vcpkg>vcpkg search ogre
ogre                 1.10.11          3D Object-Oriented Graphics Rendering Engine
ogre[d3d9]                            Build Direct3D9 RenderSystem
ogre[java]                            Build Java (JNI) bindings
ogre[python]                          Build Python bindings

If your library is not listed, please open an issue at and/or consider making a pull request:
    https://github.com/Microsoft/vcpkg/issues

C:\Program Files\vcpkg>vcpkg install ogre
The following packages will be built and installed:
  * bzip2[core]:x86-windows
  * freeimage[core]:x86-windows
  * freetype[core]:x86-windows
  * ilmbase[core]:x86-windows
  * jasper[core]:x86-windows
  * jxrlib[core]:x86-windows
  * lcms[core]:x86-windows
  * libjpeg-turbo[core]:x86-windows
  * liblzma[core]:x86-windows
  * libpng[core]:x86-windows
  * libraw[core]:x86-windows
  * libwebp[core]:x86-windows
    ogre[core]:x86-windows
  * openexr[core]:x86-windows
  * openjpeg[core]:x86-windows
  * tiff[core]:x86-windows
  * zlib[core]:x86-windows
  * zziplib[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/18: zlib:x86-windows
Building package zlib[core]:x86-windows...
A suitable version of git was not found (required v2.17.0). Downloading portable git v2.17.0...
Downloading git...
Downloading git... done.
Extracting git...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
Downloading 7zip... done.
Extracting 7zip...
A suitable version of nuget was not found (required v4.6.2). Downloading portable nuget v4.6.2...
Downloading nuget...
Downloading nuget... done.
Extracting 7zip... done.
Extracting git... done.
-- CURRENT_INSTALLED_DIR=C:/Program Files/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/Program Files/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Program Files/vcpkg/packages/zlib_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/Program Files/vcpkg/buildtrees/zlib
-- CURRENT_PORT_DIR=C:/Program Files/vcpkg/ports/zlib
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz...
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting source C:/Program Files/vcpkg/downloads/zlib1211.tar.gz
-- Extracting done
-- Applying patch C:/Program Files/vcpkg/ports/zlib/cmake_dont_build_more_than_needed.patch
-- Applying patch C:/Program Files/vcpkg/ports/zlib/cmake_dont_build_more_than_needed.patch done
-- Downloading https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip...
-- Downloading https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Configuring x86-windows
-- Configuring x86-windows done
-- Build x86-windows-dbg
-- Build x86-windows-dbg done
-- Build x86-windows-rel
-- Build x86-windows-rel done
-- Installing: C:/Program Files/vcpkg/packages/zlib_x86-windows/share/zlib/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package zlib[core]:x86-windows... done
Installing package zlib[core]:x86-windows...
Installing package zlib[core]:x86-windows... done
Elapsed time for package zlib:x86-windows: 1.989 min
Starting package 2/18: libjpeg-turbo:x86-windows
Building package libjpeg-turbo[core]:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/Program Files/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/Program Files/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Program Files/vcpkg/packages/libjpeg-turbo_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/Program Files/vcpkg/buildtrees/libjpeg-turbo
-- CURRENT_PORT_DIR=C:/Program Files/vcpkg/ports/libjpeg-turbo
-- Downloading https://github.com/libjpeg-turbo/libjpeg-turbo/archive/1.5.3.tar.gz...
-- Downloading https://github.com/libjpeg-turbo/libjpeg-turbo/archive/1.5.3.tar.gz... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting source C:/Program Files/vcpkg/downloads/libjpeg-turbo-libjpeg-turbo-1.5.3.tar.gz
-- Extracting done
-- Downloading https://github.com/libjpeg-turbo/libjpeg-turbo/commit/bd96b30b74fe166fc94218cfc64a097fafdcc05f.diff...
-- Downloading https://github.com/libjpeg-turbo/libjpeg-turbo/commit/bd96b30b74fe166fc94218cfc64a097fafdcc05f.diff... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Applying patch C:/Program Files/vcpkg/ports/libjpeg-turbo/add-options-for-exes-docs-headers.patch
-- Applying patch C:/Program Files/vcpkg/ports/libjpeg-turbo/add-options-for-exes-docs-headers.patch done
-- Applying patch C:/Program Files/vcpkg/ports/libjpeg-turbo/linux-cmake.patch
-- Applying patch C:/Program Files/vcpkg/ports/libjpeg-turbo/linux-cmake.patch done
-- Applying patch C:/Program Files/vcpkg/downloads/libjpeg-turbo-bd96b30b74fe166fc94218cfc64a097fafdcc05f.diff
-- Applying patch C:/Program Files/vcpkg/downloads/libjpeg-turbo-bd96b30b74fe166fc94218cfc64a097fafdcc05f.diff done
-- Downloading http://www.nasm.us/pub/nasm/releasebuilds/2.12.02/win32/nasm-2.12.02-win32.zip...
-- Downloading http://www.nasm.us/pub/nasm/releasebuilds/2.12.02/win32/nasm-2.12.02-win32.zip... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Configuring x86-windows
-- Configuring x86-windows done
-- Build x86-windows-dbg
-- Build x86-windows-dbg done
-- Build x86-windows-rel
-- Build x86-windows-rel done
-- Performing post-build validation
-- Performing post-build validation done
Building package libjpeg-turbo[core]:x86-windows... done
Installing package libjpeg-turbo[core]:x86-windows...
Installing package libjpeg-turbo[core]:x86-windows... done
Elapsed time for package libjpeg-turbo:x86-windows: 1.436 min
Starting package 3/18: liblzma:x86-windows
Building package liblzma[core]:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/Program Files/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/Program Files/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Program Files/vcpkg/packages/liblzma_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/Program Files/vcpkg/buildtrees/liblzma
-- CURRENT_PORT_DIR=C:/Program Files/vcpkg/ports/liblzma
-- Downloading https://github.com/xz-mirror/xz/archive/v5.2.3.tar.gz...
-- Downloading https://github.com/xz-mirror/xz/archive/v5.2.3.tar.gz... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting source C:/Program Files/vcpkg/downloads/xz-mirror-xz-v5.2.3.tar.gz
-- Extracting done
-- Configuring x86-windows
-- Configuring x86-windows done
-- Build x86-windows-dbg
-- Build x86-windows-dbg done
-- Build x86-windows-rel
-- Build x86-windows-rel done
-- Performing post-build validation
-- Performing post-build validation done
Building package liblzma[core]:x86-windows... done
Installing package liblzma[core]:x86-windows...
Installing package liblzma[core]:x86-windows... done
Elapsed time for package liblzma:x86-windows: 1.356 min
Starting package 4/18: tiff:x86-windows
Building package tiff[core]:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/Program Files/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/Program Files/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Program Files/vcpkg/packages/tiff_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/Program Files/vcpkg/buildtrees/tiff
-- CURRENT_PORT_DIR=C:/Program Files/vcpkg/ports/tiff
-- Downloading http://download.osgeo.org/libtiff/tiff-4.0.9.tar.gz...
-- Downloading http://download.osgeo.org/libtiff/tiff-4.0.9.tar.gz... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting source C:/Program Files/vcpkg/downloads/tiff-4.0.9.tar.gz
-- Extracting done
-- Applying patch C:/Program Files/vcpkg/ports/tiff/add-component-options.patch
-- Applying patch C:/Program Files/vcpkg/ports/tiff/add-component-options.patch done
-- Applying patch C:/Program Files/vcpkg/ports/tiff/fix-cxx-shared-libs.patch
-- Applying patch C:/Program Files/vcpkg/ports/tiff/fix-cxx-shared-libs.patch done
-- Applying patch C:/Program Files/vcpkg/ports/tiff/crt-secure-no-deprecate.patch
-- Applying patch C:/Program Files/vcpkg/ports/tiff/crt-secure-no-deprecate.patch done
-- Configuring x86-windows
-- Configuring x86-windows done
-- Build x86-windows-dbg
-- Build x86-windows-dbg done
-- Build x86-windows-rel
-- Build x86-windows-rel done
-- Installing: C:/Program Files/vcpkg/packages/tiff_x86-windows/share/tiff/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package tiff[core]:x86-windows... done
Installing package tiff[core]:x86-windows...
Installing package tiff[core]:x86-windows... done
Elapsed time for package tiff:x86-windows: 3.625 min
Starting package 5/18: libpng:x86-windows
Building package libpng[core]:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/Program Files/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/Program Files/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Program Files/vcpkg/packages/libpng_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/Program Files/vcpkg/buildtrees/libpng
-- CURRENT_PORT_DIR=C:/Program Files/vcpkg/ports/libpng
-- Downloading https://github.com/glennrp/libpng/archive/v1.6.34.tar.gz...
-- Downloading https://github.com/glennrp/libpng/archive/v1.6.34.tar.gz... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting source C:/Program Files/vcpkg/downloads/glennrp-libpng-v1.6.34.tar.gz
-- Extracting done
-- Applying patch C:/Program Files/vcpkg/ports/libpng/use-abort-on-all-platforms.patch
-- Applying patch C:/Program Files/vcpkg/ports/libpng/use-abort-on-all-platforms.patch done
-- Applying patch C:/Program Files/vcpkg/ports/libpng/skip-install-symlink.patch
-- Applying patch C:/Program Files/vcpkg/ports/libpng/skip-install-symlink.patch done
-- Configuring x86-windows
-- Configuring x86-windows done
-- Build x86-windows-dbg
-- Build x86-windows-dbg done
-- Build x86-windows-rel
-- Build x86-windows-rel done
-- Performing post-build validation
-- Performing post-build validation done
Building package libpng[core]:x86-windows... done
Installing package libpng[core]:x86-windows...
Installing package libpng[core]:x86-windows... done
Elapsed time for package libpng:x86-windows: 1.306 min
Starting package 6/18: ilmbase:x86-windows
Building package ilmbase[core]:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/Program Files/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/Program Files/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Program Files/vcpkg/packages/ilmbase_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/Program Files/vcpkg/buildtrees/ilmbase
-- CURRENT_PORT_DIR=C:/Program Files/vcpkg/ports/ilmbase
-- Downloading http://download.savannah.nongnu.org/releases/openexr/ilmbase-2.2.1.tar.gz...
-- Downloading http://download.savannah.nongnu.org/releases/openexr/ilmbase-2.2.1.tar.gz... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting source C:/Program Files/vcpkg/downloads/ilmbase-2.2.1.tar.gz
-- Extracting done
-- Applying patch C:/Program Files/vcpkg/ports/ilmbase/fix-parallel-build.patch
-- Applying patch C:/Program Files/vcpkg/ports/ilmbase/fix-parallel-build.patch done
-- Configuring x86-windows
-- Configuring x86-windows done
-- Build x86-windows-dbg
-- Build x86-windows-dbg done
-- Build x86-windows-rel
-- Build x86-windows-rel done
-- Performing post-build validation
-- Performing post-build validation done
Building package ilmbase[core]:x86-windows... done
Installing package ilmbase[core]:x86-windows...
Installing package ilmbase[core]:x86-windows... done
Elapsed time for package ilmbase:x86-windows: 2.934 min
Starting package 7/18: openexr:x86-windows
Building package openexr[core]:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/Program Files/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/Program Files/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Program Files/vcpkg/packages/openexr_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/Program Files/vcpkg/buildtrees/openexr
-- CURRENT_PORT_DIR=C:/Program Files/vcpkg/ports/openexr
-- Downloading http://download.savannah.nongnu.org/releases/openexr/openexr-2.2.1.tar.gz...
-- Downloading http://download.savannah.nongnu.org/releases/openexr/openexr-2.2.1.tar.gz... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting source C:/Program Files/vcpkg/downloads/openexr-2.2.1.tar.gz
-- Extracting done
-- Applying patch C:/Program Files/vcpkg/ports/openexr/add-missing-export.patch
-- Applying patch C:/Program Files/vcpkg/ports/openexr/add-missing-export.patch done
-- Applying patch C:/Program Files/vcpkg/ports/openexr/CMakeLists.txt.patch
-- Applying patch C:/Program Files/vcpkg/ports/openexr/CMakeLists.txt.patch done
-- Applying patch C:/Program Files/vcpkg/ports/openexr/fix-static-linking.patch
-- Applying patch C:/Program Files/vcpkg/ports/openexr/fix-static-linking.patch done
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: C:/Program Files/vcpkg/buildtrees/openexr/x86-windows-rel/vcpkg-parallel-configure
    See logs for more information:
      C:\Program Files\vcpkg\buildtrees\openexr\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:237 (vcpkg_execute_required_process)
  ports/openexr/portfile.cmake:26 (vcpkg_configure_cmake)
  scripts/ports.cmake:72 (include)

Error: Building package openexr:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openexr:x86-windows
  Vcpkg version: 0.0.113-nohash

Additionally, attach any relevant sections from the log files above.

C:\Program Files\vcpkg>

**Comment by Voskrese** [comment]
Command failed: ninja;-v

C:\Program Files\vcpkg\buildtrees\openexr\config-x86-windows-out.log

**Comment by ThinkalVB** [comment]
I tried the same with the x64 and it failed in the same way 
[config-x64-windows-out.log](https://github.com/Microsoft/vcpkg/files/2053935/config-x64-windows-out.log)

**Comment by NancyLi1013** [comment]
Thanks for posting this issue. I cannot reproduce it on the latest vcpkg.
Please open a new issue if this is still a problem for you.
