### ISSUE TITLE
Failure to store binary cache on all installs

### ISSUE THREAD

**Issue by tgill880** [microsoft/vcpkg#36064]
**Describe the bug**
All of my installs are getting this warning (with a different cache file each time)

```
Failed to store binary cache /Users/xxx/.cache/vcpkg/archives/8d/8d7a5482fcf0387ce6322a672f28b7a72262bbc0b2372e5757d19f18e265ed6b.zip
No such file or directory
```

**Environment**
- OS: MacBook Air M1, Sonoma 14.1.2
- Compiler: Apple clang version 15.0.0 (clang-1500.1.0.2.5)
- vcpkg: vcpkg package management program version 2023-12-12-1c9ec1978a6b0c2b39c9e9554a96e3e275f7556e

**To Reproduce**
1. ./vcpkg install `anything`

**Expected behavior**
Is this a problem?

**Failure logs**
Here is an example from installing `CImg`.

```
 % vcpkg install cimg:arm64-osx
Computing installation plan...
The following packages will be built and installed:
    cimg:arm64-osx@3.3.2
  * vcpkg-cmake:arm64-osx@2023-05-04
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet arm64-osx...
Restored 0 package(s) from /Users/thurmangillespy/.cache/vcpkg/archives in 879 us. Use --debug to see more details.
Installing 1/2 vcpkg-cmake:arm64-osx@2023-05-04...
Building vcpkg-cmake:arm64-osx@2023-05-04...
warning: -- Using community triplet arm64-osx. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /Users/thurmangillespy/Projects/vcpkg/triplets/community/arm64-osx.cmake
-- Installing: /Users/thurmangillespy/Projects/vcpkg/packages/vcpkg-cmake_arm64-osx/share/vcpkg-cmake/vcpkg_cmake_configure.cmake
-- Installing: /Users/thurmangillespy/Projects/vcpkg/packages/vcpkg-cmake_arm64-osx/share/vcpkg-cmake/vcpkg_cmake_build.cmake
-- Installing: /Users/thurmangillespy/Projects/vcpkg/packages/vcpkg-cmake_arm64-osx/share/vcpkg-cmake/vcpkg_cmake_install.cmake
-- Installing: /Users/thurmangillespy/Projects/vcpkg/packages/vcpkg-cmake_arm64-osx/share/vcpkg-cmake/vcpkg-port-config.cmake
-- Installing: /Users/thurmangillespy/Projects/vcpkg/packages/vcpkg-cmake_arm64-osx/share/vcpkg-cmake/copyright
-- Performing post-build validation
Failed to store binary cache /Users/thurmangillespy/.cache/vcpkg/archives/b6/b6432545c52e65066991bd8871cebb3083e52711d9b6cea94c9b7faabe5fa9a0.zip
No such file or directory
Stored binaries in 0 destinations in 7.01 ms.
Elapsed time to handle vcpkg-cmake:arm64-osx: 47.6 ms
vcpkg-cmake:arm64-osx package ABI: b6432545c52e65066991bd8871cebb3083e52711d9b6cea94c9b7faabe5fa9a0
Installing 2/2 cimg:arm64-osx@3.3.2...
Building cimg:arm64-osx@3.3.2...
warning: -- Using community triplet arm64-osx. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /Users/thurmangillespy/Projects/vcpkg/triplets/community/arm64-osx.cmake
-- Downloading https://github.com/dtschump/CImg/archive/v.3.3.2.tar.gz -> dtschump-CImg-v.3.3.2.tar.gz...
-- Extracting source /Users/thurmangillespy/Projects/vcpkg/downloads/dtschump-CImg-v.3.3.2.tar.gz
-- Using source at /Users/thurmangillespy/Projects/vcpkg/buildtrees/cimg/src/v.3.3.2-ebb0c3ad69.clean
-- Found external ninja('1.11.1').
-- Configuring arm64-osx
-- Building arm64-osx-rel
-- Performing post-build validation
Failed to store binary cache /Users/thurmangillespy/.cache/vcpkg/archives/c1/c15e5b54a98b74da91b9a44a2b04767973e49146dc5257bf66262eaa90942ed9.zip
No such file or directory
Stored binaries in 0 destinations in 104 ms.
Elapsed time to handle cimg:arm64-osx: 6.2 s
cimg:arm64-osx package ABI: c15e5b54a98b74da91b9a44a2b04767973e49146dc5257bf66262eaa90942ed9
Total install time: 6.2 s
cimg provides CMake targets:

  # this is heuristically generated, and may not be correct
  find_package(CImg CONFIG REQUIRED)
  target_link_libraries(main PRIVATE CImg::CImg)
```

**Additional context**
The install otherwise succeeds.

A previous ticket (which I can't find) had a similar problem with non-ASCII characters in the file path, but that's not an issue here.

**Comment by jimwang118** [comment]
I haven't reproduced this issue locally.
![image](https://github.com/microsoft/vcpkg/assets/122244446/d256b328-13a2-4f0e-9cc2-3f6074cdb598)

**Comment by tgill880** [comment]
Perhaps try on an Apple Silicon Mac?

Your system.
```
The following packages will be built and installed:
   cimg:x64-osx@3.3.2
Detecting compiler hash for triplet x64-osx...
```

My system.
```
The following packages will be built and installed:
    cimg:arm64-osx@3.3.2
  * vcpkg-cmake:arm64-osx@2023-05-04
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet arm64-osx...
```

**Comment by StarGate-One** [comment]
The `arm64-osx` triplet is only supported via the user community, where `x64-osx` triplet is the official Microsoft supported triplet for `Apple Hardware` at this time. 

I believe they are working on remedying this in the near future, but until then here are a few things to check:

- It may be a permissions issue on the directory structure vcpkg is trying to write to...
`/Users/thurmangillespy/.cache/`
`/Users/thurmangillespy/.cache/vcpkg/`
`/Users/thurmangillespy/.cache/vcpkg/archives`

- It may also be an antivirus setting... holding an open file handle or deleting the file...

Maybe someone in the user-community who has `arm64-osx Apple Silicon` can look into the possible causes of the issue shortly?

**Comment by autoantwort** [comment]
I can't reproduce on my arm64-osx mac

**Comment by tgill880** [comment]
> The `arm64-osx` triplet is only supported via the user community, where `x64-osx` triplet is the official Microsoft supported triplet for `Apple Hardware` at this time.
> 
> I believe they are working on remedying this in the near future - see #19454, but until then here are a few things to check:
> 
> * It may be a permissions issue on the directory structure vcpkg is trying to write to...
>   `/Users/thurmangillespy/.cache/`
>   `/Users/thurmangillespy/.cache/vcpkg/`
>   `/Users/thurmangillespy/.cache/vcpkg/archives`
> * It may also be an antivirus setting... holding an open file handle or deleting the file...
> 
> Maybe someone in the user-community who has `arm64-osx Apple Silicon` can look into the possible causes of the issue shortly?

All the directories listed have the same permissions, which seem correct:
`drwxr-xr-x`

No antivirus.

I suspect my vcpkg install, or the computer, is somehow corrupted.

**Comment by dg0yt** [comment]
> All the directories listed have the same permissions, which seem correct:
> `drwxr-xr-x`

You can try `rm -Rf /Users/thurmangillespy/.cache/vcpkg` nevertheless.

**Comment by tgill880** [comment]
> > All the directories listed have the same permissions, which seem correct:
> > `drwxr-xr-x`
> 
> You can try `rm -Rf /Users/thurmangillespy/.cache/vcpkg` nevertheless.

I got `Permission denied` for every file and folder in the `/.cache/vcpkg` directory. I could override by executing the command with `sudo`, but does this response give us a clue?

**Comment by dg0yt** [comment]
It confirms that the problem is the directory, not vcpkg...
When you looked for directory permissions, did you also look for the owner?

**Comment by tgill880** [comment]
> It confirms that the problem is the directory, not vcpkg... When you looked for directory permissions, did you also look for the owner?

Bingo. Owner was `root` (!). A bit of `chown` fixed the problem. Many thanks.
