### ISSUE TITLE
Regarding libpcap live packet capture support

### ISSUE THREAD

**Issue by maordadush** [microsoft/vcpkg#36067]
[config-x64-windows-static-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/13853627/config-x64-windows-static-rel-CMakeCache.txt.log)
[config-x64-windows-static-rel-err.log](https://github.com/microsoft/vcpkg/files/13853628/config-x64-windows-static-rel-err.log)
[config-x64-windows-static-rel-out.log](https://github.com/microsoft/vcpkg/files/13853629/config-x64-windows-static-rel-out.log)
### Discussed in https://github.com/microsoft/vcpkg/discussions/35395

<div type='discussions-op-text'>

<sup>Originally posted by **maordadush** November 29, 2023</sup>
by default, libpcap vcpkg is not compiling the package with live packet capture support. so to support it, the CMake needs to have Packet_ROOT defined before the check-in libpcap's CMakeLists.txt for the packet capture mechanism is done,  how that be accomplished?

I tried to add `-DPacket_ROOT=` argument in the libpcap portfile.cmake file

```
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    DISABLE_PARALLEL_CONFIGURE
    OPTIONS
        -DPacket_ROOT="C:/npcap-sdk"
        -DDISABLE_NETMAP=ON
        -DDISABLE_BLUETOOTH=ON
        -DDISABLE_DBUS=ON
        -DDISABLE_RDMA=ON
        -DDISABLE_DAG=ON
        -DDISABLE_SEPTEL=ON
        -DDISABLE_SNF=ON
        -DDISABLE_TC=ON
        -DDISABLE_PACKET=OFF
        -DENABLE_REMOTE=OFF
        -DUSE_STATIC_RT=${USE_STATIC_RT}
)
```
and I still get the "live packet capture not supported on this system" error.
</div>

**Comment by dg0yt** [comment]
https://github.com/microsoft/vcpkg/discussions/35395#discussioncomment-8040809

**Comment by maordadush** [comment]
[https://github.com/microsoft/vcpkg/discussions/35395#discussioncomment-8050491](url)
