### ISSUE TITLE
libtorrent example Build with dyn_tls_on_demand_init

### ISSUE THREAD

**Issue by killghost** [microsoft/vcpkg#36068]
### Operating system

win10

### Compiler

VS2022

### Steps to reproduce the behavior

```Shell
vcpkg install libtorrent[examples]:x86-windows-static  -rescure

This example can be compiled. But when I created a VS2022 project, I used the code of example: bt-get.cpp. The error occurred when I compiled this project statically. I referred to the configuration in vcpkg\buildtrees\libtorrent\x86-windows-static-rel\build.ninja. Contains all required libs. But still not correct.

Build Examples \ CMAKEFILES \ Simple_Client.dir \ Simple_Client.CPP.OBJ: CXX_COMPILER__CLIENT_UNSCANNED_RELELEASE F $: \ vcpkg-newstree S \ LibTorrent \ SRC \ v2.0.9-b2c835423E.CLEAN \ Examples \ Simple_Client.cpp || Cmake_Object_ORDER_DERGET_SIMPLE_Client
   DEFINES = -DBOOST_ALL_NO_LIB -DBOOST_ASIO_ENABLE_CANCELIO -DBOOST_ASIO_NO_DEPRECATED -DOPENSSL_NO_SSL2 -DTORRENT_NO_DEPRECATE -DTORRENT_SSL_PEERS -DTORRENT_USE_LIBCRYPTO -DTORRENT_USE_OPENSSL -DWIN32_LEAN_AND_MEAN -D_CRT_SE CURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_WIN32_WINNT=0x0601
   FLAGS = /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP /MT /O2 /Oi /Gy /DNDEBUG /Z7 -MT /W4 /wd4251 /wd4268 /wd4275 /wd4373 /wd4503 /EHsc
   INCLUDES = -IF:\vcpkg-new\buildtrees\libtorrent\src\v2.0.9-b2c835423e.clean\include -external:IF:\vcpkg-new\installed\x86-windows-static\include -external:W0
   OBJECT_DIR = examples\CMakeFiles\simple_client.dir
   OBJECT_FILE_DIR = examples\CMakeFiles\simple_client.dir
   TARGET_COMPILE_PDB = examples\CMakeFiles\simple_client.dir\
   TARGET_PDB = examples\simple_client.pdb
```

### Failure logs

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2001	无法解析的外部符号 ___dyn_tls_on_demand_init	Project7	C:\Users\killg\source\repos\Project7\torrent-rasterbar.lib(web_peer_connection.cpp.obj)	1	
错误	LNK2001	无法解析的外部符号 ___dyn_tls_on_demand_init	Project7	C:\Users\killg\source\repos\Project7\torrent-rasterbar.lib(udp_tracker_connection.cpp.obj)	1	
错误	LNK2001	无法解析的外部符号 ___dyn_tls_on_demand_init	Project7	C:\Users\killg\source\repos\Project7\torrent-rasterbar.lib(http_connection.cpp.obj)	1	
错误	LNK2001	无法解析的外部符号 ___dyn_tls_on_demand_init	Project7	C:\Users\killg\source\repos\Project7\torrent-rasterbar.lib(natpmp.cpp.obj)	1	
错误	LNK2001	无法解析的外部符号 ___dyn_tls_on_demand_init	Project7	C:\Users\killg\source\repos\Project7\torrent-rasterbar.lib(lsd.cpp.obj)	1	
错误	LNK2001	无法解析的外部符号 ___dyn_tls_on_demand_init	Project7	C:\Users\killg\source\repos\Project7\torrent-rasterbar.lib(instantiate_connection.cpp.obj)	1	
错误	LNK2001	无法解析的外部符号 ___dyn_tls_on_demand_init	Project7	C:\Users\killg\source\repos\Project7\torrent-rasterbar.lib(disk_buffer_pool.cpp.obj)	1	
错误	LNK2001	无法解析的外部符号 ___dyn_tls_on_demand_init	Project7	C:\Users\killg\source\repos\Project7\torrent-rasterbar.lib(ip_notifier.cpp.obj)	1	
错误	LNK2001	无法解析的外部符号 ___dyn_tls_on_demand_init	Project7	C:\Users\killg\source\repos\Project7\torrent-rasterbar.lib(resolver.cpp.obj)	1	
错误	LNK2001	无法解析的外部符号 ___dyn_tls_on_demand_init	Project7	C:\Users\killg\source\repos\Project7\torrent-rasterbar.lib(dht_tracker.cpp.obj)	1	
错误	LNK2001	无法解析的外部符号 ___dyn_tls_on_demand_init	Project7	C:\Users\killg\source\repos\Project7\torrent-rasterbar.lib(upnp.cpp.obj)	1	
错误	LNK2001	无法解析的外部符号 ___dyn_tls_on_demand_init	Project7	C:\Users\killg\source\repos\Project7\torrent-rasterbar.lib(proxy_base.cpp.obj)	1	
错误	LNK2001	无法解析的外部符号 ___dyn_tls_on_demand_init	Project7	C:\Users\killg\source\repos\Project7\torrent-rasterbar.lib(utp_stream.cpp.obj)	1	
错误	LNK2001	无法解析的外部符号 ___dyn_tls_on_demand_init	Project7	C:\Users\killg\source\repos\Project7\torrent-rasterbar.lib(socket_type.cpp.obj)	1	
错误	LNK2001	无法解析的外部符号 ___dyn_tls_on_demand_init	Project7	C:\Users\killg\source\repos\Project7\torrent-rasterbar.lib(peer_connection.cpp.obj)	1	
错误	LNK2001	无法解析的外部符号 ___dyn_tls_on_demand_init	Project7	C:\Users\killg\source\repos\Project7\torrent-rasterbar.lib(posix_disk_io.cpp.obj)	1	
错误	LNK2001	无法解析的外部符号 ___dyn_tls_on_demand_init	Project7	C:\Users\killg\source\repos\Project7\torrent-rasterbar.lib(torrent.cpp.obj)	1	
错误	LNK2001	无法解析的外部符号 ___dyn_tls_on_demand_init	Project7	C:\Users\killg\source\repos\Project7\torrent-rasterbar.lib(udp_socket.cpp.obj)	1	
错误	LNK2001	无法解析的外部符号 ___dyn_tls_on_demand_init	Project7	C:\Users\killg\source\repos\Project7\torrent-rasterbar.lib(tracker_manager.cpp.obj)	1	
错误	LNK2001	无法解析的外部符号 ___dyn_tls_on_demand_init	Project7	C:\Users\killg\source\repos\Project7\torrent-rasterbar.lib(session_handle.cpp.obj)	1	
错误	LNK2001	无法解析的外部符号 ___dyn_tls_on_demand_init	Project7	C:\Users\killg\source\repos\Project7\torrent-rasterbar.lib(session.cpp.obj)	1	
错误	LNK2001	无法解析的外部符号 ___dyn_tls_on_demand_init	Project7	C:\Users\killg\source\repos\Project7\torrent-rasterbar.lib(torrent_handle.cpp.obj)	1	
错误	LNK2001	无法解析的外部符号 ___dyn_tls_on_demand_init	Project7	C:\Users\killg\source\repos\Project7\torrent-rasterbar.lib(session_impl.cpp.obj)	1	
错误	LNK2001	无法解析的外部符号 ___tls_guard	Project7	C:\Users\killg\source\repos\Project7\torrent-rasterbar.lib(web_peer_connection.cpp.obj)	1	
错误	LNK2001	无法解析的外部符号 ___tls_guard	Project7	C:\Users\killg\source\repos\Project7\torrent-rasterbar.lib(udp_tracker_connection.cpp.obj)	1	
错误	LNK2001	无法解析的外部符号 ___tls_guard	Project7	C:\Users\killg\source\repos\Project7\torrent-rasterbar.lib(http_connection.cpp.obj)	1	

### Additional context

#include <iostream>
#include <thread>
#include <chrono>

#include <libtorrent/session.hpp>
#include <libtorrent/session_params.hpp>
#include <libtorrent/add_torrent_params.hpp>
#include <libtorrent/torrent_handle.hpp>
#include <libtorrent/alert_types.hpp>
#include <libtorrent/magnet_uri.hpp>

  {
  

      try
      {
          //if (argc != 2) {
          //    std::cerr << "usage: " << argv[0] << " <magnet-url>" << std::endl;
          //    return 1;
          //}
          lt::settings_pack p;
          p.set_int(lt::settings_pack::alert_mask, lt::alert_category::status
              | lt::alert_category::error);
          lt::session ses(p);

          lt::add_torrent_params atp = lt::parse_magnet_uri("magnet:?xt=urn:sha1:YNCKHTQCWBTRNJIV4WNAE52SJUQCZO5C");
          atp.save_path = "."; // save in current dir
          lt::torrent_handle h = ses.add_torrent(std::move(atp));

          for (;;) {
              std::vector<lt::alert*> alerts;
              ses.pop_alerts(&alerts);

              for (lt::alert const* a : alerts) {
                  std::cout << a->message() << std::endl;
                  // if we receive the finished alert or an error, we're done
                  if (lt::alert_cast<lt::torrent_finished_alert>(a)) {
                      goto done;
                  }
                  if (lt::alert_cast<lt::torrent_error_alert>(a)) {
                      goto done;
                  }
              }
              std::this_thread::sleep_for(std::chrono::milliseconds(200));
          }
      done:
          std::cout << "done, shutting down" << std::endl;
      }
      catch (std::exception& e)
      {
          std::cerr << "Error: " << e.what() << std::endl;
      }

**Comment by killghost** [comment]
torrent-rasterbar.lib;bcrypt.lib;mswsock.lib;iphlpapi.lib;libssl.lib;libcrypto.lib;ws2_32.lib;crypt32.lib;kernel32.lib;user32.lib;gdi32.lib;winspool.lib;shell32.lib;ole32.lib;oleaut32.lib;uuid.lib;comdlg32.lib;advapi32.lib;%(AdditionalDependencies)

These are the library files I use.
Thanks.

**Comment by FrankXie05** [comment]
```
错误 LNK2001 无法解析的外部符号 ___dyn_tls_on_demand_init Project7 C:\Users\killg\source\repos\Project7\torrent-rasterbar.lib(udp_tracker_connection.cpp.obj) 1
```
This is not an imported symbol.
