### ISSUE TITLE
[mpir] Add instructions for adding MPIR in CMAKE project

### ISSUE THREAD

**Issue by ivanovmp** [microsoft/vcpkg#36076]
### Is your feature request related to a problem? Please describe.

For most of the packages after the installation a brief instructions for package usage appear, e.g.:
```
> vcpkg install tiff:x64-windows
.
.
.
tiff is compatible with built-in CMake targets:

    find_package(TIFF REQUIRED)
    target_link_libraries(main PRIVATE TIFF::TIFF)

tiff provides pkg-config modules:

    #  Tag Image File Format (TIFF) library.
    libtiff-4
```

However, for `mpir:x64-windows` it is not the case, it simply says the elapsed time and stops the installation.

So it is very unclear how to include this package in a CMake project.

I spent a lot of time and found the following suggestion:
1. When running `cmake`, always add the following option: `-DCMAKE_TOOLCHAIN_FILE:FILEPATH="...\scripts\buildsystems\vcpkg.cmake"` where `...` is the `vcpkg` directory.
2. Add the following lines to the CMake file:
  ```
  find_package(PkgConfig REQUIRED)
  pkg_check_modules(gmpxx REQUIRED IMPORTED_TARGET gmpxx)
  target_link_libraries(main PkgConfig::gmpxx)
  ```

So I have three questions.
1. Should these two things be enough for everything working correctly?
2. If so, could these lines be added somehow into the installation process, so that they popped up after `vcpkg install mpir:x64-windows` running and the used could read them and have an idea how to include MPIR into their project?
3. If the answer to the first question is `yes`, why it does not work for me? I am constanly getting an error, and it seems to be caused by `pkgconf` being not found by `cmake` (I described this issue in https://github.com/microsoft/vcpkg/issues/36075). Maybe there is a way to include MPIR in a CMake project without the complications induced by `PkgConfig` usage?

### Proposed solution

Make the following lines appear each time someone installs `mpir` for Windows:
```
find_package(PkgConfig REQUIRED)
pkg_check_modules(gmpxx REQUIRED IMPORTED_TARGET gmpxx)
target_link_libraries(main PkgConfig::gmpxx)
```

In principle, it would be extremely nice if for every package there existed some minimum working CMakeFile somewhere in an accessible place.

**Comment by ivanovmp** [comment]
After I was able to get `PkgConfig` working, I still cannot import `gmpxx`.

Steps to reproduce (I am currently on Windows 10 Home):
1. Create a file `C:\test\a.cpp` with contents:
  ```c++
  #include <iostream>
  #include "gmpxx.h"
  using namespace std;
  int main() {
  	mpz_class z("122345673432785234865278546");
  	cout << z * z;
  }
  ```
2. Create a file `C:\test\CMakeLists.txt` with contents:
  ```
  cmake_minimum_required(VERSION 3.27)
  project(aaa)
  set(CMAKE_CXX_STANDARD 20)
  find_package(PkgConfig REQUIRED)
  pkg_check_modules(gmpxx REQUIRED IMPORTED_TARGET gmpxx)
  target_link_libraries(main PkgConfig::gmpxx)
  add_executable(main a.cpp)
  ```
3. Run `C:\misc\vcpkg\vcpkg.exe install mpir`, it runs successfully.
4. Run the command:
  ```
  "C:\misc\vcpkg\downloads\tools\cmake-3.27.1-windows\cmake-3.27.1-windows-i386\bin\cmake.exe" C:\test\ -DCMAKE_TOOLCHAIN_FILE=C:\misc\vcpkg\scripts\buildsystems\vcpkg.cmake
  ```
  It prints:
  ```
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19045.
-- The C compiler identification is MSVC 19.29.30153.0
-- The CXX compiler identification is MSVC 19.29.30153.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: C:/misc/vcpkg/installed/x64-windows/tools/pkgconf/pkgconf.exe (found version "2.1.0")
-- Checking for module 'gmpxx'
--   Package 'gmpxx', required by 'virtual:world', not found
CMake Error at C:/misc/vcpkg/downloads/tools/cmake-3.27.1-windows/cmake-3.27.1-windows-i386/share/cmake-3.27/Modules/FindPkgConfig.cmake:607 (message):
  A required package was not found
Call Stack (most recent call first):
  C:/misc/vcpkg/downloads/tools/cmake-3.27.1-windows/cmake-3.27.1-windows-i386/share/cmake-3.27/Modules/FindPkgConfig.cmake:829 (_pkg_check_modules_internal)
  CMakeLists.txt:5 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
  ```

**Comment by ivanovmp** [comment]
Strangely enough, `pkgconf.exe` seems to be unaware of any packages:
```
C:\Users\user>C:/misc/vcpkg/installed/x64-windows/tools/pkgconf/pkgconf.exe --list-all

C:\Users\user>C:/misc/vcpkg/installed/x64-windows/tools/pkgconf/pkgconf.exe --list-package-names
```
Both these commands printed nothing.

**Comment by dg0yt** [comment]
`pkgconf` depends on environment variables or options to locate available modules. CMake handles that based iff you ask for modern CMake, by `having cmake_minimum_required(VERSION 3.1)` before `project(...)`. Cf. https://cmake.org/cmake/help/latest/module/FindPkgConfig.html#command:pkg_check_modules.

vcpkg CI only tests gmp, and mpir is nearly unmaintained AFAIU.

**Comment by ivanovmp** [comment]
Should `vcpkg install gmp` work on Windows?

**Comment by dg0yt** [comment]
> Should `vcpkg install gmp` work on Windows?

Yes.

**Comment by ivanovmp** [comment]
But still, `mpir` works if, instead of CMake project, I create an ordinary C++ project in Visual Studio 2019. How is it possible that there is no existing minimum working example of `mpir` working in a CMake project?
