### ISSUE TITLE
antlr4:x64-windows version is not the same as x64-linux

### ISSUE THREAD

**Issue by snbit999** [microsoft/vcpkg#36077]
### Library name

antlr4

### New version number

4.13.1

### Other information that may be useful (release notes, etc...)

The available version for antlr4:x64-windows (4.9.1) is not the latest (from 3 years ago) and is not the same as what's available with antlr4:x64-linux (4.13.1).

Is there a plan to upgrade the windows version of antlr4 and keep it the same as what's available for linux?

Thanks
sn

**Comment by StarGate-One** [comment]
Has the local instance of vcpkg been updated lately i.e. git pull bootstrap-vcpkg etc?
I just installed antlr4 on my windows 11 system with latest vcpkg - version for port antlr4 is 4.13.1.

Computing installation plan...
The following packages will be built and installed:
    antlr4:x64-windows@4.13.1
Installing 1/1 antlr4:x64-windows@4.13.1...
Building antlr4:x64-windows@4.13.1...
-- Downloading https://github.com/antlr/antlr4/archive/4.13.1.tar.gz -> antlr-antlr4-4.13.1.tar.gz...
-- Extracting source D:/vcpkg/downloads/antlr-antlr4-4.13.1.tar.gz
-- Applying patch set-export-macro-define-as-private.patch
-- Using source at D:/vcpkg/buildtrees/antlr4/src/4.13.1-7b2cc1cb18.clean
INFOConfigure at 'D:/vcpkg/buildtrees/antlr4/src/4.13.1-7b2cc1cb18.clean/runtime/Cpp'
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/vcpkg/packages/antlr4_x64-windows/share/antlr4/copyright
-- Performing post-build validation
Elapsed time to handle antlr4:x64-windows: 1.3 min
antlr4:x64-windows package ABI: 8383eb2b707a3c60ed9314495f590a74d2d804cf34625171fc8eb4c456befa79
Total install time: 1.3 min
RESULTS
  antlr4:x64-windows: SUCCEEDED: 1.3 min

SUMMARY FOR x64-windows
  SUCCEEDED: 1

D:\vcpkg
->vcpkg list antlr4
antlr4:x64-windows                                4.13.1              ANother Tool for Language Recognition

**Comment by jimwang118** [comment]
You need to update the vcpkg library. The latest version of `antlr4` in vcpkg is 4.13.1.

**Comment by snbit999** [comment]
Thanks. Updating helped

sn
