### ISSUE TITLE
[tiff] Build error on x64-windows-static

### ISSUE THREAD

**Issue by lixin022280** [microsoft/vcpkg#36085]
error: building tiff:x64-windows-static failed with: BUILD_FAILED
Elapsed time to handle tiff:x64-windows-static: 1.5 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+tiff
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[tiff]+Build+error+on+x64-windows-static&body=Copy+issue+body+from+C%3A%2Fdev%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

can anybody help me ? thaks

**Comment by JonLiu1993** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report an issue.

**Comment by lixin022280** [comment]
below is total info in CMD window：
C:\dev\vcpkg>vcpkg install tiff:x64-windows-static
Computing installation plan...
The following packages will be built and installed:
    tiff[core,jpeg,lzma,zip]:x64-windows-static@4.6.0#2
Detecting compiler hash for triplet x64-windows-static...
Restored 0 package(s) from C:\Users\lx\AppData\Local\vcpkg\archives in 297 us. Use --debug to see more details.
Installing 1/1 tiff[core,jpeg,lzma,zip]:x64-windows-static@4.6.0#2...
Building tiff[core,jpeg,lzma,zip]:x64-windows-static@4.6.0#2...
-- Using cached libtiff-libtiff-v4.6.0.tar.gz.
-- Cleaning sources at C:/dev/vcpkg/buildtrees/tiff/src/v4.6.0-ba2cf5b685.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/libtiff-libtiff-v4.6.0.tar.gz
-- Applying patch FindCMath.patch
-- Using source at C:/dev/vcpkg/buildtrees/tiff/src/v4.6.0-ba2cf5b685.clean
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
**CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):**
    Command failed: C:/dev/vcpkg/downloads/tools/cmake-3.27.1-windows/cmake-3.27.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j3
    Working Directory: C:/dev/vcpkg/buildtrees/tiff/x64-windows-static-dbg
    See logs for more information:
      C:\dev\vcpkg\buildtrees\tiff\install-x64-windows-static-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/tiff/portfile.cmake:53 (vcpkg_cmake_install)
  scripts/ports.cmake:170 (include)



error: building tiff:x64-windows-static failed with: BUILD_FAILED
Elapsed time to handle tiff:x64-windows-static: 1.5 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+tiff
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[tiff]+Build+error+on+x64-windows-static&body=Copy+issue+body+from+C%3A%2Fdev%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by JonLiu1993** [comment]
Please provide this error log:
````
C:\dev\vcpkg\buildtrees\tiff\install-x64-windows-static-dbg-out.log
````

**Comment by lixin022280** [comment]
[install-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/13871532/install-x64-windows-static-dbg-out.log)

**Comment by JonLiu1993** [comment]
@lixin022280, I can't reproduce your error:
````
PS F:\test\vcpkg> ./vcpkg install tiff:x64-windows-static --editable
Computing installation plan...
The following packages are already installed:
    tiff[core,zip,lzma,jpeg]:x64-windows-static@4.6.0#2
tiff:x64-windows-static is already installed
Total install time: 1.15 ms
tiff is compatible with built-in CMake targets:

    find_package(TIFF REQUIRED)
    target_link_libraries(main PRIVATE TIFF::TIFF)

tiff provides pkg-config modules:

    #  Tag Image File Format (TIFF) library.
    libtiff-4
```` 
Please provide your VS configuration information.

**Comment by lixin022280** [comment]
because you  already have the package,if you remove the package, maybe the error will occur

**Comment by JonLiu1993** [comment]
> because you already have the package,if you remove the package, maybe the error will occur

I ran the command again to avoid too many logs.
````
PS F:\test\vcpkg> ./vcpkg install tiff:x64-windows-static --editable
Computing installation plan...
The following packages will be built and installed:
  * libjpeg-turbo:x64-windows-static@3.0.1
  * liblzma:x64-windows-static@5.4.4
    tiff[core,jpeg,lzma,zip]:x64-windows-static@4.6.0#2
  * zlib:x64-windows-static@1.3
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows-static...
Restored 0 package(s) from C:\Users\v-zhli17\AppData\Local\vcpkg\archives in 6.62 ms. Use --debug to see more details.
Installing 1/4 libjpeg-turbo:x64-windows-static@3.0.1...
Building libjpeg-turbo:x64-windows-static@3.0.1...
-- Using cached libjpeg-turbo-libjpeg-turbo-3.0.1.tar.gz.
-- Cleaning sources at F:/test/vcpkg/buildtrees/libjpeg-turbo/src/3.0.1-4324fbd2eb.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/test/vcpkg/downloads/libjpeg-turbo-libjpeg-turbo-3.0.1.tar.gz
-- Applying patch add-options-for-exes-docs-headers.patch
-- Applying patch workaround_cmake_system_processor.patch
-- Using source at F:/test/vcpkg/buildtrees/libjpeg-turbo/src/3.0.1-4324fbd2eb.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Fixing pkgconfig file: F:/test/vcpkg/packages/libjpeg-turbo_x64-windows-static/lib/pkgconfig/libjpeg.pc
-- Fixing pkgconfig file: F:/test/vcpkg/packages/libjpeg-turbo_x64-windows-static/lib/pkgconfig/libturbojpeg.pc
-- Using cached mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.9-3-x86_64.pkg.tar.zst.
-- Using msys root at F:/test/vcpkg/downloads/tools/msys2/023cdb3ca06f77f2
-- Fixing pkgconfig file: F:/test/vcpkg/packages/libjpeg-turbo_x64-windows-static/debug/lib/pkgconfig/libjpeg.pc
-- Fixing pkgconfig file: F:/test/vcpkg/packages/libjpeg-turbo_x64-windows-static/debug/lib/pkgconfig/libturbojpeg.pc
-- Installing: F:/test/vcpkg/packages/libjpeg-turbo_x64-windows-static/share/libjpeg-turbo/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 955 ms.
Elapsed time to handle libjpeg-turbo:x64-windows-static: 34 s
libjpeg-turbo:x64-windows-static package ABI: 01d66bde53f303757d5dbdf2ed0be099eb8062e68f74fefa5e378c6679192046
Installing 2/4 liblzma:x64-windows-static@5.4.4...
Building liblzma:x64-windows-static@5.4.4...
-- Using cached tukaani-project-xz-v5.4.4.tar.gz.
-- Cleaning sources at F:/test/vcpkg/buildtrees/liblzma/src/v5.4.4-6f848a7cca.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/test/vcpkg/downloads/tukaani-project-xz-v5.4.4.tar.gz
-- Applying patch fix_config_include.patch
-- Applying patch win_output_name.patch
-- Applying patch add_support_ios.patch
-- Applying patch build-tools.patch
-- Using source at F:/test/vcpkg/buildtrees/liblzma/src/v5.4.4-6f848a7cca.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Fixing pkgconfig file: F:/test/vcpkg/packages/liblzma_x64-windows-static/lib/pkgconfig/liblzma.pc
-- Using cached mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.9-3-x86_64.pkg.tar.zst.
-- Using msys root at F:/test/vcpkg/downloads/tools/msys2/023cdb3ca06f77f2
-- Fixing pkgconfig file: F:/test/vcpkg/packages/liblzma_x64-windows-static/debug/lib/pkgconfig/liblzma.pc
-- Installing: F:/test/vcpkg/packages/liblzma_x64-windows-static/share/liblzma/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 365 ms.
Elapsed time to handle liblzma:x64-windows-static: 21 s
liblzma:x64-windows-static package ABI: ebb43217d8aa2d40ccaabd75d9c8d72bf2261cf93c23fa57c3b9d1af1dbb79cb
Installing 3/4 zlib:x64-windows-static@1.3...
Building zlib:x64-windows-static@1.3...
-- Using cached madler-zlib-v1.3.tar.gz.
-- Cleaning sources at F:/test/vcpkg/buildtrees/zlib/src/v1.3-8825ee792f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/test/vcpkg/downloads/madler-zlib-v1.3.tar.gz
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch 0002-skip-building-examples.patch
-- Applying patch 0003-build-static-or-shared-not-both.patch
-- Applying patch 0004-android-and-mingw-fixes.patch
-- Using source at F:/test/vcpkg/buildtrees/zlib/src/v1.3-8825ee792f.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Installing: F:/test/vcpkg/packages/zlib_x64-windows-static/share/zlib/vcpkg-cmake-wrapper.cmake
-- Fixing pkgconfig file: F:/test/vcpkg/packages/zlib_x64-windows-static/lib/pkgconfig/zlib.pc
-- Using cached mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.9-3-x86_64.pkg.tar.zst.
-- Using msys root at F:/test/vcpkg/downloads/tools/msys2/023cdb3ca06f77f2
-- Fixing pkgconfig file: F:/test/vcpkg/packages/zlib_x64-windows-static/debug/lib/pkgconfig/zlib.pc
-- Installing: F:/test/vcpkg/packages/zlib_x64-windows-static/share/zlib/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 88.6 ms.
Elapsed time to handle zlib:x64-windows-static: 7.5 s
zlib:x64-windows-static package ABI: d7add9639561119bb512e9ec5235441c423453f4074c691c99984f42b19a1166
Installing 4/4 tiff[core,jpeg,lzma,zip]:x64-windows-static@4.6.0#2...
Building tiff[core,jpeg,lzma,zip]:x64-windows-static@4.6.0#2...
-- Downloading https://gitlab.com/libtiff/libtiff/-/archive/v4.6.0/libtiff-v4.6.0.tar.gz -> libtiff-libtiff-v4.6.0.tar.gz...
-- Extracting source F:/test/vcpkg/downloads/libtiff-libtiff-v4.6.0.tar.gz
-- Applying patch FindCMath.patch
-- Using source at F:/test/vcpkg/buildtrees/tiff/src/v4.6.0-ba2cf5b685
-- Found external ninja('1.11.0').
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Fixing pkgconfig file: F:/test/vcpkg/packages/tiff_x64-windows-static/lib/pkgconfig/libtiff-4.pc
-- Using cached mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.9-3-x86_64.pkg.tar.zst.
-- Using msys root at F:/test/vcpkg/downloads/tools/msys2/023cdb3ca06f77f2
-- Fixing pkgconfig file: F:/test/vcpkg/packages/tiff_x64-windows-static/debug/lib/pkgconfig/libtiff-4.pc
-- Installing: F:/test/vcpkg/packages/tiff_x64-windows-static/share/tiff/copyright
-- Performing post-build validation
Elapsed time to handle tiff:x64-windows-static: 34 s
tiff:x64-windows-static package ABI:
Total install time: 1.6 min
tiff is compatible with built-in CMake targets:

    find_package(TIFF REQUIRED)
    target_link_libraries(main PRIVATE TIFF::TIFF)

tiff provides pkg-config modules:

    #  Tag Image File Format (TIFF) library.
    libtiff-4
````

**Comment by lixin022280** [comment]
it still cant work,my envirment: cmake ver.3.28.0,powershell 7.3.10,win 10, can you tell me your enviroment? thaks a lot!

**Comment by JonLiu1993** [comment]
windows 11 
VS2022 version 17.7.7
````
vcpkg package management program version 2023-12-12-1c9ec1978a6b0c2b39c9e9554a96e3e275f7556e
````
Could I take a look at your VS configuration?
![image](https://github.com/microsoft/vcpkg/assets/63675417/b9a64208-8985-47e6-8a41-054a58f6973d)

**Comment by lixin022280** [comment]
vs config
Microsoft Visual Studio Premium 2013
Version 12.0.40629.00 Update 5
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Premium

LightSwitch for Visual Studio 2013   06191-004-0454001-02358
Microsoft LightSwitch for Visual Studio 2013

Team Explorer for Visual Studio 2013   06191-004-0454001-02358
Microsoft Team Explorer for Visual Studio 2013

Visual Basic 2013   06191-004-0454001-02358
Microsoft Visual Basic 2013

Visual C# 2013   06191-004-0454001-02358
Microsoft Visual C# 2013

Visual C++ 2013   06191-004-0454001-02358
Microsoft Visual C++ 2013

Visual F# 2013   06191-004-0454001-02358
Microsoft Visual F# 2013

Visual Studio 2013 Code Analysis Spell Checker   06191-004-0454001-02358
Microsoft® Visual Studio® 2013 Code Analysis Spell Checker

Portions of International CorrectSpell™ spelling correction system © 1993 by Lernout & Hauspie Speech Products N.V. All rights reserved.

The American Heritage® Dictionary of the English Language, Third Edition Copyright © 1992 Houghton Mifflin Company. Electronic version licensed from Lernout & Hauspie Speech Products N.V. All rights reserved.

Windows Phone SDK 8.0 - ENU   06191-004-0454001-02358
Windows Phone SDK 8.0 - ENU

ASP.NET and Web Tools   12.5.60612.0
Microsoft Web Developer Tools contains the following components:
Support for creating and opening ASP.NET web projects
Browser Link: A communication channel between Visual Studio and browsers
Editor extensions for HTML, CSS, and JavaScript
Page Inspector: Inspection tool for ASP.NET web projects
Scaffolding: A framework for building and running code generators
Server Explorer extensions for Microsoft Azure Web Apps
Web publishing: Extensions for publishing ASP.NET web projects to hosting providers, on-premises servers, or Microsoft Azure

ASP.NET Web Frameworks and Tools 2012.2   4.1.21001.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.30612.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.4
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   2.8.60610.756
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2013 ENU   12.0.30626
Microsoft Office Developer Tools for Visual Studio 2013 ENU

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Release Management for Visual Studio Package   1.0
Release Management for Visual Studio

SQL Server Data Tools   12.0.41012.0
Microsoft SQL Server Data Tools

Windows Phone 8.1 SDK Integration   1.0
This package integrates the tools for the Windows Phone 8.1 SDK into the menus and controls of Visual Studio.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

vcpkg package management program version 2023-12-12-1c9ec1978a6b0c2b39c9e9554a96e3e275f7556e

maybe I should update to VS2022?

**Comment by JonLiu1993** [comment]
Please update your VS version and try agagin.

**Comment by lixin022280** [comment]
it really works, VS2022 is key point, thanks a lot!!!
