### ISSUE TITLE
gli compilation error using glm 0.9.9.0

### ISSUE THREAD

**Issue by chubei-oppen** [Microsoft/vcpkg#3608]
glm has been updated to 0.9.9.0 in ports while gli remains 0.8.2-1, this combination won't compile.

**Comment by jasjuang** [comment]
Would be great if you can submit a PR for this!

**Comment by chubei-oppen** [comment]
Unfortunately gli doesn't have a release that supports glm 0.9.9.0. Should I revert the commit that updated glm?

**Comment by chubei-oppen** [comment]
@NancyLi1013 Installation is not the problem. We need to compile a file that includes gli to see the error. A minimum example would be:
`#define GLM_ENABLE_EXPERIMENTAL`
`#include <gli/gli.hpp>`

**Comment by LarryIII** [comment]
@chubei-oppen Thanks for your feedback. This issue was fixed in https://github.com/Microsoft/vcpkg/pull/5726
