### ISSUE TITLE
Some files installed by vcpkg_cmake_install are not included in package

### ISSUE THREAD

**Issue by justusranvier** [microsoft/vcpkg#36090]
I am trying to package a library for vcpkg which installs several extra .cmake files to the same directory as (PackageName)Config.cmake which are used by that file when a consumer calls find_package.

This works perfectly when the library is built and installed outside of vcpkg however when it is built by vcpkg these extra .cmake files do not get copied into the vcpkg/packages/ directory and thus are not available when a consuming project requires them.

This behavior doesn't seem to be documented anywhere and I can't find a way to make vcpkg package all the necessary files.

**Comment by dg0yt** [comment]
vcpkg does special cmake fixup do merge release and debug build types (so that MSVS gets multi-config). This is `vcpkg_cmake_config_fixup`, implemented in a script function in port `vcpkg-cmake-config`.
https://learn.microsoft.com/en-us/vcpkg/maintainers/functions/vcpkg_cmake_config_fixup

But there shouldn't be any lost files, unless deliberately removed by the portfile.
So you better report the port name and usage pattern which doesn't work - it is probably a port bug.

**Comment by justusranvier** [comment]
> But there shouldn't be any lost files, unless deliberately removed by the portfile.
So you better report the port name and usage pattern which doesn't work - it is probably a port bug.

I've written a portfile and I see the files get installed by vcpkg_cmake_install to vcpkg/installed, however they do not make it into vcpkg/packages.

What this means is if the package is compiled immediately before the project that depends on it then the dependent project's build will be successful, however if the package was restored from the cache then some files will be missing and the dependent project will fail.

**Comment by dg0yt** [comment]
> I've written a portfile and I see the files get installed by vcpkg_cmake_install to vcpkg/installed, however they do not make it into vcpkg/packages.

This is upside-down. The projects must install everything to `packages/<PORT>_<TRIPLET>`,  and this is where the vcpkg tool collects files for binary packages and for final installation. `vcpkg_cmake_configure` uses standard CMake variables to pass the desired location into the projects, but it has no control over what the project really does...

**Comment by justusranvier** [comment]
Ultimately the solution was to explicitly pass CMAKE_INSTALL_PREFIX and set it to `${CURRENT_PACKAGES_DIR}` for both release and debug builds.

The library already knows how to install multiple configurations and vcpkg adding the `/debug` suffix to the install prefix was just getting in the way.
