### ISSUE TITLE
[spirv-headers] Build error on x64-windows-static

### ISSUE THREAD

**Issue by Josplode** [microsoft/vcpkg#36114]
Package: spirv-headers:x64-windows-static@1.3.268.0

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.38.33134.0
-    vcpkg-tool version: 2023-12-12-1c9ec1978a6b0c2b39c9e9554a96e3e275f7556e
    vcpkg-scripts version: c9919121d 2024-01-09 (30 hours ago)

**To Reproduce**

`vcpkg install spirv-cross:x64-windows-static`
**Failure logs**

```
-- Using cached KhronosGroup-SPIRV-Headers-vulkan-sdk-1.3.268.0.tar.gz.
-- Cleaning sources at C:/Users/Joey/vcpkg/buildtrees/spirv-headers/src/-1.3.268.0-2e1dc3bb02.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Joey/vcpkg/downloads/KhronosGroup-SPIRV-Headers-vulkan-sdk-1.3.268.0.tar.gz
-- Using source at C:/Users/Joey/vcpkg/buildtrees/spirv-headers/src/-1.3.268.0-2e1dc3bb02.clean
CMake Error at ports/spirv-headers/portfile.cmake:10 (vcpkg_cmake_configure):
  Unknown CMake command "vcpkg_cmake_configure".
Call Stack (most recent call first):
  scripts/ports.cmake:170 (include)



```

Note: I have tried updating vcpkg-cmake package for x64-windows-static and everything is up to date.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please run command `.\vcpkg upgrade --no-dry-run`.

**Comment by Josplode** [comment]
> Thanks for posting this issue. Please run command `.\vcpkg upgrade --no-dry-run`.

I am using vcpkg directly checked out from git, so I get:
`All installed packages are up-to-date with the local portfile.`

**Comment by Josplode** [comment]
Alright, completely deleting and re-cloning the repo fixed my issue. I had already performed `git reset --hard` on the top of master a few times, I guess something untracked got clobbered.
