### ISSUE TITLE
[docopt] build error on arm64-osx (shared)

### ISSUE THREAD

**Issue by antoniaelsen** [microsoft/vcpkg#36117]
### Operating system

MacOS

### Compiler

Clang 14.0.3

### Steps to reproduce the behavior

```Shell
./vcpkg install docopt
cmake ... DVCPKG_TARGET_TRIPLET=<some dynamic triplet>
```

### Failure logs

```
In file included from <src>/src/main.cpp:8:
In file included from <src>/src/util/cli.h:4:
<src>/build/vcpkg_installed/arm64-osx-dynamic/include/docopt/docopt.h:70:31: error: unknown type name 'dllimport'
        std::map<std::string, value> DOCOPT_API docopt_parse(std::string const& doc,
                                     ^
<src>/build/vcpkg_installed/arm64-osx-dynamic/include/docopt/docopt.h:36:43: note: expanded from macro 'DOCOPT_API'
            #define DOCOPT_API __declspec(dllimport)
                                          ^
<src>/build/vcpkg_installed/arm64-osx-dynamic/include/docopt/docopt.h:70:42: error: expected function body after function declarator
        std::map<std::string, value> DOCOPT_API docopt_parse(std::string const& doc,
                                                ^
<src>/build/vcpkg_installed/arm64-osx-dynamic/include/docopt/docopt.h:83:31: error: unknown type name 'dllimport'
        std::map<std::string, value> DOCOPT_API docopt(std::string const& doc,
                                     ^
<src>/build/vcpkg_installed/arm64-osx-dynamic/include/docopt/docopt.h:36:43: note: expanded from macro 'DOCOPT_API'
            #define DOCOPT_API __declspec(dllimport)
                                          ^
<src>/build/vcpkg_installed/arm64-osx-dynamic/include/docopt/docopt.h:83:42: error: expected function body after function declarator
        std::map<std::string, value> DOCOPT_API docopt(std::string const& doc,
                                                ^
<src>/build/vcpkg_installed/arm64-osx-dynamic/include/docopt/docopt.h:90:15: error: unknown type name 'dllimport'
        std::ostream DOCOPT_API & operator<<(std::ostream&, value const&);
                     ^
<src>/build/vcpkg_installed/arm64-osx-dynamic/include/docopt/docopt.h:36:43: note: expanded from macro 'DOCOPT_API'
            #define DOCOPT_API __declspec(dllimport)
                                          ^
<src>/build/vcpkg_installed/arm64-osx-dynamic/include/docopt/docopt.h:90:28: error: expected function body after function declarator
        std::ostream DOCOPT_API & operator<<(std::ostream&, value const&);
                                  ^
```

### Additional context

Docopt's [source](https://github.com/docopt/docopt.cpp/blob/master/docopt.h) contains the following macro;
```
#ifdef DOCOPT_DLL
        // Whoever is *building* the DLL should define DOCOPT_EXPORTS.
        // The CMakeLists.txt that comes with docopt does this.
        // Clients of docopt.dll should NOT define DOCOPT_EXPORTS.
        #ifdef DOCOPT_EXPORTS
            #define DOCOPT_API __declspec(dllexport)
        #else
            #define DOCOPT_API __declspec(dllimport)
        #endif
    #else
        #define DOCOPT_API
    #endif
#endif
```

AFAIK dllimport / dllexport are only supported by the microsoft compiler / linker, and this will break builds using other compilers.

The [docopt portfile](https://github.com/microsoft/vcpkg/blob/master/ports/docopt/portfile.cmake) replaces `#ifdef DOCOPT_DLL` with `#ifdef 1`, so the MS-specific macro will always be defined, and the port will break dynamic builds on non-windows systems.

As I understand it, dllimport is not strictly required in a shared build -- a quick fix would be to omit it, or have the replacement be contingent on the use of the VS generator. Happy to submit a PR if that sounds good.

**Comment by KUGA2** [comment]
The usual solution is solution to use `#ifdef _WIN32`. See https://cmake.org/cmake/help/latest/guide/tutorial/Selecting%20Static%20or%20Shared%20Libraries.html

So we (vcpkg) would need to:
A) do not change header
  - and set DOCOPT_DLL via patched docopt-targets/config.cmake
  - or set DOCOPT_DLL manually
B) change the header to _WIN32

Or an upstream change of the header to _WIN32 and remove the patch from 'our' port

Optional fix: Note that `docopt_EXPORTS` (not `DOCOPT_EXPORTS` [defined here](https://github.com/docopt/docopt.cpp/blob/400e6dd8e59196c914dcc2c56caf7dae7efa5eb3/CMakeLists.txt#L51C1-L51C62)) would be automatically defined: https://cmake.org/cmake/help/latest/prop_tgt/DEFINE_SYMBOL.html

Workaround: Set DOCOPT_HEADER_ONLY in your target. But compiling takes fairly long.
