### ISSUE TITLE
lodepng build failed

### ISSUE THREAD

**Issue by sbruckner** [Microsoft/vcpkg#3612]
Error: Building package lodepng:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:

  Package: lodepng:x64-windows
  Vcpkg version: 0.0.113-nohash

From the logfile:

pngdetail.cpp.obj : error LNK2001: unresolved external symbol "char const * const LODEPNG_VERSION_STRING" (?LODEPNG_VERSION_STRING@@3PEBDEB)
pngdetail.exe : fatal error LNK1120: 1 unresolved externals
ninja: build stopped: subcommand failed.

**Comment by kiwixz** [comment]
Still here, looks like MSVC expecting `char const * const` when type is actually `const char *`.

**Comment by NancyLi1013** [comment]
The PR  merged. So I close it.
