### ISSUE TITLE
[dcmtk] update to 3.6.8

### ISSUE THREAD

**Issue by kevle** [microsoft/vcpkg#36121]
### Library name

dcmtk

### New version number

3.6.8

### Other information that may be useful (release notes, etc...)

Library name: DCMTK
New version number: 3.6.8

I have started work on this, and it looks promising so far.

"windows-patch.patch" will be obsoleted thanks to improvements upstream.

Relevant excerpts from the ANNOUNCE file:

```
- CMake-related enhancements and other changes:

  - Fix detection and enabling of modern C++ versions (C++11 and later) for VS.
    Mainly, it is ensured that the __cplusplus version macro is set accordingly
    when using VS while enabling C++11 or later.
```

```
# Advanced user (eg. vcpkg) may want to override this:
if(NOT DEFINED DCMTK_USE_FIND_PACKAGE_WIN_DEFAULT)
  set(DCMTK_USE_FIND_PACKAGE_WIN_DEFAULT FALSE)
endif()
```

I still have to check some stuff, e.g. there also appears to be upstream changes w.r.t. libxml2 handling:

```
- Fixed bug in libxml2 detection.
  Affects: CMake/3rdparty.cmake
```

The update also potentially resolves #31395 .

**Comment by terewenko** [comment]
MAYBE_UNUSED_VARIABLES
        -DDCMTK_USE_FIND_PACKAGE_WIN_DEFAULT=ON
These flag is ignored. 

vcpkg package management program version 2024-02-07-8a83681f921b10d86ae626fd833c253f4f8c355b
Windows 10 x64

**Comment by dg0yt** [comment]
> ```
> MAYBE_UNUSED_VARIABLES
>     -DDCMTK_USE_FIND_PACKAGE_WIN_DEFAULT=ON
> ```
> 
> These flag is ignored.

It is for variable names (`DCMTK_USE_FIND_PACKAGE_WIN_DEFAULT`), not for options.

**Comment by terewenko** [comment]
Yes, DCMTK_USE_FIND_PACKAGE_WIN_DEFAULT is ignored. 
config-x64-windows-static-dbg-CMakeCache.txt.log/config-x64-windows-static-rel-CMakeCache.txt.log do not contain this variable.
If move DCMTK_USE_FIND_PACKAGE_WIN_DEFAULT  from MAYBE_UNUSED_VARIABLES to  OPTIONS - all good
[config-x64-windows-static-out.log](https://github.com/microsoft/vcpkg/files/15002047/config-x64-windows-static-out.log)

> [1/2] "D:/src/repo/vcpkg_newest/downloads/tools/cmake-3.29.0-windows/cmake-3.29.0-windows-i386/bin/cmake.exe" -E chdir ".." "D:/src/repo/vcpkg_newest/downloads/tools/cmake-3.29.0-windows/cmake-3.29.0-windows-i386/bin/cmake.exe" "D:/src/repo/vcpkg_newest/buildtrees/dcmtk/src/6327500740-27c71348c6.clean" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=D:/src/repo/vcpkg_newest/packages/dcmtk_x64-windows-static" "-DFETCHCONTENT_FULLY_DISCONNECTED=ON" "-DDCMTK_WITH_ICONV=OFF" "-DDCMTK_WITH_ICU=OFF" "-DDCMTK_WITH_OPENSSL=ON" "-DDCMTK_WITH_PNG=OFF" "-DDCMTK_WITH_TIFF=OFF" "-DDCMTK_WITH_XML=OFF" "-DDCMTK_WITH_ZLIB=ON" "-DBUILD_APPS=OFF" "-DDCMTK_DEFAULT_DICT=builtin" "-DDCMTK_WITH_DOXYGEN=OFF" "-DDCMTK_FORCE_FPIC_ON_UNIX=ON" "-DDCMTK_OVERWRITE_WIN32_COMPILER_FLAGS=OFF" "-DDCMTK_ENABLE_PRIVATE_TAGS=ON" "-DCMAKE_CXX_STANDARD=17" "-DDCMTK_WIDE_CHAR_FILE_IO_FUNCTIONS=ON" "-DDCMTK_WIDE_CHAR_MAIN_FUNCTION=ON" "-DDCMTK_ENABLE_STL=ON" "-DCMAKE_DEBUG_POSTFIX=d" "-DCMAKE_MAKE_PROGRAM=D:/src/repo/vcpkg_newest/downloads/tools/ninja/1.10.2-windows/ninja.exe" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/src/repo/vcpkg_newest/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows-static" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v143" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=D:/src/repo/vcpkg_newest/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=static" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=D:/src/repo/vcpkg_newest" "-D_VCPKG_INSTALLED_DIR=D:/src/repo/vcpkg_newest/installed" "-DVCPKG_MANIFEST_INSTALL=OFF"

...
> -- Warning: OPENSSL support will be disabled because openssl directory was not specified. Correct path and re-enable DCMTK_WITH_OPENSSL.
> -- Warning: ZLIB support will be disabled because zlib directory was not specified. Correct path and re-enable DCMTK_WITH_ZLIB.
> -- Warning: SNDFILE support will be disabled because libsndfile directory was not specified. Correct path and re-enable DCMTK_WITH_SNDFILE.
> -- Warning: OpenJPEG support will be disabled because openjpeg directory was not specified. Correct path and re-enable DCMTK_WITH_OPENJPEG.
