### ISSUE TITLE
[zstd] all versions after 1.2.0, zstd.h is modified incorrectly

### ISSUE THREAD

**Issue by zhangyiatmicrosoft** [microsoft/vcpkg#36131]
### Is your feature request related to a problem? Please describe.

Original line is here:
https://github.com/facebook/zstd/blob/ffde100b68bcfa76bc62e3ac7421068dba927f0e/lib/zstd.h#L44C1-L44C1

VCPKG modified it and `became:
```
#elif 1
```
This looks like a mistake in that the "else" condition would never hit.

As result when we compile zstd in Windows, Android SDK, arm64, , which does not support __declspec, and always produces an error:
**__declspec attribute 'dllimport' is not supported**

### Proposed solution

This line replaced the original condition with "1":
https://github.com/microsoft/vcpkg/blob/83444c57754d01d584a4a371a070c5147e8a5aae/ports/zstd/portfile.cmake#L53C9-L53C9

The PR that introduced this change:
https://github.com/microsoft/vcpkg/pull/1032

No additional context was in the above PR and the end result does not look logical. Please remove replacement and keep the original condition untouched.

### Describe alternatives you've considered

N/A, there is no workaround

**Comment by dg0yt** [comment]
There is no port bug: The replacement is done only for Windows targets:
https://github.com/microsoft/vcpkg/blob/83444c57754d01d584a4a371a070c5147e8a5aae/ports/zstd/portfile.cmake#L51-L55

**Comment by zhangyiatmicrosoft** [comment]
> There is no port bug: The replacement is done only for Windows targets:
> 
> https://github.com/microsoft/vcpkg/blob/83444c57754d01d584a4a371a070c5147e8a5aae/ports/zstd/portfile.cmake#L51-L55

My dev environment is indeed Windows, with VS2022 + Android Studio (NDK), whose clang does not support __declspec , how do I make this work?

In the end, isn't the original condition more solid and reliable for everyone?

**Comment by Osyotr** [comment]
> In the end, isn't the original condition more solid and reliable for everyone? I am not understanding the reason behind the change to wipe it out...

What's your host compiler? The replacement is done only for Windows targets, so you're probably looking at wrong include (i.e. host instead of target).
The reason behind the replacement is to prevent errors when users forget to pass `-DZSTD_DLL_IMPORT=1` when using shared zstd and when they do pass `-dZSTD_DLL_IMPORT=1` when using static zstd.

**Comment by zhangyiatmicrosoft** [comment]
Turned out it picked up the wrong triplet .. so that worked for me.

Final thoughts though, I see removing the condition is to help certain scenarios, but feel it is somewhat unexpected when the header file in vcpkg deviates from the original zstd repo.
