### ISSUE TITLE
[eastl] find_package(EASTL) fails

### ISSUE THREAD

**Issue by vikhik** [microsoft/vcpkg#36154]
**Setup**
![image](https://github.com/microsoft/vcpkg/assets/1762365/9d066eea-1ba2-47a2-9fdb-c02135d28b2b)

**Repro:**
1. Setup up the bare minimal repro as per the image
2. vcpkg install (installs EASTL correctly)
![image](https://github.com/microsoft/vcpkg/assets/1762365/1cc5afb3-2ec7-433c-9e92-ecbad5b8da0c)

3. run cmake configure (mkdir build, cd build, cmake ../)
4. Get error:
```CMake Error at CMakeLists.txt:7 (find_package):
  Could not find a package configuration file provided by "EASTL" with any of
  the following names:

    EASTLConfig.cmake
    eastl-config.cmake

  Add the installation prefix of "EASTL" to CMAKE_PREFIX_PATH or set
  "EASTL_DIR" to a directory containing one of the above files.  If "EASTL"
  provides a separate development package or SDK, be sure it has been
  installed.```
  
**Expected Behaviour**
The above minimal steps should be sufficient to start adding EASTL to my (brand new, blank) project.

**Comment by vikhik** [comment]
Same issue as #5552 ~4 years ago, however submitted it anew rather than rezzing that one.

**Comment by Osyotr** [comment]
> 2. vcpkg install (installs EASTL correctly)

You shouldn't call this command manually. I suspect you don't even use cmake integration https://github.com/microsoft/vcpkg/#using-vcpkg-with-cmake

**Comment by vikhik** [comment]
Instead of manually installing, using `"CMAKE_TOOLCHAIN_FILE": "$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"` in a preset _does_ work.

**Comment by vikhik** [comment]
Instead of manually installing, using `"CMAKE_TOOLCHAIN_FILE": "$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"` in a preset _does_ work.

**Comment by dg0yt** [comment]
Note that a plain `vcpkg install` knows nothing about your CMake binary dir or the vcpkg target triplet chosen in CMake.
