### ISSUE TITLE
[open-vino] build failure windows 11 x64

### ISSUE THREAD

**Issue by yonisoft** [microsoft/vcpkg#36165]
### Operating system

Windows 11 22621

### Compiler

vcpkg and cmake

### Steps to reproduce the behavior

```Shell
vcpkg install openvino
```

### Failure logs

My output dbg-out:
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/13931806/install-x64-windows-dbg-out.log)

### Additional context

D:\vcpkg>vcpkg install openvino
warning: In the September 2023 release, the default triplet for vcpkg libraries changed from x86-windows to the detected host triplet (x64-windows). For the old behavior, add --triplet x86-windows . To suppress this message, add --triplet x64-windows .
Computing installation plan...
The following packages will be built and installed:
    openvino[auto,auto-batch,core,cpu,gpu,hetero,ir,onnx,paddle,pytorch,tensorflow,tensorflow-lite]:x64-windows@2023.2.0
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\yoni1\AppData\Local\vcpkg\archives in 61.9 us. Use --debug to see more details.
Installing 1/1 openvino[auto,auto-batch,core,cpu,gpu,hetero,ir,onnx,paddle,pytorch,tensorflow,tensorflow-lite]:x64-windows@2023.2.0...
Building openvino[auto,auto-batch,core,cpu,gpu,hetero,ir,onnx,paddle,pytorch,tensorflow,tensorflow-lite]:x64-windows@2023.2.0...
-- Using cached openvinotoolkit-openvino-2023.2.0.tar.gz.
-- Cleaning sources at D:/vcpkg/buildtrees/openvino/src/2023.2.0-d1a6568411.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/openvinotoolkit-openvino-2023.2.0.tar.gz
-- Applying patch 001-disable-tools.patch
-- Applying patch 002-git-version.patch
-- Using source at D:/vcpkg/buildtrees/openvino/src/2023.2.0-d1a6568411.clean
-- Using cached oneapi-src-oneDNN-284ad4574939fa784e4ddaa1f4aa577b8eb7a017.tar.gz.
-- Cleaning sources at D:/vcpkg/buildtrees/openvino/src/7b8eb7a017-ed1cc786c9.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/oneapi-src-oneDNN-284ad4574939fa784e4ddaa1f4aa577b8eb7a017.tar.gz
-- Applying patch 006-onednn-gpu-build.patch
-- Using source at D:/vcpkg/buildtrees/openvino/src/7b8eb7a017-ed1cc786c9.clean
-- Using cached openvinotoolkit-oneDNN-2ead5d4fe5993a797d9a7a4b8b5557b96f6ec90e.tar.gz.
-- Cleaning sources at D:/vcpkg/buildtrees/openvino/src/b96f6ec90e-84ad0cd873.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/openvinotoolkit-oneDNN-2ead5d4fe5993a797d9a7a4b8b5557b96f6ec90e.tar.gz
-- Using source at D:/vcpkg/buildtrees/openvino/src/b96f6ec90e-84ad0cd873.clean
-- Using cached openvinotoolkit-mlas-f6425b1394334822390fcd9da12788c9cd0d11da.tar.gz.
-- Cleaning sources at D:/vcpkg/buildtrees/openvino/src/c9cd0d11da-e7c17351a6.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/openvinotoolkit-mlas-f6425b1394334822390fcd9da12788c9cd0d11da.tar.gz
-- Using source at D:/vcpkg/buildtrees/openvino/src/c9cd0d11da-e7c17351a6.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j33
    Working Directory: D:/vcpkg/buildtrees/openvino/x64-windows-dbg
    See logs for more information:
      D:\vcpkg\buildtrees\openvino\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/openvino/portfile.cmake:124 (vcpkg_cmake_install)
  scripts/ports.cmake:170 (include)

error: building openvino:x64-windows failed with: BUILD_FAILED
Elapsed time to handle openvino:x64-windows: 2.8 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openvino
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[openvino]+Build+error+on+x64-windows&body=Copy+issue+body+from+D%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by ilya-lavrenov** [comment]
```
D:\vcpkg\buildtrees\openvino\src\2023.2.0-d1a6568411.clean\src\plugins\intel_cpu\thirdparty\onednn\src\cpu\x64\jit_brgemm_conv.cpp
src\plugins\intel_cpu\thirdparty\onednn\src\cpu\x64\jit_brgemm_conv.cpp(1707) : fatal error C1001: Internal compiler error.
(compiler file 'D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 234)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com 
Please choose the Technical Support command on the Visual C++ 
 Help menu, or open the Technical Support help file for more information
```
I wonder what is `D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c` ?

**Comment by yonisoft** [comment]
> ```
> D:\vcpkg\buildtrees\openvino\src\2023.2.0-d1a6568411.clean\src\plugins\intel_cpu\thirdparty\onednn\src\cpu\x64\jit_brgemm_conv.cpp
> src\plugins\intel_cpu\thirdparty\onednn\src\cpu\x64\jit_brgemm_conv.cpp(1707) : fatal error C1001: Internal compiler error.
> (compiler file 'D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 234)
>  To work around this problem, try simplifying or changing the program near the locations listed above.
> If possible please provide a repro here: https://developercommunity.visualstudio.com 
> Please choose the Technical Support command on the Visual C++ 
>  Help menu, or open the Technical Support help file for more information
> ```
> 
> I wonder what is `D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c` ?

I don't know too, i don't have this path on my pc, i just run vcpkg to install openvino, nothing than that

**Comment by jimwang118** [comment]
Sorry, I cannot reproduce this problem locally. Looking at the error messages in the log, there may be a problem with your local VS compiler.
![image](https://github.com/microsoft/vcpkg/assets/122244446/4552f6d8-cd22-4229-91e5-6a8764e31e22)

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
