### ISSUE TITLE
[libiconv] Build error on x64-windows

### ISSUE THREAD

**Issue by pattyl11** [microsoft/vcpkg#36164]
Copy issue body from C:/src/vcpkg/installed/vcpkg/issue_body.md - file exceeds max char limit - attaching instead. 
[issue_body.md](https://github.com/microsoft/vcpkg/files/13930533/issue_body.md)
[config-x64-windows-dbg-config.log](https://github.com/microsoft/vcpkg/files/13930538/config-x64-windows-dbg-config.log)
[config-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/13930539/config-x64-windows-dbg-err.log)
[config-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/13930540/config-x64-windows-dbg-out.log)

**Comment by pattyl11** [comment]
error: building libiconv:x64-windows failed with: BUILD_FAILED
Elapsed time to handle libiconv:x64-windows: 1.3 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libiconv
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[libiconv]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2Fsrc%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md


c:\src\vcpkg>vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

**Comment by pattyl11** [comment]
I removed libiconv-1.17.tar.gz from C:\src\vcpkg\downloads and rebuilt using vcpkg install fltk  --triplet x86-windows and it still failed. 
[config-x64-windows-dbg-config.log](https://github.com/microsoft/vcpkg/files/13930554/config-x64-windows-dbg-config.log)
[config-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/13930555/config-x64-windows-dbg-err.log)
[config-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/13930556/config-x64-windows-dbg-out.log)
[error-logs-x64-windows.txt](https://github.com/microsoft/vcpkg/files/13930557/error-logs-x64-windows.txt)
[get-cmake-vars-x64-windows-err.log](https://github.com/microsoft/vcpkg/files/13930558/get-cmake-vars-x64-windows-err.log)
[get-cmake-vars-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/13930559/get-cmake-vars-x64-windows-out.log)
[issue_body.md](https://github.com/microsoft/vcpkg/files/13930561/issue_body.md)

**Comment by FrankXie05** [comment]
See https://github.com/microsoft/vcpkg/issues/21901

**Comment by pattyl11** [comment]
It looks like Windows Security is blocking my build so I used this article to exempt my source code:
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-deployment-implement?view=o365-worldwide#customize-attack-surface-reduction-rules

**Comment by pattyl11** [comment]
It looks like Windows Security is blocking my build so I used this article to exempt my source code:
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-deployment-implement?view=o365-worldwide#customize-attack-surface-reduction-rules

**Comment by pattyl11** [comment]
It looks like Windows Security is blocking my build so I used this article to exempt my source code path using this article:
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-deployment-implement?view=o365-worldwide#customize-attack-surface-reduction-rules

**Comment by pattyl11** [comment]
It looks like Windows Security is blocking my build so I used this article to exempt my source code path using this article:
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-deployment-implement?view=o365-worldwide#customize-attack-surface-reduction-rules

**Comment by FrankXie05** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can ping me with more info and I will reopen.

**Comment by pattyl11** [comment]
I found a workaround, not sure if this was the only issue, but yes, fine to close.
