### ISSUE TITLE
error: building openssl:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Escavine** [microsoft/vcpkg#36161]
### Operating system

Windows 10

### Compiler

MinGW

### Steps to reproduce the behavior

```Shell
.\vcpkg install openssl
```

### Failure logs

error: building openssl:x64-windows failed with: BUILD_FAILED
Elapsed time to handle openssl:x64-windows: 2.5 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[openssl]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2FUsers%2FKhalid%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by StarGate-One** [comment]
See issue #30604 on how to report a build failure.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
