### ISSUE TITLE
package `sdl-image` is broken

### ISSUE THREAD

**Issue by ryancheung** [microsoft/vcpkg#3617]
I printed the symbols of libSDL2_image.a using nm command in macOS.

`nm -a /Users/Ryan/vcpkg/installed/x64-osx/lib/libSDL2_image.a | less`:

```
/Users/Ryan/vcpkg/installed/x64-osx/lib/libSDL2_image.a(IMG_jpg.c.o):
0000000000000000 T _IMG_SaveJPG
0000000000000040 T _IMG_SaveJPG_RW
                 U _SDL_RWFromFile
                 U _SDL_SetError
```
There's no `IMG_InitJPG` symbol, which means JPEG support was not integrated correctly.

This is the homebrew build script:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/sdl2_image.rb

**Comment by ryancheung** [comment]
#3432

**Comment by cbezault** [comment]
This should be resolved, let us know if it isn't.
