### ISSUE TITLE
[boost-thread] Build error on x64-osx

### ISSUE THREAD

**Issue by sujitbhogil00603** [microsoft/vcpkg#36178]
Copy issue body from /Users/sujitbhogil/Desktop/c_api/vcpkg/installed/vcpkg/issue_body.md 
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
      

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/boost-thread/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:170 (include)

**Comment by JonLiu1993** [comment]
@sujitbhogil00603, Sorry I didn't repro your issue. please make sure your network is smooth and the proxy is available.
````
Elapsed time to handle boost-thread:x64-osx: 7.9 s
boost-thread:x64-osx package ABI:
Total install time: 43 s
The package boost is compatible with built-in CMake targets:

    find_package(Boost REQUIRED [COMPONENTS <libs>...])
    target_link_libraries(main PRIVATE Boost::boost Boost::<lib1> Boost::<lib2> ...)

````

**Comment by JonLiu1993** [comment]
Ping @sujitbhogil00603 for response, does this issue still exist?

**Comment by JonLiu1993** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
