### ISSUE TITLE
[opencv3] build failure

### ISSUE THREAD

**Issue by EthanSun11** [microsoft/vcpkg#36197]
### Operating system

x64-linux

### Steps to reproduce the behavior

```Shell
`vcpkg install opencv3`
```

### Failure logs

[issue_body.md](https://github.com/microsoft/vcpkg/files/13948824/issue_body.md)

**Comment by FrankXie05** [comment]
```
../src/glib-2-7cc53588e0.clean/meson.build:2330:0: ERROR: <PythonExternalProgram 'python' -> ['/usr/bin/python3']> is not a valid python or it is missing distutils
```
You need install python3 and may also need `python3-distutils`.

**Comment by EthanSun11** [comment]
> ```
> ../src/glib-2-7cc53588e0.clean/meson.build:2330:0: ERROR: <PythonExternalProgram 'python' -> ['/usr/bin/python3']> is not a valid python or it is missing distutils
> ```
> 
> You need install python3 and may also need `python3-distutils`.

I have installed package `python3-distutils`. And this the new error log file.
[issue_body.md](https://github.com/microsoft/vcpkg/files/13965758/issue_body.md)

**Comment by FrankXie05** [comment]
```
ERROR: Dependency "xrandr" not found, tried pkgconfig and cmake
```
Try run `sudo apt install libxrandr-dev`. :)

**Comment by EthanSun11** [comment]
Thank you for your help and quick response. The question is solved now. I installed several additional packages to support the opencv3 installation in the same way after installing that package based on your reply. In my case, for a new ubuntu20.04 system, the following packages needs to be installed before installing opencv3 using Vcpkg:
sudo apt-get install python3-distutils
sudo apt install libxrandr-dev
sudo apt-get install -y libxi-dev
sudo apt install libxcursor-dev
sudo apt-get install -y libxdamage-dev
sudo apt-get install -y libxinerama-dev
