### ISSUE TITLE
Cannot download 7zip, please use the gihub URLs instead

### ISSUE THREAD

**Issue by skonstant** [microsoft/vcpkg#36214]
My organization for some reason blocks the 7zip.org website, this makes all our builds fail. 7zip seems to be required for many packages to build.

**Environment**
- Windows

**To Reproduce**
1. ./vcpkg fetch 7zip
2. download failed

**Additional context**
7zip.org is blocked but github is never blocked. Since github has the 7zip code in https://github.com/ip7z/7zip/ could we change the urls that fetch the executable and source to point to github instead? It's a much more reliable service

I attach a patch
[get_7zip_from_GitHub.patch](https://github.com/microsoft/vcpkg/files/13961029/get_7zip_from_GitHub.patch)

**Comment by MaxRev-Dev** [comment]
+ 1, I had the same issue until I changed DNS - https://github.com/microsoft/vcpkg/issues/26844#issuecomment-1867676768.
Would be nice to replace it with github URL
