### ISSUE TITLE
[ceres] Build error on x64-windows

### ISSUE THREAD

**Issue by shangle-web** [microsoft/vcpkg#36217]
Copy issue body from D:/vcpkg/installed/vcpkg/issue_body.md

**Comment by LilyWangLL** [comment]
Please see issue https://github.com/microsoft/vcpkg/issues/30604 on how to report a build failure.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
