### ISSUE TITLE
libxlsxwriter build failure

### ISSUE THREAD

**Issue by mobileFX** [microsoft/vcpkg#36213]
### Operating system

Windows 11

### Compiler

MSVC / Visual Studio 2022 Community

### Steps to reproduce the behavior

```Shell
In MFC C++ project I am using this manifest:

{
  "name": "rgs-workbench",
  "version-string": "1.0.0.0",
  "dependencies": [
    {
      "name": "openssl",
      "version>=": "3.0.7#2"
    },
    {
      "name": "libssh2",
      "version>=": "1.10.0#4"
    },
    {
      "name": "boost-beast",
      "version>=": "1.78.0"
    },
    {
      "name": "boost-asio",
      "version>=": "1.78.0"
    },
    {
      "name": "boost-process",
      "version>=": "1.78.0"
    },
    {
      "name": "boost-filesystem",
      "version>=": "1.78.0"
    },
    {
      "name": "boost-locale",
      "version>=": "1.78.0"
    },
    {
      "name": "boost-regex",
      "version>=": "1.78.0"
    },
    {
      "name": "boost-algorithm",
      "version>=": "1.78.0"
    },
    {
      "name": "boost-format",
      "version>=": "1.78.0"
    },
    {
      "name": "boost-multiprecision",
      "version>=": "1.78.0"
    },
    {
      "name": "boost-crc",
      "version>=": "1.78.0"
    },
    {
      "name": "boost-uuid",
      "version>=": "1.78.0"
    },
    {
      "name": "boost-iostreams",
      "version>=": "1.78.0"
    },
    {
      "name": "boost-interprocess",
      "version>=": "1.78.0"
    },
    {
      "name": "boost-date-time",
      "version>=": "1.78.0"
    },
    {
      "name": "zlib",
      "version>=": "1.2.12#1"
    },
    {
      "name": "bzip2",
      "version>=": "1.0.8#2"
    },
    {
      "name": "libxlsxwriter",
      "version>=": "1.1.4"
    },
    {
      "name": "mongo-cxx-driver",
      "version>=": "3.6.5"
    },
    {
      "name": "libmariadb",
      "version>=": "3.1.15"
    },
    {
      "name": "hunspell",
      "version>=": "1.7.1#2"
    }
  ],
  "builtin-baseline": "062f92c92e0e8017929ea7647819036d8daef638"
}
```

### Failure logs

C:\Users\Administrator>"E:\dev\vcpkg\vcpkg.exe" install "--host-triplet=x64-windows-static" --x-wait-for-lock --triplet "x64-windows-static" --vcpkg-root "E:\dev\vcpkg\\" "--x-manifest-root=D:\mobileFX\Projects\Software\CasinoX\RGS\Workbench\\" "--x-install-root=D:\mobileFX\Projects\Software\CasinoX\RGS\Workbench\vcpkg_installed\x64-windows-static\\"
Detecting compiler hash for triplet x64-windows-static...
The following packages will be built and installed:
  * libbson[core]:x64-windows-static -> 1.17.6#1 -- E:\dev\vcpkg\buildtrees\versioning_\versions\libbson\6ad46cf0f2a10843d03cfd2e0388527561f9e2f0
    libxlsxwriter[core]:x64-windows-static -> 1.1.4 -- E:\dev\vcpkg\buildtrees\versioning_\versions\libxlsxwriter\9e7e4072f13a2839135caf76e0b0ef31ee13bc48
  * mongo-c-driver[core]:x64-windows-static -> 1.17.6#2 -- E:\dev\vcpkg\buildtrees\versioning_\versions\mongo-c-driver\0579545ecddc3bef7941e3caa19bda27c80323bc
    mongo-cxx-driver[core]:x64-windows-static -> 3.6.5#3 -- E:\dev\vcpkg\buildtrees\versioning_\versions\mongo-cxx-driver\732830e44f7d4c9c31025d6c77e7d40220abef38
Additional packages (*) will be modified to complete this operation.
Installing 1/4 libxlsxwriter:x64-windows-static...
Building libxlsxwriter[core]:x64-windows-static...
-- Installing port from location: E:\dev\vcpkg\buildtrees\versioning_\versions\libxlsxwriter\9e7e4072f13a2839135caf76e0b0ef31ee13bc48
-- Using cached jmcnamara-libxlsxwriter-RELEASE_1.1.4.tar.gz.
-- Cleaning sources at E:/dev/vcpkg/buildtrees/libxlsxwriter/src/EASE_1.1.4-a376102254.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/dev/vcpkg/downloads/jmcnamara-libxlsxwriter-RELEASE_1.1.4.tar.gz
-- Using source at E:/dev/vcpkg/buildtrees/libxlsxwriter/src/EASE_1.1.4-a376102254.clean
-- Configuring x64-windows-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: E:/dev/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe -v
    Working Directory: E:/dev/vcpkg/buildtrees/libxlsxwriter/x64-windows-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      E:\dev\vcpkg\buildtrees\libxlsxwriter\config-x64-windows-static-out.log

Call Stack (most recent call first):
  D:/mobileFX/Projects/Software/CasinoX/RGS/Workbench/vcpkg_installed/x64-windows-static/x64-windows-static/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:238 (vcpkg_execute_required_process)
  buildtrees/versioning_/versions/libxlsxwriter/9e7e4072f13a2839135caf76e0b0ef31ee13bc48/portfile.cmake:15 (vcpkg_cmake_configure)
  scripts/ports.cmake:170 (include)

error: building libxlsxwriter:x64-windows-static failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libxlsxwriter
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libxlsxwriter]+Build+error
Include '[libxlsxwriter] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454
    vcpkg-scripts version: 91b17dd72 2024-01-16 (5 hours ago)

Please use the prefilled template from D:\mobileFX\Projects\Software\CasinoX\RGS\Workbench\vcpkg_installed\x64-windows-static\vcpkg\issue_body.md when reporting your issue.

[config-x64-windows-static-out.log](https://github.com/microsoft/vcpkg/files/13960857/config-x64-windows-static-out.log)
[error-logs-x64-windows-static.txt](https://github.com/microsoft/vcpkg/files/13960858/error-logs-x64-windows-static.txt)
[config-x64-windows-static-err.log](https://github.com/microsoft/vcpkg/files/13960859/config-x64-windows-static-err.log)

### Additional context

It appears that ZLib version is causing an error:

CMake Error at C:/Program Files/CMake/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find ZLIB (missing: 1.0) (found version "1.2.12")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.28/Modules/FindZLIB.cmake:199 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  D:/mobileFX/Projects/Software/CasinoX/RGS/Workbench/vcpkg_installed/x64-windows-static/x64-windows-static/share/zlib/vcpkg-cmake-wrapper.cmake:12 (_find_package)
  E:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:813 (include)
  CMakeLists.txt:219 (find_package)

**Comment by JonLiu1993** [comment]
@mobileFX, This error have fixed by PR https://github.com/microsoft/vcpkg/issues/31994.
