### ISSUE TITLE
Active automatically for all Solutions in MS Visual Studio 2022

### ISSUE THREAD

**Issue by CplusplusB** [microsoft/vcpkg#36219]
**Describe the bug**
When I install vcpkg, every solution of an MS Visual Studio 2022 project vcpkg is automatically active. In the solution file the entry for vcpkg is empty. This is a major bug, as it is configured defaulty it will sneek into every solution, leading in my project to issues with for example self compiled dll's.

**Environment**
- OS: Windows 10 newest Version
- Compiler: c++ on ms visual studio 2022, but not related to compiler

**To Reproduce**
install vcpkg as described in the standard configuration on a windows 10 machine with ms visual studio 2022

**Expected behavior**
I expect, that no entry of vcpkg in ms visual studio solution file leads to vcpkg is not activated, and not by default is active.

**Failure logs**
none

**Additional context**

**Comment by StarGate-One** [comment]
- If you are using vcpkg in classic mode from the CLI
  1. Do not do a `vcpkg integrate install`
  2. Instead fo a `vcpkg integrate project` in each project's root directory to integrate vcpkg into only that project

- If you are using vcpkg as installed with VS 2022
  1. Open each solution's properties page and turn vcpkg off  (**Figure 1**) -or-
  2. Open VS 2022's configuration page and uncheck vcpkg for all projects (**Figure 2**) -or-
  3. Open VS 2022's installed and uncheck vcpkg to remove vcpkg altogether from VS 2022 (**Figure 3**) and clone vcpkg from [here](https://github.com/microsoft/vcpkg) and use vcpkg in classic mode as stated above
  
**Figure 1:**
![image](https://github.com/microsoft/vcpkg/assets/68293825/331ed408-2068-4c50-8d1d-682ec5b53ba4)

**Figure 2:**
![image](https://github.com/microsoft/vcpkg/assets/68293825/b78aa80a-aa91-445e-9d48-e3c540282691)

**Figure 3:**
![image](https://github.com/microsoft/vcpkg/assets/68293825/01b82d92-7111-4dc4-93a5-7a436ab3933d)

**Comment by CplusplusB** [comment]
> * If you are using vcpkg in classic mode from the CLI
>       
>       1. Do not do a `vcpkg integrate install`
>       2. Do `vcpkg integrate remove` if a `vcpkg integrate install` has been done then
>       3. Instead do a `vcpkg integrate project` in each project's root directory to integrate vcpkg into only that project
> 

Thank you for the clarification. In wanted to integrate vcpkg into my ms visual studio, but as mentioned above, not for all solutions I already have and not using vcpkg.
Of course I can deactivate vcpkg by going through each solution, but the better approach would be to deactivate option, as mentioned from you in Figure 2 and if the solution has no entry of vcpkg it is deactivated.

OR

you add to the Getting started under:
> In order to use vcpkg with Visual Studio, run the following command (may require administrator elevation):

>> .\vcpkg\vcpkg integrate install

a hint or extra Text like "If you do this, vcpkg is automatically activated in each solutions you already have and can mess up with your work" or a less passive agressive text ;-)

**Comment by FrankXie05** [comment]
This issue hasn’t been updated for a long time; if it is still an issue, please ping me and I will reopen this issue.
