### ISSUE TITLE
[New Port Request] SWIG

### ISSUE THREAD

**Issue by cbentejac** [microsoft/vcpkg#36216]
### Library name

swig

### Library description

SWIG is a software development tool that connects programs written in C and C++ with a variety of high-level programming languages.

### Source repository URL

https://github.com/swig/swig

### Project homepage (if different from the source repository)

https://www.swig.org/

**Comment by Neumann-A** [comment]
`vcpkg_find_acquire_program(SWIG)` can be used in portfiles.
