### ISSUE TITLE
msbuild is hard-coded for building Python3 even when in Linux

### ISSUE THREAD

**Issue by Vigilans** [microsoft/vcpkg#3621]
When I tried to install pybind11 in Linux and python3 was to be installed as an dependency, a strange error occured:
```
-- Building /home/vigilans/.local/share/vcpkg/buildtrees/python3/src/v3.6.4-c8a1ba05c7-Lib-static-crt-dynamic/PCBuild/pythoncore.vcxproj for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: msbuild;/home/vigilans/.local/share/vcpkg/buildtrees/python3/src/v3.6.4-c8a1ba05c7-Lib-static-crt-dynamic/PCBuild/pythoncore.vcxproj;/p:Configuration=Release;/t:Rebuild;/p:Platform=x64;/p:PlatformToolset=external;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No;/p:WindowsTargetPlatformVersion=;/m;/p:WholeProgramOptimization=false
    Working Directory: /home/vigilans/.local/share/vcpkg/buildtrees/python3/x64-linux-rel
    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:114 (vcpkg_execute_required_process)
  ports/python3/portfile.cmake:58 (vcpkg_build_msbuild)
  scripts/ports.cmake:72 (include)
```

It means that vcpkg try to invoke msbuild to build an vcproj in Linux!
I tracked the cmake file trough the call stack and found following lines in `ports/python3/portfile.cmake`:

```
vcpkg_build_msbuild(
    PROJECT_PATH ${SOURCE_PATH}/PCBuild/pythoncore.vcxproj
    PLATFORM ${BUILD_ARCH})
```

Man...so msbuild is hard-coded here for building Python3...

**Comment by andreasschulte** [comment]
I had the same problem on Ubuntu. I hacked around in the portfile for python3 to get it to compile. 
The result is not pretty but it seemed to work: andreasschulte/vcpkg@2be6450.

On a side not, I realized later that pybind11 found my anaconda installation, so you might just need to remove the dependency from the CONTROL file in pybind11.

**Comment by Vigilans-Yea** [comment]
@andreasschulte 
Thank you for telling me to deal with the CONTROL file! I will give it a try. 
I also found another solution in the pr history but it looks not pretty too...#3420

**Comment by wangli28** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
