### ISSUE TITLE
[libiconv] Build error on x64-windows

### ISSUE THREAD

**Issue by LiuMingxi** [microsoft/vcpkg#36220]
**Logs**:

PS E:\Program Files\vcpkg> ./vcpkg install libiconv:x64-windows
Computing installation plan...
The following packages will be built and installed:
    libiconv:x64-windows@1.17#2
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\Administrator\AppData\Local\vcpkg\archives in 198 us. Use --debug to see more details.
Installing 1/1 libiconv:x64-windows@1.17#2...
Building libiconv:x64-windows@1.17#2...
-- Using cached libiconv-1.17.tar.gz.
-- Cleaning sources at E:/Program Files/vcpkg/buildtrees/libiconv/src/v1.17-84a471678e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/Program Files/vcpkg/downloads/libiconv-1.17.tar.gz
-- Applying patch 0002-Config-for-MSVC.patch
-- Applying patch 0003-Add-export.patch
-- Applying patch 0004-ModuleFileName.patch
-- Applying patch clang-fortify.patch
-- Using source at E:/Program Files/vcpkg/buildtrees/libiconv/src/v1.17-84a471678e.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
CMake Warning at scripts/cmake/vcpkg_configure_make.cmake:219 (message):
  Detected whitespace in root directory.  Please move the path to one without
  whitespaces! The required tools do not handle whitespaces correctly and the
  build will most likely fail
Call Stack (most recent call first):
  ports/libiconv/portfile.cmake:29 (vcpkg_configure_make)
  scripts/ports.cmake:170 (include)

-- Using cached msys2-autoconf-wrapper-20221207-1-any.pkg.tar.zst.
-- Using cached msys2-automake-wrapper-20221207-1-any.pkg.tar.zst.
-- Using cached msys2-binutils-2.41-3-x86_64.pkg.tar.zst.
-- Using cached msys2-libtool-2.4.7-3-x86_64.pkg.tar.zst.
-- Using cached msys2-make-4.4.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-pkgconf-2.1.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-which-2.21-4-x86_64.pkg.tar.zst.
-- Using cached msys2-bash-5.2.021-1-x86_64.pkg.tar.zst.
-- Using cached msys2-coreutils-8.32-5-x86_64.pkg.tar.zst.
-- Using cached msys2-file-5.45-1-x86_64.pkg.tar.zst.
-- Using cached msys2-gawk-5.3.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-grep-1~3.0-6-x86_64.pkg.tar.zst.
-- Using cached msys2-gzip-1.13-1-x86_64.pkg.tar.zst.
-- Using cached msys2-diffutils-3.10-1-x86_64.pkg.tar.zst.
-- Using cached msys2-sed-4.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.9-3-x86_64.pkg.tar.zst.
-- Using cached msys2-autoconf2.71-2.71-3-any.pkg.tar.zst.
-- Using cached msys2-automake1.16-1.16.5-1-any.pkg.tar.zst.
-- Using cached msys2-libiconv-1.17-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libintl-0.22.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-zlib-1.3-1-x86_64.pkg.tar.zst.
-- Using cached msys2-tar-1.35-2-x86_64.pkg.tar.zst.
-- Using cached msys2-findutils-4.9.0-3-x86_64.pkg.tar.zst.
-- Using cached msys2-gmp-6.3.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-gcc-libs-13.2.0-2-x86_64.pkg.tar.zst.
-- Using cached msys2-libbz2-1.0.8-4-x86_64.pkg.tar.zst.
-- Using cached msys2-liblzma-5.4.5-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libzstd-1.5.5-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libreadline-8.2.007-1-x86_64.pkg.tar.zst.
-- Using cached msys2-mpfr-4.2.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libpcre-8.45-4-x86_64.pkg.tar.zst.
-- Using cached msys2-m4-1.4.19-2-x86_64.pkg.tar.zst.
-- Using cached msys2-perl-5.36.1-2-x86_64.pkg.tar.zst.
-- Using cached msys2-ncurses-6.4-2-x86_64.pkg.tar.zst.
-- Using cached msys2-libxcrypt-4.4.36-1-x86_64.pkg.tar.zst.
-- Using msys root at E:/Program Files/vcpkg/downloads/tools/msys2/5f36c2d65b270362
-- Using cached mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.9-3-x86_64.pkg.tar.zst.
-- Using msys root at E:/Program Files/vcpkg/downloads/tools/msys2/023cdb3ca06f77f2
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "E:/Program Files/vcpkg/downloads/tools/msys2/5f36c2d65b270362/usr/bin/make.exe" -j 5 --trace -f Makefile all
    Working Directory: E:/Program Files/vcpkg/buildtrees/libiconv/x64-windows-dbg/
    See logs for more information:
      E:\Program Files\vcpkg\buildtrees\libiconv\build-x64-windows-dbg-out.log
      E:\Program Files\vcpkg\buildtrees\libiconv\build-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:151 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:2 (vcpkg_build_make)
  ports/libiconv/portfile.cmake:39 (vcpkg_install_make)
  scripts/ports.cmake:170 (include)

error: building libiconv:x64-windows failed with: BUILD_FAILED
Elapsed time to handle libiconv:x64-windows: 14 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
```[tasklist]
### Tasks
```

**Comment by LiuMingxi** [comment]
[build-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/13963039/build-x64-windows-dbg-err.log)
[build-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/13963042/build-x64-windows-dbg-out.log)

**Comment by jimwang118** [comment]
There are spaces in your installation path, please delete them.

**Comment by LiuMingxi** [comment]
> There are spaces in your installation path, please delete them.
thanks，I also found out last night, and now the problem has been solved。

**Comment by LiuMingxi** [comment]
> There are spaces in your installation path, please delete them.

Thanks, I also found out last night, and now the problem has been solved.

**Comment by wrxhardworking** [comment]
so how solved?
i meet same problem

**Comment by sfhacker** [comment]
![image](https://github.com/user-attachments/assets/3d64966a-c15a-4389-9b50-fc13f22dcf07)

**Comment by jimwang118** [comment]
> so how solved? i meet same problem

You can submit an issue separately to explain your problem, which will help in resolving it more effectively.
