### ISSUE TITLE
[zlib] Build error on x64-windows

### ISSUE THREAD

**Issue by DouglasSilSouza** [microsoft/vcpkg#36256]
Copy issue body from C:/Users/dougl/OneDrive/Área de Trabalho/programação/movies telegram bot/telegram-bot-api/vcpkg/installed/vcpkg/issue_body.md

**Comment by LilyWangLL** [comment]
Please see issue https://github.com/microsoft/vcpkg/issues/30604 on how to report a build failure.

**Comment by LilyWangLL** [comment]
It may be that your path contains spaces and other languages, causing the installation to fail. Please clone vcpkg to a path that is all English and has no spaces and then reinstall the port.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
