### ISSUE TITLE
cppzmq build failed on Linux(openSUSE Tumbleweed)

### ISSUE THREAD

**Issue by biluohc** [Microsoft/vcpkg#3626]
```sh
 b/vcpkg.git ╍ vcpkg install cppzmq
The following packages will be built and installed:
    cppzmq[core]:x64-linux
  * zeromq[core]:x64-linux
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: zeromq:x64-linux
Building package zeromq[core]:x64-linux... 
-- CURRENT_INSTALLED_DIR=/home/mxo/bin/vcpkg.git/installed/x64-linux
-- DOWNLOADS=/home/mxo/bin/vcpkg.git/downloads
-- CURRENT_PACKAGES_DIR=/home/mxo/bin/vcpkg.git/packages/zeromq_x64-linux
-- CURRENT_BUILDTREES_DIR=/home/mxo/bin/vcpkg.git/buildtrees/zeromq
-- CURRENT_PORT_DIR=/home/mxo/bin/vcpkg.git/ports/zeromq
-- Downloading https://github.com/zeromq/libzmq/archive/6a5051fac3bb09db7e7772dcbdd591ee7ded1400.tar.gz...
-- Downloading https://github.com/zeromq/libzmq/archive/6a5051fac3bb09db7e7772dcbdd591ee7ded1400.tar.gz... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting source /home/mxo/bin/vcpkg.git/downloads/zeromq-libzmq-6a5051fac3bb09db7e7772dcbdd591ee7ded1400.tar.gz
-- Extracting done
-- Configuring x64-linux-dbg
-- Configuring x64-linux-dbg done
-- Configuring x64-linux-rel
-- Configuring x64-linux-rel done
-- Build x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:170 (message):
    Command failed: /usr/bin/cmake;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: /home/mxo/bin/vcpkg.git/buildtrees/zeromq/x64-linux-dbg
    See logs for more information:
      /home/mxo/bin/vcpkg.git/buildtrees/zeromq/install-x64-linux-dbg-out.log
      /home/mxo/bin/vcpkg.git/buildtrees/zeromq/install-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/zeromq/portfile.cmake:30 (vcpkg_install_cmake)
  scripts/ports.cmake:72 (include)


Error: Building package zeromq:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zeromq:x64-linux
  Vcpkg version: 0.0.113-unknownhash

Additionally, attach any relevant sections from the log files above.
 b/vcpkg.git ╍ cat /home/mxo/bin/vcpkg.git/buildtrees/zeromq/install-x64-linux-dbg-err.log                                                         (15s 99ms) 
CMake Error at cmake_install.cmake:72 (file):
  file INSTALL cannot find
  "/home/mxo/bin/vcpkg.git/buildtrees/zeromq/x64-linux-dbg/doc/zmq.html".
```

**Comment by TorMFinn** [comment]
I seem to have the exact same issue, however it is on Ubuntu 18.04

**Comment by TorMFinn** [comment]
Adding 
-DWITH_DOC=OFF to ports/zeromq/portsfile.cmake solves this. 

```
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -DZMQ_BUILD_TESTS=OFF
        -DPOLLER=select
        -DBUILD_STATIC=${BUILD_STATIC}
        -DBUILD_SHARED=${BUILD_SHARED}
        -DWITH_PERF_TOOL=OFF
	-DWITH_DOC=OFF
    OPTIONS_DEBUG
        "-DCMAKE_PDB_OUTPUT_DIRECTORY=${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-dbg"
)
```

However I assume that building the docs is wanted in most cases.

**Comment by PhoebeHui** [comment]
@biluohc, thanks for posting this issue! Could you try latest vcpkg?  if the issue still occur, could you provide log file   /home/mxo/bin/vcpkg.git/buildtrees/zeromq/install-x64-linux-dbg-err.log?

It installed successfully with latest vcpkg.
linux001@linuxtest01:~/vcpkg$ ./vcpkg install cppzmq
The following packages will be built and installed:
    cppzmq[core]:x64-linux
  * zeromq[core]:x64-linux
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: zeromq:x64-linux
Building package zeromq[core]:x64-linux...
-- Downloading https://github.com/zeromq/libzmq/archive/19b64709bbf9f119d66cdacb9c0e89e4becd9775.tar.gz...
-- Extracting source /home/linux001/vcpkg/downloads/zeromq-libzmq-19b64709bbf9f119d66cdacb9c0e89e4becd9775.tar.gz
-- Using source at /home/linux001/vcpkg/buildtrees/zeromq/src/e4becd9775-bb2ebec5fe
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package zeromq[core]:x64-linux... done
Installing package zeromq[core]:x64-linux...
Installing package zeromq[core]:x64-linux... done
Elapsed time for package zeromq:x64-linux: 35.38 s
Starting package 2/2: cppzmq:x64-linux
Building package cppzmq[core]:x64-linux...
-- Downloading https://github.com/zeromq/cppzmq/archive/v4.3.0.tar.gz...
-- Extracting source /home/linux001/vcpkg/downloads/zeromq-cppzmq-v4.3.0.tar.gz
-- Using source at /home/linux001/vcpkg/buildtrees/cppzmq/src/v4.3.0-d3a2f2af17
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package cppzmq[core]:x64-linux... done
Installing package cppzmq[core]:x64-linux...
Installing package cppzmq[core]:x64-linux... done
Elapsed time for package cppzmq:x64-linux: 2.935 s

Total elapsed time: 38.31 s

The package cppzmq:x64-linux provides CMake targets:
    find_package(cppzmq CONFIG REQUIRED)
    target_link_libraries(main PRIVATE cppzmq cppzmq-static)

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
