### ISSUE TITLE
libffi:x64-windows build failure

### ISSUE THREAD

**Issue by sibman** [microsoft/vcpkg#36272]
### Operating system

Windows 11

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
vcpkg install libffi:x64-windows
```

### Failure logs

[issue_log.txt](https://github.com/microsoft/vcpkg/files/13998903/issue_log.txt)

### Additional context

[additional_context.txt](https://github.com/microsoft/vcpkg/files/13998910/additional_context.txt)

**Comment by jimwang118** [comment]
Sorry, I cannot reproduce this issue locally.
![image](https://github.com/microsoft/vcpkg/assets/122244446/5d1232f2-3a9f-4e6a-9300-80c6788646c4)

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
