### ISSUE TITLE
[vulkan-*, spirv-*, lunarg-vulkantools] update to 1.3.275

### ISSUE THREAD

**Issue by qbojj** [microsoft/vcpkg#36276]
### Library name

vulkan-headers, vulkan-loader, vulkan-sdk-components, vulkan-tools, vulkan-utility-libraries, vulkan-validationlayers, lunarg-vulkantools, spirv-cross, spirv-headers, spirv-reflect, spirv-tools

### New version number

1.3.275

### Other information that may be useful (release notes, etc...)

The 1.3.275 is the next vulkan SDK version so probably it would be a good idea to update all vulkan related ports.

**Comment by MonicaLiu0311** [comment]
Fixing by #36262.
