### ISSUE TITLE
aws-sdk-cpp

### ISSUE THREAD

**Issue by abhishekkarki** [microsoft/vcpkg#36300]
### Discussed in https://github.com/microsoft/vcpkg/discussions/36299

<div type='discussions-op-text'>

<sup>Originally posted by **abhishekkarki** January 22, 2024</sup>
I have installed aws-sdk-cpp using the vcpkg and I am trying to run an example project with it, but I am getting an error with the CMakeLists.txt that it cannot find the library aws-sdk-cpp-core but when I checked in the vcpkg manually it is present. I have also set the path correctly and the toolchain. I am running it in the Visual Studio 22.

![image](https://github.com/microsoft/vcpkg/assets/47475044/95147c94-4132-4e0b-98e3-12d98fc50091)
</div>

**Comment by jimwang118** [comment]
Please provide the cmakelists.txt file you called.
I use the following calling method to compile the result on VS2022 and the result is normal.
```
add_executable (testvcpkg "testvcpkg.cpp" "testvcpkg.h")
find_package(aws-cpp-sdk-core REQUIRED)
target_include_directories(testvcpkg PRIVATE aws-cpp-sdk-core)
target_link_libraries(testvcpkg PRIVATE aws-cpp-sdk-core)
```

**Comment by abhishekkarki** [comment]
yes, I have added these line but I am having problem with this line in the CMakeLists.txt file   AWSSDK_CPY_DYN_LIBS(SERVICE_LIST "" ${CMAKE_CURRENT_BINARY_DIR})  #Choose this line for Visual Studio and possibly other IDEs.
Where can I see the variable CMAKE_CURRENT_BINARY_DIR in VS2022?

**Comment by jimwang118** [comment]
`CMAKE_CURRENT_BINARY_DIR` is a cmake variable that represents the path of the binary directory currently being processed. You can use the message function in `cmakelists.txt` to output this macro, and then view the output results.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
