### ISSUE TITLE
No patch step for 'vcpkg-populate', running vcpkg install failed 

### ISSUE THREAD

**Issue by R-Abbasi** [microsoft/vcpkg#36306]
### Operating system

Windows 

### Compiler

MSVC

### Steps to reproduce the behavior
[github.com/skunkforce/OmniView](https://github.com/skunkforce/OmniView?tab=readme-ov-file#windows)
```Shell
Follow the steps to compile the project on Windows here: https://github.com/skunkforce/OmniView?tab=readme-ov-file#windows
```

### Failure logs

![photo_2024-01-23_00-54-52](https://github.com/microsoft/vcpkg/assets/53223982/2a58cfb2-4382-475e-aed6-e308f03f52e9)

### Additional context

While the vcpkg, as shown at the bottom of the screenshot, is installed on my Windows 10 X-64 machine, why do I get those errors and how to fix them since they point to vcpkg failure, please?

**Comment by Neumann-A** [comment]
The only relevant information here is the hash mismatch for the downloaded powershell. So basically your download of powershell failed. Everything before that does not provide any additional information it just means that whoever set-up the build uses `ExternalProject` to do so.

**Comment by R-Abbasi** [comment]
[this](https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.4#install-powershell-using-winget-recommended) fixed the issue. Thanks you.
