### ISSUE TITLE
vcpkgsrv.exe freezing in project created with vcpkg

### ISSUE THREAD

**Issue by stiv-yakovenko** [Microsoft/vcpkg#3630]
I've installed dlib x64 with cvpkg, created one-file project from this file: http://dlib.net/dnn_inception_ex.cpp.html

Project builds and runs in x64 release/debug modes, but navigation doesnt't work, if you try to go to definition, operation is never finished:

![image](https://user-images.githubusercontent.com/4163254/40794283-e8a20f48-6528-11e8-8832-18cf313e26be.png)

Tried deleting .suo folder, it doesn't help. What can I do? I am using VS2015.

**Comment by JackBoosY** [comment]
Hi @stiv-yakovenko , thanks for reporting this issue.
dlib:x64-windows works fine in vs2015 at latest version.
Plz update vcpkg and rebuild it.And Plz open a new issue if this is still a problem for you.
Thx.
