### ISSUE TITLE
[aom] Build failure

### ISSUE THREAD

**Issue by limuyuan** [microsoft/vcpkg#36304]
Package: aom[core]:arm64-linux -> 3.5.0#1

**Host Environment**

- Host: arm64-linux
- Compiler: GNU 12.2.0
-    vcpkg-tool version: 2999-12-31-unknownhash
    vcpkg-scripts version: 01:42:33.261282 git.c:460               trace: built-in: git show '--pretty=format:%h %cd (%cr)' -s --date=short HEAD
501db0f17 2023-04-15 (9 months ago)

**To Reproduce**

`vcpkg install libvpx libyuv opus aom`

**Failure logs**

```
-- Fetching https://aomedia.googlesource.com/aom 9a83c6a5a55c176adbce740e47d3512edfc9ae71...
CMake Error at scripts/cmake/vcpkg_from_git.cmake:145 (message):
  REF (9a83c6a5a55c176adbce740e47d3512edfc9ae71) does not match rev-parse'd
  reference (01:42:33.254249 git.c:460 trace: built-in: git rev-parse
  9a83c6a5a55c176adbce740e47d3512edfc9ae71

  9a83c6a5a55c176adbce740e47d3512edfc9ae71)

          [Expected : ( 9a83c6a5a55c176adbce740e47d3512edfc9ae71 )])
          [  Actual : ( 01:42:33.254249 git.c:460               trace: built-in: git rev-parse 9a83c6a5a55c176adbce740e47d3512edfc9ae71

  9a83c6a5a55c176adbce740e47d3512edfc9ae71 )]
Call Stack (most recent call first):
  ports/aom/portfile.cmake:11 (vcpkg_from_git)
  scripts/ports.cmake:147 (include)



```

**Additional context**

**Comment by Cheney-W** [comment]
Please run `git pull` to update the version of your local vcpkg and reinstall port again.
