### ISSUE TITLE
Building package harfbuzz:x64-linux failed

### ISSUE THREAD

**Issue by arthur-tacca** [Microsoft/vcpkg#3632]
I'm using Ubuntu 16.04 with the suggested PPA for gcc 7, with vcpkg at commit 33ba0669661bfededfb14bdc0399f638076e5b59 (Wed May 30 23:41:55 2018). I tried to install harfbuzz:x64-linux and I got the following error. (I was actually trying to install qt5 but harfbuzz is a dependency.)

    Call Stack (most recent call first):
      scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
      ports/harfbuzz/portfile.cmake:37 (vcpkg_install_cmake)
      scripts/ports.cmake:72 (include)

    Error: Building package harfbuzz:x64-linux failed with: BUILD_FAILED
    Please ensure you're using the latest portfiles with `.\vcpkg update`, then
    submit an issue at https://github.com/Microsoft/vcpkg/issues including:
      Package: harfbuzz:x64-linux
      Vcpkg version: 0.0.113-unknownhash

Here is the end of the log file, including the error message and a few lines of context:

    [58/60] : && /usr/bin/c++  -fno-rtti -fno-exceptions -fno-threadsafe-statics -fdiagnostics-color  -rdynamic CMakeFiles/test-would-substitute.dir/src/test-would-substitute.cc.o  -o test-would-substitute -L/usr/lib/gcc/x86_64-linux-gnu/5 -Bsymbolic-functions libharfbuzz.a /home/arthur/src/libraries/vcpkg/installed/x64-linux/lib/libfreetype.a /home/arthur/src/libraries/vcpkg/installed/x64-linux/lib/libbz2.a -lpng /home/arthur/src/libraries/vcpkg/installed/x64-linux/lib/libz.a /home/arthur/src/libraries/vcpkg/installed/x64-linux/lib/libz.a -lgcc -lgcc_s -lc -lgcc -lgcc_s && :
    FAILED: test-would-substitute 
    : && /usr/bin/c++  -fno-rtti -fno-exceptions -fno-threadsafe-statics -fdiagnostics-color  -rdynamic CMakeFiles/test-would-substitute.dir/src/test-would-substitute.cc.o  -o test-would-substitute -L/usr/lib/gcc/x86_64-linux-gnu/5 -Bsymbolic-functions libharfbuzz.a /home/arthur/src/libraries/vcpkg/installed/x64-linux/lib/libfreetype.a /home/arthur/src/libraries/vcpkg/installed/x64-linux/lib/libbz2.a -lpng /home/arthur/src/libraries/vcpkg/installed/x64-linux/lib/libz.a /home/arthur/src/libraries/vcpkg/installed/x64-linux/lib/libz.a -lgcc -lgcc_s -lc -lgcc -lgcc_s && :
    /home/arthur/src/libraries/vcpkg/installed/x64-linux/lib/libfreetype.a(sfnt.c.o): In function `error_callback':
    sfnt.c:(.text+0x23c): undefined reference to `png_set_longjmp_fn'
    /home/arthur/src/libraries/vcpkg/installed/x64-linux/lib/libfreetype.a(sfnt.c.o): In function `Load_SBit_Png':
    sfnt.c:(.text+0x4ba): undefined reference to `png_set_longjmp_fn'
    collect2: error: ld returned 1 exit status
    [59/60] : && /usr/bin/c++  -fno-rtti -fno-exceptions -fno-threadsafe-statics -fdiagnostics-color  -rdynamic CMakeFiles/test-test.dir/src/test.cc.o  -o test-test -L/usr/lib/gcc/x86_64-linux-gnu/5 -Bsymbolic-functions libharfbuzz.a /home/arthur/src/libraries/vcpkg/installed/x64-linux/lib/libfreetype.a /home/arthur/src/libraries/vcpkg/installed/x64-linux/lib/libbz2.a -lpng /home/arthur/src/libraries/vcpkg/installed/x64-linux/lib/libz.a /home/arthur/src/libraries/vcpkg/installed/x64-linux/lib/libz.a -lgcc -lgcc_s -lc -lgcc -lgcc_s && :
    FAILED: test-test 
    : && /usr/bin/c++  -fno-rtti -fno-exceptions -fno-threadsafe-statics -fdiagnostics-color  -rdynamic CMakeFiles/test-test.dir/src/test.cc.o  -o test-test -L/usr/lib/gcc/x86_64-linux-gnu/5 -Bsymbolic-functions libharfbuzz.a /home/arthur/src/libraries/vcpkg/installed/x64-linux/lib/libfreetype.a /home/arthur/src/libraries/vcpkg/installed/x64-linux/lib/libbz2.a -lpng /home/arthur/src/libraries/vcpkg/installed/x64-linux/lib/libz.a /home/arthur/src/libraries/vcpkg/installed/x64-linux/lib/libz.a -lgcc -lgcc_s -lc -lgcc -lgcc_s && :
    /home/arthur/src/libraries/vcpkg/installed/x64-linux/lib/libfreetype.a(sfnt.c.o): In function `error_callback':
    sfnt.c:(.text+0x23c): undefined reference to `png_set_longjmp_fn'
    /home/arthur/src/libraries/vcpkg/installed/x64-linux/lib/libfreetype.a(sfnt.c.o): In function `Load_SBit_Png':
    sfnt.c:(.text+0x4ba): undefined reference to `png_set_longjmp_fn'
    collect2: error: ld returned 1 exit status
    ninja: build stopped: subcommand failed.

It's perhaps worth mentioning that libpng is already successfully installed when I get this message.

**Comment by PhoebeHui** [comment]
@arthur-tacca, thank you for posting this issue, please try to install harfbuzz with vcpkg latest revision, and please open a new issue if this is still a problem for you.

Harfbuzz installed successfully currently:
linux001@linuxtest01:~/vcpkg$ ./vcpkg install harfbuzz
The following packages will be built and installed:
    harfbuzz[core,ucdn]:x64-linux
  * ragel[core]:x64-linux
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: ragel:x64-linux
Building package ragel[core]:x64-linux...
-- Downloading http://www.colm.net/files/ragel/ragel-6.10.tar.gz...
-- Extracting source /home/linux001/vcpkg/downloads/ragel-6.10.tar.gz
-- Applying patch /home/linux001/vcpkg/ports/ragel/0001-Remove-unistd.h-include-1.patch
-- Applying patch /home/linux001/vcpkg/ports/ragel/0002-Remove-unistd.h-include-2.patch
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package ragel[core]:x64-linux... done
Installing package ragel[core]:x64-linux...
Installing package ragel[core]:x64-linux... done
Elapsed time for package ragel:x64-linux: 24.29 s
Starting package 2/2: harfbuzz:x64-linux
Building package harfbuzz[core,ucdn]:x64-linux...
-- Downloading https://github.com/harfbuzz/harfbuzz/archive/1.8.4.tar.gz...
-- Extracting source /home/linux001/vcpkg/downloads/harfbuzz-harfbuzz-1.8.4.tar.gz
-- Applying patch 0001-fix-uwp-build.patch
-- Applying patch find-package-freetype-2.patch
-- Applying patch glib-cmake.patch
-- Applying patch 0001-fix-cmake-export.patch
-- Applying patch 0002-fix-macos-build.patch
-- Using source at /home/linux001/vcpkg/buildtrees/harfbuzz/src/1.8.4-e7fe7a2838
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Performing CMake integration test
-- Performing post-build validation
-- Performing post-build validation done
Building package harfbuzz[core,ucdn]:x64-linux... done
Installing package harfbuzz[core,ucdn]:x64-linux...
Installing package harfbuzz[core,ucdn]:x64-linux... done
Elapsed time for package harfbuzz:x64-linux: 18.47 s

Total elapsed time: 42.76 s

The package harfbuzz:x64-linux provides CMake targets:
    find_package(harfbuzz CONFIG REQUIRED)
    target_link_libraries(main PRIVATE harfbuzz::harfbuzz)
