### ISSUE TITLE
[qtwebengine] build failure

### ISSUE THREAD

**Issue by jezzzzza** [microsoft/vcpkg#36321]
### Operating system

Windows 64bit

### Compiler

MSVC 19.37.32825

### Steps to reproduce the behavior

```Shell
using vcpkg manifest mode, 
e.g.
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json",
  "name": "test",
  "version": "1.0.0",
  "builtin-baseline": "6ca56aeb457f033d344a7106cb3f9f1abf8f4e98",
  "dependencies": [
    "expat",
    "zlib",
    "qtwebengine"
  ]
}
```

### Failure logs

Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at C:/Users/myuser/Downloads/QtQuick-with-cmake-master/out/build/vcpkg_installed/x64-windows/share/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake:78 (file):
  file COPY cannot find
  "D:/git/vcpkg/downloads/tools/python/python-3.11.5-x64/python310.zip": File
  exists.		C:/Users/myuser/Downloads/QtQuick-with-cmake-master/out/build/vcpkg_installed/x64-windows/share/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake	78	
Error		CMake Error at D:/git/vcpkg/scripts/buildsystems/vcpkg.cmake:899 (message):
  vcpkg install failed.  See logs for more information:
  C:\Users\myuser\Downloads\QtQuick-with-cmake-master\out\build\vcpkg-manifest-install.log		D:/git/vcpkg/scripts/buildsystems/vcpkg.cmake	899

**Comment by Cheney-W** [comment]
@jezzzzza 
I noticed that you're using the commit from 9/2/2022 for builtin-baseline. If it's not necessary, I think you can use the latest commit from vcpkg.
