### ISSUE TITLE
[New Port Request] Diligent Engine

### ISSUE THREAD

**Issue by a-karimov** [microsoft/vcpkg#36323]
### Library name

Diligent Engine

### Library description

A Modern Cross-Platform Low-Level 3D Graphics Library and Rendering Framework

### Source repository URL

https://github.com/DiligentGraphics/DiligentEngine

### Project homepage (if different from the source repository)

http://diligentgraphics.com/diligent-engine/

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

Diligent Engine includes Core and Tools subprojects, which ideally should be configurable.
The Samples subproject, probably, is out of scope of vcpkg.

**Comment by SoundDev** [comment]
I would also like to see this port completed..
