### ISSUE TITLE
[New Port Request] MS-QUIC

### ISSUE THREAD

**Issue by rafalsk** [microsoft/vcpkg#36324]
### Library name

MS-QUIC

### Source repository URL

https://github.com/microsoft/msquic

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

stale for 3 years.. by Microsoft:)

**Comment by rafalsk** [comment]
`The MsQuic port in vcpkg is kept up to date by Microsoft team members and community contributors. If the version is out of date, please [create an issue or pull request](https://github.com/Microsoft/vcpkg) on the vcpkg repository.`

**Comment by luncliff** [comment]
Probably https://github.com/microsoft/vcpkg/blob/master/ports/ms-quic/vcpkg.json ?
