### ISSUE TITLE
[openssl] update to <1.1.1w>

### ISSUE THREAD

**Issue by DaraghOKeeffe** [microsoft/vcpkg#36350]
### Library name

Openssl

### New version number

1.1.1w

### Other information that may be useful (release notes, etc...)

https://github.com/openssl/openssl/releases/tag/OpenSSL_1_1_1w

**Comment by Osyotr** [comment]
1) it's out of support
2) vcpkg already has openssl 3.2.0
If you for some reason still require openssl 1.1.1, follow this thread #26723
