### ISSUE TITLE
[fastrtps] update to 2.13.1

### ISSUE THREAD

**Issue by duca** [microsoft/vcpkg#36368]
### Library name

fastrtps

### New version number

2.13.1

### Other information that may be useful (release notes, etc...)

There are a ton of improvement since 2.7.0 specially on windows, but latest release notes are: 

Fast DDS v2.13.1 (https://github.com/eProsima/Fast-DDS/tree/v2.13.1)

This patch release includes the following fixes and improvements:

    Revert wrong fix for TCP deadlock on channel reuse (https://github.com/eProsima/Fast-DDS/pull/4181)
    Fix wrong history selection when removing PDP samples (https://github.com/eProsima/Fast-DDS/pull/4182)
    Fix data race when processing incoming PDP samples on different threads (https://github.com/eProsima/Fast-DDS/pull/4188)
    Fix DNS test filter in CMakeLists (https://github.com/eProsima/Fast-DDS/pull/4211)
    Downgrade CMake minimum required version to 3.20 (https://github.com/eProsima/Fast-DDS/pull/4218)
    Update versions.md (https://github.com/eProsima/Fast-DDS/pull/4219)
    Update PR template to include check for PR description, title and backports (https://github.com/eProsima/Fast-DDS/pull/4215)
    Update Fast CDR submodule to v2.1.3 (https://github.com/eProsima/Fast-DDS/pull/4226)
    Regenerate Fast DDS types due to Gen release v3.2.1 (https://github.com/eProsima/Fast-DDS/pull/4229)

PRs in merged order:
https://github.com/eProsima/Fast-DDS/pull/4182, https://github.com/eProsima/Fast-DDS/pull/4181, https://github.com/eProsima/Fast-DDS/pull/4195, https://github.com/eProsima/Fast-DDS/pull/4188, https://github.com/eProsima/Fast-DDS/pull/4211, https://github.com/eProsima/Fast-DDS/pull/4215, https://github.com/eProsima/Fast-DDS/pull/4219 , https://github.com/eProsima/Fast-DDS/pull/4218, https://github.com/eProsima/Fast-DDS/pull/4226, https://github.com/eProsima/Fast-DDS/pull/4229

**Comment by Cheney-W** [comment]
Sloved by PR https://github.com/microsoft/vcpkg/pull/38637
