### ISSUE TITLE
spdlog: build broken with new version of fmtlib

### ISSUE THREAD

**Issue by jmin911** [Microsoft/vcpkg#3636]
fmtlib has been updated to version 4.0.
After upgrading, spdlog does not work anymore.
Here are the errors:
1>c:\src\vcpkg\installed\x86-windows-static\include\spdlog\details\log_msg.h(45): error C2039: 'MemoryWriter': is not a member of 'fmt'
1>c:\src\vcpkg\installed\x86-windows-static\include\fmt\format.h(371): note: see declaration of 'fmt'
1>c:\src\vcpkg\installed\x86-windows-static\include\spdlog\details\log_msg.h(45): error C3646: 'raw': unknown override specifier
1>c:\src\vcpkg\installed\x86-windows-static\include\spdlog\details\log_msg.h(45): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\src\vcpkg\installed\x86-windows-static\include\spdlog\details\log_msg.h(46): error C2039: 'MemoryWriter': is not a member of 'fmt'
1>c:\src\vcpkg\installed\x86-windows-static\include\fmt\format.h(371): note: see declaration of 'fmt'
1>c:\src\vcpkg\installed\x86-windows-static\include\spdlog\details\log_msg.h(46): error C3646: 'formatted': unknown override specifier
1>c:\src\vcpkg\installed\x86-windows-static\include\spdlog\details\log_msg.h(46): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\src\vcpkg\installed\x86-windows-static\include\spdlog\details\pattern_formatter_impl.h(44): error C2039: 'formatted': is not a member of 'spdlog::details::log_msg'
1>c:\src\vcpkg\installed\x86-windows-static\include\spdlog\details\log_msg.h(20): note: see declaration of 'spdlog::details::log_msg'
1>c:\src\vcpkg\installed\x86-windows-static\include\spdlog\details\pattern_formatter_impl.h(54): error C2039: 'formatted': is not a member of 'spdlog::details::log_msg'
1>c:\src\vcpkg\installed\x86-windows-static\include\spdlog\details\log_msg.h(20): note: see declaration of 'spdlog::details::log_msg'
1>c:\src\vcpkg\installed\x86-windows-static\include\spdlog\details\pattern_formatter_impl.h(63): error C2039: 'formatted': is not a member of 'spdlog::details::log_msg'
1>c:\src\vcpkg\installed\x86-windows-static\include\spdlog\details\log_msg.h(20): note: see declaration of 'spdlog::details::log_msg'
1>c:\src\vcpkg\installed\x86-windows-static\include\spdlog\details\pattern_formatter_impl.h(87): error C2039: 'formatted': is not a member of 'spdlog::details::log_msg'
1>c:\src\vcpkg\installed\x86-windows-static\include\spdlog\details\log_msg.h(20): note: see declaration of 'spdlog::details::log_msg'

**Comment by KindDragon** [comment]
https://github.com/gabime/spdlog/issues/708

**Comment by KindDragon** [comment]
Fixed in PR #4025
