### ISSUE TITLE
chipmunk

### ISSUE THREAD

**Issue by RobViren** [Microsoft/vcpkg#3638]
Package: chipmunk:x86-windows
 Vcpkg version: 0.0.113-nohash

Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : Configuration error MSB4148: The name of a property stored under the registry key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions\4.0\VCTargetsPath" has zero length.

**Comment by nicole9456** [comment]
@RobViren  we can't repro the issue on VS2017 and the latest vcpkg. Could you try a again? if you still can repro it, would you please more detail information and re-open the issue. Thanks very much!
