### ISSUE TITLE
glibc

### ISSUE THREAD

**Issue by jdm7dv** [microsoft/vcpkg#3640]
Hi can it be possible to create a port of the GNU C library to Windows? I tried using MSYS2 to no avail with the command: `./configure –prefix=/usr/local/i586-mingw32 –host=i586-mingw32msvc`

The error was:

`../configure/build --host=i586-mingw32msvc
configure: loading site script /mingw64/etc/config.site
checking build system type... x86_64-w64-mingw32
checking host system type... i586-pc-mingw32msvc
checking for i586-mingw32msvc-gcc... no
checking for gcc... gcc
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc... gcc
checking for i586-mingw32msvc-readelf... no
checking for readelf... readelf
checking for i586-mingw32msvc-g++... no
checking for i586-mingw32msvc-c++... no
checking for i586-mingw32msvc-gpp... no
checking for i586-mingw32msvc-aCC... no
checking for i586-mingw32msvc-CC... no
checking for i586-mingw32msvc-cxx... no
checking for i586-mingw32msvc-cc++... no
checking for i586-mingw32msvc-cl.exe... no
checking for i586-mingw32msvc-FCC... no
checking for i586-mingw32msvc-KCC... no
checking for i586-mingw32msvc-RCC... no
checking for i586-mingw32msvc-xlC_r... no
checking for i586-mingw32msvc-xlC... no
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether g++ can link programs... yes
checking for sysdeps preconfigure fragments... aarch64 alpha arm hppa i386 m68k microblaze mips nios2 powerpc riscv s390 sh sparc tile x86_64
configure: error:
*** The GNU C library is currently unavailable for this platform.
*** If you are interested in seeing glibc on this platform visit
*** the "How to submit a new port" in the wiki:
***   https://sourceware.org/glibc/wiki/#Development
*** and join the community!'`

This error was on MSYS2 I think I didn't have my Visual C/C++ tools installed in MSYS2.

I'm on Windows 10 2016 Enterprise LTSB I would like to use Visual C/C++ or MSYS2 and maybe a Mac port. And I just sent a message to the community listserv.

Would I have to install cross compilation tools on Debian/Ubuntu?

`sudo apt-get install mingw32`

I get the same configure error when I use the cross compilation tools on my Debian VMWare virtual machine.

`~/Downloads/glibc-2.27/build$ ../configure --host=i586-mingw32msvc
checking build system type... x86_64-pc-linux-gnu
checking host system type... i586-pc-mingw32msvc
checking for i586-mingw32msvc-gcc... i586-mingw32msvc-gcc
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether i586-mingw32msvc-gcc accepts -g... yes
checking for gcc... gcc
checking for i586-mingw32msvc-readelf... i586-mingw32msvc-readelf
checking for i586-mingw32msvc-g++... i586-mingw32msvc-g++
checking whether we are using the GNU C++ compiler... yes
checking whether i586-mingw32msvc-g++ accepts -g... yes
checking whether i586-mingw32msvc-g++ can link programs... yes
checking for sysdeps preconfigure fragments... aarch64 alpha arm hppa i386 m68k microblaze mips nios2 powerpc riscv s390 sh sparc tile x86_64 
configure: error: 
*** The GNU C library is currently unavailable for this platform.
*** If you are interested in seeing glibc on this platform visit
*** the "How to submit a new port" in the wiki:
***   https://sourceware.org/glibc/wiki/#Development
*** and join the community!
`

**Comment by JackBoosY** [comment]
I think you can use `vcpkg_configure_make` and `vcpkg_install_make`.
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
