### ISSUE TITLE
bootstrap-vcpkg.bat fails if vcpkg was cloned inside WSL on Windows April 2018 Update

### ISSUE THREAD

**Issue by kromain** [Microsoft/vcpkg#3641]
When cloning the vcpkg repo using WSL's git client, the created directory structure is now treated as case-sensitive even outside WSL starting with the Windows April 2018 update (see https://blogs.msdn.microsoft.com/commandline/2018/02/28/per-directory-case-sensitivity-and-wsl/)

This results in bootstrap-vcpkg.bat failing quickly due to mismatch cases between 'release' and 'Release' folders:

```
c:\dev\vcpkg>bootstrap-vcpkg.bat

Building vcpkg.exe ...

  pch.cpp
CL : fatal error C1083: Cannot open compiler intermediate file: 'c:\dev\vcpkg\toolsrc\vcpkglib\release\vcpkglib.pch':
No such file or directory [C:\dev\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
C:\dev\vcpkg\scripts\bootstrap.ps1 : Building vcpkg.exe failed. Please ensure you have installed Visual Studio with
the Desktop C++ workload and the Windows SDK for Desktop C++.
At line:1 char:4
+ & {& 'c:\dev\vcpkg\scripts\bootstrap.ps1'}
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,bootstrap.ps1


c:\dev\vcpkg>
```

The build script looks for 'release' but the folder on disk is 'Release', thus the no-such-file error with case-sensitive names.

**Comment by alexkaratarakis** [comment]
Fixed, thanks for reporting!

**Comment by aalpert-bluescape** [comment]
b81090e2507c6512bdc9896bab02acc68488263f changed it back and so I'm hitting this issue. I'll checkout an older version to get around it for now, but you might need to reopen this issue.
