### ISSUE TITLE
vcpkg_buildpath_length_warning guidance is obsolete / inadequate for manifest mode

### ISSUE THREAD

**Issue by justusranvier** [microsoft/vcpkg#36428]
**Describe the bug**
The recommendations printed by vcpkg_buildpath_length_warning will not resolve the MAX_PATH issues on Windows when building in manifest mode. A [superior recommendation](https://github.com/microsoft/vcpkg/issues/30446#issuecomment-1484247259) which works in all build modes is available in a comment attached to another issue but is not documented anywhere else. This guidance is what vcpkg_buildpath_length_warning should print.

The existing guidance is not applicable to manifest mode because even if you've installed vcpkg in c:\vcpkg that's not where the build trees are created.

**Environment**
- OS: Windows

**To Reproduce**
1. try to build any project in manifest mode which depends on qtdeclarative

**Comment by kaivol** [comment]
not stale, please reopen
