### ISSUE TITLE
[libsystemd] Build error on x64-linux

### ISSUE THREAD

**Issue by hash2000** [microsoft/vcpkg#36426]
Hi!

> ./vcpkg install libsystemd:x64-linux

Computing installation plan...
The following packages will be built and installed:
    libsystemd:x64-linux@254#2
Detecting compiler hash for triplet x64-linux...
Restored 0 package(s) from /home/username/.cache/vcpkg/archives in 13.3 us. Use --debug to see more details.
Installing 1/1 libsystemd:x64-linux@254#2...
Building libsystemd:x64-linux@254#2...
-- Using cached systemd-systemd-v254.tar.gz.
-- Extracting source /media/user_name/distr/vcpkg/downloads/systemd-systemd-v254.tar.gz
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /media/user_name/distr/vcpkg/downloads/tools/cmake-3.27.1-linux/cmake-3.27.1-linux-x86_64/bin/cmake -E tar xjf /media/user_name/distr/vcpkg/downloads/systemd-systemd-v254.tar.gz
    Working Directory: /media/user_name/distr/vcpkg/buildtrees/libsystemd/src/v254-832da4078b.clean.tmp
    Error code: 1
    See logs for more information:
      /media/user_name/distr/vcpkg/buildtrees/libsystemd/extract-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive.cmake:120 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:8 (vcpkg_extract_source_archive)
  scripts/cmake/vcpkg_from_github.cmake:113 (vcpkg_extract_source_archive_ex)
  ports/libsystemd/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:170 (include)

error: building libsystemd:x64-linux failed with: BUILD_FAILED
Elapsed time to handle libsystemd:x64-linux: 1.1 s

command:

`cmake -E tar xjf /media/user_name/distr/vcpkg/downloads/systemd-systemd-v254.tar.gz`

returns:
`CMake Error: Problem with archive_write_header(): Can't create 'systemd-254/test/fuzz/fuzz-unit-file/dm-back\x2dslash.swap'
CMake Error: Current file: systemd-254/test/fuzz/fuzz-unit-file/dm-back\x2dslash.swap
CMake Error: Problem extracting tar: /media/hash2000/distr/vcpkg/downloads/systemd-systemd-v254.tar.gz`

indeed, the archive is not unpacked
Ubuntu 22.04

**Comment by dg0yt** [comment]
... `/media/user_name/` ... `systemd-254/test/fuzz/fuzz-unit-file/dm-back\x2dslash.swap` ...

Maybe this removable media device has a poor (FAT) filesystem? AFAIU extraction fails on an unusual file name.

**Comment by hash2000** [comment]
yes, indeed, I was doing ext4 and everything worked. there was an ntfs markup. thanks
