### ISSUE TITLE
[libconfig] cmake files missing when installing with project manifest file

### ISSUE THREAD

**Issue by tjippasma** [microsoft/vcpkg#36441]
**Describe the bug**
The libconfig cmake files is missing when installing libconfig in a project with vcpkg manifest file (vcpkg.json)
libconfig 1.7.3

**Environment**
- OS: Windows 10
- Compiler: vc 19.38.33134

**To Reproduce**
1. vcpkg.exe add port libconfig
2. vcpkg install

The content of libconfig_1.7.3_x64-windows.list show that cmake files is missing. I compared to content of a global install of libconfig.
and the project installation is missing these files:

x64-windows/include/libconfig.hh
x64-windows/share/libconfig/libconfigConfig-debug.cmake
x64-windows/share/libconfig/libconfigConfig-release.cmake
x64-windows/share/libconfig/libconfigConfig.cmake
x64-windows/share/libconfig/libconfigConfigVersion.cmake

**Expected behavior**
-

**Failure logs**
Content of libconfig_1.7.3_x64-windows.list from project installation
`
x64-windows/
x64-windows/bin/
x64-windows/bin/libconfig++.dll
x64-windows/bin/libconfig++.pdb
x64-windows/bin/libconfig.dll
x64-windows/bin/libconfig.pdb
x64-windows/debug/
x64-windows/debug/bin/
x64-windows/debug/bin/libconfig++.dll
x64-windows/debug/bin/libconfig++.pdb
x64-windows/debug/bin/libconfig.dll
x64-windows/debug/bin/libconfig.pdb
x64-windows/debug/lib/
x64-windows/debug/lib/libconfig++.lib
x64-windows/debug/lib/libconfig.lib
x64-windows/include/
x64-windows/include/libconfig.h
x64-windows/include/libconfig.h++
x64-windows/lib/
x64-windows/lib/libconfig++.lib
x64-windows/lib/libconfig.lib
x64-windows/share/
x64-windows/share/libconfig/
x64-windows/share/libconfig/copyright
x64-windows/share/libconfig/vcpkg.spdx.json
x64-windows/share/libconfig/vcpkg_abi_info.txt
`

**Additional context**

**Comment by LilyWangLL** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
