### ISSUE TITLE
[openssl] Build error on x64-windows

### ISSUE THREAD

**Issue by PROgame557** [microsoft/vcpkg#36458]
Package: openssl:x64-windows@3.2.0#2

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.38.33133.0
-    vcpkg-tool version: 2024-01-11-710a3116bbd615864eef5f9010af178034cb9b44
    vcpkg-scripts version: unknown

**To Reproduce**

`vcpkg install openssl`
**Failure logs**

```
-- Using cached openssl-openssl-openssl-3.2.0.tar.gz.
-- Cleaning sources at D:/VCPKG/buildtrees/openssl/src/nssl-3.2.0-5a1db6e780.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/VCPKG/downloads/openssl-openssl-openssl-3.2.0.tar.gz
-- Applying patch asm-comments.patch
-- Applying patch declspec-align.patch
-- Applying patch qt-msvc.patch
-- Applying patch script-prefix.patch
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch unix/android-cc.patch
-- Applying patch unix/move-openssldir.patch
-- Applying patch unix/no-empty-dirs.patch
-- Applying patch unix/no-static-libs-for-shared.patch
-- Applying patch unix/disable-quicserver.patch
-- Using source at D:/VCPKG/buildtrees/openssl/src/nssl-3.2.0-5a1db6e780.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Getting CMake variables for x64-windows
-- Prerunning x64-windows-dbg
-- Building x64-windows-dbg
-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "D:/Visual Studio/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/nmake.exe" /NOLOGO /G /U /F makefile install_dev install_modules INSTALL_PDBS=ON
    Working Directory: D:/VCPKG/buildtrees/openssl/x64-windows-dbg
    See logs for more information:
      D:\VCPKG\buildtrees\openssl\install-x64-windows-dbg-nmake-out.log
      D:\VCPKG\buildtrees\openssl\install-x64-windows-dbg-nmake-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_nmake.cmake:156 (vcpkg_execute_build_process)
  ports/openssl/windows/portfile.cmake:69 (vcpkg_build_nmake)
  ports/openssl/portfile.cmake:78 (include)
  scripts/ports.cmake:170 (include)



```
<details><summary>D:\VCPKG\buildtrees\openssl\install-x64-windows-dbg-nmake-err.log</summary>

```
cl: командная строка warning D9025: переопределение "/Zi" на "/Z7"
NMAKE : fatal error U1077: "D:\Visual Studio\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe"  /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MDd -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -MP  -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 -I"crypto" -I"." -I"include" -I"providers\common\include" -I"providers\implementations\include" -D"L_ENDIAN" -D"OPENSSL_PIC" -D"OPENSSLDIR=\"D:\\VCPKG\\packages\\openssl_x64-windows\\debug\"" -D"ENGINESDIR=\"D:\\VCPKG\\packages\\openssl_x64-windows\\debug\\lib\\engines-3\"" -D"MODULESDIR=\"D:\\VCPKG\\packages\\openssl_x64-windows\\debug\\bin\"" -D"OPENSSL_BUILDING_OPENSSL" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"DEBUG" -D"_DEBUG"   -DAES_ASM -DBSAES_ASM -DCMLL_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DKECCAK1600_ASM -DMD5_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_USE_APPLINK -DPADLOCK_ASM -DPOLY1305_ASM -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DX25519_ASM -c /Focrypto\libcrypto-shlib-cversion.obj "crypto\cversion.c" : ������������ ��� "0x2"
Stop.
NMAKE : fatal error U1077: "D:\Visual Studio\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\nmake.exe" /LU                 _build_libs : ������������ ��� "0x2"
Stop.
```
</details>

<details><summary>D:\VCPKG\buildtrees\openssl\install-x64-windows-dbg-nmake-out.log</summary>

```
	"D:\Visual Studio\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\nmake.exe" /LU                 depend
	"D:\Visual Studio\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\nmake.exe" /LU                 _build_libs
	"D:\Visual Studio\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe"  /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MDd -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -MP  -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 -I"crypto" -I"." -I"include" -I"providers\common\include" -I"providers\implementations\include" -D"L_ENDIAN" -D"OPENSSL_PIC" -D"OPENSSLDIR=\"D:\\VCPKG\\packages\\openssl_x64-windows\\debug\"" -D"ENGINESDIR=\"D:\\VCPKG\\packages\\openssl_x64-windows\\debug\\lib\\engines-3\"" -D"MODULESDIR=\"D:\\VCPKG\\packages\\openssl_x64-windows\\debug\\bin\"" -D"OPENSSL_BUILDING_OPENSSL" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"DEBUG" -D"_DEBUG"   -DAES_ASM -DBSAES_ASM -DCMLL_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DKECCAK1600_ASM -DMD5_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_USE_APPLINK -DPADLOCK_ASM -DPOLY1305_ASM -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DX25519_ASM -c /Focrypto\libcrypto-shlib-cversion.obj "crypto\cversion.c"
cversion.c
crypto\cversion.c(60): warning C4129: V: неизвестная escape-последовательность
crypto\cversion.c(60): warning C4129: T: неизвестная escape-последовательность
crypto\cversion.c(60): warning C4129: M: неизвестная escape-последовательность
crypto\cversion.c(60): warning C4129: H: неизвестная escape-последовательность
crypto\cversion.c(60): warning C4129: c: неизвестная escape-последовательность
crypto\cversion.c(60): error C2143: синтаксическая ошибка: отсутствие ";" перед "константа"
crypto\cversion.c(60): error C2143: синтаксическая ошибка: отсутствие ";" перед "строка"
```
</details>

**Comment by PROgame557** [comment]
Help plz... I'm new to installing new libraries... and so I'm asking for your help on how to solve this problem... **thanks!**

**Comment by overcoil** [comment]
Maybe start by looking the log files that the error refers to?

```
   See logs for more information:
      D:\VCPKG\buildtrees\openssl\install-x64-windows-dbg-nmake-out.log
      D:\VCPKG\buildtrees\openssl\install-x64-windows-dbg-nmake-err.log
```

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Did you install the English Language Package on Visual Studio?

**Comment by PROgame557** [comment]
> Thanks for posting this issue. Did you install the English Language Package on Visual Studio?

No, I'm using the russian language pack.

**Comment by PROgame557** [comment]
> Maybe start by looking the log files that the error refers to?
> 
> ```
>    See logs for more information:
>       D:\VCPKG\buildtrees\openssl\install-x64-windows-dbg-nmake-out.log
>       D:\VCPKG\buildtrees\openssl\install-x64-windows-dbg-nmake-err.log
> ```

D:\VCPKG\buildtrees\openssl\install-x64-windows-dbg-nmake-out.log ->

	"D:\Visual Studio\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\nmake.exe" /LU                 depend
	"D:\Visual Studio\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\nmake.exe" /LU                 _build_libs
	"D:\Visual Studio\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe"  /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MDd -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -MP  -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 -I"crypto" -I"." -I"include" -I"providers\common\include" -I"providers\implementations\include" -D"L_ENDIAN" -D"OPENSSL_PIC" -D"OPENSSLDIR=\"D:\\VCPKG\\packages\\openssl_x64-windows\\debug\"" -D"ENGINESDIR=\"D:\\VCPKG\\packages\\openssl_x64-windows\\debug\\lib\\engines-3\"" -D"MODULESDIR=\"D:\\VCPKG\\packages\\openssl_x64-windows\\debug\\bin\"" -D"OPENSSL_BUILDING_OPENSSL" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"DEBUG" -D"_DEBUG"   -DAES_ASM -DBSAES_ASM -DCMLL_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DKECCAK1600_ASM -DMD5_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_USE_APPLINK -DPADLOCK_ASM -DPOLY1305_ASM -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DX25519_ASM -c /Focrypto\libcrypto-shlib-cversion.obj "crypto\cversion.c"
cversion.c
crypto\cversion.c(60): warning C4129: V: неизвестная escape-последовательность
crypto\cversion.c(60): warning C4129: T: неизвестная escape-последовательность
crypto\cversion.c(60): warning C4129: M: неизвестная escape-последовательность
crypto\cversion.c(60): warning C4129: H: неизвестная escape-последовательность
crypto\cversion.c(60): warning C4129: c: неизвестная escape-последовательность
crypto\cversion.c(60): error C2143: синтаксическая ошибка: отсутствие ";" перед "константа"
crypto\cversion.c(60): error C2143: синтаксическая ошибка: отсутствие ";" перед "строка"


D:\VCPKG\buildtrees\openssl\install-x64-windows-dbg-nmake-err.log ->

cl: РєРѕРјР°РЅРґРЅР°СЏ СЃС‚СЂРѕРєР° warning D9025: РїРµСЂРµРѕРїСЂРµРґРµР»РµРЅРёРµ "/Zi" РЅР° "/Z7"
NMAKE : fatal error U1077: "D:\Visual Studio\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe"  /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MDd -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -MP  -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 -I"crypto" -I"." -I"include" -I"providers\common\include" -I"providers\implementations\include" -D"L_ENDIAN" -D"OPENSSL_PIC" -D"OPENSSLDIR=\"D:\\VCPKG\\packages\\openssl_x64-windows\\debug\"" -D"ENGINESDIR=\"D:\\VCPKG\\packages\\openssl_x64-windows\\debug\\lib\\engines-3\"" -D"MODULESDIR=\"D:\\VCPKG\\packages\\openssl_x64-windows\\debug\\bin\"" -D"OPENSSL_BUILDING_OPENSSL" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"DEBUG" -D"_DEBUG"   -DAES_ASM -DBSAES_ASM -DCMLL_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DKECCAK1600_ASM -DMD5_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_USE_APPLINK -DPADLOCK_ASM -DPOLY1305_ASM -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DX25519_ASM -c /Focrypto\libcrypto-shlib-cversion.obj "crypto\cversion.c" : возвращенный код "0x2"
Stop.
NMAKE : fatal error U1077: "D:\Visual Studio\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\nmake.exe" /LU                 _build_libs : возвращенный код "0x2"
Stop.

**Comment by LilyWangLL** [comment]
Please also install the English Language Package on Visual Studio and rebuild port.

**Comment by PROgame557** [comment]
> Please also install the English Language Package on Visual Studio and rebuild port.

Can you please tell me how to do it rebuild port?

**Comment by PROgame557** [comment]
Thanks to everyone who helped!!! I reinstalled Visual Studio and vcpkg and it worked for me! Thank you again!

![image](https://github.com/microsoft/vcpkg/assets/154081543/95a03c0a-9528-438d-a71d-7b724b063231)
