### ISSUE TITLE
1

### ISSUE THREAD

**Issue by dinhtuananhne** [microsoft/vcpkg#36474]
**Describe the bug**

**Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
1. ./vcpkg install xxxx
2. See error
Repro code when

**Expected behavior**

**Failure logs**
-(please attached failure logs)

**Additional context**

**Comment by dinhtuananhne** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **Environment**
> - OS: [e.g. Windows/Linux etc...]
> - Compiler: revision
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. ./vcpkg install xxxx
> 2. See error
> Repro code when
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Failure logs**
> -(please attached failure logs)
> 
> **Additional context**
> Add any other context about the problem here.
> 

@dinhtuananhne @#

**Comment by StarGate-One** [comment]
See #30604 How to report a package build failure.

**Comment by JonLiu1993** [comment]
Ping @dinhtuananhne for response.

**Comment by JonLiu1993** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
