### ISSUE TITLE
Linux ARM / aarch64 support

### ISSUE THREAD

**Issue by TheCycoONE** [microsoft/vcpkg#3647]
Currently ./bootstrap-vcpkg.sh does not attempt to detect architecture, assuming x86_64 on Linux. This means that the bootstrap tools that are fetched cannot run. I see the following output in the terminal:

```
➜  vcpkg git:(corsixth) ./bootstrap-vcpkg.sh 
/home/stephen/github/vcpkg/scripts/bootstrap.sh: line 193: /home/stephen/github/vcpkg/downloads/tools/cmake-3.10.2-linux/cmake-3.10.2-Linux-x86_64/bin/cmake: cannot execute binary file: Exec format error
/home/stephen/github/vcpkg/scripts/bootstrap.sh: line 194: /home/stephen/github/vcpkg/downloads/tools/cmake-3.10.2-linux/cmake-3.10.2-Linux-x86_64/bin/cmake: cannot execute binary file: Exec format error
cp: cannot stat '/home/stephen/github/vcpkg/toolsrc/build.rel/vcpkg': No such file or directory
```

Is there interest from the project in supporting aarch64 (and maybe other architectures?)

**Comment by jarruda** [comment]
Yes indeed there is!  In particular, I started out using vcpkg for a few projects with the hope that it supported ARM to make targeting the Raspberry Pi a possibility.

At the very least, it would be desirable to note this lack of architecture support in the documentation (README or readthedocs).  There is no mention of x86 dependence that I could find.

**Comment by YoDaMa** [comment]
Our team is also very much interested in this feature! Would make deploying to devices significantly simpler.

**Comment by zweistein-frm2** [comment]
vcpkg can be build quite easily on a raspberry pi 
First you must build cmake 3.14 from sources as the raspberry pi buster has 3.13 cmake only.
cmake-3.14 must be the default cmake.

Then simply:
cd /vcpkg   # or where your vcpkg is
mkdir out
cd out
cmake -S /vcpkg/toolsrc  -B /vcpkg/out
cd out
make
cd ..
cp out/vcpkg ./vcpkg

but then triplets have to be defined...

**Comment by meitiever** [comment]
build cmake-3.15 from source and install to /usr/bin and /usr/share
append -useSystemBinaries to command like bootstrap-vcpkg.sh -useSystemBinaries
and then vcpkg will ignore cmake downloading and building process.
this works for me and everything is all right now.

**Comment by bramburn** [comment]
@meitiever thanks steve

**Comment by raix** [comment]
on jetson nano ubuntu 18.04lts is using 3.10.2

**Comment by makitsune** [comment]
On Debian 10, I have to compile CMake 3.14+ from source and `-useSystemBinaries` works when bootstrapping. However when I run `vcpkg install` it'll try to download CMake for x86_64 again.

**Comment by makitsune** [comment]
This works for me for now
- `./bootstrap-vcpkg.sh -useSystemBinaries`
- `VCPKG_FORCE_SYSTEM_BINARIES=1 ./vcpkg install ...`

**Comment by debion** [comment]
Here's how I got it working:
* install vcpkg
```sh
./bootstrap-vcpkg.sh -useSystemBinaries
```
* add the triplet `./triplets/arm64-linux.cmake`:
```cmake
set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
```
* add environment variables:
```sh
export VCPKG_DEFAULT_TRIPLET=arm64-linux
export VCPKG_FORCE_SYSTEM_BINARIES=1
```
* add the `-DVCPKG_TARGET_TRIPLET=arm64-linux` option when using cmake:
```sh
cmake -B [build directory] -S . -DVCPKG_TARGET_TRIPLET=arm64-linux -DCMAKE_TOOLCHAIN_FILE=[path to vcpkg]/scripts/buildsystems/vcpkg.cmake
```

**Comment by linquize** [comment]
Please also improve #12362

**Comment by jagrme00** [comment]
The `./bootstrap-vcpkg.sh -useSystemBinaries` does not work for me on aarch64 Ubuntu 16.04.
My shell hangs up when I press return. Waiting for over a half hour does not produce any output in my shell.
Can anybody help?

**Comment by advra** [comment]
@jagrme00 I am having the same issue with Ubuntu 20.04 shell hangs and nothing happens. Did you ever figure it out?

**Comment by linquize** [comment]
@jagrme00 why sudo?

**Comment by jagrme00** [comment]
> > The `sudo ./bootstrap-vcpkg.sh -useSystemBinaries` does not work for me on aarch64 Ubuntu 16.04.
> > My shell hangs up when I press return. Waiting for over a half hour does not produce any output in my shell.
> > Can anybody help?
> 
> @jagrme00 I am having the same issue with Ubuntu 20.04 shell hangs and nothing happens. Did you ever figure it out?

@advra Unfortunately I had no time to analyze this behavior. Since I needed only a few libraries, I built them from source with CMake.


> @jagrme00 why sudo?

@linquize I'm not a linux expert, but I thought it's better to try it with sudo because I don't know what commands are executed by this script. In addition I was too lazy to look inside the script. As far as  I can see it shouldn't be the reason for the problem. 

The device I was using was based on a NVIDIA Tegra X2. Maybe someone got it running on this platform?

**Comment by linquize** [comment]
@jagrme00
vcpkg minimum requirement is gcc 6. 
Ubuntu 16.04 has only gcc 5.3, which is not supported.

**Comment by jagrme00** [comment]
@linquize Thanks for this information.

**Comment by PhoebeHui** [comment]
Move the discussion to https://github.com/microsoft/vcpkg/discussions/17738.
