### ISSUE TITLE
No HarfBuzz CMake targets given on installation.

### ISSUE THREAD

**Issue by jackxbritton** [Microsoft/vcpkg#3648]
Most package installations give you the CMake targets to include in your CMakeLists.txt. For example, FreeType gives

```
find_package(Freetype REQUIRED)
target_link_libraries(main PRIVATE Freetype::Freetype
```

Harfbuzz gives no such CMake targets.

**Comment by nicole9456** [comment]
Closed the issue, because we can't repro it in the latest build.
![image](https://user-images.githubusercontent.com/46737724/51964390-47460980-241b-11e9-9d5a-e2f1cde06716.png)
