### ISSUE TITLE
libgeotiff:x64-linux build/install error on Ubuntu 18.04 (WSL, gcc 7.3)

### ISSUE THREAD

**Issue by rjoco** [microsoft/vcpkg#3649]
I'm using Ubuntu 18.04 WSL.

Tried to install libgeotiff with "./vcpkg install libgeotiff" but got this error:

/vcpkg/buildtrees/libgeotiff/config-x64-linux-dbg-out.log
/vcpkg/buildtrees/libgeotiff/config-x64-linux-dbg-err.log
Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:247 (vcpkg_execute_required_process)
  ports/libgeotiff/portfile.cmake:30 (vcpkg_configure_cmake)
  scripts/ports.cmake:72 (include)
Error: Building package libgeotiff:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libgeotiff:x64-linux
  Vcpkg version: 0.0.113-unknownhash

Here is the error message from the log file
-- Found LibLZMA: /usr/include (found version "5.2.2")
-- Found TIFF: /home/user/vcpkg/installed/x64-linux/debug/lib/libtiff.a (found version "4.0.9")
-- Looking for TIFFOpen
-- Looking for TIFFOpen - not found
-- Configuring incomplete, errors occurred!

**Comment by dethtoll1** [comment]
I'm running into the same issue on Ubuntu 16.04

**Comment by wangli28** [comment]
Hi @rjoco, thank you for posting the issue. I installed it successfully with VCPKG latest source on Ubuntu 18.04. You can update vcpkg and rebuild. Please open a new issue if this is still a problem for you.
> vwangli@vwangli003:~/test/vcpkg$ ./vcpkg install libgeotiff
The following packages will be built and installed:
/    libgeotiff[core]:x64-linux
/  * libjpeg-turbo[core]:x64-linux
/  * tiff[core]:x64-linux
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: libjpeg-turbo:x64-linux
Building package libjpeg-turbo[core]:x64-linux...
-- Using cached /home/vwangli/test/vcpkg/downloads/libjpeg-turbo-libjpeg-turbo-2.0.1.tar.gz
-- Using source at /home/vwangli/test/vcpkg/buildtrees/libjpeg-turbo/src/2.0.1-ddb48d8b8e
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package libjpeg-turbo[core]:x64-linux... done
Installing package libjpeg-turbo[core]:x64-linux...
Installing package libjpeg-turbo[core]:x64-linux... done
Elapsed time for package libjpeg-turbo:x64-linux: 12.02 s
Starting package 2/3: tiff:x64-linux
Building package tiff[core]:x64-linux...
-- Using cached /home/vwangli/test/vcpkg/downloads/tiff-4.0.10.tar.gz
-- Using source at /home/vwangli/test/vcpkg/buildtrees/tiff/src/4.0.10-fc1d67d447
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Installing: /home/vwangli/test/vcpkg/packages/tiff_x64-linux/share/tiff/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package tiff[core]:x64-linux... done
Installing package tiff[core]:x64-linux...
Installing package tiff[core]:x64-linux... done
Elapsed time for package tiff:x64-linux: 12.55 s
Starting package 3/3: libgeotiff:x64-linux
Building package libgeotiff[core]:x64-linux...
-- Using cached /home/vwangli/test/vcpkg/downloads/libgeotiff-1.4.2.tar.gz
-- Using source at /home/vwangli/test/vcpkg/buildtrees/libgeotiff/src/1.4.2-b7d89dbe60
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package libgeotiff[core]:x64-linux... done
Installing package libgeotiff[core]:x64-linux...
Installing package libgeotiff[core]:x64-linux... done
Elapsed time for package libgeotiff:x64-linux: 4.307 s
/
Total elapsed time: 28.88 s
/
The package libgeotiff:x64-linux provides CMake targets:
/
    find_package(geotiff CONFIG REQUIRED)
    target_link_libraries(main PRIVATE geotiff_library)
