### ISSUE TITLE
[shiftmedia-libgpg-error] build failure

### ISSUE THREAD

**Issue by m-kuhn** [microsoft/vcpkg#36490]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
`./vcpkg install shiftmedia-libgpg-error`
```

### Failure logs

```
CMake Error at ports/shiftmedia-libgpg-error/portfile.cmake:54 (file):
  file RENAME failed to rename

    C:/src/shiftmedia-libgpg-error/x64-windows-rel/error-1.45-995040f7c8.clean/msvc/include

  to

    D:/a/kadas-albireo2/kadas-albireo2/build/_deps/vcpkg-src/packages/shiftmedia-libgpg-error_x64-windows/include

  because: The system cannot move the file to a different disk drive.
```

### Additional context

The error is pretty clear, having the buildtree on a different device than the package triggers the issue.

Changing line 54 in the portfile to ~`file(COPY "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/${SOURCE_PATH_SUFFIX}/msvc/include" DESTINATION "${CURRENT_PACKAGES_DIR}/include")`~ fixes things.

**Comment by m-kuhn** [comment]
> Changing line 54 in the portfile to `file(COPY "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/${SOURCE_PATH_SUFFIX}/msvc/include" DESTINATION "${CURRENT_PACKAGES_DIR}/include")` fixes things.

this is wrong, as it creates a include subdirectory in include, this is correct:

**Comment by jimwang118** [comment]
I used the command `.\vcpkg.exe install shiftmedia-libgpg-error --x-packages-root=d:/vcpkg --x-install-root=D:/install` and did not reproduce the issue. May I ask what command you used to cause this issue?

**Comment by m-kuhn** [comment]
It's built in manifest mode with `-D VCPKG_INSTALL_OPTIONS="--x-buildtrees-root=C:/src" -D VCPKG_TARGET_TRIPLET="x64-windows"` on a github actions runner where everything vcpkg related except the buildtrees lives on `D:`.
