### ISSUE TITLE
[colmap] Build error on x64-windows

### ISSUE THREAD

**Issue by QR930** [microsoft/vcpkg#36500]
Copy issue body from C:/Users/Qianrong/vcpkg/installed/vcpkg/issue_body.md
```[tasklist]
### Tasks
```

**Comment by jimwang118** [comment]
See https://github.com/microsoft/vcpkg/issues/30604 How to report a vcpkg build failure.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
