### ISSUE TITLE
[skia] update to chrome/122

### ISSUE THREAD

**Issue by abique** [microsoft/vcpkg#36517]
### Library name

skia

### New version number

chrome/m122

### Other information that may be useful (release notes, etc...)

Hi,
It seems that skia is currently using the tag `canvaskit/0.38.2` but this seems to be an abandoned pattern by skia.
The latest version should be picked from the branch `chrome/m122`.
Thanks,
Alex

**Comment by FrankXie05** [comment]
Fixed by PR https://github.com/microsoft/vcpkg/pull/36680
