### ISSUE TITLE
OpenSSL install failing on debian 9

### ISSUE THREAD

**Issue by Hoffs** [microsoft/vcpkg#3654]
Hello,

So I have encountered an issue when trying to install OpenSSL on debian 9. Tested on 2 seperate machines, both produce same output. It worked fine on ubuntu machine. 

> -- Build x64-linux-dbg
> CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:170 (message):
>     Command failed: /root/vcpkg/downloads/tools/cmake-3.10.2-linux/cmake-3.10.2-Linux-x86_64/bin/cmake;--build;.;--config;Debug;--target;install;--;-v;-j1
>     Working Directory: /root/vcpkg/buildtrees/openssl/x64-linux-dbg
>     See logs for more information:
>       /root/vcpkg/buildtrees/openssl/install-x64-linux-dbg-out.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
>   ports/openssl/portfile-nonwindows.cmake:23 (vcpkg_install_cmake)
>   ports/openssl/portfile.cmake:30 (include)
>   scripts/ports.cmake:72 (include)
> 
> 
> Error: Building package openssl:x64-linux failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: openssl:x64-linux
>   Vcpkg version: 0.0.113-unknownhash
> 
> Additionally, attach any relevant sections from the log files above.
 

The install seems to be failing because `cp` is not found (?).

> evp_extra_test.c => ../../test/evp_extra_test.c
> /bin/sh: 1: cp: not found
> Makefile:68: recipe for target 'links' failed
> make[2]: *** [links] Error 127
> make[2]: Leaving directory '/root/vcpkg/buildtrees/openssl/x64-linux-dbg/openssl-1.0.2o/crypto/evp'
> Makefile:95: recipe for target 'links' failed
> make[1]: *** [links] Error 1
> make[1]: Leaving directory '/root/vcpkg/buildtrees/openssl/x64-linux-dbg/openssl-1.0.2o/crypto'
> Makefile:446: recipe for target 'links' failed
> make: *** [links] Error 1
> ninja: build stopped: subcommand failed.
>

**Comment by JasonDictos** [comment]
I've encountered this too just now, the line is the makefile in the crypto/evp folder:

links:
        @$(PERL) $(TOP)/util/mklink.pl ../../include/openssl $(EXHEADER)
        @$(PERL) $(TOP)/util/mklink.pl ../../test $(TEST)
        @[ -f $(TESTDATA) ] && cp $(TESTDATA) ../../test && echo "$(TESTDATA) -> ../../test/$(TESTDATA)"
        @$(PERL) $(TOP)/util/mklink.pl ../../apps $(APPS)

I'm running the build through a powershell script on a docker, works fine in a normal linux box however.

**Comment by JasonDictos** [comment]
Looking closer the path is setup like so:

$env:PATH="/usr/bin:/opt/microsoft/powershell/6.1.0~preview.2:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin;/app/deps/vcpkg/downloads/tools/ninja-1.8.2-linux"

Then cp isn't found, cp is in /bin for me so, since /bin is added with a semicolon there for some reason.

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen this issue.
