### ISSUE TITLE
Unable to build the library cppzmq on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by YangRongAtGit** [Microsoft/vcpkg#3655]
Hello,
I installed the vcpkg today to try to use cppzmq library on Ubuntu 16.04. After that I installed cppzmq. 
```
./vcpkg install cppzmq
```
The package cppzmq is successfully installed. Then, a build is created under the project folder. In the build folder, I run:
```
ccmake .. -DCMAKE_TOOLCHAIN_FILE=/home/rong/projects/SGX/code/Test/vcpkg/scripts/buildsystems/vcpkg.cmake
```
Then I pressed the key 'c' to configure the project. The cmake reports errors during the configuration process. It seems CMake dislike the parameter 'LOCATION' in the line `get_target_property(cppzmq_LIBRARY libzmq LOCATION)`. Based on `https://cmake.org/cmake/help/v3.0/policy/CMP0026.html` I think the LOCATION is an pretty old parameter. But I do not know what is the replacement.
```
 CMake Error at vcpkg/installed/x64-linux/share/cppzmq/cppzmqConfig.cmake:59 (get_target_property):
   INTERFACE_LIBRARY targets may only have whitelisted properties.  The
   property "LOCATION" is not allowed.
 Call Stack (most recent call first):
   vcpkg/scripts/buildsystems/vcpkg.cmake:247 (_find_package)
   CMakeLists.txt:4 (find_package)
```
After I exited the error page, It seems that ZeroMQ and cppzmq paths are configured. But there is an another error `_VCPKG_CL-NOTFOUND`

```
 CMAKE_BUILD_TYPE                                                                                                                           
 CMAKE_INSTALL_PREFIX             /usr/local                                                                                                
 VCPKG_APPLOCAL_DEPS              ON                                                                                                        
 VCPKG_TARGET_TRIPLET             x64-linux                                                                                                 
 ZeroMQ_DIR                       /home/rong/projects/SGX/code/Test/vcpkg/installed/x64-linux/share/zeromq                                  
 _VCPKG_CL                        _VCPKG_CL-NOTFOUND                                                                                        
 cppzmq_DIR                       /home/rong/projects/SGX/code/Test/vcpkg/installed/x64-linux/share/cppzmq 

```  

Any suggestions to fix the errors? Thanks :)

**Comment by JonBoyleCoding** [comment]
This is the same issue as #3356. An issue with the original repository's CMake files and a more up-to-date CMake version.

**Comment by NancyLi1013** [comment]
Duplicate to #3356.  And this issue has been fixed.
