### ISSUE TITLE
[Boost] Libraries not found

### ISSUE THREAD

**Issue by Boereck** [microsoft/vcpkg#3658]
I am trying to build an x64 project with Visual Studio 2017, using CMake 3.11.3 and binding a boost (1.67.0) lib via vcpkg (current master).
Unfortunately the boost lib cannot be found. Neither statically, nor dynamically linked. Interestingly, the 
I created a tiny project reproducing the issue:
https://github.com/Boereck/vcpkg-boost-test

The init.ps1 script shows a simple setup process.
The output of the build can be seen here:
https://ci.appveyor.com/project/Boereck/vcpkg-boost-test

In the past there have been several similar issues (like #601 or #604), but it seems currently broken again.

UPDATE: 
I forgot to mention that the include directory is determined correctly, but the libraries cannot be found.

**Comment by raulbocanegra** [comment]
I found a similar issue.
As a workaround I defined BOOST_ROOT to my vcpkg install folder:
set(BOOST_ROOT "${vcpkg_repo}/vcpkg/installed/x64-windows") and it worked.

**Comment by Boereck** [comment]
Thanks for the reply, unfortunately this did not work for me. Neither defined via the CmakeLists.txt nor via command line. I also tried setting BOOST_ROOT to ${vcpkg_repo}/vcpkg/installed/x64-windows/include, which seemed to make more sense, but it made no difference.

**Comment by raulbocanegra** [comment]
The optional library is header only I think. You don't need to specify it on the COMPONENTS. I am not sure if just adding system instead of optional works. Try of that helps you fix that.

**Comment by iso8859** [comment]
Same problem. I give a working solution #3714

**Comment by PhoebeHui** [comment]
This issue hasn’t been updated in a year, if it is still an issue, please reopen.

**Comment by kingstarcraft** [comment]
Same problem with version contorl(https://devblogs.microsoft.com/cppblog/take-control-of-your-vcpkg-dependencies-with-versioning-support/)
```json
{
  "name": "test_boost",
  "version": "1.0.0",
  "dependencies": [
    "python3",
    "boost"
  ],
  "builtin-baseline": "4f778cf094a65f836167eb301bdf62b7ba632c68",
  "overrides": [
    {
      "name": "python3",
      "version": "3.8.3"
    }
  ]
}
```
I have to set BOOST_ROOT in cmake after ```vcpkg --feature-flags="versions" install```, or boost will be not found.
```cmake
set(BOOST_ROOT /mnt/e/test_boost/vcpkg_installed/x64-linux)
```

**Comment by PhoebeHui** [comment]
@kingstarcraft, please create a new issue instead.
