### ISSUE TITLE
[openblas] Build error: vcpkg install armadillo

### ISSUE THREAD

**Issue by kimsijin33** [microsoft/vcpkg#36586]
C:\DEV\vcpkg>vcpkg install armadillo
warning: In the September 2023 release, the default triplet for vcpkg libraries changed from x86-windows to the detected host triplet (x64-windows). For the old behavior, add --triplet x86-windows . To suppress this message, add --triplet x64-windows .
Computing installation plan...
The following packages will be built and installed:
    armadillo:x64-windows -> 12.4.1
  * blas:x64-windows -> 2023-03-25
  * lapack:x64-windows -> 2022-02-22#2
  * lapack-reference[blas-select,core,noblas]:x64-windows -> 3.11.0#1
  * openblas:x64-windows -> 0.3.24
  * vcpkg-gfortran:x64-windows -> 3#3
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\user\AppData\Local\vcpkg\archives in 466 us. Use --debug to see more details.
Installing 1/6 openblas:x64-windows...
Building openblas:x64-windows...
-- Using cached xianyi-OpenBLAS-v0.3.24.tar.gz.
-- Cleaning sources at C:/DEV/vcpkg/buildtrees/openblas/src/v0.3.24-ee812b1bc7.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/DEV/vcpkg/downloads/xianyi-OpenBLAS-v0.3.24.tar.gz
-- Applying patch uwp.patch
-- Applying patch fix-redefinition-function.patch
-- Applying patch install-tools.patch
-- Using source at C:/DEV/vcpkg/buildtrees/openblas/src/v0.3.24-ee812b1bc7.clean
-- Using cached strawberry-perl-5.38.0.1-64bit-portable.zip.
CMake Error at scripts/cmake/vcpkg_extract_archive.cmake:19 (message):
  C:/DEV/vcpkg/downloads/tools/perl/5.38.0.1 was an extraction target, but it
  already exists.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:199 (vcpkg_extract_archive)
  ports/openblas/portfile.cmake:20 (vcpkg_find_acquire_program)
  scripts/ports.cmake:170 (include)

error: building openblas:x64-windows failed with: BUILD_FAILED
Elapsed time to handle openblas:x64-windows: 23 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openblas
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[openblas]+Build+error&body=Copy+issue+body+from+C%3A%2FDEV%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by autoantwort** [comment]
Manually remove the `C:/DEV/vcpkg/downloads` folder and try again

**Comment by jimwang118** [comment]
@kimsijin33 Is your issue solved?

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you
