### ISSUE TITLE
[boost-vcpkg-helpers] Build error on x64-windows

### ISSUE THREAD

**Issue by GaninNikita** [microsoft/vcpkg#36593]
Copy issue body from D:/ФАЙЛЫ НИКИТЫ/boost_1_84_0/Git/vcpkg/installed/vcpkg/issue_body.md

**Comment by StarGate-One** [comment]
Please see #30604 How to report a package build failure [Explanation Video]

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
