### ISSUE TITLE
[boost-serialization] Build error on x64-windows

### ISSUE THREAD

**Issue by themorkov** [microsoft/vcpkg#36592]
error: building boost-serialization:x64-windows failed with: BUILD_FAILED
Elapsed time to handle boost-serialization:x64-windows: 1.3 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.

**Comment by autoantwort** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report an issue.
