### ISSUE TITLE
Help: Using vcpkg in a build machine

### ISSUE THREAD

**Issue by tcw321** [microsoft/vcpkg#3659]
Hi

I don't understand what the best practice is for use of vcpkg for a build machine on Windows. This is for Windows only development. I am doing the following:

I export the vcpkg libraries as a zip file from my developer machine. I create a directory on the build machine to unzip the file.  I like this idea since I can install and compile new libraries on my developer machine and pick what is necessary for the build machine. The build machine does not need to compile the code.

However, the build machine does need to have vcpkg available at the beginning to run "vcpkg integrate install" as the user the build machine will use to install the properties file under Msbuild in Project Files and in the users local app directory.

So we checkout  vcpkg once on the build machine to run "vcpkg integrate install" then delete it. Then using vcpkg exported zip file to update the same vcpkg directory. This seems to work but in a round about way. I only need to have vcpkg.exe available at the beginning.

In the vcpkg-introducing-export-command blog post, at the bottom, it has a brief paragraph about using the exported binaries. If I understand this correctly, I can either use nuget which I have to configure or use the necessary .targets file for advanced scenarios. I don't think I have an advanced scenario, just want the build machine to find and use the third party libraries with vcpkg like the developer machines. It is not clear to me how to use these .target files. I am also not ready to add nuget configuration to my project. 

How are others using vcpkg in a build machine? Does the method above have issues?

Thanks

Tim

**Comment by PhoebeHui** [comment]
This issue hasn’t been updated in a year, if it is still an issue, please reopen.
