### ISSUE TITLE
vcpkg depend-info always uses default-features even default-features: false

### ISSUE THREAD

**Issue by recsater** [microsoft/vcpkg#36604]
**curl vcpkg.json**
```json
{
  "name": "curl",
  "version": "8.5.0",
  "port-version": 1,
  "description": "A library for transferring data with URLs",
  "homepage": "https://curl.se/",
  "license": "curl AND ISC AND BSD-3-Clause",
  "dependencies": [
    {
      "name": "vcpkg-cmake",
      "host": true
    },
    {
      "name": "vcpkg-cmake-config",
      "host": true
    },
    "zlib"
  ],
  "default-features": [
    "non-http",
    "ssl"
  ],
  "features": {
    "brotli": {
      "description": "brotli support (brotli)",
      "dependencies": [
        "brotli"
      ]
    },
    "c-ares": {
      "description": "c-ares support",
      "dependencies": [
        "c-ares"
      ]
    },
#......
```

**custom port(default-features: false)**
```json
{
  "name": "multiport",
  "version": "0.0.1",
  "port-version": 0,
  "description": "Helper port.",
  "dependencies": [
    {
      "name": "curl",
      "features": [],
      "default-features": false
    }
  ]
}
```

**`vcpkg depend-info multiport` result**
![image](https://github.com/microsoft/vcpkg/assets/16009827/aa9c6ac1-8d1c-409d-9ceb-fb5118ed7a7f)

So, even if the default-features is set to false on ports that have default-features, depend-info always outputs results that include default-features for those ports.

![image](https://github.com/microsoft/vcpkg/assets/16009827/61f2c967-16ea-4a34-a562-558b804e16f3)

**Comment by dg0yt** [comment]
Default features cannot be disabled by a **PORT** manifest - i.e. by maintainers.
They can be disabled by command line (classic mode) or **APP** manifest (manifest mode) - i.e. by users.
Related: https://github.com/microsoft/vcpkg/issues/35694 and others.

But `depend-info` cannot handle  multiple args. Alternative:
~~~
vcpkg install --dry-run multiport curl[core]
~~~
(Instead of multiport, this can be tested with curlpp.)

**Comment by JonLiu1993** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by dg0yt** [comment]
> We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

It would be more satisfying if `depend-info` could handle multiple arguments, just as `install` does.
