### ISSUE TITLE
QT's windeployqt not working correctly.

### ISSUE THREAD

**Issue by 0x14307** [microsoft/vcpkg#36606]
**Describe the bug**
windeployqt produces an error saying Qt6Guid.dll is not present in the library folder even though it is present in the build directory for the application.
**Environment**
- OS: Windows 11
- Compiler: MSVC 19.38.33135.0

**To Reproduce**
windeployqt6.exe --qmldir <path_to_qml_sources> <path_to_binary>

**Expected behavior**
windeployqt6.exe would not produce an error.

**Failure logs**
`Warning: Translations will not be available due to the following error.
Cannot open C:/vcpkg/installed/x64-windows/translations/Qt6/catalogs.json
Unable to find dependent libraries of C:\vcpkg\installed\x64-windows\bin\Qt6Guid.dll :Cannot open 'C:/vcpkg/installed/x64-windows/bin/Qt6Guid.dll': The system cannot find the file specified.`

**Additional context**
All versions of windeployqt.exe provide the same error.

**Comment by MonicaLiu0311** [comment]
Can you provide a complete log of the console output?

**Comment by MonicaLiu0311** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!

**Comment by US3RN2ME** [comment]
Still relevant

**Comment by US3RN2ME** [comment]
Here is a full log:

**Comment by US3RN2ME** [comment]
So it founds Qt6Gui.dll but the question is: What is Qt6Guid.dll?
