### ISSUE TITLE
[activemq-cpp] cmake configure failure

### ISSUE THREAD

**Issue by ASxa86** [microsoft/vcpkg#36615]
### Operating system

Windows

### Compiler

MSVC Version 17.8.3

### Steps to reproduce the behavior

```Shell
./vcpkg install activemq-cpp:x64-windows



find_package(activemq-cpp CONFIG REQUIRED)

target_link_libraries(${PROJECT_NAME} PRIVATE
    unofficial::activemq-cpp::apr
    unofficial::activemq-cpp::ws2
    unofficial::activemq-cpp::rpcrt4
    unofficial::activemq-cpp::mswsock
)

`cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake`
```

### Failure logs

```shell
Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.23620.
Compiler ID: MSVC
CMake Error at C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package):
  Found package configuration file:

    ./build/vcpkg_installed/x64-windows/share/activemq-cpp/activemq-cppConfig.cmake

  but it set activemq-cpp_FOUND to FALSE so package "activemq-cpp" is
  considered to be NOT FOUND.  Reason given by package:

  Activemq-cpp vcpkg install dependency failure: Did not find windows
  dependencies: WS2_32.lib, RpcRT4.lib, MsWsock.lib

Call Stack (most recent call first):
  myProject/CMakeLists.txt:326 (find_package)


Configuring incomplete, errors occurred!
```

### Additional context

I dug into this a little bit. It looks like the included `build\vcpkg_installed\x64-windows\share\activemq-cpp\activemq-cppConfig.cmake` from vcpkg is attempting to look for Windows SDK libraries via `find_library` and is failing to do so.

```cmake
# Macro to find OS dependencies for windows builds.
# Sets up for failure find_package() failure if dependencies not found.
# On success, creates targets unofficial::activemq-cpp::ws2, unofficial::activemq-cpp::rpcrt4, and unofficial::activemq-cpp::mswsock.
# Sets boolean ${CMAKE_FIND_PACKAGE_NAME}_WINDOWS_DEPENDENCIES_FOUND to TRUE or FALSE to indicate success or failure.
macro(_activemq_cpp_windows_dependencies)
    find_library(ACTIVEMQ_CPP_LIBWS2 WS2_32)
    find_file(ACTIVEMQ_CPP_DLLWS2 WS2_32.dll)
    find_library(ACTIVEMQ_CPP_LIBRPCRT4 RpcRT4)
    find_file(ACTIVEMQ_CPP_DLLRPCRT4 RpcRT4.dll)
    find_library(ACTIVEMQ_CPP_LIBMSWSOCK MsWsock)
    find_file(ACTIVEMQ_CPP_DLLMSWSOCK MsWsock.dll)
```

I don't know if this is expecting the SDK to be in my path or not but I typically have never had to worry about this. I did confirm the libraries exist at `C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22000.0\um\x64` on my local machine. I also confirmed I can link against them in Visual Studio via:

```cmake
target_link_libraries(${PROJECT_NAME} PRIVATE
    WS2_32
    RpcRT4
    MsWsock
)
```

So, while I have the libraries and can link against them via cmake. It seems like `activemq-cppConfig.cmake` doesn't understand how to find them.

**Comment by jimwang118** [comment]
Manually remove the C:/DEV/vcpkg/downloads folder and try again. If this does not help don't use C:/dev since this is /dev for unix tools which is not a normal folder

**Comment by dg0yt** [comment]
> don't use C:/dev since this is /dev for unix tools

Pardon?

**Comment by jimwang118** [comment]
> > don't use C:/dev since this is /dev for unix tools
> 
> Pardon?

I misread the error message.
I reproduced this problem locally and created the same path as the author. No errors were reported when compiling and using it. I haven't reproduced this issue.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.

**Comment by ASxa86** [comment]
Maybe I am missing something then. I've been banging my head against this and I cannot get this to work. I even tried just calling `find_package(WS_LIB WS2_32)` in a brand new cmake project:

```cmake
cmake_minimum_required(VERSION 3.27)

project(test)

add_executable(${PROJECT_NAME})

target_sources(${PROJECT_NAME} PRIVATE
    main.cpp
)

find_library(WS_LIB WS2_32)

```

The library cannot be found. It exists on my machine. Is there some other environment configuration that is expected that I am not catching? I thought `find_library` required path hints to find packages but the activemq cmake doesn't use them.

`"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64\WS2_32.Lib"` exists.

**Comment by ASxa86** [comment]
Yeah. I'm just trying to figure out how that activemq-cppConfig.cmake file is supposed to work and why the issue can't be reproduced. I'm having the problem on multiple PCs. Makes me think I'm missing a prerequisite.

**Comment by ASxa86** [comment]
I am doing just that. That's what I commented above. A super simple config file that links to ws2_32 directly. That works. The issues is activemq tries to run `find_library` as I described above and fails. So, I try to run `find_library` myself and confirms it fails.

**Comment by generaltoto** [comment]
Hey @ASxa86, I have just encountered the same problem a few minutes ago. Did you solve this problem by any chance ? 

I am also posting my error even if we do have the same 
```bash
CMake Error at C:[root]/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package):
  Found package configuration file:

    C:[root]/GLTF_GENERATOR/GLTF_APP/build/vcpkg_installed/x64-windows/share/activemq-cpp/activemq-cppConfig.cmake

  but it set activemq-cpp_FOUND to FALSE so package "activemq-cpp" is
  considered to be NOT FOUND.  Reason given by package:

  Activemq-cpp vcpkg install dependency failure: Did not find windows
  dependencies: WS2_32.lib, RpcRT4.lib, MsWsock.lib

Call Stack (most recent call first):
  CMakeLists.txt:24 (find_package)


-- Configuring incomplete, errors occurred!
```

I am on Windows as well using Visual Studio 17 2022

**Comment by ASxa86** [comment]
I never found the root cause but I can say it's only an issue on my work provided laptop. It works fine on my personal PC and laptop.

**Comment by generaltoto** [comment]
"It works on my machine" huh ;-;

Thank you for your response, I will continue digging. Could you send me your vcpkg.json and CMakeList.txt if you still have them ? It might help tracking the root cause

**Comment by ASxa86** [comment]
Unfortunately, I don't have access to my work machines anymore as I recently left the company. That being said, I was just using a simple vcpkg.json with "activemq-cpp" as the dependency to try and track this down. My work around was to manually set the variables that activemq-cppConfig.cmake was trying to define.

**Comment by generaltoto** [comment]
I posted a new issue on the same repository, we'll see what comes of it. 

Setting the variables could do the trick, but I can't use this as a finally solution. I am working in a Docker environnement, which means I would have to set the variable manually every time I deploy my app ...

I'll let you know if I get any news on this issue
