### ISSUE TITLE
[boost-build] Build error on x64-linux

### ISSUE THREAD

**Issue by guenterberner** [microsoft/vcpkg#36611]
Package: boost-build:x64-linux@1.84.0

**Host Environment**

- Host: x64-linux
- Compiler: GNU 13.2.1
-    vcpkg-tool version: 2024-02-05-9c1e418fc6264dffcab6ca47746a648c35c379b9
    vcpkg-scripts version: 42bb0d9e8 2024-02-05 (13 hours ago)

**To Reproduce**

`vcpkg install boost`
**Failure logs**

```
-- Using cached boostorg-build-boost-1.84.0.tar.gz.
-- Cleaning sources at /home/gbe/dev/vcpkg-gcc13/buildtrees/boost-build/src/ost-1.84.0-af9524982d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/gbe/dev/vcpkg-gcc13/downloads/boostorg-build-boost-1.84.0.tar.gz
-- Applying patch 0002-fix-get-version.patch
-- Applying patch 0003-fix-emscripten.patch
-- Applying patch 0004-workaround-MSVC-codegen-bug-in-17.5-on-ARM64.patch
-- Using source at /home/gbe/dev/vcpkg-gcc13/buildtrees/boost-build/src/ost-1.84.0-af9524982d.clean
-- Using cached boost_LICENSE_1_0.txt.
-- Using cached boost-1.84.0-boostcpp.jam.
-- Installing: /home/gbe/dev/vcpkg-gcc13/packages/boost-build_x64-linux/share/boost-build/copyright
-- Bootstrapping...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /home/gbe/dev/vcpkg-gcc13/packages/boost-build_x64-linux/tools/boost-build/bootstrap.sh
    Working Directory: /home/gbe/dev/vcpkg-gcc13/packages/boost-build_x64-linux/tools/boost-build
    Error code: 1
    See logs for more information:
      /home/gbe/dev/vcpkg-gcc13/buildtrees/boost-build/bootstrap-x64-linux-out.log
      /home/gbe/dev/vcpkg-gcc13/buildtrees/boost-build/bootstrap-x64-linux-err.log

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:71 (vcpkg_execute_required_process)
  scripts/ports.cmake:170 (include)



```
<details><summary>/home/gbe/dev/vcpkg-gcc13/buildtrees/boost-build/bootstrap-x64-linux-out.log</summary>

```
Building the B2 engine..
```
</details>

<details><summary>/home/gbe/dev/vcpkg-gcc13/buildtrees/boost-build/bootstrap-x64-linux-err.log</summary>

```

Could not find a suitable toolset.

You can specify the toolset as the argument, i.e.:
    ./build.sh [options] gcc

Toolsets supported by this script are:
    acc, clang, como, gcc, intel-darwin, intel-linux, kcc, kylix, mipspro,
    pathscale, pgi, qcc, sun, sunpro, tru64cxx, vacpp

For any toolset you can override the path to the compiler with the '--cxx'
option. You can also use additional flags for the compiler with the
'--cxxflags' option.

A special toolset; cxx, is available which is used as a fallback when a more
specific toolset is not found and the cxx command is detected. The 'cxx'
toolset will use the '--cxx' and '--cxxflags' options, if present.

Options:
    --help                  Show this help message.
    --verbose               Show messages about what this script is doing.
    --debug                 Build b2 with debug information, and no
                            optimizations.
    --guess-toolset         Print the toolset we can detect for building.
    --cxx=CXX               The compiler exec to use instead of the detected
                            compiler exec.
    --cxxflags=CXXFLAGS     The compiler flags to use in addition to the
                            flags for the detected compiler.


Failed to build the B2 engine.
```
</details>

**Comment by autoantwort** [comment]
Have you done https://github.com/microsoft/vcpkg?tab=readme-ov-file#installing-linux-developer-tools ?

**Comment by guenterberner** [comment]
Yes. Although I'm not a vcpkg newbie, I double-checked all the relevant points in the readme file.

I have already successfully installed boost and many other vcpkg ports on MacOS (apple-clang-15), Windows 11 (VS 2022 17.8.6) and SLES12 SP5 (gcc8, gcc-13; both from SLES toolchain).
Even on SLES15 SP5 (gcc-13) I managed to install many other packages.
Only the boost build is stuck.

I would be grateful for any advice on how I can support the analysis.

**Comment by yurybura** [comment]
@guenterberner Please attach full logs:
/home/gbe/dev/vcpkg-gcc13/buildtrees/boost-build/bootstrap-x64-linux-out.log
/home/gbe/dev/vcpkg-gcc13/buildtrees/boost-build/bootstrap-x64-linux-err.log

**Comment by guenterberner** [comment]
Hello @yurybura here are the requested files

[bootstrap-x64-linux-err.log](https://github.com/microsoft/vcpkg/files/14221477/bootstrap-x64-linux-err.log)
[bootstrap-x64-linux-out.log](https://github.com/microsoft/vcpkg/files/14221478/bootstrap-x64-linux-out.log)

**Comment by guenterberner** [comment]
Well, I found the problem on this specific workstation and was able to fix it.

While looking for a c++11 compiler (which is required to build the boost build tool), the boost build.sh looks for "real" compiler executables (i.e. g++) in the PATH and _ignores_ CC and CXX environment variables.
