### ISSUE TITLE
[mongo-c-driver] <opnssl-version fix>

### ISSUE THREAD

**Issue by floatval** [microsoft/vcpkg#36610]
### Is your feature request related to a problem? Please describe.

OS:
debian 10

vcpkg version : 
master

now mongo-c-dirver port will be install dependise openssl #3.2.0#2 linux.
but libssl.a not has symbol named: "RAND_bytes" and so on..

this is nm print:

 nm installed/x64-linux/lib/libssl.a | grep RAND_bytes
                 U RAND_bytes_ex
                 U RAND_bytes_ex
                 U RAND_bytes_ex
                 U RAND_bytes_ex
                 U RAND_bytes_ex
                 U RAND_bytes_ex
                 U RAND_bytes_ex
                 
extractly, there not that which name RAND_bytes. but RAND_bytes_ex

### Proposed solution

I hopt mongoc will depend right verion openssl....

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Now `openssl` has the related codes of `RAND_bytes`: https://github.com/openssl/openssl/blob/1751185154ab1f1a796e0f39567fe51c8e24b78d/include/openssl/rand.h#L61C5-L61C15.

Could you please provide the more information about the usage of `RAND_bytes` and `RAND_bytes_ex`? For example, undefined symbols error in project and so on. Now, the version of `mongo-c-driver` and `openssl` in vcpkg are the latest.

**Comment by floatval** [comment]
Thank you very much for your reply, I am now home for the Spring Festival, there is no environment around me, after the holiday, I will submit the relevant information as soon as possible. At the same time, I would like to wish you a happy Chinese New Year

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue with more info if this is still a problem for you.
