### ISSUE TITLE
[<port name>] build failure

### ISSUE THREAD

**Issue by shangle-web** [microsoft/vcpkg#36628]
### Operating system

windows11

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
.\vcpkg install boost
```

### Failure logs

error: building boost-test:x64-windows failed with: BUILD_FAILED
Elapsed time to handle boost-test:x64-windows: 11 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-test
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[boost-test]+Build+error+on+x64-windows&body=Copy+issue+body+from+D%3A%2Fproject%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

cl : Command line warning D9025 : overriding '/W3' with '/W4'
execution_monitor.cpp
D:\project\vcpkg\buildtrees\boost-test\src\ost-1.84.0-acb3af280f.clean\include\boost\test\impl\execution_monitor.ipp(1518) : fatal error C1001: Internal compiler error.
(compiler file 'D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 234)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com 
Please choose the Technical Support command on the Visual C++ 
 Help menu, or open the Technical Support help file for more information

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Could you please provide your Visual Studio version and the full log file?

**Comment by shangle-web** [comment]
Successfully reinstalled multiple times
