### ISSUE TITLE
Feature request: print errors and warnings to STDERR

### ISSUE THREAD

**Issue by pravic** [microsoft/vcpkg#3662]
There is a (pretty usual) use case to call `curl -q something | vcpkg hash | gclip` which gives a bunch of warnings among with hash in clipboard.

In general, it is common practice to print errors to `stderr`. 

The only concert here: it will be a breaking change for third tools that parse vcpkg's output. But I doubt that they would rely on the "Different source is available for vcpkg..." warning message, for example.

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen this issue.
