### ISSUE TITLE
[libiconv] Build error on x64-windows

### ISSUE THREAD

**Issue by StigmataRose** [microsoft/vcpkg#36621]
First time reporting an issue on github.
I've noticed a few other people had a similar issue a few months back.

However, changing permissions, running in administrator mode, and updating Visual Studio 2022 results in the same error. Am I missing something?

Thank you,

error: building libiconv:x64-windows failed with: BUILD_FAILED
`CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Users/Skyler Crank/Documents/vcpkg/vcpkg/downloads/tools/msys2/52c8bb2635a5bae2/usr/bin/bash.exe" --noprofile --norc --debug -c "V=1 CPP='compile cl.exe -E' CC='compile cl.exe' CC_FOR_BUILD='compile cl.exe' CPP_FOR_BUILD='compile cl.exe -E' CXX_FOR_BUILD='compile cl.exe' CXX='compile cl.exe' RC='windres-rc rc.exe' WINDRES='windres-rc rc.exe' AR='ar-lib lib.exe' LD='link.exe -verbose' RANLIB=':' STRIP=':' NM='dumpbin.exe -symbols -headers' DLLTOOL='link.exe -verbose -dll' CCAS=':' AS=':' ./../src/v1.17-84a471678e.clean/configure --build=x86_64-pc-mingw32 \"--enable-extra-encodings\" \"--without-libiconv-prefix\" \"--without-libintl-prefix\" \"--enable-relocatable\" \"ac_cv_prog_ac_ct_STRIP=:\" \"gl_cv_double_slash_root=yes\" \"ac_cv_func_memmove=yes\" \"--disable-silent-rules\" \"--verbose\" \"--enable-shared\" \"--disable-static\" \"--prefix=/C/Users/Skyler Crank/Documents/vcpkg/vcpkg/installed/x64-windows/debug\" \"--bindir=\\${prefix}/../tools/libiconv/debug/bin\" \"--sbindir=\\${prefix}/../tools/libiconv/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/libiconv\""
    Working Directory: C:/Users/Skyler Crank/Documents/vcpkg/vcpkg/buildtrees/libiconv/x64-windows-dbg
    Error code: 2
    See logs for more information:`

**Comment by StigmataRose** [comment]
`Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:862 (vcpkg_execute_required_process)
  ports/libiconv/portfile.cmake:29 (vcpkg_configure_make)
  scripts/ports.cmake:170 (include)`

**Comment by StigmataRose** [comment]
This issue was fixed by building without any spaces in the directory

**Comment by MonicaLiu0311** [comment]
Please provide the full log of console output, thank you.

**Comment by MonicaLiu0311** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
