### ISSUE TITLE
[directxmath] Build error on x64-windows

### ISSUE THREAD

**Issue by PR5GRAMM2R** [microsoft/vcpkg#36634]
Copy issue body from C:/Users/pon07/바탕 화면/vcpkg/installed/vcpkg/issue_body.md

================================================================================

C:\Users\pon07\바탕 화면\vcpkg>vcpkg install directxtk:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * directxmath:x64-windows@2023-12-31
    directxtk:x64-windows@2023-12-31
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\pon07\AppData\Local\vcpkg\archives in 137 us. Use --debug to see more details.
Installing 1/2 directxmath:x64-windows@2023-12-31...
Building directxmath:x64-windows@2023-12-31...
-- Downloading https://github.com/Microsoft/DirectXMath/archive/dec2023.tar.gz -> Microsoft-DirectXMath-dec2023.tar.gz...

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 지정된 파일을 찾을 수 없습니다
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/directxmath/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:170 (include)

error: building directxmath:x64-windows failed with: BUILD_FAILED
Elapsed time to handle directxmath:x64-windows: 57 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+directxmath
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[directxmath]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2FUsers%2Fpon07%2F%EB%B0%94%ED%83%95%20%ED%99%94%EB%A9%B4%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

=================================================================================

Error occured.

**Comment by FrankXie05** [comment]
@PR5GRAMM2R Can you access this link manually? https://github.com/Microsoft/DirectXMath/archive/dec2023.tar.gz

**Comment by PR5GRAMM2R** [comment]
I'll try this, thanks.


2024년 2월 7일 (수) 오후 6:48, Frank ***@***.***>님이 작성:
