### ISSUE TITLE
private repository random failure in vcpkg_cmake_config_fixup()

### ISSUE THREAD

**Issue by diehard2** [microsoft/vcpkg#36640]
**Describe the bug**
Randomly, and on different ports, I recently started getting "Did not find a debug configuration for target". It succeeds when I run it again. my vcpkg is from hash 2b681d95e08447fde261b4404fbeab324f7d1e5b. There were no logs, just the following message. I'm not even sure how to trouble shoot this

-- Building x64-linux-dbg
-- Building x64-linux-rel
CMake Error at /home/dev/permanent_data/temp/vcpkg_installed/x64-linux/share/vcpkg-cmake-config/vcpkg_cmake_config_fixup.cmake:171 (message):
  Did not find a debug configuration for target
  'myport::myport'.
Call Stack (most recent call first):
  /home/dev/permanent_data/temp/myrepo-repository/ports/myport/portfile.cmake:24 (vcpkg_cmake_config_fixup)
  scripts/ports.cmake:170 (include)

**Environment**
- OS: Ubuntu 22.04
- Compiler: gcc 14

**To Reproduce**
Random

**Expected behavior**
Doesn't fail

**Comment by diehard2** [comment]
@MonicaLiu0311  I can't reproduce it, its random and it started happening recently. There's no logfile to even send. What can I do here to provide you the information? it succeeds the second time I run it, but that doesn't help in a CI system

**Comment by MonicaLiu0311** [comment]
I haven't reproduced it any time, sorry, maybe waiting for someone with the same problem to provide more information...
