### ISSUE TITLE
[<GDAL>] build failure

### ISSUE THREAD

**Issue by shangle-web** [microsoft/vcpkg#36644]
### Operating system

windows11

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
.\vcpkg.exe install gdal
```

### Failure logs

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/14200601/install-x64-windows-dbg-out.log)

### Additional context

PS D:\project\vcpkg> .\vcpkg.exe install gdal
warning: In the September 2023 release, the default triplet for vcpkg libraries changed from x86-windows to the detected host triplet (x64-windows). For the old behavior, add --triplet x86-windows . To suppress this message, add --triplet x64-windows .
Computing installation plan...
The following packages will be built and installed:
    gdal[core,curl,default-features,expat,geos,gif,hdf5,iconv,jpeg,lerc,libkml,libspatialite,libxml2,lzma,netcdf,openjpeg,openssl,pcre2,png,postgresql,qhull,recommended-features,sqlite3,webp,zstd]:x64-windows@3.8.3
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\98477\AppData\Local\vcpkg\archives in 78.2 us. Use --debug to see more details.
Installing 1/1 gdal[core,curl,default-features,expat,geos,gif,hdf5,iconv,jpeg,lerc,libkml,libspatialite,libxml2,lzma,netcdf,openjpeg,openssl,pcre2,png,postgresql,qhull,recommended-features,sqlite3,webp,zstd]:x64-windows@3.8.3...
Building gdal[core,curl,default-features,expat,geos,gif,hdf5,iconv,jpeg,lerc,libkml,libspatialite,libxml2,lzma,netcdf,openjpeg,openssl,pcre2,png,postgresql,qhull,recommended-features,sqlite3,webp,zstd]:x64-windows@3.8.3...
-- Using cached OSGeo-gdal-v3.8.3.tar.gz.
-- Cleaning sources at D:/project/vcpkg/buildtrees/gdal/src/v3.8.3-3cf88842fd.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/project/vcpkg/downloads/OSGeo-gdal-v3.8.3.tar.gz
-- Applying patch find-link-libraries.patch
-- Applying patch fix-gdal-target-interfaces.patch
-- Applying patch libkml.patch
-- Applying patch target-is-valid.patch
-- Using source at D:/project/vcpkg/buildtrees/gdal/src/v3.8.3-3cf88842fd.clean
-- Found external ninja('1.11.1').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files (x86)/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j29
    Working Directory: D:/project/vcpkg/buildtrees/gdal/x64-windows-dbg
    See logs for more information:
      D:\project\vcpkg\buildtrees\gdal\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/gdal/portfile.cmake:106 (vcpkg_cmake_install)
  scripts/ports.cmake:170 (include)

error: building gdal:x64-windows failed with: BUILD_FAILED
Elapsed time to handle gdal:x64-windows: 27 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+gdal
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[gdal]+Build+error+on+x64-windows&body=Copy+issue+body+from+D%3A%2Fproject%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by FrankXie05** [comment]
```
D:\project\vcpkg\buildtrees\gdal\src\v3.8.3-3cf88842fd.clean\frmts\raw\ctable2dataset.cpp : fatal error C1001: Internal compiler error.
(compiler file 'D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 234)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com 
Please choose the Technical Support command on the Visual C++ 
 Help menu, or open the Technical Support help file for more information
 ```
@shangle-web Thanks for posting this issue, please use the Visual stuido version no less than 17.7.
https://developercommunity.visualstudio.com/t/C1001--CompilerUtcsrcp2mainc-line/10323268?q=Utc%5Csrc%5Cp2%5Cmain.c

**Comment by shangle-web** [comment]
My version is 17.8


&nbsp;


984777388
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月8日(星期四) 上午10:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [microsoft/vcpkg] [<GDAL&gt;] build failure (Issue #36644)





 D:\project\vcpkg\buildtrees\gdal\src\v3.8.3-3cf88842fd.clean\frmts\raw\ctable2dataset.cpp : fatal error C1001: Internal compiler error. (compiler file 'D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 234)  To work around this problem, try simplifying or changing the program near the locations listed above. If possible please provide a repro here: https://developercommunity.visualstudio.com  Please choose the Technical Support command on the Visual C++   Help menu, or open the Technical Support help file for more information  
@shangle-web Thanks for posting this issue, please use the Visual stuido version no less than 17.7.
 https://developercommunity.visualstudio.com/t/C1001--CompilerUtcsrcp2mainc-line/10323268?q=Utc%5Csrc%5Cp2%5Cmain.c

**Comment by shangle-web** [comment]
I upgraded to the latest VS version and just rebuilt
