### ISSUE TITLE
[qtbase] Reduce amount of x64-windows compilation when building for other Windows architectures

### ISSUE THREAD

**Issue by ajtribick** [microsoft/vcpkg#36655]
### Is your feature request related to a problem? Please describe.

When installing qtbase for x86-windows or arm64-windows on an x64-windows machine (e.g. the GitHub Windows runners), it also builds qtbase with default components for this architecture. For example, running `vcpkg install qtbase[core]:x86-windows` installs

```
qtbase[brotli,concurrent,core,dbus,default-features,doubleconversion,freetype,gui,harfbuzz,icu,jpeg,network,opengl,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,thread,widgets,zstd]:x64-windows
```

...and also the various x64-windows library dependencies of that. Is all that actually necessary for the x86-windows build?

### Proposed solution

Either eliminate the need to build the x64-windows version entirely when building x86-windows or arm64-windows on an x64-windows machine. or reduce the necessary components of such a build as much as possible (e.g. building just `qtbase[core]:x64-windows`).

**Comment by Osyotr** [comment]
Vcpkg installs default features unless you explicitly asked for `core`. It's not clear whether we need this behavior for host triplet in cross builds.
Use `vcpkg install qtbase[core]:x86-windows qtbase[core]:x64-windows` in the meantime.

**Comment by Neumann-A** [comment]
probably better to use `vcpkg install qtbase --host-triplet=x86-windows`. This way x86 is not considered a cross build

**Comment by jimwang118** [comment]
@ajtribick Can your issue be solved according to Neumann-A's suggestions?

**Comment by ajtribick** [comment]
Yes for now this is fine.
