### ISSUE TITLE
[devil] Build error on x64-freebsd

### ISSUE THREAD

**Issue by flourinekk** [microsoft/vcpkg#36653]
Hello, devil needs an update with removal of register keyboard cause while i use ./vcpkg install devil i got a problem with 

/home/vcpkg/buildtrees/devil/src/v1.8.0-13a02e996b.clean/DevIL/src-IL/src/il_manip.cpp:40:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register int s =  (i >> 16) & 0x00008000;
        ^~~~~~~~~
/home/vcpkg/buildtrees/devil/src/v1.8.0-13a02e996b.clean/DevIL/src-IL/src/il_manip.cpp:41:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register int e = ((i >> 23) & 0x000000ff) - (127 - 15);
        ^~~~~~~~~
/home/vcpkg/buildtrees/devil/src/v1.8.0-13a02e996b.clean/DevIL/src-IL/src/il_manip.cpp:42:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register int m =   i        & 0x007fffff;
        ^~~~~~~~~

**Comment by FrankXie05** [comment]
@flourinekk In C++17, although the keyword `register` is still legal, but it has lost most of its effect. It should be ignored and no warning should be issued not `-Wregister`. 🧐

https://isocpp.org/files/papers/n4340.html

**Comment by flourinekk** [comment]
Created a patch for it so it can be alternatively added : 
diff --git DevIL/src-IL/src/il_manip.cpp DevIL/src-IL/src/il_manip.cpp
index 79acc99..229a692 100644
--- a/DevIL/src-IL/src/il_manip.cpp
+++ b/DevIL/src-IL/src/il_manip.cpp
@@ -37,9 +37,9 @@ ILushort ILAPIENTRY ilFloatToHalf(ILuint i) {
 	// of float and half (127 versus 15).
 	//
 
-	register int s =  (i >> 16) & 0x00008000;
-	register int e = ((i >> 23) & 0x000000ff) - (127 - 15);
-	register int m =   i        & 0x007fffff;
+	int s =  (i >> 16) & 0x00008000;
+	int e = ((i >> 23) & 0x000000ff) - (127 - 15);
+	int m =   i        & 0x007fffff;
 
 	//
 	// Now reassemble s, e and m into a half:
-- 
2.25.1.windows.1
