### ISSUE TITLE
Dependency graph as new command

### ISSUE THREAD

**Issue by martin-s** [Microsoft/vcpkg#3665]
I would like to add a new command that builds up the dependency graph in dgml format. As I have seen, there is already a basic dot implementation in the search command (is already marked as wrong-placed). The pull request would add a new command to combine both graph implementations like:
`vcpkg graph --dot` # prints out the graph in dot syntax
`vcpkg graph --dgml` # prints out the graph in dgml XML syntax

An example is attached to this issue based on the current port files.
[vcpkg.zip](https://github.com/Microsoft/vcpkg/files/2074318/vcpkg.zip)

Another option would be to include it into the depend-info command.

**Comment by martin-s** [comment]
Just as a remark for VS 2017:
https://developercommunity.visualstudio.com/content/problem/24379/vs-2017-professional-can-no-longer-open-dgml-files.html

**Comment by WimLeflere** [comment]
The command that is implemented is `depend-info`, not `graph`. 
E.g. `vcpkg depend-info ffmpeg --dgml`

**Comment by VioletGiraffe** [comment]
This command does not seem to be listed in the docs (https://vcpkg.io/en/docs/README.html), only discoverable via this issue.

**Comment by WimLeflere** [comment]
I've created a PR to update the documentation: #29477
