### ISSUE TITLE
[boost-build] Build error on arm64-osx

### ISSUE THREAD

**Issue by Kaixin1110** [microsoft/vcpkg#36668]
error: building boost-build:arm64-osx failed with: BUILD_FAILED
Elapsed time to handle boost-build:arm64-osx: 2 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-build

**Comment by yurybura** [comment]
@Kaixin1110 Please attach log-files mentioned in your error message.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
