### ISSUE TITLE
grpc 64 bit build error

### ISSUE THREAD

**Issue by davidnoy** [Microsoft/vcpkg#3668]
Package: grpc:x64-windows-static
  Vcpkg version: 0.0.103-unknownhash
try to install i wrote
 "install grpc --triplet x64-windows-static"
and got this error
Error: Building package grpc:x64-windows-static failed with: BUILD_FAILED

**Comment by davidnoy** [comment]
CMake Error at C:/Users/davidno/Downloads/vcpkg/downloads/cmake-3.10.2-win32-x86/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137
 (message):
  
Could NOT find ZLIB 
(missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)

Call Stack (most recent call first):

C:/Users/davidno/Downloads/vcpkg/downloads/cmake-3.10.2-win32-x86/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
 
C:/Users/davidno/Downloads/vcpkg/downloads/cmake-3.10.2-win32-x86/share/cmake-3.10/Modules/FindZLIB.cmake:112 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  
C:/Users/davidno/Downloads/vcpkg/scripts/buildsystems/vcpkg.cmake:227 (_find_package)
  
CMakeLists.txt:126 (find_package)

**Comment by PhoebeHui** [comment]
@davidnoy does the issue still persist? I can installed it successfully now.

 F:\vcpkg\src> .\vcpkg version
Vcpkg package management program version 2018.11.23-nohash

PS F:\vcpkg\src> .\vcpkg install grpc:x64-windows-static
The following packages will be built and installed:
  * c-ares[core]:x64-windows-static
    grpc[core]:x64-windows-static
  * protobuf[core]:x64-windows-static
Additional packages (*) will be modified to complete this operation.
...
Building package grpc[core]:x64-windows-static... done
Installing package grpc[core]:x64-windows-static...
Installing package grpc[core]:x64-windows-static... done
Elapsed time for package grpc:x64-windows-static: 8.815 min

Total elapsed time: 14.05 min

The package grpc:x64-windows-static provides CMake targets:

    find_package(gRPC CONFIG REQUIRED)
    # Note: 9 target(s) were omitted.
    target_link_libraries(main PRIVATE gRPC::gpr gRPC::grpc gRPC::grpc++ gRPC::grpc_cronet)

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
