### ISSUE TITLE
ompl[app] build failure

### ISSUE THREAD

**Issue by Captain-Freels** [microsoft/vcpkg#36688]
### Operating system

Windows 11

### Compiler

Visual Studio 2019 -Administrator: ROS Noetic (I think, I'm new to this)

### Steps to reproduce the behavior

```Shell
C:\>vcpkg install ompl[app]
```

### Failure logs

C:\>vcpkg install ompl[app]
Computing installation plan...
The following packages will be built and installed:
  * assimp[core]:x64-windows
  * boost-bimap[core]:x64-windows
  * boost-chrono[core]:x64-windows
  * boost-compute[core]:x64-windows
  * boost-date-time[core]:x64-windows
  * boost-dynamic-bitset[core]:x64-windows
  * boost-format[core]:x64-windows
  * boost-graph[core]:x64-windows
  * boost-iostreams[core]:x64-windows
  * boost-lexical-cast[core]:x64-windows
  * boost-locale[core]:x64-windows
  * boost-math[core]:x64-windows
  * boost-mp11[core]:x64-windows
  * boost-multi-array[core]:x64-windows
  * boost-multi-index[core]:x64-windows
  * boost-multiprecision[core]:x64-windows
  * boost-odeint[core]:x64-windows
  * boost-parameter[core]:x64-windows
  * boost-phoenix[core]:x64-windows
  * boost-pool[core]:x64-windows
  * boost-program-options[core]:x64-windows
  * boost-property-map[core]:x64-windows
  * boost-property-tree[core]:x64-windows
  * boost-proto[core]:x64-windows
  * boost-random[core]:x64-windows
  * boost-ratio[core]:x64-windows
  * boost-rational[core]:x64-windows
  * boost-serialization[core]:x64-windows
  * boost-spirit[core]:x64-windows
  * boost-test[core]:x64-windows
  * boost-thread[core]:x64-windows
  * boost-timer[core]:x64-windows
  * boost-tokenizer[core]:x64-windows
  * boost-tti[core]:x64-windows
  * boost-ublas[core]:x64-windows
  * boost-units[core]:x64-windows
  * boost-uuid[core]:x64-windows
  * boost-variant[core]:x64-windows
  * boost-xpressive[core]:x64-windows
  * bzip2[core]:x64-windows
  * ccd[core]:x64-windows
  * eigen3[core]:x64-windows
  * fcl[core]:x64-windows
  * liblzma[core]:x64-windows
  * minizip[core]:x64-windows
  * octomap[core]:x64-windows
    ompl[app,core]:x64-windows
  * rapidjson[core]:x64-windows
  * zlib[core]:x64-windows
  * zstd[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Starting package 1/50: zlib:x64-windows
Building package zlib[core]:x64-windows...
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\ed\ed6a14ea759ee5df6a3d272385beb6b307f14f15.zip
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz...
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://downloads.sourceforge.net/project/libpng/zlib/1.2.11/zlib-1.2.11.tar.gz...
-- Extracting source C:/opt/ros/noetic/x64/tools/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Using source at C:/opt/ros/noetic/x64/tools/vcpkg/buildtrees/zlib/src/1.2.11-deec42f53b.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig
-- Acquiring MSYS2...
-- Downloading https://sourceforge.net/projects/msys2/files/Base/x86_64/msys2-base-x86_64-20190524.tar.xz/download...
-- Downloading https://sourceforge.net/projects/msys2/files/Base/x86_64/msys2-base-x86_64-20190524.tar.xz/download... Failed. Status: 22;"HTTP response code said error"
-- Downloading http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20190524.tar.xz...
-- Downloading http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20190524.tar.xz... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:176 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:78 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:281 (vcpkg_acquire_msys)
  ports/zlib/portfile.cmake:46 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package zlib:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x64-windows
  Vcpkg version: 2020.06.15-nohash

**Comment by autoantwort** [comment]
> Vcpkg version: 2020.06.15-nohash

This is a very old version. Update your vcpkg version by running `git pull`

**Comment by Captain-Freels** [comment]
> > Vcpkg version: 2020.06.15-nohash
> 
> This is a very old version. Update your vcpkg version by running `git pull`

I tried this and it did change a lot but it still says the version is '2020.06.15-nohash', and I still get the same error with ompl[app]

**Comment by jimwang118** [comment]
Please run git pull https://github.com/microsoft/vcpkg.git master and ./bootstrap-vcpkg.bat.

**Comment by Captain-Freels** [comment]
Thank you for your help, that solved my issue
