### ISSUE TITLE
[<vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.>] build failure

### ISSUE THREAD

**Issue by Feluxa** [microsoft/vcpkg#36690]
### Operating system

Windows

### Compiler

MSVS

### Steps to reproduce the behavior

```Shell
vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.
```

### Failure logs

error: while detecting compiler information:
The log file content at "C:\Users\anana\vcpkg\buildtrees\detect_compiler\stdout-x64-windows.log" is:
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/Users/anana/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe -v
    Working Directory: C:/Users/anana/vcpkg/buildtrees/detect_compiler/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\anana\vcpkg\buildtrees\detect_compiler\config-x64-windows-rel-CMakeCache.txt.log
      C:\Users\anana\vcpkg\buildtrees\detect_compiler\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:314 (vcpkg_execute_required_process)
  scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:170 (include)

error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.

**Comment by autoantwort** [comment]
> error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.

And what did reading the logs reveal?

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This issue hasn’t been updated in one month. Please reopen this issue with more info if this is still a problem for you.
