### ISSUE TITLE
CMake error while trying to use nana and vcpkg

### ISSUE THREAD

**Issue by Adobe-Android** [Microsoft/vcpkg#3670]
CMake Error at /home/vm/workspace/vcpkg-install/vcpkg/scripts/buildsystems/vcpkg.cmake:247 (_find_package):
By not providing "Findnana.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "nana", but
CMake did not find one.

Could not find a package configuration file provided by "nana" with any of
the following names:

 nanaConfig.cmake
 nana-config.cmake

Add the installation prefix of "nana" to CMAKE_PREFIX_PATH or set
"nana_DIR" to a directory containing one of the above files. If "nana"
provides a separate development package or SDK, be sure it has been
installed.
Call Stack (most recent call first):

Any ideas?

**Comment by martin-s** [comment]
I think the messages are verbose enough: It looks for a find script (Findnana.cmake) which is not there. At least not in the default module folders.

**Comment by Adobe-Android** [comment]
Precisely. The necessary cmake files look like they are missing from the author when compared to known working packages.

**Comment by martin-s** [comment]
Can you type in the command which is executed? Nana itself is building fine for me, besides that it is a static build.

**Comment by Adobe-Android** [comment]
Is it being found by cmake and your cpp file?

**Comment by Adobe-Android** [comment]
It appears to me that there is no cmake find module.

**Comment by Adobe-Android** [comment]
A pull request will be made to solve this.
