### ISSUE TITLE
[gtest] Build error on x64-windows

### ISSUE THREAD

**Issue by Choi-Young-Hoon** [microsoft/vcpkg#36718]
$ vcpkg install gtest:x64-windows 

failed

-- Found external ninja('1.11.0').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/Tool/vcpkg/buildtrees/gtest/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Tool\vcpkg\buildtrees\gtest\config-x64-windows-dbg-CMakeCache.txt.log
      C:\Tool\vcpkg\buildtrees\gtest\config-x64-windows-rel-CMakeCache.txt.log
      C:\Tool\vcpkg\buildtrees\gtest\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:252 (vcpkg_execute_required_process)
  ports/gtest/portfile.cmake:19 (vcpkg_cmake_configure)
  scripts/ports.cmake:170 (include)

[config-x64-windows-dbg-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/14251910/config-x64-windows-dbg-CMakeCache.txt.log)
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/14251911/config-x64-windows-out.log)
[config-x64-windows-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/14251912/config-x64-windows-rel-CMakeCache.txt.log)

**Comment by LilyWangLL** [comment]
> CMake Error at C:/Tool/vcpkg/downloads/tools/cmake-3.27.1-windows/cmake-3.27.1-windows-i386/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:67 (message):
>   The C compiler
> 
>     "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe"
> 
>   is not able to compile a simple test program.
> 
>   It fails with the following output:
> 
>     Change Dir: 'C:/Tool/vcpkg/buildtrees/gtest/x64-windows-rel/CMakeFiles/CMakeScratch/TryCompile-8ri5da'
>     
>     Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v cmTC_b0a7f
>     [1/2] C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\cl.exe  /nologo   /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP   /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\cmTC_b0a7f.dir\testCCompiler.c.obj /FdCMakeFiles\cmTC_b0a7f.dir\ /FS -c C:\Tool\vcpkg\buildtrees\gtest\x64-windows-rel\CMakeFiles\CMakeScratch\TryCompile-8ri5da\testCCompiler.c
>     FAILED: CMakeFiles/cmTC_b0a7f.dir/testCCompiler.c.obj 
>     C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\cl.exe  /nologo   /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP   /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\cmTC_b0a7f.dir\testCCompiler.c.obj /FdCMakeFiles\cmTC_b0a7f.dir\ /FS -c C:\Tool\vcpkg\buildtrees\gtest\x64-windows-rel\CMakeFiles\CMakeScratch\TryCompile-8ri5da\testCCompiler.c
>     cl : 명령줄 error D8050 : 'C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\c1.dll'을(를) 실행할 수 없습니다. 명령줄을 디버그 레코드에 가져오지 못했습니다.
>     ninja: build stopped: subcommand failed.
>     
>  
>   CMake will not be able to correctly generate this project.

Thanks for posting this issue. Please make sure you have the following installed.
- Visual Studio Desktop development with C++.
- Windows 10 SDK or Windows 11 SDK.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
