### ISSUE TITLE
Visual Studio provided vcpkg tries to update system folders

### ISSUE THREAD

**Issue by pjmlp** [microsoft/vcpkg#36722]
While trying to use the built-in vcpkg alongside cmake, it tries to update the vcpkg_dep_info.cmake inside Visual Studio own installation.

```
Fetching registry information from https://github.com/microsoft/vcpkg (HEAD)...
write_contents_and_dirs("C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\vcpkg\vcpkg\blds\0.vcpkg_dep_info.cmake"): Zugriff verweigert
```

From _vcpkg-manifest-install.log_, the German error means _access denied_.

Naturally I would expect that those files would be somehow part of the project, and not messing with Visual Studio installation.

Microsoft Visual Studio Professional 2022
Version 17.8.6
VisualStudio.17.Release/17.8.6+34525.116
Visual C++ 2022   00476-80000-00000-AA991
Microsoft Visual C++ 2022

**Comment by FrankXie05** [comment]
@pjmlp You need to give your VS administrator permissions.

**Comment by pjmlp** [comment]
Of course, given the directory VS is trying to write to.

The whole point of this issue is that it shouldn't, I did not write this by accident:

**Naturally I would expect that those files would be somehow part of the project, and not messing with Visual Studio installation.**

**Comment by FrankXie05** [comment]
If you don't want to interfere with the VS installation, you need to use the external integrated vcpkg instead of the vcpkg that comes with VS.
Use the git and classic mode or manifest mode of vcpkg to integrate and install the project

**Comment by pjmlp** [comment]
I know how vcpkg works, thank you very much.

My point regarding usability on vcpkg shipped in the box stands.

Frank ***@***.***> schrieb am Di., 5. März 2024, 09:55:

**Comment by BillyONeal** [comment]
We have tests that this does not happen. Do you have a repro?

**Comment by BillyONeal** [comment]
Sorry for the brief response above. We explicitly test vcpkg, without admin rights, as part of every insertion into VS. See procedure here: https://github.com/microsoft/vcpkg-tool/blob/086859d80e1fd054d60c6e98291eb585fe20ae51/docs/vcpkg_tool_release_process.md?plain=1#L207

If you are seeing the bundled vcpkg try to write to `%ProgramFiles%` for any command other than the first time on a machine running `integrate install`, that is extremely unexpected behavior and we need to understand what is different about your system vs. how we are testing.

Can you also run `vcpkg --version` and include what it says with your repro?

**Comment by pjmlp** [comment]
So I revised this, using my [https://github.com/pjmlp/RaytracingWeekend-CPP](RaytracingWeekend-CPP) project, however I failed to reproduce it.

It might be have been indirectly fixed by my Visual Studio update,

Microsoft Visual Studio Professional 2022
Version 17.9.4
VisualStudio.17.Release/17.9.4+34714.143
Visual C++ 2022   00476-80000-00000-AA991
Microsoft Visual C++ 2022

Output from vcpkg --version

vcpkg package management program version 2023-12-12-1c9ec1978a6b0c2b39c9e9554a96e3e275f7556e

I guess, you can close this as non reproducible.

However since I am here, you can use that sample to see how modules and vcpkg require having a double build, as vcpkg isn't invoked as pre-build step, thus having to redo the broken build after the dependencies are downloaded.

See [build.log](https://github.com/microsoft/vcpkg/files/14741956/build.log)

**Comment by BillyONeal** [comment]
I'm guessing what actually happened is that you have another copy of vcpkg on the machine which is *not* the VS copy. That other copy got confused by developer command prompt setting `%VCPKG_ROOT%` to somewhere in VS' guts. And it, thinking it is the 'get from github' copy, tried to write to its own location. Maybe some interaction with https://github.com/microsoft/vcpkg/issues/32641#issuecomment-1834475080

If you do manage to get a repro please let us know.

>However since I am here, you can use that sample to see how modules and vcpkg require having a double build, as vcpkg isn't invoked as pre-build step, thus having to redo the broken build after the dependencies are downloaded.

This seems like an unrelated feature request to compose well with how MSBuild does module bits.

**Comment by pjmlp** [comment]
From the outside it would help if Microsoft C++ related projects actually collaborated to provide an uniform experience, like on the .NET side, hence why I considered it a vcpkg issue in first place.

Closing it now.
