### ISSUE TITLE
[crashpad] Build error on x64-windows

### ISSUE THREAD

**Issue by mthongkerd** [microsoft/vcpkg#36744]
Package: crashpad:x64-windows@2022-09-05#4

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.39.33519.0
-    vcpkg-tool version: 2024-02-07-8a83681f921b10d86ae626fd833c253f4f8c355b
    vcpkg-scripts version: 095ee06e7 2024-02-13 (4 hours ago)

**To Reproduce**

`vcpkg install crashpad`
**Failure logs**

```
-- Note: crashpad only supports static library linkage. Building static library.
-- Fetching https://chromium.googlesource.com/crashpad/crashpad 261679b3d2f3336d8531ed38e110254c3e2d1c10...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/msys64/usr/bin/git.exe fetch https://chromium.googlesource.com/crashpad/crashpad 261679b3d2f3336d8531ed38e110254c3e2d1c10 --depth 1 -n
    Working Directory: C:/lib_cpp/vcpkg/downloads/git-tmp
    Error code: 3328
    See logs for more information:
      C:\lib_cpp\vcpkg\buildtrees\crashpad\git-fetch-x64-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_git.cmake:86 (vcpkg_execute_required_process)
  ports/crashpad/portfile.cmake:3 (vcpkg_from_git)
  scripts/ports.cmake:170 (include)



```
<details><summary>C:\lib_cpp\vcpkg\buildtrees\crashpad\git-fetch-x64-windows-err.log</summary>

```
C:/msys64/usr/lib/git-core/git-remote-https.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```
</details>

**Comment by WangWeiLin-MV** [comment]
It can be accessed locally that the failed URL https://chromium.googlesource.com/crashpad/crashpad in the log.
`vcpkg install crashpad` also passed successfully.
We are unable to reproduce this issue. Could you help confirm this?
If you have any questions, please feel free to contact us.

**Comment by mthongkerd** [comment]
It's working now, thanks.
