### ISSUE TITLE
recent versions of vcpkg failed to build gmp

### ISSUE THREAD

**Issue by smartmaster** [microsoft/vcpkg#36749]
`
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: D:/sss-git-repo/vcpkg/downloads/tools/msys2/52c8bb2635a5bae2/usr/bin/make.exe -j 17 --trace -f Makefile all
    Working Directory: D:/sss-git-repo/vcpkg/buildtrees/gmp/x64-windows-dbg/
    See logs for more information:
      D:\sss-git-repo\vcpkg\buildtrees\gmp\build-x64-windows-dbg-out.log
      D:\sss-git-repo\vcpkg\buildtrees\gmp\build-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:136 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:2 (vcpkg_build_make)
  ports/gmp/portfile.cmake:95 (vcpkg_install_make)
  scripts/ports.cmake:170 (include)

error: building gmp:x64-windows failed with: BUILD_FAILED
Elapsed time to handle gmp:x64-windows: 7.5 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+gmp
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[gmp]+Build+error+on+x64-windows&body=Copy+issue+body+from+D%3A%2Fsss-git-repo%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
`

the logs files are attacged
[Uploading build-x64-windows-dbg-err.log…]()

**Comment by StarGate-One** [comment]
>See logs for more information:
D:\sss-git-repo\vcpkg\buildtrees\gmp\build-x64-windows-dbg-out.log
D:\sss-git-repo\vcpkg\buildtrees\gmp\build-x64-windows-dbg-err.log

**Comment by dg0yt** [comment]
> Then check for known issues at:
> https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+gmp

https://github.com/microsoft/vcpkg/issues/36639 ?

**Comment by JonLiu1993** [comment]
@smartmaster, thanks for posting this issue, this bug has been fixed by PR https://github.com/microsoft/vcpkg/pull/36774
Please try again with the latest vcpkg.
