### ISSUE TITLE
error: building qtinterfaceframework:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by cppcloud** [microsoft/vcpkg#36741]
PS D:\dev\vcpkg> .\vcpkg.exe install qt
warning: In the September 2023 release, the default triplet for vcpkg libraries changed from x86-windows to the detected host triplet (x64-windows). For the old behavior, add --triplet x86-windows . To suppress this message, add --triplet x64-windows .
Computing installation plan...
The following packages will be built and installed:
    qt[core,default-features]:x64-windows@6.6.1
  * qtinterfaceframework:x64-windows@6.6.1
  * qtlocation:x64-windows@6.6.1
  * qtlottie[core,qml]:x64-windows@6.6.1
  * qtmqtt:x64-windows@6.6.1
  * qtnetworkauth:x64-windows@6.6.1
  * qtopcua[core,default-features,gds,ns0idnames,open62541,qml]:x64-windows@6.6.1#1
  * qtpositioning[core,qml]:x64-windows@6.6.1#2
  * qtscxml[core,qml]:x64-windows@6.6.1
  * qtsensors[core,qml]:x64-windows@6.6.1
  * qtserialbus[core,default-features]:x64-windows@6.6.1
  * qtserialport:x64-windows@6.6.1#1
  * qtspeech:x64-windows@6.6.1
  * qtsvg:x64-windows@6.6.1
  * qttranslations[core,default-features]:x64-windows@6.6.1
  * qtvirtualkeyboard[core,default-features,hunspell]:x64-windows@6.6.1
  * qtwebchannel[core,qml]:x64-windows@6.6.1
  * qtwebengine[core,default-features,geolocation,spellchecker,webchannel]:x64-windows@6.6.1#3
  * qtwebsockets[core,qml]:x64-windows@6.6.1
  * qtwebview[core,webengine]:x64-windows@6.6.1
  * vcpkg-tool-lessmsi:x64-windows@1.10.0#1
  * vcpkg-tool-nodejs:x64-windows@16.18.0#1
  * vcpkg-tool-python2:x64-windows@2.7.18#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
-- Automatically setting %HTTP(S)_PROXY% environment variables to "127.0.0.1:15732".
Installing 1/23 qtinterfaceframework:x64-windows@6.6.1...
Building qtinterfaceframework:x64-windows@6.6.1...
-- Using cached D:/dev/vcpkg/downloads/qtinterfaceframework-a2085374e38a135eaacfe7533888f0a361d4c721.tar.gz
-- Cleaning sources at D:/dev/vcpkg/buildtrees/qtinterfaceframework/src/a361d4c721-2c693f67de.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/dev/vcpkg/downloads/qtinterfaceframework-a2085374e38a135eaacfe7533888f0a361d4c721.tar.gz
-- Applying patch fix-taglib-search.patch
-- Using source at D:/dev/vcpkg/buildtrees/qtinterfaceframework/src/a361d4c721-2c693f67de.clean
-- Using cached msys2-mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst.
-- Using msys root at D:/dev/vcpkg/downloads/tools/msys2/fdbea3694fb5c0d4
-- Using cached pypa-get-pip-38e54e5de07c66e875c11a1ebbdb938854625dd8.tar.gz.
-- Cleaning sources at D:/dev/vcpkg/buildtrees/qtinterfaceframework/src/8854625dd8-861bd167bd.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/dev/vcpkg/downloads/pypa-get-pip-38e54e5de07c66e875c11a1ebbdb938854625dd8.tar.gz
-- Using source at D:/dev/vcpkg/buildtrees/qtinterfaceframework/src/8854625dd8-861bd167bd.clean
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: D:/dev/vcpkg/downloads/tools/python/python-3.11.5-x64/python.exe D:/dev/vcpkg/buildtrees/qtinterfaceframework/src/8854625dd8-861bd167bd.clean/public/get-pip.py --no-warn-script-location
    Working Directory: D:/dev/vcpkg/buildtrees/qtinterfaceframework
    Error code: 1
    See logs for more information:
      D:\dev\vcpkg\buildtrees\qtinterfaceframework\get-pip-x64-windows-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake:48 (vcpkg_execute_required_process)
  ports/qtinterfaceframework/portfile.cmake:22 (x_vcpkg_get_python_packages)
  scripts/ports.cmake:170 (include)

error: building qtinterfaceframework:x64-windows failed with: BUILD_FAILED
Elapsed time to handle qtinterfaceframework:x64-windows: 1.8 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qtinterfaceframework
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[qtinterfaceframework]+Build+error+on+x64-windows&body=Copy+issue+body+from+D%3A%2Fdev%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by StarGate-One** [comment]
>See logs for more information:
D:\dev\vcpkg\buildtrees\qtinterfaceframework\get-pip-x64-windows-err.log

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you
