### ISSUE TITLE
[chronoeninge] ChBodyEasy cause file not found error

### ISSUE THREAD

**Issue by mmarcianesi** [microsoft/vcpkg#36768]
**The bug**
Using the specific chrono::ChBodyEasyBox causes a "Could not open the include file "LinearMath/cbtScalar.h"
The error can be fixed using the full path:

`#include "chrono/collision/bullet/LinearMath/...`

**Environment**
- Windows 11
- MSVC 17.8.7
- chronoengine 8, latest available

**To Reproduce**
1. ./vcpkg install chronoengine
2. Create a simple project,  
3. Type

```
#include <iostream>
#include <chrono/physics/ChBodyEasy.h>
#include <chrono/physics/ChSystemNSC.h>

int main() {
auto body1 = std::make_shared<chrono::ChBodyEasyBox>(1, 1, 1, 1000, true, false);
return 0;
}
```

**Expected behavior**
Build without errors.

**Comment by FrankXie05** [comment]
@mmarcianesi Thanks for posting this issue.

Currently, this port does not provide any usage.
If you want to use any header files:

1.  ./vcpkg install chronoengine
2.  ./.vcpkg integrate install
3.  create a MSbuild project
4.  Include all required header files
