### ISSUE TITLE
Add QtWebKit 

### ISSUE THREAD

**Issue by traversaro** [microsoft/vcpkg#3677]
It would be great to have a port of the QtWebKit library ( https://github.com/annulen/webkit/wiki ) a community maintained version of the former official WebKit qt module.  

Build instructions: https://github.com/annulen/webkit/wiki#build-requirements . 
Debian package : https://packages.debian.org/source/sid/qtwebkit-opensource-src .
Non-core homebrew formula : https://github.com/KDE-mac/homebrew-kde/blob/master/Formula/qt-webkit.rb .

**Comment by Voskrese** [comment]
> the port is not mine, stole from not remember ))
> so bugs is not for me
> did not test

[qtwebkit.zip](https://github.com/microsoft/vcpkg/files/3394360/qtwebkit.zip)

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!

**Comment by traversaro** [comment]
I guess this means that the new policy is not to have "New port request" open. Could it make  sense to remove the corresponding issue template https://github.com/microsoft/vcpkg/blob/master/.github/ISSUE_TEMPLATE/request-a-new-port.md ?

**Comment by JackBoosY** [comment]
@traversaro No, we will **still accept** new port request, but we hope that new ports will be added by contributors.

**Comment by traversaro** [comment]
> @traversaro No, we will **still accept** new port request, but we hope that new ports will be added by contributors.

Just to clarify, so a new issue is opened, and then it will be closed after some time?

**Comment by JackBoosY** [comment]
@traversaro Yes, if there is no body to add it into vcpkg.
