### ISSUE TITLE
[libsodium] Missing include directory variable for CMake

### ISSUE THREAD

**Issue by 0xg0nz0** [microsoft/vcpkg#36772]
**Describe the bug**

**Environment**
- OS: Linux (mcr.microsoft.com/devcontainers/cpp:1-ubuntu-22.04)
- Compiler: gcc 11.4.0
- CMake: 3.22.1

**To Reproduce**
1. ./vcpkg install libsodium
2. Set up in CMakeLists.txt:

```
find_package(unofficial-sodium CONFIG REQUIRED)
```

**Expected behavior**
I expect that there should be unofficial-sodium_INCLUDE_DIR defined so you can reference it in CMake:

```
target_include_directories(iggy PRIVATE ${unofficial-sodium_INCLUDE_DIR}/../../include)
```

I had to work around it as follows:

```
target_include_directories(iggy PRIVATE ${unofficial-sodium_DIR}/../../include)
```

**Failure logs**

```
[build] [1/5] Building CXX object CMakeFiles/iggy.dir/sdk/client.cc.o
[build] FAILED: CMakeFiles/iggy.dir/sdk/client.cc.o 
[build] /usr/bin/c++    -MD -MT CMakeFiles/iggy.dir/sdk/client.cc.o -MF CMakeFiles/iggy.dir/sdk/client.cc.o.d -o CMakeFiles/iggy.dir/sdk/client.cc.o -c /workspaces/iggy-cpp-client/sdk/client.cc
[build] In file included from /workspaces/iggy-cpp-client/sdk/client.cc:1:
[build] /workspaces/iggy-cpp-client/sdk/client.h:3:10: fatal error: sodium.h: No such file or directory
[build]     3 | #include <sodium.h>
[build]       |          ^~~~~~~~~~
[build] compilation terminated.
```

**Additional context**
None.

**Comment by dg0yt** [comment]
> I expect that there should be unofficial-`sodium_INCLUDE_DIR` defined so you can reference it in CMake

This is not expected usage for modern CMake. You are to link to the given "imported" targets, and they are to implicitly provide the required include directories via target properties. As in

~~~
  find_package(unofficial-sodium CONFIG REQUIRED)
  target_link_libraries(iggy PRIVATE unofficial-sodium::sodium)
~~~

**Comment by dg0yt** [comment]
Then that's the error that should be reported...
But on x64-linux, I see
~~~
set_target_properties(unofficial-sodium::sodium PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  ...
)
~~~
so I would assume it just works. And it is used by some other ports (cnats,fizz,folly).

**Comment by 0xg0nz0** [comment]
Understood. I will dig into cnats and the others to see if I can figure out what went wrong, and open a separate issue if I can confirm it's not working as expected. Thanks.
