### ISSUE TITLE
can't get vcpkg run with cmake

### ISSUE THREAD

**Issue by jagannatharjun** [microsoft/vcpkg#3679]
i add this in my CMakeLists.txt

> find_path(ZSTD_INCLUDE_DIR zstd.h)
> find_package(ZSTD REQUIRED)
> include_directories(${ZSTD_INCLUDE_DIR})

but running 
`cmake -G Ninja ..\ -DVCPKG_TARGET_TRIPLET=x86-windows-static -DCMAKE_TOOLCHAIN_FILE=E:\Cpp\vcpkg\scripts\buildsystems\vcpkg.cmake`

fails with

> CMake Error at CMakeLists.txt:64 (find_package):
>   By not providing "FindZSTD.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "ZSTD", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "ZSTD" with any of
>   the following names:
> 
>     ZSTDConfig.cmake
>     zstd-config.cmake
> 
>   Add the installation prefix of "ZSTD" to CMAKE_PREFIX_PATH or set
>   "ZSTD_DIR" to a directory containing one of the above files.  If "ZSTD"
>   provides a separate development package or SDK, be sure it has been
>   installed.

i can confirm i have zstd installed and zstd.h exists in x86-windows\include

**Comment by PhoebeHui** [comment]
@jagannatharjun, it looks zstd doesn't have native cmake support. See 'Handling libraries without native cmake support' part in  https://github.com/Microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md

**Comment by okmechak** [comment]
#### Have similar problem with CMake on Windows:
installed box2d:

`vcpkg install box2d:x64-windwos`

at the end it printed out:

`...`
`The package box2d:x64-windows provides CMake targets:`
`find_package(unofficial-box2d CONFIG REQUIRED)`
`target_link_libraries(main PRIVATE unofficial::box2d::Box2D)`

then I configured simple _CMakeLists.txt_ file and run command:

`cmake -G "Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE=../../Source/vcpkg/scripts/buildsystems/vcpkg.cmake ../../Dev/sandbox`

And received similar result to @jagannatharjun: 

> -- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18362.
> CMake Error at box2d/CMakeLists.txt:3 (find_package):
>   Could not find a package configuration file provided by "unofficial-box2d"
>   with any of the following names:
> 
>     unofficial-box2dConfig.cmake
>     unofficial-box2d-config.cmake
> 
>   Add the installation prefix of "unofficial-box2d" to CMAKE_PREFIX_PATH or
>   set "unofficial-box2d_DIR" to a directory containing one of the above
>   files.  If "unofficial-box2d" provides a separate development package or
>   SDK, be sure it has been installed.
> 
> 
> -- Configuring incomplete, errors occurred!

But __unofficial-box2d-config.cmake__ surelly exist in _vcpkg\installed\x64-windows\share\unofficial-box2d_

**Comment by AbdulAbCellera** [comment]
any updates on this issue?

**Comment by AbdulAbCellera** [comment]
could be related to this issue https://github.com/microsoft/vcpkg/issues/28523

**Comment by Thomas1664** [comment]
@LilyWangL I think the issue can be closed: The user set the target triplet to x86-windows-static but found the headers in the x86-windows triplet. Furthermore, in the comment about box2d, the port is installed for triplet x64-windows but by not setting `VCPKG_TARGET_TRIPLET` vcpkg defaulted to x86-windows. Note that today x64-windows is the default on Windows.

**Comment by LilyWangLL** [comment]
Thanks for Thomas's suggestion, I test the usage of `zstd:x86-windows-static` and `box2d:x64-windows`, they all passed. So I am closing this issue for now.
