### ISSUE TITLE
On OpenBSD, do not require "gcc" to be installed

### ISSUE THREAD

**Issue by SchaichAlonso** [microsoft/vcpkg#36807]
**Describe the bug**
Currently, the [vcpkg boostrap logic has a branch](https://github.com/microsoft/vcpkg/blob/13bde2ff13192e1b2fdd37bd9b475c7665ae6ae5/scripts/bootstrap.sh#L103) for OpenBSD where the C and C++ compilers are set to clang. In addition, the `vcpkgUseSystem` flag is set to ON. 

[A few lines later](https://github.com/microsoft/vcpkg/blob/13bde2ff13192e1b2fdd37bd9b475c7665ae6ae5/scripts/bootstrap.sh#L114), the `vcpkgUseSystem` being ON causes a [hard dependency on gcc](https://github.com/microsoft/vcpkg/blob/13bde2ff13192e1b2fdd37bd9b475c7665ae6ae5/scripts/bootstrap.sh#L118), despite OpenBSD using clang whether gcc is installed or not. This check will fail, because [the gcc binary is called egcc by default on OpenBSD](https://github.com/openbsd/ports/blob/575cada68bd4b2a0450c358d6991a6f57d517b82/lang/gcc/11/pkg/PLIST-main#L5) .

**Environment**
- OS: OpenBSD vultr.guest 7.4 GENERIC.MP#2 amd64
- Compiler: clang version 16.0.6

**To Reproduce**
1. sh boostrap-vcpkg.sh
2. See error
Repro code when

**Expected behavior**
As the `CC` and `CXX` environment variables are provided at this point, just pass them to `cmake` and skip the "check" for gcc. 

**Failure logs**

**Additional context**

**Comment by dg0yt** [comment]
Hm, perhaps the check is meant to be for CC and CXX instead?
There is a second spot where this variable is set, if needed on non-x64 linux.
This needs consolidation.
