### ISSUE TITLE
Fix compilation of vcpkg on OpenBSD

### ISSUE THREAD

**Issue by SchaichAlonso** [microsoft/vcpkg#36812]
**Describe the bug**
The `SIOCGIFHWADDR` name, referenced in the [fallback branch within vcpkg::get_user_mac_hash](https://github.com/microsoft/vcpkg-tool/blob/05320e49448d88550c81ce0ba62f1664e8e51118/src/vcpkg/base/system.mac.cpp#L245C1-L245C19), is not defined on OpenBSD.

Further, the `environ` name referenced in [vcpkg::cmd_execute_background](https://github.com/microsoft/vcpkg-tool/blob/05320e49448d88550c81ce0ba62f1664e8e51118/src/vcpkg/base/system.process.cpp#L1297), among others, is not defined on OpenBSD, either.

**Environment**
- OS: OpenBSD vultr.guest 7.4 GENERIC.MP#2 amd64
- Compiler: clang version 16.0.6

**To Reproduce**
1. git clone git@github.com:microsoft/vcpkg-tool.git
2. mkdir vcpkg-tool/build
3. cmake -S vcpkg-tool -B vcpkg-tool/build
4. cmake --build vcpkg-tool/build

**Expected behavior**
cmake compiles a usable `vcpkg` binary

**Failure logs**
[stdout.txt](https://github.com/microsoft/vcpkg/files/14319665/stdout.txt)

**Additional context**
For most parts of it, OpenBSD is compatible with FreeBSD, which already has platform branches in vcpkg-tool to resolve these issues.

**Comment by BillyONeal** [comment]
We did a few tool releases since this :)
