### ISSUE TITLE
I'm confused. Can't install curl, can't install gflib 

### ISSUE THREAD

**Issue by BlackBoiBanta** [microsoft/vcpkg#36814]
![image_2024-02-17_182919775](https://github.com/microsoft/vcpkg/assets/87266926/1fd5b8da-bab0-47c2-9b0a-ea918e956841)

![image](https://github.com/microsoft/vcpkg/assets/87266926/16a7f9f5-d9ab-40b3-a769-6807bd9ba550)

**Comment by dg0yt** [comment]
Start with `vcpkg upgrade` (and `vcpkg upgrade --no-dry-run`).

**Comment by BlackBoiBanta** [comment]
> Start with `vcpkg upgrade` (and `vcpkg upgrade --no-dry-run`).

did that 
![image](https://github.com/microsoft/vcpkg/assets/87266926/5b9c74ee-a5d0-48cd-93cb-99583aec31fa)

**Comment by dg0yt** [comment]
And still there is something outdated here.
~~~
vcpkg remove --recurse vcpkg-cmake
git pull
vcpkg install --no-binarycaching vcpkg-cmake

**Comment by BlackBoiBanta** [comment]
> And still there is something outdated here.
> 
> ```
> vcpkg remove --recurse vcpkg-cmake
> git pull
> vcpkg install --no-binarycaching vcpkg-cmake
> ```

I ran this and still got the error. 
![image](https://github.com/microsoft/vcpkg/assets/87266926/2ab09535-4838-4cdf-a8ab-ddd7b8171c72)

**Comment by MonicaLiu0311** [comment]
Please run the following command:
```
git pull https://github.com/microsoft/vcpkg.git master
./bootstrap-vcpkg.bat
./vcpkg upgrade --no-dry-run
```

**Comment by BlackBoiBanta** [comment]
> Please run the following command:
> 
> ```
> git pull https://github.com/microsoft/vcpkg.git master
> ./bootstrap-vcpkg.bat
> ./vcpkg upgrade --no-dry-run
> ```

did it 
![image](https://github.com/microsoft/vcpkg/assets/87266926/d6d5bd61-3500-4146-8189-08ee48d7fb29)

**Comment by BlackBoiBanta** [comment]
ran the commands and still got the errors: 
![image](https://github.com/microsoft/vcpkg/assets/87266926/c8ae6990-17c1-48af-b161-bf42f1953d39)

**Comment by dg0yt** [comment]
Hm, why doesn't the upgrade command fix your installation?
~~~
vcpkg remove --recurse vcpkg-cmake-config
vcpkg install --no-binarycaching vcpkg-cmake-config

**Comment by BlackBoiBanta** [comment]
> Hm, why doesn't the upgrade command fix your installation?
> 
> ```
> vcpkg remove --recurse vcpkg-cmake-config
> vcpkg install --no-binarycaching vcpkg-cmake-config
> ```

ok ok so some progress was made. I think curl worked. But now there is a new error (I have absolutely no clue what is going on)
![image](https://github.com/microsoft/vcpkg/assets/87266926/664f0677-08ce-4be2-b7d7-2d2484e69985)
![image](https://github.com/microsoft/vcpkg/assets/87266926/e99af057-72b2-4ad7-95e4-5316fd411228)

**Comment by dg0yt** [comment]
Well, maybe you removed (some) installed files manually? You can always start with a fresh directory, but you must remove `installed` completely.

**Comment by BlackBoiBanta** [comment]
> Well, maybe you removed (some) installed files manually? You can always start with a fresh directory, but you must remove `installed` completely. 

how do i do that ?

**Comment by MonicaLiu0311** [comment]
Delete the `installed/` folder under the `vcpkg/` directory and try the installation again. 

Or re-clone vcpkg and start:
```
git clone https://github.com/microsoft/vcpkg.git
.\bootstrap-vcpkg.bat
.\vcpkg install ...
```

**Comment by BlackBoiBanta** [comment]
> Contributor

oh wow. It worked. Thank you all.

**Comment by MonicaLiu0311** [comment]
This issue will be closed soon.
