### ISSUE TITLE
vcpkg executable fails to resolve its' path on OpenBSD

### ISSUE THREAD

**Issue by SchaichAlonso** [microsoft/vcpkg#36813]
**Describe the bug**
The OpenBSD branch of `vcpkg::get_exe_path_of_current_process` [uses getprogname to resolve it's location](https://github.com/microsoft/vcpkg-tool/blob/05320e49448d88550c81ce0ba62f1664e8e51118/src/vcpkg/base/system.process.cpp#L253) that is then fed into `realpath`. [getprogname(3)](https://man.openbsd.org/getprogname.3), however, does not return the application path, but instead the application's name, which might or might not be "compatible" for this purpose. As the `vcpkg` binary is always named `vcpkg`, `getprogname` will resolve to `vcpkg`, even if vcpkg was invoked via `somePath/vcpkg`, which will then fail to resolve by `realpath`.

**Environment**
- OS: OpenBSD vultr.guest 7.4 GENERIC.MP#2 amd64
- Compiler: clang version 16.0.6

**To Reproduce**
1. git clone git@github.com:microsoft/vcpkg-tool.git
2. cd vcpkg-tool
3. git checkout 8682407923c347e76ed1deff67619fb64051993a # contains fix for #36812 
4. mkdir build
5. cmake -S . -B build
6. cmake --build build
7. ./build/vcpkg install xxxx

**Expected behavior**
The xxxx port name is good enough to reproduce the behaviour, because `vcpkg` invokes `vcpkg::get_exe_path_of_current_process` when it attempts to resolve the path to the `xxxx` port.

**Failure logs**
[stdout.txt](https://github.com/microsoft/vcpkg/files/14319820/stdout.txt)

**Additional context**
While #36812 can reuse the `__FreeBSD__` code to fix the build, we cannot resolve paths using FreeBSD's `KERN_PROC_PATHNAME` sysctl on OpenBSD here, as the `KERN_PROC_PATHNAME` name is FreeBSD specific.

Instead, we can query the arguments that were used to `exec` the vcpkg proccess by it's parent process, and evaluate our name by analyzing first argument - or `argv[0]` of `main` in C speak. Another option would be to invoke `setprogname` in `main` using `argv[0]` there, thereby overriding the default value of `getprogname`.

**Comment by JonLiu1993** [comment]
Because the vcpkg-tool version has been updated, I closed this issue
