### ISSUE TITLE
Command: "vcpkg install ogre" fails ...

### ISSUE THREAD

**Issue by syedhasan1964** [microsoft/vcpkg#36834]
Additional details can be found in this attachment:

[CWindowsSystem32cmd.exe.txt](https://github.com/microsoft/vcpkg/files/14322986/CWindowsSystem32cmd.exe.txt)

Please look into this at your earliest convenience. Thanks :)

**Comment by dg0yt** [comment]
~~~
Installing 14/37 assimp:x64-windows@5.3.1#4...
...
    See logs for more information:
      D:\VCPKG\vcpkg\buildtrees\assimp\install-x64-windows-dbg-out.log

**Comment by syedhasan1964** [comment]
To resolve the problem, I had to install Visual Studio 2022. After that, I could install ogre :)
