### ISSUE TITLE
[gloo] build failure

### ISSUE THREAD

**Issue by Bzz2745** [microsoft/vcpkg#36833]
### Operating system

Linux 

### Compiler

gcc-12 cuda-12

### Steps to reproduce the behavior

```Shell
`vcpkg install gloo`
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
    gloo:x64-linux@20201203#2
Installing 1/1 gloo:x64-linux@20201203#2...
Building gloo:x64-linux@20201203#2...
-- Using cached facebookincubator-gloo-1da21174054eaabbbd189b7f657ea24842d821e2.tar.gz.
-- Extracting source /home/user/Environments/vcpkg/downloads/facebookincubator-gloo-1da21174054eaabbbd189b7f657ea24842d821e2.tar.gz
-- Using source at /home/user/Environments/vcpkg/buildtrees/gloo/src/4842d821e2-089f9c85b8
-- Configuring x64-linux
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: /home/user/Environments/vcpkg/downloads/tools/cmake-3.27.1-linux/cmake-3.27.1-linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j13
    Working Directory: /home/user/Environments/vcpkg/buildtrees/gloo/x64-linux-dbg
    See logs for more information:
      /home/user/Environments/vcpkg/buildtrees/gloo/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/gloo/portfile.cmake:25 (vcpkg_cmake_install)
  scripts/ports.cmake:170 (include)

### Additional context

[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/14322732/install-x64-linux-dbg-out.log)

I have tried the solution provided by this [link](https://github.com/facebookincubator/gloo/commit/10909297fedab0a680799211a299203e53515032) but not work , here is other link might help (but I didn't find the obvious way to solve it) :

https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1875386.html

@https://github.com/facebookincubator/gloo/issues/345

@https://github.com/facebookincubator/gloo/pull/346

@https://github.com/facebookincubator/gloo/commit/10909297fedab0a680799211a299203e53515032

**Comment by MonicaLiu0311** [comment]
It worked when I installed using gcc-11. When I installed using gcc-12, I got a different error than yours:
```
[31/37] /usr/bin/c++  -I/mnt/vcpkg/buildtrees/gloo/src/4842d821e2-089f9c85b8.clean -I/mnt/vcpkg/buildtrees/gloo/x64-linux-dbg -fPIC -std=c++11 -fPIC -g -MD -MT gloo/CMakeFiles/gloo.dir/transport/tcp/device.cc.o -MF gloo/CMakeFiles/gloo.dir/transport/tcp/device.cc.o.d -o gloo/CMakeFiles/gloo.dir/transport/tcp/device.cc.o -c /mnt/vcpkg/buildtrees/gloo/src/4842d821e2-089f9c85b8.clean/gloo/transport/tcp/device.cc
FAILED: gloo/CMakeFiles/gloo.dir/transport/tcp/device.cc.o
/usr/bin/c++  -I/mnt/vcpkg/buildtrees/gloo/src/4842d821e2-089f9c85b8.clean -I/mnt/vcpkg/buildtrees/gloo/x64-linux-dbg -fPIC -std=c++11 -fPIC -g -MD -MT gloo/CMakeFiles/gloo.dir/transport/tcp/device.cc.o -MF gloo/CMakeFiles/gloo.dir/transport/tcp/device.cc.o.d -o gloo/CMakeFiles/gloo.dir/transport/tcp/device.cc.o -c /mnt/vcpkg/buildtrees/gloo/src/4842d821e2-089f9c85b8.clean/gloo/transport/tcp/device.cc
/mnt/vcpkg/buildtrees/gloo/src/4842d821e2-089f9c85b8.clean/gloo/transport/tcp/device.cc: In function ‘gloo::transport::tcp::attr gloo::transport::tcp::CreateDeviceAttr(const attr&)’:
/mnt/vcpkg/buildtrees/gloo/src/4842d821e2-089f9c85b8.clean/gloo/transport/tcp/device.cc:151:39: error: aggregate ‘std::array<char, 64> hostname’ has incomplete type and cannot be defined
  151 |       std::array<char, HOST_NAME_MAX> hostname;
      |                                       ^~~~~~~~

```

**Comment by Bzz2745** [comment]
Unfortunately, it still doesn't work properly now. This is the new log file I generated when I used vcpkg to compile gloo:
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/14470931/install-x64-linux-dbg-out.log)

**Comment by MonicaLiu0311** [comment]
We cannot repro your issue, but we have found a similar fix upstream. Could you please try to see if it solves your current problem: https://github.com/facebookincubator/gloo/pull/352.

**Comment by jimwang118** [comment]
> Unfortunately, it still doesn't work properly now. This is the new log file I generated when I used vcpkg to compile gloo: [install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/14470931/install-x64-linux-dbg-out.log)

I cannot reproduce your problem locally. Is the system you are using Ubuntu, Redhat or centos?
You can try using the [PR](https://github.com/facebookincubator/gloo/pull/352) code below to see if it can fix your problem.
