### ISSUE TITLE
[icu] ICU port does not build on Linux

### ISSUE THREAD

**Issue by sbj42** [Microsoft/vcpkg#3683]
`ports/icu/portfile.cmake` only works on Windows.  I've identified the following issues that impact Linux:

- MSYS is not needed on Linux
- The zip file, when extracted, uses CRLF line endings, which interferes with bash running runConfigureICU
- The runConfigureICU options `MSYS/MSVC` and `--host=i686-pc-mingw32` are Windows-specific
- Most of the CFLAGS and LDFLAGS are MSVC-specific
- Renaming static libraries to remove the "s" prefix is only necessary on Windows

**Comment by PhoebeHui** [comment]
@sbj42, the PR has merged, and Icu installed successfully on Linux now, looks there is no reason to keep this issue open.

linux001@linuxtest01:~/vcpkg$ ./vcpkg install icu
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be built and installed:
    icu[core]:x64-linux
Starting package 1/1: icu:x64-linux
Building package icu[core]:x64-linux...
-- Using cached /home/linux001/vcpkg/downloads/icu4c-61_1-src.tgz
-- Applying patch /home/linux001/vcpkg/ports/icu/disable-escapestr-tool.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch /home/linux001/vcpkg/ports/icu/remove-MD-from-configure.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Configuring x64-linux-rel
-- Configuring x64-linux-rel done
-- Configuring x64-linux-dbg
-- Configuring x64-linux-dbg done
-- Package x64-linux-rel
-- Package x64-linux-rel done
-- Package x64-linux-dbg
-- Package x64-linux-dbg done
-- Performing post-build validation
-- Performing post-build validation done
Building package icu[core]:x64-linux... done
Installing package icu[core]:x64-linux...
Installing package icu[core]:x64-linux... done
Elapsed time for package icu:x64-linux: 5.798 min

Total elapsed time: 5.798 min

linux001@linuxtest01:~/vcpkg$ ./vcpkg version
Vcpkg package management program version 2018.11.23-unknownhash
