### ISSUE TITLE
error: building boost-config:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by CBugBuster** [microsoft/vcpkg#36831]
Copy issue body from C:/dev/vcpkg/installed/vcpkg/issue_body.md

error: building boost-config:x64-windows failed with: BUILD_FAILED
I have the latest port files with `git pull` and `vcpkg update`
Had the same problem with 'building boost-build:x64-windows' right before but soved it with https://github.com/microsoft/vcpkg/pull/26527 @thebelin

**Comment by CBugBuster** [comment]
c:\dev\vcpkg>.\vcpkg install tgbot-cpp:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * boost-algorithm:x64-windows@1.84.0
  * boost-align:x64-windows@1.84.0
  * boost-any:x64-windows@1.84.0
  * boost-array:x64-windows@1.84.0
  * boost-asio:x64-windows@1.84.0
  * boost-assert:x64-windows@1.84.0
  * boost-atomic:x64-windows@1.84.0
  * boost-bind:x64-windows@1.84.0
  * boost-build:x64-windows@1.84.0#1
  * boost-chrono:x64-windows@1.84.0
  * boost-concept-check:x64-windows@1.84.0
  * boost-config:x64-windows@1.84.0
  * boost-container:x64-windows@1.84.0
  * boost-container-hash:x64-windows@1.84.0
  * boost-context:x64-windows@1.84.0
  * boost-conversion:x64-windows@1.84.0
  * boost-core:x64-windows@1.84.0
  * boost-coroutine:x64-windows@1.84.0
  * boost-date-time:x64-windows@1.84.0
  * boost-describe:x64-windows@1.84.0
  * boost-detail:x64-windows@1.84.0
  * boost-endian:x64-windows@1.84.0
  * boost-exception:x64-windows@1.84.0
  * boost-function:x64-windows@1.84.0
  * boost-function-types:x64-windows@1.84.0
  * boost-functional:x64-windows@1.84.0
  * boost-fusion:x64-windows@1.84.0
  * boost-integer:x64-windows@1.84.0
  * boost-intrusive:x64-windows@1.84.0
  * boost-io:x64-windows@1.84.0
  * boost-iterator:x64-windows@1.84.0
  * boost-lexical-cast:x64-windows@1.84.0
  * boost-modular-build-helper:x64-windows@1.84.0#2
  * boost-move:x64-windows@1.84.0
  * boost-mp11:x64-windows@1.84.0
  * boost-mpl:x64-windows@1.84.0
  * boost-multi-index:x64-windows@1.84.0
  * boost-numeric-conversion:x64-windows@1.84.0
  * boost-optional:x64-windows@1.84.0
  * boost-phoenix:x64-windows@1.84.0
  * boost-pool:x64-windows@1.84.0
  * boost-predef:x64-windows@1.84.0
  * boost-preprocessor:x64-windows@1.84.0
  * boost-property-tree:x64-windows@1.84.0
  * boost-proto:x64-windows@1.84.0
  * boost-range:x64-windows@1.84.0
  * boost-ratio:x64-windows@1.84.0
  * boost-regex:x64-windows@1.84.0
  * boost-serialization:x64-windows@1.84.0
  * boost-smart-ptr:x64-windows@1.84.0
  * boost-spirit:x64-windows@1.84.0
  * boost-static-assert:x64-windows@1.84.0
  * boost-system:x64-windows@1.84.0
  * boost-test:x64-windows@1.84.0
  * boost-thread:x64-windows@1.84.0
  * boost-throw-exception:x64-windows@1.84.0
  * boost-tokenizer:x64-windows@1.84.0
  * boost-tuple:x64-windows@1.84.0
  * boost-type-index:x64-windows@1.84.0
  * boost-type-traits:x64-windows@1.84.0
  * boost-typeof:x64-windows@1.84.0
  * boost-unordered:x64-windows@1.84.0
  * boost-utility:x64-windows@1.84.0
  * boost-variant:x64-windows@1.84.0
  * boost-variant2:x64-windows@1.84.0
  * boost-winapi:x64-windows@1.84.0
  * curl[core,non-http,schannel,ssl,sspi]:x64-windows@8.6.0
  * openssl:x64-windows@3.2.1
    tgbot-cpp:x64-windows@1.7.2
  * vcpkg-cmake:x64-windows@2023-05-04
  * vcpkg-cmake-config:x64-windows@2022-02-06#1
  * vcpkg-cmake-get-vars:x64-windows@2023-12-31
  * zlib:x64-windows@1.3.1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\User\AppData\Local\vcpkg\archives in 1.73 ms. Use --debug to see more details.
Installing 1/73 boost-config:x64-windows@1.84.0...
Building boost-config:x64-windows@1.84.0...
-- Downloading https://github.com/boostorg/config/archive/boost-1.84.0.tar.gz -> boostorg-config-boost-1.84.0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from c:\dev\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: c:\dev\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://github.com/boostorg/config/archive/boost-1.84.0.tar.gz
warning: Download failed -- retrying after 1000ms
warning: Download failed -- retrying after 2000ms
warning: Download failed -- retrying after 4000ms
error: Failed to download from mirror set
error: https://github.com/boostorg/config/archive/boost-1.84.0.tar.gz: WinHttpReceiveResponse failed with exit code 12175
error: https://github.com/boostorg/config/archive/boost-1.84.0.tar.gz: WinHttpReceiveResponse failed with exit code 12175
error: https://github.com/boostorg/config/archive/boost-1.84.0.tar.gz: WinHttpReceiveResponse failed with exit code 12175
error: https://github.com/boostorg/config/archive/boost-1.84.0.tar.gz: WinHttpReceiveResponse failed with exit code 12175
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1030):
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 2us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 1066us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 12 s (11505912us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.


Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/boost-config/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:170 (include)


error: building boost-config:x64-windows failed with: BUILD_FAILED
Elapsed time to handle boost-config:x64-windows: 12 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-config
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[boost-config]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2Fdev%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by JonLiu1993** [comment]
@CBugBuster, Thanks for posting this issue, I can not repo your issue on my local machine, It looks like this error is a network problem, you try again using the latest vcpkg.

**Comment by CBugBuster** [comment]
@JonLiu1993, thank you for your reply, I have the latest port files with git pull and vcpkg update and it really seems like a network issue, due to the message "Your connection is not private" when trying to open any link. I hope we could find the solution together

**Comment by JonLiu1993** [comment]
@CBugBuster, Can you still reproduce your error now?

**Comment by CBugBuster** [comment]
@JonLiu1993, yes, it's exactly the same as on my second comment. Or maybe I got you wrong, if that's so, let me know

**Comment by JonLiu1993** [comment]
@CBugBuster, We consider this error from two points:
1. Can you download this package manually https://github.com/boostorg/config/archive/boost-1.84.0.tar.gz
2. Second, do you have anti-virus software installed on your computer or a firewall blocking SSL connections?

**Comment by CBugBuster** [comment]
@JonLiu1993
1. No, I can't with either Google or Bing(
2. I have Avast and I have turned off all the screens. I also have Windows Defender, and I don't actually know how to deal with it or even whether it works or not. Have cleared the cache and cookies, https://www.google.com opens successfully

C:\Windows\System32>netsh firewall show state

Firewall status:
-------------------------------------------------------------------
Profile                           = ???????
Operational mode                  = Enable
Exception mode                    = Enable
Multicast/broadcast response mode = Enable
Notification mode                 = Enable
Group policy version              = ?????????? ????????? Windows
Remote admin mode                 = Disable

Ports currently open on all network interfaces:
Port   Protocol  Version  Program
-------------------------------------------------------------------
1688   TCP       Any      (null)
3389   TCP       Any      (null)

IMPORTANT: Command executed successfully.
However, "netsh firewall" is deprecated;
use "netsh advfirewall firewall" instead.
For more information on using "netsh advfirewall firewall" commands
instead of "netsh firewall", see KB article 947709
at https://go.microsoft.com/fwlink/?linkid=121488 .

**Comment by JonLiu1993** [comment]
@CBugBuster, https://github.com/boostorg/config/archive/boost-1.84.0.tar.gz I can download package manually.
In addition, if you have a firewall or some anti-virus software on your computer, this issue is not a vcpkg problem, but your "network problem".

**Comment by CBugBuster** [comment]
@JonLiu1993 it worked but partly. 10/71 pieces are already installed, I use psiphon. Thank you! But another problem has appeared.

**### error: building boost-build:x64-windows failed with: BUILD_FAILED**

C:\dev\vcpkg>.\vcpkg  install tgbot-cpp
warning: In the September 2023 release, the default triplet for vcpkg libraries changed from x86-windows to the detected host triplet (x64-windows). For the old behavior, add --triplet x86-windows . To suppress this message, add --triplet x64-windows .
Computing installation plan...
The following packages will be built and installed:
  * boost-algorithm:x64-windows@1.84.0
  * boost-align:x64-windows@1.84.0
  * boost-any:x64-windows@1.84.0
  * boost-asio:x64-windows@1.84.0
  * boost-atomic:x64-windows@1.84.0
  * boost-build:x64-windows@1.84.0#1
  * boost-chrono:x64-windows@1.84.0
  * boost-container:x64-windows@1.84.0
  * boost-container-hash:x64-windows@1.84.0
  * boost-context:x64-windows@1.84.0
  * boost-conversion:x64-windows@1.84.0
  * boost-coroutine:x64-windows@1.84.0
  * boost-date-time:x64-windows@1.84.0
  * boost-describe:x64-windows@1.84.0
  * boost-detail:x64-windows@1.84.0
  * boost-endian:x64-windows@1.84.0
  * boost-exception:x64-windows@1.84.0
  * boost-function:x64-windows@1.84.0
  * boost-function-types:x64-windows@1.84.0
  * boost-functional:x64-windows@1.84.0
  * boost-fusion:x64-windows@1.84.0
  * boost-integer:x64-windows@1.84.0
  * boost-intrusive:x64-windows@1.84.0
  * boost-io:x64-windows@1.84.0
  * boost-iterator:x64-windows@1.84.0
  * boost-lexical-cast:x64-windows@1.84.0
  * boost-modular-build-helper:x64-windows@1.84.0#2
  * boost-move:x64-windows@1.84.0
  * boost-mp11:x64-windows@1.84.0
  * boost-mpl:x64-windows@1.84.0
  * boost-multi-index:x64-windows@1.84.0
  * boost-numeric-conversion:x64-windows@1.84.0
  * boost-optional:x64-windows@1.84.0
  * boost-phoenix:x64-windows@1.84.0
  * boost-pool:x64-windows@1.84.0
  * boost-predef:x64-windows@1.84.0
  * boost-property-tree:x64-windows@1.84.0
  * boost-proto:x64-windows@1.84.0
  * boost-range:x64-windows@1.84.0
  * boost-ratio:x64-windows@1.84.0
  * boost-regex:x64-windows@1.84.0
  * boost-serialization:x64-windows@1.84.0
  * boost-smart-ptr:x64-windows@1.84.0
  * boost-spirit:x64-windows@1.84.0
  * boost-system:x64-windows@1.84.0
  * boost-test:x64-windows@1.84.0
  * boost-thread:x64-windows@1.84.0
  * boost-tokenizer:x64-windows@1.84.0
  * boost-tuple:x64-windows@1.84.0
  * boost-type-index:x64-windows@1.84.0
  * boost-typeof:x64-windows@1.84.0
  * boost-unordered:x64-windows@1.84.0
  * boost-utility:x64-windows@1.84.0
  * boost-variant:x64-windows@1.84.0
  * boost-variant2:x64-windows@1.84.0
  * boost-winapi:x64-windows@1.84.0
  * curl[core,non-http,schannel,ssl,sspi]:x64-windows@8.6.0
  * openssl:x64-windows@3.2.1
    tgbot-cpp:x64-windows@1.7.2
  * vcpkg-cmake-get-vars:x64-windows@2023-12-31
  * zlib:x64-windows@1.3.1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
-- Setting "%HTTP_PROXY%" environment variables to "127.0.0.1:52066".
-- Setting "%HTTPS_PROXY%" environment variables to "127.0.0.1:52066".
-- Setting "%SOCKS_PROXY%" environment variables to "127.0.0.1:52065".
Restored 0 package(s) from C:\Users\User\AppData\Local\vcpkg\archives in 1.11 ms. Use --debug to see more details.
Installing 1/61 boost-build:x64-windows@1.84.0#1...
Building boost-build:x64-windows@1.84.0#1...
-- Downloading https://github.com/boostorg/build/archive/boost-1.84.0.tar.gz -> boostorg-build-boost-1.84.0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from C:\dev\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: C:\dev\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://github.com/boostorg/build/archive/boost-1.84.0.tar.gz
[DEBUG] Trying to hash C:\dev\vcpkg\downloads\boostorg-build-boost-1.84.0.tar.gz.18920.part
[DEBUG] C:\dev\vcpkg\downloads\boostorg-build-boost-1.84.0.tar.gz.18920.part has hash 61540a3b2b7b6167ed8286daed4b4fde515ae9e0de81d17ef688d7972a0a6325b15afbe4e9a73ec883a81d5b86998d612cadbdc79abaf1b087a74e4e6b7cc2b5
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/boostorg/build/archive/boost-1.84.0.tar.gz
File: C:\dev\vcpkg\downloads\boostorg-build-boost-1.84.0.tar.gz.18920.part
Expected hash: 11ac21b27c5c656951784734c6642a2d4efa185e074ec48561f2800203b639d4a628fec6d356bb733494889141327a7ac730ce127449bfc7d509d5d213216995
Actual hash: 61540a3b2b7b6167ed8286daed4b4fde515ae9e0de81d17ef688d7972a0a6325b15afbe4e9a73ec883a81d5b86998d612cadbdc79abaf1b087a74e4e6b7cc2b5
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1030):
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 2us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 980us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 11 s (11373807us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.


Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/boost-build/portfile.cmake:9 (vcpkg_from_github)
  scripts/ports.cmake:170 (include)


error: building boost-build:x64-windows failed with: BUILD_FAILED
Elapsed time to handle boost-build:x64-windows: 11 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-build
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[boost-build]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2Fdev%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by JonLiu1993** [comment]
@CBugBuster, What I can confirm is that there is no problem with the boost hash value. Please delete your vcpkg and your download cache, and try cloning a new vcpkg try again.

**Comment by CBugBuster** [comment]
Thank you for help @JonLiu1993

**Comment by CBugBuster** [comment]
Thank you for help @JonLiu1993
