### ISSUE TITLE
Is there a way to use tools from mentioned in vcpkg_find_acquire_program.md ?

### ISSUE THREAD

**Issue by bialpio** [microsoft/vcpkg#3686]
Is it possible to use one of the well-known tools that are mentioned in vcpkg_find_acquire_program.md? I am interested in using flex and bison and I see that they are both used by for example thrift, but they are not listed when using `vcpkg search`.

**Comment by Cheney-W** [comment]
@bialpio 
The well-known tools in vcpkg_find_acquire_program.md are separate tools, not third-party libraries. As long as they are downloaded to the dwonload\tools directory, you can use them directly.
Vcpkg search is a built-in command of vcpkg, which is used to find the third-party libraries supported by vcpkg, so it can't find flex and bison.
