### ISSUE TITLE
[boost-build] build failure

### ISSUE THREAD

**Issue by suncs2001** [microsoft/vcpkg#36864]
### Operating system

Windows10

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
'./vcpkg install boost’
```

### Failure logs

Building boost-numeric-conversion:x64-windows@1.84.0...
-- Downloading https://github.com/boostorg/numeric_conversion/archive/boost-1.84.0.tar.gz -> boostorg-numeric_conversion-boost-1.84.0.tar.gz...
-- Extracting source E:/vcpkg/downloads/boostorg-numeric_conversion-boost-1.84.0.tar.gz
-- Using source at E:/vcpkg/buildtrees/boost-numeric-conversion/src/ost-1.84.0-aa89cfac9c.clean
-- Copying headers
-- Copying headers done
-- Installing: E:/vcpkg/packages/boost-numeric-conversion_x64-windows/share/boost-numeric-conversion/usage
-- Installing: E:/vcpkg/packages/boost-numeric-conversion_x64-windows/share/boost-numeric-conversion/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 34.3 ms.
Elapsed time to handle boost-numeric-conversion:x64-windows: 4.3 s
boost-numeric-conversion:x64-windows package ABI: d6a5992f98f8e4861eaf2408691246056572b488190b0a223fb67145e97995c0
Installing 34/168 boost-parameter:x64-windows@1.84.0...
Building boost-parameter:x64-windows@1.84.0...
-- Downloading https://github.com/boostorg/parameter/archive/boost-1.84.0.tar.gz -> boostorg-parameter-boost-1.84.0.tar.gz...
-- Extracting source E:/vcpkg/downloads/boostorg-parameter-boost-1.84.0.tar.gz
-- Using source at E:/vcpkg/buildtrees/boost-parameter/src/ost-1.84.0-abe516310d.clean
-- Copying headers
-- Copying headers done
-- Installing: E:/vcpkg/packages/boost-parameter_x64-windows/share/boost-parameter/usage
-- Installing: E:/vcpkg/packages/boost-parameter_x64-windows/share/boost-parameter/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 40.2 ms.
Elapsed time to handle boost-parameter:x64-windows: 4.5 s
boost-parameter:x64-windows package ABI: 20793aff8f20bbca611c5ed3aaafb449677de79f01782965f1d47a16e288e5dd
Installing 35/168 boost-build:x64-windows@1.84.0...
Building boost-build:x64-windows@1.84.0...
-- Downloading https://github.com/boostorg/build/archive/boost-1.84.0.tar.gz -> boostorg-build-boost-1.84.0.tar.gz...
-- Extracting source E:/vcpkg/downloads/boostorg-build-boost-1.84.0.tar.gz
-- Applying patch 0002-fix-get-version.patch
-- Applying patch 0003-fix-emscripten.patch
-- Applying patch 0004-workaround-MSVC-codegen-bug-in-17.5-on-ARM64.patch
CMake Error at scripts/cmake/z_vcpkg_apply_patches.cmake:34 (message):
  Applying patch failed: Checking patch src/engine/glob.cpp...

  error: while searching for:

   * globchars() - build a bitlist to check for character group match.
   */

  static void globchars( const char * s, const char * e, char * b )

  {

      int neg = 0;

  error: patch failed: src/engine/glob.cpp:111

  error: src/engine/glob.cpp: patch does not apply

Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive.cmake:147 (z_vcpkg_apply_patches)
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:8 (vcpkg_extract_source_archive)
  scripts/cmake/vcpkg_from_github.cmake:113 (vcpkg_extract_source_archive_ex)
  ports/boost-build/portfile.cmake:9 (vcpkg_from_github)
  scripts/ports.cmake:170 (include)

error: building boost-build:x64-windows failed with: BUILD_FAILED
Elapsed time to handle boost-build:x64-windows: 7.7 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-build
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[boost-build]+Build+error+on+x64-windows&body=Copy+issue+body+from+E%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

i use the latest vcpkg version，This problem also exists on my colleague's computer.

**Comment by jimwang118** [comment]
Sorry, I cannot reproduce this issue locally.
![image](https://github.com/microsoft/vcpkg/assets/122244446/82134f7f-1fc4-425a-8947-ff7e8bbdaa4a)

**Comment by JackBoosY** [comment]
@jimwang118 Try to re-make the patch to see whether there have some differences?

**Comment by suncs2001** [comment]
I also searched online and found that few people have similar problems. I suspect it may be related to the installation of an encryption system on my computer, but I am not sure. I plan to go home tonight and try again using my home computer

**Comment by suncs2001** [comment]
sorry for submit the issue， i try to install boost on my home computer last night, and it was successed.  so i  tracked the install process this morning and it is likely that the files in the download directory were encrypted(we have a encrypt system) when they were decompressed to the buildtrees directory.   so when execute the path apply and call git appypath command,  for the reason of file was encrypted , git can not find the corresponding function.  Although I cannot be entirely certain, it is highly likely that this is the reason.

To solve this problem, I need to know which decompression process was called during the installation process to extract the files from the download directory into the buildtree directory. This way, I can process the decompression process in the encryption system to avoid encrypting the extracted files. 
can somebody tell me which decompression process was called when extracting the source??
