### ISSUE TITLE
Share a roadmap for vcpkg

### ISSUE THREAD

**Issue by martin-s** [microsoft/vcpkg#3687]
I would like to see a roadmap to get a picture of the future topics that drive vcpkg. What is your opinion on that?

**Comment by vicroms** [comment]
It took a while but we finally have a roadmap publicly available.
Here is the [original announcement via blog post](https://devblogs.microsoft.com/cppblog/vcpkg-2020-04-update-and-product-roadmap/) and the [roadmap page in our wiki](https://github.com/microsoft/vcpkg/wiki/Roadmap).

**Comment by PhoebeHui** [comment]
Commnents to https://github.com/microsoft/vcpkg/issues/11177 if you like.
