### ISSUE TITLE
Cannot disable manifest mode

### ISSUE THREAD

**Issue by sarlinpe** [microsoft/vcpkg#36888]
vcpkg crashes on install if a parent directory happens to have a file or directory named `vcpkg.json`. Here is the setup:
```bash
/cluster/home/vcpkg.json  # some file over which I have no control and no permission and want to ignore
/cluster/home/username  # my home directory
/cluster/home/username/vcpkg  # my vcpkg install
```

Result:
```bash
$ cd /cluster/home/username/vcpkg
$ ./vcpkg install --triplet x64-linux-release any-port-name
Failed to load manifest from directory /cluster/home
try_read_contents("/cluster/home/vcpkg.json"): Permission deniednote: updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
```

I need to disable vcpkg's manifest mode and tell it to ignore this file. It seems that there is no way to do so.

**Comment by BillyONeal** [comment]
This was fixed in https://github.com/microsoft/vcpkg-tool/pull/1535 / https://github.com/microsoft/vcpkg/pull/42115
