### ISSUE TITLE
[google-cloud-cpp] Build error on x64-windows

### ISSUE THREAD

**Issue by ArkturT** [microsoft/vcpkg#36880]
Copy issue body from C:/Users/tarik/Desktop/tarikhdamir/C++/vcpkg/installed/vcpkg/issue_body.md
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/Users/tarik/Desktop/tarikhdamir/C++/vcpkg/downloads/tools/cmake-3.27.1-windows/cmake-3.27.1-windows-i386/bin/cmake.exe C:/Users/tarik/Desktop/tarikhdamir/C++/vcpkg/buildtrees/google-cloud-cpp/src/v2.21.0-2ac77ee1cc.clean -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=C:/Users/tarik/Desktop/tarikhdamir/C++/vcpkg/packages/google-cloud-cpp_x64-windows/debug -DFETCHCONTENT_FULLY_DISCONNECTED=ON -DGOOGLE_CLOUD_CPP_ENABLE=bigquery bigtable iam pubsub spanner storage -DGOOGLE_CLOUD_CPP_ENABLE_MACOS_OPENSSL_CHECK=OFF -DGOOGLE_CLOUD_CPP_ENABLE_WERROR=OFF -DGOOGLE_CLOUD_CPP_ENABLE_CCACHE=OFF -DGOOGLE_CLOUD_CPP_ENABLE_EXAMPLES=OFF -DBUILD_TESTING=OFF -DGOOGLE_CLOUD_CPP_ENABLE_CTYPE_CORD_WORKAROUND=ON "-DCMAKE_MAKE_PROGRAM=C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/tarik/Desktop/tarikhdamir/C++/vcpkg/scripts/toolchains/windows.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=v143 -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=C:/Users/tarik/Desktop/tarikhdamir/C++/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=C:/Users/tarik/Desktop/tarikhdamir/C++/vcpkg -D_VCPKG_INSTALLED_DIR=C:/Users/tarik/Desktop/tarikhdamir/C++/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF

**Comment by Cheney-W** [comment]
Please see [#30604](https://github.com/microsoft/vcpkg/issues/30604) for how to report an issue.
