### ISSUE TITLE
[boost-regex] Build error on x64-linux

### ISSUE THREAD

**Issue by jgcop** [microsoft/vcpkg#36895]
Package: boost-regex:x64-linux@1.83.0

**Host Environment**

- Host: x64-linux
- Compiler: GNU 11.4.0
-    vcpkg-tool version: 2024-02-07-8a83681f921b10d86ae626fd833c253f4f8c355b
    vcpkg-scripts version: 13bde2ff1 2024-02-17 (4 days ago)

**To Reproduce**

`vcpkg install `
**Failure logs**

```
-- Using cached boostorg-regex-boost-1.83.0.tar.gz.
-- Cleaning sources at /opt/vcpkg/buildtrees/boost-regex/src/ost-1.83.0-4f302d8536.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /opt/vcpkg/downloads/boostorg-regex-boost-1.83.0.tar.gz
-- Using source at /opt/vcpkg/buildtrees/boost-regex/src/ost-1.83.0-4f302d8536.clean
-- Including /home/tanto/.cache/vcpkg/registries/git-trees/423f035001a6e046e2f94dc3ac68201a4a3d0307/b2-options.cmake
-- Found external ninja('1.11.1.git.kitware.jobserver-1').
-- Getting CMake variables for x64-linux
-- Configuring x64-linux
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: /opt/vcpkg/downloads/tools/cmake-3.27.1-linux/cmake-3.27.1-linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j3
    Working Directory: /opt/vcpkg/buildtrees/boost-regex/x64-linux-dbg
    See logs for more information:
      /opt/vcpkg/buildtrees/boost-regex/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  /mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/default/vcpkg_installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  /mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/default/vcpkg_installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  /mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/default/vcpkg_installed/x64-linux/share/boost-build/boost-modular-build.cmake:139 (vcpkg_cmake_install)
  /home/tanto/.cache/vcpkg/registries/git-trees/423f035001a6e046e2f94dc3ac68201a4a3d0307/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:170 (include)



```
<details><summary>/opt/vcpkg/buildtrees/boost-regex/install-x64-linux-dbg-out.log</summary>

```
Change Dir: '/opt/vcpkg/buildtrees/boost-regex/x64-linux-dbg'

Run Build Command(s): /home/tanto/.local/bin/ninja -v -v -j3 install
[1/2] cd /opt/vcpkg/buildtrees/boost-regex/src/ost-1.83.0-4f302d8536.clean/build && "/mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/default/vcpkg_installed/x64-linux/tools/boost-build/b2" toolset=gcc --user-config=/opt/vcpkg/buildtrees/boost-regex/x64-linux-dbg/user-config.jam --stagedir=/opt/vcpkg/buildtrees/boost-regex/x64-linux-dbg/stage --build-dir=/opt/vcpkg/buildtrees/boost-regex/x64-linux-dbg runtime-link=shared link=static address-model=64 architecture=x86 target-os=linux threadapi=pthread variant=debug --layout=system -sICU_PATH="/usr" --disable-icu --with-atomic --with-random --with-date_time --with-filesystem --with-system --with-thread --with-chrono -j 3 -sBOOST_ROOT=/mnt/c/Program\ Files/Microsoft\ Visual\ Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/default/vcpkg_installed/x64-linux/tools/boost-build -sBOOST_BUILD_PATH=/mnt/c/Program\ Files/Microsoft\ Visual\ Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/default/vcpkg_installed/x64-linux/tools/boost-build --debug-configuration --debug-building --debug-generators --ignore-site-config --hash -q debug-symbols=on -d +2 threading=multi stage
FAILED: CMakeFiles/boost /opt/vcpkg/buildtrees/boost-regex/x64-linux-dbg/CMakeFiles/boost 
cd /opt/vcpkg/buildtrees/boost-regex/src/ost-1.83.0-4f302d8536.clean/build && "/mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/default/vcpkg_installed/x64-linux/tools/boost-build/b2" toolset=gcc --user-config=/opt/vcpkg/buildtrees/boost-regex/x64-linux-dbg/user-config.jam --stagedir=/opt/vcpkg/buildtrees/boost-regex/x64-linux-dbg/stage --build-dir=/opt/vcpkg/buildtrees/boost-regex/x64-linux-dbg runtime-link=shared link=static address-model=64 architecture=x86 target-os=linux threadapi=pthread variant=debug --layout=system -sICU_PATH="/usr" --disable-icu --with-atomic --with-random --with-date_time --with-filesystem --with-system --with-thread --with-chrono -j 3 -sBOOST_ROOT=/mnt/c/Program\ Files/Microsoft\ Visual\ Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/default/vcpkg_installed/x64-linux/tools/boost-build -sBOOST_BUILD_PATH=/mnt/c/Program\ Files/Microsoft\ Visual\ Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/default/vcpkg_installed/x64-linux/tools/boost-build --debug-configuration --debug-building --debug-generators --ignore-site-config --hash -q debug-symbols=on -d +2 threading=multi stage
notice: loading B2 from /mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/default/vcpkg_installed/x64-linux/tools/boost-build/src/kernel/bootstrap.jam
notice: Site configuration files will be ignored due to the
notice: --ignore-site-config command-line option.
notice: Loading explicitly specified user configuration file:
    /opt/vcpkg/buildtrees/boost-regex/x64-linux-dbg/user-config.jam
notice: Searching '/opt/vcpkg/buildtrees/boost-regex/x64-linux-dbg' for user-config configuration file 'user-config.jam'.
notice: Loading user-config configuration file 'user-config.jam' from '/opt/vcpkg/buildtrees/boost-regex/x64-linux-dbg'.
notice: will use '/usr/bin/c++' for gcc, condition <toolset>gcc-11
notice: using gcc libraries :: <toolset>gcc-11 :: /usr/bin /usr/lib /usr/lib32 /usr/lib64
notice: using gcc archiver :: <toolset>gcc-11 :: /usr/bin/ar
notice: using rc compiler :: <toolset>gcc-11 :: windres
[errno 2] boostcpp.jam (No such file or directory)
../Jamroot.jam:9: in modules.load
ERROR: rule "boostcpp.set-version" unknown in module "Jamfile</opt/vcpkg/buildtrees/boost-regex/src/ost-1.83.0-4f302d8536.clean>".
/mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/default/vcpkg_installed/x64-linux/tools/boost-build/src/build/project.jam:520: in load-jamfile
/mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/default/vcpkg_installed/x64-linux/tools/boost-build/src/build/project.jam:67: in load
/mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/default/vcpkg_installed/x64-linux/tools/boost-build/src/build/project.jam:137: in load-parent
/mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/default/vcpkg_installed/x64-linux/tools/boost-build/src/build/project.jam:661: in initialize
/mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/default/vcpkg_installed/x64-linux/tools/boost-build/src/build/project.jam:496: in load-jamfile
/mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/default/vcpkg_installed/x64-linux/tools/boost-build/src/build/project.jam:67: in load
/mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/default/vcpkg_installed/x64-linux/tools/boost-build/src/build/project.jam:200: in project.find
/mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/default/vcpkg_installed/x64-linux/tools/boost-build/src/build-system.jam:618: in load
/mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/default/vcpkg_installed/x64-linux/tools/boost-build/src/kernel/modules.jam:294: in import
/mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/default/vcpkg_installed/x64-linux/tools/boost-build/src/kernel/bootstrap.jam:135: in module scope
ninja: build stopped: subcommand failed.
```
</details>

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "dependencies": [
    "crow",
    "fmt"
  ]
}

```
</details>

**Comment by LilyWangLL** [comment]
Thanks for posting this issue, the version of boost-regex on latest vcpkg is 1.84.0, please update your vcpkg and rebuild it.
```
./vcpkg search boost-regex
boost-regex              1.84.0           Boost regex module
```

**Comment by jgcop** [comment]
if i run this command he prints the following out on my wsl ubuntu linux:
boost-regex              1.84.0           Boost regex module
boost-regex[icu]                          ICU backend for Boost.Regex
but if i run the cmake from my windows with visual studio 2022 he download the following package:
Installing 57/89 boost-regex:x64-linux@1.83.0...
1> [CMake] Building boost-regex:x64-linux@1.83.0...
1> [CMake] -- Installing port from location: /home/tanto/.cache/vcpkg/registries/git-trees/423f035001a6e046e2f94dc3ac68201a4a3d0307
1> [CMake] -- Downloading https://github.com/boostorg/regex/archive/boost-1.83.0.tar.gz -> boostorg-regex-boost-1.83.0.tar.gz...
and it runs in the same error:

Change Dir: '/opt/vcpkg/buildtrees/boost-regex/x64-linux-dbg'

Run Build Command(s): /home/tanto/.local/bin/ninja -v -v -j3 install
[1/2] cd /opt/vcpkg/buildtrees/boost-regex/src/ost-1.83.0-4f302d8536.clean/build && "/mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/wsl-linux/vcpkg_installed/x64-linux/tools/boost-build/b2" toolset=gcc --user-config=/opt/vcpkg/buildtrees/boost-regex/x64-linux-dbg/user-config.jam --stagedir=/opt/vcpkg/buildtrees/boost-regex/x64-linux-dbg/stage --build-dir=/opt/vcpkg/buildtrees/boost-regex/x64-linux-dbg runtime-link=shared link=static address-model=64 architecture=x86 target-os=linux threadapi=pthread variant=debug --layout=system -sICU_PATH="/usr" --disable-icu --with-atomic --with-random --with-date_time --with-filesystem --with-system --with-thread --with-chrono -j 3 -sBOOST_ROOT=/mnt/c/Program\ Files/Microsoft\ Visual\ Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/wsl-linux/vcpkg_installed/x64-linux/tools/boost-build -sBOOST_BUILD_PATH=/mnt/c/Program\ Files/Microsoft\ Visual\ Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/wsl-linux/vcpkg_installed/x64-linux/tools/boost-build --debug-configuration --debug-building --debug-generators --ignore-site-config --hash -q debug-symbols=on -d +2 threading=multi stage
FAILED: CMakeFiles/boost /opt/vcpkg/buildtrees/boost-regex/x64-linux-dbg/CMakeFiles/boost
cd /opt/vcpkg/buildtrees/boost-regex/src/ost-1.83.0-4f302d8536.clean/build && "/mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/wsl-linux/vcpkg_installed/x64-linux/tools/boost-build/b2" toolset=gcc --user-config=/opt/vcpkg/buildtrees/boost-regex/x64-linux-dbg/user-config.jam --stagedir=/opt/vcpkg/buildtrees/boost-regex/x64-linux-dbg/stage --build-dir=/opt/vcpkg/buildtrees/boost-regex/x64-linux-dbg runtime-link=shared link=static address-model=64 architecture=x86 target-os=linux threadapi=pthread variant=debug --layout=system -sICU_PATH="/usr" --disable-icu --with-atomic --with-random --with-date_time --with-filesystem --with-system --with-thread --with-chrono -j 3 -sBOOST_ROOT=/mnt/c/Program\ Files/Microsoft\ Visual\ Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/wsl-linux/vcpkg_installed/x64-linux/tools/boost-build -sBOOST_BUILD_PATH=/mnt/c/Program\ Files/Microsoft\ Visual\ Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/wsl-linux/vcpkg_installed/x64-linux/tools/boost-build --debug-configuration --debug-building --debug-generators --ignore-site-config --hash -q debug-symbols=on -d +2 threading=multi stage
notice: loading B2 from /mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/wsl-linux/vcpkg_installed/x64-linux/tools/boost-build/src/kernel/bootstrap.jam
notice: Site configuration files will be ignored due to the
notice: --ignore-site-config command-line option.
notice: Loading explicitly specified user configuration file:
    /opt/vcpkg/buildtrees/boost-regex/x64-linux-dbg/user-config.jam
notice: Searching '/opt/vcpkg/buildtrees/boost-regex/x64-linux-dbg' for user-config configuration file 'user-config.jam'.
notice: Loading user-config configuration file 'user-config.jam' from '/opt/vcpkg/buildtrees/boost-regex/x64-linux-dbg'.
notice: will use '/usr/bin/g++' for gcc, condition <toolset>gcc-13
notice: using gcc libraries :: <toolset>gcc-13 :: /usr/bin /usr/lib /usr/lib32 /usr/lib64
notice: using gcc archiver :: <toolset>gcc-13 :: /usr/bin/ar
notice: using rc compiler :: <toolset>gcc-13 :: windres
[errno 2] boostcpp.jam (No such file or directory)
../Jamroot.jam:9: in modules.load
ERROR: rule "boostcpp.set-version" unknown in module "Jamfile</opt/vcpkg/buildtrees/boost-regex/src/ost-1.83.0-4f302d8536.clean>".
/mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/wsl-linux/vcpkg_installed/x64-linux/tools/boost-build/src/build/project.jam:520: in load-jamfile
/mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/wsl-linux/vcpkg_installed/x64-linux/tools/boost-build/src/build/project.jam:67: in load
/mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/wsl-linux/vcpkg_installed/x64-linux/tools/boost-build/src/build/project.jam:137: in load-parent
/mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/wsl-linux/vcpkg_installed/x64-linux/tools/boost-build/src/build/project.jam:661: in initialize
/mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/wsl-linux/vcpkg_installed/x64-linux/tools/boost-build/src/build/project.jam:496: in load-jamfile
/mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/wsl-linux/vcpkg_installed/x64-linux/tools/boost-build/src/build/project.jam:67: in load
/mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/wsl-linux/vcpkg_installed/x64-linux/tools/boost-build/src/build/project.jam:200: in project.find
/mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/wsl-linux/vcpkg_installed/x64-linux/tools/boost-build/src/build-system.jam:618: in load
/mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/wsl-linux/vcpkg_installed/x64-linux/tools/boost-build/src/kernel/modules.jam:294: in import
/mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/wsl-linux/vcpkg_installed/x64-linux/tools/boost-build/src/kernel/bootstrap.jam:135: in module scope
ninja: build stopped: subcommand failed.

on windows and on linux the same result by ./vcpkg search boost-regex

**Comment by jgcop** [comment]
Hi there,
i analyse that the problem are not the repository. I clone this after you  told me, i have to use boost-regex 1.84.
OK, on both os i run the given command: vcpkg search boost-regex
on wsl-linux and on windows i got the following output:
    boost-regex 1.84.0 Boost regex module
    boost-regex[icu] ICU backend for Boost.Regex
i think every looks good, i got the right version 1.84
but if i restart the cmake command on visual studio, he tooks everytime the old version:

Building boost-regex:x64-linux@1.83.0...
-- Installing port from location: /home/tanto/.cache/vcpkg/registries/git-trees/423f035001a6e046e2f94dc3ac68201a4a3d0307
-- Using cached boostorg-regex-boost-1.83.0.tar.gz.
-- Cleaning sources at /opt/vcpkg/buildtrees/boost-regex/src/ost-1.83.0-4f302d8536.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /opt/vcpkg/downloads/boostorg-regex-boost-1.83.0.tar.gz
-- Using source at /opt/vcpkg/buildtrees/boost-regex/src/ost-1.83.0-4f302d8536.clean
-- Including /home/tanto/.cache/vcpkg/registries/git-trees/423f035001a6e046e2f94dc3ac68201a4a3d0307/b2-options.cmake
-- Found external ninja('1.11.1.git.kitware.jobserver-1').
-- Getting CMake variables for x64-linux
-- Configuring x64-linux
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: /home/tanto/.local/lib/python3.11/site-packages/cmake/data/bin/cmake --build . --config Debug --target install -- -v -j3
    Working Directory: /opt/vcpkg/buildtrees/boost-regex/x64-linux-dbg
    See logs for more information:
      /opt/vcpkg/buildtrees/boost-regex/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  /mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/wsl-linux/vcpkg_installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  /mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/wsl-linux/vcpkg_installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  /mnt/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/C:/Users/winmc/Desktop/cpp_workspace/WebApp/out/build/wsl-linux/vcpkg_installed/x64-linux/share/boost-build/boost-modular-build.cmake:139 (vcpkg_cmake_install)
  /home/tanto/.cache/vcpkg/registries/git-trees/423f035001a6e046e2f94dc3ac68201a4a3d0307/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:170 (include)
error: building boost-regex:x64-linux failed with: BUILD_FAILED

but i don't understand why? is there an entry to give VS the right repo of vcpkg?
on my CMakeUserPresets.cmake i only use the both entries:
the first one for windows (works fine)
the second on for my wsl-linux (not working, because the wrong version)
{
  "name": "default",
  "cacheVariables": {
    "CMAKE_TOOLCHAIN_FILE": "C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake"
  }
},
{
  "name": "wsl-linux",
  "cacheVariables": {
    "CMAKE_TOOLCHAIN_FILE": "/opt/vcpkg/scripts/buildsystems/vcpkg.cmake"
  }
}
