### ISSUE TITLE
CMake FindBoost can't determine release vs. debug libraries

### ISSUE THREAD

**Issue by Orvid** [Microsoft/vcpkg#369]
With the change to remove the extra versioning on the boost libraries, CMake's `FindBoost` module is no longer able to distinguish between the debug and release libraries, and ends up thinking that the debug version is both the debug and release versions of the library. The same issue also occurs with `FindOpenSSL`. The debug version of `boost::atomic` was previously named `boost_atomic-vc140-mt-gd-1_62.lib` and is now named `boost_atomic.lib`. This confuses CMake.

As Boost has a well-established naming layout on Windows, vcpkg should probably stick with that convention.

**Comment by chrullrich** [comment]
Concur; additionally, the nonversioned naming makes it impossible for components built with different Boost versions to coexist in the same directory. This may not be a major issue, but it is a bit annoying.

**Comment by alexkaratarakis** [comment]
We have removed `--layout=system`, so lib names are like `boost_atomic-vc140-mt-gd-1_62.lib` once again. 
Currently we are renaming the static lib files to match the names of the dynamic lib files so that `FindBoost.cmake` can pick them up.
