### ISSUE TITLE
[draco] Build error

### ISSUE THREAD

**Issue by rossetti73** [microsoft/vcpkg#36902]
Package: draco:x64-windows -> 1.5.7

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.29.30147.0
-    vcpkg-tool version: 2023-10-18-27de5b69dac4b6fe8259d283cd4011e6d20a84ce
    vcpkg-scripts version: 62f4702df 2024-02-21 (56 minutes ago)

**To Reproduce**

`vcpkg install draco`
**Failure logs**

```
-- Using cached google-draco-1.5.7.tar.gz.
-- Cleaning sources at C:/code/c++/dev/vcpkg/buildtrees/draco/src/1.5.7-c71437a6c1.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/code/c++/dev/vcpkg/downloads/google-draco-1.5.7.tar.gz
-- Applying patch fix-compile-error-uwp.patch
-- Applying patch fix-uwperror.patch
-- Applying patch fix-pkgconfig.patch
-- Applying patch disable-symlinks.patch
-- Applying patch install-linkage.diff
-- Using source at C:/code/c++/dev/vcpkg/buildtrees/draco/src/1.5.7-c71437a6c1.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/code/c++/dev/vcpkg/buildtrees/draco/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\code\c++\dev\vcpkg\buildtrees\draco\config-x64-windows-dbg-CMakeCache.txt.log
      C:\code\c++\dev\vcpkg\buildtrees\draco\config-x64-windows-rel-CMakeCache.txt.log
      C:\code\c++\dev\vcpkg\buildtrees\draco\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:252 (vcpkg_execute_required_process)
  ports/draco/portfile.cmake:19 (vcpkg_cmake_configure)
  scripts/ports.cmake:170 (include)


Any helps?

**Comment by jimwang118** [comment]
Sorry, I haven't reproduced this issue locally. You can try updating `vcpkg` and re-running `.\bootstrap-vcpkg.bat`.
![image](https://github.com/microsoft/vcpkg/assets/122244446/46c92d13-487b-4027-8bb6-f204b6af1bac)

**Comment by dg0yt** [comment]
> Any helps?

1. As indicateed:
   >     See logs for more information:
   >       C:\code\c++\dev\vcpkg\buildtrees\draco\config-x64-windows-dbg-CMakeCache.txt.log
   >       C:\code\c++\dev\vcpkg\buildtrees\draco\config-x64-windows-rel-CMakeCache.txt.log
   >       C:\code\c++\dev\vcpkg\buildtrees\draco\config-x64-windows-out.log

2. Use a working directory path without special characters (` `, `+`). There always packages use the path in unexpected way (without quotes, as a regex).

**Comment by rossetti73** [comment]
thanks


e-mail: ***@***.***
e-mail: ***@***.***

P Please consider the environment before printing this e-mail


Il giorno gio 22 feb 2024 alle ore 05:54 Kai Pastor <
***@***.***> ha scritto:

**Comment by jimwang118** [comment]
@rossetti73 Can you install normally using an installation path without special characters?

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
