### ISSUE TITLE
Use a different toolchain than the default

### ISSUE THREAD

**Issue by robmikh** [Microsoft/vcpkg#3691]
Sorry if this is already possible, but I did some digging and couldn't convince myself I knew what I was doing. Love the tool so far!

I'm running into an issue where (I'm assuming) vcpkg is using g++ or gcc on Linux, but the project I was hoping to use vcpkg with uses clang. This led to some pretty gnarly linker errors, and switching the project to g++/gcc isn't an option for us. 

Is there a way to force vcpkg to use clang to build libraries? Would I have to define my own triplet?

**Comment by ras0219-msft** [comment]
Thanks for posting this issue!

At the moment, we do not sufficiently sanitize environment variables on Linux and mac, so you can set CC and CXX to override the compiler.

In the longer term, we expect this to be set via a triplet (via a toolchain file). This works today, but is slightly too verbose to describe on mobile.

**Comment by robmikh** [comment]
That works great, thanks! I was able to build sdl2 and glm with clang, and then build the rest of my project with clang.

**Comment by PhoebeHui** [comment]
The issue looks solved.

**Comment by iskiselev** [comment]
@ras0219-msft can you give hints what should be the proper way to set it in the triplet?
Will be using `SET(CMAKE_C_COMPILER ...)` and `SET(CMAKE_CXX_COMPILER ...)` in triplet enough for it?
