### ISSUE TITLE
[skia] Build error on x64-windows with feature harfbuzz

### ISSUE THREAD

**Issue by StarGate-One** [microsoft/vcpkg#36928]
**Environment**
Windows 11 Enterprise Version [10.0.22631.3155] 

Visual Studio Community 2022 Version: [17.9.0]  VS Tools Version: [14.39.33519] 
Microsoft (R) C/C++ Optimizing Compiler Version [19.39.33519] for x64  

Vcpkg Version [2024-02-22-c549365bf9ffa652a7be7682637cdfa0c0a683c1] 
Vcpkg Scripts Version [2024-02-22-62aa44929954469878eb8fc562af706a8f5615a5] 

**To Reproduce**
->vcpkg install skia[harfbuzz]
Computing installation plan...
The following packages will be built and installed:
    skia[core,gl,harfbuzz]:x64-windows@122
Installing 1/1 skia[core,gl,harfbuzz]:x64-windows@122...
Building skia[core,gl,harfbuzz]:x64-windows@122...
-- Using cached google-skia-c3feddb877388498cc9a491e9504268a53607b15.tar.gz.
-- Extracting source D:/vcpkg-downloads/google-skia-c3feddb877388498cc9a491e9504268a53607b15.tar.gz
-- Applying patch disable-msvc-env-setup.patch
-- Applying patch disable-dev-test.patch
-- Applying patch skia-include-string.patch
-- Applying patch bentleyottmann-build.patch
-- Applying patch graphite.patch
-- Applying patch vulkan-headers.patch
-- Using source at D:/vcpkg/buildtrees/skia/src/8a53607b15-a242946b1f.clean
-- Creating third_party/externals/dng_sdk
-- Using cached D:/vcpkg-downloads/skia-c8d0c9b1d16bfda56f15165d39e0ffa360a11123.tar.gz
-- Extracting source D:/vcpkg-downloads/skia-c8d0c9b1d16bfda56f15165d39e0ffa360a11123.tar.gz
-- Using source at D:/vcpkg/buildtrees/skia/src/a360a11123-3e98e4208e.clean
-- Creating third_party/externals/piex
-- Using cached D:/vcpkg-downloads/skia-bb217acdca1cc0c16b704669dd6f91a1b509c406.tar.gz
-- Extracting source D:/vcpkg-downloads/skia-bb217acdca1cc0c16b704669dd6f91a1b509c406.tar.gz
-- Using source at D:/vcpkg/buildtrees/skia/src/a1b509c406-84c7e7ac21.clean
-- Creating third_party/externals/sfntly
-- Using cached D:/vcpkg-downloads/skia-b55ff303ea2f9e26702b514cf6a3196a2e3e2974.tar.gz
-- Extracting source D:/vcpkg-downloads/skia-b55ff303ea2f9e26702b514cf6a3196a2e3e2974.tar.gz
-- Using source at D:/vcpkg/buildtrees/skia/src/6a2e3e2974-0a8350d725.clean
-- Creating third_party/externals/wuffs
-- Using cached D:/vcpkg-downloads/skia-e3f919ccfe3ef542cfc983a82146070258fb57f8.tar.gz
-- Extracting source D:/vcpkg-downloads/skia-e3f919ccfe3ef542cfc983a82146070258fb57f8.tar.gz
-- Using source at D:/vcpkg/buildtrees/skia/src/0258fb57f8-69c6ce6bfb.clean
-- Getting CMake variables for x64-windows
-- Generating build (x64-windows-dbg)...
-- Generating build (x64-windows-rel)...
-- vcpkg-gn: fixing ninja paths for Windows
-- Building (x64-windows-dbg)...
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: D:/vcpkg-downloads/tools/ninja/1.10.2-windows/ninja.exe -C D:/vcpkg/buildtrees/skia/x64-windows-dbg :skia :modules
    Working Directory: D:/vcpkg/buildtrees/skia/src/8a53607b15-a242946b1f.clean
    See logs for more information:
      D:\vcpkg\buildtrees\skia\build-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_ninja.cmake:3 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_build_ninja.cmake:24 (z_vcpkg_build_ninja_build)
  ports/skia/skia-functions.cmake:325 (vcpkg_build_ninja)
  ports/skia/skia-functions.cmake:433 (skia_gn_install_build_type)
  ports/skia/portfile.cmake:295 (skia_gn_install)
  scripts/ports.cmake:170 (include)

error: building skia:x64-windows failed with: BUILD_FAILED
Elapsed time to handle skia:x64-windows: 58 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+skia
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[skia]+Build+error+on+x64-windows&body=Copy+issue+body+from+D%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Failure logs**
[issue_body.md](https://github.com/microsoft/vcpkg/files/14380692/issue_body.md)

**Expected Behavior**
Port skia installed with feature harfbuzz

**Additional context**

**Comment by FrankXie05** [comment]
@StarGate-One 
>skia[core,gl,harfbuzz]:x64-windows@122

What version is this `122`?

**Comment by StarGate-One** [comment]
> @StarGate-One
> 
> > skia[core,gl,harfbuzz]:x64-windows@122
> 
> What version is this `122`?

Yes, the latest 122 from commit [36680](https://github.com/microsoft/vcpkg/pull/36680).

**Comment by FrankXie05** [comment]
Reproduce locally using the latest vcpkg。

**Comment by dg0yt** [comment]
Hm, `skia[harfbuzz]` is not a default feature for `windows & !static`. I think it was also meant to be marked as unsupported on `windows & !static`. Similar to `skia[icu]`.

**Comment by StarGate-One** [comment]
Hi @dg0yt  - how would one know whether is should or should not be a feature for a specific port with a specific OS and/or triplet?
I am learning and trying to understand is all, so if I come across a similar situation in the future?
Thank you very much for all the help you provide.
