### ISSUE TITLE
[opengl] build failure

### ISSUE THREAD

**Issue by phume03** [microsoft/vcpkg#36937]
### Operating system

Windows

### Compiler

MinGW

### Steps to reproduce the behavior

```Shell
Build and run CMake+vcpkg project from VS GUI.
```

### Failure logs

 Installing 1/18 opengl:x64-windows...
1> [CMake] Building opengl:x64-windows...
1> [CMake] -- Installing port from location: <User Path>\AppData\Local\vcpkg\registries\git-trees\<hash-latest>
1> [CMake] -- Installing: <Project Path>/out/build/default/vcpkg_installed/vcpkg/pkgs/opengl_x64-windows/include/GL/gl.h
1> [CMake] -- Installing: <Project Path>/out/build/default/vcpkg_installed/vcpkg/pkgs/opengl_x64-windows/include/GL/glu.h
1> [CMake] -- Installing: <Project Path>/out/build/default/vcpkg_installed/vcpkg/pkgs/opengl_x64-windows/lib/OpenGL32.Lib
1> [CMake] -- Installing: <Project Path>/out/build/default/vcpkg_installed/vcpkg/pkgs/opengl_x64-windows/lib/GlU32.Lib
1> [CMake] -- Installing: <Project Path>/out/build/default/vcpkg_installed/vcpkg/pkgs/opengl_x64-windows/debug/lib/OpenGL32.Lib
1> [CMake] -- Installing: <Project Path>/out/build/default/vcpkg_installed/vcpkg/pkgs/opengl_x64-windows/debug/lib/GlU32.Lib
1> [CMake] -- Fixing pkgconfig file: <Project Path>/out/build/default/vcpkg_installed/vcpkg/pkgs/opengl_x64-windows/lib/pkgconfig/glu.pc
1> [CMake] -- Fixing pkgconfig file: <Project Path>/out/build/default/vcpkg_installed/vcpkg/pkgs/opengl_x64-windows/lib/pkgconfig/opengl.pc
1> [CMake] -- Using cached mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
1> [CMake] -- Downloading https://mirror.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst -> mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst...

...
1> [CMake] error: Failed to download from mirror set
...
1> [CMake] [DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1003): 
1> [CMake] [DEBUG] Time in subprocesses: 0us
1> [CMake] [DEBUG] Time in parsing JSON: 17us
1> [CMake] [DEBUG] Time in JSON reader: 0us
1> [CMake] [DEBUG] Time in filesystem: 2804us
1> [CMake] [DEBUG] Time in loading ports: 0us
1> [CMake] [DEBUG] Exiting after 4 s (3956363us)
...

ACTUAL FAILURE 404 FILE NOT FOUND ON SERVER BECAUSE IT WAS REMOVED

...

1> [CMake] error: building opengl:x64-windows failed with: BUILD_FAILED
1> [CMake] Elapsed time to handle opengl:x64-windows: 4.1 s
1> [CMake] Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
...

1> [CMake] -- Running vcpkg install - failed

...
1> [CMake] -- Configuring incomplete, errors occurred!
1> ... returned with exit code: 1'.

### Additional context

User configured project. Missing library is mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst . It was working some hours ago, the file may have been removed from the relevant server due to a "clean-up" or maintenance of old records. VCPKG possibly just needs an update to recognize newer versions of the specific library, because newer versions of the dependency do exist on the same server the compilation tool (CMake) was looking. Please fix so CMake+vcpkg do not look for any version prior to the latest available, if not already done.

**Comment by phume03** [comment]
The issue is duplicated for all ports that depend on libwinpthread, evidently a dependency fixed to the mingw compiler, which is called up to compile ports when building... hence the issue!

**Comment by dg0yt** [comment]
> Missing library is mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst 

This download was updated in vcpkg in May 2023 (#29067). Now you must update.

**Comment by phume03** [comment]
> > Missing library is mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst
> 
> This download was updated in vcpkg in May 2023 (#29067). Now you must update.

Alright, that seems about what I would want to do. I tried the latest VCPKG cloned via GitHub and it works, that is a 2024 version. So, you are right. Presumably, it downloads and uses a newer version of MinGW. I did not confirm. There are no tools to update VCPKG in the VisualStudio install. I tried to uninstall it and reinstall using the VS installer (simulating an update, minus the 23GB it otherwise requires for a complete VS upgrade/update), and it just installed the 2023 version that I already had. 

Is there a way to make the update without applying "brute force" i.e. replacing VCPKG in the VS program files folder? There always should be an "easy way", before forcing the user to make drastic manual changes. If not an update of VCPKG, maybe a clue of how to make a smaller change of updating a registry config file that tells VCPKG which version of MinGW, or just the dependent library if it will not break the rest of MinGW, to fetch?

**Comment by phume03** [comment]
Anyone else that happens on this, I resolved to compile the removed files for myself and replace them in the vcpkg local data folder. I hope it will work. Still fighting personal live-boot arch space issues (headache). Another solution is to update vcpkg (if you are working with a version around 2023, it will pull libwinpthread v9 and a newer version will pull the latest v10/11 which will just work).

I would hope that someone hosts an archive for the old vcpkg dependencies/tools to make things easier.

**Comment by phume03** [comment]
Anyone else that happens on this, I resolved to compile the removed files for myself and replace them in the vcpkg local data folder. I hope it will work. Still fighting personal live-boot arch space issues (headache). Another solution is to update vcpkg (if you are working with a version around 2023, it will pull libwinpthread v9 and a newer version will pull the latest v10/11 which will just work).

I would hope that someone hosts an archive for the old vcpkg dependencies/tools to make things easier.
