### ISSUE TITLE
[bzip2] Build error on x64-windows-static

### ISSUE THREAD

**Issue by emxcode** [microsoft/vcpkg#36941]
Copy issue body from C:/tools/vcpkg/installed/vcpkg/issue_body.md

vcpkg install tesseract:x64-windows-static
Computing installation plan...
The following packages will be built and installed:
  * bzip2[core,tool]:x64-windows-static@1.0.8#5
  * curl[core,non-http,schannel,ssl,sspi]:x64-windows-static@8.6.0
  * giflib:x64-windows-static@5.2.1#3
  * leptonica:x64-windows-static@1.84.1
  * libarchive[bzip2,core,crypto,libxml2,lz4,lzma,zstd]:x64-windows-static@3.7.2
  * libiconv:x64-windows-static@1.17#2
  * libjpeg-turbo:x64-windows-static@3.0.2
  * liblzma:x64-windows-static@5.4.4
  * libpng:x64-windows-static@1.6.40#1
  * libwebp[core,libwebpmux,nearlossless,simd,unicode]:x64-windows-static@1.3.2
  * libxml2[core,iconv,lzma,zlib]:x64-windows-static@2.11.6#1
  * lz4:x64-windows-static@1.9.4#1
  * openjpeg:x64-windows-static@2.5.0#1
  * openssl:x64-windows-static@3.2.1
    tesseract:x64-windows-static@5.3.4
  * tiff[core,jpeg,lzma,zip]:x64-windows-static@4.6.0#3
  * vcpkg-cmake-config:x64-windows@2022-02-06#1
  * vcpkg-cmake-get-vars:x64-windows@2023-12-31
  * zlib:x64-windows-static@1.3.1
  * zstd:x64-windows-static@1.5.5#2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows-static...
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\EM\AppData\Local\vcpkg\archives in 581 us. Use --debug to see more details.
Installing 1/20 bzip2[core,tool]:x64-windows-static@1.0.8#5...
Building bzip2[core,tool]:x64-windows-static@1.0.8#5...
-- Using cached bzip2-1.0.8.tar.gz.
-- Cleaning sources at C:/tools/vcpkg/buildtrees/bzip2/src/bzip2-1-336d4794a3.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/tools/vcpkg/downloads/bzip2-1.0.8.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Using source at C:/tools/vcpkg/buildtrees/bzip2/src/bzip2-1-336d4794a3.clean
-- Configuring x64-windows-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/tools/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe -v
    Working Directory: C:/tools/vcpkg/buildtrees/bzip2/x64-windows-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\tools\vcpkg\buildtrees\bzip2\config-x64-windows-static-dbg-CMakeCache.txt.log
      C:\tools\vcpkg\buildtrees\bzip2\config-x64-windows-static-rel-CMakeCache.txt.log
      C:\tools\vcpkg\buildtrees\bzip2\config-x64-windows-static-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:252 (vcpkg_execute_required_process)
  ports/bzip2/portfile.cmake:20 (vcpkg_cmake_configure)
  scripts/ports.cmake:170 (include)

error: building bzip2:x64-windows-static failed with: BUILD_FAILED
Elapsed time to handle bzip2:x64-windows-static: 1.5 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+bzip2
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[bzip2]+Build+error+on+x64-windows-static&body=Copy+issue+body+from+C%3A%2Ftools%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by MonicaLiu0311** [comment]
```
Error code: 1
See logs for more information:
C:\tools\vcpkg\buildtrees\bzip2\config-x64-windows-static-dbg-CMakeCache.txt.log
C:\tools\vcpkg\buildtrees\bzip2\config-x64-windows-static-rel-CMakeCache.txt.log
C:\tools\vcpkg\buildtrees\bzip2\config-x64-windows-static-out.log
```
Please provide the complete log file.
