### ISSUE TITLE
[harfbuzz] Build error on x64-windows

### ISSUE THREAD

**Issue by thommyTheCat** [microsoft/vcpkg#36944]
Hi all, 
I am trying to install the skia library and it is driving me around the bend... 
vcpkg always gets stuck when trying to install a package named harfbuzz. The error log is below. 

Setup: I am using Windows 11 home
Steps to reproduce: vcpkg install harfbuzz
Expected output: getting harfbuzz installed 
Actual outcome: [Error: ](error: building harfbuzz:x64-windows failed with: BUILD_FAILED)

I really don't know how this problem could be fixed and any help would be greatly appreciated. Unfortunately I'm a bit of a noob when it comes to build tools, package managers and the like...

Package: harfbuzz[core,freetype]:x64-windows@8.3.0#3

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.37.32824.0
-    vcpkg-tool version: 2023-12-12-1c9ec1978a6b0c2b39c9e9554a96e3e275f7556e
    vcpkg-scripts version: 45c8b198b 2024-01-03 (7 weeks ago)

**To Reproduce**

`vcpkg install harfbuzz`
**Failure logs**

```
-- Using cached harfbuzz-harfbuzz-8.3.0.tar.gz.
-- Cleaning sources at C:/Tools und Libs C++/vcpkg/buildtrees/harfbuzz/src/8.3.0-222d759c60.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Tools und Libs C++/vcpkg/downloads/harfbuzz-harfbuzz-8.3.0.tar.gz
-- Applying patch fix-win32-build.patch
-- Using source at C:/Tools und Libs C++/vcpkg/buildtrees/harfbuzz/src/8.3.0-222d759c60.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Configuring x64-windows-dbg
-- Using cached mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.9-3-x86_64.pkg.tar.zst.
-- Using msys root at C:/Tools und Libs C++/vcpkg/downloads/tools/msys2/023cdb3ca06f77f2
-- Configuring x64-windows-dbg done
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Package x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" install -v
    Working Directory: C:/Tools und Libs C++/vcpkg/buildtrees/harfbuzz/x64-windows-dbg
    Error code: 1
    See logs for more information:
      C:\Tools und Libs C++\vcpkg\buildtrees\harfbuzz\package-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
  ports/harfbuzz/portfile.cmake:85 (vcpkg_install_meson)
  scripts/ports.cmake:170 (include)

**Comment by saucecontrol** [comment]
>     See logs for more information:
      C:\Tools und Libs C++\vcpkg\buildtrees\harfbuzz\package-x64-windows-dbg-out.log

Detailed error information will be in the log mentioned in the output.

Using a working folder with spaces and pluses in the name is asking for a bad time.  I'd suggest simplifying that if the log file doesn't immediately reveal the issue.

**Comment by thommyTheCat** [comment]
> Using a working folder with spaces and pluses in the name is asking for a bad time. I'd suggest simplifying that if the log file doesn't immediately reveal the issue.

Thank you very much! This has fixed the problem.

**Comment by LilyWangLL** [comment]
Since this issue has been resolved, so I am closing this issue for now.

**Comment by ViViVerse** [comment]
Forgive me, but this is not completed. I have to install HarfBuzz as part of Qt5. This is the component number nnn, and I do not want to reinstall everything just because one component cannot handle spaces in the paths. Please advise on how to do this in a better way.
