### ISSUE TITLE
[libpqxx] update to 7.9.0

### ISSUE THREAD

**Issue by samuelbarrett1234** [microsoft/vcpkg#36968]
### Library name

libpqxx

### New version number

7.9.0

### Other information that may be useful (release notes, etc...)

Release notes are [here](https://github.com/jtv/libpqxx/releases/tag/7.9.0).

In particular, the Release Notes (under the section "Exception-related link errors") suggest that this new version addresses some linker errors relating to mixing different C++ standards within `vcpkg`. See:

- https://github.com/jtv/libpqxx/issues/752
- https://github.com/jtv/libpqxx/issues/743
- https://github.com/microsoft/vcpkg/pull/34941

**Comment by samuelbarrett1234** [comment]
FWIW, I have tried doing this myself [here](https://github.com/samuelbarrett1234/vcpkg/tree/bump-libpqxx-to-7.9.0), but I've not contributed to `vcpkg` before so I may be missing something.

**Comment by WangWeiLin-MV** [comment]
> FWIW, I have tried doing this myself [here](https://github.com/samuelbarrett1234/vcpkg/tree/bump-libpqxx-to-7.9.0), but I've not contributed to `vcpkg` before so I may be missing something.

The version database is added by running `./vcpkg x-add-version --all` and committing the result.

We'd be grateful if you could help [submit PR](https://learn.microsoft.com/en-us/vcpkg/get_started/get-started-adding-to-registry?pivots=shell-bash#6---create-a-pull-request) from your fork.

If you have any questions please let me known.
