### ISSUE TITLE
[poco] Build error on x64-windows

### ISSUE THREAD

**Issue by a1544** [microsoft/vcpkg#36973]
Copy issue body from C:/src/vcpkg/installed/vcpkg/issue_body.md

C:\src\vcpkg>vcpkg install poco:x64-windows
Computing installation plan...
The following packages will be built and installed:
    poco:x64-windows@1.13.0
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\AppData\Local\vcpkg\archives in 799 us. Use --debug to see more details.
Installing 1/1 poco:x64-windows@1.13.0...
Building poco:x64-windows@1.13.0...
-- Using cached pocoproject-poco-poco-1.13.0-release.tar.gz.
-- Cleaning sources at C:/src/vcpkg/buildtrees/poco/src/.0-release-58acc8dfdc.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/src/vcpkg/downloads/pocoproject-poco-poco-1.13.0-release.tar.gz
-- Applying patch 0001-static-pcre.patch
-- Applying patch 0002-arm64-pcre.patch
-- Applying patch 0003-fix-dependency.patch
-- Applying patch 0004-fix-feature-sqlite3.patch
-- Applying patch 0005-fix-error-c3861.patch
-- Applying patch 0007-find-pcre2.patch
-- Using source at C:/src/vcpkg/buildtrees/poco/src/.0-release-58acc8dfdc.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Warning at scripts/cmake/vcpkg_execute_build_process.cmake:65 (message):
  Please ensure your system has sufficient memory.
Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/poco/portfile.cmake:84 (vcpkg_cmake_install)
  scripts/ports.cmake:170 (include)

-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/src/vcpkg/downloads/tools/cmake-3.27.1-windows/cmake-3.27.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: C:/src/vcpkg/buildtrees/poco/x64-windows-dbg
    See logs for more information:
      C:\src\vcpkg\buildtrees\poco\install-x64-windows-dbg-out.log
      C:\src\vcpkg\buildtrees\poco\install-x64-windows-dbg-out-1.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/poco/portfile.cmake:84 (vcpkg_cmake_install)
  scripts/ports.cmake:170 (include)

error: building poco:x64-windows failed with: BUILD_FAILED
Elapsed time to handle poco:x64-windows: 49 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+poco
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[poco]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2Fsrc%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by StarGate-One** [comment]
>See logs for more information:
C:\src\vcpkg\buildtrees\poco\install-x64-windows-dbg-out.log
C:\src\vcpkg\buildtrees\poco\install-x64-windows-dbg-out-1.log

**Comment by FrankXie05** [comment]
@a1544 Please provide the error log.

**Comment by a1544** [comment]
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/14416344/install-x64-windows-dbg-out.log)
[install-x64-windows-dbg-out-1.log](https://github.com/microsoft/vcpkg/files/14416347/install-x64-windows-dbg-out-1.log)

**Comment by a1544** [comment]
> > See logs for more information:
> > C:\src\vcpkg\buildtrees\poco\install-x64-windows-dbg-out.log
> > C:\src\vcpkg\buildtrees\poco\install-x64-windows-dbg-out-1.log
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/14416369/install-x64-windows-dbg-out.log)
[install-x64-windows-dbg-out-1.log](https://github.com/microsoft/vcpkg/files/14416370/install-x64-windows-dbg-out-1.log)

Thanks for you response. here you fing the log file

**Comment by StarGate-One** [comment]
>C:\src\vcpkg\buildtrees\poco\src\.0-release-58acc8dfdc.clean\Foundation\include\Poco/Tuple.h(3128): fatal error C1060: compiler is out of heap space
ninja: build stopped: subcommand failed.

The compiler ran out of memory.

**Comment by upinget** [comment]
I am using Visual Studio 2017, same error happened to me while installing the poco package.
