### ISSUE TITLE
[icu] Build error

### ISSUE THREAD

**Issue by leoayt** [microsoft/vcpkg#36976]
Fix: icu depends on autoconf-archive, so I installed it before building icu manually.

**Comment by jimwang118** [comment]
Which triplet did you compile under?

**Comment by leoayt** [comment]
x64-osx

Thanks.

From: jim wang ***@***.***>
Date: Tuesday, February 27, 2024 at 11:34 AM
To: microsoft/vcpkg ***@***.***>
Cc: Leo An ***@***.***>, Author ***@***.***>
Subject: Re: [microsoft/vcpkg] [icu] Build error (Issue #36976)

Which triplet did you compile under?

**Comment by jimwang118** [comment]
Yes, this means that this port depends on `autoconf-archive`, and you need to install `autoconf-archive` manually before installation.

**Comment by leoayt** [comment]
Sure.

Thanks.

From: jim wang ***@***.***>
Date: Tuesday, February 27, 2024 at 6:50 PM
To: microsoft/vcpkg ***@***.***>
Cc: Leo An ***@***.***>, Author ***@***.***>
Subject: Re: [microsoft/vcpkg] [icu] Build error (Issue #36976)

Yes, this means that this port depends on autoconf-archive, and you need to install autoconf-archive manually before installation.

**Comment by jimwang118** [comment]
Can you install the port normally after installing autoconf-archive?

**Comment by nvoronetskiy** [comment]
We had the same problem with the same solution.

**Comment by jimwang118** [comment]
> We had the same problem with the same solution.

Are you still unable to build icu after installing autoconf-archive?

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
