### ISSUE TITLE
Link dynamic cpprestsdk and static boost the same time?

### ISSUE THREAD

**Issue by sinall** [microsoft/vcpkg#3699]
Is there a way to use cpprestsdk dynamically and boost statically in a project?

I have both static & dynamic boost lib installed. How do I choose which one to use with VC++ solution?

**Comment by Cheney-W** [comment]
@sinall 
You can use following command to export a nuget package and then install it in your project:
.\vcpkg.exe export cpprestsdk:x64-windows boost:x64-windows-static --nuget
