### ISSUE TITLE
 post-build validation fails if VS is not installed in "C:\Program Files (x86)\Microsoft Visual Studio 14.0\""

### ISSUE THREAD

**Issue by Remotion** [Microsoft/vcpkg#37]
post-build validation fails if VS is not installed in "C:\Program Files (x86)\Microsoft Visual Studio 14.0\""
But this is common if SSD for windows it too small. 

Apparently because of this line hard coded path.

static const fs::path DUMPBIN_EXE = R"(C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\dumpbin.exe)";

%VS140COMNTOOLS% should be used instate.

**Comment by ras0219-msft** [comment]
Fixed by #38, thanks for reporting this!
