### ISSUE TITLE
error: building cudnn:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by NOCls** [microsoft/vcpkg#37001]
-- Found CUDA V12.3.52
-- CUDNN_INCLUDE_DIR: CUDNN_INCLUDE_DIR-NOTFOUND
-- CUDNN_LIBRARY: CUDNN_LIBRARY-NOTFOUND
CMake Error at ports/cudnn/portfile.cmake:58 (message):
  Please download CUDNN from official sources (such as
  https://developer.nvidia.com/rdp/cudnn-download ) and extract the zip into
  your CUDA_TOOLKIT_ROOT (C:/Program Files/NVIDIA GPU Computing
  Toolkit/CUDA/v12.3).  (For example: tar.exe -xvf
  cudnn-11.2-windows-x64-v8.1.1.33.zip --strip 1 --directory "C:/Program
  Files/NVIDIA GPU Computing Toolkit/CUDA/v12.3"
Call Stack (most recent call first):
  scripts/ports.cmake:170 (include)

error: building cudnn:x64-windows failed with: BUILD_FAILED
Elapsed time to handle cudnn:x64-windows: 159 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+cudnn
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[cudnn]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2FUsers%2FAdministor%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by StarGate-One** [comment]
>Please download CUDNN from official sources (such as
https://developer.nvidia.com/rdp/cudnn-download ) and extract the zip into
your CUDA_TOOLKIT_ROOT (C:/Program Files/NVIDIA GPU Computing
Toolkit/CUDA/v12.3).

You need to do this before you can install CUDNN port/features.
