### ISSUE TITLE
[boost-cobalt] Build error on x64-windows

### ISSUE THREAD

**Issue by rczheng218** [microsoft/vcpkg#37007]
[issue_body.md](https://github.com/microsoft/vcpkg/files/14426707/issue_body.md)

-- Using cached boostorg-cobalt-boost-1.84.0.tar.gz.
-- Cleaning sources at C:/Users/teranlab/vcpkg/buildtrees/boost-cobalt/src/ost-1.84.0-f1b8232bac.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/teranlab/vcpkg/downloads/boostorg-cobalt-boost-1.84.0.tar.gz
-- Using source at C:/Users/teranlab/vcpkg/buildtrees/boost-cobalt/src/ost-1.84.0-f1b8232bac.clean
-- Including C:/Users/teranlab/vcpkg/ports/boost-cobalt/b2-options.cmake
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
Working Directory: C:/Users/teranlab/vcpkg/buildtrees/boost-cobalt/x64-windows-rel/vcpkg-parallel-configure
Error code: 1
See logs for more information:
C:\Users\teranlab\vcpkg\buildtrees\boost-cobalt\config-x64-windows-dbg-CMakeCache.txt.log
C:\Users\teranlab\vcpkg\buildtrees\boost-cobalt\config-x64-windows-rel-CMakeCache.txt.log
C:\Users\teranlab\vcpkg\buildtrees\boost-cobalt\config-x64-windows-out.log

Call Stack (most recent call first):
installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:252 (vcpkg_execute_required_process)
installed/x64-windows/share/boost-build/boost-modular-build.cmake:120 (vcpkg_cmake_configure)
ports/boost-cobalt/portfile.cmake:17 (boost_modular_build)
scripts/ports.cmake:170 (include)

error: building boost-cobalt:x64-windows failed with: BUILD_FAILED
Elapsed time to handle boost-cobalt:x64-windows: 1.3 s
Please ensure you're using the latest port files with git pull and vcpkg update.
Then check for known issues at:
https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-cobalt
You can submit a new issue at:
[https://github.com/microsoft/vcpkg/issues/new?title=[boost-cobalt]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2FUsers%2Fteranlab%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md](https://github.com/microsoft/vcpkg/issues/new?title=%5Bboost-cobalt%5D+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2FUsers%2Fteranlab%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md)

**Comment by rczheng218** [comment]
-- Using cached boostorg-cobalt-boost-1.84.0.tar.gz.
-- Cleaning sources at C:/Users/teranlab/vcpkg/buildtrees/boost-cobalt/src/ost-1.84.0-f1b8232bac.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/teranlab/vcpkg/downloads/boostorg-cobalt-boost-1.84.0.tar.gz
-- Using source at C:/Users/teranlab/vcpkg/buildtrees/boost-cobalt/src/ost-1.84.0-f1b8232bac.clean
-- Including C:/Users/teranlab/vcpkg/ports/boost-cobalt/b2-options.cmake
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/Users/teranlab/vcpkg/buildtrees/boost-cobalt/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\teranlab\vcpkg\buildtrees\boost-cobalt\config-x64-windows-dbg-CMakeCache.txt.log
      C:\Users\teranlab\vcpkg\buildtrees\boost-cobalt\config-x64-windows-rel-CMakeCache.txt.log
      C:\Users\teranlab\vcpkg\buildtrees\boost-cobalt\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:252 (vcpkg_execute_required_process)
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:120 (vcpkg_cmake_configure)
  ports/boost-cobalt/portfile.cmake:17 (boost_modular_build)
  scripts/ports.cmake:170 (include)


error: building boost-cobalt:x64-windows failed with: BUILD_FAILED
Elapsed time to handle boost-cobalt:x64-windows: 1.3 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-cobalt
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[boost-cobalt]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2FUsers%2Fteranlab%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by StarGate-One** [comment]
See #30604 How to report a package build failure [Explanation Video]

>Error code: 1
See logs for more information:
C:\Users\teranlab\vcpkg\buildtrees\boost-cobalt\config-x64-windows-dbg-CMakeCache.txt.log
C:\Users\teranlab\vcpkg\buildtrees\boost-cobalt\config-x64-windows-rel-CMakeCache.txt.log
C:\Users\teranlab\vcpkg\buildtrees\boost-cobalt\config-x64-windows-out.log

What is/are the error(s) listed in the mentioned logs?

**Comment by StarGate-One** [comment]
>  Boost.Cobalt is supported since Clang 14, GCC 10 and MSVC 19.30 (Visual
  Studio 2022).  Detected compiler is MSVC 1929.

Current Visual Studio you have installed is 19.29, but it needs to be updated to at least 19.30

Run the Visual Studio installer and upgrade.

**Comment by JonLiu1993** [comment]
@rczheng218, Have you tried @StarGate-One's suggestion?

**Comment by killghost** [comment]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional>cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30154 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.


So, boots  must be compiled with vs2022?

**Comment by JonLiu1993** [comment]
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional>cl Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30154 for x64 Copyright (C) Microsoft Corporation. All rights reserved.
> 
> So, boots must be compiled with vs2022?

Yes, MSVC 1930 and above is VS2022.

**Comment by JonLiu1993** [comment]
@rczheng218, We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
