### ISSUE TITLE
Incorrect license for libiconv

### ISSUE THREAD

**Issue by arthur-tacca** [Microsoft/vcpkg#3700]
When libiconv is installed, the copyright file in share/libiconv is a copy of the GPL. But according to the [readme](https://www.gnu.org/software/libiconv/), "The `libiconv` and `libcharset` *libraries* and their header files are under LGPL. The `iconv` *program* is under GPL." The source distribution doesn't seem to include a copy of the LGPL so it would need to be downloaded separately. Unfortunately the readme is not clear about which version is used.

On a related note, it would be good to show some sort of warning when installing an LGPL package with a static triplet such as `x64-windows-static` or `x64-linux`. It could be possible to install such a package as a dependency to something without realising it, with consequences for the licensing of the application code. Similarly, a warning when a GPL package is installed would be useful (for all triplets).

**Comment by ras0219-msft** [comment]
Thanks for posting this issue!

From my reading of the portfile[1], we are using `COPYING.LIB`, which begins with the stanza:
```
		  GNU LIBRARY GENERAL PUBLIC LICENSE
		       Version 2, June 1991
```

If this is incorrect, which file should we be using?

[1] https://github.com/Microsoft/vcpkg/blob/5c8b828e070e860af9c524fbdd96a699ffeeec05/ports/libiconv/portfile.cmake#L40-L41

**Comment by arthur-tacca** [comment]
I'm really sorry, that is indeed the correct license. Somehow I managed to miss the word "LIBRARY" every time I looked at the heading in that file. I even saw there is both an COPYING and COPYING.LIB in the source distribution and thought it was odd that they both seemed to be the same!

Sorry again for the noise, and keep up the great work on vcpkg!
