### ISSUE TITLE
[glm] build failure - SHA512 hash mismatch

### ISSUE THREAD

**Issue by StarGate-One** [microsoft/vcpkg#37008]
### Operating system

Windows 11 10.0.22621.3155 x64 Enterprise

### Compiler
Visual Studio Community 2022 Version: [17.9.2]  VS Tools Version: [14.39.33519]
Microsoft (R) C/C++ Optimizing Compiler Version [19.39.33521] for x64 

### Vcpkg Information
Vcpkg Version [2024-02-27-29a99e84b4d7bf30e43466b1572ea6b392dcf4e3] 
Vcpkg Scripts Version [2024-02-27-3dd44b931481d7a8e9ba412621fa810232b66289] 

### Steps to reproduce the behavior

```Shell
`.\vcpkg.exe install glm`
```

### Failure logs

Installing 39/72 glm:x64-windows@1.0.1...
Building glm:x64-windows@1.0.1...
-- Note: glm only supports static library linkage. Building static library.
-- Downloading https://github.com/g-truc/glm/archive/1.0.1.tar.gz -> g-truc-glm-1.0.1.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Disabling metrics because vcpkg.disable-metrics exists
[DEBUG] Trying to load bundleconfig from D:\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: D:\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://github.com/g-truc/glm/archive/1.0.1.tar.gz
[DEBUG] Trying to hash D:\vcpkg\downloads\g-truc-glm-1.0.1.tar.gz.6100.part
[DEBUG] D:\vcpkg\downloads\g-truc-glm-1.0.1.tar.gz.6100.part has hash c6c6fa1ea7a7e97820e36ee042a78be248ae828c99c1b1111080d9bf334a5160c9993a70312351c92a867cd49907c95f9f357c8dfe2bc29946da6e83e27ba20c
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/g-truc/glm/archive/1.0.1.tar.gz
File: D:\vcpkg\downloads\g-truc-glm-1.0.1.tar.gz.6100.part
Expected hash: `0296a9bac8a114f50aa719b402d66524a4028aeec72649da1964faa80116f3f1ae5fa13d741dbaf9f4bcdb0722c0e44a4e85e8fc16dda641f4ba03f4a2c755d3`
Actual hash: `c6c6fa1ea7a7e97820e36ee042a78be248ae828c99c1b1111080d9bf334a5160c9993a70312351c92a867cd49907c95f9f357c8dfe2bc29946da6e83e27ba20c`
[DEBUG] D:\vcpkg-tool\src\vcpkg\base\downloads.cpp(1030):
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 10us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 76us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 1.1 s (1118400us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/glm/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:170 (include)

error: building glm:x64-windows failed with: BUILD_FAILED
Elapsed time to handle glm:x64-windows: 1.2 s

### Additional context

I downloaded the file manually and checked SHA512 with hashtools.

The SHA512 from the downloaded file is `c6c6fa1ea7a7e97820e36ee042a78be248ae828c99c1b1111080d9bf334a5160c9993a70312351c92a867cd49907c95f9f357c8dfe2bc29946da6e83e27ba20c` which matches the one reported by vcpkg as being incorrect, does not match the SHA512 from the `portfile.cmake` of `0296a9bac8a114f50aa719b402d66524a4028aeec72649da1964faa80116f3f1ae5fa13d741dbaf9f4bcdb0722c0e44a4e85e8fc16dda641f4ba03f4a2c755d3`

**Comment by xorz57** [comment]
I just encountered the same issue a couple of minutes ago! Good to know there is a fix for it!
