### ISSUE TITLE
CMAKE fails to find package jsoncpp installed by vcpkg when using a manifest.

### ISSUE THREAD

**Issue by fishnet37222** [microsoft/vcpkg#37019]
**Describe the bug**
When attempting to configure a CMAKE project using a vcpkg manifest to specify the dependencies, CMAKE fails to find the package jsoncpp listed in the manifest.  When not using a manifest, CMAKE finds the package without any issues.

**Environment**
- OS: Windows 10 Pro
- Compiler: Visual Studio 2022

**To Reproduce**
1. Open the attached CMAKE project: [jsoncpp-vcpkg-test.zip](https://github.com/microsoft/vcpkg/files/14431189/jsoncpp-vcpkg-test.zip)
2. See error

**Expected behavior**
CMAKE should be able to find the package when it's installed by being listed in a vcpkg manifest.

**Failure logs**
-(please attached failure logs): [error.txt](https://github.com/microsoft/vcpkg/files/14431202/error.txt)

**Additional context**
This issue does not occur when using a vcpkg manifest with an MSBUILD project.

**Comment by FrankXie05** [comment]
>1> [CMake] All requested packages are currently installed.
>1> [CMake] Total install time: 300 ns

@fishnet37222 Thanks for posting this issue. After the installation is complete, do you have the file `jsoncppConfig.cmake` on folder `\vcpkg\installed\x64-windows\share\jsoncpp`  locally?

**Comment by fishnet37222** [comment]
Yes, but when using a manifest, there's nothing in the `vcpkg_installed` folder.

**Comment by FrankXie05** [comment]
I don't see anything in your vcpkg.json.

**Comment by FrankXie05** [comment]
Maybe you need to see https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/consume/manifest-mode.md :)

**Comment by fishnet37222** [comment]
I could have sworn I ran the command `vcpkg add port jsoncpp`.  Regardless, I ran it again and it's working as expected.

**Comment by fishnet37222** [comment]
Actually, I was wrong when I said it was working correctly.  The configuration process completes without any errors, but the `jsoncpp` headers are unable to be found.

I've attached an updated project:  [jsoncpp-vcpkg-test.zip](https://github.com/microsoft/vcpkg/files/14431886/jsoncpp-vcpkg-test.zip)

**Comment by FrankXie05** [comment]
@fishnet37222 Have you added `CMAKE_TOOLCHAIN_FILE` to your cmake project?

**Comment by fishnet37222** [comment]
I'm using CLion, and here's a screenshot of the CMake settings for the project:
![image](https://github.com/microsoft/vcpkg/assets/1977106/4a25718d-5cde-4bd6-91ef-f26fec793ef6)

**Comment by fishnet37222** [comment]
Just for giggles I tried adding `JsonCpp::JsonCpp` to the `target_link_libraries` command in the `CmakeLists.txt` file and everything is working correctly.

Usually, specifying the `${<package>_INCLUDE_DIRS}` and `${<package>_LIBRARIES}` variables in the `target_include_directories` and `target_link_libraries` commands works without any issues.  However, this port doesn't seem to populate those variables.

**Comment by dg0yt** [comment]
> Usually, specifying the `${<package>_INCLUDE_DIRS}` and `${<package>_LIBRARIES}` variables in the `target_include_directories` and `target_link_libraries` commands works without any issues. However, this port doesn't seem to populate those variables.

And this is a good thing.
These variables are usually populated by "Find modules", by (informed) guessing. This is legacy CMake.
Modern CMake directly exports known values as properties of "imported targets" in "Config packages" generated at build time.
And even the find modules coming with CMake provide more and more imported targets (e.g, `ZLIB::ZLIB`).
