### ISSUE TITLE
[realsense2] Build error on x64-windows

### ISSUE THREAD

**Issue by laracb01** [microsoft/vcpkg#37030]
command: ./vcpkg integrate install
Applied user-wide integration for this vcpkg root.
CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=C:/Users/Lara/Desktop/ASPACE/vcpkg/scripts/buildsystems/vcpkg.cmake"

All MSBuild C++ projects can now #include any installed libraries. Linking will be handled automatically. Installing new libraries will make them instantly available.  
PS C:\Users\Lara\Desktop\ASPACE\vcpkg> ./vcpkg install realsense2
warning: In the September 2023 release, the default triplet for vcpkg libraries changed from x86-windows to the detected host triplet (x64-windows). For the old behavior, add --triplet x86-windows . To suppress this message, add --triplet x64-windows .
Computing installation plan...
The following packages will be built and installed:
    realsense2:x64-windows@2.54.2#2
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\Lara\AppData\Local\vcpkg\archives in 228 us. Use --debug to see more details.
Installing 1/1 realsense2:x64-windows@2.54.2#2...
Building realsense2:x64-windows@2.54.2#2...
-- Using cached IntelRealSense-librealsense-v2.54.2.tar.gz.
-- Cleaning sources at C:/Users/Lara/Desktop/ASPACE/vcpkg/buildtrees/realsense2/src/v2.54.2-e3f135a521.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Lara/Desktop/ASPACE/vcpkg/downloads/IntelRealSense-librealsense-v2.54.2.tar.gz
-- Applying patch fix_openni2.patch
-- Applying patch fix-osx.patch
-- Using source at C:/Users/Lara/Desktop/ASPACE/vcpkg/buildtrees/realsense2/src/v2.54.2-e3f135a521.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/Users/Lara/Desktop/ASPACE/vcpkg/downloads/tools/cmake-3.27.1-windows/cmake-3.27.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j17
    Working Directory: C:/Users/Lara/Desktop/ASPACE/vcpkg/buildtrees/realsense2/x64-windows-dbg
    See logs for more information:
      C:\Users\Lara\Desktop\ASPACE\vcpkg\buildtrees\realsense2\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/realsense2/portfile.cmake:46 (vcpkg_cmake_install)
  scripts/ports.cmake:170 (include)

error: building realsense2:x64-windows failed with: BUILD_FAILED
Elapsed time to handle realsense2:x64-windows: 52 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+realsense2
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[realsense2]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2FUsers%2FLara%2FDesktop%2FASPACE%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by Cheney-W** [comment]
Please see [#30604](https://github.com/microsoft/vcpkg/issues/30604) for how to report an issue.
