### ISSUE TITLE
[glib] Unable to link

### ISSUE THREAD

**Issue by nlogozzo** [microsoft/vcpkg#37053]
**Describe the bug**
Unable to link to glib when installed via vcpkg.

**Environment**
- OS: OpenSuse Tumbleweed
- Compiler: GCC 13

**To Reproduce**
1. ./vcpkg install glib
2. See error

**Expected behavior**
No linker errors when linking to glib

**Failure logs**
```
/usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /home/nlogozzo/vcpkg/installed/x64-linux/lib/libglib-2.0.a(gregex.c.o): undefined reference to symbol 'pcre2_set_bsr_8'
/usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libpcre2-8.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
**Additional context**
Could possibly be due to the fast that glib is also installed on the host system via its package manager....but I honestly wouldn't know.

**Comment by SchaichAlonso** [comment]
It being installed as part of the Operating System "shouldn't" matter. The `libpcre2-8.so` library is installed as part of the `pcre2` library, which "should" have been deployed by vcpkg prior to attempting to deploy glib, and glib's build system "should" have been instructed to look for libraries in the vcpkg library path.

... if you use the `x64-linux-dynamic` triplet, that is.

With the `x64-linux` triplet, the pcre2 library should be there nevertheless, however, it is static. `ld` will always prefer to link against dynamic libraries when it has the choice, so case glib's package dependencies "should" be asking `ld` to link it explicitly against vcpkg's libraries by providing the absolute file paths to the linker. "Should" is a dangerous word.

That said, how are you referencing to glib/pcre2? Are you explicitly referencing pcre2 or is it implicit via glib, and how does your project file discover glib and the glib dependencies?

**Comment by dg0yt** [comment]
Port glib already depends on port pcre2. Share the logs.

**Comment by SchaichAlonso** [comment]
> Port glib already depends on port pcre2. Share the logs.

It depends doesn't mean that it actually exports this dependency in a feasible way, does it?

A long time ago, vcpkg used to maintain [it's own cmake project for glib](https://github.com/microsoft/vcpkg/blob/e1e681f71b219b5673023dfe045e737955554897/ports/glib/CMakeLists.txt). It used to [find pcre](https://github.com/microsoft/vcpkg/blob/e1e681f71b219b5673023dfe045e737955554897/ports/glib/CMakeLists.txt#L28), create a [glib target](https://github.com/microsoft/vcpkg/blob/e1e681f71b219b5673023dfe045e737955554897/ports/glib/CMakeLists.txt#L136), [link it against pcre](https://github.com/microsoft/vcpkg/blob/e1e681f71b219b5673023dfe045e737955554897/ports/glib/CMakeLists.txt#L138), and [export the glib targets](https://github.com/microsoft/vcpkg/blob/e1e681f71b219b5673023dfe045e737955554897/ports/glib/CMakeLists.txt#L336) into an `unofficial::glib` namespace, so users could run `find_package(GLib2)` and then link their target against `unofficial::glib::glib` which was resulting in all vcpkg tracked dependencies also getting linked.

Eventually, [in 2021 vcpkg stopped maintaining it's cmake project for glib and started using the upstream provided meson.](https://github.com/microsoft/vcpkg/commit/546813ae7b9e2873dd3d38e78b27ac5582feae10). As a side effect, we lost the `unofficial::glib` targets and now have to handle the glib discovery and glib dependencies using other means. I am aware that we should use the upstream provided packaging stuff wherever it's feasible, but nevertheless this was a huge usability loss IMO. I myself ended up migrating to use [KDE's package finding scripts for glib and friends](https://invent.kde.org/frameworks/extra-cmake-modules/-/tree/master/find-modules) but I assume other users have different means to discover and link against glib, including attempting to track dependencies "manually".

Hence I assume the integration of the glib dependency into the project to be more likely an issue then vcpkg packaging details. The OP hasn't reported vcpkg failing to build the port, but the consuming project failing to link properly instead, so the vcpkg packaging logs will likely read "successfully deployed" anyways.

**Comment by nlogozzo** [comment]
> The OP hasn't reported vcpkg failing to build the port, but the consuming project failing to link properly instead, so the vcpkg packaging logs will likely read "successfully deployed" anyways.

Exactly. `glib` builds just fine...it's when linking in projects the error occurs.

> That said, how are you referencing to glib/pcre2 in your project? Are you explicitly referencing pcre2 or is it implicit via glib, and how does your project discover glib and the glib dependencies?

with `x64-linux`

```
find_package(PkgConfig REQUIRED)
pkg_check_modules(glib REQUIRED IMPORTED_TARGET glib-2.0)
pkg_check_modules(gio REQUIRED IMPORTED_TARGET gio-2.0)
pkg_check_modules(gmodule REQUIRED IMPORTED_TARGET gmodule-2.0)
pkg_check_modules(gobject REQUIRED IMPORTED_TARGET gobject-2.0)
pkg_check_modules(gthread REQUIRED IMPORTED_TARGET gthread-2.0)
target_link_libraries(${PROJECT_NAME} PUBLIC PkgConfig::glib PkgConfig::gio PkgConfig::gmodule PkgConfig::gobject PkgConfig::gthread)
```

**Comment by SchaichAlonso** [comment]
pkg-config is not evaluating to explicit static library referencing over here. In a shell,
```
# PKG_CONFIG_PATH=$(pwd)/installed/x64-linux/lib/pkgconfig pkg-config --libs glib-2.0 gio-2.0 gmodule-2.0 gobject-2.0 gthread-2.0
```
evaluates to 
```
-L/tmp/vcpkg/installed/x64-linux/lib/pkgconfig/../../lib -lpcre2-8 -lgio-2.0 -lz -Wl,--export-dynamic -lgmodule-2.0 -lintl -lgobject-2.0 -lffi -lgthread-2.0 -lintl -lglib-2.0 -lintl -lm -pthread
```
over here, which might result in each and every of those libraries getting used from the operating system's default path instead of `/tmp/vcpkg/installed/x64-linux/lib/pkgconfig/../../lib` which is the vcpkg path, as `ld` prefers dynamic libraries over static libraries.

The `-Wl,-Bstatic` linker option to the GNU linker (and compatible LLVM one) resets the preference setting of libraries following **after** the `-Wl,-Bstatic` argument to prefer static over dynamic libraries. Can you try using
```
target_link_libraries(${PROJECT_NAME} PUBLIC "-Wl,-Bstatic" PkgConfig::glib PkgConfig::gio PkgConfig::gmodule PkgConfig::gobject PkgConfig::gthread)
```
to tell the linker to prefer static libs (which are from vcpkg)?

**Comment by nlogozzo** [comment]
> Can you try using

@SchaichAlonso after adding `"-Wl,-Bstatic"` to the beginning of `target_link_libraries`, I get a new set of linker errors:
```
/usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: cannot find -lm: No such file or directory
/usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: cannot find -lm: No such file or directory
/usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: cannot find -lgcc_s: No such file or directory
/usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: cannot find -lc: No such file or directory
/usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: cannot find -lgcc_s: No such file or directory
```

**Comment by SchaichAlonso** [comment]
With only `-lm` out of the diagnosed libraries being implied by pkgconfig, maybe
```
target_link_libraries(${PROJECT_NAME} PUBLIC m "-Wl,-Bstatic" PkgConfig::glib PkgConfig::gio PkgConfig::gmodule PkgConfig::gobject PkgConfig::gthread "-Wl,-Bdynamic")
```
does the trick, where `-Wl,-Bdynamic` resets the linker's preference.

**Comment by dg0yt** [comment]
This is not how it works... `target_link_libraries` doesn't map to a linker command line in a literal way (as in; `pkg-config --libs`). It is a collection of name specs, files and targets. Targets may have a very different order depending on dependencies.  And so the attempt to form groups with link options won't work (reliably).
I don't want to add more details now. Supply a minimal reproducible example (CMakeLists.txt).
