### ISSUE TITLE
can't down load jom_1_1_2.zip

### ISSUE THREAD

**Issue by xtwgigu** [Microsoft/vcpkg#3705]
on file:scripts\cmake\vcpkg_find_acquire_program.cmake

seems the url can't be reached:
http://download.qt.io/official_releases/jom/jom_1_1_2.zip 

i changed it to:
https://www.mirrorservice.org/sites/download.qt-project.org/official_releases/jom/jom_1_1_2.zip

**Comment by PhoebeHui** [comment]
It looks a temporary issue, the url could be reached now, please open a new issue if the it persists.
