### ISSUE TITLE
Current upstream revision scheme clashes with semver

### ISSUE THREAD

**Issue by boris-kolpackov** [microsoft/vcpkg#3707]
It appears that vcpkg uses the -N notation to distinguish between revisions of the same upstream version. For example, looking at libuv, its upstream version is currently 1.20.3 while the corresponding vcpkg CONTROL file lists it as 1.20.3-2.

The problem with this notation is that in semver it means pre-release and is ordered before the final version. In other words, 1.20.3 > 1.20.3-2.

I would suggest changing it to +N which in semver means build metadata and is ignored for version comparison. For example, 1.20.3+2. An alternative would be to add another version component, for example, 1.20.3.2. The major drawback of this approach is that the version is no longer semver.

**Comment by ras0219-msft** [comment]
Thanks for the info, @boris-kolpackov!

First, I will note that on the grand scale it isn't a goal for our package names to fit into SemVer -- if authors decide to name their packages versions after animals, we intend to follow that.

However, I definitely see the value in not being excessively hostile here! It is intended that `1.20.3-2` is sorted after `1.20.3`. Would that be the case in `1.20.3+2`? As for `1.20.3.2`, we avoid that because we prefer to make the difference between the upstream package version component and any suffix we add as clear as reasonably possible.

If `+2` doesn't work, do you have any other suggestions that would achieve the desired results above?

**Comment by boris-kolpackov** [comment]
Per semver 1.20.3+2 == 1.20.3. It is not ideal but better than the outright incorrect sorting (and one could argue that it is actually the same upstream version, especially if the changes are to the packaging infrastructure only).

Unfortunately there is no way to get the 1.20.3?2 > 1.20.3 in semver. We cannot add another version component (1.20.3.2) since it will no longer be semver, we cannot use pre-release (1.20.3-2) since it won't sort correctly, which leaves the build meta-data as the only option.

**Comment by ras0219-msft** [comment]
There is one other option (though admittedly not great): extending our versions as `<vcpkgsnapshotdate>.0.0+<packageversion>`. This would guarantee correct sorting, and not cause any `==` conflicts because there will only be one entry for each `<vcpkgsnapshotdate>`.

**Comment by ras0219-msft** [comment]
(Also, we use `-1` to indicate any changes to the output package -- this could be adding missing headers for installation, or applying a patch to the source code, or fixing a typo in the license. We try to only bump package versions when there are _real_ changes to the output package that are relevant for the consumer and downstream packages).

**Comment by boris-kolpackov** [comment]
I don't think replacing the package version with your own is a good idea. It will just confuse things further. I believe the only way to fix this properly is to introduce another control field (e.g., Revision:) next to Version: but that might be a bit too involved.

I still think +N is the best option here. You can document that this component is actually significant for version sorting (like we did in build2). Clients that are aware of this "extension" will be able to see the difference between +N versions while the rest can still treat it as plain semver with the less precise (but not outright incorrect like right now) results.

BTW, another point about using the pre-release notation (-N) is that upstream could be using it themselves. In fact, this was what made me submit this issue: looking at the version in the CONTROL file I cannot say whether -N came from upstream or from vcpkg. So any fix that will allow us to distinguish the upstream version from vcpkg version will work for us.

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen this issue.
