### ISSUE TITLE
vcpkg fails with ninja error

### ISSUE THREAD

**Issue by adevelopcr** [Microsoft/vcpkg#3710]
it was working for me days ago but today I'm tried to build sqlite3 x64 and curl x64 and x86 but all failed with the same error don't know why ?

`CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: E:/programs/mingw-packages/vcpkg-master/buildtrees/zlib/x86-windows-static-rel/vcpkg-parallel-configure
    See logs for more information:
      E:\programs\mingw-packages\vcpkg-master\buildtrees\zlib\config-x86-windows-static-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:233 (vcpkg_execute_required_process)
  ports/zlib/portfile.cmake:19 (vcpkg_configure_cmake)
  scripts/ports.cmake:72 (include)`

**Comment by adevelopcr** [comment]
even sqlite3 x86 I installed it before now I went to upgrade it and failed : 

`   CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: E:/programs/mingw-packages/vcpkg-master/buildtrees/sqlite3/x86-windows-static-rel/vcpkg-parallel-configure
    See logs for more information:
      E:\programs\mingw-packages\vcpkg-master\buildtrees\sqlite3\config-x86-windows-static-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:233 (vcpkg_execute_required_process)
  ports/sqlite3/portfile.cmake:20 (vcpkg_configure_cmake)
  scripts/ports.cmake:72 (include)`

**Comment by adevelopcr** [comment]
now I can't build any thing

**Comment by wangli28** [comment]
Please open a new issue if this is still a problem for you.
