### ISSUE TITLE
[matio] Build error on x64-linux where is setting -j3?

### ISSUE THREAD

**Issue by zp146** [microsoft/vcpkg#37115]
Building matio[core,hdf5,zlib]:x64-linux@1.5.26...
-- Installing port from location: /home/better/reps/github/vcpkg/buildtrees/versioning_/versions/matio/9fd8ec3eacecc04384ff5a048c0962f852cdb793
-- Using cached tbeu-matio-v1.5.26.tar.gz.
-- Cleaning sources at /home/better/reps/github/vcpkg/buildtrees/matio/src/v1.5.26-c50df3a1d0.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/better/reps/github/vcpkg/downloads/tbeu-matio-v1.5.26.tar.gz
-- Applying patch fix-dependencies.patch
-- Using source at /home/better/reps/github/vcpkg/buildtrees/matio/src/v1.5.26-c50df3a1d0.clean
-- Configuring x64-linux
-- Building x64-linux-dbg
-- Building x64-linux-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: /home/better/reps/github/vcpkg/downloads/tools/cmake-3.27.1-linux/cmake-3.27.1-linux-x86_64/bin/cmake --build . --config Release --target install -- -v -j3
    Working Directory: /home/better/reps/github/vcpkg/buildtrees/matio/x64-linux-rel
    See logs for more information:
      /home/better/reps/github/vcpkg/buildtrees/matio/install-x64-linux-rel-out.log

Call Stack (most recent call first):
  vcpkg_installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  vcpkg_installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  buildtrees/versioning_/versions/matio/9fd8ec3eacecc04384ff5a048c0962f852cdb793/portfile.cmake:28 (vcpkg_cmake_install)
  scripts/ports.cmake:172 (include)

**Comment by FrankXie05** [comment]
Please see [#30604](https://github.com/microsoft/vcpkg/issues/30604) for how to report an issue.
