### ISSUE TITLE
[rttr] Build error on x64-android

### ISSUE THREAD

**Issue by diaosi39** [microsoft/vcpkg#37123]
### Operating system

 x64-windows

### Compiler

Clang 14.0.06

### Steps to reproduce the behavior

```Shell
vcpkg install rttr:arm64-android
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
    rttr[core]:arm64-android -> 0.9.6+20210811
Detecting compiler hash for triplet arm64-android...
-- Automatically setting HTTP(S)_PROXY environment variables to "127.0.0.1:7890".
Restored 0 package(s) from C:\Users\Lenovo\AppData\Local\vcpkg\archives in 315 us. Use --debug to see more details.
Installing 1/1 rttr:arm64-android...
Building rttr[core]:arm64-android...
-- Using cached rttrorg-rttr-7edbd580cfad509a3253c733e70144e36f02ecd4.tar.gz.
-- Cleaning sources at D:/vcpkg/buildtrees/rttr/src/e36f02ecd4-afbbb37f66.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/rttrorg-rttr-7edbd580cfad509a3253c733e70144e36f02ecd4.tar.gz
-- Applying patch fix-directory-output.patch
-- Applying patch Fix-depends.patch
-- Applying patch remove-owner-read-perms.patch
-- Applying patch disable-unsupport-header.patch
-- Using source at D:/vcpkg/buildtrees/rttr/src/e36f02ecd4-afbbb37f66.clean
-- Configuring arm64-android
-- Building arm64-android-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j17
    Working Directory: D:/vcpkg/buildtrees/rttr/arm64-android-dbg
    See logs for more information:
      D:\vcpkg\buildtrees\rttr\install-arm64-android-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/rttr/portfile.cmake:42 (vcpkg_cmake_install)
  scripts/ports.cmake:170 (include)

[install-arm64-android-dbg-out.log](https://github.com/microsoft/vcpkg/files/14481434/install-arm64-android-dbg-out.log)

**Comment by FrankXie05** [comment]
Reproduce on `x64-android`.
