### ISSUE TITLE
vcpkg removes environment variables when calling cmake

### ISSUE THREAD

**Issue by donny-dont** [microsoft/vcpkg#3712]
I have a custom triplet with its own toolchain file. The root of its SDK is typically set with an environment variable but that environment variable is gone once CMake starts running within vcpkg. Is there a good place to transfer that environment variable over? Currently I had to change the toolchain file to specify a default.

**Comment by ras0219-msft** [comment]
Thanks for posting this issue!

The triplet file can set environment variables via
```
set(ENV{var} "setting")
```
and they should be available during the build.

**Comment by donny-dont** [comment]
@ras0219-msft in this case the environment variable was set but then its gone when `vcpkg` runs. Is there any way to do this or should the person just add that to the triplet file?

**Comment by martin-s** [comment]
It's by design to clear all environment variables when vcpkg is run. You can either edit/write to triplet file or port file to inject variables to the environment.
I have also in mind that there is a whitelist for specific environment variables which @ras0219-msft can answer.

**Comment by ras0219-msft** [comment]
First, let me explain why we clear the environment: Vcpkg is designed to build software _reliably_ across multiple machines. This means isolating the inner builds from as much external machine state as possible (such as the presence or absence of external SDKs).

Therefore, the best and most native way (if possible) to handle prebuilt SDKs is to create a vcpkg portfile for them that downloads, extracts, and installs the headers and libs just like any other vcpkg port. For examples, see the `kinectsdk1`[1], `kinectsdk2`[2], and `msmpi`[3] ports.

If you can take this approach, then you get the benefit that any downstream libraries you want to build will _just work_ on any machine, regardless of the initial user's state.

If that isn't possible, then the simplest option would be to read from a file via something like:
```cmake
# In a triplet file like triplets\x86-windows.cmake
file(READ "${CMAKE_CURRENT_LIST_DIR}/../FOO_SDK_DIR.txt" _foo_sdk_dir)
set(ENV{FOO_SDK_DIR} "${_foo_sdk_dir}")
```
This would read from a file `/path/to/vcpkg/FOO_SDK_DIR.txt`.

It is also possible to edit our whitelist for environment variables in the tool source code here[4], however I think the above approach is a better option.

[1] https://github.com/Microsoft/vcpkg/blob/master/ports/kinectsdk1/portfile.cmake
[2] https://github.com/Microsoft/vcpkg/blob/master/ports/kinectsdk2/portfile.cmake
[3] https://github.com/Microsoft/vcpkg/blob/master/ports/msmpi/portfile.cmake -- note that this one isn't fully contained (unfortunately)
[4] https://github.com/Microsoft/vcpkg/blob/2a0bf9c488d5291e82a37d19d4b0f81e79678f0d/toolsrc/src/vcpkg/base/system.cpp#L141-L185

**Comment by cbezault** [comment]
We're planning on adding a `VCPKG_ENV_PASSTHROUGH` variable that can be set in the triplet to pass through env variables to cmake.

**Comment by ras0219-msft** [comment]
`VCPKG_ENV_PASSTHROUGH` has been implemented: https://github.com/Microsoft/vcpkg/blob/master/docs/users/triplets.md#vcpkg_env_passthrough
