### ISSUE TITLE
[boost-exception] Build error on x64-windows

### ISSUE THREAD

**Issue by ZhouYuJiang-329** [microsoft/vcpkg#37131]
Copy issue body from D:/vcpkg/installed/vcpkg/issue_body.md
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: D:/ompl/cmake/bin/cmake.exe --build . --config Debug --target install -- -v -j17
    Working Directory: D:/vcpkg/buildtrees/boost-exception/x64-windows-dbg
    See logs for more information:
      D:\vcpkg\buildtrees\boost-exception\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:139 (vcpkg_cmake_install)
  ports/boost-exception/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:172 (include)

error: building boost-exception:x64-windows failed with: BUILD_FAILED
Elapsed time to handle boost-exception:x64-windows: 4.5 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
how to solve this problem
the install-x64-windows-dbg-out.log is:
FAILED: CMakeFiles/boost D:/vcpkg/buildtrees/boost-exception/x64-windows-dbg/CMakeFiles/boost 
cmd.exe /C "cd /D D:\vcpkg\buildtrees\boost-exception\src\ost-1.84.0-4868094bf7.clean\build && D:\vcpkg\installed\x64-windows\tools\boost-build\b2.exe toolset=msvc --user-config=D:/vcpkg/buildtrees/boost-exception/x64-windows-dbg/user-config.jam --stagedir=D:/vcpkg/buildtrees/boost-exception/x64-windows-dbg/stage --build-dir=D:/vcpkg/buildtrees/boost-exception/x64-windows-dbg runtime-link=shared link=shared address-model=64 architecture=x86 target-os=windows threadapi=win32 variant=debug --disable-icu --with-atomic --with-random --with-date_time --with-filesystem --with-system --with-thread --with-chrono -j 17 -sBOOST_ROOT=D:/vcpkg/installed/x64-windows/tools/boost-build -sBOOST_BUILD_PATH=D:/vcpkg/installed/x64-windows/tools/boost-build --debug-configuration --debug-building --debug-generators --ignore-site-config --hash -q debug-symbols=on -d +2 threading=multi stage"
notice: loading B2 from D:/vcpkg/installed/x64-windows/tools/boost-build/src/kernel/bootstrap.jam
notice: Site configuration files will be ignored due to the
notice: --ignore-site-config command-line option.
notice: Loading explicitly specified user configuration file:

**Comment by MonicaLiu0311** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
