### ISSUE TITLE
Building boost

### ISSUE THREAD

**Issue by iso8859** [microsoft/vcpkg#3714]
Hello vcpkg community.
I'm new to vcpkg and use to build boost the old way :-)
I spend two days trying to build boost in static+x86+x64+debug+release
I share my feedback and a working CMakeFile.txt here
https://github.com/iso8859/vcpkg-boost
A lot of reverse ingeniering was needed to obtain two working sln that can build un release and debug.

Sincerely,
Remi

**Comment by NancyLi1013** [comment]
Hi @iso8859, thanks for posting this issue. Boost has been upgraded. I have tested and boost can be installed and built successfully now. Could you please update to the latest version and try it again?

**Comment by PhoebeHui** [comment]
@iso8859, please reopen this issue if it still be a problem for you.
