### ISSUE TITLE
error: building draco:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by jessplease** [microsoft/vcpkg#37148]
I'm trying to install the assimp package. I updated my vcpkg package. However, I am getting an error that there is an error building draco package, which assimp seems dependent on. 
<img width="460" alt="Screenshot 2024-03-05 104425" src="https://github.com/microsoft/vcpkg/assets/72938112/d0fac416-fda7-4540-9d46-fcacbe75edd7">

**Comment by StarGate-One** [comment]
Please see #30604 How to reports a package build failure [Explanation Video].

**Comment by jimwang118** [comment]
Please see #30604 for how to report an issue.
