### ISSUE TITLE
Unclear error for PR build

### ISSUE THREAD

**Issue by a4z** [microsoft/vcpkg#37153]
**Describe the bug**
[This PR does not build, and I don't understand why.](https://github.com/microsoft/vcpkg/pull/37142)

Just one platform, Win32, reports a JSON error, which makes no sense to me.

**Environment**
- OS: Win32
- Compiler: not applicable

**To Reproduce**

Re-Run the PR 

**Expected behavior**
The PR build should pass like all others

**Failure logs**
please see https://github.com/microsoft/vcpkg/pull/37142

**Additional context**
Sorry for this issue, I would like to be able to help myself, but the error is not logical or helpful to me. 
Everything works local for me, and also for all other configurations, except Win32, and that the issue is partins of the version JSON file is strange.

**Comment by MonicaLiu0311** [comment]
Already answered in PR: https://github.com/microsoft/vcpkg/pull/37142#issuecomment-1979983996

**Comment by a4z** [comment]
Thank you! I am not sure what happend in with the first attempt, , but redoing the whole update flow fixed the issue in the (new) PR
