### ISSUE TITLE
Python 3 fails to build with VS2015 and default SDK

### ISSUE THREAD

**Issue by DavidFair** [Microsoft/vcpkg#3715]
Attempting to build python3 results in a failure as a specific SDK version is not installed. 
There is an upstream [issue](https://bugs.python.org/issue32423) for this too, with a potential patch.

Environment:
- Fresh install of Windows 10 (Build 17134)
- Visual Studio 2015
- Latest version of vcpkg - specifically commit 2a0bf9c4

Additional details from vcpkg:
- Package: python3:x64-windows
- Vcpkg version: 0.0.113-nohash

Build log:
```
...
     1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 10.0.15063.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\david\vcpkg\buildtrees\python3\src\v3.6.4-c8a1ba05c7-Lib-dynamic-crt-dynamic\PCBuild\pythoncore.vcxproj]
     1>Done Building Project "C:\Users\david\vcpkg\buildtrees\python3\src\v3.6.4-c8a1ba05c7-Lib-dynamic-crt-dynamic\PCBuild\pythoncore.vcxproj" (Rebuild target(s)) -- FAILED.

Build FAILED.

       "C:\Users\david\vcpkg\buildtrees\python3\src\v3.6.4-c8a1ba05c7-Lib-dynamic-crt-dynamic\PCBuild\pythoncore.vcxproj" (Rebuild target) (1) ->
       (Desktop_PlatformPrepareForBuild target) -> 
         C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 10.0.15063.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\david\vcpkg\buildtrees\python3\src\v3.6.4-c8a1ba05c7-Lib-dynamic-crt-dynamic\PCBuild\pythoncore.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.93
```

**Comment by Voskrese** [comment]
по вашим же ссылкам есть патч, попробуйте просто добавить вашу версию SDK

> By your own links there is a patch, try to simply add your version of SDK

`https://github.com/isuruf/cpython/commit/9432a2c7f63b3bb55e8066e91eade81321154476`

`     <DefaultWindowsSDKVersion Condition="$(_RegistryVersion) == '10.0.17134'">10.0.17134.0</DefaultWindowsSDKVersion>`

**Comment by JackBoosY** [comment]
Hi @DavidFair , thanks for reporting this issue.
This bug seems has been fixed. Plz update vcpkg and rebuild it.
Please open a new issue if this is still a problem for you.
Thx.
