### ISSUE TITLE
[New Port Request] SDL3 prerelease

### ISSUE THREAD

**Issue by briaguya-ai** [microsoft/vcpkg#37162]
### Library name

SDL3

### Source repository URL

https://github.com/libsdl-org/SDL.git

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

This was originally requested here https://github.com/Microsoft/vcpkg/issues/32062 but closed for inactivity

**Comment by briaguya-ai** [comment]
Please don't close this for being stale

**Comment by howprice** [comment]
SDL3 is now [ABI stable](https://github.com/libsdl-org/SDL/issues/11060) and a package would be much appreciated. Could this please be re-opened?

**Comment by dg0yt** [comment]
It is not necessary to re-open the issue. There is a PR: PR #40867.
