### ISSUE TITLE
Recast DetourDebugDraw.h headers not found

### ISSUE THREAD

**Issue by doomtr666** [Microsoft/vcpkg#3719]
Hi,
I'm having a problem using recast debug utils:

#include "Recast/DebugUtils/DetourDebugDraw.h"

"detourdebugdraw.h(22): fatal error C1083: Impossible d'ouvrir le fichier include : 'DetourNavMesh.h' : No such file or directory"

There're path issues in RecastDebugDraw.h too.

**Comment by wangli28** [comment]
@doomtr666, thank you for posting the issue, does the issue still occur?

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
