### ISSUE TITLE
Please update Cryptopp to 7.0.0

### ISSUE THREAD

**Issue by cempayzin** [Microsoft/vcpkg#3721]
A new version with multiple important fixes are out more than a month. Please update vcpkg so we can get the latest.

**Comment by studoot** [comment]
This would (I would imagine) also have the beneficial side-effect of picking up [a commit](https://github.com/noloader/cryptopp-cmake/commit/502e1ffbffd099e4a81a59714220830669f5b9f6) that modifies the cryptopp include directories from `${INSTALL_LOCATION}/include/cryptopp` to `${INSTALL_LOCATION}/include/`.

This would mean that includes of the form `#include <cryptopp/sha3.h>` would now work (whereas at the moment, an include of `<sha3.h>` is needed. Given that all of the sample code on the cryptopp website uses the `<cryptopp/sha3.h>` form, making this change would mean that using cryptocpp with vcpkg would now give an environment that matches the one used in the Cryptopp samples.

**Comment by NancyLi1013** [comment]
@cempayzin , the package has been updated to the version 8.0.0 on the master. Please take a look.
Thanks.
