### ISSUE TITLE
[libiconv] build failure in Manifest mode

### ISSUE THREAD

**Issue by patrikhuber** [microsoft/vcpkg#37228]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
* Have a vcpkg.json that contains `libiconv` as dependency
* Have a setup.py that fetches vcpkg, runs vcpkg in manifest mode on the dependencies in vcpkg.json
* Do `python setup.py bdist_wheel` or `pip install .\mylib`

=> Then vcpkg will fail building/installing libiconv - error output see below in "Failure logs".


I should note that a plain `vcpkg.exe install libiconv:x64-windows` on the command-line works and does not give above error.

A random guess I have at what might play a role is that `setup.py` calls vcpkg with `subprocess.run(["cmake", "--build", "build/", *build_args], cwd=build_temp, shell=True, check=True)`. This normally works fine. But perhaps the libiconv build/install step does some weird shell magic that fails if it's run within `subprocess.run()`?

The whole thing is a bit weird though, as `install-x64-windows-dbg-out.log` suggests the problem happens during the install step - and in that log, there are various errors ranging from `Makefile:51: update target 'install' due to: target does not exist` to ".a" (Linux) files it can't find, to actually linker errors (unresolved external symbol). Something must trigger these linker errors in libiconv when running vcpkg through `setup.py` as opposed to just doing `vcpkg.exe install libiconv:x64-windows` ...? This approach works completely fine for any other library/dependency I've used so far.
```

### Failure logs

```
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
-- Installing x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/Users/PatrikHuber/Projects/Facebow/iconv-vcpkg-python-build-error-repro/build/temp.win-amd64-cpython-312/Release/mylib/vcpkg/downloads/tools/msys2/09133458fed80fcb/usr/bin/make.exe -j 21 --trace -f Makefile install DESTDIR=/C/Users/PatrikHuber/Projects/Facebow/iconv-vcpkg-python-build-error-repro/build/temp.win-amd64-cpython-312/Release/mylib/vcpkg/packages/libiconv_x64-windows
    Working Directory: C:/Users/PatrikHuber/Projects/Facebow/iconv-vcpkg-python-build-error-repro/build/temp.win-amd64-cpython-312/Release/mylib/vcpkg/buildtrees/libiconv/x64-windows-dbg/
    See logs for more information:
      C:\Users\PatrikHuber\Projects\Facebow\iconv-vcpkg-python-build-error-repro\build\temp.win-amd64-cpython-312\Release\mylib\vcpkg\buildtrees\libiconv\install-x64-windows-dbg-out.log
      C:\Users\PatrikHuber\Projects\Facebow\iconv-vcpkg-python-build-error-repro\build\temp.win-amd64-cpython-312\Release\mylib\vcpkg\buildtrees\libiconv\install-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:153 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:2 (vcpkg_build_make)
  C:/Users/PatrikHuber/AppData/Local/vcpkg/registries/git-trees/6103c3aaaf279f20df4c758fd25d5954c8582cbd/portfile.cmake:39 (vcpkg_install_make)
  scripts/ports.cmake:172 (include)


error: building libiconv:x64-windows failed with: BUILD_FAILED
```

* [install-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/14527263/install-x64-windows-dbg-err.log)
* [install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/14527264/install-x64-windows-dbg-out.log)

### Additional context

Full minimal repro:
* [CMakeLists.txt](https://github.com/microsoft/vcpkg/files/14527270/CMakeLists.txt)
* [python-bindings.cpp.txt](https://github.com/microsoft/vcpkg/files/14527273/python-bindings.cpp.txt) (remove .txt extension from this)
* [setup.py.txt](https://github.com/microsoft/vcpkg/files/14527276/setup.py.txt) (remove .txt extension from this)
* [vcpkg.json](https://github.com/microsoft/vcpkg/files/14527277/vcpkg.json)
* [vcpkg-configuration.json](https://github.com/microsoft/vcpkg/files/14527278/vcpkg-configuration.json)

Put all these files in a directory and then do `python setup.py bdist_wheel` (it needs `pip install setuptools wheel` before).

**Comment by patrikhuber** [comment]
Okay, so it turns out this may not have anything to do with setup.py or subprocess.call(), but actually with vcpkg's manifest mode:

* `vcpkg.exe install libiconv` works (classic mode)
* `vcpkg.exe install` (in a project with a vcpkg.json with libiconv as dependency) **fails** with the above error(s) (manifest mode)

I'm puzzled, can anyone makes sense of this / have any ideas?

libiconv's build seems to be somewhat complicated, it downloads and uses msys2/mingw, as far as I can see.

**Comment by patrikhuber** [comment]
By almost pure chance I found the cause and was able to "fix" it. The problem was Windows's MAX_PATH limit. When I ran vcpkg in Manifest mode or with setup.py, it creates quite a deep folder structure. Then, MSYS2 within the libiconv installation creates an even deeper folder structure. That then causes libiconv's install step to fail, because there are probably missing files and stuff.

Disabling the MAX_PATH limit using:
`` 
New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
-Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
`` 
and then a reboot, and that fixed it for me.

Perhaps there should be a big warning in vcpkg when you install libiconv that you _very likely_ might run into problems if you haven't disabled MAX_PATH.

I'm closing this as it's fixed for me but CC @dg0yt @BillyONeal in case you want to read my suggestion of a warning and potentially add that. These are the obscure errors that can take days to debug or you might likely never find the cause and give up, if you hit the problem.

**Comment by dg0yt** [comment]
In fact, path length was the first thing which I wanted to suggest here. This is a fairly frequent issue, and not specific to libiconv. (libiconv is a dependency which is installed early, so it might be hitten more often. You may get the same issue with another port even after libiconv success.)
