### ISSUE TITLE
[nowide] x64-windows-static build links static CRT

### ISSUE THREAD

**Issue by EvanBalster** [microsoft/vcpkg#37250]
### Operating system

Windows 11 x64

### Compiler

Microsoft Visual C++ 2022

### Steps to reproduce the behavior

```Shell
`./vcpkg install nowide:x64-windows-static`

This installs static libraries for the standalone branch of boost::nowide.

Unlike most other `x64-windows-static` ports, `nowide` is built against the static version of the Microsoft Visual C++ runtime.  This results in build errors when linking it alongside `x64-windows-static` versions of other vcpkg packages.
```

### Failure logs

Essentially, a downstream project will complain about the C++ runtime configuration.

### Additional context

When building `nowide` directly from the [standalone branch](https://github.com/boostorg/nowide/tree/standalone), the result will be a static library built against the ''Multi-Threaded DLL'' version(s) of the Microsoft Visual C++ runtime.  This suggests a mis-configuration of the vcpkg port rather than an upstream issue that needs to be patched out.

**Comment by dg0yt** [comment]
`x64-windows-static` is for static library linkage *and* static runtime linkage.
If you want static library linkage with dynamic runtime linkage, you must choose `x64-windows-static-md`.

**Comment by Cheney-W** [comment]
@EvanBalster Has `x64-windows-static-md` triplet resolved your issue?

**Comment by EvanBalster** [comment]
Yes, it appears I misunderstood the behavior of `x64-windows-static`.  By happenstance my other ~20 dependencies had no issue linking with an application using the dynamic runtime, probably because most of those were written in C.  I'll close this issue.
