### ISSUE TITLE
[boost] boostorg-cobalt-boost build failure with C++ 17

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#37256]
### Operating system

Windows 11

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
vcpkg install boost
```

### Failure logs

```sh
> vcpkg install boost
...
-- Downloading https://github.com/boostorg/cobalt/archive/boost-1.84.0.tar.gz -> boostorg-cobalt-boost-1.84.0.tar.gz...
-- Cleaning sources at C:/path/to/vcpkg/buildtrees/boost-cobalt/src/ost-1.84.0-f1b8232bac.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/path/to/vcpkg/downloads/boostorg-cobalt-boost-1.84.0.tar.gz
-- Using source at C:/path/to/vcpkg/buildtrees/boost-cobalt/src/ost-1.84.0-f1b8232bac.clean
-- Including C:/path/to/vcpkg/ports/boost-cobalt/b2-options.cmake
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows-cpp17
-- Configuring x64-windows-cpp17
-- Building x64-windows-cpp17-dbg
-- Building x64-windows-cpp17-rel
CMake Error at installed/x64-windows-cpp17/share/boost-build/boost-modular-build.cmake:196 (message):
  No libraries were produced.  This indicates a failure while building the
  boost library.
Call Stack (most recent call first):
  ports/boost-cobalt/portfile.cmake:17 (boost_modular_build)
  scripts/ports.cmake:175 (include)


error: building boost-cobalt:x64-windows-cpp17 failed with: BUILD_FAILED
Elapsed time to handle boost-cobalt:x64-windows-cpp17: 5.1 s
...
```

triplet: x64-windows-cpp17.cmake
```cmake
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_CXX_FLAGS "/std:c++17")
set(VCPKG_C_FLAGS "/std:c17")
```

**Comment by FrankXie05** [comment]
Thanks for posting this issue, could you plesa refer to this issue https://github.com/microsoft/vcpkg/issues/33288 ?

**Comment by playgithub** [comment]
`CMake Error at installed/x64-windows-cpp17/share/boost-build/boost-modular-build.cmake:196` as below:
```cmake
if(NOT EXISTS "${CURRENT_PACKAGES_DIR}/lib")
    message(FATAL_ERROR "No libraries were produced. This indicates a failure while building the boost library.")
endif()
```

No complie or link error, but lack of the lib directory.

**Comment by FrankXie05** [comment]
@playgithub 
Could you please run the following command and try again? :)
```
./vcpkg remove boost-uninstall:x64-windows-cpp17 --recurse
```

**Comment by FrankXie05** [comment]
Reproduce this issue locally on `x64-windows`.

![image](https://github.com/microsoft/vcpkg/assets/65999885/f18337c5-d5d5-4a16-aa06-7d2dff1dc5d3)

**Comment by playgithub** [comment]
> @playgithub Could you please run the following command and try again? :)
> 
> ```
> ./vcpkg remove boost-uninstall:x64-windows-cpp17 --recurse
> ```

With the env vars below
```
VCPKG_DEFAULT_HOST_TRIPLET x64-windows-cpp17
VCPKG_DEFAULT_TRIPLET x64-windows-cpp17
```
Tried as below
```sh
vcpkg remove boost-uninstall:x64-windows-cpp17 --recurse
vcpkg install boost
```
Got the same error

**Comment by playgithub** [comment]
How long would it be fixed?

**Comment by FrankXie05** [comment]
@playgithub 
Do you have the generated lib in folder `\vcpkg\installed\x64-windows-cpp17\lib`?

**Comment by playgithub** [comment]
> Do you have the generated lib in folder `\vcpkg\installed\x64-windows-cpp17\lib`?

For the bug blocks my work, I've switched to Linux, so I can't test it now.

**Comment by playgithub** [comment]
> Do you have the generated lib in folder `\vcpkg\installed\x64-windows-cpp17\lib`?

Yes

**Comment by achmad-agus** [comment]
Will there be any target date for this ? 
We are having same issue for 'x64-linux' and cannot do anything without the fix.

**Comment by FrankXie05** [comment]
@achmad-agus 
Sorry for the late reply, for `boost-cobalt`, both `vcpkg` and `upstream` have a C++ standard requirement of 20 for the build.

vcpkg: https://github.com/microsoft/vcpkg/blob/5fa0f075ea51f305b627ecd5e050a363707353ff/ports/boost-cobalt/b2-options.cmake#L1

Upstream: 
https://github.com/boostorg/cobalt/blob/820f9c3906c236e6fd316cba4736c87e16b4eacb/build/Jamfile#L54

**Comment by playgithub** [comment]
If the error message would have told this, it would save a lot of time.
Thanks
