### ISSUE TITLE
Error building gdal as dynamic, and dependencies as static

### ISSUE THREAD

**Issue by oddraly** [microsoft/vcpkg#3725]
My setup is:
- Windows10 Version 10.0.15063 Build 15063
- Locale	Norway
- Visual Studio 2017 latest update
- Package: gdal:x64-windows-mixed
- Vcpkg version: 0.0.113-nohash

This is my triplet file for mixedmode build(The way I want it to be):
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)

if(${PORT} MATCHES "gdal|pdal")
	set(VCPKG_LIBRARY_LINKAGE dynamic)
else()
	set(VCPKG_LIBRARY_LINKAGE static)
endif()
```
## Problem 1)
I don't know if this is an issue for gdal or libmysql.

But I'm not able to build gdal, and the reason seems to be that libmysql doesn't copy lib file to installed\lib folder.

Here is the error message from vcpkg install log:
> LINK : fatal error LNK1181: cannot open input file 'D:\Src\o\vcpkg\installed\x64-windows-mixedmode\lib\libmysql.lib'

If I manually copy the file from buildtrees\libmysql\x64-windows-mixedmode-rel\libmysql\libmysql.lib, then it works

## Problem 2)
First problem solved, then I run into a new problem, again from install.log

> LINK : fatal error LNK1181: cannot open input file 'D:\Src\o\vcpkg\installed\x64-windows-mixedmode\lib\geos_c.lib'

As I have built geos as a static lib, the file I have is 'D:\Src\o\vcpkg\installed\x64-windows-mixedmode\lib\libgeos_c.lib'

Adding geos in the list of dynamically linked builds, in my triplet file, resolves this problem **(...but this is not what I want)**

## Problem 3)
Now I get linking errors, for unresolved externals, from log:

> Creating library gdal_i.lib and object gdal_i.exp
> libpq.lib(fe-connect.c.obj) : error LNK2019: unresolved external symbol __imp_FreeCredentialsHandle referenced in function closePGconn
> ...
> gdal203.dll : fatal error LNK1120: 215 unresolved externals 

What's the right way to do this, if it's possible?

I have previously configured gdal build using cmake, but I would like to use vcpkg if it's possible.
We use delay load on gdal and pdal, so that's why I want only those builds as dynamic.

**Comment by PhoebeHui** [comment]
@oddraly, currently gdal use VCPKG_BUILD_TYPE to build release or debug only, it successfully installed. you can have a try.

PS F:\vcpkg\src> ./vcpkg version
Vcpkg package management program version 2018.11.23-nohash

PS F:\vcpkg\src> .\vcpkg install gdal:x64-windows
The following packages will be built and installed:
    gdal[core,mysql-libmysql]:x64-windows
Starting package 1/1: gdal:x64-windows
Building package gdal[core,mysql-libmysql]:x64-windows...
-- Using cached F:/VCPKG/src/downloads/gdal240.zip
-- Extracting source F:/VCPKG/src/downloads/gdal240.zip
-- Applying patch F:/VCPKG/src/ports/gdal/0001-Fix-debug-crt-flags.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Extracting source F:/VCPKG/src/downloads/gdal240.zip
-- Applying patch F:/VCPKG/src/ports/gdal/0001-Fix-debug-crt-flags.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Building x64-windows-rel
-- Building x64-windows-rel done
-- Building x64-windows-dbg
-- Building x64-windows-dbg done
-- Packaging x64-windows
-- Performing post-build validation
-- Performing post-build validation done
Building package gdal[core,mysql-libmysql]:x64-windows... done
Installing package gdal[core,mysql-libmysql]:x64-windows...
Installing package gdal[core,mysql-libmysql]:x64-windows... done
Elapsed time for package gdal:x64-windows: 26.28 min

Total elapsed time: 26.28 min

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
