### ISSUE TITLE
Building package sdl2:x64-uwp failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Jace-Samsung** [Microsoft/vcpkg#3727]
The sdl2 port needs updated to be compatible with WinRT / UWP.  The 2.0.8 version of sdl2 does not build from a clean checkout of vcpkg.  Reverting to the 2.0.7 version builds successfully.  It looks like ports/sdl2/enable-winrt-cmake.patch needs to be updated to be compatible with the latest stable version of SDL2, which includes WASAPI audio driver support for WinRT / UWP.

Package: sdl2:x64-uwp
Vcpkg version: 0.0.113-nohash

**Comment by PhoebeHui** [comment]
@Jace-Samsung Sdl2 update to 2.0.9 version, and it successfully installed.

PS F:\vcpkg\src> ./vcpkg version
Vcpkg package management program version 2018.11.23-nohash

See LICENSE.txt for license information.
PS F:\vcpkg\src> ./vcpkg install sdl2:x64-uwp
The following packages will be built and installed:
    sdl2[core]:x64-uwp
Starting package 1/1: sdl2:x64-uwp
Building package sdl2[core]:x64-uwp...
-- Using cached F:/VCPKG/src/downloads/SDL-Mirror-SDL-release-2.0.9.tar.gz
-- Using source at F:/VCPKG/src/buildtrees/sdl2/src/ease-2.0.9-ad425106c1
-- Configuring x64-uwp
-- Building x64-uwp-dbg
-- Building x64-uwp-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package sdl2[core]:x64-uwp... done
Installing package sdl2[core]:x64-uwp...
Installing package sdl2[core]:x64-uwp... done
Elapsed time for package sdl2:x64-uwp: 1.902 min

Total elapsed time: 1.902 min

The package sdl2:x64-uwp provides CMake targets:

    find_package(SDL2 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE SDL2::SDL2)

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
