### ISSUE TITLE
libjxl update to v0.10.2

### ISSUE THREAD

**Issue by JamieStM** [microsoft/vcpkg#37288]
### Library name

libjxl

### New version number

0.10.2

### Other information that may be useful (release notes, etc...)

Current version is 0.8.2, releases 0.9.0-0.10.2 have significant API changes and bug fixes, including 2x-20x speed and memory improvements when compressing lossless images (per blog post here: https://cloudinary.com/blog/jpeg-xl-and-the-pareto-front).

**Comment by LilyWangLL** [comment]
Closed as duplicate of #37066.
