### ISSUE TITLE
[boost-regex] Build error on x64-windows

### ISSUE THREAD

**Issue by a-milans-del-bosch** [microsoft/vcpkg#37287]
Copy issue body from C:/Users/almu_/vcpkg/installed/vcpkg/issue_body.md

.\vcpkg install boost-regex:x64-windows
Computing installation plan...
The following packages will be built and installed:
    boost-regex:x64-windows@1.84.0
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\almu_\AppData\Local\vcpkg\archives in 105 us. Use --debug to see more details.
Installing 1/1 boost-regex:x64-windows@1.84.0...
Building boost-regex:x64-windows@1.84.0...
-- Using cached boostorg-regex-boost-1.84.0.tar.gz.
-- Cleaning sources at C:/Users/almu_/vcpkg/buildtrees/boost-regex/src/ost-1.84.0-36fba3ea30.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/almu_/vcpkg/downloads/boostorg-regex-boost-1.84.0.tar.gz
-- Using source at C:/Users/almu_/vcpkg/buildtrees/boost-regex/src/ost-1.84.0-36fba3ea30.clean
-- Including C:/Users/almu_/vcpkg/ports/boost-regex/b2-options.cmake
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/Users/almu_/vcpkg/downloads/tools/cmake-3.27.1-windows/cmake-3.27.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j17
    Working Directory: C:/Users/almu_/vcpkg/buildtrees/boost-regex/x64-windows-dbg
    See logs for more information:
      C:\Users\almu_\vcpkg\buildtrees\boost-regex\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:139 (vcpkg_cmake_install)
  ports/boost-regex/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:175 (include)

error: building boost-regex:x64-windows failed with: BUILD_FAILED
Elapsed time to handle boost-regex:x64-windows: 4.2 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-regex
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[boost-regex]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2FUsers%2Falmu_%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by Cheney-W** [comment]
Please see [#30604](https://github.com/microsoft/vcpkg/issues/30604) for how to report an issue.
