### ISSUE TITLE
[microsoft-signalr] build failure (Could not find a configuration file for package "jsoncpp")

### ISSUE THREAD

**Issue by dab0bby** [microsoft/vcpkg#37285]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
Build the attached project
```

### Failure logs

CMake Error at D:/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package):
  Could not find a configuration file for package "jsoncpp" that is
  compatible with requested version "".

  The following configuration files were considered but not accepted:

  D:/Playground/microsoft-signalr/vcpkg_installed/x86-windows-static/share/jsoncpp/jsoncppConfig.cmake, version: 1.9.5 (32bit)

Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
  vcpkg_installed/x86-windows-static/share/microsoft-signalr/microsoft-signalr-config.cmake:7 (find_dependency)
  D:/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  CMakeLists.txt:10 (find_package)

### Additional context

vcpkg.json
```json
{
  "name": "signalr-test",
  "version": "0.1.0",
  "dependencies": [
    {
      "name": "microsoft-signalr",
      "default-features": false,
      "features": ["messagepack"]
    }
  ]
}
```

CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.8)

set(VCPKG_TARGET_TRIPLET x86-windows-static)
set(CMAKE_TOOLCHAIN_FILE "D:/vcpkg/scripts/buildsystems/vcpkg.cmake")

project(signalr-test)

add_executable(${PROJECT_NAME} main.cpp)

find_package(microsoft-signalr CONFIG REQUIRED)
target_link_libraries(${PROJECT_NAME}
    PRIVATE
        microsoft-signalr::microsoft-signalr)
```

main.cpp
```cpp
int main(int argc, char const *argv[])
{
    return 0;
}
```

**Comment by LilyWangLL** [comment]
The reason is that you installed an `x86-windows-static` port, but during compilation, x64 cl.exe was used. To resolve this error, please add option `-A win32` to your cmake command line.

**Comment by dab0bby** [comment]
@LilyWangLL I just tried and it works with `-A win32` 👍🏾.
What's interesting is that it works with all my other ports (spdlog, catch2, zlib, ...) without the flag except `signalr`.

Any idea why that's the case? Just out of curiosity 😉
