### ISSUE TITLE
It's not always obvious how to use installed packages.

### ISSUE THREAD

**Issue by bradhe** [microsoft/vcpkg#3729]
Conceptually, I love vcpkg and where it's going. There's a lot of really good ideas at play here. Keeping ports definitions directly in the repo is awesome. I've used it on Windows, macOS, and Linux to date. The Windows experience is somewhat better than the macOS experience, obviously the toolchain is better integrated.

In general, when vcpkg works it works great. But it's pretty damn easy to get mind boggling behavior out of it. Typically this seems to come from a lack of transparency.

Consider the following example. I want to include `sdl2-image` in my project. Installing it is pretty straight forward:

```
>> ./vcpkg install sdl2-image
The following packages will be built and installed:
    sdl2-image[core]:x64-linux
Starting package 1/1: sdl2-image:x64-linux
Building package sdl2-image[core]:x64-linux... 
-- CURRENT_INSTALLED_DIR=/home/brad/Development/vcpkg/installed/x64-linux
-- DOWNLOADS=/home/brad/Development/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=/home/brad/Development/vcpkg/packages/sdl2-image_x64-linux
-- CURRENT_BUILDTREES_DIR=/home/brad/Development/vcpkg/buildtrees/sdl2-image
-- CURRENT_PORT_DIR=/home/brad/Development/vcpkg/ports/sdl2-image
-- Using cached /home/brad/Development/vcpkg/downloads/SDL2_image-2.0.2.zip
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Configuring x64-linux-dbg
-- Configuring x64-linux-dbg done
-- Configuring x64-linux-rel
-- Configuring x64-linux-rel done
-- Build x64-linux-dbg
-- Build x64-linux-dbg done
-- Build x64-linux-rel
-- Build x64-linux-rel done
-- Performing post-build validation
-- Performing post-build validation done
Building package sdl2-image[core]:x64-linux... done
Installing package sdl2-image[core]:x64-linux... 
Installing package sdl2-image[core]:x64-linux... done
Elapsed time for package sdl2-image:x64-linux: 2.144 s

Total elapsed time: 2.144 s
```

Notice there's no message about what package to include in my `CMakeLists.txt` file. I end up hunting and pecking around the buildtrees for a while and find that, despite the port being called `sdl2-image` it is *actually* called `SDL_image` -- looks like some kind of SDL related convention or something? Hopefully the libraries the actual libraries are the same (looks like it, based on the libs dir).

Now I need to regenerate my cmake configuration and maybe I'll be able to build and link my project again. Here I encounter another mind boggling issue:

```
cd ./build && cmake .. "-DCMAKE_TOOLCHAIN_FILE=/home/brad/Development/vcpkg/scripts/buildsystems/vcpkg.cmake"
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.67.0
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find SDL_image (missing: SDL_IMAGE_LIBRARIES
  SDL_IMAGE_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindSDL_image.cmake:91 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /home/brad/Development/vcpkg/scripts/buildsystems/vcpkg.cmake:247 (_find_package)
  src/CMakeLists.txt:5 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/brad/Development/game3/build/CMakeFiles/CMakeOutput.log".
Makefile:13: recipe for target 'rebuild' failed
make: *** [rebuild] Error 1
```

So is this...is this an issue with the port (e.g. portfile.cmake or something) or what?

## My actual questions

1. Is there a consistent way to figure out what directives to include to `find_package`?
1. What about the linking stage, is there a consistent way of figuring out what incantation needs to be given to `cmake` via `target_link_libraries`?
1. What tools are available to debug these types of issues? How can I tell when this is a cmake issue vs a packaging issue?
1. Is there a community (irc channel or mailing list or...something?) for this type of support that isn't part of Github?

**Comment by edmBernard** [comment]
It's at each contributor to add the usage like in zlib for example : 
https://github.com/Microsoft/vcpkg/blob/master/ports/zlib/usage
https://github.com/Microsoft/vcpkg/blob/master/ports/zlib/portfile.cmake#L45

**Comment by chronos38** [comment]
@edmBernard If you type the same install command as the first one, the message will actually reappear. But that only works for libraries which provide the message in the first place.

I second this request since I run into a similar issue a few days ago and if it isn't possible to show an easy way how to include packages, then at least enforce a rule for consistency across all packages.

**Comment by ThePhosphorus** [comment]
Hi, do we have any news about this issue?
I'm trying to use SDL2_ttf and SDL2_image and can't seem to find a solution. I only have the `no SDL2_ttf-config.cmake`

Thank you for your time.

**Comment by slawtul** [comment]
Hi guys, the same issue with SDL2_image in my project...

**Comment by pierregillet** [comment]
The following comment is providing a quick but very, very ugly fix that I got from a lecturer (he is not proud of it). **It is very wrong to use that**. Do not use this fix for any important or large project that needs reliability and good practices. Or for anything for that matter. I only used it as a last resort, and hope it won't be used as anything except last resort.

For anybody encountering this issue, a quick fix to get it to work on Windows (although, I repeat, **it is very _very_ ugly**) would be to have as minimal CMakeLists.txt file : 

```
cmake_minimum_required(VERSION 2.8.4)

if (WIN32)  # MSVS is unset before "project"
  set(CMAKE_TOOLCHAIN_FILE ${CMAKE_TOOLCHAIN_FILE} "$ENV{VCPKG_ROOT}//scripts//buildsystems//vcpkg.cmake")
  set(CMAKE_PREFIX_PATH    ${CMAKE_PREFIX_PATH}    "$ENV{VCPKG_ROOT}//installed//x64-windows")
  set(CMAKE_LIBRARY_PATH   ${CMAKE_LIBRARY_PATH}   "$ENV{VCPKG_ROOT}//installed//x64-windows//lib//manual-link")
endif ()

set(name hello-sdl2-image)
project(${name})    # Setting CMAKE_TOOLCHAIN_FILE must precede "project"

add_executable(${name} ${name}.cpp)

find_library(LIBSDL2     SDL2)
find_library(LIBSDL2MAIN SDL2main)
find_library(LIBSDL2IMG  SDL2_image)
target_link_libraries(${name} optimized ${LIBSDL2})
target_link_libraries(${name} optimized ${LIBSDL2MAIN})
target_link_libraries(${name} optimized ${LIBSDL2IMG})

if (WIN32)
  find_path(INCSDL2 SDL2/SDL_image.h) # Call before setting debug find paths
  target_include_directories(${name} PRIVATE ${INCSDL2})

  set(CMAKE_PREFIX_PATH  ${CMAKE_PREFIX_PATH}  "$ENV{VCPKG_ROOT}//installed//x64-windows//debug")
  set(CMAKE_LIBRARY_PATH ${CMAKE_LIBRARY_PATH} "$ENV{VCPKG_ROOT}//installed//x64-windows//debug//lib//manual-link")

  find_library(LIBSDL2D     SDL2d)      # n.b. SDL2d
  find_library(LIBSDL2MAIND SDL2maind)  # n.b. SDL2maind
  find_library(LIBSDL2IMGD  SDL2_image) # Debug library has the same name!

  target_link_libraries(${name} debug ${LIBSDL2D})
  target_link_libraries(${name} debug ${LIBSDL2MAIND})
  target_link_libraries(${name} debug ${LIBSDL2IMGD})

  set_property(DIRECTORY PROPERTY VS_STARTUP_PROJECT ${name})
endif (WIN32)
````

I only provide that as a last resort, or for testing. I hope nobody will use it, but since I needed it I guess someday someone else might need it as much as I needed it.

**Comment by chronos38** [comment]
Installing SDL image now provides a message on how to include it:
`find_package(sdl2-image CONFIG REQUIRED)`
`target_link_libraries(main PRIVATE SDL2::SDL2_image)`

I believe this issue can be closed as the above code worked superbly fine for me.

**Comment by cbezault** [comment]
In general if a port supports cmake and exports cmake targets we will print the targets to use in downstream projects.
