### ISSUE TITLE
error with kinectsdk2:x64-windows

### ISSUE THREAD

**Issue by hanseuljun** [Microsoft/vcpkg#3733]
Reporting a problem I had while installing kinectsdk2. Attached is the log I got from PowerShell.

Starting package 1/1: kinectsdk2:x64-windows
Building package kinectsdk2[core]:x64-windows...
-- CURRENT_INSTALLED_DIR=C:/Users/hanseuljun/GitRepositories/GitHub/vcpkg/installed/x64-windows
-- DOWNLOADS=C:/Users/hanseuljun/GitRepositories/GitHub/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/hanseuljun/GitRepositories/GitHub/vcpkg/packages/kinectsdk2_x64-windows
-- CURRENT_BUILDTREES_DIR=C:/Users/hanseuljun/GitRepositories/GitHub/vcpkg/buildtrees/kinectsdk2
-- CURRENT_PORT_DIR=C:/Users/hanseuljun/GitRepositories/GitHub/vcpkg/ports/kinectsdk2
-- Using cached C:/Users/hanseuljun/GitRepositories/GitHub/vcpkg/downloads/KinectSDK-v2.0_1409-Setup.exe
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: C:/Users/hanseuljun/GitRepositories/GitHub/vcpkg/buildtrees/kinectsdk2/msiextract-msmpi.bat
    Working Directory: C:/Users/hanseuljun/GitRepositories/GitHub/vcpkg/buildtrees/kinectsdk2
    See logs for more information:
      C:\Users\hanseuljun\GitRepositories\GitHub\vcpkg\buildtrees\kinectsdk2\extract_msi_installer-out.log

Call Stack (most recent call first):
  ports/kinectsdk2/portfile.cmake:41 (vcpkg_execute_required_process)
  scripts/ports.cmake:72 (include)

Error: Building package kinectsdk2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: kinectsdk2:x64-windows
  Vcpkg version: 0.0.113-nohash

**Comment by wangli28** [comment]
Please open a new issue if this is still a problem for you.
