### ISSUE TITLE
Libraries needs classification or tags - [Proposal]

### ISSUE THREAD

**Issue by aPSopt** [microsoft/vcpkg#3734]
There are too much libraries included in the vcpkg. 
When I search the library for solving some task I need read all libraries description that present in vcpkg.
It took too much time + often description cut offs by "..." - so I must search the description in the web. It take too much time.

I propose to add some classification for libraries or even add tags for them.

**Comment by carmangary** [comment]
I don't think vcpkg was meant to allow you to browse and discover libraries.  Mainly just a way to build and include them in your project.   I agree it would be nice if the description wasn't cut off, though.

**Comment by aPSopt** [comment]
Yes, vcpkg was initially just a way to build and include libs on the Windows platform. I propose to make it more functional (as early was add support the Linux platform).

There are 2 issues that takes time:
1) "searching" trouble that I described above.
2) discover the new libraries. I need to look at the diff between vcpkg search result (month ago and today) to see what new libraries was added. Also description often don`t give needed information so I need to search in the web.

Solving above troubles will make vcpkg more helpfull in usage. Isnt it?

**Comment by aPSopt** [comment]
Today I made the diff between vcpkg search result today and few month ago. The sittuation is become worse. For example take a look on following new description:

> "ade 0.1.1e ADE Framework is a graph construction, manipulation, and processing framework...."

And there are no any link, google didn`t see it, the above decsription nothing describe. It looks like piece of garbage or whose private library that somehow come to vcpkg.

I propose oblige the author of every new library to provide the full description + tags for his library. And add ability for vcpkg to show this description on demand.

**Comment by PhoebeHui** [comment]
@aPSopt, thanks for your suggestions!

> discover the new libraries

You can check the new libraries from the release notes https://github.com/microsoft/vcpkg/releases/tag/2021.04.30.
For the description, currently we add the homepage to the port, it will help to navigate to the Upstream directly.

BTW, the vcpkg website is now available to view as a draft! this would improve the situation in future. We really appreciate any feedback. You can report a new issues in https://github.com/vcpkg/vcpkg.github.io/issues.
