### ISSUE TITLE
[qt5-tools] Build failed on x64-windows-static

### ISSUE THREAD

**Issue by ohlig** [microsoft/vcpkg#37343]
### Operating system

win11

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
.\vcpkg.exe install qt5[all]:x64-windows-static
```

### Failure logs

PS E:\vcpkg> .\vcpkg.exe install qt5[all]:x64-windows-static
Computing installation plan...
The following packages will be built and installed:
    qt5[3d,activeqt,all,charts,connectivity,core,datavis3d,declarative,doc,essentials,extras,gamepad,graphicaleffects,imageformats,location,mqtt,multimedia,networkauth,purchasing,quickcontrols,quickcontrols2,remoteobjects,script,scxml,sensors,serialbus,serialport,speech,svg,tools,translations,virtualkeyboard,webchannel,webglplugin,websockets,webview,xmlpatterns]:x64-windows-static@5.15.12
  * qt5-script:x64-windows-static@5.15.12
  * qt5-scxml:x64-windows-static@5.15.12
  * qt5-sensors:x64-windows-static@5.15.12
  * qt5-serialbus:x64-windows-static@5.15.12
  * qt5-speech:x64-windows-static@5.15.12
  * qt5-tools:x64-windows-static@5.15.12
  * qt5-translations:x64-windows-static@5.15.12
  * qt5-virtualkeyboard:x64-windows-static@5.15.12
  * qt5-webchannel:x64-windows-static@5.15.12
  * qt5-webglplugin:x64-windows-static@5.15.12
  * qt5-websockets:x64-windows-static@5.15.12
  * qt5-webview:x64-windows-static@5.15.12
  * qt5-winextras[core,declarative]:x64-windows-static@5.15.12
  * qt5-xmlpatterns:x64-windows-static@5.15.12
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows-static...
-- Automatically setting %HTTP(S)_PROXY% environment variables to "127.0.0.1:7897".
Restored 0 package(s) from C:\Users\LIB\AppData\Local\vcpkg\archives in 1.41 ms. Use --debug to see more details.
Installing 1/15 qt5-tools:x64-windows-static@5.15.12...
Building qt5-tools:x64-windows-static@5.15.12...
-- Using cached qttools-everywhere-opensource-src-5.15.12.tar.xz.
-- Cleaning sources at E:/vcpkg/buildtrees/qt5-tools/src/5.15.12-266ce3aca4.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/vcpkg/downloads/qttools-everywhere-opensource-src-5.15.12.tar.xz
-- Applying patch fix-pkgconfig-qt5uiplugin-not-found.patch
-- Using source at E:/vcpkg/buildtrees/qt5-tools/src/5.15.12-266ce3aca4.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows-static
-- Using cached msys2-mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst.
-- Using msys root at E:/vcpkg/downloads/tools/msys2/fdbea3694fb5c0d4
-- Configuring x64-windows-static-rel
-- Configuring x64-windows-static-rel done
-- Configuring x64-windows-static-dbg
-- Configuring x64-windows-static-dbg done
-- Package build-x64-windows-static-dbg
CMake Warning at scripts/cmake/vcpkg_execute_build_process.cmake:65 (message):
  Please ensure your system has sufficient memory.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_qmake.cmake:3 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_build_qmake.cmake:76 (z_run_jom_build)
  installed/x64-windows-static/share/qt5/qt_build_submodule.cmake:11 (vcpkg_build_qmake)
  installed/x64-windows-static/share/qt5/qt_submodule_installation.cmake:9 (qt_build_submodule)
  ports/qt5-tools/portfile.cmake:3 (qt_submodule_installation)
  scripts/ports.cmake:175 (include)

-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: E:/vcpkg/downloads/tools/jom/jom-1_1_4/jom.exe -j 17
    Working Directory: E:/vcpkg/buildtrees/qt5-tools/x64-windows-static-dbg
    See logs for more information:
      E:\vcpkg\buildtrees\qt5-tools\package-build-x64-windows-static-dbg-out.log
      E:\vcpkg\buildtrees\qt5-tools\package-build-x64-windows-static-dbg-err.log
      E:\vcpkg\buildtrees\qt5-tools\package-build-x64-windows-static-dbg-out-1.log
      E:\vcpkg\buildtrees\qt5-tools\package-build-x64-windows-static-dbg-err-1.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_qmake.cmake:3 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_build_qmake.cmake:76 (z_run_jom_build)
  installed/x64-windows-static/share/qt5/qt_build_submodule.cmake:11 (vcpkg_build_qmake)
  installed/x64-windows-static/share/qt5/qt_submodule_installation.cmake:9 (qt_build_submodule)
  ports/qt5-tools/portfile.cmake:3 (qt_submodule_installation)
  scripts/ports.cmake:175 (include)

error: building qt5-tools:x64-windows-static failed with: BUILD_FAILED
Elapsed time to handle qt5-tools:x64-windows-static: 1.5 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qt5-tools
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[qt5-tools]+Build+error+on+x64-windows-static&body=Copy+issue+body+from+E%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by autoantwort** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report a build failure.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
