### ISSUE TITLE
[boost-modular-build-helper] Add boost build customizations without having to create overlay port

### ISSUE THREAD

**Issue by elcombs** [microsoft/vcpkg#37341]
### Is your feature request related to a problem? Please describe.

This request is similar to [Issue 32306](https://github.com/microsoft/vcpkg/issues/32306).  As a developer, I would like to add my own configuration options to the b2 command.  I would like to do this without having to create an overlay port.  

### Proposed solution

Remove this line from ports/boost-modular-build-helper/CMakeLists.txt,

`set(B2_OPTIONS "")`

If this line is removed, then a developer could initialize B2_OPTIONS in their VCPKG_CHAINLOAD_TOOLCHAIN_FILE file.  If B2_OPTIONS is not set by the developer then the first APPEND to the list in boost-modular-build-helper/CMakeLists.txt will create it.  Unless I am missing something, I do not see any reason to force B2_OPTIONS to be initialized in boost-modular-build-helper/CMakeLists.txt.

### Describe alternatives you've considered

Create overlay port(s) for each boost port that needs custom configuration option(s) or create an overlay port for boost-modular-build-helper with the change described above.

### Additional context

This does not allow the developer to change any boost configuration options that are specified in a b2-options.cmake file.  This would require an overlay port.

**Comment by elcombs** [comment]
It might also be worthwhile replacing

`set(B2_OPTIONS "")`

with

`list(REMOVE_DUPLICATES B2_OPTIONS)`

because it seems that the VCPKG_CHAINLOAD_TOOLCHAIN_FILE may get loaded more than once in some cases.

**Comment by MonicaLiu0311** [comment]
@elcombs 

Please try #37414 to see if it solves the issue.
