### ISSUE TITLE
Make it possible add extra properties to upload URL with binary http provider

### ISSUE THREAD

**Issue by tsondergaard** [microsoft/vcpkg#37361]
**Describe the bug**
I would like to use the HTTP binary caching provider. When uploading artifacts I want to attach extra properties as metadata. I'm using a generic repo in JFro Artifactory and I can provide metadata when uploading artifacts by 

```
VCPKG_BINARY_SOURCES="clear;http,https://artifactory.company.com/artifactory/generic-temp-local/{name}/{version}/{triplet}/{sha}`;vcs.revision=...`;vcs.branch=...`;vcs.url=...`;build.timestamp=...`;build.name=...`;build.number=...,readwrite,Authorization: Basic ****,
```

The problem is that the build job that runs with `;vcs.revision=...;vcs.branch=...;vcs.url=...;build.timestamp=...;build.name=...;build.number=...` appended to the URL will never actually hit anything when *retrieving* from the cache as these properties are also required to match from downloading from artifactory, *if* they are specified and several of them would typically be different such as e.g `build.timestamp`.

A possible solution would be to allow the specification of a separate upload URL.

**Comment by autoantwort** [comment]
You could add a seperate binary source that is readonly without the metadata
