### ISSUE TITLE
[python3] Do not remove dll files from bin directory

### ISSUE THREAD

**Issue by robtor-de** [microsoft/vcpkg#37374]
### Is your feature request related to a problem? Please describe.

Currently the portfile removes all[ python build files from the /bin directory ](https://github.com/microsoft/vcpkg/blob/0719a71389654b88d827501d88e37e58ea8cbd70/ports/python3/portfile.cmake#L296) and thus the [dependency resolve mechanism](https://github.com/microsoft/vcpkg/blob/619b29470031781e0c787eff32dbc7d8568bdbe6/scripts/buildsystems/vcpkg.cmake#L360:L408) cannot copy the python*.dll into the same directory the binaries are in (e.g. in unittests)
The [script](https://github.com/microsoft/vcpkg/blob/619b29470031781e0c787eff32dbc7d8568bdbe6/scripts/buildsystems/msbuild/applocal.ps1) seems to search only in the /bin directory

### Proposed solution

Copy the python .dll files into the `bin/` directory after cleaning unneeded files

```CMake
    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin")
    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/bin")
    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")
    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/include/python${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}d")
    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/share/${PORT}/man1")
    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/tools/${PORT}/bin")
    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/tools/${PORT}/debug")

    # When building with mingw, copy the dll files to the bin/ directory so that the vcpkg depdendency searching mechanism can copy them
    if (VCPKG_TARGET_IS_MINGW)
        file(GLOB_RECURSE PYTHON_COPY_FILES LIST_DIRECTORIES true
                "${CURRENT_PACKAGES_DIR}/tools/${PORT}/*.dll")
        file(COPY ${PYTHON_COPY_FILES} DESTINATION "${CURRENT_PACKAGES_DIR}/bin/")
    endif ()
```

### Describe alternatives you've considered

Modify or patch the dependency search mechanism to search in tools/python3 directory as well when building python for windows

**Comment by Neumann-A** [comment]
> Modify or patch the dependency search mechanism to search in tools/python3 directory as well when building python for windows

That is #31279

**Comment by robtor-de** [comment]
I don't understand what a difference this should make, I just need the python dll file in the /bin directory in addition to the tools directory because the [dependency resolver of vcpkg ](https://github.com/microsoft/vcpkg/blob/619b29470031781e0c787eff32dbc7d8568bdbe6/scripts/buildsystems/vcpkg.cmake#L360:L408) does not search in the tools directory for this dll but only in `bin/`

**Comment by dg0yt** [comment]
> My proposed solution above wouldn't work because there aren't any files in /bin to be removed anyway.

The proposed solution touches code for `!windows`, so it doesn't deal with DLLs.

**Comment by robtor-de** [comment]
I think my proposed solution is rather a dirty workaround, maybe the real problem should be solved within the dependency resolving mechanism to consider the tool directories as well. So the script called in this line
[](https://github.com/microsoft/vcpkg/blob/619b29470031781e0c787eff32dbc7d8568bdbe6/scripts/buildsystems/vcpkg.cmake#L370)
might need a workaround for python3 or the overall mechanism must be adjusted
