### ISSUE TITLE
[osg] not handling optional dependencies correctly. 

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#37372]
there is no `CMAKE_DISABLE_FIND_PACKAGE_X` or another way to handle optional deps. 
Using `CMAKE_REQUIRE_FIND_PACKAGE_X` is simply not enough to ensure the integrity of the generated binary artifact since stuff can  already be installed and thus be picked up.

**Comment by dg0yt** [comment]
I still want https://github.com/microsoft/vcpkg/pull/27950.
