### ISSUE TITLE
Unnecessary requirement for VCPKG_TARGET_ARCHITECTURE in ios triplets

### ISSUE THREAD

**Issue by mntt-SSE** [microsoft/vcpkg#37388]
**Describe the bug**
It seems that `VCPKG_TARGET_ARCHITECTURE` has to be specified for ios builds, even when `VCPKG_OSX_ARCHITECTURES` and `VCPKG_OSX_SYSROOT` are specified. I don't think this should be the case.

**Environment**
- OS: MacOS Sonoma 14.0
- Compiler: XCode 15.2

**To Reproduce**
1. Create a triplet file containing the following:
```cmake
set(VCPKG_OSX_ARCHITECTURES "arm64;x86_64")
set(VCPKG_OSX_SYSROOT iphoneos)

set(VCPKG_CMAKE_SYSTEM_NAME iOS)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CRT_LINKAGE static)
```
2. vcpkg install lz4

**Expected behavior**
The package is installed successfully

**Failure logs**
This is in the config-<triplet>-rel-err.log:
```
CMake Error at /usr/local/var/jenkins/vcpkg/scripts/toolchains/ios.cmake:27 (message):
  Unknown VCPKG_TARGET_ARCHITECTURE value provided for triplet <triplet>:
```

**Comment by JonLiu1993** [comment]
The function `VCPKG_OSX_ARCHITECTURES` can only set one variable. How do you set two variables?
````
set(VCPKG_OSX_ARCHITECTURES "arm64;x86_64")
````

**Comment by mntt-SSE** [comment]
@JonLiu1993 
I thought it reflected the [CMAKE_OSX_ARCHITECTURES](https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_ARCHITECTURES.html) variable? It's for creating "fat" binaries, made to run both on arm64 (M1/M2/iPhone), and x86_64 (older Macs).

**Comment by dg0yt** [comment]
`VCPKG_TARGET_ARCHITECTURE` is the general guiding variable, used for all default behaviors.
There are many ports which don't support universal binaries, e.g. openssl.
And there is no CI coverage here for universal binaries.

BTW there is also no way to express universal binary support in manifests.

**Comment by mntt-SSE** [comment]
Ah, I see! I think I got confused because setting only `VCPKG_OSX_ARCHITECTURES` "works" for Darwin. This triplet works for me, although I guess it is actually some kind of undefined behavior.

```cmake
set(VCPKG_OSX_ARCHITECTURES "arm64;x86_64")
set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_OSX_DEPLOYMENT_TARGET 12.0)
```

I'll close this ticket then. Thanks for answering, I'll try to find a way to work around it :)
