### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by Rick-960123** [microsoft/vcpkg#37420]
### Operating system

Windows10

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
.\vcpkg install zlib:x64-windows --debug
```

### Failure logs

[DEBUG] Trying to hash D:\Program Files\vcpkg\ports\zlib\vcpkg.json
[DEBUG] D:\Program Files\vcpkg\ports\zlib\vcpkg.json has hash 8ad7072167e1bf56d2ed531e43ecc95026d5b305ed0393140d5ec78f5c6b6c00
[DEBUG] <abientries for zlib:x64-windows>
[DEBUG]   0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch|750b9542cb55e6328cca01d3ca997f1373b9530afa95e04213168676936e7bfa
[DEBUG]   0002-build-static-or-shared-not-both.patch|dd4945e8af55d9feb65af706cb0254a6925dc4ac12789586c0d28acf323ad075
[DEBUG]   0003-android-and-mingw-fixes.patch|63e62c9bae3952b8cca832e01aa96ef3b2696b21976c5031d6d6d79937d8d54c
[DEBUG]   cmake|3.27.1
[DEBUG]   features|core
[DEBUG]   portfile.cmake|b14cee469c2da06e036e63293c0b6e6509924462e9b341b317986df46b281695
[DEBUG]   ports.cmake|0500e9e2422fe0084c99bdd0c9de4c7069b76da14c8b58228a7e95ebac43058a
[DEBUG]   post_build_checks|2
[DEBUG]   powershell|7.4.1
[DEBUG]   triplet|x64-windows
[DEBUG]   triplet_abi|4556164a2cd3dd6f4742101eabb46def7e71b6e5856faa88e5d005aac12a803c-e36df1c7f50ab25f9c182fa927d06c19ae082e0d599f132b3f655784b49e4b33-3361a17d8afbd07b0f5c7f4dac4bd892b23a29d3
[DEBUG]   usage|be22662327df993eebc437495add75acb365ab18d37c7e5de735d4ea4f5d3083
[DEBUG]   vcpkg-cmake|ec4adb82e6fea2c00603e342f7766d22e588f9ce2bff16a56d4cd02e0126bf93
[DEBUG]   vcpkg-cmake-wrapper.cmake|5d49ef2ee6448479c2aad0e5f732e2676eaba0411860f9bebabe6002d66f57d1
[DEBUG]   vcpkg.json|8ad7072167e1bf56d2ed531e43ecc95026d5b305ed0393140d5ec78f5c6b6c00
[DEBUG]   vcpkg_copy_pdbs|d57e4f196c82dc562a9968c6155073094513c31e2de475694143d3aa47954b1c
[DEBUG]   vcpkg_fixup_pkgconfig|904e67c46ecbb67379911bc1d7222855c0cbfcf1129bf47783858bcf0cc44970
[DEBUG]   vcpkg_from_git|96ed81968f76354c00096dd8cd4e63c6a235fa969334a11ab18d11c0c512ff58
[DEBUG]   vcpkg_from_github|b743742296a114ea1b18ae99672e02f142c4eb2bef7f57d36c038bedbfb0502f
[DEBUG]   vcpkg_replace_string|d43c8699ce27e25d47367c970d1c546f6bc36b6df8fb0be0c3986eb5830bd4f1
[DEBUG] </abientries>
[DEBUG] Default binary cache path is: C:\Users\FK-Gaopengwei\AppData\Local\vcpkg\archives
Restored 0 package(s) from C:\Users\FK-Gaopengwei\AppData\Local\vcpkg\archives in 125 us. Use --debug to see more details.
Installing 1/2 vcpkg-cmake:x64-windows@2023-05-04...
Building vcpkg-cmake:x64-windows@2023-05-04...
[DEBUG] Detecting host with IsWow64Process2
[DEBUG] 1007: CreateProcessW("D:\Program Files\vcpkg\downloads\tools\cmake-3.27.1-windows\cmake-3.27.1-windows-i386/bin/cmake.exe" -DALL_FEATURES= "-DCURRENT_PORT_DIR=D:/Program Files/vcpkg/ports/vcpkg-cmake" -D_HOST_TRIPLET=x64-windows -DFEATURES=core -DPORT=vcpkg-cmake -DVERSION=2023-05-04 -DVCPKG_USE_HEAD_VERSION=0 -D_VCPKG_DOWNLOAD_TOOL=BUILT_IN -D_VCPKG_EDITABLE=0 -D_VCPKG_NO_DOWNLOADS=0 "-DZ_VCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/Program Files/vcpkg/scripts/toolchains/windows.cmake" -DCMD=BUILD "-DDOWNLOADS=D:/Program Files/vcpkg/downloads" -DTARGET_TRIPLET=x64-windows "-DTARGET_TRIPLET_FILE=D:/Program Files/vcpkg/triplets/x64-windows.cmake" -DVCPKG_BASE_VERSION=2024-02-07 -DVCPKG_CONCURRENCY=17 -DVCPKG_PLATFORM_TOOLSET=v142 "-DGIT=C:/Program Files/Git/cmd/git.exe" "-DVCPKG_ROOT_DIR=D:/Program Files/vcpkg" "-DPACKAGES_DIR=D:/Program Files/vcpkg/packages" "-DBUILDTREES_DIR=D:/Program Files/vcpkg/buildtrees" "-D_VCPKG_INSTALLED_DIR=D:/Program Files/vcpkg/installed" "-DDOWNLOADS=D:/Program Files/vcpkg/downloads" -DVCPKG_MANIFEST_INSTALL=OFF -P "D:\Program Files\vcpkg\scripts\ports.cmake")
-- Installing: D:/Program Files/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake
-- Installing: D:/Program Files/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake
-- Installing: D:/Program Files/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake
-- Installing: D:/Program Files/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg-port-config.cmake
-- Installing: D:/Program Files/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/copyright
[DEBUG] 1007: cmd_execute_and_stream_data() returned 0 after   174668 us
error: Failed to convert to UTF-8: invalid code unit
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\unicode.cpp(259):
[DEBUG] Time in subprocesses: 9700307us
[DEBUG] Time in parsing JSON: 26us
[DEBUG] Time in JSON reader: 94us
[DEBUG] Time in filesystem: 5863us
[DEBUG] Time in loading ports: 754us
[DEBUG] Exiting after 10 s (9936698us)

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please make sure you have set utf-8 locale in Windows settings, see https://www.cnblogs.com/walker-world/p/9548852.html.

![image](https://github.com/microsoft/vcpkg/assets/94091114/a82b84a7-7566-494d-accb-980259ac1851)

**Comment by Rick-960123** [comment]
[DEBUG] Default binary cache path is: C:\Users\FK-Gaopengwei\AppData\Local\vcpkg\archives
Restored 0 package(s) from C:\Users\FK-Gaopengwei\AppData\Local\vcpkg\archives in 97.2 us. Use --debug to see more details.
Installing 1/2 vcpkg-cmake:x64-windows@2023-05-04...
Building vcpkg-cmake:x64-windows@2023-05-04...
[DEBUG] Detecting host with IsWow64Process2
[DEBUG] 1007: CreateProcessW("D:\Program Files\vcpkg\downloads\tools\cmake-3.27.1-windows\cmake-3.27.1-windows-i386/bin/cmake.exe" -DALL_FEATURES= "-DCURRENT_PORT_DIR=D:/Program Files/vcpkg/ports/vcpkg-cmake" -D_HOST_TRIPLET=x64-windows -DFEATURES=core -DPORT=vcpkg-cmake -DVERSION=2023-05-04 -DVCPKG_USE_HEAD_VERSION=0 -D_VCPKG_DOWNLOAD_TOOL=BUILT_IN -D_VCPKG_EDITABLE=0 -D_VCPKG_NO_DOWNLOADS=0 "-DZ_VCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/Program Files/vcpkg/scripts/toolchains/windows.cmake" -DCMD=BUILD "-DDOWNLOADS=D:/Program Files/vcpkg/downloads" -DTARGET_TRIPLET=x64-windows "-DTARGET_TRIPLET_FILE=D:/Program Files/vcpkg/triplets/x64-windows.cmake" -DVCPKG_BASE_VERSION=2024-02-07 -DVCPKG_CONCURRENCY=17 -DVCPKG_PLATFORM_TOOLSET=v142 "-DGIT=C:/Program Files/Git/cmd/git.exe" "-DVCPKG_ROOT_DIR=D:/Program Files/vcpkg" "-DPACKAGES_DIR=D:/Program Files/vcpkg/packages" "-DBUILDTREES_DIR=D:/Program Files/vcpkg/buildtrees" "-D_VCPKG_INSTALLED_DIR=D:/Program Files/vcpkg/installed" "-DDOWNLOADS=D:/Program Files/vcpkg/downloads" -DVCPKG_MANIFEST_INSTALL=OFF -P "D:\Program Files\vcpkg\scripts\ports.cmake")
-- Installing: D:/Program Files/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake
-- Installing: D:/Program Files/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake
-- Installing: D:/Program Files/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake
-- Installing: D:/Program Files/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg-port-config.cmake
-- Installing: D:/Program Files/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/copyright
[DEBUG] 1007: cmd_execute_and_stream_data() returned 0 after   133825 us
error: Failed to convert to UTF-8: found start code unit in continue position
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\unicode.cpp(259):
[DEBUG] Time in subprocesses: 6993403us
[DEBUG] Time in parsing JSON: 24us
[DEBUG] Time in JSON reader: 87us
[DEBUG] Time in filesystem: 4847us
[DEBUG] Time in loading ports: 647us
[DEBUG] Exiting after 7.2 s (7160988us)
PS D:\Program Files\vcpkg> chcp
Active code page: 65001
PS D:\Program Files\vcpkg>

**Comment by Rick-960123** [comment]
> Thanks for posting this issue. Please make sure you have set utf-8 locale in Windows settings, see https://www.cnblogs.com/walker-world/p/9548852.html.
> 
> ![image](https://private-user-images.githubusercontent.com/94091114/312670630-a82b84a7-7566-494d-accb-980259ac1851.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODIxOTAsIm5iZiI6MTcxMDM4MTg5MCwicGF0aCI6Ii85NDA5MTExNC8zMTI2NzA2MzAtYTgyYjg0YTctNzU2Ni00OTRkLWFjY2ItOTgwMjU5YWMxODUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDAyMDQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MTlkN2RiYzk2ZDhmZjA3M2FhYjE1MDBmMWIyNjdkNjc5YzYxZDUxYmFiMTYxNDJlZTBkNjliOWMyNTliYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Or25DqjpdKq46PBq4ER8CvXXRldYMTp2U4iBiOiisE0)

[DEBUG] Default binary cache path is: C:\Users\FK-Gaopengwei\AppData\Local\vcpkg\archives
Restored 0 package(s) from C:\Users\FK-Gaopengwei\AppData\Local\vcpkg\archives in 97.2 us. Use --debug to see more details.
Installing 1/2 vcpkg-cmake:x64-windows@2023-05-04...
Building vcpkg-cmake:x64-windows@2023-05-04...
[DEBUG] Detecting host with IsWow64Process2
[DEBUG] 1007: CreateProcessW("D:\Program Files\vcpkg\downloads\tools\cmake-3.27.1-windows\cmake-3.27.1-windows-i386/bin/cmake.exe" -DALL_FEATURES= "-DCURRENT_PORT_DIR=D:/Program Files/vcpkg/ports/vcpkg-cmake" -D_HOST_TRIPLET=x64-windows -DFEATURES=core -DPORT=vcpkg-cmake -DVERSION=2023-05-04 -DVCPKG_USE_HEAD_VERSION=0 -D_VCPKG_DOWNLOAD_TOOL=BUILT_IN -D_VCPKG_EDITABLE=0 -D_VCPKG_NO_DOWNLOADS=0 "-DZ_VCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/Program Files/vcpkg/scripts/toolchains/windows.cmake" -DCMD=BUILD "-DDOWNLOADS=D:/Program Files/vcpkg/downloads" -DTARGET_TRIPLET=x64-windows "-DTARGET_TRIPLET_FILE=D:/Program Files/vcpkg/triplets/x64-windows.cmake" -DVCPKG_BASE_VERSION=2024-02-07 -DVCPKG_CONCURRENCY=17 -DVCPKG_PLATFORM_TOOLSET=v142 "-DGIT=C:/Program Files/Git/cmd/git.exe" "-DVCPKG_ROOT_DIR=D:/Program Files/vcpkg" "-DPACKAGES_DIR=D:/Program Files/vcpkg/packages" "-DBUILDTREES_DIR=D:/Program Files/vcpkg/buildtrees" "-D_VCPKG_INSTALLED_DIR=D:/Program Files/vcpkg/installed" "-DDOWNLOADS=D:/Program Files/vcpkg/downloads" -DVCPKG_MANIFEST_INSTALL=OFF -P "D:\Program Files\vcpkg\scripts\ports.cmake")
-- Installing: D:/Program Files/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake
-- Installing: D:/Program Files/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake
-- Installing: D:/Program Files/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake
-- Installing: D:/Program Files/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg-port-config.cmake
-- Installing: D:/Program Files/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/copyright
[DEBUG] 1007: cmd_execute_and_stream_data() returned 0 after   133825 us
error: Failed to convert to UTF-8: found start code unit in continue position
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\unicode.cpp(259):
[DEBUG] Time in subprocesses: 6993403us
[DEBUG] Time in parsing JSON: 24us
[DEBUG] Time in JSON reader: 87us
[DEBUG] Time in filesystem: 4847us
[DEBUG] Time in loading ports: 647us
[DEBUG] Exiting after 7.2 s (7160988us)
PS D:\Program Files\vcpkg> chcp
Active code page: 65001
PS D:\Program Files\vcpkg>

**Comment by Rick-960123** [comment]
How can I find the file and remove it?

**Comment by Rick-960123** [comment]
> Thanks for posting this issue. Please make sure you have set utf-8 locale in Windows settings, see https://www.cnblogs.com/walker-world/p/9548852.html.
> 
> ![image](https://private-user-images.githubusercontent.com/94091114/312670630-a82b84a7-7566-494d-accb-980259ac1851.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODMyMzcsIm5iZiI6MTcxMDM4MjkzNywicGF0aCI6Ii85NDA5MTExNC8zMTI2NzA2MzAtYTgyYjg0YTctNzU2Ni00OTRkLWFjY2ItOTgwMjU5YWMxODUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDAyMjIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlOWZiNjAyYmYwMWFhMzAxM2YwN2ExMTA4MGE1YmU3ZmUzODhkZmM1NDM1ZjE3ZjJlMzNiMTNkMDNlZmFiNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1FmDR3_ZYdWw4HgDiTPgYw01ZDVpi40gE9YCpIO1vSU)

I have seted, but the problem still exist.

**Comment by LilyWangLL** [comment]
Maybe the failed reason is the sapce in your VCPKG_ROOT_PATH _D:/Program Files_, could you please clone vcpkg to a no-space path and rebuild `zlib`?

**Comment by Rick-960123** [comment]
> Maybe the failed reason is the sapce in your VCPKG_ROOT_PATH _D:/Program Files_, could you please clone vcpkg to a no-space path and rebuild `zlib`?

PS C:\Users\FK-Gaopengwei> vcpkg install boost-interprocess:x64-windows --debug
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from D:\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: D:\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
[DEBUG] Using scripts-root: D:\vcpkg\scripts
[DEBUG] Using builtin-ports: D:\vcpkg\ports
[DEBUG] Using installed-root: D:\vcpkg\installed
[DEBUG] Using buildtrees-root: D:\vcpkg\buildtrees
[DEBUG] Using packages-root: D:\vcpkg\packages
[DEBUG] Using vcpkg-root: D:\vcpkg
[DEBUG] Using scripts-root: D:\vcpkg\scripts
[DEBUG] Using builtin-registry: D:\vcpkg\versions
[DEBUG] Using downloads-root: D:\vcpkg\downloads
[DEBUG] Detecting host with IsWow64Process2
[DEBUG] Detecting host with IsWow64Process2
Computing installation plan...
error: Failed to convert to UTF-8: invalid code unit
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\unicode.cpp(259):
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 0us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 2156us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 58.2 ms (7318us)

**Comment by Rick-960123** [comment]
Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
CMake Error at scripts/cmake/z_vcpkg_apply_patches.cmake:34 (message):
  Applying patch failed: Checking patch zconf.h.cmakein...

  error: while searching for:

  #endif



  #ifdef HAVE_UNISTD_H /* may be set to #if 1 by ./configure */

  # define Z_HAVE_UNISTD_H

  #endif



  #ifdef HAVE_STDARG_H /* may be set to #if 1 by ./configure */

  # define Z_HAVE_STDARG_H

  #endif



  #ifdef STDC



  error: patch failed: zconf.h.cmakein:434

  error: zconf.h.cmakein: patch does not apply

  Checking patch zconf.h.in...

  error: while searching for:

  #endif



  #ifdef HAVE_UNISTD_H /* may be set to #if 1 by ./configure */

  # define Z_HAVE_UNISTD_H

  #endif



  #ifdef HAVE_STDARG_H /* may be set to #if 1 by ./configure */

  # define Z_HAVE_STDARG_H

  #endif



  #ifdef STDC



  error: patch failed: zconf.h.in:432

  error: zconf.h.in: patch does not apply

Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive.cmake:147 (z_vcpkg_apply_patches)
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:8 (vcpkg_extract_source_archive)
  scripts/cmake/vcpkg_from_github.cmake:113 (vcpkg_extract_source_archive_ex)
  ports/zlib/portfile.cmake:2 (vcpkg_from_github)
  scripts/ports.cmake:175 (include)


[DEBUG] 1007: cmd_execute_and_stream_data() returned 1 after   863314 us
error: 生成 zlib:x64-windows 失败，结果为: BUILD_FAILED
处理 zlib:x64-windows 所用时间: 868 ms
[DEBUG] Detecting host with IsWow64Process2
[DEBUG] 1008: CreateProcessW("C:\Program Files\Git\cmd\git.exe" "--git-dir=D:\vcpkg\.git" "--work-tree=D:\vcpkg\.git" -c core.autocrlf=false show "--pretty=format:%h %cd (%cr)" -s --date=short HEAD)
[DEBUG] 1008: cmd_execute_and_stream_data() returned 0 after    46096 us
请确保使用具有“git pull” 和 “vcpkg update”的最新端口文件。
然后，在以下位置查看已知问题:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+zlib
可在以下位置提交新问题:
  https://github.com/microsoft/vcpkg/issues/new?title=[zlib]+Build+error+on+x64-windows&body=Copy+issue+body+from+D%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

[DEBUG] D:\a\_work\1\s\src\vcpkg\commands.install.cpp(603):
[DEBUG] Time in subprocesses: 8457519us
[DEBUG] Time in parsing JSON: 13549us
[DEBUG] Time in JSON reader: 431us
[DEBUG] Time in filesystem: 13234us
[DEBUG] Time in loading ports: 9504us
[DEBUG] Exiting after 8.7 s (8578262us)

**Comment by LilyWangLL** [comment]
You can check whether file `D:\a_work\1\s\src\vcpkg\base\unicode.cpp` exists and delete it, then try to install.

**Comment by Rick-960123** [comment]
> 您可以检查文件是否`D:\a_work\1\s\src\vcpkg\base\unicode.cpp`存在并将其删除，然后尝试安装。

The path does not exsit.

**Comment by dg0yt** [comment]
> You can check whether file `D:\a_work\1\s\src\vcpkg\base\unicode.cpp` exists and delete it, then try to install.

This is the file path of the vcpkg tool source code unit which reports the encoding error... 
It is not expected ot exist on the user system.
