### ISSUE TITLE
[gmp] Build error on x64-windows

### ISSUE THREAD

**Issue by mxlik-ali** [microsoft/vcpkg#37431]
please help me it shows some sort of error i cant understand what does it says, how much i understood is clang is already present and it couldnt extract, how do i solve it, its very imp as im trying to make a project and deadline is near

Copy issue body from C:/Users/Mohommad Ali/vcpkg/installed/vcpkg/issue_body.md
Microsoft Windows [Version 10.0.22621.3296]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Mohommad Ali>cd vcpkg

C:\Users\Mohommad Ali\vcpkg>.\vcpkg install colmap[cuda,tests]:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * cgal:x64-windows@5.6#1
    colmap[core,cuda,tests]:x64-windows@2023-10-01
  * cuda:x64-windows@10.1#13
  * double-conversion:x64-windows@3.3.0
  * egl-registry:x64-windows@2024-01-25
  * flann:x64-windows@2019-04-07#7
  * freeglut:x64-windows@3.4.0#1
  * freeimage:x64-windows@3.18.0#25
  * freetype[brotli,bzip2,core,png,zlib]:x64-windows@2.13.2
  * glew:x64-windows@2.2.0#3
  * gmp:x64-windows@6.3.0
  * gtest:x64-windows@1.14.0
  * harfbuzz[core,freetype]:x64-windows@8.3.0#3
  * imath:x64-windows@3.1.11
  * jasper[core,default-features,opengl]:x64-windows@4.2.1
  * jxrlib:x64-windows@2019.10.9#6
  * lcms:x64-windows@2.14
  * libdeflate[compression,core,decompression,gzip,zlib]:x64-windows@1.19#1
  * libjpeg-turbo:x64-windows@3.0.2
  * libpng:x64-windows@1.6.43
  * libraw:x64-windows@0.21.2
  * libwebp[core,libwebpmux,nearlossless,simd,unicode]:x64-windows@1.3.2
  * lz4:x64-windows@1.9.4#1
  * mpfr:x64-windows@4.2.1
  * openexr:x64-windows@3.2.3
  * opengl:x64-windows@2022-12-04#3
  * opengl-registry:x64-windows@2024-02-10#1
  * openjpeg:x64-windows@2.5.2
  * openssl:x64-windows@3.2.1
  * pcre2[core,jit,platform-default-features]:x64-windows@10.42#2
  * pkgconf:x64-windows@2.1.0
  * qt5-base:x64-windows@5.15.12#2
  * sqlite3[core,json1]:x64-windows@3.45.1#1
  * tiff[core,jpeg,lzma,zip]:x64-windows@4.6.0#4
  * vcpkg-pkgconfig-get-modules:x64-windows@2023-09-06
  * vcpkg-tool-meson:x64-windows@1.3.2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\Mohommad Ali\AppData\Local\vcpkg\archives in 6.45 ms. Use --debug to see more details.
Installing 1/36 gmp:x64-windows@6.3.0...
Building gmp:x64-windows@6.3.0...
-- Using cached gmp-6.3.0.tar.xz.
-- Cleaning sources at C:/Users/Mohommad Ali/vcpkg/buildtrees/gmp/src/v6.3.0-036e54f1a3.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Mohommad Ali/vcpkg/downloads/gmp-6.3.0.tar.xz
-- Applying patch asmflags.patch
-- Applying patch cross-tools.patch
-- Applying patch subdirs.patch
-- Applying patch msvc_symbol.patch
-- Applying patch arm64-coff.patch
-- Using source at C:/Users/Mohommad Ali/vcpkg/buildtrees/gmp/src/v6.3.0-036e54f1a3.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Using cached LLVM-15.0.6-win64.7z.exe.
CMake Error at scripts/cmake/vcpkg_extract_archive.cmake:19 (message):
  C:/Users/Mohommad Ali/vcpkg/downloads/tools/clang/clang-15.0.6 was an
  extraction target, but it already exists.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:203 (vcpkg_extract_archive)
  ports/gmp/portfile.cmake:55 (vcpkg_find_acquire_program)
  scripts/ports.cmake:175 (include)

error: building gmp:x64-windows failed with: BUILD_FAILED
Elapsed time to handle gmp:x64-windows: 34 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+gmp
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[gmp]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2FUsers%2FMohommad%20Ali%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by MonicaLiu0311** [comment]
> CMake Error at scripts/cmake/vcpkg_extract_archive.cmake:19 (message):
> C:/Users/Mohommad Ali/vcpkg/downloads/tools/clang/clang-15.0.6 was an
> extraction target, but it already exists.

Please remove `vcpkg/downloads/clang*` and `vcpkg/downloads/tools/clang*` and try again.

**Comment by mxlik-ali** [comment]
there is no vcpkg/downloads/clang in the dir
