### ISSUE TITLE
[sfml] Build error on x64-linux

### ISSUE THREAD

**Issue by logeshwaranmcw** [microsoft/vcpkg#37432]
Copy issue body from /home/mcw/vcpkg/installed/vcpkg/issue_body.mdThese can be installed on Ubuntu systems via apt-get install libx11-dev libxrandr-dev libxcursor-dev libxi-dev libudev-dev libgl1-mesa-dev
-- Found external ninja('1.11.1').
-- Configuring x64-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/local/bin/ninja -v
    Working Directory: /home/mcw/vcpkg/buildtrees/sfml/x64-linux-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      /home/mcw/vcpkg/buildtrees/sfml/config-x64-linux-dbg-CMakeCache.txt.log
      /home/mcw/vcpkg/buildtrees/sfml/config-x64-linux-rel-CMakeCache.txt.log
      /home/mcw/vcpkg/buildtrees/sfml/config-x64-linux-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:252 (vcpkg_execute_required_process)
  ports/sfml/portfile.cmake:17 (vcpkg_cmake_configure)
  scripts/ports.cmake:175 (include)

error: building sfml:x64-linux failed with: BUILD_FAILED
Elapsed time to handle sfml:x64-linux: 1.6 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+sfml
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[sfml]+Build+error+on+x64-linux&body=Copy+issue+body+from+%2Fhome%2Fmcw%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by LilyWangLL** [comment]
Please see #30604 for how to report an issue.
Please provide the error log `/home/mcw/vcpkg/buildtrees/sfml/config-x64-linux-out.log`.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
