### ISSUE TITLE
[<Onnx] onnx.pb.h not created as part of build

### ISSUE THREAD

**Issue by DougRogers** [microsoft/vcpkg#37456]
### Operating system

Windows

### Compiler

Visual Studio 2022 Commuity

### Steps to reproduce the behavior

```Shell
vcpkg install onnx --recurse

In a program, include the file

#include <onnx/onnx_pb.h>
```

### Failure logs

Compile
```
Build started at 2:08 PM...
1>------ Build started: Project: test, Configuration: Debug x64 ------
1>main.cpp
1>c:\vcpkg\installed\x64-windows\include\onnx\onnx_pb.h(53,10): error C1083: Cannot open include file: 'onnx/onnx.pb.h': No such file or directory

```

Note that there are two '.' (periods) in the file name.

**Comment by jimwang118** [comment]
@DougRogers Please test whether PR https://github.com/microsoft/vcpkg/pull/37469 solves your issue.

**Comment by DougRogers** [comment]
I did 
```
git pull
vcpkg upgrade
vcpkg x-add-version --all
```

The file was not created.

**Comment by jimwang118** [comment]
> The file was not created.

What file was not created?

**Comment by dg0yt** [comment]
You would need to fetch and checkout that PR's branch before rebuilding the affected packages.
You don't need x-add-version,

**Comment by DougRogers** [comment]
@jimwang118 onnx.pb.h

**Comment by jimwang118** [comment]
> @jimwang118 onnx.pb.h

Are you looking for onnx_pd.h?

**Comment by dg0yt** [comment]
> > @jimwang118 onnx.pb.h
> 
> Are you looking for onnx_pd.h?

See first post, end of the error mesage...

**Comment by jimwang118** [comment]
> See first post, end of the error mesage...

Upstream has removed this header file from the code. https://github.com/onnx/onnx/blob/0bb2775098cb72c5619451f37cc0c8f9f335893f/docs/OnnxReleases.md#:~:text=p%20PYPI_PASSWORD.-,Source%20Distribution,-Make%20sure%20all

**Comment by dg0yt** [comment]
Upstream says that "none of the auto-generated header files"  shall be added to the "Source Distribution".
This has no relevance for the *installed header files* after the build. They are expected to be generated during the build.
(They also don't add the DLL to the Source Distribution...)
(The same pattern exists in other ports. I just dealt with `cld3`.)
