### ISSUE TITLE
[Nana] Freetype linker failure

### ISSUE THREAD

**Issue by Adobe-Android** [Microsoft/vcpkg#3745]
/usr/sbin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/8.1.1/../../../../lib/libXft.so: undefined reference to symbol 'FT_Done_Face'
/usr/lib/libfreetype.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/nana-test.dir/build.make:98: nana-test] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/nana-test.dir/all] Error 2
make: *** [Makefile:117: all] Error 2

It looks to be finding the system version rather than the one installed by vcpkg.

**Comment by Voskrese** [comment]
from which follows https://packages.debian.org/stretch/libxft2 the **libxft2** package is assembled without anything where there is no `FT_Done_Face`

**Comment by PhoebeHui** [comment]
@Adobe-Android, please try to install Nana with VCPKG latest revision, and please open a new issue if this is still a problem for you.

Nana installed successfully on Ubuntu 16.04
linux001@linuxtest01:~/vcpkg$ ./vcpkg install nana
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be built and installed:
  * dirent[core]:x64-linux
  * fontconfig[core]:x64-linux
    nana[core]:x64-linux
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: dirent:x64-linux
Building package dirent[core]:x64-linux...
-- Performing post-build validation
-- Performing post-build validation done
Building package dirent[core]:x64-linux... done
Installing package dirent[core]:x64-linux...
Installing package dirent[core]:x64-linux... done
Elapsed time for package dirent:x64-linux: 25.24 ms
Starting package 2/3: fontconfig:x64-linux
Building package fontconfig[core]:x64-linux...
-- Downloading https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.12.4.tar.gz...
-- Extracting source /home/linux001/vcpkg/downloads/fontconfig-2.12.4.tar.gz
-- Applying patch fcobjtypehash.patch
-- Using source at /home/linux001/vcpkg/buildtrees/fontconfig/src/2.12.4-3074630478
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Performing CMake integration test
-- Performing post-build validation
-- Performing post-build validation done
Building package fontconfig[core]:x64-linux... done
Installing package fontconfig[core]:x64-linux...
Installing package fontconfig[core]:x64-linux... done
Elapsed time for package fontconfig:x64-linux: 5.16 s
Starting package 3/3: nana:x64-linux
Building package nana[core]:x64-linux...
CMake Warning at ports/nana/portfile.cmake:7 (message):
  You will need to install Xorg dependencies to use nana:

  apt install libx11-dev libxft-dev

Call Stack (most recent call first):
  scripts/ports.cmake:71 (include)


-- Downloading https://github.com/cnjinhao/nana/archive/v1.6.2.tar.gz...
-- Extracting source /home/linux001/vcpkg/downloads/cnjinhao-nana-v1.6.2.tar.gz
-- Using source at /home/linux001/vcpkg/buildtrees/nana/src/v1.6.2-51b575c248
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package nana[core]:x64-linux... done
Installing package nana[core]:x64-linux...
Installing package nana[core]:x64-linux... done
Elapsed time for package nana:x64-linux: 49.87 s

Total elapsed time: 55.06 s

The package nana:x64-linux provides CMake targets:
    find_package(unofficial-nana CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::nana::nana)

**Comment by Adobe-Android** [comment]
Thanks @PhoebeHui. I'll give it a try.

**Comment by Adobe-Android** [comment]
Just tried it on Ubuntu 18.04 and I got the following issue.
vm@vm-VM:~/vcpkg$ ./vcpkg install nana
The following packages will be built and installed:
  * bzip2[core]:x64-linux
  * expat[core]:x64-linux
  * fontconfig[core]:x64-linux
  * freetype[core]:x64-linux
  * libjpeg-turbo[core]:x64-linux
  * libpng[core]:x64-linux
    nana[core]:x64-linux
  * zlib[core]:x64-linux
Additional packages (*) will be modified to complete this operation.
Starting package 1/8: zlib:x64-linux
Building package zlib[core]:x64-linux... 
-- Using cached /home/vm/vcpkg/downloads/zlib1211.tar.gz
-- Using source at /home/vm/vcpkg/buildtrees/zlib/src/1.2.11-f690224aeb
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Installing: /home/vm/vcpkg/packages/zlib_x64-linux/share/zlib/copyright
-- Performing CMake integration test
CMake Error at scripts/cmake/vcpkg_test_cmake.cmake:56 (message):
  CMake integration test failed; unable to find_package(ZLIB MODULE REQUIRED)
Call Stack (most recent call first):
  ports/zlib/portfile.cmake:50 (vcpkg_test_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package zlib:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x64-linux
  Vcpkg version: 2018.11.23-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by Adobe-Android** [comment]
I'll just add that this error appears to be the fault of #4817
