### ISSUE TITLE
Failed to build poco:x64-linux

### ISSUE THREAD

**Issue by ryukw7** [Microsoft/vcpkg#3746]
'cpspc.exe' should be 'cpspc' for linux vcpkg
---
Package: poco:x64-linux
Vcpkg version: 0.0.113-unknownhash
---
00:02:45.536 Starting package 5/5: poco:x64-linux
00:02:45.536 Building package poco[core]:x64-linux... 
00:02:45.540 -- CURRENT_INSTALLED_DIR=/var/lib/jenkins/workspace/vcpkg_build-poco/installed/x64-linux
00:02:45.540 -- DOWNLOADS=/var/lib/jenkins/workspace/vcpkg_build-poco/downloads
00:02:45.540 -- CURRENT_PACKAGES_DIR=/var/lib/jenkins/workspace/vcpkg_build-poco/packages/poco_x64-linux
00:02:45.540 -- CURRENT_BUILDTREES_DIR=/var/lib/jenkins/workspace/vcpkg_build-poco/buildtrees/poco
00:02:45.540 -- CURRENT_PORT_DIR=/var/lib/jenkins/workspace/vcpkg_build-poco/ports/poco
00:02:45.544 -- Downloading https://github.com/pocoproject/poco/archive/poco-1.9.0-release.tar.gz...
00:02:56.604 -- Downloading https://github.com/pocoproject/poco/archive/poco-1.9.0-release.tar.gz... OK
00:02:56.605 -- Testing integrity of downloaded file...
00:02:56.653 -- Testing integrity of downloaded file... OK
00:02:56.654 -- Extracting source /var/lib/jenkins/workspace/vcpkg_build-poco/downloads/pocoproject-poco-poco-1.9.0-release.tar.gz
00:02:56.901 -- Extracting done
00:02:56.901 -- Applying patch /var/lib/jenkins/workspace/vcpkg_build-poco/ports/poco/config_h.patch
00:02:56.904 -- Applying patch /var/lib/jenkins/workspace/vcpkg_build-poco/ports/poco/config_h.patch done
00:02:56.904 -- Applying patch /var/lib/jenkins/workspace/vcpkg_build-poco/ports/poco/find_pcre.patch
00:02:56.905 -- Applying patch /var/lib/jenkins/workspace/vcpkg_build-poco/ports/poco/find_pcre.patch done
00:02:56.905 -- Applying patch /var/lib/jenkins/workspace/vcpkg_build-poco/ports/poco/foundation-public-include-pcre.patch
00:02:56.907 -- Applying patch /var/lib/jenkins/workspace/vcpkg_build-poco/ports/poco/foundation-public-include-pcre.patch done
00:02:56.907 -- Applying patch /var/lib/jenkins/workspace/vcpkg_build-poco/ports/poco/fix-static-internal-pcre.patch
00:02:56.908 -- Applying patch /var/lib/jenkins/workspace/vcpkg_build-poco/ports/poco/fix-static-internal-pcre.patch done
00:02:56.909 -- Configuring x64-linux-dbg
00:02:58.187 -- Configuring x64-linux-dbg done
00:02:58.187 -- Configuring x64-linux-rel
00:02:59.398 -- Configuring x64-linux-rel done
00:02:59.398 -- Build x64-linux-dbg
00:04:09.796 -- Build x64-linux-dbg done
00:04:09.796 -- Build x64-linux-rel
00:05:22.254 -- Build x64-linux-rel done
00:05:22.254 CMake Error at ports/poco/portfile.cmake:49 (file):
00:05:22.254   file RENAME failed to rename
00:05:22.254 
00:05:22.254     /var/lib/jenkins/workspace/vcpkg_build-poco/packages/poco_x64-linux/bin/cpspc.exe
00:05:22.254 
00:05:22.254   to
00:05:22.254 
00:05:22.254     /var/lib/jenkins/workspace/vcpkg_build-poco/packages/poco_x64-linux/tools/cpspc.exe
00:05:22.254 
00:05:22.254   because: No such file or directory
00:05:22.254 
00:05:22.254 Call Stack (most recent call first):
00:05:22.254   scripts/ports.cmake:72 (include)
00:05:22.254 
00:05:22.254 
00:05:22.254 Error: Building package poco:x64-linux failed with: BUILD_FAILED

**Comment by Voskrese** [comment]
file RENAME failed to rename
/var/lib/jenkins/workspace/vcpkg_build-poco/packages/poco_x64-linux/tools/**cpspc.exe**

linux - EXE ? ;)

`ls /var/lib/jenkins/workspace/vcpkg_build-poco/packages/poco_x64-linux/tools/`
