### ISSUE TITLE
Bootstrap fails if Use/Machine Environment contains TMP Environment variables in different case

### ISSUE THREAD

**Issue by xgcssch** [microsoft/vcpkg#3748]
Environment:
Win 10 1709 / VS 15+VS 17

Steps to reproduce:
* Environment contains a `TMP`/`TEMP` (uppercase) variable in Machine Environment and a `tmp`/`temp` (lowercase) variable in User Environment.
* The machine tmp directories are not writable by the user
* the compile fails when building with `.\bootstrap-vcpkg.bat`.

Solution:
I found that in `cleanEnvironmentHelper.ps1' the line

    $nameSet = ($specialEnvironmentMap.Keys + $machineEnvironmentMap.Keys + $userEnvironmentMap.Keys) | Sort-Object | Select-Object -Unique

does a case sensitive "unique" and should be changed to

    $nameSet = ($specialEnvironmentMap.Keys + $machineEnvironmentMap.Keys + $userEnvironmentMap.Keys) | Sort-Object -Unique

which is caseinsensitive. After that change the build completes normal.

Best regards
Soenke Schau

**Comment by NancyLi1013** [comment]
Hi @xgcssch, thanks for posing this issue. I try to build it on my local and it can be built successfully. I can't reproduce it now. Please feel free to reopen this issue if this is still a problem for you.
