### ISSUE TITLE
im not able to go ahead im stuck here for hours

### ISSUE THREAD

**Issue by mxlik-ali** [microsoft/vcpkg#37484]
<img width="960" alt="Screenshot 2024-03-15 222929" src="https://github.com/microsoft/vcpkg/assets/97386337/0fbab69a-5ff5-4f84-9a74-6e7e9e673846">

**Comment by mxlik-ali** [comment]
it doesnt proceed ahead

**Comment by dg0yt** [comment]
It is unpacking LLVM. It takes time. Alternative: Install clang from Visual Studio.
