### ISSUE TITLE
libtorch build failure

### ISSUE THREAD

**Issue by dannypike** [microsoft/vcpkg#37482]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
I can only manage to build libtorch if I strip my machine clean of every vesion of CUDA and restart from scratch with 11.8.

Unfortunately, when I then try to use the libtorch, it tries (and fails) to load the version 12 DLLs at runtime.

Renaming cudart_11.dll etc to be cudart_12.dll doesn't solve the problem because it fails to find some of the exports that are in the v12 DLLs, but not the v11 ones. It also tries to load magma v12 (whatever that is for?)

The project seems to be a bit confused at the moment, about what version of everything it needs to build with and run with :)
```

### Failure logs

I can't put the logs here because it's a dialog box. It's the usual Windows dialog boxes about failing to load a DLL. About four of them (one for each v12 DLL that it can't find on my machine any more).

I can't give the log files of the failure to build with CUDA v12 because I've already spend hours stripping the machine down to get it to compile at all! Unfortunately, I can't remember what the original error was that sent me on this long journey.

**Comment by jimwang118** [comment]
Please provide the steps to reproduce the issue.

**Comment by dannypike** [comment]
Unfortunately, I cannot. It has taken me about six hours to get everything on my machine back to running with CUDA 11.8. I thought that I explained this, above. You To reinstall CUDA 12 in order to break it again would take too long; I don't want to do that. :)

Would it be possible to create some kind of verification-tool that checks what versions of libraries libtorch thinks it can "see" and whether they are compatible with each other? It is a very complex build and, because of the versioning issues that come with using a Python thing, it's easy to get in a mess,

That would have been a very helpful diagnostic tool.

Thanks.

**Comment by jimwang118** [comment]
In addition to installing `cuda`, you also need to install `cudnn`, and their two versions need to be matched. You can check whether the two software versions on your computer meet the requirements. Could you please provide the log of `libtorch` installation failure?

**Comment by dannypike** [comment]
Thanks for the quick response. I'll try that out when I next have a spare weekend.

I don't want to break the setup that I have right now, because it'll stop me from working. At the moment, libtorch is happy to build with CUDA 11.8.

**Comment by jimwang118** [comment]
Your issue is solved, I will close this issue. If you have other questions, please submit a new issue.
