### ISSUE TITLE
How to define custom make command [rocksdb]

### ISSUE THREAD

**Issue by edmBernard** [microsoft/vcpkg#3749]
I try to fix rocksdb build. 
But the configuration if we want shared library or static one is done in the make command : 
```
make static_lib
make shared_lib
```
so by default, `make` command alone try to build both. (the shared library fail on linux because zlib is static)

Is there a way to ask vcpkg to build only one target ? 

The other solution is to make my custom CMakelist file.

**Comment by JackBoosY** [comment]
Hi @edmBernard, thanks for reporting this issue!
You can add judgement `if (BUILD_SHARED_LIBS)` / `if (NOT BUILD_SHARED_LIBS)` to `add_library(${ROCKSDB_SHARED_LIB} SHARED ${SOURCES})` / `add_library(${ROCKSDB_STATIC_LIB} STATIC ${SOURCES})` to solve this issue.

**Comment by edmBernard** [comment]
thanks for the answer. I don't remenber exactly the context but I think it will work.
