### ISSUE TITLE
Compatibility is incorrectly reported on vcpkg.io

### ISSUE THREAD

**Issue by jeremy-rifkin** [microsoft/vcpkg#37493]
**Describe the bug**
Package compatibility is incorrectly reported on https://vcpkg.io/en/packages. For example, z3 shows supporting arm-uwp and x64-uwp despite the package not supporting UWP:
![image](https://github.com/microsoft/vcpkg/assets/51220084/bc02e150-cf82-414f-9d93-2c0899c87988)
https://github.com/microsoft/vcpkg/blob/cf4ebef2294e164875ce17d7937f44d3e3ea156e/ports/z3/vcpkg.json#L2-L7

**Environment**
- OS: All
- Compiler: All

**To Reproduce**
1. Visit https://vcpkg.io/en/packages
2. Search for z3
3. Observe UWP compatibility listed

**Expected behavior**
Correct compatibility information should be shown.

**Failure logs**
N/A

**Additional context**
N/A

**Comment by LilyWangLL** [comment]
Now `Compatibility` field has been removed, see details from https://github.com/vcpkg/vcpkg.github.io/pull/154.
