### ISSUE TITLE
[sdl2] build failure

### ISSUE THREAD

**Issue by alexhsu** [microsoft/vcpkg#37500]
### Operating system

windows 11

### Compiler

msvc

### Steps to reproduce the behavior

```Shell
`.\vcpkg.exe install sdl2:x64-windows`
```

### Failure logs

Computing installation plan...
error: while looking for sdl2:x64-windows:
error: while loading C:\Users\alex\source\repos\vcpkg\ports\sdl2\vcpkg.json:
$.default-features[0]: mismatched type: expected an identifier
$.default-features[1]: mismatched type: expected an identifier
$.default-features[2]: mismatched type: expected an identifier

**Comment by FrankXie05** [comment]
@alexhsu Could you please run command `.\bootstrap-vcpkg.bat` and try again?

**Comment by alexhsu** [comment]
> @alexhsu Could you please run command `.\bootstrap-vcpkg.bat` and try again?

thanks, it works for me

**Comment by FrankXie05** [comment]
Closed this by https://github.com/microsoft/vcpkg/issues/37500#issuecomment-2017447159
