### ISSUE TITLE
fatal error LNK1104: cannot open file 'libboost_regex-vc141-mt-gd-x32-1_67.lib'

### ISSUE THREAD

**Issue by JBSedich** [microsoft/vcpkg#3750]
Hello,
I encounter the following error for bootstrap-vcpkg.bat (I have not modified .vcxproj file, fresh download).

> Building vcpkg.exe ...
> 
>   Vcpkg is unable to link because we cannot decide between Release and Debug libraries. Please define the property Vc
>   pkgConfiguration to be 'Release' or 'Debug' (currently 'release').
>   pch.cpp
>   checks.cpp
> 
> [...]  
> 
>   vcpkgpaths.cpp
>   versiont.cpp
>   vcpkglib.vcxproj -> C:\libraries\vcpkg-master\toolsrc\release\vcpkglib.lib
>   Vcpkg is unable to link because we cannot decide between Release and Debug libraries. Please define the property Vc
>   pkgConfiguration to be 'Release' or 'Debug' (currently 'release').
>   vcpkg.cpp
>   Generating code

I also encounter this in VS after _vcpkg integrate install_

> 1>LINK : fatal error LNK1104: cannot open file 'libboost_regex-vc141-mt-gd-x32-1_67.lib'

Windows 10.0.17134, latest vcpkg as of today.

**Comment by alexkaratarakis** [comment]
Hi @JBSedich, 
The first one is a known issue that we are working on. You can safely disregard it for now.

Regarding the second one:
- Does removing integration with `vcpkg integrate remove` make the problem go away?
- Can you remove and install boost to make sure it is properly installed?

**Comment by KindDragon** [comment]
Relate to #2790

**Comment by JackBoosY** [comment]
Hi everyone, boost has been updated to 1.73.0, so I guess this issue was resolved.
Please reopen this issue if it still bother you,

Thanks.
