### ISSUE TITLE
Rename scripts/cmake/vcpkg_find_acquire_program(DARK).cmake to scripts/cmake/vcpkg_find_acquire_program(WiX).cmake

### ISSUE THREAD

**Issue by JoergAtGithub** [microsoft/vcpkg#37519]
**Describe the bug**
scripts/cmake/vcpkg_find_acquire_program(DARK).cmake acquires the full WiX toolkit and not only the dark decompiler contained in this toolkit.

**Expected behavior**
Users who use the WiX toolkit to build MSI installers could use it from VCPKG, instead of installing the toolkit seperatly. But they will not find it, if it's hidden under the name DARK.

**Comment by jimwang118** [comment]
The name cannot be changed to wix. The `vcpkg_find_acquire_program()` function will find the corresponding runnable program based on the parameters passed in. If the name is changed to wix, there is no corresponding runnable program and the port that relies on this script will report an error.

**Comment by JoergAtGithub** [comment]
Thanks for explaining this!
