### ISSUE TITLE
failed to compress folder

### ISSUE THREAD

**Issue by mxlik-ali** [microsoft/vcpkg#37513]
<img width="907" alt="Screenshot 2024-03-17 070031" src="https://github.com/microsoft/vcpkg/assets/97386337/980aff78-3770-4ed5-a878-38832c285da1">

it comes with this warning will this create some issues later or not??

**Comment by LilyWangLL** [comment]
This should be a permissions issue with the C drive. If installed on another disk, this warning should not appear.

**Comment by mxlik-ali** [comment]
> This should be a permissions issue with the C drive. If installed on another disk, this warning should not appear.

initially i was installing on path C/Users/Mohammed Ali/ but since there was space between Mohammed and Ali there was some issue with thw installation so i changed the path to C drive directly , wht should i do to solve this?

**Comment by LilyWangLL** [comment]
This issue will be fixed by #37585.
