### ISSUE TITLE
Adding triplet/toolchain for mingw on Windows

### ISSUE THREAD

**Issue by thomas-t1** [microsoft/vcpkg#3752]
For various reasons we would like to use vcpkg to use mingw gcc to build packages on windows.

I'm having a hard time understanding if it is supported to extend vcpkg in this way?
If it is possible, how to add custom triplets and specifically how to add the corresponding toolchain support i.e. how to instruct vcpkg to use the mingw gcc toolchain?

**Comment by Voskrese** [comment]
полностью вынести mingw просто видимо не получиться, код заточен для msvc, но многие порты собираются именно через mingw. так что, просто используйте в порте mingw, мне кажется это упростит задачу

> Completely to bear MinGW just apparently not get, the code imprisoned for MSVC, but many ports are collected through MinGW. So, just use the port MinGW, I think it will simplify the task

**Comment by mloskot** [comment]
I think this can be closed as per @ras0219-msft 's https://github.com/Microsoft/vcpkg/issues/4418#issuecomment-428168157 posted in October 2018.

**Comment by Voskrese** [comment]
Attempting to build under mingw, semi-working option

https://github.com/Microsoft/vcpkg/pull/5117

**Comment by alcroito** [comment]
I think if https://github.com/microsoft/vcpkg/pull/9137 gets merged, this issues's status could be changed to fixed.
