### ISSUE TITLE
[zeromq] Build error on x64-windows

### ISSUE THREAD

**Issue by fcyctop** [microsoft/vcpkg#37525]
vcpkg package management program version 2024-02-07-8a83681f921b10d86ae626fd833c253f4f8c355b

[issue_body.md](https://github.com/microsoft/vcpkg/files/14630342/issue_body.md)

**Comment by MonicaLiu0311** [comment]
> ```
> CMake Warning at scripts/cmake/vcpkg_execute_build_process.cmake:65 (message):
>   Please ensure your system has sufficient memory
> ```

This warning was found in your logs.

**Comment by fcyctop** [comment]
> [Mar 18, 2024](#event-12146293329)
> [<img alt="@MonicaLiu0311" width="40" height="40" src="https://avatars.githubusercontent.com/u/110024546?s=80&amp;u=e828dedb2f7e67945b6c3cf9be5ddf80a988826b&amp;v=4">](/MonicaLiu0311)

感谢你的回复！但是我想我应该有足够的内存。下面是我在同一台电脑并且打开任务管理器的情况下再次运行'.\vcpkg.exe install zeromq'的截图。
![2yGL0sdzOy](https://github.com/microsoft/vcpkg/assets/73358471/2f350183-eb59-4d41-91b4-57a4bed30a0d)
从开始到结束我的内存占用率都没有超过40%，但是还是失败了。
我看到vcpkg的提示，运行'git pull'和'vcpkg update'，但是都没有用。
我不知道怎么解决，所以来这里需求帮助。

这是我现在用的vcpkg版本：
PS D:\github2\samples\third_part\vcpkg> .\vcpkg.exe version
vcpkg package management program version 2024-02-07-8a83681f921b10d86ae626fd833c253f4f8c355b

See LICENSE.txt for license information.

**Comment by fcyctop** [comment]
I think it's the same problem as #37023
