### ISSUE TITLE
[sail] fix layout in vcpkg include tree

### ISSUE THREAD

**Issue by ghesketh** [microsoft/vcpkg#37522]
### Is your feature request related to a problem? Please describe.

the primary header expects to be
`#include <sail/sail.h>`

but vcpkg creates it as
`#include <sail/sail/sail.h>`

... which causes failure to load the content of sail.h:

`#include <sail-common/sail-common.h>`

`#include <sail/codec_bundle.h>`
`#include <sail/codec_bundle_node.h>`
`#include <sail/codec_info.h>`
`#include <sail/codec_priority.h>`
`#include <sail/context.h>`
`#include <sail/io_file.h>`
`#include <sail/io_memory.h>`
`#include <sail/io_noop.h>`
`#include <sail/sail_advanced.h>`
`#include <sail/sail_deep_diver.h>`
`#include <sail/sail_junior.h>`
`#include <sail/sail_technical_diver.h>`

### Proposed solution

the most sustainable solution would be to add sail's headers in the expected places

### Describe alternatives you've considered

it would also be possible to modify the headers when building the sail package, but that probably requires more work and produces a result inconsistent with the library's documentation

**Comment by JonLiu1993** [comment]
@ghesketh, Thanks for posting this issue, After I installed sail:x64-windows locally, I created a simple cmake project and could successfully include the following content
````
#include <sail/codec_bundle.h>
#include <sail/codec_bundle_node.h>
#include <sail/codec_info.h>
#include <sail/codec_priority.h>
#include <sail/context.h>
#include <sail/io_file.h>
#include <sail/io_memory.h>
#include <sail/io_noop.h>
#include <sail/sail_advanced.h>
#include <sail/sail_deep_diver.h>
#include <sail/sail_junior.h>
#include <sail/sail_technical_diver.h>
````
May I ask if there is something wrong with my understanding?
![image](https://github.com/microsoft/vcpkg/assets/63675417/9e8bdcb2-feda-4b33-8c34-81b76fcbf1ff)

**Comment by ghesketh** [comment]
> @ghesketh, Thanks for posting this issue, After I installed sail:x64-windows locally, I created a simple cmake project and could successfully include the following content
> 
> ```
> #include <sail/codec_bundle.h>
> #include <sail/codec_bundle_node.h>
> #include <sail/codec_info.h>
> #include <sail/codec_priority.h>
> #include <sail/context.h>
> #include <sail/io_file.h>
> #include <sail/io_memory.h>
> #include <sail/io_noop.h>
> #include <sail/sail_advanced.h>
> #include <sail/sail_deep_diver.h>
> #include <sail/sail_junior.h>
> #include <sail/sail_technical_diver.h>
> ```
> 
> May I ask if there is something wrong with my understanding?

Thank you for the reply!

I have an existing Visual Studio (msbuild) project, and after I installed sail, Visual Studio did not see sail's headers because their locations in the include tree were not correct.

-- Gifford

**Comment by JonLiu1993** [comment]
I also created a C++ project and can still find it automatically using msbuild mode.
![image](https://github.com/microsoft/vcpkg/assets/63675417/56e5ac76-d281-44fd-bb0c-ffcad0d6d53f)

**Comment by dg0yt** [comment]
> I also created a C++ project and can still find it automatically using msbuild mode.

No? You cannot, according to the screenshot: You end with `sail/sail/...` but official usage is `sail/...`.

**Comment by JonLiu1993** [comment]
OK, I will Ok, I have modified the label, I will try to fix this issue.

**Comment by ghesketh** [comment]
> It should be noted that vcpkg can only find header files in the include folder by default. In order to prevent conflicts, vcpkg adds a layer of directory xxx and installs some libraries in the include\xxx folder. At this time, you need to manually add include\ xxx to the msbuild project.

I am not sure I understand your comment.  Sail only expects to find its headers below the include directory.  It does have multiple folders (sail, sail-common, sail-manip) that it expects there, but there are other packages (ffmpeg, fast_io, etc.) that install multiple directories as include\xxx, so equivalent behavior between CMake and msbuild seems not to be difficult.
