### ISSUE TITLE
[sail] static library detection for libjxl does not match installed library

### ISSUE THREAD

**Issue by ghesketh** [microsoft/vcpkg#37557]
the end result is that sail wants to import functions from dynamic libraries that do not exist

vcpkg install sail[jpegxl]:x64-windows-static

the static library names for libjxl are jxl.lib, jxl_cms.lib, and jxl_threads.lib

... but sail's CMakeLists.txt expects otherwise:

if (JPEGXL_LIBRARY MATCHES "jxl-static")
    set(JXL_STATIC_DEFINE "JXL_STATIC_DEFINE")
endif()

**Comment by jimwang118** [comment]
I don't understand what you mean? But I searched the `libjxl` code and didn't find the content in `cmakelists.txt` you mentioned. Are you using the latest version of vcpkg?

**Comment by ghesketh** [comment]
the issue is for the sail package, and the CMakeLists.txt lines are from the sail package

... and yes, vcpkg and all of its parts are completely current

**Comment by ghesketh** [comment]
src\v0.9.1-4948948aa8.clean\src\sail-codecs\jpegxl\CMakeLists.txt

**Comment by dg0yt** [comment]
Maybe libjxl needs to burn in `JXL_STATIC_DEFINE`.

**Comment by jimwang118** [comment]
I searched in the cmakelists.txt of `libjxl` and found that only the library named `jxl` was compiled, but there was no library named `jxl-static`. Therefore, the wrong library name was filled in when calling in sail.

jxl.cmake
`add_library(jxl ${JPEGXL_INTERNAL_OBJECTS})`
