### ISSUE TITLE
ubuntu [opencl] Build error on x64-mingw-dynamic

### ISSUE THREAD

**Issue by shellow** [microsoft/vcpkg#37576]
On ubuntu 22.04

VCPKG_DEFAULT_TRIPLET=x64-mingw-dynamic VCPKG_DEFAULT_HOST_TRIPLET=x64-mingw-dynamic vcpkg install opencl

CMake Error at ports/opencl/portfile.cmake:52 (file):
  file INSTALL cannot find
  "vcpkg/buildtrees/opencl/x64-mingw-dynamic-rel/libOpenCL.dll":
  No such file or directory.

**Comment by DistinctWind** [comment]
The same thing also happens on Windows with x64-mingw-dynamic triplet.
