### ISSUE TITLE
error LNK2019: unresolved external symbol for building PCL

### ISSUE THREAD

**Issue by hrheydarian** [Microsoft/vcpkg#3758]
Hi,

I followed the instruction on http://unanancyowen.com/en/pcl-vcpkg/ to install PCL using vcpkg. Everything is fine and cmake is producing the solution and project files without any errors or warnings.

However, when I try to build the project using Visual Studio 2017 I get several unresolved external symbol errors. Could anyone help me with that? I spent two days on this issue but cannot resolve it.

The errors are as follow:

> 2>iterative_closest_point.obj : error LNK2019: unresolved external symbol "void __cdecl pcl::console::print(enum pcl::console::VERBOSITY_LEVEL,char const *,...)" (?print@console@pcl@@YAXW4VERBOSITY_LEVEL@12@PEBDZZ) referenced in function "protected: virtual void __cdecl pcl::IterativeClosestPoint<struct pcl::PointXYZ,struct pcl::PointXYZ,float>::computeTransformation(class pcl::PointCloud<struct pcl::PointXYZ> &,class Eigen::Matrix<float,4,4,0,4,4> const &)" (?computeTransformation@?$IterativeClosestPoint@UPointXYZ@pcl@@U12@M@pcl@@MEAAXAEAV?$PointCloud@UPointXYZ@pcl@@@2@AEBV?$Matrix@M$03$03$0A@$03$03@Eigen@@@Z)
2>iterative_closest_point.obj : error LNK2019: unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::generic_category(void)" (?generic_category@system@boost@@YAAEBVerror_category@12@XZ) referenced in function "public: __cdecl boost::thread_exception::thread_exception(int,char const *)" (??0thread_exception@boost@@QEAA@HPEBD@Z)
2>iterative_closest_point.obj : error LNK2019: unresolved external symbol "public: __cdecl pcl::PCLBase<struct pcl::PointXYZ>::PCLBase<struct pcl::PointXYZ>(void)" (??0?$PCLBase@UPointXYZ@pcl@@@pcl@@QEAA@XZ) referenced in function "public: __cdecl pcl::registration::CorrespondenceEstimationBase<struct pcl::PointXYZ,struct pcl::PointXYZ,float>::CorrespondenceEstimationBase<struct pcl::PointXYZ,struct pcl::PointXYZ,float>(void)" (??0?$CorrespondenceEstimationBase@UPointXYZ@pcl@@U12@M@registration@pcl@@QEAA@XZ)
2>iterative_closest_point.obj : error LNK2019: unresolved external symbol "public: __cdecl pcl::PCLBase<struct pcl::PointXYZ>::PCLBase<struct pcl::PointXYZ>(class pcl::PCLBase<struct pcl::PointXYZ> const &)" (??0?$PCLBase@UPointXYZ@pcl@@@pcl@@QEAA@AEBV01@@Z) referenced in function "public: __cdecl pcl::registration::CorrespondenceEstimationBase<struct pcl::PointXYZ,struct pcl::PointXYZ,float>::CorrespondenceEstimationBase<struct pcl::PointXYZ,struct pcl::PointXYZ,float>(class pcl::registration::CorrespondenceEstimationBase<struct pcl::PointXYZ,struct pcl::PointXYZ,float> const &)" (??0?$CorrespondenceEstimationBase@UPointXYZ@pcl@@U12@M@registration@pcl@@QEAA@AEBV012@@Z)
2>iterative_closest_point.obj : error LNK2019: unresolved external symbol "public: virtual void __cdecl pcl::PCLBase<struct pcl::PointXYZ>::setInputCloud(class boost::shared_ptr<class pcl::PointCloud<struct pcl::PointXYZ> const > const &)" (?setInputCloud@?$PCLBase@UPointXYZ@pcl@@@pcl@@UEAAXAEBV?$shared_ptr@$$CBV?$PointCloud@UPointXYZ@pcl@@@pcl@@@boost@@@Z) referenced in function "public: void __cdecl pcl::registration::CorrespondenceEstimationBase<struct pcl::PointXYZ,struct pcl::PointXYZ,float>::setInputSource(class boost::shared_ptr<class pcl::PointCloud<struct pcl::PointXYZ> const > const &)" (?setInputSource@?$CorrespondenceEstimationBase@UPointXYZ@pcl@@U12@M@registration@pcl@@QEAAXAEBV?$shared_ptr@$$CBV?$PointCloud@UPointXYZ@pcl@@@pcl@@@boost@@@Z)
2>iterative_closest_point.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl pcl::PCLBase<struct pcl::PointXYZ>::setIndices(class boost::shared_ptr<class std::vector<int,class std::allocator<int> > > const &)" (?setIndices@?$PCLBase@UPointXYZ@pcl@@@pcl@@UEAAXAEBV?$shared_ptr@V?$vector@HV?$allocator@H@std@@@std@@@boost@@@Z)
2>iterative_closest_point.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl pcl::PCLBase<struct pcl::PointXYZ>::setIndices(class boost::shared_ptr<class std::vector<int,class std::allocator<int> > const > const &)" (?setIndices@?$PCLBase@UPointXYZ@pcl@@@pcl@@UEAAXAEBV?$shared_ptr@$$CBV?$vector@HV?$allocator@H@std@@@std@@@boost@@@Z)
2>iterative_closest_point.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl pcl::PCLBase<struct pcl::PointXYZ>::setIndices(class boost::shared_ptr<struct pcl::PointIndices const > const &)" (?setIndices@?$PCLBase@UPointXYZ@pcl@@@pcl@@UEAAXAEBV?$shared_ptr@$$CBUPointIndices@pcl@@@boost@@@Z)
2>iterative_closest_point.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl pcl::PCLBase<struct pcl::PointXYZ>::setIndices(unsigned __int64,unsigned __int64,unsigned __int64,unsigned __int64)" (?setIndices@?$PCLBase@UPointXYZ@pcl@@@pcl@@UEAAX_K000@Z)
2>iterative_closest_point.obj : error LNK2019: unresolved external symbol "protected: bool __cdecl pcl::PCLBase<struct pcl::PointXYZ>::initCompute(void)" (?initCompute@?$PCLBase@UPointXYZ@pcl@@@pcl@@IEAA_NXZ) referenced in function "protected: bool __cdecl pcl::registration::CorrespondenceEstimationBase<struct pcl::PointXYZ,struct pcl::PointXYZ,float>::initCompute(void)" (?initCompute@?$CorrespondenceEstimationBase@UPointXYZ@pcl@@U12@M@registration@pcl@@IEAA_NXZ)
2>iterative_closest_point.obj : error LNK2019: unresolved external symbol "protected: bool __cdecl pcl::PCLBase<struct pcl::PointXYZ>::deinitCompute(void)" (?deinitCompute@?$PCLBase@UPointXYZ@pcl@@@pcl@@IEAA_NXZ) referenced in function "public: void __cdecl pcl::Registration<struct pcl::PointXYZ,struct pcl::PointXYZ,float>::align(class pcl::PointCloud<struct pcl::PointXYZ> &,class Eigen::Matrix<float,4,4,0,4,4> const &)" (?align@?$Registration@UPointXYZ@pcl@@U12@M@pcl@@QEAAXAEAV?$PointCloud@UPointXYZ@pcl@@@2@AEBV?$Matrix@M$03$03$0A@$03$03@Eigen@@@Z)
2>iterative_closest_point.obj : error LNK2019: unresolved external symbol "public: __cdecl pcl::search::KdTree<struct pcl::PointXYZ,class pcl::KdTreeFLANN<struct pcl::PointXYZ,struct flann::L2_Simple<float> > >::KdTree<struct pcl::PointXYZ,class pcl::KdTreeFLANN<struct pcl::PointXYZ,struct flann::L2_Simple<float> > >(bool)" (??0?$KdTree@UPointXYZ@pcl@@V?$KdTreeFLANN@UPointXYZ@pcl@@U?$L2_Simple@M@flann@@@2@@search@pcl@@QEAA@_N@Z) referenced in function "public: __cdecl pcl::registration::CorrespondenceEstimationBase<struct pcl::PointXYZ,struct pcl::PointXYZ,float>::CorrespondenceEstimationBase<struct pcl::PointXYZ,struct pcl::PointXYZ,float>(void)" (??0?$CorrespondenceEstimationBase@UPointXYZ@pcl@@U12@M@registration@pcl@@QEAA@XZ)
2>iterative_closest_point.obj : error LNK2019: unresolved external symbol "public: void __cdecl pcl::search::KdTree<struct pcl::PointXYZ,class pcl::KdTreeFLANN<struct pcl::PointXYZ,struct flann::L2_Simple<float> > >::setPointRepresentation(class boost::shared_ptr<class pcl::PointRepresentation<struct pcl::PointXYZ> const > const &)" (?setPointRepresentation@?$KdTree@UPointXYZ@pcl@@V?$KdTreeFLANN@UPointXYZ@pcl@@U?$L2_Simple@M@flann@@@2@@search@pcl@@QEAAXAEBV?$shared_ptr@$$CBV?$PointRepresentation@UPointXYZ@pcl@@@pcl@@@boost@@@Z) referenced in function "public: void __cdecl pcl::Registration<struct pcl::PointXYZ,struct pcl::PointXYZ,float>::align(class pcl::PointCloud<struct pcl::PointXYZ> &,class Eigen::Matrix<float,4,4,0,4,4> const &)" (?align@?$Registration@UPointXYZ@pcl@@U12@M@pcl@@QEAAXAEAV?$PointCloud@UPointXYZ@pcl@@@2@AEBV?$Matrix@M$03$03$0A@$03$03@Eigen@@@Z)
2>C:\pcl\test_icp\build\Debug\iterative_closest_point.exe : fatal error LNK1120: 13 unresolved externals
2>Done building project "iterative_closest_point.vcxproj" -- FAILED.

Thanks

**Comment by skycowninja** [comment]
Did you run the command 'vcpkg integrate install' after installing pcl? If not, I might try that. 

It became a lot easier for me cause I'm a newb and cmake was even difficult for me. It should automatically integrate everything into Visual Studio 2017 as needed.

**Comment by PhoebeHui** [comment]
@hrheydarian, does the issue still persist? I installed pcl:x64-windows successfully.

PS F:\vcpkg\src> ./vcpkg version
Vcpkg package management program version 2018.11.23-nohash

PS F:\vcpkg\src> ./vcpkg install pcl:x64-windows
...
Building package pcl[core]:x64-windows... done
Installing package pcl[core]:x64-windows...
Installing package pcl[core]:x64-windows... done
Elapsed time for package pcl:x64-windows: 55.07 min

Total elapsed time: 1.543 h

The package pcl:x64-windows provides CMake targets:

    find_package(PCL CONFIG REQUIRED)
    target_link_libraries(main PRIVATE ${pcl_component})

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
