### ISSUE TITLE
libssh build failed

### ISSUE THREAD

**Issue by sn2234** [Microsoft/vcpkg#3759]
C:\SDKs\vcpkg>vcpkg.exe install libssh:x64-windows libssh:x86-windows
The following packages will be built and installed:
    libssh[core]:x64-windows
    libssh[core]:x86-windows
Starting package 1/2: libssh:x64-windows
Building package libssh[core]:x64-windows...
-- CURRENT_INSTALLED_DIR=C:/SDKs/vcpkg/installed/x64-windows
-- DOWNLOADS=C:/SDKs/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/SDKs/vcpkg/packages/libssh_x64-windows
-- CURRENT_BUILDTREES_DIR=C:/SDKs/vcpkg/buildtrees/libssh
-- CURRENT_PORT_DIR=C:/SDKs/vcpkg/ports/libssh
-- Downloading https://red.libssh.org/attachments/download/218/libssh-0.7.5.tar.xz...
-- Downloading https://red.libssh.org/attachments/download/218/libssh-0.7.5.tar.xz... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:155 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/libssh/portfile.cmake:7 (vcpkg_download_distfile)
  scripts/ports.cmake:72 (include)

Error: Building package libssh:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libssh:x64-windows
  Vcpkg version: 0.0.113-nohash

**Comment by fredstoolbox** [comment]
looks like the libssh tarball no longer available for download or that it has been moved (there is no indication what's wrong on libssh's website)

**Comment by PhoebeHui** [comment]
@sn2234, it looks a temporary issue, libssh update to 0.7.6 version, and change to more stable link to download the file,  please open a new issue if it persists.
