### ISSUE TITLE
jxrlib not compiling in x64-windows 

### ISSUE THREAD

**Issue by traversaro** [Microsoft/vcpkg#376]
See https://github.com/Microsoft/vcpkg/pull/366#issuecomment-264120322 .

cc @phsucharee .

**Comment by phsucharee** [comment]
I think it is best to modify `ports/jxrlib/CMakeLists.txt` at
```
65|-   PROPERTY COMPILE_DEFINITIONS __ANSI__ DISABLE_PERF_MEASUREMENT ${DEF_ENDIAN}
65|+   PROPERTY COMPILE_DEFINITIONS DISABLE_PERF_MEASUREMENT ${DEF_ENDIAN}
```
and
```
83|-   PROPERTY COMPILE_DEFINITIONS __ANSI__ DISABLE_PERF_MEASUREMENT ${DEF_ENDIAN}
83|+   PROPERTY COMPILE_DEFINITIONS DISABLE_PERF_MEASUREMENT ${DEF_ENDIAN}
```
I'm not sure why `__ANSI__` is needed here since we're on a windows system. Leaving `__ANSI__` out compiles perfectly fine. 

For reference: 
https://sourceforge.net/p/freeimage/discussion/36111/thread/a9cc87b6/

**Comment by phsucharee** [comment]
I made a pull request #379.
