### ISSUE TITLE
[vcpkg-tool-meson] Build error on x64-windows

### ISSUE THREAD

**Issue by WaywardWhite** [microsoft/vcpkg#37615]
Copy issue body from C:/Program Files/VCPKG/vcpkg-master/installed/vcpkg/issue_body.md

error: building vcpkg-tool-meson:x64-windows failed with: BUILD_FAILED
Elapsed time to handle vcpkg-tool-meson:x64-windows: 14 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+vcpkg-tool-meson
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[vcpkg-tool-meson]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2FProgram%20Files%2FVCPKG%2Fvcpkg-master%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by WaywardWhite** [comment]
Computing installation plan...
The following packages will be built and installed:
    colmap[core,cuda,tests]:x64-windows@2023-10-01
  * harfbuzz[core,freetype]:x64-windows@8.3.1
  * openssl:x64-windows@3.2.1#1
  * pcre2[core,jit,platform-default-features]:x64-windows@10.42#2
  * pkgconf:x64-windows@2.1.0
  * qt5-base:x64-windows@5.15.13#1
  * sqlite3[core,json1]:x64-windows@3.45.2
  * vcpkg-pkgconfig-get-modules:x64-windows@2023-09-06
  * vcpkg-tool-meson:x64-windows@1.3.2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
A suitable version of git was not found (required v2.7.4) Downloading portable git 2.7.4...
Extracting git...
A suitable version of powershell-core was not found (required v7.2.16) Downloading portable powershell-core 7.2.16...
Extracting powershell-core...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exeA suitable version of 7zip was not found (required v23.1.0) Downloading portable 7zip 23.1.0...
Extracting 7zip...
Restored 0 package(s) from C:\Users\zfq\AppData\Local\vcpkg\archives in 2.08 ms. Use --debug to see more details.
Installing 1/9 vcpkg-tool-meson:x64-windows@1.3.2...
Building vcpkg-tool-meson:x64-windows@1.3.2...
-- Installing: C:/Program Files/VCPKG/vcpkg-master/packages/vcpkg-tool-meson_x64-windows/share/vcpkg-tool-meson/copyright
-- Using cached python-3.11.8-embed-amd64.zip.
-- Found Python version '3.11.8 at C:/Program Files/VCPKG/vcpkg-master/downloads/tools/python/python-3.11.8-x64/python.exe'
-- Using cached meson-614d436232d3a86518164cbe2b8af12db3bde009.tar.gz.
-- Applying patch C:/Program Files/VCPKG/vcpkg-master/packages/vcpkg-tool-meson_x64-windows/share/vcpkg-tool-meson/adjust-args.patch
CMake Error at scripts/cmake/z_vcpkg_apply_patches.cmake:34 (message):
  Applying patch failed:
Call Stack (most recent call first):
  packages/vcpkg-tool-meson_x64-windows/share/vcpkg-tool-meson/vcpkg-port-config.cmake:50 (z_vcpkg_apply_patches)
  ports/vcpkg-tool-meson/portfile.cmake:39 (include)
  scripts/ports.cmake:175 (include)

**Comment by Cheney-W** [comment]
`C:/Program Files/VCPKG`
Please do not clone the `vcpkg` folder to a path with spaces.

**Comment by Neumann-A** [comment]
> Please do not clone the vcpkg folder to a path with spaces.

you mean without spaces

**Comment by WaywardWhite** [comment]
I moved the VCPKG folder to a path with no Spaces, and this is still the result

**Comment by Aketti** [comment]
Yes that has nothing to do with it, I have no white spaces in my path to vcpkg and I also have build problems with this, starting yesterday for me when trying to install harfbuzz as a dependency. vcpkg-tool-meson:x64-windows build was failing earlier but upgrading it just now succeeded. pkgconf:x64-windows build is the one failing.

**Comment by Neumann-A** [comment]
tried to reproduce it locally but wasn't able to see an error.

**Comment by Aketti** [comment]
Yeah, so there seems to arise a conflict between the internal python used by vcpkg and one of the versions installed on my computer outside of vcpkg. More precisely one that is installed via the company portal and is required by my organization. It is not the version I use as my main python however (the one I have in PATH).

When trying to install the failing package in vcpkg, vcpkg python is found:
Found Python version '3.11.8 at `user/vcpkg/downloads/tools/python/python-3.11.8-x64/python.exe`

By changing the name of a directory, `C:\Program Files\Python3` I was able to build and install the packages.

I have not encountered this problem before even though I have had pretty much the same configuration of python versions on my computer for a good while.

**Comment by WaywardWhite** [comment]
Thanks for your response, a different python version (PATH) successfully solved the problem

**Comment by aminya** [comment]
I have the same version with Python 12 installed on my system.

```
> python --version
Python 3.12.2
```

But 
```
vcpkg\downloads\tools\python\python-3.11.8-x64\python.exe --version
```

Fails with 
```
-- Using cached python-3.11.8-embed-amd64.zip.
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: C:/Users/aminy/vcpkg/downloads/python-3.11.8-embed-amd64.zip
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: K:/Programs/vcpkg/downloads/tools/cmake-3.29.0-windows/cmake-3.29.0-windows-i386/bin/cmake.exe -E rm python311._pth
    Working Directory: C:/Users/aminy/vcpkg/downloads/tools/python/python-3.11.8-x64
    Error code: 1
    See logs for more information:
      C:\Users\aminy\vcpkg\buildtrees\vcpkg-tool-meson\PYTHON3-tool-post-install-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:207 (vcpkg_execute_required_process)
  packages/vcpkg-tool-meson_x64-windows/share/vcpkg-tool-meson/vcpkg-port-config.cmake:50 (vcpkg_find_acquire_program)
  buildtrees/versioning_/versions/vcpkg-tool-meson/8408112396883b134bd25e2522f9a806ceaae3ea/portfile.cmake:39 (include)
  scripts/ports.cmake:175 (include)
```

**Comment by combolek** [comment]
I ran into the same issue when trying to install `harfbuzz`. Yes, it is a conflict with system python. I didn't want to remove it so instead what worked for me was to point `PYTHONHOME` to wherever the vcpkg downloaded python is e.g.:
```
set PYTHONHOME=C:\src\vcpkg\downloads\tools\python\python-3.11.8-x64
```

**Comment by aminya** [comment]
I think, the python versions need to match the system's python to avoid these issues (especially on Linux).
Or there needs to be an option for that at least.
