### ISSUE TITLE
[glew] Build error on x64-linux

### ISSUE THREAD

**Issue by timta8** [microsoft/vcpkg#37627]
Copy issue body from /home/timta/anura/vcpkg_installed/vcpkg/issue_body.md
<img width="542" alt="error" src="https://github.com/microsoft/vcpkg/assets/159729017/8ff02797-6021-4667-b130-76ae4762a35d">

**Comment by WangWeiLin-MV** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report a build failure.
