### ISSUE TITLE
[qcoro]Build error

### ISSUE THREAD

**Issue by mazalet** [microsoft/vcpkg#37652]

**Comment by mazalet** [comment]
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: D:/k/buildtrees/qcoro/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\k\buildtrees\qcoro\config-x86-windows-dbg-CMakeCache.txt.log
      D:\k\buildtrees\qcoro\config-x86-windows-rel-CMakeCache.txt.log
      D:\k\buildtrees\qcoro\config-x86-windows-out.log

Call Stack (most recent call first):
  C:/dev/txt/coro-test/cmake-build-debug-visual-studio-32/vcpkg_installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:252 (vcpkg_execute_required_process)
  tela-qt5-ports/qcoro/portfile.cmake:20 (vcpkg_cmake_configure)
  scripts/ports.cmake:175 (include)

**Comment by FrankXie05** [comment]
@mazalet Please see #30604 for how to report an issue.
