### ISSUE TITLE
[PCL] install failure

### ISSUE THREAD

**Issue by Bzz2745** [microsoft/vcpkg#37655]
### Operating system

Windows 11

### Compiler

MSVC vc143

### Steps to reproduce the behavior

```Shell
`./vcpkg install pcl[apps,core,cuda,opengl,openni2,qt,simulation,tools,visualization,vtk]:x64-windows`
```

### Failure logs

Installing 24/49 vtk[atlmfc,core,cuda,gdal,geojson,mpi,opengl,openvr,qt,utf8,vtkm]:x64-windows@9.2.0-pv5.11.0#10...
Building vtk[atlmfc,core,cuda,gdal,geojson,mpi,opengl,openvr,qt,utf8,vtkm]:x64-windows@9.2.0-pv5.11.0#10...
-- Downloading https://gitlab.kitware.com/vtk/vtk/-/commit/bfa3e4c7621ddf5826755536eb07284c86db6474.diff?full_index=1 -> vtk-string-bfa3e4.diff...
-- Downloading https://gitlab.kitware.com/vtk/vtk/-/commit/c938d30634a284fad026f6ae25c30bc84cadc07e.diff?full_index=1 -> vtk-mpi4py-update-part1-c938d3.diff...
-- Downloading https://gitlab.kitware.com/vtk/vtk/-/commit/53e6ce92ae4591552e7e00344d69803117d56bfe.diff?full_index=1 -> vtk-mpi4py-update-part2-53e6ce.diff...
-- Downloading https://github.com/Kitware/VTK/archive/66143ef041b980a51e41ee470d053e67209150f8.tar.gz -> Kitware-VTK-66143ef041b980a51e41ee470d053e67209150f8.tar.gz...
-- Extracting source C:/vcpkg/downloads/Kitware-VTK-66143ef041b980a51e41ee470d053e67209150f8.tar.gz
-- Applying patch FindLZMA.patch
-- Applying patch FindLZ4.patch
-- Applying patch libproj.patch
-- Applying patch pegtl.patch
-- Applying patch pythonwrapper.patch
-- Applying patch NoUndefDebug.patch
-- Applying patch fix-using-hdf5.patch
-- Applying patch FindExpat.patch
-- Applying patch cgns.patch
-- Applying patch vtkm.patch
-- Applying patch afxdll.patch
-- Applying patch vtkioss.patch
-- Applying patch jsoncpp.patch
-- Applying patch iotr.patch
-- Applying patch C:/vcpkg/downloads/vtk-string-bfa3e4.diff
-- Applying patch C:/vcpkg/downloads/vtk-mpi4py-update-part1-c938d3.diff
-- Applying patch C:/vcpkg/downloads/vtk-mpi4py-update-part2-53e6ce.diff
-- Applying patch 9690.diff
-- Applying patch missing-include-fixes.patch
-- Using source at C:/vcpkg/buildtrees/vtk/src/67209150f8-20b191a384.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: C:/vcpkg/packages/vtk_x64-windows/tools/vtk/vtkWrapPythonInit-9.2.exe
-- Installing: C:/vcpkg/packages/vtk_x64-windows/tools/vtk/vtkWrapPython-9.2.exe
-- Installing: C:/vcpkg/packages/vtk_x64-windows/tools/vtk/vtkWrapJava-9.2.exe
-- Installing: C:/vcpkg/packages/vtk_x64-windows/tools/vtk/vtkWrapHierarchy-9.2.exe
-- Installing: C:/vcpkg/packages/vtk_x64-windows/tools/vtk/vtkParseJava-9.2.exe
-- Installing: C:/vcpkg/packages/vtk_x64-windows/tools/vtk/vtkProbeOpenGLVersion-9.2.exe
-- Installing: C:/vcpkg/packages/vtk_x64-windows/tools/vtk/vtkTestOpenGLVersion-9.2.exe
-- Installing: C:/vcpkg/packages/vtk_x64-windows/share/vtk/copyright
-- Performing post-build validation
Elapsed time to handle vtk:x64-windows: 46 min
vtk:x64-windows package ABI: f7a9afde80333ea63fa2885ac84cf1a4711b7c0de19d3f3bf25daf938dda95a0
Installing 25/49 pcl[apps,core,cuda,opengl,openni2,qt,simulation,tools,visualization,vtk]:x64-windows@1.14.0#2...
Building pcl[apps,core,cuda,opengl,openni2,qt,simulation,tools,visualization,vtk]:x64-windows@1.14.0#2...
-- Downloading https://github.com/PointCloudLibrary/pcl/archive/pcl-1.14.0.tar.gz -> PointCloudLibrary-pcl-pcl-1.14.0.tar.gz...
-- Extracting source C:/vcpkg/downloads/PointCloudLibrary-pcl-pcl-1.14.0.tar.gz
-- Applying patch add-gcc-version-check.patch
-- Applying patch fix-check-sse.patch
-- Applying patch fix-numeric-literals-flag.patch
-- Applying patch pcl_config.patch
-- Applying patch pcl_utils.patch
-- Applying patch install-examples.patch
-- Applying patch no-absolute.patch
-- Applying patch fix-clang-cl.patch
-- Applying patch fix-pcl-exports.patch
-- Applying patch fix-kinfu.patch
-- Using source at C:/vcpkg/buildtrees/pcl/src/pcl-1.14.0-4d3a46132f.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_2d.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_apps.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_common.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_cuda_common.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_cuda_features.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_cuda_sample_consensus.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_cuda_segmentation.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_features.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_filters.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_geometry.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_gpu_containers.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_gpu_features.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_gpu_kinfu.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_gpu_kinfu_large_scale.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_gpu_octree.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_gpu_segmentation.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_gpu_utils.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_io.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_kdtree.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_keypoints.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_ml.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_octree.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_outofcore.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_people.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_recognition.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_registration.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_sample_consensus.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_search.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_segmentation.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_simulation.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_stereo.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_surface.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_tracking.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_visualization.pc
-- Downloading https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst -> msys2-mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst...
-- Downloading https://mirror.msys2.org/msys/x86_64/msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst;https://repo.msys2.org/msys/x86_64/msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/msys/x86_64/msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst;https://mirror.selfnet.de/msys2/msys/x86_64/msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst -> msys2-msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst...
-- Using msys root at C:/vcpkg/downloads/tools/msys2/fdbea3694fb5c0d4
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:134 (message):
  C:/vcpkg/downloads/tools/msys2/fdbea3694fb5c0d4/mingw64/bin/pkg-config.exe
  --exists pcl_gpu_kinfu_large_scale failed with error code: 1

      ENV{PKG_CONFIG_PATH}: "C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig;C:/vcpkg/packages/pcl_x64-windows/share/pkgconfig;C:/vcpkg/installed/x64-windows/lib/pkgconfig;C:/vcpkg/installed/x64-windows/share/pkgconfig"
      output: Package vtk was not found in the pkg-config search path.

  Perhaps you should add the directory containing `vtk.pc'

  to the PKG_CONFIG_PATH environment variable

  Package 'vtk', required by 'pcl_gpu_kinfu_large_scale', not found
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:196 (z_vcpkg_fixup_pkgconfig_check_files)
  ports/pcl/portfile.cmake:104 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:175 (include)

**Comment by QiuYilin** [comment]
I also encountered this problem when I turn on cuda option.

**Comment by dg0yt** [comment]
Would be good to see the config logs.

**Comment by dg0yt** [comment]
> Would be good to see the config logs.

Nevermind. Port `vtk` simply doesn't provide a `vtk.pc` file.

**Comment by WangWeiLin-MV** [comment]
@dg0yt  The script `find_package(VTK)` will use the `vtk-config.cmake`.

In my local build, the feature `tools` not enabled, since the post check failed due to the `DLL` that the tools depended on were not cleaned, but this does not affect this result.

Local install passed by the command `vcpkg install pcl[apps,core,cuda,opengl,openni2,qt,simulation,visualization,vtk]`.

@Bzz2745 @QiuYilin Could you help provide the build logs?

### Build Env
* VS 17.9.4
* Windows 11 23H2
* CUDA 11.8

**Comment by dg0yt** [comment]
> @dg0yt The script `find_package(VTK)` will use the `vtk-config.cmake`.

@WangWeiLin-MV True, but unrelated to the problem. The CMake build is reported as successful:

> ~~~
> -- Configuring x64-windows
> -- Building x64-windows-dbg
> -- Building x64-windows-rel

The problem is clearly raised in a following portfile step, due to an invalid pc file.

> ~~~
> - Using msys root at C:/vcpkg/downloads/tools/msys2/fdbea3694fb5c0d4
> CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:134 (message):
> C:/vcpkg/downloads/tools/msys2/fdbea3694fb5c0d4/mingw64/bin/pkg-config.exe
> --exists pcl_gpu_kinfu_large_scale failed with error code: 1
> 
>   ENV{PKG_CONFIG_PATH}: "C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig;C:/vcpkg/packages/pcl_x64-windows/share/pkgconfig;C:/vcpkg/installed/x64-windows/lib/pkgconfig;C:/vcpkg/installed/x64-windows/share/pkgconfig"
>   output: Package vtk was not found in the pkg-config search path.
> 
> Perhaps you should add the directory containing `vtk.pc'
> to the PKG_CONFIG_PATH environment variable
> 
> Package 'vtk', required by 'pcl_gpu_kinfu_large_scale', not found
> Call Stack (most recent call first):
> scripts/cmake/vcpkg_fixup_pkgconfig.cmake:196 (z_vcpkg_fixup_pkgconfig_check_files)
> ports/pcl/portfile.cmake:104 (vcpkg_fixup_pkgconfig)

My PR removes the pc file. The pc files are incomplete anyways.
Upstream has https://github.com/PointCloudLibrary/pcl/pull/5986 which removes the vtk dependency.

**Comment by QiuYilin** [comment]
So, when will vcpkg update pcl now that pcl has updated?

**Comment by AIkikaze** [comment]
I'm facing the same problem again. Hope that vcpkg could update the port of pcl.

**Comment by dg0yt** [comment]
The port bug was fixed last month. If you still see the problem, make a proper new report, with all version information. You did update your vcpkg, didn't you?

**Comment by QiuYilin** [comment]
I see, I can use option "--head" .

**Comment by AIkikaze** [comment]
> The port bug was fixed last month. If you still see the prob. em, make a proper new report, with all version information. You did update your vcpkg, didn't you?

I did, but it didn't work, and I fix this by manually modifying `gpu/kinfu_large_scale/CMakeLists.txt` as your PR. I will make a proper new report soon.

**Comment by dg0yt** [comment]
On a second look, it is visible why the fix in the port doesn't work. With a proper report, I would have looked at this already...
