### ISSUE TITLE
Libunibreak 6.1 port resulting static lib is not linking with MSVC

### ISSUE THREAD

**Issue by HildgenF** [microsoft/vcpkg#37669]
**Describe the bug**
The resulting static lib after vcpkg install is not linking.

**Environment**
- OS: Windows
- Compiler: Microsoft Visual 2022 17.9.4

**To Reproduce**
1. ./vcpkg install libunibreak:x64-windows
2. Try to use use the library in a C++ program in Visual Studio 2022
When linking the following function is not found : ub_get_char_eaw_class

**Additional context**
The cmakelist.txt in the port has not been updated for the 6.1 version of linunibreak.
The missing function is in the file eastasianwidthdef.c which is missing the the cmakelist.txt
Other files might me missing. The current cmakelist.txt is working for libunibreak 5.0 but not 6.x.
The https://github.com/microsoft/vcpkg/pull/37247/commits/cf9d18bef02fe21fb7b99a08c05bbf36dbf9a51f is not complete

**Comment by JonLiu1993** [comment]
@HildgenF, thanks for posting this issue, please provide your C++ project so I can reproduce your issue.

**Comment by jiayuehua** [comment]
```
 add_executable(he a.cpp)
target_link_libraries(he PUBLIC  libunibreak::libunibreak )
```
```
~/tmp$ cat a.cpp                                                                                                                                                    
#include <eastasianwidthdef.h>
int main(){
  utf32_t ch ;
  ub_get_char_eaw_class(ch);
}
```
I can reproduce the issue. But I don't know how to fix.

**Comment by dg0yt** [comment]
> I can reproduce the issue. But I don't know how to fix.

It is written in the initial post, section "Additional context": You must update `ports/libunibreak/CMakeLists.txt`.

Build systems vendored into vcpkg, uninformed automated port updates, and cursory PR review are a harmful combination.

**Comment by jiayuehua** [comment]
update CMakeLists.txt likely not work,  even change libunibreak_src and libunibreak_headers to below, still report error.

```
set(libunibreak_srcs
  src/unibreakbase.c
  src/unibreakdef.c
  src/linebreak.c
  src/linebreakdata.c
  src/linebreakdef.c
  src/eastasianwidthdef.c
  src/emojidef.c
  src/graphemebreak.c
  src/wordbreak.c
)

set(libunibreak_headers
  src/unibreakbase.h
  src/unibreakdef.h
  src/linebreak.h
  src/linebreakdef.h
  src/eastasianwidthdef.h
  src/graphemebreak.h
  src
```/wordbreak.h
)
