### ISSUE TITLE
[icu] Build failure on x64-windows

### ISSUE THREAD

**Issue by zhruith** [microsoft/vcpkg#37685]
Package: icu[core,tools]:x64-windows@74.2#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.38.33130.0
-    vcpkg-tool version: 2024-03-14-7d353e869753e5609a1f1a057df3db8fd356e49d
    vcpkg-scripts version: 898b728ed 2024-03-19 (5 days ago)

**To Reproduce**

`vcpkg install qtserialport`
**Failure logs**

```
-- Using cached icu4c-74_2-src.tgz.
-- Cleaning sources at C:/Users/zhrui/scoop/apps/vcpkg/current/buildtrees/icu/src/c-74_2-src-83138cd994.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/zhrui/scoop/apps/vcpkg/current/downloads/icu4c-74_2-src.tgz
-- Applying patch disable-escapestr-tool.patch
-- Applying patch remove-MD-from-configure.patch
-- Applying patch fix_parallel_build_on_windows.patch
-- Applying patch fix-extra.patch
-- Applying patch mingw-dll-install.patch
-- Applying patch disable-static-prefix.patch
-- Applying patch fix-win-build.patch
-- Applying patch vcpkg-cross-data.patch
-- Applying patch darwin-rpath.patch
-- Using source at C:/Users/zhrui/scoop/apps/vcpkg/current/buildtrees/icu/src/c-74_2-src-83138cd994.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Using cached msys2-autoconf-wrapper-20221207-1-any.pkg.tar.zst.
-- Using cached msys2-automake-wrapper-20221207-2-any.pkg.tar.zst.
-- Using cached msys2-binutils-2.42-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libtool-2.4.7-3-x86_64.pkg.tar.zst.
-- Using cached msys2-make-4.4.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-pkgconf-2.1.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-which-2.21-4-x86_64.pkg.tar.zst.
-- Using cached msys2-autoconf-archive-2023.02.20-1-any.pkg.tar.zst.
-- Using cached msys2-bash-5.2.026-1-x86_64.pkg.tar.zst.
-- Using cached msys2-coreutils-8.32-5-x86_64.pkg.tar.zst.
-- Using cached msys2-file-5.45-1-x86_64.pkg.tar.zst.
-- Using cached msys2-gawk-5.3.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-grep-1~3.0-6-x86_64.pkg.tar.zst.
-- Using cached msys2-gzip-1.13-1-x86_64.pkg.tar.zst.
-- Using cached msys2-diffutils-3.10-1-x86_64.pkg.tar.zst.
-- Using cached msys2-sed-4.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst.
-- Using cached msys2-autoconf2.71-2.71-3-any.pkg.tar.zst.
-- Using cached msys2-automake1.16-1.16.5-1-any.pkg.tar.zst.
-- Using cached msys2-libiconv-1.17-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libintl-0.22.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-zlib-1.3.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-tar-1.35-2-x86_64.pkg.tar.zst.
-- Using cached msys2-findutils-4.9.0-3-x86_64.pkg.tar.zst.
-- Using cached msys2-gmp-6.3.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-gcc-libs-13.2.0-2-x86_64.pkg.tar.zst.
-- Using cached msys2-libbz2-1.0.8-4-x86_64.pkg.tar.zst.
-- Using cached msys2-liblzma-5.4.6-2-x86_64.pkg.tar.zst.
-- Using cached msys2-libzstd-1.5.5-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libreadline-8.2.010-1-x86_64.pkg.tar.zst.
-- Using cached msys2-mpfr-4.2.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libpcre-8.45-4-x86_64.pkg.tar.zst.
-- Using cached msys2-m4-1.4.19-2-x86_64.pkg.tar.zst.
-- Using cached msys2-perl-5.38.2-1-x86_64.pkg.tar.zst.
-- Using cached msys2-ncurses-6.4-2-x86_64.pkg.tar.zst.
-- Using cached msys2-libxcrypt-4.4.36-1-x86_64.pkg.tar.zst.
-- Using msys root at C:/Users/zhrui/scoop/apps/vcpkg/current/downloads/tools/msys2/a4d8db9df5991f31
-- Generating configure for x64-windows
-- Finished generating configure for x64-windows
-- Using cached msys2-mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst.
-- Using msys root at C:/Users/zhrui/scoop/apps/vcpkg/current/downloads/tools/msys2/fdbea3694fb5c0d4
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
-- Installing x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/Users/zhrui/scoop/apps/vcpkg/current/downloads/tools/msys2/a4d8db9df5991f31/usr/bin/make.exe -j 9 --trace -f Makefile install DESTDIR=/C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows
    Working Directory: C:/Users/zhrui/scoop/apps/vcpkg/current/buildtrees/icu/x64-windows-dbg/
    See logs for more information:
      C:\Users\zhrui\scoop\apps\vcpkg\current\buildtrees\icu\install-x64-windows-dbg-out.log
      C:\Users\zhrui\scoop\apps\vcpkg\current\buildtrees\icu\install-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:153 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:2 (vcpkg_build_make)
  ports/icu/portfile.cmake:84 (vcpkg_install_make)
  scripts/ports.cmake:175 (include)



```
<details><summary>C:\Users\zhrui\scoop\apps\vcpkg\current\buildtrees\icu\install-x64-windows-dbg-err.log</summary>

```
make[1]: ./../src/c-74_2-src-83138cd994.clean/source/install-sh: No such file or directory
make[1]: *** [Makefile:87: install-library] Error 127
make: *** [Makefile:153: install-recursive] Error 2
make: *** Waiting for unfinished jobs....
```
</details>

<details><summary>C:\Users\zhrui\scoop\apps\vcpkg\current\buildtrees\icu\install-x64-windows-dbg-out.log</summary>

```
Makefile:153: update target 'install-recursive' due to: target is .PHONY
dot_seen=no; \
target=`echo install-recursive | sed s/-recursive//`; \
list='stubdata common i18n  io tools data extra  '; for subdir in $list; do \
  echo "/c/Users/zhrui/scoop/apps/vcpkg/current/downloads/tools/msys2/a4d8db9df5991f31/usr/bin/make[0]: Making \`$target' in \`$subdir'"; \
  if test "$subdir" = "."; then \
    dot_seen=yes; \
    local_target="$target-local"; \
  else \
    local_target="$target"; \
  fi; \
  (cd $subdir && /c/Users/zhrui/scoop/apps/vcpkg/current/downloads/tools/msys2/a4d8db9df5991f31/usr/bin/make RECURSIVE=YES $local_target) || exit; \
done; \
if test "$dot_seen" = "no"; then \
  /c/Users/zhrui/scoop/apps/vcpkg/current/downloads/tools/msys2/a4d8db9df5991f31/usr/bin/make "$target-local" || exit; \
fi
Makefile:184: update target 'install-icu' due to: target is .PHONY
/bin/sh ./../src/c-74_2-src-83138cd994.clean/source/mkinstalldirs /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/share/icu/icud/74.2/config
Makefile:364: update target 'config/icu-config.1' due to: target does not exist
cd . \
 && CONFIG_FILES=./config/icu-config.1 CONFIG_HEADERS= /bin/sh ./config.status
/c/Users/zhrui/scoop/apps/vcpkg/current/downloads/tools/msys2/a4d8db9df5991f31/usr/bin/make[0]: Making `install' in `stubdata'
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C
make[1]: Entering directory '/c/Users/zhrui/scoop/persist/vcpkg/buildtrees/icu/x64-windows-dbg/stubdata'
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop
.././../src/c-74_2-src-83138cd994.clean/source/config/mh-msys-msvc:208: update target 'icudtd.dll' due to: target does not exist
echo -n
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps
([ -e icudtd74.dll.manifest ] && ( echo Embedding manifest into icudtd74.dll && mt.exe -nologo -manifest icudtd74.dll.manifest -outputresource:"icudtd74.dll;2" && rm -rf icudtd74.dll.manifest )) || true
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current
Makefile:86: update target 'install-library' due to: target is .PHONY
/bin/sh .././../src/c-74_2-src-83138cd994.clean/source/mkinstalldirs /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/lib
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/share
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/lib
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/share/icu
./../src/c-74_2-src-83138cd994.clean/source/install-sh -c icudtd74.dll /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/lib
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/share/icu/icud
make[1]: Leaving directory '/c/Users/zhrui/scoop/persist/vcpkg/buildtrees/icu/x64-windows-dbg/stubdata'
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/share/icu/icud/74.2
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/share/icu/icud/74.2/config
/bin/sh ./../src/c-74_2-src-83138cd994.clean/source/mkinstalldirs /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/lib/icud/74.2
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/lib/icud
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/lib/icud/74.2
/bin/sh ./../src/c-74_2-src-83138cd994.clean/source/mkinstalldirs /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/../tools/icu/debug/bin
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/../tools
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/../tools/icu
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/../tools/icu/debug
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/../tools/icu/debug/bin
/bin/sh ./../src/c-74_2-src-83138cd994.clean/source/mkinstalldirs /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/../tools/icu/debug/bin
./../src/c-74_2-src-83138cd994.clean/source/install-sh -c -m 644 ./../src/c-74_2-src-83138cd994.clean/source/config/mh-msys-msvc /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/share/icu/icud/74.2/config/mh-msys-msvc
./../src/c-74_2-src-83138cd994.clean/source/install-sh -c ./../src/c-74_2-src-83138cd994.clean/source/mkinstalldirs /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/share/icu/icud/74.2/mkinstalldirs
config.status: creating ./config/icu-config.1
./../src/c-74_2-src-83138cd994.clean/source/install-sh -c ./../src/c-74_2-src-83138cd994.clean/source/install-sh /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/share/icu/icud/74.2/install-sh
/bin/sh ./../src/c-74_2-src-83138cd994.clean/source/mkinstalldirs /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/lib/pkgconfig
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/lib/pkgconfig
./../src/c-74_2-src-83138cd994.clean/source/install-sh -c -m 644 ./config/icu-uc.pc ./config/icu-i18n.pc ./config/icu-io.pc /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/lib/pkgconfig/
./../src/c-74_2-src-83138cd994.clean/source/install-sh -c -m 644 ./../src/c-74_2-src-83138cd994.clean/source/../LICENSE /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/share/icu/icud/74.2/LICENSE
./../src/c-74_2-src-83138cd994.clean/source/install-sh -c ./config/icu-config /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/../tools/icu/debug/bin/icu-config
./../src/c-74_2-src-83138cd994.clean/source/install-sh -c -m 644 ./config/Makefile.inc /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/lib/icud/74.2/Makefile.inc
./../src/c-74_2-src-83138cd994.clean/source/install-sh -c -m 644 ./config/pkgdata.inc /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/lib/icud/74.2/pkgdata.inc
cd /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/lib/icud/74.2/..; \
    rm -rf current && ln -s 74.2 current; \
    rm -f Makefile.inc && ln -s current/Makefile.inc Makefile.inc; \
    rm -f pkgdata.inc && ln -s current/pkgdata.inc pkgdata.inc
```
</details>

**Comment by Cheney-W** [comment]
I tried to reproduce this issue with the latest vcpkg, but I can't reproduce this issue in my side. I cloned a new vcpkg and installed `icu[core,tools]:x64-windows` and it could be installed successfully.
![image](https://github.com/microsoft/vcpkg/assets/38240633/507cc864-f207-407b-b7f5-b8fc0ef01e8c)

**Comment by zhruith** [comment]
It's very weird, I just install qt5,  is the reason that I'm just clean the buildtrees folders or not upgrade all of the vcpkg?

**Comment by JackBoosY** [comment]
Also please provide the configure log.

**Comment by Cheney-W** [comment]
@zhruith 
You can either clone a new vcpkg repository and then install the ports you need with `--binarysource=clear` option, or you can delete the local `downloads` folder, perform a `git pull` to update the local vcpkg source, and then reinstall the ports you need with `--binarysource=clear` option.

**Comment by zhruith** [comment]
@Cheney-W 
I use "vcpkg upgrade" to got: "All installed packages are up-to-date with the local portfile."
Use git pull to got: "Already up to date."
And clear the downloads folder.
Then use "vcpkg install --binarysource=clear qtserialport" still got BUILD_FAILED

**Comment by zhruith** [comment]
Makefile:153: update target 'install-recursive' due to: target is .PHONY
dot_seen=no; \
target=`echo install-recursive | sed s/-recursive//`; \
list='stubdata common i18n  io tools data extra  '; for subdir in $list; do \
  echo "/c/Users/zhrui/scoop/apps/vcpkg/current/downloads/tools/msys2/a4d8db9df5991f31/usr/bin/make[0]: Making \`$target' in \`$subdir'"; \
  if test "$subdir" = "."; then \
    dot_seen=yes; \
    local_target="$target-local"; \
  else \
    local_target="$target"; \
  fi; \
  (cd $subdir && /c/Users/zhrui/scoop/apps/vcpkg/current/downloads/tools/msys2/a4d8db9df5991f31/usr/bin/make RECURSIVE=YES $local_target) || exit; \
done; \
if test "$dot_seen" = "no"; then \
  /c/Users/zhrui/scoop/apps/vcpkg/current/downloads/tools/msys2/a4d8db9df5991f31/usr/bin/make "$target-local" || exit; \
fi
Makefile:184: update target 'install-icu' due to: target is .PHONY
/bin/sh ./../src/c-74_2-src-83138cd994.clean/source/mkinstalldirs /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/share/icu/icud/74.2/config
Makefile:364: update target 'config/icu-config.1' due to: target does not exist
cd . \
 && CONFIG_FILES=./config/icu-config.1 CONFIG_HEADERS= /bin/sh ./config.status
/c/Users/zhrui/scoop/apps/vcpkg/current/downloads/tools/msys2/a4d8db9df5991f31/usr/bin/make[0]: Making `install' in `stubdata'
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C
make[1]: Entering directory '/c/Users/zhrui/scoop/persist/vcpkg/buildtrees/icu/x64-windows-dbg/stubdata'
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui
.././../src/c-74_2-src-83138cd994.clean/source/config/mh-msys-msvc:208: update target 'icudtd.dll' due to: target does not exist
echo -n
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps
([ -e icudtd74.dll.manifest ] && ( echo Embedding manifest into icudtd74.dll && mt.exe -nologo -manifest icudtd74.dll.manifest -outputresource:"icudtd74.dll;2" && rm -rf icudtd74.dll.manifest )) || true
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current
Makefile:86: update target 'install-library' due to: target is .PHONY
/bin/sh .././../src/c-74_2-src-83138cd994.clean/source/mkinstalldirs /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/lib
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/share
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/lib
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/share/icu
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/share/icu/icud
./../src/c-74_2-src-83138cd994.clean/source/install-sh -c icudtd74.dll /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/lib
make[1]: Leaving directory '/c/Users/zhrui/scoop/persist/vcpkg/buildtrees/icu/x64-windows-dbg/stubdata'
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/share/icu/icud/74.2
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/share/icu/icud/74.2/config
/bin/sh ./../src/c-74_2-src-83138cd994.clean/source/mkinstalldirs /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/lib/icud/74.2
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/lib/icud
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/lib/icud/74.2
/bin/sh ./../src/c-74_2-src-83138cd994.clean/source/mkinstalldirs /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/../tools/icu/debug/bin
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/../tools
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/../tools/icu
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/../tools/icu/debug
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/../tools/icu/debug/bin
/bin/sh ./../src/c-74_2-src-83138cd994.clean/source/mkinstalldirs /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/../tools/icu/debug/bin
./../src/c-74_2-src-83138cd994.clean/source/install-sh -c -m 644 ./../src/c-74_2-src-83138cd994.clean/source/config/mh-msys-msvc /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/share/icu/icud/74.2/config/mh-msys-msvc
./../src/c-74_2-src-83138cd994.clean/source/install-sh -c ./../src/c-74_2-src-83138cd994.clean/source/mkinstalldirs /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/share/icu/icud/74.2/mkinstalldirs
config.status: creating ./config/icu-config.1
./../src/c-74_2-src-83138cd994.clean/source/install-sh -c ./../src/c-74_2-src-83138cd994.clean/source/install-sh /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/share/icu/icud/74.2/install-sh
/bin/sh ./../src/c-74_2-src-83138cd994.clean/source/mkinstalldirs /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/lib/pkgconfig
mkdir /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/lib/pkgconfig
./../src/c-74_2-src-83138cd994.clean/source/install-sh -c -m 644 ./config/icu-uc.pc ./config/icu-i18n.pc ./config/icu-io.pc /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/lib/pkgconfig/
./../src/c-74_2-src-83138cd994.clean/source/install-sh -c -m 644 ./../src/c-74_2-src-83138cd994.clean/source/../LICENSE /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/share/icu/icud/74.2/LICENSE
./../src/c-74_2-src-83138cd994.clean/source/install-sh -c ./config/icu-config /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/../tools/icu/debug/bin/icu-config
./../src/c-74_2-src-83138cd994.clean/source/install-sh -c -m 644 ./config/Makefile.inc /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/lib/icud/74.2/Makefile.inc
./../src/c-74_2-src-83138cd994.clean/source/install-sh -c -m 644 ./config/pkgdata.inc /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/lib/icud/74.2/pkgdata.inc
cd /C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows/C/Users/zhrui/scoop/apps/vcpkg/current/installed/x64-windows/debug/lib/icud/74.2/..; \
    rm -rf current && ln -s 74.2 current; \
    rm -f Makefile.inc && ln -s current/Makefile.inc Makefile.inc; \
    rm -f pkgdata.inc && ln -s current/pkgdata.inc pkgdata.inc

**Comment by zhruith** [comment]
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
-- Installing x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/Users/zhrui/scoop/apps/vcpkg/current/downloads/tools/msys2/a4d8db9df5991f31/usr/bin/make.exe -j 9 --trace -f Makefile install DESTDIR=/C/Users/zhrui/scoop/apps/vcpkg/current/packages/icu_x64-windows
    Working Directory: C:/Users/zhrui/scoop/apps/vcpkg/current/buildtrees/icu/x64-windows-dbg/
    See logs for more information:
      C:\Users\zhrui\scoop\apps\vcpkg\current\buildtrees\icu\install-x64-windows-dbg-out.log
      C:\Users\zhrui\scoop\apps\vcpkg\current\buildtrees\icu\install-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:153 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:2 (vcpkg_build_make)
  ports/icu/portfile.cmake:84 (vcpkg_install_make)
  scripts/ports.cmake:175 (include)


error: building icu:x64-windows failed with: BUILD_FAILED
Elapsed time to handle icu:x64-windows: 4.5 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+icu
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[icu]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2FUsers%2Fzhrui%2Fscoop%2Fapps%2Fvcpkg%2Fcurrent%2Finstalled%2Fvcpkg%2Fissue_body.md
You can also submit an issue by running (GitHub CLI must be installed):
  gh issue create -R microsoft/vcpkg --title "[icu] Build failure on x64-windows" --body-file C:/Users/zhrui/scoop/apps/vcpkg/current/installed/vcpkg/issue_body.md

**Comment by dg0yt** [comment]
FTR we have repeatedly seen issues when using scoop.

**Comment by zhruith** [comment]
All right, I give up
