### ISSUE TITLE
[tensorflow] Build failure on x64-linux

### ISSUE THREAD

**Issue by boudarbala** [microsoft/vcpkg#37684]
Package: tensorflow:x64-linux@2.10.0

**Host Environment**

- Host: x64-linux
- Compiler: GNU 11.4.0
-    vcpkg-tool version: 2024-02-07-8a83681f921b10d86ae626fd833c253f4f8c355b
    vcpkg-scripts version: a34c873a9 2024-03-22 (2 days ago)

**To Reproduce**

`vcpkg install tensorflow`
**Failure logs**

```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/python3 -m venv --symlinks /home/ahmed/vcpkg/buildtrees/tensorflow/x64-linux-venv
    Working Directory: /home/ahmed/vcpkg/buildtrees/tensorflow
    Error code: 1
    See logs for more information:
      /home/ahmed/vcpkg/buildtrees/tensorflow/prerequisites-venv-x64-linux-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/tensorflow-common/tensorflow-common.cmake:59 (vcpkg_execute_required_process)
  ports/tensorflow/portfile.cmake:5 (include)
  scripts/ports.cmake:175 (include)



```
<details><summary>/home/ahmed/vcpkg/buildtrees/tensorflow/prerequisites-venv-x64-linux-out.log</summary>

```
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.10-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: /home/ahmed/vcpkg/buildtrees/tensorflow/x64-linux-venv/bin/python3
```
</details>

**Comment by LilyWangLL** [comment]
> The virtual environment was not created successfully because ensurepip is not
> available.  On Debian/Ubuntu systems, you need to install the python3-venv
> package using the following command.
> 
>     apt install python3.10-venv

Please install `python3.10-venv`.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
