### ISSUE TITLE
Can't install opencv 

### ISSUE THREAD

**Issue by stiv-yakovenko** [Microsoft/vcpkg#3768]
how can I install opencv?
mscv2015, cmake 3.12.0:

> [1/2] cmd /c "cd .. && "C:/Program Files/CMake/bin/cmake.exe" "C:/Users/steve/Projects/vcpkg-master/buildtrees/libpng/src/v1.6.34-8b0008e7a8" "-DPNG_STATIC=OFF" "-DPNG_SHARED=ON" "-DPNG_TESTS=OFF" "-DSKIP_INSTALL_PROGRAMS=ON" "-DSKIP_INSTALL_EXECUTABLES=ON" "-DSKIP_INSTALL_FILES=ON" "-DSKIP_INSTALL_SYMLINK=ON" "-DCMAKE_MAKE_PROGRAM=C:/Users/steve/Projects/vcpkg-master/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/steve/Projects/vcpkg-master/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/steve/Projects/vcpkg-master/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/Users/steve/Projects/vcpkg-master/packages/libpng_x86-windows""
> FAILED: ../CMakeCache.txt 
> cmd /c "cd .. && "C:/Program Files/CMake/bin/cmake.exe" "C:/Users/steve/Projects/vcpkg-master/buildtrees/libpng/src/v1.6.34-8b0008e7a8" "-DPNG_STATIC=OFF" "-DPNG_SHARED=ON" "-DPNG_TESTS=OFF" "-DSKIP_INSTALL_PROGRAMS=ON" "-DSKIP_INSTALL_EXECUTABLES=ON" "-DSKIP_INSTALL_FILES=ON" "-DSKIP_INSTALL_SYMLINK=ON" "-DCMAKE_MAKE_PROGRAM=C:/Users/steve/Projects/vcpkg-master/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/steve/Projects/vcpkg-master/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/steve/Projects/vcpkg-master/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/Users/steve/Projects/vcpkg-master/packages/libpng_x86-windows""
> -- The ASM compiler identification is MSVC
> -- Found assembler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe
> -- The C compiler identification is MSVC 19.0.24215.1
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe -- broken
> CMake Error at C:/Program Files/CMake/share/cmake-3.12/Modules/CMakeTestCCompiler.cmake:52 (message):
>   The C compiler
> 
>     "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe"
> 
>   is not able to compile a simple test program.
> 
>   It fails with the following output:
> 
>     Change Dir: C:/Users/steve/Projects/vcpkg-master/buildtrees/libpng/x86-windows-rel/CMakeFiles/CMakeTmp
>     
>     Run Build Command:"C:/Users/steve/Projects/vcpkg-master/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "cmTC_2b052"
>     [1/2] Building C object CMakeFiles\cmTC_2b052.dir\testCCompiler.c.obj
>     [2/2] Linking C executable cmTC_2b052.exe
>     FAILED: cmTC_2b052.exe 
>     cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_2b052.dir --manifests  -- C:\PROGRA~2\MICROS~1.0\VC\bin\AMD64_~2\link.exe /nologo CMakeFiles\cmTC_2b052.dir\testCCompiler.c.obj  /out:cmTC_2b052.exe /implib:cmTC_2b052.lib /pdb:cmTC_2b052.pdb /version:0.0  /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
>     RC Pass 1: command "rc /foCMakeFiles\cmTC_2b052.dir/manifest.res CMakeFiles\cmTC_2b052.dir/manifest.rc" failed (exit code 0) with the following output:
>     Не удается найти указанный файл
>     ninja: build stopped: subcommand failed.
>     
> 
>   
> 
>   CMake will not be able to correctly generate this project.
> Call Stack (most recent call first):
>   CMakeLists.txt:34 (project)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "C:/Users/steve/Projects/vcpkg-master/buildtrees/libpng/x86-windows-rel/CMakeFiles/CMakeOutput.log".
> See also "C:/Users/steve/Projects/vcpkg-master/buildtrees/libpng/x86-windows-rel/CMakeFiles/CMakeError.log".
> [2/2] cmd /c "cd ../../x86-windows-dbg && "C:/Program Files/CMake/bin/cmake.exe" "C:/Users/steve/Projects/vcpkg-master/buildtrees/libpng/src/v1.6.34-8b0008e7a8" "-DPNG_STATIC=OFF" "-DPNG_SHARED=ON" "-DPNG_TESTS=OFF" "-DSKIP_INSTALL_PROGRAMS=ON" "-DSKIP_INSTALL_EXECUTABLES=ON" "-DSKIP_INSTALL_FILES=ON" "-DSKIP_INSTALL_SYMLINK=ON" "-DCMAKE_MAKE_PROGRAM=C:/Users/steve/Projects/vcpkg-master/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/steve/Projects/vcpkg-master/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/steve/Projects/vcpkg-master/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-DSKIP_INSTALL_HEADERS=ON" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/Users/steve/Projects/vcpkg-master/packages/libpng_x86-windows/debug""
> FAILED: ../../x86-windows-dbg/CMakeCache.txt 
> cmd /c "cd ../../x86-windows-dbg && "C:/Program Files/CMake/bin/cmake.exe" "C:/Users/steve/Projects/vcpkg-master/buildtrees/libpng/src/v1.6.34-8b0008e7a8" "-DPNG_STATIC=OFF" "-DPNG_SHARED=ON" "-DPNG_TESTS=OFF" "-DSKIP_INSTALL_PROGRAMS=ON" "-DSKIP_INSTALL_EXECUTABLES=ON" "-DSKIP_INSTALL_FILES=ON" "-DSKIP_INSTALL_SYMLINK=ON" "-DCMAKE_MAKE_PROGRAM=C:/Users/steve/Projects/vcpkg-master/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/steve/Projects/vcpkg-master/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/steve/Projects/vcpkg-master/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-DSKIP_INSTALL_HEADERS=ON" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/Users/steve/Projects/vcpkg-master/packages/libpng_x86-windows/debug""
> -- The ASM compiler identification is MSVC
> -- Found assembler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe
> -- The C compiler identification is MSVC 19.0.24215.1
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe -- broken
> CMake Error at C:/Program Files/CMake/share/cmake-3.12/Modules/CMakeTestCCompiler.cmake:52 (message):
>   The C compiler
> 
>     "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe"
> 
>   is not able to compile a simple test program.
> 
>   It fails with the following output:
> 
>     Change Dir: C:/Users/steve/Projects/vcpkg-master/buildtrees/libpng/x86-windows-dbg/CMakeFiles/CMakeTmp
>     
>     Run Build Command:"C:/Users/steve/Projects/vcpkg-master/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "cmTC_42454"
>     [1/2] Building C object CMakeFiles\cmTC_42454.dir\testCCompiler.c.obj
>     [2/2] Linking C executable cmTC_42454.exe
>     FAILED: cmTC_42454.exe 
>     cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_42454.dir --manifests  -- C:\PROGRA~2\MICROS~1.0\VC\bin\AMD64_~2\link.exe /nologo CMakeFiles\cmTC_42454.dir\testCCompiler.c.obj  /out:cmTC_42454.exe /implib:cmTC_42454.lib /pdb:cmTC_42454.pdb /version:0.0  /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
>     RC Pass 1: command "rc /foCMakeFiles\cmTC_42454.dir/manifest.res CMakeFiles\cmTC_42454.dir/manifest.rc" failed (exit code 0) with the following output:
>     Не удается найти указанный файл
>     ninja: build stopped: subcommand failed.
>     
> 
>   
> 
>   CMake will not be able to correctly generate this project.
> Call Stack (most recent call first):
>   CMakeLists.txt:34 (project)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "C:/Users/steve/Projects/vcpkg-master/buildtrees/libpng/x86-windows-dbg/CMakeFiles/CMakeOutput.log".
> See also "C:/Users/steve/Projects/vcpkg-master/buildtrees/libpng/x86-windows-dbg/CMakeFiles/CMakeError.log".
> ninja: build stopped: subcommand failed.
> 

and this:

> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
>     Command failed: ninja;-v
>     Working Directory: C:/Users/steve/Projects/vcpkg-master/buildtrees/libpng/x86-windows-rel/vcpkg-parallel-configure
>     See logs for more information:
>       C:\Users\steve\Projects\vcpkg-master\buildtrees\libpng\config-x86-windows-out.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_configure_cmake.cmake:237 (vcpkg_execute_required_process)
>   ports/libpng/portfile.cmake:26 (vcpkg_configure_cmake)
>   scripts/ports.cmake:72 (include)
> 
> 
> Error: Building package libpng:x86-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: libpng:x86-windows
>   Vcpkg version: 0.0.113-nohash
>

**Comment by stiv-yakovenko** [comment]
Ok, here is how you fix it:

![image](https://user-images.githubusercontent.com/4163254/41813176-cad7a8b2-775a-11e8-9dc5-0d35866e7f27.png)

modify msvc 2015 installation and set this flag

**Comment by PhoebeHui** [comment]
Looks the issue fixed.
