### ISSUE TITLE
[libcoro] It is unclear how to use this port

### ISSUE THREAD

**Issue by dasmysh** [microsoft/vcpkg#37697]
### Is your feature request related to a problem? Please describe.

I am trying to use libcoro in one of my projects, but due to the lack of a `libcoroConfig.cmake` file can not perform a `find_package` in CMake. I am not sure if I am overseeing something here but in the current state the port feels kind of incomplete.

### Proposed solution

Provide a `libcoroConfig.cmake` file that exposes a target that can be used to link against in CMake.

**Comment by dasmysh** [comment]
I am currently trying to figure out how to best fix this to create a PR. I guess it is best to create these files during cmake install. So I will try to fix this in the libcoro repository and first create a PR there, and then probably (depending on how fast that gets merged) provide a PR with a patch file for what I did there in vcpkg.

**Comment by LilyWangLL** [comment]
`libcoro` provide the pc file, you could use it as the following usage:
```
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(test REQUIRED IMPORTED_TARGET libcoro)
    target_link_libraries(main PkgConfig::test)
```

**Comment by dasmysh** [comment]
That looks like a great option, but I think it would be nice to have usage instructions for that. I created a pull request that adds those instructions as a draft. Would be great to get some feedback on it.
