### ISSUE TITLE
[gdal] Build error on x64-linux

### ISSUE THREAD

**Issue by ekke23** [microsoft/vcpkg#37694]
Linux Mint 21.3 Cinnamon
vcpkg install gdal
"I expected to have gdal compiled and installed"
The actual outcome: "See logs below"
------------------------------------

-- Downloading https://github.com/OSGeo/gdal/archive/v3.8.4.tar.gz -> OSGeo-gdal-v3.8.4.tar.gz...
-- Extracting source */vcpkg/downloads/OSGeo-gdal-v3.8.4.tar.gz
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: */vcpkg/downloads/tools/cmake-3.27.1-linux/cmake-3.27.1-linux-x86_64/bin/cmake -E tar xjf */vcpkg/downloads/OSGeo-gdal-v3.8.4.tar.gz

------------------------------------
*/vcpkg/buildtrees/gdal/extract-err.log 

CMake Error: Problem with archive_write_header(): Can't create 'gdal-3.8.4/autotest/gdrivers/data/ogcapi/request_collections_SRTM_ViewFinderPanorama_coverage_f_tif_subset_Lon_-9.8437_-8.4375__Lat_53.0627_54.4689__scaleSize_Lon_256__Lat_256_.http_data'
CMake Error: Current file: gdal-3.8.4/autotest/gdrivers/data/ogcapi/request_collections_SRTM_ViewFinderPanorama_coverage_f_tif_subset_Lon_-9.8437_-8.4375__Lat_53.0627_54.4689__scaleSize_Lon_256__Lat_256_.http_data
CMake Error: Problem extracting tar:*vcpkg/downloads/OSGeo-gdal-v3.8.4.tar.gz

------------------------------------
It seems that the tar command fails.

**Comment by dg0yt** [comment]
You hide the full paths. Is this a WSL scenario? The port is not generally broken, but the filepaths in `autotest`  are very long and known to create problems. The port removes the dir right after extraction because even `vcpkg clean` can't handle it...

**Comment by ekke23** [comment]
No , Linux mint.

**Comment by ekke23** [comment]
It turn out that encryption on the home folder caused this error. 
So from my side you can close this issue.
