### ISSUE TITLE
[vcpkg-tool-meson] build failure

### ISSUE THREAD

**Issue by Cazadorro** [microsoft/vcpkg#37693]
### Operating system

centos 7 linux
 

### Compiler

gcc-11

### Steps to reproduce the behavior

```Shell
./vcpkg install vcpkg-tool-meson --only-downloads

./vcpkg install vcpkg-tool-meson --no-downloads
```

### Failure logs

```
Installing 1/1 vcpkg-tool-meson:x64-linux@1.3.2#1...
Building vcpkg-tool-meson:x64-linux@1.3.2#1...
/home/user/Documents/vcpkg_deployment/vcpkg_no_download/buildtrees/versioning_/versions/vcpkg-tool-meson/17b86f3a18ad63659d4dfbafc194969279a7a4f0: info: installing overlay port from here
-- Installing: /home/user/Documents/vcpkg_deployment/vcpkg_no_download/packages/vcpkg-tool-meson_x64-linux/share/vcpkg-tool-meson/copyright
-- Found Python version '3.8.13 at /opt/rh/rh-python38/root/usr/bin/python3'
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:212 (message):
  Downloads are disabled, but
  '/home/user/Documents/vcpkg_deployment/vcpkg_no_download/downloads/meson-614d436232d3a86518164cbe2b8af12db3bde009.tar.gz'
  does not exist.
Call Stack (most recent call first):
  packages/vcpkg-tool-meson_x64-linux/share/vcpkg-tool-meson/vcpkg-port-config.cmake:38 (vcpkg_download_distfile)
  buildtrees/versioning_/versions/vcpkg-tool-meson/17b86f3a18ad63659d4dfbafc194969279a7a4f0/portfile.cmake:39 (include)
  scripts/ports.cmake:175 (include)
```

### Additional context

Trying to test --only-downloads and --no-downloads.  This has worked in previous versions of VCPKG, doesn't work now. Works fine when normal install process is used.  The meson download missing *is* installed if only-downloads isn't used.

**Comment by Osyotr** [comment]
Maybe #37585?

**Comment by Cazadorro** [comment]
No idea, hopefully, but I personally can't test this anymore since I found out that libsystemd is irrevocably broken with centos 7 because it requires a higher kernel version, and older versions don't exist in vcpkg, meaning I have to stick with older versions of vcpkg anyway.  OpenCV now cannot work on Centos 7/Redhat 7 since libsystemd's introduction to vcpkg 6 months ago.

**Comment by Osyotr** [comment]
> No idea, hopefully, but I personally can't test this anymore since I found out that libsystemd is irrevocably broken with centos 7 because it requires a higher kernel version headers, and older versions don't exist in vcpkg, meaning I have to stick with older versions of vcpkg anyway. OpenCV now cannot work on Centos 7/Redhat 7 since libsystemd's introduction to vcpkg 6 months ago.

How did it work before? Maybe create empty overlay for `libsystemd` (and probably `libmount`)?

**Comment by dg0yt** [comment]
> ~~~
> -- Found Python version '3.8.13 at /opt/rh/rh-python38/root/usr/bin/python3'

Is this recent enough for meson?

> OpenCV now cannot work on Centos 7/Redhat 7 since libsystemd's introduction to vcpkg 6 months ago.

I warned about side effects...
But you can replace the vcpkg port with an empty overlay port.

**Comment by Neumann-A** [comment]
@BillyONeal Do I need to include the `vcpkg-port-config.cmake` in the portfile of the installing port to make `--only-downloads` work?

**Comment by dg0yt** [comment]
> Do I need to include the `vcpkg-port-config.cmake` in the portfile of the installing port to make `--only-downloads` work?

AFAICT You need "to make `--only-downloads` work". This means to *invoke* code for downloading. 

I guess the current version stops at 
~~~
vcpkg_execute_required_process(COMMAND "${PYTHON3}" --version
            WORKING_DIRECTORY "${CURRENT_BUILDTREES_DIR}"
            LOGNAME "python3-version-${TARGET_TRIPLET}")
~~~

**Comment by BillyONeal** [comment]
Yeah, it seems like that could get `ALLOW_IN_DOWNLOAD_MODE`

**Comment by Neumann-A** [comment]
opened #37768 to reorder the code and put the download before the version check of python.
