### ISSUE TITLE
tbb build fails

### ISSUE THREAD

**Issue by degski** [microsoft/vcpkg#3771]
The build of tbb:x64-windows fails, because ...\vcpkg\buildtrees\tbb\src\2018_U4-aac0bf0e71\build\vs2013\makefile.sln contains an Optimization value of "MaxSpeedHighLevel". This value is a value intended for consumption by icc. Opening that makefile.sln in VS2017 and changing the values to the correct one (/Ox I pressume) makes the library build without fail.

[build-x64-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/2132002/build-x64-windows-rel-out.log)

**Comment by PhoebeHui** [comment]
@degski, could you have a try again? tbb:x64-windows installed successfully now.
@Praying, tbb can be used on Linux now, it has merged to master by commit https://github.com/Microsoft/vcpkg/commit/6af7c99555a03235994bc6dfe495ad07369088c6#diff-f5c9d1feb223698db086fe054c247be4

PS F:\vcpkg\src> ./vcpkg version
Vcpkg package management program version 2018.11.23-nohash

See LICENSE.txt for license information.
PS F:\vcpkg\src> ./vcpkg install tbb:x64-windows
The following packages will be built and installed:
    tbb[core]:x64-windows
Starting package 1/1: tbb:x64-windows
Building package tbb[core]:x64-windows...
-- Downloading https://github.com/01org/tbb/archive/2019_U3.tar.gz...
-- Extracting source F:/VCPKG/src/downloads/01org-tbb-2019_U3.tar.gz
-- Using source at F:/VCPKG/src/buildtrees/tbb/src/2019_U3-6dcad37699
-- Building build/vs2013/makefile.sln for Release
-- Building build/vs2013/makefile.sln for Debug
-- Performing CMake integration test
-- Performing post-build validation
-- Performing post-build validation done
Building package tbb[core]:x64-windows... done
Installing package tbb[core]:x64-windows...
Installing package tbb[core]:x64-windows... done
Elapsed time for package tbb:x64-windows: 1.836 min

Total elapsed time: 1.836 min

The package tbb provides CMake targets:

    find_package(TBB CONFIG REQUIRED)
    target_link_libraries(main PRIVATE TBB::tbb)

**Comment by degski** [comment]
@PhoebeHui 

No, still the same problem.

    4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(423,5): error : Element <Optimization> has an invalid value of "MaxSpeedHighLevel".

[build-x64-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/2830883/build-x64-windows-rel-out.log)

**Comment by PhoebeHui** [comment]
@degski, 

I checked tbb latest revision 2019_U7.  ...\build\vs2013\makefile.sln doesn't contains an Optimization value of "MaxSpeedHighLevel", and opening makefile.sln in VS2017, the Optimization default value is Disabled(/Od). I guess 'MaxSpeedHighLevel' value is invalid, see all the value for Optimization:https://docs.microsoft.com/en-us/cpp/build/reference/o-options-optimize-code?view=vs-2019.

**Comment by degski** [comment]
@PhoebeHui 

I grepped the Visual Studio installation directory for `MaxSpeedHighLevel`, and in `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\qvdaamts.0rh`, I found a file named `ICProperties.xml`, which contains that value. As I said in the original post, this is a value used by `icc`, the intel compiler. 

I have installed on my system both `tbb` and `mkl` from the original [intel distribution](https://software.intel.com/en-us/tbb), which during the install does install a Visual Studio system integration. Apparently, that messes with the `vcpkg` build.

**Comment by PhoebeHui** [comment]
@degski, thanks for the details!

After installing ParallelStudio(IntelC++Compiler), I find C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\qvdaamts.0rh\ICProperties.xml finally, however, I'm not familiar with it. I think the value might need to update.

@ras0219-msft, could you help have a look?

Snip code in ICProperties.xml:
```
 <Tool Name="Compiler">
      <Property Name="Optimization" Type="enum" Mixed="true">
        <Value Num="1000" String="MaxSpeedHighLevel"/>
      </Property>
      <Property Name="EnableEnhancedInstructionSet" Type="enum" Mixed="true">
        <Value Num="1000" String="StreamingSIMDExtensions3"/>
        <Value Num="1001" String="NoExtensions"/>
        <Value Num="1002" String="AdvancedVectorExtensions"/>
        <Value Num="1003" String="AdvancedVectorExtensions2"/>
      </Property>
    ...
<Tool>
```

[ICProperties.txt](https://github.com/microsoft/vcpkg/files/3471736/ICProperties.txt)

**Comment by degski** [comment]
@PhoebeHui The thing is that the value is correct for `icc`, it's the `/O2` equivalent for `icc`. The thing is of course that it should not show up in a `.sln` if it's not gonna be built with `icc`. The problem must be in the `Intel VS Integration`, it seems to assume that `icc` is installed, while this is not a pre-requisite of any of the `Intel Performance Libraries.

**Comment by PhoebeHui** [comment]
@degski, yes, it seems that the issue in the Intel VS Integration, I'm not sure what VCPKG could do here. I closed this issue now, please reopen it if you expect some action from vcpkg.
