### ISSUE TITLE
[libgnutls] build failure

### ISSUE THREAD

**Issue by misha4gps** [microsoft/vcpkg#37728]
### Operating system

Windows 11 arm64

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
.\vcpkg.exe install libgnutls:arm64-windows-static
```

### Failure logs

Computing installation plan...
libgnutls is only supported on '!windows | mingw', which does not match arm64-windows-static. This usually means that there are known build failures, or runtime problems, when building other platforms. To ignore this and attempt to build libgnutls anyway, rerun vcpkg with `--allow-unsupported`.

### Additional context

dev environment:
- MSVC v143 - VS 2022 C++ x64/x86 build tools
- Windows 11 SDK (10.0.22621.0)
- C++ CMake tools for Windows
- MSVC v143 - VS 2022 C++ ARM64/ARM64EC build tools

**Comment by dg0yt** [comment]
Not a bug. `libgnutls` doesn't support MSVC. 
But you might use `shiftmedia-libgnutls`.
