### ISSUE TITLE
[libpq] Build error on x64-win-llvm

### ISSUE THREAD

**Issue by Arndt-MBE** [microsoft/vcpkg#37721]
After pulling and upgrading vcpkg on 2024/03/25, `libpq` can no longer be compiled for `x64-win-llvm`.
I use [triplets](https://github.com/Neumann-A/my-vcpkg-triplets) and [ports](https://github.com/Neumann-A/my-vcpkg-ports) by @Neumann-A, checked out to sibling folders of vcpkg.

According to [build-libpq-x64-win-llvm-dbg-out.log](https://github.com/microsoft/vcpkg/files/14758538/build-libpq-x64-win-llvm-dbg-out.log), there seems to be a Visual Studio project configuration involved, which insists to use `clang-cl` v12 from a Visual Studio installation.
I use an LLVM (v18) installation by Chocolatey, which used to work fine with the mentioned triplets, and a several weeks older state of vcpkg.

**Operating system:** Windows 11 [Version 10.0.22631.3296]

**Installed Microsoft tool chain:** Visual Studio Build Tools 2019 v16.11.34 with `clang-cl for v142 build tools`, but without its Clang v12 installation.

**Reproduction:**
`vcpkg.exe --overlay-ports=..\vcpkg-ports --overlay-triplets=..\vcpkg-triplets install libpq:x64-win-llvm`

**Result:**
```
Computing installation plan...
The following packages will be built and installed:
    libpq[core,lz4,openssl,zlib]:x64-win-llvm@16.2#1
Detecting compiler hash for triplet x64-win-llvm...
Restored 0 package(s) from C:\Users\Arndt\AppData\Local\vcpkg\archives in 1.21 ms. Use --debug to see more details.
Installing 1/1 libpq[core,lz4,openssl,zlib]:x64-win-llvm@16.2#1...
Building libpq[core,lz4,openssl,zlib]:x64-win-llvm@16.2#1...
-- [OVERLAY] Loading triplet configuration from: C:\Code\ttnode\vcpkg-triplets\x64-win-llvm.cmake
-- Using cached postgresql-16.2.tar.bz2.
-- Cleaning sources at C:/Code/vcpkg/buildtrees/libpq/src/tgresql-16-b00fbb6ff2.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Code/vcpkg/downloads/postgresql-16.2.tar.bz2
-- Applying patch unix/installdirs.patch
-- Applying patch unix/fix-configure.patch
-- Applying patch unix/single-linkage.patch
-- Applying patch unix/no-server-tools.patch
-- Applying patch unix/mingw-install.patch
-- Applying patch unix/python.patch
-- Applying patch windows/macro-def.patch
-- Applying patch windows/win_bison_flex.patch
-- Applying patch windows/msbuild.patch
-- Applying patch windows/spin_delay.patch
-- Applying patch android/unversioned_so.patch
-- Using source at C:/Code/vcpkg/buildtrees/libpq/src/tgresql-16-b00fbb6ff2.clean
-- Getting CMake variables for x64-win-llvm
-- Building x64-win-llvm-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/Code/vcpkg/downloads/tools/perl/5.38.0.1/perl/bin/perl.exe build.pl DEBUG libpq
    Working Directory: C:/Code/vcpkg/buildtrees/libpq/x64-win-llvm-dbg/src/tools/msvc
    Error code: 1
    See logs for more information:
      C:\Code\vcpkg\buildtrees\libpq\build-libpq-x64-win-llvm-dbg-out.log

Call Stack (most recent call first):
  ports/libpq/build-msvc.cmake:67 (vcpkg_execute_required_process)
  ports/libpq/portfile.cmake:74 (build_msvc)
  scripts/ports.cmake:175 (include)


error: building libpq:x64-win-llvm failed with: BUILD_FAILED
Elapsed time to handle libpq:x64-win-llvm: 1.2 min
```

**Comment by Neumann-A** [comment]
Looks like you forgot to set `LLVMToolsVersion` in the parent environment?

**Comment by Arndt-MBE** [comment]
Thank you for the quick reply, @Neumann-A 

I am almost sure that was not required before, since the Chocolatey installation of LLVM (in `C:\Program Files\LLVM`) is in the path anyway. (I try to avoid user-managed system-wide environment variables as a requirement to the development environment like hell.)
But of course I tried to set the variables:
```
> clang --version
clang version 18.1.0rc
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
> echo %LLVMInstallDir% %LLVMToolsVersion%
"C:\Program Files\LLVM" 18
```
**Result:**
```
Detecting compiler hash for triplet x64-win-llvm...
error: while detecting compiler information:

CMake Error at C:/Code/ttnode/vcpkg-triplets/x64-win-llvm/extra_setup.cmake:32 (message):
  Unable to find LLVM installation.  Please define environment variable
  'LLVMInstallDir' and 'LLVMToolsVersion'
Call Stack (most recent call first):
  C:/Code/ttnode/vcpkg-triplets/x64-win-llvm.cmake:22 (include)
  scripts/ports.cmake:158 (include)

error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.
```
So, no effect, it seems.

**Comment by Arndt-MBE** [comment]
According to the debug output of `vcpkg.exe --debug-env --debug --overlay-ports=..\vcpkg-ports --overlay-triplets=..\vcpkg-triplets --x-cmake-args=--debug install libpq:x64-win-llvm`, Clang v18 is found indeed:
```
[DEBUG] -- VCPKG_USE_COMPILER_FOR_LINKAGE:OFF
[DEBUG] -- The C compiler identification is Clang 18.1.0 with MSVC-like command-line
[DEBUG] -- The CXX compiler identification is Clang 18.1.0 with MSVC-like command-line
[DEBUG] #COMPILER_HASH#0e32ae4e1b0d47049866a52ff4eb81be29ce9804
[DEBUG] #COMPILER_C_HASH#7fd9e70b5c1a79a7d43bec0eb6e1de4b6dd10157
[DEBUG] #COMPILER_C_VERSION#18.1.0
[DEBUG] #COMPILER_C_ID#Clang
[DEBUG] #COMPILER_C_PATH#C:/Program Files/LLVM/bin/clang-cl.exe
[DEBUG] #COMPILER_CXX_HASH#7fd9e70b5c1a79a7d43bec0eb6e1de4b6dd10157
[DEBUG] #COMPILER_CXX_VERSION#18.1.0
[DEBUG] #COMPILER_CXX_ID#Clang
[DEBUG] #COMPILER_CXX_PATH#C:/Program Files/LLVM/bin/clang-cl.exe
[DEBUG] -- Configuring done (1.9s)
[DEBUG] -- Generating done (0.0s)
[DEBUG] CMake Warning:
[DEBUG]   Manually-specified variables were not used by the project:
[DEBUG]
[DEBUG]     BUILD_SHARED_LIBS
[DEBUG]     CMAKE_INSTALL_BINDIR
[DEBUG]     CMAKE_INSTALL_LIBDIR
[DEBUG]     CMAKE_POLICY_DEFAULT_CMP0012
[DEBUG]     CMAKE_POLICY_DEFAULT_CMP0056
[DEBUG]     _VCPKG_ROOT_DIR
[DEBUG]
[DEBUG]
[DEBUG] -- Build files have been written to: C:/Code/vcpkg/buildtrees/detect_compiler/x64-win-llvm-rel
```
But that does not change the error or the resulting log file in any way.
The log file repeatedly contains error messages of the following kind:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.ClangCl.Common.targets(74,5): error MSB8073: Die LLVM-Toolsetversion 12.0.0 wurde nicht gefunden. Der Ordner "'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\Llvm\x64\lib\clang\12.0.0'" ist nicht vorhanden. Stellen Sie sicher, dass die LLVM-Toolsetversion 12.0.0 installiert ist, oder wählen Sie eine andere Toolsetversion aus. Weitere Informationen: https://aka.ms/AA55s5p [C:\Code\vcpkg\buildtrees\libpq\x64-win-llvm-dbg\libpgport.vcxproj]
```
`libpq` seems to be a VS build that seems to require VS's Clang installation (which is outdated), and does not accept the found non-VS one.

**Comment by Neumann-A** [comment]
The ClangCL toolset requires the env variables 'LLVMInstallDir' and 'LLVMToolsVersion' for external LLVM. Could it be that you had llvm of VS installed previously?

However i do not yet understand why it failed early when you added the variables

**Comment by Neumann-A** [comment]
See https://learn.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-170#custom_llvm_location

**Comment by Arndt-MBE** [comment]
I had temporarily installed VS2019's Clang 12 today, and achieved a successful build of `libpq` with it. However, it is my goal to use the latest Clang version for all builds.

I am almost sure that the build used to work without 'LLVMInstallDir' and 'LLVMToolsVersion' until before my last pull of vcpkg (like yesterday), but although there have been some changes to `libpq` in the vcpkg repo, I doubt that these would affect the build process in such a way.

The previous debug output, which reports to have found Clang 18, was _without_ the environment variables.

_With_ the variables set, the 'Visual Studio 2019 Developer Command Prompt v16.11.34' is opened during the build process, which unsets these variables.

**Comment by Neumann-A** [comment]
So to be clear. On Windows vcpkg cleans the environment and only takes variables which are set by `vcvars.bat` unless you have [VCPKG_KEEP_ENV_VARS](https://learn.microsoft.com/en-us/vcpkg/users/config-environment#vcpkg_keep_env_vars) or [VCPKG_ENV_PASSTHROUGH](https://learn.microsoft.com/en-us/vcpkg/users/triplets#vcpkg_env_passthrough) set. So previously vcpkg couldn't really find clang-cl unless you told it to find it somehow. That is where `LLVMInstallDir` and `LLVMToolsVersion` come in. These env variables are marked as passthrough in the triplet and vcpkg/cmake should be able to find clang-cl with those. However, MSBuild still needs to see those and the triplet is modifying PATH to put LLVM on the PATH via `set(ENV{PATH} "${LLVM_BIN_DIR};$ENV{PATH}")`. According to the docs that should be enough for MSBuild to find external LLVM. However in your case the triplet already tells you that it cannot find clang-cl so something strange is going on. Without further debugging logs with the environment variables I basically don't know what is going on. Especially since locally it just works fine for me.

**Comment by Arndt-MBE** [comment]
I have uploaded the debug output and logs of approaches with and without the variables, with all the debug options I could find enabled.
* [Output without variables](https://github.com/microsoft/vcpkg/files/14773885/vcpkg_37721_output_without_variables.txt)
* [Log without variables](https://github.com/microsoft/vcpkg/files/14773886/vcpkg_37721_without_variables_build-libpq-x64-win-llvm-dbg-out.log)
* [Output with variables set](https://github.com/microsoft/vcpkg/files/14773884/vcpkg_37721_output_with_variables.txt)
With variables, a log is not even created.
Contrary to what I assumed earlier, the two variables remain set when the Developer prompt is opened during the process.

**Comment by Neumann-A** [comment]
@Arndt-MBE `LLVMInstallDir="C:\Program Files\LLVM"` is not going to work. You need to remove the `"`

**Comment by Neumann-A** [comment]
Also `--x-cmake-args="--debug-find --debug-output"` is not going to work. needs to be passed as `--x-cmake-args=--debug-find --x-cmake-args=--debug-output`

**Comment by Arndt-MBE** [comment]
Thank you @Neumann-A, removing the quotes helped indeed. I have a successfully built from the command line both with vcpkg stand-alone and in manifest mode from a CMake preset.
I'm still trying to figure out why I didn't need the two variable before, but that's ok for now.

**Comment by dg0yt** [comment]
I was too slow to comment. But note:

> ```
> > echo %LLVMInstallDir% %LLVMToolsVersion%
> "C:\Program Files\LLVM" 18
> ```
^^^^^
