### ISSUE TITLE
[grpc] update to v1.62.1

### ISSUE THREAD

**Issue by matthewleta** [microsoft/vcpkg#37729]
### Library name

grpc

### New version number

v1.62.1

### Other information that may be useful (release notes, etc...)

This port is a bit behind, it would be great if we could get it upgraded! Thanks!

**Comment by luzpaz** [comment]
1.62.2 released https://github.com/grpc/grpc/releases/tag/v1.62.2

**Comment by luzpaz** [comment]
bump

**Comment by VAllens** [comment]
The latest version of the grpc repository is `1.67.1` !!!
Who maintains the `grpc` package version on vcpkg ???
Can I participate?
How can I participate?

**Comment by WangWeiLin-MV** [comment]
> Can I participate?

@VAllens Sure.

https://github.com/microsoft/vcpkg/blob/2024.10.21/README.md#contribute

> vcpkg is an open source project, and is thus built with your > contributions. Here
> are some ways you can contribute:
>
> * [Submit issues][contributing:submit-issue] in vcpkg or existing packages
> * [Submit fixes and new packages][contributing:submit-pr]
>
> Please refer to our [mantainer guide](https://learn.microsoft.com/vcpkg/> contributing/maintainer-guide) and
> [packaging tutorial](https://learn.microsoft.com/vcpkg/get_started/> get-started-packaging) for more details.
>
> This project has adopted the [Microsoft Open Source Code of
> Conduct][contributing:coc]. For more information see the [Code of Conduct
> FAQ][contributing:coc-faq] or email
> [opencode@microsoft.com](mailto:opencode@microsoft.com) with any > additional
> questions or comments.
>
> [contributing:submit-issue]: https://github.com/microsoft/vcpkg/issues/> new/choose
> [contributing:submit-pr]: https://github.com/microsoft/vcpkg/pulls
> [contributing:coc]: https://opensource.microsoft.com/codeofconduct/
> [contributing:coc-faq]: https://opensource.microsoft.com/codeofconduct/

**Comment by dg0yt** [comment]
https://github.com/microsoft/vcpkg/issues/40803#issuecomment-2461435666
