### ISSUE TITLE
[gmp] Build error on x64-windows

### ISSUE THREAD

**Issue by LauYL2580** [microsoft/vcpkg#37724]
Computing installation plan...
The following packages will be built and installed:
  * boost-iostreams[bzip2,core,lzma,zlib,zstd]:x64-windows@1.84.0
  * boost-multi-array:x64-windows@1.84.0
  * boost-ptr-container:x64-windows@1.84.0
  * boost-units:x64-windows@1.84.0
  * bzip2[core,tool]:x64-windows@1.0.8#5
    cgal:x64-windows@5.6.1
  * gmp:x64-windows@6.3.0
  * liblzma:x64-windows@5.6.0
  * mpfr:x64-windows@4.2.1
  * zlib:x64-windows@1.3.1
  * zstd:x64-windows@1.5.5#2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
-- Automatically setting %HTTP(S)_PROXY% environment variables to "127.0.0.1:10809".
Compiler found: F:/vs/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from C:\Users\LIU\AppData\Local\vcpkg\archives in 3.28 ms. Use --debug to see more details.
Installing 1/11 bzip2[core,tool]:x64-windows@1.0.8#5...
Building bzip2[core,tool]:x64-windows@1.0.8#5...
-- Downloading https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz -> bzip2-1.0.8.tar.gz...
-- Extracting source C:/Users/LIU/vcpkg/downloads/bzip2-1.0.8.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Using source at C:/Users/LIU/vcpkg/buildtrees/bzip2/src/bzip2-1-336d4794a3.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig file: C:/Users/LIU/vcpkg/packages/bzip2_x64-windows/lib/pkgconfig/bzip2.pc
-- Downloading https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst -> msys2-mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst...
-- Downloading https://mirror.msys2.org/msys/x86_64/msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst;https://repo.msys2.org/msys/x86_64/msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/msys/x86_64/msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst;https://mirror.selfnet.de/msys2/msys/x86_64/msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst -> msys2-msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst...
-- Using msys root at C:/Users/LIU/vcpkg/downloads/tools/msys2/fdbea3694fb5c0d4
-- Fixing pkgconfig file: C:/Users/LIU/vcpkg/packages/bzip2_x64-windows/debug/lib/pkgconfig/bzip2.pc
-- Installing: C:/Users/LIU/vcpkg/packages/bzip2_x64-windows/share/bzip2/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 302 ms.
Elapsed time to handle bzip2:x64-windows: 29 s
bzip2:x64-windows package ABI: 7dcf72a1f087994a61f014019d677d32d8a419f7522e79f008fe291e3a6576a0
Installing 2/11 liblzma:x64-windows@5.6.0...
Building liblzma:x64-windows@5.6.0...
-- Downloading https://github.com/tukaani-project/xz/archive/v5.6.0.tar.gz -> tukaani-project-xz-v5.6.0.tar.gz...
-- Extracting source C:/Users/LIU/vcpkg/downloads/tukaani-project-xz-v5.6.0.tar.gz
-- Applying patch fix_config_include.patch
-- Applying patch win_output_name.patch
-- Applying patch add_support_ios.patch
-- Applying patch build-tools.patch
-- Using source at C:/Users/LIU/vcpkg/buildtrees/liblzma/src/v5.6.0-0bc01dfc88.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
CMake Warning at installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:318 (message):
  The following variables are not used in CMakeLists.txt:

      ENABLE_NLS

  Please recheck them and remove the unnecessary options from the
  `vcpkg_cmake_configure` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):
  ports/liblzma/portfile.cmake:23 (vcpkg_cmake_configure)
  scripts/ports.cmake:175 (include)

-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig file: C:/Users/LIU/vcpkg/packages/liblzma_x64-windows/lib/pkgconfig/liblzma.pc
-- Using cached msys2-mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst.
-- Using msys root at C:/Users/LIU/vcpkg/downloads/tools/msys2/fdbea3694fb5c0d4
-- Fixing pkgconfig file: C:/Users/LIU/vcpkg/packages/liblzma_x64-windows/debug/lib/pkgconfig/liblzma.pc
-- Installing: C:/Users/LIU/vcpkg/packages/liblzma_x64-windows/share/liblzma/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 295 ms.
Elapsed time to handle liblzma:x64-windows: 50 s
liblzma:x64-windows package ABI: 00a739255e1e3eb8b435fca3eb0ad6443d045dbcbbaa71bc91dfee9137880eb3
Installing 3/11 zlib:x64-windows@1.3.1...
Building zlib:x64-windows@1.3.1...
-- Downloading https://github.com/madler/zlib/archive/v1.3.1.tar.gz -> madler-zlib-v1.3.1.tar.gz...
-- Extracting source C:/Users/LIU/vcpkg/downloads/madler-zlib-v1.3.1.tar.gz
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch 0002-build-static-or-shared-not-both.patch
-- Applying patch 0003-android-and-mingw-fixes.patch
-- Using source at C:/Users/LIU/vcpkg/buildtrees/zlib/src/v1.3.1-2e5db616bf.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: C:/Users/LIU/vcpkg/packages/zlib_x64-windows/share/zlib/vcpkg-cmake-wrapper.cmake
-- Fixing pkgconfig file: C:/Users/LIU/vcpkg/packages/zlib_x64-windows/lib/pkgconfig/zlib.pc
-- Using cached msys2-mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst.
-- Using msys root at C:/Users/LIU/vcpkg/downloads/tools/msys2/fdbea3694fb5c0d4
-- Fixing pkgconfig file: C:/Users/LIU/vcpkg/packages/zlib_x64-windows/debug/lib/pkgconfig/zlib.pc
-- Installing: C:/Users/LIU/vcpkg/packages/zlib_x64-windows/share/zlib/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 169 ms.
Elapsed time to handle zlib:x64-windows: 16 s
zlib:x64-windows package ABI: 9def8779246a40a63d4cfa26000eb2c40b5fcb5c2f40a0e939f20cb2dd126c1e
Installing 4/11 zstd:x64-windows@1.5.5#2...
Building zstd:x64-windows@1.5.5#2...
-- Downloading https://github.com/facebook/zstd/archive/v1.5.5.tar.gz -> facebook-zstd-v1.5.5.tar.gz...
-- Extracting source C:/Users/LIU/vcpkg/downloads/facebook-zstd-v1.5.5.tar.gz
-- Applying patch no-static-suffix.patch
-- Applying patch fix-emscripten-and-clang-cl.patch
-- Using source at C:/Users/LIU/vcpkg/buildtrees/zstd/src/v1.5.5-b23e615f5d.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig file: C:/Users/LIU/vcpkg/packages/zstd_x64-windows/lib/pkgconfig/libzstd.pc
-- Using cached msys2-mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst.
-- Using msys root at C:/Users/LIU/vcpkg/downloads/tools/msys2/fdbea3694fb5c0d4
-- Fixing pkgconfig file: C:/Users/LIU/vcpkg/packages/zstd_x64-windows/debug/lib/pkgconfig/libzstd.pc
-- Installing: C:/Users/LIU/vcpkg/packages/zstd_x64-windows/share/zstd/usage
-- Performing post-build validation
Stored binaries in 1 destinations in 598 ms.
Elapsed time to handle zstd:x64-windows: 34 s
zstd:x64-windows package ABI: d8e955d9766043be7e3bd2ff97e6976a2ca3921385b0386f6dc3672d31102544
Installing 5/11 boost-iostreams[bzip2,core,lzma,zlib,zstd]:x64-windows@1.84.0...
Building boost-iostreams[bzip2,core,lzma,zlib,zstd]:x64-windows@1.84.0...
-- Downloading https://github.com/boostorg/iostreams/archive/boost-1.84.0.tar.gz -> boostorg-iostreams-boost-1.84.0.tar.gz...
-- Extracting source C:/Users/LIU/vcpkg/downloads/boostorg-iostreams-boost-1.84.0.tar.gz
-- Applying patch Removeseekpos.patch
-- Using source at C:/Users/LIU/vcpkg/buildtrees/boost-iostreams/src/ost-1.84.0-9cfee6bcc3.clean
-- Including C:/Users/LIU/vcpkg/ports/boost-iostreams/b2-options.cmake
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Copying headers
-- Copying headers done
-- Installing: C:/Users/LIU/vcpkg/packages/boost-iostreams_x64-windows/share/boost-iostreams/usage
-- Installing: C:/Users/LIU/vcpkg/packages/boost-iostreams_x64-windows/share/boost-iostreams/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 337 ms.
Elapsed time to handle boost-iostreams:x64-windows: 32 s
boost-iostreams:x64-windows package ABI: e0a3d2cd83becdc04fca4b519c29a67b3fbc8acc23d33235aff7cafffe408666
Installing 6/11 boost-multi-array:x64-windows@1.84.0...
Building boost-multi-array:x64-windows@1.84.0...
-- Downloading https://github.com/boostorg/multi_array/archive/boost-1.84.0.tar.gz -> boostorg-multi_array-boost-1.84.0.tar.gz...
-- Extracting source C:/Users/LIU/vcpkg/downloads/boostorg-multi_array-boost-1.84.0.tar.gz
-- Using source at C:/Users/LIU/vcpkg/buildtrees/boost-multi-array/src/ost-1.84.0-d91f5f92e4.clean
-- Copying headers
-- Copying headers done
-- Installing: C:/Users/LIU/vcpkg/packages/boost-multi-array_x64-windows/share/boost-multi-array/usage
-- Installing: C:/Users/LIU/vcpkg/packages/boost-multi-array_x64-windows/share/boost-multi-array/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 49.9 ms.
Elapsed time to handle boost-multi-array:x64-windows: 4.2 s
boost-multi-array:x64-windows package ABI: 395f399d25e3cb3bec52eecd73ffa5da1ad109090d7e086db57a68dd6d7ebd3d
Installing 7/11 boost-ptr-container:x64-windows@1.84.0...
Building boost-ptr-container:x64-windows@1.84.0...
-- Downloading https://github.com/boostorg/ptr_container/archive/boost-1.84.0.tar.gz -> boostorg-ptr_container-boost-1.84.0.tar.gz...
-- Extracting source C:/Users/LIU/vcpkg/downloads/boostorg-ptr_container-boost-1.84.0.tar.gz
-- Using source at C:/Users/LIU/vcpkg/buildtrees/boost-ptr-container/src/ost-1.84.0-fede4656f5.clean
-- Copying headers
-- Copying headers done
-- Installing: C:/Users/LIU/vcpkg/packages/boost-ptr-container_x64-windows/share/boost-ptr-container/usage
-- Installing: C:/Users/LIU/vcpkg/packages/boost-ptr-container_x64-windows/share/boost-ptr-container/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 60 ms.
Elapsed time to handle boost-ptr-container:x64-windows: 4.5 s
boost-ptr-container:x64-windows package ABI: 265392e5c6240a6038234870d1ebc6d4cd5e8c4450a131a7418a3d9614d7561f
Installing 8/11 boost-units:x64-windows@1.84.0...
Building boost-units:x64-windows@1.84.0...
-- Downloading https://github.com/boostorg/units/archive/boost-1.84.0.tar.gz -> boostorg-units-boost-1.84.0.tar.gz...
-- Extracting source C:/Users/LIU/vcpkg/downloads/boostorg-units-boost-1.84.0.tar.gz
-- Using source at C:/Users/LIU/vcpkg/buildtrees/boost-units/src/ost-1.84.0-f263b9af0f.clean
-- Copying headers
-- Copying headers done
-- Installing: C:/Users/LIU/vcpkg/packages/boost-units_x64-windows/share/boost-units/usage
-- Installing: C:/Users/LIU/vcpkg/packages/boost-units_x64-windows/share/boost-units/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 123 ms.
Elapsed time to handle boost-units:x64-windows: 8.1 s
boost-units:x64-windows package ABI: b9ac6b2f3be5d945f17c55715adaced4d45733a4430173a43da4a17adc329cd5
Installing 9/11 gmp:x64-windows@6.3.0...
Building gmp:x64-windows@6.3.0...
-- Downloading https://ftpmirror.gnu.org/gmp/gmp-6.3.0.tar.xz;https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz;https://gmplib.org/download/gmp/gmp-6.3.0.tar.xz -> gmp-6.3.0.tar.xz...
-- Extracting source C:/Users/LIU/vcpkg/downloads/gmp-6.3.0.tar.xz
-- Applying patch asmflags.patch
-- Applying patch cross-tools.patch
-- Applying patch subdirs.patch
-- Applying patch msvc_symbol.patch
-- Applying patch arm64-coff.patch
-- Using source at C:/Users/LIU/vcpkg/buildtrees/gmp/src/v6.3.0-036e54f1a3.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Downloading https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.6/LLVM-15.0.6-win64.exe -> LLVM-15.0.6-win64.7z.exe...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from C:\Users\LIU\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: C:\Users\LIU\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.6/LLVM-15.0.6-win64.exe
[DEBUG] Trying to hash C:\Users\LIU\vcpkg\downloads\LLVM-15.0.6-win64.7z.exe.4768.part
[DEBUG] C:\Users\LIU\vcpkg\downloads\LLVM-15.0.6-win64.7z.exe.4768.part has hash 4d97dc6bf3eaada9e2fedde8f77897f65b52ff8a726945fface6d39efa576330db296a1dfe359e2fe0ea927d00cee6971f93913dd06f55c7542f9509bcac0da3
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.6/LLVM-15.0.6-win64.exe
File: C:\Users\LIU\vcpkg\downloads\LLVM-15.0.6-win64.7z.exe.4768.part
Expected hash: 2dd6f3eea106f2b905e6658ea5ea12856d17285adbfba055edc2d6b6389c4c2f7aa001df5cb0d8fb84fa7fa47d5035a7fddf276523b472dd55f150ae25938768
Actual hash: 4d97dc6bf3eaada9e2fedde8f77897f65b52ff8a726945fface6d39efa576330db296a1dfe359e2fe0ea927d00cee6971f93913dd06f55c7542f9509bcac0da3
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1031):
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 3us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 4070us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 14 min (847369145us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_find_acquire_program.cmake:170 (vcpkg_download_distfile)
  ports/gmp/portfile.cmake:55 (vcpkg_find_acquire_program)
  scripts/ports.cmake:175 (include)

error: building gmp:x64-windows failed with: BUILD_FAILED
Elapsed time to handle gmp:x64-windows: 15 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+gmp
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[gmp]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2FUsers%2FLIU%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by Cheney-W** [comment]
I tried downloading `LLVM-15.0.6-win64.exe` directly, but I couldn't reproduce the issue you encountered. The default hash values in vcpkg are correct. I suspect that some software on your machine may be touched the downloaded `LLVM-15.0.6-win64.exe` file, causing the hash value to change.

Also, you can try installing LLVM through the VS installer, which will bypass the download of LLVM in vcpkg.
![image](https://github.com/microsoft/vcpkg/assets/38240633/39f2d4b2-c497-44a5-9cb4-f35f9b42df8e)
