### ISSUE TITLE
mpir build generates generic library

### ISSUE THREAD

**Issue by degski** [microsoft/vcpkg#3773]
I'm building mpir:x64-windows-static on a Broadwell machine, I should be getting the Haswell binaries, but instead I get the generic binaries, which are, other then for educational purposes, rather useless.
The Haswell build **is** in the .sln file, I guess there need to be several mpir packages (mpir[Haswell] etc.), one per supported architecture.

**Comment by JackBoosY** [comment]
Hi @degski, sorry for late.
Could you provide some repro steps?

Thanks.

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
