### ISSUE TITLE
Error: Building package zlib:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by fragrans** [Microsoft/vcpkg#3774]
It is not just zlib. I also tried lua, boost, ....
The build process stopped with the same error.
environments:
- Windows 10 Pro 64bit, Chinese, updated (newly installed).
- Visual studio 2017 community (newly installed), with mfc, vs2015 toolsets.

I have tried with chcp 65001, installed English language pack.
no luck.

<pre>
PS D:\vcpkg> .\vcpkg.exe install zlib
The following packages will be built and installed:
    zlib[core]:x86-windows
Starting package 1/1: zlib:x86-windows
Building package zlib[core]:x86-windows...
A suitable version of cmake was not found (required v3.10.2). Downloading portable cmake v3.10.2...
Downloading cmake...
Downloading cmake... done.
Extracting cmake...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
Downloading 7zip... done.
Extracting 7zip...
A suitable version of nuget was not found (required v4.6.2). Downloading portable nuget v4.6.2...
Downloading nuget...
Downloading nuget... done.
Extracting 7zip... done.
Extracting cmake... done.
-- CURRENT_INSTALLED_DIR=D:/vcpkg/installed/x86-windows
-- DOWNLOADS=D:/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/vcpkg/packages/zlib_x86-windows
-- CURRENT_BUILDTREES_DIR=D:/vcpkg/buildtrees/zlib
-- CURRENT_PORT_DIR=D:/vcpkg/ports/zlib
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz...
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting source D:/vcpkg/downloads/zlib1211.tar.gz
-- Extracting done
-- Applying patch D:/vcpkg/ports/zlib/cmake_dont_build_more_than_needed.patch
-- Applying patch D:/vcpkg/ports/zlib/cmake_dont_build_more_than_needed.patch done
-- Downloading https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip...
-- Downloading https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Configuring x86-windows
-- Configuring x86-windows done
-- Build x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:170 (message):
    Command failed: D:/vcpkg/downloads/tools/cmake-3.10.2-windows/cmake-3.10.2-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: D:/vcpkg/buildtrees/zlib/x86-windows-dbg
    See logs for more information:
      D:\vcpkg\buildtrees\zlib\install-x86-windows-dbg-out.log
      D:\vcpkg\buildtrees\zlib\install-x86-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/zlib/portfile.cmake:29 (vcpkg_install_cmake)
  scripts/ports.cmake:72 (include)

Error: Building package zlib:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x86-windows
  Vcpkg version: 0.0.113-nohash

Additionally, attach any relevant sections from the log files above.
</pre>
[install-x86-windows-dbg-err.log](https://github.com/Microsoft/vcpkg/files/2130867/install-x86-windows-dbg-err.log)
[install-x86-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2130868/install-x86-windows-dbg-out.log)

**Comment by fragrans** [comment]
It just began to compile, this morning.
I didn't do nothing; 
---------------
Any one can explain that?
or just close this issue silently?

**Comment by Voskrese** [comment]
`vcpkg install zlib:x86-windows --debug`

```
The following packages will be built and installed:
    zlib[core]:x86-windows
Starting package 1/1: zlib:x86-windows
Building package zlib[core]:x86-windows...
[DEBUG] _wpopen("where.exe cmake 2>&1")
[DEBUG] _pclose() returned 0 after  1028159 us
[DEBUG] _wpopen(""E:\tools\vcpkg\downloads\tools\cmake-3.10.2-windows\cmake-3.10.2-win32-x86\bin\cmake.exe" --version 2>&1")
[DEBUG] _pclose() returned 1 after   300658 us
[DEBUG] _wpopen(""C:\Program Files (x86)\CMake\bin\cmake.exe" --version 2>&1")
[DEBUG] _pclose() returned 0 after   382779 us
[DEBUG] _wpopen(""C:\Program Files (x86)\CMake\bin\cmake.exe" "-DCMAKE_TRIPLET_FILE=E:/tools/vcpkg/triplets/x86-windows.cmake" -P "E:/tools/vcpkg/scripts/get_triplet_environment.cmake" 2>&1")
[DEBUG] _pclose() returned 0 after   423054 us
[DEBUG] _wpopen("where.exe git 2>&1")
[DEBUG] _pclose() returned 1 after   733119 us
[DEBUG] _wpopen(""E:\tools\vcpkg\downloads\tools\git-2.16.2-windows\cmd\git.exe" --version 2>&1")
[DEBUG] _pclose() returned 0 after   485823 us
[DEBUG] _wpopen("powershell -NoProfile -ExecutionPolicy Bypass -Command "& {& 'E:\tools\vcpkg\scripts\findVisualStudioInstallationInstances.ps1' }" 2>&1")
[DEBUG] _pclose() returned 0 after  9613367 us
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise
Please install the English language pack.
[DEBUG] CreateProcessW(cmd.exe /c ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"  amd64_x86   2>&1 && "C:\Program Files (x86)\CMake\bin\cmake.exe" "-DCMD=BUILD" "-DPORT=zlib" "-DCURRENT_PORT_DIR=E:/tools/vcpkg/ports/zlib/." "-DTARGET_TRIPLET=x86-windows" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DVCPKG_USE_HEAD_VERSION=0" "-D_VCPKG_NO_DOWNLOADS=0" "-D_VCPKG_DOWNLOAD_TOOL=BUILT_IN" "-DGIT=E:/tools/vcpkg/downloads/tools/git-2.16.2-windows/cmd/git.exe" "-DFEATURES=core" "-DALL_FEATURES=" -P "E:/tools/vcpkg/scripts/ports.cmake"")
-- CURRENT_INSTALLED_DIR=E:/tools/vcpkg/installed/x86-windows
-- DOWNLOADS=E:/tools/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=E:/tools/vcpkg/packages/zlib_x86-windows
-- CURRENT_BUILDTREES_DIR=E:/tools/vcpkg/buildtrees/zlib
-- CURRENT_PORT_DIR=E:/tools/vcpkg/ports/zlib/.
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz...
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting source E:/tools/vcpkg/downloads/zlib1211.tar.gz
-- Extracting done
-- Applying patch E:/tools/vcpkg/ports/zlib/cmake_dont_build_more_than_needed.patch
-- Applying patch E:/tools/vcpkg/ports/zlib/cmake_dont_build_more_than_needed.patch done
-- Configuring x86-windows
-- Configuring x86-windows done
-- Build x86-windows-dbg
-- Build x86-windows-dbg done
-- Build x86-windows-rel
-- Build x86-windows-rel done
-- Installing: E:/tools/vcpkg/packages/zlib_x86-windows/share/zlib/copyright
[DEBUG] CreateProcessW() returned 0
-- Performing post-build validation
[DEBUG] _wpopen(""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\dumpbin.exe" /exports "E:\tools\vcpkg\packages\zlib_x86-windows\debug\bin\zlibd1.dll" 2>&1")
[DEBUG] _pclose() returned 0 after  1033995 us
[DEBUG] _wpopen(""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\dumpbin.exe" /exports "E:\tools\vcpkg\packages\zlib_x86-windows\bin\zlib1.dll" 2>&1")
[DEBUG] _pclose() returned 0 after   444682 us
[DEBUG] _wpopen(""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\dumpbin.exe" /dependents "E:\tools\vcpkg\packages\zlib_x86-windows\debug\bin\zlibd1.dll" 2>&1")
[DEBUG] _pclose() returned 0 after   407683 us
[DEBUG] _wpopen(""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\dumpbin.exe" /dependents "E:\tools\vcpkg\packages\zlib_x86-windows\bin\zlib1.dll" 2>&1")
[DEBUG] _pclose() returned 0 after   427777 us
-- Performing post-build validation done
Building package zlib[core]:x86-windows... done
Installing package zlib[core]:x86-windows...
File E:\tools\vcpkg\installed\x86-windows\bin\zlib1.dll was already present and will be overwritten
File E:\tools\vcpkg\installed\x86-windows\include\zconf.h was already present and will be overwritten
File E:\tools\vcpkg\installed\x86-windows\include\zlib.h was already present and will be overwritten
File E:\tools\vcpkg\installed\x86-windows\lib\zlib.lib was already present and will be overwritten
Installing package zlib[core]:x86-windows... done
Elapsed time for package zlib:x86-windows: 47.52 s

Total elapsed time: 47.52 s

The package zlib is compatible with built-in CMake targets:

    find_package(ZLIB REQUIRED)
    target_link_libraries(main PRIVATE ZLIB::ZLIB)
```

ok

**Comment by Cheney-W** [comment]
@fragrans , I just tried to install this lib with latest VCPKG and VS2017 15.9.5 , it installed successfully. I think you can have a try, if you install zlib successfully, please close this issue.

**Comment by tnie** [comment]
@Cheney-W ,i think @fragrans using vc2017 with **v140** toolset

> Visual studio 2017 community (newly installed), with mfc, **vs2015 toolsets.**

**Comment by Cheney-W** [comment]
@fragrans , 
Please open a new issue if this is still a problem for you.
