### ISSUE TITLE
Can Manifest Mode can configure every package seperatly?

### ISSUE THREAD

**Issue by breaking153** [microsoft/vcpkg#37757]
**Environment**
Windows

**To Reproduce**
Like:
`{
    "name": "your-project-name",
    "version-string": "1.0",
    "dependencies": [
        {
            "name": "<libname>",
            "triplet": "x64-windows-static"
        }
    ]
}
`

```[tasklist]
### Tasks
```

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Can you describe it in more detail? Are you intending to create a separate file for each port?

**Comment by breaking153** [comment]
i'm trying to use vcpkg to install different package with different triplets (in manifest mode)

**Comment by breaking153** [comment]
like:
{
  "name": "my_project",
  "version-string": "0.1",
  "dependencies": [
    {
      "name": "openssl",
      "version": "1.1.1",
      "triplet": "x64-windows-static"
    },
    {
      "name": "fmt",
      "version": "7.1.3",
      "triplet": "x86-windows"
    },
    {
      "name": "sqlite3",
      "version": "3.36.0",
      "triplet": "x64-linux"
    }
  ]
}
