### ISSUE TITLE
Boost Build does not statically link to the CRT

### ISSUE THREAD

**Issue by degski** [Microsoft/vcpkg#3775]
I've just built some Boost libs, with triple "x64-windows-static". The libraries I get though, are linked to the dynamic CRT (/MD and /MDd), unless the naming is wrong and they are still linked to the static CRT (/MT and /MTd). I get f.e. boost_container-vc140-mt.lib and boost_container-vc140-mt-gd.lib, while I would have expected boost_container-vc140-mt-s.lib and boost_container-vc140-mt-sgd.lib. Other than that, I only have VS2017 installed (on a clean machine), so the vc140 is weird as well, ~~but that is most probably a Boost issue and I think~~ can be safely ignored. There should AFAIK also in this case be "x64" somewhere towards the end of the filename (but that can be suppressed I believe, so maybe it is).
bjam expects a.o. link=static runtime-link=static as switches, to build a static lib, statically linked to the CRT.

Closing this one and opened #3837

**Comment by arthur-tacca** [comment]
I am pretty sure it is actually statically linking the CRT. If it weren't, I would've expected a link error (or runtime crash!) due to mismatched CRTs. 

It looks like vcpkg is [renaming the libraries](https://github.com/Microsoft/vcpkg/blob/751015f6a44d6f89ca71ac63d7c5cab83cf531c0/ports/boost-modular-build-helper/boost-modular-build.cmake#L304-L307). I'm not sure why, but it looks very intentional so I presume there's a good reason. Perhaps it makes `find_package` in the application build work more seamlessly with the static integration.

**Comment by degski** [comment]
Yes, I looked at your link, and that script does indeed do what I'm observing, thanks for that info. It does seem to be a rather unfortunate decision though, as the versioned naming obviously allows for having those configurations side-by-side. The x86/x64 was actually just recently (1.67) added by Peter Dimov, to allow for also having both 32 and 64 bit binaries in the same folder.

**Comment by degski** [comment]
It gets stranger, checking the build output (of some project) (with a high verbosity) reveals that, simply all libs in the `..\vcpkg\installed\x64-windows-static\lib`  folder get fed to the linker with a wild-card `*.lib`, this seems to be messy and over-simplified.

**Comment by OlafvdSpek** [comment]
Why would it be too simple?

**Comment by arthur-tacca** [comment]
> l libs in the ..\vcpkg\installed\x64-windows-static\lib folder get fed to the linker with a wild-card *.lib

I often use `x64-windows-static` and I haven't seen this behaviour. I can see the individual .lib file names passed to the linker, including the appropriate Boost libraries. I use CMake for my application with the "Visual Studio 15 2017 Win64" generator; you can see the full command I use in #3807. What generator are you using? Or are you using vcpkg integration from a manually-created Visual Studio project? If so, do you get the same problem with a freshly-created project? Also, what exactly *is* your problem?

**Comment by degski** [comment]
@OlafvdSpek  It excludes the use of different flavours of the same library, this is not exactly template type deduction, it will pick the first one it encounters.

**Comment by degski** [comment]
@arthur-tacca I don't use exactly "manually created" projects, but ["project templates"](https://msdn.microsoft.com/en-us/library/ms247121.aspx?f=255&MSPPError=-2147217396)  (it's really handy), and with those I use the vcpkg integration, isn't that the whole idea? The only thing that's not automatic is the writing of the code, but I'm working on that ;-) .
