### ISSUE TITLE
[CGAL] build failure

### ISSUE THREAD

**Issue by winnonatural** [microsoft/vcpkg#37754]
### Operating system

Windows

### Steps to reproduce the behavior

```Shell
.\vcpkg.exe install cgal:x64-windows
```

### Failure logs

![Uploading 微信截图_20240327174547.png…]()

```[tasklist]
### Tasks
```

**Comment by winnonatural** [comment]
PS D:\Code\vcpkg\vcpkg> .\vcpkg.exe install cgal:x64-windows
Computing installation plan...
The following packages will be built and installed:
    cgal:x64-windows@5.6.1
Detecting compiler hash for triplet x64-windows...
-- Setting "%SOCKS_PROXY%" environment variables to "127.0.0.1:1080".
Compiler found: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from C:\Users\lzs\AppData\Local\vcpkg\archives in 122 us. Use --debug to see more details.
Installing 1/1 cgal:x64-windows@5.6.1...
Building cgal:x64-windows@5.6.1...
-- Downloading https://github.com/CGAL/cgal/archive/v5.6.1.tar.gz -> CGAL-cgal-v5-943413bf.6.1.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from D:\Code\vcpkg\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: D:\Code\vcpkg\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://github.com/CGAL/cgal/archive/v5.6.1.tar.gz
error: Failed to download from mirror set
error: https://github.com/CGAL/cgal/archive/v5.6.1.tar.gz: failed: status code 404
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1031):
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 2us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 1205us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 6.8 s (6758804us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.


Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/cgal/portfile.cmake:4 (vcpkg_from_github)
  scripts/ports.cmake:175 (include)


error: building cgal:x64-windows failed with: BUILD_FAILED
Elapsed time to handle cgal:x64-windows: 7.2 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+cgal
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[cgal]+Build+error+on+x64-windows&body=Copy+issue+body+from+D%3A%2FCode%2Fvcpkg%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by winnonatural** [comment]
I 
![Uploading 微信截图_20240327175930.png…]()

**Comment by winnonatural** [comment]
vcpkg already update to date

**Comment by MonicaLiu0311** [comment]
Sorry I can't repro your issue.
```
Installing 67/67 cgal:x64-windows@5.6.1...
Building cgal:x64-windows@5.6.1...
-- Downloading https://github.com/CGAL/cgal/archive/v5.6.1.tar.gz -> CGAL-cgal-v5.6.1.tar.gz...
-- Extracting source F:/vcpkg/downloads/CGAL-cgal-v5.6.1.tar.gz
-- Using source at F:/vcpkg/buildtrees/cgal/src/v5.6.1-f2c46bdd3d.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- ------------release_share: F:/vcpkg/packages/cgal_x64-windows/share/cgal
-- ------------CURRENT_PACKAGES_DIR: F:/vcpkg/packages/cgal_x64-windows
-- ------------target_path: share/cgal
-- ------------release_targets:
-- ------------release_targets:
-- ------------debug_targets:
-- ------------debug_targets:
-- ------------main_cmakes: F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGALConfig-installation-dirs.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGALConfig.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGALConfigBuildVersion.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGALConfigVersion.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_Boost_iostreams_support.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_Boost_serialization_support.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_Ceres_support.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_CheckCXXFileRuns.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_Common.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_CreateSingleSourceCGALProgram.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_Eigen3_support.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_Eigen_support.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_GLPK_support.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_GeneratorSpecificSettings.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_ITK_support.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_LASLIB_support.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_METIS_support.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_Macros.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_OSQP_support.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_OpenCV_support.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_OpenGR_support.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_Qt5_moc_and_resource_files.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_SCIP_support.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_SCM.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_SetupBoost.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_SetupCGALDependencies.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_SetupCGAL_CoreDependencies.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_SetupCGAL_ImageIODependencies.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_SetupCGAL_Qt5Dependencies.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_SetupDependencies.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_SetupFlags.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_SetupGMP.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_SetupLEDA.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_SetupVLD.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_TBB_support.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_TweakFindBoost.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_UseLEDA.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_UseMKL.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_UseMPFI.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_UseRS.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_UseRS3.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_VersionUtils.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_add_test.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_display_flags.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_enable_end_of_configuration_hook.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_parse_version_h.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_pointmatcher_support.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_setup_target_dependencies.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGAL_target_use_TBB.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/FindCORE.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/FindESBTL.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/FindEigen3.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/FindF2C.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/FindGLPK.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/FindGMP.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/FindGMPXX.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/FindIPE.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/FindITT.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/FindLASLIB.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/FindLEDA.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/FindLibSSH.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/FindMETIS.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/FindMKL.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/FindMPFI.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/FindMPFR.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/FindNTL.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/FindOSQP.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/FindOpenMesh.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/FindRS.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/FindRS3.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/FindSuiteSparse.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/FindTBB.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/UseCGAL.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/UseESBTL.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/UseEigen3.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/UseLASLIB.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/UseOpenMesh.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/UseTBB.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/list_of_whitelisted_headers.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/process_dependencies.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/run_cmd_redirection_cerr.cmake;F:/vcpkg/packages/cgal_x64-windows/share/cgal/run_test_with_cin.cmake
-- ------------main_cmake: F:/vcpkg/packages/cgal_x64-windows/share/cgal/CGALConfig-installation-dirs.cmake
-- ------------debug_share: F:/vcpkg/packages/cgal_x64-windows/debug/share/cgal
-- ------------release_share: F:/vcpkg/packages/cgal_x64-windows/share/cgal
-- ------------debug_cmake: F:/vcpkg/packages/cgal_x64-windows/debug/share/cgal/CGALConfig-installation-dirs.cmake
-- ------------VCPKG_BUILD_TYPE:

...

-- Installing: F:/vcpkg/packages/cgal_x64-windows/share/cgal/usage
-- Performing post-build validation
Stored binaries in 1 destinations in 36 s.
Elapsed time to handle cgal:x64-windows: 3.2 min
cgal:x64-windows package ABI: 00d2ad2c6db2c73c182e3f704308cc94d7031504eb35d5bcc9577387457bafaf
Total install time: 23 min
The package cgal provides CMake targets:

    find_package(CGAL CONFIG REQUIRED)
    target_link_libraries(main PRIVATE CGAL::CGAL)
```

**Comment by MonicaLiu0311** [comment]
> ```
> Downloading https://github.com/CGAL/cgal/archive/v5.6.1.tar.gz
> ```

I can also download this link manually.

**Comment by winnonatural** [comment]
today   I  can download
yesterday can't
from china

**Comment by winnonatural** [comment]
D:\Code\vcpkg\vcpkg>.\vcpkg.exe install cgal:x64-windows
Computing installation plan...
The following packages will be built and installed:
    cgal:x64-windows@5.6.1
Detecting compiler hash for triplet x64-windows...
-- Setting "%SOCKS_PROXY%" environment variables to "127.0.0.1:1080".
Compiler found: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from C:\Users\lzs\AppData\Local\vcpkg\archives in 137 us. Use --debug to see more details.
Installing 1/1 cgal:x64-windows@5.6.1...
Building cgal:x64-windows@5.6.1...
-- Using cached CGAL-cgal-v5.6.1.tar.gz.
-- Extracting source D:/Code/vcpkg/vcpkg/downloads/CGAL-cgal-v5.6.1.tar.gz
-- Using source at D:/Code/vcpkg/vcpkg/buildtrees/cgal/src/v5.6.1-f2c46bdd3d.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/Code/vcpkg/vcpkg/packages/cgal_x64-windows/share/cgal/usage
-- Performing post-build validation
Stored binaries in 1 destinations in 820 ms.
Elapsed time to handle cgal:x64-windows: 44 s
cgal:x64-windows package ABI: 288bb2616dd5be5f33e1a03928c0dace5a2b977dcaf3f4717b896bdbc90d32be
Total install time: 44 s
The package cgal provides CMake targets:

    find_package(CGAL CONFIG REQUIRED)
    target_link_libraries(main PRIVATE CGAL::CGAL)
