### ISSUE TITLE
z85 encoding library

### ISSUE THREAD

**Issue by degski** [Microsoft/vcpkg#3777]
Please consider adding the [z85](https://github.com/artemkin/z85) library. it will add to the ZeroMQ collection.

**Comment by NancyLi1013** [comment]
Hi @degski , thanks for posting this issue. The port has been added to the vcpkg, please try to use it.

**Comment by degski** [comment]
@NancyLi1013 Did I miss something at school? Wasup here? The build output:

    Y:\vcpkg>vcpkg install z85
    Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
    The following packages will be built and installed:
        z85[core]:x64-windows-static
    Starting package 1/1: z85:x64-windows-static
    Building package z85[core]:x64-windows-static...
    -- Using cached Y:/vcpkg/downloads/artemkin-z85-v1.0.tar.gz
    -- Using source at Y:/vcpkg/buildtrees/z85/src/v1.0-8e33a1baf6
    -- Installing: Y:/vcpkg/packages/z85_x64-windows-static/include/z85/z85.h
    -- Installing: Y:/vcpkg/packages/z85_x64-windows-static/include/z85/z85.c
    -- Installing: Y:/vcpkg/packages/z85_x64-windows-static/include/z85/z85.hpp
    -- Installing: Y:/vcpkg/packages/z85_x64-windows-static/include/z85/z85_impl.cpp
    -- Installing: Y:/vcpkg/packages/z85_x64-windows-static/share/z85/copyright
    -- Performing post-build validation
    -- Performing post-build validation done
    Building package z85[core]:x64-windows-static... done
    Installing package z85[core]:x64-windows-static...
    Installing package z85[core]:x64-windows-static... done
    Elapsed time for package z85:x64-windows-static: 6.586 s

    Total elapsed time: 6.586 s

I didn't realize .c- and .cpp-files counted as valid header-only libraries, I'll go dig out the books :-) .
