### ISSUE TITLE
vcpkg.exe contact --survey does not work

### ISSUE THREAD

**Issue by espresso3389** [Microsoft/vcpkg#3778]
On bf6708576c4e0f7ccec52c9acbc1e220e3032e6b, `.\vcpkg.exe contact --survey` does not work correctly and shows an error dialog:

![image](https://user-images.githubusercontent.com/1311400/41821384-aa82c0e0-781a-11e8-884a-a1f96260b7d6.png)

**Comment by jasjuang** [comment]
I just tried with the latest master and it works for me. Do you want to do a git pull and try again?

**Comment by espresso3389** [comment]
Wow, I realized that Windows 10 1803 correctly handle the request but Insider Preview 17704 (RS5) does not handle it correctly. I'll file it on Feedback Hub. Sorry for bothering you. Thanks.
