### ISSUE TITLE
[cudnn] Build error on x64-windows

### ISSUE THREAD

**Issue by AbSomeone** [microsoft/vcpkg#37799]
Package: cudnn:x64-windows@7.6.5#10

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.29.30152.0
-    vcpkg-tool version: 2024-03-14-7d353e869753e5609a1f1a057df3db8fd356e49d
    vcpkg-scripts version: 3c76dc55f 2024-03-27 (11 hours ago)

**To Reproduce**

`vcpkg install dlib[cuda]:x64-windows`
**Failure logs**

```
-- Found CUDA V12.1.105
-- CUDNN_INCLUDE_DIR: CUDNN_INCLUDE_DIR-NOTFOUND
-- CUDNN_LIBRARY: CUDNN_LIBRARY-NOTFOUND
CMake Error at ports/cudnn/portfile.cmake:58 (message):
  Please download CUDNN from official sources (such as
  https://developer.nvidia.com/rdp/cudnn-download ) and extract the zip into
  your CUDA_TOOLKIT_ROOT (C:/Program Files/NVIDIA GPU Computing
  Toolkit/CUDA/v12.1).  (For example: tar.exe -xvf
  cudnn-11.2-windows-x64-v8.1.1.33.zip --strip 1 --directory "C:/Program
  Files/NVIDIA GPU Computing Toolkit/CUDA/v12.1"
Call Stack (most recent call first):
  scripts/ports.cmake:175 (include)

**Comment by jimwang118** [comment]
You need to install cudnn locally and match the cuda version.

**Comment by jimwang118** [comment]
> I disagree. The cudnn vpkg package should match the installed version of CUDA. Not the other way around.

cudnn in vcpkg also searches for locally installed packages and obtains the required files.

**Comment by dannypike** [comment]
I'm sorry but I don't understand why you said that?

My point was that you say we should install a version of CUDA to match the vcpkg package. I say that it is the other way around.

VCPKG should provide packages to match whatever supported version of CUDA that may be installed.

I have CUDA 11.8 on this PC because that is the version that matches what my customer is using. CUDA 11.8 is still supported by nVidia, so vcpkg should support it, too. If that needs two varieties of pakcage, then that is what vcpkg should have.

**Comment by jimwang118** [comment]
> I'm sorry but I don't understand why you said that?
> 
> My point was that you say we should install a version of CUDA to match the vcpkg package. I say that it is the other way around.
> 
> VCPKG should provide packages to match whatever valid and supported version of CUDA may be installed.
> 
> I have CUDA 11.8 on this PC because that is the version that matches what my customer is using. CUDA 11.8 is still supported by nVidia, so vcpkg should support it, too. If that needs two varieties of the vcpkg package, then that is what vcpkg should have.

You do not need to install cuda that matches vcpkg. You only need to install cuda and cudnn on your local machine to match each other. vcpkg has no restrictions on cuda versions.
In addition, you can check the `portfile.cmake` files of `cuda` and `cudnn` and find that they are not compiled from source code, but obtain available libraries by looking for locally installed files.

**Comment by dannypike** [comment]
Thank you for the clarification.

**Comment by jimwang118** [comment]
If the above reply can solve your problem, I will close the issue.

**Comment by dannypike** [comment]
Are you asking me? I am happy, thank you, but I am not the original poster.

**Comment by jimwang118** [comment]
> Are you asking me? I am happy, thank you, but I am not the original poster.

Thanks for the reply, it would be great to help you solve the problem. 
@AbSomeone , can you install cuda normally by installing cudnn?
