### ISSUE TITLE
[duktape] find_package_handle_standard_args argument should be lowercase

### ISSUE THREAD

**Issue by alandefreitas** [microsoft/vcpkg#37807]
### Is your feature request related to a problem? Please describe.

The following command

https://github.com/microsoft/vcpkg/blob/3c76dc55f8bd2b7f4824bcd860055094bfbbb9ea/ports/duktape/duktapeConfig.cmake.in#L22-L23

should use `duktape` in lowercase.

It works fine on linux but it gives me a warning on windows:

```
CMake Warning (dev) at .../bin/cmake/win/x64/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (Duktape)
  does not match the name of the calling package (duktape).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  build/debwithopt-msvc/vcpkg_installed/x64-windows/share/duktape/duktapeConfig.cmake:22 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  .../vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  CMakeLists.txt:106 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

### Proposed solution

Make it lowercase

### Describe alternatives you've considered

Using variants of lowercase and capitalized. But it's impossible to get to a general solution this way. Capitalized name won't find the config file. Lowercase will lead to the warning.

**Comment by dg0yt** [comment]
OMG. What a mess.

**Comment by dg0yt** [comment]
Duplicates #35308.
