### ISSUE TITLE
Using a port-version in a package dependency results in incomparable versions

### ISSUE THREAD

**Issue by kevin--** [microsoft/vcpkg#37804]
Escalating this to a bug because this doesn't seem like correct behavior:

### Discussed in https://github.com/microsoft/vcpkg/discussions/37539

<div type='discussions-op-text'>

<sup>Originally posted by **kevin--** March 18, 2024</sup>
We have an internal library which depends on `libsamplerate` 0.2.2#1. 

According to https://learn.microsoft.com/en-us/vcpkg/reference/vcpkg-json#dependency-version-gt in this case it is valid to specify the dependency version include port-number like so:
```
    {
      "name": "libsamplerate",
      "version>=": "0.2.2#1"
    },
```

However when we run install, it doesn't compare the version strings correctly, leading to us having to override the dependency on the consuming-project level which is unideal.

What can we do to rectify this, as specifying `port-version` in the dependencies is also an error.

```
-- Running vcpkg install
Fetching registry information from /Users/xxx/projects/vcpkg-registry (HEAD)...
Fetching registry information from git@github.com:microsoft/vcpkg.git (HEAD)...
error: version conflict on libsamplerate:arm64-osx: opdsp:arm64-osx@1.1.1 required 0.2.2#1, which cannot be compared with the baseline version 0.2.2.

The versions have incomparable schemes:
  libsamplerate@0.2.2 has scheme string
  libsamplerate@0.2.2#1 has scheme relaxed

This can be resolved by adding an explicit override to the preferred version. For example:

  "overrides": [
    { "name": "libsamplerate", "version": "0.2.2" }
  ]

See `vcpkg help versioning` or https://learn.microsoft.com/vcpkg/users/versioning for more information.
-- Running vcpkg install - failed
```

**Comment by Osyotr** [comment]
Vcpkg port can't change it's version scheme without version bump, so your users should update their baselines or use overrides.

**Comment by kevin--** [comment]
> Vcpkg port can't change it's version scheme without version bump, so your users should update their baselines or use overrides.

We have worked around it by changing the baseline thanks for the info.

IMO this feels like a defect, as bugs in ports can be very relevant to end dev experience
