### ISSUE TITLE
aws-sdk-cpp x64-windows-static-md fails with apparent CPP standard error

### ISSUE THREAD

**Issue by VikingExplorer** [microsoft/vcpkg#37805]
### Discussed in https://github.com/microsoft/vcpkg/discussions/37735

<div type='discussions-op-text'>

<sup>Originally posted by **VikingExplorer** March 26, 2024</sup>
I haven't used vcpkg in a year or two. Does anyone have an idea what's going wrong?

I'm using VS2022 17.9.4, v143

C:\Dev\Couloir\3pLibs\vcpkg>.\vcpkg install aws-sdk-cpp[apigateway,apigatewayv2,appsync,autoscaling,autoscaling-plans,budgets,core,dynamodb,ec2,email,glacier,iam,imagebuilder,lambda,lex,lex-models,location,logs,managedblockchain,pricing,rds,rds-data,s3,secretsmanager,sms,sns,sqs,translate,wellarchitected,xray]:x64-windows-static-md --recurse

**warning: vcpkg appears to be in a Visual Studio prompt targeting x86 but installing for x64-windows-static-md. Consider using --triplet x86-windows or --triplet x86-uwp.**

CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/Dev/Couloir/3pLibs/vcpkg/downloads/tools/cmake-3.29.0-windows/cmake-3.29.0-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j17
    Working Directory: C:/Dev/Couloir/3pLibs/vcpkg/buildtrees/aws-c-cal/x64-windows-static-md-dbg
    See logs for more information:
      C:\Dev\Couloir\3pLibs\vcpkg\buildtrees\aws-c-cal\install-x64-windows-static-md-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:102 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/aws-c-cal/portfile.cmake:17 (vcpkg_cmake_install)
  scripts/ports.cmake:175 (include)

error: building aws-c-cal:x64-windows-static-md failed with: BUILD_FAILED
Elapsed time to handle aws-c-cal:x64-windows-static-md: 4.7 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+aws-c-cal
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[aws-c-cal]+Build+error+on+x64-windows-static-md&body=Copy+issue+body+from+C%3A%2FDev%2FCouloir%2F3pLibs%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
</div>

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. I can't repro this issue locally, I could install `aws-sdk-cpp[apigateway,apigatewayv2,appsync,autoscaling,autoscaling-plans,budgets,core,dynamodb,ec2,email,glacier,iam,imagebuilder,lambda,lex,lex-models,location,logs,managedblockchain,pricing,rds,rds-data,s3,secretsmanager,sms,sns,sqs,translate,wellarchitected,xray]:x64-windows-static-md` succeed on the latest vcpkg.

```
Installing 13/13 aws-sdk-cpp[apigateway,apigatewayv2,appsync,autoscaling,autoscaling-plans,budgets,core,dynamodb,ec2,email,glacier,iam,imagebuilder,lambda,lex,lex-models,location,logs,managedblockchain,pricing,rds,rds-data,s3,secretsmanager,sms,sns,sqs,translate,wellarchitected,xray]:x64-windows-static-md@1.11.285...
Building aws-sdk-cpp[apigateway,apigatewayv2,appsync,autoscaling,autoscaling-plans,budgets,core,dynamodb,ec2,email,glacier,iam,imagebuilder,lambda,lex,lex-models,location,logs,managedblockchain,pricing,rds,rds-data,s3,secretsmanager,sms,sns,sqs,translate,wellarchitected,xray]:x64-windows-static-md@1.11.285...
F:\0326\triplets\community\x64-windows-static-md.cmake: info: loaded community triplet from here. Community triplets are not built in the curated registry and are thus less likely to succeed.
-- Downloading https://github.com/aws/aws-sdk-cpp/archive/1.11.285.tar.gz -> aws-aws-sdk-cpp-1.11.285.tar.gz...
-- Extracting source F:/0326/downloads/aws-aws-sdk-cpp-1.11.285.tar.gz
-- Applying patch patch-relocatable-rpath.patch
-- Applying patch fix-aws-root.patch
-- Applying patch lock-curl-http-and-tls-settings.patch
-- Using source at F:/0326/buildtrees/aws-sdk-cpp/src/1.11.285-786fbfbeca.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-static-md-dbg
-- Configuring x64-windows-static-md-rel
-- Building x64-windows-static-md-dbg
-- Building x64-windows-static-md-rel
-- Installing: F:/0326/packages/aws-sdk-cpp_x64-windows-static-md/share/aws-sdk-cpp/copyright
-- Performing post-build validation
Elapsed time to handle aws-sdk-cpp:x64-windows-static-md: 6.4 min
aws-sdk-cpp:x64-windows-static-md package ABI: 27e7bbe15c58845f02b4f5b6cdd175690f6768202046d2bc2cb5c3c58e2e61e4
Total install time: 7.4 min
The package aws-sdk-cpp:x64-windows-static-md provides CMake targets:

    When using AWSSDK, AWSSDK_ROOT_DIR must be defined by the user.
    find_package(AWSSDK CONFIG COMPONENTS core dynamodb kinesis s3 REQUIRED)
    target_include_directories(main PRIVATE ${AWSSDK_INCLUDE_DIRS})
    target_link_libraries(main PRIVATE ${AWSSDK_LIBRARIES})

    OR

    find_package(aws-cpp-sdk-core REQUIRED)
    target_include_directories(main PRIVATE aws-cpp-sdk-core)
    target_link_libraries(main PRIVATE aws-cpp-sdk-core)

PS F:\0326> .\vcpkg.exe --version
vcpkg package management program version 2024-03-14-7d353e869753e5609a1f1a057df3db8fd356e49d
```

**Comment by VikingExplorer** [comment]
Lily, did you use recurse?

./vcpkg install aws-sdk-cpp[apigateway,apigatewayv2,appsync,autoscaling,autoscaling-plans,budgets,core,dynamodb,ec2,email,glacier,iam,imagebuilder,lambda,lex,lex-models,location,logs,managedblockchain,pricing,rds,rds-data,s3,secretsmanager,sms,sns,sqs,translate,wellarchitected,xray]:x64-windows-static-md --recurse

**Comment by VikingExplorer** [comment]
PS C:\Dev\Couloir\3pLibs\vcpkg> ./vcpkg install aws-sdk-cpp[apigateway,apigatewayv2,appsync,autoscaling,autoscaling-plans,budgets,core,dynamodb,ec2,email,glacier,iam,imagebuilder,lambda,lex,lex-models,location,logs,managedblockchain,pricing,rds,rds-data,s3,secretsmanager,sms,sns,sqs,translate,wellarchitected,xray]:x64-windows-static-md
Computing installation plan...
The following packages will be built and installed:
  * aws-c-auth:x64-windows-static-md@0.7.16
  * aws-c-cal:x64-windows-static-md@0.6.10
  * aws-c-compression:x64-windows-static-md@0.2.18
  * aws-c-http:x64-windows-static-md@0.8.1
  * aws-c-io:x64-windows-static-md@0.14.6
  * aws-c-mqtt:x64-windows-static-md@0.10.3
  * aws-c-s3:x64-windows-static-md@0.5.3
  * aws-c-sdkutils:x64-windows-static-md@0.1.15
  * aws-crt-cpp:x64-windows-static-md@0.26.4
    aws-sdk-cpp[apigateway,apigatewayv2,appsync,autoscaling,autoscaling-plans,budgets,core,dynamodb,ec2,email,glacier,iam,imagebuilder,lambda,lex,lex-models,location,logs,managedblockchain,pricing,rds,rds-data,s3,secretsmanager,sms,sns,sqs,translate,wellarchitected,xray]:x64-windows-static-md@1.11.285
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows-static-md...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from C:\Users\gunna\AppData\Local\vcpkg\archives in 406 us. Use --debug to see more details.
Installing 1/10 aws-c-cal:x64-windows-static-md@0.6.10...
Building aws-c-cal:x64-windows-static-md@0.6.10...
C:\Dev\Couloir\3pLibs\vcpkg\triplets\community\x64-windows-static-md.cmake: info: loaded community triplet from here. Community triplets are not built in the curated registry and are thus less likely to succeed.
-- Using cached awslabs-aws-c-cal-v0.6.10.tar.gz.
-- Cleaning sources at C:/Dev/Couloir/3pLibs/vcpkg/buildtrees/aws-c-cal/src/v0.6.10-73dc1009ad.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Dev/Couloir/3pLibs/vcpkg/downloads/awslabs-aws-c-cal-v0.6.10.tar.gz
-- Applying patch remove-libcrypto-messages.patch
-- Using source at C:/Dev/Couloir/3pLibs/vcpkg/buildtrees/aws-c-cal/src/v0.6.10-73dc1009ad.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-static-md
-- Building x64-windows-static-md-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/Dev/Couloir/3pLibs/vcpkg/downloads/tools/cmake-3.29.0-windows/cmake-3.29.0-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j17
    Working Directory: C:/Dev/Couloir/3pLibs/vcpkg/buildtrees/aws-c-cal/x64-windows-static-md-dbg
    See logs for more information:
      C:\Dev\Couloir\3pLibs\vcpkg\buildtrees\aws-c-cal\install-x64-windows-static-md-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:102 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/aws-c-cal/portfile.cmake:17 (vcpkg_cmake_install)
  scripts/ports.cmake:175 (include)


error: building aws-c-cal:x64-windows-static-md failed with: BUILD_FAILED
Elapsed time to handle aws-c-cal:x64-windows-static-md: 4.1 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.

**Comment by dg0yt** [comment]
Note: the failing port is `aws-c-cal`. 
You should read and provide the log:
~~~
 C:\Dev\Couloir\3pLibs\vcpkg\buildtrees\aws-c-cal\install-x64-windows-static-md-dbg-out.log

**Comment by VikingExplorer** [comment]
Kai, I did at the Discussion (linked above).  Here it is again:

install-x64-windows-static-md-dbg-out.log

C:\PROGRA1\MIB0551\2022\COMMUN1\VC\Tools\MSVC\14391.335\bin\Hostx64\x64\cl.exe -DDEBUG_BUILD -IC:\Dev\Couloir\3pLibs\vcpkg\buildtrees\aws-c-cal\src\v0.6.10-73dc1009ad.clean\include -external:IC:\Dev\Couloir\3pLibs\vcpkg\installed\x64-windows-static-md\include -external:W0 /nologo /DWIN32 /D_WINDOWS /utf-8 /MP /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /W4 /WX /MP /volatile:iso /showIncludes /FoCMakeFiles\aws-c-cal.dir\source\cal.c.obj /FdCMakeFiles\aws-c-cal.dir\aws-c-cal.pdb /FS -c C:\Dev\Couloir\3pLibs\vcpkg\buildtrees\aws-c-cal\src\v0.6.10-73dc1009ad.clean\source\cal.c
C:\Dev\Couloir\3pLibs\vcpkg\buildtrees\aws-c-cal\src\v0.6.10-73dc1009ad.clean\include\aws/cal/cal.h(15): error C2220: the following warning is treated as an error
C:\Dev\Couloir\3pLibs\vcpkg\buildtrees\aws-c-cal\src\v0.6.10-73dc1009ad.clean\include\aws/cal/cal.h(15): warning C4431: missing type specifier - int assumed. Note: C no longer supports default-int
C:\Dev\Couloir\3pLibs\vcpkg\buildtrees\aws-c-cal\src\v0.6.10-73dc1009ad.clean\include\aws/cal/cal.h(15): error C2054: expected '(' to follow 'AWS_PUSH_SANE_WARNING_LEVEL'
C:\Dev\Couloir\3pLibs\vcpkg\buildtrees\aws-c-cal\src\v0.6.10-73dc1009ad.clean\include\aws/cal/cal.h(20): error C2296: '<<': not valid as left operand has type 'char [3]'
C:\Dev\Couloir\3pLibs\vcpkg\buildtrees\aws-c-cal\src\v0.6.10-73dc1009ad.clean\include\aws/cal/cal.h(20): error C2297: '<<': not valid as right operand has type 'char [3]'
C:\Dev\Couloir\3pLibs\vcpkg\buildtrees\aws-c-cal\src\v0.6.10-73dc1009ad.clean\include\aws/cal/cal.h(20): error C2056: illegal expression

**Comment by VikingExplorer** [comment]
Just reproduced again.  What could be the difference in our environments?   Here are my steps:

1. Open Windows Powershell 
2. cd C:\Dev\Couloir\3pLibs\vcpkg
3. ./bootstrap-vcpkg.bat 
4. git pull
5. ./vcpkg update   (to see what is out of date)
6. ./vcpkg install aws-sdk-cpp[apigateway,apigatewayv2,appsync,autoscaling,autoscaling-plans,budgets,core,dynamodb,ec2,email,glacier,iam,imagebuilder,lambda,lex,lex-models,location,logs,managedblockchain,pricing,rds,rds-data,s3,secretsmanager,sms,sns,sqs,translate,wellarchitected,xray]:x64-windows-static-md --recurse

**Comment by VikingExplorer** [comment]
The update produced a list.   Just noticed these two:
        vcpkg-cmake:x64-windows          2021-02-28 -> 2023-05-04
        vcpkg-cmake-config:x64-windows   2021-02-26 -> 2022-02-06#1

PS C:\Dev\Couloir\3pLibs\vcpkg> cmake --version
cmake version 3.29.0

**Comment by VikingExplorer** [comment]
**How is one supposed to update a package?**

PS C:\Dev\Couloir\3pLibs\vcpkg> ./vcpkg install vcpkg-cmake:x64-windows --recurse
Computing installation plan...
The following packages are already installed:
    vcpkg-cmake:x64-windows@2021-02-28
vcpkg-cmake:x64-windows is already installed

**Comment by VikingExplorer** [comment]
I did a remove operation on those vcpkg-cmake packages (certainly irrelevant), but also on 3 aws packages.

After that, the aws build worked!

**Comment by VikingExplorer** [comment]
**The problem appeared to be the 3 aws packages:**

PS C:\Dev\Couloir\3pLibs\vcpkg> ./vcpkg remove vcpkg-cmake-config:x64-windows --recurse
The following packages will be removed:
vcpkg-cmake-config:x64-windows
Removing 1/1 vcpkg-cmake-config:x64-windows
PS C:\Dev\Couloir\3pLibs\vcpkg> ./vcpkg update
Using local portfile versions. To update the local portfiles, use git pull.
The following packages differ from their port versions:
aws-c-common:x64-windows-static-md 0.4.56 -> 0.9.14
aws-c-event-stream:x64-windows-static-md 0.1.6 -> 0.4.2
aws-checksums:x64-windows-static-md 0.1.9 -> 0.1.18

**Comment by VikingExplorer** [comment]
**Lesson is that packages with Features can't be upgraded. Also, make sure to remove all related packages before attempting to install again.**
 
Won't work: PS C:\Dev\Couloir\3pLibs\vcpkg> ./vcpkg upgrade aws-sdk-cpp[apigateway,apigatewayv2,appsync,autoscaling,autoscaling-plans,budgets,core,dynamodb,ec2,email,glacier,iam,imagebuilder,lambda,lex,lex-models,location,logs,managedblockchain,pricing,rds,rds-data,s3,secretsmanager,sms,sns,sqs,translate,wellarchitected,xray]:x64-windows-static-md
**error: List of features is not allowed in this context**

**My updated procedure:**
UPDATE
1. Open Windows Powershell  
2. cd C:\Dev\Couloir\3pLibs\vcpkg
3. ./bootstrap-vcpkg.bat
4. git pull
5. ./vcpkg update   (to see what is out of date)
6. install or upgrade from PACKAGE LIST  (or all at once: ./vcpkg upgrade --no-dry-run)
---------------------
FIRST TIME
1. install 64 bit git (https://git-scm.com/download/win)
2. Open Windows Powershell
3. cd C:\Dev\Couloir\3pLibs
4. git clone https://github.com/Microsoft/vcpkg
