### ISSUE TITLE
Export Configuration using INSTALL_INTERFACE doesn't work in debug.

### ISSUE THREAD

**Issue by kobalicek** [microsoft/vcpkg#37806]
**Describe the bug**

I'm trying to publish a package that follows CMake "best practices", it uses the following bits in a cmake file to properly export the required interface:

```cmake
target_include_directories(some_library PUBLIC
  $<BUILD_INTERFACE:${CMAKE_CURRENT_LIST_DIR}/include>
  $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>
)

# Then it generates the exports:

install(TARGETS some_library
        EXPORT some_library-config
        RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}"
        ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}"
        LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}"
        INCLUDES DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}")

install(EXPORT some_library-config
        NAMESPACE some_library::
        DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/some_library")
```

This is all pretty much a CMake way of generating the exports, at least according to the CMake documentation linked below:

  * https://cmake.org/cmake/help/latest/guide/tutorial/Adding%20Export%20Configuration.html

Now when I want to package this library as a vcpkg package and follow the documentation on vcpkg side:

  * https://learn.microsoft.com/en-us/vcpkg/get_started/get-started-packaging

The following is suggested:

```cmake
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
```

As it "Deletes the include directory from the debug installation to prevent overlap". Packaging this package works, but consuming doesn't, because then cmake complains that it includes a directory that doesn't exist:

```
CMake Error in CMakeLists.txt:
  Imported target "some_library::some_library" includes non-existent path

    "$HOME/some_project/build/Debug/vcpkg_installed/arm64-osx/debug/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

I'm not sure what to do about this, especially why I should remove include files in debug builds - I understand that it's a saving in multi-configuration generators, but it just doesn't work with regular cmake projects that generate exports the recommended way.

Is this a bug? Is there a solution or a recommended way of dealing with this?

**Comment by Neumann-A** [comment]
Post your portfile. You are probably missing a vcpkg_cmake_config_fixup() call

**Comment by kobalicek** [comment]
Indeed, it's not there!

Thanks, this is really great to know that it's a bug on my side.

BTW I'm upgrading a portfile that I didn't create and `vcpkg_cmake_config_fixup` was missing there, but I don't know whether it was missing because it's ancient or because it was buggy all the time.
