### ISSUE TITLE
jemalloc built with triplet x64-windows-static generates dll

### ISSUE THREAD

**Issue by degski** [Microsoft/vcpkg#3781]
The case might well be that building jemalloc with `x64-windows-static` is not a good idea. What I don't know is which crt it is linked to. It could be that it's now a dll with /MT. tbb does not allow that, jemalloc probably shouldn't allow that either. The library, including its dll end up in ..\installed\x64-windows-static. The workaround to problem in #3780 obviously makes this moot.

**Comment by JackBoosY** [comment]
Hi @degski , thanks for reporting this issue!
I've fixed this issue just now. Please update vcpkg and rebuild jemalloc with x64-windows-static.
Thanks.
