### ISSUE TITLE
cpp_redis artifacts do not work in Visual Studio 207

### ISSUE THREAD

**Issue by unclevlad** [Microsoft/vcpkg#3782]
I originally thought this was a problem with cpp_redis, but cloning and building the current version from GitHub shows that works fine, and vcpkg is supposedly the same version.

Steps to Reproduce:
1. Install cpp_redis in vcpkg
2. Create brand new solution in VS 2017 - Windows console application - Debug - 64bit
3. Gut all the precompiled header stuff
4. Cut and paste https://github.com/Cylix/cpp_redis/blob/master/examples/cpp_redis_client.cpp
5. Build and run
6. Watch the deadlock in tacopie::io_service::thread_pool::stop( ) line 85

**Comment by Cheney-W** [comment]
@unclevlad , I can't reproduce this issue with the latest vcpkg:2018.11.23-nohash and VS2017 15.9.7.
Please open a new issue if this is still a problem for you.
