### ISSUE TITLE
[jsoncpp] CodeQL Compiler missing Control Flow Guard in JsonCpp DLL file

### ISSUE THREAD

**Issue by ndjenguerian** [microsoft/vcpkg#37838]
Environment
- OS: [Windows]

Description:
We have received a warning that vcpkg json cpp [here](https://github.com/microsoft/vcpkg/tree/1921ac8524ac6a4c1acb4594fa2426bfeb1aeb1b/ports/jsoncpp) is missing the Control Flow Guard

It is important that the compiler for jsoncpp pass the /guard:cf on both the compiler and linker command lines. Binaries also require the /DYNAMICBASE linker option in order to enable CFG.

**Comment by JonLiu1993** [comment]
@ndjenguerian, thanks for posting this question, please provide more information about your error and steps to reproduce.
