### ISSUE TITLE
[grpc] CodeQL Compiler Disablement Warnings in Lib Files

### ISSUE THREAD

**Issue by ndjenguerian** [microsoft/vcpkg#37835]
Environment
- OS: [Windows]

Description:

We have received vcpkg grpc CodeQL compiler disablement warnings in lib files for codes 4146, 4244, 4267, and 4996

vcpkg appears to be using [grpc version 1.51](https://github.com/microsoft/vcpkg/blob/master/ports/grpc/vcpkg.json), which has disablements for codes 4244, 4267, and 4996 [here](https://github.com/grpc/grpc/blob/v1.51.x/CMakeLists.txt)

Additionally, it appears vcpkg grpc is using external packages [here](https://github.com/microsoft/vcpkg/blob/master/ports/grpc/portfile.cmake), which include ZLIB, SSL, PROTOBUF, ABSL, UPB, RE2, and CARES

It is important that the lib files in these external packages also do not have compiler disablements for codes 4146, 4244, 4267, and 4996

**Comment by Cheney-W** [comment]
@ndjenguerian 
I have checked `grpc` and its dependencies, and except for the port `upb`, which adds a `/wd4146` option through the `0001-make-cmakelists-py.patch` file, the disable warning options in other ports are all set by upstream.
So if you want to remove this option during the port build process, you should submit your request upstream, or you can use your own [overlay port](https://learn.microsoft.com/en-us/vcpkg/concepts/overlay-ports) which removed those option locally.
