### ISSUE TITLE
[grpc] CodeQL Compiler missing Control Flow Guard in Third Party DLL files

### ISSUE THREAD

**Issue by ndjenguerian** [microsoft/vcpkg#37836]
Environment
- OS: [Windows]

Description:

It appears vcpkg grpc is using external packages [here](https://github.com/microsoft/vcpkg/blob/master/ports/grpc/portfile.cmake), including ZLIB, SSL, PROTOBUF, ABSL, UPB, RE2, and CARES

It is important that the compiler for these third party dll files pass the /guard:cf on both the compiler and linker command lines. Binaries also require the /DYNAMICBASE linker option in order to enable CFG.

We have received particular warnings for libprotoc.dll (from PROTOBUF), libprotobuf.dll (from PROTOBUF), libprotobuf-lite.dll (from PROTOBUF) cares.dll (from CARES), and libcrypto-1_1-x64.dll (from SSL)

**Comment by jimwang118** [comment]
Please provide steps to reproduce these issues.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
