### ISSUE TITLE
Installing vcpkg before Visual Studio should be warned against

### ISSUE THREAD

**Issue by DukeOfErl** [Microsoft/vcpkg#3783]
I bootstrapped vcpkg before installing VS. 
Even though I used 'vcpkg integrate install', VS did not find the libraries i wanted to include.
Redoing 'integrate install' did not help
After deleting vcpkg and re-bootstrapping it, everything worked fine.

I imagine this cannot be helped (since vcpkg is implemented in a self-contained folder?), but this should be mentioned in the tutorial. 

For context, I bootstrapped vcpkg before installing VS because I originally planned to use vcpkg with Clion.
Only after failing to make vcpkg work for me in Clion (with minGW), I decided to switch to VS.

Making people switch IDE to VS because of cool features like vcpkg is probably something Microsoft should encourage, so you might want to mention this issue in the documentation.

**Comment by Cheney-W** [comment]
We have mentioned the essential environment and tools in [Quick Start](https://github.com/Microsoft/vcpkg/blob/master/README.md#quick-start), so close this issue.
