### ISSUE TITLE
[boost] build failure

### ISSUE THREAD

**Issue by 20072330** [microsoft/vcpkg#37850]
### Operating system

Centos

### Steps to reproduce the behavior

```Shell
./vcpkg install boost
```

### Failure logs

Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Compiler found: /opt/rh/devtoolset-11/root/usr/bin/c++
Restored 0 package(s) from /root/.cache/vcpkg/archives in 1.31 ms. Use --debug to see more details.
Installing 1/47 liblzma:x64-linux@5.6.0...
Building liblzma:x64-linux@5.6.0...
-- Downloading https://github.com/tukaani-project/xz/archive/v5.6.0.tar.gz -> tukaani-project-xz-v5-0aa74e01.6.0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from /opt/vcpkg/vcpkg-bundle.json
[DEBUG] Failed to open: /opt/vcpkg/vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
[DEBUG] 1000: execute_process(curl --fail -L https://github.com/tukaani-project/xz/archive/v5.6.0.tar.gz --create-dirs --output /opt/vcpkg/downloads/tukaani-project-xz-v5-0aa74e01.6.0.tar.gz.8788.part)
[DEBUG] 1000: cmd_execute_and_stream_data() returned 0 after  1065685 us
[DEBUG] Trying to hash /opt/vcpkg/downloads/tukaani-project-xz-v5-0aa74e01.6.0.tar.gz.8788.part
[DEBUG] /opt/vcpkg/downloads/tukaani-project-xz-v5-0aa74e01.6.0.tar.gz.8788.part has hash 9a7678b06523cb36a7e4cefea44402e4221f601fb72ec5492783e372167b5185398effaa9b029b4bc4c8a9930de5f45a73f2267b0403a5c97c46f6b550142b1c
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/tukaani-project/xz/archive/v5.6.0.tar.gz
File: /opt/vcpkg/downloads/tukaani-project-xz-v5-0aa74e01.6.0.tar.gz.8788.part
Expected hash: 0aa74e01c019c1d3893cf16f53b300ba4e74c6aa9febabf57ddb49b28615d76862eeb746c54c2085efd37c7e8cc0829014d9b7ad481a76294bc929b3cca91336
Actual hash: 9a7678b06523cb36a7e4cefea44402e4221f601fb72ec5492783e372167b5185398effaa9b029b4bc4c8a9930de5f45a73f2267b0403a5c97c46f6b550142b1c
[DEBUG] /mnt/vss/_work/1/s/src/vcpkg/base/downloads.cpp(1031): 
[DEBUG] Time in subprocesses: 1065685us
[DEBUG] Time in parsing JSON: 7us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 228us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 1.1 s (1066714us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
      

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/liblzma/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:175 (include)

error: building liblzma:x64-linux failed with: BUILD_FAILED
Elapsed time to handle liblzma:x64-linux: 2.3 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+liblzma
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[liblzma]+Build+error+on+x64-linux&body=Copy+issue+body+from+%2Fopt%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

The branch "https://github.com/tukaani-project/xz/archive/v5.6.0.tar.gz" is not found.
[https://github.com/tukaani-project/xz/archive/v5.6.0.tar.gz
![Pic](https://github.com/microsoft/vcpkg/assets/32033879/df3373af-b76a-4ab5-96e1-f1d2e9d475a5)
](url)

**Comment by BA7LYA** [comment]
Same.

**Comment by BA7LYA** [comment]
After googling i got this, ["backdoor in upstream xz/liblzma leading to ssh server compromise"](https://www.openwall.com/lists/oss-security/2024/03/29/4), well, it make sense now.

**Comment by dg0yt** [comment]
Is there anything that we can do to make users report liblzma errors as liblzma errors? There is already
~~~
error: building liblzma:x64-linux failed with: BUILD_FAILED
Elapsed time to handle liblzma:x64-linux: 2.3 s
Please ensure you're using the latest port files with git pull and vcpkg update.
Then check for known issues at:
https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+liblzma
You can submit a new issue at:
[https://github.com/microsoft/vcpkg/issues/new?title=[liblzma]+Build+error+on+x64-linux&body=Copy+issue+body+from+%2Fopt%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md](https://github.com/microsoft/vcpkg/issues/new?title=%5Bliblzma%5D+Build+error+on+x64-linux&body=Copy+issue+body+from+%2Fopt%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md)
~~~
At least in the Visual Studio Code console, these links are clickable.

**Comment by WangWeiLin-MV** [comment]
Duplicate #37839
