### ISSUE TITLE
[liblzma] Build error on x86-windows

### ISSUE THREAD

**Issue by kossiLeBeau** [microsoft/vcpkg#37870]
Computing installation plan...
The following packages will be built and installed:
  * liblzma:x86-windows@5.4.4
    tiff[core,jpeg,lzma,zip]:x86-windows@4.6.0#4
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x86/cl.exe
Restored 0 package(s) from P:\VCPKG-CACHE in 931 us. Use --debug to see more details.
Installing 1/2 liblzma:x86-windows@5.4.4...
Building liblzma:x86-windows@5.4.4...
-- Downloading https://github.com/tukaani-project/xz/archive/v5.4.4.tar.gz -> tukaani-project-xz-v5.4.4.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Disabling metrics because vcpkg.disable-metrics exists
[DEBUG] Trying to load bundleconfig from E:\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: E:\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://github.com/tukaani-project/xz/archive/v5.4.4.tar.gz
[DEBUG] Trying to hash E:\vcpkg\downloads\tukaani-project-xz-v5.4.4.tar.gz.13692.part
[DEBUG] E:\vcpkg\downloads\tukaani-project-xz-v5.4.4.tar.gz.13692.part has hash 13d031c83e56cf2ffdb5936e65139c4dbd4ab2ccfd914debfe41ed627cb8d71021c5f5aae633e2ef82bc62ee29a6898075cfd5dc51611ac1af21518c99705950
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/tukaani-project/xz/archive/v5.4.4.tar.gz
File: E:\vcpkg\downloads\tukaani-project-xz-v5.4.4.tar.gz.13692.part
Expected hash: c28461123562564e030f3f733f078bc4c840e87598d9f4b718d4bca639120d8133f969c45d7bdc62f33f081d789ec0f14a1791fb7da18515682bfe3c0c7362e0
Actual hash: 13d031c83e56cf2ffdb5936e65139c4dbd4ab2ccfd914debfe41ed627cb8d71021c5f5aae633e2ef82bc62ee29a6898075cfd5dc51611ac1af21518c99705950
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1031): 
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 3us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 191us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 690 ms (690185us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
      

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/liblzma/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:175 (include)

error: building liblzma:x86-windows failed with: BUILD_FAILED
Elapsed time to handle liblzma:x86-windows: 799 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+liblzma
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[liblzma]+Build+error+on+x86-windows&body=Copy+issue+body+from+E%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by dg0yt** [comment]
https://github.com/microsoft/vcpkg/issues/37839

**Comment by WangWeiLin-MV** [comment]
Duplicate #37839
