### ISSUE TITLE
[ffmpeg] update to 7.0

### ISSUE THREAD

**Issue by 3alisaki** [microsoft/vcpkg#37888]
### Library name

ffmpeg

### New version number

7.0

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. The upstream has not yet released the tag for version 7.0. Once the upstream releases version 7.0, we will update `ffmpeg` to 7.0.

**Comment by thomvil** [comment]
Is this the upstream tag? https://github.com/FFmpeg/FFmpeg/releases/tag/n7.0
