### ISSUE TITLE
[freeglut] Build error on x64-osx

### ISSUE THREAD

**Issue by DrHomer** [microsoft/vcpkg#37884]
[main] Configuring project: opengl 
[proc] Executing command: /usr/local/bin/cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++ -S/Users/kirilleremeev/00_dev/0300_test/00_opengl/opengl -B/Users/kirilleremeev/00_dev/0300_test/00_opengl/opengl/build -G "Unix Makefiles"
[cmake] Not searching for unused variables given on the command line.
[cmake] -- Running vcpkg install
[cmake] Detecting compiler hash for triplet x64-osx...
[cmake] Compiler found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
[cmake] The following packages will be built and installed:
[cmake]   * freeglut:x64-osx@3.4.0#1
[cmake]     glui:x64-osx@2019-11-30#4
[cmake] Additional packages (*) will be modified to complete this operation.
[cmake] Restored 0 package(s) from /Users/kirilleremeev/.cache/vcpkg/archives in 17.4 us. Use --debug to see more details.
[cmake] Installing 1/2 freeglut:x64-osx@3.4.0#1...
[cmake] Building freeglut:x64-osx@3.4.0#1...
[cmake] -- Using cached FreeGLUTProject-freeglut-v3.4.0.tar.gz.
[cmake] -- Cleaning sources at /Users/kirilleremeev/00_dev/0300_test/00_opengl/opengl/3rdparty/vcpkg/buildtrees/freeglut/src/v3.4.0-fe4645a74b.clean. Use --editable to skip cleaning for the packages you specify.
[cmake] -- Extracting source /Users/kirilleremeev/00_dev/0300_test/00_opengl/opengl/3rdparty/vcpkg/downloads/FreeGLUTProject-freeglut-v3.4.0.tar.gz
[cmake] -- Applying patch x11-dependencies-export.patch
[cmake] -- Applying patch fix-debug-macro.patch
[cmake] -- Applying patch no_x64_enforcement.patch
[cmake] -- Applying patch windows-output-name.patch
[cmake] -- Using source at /Users/kirilleremeev/00_dev/0300_test/00_opengl/opengl/3rdparty/vcpkg/buildtrees/freeglut/src/v3.4.0-fe4645a74b.clean
[cmake] Freeglut currently requires Xquartz for macOS.
[cmake] -- Configuring x64-osx
[cmake] CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
[cmake]     Command failed: /Users/kirilleremeev/00_dev/0300_test/00_opengl/opengl/3rdparty/vcpkg/downloads/tools/ninja/1.10.2-osx/ninja -v
[cmake]     Working Directory: /Users/kirilleremeev/00_dev/0300_test/00_opengl/opengl/3rdparty/vcpkg/buildtrees/freeglut/x64-osx-rel/vcpkg-parallel-configure
[cmake]     Error code: 1
[cmake]     See logs for more information:
[cmake]       /Users/kirilleremeev/00_dev/0300_test/00_opengl/opengl/3rdparty/vcpkg/buildtrees/freeglut/config-x64-osx-dbg-CMakeCache.txt.log
[cmake]       /Users/kirilleremeev/00_dev/0300_test/00_opengl/opengl/3rdparty/vcpkg/buildtrees/freeglut/config-x64-osx-rel-CMakeCache.txt.log
[cmake]       /Users/kirilleremeev/00_dev/0300_test/00_opengl/opengl/3rdparty/vcpkg/buildtrees/freeglut/config-x64-osx-out.log
[cmake] 
[cmake] Call Stack (most recent call first):
[cmake]   /Users/kirilleremeev/00_dev/0300_test/00_opengl/opengl/build/vcpkg_installed/x64-osx/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:252 (vcpkg_execute_required_process)
[cmake]   ports/freeglut/portfile.cmake:23 (vcpkg_cmake_configure)
[cmake]   scripts/ports.cmake:175 (include)
[cmake] 
[cmake] 
[cmake] error: building freeglut:x64-osx failed with: BUILD_FAILED
[cmake] Elapsed time to handle freeglut:x64-osx: 2.8 s
[cmake] Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
[cmake] Then check for known issues at:
[cmake]   https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+freeglut
[cmake] You can submit a new issue at:
[cmake]   https://github.com/microsoft/vcpkg/issues/new?title=[freeglut]+Build+error+on+x64-osx&body=Copy+issue+body+from+%2FUsers%2Fkirilleremeev%2F00_dev%2F0300_test%2F00_opengl%2Fopengl%2Fbuild%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md
[cmake] 
[cmake] -- Running vcpkg install - failed
[cmake] CMake Error at 3rdparty/vcpkg/scripts/buildsystems/vcpkg.cmake:899 (message):
[cmake]   vcpkg install failed.  See logs for more information:
[cmake]   /Users/kirilleremeev/00_dev/0300_test/00_opengl/opengl/build/vcpkg-manifest-install.log
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:8 (include)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[proc] The command: /usr/local/bin/cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++ -S/Users/kirilleremeev/00_dev/0300_test/00_opengl/opengl -B/Users/kirilleremeev/00_dev/0300_test/00_opengl/opengl/build -G "Unix Makefiles" exited with code: 1

**Comment by dg0yt** [comment]
Note:
~~~
 [cmake] Freeglut currently requires Xquartz for macOS.
~~~

**Comment by JonLiu1993** [comment]
Please provide this log:
````
Users/kirilleremeev/00_dev/0300_test/00_opengl/opengl/3rdparty/vcpkg/buildtrees/freeglut/config-x64-osx-out.log
````
