### ISSUE TITLE
[qt5-base] does not deploy all platform plugins on Windows

### ISSUE THREAD

**Issue by tsondergaard** [microsoft/vcpkg#37897]
On Windows qt5-qtbase only deploys the windows.dll platform plugin to the build folder. This is done by `vcpkg-ports/qt5-base/qtdeploy.ps1`. This is a problem as Qt supplies other platform plugins that consuming software may use. I need the offscreen.dll platform plugin as my project uses it to run GUI unit tests. `vcpkg-ports/qt5-base/qtdeploy.ps1` only selectively deploys from the `platforms` plugins folder. All other Qt plugin types are deployed fully.

**Environment**
- OS: Windows
- Compiler: Visual Studio 2022

**Comment by dg0yt** [comment]
You can always deploy plugins yourself if the default isn't enough. Deploying  all of them may not be desirable as well. 

Somewhat related: https://github.com/microsoft/vcpkg/pull/35931. It would deploy qminimal and qoffscreen along the Test lib.

**Comment by tsondergaard** [comment]
@dg0yt, I've made a simple PR for this. I would appreciate it if you would have a look at it.
