### ISSUE TITLE
[qt5] build failure

### ISSUE THREAD

**Issue by wrxhardworking** [microsoft/vcpkg#37905]
### Operating system

windows

### Steps to reproduce the behavior

```Shell
'.\vcpkg qt5'
```

### Failure logs

error: building qt5-base:x64-mingw-dynamic failed with: BUILD_FAILED
Elapsed time to handle qt5-base:x64-mingw-dynamic: 30 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.

**Comment by wrxhardworking** [comment]
who can help me ? if it always has problem like this if i should reinstall the vcpkg?

**Comment by LilyWangLL** [comment]
Please provide your failure log.

**Comment by wrxhardworking** [comment]
error: building qt5-base:x64-mingw-dynamic failed with: BUILD_FAILED
Elapsed time to handle qt5-base:x64-mingw-dynamic: 30 min
Please ensure you're using the latest port files with git pull and vcpkg update.
