### ISSUE TITLE
[opencv4] build failure

### ISSUE THREAD

**Issue by rinechran** [microsoft/vcpkg#37907]
### Operating system

Windows 11 

### Compiler

MSVC  latest

### Steps to reproduce the behavior

```Shell
vcpkg.exe install opencv4
```

### Failure logs

![image](https://github.com/microsoft/vcpkg/assets/15512801/276c8796-9b7d-4ae2-b58b-d2703bdc5109)

[install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/14826437/install-x64-windows-rel-out.log)
![image](https://github.com/microsoft/vcpkg/assets/15512801/1fc5dec9-b5e6-4072-a7a6-edaaaa7081fa)

https://developercommunity.visualstudio.com/t/Compiler-error-during-flatbuffers-build/10624948

### Additional context

Defendancy protobuf build error occurred during build with opencv4. also jsust building the opencv4[core] part caused a compiler error . 

I uploaded this issue developer community. but they think it's vcpkg error

**Comment by rinechran** [comment]
I use the latest vcpkg but I changed the part I patched separately to xz mirror.

**Comment by FrankXie05** [comment]
@rinechran Thanks for posting this issue. What is your current version of VS? 
This bug has been solved in VS 17.7 and later versions. 😊

**Comment by FrankXie05** [comment]
I am using version `17.9.3`
![image](https://github.com/microsoft/vcpkg/assets/65999885/32ee424b-2068-42cb-8de9-951e00388c11)

**Comment by eunsikNota** [comment]
LGTM i'll check it out when i get home from work

**Comment by rinechran** [comment]
LGTM i'll check it out when i get home from work

**Comment by rinechran** [comment]
i use 17.9.5![image](https://github.com/microsoft/vcpkg/assets/15512801/4f6fd02a-e7ab-4020-a222-5003ca995ac3)

**Comment by FrankXie05** [comment]
Sorry, it seems that the current 2022 version of vs has this problem. Maybe you can use other versions of vs.

https://developercommunity.visualstudio.com/t/Internal-compiler-error-when-install-col/10035653

**Comment by rinechran** [comment]
i got it, should close the issue ?

**Comment by FrankXie05** [comment]
@rinechran If your question is answered satisfactorily, you can close it. :)
