### ISSUE TITLE
[cuda]Build：building cuda:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by yangxingyh** [microsoft/vcpkg#37914]
-- Executing NVCC-NOTFOUND --version resulted in error: 1
CMake Error at ports/cuda/vcpkg_find_cuda.cmake:69 (message):
  Could not find CUDA.  Before continuing, please download and install CUDA
  (v10.1.0 or higher) from:

      https://developer.nvidia.com/cuda-downloads

Call Stack (most recent call first):
  ports/cuda/portfile.cmake:9 (vcpkg_find_cuda)
  scripts/ports.cmake:175 (include)

**Comment by MonicaLiu0311** [comment]
Please follow the error message to check whether cuda is installed?

**Comment by yangxingyh** [comment]
OK，thank you.

**Comment by MonicaLiu0311** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
