### ISSUE TITLE
[boost-exception] Build error on x64-windows

### ISSUE THREAD

**Issue by TheishV** [microsoft/vcpkg#37910]
I don't know if all the message is relevant, but if its not, just read the final lines, its where the error is
I also tried to create a new user name, because mine had a space, but it didn't work

PS C:\Users\Theish Vieira\Desktop\vcpkg-2024.03.25> .\vcpkg install --triplet x64-windows boost-iostreams boost-asio boost-system boost-variant boost-lockfree boost-locale luajit libmariadb pugixml cryptopp fmt
warning: The vcpkg C:\Users\Theish Vieira\Desktop\vcpkg-2024.03.25\vcpkg.exe is using detected vcpkg root C:\Users\Theish Vieira\Desktop\vcpkg-2024.03.25 and ignoring mismatched VCPKG_ROOT environment value C:\vcpkg. To suppress this message, unset the environment variable or use the --vcpkg-root command line switch.
Computing installation plan...
A suitable version of cmake was not found (required v3.27.1) Downloading portable cmake 3.27.1...
Downloading cmake...
https://github.com/Kitware/CMake/releases/download/v3.27.1/cmake-3.27.1-windows-i386.zip->C:\Users\Theish Vieira\Desktop\vcpkg-2024.03.25\downloads\cmake-3.27.1-windows-i386.zip
Downloading https://github.com/Kitware/CMake/releases/download/v3.27.1/cmake-3.27.1-windows-i386.zip
Extracting cmake...
The following packages will be built and installed:
  * boost-algorithm:x64-windows@1.84.0
  * boost-align:x64-windows@1.84.0
  * boost-array:x64-windows@1.84.0
    boost-asio:x64-windows@1.84.0
  * boost-assert:x64-windows@1.84.0
  * boost-atomic:x64-windows@1.84.0
  * boost-bind:x64-windows@1.84.0
  * boost-build:x64-windows@1.84.0
  * boost-chrono:x64-windows@1.84.0
  * boost-concept-check:x64-windows@1.84.0
  * boost-config:x64-windows@1.84.0
  * boost-container:x64-windows@1.84.0
  * boost-container-hash:x64-windows@1.84.0
  * boost-context:x64-windows@1.84.0
  * boost-conversion:x64-windows@1.84.0
  * boost-core:x64-windows@1.84.0
  * boost-coroutine:x64-windows@1.84.0
  * boost-date-time:x64-windows@1.84.0
  * boost-describe:x64-windows@1.84.0
  * boost-detail:x64-windows@1.84.0
  * boost-dynamic-bitset:x64-windows@1.84.0
  * boost-exception:x64-windows@1.84.0
  * boost-function:x64-windows@1.84.0
  * boost-function-types:x64-windows@1.84.0
  * boost-functional:x64-windows@1.84.0
  * boost-fusion:x64-windows@1.84.0
  * boost-integer:x64-windows@1.84.0
  * boost-intrusive:x64-windows@1.84.0
  * boost-io:x64-windows@1.84.0
    boost-iostreams[bzip2,core,lzma,zlib,zstd]:x64-windows@1.84.0
  * boost-iterator:x64-windows@1.84.0
  * boost-lexical-cast:x64-windows@1.84.0
    boost-locale:x64-windows@1.84.0
    boost-lockfree:x64-windows@1.84.0
  * boost-modular-build-helper:x64-windows@1.84.0#3
  * boost-move:x64-windows@1.84.0
  * boost-mp11:x64-windows@1.84.0
  * boost-mpl:x64-windows@1.84.0
  * boost-numeric-conversion:x64-windows@1.84.0
  * boost-optional:x64-windows@1.84.0
  * boost-parameter:x64-windows@1.84.0
  * boost-pool:x64-windows@1.84.0
  * boost-predef:x64-windows@1.84.0
  * boost-preprocessor:x64-windows@1.84.0
  * boost-random:x64-windows@1.84.0
  * boost-range:x64-windows@1.84.0
  * boost-ratio:x64-windows@1.84.0
  * boost-regex:x64-windows@1.84.0
  * boost-smart-ptr:x64-windows@1.84.0
  * boost-static-assert:x64-windows@1.84.0
    boost-system:x64-windows@1.84.0
  * boost-thread:x64-windows@1.84.0
  * boost-throw-exception:x64-windows@1.84.0
  * boost-tokenizer:x64-windows@1.84.0
  * boost-tuple:x64-windows@1.84.0
  * boost-type-index:x64-windows@1.84.0
  * boost-type-traits:x64-windows@1.84.0
  * boost-typeof:x64-windows@1.84.0
  * boost-uninstall:x64-windows@1.84.0
  * boost-unordered:x64-windows@1.84.0
  * boost-utility:x64-windows@1.84.0
    boost-variant:x64-windows@1.84.0
  * boost-variant2:x64-windows@1.84.0
  * boost-vcpkg-helpers:x64-windows@1.84.0
  * boost-winapi:x64-windows@1.84.0
  * bzip2[core,tool]:x64-windows@1.0.8#5
    cryptopp:x64-windows@8.9.0
    fmt:x64-windows@10.2.1#1
  * liblzma:x64-windows@5.6.0
    libmariadb[core,schannel,ssl]:x64-windows@3.3.1#3
    luajit:x64-windows@2023-01-04#5
    pugixml:x64-windows@1.14
  * vcpkg-cmake:x64-windows@2023-05-04
  * vcpkg-cmake-config:x64-windows@2022-02-06#1
  * vcpkg-cmake-get-vars:x64-windows@2023-12-31
  * zlib:x64-windows@1.3.1
  * zstd:x64-windows@1.5.5#2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
A suitable version of powershell-core was not found (required v7.2.16) Downloading portable powershell-core 7.2.16...
Downloading powershell-core...
https://github.com/PowerShell/PowerShell/releases/download/v7.2.16/PowerShell-7.2.16-win-x64.zip->C:\Users\Theish Vieira\Desktop\vcpkg-2024.03.25\downloads\PowerShell-7.2.16-win-x64.zip
Downloading https://github.com/PowerShell/PowerShell/releases/download/v7.2.16/PowerShell-7.2.16-win-x64.zip
Extracting powershell-core...
Compiler found: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
A suitable version of 7zip was not found (required v23.1.0) Downloading portable 7zip 23.1.0...
Downloading 7zip...
https://github.com/ip7z/7zip/releases/download/23.01/7z2301-extra.7z->C:\Users\Theish Vieira\Desktop\vcpkg-2024.03.25\downloads\7z2301-extra.7z
Downloading https://github.com/ip7z/7zip/releases/download/23.01/7z2301-extra.7z
Extracting 7zip...
Restored 0 package(s) from C:\Users\Theish Vieira\AppData\Local\vcpkg\archives in 3.52 ms. Use --debug to see more details.
Installing 1/77 boost-uninstall:x64-windows@1.84.0...
Building boost-uninstall:x64-windows@1.84.0...
--
Please use the following command when you need to remove all boost ports/components:
    "./vcpkg remove boost-uninstall:x64-windows --recurse"

-- Performing post-build validation
Stored binaries in 1 destinations in 88 ms.
Elapsed time to handle boost-uninstall:x64-windows: 590 ms
boost-uninstall:x64-windows package ABI: 05f3eaa2cd997a8aeb3873fbc29690543db4abd91afdf5dc90cf8dc862532894
Installing 2/77 boost-vcpkg-helpers:x64-windows@1.84.0...
Building boost-vcpkg-helpers:x64-windows@1.84.0...
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.84.0/LICENSE_1_0.txt -> boost_LICENSE_1_0.txt...
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-vcpkg-helpers_x64-windows/share/boost-vcpkg-helpers/boost-modular-headers.cmake
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-vcpkg-helpers_x64-windows/share/boost-vcpkg-helpers/usage
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-vcpkg-helpers_x64-windows/share/boost-vcpkg-helpers/boost_LICENSE_1_0.txt
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-vcpkg-helpers_x64-windows/share/boost-vcpkg-helpers/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 120 ms.
Elapsed time to handle boost-vcpkg-helpers:x64-windows: 614 ms
boost-vcpkg-helpers:x64-windows package ABI: 9d45979d4d99138a4e663fc21fb354aa9b4d87c23fd1acb529736cf2399c6d04
Installing 3/77 boost-config:x64-windows@1.84.0...
Building boost-config:x64-windows@1.84.0...
-- Downloading https://github.com/boostorg/config/archive/boost-1.84.0.tar.gz -> boostorg-config-boost-1.84.0.tar.gz...
-- Extracting source C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/downloads/boostorg-config-boost-1.84.0.tar.gz
-- Using source at C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/buildtrees/boost-config/src/ost-1.84.0-003053c176.clean
-- Copying headers
-- Copying headers done
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-config_x64-windows/share/boost-config/usage
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-config_x64-windows/share/boost-config/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 795 ms.
Elapsed time to handle boost-config:x64-windows: 7.7 s
boost-config:x64-windows package ABI: 032c23c70f31646b2e797d62906a5c81a025ccd88cb6fe2fcca233dbb575f42d
Installing 4/77 boost-assert:x64-windows@1.84.0...
Building boost-assert:x64-windows@1.84.0...
-- Downloading https://github.com/boostorg/assert/archive/boost-1.84.0.tar.gz -> boostorg-assert-boost-1.84.0.tar.gz...
-- Extracting source C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/downloads/boostorg-assert-boost-1.84.0.tar.gz
-- Using source at C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/buildtrees/boost-assert/src/ost-1.84.0-a72035ddae.clean
-- Copying headers
-- Copying headers done
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-assert_x64-windows/share/boost-assert/usage
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-assert_x64-windows/share/boost-assert/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 122 ms.
Elapsed time to handle boost-assert:x64-windows: 2 s
boost-assert:x64-windows package ABI: f59380a430adaf6c95294367c9f4c2250b8ac89ad465167e1e9a410c3dab8991
Installing 5/77 boost-static-assert:x64-windows@1.84.0...
Building boost-static-assert:x64-windows@1.84.0...
-- Downloading https://github.com/boostorg/static_assert/archive/boost-1.84.0.tar.gz -> boostorg-static_assert-boost-1.84.0.tar.gz...
-- Extracting source C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/downloads/boostorg-static_assert-boost-1.84.0.tar.gz
-- Using source at C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/buildtrees/boost-static-assert/src/ost-1.84.0-e3347d03d7.clean
-- Copying headers
-- Copying headers done
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-static-assert_x64-windows/share/boost-static-assert/usage
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-static-assert_x64-windows/share/boost-static-assert/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 58.4 ms.
Elapsed time to handle boost-static-assert:x64-windows: 1.2 s
boost-static-assert:x64-windows package ABI: 41225c510c6ae061c669158ff94b7e1e8000e08d3f3746582117ed889553b4b1
Installing 6/77 boost-throw-exception:x64-windows@1.84.0...
Building boost-throw-exception:x64-windows@1.84.0...
-- Downloading https://github.com/boostorg/throw_exception/archive/boost-1.84.0.tar.gz -> boostorg-throw_exception-boost-1.84.0.tar.gz...
-- Extracting source C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/downloads/boostorg-throw_exception-boost-1.84.0.tar.gz
-- Using source at C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/buildtrees/boost-throw-exception/src/ost-1.84.0-18a8557460.clean
-- Copying headers
-- Copying headers done
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-throw-exception_x64-windows/share/boost-throw-exception/usage
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-throw-exception_x64-windows/share/boost-throw-exception/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 98.2 ms.
Elapsed time to handle boost-throw-exception:x64-windows: 1.6 s
boost-throw-exception:x64-windows package ABI: a7ab7edda4dd0d690abbe87b89419aa3c9a24142e27df15180d304c381b2b42e
Installing 7/77 boost-core:x64-windows@1.84.0...
Building boost-core:x64-windows@1.84.0...
-- Downloading https://github.com/boostorg/core/archive/boost-1.84.0.tar.gz -> boostorg-core-boost-1.84.0.tar.gz...
-- Extracting source C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/downloads/boostorg-core-boost-1.84.0.tar.gz
-- Using source at C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/buildtrees/boost-core/src/ost-1.84.0-c7d2be1c95.clean
-- Copying headers
-- Copying headers done
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-core_x64-windows/share/boost-core/usage
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-core_x64-windows/share/boost-core/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 90.2 ms.
Elapsed time to handle boost-core:x64-windows: 3.7 s
boost-core:x64-windows package ABI: ab753ed70eaf544744f719cf59cc8d7bce036279a6065fb70e4862427d0fef54
Installing 8/77 boost-array:x64-windows@1.84.0...
Building boost-array:x64-windows@1.84.0...
-- Downloading https://github.com/boostorg/array/archive/boost-1.84.0.tar.gz -> boostorg-array-boost-1.84.0.tar.gz...
-- Extracting source C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/downloads/boostorg-array-boost-1.84.0.tar.gz
-- Using source at C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/buildtrees/boost-array/src/ost-1.84.0-f4a4f3f6f3.clean
-- Copying headers
-- Copying headers done
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-array_x64-windows/share/boost-array/usage
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-array_x64-windows/share/boost-array/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 67.6 ms.
Elapsed time to handle boost-array:x64-windows: 1.5 s
boost-array:x64-windows package ABI: e95dadb09c1dda194540352e89f85f3478c64d00681d778e1864f841f61b4b9e
Installing 9/77 boost-bind:x64-windows@1.84.0...
Building boost-bind:x64-windows@1.84.0...
-- Downloading https://github.com/boostorg/bind/archive/boost-1.84.0.tar.gz -> boostorg-bind-boost-1.84.0.tar.gz...
-- Extracting source C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/downloads/boostorg-bind-boost-1.84.0.tar.gz
-- Using source at C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/buildtrees/boost-bind/src/ost-1.84.0-7f695603d9.clean
-- Copying headers
-- Copying headers done
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-bind_x64-windows/share/boost-bind/usage
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-bind_x64-windows/share/boost-bind/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 347 ms.
Elapsed time to handle boost-bind:x64-windows: 2.6 s
boost-bind:x64-windows package ABI: ee0b6c3b3bc4a3cd028be430ee0c0ea3c36431108f178caceb92e1c20430be7a
Installing 10/77 boost-preprocessor:x64-windows@1.84.0...
Building boost-preprocessor:x64-windows@1.84.0...
-- Downloading https://github.com/boostorg/preprocessor/archive/boost-1.84.0.tar.gz -> boostorg-preprocessor-boost-1.84.0.tar.gz...
-- Extracting source C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/downloads/boostorg-preprocessor-boost-1.84.0.tar.gz
-- Using source at C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/buildtrees/boost-preprocessor/src/ost-1.84.0-f8aeeec8f0.clean
-- Copying headers
-- Copying headers done
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-preprocessor_x64-windows/share/boost-preprocessor/usage
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-preprocessor_x64-windows/share/boost-preprocessor/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 537 ms.
Elapsed time to handle boost-preprocessor:x64-windows: 15 s
boost-preprocessor:x64-windows package ABI: 145fd629b9e5bc09552a539467e26f88f98ac1fbdd7c2335bc9c126592ce8eb6
Installing 11/77 boost-type-traits:x64-windows@1.84.0...
Building boost-type-traits:x64-windows@1.84.0...
-- Downloading https://github.com/boostorg/type_traits/archive/boost-1.84.0.tar.gz -> boostorg-type_traits-boost-1.84.0.tar.gz...
-- Extracting source C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/downloads/boostorg-type_traits-boost-1.84.0.tar.gz
-- Using source at C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/buildtrees/boost-type-traits/src/ost-1.84.0-8ae87fae2f.clean
-- Copying headers
-- Copying headers done
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-type-traits_x64-windows/share/boost-type-traits/usage
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-type-traits_x64-windows/share/boost-type-traits/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 115 ms.
Elapsed time to handle boost-type-traits:x64-windows: 6.3 s
boost-type-traits:x64-windows package ABI: 02fd94d5588f52602aed2e254c4d7ca51876b2c4b303b9522d9f3f43eed26bce
Installing 12/77 boost-concept-check:x64-windows@1.84.0...
Building boost-concept-check:x64-windows@1.84.0...
-- Downloading https://github.com/boostorg/concept_check/archive/boost-1.84.0.tar.gz -> boostorg-concept_check-boost-1.84.0.tar.gz...
-- Extracting source C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/downloads/boostorg-concept_check-boost-1.84.0.tar.gz
-- Using source at C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/buildtrees/boost-concept-check/src/ost-1.84.0-15123b20dc.clean
-- Copying headers
-- Copying headers done
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-concept-check_x64-windows/share/boost-concept-check/usage
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-concept-check_x64-windows/share/boost-concept-check/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 68.9 ms.
Elapsed time to handle boost-concept-check:x64-windows: 1.7 s
boost-concept-check:x64-windows package ABI: 5d400a3cefacb66aa5add3c4fc14d2b56eeb7cf07b8388d528c0f967b0b0d5fb
Installing 13/77 boost-build:x64-windows@1.84.0...
Building boost-build:x64-windows@1.84.0...
-- Downloading https://github.com/boostorg/build/archive/boost-1.84.0.tar.gz -> boostorg-build-boost-1.84.0.tar.gz...
-- Extracting source C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/downloads/boostorg-build-boost-1.84.0.tar.gz
-- Applying patch 0002-fix-get-version.patch
-- Applying patch 0003-fix-emscripten.patch
-- Applying patch 0004-workaround-MSVC-codegen-bug-in-17.5-on-ARM64.patch
-- Using source at C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/buildtrees/boost-build/src/ost-1.84.0-af9524982d.clean
-- Using cached boost_LICENSE_1_0.txt.
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.84.0/boostcpp.jam -> boost-1.84.0-boostcpp.jam...
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-build_x64-windows/share/boost-build/copyright
-- Bootstrapping...
-- Performing post-build validation
Stored binaries in 1 destinations in 10 s.
Elapsed time to handle boost-build:x64-windows: 1.1 min
boost-build:x64-windows package ABI: fb56d57ca297a4e98c5fc8d18262dbc0dfffe4b459805eb39a83640a4d8a6791
Installing 14/77 vcpkg-cmake:x64-windows@2023-05-04...
Building vcpkg-cmake:x64-windows@2023-05-04...
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg-port-config.cmake
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 67.5 ms.
Elapsed time to handle vcpkg-cmake:x64-windows: 272 ms
vcpkg-cmake:x64-windows package ABI: 6de3c32d2fe00761cbf14ef066b7a2d9bbe1471fa1cac26432ccb8e023dce501
Installing 15/77 vcpkg-cmake-get-vars:x64-windows@2023-12-31...
Building vcpkg-cmake-get-vars:x64-windows@2023-12-31...
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/vcpkg-cmake-get-vars_x64-windows/share/vcpkg-cmake-get-vars/vcpkg_cmake_get_vars.cmake
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/vcpkg-cmake-get-vars_x64-windows/share/vcpkg-cmake-get-vars/cmake_get_vars
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/vcpkg-cmake-get-vars_x64-windows/share/vcpkg-cmake-get-vars/cmake_get_vars/CMakeLists.txt
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/vcpkg-cmake-get-vars_x64-windows/share/vcpkg-cmake-get-vars/vcpkg-port-config.cmake
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/vcpkg-cmake-get-vars_x64-windows/share/vcpkg-cmake-get-vars/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 70.3 ms.
Elapsed time to handle vcpkg-cmake-get-vars:x64-windows: 298 ms
vcpkg-cmake-get-vars:x64-windows package ABI: 88bb9b1f2dda91b1c652de4256816ef2c674de253e2c5b4202b924ecedb00bab
Installing 16/77 boost-modular-build-helper:x64-windows@1.84.0#3...
Building boost-modular-build-helper:x64-windows@1.84.0#3...
-- Performing post-build validation
Stored binaries in 1 destinations in 108 ms.
Elapsed time to handle boost-modular-build-helper:x64-windows: 315 ms
boost-modular-build-helper:x64-windows package ABI: 2a2386155552bd54e40770f8df2d7a3fdaab825526e25bbb8ca9f74adce94d9a
Installing 17/77 boost-move:x64-windows@1.84.0...
Building boost-move:x64-windows@1.84.0...
-- Downloading https://github.com/boostorg/move/archive/boost-1.84.0.tar.gz -> boostorg-move-boost-1.84.0.tar.gz...
-- Extracting source C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/downloads/boostorg-move-boost-1.84.0.tar.gz
-- Using source at C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/buildtrees/boost-move/src/ost-1.84.0-c56de6495a.clean
-- Copying headers
-- Copying headers done
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-move_x64-windows/share/boost-move/usage
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-move_x64-windows/share/boost-move/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 78.5 ms.
Elapsed time to handle boost-move:x64-windows: 2.2 s
boost-move:x64-windows package ABI: 6b4b9226feecd21948b31813951b1104d17a5380cb1bae55756ee99425a317dc
Installing 18/77 boost-smart-ptr:x64-windows@1.84.0...
Building boost-smart-ptr:x64-windows@1.84.0...
-- Downloading https://github.com/boostorg/smart_ptr/archive/boost-1.84.0.tar.gz -> boostorg-smart_ptr-boost-1.84.0.tar.gz...
-- Extracting source C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/downloads/boostorg-smart_ptr-boost-1.84.0.tar.gz
-- Using source at C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/buildtrees/boost-smart-ptr/src/ost-1.84.0-e47244b3e1.clean
-- Copying headers
-- Copying headers done
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-smart-ptr_x64-windows/share/boost-smart-ptr/usage
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-smart-ptr_x64-windows/share/boost-smart-ptr/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 87.1 ms.
Elapsed time to handle boost-smart-ptr:x64-windows: 5.1 s
boost-smart-ptr:x64-windows package ABI: 71f2c4c7aadb4b7f45d1a12cd877e74c000de921855500a4b2df9c698fe87ae2
Installing 19/77 boost-tuple:x64-windows@1.84.0...
Building boost-tuple:x64-windows@1.84.0...
-- Downloading https://github.com/boostorg/tuple/archive/boost-1.84.0.tar.gz -> boostorg-tuple-boost-1.84.0.tar.gz...
-- Extracting source C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/downloads/boostorg-tuple-boost-1.84.0.tar.gz
-- Using source at C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/buildtrees/boost-tuple/src/ost-1.84.0-cc4c6791c3.clean
-- Copying headers
-- Copying headers done
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-tuple_x64-windows/share/boost-tuple/usage
-- Installing: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/packages/boost-tuple_x64-windows/share/boost-tuple/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 363 ms.
Elapsed time to handle boost-tuple:x64-windows: 1.8 s
boost-tuple:x64-windows package ABI: a4c4bf7efdb7403f26514d4d930a50048769bfdb3fe53fee8b606080aa0f7f85
Installing 20/77 boost-exception:x64-windows@1.84.0...
Building boost-exception:x64-windows@1.84.0...
-- Downloading https://github.com/boostorg/exception/archive/boost-1.84.0.tar.gz -> boostorg-exception-boost-1.84.0.tar.gz...
-- Extracting source C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/downloads/boostorg-exception-boost-1.84.0.tar.gz
-- Using source at C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/buildtrees/boost-exception/src/ost-1.84.0-4868094bf7.clean
-- Getting CMake variables for x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/downloads/tools/ninja/1.10.2-windows/ninja.exe" -v
    Working Directory: C:/Users/Theish Vieira/Desktop/vcpkg-2024.03.25/buildtrees/boost-exception/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\Theish Vieira\Desktop\vcpkg-2024.03.25\buildtrees\boost-exception\cmake-get-vars-x64-windows-dbg-CMakeCache.txt.log
      C:\Users\Theish Vieira\Desktop\vcpkg-2024.03.25\buildtrees\boost-exception\cmake-get-vars-x64-windows-rel-CMakeCache.txt.log
      C:\Users\Theish Vieira\Desktop\vcpkg-2024.03.25\buildtrees\boost-exception\cmake-get-vars-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:252 (vcpkg_execute_required_process)
  installed/x64-windows/share/vcpkg-cmake-get-vars/vcpkg_cmake_get_vars.cmake:15 (vcpkg_cmake_configure)
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:111 (vcpkg_cmake_get_vars)
  ports/boost-exception/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:175 (include)

error: building boost-exception:x64-windows failed with: BUILD_FAILED
Elapsed time to handle boost-exception:x64-windows: 4.7 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-exception
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[boost-exception]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2FUsers%2FTheish%20Vieira%2FDesktop%2Fvcpkg-2024.03.25%2Finstalled%2Fvcpkg%2Fissue_body.md
  
[cmake-get-vars-x64-windows-dbg-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/14829463/cmake-get-vars-x64-windows-dbg-CMakeCache.txt.log)
[cmake-get-vars-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/14829466/cmake-get-vars-x64-windows-out.log)

  
[cmake-get-vars-x64-windows-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/14829465/cmake-get-vars-x64-windows-rel-CMakeCache.txt.log)

**Comment by StarGate-One** [comment]
Try putting vcpkg into a directory without spaces or special characters. Many of the 3rd party tools used by vcpkg are not space/special character friendly in path names.

**Comment by TheishV** [comment]
I tried with my other windows account (without space) and renamed the folder, got rid of spaces, numbers etc, and still got the same error.

**Comment by WangWeiLin-MV** [comment]
Please try to remove `vcpkg package manager` in `Individual Components` in `Visual Studio Installer`, then open a new `Developer Command Prompt for VS`, use latest vcpkg from repository and `.\bootstrap-vcpkg.bat`.
