### ISSUE TITLE
[curl] Build error

### ISSUE THREAD

**Issue by RodionPasynkov** [microsoft/vcpkg#37917]
Copy issue body from C:/dev/vcpkg/installed/vcpkg/issue_body.md

**Comment by RodionPasynkov** [comment]
Package: curl[core,non-http,schannel,ssl,sspi]:x64-windows -> 8.4.0

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.38.33133.0
-    vcpkg-tool version: 2023-10-18-27de5b69dac4b6fe8259d283cd4011e6d20a84ce
    vcpkg-scripts version: 0c20b2a97 2023-11-17 (5 months ago)

**To Reproduce**

`vcpkg install curl`
**Failure logs**

```
-- Using cached curl-curl-curl-8_4_0.tar.gz.
-- Cleaning sources at C:/dev/vcpkg/buildtrees/curl/src/curl-8_4_0-1dac1974ab.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/curl-curl-curl-8_4_0.tar.gz
-- Applying patch 0002_fix_uwp.patch
-- Applying patch 0005_remove_imp_suffix.patch
-- Applying patch 0012-fix-dependency-idn2.patch
-- Applying patch 0020-fix-pc-file.patch
-- Applying patch 0022-deduplicate-libs.patch
-- Applying patch mbedtls-ws2_32.patch
-- Applying patch export-components.patch
-- Applying patch dependencies.patch
-- Applying patch cmake-config.patch
-- Using source at C:/dev/vcpkg/buildtrees/curl/src/curl-8_4_0-1dac1974ab.clean
CMake Error at ports/curl/portfile.cmake:67 (vcpkg_cmake_configure):
  Unknown CMake command "vcpkg_cmake_configure".
Call Stack (most recent call first):
  scripts/ports.cmake:170 (include)



```

**Comment by dg0yt** [comment]
> ~~~
> Package: curl[core,non-http,schannel,ssl,sspi]:x64-windows -> 8.4.0

Outdated.

> ~~~
> * vcpkg-tool version: 2023-10-18-27de5b69dac4b6fe8259d283cd4011e6d20a84ce
>       vcpkg-scripts version: [0c20b2a](https://github.com/microsoft/vcpkg/commit/0c20b2a97c390e106150837042d921b0939e7ecb) 2023-11-17 (5 months ago)

Outdated.

> Unknown CMake command "vcpkg_cmake_configure".

Outdated installation of `vcpkg-cmake`. Upgrade the installed ports / the "builtin-baseline".
