### ISSUE TITLE
[New Port Request] <Qt5Quick3D>

### ISSUE THREAD

**Issue by haobo724** [microsoft/vcpkg#37928]
### Library name

Qt5Quick3D

### Library description

Qt Quick 3D Qt Quick 3D provides a high-level API for creating 3D content and 3D user interfaces based on Qt Quick. 

### Source repository URL

https://github.com/qt/qtquick3d

### Project homepage (if different from the source repository)

https://doc.qt.io/qt-5/qtquick3d-index.html 

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

In my project I use the QT5 version of the quick3d library, but the vcpkg doesn't have the qt5quick3d, only the qt6 one, so I'd like to request the QT5 version.

**Comment by haobo724** [comment]
any update ?

**Comment by yanzixiang** [comment]
https://github.com/microsoft/vcpkg/pull/44478
