### ISSUE TITLE
Tesseract build failure

### ISSUE THREAD

**Issue by akw0088** [microsoft/vcpkg#37929]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
vcpkg install tesseract-x86-windows
```

### Failure logs

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1

### Additional context

Is vcpkg for Windows still maintained? I asked a question here a week ago and have not heard back. When I view the build log I can see it has not compiled many projects. I am looking for things like multithreaded encoding / decoding and a few updates that Brett Okken had submited (but are still waiting for merge). Should I add these things to only my local version, or is there a plan for these things in the future?

With your current rate, I very doubt to see 5.4.0 release this year. The only progress since april has been small changes to test code. You ignore the many patches bit rotting away on this mailing list. Right now you choke your repo.

**Comment by autoantwort** [comment]
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report a build failure.

**Comment by FrankXie05** [comment]
Please see #30604 for how to report an issue.
