### ISSUE TITLE
[libcap] build failure

### ISSUE THREAD

**Issue by Xia-Chuan** [microsoft/vcpkg#37948]
### Operating system

Linux

### Compiler

GCC

### Steps to reproduce the behavior

```Shell
./vcpkg install wxwidgets --triplet arm64-linux
```

### Failure logs

Package: libcap:arm64-linux@2.69#4

**Host Environment**

- Host: arm64-linux
- Compiler: GNU 8.3.0
-    vcpkg-tool version: 2999-12-31-unknownhash
    vcpkg-scripts version: 11ed79186 2024-04-02 (6 小时前)

**To Reproduce**

`vcpkg install wxwidgets`
**Failure logs**

```
-- Downloading https://git.kernel.org/pub/scm/libs/libcap/libcap.git/snapshot/libcap-2.69.tar.gz -> libcap-2.69.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from /usr/local/share/vcpkg/vcpkg-bundle.json
[DEBUG] Failed to open: /usr/local/share/vcpkg/vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
[DEBUG] 1000: execute_process(curl --fail -L https://git.kernel.org/pub/scm/libs/libcap/libcap.git/snapshot/libcap-2.69.tar.gz --create-dirs --output /usr/local/share/vcpkg/downloads/libcap-2.69.tar.gz.15708.part)
[DEBUG] 1000: cmd_execute_and_stream_data() returned 22 after   775927 us
error: Failed to download from mirror set
error: https://git.kernel.org/pub/scm/libs/libcap/libcap.git/snapshot/libcap-2.69.tar.gz: curl failed to download with exit code 22
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

curl: (22) The requested URL returned error: 404 Not Found

[DEBUG] /usr/local/share/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-03-14/src/vcpkg/base/downloads.cpp(1031): 
[DEBUG] Time in subprocesses: 775927us
[DEBUG] Time in parsing JSON: 7us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 491us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 778 ms (776864us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
      

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/libcap/portfile.cmake:1 (vcpkg_download_distfile)
  scripts/ports.cmake:175 (include)



```

**Comment by flnhst** [comment]
The URL https://git.kernel.org/pub/scm/libs/libcap/libcap.git/snapshot/libcap-2.69.tar.gz appears to be unavailable again.

Is there perhaps a more reliable source for this package?

**Comment by oracleoftroy** [comment]
Same issue as @flnhst. This should probably be reopened or a new issue created unless this is a temporary problem.

Hitting the URI directly gives: "Unsupported snapshot format: libcap-2.69.tar.gz". I don't know the snapshot syntax that well and I didn't see any documentation, so I'm not sure why it doesn't like it.

Looking around, I saw that Linux From Scratch uses https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/ as the base URI. I was able to download from https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-{VERSION}.tar.gz, though the sha512 doesn't match what the portfile is looking for.

No idea what the difference is and whether that would or wouldn't be an appropriate URI to use instead.

**Comment by dg0yt** [comment]
> Looking around, I saw that Linux From Scratch uses https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/ as the base URI. I was able to download from [https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-{VERSION}.tar.gz](https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-%7BVERSION%7D.tar.gz), though the sha512 doesn't match what the portfile is looking for.

Assuming that there are the official downloads (instead of on-the-fly tarballs), the this is a mirror:  
https://www.mirrorservice.org/sites/ftp.kernel.org/pub/linux/libs/security/linux-privs/libcap2/
