### ISSUE TITLE
install mozjpeg:x86-windows-static fails

### ISSUE THREAD

**Issue by lalexf** [Microsoft/vcpkg#3795]
I tried to install mozjpeg:x86-windows-static from a clean up to date vcpkg-repo and it fails with the following output.

> The following packages will be built and installed:
>     mozjpeg[core]:x86-windows-static
> Starting package 1/1: mozjpeg:x86-windows-static
> Building package mozjpeg[core]:x86-windows-static...
> A suitable version of cmake was not found (required v3.10.2). Downloading portable cmake v3.10.2...
> Downloading cmake...
> Downloading cmake... done.
> Extracting cmake...
> A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
> Downloading 7zip...
> Downloading 7zip... done.
> Extracting 7zip...
> A suitable version of nuget was not found (required v4.6.2). Downloading portable nuget v4.6.2...
> Downloading nuget...
> Downloading nuget... done.
> Extracting 7zip... done.
> Extracting cmake... done.
> -- Downloading https://github.com/mozilla/mozjpeg/archive/v3.2.tar.gz...
> -- Extracting source E:/develop/vcpkg_2/downloads/mozilla-mozjpeg-v3.2.tar.gz
> -- Using source at E:/develop/vcpkg_2/buildtrees/mozjpeg/src/v3.2-4c4893bbe3
> -- Downloading http://www.nasm.us/pub/nasm/releasebuilds/2.12.02/win32/nasm-2.12.02-win32.zip...
> -- Downloading https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip...
> -- Configuring x86-windows-static
> -- Building x86-windows-static-dbg
> CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:170 (message):
>     Command failed: E:/develop/vcpkg_2/downloads/tools/cmake-3.10.2-windows/cmake-3.10.2-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No
>     Working Directory: E:/develop/vcpkg_2/buildtrees/mozjpeg/x86-windows-static-dbg
>     See logs for more information:
>       E:\develop\vcpkg_2\buildtrees\mozjpeg\install-x86-windows-static-dbg-out.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
>   ports/mozjpeg/portfile.cmake:30 (vcpkg_install_cmake)
>   scripts/ports.cmake:71 (include)
> 
> 
> Error: Building package mozjpeg:x86-windows-static failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: mozjpeg:x86-windows-static
>   Vcpkg version: 0.0.113-nohash
> 
> Additionally, attach any relevant sections from the log files above.

Here is the logfile:
[install-x86-windows-static-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2141506/install-x86-windows-static-dbg-out.log)

**Comment by Voskrese** [comment]
```
E:\develop\vcpkg_2\downloads\tools\cmake-3.10.2-windows\cmake-3.10.2-win32-x86\bin\cmake.exe -DBUILD_TYPE=Debug -P cmake_install.cmake
....
         -- Install configuration: "Debug"
         -- Installing: E:/develop/vcpkg_2/packages/mozjpeg_x86-windows-static/debug/lib/turbojpeg-static.lib
         CMake Error at cmake_install.cmake:48 (file):
           file INSTALL cannot find
"E:/develop/vcpkg_2/buildtrees/mozjpeg/x86-windows-static-dbg/tjbench-static.exe".
```

It is necessary in the script to fix the installation of executable files, which are not

**Comment by lalexf** [comment]
Ok, and what have i to do to fix it?

**Comment by Voskrese** [comment]
@lalexf  study Cmake or wait for someone to respond
I'm not very good at it, so I won't be able to help

**Comment by JackBoosY** [comment]
Hi @lalexf , thanks for reporting this issue!
I've fixed this issue. Please update vcpkg and rebuild mozjpeg.
Thanks.
