### ISSUE TITLE
Github and vcpkg integration

### ISSUE THREAD

**Issue by kelbon** [microsoft/vcpkg#37965]
It would be useful to have a github action like 'git checkout vcpkg' which checkouts git repository, loads packages and caches them in CI. Is there are something like this already? I think Microsoft is interested in this, since their infrastructure endlessly downloads repositories from packages and it would be reasonable to popularize such a GitHub action

**Comment by autoantwort** [comment]
You mean https://github.com/marketplace/actions/run-vcpkg ?

**Comment by Nosenzor** [comment]
> You mean https://github.com/marketplace/actions/run-vcpkg ?

This actions items work fine for me. I've been using it for 2 years now. Combine it with the variant vcpkg+cmake and that's even finer.
