### ISSUE TITLE
FFMPEG Package not recognised by CMake Toolchain

### ISSUE THREAD

**Issue by JonBoyleCoding** [Microsoft/vcpkg#3796]
The FFMPEG package doesn't properly work with the CMake toolchain. 

The package provides a FindFFMPEG.cmake file which isn't recognised by find_package. It seems to want a file formatted FFMPEGConfig.cmake instead. Renaming the file works; however, this may not be an overall solution as it doesn't move produced DLLs to the executable directory when used in compilation further down the line.

I'm uncertain as to how to best deal with this, as I'm new to vcpkg. Thought it would be worth making an issue

**Comment by colinsf** [comment]
https://github.com/Microsoft/vcpkg/issues/1379

**Comment by LarryIII** [comment]
FFmpeg does not support cmake, so you need to use find_path and find_library instead of find_package. See https://github.com/Microsoft/vcpkg/issues/1379
