### ISSUE TITLE
[prometheus-cpp] Build error on x64-linux

### ISSUE THREAD

**Issue by cys9211** [microsoft/vcpkg#37979]
Copy issue body from /home/ots/canary/build/linux-release/vcpkg_installed/vcpkg/issue_body.md

CMake Error at /home/ots/vcpkg/scripts/buildsystems/vcpkg.cmake:899 (message):
  vcpkg install failed.  See logs for more information:
  /home/ots/canary/build/linux-release/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /snap/cmake/1379/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:146 (include)
  CMakeLists.txt:30 (project)

**Comment by Cheney-W** [comment]
Please see [#30604](https://github.com/microsoft/vcpkg/issues/30604) for how to report an issue.
