### ISSUE TITLE
[json-schema-validator] DLL is not generated for dynamic linking

### ISSUE THREAD

**Issue by Demonslay335** [microsoft/vcpkg#37972]
**Describe the bug**
When dynamically linking the `json-schema-validator` library using the `x64-windows` target triplet, the DLL is not produced in the output directory. This causes a run-time error about `nlohmann_json_schema_validator.dll` being missing.

**Environment**
- OS: Windows
- Compiler: MSVC

**To Reproduce**
1. `./vcpkg install json-schema-validator`
2. Use `"VCPKG_TARGET_TRIPLET": "x64-windows"` in CMake project.
3. Setup CMake and program to use the library as normal from examples.
4. Attempt to run your program.

**Expected behavior**
The program should run without an error about a missing DLL.

**Failure logs**
![image](https://github.com/microsoft/vcpkg/assets/5551512/b3bad9a3-f7ea-4897-87a8-a6f335fe6169)

**Additional context**
Perhaps this flag from the [library's documentation](https://github.com/pboettch/json-schema-validator#building-as-shared-library) needs added when being dynamically linked.

```
-DBUILD_SHARED_LIBS=ON
```

I assume this also affects the production of a `.so` file on Linux.

**Comment by Neumann-A** [comment]
upstream as a broken install rule using `CMAKE_INSTALL_RUNTIMEDIR` instead of `CMAKE_INSTALL_BINDIR`

**Comment by Neumann-A** [comment]
And yes the dll is generate the problem is just that it is not copied over.

@BillyONeal. If the tool already checks the lib files could it not also check that the associated dll is actually being installed?

**Comment by BillyONeal** [comment]
> If the tool already checks the lib files could it not also check that the associated dll is actually being installed?

This is a complicated question for the tool to answer. There is no 1:1 relationship between .lib and .dll.
