### ISSUE TITLE
Dynamically linked libraries and static libraries coexisting

### ISSUE THREAD

**Issue by AndreaNappi00** [microsoft/vcpkg#37977]
OS: `x64-linux`

Further info: vcpk in manifest mode with overlays

After reading the docs and issues posted here, I understood that dynamically linked libraries are not officially supported, thus the need to set `-DVCPKG_TARGET_TRIPLET=x64-linux-dynamic` and `-DVCPKG_INSTALL_OPTIONS="--allow-unsupported"` to the CMakePresets.json. This indeed works but "forces" all other libraries to be built dynamically as a default. 
Is it possible to have a static default install for all the libraries that allow it, while only trying dynamically linked library install for the ones that allow only this mode?

**Comment by Osyotr** [comment]
https://learn.microsoft.com/en-us/vcpkg/users/triplets#per-port-customization

PS: you don't really need `--allow-unsupported`

**Comment by dg0yt** [comment]
This seems to mix two interpretations of "supported":   
One is that the triplet is tested in vcpkg CI. You get out of this by choosing other triplets (or custom overlay triplets). This may work well most of the times.
Another one is what is supported by the package of interest. Like building `msmpi` for `windows`. You can _try_ to get over this for `osx` with `--allow-unsupported`, but it won't work most of the times.
