### ISSUE TITLE
[Request] 3DStreamingToolkit

### ISSUE THREAD

**Issue by KanishkT123** [microsoft/vcpkg#3797]
I'd like to add the Microsoft CSE 3D Streaming Toolkit repo to vcpkg as a package. I forked the repo into the 3D Streaming Toolkit repo, available [here](https://github.com/3DStreamingToolkit/vcpkg) and I want to make a PR to add the package. 

The package itself is available under CatalystCode at the following link:
https://github.com/CatalystCode/3DStreamingToolkit

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
