### ISSUE TITLE
Error: Building package vtk:x86-windows-static failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Gr8-Dane** [Microsoft/vcpkg#3799]
I checked and made sure all packages in vcpkg were up to date and they are. Any ideas why this build failed?

"
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: vtk:x86-windows-static
  Vcpkg version: 0.0.113-nohash"

**Comment by luzpaz** [comment]
Related to https://github.com/Microsoft/vcpkg/issues/3757

**Comment by LarryIII** [comment]
@Gr8-Dane Thanks for your feedback. I installed vtk:x86-windows-static successfully with VS 2017 15.9.7. Please open a new issue if this is still a problem for you.
