### ISSUE TITLE
[liblzma]:Invalid URL

### ISSUE THREAD

**Issue by Rhenus-Re** [microsoft/vcpkg#37992]
![%M}(UV3BGP2IEQZ0QVAJXF4](https://github.com/microsoft/vcpkg/assets/63099121/f5d9bde7-0c81-41f3-adb3-c70a52c51cfe)
https://[github.com/tukaani-project/xz/archive/v5.4.4.tar.gz](https://github.com/tukaani-project/xz/archive/v5.4.4.tar.gz)

**Comment by bansan85** [comment]
Look at #37839

See temporary workaround at https://github.com/microsoft/vcpkg/issues/37962#issuecomment-2036223908

**Comment by LilyWangLL** [comment]
Duplicate of https://github.com/microsoft/vcpkg/issues/37893.
