### ISSUE TITLE
[icu] build failure

### ISSUE THREAD

**Issue by kobalicek** [microsoft/vcpkg#38005]
### Operating system

Macos

### Compiler

Clang

### Steps to reproduce the behavior

```Shell
$VCPKG_ROOT/vcpkg install icu
```

### Failure logs

 % $VCPKG_ROOT/vcpkg install icu                  
Computing installation plan...
The following packages will be built and installed:
    icu[core,tools]:arm64-osx@74.2#1
Detecting compiler hash for triplet arm64-osx...
Restored 0 package(s) from /Users/petr/.cache/vcpkg/archives in 4.75 us. Use --debug to see more details.
Installing 1/1 icu[core,tools]:arm64-osx@74.2#1...
Building icu[core,tools]:arm64-osx@74.2#1...
-- Using cached icu4c-74_2-src.tgz.
-- Cleaning sources at /Users/petr/oss/vcpkg/buildtrees/icu/src/c-74_2-src-83138cd994.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/petr/oss/vcpkg/downloads/icu4c-74_2-src.tgz
-- Applying patch disable-escapestr-tool.patch
-- Applying patch remove-MD-from-configure.patch
-- Applying patch fix_parallel_build_on_windows.patch
-- Applying patch fix-extra.patch
-- Applying patch mingw-dll-install.patch
-- Applying patch disable-static-prefix.patch
-- Applying patch fix-win-build.patch
-- Applying patch vcpkg-cross-data.patch
-- Applying patch darwin-rpath.patch
-- Using source at /Users/petr/oss/vcpkg/buildtrees/icu/src/c-74_2-src-83138cd994.clean
-- Getting CMake variables for arm64-osx-dbg
-- Getting CMake variables for arm64-osx-rel
-- Generating configure for arm64-osx
-- Finished generating configure for arm64-osx
-- Configuring arm64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /bin/bash -c "V=1 ./../src/c-74_2-src-83138cd994.clean/source/configure  \"--enable-tools\" \"--disable-samples\" \"--disable-tests\" \"--disable-layoutex\" \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"--enable-debug\" \"--disable-release\" \"--prefix=/Users/petr/oss/vcpkg/installed/arm64-osx/debug\" \"--bindir=\\${prefix}/../tools/icu/debug/bin\" \"--sbindir=\\${prefix}/../tools/icu/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/icu\""
    Working Directory: /Users/petr/oss/vcpkg/buildtrees/icu/arm64-osx-dbg
    Error code: 1
    See logs for more information:
      /Users/petr/oss/vcpkg/buildtrees/icu/config-arm64-osx-dbg-config.log
      /Users/petr/oss/vcpkg/buildtrees/icu/config-arm64-osx-dbg-out.log
      /Users/petr/oss/vcpkg/buildtrees/icu/config-arm64-osx-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:863 (vcpkg_execute_required_process)
  ports/icu/portfile.cmake:66 (vcpkg_configure_make)
  scripts/ports.cmake:175 (include)

error: building icu:arm64-osx failed with: BUILD_FAILED
Elapsed time to handle icu:arm64-osx: 3.9 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+icu
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[icu]+Build+error+on+arm64-osx&body=Copy+issue+body+from+%2FUsers%2Fpetr%2Foss%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

The most interesting line from the `config-arm64-osx-dbg` log is:

`autoconf-archive is missing`

Which is actually the problem.

### Additional context

I have solved this by installing autoconf-archive via brew `brew install autoconf-archive`, however, I'm not sure whether this package should not be installed via vcpkg instead, because this basically means that I need to install a build dependency explicitly.

Also, maybe vcpkg should hint to do this even before attempting to configure the package?

**Comment by MonicaLiu0311** [comment]
The issue did reproduce when I uninstalled `autoconf-archive`, since `vcpkg_configure_make` requires it:
```
vcpkg@vcpkgs-Virtual-Machine vcpkg % brew uninstall autoconf-archive
Uninstalling /opt/homebrew/Cellar/autoconf-archive/2023.02.20... (600 files, 3.6MB)
vcpkg@vcpkgs-Virtual-Machine vcpkg %
vcpkg@vcpkgs-Virtual-Machine vcpkg %
vcpkg@vcpkgs-Virtual-Machine vcpkg % vim  /Users/vcpkg/Monica/vcpkg/buildtrees/icu/config-arm64-osx-dbg-err.log
configure: WARNING: unrecognized options: --disable-silent-rules
configure: error: 'autoconf-archive' is missing
```

```
vcpkg_configure_make(
    SOURCE_PATH "${SOURCE_PATH}"
    PROJECT_SUBPATH source
    AUTOCONFIG
    DETERMINE_BUILD_TRIPLET
    ADDITIONAL_MSYS_PACKAGES autoconf-archive
    OPTIONS
        ${CONFIGURE_OPTIONS}
        --disable-samples
        --disable-tests
        --disable-layoutex
    OPTIONS_RELEASE
        --disable-debug
        --enable-release
    OPTIONS_DEBUG
        --enable-debug
        --disable-release
)
```
