### ISSUE TITLE
[freeimage] build failure due to xz

### ISSUE THREAD

**Issue by dsvensson** [microsoft/vcpkg#38013]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
Depend on freeimage.
```

### Failure logs

Same as https://github.com/microsoft/vcpkg/issues/38007

### Additional context

Make lzma an optional dependency. Seems to be pulled in via tiff at least.

**Comment by JonLiu1993** [comment]
Duplicate of https://github.com/microsoft/vcpkg/issues/37893.

**Comment by dsvensson** [comment]
Agreed. It's a bit broken that you can't depend on freeimage without opting into a whole slew of unwanted dependencies.

**Comment by JackBoosY** [comment]
Port feature request.

**Comment by dg0yt** [comment]
> Port feature request.

Port bug.
