### ISSUE TITLE
Error: Building package eigen3:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by jonghoon-park** [Microsoft/vcpkg#3801]
Hi vcpkg people

I had install eigen3 using vcpkg. 
but it cannot install eigen3. i dont know why.
How do i fix it?

here is error message.

CMakeError.log
Performing C++ SOURCE FILE Test EIGEN_COMPILER_SUPPORT_CPP11 failed with the following output:
Change Dir: C:/vcpkg/buildtrees/eigen3/x64-windows-dbg/CMakeFiles/CMakeTmp

Run Build Command:"C:/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "cmTC_69c03"
[1/2] Building CXX object CMakeFiles\cmTC_69c03.dir\src.cxx.obj

cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
[2/2] Linking CXX executable cmTC_69c03.exe

Source file was:
int main() { return 0; }
Performing C++ SOURCE FILE Test EIGEN_COMPILER_SUPPORT_CXX11 failed with the following output:
Change Dir: C:/vcpkg/buildtrees/eigen3/x64-windows-dbg/CMakeFiles/CMakeTmp

Run Build Command:"C:/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "cmTC_9fd1d"
[1/2] Building CXX object CMakeFiles\cmTC_9fd1d.dir\src.cxx.obj

cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
[2/2] Linking CXX executable cmTC_9fd1d.exe

Source file was:
int main() { return 0; }
Determining if the include file pthread.h exists failed with the following output:
Change Dir: C:/vcpkg/buildtrees/eigen3/x64-windows-dbg/CMakeFiles/CMakeTmp

Run Build Command:"C:/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "cmTC_d4157"
[1/2] Building C object CMakeFiles\cmTC_d4157.dir\CheckIncludeFile.c.obj

FAILED: CMakeFiles/cmTC_d4157.dir/CheckIncludeFile.c.obj 

C:\PROGRA~2\MICROS~1\2017\COMMUN~1\VC\Tools\MSVC\1414~1.264\bin\Hostx64\x64\cl.exe  /nologo   /DWIN32 /D_WINDOWS /W3 /utf-8 /MP   /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\cmTC_d4157.dir\CheckIncludeFile.c.obj /FdCMakeFiles\cmTC_d4157.dir\ /FS -c CheckIncludeFile.c

CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory
ninja: build stopped: subcommand failed.

Performing C SOURCE FILE Test SCOTCH_Num_4 failed with the following compile output:
Change Dir: C:/vcpkg/buildtrees/eigen3/x64-windows-dbg/CMakeFiles/CMakeTmp

Run Build Command:"C:/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "cmTC_16050"
[1/2] Building C object CMakeFiles\cmTC_16050.dir\src.c.obj

FAILED: CMakeFiles/cmTC_16050.dir/src.c.obj 

C:\PROGRA~2\MICROS~1\2017\COMMUN~1\VC\Tools\MSVC\1414~1.264\bin\Hostx64\x64\cl.exe  /nologo   /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  -DSCOTCH_Num_4 /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\cmTC_16050.dir\src.c.obj /FdCMakeFiles\cmTC_16050.dir\ /FS -c src.c

src.c(4): fatal error C1083: Cannot open include file: 'scotch.h': No such file or directory
ninja: build stopped: subcommand failed.

...and run output:

Return value: 1
Source file was:

#include <stdio.h>
#include <stdint.h>
#include <scotch.h>
int main(int argc, char **argv) {
  if (sizeof(SCOTCH_Num) == 4)
    return 0;
  else
    return 1;
}

Performing C SOURCE FILE Test SCOTCH_Num_8 failed with the following compile output:
Change Dir: C:/vcpkg/buildtrees/eigen3/x64-windows-dbg/CMakeFiles/CMakeTmp

Run Build Command:"C:/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "cmTC_30049"
[1/2] Building C object CMakeFiles\cmTC_30049.dir\src.c.obj

FAILED: CMakeFiles/cmTC_30049.dir/src.c.obj 

C:\PROGRA~2\MICROS~1\2017\COMMUN~1\VC\Tools\MSVC\1414~1.264\bin\Hostx64\x64\cl.exe  /nologo   /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  -DSCOTCH_Num_8 /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\cmTC_30049.dir\src.c.obj /FdCMakeFiles\cmTC_30049.dir\ /FS -c src.c

src.c(4): fatal error C1083: Cannot open include file: 'scotch.h': No such file or directory
ninja: build stopped: subcommand failed.

...and run output:

Return value: 1
Source file was:

#include <stdio.h>
#include <stdint.h>
#include <scotch.h>
int main(int argc, char **argv) {
  if (sizeof(SCOTCH_Num) == 8)
    return 0;
  else
    return 1;
}

Performing C SOURCE FILE Test PTSCOTCH_Num_4 failed with the following compile output:
Change Dir: C:/vcpkg/buildtrees/eigen3/x64-windows-dbg/CMakeFiles/CMakeTmp

Run Build Command:"C:/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "cmTC_c4a00"
[1/2] Building C object CMakeFiles\cmTC_c4a00.dir\src.c.obj

FAILED: CMakeFiles/cmTC_c4a00.dir/src.c.obj 

C:\PROGRA~2\MICROS~1\2017\COMMUN~1\VC\Tools\MSVC\1414~1.264\bin\Hostx64\x64\cl.exe  /nologo   /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  -DPTSCOTCH_Num_4 /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\cmTC_c4a00.dir\src.c.obj /FdCMakeFiles\cmTC_c4a00.dir\ /FS -c src.c

src.c(4): fatal error C1083: Cannot open include file: 'ptscotch.h': No such file or directory
ninja: build stopped: subcommand failed.

...and run output:

Return value: 1
Source file was:

#include <stdio.h>
#include <stdint.h>
#include <ptscotch.h>
int main(int argc, char **argv) {
  if (sizeof(SCOTCH_Num) == 4)
    return 0;
  else
    return 1;
}

Performing C SOURCE FILE Test PTSCOTCH_Num_8 failed with the following compile output:
Change Dir: C:/vcpkg/buildtrees/eigen3/x64-windows-dbg/CMakeFiles/CMakeTmp

Run Build Command:"C:/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "cmTC_d1f60"
[1/2] Building C object CMakeFiles\cmTC_d1f60.dir\src.c.obj

FAILED: CMakeFiles/cmTC_d1f60.dir/src.c.obj 

C:\PROGRA~2\MICROS~1\2017\COMMUN~1\VC\Tools\MSVC\1414~1.264\bin\Hostx64\x64\cl.exe  /nologo   /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  -DPTSCOTCH_Num_8 /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\cmTC_d1f60.dir\src.c.obj /FdCMakeFiles\cmTC_d1f60.dir\ /FS -c src.c

src.c(4): fatal error C1083: Cannot open include file: 'ptscotch.h': No such file or directory
ninja: build stopped: subcommand failed.

...and run output:

Return value: 1
Source file was:

#include <stdio.h>
#include <stdint.h>
#include <ptscotch.h>
int main(int argc, char **argv) {
  if (sizeof(SCOTCH_Num) == 8)
    return 0;
  else
    return 1;
}

Performing C++ SOURCE FILE Test COMPILER_SUPPORT_FASTMATH failed with the following output:
Change Dir: C:/vcpkg/buildtrees/eigen3/x64-windows-dbg/CMakeFiles/CMakeTmp

Run Build Command:"C:/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "cmTC_89fb1"
[1/2] Building CXX object CMakeFiles\cmTC_89fb1.dir\src.cxx.obj

cl : Command line warning D9002 : ignoring unknown option '-ffast-math'
[2/2] Linking CXX executable cmTC_89fb1.exe

Source file was:
int main() { return 0; }

**Comment by jonghoon-park** [comment]
using Visual studio 2017 and cmake 3.12.0-rc1

**Comment by jasjuang** [comment]
Builds for me without a problem. I am using cmake 3.11.4 not sure if that makes a difference.

**Comment by Voskrese** [comment]
ptscotch? You need to edit the port and remove the assembly from scotch

**Comment by edoreshef** [comment]
Same here. 
@Voskrese, What do you mean "edit the port and remove the assembly from scotch"?

**Comment by Voskrese** [comment]
cmake .. -LA

**Comment by ras0219-msft** [comment]
@jonghoon-park I think all the compile failures in that file are actually fine and expected. Could you post the _vcpkg_ error log? (buildtrees/eigen3/build-x64-windows-dbg-out.log)

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
