### ISSUE TITLE
On windows system with no Visual Studio installed, using the community triplet forces a default installation of `vcpkg-cmake` and `vcpkg-cmake-config` for `x64-windows`.

### ISSUE THREAD

**Issue by traversebitree** [microsoft/vcpkg#38026]
**Describe the bug**
On windows system with no Visual Studio installed, using the community triplet forces a default installation of `vcpkg-cmake` and `vcpkg-cmake-config` for `x64-windows`. But I have not installed Visual Studio, so there will be an error `error: in triplet x64-windows: Unable to find a valid Visual Studio instance`. Even if I manually installed `vcpkg-cmake-config:x64-mingw-dynamic` and `vcpkg-cmake:x64-mingw-dynamic`, the error still remains when I install `vcpkg.exe install fmt:x64-mingw-dynamic`.

**Environment**
- OS: Windows 11
- Compiler: llvm-mingw v18.1.3 https://github.com/mstorsjo/llvm-mingw/

**To Reproduce**
1. No Visual Studio. Only llvm-mingw installed.
1. ./vcpkg install fmt:x64-mingw-dynamic
2. See error
![image](https://github.com/microsoft/vcpkg/assets/30373236/1fe36945-d7d8-4ebc-bf7b-afd60e9a147c)

**Expected behavior**
The dependencies: `vcpkg-cmake` and `vcpkg-cmake-config` should not use triplet `x64-windows`.

They should be
- `vcpkg-cmake:x64-mingw-dynamic`
- `vcpkg-cmake-config:x64-mingw-dynamic`

**Failure logs**
![image](https://github.com/microsoft/vcpkg/assets/30373236/1fe36945-d7d8-4ebc-bf7b-afd60e9a147c)

**Additional context**
Visual Studio is too huge and I do not want to install it on my Windows machine. llvm-mingw is very small size.

**Comment by Osyotr** [comment]
You've specified target triplet, but did not specify host triplet. Try `./vcpkg install fmt --triplet=x64-mingw-dynamic --host-triplet=x64-mingw-dynamic`.

**Comment by traversebitree** [comment]
Thank you!
