### ISSUE TITLE
vckpg on ubuntu desktop fails to compile flatbuffers

### ISSUE THREAD

**Issue by cempayzin** [Microsoft/vcpkg#3804]
tester@tester-virtual-machine:~/vcpkg$ ./vcpkg  list
cryptopp:x64-linux                                 6.1.0-2          Crypto++ is a free C++ class library of cryptogr...
tester@tester-virtual-machine:~/vcpkg$ ./vcpkg  update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
tester@tester-virtual-machine:~/vcpkg$ ./vcpkg install flatbuffers
The following packages will be built and installed:
    flatbuffers[core]:x64-linux
Starting package 1/1: flatbuffers:x64-linux
Building package flatbuffers[core]:x64-linux... 
-- Using cached /home/tester/vcpkg/downloads/google-flatbuffers-v1.9.0.tar.gz
-- Using source at /home/tester/vcpkg/buildtrees/flatbuffers/src/v1.9.0-d534cc7a83
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: /home/tester/vcpkg/downloads/tools/cmake-3.10.2-linux/cmake-3.10.2-Linux-x86_64/bin/cmake;/home/tester/vcpkg/buildtrees/flatbuffers/src/v1.9.0-d534cc7a83;-DFLATBUFFERS_BUILD_TESTS=OFF;-DFLATBUFFERS_BUILD_GRPCTEST=OFF;-DCMAKE_MAKE_PROGRAM=/home/tester/vcpkg/downloads/tools/ninja-1.8.2-linux/ninja;-DCMAKE_SYSTEM_NAME=Linux;-DBUILD_SHARED_LIBS=OFF;-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/tester/vcpkg/scripts/toolchains/linux.cmake;-DVCPKG_TARGET_TRIPLET=x64-linux;-DVCPKG_PLATFORM_TOOLSET=external;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=/home/tester/vcpkg/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DVCPKG_CXX_FLAGS=;-DVCPKG_CXX_FLAGS_RELEASE=;-DVCPKG_CXX_FLAGS_DEBUG=;-DVCPKG_C_FLAGS=;-DVCPKG_C_FLAGS_RELEASE=;-DVCPKG_C_FLAGS_DEBUG=;-DVCPKG_CRT_LINKAGE=dynamic;-DVCPKG_LINKER_FLAGS=;-DCMAKE_INSTALL_LIBDIR:STRING=lib;-DCMAKE_INSTALL_BINDIR:STRING=bin;-G;Ninja;-DCMAKE_BUILD_TYPE=Debug;-DCMAKE_INSTALL_PREFIX=/home/tester/vcpkg/packages/flatbuffers_x64-linux/debug
    Working Directory: /home/tester/vcpkg/buildtrees/flatbuffers/x64-linux-dbg
    See logs for more information:
      /home/tester/vcpkg/buildtrees/flatbuffers/config-x64-linux-dbg-out.log
      /home/tester/vcpkg/buildtrees/flatbuffers/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:249 (vcpkg_execute_required_process)
  ports/flatbuffers/portfile.cmake:24 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package flatbuffers:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: flatbuffers:x64-linux
  Vcpkg version: 0.0.113-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by sanxiyn** [comment]
flatbuffers:x64-linux installs fine and this is unreproducible.

**Comment by LarryIII** [comment]
Not repro this issue. Please open a new issue if this is still a problem for you
