### ISSUE TITLE
Unable to find the port added in the custom registry

### ISSUE THREAD

**Issue by QiuYilin** [microsoft/vcpkg#38061]
I added one port in my custom registry.Then official vcpkg.exe can not find the new port by vcpkg-configuration.json like this:
```
{
    "default-registry": {
        "kind": "git",
            "repository": "https://github.com/Microsoft/vcpkg",
            "baseline": "ce1916404fc6f2b645f419a6d47b7ebafe686582"
    },
    "registries": [
        {
            "kind": "git",
			"repository": "https://mygit/vcpkg-registry",
			"packages":[
                                "new_port"
			],
            "baseline": "a7de4b075c4aecfc3c2fa65a6eae6230b71c6bd2"
        }
    ]
}
```
I have checked the baseline of custom registry. 
If I install it directly, an error will be reported ：

```
error: while looking for new_port:x64-windows:
error: failed to execute: "C:\Program Files\Git\cmd\git.exe" "--git-dir=C:\Users\user.QIUYILIN-L1\AppData\Local\vcpkg\registries\git\.git" "--work-tree=C:\Users\user.QIUYILIN-L1\AppData\Local\vcpkg\registries\git-trees\c5b965fc3dd1aa00cc7946591cc928b64e257334_4448.tmp" -c core.autocrlf=false read-tree -m -u c5b965fc3dd1aa00cc7946591cc928b64e257334
error: git failed with exit code: (128).
fatal: failed to unpack tree object c5b965fc3dd1aa00cc7946591cc928b64e257334
```

If I copy the same file of new port  into the official vcpkg root directory and disable vcpkg-configuration.json , searching and installing are normal. 

**Environment**
- OS: Windows
- Compiler: MSVC

**Comment by JonLiu1993** [comment]
In your `vcpkg-configuration.json`, you have defined a custom registry using the repository URL "https://mygit/vcpkg-registry". Can you open this repository? I can't open.

**Comment by QiuYilin** [comment]
@JonLiu1993  the URL name is an example. The connection is correct and other packages defined in custom registry can be found successfully.

**Comment by JonLiu1993** [comment]
@QiuYilin, Which port did you update? Can the updated port be installed normally?

**Comment by QiuYilin** [comment]
@JonLiu1993  I repeated steps ④ and ⑤ directly on the master, and now it can be found. I think I may have messed up the git execution steps after executing the correct format script midway. I think I don't understand the requirements for the git-tree in the port's version file.

**Comment by JonLiu1993** [comment]
So is this issue resolved now?

**Comment by QiuYilin** [comment]
@JonLiu1993  Yes，but can you explain what are the requirements for git-tree in the version file? It must be after the commit of the port is modified and there is no problem with the format at this time?

**Comment by JonLiu1993** [comment]
For detailed instructions on git tree, you can refer to the official documentation: https://github.com/microsoft/vcpkg-docs/blob/975d4acc8aee320ebb8c95761b08b6dbeacfde99/vcpkg/commands/add-version.md
After modifying the commit of the port, a new "git-tree" will be generated
