### ISSUE TITLE
[re2] re2 port doesn't work with cmake 3.29.1

### ISSUE THREAD

**Issue by adamreeve** [microsoft/vcpkg#38064]
**Describe the bug**

After GitHub actions runners were updated to use cmake 3.29.1 (https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20240407.1), our builds of ParquetSharp, which depends on re2, have started failing due to this issue in re2: https://github.com/google/re2/issues/488.

This is caused by this change in cmake: https://gitlab.kitware.com/cmake/cmake/-/commit/6ddf8712cdcc1b548af4b502ea91e94cf0bf4f0b

**Environment**

I've reproduced this in my local dev environment:
- OS: Fedora Linux 39
- Compiler: gcc 13.2.1
- Cmake: 3.29.1

**To Reproduce**

Build a project that uses re2:

vcpkg.json:
```
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json",
  "name": "re2-build-test",
  "version-string": "undefined",
  "builtin-baseline": "0bc3f04da6cb8ae1dbd5e2051032c596bb03cffa",
  "dependencies": [
    "re2"
  ]
}
```

CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.16)

project(re2-build-test VERSION 0.1 LANGUAGES CXX)

find_package(re2 CONFIG REQUIRED)

add_executable(program src/main.cc)
target_link_libraries(program PRIVATE re2::re2)
```

src/main.cc:
```
int main() {
  return 0;
}
```

Build with vcpkg:
```
cmake -B build -S . -D CMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake
cmake --build build
```

**Expected behavior**

The program should build successfully.

**Failure logs**

Building and installing re2 itself works, but then building the local program fails with:
```
CMake Error at build/vcpkg_installed/x64-linux/share/re2/re2Config.cmake:15 (message):
  File or directory /include referenced by variable re2_INCLUDE_DIR does not                                                                                   
  exist !                                                                      
Call Stack (most recent call first):                                           
  build/vcpkg_installed/x64-linux/share/re2/re2Config.cmake:33 (set_and_check)
  /home/adam/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  CMakeLists.txt:5 (find_package)   
```

The line causing the error in `build/vcpkg_installed/x64-linux/share/re2/re2Config.cmake` is:
```
set_and_check(re2_INCLUDE_DIR ${PACKAGE_PREFIX_DIR}/include)
```

Because `PACKAGE_PREFIX_DIR` is not defined.

**Additional context**

This has been fixed upstream in re2: https://github.com/google/re2/commit/9ebe4a22cad8a025b68a9594bdff3c047a111333

Would you accept a patch to backport this fix for the current version of re2 in vcpkg?

If not, we can work around this by using our own port of re2 with a patch, or install an older version of cmake on our GitHub action runners, but it seems likely that other users will run into this too.

**Comment by dg0yt** [comment]
This port really needs the specific fix. 

But note that CMake 3.29.1 breaks vcpkg's cmake config fixup ATM, https://github.com/microsoft/vcpkg/issues/37968 (Well, vcpkg relies on CMake implementation details, not on interfaces...)
