### ISSUE TITLE
libwebp libsharpyuv.dll dependency not satisfied

### ISSUE THREAD

**Issue by hafedh-trimeche** [microsoft/vcpkg#38079]
**Describe the bug**

**Environment**
- OS: Windows
- Compiler: 2024-03-14

**To Reproduce**
1. ./vcpkg install libwebp

**Expected behavior**
**libsharpyuv.dll** should also installed

![image](https://github.com/microsoft/vcpkg/assets/988584/c2032579-d2dc-4ac3-85a3-b9d810299fb6)

**Comment by JonLiu1993** [comment]
@hafedh-trimeche, I want to confirm with you: Your problem is that libsharpyuv.dll after libwebp is installed lacks the following *.dll dependencies?
![image](https://github.com/microsoft/vcpkg/assets/63675417/48a8f20f-241b-44c3-8305-3ffb2168bc8f)

**Comment by hafedh-trimeche** [comment]
Indeed, **libsharpyuv.dll** not included as a dependency when invoking **vcpkg install libwebp**.

Msys2 did: https://packages.msys2.org/package/mingw-w64-x86_64-libwebp?repo=mingw64

**Comment by JonLiu1993** [comment]
Is your error about `libwebp:x64-mingw`?

**Comment by hafedh-trimeche** [comment]
YES

**Comment by dg0yt** [comment]
When I tested it today with x64-mingw-dynamic, libsharpyuv.dll was properly installed in `/bin`.

**Comment by dg0yt** [comment]
> > Is your error about `libwebp:x64-mingw`?
>
> YES

No. x64-windows != x64-mingw.
