### ISSUE TITLE
[dlib] build failure on Windows

### ISSUE THREAD

**Issue by pkeir** [microsoft/vcpkg#38081]
### Operating system

Windows 11

### Compiler

Microsoft Visual Studio Enterprise 2022 (64-bit) - Current Version 17.6.5

### Steps to reproduce the behavior

```Shell
`./vcpkg install dlib`
```

### Failure logs

1>------ Build started: Project: mlp_ex, Configuration: Debug x64 ------
1>mlp_ex.cpp
1>LINK : fatal error LNK1104: cannot open file 'C:\Program Files (x86)\Intel\oneAPI\mkl\2021.1.1\lib\intel64\mkl_intel_lp64.lib'
1>Done building project "mlp_ex.vcxproj" -- FAILED.

### Additional context

It worked previously. It seems Intel oneAPI is now expected. Within the Visual Studio project generated by CMake, a number of explicit non-existent paths are found:

```
C:\Program Files (x86)\Intel\oneAPI\mkl\2021.1.1\lib\intel64\mkl_intel_lp64.lib
C:\Program Files (x86)\Intel\oneAPI\mkl\2021.1.1\lib\intel64\mkl_core.lib
C:\Program Files (x86)\Intel\oneAPI\mkl\2021.1.1\lib\intel64\mkl_intel_thread.lib
C:\Program Files (x86)\Intel\oneAPI\compiler\2021.1.1\windows\compiler\lib\intel64_win\libiomp5md.lib
```

Here is the CMakeLists.txt file contents:

```
cmake_minimum_required(VERSION 3.7)

set(VCPKG_CMAKE "C:/vcpkg/scripts/buildsystems/vcpkg.cmake")
set(CMAKE_TOOLCHAIN_FILE ${VCPKG_CMAKE})

set(n mlp_ex)
project(${n})

add_executable(${n} ${n}.cpp)

find_package(dlib REQUIRED)

target_link_libraries(${n} dlib::dlib)
set_property(DIRECTORY PROPERTY VS_STARTUP_PROJECT ${n})
```

**Comment by MonicaLiu0311** [comment]
Srry I can't repro your issue.

```
G:\test_manifest\build>cmake ..
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
-- The CXX compiler identification is MSVC 19.39.33522.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (3.6s)
-- Generating done (0.0s)
CMake Warning (dev) in CMakeLists.txt:
  Directory property VS_STARTUP_PROJECT specifies target 'test_manifest' that
  does not exist.  Ignoring.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Build files have been written to: G:/test_manifest/build

G:\test_manifest\build>
G:\test_manifest\build>
G:\test_manifest\build>
G:\test_manifest\build>
G:\test_manifest\build>cmake --build .
MSBuild version 17.9.5+33de0b227 for .NET Framework

  1>Checking Build System
  Building Custom Rule G:/test_manifest/CMakeLists.txt
  main.cpp
  main.vcxproj -> G:\test_manifest\build\Debug\main.exe
  Building Custom Rule G:/test_manifest/CMakeLists.txt
```


<details>
<summary><b>main.cpp</b></summary>
<pre>
#include &#60;iostream&#62;
#include "dlib/config.h"

using namespace std;

int main()
{
    cout << "Hello CMake." << endl;
    return 0;
}
</pre></details>

<details>
<summary><b>CMakeLists.txt</b></summary>
<pre>
cmake_minimum_required(VERSION 3.8)

set(CMAKE_TOOLCHAIN_FILE "G:/vcpkg/scripts/buildsystems/vcpkg.cmake")

project(test_manifest CXX)
add_executable(main main.cpp)

find_package(dlib CONFIG REQUIRED)
target_link_libraries(main PRIVATE dlib::dlib)

set_property(DIRECTORY PROPERTY VS_STARTUP_PROJECT test_manifest)
</pre></details>

**Comment by MonicaLiu0311** [comment]
```
PS G:\vcpkg> ./vcpkg version
vcpkg package management program version 2024-03-14-7d353e869753e5609a1f1a057df3db8fd356e49d

See LICENSE.txt for license information.
```
Please confirm your current vcpkg version and try the following commands:

```
./vcpkg remove dlib lapack lapack-reference --recurse
./vcpkg install dlib
```

**Comment by Neumann-A** [comment]
That is a problem which happens if MKL is installed but blas/lapack is not explicitly controlled. Try rebuilding with https://github.com/microsoft/vcpkg/pull/38100

**Comment by MonicaLiu0311** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
