### ISSUE TITLE
[proxygen] build failure

### ISSUE THREAD

**Issue by jkammerland** [microsoft/vcpkg#38086]
### Operating system

Linux

### Compiler

GCC 13.2

### Steps to reproduce the behavior

```Shell
vcpkg install proxygen
```

### Failure logs

undefined reference to `io_uring_submit' 

i.e
/usr/bin/ld: /home/jonkam/Programmering/cpp/cpp_rebuild_template/build/vcpkg_installed/x64-linux/debug/lib/libfolly.a(IoUringBackend.cpp.o): in function `folly::IoUringBackend::submitBusyCheck(int, folly::IoUringBackend::WaitForEventsMode)':
/home/jonkam/Programmering/cpp/cpp_rebuild_template/vcpkg/buildtrees/folly/src/4.01.01.00-60a2322077.clean/folly/experimental/io/IoUringBackend.cpp:1874: undefined reference to `io_uring_submit'

### Additional context

Not a selfcontained package.
Fedora 38
got liburing-devel installed.

**Comment by dg0yt** [comment]
Upstream folly and proxygen don't allow control over liburing, but rely on `__has_include`.
To resolve installation order issues, the ports need additional patches, or must unconditionally depend on and use uring on linux.

(Fixing the uring feature in folly is not enough.)
