### ISSUE TITLE
Boost Errors

### ISSUE THREAD

**Issue by Gr8-Dane** [Microsoft/vcpkg#3808]
Hi All,
   I'm going crazy trying to figure this out. I'm trying to read some .ply files and was going to use PCL to do that. I've taken my code out to see what the problem is, and its something to do with the header files and boost. Here's the code I try and compile just as something to run:

#include <iostream>
#include <pcl/point_types.h>
#include <pcl/io/ply_io.h>

int main() {

	return(0);
};

And heres the error i get as a result. Any ideas?? I've some people with similar looking issues but their solutions haven't seemed to help. 

1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\memory(46): error C4996: 'std::uninitialized_copy::_Unchecked_iterators::_Deprecate': Call to 'std::uninitialized_copy' with parameters that may be unsafe - this call relies on the caller to check that the passed values are correct. To disable this warning, use -D_SCL_SECURE_NO_WARNINGS. See documentation on how to use Visual C++ 'Checked Iterators'
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\memory(46): note: see declaration of 'std::uninitialized_copy::_Unchecked_iterators::_Deprecate'
1>c:\users\dane.rich\vcpkg\installed\x64-windows-static\include\boost\signals2\detail\auto_buffer.hpp(191): note: see reference to function template instantiation '_FwdIt *std::uninitialized_copy<I,boost::shared_ptr<void>*>(const _InIt,const _InIt,_FwdIt)' being compiled
1>        with
1>        [
1>            _FwdIt=boost::shared_ptr<void> *,
1>            I=boost::shared_ptr<void> *,
1>            _InIt=boost::shared_ptr<void> *
1>        ]
1>c:\users\dane.rich\vcpkg\installed\x64-windows-static\include\boost\signals2\detail\auto_buffer.hpp(178): note: see reference to function template instantiation 'void boost::signals2::detail::auto_buffer<boost::shared_ptr<void>,boost::signals2::detail::store_n_objects<10>,boost::signals2::detail::default_grow_policy,std::allocator<T>>::copy_rai<I,false>(I,I,boost::shared_ptr<void> *,const boost::integral_constant<bool,false> &)' being compiled
1>        with
1>        [
1>            T=boost::shared_ptr<void>,
1>            I=boost::shared_ptr<void> *
1>        ]
1>c:\users\dane.rich\vcpkg\installed\x64-windows-static\include\boost\signals2\detail\auto_buffer.hpp(178): note: see reference to function template instantiation 'void boost::signals2::detail::auto_buffer<boost::shared_ptr<void>,boost::signals2::detail::store_n_objects<10>,boost::signals2::detail::default_grow_policy,std::allocator<T>>::copy_rai<I,false>(I,I,boost::shared_ptr<void> *,const boost::integral_constant<bool,false> &)' being compiled
1>        with
1>        [
1>            T=boost::shared_ptr<void>,
1>            I=boost::shared_ptr<void> *
1>        ]
1>c:\users\dane.rich\vcpkg\installed\x64-windows-static\include\boost\signals2\detail\auto_buffer.hpp(204): note: see reference to function template instantiation 'void boost::signals2::detail::auto_buffer<boost::shared_ptr<void>,boost::signals2::detail::store_n_objects<10>,boost::signals2::detail::default_grow_policy,std::allocator<T>>::copy_impl<I>(I,I,boost::shared_ptr<void> *,std::random_access_iterator_tag)' being compiled
1>        with
1>        [
1>            T=boost::shared_ptr<void>,
1>            I=boost::shared_ptr<void> *
1>        ]
1>c:\users\dane.rich\vcpkg\installed\x64-windows-static\include\boost\signals2\detail\auto_buffer.hpp(203): note: see reference to function template instantiation 'void boost::signals2::detail::auto_buffer<boost::shared_ptr<void>,boost::signals2::detail::store_n_objects<10>,boost::signals2::detail::default_grow_policy,std::allocator<T>>::copy_impl<I>(I,I,boost::shared_ptr<void> *,std::random_access_iterator_tag)' being compiled
1>        with
1>        [
1>            T=boost::shared_ptr<void>,
1>            I=boost::shared_ptr<void> *
1>        ]
1>c:\users\dane.rich\vcpkg\installed\x64-windows-static\include\boost\signals2\detail\auto_buffer.hpp(304): note: see reference to function template instantiation 'void boost::signals2::detail::auto_buffer<boost::shared_ptr<void>,boost::signals2::detail::store_n_objects<10>,boost::signals2::detail::default_grow_policy,std::allocator<T>>::copy_impl<boost::shared_ptr<void>*>(I,I,boost::shared_ptr<void> *)' being compiled
1>        with
1>        [
1>            T=boost::shared_ptr<void>,
1>            I=boost::shared_ptr<void> *
1>        ]
1>c:\users\dane.rich\vcpkg\installed\x64-windows-static\include\boost\signals2\detail\auto_buffer.hpp(304): note: see reference to function template instantiation 'void boost::signals2::detail::auto_buffer<boost::shared_ptr<void>,boost::signals2::detail::store_n_objects<10>,boost::signals2::detail::default_grow_policy,std::allocator<T>>::copy_impl<boost::shared_ptr<void>*>(I,I,boost::shared_ptr<void> *)' being compiled
1>        with
1>        [
1>            T=boost::shared_ptr<void>,
1>            I=boost::shared_ptr<void> *
1>        ]
1>c:\users\dane.rich\vcpkg\installed\x64-windows-static\include\boost\signals2\detail\auto_buffer.hpp(302): note: while compiling class template member function 'boost::shared_ptr<void> *boost::signals2::detail::auto_buffer<boost::shared_ptr<void>,boost::signals2::detail::store_n_objects<10>,boost::signals2::detail::default_grow_policy,std::allocator<T>>::move_to_new_buffer(unsigned __int64,const boost::true_type &)'
1>        with
1>        [
1>            T=boost::shared_ptr<void>
1>        ]
1>c:\users\dane.rich\vcpkg\installed\x64-windows-static\include\boost\signals2\detail\auto_buffer.hpp(310): note: see reference to function template instantiation 'boost::shared_ptr<void> *boost::signals2::detail::auto_buffer<boost::shared_ptr<void>,boost::signals2::detail::store_n_objects<10>,boost::signals2::detail::default_grow_policy,std::allocator<T>>::move_to_new_buffer(unsigned __int64,const boost::true_type &)' being compiled
1>        with
1>        [
1>            T=boost::shared_ptr<void>
1>        ]
1>c:\users\dane.rich\vcpkg\installed\x64-windows-static\include\boost\signals2\connection.hpp(53): note: see reference to class template instantiation 'boost::signals2::detail::auto_buffer<boost::shared_ptr<void>,boost::signals2::detail::store_n_objects<10>,boost::signals2::detail::default_grow_policy,std::allocator<T>>' being compiled
1>        with
1>        [
1>            T=boost::shared_ptr<void>
1>        ]
1>c:\users\dane.rich\vcpkg\installed\x64-windows-static\include\boost\signals2\connection.hpp(55): note: see reference to class template instantiation 'boost::signals2::detail::garbage_collecting_lock<Mutex>' being compiled
1>c:\users\dane.rich\vcpkg\installed\x64-windows-static\include\boost\bind\placeholders.hpp(54): note: see reference to class template instantiation 'boost::arg<9>' being compiled
1>c:\users\dane.rich\vcpkg\installed\x64-windows-static\include\boost\bind\placeholders.hpp(53): note: see reference to class template instantiation 'boost::arg<8>' being compiled
1>c:\users\dane.rich\vcpkg\installed\x64-windows-static\include\boost\bind\placeholders.hpp(52): note: see reference to class template instantiation 'boost::arg<7>' being compiled
1>c:\users\dane.rich\vcpkg\installed\x64-windows-static\include\boost\bind\placeholders.hpp(51): note: see reference to class template instantiation 'boost::arg<6>' being compiled
1>c:\users\dane.rich\vcpkg\installed\x64-windows-static\include\boost\bind\placeholders.hpp(50): note: see reference to class template instantiation 'boost::arg<5>' being compiled
1>c:\users\dane.rich\vcpkg\installed\x64-windows-static\include\boost\bind\placeholders.hpp(49): note: see reference to class template instantiation 'boost::arg<4>' being compiled
1>c:\users\dane.rich\vcpkg\installed\x64-windows-static\include\boost\bind\placeholders.hpp(48): note: see reference to class template instantiation 'boost::arg<3>' being compiled
1>c:\users\dane.rich\vcpkg\installed\x64-windows-static\include\boost\bind\placeholders.hpp(47): note: see reference to class template instantiation 'boost::arg<2>' being compiled
1>c:\users\dane.rich\vcpkg\installed\x64-windows-static\include\boost\bind\placeholders.hpp(46): note: see reference to class template instantiation 'boost::arg<1>' being compiled
1>Done building project "Data_Reading.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by LarryIII** [comment]
@Gr8-Dane Thanks for your feedback, I did not reproduce your issue with your code demo. Please open a new issue if this is still a problem for you.
