### ISSUE TITLE
Nuget uses .lib or .dll

### ISSUE THREAD

**Issue by tellybobah** [microsoft/vcpkg#3810]
Hi,
I recently started to used vcpkg. I installed openssl:x64 and openssl:x86 and exported them into my project but when i compile i would like my code to use the .dll and not .lib. I'm not quite familiar with the tool so I would like some help if you can provide. Thanks

**Comment by JackBoosY** [comment]
You need to export `openssl:x64-windows` or `openssl:x64-windows`.
Please feel free to open this issue if it still bother you.

Thanks.
