### ISSUE TITLE
tiff build failure

### ISSUE THREAD

**Issue by sgillies** [microsoft/vcpkg#38116]
### Operating system

Windows

### Steps to reproduce the behavior

The tiff port builds with zstd and lerc features, but not with webp. Specifying this in my project's vcpkg.json results in a non-finishing build.

```json
    "dependencies": [
        { "name": "tiff", "features": [ "zstd", "lerc", "webp" ] },
        "gdal"
    ],
```

Log excerpt is included below.

### Failure logs

In `config-x64-windows-out.log`:

```
...
-- Found ZLIB: optimized;C:/vcpkg/installed/x64-windows/lib/zlib.lib;debug;C:/vcpkg/installed/x64-windows/debug/lib/zlibd.lib (found version "1.3.1")
-- Could NOT find Deflate (missing: Deflate_LIBRARY Deflate_INCLUDE_DIR)
-- Found JPEG: optimized;C:/vcpkg/installed/x64-windows/lib/jpeg.lib;debug;C:/vcpkg/installed/x64-windows/debug/lib/jpeg.lib (found version "62")
-- Could NOT find JBIG (missing: JBIG_LIBRARY JBIG_INCLUDE_DIR)
-- Found LERC: C:/vcpkg/installed/x64-windows/lib/Lerc.lib (found version "4.0.0")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
CMake Error at C:/vcpkg/installed/x64-windows/share/WebP/WebPConfig.cmake:15 (message):
  File or directory C:/vcpkg/installed/include referenced by variable
  WebP_INCLUDE_DIR does not exist !
Call Stack (most recent call first):
  C:/vcpkg/installed/x64-windows/share/WebP/WebPConfig.cmake:38 (set_and_check)
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  cmake/WebPCodec.cmake:29 (find_package)
  CMakeLists.txt:123 (include)


-- Configuring incomplete, errors occurred!
ninja: build stopped: subcommand failed.
```

### Additional context

@dg0yt I'd try to sort this out myself but I have no Windows computer.

**Comment by dg0yt** [comment]
You are stumbling over CMake 3.29.1. Downgrade, and reinstall all ports which were built with that version.
https://github.com/microsoft/vcpkg/issues/37968

**Comment by sgillies** [comment]
Ugh. Thanks for the explanation @dg0yt ! I really do appreciate your work on the GDAL-related packages her 🙏

**Comment by sgillies** [comment]
@dg0yt I'm finding it difficult to downgrade or tell vcpkg to use my downgraded version. The GitHub runners have 3.29.1 and installing cmake 3.28.4 via pip or the lukka/get-cmake action (which I've seen others do) doesn't work. In the tiff build logs I still only see references to 3.29.

```
cd tiff; grep -R "3.29" .
./config-x64-windows-rel-CMakeCache.txt.log:CMAKE_ROOT:INTERNAL=C:/Program Files/CMake/share/cmake-3.29
./config-x64-windows-dbg-CMakeCache.txt.log:CMAKE_ROOT:INTERNAL=C:/Program Files/CMake/share/cmake-3.29
```

**Comment by jimwang118** [comment]
You can try PR [38017](https://github.com/microsoft/vcpkg/pull/38017) to see if it can solve your problem.

**Comment by jimwang118** [comment]
@sgillies Does it compile normally after you downgrade cmake to 3.29.0 or upgrade to 3.29.2?

**Comment by sgillies** [comment]
@jimwang118 I'm using GitHub Actions, where the runners didn't have 3.29.2 until yesterday, and found it too difficult to convince vcpkg to not use the pre-installed cmake. So I went with an overlay port for vcpkg-cmake-config.

**Comment by jimwang118** [comment]
@sgillies Is your issue solved now?

**Comment by sgillies** [comment]
@jimwang118 I don't know. I haven't had the free time to see if my overlay port can be removed. GHA windows-latest runners have [cmake 3.29.3 now](https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md), so I'll presume the problem is fixed and close this issue. Thanks for the support!
