### ISSUE TITLE
[New Port Request] <sparkle>

### ISSUE THREAD

**Issue by fwcd** [microsoft/vcpkg#38117]
### Library name

Sparkle

### Library description

Software update framework for macOS applications

### Source repository URL

https://github.com/sparkle-project/Sparkle

### Project homepage (if different from the source repository)

https://sparkle-project.org/

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

The library is built with Xcode (the Makefile is just a thin wrapper around that) and IIUC has to be built as a macOS framework (i.e. a bundle). Some experimental attempts at packaging up Sparkle in a port can be found [in this branch](https://github.com/fwcd/vcpkg/tree/sparkle). If I get around verifying that this is actually usable, a PR might follow, otherwise anyone should feel free to have a go at that.

**Comment by kevin--** [comment]
we have sparkle hosted as a pre-built in our internal registry. One of the challenges is deploying the framework to the build app bundle.

Our port injects a config file for the library so that it works with find_package that exposes a deploy function you can attach to the final target

```
function( sparkle_mac_deploy target )
  if( NOT TARGET ${target} )
    message( FATAL_ERROR "sparkle_mac_deploy: ${target} does not exist as a target" )
  endif()

  if( APPLE AND NOT IOS )
    add_custom_command( TARGET ${target} POST_BUILD
      COMMAND
        ditto "${SPARKLE_MAC_FRAMEWORK}" "$<TARGET_FILE_DIR:${target}>/../Frameworks/Sparkle.framework"
      COMMENT
        "Deploy Sparkle: ${SPARKLE_MAC_FRAMEWORK}"
    )
  endif()
endfunction()
```
