### ISSUE TITLE
Error installing protobuf on windows

### ISSUE THREAD

**Issue by MaxLovell** [Microsoft/vcpkg#3815]
I've downloaded the latest vcpkg using Git.
I run vcpkg.exe install protobuf:x32-windows
the following error occurs:

The following packages will be built and installed:
    protobuf[core]:x86-windows
Starting package 1/1: protobuf:x86-windows
Building package protobuf[core]:x86-windows...
-- Using cached C:/Program Files (x86)/vcpkg/downloads/protobuf-cpp-3.5.1.tar.gz
-- Applying patch C:/Program Files (x86)/vcpkg/ports/protobuf/001-add-compiler-flag.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/Program Files (x86)/vcpkg/ports/protobuf/export-ParseGeneratorParameter.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/Program Files (x86)/vcpkg/ports/protobuf/js-embed.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/Program Files (x86)/vcpkg/ports/protobuf/fix-uwp.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/Program Files (x86)/vcpkg/ports/protobuf/wire_format_lite_h_fix_error_C4146.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Using cached C:/Program Files (x86)/vcpkg/downloads/protoc-3.5.1-win32.zip
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:170 (message):
    Command failed: C:/Program Files (x86)/vcpkg/downloads/tools/cmake-3.11.4-windows/cmake-3.11.4-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: C:/Program Files (x86)/vcpkg/buildtrees/protobuf/x86-windows-dbg
    See logs for more information:
      C:\Program Files (x86)\vcpkg\buildtrees\protobuf\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/protobuf/portfile.cmake:75 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package protobuf:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: protobuf:x86-windows
  Vcpkg version: 0.0.113-nohash

Additionally, attach any relevant sections from the log files above.

I've attached the install log.

[install-x86-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2149222/install-x86-windows-dbg-out.log)

**Comment by arthur-tacca** [comment]
I think you have put vcpkg in a path containing spaces: "C:\Program Files (x86)\vcpkg". I don't know if that's actually the problem but it looks like it from the command that failed and the docs definitely say not to do that. Try again in a path without any spaces and see if you get the same error.

Here's the command that failed, taken from that log file:

    [87/208] cmd.exe /C "cd . && "C:\Program Files (x86)\vcpkg\downloads\tools\cmake-3.11.4-windows\cmake-3.11.4-win32-x86\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\js_embed.dir --manifests  -- 
    C:\PROGRA~2\MIB055~1\2017\ENTERP~1\VC\Tools\MSVC\1414~1.264\bin\Hostx64\x86\link.exe  
    CMakeFiles\js_embed.dir\C_\Program_Files_(x86)\vcpkg\buildtrees\protobuf\src\protobuf-3.5.1\src\google\protobuf\compiler\js\embed.cc.obj  /out:js_embed.exe /implib:js_embed.lib /pdb:js_embed.pdb /version:0.0  /machine:X86 /debug /INCREMENTAL  /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."

**Comment by MaxLovell** [comment]
Thanks for your help, that fixed it for me.

**Comment by fefy96** [comment]
Yep! It helped me too. Even though it wasn't in a weird path with white spaces in it, simply moving the whole folder where vcpkg was installed, to C:/ , solved the problem. Thank you!
