### ISSUE TITLE
[DPP] build failure on arm64-osx 

### ISSUE THREAD

**Issue by Xbz-24** [microsoft/vcpkg#38157]
### Operating system

OSX

### Compiler

Clang

### Steps to reproduce the behavior
I just pressed git install button in clion vcpkg menu and that package gets installed to this ~/.clion-vcpkg/ path and I get to reference that toolchain path through my .cmake files
```Shell
~/.clion-vcpkg/vcpkg/packages
```

### Failure logs

https://gist.github.com/Xbz-24/1d9f8ac45a87ddc25f6eeeae8db011bb

I added the logs in a gist because is too long

**Comment by jimwang118** [comment]
libsodium requires autoconf from the system package manager (example: "sudo  apt-get install autoconf")

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
