### ISSUE TITLE
[opencolorio] implicitly depends on other library

### ISSUE THREAD

**Issue by AlexeySmolenchuk** [microsoft/vcpkg#38153]
### Is your feature request related to a problem? Please describe.

 [opencolorio] fails to build until I manually add [lcms] to my project vcpkg.json

### Proposed solution

Explicitly add [lcms] library to [opencolorio] dependencies.

**Comment by FrankXie05** [comment]
@AlexeySmolenchuk Thanks for posting this issue, I can't reproduce your problem locally. 
Could you please provide the log of your failed build?
For `lcms`, the official clearly states that this is an option and it is dependent on the tool feature.

https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/67a26e4a383d2125bae437432cdad535d55c751b/share/cmake/modules/FindExtPackages.cmake#L126

https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/67a26e4a383d2125bae437432cdad535d55c751b/docs/quick_start/installation.rst#L207:~:text=OpenImageIO-,lcms2,-pybind11

**Comment by AlexeySmolenchuk** [comment]
Hi @FrankXie05 

I've prepared a minimalistic repro here: https://github.com/AlexeySmolenchuk/vcpkg_repro_38153


Clone, checkout **main** branch, configure cmake.
```
git clone git@github.com:AlexeySmolenchuk/vcpkg_repro_38153.git --recursive
cd vcpkg_repro_38153
git checkout main
mkdir build
cd build
cmake ..
```
After bootstrapping I'm getting this error:
```
[cmake] CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package):
[cmake]   Could not find a package configuration file provided by "lcms2" with any of
[cmake]   the following names:
[cmake] 
[cmake]     lcms2Config.cmake
[cmake]     lcms2-config.cmake
...
-- Configuring incomplete, errors occurred!
```

Checkout to **workaround** branch, which explicitly set [lcms] as dependency. https://github.com/AlexeySmolenchuk/vcpkg_repro_38153/blob/workaround/vcpkg.json#L3 \
Configure cmake.
```
git checkout workaround
cmake ..
```
Now it's working.

Details:
OS Windows 10\
cmake-3.27

Thanks,
Alexey

**Comment by FrankXie05** [comment]
@AlexeySmolenchuk 
Thank you very much for your patience in explaining and replicating the code, I noticed that your `vcpkg.json` is missing a critical part. As I said, `lcms` depends on `tools` features, so you need to modify your `vcpkg.json` file like this:
```
{
  "dependencies": [
    {
      "name": "opencolorio",
      "features": [
        "tools"
      ]
    }
  ]
```
Reference documentation： https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/reference/vcpkg-json.md

**Comment by dg0yt** [comment]
This proposal is so wrong. Please investigate the error properly.
@AlexeySmolenchuk Your manifest is okay. If you don't need tools, you don't need to ask for tools.

**Comment by AlexeySmolenchuk** [comment]
If [lcms] is optional by design it shouldn't be triggered when I build default [opencolorio] without extensions.
