### ISSUE TITLE
[gdal] build failure

### ISSUE THREAD

**Issue by Bzz2745** [microsoft/vcpkg#38168]
### Operating system

Windows

### Compiler

MSVC vs143

### Steps to reproduce the behavior

```Shell
`./vcpkg install gdal[aws-ec2-windows,cfitsio,core,curl,default-features,expat,freexl,geos,gif,hdf5,iconv,jpeg,lerc,libkml,libspatialite,libxml2,lzma,netcdf,openjpeg,openssl,pcre2,png,poppler,postgresql,qhull,recommended-features,sqlite3,supported-default-features,system-libraries,tools,webp,zstd]:x64-windows`
```

### Failure logs

Installing 1/91 gdal[aws-ec2-windows,cfitsio,core,curl,default-features,expat,freexl,geos,gif,hdf5,iconv,jpeg,lerc,libkml,libspatialite,libxml2,lzma,netcdf,openjpeg,openssl,pcre2,png,poppler,postgresql,qhull,recommended-features,sqlite3,supported-default-features,system-libraries,tools,webp,zstd]:x64-windows@3.8.4...
Building gdal[aws-ec2-windows,cfitsio,core,curl,default-features,expat,freexl,geos,gif,hdf5,iconv,jpeg,lerc,libkml,libspatialite,libxml2,lzma,netcdf,openjpeg,openssl,pcre2,png,poppler,postgresql,qhull,recommended-features,sqlite3,supported-default-features,system-libraries,tools,webp,zstd]:x64-windows@3.8.4...
-- Using cached OSGeo-gdal-v3.8.4.tar.gz.
-- Extracting source C:/Users/bazunzhi/opt/vcpkg/downloads/OSGeo-gdal-v3.8.4.tar.gz
-- Applying patch find-link-libraries.patch
-- Applying patch fix-gdal-target-interfaces.patch
-- Applying patch libkml.patch
-- Applying patch target-is-valid.patch
-- Using source at C:/Users/bazunzhi/opt/vcpkg/buildtrees/gdal/src/v3.8.4-21e5819874.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/Users/bazunzhi/opt/vcpkg/buildtrees/gdal/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\bazunzhi\opt\vcpkg\buildtrees\gdal\config-x64-windows-dbg-CMakeCache.txt.log
      C:\Users\bazunzhi\opt\vcpkg\buildtrees\gdal\config-x64-windows-rel-CMakeCache.txt.log
      C:\Users\bazunzhi\opt\vcpkg\buildtrees\gdal\config-x64-windows-out.log

### Additional context

[config-x64-windows-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/14964801/config-x64-windows-rel-CMakeCache.txt.log)
[config-x64-windows-dbg-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/14964802/config-x64-windows-dbg-CMakeCache.txt.log)
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/14964803/config-x64-windows-out.log)

**Comment by dg0yt** [comment]
Don't use CMake 3.29.1: https://github.com/microsoft/vcpkg/issues/37968
Replace CMake, and reinstall all packages that were built with this version.

**Comment by MonicaLiu0311** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
