### ISSUE TITLE
Building GDAL on Ubuntu 18.04 fails on openjpeg

### ISSUE THREAD

**Issue by razor85** [microsoft/vcpkg#3816]
When trying to build gdal, it fails on openjpeg:
openjpeg:x64-linux
Vcpkg version: 0.0.113-unknownhash

err.log says:

CMake Error: INSTALL(EXPORT) given unknown export "OpenJPEGTargets"
CMake Warning:
Manually-specified variables were not used by the project:

CMAKE_INSTALL_BINDIR
CMAKE_INSTALL_LIBDIR
VCPKG_CRT_LINKAGE
VCPKG_PLATFORM_TOOLSET

**Comment by dethtoll1** [comment]
I can confirm the same issue on Ubuntu 16.04

**Comment by studiofuga** [comment]
See #4744 that fixes this issue.

**Comment by razor85** [comment]
> 
> 
> See #4744 that fixes this issue.

Proposed patch fixes this issue for me (openjpeg now builds successfully). There are still other issues but the jpeg one is gone.

**Comment by wangli28** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
