### ISSUE TITLE
[prometheus-cpp] build failure

### ISSUE THREAD

**Issue by spqqky** [microsoft/vcpkg#38199]
### Operating system

Linux

### Compiler

Clang

### Steps to reproduce the behavior

```Shell
<details><summary>vcpkg.json</summary>


{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg.schema.json",
  "dependencies": [
    {
      "name": "sdl2",
      "platform": "!windows"
    },
    {
      "name": "sdl2-image",
      "platform": "!windows"
    },
    {
      "name": "sdl2-ttf",
      "platform": "!windows"
    },
    "openssl",
    "jsoncpp",
    "libwebsockets",
    "curl",
    "zlib",
    {
      "name": "prometheus-cpp",
      "features": [
        "push",
        "compression"
      ]
    },
    "glfw3",
    "opengl",
    {
      "name": "imgui",
      "features": [
        "glfw-binding",
        "opengl3-binding"
      ],
      "platform": "windows"
    }
  ]
}

```
</details>
```


### Failure logs

Package: prometheus-cpp[compression,core,pull,push]:x64-linux@1.2.4

**Host Environment**

- Host: x64-linux
- Compiler: GNU 11.4.0
-    vcpkg-tool version: 2024-03-14-7d353e869753e5609a1f1a057df3db8fd356e49d
    vcpkg-scripts version: ad3bae5 2024-04-12 (3 days ago)

**To Reproduce**

`vcpkg install `
**Failure logs**

```
-- Downloading https://github.com/jupp0r/prometheus-cpp/archive/v1.2.4.tar.gz -> jupp0r-prometheus-cpp-v1.2.4.tar.gz...
-- Extracting source /home/vsts/work/1/s/vcpkg/downloads/jupp0r-prometheus-cpp-v1.2.4.tar.gz
-- Using source at /home/vsts/work/1/s/vcpkg/buildtrees/prometheus-cpp/src/v1.2.4-6cdf3985a5.clean
-- Configuring x64-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /home/vsts/work/1/s/vcpkg/downloads/tools/ninja/1.10.2-linux/ninja -v
    Working Directory: /home/vsts/work/1/s/vcpkg/buildtrees/prometheus-cpp/x64-linux-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      /home/vsts/work/1/s/vcpkg/buildtrees/prometheus-cpp/config-x64-linux-dbg-CMakeCache.txt.log
      /home/vsts/work/1/s/vcpkg/buildtrees/prometheus-cpp/config-x64-linux-rel-CMakeCache.txt.log
      /home/vsts/work/1/s/vcpkg/buildtrees/prometheus-cpp/config-x64-linux-out.log

Call Stack (most recent call first):
  /home/vsts/work/1/s/build/vcpkg_installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:252 (vcpkg_execute_required_process)
  ports/prometheus-cpp/portfile.cmake:20 (vcpkg_cmake_configure)
  scripts/ports.cmake:175 (include)

```
<details><summary>/home/vsts/work/1/s/vcpkg/buildtrees/prometheus-cpp/config-x64-linux-out.log</summary>

```
[1/2] "/usr/local/bin/cmake" -E chdir ".." "/usr/local/bin/cmake" "/home/vsts/work/1/s/vcpkg/buildtrees/prometheus-cpp/src/v1.2.4-6cdf3985a5.clean" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=/home/vsts/work/1/s/vcpkg/packages/prometheus-cpp_x64-linux" "-DFETCHCONTENT_FULLY_DISCONNECTED=ON" "-DUSE_THIRDPARTY_LIBRARIES=OFF" "-DGENERATE_PKGCONFIG=OFF" "-DENABLE_COMPRESSION=ON" "-DENABLE_PULL=ON" "-DENABLE_PUSH=ON" "-DENABLE_TESTING=OFF" "-DCMAKE_MAKE_PROGRAM=/home/vsts/work/1/s/vcpkg/downloads/tools/ninja/1.10.2-linux/ninja" "-DCMAKE_SYSTEM_NAME=Linux" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/vsts/work/1/s/vcpkg/scripts/toolchains/linux.cmake" "-DVCPKG_TARGET_TRIPLET=x64-linux" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=external" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=/home/vsts/work/1/s/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=/home/vsts/work/1/s/vcpkg" "-D_VCPKG_INSTALLED_DIR=/home/vsts/work/1/s/build/vcpkg_installed" "-DVCPKG_MANIFEST_INSTALL=OFF"
FAILED: ../CMakeCache.txt 
"/usr/local/bin/cmake" -E chdir ".." "/usr/local/bin/cmake" "/home/vsts/work/1/s/vcpkg/buildtrees/prometheus-cpp/src/v1.2.4-6cdf3985a5.clean" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=/home/vsts/work/1/s/vcpkg/packages/prometheus-cpp_x64-linux" "-DFETCHCONTENT_FULLY_DISCONNECTED=ON" "-DUSE_THIRDPARTY_LIBRARIES=OFF" "-DGENERATE_PKGCONFIG=OFF" "-DENABLE_COMPRESSION=ON" "-DENABLE_PULL=ON" "-DENABLE_PUSH=ON" "-DENABLE_TESTING=OFF" "-DCMAKE_MAKE_PROGRAM=/home/vsts/work/1/s/vcpkg/downloads/tools/ninja/1.10.2-linux/ninja" "-DCMAKE_SYSTEM_NAME=Linux" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/vsts/work/1/s/vcpkg/scripts/toolchains/linux.cmake" "-DVCPKG_TARGET_TRIPLET=x64-linux" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=external" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=/home/vsts/work/1/s/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=/home/vsts/work/1/s/vcpkg" "-D_VCPKG_INSTALLED_DIR=/home/vsts/work/1/s/build/vcpkg_installed" "-DVCPKG_MANIFEST_INSTALL=OFF"
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB - Success
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
CMake Error at /home/vsts/work/1/s/build/vcpkg_installed/x64-linux/share/civetweb/civetweb-config.cmake:11 (message):
  File or directory /home/vsts/work/1/s/build/vcpkg_installed/include
  referenced by variable civetweb_INCLUDE_DIR does not exist !
Call Stack (most recent call first):
  /home/vsts/work/1/s/build/vcpkg_installed/x64-linux/share/civetweb/civetweb-config.cmake:18 (set_and_check)
  /home/vsts/work/1/s/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  pull/CMakeLists.txt:11 (find_package)

-- Configuring incomplete, errors occurred!
[2/2] "/usr/local/bin/cmake" -E chdir "../../x64-linux-dbg" "/usr/local/bin/cmake" "/home/vsts/work/1/s/vcpkg/buildtrees/prometheus-cpp/src/v1.2.4-6cdf3985a5.clean" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=/home/vsts/work/1/s/vcpkg/packages/prometheus-cpp_x64-linux/debug" "-DFETCHCONTENT_FULLY_DISCONNECTED=ON" "-DUSE_THIRDPARTY_LIBRARIES=OFF" "-DGENERATE_PKGCONFIG=OFF" "-DENABLE_COMPRESSION=ON" "-DENABLE_PULL=ON" "-DENABLE_PUSH=ON" "-DENABLE_TESTING=OFF" "-DCMAKE_MAKE_PROGRAM=/home/vsts/work/1/s/vcpkg/downloads/tools/ninja/1.10.2-linux/ninja" "-DCMAKE_SYSTEM_NAME=Linux" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/vsts/work/1/s/vcpkg/scripts/toolchains/linux.cmake" "-DVCPKG_TARGET_TRIPLET=x64-linux" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=external" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=/home/vsts/work/1/s/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=/home/vsts/work/1/s/vcpkg" "-D_VCPKG_INSTALLED_DIR=/home/vsts/work/1/s/build/vcpkg_installed" "-DVCPKG_MANIFEST_INSTALL=OFF"
FAILED: ../../x64-linux-dbg/CMakeCache.txt 
"/usr/local/bin/cmake" -E chdir "../../x64-linux-dbg" "/usr/local/bin/cmake" "/home/vsts/work/1/s/vcpkg/buildtrees/prometheus-cpp/src/v1.2.4-6cdf3985a5.clean" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=/home/vsts/work/1/s/vcpkg/packages/prometheus-cpp_x64-linux/debug" "-DFETCHCONTENT_FULLY_DISCONNECTED=ON" "-DUSE_THIRDPARTY_LIBRARIES=OFF" "-DGENERATE_PKGCONFIG=OFF" "-DENABLE_COMPRESSION=ON" "-DENABLE_PULL=ON" "-DENABLE_PUSH=ON" "-DENABLE_TESTING=OFF" "-DCMAKE_MAKE_PROGRAM=/home/vsts/work/1/s/vcpkg/downloads/tools/ninja/1.10.2-linux/ninja" "-DCMAKE_SYSTEM_NAME=Linux" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/vsts/work/1/s/vcpkg/scripts/toolchains/linux.cmake" "-DVCPKG_TARGET_TRIPLET=x64-linux" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=external" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=/home/vsts/work/1/s/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=/home/vsts/work/1/s/vcpkg" "-D_VCPKG_INSTALLED_DIR=/home/vsts/work/1/s/build/vcpkg_installed" "-DVCPKG_MANIFEST_INSTALL=OFF"
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB - Success
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
CMake Error at /home/vsts/work/1/s/build/vcpkg_installed/x64-linux/share/civetweb/civetweb-config.cmake:11 (message):
  File or directory /home/vsts/work/1/s/build/vcpkg_installed/include
  referenced by variable civetweb_INCLUDE_DIR does not exist !
Call Stack (most recent call first):
  /home/vsts/work/1/s/build/vcpkg_installed/x64-linux/share/civetweb/civetweb-config.cmake:18 (set_and_check)
  /home/vsts/work/1/s/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  pull/CMakeLists.txt:11 (find_package)

-- Configuring incomplete, errors occurred!
ninja: build stopped: subcommand failed.
```
</details>

### Additional context

_No response_

**Comment by FrankXie05** [comment]
Nor repro on `x64-linux`:
```
Test@Test002:~/vcpkg$ ./vcpkg install prometheus-cpp[compression,core,pull,push]:x64-linux
Computing installation plan...
The following packages will be built and installed:
  * civetweb:x64-linux@1.16#2
  * curl[core,non-http,openssl,ssl]:x64-linux@8.7.1
  * openssl:x64-linux@3.2.1#2
    prometheus-cpp[compression,core,pull,push]:x64-linux@1.2.4
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Compiler found: /usr/bin/c++
Restored 0 package(s) from /home/Test/.cache/vcpkg/archives in 426 us. Use --debug to see more details.
Installing 1/4 civetweb:x64-linux@1.16#2...
Building civetweb:x64-linux@1.16#2...
-- Downloading https://github.com/civetweb/civetweb/archive/v1.16.tar.gz -> civetweb-civetweb-v1.16.tar.gz...
-- Extracting source /home/Test/vcpkg/downloads/civetweb-civetweb-v1.16.tar.gz
-- Applying patch disable_warnings.patch
-- Applying patch fix-fseeko.patch
-- Applying patch pkgconfig.patch
-- Using source at /home/Test/vcpkg/buildtrees/civetweb/src/v1.16-fdc4998d67.clean
-- Configuring x64-linux
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Fixing pkgconfig file: /home/Test/vcpkg/packages/civetweb_x64-linux/lib/pkgconfig/civetweb-cpp.pc
-- Fixing pkgconfig file: /home/Test/vcpkg/packages/civetweb_x64-linux/lib/pkgconfig/civetweb.pc
-- Fixing pkgconfig file: /home/Test/vcpkg/packages/civetweb_x64-linux/debug/lib/pkgconfig/civetweb-cpp.pc
-- Fixing pkgconfig file: /home/Test/vcpkg/packages/civetweb_x64-linux/debug/lib/pkgconfig/civetweb.pc
-- Installing: /home/Test/vcpkg/packages/civetweb_x64-linux/share/civetweb/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 75.2 ms.
Elapsed time to handle civetweb:x64-linux: 9 s
civetweb:x64-linux package ABI: 4772e582a559129cbaa3c9ca6b6278e8204e90c0c387f2f559dfa68aed3e58a3
Installing 2/4 openssl:x64-linux@3.2.1#2...
Building openssl:x64-linux@3.2.1#2...
-- Downloading https://github.com/openssl/openssl/archive/openssl-3.2.1.tar.gz -> openssl-openssl-openssl-3.2.1.tar.gz...
-- Extracting source /home/Test/vcpkg/downloads/openssl-openssl-openssl-3.2.1.tar.gz
-- Applying patch command-line-length.patch
-- Applying patch script-prefix.patch
-- Applying patch windows/install-layout.patch
...
...
-- Fixing pkgconfig file: /home/Test/vcpkg/packages/curl_x64-linux/lib/pkgconfig/libcurl.pc
-- Fixing pkgconfig file: /home/Test/vcpkg/packages/curl_x64-linux/debug/lib/pkgconfig/libcurl.pc
-- Installing: /home/Test/vcpkg/packages/curl_x64-linux/share/curl/vcpkg-cmake-wrapper.cmake
-- Installing: /home/Test/vcpkg/packages/curl_x64-linux/share/curl/usage
-- Performing post-build validation
Stored binaries in 1 destinations in 517 ms.
Elapsed time to handle curl:x64-linux: 16 s
curl:x64-linux package ABI: ec0224593345b4ac6e5ff93582f0bbf613ddd39fbe40ff923bc07031b5218fdc
Installing 4/4 prometheus-cpp[compression,core,pull,push]:x64-linux@1.2.4...
Building prometheus-cpp[compression,core,pull,push]:x64-linux@1.2.4...
-- Downloading https://github.com/jupp0r/prometheus-cpp/archive/v1.2.4.tar.gz -> jupp0r-prometheus-cpp-v1.2.4.tar.gz...
-- Extracting source /home/Test/vcpkg/downloads/jupp0r-prometheus-cpp-v1.2.4.tar.gz
-- Using source at /home/Test/vcpkg/buildtrees/prometheus-cpp/src/v1.2.4-6cdf3985a5.clean
-- Configuring x64-linux
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Performing post-build validation
Stored binaries in 1 destinations in 426 ms.
Elapsed time to handle prometheus-cpp:x64-linux: 6.1 s
prometheus-cpp:x64-linux package ABI: 1f474dfb556746a61828eb4ab4302b6f0ed268901150b9f6550523d764933249
Total install time: 1.3 min
prometheus-cpp provides CMake targets:

  # this is heuristically generated, and may not be correct
  find_package(prometheus-cpp CONFIG REQUIRED)
  target_link_libraries(main PRIVATE prometheus-cpp::core prometheus-cpp::pull prometheus-cpp::push prometheus-cpp::util)

Test@Test002:~/vcpkg$ cmake --version
cmake version 3.27.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by dg0yt** [comment]
Of course you cannot reproduce it with CMake 3.27.4...

**Comment by spqqky** [comment]
CMake 3.27.4 fixes the issue

**Comment by dg0yt** [comment]
Any version other than 3.29.1...
