### ISSUE TITLE
[Request] Chromium Embedded Framework (CEF)

### ISSUE THREAD

**Issue by Nemandza82** [microsoft/vcpkg#3821]
The Chromium Embedded Framework (CEF) is a simple framework for embedding Chromium-based browsers in other applications.

The address is: https://bitbucket.org/chromiumembedded/cef

It would be very helpful if CEF could be used in vcpkg.

**Comment by jolting** [comment]
Dupe of #332

**Comment by NancyLi1013** [comment]
Thanks for posting this request. Please pay attention to the progress of issue #332.
