### ISSUE TITLE
[vcpkg] VCPKG_TARGET_TRIPLET does not load toolchain file via VCPKG_CHAINLOAD_TOOLCHAIN_FILE

### ISSUE THREAD

**Issue by fabianrensen** [microsoft/vcpkg#38217]
**Describe the bug**
I have constructed a test project with a sample library, a sample executable and a sample private registry. This bug(?) is completely reproducible for me by just using the helloworld example, the official registry and the fmt port, though.

So, I am developing on linux and tried to create a custom triplet with a custom toolchain file to always use clang 18 instead of whatever is configured as the default cpp compiler on that system. 
Basically, my triplet file and the toolchain file look like those described [here](https://github.com/microsoft/vcpkg/issues/36351).

I now call cmake in the example executable project like this (it depends on gtest from the official vcpkg repository and the sample library from my private registry):
```bash
cmake -DVCPKG_TARGET_TRIPLET=linux-x64-clang-18 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=/path/to/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_OVERLAY_TRIPLETS=/path/to/SampleExecutable/cmake/triplets -S/path/to/SampleExecutable -B/path/to/SampleExecutable/cmake-build-debug-clang-18 -G Ninja
```

Here comes the output:
```
-- Running vcpkg install
Fetching registry information from https://github.com/microsoft/vcpkg (HEAD)...
Fetching registry information from https:/url/of/sampleregistry.git (HEAD)...
Detecting compiler hash for triplet x64-linux...
Compiler found: /usr/bin/g++
Detecting compiler hash for triplet linux-x64-clang-18...
Compiler found: /usr/bin/clang++-18
```
Okay, so, vcpkg is using the triplet `x64-linux` with `/usr/bin/g++` (the default) and my custom triplet `linux-x64-clang-18` with `/usr/bin/clang++-18` as defined in my toolchain file. So far, so good.
```
The following packages will be built and installed:
    gtest:linux-x64-clang-18@1.14.0 -- /path/to/.cache/vcpkg/registries/git-trees/c6dde67781b31b556e0868cc9f45f3eec59dc2a8
    samplelibrary:linux-x64-clang-18@1.0.2 -- /path/to/.cache/vcpkg/registries/git-trees/b8e729529a07c90900c5e12ecb39983b63c52d12
  * vcpkg-cmake:x64-linux@2023-05-04 -- /path/to/.cache/vcpkg/registries/git-trees/88a7058fc7fa73a9c4c99cfcae9d79e2abf87a5a
  * vcpkg-cmake-config:x64-linux@2022-02-06#1 -- /path/to/.cache/vcpkg/registries/git-trees/8d54cc4f487d51b655abec5f9c9c3f86ca83311f
```
Still fine. `gtest` and `samplelibrary` are going to be built with the custom triplet, while `vcpkg-cmake` and `vcpkg-cmake-config` use the default triplet for the host. That makes sense, since the latter two will be executed on the host and are not direct dependencies of the project. I know I can change that (and that works, too) by changing `VCPKG_HOST_TRIPLET`.

After all the dependency installation is done, I see this however:
```
-- Running vcpkg install - done
-- The C compiler identification is GNU 13.2.0
-- The CXX compiler identification is GNU 13.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build testing is enabled
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Configuring done (10.4s)
-- Generating done (0.0s)
-- Build files have been written to: /path/to/SampleExecutable/cmake-build-debug-clang-18
```
As can be seen, the project (the executable) itself, is now ignoring the target triplet and/or the clang 18 toolchain and instead uses the default compiler.
That does not make any sense to me. I now built the dependencies with a different compiler than is going to be used for my project.
I would expect the cmake file specified through `VCPKG_TARGET_TRIPLET` to also be executed for my project.
I need to explicitly set the toolchain file again via 
```
-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE="/path/to/SampleExecutable/cmake/toolchains/linux-x64-clang-18.cmake"
```
Only then cmake will actually use clang for my project.

**Environment**
- OS: Ubuntu 23.10 on two different WSL2 (Win11), Linux Mint 21.3
- Compiler: GCC 13.2 and Clang 18.1.2

**To Reproduce**
1. It is enough to create a small hellworld sample. Take the one from the documentation.
2. Make for example fmt from the official registry a dependency
3. Create a Clang toolchain file as described [here](https://github.com/microsoft/vcpkg/issues/36351)
4. Have a different default compiler
5. Set the target triplet and the overlay triplets to point to the custom triplet file.
6. Use `set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE /path/to/customToolchain.cmake)` in the triplet file
7. Configure the project

**Expected behavior**
vcpkg uses the `VCPKG_TARGET_TRIPLET` to select and use for the main project, too.

**Comment by Osyotr** [comment]
Triplet file is for building dependencies, not your project.
> I need to explicitly set the toolchain file again

This is correct way to do it right now.
(Though I admit it's not 100% user friendly).

**Comment by fabianrensen** [comment]
Okay, good to know. Thanks for your quick answer. If this is the intended behavior, this is obviously not a bug, so closing 😄

**Comment by wardw** [comment]
> This is correct way to do it right now.
> (Though I admit it's not 100% user friendly).

@Osyotr It would be great to have some documentation on this.  I also assumed the same as @fabianrensen and went through the same process of creating a sample project to find out.   Stateful problems like this can be especially fiddly to reason about correctly; there's nothing quite like having documentation that you can depend on as authoritative.

Is it not also an issue that by defining `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` in the environment for your build, this may also modify the same environment under which vcpkg builds its dependencies as part of the same process (when using manifest mode with CMake to drive both).  In which case, defining `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` can conflict with and undermine the role of the triplet given to vcpkg to build it's dependencies.  I've been trying to understand the separation between the state of the environment for building vcpkg's dependencies and the state of the environment for your own project.  My test suggested that defining `VCPKG_TARGET_TRIPLET` only affects vcpkg building its dependencies, necessitating you define `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` for your project but which then back in turn affects the environment for vcpkg's dependencies, with the possible contradiction should these not agree.   

Of course in practice I suspect these should always be the same but it wasn't clear to me what the user is expected to define.  The documentation is fairly light on the issue; it would be great to have a little info on how triplets behave in manifest mode and how this interacts with any state set for your own project's build.  Any way you can enforce this through design all the better.

**Comment by redbaron** [comment]
> My test suggested that defining VCPKG_TARGET_TRIPLET only affects vcpkg building its dependencies, necessitating you define VCPKG_CHAINLOAD_TOOLCHAIN_FILE for your project but which then back in turn affects the environment for vcpkg's dependencies, with the possible contradiction should these not agree.

Is `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` in triplet a good practice at all then? It seems to me that 

```
cmake
-DCMAKE_TOOLCHAIN_FILE=/path/to/vcpkg/scripts/buildsystems/vcpkg.cmake
-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=clang-18.cmake
```

will make both vcpkg and main project build env consistent

**Comment by Osyotr** [comment]
This is now documented in https://learn.microsoft.com/en-us/vcpkg/users/buildsystems/cmake-integration#using-multiple-toolchain-files

**Comment by redbaron** [comment]
> Want to build vcpkg deps with custom toolchain? Set `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` in your triplet. Want to build your project with custom toolchain? Set `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` and vcpkg toolchain. Want to build vcpkg deps and your project with the same toolchain? Set `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` in both places.

Just done my testing and indeed I was building vcpkg deps incorrectly. Thanks!
