### ISSUE TITLE
[libtorch:arm64-windows] build failure

### ISSUE THREAD

**Issue by ukc-work** [microsoft/vcpkg#38212]
### Operating system

windows

### Steps to reproduce the behavior

```Shell
> vcpkg install --allow-unsupported
```

### Failure logs

**console output:**
warning: sleef is only supported on '!uwp & !(arm & windows) & !(arm64 & osx)', which does not match arm64-windows. This usually means that there are known build failures, or runtime problems, when building other platforms. Proceeding anyway due to `--allow-unsupported`.
Detecting compiler hash for triplet arm64-windows...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostarm64/arm64/cl.exe
The following packages will be built and installed:
  * blas:arm64-windows@2023-03-25
  * bzip2[core,tool]:arm64-windows@1.0.8#5
  * clapack:arm64-windows@3.2.1#22
  * cpuinfo:arm64-windows@2022-07-19#3
  * eigen3:arm64-windows@3.4.0#4
  * expat:arm64-windows@2.6.2
  * flatbuffers:arm64-windows@23.5.26#1
  * fmt:arm64-windows@10.2.1#1
  * foxi:arm64-windows@2021-12-01
  * fp16:arm64-windows@2021-02-21#2
  * fxdiv:arm64-windows@2021-02-21#2
  * gemmlowp:arm64-windows@2021-09-28
  * gflags:arm64-windows@2.2.2#9
  * glog:arm64-windows@0.7.0#1
  * lapack:arm64-windows@2022-02-22#2
  * libffi:arm64-windows@3.4.6
  * liblzma:arm64-windows@5.6.0
    libtorch:arm64-windows@2.1.2#2
  * lmdb:arm64-windows@0.9.31
  * mimalloc:arm64-windows@2.1.2#2
  * onnx:arm64-windows@1.15.0#1
  * onnx-optimizer:arm64-windows@0.3.18
  * openblas:arm64-windows@0.3.26#3
  * opencl:arm64-windows@v2023.02.06#2
  * openssl:arm64-windows@3.2.1#1
  * pkgconf:arm64-windows@2.1.0
  * pocketfft:arm64-windows@2023-09-25
  * protobuf:arm64-windows@3.21.12#1
  * psimd:arm64-windows@2021-02-21#2
  * pthreadpool:arm64-windows@2020-04-10#3
  * python3:arm64-windows@3.11.8#1
  * sleef:arm64-windows@3.5.1#4
  * sqlite3[core,json1]:arm64-windows@3.45.2
  * vcpkg-cmake:arm64-windows@2023-05-04
  * vcpkg-cmake-config:arm64-windows@2022-02-06#1
  * vcpkg-cmake-get-vars:arm64-windows@2023-12-31
  * vcpkg-get-python-packages:arm64-windows@2024-01-24
  * vcpkg-msbuild:arm64-windows@2023-08-08
  * vcpkg-pkgconfig-get-modules:arm64-windows@2023-09-06
  * vcpkg-tool-meson:arm64-windows@1.3.2#1
  * zlib:arm64-windows@1.3.1
Installing 4/41 sleef:arm64-windows@3.5.1#4...
Building sleef:arm64-windows@3.5.1#4...
-- Using cached shibatch-sleef-3.5.1.tar.gz.
-- Cleaning sources at C:/wenv_/vcpkg/vcpkg/buildtrees/sleef/src/3.5.1-7f3a2e645a.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/wenv_/vcpkg/vcpkg/downloads/shibatch-sleef-3.5.1.tar.gz
-- Using source at C:/wenv_/vcpkg/vcpkg/buildtrees/sleef/src/3.5.1-7f3a2e645a.clean
-- Found external ninja('1.11.0').
-- Configuring arm64-windows
-- Building arm64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j13
    Working Directory: C:/wenv_/vcpkg/vcpkg/buildtrees/sleef/arm64-windows-dbg
    See logs for more information:
      C:\wenv_\vcpkg\vcpkg\buildtrees\sleef\install-arm64-windows-dbg-out.log

**Sleef debg-out logs :** 

[52/55] C:\windows\system32\cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_dll --intdir=src\libm\CMakeFiles\sleef.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\arm64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\arm64\mt.exe --manifests  -- C:\PROGRA~1\MICROS~1\2022\COMMUN~1\VC\Tools\MSVC\1439~1.335\bin\HOSTAR~1\arm64\link.exe  src\libm\CMakeFiles\sleefpurec_scalar.dir\sleefsimdsp.c.obj src\libm\CMakeFiles\sleefpurec_scalar.dir\sleefsimddp.c.obj src\libm\CMakeFiles\sleefdetpurec_scalar.dir\sleefsimdsp.c.obj src\libm\CMakeFiles\sleefdetpurec_scalar.dir\sleefsimddp.c.obj src\libm\CMakeFiles\sleefpurecfma_scalar.dir\sleefsimdsp.c.obj src\libm\CMakeFiles\sleefpurecfma_scalar.dir\sleefsimddp.c.obj src\libm\CMakeFiles\sleefdetpurecfma_scalar.dir\sleefsimdsp.c.obj src\libm\CMakeFiles\sleefdetpurecfma_scalar.dir\sleefsimddp.c.obj src\common\CMakeFiles\common.dir\common.c.obj src\libm\CMakeFiles\sleef.dir\sleefdp.c.obj src\libm\CMakeFiles\sleef.dir\sleefsp.c.obj src\libm\CMakeFiles\sleef.dir\rempitab.c.obj  /out:bin\sleef.dll /implib:lib\sleef.lib /pdb:bin\sleef.pdb /dll /version:3.5 /machine:ARM64 /nologo    /debug /INCREMENTAL  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
FAILED: bin/sleef.dll lib/sleef.lib 
C:\windows\system32\cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_dll --intdir=src\libm\CMakeFiles\sleef.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\arm64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\arm64\mt.exe --manifests  -- C:\PROGRA~1\MICROS~1\2022\COMMUN~1\VC\Tools\MSVC\1439~1.335\bin\HOSTAR~1\arm64\link.exe  src\libm\CMakeFiles\sleefpurec_scalar.dir\sleefsimdsp.c.obj src\libm\CMakeFiles\sleefpurec_scalar.dir\sleefsimddp.c.obj src\libm\CMakeFiles\sleefdetpurec_scalar.dir\sleefsimdsp.c.obj src\libm\CMakeFiles\sleefdetpurec_scalar.dir\sleefsimddp.c.obj src\libm\CMakeFiles\sleefpurecfma_scalar.dir\sleefsimdsp.c.obj src\libm\CMakeFiles\sleefpurecfma_scalar.dir\sleefsimddp.c.obj src\libm\CMakeFiles\sleefdetpurecfma_scalar.dir\sleefsimdsp.c.obj src\libm\CMakeFiles\sleefdetpurecfma_scalar.dir\sleefsimddp.c.obj src\common\CMakeFiles\common.dir\common.c.obj src\libm\CMakeFiles\sleef.dir\sleefdp.c.obj src\libm\CMakeFiles\sleef.dir\sleefsp.c.obj src\libm\CMakeFiles\sleef.dir\rempitab.c.obj  /out:bin\sleef.dll /implib:lib\sleef.lib /pdb:bin\sleef.pdb /dll /version:3.5 /machine:ARM64 /nologo    /debug /INCREMENTAL  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
LINK Pass 1: command "C:\PROGRA~1\MICROS~1\2022\COMMUN~1\VC\Tools\MSVC\1439~1.335\bin\HOSTAR~1\arm64\link.exe src\libm\CMakeFiles\sleefpurec_scalar.dir\sleefsimdsp.c.obj src\libm\CMakeFiles\sleefpurec_scalar.dir\sleefsimddp.c.obj src\libm\CMakeFiles\sleefdetpurec_scalar.dir\sleefsimdsp.c.obj src\libm\CMakeFiles\sleefdetpurec_scalar.dir\sleefsimddp.c.obj src\libm\CMakeFiles\sleefpurecfma_scalar.dir\sleefsimdsp.c.obj src\libm\CMakeFiles\sleefpurecfma_scalar.dir\sleefsimddp.c.obj src\libm\CMakeFiles\sleefdetpurecfma_scalar.dir\sleefsimdsp.c.obj src\libm\CMakeFiles\sleefdetpurecfma_scalar.dir\sleefsimddp.c.obj src\common\CMakeFiles\common.dir\common.c.obj src\libm\CMakeFiles\sleef.dir\sleefdp.c.obj src\libm\CMakeFiles\sleef.dir\sleefsp.c.obj src\libm\CMakeFiles\sleef.dir\rempitab.c.obj /out:bin\sleef.dll /implib:lib\sleef.lib /pdb:bin\sleef.pdb /dll /version:3.5 /machine:ARM64 /nologo /debug /INCREMENTAL kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:src\libm\CMakeFiles\sleef.dir/intermediate.manifest src\libm\CMakeFiles\sleef.dir/manifest.res" failed (exit code 1120) with the following output:
   Creating library lib\sleef.lib and object lib\sleef.exp

common.c.obj : error LNK2019: unresolved external symbol __cpuidex referenced in function Sleef_x86CpuID

bin\sleef.dll : fatal error LNK1120: 1 unresolved externals

[53/55] C:\windows\system32\cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_dll --intdir=src\quad\CMakeFiles\sleefquad.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\arm64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\arm64\mt.exe --manifests  -- C:\PROGRA~1\MICROS~1\2022\COMMUN~1\VC\Tools\MSVC\1439~1.335\bin\HOSTAR~1\arm64\link.exe  src\quad\CMakeFiles\sleefquadpurec_scalar_obj.dir\sleefsimdqp.c.obj src\quad\CMakeFiles\sleefquadpurecfma_scalar_obj.dir\sleefsimdqp.c.obj src\quad\CMakeFiles\sleefquad.dir\rempitabqp.c.obj  /out:bin\sleefquad.dll /implib:lib\sleefquad.lib /pdb:bin\sleefquad.pdb /dll /version:3.5 /machine:ARM64 /nologo    /debug /INCREMENTAL  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
ninja: build stopped: subcommand failed.

### Additional context

vcpkg.json used for package installation in manifest mode:

{

    "dependencies": [
        {
            "name": "libtorch",
            "default-features": false
        }
    ]
}

**Comment by Cheney-W** [comment]
Please report this issue to the upstream of [sleef](https://github.com/shibatch/sleef).

**Comment by Cheney-W** [comment]
>But in vcpkg packages, it shows both sleef and libtorch are available for windows-on-arm64.

No, it's not.
According to the value of supports of sleef: `!uwp & !(arm & windows) & !(arm64 & osx)`,
`!(arm & windows)` has indicated that `sleef` does not support arm-windows and arm64-windows. Since `sleef` is a dependency of `libtorch`, anything not supported by `sleef` is also not supported by `libtorch`.

**Comment by ukc-work** [comment]
Agreed. I got confused with vcpkg browsing page where it shows supported. 

<img width="818" alt="libtorch" src="https://github.com/microsoft/vcpkg/assets/167169215/be6fac1f-96d5-4420-bb7e-345dc65e6d72">

<img width="815" alt="sleef" src="https://github.com/microsoft/vcpkg/assets/167169215/d3804f28-d417-436d-abc9-8fc0237cf61a">

**Comment by fGadola** [comment]
Hi! Any updates on this? Is still not possible to do this on arm computers?
