### ISSUE TITLE
Could not find Visual Studio. VS2015 or VS2017 (with C++) needs to be installed.

### ISSUE THREAD

**Issue by waruqi** [Microsoft/vcpkg#3825]
I've installed the vs2017, but I still can't install vcpkg

```
PS F:\vcpkg> .\bootstrap-vcpkg.bat
Could not find Visual Studio. VS2015 or VS2017 (with C++) needs to be installed.
+         throw "Could not find Visual Studio. VS2015 or VS2017 (with C ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...o be installed.:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find Visual Studio. VS2015 or VS2017 (with C++) needs to be installed.
```

My Visual Studio Version:

```
Microsoft Visual Studio Community 2017
15.0.26228.9 D15RTWSVC
Microsoft .NET Framework
4.7.02558
```

**Comment by carmangary** [comment]
Do you have the C++ features installed?

**Comment by waruqi** [comment]
I have the C++ development environment and SDK installed and I can build c++ program.

**Comment by waruqi** [comment]
@degski vswhere is not installed.

> You can download the tool here and put it somewhere in your path. Then try again.

It works, Thanks!

By the way, why not read registry value `HKEY_LOCAL_MACHINE\\SOFTWARE\\Wow6432Node\\Microsoft\\VisualStudio\\SxS\\VS7;15.0\\VC` to find vs (vcallvars.bat)  or download/run vswhere.exe in bootstrap-vcpkg.bat?

**Comment by degski** [comment]
Well, great, you're welcome, not crap after all then.

**Comment by degski** [comment]
Added some stuff, this message is just to let you know that, I'll delete it later.

**Comment by waruqi** [comment]
@degski I see. 

> : it wasn't installed, because the tool was not yet created at the time of the release of that VS version, in newer versions it is included, so you should delete it again after you upgrade to a newer version of VS (which you should, but up to you).

However, this is not friendly to users who use the old version vs. Not all users are willing to upgrade vs.

**Comment by waruqi** [comment]
Another problem: [#3842](https://github.com/Microsoft/vcpkg/issues/3842)

**Comment by Himel55** [comment]
I ran into something similar today. The version of vswhere that I have is 1.0.62, which doesn't have the `-prerelease` flag and hence the install was failing.
https://github.com/Microsoft/vcpkg/blob/7c4e262e5037b0b4a49775b65b2de55ed9b7b4af/scripts/bootstrap.ps1#L75

**Comment by redbeaner** [comment]
same to mee, i fix it by change the below 👍 
$output = & $vswhereExe **-all** -products * -format xml

**Comment by eouedraogo4** [comment]
i got the same problem. i read the comments but did not understand. someone can help me?

**Comment by eouedraogo4** [comment]
i got the same problem. i read the comments but did not understand. someone can help me?

**Comment by nisarggandhewar** [comment]
while running bootstrap-vcpkg.bat i am getting following error.

Could not find MSBuild version with C++ support. VS2015, VS2017, or VS2019 (with C++) needs to be installed.

I have already install VS 2017 Community Edition. and found vswhere.exe file also.
how to resolve this error

**Comment by linquize** [comment]
@nisarggandhewar Could you run `"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -prerelease -legacy -products * -format xml`  and post the content here?

**Comment by nisarggandhewar** [comment]
Dear sir,
    I did not understand how to run this in cmd prompt.still I have run this

C:\>cd Program Files (x86)\Microsoft Visual Studio\Installer

C:\Program Files (x86)\Microsoft Visual Studio\Installer>cd vswhere.exe
The directory name is invalid.

C:\Program Files (x86)\Microsoft Visual Studio\Installer>-prerelease
-legacy -products * -format xml
'-prerelease' is not recognized as an internal or external command,
operable program or batch file.

kindly help me.

**Comment by linquize** [comment]
```
C:\>cd Program Files (x86)\Microsoft Visual Studio\Installer

C:\Program Files (x86)\Microsoft Visual Studio\Installer>vswhere.exe -prerelease -legacy -products * -format xml
```

**Comment by nisarggandhewar** [comment]
Thanks sir, Following is output that i obtain for executing above command

C:\Program Files (x86)\Microsoft Visual Studio\Installer>vswhere.exe
-prerelease -legacy -products * -format xml

<?xml version="1.0"?>
<instances>
  <instance>
    <instanceId>9c09f4a9</instanceId>
    <installDate>2020-05-10T06:21:16Z</installDate>
    <installationName>VisualStudio/15.9.22+28307.1093</installationName>
    <installationPath>C:\Program Files (x86)\Microsoft Visual
Studio\2017\Community</installationPath>
    <installationVersion>15.9.28307.1093</installationVersion>
    <productId>Microsoft.VisualStudio.Product.Community</productId>
    <productPath>C:\Program Files (x86)\Microsoft Visual
Studio\2017\Community\Common7\IDE\devenv.exe</productPath>
    <state>4294967295</state>
    <isComplete>1</isComplete>
    <isLaunchable>1</isLaunchable>
    <isPrerelease>0</isPrerelease>
    <isRebootRequired>0</isRebootRequired>
    <displayName>Visual Studio Community 2017</displayName>
    <description>Free, fully-featured IDE for students, open-source and
individual developers</description>
    <channelId>VisualStudio.15.Release</channelId>
    <channelUri>https://aka.ms/vs/15/release/channel</channelUri>
    <enginePath>C:\Program Files (x86)\Microsoft Visual
Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service</enginePath>
    <releaseNotes>https://go.microsoft.com/fwlink/?LinkId=660692#15.9.22
</releaseNotes>
    <thirdPartyNotices>https://go.microsoft.com/fwlink/?LinkId=660708
</thirdPartyNotices>
    <updateDate>2020-05-10T06:21:16.9847371Z</updateDate>
    <catalog>
      <buildBranch>d15.9</buildBranch>
      <buildVersion>15.9.28307.1093</buildVersion>
      <id>VisualStudio/15.9.22+28307.1093</id>
      <localBuild>build-lab</localBuild>
      <manifestName>VisualStudio</manifestName>
      <manifestType>installer</manifestType>
      <productDisplayVersion>15.9.22</productDisplayVersion>
      <productLine>Dev15</productLine>
      <productLineVersion>2017</productLineVersion>
      <productMilestone>RTW</productMilestone>
      <productMilestoneIsPreRelease>False</productMilestoneIsPreRelease>
      <productName>Visual Studio</productName>
      <productPatchVersion>22</productPatchVersion>

<productPreReleaseMilestoneSuffix>1.0</productPreReleaseMilestoneSuffix>
      <productRelease>RTW</productRelease>
      <productSemanticVersion>15.9.22+28307.1093</productSemanticVersion>
      <requiredEngineVersion>1.18.1059.4691</requiredEngineVersion>
    </catalog>
    <properties>
      <campaignId>1165781126.1588502346</campaignId>

<channelManifestId>VisualStudio.15.Release/15.9.22+28307.1093</channelManifestId>
      <nickname></nickname>
      <setupEngineFilePath>C:\Program Files (x86)\Microsoft Visual
Studio\Installer\vs_installershell.exe</setupEngineFilePath>
    </properties>
  </instance>
  <instance>
    <instanceId>a0080b06</instanceId>
    <installDate>2020-05-03T11:00:27Z</installDate>
    <installationName>VisualStudio/16.5.4+30011.22</installationName>
    <installationPath>C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community</installationPath>
    <installationVersion>16.5.30011.22</installationVersion>
    <productId>Microsoft.VisualStudio.Product.Community</productId>
    <productPath>C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\Common7\IDE\devenv.exe</productPath>
    <state>4294967295</state>
    <isComplete>1</isComplete>
    <isLaunchable>1</isLaunchable>
    <isPrerelease>0</isPrerelease>
    <isRebootRequired>0</isRebootRequired>
    <displayName>Visual Studio Community 2019</displayName>
    <description>Powerful IDE, free for students, open-source contributors,
and individuals</description>
    <channelId>VisualStudio.16.Release</channelId>
    <channelUri>https://aka.ms/vs/16/release/channel</channelUri>
    <enginePath>C:\Program Files (x86)\Microsoft Visual
Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service</enginePath>
    <releaseNotes>https://go.microsoft.com/fwlink/?LinkId=660893#16.5.4
</releaseNotes>
    <thirdPartyNotices>https://go.microsoft.com/fwlink/?LinkId=660909
</thirdPartyNotices>
    <updateDate>2020-05-03T11:00:27.1069499Z</updateDate>
    <catalog>
      <buildBranch>d16.5</buildBranch>
      <buildVersion>16.5.30011.22</buildVersion>
      <id>VisualStudio/16.5.4+30011.22</id>
      <localBuild>build-lab</localBuild>
      <manifestName>VisualStudio</manifestName>
      <manifestType>installer</manifestType>
      <productDisplayVersion>16.5.4</productDisplayVersion>
      <productLine>Dev16</productLine>
      <productLineVersion>2019</productLineVersion>
      <productMilestone>RTW</productMilestone>
      <productMilestoneIsPreRelease>False</productMilestoneIsPreRelease>
      <productName>Visual Studio</productName>
      <productPatchVersion>4</productPatchVersion>

<productPreReleaseMilestoneSuffix>1.0</productPreReleaseMilestoneSuffix>
      <productSemanticVersion>16.5.4+30011.22</productSemanticVersion>
      <requiredEngineVersion>2.5.2141.57745</requiredEngineVersion>
    </catalog>
    <properties>
      <campaignId>1165781126.1588502346</campaignId>
      <canceled>0</canceled>

<channelManifestId>VisualStudio.16.Release/16.5.4+30011.22</channelManifestId>
      <nickname></nickname>
      <setupEngineFilePath>C:\Program Files (x86)\Microsoft Visual
Studio\Installer\vs_installershell.exe</setupEngineFilePath>
    </properties>
  </instance>
</instances>

kindly guide me

**Comment by nisarggandhewar** [comment]
Dear sir,
    Kindly reply. How can I recover from this error.

**Comment by nisarggandhewar** [comment]
Dear sir,
     Is their any solution to above problem.
Kindly reply.

**Comment by linquize** [comment]
Did you install C++ features from Visual Studio Installer?

**Comment by Taylor-Philip** [comment]
I think that a part of the problem may be, that under Windows 7 64-bit Enterprise at least, one cannot " install C++ features from Visual Studio Installer".  It is necessary to first "" install the Visual Studio [2019 Enterprise] Installer" and then modify its configuration to support C++ (and any others features that do not come supported out of the box).

Philip Taylor
