### ISSUE TITLE
[openssl] Build error

### ISSUE THREAD

**Issue by cheboxarov** [microsoft/vcpkg#38256]
wlvm@minint-p8ur1vk:~/Documents/vcpkg$  vcpkg install openssl
Computing installation plan...
The following packages will be built and installed:
    openssl:x64-linux -> 3.3.0
Detecting compiler hash for triplet x64-linux...
Restored 0 package(s) from /home/wlvm/.cache/vcpkg/archives in 64.2 us. Use --debug to see more details.
Installing 1/1 openssl:x64-linux...
Building openssl:x64-linux...
-- Using cached openssl-openssl-openssl-3.3.0.tar.gz.
-- Cleaning sources at /home/wlvm/Documents/vcpkg/buildtrees/openssl/src/nssl-3.3.0-961d78b8a1.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/wlvm/Documents/vcpkg/downloads/openssl-openssl-openssl-3.3.0.tar.gz
-- Applying patch cmake-config.patch
-- Applying patch command-line-length.patch
-- Applying patch script-prefix.patch
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch unix/android-cc.patch
-- Applying patch unix/move-openssldir.patch
-- Applying patch unix/no-empty-dirs.patch
-- Applying patch unix/no-static-libs-for-shared.patch
-- Using source at /home/wlvm/Documents/vcpkg/buildtrees/openssl/src/nssl-3.3.0-961d78b8a1.clean
openssl requires Linux kernel headers from the system package manager.
   They can be installed on Alpine systems via `apk add linux-headers`.
   They can be installed on Ubuntu systems via `apt install linux-libc-dev`.

-- Found external ninja('1.11.1').
-- Getting CMake variables for x64-linux
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/bash -c "V=1 ./../src/nssl-3.3.0-961d78b8a1.clean/vcpkg/configure  \"/usr/bin/perl\" \"/home/wlvm/Documents/vcpkg/buildtrees/openssl/src/nssl-3.3.0-961d78b8a1.clean/Configure\" \"linux-x86_64\" \"enable-static-engine\" \"enable-capieng\" \"no-tests\" \"no-docs\" \"no-shared\" \"no-module\" \"no-apps\" \"--openssldir=/etc/ssl\" \"--libdir=lib\" \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"--debug\" \"--prefix=/home/wlvm/Documents/vcpkg/installed/x64-linux/debug\""
    Working Directory: /home/wlvm/Documents/vcpkg/buildtrees/openssl/x64-linux-dbg
    Error code: 2
    See logs for more information:
      /home/wlvm/Documents/vcpkg/buildtrees/openssl/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:863 (vcpkg_execute_required_process)
  ports/openssl/unix/portfile.cmake:106 (vcpkg_configure_make)
  ports/openssl/portfile.cmake:79 (include)
  scripts/ports.cmake:175 (include)

error: building openssl:x64-linux failed with: BUILD_FAILED
Elapsed time to handle openssl:x64-linux: 1.5 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.

On Fedora Linux

**Comment by StarGate-One** [comment]
See #30604 How to report a package build failure.

FWIW - try installing and/or verify the installation of the required system libraries:
>-- Using source at /home/wlvm/Documents/vcpkg/buildtrees/openssl/src/nssl-3.3.0-961d78b8a1.clean
openssl requires Linux kernel headers from the system package manager.
They can be installed on Alpine systems via apk add linux-headers.
They can be installed on Ubuntu systems via apt install linux-libc-dev.

**Comment by WangWeiLin-MV** [comment]
See #30604 on how to properly report an issue.
