### ISSUE TITLE
[ACE] Support CMake-based usage

### ISSUE THREAD

**Issue by martingalvan-volue** [microsoft/vcpkg#38251]
### Is your feature request related to a problem? Please describe.

Currently, ACE does not provide facilities for importing it to CMake-based project with e.g. `find_package`. This should be fixed.

### Proposed solution

Add the required machinery to do so, as well as a usage file documenting how to import the library.

**Comment by jwillemsen** [comment]
ACE doesn't provide at this moment support for cmake build/use. Some projects that use ACE have added some find support to their code, but ACE itself doesn't use cmake, we use MPC to build ACE and all its tests.

**Comment by jwillemsen** [comment]
Building ACE itself with cmake is not planned, it will make maintenance more complex (multiple build systems to maintain). 

There is an upstream issue https://github.com/DOCGroup/ACE_TAO/issues/266, maybe helpful, there are some references there for findACE/TAO modules people created, seems nobody spended time to integrate those into ACE/TAO itself.

**Comment by jwillemsen** [comment]
Feel free to contribute one ;-)

**Comment by jwillemsen** [comment]
When you think it is necessary and you don't want to do the work yourself, see https://github.com/DOCGroup/ACE_TAO/wiki/ACE-and-TAO-Commercial-support for the support providers for ACE who could assist with this.

**Comment by dg0yt** [comment]
The key isn't the `usage` file, but installing a good CMake config package.

**Comment by jwillemsen** [comment]
If it easy to create why not contribute it yourself @martingalvan-volue?

**Comment by jwillemsen** [comment]
Be aware that ACE isn't actively maintained and tested anymore with Visual Studio in general, due to lack of sponsoring. There are some github CI actions to compile the core with some versions, but nobody runs daily builds/tests of the full stack anymore.

**Comment by dg0yt** [comment]
> They are both needed, but a usage file would be simpler to create.

No. No.
For simpe config packages, a usage file is not needed. Vcpkg tool uses heuristics.
Without cmake config or find module, the usage file will need just the cmake code which would go to the cmake file...

**Comment by Osyotr** [comment]
Didn't this package install pkg-config files? You can use them from cmake.

**Comment by dg0yt** [comment]
> Didn't this package install pkg-config files? You can use them from cmake.

Not for windows, according to CI file lists.
If it did, vcpkg tool would report that. (Usage heuristics.)

**Comment by jimwang118** [comment]
ACE upstream does not provide a method to export cmake, so vcpkg does not support cmake calling ACE for now. If ACE upstream updates cmake export later, we will update it in time.
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
