### ISSUE TITLE
[gdk-pixbuf] can't build without tiff, libjpeg and libpng as expected

### ISSUE THREAD

**Issue by a3emdot** [microsoft/vcpkg#38270]
### Is your feature request related to a problem? Please describe.

I'm trying to install 'gdk-pixbuf' without depending on the 'tiff' library (and/or without 'libjpeg' and 'libpng')

This should work on a recent Fedora Linux AND on Windows.
It should also be possible for 'gdk-pixbuf' to be built without 'libjpeg' and 'libpng'.

See also
https://github.com/microsoft/vcpkg/pull/38033

The following two variants were run on a recently updated Fedora 38 Linux,
directly in an empty directory after a git clone of the vcpkg project and the vcpkg-bootstrap.sh run.

Variant 1 (Fedora 38 run). The following installs 'tiff' as a component
```
[user@fedora vcpkg]$ ./vcpkg --disable-metrics install gdk-pixbuf[jpeg,png]
Computing installation plan...
A suitable version of cmake was not found (required v3.29.0) Downloading portable cmake 3.29.0...
Downloading cmake...
https://github.com/Kitware/CMake/releases/download/v3.29.0/cmake-3.29.0-linux-x86_64.tar.gz->/home/mauteand/tmp-vcpkg/vcpkg/vcpkg/downloads/cmake-3.29.0-linux-x86_64.tar.gz
Extracting cmake...
The following packages will be built and installed:
  * dirent:x64-linux@1.24
    gdk-pixbuf[core,jpeg,png,tiff]:x64-linux@2.42.10#4
  * gettext:x64-linux@0.22.5
  * gettext-libintl:x64-linux@0.22.5
  * glib:x64-linux@2.78.4#1
  * libffi:x64-linux@3.4.6
  * libiconv:x64-linux@1.17#3
  * libjpeg-turbo:x64-linux@3.0.2
  * liblzma:x64-linux@5.4.4
  * libpng:x64-linux@1.6.43
  * pcre2[core,jit,platform-default-features]:x64-linux@10.42#3
  * tiff[core,jpeg,lzma,zip]:x64-linux@4.6.0#4
  * vcpkg-cmake:x64-linux@2023-05-04
  * vcpkg-cmake-config:x64-linux@2022-02-06#1
  * vcpkg-cmake-get-vars:x64-linux@2023-12-31
  * vcpkg-tool-meson:x64-linux@1.3.2#2
  * zlib:x64-linux@1.3.1
```

Variant 2 (Fedora 38). This one also installs 'tiff' as a component, though the 'gdk-pixbuf' line doesn't mention it.
```
[user@fedora vcpkg]$ ./vcpkg --disable-metrics install gdk-pixbuf[core,jpeg,png]
Computing installation plan...
A suitable version of cmake was not found (required v3.29.0) Downloading portable cmake 3.29.0...
Downloading cmake...
https://github.com/Kitware/CMake/releases/download/v3.29.0/cmake-3.29.0-linux-x86_64.tar.gz->/home/mauteand/tmp-vcpkg/vcpkg/vcpkg/downloads/cmake-3.29.0-linux-x86_64.tar.gz
Extracting cmake...
The following packages will be built and installed:
  * dirent:x64-linux@1.24
    gdk-pixbuf[core,jpeg,png]:x64-linux@2.42.10#4
  * gettext:x64-linux@0.22.5
  * gettext-libintl:x64-linux@0.22.5
  * glib:x64-linux@2.78.4#1
  * libffi:x64-linux@3.4.6
  * libiconv:x64-linux@1.17#3
  * libjpeg-turbo:x64-linux@3.0.2
  * liblzma:x64-linux@5.4.4
  * libpng:x64-linux@1.6.43
  * pcre2[core,jit,platform-default-features]:x64-linux@10.42#3
  * tiff[core,jpeg,lzma,zip]:x64-linux@4.6.0#4
  * vcpkg-cmake:x64-linux@2023-05-04
  * vcpkg-cmake-config:x64-linux@2022-02-06#1
  * vcpkg-cmake-get-vars:x64-linux@2023-12-31
  * vcpkg-tool-meson:x64-linux@1.3.2#2
  * zlib:x64-linux@1.3.1
```

### Proposed solution

change the port so that it supports a 'gdk-pixbuf' built without these dependencies

**Comment by dg0yt** [comment]
Try #38272.

**Comment by a3emdot** [comment]
@dg0yt 
I did some clean builds but only on my Fedora 38 Linux.

I checked the following variants with your change:
```
./vcpkg install 'gdk-pixbuf'
./vcpkg install 'gdk-pixbuf[jpeg]'
./vcpkg install 'gdk-pixbuf[tiff]'
./vcpkg install 'gdk-pixbuf[jpeg,tiff]'
./vcpkg install 'gdk-pixbuf[png]'
./vcpkg install 'gdk-pixbuf[png,jpeg]'
./vcpkg install 'gdk-pixbuf[png,tiff]'
./vcpkg install 'gdk-pixbuf[png,jpeg,tiff]'

./vcpkg install 'gdk-pixbuf[core]'
./vcpkg install 'gdk-pixbuf[core,jpeg]'
./vcpkg install 'gdk-pixbuf[core,tiff]' (*)
./vcpkg install 'gdk-pixbuf[core,jpeg,tiff]'
./vcpkg install 'gdk-pixbuf[core,png]'
./vcpkg install 'gdk-pixbuf[core,png,jpeg]'
./vcpkg install 'gdk-pixbuf[core,png,tiff]' (*)
./vcpkg install 'gdk-pixbuf[core,png,jpeg,tiff]'
```
The two variants marked with an asterisk will still install 'libjpeg'
```
./vcpkg install 'gdk-pixbuf[core,tiff]' (*)
./vcpkg install 'gdk-pixbuf[core,png,tiff]' (*)
```
Is this intended? It should be possible to disable 'jpeg' when building with 'tiff'
This is suggested when checking the 'libtiff' upstream configure script.

I wonder if the only solution for these cases is to add an additional 'tiff[core]' to the 'gdk-pixbuf' install commands, which indeed works.

FYI. I didn't check the 'windows' builds

- ae3mdot

P.S.
The 'only' viable option  for the comment button below is 'close with comment' ??

**Comment by dg0yt** [comment]
> The two variants marked with an asterisk will still install 'libjpeg'
> 
> ```
> ./vcpkg install 'gdk-pixbuf[core,tiff]' (*)
> ./vcpkg install 'gdk-pixbuf[core,png,tiff]' (*)
> ```
> Is this intended? It should be possible to disable 'jpeg' when building with 'tiff'

Yes. You only ask for gdk-pixbuf without direct jpeg capabilities, and you get it.

However, `tiff` has a `[jpeg]` feature which is on by default. To disable the use of JPEG compression inside TIFF files, you would need to use:

~~~
./vcpkg install 'gdk-pixbuf[core,tiff]' 'tiff[core,<your-desired-features>]'
./vcpkg install 'gdk-pixbuf[core,png,tiff]' 'tiff[core,<your-desired-features>]'
~~~

> This is suggested when checking the 'libtiff' upstream configure script.

There is not much relevance in the upstream configure script. We build with CMake. 
https://gitlab.com/libtiff/libtiff/-/blob/master/cmake/JPEGCodec.cmake?ref_type=heads

And libtiff without jpeg would be quite incomplete.  There is some "old" JPEG support which is off by default in both buildsystems IIUC.
