### ISSUE TITLE
[GLM] Currently not building as a static library

### ISSUE THREAD

**Issue by crgnam** [microsoft/vcpkg#38277]
### Is your feature request related to a problem? Please describe.

The GLM library can be built as a static library by setting `GLM_BUILD_LIBRARY`, however it does not appear to be an option when using vcpkg.  On windows, the `portfile.cmake` file shows:

```
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DGLM_BUILD_LIBRARY=ON
        -DGLM_BUILD_TESTS=OFF
        -DGLM_BUILD_INSTALL=ON
)
```
implying this should be possible (and in-fact, the default behavior) however even manually setting this with `set(VCPKG_CMAKE_CONFIGURE_OPTIONS -DGLM_BUILD_LIBRARY:BOOL=ON)` has no effect, and no `glm.lib` is built.

On Linux, the `portfile.cmake`  does not include any indication of these options, instead only saying:

```
`set(VCPKG_BUILD_TYPE release) # header-only port`
```

implying that glm is only available as a header-only port.

### Proposed solution

I am not sure how this would be fixed, but the ultimate outcome should allow GLM to be built as a library, yielding a `glm.lib` on Windows, or a `libglm.a` on Linux.  (I do not have access to a Mac, but the same should be true there as well)

### Describe alternatives you've considered

Personally, I am considering just keeping a copy of the `glm` source code in my project, and having it be built as a subproject (as this works without issue)

**Comment by Osyotr** [comment]
You are using old version of glm. The current version does produce .lib/.a files on all platforms.
