### ISSUE TITLE
building qtwebengine:x64-windows failed

### ISSUE THREAD

**Issue by mazalet** [microsoft/vcpkg#38278]
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/15046126/install-x64-windows-dbg-out.log)

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vcpkg/issues/36321
```

**Comment by JonLiu1993** [comment]
Duplicate of https://github.com/microsoft/vcpkg/issues/34971.
