### ISSUE TITLE
Error: Building package vtk:x64-linux failed with: POST_BUILD_CHECKS_FAILED

### ISSUE THREAD

**Issue by Goldesel23** [Microsoft/vcpkg#3828]
Hi, I was testing installing VTK on my machine and got this error. I tried to check the logs, but I found nothing useful. I tried in two different machines but the error was the same on both machines (with different linux distros). 

Here are the output messages: 

`The following packages will be built and installed:
    vtk[core]:x64-linux
Starting package 1/1: vtk:x64-linux
Building package vtk[core]:x64-linux... 
-- Using cached /home/tf/Libraries/vcpkg/downloads/Kitware-VTK-v8.1.0.tar.gz
-- Using source at /home/tf/Libraries/vcpkg/buildtrees/vtk/src/v8.1.0-438bd232dc
-- Applying patch /home/tf/Libraries/vcpkg/ports/vtk/dont-define-ssize_t.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch /home/tf/Libraries/vcpkg/ports/vtk/use-fixed-find-hdf5.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch /home/tf/Libraries/vcpkg/ports/vtk/disable-workaround-findhdf5.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch /home/tf/Libraries/vcpkg/ports/vtk/fix-find-libproj4.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch /home/tf/Libraries/vcpkg/ports/vtk/fix-find-libharu.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch /home/tf/Libraries/vcpkg/ports/vtk/fix-find-mysql.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch /home/tf/Libraries/vcpkg/ports/vtk/fix-find-odbc.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Performing post-build validation
There should be no empty directories in /home/tf/Libraries/vcpkg/packages/vtk_x64-linux
The following empty directories were found: 

    /home/tf/Libraries/vcpkg/packages/vtk_x64-linux/tools/vtk

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/a/dir ${CURRENT_PACKAGES_DIR}/some/other/dir)

Found 1 error(s). Please correct the portfile:
    /home/tf/Libraries/vcpkg/ports/vtk/portfile.cmake
-- Performing post-build validation done
Error: Building package vtk:x64-linux failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: vtk:x64-linux
  Vcpkg version: 0.0.113-unknownhash

Additionally, attach any relevant sections from the log files above.`

Is there a fix for this problem?

**Comment by Goldesel23** [comment]
In some of the logs I found some relevant info's:

patch-x64-linux-6-err.log:

```
Checking patch CMake/FindODBC.cmake...
error: while searching for:
)

FIND_LIBRARY( ODBC_LIBRARY
  NAMES odbc iodbc unixodbc
  PATHS
  /usr/lib
  /usr/lib/odbc

error: patch failed: CMake/FindODBC.cmake:30
error: CMake/FindODBC.cmake: patch does not apply
```
patch-x64-linux-5-err.log:

```
Checking patch CMake/FindMySQL.cmake...
error: while searching for:
  "C:/MySQL/include"
  "[HKEY_LOCAL_MACHINE\\SOFTWARE\\MySQL AB\\MySQL Server 5.0;Location]/include"
  "[HKEY_LOCAL_MACHINE\\SOFTWARE\\Wow6432Node\\MySQL AB\\MySQL Server 5.0;Location]/include"
  DOC "Specify the directory containing mysql.h."
)


error: patch failed: CMake/FindMySQL.cmake:28
error: CMake/FindMySQL.cmake: patch does not apply
```
patch-x64-linux-4-err.log:

```
Checking patch CMake/FindLibHaru.cmake...
error: while searching for:

find_path(LIBHARU_INCLUDE_DIR hpdf.h)

find_library(LIBHARU_LIBRARY NAMES hpdf hpdfs)

# handle the QUIETLY and REQUIRED arguments and set FONTCONFIG_FOUND to TRUE if
# all listed variables are TRUE
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(LibHaru DEFAULT_MSG

error: patch failed: CMake/FindLibHaru.cmake:19
error: CMake/FindLibHaru.cmake: patch does not apply
```

patch-x64-linux-3-err.log:

```
Checking patch CMake/FindLIBPROJ4.cmake...
error: while searching for:
    file( TO_CMAKE_PATH "$ENV{LIBPROJ4_DIR}" _LIBPROJ4_DIR )
  endif ()

  find_library( LIBPROJ4_LIBRARIES
    NAMES proj
    PATHS
      ${_LIBPROJ4_DIR}/lib64

error: patch failed: CMake/FindLIBPROJ4.cmake:11
error: CMake/FindLIBPROJ4.cmake: patch does not apply

```
patch-x64-linux-2-err.log

```
Checking patch CMake/vtkModuleMacros.cmake...
error: while searching for:
      set(vtk${_lower}_LIBRARIES "${${_upper_pkg_name}_LIBRARIES}")
    endif()

    #a workaround for bad FindHDF5 behavior in which deb or opt can
    #end up empty. cmake >= 2.8.12.2 makes this unnecessary
    string(REGEX MATCH "debug;.*optimized;.*"
           _remove_deb_opt "${vtk${_lower}_LIBRARIES}")
    if (_remove_deb_opt)
      set(_tmp ${vtk${_lower}_LIBRARIES})
      list(REMOVE_ITEM _tmp "debug")
      list(REMOVE_ITEM _tmp "optimized")
      list(REMOVE_DUPLICATES _tmp)
      set(vtk${_lower}_LIBRARIES ${_tmp})
    endif()

    set(vtk${_lower}_INCLUDE_DIRS "")
  else()
    if(_nolibs)

error: patch failed: CMake/vtkModuleMacros.cmake:893
error: CMake/vtkModuleMacros.cmake: patch does not apply

```

patch-x64-linux-1-err.log

```
Checking patch CMake/FindHDF5.cmake...
error: while searching for:
# (BUG #0014363).

# include the default FindHDF5.cmake.
if(CMAKE_VERSION VERSION_LESS 3.6.1)
  include(${CMAKE_CURRENT_LIST_DIR}/NewCMake/FindHDF5.cmake)
else()
  include(${CMAKE_ROOT}/Modules/FindHDF5.cmake)
endif()

if(HDF5_FOUND AND (HDF5_IS_PARALLEL OR HDF5_ENABLE_PARALLEL))
  include(vtkMPI)

error: patch failed: CMake/FindHDF5.cmake:3
error: CMake/FindHDF5.cmake: patch does not apply

```

patch-x64-linux-0-err.log

```
Checking patch ThirdParty/netcdf/vtknetcdf/ncconfig.h.in...
error: while searching for:
#cmakedefine HAVE_LIBHDF5_HL

/* Define to `int' if system doesn't define.  */
#cmakedefine ssize_t @ssize_t@

/* Define to `int' if system doesn't define.  */
#cmakedefine ptrdiff_t @ptrdiff_t@

error: patch failed: ThirdParty/netcdf/vtknetcdf/ncconfig.h.in:110
error: ThirdParty/netcdf/vtknetcdf/ncconfig.h.in: patch does not apply

```

**Comment by PhoebeHui** [comment]
@Goldesel23, thank you for posting this issue, please try to install vtk by vcpkg latest revision, and please open a new issue if this is still a problem for you.

VTK installed successsfully:
...
Building package vtk[core]:x64-linux... done
Installing package vtk[core]:x64-linux...
Installing package vtk[core]:x64-linux... done
Elapsed time for package vtk:x64-linux: 18.87 min

Total elapsed time: 25.09 min

The package vtk:x64-linux provides CMake targets:
    find_package(VTK CONFIG REQUIRED)
    # Note: 108 target(s) were omitted.
    target_link_libraries(main PRIVATE foo vtksys ${name} ${name})
