### ISSUE TITLE
Unresolved external symbol errors

### ISSUE THREAD

**Issue by XECTRA-RAW** [microsoft/vcpkg#38290]
I tried to install x64 of boost and OpenSSL they have build the files but the build tool version of the lib files seem to be v140 I'm not sure if that's what is causing my errors but doesn't seem to make all the lib files in boost-filesystem unsure if other have built okay or not!

**Comment by WangWeiLin-MV** [comment]
All `vc14*` for port `boost` lib build will be uniformly changed to `vc140`. Currently, other downstream dependencies use `boost` normally. So this problem may be due to other reasons. Could you provide logs to help debug the issue?

**Comment by XECTRA-RAW** [comment]
So i change the project to debug and it built but the release version doesn't build at all!

**Comment by WangWeiLin-MV** [comment]
@XECTRA-RAW Could you please provide the build logs for debug? See #30604 on how to append logs.
