### ISSUE TITLE
Linking to arrow in a static x64-windows-static-md build incorrectly links ws2_32.dll.lib

### ISSUE THREAD

**Issue by robambalu** [microsoft/vcpkg#38305]
**Describe the bug**
I'm trying to build my vcpkg as fully static ( less runtime libs, so x64-windows-static-md ).
Everything builds / links fine except one part of my project that links against arrow.  When linking Arrow I hit this error:
`LINK : fatal error LNK1181: cannot open input file 'ws2_32.dll.lib' [C:\Users\robam\csp\_skbuild\win-amd64-3.11\cmake-build\cpp\csp\python\adapters\parquetadapterimpl.vcxproj]`

Which looks odd on its face ( ".dll.lib" ? ).
When I looked a bit further I found this in the arrow cmake ( under vcpkg_installed\x64-windows-static-md\share\arrow\ArrowTargets.cmake:64 ):
`INTERFACE_LINK_LIBRARIES "OpenSSL::Crypto;OpenSSL::SSL;unofficial::brotli::brotlienc;unofficial::brotli::brotlidec;unofficial::brotli::brotlicommon;BZip2::BZip2;lz4::lz4;Snappy::snappy-static;ZLIB::ZLIB;zstd::libzstd_static;Threads::Threads;**ws2_32.dll**"`

Sure enough if I remove the .dll my build works fine.
I'm not sure if I'm doing something wrong or if that is some typo in the arrow cmake file ( forgive any ignorance on my part, its my first time using vcpkg )

**Environment**
- OS: Windows
- Compiler: MSVC 2019
- - Triplet: x64-windows-static-md

**To Reproduce**
Dont have an easy repro as my project is somewhat large, but if "ws2_32.dll" looks like its correct in that cmake file I can try to put one together.

**Expected behavior**
Since this is a static -md build I dont think ws2_32 should be placed with a .dll extension there )

**Comment by dg0yt** [comment]
Probably an upstream issue, cf. https://github.com/microsoft/vcpkg/pull/38295#issuecomment-2068498113

**Comment by robambalu** [comment]
I'm a bit new to vcpkg, but if I'm reading the change correctly it looks like it would only apply to arrow version 16.0, is that right?  Would it be possible to apply to 15.0.0 as well?

**Comment by dg0yt** [comment]
> Would it be possible to apply to 15.0.0 as well?

Not in the vcpkg registry.
You may do that in a local overlay port based on the old revision.

**Comment by robambalu** [comment]
Thanks, this is all still a bit unclear to me as I said I'm rather new to vcpkg.
I'm not sure what port-versions are exactly and why 16.0.0 port-version 1 has the fix, 0 does not ( and 15.0.2 port-version 1 does not have the fix either )
Can you point my in the right direction on how to apply the patch for 15.0.0 using a local overlay?

**Comment by robambalu** [comment]
The main thing I think I dont understand is why the patch isnt getting applied.  If I see that the arrow/portfile.cmake that I have checked out has the new patch listed in the patch list, why isnt it getting applied ( what is controlling this so that only 16.0.0 version 1 is getting the patch applied )

**Comment by dg0yt** [comment]
Please open a proper new issue.
