### ISSUE TITLE
[<port name>] instal failure  

### ISSUE THREAD

**Issue by Vincent11499** [microsoft/vcpkg#38314]
### Operating system

windows

### Steps to reproduce the behavior

```Shell
vcpkg install  vtk[qt]:x64-windows
```

### Failure logs

Computing installation plan...
error: while looking for qtbase:x64-windows:
error: while loading C:\src\vcpkg\ports\qtbase\vcpkg.json:
$.default-features[11]: mismatched type: expected an identifier
$.default-features[12]: mismatched type: expected an identifier
$.default-features[15]: mismatched type: expected an identifier
![20240422162455](https://github.com/microsoft/vcpkg/assets/42113343/45d368ef-6a9d-446d-aefa-9194e5d6cbd6)

### Additional context

I have installed qt5-base:x64-windows.

**Comment by talregev** [comment]
You can try this PR:
https://github.com/microsoft/vcpkg/pull/37731

**Comment by LilyWangLL** [comment]
This error is due to your vcpkg is old, please run command `git pull` and `.\bootstrap-vcpkg.bat` to update your local vcpkg. And you can also run command `.\vcpkg upgrade --no-dry-run` to update the installed packages.

**Comment by Vincent11499** [comment]
翻译为英文：非常感谢，更新后，已不再出现该错误
