### ISSUE TITLE
[physx] I can not link physx:x64-windows to my porject

### ISSUE THREAD

**Issue by ChivenZhang** [microsoft/vcpkg#38338]
**Describe the bug**
I can not link physx:x64-windows to my porject.

**Environment**
- OS: Windows 11
- Compiler: msvc 2019

**To Reproduce**
1. install physx:x64-windows using vcpkg
2. link 15 libs into project
3. compile failed as lnk2019 error

**Expected behavior**
link pass

**Failure logs**
![image](https://github.com/microsoft/vcpkg/assets/48938612/0480a96a-fcb5-4582-829a-6d33b42a19c9)

**Additional context**
Please see https://github.com/NVIDIA-Omniverse/PhysX/issues/275

**Comment by FrankXie05** [comment]
@ChivenZhang Thanks for posting this issue, could you please provide a simple camke reproduction project?

**Comment by ChivenZhang** [comment]
> @ChivenZhang Thanks for posting this issue, could you please provide a simple camke reproduction project?

Of course.
[TestPhysx.zip](https://github.com/microsoft/vcpkg/files/15071556/TestPhysx.zip)

**Comment by FrankXie05** [comment]
@ChivenZhang 
Thanks for the file, we recommend you use the method provided by vcpkg:
```
[Sample port usage]
physx provides CMake targets:

    cmake_minimum_required(VERSION 3.15)

    find_package(unofficial-omniverse-physx-sdk CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::omniverse-physx-sdk::sdk)
    ...
    ...
``` 

It is not recommended to manually link all header files and library. Just add this and only need to include the header file in `main.cpp`:
CMakeLists.txt:
```
...
add_executable(MyExecutable main.cpp)
find_package(unofficial-omniverse-physx-sdk CONFIG REQUIRED)

target_link_libraries(MyExecutable PRIVATE unofficial::omniverse-physx-sdk::sdk)
```

**Comment by ChivenZhang** [comment]
I have never use vcpkg for deferent ports building. Could you please give me some hint？Thanks very much. I do not know how to produce "unofficial::omniverse-physx-sdk::sdk" library.

**Comment by FrankXie05** [comment]
@ChivenZhang Just run command and pass `CMAKE_TOOLCHAIN_FILE` the  to your cmake project:
```
PS: git clone https://github.com/microsoft/vcpkg
PS: cd .\vcpkg\
PS: .\bootstrap-vcpkg.bat
PS: ./vcpkg install physx:x64-windows
PS: ./vcpkg integrate install
Applied user-wide integration for this vcpkg root.
CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=F:/vcpkg/scripts/buildsystems/vcpkg.cmake"

All MSBuild C++ projects can now #include any installed libraries. Linking will be handled automatically. Installing new libraries will make them instantly available.
```
https://github.com/microsoft/vcpkg?tab=readme-ov-file#getting-started

**Comment by ChivenZhang** [comment]
![image](https://github.com/microsoft/vcpkg/assets/48938612/822b058b-09db-4648-90a5-46a8cb3d76bc)
@FrankXie05 Thanks so much again. You have helped me lot. I have no problem now, thanks.

**Comment by ChivenZhang** [comment]
![image](https://github.com/microsoft/vcpkg/assets/48938612/822b058b-09db-4648-90a5-46a8cb3d76bc)
@FrankXie05 Thanks so much again. You have helped me lot. I have no problem now, thanks.
