### ISSUE TITLE
[luafilesystem] [lpeg] package config file

### ISSUE THREAD

**Issue by TheCycoONE** [microsoft/vcpkg#38340]
### Is your feature request related to a problem? Please describe.

Neither of these ports, indeed none of the lua libraries, currently provide package config files; so they are not easily found by cmake when they are installed.

I suspect normally these dlls are not linked and simply loaded at runtime through lua's require command, but that doesn't work when a static triplet is used.

### Proposed solution

Provide package config files for these ports e.g. lpegConfig.cmake

### Describe alternatives you've considered

Alternatively I've considered restricting these packages to always build with dlls/so files even when a static triplet is chosen. I think it would be more valuable to support linking the libraries as this differentiates vcpkg from luarocks and results in simpler packaging.

### Additional context

I am willing to work on the change myself if there is consensus.

**Comment by jimwang118** [comment]
Thanks, it would be great if you could add the usage of cmake.
