### ISSUE TITLE
[New Port Request] Low Level Graphics Library

### ISSUE THREAD

**Issue by zhaoboqiang** [microsoft/vcpkg#38357]
### Library name

Low Level Graphics Library

### Library description

Low Level Graphics Library (LLGL) is a thin abstraction layer for the modern graphics APIs OpenGL, Direct3D, Vulkan, and Metal

### Source repository URL

https://github.com/LukasBanana/LLGL

**Comment by Osyotr** [comment]
The library is already in vcpkg.
https://github.com/microsoft/vcpkg/tree/master/ports/llgl

And it's even mentioned in readme: https://github.com/LukasBanana/LLGL?tab=readme-ov-file#installing-luabridge-vcpkg
