### ISSUE TITLE
[opencv4] Build error (CUDA)

### ISSUE THREAD

**Issue by REVRBE** [microsoft/vcpkg#38362]
Having some issues building opencv4 with CUDA module using vcpkg

I installed opencv4 normally first then did the cuda module with --recurse

'vcpkg.exe install opencv4:x64-windows'
'vcpkg.exe install opencv4[cuda]:x64-windows --recurse'

I read somewhere that Visual Studio 2022 isn't supported, is this the case? Feels kind of weird having to downgrade to 2015 or 2019...

Visual Studio 2022
Windows 10

`-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/vcpkg/vcpkg/downloads/tools/cmake-3.29.2-windows/cmake-3.29.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j21
    Working Directory: C:/vcpkg/vcpkg/buildtrees/opencv4/x64-windows-dbg
    See logs for more information:
      C:\vcpkg\vcpkg\buildtrees\opencv4\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/opencv4/portfile.cmake:479 (vcpkg_cmake_install)
  scripts/ports.cmake:175 (include)

error: building opencv4:x64-windows failed with: BUILD_FAILED
Elapsed time to handle opencv4:x64-windows: 6.1 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+opencv4
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[opencv4]+Build+error&body=Copy+issue+body+from+C%3A%2Fvcpkg%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md`

Copy issue body from C:/vcpkg/vcpkg/installed/vcpkg/issue_body.md

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/15078701/install-x64-windows-dbg-out.log)

**Comment by Cheney-W** [comment]
I could reproduce this issue with the latest vcpkg and VS2022 17.9.6 and cuda 12.4.1.

**Comment by REVRBE** [comment]
> I could reproduce this issue with the latest vcpkg and VS2022 17.9.6 and cuda 12.4.1.

I'm using the latest vcpkg, VS2022 17.7.4 and cuda 12.4.1 - I failed to mention the specific versions I've been using. Anyways, do you know how and what I need to downgrade in order to be able to build OpenCV4 with CUDA?

**Comment by Cheney-W** [comment]
You could remove the cuda 12.4.1 and reinstall the cuda 11.7.
https://developer.nvidia.com/cuda-11-7-0-download-archive
