### ISSUE TITLE
[gdk-pixbuf] not installable by default on windows

### ISSUE THREAD

**Issue by kazssym** [microsoft/vcpkg#38360]
**Describe the bug**
I could not install gdk-pixbuf on Windows with its default features and got this error.

```
gdk-pixbuf[tiff] is only supported on '!windows', which does not match x64-windows. This usually means that there are known build failures, or runtime problems, when building other platforms. To ignore this and attempt to build gdk-pixbuf anyway, rerun vcpkg with `--allow-unsupported`.
```

It requires me to omit features `tiff` and `jpeg` (these two have `!windows` set) to install without this error.

**Environment**
- OS: Windows 11
- Compiler: MSVC 19.39.33522

**To Reproduce**
1. ./vcpkg install gdk-pixbuf:x64-windows
2. See error

**Expected behavior**
gdk-pixbuf should be installed with the default features or automatically omit unsupported features.

**Failure logs**
-(please attached failure logs)

**Additional context**

**Comment by kazssym** [comment]
The change was at dda6ab70d6.

**Comment by dg0yt** [comment]
Wow, that PR was cursed.
