### ISSUE TITLE
[gettext] Build error on x64-linux with bison

### ISSUE THREAD

**Issue by mkreddy477** [microsoft/vcpkg#38370]
Copy issue body from Installing 117/174 gettext-libintl:x64-linux@0.22.4#1...

Elapsed time to handle gettext-libintl:x64-linux: 3.34 ms

gettext-libintl:x64-linux package ABI: 24c3008f27e52fc3c24e2a02faa7fe918b7aeff29b1bbccd01a2075642eb3e93

Installing 118/174 gettext[core,tools]:x64-linux@0.22.4#2...

Building gettext[core,tools]:x64-linux@0.22.4#2...

-- Installing port from location: /local/home/server/.cache/vcpkg/registries/git-trees/d9cc9b8256d9653fe2d484ecf268f7368666d942

-- Using cached gettext-0.22.4.tar.gz.

-- Cleaning sources at /local/home/server/jenkins/workspace/vcpkg_linux_fba75d0/buildtrees/gettext/src/gettext-0-b0a8925cfc.clean. Use --editable to skip cleaning for the packages you specify.

-- Extracting source /local/home/server/jenkins/workspace/vcpkg_linux_fba75d0/downloads/gettext-0.22.4.tar.gz

-- Applying patch assume-modern-darwin.patch

-- Applying patch uwp.patch

-- Applying patch rel_path.patch

-- Applying patch subdirs.patch

-- Applying patch parallel-gettext-tools.patch

-- Applying patch config-step-order.patch

-- Using source at /local/home/server/jenkins/workspace/vcpkg_linux_fba75d0/buildtrees/gettext/src/gettext-0-b0a8925cfc.clean

CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:166 (message):

  Could not find bison.  Please install it via your package manager:

      sudo apt-get install bison

Call Stack (most recent call first):

  /local/home/server/.cache/vcpkg/registries/git-trees/d9cc9b8256d9653fe2d484ecf268f7368666d942/portfile.cmake:43 (vcpkg_find_acquire_program)

  scripts/ports.cmake:170 (include)

error: building gettext:x64-linux failed with: BUILD_FAILED

Can someone throw some light on this issue?

**Comment by mkreddy477** [comment]
Ideally, I need videoio core and video libraries. Is it possible to exclude these other modules to be installed into my project?

**Comment by jimwang118** [comment]
Can you install gettext normally after installing bison?

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
