### ISSUE TITLE
Wild-card linking

### ISSUE THREAD

**Issue by degski** [microsoft/vcpkg#3837]
Checking the build output (of some project) (with a high verbosity) reveals that, simply all libs in the `..\vcpkg\installed\x64-windows-static\lib` folder get fed to the linker with a wild-card `*.lib` .

This, IMHO, is asking for trouble, but at the very least dis-allows for some more fine-grained approach to linking libraries.

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen this issue.
