### ISSUE TITLE
[libmount] Build error on x64-linux

### ISSUE THREAD

**Issue by MichaelSipayung** [microsoft/vcpkg#38429]
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/autoreconf -vfi
    Working Directory: /home/humasaks/vcpkg/buildtrees/libmount/src/2.40-b5c733b07e.clean/
    Error code: 2
    See logs for more information:
      /home/humasaks/vcpkg/buildtrees/libmount/autoconf-x64-linux-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:728 (vcpkg_execute_required_process)
  ports/libmount/portfile.cmake:25 (vcpkg_configure_make)
  scripts/ports.cmake:175 (include

**Comment by JonLiu1993** [comment]
Please provide your error log:
````
/home/humasaks/vcpkg/buildtrees/libmount/autoconf-x64-linux-err.log
````

**Comment by lesauxvi** [comment]
I have the same issue. The content of the log is:

```
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: running: true --force
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
Can't exec "libtoolize": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 293.
autoreconf: error: libtoolize failed with exit status: 2
```

**Comment by MichaelSipayung** [comment]
I already found it, the solution is simple, just try install missing
library on Linux. Look the error logs, it's mention that some library is
missing.
