### ISSUE TITLE
Could not locate a complete toolset. Please install the English language pack

### ISSUE THREAD

**Issue by waruqi** [Microsoft/vcpkg#3842]
> Warning: The following VS instances are excluded because the English language pack is unavailable.

Can vcpkg support vs for lower version and other languages?  I don't really want to upgrade VS, because my virtual machine's disk space is really not enough.

```console
> vcpkg install mbedtls
The following packages will be built and installed:
    mbedtls[core]:x86-windows
Starting package 1/1: mbedtls:x86-windows
Building package mbedtls[core]:x86-windows...
A suitable version of cmake was not found (required v3.11.4). Downloading portable cmake v3.11.4...
Downloading cmake...
Downloading cmake... done.
Extracting cmake...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
Downloading 7zip... done.
Extracting 7zip...
A suitable version of nuget was not found (required v4.6.2). Downloading portable nuget v4.6.2...
Downloading nuget...
Downloading nuget... done.
Extracting 7zip... done.
Extracting cmake... done.
A suitable version of git was not found (required v2.17.1). Downloading portable git v2.17.1...
Downloading git...
Downloading git... done.
Extracting git...
Extracting git... done.
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
Please install the English language pack.
Could not locate a complete toolset.
The following paths were examined:
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX86\x86\dumpbin.exe
```

see [#3825](https://github.com/Microsoft/vcpkg/issues/3825)

**Comment by jairov4** [comment]
Why it was closed? I still have the same problem

**Comment by waruqi** [comment]
@jairov4 I have re-installed vs2017 with English language pack to solve this problem.

**Comment by Biter777** [comment]
1) Go to https://visualstudio.microsoft.com/ru/downloads/
and download "Build Tools for Visual Studio"
2) Run "Build Tools for Visual Studio", choise "Language packs" and add "English".

Profit!

**Comment by eatcosmos** [comment]
> 1. Go to https://visualstudio.microsoft.com/ru/downloads/
>    and download "Build Tools for Visual Studio"
> 2. Run "Build Tools for Visual Studio", choise "Language packs" and add "English".
> 
> Profit!

![image](https://user-images.githubusercontent.com/16435896/71135427-8a2fec00-223c-11ea-9549-4b3630806f4a.png)

**Comment by Sunnyone1234** [comment]
> 1. Go to https://visualstudio.microsoft.com/ru/downloads/
>    and download "Build Tools for Visual Studio"
> 2. Run "Build Tools for Visual Studio", choise "Language packs" and add "English".
> 
> Profit!

Another way is just run the installer and  use the modify option to add new language package. Just like this: [add new language package](https://agirlamonggeeks.com/2019/03/10/how-to-change-language-in-visual-studio-2019-after-installation/)

**Comment by Edurd987** [comment]
Which command from the console can install the English Language Pack for Visual Studio 2019

**Comment by the-overdriven** [comment]
I have English VS already and I still get the same error.

**Comment by sfhacker** [comment]
This issue is from 2018!!!!
There is no need to install any language pack to build projects from source on Windows.
No idea where that weird requirement came/come from?
