### ISSUE TITLE
providing multiple vcpkg install options in manifest mode fails

### ISSUE THREAD

**Issue by gtsc** [microsoft/vcpkg#38431]
**Describe the bug**
When using vcpkg in manifest mode, I would want to be able to provide more than one install option via `VCPKG_INSTALL_OPTIONS`.

I'm using CMake on a project that has a `vcpkg.json` in the following way:
`cmake /path/to/source/code -DCMAKE_TOOLCHAIN_FILE=/path/to/vcpkg/scripts/buildsystems/vcpkg.cmake -G Ninja`

Sometimes I would want to add one or more of the [vcpkg install options](https://learn.microsoft.com/en-us/vcpkg/commands/install#options) which I think is done by providing the variable `VCPKG_INSTALL_OPTIONS`. E.g. appending `-DVCPKG_INSTALL_OPTIONS="--no-print-usage"` to the command shown above does what it is supposed to do.

However, I struggle with being able to provide multiple options. According to [this Microsoft Learn page](https://learn.microsoft.com/en-us/vcpkg/users/buildsystems/cmake-integration#vcpkg_install_options) it should be possible to provide a list of options, but I the following won't work (see below for error message):
- ` -DVCPKG_INSTALL_OPTIONS="--debug --no-print-usage"`
- ` -DVCPKG_INSTALL_OPTIONS="--debug,--no-print-usage"`

There might be a correct way of providing the list of options, but I couldn't figure out how to do it (neither via the command line nor via a CMake preset).

Can you please advise how to use more than one vcpkg install option in manifest mode via the CMake variable? If this is indeed a shortcoming I am happy to work on it and submit a fix for it.

**Environment**
- OS: MacOS X
- Compiler: Apple Clang 15.0.0.15000309

**To Reproduce**
1. run `cmake /path/to/source/code -DCMAKE_TOOLCHAIN_FILE=/path/to/vcpkg/scripts/buildsystems/vcpkg.cmake -G Ninja -DVCPKG_INSTALL_OPTIONS="--debug --no-print-usage"` on a project that supports vcpkg manifest mode (has `vcpkg.json`)
2. See error
Repro code when

**Expected behavior**
vcpkg should be able to take multiple install options in manifest mode, and in this example both provide debug output and omit printing the usage of individual packages.

**Failure logs**
```
cmake .. -DCMAKE_TOOLCHAIN_FILE=/path/to/vcpkg/scripts/buildsystems/vcpkg.cmake -G Ninja -DVCPKG_INSTALL_OPTIONS="--debug --no-print-usage"
-- Running vcpkg install
error: unexpected switch: --debug --no-print-usage
vcpkg install <port name> <port name>...
vcpkg install zlib zlib:x64-windows curl boost
vcpkg install --triplet x64-windows
Options:
  --allow-unsupported    Continues with a warning on unsupported ports, rather than failing
  --x-asset-sources=...  Asset caching sources. See 'vcpkg help assetcaching'
  --binarysource=...     Binary caching sources. See 'vcpkg help binarycaching'
  --x-buildtrees-root=...
                         Buildtrees directory (experimental)
  --clean-after-build    Cleans buildtrees, packages and downloads after building each package
  --clean-buildtrees-after-build
                         Cleans buildtrees after building each package
  --clean-downloads-after-build
                         Cleans downloads after building each package
  --clean-packages-after-build
                         Cleans packages after building each package
  --downloads-root=...   Downloads directory (default: $VCPKG_DOWNLOADS)
  --dry-run              Does not actually build or install
  --editable             Disables source re-extraction and binary caching for libraries on the
                         command line (classic mode)
  --enforce-port-checks  Fails install if a port has detected problems or attempts to use a
                         deprecated feature
  --x-feature=...        Additional features from the top-level manifest to install (manifest mode)
  --head                 Installs the libraries on the command line using the latest upstream
                         sources (classic mode)
  --host-triplet=...     Host triplet. See 'vcpkg help triplet' (default:
                         $VCPKG_DEFAULT_HOST_TRIPLET)
  --x-install-root=...   Installed directory (experimental)
  --keep-going           Continues installing packages on failure
  --x-no-default-features
                         Does not install the default features from the top-level manifest (manifest
                         mode)
  --no-downloads         Does not download new sources
  --no-print-usage       Does not print CMake usage information after install
  --only-binarycaching   Fails if cached binaries are not available
  --only-downloads       Makes best-effort attempt to download sources without building
  --overlay-ports=...    Directories of overlay ports (also: $VCPKG_OVERLAY_PORTS)
  --overlay-triplets=... Directories of overlay triplets (also: $VCPKG_OVERLAY_TRIPLETS)
  --x-packages-root=...  Packages directory (experimental)
  --recurse              Allows removal of packages as part of installation
  --triplet=...          Target triplet. See 'vcpkg help triplet' (default: $VCPKG_DEFAULT_TRIPLET)
  --x-use-aria2          Uses aria2 to perform download tasks
  --vcpkg-root=...       The vcpkg root directory (default: $VCPKG_ROOT)
  --x-write-nuget-packages-config=...
                         Writes a NuGet packages.config-formatted file for use with external binary
                         caching. See `vcpkg help binarycaching` for more information

-- Running vcpkg install - failed
CMake Error at /path/to/vcpkg/scripts/buildsystems/vcpkg.cmake:899 (message):
  vcpkg install failed.  See logs for more information:
  /path/to/repo/vcpkg-minimal-example/build/vcpkg-manifest-install.log
Call Stack (most recent call first):
  build/CMakeFiles/3.20.5/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:3 (project)


-- Configuring incomplete, errors occurred!
See also "/path/to/repo/vcpkg-minimal-example/build/CMakeFiles/CMakeOutput.log".
See also /path/to/repo/vcpkg-minimal-example/build/CMakeFiles/CMakeError.log".
```

**Comment by autoantwort** [comment]
CMake lists are separated by `;`. So ` -DVCPKG_INSTALL_OPTIONS="--debug;--no-print-usage"` should work as expected.

**Comment by gtsc** [comment]
@autoantwort Today I learned, no idea why I hadn't tried that earlier. Thanks, can confirm that it's working as expected!
