### ISSUE TITLE
[gmp] Build error on x64-windows

### ISSUE THREAD

**Issue by kdhjc** [microsoft/vcpkg#38447]
Computing installation plan...
The following packages will be built and installed:
    gmp:x64-windows@6.3.0
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from C:\Users\jiachenghao\AppData\Local\vcpkg\archives in 89.6 us. Use --debug to see more details.
Installing 1/1 gmp:x64-windows@6.3.0...
Building gmp:x64-windows@6.3.0...
-- Using cached gmp-6.3.0.tar.xz.
-- Cleaning sources at E:/vcpkg/buildtrees/gmp/src/v6.3.0-036e54f1a3.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/vcpkg/downloads/gmp-6.3.0.tar.xz
-- Applying patch asmflags.patch
-- Applying patch cross-tools.patch
-- Applying patch subdirs.patch
-- Applying patch msvc_symbol.patch
-- Applying patch arm64-coff.patch
-- Using source at E:/vcpkg/buildtrees/gmp/src/v6.3.0-036e54f1a3.clean
-- Getting CMake variables for x64-windows
-- Getting CMake variables for x64-windows
-- Using cached msys2-autoconf-wrapper-20221207-1-any.pkg.tar.zst.
-- Using cached msys2-automake-wrapper-20221207-2-any.pkg.tar.zst.
-- Using cached msys2-binutils-2.42-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libtool-2.4.7-3-x86_64.pkg.tar.zst.
-- Using cached msys2-make-4.4.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-pkgconf-2.1.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-which-2.21-4-x86_64.pkg.tar.zst.
-- Using cached msys2-bash-5.2.026-1-x86_64.pkg.tar.zst.
-- Using cached msys2-coreutils-8.32-5-x86_64.pkg.tar.zst.
-- Using cached msys2-file-5.45-1-x86_64.pkg.tar.zst.
-- Using cached msys2-gawk-5.3.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-grep-1~3.0-6-x86_64.pkg.tar.zst.
-- Using cached msys2-gzip-1.13-1-x86_64.pkg.tar.zst.
-- Using cached msys2-diffutils-3.10-1-x86_64.pkg.tar.zst.
-- Using cached msys2-sed-4.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst.
-- Using cached msys2-autoconf2.71-2.71-3-any.pkg.tar.zst.
-- Using cached msys2-automake1.16-1.16.5-1-any.pkg.tar.zst.
-- Using cached msys2-libiconv-1.17-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libintl-0.22.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-zlib-1.3.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-tar-1.35-2-x86_64.pkg.tar.zst.
-- Using cached msys2-findutils-4.9.0-3-x86_64.pkg.tar.zst.
-- Using cached msys2-gmp-6.3.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-gcc-libs-13.2.0-2-x86_64.pkg.tar.zst.
-- Using cached msys2-libbz2-1.0.8-4-x86_64.pkg.tar.zst.
-- Using cached msys2-liblzma-5.4.6-2-x86_64.pkg.tar.zst.
-- Using cached msys2-libzstd-1.5.5-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libreadline-8.2.010-1-x86_64.pkg.tar.zst.
-- Using cached msys2-mpfr-4.2.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libpcre-8.45-4-x86_64.pkg.tar.zst.
-- Using cached msys2-m4-1.4.19-2-x86_64.pkg.tar.zst.
-- Using cached msys2-perl-5.38.2-1-x86_64.pkg.tar.zst.
-- Using cached msys2-ncurses-6.4-2-x86_64.pkg.tar.zst.
-- Using cached msys2-libxcrypt-4.4.36-1-x86_64.pkg.tar.zst.
-- Using msys root at E:/vcpkg/downloads/tools/msys2/09133458fed80fcb
-- Generating configure for x64-windows
-- Finished generating configure for x64-windows
-- Using cached msys2-mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst.
-- Using msys root at E:/vcpkg/downloads/tools/msys2/d33df895d441a36d
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: E:/vcpkg/downloads/tools/msys2/09133458fed80fcb/usr/bin/make.exe -j 9 --trace -f Makefile all
    Working Directory: E:/vcpkg/buildtrees/gmp/x64-windows-dbg/
    See logs for more information:
      E:\vcpkg\buildtrees\gmp\build-x64-windows-dbg-out.log
      E:\vcpkg\buildtrees\gmp\build-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:136 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:2 (vcpkg_build_make)
  ports/gmp/portfile.cmake:92 (vcpkg_install_make)
  scripts/ports.cmake:175 (include)
[build-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/15140840/build-x64-windows-dbg-err.log)
[build-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/15140842/build-x64-windows-dbg-out.log)

```[tasklist]
### Tasks
```

**Comment by kdhjc** [comment]
I install CGAL under Windows, and then it prompts an error to install gmp, and I get this error when I install GMP alone

**Comment by jimwang118** [comment]
Sorry, I can't reproduce your issue locally.
It is recommended that you set the compiler language to other than English.
![image](https://github.com/microsoft/vcpkg/assets/122244446/136827b0-1173-4322-9099-4ff897445cad)

**Comment by mrei-kiel** [comment]
My build failed with the same Call Stack when I tried to install GMP using the Visual Studio MSVC.

**Comment by jimwang118** [comment]
> My build failed with the same Call Stack when I tried to install GMP using the Visual Studio MSVC.

Did you install cgal through vcpkg?

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
