### ISSUE TITLE
[aom] build failure

### ISSUE THREAD

**Issue by xfront** [microsoft/vcpkg#38454]
### Operating system

linux

### Compiler

gcc

### Steps to reproduce the behavior

```Shell
vcpkg/vcpkg install aom
```

### Failure logs

Installing 1/1 aom:x64-linux@3.8.1...
Building aom:x64-linux@3.8.1...
-- Fetching https://aomedia.googlesource.com/aom bb6430482199eaefbeaaa396600935082bc43f66...
-- Extracting source /work/opensrc/c++/vcpkg/downloads/aom-bb6430482199eaefbeaaa396600935082bc43f66.tar.gz
-- Applying patch aom-rename-static.diff
-- Applying patch aom-uninitialized-pointer.diff
-- Applying patch aom-install.diff
-- Using source at /work/opensrc/c++/vcpkg/buildtrees/aom/src/082bc43f66-bbe7040b1b.clean
-- Configuring x64-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /work/opensrc/c++/vcpkg/downloads/tools/ninja/1.10.2-linux/ninja -v
    Working Directory: /work/opensrc/c++/vcpkg/buildtrees/aom/x64-linux-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      /work/opensrc/c++/vcpkg/buildtrees/aom/config-x64-linux-dbg-CMakeCache.txt.log
      /work/opensrc/c++/vcpkg/buildtrees/aom/config-x64-linux-rel-CMakeCache.txt.log
      /work/opensrc/c++/vcpkg/buildtrees/aom/config-x64-linux-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:252 (vcpkg_execute_required_process)
  ports/aom/portfile.cmake:33 (vcpkg_cmake_configure)
  scripts/ports.cmake:175 (include)

error: building aom:x64-linux failed with: BUILD_FAILED
Elapsed time to handle aom:x64-linux: 8 s
Please ensure you're using the latest port files with `git pull` and `vcpkg upda

### Additional context

linux mint 21.3, gcc 12, vcpkg [2024.03.25]

**Comment by MonicaLiu0311** [comment]
> ```
> Error code: 1
> See logs for more information:
> /work/opensrc/c++/vcpkg/buildtrees/aom/config-x64-linux-dbg-CMakeCache.txt.log
> /work/opensrc/c++/vcpkg/buildtrees/aom/config-x64-linux-rel-CMakeCache.txt.log
> /work/opensrc/c++/vcpkg/buildtrees/aom/config-x64-linux-out.log
> ```

Please provide the log file containing error information.

**Comment by MonicaLiu0311** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
