### ISSUE TITLE
A suitable version of cmake was not found (required v3.11.4). Downloading portable cmake v3.11.4... Downloading cmake...

### ISSUE THREAD

**Issue by Ben940315** [Microsoft/vcpkg#3846]
When I use vcpkg to install boost ,I meet the issue. 
However I have installed the cmake. 
 I run "cmake --version", and I got cmake version 3.11.4

**Comment by licensedslacker** [comment]
I have the same issue. Does this generate too much traffic to CMake website because it seems to be unavailable very often?

**Comment by gix** [comment]
This was fixed in https://github.com/Microsoft/vcpkg/commit/1f4dde2b22a872b9ff5bbe909d8c7af63adc4efa

**Comment by NancyLi1013** [comment]
The PR has been merged. So close this issue.
