### ISSUE TITLE
[boost] build failure

### ISSUE THREAD

**Issue by SKNo** [microsoft/vcpkg#38487]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
git pull
vcpkg upgrade --no-dry-run
```

### Failure logs

```
error: The control or manifest file for boost-vcpkg-helpers could not be loaded due to the following error. Please remove boost-vcpkg-helpers and try again.)
E:\Lib\vcpkg\ports\boost-vcpkg-helpers: error: boost-vcpkg-helpers dies not exist
```

### Additional context

It happend after git pull (including the latest version of boost)

**Comment by Neumann-A** [comment]
`boost-vcpkg-helpers` has been removed. Be aware that `vcpkg upgrade` is not really a supported command since it is not transactional

**Comment by SKNo** [comment]
@Neumann-A 
I am confuse : what would be the command to upgrade all updated softwares and their dependencies after a `git pull` 
Thank you

**Comment by Neumann-A** [comment]
Either use a manifest which automatically rebuilds everything (and deletes as needed) or delete your installed tree manually and rebuild everything manually. 
`vcpkg upgrade` is not transactional; it just exists for historic reasons.

**Comment by SKNo** [comment]
Thank you @Neumann-A 
I've always looked at `vcpkg upgrade` as a usefull one-liner similar to `conda update --all` 
Is there an example for such a manifest or should I go through documentations?
Thanks again

**Comment by Neumann-A** [comment]
> Is there an example for such a manifest or should I go through documentations?

Manifest is just a `vcpkg.json`. All ports have such a file. For usage having only the `dependencies` field is theoretical enough. You can use `--x-manifest-root=<manifest-dir>` if you do not want to have the manifest in the same directory as vcpkg.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by alexander-sorokin** [comment]
> > Is there an example for such a manifest or should I go through documentations?
> 
> Manifest is just a `vcpkg.json`. All ports have such a file. For usage having only the `dependencies` field is theoretical enough. You can use `--x-manifest-root=<manifest-dir>` if you do not want to have the manifest in the same directory as vcpkg.

Sorry, I am from old times when people was expecting from developers to create some useful tools, like update assistants and built-in commands to perform standard action instead of removing files or correcting text files by hands. These times it was a good practice for developer to create some kind of porting script if backward compatibility was broken by update insted of asking millions of users to find out how to solve the problem they not created.

Is there any tutorial how to use modern practices of updating?

**Comment by ZhangAnam** [comment]
FIx it !

**Comment by ZhangAnam** [comment]
> > > Is there an example for such a manifest or should I go through documentations?
> > 
> > 
> > Manifest is just a `vcpkg.json`. All ports have such a file. For usage having only the `dependencies` field is theoretical enough. You can use `--x-manifest-root=<manifest-dir>` if you do not want to have the manifest in the same directory as vcpkg.
> 
> Sorry, I am from old times when people was expecting from developers to create some useful tools, like update assistants and built-in commands to perform standard action instead of removing files or correcting text files by hands. These times it was a good practice for developer to create some kind of porting script if backward compatibility was broken by update insted of asking millions of users to find out how to solve the problem they not created.
> 
> Is there any tutorial how to use modern practices of updating?

Removed, without any candidate solutions. OMG!

**Comment by Blakjak88** [comment]
Where is the explanation of how to build a manifest file to update all my packages after a git-pull. I have about 50 packages installed. Am I expected to upgrade each one by one?

**Comment by dg0yt** [comment]
> Where is the explanation of how to build a manifest file to update all my packages after a git-pull. I have about 50 packages installed. Am I expected to upgrade each one by one?

In manifest mode, the `builtin-baseline` controls the versions which are selected by default.
https://learn.microsoft.com/en-us/vcpkg/reference/vcpkg-json#builtin-baseline

There is command to update this property:
https://learn.microsoft.com/en-us/vcpkg/commands/update-baseline

**Comment by alexander-sorokin** [comment]
> In manifest mode, the `builtin-baseline` controls the versions which are selected by default.

But what about old good global mode? I do not want to create dozens of copies of the same version DLLs and LIBs on my HDD.

**Comment by dg0yt** [comment]
Let's not continue in issue "[boost] build failure".

**Comment by pudding186** [comment]
Could any expert provide a vcpkg.json file that updates all installed packages?

**Comment by dg0yt** [comment]
> Could any expert provide a vcpkg.json file that updates all installed packages?

No. That's not possible.

@LilyWangLL I suggest locking this issue.

**Comment by pudding186** [comment]
> > Could any expert provide a vcpkg.json file that updates all installed packages?
> 
> No. That's not possible.
> 
> @LilyWangLL I suggest locking this issue.

Why it's not possible? Shouldn't software provide backward compatibility? If it truly cannot be compatible, then at least the update notes should address this issue and provide a solution, right?

**Comment by dg0yt** [comment]
@pudding186 Plese open your own discussion. Do not use this issue.

**Comment by olapchuk** [comment]
Do I get it right: the tool is broken for several months, and nobody cares ?

**Comment by Neumann-A** [comment]
> Do I get it right: the tool is broken for several months, and nobody cares ?

Because `upgrade` is as mentioned in the docs not robust and basically usage has been discouraged at least since the introduction of manifest mode. If you really need the `upgrade` command and dont want to switch to manifest mode you can restore the old version of the port locally or create an empty dummy for it. 
So there are so many ways to work around the issue...

**Comment by sfhacker** [comment]
This is not sustainable!
