### ISSUE TITLE
[qtwebengine] build completes without errors but the core Qt6WebEngine module is not being built

### ISSUE THREAD

**Issue by tsondergaard** [microsoft/vcpkg#38503]
**Describe the bug**
qtwebengine doesn't detect that the core Qt6WebEngine module isn't being built

This can happen in different situations where the detection of a dependency fails. The underlying issue is the qtwebengine build system allows some modules to fail to build without the configure script returning an error code. #38497 provides a repro example for this where the trigger is that the ffmpeg version in the current baseline is too new for qtwebengine and it prints this message while still returning 0 as exit code from the configure step:

```
WARNING: QtWebEngine won't be built. Unmodified ffmpeg >= 5.0 is not supported.
```

The Vcpkg port patch the Qt configure script to make that warning fatal.

**Comment by Neumann-A** [comment]
Patch for ffmpeg is here:
https://aur.archlinux.org/cgit/aur.git/tree/040-ffmpeg-add-av_stream_get_first_dts-for-chromium.patch?h=ffmpeg-intel-full-git
