### ISSUE TITLE
2024.04.23 build failure

### ISSUE THREAD

**Issue by chenrui333** [microsoft/vcpkg#38517]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  CMake Error at CMakeLists.txt:196 (cmrc_add_resource_library):
    Unknown CMake command "cmrc_add_resource_library".
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/8900317936/job/24441728512
relates to Homebrew/homebrew-core#170471

**Comment by FrankXie05** [comment]
This command should be included and used by `find_package(CMakeRC REQUIRED)`. 
Could you please try clearing the cmake cache and try again?

https://github.com/microsoft/vcpkg-tool/blob/d6945642ee5c3076addd1a42c331bbf4cfc97457/CMakeLists.txt#L191

cc @data-queue
