### ISSUE TITLE
Error: Building package libuuid:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by zmm20** [Microsoft/vcpkg#3852]
Vcpkg version: 0.0.108-2018-04-19-4f52f53b99f6a5465157958bc99f79cc0b2712ad

how solve this issue please?

**Comment by justinvh** [comment]
Just confirming that I also see this:

  Package: libuuid:x64-windows
  Vcpkg version: 0.0.113-nohash

**Comment by PhoebeHui** [comment]
@zmm20, could you share .\buildtrees\libuuid\install-x64-windows-dbg-out.log? I tried to install libuuid, and it failed with ".\buildtrees\libuuid\src\libuuid-1.0.3\randutils.c(10): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory",  is it same issue with you? 

Similar issue with https://github.com/Microsoft/vcpkg/issues/4331

**Comment by JackBoosY** [comment]
Hi @zmm20, thanks for reporting this issue!
This issue has been fixed. Plz update and rebuild libuuid.
Thx.
