### ISSUE TITLE
[cudnn] Build error on x64-windows

### ISSUE THREAD

**Issue by sinozope** [microsoft/vcpkg#38521]
Package: cudnn:x64-windows@7.6.5#11

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.39.33523.0
-    vcpkg-tool version: 2024-04-23-d6945642ee5c3076addd1a42c331bbf4cfc97457
    vcpkg-scripts version: c591ac646 2024-04-30 (31 hours ago)

**To Reproduce**

`vcpkg install cuda:x64-windows cudnn:x64-windows`

**Failure logs**

```
-- Found CUDA V12.4.131
-- CUDNN_INCLUDE_DIR: CUDNN_INCLUDE_DIR-NOTFOUND
-- CUDNN_LIBRARY: CUDNN_LIBRARY-NOTFOUND
CMake Error at ports/cudnn/portfile.cmake:58 (message):
  Please download CUDNN from official sources (such as
  https://developer.nvidia.com/rdp/cudnn-download ) and extract the zip into
  your CUDA_TOOLKIT_ROOT (C:/Program Files/NVIDIA GPU Computing
  Toolkit/CUDA/v12.4).  (For example: tar.exe -xvf
  cudnn-11.2-windows-x64-v8.1.1.33.zip --strip 1 --directory "C:/Program
  Files/NVIDIA GPU Computing Toolkit/CUDA/v12.4"
Call Stack (most recent call first):
  scripts/ports.cmake:175 (include)



```

**Comment by WangWeiLin-MV** [comment]
Please see external dependencies documentation https://docs.nvidia.com/deeplearning/cudnn/latest/installation/windows.html#installing-on-windows
