### ISSUE TITLE
[wxwidgets] Cannot link wx::wxgl namespace.

### ISSUE THREAD

**Issue by sidy3d** [microsoft/vcpkg#38539]
**Describe the bug**
Cannot use features in the wxGL library (wxGLContext, wxGLCanvas, etc) of WxWidgets when using manifests mode with CMake.

**Environment**
- OS: Windows 11, Version 23H2
- Compiler: MSVC MSVC 17.9.6

**To Reproduce**
1. Create a CMake project
2. Install wxWidgets and glew using manifest mode
3. Create a sample application with this code [https://github.com/lszl84/wx_opengl_tutorial/blob/main/src/main.cpp](url)
4. Add a simple `CMakeLists.txt` file:
```
cmake_minimum_required (VERSION 3.28)

set(CMAKE_CXX_STANDARD 20)
project (openGLIntergration CXX)

find_package(gl3w CONFIG REQUIRED)
find_package(wxwidgets CONFIG REQUIRED)

# Add source to this project's executable.
add_executable (openGLIntergration WIN32 "main.cpp")

target_link_libraries(openGLIntergration PRIVATE unofficial::gl3w::gl3w)
target_link_libraries(openGLIntergration PRIVATE wx::core wx::base wx::wxgl)
```

**Expected behavior**
The CMake cache generation should be successful, and the project should be built successfully.

**Failure logs**
```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error		CMake Error at out/build/x64-Debug-MSVC/vcpkg_installed/x64-windows/share/wxwidgets/wxWidgetsTargets.cmake:159 (set_target_properties):
  The link interface of target "wx::wxgl" contains:

    OpenGL::GLU

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.		C:\dev\source\wxWidgetsTutorials\openGLIntergration\out/build/x64-Debug-MSVC/vcpkg_installed/x64-windows/share/wxwidgets/wxWidgetsTargets.cmake	159		

```

**Additional context**
This error makes it impossible to use OpenGL related functionality with WxWidgets. The same project works fine with a standard Visual Studio solution using vcpkg in manifests mode.

**Comment by WangWeiLin-MV** [comment]
Please temporarily use the following workaround:
```cmake
find_package(wxWidgets COMPONENTS core base gl REQUIRED)
target_link_libraries(main PRIVATE ${wxWidgets_LIBRARIES})
```

**Comment by sidy3d** [comment]
Ok that seems to work. I had to change the OpenGL loader to GLEW, not sure if the control works with other loaders but that is different question.

**Comment by sidy3d** [comment]
From the linked thread the solution is to add `find_package(OpenGL QUIET)` to the CMake file.
The issue is already fixed in the main branch, so I will mark this as closed.
