### ISSUE TITLE
boost-iostream port cmakelists.txt contains hard-coded "x32"

### ISSUE THREAD

**Issue by longpractice** [microsoft/vcpkg#3853]
https://github.com/Microsoft/vcpkg/blob/7c4e262e5037b0b4a49775b65b2de55ed9b7b4af/ports/boost-iostreams/CMakeLists.txt#L19

I think this one should not be hard-coded as a "x32" here.

**Comment by cguebert** [comment]
I would also add that the version of boost should not be hard coded.

**Comment by PhoebeHui** [comment]
@longpractice , thanks for reporting this issue, currently it fixed. Related commit https://github.com/microsoft/vcpkg/commit/0e759709ddc7dbad0b881f9f068f1b04b2092773#diff-06fedcaf7b3eaa65526cfa730c130a30
