### ISSUE TITLE
Adding nanovg

### ISSUE THREAD

**Issue by spacepluk** [Microsoft/vcpkg#3854]
Hi there, I created a package for [nanovg](https://github.com/memononen/nanovg) in my [fork](https://github.com/mooistudios/vcpkg/commit/f340b12384080c4e5d2084a47a86c6e21152b03a).  Are you interested in a PR?

**Comment by MarkIanHolland** [comment]
Hi! 
I also made a port for myself a little while ago but I didn't know if anyone would want it. Seeing as we're both using it, surely some others would appreciate it. 

After having a look at your port, one thing I would say is that I found that the lib would sometimes not be created on windows 10. I had the same result when i developed mine. It works for me if you add `set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)` to the cmakelist.

**Comment by spacepluk** [comment]
Oh, I forgot to ask about [this bit](https://github.com/MarkIanHolland/vcpkg/blob/nanovg/ports/nanovg/CMakeLists.txt#L3).  What's the use case for this? Just making sure that the PR will cover all our needs :)

**Comment by MarkIanHolland** [comment]
I was just playing around to sidestep the recursive delete in the portfile. It's not required.

**Comment by MarkIanHolland** [comment]
Still looking to make a PR?

**Comment by NancyLi1013** [comment]
@spacepluk , thanks for posting this issue and your PR. Now this port has been added to the master. So I close it.
