### ISSUE TITLE
[boost] boost:x64-windows build failed

### ISSUE THREAD

**Issue by imprnoob** [microsoft/vcpkg#38549]
**Describe the bug**
Error message displayed during library installation: Command failure "ninjia.exe-v"

**Environment**
- OS: [e.g. Windows]
- visual studio: 2022

**To Reproduce**
1. ./vcpkg install boost:x64-windows
2. See error
Repro code when

**Expected behavior**
install success

**Failure logs**
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/15201316/config-x64-windows-out.log)

**Additional context**
The error information is as follows：

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: F:/src/vcpkg/buildtrees/boost-headers/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      F:\src\vcpkg\buildtrees\boost-headers\config-x64-windows-rel-CMakeCache.txt.log
      F:\src\vcpkg\buildtrees\boost-headers\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:261 (vcpkg_execute_required_process)
  installed/x64-windows/share/vcpkg-boost/boost-install.cmake:55 (vcpkg_cmake_configure)
  ports/boost-headers/portfile.cmake:12 (boost_configure_and_install)
  scripts/ports.cmake:175 (include)

error: building boost-headers:x64-windows failed with: BUILD_FAILED
Elapsed time to handle boost-headers:x64-windows: 1.1 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-headers
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[boost-headers]+Build+error+on+x64-windows&body=Copy+issue+body+from+F%3A%2Fsrc%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by Cheney-W** [comment]
Could you please provide the below logs to us? Thank you!
```
F:\src\vcpkg\buildtrees\boost-headers\config-x64-windows-rel-CMakeCache.txt.log
F:\src\vcpkg\buildtrees\boost-headers\config-x64-windows-out.log
```

**Comment by Neumann-A** [comment]
@Cheney-W: The config log is there. However, the problem seems to be unrelated to boost. The problem here is that CMake is not able to run a simple test program:

```
    cl : Command line error D8050 : cannot execute 'C:\PROGRA~1\MICROS~3\2022\COMMUN~1\VC\Tools\MSVC\1439~1.335\bin\Hostx64\x64\c1xx.dll': failed to get command line into debug records

    ninja: build stopped: subcommand failed.
```

**Comment by Cheney-W** [comment]
@imprnoob Could you please reinstall Visual Studio and see if this issue still persists? Thank you!

**Comment by tensor5375** [comment]
I have a same issue with boost-core.

[vcpkg\buildtrees\boost-core\stdout-x64-windows.txt]
-- Downloading https://github.com/boostorg/core/archive/boost-1.85.0.tar.gz -> boostorg-core-boost-1.85.0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from c:\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: c:\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://github.com/boostorg/core/archive/boost-1.85.0.tar.gz
[DEBUG] Trying to hash C:\vcpkg\downloads\boostorg-core-boost-1.85.0.tar.gz.7816.part
[DEBUG] C:\vcpkg\downloads\boostorg-core-boost-1.85.0.tar.gz.7816.part has hash a1e774c98b537dd42018742af68f5889af1afd4e6c9809399987124e56a3b9ae2f20e8173170bc6fc0ad76fb95e2da7b9d385a4037e9ee12011fc02bf8f7e009
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/boostorg/core/archive/boost-1.85.0.tar.gz
File: C:\vcpkg\downloads\boostorg-core-boost-1.85.0.tar.gz.7816.part
Expected hash: 3a7be75e52f5c20830fccb9e7391a1e4556ebb072e6324df95b1ba38bed46e24f4c9f27a62a1099eddc90f2ac1ede083f0c850e2dc27fd42375d028516f675b3
Actual hash: a1e774c98b537dd42018742af68f5889af1afd4e6c9809399987124e56a3b9ae2f20e8173170bc6fc0ad76fb95e2da7b9d385a4037e9ee12011fc02bf8f7e009
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(997): 
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 3us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 700us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 477 ms (468531us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
      

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/boost-core/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:175 (include)

**Comment by Neumann-A** [comment]
@tensor5375 that is a different issue and duplicate to #38974
