### ISSUE TITLE
liblemon installs 1.3.1

### ISSUE THREAD

**Issue by degski** [microsoft/vcpkg#3855]
liblemon installs 1.3.1, and thus lacks a number of important bug-fixes, that are all in trunk. I will contact the lemon maintainers and ask them to now finally push the button and release 1.4.0.

**Comment by degski** [comment]
I have now had a response stating that a new release, is in the making, if that happens I'll open a new issue and close this one.

**Comment by wangli28** [comment]
Hi @degski, thanks for posting this issue! Liblemon has upgrade to 1.3.1.
