### ISSUE TITLE
libpq build failure

### ISSUE THREAD

**Issue by Sbai7** [microsoft/vcpkg#38566]
### Operating system

Windows 11 Pro

### Compiler

MSVC (Visual Studio 2022)

### Steps to reproduce the behavior

```Shell
vcpkg install gdal:x64-windows
```

### Failure logs

-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: D:/develop/vcpkg/downloads/tools/perl/5.38.0.1/perl/bin/perl.exe build.pl DEBUG libpq
    Working Directory: D:/develop/vcpkg/buildtrees/libpq/x64-windows-dbg/src/tools/msvc
    Error code: 1
    See logs for more information:
      D:\develop\vcpkg\buildtrees\libpq\build-libpq-x64-windows-dbg-out.log

Call Stack (most recent call first):
  ports/libpq/build-msvc.cmake:67 (vcpkg_execute_required_process)
  ports/libpq/portfile.cmake:74 (build_msvc)
  scripts/ports.cmake:175 (include)

error: building libpq:x64-windows failed with: BUILD_FAILED
Elapsed time to handle libpq:x64-windows: 28 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libpq
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[libpq]+Build+error+on+x64-windows&body=Copy+issue+body+from+D%3A%2Fdevelop%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by JonLiu1993** [comment]
Please provide error log:
````
D:\develop\vcpkg\buildtrees\libpq\build-libpq-x64-windows-dbg-out.log
````

**Comment by JonLiu1993** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
