### ISSUE TITLE
[New Port Request] MIT Kerberos/krb5

### ISSUE THREAD

**Issue by sharadhr** [microsoft/vcpkg#38576]
### Library name

krb5

### Source repository URL

https://github.com/krb5/krb5

### Project homepage (if different from the source repository)

https://web.mit.edu/kerberos/

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

krb5 has a Kerberos for Windows release as well:

https://web.mit.edu/kerberos/kfw-4.1/kfw-4.1.html

**Comment by dg0yt** [comment]
PR: #38402
