### ISSUE TITLE
Qt5 long path warning is not valid on Linux/macOS

### ISSUE THREAD

**Issue by gladhorn** [microsoft/vcpkg#3858]
CMake Warning at installed/x64-linux/share/qt5modularscripts/qt_modular_library.cmake:6 (message):
  Qt5's buildsystem uses very long paths and may fail on your system.

  We recommend moving vcpkg to a short path such as 'C:\src\vcpkg' or using
  the subst command.
Call Stack (most recent call first):
  ports/qt5-speech/portfile.cmake:5 (qt_modular_library)
  scripts/ports.cmake:71 (include)

Non-Windows handles long paths (at least much longer) just fine. The recommended short path makes little sense ("c:\...").

**Comment by MikeGitb** [comment]
As a related question: Is this still a problem on Win10 if the LongPathsEnabled reg-key is set?

**Comment by JackBoosY** [comment]
In Windows, **MAX_PATH** is **260**. In Linux, **PATH_MAX** is **4096**. In OSX, **PATH_MAX** is **1024**.
So maybe we need to treat it differently?

**Comment by Neumann-A** [comment]
@JackBoosY: can be closed since Qt uses `vcpkg_buildpath_length_warning` which only fires on Windows Hosts

**Comment by JackBoosY** [comment]
@Neumann-A Agreed.
