### ISSUE TITLE
[avcpp] Can't use avcpp with CMake on x64-windows because CMake can't find Threads::Threads

### ISSUE THREAD

**Issue by GOKOP** [microsoft/vcpkg#38582]
**Describe the bug**
As the title says. The build itself is successful so the issue must be in the provided CMake files. On Linux it works

**Environment**
- OS: Windows 11
- Compiler: MSVC 19.37.32822 under Visual Studio Community 2022 17.7.3

**To Reproduce**
Add "avcpp" to vcpkg.json dependencies and in CMakeLists.txt `find_package(avcpp CONFIG REQUIRED)`, then link `avcpp::avcpp` and `avcpp::FFmpeg` to your target. I used it in Visual Studio (opening the project with "open folder") but I expect the same to happen with standalone CMake. I'm using vcpkg in manifest mode as a git submodule

**Expected behavior**
It should work

**Failure logs**
CMake failure:
```
1> [CMake] CMake Error at build/debug/vcpkg_installed/x64-windows/share/avcpp/avcpp-targets.cmake:61 (set_target_properties):
1> [CMake]   The link interface of target "avcpp::avcpp" contains:
1> [CMake] 
1> [CMake]     Threads::Threads
1> [CMake] 
1> [CMake]   but the target was not found.  Possible reasons include:
1> [CMake] 
1> [CMake]     * There is a typo in the target name.
1> [CMake]     * A find_package call is missing for an IMPORTED target.
1> [CMake]     * An ALIAS target is missing.
1> [CMake] 
1> [CMake] Call Stack (most recent call first):
1> [CMake]   build/debug/vcpkg_installed/x64-windows/share/avcpp/avcpp-config.cmake:26 (include)
1> [CMake]   vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
1> [CMake]   CMakeLists.txt:16 (find_package)
```

**Comment by Neumann-A** [comment]
The error means that `avcpp-config.cmake` is missing a call to `find_dependency(Threads)`.

As a workaround you can call `find_package(Threads)` yourself.

**Comment by GOKOP** [comment]
Thanks!

> As a workaround you can call find_package(Threads) yourself.

Now I feel stupid
