### ISSUE TITLE
[log4cpp-log4cpp] build failure on Windows

### ISSUE THREAD

**Issue by bzeb** [microsoft/vcpkg#38585]
### Operating system

Windows

### Compiler

MSCV

### Steps to reproduce the behavior

```Shell
Vcpkg.json

{
	"name": "app",
	"version": "1.0.5",
	"builtin-baseline": "c4af3593e1f1aa9e14a560a09e45ea2cb0dfd74d",
	"dependencies": [
		{
			"name": "log4cpp-log4cpp",
			"version>=": "1.1.4"
}
]
}
```

### Failure logs

error LNK2019: unresolved external symbol "public: __cdecl log4cpp::Appender::AppenderMapStorageInitializer::AppenderMapStorageInitializer(void)" (??0AppenderMapStorageInitializer@Appender@log4cpp@@QEAA@XZ) referenced in function "void __cdecl log4cpp::`dynamic initializer for 'appenderMapStorageInitializer''(void)" (??__EappenderMapStorageInitializer@log4cpp@@YAXXZ)
error LNK2019: unresolved external symbol "public: __cdecl log4cpp::Appender::AppenderMapStorageInitializer::~AppenderMapStorageInitializer(void)" (??1AppenderMapStorageInitializer@Appender@log4cpp@@QEAA@XZ) referenced in function "void __cdecl log4cpp::`dynamic atexit destructor for 'appenderMapStorageInitializer''(void)" (??__FappenderMapStorageInitializer@log4cpp@@YAXXZ)
error LNK2019: unresolved external symbol "public: __cdecl log4cpp::CategoryStream::~CategoryStream(void)" (??1CategoryStream@log4cpp@@QEAA@XZ) referenced in function "public: void __cdecl Logger::log(enum LogLevel,class log4cpp::Category &,char const *,char const *,char *)" (?log@Logger@@QEAAXW4LogLevel@@AEAVCategory@log4cpp@@PEBD2PEAD@Z)
error LNK2019: unresolved external symbol "public: class log4cpp::CategoryStream & __cdecl log4cpp::CategoryStream::operator<<(char const *)" (??6CategoryStream@log4cpp@@QEAAAEAV01@PEBD@Z) referenced in function "public: void __cdecl Logger::log(enum LogLevel,class log4cpp::Category &,char const *,char const *,char *)" (?log@Logger@@QEAAXW4LogLevel@@AEAVCategory@log4cpp@@PEBD2PEAD@Z)
error LNK2019: unresolved external symbol "public: static class log4cpp::Category & __cdecl log4cpp::Category::getRoot(void)" (?getRoot@Category@log4cpp@@SAAEAV12@XZ) referenced in function "public: static void __cdecl Logger::configureLogger(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned __int64,unsigned int)" (?configureLogger@Logger@@SAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0_KI@Z)
error LNK2019: unresolved external symbol "public: static class log4cpp::Category & __cdecl log4cpp::Category::getInstance(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?getInstance@Category@log4cpp@@SAAEAV12@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function "public: static class log4cpp::Category & __cdecl Logger::getCategory(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?getCategory@Logger@@SAAEAVCategory@log4cpp@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
error LNK2019: unresolved external symbol "public: static class log4cpp::Category * __cdecl log4cpp::Category::exists(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?exists@Category@log4cpp@@SAPEAV12@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function "public: static class log4cpp::Category & __cdecl Logger::getCategory(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?getCategory@Logger@@SAAEAVCategory@log4cpp@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
error LNK2019: unresolved external symbol "public: __cdecl log4cpp::RollingFileAppender::RollingFileAppender(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned __int64,unsigned int,bool,int)" (??0RollingFileAppender@log4cpp@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0_KI_NH@Z) referenced in function "public: static void __cdecl Logger::configureLogger(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned __int64,unsigned int)" (?configureLogger@Logger@@SAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0_KI@Z)
error LNK2019: unresolved external symbol "public: __cdecl log4cpp::PatternLayout::PatternLayout(void)" (??0PatternLayout@log4cpp@@QEAA@XZ) referenced in function "class log4cpp::PatternLayout * __cdecl createLayout(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?createLayout@@YAPEAVPatternLayout@log4cpp@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
error LNK2019: unresolved external symbol "public: __cdecl log4cpp::OstreamAppender::OstreamAppender(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_ostream<char,struct std::char_traits<char> > *)" (??0OstreamAppender@log4cpp@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAV?$basic_ostream@DU?$char_traits@D@std@@@3@@Z) referenced in function "public: static void __cdecl Logger::configureLogger(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned __int64,unsigned int)" (?configureLogger@Logger@@SAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0_KI@Z)

  

### Additional context

There is no .lib file for log4cpp in \out\build\x64-Debug\vcpkg_installed\x64-windows\lib\

**Comment by Cheney-W** [comment]
I can't reproduce this issue in my side with a new vcpkg and the vcpkg.json you provided.
Env:
vcpkg: version 2024-04-23-d6945642ee5c3076addd1a42c331bbf4cfc97457
VS: VS2022 17.9.6

**Comment by bzeb** [comment]
I currently don't have this library added in the CMakeLists.txt file because find_package doesn't find log4cpp. It works on Linux, and I have:

if(NOT WIN32)
	find_package(PkgConfig)
	pkg_check_modules(log4cpp REQUIRED IMPORTED_TARGET log4cpp)

	target_link_libraries(core PRIVATE PkgConfig::log4cpp)
else()
endif()

**Comment by bzeb** [comment]
I have the following versions:
VS: VS2022 17.9.6
vcpkg package management program version 2024-04-23-d6945642ee5c3076addd1a42c331bbf4cfc97457
cmake version 3.29.2
 and CMakeSettings.json:

{
  "configurations": [
    {
      "name": "x64-Debug",
      "generator": "Ninja",
      "configurationType": "Debug",
      "buildRoot": "${projectDir}\\out\\build\\${name}",
      "installRoot": "${projectDir}\\out\\install\\${name}",
      "cmakeCommandArgs": "",
      "buildCommandArgs": "",
      "ctestCommandArgs": "",
      "inheritEnvironments": [ "msvc_x64_x64" ],
      "variables": [
      ]
    },
