### ISSUE TITLE
[gl3w] Support extension loading.

### ISSUE THREAD

**Issue by sidy3d** [microsoft/vcpkg#38588]
### Is your feature request related to a problem? Please describe.

The gl3w library also supports generating functions for loading OpenGL extensions, currently this functionality is not exposed in the port available through vcpkg.

### Proposed solution

Using gl3w with OpenGL extensions can be enabled by passing `--ext` to the generation script `gl3w_gen.py`. This should be enabled through an optional feature.

**Comment by FrankXie05** [comment]
@sidy3d Thanks for posting this issue, could you please provide an official explanation? ：）
