### ISSUE TITLE
qt5 does not build on Linux

### ISSUE THREAD

**Issue by gladhorn** [microsoft/vcpkg#3859]
The qt5 ports disable static linkage (it should work in theory at least, but maybe it requires a version bump to a newer release). Building on Linux with dynamic linkage by creating a new triplet fails on sqlite3.

**Comment by JackBoosY** [comment]
Hi @gladhorn, thanks for reporting this issue!
I've fixed qt5-linux build, please update vcpkg and rebuild qt5.

Thanks.
