### ISSUE TITLE
[libpq] build failure on x64-windows

### ISSUE THREAD

**Issue by QiuYilin** [microsoft/vcpkg#38626]
### Operating system

Windows 11

### Compiler

MSVC 2019

### Steps to reproduce the behavior

```Shell
error happend while mainfest intalling after I uninstalled VS2022 and reinstalled VS2019.
```

### Failure logs

log:

```
cmake] CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
[cmake]     Command failed: E:/src/vcpkg/downloads/tools/perl/5.38.0.1/perl/bin/perl.exe build.pl DEBUG libpq
[cmake]     Working Directory: E:/src/vcpkg/buildtrees/libpq/x64-windows-dbg/src/tools/msvc
[cmake]     Error code: 255
[cmake]     See logs for more information:
[cmake]       E:\src\vcpkg\buildtrees\libpq\build-libpq-x64-windows-dbg-err.log
[cmake] 
[cmake] Call Stack (most recent call first):
[cmake]   C:/Users/user.QIUYILIN-L1/AppData/Local/vcpkg/registries/git-trees/cbd6314cbfd04132985a7a6412184d368c3cd0b6/build-msvc.cmake:67 (vcpkg_execute_required_process)
[cmake]   C:/Users/user.QIUYILIN-L1/AppData/Local/vcpkg/registries/git-trees/cbd6314cbfd04132985a7a6412184d368c3cd0b6/portfile.cmake:75 (build_msvc)
[cmake]   scripts/ports.cmake:175 (include)
```

error in log:

`Unable to determine Visual Studio version: The nmake version could not be determined. at E:/src/vcpkg/buildtrees/libpq/x64-windows-dbg/src/tools/msvc/Mkvcbuild.pm line 97.`

**Comment by ACE199704** [comment]
![image](https://github.com/microsoft/vcpkg/assets/23281568/2f939b96-7896-449f-b48b-fc98dd23b3f5)
看一下你的SDK是不是有重复装的，只能一个，把另一个删了就行。。。【试了一下午orz】

**Comment by QiuYilin** [comment]
@ACE199704 谢谢提醒，确实是这个问题，我发现编译时一直在找被卸载的VS2022的win11 sdk。

**Comment by WangWeiLin-MV** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by QiuYilin** [comment]
Additional note: The remaining sdk needs to be manually deleted from Windows app.
