### ISSUE TITLE
attempted to us vcpkg to install tiff

### ISSUE THREAD

**Issue by mjtrac** [Microsoft/vcpkg#3862]
Attempting to use vcpkg to install tiff yields the following output:

PS C:\Users\mtrachtenberg\vcpkg> .\vcpkg.exe remove tiff
The following packages are not installed, so not removed:
    tiff:x86-windows
Package tiff:x86-windows is not installed
Purging package tiff:x86-windows...
Purging package tiff:x86-windows... done
PS C:\Users\mtrachtenberg\vcpkg> .\vcpkg.exe install tiff
The following packages will be built and installed:
    tiff[core]:x86-windows
Starting package 1/1: tiff:x86-windows
Building package tiff[core]:x86-windows...
-- Using cached C:/Users/mtrachtenberg/vcpkg/downloads/tiff-4.0.9.tar.gz
-- Applying patch C:/Users/mtrachtenberg/vcpkg/ports/tiff/add-component-options.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/Users/mtrachtenberg/vcpkg/ports/tiff/fix-cxx-shared-libs.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/Users/mtrachtenberg/vcpkg/ports/tiff/crt-secure-no-deprecate.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: C:/Users/mtrachtenberg/vcpkg/buildtrees/tiff/x86-windows-rel/vcpkg-parallel-configure
    See logs for more information:
      C:\Users\mtrachtenberg\vcpkg\buildtrees\tiff\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:240 (vcpkg_execute_required_process)
  ports/tiff/portfile.cmake:25 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package tiff:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: tiff:x86-windows
  Vcpkg version: 0.0.113-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by Voskrese** [comment]
> See logs for more information:
> C:\Users\mtrachtenberg\vcpkg\buildtrees\tiff\config-x86-windows-out.log

**Comment by PhoebeHui** [comment]
@mjtrac , does the issue persist? I can install tiff:x86-windows successfully now. if the issue occurred, could you provide .\vcpkg\buildtrees\tiff\config-x86-windows-out.log?

PS F:\vcpkg\src> ./vcpkg version
Vcpkg package management program version 2018.11.23-nohash

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
