### ISSUE TITLE
Add the support of HDF4, HDF5 and netCDF in GDAL

### ISSUE THREAD

**Issue by jiaozhh** [microsoft/vcpkg#3863]
I use Windows 10 x64 with the latest update. I hope that the file formats of HDF4, HDF5 and netCDF could be supported by gdal::x64-windows 2.3.0. This can make it more practical when processing remote sensing data.

**Comment by NancyLi1013** [comment]
Hi @jiaozhh 
Thanks for posting this issue.
`gdal` has the dependencies of `hdf5` and `netcdf-c` in vcpkg. Does this current status meet your demand?

**Comment by jiaozhh** [comment]
Thank you very much for your hard work. GDAL in vcpkg is better.

**Comment by IfremerUnderwater** [comment]
Hi all, this issue has been marked as fixed but it seems that even if the gdal package has the netcdf dependencies it is still impossible to open netcdf format. Gdalinfo tell the format is not recognized while on linux default installation the same file is recognized. Thank you for any help

**Comment by NancyLi1013** [comment]
@IfremerUnderwater 

Thanks for posting this issue. Factually, this original issue is about the support `hdf5 `and `netcdf`. In this point, it is solved. But for the usage, we might need to fix it in another PR. Please open a new issue to report the problem you encountered if it is a problem in vcpkg side.
