### ISSUE TITLE
[boost-winapi] Build error on wasm32-emscripten

### ISSUE THREAD

**Issue by tekinas** [microsoft/vcpkg#38640]
Package: boost-winapi:wasm32-emscripten@1.84.0#1

**Host Environment**

- Host: x64-linux
- Compiler: Clang 19.0.0
-    vcpkg-tool version: 2024-04-23-d6945642ee5c3076addd1a42c331bbf4cfc97457
    vcpkg-scripts version: b323a599 2024-05-07 (13 hours ago)

**To Reproduce**

`vcpkg install boost:wasm32-emscripten`

**Failure logs**

```
-- Using cached boostorg-winapi-boost-1.84.0.tar.gz.
-- Cleaning sources at /home/tekinas/Documents/vcpkg/buildtrees/boost-winapi/src/ost-1.84.0-45e8b75ad4.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/tekinas/Documents/vcpkg/downloads/boostorg-winapi-boost-1.84.0.tar.gz
-- Using source at /home/tekinas/Documents/vcpkg/buildtrees/boost-winapi/src/ost-1.84.0-45e8b75ad4.clean
CMake Error at ports/boost-winapi/portfile.cmake:12 (boost_configure_and_install):
  Unknown CMake command "boost_configure_and_install".
Call Stack (most recent call first):
  scripts/ports.cmake:175 (include)



```

**Comment by Osyotr** [comment]
Mixed installed tree: please reinstall boost (`vcpkg remove boost-uninstall:wasm32-emscripten --recurse` + `boost-winapi:wasm32-emscripten`) or remove `installed/` dir.
