### ISSUE TITLE
x-update-baseline does not respect reference (git branch)

### ISSUE THREAD

**Issue by tobylane** [microsoft/vcpkg#38701]
**Describe the bug**
Updating the baseline in vcpkg-configuration.json ignores the reference. If another commit in the repository is newer. even in another branch (or only main?) it is used.

**Environment**
Not OS specific

**To Reproduce**
1. Download https://github.com/tobylane/CorsixTH/blob/06316899e5daf04ff0fd344443d0b64d50723fbc/vcpkg-configuration.json
2. `vcpkg x-update-baseline --dry-run`
3.  See the line "updated registry 'https://github.com/TheCycoONE/vcpkg-registry': baseline '15529ddf98c6ae963861c7fdc145c969d666aadf' -> '7e2920647c0c00b21d684c887d2c9b375a1b5b32'"

**Expected behavior**
It should respect the reference. The commit starting 15529dd is the [head of that branch](https://github.com/TheCycoONE/vcpkg-registry/tree/lua_cmake) and does not need changing.

**Additional context**
The alternative I have is below, but I think `x-update`baseline` should do this by default, as it's the least surprising option. Switching to another reference (ie changing branch to main) should be behind an option.

```bash
          newsha="$(curl -s https://api.github.com/repos/microsoft/vcpkg/git/refs/heads/master | jq '.object.sha')"
          jq '."default-registry".baseline = '$newsha vcpkg-configuration.json > tmp
          mv tmp vcpkg-configuration.json
```

edit: I don't know this program or cpp, but should HEAD be here? https://github.com/microsoft/vcpkg-tool/blob/main/src/vcpkg/configuration.cpp#L695

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. I use command `git rev-parse HEAD` to get the latest commit ID of the repo https://github.com/TheCycoONE/vcpkg-registry/tree/lua_cmake, the latest commit ID is `7e2920647c0c00b21d684c887d2c9b375a1b5b32`.
![image](https://github.com/microsoft/vcpkg/assets/94091114/f84d1bcf-5c52-4b4d-a3ea-e71cb749d352)

**Comment by tobylane** [comment]
[From docs for reference](https://learn.microsoft.com/en-us/vcpkg/reference/vcpkg-configuration-json#registry-reference)

> The Git reference used to list available versions of a [Git Registry](https://learn.microsoft.com/en-us/vcpkg/maintainers/registries#git-registries). A string. Optional. If not specified, defaults to HEAD. This field can be a topic branch to access versions that are not yet fully published.

It sounds like reference is used here to identify an alternative version, in another branch. The `git rev-parse` command needs the reference if it exists, or HEAD.

**Comment by LilyWangLL** [comment]
I switched to branch `lua_cmake`, then used command `git rev-parse HEAD` to get the latest commit of that branch, the value is `15529ddf98c6ae963861c7fdc145c969d666aadf`. I checked the code on the vcpkg-tool, and it seems that the case where the keyword `reference` is a branch is not handled. I have temporarily marked this issue as Vcpkg bug.

cc on call manger @data-queue and @BillyONeal, could you please take a look this issue?
