### ISSUE TITLE
sqlite3[dbstat] doesn't enable dbstat actually.

### ISSUE THREAD

**Issue by veawor** [microsoft/vcpkg#38700]
**Describe the bug**
After `vcpkg.exe install sqlite3[dbstat]` , use sqlite3_compileoption_used("SQLITE_ENABLE_DBSTAT_VTAB") to test if the feature is built-in. However, the function returns false.

**Environment**
- OS: Windows
- Compiler: Microsoft Visual C++ 2022

**To Reproduce**
1. vcpkg.exe install sqlite3[dbstat]
2. Use sqlite3_compileoption_used("SQLITE_ENABLE_DBSTAT_VTAB") to test if return true.

**Expected behavior**
sqlite3_compileoption_used("SQLITE_ENABLE_DBSTAT_VTAB") shall return true.

**Failure logs**
N/A

**Additional context**
N/A

**Comment by Osyotr** [comment]
#30432 missed crucial change in the configuration header
https://github.com/microsoft/vcpkg/blob/ aster/ports/sqlite3/sqlite3-vcpkg-config.h.in
