### ISSUE TITLE
isuue with nanorange

### ISSUE THREAD

**Issue by MicheleBe** [Microsoft/vcpkg#3870]
The following packages will be built and installed:
    nanorange[core]:x64-windows
Starting package 1/1: nanorange:x64-windows
Building package nanorange[core]:x64-windows...
CMake Error at scripts/cmake/vcpkg_from_github.cmake:97 (message):
  Package does not specify REF.  It must built using --head.
Call Stack (most recent call first):
  ports/nanorange/portfile.cmake:4 (vcpkg_from_github)
  scripts/ports.cmake:71 (include)

Error: Building package nanorange:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: nanorange:x64-windows
  Vcpkg version: 0.0.113-nohash

**Comment by Voskrese** [comment]
>  Package does not specify REF. It must built using --head.

` nanorange[core]:x64-windows --head`

**Comment by Voskrese** [comment]
`echo 'Acquire::ForceIPv4 "true";' | sudo tee /etc/apt/apt.conf.d/99force-ipv4`

`apt-get -o Acquire::ForceIPv4=true update`

`Acquire::ForceIPv4 and Acquire::ForceIPv6`

`apt.conf` to write `Acquire::ForceIPv4 "true";`


`host security.debian.org`

> security.debian.org has address 212.211.132.250
> security.debian.org has address 217.196.149.233
> security.debian.org has IPv6 address 2a02:16a8:dc41:100::233
> security.debian.org has IPv6 address 2001:a78:5:1:216:35ff:fe7f:6ceb
> security.debian.org mail is handled by 10 mailly.debian.org.
> security.debian.org mail is handled by 10 muffat.debian.org.

`host www.ripe.net`

> www.ripe.net has address 193.0.6.139
> www.ripe.net has IPv6 address 2001:67c:2e8:22::c100:68b

http://ru.manpages.org/gaiconf/5

https://version6.ru/deprefer-ipv6

Prefer IPV4, edit `nano /etc/gai.conf`

`precedence ::ffff:0:0/96  100`

Prefer IPV6 for specific hosts

`precedence 2001:470::/96 100`

http proxy

edit `nano /etc/apt/apt.conf.d/90httpproxy`

`Acquire::http { Proxy "http://[192.168.1.254]:3142"; };`

edit `nano /etc/hosts`

> 130.89.149.226  ftp.debian.org      
> 195.20.242.89   security.debian.org 

http proxy

edit `nano /etc/apt/apt.conf`

> Acquire::http::proxy "http://192.168.1.10:7777/";
> Acquire::http::Timeout "10";
> Acquire::ftp::Timeout "10";

https://github.com/jblakeman/apt-select

https://blog.kmonsoor.com/ubuntu-update-apt-get-server-to-use-fastest-mirror/
