### ISSUE TITLE
Bootstrapping....

### ISSUE THREAD

**Issue by Darth-Verd** [Microsoft/vcpkg#3874]
I'm having some issues to install libraries for 64-bit (x64) build (using windows 7)
![teste](https://user-images.githubusercontent.com/41042943/42493842-d4a6a91e-83f4-11e8-814d-145ad2cfe518.png)

Honestly, this is my very first post here! I just got introduced in GitHub some days ago. I feel I'm figure out some things, but I know that's a scratch in the surface! So I'll do my best to catch up to your answer

**Comment by degski** [comment]
You don't show what command triggered this error!

**Comment by ras0219-msft** [comment]
Hi @Darth-Verd, thanks for posting this issue!

There will be additional information about the failures inside the error log paths:

>buildtrees\boost-build\bootstrap-x64-windows-out.log
>buildtrees\boost-build\bootstrap-x64-windows-err.log

Could you post these to this issue?

**Comment by Darth-Verd** [comment]
@degski this one triggered the error! `.\vcpkg install boost-iostreams:x64-windows boost-asio:x64-windows boost-system:x64-windows boost-variant:x64-windows boost-lockfree:x64-windows luajit:x64-windows libmariadb:x64-windows pugixml:x64-windows mpir:x64-windows`

The previous commands
```
git clone https://github.com/Microsoft/vcpkg
cd vcpkg
.\bootstrap-vcpkg.bat
.\vcpkg integrate install
```

@ras0219-msft sure
[bootstrap-x64-windows-err.log](https://github.com/Microsoft/vcpkg/files/2186448/bootstrap-x64-windows-err.log)
[bootstrap-x64-windows-out.log](https://github.com/Microsoft/vcpkg/files/2186449/bootstrap-x64-windows-out.log)

**Comment by degski** [comment]
@Darth-Verd 

You installation of VS cannot be found, neither by Boost.Build nor .\vcpkg.

Run `.\vcpkg install <packages>` from Windows Developer Command Prompt, to be found in the windows menu (push the windows button) and pick the x64 native one, then proceed as you did.

If you build this config all the time, I suggest to set (globally) in your system a (you have to create it) VCPKG_DEFAULT_TRIPLET=x64-windows (then you don't need to do that every time and will have consistent builds, by definition).

**Comment by Darth-Verd** [comment]
@degski Do you mean run all the commands from x64 Native Tools Command Prompt for VS 2017?
Because I did and found the same error.
I started again from C:\Program Files (x86)\Microsoft Visual Studio\2017\Community> and followed the instroctions

I don't think I'll need to do this all the time, once done I'm good to go, but your advice could be useful in the future, thanks!

**Comment by degski** [comment]
@Darth-Verd 

> Because I did and found the same error.

But surely if you open  `x64 Native Tools Command Prompt for VS 2017` you **must** be able to run just cl from there!

    C:\Windows\System32>cl
    Microsoft (R) C/C++ Optimizing Compiler Version 19.14.26433 for x64
    Copyright (C) Microsoft Corporation.  All rights reserved.

    usage: cl [ option... ] filename... [ /link linkoption... ]

**Comment by Darth-Verd** [comment]
@degski solved! Thank you very much for your attention and patience!
