### ISSUE TITLE
[New Port Request] <GmSSL>

### ISSUE THREAD

**Issue by wangdschina** [microsoft/vcpkg#38745]
### Library name

GmSSL

### Library description

GmSSL是由北京大学自主开发的国产商用密码开源库，实现了对国密算法、标准和安全通信协议的全面功能覆盖，支持包括移动端在内的主流操作系统和处理器，支持密码钥匙、密码卡等典型国产密码硬件，提供功能丰富的命令行工具及多种编译语言编程接口。

### Source repository URL

https://github.com/guanzhi/GmSSL

**Comment by sfhacker** [comment]
Disgusting!
