### ISSUE TITLE
jluna: A modern Julia Wrapper for C++ (v1.0.0)

### ISSUE THREAD

**Issue by eclipseyin147** [microsoft/vcpkg#38747]
### Library name

jluna

### Source repository URL

https://github.com/Clemapfel/jluna

**Comment by Neumann-A** [comment]
Would require Julia first. 

Julia however is unbuildable due to the LLVM version requirement and not being natively compile able with MSVC. 
(and the Julia build is all hardcoded Makefiles so that makes is especially fun)

**Comment by kannode** [comment]
I would support this port.
