### ISSUE TITLE
[<port name>] build failurebootstrap-vcpkg.bat errors

### ISSUE THREAD

**Issue by Norldis** [microsoft/vcpkg#38769]
### Operating system

windows 7

### Steps to reproduce the behavior

```Shell
bootstrap-vcpkg.bat
```

### Failure logs

Произошла ошибка при вызове метода, так как [System.String] не содержит метод с именем "IsNullOrWhiteSpace".

**Comment by FrankXie05** [comment]
See https://github.com/microsoft/vcpkg/issues/16207

**Comment by FrankXie05** [comment]
This issue hasn’t been updated for a long time; if it is still an issue, please ping me and I will reopen this issue.
