### ISSUE TITLE
zeromq windows: does not deploy lib/dll properly

### ISSUE THREAD

**Issue by TheHugeManatee** [Microsoft/vcpkg#3876]
When installing zeromq, the library gets built but the respective dll and lib are not copied to the appropriate directories after build. They exist in the build tree but are missing in the installed packages folder, neither does the dll automatically get deployed to an application that links to it.

Environment: 
Windows 10, Visual Studio 2017 15.7.4. Latest vcpkg master branch.

**Comment by PhoebeHui** [comment]
Hi TheHugeManatee,

Thanks for posting this issue, I checked the lib/dll under build tree and installed packages folder, please reopen it if the issue still persists.

PS F:\vcpkg\src> .\vcpkg version
Vcpkg package management program version 2018.11.23-nohash

Thanks,
Phoebe
