### ISSUE TITLE
[gdal] cannot open file 'gdal_i.lib'

### ISSUE THREAD

**Issue by sbheinric** [microsoft/vcpkg#38795]
### Operating system

Windows 10 Enterprise

### Compiler

MSVC Community 2022 (64-bit)

### Steps to reproduce the behavior

```Shell
1) Initialize a new hello world repo like this:
https://learn.microsoft.com/en-us/vcpkg/get_started/get-started-vs?pivots=shell-cmd

2) Add GDAL port:
vcpkg add port GDAL

3) Then add GDAL as a dependency in the Cmake:

CMakeLists.txt:
cmake_minimum_required(VERSION 3.10)

project(HelloWorld)

find_package(fmt CONFIG REQUIRED)
find_package(GDAL CONFIG REQUIRED)

add_executable(HelloWorld helloworld.cpp)

target_link_libraries(HelloWorld PRIVATE fmt::fmt GDAL::GDAL)

4) Build
```

### Failure logs

>------ Build All started: Project: helloworld, Configuration: default ------
  [1/1] Linking CXX executable HelloWorld.exe
  FAILED: HelloWorld.exe 
  cmd.exe /C "cd . && "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\HelloWorld.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1437~1.328\bin\Hostx64\x64\link.exe /nologo CMakeFiles\HelloWorld.dir\helloworld.cpp.obj  /out:HelloWorld.exe /implib:HelloWorld.lib /pdb:HelloWorld.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console  vcpkg_installed\x64-windows\debug\lib\fmtd.lib  vcpkg_installed\x64-windows\debug\lib\gdald.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cmd.exe /C "cd /D C:\Users\USERNAME\repos\helloworld\build && C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noprofile -executionpolicy Bypass -file C:/Users/USERNAME/repos/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/Users/USERNAME/repos/helloworld/build/HelloWorld.exe -installedDir C:/Users/USERNAME/repos/helloworld/build/vcpkg_installed/x64-windows/debug/bin -OutVariable out""
  LINK Pass 1: command "C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1437~1.328\bin\Hostx64\x64\link.exe /nologo CMakeFiles\HelloWorld.dir\helloworld.cpp.obj /out:HelloWorld.exe /implib:HelloWorld.lib /pdb:HelloWorld.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console vcpkg_installed\x64-windows\debug\lib\fmtd.lib vcpkg_installed\x64-windows\debug\lib\gdald.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\HelloWorld.dir/intermediate.manifest CMakeFiles\HelloWorld.dir/manifest.res" failed (exit code 1104) with the following output:
C:\Users\USERNAME\repos\helloworld\build\LINK : fatal error LNK1104: cannot open file 'gdal_i.lib'
  
  ninja: build stopped: subcommand failed.

Build All failed.

**Comment by dg0yt** [comment]
> > C:\Users\USERNAME\repos\helloworld\build\LINK : fatal error LNK1104: cannot open file 'gdal_i.lib'

Where should this come from? The command line passes `vcpkg_installed\x64-windows\debug\lib\gdald.lib`. Show your code...

**Comment by sbheinric** [comment]
Problem has been solved, I found the following offending line hardcoded in some of our library code:

#pragma comment(lib, "gdal_i.lib" )

**Comment by dg0yt** [comment]
> #pragma comment(lib, "gdal_i.lib" )

Yeah, that's what I expected.
