### ISSUE TITLE
vcpkg install armadillo:x64-windows

### ISSUE THREAD

**Issue by kimsijin33** [microsoft/vcpkg#38792]
I tried below code.
vcpkg install armadillo:x64-windows

and occured below error messages 

error: building openblas:x64-windows failed with: BUILD_FAILED
Elapsed time to handle openblas:x64-windows: 20 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openblas
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[openblas]+Build+error&body=Copy+issue+body+from+C%3A%2FDEV%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

please help me

**Comment by StarGate-One** [comment]
See #30604 on how to report a build failure.

**Comment by MonicaLiu0311** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
