### ISSUE TITLE
Failed code compilation including CLI11.hpp

### ISSUE THREAD

**Issue by gdidomenico** [microsoft/vcpkg#38804]
**Describe the bug**
I have tried to compile the first CLI11 example  but It failed

**Environment**
- OS: Windows 64 bits
- Compiler: MSVC 143 VS 2022

**To Reproduce**
1. ./vcpkg install CLI11 --triplet=x64-windows
2. See error: 
the error C1083 has been generated:
 It is not possible to include : 'impl/Encoding_inl.hpp': No such file or directory	
3. Example code
//+++++++++++++++++++++++++++++
#include "CLI/CLI.hpp"
#include <iostream>

int main(int argc, char** argv) {
    CLI::App app{ "App description" };

    // Define options
    int p = 0;
    app.add_option("-p", p, "Parameter");

    CLI11_PARSE(app, argc, argv);

    std::cout << "Parameter value: " << p << std::endl;
    return 0;
}
//++++++++++++++++++++++++++++
**Expected behavior**
The code must compile

**Comment by dg0yt** [comment]
You are not using CMake... So you must manually add `CLI11_COMPILE` to the definitions when using cli11 at the moment.

**Comment by jimwang118** [comment]
You need to add a cmakelists.txt and call cli11 through the following statement.
```
  find_package(CLI11 CONFIG REQUIRED)
  target_link_libraries(main PRIVATE CLI11::CLI11)
```
