### ISSUE TITLE
[glib] Build error on x64-linux

### ISSUE THREAD

**Issue by andok1388** [microsoft/vcpkg#38813]
error: building glib:x64-linux failed with: BUILD_FAILED
Elapsed time to handle glib:x64-linux: 19 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+glib
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[glib]+Build+error+on+x64-linux&body=Copy+issue+body+from+%2Fhome%2Fjohnsmile%2Fprojects%2Fzing%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by JonLiu1993** [comment]
Please provide error log, thanks.

**Comment by JonLiu1993** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
