### ISSUE TITLE
bootstrap does not find msvc

### ISSUE THREAD

**Issue by lucidbee** [Microsoft/vcpkg#3881]
I saw there was an issue on this that was resolved. Unlike that, I have vswhere installed and it is on my path. 

- The first image shows the error. 
- The second image shows the output of vswhere in the context in which I ran the bootstrapper. 

The compiler is listed and it looks right to me but I could be missing something. 
![capture1](https://user-images.githubusercontent.com/7990726/42532463-d444d90e-843b-11e8-91ee-395a704d0694.PNG)
![capture2](https://user-images.githubusercontent.com/7990726/42532475-daf4e6ae-843b-11e8-8aed-23b5a16bc3b1.PNG)

**Comment by degski** [comment]
Yes till yesterday, this was the latest stable. You do mean to say, that you executed the bootstrap batch file from the vc-command prompt, no? If yes, I don't see any error in you method, which does not solve the problem, but you're doing it right, IMO.

**Comment by ras0219-msft** [comment]
Hi @lucidbee, thanks for posting this issue!

We directly look for vswhere.exe in the VS2017 installer's location, not the path, though that might be a good place to look as well!

Can you run the internal powershell bootstrap in verbose mode to get more information?

>`C:\vcpkg\scripts\bootstrap.ps1 -verbose`

Specifically, we are calling

```
"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -prerelease -legacy -products * -format xml
```

**Comment by wangli28** [comment]
Please open a new issue if this is still a problem for you.
