### ISSUE TITLE
[protobuf] Build with -fPIC on Linux

### ISSUE THREAD

**Issue by kya8** [microsoft/vcpkg#38836]
### Is your feature request related to a problem? Please describe.

I get the follow error when linking static `protobuf` into a shared library:
> /usr/bin/ld: /home/user/vcpkg/installed/x64-linux/lib/libprotobuf.a(arena.cc.o): relocation R_X86_64_TPOFF32 against symbol `_ZN6google8protobuf8internal15ThreadSafeArena13thread_cache_E' can not be used when making a shared object; recompile with -fPIC 

It looks like `protobuf` wasn't built as position independent code. Or am I missing some linker flags required to make it work?

### Proposed solution

`protobuf` should be built as PIC on Linux, so it can be used in shared libraries.

Adding `-DCMAKE_POSITION_INDEPENDENT_CODE=ON` to `protobuf/portfile.cmake` seems to work for me. But I'm not sure if this is the right way of doing things.

### Additional context

My vcpkg ports version is tag 2023.12.12

**Comment by Osyotr** [comment]
Default vcpkg toolchain already adds `-fPIC`.
https://github.com/microsoft/vcpkg/blob/261dd6831673d3b07e5118261f7e161a21d1a759/scripts/toolchains/linux.cmake#L55

**Comment by kya8** [comment]
> Default vcpkg toolchain already adds `-fPIC`.
> 
> https://github.com/microsoft/vcpkg/blob/261dd6831673d3b07e5118261f7e161a21d1a759/scripts/toolchains/linux.cmake#L55

I just rebuilt `protobuf` in vcpkg with default options, and it linked without errors. I might have mixed libraries that were compiled earlier... 🥲
Closing this for now, until I find another cause of the issue.

Thank you for answering!
