### ISSUE TITLE
Building package hdf5:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by mkm-GitHub** [Microsoft/vcpkg#3885]
Package: hdf5:x64-windows
Vcpkg version: 0.0.113-nohash

### Log:
Building package hdf5[core]:x64-windows...
-- Downloading https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.1
0.1/src/CMake-hdf5-1.10.1.zip...
-- Downloading https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.1
0.1/src/CMake-hdf5-1.10.1.zip... Failed. Status: 35;"SSL connect error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:151 (message):

**Comment by mkm-GitHub** [comment]
Could someone help me on this issue?

**Comment by PhoebeHui** [comment]
This issue doesn't repro now, please file a new issue if the problem persists.
