### ISSUE TITLE
pugixml debug lib not found

### ISSUE THREAD

**Issue by smonasco** [Microsoft/vcpkg#3886]
I'm getting the following:

CMake Error at build_2017/vcpkg-export-20180711-074947/installed/x64-windows/sha
re/pugixml/pugixml-config.cmake:74 (message):
  The imported target "pugixml" references the file

     "C:/code/gitkraken/code/c++/build_2017/vcpkg-export-20180711-074947/install
ed/x64-windows/debug/lib/pugixml.lib"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "C:/code/gitkraken/code/c++/build_2017/vcpkg-export-20180711-074947/install
ed/x64-windows/share/pugixml/pugixml-config.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  build_2017/vcpkg-export-20180711-074947/scripts/buildsystems/vcpkg.cmake:247 (
_find_package)
  CMakeLists.txt:94 (find_package)

It looks like pugixml-config-debug.cmake is looking for pugixml.lib but should be looking for pugixmld.lib

I changed lines 12 and 16 of pugixml-config-debug.cmake to reference pugixmld.lib and it worked on my machine.

**Comment by smonasco** [comment]
If you want to point me to which file in which git repo (this one or pugixml) I should fork, fix, pull request and merge the change, I'd be happy to do all that.

**Comment by PhoebeHui** [comment]
Hi smonasco,

Does the issue still persist?

I installed pugixml:x64-windows, and ".\VCPKG\src\installed\x64-windows\debug\lib\pugixml.lib successfully installed.

PS F:\vcpkg\src> ./vcpkg install pugixml:x64-windows
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be built and installed:
    pugixml[core]:x64-windows
Starting package 1/1: pugixml:x64-windows
Building package pugixml[core]:x64-windows...
-- Using cached F:/VCPKG/src/downloads/zeux-pugixml-v1.9.tar.gz
-- Using source at F:/VCPKG/src/buildtrees/pugixml/src/v1.9-b1b3e70dc2
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: F:/VCPKG/src/packages/pugixml_x64-windows/share/pugixml/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package pugixml[core]:x64-windows... done
Installing package pugixml[core]:x64-windows...
Installing package pugixml[core]:x64-windows... done
Elapsed time for package pugixml:x64-windows: 27.03 s

Total elapsed time: 27.03 s

The package pugixml:x64-windows provides CMake targets:

    find_package(pugixml CONFIG REQUIRED)
    target_link_libraries(main PRIVATE pugixml)

Thanks,
Phoebe

**Comment by smonasco** [comment]
Looks like this is working
