### ISSUE TITLE
[libffi] Build error on x64-windows

### ISSUE THREAD

**Issue by Yoshi-OOF** [microsoft/vcpkg#38881]
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "B:/Enzo/Desktop/Rocket League/RLMarlbot-master/MemoryWriter/vcpkg/downloads/tools/msys2/09133458fed80fcb/usr/bin/bash.exe" --noprofile --norc --debug -c "V=1 CPP='compile cl.exe -E' CC='compile cl.exe' CC_FOR_BUILD='compile cl.exe' CPP_FOR_BUILD='compile cl.exe -E' CXX_FOR_BUILD='compile cl.exe' CXX='compile cl.exe' RC='windres-rc rc.exe' WINDRES='windres-rc rc.exe' AR='ar-lib lib.exe' LD='link.exe -verbose' RANLIB=':' STRIP=':' NM='dumpbin.exe -symbols -headers' DLLTOOL='link.exe -verbose -dll' CCAS=':' AS=':' ./../src/libffi-3-5867c437e9.clean/configure --build=x86_64-pc-mingw32 \"--enable-portable-binary\" \"--disable-docs\" \"--disable-multi-os-directory\" \"CFLAGS=${CFLAGS} -DFFI_BUILDING_DLL\" \"CCAS=msvcc.sh -m64\" \"ac_cv_prog_ac_ct_STRIP=:\" \"gl_cv_double_slash_root=yes\" \"ac_cv_func_memmove=yes\" \"--disable-silent-rules\" \"--verbose\" \"--enable-shared\" \"--disable-static\" \"--prefix=/B/Enzo/Desktop/Rocket League/RLMarlbot-master/MemoryWriter/vcpkg/installed/x64-windows/debug\" \"--bindir=\\${prefix}/../tools/libffi/debug/bin\" \"--sbindir=\\${prefix}/../tools/libffi/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/libffi\""
    Working Directory: B:/Enzo/Desktop/Rocket League/RLMarlbot-master/MemoryWriter/vcpkg/buildtrees/libffi/x64-windows-dbg
    Error code: 77
    See logs for more information:
      B:\Enzo\Desktop\Rocket League\RLMarlbot-master\MemoryWriter\vcpkg\buildtrees\libffi\config-x64-windows-dbg-config.log
      B:\Enzo\Desktop\Rocket League\RLMarlbot-master\MemoryWriter\vcpkg\buildtrees\libffi\config-x64-windows-dbg-out.log
      B:\Enzo\Desktop\Rocket League\RLMarlbot-master\MemoryWriter\vcpkg\buildtrees\libffi\config-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:863 (vcpkg_execute_required_process)
  ports/libffi/portfile.cmake:49 (vcpkg_configure_make)
  scripts/ports.cmake:175 (include)

error: building libffi:x64-windows failed with: BUILD_FAILED

**Comment by dg0yt** [comment]
> Working Directory: B:/Enzo/Desktop/Rocket League/RLMarlbot-master/MemoryWriter/vcpkg/buildtrees/libffi/x64-windows-dbg

Do not use locations with special characters: space, `+`, `*`, `(`, `?`.

**Comment by FrankXie05** [comment]
This issue hasn’t been updated for a long time; if it is still an issue, please ping me and I will reopen this issue.
