### ISSUE TITLE
[colmap] Build error on x64-windows

### ISSUE THREAD

**Issue by Lynx5261** [microsoft/vcpkg#38897]
Package: colmap[core,cuda,tests]:x64-windows@2023-10-01

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.39.33523.0
-    vcpkg-tool version: 2024-04-23-d6945642ee5c3076addd1a42c331bbf4cfc97457
    vcpkg-scripts version: 59aeb8fe8 2024-05-23 (4 hours ago)

**To Reproduce**

(Fresh clone & install of vcpkg)
`git clone https://github.com/microsoft/vcpkg`
`cd vcpkg`
`.\bootstrap-vcpkg.bat`
`vcpkg install colmap[cuda,tests]:x64-windows --recurse`

**Failure logs**

```
-- Using cached colmap-colmap-9c704e89ff0a80e797725e112011f9f69e5aa28f.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/colmap/src/f69e5aa28f-361efbb7b2.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/colmap-colmap-9c704e89ff0a80e797725e112011f9f69e5aa28f.tar.gz
-- Using source at C:/vcpkg/buildtrees/colmap/src/f69e5aa28f-361efbb7b2.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j25
    Working Directory: C:/vcpkg/buildtrees/colmap/x64-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\colmap\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/colmap/portfile.cmake:58 (vcpkg_cmake_install)
  scripts/ports.cmake:175 (include)
```

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/15416223/install-x64-windows-dbg-out.log)

**Comment by Lynx5261** [comment]
Seems to be a similar issue as in #38393 , though experienced in windows.

**Comment by LilyWangLL** [comment]
I can reproduce this issue locally.

**Comment by Lynx5261** [comment]
I have retried with a fresh full vcpkg install with the updated github vcpkg repo, however, to no avail it seems.

I'm still running into trouble with a final message saying "ninja: build stopped: subcommand failed." 
When I check the log file (included below) , no fatal errors are encountered like there were previously though, yet the process is still stopped somehow.
Positive note: We are getting a little further in the installation process ([95/369]) then previously ([53/369]).

[install-x64-windows-dbg-out.log](https://github.com/user-attachments/files/15574271/install-x64-windows-dbg-out.log)



For completion:

Package: colmap[core,cuda,tests]:x64-windows@2023-10-01#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.39.33523.0
-    vcpkg-tool version: 2024-04-23-d6945642ee5c3076addd1a42c331bbf4cfc97457
    vcpkg-scripts version: a4275b7ee 2024-06-04 (10 hours ago)

**To Reproduce**

`vcpkg install colmap[cuda,tests]:x64-windows`

**Failure logs**

```
-- Downloading https://github.com/colmap/colmap/archive/9c704e89ff0a80e797725e112011f9f69e5aa28f.tar.gz -> colmap-colmap-9c704e89ff0a80e797725e112011f9f69e5aa28f.tar.gz...
-- Extracting source C:/vcpkg/downloads/colmap-colmap-9c704e89ff0a80e797725e112011f9f69e5aa28f.tar.gz
-- Applying patch fix-link-glog.patch
-- Using source at C:/vcpkg/buildtrees/colmap/src/f69e5aa28f-d3d9082ca8.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j25
    Working Directory: C:/vcpkg/buildtrees/colmap/x64-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\colmap\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/colmap/portfile.cmake:60 (vcpkg_cmake_install)
  scripts/ports.cmake:175 (include)

**Comment by LilyWangLL** [comment]
> I have retried with a fresh full vcpkg install with the updated github vcpkg repo, however, to no avail it seems.
> 
> I'm still running into trouble with a final message saying "ninja: build stopped: subcommand failed." When I check the log file (included below) , no fatal errors are encountered like there were previously though, yet the process is still stopped somehow. Positive note: We are getting a little further in the installation process ([95/369]) then previously ([53/369]).
> 
> [install-x64-windows-dbg-out.log](https://github.com/user-attachments/files/15574271/install-x64-windows-dbg-out.log)
> 
> For completion:
> 
> Package: colmap[core,cuda,tests]:x64-windows@2023-10-01#1
> 
> **Host Environment**
> 
> * Host: x64-windows
> * Compiler: MSVC 19.39.33523.0
> * vcpkg-tool version: 2024-04-23-d6945642ee5c3076addd1a42c331bbf4cfc97457
>   vcpkg-scripts version: [a4275b7](https://github.com/microsoft/vcpkg/commit/a4275b7eee79fb24ec2e135481ef5fce8b41c339) 2024-06-04 (10 hours ago)
> 
> **To Reproduce**
> 
> `vcpkg install colmap[cuda,tests]:x64-windows`
> 
> **Failure logs**
> 
> ```
> -- Downloading https://github.com/colmap/colmap/archive/9c704e89ff0a80e797725e112011f9f69e5aa28f.tar.gz -> colmap-colmap-9c704e89ff0a80e797725e112011f9f69e5aa28f.tar.gz...
> -- Extracting source C:/vcpkg/downloads/colmap-colmap-9c704e89ff0a80e797725e112011f9f69e5aa28f.tar.gz
> -- Applying patch fix-link-glog.patch
> -- Using source at C:/vcpkg/buildtrees/colmap/src/f69e5aa28f-d3d9082ca8.clean
> -- Found external ninja('1.11.0').
> -- Configuring x64-windows-dbg
> -- Configuring x64-windows-rel
> -- Building x64-windows-dbg
> CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
>     Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j25
>     Working Directory: C:/vcpkg/buildtrees/colmap/x64-windows-dbg
>     See logs for more information:
>       C:\vcpkg\buildtrees\colmap\install-x64-windows-dbg-out.log
> 
> Call Stack (most recent call first):
>   installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
>   installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
>   ports/colmap/portfile.cmake:60 (vcpkg_cmake_install)
>   scripts/ports.cmake:175 (include)
> ```

This error will be fix by PR https://github.com/microsoft/vcpkg/pull/39244.
