### ISSUE TITLE
Whitelist for postbuild verification

### ISSUE THREAD

**Issue by martin-s** [microsoft/vcpkg#3889]
The PostBuildLint process checks for export of dlls which in some port cases are counter-productive (e.g. osg). The plugin libraries actually do not export any symbols, so this post-verification fails and makes the build fail.
Currently, the port file moves the affected libraries out of the bin folder which is some kind of workaround. A better solution would be to skip the verification for these libraries on a port basis. Are there any ways I have not seen yet that enable that approach?
Otherwise I would propose to add a whitelist that takes a list of library names that should be skipped in the verification process (especially check_exports_of_dlls).

**Comment by JackBoosY** [comment]
It's by design. You can move them to _tools/plugins_ or _share/${PORT}/plugins_.
