### ISSUE TITLE
install old version libmysql

### ISSUE THREAD

**Issue by jphz** [microsoft/vcpkg#38904]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json",
  "name": "xxxx-windows",
  "version": "1.0.0",
  "dependencies": [
    {
      "name": "libmysql"
    }
  ],
  "overrides": [
    {
      "name": "libmysql",
      "version": "5.7.16"
    }
  ],
  "builtin-baseline": "cbf4a6641528cee6f172328984576f51698de726"
}

.\vcpkg.exe install --clean-after-build
```

### Failure logs

error: failed to execute: "D:\Program Files\Git\cmd\git.exe" "--git-dir=D:\code\vcpkg\.git" "--work-tree=D:\code\vcpkg\buildtrees\versioning_\versions\libmysql\bd8444042adf5f24eceafe33353340c2f0961a5b_20288.tmp" -c core.autocrlf=false read-tree -m -u bd8444042adf5f24eceafe33353340c2f0961a5b
vcpkg was cloned as a shallow repository in: D:\code\vcpkg\.git
Try again with a full vcpkg clone.
error: git failed with exit code: (128).
fatal: failed to unpack tree object bd8444042adf5f24eceafe33353340c2f0961a5b
note: while checking out port libmysql with git tree bd8444042adf5f24eceafe33353340c2f0961a5b

**Comment by autoantwort** [comment]
> vcpkg was cloned as a shallow repository in: D:\code\vcpkg.git
Try again with a full vcpkg clone.

**Comment by jphz** [comment]
我该如何操作？

**Comment by autoantwort** [comment]
Ich verstehe dich leider nicht?
