### ISSUE TITLE
Packages fail with Visual Studio 17.10

### ISSUE THREAD

**Issue by Knightly1** [microsoft/vcpkg#38919]
**Describe the bug**
vcpkg being used with Visual Studio 17.10 fail. Prior to 17.10 these packages were successful. Ella Zhang from Microsoft has reported that this is a vcpkg problem and not a Visual Studio 17.10 problem.  

**Environment**
- OS: Windows
- Compiler: Visual Studio 17.10

**To Reproduce**
1. Install Visual Studio 17.10
2. Use vcpkg standalone (not integrated)
3. Attempt to install package from vcpkg (tested using multiple, but primarily fmt)
4. Package will fail
5. Roll back to previous Visual Studio 17.9.6
6. Attempt to install package from vcpkg
7. Package will fail

**Expected behavior**
vcpkg bootstraps and packages install

**Failure logs**
```
-- Running vcpkg install
error: in triplet x64-windows: Unable to find a valid Visual Studio instance
Could not locate a complete Visual Studio instance
The following paths were examined for Visual Studio instances:
  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary/Build\vcvarsall.bat

-- Running vcpkg install - failed
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:899 (message):
  vcpkg install failed.  See logs for more information:
  <source tree>\build\vcpkg-manifest-install.log
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:146 (include)
  CMakeLists.txt:3 (project)

-- Configuring incomplete, errors occurred!
```

**Additional context**
https://developercommunity.visualstudio.com/t/VCPKG-fails-with-VS-v17100/10663893

**Comment by jimwang118** [comment]
I upgraded visual studio 2022 to version 17.10, and then tested the installation of fmt. The results were normal and the problem you mentioned could not be reproduced.
![image](https://github.com/microsoft/vcpkg/assets/122244446/de84b3f8-67fa-4b7c-affe-f9687d6b736c)

**Comment by Knightly1** [comment]
> I upgraded visual studio 2022 to version 17.10, and then tested the installation of fmt. The results were normal and the issue you mentioned could not be reproduced.

Thank you for this, it looks like it was an issue in vcpkg-cmake that was resolved in latest.  Will test and report back.
