### ISSUE TITLE
[openssl] Build error

### ISSUE THREAD

**Issue by hqho** [microsoft/vcpkg#38913]
Package: openssl:x64-linux -> 1.0.2j

**Host Environment**

- Host: x64-linux
- Compiler: GNU 7.4.0
-    vcpkg-tool version: 2023-08-09-9990a4c9026811a312cb2af78bf77f3d9d288416
    vcpkg-scripts version: 9edb1b8e5 2023-08-14 (9 months ago)

**To Reproduce**

`vcpkg install `
**Failure logs**

```
CMake Warning at /home/jenkins/vcpkg/scripts/cmake/vcpkg_common_functions.cmake:3 (message):
  vcpkg_common_functions has been removed and all values are automatically
  provided in all portfile.cmake invocations.  Please remove
  `include(vcpkg_common_functions)`.
Call Stack (most recent call first):
  /home/jenkins/vcpkg/buildtrees/versioning_/versions/openssl/f18f7a91cacba1703f571e5c0a06c0f6b0d2a13f/portfile.cmake:6 (include)
  /home/jenkins/vcpkg/scripts/ports.cmake:147 (include)


-- Downloading https://www.openssl.org/source/openssl-1.0.2j.tar.gz -> openssl-1.0.2j.tar.gz...
-- Configuring x64-linux-rel
CMake Error at /home/jenkins/vcpkg/scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /var/opt/teradata/jenkins/cmake-3.27.6-linux-x86_64/bin/cmake /home/jenkins/vcpkg/buildtrees/openssl/src/openssl-1.0.2j -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/jenkins/vcpkg/packages/openssl_x64-linux -DCURRENT_INSTALLED_DIR=/home/jenkins/google-cloud-cpp/cmake-out/vcpkg_installed/x64-linux -DCURRENT_PACKAGES_DIR=/home/jenkins/vcpkg/packages/openssl_x64-linux -DCURRENT_BUILDTREES_DIR=/home/jenkins/vcpkg/buildtrees/openssl -DOPENSSL_SOURCE_ARCHIVE=/home/jenkins/vcpkg/downloads/openssl-1.0.2j.tar.gz -DCMAKE_MODULE_PATH=/home/jenkins/vcpkg/scripts/cmake -DTRIPLET_SYSTEM_ARCH=x64 -DVERSION=1.0.2j -DTARGET_TRIPLET=x64-linux -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/jenkins/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/home/jenkins/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/home/jenkins/vcpkg -DZ_VCPKG_ROOT_DIR=/home/jenkins/vcpkg -D_VCPKG_INSTALLED_DIR=/home/jenkins/google-cloud-cpp/cmake-out/vcpkg_installed -DVCPKG_MANIFEST_INSTALL=OFF
    Working Directory: /home/jenkins/vcpkg/buildtrees/openssl/x64-linux-rel
    Error code: 1
    See logs for more information:
      /home/jenkins/vcpkg/buildtrees/openssl/config-x64-linux-rel-err.log

Call Stack (most recent call first):
  /home/jenkins/vcpkg/scripts/cmake/vcpkg_configure_cmake.cmake:344 (vcpkg_execute_required_process)
  /home/jenkins/vcpkg/buildtrees/versioning_/versions/openssl/f18f7a91cacba1703f571e5c0a06c0f6b0d2a13f/portfile.cmake:27 (vcpkg_configure_cmake)
  /home/jenkins/vcpkg/scripts/ports.cmake:147 (include)



```
<details><summary>/home/jenkins/vcpkg/buildtrees/openssl/config-x64-linux-rel-err.log</summary>

```
CMake Error: Could not create named generator NMake Makefiles

Generators
  Green Hills MULTI            = Generates Green Hills MULTI files
                                 (experimental, work-in-progress).
* Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  Ninja Multi-Config           = Generates build-<Config>.ninja files.
  Watcom WMake                 = Generates Watcom WMake makefiles.
  CodeBlocks - Ninja           = Generates CodeBlocks project files
                                 (deprecated).
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files
                                 (deprecated).
  CodeLite - Ninja             = Generates CodeLite project files
                                 (deprecated).
  CodeLite - Unix Makefiles    = Generates CodeLite project files
                                 (deprecated).
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files
                                 (deprecated).
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files
                                 (deprecated).
  Kate - Ninja                 = Generates Kate project files (deprecated).
  Kate - Ninja Multi-Config    = Generates Kate project files (deprecated).
  Kate - Unix Makefiles        = Generates Kate project files (deprecated).
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files
                                 (deprecated).
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files
                                 (deprecated).
```
</details>**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "name": "google-cloud-cpp-development",
  "version": "2.18.0",
  "description": "Describes the vcpkg dependencies for vcpkg development.",
  "homepage": "https://github.com/googleapis/google-cloud-cpp",
  "license": "Apache-2.0",
  "supports": "!uwp",
  "dependencies": [
    "abseil",
    "crc32c",
    {
      "name": "curl",
      "features": [
        "ssl"
      ]
    },
    {
      "$description": "If cross-compiling, we need the gRPC protoc plugin on the 'host' environment.",
      "name": "grpc",
      "host": true
    },
    {
      "$description": "If cross-compiling, we need the protoc compiler on the 'host' environment.",
      "name": "protobuf",
      "host": true
    },
    "grpc",
    "protobuf",
    "nlohmann-json",
    "benchmark",
    "gtest",
    {
      "$description": "Only used for the opentelemetry feature.",
      "name": "opentelemetry-cpp"
    },
    {
      "$description": "Only used for the docfx feature.",
      "name": "pugixml"
    },
    {
      "$description": "Only used for the docfx feature.",
      "name": "yaml-cpp"
    }
  ],
  "builtin-baseline": "9edb1b8e590cc086563301d735cae4b6e732d2d2",
  "overrides": [
    {
      "name": "openssl",
      "version-string": "1.0.2j"
    },
    {
      "name": "curl",
      "version": "8.2.1"
    }
  ]
}

```
</details>

**Comment by dg0yt** [comment]
> Package: openssl:x64-linux -> 1.0.2j

Outdated, won't be fixed.

> * vcpkg-tool version: 2023-08-09-9990a4c9026811a312cb2af78bf77f3d9d288416
>       vcpkg-scripts version: [9edb1b8](https://github.com/microsoft/vcpkg/commit/9edb1b8e590cc086563301d735cae4b6e732d2d2) 2023-08-14 (9 months ago)

Outdated, won't be fixed.

Why are people flooding vcpkg with outdated stuff ATM? A teacher providing outdated materials?

**Comment by hqho** [comment]
It might be outdated, but it's still supported by google cloud cpp
https://github.com/googleapis/google-cloud-cpp/blob/main/doc/packaging.md#required-libraries

**Comment by dg0yt** [comment]
You might be able to build old versions of openssl with an up-to-date vcpkg, using manifest mode. That's what versioning exists for. However, you leave the area of tested configurations, and you don't get fixes for old port versions from this registry.

**Comment by hqho** [comment]
Can you point me to how I can do this?

**Comment by dg0yt** [comment]
https://learn.microsoft.com/en-us/vcpkg/consume/lock-package-versions

**Comment by hqho** [comment]
This  was what were done above using the "overrides" list in the vcpkg.json.   

"overrides": [
    {
      "name": "openssl",
      "version-string": "1.0.2j"
    },
    {
      "name": "curl",
      "version": "8.2.1"
    }
  ]

After it downloaded the openssl version then it failed cmake

-- Downloading https://www.openssl.org/source/openssl-1.0.2j.tar.gz -> openssl-1.0.2j.tar.gz...
-- Configuring x64-linux-rel
CMake Error at /home/jenkins/vcpkg/scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /var/opt/teradata/jenkins/cmake-3.27.6-linux-x86_64/bin/cmake /home/jenkins/vcpkg/buildtrees/openssl/src/openssl-1.0.2j -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/jenkins/vcpkg/packages/openssl_x64-linux -DCURRENT_INSTALLED_DIR=/home/jenkins/google-cloud-cpp/cmake-out/vcpkg_installed/x64-linux -DCURRENT_PACKAGES_DIR=/home/jenkins/vcpkg/packages/openssl_x64-linux -DCURRENT_BUILDTREES_DIR=/home/jenkins/vcpkg/buildtrees/openssl -DOPENSSL_SOURCE_ARCHIVE=/home/jenkins/vcpkg/downloads/openssl-1.0.2j.tar.gz -DCMAKE_MODULE_PATH=/home/jenkins/vcpkg/scripts/cmake -DTRIPLET_SYSTEM_ARCH=x64 -DVERSION=1.0.2j -DTARGET_TRIPLET=x64-linux -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/jenkins/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/home/jenkins/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/home/jenkins/vcpkg -DZ_VCPKG_ROOT_DIR=/home/jenkins/vcpkg -D_VCPKG_INSTALLED_DIR=/home/jenkins/google-cloud-cpp/cmake-out/vcpkg_installed -DVCPKG_MANIFEST_INSTALL=OFF
    Working Directory: /home/jenkins/vcpkg/buildtrees/openssl/x64-linux-rel
    Error code: 1
    See logs for more information:
      /home/jenkins/vcpkg/buildtrees/openssl/config-x64-linux-rel-err.log

CMake Error: Could not create named generator NMake Makefiles

Generators
  Green Hills MULTI            = Generates Green Hills MULTI files
                                 (experimental, work-in-progress).
* Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  Ninja Multi-Config           = Generates build-<Config>.ninja files.
  Watcom WMake                 = Generates Watcom WMake makefiles.
  CodeBlocks - Ninja           = Generates CodeBlocks project files
                                 (deprecated).
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files
                                 (deprecated).
  CodeLite - Ninja             = Generates CodeLite project files
                                 (deprecated).
  CodeLite - Unix Makefiles    = Generates CodeLite project files
                                 (deprecated).
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files
                                 (deprecated).
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files
                                 (deprecated).
  Kate - Ninja                 = Generates Kate project files (deprecated).
  Kate - Ninja Multi-Config    = Generates Kate project files (deprecated).
  Kate - Unix Makefiles        = Generates Kate project files (deprecated).
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files
                                 (deprecated).
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files
                                 (deprecated).

**Comment by dg0yt** [comment]
Linux doesn't need the "NMake Makefiles" generator.
And nobody cares about a port version from 2016, in particular in a security-sensitive area.
(Maybe you need to use port "openssl-unix" if you really want stone age.)

**Comment by FrankXie05** [comment]
This issue hasn’t been updated for a long time; if it is still an issue, please ping me and I will reopen this issue.
