### ISSUE TITLE
zlib build failed

### ISSUE THREAD

**Issue by Fish-Potato** [Microsoft/vcpkg#3892]
D:\vcpkg> .\vcpkg install zlib:x64-windows
The following packages will be built and installed:
    zlib[core]:x64-windows
Starting package 1/1: zlib:x64-windows
Building package zlib[core]:x64-windows...
-- Using cached D:/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch D:/vcpkg/ports/zlib/cmake_dont_build_more_than_needed.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:170 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: D:/vcpkg/buildtrees/zlib/x64-windows-dbg
    See logs for more information:
      D:\vcpkg\buildtrees\zlib\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/zlib/portfile.cmake:29 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Package: zlib:x64-windows
Vcpkg version: 0.0.113-nohash

[install-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2191293/install-x64-windows-dbg-out.log)
[patch-x64-windows-0-err.log](https://github.com/Microsoft/vcpkg/files/2191294/patch-x64-windows-0-err.log)
[config-x64-windows-out.log](https://github.com/Microsoft/vcpkg/files/2191299/config-x64-windows-out.log)

**Comment by wangii** [comment]
seems to be a language issue. set both system and vs language to English, problem solved.

**Comment by wangli28** [comment]
Please open a new issue if this is still a problem for you.
