### ISSUE TITLE
[opencc] hope support for arm64-windows

### ISSUE THREAD

**Issue by lsl330** [microsoft/vcpkg#38938]
### Is your feature request related to a problem? Please describe.

here is an error,opencc is only supported on '!(arm | uwp)', which does not match arm64-windows. 

### Proposed solution

opencc Fix build on win arm64 since 1.1.5(lastest is 1.1.7)
https://github.com/BYVoid/OpenCC/releases/tag/ver.1.1.5

**Comment by WangWeiLin-MV** [comment]
Failed in dependency `marisa-trie:arm64ec-windows`, we should fix it first.

**Comment by lsl330** [comment]
> marisa

the marisa can build on arm64，but i don't know how to fix on vcpkg.

here is my step：
1、./vcpkg install marisa-trie:arm64-windows --allow-unsupported，and will show the error.
2、unzip the marisa-trie file on vcpkg/download
3、use vs studio open the 2019.sln，and copy x64 setting to arm64
4、build arm64 success

hope will help for the marisa-trie:arm64-windows

[s-yata-marisa-trie.tar.gz](https://github.com/user-attachments/files/15722368/s-yata-marisa-trie.tar.gz)

**Comment by lsl330** [comment]
> Failed in dependency `marisa-trie:arm64-windows` which does not provide `arm64` configuration platform by [s-yata/marisa-trie - vs2019/vs2019.sln](https://github.com/s-yata/marisa-trie/blob/006020c1df76d0d7dc6118dacc22da64da2e35c4/vs2019/vs2019.sln).
> 
> As for the fixes you mentioned, probably it was against to the **unofficial** [BYVoid/OpenCC - deps/marisa-0.2.6/CMakeLists.txt](https://github.com/BYVoid/OpenCC/blob/ver.1.1.7/deps/marisa-0.2.6/CMakeLists.txt) that maintained by OpenCC.
> 
> Please request platform `arm64` support from upstream `marisa-trie`.



> Failed in dependency `marisa-trie:arm64-windows` which does not provide `arm64` configuration platform by [s-yata/marisa-trie - vs2019/vs2019.sln](https://github.com/s-yata/marisa-trie/blob/006020c1df76d0d7dc6118dacc22da64da2e35c4/vs2019/vs2019.sln).
> 
> As for the fixes you mentioned, probably it was against to the **unofficial** [BYVoid/OpenCC - deps/marisa-0.2.6/CMakeLists.txt](https://github.com/BYVoid/OpenCC/blob/ver.1.1.7/deps/marisa-0.2.6/CMakeLists.txt) that maintained by OpenCC.
> 
> Please request platform `arm64` support from upstream `marisa-trie`.

the marisa can build on arm64，but i don't know how to fix on vcpkg.

here is my step：
1、./vcpkg install marisa-trie:arm64-windows --allow-unsupported，and will show the error.
2、unzip the marisa-trie file on vcpkg/download
3、use vs studio open the 2019.sln，and copy x64 setting to arm64
4、build arm64 success

hope will help for the marisa-trie:arm64-windows

[s-yata-marisa-trie.tar.gz](https://github.com/user-attachments/files/15722488/s-yata-marisa-trie.tar.gz)

**Comment by WangWeiLin-MV** [comment]
@lsl330 Thank you for your investigation, there is currently no easy way to increase the build configurations for `sln`, and given that the upstream does not explicitly provide support for the `arm64` or `arm64ec` support, the most appropriate way is still to request the upstream.
