### ISSUE TITLE
[qttools] Install error.

### ISSUE THREAD

**Issue by reitowo** [microsoft/vcpkg#38936]
Qt 6.7.0 doesn't handle CMake scripts properly at install command. 
When using `qt_generate_deploy_app_script` in my CMakeLists and install, it can't find `qtpaths.exe`. It is trying to find under `vcpkg_installed/x64-windows/bin` but it is in `vcpkg_installed/x64_windows/tools/Qt6/bin`. 
Also, when setting the qtpaths manually to correct path, it also trying to find all debug dlls under `vcpkg_installed/x64-windows/bin` instead of `vcpkg_installed/x64_windows/debug/bin`. 

At least 6.4.3 version was working normally.

Qt really just don't like vcpkg's model, huh?

**Comment by Neumann-A** [comment]
can you give me an expanded trace with `--trace-expand`? 

Probably an easy fix by adjusting the script

**Comment by reitowo** [comment]
which command this arg is apply to?

```
-- Running Qt deploy tool for E:/VTSLink/Client/VTSLink/out/build/x64-RelWithDebInfo/bin/VTSLink.exe in working directory 'E:/VTSLink/Client/VTSLink/out/install/x64-RelWithDebInfo'
'E:/VTSLink/Client/VTSLink/out/build/x64-RelWithDebInfo/vcpkg_installed/x64-windows/tools/Qt6/bin/windeployqt.exe' 'E:/VTSLink/Client/VTSLink/out/build/x64-RelWithDebInfo/bin/VTSLink.exe' '--dir' '.' '--libdir' 'bin' '--plugindir' 'plugins' '--qml-deploy-dir' 'qml' '--translationdir' 'translations' '--force' '--qtpaths' 'E:/VTSLink/Client/VTSLink/out/build/x64-RelWithDebInfo/vcpkg_installed/x64-windows/bin/qtpaths.exe'
Error: "E:\VTSLink\Client\VTSLink\out\build\x64-RelWithDebInfo\vcpkg_installed\x64-windows\bin\qtpaths.exe" does not exist.
CMake Error at vcpkg_installed/x64-windows/share/Qt6Core/Qt6CoreDeploySupport.cmake:528 (message):
  Executing
  E:/VTSLink/Client/VTSLink/out/build/x64-RelWithDebInfo/vcpkg_installed/x64-windows/tools/Qt6/bin/windeployqt.exe
  failed: 1
Call Stack (most recent call first):
  .qt/deploy_VTSLink_bfe1574f6c.cmake:5 (qt6_deploy_runtime_dependencies)
  cmake_install.cmake:58 (include)
```

**Comment by reitowo** [comment]
The patch works! Thanks.
