### ISSUE TITLE
[boost-fiber] build failure

### ISSUE THREAD

**Issue by adokhugi** [microsoft/vcpkg#38958]
### Operating system

Windows

### Compiler

Visual Studio 2022

### Steps to reproduce the behavior

```Shell
vcpkg install boost
```

### Failure logs

C:\dev\vcpkg>vcpkg install boost
Computing installation plan...
The following packages will be built and installed:
    boost:x64-windows@1.81.0#3 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\afc980d4093ddd9d122b1bba1a894edd549c43a1
  * boost-fiber:x64-windows@1.81.0#2 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\e7a28ac75f376fe846ce57d52d5c3f07f72ce755
  * boost-json:x64-windows@1.81.0#2 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\e1823e435f5b0a89baadc0aedbd7b80cd3c8b4ef
  * boost-log:x64-windows@1.81.0#2 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\caf66e1400f40a88d45f8411351c04a15fe764bf
  * boost-poly-collection:x64-windows@1.81.0#2 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\4256eb60f0d91c480186af87acaf8a45bedb4833
  * boost-test:x64-windows@1.81.0#2 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\7e47dbce4949b5085b51a15ebb1041c86c7dde88
  * boost-timer:x64-windows@1.81.0#2 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\c3e14b189e9ba8356438d69471038ffe993ba9e6
  * boost-type-erasure:x64-windows@1.81.0#2 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\2db0ac9588dd25a7088c7b5967ebd1e479f235ac
  * boost-wave:x64-windows@1.81.0#2 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\f6aef641dfdf7f20ec1dbcd1280a260391b255ee
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\Acer\AppData\Local\vcpkg\archives in 1.79 ms. Use --debug to see more details.
Installing 1/9 boost-fiber:x64-windows@1.81.0#2...
Building boost-fiber:x64-windows@1.81.0#2...
-- Installing port from location: C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\e7a28ac75f376fe846ce57d52d5c3f07f72ce755
-- Using cached boostorg-fiber-boost-1.81.0.tar.gz.
-- Cleaning sources at C:/dev/vcpkg/buildtrees/boost-fiber/src/ost-1.81.0-76e8dedc5e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/boostorg-fiber-boost-1.81.0.tar.gz
-- Using source at C:/dev/vcpkg/buildtrees/boost-fiber/src/ost-1.81.0-76e8dedc5e.clean
-- Including C:/Users/Acer/AppData/Local/vcpkg/registries/git-trees/e7a28ac75f376fe846ce57d52d5c3f07f72ce755/b2-options.cmake
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/dev/vcpkg/downloads/tools/cmake-3.29.2-windows/cmake-3.29.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: C:/dev/vcpkg/buildtrees/boost-fiber/x64-windows-dbg
    See logs for more information:
      C:\dev\vcpkg\buildtrees\boost-fiber\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:140 (vcpkg_cmake_install)
  C:/Users/Acer/AppData/Local/vcpkg/registries/git-trees/e7a28ac75f376fe846ce57d52d5c3f07f72ce755/portfile.cmake:17 (boost_modular_build)
  scripts/ports.cmake:175 (include)

error: building boost-fiber:x64-windows failed with: BUILD_FAILED
Elapsed time to handle boost-fiber:x64-windows: 5.3 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-fiber
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[boost-fiber]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2Fdev%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

All of these packages cannot be built.

**Comment by Neumann-A** [comment]
Old boost version **1.81.0** . Won't be fixed (also no logs to analyze the error).

**Comment by JonLiu1993** [comment]
@adokhugi, Please use the latest vcpkg by command `git pull` and provide your error log:
````
C:\dev\vcpkg\buildtrees\boost-fiber\install-x64-windows-dbg-out.log
````

**Comment by JonLiu1993** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
