### ISSUE TITLE
boost-json build failure

### ISSUE THREAD

**Issue by adokhugi** [microsoft/vcpkg#38957]
### Operating system

Windows

### Compiler

Visual Studio 2022

### Steps to reproduce the behavior

```Shell
vcpkg install boost-json
```

### Failure logs

C:\dev\vcpkg>vcpkg install boost-json
Computing installation plan...
The following packages will be built and installed:
    boost-json:x64-windows@1.81.0#2 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\e1823e435f5b0a89baadc0aedbd7b80cd3c8b4ef
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\Acer\AppData\Local\vcpkg\archives in 519 us. Use --debug to see more details.
Installing 1/1 boost-json:x64-windows@1.81.0#2...
Building boost-json:x64-windows@1.81.0#2...
-- Installing port from location: C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\e1823e435f5b0a89baadc0aedbd7b80cd3c8b4ef
-- Downloading https://github.com/boostorg/json/archive/boost-1.81.0.tar.gz -> boostorg-json-boost-1.81.0.tar.gz...
-- Extracting source C:/dev/vcpkg/downloads/boostorg-json-boost-1.81.0.tar.gz
-- Using source at C:/dev/vcpkg/buildtrees/boost-json/src/ost-1.81.0-9cf4711843.clean
-- Including C:/Users/Acer/AppData/Local/vcpkg/registries/git-trees/e1823e435f5b0a89baadc0aedbd7b80cd3c8b4ef/b2-options.cmake
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/dev/vcpkg/downloads/tools/cmake-3.29.2-windows/cmake-3.29.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: C:/dev/vcpkg/buildtrees/boost-json/x64-windows-dbg
    See logs for more information:
      C:\dev\vcpkg\buildtrees\boost-json\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:140 (vcpkg_cmake_install)
  C:/Users/Acer/AppData/Local/vcpkg/registries/git-trees/e1823e435f5b0a89baadc0aedbd7b80cd3c8b4ef/portfile.cmake:17 (boost_modular_build)
  scripts/ports.cmake:175 (include)

error: building boost-json:x64-windows failed with: BUILD_FAILED
Elapsed time to handle boost-json:x64-windows: 8.5 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-json
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[boost-json]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2Fdev%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by Neumann-A** [comment]
probably same error as #38958

**Comment by WangWeiLin-MV** [comment]
Please try to run with latest vcpkg.

If the issue persists, please see #30604 for how to report a build failure.
