### ISSUE TITLE
qtinterfaceframework:x64-windows@6.4.3 build failure

### ISSUE THREAD

**Issue by adokhugi** [microsoft/vcpkg#38986]
### Operating system

Windows

### Compiler

Visual Studio 2022

### Steps to reproduce the behavior

```Shell
vcpkg install qt
```

### Failure logs

C:\dev\vcpkg>vcpkg install qt
Computing installation plan...
The following packages will be built and installed:
    qt[core,default-features]:x64-windows@6.4.3 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\01393fc66b4bf4414a40b6dfe895e025c1778fe6
  * qtinterfaceframework:x64-windows@6.4.3 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\0bb5fdc2bde29cd083a90c67dc1892d68772dadc
  * qtlanguageserver:x64-windows@6.4.3 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\9e626f373f4ca8f18e9bde990f75c34aef89baa2
  * qtlocation:x64-windows@6.4.3 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\9ff1609af9be7a187f0edcc495b0d646dc36a976
  * qtlottie[core,qml]:x64-windows@6.4.3 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\d8887bee44785f3c285c103d31d6c1436908ea8f
  * qtmqtt:x64-windows@6.4.3 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\67ca11347716f0408dd58bec49c52b8bc3c04da5
  * qtnetworkauth:x64-windows@6.4.3 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\e521ca0bc29e9c96290d6765997d4c7df3712599
  * qtopcua[core,default-features,gds,ns0idnames,open62541,qml]:x64-windows@6.4.3 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\2271b5bd852c0d9afdcee54b6f335667e7883501
  * qtpositioning[core,qml]:x64-windows@6.4.3 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\e6e37d5325bba76a2c912dcc537c36f5214e45d7
  * qtquick3d[core,default-features]:x64-windows@6.4.3 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\4fcbc24a4f09f2e43f69d771ed87ac6cc187a629
  * qtquicktimeline:x64-windows@6.4.3 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\8272dedda604707ed4bdd252fb855ca828b41719
  * qtscxml[core,qml]:x64-windows@6.4.3 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\60116e86139859df7acad954b48f839240e78272
  * qtsensors[core,qml]:x64-windows@6.4.3 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\21c5259e771214cb14555b2b0310a4ef4c068294
  * qtserialbus[core,default-features]:x64-windows@6.4.3 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\3dba771f89dc1c260819b83479a1daba0a822936
  * qtserialport:x64-windows@6.4.3 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\32ebc82d527f3da5977dcfae337c4eab9e6f228f
  * qtspeech:x64-windows@6.4.3 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\93a6cd65b0db0994bbedef360adbe246b5df6d91
  * qtsvg:x64-windows@6.4.3 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\864d53d5bedd0946c9790551a06258580647478f
  * qttranslations[core,default-features]:x64-windows@6.4.3 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\48b6fd21acccdffacd9390b9b860a5b2e3ba554a
  * qtvirtualkeyboard[core,default-features,hunspell]:x64-windows@6.4.3 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\6cbb11db41affe7798e62dbec8ebb5aa8e728b5d
  * qtwebchannel[core,qml]:x64-windows@6.4.3 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\27b0c979401491880b2dad92b728e14fb5b7e37b
  * qtwebengine[core,default-features,geolocation,spellchecker,webchannel]:x64-windows@6.4.3 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\7a5dda5f36b2686d421d061f93a73da169815174
  * qtwebsockets[core,qml]:x64-windows@6.4.3 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\89352bf06b1d966295a7b5e919836e9994eef0a9
  * qtwebview[core,qml,webengine]:x64-windows@6.4.3 -- C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\9b5466522d3ff72530716724384c7122f4ffe8c1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\Acer\AppData\Local\vcpkg\archives in 553 us. Use --debug to see more details.
Installing 1/23 qtinterfaceframework:x64-windows@6.4.3...
Building qtinterfaceframework:x64-windows@6.4.3...
-- Installing port from location: C:\Users\Acer\AppData\Local\vcpkg\registries\git-trees\0bb5fdc2bde29cd083a90c67dc1892d68772dadc
-- Using cached C:/dev/vcpkg/downloads/qtinterfaceframework-35892bfbfa4c405bba2a648d1a4d4d17b1bc62b2.tar.gz
-- Cleaning sources at C:/dev/vcpkg/buildtrees/qtinterfaceframework/src/17b1bc62b2-44f32b96ee.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/qtinterfaceframework-35892bfbfa4c405bba2a648d1a4d4d17b1bc62b2.tar.gz
-- Applying patch fix-taglib-search.patch
-- Using source at C:/dev/vcpkg/buildtrees/qtinterfaceframework/src/17b1bc62b2-44f32b96ee.clean
-- Using cached msys2-mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst.
-- Using msys root at C:/dev/vcpkg/downloads/tools/msys2/d33df895d441a36d
CMake Error at installed/x64-windows/share/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake:78 (file):
  file COPY cannot find
  "C:/dev/vcpkg/downloads/tools/python/python-3.11.8-x64/python310.zip": File
  exists.
Call Stack (most recent call first):
  C:/Users/Acer/AppData/Local/vcpkg/registries/git-trees/0bb5fdc2bde29cd083a90c67dc1892d68772dadc/portfile.cmake:22 (x_vcpkg_get_python_packages)
  scripts/ports.cmake:175 (include)

error: building qtinterfaceframework:x64-windows failed with: BUILD_FAILED
Elapsed time to handle qtinterfaceframework:x64-windows: 3 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qtinterfaceframework
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[qtinterfaceframework]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2Fdev%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

python310.zip does not exist, but there is python311.zip.

I did "git pull" and "vcpkg update" before executing this.

**Comment by Neumann-A** [comment]
remove vcpkg-get-python-packages and reinstall. Otherwise update vcpkg to a newer version?

**Comment by Neumann-A** [comment]
also you probably don'T want qtinterfaceframework. Just install the parts of qt you need. If you just do widget stuff qtbase is enough. If you need qml stuff you need to install qtdeclarative.

**Comment by dg0yt** [comment]
And do not expect fixes to old versions.

**Comment by WangWeiLin-MV** [comment]
Using the latest version of vcpkg for local installation does not reproduce the issue.

Please try with latest vcpkg.

If the issue persists, please see #30604 for how to report a build failure.
