### ISSUE TITLE
[libcap] curl failed to download with exit code 22

### ISSUE THREAD

**Issue by onbings** [microsoft/vcpkg#38981]
### Operating system

gcc (Debian 10.2.1-6) 10.2.1 20210110

### Compiler

gcc (Debian 10.2.1-6) 10.2.1 20210110

### Steps to reproduce the behavior

```Shell
[DEBUG] 1000: execute_process(curl --fail -L https://git.kernel.org/pub/scm/libs/libcap/libcap.git/snapshot/libcap-3c7dda330bd9a154bb5b878d31fd591e4951fe17.tar.gz --create-dirs --output /home/bha/pro/vcpkg/downloads/libpcap-2.69.tar.gz.4190190.part)
[DEBUG] 1000: cmd_execute_and_stream_data() returned 22 after    67473 us
error: Failed to download from mirror set
error: https://git.kernel.org/pub/scm/libs/libcap/libcap.git/snapshot/libcap-3c7dda330bd9a154bb5b878d31fd591e4951fe17.tar.gz: curl failed to download with exit code 22
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

curl: (22) The requested URL returned error: 403 Forbidden
```

### Failure logs

Installing 1/65 libcap:x64-linux@2.69#3...
Building libcap:x64-linux@2.69#3...
/home/bha/.cache/vcpkg/registries/git-trees/23bb9f2743e684bacba57b8cc8a931756f0e7447: info: installing overlay port from here
-- Downloading https://git.kernel.org/pub/scm/libs/libcap/libcap.git/snapshot/libcap-3c7dda330bd9a154bb5b878d31fd591e4951fe17.tar.gz -> libpcap-2.69.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from /home/bha/pro/vcpkg/vcpkg-bundle.json
[DEBUG] Failed to open: /home/bha/pro/vcpkg/vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
[DEBUG] 1000: execute_process(curl --fail -L https://git.kernel.org/pub/scm/libs/libcap/libcap.git/snapshot/libcap-3c7dda330bd9a154bb5b878d31fd591e4951fe17.tar.gz --create-dirs --output /home/bha/pro/vcpkg/downloads/libpcap-2.69.tar.gz.4190190.part)
[DEBUG] 1000: cmd_execute_and_stream_data() returned 22 after    67473 us
error: Failed to download from mirror set
error: https://git.kernel.org/pub/scm/libs/libcap/libcap.git/snapshot/libcap-3c7dda330bd9a154bb5b878d31fd591e4951fe17.tar.gz: curl failed to download with exit code 22
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

curl: (22) The requested URL returned error: 403 Forbidden

[DEBUG] /source/src/vcpkg/base/downloads.cpp(997):
[DEBUG] Time in subprocesses: 67473us
[DEBUG] Time in parsing JSON: 2us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 408us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 68.5 ms (67780us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  /home/bha/.cache/vcpkg/registries/git-trees/23bb9f2743e684bacba57b8cc8a931756f0e7447/portfile.cmake:1 (vcpkg_download_distfile)
  scripts/ports.cmake:175 (include)

error: building libcap:x64-linux failed with: BUILD_FAILED
Elapsed time to handle libcap:x64-linux: 83.6 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libcap
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[libcap]+Build+error+on+x64-linux&body=Copy+issue+body+from+%2Fhome%2Fbha%2Fbld%2Fevs-hwfw-sb-xts-lin%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md

-- Running vcpkg install - failed
CMake Error at /home/bha/pro/vcpkg/scripts/buildsystems/vcpkg.cmake:899 (message):
  vcpkg install failed.  See logs for more information:
  /home/bha/bld/evs-hwfw-sb-xts-lin/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/local/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:170 (include)
  CMakeLists.txt:47 (project)

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
bha@fw-build-01:~/pro$ ^C

**Comment by MonicaLiu0311** [comment]
Currently, `libcap` has been updated to `2.69#5`, please pull the latest vcpkg.

```
monica@monica003:/mnt/vcpkg$  ./vcpkg version
vcpkg package management program version 2024-04-23-d6945642ee5c3076addd1a42c331bbf4cfc97457

See LICENSE.txt for license information.
```

```
monica@monica003:/mnt/vcpkg$ ./vcpkg install libcap
Computing installation plan...
The following packages will be built and installed:
    libcap:x64-linux@2.69#5
Detecting compiler hash for triplet x64-linux...
Compiler found: /usr/bin/c++
Restored 0 package(s) from /home/monica/.cache/vcpkg/archives in 7.6 us. Use --debug to see more details.
Installing 1/1 libcap:x64-linux@2.69#5...
Building libcap:x64-linux@2.69#5...
-- Downloading https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.69.tar.xz;https://www.mirrorservice.org/sites/ftp.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.69.tar.xz -> libcap-2.69.tar.xz...
-- Extracting source /mnt/vcpkg/downloads/libcap-2.69.tar.xz
-- Using source at /mnt/vcpkg/buildtrees/libcap/src/libcap-2-46d2f5c326.clean
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Installing x64-linux-dbg
-- Building x64-linux-rel
-- Installing x64-linux-rel
-- Fixing pkgconfig file: /mnt/vcpkg/packages/libcap_x64-linux/lib/pkgconfig/libcap.pc
-- Fixing pkgconfig file: /mnt/vcpkg/packages/libcap_x64-linux/lib/pkgconfig/libpsx.pc
-- Fixing pkgconfig file: /mnt/vcpkg/packages/libcap_x64-linux/debug/lib/pkgconfig/libcap.pc
-- Fixing pkgconfig file: /mnt/vcpkg/packages/libcap_x64-linux/debug/lib/pkgconfig/libpsx.pc
-- Installing: /mnt/vcpkg/packages/libcap_x64-linux/share/libcap/copyright
-- Performing post-build validation
Failed to store binary cache /home/monica/.cache/vcpkg/archives/ae/ae13fb267afd657212e4ba63687e4de6cc632a955f7c2aa2ae4fa9f0c892cda9.zip
No such file or directory
Stored binaries in 0 destinations in 16 ms.
Elapsed time to handle libcap:x64-linux: 3.2 s
libcap:x64-linux package ABI: ae13fb267afd657212e4ba63687e4de6cc632a955f7c2aa2ae4fa9f0c892cda9
Total install time: 3.2 s
libcap provides pkg-config modules:

  # libcap - linux capabilities library
  libcap

  # libpsx - linux posix syscall API for pthreads
  libpsx
```

**Comment by onbings** [comment]
Thank you for your fast answer (I really appreciate it) and you're right it works in **INSTALL** mode as you can see below **BUT (see below)**

bha@WL2100156:~/pro/vcpkg$ ./vcpkg version
vcpkg package management program version 2024-04-23-d6945642ee5c3076addd1a42c331bbf4cfc97457

See LICENSE.txt for license information.
 
 bha@WL2100156:~/pro/vcpkg$ ./vcpkg install libcap
Computing installation plan...
The following packages will be built and installed:
    libcap:x64-linux@2.69#5
Detecting compiler hash for triplet x64-linux...
Compiler found: /usr/bin/c++
Restored 0 package(s) from /home/bha/.cache/vcpkg/archives in 9 us. Use --debug to see more details.
Installing 1/1 libcap:x64-linux@2.69#5...
Building libcap:x64-linux@2.69#5...
-- Downloading https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.69.tar.xz;https://www.mirrorservice.org/sites/ftp.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.69.tar.xz -> libcap-2.69.tar.xz...
-- Extracting source /home/bha/pro/vcpkg/downloads/libcap-2.69.tar.xz
-- Using source at /home/bha/pro/vcpkg/buildtrees/libcap/src/libcap-2-46d2f5c326.clean
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Installing x64-linux-dbg
-- Building x64-linux-rel
-- Installing x64-linux-rel
-- Fixing pkgconfig file: /home/bha/pro/vcpkg/packages/libcap_x64-linux/lib/pkgconfig/libcap.pc
-- Fixing pkgconfig file: /home/bha/pro/vcpkg/packages/libcap_x64-linux/lib/pkgconfig/libpsx.pc
-- Fixing pkgconfig file: /home/bha/pro/vcpkg/packages/libcap_x64-linux/debug/lib/pkgconfig/libcap.pc
-- Fixing pkgconfig file: /home/bha/pro/vcpkg/packages/libcap_x64-linux/debug/lib/pkgconfig/libpsx.pc
-- Installing: /home/bha/pro/vcpkg/packages/libcap_x64-linux/share/libcap/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 12.4 ms.
Elapsed time to handle libcap:x64-linux: 19 s
libcap:x64-linux package ABI: 0b899be2f26cc23e17fcf37ae97d51f3f56fb0737a215a1fa76b55adce180027
Total install time: 19 s
libcap provides pkg-config modules:

  # libcap - linux capabilities library
  libcap

  # libpsx - linux posix syscall API for pthreads
  libpsx

bha@WL2100156:~/pro/vcpkg$


**========> on the SAME computer in MANIFEST mode i got: <=======================**

Installing 38/102 libcap:x64-linux@2.69#3...
Building libcap:x64-linux@2.69#3...
/home/bha/.cache/vcpkg/registries/git-trees/23bb9f2743e684bacba57b8cc8a931756f0e7447: info: installing overlay port from here
-- Downloading https://git.kernel.org/pub/scm/libs/libcap/libcap.git/snapshot/libcap-3c7dda330bd9a154bb5b878d31fd591e4951fe17.tar.gz -> libpcap-2.69.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from /home/bha/pro/vcpkg/vcpkg-bundle.json
[DEBUG] Failed to open: /home/bha/pro/vcpkg/vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
[DEBUG] 1000: execute_process(curl --fail -L https://git.kernel.org/pub/scm/libs/libcap/libcap.git/snapshot/libcap-3c7dda330bd9a154bb5b878d31fd591e4951fe17.tar.gz --create-dirs --output /home/bha/pro/vcpkg/downloads/libpcap-2.69.tar.gz.25970.part)
[DEBUG] 1000: cmd_execute_and_stream_data() returned 22 after   157249 us
error: Failed to download from mirror set
error: https://git.kernel.org/pub/scm/libs/libcap/libcap.git/snapshot/libcap-3c7dda330bd9a154bb5b878d31fd591e4951fe17.tar.gz: curl failed to download with exit code 22
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

curl: (22) The requested URL returned error: 403 Forbidden

[DEBUG] /source/src/vcpkg/base/downloads.cpp(997):
[DEBUG] Time in subprocesses: 157249us
[DEBUG] Time in parsing JSON: 4us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 208us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 158 ms (157618us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.


Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  /home/bha/.cache/vcpkg/registries/git-trees/23bb9f2743e684bacba57b8cc8a931756f0e7447/portfile.cmake:1 (vcpkg_download_distfile)
  scripts/ports.cmake:175 (include)


error: building libcap:x64-linux failed with: BUILD_FAILED
Elapsed time to handle libcap:x64-linux: 442 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libcap
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[libcap]+Build+error+on+x64-linux&body=Copy+issue+body+from+%2Fhome%2Fbha%2Fbld%2Fevs-hwfw-sb-xts-lin%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md

-- Running vcpkg install - failed

REMARK: This last test has been made on WSL2 ubuntu 20.4. My previous test was on a native pc with ubuntu 20.4

bha@WL2100156:~/pro/vcpkg$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
bha@WL2100156:~/pro/vcpkg$

**Comment by dg0yt** [comment]
This is not caused by the mode, but by your manifest using an old baseline or override version.

**Comment by onbings** [comment]
Ok nice idea, i will give a look and keep you informed of my progress.
It seems that the very last base line 37630acd98740f98d7e51da78c9630758835037f does no more include the linenoise-ng lib but i need this one to build my app ??!!???
Do you know why this one has been removed and/or can you put it back in the official repository ?
{
  "name": "linenoise-ng",
  "version-string": "4754bee2d8eb3",
  "port-version": 3,
  "description": "A small, portable GNU readline replacement for Linux, Windows and MacOS which is capable of handling UTF-8 characters.",
  "dependencies": [
    {
      "name": "vcpkg-cmake",
      "host": true
    }
  ]
}

**Comment by dg0yt** [comment]
https://github.com/microsoft/vcpkg/pull/37492#issuecomment-2008192503 says: Port needs fixes, upstream is gone.

Note that you can still use the existing version in manifest mode.

**Comment by onbings** [comment]
Ok

**Comment by onbings** [comment]
Great work, thank you for the help. I'm now struggling with my system to validate all this

**Comment by onbings** [comment]
All is ok now, thx !
Have a nice week end
