### ISSUE TITLE
Non-ASCII username: Many things break

### ISSUE THREAD

**Issue by omartijn** [microsoft/vcpkg#38990]
**Describe the bug**
When using vcpkg  from a user-account with non-ASCII characters in the name, many things break.

**Environment**
- OS: Windows 10
- Compiler: VS 2022

**To Reproduce**
Try to install any package, either standalone or in manifest mode.

**Expected behavior**
Package should build and install

**Failure logs**

File download fails, because `${ENV{VCPKG_COMMAND}}` is messed up. Downloading the file manually and placing it in the downloads folder gets us to the next errors: The C compiler is unable to compile a simple test program.

Note that running vcpkg in the same VM from a user account only containing ASCII characters works.

**Comment by omartijn** [comment]
@MonicaLiu0311 Why is this marked as a question? It's clearly a bug.

**Comment by omartijn** [comment]
> Don't use non-ascii symbols in usernames and paths ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

If only that were an option. Since people are using our software with these usernames on Windows and they are running into issues, I need to be able to debug this.

**Comment by dg0yt** [comment]
> If only that were an option. Since people are using our software with these usernames on Windows and they are running into issues, I need to be able to debug this.

And once it is fixed in one place, people will just build another package which stumbles over it. It won't stop soon.

**Comment by MonicaLiu0311** [comment]
https://github.com/microsoft/vcpkg?tab=readme-ov-file#quick-start-windows

Thank you for your feedback, currently we recommend installing vcpkg to a path without non-ASCII characters and may not resolve this issue for a while.
