### ISSUE TITLE
Add Pre-compiled Qt 4.x and 5.x

### ISSUE THREAD

**Issue by sarthakcbica** [Microsoft/vcpkg#39]
A lot of these can be found here:

http://www.npcglib.org/~stathis/blog/precompiled-qt4-qt5/

**Comment by barcharcraz** [comment]
Do these have to be precompiled? it's not all that hard to build qt on windows, although it does take a really long time.

I have some working scripts for qt5 source builds that I'll eventually port over to vcpkg, but they use nmake right now, which is not ideal.

**Comment by sarthakcbica** [comment]
It does need to be pre-compiled and it is a pain for people who aren't very familiar with the different configuration options (especially configuration with openssl).

**Comment by ras0219-msft** [comment]
The difficulty for binary packages with dependencies is that they introduce significant constraints on their dependencies -- whenever a dependency (openssl) wants to updated, the prebuilt binaries (qt) would also need to be rebuilt and updated. Users who care about that dependency (e.g. openssl) might not care about the main package so it introduces a lot of overhead for them. With a source-based approach, the higher level packages consume dependency changes automatically which reduces the burden on maintainers.

It may still be the right call to use prebuilt binaries for qt, but these are the concerns I see.

**Comment by sarthakcbica** [comment]
Thanks for the pro-active replies, MS guys! 

That is definitely true. In any case, even without specific dependencies, Qt builds are pretty tough for non-programmers to get right; especially the older versions where pre-built binaries aren't distributed by the company. For instance, a majority of research groups use Qt 4.8.6, for which there aren't any official builds available (either for VS 2013 or 2015).

**Comment by ras0219-msft** [comment]
Closing, since we have `qt5` available as a building package.
