### ISSUE TITLE
[yasm] Build error on x64-windows

### ISSUE THREAD

**Issue by Dineshbabu0603** [microsoft/vcpkg#39008]
how can i solve this issue?

error: building yasm:x64-windows failed with: BUILD_FAILED
Elapsed time to handle yasm:x64-windows: 3 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+yasm
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[yasm]+Build+error+on+x64-windows&body=Copy+issue+body+from+D%3A%2Fvcpkg%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by jimwang118** [comment]
Please provide specific steps to reproduce the problem and error log.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
