### ISSUE TITLE
Fixing pthreads for ARM and ARM64

### ISSUE THREAD

**Issue by carlo-bramini** [microsoft/vcpkg#3903]
At the time of writing, pthread-win32 cannot be compiled for ARM and ARM64.
Adding the little change in the attached patch made it working.
I hope that this could be fixed.
Sincerely.

[patch.txt](https://github.com/Microsoft/vcpkg/files/2194918/patch.txt)

**Comment by carlo-bramini** [comment]
I also would like to signal that, from an email that I received from the maintainer, versione 2.9.1 is quite old and no longer updated. The project migrated to sourceforge at:

https://sourceforge.net/projects/pthreads4w/

with the name of pthread4w and it is the continuation of the previous one. At the time of writing, a more updated version is also available for  download. When it will be released, the newer version will also include the above fix.

**Comment by JackBoosY** [comment]
Hi @carlo-bramini, thanks for reporting this issue.
This issue has been fixed in some PRs. Please update vcpkg and rebuild pthreads.

Thanks.
