### ISSUE TITLE
[poco] build failure

### ISSUE THREAD

**Issue by Nosenzor** [microsoft/vcpkg#39045]
### Operating system

MacOs 14.5 (ARM)

### Compiler

Apple clang

### Steps to reproduce the behavior

```Shell
Using vcpkg in manifest mode 
Extract of my vcpkg.json
{
      "name" : "poco",
      "platform": "(windows & x64) | (linux & x64) | (osx & x64) | (osx & arm64)"
}


Then the call in Cmake

find_package(Poco CONFIG REQUIRED COMPONENTS Zip)
```

### Failure logs

CMake Error at /Users/romainnosenzo/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package):
  Found package configuration file:

    /Users/romainnosenzo/CLionProjects/PhotoTools/builds/ninja-release-vcpkg/vcpkg_installed/arm64-osx/share/poco/PocoUtilConfig.cmake

  but it set PocoUtil_FOUND to FALSE so package "PocoUtil" is considered to
  be NOT FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing: Poco::XML
  Poco::JSON

Call Stack (most recent call first):
  /Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.28/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
  builds/ninja-release-vcpkg/vcpkg_installed/arm64-osx/share/poco/PocoZipConfig.cmake:3 (find_dependency)
  /Users/romainnosenzo/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  builds/ninja-release-vcpkg/vcpkg_installed/arm64-osx/share/poco/PocoConfig.cmake:35 (find_package)
  /Users/romainnosenzo/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)

### Additional context

The build has worked up to a recent vcpkg update.

The same vcpkg.json with the same cmake is working fine on Windows 11 and with an older mac os system (10.15 with x86)

**Comment by jimwang118** [comment]
I can't reproduce this problem locally, you can try using the following statement
`find_package(Poco CONFIG REQUIRED COMPONENTS XML JSON Zip)`

**Comment by Nosenzor** [comment]
Now it works : I've destroyed the vcpkg cache and had to do as you told me (added XML and JSON) 
`find_package(Poco CONFIG REQUIRED COMPONENTS XML JSON Zip)`
Now the bug can be turned into why should i add XML and JSON while I only use Zip ? Not a big issue in my case but that's a bit odd.
Feel free to close the issue if you think that behavior is standard.

**Comment by jimwang118** [comment]
> Now it works : I've destroyed the vcpkg cache and had to do as you told me (added XML and JSON) `find_package(Poco CONFIG REQUIRED COMPONENTS XML JSON Zip)` Now the bug can be turned into why should i add XML and JSON while I only use Zip ? Not a big issue in my case but that's a bit odd. Feel free to close the issue if you think that behavior is standard.

Normally, zip calls uitl, and uitl calls json and xml. So when zip is called, uitl, json, and xml are automatically called. However, the search for uitl's dependent json and xml on your device fails.
I cannot reproduce this problem locally, so I cannot locate it. You can also try to create a new folder on the device and clone vcpkg. Try to use the newly cloned code to see if there is the same error. If the problem does not exist in the newly cloned code, it may be caused by the cache.

**Comment by dg0yt** [comment]
@Nosenzor You can get more tracing information from CMake with `--trace-expand` or `-DCMAKE_FIND_DEBUG_MODE=ON`.
