### ISSUE TITLE
vcpkg install fails to detect msvc after Visual Studio 2022 build tools upgrade to 17.10.0

### ISSUE THREAD

**Issue by dbenson2000** [microsoft/vcpkg#39048]
**Describe the bug**
We have been successfully using vcpkg with Visual Studio Build Tools 2022 version 17.9.x. Since upgrading to 17.10.0, installation of packages fails to find a working compiler.

**Environment**
- OS: Windows
- Compiler: 19.40.33808 for x64

**To Reproduce**
The issue is occurring regardless of package chosen. Steps to reproduce the behavior:
1. Open a Developer Command Prompt for VS2022 (or Powershell, same behavior)
2. cl (demonstrates that command is in path and has expected version)
3. ./vcpkg install fmt --triplet x64-windows

**Expected behavior**
As with Visual Studio Build Tools 2022 version 17.9.x, we expect the compiler chosen to be cl (msvc).

**Failure logs**
[stdout-x64-windows.log](https://github.com/microsoft/vcpkg/files/15505772/stdout-x64-windows.log)
[CMakeCache.txt](https://github.com/microsoft/vcpkg/files/15505777/CMakeCache.txt)

**Comment by carsten-grimm-at-ipolog** [comment]
Can you share the error message that you are seeing? I do not see an error in the attached log, but it seems to indicate that MSVC 19.39 was found, I believe you should be seeing 19.40 for VS2022 17.10.0. 

I am not entirely sure if it is the same issue, but it sounds like the error message that I got after updating to  VS2022 17.10.1. It occurs when I install anything with from a powershell in the vcpkg folder. 

> error: in triplet x64-windows: Unable to find a valid Visual Studio instance
Could not locate a complete Visual Studio instance
The following paths were examined for Visual Studio instances:
  C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary/Build\vcvarsall.bat

Running `./bootstrap.bat` in the vcpkg folder solved this issue for me.

**Comment by dbenson2000** [comment]
Running bootstrap didn't make a difference for me.

The error which seems most relevant to me is:
-- The CXX compiler identification is Clang 17.0.3 with GNU-like command-line

C:\PROGRA~2\MICROS~3\2022\BUILDT~1\VC\Tools\Llvm\x64\bin\CLANG_~1.EXE   /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP   /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -MD -MT CMakeFiles/cmTC_65363.dir/testCXXCompiler.cxx.obj -MF CMakeFiles\cmTC_65363.dir\testCXXCompiler.cxx.obj.d -o CMakeFiles/cmTC_65363.dir/testCXXCompiler.cxx.obj -c C:/Users/David.Benson/ThirdParty/vcpkg/buildtrees/fmt/x64-windows-static-md-rel/CMakeFiles/CMakeScratch/TryCompile-twve2z/testCXXCompiler.cxx
    CLANG_~1: error: no such file or directory: '/nologo'
    CLANG_~1: error: no such file or directory: '/DWIN32'
    CLANG_~1: error: no such file or directory: '/D_WINDOWS'
    CLANG_~1: error: no such file or directory: '/W3'
    CLANG_~1: error: no such file or directory: '/utf-8'



Console output:
C:\Users\David.Benson\ThirdParty\vcpkg>vcpkg install fmt --triplet x64-windows-static-md
Computing installation plan...
The following packages will be built and installed:
    fmt:x64-windows-static-md -> 10.1.1
Detecting compiler hash for triplet x64-windows-static-md...
Restored 0 package(s) from C:\Users\David.Benson\AppData\Local\vcpkg\archives in 823 us. Use --debug to see more details.
Installing 1/1 fmt:x64-windows-static-md...
Building fmt:x64-windows-static-md...
warning: -- Using community triplet x64-windows-static-md. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\Users\David.Benson\ThirdParty\vcpkg\triplets\community\x64-windows-static-md.cmake
-- Using cached fmtlib-fmt-10.1.1.tar.gz.
-- Cleaning sources at C:/Users/David.Benson/ThirdParty/vcpkg/buildtrees/fmt/src/10.1.1-281bbdd8af.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/David.Benson/ThirdParty/vcpkg/downloads/fmtlib-fmt-10.1.1.tar.gz
-- Applying patch fix-write-batch.patch
-- Applying patch fix-format-conflict.patch
-- Using source at C:/Users/David.Benson/ThirdParty/vcpkg/buildtrees/fmt/src/10.1.1-281bbdd8af.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-static-md
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/Users/David.Benson/ThirdParty/vcpkg/buildtrees/fmt/x64-windows-static-md-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\David.Benson\ThirdParty\vcpkg\buildtrees\fmt\config-x64-windows-static-md-dbg-CMakeCache.txt.log
      C:\Users\David.Benson\ThirdParty\vcpkg\buildtrees\fmt\config-x64-windows-static-md-rel-CMakeCache.txt.log
      C:\Users\David.Benson\ThirdParty\vcpkg\buildtrees\fmt\config-x64-windows-static-md-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:252 (vcpkg_execute_required_process)
  ports/fmt/portfile.cmake:12 (vcpkg_cmake_configure)
  scripts/ports.cmake:170 (include)


error: building fmt:x64-windows-static-md failed with: BUILD_FAILED
Elapsed time to handle fmt:x64-
[config-x64-windows-static-md-out.log](https://github.com/user-attachments/files/15506821/config-x64-windows-static-md-out.log)
windows-static-md: 36 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+fmt
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[fmt]+Build+error+on+x64-windows-static-md&body=Copy+issue+body+from+C%3A%2FUsers%2FDavid.Benson%2FThirdParty%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by carsten-grimm-at-ipolog** [comment]
You could consider using the link at the bottom of the message to submit an issue here. I believe the process behind that ensures that all relevant details are recorded to help the maintainers help you with the issue.

**Comment by xiaozhuai** [comment]
I am on 17.10.0 too, but I didn't repro it.
> 1. Open a Developer Command Prompt for VS2022 (or Powershell, same behavior)
> 2. cl (demonstrates that command is in path and has expected version)
> 3. ./vcpkg install fmt --triplet x64-windows
BTW, the first 2 step is no need. Just run `vcpkg install xxx`

**Comment by dbenson2000** [comment]
Deleting the vcpkg directory cleared the issue. Closing.

**Comment by Jiatutu** [comment]
> Deleting the vcpkg directory cleared the issue. Closing.

Delete the vcpkg directory in the vs2022 installation directory?

**Comment by wdx04** [comment]
I fixed this issue with an old version of vcpkg by installing the 14.39 toolset via the Visual Studio Installer.

**Comment by Jyotipm05** [comment]
Can you explain how you explain how to do it?
