### ISSUE TITLE
[New Port Request] mariadb-connector-cpp

### ISSUE THREAD

**Issue by quqiOnfree** [microsoft/vcpkg#39062]
### Library name

mariadb-connector-cpp

### Library description

MariaDB Connector for C++

### Source repository URL

https://github.com/mariadb-corporation/mariadb-connector-cpp

### Project homepage (if different from the source repository)

https://mariadb.com/docs/server/connect/programming-languages/cpp/

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

I have found the same issue #27571, but it was unresolved.
It must copy a library source code [mariadb-connector-c](https://github.com/mariadb-corporation/mariadb-connector-c) to directory called `libmariadb/`, and then it can be built.
I have forked [vcpkg](https://github.com/quqiOnfree/vcpkg), but I don't know how to modify it correctly.

**Comment by dg0yt** [comment]
IIUC this is port `libmariadb`.

**Comment by dg0yt** [comment]
> IIUC this is port `libmariadb`.

Ignore, you want the C++ variant.
