### ISSUE TITLE
Building package python3:x64-windows failed with vs2015

### ISSUE THREAD

**Issue by changjiayi6322** [Microsoft/vcpkg#3908]
+ CategoryInfo          : NotSpecified: (CMake Error at ...e:56 (message): 
   :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
    Command failed: msbuild;F:/git/vcpkg/buildtrees/python3/src/v3.6.4-5bfb0301
b2-Lib-dynamic-crt-dynamic/PCBuild/pythoncore.vcxproj;/p:Configuration=Release;
/t:Rebuild;/p:Platform=x64;/p:PlatformToolset=v140;/p:VCPkgLocalAppDataDisabled
=true;/p:UseIntelMKL=No;/p:WindowsTargetPlatformVersion=10.0.14393.0;/m
    Working Directory: F:/git/vcpkg/buildtrees/python3/x64-windows-rel

[build-x64-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/2195385/build-x64-windows-rel-out.log)

**Comment by Voskrese** [comment]
`link.exe /ERRORREPORT:QUEUE /OUT:"F:\git\vcpkg\buildtrees\python3\src\v3.6.4-5bfb0301b2-Lib-dynamic-crt-dynamic\PCBuild\amd64\python36.dll" /NOLOGO /LIBPATH:"F:\git\vcpkg\buildtrees\python3\src\v3.6.4-5bfb0301b2-Lib-dynamic-crt-dynamic\PCBuild\amd64\\" /LIBPATH:"F:\git\vcpkg\buildtrees\python3\src\v3.6.4-5bfb0301b2-Lib-dynamic-crt-dynamic\PC\external\v140\amd64" version.lib shlwapi.lib ws2_32.lib opencv_world340.lib libEGL.lib libGLESv2.lib libMaliEmulator.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib`

`LINK : fatal error LNK1181: cannot open input file 'libEGL.lib'` ?

**Comment by JackBoosY** [comment]
Hi @changjiayi6322 , thanks for reporting this issue!
python3:x64-windows built success on my machine. Maybe someone fixed it.
Please open a new issue if this is still a problem for you.
Thx.
