### ISSUE TITLE
[qt] <qt6>

### ISSUE THREAD

**Issue by WangHHY19931001** [microsoft/vcpkg#39095]
### Is your feature request related to a problem? Please describe.

now qt version up to qt6, and qml have too much diff from qt5, need it

### Proposed solution

need add qt6 support

**Comment by JonLiu1993** [comment]
@WangHHY19931001, could you please elaborate on your needs?

**Comment by carsten-grimm-at-ipolog** [comment]
There are already ports for Qt6, e.g., `qtbase`, `qtdeclarative`, `qtsvg` and so forth. They are separate from the Qt5 ports, e.g., `qt5-base`, `qt5-declarative`, `qt5-svg`.

**Comment by JonLiu1993** [comment]
It seems that your problem has been solved. If you have other needs, please reopen this issue.
