### ISSUE TITLE
Update OpenCV to 3.4.2

### ISSUE THREAD

**Issue by jasjuang** [Microsoft/vcpkg#3910]
It would be great if someone can update OpenCV to 3.4.2. @cenit would you be able to do it?

**Comment by cenit** [comment]
Hi! Sorry really busy period. I can try to do it asap, but at least for one week more I will be totally packed. Maybe we should try to merge also the external ffmpeg, thanks to ffmpeg4 and the work the opencv community is doing on this front it should alleviate much trouble...

**Comment by jasjuang** [comment]
@cenit Thanks a lot and look forward to see you making this happen!

**Comment by carmangary** [comment]
FYI: OpenCV 3.4.3 is out.  Should this be closed or modified?

**Comment by cenit** [comment]
yep, working directly on 3.4.3. Sorry for the long delay

**Comment by pwm1234** [comment]
I need the vcpkg build of opencv 3.4.3. Is there something I can do to help or test? My initial need is for x64-windows with the hdf contrib module.

**Comment by alexkaratarakis** [comment]
#4636 PR.

**Comment by jasjuang** [comment]
close by #4636
