### ISSUE TITLE
[spdlog] fmt dependency

### ISSUE THREAD

**Issue by bumbar1** [microsoft/vcpkg#39116]
### Is your feature request related to a problem? Please describe.

Why does spdlog have fmt as listed dependency? Spdlog bundles it and there's no need to have it listed as dependency.

### Proposed solution

Remove fmt dependency for spdlog port.

**Comment by bumbar1** [comment]
Tried to undefine SPDLOG_FMT_EXTERNAL so it would use bundled version, but bundled directory is [removed during installation](https://github.com/microsoft/vcpkg/blob/master/ports/spdlog/portfile.cmake#L60)???

**Comment by LilyWangLL** [comment]
Oue policy about dependency is: "Do not use embedded copies of libraries", please refer to the maintainer guide https://learn.microsoft.com/en-us/vcpkg/contributing/maintainer-guide#do-not-use-vendored-dependencies.
