### ISSUE TITLE
[boost-variant2] Build error on x64-windows-static

### ISSUE THREAD

**Issue by JPersson77** [microsoft/vcpkg#39117]
I just recently started getting build errors (file hash errors actually) on github continous actions. Please see below

Building boost-variant2:x64-windows-static@1.85.0...
-- Downloading https://github.com/boostorg/variant2/archive/boost-1.85.0.tar.gz -> boostorg-variant2-boost-1.85.0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from D:\a\LGTVCompanion\LGTVCompanion\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: D:\a\LGTVCompanion\LGTVCompanion\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://github.com/boostorg/variant2/archive/boost-1.85.0.tar.gz
[DEBUG] Trying to hash D:\a\LGTVCompanion\LGTVCompanion\vcpkg\downloads\boostorg-variant2-boost-1.85.0.tar.gz.7492.part
[DEBUG] D:\a\LGTVCompanion\LGTVCompanion\vcpkg\downloads\boostorg-variant2-boost-1.85.0.tar.gz.7492.part has hash f4f79ab208c534a7e7a285e2722dbe14c7d810a8ad9e73dd2a6de51862b3b08928802251e8661815e5bf9f82eefd10125a984724ae4670823307edc93cd679a8
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/boostorg/variant2/archive/boost-1.85.0.tar.gz
File: D:\a\LGTVCompanion\LGTVCompanion\vcpkg\downloads\boostorg-variant2-boost-1.85.0.tar.gz.7492.part
Expected hash: 1a5fc662247f3e8437dfeec552fc3c5c380112db4a2e6b0c9e7abad1c06ec0d07dcbb528c244884f2507ac14174f4db3fadfd211e84d9bcd26a5ab5f33cb4d97
Actual hash: f4f79ab208c534a7e7a285e2722dbe14c7d810a8ad9e73dd2a6de51862b3b08928802251e8661815e5bf9f82eefd10125a984724ae4670823307edc93cd679a8
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(997): 
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 6us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 828us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 452 ms (443921us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
      

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/boost-variant2/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:175 (include)

error: building boost-variant2:x64-windows-static failed with: BUILD_FAILED
Elapsed time to handle boost-variant2:x64-windows-static: 503 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-variant2
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[boost-variant2]+Build+error+on+x64-windows-static&body=Copy+issue+body+from+D%3A%2Fa%2FLGTVCompanion%2FLGTVCompanion%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
You can also submit an issue by running (GitHub CLI must be installed):
  gh issue create -R microsoft/vcpkg --title "[boost-variant2] Build failure on x64-windows-static" --body-file D:/a/LGTVCompanion/LGTVCompanion/vcpkg/installed/vcpkg/issue_body.md
Error: Process completed with exit code 1.

**Comment by Cheney-W** [comment]
This issue has been fixed by https://github.com/microsoft/vcpkg/pull/38979/files#diff-bbe6b2a544475676138a333ff929568e5e159d870f04fd90a109f01ecc1f9279

**Comment by JPersson77** [comment]
thanks, any idea when a new release will be? I understand that my action ( https://github.com/johnwason/vcpkg-action ) downloads the executable vcpkg rather than pulling in the vcpkg as a submodule.

**Comment by computerquip-work** [comment]
For what it's worth, I did a fresh install yesterday (all of Windows actually) and I'm getting this error that I'm currently having to debug.

**Comment by computerquip-work** [comment]
Doh! I forgot to update the baseline in `vcpkg-configuration.json`.
