### ISSUE TITLE
[dbus] Download failed, gitlab.freedesktop.org is currently under maintenance

### ISSUE THREAD

**Issue by LemonZHFF** [microsoft/vcpkg#39113]
### Is your feature request related to a problem? Please describe.

when i install qt5:x64-linux ，the download dbus failed!

### Proposed solution

when i install qt5:x64-linux ，the download dbus failed!

### Describe alternatives you've considered

when i install qt5:x64-linux ，the download dbus failed!

### Additional context

when i install qt5:x64-linux ，the download dbus failed!

**Comment by StarGate-One** [comment]
At present Gitlab is down for maintenance so any vcpkg ports needing source from gitlab will be unavailable until the maintenance is completed - https://gitlab.freedesktop.org/1

**Comment by Flole998** [comment]
Looks like they are done now. Btw: There were several opportunities to run a build as it came back online a few times, you just had to get the timing right ;)

**Comment by WangWeiLin-MV** [comment]
The service of https://gitlab.freedesktop.org/ should now be restored.
