### ISSUE TITLE
[vxl] build error:error C2660: 'opj_stream_set_user_data'

### ISSUE THREAD

**Issue by wurui1994** [microsoft/vcpkg#3911]
E:\Workspace\vcpkg\buildtrees\vxl\src\c46e77f524-9f281e37d1\core\vil\file_formats\vil_openjpeg.cxx(257): error C2660: 'opj_stream_set_user_data': function does not take 2 arguments
...
ninja: build stopped: subcommand failed.

**Comment by JackBoosY** [comment]
Vxl needs to wait for official support for the latest openjpeg2 before updating, see [#627](https://github.com/vxl/vxl/issues/627).

**Comment by JackBoosY** [comment]
Close this PR until upstream fixes this.
