### ISSUE TITLE
Installing openssl and other libraries on MacOS

### ISSUE THREAD

**Issue by Merethiel** [Microsoft/vcpkg#3913]
Hi I have the latest version of vcpkg which I cloned from the repository.
Then I executed ./bootstrap-vcpkg.sh which seems to have executed fine.
But I need to install several different libraries which unfortunately has dependencies on openssl, I can't get openssl to install. This is the log it generates.

I ran the command ./vcpkg install openssl

The following packages will be built and installed:
    openssl[core]:x64-osx
Starting package 1/1: openssl:x64-osx
Building package openssl[core]:x64-osx... 
-- Downloading https://www.openssl.org/source/openssl-1.0.2o.tar.gz...
-- Extracting source /users/merethiel/vcpkg/downloads/openssl-1.0.2o.tar.gz
-- Applying patch /users/merethiel/vcpkg/ports/openssl/ConfigureIncludeQuotesFix.patch
-- Applying patch /users/merethiel/vcpkg/ports/openssl/STRINGIFYPatch.patch
-- Applying patch /usersmerethiell/vcpkg/ports/openssl/EmbedSymbolsInStaticLibsZ7.patch
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:170 (message):
    Command failed: /Users/merethiel/vcpkg/downloads/tools/cmake-3.11.4-osx/cmake-3.11.4-Darwin-x86_64/CMake.app/Contents/bin/cmake;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: /users/merethiel/vcpkg/buildtrees/openssl/x64-osx-dbg
    See logs for more information:
      /users/merethiel/vcpkg/buildtrees/openssl/install-x64-osx-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/openssl/portfile-nonwindows.cmake:23 (vcpkg_install_cmake)
  ports/openssl/portfile.cmake:30 (include)
  scripts/ports.cmake:71 (include)

Error: Building package openssl:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl:x64-osx
  Vcpkg version: 0.0.113-unknownhash

I receive this error with other libraries I try to install as well.

**Comment by snorristurluson** [comment]
I had a similar error, with the following error in the log:

In file included from cryptlib.c:117:
./cryptlib.h:62:11: fatal error: 'stdlib.h' file not found
# include <stdlib.h>
          ^~~~~~~~~~
1 error generated.

This was resolved by running xcode-select --install.

See https://github.com/frida/frida/issues/338 for a similar issue.

**Comment by Merethiel** [comment]
Ah okay, so I just run xcode-select --install in the terminal then run vcpkg again?

**Comment by snorristurluson** [comment]
That worked for me, yes.

**Comment by Merethiel** [comment]
That seems to have done it! Thank you!
