### ISSUE TITLE
[EXIV2] build failure

### ISSUE THREAD

**Issue by swede1128** [microsoft/vcpkg#39148]
### Operating system

Windows 11

### Compiler

VS 2022 Community

### Steps to reproduce the behavior

```Shell
./vcpkg install exiv2
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
    exiv2[core]:x86-windows -> 0.27.3#4
  * gettext[core]:x86-windows -> 0.21#2
  * libiconv[core]:x86-windows -> 1.16#8
  * zlib[core]:x86-windows -> 1.2.11#10
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
A suitable version of git was not found (required v2.26.0). Downloading portable git v2.26.0...
Downloading git...
  https://github.com/git-for-windows/git/releases/download/v2.26.2.windows.1/PortableGit-2.26.2-32-bit.7z.exe -> D:\SwedesProjects\_vcpkg\downloads\PortableGit-2.26.2-32-bit.7z.exe
Extracting git...
Could not locate cached archive: C:\Users\swede\AppData\Local\vcpkg\archives\47\4766256634ed6ed6e06e435939cffd4c397dc9b8.zip
Could not locate cached archive: C:\Users\swede\AppData\Local\vcpkg\archives\a0\a019e3036374204431f2b336d46670f56ef38d20.zip
Could not locate cached archive: C:\Users\swede\AppData\Local\vcpkg\archives\d7\d7f72da60e42afe0aaeb1798d08a53c101131198.zip
Could not locate cached archive: C:\Users\swede\AppData\Local\vcpkg\archives\b4\b40549322476e99e84387e011d1f593bd8d6e178.zip
Starting package 1/4: libiconv:x86-windows
Building package libiconv[core]:x86-windows...
-- Using cached D:/SwedesProjects/_vcpkg/downloads/libiconv-1.16.tar.gz
-- Cleaning sources at D:/SwedesProjects/_vcpkg/buildtrees/libiconv/src/1.16-de9101a181.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/SwedesProjects/_vcpkg/downloads/libiconv-1.16.tar.gz
-- Applying patch 0002-Config-for-MSVC.patch
-- Applying patch 0003-Add-export.patch
-- Using source at D:/SwedesProjects/_vcpkg/buildtrees/libiconv/src/1.16-de9101a181.clean
-- Configuring x86-windows
-- Downloading https://repo.msys2.org/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz -> msys-bash-4.4.023-2-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz -> msys-bash-4.4.023-2-x86_64.pkg.tar.xz...
-- Downloading https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz -> msys-bash-4.4.023-2-x86_64.pkg.tar.xz...
-- Downloading https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz -> msys-bash-4.4.023-2-x86_64.pkg.tar.xz...
-- Downloading https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirrors.ustc.edu.cn/msys2/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz -> msys-bash-4.4.023-2-x86_64.pkg.tar.xz...
-- Downloading https://mirrors.ustc.edu.cn/msys2/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirror.bit.edu.cn/msys2/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz -> msys-bash-4.4.023-2-x86_64.pkg.tar.xz...
-- Downloading https://mirror.bit.edu.cn/msys2/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz... Failed. Status: 28;"Timeout was reached"
-- Downloading https://mirror.selfnet.de/msys2/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz -> msys-bash-4.4.023-2-x86_64.pkg.tar.xz...
-- Downloading https://mirror.selfnet.de/msys2/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz -> msys-bash-4.4.023-2-x86_64.pkg.tar.xz...
-- Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz... Failed. Status: 28;"Timeout was reached"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:184 (message):
      
      Failed to download file.
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. You proxy's remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:90 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_acquire_msys.cmake:128 (msys_package_download)
  scripts/cmake/vcpkg_acquire_msys.cmake:170 (msys_package)
  scripts/cmake/vcpkg_configure_make.cmake:295 (vcpkg_acquire_msys)
  ports/libiconv/portfile.cmake:28 (vcpkg_configure_make)
  scripts/ports.cmake:141 (include)

Error: Building package libiconv:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libiconv:x86-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

Additionally, attach any relevant sections from the log files above.

**Comment by StarGate-One** [comment]
Need to update the vcpkg as it is trying to download very old msys tools:
1. `cd <vcpkg-root>`
2. `git pull`
3. `.\bootstrap-vcpkg.bat`
4. `.\vcpkg.exe upgrade` if okay add the --no-dry-run

If that fails, then it may be best just do delete the vcpkg repo and rebuild from scratch.

**Comment by jimwang118** [comment]
You need to update vcpkg according to the above steps, and then you can compile normally.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
