### ISSUE TITLE
[vcpkg-artifact] 'cmake' matched more than one result

### ISSUE THREAD

**Issue by FrankXie05** [microsoft/vcpkg#39157]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
iex (iwr -useb https://aka.ms/vcpkg-init.ps1) 
cd .\.vcpkg\
.\vcpkg.exe find artifact cmake
.\vcpkg.exe use cmake
```

### Failure logs

```
PS C:\Users\test\.vcpkg> .\vcpkg.exe use cmake
warning: vcpkg-artifacts is experimental and may change at any time.
error: AssertionError [ERR_ASSERTION]: 'cmake' matched more than one result (microsoft:tools/kitware/cmake,arm:tools/kitware/cmake).
```

### Additional context

It seems that ce downloads two different versions of cmake from different places and looks for them, and ignores the local `cmake`.
@vicroms @BillyONeal 

![6dda6f02-a51a-4ba9-9614-9da3f84130ed](https://github.com/microsoft/vcpkg/assets/65999885/57266145-12cf-460f-83a8-3374faf81619)
![f76e0382-f360-4a60-b77a-23c29958b82e](https://github.com/microsoft/vcpkg/assets/65999885/8c565e48-11f0-42df-ad69-b38411e8bef1)
![653dfa2e-67b8-4ea2-b366-be8360637786](https://github.com/microsoft/vcpkg/assets/65999885/7eaca381-c4ba-4cda-956f-8b885c6144e5)

**Comment by FrankXie05** [comment]
@102030w

**Comment by BillyONeal** [comment]
This is expected, now that ARM has decided to add an artifact named `cmake` to their repo. It needs to be explicitly qualified `microsoft:cmake` if you want the previous behavior.

**Comment by 102030w** [comment]
I need to be explicitly qualified microsoft:cmake. What should I do?
eg: 
```
./vcpkg.exe use microsoft:cmake
```
