### ISSUE TITLE
Add some CMake variables relative to Installation Path

### ISSUE THREAD

**Issue by Tom-Henoch** [Microsoft/vcpkg#3915]
Hello,

Could it be possible to add some CMake variables relative to vckpg installation path and current triplet  when using a tool chain ? 

- `VCPKG_INCLUDE_DIR` : which point to current `include` directory
- `VCPKG_BIN_DIR` : which point to current `bin` directory
-  `VCPKG_LIB_DIR`: which point to current `lib` directory
- etc.

Currently you can retreive them by using :  `${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include` 

But I suppose the variable `_VCPKG_INSTALLED_DIR`  is not supposed to be used outside the toolchain file (because of the underscore).

I could be usefull both : in our projects CMakeLists and in patches used by portfiles.

**Comment by MathiasMagnus** [comment]
I have been successfully relying on `${CURRENT_PACKAGES_DIR}` in the OpenCL SDK portfile to replicate your `${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}` use case. Is that sufficient?

**Comment by Tom-Henoch** [comment]
Yes, it's perfect :D
Thanks !
