### ISSUE TITLE
[New Port Request] Tessil ordered map

### ISSUE THREAD

**Issue by diehard2** [microsoft/vcpkg#39167]
### Library name

tessil-ordered-map

### Library description

hash map that maintains order of insertion

### Source repository URL

https://github.com/Tessil/ordered-map

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

Would be really nice to have. Header only library, but exports cmake targets for easy integration via CMake and vcpkg

**Comment by diehard2** [comment]
the following is working in an overlay port for me

portfile.cmake
```
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO Tessil/ordered-map
    REF v${VERSION}
    SHA512 1ae4f8876b13aaf5a9b08f8075299255a51e64fac8ca1c46813294e374b8c9334a7bd1b22618719fab2a8dced42be91e96d8b15595ce3dd8a6d726dadba52ce9
)


vcpkg_cmake_configure(
    SOURCE_PATH ${SOURCE_PATH}
    OPTIONS
        ${FEATURE_OPTIONS}
)

vcpkg_cmake_install()


file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```

vcpkg.json
```
{
    "name": "tessil-ordered-map",
    "version": "1.1.0",
    "homepage": "https://github.com/Tessil/ordered-map",
    "dependencies": [
        {
            "name": "vcpkg-cmake",
            "host": true
        },
        {
            "name": "vcpkg-cmake-config",
            "host": true
        }
    ]
}
```

**Comment by motazmuhammad** [comment]
it is already added under the name [tsl-ordered-map] the link is below





(https://github.com/Microsoft/vcpkg/tree/master/ports/tsl-ordered-map)[tsl-ordered-map](https://github.com/Microsoft/vcpkg/tree/master/ports/tsl-ordered-map)[tsl-ordered-map](https://github.com/Microsoft/vcpkg/tree/master/ports/tsl-ordered-map)
