### ISSUE TITLE
vcpkag not copying depended dll's for the project which built using sfml

### ISSUE THREAD

**Issue by mohandarsi** [Microsoft/vcpkg#3917]
i have installed sfml using following command
vcpkg install sfml
After creating new project  with following code, project built successfully,
#include <SFML/Graphics.hpp>
int main()
{
	sf::RenderWindow window(sf::VideoMode(200, 200), "SFML works!");
	sf::CircleShape shape(100.f);
	return 0;
}
But when i try to run, application threw following error.
The program cant start becuase freetype.dll is missing.
After copying all depended dlls into bin folder(where exe located), program ran expected.
it seems vcpkg is not copying all required dlls into output folder

**Comment by wangli28** [comment]
@mohandarsi Thanks for your feedback. I installed sfml successfully with VS 2017 15.9.10. I created new project with your code, I built and ran this project successfully. Please reopen a new issue if it is still a problem for you!

**Comment by liuaifu** [comment]
@wangli28 I found the /OUT option can't change.
I change it from
    `$(OutDir)$(TargetName)$(TargetExt)`
to
    `$(OutDir)$(TargetName)D$(TargetExt)`

The bug reappearance.
