### ISSUE TITLE
[skia] Unresolved external symbol SkSVGDOM::Builder::make

### ISSUE THREAD

**Issue by cosmin42** [microsoft/vcpkg#39186]
**Describe the bug**
The symbol for `sk_sp<SkSVGDOM> make(SkStream&) const;` is missing

**Environment**
- OS: WIndows
- Compiler: cl 19.40.33811
- IDE: Visual Studio 2022

**To Reproduce**
1. vcpkg install skia:x64-windows
2. Build a program that uses `SkSVGDOM::MakeFromStream(stream);`

**Expected behavior**
The build is successsful.

**Failure logs**
```
2>main.obj : error LNK2019: unresolved external symbol "public: class sk_sp<class SkSVGDOM> __cdecl SkSVGDOM::Builder::make(class SkStream &)const " (?make@Builder@SkSVGDOM@@QEBA?AV?$sk_sp@VSkSVGDOM@@@@AEAVSkStream@@@Z) referenced in function "public: static class sk_sp<class SkSVGDOM> __cdecl SkSVGDOM::MakeFromStream(class SkStream &)" (?MakeFromStream@SkSVGDOM@@SA?AV?$sk_sp@VSkSVGDOM@@@@AEAVSkStream@@@Z)
2>C:\Users\ionut\skia-sample\build-x64\Debug\SampleProjectExecutable.exe : fatal error LNK1120: 1 unresolved externals
2>Done building project "SampleProjectExecutable.vcxproj" -- FAILED.
```

**Additional context**

The build fails when the below code is run. I also attached a minimum reproducible example that can be run using this command:
`cmake -A x64 -B build-x64 -S . -DCMAKE_TOOLCHAIN_FILE=<your vcpkg location here>/vcpkg/scripts/buildsystems/vcpkg.cmake`

```
#include <stdio.h>

#include <include/core/SkBitmap.h>
#include <include/core/SkCanvas.h>
#include <include/core/SkStream.h>
#include <include/core/SkSurface.h>
#include <include/encode/SkPngEncoder.h>
#include <include/svg/SkSVGCanvas.h>
#include <modules/svg/include/SkSVGDOM.h>

#include <filesystem>
#include <fstream>

sk_sp<SkData> read_file(const char* path)
{
	std::ifstream file(path, std::ios::binary);
	file.seekg(0, std::ios::end);
	size_t size = file.tellg();
	file.seekg(0, std::ios::beg);

	sk_sp<SkData> data = SkData::MakeUninitialized(size);
	file.read((char*)data->writable_data(), size);
	return data;
}

int main()
{
	std::filesystem::path svgPath = "C:\\Users\\josep\\Desktop\\svg\\test.svg";

	sk_sp<SkData> svgData = read_file(svgPath.string().c_str());

	SkMemoryStream  stream(svgData);
	sk_sp<SkSVGDOM> svgDOM = SkSVGDOM::MakeFromStream(stream);

	return 0;
}


```

The CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.27)

project(SampleProject)

add_compile_options(/std:c++20)
find_package(unofficial-skia CONFIG REQUIRED)

add_executable(SampleProjectExecutable src/main.cpp)

target_link_libraries(SampleProjectExecutable PRIVATE unofficial::skia::skia)
```

[skia-sample.zip](https://github.com/user-attachments/files/15743412/skia-sample.zip)

**Comment by dg0yt** [comment]
Hm, skia svg lives in "modules", but I see little indication of our port building/installing this module in vcpkg CI for x64-windows.

In fact, it seems to be off by default in shared library linkage,
https://github.com/google/skia/blob/ad3c9f203f4e65d0070b1257f40479563e416c46/gn/skia.gni#L27
I don't know if it would work as a DLL.

**Comment by cosmin42** [comment]
The same issue is occurring when using the static triplet x64-windows-static.

I noticed that the source file for the said symbol can be found under a cleaning folder along with the whole component, it just seems to be discarded and not used in the final lib.

```
vcpkg/buildtrees/skia/src/1c27019d33-728a6df320.clean/modules/svg ((2024.04.26))
$ ls
BUILD.gn  include/  src/  svg.gni  tests/  utils/
```

**Comment by dg0yt** [comment]
That's not a "cleaning" folder, but the clean source dir, recreated before each build. (A different dir is used for `--editable` mode which reuse am existing (possibly edited) source dir.

And "modules" is the part which tells us that it is not expected to be in the main lib/target. You may need to link another lib/target. The static build has a `svg.lib`, and there should be a corresponding cmake config/target.

**Comment by cosmin42** [comment]
Actually skia seems to be working along with the -static triplet, I should have clean up the build. Thanks!
