### ISSUE TITLE
Problems with Boost build process (dynamic build is unusable)

### ISSUE THREAD

**Issue by chrullrich** [Microsoft/vcpkg#392]
There is something seriously wrong with the Boost build process right now. `vcpkg install boost:x86-windows` (same for x64-windows) builds a full set of DLLs and import libs, but for some reason it also builds a number of "normal" static libraries. The installation procedure then replaces the import libs with the static libraries, with the result that modules that use the libraries with "normal" static libs (chrono, exception, system, test_exec_monitor, timer, and unit_test_framework) will not link.

Example: 

    buildtrees\boost\x86-windows-rel\stage\lib:
    2016-12-06  15:57            29.184 boost_chrono-vc140-mt-1_62.dll
    2016-12-06  15:57            24.492 boost_chrono-vc140-mt-1_62.lib      (import library)
    2016-12-06  15:58         2.065.926 libboost_chrono-vc140-mt-1_62.lib   (static library)

    installed\x86-windows\bin:
    2016-12-06  15:57            29.184 boost_chrono-vc140-mt-1_62.dll

    installed\x86-windows\lib:
    2016-12-06  15:58         2.065.926 boost_chrono-vc140-mt-1_62.lib

The import library is gone, and the static lib has taken its place.

This is with vcpkg as of af9d82ce, starting with an empty `buildtrees`.

**Comment by alexkaratarakis** [comment]
I believe a545be80b4a5388e6cfde1ab9cd554bcaede4065 fixes the issue. 
Can you check if it works for you? Thanks!

**Comment by chrullrich** [comment]
Looking at the patch, I think it will fix the immediate issue. However, I'm not sure why it even arises, that is, why these stray static libraries are created at all. I have tried Boost builds outside of vcpkg, and it still happens there as well. I had the hypothesis that something in the build environment perhaps misled the Boost build system into creating them, so I tried on a "clean" system, with the same result.

Just to be sure, I have asked the boost-users mailing list why these static libraries (six in 1.62, two in 1.58, and each release in between seems to add one or two) are built at all. Mainly I'm worried that there may actually be a bug in Boost itself that somehow builds some code into static libs by mistake. As far as I can tell via dumpbin, there are some symbols that appear only in the DLLs and some that appear only in the statics, and I don't know why that should be. I'll report back as I get news on that.

**Comment by chrullrich** [comment]
I have not received final confirmation from the Boost project that I'm correct here, but I feel confident enough now. There are several reasons static libraries are created:

- exception: Boost.Exception can only be built statically.
- test_exec_monitor, timer, chrono, system: Boost.Test consists of several libraries, and one of them, test_exec_monitor, can only be built statically. It has a dependency on timer, which in turn depends on chrono and system. The other two libraries in Boost.Test, unit_test_framework and prg_exec_monitor, are correctly built as DLLs.
- unit_test_framework: Boost.Metaparse is a header-only library, but for some reason has a build configuration file (Jamfile) that references Boost.Test and causes the static library for unit_test_framework to be built (in addition to the other dependencies of Test in the item above).

Installing only those static libraries for which no DLL is built (that is, exception and test_exec_monitor) looks to be the best solution to have as complete a set of libraries in the non-static build as possible, even if two of them are statics. The only downside is that the test_exec_monitor static library stands out a bit among the import libraries, because it is more than 12 times as large as the rest put together.

**Comment by chrullrich** [comment]
This issue is fixed, and I've found the next one. Look out for the new bug, arriving in 5 ... 4 ... 3 ...

**Comment by Type1J** [comment]
Is there a list of which libraries are built statically and which are built dynamically?
