### ISSUE TITLE
[ffmpeg] Build error on x64-windows

### ISSUE THREAD

**Issue by thisiszy** [microsoft/vcpkg#39218]
`unsatisfied condition: __STDC_VERSION__ >= 201112L` error when building the ffmpeg. 

**Package**: ffmpeg[avcodec,avdevice,avfilter,avformat,core,swresample,swscale]:x64-windows@6.1.1#7

**Host Environment**: 
+ Host: Windows 11 Education 10.0.22631 Build 22631
+ Compiler: MSVC 14.40.33807
+ vcpkg repo: b27651341123a59f7187b42ef2bc476284afb310

The following patch did the trick. 

```
diff --git a/ports/ffmpeg/portfile.cmake b/ports/ffmpeg/portfile.cmake
index 72055b063..78b458895 100644
--- a/ports/ffmpeg/portfile.cmake
+++ b/ports/ffmpeg/portfile.cmake
@@ -609,7 +609,7 @@ endif()
 if(VCPKG_TARGET_IS_MINGW)
     set(OPTIONS "${OPTIONS} --extra_cflags=-D_WIN32_WINNT=0x0601")
 elseif(VCPKG_TARGET_IS_WINDOWS)
-    set(OPTIONS "${OPTIONS} --extra-cflags=-DHAVE_UNISTD_H=0")
+    set(OPTIONS "${OPTIONS} --extra-cflags=\"-DHAVE_UNISTD_H=0 -std=11\"")
 endif()
 
 vcpkg_find_acquire_program(PKGCONFIG)
```

**Comment by thisiszy** [comment]
> @thisiszy, thanks for posting this issue, could you provide the steps to reproduce?

Yes, I just used `git pull` to update my local vcpkg repo version and tried to use `vcpkg install ffmpeg` to install the ffmpeg. Then, the installation will fail during the `Build Release` phase.

**Comment by JonLiu1993** [comment]
I have successfully installed ffmpeg locally using the latest vcpkg. Which version of ffmpeg did you install?
````
-- Installing: F:/Feature-test/ffmpeg/packages/ffmpeg_x64-windows/share/ffmpeg/usage
-- Installing: F:/Feature-test/ffmpeg/packages/ffmpeg_x64-windows/share/ffmpeg/copyright
-- Performing post-build validation
Elapsed time to handle ffmpeg:x64-windows: 22 min
Total install time: 22 min
To use ffmpeg add the following to your CMake project:

    find_package(FFMPEG REQUIRED)
    target_include_directories(main PRIVATE ${FFMPEG_INCLUDE_DIRS})
    target_link_directories(main PRIVATE ${FFMPEG_LIBRARY_DIRS})
    target_link_libraries(main PRIVATE ${FFMPEG_LIBRARIES})
````
Could you provide the complete error log? Thanks

**Comment by thisiszy** [comment]
Sorry for the inconvenience. Yesterday, I fixed this by adding the ` -std=11` to the `extra-cflags`, but I can not reproduce it today anyway. I tried to uninstall and reinstall the ffmpeg and this error never happened again. Maybe this is due to my other packages and it was fixed after yesterday's successful build.

I'll close this issue.
