### ISSUE TITLE
bug on llvm

### ISSUE THREAD

**Issue by cjwddtc** [microsoft/vcpkg#3921]
The visual studio and the vcpkg is the lastest version yesterday, and I fount that after I install llvm:x64-windows,I try to use cmake to test the install of the llvm,and there is a error.
`CMake Error at D:/vcpkg/installed/x64-windows/share/llvm/LLVMExports.cmake:622 (message):
  The imported target "LTO" references the file

     "D:/vcpkg/installed/x64-windows/bin/LTO.dll"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "D:/vcpkg/installed/x64-windows/share/llvm/LLVMExports.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  D:/vcpkg/installed/x64-windows/share/llvm/LLVMConfig.cmake:144 (include)
  D:/vcpkg/scripts/buildsystems/vcpkg.cmake:247 (_find_package)
  CMakeLists.txt:4 (find_package)

-- Configuring incomplete, errors occurred!
See also "D:/code/ir/CMakeFiles/CMakeOutput.log".
`
this error can easy fix by just simply copy the LTO.dll in the buildtree to the D:/vcpkg/installed/x64-windows/bin/LTO.dll.

**Comment by JackBoosY** [comment]
Hi @cjwddtc , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.

**Comment by JackBoosY** [comment]
This issue has been resolved in some PR.
