### ISSUE TITLE
[readline-unix] Add CMake find module

### ISSUE THREAD

**Issue by aabellagm** [microsoft/vcpkg#39219]
### Is your feature request related to a problem? Please describe.

Readline for Windows uses find_package() but for Unix we use PkgConfig with a different name schema. I've tried to find in the documentation if it is preferred to have CMake modules or to keep the PkgConfig usage, but I didn't find anything.

### Proposed solution

Since my guess is that it is better to unify the ports to use find_package(), I've created a PR for your consideration, adding a new CMake find module for the unix port, following the same unofficial naming as for Windows.

**Comment by dg0yt** [comment]
> Readline for Windows uses find_package() but for Unix we use PkgConfig with a different name schema.

The `find_package` pattern is windows-only, vcpkg-only.

The PkgConfig pattern is portable, including windows. (The known limitation is poor multi-config support.)
