### ISSUE TITLE
[jsoncpp] Error during installing package

### ISSUE THREAD

**Issue by DmitryBelikov** [Microsoft/vcpkg#3922]
This error occurs during installation of any package.

C:\vcpkg>vcpkg install jsoncpp --triplet x64-windows
The following packages will be built and installed:
    jsoncpp[core]:x64-windows
Starting package 1/1: jsoncpp:x64-windows
Building package jsoncpp[core]:x64-windows...
-- Using cached C:/vcpkg/downloads/open-source-parsers-jsoncpp-1.8.4.tar.gz
-- Using source at C:/vcpkg/buildtrees/jsoncpp/src/1.8.4-15e6f27349
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: C:/vcpkg/buildtrees/jsoncpp/x64-windows-rel/vcpkg-parallel-configure
    See logs for more information:
      C:\vcpkg\buildtrees\jsoncpp\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:240 (vcpkg_execute_required_process)
  ports/jsoncpp/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package jsoncpp:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: jsoncpp:x64-windows
  Vcpkg version: 0.0.113-nohash

[config-x64-windows-out.log](https://github.com/Microsoft/vcpkg/files/2205102/config-x64-windows-out.log)

**Comment by Voskrese** [comment]
@DmitryBelikov 
`-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- broken`

`    LINK : fatal error LNK1104: cannot open file 'ucrtd.lib'`


когда msvc устанавлмвал, добавил нужные компоненты?

**Comment by JackBoosY** [comment]
Hi @DmitryBelikov , thanks for reporting this issue.
Jsoncpp built successfully in the latest version.
Please open a new issue if this is still a problem for you.
Thx,
