### ISSUE TITLE
[error: building osg:x64-windows failed with: BUILD_FAILED]

### ISSUE THREAD

**Issue by michaelcxd** [microsoft/vcpkg#39238]
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: E:/src/vcpkg/downloads/tools/cmake-3.29.2-windows/cmake-3.29.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: E:/src/vcpkg/buildtrees/osg/x64-windows-dbg
    See logs for more information:
      E:\src\vcpkg\buildtrees\osg\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/osg/portfile.cmake:135 (vcpkg_cmake_install)
  scripts/ports.cmake:175 (include)

error: building osg:x64-windows failed with: BUILD_FAILED
Elapsed time to handle osg:x64-windows: 1.1 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+osg
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[osg]+Build+error+on+x64-windows&body=Copy+issue+body+from+E%3A%2Fsrc%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by JonLiu1993** [comment]
Please provide error log:
````
E:\src\vcpkg\buildtrees\osg\install-x64-windows-dbg-out.log
````

**Comment by michaelcxd** [comment]
[Uploading install-x64-windows-dbg-out.log…]()

**Comment by michaelcxd** [comment]
> Please provide error log:
> 
> ```
> E:\src\vcpkg\buildtrees\osg\install-x64-windows-dbg-out.log
> ```

thank you for reply. I have submitted the log file.

**Comment by JonLiu1993** [comment]
Sorry, The link you provided opens without any error log:
[Uploading install-x64-windows-dbg-out.log…](https://github.com/microsoft/vcpkg/issues/39238)

**Comment by michaelcxd** [comment]
So, Why the building of osg was failed?

**Comment by JonLiu1993** [comment]
I can't reproduce your problem locally, so I need you to provide the error log to analyze and solve the error.

**Comment by michaelcxd** [comment]
-- Building x64-windows-dbg
CMake Error at scripts/cmake/[Uploading vcpkg_execute_build_process.cmake…]():134 (message):
    Command failed: E:/src/vcpkg/downloads/tools/cmake-3.29.2-windows/cmake-3.29.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: E:/src/vcpkg/buildtrees/osg/x64-windows-dbg
    See logs for more information:
      E:\src\vcpkg\buildtrees\osg\install-x64-windows-dbg-out.log

**Comment by michaelcxd** [comment]
This file maybe useful
[Uploading vcpkg_execute_build_process.cmake.txt…]()

**Comment by michaelcxd** [comment]
[Uploading install-x64-windows-dbg-out.log…]()

**Comment by michaelcxd** [comment]
This file maybe usefu;
[vcpkg_execute_build_process.cmake.txt](https://github.com/user-attachments/files/15839440/vcpkg_execute_build_process.cmake.txt)

**Comment by michaelcxd** [comment]
[Uploading install-x64-windows-dbg-out.log…]()

**Comment by michaelcxd** [comment]
[install-x64-windows-dbg-out.log](https://github.com/user-attachments/files/15841828/install-x64-windows-dbg-out.log)

**Comment by michaelcxd** [comment]
I submitte the log file again, can you see it?

**Comment by michaelcxd** [comment]
There is a Error in this log file:

E:\src\vcpkg\buildtrees\osg\src\raph-3.6.5-499ecaa6e1.clean\src\osgSim\SphereSegment.cpp(724): error C2059: syntax error: 'constant'

**Comment by michaelcxd** [comment]
thanks for everyone, i'v solved the problem by reinstalling vs2019

**Comment by michaelcxd** [comment]
> Are you using the latest vcpkg

Yes, i'm using the latest vcpkg, the version of osg is 3.6.5. Thank you very much, i'v solved the problem by reinstalling vc2019.
