### ISSUE TITLE
boost-core build failure

### ISSUE THREAD

**Issue by sbjw** [microsoft/vcpkg#39240]
### Operating system

windows-64

### Steps to reproduce the behavior

```Shell
version vcpkg-2024.05.24

vcpkg install boost-core
```

### Failure logs

port.cmake sha512 has error
```
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/core
    REF boost-${VERSION}
    SHA512 3a7be75e52f5c20830fccb9e7391a1e4556ebb072e6324df95b1ba38bed46e24f4c9f27a62a1099eddc90f2ac1ede083f0c850e2dc27fd42375d028516f675b3
    HEAD_REF master
)

```

the real is SHA512 a1e774c98b537dd42018742af68f5889af1afd4e6c9809399987124e56a3b9ae2f20e8173170bc6fc0ad76fb95e2da7b9d385a4037e9ee12011fc02bf8f7e009

**Comment by dg0yt** [comment]
Update your vcpkg.
https://github.com/microsoft/vcpkg/pull/38979

**Comment by sbjw** [comment]
thanks
