### ISSUE TITLE
[vcpkg] status file is not generated during first build

### ISSUE THREAD

**Issue by demconLMA** [microsoft/vcpkg#39249]
**Describe the bug**
When installing vcpkg I would expect `vcpkg_installed/vcpkg/status` to be generated, even if it runs from a "clean" install. Now it is generated only if install is called second time. Second install does no changes to vcpkg. 

**Environment**
- OS: windows
- Using manifest install [vcpkg.json](https://github.com/user-attachments/files/15803930/vcpkg.json)

**To Reproduce**
1. Delete `vcpkg_installed` if it exists.
2. Call `./vcpkg.exe install --x-wait-for-lock --triplet x64-windows`
3. File `vcpkg_installed/vcpkg/status` is not created /does not exist
4. Call `./vcpkg.exe install --x-wait-for-lock --triplet x64-windows`
5. File `vcpkg_installed/vcpkg/status` is created and contains expected info

**Expected behavior**
When doing clean install `vcpkg_installed/vcpkg/status` file is generated. So at step 3 `vcpkg_installed/vcpkg/status` should be already there. 

**Additional context**
I am using this file to check if reinstall of vcpkg is needed. Its creation date is compared to `vcpkg.json` modification date.

**Comment by jimwang118** [comment]
The function is designed to create a status file during reinstallation to record the update information after reinstallation.

**Comment by demconLMA** [comment]
Ah. Is there any other status/log file which would be updated every installation of vcpkg? I am trying to reduce number of vcpkg calls during our build process.
