### ISSUE TITLE
[openssl] Build error on x64-linux

### ISSUE THREAD

**Issue by DrmYuri** [microsoft/vcpkg#39253]
OS:linux        kenerl:5.14.0-452.el9.x86_64

detail:

command: vcpkg install  openssl
....
//before this line Is OK.
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/bash -c "V=1 ./../src/nssl-3.3.1-6a4778eae7.clean/vcpkg/configure  \"/usr/bin/perl\" \"/home/fuh_cs/Desktop/vcpkg/buildtrees/openssl/src/nssl-3.3.1-6a4778eae7.clean/Configure\" \"linux-x86_64\" \"enable-static-engine\" \"enable-capieng\" \"no-tests\" \"no-docs\" \"no-shared\" \"no-module\" \"no-apps\" \"--openssldir=/etc/ssl\" \"--libdir=lib\" \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"--debug\" \"--prefix=~/vcpkg/installed/x64-linux/debug\""
    Working Directory:~/vcpkg/buildtrees/openssl/x64-linux-dbg
    Error code: 2
    See logs for more information:
      ~/vcpkg/buildtrees/openssl/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:863 (vcpkg_execute_required_process)
  ports/openssl/unix/portfile.cmake:106 (vcpkg_configure_make)
  ports/openssl/portfile.cmake:71 (include)
  scripts/ports.cmake:175 (include)

error: building openssl:x64-linux failed with: BUILD_FAILED
Elapsed time to handle openssl:x64-linux: 2.4 s

then,the vcpkg/buildtrees/openssl/config-x64-linux-dbg-err.log：
+ /usr/bin/perl /home/fuh_cs/Desktop/vcpkg/buildtrees/openssl/src/nssl-3.3.1-6a4778eae7.clean/Configure linux-x86_64 enable-static-engine enable-capieng no-tests no-docs no-shared no-module no-apps --openssldir=/etc/ssl --libdir=lib --debug --prefix=/home/fuh_cs/Desktop/vcpkg/installed/x64-linux/debug
Can't locate FindBin.pm in @INC (you may need to install the FindBin module) (@INC contains: /usr/local/lib64/perl5/5.32 /usr/local/share/perl5/5.32 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /home/fuh_cs/Desktop/vcpkg/buildtrees/openssl/src/nssl-3.3.1-6a4778eae7.clean/Configure line 15.
BEGIN failed--compilation aborted at /home/fuh_cs/Desktop/vcpkg/buildtrees/openssl/src/nssl-3.3.1-6a4778eae7.clean/Configure line 15.

I make sure the vpckg is latest,and I have the right kernel header in my linux system,and my net have no vpn.
I think the core problem is below:
error: building openssl:x64-linux failed with: BUILD_FAILED

**Comment by dg0yt** [comment]
> ~~~
> Can't locate FindBin.pm in @inc (you may need to install the FindBin module)

**Comment by DrmYuri** [comment]
@dg0yt thank you very much ,this question is solved by your suggestion.I will close this issue.
