### ISSUE TITLE
[mysql-connector-cpp[jdbc]] 64-windows-static

### ISSUE THREAD

**Issue by jfnaugusto** [microsoft/vcpkg#39252]
Installing the mysql-connector-cpp[jdbc] will create the output library, not on the root "..\installed\x64-windows-static\lib" but under a subfolder.
Also it will label the .lib as mysqlcppconn8-static-mt-mt.lib instead of the usual mysqlcppconn-static.lib  (jdbc legacy).
This means that when trying to link you will get errors, to fix the copy of the .lib to the root lib folder must be done manually.

- OS: w11
- Compiler: vs2019/22

vcpkg install mysql-connector-cpp[jdbc]:x64-windows-static

Regards.

**Comment by JonLiu1993** [comment]
@jfnaugusto, Thanks for posting this issue, Regarding your first question, you think that the lib location exported by mysql-connector-cpp[jdbc] after installation is not under "..\installed\x64-windows-static\lib" but in a subdirectory? However, after installation, I found that it is indeed under "..\installed\x64-windows-static\lib"

![image](https://github.com/microsoft/vcpkg/assets/63675417/6ee29804-2f68-40fa-99e6-5100457b0c2e)

**Comment by jfnaugusto** [comment]
Hi, 
That lib is for the **mysql-connector-cpp**:x64-windows-static, and not for the **mysql-connector-cpp[jdbc]**:x64-windows-static (legacy one).
![Untitled](https://github.com/microsoft/vcpkg/assets/49069282/64885969-a377-4ca4-a8ab-35688c9d385f)
The later one get's installed in the vs14 folder.
That's also a reason why I think they should keep the "original" names to avoid this type of confusion.
mysqlcppconn8-static-mt.lib -> mysqlcppconn8-static.lib
mysqlcppconn8-static-mt-mt.lib -> mysqlcppconn-static.lib

Thanks.

**Comment by dudantas** [comment]
I am experiencing the same issue, but it only occurs with the static library. Is there any prediction or timeline for a fix?

**Comment by dg0yt** [comment]
I guess port maintenance wasn't careful enough with regard to the jdbc feature.
- The jdbc feature doesn't use the same lib name patching as the main lib.
- A serious problem for vcpkg: The connector-jdbc lib/target is created as a convenience lib via
  ~~~cmake
  merge_libraries(connector-jdbc jdbc)
  ~~~
  with
  ~~~cmake
  # merge_libraries()
  #   Merge several static libraries into single static or shared library.
  #   Includes all transitive dependencies of the libraries being merged.
  ~~~
  This duplicates at least the main lib symbols. The resulting redundancy is not desired - at least not for files which go directly to `/lib`.
  So for the jdbc feature in vcpkg, the connector-jdbc lib must be either created without merging, or the jdbc-enabled lib should *replace* the original lib, or the jdbc-enabled lib has to be put into subdir (`lib/manual-link`).

**Comment by dudantas** [comment]
![image](https://github.com/microsoft/vcpkg/assets/8551443/ba60c131-2258-4e3a-b901-0f1948aad28d)
![image](https://github.com/microsoft/vcpkg/assets/8551443/f31a932a-5d35-4b09-a720-9f09f467521b)
![image](https://github.com/microsoft/vcpkg/assets/8551443/65d181a0-d6e5-4dd7-949b-61de972652fc)

I'm currently working with CMake in Visual Studio (MySQL), and my setup is fully updated, including Vcpkg in manifest mode. However, I consistently encounter a specific error when attempting to build the static version of my project. The dynamic build, on the other hand, proceeds without any issues. Could this be related to how the static libraries are configured or a particular dependency that behaves differently in static context?

**Comment by dg0yt** [comment]
> Could this be related to how the static libraries are configured or a particular dependency that behaves differently in static context?

YES.

Some things are generally different with static library linkage:
 - There are transitive link lib requirements (unless using large "convenience libs"))
 - On Windows, package often different lib names due to conflict between static lib and import lib.

In vcpkg, we also see a inconsistent quality of ports and patches: some errors are not visible until libraries are actually used (missing link libs, wrong runtime lib), so they may go unnoticed by CI and maintainers.

**Comment by dudantas** [comment]
It seems to be linked to this issue as well? #37407

**Comment by mkdev-jaugusto** [comment]
I have no issues with the building of the jdbc static library, the only issue is that you have to manually copy the .lib to the root, to prevent linking errors.

The 37407 fixed that for the non jdbc lib, nevertheless I think that the libs should keep their orignal names.

mysqlcppconn8-static-mt.lib -> mysqlcppconn8-static.lib
mysqlcppconn8-static-mt-mt.lib -> mysqlcppconn-static.lib

Also imo there is no need to add the runtime to the name of the .libs (mt, etc.), since the triplets already creates folders for different runtimes.

> It seems to be linked to this issue as well? #37407

**Comment by dg0yt** [comment]
> the only issue is that you have to manually copy the .lib to the root, to prevent linking errors.

This issue should not exist, and it is a result of how this port builds libs. It needs reasonable modifications. Basically, there is no need to have two libs which are mostly identical. If the user asks for jdbc, the lib without jdbc should be replaced IMO.

Naming should be reviewed, too. `-mt` comes from upstream IIUC, and vcpkg mostly follows upstream. Except for harmonizing static and shared.
https://learn.microsoft.com/en-us/vcpkg/contributing/maintainer-guide#do-not-rename-binaries-outside-the-names-given-by-upstream

**Comment by jfnaugusto** [comment]
This can be closed, the latest version fixes the naming and the placement.
Thanks
