### ISSUE TITLE
`vcpkg_fixup_cmake_targets()` doesn't handle `XYZExports.cmake`

### ISSUE THREAD

**Issue by jarruda** [Microsoft/vcpkg#3925]
I'm trying to create my first port, a [TMX](https://github.com/baylej/tmx) file loading library.  It uses CMake for its build, and I'm also trying to use the package in a CMake project.

I eventually got through build and post build checks, but when I tried to use the library it failed during configuration.  The target appears to improperly reference the debug library path, not including the triplet in the vcpkg directory.

(note: swapped absolute path prefixes with ...)
```
CMake Error at .../vcpkg/installed/x64-windows-static/share/tmx/tmxExports.cmake:74 (message):
  The imported target "tmx" references the file

     ".../vcpkg/installed/debug/lib/tmx.lib"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     ".../vcpkg/installed/x64-windows-static/share/tmx/tmxExports.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  .../vcpkg/installed/x64-windows-static/share/tmx/tmxConfig.cmake:13 (include)
  .../vcpkg/scripts/buildsystems/vcpkg.cmake:247 (_find_package)
```

My knowledge of cmake export targets and how vcpkg uses them is a little weak, but I browsed through several ports and most just seem to use `vcpkg_fixup_cmake_targets` with no other alteration.

What's the cause of the problem and the recommended way to fix it? Thanks

edit: the portfile
```cmake
include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO baylej/tmx
    REF tmx_1.0.0
    HEAD_REF master
    SHA512 d045c45efd03f91a81dae471cb9ddc80d222b3ac52e13b729deeaf3e07d0a03b8e0956b30336ef410c72ddbbf33bea6811da5454b88d44b1db75683ef2a9383a
)

string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "dynamic" TMX_SHARED)

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -DBUILD_SHARED_LIBS=${TMX_SHARED}
)

vcpkg_install_cmake()
vcpkg_copy_pdbs()

vcpkg_fixup_cmake_targets(CONFIG_PATH "lib/cmake/tmx")

file(REMOVE_RECURSE
    ${CURRENT_PACKAGES_DIR}/debug/include
    ${CURRENT_PACKAGES_DIR}/debug/share
)

# Handle copyright
file(INSTALL ${SOURCE_PATH}/COPYING DESTINATION ${CURRENT_PACKAGES_DIR}/share/tmx RENAME copyright)
```

**Comment by jarruda** [comment]
Bump.   Is there a better place for community support?

**Comment by ericmitt** [comment]
Hey Jarruda. Just tried to reproduce your issue. I created the same portfile as you: build fine. Tried to use the tmx.h in a VStudio project work fine. So I think you're trying to use it from a CMake script: Could you share this script?

**Comment by ras0219-msft** [comment]
@jarruda Sorry for taking so long to get to this!

The issue you're encountering is a bug in our `vcpkg_fixup_cmake_targets()` script, which doesn't recognize cmake files named `*Exports.cmake` and thus doesn't apply the correct fixups to the file.

I have a branch [1] which fixes this bug and according to my tests makes your above port work flawlessly :). If you would like to work around the issue before I get the changes into master, you could rename the exports file, then run the fixup script, then rename it back:

```cmake
file(RENAME ${CURRENT_PACKAGES_DIR}/lib/cmake/tmx/tmxExports.cmake ${CURRENT_PACKAGES_DIR}/lib/cmake/tmx/tmxTargets.cmake)
vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/tmx)
file(RENAME ${CURRENT_PACKAGES_DIR}/share/tmx/tmxTargets.cmake ${CURRENT_PACKAGES_DIR}/share/tmx/tmxExports.cmake)
```

Once again, thanks for the perserverence!

[1] https://github.com/Microsoft/vcpkg/tree/dev/roschuma/enable-export-dot-cmake

**Comment by jarruda** [comment]
@ras0219-msft Right on, worked perfectly!  Thanks for the follow up.

Is there a separate issue tracking this bug?  I'd like to wait until it's resolved before submitting the port for inclusion.

**Comment by JackBoosY** [comment]
Hi @jarruda , if you have any question else, plz create a new issue.
Thx.
