### ISSUE TITLE
[libvpx] Build error on x64-windows-static

### ISSUE THREAD

**Issue by anan1213095357** [microsoft/vcpkg#39264]
### Operating system

error: building libvpx:x64-windows-static failed with: BUILD_FAILED Please ensure you're using the latest port files with `git pull` and `vcpkg update`. Then check for known issues at:     https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libvpx You can submit a new issue at:     https://github.com/microsoft/vcpkg/issues/new?title=[libvpx]+Build+error&body=Copy+issue+body+from+D%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Steps to reproduce the behavior

```Shell
error: building libvpx:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libvpx
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[libvpx]+Build+error&body=Copy+issue+body+from+D%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
```

### Failure logs

error: building libvpx:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libvpx
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[libvpx]+Build+error&body=Copy+issue+body+from+D%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

error: building libvpx:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libvpx
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[libvpx]+Build+error&body=Copy+issue+body+from+D%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by MonicaLiu0311** [comment]
Please run the following commands:
```
git pull https://github.com/microsoft/vcpkg.git master
./bootstrap-vcpkg.bat
```
The latest vcpkg version:
```
PS G:\vcpkg> ./vcpkg version
vcpkg package management program version 2024-06-10-02590c430e4ed9215d27870138c2e579cc338772

See LICENSE.txt for license information.
```

Please try the installation again. If the error persists, please provide the complete error log.

**Comment by MonicaLiu0311** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
