### ISSUE TITLE
[python3] Build error on x64-windows

### ISSUE THREAD

**Issue by ArtStealer** [microsoft/vcpkg#39262]
适用于 .NET Framework MSBuild 版本 17.8.5+b5265ef37
生成启动时间为 2024/6/13 8:54:51。

     1>项目“D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\pcbuild.proj”在节点 1 上(Rebuild 个目标)。
     1>项目“D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\pcbuild.proj”(1)正在节点 1 上生成“D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\python.vcxproj”(2) (Clean 个目标)。
     2>D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\python.props(205,5): error MSB4186: 静态方法调用语法无效:“[msbuild]::Multiply($(MajorVersionNumber), 16777216)”。未找到方法“[MSBuild]::Multiply”。 静态方法调用应采用以下形式:$([FullTypeName]::Method())，例如 $([System.IO.Path]::Combine(`a`, `b`))。请检查确保所有参数均已定义、其类型正确无误，并且按正确的顺序指定。 [D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\python.vcxproj]
     2>已完成生成项目“D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\python.vcxproj”(Clean 个目标)的操作 - 失败。
     1>项目“D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\pcbuild.proj”(1)正在节点 1 上生成“D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\pythonw.vcxproj”(3) (Clean 个目标)。
     3>D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\python.props(205,5): error MSB4186: 静态方法调用语法无效:“[msbuild]::Multiply($(MajorVersionNumber), 16777216)”。未找到方法“[MSBuild]::Multiply”。 静态方法调用应采用以下形式:$([FullTypeName]::Method())，例如 $([System.IO.Path]::Combine(`a`, `b`))。请检查确保所有参数均已定义、其类型正确无误，并且按正确的顺序指定。 [D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\pythonw.vcxproj]
     3>已完成生成项目“D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\pythonw.vcxproj”(Clean 个目标)的操作 - 失败。
     1>项目“D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\pcbuild.proj”(1)正在节点 1 上生成“D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\venvlauncher.vcxproj”(4) (Clean 个目标)。
     4>D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\python.props(205,5): error MSB4186: 静态方法调用语法无效:“[msbuild]::Multiply($(MajorVersionNumber), 16777216)”。未找到方法“[MSBuild]::Multiply”。 静态方法调用应采用以下形式:$([FullTypeName]::Method())，例如 $([System.IO.Path]::Combine(`a`, `b`))。请检查确保所有参数均已定义、其类型正确无误，并且按正确的顺序指定。 [D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\venvlauncher.vcxproj]
     4>已完成生成项目“D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\venvlauncher.vcxproj”(Clean 个目标)的操作 - 失败。
     1>项目“D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\pcbuild.proj”(1)正在节点 1 上生成“D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\venvwlauncher.vcxproj”(5) (Clean 个目标)。
     5>D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\python.props(205,5): error MSB4186: 静态方法调用语法无效:“[msbuild]::Multiply($(MajorVersionNumber), 16777216)”。未找到方法“[MSBuild]::Multiply”。 静态方法调用应采用以下形式:$([FullTypeName]::Method())，例如 $([System.IO.Path]::Combine(`a`, `b`))。请检查确保所有参数均已定义、其类型正确无误，并且按正确的顺序指定。 [D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\venvwlauncher.vcxproj]
     5>已完成生成项目“D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\venvwlauncher.vcxproj”(Clean 个目标)的操作 - 失败。
     1>已完成生成项目“D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\pcbuild.proj”(Rebuild 个目标)的操作 - 失败。

生成失败。

       “D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\pcbuild.proj”(Rebuild 目标) (1) ->
       “D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\python.vcxproj”(Clean 目标) (2) ->
         D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\python.props(205,5): error MSB4186: 静态方法调用语法无效:“[msbuild]::Multiply($(MajorVersionNumber), 16777216)”。未找到方法“[MSBuild]::Multiply”。 静态方法调用应采用以下形式:$([FullTypeName]::Method())，例如 $([System.IO.Path]::Combine(`a`, `b`))。请检查确保所有参数均已定义、其类型正确无误，并且按正确的顺序指定。 [D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\python.vcxproj]

       “D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\pcbuild.proj”(Rebuild 目标) (1) ->
       “D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\pythonw.vcxproj”(Clean 目标) (3) ->
         D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\python.props(205,5): error MSB4186: 静态方法调用语法无效:“[msbuild]::Multiply($(MajorVersionNumber), 16777216)”。未找到方法“[MSBuild]::Multiply”。 静态方法调用应采用以下形式:$([FullTypeName]::Method())，例如 $([System.IO.Path]::Combine(`a`, `b`))。请检查确保所有参数均已定义、其类型正确无误，并且按正确的顺序指定。 [D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\pythonw.vcxproj]

       “D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\pcbuild.proj”(Rebuild 目标) (1) ->
       “D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\venvlauncher.vcxproj”(Clean 目标) (4) ->
         D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\python.props(205,5): error MSB4186: 静态方法调用语法无效:“[msbuild]::Multiply($(MajorVersionNumber), 16777216)”。未找到方法“[MSBuild]::Multiply”。 静态方法调用应采用以下形式:$([FullTypeName]::Method())，例如 $([System.IO.Path]::Combine(`a`, `b`))。请检查确保所有参数均已定义、其类型正确无误，并且按正确的顺序指定。 [D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\venvlauncher.vcxproj]

       “D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\pcbuild.proj”(Rebuild 目标) (1) ->
       “D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\venvwlauncher.vcxproj”(Clean 目标) (5) ->
         D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\python.props(205,5): error MSB4186: 静态方法调用语法无效:“[msbuild]::Multiply($(MajorVersionNumber), 16777216)”。未找到方法“[MSBuild]::Multiply”。 静态方法调用应采用以下形式:$([FullTypeName]::Method())，例如 $([System.IO.Path]::Combine(`a`, `b`))。请检查确保所有参数均已定义、其类型正确无误，并且按正确的顺序指定。 [D:\Work\Develop\vcpkg\buildtrees\python3\x64-windows-rel\PCbuild\venvwlauncher.vcxproj]

    0 个警告
    4 个错误

已用时间 00:00:00.13

**Comment by JonLiu1993** [comment]
The project name does not recognize ".", please remove the "." in the project name and try again.

**Comment by ArtStealer** [comment]
> The project name does not recognize ".", please remove the "." in the project name and try again.

??? which project name contains "." ?
I just run "vcpkg install python3" or "vcpkg install boost"

**Comment by JonLiu1993** [comment]
Sorry, I replied to the wrong issue. I can't reproduce your problem locally. Could you please show me your steps to complete the reproduction? For example:
````
PS F:\Feature-test\vcpkg> ./vcpkg install python3 --editable
Computing installation plan...
The following packages are already installed:
python3:x64-windows@3.11.8#2
python3:x64-windows is already installed
Total install time: 5.9 ms
The package python3 is compatible with built-in CMake targets:

find_package(Python3 COMPONENTS Development REQUIRED)
target_link_libraries(main PRIVATE Python3::Python)

The package python3 provides a python interpreter that supports virtual environments:

>tools\python3\python.exe -m venv c:\path\to\venv
>set VIRTUAL_ENV=c:\path\to\venv
>set PATH=c:\path\to\venv\bin;%PATH%
>set PYTHONHOME=

See https://docs.python.org/3/library/venv.html for more details.
````

**Comment by sfhacker** [comment]
This issue looks disgusting!
