### ISSUE TITLE
vcpkg/scripts/test_ports/vcpkg-ci-openimageio/vcpkg.json is invalid

### ISSUE THREAD

**Issue by Chu-4hun** [microsoft/vcpkg#39276]
**Describe the bug**
`vcpkg.json` file in `vcpkg/scripts/test_ports/vcpkg-ci-openimageio` missing `,` character 

```json
{
  "name": "vcpkg-ci-openimageio",
  "version": "1",
  "description": "OpenImageIO features testing within CI.",
  "license": "MIT",
  "dependencies": [
    {
      "name": "openimageio",
      "features": [
        "ffmpeg",
        "freetype",
        "gif",
        "libraw",
        "opencv",
        "openjpeg",
        {
          "name": "pybind11",
          "platform": "!(windows & static)"
        } <------- missing , here
        "tools",
        "webp"
      ]
    }
  ]
}

```

**Environment**
- Any

**To Reproduce**
Open https://github.com/microsoft/vcpkg/blob/master/scripts/test_ports/vcpkg-ci-openimageio/vcpkg.json

**Expected behavior**
regular json array with ','

**Failure logs**
```
Parse error on line 19:
..."        }        "tools",        "we
---------------------^
Expecting 'EOF', '}', ',', ']', got 'STRING'
```

**Additional context**
---

**Comment by dg0yt** [comment]
https://github.com/microsoft/vcpkg-tool/pull/1435 should help to permanently prevent such problems.
