### ISSUE TITLE
[flatbuffers] respect the VCPKG_BUILD_TYPE var

### ISSUE THREAD

**Issue by jonatino** [microsoft/vcpkg#39284]
### Is your feature request related to a problem? Please describe.

Right now flatbuffers doesn't respect the `VCPKG_BUILD_TYPE` variable causing a `x64-windows-dbg`, `x64-windows-rel`, `x64-windows-static-release-rel` when my triplet is set to `x64-windows-static-release` which sets `VCPKG_BUILD_TYPE` to `release`. This causes slow build times needing to build 3 different version and since flatbuffers is a large repo, a significant amount of disk space is wasted. 

### Proposed solution

Update the `flatbuffers` vcpkg to properly respect the `VCPKG_BUILD_TYPE` environment variable to avoid useless builds and wasted disk space.

**Comment by dg0yt** [comment]
"A single build will consume files from up to two triplets: the target triplet and the host triplet."  
https://learn.microsoft.com/vcpkg/concepts/triplets

I guess what you really want is to set the host triplet.

**Comment by jonatino** [comment]
@dg0yt I tried setting those variables but it still results in 3 builds.

```
set VCPKG_HOST_TRIPLET=x64-windows-static-release
set VCPKG_TARGET_TRIPLET=x64-windows-static-release
```

![image](https://github.com/microsoft/vcpkg/assets/1808569/d435abc5-7a81-4136-b574-01688fb035ad)

**Comment by dg0yt** [comment]
If you do it right, it won't. 
The syntax seems to be `cmd` for environmentvariables. But the variable names are CMake. Try:

~~~
set VCPKG_DEFAULT_HOST_TRIPLET=x64-windows-static-release
~~~
https://learn.microsoft.com/de-de/vcpkg/users/config-environment#vcpkg_default_host_triplet

**Comment by jonatino** [comment]
> The syntax seems to be `cmd` for environment variables. But the variable names are for CMake input variables. Try:
> 
> ```
> set VCPKG_DEFAULT_HOST_TRIPLET=x64-windows-static-release
> ```
> 
> https://learn.microsoft.com/de-de/vcpkg/users/config-environment#vcpkg_default_host_triplet

That did it! Thank you. 

I'm not sure whether to leave this issue open as this is the only dependency I have that's required to have `VCPKG_DEFAULT_HOST_TRIPLET` set to only build `x64-windows-static-release-rel` as all the others do that just by using the ` `x64-windows-static-release` triplet.

**Comment by dg0yt** [comment]
> I'm not sure whether to leave this issue open.

There is no port bug here. The port does respect `VCPKG_BUILD_TYPE`.

There might be an issue with communication/learning about triplets and variables, but it is more between the lines at the moment.
