### ISSUE TITLE
Vcpkg unable to find meson on linux

### ISSUE THREAD

**Issue by MarkIanHolland** [Microsoft/vcpkg#3928]
Platform ubuntu
Steps to reproduce: vcpkg install libepoxy
Expected result: install successful
Actual result: [BUILD_FAILED](https://github.com/Microsoft/vcpkg/files/2210789/output.txt)

> Could not find meson.  Please install it via your package manager.

When vcpkg tries to find meson, it looks for the script ['meson.py](https://github.com/Microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_find_acquire_program.cmake#L131)', so it does not find the binary from apt, as 'meson'. When [I specified that the linux version is 'meson', it works for me](https://github.com/MarkIanHolland/vcpkg/blob/meson-madness/scripts/cmake/vcpkg_find_acquire_program.cmake#L133). Worth a PR? I also updated meson and added the references needed for it to display the package example too.

**Comment by Voskrese** [comment]
`python3 -m pip install meson` ?

**Comment by Voskrese** [comment]
`which meson` ?

**Comment by Voskrese** [comment]
xmm... add to ?
https://github.com/MarkIanHolland/vcpkg/blob/meson-madness/scripts/cmake/vcpkg_find_acquire_program.cmake#L133
```
add
    elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
      set(SCRIPTNAME meson)
else()
```
