### ISSUE TITLE
Support for accompanying .net assemblies

### ISSUE THREAD

**Issue by mmassing** [microsoft/vcpkg#3929]
I'm currently looking for a clean way to implement vcpkg-builds of dot-net assemblies (for the case where assemblies are generated as wrappers around the C++ libraries built by vcpkg).

Specifically, I have added a [csharp] feature to GDAL in oder to generate wrappers from the same
buildtree as the C++ libraries. 
Unfortunately, post-build validation will fail due to architecture mismatch (in this case, anycpu) and 
missing exports. I'm working around this by copying assemblies into a special assembly folder outside the vcpkg installed tree.

But I was wondering  if  the feature (admittetly somewhat borderline) could be supported by vcpkg,
e.g. by designating a directory (such as installed\<triplet>\dotnet) where postvalidation would use assembly-specific rules, i.e. ignore missing exports, and ignore the DLL architecture (or handle "anycpu" assemblies correctly).

Slightly related to #2974.

**Comment by ras0219-msft** [comment]
Thanks for the suggestion!

I think it probably makes the most sense to just always ignore "anycpu" assemblies during our post build checks. I _think_ it makes sense for now to put them into the `bin\` folder with native DLLs, but perhaps separating them would enable some better MSBuild integration?

Would you be interested in submitting a PR to ignore AnyCPU DLLs?

**Comment by mmassing** [comment]
Ok, great, I'll do that :-) Thanks for the quick feedback.

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen this issue.
