### ISSUE TITLE
[x64-windows-static] <tinyxml2>

### ISSUE THREAD

**Issue by ncook-hxgn** [microsoft/vcpkg#39296]
### Library name

tinyxml2

### Source repository URL

https://github.com/leethomason/tinyxml2

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

I almost hate to ask this

I need to have x64, win32,; debug, release; and static lib, shared lib permutations of tinyxml2 For Reasons.

Could you please implement 'features' for these?

**Comment by ncook-hxgn** [comment]
Sounds like the correct triplet is what I need, and features are the wrong tree to bark up.

I'm new to vcpkg, please forgive my ignorance. I've struggled with the vcpkg documentation last week and only just figured out the dance I have to do install a particular version of a library.

**Comment by autoantwort** [comment]
This library is already part of vcpkg: https://vcpkg.link/ports/tinyxml2
