### ISSUE TITLE
[python3] Build error on x64-linux

### ISSUE THREAD

**Issue by Akhasi1** [microsoft/vcpkg#39306]
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/bash -c "V=1 ./../src/v3.11.8-fe0ac5827a.clean/configure  \"--with-openssl=/home/lhk/forward-secure-cloud-storage/build/vcpkg_installed/x64-linux\" \"--without-ensurepip\" \"--with-suffix=\" \"--with-system-expat\" \"--without-readline\" \"--disable-test-modules\" \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"--with-pydebug\" \"vcpkg_rpath=/home/lhk/forward-secure-cloud-storage/build/vcpkg_installed/x64-linux/debug/lib\" \"--prefix=/home/lhk/forward-secure-cloud-storage/build/vcpkg_installed/x64-linux/debug\" \"--bindir=\\${prefix}/../tools/python3/debug/bin\" \"--sbindir=\\${prefix}/../tools/python3/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/python3\""
    Working Directory: /opt/vcpkg/buildtrees/python3/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /opt/vcpkg/buildtrees/python3/config-x64-linux-dbg-config.log
      /opt/vcpkg/buildtrees/python3/config-x64-linux-dbg-out.log
      /opt/vcpkg/buildtrees/python3/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:863 (vcpkg_execute_required_process)
  ports/python3/portfile.cmake:274 (vcpkg_configure_make)
  scripts/ports.cmake:191 (include)

error: building python3:x64-linux failed with: BUILD_FAILED
Elapsed time to handle python3:x64-linux: 19 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+python3
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[python3]+Build+error+on+x64-linux&body=Copy+issue+body+from+%2Fhome%2Flhk%2Fforward-secure-cloud-storage%2Fbuild%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md

-- Running vcpkg install - failed
CMake Error at /opt/vcpkg/scripts/buildsystems/vcpkg.cmake:899 (message):
  vcpkg install failed.  See logs for more information:
  /home/lhk/forward-secure-cloud-storage/build/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:148 (include)
  CMakeLists.txt:9 (project)

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage

**Comment by jimwang118** [comment]
Sorry, i can`t reproduce this issue locally. Can you provide the error log?
```
/opt/vcpkg/buildtrees/python3/config-x64-linux-dbg-config.log
/opt/vcpkg/buildtrees/python3/config-x64-linux-dbg-out.log
/opt/vcpkg/buildtrees/python3/config-x64-linux-dbg-err.log
```

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
