### ISSUE TITLE
[hwloc] build failure on windows

### ISSUE THREAD

**Issue by JWi3b3** [microsoft/vcpkg#39307]
### Operating system

Windows 11 Home

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
./vcpkg install hwloc:x64-windows
```

### Failure logs

# Console

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Users/Jan Wiebe/vcpkg/downloads/tools/msys2/212eb2bc95cd8a82/usr/bin/bash.exe" --noprofile --norc --debug -c "V=1 CPP='compile cl.exe -E' CC='compile cl.exe' CC_FOR_BUILD='compile cl.exe' CPP_FOR_BUILD='compile cl.exe -E' CXX_FOR_BUILD='compile cl.exe' CXX='compile cl.exe' RC='windres-rc rc.exe' WINDRES='windres-rc rc.exe' AR='ar-lib lib.exe' LD='link.exe -verbose' RANLIB=':' STRIP=':' NM='dumpbin.exe -symbols -headers' DLLTOOL='link.exe -verbose -dll' CCAS=':' AS=':' ./../src/loc-2.10.0-fb617e570c.clean/configure --build=x86_64-pc-mingw32 \"ac_cv_prog_cc_c99=\" \"--disable-plugin-dlopen\" \"HWLOC_LDFLAGS=-no-undefined\" \"--disable-libxml2\" \"--disable-opencl\" \"--disable-cairo\" \"--disable-cuda\" \"--disable-libudev\" \"--disable-levelzero\" \"--disable-nvml\" \"--disable-rsmi\" \"--disable-pci\" \"ac_cv_prog_ac_ct_STRIP=:\" \"gl_cv_double_slash_root=yes\" \"ac_cv_func_memmove=yes\" \"--disable-silent-rules\" \"--verbose\" \"--enable-shared\" \"--disable-static\" \"--prefix=/C/Users/Jan Wiebe/vcpkg/installed/x64-windows/debug\" \"--bindir=\\${prefix}/../tools/hwloc/debug/bin\" \"--sbindir=\\${prefix}/../tools/hwloc/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/hwloc\""
    Working Directory: C:/Users/Jan Wiebe/vcpkg/buildtrees/hwloc/x64-windows-dbg
    Error code: 2
    See logs for more information:
      C:\Users\Jan Wiebe\vcpkg\buildtrees\hwloc\config-x64-windows-dbg-config.log
      C:\Users\Jan Wiebe\vcpkg\buildtrees\hwloc\config-x64-windows-dbg-out.log
      C:\Users\Jan Wiebe\vcpkg\buildtrees\hwloc\config-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:863 (vcpkg_execute_required_process)
  ports/hwloc/portfile.cmake:22 (vcpkg_configure_make)
  scripts/ports.cmake:191 (include)

# log files
[config-x64-windows-dbg-config.log](https://github.com/user-attachments/files/15846138/config-x64-windows-dbg-config.log)
[config-x64-windows-dbg-err.log](https://github.com/user-attachments/files/15846139/config-x64-windows-dbg-err.log)
[config-x64-windows-dbg-out.log](https://github.com/user-attachments/files/15846140/config-x64-windows-dbg-out.log)

### Additional context

Possible problem: there is a space in the path of vcpkg:
"C:\Users\Jan Wiebe\vcpkg"

**Comment by WangWeiLin-MV** [comment]
>Possible problem: there is a space in the path of vcpkg:
"C:\Users\Jan Wiebe\vcpkg"

Yes, it appears from the error log that this is exactly the reason.

Please do not use a working directory with space ` `. Many packages can't handle it. You can create a new vcpkg directory in a non-space directory.

**Comment by JWi3b3** [comment]
Thank you! It conpiles, when I place the vcpkg folder in a path without spaces.
