### ISSUE TITLE
[zlib] x64-windows-static build failure

### ISSUE THREAD

**Issue by nnaem** [microsoft/vcpkg#39317]
### Operating system

Windows 11

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
`./vcpkg install zlib:x64-windows-static`
```

### Failure logs

```
-- Configuring x64-windows-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/vcpkg/buildtrees/zlib/x64-windows-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\zlib\config-x64-windows-static-dbg-CMakeCache.txt.log
      C:\vcpkg\buildtrees\zlib\config-x64-windows-static-rel-CMakeCache.txt.log
      C:\vcpkg\buildtrees\zlib\config-x64-windows-static-dbg-CMakeConfigureLog.yaml.log
      C:\vcpkg\buildtrees\zlib\config-x64-windows-static-rel-CMakeConfigureLog.yaml.log
      C:\vcpkg\buildtrees\zlib\config-x64-windows-static-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:269 (vcpkg_execute_required_process)
  ports/zlib/portfile.cmake:17 (vcpkg_cmake_configure)
  scripts/ports.cmake:191 (include)


error: building zlib:x64-windows-static failed with: BUILD_FAILED
Elapsed time to handle zlib:x64-windows-static: 1.3 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+zlib
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[zlib]+Build+error+on+x64-windows-static&body=Copy+issue+body+from+C%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
  ```
  
[config-x86-windows-static-dbg-CMakeCache.txt.log](https://github.com/user-attachments/files/15858212/config-x86-windows-static-dbg-CMakeCache.txt.log)
[config-x86-windows-static-dbg-CMakeConfigureLog.yaml.log](https://github.com/user-attachments/files/15858213/config-x86-windows-static-dbg-CMakeConfigureLog.yaml.log)
[config-x64-windows-static-out.log](https://github.com/user-attachments/files/15858214/config-x64-windows-static-out.log)
[config-x64-windows-static-rel-CMakeCache.txt.log](https://github.com/user-attachments/files/15858215/config-x64-windows-static-rel-CMakeCache.txt.log)
[config-x64-windows-static-rel-CMakeConfigureLog.yaml.log](https://github.com/user-attachments/files/15858216/config-x64-windows-static-rel-CMakeConfigureLog.yaml.log)

### Additional context

Fresh Windows 11 install.

**Comment by Cheney-W** [comment]
I am unable to reproduce this issue locally. To help me investigate the problem, could you please provide the following information:
1. What is your version of Visual Studio? Which components are installed?
2. What is your Windows SDK version?

**Comment by nnaem** [comment]
Hello @Cheney-W. 
1. My Visual Studio version is the latest 2022 Enterprise preview version (17.11.0 Preview 2.0). I installed all components from the "Workloads" tab in visual studio installer. I didn't modify the individual components tab. I also have Visual Studio Build Tools 2019 installed which has the "Desktop development with C++" workload installed, the windows SDK version selected in the individual components tab is older than the latest one.
2. ![image](https://github.com/microsoft/vcpkg/assets/66337470/00e00736-d184-491f-bd98-932110858802)

Thank you for taking your time to help me.

**Comment by AenBleidd** [comment]
@nnaem, check that you have these two installed in the 'Individual components' tab (might be different version for the VS2019, but the idea is the same):
![image](https://github.com/microsoft/vcpkg/assets/3234209/aac4b4a6-8d3b-47aa-9100-a3645ad81715)

**Comment by nnaem** [comment]
> @nnaem, check that you have these two installed in the 'Individual components' tab (might be different version for the VS2019, but the idea is the same): ![image](https://private-user-images.githubusercontent.com/3234209/340383530-aac4b4a6-8d3b-47aa-9100-a3645ad81715.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NDQ3MDYsIm5iZiI6MTcxODY0NDQwNiwicGF0aCI6Ii8zMjM0MjA5LzM0MDM4MzUzMC1hYWM0YjRhNi04ZDNiLTQ3YWEtOTEwMC1hMzY0NWFkODE3MTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTdUMTcxMzI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDY0ZWM0ODMwYjViMjU2MmViOTAxMDk1MWU1M2ZmZWI5MjY4ZjY1MzMzNThjZTAwZWRkNzk4ZWZkYjA1ZTQ1YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dSf1uXcifuMUd-ZN4ggpt8s8wTt6aB3Uy-wrjhHvcnM)

Oh my god I uninstalled Visual Studio build tools 2019 and it worked.. I don't even know why they were installed in the first place, I never used or installed them. Thank you so much.
