### ISSUE TITLE
[activemq-cpp] cmake configuration failure

### ISSUE THREAD

**Issue by generaltoto** [microsoft/vcpkg#39338]
### Operating system

Windows 11

### Compiler

MSVC 14.39.33519

### Steps to reproduce the behavior

My vcpkg.json

```json
{
  "dependencies": [
    "opencascade", // Not mandatory to reproduce the error, might also take a long time to build
    "nlohmann-json", // Also not mandatory 
    {
      "name": "protobuf",
      "version>=": "3.21.8"
    },
    {
      "name": "activemq-cpp",
      "version>=": "3.9.5#15"
    }
  ]
}
```

CMakeList.txt
```cmake
cmake_minimum_required (VERSION 3.28.0 FATAL_ERROR)

set(APP_NAME "GLTF_APP")

project (${APP_NAME} CXX)

set(CMAKE_CXX_STANDARD 20)

# ... SOME CODE

find_package(activemq-cpp CONFIG REQUIRED)
if (activemq-cpp_FOUND)
  message(STATUS "ActiveMQ-CPP found")
  # Note: This message is never called, since the find_package fails
endif()

# ... ADD EXECUTABLE AND SOME CODE

target_link_libraries(${APP_NAME} PRIVATE unofficial::activemq-cpp::apr unofficial::activemq-cpp::ws2 unofficial::activemq-cpp::rpcrt4 unofficial::activemq-cpp::mswsock)
```

Otherwise, consider this a basic c++ project. I am building all this using the following CMake commands : 

```Shell
# Configure 
cmake --preset=default -G "Visual Studio 17 2022"

# /!\ FAILS HERE

# Build
cmake --build build 
```

### Failure logs

```bash
CMake Error at C:/Users/thoma/workspaces/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package):
  Found package configuration file:

    C:/Users/thoma/workspaces/GLTF_GENERATOR/GLTF_APP/build/vcpkg_installed/x64-windows/share/activemq-cpp/activemq-cppConfig.cmake

  but it set activemq-cpp_FOUND to FALSE so package "activemq-cpp" is
  considered to be NOT FOUND.  Reason given by package:

  Activemq-cpp vcpkg install dependency failure: Did not find windows
  dependencies: WS2_32.lib, RpcRT4.lib, MsWsock.lib

Call Stack (most recent call first):
  CMakeLists.txt:24 (find_package)


-- Configuring incomplete, errors occurred!
```

### Additional context

The project builds fine as long as I remove ActiveMQ-cpp from the dependencies. 

I have tried adding winsock2 to the dependencies. It only removes the `WS2_32.lib` missing library. 

You may also see [this issue that was posted months ago](https://github.com/microsoft/vcpkg/issues/36615)

**Comment by dg0yt** [comment]
Reprise of #36615. I guess you need one Windows SDK more or less.

**Comment by generaltoto** [comment]
Yes that's why I mentioned the previous issue. It wasn't resolved, I just wanted to repost the problem to see if someone would come up with a new solution. 

What do you mean by "need one Windows SDK" ? I already am on Windows. I'm not sure to understand.

**Comment by WangWeiLin-MV** [comment]
Please build under `Developer Command Prompt` or `Developer PowerShell` which have specific environment variables set.

Or launch in [command line](https://learn.microsoft.com/en-us/visualstudio/ide/reference/command-prompt-powershell?view=vs-2022#command-line-arguments), for example:

```cmd
"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x64 -host_arch=x64
```

or

```pwsh
& 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\Launch-VsDevShell.ps1' -Arch arm64 -HostArch amd64
```

**Comment by generaltoto** [comment]
It worked when building under Developer Comand Prompt, thank you for this tips ! I will stay with this command prompt from now on. 

The build also worked, I had to redirect the path to `Ws2_32.Lib` though. It was first located in `vcpkg_installed\x64-windows\debug\lib\Ws2_32.Lib` (it wasn't there) when it was actually in `C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22000.0\um\x64\Ws2_32.Lib`. 

`RpcRT4.Lib` and `MsWSock.Lib` were located correctly in Windows Kits. I think it was due to the fact that I tried to manually import winsock2 with vcpkg  and removed it afterwards. The file might have been considered still there. I will come back to you if the error does come back when I do a clean build. 

Anyway, again, thank you very much.

**Comment by dg0yt** [comment]
> I had to redirect the path to `Ws2_32.Lib` though. It was first located in `vcpkg_installed\x64-windows\debug\lib\Ws2_32.Lib` (it wasn't there) when it was actually in `C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22000.0\um\x64\Ws2_32.Lib`.

This is the effect of the CMake config cache in your project.

**Comment by generaltoto** [comment]
> which have specific environment variables set.
Would you know which variables ? 
Hello again, I am trying to build the project with CLion (great CMake and Vcpkg integration) but the build fails with the same errors metionned above.

**Comment by grahamaj** [comment]
For anyone else still running into this (like me), it is the `LIB` environment variable that needs to be set.  The following fixed this issue for me when running outside of a developer command prompt:
```cmake
if(WIN32 AND NOT DEFINED ENV{LIB})
  set(ENV{LIB} "C:/Program Files (x86)/Windows Kits/10/Lib/${CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION}/um/x64")
endif()
find_package(activemq-cpp CONFIG REQUIRED)
```
NOTE: I only need to support the `x64` architecture.
