### ISSUE TITLE
[boost-filesystem] Error linking with boost-filesystem whilst using Emscripten

### ISSUE THREAD

**Issue by uniformization** [microsoft/vcpkg#39346]
**Describe the bug**
When compiling my application, the linking process fails because `boost-filesystem` was not compiled with `-pthread` on Emscripten. The error is as follows:

`wasm-ld: error: --shared-memory is disallowed by exception.cpp.o because it was not compiled with 'atomics' or 'bulk-memory' features.`

**Environment**
- OS: Windows
- Compiler: emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.61 (67fa4c16496b157a7fc3377afd69ee0445e8a6e3)

**To Reproduce**
1. Clone the demo I made for this issue: `git clone https://github.com/uniformization/boost-error-vcpkg-test.git`.
2. Run the preset then build it: `cmake --preset vcpkg-emscripten && cmake --build --preset emscripten`.
3. See error.

**Expected behavior**
The program should link successfully.

**Failure logs**
[build.log](https://github.com/user-attachments/files/15876793/build.log)

**Additional context**
I created a quick demo so any reviewer can see the setup I'm using: <https://github.com/uniformization/boost-error-vcpkg-test/>.

**Comment by Neumann-A** [comment]
Not really an issue with vcpkg but your assumption about the emscripten triplet. 
vcpkg just includes `include("${EMSCRIPTEN_ROOT}/cmake/Modules/Platform/Emscripten.cmake")` you however want to also have 
```
string(APPEND CMAKE_CXX_FLAGS " -sWASM=1 -sUSE_PTHREADS -pthread")
string(APPEND CMAKE_C_FLAGS " -sWASM=1 -sUSE_PTHREADS -pthread")
```
So write your own emscripten triplet/toolchain and add the required flags? (Or adjust CFLAGS and CXXFLAGS in your environment accordingly.)

**Comment by dg0yt** [comment]
> ```
> string(APPEND CMAKE_CXX_FLAGS " -sWASM=1 -sUSE_PTHREADS -pthread")
> string(APPEND CMAKE_C_FLAGS " -sWASM=1 -sUSE_PTHREADS -pthread")
> ```

AFAIU `-pthread` is all what is needed today:
https://emscripten.org/docs/porting/pthreads.html#pthreads-support

Why should this be handled in the triplet/toolchain for emscripten? This is normally detected/added by the packages, for other platforms. 

> Or adjust CFLAGS and CXXFLAGS in your environment accordingly.

Doesn't this have an effect on building host dependencies?

**Comment by Neumann-A** [comment]
> Why should this be handled in the triplet/toolchain for emscripten? This is normally detected/added by the packages, for other platforms.

If you read https://emscripten.org/docs/porting/pthreads.html#pthreads-support carefully:

`Pass the compiler flag -pthread when compiling any .c/.cpp files, AND when linking to generate the final output .js file.`

which basically means it is an all or nothing flag which also is inline with my experience with it while testing https://github.com/microsoft/vcpkg-tool/pull/1315 with wasm. You will just get errors that abc wasn't build with thread support. 

> Doesn't this have an effect on building host dependencies?

Hmm yes. So setting CFLAGS and CXXFLAGS in the triplet is required, e.g.:
```
set(ENV{CXXFLAGS} " -sWASM=1 -sUSE_PTHREADS -pthread")
set(ENV{CFLAGS}  " -sWASM=1 -sUSE_PTHREADS -pthread")
```

**Comment by uniformization** [comment]
> So write your own emscripten triplet/toolchain and add the required flags? (Or adjust CFLAGS and CXXFLAGS in your environment accordingly.)

This worked perfectly, thanks!
