### ISSUE TITLE
Error: Building package zlib:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Kevindyb** [Microsoft/vcpkg#3934]
Additionally, attach any relevant sections from the log files above.
Package: zlib:x86-windows
Vcpkg version: 0.0.113-nohash

--I did not find the location of the log folder....

**Comment by TheAifam5** [comment]
@Kevindyb look here: #3774 Its magic!

**Comment by Voskrese** [comment]
` Vcpkg version: 0.0.113-nohash` upgrade

**Comment by PhoebeHui** [comment]
@Kevindyb, does the issue persist? do you mind providing more information or logs? I just tried to install this lib, it installed successfully, the logs also generated correctly.

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
