### ISSUE TITLE
[qt] update to 6.7.2

### ISSUE THREAD

**Issue by tsondergaard** [microsoft/vcpkg#39377]
### Library name

qt

### New version number

6.7.2

### Other information that may be useful (release notes, etc...)

https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.7.2/release-note.md

**Comment by tsondergaard** [comment]
@Neumann-A, there are many nice fixes in this release. It also comes hot on the heels of 6.7.1 which is a good indication that they are important.

**Comment by ddriver** [comment]
> @Neumann-A, there are many nice fixes in this release. It also comes hot on the heels of 6.7.1 which is a good indication that they are important.

Equally good indication that they are rushing and behind schedule and are letting things slide.

Excessive patching is not a sign of good software health.
