### ISSUE TITLE
[boost-cobalt] Build error on x64-windows

### ISSUE THREAD

**Issue by Alanzelic** [microsoft/vcpkg#39387]
vcpkg install boost
Computing installation plan...
The following packages will be built and installed:
    boost:x64-windows@1.85.0#1
  * boost-cobalt:x64-windows@1.85.0#2
  * boost-compat:x64-windows@1.85.0#2
  * boost-compatibility:x64-windows@1.85.0#1
  * boost-contract:x64-windows@1.85.0#1
  * boost-convert:x64-windows@1.85.0#1
  * boost-coroutine2:x64-windows@1.85.0#1
  * boost-crc:x64-windows@1.85.0#1
  * boost-dll:x64-windows@1.85.0#1
  * boost-fiber:x64-windows@1.85.0#1
  * boost-flyweight:x64-windows@1.85.0#1
  * boost-format:x64-windows@1.85.0#1
  * boost-geometry:x64-windows@1.85.0#2
  * boost-gil:x64-windows@1.85.0#1
  * boost-hana:x64-windows@1.85.0#1
  * boost-heap:x64-windows@1.85.0#1
  * boost-histogram:x64-windows@1.85.0#1
  * boost-hof:x64-windows@1.85.0#1
  * boost-icl:x64-windows@1.85.0#1
  * boost-json:x64-windows@1.85.0#2
  * boost-lambda2:x64-windows@1.85.0#1
  * boost-local-function:x64-windows@1.85.0#1
  * boost-locale:x64-windows@1.85.0#2
  * boost-lockfree:x64-windows@1.85.0#1
  * boost-log:x64-windows@1.85.0#2
  * boost-metaparse:x64-windows@1.85.0#1
  * boost-msm:x64-windows@1.85.0#2
  * boost-multiprecision:x64-windows@1.85.0#2
  * boost-mysql:x64-windows@1.85.0#2
  * boost-nowide:x64-windows@1.85.0#2
  * boost-odeint:x64-windows@1.85.0#1
  * boost-outcome:x64-windows@1.85.0#2
  * boost-parameter-python:x64-windows@1.85.0#1
  * boost-pfr:x64-windows@1.85.0#2
  * boost-poly-collection:x64-windows@1.85.0#1
  * boost-polygon:x64-windows@1.85.0#1
  * boost-process:x64-windows@1.85.0#2
  * boost-program-options:x64-windows@1.85.0#2
  * boost-python[core,python3]:x64-windows@1.85.0#1
  * boost-qvm:x64-windows@1.85.0#1
  * boost-rational:x64-windows@1.85.0#1
  * boost-redis:x64-windows@1.85.0#2
  * boost-safe-numerics:x64-windows@1.85.0#1
  * boost-scope-exit:x64-windows@1.85.0#1
  * boost-stacktrace:x64-windows@1.85.0#2
  * boost-statechart:x64-windows@1.85.0#1
  * boost-stl-interfaces:x64-windows@1.85.0#1
  * boost-test:x64-windows@1.85.0#1
  * boost-timer:x64-windows@1.85.0#2
  * boost-type-erasure:x64-windows@1.85.0#1
  * boost-units:x64-windows@1.85.0#1
  * boost-url:x64-windows@1.85.0#1
  * boost-vmd:x64-windows@1.85.0#1
  * boost-wave:x64-windows@1.85.0#2
  * boost-yap:x64-windows@1.85.0#1
  * expat:x64-windows@2.6.2
  * libffi:x64-windows@3.4.6
  * openssl:x64-windows@3.3.1
  * pkgconf:x64-windows@2.2.0
  * python3:x64-windows@3.11.8#3
  * sqlite3[core,json1]:x64-windows@3.46.0#1
  * vcpkg-cmake-get-vars:x64-windows@2023-12-31
  * vcpkg-get-python:x64-windows@2024-06-08
  * vcpkg-msbuild:x64-windows@2023-08-08
  * vcpkg-pkgconfig-get-modules:x64-windows@2024-04-03
  * vcpkg-tool-meson:x64-windows@1.3.2#6
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
-- Automatically setting %HTTP(S)_PROXY% environment variables to "127.0.0.1:7890".
Compiler found: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from C:\Users\37097\AppData\Local\vcpkg\archives in 4.03 ms. Use --debug to see more details.
Installing 1/66 boost-cobalt:x64-windows@1.85.0#2...
Building boost-cobalt:x64-windows@1.85.0#2...
-- Using cached boostorg-cobalt-boost-1.85.0.tar.gz.
-- Cleaning sources at C:/Users/37097/vcpkg/buildtrees/boost-cobalt/src/ost-1.85.0-74ba267639.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/37097/vcpkg/downloads/boostorg-cobalt-boost-1.85.0.tar.gz
-- Using source at C:/Users/37097/vcpkg/buildtrees/boost-cobalt/src/ost-1.85.0-74ba267639.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/Users/37097/vcpkg/downloads/tools/cmake-3.29.2-windows/cmake-3.29.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j33
    Working Directory: C:/Users/37097/vcpkg/buildtrees/boost-cobalt/x64-windows-dbg
    See logs for more information:
      C:\Users\37097\vcpkg\buildtrees\boost-cobalt\install-x64-windows-dbg-out.log
      C:\Users\37097\vcpkg\buildtrees\boost-cobalt\install-x64-windows-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  installed/x64-windows/share/vcpkg-boost/boost-install.cmake:65 (vcpkg_cmake_install)
  ports/boost-cobalt/portfile.cmake:12 (boost_configure_and_install)
  scripts/ports.cmake:191 (include)

error: building boost-cobalt:x64-windows failed with: BUILD_FAILED
Elapsed time to handle boost-cobalt:x64-windows: 1.2 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-cobalt
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[boost-cobalt]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2FUsers%2F37097%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by Alanzelic** [comment]
![微信图片_20240619213416](https://github.com/microsoft/vcpkg/assets/77497590/8096bce0-ea7d-4710-b045-49ebfc9ea9fd)

**Comment by dg0yt** [comment]
> ` Installing 1/66 boost-cobalt:x64-windows@1.85.0#2...`

If this is the first package to be installed, you may need to update the *installed* packages first. There are helper scripts for boost which come before the actual ports.

**Comment by MonicaLiu0311** [comment]
If you still fail after trying above operation, please provide the detailed log:
> ```
> See logs for more information:
> C:\Users\37097\vcpkg\buildtrees\boost-cobalt\install-x64-windows-dbg-out.log
> C:\Users\37097\vcpkg\buildtrees\boost-cobalt\install-x64-windows-dbg-err.log
> ```

**Comment by MonicaLiu0311** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
