### ISSUE TITLE
[sqlite3] Lack of DB recovery feature.

### ISSUE THREAD

**Issue by STVHA** [microsoft/vcpkg#39396]
### Is your feature request related to a problem? Please describe.

I would do recover a corrupt database, without this feature I could not do that.
_sqlite3 corrupted-db.db ".recover" | sqlite3 recovered-db.db_

### Proposed solution

Please support this feature and provide an optional argument for it, some thing like "recovery" as below
_vcpkg install sqlite3[core,recovery]:x64-windows_

**Comment by jimwang118** [comment]
The recovery function is already included in the existing installation of sqlite3. You should call the corresponding function interface (global_recover) to implement this function.

**Comment by STVHA** [comment]
No it isn't. When I run from console: "sqlite3 corrupted-db.db ".recover" | sqlite3 recovered-db.db", the error says ".recover" not found, that means the recovery feature was not enabled by vcpkg when it built sqlite3.exe. Also the ".help" command does not show ".recover" in the supported list.

Additionally the function you mentioned sqlite3_global_recover() is deprecated that SQLite docs recommend not to use and it does not relate with what I asked.
