### ISSUE TITLE
provide upgrade for boost-di 1.0.2

### ISSUE THREAD

**Issue by themagnet** [Microsoft/vcpkg#3939]
please provide upgrade for boost-di 1.0.2
this support supports msvc-2017. http://boost-experimental.github.io/di/CHANGELOG/index.html#-102-2018-01-04

**Comment by jrunestone** [comment]
I opened a PR for this: https://github.com/Microsoft/vcpkg/pull/3988

**Comment by themagnet** [comment]
Thanks for your effort.
Fyi: Unfortunately version 1.0.2 still has issues with msvc-2017. 
Manually integrating the changes from https://github.com/boost-experimental/di/issues/326 helped.

**Comment by jrunestone** [comment]
I guess this particular issue can now be closed though! @themagnet
