### ISSUE TITLE
Qt include issues with Vcpkg & Visual Studio 2022

### ISSUE THREAD

**Issue by 3UR** [microsoft/vcpkg#39402]
I am using Visual Studio 2022 & Vcpkg is manfiest mode.

The issue is that one of my projects is using Qt 5 and when I do for example `#include <qt5/QtCore/QUrl>` it will include fine but `qt5/QtCore/QUrl.h` its self is trying to include things from Qt 5 but is not using `qt5/` so it is unable to find them headers

I assumed I did not need anything in `Additional Include Directories` but I am unsure now if I need to add Qt 5? Some projects such as Boost are fine it is only Qt I have this issue with.

I hope I explained the issue fine if someone has the answer please let me know.

**DISREGARD THIS ABOVE AND PLEASE CHECK MY LATEST COMMENT I HAVE A NEW ISSUE RELATED TO INCLUDES**

> Okay so I came across another issue `vcpkg_installed\x86-windows\x86-windows\include\qt5\QtGui\5.15.13\QtGui\private\qtguiglobal_p.h(55,10): error C1083: Cannot open include file: 'QtCore/private/qglobal_p.h': No such file or directory`
> 
> This happens because for whatever reason private is inside a different folder `vcpkg_installed\x86-windows\x86-windows\include\qt5\QtCore\5.15.13\QtCore\private`
> 
> Why is the folder like this? I don't think this is normal espically if the library headers don't even expect it to be like this 🤔
> 
> Anyone know the solution, let me know

**Comment by 3UR** [comment]
For now I added `$(VcpkgManifestRoot)\vcpkg_installed\$(VcpkgTriplet)\$(VcpkgTriplet)\include\qt5` to my additional includes and it seems to work BUT if I did make a mistake and this is not the correct way to resolve it let me know!

**Comment by Osyotr** [comment]
Yeah MSBuild doesn't have ways to figure out qt5's include dirs so you have to do it manually.

**Comment by dg0yt** [comment]
Note: this is a frequent problem with msbuild. Package publish include dirs via cmake, pkgconfig, or config scripts. There is no tool to magically transfer this into msbuild projects.

**Comment by 3UR** [comment]
> Yeah MSBuild doesn't have ways to figure out qt5's include dirs so you have to do it manually.



> Note: this is a frequent problem with msbuild. Package publish include dirs via cmake, pkgconfig, or config scripts. There is no tool to magically transfer this into msbuild projects.

Alright thanks

**Comment by 3UR** [comment]
Okay so I came across another issue `vcpkg_installed\x86-windows\x86-windows\include\qt5\QtGui\5.15.13\QtGui\private\qtguiglobal_p.h(55,10): error C1083: Cannot open include file: 'QtCore/private/qglobal_p.h': No such file or directory`


This happens because for whatever reason private is inside a different folder `vcpkg_installed\x86-windows\x86-windows\include\qt5\QtCore\5.15.13\QtCore\private`

Why is the folder like this? I don't think this is normal espically if the library headers don't even expect it to be like this 🤔 

Anyone know the solution, let me know

**Comment by 3UR** [comment]
I will attempt to add `$(VcpkgManifestRoot)\vcpkg_installed\$(VcpkgTriplet)\$(VcpkgTriplet)\include\qt5\QtCore\5.15.13` to additional includes because this seems like the only way to resolve it which makes sense

**Comment by Osyotr** [comment]
You should also add `vcpkg_installed\x86-windows\x86-windows\include\qt5\mkspecs\win32-msvc` and maybe each individual module, too.
If you use private Qt API, you should also add `...\QtCore\5.15.13`.

**Comment by 3UR** [comment]
> You should also add `vcpkg_installed\x86-windows\x86-windows\include\qt5\mkspecs\win32-msvc` 
To Additional Include Directories?

> If you use private Qt API, you should also add `...\QtCore\5.15.13`.
Where shoudl this go?

**Comment by 3UR** [comment]
My includes are getting filled now due to library headers including private stuff, Some of the library headers also just do `private/xxx.h` so I have to do 

`$(VcpkgManifestRoot)\vcpkg_installed\$(VcpkgTriplet)\$(VcpkgTriplet)\include\qt5\QtConcurrent\5.15.13` and `$(VcpkgManifestRoot)\vcpkg_installed\$(VcpkgTriplet)\$(VcpkgTriplet)\include\qt5\QtConcurrent\5.15.13\QtConcurrent`

due to inconsitency with library headers 😦


This is how my includes to QTitanRibbon currently looks due to this:
![image](https://github.com/microsoft/vcpkg/assets/76826837/4694a752-1729-4c87-98ed-fb8699ad7714)

**Comment by Osyotr** [comment]
This is the same set of include directories I've been using in my project (also using QTitanRibbon LOL)

**Comment by 3UR** [comment]
> > This is the same set of include directories I've been using in my project (also using QTitanRibbon LOL)
> 
> By any chance are you using Qt 5? if so have I missed any because some library headers reference stuff like this:
> 
> 
> `#include "private/qrasterdefs_p.h"`
> 
> 
> `#include <QtGui/private/qtguiglobal_p.h>`
> 
> At this point I may just end up going and also adding another set to includes like
> 
> `$(VcpkgManifestRoot)\vcpkg_installed\$(VcpkgTriplet)\$(VcpkgTriplet)\include\qt5\QtConcurrent\5.15.13\QtCore` etc

Ended up doing that if it resolves the issue then it'll be fine it is pretty ugly but I don't think I have any other options
![image](https://github.com/microsoft/vcpkg/assets/76826837/9e0124a9-afd1-4abf-8303-df95b2e6422d)

**Comment by 3UR** [comment]
Ribbon builds fine now, I will keep this open to see if anyone has any suggestions but for now I guess this is okay

**Comment by Neumann-A** [comment]
The only true advice here is: when using Qt, use CMake. (or QMake when using Qt5)

> There is no tool to magically transfer this into msbuild projects.

There could be ;). Something something could generate props files from CMake or pc files and import that magically into the project. vcpkg_msbuild_* already does that for pc files internally.

**Comment by JonLiu1993** [comment]
This issue appears to have been resolved, closing this issue.
