### ISSUE TITLE
[openssl] update openssl lts from 3.0.8 to latest (current 3.0.13)

### ISSUE THREAD

**Issue by liudongmiao** [microsoft/vcpkg#39417]
### Is your feature request related to a problem? Please describe.

In some cases, openssl lts is preferred.

For example, in [github actions runner-images](https://github.com/actions/runner-images), they offer following openssl:
- ubuntu-24.04 (next ubuntu-latest), openssl 3.0.13, latest lts
- windows-latest, openssl 1.1.1w, previous lts (it's not in vcpkg)
- macos-latest, openssl 1.1.1w, previous lts, however, homebrew offer lts version

### Proposed solution

Update openssl 3.0.X to latest (current 3.0.13).

**Comment by jimwang118** [comment]
Openssl has been updated to version 3.3.1.

**Comment by liudongmiao** [comment]
@jimwang118 I know the latest openssl stable is 3.3.1. However, I'm discussing the lts version of openssl.
For production use, many distro include debian, ubuntu, windows-latest use the lts version instead latest stable.

**Comment by dg0yt** [comment]
@liudongmiao 
This vcpkg registry doesn't offer that kind of forking the linear version records. You have to use an "overlay port" (or add your own registry) in that case. You have to create that port yourself. You can start with a copy of the last version 3.0.x from the vcpkg registry.

**Comment by liudongmiao** [comment]
@jimwang118 @dg0yt Yes, I can use manifest to use 3.0.X, however the latest lts in vcpkg is 3.0.8, not the latest 3.0.13.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
