### ISSUE TITLE
Install of x64-windows for gdal fails cannot download icu4c

### ISSUE THREAD

**Issue by calebbuahin** [Microsoft/vcpkg#3941]
The link to download the icu4c source is broken. Does anyone have a work around ? 

Building package icu[core]:x64-windows...
-- Downloading http://download.icu-project.org/files/icu4c/61.1/icu4c-61_1-src.zip...
-- Downloading http://download.icu-project.org/files/icu4c/61.1/icu4c-61_1-src.zip... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:151 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/icu/portfile.cmake:22 (vcpkg_download_distfile)
  scripts/ports.cmake:71 (include)

Error: Building package icu:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x64-windows
  Vcpkg version: 0.0.113-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by ldsangr3** [comment]
Maybe not availble when you try....
Try againn....is back i thing

**Comment by calebbuahin** [comment]
It is indeed back up. Thanks!
