### ISSUE TITLE
[openvino] update to 2024.2.0

### ISSUE THREAD

**Issue by hhxdestiny** [microsoft/vcpkg#39423]
### Library name

openvino

### New version number

2024.2.0

**Comment by WangWeiLin-MV** [comment]
The port has been updated in #39383

Please try with latest vcpkg.

**Comment by hhxdestiny** [comment]
> The port has been updated in #39383
> 
> Please try with latest vcpkg.

Thank you, but when I updated the vcpkg master branch and installed openvino static, it failed!
```
vcpkg install openvino:x64-windows-static failed!
```
