### ISSUE TITLE
[skia] update to 127

### ISSUE THREAD

**Issue by r-tmp** [microsoft/vcpkg#39446]
### Library name

skia

### New version number

127

### Other information that may be useful (release notes, etc...)

https://skia.googlesource.com/skia/+/refs/heads/main/RELEASE_NOTES.md

**Comment by r-tmp** [comment]
Very sorry to be a pest, any ETA on this?

**Comment by WangWeiLin-MV** [comment]
The two PR haven't fixed yet. Error log can be [downloaded here](https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/104272/artifacts?artifactName=failure%20logs%20for%20x64-windows&api-version=7.1&%24format=zip)

**Comment by dg0yt** [comment]
FTR the blocker is (probably) icu from Windows SDK instead of icu from vcpg being picked in the link step. This took some time to resolve in the past, and it is difficult to resolve with only the CI logs.
