### ISSUE TITLE
[libmysql] Build error on x64-windows

### ISSUE THREAD

**Issue by horrzs** [microsoft/vcpkg#39457]
Package: libmysql:x64-windows@8.0.34#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.29.30154.0
-    vcpkg-tool version: 2024-06-10-02590c430e4ed9215d27870138c2e579cc338772
    vcpkg-scripts version: c4467cb68 2024-06-21 (19 hours ago)

**To Reproduce**

`vcpkg install poco[crypto,mariadb,mysql,netssl,pdf,postgresql,sqlite3]`

**Failure logs**

```
CMake Error at ports/libmysql/portfile.cmake:2 (message):
  FATAL ERROR: libmysql and libmariadb are incompatible.
Call Stack (most recent call first):
  scripts/ports.cmake:191 (include)



```

**Comment by dg0yt** [comment]
> FATAL ERROR: libmysql and libmariadb are incompatible.

Choose one, not both.

**Comment by sfhacker** [comment]
@horrzs Change your medication!

**Comment by horrzs** [comment]
> @horrzs Change your medication!

Change you
