### ISSUE TITLE
integrate with powershell is not working

### ISSUE THREAD

**Issue by ldsangr3** [microsoft/vcpkg#3945]

**Comment by Voskrese** [comment]
What's the conclusion? You can more poinformativnej your complaint

**Comment by ldsangr3** [comment]
I try use integration poweshell, after restar...i have the next error

signed. You cannot run this script on the current system. For more information about running scripts and setting
execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:3
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by wangli28** [comment]
same with #5413

**Comment by wangli28** [comment]
Thanks for posting this issue! Duplicate with #5413, so I am closing this issue for now.
