### ISSUE TITLE
[DCMTK] build success, but it runs failure in triplte x64-windows-static-md

### ISSUE THREAD

**Issue by xb284524239** [microsoft/vcpkg#39477]
### Operating system

Windows 10

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
// 1、vcpkg.json
{
  "dependencies": [
    {
      "name": "dcmtk",
      "features": [
        "zlib"
      ]
    }
  ]
}

// 2、CMakelists.txt
cmake_minimum_required(VERSION 3.29.0)

# vcpkg init config
set(VCPKG_HOST_TRIPLET      x64-windows-static-md)
set(VCPKG_TARGET_TRIPLET    x64-windows-static-md)
include(C:/CXXThirdParty/vcpkg/scripts/buildsystems/vcpkg.cmake)

project(Stork VERSION 0.1.1 LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_INCLUDE_CURRENT_DIR ON)

add_executable(Stork main.cpp)

# DCMTK
find_package(DCMTK CONFIG REQUIRED)
target_link_libraries(Stork PRIVATE DCMTK::DCMTK)
if ("${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}" STREQUAL "/")
    message(WARNING "No vcpkg install dir found, DCMTK definitions are not set")
else()
    target_compile_definitions(${PROJECT_NAME} PUBLIC
		"DCMTK_PREFIX=${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}"
		"DCM_DICT_DEFAULT_PATH=${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/share/dcmtk-3.6.8/dicom.dic:${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/share/dcmtk-3.6.8/private.dic"
		"DEFAULT_CONFIGURATION_DIR=${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/etc/dcmtk-3.6.8/"
		"DEFAULT_SUPPORT_DATA_DIR=${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/share/dcmtk-3.6.8/"
    )
endif()

// 3、main.cpp

#include <dcmtk/dcmdata/dcfilefo.h>
#include <dcmtk/ofstd/ofcond.h>
#include <iostream>
int main(int argc, char** argv) {
    DcmFileFormat format;
    format.loadFile(R"(C:\test.dcm)");

    // this code runs failure in triplet x64-windows-static-md;
    // but it runs well in triplet x64-windows
    OFCondition ofc = format.convertToUTF8();
    std::cout << "convertToUTF8: " << ofc.good() << ", text: " << ofc.text();
}
```

### Failure logs

```
W: Failed to open oficonv data file 'esdb\esdb.alias.db', check environment variable DCMICONVPATH
W: Failed to open oficonv data file 'esdb\esdb.alias', check environment variable DCMICONVPATH
W: Failed to open oficonv data file 'esdb\esdb.dir.db', check environment variable DCMICONVPATH
W: Failed to open oficonv data file 'esdb\esdb.dir', check environment variable DCMICONVPATH
convertToUTF8:  false , text:  Cannot open character encoding: Invalid argument
```

### Additional context

`format.convertToUTF8(); ` runs failure in triplet x64-windows-static-md, but it runs well in triplet x64-windows

**Comment by JonLiu1993** [comment]
I reproduced the problem using the file you provided and got a different error：
````
F:\Feature-test\dcmt\build>cmake --build .
MSBuild version 17.10.4+10fbfbf2e for .NET Framework

  Checking Build System
  Building Custom Rule F:/Feature-test/dcmt/CMakeLists.txt
  main.cpp
F:\Feature-test\dcmt\main.cpp(2,5): error C2065: 'DcmFileFormat': undeclared identifier [F:\Feature-test\dcmt\build\Stork.vcxproj]
F:\Feature-test\dcmt\main.cpp(2,19): error C2146: syntax error: missing ';' before identifier 'format' [F:\Feature-test\dcmt\build\Stork.vcxproj]
F:\Feature-test\dcmt\main.cpp(2,19): error C2065: 'format': undeclared identifier [F:\Feature-test\dcmt\build\Stork.vcxproj]
F:\Feature-test\dcmt\main.cpp(3,5): error C2065: 'format': undeclared identifier [F:\Feature-test\dcmt\build\Stork.vcxproj]
F:\Feature-test\dcmt\main.cpp(7,5): error C2065: 'OFCondition': undeclared identifier [F:\Feature-test\dcmt\build\Stork.vcxproj]
F:\Feature-test\dcmt\main.cpp(7,17): error C2146: syntax error: missing ';' before identifier 'ofc' [F:\Feature-test\dcmt\build\Stork.vcxproj]
F:\Feature-test\dcmt\main.cpp(7,17): error C2065: 'ofc': undeclared identifier [F:\Feature-test\dcmt\build\Stork.vcxproj]
F:\Feature-test\dcmt\main.cpp(7,23): error C2065: 'format': undeclared identifier [F:\Feature-test\dcmt\build\Stork.vcxproj]
F:\Feature-test\dcmt\main.cpp(8,10): error C2039: 'cout': is not a member of 'std' [F:\Feature-test\dcmt\build\Stork.vcxproj]
F:\Feature-test\dcmt\main.cpp(8,10): error C2065: 'cout': undeclared identifier [F:\Feature-test\dcmt\build\Stork.vcxproj]
F:\Feature-test\dcmt\main.cpp(8,39): error C2065: 'ofc': undeclared identifier [F:\Feature-test\dcmt\build\Stork.vcxproj]
F:\Feature-test\dcmt\main.cpp(8,67): error C2065: 'ofc': undeclared identifier [F:\Feature-test\dcmt\build\Stork.vcxproj]
````

**Comment by xb284524239** [comment]
> I reproduced the problem using the file you provided and got a different error：
> 
> ```
> F:\Feature-test\dcmt\build>cmake --build .
> MSBuild version 17.10.4+10fbfbf2e for .NET Framework
> 
>   Checking Build System
>   Building Custom Rule F:/Feature-test/dcmt/CMakeLists.txt
>   main.cpp
> F:\Feature-test\dcmt\main.cpp(2,5): error C2065: 'DcmFileFormat': undeclared identifier [F:\Feature-test\dcmt\build\Stork.vcxproj]
> F:\Feature-test\dcmt\main.cpp(2,19): error C2146: syntax error: missing ';' before identifier 'format' [F:\Feature-test\dcmt\build\Stork.vcxproj]
> F:\Feature-test\dcmt\main.cpp(2,19): error C2065: 'format': undeclared identifier [F:\Feature-test\dcmt\build\Stork.vcxproj]
> F:\Feature-test\dcmt\main.cpp(3,5): error C2065: 'format': undeclared identifier [F:\Feature-test\dcmt\build\Stork.vcxproj]
> F:\Feature-test\dcmt\main.cpp(7,5): error C2065: 'OFCondition': undeclared identifier [F:\Feature-test\dcmt\build\Stork.vcxproj]
> F:\Feature-test\dcmt\main.cpp(7,17): error C2146: syntax error: missing ';' before identifier 'ofc' [F:\Feature-test\dcmt\build\Stork.vcxproj]
> F:\Feature-test\dcmt\main.cpp(7,17): error C2065: 'ofc': undeclared identifier [F:\Feature-test\dcmt\build\Stork.vcxproj]
> F:\Feature-test\dcmt\main.cpp(7,23): error C2065: 'format': undeclared identifier [F:\Feature-test\dcmt\build\Stork.vcxproj]
> F:\Feature-test\dcmt\main.cpp(8,10): error C2039: 'cout': is not a member of 'std' [F:\Feature-test\dcmt\build\Stork.vcxproj]
> F:\Feature-test\dcmt\main.cpp(8,10): error C2065: 'cout': undeclared identifier [F:\Feature-test\dcmt\build\Stork.vcxproj]
> F:\Feature-test\dcmt\main.cpp(8,39): error C2065: 'ofc': undeclared identifier [F:\Feature-test\dcmt\build\Stork.vcxproj]
> F:\Feature-test\dcmt\main.cpp(8,67): error C2065: 'ofc': undeclared identifier [F:\Feature-test\dcmt\build\Stork.vcxproj]
> ```

@JonLiu1993 
It should include the header files, and a DICOM file for testing.

// main.cpp

```
#include <dcmtk/dcmdata/dcfilefo.h>
#include <dcmtk/ofstd/ofcond.h>
#include <iostream>

int main(int argc, char** argv) {
    DcmFileFormat format;
    format.loadFile(R"(C:\test.dcm)");

    // this code runs failure in triplet x64-windows-static-md;
    // but it runs well in triplet x64-windows
    OFCondition ofc = format.convertToUTF8();
    std::cout << "convertToUTF8: " << ofc.good() << ", text: " << ofc.text();
}
```

**Comment by JonLiu1993** [comment]
I successfully compiled the second time according to the file you provided：
````
F:\Feature-test\build>cmake ..
-- Building for: Visual Studio 17 2022
-- Running vcpkg install
Detecting compiler hash for triplet x64-windows-static-md...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe
The following packages will be built and installed:
    dcmtk[core,zlib]:x64-windows-static-md@3.6.8#6
  * vcpkg-cmake:x64-windows-static-md@2024-04-23
  * vcpkg-cmake-config:x64-windows-static-md@2024-05-23
  * zlib:x64-windows-static-md@1.3.1
Additional packages (*) will be modified to complete this operation.
Restored 4 package(s) from C:\Users\v-zhli17\AppData\Local\vcpkg\archives in 11 s. Use --debug to see more details.
Installing 1/4 vcpkg-cmake:x64-windows-static-md@2024-04-23...
Elapsed time to handle vcpkg-cmake:x64-windows-static-md: 10.9 ms
vcpkg-cmake:x64-windows-static-md package ABI: fe2a1ac2240f65b07dbd4370681338f526038f955668765a51da3223be75ea86
Installing 2/4 zlib:x64-windows-static-md@1.3.1...
Elapsed time to handle zlib:x64-windows-static-md: 22.5 ms
zlib:x64-windows-static-md package ABI: 9bd55a5741cfa2675e79e33ffb9ebab26d9c0e631e34d1b4fe5a5d7a830c0a52
Installing 3/4 vcpkg-cmake-config:x64-windows-static-md@2024-05-23...
Elapsed time to handle vcpkg-cmake-config:x64-windows-static-md: 7.26 ms
vcpkg-cmake-config:x64-windows-static-md package ABI: 90da9233165883042a0431df790928b5f7c497f978d7da6edca593b603a9c9c0
Installing 4/4 dcmtk[core,zlib]:x64-windows-static-md@3.6.8#6...
Elapsed time to handle dcmtk:x64-windows-static-md: 775 ms
dcmtk:x64-windows-static-md package ABI: 7cd9d3190c291c4fcd3fe2157656ccedd329f68035a72f39e3e9a3404c5edaa2
Total install time: 816 ms
The package dcmtk provides CMake targets:

    find_package(DCMTK CONFIG REQUIRED)
    target_link_libraries(main PRIVATE DCMTK::DCMTK)
    # You may also need one or more of the following targets:
    # DCMTK::cmr DCMTK::i2d DCMTK::ijg8 DCMTK::config DCMTK::ofstd
    # DCMTK::oflog DCMTK::dcmdata DCMTK::dcmimgle DCMTK::dcmimage
    # DCMTK::dcmjpeg DCMTK::ijg12 DCMTK::ijg16 DCMTK::dcmjpls
    # DCMTK::dcmtkcharls DCMTK::dcmtls DCMTK::dcmnet DCMTK::dcmsr
    # DCMTK::dcmdsig DCMTK::dcmwlm DCMTK::dcmqrdb DCMTK::dcmpstat
    # DCMTK::dcmrt DCMTK::dcmiod DCMTK::dcmfg DCMTK::dcmseg
    # DCMTK::dcmtract DCMTK::dcmpmap DCMTK::dcmect

Add the following cmake code to your CMakeLists.txt to create definitions for DCMTK
    if ("${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}" STREQUAL "/")
        message(WARNING "No vcpkg install dir found, DCMTK definitions are not set")
    else()
        target_compile_definitions(main
            PUBLIC
                "DCMTK_PREFIX=${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}"
                "DCM_DICT_DEFAULT_PATH=${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/share/dcmtk-3.6.8/dicom.dic:${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/share/dcmtk-3.6.8/private.dic"
                "DEFAULT_CONFIGURATION_DIR=${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/etc/dcmtk-3.6.8/"
                "DEFAULT_SUPPORT_DATA_DIR=${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/share/dcmtk-3.6.8/"
        )
    endif()

-- Running vcpkg install - done
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
-- The C compiler identification is MSVC 19.40.33811.0
-- The CXX compiler identification is MSVC 19.40.33811.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (23.7s)
-- Generating done (0.0s)
-- Build files have been written to: F:/Feature-test/build
````
````
F:\Feature-test\build>cmake --build .
MSBuild version 17.10.4+10fbfbf2e for .NET Framework

  Checking Build System
  Building Custom Rule F:/Feature-test/CMakeLists.txt
  main.cpp
  Stork.vcxproj -> F:\Feature-test\build\Debug\Stork.exe
  Building Custom Rule F:/Feature-test/CMakeLists.txt

````

**Comment by xb284524239** [comment]
> I successfully compiled the second time according to the file you provided：
> 
> ```
> F:\Feature-test\build>cmake ..
> -- Building for: Visual Studio 17 2022
> -- Running vcpkg install
> Detecting compiler hash for triplet x64-windows-static-md...
> Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe
> The following packages will be built and installed:
>     dcmtk[core,zlib]:x64-windows-static-md@3.6.8#6
>   * vcpkg-cmake:x64-windows-static-md@2024-04-23
>   * vcpkg-cmake-config:x64-windows-static-md@2024-05-23
>   * zlib:x64-windows-static-md@1.3.1
> Additional packages (*) will be modified to complete this operation.
> Restored 4 package(s) from C:\Users\v-zhli17\AppData\Local\vcpkg\archives in 11 s. Use --debug to see more details.
> Installing 1/4 vcpkg-cmake:x64-windows-static-md@2024-04-23...
> Elapsed time to handle vcpkg-cmake:x64-windows-static-md: 10.9 ms
> vcpkg-cmake:x64-windows-static-md package ABI: fe2a1ac2240f65b07dbd4370681338f526038f955668765a51da3223be75ea86
> Installing 2/4 zlib:x64-windows-static-md@1.3.1...
> Elapsed time to handle zlib:x64-windows-static-md: 22.5 ms
> zlib:x64-windows-static-md package ABI: 9bd55a5741cfa2675e79e33ffb9ebab26d9c0e631e34d1b4fe5a5d7a830c0a52
> Installing 3/4 vcpkg-cmake-config:x64-windows-static-md@2024-05-23...
> Elapsed time to handle vcpkg-cmake-config:x64-windows-static-md: 7.26 ms
> vcpkg-cmake-config:x64-windows-static-md package ABI: 90da9233165883042a0431df790928b5f7c497f978d7da6edca593b603a9c9c0
> Installing 4/4 dcmtk[core,zlib]:x64-windows-static-md@3.6.8#6...
> Elapsed time to handle dcmtk:x64-windows-static-md: 775 ms
> dcmtk:x64-windows-static-md package ABI: 7cd9d3190c291c4fcd3fe2157656ccedd329f68035a72f39e3e9a3404c5edaa2
> Total install time: 816 ms
> The package dcmtk provides CMake targets:
> 
>     find_package(DCMTK CONFIG REQUIRED)
>     target_link_libraries(main PRIVATE DCMTK::DCMTK)
>     # You may also need one or more of the following targets:
>     # DCMTK::cmr DCMTK::i2d DCMTK::ijg8 DCMTK::config DCMTK::ofstd
>     # DCMTK::oflog DCMTK::dcmdata DCMTK::dcmimgle DCMTK::dcmimage
>     # DCMTK::dcmjpeg DCMTK::ijg12 DCMTK::ijg16 DCMTK::dcmjpls
>     # DCMTK::dcmtkcharls DCMTK::dcmtls DCMTK::dcmnet DCMTK::dcmsr
>     # DCMTK::dcmdsig DCMTK::dcmwlm DCMTK::dcmqrdb DCMTK::dcmpstat
>     # DCMTK::dcmrt DCMTK::dcmiod DCMTK::dcmfg DCMTK::dcmseg
>     # DCMTK::dcmtract DCMTK::dcmpmap DCMTK::dcmect
> 
> Add the following cmake code to your CMakeLists.txt to create definitions for DCMTK
>     if ("${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}" STREQUAL "/")
>         message(WARNING "No vcpkg install dir found, DCMTK definitions are not set")
>     else()
>         target_compile_definitions(main
>             PUBLIC
>                 "DCMTK_PREFIX=${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}"
>                 "DCM_DICT_DEFAULT_PATH=${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/share/dcmtk-3.6.8/dicom.dic:${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/share/dcmtk-3.6.8/private.dic"
>                 "DEFAULT_CONFIGURATION_DIR=${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/etc/dcmtk-3.6.8/"
>                 "DEFAULT_SUPPORT_DATA_DIR=${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/share/dcmtk-3.6.8/"
>         )
>     endif()
> 
> -- Running vcpkg install - done
> -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
> -- The C compiler identification is MSVC 19.40.33811.0
> -- The CXX compiler identification is MSVC 19.40.33811.0
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Configuring done (23.7s)
> -- Generating done (0.0s)
> -- Build files have been written to: F:/Feature-test/build
> ```
> 
> ```
> F:\Feature-test\build>cmake --build .
> MSBuild version 17.10.4+10fbfbf2e for .NET Framework
> 
>   Checking Build System
>   Building Custom Rule F:/Feature-test/CMakeLists.txt
>   main.cpp
>   Stork.vcxproj -> F:\Feature-test\build\Debug\Stork.exe
>   Building Custom Rule F:/Feature-test/CMakeLists.txt
> ```

@JonLiu1993 
Yes, run it. Then you will see the error log: 
( If you don't have DICOM files for testing, I can send some to you via email )

```
W: Failed to open oficonv data file 'esdb\esdb.alias.db', check environment variable DCMICONVPATH
W: Failed to open oficonv data file 'esdb\esdb.alias', check environment variable DCMICONVPATH
W: Failed to open oficonv data file 'esdb\esdb.dir.db', check environment variable DCMICONVPATH
W: Failed to open oficonv data file 'esdb\esdb.dir', check environment variable DCMICONVPATH
convertToUTF8:  false , text:  Cannot open character encoding: Invalid argument
```

**Comment by JonLiu1993** [comment]
````
F:\Feature-test\build\Debug>Stork.exe
convertToUTF8: 1, text: Normal
````

**Comment by dg0yt** [comment]
> check environment variable DCMICONVPATH

Did you set and check it?

**Comment by xb284524239** [comment]
> > check environment variable DCMICONVPATH
> 
> Did you set and check it?

@dg0yt 
It runs well after I set the `environment variable DCMICONVPATH.`

**Comment by JonLiu1993** [comment]
It seems that this issue has been resolved, I will close this issue.

**Comment by xb284524239** [comment]
@JonLiu1993  @dg0yt 

I have discovered some notes in the source code of the DCMTK library. I plan to add a CMake variable named 'DCMTK_ENABLE_BUILTIN_OFICONV_DATA' to the 'dcmtk/portfile.cmake' file and submit a pull request (PR).

```
OFICONV DATA FILES
==================

When oficonv is used to implement character set conversion (which is the
default, starting with DCMTK 3.6.8), then a set of binary data files containing
mapping tables are used during the conversion process.  By default, these are
installed and expected in DCMTK's data path ("/usr/local/share/dcmtk-<VERSION>/
data") in the subdirectories "esdb" and "csmapper".  The data path can be
overridden at runtime by setting the environment variable "DCMICONVPATH" to
point to a different directory.

It is possible to embed the mapping tables into the oficonv library, in which
case no external files are needed at runtime.  This can be enabled by setting
the CMake variable "DCMTK_ENABLE_BUILTIN_OFICONV_DATA" to "ON".  This behavior
is enabled by default when DCMTK is compiled into shared libraries (option
"BUILD_SHARED_LIBS" set to "ON"), and disabled by default otherwise.  Note that
when using static libraries, the built-in mapping tables will increase the size
of each executable by ca. 4 MBytes.

The "DCMICONVPATH" environment variable is respected even when built-in mapping
tables are available.  In this case, the files referred to by "DCMICONVPATH"
override the built-in files, unless "DCMICONVPATH" points to DCMTK's default
data path.
```
