### ISSUE TITLE
[abseil] Build error on x64-windows

### ISSUE THREAD

**Issue by Hdjdjk** [microsoft/vcpkg#39470]
Package: abseil:x64-windows@20240116.2#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.40.33811.0
-    vcpkg-tool version: 2024-06-10-02590c430e4ed9215d27870138c2e579cc338772
    vcpkg-scripts version: c4467cb68 2024-06-21 (2 days ago)

**To Reproduce**

`vcpkg install protobuf:x64-windows-static`

**Failure logs**

```
-- Downloading https://github.com/abseil/abseil-cpp/archive/20240116.2.tar.gz -> abseil-abseil-cpp-20240116.2.tar.gz...

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: no such file or directory
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
      

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/abseil/portfile.cmake:5 (vcpkg_from_github)
  scripts/ports.cmake:191 (include)



```

HELP ME PLS

**Comment by Cheney-W** [comment]
I can't reproduce this issue in my side with the latest vcpkg. I could install `abseil:x64-windows` successfully.
Could you manually download `https://github.com/abseil/abseil-cpp/archive/20240116.2.tar.gz`, rename it to `abseil-abseil-cpp-20240116.2.tar.gz` and then save it into the `vcpkg\downloads` folder?

**Comment by andymacxx** [comment]
I'm having the same issue. using vcpkg built-in to vs2022  and manifest mode.

**Comment by beyond-space21** [comment]
when i try to install opencv, I get the below erroe log,

`error: building abseil:x64-windows failed with: BUILD_FAILED
Elapsed time to handle abseil:x64-windows: 4.5 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+abseil
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[abseil]+Build+error+on+x64-windows&body=Copy+issue+body+from+D%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md`

**Comment by Cheney-W** [comment]
Could you please provide the `vcpkg\installed\vcpkg\issue_body.md` file?

**Comment by beyond-space21** [comment]
hello @Cheney-W , here is the file
[issue_body.md](https://github.com/user-attachments/files/15969768/issue_body.md)

**Comment by Cheney-W** [comment]
Duplicates https://github.com/microsoft/vcpkg/issues/39452
