### ISSUE TITLE
[vtk] Reduce dependencies by adding new features

### ISSUE THREAD

**Issue by bansan85** [microsoft/vcpkg#39491]
### Is your feature request related to a problem? Please describe.

I just need vtkImageData. I don't need the 50 dependencies.

### Proposed solution

All dependencies should depend on feature. To keep backward compatibility, new features should be enabled by default.

If you're okay with that, I can work on it.

**Comment by jimwang118** [comment]
You can make modifications without affecting the basic functions.

**Comment by dg0yt** [comment]
And every new feature must come with proper inter-feature dependencies...

**Comment by bansan85** [comment]
I just started and this PR will need lots of work. I will try not to introduce too many features.

And I will need to update packages that depend on vtk because they all depend on it with "default-features: false".

**Comment by bansan85** [comment]
Before it took me 1h15. Now, it takes 55 minutes. Much better :)
