### ISSUE TITLE
[cuda] update to 12.5

### ISSUE THREAD

**Issue by SoundDev** [microsoft/vcpkg#39494]
### Library name

CUDA Toolkit

### New version number

12.5

### Other information that may be useful (release notes, etc...)

Windows library port for CUDA Toolkit version 12.5
https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=11

**Comment by WangWeiLin-MV** [comment]
This port script is compatible with `CUDA` 12.5
