### ISSUE TITLE
vcpkg install gtest x64 don't work

### ISSUE THREAD

**Issue by shitdarling** [Microsoft/vcpkg#3952]
`Installing package gtest:x64-windows... done`
just the same as [gtest link fatal error lnk1561](https://stackoverflow.com/questions/41078597/error-link-fatal-error-lnk1561-entry-point-must-be-defined-c#)
It occurs in both my own laptop and my working computer in company, vs2017 community.

**Comment by gix** [comment]
GoogleTest is one of the few libraries that require manual linking, especially for the part of GoogleTest that defines `main`. See [the relevant section in the manual](https://github.com/Microsoft/vcpkg/blob/master/docs/users/integration.md#user-wide-for-msbuild-recommended-for-open-source-msbuild-projects).

**Comment by rleigh-codelibre** [comment]
So long as you use

```
find_package(GTest)
```

in your project's `CMakeList.txt`, you should be able to use the `GTest::GTest` imported target providing you use the vcpkg toolchain file to add the appropriate search paths.  I'm doing just this, and it's working perfectly.

**Comment by vicroms** [comment]
This is not an issue. 

As stated above by @gix, `gtest` must be manually linked in your VS project.
As a rule-of-thumb, any library that defines its own `::main` is not auto-linked by vcpkg.
