### ISSUE TITLE
[qt5-webengine] Build error C2976: 'absl::lts_20240116::strings_internal::Splitter': too few template arguments

### ISSUE THREAD

**Issue by cgilles** [microsoft/vcpkg#39528]
* Context:

Windows 10 up-to-date, Visual Studio 2022 up-to-date. 

* Console trace:

Installing 7/7 qt5-webengine:x64-windows@5.15.14...
Building qt5-webengine:x64-windows@5.15.14...
-- qt5-webengine requires a lot of free disk space (>100GB), ram (>8 GB) and time (>2h per configuration) to be successfully build.
-- As such qt5-webengine is currently experimental.
-- If qt5-webengine fails post build validation please try manually reducing VCPKG_MAX_CONCURRENCY and open up an issue if it still cannot build.
-- If it fails due to post validation the successfully installed files can be found in C:/vcpkg/packages/qt5-webengine_x64-windows
-- and just need to be copied into E:/dk/x64-windows
-- Downloading https://sourceforge.net/projects/gnuwin32/files/gperf/3.0.1/gperf-3.0.1-bin.zip/download -> gperf-3.0.1-bin.zip...
-- Downloading https://www.python.org/ftp/python/2.7.18/python-2.7.18.amd64.msi -> python-2.7.18.amd64.msi...
-- Found external ninja('1.11.0').
CMake Warning at scripts/ports.cmake:167 (message):
  Unexpected READ_ACCESS on variable WIN32 in script mode.

  This variable name insufficiently expresses whether it refers to the target
  system or to the host system.  Use a prefixed variable instead.

  - Variables providing information about the host:

    CMAKE_HOST_<SYSTEM>
    VCPKG_HOST_IS_<SYSTEM>

  - Variables providing information about the target:

    VCPKG_TARGET_IS_<SYSTEM>
    VCPKG_DETECTED_<VARIABLE> (using vcpkg_cmake_get_vars)

Call Stack (most recent call first):
  ports/qt5-webengine/portfile.cmake:2147483647 (z_vcpkg_warn_ambiguous_system_variables)
  ports/qt5-webengine/portfile.cmake:32 (if)
  scripts/ports.cmake:191 (include)

-- Downloading https://download.qt.io/archive/qt/5.15/5.15.14/submodules/qtwebengine-everywhere-opensource-src-5.15.14.tar.xz;https://mirrors.ocf.berkeley.edu/qt/archive/qt/5.15/5.15.14/submodules/qtwebengine-everywhere-opensource-src-5.15.14.tar.xz -> qtwebengine-everywhere-opensource-src-5.15.14.tar.xz...
-- Extracting source E:/d/qtwebengine-everywhere-opensource-src-5.15.14.tar.xz
-- Applying patch common.pri.patch
-- Applying patch gl.patch
-- Applying patch build_1.patch
-- Applying patch build_2.patch
-- Applying patch 0001-Support-ICU-74-in-LazyTextBreakIterator.patch
-- Applying patch workaround-protobuf-issue.patch
-- Applying patch 0001-Fix-jumbo-build-error-due-to-ResolveColor-redefiniti.patch
-- Using source at E:/b/qt5-webengine/src/5.15.14-55225c1f0f.clean
-- Getting CMake variables for x64-windows
-- Using cached msys2-mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.5.3-3-x86_64.pkg.tar.zst.
-- Using msys root at E:/d/tools/msys2/1e74ca60daa10104
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Configuring x64-windows-dbg
-- Configuring x64-windows-dbg done
-- Package build-x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: E:/d/tools/jom/jom-1_1_4/jom.exe -j 9
    Working Directory: E:/b/qt5-webengine/x64-windows-dbg
    See logs for more information:
      E:\b\qt5-webengine\package-build-x64-windows-dbg-out.log
      E:\b\qt5-webengine\package-build-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_qmake.cmake:3 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_build_qmake.cmake:76 (z_run_jom_build)
  E:/dk/x64-windows/share/qt5/qt_build_submodule.cmake:11 (vcpkg_build_qmake)
  E:/dk/x64-windows/share/qt5/qt_submodule_installation.cmake:9 (qt_build_submodule)
  ports/qt5-webengine/portfile.cmake:69 (qt_submodule_installation)
  scripts/ports.cmake:191 (include)

error: building qt5-webengine:x64-windows failed with: BUILD_FAILED
Elapsed time to handle qt5-webengine:x64-windows: 1.6 h
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qt5-webengine
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[qt5-webengine]+Build+error+on+x64-windows&body=Copy+issue+body+from+E%3A%2Fdk%2Fvcpkg%2Fissue_body.md

FAILED COMMAND: $VCPKG_DIR/vcpkg ${VCPKG_COMMON_OPTIONS[@]} install qt5-webengine

* Errors from log: 

E:\b\qt5-webengine\src\5.15.14-55225c1f0f.clean\src\3rdparty\chromium\third_party/abseil-cpp/absl/strings/str_split.h(491): error C2976: 'absl::lts_20240116::strings_internal::Splitter': too few template arguments
E:\dk\x64-windows\include\absl/strings/internal/str_split_internal.h(278): note: see declaration of 'absl::lts_20240116::strings_internal::Splitter'
E:\b\qt5-webengine\src\5.15.14-55225c1f0f.clean\src\3rdparty\chromium\third_party/abseil-cpp/absl/strings/str_split.h(501): error C2976: 'absl::lts_20240116::strings_internal::Splitter': too few template arguments
E:\dk\x64-windows\include\absl/strings/internal/str_split_internal.h(278): note: see declaration of 'absl::lts_20240116::strings_internal::Splitter'
E:\b\qt5-webengine\src\5.15.14-55225c1f0f.clean\src\3rdparty\chromium\net/quiche/common/platform/impl/quiche_text_utils_impl.h(148): error C2440: 'return': cannot convert from 'absl::lts_20240116::strings_internal::Splitter' to 'std::vector<quiche::QuicheStringPiece,std::allocator<quiche::QuicheStringPiece>>'
E:\b\qt5-webengine\src\5.15.14-55225c1f0f.clean\src\3rdparty\chromium\net/quiche/common/platform/impl/quiche_text_utils_impl.h(148): note: 'std::vector<quiche::QuicheStringPiece,std::allocator<quiche::QuicheStringPiece>>::vector': no overloaded function could convert all the argument types
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\vector(650): note: could be 'std::vector<quiche::QuicheStringPiece,std::allocator<quiche::QuicheStringPiece>>::vector(std::initializer_list<absl::lts_20240116::string_view>,const _Alloc &)'
        with
        [
            _Alloc=std::allocator<quiche::QuicheStringPiece>
        ]
E:\b\qt5-webengine\src\5.15.14-55225c1f0f.clean\src\3rdparty\chromium\net/quiche/common/platform/impl/quiche_text_utils_impl.h(148): note: 'std::vector<quiche::QuicheStringPiece,std::allocator<quiche::QuicheStringPiece>>::vector(std::initializer_list<absl::lts_20240116::string_view>,const _Alloc &)': cannot convert argument 1 from 'absl::lts_20240116::strings_internal::Splitter' to 'std::initializer_list<absl::lts_20240116::string_view>'
        with
        [
            _Alloc=std::allocator<quiche::QuicheStringPiece>
        ]
E:\b\qt5-webengine\src\5.15.14-55225c1f0f.clean\src\3rdparty\chromium\net/quiche/common/platform/impl/quiche_text_utils_impl.h(148): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\vector(623): note: or       'std::vector<quiche::QuicheStringPiece,std::allocator<quiche::QuicheStringPiece>>::vector(_Iter,_Iter,const _Alloc &)'
        with
        [
            _Alloc=std::allocator<quiche::QuicheStringPiece>
        ]

* Logs files are attached to this report.

[qt5-webengine-log.zip](https://github.com/user-attachments/files/15984118/qt5-webengine-log.zip)

Best regards

Gilles Caulier

**Comment by WangWeiLin-MV** [comment]
Please try with latest vcpkg.

Duplicate with #34452

**Comment by tsondergaard** [comment]
Hi @WangWeiLin-MV,

This issue should be reopened. My PR #37044 incorrectly listed #34452 as fixed. I overlooked at the time that there were two issues in #34452 - the protobuf issue and an abseil-issue. I have now created #39530 to also fix the abseil-cpp issue.

**Comment by cgilles** [comment]
@tsondergaard I just updated VCPKG and try to rebuild qt5webengine : same error....
