### ISSUE TITLE
[protobuf-c] build failure

### ISSUE THREAD

**Issue by shubhamble** [microsoft/vcpkg#39526]
### Operating system

Windows

### Compiler

protoc

### Steps to reproduce the behavior

```Shell
.\vcpkg.exe install --clean-after-build --recurse protobuf-c:x64-windows protobuf-c[tools]:x64-windows
```

### Failure logs

vcpkg package management program version 2024-06-10-02590c430e4ed9215d27870138c2e579cc338772

See LICENSE.txt for license information.
Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
Installing packages...
Computing installation plan...
The following packages will be built and installed:
  * abseil:x64-windows@20240116.2#1
  * protobuf:x64-windows@4.25.1
    protobuf-c[core,tools]:x64-windows@1.4.1#1
  * utf8-range:x64-windows@4.25.1
  * vcpkg-cmake:x64-windows@2024-04-23
  * vcpkg-cmake-config:x64-windows@2024-05-23
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
A suitable version of powershell-core was not found (required v7.2.16) Downloading portable powershell-core 7.2.16...
Downloading powershell-core...
https://github.com/PowerShell/PowerShell/releases/download/v7.2.16/PowerShell-7.2.16-win-x64.zip->C:\Users\shubh_5ea5vvc\adder-remote-desktop\thirdparty\vcpkg\downloads\PowerShell-7.2.16-win-x64.zip
Downloading https://github.com/PowerShell/PowerShell/releases/download/v7.2.16/PowerShell-7.2.16-win-x64.zip
Extracting powershell-core...
Compiler found: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe
A suitable version of 7zip was not found (required v24.6.0) Downloading portable 7zip 24.6.0...
Downloading 7zip...
https://github.com/ip7z/7zip/releases/download/24.06/7z2406-extra.7z->C:\Users\shubh_5ea5vvc\adder-remote-desktop\thirdparty\vcpkg\downloads\7z2406-extra.7z
Downloading https://github.com/ip7z/7zip/releases/download/24.06/7z2406-extra.7z
Extracting 7zip...
Restored 5 package(s) from C:\Users\shubh_5ea5vvc\AppData\Local\vcpkg\archives in 8.9 s. Use --debug to see more details.
Installing 1/6 vcpkg-cmake:x64-windows@2024-04-23...
Elapsed time to handle vcpkg-cmake:x64-windows: 23.1 ms
vcpkg-cmake:x64-windows package ABI: b66e83a2497b248f998fbad51bfa1a19001af5eab195537b4f11942d8c5f39de
Installing 2/6 vcpkg-cmake-config:x64-windows@2024-05-23...
Elapsed time to handle vcpkg-cmake-config:x64-windows: 23.6 ms
vcpkg-cmake-config:x64-windows package ABI: d3e2a72751a858a83408fb846ebabdd70f90411c1632cc43eacec4478698384e
Installing 3/6 abseil:x64-windows@20240116.2#1...
Elapsed time to handle abseil:x64-windows: 516 ms
abseil:x64-windows package ABI: 73bd81b6f12198cefa1690d5606223773775303946b20fd2b68632787d168242
Installing 4/6 utf8-range:x64-windows@4.25.1...
Elapsed time to handle utf8-range:x64-windows: 18.8 ms
utf8-range:x64-windows package ABI: 8436da57b8ad1d1021a2b206f4e6c39723ec108bdfa9214cf8e1f5d957132679
Installing 5/6 protobuf:x64-windows@4.25.1...
Elapsed time to handle protobuf:x64-windows: 243 ms
protobuf:x64-windows package ABI: 179990d5211ab90856a623ed7d052a1f4244affca15682cf0430780684c69f9a
Installing 6/6 protobuf-c[core,tools]:x64-windows@1.4.1#1...
Building protobuf-c[core,tools]:x64-windows@1.4.1#1...
-- Downloading https://github.com/protobuf-c/protobuf-c/archive/v1.4.1.tar.gz -> protobuf-c-protobuf-c-v1.4.1.tar.gz...
-- Extracting source C:/Users/shubh_5ea5vvc/adder-remote-desktop/thirdparty/vcpkg/downloads/protobuf-c-protobuf-c-v1.4.1.tar.gz
-- Applying patch fix-crt-linkage.patch
-- Using source at C:/Users/shubh_5ea5vvc/adder-remote-desktop/thirdparty/vcpkg/buildtrees/protobuf-c/src/v1.4.1-d0ea40a369.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j5
    Working Directory: C:/Users/shubh_5ea5vvc/adder-remote-desktop/thirdparty/vcpkg/buildtrees/protobuf-c/x64-windows-dbg
    See logs for more information:
      C:\Users\shubh_5ea5vvc\adder-remote-desktop\thirdparty\vcpkg\buildtrees\protobuf-c\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/protobuf-c/portfile.cmake:23 (vcpkg_cmake_install)
  scripts/ports.cmake:191 (include)

error: building protobuf-c:x64-windows failed with: BUILD_FAILED
Elapsed time to handle protobuf-c:x64-windows: 8.7 s

```[tasklist]
### Tasks
- [ ] I made a script and tried to run the vcpkg command:
```

**Comment by shubhamble** [comment]
I made a script and tried to run the vcpkg command:

Write-Host -ForegroundColor White " ** protobuf installation... " -NoNewline

# Specify the desired folder to clone vcpkg
$cloneFolder = "$pwd/thirdparty/"

# Create the folder if it doesn't exist
New-Item -ItemType Directory -Force -Path $cloneFolder | Out-Null

# Change to the desired folder
Set-Location -Path $cloneFolder

# Download and install vcpkg
Write-Host "Downloading vcpkg..."
git clone https://github.com/Microsoft/vcpkg.git 

# Change to vcpkg directory
Write-Host "Changing to vcpkg directory..."
Set-Location -Path vcpkg

# Bootstrap vcpkg
Write-Host "Bootstrapping vcpkg..."
.\bootstrap-vcpkg.bat

# Install desired packages (replace with your packages)
Write-Host "Installing packages..."
.\vcpkg.exe install --clean-after-build --recurse protobuf-c:x64-windows protobuf-c[tools]:x64-windows

# Set protoc.exe path in PATH environment variable
$tempPaths = (($env:Path -split ';') | Select-Object -Unique) -join ';'
[Environment]::SetEnvironmentVariable("Path", $tempPaths + ";$($pwd)\thirdparty\vcpkg\installed\x64-windows\tools\protobuf" +
    ";$($pwd)\thirdparty\vcpkg\installed\x64-windows\tools\protobuf-c", "Machine")
$env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path", "User")

Write-Host "Protobuf installation completed."

**Comment by jimwang118** [comment]
Sorry, I can`t reproduce this issue locally.
Please provide the error log. 
C:\Users\shubh_5ea5vvc\adder-remote-desktop\thirdparty\vcpkg\buildtrees\protobuf-c\install-x64-windows-dbg-out.log
![image](https://github.com/microsoft/vcpkg/assets/122244446/87312e6e-a19d-4f2d-9118-6427004118bf)

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
