### ISSUE TITLE
error: building abseil:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by CristianMoran1** [microsoft/vcpkg#39538]
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
Error code: 1
Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:287 (vcpkg_execute_required_process)
  ports/abseil/portfile.cmake:28 (vcpkg_cmake_configure)
  scripts/ports.cmake:191 (include)

**Comment by StarGate-One** [comment]
See #30604 How to report a package build failure.

**Comment by jimwang118** [comment]
Please provide more useful information, such as error logs, steps to reproduce, etc.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
