### ISSUE TITLE
pdal package missing include (nanoflann.hpp)

### ISSUE THREAD

**Issue by dethtoll1** [Microsoft/vcpkg#3957]
After installing the pdal package, including the <pdal/KDIndex.hpp> header produces a compilation error, as it includes <nanoflann/nanoflann.hpp>

nanoflann.hpp does exist in the buildtrees, but it is not copied to the vcpkg/installed/<platform>/include directory.

Environment details:
- Latest vcpkg (0.0.113)
- Package: pdal:x64-windows v1.7.1-2
- Using CMake 3.11 (not Visual Studio integration)

**Comment by JackBoosY** [comment]
Hi @dethtoll1, thanks for reporting this issue!
This issue has been fixed. Plz update vcpkg and rebuild pdal.
Thanks.
