### ISSUE TITLE
[abseil] dynamic linking with MSVC gives linker error

### ISSUE THREAD

**Issue by giles45** [microsoft/vcpkg#39584]
**Describe the bug**
Having installed abseil with dynamic linkage with vcpkg, build a C++ program in Visual Studio that uses certain abseil functions, e.g. absl::ascii_toupper, absl::ascii_islower, etc - you get a link time error

1>Source.obj : error LNK2001: unresolved external symbol "char const * const absl::lts_20240116::ascii_internal::kToUpper" (?kToUpper@ascii_internal@lts_20240116@absl@@3QBDB)

If you use a custom triplet with abseil installed with static linkage, linking with abseil works fine.

This issues looks the same as this previously reported & fixed issue: https://github.com/microsoft/vcpkg/issues/12021 and adding the preprocessor definition ABSL_CONSUME_DLL does resolve the linker error BUT the answer & solution to this ticket says that this should not be needed.

**Environment**
- OS: Windows
- Compiler: MSVC 19.39.33523 (from Visual Studio 2022)

**To Reproduce**
1. ./vcpkg install abseil:x86-windows
2. In Visual Studio, create new solution (with vcpkg integrated and enabled in the solution). E.g.
```
#include <absl/strings/ascii.h>
int main(int argc, char* argv[])
{
    return absl::ascii_toupper(argv[0][0]);
}
```

When building get linker error:

```
1>Source.obj : error LNK2001: unresolved external symbol "char const * const absl::lts_20240116::ascii_internal::kToUpper" (?kToUpper@ascii_internal@lts_20240116@absl@@3QBDB)
1>..\..\..\bin\Win32\Debug\test.exe : fatal error LNK1120: 1 unresolved externals
```

**Expected behavior**

Linking succeeds without issue 

**Failure logs**
-(please attached failure logs)

**Additional context**
Trying to diagnose why the solution from https://github.com/microsoft/vcpkg/issues/12021 doesn't look to be working, a line of code in ports/abseil/portfile.cmake looks to be wrong.

The line

```
    foreach(header IN LISTS ${headers})
```

should be 

```
    foreach(header IN LISTS headers)
```

Having changed that line, the following vcpkg_replace_string calls do their job and I no longer get a linker error

**Comment by dg0yt** [comment]
Please test https://github.com/microsoft/vcpkg/pull/39664. It handles only two headers, explicitly.
