### ISSUE TITLE
Building package pmdk:x64-windows failed with Visual Studio 2015

### ISSUE THREAD

**Issue by Greg091** [Microsoft/vcpkg#3960]
I can not install package pmdk:x64-windows on the Windows 10 (10.0.16299). I have Visual Studio 2015, the newest versions of Git and cmake.
I got the log, which I attached in the file below.
[log.txt](https://github.com/Microsoft/vcpkg/files/2235859/log.txt)

**Comment by Voskrese** [comment]
`Actual hash: [ a4bffb393f07e5e2ffbd2a7835b906148401abf0f3cff28262cf8607691fc2d567d153358a3fb3a15197db699519c7b3a4699b67a51c15fecd707bc30795c5c7 ]`

**Comment by Voskrese** [comment]
proxy GIT

**http**

`git config --global http.proxy http://<username>:<password>@<proxy-port>`

where username and password are your proxy username and password; proxy-port might be a value such as proxy.mycompany.com:80.

**httpS**

` git config --global http.proxy http://<username>:<password>@<proxy-port>`

where username and password are your proxy username and password; proxy-port might be a value such as proxy.mycompany.com:80

**Comment by Greg091** [comment]
Now, it is working correctly.
Verified on ff5d6eb3c84d6a41fefc2ab10b77790db933c8ed
