### ISSUE TITLE
any.hpp is missing in boost directory

### ISSUE THREAD

**Issue by code667** [Microsoft/vcpkg#3961]
If we download boost1.67 from boost.org, any.hpp is in boost\any.hpp

> dir  any.hpp
...\boost_1_67_0\boost\any.hpp

But if we install boost using vcpkg, there is no any.hpp in x64-windows-static\include\boost\

it break all the codes with the line blow:

`#include <boost/any.hpp>`

**Comment by JackBoosY** [comment]
Hi @code667 , thanks for reporting this issue!
Boost-any has been updated to v1.69.0 and fixed this issue. Please update and rebuild boost-any.
Thanks.
