### ISSUE TITLE
[mp-units] Add feature to use ms-gsl or gsl-lite

### ISSUE THREAD

**Issue by wongjk** [microsoft/vcpkg#39619]
### Is your feature request related to a problem? Please describe.

A project of mine uses `ms-gsl`, which will conflict with the `gsl-lite` dependency in `mp-units`.

### Proposed solution

Add a feature choose between `ms-gsl` and `gsl-lite`.

**Comment by Osyotr** [comment]
> Add a feature choose between ms-gsl and gsl-lite.

There can't be such a feature. https://learn.microsoft.com/en-us/vcpkg/contributing/maintainer-guide#do-not-use-features-to-implement-alternatives

**Comment by wongjk** [comment]
I see. I will have to use an overlay port then.

Thank you,

**Comment by dg0yt** [comment]
Do I understand correctly that we already have two alternative implmentations of the GSL which cannot be used at the same time? Maybe we don't need a feature but must force all ports to use the same variant. AFAIU the ban of alternatives is intented to prevent the situation which is reported here.

**Comment by wongjk** [comment]
> Do I understand correctly that we already have two alternative implmentations of the GSL which cannot be used at the same time?

Yes. Both `ms-gsl` and `gsl-lite` define things under the `gsl` namespace, which causes type conflicts and ODR violations.

**Comment by dg0yt** [comment]
It seems like only one of them should be used in vcpkg.
