### ISSUE TITLE
mariadb-client 3.0.5 errors

### ISSUE THREAD

**Issue by OlafvdSpek** [microsoft/vcpkg#3962]
Trying to update mariadb-client to 3.0.5 but it doesn't build. I see errors like:
```
    35>LINK : fatal error LNK1104: cannot open file '..\mytap\Debug\cctap.lib' [C:\VC\vcpkg\buildtrees\libmariadb\x86-windows-dbg\unittest\libmariadb\view.vcxproj]
    35>Done Building Project "C:\VC\vcpkg\buildtrees\libmariadb\x86-windows-dbg\unittest\libmariadb\view.vcxproj" (default targets) -- FAILED.
```

Could be an upstream error.

[install-x86-windows-dbg-out.txt](https://github.com/Microsoft/vcpkg/files/2237990/install-x86-windows-dbg-out.txt)

**Comment by JackBoosY** [comment]
Related: #6562.

**Comment by JackBoosY** [comment]
PR has been merged, so I close it.
