### ISSUE TITLE
[whatsapp-api-client-cpp] Build error on x64-windows

### ISSUE THREAD

**Issue by EscHelpNew** [microsoft/vcpkg#39637]
Hello, please help, I can’t assemble my package

Package: whatsapp-api-client-cpp:x64-windows@0.0.1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.40.33811.0
-    vcpkg-tool version: 2024-06-10-02590c430e4ed9215d27870138c2e579cc338772
    vcpkg-scripts version: 101cc9a69 2024-06-30 (12 hours ago)

**To Reproduce**

`vcpkg install whatsapp-api-client-cpp`

**Failure logs**

```
-- Note: whatsapp-api-client-cpp only supports static library linkage. Building static library.
-- Using cached green-api-whatsapp-api-client-cpp-0.0.1.tar.gz.
-- Extracting source F:/projects/GREEN-API/C++/whatsapp-api-client-cpp/vcpkg/downloads/green-api-whatsapp-api-client-cpp-0.0.1.tar.gz
-- Using source at F:/projects/GREEN-API/C++/whatsapp-api-client-cpp/vcpkg/buildtrees/whatsapp-api-client-cpp/src/0.0.1-692377cfed.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j17
    Working Directory: F:/projects/GREEN-API/C++/whatsapp-api-client-cpp/vcpkg/buildtrees/whatsapp-api-client-cpp/x64-windows-dbg
    See logs for more information:
      F:\projects\GREEN-API\C++\whatsapp-api-client-cpp\vcpkg\buildtrees\whatsapp-api-client-cpp\install-x64-windows-dbg-out.log
      F:\projects\GREEN-API\C++\whatsapp-api-client-cpp\vcpkg\buildtrees\whatsapp-api-client-cpp\install-x64-windows-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  F:/projects/GREEN-API/C++/whatsapp-api-client-cpp/custom-overlay/whatsapp-api-client-cpp/portfile.cmake:16 (vcpkg_cmake_install)
  scripts/ports.cmake:192 (include)



```

<details><summary>F:\projects\GREEN-API\C++\whatsapp-api-client-cpp\vcpkg\buildtrees\whatsapp-api-client-cpp\install-x64-windows-dbg-err.log</summary>

```
ninja: error: unknown target 'install'
```
</details>

<details><summary>F:\projects\GREEN-API\C++\whatsapp-api-client-cpp\vcpkg\buildtrees\whatsapp-api-client-cpp\install-x64-windows-dbg-out.log</summary>

```
Change Dir: 'F:/projects/GREEN-API/C++/whatsapp-api-client-cpp/vcpkg/buildtrees/whatsapp-api-client-cpp/x64-windows-dbg'

Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v -v -j17 install
```
</details>

**Comment by jimwang118** [comment]
The `whatsapp-api-client-cpp` port does not exist in vcpkg. Did you add this port yourself?

**Comment by EscHelpNew** [comment]
@jimwang118 
Hello, yes, there is no port in vcpkg at the moment, I’m just trying to add it there, following the instructions [https://learn.microsoft.com/ru-ru/vcpkg/get_started/get-started-packaging?pivots=shell -cmd](https://learn.microsoft.com/ru-ru/vcpkg/get_started/get-started-packaging?pivots=shell-cmd)

I created vcpkg.json and portfile, but at step 5 after entering the command with my parameters 
`vcpkg install vcpkg-sample-library --overlay-ports=C:\path\to\custom-overlay` I get an error

**Comment by EscHelpNew** [comment]
I think I understand, I need to make a pull request to the main repository with my vcpkg and portfile files.
And the instructions I follow are just for local checking.

**Comment by jimwang118** [comment]
Did you compile successfully after adding whatsapp-api-client-cpp to your local repository?

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
