### ISSUE TITLE
[gettext-libintl] Build error on x64-linux (NixOS) due to hardcoded path

### ISSUE THREAD

**Issue by easrng** [microsoft/vcpkg#39641]
Package: gettext-libintl:x64-linux@0.22.5#1

**Host Environment**

- Host: x64-linux (NixOS 24.11pre641786.d603719ec6e2 (Vicuna) x86_64)
- Compiler: GNU 13.3.0
-    vcpkg-tool version: 2024-06-10-02590c430e4ed9215d27870138c2e579cc338772
    vcpkg-scripts version: f7423ee18 2024-06-14 (2 weeks ago)

**To Reproduce**

`vcpkg install --no-print-usage`

**Failure logs**

```
CMake Error at buildtrees/versioning_/versions/gettext-libintl/ac89519d5ec11430978a4e45619befb7a1c4a062/portfile.cmake:4 (message):
  When targeting Linux, `libintl.h` is expected to come from the C Runtime
  Library (glibc).  Please use "sudo apt-get install libc-dev" or the
  equivalent to install development files.
Call Stack (most recent call first):
  scripts/ports.cmake:191 (include)



```

The issue here is that [the portfile only checks if `/usr/include/libintl.h exists`](https://github.com/microsoft/vcpkg/blob/f61a294e765b257926ae9e9d85f96468a0af74e7/ports/gettext-libintl/portfile.cmake#L3), when on NixOS it'll be something like `/nix/store/4vgk1rlzdqjnpjicb5qcxjcd4spi7wyw-glibc-2.39-52-dev/include/libintl.h`

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "builtin-baseline": "f7423ee180c4b7f40d43402c2feb3859161ef625",
  "dependencies": [
    {
      "name": "fontconfig",
      "platform": "linux | freebsd | openbsd"
    },
    "icu",
    "libjpeg-turbo",
    {
      "name": "libpng",
      "features": [
        "apng"
      ]
    },
    {
      "name": "skia",
      "platform": "osx",
      "features": [
        "metal"
      ]
    },
    {
      "name": "skia",
      "platform": "linux | freebsd | openbsd"
    },
    "sqlite3",
    "woff2"
  ],
  "overrides": [
    {
      "name": "fontconfig",
      "version": "2.14.2#1"
    },
    {
      "name": "icu",
      "version": "74.2#2"
    },
    {
      "name": "libjpeg-turbo",
      "version": "3.0.2"
    },
    {
      "name": "libpng",
      "version": "1.6.43#1"
    },
    {
      "name": "skia",
      "version": "124#0"
    },
    {
      "name": "sqlite3",
      "version": "3.45.3"
    },
    {
      "name": "woff2",
      "version": "1.0.2#4"
    }
  ]
}

```
</details>

**Comment by MonicaLiu0311** [comment]
Sorry I didn't repro issue.

```
monica@monica003:/mnt/vcpkg$ cat /proc/version
Linux version 6.5.0-1016-azure (buildd@bos03-amd64-021) (x86_64-linux-gnu-gcc-11 (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #16~22.04.1-Ubuntu SMP Fri Feb 16 15:42:02 UTC 2024
```

```
monica@monica003:/mnt/vcpkg$ ./vcpkg install gettext-libintl
Computing installation plan...
The following packages will be built and installed:
    gettext-libintl:x64-linux@0.22.5#1
Detecting compiler hash for triplet x64-linux...
Compiler found: /usr/bin/c++
Restored 0 package(s) from /home/monica/.cache/vcpkg/archives in 7.3 us. Use --debug to see more details.
Installing 1/1 gettext-libintl:x64-linux@0.22.5#1...
Building gettext-libintl:x64-linux@0.22.5#1...
-- Skipping post-build validation due to VCPKG_POLICY_EMPTY_PACKAGE
Failed to store binary cache /home/monica/.cache/vcpkg/archives/78/788ba230ad941885894aeb2c5e59da66d508e4845420f1b8cf0c5e9f35d8ea6a.zip
No such file or directory
Stored binaries in 0 destinations in 3.31 ms.
Elapsed time to handle gettext-libintl:x64-linux: 47.2 ms
gettext-libintl:x64-linux package ABI: 788ba230ad941885894aeb2c5e59da66d508e4845420f1b8cf0c5e9f35d8ea6a
Total install time: 47.2 ms
gettext-libintl is compatible with built-in CMake targets:

    find_package(Intl REQUIRED)
    target_link_libraries(main PRIVATE Intl::Intl) # since CMake 3.20
```

**Comment by MonicaLiu0311** [comment]
> The issue here is that [the portfile only checks if `/usr/include/libintl.h exists`](https://github.com/microsoft/vcpkg/blob/f61a294e765b257926ae9e9d85f96468a0af74e7/ports/gettext-libintl/portfile.cmake#L3), when on NixOS it'll be something like `/nix/store/4vgk1rlzdqjnpjicb5qcxjcd4spi7wyw-glibc-2.39-52-dev/include/libintl.h`


Could you please modify `portfile.cmake` as follows and install it, then use it in `CMakeLists.txt` according to `usage` to test whether it can be found.
```
if(VCPKG_TARGET_IS_LINUX)
    set(VCPKG_POLICY_EMPTY_PACKAGE enabled)
        find_program(LIBINTL_H_FOUND NAMES libintl.h PATHS /usr/include /nix/store NO_DEFAULT_PATH)
        if(NOT LIBINTL_H_FOUND)
            message(FATAL_ERROR
                "Could not find libintl.h in either /usr/include or /nix/store. "
                "Please use \"sudo apt-get install libc-dev\" or the equivalent to install development files."
            )
        endif()
    endif()
endif()
```

**Comment by easrng** [comment]
I'll try when I get home, but that looks very inefficient. cmake finds the header just fine, is there a way to just ask it to run it's normal resolution logic instead of hacks like this?

**Comment by quentinmit** [comment]
`/nix/store` should never be searched for files like that; it might contain many different copies of `libintl.h` from different versions of glibc. You should just rely on the normal cmake logic for finding a header file (e.g. a Nix shell will automatically set `CMAKE_INCLUDE_PATH` to point to the packages in the shell).

**Comment by dg0yt** [comment]
It is really one unusual package manager meeting another one.

> ~~~cmake
> find_program(LIBINTL_H_FOUND NAMES libintl.h PATHS /usr/include /nix/store NO_DEFAULT_PATH)

This makes no sense. :facepalm: 

The answer is probably building a test project, at least if `/usr/include/libintl.h` doesn't exist.

**Comment by dg0yt** [comment]
> at least if `/usr/include/libintl.h` doesn't exist.

But this is the wrong indicator also for cross builds...

**Comment by dg0yt** [comment]
Please test #39662. It uses a CMake project for detecting `libintl.h`.

**Comment by quentinmit** [comment]
> Please test #39662. It uses a CMake project for detecting `libintl.h`.

How can I test this? Do you have a sample invocation that will trigger the new detection code?

**Comment by dg0yt** [comment]
> cmake finds the header just fine, is there a way to just ask it to run it's normal resolution logic instead of hacks like this?

There is *no hack*, and *nothing inefficient*. The portfile runs in CMake script mode which *does not* offer "normal resolution". Building a project means regular invocation of CMake project mode with proper target toolchain setup.

**Comment by dg0yt** [comment]
You might simply checkout the branch which is the input to that PR.
Shortcut: https://github.com/dg0yt/vcpkg/tree/libintl
