### ISSUE TITLE
 [vcpkg-tool] build failed on arm64v8/ubuntu:16.04

### ISSUE THREAD

**Issue by alexlee728** [microsoft/vcpkg#39643]
[210/216] Building CXX object CMakeFiles/vcpkg-test.dir/src/vcpkg-test/util.cpp.o
[211/216] Building CXX object CMakeFiles/vcpkg-test.dir/src/vcpkg-test/versionplan.cpp.o
[212/216] Building CXX object CMakeFiles/vcpkg-test.dir/src/vcpkg-test/versions.cpp.o
[213/216] Building CXX object CMakeFiles/vcpkg-test.dir/src/vcpkg-test/xunitwriter.cpp.o
FAILED: /usr/bin/c++ -DVCPKG_BASE_VERSION=2999-12-31 -DVCPKG_VERSION=unknownhash -D_FILE_OFFSET_BITS=64 -I/builds/xxx/external/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-06-10/include -I/builds/xxx/external/vcpkg/buildtrees/_vcpkg/build/_deps/fmt-src/include -I/builds/xxx/external/vcpkg/buildtrees/_vcpkg/build/_cmrc/include -O3 -DNDEBUG -std=c++1z -pthread -Winvalid-pch -include /builds/xxx/external/vcpkg/buildtrees/_vcpkg/build/CMakeFiles/vcpkglib.dir/cmake_pch.hxx -MD -MT CMakeFiles/vcpkglib.dir/src/vcpkg/sourceparagraph.cpp.o -MF CMakeFiles/vcpkglib.dir/src/vcpkg/sourceparagraph.cpp.o.d -o CMakeFiles/vcpkglib.dir/src/vcpkg/sourceparagraph.cpp.o -c /builds/xxx/external/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-06-10/src/vcpkg/sourceparagraph.cpp
/builds/xxx/external/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-06-10/src/vcpkg/sourceparagraph.cpp: In function 'vcpkg::ExpectedL<std::unique_ptr<vcpkg::SourceParagraph> > vcpkg::parse_source_paragraph(vcpkg::StringView, vcpkg::Paragraph&&)':
/builds/xxx/external/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-06-10/src/vcpkg/sourceparagraph.cpp:399:16: error: could not convert 'spgh' from 'std::unique_ptr<vcpkg::SourceParagraph>' to 'vcpkg::ExpectedL<std::unique_ptr<vcpkg::SourceParagraph> > {aka vcpkg::ExpectedT<std::unique_ptr<vcpkg::SourceParagraph>, vcpkg::LocalizedString>}'
         return spgh;
                ^~~~
/builds/xxx/external/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-06-10/src/vcpkg/sourceparagraph.cpp: In function 'vcpkg::ExpectedL<std::unique_ptr<vcpkg::FeatureParagraph> > vcpkg::parse_feature_paragraph(vcpkg::StringView, vcpkg::Paragraph&&)':
/builds/xxx/external/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-06-10/src/vcpkg/sourceparagraph.cpp:434:16: error: could not convert 'fpgh' from 'std::unique_ptr<vcpkg::FeatureParagraph>' to 'vcpkg::ExpectedL<std::unique_ptr<vcpkg::FeatureParagraph> > {aka vcpkg::ExpectedT<std::unique_ptr<vcpkg::FeatureParagraph>, vcpkg::LocalizedString>}'
         return fpgh;
                ^~~~
/builds/xxx/external/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-06-10/src/vcpkg/sourceparagraph.cpp: In static member function 'static vcpkg::ExpectedL<std::unique_ptr<vcpkg::SourceControlFile> > vcpkg::SourceControlFile::parse_control_file(vcpkg::StringView, std::vector<std::map<std::__cxx11::basic_string<char>, std::pair<std::__cxx11::basic_string<char>, vcpkg::TextRowCol>, std::less<void> > >&&)':
/builds/xxx/external/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-06-10/src/vcpkg/sourceparagraph.cpp:465:16: error: could not convert 'control_file' from 'std::unique_ptr<vcpkg::SourceControlFile>' to 'vcpkg::ExpectedL<std::unique_ptr<vcpkg::SourceControlFile> > {aka vcpkg::ExpectedT<std::unique_ptr<vcpkg::SourceControlFile>, vcpkg::LocalizedString>}'
         return control_file;
                ^~~~~~~~~~~~
FAILED: /usr/bin/c++ -DVCPKG_BASE_VERSION=2999-12-31 -DVCPKG_VERSION=unknownhash -D_FILE_OFFSET_BITS=64 -I/builds/xxx/external/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-06-10/include -I/builds/xxx/external/vcpkg/buildtrees/_vcpkg/build/_deps/fmt-src/include -I/builds/xxx/external/vcpkg/buildtrees/_vcpkg/build/_cmrc/include -O3 -DNDEBUG -std=c++1z -pthread -Winvalid-pch -include /builds/xxx/external/vcpkg/buildtrees/_vcpkg/build/CMakeFiles/vcpkglib.dir/cmake_pch.hxx -MD -MT CMakeFiles/vcpkglib.dir/src/vcpkg/registries.cpp.o -MF CMakeFiles/vcpkglib.dir/src/vcpkg/registries.cpp.o.d -o CMakeFiles/vcpkglib.dir/src/vcpkg/registries.cpp.o -c /builds/xxx/external/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-06-10/src/vcpkg/registries.cpp
/builds/xxx/external/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-06-10/src/vcpkg/registries.cpp: In member function 'virtual vcpkg::ExpectedL<std::unique_ptr<vcpkg::RegistryEntry> > {anonymous}::BuiltinGitRegistry::get_port_entry(vcpkg::StringView) const':
/builds/xxx/external/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-06-10/src/vcpkg/registries.cpp:794:16: error: could not convert 'res' from 'std::unique_ptr<{anonymous}::BuiltinGitRegistryEntry, std::default_delete<{anonymous}::BuiltinGitRegistryEntry> >' to 'vcpkg::ExpectedL<std::unique_ptr<vcpkg::RegistryEntry> > {aka vcpkg::ExpectedT<std::unique_ptr<vcpkg::RegistryEntry>, vcpkg::LocalizedString>}'
         return res;
                ^~~
/builds/xxx/external/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-06-10/src/vcpkg/registries.cpp: In member function 'virtual vcpkg::ExpectedL<std::unique_ptr<vcpkg::RegistryEntry> > {anonymous}::FilesystemRegistry::get_port_entry(vcpkg::StringView) const':
/builds/xxx/external/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-06-10/src/vcpkg/registries.cpp:884:16: error: could not convert 'res' from 'std::unique_ptr<{anonymous}::FilesystemRegistryEntry, std::default_delete<{anonymous}::FilesystemRegistryEntry> >' to 'vcpkg::ExpectedL<std::unique_ptr<vcpkg::RegistryEntry> > {aka vcpkg::ExpectedT<std::unique_ptr<vcpkg::RegistryEntry>, vcpkg::LocalizedString>}'
         return res;
                ^~~
FAILED: /usr/bin/c++ -DVCPKG_BASE_VERSION=2999-12-31 -DVCPKG_VERSION=unknownhash -D_FILE_OFFSET_BITS=64 -I/builds/xxx/external/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-06-10/include -I/builds/xxx/external/vcpkg/buildtrees/_vcpkg/build/_deps/fmt-src/include -I/builds/xxx/external/vcpkg/buildtrees/_vcpkg/build/_cmrc/include -O3 -DNDEBUG -std=c++1z -pthread -Winvalid-pch -include /builds/xxx/external/vcpkg/buildtrees/_vcpkg/build/CMakeFiles/vcpkglib.dir/cmake_pch.hxx -MD -MT CMakeFiles/vcpkglib.dir/src/vcpkg/dependencies.cpp.o -MF CMakeFiles/vcpkglib.dir/src/vcpkg/dependencies.cpp.o.d -o CMakeFiles/vcpkglib.dir/src/vcpkg/dependencies.cpp.o -c /builds/xxx/external/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-06-10/src/vcpkg/dependencies.cpp
In file included from /usr/include/c++/7/memory:64:0,
                 from /aubo-base-vcpkg-arm64-linux/buildtrees/_vcpkg/build/_deps/fmt-src/include/fmt/format.h:41,
                 from /builds/xxx/external/vcpkg/buildtrees/_vcpkg/build/_deps/fmt-src/include/fmt/compile.h:11,
                 from /builds/xxx/external/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-06-10/include/vcpkg/base/fmt.h:15,
                 from /builds/xxx/external/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-06-10/include/pch.h:5,
                 from /builds/xxx/external/vcpkg/buildtrees/_vcpkg/build/CMakeFiles/vcpkglib.dir/cmake_pch.hxx:5,
                 from <command-line>:0:
/usr/include/c++/7/bits/stl_construct.h: In instantiation of 'void std::_Construct(_T1*, _Args&& ...) [with _T1 = vcpkg::InstallPlanAction; _Args = {const vcpkg::InstallPlanAction&}]':
/usr/include/c++/7/bits/stl_uninitialized.h:83:18:   required from 'static _ForwardIterator std::__uninitialized_copy<_TrivialValueTypes>::__uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = __gnu_cxx::__normal_iterator<const vcpkg::InstallPlanAction*, std::vector<vcpkg::InstallPlanAction> >; _ForwardIterator = vcpkg::InstallPlanAction*; bool _TrivialValueTypes = false]'
/usr/include/c++/7/bits/stl_uninitialized.h:134:15:   required from '_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = __gnu_cxx::__normal_iterator<const vcpkg::InstallPlanAction*, std::vector<vcpkg::InstallPlanAction> >; _ForwardIterator = vcpkg::InstallPlanAction*]'
/usr/include/c++/7/bits/stl_uninitialized.h:289:37:   required from '_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = __gnu_cxx::__normal_iterator<const vcpkg::InstallPlanAction*, std::vector<vcpkg::InstallPlanAction> >; _ForwardIterator = vcpkg::InstallPlanAction*; _Tp = vcpkg::InstallPlanAction]'
/usr/include/c++/7/bits/stl_vector.h:331:31:   required from 'std::vector<_Tp, _Alloc>::vector(const std::vector<_Tp, _Alloc>&) [with _Tp = vcpkg::InstallPlanAction; _Alloc = std::allocator<vcpkg::InstallPlanAction>]'
/builds/xxx/external/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-06-10/include/vcpkg/dependencies.h:93:12:   required from 'vcpkg::ExpectedHolder<T>::ExpectedHolder(Fwd&&) [with Fwd = vcpkg::ActionPlan&; typename std::enable_if<(! is_same_v<vcpkg::ExpectedHolder<T>, typename std::remove_cv<typename std::remove_reference<_SrcTuple>::type>::type>), int>::type <anonymous> = 0; T = vcpkg::ActionPlan]'
/builds/xxx/external/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-06-10/include/vcpkg/base/expected.h:78:66:   required from 'vcpkg::ExpectedT<T, Error>::ExpectedT(ConvToT&&) [with ConvToT = vcpkg::ActionPlan&; typename std::enable_if<(is_convertible_v<ConvToT, T> && (! is_same_v<typename std::remove_reference<_SrcTuple>::type, Error>)), int>::type <anonymous> = 0; T = vcpkg::ActionPlan; Error = vcpkg::LocalizedString]'
/builds/xxx/external/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-06-10/src/vcpkg/dependencies.cpp:2051:20:   required from here
/usr/include/c++/7/bits/stl_construct.h:75:7: error: use of deleted function 'vcpkg::InstallPlanAction::InstallPlanAction(const vcpkg::InstallPlanAction&)'
     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /builds/xxx/external/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-06-10/src/vcpkg/dependencies.cpp:8:0:
/builds/xxx/external/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-06-10/include/vcpkg/dependencies.h:37:9: note: declared here
         InstallPlanAction(const InstallPlanAction&) = delete;
         ^~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.

**Comment by alexlee728** [comment]
using gcc 7.5

**Comment by dg0yt** [comment]
Install a more modern compiler, and set `CXX` before starting the build.

**Comment by LilyWangLL** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
