### ISSUE TITLE
[vcpkg-tool] build failure on arm64-linux（2024.06.15）

### ISSUE THREAD

**Issue by chenpei2** [microsoft/vcpkg#39663]
### Operating system

Linux 2829673ac438 5.15.136-tegra aarch64

### Steps to reproduce the behavior

```Shell
./bootstrap-vcpkg.sh
```

### Failure logs

Unable to determine a binary release of vcpkg; attempting to build from source.
Downloading vcpkg tool sources
Building vcpkg-tool...
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/workspace/vcpkg/buildtrees/_vcpkg/build/CMakeFiles/CMakeOutput.log".

**Comment by LilyWangLL** [comment]
Please install compiler `gcc` and `g++`.
```
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
```

**Comment by chenpei2** [comment]
> Please install compiler `gcc` and `g++`.
> 
> ```
> CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
> CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
> ```

gcc/g++ already installed. gcc -v:

**Comment by chenpei2** [comment]
> Please install compiler `gcc` and `g++`.
> 
> ```
> CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
> CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
> ```

gcc/g++ already installed. gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)

**Comment by chenpei2** [comment]
problem solved after: 
`apt install ninja-build`
