### ISSUE TITLE
[New Port Request] OSQP

### ISSUE THREAD

**Issue by kjohnsen** [microsoft/vcpkg#39674]
### Library name

OSQP: Operator Splitting Quadratic Program

### Library description

A quadratic program solver that uses the ADMM algorithm

### Source repository URL

https://github.com/osqp/osqp

### Project homepage (if different from the source repository)

https://osqp.org/docs/index.html

**Comment by kjohnsen** [comment]
Please keep open

**Comment by zsq5610** [comment]
support add OSQP to ports
