### ISSUE TITLE
[vcpkg] Telemetry locks .vcpkg-root

### ISSUE THREAD

**Issue by bansan85** [microsoft/vcpkg#39689]
**Describe the bug**
Telemetry is locking `.vcpkg-root` file in background. It should not.

I can't run `vcpkg` if telemetry is running in background.

**Environment**
- OS: Linux

**To Reproduce**
1. `./vcpkg install --help`
2. `./vcpkg install --help` (fast after the previous one)
3. See error : `/home/gitlab-runner/.cache/vcpkg/vcpkg-git/.vcpkg-root: error: Failed to take the filesystem lock`

Randomly reproducible.

**Expected behavior**
I'm fine with telemetry. But it should not reduce user experience. I had to disable it.

**Failure logs**
```
gitlab-runner@XXXXXX:~/builds/XXXXXX$ ~/.cache/vcpkg/vcpkg-git/vcpkg install --help
/home/gitlab-runner/.cache/vcpkg/vcpkg-git/.vcpkg-root: error: Failed to take the filesystem lock
    Device or resource busy
```

```
gitlab-runner@XXXXXX:~/builds/XXXXXX$ ps -A x |grep vcpkg
2920208 pts/3    S      0:00 sh -c curl https://dc.services.visualstudio.com/v2/track --max-time 60 -H "Content-Type: application/json" -X POST --tlsv1.2 --data @/tmp/vcpkg/vcpkgcb3d626e-8f38-42b1-bc1c-698e28e8fd38.txt >/dev/null 2>&1 ; rm /tmp/vcpkg/vcpkgcb3d626e-8f38-42b1-bc1c-698e28e8fd38.txt
2920209 pts/3    S      0:00 curl https://dc.services.visualstudio.com/v2/track --max-time 60 -H Content-Type: application/json -X POST --tlsv1.2 --data @/tmp/vcpkg/vcpkgcb3d626e-8f38-42b1-bc1c-698e28e8fd38.txt
```

```
integration@XXXXXX:~$ sudo lsof |grep vcpkg-root
sh        2920251                     gitlab-runner    3u      REG              253,0         0    4213983 /home/gitlab-runner/.cache/vcpkg/vcpkg-git/.vcpkg-root
curl      2920252                     gitlab-runner    3u      REG              253,0         0    4213983 /home/gitlab-runner/.cache/vcpkg/vcpkg-git/.vcpkg-root
```

**Comment by jimwang118** [comment]
I followed your steps to reproduce the problem and ran the command multiple times locally, but the problem did not recur.
![image](https://github.com/microsoft/vcpkg/assets/122244446/59d405ac-fb20-4ea7-9668-d2ab3810cb2e)

**Comment by bansan85** [comment]
Oh, sorry, the `$` is a mistake in the command line. But I got stuck because the previous line didn't have the `$` and a telemetry was in process.

I edited the main description.

**Comment by jimwang118** [comment]
Execute the `./vcpkg install --help` command multiple times and the results are normal.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
