### ISSUE TITLE
[aom] Build error

### ISSUE THREAD

**Issue by Chapra78** [microsoft/vcpkg#39691]
We are getting error after executing the command to install aom="vcpkg install aom --triplet x86-windows-static --clean-after-build"

error: building aom:x86-windows-static failed with: BUILD_FAILED
Elapsed time to handle aom:x86-windows-static: 2.2 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+aom
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[aom]+Build+error&body=Copy+issue+body+from+C%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by WangWeiLin-MV** [comment]
Using the latest version of vcpkg for local installation does not reproduce the issue.

Please try with latest vcpkg.

If the issue persists, please see #30604 for how to report a build failure.

**Comment by Chapra78** [comment]
I'm using latest version of vcpkg but still the error is same.

PS C:\vcpkg> .\vcpkg install libyuv:x86-windows-static libvpx:x86-windows-static aom:x86-windows-static
Computing installation plan...
The following packages are already installed:
    libvpx:x86-windows-static@1.13.1#3
    libyuv:x86-windows-static@1857#1
The following packages will be built and installed:
    aom:x86-windows-static@3.8.1#1
Detecting compiler hash for triplet x86-windows-static...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x86/cl.exe
Restored 0 package(s) from C:\Users\Admin\AppData\Local\vcpkg\archives in 577 us. Use --debug to see more details.
libvpx:x86-windows-static is already installed
libyuv:x86-windows-static is already installed
Installing 1/1 aom:x86-windows-static@3.8.1#1...
Building aom:x86-windows-static@3.8.1#1...
C:\vcpkg\triplets\community\x86-windows-static.cmake: info: loaded community triplet from here. Community triplets are not built in the curated registry and are thus less likely to succeed.
-- Using cached C:/vcpkg/downloads/aom-bb6430482199eaefbeaaa396600935082bc43f66.tar.gz
-- Cleaning sources at C:/vcpkg/buildtrees/aom/src/082bc43f66-89b017b851.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/aom-bb6430482199eaefbeaaa396600935082bc43f66.tar.gz
-- Applying patch aom-rename-static.diff
-- Applying patch aom-uninitialized-pointer.diff
-- Applying patch aom-install.diff
-- Using source at C:/vcpkg/buildtrees/aom/src/082bc43f66-89b017b851.clean
-- Found external ninja('1.11.0').
-- Configuring x86-windows-static
-- Building x86-windows-static-dbg
-- Building x86-windows-static-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.29.2-windows/cmake-3.29.2-windows-i386/bin/cmake.exe --build . --config Release --target install -- -v -j13
    Working Directory: C:/vcpkg/buildtrees/aom/x86-windows-static-rel
    See logs for more information:
      C:\vcpkg\buildtrees\aom\install-x86-windows-static-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/aom/portfile.cmake:44 (vcpkg_cmake_install)
  scripts/ports.cmake:192 (include)


error: building aom:x86-windows-static failed with: BUILD_FAILED
Elapsed time to handle aom:x86-windows-static: 18 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+aom
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[aom]+Build+error+on+x86-windows-static&body=Copy+issue+body+from+C%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by dg0yt** [comment]
> See logs for more information:
> C:\vcpkg\buildtrees\aom\install-x86-windows-static-rel-out.log

**Comment by WangWeiLin-MV** [comment]
Please see #30604 and attach the error log file.
