### ISSUE TITLE
[Wt] build fail

### ISSUE THREAD

**Issue by sdcb** [Microsoft/vcpkg#397]
C:\_\3rd\vcpkg>vcpkg version
Vcpkg package management program version 0.0.61-ed2994a5e930b27fd5dbe121b35fe0abba428376

See LICENSE.txt for license information.

output message: 
-- CURRENT_INSTALLED_DIR=C:/_/3rd/vcpkg/installed/x64-windows
-- DOWNLOADS=C:/_/3rd/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/_/3rd/vcpkg/packages/wt_x64-windows
-- CURRENT_BUILDTREES_DIR=C:/_/3rd/vcpkg/buildtrees/wt
-- CURRENT_PORT_DIR=C:/_/3rd/vcpkg/ports/wt/.
-- Using cached C:/_/3rd/vcpkg/downloads/wt-3.3.6.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Configuring x64-windows-dbg
-- Configuring x64-windows-dbg done
-- Package x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Release;--target;install;--;/m
    Working Directory: C:/_/3rd/vcpkg/buildtrees/wt/x64-windows-rel
    See logs for more information:
      C:\_\3rd\vcpkg\buildtrees\wt\package-x64-windows-rel-out.log
      C:\_\3rd\vcpkg\buildtrees\wt\package-x64-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:3 (vcpkg_execute_required_process)
  ports/wt/portfile.cmake:24 (vcpkg_install_cmake)
  scripts/ports.cmake:74 (include)

error output (in rel-out.log): 
LINK : fatal error LNK1104: cannot open file“boost_date_time.lib” [C:\_\3rd\vcpkg\buildtrees\wt\x64-windows-rel\src\Wt\Dbo\wtdbo.vcxproj]

**Comment by codeandroid** [comment]
If one removes the following line in ports/boost/portfile.cmake, it works again.

`file(APPEND ${CURRENT_PACKAGES_DIR}/include/boost/config/user.hpp "\n#define BOOST_AUTO_LINK_NOMANGLE\n")`

This line was added as part of 56c3febc9de168df0707269e48d31701f60e7673 in order to enable boost's system install (= library names without mangled suffixes).

This option was later disabled in ff4d33b156e06b5457837361b28803fb8570d350 but the line setting `BOOST_AUTO_LINK_NOMANGLE` was kept.

I'm not sure if removing this line will work across all projects but at least Wt builds again and I'll be testing a few more ports.

**Comment by codeandroid** [comment]
This also fixes the build for cpprestsdk (and probably others).
I'll prepare a PR.

**Comment by DragonOsman** [comment]
I hope it's okay to ask this here, but: has this issue been resolved?  Will it be fine to remove that "NOMANGLE" line in our builds if we get Wt using vcpkg?

**Comment by ras0219-msft** [comment]
@DragonOsman Thanks for posting your issue! I've moved it over to #1288 for further diagnosis.

Re: the NOMANGLE -- I _believe_ that's correct. In our CI, the current port for Wt is building just fine against the current port of Boost and I don't believe it has the NOMANGLE macro set. However, we do still patch out the reliance on boost autolinking[1].

[1] https://github.com/Microsoft/vcpkg/blob/687440f9760f3b9492de9a3105cdd6b99f9a3634/ports/wt/add-disable-boost-autolink-option.patch

**Comment by DragonOsman** [comment]
Thanks.  

It seems like part of the problem for me was figuring out where to run the ".\vcpkg integrate install" command.  I built vcpkg from source using VS and then went to where the x64 .exe file is for it, and then I ran that command.  It worked.  I'll try it out now.

**Comment by ras0219-msft** [comment]
Ah, of course that's what you meant by build from source 😄!

The `bootstrap-vcpkg.bat` script performs the same source build but also places the output exe into the root. It's totally fine to use the x64 exe directly from the output folder though! I personally add `D:\src\vcpkg\toolsrc\x64\Release` to my default user path.

Could you elaborate on precisely what you mean by "where to run the ... command" in #1288? We should not be requiring any specific working directory.

**Comment by DragonOsman** [comment]
OK, update:
Here's my recent attempt output:

C:\vcpkg\toolsrc\src>cd C:\vcpkg\toolsrc\x64\Release

> C:\vcpkg\toolsrc\x64\Release>.\vcpkg integrate install
> Applied user-wide integration for this vcpkg root.
> 
> All MSBuild C++ projects can now #include any installed libraries.
> Linking will be handled automatically.
> Installing new libraries will make them instantly available.
> 
> CMake projects should use -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
> 
> C:\vcpkg\toolsrc\x64\Release>vcpkg install boost
> The following packages will be built and installed:
>     boost:x86-windows
>   * bzip2:x86-windows
>   * zlib:x86-windows
> Additional packages (*) will be installed to complete this operation.
> Building package zlib:x86-windows...
> Could not run script to detect VS 2017 instances

So it still can't run the Shell script to detect VS 2017 instances.  Why is  his happening?
