### ISSUE TITLE
Improve nuget export for static package

### ISSUE THREAD

**Issue by NN---** [microsoft/vcpkg#3970]
Currently vcpkg has support for static libraries but it is error-prone.

See: #3042 

1. You have to install both static and non-static triplet in order to export the package as nuget.
2. If you export nuget package with specifying only static, the package doesn't use correct path for headers and libs.
3. After exporting package with static and non-static, the package is compiling but not working correctly !
This is the most annoying.

In order to make it work you have to **manually** update vcxproj.
https://blogs.msdn.microsoft.com/vcblog/2016/11/01/vcpkg-updates-static-linking-is-now-available/

I would expect this to be working automatically.
There is ClCompile.RuntimeLibrary property which can be used for this:

https://social.msdn.microsoft.com/Forums/vstudio/en-US/109c2303-b4a5-4aa1-8f61-01663d358fa5/using-metadata-in-conditions

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen this issue.

**Comment by NN---** [comment]
I didn't check, but if nobody looked on it, it might not be solved
