### ISSUE TITLE
cpr ssl broken for new cloudflare certs(discord etc)

### ISSUE THREAD

**Issue by Chrys4lisfag** [microsoft/vcpkg#39712]
**Describe the bug**
Cloudflare now issue new kind of ssl certs with no tls pin support.
While doing https request to any cloudflared website with new certs, you will get internal error 4

More details in cpr issue: https://github.com/libcpr/cpr/issues/1069
This issue only appears on vcpkg version (confirmed by me as well using this example: https://github.com/libcpr/example-cmake-fetch-content, NOTE: upgrade it to latest commit)
The issue author tested it for discord.gg, I have the same issue for discord and many more cloudflare websites.

**Environment**
- OS: Windows 11
- Compiler: MSVC 22

**To Reproduce**
```
const cpr::Url url = cpr::Url{ "https://discord.com" };
const auto response = cpr::Get( url);
```

**Expected behavior**
successful ssl verify and complete the request

**Failure logs**
Connected to ******************************** port 443
schannel: disabled automatic use of client certificate
schannel: connection hostname () validated against certificate name ()
Subject: CN=********************************
Issuer: C=US, O=Let's Encrypt, CN=E6
Version: 2
Serial Number: 03:cf:f5:40:86:7e:2e:f9:b6:d2:e6:24:17:ff:eb:b9:58:c9:
Closing connection
schannel: shutting down SSL/TLS connection with t******************************** port 443

**Additional context**

**Comment by jimwang118** [comment]
Which vcpkg port did you use during this process that caused this issue?

**Comment by Chrys4lisfag** [comment]
cpr:x64-windows-static                            1.10.5#2

**Comment by Chrys4lisfag** [comment]
https://github.com/curl/curl/issues/13845
maybe it is related with this issue

cpr uses curl-8_7_1 while vcpkg bugged v8.8.0 as I understand?

**Comment by jimwang118** [comment]
I call this example: https://github.com/libcpr/example-cmake-fetch-content, and then call the following usage in cmakelists.txt, and the result is displayed normally.
 ```
 find_package(cpr CONFIG REQUIRED)
  target_link_libraries(main PRIVATE cpr::cpr)
```
![image](https://github.com/user-attachments/assets/08d52691-78ac-436c-8fbc-3539b83f6f00)

**Comment by Chrys4lisfag** [comment]
> I call this example: https://github.com/libcpr/example-cmake-fetch-content, and then call the following usage in cmakelists.txt, and the result is displayed normally.
> 
> ```
> find_package(cpr CONFIG REQUIRED)
>  target_link_libraries(main PRIVATE cpr::cpr)
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/122244446/348099333-08d52691-78ac-436c-8fbc-3539b83f6f00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MDU5MzYsIm5iZiI6MTcyMDgwNTYzNiwicGF0aCI6Ii8xMjIyNDQ0NDYvMzQ4MDk5MzMzLTA4ZDUyNjkxLTc4YWMtNDM2Yy04ZmJjLTM1MzliODNmNmYwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQxNzMzNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYWY5YmVlMjI5MTJkZjlmYTRhMzczZjlkN2Y1NjBmMGJmMGFhZjllNjRmODlkNWFkMjg0N2RmMDg1YzI5YmIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ez2DUONsdzaJt9T_C2J2Tvo4D15sHUSeRkk7mCTCsgc)
![image](https://github.com/user-attachments/assets/8551bd78-60da-4597-9960-8b323d45724b)
![image](https://github.com/user-attachments/assets/5e213e42-4dec-42bc-9dec-5b8600122ae8)


I've pulled and upgraded vcpkg rn and testing for discord.gg and github as from example.
Vcpkg cpr::x64-windows-static does not work for me as you see in the screenshots above.
while it works from the cpr repository(clang-llvm cmake)

Not working:
vcpkg: latest(pulled today),
cpr:x64-windows-static                            1.10.5#2 
cpr[ssl]:x64-windows-static
curl:x64-windows-static                           8.8.0#3

OS: Windows 10  (tested my binaries on 10+ machines in 5 different regions RU\EU\USA)
compiler: Visual Studio 2022(17.10.4), c++ 20, build tools v143

example of code not working: https://github.com/Chrys4lisfag/vcpkg-cpr-issue

**Comment by Chrys4lisfag** [comment]
Probably related
https://github.com/libcpr/cpr/issues/1068

**Comment by raytangRT** [comment]
My workaround is to install both `curl` and `cpr` as dependencies and fixing `curl` version to `8.6.0`.

(btw, I am on macOS, so not sure this will help if you are on Windows or Linux)

```json

{  
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg.schema.json",
  "name": "app",
  "version-string": "1.0.0",
  "dependencies": [
    "cpr",
    "curl"
  ],
  "overrides": [
    {
      "name": "curl",
      "version": "8.6.0"
    }
  ]
}

```

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.

**Comment by itztiva** [comment]
I'm having the same issue on windows, Anyone find a solution?
