### ISSUE TITLE
Vcpkg

### ISSUE THREAD

**Issue by Sarah44537** [microsoft/vcpkg#39711]
**Describe the bug**

**Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
1. ./vcpkg install xxxx
2. See error
Repro code when

**Expected behavior**

**Failure logs**
-(please attached failure logs)

**Additional context**

**Comment by sfhacker** [comment]
Embarrassing!

**Comment by FrankXie05** [comment]
Please see #30604 for how to report an issue.
