### ISSUE TITLE
OpenGL BUILD_FAILED

### ISSUE THREAD

**Issue by CaswellBerry** [Microsoft/vcpkg#3971]
Hi guys,

I am using Windows 10 Enterprise 2016 LTSB Version 1607. Build 14393.2368.

I'm new to vcpkg and I am trying to install some packages. Everything works fine (e.g. boost) until I try to install opengl via `vcpkg.exe install opengl:x64-windows`. This is the error I get:

![grafik](https://user-images.githubusercontent.com/37413545/43390985-c32db596-93ef-11e8-99d0-8c0747c926d6.png)

The folder `buildtrees/opengl` is completely empty (no log files etc.).

Any suggestions how to solve the problem are greatly appreciated!
Thank you.

**Comment by Voskrese** [comment]
Windows SDK VER ?

**Comment by CaswellBerry** [comment]
When I look into `Windows Kits/10/Include` I see two folders: 
- 10.0.10150.0
- 10.0.10240.0

Or am I looking in the wrong folder?

**Comment by Voskrese** [comment]
`https://github.com/Microsoft/vcpkg/blob/master/ports/opengl/portfile.cmake`

` set(LIBGLFILEPATH "${PROGRAM_FILES_32_BIT}\\Windows Kits\\10\\Lib\\${WINDOWS_SDK}\\um\\${TRIPLET_SYSTEM_ARCH}\\OpenGL32.Lib")`

**Comment by CaswellBerry** [comment]
> When I look into Windows Kits/10/Include I see two folders:
> - 10.0.10150.0
> - 10.0.10240.0

Same for `Windows Kits/10/Lib`. But there is only a folder named `urct` and not `um` as indicated by your line of code.

**Comment by Voskrese** [comment]
reinstall MSVC or install
https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk

**Comment by CaswellBerry** [comment]
Thank you very much. I just realised, my Win10 SDK installation might not be complete.

**Comment by CaswellBerry** [comment]
VCPKG installs the package seamlessly now. Thanks again!
In the end I just checked the wrong checkbox during Visual Studio Setup.
