### ISSUE TITLE
[boost-headers] Build error on x64-windows

### ISSUE THREAD

**Issue by pata00** [microsoft/vcpkg#39728]
Package: boost-headers:x64-windows@1.85.0#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.40.33811.0
-    vcpkg-tool version: 2024-06-10-02590c430e4ed9215d27870138c2e579cc338772
    vcpkg-scripts version: 576379156 2024-07-05 (21 hours ago)

**To Reproduce**

`vcpkg install boost`

**Failure logs**

```
-- Downloading https://github.com/boostorg/headers/archive/boost-1.85.0.tar.gz -> boostorg-headers-boost-1.85.0.tar.gz...
-- Extracting source F:/gitlab/vcpkg/downloads/boostorg-headers-boost-1.85.0.tar.gz
-- Using source at F:/gitlab/vcpkg/buildtrees/boost-headers/src/ost-1.85.0-f4cb877742.clean
CMake Error at installed/x64-windows/share/vcpkg-boost/boost-install.cmake:29 (file):
  file RENAME failed to rename

    F:/gitlab/vcpkg/buildtrees/boost-headers/src/ost-1.85.0-f4cb877742.clean/

  to

    F:/gitlab/vcpkg/buildtrees/boost-headers/src/ost-1.85.0-f4cb877742.clean.tmp/

  because: �ܾ����ʡ�



Call Stack (most recent call first):
  ports/boost-headers/portfile.cmake:12 (boost_configure_and_install)
  scripts/ports.cmake:192 (include)



```

**Comment by WangWeiLin-MV** [comment]
Using the latest version of vcpkg for local installation does not reproduce the issue.

Please try with latest vcpkg.

If the issue persists, please see #30604 for how to report a build failure.
