### ISSUE TITLE
Building package openssl-windows:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by perplexedyawdie** [Microsoft/vcpkg#3972]
I am using Windows 10 Home 1803. My machine is using the en-jam locale. When attempting to run 
`vcpkg install curl:x64-windows`, it gets to downloading strawberryperl then states that:
 `Failed. Status: 6;"Couldn't resolve host name" ` 
More specifically: 
```
Downloading http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portable.zip... Failed. Status: 6;"Couldn't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:151 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/"
```
Is there anything I can do to get around this?

**Comment by Voskrese** [comment]
proxy ?
https://github.com/Microsoft/vcpkg/issues/3960#issuecomment-408480349

**Comment by DryaginIt** [comment]
I used a VPN. It helped me

**Comment by DryaginIt** [comment]
I used a VPN. It helped me
