### ISSUE TITLE
Transient failure for strawberryperl.com

### ISSUE THREAD

**Issue by atulkumarpccs** [Microsoft/vcpkg#3973]
PS C:\Users\Atul\Documents\Term 2_Udacity\vcpkg> .\vcpkg install openssl zlib libuv
The following packages will be built and installed:
    libuv[core]:x86-windows
    openssl[core]:x86-windows
  * openssl-windows[core]:x86-windows
    zlib[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/4: openssl-windows:x86-windows
Building package openssl-windows[core]:x86-windows...
A suitable version of cmake was not found (required v3.11.4). Downloading portable cmake v3.11.4...
Downloading cmake...
Downloading cmake... done.
Extracting cmake...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
Downloading 7zip... done.
Extracting 7zip...
A suitable version of nuget was not found (required v4.6.2). Downloading portable nuget v4.6.2...
Downloading nuget...
Downloading nuget... done.
Extracting 7zip... done.
Extracting cmake... done.
-- Downloading http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portable.zip...
-- Downloading http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portable.zip... Failed. Status: 6;"Couldn't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:151 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:217 (vcpkg_download_distfile)
  ports/openssl-windows/portfile.cmake:9 (vcpkg_find_acquire_program)
  scripts/ports.cmake:71 (include)

Error: Building package openssl-windows:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-windows:x86-windows
  Vcpkg version: 0.0.113-nohash

Additionally, attach any relevant sections from the log files above.
PS C:\Users\Atul\Documents\Term 2_Udacity\vcpkg> .\vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
PS C:\Users\Atul\Documents\Term 2_Udacity\vcpkg> git pull
Already up to date.
PS C:\Users\Atul\Documents\Term 2_Udacity\vcpkg>

**Comment by Voskrese** [comment]
proxy ?

```
netsh winhttp show proxy
netsh winhttp reset proxy
```

**Comment by coryan** [comment]
I do not think this is a problem with proxy settings.  First `http://strawberryperl.com/` seems to be down:

http://www.isitdownrightnow.com/strawberryperl.com.html

Second, I am not using a proxy:

```console
# netsh winhttp show proxy

Current WinHTTP proxy settings:

    Direct access (no proxy server).
```

**Comment by Stayer** [comment]
Site is down, can't connect to it

**Comment by traversaro** [comment]
Tangentially related (in that the case the problem was not the site downtime): https://github.com/Microsoft/vcpkg/issues/932 .

**Comment by ras0219-msft** [comment]
The website appears to be back up for now; we will look into a longer-term solution for the problem in the future.
