### ISSUE TITLE
[libsystemd] Build error on x64-linux

### ISSUE THREAD

**Issue by frouss** [microsoft/vcpkg#39740]
Getting errors when installing libsystemd on Fedora 40.
[config-x64-linux-dbg-meson-log.txt.log](https://github.com/user-attachments/files/16118527/config-x64-linux-dbg-meson-log.txt.log)
[config-x64-linux-dbg-out.log](https://github.com/user-attachments/files/16118528/config-x64-linux-dbg-out.log)

**Comment by dg0yt** [comment]
Duplicates https://github.com/microsoft/vcpkg/issues/39365.

**Comment by FrankXie05** [comment]
```

../src/v255-948a7f2e81.clean/src/basic/meson.build:238:8: ERROR: Problem encountered: Unknown filesystems defined in kernel headers:

Filesystem found in kernel header but not in filesystems-gperf.gperf: PID_FS_MAGIC
```
