### ISSUE TITLE
vcpkg install error

### ISSUE THREAD

**Issue by fldx** [microsoft/vcpkg#39761]
**Describe the bug**

**Environment**
- OS: Windows 11
- Compiler: revision

**To Reproduce**
1. ./vcpkg install blend2d
2. See error
Repro code when

**Expected behavior**

**Failure logs**
-(please attached failure logs)
![image](https://github.com/microsoft/vcpkg/assets/11643460/41ee4668-259a-4b2d-a1b4-2a558fb65fa6)

**Additional context**

**Comment by WangWeiLin-MV** [comment]
Please make sure that the compiler was installed correctly, or the compiler executable is in environment variable PATH.

**Comment by dg0yt** [comment]
Remove msys (/usr/bin) CMake from your PATH. It is POSIX subsystem, with POSIX path separators *only*.

**Comment by fldx** [comment]
> Remove msys (/usr/bin) CMake from your PATH. It is POSIX subsystem, with POSIX path separators _only_.

Thank you
