### ISSUE TITLE
[glfw3] Build error on x64-linux

### ISSUE THREAD

**Issue by GinShio** [microsoft/vcpkg#39765]
Package: glfw3:x64-linux@3.4

**Host Environment**

- Host: x64-linux
- Compiler: GNU 13.3.0
-    vcpkg-tool version: 2024-03-14-7d353e869753e5609a1f1a057df3db8fd356e49d
    vcpkg-scripts version: a34c873a9 2024-03-22 (4 months ago)

**To Reproduce**

`vcpkg install boost-exception:x64-linux boost-program-options:x64-linux boost-stacktrace:x64-linux glfw3:x64-linux glm:x64-linux imgui[core,freetype,glfw-binding,vulkan-binding]:x64-linux stb:x64-linux tinyobjloader:x64-linux`
**Failure logs**

```
-- Downloading https://github.com/glfw/glfw/archive/3.4.tar.gz -> glfw-glfw-3.4.tar.gz...
-- Extracting source /home/russell/Projects/RayTracingInVulkan/build/vcpkg.linux/downloads/glfw-glfw-3.4.tar.gz
-- Using source at /home/russell/Projects/RayTracingInVulkan/build/vcpkg.linux/buildtrees/glfw3/src/3.4-2448ff4533.clean
GLFW3 currently requires the following libraries from the system package manager:
    xinerama
    xcursor
    xorg
    libglu1-mesa
    pkg-config

These can be installed on Ubuntu systems via sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config

Alternatively, when targeting the Wayland display server, use the packages listed in the GLFW documentation here:

https://www.glfw.org/docs/3.3/compile.html#compile_deps_wayland
-- Found external ninja('1.12.1').
-- Configuring x64-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/ninja -v
    Working Directory: /home/russell/Projects/RayTracingInVulkan/build/vcpkg.linux/buildtrees/glfw3/x64-linux-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      /home/russell/Projects/RayTracingInVulkan/build/vcpkg.linux/buildtrees/glfw3/config-x64-linux-dbg-CMakeCache.txt.log
      /home/russell/Projects/RayTracingInVulkan/build/vcpkg.linux/buildtrees/glfw3/config-x64-linux-rel-CMakeCache.txt.log
      /home/russell/Projects/RayTracingInVulkan/build/vcpkg.linux/buildtrees/glfw3/config-x64-linux-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:252 (vcpkg_execute_required_process)
  ports/glfw3/portfile.cmake:40 (vcpkg_cmake_configure)
  scripts/ports.cmake:175 (include)
```

[config-x64-linux-out.log](https://github.com/user-attachments/files/16130822/config-x64-linux-out.log)
[config-x64-linux-rel-CMakeCache.txt.log](https://github.com/user-attachments/files/16130823/config-x64-linux-rel-CMakeCache.txt.log)
[config-x64-linux-dbg-CMakeCache.txt.log](https://github.com/user-attachments/files/16130824/config-x64-linux-dbg-CMakeCache.txt.log)

**Comment by LilyWangLL** [comment]
> CMake Error at src/CMakeLists.txt:192 (message):
>   Xinerama headers not found; install libxinerama development package

The build failure due to missing `libxinerama`, please fix the build error by the following message:
```
GLFW3 currently requires the following libraries from the system package manager:
    xinerama
    xcursor
    xorg
    libglu1-mesa
    pkg-config

These can be installed on Ubuntu systems via sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config
```

**Comment by GinShio** [comment]
Thanks, it's my bad.
I installed these packages, but still got a configuration error. After review the log file, I found I don't install `libXi-devel`.

```fundamental
CMake Error at src/CMakeLists.txt:210 (message):
  XInput headers not found; install libxi development package
```

I use openSUSE Tumbleweed, so I'm not sure this package need to manually install.
**So, please add this package in requirement list.**
