### ISSUE TITLE
strawberryperl.com is not accessible

### ISSUE THREAD

**Issue by jakubkid** [Microsoft/vcpkg#3977]
strawberryperl.com seems to be completely down now. It would be nice to have some backup server because after reading forums it is not the first time it happened. Because of that download fails with following message:
Starting package 1/3: openssl-windows:x64-windows
Building package openssl-windows[core]:x64-windows...
-- Downloading http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portable.zip...
-- Downloading http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portable.zip... Failed. Status: 6;"Couldn't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:151 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:217 (vcpkg_download_distfile)
  ports/openssl-windows/portfile.cmake:9 (vcpkg_find_acquire_program)
  scripts/ports.cmake:71 (include)

**Comment by Voskrese** [comment]
https://github.com/Microsoft/vcpkg/issues/3973#issuecomment-408871654

**Comment by albertziegenhagel** [comment]
As a temporary workaround while the website is down you can download the file from http://vcell.org/webstart/strawberry-perl-5.24.1.1-32bit-portable.zip and move it into `<vcpkg_root>/downloads` manually.

**Comment by jakubkid** [comment]
Thanks Albert I didn't know I can download it manually, Looks like strawberryperl.com is back online.

**Comment by traversaro** [comment]
If there is a reliable mirror for that file, it can be added directly in the `vcpkg_find_acquire_program.cmake` CMake script at https://github.com/Microsoft/vcpkg/blob/b5e4c4c7cf68b807e222b09415b678d2f47a3d3b/scripts/cmake/vcpkg_find_acquire_program.cmake#L56 , but perhaps it is a bit rude to add the URL to a widely used system such as vcpkg without asking beforehand to the vcell.org admins. 

If Microsoft could provide fall back hosting, even here on GitHub, for a few critical tarballs, it would be great. This perl tarball in particular seems to be quite problematic, and it is a dependency for the widely used `openssl` port.

**Comment by pkeir** [comment]
For me, I'd set my `HTTPS_PROXY`, but not my `HTTP_PROXY`. (Installing boost:x64-windows I got through tens of packages before halting here too..) Setting `HTTP_PROXY` allowed me to proceed. I still wonder why the 32 version of Strawberry Perl is targeted.

**Comment by mcgoo** [comment]
Looks like it is down again at the moment. (I have been unable to hit it for about 6 hours.)

https://github.com/StrawberryPerl/strawberryperl.com/issues/16
