### ISSUE TITLE
[thrift] build failure

### ISSUE THREAD

**Issue by harris-josh** [microsoft/vcpkg#39786]
### Operating system

Windows/macOS/Linux

### Steps to reproduce the behavior

```Shell
./vcpkg install thrift
```

### Failure logs

```
Installing 1/1 thrift:x64-linux@0.20.0...
Building thrift:x64-linux@0.20.0...
-- Downloading https://github.com/apache/thrift/archive/0.20.0.tar.gz -> apache-thrift-0.20.0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Disabling metrics because vcpkg.disable-metrics exists
[DEBUG] Trying to load bundleconfig from /home/user/vcpkg/vcpkg-bundle.json
[DEBUG] Failed to open: /home/user/vcpkg/vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
[DEBUG] 1000: execute_process(curl --fail -L https://github.com/apache/thrift/archive/0.20.0.tar.gz --create-dirs --output /home/user/vcpkg/downloads/apache-thrift-0.20.0.tar.gz.1360638.part)
[DEBUG] 1000: cmd_execute_and_stream_data() returned 0 after  1038717 us
[DEBUG] Trying to hash /home/user/vcpkg/downloads/apache-thrift-0.20.0.tar.gz.1360638.part
[DEBUG] /home/user/vcpkg/downloads/apache-thrift-0.20.0.tar.gz.1360638.part has hash 86a609f5725506abc2109902b338cbaad85abf980f9d28c63e6e50a5c265dc10699372c4e91f5ee85d8d09fbcbb0dc17c19745b86d215b96bbf7d0a9270f0932
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/apache/thrift/archive/0.20.0.tar.gz
File: /home/user/vcpkg/downloads/apache-thrift-0.20.0.tar.gz.1360638.part
Expected hash: 5e4ee9870b30fe5ba484d39781c435716f7f3903793dc8aae96594ca813b1a5a73363b84719038ca8fa3ab8ef0a419a28410d936ff7b3bbadf36fc085a6883ae
Actual hash: 86a609f5725506abc2109902b338cbaad85abf980f9d28c63e6e50a5c265dc10699372c4e91f5ee85d8d09fbcbb0dc17c19745b86d215b96bbf7d0a9270f0932
[DEBUG] /mnt/vss/_work/1/s/src/vcpkg/base/downloads.cpp(1048):
[DEBUG] Time in subprocesses: 1038717us
[DEBUG] Time in parsing JSON: 3us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 19us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 1 s (1048244us)
```

### Additional context

It looks like commit https://github.com/apache/thrift/commit/a1898053bba390b2069179b914c7339caab9b7ef was introduced on the 0.20.0 branch which invalidates the expected SHA-512 hash.

A quick fix would be to just update the hash, but I'm not sure if that's desired behavior or if the actual tagged v0.20.0 version should be used here.

**Comment by diverru** [comment]
up

**Comment by diverru** [comment]
/home/diver/.cache/vcpkg/registries/git-trees/6855be1ce96497811d4eb0a9879baf6cf1b3610c: info: installing overlay port from here
-- Downloading https://github.com/apache/thrift/archive/0.20.0.tar.gz -> apache-thrift-0.20.0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from /home/diver/vcpkg/vcpkg-bundle.json
[DEBUG] Failed to open: /home/diver/vcpkg/vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
[DEBUG] 1000: execute_process(curl --fail -L https://github.com/apache/thrift/archive/0.20.0.tar.gz --create-dirs --output /home/diver/vcpkg/downloads/apache-thrift-0.20.0.tar.gz.942600.part)
[DEBUG] 1000: cmd_execute_and_stream_data() returned 0 after  1001987 us
[DEBUG] Trying to hash /home/diver/vcpkg/downloads/apache-thrift-0.20.0.tar.gz.942600.part
[DEBUG] /home/diver/vcpkg/downloads/apache-thrift-0.20.0.tar.gz.942600.part has hash 86a609f5725506abc2109902b338cbaad85abf980f9d28c63e6e50a5c265dc10699372c4e91f5ee85d8d09fbcbb0dc17c19745b86d215b96bbf7d0a9270f0932
error: Missing apache-thrift-0.20.0.tar.gz and downloads are blocked by x-block-origin.
error: File does not have the expected hash:
url: https://github.com/apache/thrift/archive/0.20.0.tar.gz
File: /home/diver/vcpkg/downloads/apache-thrift-0.20.0.tar.gz.942600.part
Expected hash: 5e4ee9870b30fe5ba484d39781c435716f7f3903793dc8aae96594ca813b1a5a73363b84719038ca8fa3ab8ef0a419a28410d936ff7b3bbadf36fc085a6883ae
Actual hash: 86a609f5725506abc2109902b338cbaad85abf980f9d28c63e6e50a5c265dc10699372c4e91f5ee85d8d09fbcbb0dc17c19745b86d215b96bbf7d0a9270f0932
[DEBUG] /source/src/vcpkg/base/downloads.cpp(1030):
[DEBUG] Time in subprocesses: 1001987us
[DEBUG] Time in parsing JSON: 9us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 416us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 1 s (1045439us)

**Comment by diverru** [comment]
Fixing hash in ports/thrift/portfile.cmake doesn't have any influence

**Comment by MonicaLiu0311** [comment]
I didn't repro your issue.
```
PS G:\vcpkg> ./vcpkg install thrift
Computing installation plan...
The following packages will be built and installed:
    thrift:x64-windows@0.20.0#1
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from C:\Users\monica\AppData\Local\vcpkg\archives in 174 us. Use --debug to see more details.
Installing 1/1 thrift:x64-windows@0.20.0#1...
Building thrift:x64-windows@0.20.0#1...
-- Note: thrift only supports static library linkage. Building static library.
-- Using cached apache-thrift-v0.20.0.tar.gz.
-- Extracting source G:/vcpkg/downloads/apache-thrift-v0.20.0.tar.gz
-- Applying patch correct-paths.patch
-- Applying patch pc-suffix.patch
-- Using source at G:/vcpkg/buildtrees/thrift/src/v0.20.0-8f0d9a10a3.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig file: G:/vcpkg/packages/thrift_x64-windows/lib/pkgconfig/thrift-nb.pc
-- Fixing pkgconfig file: G:/vcpkg/packages/thrift_x64-windows/lib/pkgconfig/thrift-z.pc
-- Fixing pkgconfig file: G:/vcpkg/packages/thrift_x64-windows/lib/pkgconfig/thrift.pc
-- Using cached msys2-mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.5.3-3-x86_64.pkg.tar.zst.
-- Using msys root at G:/vcpkg/downloads/tools/msys2/1e74ca60daa10104
-- Fixing pkgconfig file: G:/vcpkg/packages/thrift_x64-windows/debug/lib/pkgconfig/thrift-nb.pc
-- Fixing pkgconfig file: G:/vcpkg/packages/thrift_x64-windows/debug/lib/pkgconfig/thrift-z.pc
-- Fixing pkgconfig file: G:/vcpkg/packages/thrift_x64-windows/debug/lib/pkgconfig/thrift.pc
-- Installing: G:/vcpkg/packages/thrift_x64-windows/share/thrift/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 4 s.
Elapsed time to handle thrift:x64-windows: 2.1 min
thrift:x64-windows package ABI: 7e6e589a7564623077a0ebf72e509cfe6b2970053c1942534cce34ae71218af0
Total install time: 2.1 min
thrift provides CMake targets:

  # this is heuristically generated, and may not be correct
  find_package(Thrift CONFIG REQUIRED)
  target_link_libraries(main PRIVATE thrift::thrift thriftz::thriftz thriftnb::thriftnb)

thrift provides pkg-config modules:

  # Thrift Nonblocking API
  thrift-nb

  # Thrift Zlib API
  thrift-z

  # Thrift C++ API
  thrift
```

Please run the following commands and try again:
```
git pull https://github.com/microsoft/vcpkg.git master
./vcpkg remove thrift --recurse
./vcpkg install thrift --binarysource=clear
```

**Comment by garthgoodson** [comment]
I'm still seeing this issue.  Running in manifest mode, blew away vcpkg (and ~/.cache/vcpkg) and repulled it.  Using a builtin-baseline that is older due to older dependencies, no version override for thrift.  Still seeing mismatched hash, not sure how to resolve.
