### ISSUE TITLE
[New Port Request] libplacebo

### ISSUE THREAD

**Issue by Hlongyu** [microsoft/vcpkg#39791]
### Library name

libplacebo

### Library description

libplacebo is, in a nutshell, the core rendering algorithms and ideas of mpv rewritten as an independent library. As of today, libplacebo contains a large assortment of video processing shaders, focusing on both quality and performance.libplacebo is, in a nutshell, the core rendering algorithms and ideas of mpv rewritten as an independent library. As of today, libplacebo contains a large assortment of video processing shaders, focusing on both quality and performance.

### Source repository URL

https://github.com/haasn/libplacebo/tree/master

**Comment by capric8416** [comment]
I'm porting now
https://github.com/MediaPorts
