### ISSUE TITLE
Add Range-V3-VS2015?

### ISSUE THREAD

**Issue by LYP951018** [Microsoft/vcpkg#398]
https://github.com/Microsoft/Range-V3-VS2015

**Comment by sdcb** [comment]
There was one here:
https://github.com/Microsoft/vcpkg/commit/6fb82365f49901fee330ae00ba0be7a0f85be06d

But we updated it to here:
https://github.com/Microsoft/vcpkg/tree/master/ports/range-v3

so basically you can install range-v3-vs2015 by typing: 
vcpkg install range-v3
