### ISSUE TITLE
Setting clang 6 as CC/CXX causes Illegal number: clang version 6

### ISSUE THREAD

**Issue by JasonDictos** [Microsoft/vcpkg#3980]
So I'm trying to build my vcpkg dependencies with clang 6.0, the first thing I noticed is this error when setting CC and CXX to clang/clang++:

'/home/jason/signalwire/swsdk/deps/vcpkg/bootstrap-vcpkg.sh: 182: [: Illegal number: clang version 6'

Whats going on here?

**Comment by chausner** [comment]
It seems the bootstrap script on Linux only supports gcc/g++ at the moment. Assuming the rest of vcpkg is compatible to Clang, it should be easy to adapt boostrap.sh to support Clang.

**Comment by JasonDictos** [comment]
I have a fork right now where we build everything with clang-6.0.1 toolchains and triplets. It works but its not good enough for a pr yet, we'll get there.

**Comment by JasonDictos** [comment]
Also I noticed there's more then a few places where the ENV is manipulated with windows style semi-colons rather then linux style colons. Had to fix a few of those for various issues.

**Comment by degski** [comment]
@JasonDictos 

This is great news, I like that. Since it's not ready for prime-time, it seems a good idea to hold on and move to clang 7.0.0 right away. They just passed RC1, so Stable Release will be out within days.

**Comment by JasonDictos** [comment]
Ok good to hear those clang guys are always on top of the c++ scene. Note I actually got even vcpkg itself to build with clang as well so the entire stack, dependencies etc, all are fully on the clang toolchain using a generic cmake toolchain file. This should be a top level option on the bootstrap script as well as a commandline option when building dependencies, since its pretty roundabout right now with the triplets (I have to use an env var to pass along my clang toolchain cmake file).

**Comment by degski** [comment]
@JasonDictos 

It's seems I was over-optimistic, release date appears to be 5th of September. In the meanwhile, there's a recent (windows) trunk build [here](https://llvm.org/builds/).

**Comment by ras0219-msft** [comment]
@JasonDictos Great to hear!

You shouldn't need to use environment variables; by setting `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` in a custom triplet we should pass the right thing in.

[1] https://github.com/Microsoft/vcpkg/blob/master/docs/users/triplets.md#vcpkg_chainload_toolchain_file

**Comment by JasonDictos** [comment]
Well yeah but if its going to find the cmake toolchain file it has to know the path right, thats different based on where we decide to clone our project out. So the only way I can really communicate with the triplet without writing one off ones every time, is the env.
