### ISSUE TITLE
[<port name>] build failure

### ISSUE THREAD

**Issue by Ardish4** [microsoft/vcpkg#39808]
### Operating system

Windows

### Steps to reproduce the behavior

```Shell
vcpkg install jsoncpp:x64-windows zlib:x64-windows openssl:x64-windows sqlite3:x64-windows libpq:x64-windows libpqxx:x64-windows drogon[core,ctl,sqlite3,postgres,orm]:x64-windows
```

### Failure logs

error: building drogon:x64-windows failed with: BUILD_FAILED
Elapsed time to handle drogon:x64-windows: 3.8 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+drogon
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[drogon]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2FProgram%20Files%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

**C:\Program Files\vcpkg\installed\x64-windows>** _vcpkg install jsoncpp:x64-windows zlib:x64-windows openssl:x64-windows sqlite3:x64-windows libpq:x64-windows libpqxx:x64-windows drogon[core,ctl,sqlite3,postgres,orm]:x64-windows_
Computing installation plan...
The following packages are already installed:
    jsoncpp:x64-windows@1.9.5#4
    libpq[core,zlib,openssl,lz4]:x64-windows@16.2#1
    openssl:x64-windows@3.3.1#1
    sqlite3[core,json1]:x64-windows@3.46.0#2
    zlib:x64-windows@1.3.1
The following packages will be built and installed:
    drogon[core,ctl,orm,postgres,sqlite3]:x64-windows@1.9.5
    libpqxx:x64-windows@7.9.0
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exeRestored 0 package(s) from C:\Users\adi\AppData\Local\vcpkg\archives in 216 us. Use --debug to see more details.
jsoncpp:x64-windows is already installed
libpq:x64-windows is already installed
sqlite3:x64-windows is already installed
zlib:x64-windows is already installed
openssl:x64-windows is already installed
Installing 1/2 drogon[core,ctl,orm,postgres,sqlite3]:x64-windows@1.9.5...
Building drogon[core,ctl,orm,postgres,sqlite3]:x64-windows@1.9.5...
-- Using cached an-tao-drogon-v1.9.5.tar.gz.
-- Cleaning sources at C:/Program Files/vcpkg/buildtrees/drogon/src/v1.9.5-d600c126fc.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Program Files/vcpkg/downloads/an-tao-drogon-v1.9.5.tar.gz
-- Applying patch 0001-vcpkg.patch
-- Applying patch 0002-drogon-config.patch
-- Applying patch 0003-deps-redis.patch
-- Applying patch 0004-drogon-ctl.patch
-- Applying patch 0005-drogon-cross-compile.patch
-- Using source at C:/Program Files/vcpkg/buildtrees/drogon/src/v1.9.5-d600c126fc.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/vcpkg/downloads/tools/cmake-3.29.2-windows/cmake-3.29.2-windows-i386/bin/cmake.exe" --build . --config Release --target install -- -v -j5
    Working Directory: C:/Program Files/vcpkg/buildtrees/drogon/x64-windows-rel
    See logs for more information:
      C:\Program Files\vcpkg\buildtrees\drogon\install-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/drogon/portfile.cmake:49 (vcpkg_cmake_install)
  scripts/ports.cmake:192 (include)

error: building drogon:x64-windows failed with: BUILD_FAILED
Elapsed time to handle drogon:x64-windows: 3.8 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+drogon
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[drogon]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2FProgram%20Files%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by FrankXie05** [comment]
@Ardish4 Could you please provide the error log? 
```
C:\Program Files\vcpkg\buildtrees\drogon\install-x64-windows-rel-out.log
```

**Comment by Ardish4** [comment]
> @Ardish4 Could you please provide the error log?
> 
> ```
> C:\Program Files\vcpkg\buildtrees\drogon\install-x64-windows-rel-out.log
> ```

[install-x64-windows-rel-out.log](https://github.com/user-attachments/files/16171739/install-x64-windows-rel-out.log)

**Comment by FrankXie05** [comment]
> > @Ardish4 Could you please provide the error log?
> > ```
> > C:\Program Files\vcpkg\buildtrees\drogon\install-x64-windows-rel-out.log
> > ```
> 
> [install-x64-windows-rel-out.log](https://github.com/user-attachments/files/16171739/install-x64-windows-rel-out.log)

I don't see any errors in the log file you provided.

**Comment by FrankXie05** [comment]
@Ardish4 Thanks for providing the log file. This problem is that the view fails to be created. I suspect it is because of the space in the path.  Could you please put vcpkg in the root directory(eg: `E:\`) and try again?
```
create view:C:/Program Files/vcpkg/buildtrees/drogon/src/v1.9.5-d600c126fc.clean/drogon_ctl/templates/config_yaml.csp

create HttpView Class file by C:/Program Files/vcpkg/buildtrees/drogon/src/v1.9.5-d600c126fc.clean/drogon_ctl/templates/config_yaml.csp

className=config_yaml
```

**Comment by Ardish4** [comment]
I have copied the folder in "C://" and deleted the "vcpkg" folder from "C://Program Files/". I also updated the vcpkg environment variable.
Rerun this command as administrator:
`vcpkg install jsoncpp:x64-windows zlib:x64-windows openssl:x64-windows sqlite3:x64-windows libpq:x64-windows libpqxx:x64-windows drogon[core,ctl,sqlite3,postgres,orm]:x64-windows`

It is still showing an error, here is the build file:
[install-x64-windows-rel-out.log](https://github.com/user-attachments/files/16216134/install-x64-windows-rel-out.log)
