### ISSUE TITLE
[xsimd] build failure on Windows only

### ISSUE THREAD

**Issue by Nosenzor** [microsoft/vcpkg#39810]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
There's no error when installing this package because it's header only.
But there's an error when using it on windows (it's fine on mac and linux)
```

### Failure logs

Below is some traces from Github Actions.
 D:\a\FW\builds\ninja-release-vcpkg\vcpkg_installed\x64-windows\include\xsimd\arch\generic\./xsimd_generic_details.hpp(207,22): error C2187: syntax error: 'char' was unexpected here
  D:\a\FW\builds\ninja-release-vcpkg\vcpkg_installed\x64-windows\include\xsimd\arch\generic\./xsimd_generic_details.hpp(207,28): error C3878: syntax error: unexpected token '=' following 'simple_declaration'
  D:\a\FW\builds\ninja-release-vcpkg\vcpkg_installed\x64-windows\include\xsimd\arch\generic\./xsimd_generic_details.hpp(207,28): note: error recovery skipped: '='
  D:\a\FW\builds\ninja-release-vcpkg\vcpkg_installed\x64-windows\include\xsimd\arch\generic\./xsimd_generic_details.hpp(211,76): error C2760: syntax error: ')' was unexpected here; expected 'expression'
  D:\a\FW\builds\ninja-release-vcpkg\vcpkg_installed\x64-windows\include\xsimd\arch\generic\./xsimd_generic_details.hpp(211,76): error C2760: syntax error: ')' was unexpected here; expected ';'
  D:\a\FW\builds\ninja-release-vcpkg\vcpkg_installed\x64-windows\include\xsimd\arch\generic\./xsimd_generic_details.hpp(211,76): error C3878: syntax error: unexpected token ')' following 'jump_statement'
  D:\a\FW\builds\ninja-release-vcpkg\vcpkg_installed\x64-windows\include\xsimd\arch\generic\./xsimd_generic_details.hpp(211,76): note: error recovery skipped: ') )'

### Additional context

If i comment those lines on local computer then the build is correct.

**Comment by Nosenzor** [comment]
Opened a bug in xsimd repo too : https://github.com/xtensor-stack/xsimd/issues/1037

**Comment by jimwang118** [comment]
Confirmed that this issue has been reproduced locally.
