### ISSUE TITLE
[boost] build failure with vs 2022 17.10.33

### ISSUE THREAD

**Issue by jalalsadegh** [microsoft/vcpkg#39816]
### Operating system

windows

### Compiler

msvc

### Steps to reproduce the behavior

```Shell
I had a project that was building successfully with vs 2022 previous version after upgrading to 17.10.4 and for some reason building vcpackage again the build is failed with below log. but the point is that when i open boost_thread building log this error is seen:
error:     '/boost//H:/misSolution_2010/misSoloution/vcpkg_installed/x64-windows/x64-windows/debug/lib/boost_chrono-vc140-mt-gd.lib'
Why vc140 libraries?
and also, when i create a new project the project build successful but old project is not building.
```

### Failure logs

Build started at 9:01 AM...
1>------ Build started: Project: CoreSystemServices, Configuration: Debug x64 ------
1>Installing vcpkg dependencies to H:\misSolution_2010\misSoloution\vcpkg_installed\x64-windows\
1>"H:\vcpkg\vcpkg.exe" install  --x-wait-for-lock --triplet "x64-windows" --vcpkg-root "H:\vcpkg\\" "--x-manifest-root=H:\misSolution_2010\misSoloution\\" "--x-install-root=H:\misSolution_2010\misSoloution\vcpkg_installed\x64-windows\\"
1>Loading dependency information for 150 packages...
1>Detecting compiler hash for triplet x64-windows...
1>-- Automatically setting %HTTP(S)_PROXY% environment variables to "127.0.0.1:8086".
1>Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe
1>The following packages will be built and installed:
1>    boost:x64-windows@1.83.0#1 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\315139e076ff5ea5672a158688934b04d2b7a815
1>  * boost-accumulators:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\fbc8e739bd519a5da1db826cb1cd6b14c0072533
1>  * boost-any:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\8995a49c0eb70b1e306323f70d79dc5b6343bd6b
1>  * boost-asio:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\0d4a6f6c528811c3c79ac046e738e5bab3db995f
1>  * boost-assign:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\9ba196ef5fe0c4127c48503b32b1107c3d2575e6
1>  * boost-beast:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\cf5be95a5b8d706f46ad14f219b940a3fb0c3ef4
1>  * boost-bimap:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\0c07fcb928615b411a23ca3676e62494c3304f31
1>  * boost-callable-traits:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\0558d1c063b8c2137f5e44644bc4c47180f30da1
1>  * boost-circular-buffer:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\4df4c980c22d3b54856d81430343e6ce70a18521
1>  * boost-compat:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\790894b29260c3cb8b2bd6be3bd2822e3118789e
1>  * boost-compatibility:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\f503e07b29b61e3679b9efd9986ac64503808dea
1>  * boost-compute:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\3e4c8cd7be193c46ac0e3633dd63b723dac6f363
1>  * boost-context:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\2c0ccde97a196bd6c78f0fbb52ae9c8b33a525b5
1>  * boost-contract:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\2c3cb8d14edbf7d1f72bcb9604c134828c52db92
1>  * boost-convert:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\7b29caca0f13ed5f5c083216a177a43984cab5fb
1>  * boost-coroutine:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\d8a5c2cff3de497580fc8dc363ebc3e8ec0c9a1d
1>  * boost-coroutine2:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\07cd3acf80575853ec41795a24803f75605f9c9b
1>  * boost-crc:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\b0f11a830b77b6a039d0d008a18b066d99a87672
1>  * boost-dll:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\9458e313715bc4132ded9a04a5d991f9993dcafb
1>  * boost-dynamic-bitset:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\783e8e0c0387114a445ad62dacbbb2f2ce910cd2
1>  * boost-endian:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\5321b25b38e55ebe1bbeb54242c104e208b643f8
1>  * boost-fiber:x64-windows@1.83.0#1 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\7eadb0ddae816cfed4358cb08ef2bc90c5c0bfa5
1>  * boost-filesystem:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\f6419d12dfeb0010846e425acd9e5b27772e1ac9
1>  * boost-flyweight:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\ef75501a5a95e34a23f190e5d41792311f4b29fe
1>  * boost-foreach:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\10ddba1bb2b7513dc1459166eed1f4f1b25aa49d
1>  * boost-format:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\8b4697f0c1e3cc49f4bf08c12b748544c132db48
1>  * boost-geometry:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\24efcc4edf764482c058e70a2ce8ab500d40d1c2
1>  * boost-gil:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\0a3fb8c8c6ef3abbe51fb887be13d94d8c4bb983
1>  * boost-graph:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\6647f8f09420268c0381bf2416492cedcc348c73
1>  * boost-heap:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\c7dc9b45d83570bc364f2eec2caa556ca1cbb5a3
1>  * boost-histogram:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\cfb8451fad642630b3bd4072178d9ac1b318d705
1>  * boost-hof:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\56156c027ebd8af07a502ea9b5fc58fee6cc0b64
1>  * boost-icl:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\d8cf7df44d1c0d7579411af9d8c0decdf498475d
1>  * boost-interprocess:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\685634ef2e0b7c514fc454d668e27c17937dc005
1>  * boost-interval:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\a3eb772da1f0b5a2fe86601716b0fa8fc8aae645
1>  * boost-iostreams[bzip2,core,lzma,zlib,zstd]:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\da8972f0e4c59981021913e4ef16a39a9ff8d491
1>  * boost-json:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\bf515b1083df1c9d11c17713ea9cd22ad8deee20
1>  * boost-lambda:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\9f5b545dcb43d7901ce68b14f598605e86b2711a
1>  * boost-lambda2:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\399a7528e08b7a9e7a888cbb7d4a60c3212d3fc4
1>  * boost-leaf:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\9c5d7bf52009af1e4fa9ab2bf88a8592a3f9c2f0
1>  * boost-local-function:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\f059d8e9dc60d429ca4910eb0603b7ad768339b1
1>  * boost-locale:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\41e9801248d577c58c9827d2177ec7a88719b116
1>  * boost-lockfree:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\db32f8262d243ce50d3dd2b67e9f13ce9fb584f0
1>  * boost-log:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\a9fc311a8361a136d6723b2a45e98af511749e7d
1>  * boost-logic:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\4caeef24d5d621a2a42819bdcea2ee90b4414f5a
1>  * boost-math:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\d2b21d46b8da00d788266ec6b386602f345659c1
1>  * boost-metaparse:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\5994a689a2da98a3effa716ab52de1b13266fe13
1>  * boost-msm:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\1e6c265d4b9681f5da0f23cb3a3912498fe4fbb2
1>  * boost-multi-array:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\f7c1d6533820072446bd68c928c72964501def1e
1>  * boost-multi-index:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\7d40ee58c3e54b9c841abc6dd57033366218f064
1>  * boost-multiprecision:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\d5c0acb2f8f25475a0a69d41460e377e6ce66749
1>  * boost-mysql:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\0acda793061ac85e68029b15c6fa6919a2f87e8d
1>  * boost-nowide:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\b4c07fcec5ae6b5f94811dbd50ee720884d65752
1>  * boost-odeint:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\f65beca22b3663038f2d5da292a1dd7f63c1fc23
1>  * boost-outcome:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\b4f9214c118d7d3ee45f5c2624f8383ff596fa14
1>  * boost-parameter:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\1dce1428072cad1f8bc7b6c02f14cc6ba12da3fd
1>  * boost-parameter-python:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\3894f883ee35b2bae2f102c520e81deca80f6643
1>  * boost-pfr:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\2a38c23f0ff2226b879e1ef04aefd19f479bc5a6
1>  * boost-phoenix:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\a4c5832e8ebf68cd4f2ee601a10aa7adfc12e6e9
1>  * boost-poly-collection:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\28e876df1967c012343839a6258191ce5107e5f7
1>  * boost-polygon:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\a2cd356928aae40e3ed8a5764f868de84dde981d
1>  * boost-pool:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\e5c81fe62cb0da4fdc940d21d87837678a2e67cf
1>  * boost-process:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\d0426afce7bf4a50b9928232515951043a59bcd3
1>  * boost-program-options:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\ce15d2fa5ea81e6da9f8ec078cfe466f4d4e0339
1>  * boost-property-map:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\1b4cf346ccedc4c90c63a8676b0115554301a62c
1>  * boost-property-tree:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\caa9ef5866c4dcf2869fca47fb3a478f74e07f7a
1>  * boost-proto:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\7bb3591b035347ce419b85ae321c0e1b6c71084a
1>  * boost-ptr-container:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\5b926ddc4f1044a202ed6b5a052fab6d6578f051
1>  * boost-python[core,python3]:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\2e89ec0e4997ffd54bfbbd891df39df068d84fc7
1>  * boost-qvm:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\7f023cb85fbc266b836aabc8f0b66d55332869d6
1>  * boost-random:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\045960cb6d4295d363e1748931ea56fc245f7c09
1>  * boost-safe-numerics:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\6ddd605460c8155173f242e5ec867b8baf9d0ec2
1>  * boost-scope-exit:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\735ee02b2601c7a8777fbe1d421d8e6933f7c40b
1>  * boost-serialization:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\7ebe53455e9721a76ebe14c651a2deafbcb758b8
1>  * boost-signals2:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\41fa1cbba1b311066df31c154e0926fe003039df
1>  * boost-sort:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\71805d53be199c5d3b2566456b9ae7cff9a8a94a
1>  * boost-spirit:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\e2ebc2bcf72d8ae953ac54163a7c5b43f17396f0
1>  * boost-stacktrace:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\d9fe043e8398589eaa7c319295a87114acb55538
1>  * boost-statechart:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\5d2243b3611cb12d9317e672fb7fbc296e87494c
1>  * boost-static-string:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\dba046b1b41f91b5927d8f4198157bc135d6a705
1>  * boost-stl-interfaces:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\c11bab85b94163499bbc4e7931ef1270fb64213d
1>  * boost-test:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\2e21f61b617327941161649451b4a022747fbc1e
1>  * boost-thread:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\f2f50fecd4338161565a0425c3e9b55fdbe68424
1>  * boost-timer:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\c143993e19cd4999f4199d79190b48058bd13a1a
1>  * boost-tti:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\06c466d2662d638138c5318e4ad3a165974de862
1>  * boost-type-erasure:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\9897b32081b334c6519a7252247d7dd292414e5d
1>  * boost-ublas:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\0a77eac23b724a17117bf6b25d8a40482d805b5f
1>  * boost-units:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\c9dffd7cd1fdc999f543b7d140f119f962ae076c
1>  * boost-url:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\2cfc398b72ab925f876eb071d9577cbf9a84f33d
1>  * boost-uuid:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\f87e5dc08c5466a56e32d055878d39dbdbdc18d4
1>  * boost-vmd:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\eaa0b491a87169b97213b923582836a9d3cd88ed
1>  * boost-wave:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\298ef29ed61665419dfb1f05e4823f63086afb14
1>  * boost-xpressive:x64-windows@1.83.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\55de0dfb037123cd093c56acf61b22948e98295b
1>  * bzip2[core,tool]:x64-windows@1.0.8#5 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\92e9a8bbf1abbd89872b48ad82fcf75852de1006
1>  * expat:x64-windows@2.5.0#3 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\9a1bc114edd74892d292c799e7b45b407f2a0b8b
1>  * libffi:x64-windows@3.4.4#5 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\db85488447cfda7bcc5e08452d8581ac0295b4c9
1>  * liblzma:x64-windows@5.4.3#1 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\3f97f6a0904a3add9c3273f8ab1993902d75d5ef
1>    libzip[bzip2,core,default-aes,wincrypto]:x64-windows@1.9.2#2 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\59242c6974f6245813fa69d09f9c6df6c501b895
1>  * openssl:x64-windows@3.1.2#3 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\11cbc05950decb26474353fb9c0bfed3be3008c4
1>  * pkgconf:x64-windows@1.8.0#5 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\8848e56b32837456dfb872f6ca3cc9953558d453
1>  * python3:x64-windows@3.11.5 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\52f5c3a91d997108f5acebea1748176156dbefc9
1>    sqlite3[core,json1]:x64-windows@3.43.0 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\4f7a1dcf86377b6045fbf05eb0ec1baff1d2ceb6
1>  * vcpkg-cmake-config:x64-windows@2022-02-06#1 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\8d54cc4f487d51b655abec5f9c9c3f86ca83311f
1>  * vcpkg-msbuild:x64-windows@2023-08-08 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\09443e951188f7850761144fde77fe9edf0dceba
1>  * vcpkg-pkgconfig-get-modules:x64-windows@2023-09-06 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\365f7303c0f9fe13458a62e7e4998760e6d918a4
1>  * vcpkg-tool-meson:x64-windows@0.63 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\bee0cb6c5edf45133ebc9643b86c9c775ab36cfe
1>  * zlib:x64-windows@1.3 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\5ac18c6e6e3e2bf5a9e3d0bc8a845f198e4c4e05
1>  * zstd:x64-windows@1.5.5#1 -- C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\44fdd2e1576b62ee75cdaab5ce74452ed08f84ce
1>Additional packages (*) will be modified to complete this operation.
1>Restored 2 package(s) from h:\packages\vcpkg in 89.2 ms. Use --debug to see more details.
1>Installing 1/108 boost-thread:x64-windows@1.83.0...
1>Building boost-thread:x64-windows@1.83.0...
1>C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\f2f50fecd4338161565a0425c3e9b55fdbe68424: info: installing overlay port from here
1>-- Using cached boostorg-thread-boost-1.83.0.tar.gz.
1>-- Cleaning sources at H:/vcpkg/buildtrees/boost-thread/src/ost-1.83.0-690cb03abf.clean. Use --editable to skip cleaning for the packages you specify.
1>-- Extracting source H:/vcpkg/downloads/boostorg-thread-boost-1.83.0.tar.gz
1>-- Using source at H:/vcpkg/buildtrees/boost-thread/src/ost-1.83.0-690cb03abf.clean
1>-- Including C:/Users/Jsadeghi/AppData/Local/vcpkg/registries/git-trees/f2f50fecd4338161565a0425c3e9b55fdbe68424/b2-options.cmake
1>-- Found external ninja('1.11.0').
1>-- Getting CMake variables for x64-windows
1>-- Configuring x64-windows
1>-- Building x64-windows-dbg
1>CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
1>    Command failed: H:/vcpkg/downloads/tools/cmake-3.29.2-windows/cmake-3.29.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j17
1>    Working Directory: H:/vcpkg/buildtrees/boost-thread/x64-windows-dbg
1>    See logs for more information:
1>      H:\vcpkg\buildtrees\boost-thread\install-x64-windows-dbg-out.log
1>
1>Call Stack (most recent call first):
1>  H:/misSolution_2010/misSoloution/vcpkg_installed/x64-windows/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
1>  H:/misSolution_2010/misSoloution/vcpkg_installed/x64-windows/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
1>  H:/misSolution_2010/misSoloution/vcpkg_installed/x64-windows/x64-windows/share/boost-build/boost-modular-build.cmake:139 (vcpkg_cmake_install)
1>  C:/Users/Jsadeghi/AppData/Local/vcpkg/registries/git-trees/f2f50fecd4338161565a0425c3e9b55fdbe68424/portfile.cmake:12 (boost_modular_build)
1>  scripts/ports.cmake:192 (include)
1>
1>
1>EXEC : error : building boost-thread:x64-windows failed with: BUILD_FAILED
1>Elapsed time to handle boost-thread:x64-windows: 2.3 s
1>Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
1>Then check for known issues at:
1>  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-thread
1>You can submit a new issue at:
1>  https://github.com/microsoft/vcpkg/issues/new?title=[boost-thread]+Build+error+on+x64-windows&body=Copy+issue+body+from+H%3A%2FmisSolution_2010%2FmisSoloution%2Fvcpkg_installed%2Fx64-windows%2Fvcpkg%2Fissue_body.md
1>You can also submit an issue by running (GitHub CLI must be installed):
1>  gh issue create -R microsoft/vcpkg --title "[boost-thread] Build failure on x64-windows" --body-file H:/misSolution_2010/misSoloution/vcpkg_installed/x64-windows/vcpkg/issue_body.md
1>H:\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(183,5): error MSB3073: The command ""H:\vcpkg\vcpkg.exe" install  --x-wait-for-lock --triplet "x64-windows" --vcpkg-root "H:\vcpkg\\" "--x-manifest-root=H:\misSolution_2010\misSoloution\\" "--x-install-root=H:\misSolution_2010\misSoloution\vcpkg_installed\x64-windows\\" " exited with code 1.
1>Done building project "CoreSystemServices.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 9:01 AM and took 09.075 seconds ==========

**Comment by LilyWangLL** [comment]
> 1>Installing 1/108 boost-thread:x64-windows@1.83.0...
> 1>Building boost-thread:x64-windows@1.83.0...
> 1>C:\Users\Jsadeghi\AppData\Local\vcpkg\registries\git-trees\f2f50fecd4338161565a0425c3e9b55fdbe68424: info: installing overlay port from here

Duplicate of issue https://github.com/microsoft/vcpkg/issues/38980, please refer to the solution from https://github.com/microsoft/vcpkg/issues/38980#issuecomment-2138632860.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
