### ISSUE TITLE
Invalid triplet

### ISSUE THREAD

**Issue by suryakiran** [microsoft/vcpkg#3984]
I'm trying to install breakpad with vcpkg for vs2017 compiler. Installed vcpkg using bootstrap.bat and giving command `.\vcpkg install breakpad`. I'm getting `Error: invalid triplet: x86-windows` error. 

`vcpkg help triplet` lists no available triplets. I tried giving triplet option explicitly like this
`vcpkg install breakpad --triplet x64-windows.cmake`. I'm getting `Error: invalid triplet: x64-windows.cmake`

What am I missing here ?

**Comment by Voskrese** [comment]
`vcpkg install breakpad --triplet x64-windows.cmake` not `.cmake`

`vcpkg install breakpad --triplet x64-windows`

**Comment by ras0219-msft** [comment]
@suryakiran Could you try removing the entire repo and re-cloning? Then, confirm that the `triplets\` directory is populated.

**Comment by sbj42** [comment]
Also check if you have the environment variable `VCPKG_ROOT` set.  If set, vcpkg will look there for triplets.
