### ISSUE TITLE
Add Apple TVos support 

### ISSUE THREAD

**Issue by AzanovAA** [microsoft/vcpkg#39842]
Hello, how can I make a triplet for Apple TVos?
As I understand there is no easy way and requires modifications inside vcpkg?

**Comment by WangWeiLin-MV** [comment]
You could check Apple's official cross-compilation documentation and refer to the PRs that similar Apple ecosystem triplet, like osx, iOS https://github.com/microsoft/vcpkg/pull/6275/files#diff-7ed2e6a85cfb24dea051b5c58291e8cd8108af1d5737fe18a34d1d79f0bb254b
