### ISSUE TITLE
[upb]BUILD_FAILED on x64-windows

### ISSUE THREAD

**Issue by dmarsal** [microsoft/vcpkg#39868]
Building the latest version of QT today (July 11th), I got this build error message
```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/Tools/cmake/bin/cmake.exe --build . --config Debug --target install -- -v -j25
    Working Directory: E:/Dev/vcpkg/buildtrees/upb/x64-windows-dbg
    See logs for more information:
      E:\Dev\vcpkg\buildtrees\upb\install-x64-windows-dbg-out.log
```

The error inside the file '**install-x64-windows-dbg-out.log**' is:
`E:\Dev\vcpkg\buildtrees\upb\src\v4.25.1-328a82a975.clean\upb\message\message.c(20): error C2099: initializer is not a constant
`
The line **20** of '**message.c**' is:
`const double kUpb_NaN = NAN;`

**Comment by FrankXie05** [comment]
I can't reproduce your problem locally.

The definition of this macro `NAN` is usually included in the header file `math.h`. For VS 2022, it supports `c99` and `c11` standards by default. Please make sure you are using the latest vcpkg and vs.

`message.c`:
```
#include "upb/message/message.h"

#include <math.h>

#include "upb/base/internal/log2.h"
#include "upb/message/internal/message.h"

// Must be last.
#include "upb/port/def.inc"

const float kUpb_FltInfinity = INFINITY;
const double kUpb_Infinity = INFINITY;
const double kUpb_NaN = NAN;

static const size_t overhead = sizeof(upb_Message_InternalData);
```

**Comment by dmarsal** [comment]
I am using the latest version from vcpkg: git clone https://github.com/microsoft/vcpkg
And Visual Studio Community 2022.
I am on 64-bit Windows 11.

My **message.c** file is same as what you pasted above.

Actually, I am trying to install/compile QT using the command
`.\vcpkg install qt
`
and it fails on upb compilation.

**Comment by dmarsal** [comment]
For information, I reproduce the same issue on a brand new system:
Fresh install Visual Studio Community 2022
Install Git from git-scm.com
Clone vcpkg
And the upb installation fails.

**Comment by dmarsal** [comment]
I have resolved this issue.
This is a problem with the latest version of Windows 11 SDK 10.26100.0.
See this [link](https://developercommunity.visualstudio.com/t/NAN-is-no-longer-compile-time-constant-i/10688907?pageSize=15&sort=active&topics=cppcompiler&q=__ucrt_int_to_float)

Rolling back to the previous version of Windows 11 SDK 10.0.22000.0 solves my issue.
