### ISSUE TITLE
[llvm] Set PYTHON_HOME for LLDB, but how?

### ISSUE THREAD

**Issue by TheAifam5** [Microsoft/vcpkg#3989]
Hi,

Does anyone know how can I set PYTHON_HOME that the LLDB finds it?
The simple set(ENV... does not work sadly.

Regards,
TheAifam5

**Comment by Voskrese** [comment]
Nothing is understood what you want, but here are some variables

```
set PYTHONHOME=e:\Anaconda2\
set PYTHONPATH=e:\Anaconda2\Lib
set LLVM_PATH=E:\tools\LLVM32
```

**Comment by TheAifam5** [comment]
@Voskrese I want to set the environment variable PYTHONHOME while compiling my LLVM package from my pull-request https://github.com/Microsoft/vcpkg/pull/3987 . The LLDB project doesn't see it and that's a problem.

**Comment by Voskrese** [comment]
http://lldb.llvm.org/build.html#BuildingLldbOnWindows

Required Dependencies

> 
>     Visual Studio 2015 or greater
>     Windows SDK 8.0 or higher. In general it is best to use the latest available version.
>     Python 3.5 or higher or higher. Earlier versions of Python can be made to work by compiling your own distribution from source, but this workflow is unsupported and you are own your own.
>     Ninja build tool (strongly recommended)
>     GnuWin32
>     SWIG for Windows (version 3+)


` cmake -G Ninja -DLLDB_TEST_DEBUG_TEST_CRASHES=1 -DPYTHON_HOME=C:\Python35 -DLLDB_TEST_USE_CUSTOM_C_COMPILER=ON -DLLDB_TEST_C_COMPILER=d:\src\llvmbuild\ninja_release\bin\clang.exe ..\..\llvm `

> `cmake -G Ninja <arguments>` or `cmake -G "Visual Studio 14 2015" <arguments>

**Comment by TheAifam5** [comment]
Yea I fixed it.. Now I see that the python version from `vcpkg_find_acquire_program` isn't a full version of python - its only binaries.
