### ISSUE TITLE
[openssl] Build error on x64-windows

### ISSUE THREAD

**Issue by adahox** [microsoft/vcpkg#39915]
Trying to install openssl shows me this errro:

```
error: building openssl:x64-windows failed with: BUILD_FAILEDSee https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.

Elapsed time to handle openssl:x64-windows: 2.1 min
```

**Comment by WangWeiLin-MV** [comment]
Using the latest version of vcpkg for local installation does not reproduce the issue.

Please try with latest vcpkg.

If the issue persists, please see #30604 for how to report a build failure.
