### ISSUE TITLE
Upgrade is failed

### ISSUE THREAD

**Issue by ProphetRu** [microsoft/vcpkg#39925]
>vcpkg upgrade boost
error: The following packages are not installed:
  boost:x64-windows
internal error: D:\a\_work\1\s\src\vcpkg\commands.upgrade.cpp(183): vcpkg has crashed; no additional details are available.
Please open an issue at https://github.com/microsoft/vcpkg/issues/new?template=other-type-of-bug-report.md&labels=category:vcpkg-bug with detailed steps to reproduce the problem.

**Comment by FrankXie05** [comment]
Please see #30604 for how to report an issue.
