### ISSUE TITLE
Interest in adding TagLib library

### ISSUE THREAD

**Issue by willkara** [Microsoft/vcpkg#3993]
I was hoping someone could either add support for installing the [TagLib](http://taglib.org/) library or show me some examples in how to add it myself.

[Here's](https://github.com/taglib/taglib) a link to its GitHub repo.

**Comment by ras0219-msft** [comment]
Take a look at our packaging example: https://github.com/Microsoft/vcpkg/blob/master/docs/examples/packaging-zlib.md

**Comment by evpobr** [comment]
It is already ported.

**Comment by willkara** [comment]
@evpobr , you're right! My apologies, not sure how I missed it.
