### ISSUE TITLE
How do I use vcpkg?

### ISSUE THREAD

**Issue by AFWSI** [Microsoft/vcpkg#3994]
I can't seem to follow the setup instructions I guess. I am trying to build this https://github.com/alicevision/AliceVision/blob/develop/INSTALL.md

I have done the  
```
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg

```
nothing seems to happen when I do
```
.\bootstrap-vcpkg.bat
```

How do I use vcpkg in the instructions posted above?

**Comment by OlafvdSpek** [comment]
What's `nothing`? ;)
Does it return to the prompt immediately?
Does it appear to hang?

**Comment by AFWSI** [comment]
@OlafvdSpek Yeah, going back to the prompt immediately. I finally got it to start working by getting vcpkg a little different. 

When I did this
```
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
.\bootstrap-vcpkg.bat
```
I noticed the `bootstrap-vcpkg.bat` was empty and nothing happens after you entered that.

I got everything again like this
```
git clone --recursive git://github.com/Microsoft/vcpkg
cd vcpkg
.\bootstrap-vcpkg.bat
```
and it setup vcpkg and was able to get it to work.
