### ISSUE TITLE
[reactiveplusplus] Cannot open source file using MSBuild

### ISSUE THREAD

**Issue by idotta** [microsoft/vcpkg#39940]
### Is your feature request related to a problem? Please describe.

When I try to use reactiveplusplus in manifest mode in a Visual Studio MSBuild project, the library is installed in directory `vcpkg_installed/.../include/rpp/rpp`. However, the install location is `vcpkg_installed/.../include/rpp`. This prevents the compiler from finding the rpp library directory. Even if I include it like `#include rpp/rpp/rpp.hpp`, the inner files depend on the correct location too.

### Proposed solution

Install the library in `vcpkg_installed/.../include/rpp`.

### Describe alternatives you've considered

Currently, I'm just using it as a submodule, but I'd like to include it with vcpkg like my other dependencies.

**Comment by MonicaLiu0311** [comment]
The directory for the rpp header files is:
![image](https://github.com/user-attachments/assets/dbabe7cf-eb73-4831-8e53-236ce670f230)

* CMake Project
    In the cmake project, the basis for finding the rpp header file is `INTERFACE_INCLUDE_DIRECTORIES`, which is defined in `share/RPP/RPPTargets.cmake`:
    ```
    set_target_properties(RPP::rpp PROPERTIES
      INTERFACE_COMPILE_FEATURES "cxx_std_20"
      INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/rpp"
      INTERFACE_LINK_LIBRARIES "Threads::Threads"
    )
    ```

    So in the CMake project, you only need to include the header file like this:
    ![image](https://github.com/user-attachments/assets/93ce3262-8ed0-413d-987d-8b1d6edc78e5)

    Other headers included in rpp.hpp are also searched in the `INTERFACE_INCLUDE_DIRECTORIES` directories:
    ```
    #pragma once

    #include <rpp/disposables.hpp>
    #include <rpp/fwd.hpp>
    #include <rpp/observables.hpp>
    #include <rpp/observers.hpp>
    #include <rpp/operators.hpp>
    #include <rpp/schedulers.hpp>
    #include <rpp/sources.hpp>
    #include <rpp/subjects.hpp>
    ```


* MSBuild Project
    In MSBuild projects, it is `not` searched through `RPPTargets.cmake`, so the path to the header file is as follows:
    ![image](https://github.com/user-attachments/assets/2fd3e6a6-46fb-4733-8713-cfb43e745be8)

    At this time, the following header files are not found in `$(_ZVcpkgCurrentInstalledDir)include`，which is defined in `vcpkg\scripts\buildsystems\msbuild\vcpkg.targets`:
    ```
    #pragma once

    #include <rpp/disposables.hpp>
    #include <rpp/fwd.hpp>
    #include <rpp/observables.hpp>
    #include <rpp/observers.hpp>
    #include <rpp/operators.hpp>
    #include <rpp/schedulers.hpp>
    #include <rpp/sources.hpp>
    #include <rpp/subjects.hpp>
    ```
    ```
    <ClCompile>
      <AdditionalIncludeDirectories>%(AdditionalIncludeDirectories);$(_ZVcpkgCurrentInstalledDir)include</AdditionalIncludeDirectories>
    </ClCompile>
    <ResourceCompile>
      <AdditionalIncludeDirectories>%(AdditionalIncludeDirectories);$(_ZVcpkgCurrentInstalledDir)include</AdditionalIncludeDirectories>
    </ResourceCompile>
    ```

    So the rpp path needs to be added to the `Additional Include Directories`:
    ![image](https://github.com/user-attachments/assets/f699ab6b-a623-4631-adfd-de6e0c960b53)

**Comment by idotta** [comment]
Hey @MonicaLiu0311! Thanks a lot for the workaround! This is the path that worked for me:
`$(SolutionDir)vcpkg_installed\$(Platform)-windows\$(Platform)-windows\include\rpp`
Do you think there's anything that can be done to use it automatically like other packages?

To keep as a future reference, I created this [working sample](https://github.com/idotta/rpp-msbuild).

**Comment by MonicaLiu0311** [comment]
> Do you think there's anything that can be done to use it automatically like other packages?

[ReactivePlusPlus](https://github.com/victimsnino/ReactivePlusPlus) is a CMake project, and the header files can be found using CMake, so this is not an error.

Instead of modifying the `Additional Include Directories`, you can also use [--overlay-ports](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/concepts/overlay-ports.md)(the advantage is that when you encounter other ports that you want to process separately, the approach is similar):

Modify the code as follows (generate patch), [v2.1.1/cmake/install-rules.cmake#L7-L27](https://github.com/victimsnino/ReactivePlusPlus/blob/v2.1.1/cmake/install-rules.cmake#L7-L27):
```
install(
    DIRECTORY
        src/rpp/rpp
       src/rppqt/rppqt
    DESTINATION
        "${CMAKE_INSTALL_INCLUDEDIR}"
    COMPONENT
        RPP_Development
)

install(
    TARGETS rpp
    EXPORT RPPTargets
    INCLUDES DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}"
)

install(
    TARGETS rppqt
    EXPORT RPPTargets
    INCLUDES DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}"
)
```

Apply the patch to `portfile.cmake`.

Create a new overlay-ports directory and put reactiveplusplus in it:
```
overlayPorts/
    reactiveplusplus/
        portfile.cmake（apply the newly generated patch）
        vcpkg.json
```

Use `--overlay-ports` to specify installation:
```
./vcpkg install reactiveplusplus --overlay-ports=overlayPortsPath
```

**Comment by idotta** [comment]
That's great, thanks! I'll keep it that way so I can fix any future problem.

As a side note, I still think it's an error, though. Since vcpkg has native support in MSBuild and Visual Studio, a simple install of a header-only library should work automatically.

But anyway, thanks a lot! Closing the issue.
