### ISSUE TITLE
import export

### ISSUE THREAD

**Issue by jean-christophe81** [microsoft/vcpkg#39958]
**Describe the bug**
My goal is to compile dependencies in a worflow and to reuse it in my project compilation workflows.
I have tried vcpkg export, but when I import it in a new runner context, it recompiles every dependencies. 
So I have decided to zip entire vcpkg directory and reuse it in next workflows.
Yesterday, it worked, but today not.

**Environment**
- OS: github Windows runner
- Compiler: MSVC/14.40.33807

**To Reproduce**
1. In a first workflow, inorder to compile dependencies, I do a cmake --preset=release with this preset in my project: 
`        {
            "name": "release",
            "generator": "Ninja",
            "binaryDir": "${sourceDir}/build_windows",
            "cacheVariables": {
                "CMAKE_BUILD_TYPE": "Release",
                "WITH_TESTING": "On",
                "CMAKE_TOOLCHAIN_FILE": "$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake",
                "VCPKG_OVERLAY_TRIPLETS": "custom-triplets",
                "VCPKG_TARGET_TRIPLET": "x64-windows"
            }
        },
`
2. I zip all vcpkg directory to reuse it in my project compile
3. In the compile workflow, I unzip vcpkg archive. I do a cmake --preset with this preset:
`        {
            "name": "release-ci",
            "generator": "Ninja",
            "binaryDir": "${sourceDir}/build_windows",
            "cacheVariables": {
                "CMAKE_BUILD_TYPE": "Release",
                "WITH_TESTING": "On",
                "CMAKE_TOOLCHAIN_FILE": "$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake",
                "VCPKG_OVERLAY_TRIPLETS": "custom-triplets",
                "VCPKG_TARGET_TRIPLET": "x64-windows",
                "VCPKG_INSTALL_OPTIONS": "--no-downloads"
            }
        }
`
4. despite the --no-downloads, vcpkg recompile somethings

**Expected behavior**
vcpkg don't recompile dependencies

**Additional context**

**Comment by jimwang118** [comment]
You can learn how [binarycaching](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/users/binarycaching.md) is used.

**Comment by jean-christophe81** [comment]
Thanks, I have also tried without success. So I have decided to backup generated vcpkg install directory in my project and to restore it in my second workflow. The I Compile without using vcpkg and it works fine.

**Comment by jean-christophe81** [comment]
I have found a workaround
