### ISSUE TITLE
[python3] Build failure on arm64-osx

### ISSUE THREAD

**Issue by aliddell** [microsoft/vcpkg#39950]
Package: python3:arm64-osx@3.11.8#2

**Host Environment**

- Host: arm64-osx
- Compiler: AppleClang 15.0.0.15000309
-    vcpkg-tool version: 2024-06-10-02590c430e4ed9215d27870138c2e579cc338772
    vcpkg-scripts version: b2fd29fec 2024-07-16 (7 hours ago)

**To Reproduce**

`vcpkg install `

**Failure logs**

```
CMake Warning at /Users/aliddell/.cache/vcpkg/registries/git-trees/24bb8d2b3db0a12a7ca7f04061f632f0e94abcc2/portfile.cmake:7 (message):
  python3 currently requires the following programs from the system package
  manager:

      autoconf automake autoconf-archive

  On Debian and Ubuntu derivatives:

      sudo apt-get install autoconf automake autoconf-archive

  On recent Red Hat and Fedora derivatives:

      sudo dnf install autoconf automake autoconf-archive

  On Arch Linux and derivatives:

      sudo pacman -S autoconf automake autoconf-archive

  On Alpine:

      apk add autoconf automake autoconf-archive

  On macOS:

      brew install autoconf automake autoconf-archive

Call Stack (most recent call first):
  scripts/ports.cmake:192 (include)


-- Using cached python-cpython-v3.11.8.tar.gz.
-- Cleaning sources at /Users/aliddell/repos/vcpkg/buildtrees/python3/src/v3.11.8-31d17ab840.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/aliddell/repos/vcpkg/downloads/python-cpython-v3.11.8.tar.gz
-- Applying patch 0001-only-build-required-projects.patch
-- Applying patch 0003-use-vcpkg-zlib.patch
-- Applying patch 0004-devendor-external-dependencies.patch
-- Applying patch 0005-dont-copy-vcruntime.patch
-- Applying patch 0008-python.pc.patch
-- Applying patch 0010-dont-skip-rpath.patch
-- Applying patch 0012-force-disable-modules.patch
-- Applying patch 0014-fix-get-python-inc-output.patch
-- Applying patch 0015-dont-use-WINDOWS-def.patch
-- Applying patch 0016-undup-ffi-symbols.patch
-- Applying patch 0018-fix-sysconfig-include.patch
-- Applying patch 0002-static-library.patch
-- Using source at /Users/aliddell/repos/vcpkg/buildtrees/python3/src/v3.11.8-31d17ab840.clean
-- Getting CMake variables for arm64-osx-dbg
-- Getting CMake variables for arm64-osx-rel
CMake Error at scripts/cmake/vcpkg_configure_make.cmake:721 (message):
  python3 requires autoconf from the system package manager (example: "sudo
  apt-get install autoconf")
Call Stack (most recent call first):
  /Users/aliddell/.cache/vcpkg/registries/git-trees/24bb8d2b3db0a12a7ca7f04061f632f0e94abcc2/portfile.cmake:274 (vcpkg_configure_make)
  scripts/ports.cmake:192 (include)



```

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "dependencies": [
    {
      "name": "blosc",
      "version>=": "1.21.5"
    },
    {
      "name": "nlohmann-json",
      "version>=": "3.11.3"
    },
    {
      "name": "pybind11"
    },
    {
      "name": "python3"
    }
  ]
}

```
</details>

**Comment by pzemp1** [comment]
I get this same exact issue, except I'm trying to install the Boost library. Using C++ in a MacOs environment is proving to be a pain.

**Comment by SpiritDogstar** [comment]
Still happening

**Comment by SpiritDogstar** [comment]
@aliddell what did you do to fix this? Is there a patch that's needed or a workaround?

**Comment by dg0yt** [comment]
@SpiritDogstar This issue had a clear error message and instruction:
~~~
CMake Error at scripts/cmake/vcpkg_configure_make.cmake:721 (message):
  python3 requires autoconf from the system package manager (example: "sudo
  apt-get install autoconf")
~~~

**Comment by SpiritDogstar** [comment]
This issue is still happening on OSX.

eg:
https://github.com/microsoft/vcpkg/issues/41055

These are already brew installs:
python3 currently requires the following programs from the system package
  manager:

      autoconf automake autoconf-archive

  On Debian and Ubuntu derivatives:

      sudo apt-get install autoconf automake autoconf-archive

  On recent Red Hat and Fedora derivatives:

      sudo dnf install autoconf automake autoconf-archive

  On Arch Linux and derivatives:

      sudo pacman -S autoconf automake autoconf-archive

  On Alpine:

      apk add autoconf automake autoconf-archive

  On macOS:

      **brew install autoconf automake autoconf-archive**

Call Stack (most recent call first):
  scripts/ports.cmake:192 (include)

**Comment by dg0yt** [comment]
> eg:
> [#41055](https://github.com/microsoft/vcpkg/issues/41055)

No, this is a different problem.

**Comment by SpiritDogstar** [comment]
Should I open a new issue for this not working on OSX?

**Comment by SpiritDogstar** [comment]
Hmm.. well, if anyone else comes across this and has a fix for the OSX version, please comment! It's still broken for me.

**Comment by SpiritDogstar** [comment]
This might not solve anything directly, but provides a work around. I noticed that pybind11 started requiring python3 as a dependency a few months back:
https://github.com/microsoft/vcpkg/commit/e338d66dcdf3fb22b1fa2563b8318446c1e1f9c6

So, using pybind11 at version 2.12.0 doesn't pull it in to fail to build. It doesn't resolve why python3 won't build on arm64-osx, but it's a work around for now for those using pybind11 in vcpkg.

**Comment by yulu0131** [comment]
got same problem here, and I think the bug occurs recently. I reinstalled the vcpkg things early this morning, and now all the related-python stuff in vcpkg cannot work properly, especially the failure for building pybind11 and boost. However, I am pretty sure that before this reinstallation, everything works well on my mac.

run 'brew install boost' and manually install pybind11 from their github page can solve my problem temporarily.

error: building python3:arm64-osx failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle python3:arm64-osx: 4.9 s

**Comment by dg0yt** [comment]
@yulu0131 Open a new issue with all relevant information. 

READERS, this issue was for missing tools from the host. And the output clearly show how to install the missing tools. Read it, do it.
