### ISSUE TITLE
[paho-mqttpp3] paho-mqtt with feature ssl

### ISSUE THREAD

**Issue by Manfred-O** [microsoft/vcpkg#39960]
### Is your feature request related to a problem? Please describe.

I wanted to use the paho c++ sync client together with ssl support, but it tells me "Error: MQTT error [-13]: SSL is not supported [0]" when running the programm. Now i'm getting a little bit confused because while downloading and compiling with vcpkg i see that there are dependencies to openssl. So can't figure out what went wrong. I went thru the "vcpkg\ports\paho-mqttpp3\profile.cmake" paho port and i'm recognizing that it is compiled against. 
set(PAHO_C_LIBNAME paho-mqtt3as)
which is the async secure one. Does that get me the error.

### Proposed solution

How can i get that to work.

### Additional context

I posted also to the github paho repository. 
"https://github.com/eclipse/paho.mqtt.cpp/issues/506"

**Comment by WangWeiLin-MV** [comment]
Could you help provide a minimal CMake example?

**Comment by Manfred-O** [comment]
I'm not an expert in cmake. I tried to build paho statically and with ssl support by downloading those two repositories and build them but no luck in my project. I try to use the vcpkg for paho as an dll now. This do work, but i have some other libs like json c++ build as static. How can in setup visualstudio to use both
static and shared vcpkg.

**Comment by dg0yt** [comment]
I don't know enough about the specific problem, and I do not have MSVS. But port paho-mqttpp3 doesn't look healthy...
