### ISSUE TITLE
Contribute new package: Native Windows C++ library for EMC ECS S3 REST support

### ISSUE THREAD

**Issue by bobk2824** [Microsoft/vcpkg#3996]
I have a new Windows C++ library:
https://github.com/EMCECS/ecs-object-client-windows-cpp
It is ready to be published in vcpkg.
I have tested x64, x86, dynamic and static builds.
What info do you need?

**Comment by chausner** [comment]
Hi bobk2824,

I am not 100% sure but I think only CMake-based builds are supported at the moment. This means you will have to write a CMakeLists.txt file containing all your source files, linker dependencies and build flags. Then, clone the vcpkg repository, add your package and create a pull request. See also https://github.com/Microsoft/vcpkg/blob/master/docs/examples/packaging-zlib.md for a short tutorial on how to contribute new packages.

**Comment by ras0219-msft** [comment]
@bobk2824 Thanks for the interest!

We definitely support MSBuild[1], however as @chausner suggests CMake makes it _easier_ to express all the capabilities of Vcpkg.

To add a library to vcpkg, all you need to do is submit a PR adding a folder into `ports\` that tells us how to build it! I also recommend the tutorial example that @chausner mentioned to get started with that.

[1] https://github.com/Microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_build_msbuild.md

**Comment by LarryIII** [comment]
It was fixed in https://github.com/Microsoft/vcpkg/commit/13ec697c39ff6441393003f38635898b04d6d931#diff-df9c2d78ca7daa27b0fee9339fb95048
