### ISSUE TITLE
Protobuf needs to be updated from 3.6.0.1 to 3.6.1

### ISSUE THREAD

**Issue by Kwizatz** [Microsoft/vcpkg#3997]
This is a heads up regarding this protobuff issue:

global std::once_flag variables don't work with Visual Studio
https://github.com/google/protobuf/issues/4773

There is a workaround in 3.6.1 which came out yesterday, but for now, any programs linked against vcpkg's protobuf crash when calling google::protobuf::ShutdownProtobufLibrary() as I descrived on this other issue:

Calling google::protobuf::ShutdownProtobufLibrary() against a DLL build throws an Access violation reading location 0xFFFFFFFFFFFFFFFF exception

https://github.com/google/protobuf/issues/4950

**Comment by TheAifam5** [comment]
Have fun :)
https://github.com/Microsoft/vcpkg/pull/4000

**Comment by TheAifam5** [comment]
@kiwixz its already merged by other pull request: https://github.com/Microsoft/vcpkg/pull/3995

**Comment by ras0219-msft** [comment]
Fixed by #3995.
