### ISSUE TITLE
[nifticlib:x64-windows] Declared struct member variable types are inconsistent with vcpkg built lib

### ISSUE THREAD

**Issue by Cercospora** [microsoft/vcpkg#39986]
**Describe the bug**
I apologize if this is the wrong place to report this bug, but I only experienced this issue using nifticlib built by vcpkg. If I build nifticlib myself, everything works fine.

The `struct nifti_image` is declared at https://github.com/NIFTI-Imaging/nifti_clib/blob/master/niftilib/nifti1_io.h on line 88
The declaration of some variables in the struct has the wrong type. Declared type => actual type in memory: `int => long long`, `float => double`
This leads to misinterpretation of the variables in the host program code and library functions.

![image](https://github.com/user-attachments/assets/b4d535e5-f649-41f8-9b45-edcae68160e4)
Notice how the `nim->n*` variables in debugger does not match the output of `nifti_image_infodump`.

![image](https://github.com/user-attachments/assets/9bf370f4-7e6e-4326-9f72-d9d7de183cb5)
When I write to the variables, `nifti_image_infodump` prints garbled data.

![image](https://github.com/user-attachments/assets/1f49714d-3912-4f86-ab8f-52a03e9db013)
After changing the types to `long long` and `double` in `nifti1_io.h`, the values in debugger and `nifti_image_infodump` becomes consistent.

![image](https://github.com/user-attachments/assets/236baf4b-95d8-40c3-a638-6d3a5c9b8242)
Writing to the variables also yields the expected results.

**Environment**
- OS: Windows 10
- Compiler: MSVC 143 (Visual Studio 2022)

**To Reproduce**
1. ./vcpkg install nifticlib:x64-windows
2. Run the following code
```
#include <nifti1_io.h>

void writeNifti(const char* filename, float* pBuffer, size_t width, size_t height, size_t frames) {
    nifti_image* nim = nifti_simple_init_nim();
    nifti_set_filenames(nim, filename, 0, 0);
    nifti_image_infodump(nim);

    nim->nifti_type = NIFTI_FTYPE_NIFTI1_1;
    nim->ndim = 3;
    nim->nx = width;
    nim->ny = height;
    nim->nz = frames;
    nim->dx = 1;
    nim->dy = 1;
    nim->dz = 1;
    nim->nvox = width * height * frames;
    nim->nbyper = sizeof(float);
    nim->datatype = NIFTI_TYPE_FLOAT32;
    nim->data = (void*)pBuffer;

    nifti_image_infodump(nim);
    nifti_image_write(nim);
    nifti_image_free(nim);
}

int main() {
    float* buffer = new float[10 * 10 * 10];
    writeNifti("test", buffer, 10, 10, 10);
    delete[] buffer;
    return 0;
}
```
3. Console prints: `** ERROR: nifti_image_write_engine: no image data`

**Comment by jimwang118** [comment]
I tried your solution locally, changing int to long long and float to double, but it still outputs the same error message. I checked the error message, which indicates that the correct image file was not added.
![image](https://github.com/user-attachments/assets/bd5f2740-707d-42a9-b8cf-75dafc352193)

**Comment by Cercospora** [comment]
> I tried your solution locally, changing int to long long and float to double, but it still outputs the same error message. I checked the error message, which indicates that the correct image file was not added. ![image](https://private-user-images.githubusercontent.com/122244446/350859462-bd5f2740-707d-42a9-b8cf-75dafc352193.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzkxNjEsIm5iZiI6MTcyMTYzODg2MSwicGF0aCI6Ii8xMjIyNDQ0NDYvMzUwODU5NDYyLWJkNWYyNzQwLTcwN2QtNDJhOS1iOGNmLTc1ZGFmYzM1MjE5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQwOTAxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzNkZTkwYzk3ODg1NWQwYTEyYTMzMzI1ZDRmODE5ODBmNWU5NjBhODY2MGRiMTI0ZDZhMTFhOWZjYmVhYWJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m-UMEYiVbW4qyW5oZpBPPVdxyVtzYEUFjGflB5QnJkU)

I was never able to get rid of the error myself. I think only some variables are misdeclared so a simple find and replace won't solve the issue. I was only able to check variables that is printed by `nifti_image_infodump`.

The error is due to `nim->data` not being set, which we can't do without the correct struct declaration.

Changing the header doesn't fix the root of the issue. Why is the struct used by the library different from the header?

**Comment by dg0yt** [comment]
Does the program actually link/load the vcpg build of the library?

There are no special tricks in the nifticlib vcpkg port. There is no reason to assume the compiler could use a different memory layout than what is declared for the struct.

**Comment by Cercospora** [comment]
> Does the program actually link/load the vcpg build of the library?
> 
> There are no special tricks in the nifticlib vcpkg port. There is no reason to assume the compiler could use a different memory layout than what is declared for the struct.

Yes, it's linking to vcpkg's version. Here's my linker options from Visual Studio with nifti libs highlighted.
<img width="590" alt="image" src="https://github.com/user-attachments/assets/729c71a0-b459-470f-b1f3-64267ba43add">

**Comment by Cercospora** [comment]
I have figured it out. It's not a vcpkg issue (my bad). Apparently `nifti2_io.h` also declares the same `nifti_image` struct and functions. Since I linked to both `nifti2.lib` and `niftiio.lib`, my nifti1 functions are linked to the nifti2 versions. I fixed the issue by removing `NIFTI::nifti2` from `target_link_libraries`.
