### ISSUE TITLE
[qtbase] QDnsLookup does not work on !Windows in 6.7.2#0

### ISSUE THREAD

**Issue by sgoth** [microsoft/vcpkg#39997]
**Describe the bug**
Building a basic Qt application with the default triplet on x64 linux (static) results in a misscompiled QDnsLookup

https://codebrowser.dev/qt6/qtbase/src/network/kernel/qdnslookup_unix.cpp.html lists only libresolv - and is available on the system.

**Environment**
- OS: Linux (Arch, but probably any other)
- Compiler: gcc-14.1.1

**To Reproduce**
1. clone repro project https://github.com/sgoth/vcpkg-qtbase-dnslookup
2. build 
   `cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake -B build`
3. run ./build/dnsc

Should print a QHostAddress of an A record of www.github.com
Actually prints `DNS lookup failed:  QDnsLookup::ResolverError`

Running in gdb and breaking in `QDnsLookupRunnable::query` shows that src/network/kernel/qdnslookup_dummy.cpp is used.

**Expected behavior**

`QDnsLookupRunnable::query` should be from src/network/kernel/qdnslookup_unix.cpp

**Additional context**
Building the sample project against a system wide Qt works.
Explicitly linking to libresolv doesn't change anything (even done in the repro).

**Comment by sgoth** [comment]
Please note the reduced feature set in the vcpkg.json

**Comment by Neumann-A** [comment]
https://github.com/qt/qtbase/blob/dev/src/network/CMakeLists.txt#L249

`Network CONDITION QT_FEATURE_dnslookup AND NOT QT_FEATURE_libresolv AND NOT WIN32`


WrapResolv is disabled in the portfile. Feel free to make it a feature to control the dependency on libresolv.

**Comment by sgoth** [comment]
Thanks, will give it a shot in the next days!

**Comment by sgoth** [comment]
I guess it doesn't make sense to have a feature "libresolv" on the port level as that would be linux/unix only. So the more sensible approach would be to use "dnslookup" but that is currently default on and probably should stay that way.

Having the dummy code compiled in doesn't help at all and even hides the fact that QDnsLookup will not work instead of raising a compilation error (at least i assume that would happen with dnslookup being disabled).

That would make libresolv being a default dependency on linux. As that is part of glibc i'd guess that is ok - and can be explicitly disabled.

Does that make sense?
