### ISSUE TITLE
Provide examples on how to convert from CoApp

### ISSUE THREAD

**Issue by codekaizen** [Microsoft/vcpkg#4]
[CoApp](https://github.com/coapp/) is the existing native packaging tool from Microsoft which uses nuget. If I want to convert from CoApp to vcpkg, how will I go about doing it?

**Comment by ras0219-msft** [comment]
It would be great to have examples on both sides, but to prioritize: are you currently packaging your library using CoApp and you'd like to write a vcpkg port instead?

**Comment by ras0219-msft** [comment]
Closing for lack of interest. If this is relevant to you, please post here and we can reopen the issue.
