### ISSUE TITLE
[boost-stacktrace] Request for a new feature `backtrace` to build with `libbacktrace`

### ISSUE THREAD

**Issue by kyechou** [microsoft/vcpkg#40009]
### Is your feature request related to a problem? Please describe.

`boost-stacktrace` always builds with backtrace disabled, which causes issues like #39625.
https://github.com/microsoft/vcpkg/blob/821100d967e1737d96414a308e3f7cbe0d1abf18/ports/boost-stacktrace/features.cmake#L26

### Proposed solution

- As suggested by [FrankXie05's comment](https://github.com/microsoft/vcpkg/issues/39625#issuecomment-2202104175), `boost-stacktrace` should build with backtrace support if `libbacktrace` is found, either from vcpkg or system paths.
- Also, it'd be helpful to add a new feature `backtrace` to explicitly enable backtrace support and the dependency on `libbacktrace`.

### Describe alternatives you've considered

An alternative would be to use the addr2line backend, but it has its own problem supporting position-independent code (https://github.com/boostorg/stacktrace/issues/97#issuecomment-1575611889).

### Additional context

From CONTRIBUTING.md:
> [...], we highly encourage opening an issue to discuss whether the PR you're thinking about making will be acceptable. This is doubly true for features and new packages.

I'm considering making a PR to add a new feature `backtrace` for port `boost-stacktrace` in the next month or two, but I'm not sure if this is something you want or what the best practice is.

**Comment by jimwang118** [comment]
You are welcome to submit PRs to add features at any time.
