### ISSUE TITLE
[gmp] build failure

### ISSUE THREAD

**Issue by iboisvert** [microsoft/vcpkg#40016]
### Operating system

Linux 

### Compiler

gcc

### Steps to reproduce the behavior

```Shell
docker run -it --rm mcr.microsoft.com/devcontainers/cpp:ubuntu
mkdir ws && cd ws
apt-get update && apt-get install -y autoconf autoconf-archive
vcpkg new --application
vcpkg add gmp
vcpkg install --triplet=x64-linux gmp
```
```


### Failure logs

Text from console:

```
root ➜ /ws $ vcpkg install --triplet=x64-linux    
Fetching registry information from https://github.com/microsoft/vcpkg (HEAD)...
A suitable version of cmake was not found (required v3.29.2) Downloading portable cmake 3.29.2...
Downloading cmake...
https://github.com/Kitware/CMake/releases/download/v3.29.2/cmake-3.29.2-linux-x86_64.tar.gz->/usr/local/vcpkg-downloads/cmake-3.29.2-linux-x86_64.tar.gz
Extracting cmake...
Detecting compiler hash for triplet x64-linux...
Compiler found: /usr/bin/c++
The following packages will be built and installed:
    gmp:x64-linux@6.3.0 -- /root/.cache/vcpkg/registries/git-trees/c28d96e8dd3ed941ba550f1e9d9f7bf1f2a83ac8
  * vcpkg-cmake:x64-linux@2024-04-23 -- /root/.cache/vcpkg/registries/git-trees/e74aa1e8f93278a8e71372f1fa08c3df420eb840
  * vcpkg-cmake-get-vars:x64-linux@2023-12-31 -- /root/.cache/vcpkg/registries/git-trees/725c841810ceb8de33da68ea879eb8f0b4d6c94c
Additional packages (*) will be modified to complete this operation.
Restored 0 package(s) from /root/.cache/vcpkg/archives in 12.6 us. Use --debug to see more details.
Installing 1/3 vcpkg-cmake:x64-linux@2024-04-23...
Building vcpkg-cmake:x64-linux@2024-04-23...
/root/.cache/vcpkg/registries/git-trees/e74aa1e8f93278a8e71372f1fa08c3df420eb840: info: installing overlay port from here
-- Installing: /usr/local/vcpkg/packages/vcpkg-cmake_x64-linux/share/vcpkg-cmake/vcpkg_cmake_configure.cmake
-- Installing: /usr/local/vcpkg/packages/vcpkg-cmake_x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake
-- Installing: /usr/local/vcpkg/packages/vcpkg-cmake_x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake
-- Installing: /usr/local/vcpkg/packages/vcpkg-cmake_x64-linux/share/vcpkg-cmake/vcpkg-port-config.cmake
-- Installing: /usr/local/vcpkg/packages/vcpkg-cmake_x64-linux/share/vcpkg-cmake/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 10.8 ms.
Elapsed time to handle vcpkg-cmake:x64-linux: 58.4 ms
vcpkg-cmake:x64-linux package ABI: e7daa025661d2e45e22769d994053715c662f4c9003a34fa0493a9d8bfe84cb7
Installing 2/3 vcpkg-cmake-get-vars:x64-linux@2023-12-31...
Building vcpkg-cmake-get-vars:x64-linux@2023-12-31...
/root/.cache/vcpkg/registries/git-trees/725c841810ceb8de33da68ea879eb8f0b4d6c94c: info: installing overlay port from here
-- Installing: /usr/local/vcpkg/packages/vcpkg-cmake-get-vars_x64-linux/share/vcpkg-cmake-get-vars/vcpkg_cmake_get_vars.cmake
-- Installing: /usr/local/vcpkg/packages/vcpkg-cmake-get-vars_x64-linux/share/vcpkg-cmake-get-vars/cmake_get_vars
-- Installing: /usr/local/vcpkg/packages/vcpkg-cmake-get-vars_x64-linux/share/vcpkg-cmake-get-vars/cmake_get_vars/CMakeLists.txt
-- Installing: /usr/local/vcpkg/packages/vcpkg-cmake-get-vars_x64-linux/share/vcpkg-cmake-get-vars/vcpkg-port-config.cmake
-- Installing: /usr/local/vcpkg/packages/vcpkg-cmake-get-vars_x64-linux/share/vcpkg-cmake-get-vars/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 3.47 ms.
Elapsed time to handle vcpkg-cmake-get-vars:x64-linux: 28.4 ms
vcpkg-cmake-get-vars:x64-linux package ABI: 8c036d8e2cfca0a8d3968c192469ca365b39c4b923036ed2b732f34105a833cd
Installing 3/3 gmp:x64-linux@6.3.0...
Building gmp:x64-linux@6.3.0...
/root/.cache/vcpkg/registries/git-trees/c28d96e8dd3ed941ba550f1e9d9f7bf1f2a83ac8: info: installing overlay port from here
-- Downloading https://ftpmirror.gnu.org/gmp/gmp-6.3.0.tar.xz;https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz;https://gmplib.org/download/gmp/gmp-6.3.0.tar.xz -> gmp-6.3.0.tar.xz...
-- Extracting source /usr/local/vcpkg-downloads/gmp-6.3.0.tar.xz
-- Applying patch asmflags.patch
-- Applying patch cross-tools.patch
-- Applying patch subdirs.patch
-- Applying patch msvc_symbol.patch
-- Applying patch arm64-coff.patch
-- Using source at /usr/local/vcpkg/buildtrees/gmp/src/v6.3.0-036e54f1a3.clean
-- Getting CMake variables for x64-linux
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Generating configure for x64-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: /usr/bin/autoreconf -vfi
    Working Directory: /usr/local/vcpkg/buildtrees/gmp/src/v6.3.0-036e54f1a3.clean/
    Error code: 1
    See logs for more information:
      /usr/local/vcpkg/buildtrees/gmp/autoconf-x64-linux-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:731 (vcpkg_execute_required_process)
  /root/.cache/vcpkg/registries/git-trees/c28d96e8dd3ed941ba550f1e9d9f7bf1f2a83ac8/portfile.cmake:82 (vcpkg_configure_make)
  scripts/ports.cmake:192 (include)
```

### Additional context

```
root ➜ /ws $ cat /usr/local/vcpkg/buildtrees/gmp/autoconf-x64-linux-err.log
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
configure.ac:3856: warning: AC_LIBTOOL_PROG_COMPILER_PIC is m4_require'd but not m4_defun'd
acinclude.m4:2363: GMP_ASM_X86_GOT_UNDERSCORE is expanded from...
configure.ac:3856: the top level
configure.ac:3859: warning: AC_ENABLE_SHARED is m4_require'd but not m4_defun'd
acinclude.m4:2717: GMP_ASM_X86_MCOUNT is expanded from...
configure.ac:3859: the top level
configure.ac:3859: warning: AC_PROG_LIBTOOL is m4_require'd but not m4_defun'd
acinclude.m4:2717: GMP_ASM_X86_MCOUNT is expanded from...
configure.ac:3859: the top level
autoreconf: configure.ac: tracing
configure.ac:3856: warning: AC_LIBTOOL_PROG_COMPILER_PIC is m4_require'd but not m4_defun'd
acinclude.m4:2363: GMP_ASM_X86_GOT_UNDERSCORE is expanded from...
configure.ac:3856: the top level
configure.ac:3859: warning: AC_ENABLE_SHARED is m4_require'd but not m4_defun'd
acinclude.m4:2717: GMP_ASM_X86_MCOUNT is expanded from...
configure.ac:3859: the top level
configure.ac:3859: warning: AC_PROG_LIBTOOL is m4_require'd but not m4_defun'd
acinclude.m4:2717: GMP_ASM_X86_MCOUNT is expanded from...
configure.ac:3859: the top level
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:3856: warning: AC_LIBTOOL_PROG_COMPILER_PIC is m4_require'd but not m4_defun'd
acinclude.m4:2363: GMP_ASM_X86_GOT_UNDERSCORE is expanded from...
configure.ac:3856: the top level
configure.ac:3859: warning: AC_ENABLE_SHARED is m4_require'd but not m4_defun'd
acinclude.m4:2717: GMP_ASM_X86_MCOUNT is expanded from...
configure.ac:3859: the top level
configure.ac:3859: warning: AC_PROG_LIBTOOL is m4_require'd but not m4_defun'd
acinclude.m4:2717: GMP_ASM_X86_MCOUNT is expanded from...
configure.ac:3859: the top level
configure.ac:2726: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:2814: error: possibly undefined macro: AC_PROG_LIBTOOL
configure.ac:2937: error: possibly undefined macro: AC_CHECK_LIBM
configure:11298: error: possibly undefined macro: AC_PROG_NM
configure:15278: error: possibly undefined macro: AC_LIBTOOL_PROG_COMPILER_PIC
configure:15373: error: possibly undefined macro: AC_ENABLE_SHARED
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

**Comment by iboisvert** [comment]
Sorry, I should be clear: this step is run on host:

```
docker run -it --rm mcr.microsoft.com/devcontainers/cpp:ubuntu
```

These steps are run in the container:
```
mkdir ws && cd ws
apt-get update && apt-get install -y autoconf autoconf-archive
vcpkg new --application
vcpkg add gmp
vcpkg install --triplet=x64-linux gmp
```

**Comment by FrankXie05** [comment]
@iboisvert Thanks for posting this issue. Please run `sudo apt-get install autoconf automake libtool` and reinstall `gmp` again.

**Comment by iboisvert** [comment]
That got it, thanks @FrankXie05 !
