### ISSUE TITLE
[opencv3]Cannot link to debug version of dll in manifest mode

### ISSUE THREAD

**Issue by QiuYilin** [microsoft/vcpkg#40017]
**Describe the bug**
I want to link to opencv3 in manifest mode.
vcpkg.json
```
{
    "dependencies": [
      {
        "name": "opencv3"
      }
    ],
    "builtin-baseline": "576379156e82da642f8d1834220876759f13534d"
}
```
CMakeList.txt
```
set(OpenCV_DIR "${VCPKG_INSTALLED_DIR}/x64-windows/share/opencv3")
find_package(OpenCV 3 REQUIRED)
include_directories(${OpenCV_INCLUDE_DIRS})

add_executable(${PROJECT_NAME}_test main.cpp)
target_link_libraries(${PROJECT_NAME}_test ${OpenCV_LIBS})
```
building can pass in release mode but fail in debug mode

`error LNK2019: unresolved external symbol "public: void __cdecl cv::Mat::copyTo(class cv::_OutputArray const &,class cv::_InputArray const &)const " (?copyTo@Mat@cv@@QEBAXAEBV_OutputArray@2@AEBV_InputArray@2@@Z) `

**Environment**
- OS: Windows
- Compiler: MSVC

**Comment by jimwang118** [comment]
Sorry, I cannot reproduce this issue locally.

**Comment by QiuYilin** [comment]
https://github.com/QiuYilin/shape_based_matching/tree/feature_MSVC_build
This is the project where I have problems. I cannot link to the dll in debug mode. Have I overlooked something?

**Comment by jimwang118** [comment]
> https://github.com/QiuYilin/shape_based_matching/tree/feature_MSVC_build This is the project where I have problems. I cannot link to the dll in debug mode. Have I overlooked something?

There is a problem with the compilation options you set. I can compile successfully after removing all the compilation options.

**Comment by QiuYilin** [comment]
Yes, Any of -O0 -g2 -ggdb will cause compilation failure. Is this normal?

**Comment by jimwang118** [comment]
I use the msvc compiler in Windows. These compilation options only support gcc or clang compilers, so they will fail in msvc. You can find similar compilation options in msvc.

**Comment by QiuYilin** [comment]
Thank you for your support@jimwang118
