### ISSUE TITLE
[vcpkg] Why linux?

### ISSUE THREAD

**Issue by TheAifam5** [Microsoft/vcpkg#4003]
Hey,
I understand that vcpkg is needed on Windows, maaaaybe also on Mac but who using it on linux where the package manager has everything?
Do we really need it on Linux or/and Mac?

Regards,
TheAifam5

**Comment by MikeGitb** [comment]
Yes I do for multiple reasons:

- I can use the same package manager with the same library versions on all platforms. This is by far the most important point.
- I can easily add my own libraries
- Installing a new library doesn't affect the rest of my system which also means I don't need sudo privileges to do it.

vcpkg running on Linux of course doesn't mean each individual library has to be compilable on Linux too.
