### ISSUE TITLE
[opencv4] Build error on x64-windows

### ISSUE THREAD

**Issue by freespiritss** [microsoft/vcpkg#40057]
Copy issue body from C:/BEA/vcpkg/installed/vcpkg/issue_body.md

CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/BEA/vcpkg/downloads/tools/cmake-3.29.2-windows/cmake-3.29.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j23
    Working Directory: C:/BEA/vcpkg/buildtrees/opencv4/x64-windows-dbg
    See logs for more information:
      C:\BEA\vcpkg\buildtrees\opencv4\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/opencv4/portfile.cmake:508 (vcpkg_cmake_install)
  scripts/ports.cmake:192 (include)

error: building opencv4:x64-windows failed with: BUILD_FAILEDSee https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.

[install-x64-windows-dbg-out.log](https://github.com/user-attachments/files/16354032/install-x64-windows-dbg-out.log)

**Comment by MonicaLiu0311** [comment]
Sorry I didn't repro your issue. Please check your vcpkg version.
```
PS G:\vcpkg> ./vcpkg version
vcpkg package management program version 2024-07-10-d2dfc73769081bdd9b782d08d27794780b7a99b9

See LICENSE.txt for license information.
```
```
PS G:\vcpkg> ./vcpkg install opencv4
Computing installation plan...
The following packages are already installed:
    opencv4[core,webp,tiff,quirc,png,jpeg,dnn,default-features]:x64-windows@4.8.0#21
opencv4:x64-windows is already installed
Total install time: 282 us
If you do not install the meta-port *opencv*, the package opencv4 is compatible with CMake
if you set the OpenCV_DIR *before* the find_package call

    set(OpenCV_DIR "${VCPKG_INSTALLED_DIR}/x64-windows/share/opencv4")
    find_package(OpenCV REQUIRED)
```

**Comment by freespiritss** [comment]
PS C:\BEA\vcpkg> .\vcpkg version
vcpkg package management program version 2024-07-10-d2dfc73769081bdd9b782d08d27794780b7a99b9

**Comment by greenozon** [comment]
@freespiritss  looks like smth wrong is the protoc compiler...
no any clear errors though... sorry

PS I can't reproduce this issue locally
