### ISSUE TITLE
SDL2_ttf Targets not yet defined: ZLIB::zlibstatic, Fedora linux

### ISSUE THREAD

**Issue by chriztheanvill** [microsoft/vcpkg#40078]
**Describe the bug**
Setup SDL2_ttf with CMake in Fedora linux, cant compile, but with openSUSE Tumbleweed it works.

**Environment**
- OS: Fedora 40, KDE, 
- Compiler: 
clang 18.1.6
c++ 14.1.1
cmake 3.28.2

**To Reproduce**
1. git clone https://github.com/microsoft/vcpkg.git && cd vcpkg
2. ./bootstrap-vcpkg.sh
3. Open the folder project with CLion
Even running "Reload CMake Project"

Or

cmake ../.. -G "Ninja" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_IGNORE_PREFIX_PATH=/usr/lib64 -DVCPKG_TARGET_TRIPLET=x64-linux

I tried with out prefix_path and target_triplet

**Expected behavior**
Compile without error

**Failure logs**
```sh

-- Running vcpkg install - done
-- Found ZLIB: optimized;/home/cris/Workspace/C++/Clion/Game_01/cmake-build-debug/vcpkg_installed/x64-linux/lib/libz.a;debug;/home/cris/Workspace/C++/Clion/Game_01/cmake-build-debug/vcpkg_installed/x64-linux/debug/lib/libz.a (found version "1.3.1")
-- Found PNG: optimized;/home/cris/Workspace/C++/Clion/Game_01/cmake-build-debug/vcpkg_installed/x64-linux/lib/libpng16.a;debug;/home/cris/Workspace/C++/Clion/Game_01/cmake-build-debug/vcpkg_installed/x64-linux/debug/lib/libpng16d.a (found version "1.6.43")
-- Found nlohmann_json: /home/cris/Workspace/C++/Clion/Game_01/cmake-build-debug/vcpkg_installed/x64-linux/share/nlohmann_json/nlohmann_jsonConfig.cmake (found version "3.11.3")
-- Found SQLite3: /home/cris/Workspace/C++/Clion/Game_01/cmake-build-debug/vcpkg_installed/x64-linux/include (found version "3.46.0")
-- Found JPEG: optimized;/home/cris/Workspace/C++/Clion/Game_01/cmake-build-debug/vcpkg_installed/x64-linux/lib/libjpeg.a;debug;/home/cris/Workspace/C++/Clion/Game_01/cmake-build-debug/vcpkg_installed/x64-linux/debug/lib/libjpeg.a (found version "62")
CMake Error at /usr/lib64/cmake/ZLIB/ZLIB.cmake:42 (message):
  Some (but not all) targets in this export set were already defined.

  Targets Defined: ZLIB::ZLIB

  Targets not yet defined: ZLIB::zlibstatic

Call Stack (most recent call first):
  /usr/lib64/cmake/ZLIB/zlib-config.cmake:44 (include)
  cmake-build-debug/vcpkg_installed/x64-linux/share/zlib/vcpkg-cmake-wrapper.cmake:12 (_find_package)
  /home/cris/Documents/My_Libs/vcpkg/scripts/buildsystems/vcpkg.cmake:811 (include)
  cmake-build-debug/vcpkg_installed/x64-linux/share/freetype/vcpkg-cmake-wrapper.cmake:40 (find_package)
  /home/cris/Documents/My_Libs/vcpkg/scripts/buildsystems/vcpkg.cmake:811 (include)
  /home/cris/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.29/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
  cmake-build-debug/vcpkg_installed/x64-linux/share/SDL2_ttf/SDL2_ttfConfig.cmake:42 (find_dependency)
  /home/cris/Documents/My_Libs/vcpkg/scripts/buildsystems/vcpkg.cmake:857 (_find_package)
  My_Cmake/Vcpkg_Find.cmake:50 (find_package)
  CMakeLists.txt:105 (include)


-- Configuring incomplete, errors occurred!

Cannot get compiler information:
	Cannot start a process, the working directory '/home/cris/Workspace/C++/Clion/Game_01/cmake-build-debug/Source/Main' does not exist

[Failed to reload]
```

**Additional context**
In the OS openSUSE Tumbleweed this doesn't happen.
Also in fedora I have in /usr/lib64/cmake/ ZLIB and zlib-ng

**Comment by dg0yt** [comment]
Interesting:

> ```shell
> Call Stack (most recent call first):
>   /usr/lib64/cmake/ZLIB/zlib-config.cmake:44 (include)
>   cmake-build-debug/vcpkg_installed/x64-linux/share/zlib/vcpkg-cmake-wrapper.cmake:12 (_find_package)
>   /home/cris/Documents/My_Libs/vcpkg/scripts/buildsystems/vcpkg.cmake:811 (include)
>   cmake-build-debug/vcpkg_installed/x64-linux/share/freetype/vcpkg-cmake-wrapper.cmake:40 (find_package)
> ```

`freetype/vcpkg-cmake-wrapper.cmake:40` has `find_package(ZLIB)`.
Normal search order would use CMake's `FindZLIB.cmake`. But here we get `/usr/lib64/cmake/ZLIB/zlib-config.cmake`. Do you call CMake with  `CMAKE_FIND_PACKAGE_PREFER_CONFIG`?

**Comment by chriztheanvill** [comment]
> Interesting:
> 
> > ```shell
> > Call Stack (most recent call first):
> >   /usr/lib64/cmake/ZLIB/zlib-config.cmake:44 (include)
> >   cmake-build-debug/vcpkg_installed/x64-linux/share/zlib/vcpkg-cmake-wrapper.cmake:12 (_find_package)
> >   /home/cris/Documents/My_Libs/vcpkg/scripts/buildsystems/vcpkg.cmake:811 (include)
> >   cmake-build-debug/vcpkg_installed/x64-linux/share/freetype/vcpkg-cmake-wrapper.cmake:40 (find_package)
> > ```
> 
> `freetype/vcpkg-cmake-wrapper.cmake:40` has `find_package(ZLIB)`. Normal search order would use CMake's `FindZLIB.cmake`. But here we get `/usr/lib64/cmake/ZLIB/zlib-config.cmake`. Do you call CMake with `CMAKE_FIND_PACKAGE_PREFER_CONFIG`?

Mmm... I don't know, how do I check that?

**Comment by chriztheanvill** [comment]
> CMAKE_FIND_PACKAGE_PREFER_CONFIG

Uffffff worked thanks :D 

`set(CMAKE_FIND_PACKAGE_PREFER_CONFIG OFF)`
