### ISSUE TITLE
[qtdeclarative] Compilation crashes midway

### ISSUE THREAD

**Issue by QiuYilin** [microsoft/vcpkg#40083]
### Operating system

Ubuntu 22.04

### Compiler

GCC

### Steps to reproduce the behavior
vcpkg location: /home/username/
vcpkg config
```
{
    "default-registry": {
        "kind": "git",
            "repository": "https://github.com/Microsoft/vcpkg",
            "baseline": "1de2026f28ead93ff1773e6e680387643e914ea1"
    }
}
```

```Shell
‘sudo ./vcpkg install qtdeclarative’
```

### Failure logs

The console exits directly and the log does not look complete
[install-x64-linux-dbg-out.log](https://github.com/user-attachments/files/16371638/install-x64-linux-dbg-out.log)

How should I debug this situation?

**Comment by jimwang118** [comment]
Here is an [example](https://www.cnblogs.com/vcpkg/p/15167876.html) of how to use xxx that we wrote, you can refer to it.

**Comment by QiuYilin** [comment]
![image](https://github.com/user-attachments/assets/e0442b5f-e96f-4bcb-b190-88bcb923390f)
I mean, when I use the official version, the compilation gets stuck at this step and crashes, and there is no valid information in the log file. How can I print detailed compilation information in the terminal so that I can see at which specific step the crash occurred?

**Comment by dg0yt** [comment]
Make sure you have enough resources (memory and disk storage).

> `sudo ./vcpkg install qtdeclarative`

There is no reason to use `sudo`. Maybe the system is already broken by previous abuse of `sudo`.

**Comment by Neumann-A** [comment]
and make sure you don't have a 13 or 14th gen Intel processor.  Also sudo and /root/ is kind of strange. So probably already broken system.

**Comment by QiuYilin** [comment]
Thanks for the correction, I reinstalled the system yesterday.

**Comment by QiuYilin** [comment]
I reinstalled my system and the problem happens again. My CPU is i7 7700HQ. Disk storage is redundant. However, I observed that my memory usage was 95% when the app crashed, and there was no record of memory overflow in the system log.

**Comment by QiuYilin** [comment]
I reinstalled my system and the problem happens again. My CPU is i7 7700HQ. Disk storage is redundant. However, I observed that my memory usage was 95% when the app crashed, and there was no record of memory overflow in the system log.

**Comment by QiuYilin** [comment]
To reduce memory usage, I ended up reducing the number of concurrent threads by setting VCPKG_MAX_CONCURRENCY.
