### ISSUE TITLE
install Microsoft VCPKG, which will then be used to build OpenCV:

### ISSUE THREAD

**Issue by kejuZhang** [microsoft/vcpkg#40082]
git clone https://github.com/microsoft/vcpkg
cd vcpkg
bootstrap-vcpkg.bat
.\vcpkg.exe integrate install
.\vcpkg.exe integrate powershell
.\vcpkg.exe install opencv[contrib,dnn,freetype,jpeg,openmp,png,webp,world]:x64-windows
**erro：**
The following packages will be built and installed:
    opencv[contrib,core,default-features,dnn,freetype,jpeg,openmp,png,webp,world]:x64-windows@4.8.0#1
  * opencv4[contrib,core,default-features,dnn,freetype,jpeg,openmp,png,quirc,tiff,webp,world]:x64-windows@4.8.0#21
  * protobuf:x64-windows@4.25.1
  * quirc:x64-windows@1.2
  * tesseract:x64-windows@5.4.1
  * vcpkg-get-python-packages:x64-windows@2024-01-24
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Compiler found: D:/soft/visualstudio/program/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from C:\Users\莱斯\AppData\Local\vcpkg\archives in 247 us. Use --debug to see more details.
Installing 1/6 protobuf:x64-windows@4.25.1...
Building protobuf:x64-windows@4.25.1...
-- Using cached protocolbuffers-protobuf-v4.25.1.tar.gz.
-- Cleaning sources at C:/src/vcpkg/buildtrees/protobuf/src/v4.25.1-a5e9c0ed50.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/src/vcpkg/downloads/protocolbuffers-protobuf-v4.25.1.tar.gz
-- Applying patch fix-static-build.patch
-- Applying patch fix-default-proto-file-path.patch
-- Applying patch fix-utf8-range.patch
-- Using source at C:/src/vcpkg/buildtrees/protobuf/src/v4.25.1-a5e9c0ed50.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
    Working Directory: C:/src/vcpkg/buildtrees/protobuf/x64-windows-dbg
    See logs for more information:
      C:\src\vcpkg\buildtrees\protobuf\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/protobuf/portfile.cmake:60 (vcpkg_cmake_install)
  scripts/ports.cmake:192 (include)

error: building protobuf:x64-windows failed with: BUILD_FAILEDSee https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle protobuf:x64-windows: 1.5 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+protobuf

**Comment by FrankXie05** [comment]
@kejuZhang Thanks for posting this issue, could you please provide the error log?
```
C:\src\vcpkg\buildtrees\protobuf\install-x64-windows-dbg-out.log
```
