### ISSUE TITLE
[pugixml] PUGIXML_WCHAR_MODE

### ISSUE THREAD

**Issue by andrelehto** [microsoft/vcpkg#40108]
### Is your feature request related to a problem? Please describe.

At the moment there is no feature flag to install pugixml in wchar_t mode.

### Proposed solution

Add a feature flag to install pugixml in wchar_t mode.

**Comment by MonicaLiu0311** [comment]
Please try #40230 to see if it meets your expectations:
![image](https://github.com/user-attachments/assets/974e2c5f-bf21-4611-acb1-8ecc490b8e49)

**Comment by MonicaLiu0311** [comment]
This violates our feature policy: [maintainer-guide#do-not-use-features-to-control-alternatives-in-published-interfaces](https://learn.microsoft.com/en-us/vcpkg/contributing/maintainer-guide#do-not-use-features-to-control-alternatives-in-published-interfaces).

So this issue will be closed.

**Comment by andrelehto** [comment]
Hold on, so if I want to use the pugixml library using wide chars, using vcpkg is not an option, since I cannot install the package using wide strings? Or am I missing something?

**Comment by dg0yt** [comment]
It can't be done as feature if that feature takes away the original API.

What you can use is per-port customization in the triplet file, using `VCPKG_CMAKE_CONFIGURE_OPTIONS`.
https://learn.microsoft.com/en-us/vcpkg/users/triplets#per-port-customization

**Comment by andrelehto** [comment]
@dg0yt That does not seem to work. I keep getting linking errors, which leads me to believe that the package is not built with the flags, although I am setting them:

`x64-windows.cmake`
```cmake
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DPUGIXML_WCHAR_MODE")

```

**Comment by andrelehto** [comment]
@dg0yt  That did not fix it. The library is still only links when the flag is not set in the main project, and `pugi::char_t` is still defined as `char`.

**Comment by andrelehto** [comment]
**Update:** The issue seems to be `/Zc:wchar_t-`. It is set in the main project, and not in the package.

**Comment by andrelehto** [comment]
That did it, thank you for the support!
