### ISSUE TITLE
opencv4[qt] Failure for install.

### ISSUE THREAD

**Issue by SkyRiderMike** [microsoft/vcpkg#40106]
### Operating system

MacOS arm64

- Host: arm64-osx
- Compiler: AppleClang 15.0.0.15000309
-    vcpkg-tool version: 2024-06-10-02590c430e4ed9215d27870138c2e579cc338772
    vcpkg-scripts version: 198d68dbc 2024-07-18 (17 hours ago)

### Compiler

AppleClang 15.0.0.15000309

### Steps to reproduce the behavior

```Shell
./vcpkg install opencv4[qt]
```

### Failure logs

zsh: no matches found: opencv4[qt]

**Comment by SkyRiderMike** [comment]
As above, i have some difficulties when i tried to install opencv4 with qt support and it fails. Also, i've tried to install other config of opencv4, (eg. opencv4[vtk]) and it also failed.

**Comment by SkyRiderMike** [comment]
what can i do ? please help~

**Comment by SkyRiderMike** [comment]
@peters @gnu-lorien @jdthomas

**Comment by dg0yt** [comment]
> zsh: no matches found: opencv4[qt]

You must learn `zsh`. Use
~~~
./vcpkg install 'opencv4[qt]'
~~~

**Comment by WangWeiLin-MV** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by SkyRiderMike** [comment]
> > zsh: no matches found: opencv4[qt]
> 
> You must learn `zsh`. Use
> 
> ```
> ./vcpkg install 'opencv4[qt]'
> ```

It works! thank you!
