### ISSUE TITLE
shiva fails to build

### ISSUE THREAD

**Issue by degski** [Microsoft/vcpkg#4012]
Z:\vcpkg>vcpkg.exe install shiva shiva-sfml
    The following packages will be built and installed:
        shiva[core]:x64-windows-static
        shiva-sfml[core]:x64-windows-static
    Starting package 1/2: shiva:x64-windows-static
    Building package shiva[core]:x64-windows-static...
    -- Using cached Z:/vcpkg/downloads/Milerius-shiva-0.7.tar.gz
    -- Using source at Z:/vcpkg/buildtrees/shiva/src/0.7-65fc489898
    -- Configuring x64-windows-static
    CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
        Command failed: ninja;-v
        Working Directory: Z:/vcpkg/buildtrees/shiva/x64-windows-static-rel/vcpkg-parallel-configure
        See logs for more information:
          Z:\vcpkg\buildtrees\shiva\config-x64-windows-static-out.log

    Call Stack (most recent call first):
      scripts/cmake/vcpkg_configure_cmake.cmake:240 (vcpkg_execute_required_process)
      ports/shiva/portfile.cmake:11 (vcpkg_configure_cmake)
      scripts/ports.cmake:71 (include)

    Error: Building package shiva:x64-windows-static failed with: BUILD_FAILED
    Please ensure you're using the latest portfiles with `.\vcpkg update`, then
    submit an issue at https://github.com/Microsoft/vcpkg/issues including:
      Package: shiva:x64-windows-static
      Vcpkg version: 0.0.113-nohash

[config-x64-windows-static-out.log](https://github.com/Microsoft/vcpkg/files/2255797/config-x64-windows-static-out.log)

PS1: One of the errors states:

    Python config failure: Python is 32-bit, chosen compiler is 64-bit

So I'm downloading `python-2.7.15-x64` and see how that goes (don't see why that should be a problem though). There's another issue related to `lua`.

PS2: The lua related issue:

    CMake Error: File Z:/vcpkg/buildtrees/shiva/src/0.7-65fc489898/modules/lua/LFSDLL-NOTFOUND does not exist.
    CMake Error at modules/lua/CMakeLists.txt:14 (configure_file):

[config-x64-windows-static-out.log](https://github.com/Microsoft/vcpkg/files/2255876/config-x64-windows-static-out.log)

**Comment by ras0219-msft** [comment]
@Milerius, the author of shiva

**Comment by Milerius** [comment]
Hey @degski, currently I support only shared build on Windows.

@ras0219-msft there is a proper way to precise it ?

**Comment by degski** [comment]
@Milerius 

64-bit is good, non-static is a bummer, though. Will you support that in the future, I saw it was actually luafilesystem, which is also available from vcpkg (and x64-windows-static).

I moved now to 64-bit python, in the passed this (64-bit) caused some un-related problems, but I guess that's all been resolved, so no problem.

What I saw happening with tbb/jemalloc (only dynamic) is that the static just gets overridden, as opposed to failing.

I'll leave this open for a little while (in case someone wants to comment), then I close it as the issue "is resolved" (we know why now at least).

**Comment by Milerius** [comment]
@degski Yes i will suport static build in the future, is already the case on Linux/OSX. For Windows i need some things to be shared, and other to be static, that's why i will support a custom triplet for shiva -> https://github.com/Microsoft/vcpkg/blob/master/docs/users/triplets.md#per-port-customization

**Comment by degski** [comment]
@Milerius 

> ... suport static build in the future ...

Great!

> ... some things to be shared, and other to be static ...

Fingers crossed then!

**Comment by Milerius** [comment]
@degski Did you try to build everything in shared on Windows, since I didn't have windows I don't know if everything work ATM on Windows

**Comment by degski** [comment]
@ Milerius

I can do that for you ( I am). Will get back.

**Comment by ras0219-msft** [comment]
>Python config failure: Python is 32-bit, chosen compiler is 64-bit

Ick, is there really no way around this? I don't immediately understand why the python bitness is related to the compiler bitness here (assuming we're talking about the system-installed python, not the `python3` port). Perhaps the port is confused about which one to use?

@Milerius You can indicate to the user that you only support shared builds by doing something like
```cmake
if(VCPKG_LIBRARY_LINKAGE STREQUAL "static" AND NOT VCPKG_CMAKE_SYSTEM_NAME)
    message(FATAL_ERROR "Shiva only supports dynamic builds on Windows.")
endif()
```
(the `VCPKG_CMAKE_SYSTEM_NAME` check is checking for windows desktop)

**Comment by Milerius** [comment]
@ras0219-msft It's a pybind11Config.cmake which emit this error

**Comment by degski** [comment]
@Milerius 

Happy coding!
