### ISSUE TITLE
Hidden CI failures

### ISSUE THREAD

**Issue by dg0yt** [microsoft/vcpkg#40124]
Some PR CI failures are not treated as errors by AZP and GH. This might lead to merging broken PRs.

E.g. https://dev.azure.com/vcpkg/public/_build/results?buildId=105435&view=logs&j=7922e5c4-0103-5f8f-ad17-45ce9bb98e80&t=8ceef4ed-9be5-594f-e707-4e1dd58a3d21
![screenshot](https://github.com/user-attachments/assets/3f6a3a70-1ccc-4869-b2f3-6e9a51610ed0)

x64-windows failed but green. 
x64-osx failed and red - it also has a `##[error]REGRESSIONS:` output line.

**Comment by Neumann-A** [comment]
> This might lead to merging broken PRs.

This ~~might~~ will lead to merging broken PRs.

**Comment by dg0yt** [comment]
This *did* lead to merging broken PRs already: #40004.

**Comment by dg0yt** [comment]
Thanks for the fix.
(I was wondering if I should or shouldn't ping you directly @BillyONeal , but I thought that quick escalation must work in the regular proces, in particular in case you are not available.)

**Comment by Neumann-A** [comment]
@dg0yt:
![image](https://github.com/user-attachments/assets/15cef76c-5f42-4149-93dc-017cf7cff174)

So:
- stronger wording. **might** is too weak to catch attention.
- PING all the maintainers when there is already a big fire! (in hope one opens the associated e-mail and sees the issue and escalates it)

We need to be loud on all channels especially the next three weeks. 

(I am also kind of wondering why I don't have an Github E-Mail titled "Hidden CI failures" from Saturday)

**Comment by BillyONeal** [comment]
> (I was wondering if I should or shouldn't ping you directly @BillyONeal , but I thought that quick escalation must work in the regular proces, in particular in case you are not available.)

If pinging me directly works and usual channels do not that's my and my team's problem, not yours :)
