### ISSUE TITLE
[libsystemd] Build error on x64-linux

### ISSUE THREAD

**Issue by CharlosNels** [microsoft/vcpkg#40137]
[issue_body.md](https://github.com/user-attachments/files/16402828/issue_body.md)

**Comment by CharlosNels** [comment]
The issue body is too long to write here, so I upload the file. ;  )

**Comment by dg0yt** [comment]
Please install system jinja2.

**Comment by CharlosNels** [comment]
> Please install system jinja2.

thx, that's useful.
