### ISSUE TITLE
When installing skia and integrating vcpkg into visual studio i got error(s) for invalid path

### ISSUE THREAD

**Issue by cherphguy** [microsoft/vcpkg#40156]
**Describe the bug**
instead of include directories being #include "skia/include/core/SkSurface.h"
they were #include "include/core/SkSurface.h"
**Environment**
- OS: Windows
- Compiler: Visual Studio

**To Reproduce**
1. ./vcpkg install skia
2. // ConsoleApplication1.cpp : This file contains the 'main' function. Program execution begins and ends there.
//

#include <iostream>
#include "skia/include/core/SkSurface.h"
#include "skia/include/core/SkCanvas.h"
#include "skia/include/core/SkPaint.h"
#include "skia/include/core/SkImage.h"
#include "skia/include/core/SkStream.h"
int main()
{
    auto surface = SkSurface::MakeRasterN32Premul(256, 256);
    if (!surface) {
        return -1; // Error creating surface
    }

    SkCanvas* canvas = surface->getCanvas();

    // Clear the canvas with a white color
    canvas->clear(SK_ColorWHITE);

    // Create a paint object
    SkPaint paint;
    paint.setColor(SK_ColorRED);
    paint.setStrokeWidth(10);
    paint.setStyle(SkPaint::kStroke_Style);

    // Draw a line
    canvas->drawLine(10, 10, 200, 200, paint);

    // Save the image to a file
    SkImage* image = surface->makeImageSnapshot().release();
    SkFILEWStream file_stream("output.png");
    image->encodeToStream(&file_stream);

    return 0;
}

// Run program: Ctrl + F5 or Debug > Start Without Debugging menu
// Debug program: F5 or Debug > Start Debugging menu

// Tips for Getting Started: 
//   1. Use the Solution Explorer window to add/manage files
//   2. Use the Team Explorer window to connect to source control
//   3. Use the Output window to see build output and other messages
//   4. Use the Error List window to view errors
//   5. Go to Project > Add New Item to create new code files, or Project > Add Existing Item to add existing code files to the project
//   6. In the future, to open this project again, go to File > Open > Project and select the .sln file

**Comment by dg0yt** [comment]
Look at what skia uses internally:
https://github.com/google/skia/blob/c1de8c48c99871c038e1972602adfb07dcc17601/include/core/SkImage.h#L11-L16
e.g.
~~~C
#include "include/core/SkRect.h"
~~~~
That's the pattern which you may also use, and it requires to add `<VCPKG_INSTALLED>/include/skia` to the project's include dirs when not using the CMake targets.

**Comment by cherphguy** [comment]
thanks

**Comment by manuel76413** [comment]
but... I use:  vcpkg.exe install skia:x64-windows, install skia package failed
