### ISSUE TITLE
[colmap] Build error on x64-windows? cmake problem?

### ISSUE THREAD

**Issue by Tidus80072** [microsoft/vcpkg#40159]
(nerfstudio) C:\Users\docto\vcpkg>.\vcpkg install colmap[cuda]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    colmap[core,cuda]:x64-windows@3.9.1
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from C:\Users\docto\AppData\Local\vcpkg\archives in 196 us. Use --debug to see more details.
Installing 1/1 colmap[core,cuda]:x64-windows@3.9.1...
Building colmap[core,cuda]:x64-windows@3.9.1...
-- Using cached colmap-colmap-3.9.1.tar.gz.
-- Cleaning sources at C:/Users/docto/vcpkg/buildtrees/colmap/src/3.9.1-d3f472677e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/docto/vcpkg/downloads/colmap-colmap-3.9.1.tar.gz
-- Applying patch fix-link-glog.patch
-- Using source at C:/Users/docto/vcpkg/buildtrees/colmap/src/3.9.1-d3f472677e.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: C:/Users/docto/vcpkg/downloads/tools/cmake-3.29.2-windows/cmake-3.29.2-windows-i386/bin/cmake.exe C:/Users/docto/vcpkg/buildtrees/colmap/src/3.9.1-d3f472677e.clean -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=C:/Users/docto/vcpkg/packages/colmap_x64-windows/debug -DFETCHCONTENT_FULLY_DISCONNECTED=ON -DCUDA_ENABLED=ON -DCMAKE_CUDA_ARCHITECTURES=native -DTESTS_ENABLED=OFF -DGIT_COMMIT_ID=e99036415ec0cf0f75c1d0b8d60fdd91af0d6c68 -DGIT_COMMIT_DATE=2024-07-30 -DOPENMP_ENABLED=ON "-DCMAKE_MAKE_PROGRAM=C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -DBUILD_SHARED_LIBS=ON -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/docto/vcpkg/scripts/toolchains/windows.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=v143 -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=C:/Users/docto/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=C:/Users/docto/vcpkg -D_VCPKG_INSTALLED_DIR=C:/Users/docto/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF
    Working Directory: C:/Users/docto/vcpkg/buildtrees/colmap/x64-windows-dbg
    Error code: 1
    See logs for more information:
      C:\Users\docto\vcpkg\buildtrees\colmap\config-x64-windows-dbg-CMakeCache.txt.log
      C:\Users\docto\vcpkg\buildtrees\colmap\config-x64-windows-dbg-CMakeConfigureLog.yaml.log
      C:\Users\docto\vcpkg\buildtrees\colmap\config-x64-windows-dbg-out.log
      C:\Users\docto\vcpkg\buildtrees\colmap\config-x64-windows-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:287 (vcpkg_execute_required_process)
  ports/colmap/portfile.cmake:48 (vcpkg_cmake_configure)
  scripts/ports.cmake:192 (include)

error: building colmap:x64-windows failed with: BUILD_FAILEDSee https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle colmap:x64-windows: 19 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+colmap
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[colmap]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2FUsers%2Fdocto%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
```[tasklist]
### Tasks
```

**Comment by greenozon** [comment]
it is not obvious the root cause..
I guess it'd be nice to attach to the issues those files:

C:\Users\docto\vcpkg\buildtrees\colmap\config-x64-windows-dbg-out.log
C:\Users\docto\vcpkg\buildtrees\colmap\config-x64-windows-dbg-err.log

**Comment by Tidus80072** [comment]
https://docs.nerf.studio/quickstart/custom_dataset.html

I step by step use install clomp by windows CUDA

**Comment by WangWeiLin-MV** [comment]
Please see #30604 for how to report a build failure.

**Comment by Tidus80072** [comment]
Thanks Lily Wang @LilyWangLL  Wang
This is support issue of cuda, please add the following arguments at here: https://github.com/microsoft/vcpkg/blob/1dc5ee30eb1032221d29f281f4a94b73f06b4284/ports/colmap/portfile.cmake#L52

add the code choose one add in line 52 ,I use the first one. Can solve .
        "-DCMAKE_CUDA_FLAGS=-allow-unsupported-compiler"
        "-DCUDA_NVCC_FLAGS=-allow-unsupported-compiler"
Then rebuild colmap[core,cuda].

It seems you are configuring CMake and there are some redundant and unnecessary options. Below is a brief explanation and recommendations for these options:

-DCMAKE_CUDA_FLAGS vs. -DCUDA_NVCC_FLAGS:
Both of these options are used to set the CUDA compiler flags. Generally, you only need one of them, typically -DCUDA_NVCC_FLAGS.

-DCUDA_ENABLED:
This option is used to enable or disable CUDA support. Keep this option if your program requires CUDA support.

-DCMAKE_CUDA_ARCHITECTURES:
This option specifies the target CUDA architecture, which is necessary because different GPUs have different architectures.

-DTESTS_ENABLED:
This option is used to enable or disable testing features. Keep this option if you need testing functionality.

-DGIT_COMMIT_ID and -DGIT_COMMIT_DATE:
These options are used to record the current Git commit ID and commit date, which is useful for version control and tracking.

-DOPENMP_ENABLED:
This option is used to enable or disable OpenMP support. Keep this option if your program requires multi-threading support.

Here’s the streamlined CMake configuration options:
OPTIONS
    -DCUDA_NVCC_FLAGS=-allow-unsupported-compiler     
    -DCUDA_ENABLED=${CUDA_ENABLED}
    -DCMAKE_CUDA_ARCHITECTURES=${CUDA_ARCHITECTURES}
    -DTESTS_ENABLED=${TESTS_ENABLED}
    -DGIT_COMMIT_ID=${GIT_COMMIT_ID}
    -DGIT_COMMIT_DATE=${COLMAP_GIT_COMMIT_DATE}
    -DOPENMP_ENABLED=${OPENMP_ENABLED}

In this configuration, -DCMAKE_CUDA_FLAGS is removed because it duplicates the functionality of -DCUDA_NVCC_FLAGS, and we only need the latter. The other options are retained to meet specific requirements. This makes the configuration more concise and clear.
