### ISSUE TITLE
[harfbuzz] Build error on x64-windows

### ISSUE THREAD

**Issue by LuKaCR7** [microsoft/vcpkg#40152]
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: D:/soft/qt/vcpkg-master/downloads/tools/ninja/1.10.2-windows/ninja.exe install -v
    Working Directory: D:/soft/qt/vcpkg-master/buildtrees/harfbuzz/x64-windows-dbg
    Error code: 1
    See logs for more information:
      D:\soft\qt\vcpkg-master\buildtrees\harfbuzz\package-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-tool-meson/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
  ports/harfbuzz/portfile.cmake:90 (vcpkg_install_meson)
  scripts/ports.cmake:192 (include)

error: building harfbuzz:x64-windows failed with: BUILD_FAILED
[package-x64-windows-dbg-out.log](https://github.com/user-attachments/files/16412846/package-x64-windows-dbg-out.log)

**Comment by greenozon** [comment]
what VC version are  you using?

looks like you need newer version...
from your logs:

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\xstddef(377): error C2338: The C++ Standard doesn't provide a hash for this type.

**Comment by greenozon** [comment]
@LuKaCR7  what MS VC version do you use?
the 
vcpkg install harfbuzz:x64-windows
builds just fine on MS VC2019

**Comment by LuKaCR7** [comment]
> @LuKaCR7 你使用哪个 MS VC 版本？ vcpkg install harfbuzz:x64-windows 在 MS VC2019 上构建得很好

I am using VC2015

**Comment by greenozon** [comment]
VC2015 supports  up to C++14
what if the code needs C++17 or 20?

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
