### ISSUE TITLE
[qtbase] build failure on windows

### ISSUE THREAD

**Issue by sgoth** [microsoft/vcpkg#40188]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
install qtbase with dnslookup feature
```

### Failure logs

    ```
    ERROR: Feature "libresolv": Forcing to "ON" breaks its condition:
        WrapResolv_FOUND
    Condition values dump:
        WrapResolv_FOUND = "FALSE"
    ```

**Comment by gauvindigital** [comment]
The building of qtbase breaks when attempting to install vtk[qt] for x64-windows in manifest mode. Even after updating VCPKG to the latest, I have the following error in the file `config-x64-windows-out.log`, :

```
ERROR: Feature "libresolv": Forcing to "ON" breaks its condition:
    WrapResolv_FOUND
Condition values dump:
    WrapResolv_FOUND = "FALSE"
```
VCPKG version:
`vcpkg package management program version 2024-08-01-fd884a0d390d12783076341bd43d77c3a6a15658`


Can you reproduce this? Am I doing something wrong?

**Comment by sgoth** [comment]
> The building of qtbase breaks when attempting to install vtk[qt] for x64-windows in manifest mode. Even after updating VCPKG to the latest, I have the following error in the file `config-x64-windows-out.log`, :
> 
> ```
> ERROR: Feature "libresolv": Forcing to "ON" breaks its condition:
>     WrapResolv_FOUND
> Condition values dump:
>     WrapResolv_FOUND = "FALSE"
> ```
> 
> VCPKG version: `vcpkg package management program version 2024-08-01-fd884a0d390d12783076341bd43d77c3a6a15658`
> 
> Can you reproduce this? Am I doing something wrong?

Did you miss updating the baseline in your manifest?

**Comment by gauvindigital** [comment]
Here's my `vcpkg.json` :
```
{
  "dependencies": [
    "boost",
    "eigen3",
    "opencv4",
    "opengl",
    "pcl",
    {
        "name": "vtk",
        "features": ["qt"]
    }
  ]
}
```
In my understanding, ommiting the commit baseline parameter in `vcpkg.json` has the effect of updating the packages to the latest versions possible. Am I right?

**Comment by jimwang118** [comment]
> In my understanding, ommiting the commit baseline parameter in `vcpkg.json` has the effect of updating the packages to the latest versions possible. Am I right?

Yes, you understand it correctly.

**Comment by sgoth** [comment]
I'm still not convinced the error is possible with current master.
That specific error should have only ever existed in qtbase 6.7.2#1
vtk and the rest of the chain even disable qtbase default features, so even the dnslookup feature isn't enabled.
Glancing over #40279 it seems vtk got touched a lot and tested on windows with qt since the last change to qtbase. I'd expect such a break would have come up a lot before.

But well - never say never - so I'd suggest opening a new issue with more info so we can see what versions are pulled in.

**Comment by dg0yt** [comment]
> > In my understanding, ommiting the commit baseline parameter in `vcpkg.json` has the effect of updating the packages to the latest versions possible. Am I right?
> 
> Yes, you understand it correctly.

That is: The latest version in your local copy of vpckg. vcpkg won't access the network. `git pull` does.

**Comment by gauvindigital** [comment]
> > The building of qtbase breaks when attempting to install vtk[qt] for x64-windows in manifest mode. Even after updating VCPKG to the latest, I have the following error in the file `config-x64-windows-out.log`, :
> > ```
> > ERROR: Feature "libresolv": Forcing to "ON" breaks its condition:
> >     WrapResolv_FOUND
> > Condition values dump:
> >     WrapResolv_FOUND = "FALSE"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > VCPKG version: `vcpkg package management program version 2024-08-01-fd884a0d390d12783076341bd43d77c3a6a15658`
> > Can you reproduce this? Am I doing something wrong?
> 
> Did you miss updating the baseline in your manifest?

@sgoth was right. It was a baseline issue. However, it was specified in my `vcpkg-configuration.json` file, which I wasn't aware of. Sorry for that!
