### ISSUE TITLE
Conflict lua <--> luajit

### ISSUE THREAD

**Issue by degski** [Microsoft/vcpkg#4019]
Z:\vcpkg>vcpkg install luajit sol2
    The following packages will be built and installed:
        luajit[core]:x64-windows-static
        sol2[core]:x64-windows-static
    Starting package 1/2: luajit:x64-windows-static
    Building package luajit[core]:x64-windows-static...
    -- Using cached Z:/vcpkg/downloads/LuaJIT-LuaJIT-v2.0.5.tar.gz
    -- Using source at Z:/vcpkg/buildtrees/luajit/src/v2.0.5-c87550d73d
    -- Applying patch Z:/vcpkg/ports/luajit/001-fixStaticBuild.patch
    -- Applying patch failed. This is expected if this patch was previously applied.
    -- Building x64-windows-static-dbg
    -- Installing: Z:/vcpkg/packages/luajit_x64-windows-static/debug/tools/luajit.exe
    -- Installing: Z:/vcpkg/packages/luajit_x64-windows-static/debug/lib/lua51.lib
    -- Building x64-windows-static-rel
    -- Installing: Z:/vcpkg/packages/luajit_x64-windows-static/tools/luajit.exe
    -- Installing: Z:/vcpkg/packages/luajit_x64-windows-static/lib/lua51.lib
    -- Installing: Z:/vcpkg/packages/luajit_x64-windows-static/include/lua.h
    -- Installing: Z:/vcpkg/packages/luajit_x64-windows-static/include/luajit.h
    -- Installing: Z:/vcpkg/packages/luajit_x64-windows-static/include/luaconf.h
    -- Installing: Z:/vcpkg/packages/luajit_x64-windows-static/include/lualib.h
    -- Installing: Z:/vcpkg/packages/luajit_x64-windows-static/include/lauxlib.h
    -- Installing: Z:/vcpkg/packages/luajit_x64-windows-static/include/lua.hpp
    -- Performing post-build validation
    -- Performing post-build validation done
    Building package luajit[core]:x64-windows-static... done
    Installing package luajit[core]:x64-windows-static...
    The following files are already installed in z:/vcpkg/installed/x64-windows-static and are in conflict with luajit:x64-windows-static

        include/lauxlib.h
        include/lua.h
        include/lua.hpp
        include/luaconf.h
        include/lualib.h

It appears (from the above output) that `luajit` uses 5.1, while `lua` is 5.3.

**Comment by JackBoosY** [comment]
This is why we recommend creating a new directory to install headers.

**Comment by LarryIII** [comment]
Thanks for your feedback. this issue has fixed in https://github.com/Microsoft/vcpkg/pull/5863/

**Comment by degski** [comment]
Thanks.
