### ISSUE TITLE
devil-x64-windows-static failure

### ISSUE THREAD

**Issue by katahiromz** [Microsoft/vcpkg#4022]
Package: devil:x64-windows-static
    Vcpkg version: 0.0.113-nohash

**Comment by wangli28** [comment]
@katahiromz Could you pull master and try again? I installed it successfully with VS2017 15.9.11 and VCPKG latest source. Please open a new issue if this is still a problem for you.

> PS F:\b\vcpkg> .\vcpkg.exe install devil:x64-windows-static
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be built and installed:
    devil[core,jasper,lcms,libjpeg,libpng,openexr,tiff]:x64-windows-static
 \ * jasper[core]:x64-windows-static
 \ * lcms[core]:x64-windows-static
 \ * libjpeg-turbo[core]:x64-windows-static
 \ * liblzma[core]:x64-windows-static
 \ * libpng[core]:x64-windows-static
 \ * openexr[core]:x64-windows-static
 \ * tiff[core]:x64-windows-static
 \ * zlib[core]:x64-windows-static
Additional packages (*) will be modified to complete this operation.
Starting package 1/9: libjpeg-turbo:x64-windows-static
Building package libjpeg-turbo[core]:x64-windows-static...
\......
Building package devil[core,jasper,lcms,libjpeg,libpng,openexr,tiff]:x64-windows-static... done
Installing package devil[core,jasper,lcms,libjpeg,libpng,openexr,tiff]:x64-windows-static...
Installing package devil[core,jasper,lcms,libjpeg,libpng,openexr,tiff]:x64-windows-static... done
Elapsed time for package devil:x64-windows-static: 1.006 min
\
Total elapsed time: 8.649 min
