### ISSUE TITLE
[ffmpeg] why disable sdl2 on osx?

### ISSUE THREAD

**Issue by foobra** [microsoft/vcpkg#40232]
### Is your feature request related to a problem? Please describe.

None

### Proposed solution

don't disable sdl2 on osx

### Describe alternatives you've considered

I test ffmpeg[all, sdl2]  on osx-x64,  and it works fine. 
So I don't know the reason why feature sdl2 disabled on osx from begining. If no other reason , i can submit a patch for that.

**Comment by dg0yt** [comment]
The answer to "why" is probably buried in the past.
If you want to make a PR, wait for (or base you work on) the ffmpeg 7 update, #38011

**Comment by FrankXie05** [comment]
Fixed by PR https://github.com/microsoft/vcpkg/issues/40232
