### ISSUE TITLE
[CMake] [Libxml2] port only includes debug library in find_package output

### ISSUE THREAD

**Issue by jarruda** [microsoft/vcpkg#4024]
**Package:** libxml2
**Triplet (tested):** x64-windows-static

**Problem:**
`find_package` sets up the `LIBXML2_LIBRARIES` variable, but that variable only contains the debug library for both libxml2.lib and its dependency on lzma.lib.  Both libxml2.lib and lzma.lib are present in the release lib dir.

**Repro**:
1. `vcpkg install libxml2:x64-windows-static`
1. `cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_TOOLCHAIN_FILE="C:\Users\arrudaj\vcpkg\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows-static`

CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.8)
find_package(LibXml2 REQUIRED)
message("xml2: ${LIBXML2_LIBRARIES}")
```

**Output** (line breaks inserted):
```
xml2:
C:/Users/arrudaj/vcpkg/installed/x64-windows-static/debug/lib/libxml2.lib;
C:/Users/arrudaj/vcpkg/installed/x64-windows-static/debug/lib/lzma.lib;
debug;C:/Users/arrudaj/vcpkg/installed/x64-windows-static/debug/lib/libiconv.lib;
optimized;C:/Users/arrudaj/vcpkg/installed/x64-windows-static/lib/libiconv.lib;
debug;C:/Users/arrudaj/vcpkg/installed/x64-windows-static/debug/lib/libcharset.lib;
optimized;C:/Users/arrudaj/vcpkg/installed/x64-windows-static/lib/libcharset.lib;
ws2_32
```

As an aside, the port for libxml2 appears to contain its own CMakeLists.txt that could be modified to export a target for the library instead of using the legacy CMake approach.

**Comment by ras0219-msft** [comment]
Thanks for posting this issue!

This is an issue with multi-configuration generators such as VS and XCode, which are not well supported by the built-in cmake targets. You can work around this issue until we can get a better fix by either:
1. Use VS2017's built-in CMake integration
2. Generate dedicated build trees for release and debug (`-DCMAKE_BUILD_TYPE=Release`, etc)

**Comment by jarruda** [comment]
Is there a reason we couldn't provide cmake targets in the CMakeLists.txt in the port directory?

**Comment by NancyLi1013** [comment]
Hi @jarruda 
Thanks for posting this issue.
Sorry for the so late reply.
We have added `vcpkg-cmake-wrapper.cmake `for `libxml2`.
You can use the following codes to find `libxml2`:
   ```
 find_package(LibXml2 REQUIRED)
    target_include_directories(main PRIVATE ${LIBXML2_INCLUDE_DIR})
    target_link_libraries(main PRIVATE ${LIBXML2_LIBRARIES})
```

**Comment by NancyLi1013** [comment]
Please feel free to reopen this issue if it is still a problem for you.
