### ISSUE TITLE
[CMake] [assimp] port only includes release library in find_package output

### ISSUE THREAD

**Issue by jarruda** [Microsoft/vcpkg#4026]
**Package:** assimp
**Triplet (tested):** x64-windows-static

**Problem:**
`find_package` sets up the `ASSIMP_LIBRARIES` variable, but that variable only contains the release library for assimp-vc140-mt.lib.  assimp-vc140-mtd.lib is present in the debug dir.

**Repro**:
1. `vcpkg install assimp:x64-windows-static`
1. `cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_TOOLCHAIN_FILE="C:\Users\arrudaj\vcpkg\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows-static`

CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.8)
find_package(assimp CONFIG REQUIRED)
message("assimp: ${ASSIMP_LIBRARIES}")
```

**Output**:
```
assimp: C:/Users/arrudaj/vcpkg/installed/x64-windows-static/lib/assimp-vc140-mt.lib
```

**Comment by jarruda** [comment]
I am currently using the following workaround.  It will need modification to work on a different platform or compiler.

```cmake
find_package(assimp CONFIG REQUIRED)
find_library(ASSIMP_DEBUG_LIBRARY assimp-vc140-mtd.lib)

add_library(assimp INTERFACE)
target_include_directories(assimp INTERFACE ${ASSIMP_INCLUDE_DIRS})
target_link_libraries(assimp INTERFACE
    debug ${ASSIMP_DEBUG_LIBRARY}
    optimized ${ASSIMP_LIBRARIES}
)
```

**Comment by jarruda** [comment]
Related issue: #3108 Cmake package config files all wrong

**Comment by ras0219-msft** [comment]
Thanks for posting this issue!

I was able to apply patches to the assimp config files which retain the previous interface but should correctly support multi-configuration generators such as VS.
