### ISSUE TITLE
[libsquish] build failure on <any>-android with ndk 27

### ISSUE THREAD

**Issue by bwrsandman** [microsoft/vcpkg#40262]
### Operating system

Linux

### Compiler

Clang

### Steps to reproduce the behavior

```Shell
export ANDROID_NDK_HOME=$HOME/Downloads/android-ndk-r27/
run `vcpkg install libsquish:arm-android`
```

### Failure logs
```
CMake Warning (dev) at CMakeLists.txt:12 (PROJECT):
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at android-ndk-r27/build/cmake/flags.cmake:46 (if):
  Policy CMP0057 is not set: Support new IN_LIST if() operator.  Run "cmake
  --help-policy CMP0057" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  IN_LIST will be interpreted as an operator when the policy is set to NEW.
  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  /usr/share/cmake/Modules/Platform/Android-Clang.cmake:23 (include)
  /usr/share/cmake/Modules/Platform/Android-Clang-C.cmake:1 (include)
  /usr/share/cmake/Modules/CMakeCInformation.cmake:48 (include)
  CMakeLists.txt:12 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at Downloads/android-ndk-r27/build/cmake/flags.cmake:46 (if):
  if given arguments:

    "hwaddress" "IN_LIST" "ANDROID_SANITIZE"

  Unknown arguments specified
Call Stack (most recent call first):
  /usr/share/cmake/Modules/Platform/Android-Clang.cmake:23 (include)
  /usr/share/cmake/Modules/Platform/Android-Clang-C.cmake:1 (include)
  /usr/share/cmake/Modules/CMakeCInformation.cmake:48 (include)
  CMakeLists.txt:12 (PROJECT)
```

### Additional context

https://github.com/android/ndk/issues/2032

**Comment by sr-tream** [comment]
Affected most packages: curlpp, openal-soft, bzip2. Anything what I trieng to build with vcpkg and NDK 27. If I use NDK 26 or [CPM](https://github.com/cpm-cmake/CPM.cmake) instead vcpkg - all works fine

**Comment by dg0yt** [comment]
> Affected most packages: curlpp, openal-soft, bzip2. Anything what I trieng to build with vcpkg and NDK 27. If I use NDK 26 or [CPM](https://github.com/cpm-cmake/CPM.cmake) instead vcpkg - all works fine

It affects anything which uses NDK 27 CMake toolchains. It can be mitigated by injecting a CMake policy setting via custom android triplets. A more permanent workaround could be added to `scripts/toolchains/android.cmake`

**Comment by dg0yt** [comment]
> It affects anything which uses NDK 27 CMake toolchains.

This was too negative. It affects only CMake project which don't require CMake 3.5 or newer.
Let's move the broader topic to #40339.
