### ISSUE TITLE
cmake can't find mongo-cxx-driver

### ISSUE THREAD

**Issue by 678uhb** [microsoft/vcpkg#4027]
i installed mongo-c-driver libbson mongo-cxx-driver via vcpkg
and i can only find mongo-c-driver-config.cmake in installed folder
and i can see libmongocxx-config.cmake in buildtrees folder

i have tried 
find_package(mongo-cxx-driver REQUIRED)
find_package(libmongocxx REQUIRED)
they all result in something like below(vscode with cmake extension):
```
[cmake]   Could not find a package configuration file provided by "mongo-cxx-driver"
[cmake]   with any of the following names:
[cmake] 
[cmake]     mongo-cxx-driverConfig.cmake
[cmake]     mongo-cxx-driver-config.cmake
```

**Comment by 678uhb** [comment]
and in linux 
i tried 
`vcpkg install mongo-cxx-driver`
result to
```
 file RENAME failed to rename

    /root/vcpkg/packages/libbson_x64-linux/lib/bson-static-1.0.lib

  to

    /root/vcpkg/packages/libbson_x64-linux/lib/bson-1.0.lib

  because: No such file or directory

Call Stack (most recent call first):
  scripts/ports.cmake:71 (include)

```
and there is only a libbson-static-1.0.a not bson-static-1.0.lib

**Comment by lsparey** [comment]
I've been able to get it working locally for version 3.4.0 by adding the cmake targets which were missing. It looks like you need at least version 3.2.0 of mongo-cxx-driver for the linking to work nicely and that's the latest version that works with the current mongo-c-driver and libbson ports, so I've submitted a pull request that should fix this

**Comment by KaoCC** [comment]
It seems like the package can be found but the link will fail. I did it like this:
```
find_package(libmongocxx REQUIRED)
target_link_libraries(app PRIVATE ${LIBMONGOCXX_LIBRARIES})
```

Error message:
```
[build] Undefined symbols for architecture x86_64:
[build]   "_mongoc_cleanup", referenced from:
[build]       mongocxx::v_noabi::instance::impl::~impl() in libmongocxx-static.a(instance.cpp.o)
[build]   "_mongoc_handshake_data_append", referenced from:
[build]       mongocxx::v_noabi::instance::impl::impl(std::__1::unique_ptr<mongocxx::v_noabi::logger, std::__1::default_delete<mongocxx::v_noabi::logger> >) in libmongocxx-static.a(instance.cpp.o)
[build]   "_mongoc_init", referenced from:
[build]       mongocxx::v_noabi::instance::impl::impl(std::__1::unique_ptr<mongocxx::v_noabi::logger, std::__1::default_delete<mongocxx::v_noabi::logger> >) in libmongocxx-static.a(instance.cpp.o)
[build]   "_mongoc_log", referenced from:
[build]       mongocxx::v_noabi::instance::impl::impl(std::__1::unique_ptr<mongocxx::v_noabi::logger, std::__1::default_delete<mongocxx::v_noabi::logger> >) in libmongocxx-static.a(instance.cpp.o)
[build]   "_mongoc_log_set_handler", referenced from:
[build]       mongocxx::v_noabi::instance::impl::impl(std::__1::unique_ptr<mongocxx::v_noabi::logger, std::__1::default_delete<mongocxx::v_noabi::logger> >) in libmongocxx-static.a(instance.cpp.o)
[build]       mongocxx::v_noabi::instance::impl::~impl() in libmongocxx-static.a(instance.cpp.o)
[build] ld: symbol(s) not found for architecture x86_64
```

**Comment by alandr967** [comment]
> It seems like the package can be found but the linking stage will fail. I did it like this:
> 
> ```
> find_package(libmongocxx REQUIRED)
> target_link_libraries(app PRIVATE ${LIBMONGOCXX_LIBRARIES})
> ```
> 
> Error message:
> 
> ```
> [build] Undefined symbols for architecture x86_64:
> [build]   "_mongoc_cleanup", referenced from:
> [build]       mongocxx::v_noabi::instance::impl::~impl() in libmongocxx-static.a(instance.cpp.o)
> [build]   "_mongoc_handshake_data_append", referenced from:
> [build]       mongocxx::v_noabi::instance::impl::impl(std::__1::unique_ptr<mongocxx::v_noabi::logger, std::__1::default_delete<mongocxx::v_noabi::logger> >) in libmongocxx-static.a(instance.cpp.o)
> [build]   "_mongoc_init", referenced from:
> [build]       mongocxx::v_noabi::instance::impl::impl(std::__1::unique_ptr<mongocxx::v_noabi::logger, std::__1::default_delete<mongocxx::v_noabi::logger> >) in libmongocxx-static.a(instance.cpp.o)
> [build]   "_mongoc_log", referenced from:
> [build]       mongocxx::v_noabi::instance::impl::impl(std::__1::unique_ptr<mongocxx::v_noabi::logger, std::__1::default_delete<mongocxx::v_noabi::logger> >) in libmongocxx-static.a(instance.cpp.o)
> [build]   "_mongoc_log_set_handler", referenced from:
> [build]       mongocxx::v_noabi::instance::impl::impl(std::__1::unique_ptr<mongocxx::v_noabi::logger, std::__1::default_delete<mongocxx::v_noabi::logger> >) in libmongocxx-static.a(instance.cpp.o)
> [build]       mongocxx::v_noabi::instance::impl::~impl() in libmongocxx-static.a(instance.cpp.o)
> [build] ld: symbol(s) not found for architecture x86_64
> ```

Did you find the solution? I am now struggling with the same one?

**Comment by KaoCC** [comment]
I gave up and used Go package at the end...

**Comment by LilyWangLL** [comment]
This issue has been fixed, You can use the following codes to use `mongo-cxx-driver` in your CMake project.
```
    find_package(mongocxx CONFIG REQUIRED)
    target_link_libraries(main PRIVATE mongo::mongocxx_shared)
```
