### ISSUE TITLE
HDF5 lib name incompatible with CMake's FindHDF5

### ISSUE THREAD

**Issue by letmaik** [microsoft/vcpkg#4028]
The lib name of HDF5 is libhdf5.lib, however it should be hdf5.lib as CMake does not prepend `lib` on Windows when searching for libraries. I saw the same for a few other libraries like libcurl.lib, libeay32.lib, libszip.lib. On the other hand, we have ssleay32.lib, netcdf.lib, or zlib.lib.
This is for the scenario when using vcpkg for existing projects without touching any CMakeLists.txt files, meaning most likely module mode is used while looking for libraries.

**Comment by Neumann-A** [comment]
simply renaming is actually a problem if you use CMake targets and if a library builds both a static and a dynamic versions of itself and exports the appropriate targets for it just like hdf5 does.
So currently: 
```
find_package(hdf5 CONFIG REQUIRED COMPONENTS C CXX)
target_link_libraries(${PROJECT_NAME} PUBLIC hdf5::hdf5-static hdf5::hdf5_hl-static hdf5::hdf5_cpp-static)
```
works as expected and links the correct libraries (libhdf5... etc. ).  
You could also look it up in `hdf5-targets-<config>.cmake`
Maybe update your CMakeLists.txt to use more modern CMake features/syntax/style.

**Comment by luzpaz** [comment]
Any progress on this ?

**Comment by JackBoosY** [comment]
Since hdf5 officially exported namespace `hdf5::`, I think we should use `hdf5::hdf5-shared hdf5::hdf5_hl-shared` or `hdf5::hdf5-static hdf5::hdf5_hl-static`.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
