### ISSUE TITLE
[Reviewed] building realsense2:x64-linux failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by may-iCOMgiken** [microsoft/vcpkg#40281]
### Operating system

WSL2

### Steps to reproduce the behavior

```Shell
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
./bootstrap-vcpkg.sh
./vcpkg integrate install
./vcpkg install realsense2
```

### Failure logs

error: building realsense2:x64-linux failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle realsense2:x64-linux: 4.4 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+realsense2
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[realsense2]+Build+error+on+x64-linux&body=Copy+issue+body+from+%2Fmnt%2Fc%2FSources%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

```[tasklist]
### Tasks
```

**Comment by MonicaLiu0311** [comment]
Please provide the complete error log.

**Comment by MonicaLiu0311** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
