### ISSUE TITLE
What cmake bin to use?

### ISSUE THREAD

**Issue by NietzscheCoder** [Microsoft/vcpkg#4029]
Ok so after setting it up perfectly by following the tutorial, i created a sample application using cmake and tried the demo glew library..when I only try it with one package it works and builds successfully!, however when I add, say glfw3 with it, it'll say GLFW/glfw3.h not found, whereas if i spawn a new project with only glfw3 imported, that'll work. 

Visual studio has its own cmake.exe/cpack.exe bins, VCPKG also has its own, what should be used? Does it matter?

Here's the "config-x86-windows-out.log" output

```
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE  
-- Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR) 
-- Using Win32 for window creation
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_INSTALL_BINDIR
    CMAKE_INSTALL_LIBDIR
    PACKAGE_CMAKE_INSTALL_PREFIX

```

And after this it fails! Btw I haven't modified any Manually-specified variables whatsoever!

**Comment by Voskrese** [comment]
So what's the problem?

**Comment by NietzscheCoder** [comment]
Glfw/glfw3.h not found

**Comment by ras0219-msft** [comment]
Any of the cmake.exe versions should be fine to use.

Could you post your CMakeLists.txt?
