### ISSUE TITLE
[microsoft-signalr] Build error on x64-linux

### ISSUE THREAD

**Issue by sagarc02** [microsoft/vcpkg#40292]
The package microsoft-signalr[cpprestsdk] has failed while building and installing.

The error log has been atached.

please find the command below used to build and install package:

vcpkg microsoft-signalr[cpprestsdk]
[install-x64-linux-dbg-out.log](https://github.com/user-attachments/files/16493854/install-x64-linux-dbg-out.log)
[install-x64-linux-dbg-err.log](https://github.com/user-attachments/files/16493856/install-x64-linux-dbg-err.log)

**Comment by mprather** [comment]
See https://github.com/aspnet/SignalR-Client-Cpp/pull/96.
