### ISSUE TITLE
[drogon] Build error on x64-linux

### ISSUE THREAD

**Issue by sagarc02** [microsoft/vcpkg#40291]
[config-x64-linux-dbg-out.log](https://github.com/user-attachments/files/16493537/config-x64-linux-dbg-out.log)

The drogon[mysql] package is failing on build the package using vcpkg :

command used to build the package is:

vcpkg install drogon[mysql] --recurse

**Comment by jimwang118** [comment]
There is no valid error message from the log. Do you have any other error information to provide?

**Comment by sagarc02** [comment]
please find the updated error log atached.
[install-x64-linux-dbg-out.log](https://github.com/user-attachments/files/16494188/install-x64-linux-dbg-out.log)

**Comment by jimwang118** [comment]
Sorry, i cannot reproduce this issue locally.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
