### ISSUE TITLE
[blas] `blas` incorrectly thinks `openblas` doesn't support static compilation

### ISSUE THREAD

**Issue by rjzak** [microsoft/vcpkg#40300]
### Is your feature request related to a problem? Please describe.

I'd like to use Armadillo with a fully static build. Armadillo uses `blas` which imports `openblas`.

The `blas` [vcpkg.json](https://github.com/microsoft/vcpkg/blob/master/ports/blas/vcpkg.json) seems to think `openblas` doesn't support static builds, but the [vcpkg.json](https://github.com/microsoft/vcpkg/blob/master/ports/openblas/vcpkg.json) for it doesn't have `!static`.

### Proposed solution

Remove `!static` for `openblas` dependency in https://github.com/microsoft/vcpkg/blob/master/ports/blas/vcpkg.json.

**Comment by Neumann-A** [comment]
blas is a metaport. It will use the blas vendored in lapack for static builds.

**Comment by rjzak** [comment]
But it seems to disable static compilation, which should work.

**Comment by Neumann-A** [comment]
> But it seems to disable static compilation, which should work.

You can compile openblas staticly. It will just not be used to fullfill the blas dependency in dependent ports. Alternative, use an overlay and deactivate lapack. You don't want to have two competing blas implementations.

**Comment by Neumann-A** [comment]
To be clear here: You cannot build static openblas and have lapack use openblas at the same time. This is why the deps are this way.

**Comment by rjzak** [comment]
Is there a way to compile a project with Armadillo and have it all statically compiled, without needing a libblas.dll, libgfortran.dll, libquadmath.dll, openblas.dll, etc?
