### ISSUE TITLE
[libsodium] Build error on x86-windows

### ISSUE THREAD

**Issue by ursids** [microsoft/vcpkg#40314]
**Library name** :  libsodium

**Version** :  1.0.19

I am running into errors when trying to build libsodium. Looks to be a mismatch in the hash expected.

```
4>[DEBUG] Trying to hash D:\Project\apps\vcpkg\current\downloads\jedisct1-libsodium-1.0.19.tar.gz.3220.part
4>[DEBUG] D:\Project\apps\vcpkg\current\downloads\jedisct1-libsodium-1.0.19.tar.gz.3220.part has hash efeb4c0dc352993fc128974abb27e4be60521e85ce191c8c38a84168d4e7d7b1d2c26843250077dd21dadb13678bf56712375e74754eb02100b8cc418ebffb94
4>EXEC : error : Missing jedisct1-libsodium-1.0.19.tar.gz and downloads are blocked by x-block-origin.
4>EXEC : error : File does not have the expected hash:
4>url: https://github.com/jedisct1/libsodium/archive/1.0.19.tar.gz
4>File: D:\Project\apps\vcpkg\current\downloads\jedisct1-libsodium-1.0.19.tar.gz.3220.part
4>Expected hash: 6094d7bf191ea3be85f2ddab76b71f1b9c69c786493db5b84d3c5d5a0237003377ddf6a8687a962ea651fe4a9369cf5ee1676ba0bae82690f5f7ef31a698efa9
4>Actual hash: efeb4c0dc352993fc128974abb27e4be60521e85ce191c8c38a84168d4e7d7b1d2c26843250077dd21dadb13678bf56712375e74754eb02100b8cc418ebffb94
```

**Comment by greenozon** [comment]
Your library was not fully downloaded (as it has .part in the end for some reason)
as a temp workaround you could download it by hands and put into vcpkg\downloads\ dir
but of course it should be done automatically by vcpkg itself..

**Comment by dg0yt** [comment]
Libsodium's fault.
Duplicates https://github.com/microsoft/vcpkg/issues/38947

**Comment by ursids** [comment]
@dg0yt Shouldn't pull request https://github.com/microsoft/vcpkg/pull/38954 cause vcpkg to now download v1.0.20 instead of v1.0.19. I do not use the versions feature flag.
