### ISSUE TITLE
[SDL2] update to 2.30.6

### ISSUE THREAD

**Issue by MSlockbo** [microsoft/vcpkg#40338]
### Library name

SDL2

### New version number

2.30.6

### Other information that may be useful (release notes, etc...)

This is a stable bugfix release, with the following changes:
- Improved detection of Nintendo Switch Pro controller report mode
- Fixed a rare crash when a controller is disconnected
- Fixed creating a framebuffer with KMSDRM on some systems

**Comment by dg0yt** [comment]
#40259
