### ISSUE TITLE
[pugixml] Build error on x64-windows

### ISSUE THREAD

**Issue by greenozon** [microsoft/vcpkg#40333]
Copied issue body from C:/Dev/vcpkg/installed/vcpkg/issue_body.md

Package: pugixml:x64-windows@1.14

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.29.30154.0
-    vcpkg-tool version: 2024-08-01-fd884a0d390d12783076341bd43d77c3a6a15658
    vcpkg-scripts version: 6af584dd5 2024-08-06 (15 hours ago)

**To Reproduce**

`vcpkg install pugixml`

**Failure logs**

-- Using cached zeux-pugixml-v1.14.tar.gz.
-- Cleaning sources at C:/Dev/vcpkg/buildtrees/pugixml/src/v1.14-3215fd4dab.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Dev/vcpkg/downloads/zeux-pugixml-v1.14.tar.gz
-- Using source at C:/Dev/vcpkg/buildtrees/pugixml/src/v1.14-3215fd4dab.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at ports/pugixml/portfile.cmake:17 (vcpkg_cmake_config_fixup):
  Unknown CMake command "vcpkg_cmake_config_fixup".
Call Stack (most recent call first):
  scripts/ports.cmake:192 (include)

steps:

```
c:\Dev\vcpkg>git pull
Already up to date.

c:\Dev\vcpkg>bootstrap-vcpkg.bat
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2024-08-01/vcpkg.exe -> C:\Dev\vcpkg\vcpkg.exe... done.
Validating signature... done.

vcpkg package management program version 2024-08-01-fd884a0d390d12783076341bd43d77c3a6a15658

See LICENSE.txt for license information.

c:\Dev\vcpkg>vcpkg install pugixml
Computing installation plan...
The following packages will be built and installed:
    pugixml:x64-windows@1.14
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Dev/VS2019/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from C:\Users\TATO\AppData\Local\vcpkg\archives in 225 us. Use --debug to see more details.
Installing 1/1 pugixml:x64-windows@1.14...
Building pugixml:x64-windows@1.14...
-- Using cached zeux-pugixml-v1.14.tar.gz.
-- Cleaning sources at C:/Dev/vcpkg/buildtrees/pugixml/src/v1.14-3215fd4dab.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Dev/vcpkg/downloads/zeux-pugixml-v1.14.tar.gz
-- Using source at C:/Dev/vcpkg/buildtrees/pugixml/src/v1.14-3215fd4dab.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at ports/pugixml/portfile.cmake:17 (vcpkg_cmake_config_fixup):
  Unknown CMake command "vcpkg_cmake_config_fixup".
Call Stack (most recent call first):
  scripts/ports.cmake:192 (include)


error: building pugixml:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle pugixml:x64-windows: 9.6 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+pugixml
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[pugixml]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2FDev%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md


c:\Dev\vcpkg>vcpkg list
pkgconf:x64-windows                               2.2.0               pkgconf is a program which helps to configure co...
vcpkg-boost:x64-windows                           2024-05-15
vcpkg-cmake-config:x64-windows                    2024-05-23
vcpkg-cmake-get-vars:x64-windows                  2023-12-31
vcpkg-cmake:x64-windows                           2024-04-23
vcpkg-gn:x64-windows                              2024-02-22          GN is a meta-build system that generates build f...
vcpkg-tool-gn:x64-windows                         2024-02-22          GN build system
vcpkg-tool-meson:x64-windows                      1.5.1               Meson build system
```

**Comment by greenozon** [comment]
the funny thing is that it worked this week, but something got broken.. not sure what is that

**Comment by dg0yt** [comment]
You can try `vcpkg install pugixml --cmake-args=--trace-expand`  
At some point it should load `share/vcpkg-cmake-config/vcpkg-port-config.cmake` and so on.
Unless you removed the files from `installed/<host_triplet>`.

**Comment by greenozon** [comment]
Thanks!

the --trace-expand  produces super huge logs....

I guess you are right (there were smth removed from the installed/<host_triplet> dir

anyway, I'd like to find that error log in attached file, and close the ticket
if you happen to pint me into the error line,...
thank you for the time & support

[issue_body.md](https://github.com/user-attachments/files/16532503/issue_body.md)

**Comment by dg0yt** [comment]
So it is not loading `share/vcpkg-cmake-config/vcpkg-port-config.cmake`, and that's why the script doesn't get the maintainer function.

You will have to reinstall `vcpkg-cmake-config`. Or maybe more.

**Comment by greenozon** [comment]
Excellent root causing
Thanks again
I"ll be more carefull in the future

Closing
