### ISSUE TITLE
bootstrap-vcpkg.sh is showing a weird error

### ISSUE THREAD

**Issue by IronicallySerious** [Microsoft/vcpkg#4034]
The error I am getting is this:
```
Downloading cmake...
curl: (48) An unknown option was passed in to libcurl
```

**Comment by ras0219-msft** [comment]
Thanks for posting!

What system are you on and what version of curl do you have (`curl --version`)?

**Comment by IronicallySerious** [comment]
I just cloned the repo again after deleting it and somehow it's working now.
Closing this. 

Thanks for the response!
I have been getting some issues on using DevIL with vcpkg, for those I have opened separate issues
