### ISSUE TITLE
spdlog not the same in linux and windows

### ISSUE THREAD

**Issue by ywj11407** [Microsoft/vcpkg#4036]
the spdlog of linux maybe is old， some files can’t find  (https://github.com/gabime/spdlog)

**Comment by arthur-tacca** [comment]
If you are using vcpkg on both Windows and Linux, are you sure you have the most up to date revision of the vcpkg repository? Its spdlog port changed in the last couple of days.


Or, do you mean that the version of spdlog provided by your Linux package manager is older than the version provided by vcpkg? If so, why is that vcpkg's fault any more than that of your Linux package manager?

I can think of several ways around this:

* Use an older version of spdlog on Windows. To do this, find a revision of vcpkg from before spdlog was updated, and build all your packages using that revision of vcpkg.
* Use a newer version of spdlog on Linux. One way of doing that is to download spdlog yourself on Linux. Or find a private Linux package for newer spdlog e.g. some PPA (if you are using Ubuntu).
* Use a newer version of spdlog on Linux by using vcpkg for Linux!
* Write code that works for both versions of spdlog by using `#ifdef` statements. If `SPDLOG_VER_MAJOR` is not defined then you are using an old version of spdlog. If it is defined and equal to 1 then you are using a new version of spdlog. In future if another version of spdlog is released then `SPDLOG_VER_MAJOR` might be defined as greater than 1. See [spdlog issue #767](https://github.com/gabime/spdlog/issues/767) for more info.
