### ISSUE TITLE
[libevent] Build error on loongarch64-linux

### ISSUE THREAD

**Issue by Swwc2023** [microsoft/vcpkg#40363]
Copy issue body from /home/loongson/Tool/vcpkg/installed/vcpkg/issue_body.md
```[tasklist]
### Tasks
```

**Comment by LilyWangLL** [comment]
Please provide the error log, see #30604 for how to report an issue.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
