### ISSUE TITLE
[libevent] Build error on loongarch64-linux

### ISSUE THREAD

**Issue by ttlovehh** [microsoft/vcpkg#40364]
error: building libevent:loongarch64-linux failed with: BUILD_FAILED
Elapsed time to handle libevent:loongarch64-linux: 3.5 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libevent
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[libevent]+Build+error+on+loongarch64-linux&body=Copy+issue+body+from+%2Fhome%2Floongson%2FTool%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by Cheney-W** [comment]
Please see #30604 for how to report an issue.
