### ISSUE TITLE
getopt only supports dynamic library linkage.

### ISSUE THREAD

**Issue by degski** [Microsoft/vcpkg#4037]
getopt-win32 only supports dynamic library linkage. Building dynamic library.

Is there a reason for this?

**Comment by ras0219-msft** [comment]
The upstream project providing the implementation (https://github.com/libimobiledevice-win32/getopt) uses MSBuild and only has project files for building a DLL.

If you'd like to submit a PR with a CMake replacement that can build both, that would be awesome!

**Comment by degski** [comment]
@ras0219-msft 

Now, after having looked at that project, in particular [article.md](https://github.com/libimobiledevice-win32/getopt/blob/master/article.md), it looks to me like this is only providing a dynamic build because of the LGPL restrictions. I've never written one line of cmake, but it looks like this is the "hello world" project for cmake. In view of the LGPL-issue, just tell me what you think could/should be done.
