### ISSUE TITLE
[<vcpkg-tool>] build failure on arm64-linux

### ISSUE THREAD

**Issue by hqho** [microsoft/vcpkg#40382]
### Operating system

SUSE Linux Enterprise Server 15 SP4

### Compiler

GCC 7.5.0

### Steps to reproduce the behavior

```Shell
env VCPKG_ROOT=$InstallDIR/vcpkg $InstallDIR/vcpkg/bootstrap-vcpkg.sh
```

### Failure logs

Unable to determine a binary release of vcpkg; attempting to build from source.
Building vcpkg-tool...
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting the C++ compiler in use
-- Detecting the C++ compiler in use - gcc
-- Version: 10.1.0
-- Build type: Release
-- Performing Test CPP_ATOMIC_BUILTIN
-- Performing Test CPP_ATOMIC_BUILTIN - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/build
[0/2] Re-checking globbed directories...
[134/217] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/dependencies.cpp.o
FAILED: CMakeFiles/vcpkglib.dir/src/vcpkg/dependencies.cpp.o
/usr/bin/c++ -DVCPKG_BASE_VERSION=2999-12-31 -DVCPKG_VERSION=unknownhash -D_FILE_OFFSET_BITS=64 -I/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/include -I_deps/fmt-src/include -I_cmrc/include -O3 -DNDEBUG -pthread -std=c++1z -Winvalid-pch -include /gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/build/CMakeFiles/vcpkglib.dir/cmake_pch.hxx -MD -MT CMakeFiles/vcpkglib.dir/src/vcpkg/dependencies.cpp.o -MF CMakeFiles/vcpkglib.dir/src/vcpkg/dependencies.cpp.o.d -o CMakeFiles/vcpkglib.dir/src/vcpkg/dependencies.cpp.o -c /gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/dependencies.cpp
In file included from /usr/include/c++/7/memory:64:0,
                 from _deps/fmt-src/include/fmt/format.h:41,
                 from _deps/fmt-src/include/fmt/compile.h:11,
                 from /gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/include/vcpkg/base/fmt.h:15,
                 from /gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/include/pch.h:5,
                 from /gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/build/CMakeFiles/vcpkglib.dir/cmake_pch.hxx:5,
                 from <command-line>:0:
/usr/include/c++/7/bits/stl_construct.h: In instantiation of 'void std::_Construct(_T1*, _Args&& ...) [with _T1 = vcpkg::InstallPlanAction; _Args = {const vcpkg::InstallPlanAction&}]':
/usr/include/c++/7/bits/stl_uninitialized.h:83:18:   required from 'static _ForwardIterator std::__uninitialized_copy<_TrivialValueTypes>::__uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = __gnu_cxx::__normal_iterator<const vcpkg::InstallPlanAction*, std::vector<vcpkg::InstallPlanAction> >; _ForwardIterator = vcpkg::InstallPlanAction*; bool _TrivialValueTypes = false]'
/usr/include/c++/7/bits/stl_uninitialized.h:134:15:   required from '_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = __gnu_cxx::__normal_iterator<const vcpkg::InstallPlanAction*, std::vector<vcpkg::InstallPlanAction> >; _ForwardIterator = vcpkg::InstallPlanAction*]'
/usr/include/c++/7/bits/stl_uninitialized.h:289:37:   required from '_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = __gnu_cxx::__normal_iterator<const vcpkg::InstallPlanAction*, std::vector<vcpkg::InstallPlanAction> >; _ForwardIterator = vcpkg::InstallPlanAction*; _Tp = vcpkg::InstallPlanAction]'
/usr/include/c++/7/bits/stl_vector.h:331:31:   required from 'std::vector<_Tp, _Alloc>::vector(const std::vector<_Tp, _Alloc>&) [with _Tp = vcpkg::InstallPlanAction; _Alloc = std::allocator<vcpkg::InstallPlanAction>]'
/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/include/vcpkg/dependencies.h:93:12:   required from 'vcpkg::ExpectedHolder<T>::ExpectedHolder(Fwd&&) [with Fwd = vcpkg::ActionPlan&; typename std::enable_if<(! is_same_v<vcpkg::ExpectedHolder<T>, typename std::remove_cv<typename std::remove_reference<_SrcTuple>::type>::type>), int>::type <anonymous> = 0; T = vcpkg::ActionPlan]'
/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/include/vcpkg/base/expected.h:78:66:   required from 'vcpkg::ExpectedT<T, Error>::ExpectedT(ConvToT&&) [with ConvToT = vcpkg::ActionPlan&; typename std::enable_if<(is_convertible_v<ConvToT, T> && (! is_same_v<typename std::remove_reference<_SrcTuple>::type, Error>)), int>::type <anonymous> = 0; T = vcpkg::ActionPlan; Error = vcpkg::LocalizedString]'
/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/dependencies.cpp:2051:20:   required from here
/usr/include/c++/7/bits/stl_construct.h:75:7: error: use of deleted function 'vcpkg::InstallPlanAction::InstallPlanAction(const vcpkg::InstallPlanAction&)'
     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/dependencies.cpp:8:0:
/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/include/vcpkg/dependencies.h:37:9: note: declared here
         InstallPlanAction(const InstallPlanAction&) = delete;
         ^~~~~~~~~~~~~~~~~
[141/217] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/sourceparagraph.cpp.o
FAILED: CMakeFiles/vcpkglib.dir/src/vcpkg/sourceparagraph.cpp.o
/usr/bin/c++ -DVCPKG_BASE_VERSION=2999-12-31 -DVCPKG_VERSION=unknownhash -D_FILE_OFFSET_BITS=64 -I/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/include -I_deps/fmt-src/include -I_cmrc/include -O3 -DNDEBUG -pthread -std=c++1z -Winvalid-pch -include /gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/build/CMakeFiles/vcpkglib.dir/cmake_pch.hxx -MD -MT CMakeFiles/vcpkglib.dir/src/vcpkg/sourceparagraph.cpp.o -MF CMakeFiles/vcpkglib.dir/src/vcpkg/sourceparagraph.cpp.o.d -o CMakeFiles/vcpkglib.dir/src/vcpkg/sourceparagraph.cpp.o -c /gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/sourceparagraph.cpp
/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/sourceparagraph.cpp: In function 'vcpkg::ExpectedL<std::unique_ptr<vcpkg::SourceParagraph> > vcpkg::parse_source_paragraph(vcpkg::StringView, vcpkg::Paragraph&&)':
/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/sourceparagraph.cpp:399:16: error: could not convert 'spgh' from 'std::unique_ptr<vcpkg::SourceParagraph>' to 'vcpkg::ExpectedL<std::unique_ptr<vcpkg::SourceParagraph> > {aka vcpkg::ExpectedT<std::unique_ptr<vcpkg::SourceParagraph>, vcpkg::LocalizedString>}'
         return spgh;
                ^~~~
/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/sourceparagraph.cpp: In function 'vcpkg::ExpectedL<std::unique_ptr<vcpkg::FeatureParagraph> > vcpkg::parse_feature_paragraph(vcpkg::StringView, vcpkg::Paragraph&&)':
/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/sourceparagraph.cpp:434:16: error: could not convert 'fpgh' from 'std::unique_ptr<vcpkg::FeatureParagraph>' to 'vcpkg::ExpectedL<std::unique_ptr<vcpkg::FeatureParagraph> > {aka vcpkg::ExpectedT<std::unique_ptr<vcpkg::FeatureParagraph>, vcpkg::LocalizedString>}'
         return fpgh;
                ^~~~
/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/sourceparagraph.cpp: In static member function 'static vcpkg::ExpectedL<std::unique_ptr<vcpkg::SourceControlFile> > vcpkg::SourceControlFile::parse_control_file(vcpkg::StringView, std::vector<std::map<std::__cxx11::basic_string<char>, std::pair<std::__cxx11::basic_string<char>, vcpkg::TextRowCol>, std::less<void> > >&&)':
/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/sourceparagraph.cpp:465:16: error: could not convert 'control_file' from 'std::unique_ptr<vcpkg::SourceControlFile>' to 'vcpkg::ExpectedL<std::unique_ptr<vcpkg::SourceControlFile> > {aka vcpkg::ExpectedT<std::unique_ptr<vcpkg::SourceControlFile>, vcpkg::LocalizedString>}'
         return control_file;
                ^~~~~~~~~~~~
[142/217] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/registries.cpp.o
FAILED: CMakeFiles/vcpkglib.dir/src/vcpkg/registries.cpp.o
/usr/bin/c++ -DVCPKG_BASE_VERSION=2999-12-31 -DVCPKG_VERSION=unknownhash -D_FILE_OFFSET_BITS=64 -I/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/include -I_deps/fmt-src/include -I_cmrc/include -O3 -DNDEBUG -pthread -std=c++1z -Winvalid-pch -include /gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/build/CMakeFiles/vcpkglib.dir/cmake_pch.hxx -MD -MT CMakeFiles/vcpkglib.dir/src/vcpkg/registries.cpp.o -MF CMakeFiles/vcpkglib.dir/src/vcpkg/registries.cpp.o.d -o CMakeFiles/vcpkglib.dir/src/vcpkg/registries.cpp.o -c /gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/registries.cpp
/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/registries.cpp: In lambda function:
/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/registries.cpp:777:24: error: could not convert 'res' from 'std::unique_ptr<{anonymous}::BuiltinGitRegistryEntry, std::default_delete<{anonymous}::BuiltinGitRegistryEntry> >' to 'vcpkg::ExpectedL<std::unique_ptr<vcpkg::RegistryEntry> > {aka vcpkg::ExpectedT<std::unique_ptr<vcpkg::RegistryEntry>, vcpkg::LocalizedString>}'
                 return res;
                        ^~~
/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/registries.cpp: In lambda function:
/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/registries.cpp:861:24: error: could not convert 'res' from 'std::unique_ptr<{anonymous}::FilesystemRegistryEntry, std::default_delete<{anonymous}::FilesystemRegistryEntry> >' to 'vcpkg::ExpectedL<std::unique_ptr<vcpkg::RegistryEntry> > {aka vcpkg::ExpectedT<std::unique_ptr<vcpkg::RegistryEntry>, vcpkg::LocalizedString>}'
                 return res;
                        ^~~
[147/217] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/postbuildlint.cpp.o
ninja: build stopped: subcommand failed.

**Comment by LilyWangLL** [comment]
You can try to upgrade the version of gcc.

**Comment by hqho** [comment]
Is there a work around this if upgrading the gcc version is not an option?

**Comment by dg0yt** [comment]
You can try a clang++ version of the same age...

**Comment by hqho** [comment]
Can you tell me how to do this while running the bootstrap script?

**Comment by dg0yt** [comment]
Set standard environment variables: `CXX` in particular.

**Comment by hqho** [comment]
hh186013@2223-sles15sp4-aarch64:/gitspace/hh186013/suselinux-aarch64> export CXX=/usr/bin/g++-7
hh186013@2223-sles15sp4-aarch64:/gitspace/hh186013/suselinux-aarch64> env VCPKG_ROOT=$InstallDIR/vcpkg $InstallDIR/vcpkg/bootstrap-vcpkg.sh
Unable to determine a binary release of vcpkg; attempting to build from source.
Building vcpkg-tool...
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++-7 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting the C++ compiler in use
-- Detecting the C++ compiler in use - gcc
-- Version: 10.1.0
-- Build type: Release
-- Performing Test CPP_ATOMIC_BUILTIN
-- Performing Test CPP_ATOMIC_BUILTIN - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/build
[0/2] Re-checking globbed directories...
[137/217] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/sourceparagraph.cpp.o
FAILED: CMakeFiles/vcpkglib.dir/src/vcpkg/sourceparagraph.cpp.o
/usr/bin/g++-7 -DVCPKG_BASE_VERSION=2999-12-31 -DVCPKG_VERSION=unknownhash -D_FILE_OFFSET_BITS=64 -I/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/include -I_deps/fmt-src/include -I_cmrc/include -O3 -DNDEBUG -pthread -std=c++1z -Winvalid-pch -include /gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/build/CMakeFiles/vcpkglib.dir/cmake_pch.hxx -MD -MT CMakeFiles/vcpkglib.dir/src/vcpkg/sourceparagraph.cpp.o -MF CMakeFiles/vcpkglib.dir/src/vcpkg/sourceparagraph.cpp.o.d -o CMakeFiles/vcpkglib.dir/src/vcpkg/sourceparagraph.cpp.o -c /gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/sourceparagraph.cpp
/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/sourceparagraph.cpp: In function 'vcpkg::ExpectedL<std::unique_ptr<vcpkg::SourceParagraph> > vcpkg::parse_source_paragraph(vcpkg::StringView, vcpkg::Paragraph&&)':
/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/sourceparagraph.cpp:399:16: error: could not convert 'spgh' from 'std::unique_ptr<vcpkg::SourceParagraph>' to 'vcpkg::ExpectedL<std::unique_ptr<vcpkg::SourceParagraph> > {aka vcpkg::ExpectedT<std::unique_ptr<vcpkg::SourceParagraph>, vcpkg::LocalizedString>}'
         return spgh;
                ^~~~
/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/sourceparagraph.cpp: In function 'vcpkg::ExpectedL<std::unique_ptr<vcpkg::FeatureParagraph> > vcpkg::parse_feature_paragraph(vcpkg::StringView, vcpkg::Paragraph&&)':
/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/sourceparagraph.cpp:434:16: error: could not convert 'fpgh' from 'std::unique_ptr<vcpkg::FeatureParagraph>' to 'vcpkg::ExpectedL<std::unique_ptr<vcpkg::FeatureParagraph> > {aka vcpkg::ExpectedT<std::unique_ptr<vcpkg::FeatureParagraph>, vcpkg::LocalizedString>}'
         return fpgh;
                ^~~~
/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/sourceparagraph.cpp: In static member function 'static vcpkg::ExpectedL<std::unique_ptr<vcpkg::SourceControlFile> > vcpkg::SourceControlFile::parse_control_file(vcpkg::StringView, std::vector<std::map<std::__cxx11::basic_string<char>, std::pair<std::__cxx11::basic_string<char>, vcpkg::TextRowCol>, std::less<void> > >&&)':
/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/sourceparagraph.cpp:465:16: error: could not convert 'control_file' from 'std::unique_ptr<vcpkg::SourceControlFile>' to 'vcpkg::ExpectedL<std::unique_ptr<vcpkg::SourceControlFile> > {aka vcpkg::ExpectedT<std::unique_ptr<vcpkg::SourceControlFile>, vcpkg::LocalizedString>}'
         return control_file;
                ^~~~~~~~~~~~
[140/217] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/dependencies.cpp.o
FAILED: CMakeFiles/vcpkglib.dir/src/vcpkg/dependencies.cpp.o
/usr/bin/g++-7 -DVCPKG_BASE_VERSION=2999-12-31 -DVCPKG_VERSION=unknownhash -D_FILE_OFFSET_BITS=64 -I/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/include -I_deps/fmt-src/include -I_cmrc/include -O3 -DNDEBUG -pthread -std=c++1z -Winvalid-pch -include /gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/build/CMakeFiles/vcpkglib.dir/cmake_pch.hxx -MD -MT CMakeFiles/vcpkglib.dir/src/vcpkg/dependencies.cpp.o -MF CMakeFiles/vcpkglib.dir/src/vcpkg/dependencies.cpp.o.d -o CMakeFiles/vcpkglib.dir/src/vcpkg/dependencies.cpp.o -c /gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/dependencies.cpp
In file included from /usr/include/c++/7/memory:64:0,
                 from _deps/fmt-src/include/fmt/format.h:41,
                 from _deps/fmt-src/include/fmt/compile.h:11,
                 from /gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/include/vcpkg/base/fmt.h:15,
                 from /gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/include/pch.h:5,
                 from /gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/build/CMakeFiles/vcpkglib.dir/cmake_pch.hxx:5,
                 from <command-line>:0:
/usr/include/c++/7/bits/stl_construct.h: In instantiation of 'void std::_Construct(_T1*, _Args&& ...) [with _T1 = vcpkg::InstallPlanAction; _Args = {const vcpkg::InstallPlanAction&}]':
/usr/include/c++/7/bits/stl_uninitialized.h:83:18:   required from 'static _ForwardIterator std::__uninitialized_copy<_TrivialValueTypes>::__uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = __gnu_cxx::__normal_iterator<const vcpkg::InstallPlanAction*, std::vector<vcpkg::InstallPlanAction> >; _ForwardIterator = vcpkg::InstallPlanAction*; bool _TrivialValueTypes = false]'
/usr/include/c++/7/bits/stl_uninitialized.h:134:15:   required from '_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = __gnu_cxx::__normal_iterator<const vcpkg::InstallPlanAction*, std::vector<vcpkg::InstallPlanAction> >; _ForwardIterator = vcpkg::InstallPlanAction*]'
/usr/include/c++/7/bits/stl_uninitialized.h:289:37:   required from '_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = __gnu_cxx::__normal_iterator<const vcpkg::InstallPlanAction*, std::vector<vcpkg::InstallPlanAction> >; _ForwardIterator = vcpkg::InstallPlanAction*; _Tp = vcpkg::InstallPlanAction]'
/usr/include/c++/7/bits/stl_vector.h:331:31:   required from 'std::vector<_Tp, _Alloc>::vector(const std::vector<_Tp, _Alloc>&) [with _Tp = vcpkg::InstallPlanAction; _Alloc = std::allocator<vcpkg::InstallPlanAction>]'
/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/include/vcpkg/dependencies.h:93:12:   required from 'vcpkg::ExpectedHolder<T>::ExpectedHolder(Fwd&&) [with Fwd = vcpkg::ActionPlan&; typename std::enable_if<(! is_same_v<vcpkg::ExpectedHolder<T>, typename std::remove_cv<typename std::remove_reference<_SrcTuple>::type>::type>), int>::type <anonymous> = 0; T = vcpkg::ActionPlan]'
/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/include/vcpkg/base/expected.h:78:66:   required from 'vcpkg::ExpectedT<T, Error>::ExpectedT(ConvToT&&) [with ConvToT = vcpkg::ActionPlan&; typename std::enable_if<(is_convertible_v<ConvToT, T> && (! is_same_v<typename std::remove_reference<_SrcTuple>::type, Error>)), int>::type <anonymous> = 0; T = vcpkg::ActionPlan; Error = vcpkg::LocalizedString]'
/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/dependencies.cpp:2051:20:   required from here
/usr/include/c++/7/bits/stl_construct.h:75:7: error: use of deleted function 'vcpkg::InstallPlanAction::InstallPlanAction(const vcpkg::InstallPlanAction&)'
     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/dependencies.cpp:8:0:
/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/include/vcpkg/dependencies.h:37:9: note: declared here
         InstallPlanAction(const InstallPlanAction&) = delete;
         ^~~~~~~~~~~~~~~~~
[141/217] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/registries.cpp.o
FAILED: CMakeFiles/vcpkglib.dir/src/vcpkg/registries.cpp.o
/usr/bin/g++-7 -DVCPKG_BASE_VERSION=2999-12-31 -DVCPKG_VERSION=unknownhash -D_FILE_OFFSET_BITS=64 -I/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/include -I_deps/fmt-src/include -I_cmrc/include -O3 -DNDEBUG -pthread -std=c++1z -Winvalid-pch -include /gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/build/CMakeFiles/vcpkglib.dir/cmake_pch.hxx -MD -MT CMakeFiles/vcpkglib.dir/src/vcpkg/registries.cpp.o -MF CMakeFiles/vcpkglib.dir/src/vcpkg/registries.cpp.o.d -o CMakeFiles/vcpkglib.dir/src/vcpkg/registries.cpp.o -c /gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/registries.cpp
/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/registries.cpp: In lambda function:
/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/registries.cpp:777:24: error: could not convert 'res' from 'std::unique_ptr<{anonymous}::BuiltinGitRegistryEntry, std::default_delete<{anonymous}::BuiltinGitRegistryEntry> >' to 'vcpkg::ExpectedL<std::unique_ptr<vcpkg::RegistryEntry> > {aka vcpkg::ExpectedT<std::unique_ptr<vcpkg::RegistryEntry>, vcpkg::LocalizedString>}'
                 return res;
                        ^~~
/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/registries.cpp: In lambda function:
/gitspace/hh186013/suselinux-aarch64/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2024-07-10/src/vcpkg/registries.cpp:861:24: error: could not convert 'res' from 'std::unique_ptr<{anonymous}::FilesystemRegistryEntry, std::default_delete<{anonymous}::FilesystemRegistryEntry> >' to 'vcpkg::ExpectedL<std::unique_ptr<vcpkg::RegistryEntry> > {aka vcpkg::ExpectedT<std::unique_ptr<vcpkg::RegistryEntry>, vcpkg::LocalizedString>}'
                 return res;
                        ^~~
[150/217] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/tools.cpp.o
ninja: build stopped: subcommand failed.

**Comment by hqho** [comment]
What did I do wrong?

**Comment by dg0yt** [comment]
I suggested CXX because it is the way to choose a different compiler. If you choose the old compiler, you get the old result.

**Comment by hqho** [comment]
We are trying to build azure sdk for cpp and google cloud cpp on aarch64.  The minimum gcc complier version for these SDKs is 7.5.  Moving to a different version of the complier is not an option.  Looks like there is no workaround for gcc version 7.5.

**Comment by dg0yt** [comment]
At the moment you are building the `vcpkg` tool. This can use a different compiler than the vcpkg triplet/toolchain that will build the ports. So you don't need a workaround yet.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
