### ISSUE TITLE
Exporting Nuget Package Not Working

### ISSUE THREAD

**Issue by DM-christiangomez** [microsoft/vcpkg#4039]
I'm trying to export the protobuf library as a nuget package so that I can bounce my project between different machines without having to use vcpkg on each one, but when I export the library to a nuget package and install it as directed, when I try to (for instance) #include <google/protobuf/stubs/common.h>, it doesn't work. I've checked, and all the headers, dlls, and libs are inside of the nuget package, so it _did_ install, but my project won't recognize any attempts to reference the associated headers.

**Comment by ras0219-msft** [comment]
Thanks for posting!

First, could you check that:
- The vcxproj is using v140/v141
- You're targetting the same architecture as was exported in the NuGet package
- Your project works as expected with `vcpkg integrate install`, but then installing the NuGet package does not work

**Comment by DM-christiangomez** [comment]
1. Yep, the version is v140
2. I've tried both the x86 version and the x64 version and neither works
3. Yeah, when I run the project like normal (with protobuf windows x64 installed) it works perfectly. I then export that as a nuget package, install the package to my project, then uninstall the protobuf libraries from vcpkg to simulate moving to another machine, and it stops working.

**Comment by ras0219-msft** [comment]
Ok, the following worked for me:
1. `vcpkg install protobuf`
2. `vcpkg export protobuf --nuget`
3. Create new Empty Project in VS 2017
4. Add the NuGet package according to the output
5. Add a Source.cpp that just has `#include <google/protobuf/stubs/common.h>` and `main()`
6. Build for Debug/x86

I then ran `vcpkg install protobuf:x64-windows` and `vcpkg export protobuf:x64-windows --nuget`, swapped the packages (they will not work if installed simultaneously -- you need to do `vcpkg export protobuf protobuf:x64-windows` for that) and changed the configuration to x64 and it worked as well.

Do you have any other NuGet packages in your project that might conflict with the vcpkg exported one?

**Comment by DM-christiangomez** [comment]
Did you simulate switching to another system by removing your protobuf libraries from vcpkg? If I follow your directions directly, yes, it works, but only because the original vcpkg library is installed (when you right click on the <google/protobuf/stubs/common.h> and open, it opens the file in the vcpkg directory outside of the main project).

**Comment by ras0219-msft** [comment]
Aha; I had run `vcpkg integrate remove` instead of `vcpkg remove protobuf`. It looks like we are having a clash between the user-wide integration and the NuGet package (the package should take precedence).

For now, you can work around the issue by just running `vcpkg integrate remove`, but I'll look at getting a proper fix in soon.

**Comment by DM-christiangomez** [comment]
But if I just run `vcpkg integrate remove`, my code still refers to the protobuf library in the vcpkg area. The only way I have found to completely simulate moving to another machine is to run `vcpkg remove protobuf`, thus removing all references to the protobuf library in vcpkg, leaving the only way to refer to the library to be through the nuget package. And when I do that, it doesn't work.

**Comment by DM-christiangomez** [comment]
I think that did it! I'm going to try and run it on a separate computer to see if it actually worked now, so don't close the thread yet please, but it's looking promising... Thanks!

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen this issue.
