### ISSUE TITLE
[opencv] build failure with NVIDIA video codec

### ISSUE THREAD

**Issue by kauai68** [microsoft/vcpkg#40393]
### Operating system

Windows 10, x64

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
Download and copy include and lib files to your CUDA toolkit directory from here: https://developer.nvidia.com/nvidia-video-codec-sdk/download

.\vcpkg install opencv[OPENMP,CUDA,CUDNN]:x64-windows
build fails with a bug in NvEncoder.cpp (patch is attached)
```

### Failure logs

[fix_nvencoder.patch](https://github.com/user-attachments/files/16570446/fix_nvencoder.patch)

**Comment by greenozon** [comment]
Please include logs files with errors as well

**Comment by kauai68** [comment]
I don't have the error log available, but the attribute pixelBitDepthMinus8 doesn't exist in hevcConfig anymore. pIntializeParams->encodeConfig->encodeCodecConfig.hevcConfig.pixelBitDepthMinus8-------- Ursprüngliche Nachricht --------Von: Alex ***@***.***>Datum: So., 11. Aug. 2024, 08:21An: microsoft/vcpkg ***@***.***>Cc: kauai68 ***@***.***>, Author ***@***.***>Betreff: Re: [microsoft/vcpkg] [opencv] build failure with NVIDIA video codec (Issue #40393)
Please include logs files with errors as well

**Comment by JonLiu1993** [comment]
@kauai68, Could you please provide the steps to reproduce your error?
