### ISSUE TITLE
Prompt "A suitable version of 7zip was not found (required v24.6.0)" when installing

### ISSUE THREAD

**Issue by luo2430** [microsoft/vcpkg#40408]
**Describe the bug**

The latest version of 7-zip is 24.0.7, which I have installed in my computer.  When I was installing a package, it prompt "A suitable version of 7zip was not found (required v24.6.0)" and actually download the version 24.0.6 of 7-zip. I think it's supposed to be some code somewhere that misspells the numbers, but I didn't find the code for that in the source code.

**Environment**
- OS: Windows

**To Reproduce**
1. ./vcpkg install xxxx
2. See error

**Expected behavior**

It should prompt "A suitable version of 7zip was not found (required v24.0.6)" instead of "A suitable version of 7zip was not found (required v24.6.0)".

**Comment by greenozon** [comment]
This is old known issue..
eg:
https://github.com/microsoft/vcpkg/issues/39921#issuecomment-2231134159

**Comment by luo2430** [comment]
> This is old known issue.. eg: [#39921 (comment)](https://github.com/microsoft/vcpkg/issues/39921#issuecomment-2231134159) #26844 etc

Thanks for the heads up.

Wow, it looks like this was a problem a long time ago and I'm surprised it hasn't been fixed by now. Though it's not too big of a deal except for the extra copy of the software.

**Comment by FrankXie05** [comment]
Duplicated of https://github.com/microsoft/vcpkg/issues/39921
