### ISSUE TITLE
bzip2 un-downloadable - `bzip.org` domain expired

### ISSUE THREAD

**Issue by past-due** [Microsoft/vcpkg#4040]
It appears as though the bzip.org domain has expired. Until the owner renews it, attempting to download + build bzip2 with vcpkg will fail. This affects many ports (through the dependency tree).

I've mirrored things here: https://github.com/past-due/bzip2-mirror/releases/tag/v1.0.6

@ras0219-msft, @alexkaratarakis:
Is that sufficient for now, or is there a better place we can get the `bzip2-1.0.6.tar.gz` mirrored for vcpkg?

**Comment by ras0219-msft** [comment]
Fix is in master; thanks again!

This is sufficient for now, though it of course indicates that we need to find a way to solve this on a grander scale :)
