### ISSUE TITLE
[openvdb] Build error

### ISSUE THREAD

**Issue by fmg-thomas** [microsoft/vcpkg#40411]
Operating System: Ubuntu 24.04
Compiler: gcc
vcpkg version: 2022.06.15

trying to run `vcpkg install openvdb` (with `tbb` already installed)

**error:**

```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:83 (message):
    Command failed: /usr/bin/cmake /home/tomas-tetlaw/Dev/[redacted]/vcpkg/buildtrees/openvdb/src/b3c7429803-66ab1161d7.clean -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/tomas-tetlaw/Dev/[redacted]/vcpkg/packages/openvdb_x64-linux/debug -DOPENVDB_BUILD_UNITTESTS=OFF -DOPENVDB_BUILD_PYTHON_MODULE=OFF -DOPENVDB_ENABLE_3_ABI_COMPATIBLE=OFF -DUSE_GLFW3=ON -DOPENVDB_CORE_STATIC=1 -DOPENVDB_CORE_SHARED=0 -DOPENVDB_BUILD_VDB_PRINT=OFF -DOPENVDB_BUILD_VDB_VIEW=OFF -DOPENVDB_BUILD_VDB_RENDER=OFF -DOPENVDB_BUILD_VDB_LOD=OFF -DUSE_PKGCONFIG=OFF -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/tomas-tetlaw/Dev/[redacted]/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/home/tomas-tetlaw/Dev/[redacted]/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/home/tomas-tetlaw/Dev/[redacted]/vcpkg -D_VCPKG_INSTALLED_DIR=/home/tomas-tetlaw/Dev/[redacted]/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF
    Working Directory: /home/tomas-tetlaw/Dev/[redacted]/vcpkg/buildtrees/openvdb/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /home/tomas-tetlaw/Dev/[redacted]/vcpkg/buildtrees/openvdb/config-x64-linux-dbg-out.log
      /home/tomas-tetlaw/Dev/[redacted]/vcpkg/buildtrees/openvdb/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:250 (vcpkg_execute_required_process)
  ports/openvdb/portfile.cmake:36 (vcpkg_cmake_configure)
  scripts/ports.cmake:146 (include)


error: building openvdb:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openvdb
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openvdb]+Build+error
Include '[openvdb] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-06-15-b0f08e40f8e8752dd0b260138ee078bd9599559c
    vcpkg-scripts version: unknown

You can also use the prefilled template from /home/tomas-tetlaw/Dev/[redacted]/vcpkg/installed/vcpkg/issue_body.md.

```

**config-x64-linux-dbg-out.log:**

```
cat /home/tomas-tetlaw/Dev/[redacted]/vcpkg/buildtrees/openvdb/config-x64-linux-dbg-out.log
-- The CXX compiler identification is GNU 13.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMake Build Type: Debug
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.1") 
-- Configuring for OpenVDB Version 9.0.0
-- Configuring for OpenVDB ABI Version 9
-- ----------------------------------------------------
-- ------------- Configuring OpenVDBCore --------------
-- ----------------------------------------------------
-- Found Boost: /home/tomas-tetlaw/Dev/[redacted]/vcpkg/installed/x64-linux/include (found suitable version "1.79.0", minimum required is "1.70") found components: iostreams system regex 
-- Missed required Intel TBB component: tbb
--   one or both of:
   /home/tomas-tetlaw/Dev/[redacted]/vcpkg/installed/x64-linux/lib/libtbb.so.2
    /home/tomas-tetlaw/Dev/[redacted]/vcpkg/installed/x64-linux/debug/lib/libtbb_debug.so.2
   files must exist.
-- Missed required Intel TBB component: tbbmalloc
--   one or both of:
   /home/tomas-tetlaw/Dev/[redacted]/vcpkg/installed/x64-linux/lib/libtbbmalloc.so.2
    /home/tomas-tetlaw/Dev/[redacted]/vcpkg/installed/x64-linux/debug/lib/libtbbmalloc_debug.so.2
   files must exist.
-- Missed required Intel TBB component: tbbmalloc_proxy
--   one or both of:
   /home/tomas-tetlaw/Dev/[redacted]/vcpkg/installed/x64-linux/lib/libtbbmalloc_proxy.so.2
    /home/tomas-tetlaw/Dev/[redacted]/vcpkg/installed/x64-linux/debug/lib/libtbbmalloc_proxy_debug.so.2
   files must exist.
-- Configuring incomplete, errors occurred!

```
**config-x64-linux-dbg-err.log:**

```
CMake Warning at CMakeLists.txt:512 (message):
  Unable to find Jemalloc, attempting to fall back to TBB malloc.

          It is recommended to use Jemalloc for optimum performance.


CMake Error at /home/tomas-tetlaw/Dev/[redacted]/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package):
  Found package configuration file:

    /home/tomas-tetlaw/Dev/[redacted]/vcpkg/installed/x64-linux/share/tbb/TBBConfig.cmake

  but it set TBB_FOUND to FALSE so package "TBB" is considered to be NOT
  FOUND.
Call Stack (most recent call first):
  openvdb/openvdb/CMakeLists.txt:130 (find_package)

```

**Comment by greenozon** [comment]
Not able to reproduce the issue (Ubuntu 20.04 LTS)

<details><summary>Details</summary>
<p>

$ ./vcpkg install openvdb
Computing installation plan...
The following packages will be built and installed:
  * blosc:x64-linux@1.21.5
  * imath:x64-linux@3.1.11
  * libdeflate[compression,core,decompression,gzip,zlib]:x64-linux@1.21
  * openexr:x64-linux@3.2.3#1
    openvdb:x64-linux@11.0.0
  * snappy:x64-linux@1.2.1
  * tbb:x64-linux@2021.13.0
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Compiler found: /bin/c++
Restored 0 package(s) from /home/usr/.cache/vcpkg/archives in 538 us. Use --debug to see more details.
Installing 1/7 snappy:x64-linux@1.2.1...
Building snappy:x64-linux@1.2.1...
-- Downloading https://github.com/google/snappy/archive/1.2.1.tar.gz -> google-snappy-1.2.1.tar.gz...
-- Extracting source /home/usr/vcpkg/downloads/google-snappy-1.2.1.tar.gz
-- Applying patch fix_clang-cl_build.patch
-- Applying patch no-werror.patch
-- Applying patch pkgconfig.diff
-- Using source at /home/usr/vcpkg/buildtrees/snappy/src/1.2.1-9beee7c0e8.clean
-- Configuring x64-linux
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Fixing pkgconfig file: /home/usr/vcpkg/packages/snappy_x64-linux/lib/pkgconfig/snappy.pc
-- Fixing pkgconfig file: /home/usr/vcpkg/packages/snappy_x64-linux/debug/lib/pkgconfig/snappy.pc
-- Installing: /home/usr/vcpkg/packages/snappy_x64-linux/share/snappy/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 52.3 ms.
Elapsed time to handle snappy:x64-linux: 8.3 s
snappy:x64-linux package ABI: 976c1dceae5c44cc4646e941da75a798479074cc1666cea762194a5f5cb7adcc
Installing 2/7 blosc:x64-linux@1.21.5...
Building blosc:x64-linux@1.21.5...
-- Downloading https://github.com/Blosc/c-blosc/archive/v1.21.5.tar.gz -> Blosc-c-blosc-v1.21.5.tar.gz...
-- Extracting source /home/usr/vcpkg/downloads/Blosc-c-blosc-v1.21.5.tar.gz
-- Applying patch 0001-fix-CMake-config.patch
-- Using source at /home/usr/vcpkg/buildtrees/blosc/src/v1.21.5-e26f33ecea.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Installing: /home/usr/vcpkg/packages/blosc_x64-linux/share/blosc/copyright
-- Fixing pkgconfig file: /home/usr/vcpkg/packages/blosc_x64-linux/lib/pkgconfig/blosc.pc
-- Fixing pkgconfig file: /home/usr/vcpkg/packages/blosc_x64-linux/debug/lib/pkgconfig/blosc.pc
-- Performing post-build validation
Stored binaries in 1 destinations in 31.5 ms.
Elapsed time to handle blosc:x64-linux: 5.9 s
blosc:x64-linux package ABI: 71506e529ea5f41b7fe95fd515a55833ab2f45b7393f6dbd30ff5ecd56b16ba1
Installing 3/7 imath:x64-linux@3.1.11...
Building imath:x64-linux@3.1.11...
-- Downloading https://github.com/AcademySoftwareFoundation/Imath/archive/v3.1.11.tar.gz -> AcademySoftwareFoundation-Imath-v3.1.11.tar.gz...
-- Extracting source /home/usr/vcpkg/downloads/AcademySoftwareFoundation-Imath-v3.1.11.tar.gz
-- Using source at /home/usr/vcpkg/buildtrees/imath/src/v3.1.11-70a082b9c8.clean
-- Configuring x64-linux
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Fixing pkgconfig file: /home/usr/vcpkg/packages/imath_x64-linux/lib/pkgconfig/Imath.pc
-- Fixing pkgconfig file: /home/usr/vcpkg/packages/imath_x64-linux/debug/lib/pkgconfig/Imath.pc
-- Installing: /home/usr/vcpkg/packages/imath_x64-linux/share/imath/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 116 ms.
Elapsed time to handle imath:x64-linux: 7.1 s
imath:x64-linux package ABI: 041fad3ab7e1c72ad69d01400b9ff89d3bf7857edcc1e44d6663dea956bdb048
Installing 4/7 libdeflate[compression,core,decompression,gzip,zlib]:x64-linux@1.21...
Building libdeflate[compression,core,decompression,gzip,zlib]:x64-linux@1.21...
-- Downloading https://github.com/ebiggers/libdeflate/archive/v1.21.tar.gz -> ebiggers-libdeflate-v1.21.tar.gz...
-- Extracting source /home/usr/vcpkg/downloads/ebiggers-libdeflate-v1.21.tar.gz
-- Applying patch remove_wrong_c_flags_modification.diff
-- Using source at /home/usr/vcpkg/buildtrees/libdeflate/src/v1.21-9f072c60e7.clean
-- Configuring x64-linux
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Fixing pkgconfig file: /home/usr/vcpkg/packages/libdeflate_x64-linux/lib/pkgconfig/libdeflate.pc
-- Fixing pkgconfig file: /home/usr/vcpkg/packages/libdeflate_x64-linux/debug/lib/pkgconfig/libdeflate.pc
-- Installing: /home/usr/vcpkg/packages/libdeflate_x64-linux/share/libdeflate/copyright
-- Installing: /home/usr/vcpkg/packages/libdeflate_x64-linux/share/libdeflate/usage
-- Performing post-build validation
Stored binaries in 1 destinations in 48.7 ms.
Elapsed time to handle libdeflate:x64-linux: 6.1 s
libdeflate:x64-linux package ABI: b0a033ea315820a6171ce4f4c32e4277c9ac0b2614a2c564e44236184b529186
Installing 5/7 openexr:x64-linux@3.2.3#1...
Building openexr:x64-linux@3.2.3#1...
-- Downloading https://github.com/AcademySoftwareFoundation/openexr/archive/v3.2.3.tar.gz -> AcademySoftwareFoundation-openexr-v3.2.3.tar.gz...
-- Extracting source /home/usr/vcpkg/downloads/AcademySoftwareFoundation-openexr-v3.2.3.tar.gz
-- Applying patch fix-cmake-package.patch
-- Using source at /home/usr/vcpkg/buildtrees/openexr/src/v3.2.3-df0d4b286c.clean
-- Configuring x64-linux
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Fixing pkgconfig file: /home/usr/vcpkg/packages/openexr_x64-linux/lib/pkgconfig/OpenEXR.pc
-- Fixing pkgconfig file: /home/usr/vcpkg/packages/openexr_x64-linux/debug/lib/pkgconfig/OpenEXR.pc
-- Installing: /home/usr/vcpkg/packages/openexr_x64-linux/share/openexr/usage
-- Installing: /home/usr/vcpkg/packages/openexr_x64-linux/share/openexr/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 2.5 s.
Elapsed time to handle openexr:x64-linux: 1.8 min
openexr:x64-linux package ABI: 559a58a4634c3d19ddd6e481599ddd93db613c38eec2602042aec131db0be2f7
Installing 6/7 tbb:x64-linux@2021.13.0...
Building tbb:x64-linux@2021.13.0...
-- Downloading https://github.com/oneapi-src/oneTBB/archive/v2021.13.0.tar.gz -> oneapi-src-oneTBB-v2021.13.0.tar.gz...
-- Extracting source /home/usr/vcpkg/downloads/oneapi-src-oneTBB-v2021.13.0.tar.gz
-- Using source at /home/usr/vcpkg/buildtrees/tbb/src/v2021.13.0-c5ed208c36.clean
-- Configuring x64-linux
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Fixing pkgconfig file: /home/usr/vcpkg/packages/tbb_x64-linux/lib/pkgconfig/tbb.pc
-- Fixing pkgconfig file: /home/usr/vcpkg/packages/tbb_x64-linux/debug/lib/pkgconfig/tbb.pc
-- Installing: /home/usr/vcpkg/packages/tbb_x64-linux/share/tbb/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 801 ms.
Elapsed time to handle tbb:x64-linux: 27 s
tbb:x64-linux package ABI: 3b3ff085c27b6da047664937837aba9a083b3a8afad9199bbd3d9b7c5bebae1e
Installing 7/7 openvdb:x64-linux@11.0.0...
Building openvdb:x64-linux@11.0.0...
-- Downloading https://github.com/AcademySoftwareFoundation/openvdb/archive/v11.0.0.tar.gz -> AcademySoftwareFoundation-openvdb-v11.0.0.tar.gz...
-- Extracting source /home/usr/vcpkg/downloads/AcademySoftwareFoundation-openvdb-v11.0.0.tar.gz
-- Applying patch fix_cmake.patch
-- Applying patch fix_nanovdb.patch
-- Using source at /home/usr/vcpkg/buildtrees/openvdb/src/v11.0.0-677e16da9c.clean
-- Configuring x64-linux
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Installing: /home/usr/vcpkg/packages/openvdb_x64-linux/share/openvdb/usage
-- Installing: /home/usr/vcpkg/packages/openvdb_x64-linux/share/openvdb/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 5 s.
Elapsed time to handle openvdb:x64-linux: 4.3 min
openvdb:x64-linux package ABI: 9dc66045c29152fca6cdefdb39f26ee6c92345e9353eb7477422160942b791de
Total install time: 7 min
The package openvdb provides CMake targets:

    find_package(OpenVDB CONFIG REQUIRED)
    target_link_libraries(main PRIVATE OpenVDB::openvdb)

07:09:29 usr@tplevo347:~/vcpkg (master U:1 ✗)
      ▶  $ ./vcpkg install openvdb
Computing installation plan...
The following packages are already installed:
    openvdb:x64-linux@11.0.0
openvdb:x64-linux is already installed
Total install time: 16.3 us
The package openvdb provides CMake targets:

    find_package(OpenVDB CONFIG REQUIRED)
    target_link_libraries(main PRIVATE OpenVDB::openvdb)


</p>
</details> 

I'd suggest to re-install TBB library using vcpkg

**Comment by fmg-thomas** [comment]
@greenozon I can't upgrade as we need this specific version. Is there anything I can change to get this to build with 2022.06.15?

**Comment by WangWeiLin-MV** [comment]
If stay in old version, could be modified the `portfile.cmake` directly to fix some issue.
Or on the latest version with [Overlay ports](https://learn.microsoft.com/en-us/vcpkg/concepts/overlay-ports) to specify the port for a specific version, see [Tutorial: Install a specific version of a package](https://learn.microsoft.com/en-us/vcpkg/consume/lock-package-versions?tabs=inspect-powershell#5---force-a-specific-version)

**Comment by fmg-thomas** [comment]
@WangWeiLin-MV should it not be using the versions from `2022.06.15` already?

**Comment by WangWeiLin-MV** [comment]
It's recommend using the latest version of vcpkg, and you could install specific version of port by the way mentioned above.
We currently do not maintain old versions of ports, but you can be fixed by modifying `ports/openvdb/portfile.cmake`.
