### ISSUE TITLE
[shiftmedia-libgnutls] Add release dll on debug when compile with ngtcp2 and gnutls

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#40414]
### Operating system

windows gitgub action ci

### Compiler

msvc

### Steps to reproduce the behavior

```Shell
./vcpkg install brotli zlib zstd libpsl nghttp2 shiftmedia-libgnutls libssh2 pkgconf gsasl ngtcp2[gnutls] nghttp3

# curl cmake
cmake -DENABLE_DEBUG=ON -DENABLE_UNICODE=OFF -DCURL_USE_SCHANNEL=OFF -DCURL_BROTLI=ON -DCURL_ZSTD=ON -DCURL_USE_LIBPSL=ON -DUSE_NGHTTP2=ON -DBUILD_SHARED_LIBS=OFF -DCURL_USE_LIBSSH2=ON -DCURL_USE_GNUTLS=ON -DCURL_USE_GSASL=ON -DUSE_NGTCP2=ON
```
https://github.com/curl/curl/pull/14495
```


### Failure logs

> @talregev There is an issue with GnuTLS + ngtcp2 which looks vcpkg-related:
>
> When building in Debug mode, curl.exe gets linked with gnutlsd.dll
(the debug GnuTLS DLL), plus ngtcp2.dll. Which in turn pulls in
ngtcp2_crypto_gnutls.dll, which in turn pulls in the release version
of gnutls.dll. This release mode DLL is not copied automatically next to
curl.exe, so it fails to launch.



### Additional context

https://github.com/curl/curl/pull/14495

**Comment by dg0yt** [comment]
Well, you added shiftmedia-libgnutls to port ngtcp2, but it is unclear if this was ever expected to work.

How does ngtcp2 find GnuTLS? Using CMake's find module.

Will the find module find the right import lib for each build tyoe? Let's check the installed names:
~~~
shiftmedia-libgnutls:x64-windows:/debug/lib/gnutlsd.lib
shiftmedia-libgnutls:x64-windows:/lib/gnutls.lib
~~~
No, the debug config won't be found!

Task: Add a vcpkg-cmake-wrapper for `GnuTLS` to port `shiftmedia-libgnutls`.

Hint: Start with adding GnuTLS to the tested packages in `scripts/tests/cmake-user`. It should report a debug/release mismatch.

**Comment by talregev** [comment]
Maybe it also happen with wolfssl and ngtcp2.

**Comment by dg0yt** [comment]
ngtcp2 uses wolfssl CMake config. This should be safe.

**Comment by talregev** [comment]
> Well, you added shiftmedia-libgnutls to port ngtcp2, but it is unclear if this was ever expected to work.
> 
> How does ngtcp2 find GnuTLS? Using CMake's find module.
> 
> Will the find module find the right import lib for each build type? Let's check the installed names:
> 
> ```
> shiftmedia-libgnutls:x64-windows:/debug/lib/gnutlsd.lib
> shiftmedia-libgnutls:x64-windows:/lib/gnutls.lib
> ```
> 
> No, the debug config won't be found!
> 
> Task: Add a vcpkg-cmake-wrapper for `GnuTLS` to port `shiftmedia-libgnutls`.
> 
> Hint: Start with adding GnuTLS to the tested packages in `scripts/tests/cmake-user`. It should report a debug/release mismatch.

Can you fix it? :)

**Comment by dg0yt** [comment]
I do not want to improve shiftmedia-libgnutls at the moment.

**Comment by dg0yt** [comment]
Remove `curl` from the title. It is not a curl issue. Every downstream use of `FindGnuTLS.cmake` can become a victim of shiftmedia-libgnutls' debug suffix.

**Comment by talregev** [comment]
I remove. Thank you for your time to investigate this problem.

**Comment by talregev** [comment]
> I do not want to improve shiftmedia-libgnutls at the moment.

shiftmedia-libgnutls  is now tested with curl tests.

**Comment by dg0yt** [comment]
> shiftmedia-libgnutls is now tested with curl tests.

This bug report is about the debug configuration. CURL's workaround was to use the release config. Did they change it again?

**Comment by talregev** [comment]
> > shiftmedia-libgnutls is now tested with curl tests.
> 
> This bug report is about the debug configuration. CURL's workaround was to use the release config. Did they change it again?

No.
I just mention because you write before that you don't know the state of the port shiftmedia-libgnutls. and you write here that you don't want to improve shiftmedia-libgnutls.

I just mention that now curl test this port on their ci, and we can estimate how good the port is.
And if there is a problem with curl side, they can know, and work with shiftmedia-libgnutls upstream to improve it.

**Comment by dg0yt** [comment]
> adding GnuTLS to the tested packages in `scripts/tests/cmake-user`.

https://github.com/microsoft/vcpkg/pull/40473

> It should report a debug/release mismatch.

Confirmed:

~~~
CMake Error at CMakeLists.txt:81 (message):
  Release lib for 'Debug' build: D:/installed/x64-windows/lib/gnutls.lib
~~~
