### ISSUE TITLE
crashpad build failure

### ISSUE THREAD

**Issue by chad171** [microsoft/vcpkg#40415]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
MSVC cannot link properly to crashpad when in any release build when using cmake and vcpkg.

-------CMakePresets.json------
{
  "version": 4,
  "cmakeMinimumRequired": {
    "major": 3,
    "minor": 19,
    "patch": 0
  },
  "configurePresets": [
    {
      "name": "windows-release",
      "generator": "Visual Studio 17 2022",
      "binaryDir": "${sourceDir}/out/build/windows-release",
      "cacheVariables": {
        "CMAKE_BUILD_TYPE": "Release",
        "VCPKG_TARGET_TRIPLET": "x64-windows",
        "CMAKE_TOOLCHAIN_FILE": "${sourceDir}/vcpkg/scripts/buildsystems/vcpkg.cmake"
      }
    }
  ],
  "buildPresets": [
    {
      "name": "windows-release-build",
      "configurePreset": "windows-release"
    }
  ]
}

-----CMakeLists.txt ----------------------
cmake_minimum_required(VERSION 3.15)

# Define your project
project(CrashpadDemo)

# Use vcpkg's toolchain file
set(CMAKE_TOOLCHAIN_FILE "${CMAKE_SOURCE_DIR}/vcpkg/scripts/buildsystems/vcpkg.cmake")

# Set C++ standard
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Add the executable
add_executable(CrashpadDemo main.cpp)

# Link Crashpad libraries
find_package(crashpad CONFIG REQUIRED)
target_link_libraries(CrashpadDemo PRIVATE crashpad::crashpad)

------------vcpkg.json -------------------------
{
    "name": "crashpad-demo",
    "version": "1.0.0",
    "dependencies": [
      "crashpad"
    ]
  }
  

----------main.cpp------------------------------
#include <crashpad/client/crashpad_client.h>
#include <crashpad/client/crashpad_info.h>
#include <iostream>

void causeCrash() {
    int* ptr = nullptr;
    *ptr = 42; // This will crash.
}

int main() {
    // Initialize Crashpad
    // Path where crashpad stores crash reports before uploading.
    base::FilePath db_path(L"Crashpad");

    // Path to the Crashpad handler executable.
    base::FilePath handler_path(L"crashpad_handler.exe");

    // URL to your Crashpad server.
    std::string server_url = "";
    std::vector<std::string> arguments;

    crashpad::CrashpadClient client;

    if (!client.StartHandler(handler_path,
                             db_path,
                             db_path,
                             server_url,
                             {},
                             {},
                             true,
                             true)) {
        std::cerr << "Failed to start Crashpad handler." << std::endl;
        return 1;
    }

    crashpad::CrashpadInfo* crashpad_info = crashpad::CrashpadInfo::GetCrashpadInfo();
    crashpad_info->set_crashpad_handler_behavior(crashpad::TriState::kEnabled);

    std::cout << "Crashpad is initialized. Crashing now..." << std::endl;

    causeCrash(); // Cause a crash

    return 0;
}
```

### Failure logs

PS C:\coding\code_for_fun\crashpad_vcpkg_demo> cmake --preset windows-release
Preset CMake variables:

  CMAKE_BUILD_TYPE="Release"
  CMAKE_TOOLCHAIN_FILE="C:/coding/code_for_fun/crashpad_vcpkg_demo/vcpkg/scripts/buildsystems/vcpkg.cmake"
  VCPKG_TARGET_TRIPLET="x64-windows"

-- Running vcpkg install
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe
The following packages will be built and installed:
    crashpad:x64-windows@2024-04-11#1
  * curl[core,non-http,schannel,ssl,sspi]:x64-windows@8.9.1
  * vcpkg-cmake:x64-windows@2024-04-23
  * vcpkg-cmake-config:x64-windows@2024-05-23
  * vcpkg-cmake-get-vars:x64-windows@2023-12-31
  * vcpkg-gn:x64-windows@2024-02-22
  * vcpkg-tool-gn:x64-windows@2024-02-22
  * zlib:x64-windows@1.3.1
Additional packages (*) will be modified to complete this operation.
Restored 8 package(s) from C:\Users\Chad\AppData\Local\vcpkg\archives in 369 ms. Use --debug to see more details.
Installing 1/8 vcpkg-cmake:x64-windows@2024-04-23...
Elapsed time to handle vcpkg-cmake:x64-windows: 3.34 ms
vcpkg-cmake:x64-windows package ABI: 2a0f6a2d855a4164e32eb75c7376fe6bf9ea3485d9809b29a0ec9c23c5c3e3d1
Installing 2/8 zlib:x64-windows@1.3.1...
Elapsed time to handle zlib:x64-windows: 5.03 ms
zlib:x64-windows package ABI: 42a57d49b5f89e1d4006374fa290d6f2eb01ca7b1c8bab9cc99a2eaf59f1eb43
Installing 3/8 vcpkg-tool-gn:x64-windows@2024-02-22...
Elapsed time to handle vcpkg-tool-gn:x64-windows: 3.52 ms
vcpkg-tool-gn:x64-windows package ABI: b4134a2bad645ed564894cf1c6ec891f446ed5517eb7d1547aa1d97a6bedff81
Installing 4/8 vcpkg-gn:x64-windows@2024-02-22...
Elapsed time to handle vcpkg-gn:x64-windows: 2.7 ms
vcpkg-gn:x64-windows package ABI: 4057ff7e28626fc8aacda2a80f7eaeb23484a2f46ba222a4e818b6bb17314db3
Installing 5/8 vcpkg-cmake-get-vars:x64-windows@2023-12-31...
Elapsed time to handle vcpkg-cmake-get-vars:x64-windows: 3.09 ms
vcpkg-cmake-get-vars:x64-windows package ABI: ce2ed716e1677d65b4e6a940f2b58cd4f95f2f126202da24d83bf9ae5b55deca
Installing 6/8 vcpkg-cmake-config:x64-windows@2024-05-23...
Elapsed time to handle vcpkg-cmake-config:x64-windows: 2.71 ms
vcpkg-cmake-config:x64-windows package ABI: 32421728ca7fca59ac93ffc023211a23962e31933dfb3504f70e95d2449d19cc
Installing 7/8 curl[core,non-http,schannel,ssl,sspi]:x64-windows@8.9.1...
Elapsed time to handle curl:x64-windows: 11 ms
curl:x64-windows package ABI: 9e2bcf9f5f18d35cd0e0e3ba27e42d2d21a673d35d9d5c5961cb92d60a24afb3
Installing 8/8 crashpad:x64-windows@2024-04-11#1...
Elapsed time to handle crashpad:x64-windows: 48.2 ms
crashpad:x64-windows package ABI: 968b1ecce3d534294dc41874ad1baef4b3efb0704ea31d27819144a289d9259e
Total install time: 79.7 ms
crashpad provides CMake targets:

  # this is heuristically generated, and may not be correct
  find_package(crashpad CONFIG REQUIRED)
  target_link_libraries(main PRIVATE crashpad::crashpad)

-- Running vcpkg install - done
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
-- The C compiler identification is MSVC 19.40.33813.0
-- The CXX compiler identification is MSVC 19.40.33813.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: optimized;C:/coding/code_for_fun/crashpad_vcpkg_demo/out/build/windows-release/vcpkg_installed/x64-windows/lib/zlib.lib;debug;C:/coding/code_for_fun/crashpad_vcpkg_demo/out/build/windows-release/vcpkg_installed/x64-windows/debug/lib/zlibd.lib (found version "1.3.1")  
-- Configuring done (4.5s)
-- Generating done (0.0s)
-- Build files have been written to: C:/coding/code_for_fun/crashpad_vcpkg_demo/out/build/windows-release
PS C:\coding\code_for_fun\crashpad_vcpkg_demo> cmake --build --preset windows-release-build
MSBuild version 17.10.4+10fbfbf2e for .NET Framework

  1>Checking Build System
  Building Custom Rule C:/coding/code_for_fun/crashpad_vcpkg_demo/CMakeLists.txt
  main.cpp
common.lib(common.crashpad_info.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
common.lib(common.crashpad_info.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
client.lib(client.crashpad_client_win.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
client.lib(client.crashpad_client_win.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.scoped_handle.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.scoped_handle.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.random_string.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.random_string.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.command_line.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.command_line.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.critical_section_with_debug_info.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.critical_section_with_debug_info.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.get_function.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.get_function.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.handle.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.handle.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.initial_client_data.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.initial_client_data.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.ntstatus_logging.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.ntstatus_logging.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.process_info.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.process_info.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.registration_protocol_win.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.registration_protocol_win.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.scoped_process_suspend.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.scoped_process_suspend.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.file_io.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.file_io.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.string_number_conversion.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.string_number_conversion.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.split_string.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.split_string.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.aligned_allocator.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.aligned_allocator.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.scoped_local_alloc.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.scoped_local_alloc.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.file_io_win.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
util.lib(util.file_io_win.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
base.lib(base.file_path.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
base.lib(base.file_path.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
base.lib(base.logging.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
base.lib(base.logging.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
base.lib(base.stringprintf.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
base.lib(base.stringprintf.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
base.lib(base.utf_string_conversions.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
base.lib(base.utf_string_conversions.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
base.lib(base.rand_util.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
base.lib(base.rand_util.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
base.lib(base.string_util_win.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
base.lib(base.string_util_win.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
base.lib(base.utf_string_conversion_utils.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
base.lib(base.utf_string_conversion_utils.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\Debug\CrashpadDemo.exe : fatal error LNK1319: 52 mismatches detected [C:\coding\code_for_fun\crashpad_vcpkg_demo\out\build\windows-release\CrashpadDemo.vcxproj]
PS C:\coding\code_for_fun\crashpad_vcpkg_demo> 

### Additional context

You can manually change the link lib in the vcxproj file to the non debug versions and a project will compile properly.

**Comment by LilyWangLL** [comment]
I can repro this issue locally.

**Comment by 9241304** [comment]
I have the same problem with RelWithDebInfo config (I can`t check Release config in my project)

After small investigation I see this in linker log:

`"..\VCPKG_INSTALLED\X64-WINDOWS\LIB\SPDLOG.LIB" "..\VCPKG_INSTALLED\X64-WINDOWS\LIB\LIBPNG16.LIB" "..\VCPKG_INSTALLED\X64-WINDOWS\LIB\LCMS2.LIB" "..\VCPKG_INSTALLED\X64-WINDOWS\LIB\FMT.LIB" "..\VCPKG_INSTALLED\X64-WINDOWS\LIB\ZLIB.LIB" "..\VCPKG_INSTALLED\X64-WINDOWS\**DEBUG**\LIB\COMMON.LIB" "..\VCPKG_INSTALLED\X64-WINDOWS\**DEBUG**\LIB\CLIENT.LIB" "..\VCPKG_INSTALLED\X64-WINDOWS\**DEBUG**\LIB\UTIL.LIB" "..\VCPKG_INSTALLED\X64-WINDOWS\**DEBUG**\LIB\BASE.LIB" KERNEL32.LIB USER32.LIB`

It tries to link crashpad debug libs.
