### ISSUE TITLE
[curl] curl-config doesn't work correctly without setting $prefix variable on Linux

### ISSUE THREAD

**Issue by swt2c** [microsoft/vcpkg#40434]
**Describe the bug**
libcurl's helper tool `curl-config` doesn't work correctly unless you set the ${prefix} environment variable beforehand.

**Environment**
- OS: Linux
- Compiler: gcc (GCC) 14.2.1 20240801 (Red Hat 14.2.1-1)

**To Reproduce**
1. ./vcpkg install curl
2. run `~/.local/share/vcpkg/packages/curl_x64-linux/tools/curl/bin/curl-config --cflags`
3. Observe that the cflags do not include the appropriate paths.

**Expected behavior**
curl-config shows the appropriate flags without having to set external variables yourself.

**Comment by FrankXie05** [comment]
@swt2c Thanks for posting this issue, Do you mean the full path should be shown here? :)
```
Frank@vcpkg:~/vcpkg$ ./packages/curl_x64-linux/tools/curl/bin/curl-config --cflags
-DCURL_STATICLIB -I/include

```

**Comment by dg0yt** [comment]
https://github.com/microsoft/vcpkg/pull/40443. 
`curl-config` is legacy. Consider switching to `pkg-config`.

**Comment by swt2c** [comment]
> @swt2c Thanks for posting this issue, Do you mean the full path should be shown here? :)
> 
> ```
> Frank@vcpkg:~/vcpkg$ ./packages/curl_x64-linux/tools/curl/bin/curl-config --cflags
> -DCURL_STATICLIB -I/include
> ```

Yes.

> #40443. `curl-config` is legacy. Consider switching to `pkg-config`.

Thanks for the PR.  It is?  Seems to be still recommended by official documentation:
https://curl.se/libcurl/using/

**Comment by dg0yt** [comment]
> It is? Seems to be still recommended by official documentation:
> https://curl.se/libcurl/using/

Well, opinion ;-) 
In vcpkg, pkg-config is used for all toolchains including MSVC, but shell config scripts usally don't work well for the Windows platform. For some ports, the shell config scripts are omitted.
