### ISSUE TITLE
[log4cxx] build failure

### ISSUE THREAD

**Issue by greenozon** [microsoft/vcpkg#40454]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
vcpkg install log4cxx
```

### Failure logs

c:\Dev\vcpkg> vcpkg install log4cxx
Computing installation plan...
The following packages will be built and installed:
    log4cxx:x64-windows@1.2.0
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Dev/VS2019/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from C:\Users\user\AppData\Local\vcpkg\archives in 299 us. Use --debug to see more details.
Installing 1/1 log4cxx:x64-windows@1.2.0...
Building log4cxx:x64-windows@1.2.0...
-- Using cached apache-log4cxx-1.2.0.tar.gz.
-- Cleaning sources at C:/Dev/vcpkg/buildtrees/log4cxx/src/-log4cxx-1-7191328f13.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Dev/vcpkg/downloads/apache-log4cxx-1.2.0.tar.gz
-- Applying patch fix-find-package.patch
-- Using source at C:/Dev/vcpkg/buildtrees/log4cxx/src/-log4cxx-1-7191328f13.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/Dev/vcpkg/downloads/tools/cmake-3.29.2-windows/cmake-3.29.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: C:/Dev/vcpkg/buildtrees/log4cxx/x64-windows-dbg
    See logs for more information:
      C:\Dev\vcpkg\buildtrees\log4cxx\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/log4cxx/portfile.cmake:20 (vcpkg_cmake_install)
  scripts/ports.cmake:192 (include)

error: building log4cxx:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle log4cxx:x64-windows: 1.3 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+log4cxx
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[log4cxx]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2FDev%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

FAILED: src/main/cpp/CMakeFiles/log4cxx.dir/stringhelper.cpp.obj 
C:\Dev\VS2019\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe   /TP -DLOG4CXX -Dlog4cxx_EXPORTS -IC:\Dev\vcpkg\buildtrees\log4cxx\x64-windows-dbg\src\main\include -IC:\Dev\vcpkg\buildtrees\log4cxx\src\-log4cxx-1-7191328f13.clean\src\main\include -external:IC:\Dev\vcpkg\installed\x64-windows\include -external:W0 /nologo /DWIN32 /D_WINDOWS /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++20 /showIncludes /Fosrc\main\cpp\CMakeFiles\log4cxx.dir\stringhelper.cpp.obj /Fdsrc\main\cpp\log4cxx.pdb /FS -c C:\Dev\vcpkg\buildtrees\log4cxx\src\-log4cxx-1-7191328f13.clean\src\main\cpp\stringhelper.cpp
cl : Command line error D8037 : cannot create temporary il file; clean temp directory of old il files

Full logs:
[install-x64-windows-dbg-out.log](https://github.com/user-attachments/files/16618752/install-x64-windows-dbg-out.log)

**Comment by LilyWangLL** [comment]
This error is due to there is not enough space to create temporary compiler intermediate files. Please check the space of system disk.
Duplicate of https://github.com/microsoft/vcpkg/issues/17998.

**Comment by greenozon** [comment]
yeah, good catch @LilyWangLL 
thanks, closing
