### ISSUE TITLE
tbb build fails on linux

### ISSUE THREAD

**Issue by githubkusi** [Microsoft/vcpkg#4047]
The port tries to use msbuild, which is obviously not available under linux

- Machine setup: Opensuse 15.0. I know that Opensuse is not a supported platform, but I was so far able to successfully build more than 50 packages with vcpkg under Opensuse. So it should work in general.
- steps to reproduce: in a bash shell:  ./vcpkg install tbb
- log files were empty

Error message:

$ ./vcpkg install tbb
The following packages will be built and installed:
    tbb[core]:x64-linux
Starting package 1/1: tbb:x64-linux
Building package tbb[core]:x64-linux... 
-- Warning: Static building not supported yet. Building dynamic.
-- Using cached /home/kusi/develop/vcpkg/vcpkg/downloads/01org-tbb-2018_U5.tar.gz
-- Using source at /home/kusi/develop/vcpkg/vcpkg/buildtrees/tbb/src/2018_U5-94342757ca
-- Building /home/kusi/develop/vcpkg/vcpkg/buildtrees/tbb/src/2018_U5-94342757ca/build/vs2013/makefile.sln for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: msbuild;/home/kusi/develop/vcpkg/vcpkg/buildtrees/tbb/src/2018_U5-94342757ca/build/vs2013/makefile.sln;/p:Configuration=Release;/t:Rebuild;/p:Platform=x64;/p:PlatformToolset=external;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No;/p:WindowsTargetPlatformVersion=;/m
    Working Directory: /home/kusi/develop/vcpkg/vcpkg/buildtrees/tbb/x64-linux-rel
    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:119 (vcpkg_execute_required_process)
  ports/tbb/portfile.cmake:25 (vcpkg_build_msbuild)
  scripts/ports.cmake:71 (include)

Error: Building package tbb:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: tbb:x64-linux
  Vcpkg version: 0.0.113-unknownhash

**Comment by Voskrese** [comment]
`x64-linux` - `vs2013/makefile.sln` ?

apparently the port is not for linux

**Comment by sanxiyn** [comment]
TBB works fine on Linux, see https://packages.debian.org/sid/libtbb-dev. vcpkg's TBB port just needs to support Linux, this is not `needs-repro`.

**Comment by wangli28** [comment]
Please open a new issue if this is still a problem for you.
