### ISSUE TITLE
[#5] error: building bzip2:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by running-az** [microsoft/vcpkg#40481]
### Operating system

windows10

### Compiler

Visual Studio Community 2022

### Steps to reproduce the behavior

```Shell
vcpkg install tesseract
```

### Failure logs

**vcpkg-master\installed\vcpkg\issue_body.md:**
Package: bzip2[core,tool]:x64-windows@1.0.8#5

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.41.34120.0
-    vcpkg-tool version: 2024-08-01-fd884a0d390d12783076341bd43d77c3a6a15658
    vcpkg-scripts version: unknown

**To Reproduce**

`vcpkg install tesseract`

**Failure logs**

```
-- Using cached bzip2-1.0.8.tar.gz.
-- Cleaning sources at D:/ALL/vcpkg-master/buildtrees/bzip2/src/bzip2-1-336d4794a3.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/ALL/vcpkg-master/downloads/bzip2-1.0.8.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Using source at D:/ALL/vcpkg-master/buildtrees/bzip2/src/bzip2-1-336d4794a3.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig file: D:/ALL/vcpkg-master/packages/bzip2_x64-windows/lib/pkgconfig/bzip2.pc
-- Downloading https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst -> msys2-mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst...

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: no such file or directory
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
      

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_acquire_msys.cmake:25 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_acquire_msys.cmake:124 (z_vcpkg_acquire_msys_download_package)
  scripts/cmake/vcpkg_acquire_msys.cmake:212 (z_vcpkg_acquire_msys_download_packages)
  scripts/cmake/vcpkg_find_acquire_program(PKGCONFIG).cmake:52 (vcpkg_acquire_msys)
  scripts/cmake/vcpkg_find_acquire_program.cmake:121 (include)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:193 (vcpkg_find_acquire_program)
  ports/bzip2/portfile.cmake:53 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:192 (include)



```

vcpkg install tesseract
Computing installation plan...
The following packages will be built and installed:
  * bzip2[core,tool]:x64-windows@1.0.8#5
  * curl[core,non-http,schannel,ssl,sspi]:x64-windows@8.9.1
  * leptonica:x64-windows@1.84.1#1
  * libarchive[bzip2,core,crypto,libxml2,lz4,lzma,zstd]:x64-windows@3.7.4
  * libiconv:x64-windows@1.17#4
  * libjpeg-turbo:x64-windows@3.0.3
  * liblzma:x64-windows@5.6.2
  * libpng:x64-windows@1.6.43#3
  * libwebp[core,libwebpmux,nearlossless,simd,unicode]:x64-windows@1.4.0#1
  * libxml2[core,iconv,lzma,zlib]:x64-windows@2.11.9
  * lz4:x64-windows@1.10.0
  * openjpeg:x64-windows@2.5.2#1
  * openssl:x64-windows@3.3.1#1
    tesseract:x64-windows@5.4.1
  * tiff[core,jpeg,lzma,zip]:x64-windows@4.6.0#4
  * vcpkg-cmake-get-vars:x64-windows@2023-12-31
  * zlib:x64-windows@1.3.1
  * zstd:x64-windows@1.5.6
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Compiler found: D:/VS2022Community/VisualStudioCommunity/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from C:\Users\xingzesheng\AppData\Local\vcpkg\archives in 436 us. Use --debug to see more details.
Installing 1/18 bzip2[core,tool]:x64-windows@1.0.8#5...
Building bzip2[core,tool]:x64-windows@1.0.8#5...
-- Using cached bzip2-1.0.8.tar.gz.
-- Cleaning sources at D:/ALL/vcpkg-master/buildtrees/bzip2/src/bzip2-1-336d4794a3.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/ALL/vcpkg-master/downloads/bzip2-1.0.8.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Using source at D:/ALL/vcpkg-master/buildtrees/bzip2/src/bzip2-1-336d4794a3.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig file: D:/ALL/vcpkg-master/packages/bzip2_x64-windows/lib/pkgconfig/bzip2.pc
-- Downloading https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst -> msys2-mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst...

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: no such file or directory
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_acquire_msys.cmake:25 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_acquire_msys.cmake:124 (z_vcpkg_acquire_msys_download_package)
  scripts/cmake/vcpkg_acquire_msys.cmake:212 (z_vcpkg_acquire_msys_download_packages)
  scripts/cmake/vcpkg_find_acquire_program(PKGCONFIG).cmake:52 (vcpkg_acquire_msys)
  scripts/cmake/vcpkg_find_acquire_program.cmake:121 (include)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:193 (vcpkg_find_acquire_program)
  ports/bzip2/portfile.cmake:53 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:192 (include)

error: building bzip2:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle bzip2:x64-windows: 12 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+bzip2
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[bzip2]+Build+error+on+x64-windows&body=Copy+issue+body+from+D%3A%2F%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86%2FOCRmyPDF%2FALL%2Fvcpkg-master%2Finstalled%2Fvcpkg%2Fissue_body.md

**vcpkg-master\buildtrees\detect_compiler\config-x64-windows-out.log：**
[1/1] "D:/ALL/vcpkg-master/downloads/tools/cmake-3.29.2-windows/cmake-3.29.2-windows-i386/bin/cmake.exe" -E chdir ".." "D:/ALL/vcpkg-master/downloads/tools/cmake-3.29.2-windows/cmake-3.29.2-windows-i386/bin/cmake.exe" "D:/ALL/vcpkg-master/scripts/detect_compiler" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=D:/ALL/vcpkg-master/packages/detect_compiler_x64-windows" "-DCMAKE_MAKE_PROGRAM=D:/VS2022Community/VisualStudioCommunity/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/ALL/vcpkg-master/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v143" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=D:/ALL/vcpkg-master/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=D:/ALL/vcpkg-master" "-DZ_VCPKG_ROOT_DIR=D:/ALL/vcpkg-master" "-D_VCPKG_INSTALLED_DIR=D:/ALL/vcpkg-master/installed" "-DVCPKG_MANIFEST_INSTALL=OFF"
-- The C compiler identification is MSVC 19.41.34120.0
-- The CXX compiler identification is MSVC 19.41.34120.0
#COMPILER_HASH#41fcbe159d3e0157ad0ffb47ecaf454584e3c371
#COMPILER_C_HASH#44ea048b252ee29d93bf1b3f14059b71485bcbe2
#COMPILER_C_VERSION#19.41.34120.0
#COMPILER_C_ID#MSVC
#COMPILER_C_PATH#D:/VS2022Community/VisualStudioCommunity/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe
#COMPILER_CXX_HASH#44ea048b252ee29d93bf1b3f14059b71485bcbe2
#COMPILER_CXX_VERSION#19.41.34120.0
#COMPILER_CXX_ID#MSVC
#COMPILER_CXX_PATH#D:/VS2022Community/VisualStudioCommunity/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe
-- Configuring done (3.9s)
-- Generating done (0.0s)
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_SHARED_LIBS
    CMAKE_INSTALL_BINDIR
    CMAKE_INSTALL_LIBDIR
    _VCPKG_ROOT_DIR

-- Build files have been written to: D:/ALL/vcpkg-master/buildtrees/detect_compiler/x64-windows-rel

**Comment by LilyWangLL** [comment]
I cannot repro this issue locally, your problem is downloading `pkgconf`, please confirm the status of your internet.
```
-- Fixing pkgconfig file: D:/ALL/vcpkg-master/packages/bzip2_x64-windows/lib/pkgconfig/bzip2.pc
-- Downloading https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst -> msys2-mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

  Failed to download file with error: no such file or directory
```

**Comment by running-az** [comment]
I can input web pages in the browser: https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-pkgconf-1 ~2.2.0-1-any. pkg. tar. zst is downloading normally, which should indicate that the network is working properly, right?The manually downloaded software package is placed in:ALL\vcpkg-master\downloads

**Comment by LilyWangLL** [comment]
You could download it manually, then rename it to `msys2-mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst`, and put it to _D:\ALL\vcpkg-master\downloads\_.

**Comment by running-az** [comment]
Yes, I downloaded and renamed all the packages needed for building, but now there is a new issue:CMake Warning at installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:344 (message):
  The following variables are not used in CMakeLists.txt:

      PKG_CONFIG_EXECUTABLE

  Please recheck them and remove the unnecessary options from the
  `vcpkg_cmake_configure` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):
  ports/curl/portfile.cmake:76 (vcpkg_cmake_configure)
  scripts/ports.cmake:192 (include)


-- Building x64-windows-dbg
CMake Warning at scripts/cmake/vcpkg_execute_build_process.cmake:65 (message):
  Please ensure your system has sufficient memory.
Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/curl/portfile.cmake:90 (vcpkg_cmake_install)
  scripts/ports.cmake:192 (include)


-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: D:/CMake/bin/cmake.exe --build . --config Debug --target install -- -v -j21
    Working Directory: D:/ALL/vcpkg-master/buildtrees/curl/x64-windows-dbg
    See logs for more information:
      D:\ALL\vcpkg-master\buildtrees\curl\install-x64-windows-dbg-out.log
      D:\ALL\vcpkg-master\buildtrees\curl\install-x64-windows-dbg-out-1.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/curl/portfile.cmake:90 (vcpkg_cmake_install)
  scripts/ports.cmake:192 (include)

D:\ALL\vcpkg-master\buildtrees\curl\install-x64-windows-dbg-out-1.log：
Change Dir: 'D:/ALL/vcpkg-master/buildtrees/curl/x64-windows-dbg'

Run Build Command(s): D:/VS2022Community/VisualStudioCommunity/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe -v -v -j1 install
[1/3] D:/CMake/bin/cmcldeps.exe RC D:\ALL\vcpkg-master\buildtrees\curl\src\curl-8_9_1-bb74e44024.clean\lib\libcurl.rc lib\CMakeFiles\libcurl_shared.dir\libcurl.rc.res.d lib\CMakeFiles\libcurl_shared.dir\libcurl.rc.res "Note: including file: " "D:/VS2022Community/VisualStudioCommunity/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe" "D:\Windows Kits\10\bin\10.0.22621.0\x64\rc.exe" -DBUILDING_LIBCURL -DCURLDEBUG -DDEBUGBUILD -DHAVE_CONFIG_H -DUNICODE -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -D_UNICODE -Dlibcurl_shared_EXPORTS -I D:\ALL\vcpkg-master\buildtrees\curl\src\curl-8_9_1-bb74e44024.clean\include -I D:\ALL\vcpkg-master\buildtrees\curl\x64-windows-dbg\lib\..\include -I D:\ALL\vcpkg-master\buildtrees\curl\src\curl-8_9_1-bb74e44024.clean\lib\.. -I D:\ALL\vcpkg-master\buildtrees\curl\src\curl-8_9_1-bb74e44024.clean\lib\..\include -I D:\ALL\vcpkg-master\buildtrees\curl\x64-windows-dbg\lib\.. -I D:\ALL\vcpkg-master\buildtrees\curl\src\curl-8_9_1-bb74e44024.clean\lib -I D:\ALL\vcpkg-master\buildtrees\curl\x64-windows-dbg\lib -I D:\ALL\vcpkg-master\installed\x64-windows\include -c65001 /DWIN32 -DCURL_EMBED_MANIFEST -D_DEBUG /fo lib\CMakeFiles\libcurl_shared.dir\libcurl.rc.res D:\ALL\vcpkg-master\buildtrees\curl\src\curl-8_9_1-bb74e44024.clean\lib\libcurl.rc
[2/3] C:\Windows\system32\cmd.exe /C "C:\Windows\system32\cmd.exe /C "D:\CMake\bin\cmake.exe -E __create_def D:\ALL\vcpkg-master\buildtrees\curl\x64-windows-dbg\lib\CMakeFiles\libcurl_shared.dir\.\exports.def D:\ALL\vcpkg-master\buildtrees\curl\x64-windows-dbg\lib\CMakeFiles\libcurl_shared.dir\.\exports.def.objs && cd D:\ALL\vcpkg-master\buildtrees\curl\x64-windows-dbg" && D:\CMake\bin\cmake.exe -E vs_link_dll --intdir=lib\CMakeFiles\libcurl_shared.dir --rc="D:\Windows Kits\10\bin\10.0.22621.0\x64\rc.exe" --mt="D:\Windows Kits\10\bin\10.0.22621.0\x64\mt.exe" --manifests  -- D:\VS2022Community\VisualStudioCommunity\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64\link.exe  @CMakeFiles\libcurl_shared.rsp  /out:lib\libcurl-d.dll /implib:lib\libcurl-d.lib /pdb:lib\libcurl-d.pdb /dll /version:0.0 /machine:x64 /nologo    /debug /INCREMENTAL  /DEF:lib\CMakeFiles\libcurl_shared.dir\.\exports.def && cd ."
FAILED: lib/libcurl-d.dll lib/libcurl-d.lib 
C:\Windows\system32\cmd.exe /C "C:\Windows\system32\cmd.exe /C "D:\CMake\bin\cmake.exe -E __create_def D:\ALL\vcpkg-master\buildtrees\curl\x64-windows-dbg\lib\CMakeFiles\libcurl_shared.dir\.\exports.def D:\ALL\vcpkg-master\buildtrees\curl\x64-windows-dbg\lib\CMakeFiles\libcurl_shared.dir\.\exports.def.objs && cd D:\ALL\vcpkg-master\buildtrees\curl\x64-windows-dbg" && D:\CMake\bin\cmake.exe -E vs_link_dll --intdir=lib\CMakeFiles\libcurl_shared.dir --rc="D:\Windows Kits\10\bin\10.0.22621.0\x64\rc.exe" --mt="D:\Windows Kits\10\bin\10.0.22621.0\x64\mt.exe" --manifests  -- D:\VS2022Community\VisualStudioCommunity\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64\link.exe  @CMakeFiles\libcurl_shared.rsp  /out:lib\libcurl-d.dll /implib:lib\libcurl-d.lib /pdb:lib\libcurl-d.pdb /dll /version:0.0 /machine:x64 /nologo    /debug /INCREMENTAL  /DEF:lib\CMakeFiles\libcurl_shared.dir\.\exports.def && cd ."
LINK Pass 1: command "D:\VS2022Community\VisualStudioCommunity\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64\link.exe @CMakeFiles\libcurl_shared.rsp /out:lib\libcurl-d.dll /implib:lib\libcurl-d.lib /pdb:lib\libcurl-d.pdb /dll /version:0.0 /machine:x64 /nologo /debug /INCREMENTAL /DEF:lib\CMakeFiles\libcurl_shared.dir\.\exports.def /MANIFEST /MANIFESTFILE:lib\CMakeFiles\libcurl_shared.dir/intermediate.manifest lib\CMakeFiles\libcurl_shared.dir/manifest.res" failed (exit code 1104) with the following output:
LINK : fatal error LNK1104: cannot open file 'D:\ALL\vcpkg-master\installed\x64-windows\debug\lib\zlibd.lib'

ninja: build stopped: subcommand failed.

**Comment by running-az** [comment]
I deleted vcpkg, re extracted and installed vcpkg, re executed vcpkg install teseract, and it was successful. I no longer need to manually download any packages. Can the decompression path of vcpkg package only be in English, right? I decompressed vcpkg for the second time and placed it in the full English path.
