### ISSUE TITLE
[boost-safe-numerics] Build error on x64-windows-static

### ISSUE THREAD

**Issue by zzdmfk** [microsoft/vcpkg#40547]
My visual studio version is VS2022, there is an issue when I built boost with command: .\vcpkg install boost:x64-windows-static

outputs:
error: building boost-safe-numerics:x64-windows-static failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle boost-safe-numerics:x64-windows-static: 28 s
Please ensure you're using the latest port files with git pull and vcpkg update.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-safe-numerics
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[boost-safe-numerics]+Build+error+on+x64-windows-static&body=Copy+issue+body+from+D%3A%2Fgitvcpkg%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by JonLiu1993** [comment]
@zzdmfk, Please provide error log, thanks.
