### ISSUE TITLE
'_ReturnAddres': identifier not found

### ISSUE THREAD

**Issue by PARKGIBAEK** [microsoft/vcpkg#40551]
**Describe the bug**

In our project, we were using the Boost library installed with the default options of vcpkg. However, we now need to install the Boost library as a static library with vcpkg, while the CRT of the Boost library must remain dynamic.

We deleted all packages installed via vcpkg and cleared the cache, then attempted to reinstall the Boost library. Despite this, we encountered issues with finding the file paths.

To address this, we manually added the paths vcpkg/installed/x64-windows-static/include and vcpkg/installed/x64-windows-static/lib to our build configuration. However, this resulted in errors such as _ReturnAddress: identifier not found.

**Environment**

- OS: windows10
- Compiler: msvc++20

**To Reproduce**

1. Changed '..\vcpkg\triplets\x64-windows-static' file content

```
set(VCPKG_TARGET_ARCHITECTURE x64)
# set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CRT_LINKAGE dynamic)
```

2. vcpkg install boost:x64-windows-static
- boost version : 1.85.0

3. Create a new project for Static library on VS 2022 Community 17.11.0

4. Configureation Properties :

1) General
- C++ Language Standard : /std:c++20
- C Language Standard : /std:c17
2) vcpkg
- Use Static Libraries : Yes
- Use Dynamic CRT : Yes
3) C/C++ > Code Generation
- Runtime Library : /MD
4) others
- default

**Code**

```
// BoostTypes.h
#pragma once
#include <boost/asio.hpp>
#include <boost/beast/core/error.hpp>
#include <boost/lockfree/queue.hpp>

namespace ServerCore
{

using namespace boost;

using Tcp = asio::ip::tcp;
using Udp = asio::ip::udp;
using TcpSocket = asio::ip::tcp::socket;
using UdpSocket = asio::ip::udp::socket;
using TcpEndPoint = asio::ip::tcp::endpoint;
using UdpEndPoint = asio::ip::udp::endpoint;
using TcpAcceptor = asio::ip::tcp::acceptor;
using IoContext = asio::io_context;

template <typename T>
using LockfreeQueue = lockfree::queue<T>;
template<typename T>
using LockfreeQueueRef = std::shared_ptr<LockfreeQueue<T>>;
}
```

**Expected behavior**

Can't build due to error

1. 
'_ReturnAddres': identifier not found
File ppltasks.h
Line 2473, 2487, 2706, 2720, 3017, 3064, 3188, 3230, 3278, 3490, 4030, 4157, 4205, 4377, 4551

2. Cannot find file 'boost/asio.hpp', 'boost/lockfree/queue.hpp' , ....

but all files are properly located

**Failure logs**

```
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(2473,60): error C3861: '_ReturnAddress': identifier not found
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(2473,60): message : '_ReturnAddress': function declaration must be available as none of the arguments depend on a template parameter
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(2470,10): message : This diagnostic occurred in the compiler generated function 'bool Concurrency::task_completion_event<_ResultType>::set_exception(_E) const'
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(2664,2): message : see reference to class template instantiation 'Concurrency::task_completion_event<_ResultType>' being compiled
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(2487,39): error C3861: '_ReturnAddress': identifier not found
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(2487,39): message : '_ReturnAddress': function declaration must be available as none of the arguments depend on a template parameter
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(2706,73): error C3861: '_ReturnAddress': identifier not found
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(2706,73): message : '_ReturnAddress': function declaration must be available as none of the arguments depend on a template parameter
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(2704,10): message : This diagnostic occurred in the compiler generated function 'bool Concurrency::task_completion_event<void>::set_exception(_E) const'
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(2720,52): error C3861: '_ReturnAddress': identifier not found
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(3017,35): error C3861: '_ReturnAddress': identifier not found
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(3017,35): message : '_ReturnAddress': function declaration must be available as none of the arguments depend on a template parameter
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(3009,5): message : This diagnostic occurred in the compiler generated function 'Concurrency::task<_Ty>::task(_Ty)'
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(3940,2): message : see reference to class template instantiation 'Concurrency::task<_Ty>' being compiled
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(3064,196): error C3861: '_ReturnAddress': identifier not found
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(3064,196): message : '_ReturnAddress': function declaration must be available as none of the arguments depend on a template parameter
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(3057,5): message : This diagnostic occurred in the compiler generated function 'Concurrency::task<_Ty>::task(_Ty,const Concurrency::task_options &)'
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(3188,83): error C3861: '_ReturnAddress': identifier not found
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(3188,83): message : '_ReturnAddress': function declaration must be available as none of the arguments depend on a template parameter
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(3185,10): message : This diagnostic occurred in the compiler generated function 'details::_ContinuationTypeTraits<_Function,_ReturnType>::_TaskOfType Concurrency::task<_Ty>::then(const _Function &) const'
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(3230,83): error C3861: '_ReturnAddress': identifier not found
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(3230,83): message : '_ReturnAddress': function declaration must be available as none of the arguments depend on a template parameter
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(3228,10): message : This diagnostic occurred in the compiler generated function 'details::_ContinuationTypeTraits<_Function,_ReturnType>::_TaskOfType Concurrency::task<_Ty>::then(const _Function &,Concurrency::task_options) const'
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(3278,83): error C3861: '_ReturnAddress': identifier not found
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(3278,83): message : '_ReturnAddress': function declaration must be available as none of the arguments depend on a template parameter
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(3274,10): message : This diagnostic occurred in the compiler generated function 'details::_ContinuationTypeTraits<_Function,_ReturnType>::_TaskOfType Concurrency::task<_Ty>::then(const _Function &,Concurrency::cancellation_token,Concurrency::task_continuation_context) const'
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(3490,90): error C3861: '_ReturnAddress': identifier not found
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(3490,90): message : '_ReturnAddress': function declaration must be available as none of the arguments depend on a template parameter
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(3481,10): message : This diagnostic occurred in the compiler generated function 'details::_ContinuationTypeTraits<_Function,_ReturnType>::_TaskOfType Concurrency::task<_Ty>::_Then(const _Function &,Concurrency::details::_CancellationTokenState *,Concurrency::details::_TaskInliningMode_t) const'
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(4030,208): error C3861: '_ReturnAddress': identifier not found
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(4030,208): message : '_ReturnAddress': function declaration must be available as none of the arguments depend on a template parameter
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(4023,5): message : This diagnostic occurred in the compiler generated function 'Concurrency::task<void>::task(_Ty,const Concurrency::task_options &)'
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(4157,83): error C3861: '_ReturnAddress': identifier not found
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(4157,83): message : '_ReturnAddress': function declaration must be available as none of the arguments depend on a template parameter
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(4155,10): message : This diagnostic occurred in the compiler generated function 'details::_ContinuationTypeTraits<_Function,void>::_TaskOfType Concurrency::task<void>::then(const _Function &,Concurrency::task_options) const'
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(4205,83): error C3861: '_ReturnAddress': identifier not found
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(4205,83): message : '_ReturnAddress': function declaration must be available as none of the arguments depend on a template parameter
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(4201,10): message : This diagnostic occurred in the compiler generated function 'details::_ContinuationTypeTraits<_Function,void>::_TaskOfType Concurrency::task<void>::then(const _Function &,Concurrency::cancellation_token,Concurrency::task_continuation_context) const'
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(4377,90): error C3861: '_ReturnAddress': identifier not found
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(4377,90): message : '_ReturnAddress': function declaration must be available as none of the arguments depend on a template parameter
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(4367,10): message : This diagnostic occurred in the compiler generated function 'details::_ContinuationTypeTraits<_Function,void>::_TaskOfType Concurrency::task<void>::_Then(const _Function &,Concurrency::details::_CancellationTokenState *,Concurrency::details::_TaskInliningMode_t) const'
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(4551,79): error C3861: '_ReturnAddress': identifier not found
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\ppltasks.h(4551,79): message : '_ReturnAddress': function declaration must be available as none of the arguments depend on a template parameter
```

**Additional context**

**Comment by Osyotr** [comment]
> we now need to install the Boost library as a static library with vcpkg, while the CRT of the Boost library must remain dynamic.

Note: there's `x64-windows-static-md` community triplet for that.

**Comment by PARKGIBAEK** [comment]
> > we now need to install the Boost library as a static library with vcpkg, while the CRT of the Boost library must remain dynamic.
> 
> Note: there's `x64-windows-static-md` community triplet for that.


"I encountered the same error regardless of whether the CRT is dynamic or static.

Also, I don't understand why the issue with not finding the vcpkg path started after installing the static library in the first place."

**Comment by PARKGIBAEK** [comment]
In addition, even if you give the static option during installation, if you open the lib file, you can see that it is an 'Import Library' that refers to other files inside.

I want the extracted library to be independently available for unreal engine and other external projects as well.

But the problem is that some libraries are still import libraries even if they are installed statically.



'boost_system-vc144-mt-x64-1_85.lib' file content as belows : 

!<arch>
/               1724292206              0       53        `
     n?dummy_exported_function@system@boost@@YAXXZ 
/               1724292206              0       59        `
   n      ?dummy_exported_function@system@boost@@YAXXZ 
//              1724292206              0       63        `
libs\system\CMakeFiles\boost_system.dir\src\error_code.cpp.obj 
/0              1724292206              100666  6735      `
d? n쑪f?         .drectve        /                  
 .debug$S        X
  3              @ B.text$mn           ?               P`.debug$S        ?  ?  :         @B.debug$T        l	  b              @ B.chks64         0   ?               
     /DEFAULTLIB:"MSVCRT" /DEFAULTLIB:"OLDNAMES"    ?    ?    C:\Users\tkdri\vcpkg\buildtrees\boost-system\x64-windows-static-md-rel\libs\system\CMakeFiles\boost_system.dir\src\error_code.cpp.obj : <`  ? ) H?  ) H? Microsoft (R) Optimizing Compiler  $boost 	 $system  $__vc_attributes  $helper_attributes  $atl  $std    ?  p      ?+?갍uJo6綴'@퇘?v?g슾굻C  g    o땚`럲???V좾껌싎事.?  ?   콺?推?/s춰?k튦e~X?f??f^  3   熊,벣I뼗N묓??떞?쀉￦?쟨微]?  ?   ?a{[? v?춒Q??Q}?W?{&췓#껋  ?   俗?GM{5낐;딅퍄쪷[혲!)뎙zt?  O   챝?X[?3퓋疊겍윬+}*??-?0@雪  ?   N>뺪?v扇?QT랬頂???^?LNu  8   ??s5mKym꿬:憎?M뤸^랴?H縯  ?   729
 ?밟b렟꿂9쓘퇣??+?픲?    ]?]溜B?춧?)YT쳔J튰 ?7?瘀? R   s웞?R7[쒦q?쎫쏽]웴Jgo?챈믏  ?   `q@?T~?>w쐿젰s쨔?씹牛?팫     Q탿뜵瓦?`\E}촘놄燎?e`쇖J? z   林9물eE諛??|湯
]B率7?U읠n鈿? ?   ???+ 1P)?T榜;봑?{삺?V  @   賀쥢,`S施둗?얐쬧fn왬cw쏺??魄  ?   ofЭ?px??푓琮X??s탙4?ba?? 	   ??r6?첹?桐B?)?R展u性?  o   ?dY?h ?쁯<fSLt?챓+獨+4??  ?   đ?o?춞a?(嘉켼9쉂쑊

?  :    I찍?푯.얎;???曙?윇9뇰?  ?  ?   C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\xkeycheck.h C:\Users\tkdri\vcpkg\installed\x64-windows-static-md\include\boost\config\stdlib\dinkumware.hpp C:\Users\tkdri\vcpkg\installed\x64-windows-static-md\include\boost\config\detail\select_platform_config.hpp C:\Users\tkdri\vcpkg\installed\x64-windows-static-md\include\boost\config\platform\win32.hpp C:\Users\tkdri\vcpkg\installed\x64-windows-static-md\include\boost\config\detail\suffix.hpp C:\Users\tkdri\vcpkg\installed\x64-windows-static-md\include\boost\config\detail\cxx_composite.hpp C:\Users\tkdri\vcpkg\buildtrees\boost-system\src\ost-1.85.0-e47a1ad8ab.clean\libs\system\include\boost\system\api_config.hpp C:\Users\tkdri\vcpkg\buildtrees\boost-system\src\ost-1.85.0-e47a1ad8ab.clean\libs\system\src\error_code.cpp C:\Users\tkdri\vcpkg\buildtrees\boost-system\src\ost-1.85.0-e47a1ad8ab.clean\libs\system\include\boost\system\config.hpp C:\Users\tkdri\vcpkg\installed\x64-windows-static-md\include\boost\config.hpp C:\Users\tkdri\vcpkg\installed\x64-windows-static-md\include\boost\config\user.hpp C:\Users\tkdri\vcpkg\installed\x64-windows-static-md\include\boost\config\detail\select_compiler_config.hpp C:\Users\tkdri\vcpkg\installed\x64-windows-static-md\include\boost\config\compiler\visualc.hpp C:\Users\tkdri\vcpkg\installed\x64-windows-static-md\include\boost\config\pragma_message.hpp C:\Users\tkdri\vcpkg\installed\x64-windows-static-md\include\boost\config\helper_macros.hpp C:\Users\tkdri\vcpkg\installed\x64-windows-static-md\include\boost\config\detail\select_stdlib_config.hpp C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\version C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\yvals_core.h C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\vcruntime.h C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\sal.h C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\concurrencysal.h C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\vadefs.h    ?      L  ?    ?  p   L G                               boost::system::dummy_exported_function                         @  O?  (                                  ,       0      
 ?      ?     
         boost::system 秩               *      dummy_exported_function ↖[?+-pN     C:\Users\tkdri\vcpkg\buildtrees\boost-system\x64-windows-static-md-rel ?     C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1441~1.341\bin\Hostx64\x64\cl.exe ?     C:\Users\tkdri\vcpkg\buildtrees\boost-system\src\ost-1.85.0-e47a1ad8ab.clean\libs\system\src\error_code.cpp z     C:\Users\tkdri\vcpkg\buildtrees\boost-system\x64-windows-static-md-rel\stage\lib\boost_system-vc144-mt-x64-1_85.pdb ?    -TP -IC:\Users\tkdri\vcpkg\buildtrees\boost-system\src\ost-1.85.0-e47a1ad8ab.clean\libs\system\include -external:IC:\Users\tkdri\vcpkg\installed\x64-windows-static-md\include -external:W0 -nologo -DWIN32 -D_WINDOWS -utf-8 -GR -EHs ?     -EHc -MP -O2 -Oi -Gy -DNDEBUG -Z7 -MD -showIncludes -FS -c -I"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include" -I"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\ATLMFC\include" 增      -I"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\um" -I"C:\Program 增      Files (x86)\Windows Kits\10\include\10.0.20348.0\shared" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\winrt" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\cppwinrt" -I"C:\Program Files (x86)\Windows 蒸      Kits\NETFXSDK\4.8\include\um" -external:I"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include" -external:I"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\ATLMFC\include" ?     -external:I"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" -external:I"C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\ucrt" -external:I"C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\um" ?     -external:I"C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\shared" -external:I"C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\winrt" -external:I"C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\cppwinrt" 秩"      	  
      
    V    -external:I"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" -X 寀?            秩v臭?H僿쮢횕G鋼똥壹胄~tl엽??>n힣zE?       @comp.idH?   @feat.00?   @vol.md       .drectve       /                 .debug$S       X
                .text$mn              .B+?    .debug$S       ?                            .debug$T       l	                .chks64        0                 1   ?dummy_exported_function@system@boost@@YAXXZ
