### ISSUE TITLE
[openvino] Build error

### ISSUE THREAD

**Issue by lwf0724** [microsoft/vcpkg#40554]
Copy issue body from D:/vcpkg/vcpkg-master/installed/vcpkg/issue_body.md
D:\vcpkg\vcpkg-master>.\vcpkg install opencv:x64-windows
Computing installation plan...
The following packages will be built and installed:
    opencv[core,default-features]:x64-windows -> 4.8.0
  * opencv4[core,default-features,dnn,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.8.0#8
  * openvino[auto,auto-batch,core,cpu,gpu,hetero,ir,onnx,paddle,pytorch,tensorflow,tensorflow-lite]:x64-windows -> 2023.1.0#4
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\luowenfei\AppData\Local\vcpkg\archives in 421 us. Use --debug to see more details.
Installing 1/3 openvino:x64-windows...
Building openvino[auto,auto-batch,core,cpu,gpu,hetero,ir,onnx,paddle,pytorch,tensorflow,tensorflow-lite]:x64-windows...
-- Using cached openvinotoolkit-openvino-2023.1.0.tar.gz.
-- Extracting source D:/vcpkg/vcpkg-master/downloads/openvinotoolkit-openvino-2023.1.0.tar.gz
-- Applying patch 001-disable-tools.patch
-- Applying patch 003-fix-find-onnx.patch
-- Applying patch 004-compilation-with-cpp17.patch
-- Applying patch 005-tflite-search.patch
-- Applying patch 007-macos-14.patch
-- Applying patch 008-dynamic-protubuf.patch
-- Applying patch 009-tensorflow-proto-odr.patch
-- Using source at D:/vcpkg/vcpkg-master/buildtrees/openvino/src/2023.1.0-d4639b6ba4.clean
-- Using cached oneapi-src-oneDNN-ec0b2ee85fc2a2dbdeec10035c5ef5813d8fb5ea.tar.gz.
-- Extracting source D:/vcpkg/vcpkg-master/downloads/oneapi-src-oneDNN-ec0b2ee85fc2a2dbdeec10035c5ef5813d8fb5ea.tar.gz
-- Applying patch 006-onednn-gpu-build.patch
-- Using source at D:/vcpkg/vcpkg-master/buildtrees/openvino/src/813d8fb5ea-f10e7a77bc.clean
-- Using cached openvinotoolkit-oneDNN-a1aa20ca8f19465dc2fd18389953ed83798b2fd3.tar.gz.
-- Extracting source D:/vcpkg/vcpkg-master/downloads/openvinotoolkit-oneDNN-a1aa20ca8f19465dc2fd18389953ed83798b2fd3.tar.gz
-- Using source at D:/vcpkg/vcpkg-master/buildtrees/openvino/src/83798b2fd3-bd5f7c44d8.clean
-- Using cached openvinotoolkit-mlas-c7c8a631315000f17c650af34431009d2f22129c.tar.gz.
-- Extracting source D:/vcpkg/vcpkg-master/downloads/openvinotoolkit-mlas-c7c8a631315000f17c650af34431009d2f22129c.tar.gz
-- Using source at D:/vcpkg/vcpkg-master/buildtrees/openvino/src/9d2f22129c-d6edabccf5.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: D:/Cmake/bin/cmake.exe --build . --config Debug --target install -- -v -j5
    Working Directory: D:/vcpkg/vcpkg-master/buildtrees/openvino/x64-windows-dbg
    See logs for more information:
      D:\vcpkg\vcpkg-master\buildtrees\openvino\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/openvino/portfile.cmake:134 (vcpkg_cmake_install)
  scripts/ports.cmake:168 (include)

d:\vcpkg\vcpkg-master\buildtrees\openvino\src\2023.1.0-d4639b6ba4.clean\src\plugins\intel_gpu\thirdparty\onednn_gpu\src\common\memory_tracking.hpp(364): warning C4307: '+': integral constant overflow
d:\vcpkg\vcpkg-master\buildtrees\openvino\src\2023.1.0-d4639b6ba4.clean\src\plugins\intel_gpu\thirdparty\onednn_gpu\src\common\memory_tracking.hpp(444): warning C4307: '+': integral constant overflow
D:\vcpkg\vcpkg-master\buildtrees\openvino\src\2023.1.0-d4639b6ba4.clean\src\plugins\intel_gpu\thirdparty\onednn_gpu\src\common\binary.cpp(42): error C2059: syntax error: ','
D:\vcpkg\vcpkg-master\buildtrees\openvino\src\2023.1.0-d4639b6ba4.clean\src\plugins\intel_gpu\thirdparty\onednn_gpu\src\common\binary.cpp(47): error C2059: syntax error: ','
D:\vcpkg\vcpkg-master\buildtrees\openvino\src\2023.1.0-d4639b6ba4.clean\src\plugins\intel_gpu\thirdparty\onednn_gpu\src\common\binary.cpp(58): error C2059: syntax error: ','
D:\vcpkg\vcpkg-master\buildtrees\openvino\src\2023.1.0-d4639b6ba4.clean\src\plugins\intel_gpu\thirdparty\onednn_gpu\src\common\binary.cpp(61): error C2059: syntax error: ','
D:\vcpkg\vcpkg-master\buildtrees\openvino\src\2023.1.0-d4639b6ba4.clean\src\plugins\intel_gpu\thirdparty\onednn_gpu\src\common\binary.cpp(64): error C2059: syntax error: ','
[151/380] Building CXX object src\common\CMakeFiles\dnnl_common.dir\concat.cpp.obj
FAILED: src/common/CMakeFiles/dnnl_common.dir/concat.cpp.obj 
C:\PROGRA~2\MICROS~2\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe  /nologo /TP -DCL_TARGET_OPENCL_VERSION=120 -DDNNL_DISABLE_PRIMITIVE_CACHE -DDNNL_ENABLE_CONCURRENT_EXEC -DDNNL_ENABLE_CPU_ISA_HINTS -DDNNL_ENABLE_MAX_CPU_ISA -DDNNL_X64=1 -DNOMINMAX -DWIN32_LEAN_AND_MEAN -D_WIN -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -ID:\vcpkg\vcpkg-master\buildtrees\openvino\src\2023.1.0-d4639b6ba4.clean\src\plugins\intel_gpu\thirdparty\onednn_gpu\include -ID:\vcpkg\vcpkg-master\buildtrees\openvino\x64-windows-dbg\src\plugins\intel_gpu\thirdparty\onednn_gpu_build\include -ID:\vcpkg\vcpkg-master\buildtrees\openvino\src\2023.1.0-d4639b6ba4.clean\src\plugins\intel_gpu\thirdparty\onednn_gpu\src -ID:\vcpkg\vcpkg-master\installed\x64-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_CRT_SECURE_NO_WARNINGS /D_SCL_SECURE_NO_WARNINGS /EHsc /Gy /W3 /bigobj /MP /wd4251 /wd4275 /wd4996 /wd4244 /wd4018 -openmp  /MP /bigobj /Zc:preprocessor    /wd4800 /wd4068 /wd4305 /wd4551 /wd4244 /wd5105  -DITT_API_IPT_SUPPORT /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /Fosrc\common\CMakeFiles\dnnl_common.dir\concat.cpp.obj /Fdsrc\common\CMakeFiles\dnnl_common.dir\ /FS -c D:\vcpkg\vcpkg-master\buildtrees\openvino\src\2023.1.0-d4639b6ba4.clean\src\plugins\intel_gpu\thirdparty\onednn_gpu\src\common\concat.cpp
cl : Command line warning D9002 : ignoring unknown option '/Zc:preprocessor'
d:\vcpkg\vcpkg-master\buildtrees\openvino\src\2023.1.0-d4639b6ba4.clean\src\plugins\intel_gpu\thirdparty\onednn_gpu\src\common\memory_tracking.hpp(364): warning C4307: '+': integral constant overflow
d:\vcpkg\vcpkg-master\buildtrees\openvino\src\2023.1.0-d4639b6ba4.clean\src\plugins\intel_gpu\thirdparty\onednn_gpu\src\common\memory_tracking.hpp(444): warning C4307: '+': integral constant overflow
D:\vcpkg\vcpkg-master\buildtrees\openvino\src\2023.1.0-d4639b6ba4.clean\src\plugins\intel_gpu\thirdparty\onednn_gpu\src\common\concat.cpp(45): error C2059: syntax error: ','
D:\vcpkg\vcpkg-master\buildtrees\openvino\src\2023.1.0-d4639b6ba4.clean\src\plugins\intel_gpu\thirdparty\onednn_gpu\src\common\concat.cpp(54): error C2059: syntax error: ','
D:\vcpkg\vcpkg-master\buildtrees\openvino\src\2023.1.0-d4639b6ba4.clean\src\plugins\intel_gpu\thirdparty\onednn_gpu\src\common\concat.cpp(69): error C2059: syntax error: ','
D:\vcpkg\vcpkg-master\buildtrees\openvino\src\2023.1.0-d4639b6ba4.clean\src\plugins\intel_gpu\thirdparty\onednn_gpu\src\common\concat.cpp(88): error C2059: syntax error: ',

**Comment by LilyWangLL** [comment]
The latest version of `openvino` is 2024.3.0, it could install succeed on latest vcpkg, please update your vcpkg and rebuild it.
```
Installing 16/16 openvino[auto,auto-batch,core,cpu,gpu,hetero,ir,onnx,paddle,pytorch,tensorflow,tensorflow-lite]:x64-windows@2024.3.0...
Building openvino[auto,auto-batch,core,cpu,gpu,hetero,ir,onnx,paddle,pytorch,tensorflow,tensorflow-lite]:x64-windows@2024.3.0...
-- Downloading https://github.com/openvinotoolkit/openvino/archive/2024.3.0.tar.gz -> openvinotoolkit-openvino-2024.3.0.tar.gz...
-- Extracting source F:/0814/downloads/openvinotoolkit-openvino-2024.3.0.tar.gz
-- Applying patch 001-disable-tools.patch
-- Applying patch 002-fix-onnx-codegen.patch
-- Using source at F:/0814/buildtrees/openvino/src/2024.3.0-38b00ca3fb.clean
-- Downloading https://github.com/oneapi-src/oneDNN/archive/7ab8ee9adda866d675edeee7a3a6a29b2d0a1572.tar.gz -> oneapi-src-oneDNN-7ab8ee9adda866d675edeee7a3a6a29b2d0a1572.tar.gz...
-- Extracting source F:/0814/downloads/oneapi-src-oneDNN-7ab8ee9adda866d675edeee7a3a6a29b2d0a1572.tar.gz
-- Using source at F:/0814/buildtrees/openvino/src/9b2d0a1572-22d6d1ff37.clean
-- Downloading https://github.com/openvinotoolkit/oneDNN/archive/f0f8defe2dff5058391f2a66e775e20b5de33b08.tar.gz -> openvinotoolkit-oneDNN-f0f8defe2dff5058391f2a66e775e20b5de33b08.tar.gz...
-- Extracting source F:/0814/downloads/openvinotoolkit-oneDNN-f0f8defe2dff5058391f2a66e775e20b5de33b08.tar.gz
-- Using source at F:/0814/buildtrees/openvino/src/0b5de33b08-c8246f99ba.clean
-- Downloading https://github.com/openvinotoolkit/mlas/archive/d1bc25ec4660cddd87804fcf03b2411b5dfb2e94.tar.gz -> openvinotoolkit-mlas-d1bc25ec4660cddd87804fcf03b2411b5dfb2e94.tar.gz...
-- Extracting source F:/0814/downloads/openvinotoolkit-mlas-d1bc25ec4660cddd87804fcf03b2411b5dfb2e94.tar.gz
-- Using source at F:/0814/buildtrees/openvino/src/1b5dfb2e94-e89ef61ea3.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: F:/0814/packages/openvino_x64-windows/share/openvino/usage
-- Performing post-build validation
Stored binaries in 1 destinations in 1.3 min.
Elapsed time to handle openvino:x64-windows: 1 h
openvino:x64-windows package ABI: ae5c73d59d95c456ae41843506101ddd60f6e761dc070ece8ff5151ceb6c7488
Total install time: 1.3 h
The package OpenVINO can be used in cmake scripts as:

    find_package(OpenVINO REQUIRED)
    target_link_libraries(main PRIVATE openvino::runtime)
```

**Comment by LilyWangLL** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
