### ISSUE TITLE
[many ports] FILE_CONFLICTS and POST_BUILD_CHECKS_FAILED on androids in ci

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#40559]
### Operating system

Android

### Compiler

CI android compiler

### Steps to reproduce the behavior

```Shell
Run CI
https://dev.azure.com/vcpkg/public/_build/results?buildId=106229&view=logs&jobId=18f767b8-9e55-53aa-9c57-42862973482f&j=185c373b-2f55-539e-a6cb-ef2677cc0d97&t=812b592a-a8ab-5878-a745-53ef2e734f42
```

### Failure logs

https://dev.azure.com/vcpkg/public/_build/results?buildId=106229&view=logs&jobId=18f767b8-9e55-53aa-9c57-42862973482f&j=185c373b-2f55-539e-a6cb-ef2677cc0d97&t=812b592a-a8ab-5878-a745-53ef2e734f42

### Additional context

From recent run on the CI on androids. CI get green on CI, but there is ports that get:
  POST_BUILD_CHECKS_FAILED: 2
  FILE_CONFLICTS: 4
```
  libosip2:arm64-android: POST_BUILD_CHECKS_FAILED: 373 ms
  loguru:arm64-android: POST_BUILD_CHECKS_FAILED: 309 ms
  dbg-macro:arm64-android: FILE_CONFLICTS: 376 ms
  ijg-libjpeg:arm64-android: FILE_CONFLICTS: 2.2 s
  range-v3-vs2015:arm64-android: FILE_CONFLICTS: 577 ms
  signalrclient:arm64-android: FILE_CONFLICTS: 23 s
```

We should fix that ports.
It happen on:
arm64-android
x64_android
arm_neon_android

**Comment by dg0yt** [comment]
Duplicates #40527.

**Comment by talregev** [comment]
This is the original, and the old one is duplicated.
I close the old one, but you refuse, and they reopen it.

I can close again the old one (https://github.com/microsoft/vcpkg/issues/40527)

**Comment by dg0yt** [comment]
The second (= this) one is the duplicate. Opening a second one always cuts away original discussions.

**Comment by dg0yt** [comment]
"android" is just a tiny subset of the full problem. Don't want to add more comments here.

**Comment by talregev** [comment]
> "android" is just a tiny subset of the full problem. Don't want to add more comments here.

You can open a new one.

**Comment by dg0yt** [comment]
> You can open a new one.

Again: "Opening a second one always cuts away original discussions."

**Comment by dg0yt** [comment]
You could just leave the triage to the vcpkg maintainers...
I was aware of *this* issue until this morning. I added the cross-reference of type "duplicate" because IMO it should have been mentioned right in the beginning.

**Comment by talregev** [comment]
What can i say? I love this issue, and I don't want it be closed as duplicate. Only after the merge of the PRs.

**Comment by talregev** [comment]
After the merge, I will open the old one.

**Comment by dg0yt** [comment]
Yes, this issue created a lot of acitivity for pouring new shiny water into the shiny bucket. The original issue is about the fact that the bucket has holes.
