### ISSUE TITLE
[freetype] Download from github instead of sourceforge

### ISSUE THREAD

**Issue by nextstate** [microsoft/vcpkg#40560]
### Is your feature request related to a problem? Please describe.

Microsoft has blocked sourceforge.net. Building freetype is impossible because vcpkg is downloading freetype from sourceforge.net.

### Proposed solution

The package should be updated to download from https://github.com/freetype/freetype

**Comment by dg0yt** [comment]
> Microsoft has blocked sourceforge.net.

Can you add more information?

**Comment by nextstate** [comment]
Does this help?

![image](https://github.com/user-attachments/assets/d935d3c7-69eb-4d65-a45d-1bd005c41c9a)

**Comment by dg0yt** [comment]
No. Unless "your organization" is "Microsoft". Otherwise, contact your administrator. There are more source packages hosted on sourceforge.net.

**Comment by FrankXie05** [comment]
@nextstate This may be a Windows problem. Not a port or sorceforge problem. I have reported it. Wait a moment.

**Comment by dg0yt** [comment]
This may be an organizational policy, enforced via a Microsoft product.

**Comment by vicroms** [comment]
@nextstate can you send an email to vcpkg@microsoft.com  so we can help you with this issue
