### ISSUE TITLE
icuuc link fails when using UnicodeString

### ISSUE THREAD

**Issue by liubailin2017** [microsoft/vcpkg#40569]
**Describe the bug**
icuuc link fails using UnicodeString

**Environment**
- OS: [  Windows]
- Compiler: GCC 7.3.0

**To Reproduce**

1. ./vcpkg install icu

#include <unicode/ucnv.h>
#include <unicode/ustring.h>
#include <unicode/unistr.h> 
#include<string>
using icu::UnicodeString;
int main() {
std::string& utf8_str;
UnicodeString uni_str(utf8_str.c_str());   
return 0
}

err :
undefined reference to `icu_74::UnicodeString::~UnicodeString()

**Expected behavior**
It works fine when using u_strFromUTF8, but a link error is reported when using UnicodeString.
**Failure logs**
undefined reference to `icu_74::UnicodeString::~UnicodeString()

**Comment by greenozon** [comment]
1st question (C++ related):

for line
>std::string& utf8_str;

we hit compiler error:
error C2530: 'utf8_str': references must be initialized

so I suggest to remove reference and keep string as is, next

I tried to build up a sample app in MSVC, it iinks and works well, details:

Here's an example of how you might set up your project properties in Visual Studio:

Project Properties > C/C++ > General > Additional Include Directories: 
C:\path\to\icu\include

Project Properties > Linker > General > Additional Library Directories: 
C:\path\to\icu\lib

Project Properties > Linker > Input > Additional Dependencies: 
icuuc.lib; icuin.lib; icudt.lib

I believe you need to do similar steps inside your GCC project

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
