### ISSUE TITLE
Error: Building package ceres:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by adgbu** [Microsoft/vcpkg#4057]
$ git pull && vcpkg update
Already up-to-date.
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

$ cmake --version
cmake version 3.6.1

$ vcpkg install ceres --triplet x64-windows

The following packages will be built and installed:
    ceres[core]:x64-windows
Starting package 1/1: ceres:x64-windows
Building package ceres[core]:x64-windows...
-- Using cached C:/local/vcpkg/downloads/ceres-solver-ceres-solver-1.14.0.tar.gz
-- Using source at C:/local/vcpkg/buildtrees/ceres/src/1.14.0-3cdce6815a
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:170 (message):
    Command failed: C:/local/vcpkg/downloads/tools/cmake-3.11.4-windows/cmake-3.11.4-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: C:/local/vcpkg/buildtrees/ceres/x64-windows-dbg
    See logs for more information:
      C:\local\vcpkg\buildtrees\ceres\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/ceres/portfile.cmake:61 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package ceres:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ceres:x64-windows
  Vcpkg version: 0.0.113-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by Voskrese** [comment]
See logs for more information:
C:\local\vcpkg\buildtrees\ceres\install-x64-windows-dbg-out.log

**Comment by adgbu** [comment]
I tried building it again and this time it worked. Don't know what the difference was. It worked with __ceres[core]__, so then I tried  __ceres[suitesparse]__ and that built fine also.
