### ISSUE TITLE
[LLVM] Building package llvm:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by aPSopt** [microsoft/vcpkg#4058]
> CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
>     Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
>     Working Directory: L:/vcpkg/buildtrees/llvm/x64-windows-dbg
>     See logs for more information:
>       L:\vcpkg\buildtrees\llvm\install-x64-windows-dbg-out.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
>   ports/llvm/portfile.cmake:51 (vcpkg_install_cmake)
>   scripts/ports.cmake:71 (include)
> 
> 
> Error: Building package llvm:x64-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: llvm:x64-windows
>   Vcpkg version: 0.0.113-nohash

Log file attached.

[install-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2278316/install-x64-windows-dbg-out.log)

**Comment by Voskrese** [comment]
it's hard to say anything, try to change the toolchain, now you have 14.14

> LINK : fatal error LNK1000: unknown error at 0000028420920EE0; consult documentation for technical support options

`error  llvm-tblgen.exe `

`[169/2434] cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=utils\TableGen\CMakeFiles\llvm-tblgen.dir --manifests  -- C:\PROGRA~2\MICROS~4\2017\ENTERP~1\VC\Tools\MSVC\1414~1.264\bin\Hostx64\x64\link.exe  utils\TableGen\CMakeFiles\llvm-tblgen.dir\AsmMatcherEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\AsmWriterEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\AsmWriterInst.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\Attributes.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\CallingConvEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\CodeEmitterGen.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\CodeGenDAGPatterns.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\CodeGenHwModes.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\CodeGenInstruction.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\CodeGenMapTable.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\CodeGenRegisters.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\CodeGenSchedule.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\CodeGenTarget.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\DAGISelEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\DAGISelMatcherEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\DAGISelMatcherGen.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\DAGISelMatcherOpt.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\DAGISelMatcher.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\DFAPacketizerEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\DisassemblerEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\FastISelEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\FixedLenDecoderEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\GlobalISelEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\InfoByHwMode.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\InstrInfoEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\InstrDocsEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\IntrinsicEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\OptParserEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\PseudoLoweringEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\RegisterBankEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\RegisterInfoEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\SDNodeProperties.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\SearchableTableEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\SubtargetEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\SubtargetFeatureInfo.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\TableGen.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\Types.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\X86DisassemblerTables.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\X86EVEX2VEXTablesEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\X86FoldTablesEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\X86ModRMFilters.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\X86RecognizableInstr.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\CTagsEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\__\__\resources\windows_version_resource.rc.res  /out:bin\llvm-tblgen.exe /implib:lib\llvm-tblgen.lib /pdb:bin\llvm-tblgen.pdb /version:0.0  /machine:x64 /STACK:10000000 /debug /INCREMENTAL /subsystem:console  lib\LLVMSupport.lib lib\LLVMTableGen.lib lib\LLVMSupport.lib psapi.lib shell32.lib ole32.lib uuid.lib advapi32.lib lib\LLVMDemangle.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."`

> FAILED: bin/llvm-tblgen.exe

**Comment by Voskrese** [comment]
I assumed, but I'm not sure that this will help, look here
https://github.com/Microsoft/vcpkg/issues/3147#issue-309377113

or use VS 2015

**Comment by aPSopt** [comment]
Ok, I tried but it doesn`t help. I also tried different triplets and also check on other computer. 
The result is same - the build breaks.
It too complex for me so I give up.

The much more simpler way - is to download the sources from official llvm site and build it by self.
But there are exist one issue: if I try to build sources via cmake - it breaks by "internal compiler error".
So you need just to generate msvs solution and build it via msvs.
In this case all compiled succesfuly. (the visual studio is amaizing stable and robust tool)

**Comment by wangli28** [comment]
Hi @aPSopt, thanks for posting this issue. I can't reproduce this issue locally, does the issue persist? can you try vcpkg latest revision?

.\vcpkg.exe install llvm:x64-windows
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be built and installed:
  * atlmfc[core]:x64-windows
    llvm[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: atlmfc:x64-windows
Building package atlmfc[core]:x64-windows...
-- Performing post-build validation
-- Performing post-build validation done
Building package atlmfc[core]:x64-windows... done
Installing package atlmfc[core]:x64-windows...
Installing package atlmfc[core]:x64-windows... done
Elapsed time for package atlmfc:x64-windows: 1.572 s
Starting package 2/2: llvm:x64-windows
Building package llvm[core]:x64-windows...
-- Downloading http://releases.llvm.org/8.0.0/llvm-8.0.0.src.tar.xz...
-- Extracting source F:/test/vcpkg/downloads/llvm-8.0.0.src.tar.xz
-- Downloading http://releases.llvm.org/8.0.0/cfe-8.0.0.src.tar.xz...
-- Extracting source F:/test/vcpkg/downloads/cfe-8.0.0.src.tar.xz
-- Applying patch install-cmake-modules-to-share.patch
-- Applying patch fix-build-error.patch
-- Downloading https://www.python.org/ftp/python/3.7.3/python-3.7.3-embed-win32.zip...
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: F:/test/vcpkg/packages/llvm_x64-windows/share/llvm/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package llvm[core]:x64-windows... done
Installing package llvm[core]:x64-windows...
Installing package llvm[core]:x64-windows... done
Elapsed time for package llvm:x64-windows: 4.29 h

Total elapsed time: 4.291 h

The package llvm:x64-windows provides CMake targets:

    find_package(Clang CONFIG REQUIRED)
    # Note: 27 target(s) were omitted.
    target_link_libraries(main PRIVATE clangAST clangLex libclang clangEdit)

    find_package(LLVM CONFIG REQUIRED)
    # Note: 62 target(s) were omitted.
    target_link_libraries(main PRIVATE LTO LLVMMC ${name} LLVMLTO)

**Comment by aPSopt** [comment]
Hi @wangli28, today I tried fresh version on vcpkg and install llvm. Now it builds fine. Thx!)

> The following packages will be built and installed:
>   * atlmfc[core]:x64-windows
>     llvm[core]:x64-windows
> Additional packages (*) will be modified to complete this operation.
> Starting package 1/2: atlmfc:x64-windows
> Building package atlmfc[core]:x64-windows...
> -- Performing post-build validation
> -- Performing post-build validation done
> Building package atlmfc[core]:x64-windows... done
> Installing package atlmfc[core]:x64-windows...
> Installing package atlmfc[core]:x64-windows... done
> Elapsed time for package atlmfc:x64-windows: 1.072 s
> Starting package 2/2: llvm:x64-windows
> Building package llvm[core]:x64-windows...
> -- Downloading http://releases.llvm.org/8.0.0/llvm-8.0.0.src.tar.xz...
> -- Extracting source D:/libs/vcpkg_llvm/downloads/llvm-8.0.0.src.tar.xz
> -- Downloading http://releases.llvm.org/8.0.0/cfe-8.0.0.src.tar.xz...
> -- Extracting source D:/libs/vcpkg_llvm/downloads/cfe-8.0.0.src.tar.xz
> -- Applying patch install-cmake-modules-to-share.patch
> -- Applying patch fix-build-error.patch
> -- Downloading https://www.python.org/ftp/python/3.7.3/python-3.7.3-embed-win32.zip...
> -- Configuring x64-windows
> -- Building x64-windows-dbg
> -- Building x64-windows-rel
> -- Installing: D:/libs/vcpkg_llvm/packages/llvm_x64-windows/share/llvm/copyright
> -- Performing post-build validation
> -- Performing post-build validation done
> Building package llvm[core]:x64-windows... done
> Installing package llvm[core]:x64-windows...
> Installing package llvm[core]:x64-windows... done
> Elapsed time for package llvm:x64-windows: 50.17 min
> 
> Total elapsed time: 50.19 min
> 
> The package llvm:x64-windows provides CMake targets:
> 
>     find_package(Clang CONFIG REQUIRED)
>     # Note: 27 target(s) were omitted.
>     target_link_libraries(main PRIVATE clangAST clangLex libclang clangEdit)
> 
>     find_package(LLVM CONFIG REQUIRED)
>     # Note: 62 target(s) were omitted.
>     target_link_libraries(main PRIVATE LTO LLVMMC ${name} LLVMLTO)
