### ISSUE TITLE
[brotli] build error on x64-windows-static

### ISSUE THREAD

**Issue by yangyitzzg** [microsoft/vcpkg#40585]
### Operating system

windows10

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
vcpkg install brotli:x64-windows-static
```

### Failure logs

-- Using cached google-brotli-v1.1.0.tar.gz.
-- Cleaning sources at D:/vcpkg/buildtrees/brotli/src/v1.1.0-958bece74c.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/google-brotli-v1.1.0.tar.gz
-- Applying patch install.patch
-- Applying patch fix-arm-uwp.patch
-- Applying patch pkgconfig.patch
-- Applying patch emscripten.patch
-- Using source at D:/vcpkg/buildtrees/brotli/src/v1.1.0-958bece74c.clean
CMake Error at ports/brotli/portfile.cmake:14 (vcpkg_cmake_configure):
  Unknown CMake command "vcpkg_cmake_configure".
Call Stack (most recent call first):
  scripts/ports.cmake:192 (include)

**Comment by WangWeiLin-MV** [comment]
Using the latest version of vcpkg for local installation does not reproduce the issue.

Please try with latest vcpkg.

If the issue persists, please see #30604 for how to report a build failure.

**Comment by dg0yt** [comment]
In particular, you need `vcpkg upgrade [--no-dry-run]` to update installed ports.

**Comment by yangyitzzg** [comment]
>>vcpkg upgrade --no-dry-run
All installed packages are up-to-date.

D:\vcpkg>vcpkg install brotli:x64-windows-static
Computing installation plan...
The following packages will be built and installed:
    brotli:x64-windows-static@1.1.0#1
Detecting compiler hash for triplet x64-windows-static...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from C:\Users\x\AppData\Local\vcpkg\archives in 106 us. Use --debug to see more details.
Installing 1/1 brotli:x64-windows-static@1.1.0#1...
Building brotli:x64-windows-static@1.1.0#1...
-- Using cached google-brotli-v1.1.0.tar.gz.
-- Cleaning sources at D:/vcpkg/buildtrees/brotli/src/v1.1.0-958bece74c.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/google-brotli-v1.1.0.tar.gz
-- Applying patch install.patch
-- Applying patch fix-arm-uwp.patch
-- Applying patch pkgconfig.patch
-- Applying patch emscripten.patch
-- Using source at D:/vcpkg/buildtrees/brotli/src/v1.1.0-958bece74c.clean
CMake Error at ports/brotli/portfile.cmake:14 (vcpkg_cmake_configure):
  Unknown CMake command "vcpkg_cmake_configure".
Call Stack (most recent call first):
  scripts/ports.cmake:192 (include)


error: building brotli:x64-windows-static failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle brotli:x64-windows-static: 439 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+brotli
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[brotli]+Build+error+on+x64-windows-static&body=Copy+issue+body+from+D%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md


D:\vcpkg>vcpkg --version
vcpkg package management program version 2024-08-01-fd884a0d390d12783076341bd43d77c3a6a15658

See LICENSE.txt for license information.

**Comment by yangyitzzg** [comment]
this is issue_body.md:

Package: brotli:x64-windows-static@1.1.0#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.39.33520.0
-    vcpkg-tool version: 2024-08-01-fd884a0d390d12783076341bd43d77c3a6a15658
    vcpkg-scripts version: bb002e69d 2024-08-20 (22 hours ago)

**To Reproduce**

`vcpkg install brotli:x64-windows-static`

**Failure logs**

```
-- Using cached google-brotli-v1.1.0.tar.gz.
-- Cleaning sources at D:/vcpkg/buildtrees/brotli/src/v1.1.0-958bece74c.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/google-brotli-v1.1.0.tar.gz
-- Applying patch install.patch
-- Applying patch fix-arm-uwp.patch
-- Applying patch pkgconfig.patch
-- Applying patch emscripten.patch
-- Using source at D:/vcpkg/buildtrees/brotli/src/v1.1.0-958bece74c.clean
CMake Error at ports/brotli/portfile.cmake:14 (vcpkg_cmake_configure):
  Unknown CMake command "vcpkg_cmake_configure".
Call Stack (most recent call first):
  scripts/ports.cmake:192 (include)


```

**Comment by dg0yt** [comment]
`Unknown CMake command "vcpkg_cmake_configure".` is a clear indication of an outdated installed port `vcpkg-cmake`.
Please use `.\vcpkg` (maybe after `.\bootstrap-vcpkg.bat`) instead of `vcpkg`. Visual Studio's bundled `vcpkg` could be in the PATH, and IIRC it behaves different in some regards.

**Comment by yangyitzzg** [comment]
Yes, I understand very well, but I use \After vcpkg testing, the error still persists, which is very strange.

**Comment by WangWeiLin-MV** [comment]
Could you please try the command?
`./vcpkg.exe --vcpkg-root=. install brotli:x64-windows-static`

**Comment by yangyitzzg** [comment]
![20240822141001](https://github.com/user-attachments/assets/60df9e13-9163-44f6-b43b-d6e38ccd675a)

**Comment by WangWeiLin-MV** [comment]
Sorry I can't reproduce, please append `cmake` version like:

```ps1
Get-Command vcpkg
Get-Command cmake
```

And please try it from a new vcpkg instance, you could custom the new directory:

```ps1
$SomeNewDir = "D:\vcpkg-40585"

mkdir $SomeNewDir
cd $SomeNewDir
& git clone https://github.com/microsoft/vcpkg
cd vcpkg
$env:Path = "$SomeNewDir\vcpkg;" + $env:Path
& bootstrap-vcpkg.bat

./vcpkg.exe install brotli
```

**Comment by yangyitzzg** [comment]
I reset operating system and re git vcpkg, and the problem was resolved. Thank you!
