### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by Fabi12345** [microsoft/vcpkg#40595]
Doesn't recognize the command: "./vcpkg install assimp"

**Environment**
- OS: W10
- Compiler: shell

**To Reproduce**
git clone https://github.com/Microsoft/vcpkg.git
    cd vcpkg
    ./bootstrap-vcpkg.sh
    ./vcpkg integrate install
    ./vcpkg install assimp

**Comment by greenozon** [comment]
regarding
>Doesn't recognize the command: "./vcpkg install assimp"

could you show the errors it shows?

also make sure you have the dir vcpkg\ports\assimp\  with the contents

**Comment by FrankXie05** [comment]
@greenozon Thanks for postint this issue, could you please provide the erro log?

**Comment by greenozon** [comment]
I guess we should ask @Fabi12345   as issue originator!

**Comment by FrankXie05** [comment]
> I guess we should ask @Fabi12345 as issue originator!

Sorry for this. 😅

**Comment by Fabi12345** [comment]
I don't know where the relevant log file is located, there is so many of them. I tried one more thing since this error occurred, installing from visual studio and then it automatically installed a few more packages, it didn't throw an error this time, so I think its fine now, but haven't checked yet.

**Comment by greenozon** [comment]
@Fabi12345  the vcpkg will print the path to all logs files in the screen

just follow those andd then either drag-n-drop into your 1st post or add using Details  GH command (press / then select Details and copy-paste the log file contents) - in this case you'll see the ">" sign that will collapse/expand - very handy feature!

**Comment by dg0yt** [comment]
> Doesn't recognize the command: "./vcpkg install assimp"

Note that `/` is the separator for POSIX paths. Windows tolerates it in some places, but `cmd` still wants to see `\`.

**Comment by Fabi12345** [comment]
When I opened this issue I used the normal Windows shell (cmd), and that just said it doesn't recognize the command "./vcpkg install assimp", thats all. Then I tried in Visual Studio Developer Powershell and that worked successfully.
