### ISSUE TITLE
[zlib] building zlib:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by vadimGoodmen** [microsoft/vcpkg#40602]
### Operating system

windows

### Compiler

vcpkg

### Steps to reproduce the behavior

```Shell
error: building zlib:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle zlib:x64-windows: 54.5 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+zlib
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[zlib]+Build+error+on+x64-windows&body=Copy+issue+body+from+D%3A%2F%D0%91%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B8%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
```

### Failure logs

error: building zlib:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle zlib:x64-windows: 54.5 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+zlib
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[zlib]+Build+error+on+x64-windows&body=Copy+issue+body+from+D%3A%2F%D0%91%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B8%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

error: building zlib:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle zlib:x64-windows: 54.5 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+zlib
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[zlib]+Build+error+on+x64-windows&body=Copy+issue+body+from+D%3A%2F%D0%91%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B8%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by greenozon** [comment]
please fix the issue name! :) 
its too large now :100: 

![image](https://github.com/user-attachments/assets/f87819f5-2737-4bad-9cc1-d604fe0c7903)

**Comment by sfhacker** [comment]
This is embarrassing! Will report this user.

**Comment by MonicaLiu0311** [comment]
Please provide the detail error log.

**Comment by MonicaLiu0311** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
