### ISSUE TITLE
[ARROW] build failure

### ISSUE THREAD

**Issue by diehard2** [microsoft/vcpkg#40610]
### Operating system

AlamLinux 8.9

### Compiler

gcc 13.1

### Steps to reproduce the behavior

```Shell
vcpkg install with the following in the manifest file

 {
            "name": "arrow",
            "features": [
                "csv",
                "filesystem",
                "json",
                "parquet",
                "jemalloc"
            ]
        },
```

### Failure logs

FAILED: jemalloc_ep-prefix/src/jemalloc_ep-stamp/jemalloc_ep-install /home/dev/DDS/build/_deps/vcpkg-src/buildtrees/arrow/dds-dbg/jemalloc_ep-prefix/src/jemalloc_ep-stamp/jemalloc_ep-install 
cd /home/dev/DDS/build/_deps/vcpkg-src/buildtrees/arrow/dds-dbg/jemalloc_ep-prefix/src/jemalloc_ep && /home/dev/DDS/build/_deps/vcpkg-src/downloads/tools/cmake-3.29.2-linux/cmake-3.29.2-linux-x86_64/bin/cmake -P /home/dev/DDS/build/_deps/vcpkg-src/buildtrees/arrow/dds-dbg/jemalloc_ep-prefix/src/jemalloc_ep-stamp/jemalloc_ep-install-DEBUG.cmake && /home/dev/DDS/build/_deps/vcpkg-src/downloads/tools/cmake-3.29.2-linux/cmake-3.29.2-linux-x86_64/bin/cmake -E touch /home/dev/DDS/build/_deps/vcpkg-src/buildtrees/arrow/dds-dbg/jemalloc_ep-prefix/src/jemalloc_ep-stamp/jemalloc_ep-install
CMake Error at /home/dev/DDS/build/_deps/vcpkg-src/buildtrees/arrow/dds-dbg/jemalloc_ep-prefix/src/jemalloc_ep-stamp/jemalloc_ep-install-DEBUG.cmake:37 (message):
  Command failed: 2

   '/usr/bin/make' '-j1' 'install'

  See also

    /home/dev/DDS/build/_deps/vcpkg-src/buildtrees/arrow/dds-dbg/jemalloc_ep-prefix/src/jemalloc_ep-stamp/jemalloc_ep-install-*.log

-- stdout output is:
build-aux/install-sh -c -d /home/dev/DDS/build/_deps/vcpkg-src/buildtrees/arrow/dds-dbg/jemalloc_ep-prefix/src/jemalloc_ep/dist/bin
install:  -v does not exist
install:  -v does not exist
install:  -v does not exist

-- stderr output is:
make: *** [Makefile:557: install_bin] Error 1

### Additional context

it looks like its trying to install jemalloc as a third party dependency.

**Comment by dg0yt** [comment]
> jemalloc_ep-prefix

Oops, arrow building an `ExternalProject`? The port must stop this.

**Comment by jimwang118** [comment]
Sorry, i can`t reproduce this issue locally.
![image](https://github.com/user-attachments/assets/deb42060-7a0e-44d6-a9f5-8537b7ca23c4)

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
