### ISSUE TITLE
Random failures in extraction on Mac + Docker

### ISSUE THREAD

**Issue by diehard2** [microsoft/vcpkg#40615]
**Describe the bug**
In a bind mount between a Mac directory (M3) and Docker (using Colima) I occasionally get the following errors on random ports

Problem with archive_write_finish_entry(): Can't restore time

This is seen in zstd. In particular it is having trouble with symbolic links in the archive. However I have seen it in other archives that do not have symbolic links, but I haven't dug any further.

**Environment**
- OS: AlmalLinux 8.9 with QEMU X86 emulation through Colima on MacOS Sonoma 14.6.1

**To Reproduce**
1. bind a directory from mac to a docker container (almalinux 8.9 in my case)
2. vcpkg install zstd

**Expected behavior**
The archive would extract correctly

**Failure logs**
Problem with archive_write_finish_entry(): Can't restore time

**Additional context**
It looks like cmake rolled their own version of tar that can't handle time stamps that are incorrect. The system tar does handle this correctly with the -m flag. I have fixed this locally by patching vcpkg with 

COMMAND /usr/bin/tar -mxzf "${arg_ARCHIVE}" 

in line 122 of vcpkg-src/scripts/cmake/vcpkg_extract_source_archive.cmake

would be nice to switch to the official system tar, although I recognize this is most likely a colima bug (and I'll report there also)

**Comment by MonicaLiu0311** [comment]
Sorry for the late reply, could you provide the specific error log? I would like to compare it with #28527.

**Comment by diehard2** [comment]
Hi Monica, sorry for the late reply here also!

The log is simply 
Problem with archive_write_finish_entry(): Can't restore time

there was nothing else in the logs. It just bombs out nearly immediately. Tar also has this problem is you don't use the -m flag. In that particular tar file it had something to do with symbolic links, so it would succeed that second time you run the command. however, that's not possible with vcpkg. Its been awhile, but I believe this was solely on Colima, I think Docker Desktop worked as expected
