### ISSUE TITLE
can not install libmysql x64

### ISSUE THREAD

**Issue by haifeng2170** [Microsoft/vcpkg#4062]
I need to install poco[mysql]:x64-windows, so first I install
 libmysql:x64-windows, unfortunately, it failed,  then I checked 
the ports/libmysql/ignore-boost-version.patch,
it need boost 1.65,but the recent is 1.67, how to resolve?

**Comment by NancyLi1013** [comment]
Thanks for posting this issue. I cannot reproduce it on the latest vcpkg now.
Please open a new issue if this is still a problem for you.
