### ISSUE TITLE
liburing update to 2.7

### ISSUE THREAD

**Issue by 0xg0nz0** [microsoft/vcpkg#40621]
### Library name

liburing

### New version number

2.7

### Other information that may be useful (release notes, etc...)

Bug fixes since April 2024 + sync to kernel 6.10 (aligned with Ubuntu Noble kernel):

https://github.com/axboe/liburing/releases/tag/liburing-2.7

**Comment by dg0yt** [comment]
https://github.com/microsoft/vcpkg/pull/40601
