### ISSUE TITLE
Add Embedded template Library

### ISSUE THREAD

**Issue by jwellbelove** [microsoft/vcpkg#4063]
Add the C++ Embedded template Library.
https://www.etlcpp.com
https://github.com/ETLCPP/etl.git

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!

**Comment by jwellbelove** [comment]
Are there any tutorials on the details on how a new package is added to vcpkg.
I can see a 'ports' directory which I assume contains the details of each package, but what files are expected to be in there, and what must they contain? I can hack an existing one, but it's not clear whether I'm covering all the bases.

**Comment by jwellbelove** [comment]
For example:

```
PS D:\Users\John\Documents\Programming\GitHub\vcpkg> ./vcpkg install etl
Computing installation plan...
The following packages will be built and installed:
    etl[core]:x86-windows
Starting package 1/1: etl:x86-windows
Building package etl[core]:x86-windows...
-- Downloading https://github.com/ETLCPP/etl/archive/18.3.0.tar.gz...
-- Extracting source D:/Users/John/Documents/Programming/GitHub/vcpkg/downloads/ETLCPP-etl-18.3.0.tar.gz
-- Using source at D:/Users/John/Documents/Programming/GitHub/vcpkg/buildtrees/etl/src/18.3.0-e725730664
-- Performing post-build validation
The folder /include is empty or not present. This indicates the library was not correctly installed.
The software license must be available at ${CURRENT_PACKAGES_DIR}/share/etl/copyright

    configure_file("${CURRENT_BUILDTREES_DIR}/src/18.3.0-e725730664/LICENSE/LICENSE" "${CURRENT_PACKAGES_DIR}/share/etl/copyright" COPYONLY)
Found 2 error(s). Please correct the portfile:
    D:\Users\John\Documents\Programming\GitHub\vcpkg\ports\etl\portfile.cmake
-- Performing post-build validation done
Error: Building package etl:x86-windows failed with: POST_BUILD_CHECKS_FAILED
```
Where is ${CURRENT_PACKAGES_DIR} supposed to be?
Why is it trying to build ANYTHING? This is a C++ header only template library. There is nothing to build!

**Comment by jwellbelove** [comment]
And why is it installing for 'x86-windows'? This is a cross platform library.

**Comment by JackBoosY** [comment]
@jwellbelove See documentation:
https://github.com/microsoft/vcpkg/blob/master/docs/examples/packaging-zipfiles.md
https://github.com/microsoft/vcpkg/blob/master/docs/examples/packaging-github-repos.md

You can find several examples in _VCPKG_PATH/ports_.
