### ISSUE TITLE
[vcpkg-tool]vcpkg_abi_info.txt add glibc/glibcxx on Linux

### ISSUE THREAD

**Issue by iHuahua** [microsoft/vcpkg#40639]
Different versions of GLIBC/GLIBCXX cause the binaries to be non-generic

**Environment**
- OS: Linux(Ubuntu/CentOS)
- Compiler: clang
- Vcpkg: manifest mode

**Environment Variable**
- VCPKG_BINARY_SOURCES="clear;http,http://mysvr/{name}/{triplet}/{version}/{sha},readwrite"
- VCPKG_FORCE_DOWNLOADED_BINARIES=1

**Failure logs**
```
[CMake Build] /data/workspace/out/build/Release/vcpkg_installed/x64-linux/tools/protobuf/protoc-3.21.12.0: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /data/workspace/out/build/Release/vcpkg_installed/x64-linux/tools/protobuf/protoc-3.21.12.0)
[CMake Build] /data/workspace/out/build/Release/vcpkg_installed/x64-linux/tools/protobuf/protoc-3.21.12.0: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /data/workspace/out/build/Release/vcpkg_installed/x64-linux/tools/protobuf/protoc-3.21.12.0)
```

**To Reproduce**
In my project, some environment OS is Ubuntu, some is CentOS, a machine which has a high version GLIBC/GLIBCXX build binary and upload to remote storage, the other machine which has lower version GLIBC will build failed. pls add GLIBC/GLIBCC to calc abi info.

看了一下 vcpkg-tool 的代码，在计算`vcpkg abi info`时似乎并没有看到GLIBC相关参与，导致高版本GLIBC编译的二进制产物，被低版本系统拉取到时无法使用，在CI过程中遇到这种情况就很棘手，是否可以让 GLIBC/GLIBCXX 参与计算 abi info？

**Comment by Osyotr** [comment]
It kinda works if you don't disable `VCPKG_DISABLE_COMPILER_TRACKING`.
The problem with glibc and abi hashing is that the latter right now requires exact match.

**Comment by iHuahua** [comment]
Thx for relay, I did not disable it manually, But `set(VCPKG_DISABLE_COMPILER_TRACKING 1)` has been setted in `x64-linux.cmake` triplet.

**Comment by Osyotr** [comment]
It is not set by default.
https://github.com/microsoft/vcpkg/blob/master/triplets/x64-linux.cmake

**Comment by iHuahua** [comment]
> It is not set by default. https://github.com/microsoft/vcpkg/blob/master/triplets/x64-linux.cmake

Thanks much!!! I made a mistake and my project (someone) modified the triplet, sorry
