### ISSUE TITLE
[opecv4] build failure

### ISSUE THREAD

**Issue by StormCheats** [microsoft/vcpkg#40680]
### Operating system

x64-windows

### Compiler

MSVC 19.41.34120.0

### Steps to reproduce the behavior

```Shell
vcpkg install opencv[contrib,freetype,jpeg,openmp,png,webp,world]:x64-windows
```

### Failure logs

-- Using cached opencv4-e5e1a3bfdea96bebda2ad963bc8f6cf17930aef7.patch.
-- Using cached opencv4-3e3ee106fb8ccd003aa2c9a943a2340b066537bc.patch.
-- Using cached opencv-opencv-4.8.0.tar.gz.
-- Cleaning sources at E:/src/vcpkg/buildtrees/opencv4/src/4.8.0-f4e8005717.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/src/vcpkg/downloads/opencv-opencv-4.8.0.tar.gz
-- Applying patch 0001-disable-downloading.patch
-- Applying patch 0002-install-options.patch
-- Applying patch 0003-force-package-requirements.patch
-- Applying patch 0004-fix-eigen.patch
-- Applying patch 0005-fix-policy-CMP0057.patch
-- Applying patch 0006-fix-uwp.patch
-- Applying patch 0008-devendor-quirc.patch
-- Applying patch 0009-fix-protobuf.patch
-- Applying patch 0010-fix-uwp-tiff-imgcodecs.patch
-- Applying patch 0011-remove-python2.patch
-- Applying patch 0012-fix-zlib.patch
-- Applying patch 0015-fix-freetype.patch
-- Applying patch 0017-fix-flatbuffers.patch
-- Applying patch 0019-missing-include.patch
-- Applying patch 0020-fix-compat-cuda12.2.patch
-- Applying patch 0021-static-openvino.patch
-- Applying patch E:/src/vcpkg/downloads/opencv4-e5e1a3bfdea96bebda2ad963bc8f6cf17930aef7.patch
-- Applying patch 0022-fix-supportqnx.patch
-- Applying patch E:/src/vcpkg/downloads/opencv4-3e3ee106fb8ccd003aa2c9a943a2340b066537bc.patch
-- Using source at E:/src/vcpkg/buildtrees/opencv4/src/4.8.0-f4e8005717.clean
-- Using cached opencv-cache/tiny_dnn/adb1c512e09ca2c7a6faef36f9c53e59-v1.0.0a3.tar.gz.
-- Using cached opencv-contrib-1ed3dd2c53888e3289afdb22ec4e9ebbff3dba87.patch.
-- Using cached opencv-contrib-9358ad2e56f6d0b99860856fc1b53b783d186e73.patch.
-- Using cached opencv-contrib-baaeb68b3d6b557536f95b527c0dd87c8f1ce80d.patch.
-- Using cached opencv-opencv_contrib-4.8.0.tar.gz.
-- Cleaning sources at E:/src/vcpkg/buildtrees/opencv4/src/4.8.0-59c03c175c.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/src/vcpkg/downloads/opencv-opencv_contrib-4.8.0.tar.gz
-- Applying patch 0007-fix-hdf5.patch
-- Applying patch 0016-fix-freetype-contrib.patch
-- Applying patch 0018-fix-depend-tesseract.patch
-- Applying patch 0019-fix-ogre-dependency.patch
-- Applying patch E:/src/vcpkg/downloads/opencv-contrib-1ed3dd2c53888e3289afdb22ec4e9ebbff3dba87.patch
-- Applying patch E:/src/vcpkg/downloads/opencv-contrib-9358ad2e56f6d0b99860856fc1b53b783d186e73.patch
-- Applying patch E:/src/vcpkg/downloads/opencv-contrib-baaeb68b3d6b557536f95b527c0dd87c8f1ce80d.patch
-- Using source at E:/src/vcpkg/buildtrees/opencv4/src/4.8.0-59c03c175c.clean
-- Using cached opencv-cache/wechat_qrcode/238e2b2d6f3c18d6c3a30de0c31e23cf-detect.caffemodel.
-- Using cached opencv-cache/wechat_qrcode/cbfcd60361a73beb8c583eea7e8e6664-sr.caffemodel.
-- Using cached opencv-cache/wechat_qrcode/6fb4976b32695f9f5c6305c19f12537d-detect.prototxt.
-- Using cached opencv-cache/wechat_qrcode/69db99927a70df953b471daaba03fbef-sr.prototxt.
-- Using cached opencv-cache/xfeatures2d/boostdesc/0ea90e7a8f3f7876d450e4149c97c74f-boostdesc_bgm.i.
-- Using cached opencv-cache/xfeatures2d/boostdesc/232c966b13651bd0e46a1497b0852191-boostdesc_bgm_bi.i.
-- Using cached opencv-cache/xfeatures2d/boostdesc/324426a24fa56ad9c5b8e3e0b3e5303e-boostdesc_bgm_hd.i.
-- Using cached opencv-cache/xfeatures2d/boostdesc/202e1b3e9fec871b04da31f7f016679f-boostdesc_binboost_064.i.
-- Using cached opencv-cache/xfeatures2d/boostdesc/98ea99d399965c03d555cef3ea502a0b-boostdesc_binboost_128.i.
-- Using cached opencv-cache/xfeatures2d/boostdesc/e6dcfa9f647779eb1ce446a8d759b6ea-boostdesc_binboost_256.i.
-- Using cached opencv-cache/xfeatures2d/boostdesc/0ae0675534aa318d9668f2a179c2a052-boostdesc_lbgm.i.
-- Using cached opencv-cache/xfeatures2d/vgg/e8d0dcd54d1bcfdc29203d011a797179-vgg_generated_48.i.
-- Using cached opencv-cache/xfeatures2d/vgg/7126a5d9a8884ebca5aea5d63d677225-vgg_generated_64.i.
-- Using cached opencv-cache/xfeatures2d/vgg/7cd47228edec52b6d82f46511af325c5-vgg_generated_80.i.
-- Using cached opencv-cache/xfeatures2d/vgg/151805e03568c9f490a5e3a872777b75-vgg_generated_120.i.
-- Using cached opencv-cache/data/7505c44ca4eb54b4ab1e4777cb96ac05-face_landmark_model.dat.
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j13
    Working Directory: E:/src/vcpkg/buildtrees/opencv4/x64-windows-dbg
    See logs for more information:
      E:\src\vcpkg\buildtrees\opencv4\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/opencv4/portfile.cmake:508 (vcpkg_cmake_install)
  scripts/ports.cmake:192 (include)
  
  
[install-x64-windows-dbg-out.log](https://github.com/user-attachments/files/16780815/install-x64-windows-dbg-out.log)

**Comment by StormCheats** [comment]
this fixed it for me: https://github.com/microsoft/vcpkg/issues/34247#issuecomment-2227320165

**Comment by greenozon** [comment]
Could you make sure that you are really missing ms vc redistl libs using for example this util?
https://www.dependencywalker.com/
