### ISSUE TITLE
[protobuf] incorrect upstream version specified in vcpkg.json

### ISSUE THREAD

**Issue by majaeger** [microsoft/vcpkg#40689]
### Library name

protobuf

### New version number

3.25.1

### Other information that may be useful (release notes, etc...)

It looks like protobuf was updated to version 3.25.1 with this commit https://microsoft.visualstudio.com/Analog/_git/mixedreality.cloud.oss.vcpkg/commit/561d171d797c2210308128d6ab64f1fe510a35b4?refName=refs%2Fheads%2Fmaster&path=%2Fports%2Fprotobuf%2Fvcpkg.json&_a=compare, however the version in the manifest was incorrectly entered as 4.25.1

**Comment by WangWeiLin-MV** [comment]
Protobuf released https://github.com/protocolbuffers/protobuf/commit/7f94235e552599141950d7a4a3eaf93bc87d1b22 with both https://github.com/protocolbuffers/protobuf/releases/tag/v4.25.1 and https://github.com/protocolbuffers/protobuf/releases/tag/v3.25.1

**Comment by majaeger** [comment]
Ah, I see. Please disregard!
