### ISSUE TITLE
[NEWS] OpenJDK from Microsoft

### ISSUE THREAD

**Issue by Voskrese** [Microsoft/vcpkg#4069]
I read the instructions and came across an amazing news, decided to share
it will be useful, who compiles for android from under windows

> download the correct build for your system.

https://docs.microsoft.com/ru-ru/xamarin/android/get-started/installation/openjdk

Mac – https://dl.xamarin.com/OpenJDK/mac/microsoft-dist-openjdk-1.8.0.9.zip
Windows x86 – https://dl.xamarin.com/OpenJDK/win32/microsoft-dist-openjdk-1.8.0.9.zip
Windows x64 – https://dl.xamarin.com/OpenJDK/win64/microsoft-dist-openjdk-1.8.0.9.zip

**Comment by AshleyKwan** [comment]
The domain was closed, so cannot continue downloading the correct version.

**Comment by MVoz** [comment]
> The domain was closed, so cannot continue downloading the correct version.

<img width="1326" height="802" alt="Image" src="https://github.com/user-attachments/assets/cf9a8f4f-7e1c-4fea-afc4-c16bd7b538b0" />

https://docs.microsoft.com/java/openjdk/download
