### ISSUE TITLE
Can't build a sample project with vcpkg installed sqlite3 in visual studio 2015

### ISSUE THREAD

**Issue by liuliushimonkey** [Microsoft/vcpkg#4071]
Hello,
  I'm having a compile problem after installing sqlite3 from vcpkg. I have created a new project with a couple of lines, with "#include <sqlite3.h>". I fail to compile the project, here's the error message:
Can you please help? Thanks!

 Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3075	The command "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -noprofile -File "C:\DevLiu\C++\Vcpkg\vcpkg-master\vcpkg-master\scripts\buildsystems\msbuild\applocal.ps1" "C:\DevLiu\C++\TestSqlite\Debug\TestSqlite.exe" "C:\DevLiu\C++\Vcpkg\vcpkg-master\vcpkg-master\installed\x86-windows\debug\bin" "Debug\TestSqlite.tlog\TestSqlite.write.1u.tlog" "Debug\vcpkg.applocal.log"" exited with code 5. Please verify that you have sufficient rights to run this command.	TestSqlite	C:\DevLiu\C++\Vcpkg\vcpkg-master\vcpkg-master\scripts\buildsystems\msbuild\vcpkg.targets	85

**Comment by liuliushimonkey** [comment]
I think it's related to my fireware, resolved now.

**Comment by rishavghosh605** [comment]
Hey I am having the same problem. Can you tell me how to solve this problem?
