### ISSUE TITLE
Can't install boost from vcpkg

### ISSUE THREAD

**Issue by liuliushimonkey** [Microsoft/vcpkg#4073]
I had no problem installing sqlite3, but as for boost, I have the following error: 
I'm not using a proxy, and when I tried to access this link:https://github.com/boostorg/preprocessor/archive/boost-1.67.0.tar
.gz. I can't find it. Can you please help? Thanks!

-- Downloading https://github.com/boostorg/preprocessor/archive/boost-1.67.0.tar
.gz... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:151 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/is
sues

**Comment by Voskrese** [comment]
`https://github.com/boostorg/preprocessor/archive/boost-1.67.0.tar.gz`

**Comment by liuliushimonkey** [comment]
Thanks, it works now
