### ISSUE TITLE
Visual studio integration fails to rebuild dependencies on compiler version change

### ISSUE THREAD

**Issue by duckdoom4** [microsoft/vcpkg#40737]
**Describe the bug**
I'm using the visual studio integrated version of vckpg, which uses MSBuild to run vcpkg commands etc.

I'm building my packages as static libs and because of that I receive errors every time the compiler version is updated because a version change does not trigger a vcpkg rebuild. (eg. `my-lib.lib was compiled with a different version of the compiler`)

**Environment**
- OS: Windows
- Compiler: Not relevant (old bug and latest version still has this issue)

**To Reproduce**
1. Build a project with vcpkg manifest dependencies using an older version of the compiler
   (Note: the need to be static libs to receive the error)
2. Build the project again with a newer version of the compiler
3. Notice the error when attempting to build

**Expected behavior**
vcpkg manifest dependencies are rebuild when the compiler version doesn't match the previously used version.

**Failure logs**
eg. `my-lib.lib was compiled with a different version of the compiler`

**Additional context**
Old bug
Visual studio integrated version of vckpg
MSBuild

**Comment by Osyotr** [comment]
Please post the exact error message.

**Comment by duckdoom4** [comment]
That's litterally the error message `assimp-vc143-mt.lib was compiled with a different version of the compiler`

**Comment by JonLiu1993** [comment]
The next line of the log you posted should be the error. Can you send your complete error log?
````
assimp-vc143-mt.lib was compiled with a different version of the compiler
````
