### ISSUE TITLE
Issue in installing signalRclient using vcpkg

### ISSUE THREAD

**Issue by ShailjaDataman** [Microsoft/vcpkg#4075]
On installing vcpkg using command "vcpkg install signalrclient" getting error : 

The following packages will be built and installed:
    signalrclient[core]:x86-windows
Starting package 1/1: signalrclient:x86-windows
Building package signalrclient[core]:x86-windows...
-- Using cached C:/Users/dataman/vcpkg/downloads/SignalR-SignalR-Client-Cpp-1.0.0-beta1.tar.gz
-- Using source at C:/Users/dataman/vcpkg/buildtrees/signalrclient/src/.0.0-beta1-a6e6078b32
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at C:/Users/dataman/vcpkg/scripts/cmake/vcpkg_build_cmake.cmake:170 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No
    Working Directory: C:/Users/dataman/vcpkg/buildtrees/signalrclient/x86-windows-dbg
    See logs for more information:
      C:\Users\dataman\vcpkg\buildtrees\signalrclient\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  C:/Users/dataman/vcpkg/scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  C:/Users/dataman/vcpkg/ports/signalrclient/portfile.cmake:24 (vcpkg_install_cmake)
  C:/Users/dataman/vcpkg/scripts/ports.cmake:71 (include)

Error: Building package signalrclient:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: signalrclient:x86-windows
  Vcpkg version: 0.0.113-nohash

for Reference i have attached install-x86-windows-dbg-out.log
[install-x86-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2282163/install-x86-windows-dbg-out.log)
[install-x86-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2282165/install-x86-windows-dbg-out.log)

**Comment by Voskrese** [comment]
`LINK : fatal error LNK1104: cannot open file 'C:\Users\dataman\vcpkg\installed\x86-windows\debug\lib\cpprest_2_10.lib' `

**Comment by PhoebeHui** [comment]
After install cpprestsdk, it installed  .\VCPKG\src\installed\x86-windows\debug\libcpprest_2_10d.lib, but here it try to find .\VCPKG\src\installed\x86-windows\debug\lib\cpprest_2_10.lib. The file name need fix.

**Comment by alangab** [comment]
Hi,
I go around this problem simply copying libcpprest_2_10d.lib into libcpprest_2_10.lib in the same folder.
But... there is another problem.... The package is missing openssl lib . We get this error now:
unresolved external symbol _CRYPTO_cleanup_all_ex_data referenced public: __thiscall boost::asio::ssl::detail::openssl_init_base::do_init::~do_init(void) and so on...
Is there any way to change locally the package to build successfully this package?
TIA

**Comment by JackBoosY** [comment]
@alangab  I didn't find any problems on the latest version. Maybe you should update and rebuild this port.

**Comment by JackBoosY** [comment]
Hi @ShailjaDataman , thanks for reporting this issue!
This issue has been fixed. Plz update vcpkg and rebuild signalrclient.
Thanks.

**Comment by alangab** [comment]
Hi    JackBoosY
Thanks for the information , i tryed again and it works now.
I cannot answer immediately,

Bye



Il giorno gio 18 apr 2019 alle ore 06:06 JackBoosY <notifications@github.com>
ha scritto:
