### ISSUE TITLE
[qtbase] build failure for x64-android

### ISSUE THREAD

**Issue by 12udi** [microsoft/vcpkg#40762]
After fixing some issues with dbus in its portfile.cmake due to linking issues and passing the ANDROID_SDK_ROOT as an export directly to the qt_install_submodule.cmake the build finally fails at qtbase config step. Is there anything I might miss when trying to compiling on x64 linux host.

```
ERROR: Feature "openssl": Forcing to "ON" breaks its condition:
    QT_FEATURE_openssl_runtime OR QT_FEATURE_openssl_linked
Condition values dump:
    QT_FEATURE_openssl_runtime = "OFF"
    QT_FEATURE_openssl_linked = "OFF"

ERROR: Feature "libresolv": Forcing to "ON" breaks its condition:
    WrapResolv_FOUND
Condition values dump:
    WrapResolv_FOUND = "FALSE"
```

[config-x64-android-out.log](https://github.com/user-attachments/files/16840952/config-x64-android-out.log)

**Comment by 12udi** [comment]
@LilyWangLL, do you need some infos how to reproduce or my setup where the issue occured? I actually could reproduce this on fedora 40 and on an WSL running ubuntu latest.

**Comment by LilyWangLL** [comment]
> @LilyWangLL, do you need some infos how to reproduce or my setup where the issue occured? I actually could reproduce this on fedora 40 and on an WSL running ubuntu latest.

Nothing, I currently don't have a test environment locally to reproduce this issue.

**Comment by justusranvier** [comment]
> passing the ANDROID_SDK_ROOT as an export directly to the qt_install_submodule.cmake

Now that Android triplets are officially supported is it possible to get an actual resolution for #26500?

"provide your own andorid toolchain which does stuff like that" made sense for a community triplet but not for a supported triplet.

**Comment by dg0yt** [comment]
You might help fixing https://github.com/microsoft/vcpkg/pull/35845.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
