### ISSUE TITLE
Error on install sdl2 curl

### ISSUE THREAD

**Issue by sraja12184** [Microsoft/vcpkg#4076]
I am receiving the following error upon doing ".\vcpkg install sdl2 curl" as mentioned in the vcpkg github page.

The following packages will be built and installed:
    curl[core,ssl]:x86-windows
  * openssl[core]:x86-windows
  * openssl-windows[core]:x86-windows
    sdl2[core]:x86-windows
  * zlib[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/5: sdl2:x86-windows
Building package sdl2[core]:x86-windows...
-- Downloading https://github.com/SDL-Mirror/SDL/archive/release-2.0.8.tar.gz...
-- Downloading https://github.com/SDL-Mirror/SDL/archive/release-2.0.8.tar.gz... Failed. Status: 4;"A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision."
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:151 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:108 (vcpkg_download_distfile)
  ports/sdl2/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:71 (include)

Error: Building package sdl2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sdl2:x86-windows
  Vcpkg version: 0.0.113-nohash

Additionally, attach any relevant sections from the log files above.

I have set the HTTP_PROXY and HTTPS_PROXY environmental variables as well. I didn't find any log files to attach with.

Thanks,
Raja

**Comment by Voskrese** [comment]
check your connection via ping \ ping

`ping google.com`

here most of the messages about it, or the site is temporarily unavailable, or the Internet itself simply has a buggy

and your file is downloaded normally through the browser

> проверьте свое соединение через пинг\ping
> 
> ping google.com
> 
> тут большинство сообщений про это, либо сайт временно недоступен, либо у самого просто интернет глючит
> 
> а ваш файл через браузер нормально скачивается

**Comment by sraja12184** [comment]
@Voskrese My internet works fine. I can download it normally through the browser but I don't know if my C++Rest applications works further or not(Because I dont know if I need to install these packages)
It seems, 5 packages will be downloaded along with this command. I could see the first one itself is failing SDL-Mirror.

**Comment by Voskrese** [comment]
close the terminal and open it and enter the necessary commands, here write that it helps

> закройте терминал и заного открой и введите нужные команды, здесь пишут что это помогает

**Comment by sraja12184** [comment]
@Voskrese I have executed all the commands after machine restart. Still facing the issue. Any idea how to resolve it.

**Comment by Voskrese** [comment]
you can download manually all the necessary source files and put them in the download folder
vcpkg uses it as a cache and takes it from there, if there is a file with the same name, then nothing is downloaded

> вы можете скачать вручную все необходимые исходные файлы и поместить их в папку download
> vcpkg использует ее как кеш и берет от туда, если там имеется одноименный файл, то ничего не скачивается

**Comment by sraja12184** [comment]
thanks for the response. do we need to install from cmake toolchain file? 
it is observed that the URL  "https://github.com/SDL-Mirror/SDL/archive/" doesn't exist. it is the same case for most of the projects such as boostorg/preprocessor etc.

**Comment by Voskrese** [comment]
https://github.com/SDL-mirror/SDL/releases

**Comment by sraja12184** [comment]
Thanks its working. 
I followed this approach: For any failed installs, download it manually from GitHub and place it in downloads folder of vcpkg(don't extract). Then execute "install" command.
