### ISSUE TITLE
[pkgconf] build failure on windows

### ISSUE THREAD

**Issue by stvsl** [microsoft/vcpkg#40766]
### Operating system

Windows

### Compiler

MSVC 14.41.34120

### Steps to reproduce the behavior

```Shell
vcpkg install pkgconf
```

### Failure logs

PS C:\vcpkg> vcpkg install pkgconf
Computing installation plan...
The following packages will be built and installed:
    pkgconf:x64-windows@2.3.0
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from C:\Users\aptx4\AppData\Local\vcpkg\archives in 97.1 us. Use --debug to see more details.
Installing 1/1 pkgconf:x64-windows@2.3.0...
Building pkgconf:x64-windows@2.3.0...
-- Found Python version '3.11.8 at C:/vcpkg/downloads/tools/python/python-3.11.8-x64/python.exe'
-- Using meson: C:/vcpkg/downloads/tools/meson-1.5.1-81f7e3/meson.py
-- Using cached pkgconf-pkgconf-pkgconf-2.3.0.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/pkgconf/src/conf-2.3.0-07e4a066bf.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/pkgconf-pkgconf-pkgconf-2.3.0.tar.gz
-- Using source at C:/vcpkg/buildtrees/pkgconf/src/conf-2.3.0-07e4a066bf.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-dbg
-- Getting CMake variables for x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/vcpkg/buildtrees/pkgconf/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\pkgconf\cmake-get-vars-x64-windows-dbg-CMakeCache.txt.log
      C:\vcpkg\buildtrees\pkgconf\cmake-get-vars-x64-windows-rel-CMakeCache.txt.log
      C:\vcpkg\buildtrees\pkgconf\cmake-get-vars-x64-windows-dbg-CMakeConfigureLog.yaml.log
      C:\vcpkg\buildtrees\pkgconf\cmake-get-vars-x64-windows-rel-CMakeConfigureLog.yaml.log
      C:\vcpkg\buildtrees\pkgconf\cmake-get-vars-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:269 (vcpkg_execute_required_process)
  installed/x64-windows/share/vcpkg-cmake-get-vars/vcpkg_cmake_get_vars.cmake:15 (vcpkg_cmake_configure)
  installed/x64-windows/share/vcpkg-tool-meson/vcpkg_configure_meson.cmake:323 (vcpkg_cmake_get_vars)
  installed/x64-windows/share/vcpkg-tool-meson/vcpkg_configure_meson.cmake:458 (vcpkg_generate_meson_cmd_args)
  ports/pkgconf/portfile.cmake:9 (vcpkg_configure_meson)
  scripts/ports.cmake:192 (include)

error: building pkgconf:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle pkgconf:x64-windows: 1.8 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+pkgconf
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[pkgconf]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by FrankXie05** [comment]
@stvsl Thanks for posting this issue, could you  please provide the error log? 
```
C:\vcpkg\buildtrees\pkgconf\cmake-get-vars-x64-windows-dbg-CMakeCache.txt.log
C:\vcpkg\buildtrees\pkgconf\cmake-get-vars-x64-windows-rel-CMakeCache.txt.log
C:\vcpkg\buildtrees\pkgconf\cmake-get-vars-x64-windows-dbg-CMakeConfigureLog.yaml.log
C:\vcpkg\buildtrees\pkgconf\cmake-get-vars-x64-windows-rel-CMakeConfigureLog.yaml.log
C:\vcpkg\buildtrees\pkgconf\cmake-get-vars-x64-windows-out.log
```
