### ISSUE TITLE
[libssh] Repository URL might be out of date

### ISSUE THREAD

**Issue by chuongvhn** [Microsoft/vcpkg#4077]
vcpkg tries to download package at this url but it is not available  

> The following packages will be built and installed:
    libssh[core]:x86-windows
Starting package 1/1: libssh:x86-windows
Building package libssh[core]:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/vcpkg/packages/libssh_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/vcpkg/buildtrees/libssh
-- CURRENT_PORT_DIR=C:/vcpkg/ports/libssh/.
-- Downloading https://red.libssh.org/attachments/download/218/libssh-0.7.5.tar.xz...
-- Downloading https://red.libssh.org/attachments/download/218/libssh-0.7.5.tar.xz... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:121 (message):
      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
Call Stack (most recent call first):
  ports/libssh/portfile.cmake:7 (vcpkg_download_distfile)
  scripts/ports.cmake:72 (include)
Error: Building package libssh:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libssh:x86-windows
  Vcpkg version: 0.0.105-2018-03-01-80e0648a401a438ed2f77beb17c901cfcb2bb7bc

**Comment by Voskrese** [comment]
`https://git.libssh.org/projects/libssh.git/`
https://git.libssh.org/projects/libssh.git/snapshot/libssh-0.7.5.tar.gz

upgrade

https://git.libssh.org/projects/libssh.git/snapshot/libssh-0.8.0.tar.gz

**Comment by chuongvhn** [comment]
>PS> git pull 
>PS> vcpkg update

Then the issue is solved
