### ISSUE TITLE
[shiftmedia-libgnutls] Build error on x64-windows

### ISSUE THREAD

**Issue by Harold-Glitch** [microsoft/vcpkg#40787]
Just enter on windows:

vcpkg install shiftmedia-libgnutls:x64-windows

... build faild

**Comment by sfhacker** [comment]
God save us all!

**Comment by jimwang118** [comment]
Please provide more error information, such as error log.

**Comment by dg0yt** [comment]
There might be an issue with more recent version of MSVC, as noted in other issues/PRs.

**Comment by dg0yt** [comment]
Note a fix was just added in #40739.

**Comment by Harold-Glitch** [comment]
bug fixed thank you !
