### ISSUE TITLE
Visual Studio cmake unable to find dependencies installed using vcpkg

### ISSUE THREAD

**Issue by gera710** [microsoft/vcpkg#4078]
I have a problem building my project using Visual Studio cmake after installing packages with vcpkg.

I've installed dependencies like this:
>set VCPKG_DEFAULT_TRIPLET=x64-windows

>vcpkg install cpprestsdk cpprestsdk --triplet x64-windows

>vcpkg install libmysql libmysql --triplet x64-windows

And the list of installed packages:

    vcpkg list
    boost-algorithm:x64-windows                        1.67.0           Boost algorithm module
    boost-any:x64-windows                              1.67.0           Boost any module
    boost-array:x64-windows                            1.67.0           Boost array module
    boost-asio:x64-windows                             1.67.0-1         Boost asio module
    boost-assert:x64-windows                           1.67.0           Boost assert module
    boost-atomic:x64-windows                           1.67.0           Boost atomic module
    boost-bimap:x64-windows                            1.67.0           Boost bimap module
    boost-bind:x64-windows                             1.67.0           Boost bind module
    boost-build:x64-windows                            1.67.0           Boost.Build
    boost-chrono:x64-windows                           1.67.0           Boost chrono module
    boost-compatibility:x64-windows                    1.67.0           Boost compatibility module
    boost-concept-check:x64-windows                    1.67.0           Boost concept_check module
    boost-config:x64-windows                           1.67.0           Boost config module
    boost-container-hash:x64-windows                   1.67.0           Boost container_hash module
    boost-container:x64-windows                        1.67.0           Boost container module
    boost-context:x64-windows                          1.67.0           Boost context module
    boost-conversion:x64-windows                       1.67.0           Boost conversion module
    boost-core:x64-windows                             1.67.0           Boost core module
    boost-coroutine:x64-windows                        1.67.0           Boost coroutine module
    boost-date-time:x64-windows                        1.67.0           Boost date_time module
    boost-detail:x64-windows                           1.67.0           Boost detail module
    boost-endian:x64-windows                           1.67.0           Boost endian module
    boost-exception:x64-windows                        1.67.0           Boost exception module
    boost-filesystem:x64-windows                       1.67.0           Boost filesystem module
    boost-foreach:x64-windows                          1.67.0           Boost foreach module
    boost-format:x64-windows                           1.67.0           Boost format module
    boost-function-types:x64-windows                   1.67.0           Boost function_types module
    boost-function:x64-windows                         1.67.0           Boost function module
    boost-functional:x64-windows                       1.67.0           Boost functional module
    boost-fusion:x64-windows                           1.67.0           Boost fusion module
    boost-geometry:x64-windows                         1.67.0           Boost geometry module
    boost-graph:x64-windows                            1.67.0           Boost graph module
    boost-integer:x64-windows                          1.67.0           Boost integer module
    boost-intrusive:x64-windows                        1.67.0           Boost intrusive module
    boost-io:x64-windows                               1.67.0           Boost io module
    boost-iostreams:x64-windows                        1.67.0-1         Boost iostreams module
    boost-iterator:x64-windows                         1.67.0           Boost iterator module
    boost-lambda:x64-windows                           1.67.0           Boost lambda module
    boost-lexical-cast:x64-windows                     1.67.0           Boost lexical_cast module
    boost-locale:x64-windows                           1.67.0           Boost locale module
    boost-math:x64-windows                             1.67.0           Boost math module
    boost-modular-build-helper:x64-windows             2018-05-14
    boost-move:x64-windows                             1.67.0           Boost move module
    boost-mpl:x64-windows                              1.67.0           Boost mpl module
    boost-multi-index:x64-windows                      1.67.0           Boost multi_index module
    boost-multiprecision:x64-windows                   1.67.0           Boost multiprecision module
    boost-numeric-conversion:x64-windows               1.67.0           Boost numeric_conversion module
    boost-optional:x64-windows                         1.67.0           Boost optional module
    boost-parameter:x64-windows                        1.67.0           Boost parameter module
    boost-phoenix:x64-windows                          1.67.0           Boost phoenix module
    boost-polygon:x64-windows                          1.67.0           Boost polygon module
    boost-pool:x64-windows                             1.67.0           Boost pool module
    boost-predef:x64-windows                           1.67.0           Boost predef module
    boost-preprocessor:x64-windows                     1.67.0           Boost preprocessor module
    boost-property-map:x64-windows                     1.67.0           Boost property_map module
    boost-property-tree:x64-windows                    1.67.0           Boost property_tree module
    boost-proto:x64-windows                            1.67.0           Boost proto module
    boost-qvm:x64-windows                              1.67.0           Boost qvm module
    boost-random:x64-windows                           1.67.0           Boost random module
    boost-range:x64-windows                            1.67.0           Boost range module
    boost-ratio:x64-windows                            1.67.0           Boost ratio module
    boost-rational:x64-windows                         1.67.0           Boost rational module
    boost-regex:x64-windows                            1.67.0           Boost regex module
    boost-serialization:x64-windows                    1.67.0           Boost serialization module
    boost-smart-ptr:x64-windows                        1.67.0           Boost smart_ptr module
    boost-spirit:x64-windows                           1.67.0           Boost spirit module
    boost-static-assert:x64-windows                    1.67.0           Boost static_assert module
    boost-system:x64-windows                           1.67.0           Boost system module
    boost-test:x64-windows                             1.67.0-2         Boost test module
    boost-thread:x64-windows                           1.67.0           Boost thread module
    boost-throw-exception:x64-windows                  1.67.0           Boost throw_exception module
    boost-timer:x64-windows                            1.67.0           Boost timer module
    boost-tokenizer:x64-windows                        1.67.0           Boost tokenizer module
    boost-tti:x64-windows                              1.67.0           Boost tti module
    boost-tuple:x64-windows                            1.67.0           Boost tuple module
    boost-type-index:x64-windows                       1.67.0           Boost type_index module
    boost-type-traits:x64-windows                      1.67.0           Boost type_traits module
    boost-typeof:x64-windows                           1.67.0           Boost typeof module
    boost-unordered:x64-windows                        1.67.0           Boost unordered module
    boost-utility:x64-windows                          1.67.0           Boost utility module
    boost-variant:x64-windows                          1.67.0           Boost variant module
    boost-vcpkg-helpers:x64-windows                    4                a set of vcpkg-internal scripts used to modulari...
    boost-winapi:x64-windows                           1.67.0           Boost winapi module
    boost-xpressive:x64-windows                        1.67.0           Boost xpressive module
    bzip2:x64-windows                                  1.0.6-2          High-quality data compressor.
    cpprestsdk:x64-windows                             2.10.3-1         C++11 JSON, REST, and OAuth library The C++ REST...
    icu:x64-windows                                    61.1-1           Mature and widely used Unicode and localization ...
    libevent:x64-windows                               2.1.8-3          An event notification library
    liblzma:x64-windows                                5.2.3-2          Compression library with an API similar to that ...
    libmysql:x64-windows                               8.0.4-2          A MySQL client library for C development.
    lz4:x64-windows                                    1.8.2            Lossless compression algorithm, providing compre...
    openssl-windows:x64-windows                        1.0.2o           OpenSSL is an open source project that provides ...
    openssl:x64-windows                                0                OpenSSL is an open source project that provides ...
    websocketpp:x64-windows                            0.7.0-1          Library that implements RFC6455 The WebSocket Pr...
    zlib:x64-windows                                   1.2.11-3         A compression library

But when I tried to cmake the project using Visual Studio 17 I receive errors like:

    CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.11/Modules/FindBoost.cmake:1903 (message):
      Unable to find the requested Boost libraries.
      Unable to find the Boost header files.  Please set BOOST_ROOT to the root
      directory containing Boost or BOOST_INCLUDEDIR to the directory containing
      Boost's headers.
    Call Stack (most recent call first):
    CMakeLists.txt:53 (find_package)
    CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
      Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
      system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
      OPENSSL_INCLUDE_DIR) (Required is at least version "1.0.0")

I've tried to add OPENSSL_ROOT_DIR environment variable but received the same issue with zlib:

    CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
      Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)

And for some builds I still receive error about OpenSSL...
CMakeLists.txt part:

    find_library(CPPREST_LIB NAMES cpprest_2_9d cpprest_2_9 cpprestd cpprest)
    find_package(Boost REQUIRED COMPONENTS random system filesystem regex locale)
    find_package(OpenSSL REQUIRED)
    find_package(ZLIB REQUIRED)

When tried to install openssl additionally I receive further output.

    >vcpkg install openssl
    The following packages are already installed:
        openssl[core]:x64-windows
    Starting package 1/1: openssl:x64-windows
    Package openssl:x64-windows is already installed
    Elapsed time for package openssl:x64-windows: 1.988 ms
    
    Total elapsed time: 2.98 ms
    
    The package openssl is compatible with built-in CMake targets:
    
        find_package(OpenSSL REQUIRED)
        target_link_libraries(main PRIVATE OpenSSL::SSL OpenSSL::Crypto)

The same with other packages. So it should work... 
I've removed the dependencies using 

    vcpkg remove cpprestsdk --recurse
and installed again - same thing.

I've done 

    vcpkg integrate install
And tried to add -DCMAKE_TOOLCHAIN_FILE=D:/repo/vcpkg/scripts/buildsystems/vcpkg.cmake running cmake command from cmd:

    "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\user\CMakeBuilds\6ec40ad3-aec5-e439-9463-46e3ff20b362\install\x64-Debug"  -DCMAKE_CXX_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/HostX64/x64/cl.exe"  -DCMAKE_C_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/HostX64/x64/cl.exe"  -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "D:\repo\project" -DCMAKE_TOOLCHAIN_FILE=D:/repo/vcpkg/scripts/buildsystems/vcpkg.cmake

And received an errors:

    -- VERSION: 2.0.0(1)
    -- The C compiler identification is unknown
    -- The CXX compiler identification is unknown
    -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/HostX64/x64/cl.exe
    -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/HostX64/x64/cl.exe -- broken
    CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.11/Modules/CMakeTestCCompiler.cmake:52 (message):
      The C compiler
    
        "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/HostX64/x64/cl.exe"
    
      is not able to compile a simple test program.
    
      It fails with the following output:
    
        Change Dir: C:/Windows/System32/CMakeFiles/CMakeTmp
    
        Run Build Command:"C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "cmTC_e1a7a"
        ninja: error: loading 'build.ninja': The system cannot find the path specified.

CMakeError.log:

    Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
    Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/HostX64/x64/cl.exe 
    Build flags: 
    Id flags: --c++ 
    
    The output was:
    2
    Microsoft (R) C/C++ Optimizing Compiler Version 19.14.26433 for x64
    Copyright (C) Microsoft Corporation.  All rights reserved.
    
    cl : Command line warning D9002 : ignoring unknown option '--c++'
    CMakeCXXCompilerId.cpp
    c1xx: fatal error C1083: Cannot open source file: 'CMakeCXXCompilerId.cpp': No such file or directory
    
    
    Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
    Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/HostX64/x64/cl.exe 
    Build flags: 
    Id flags: --ec++ 
    
    The output was:
    2
    Microsoft (R) C/C++ Optimizing Compiler Version 19.14.26433 for x64
    Copyright (C) Microsoft Corporation.  All rights reserved.
    
    cl : Command line warning D9002 : ignoring unknown option '--ec++'
    CMakeCXXCompilerId.cpp
    c1xx: fatal error C1083: Cannot open source file: 'CMakeCXXCompilerId.cpp': No such file or directory
    
    
    Checking whether the CXX compiler is IAR using "" did not match "IAR .+ Compiler":
    Microsoft (R) C/C++ Optimizing Compiler Version 19.14.26433 for x64
    Copyright (C) Microsoft Corporation.  All rights reserved.
    
    usage: cl [ option... ] filename... [ /link linkoption... ]
    Checking whether the CXX compiler is IAR using "" did not match "IAR .+ Compiler":
    Microsoft (R) C/C++ Optimizing Compiler Version 19.14.26433 for x64
    Copyright (C) Microsoft Corporation.  All rights reserved.
    
    usage: cl [ option... ] filename... [ /link linkoption... ]
    Determining if the C compiler works failed with the following output:
    Change Dir: C:/Windows/System32/CMakeFiles/CMakeTmp
    
    Run Build Command:"C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "cmTC_e1a7a"
    ninja: error: loading 'build.ninja': The system cannot find the path specified.

Documentation and promo video says it should work almost from the box.
https://docs.microsoft.com/en-us/cpp/vcpkg
https://www.youtube.com/watch?v=zo6nqFVBd5o

Please advise - I'm out of ideas.

Thanks in advance.

**Comment by PhoebeHui** [comment]
@gera710, does this still be a problem for you?

**Comment by PhoebeHui** [comment]
@gera710, boost has been upgrade to 1.76 in vcpkg, please try latest source and open a new issue if still be a problem for you.
