### ISSUE TITLE
Clipper2 update to 1.4.0

### ISSUE THREAD

**Issue by petamas** [microsoft/vcpkg#40806]
### Library name

Clipper2

### New version number

1.4.0

### Other information that may be useful (release notes, etc...)

It seems like Clipper2 started exposing a proper `Clipper2Config.cmake`, so `usage` can be changed to use `find_package(Clipper2)` from `pkg_check_modules(Clipper2)`: https://github.com/AngusJohnson/Clipper2/blob/Clipper2_1.4.0/CPP/CMakeLists.txt#L331

**Comment by FrankXie05** [comment]
This issue has been fixed by PR https://github.com/microsoft/vcpkg/pull/40736

**Comment by petamas** [comment]
@FrankXie05 ooops, apparently I only checked the latest vcpkg release, not `master`. Sorry for the unnecessary issue!
