### ISSUE TITLE
While install zeroc-ice-mumble:x64-windows ,got error

### ISSUE THREAD

**Issue by Sardonyxtechsupport** [microsoft/vcpkg#40814]
I have downloaded VCPKG for running mumble-voip application.
while running commands ,some of the packages were not downloading.

Command  : vcpkg install zeroc-ice-mumble:x64-windows
kindly refer below screenshots for vcpkg with Mumble , download and installation Error
![VCPKG-1](https://github.com/user-attachments/assets/aaffdf1e-ca87-4c29-abdf-b988cf5ae223)
![VCPKG-2](https://github.com/user-attachments/assets/c68e74f6-5346-44be-9969-4dfdfaffa0d0)

kindly check and update

**Comment by greenozon** [comment]
Not sure where did you get that port
In my case:
```
c:\Dev\vcpkg>vcpkg install zeroc-ice-mumble:x64-windows
Computing installation plan...
error: while looking for zeroc-ice-mumble:x64-windows:
C:\Dev\vcpkg\ports\zeroc-ice-mumble: error: zeroc-ice-mumble does not exist
```

**Comment by LilyWangLL** [comment]
![image](https://github.com/user-attachments/assets/7aef4cfc-7b0b-4f39-ae74-29758e888cac)
You need update the old hash in `portfile.cmake` of `zeroc-ice-mumble`.

**Comment by Sardonyxtechsupport** [comment]
How to update old hash ..kindly help me

**Comment by LilyWangLL** [comment]
The file path is _C:/Users/Administrator/vcpkg/ports/zeroc-ice-mumble/portfile.cmake_, you need update the `SHA512`.

**Comment by greenozon** [comment]
the official vcpkg repo have only the `zeroc-ice` lib
where does the `zeroc-ice-mumble` come from?
![image](https://github.com/user-attachments/assets/5611df55-767c-4056-b5ef-91dd36376102)

**Comment by LilyWangLL** [comment]
`zeroc-ice-mumble` is a new port that you created yourself and is not an existing port in vcpkg. You need to update the hash of this port in your local vcpkg. Please reopen this issue if this is still a problem for you.
