### ISSUE TITLE
[ffmpeg] vaapi support

### ISSUE THREAD

**Issue by Hlongyu** [microsoft/vcpkg#40820]
### Is your feature request related to a problem? Please describe.

I need use vaapi to decode video in linux with intel cpu.

### Proposed solution

add enable-vaapi in ffmpeg configure like cuda
```
if("nvcodec" IN_LIST FEATURES)
    #Note: the --enable-cuda option does not actually require the cuda sdk or toolset port dependency as ffmpeg uses runtime detection and dynamic loading
    set(OPTIONS "${OPTIONS} --enable-cuda --enable-nvenc --enable-nvdec --enable-cuvid --enable-ffnvcodec")
else()
    set(OPTIONS "${OPTIONS} --disable-cuda --disable-nvenc --disable-nvdec  --disable-cuvid --disable-ffnvcodec")
endif()
```

**Comment by FrankXie05** [comment]
@Hlongyu Sorry for the late reply, vcpkg does not support `vappi` at present. We need to wait for port `vappi` adding.

**Comment by teaalltr** [comment]
@FrankXie05 any news from this front? Is VAAPI going to be supported? Any ETA?

**Comment by FrankXie05** [comment]
@teaalltr Sorry, under our current policy, while users are more than welcome to add new ports, maintainers will no longer add new ports.

**Comment by paaspaas00** [comment]
@FrankXie05 does it need a port? From what I see it's just a command line flag addition. @Hlongyu please correct me if I'm wrong

**Comment by Hlongyu** [comment]
https://github.com/intel/libva  
may be need add a new port for it

**Comment by Hlongyu** [comment]
Can we use message to enable libva like this?
```
if(VCPKG_TARGET_IS_LINUX)
    message(
"GLFW3 currently requires the following libraries from the system package manager:
    xinerama
    xcursor
    xorg
    libglu1-mesa
    pkg-config

These can be installed on Ubuntu systems via sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config

Alternatively, when targeting the Wayland display server, use the packages listed in the GLFW documentation here:

https://www.glfw.org/docs/3.3/compile.html#compile_deps_wayland")
endif()
```

**Comment by Hlongyu** [comment]
https://github.com/microsoft/vcpkg/pull/46684

**Comment by paaspaas00** [comment]
@Hlongyu so last thing missing Is vcpkg vaapi support in ffmpeg right? Like a declaration in vcpkg package

**Comment by Hlongyu** [comment]
> [@Hlongyu](https://github.com/Hlongyu) so last thing missing Is vcpkg vaapi support in ffmpeg right? Like a declaration in vcpkg package

already support, you need add  vaapi in ffmpeg features.
