### ISSUE TITLE
c-aries  - fail - Building package c-ares[core]:x86-windows - 1_14_0-74d21949f7

### ISSUE THREAD

**Issue by SpencerBarrett** [Microsoft/vcpkg#4082]
Package: c-ares:x86-windows
  Vcpkg version: 0.0.113-nohash

-- Using source at C:/SW/vcpkg/buildtrees/c-ares/src/res-1_14_0-74d21949f7
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: C:/SW/vcpkg/downloads/tools/cmake-3.11.4-windows/cmake-3.1
nfig;Debug;--target;install;--;-v;-j1
    Working Directory: C:/SW/vcpkg/buildtrees/c-ares/x86-windows-dbg
    See logs for more information:
      C:\SW\vcpkg\buildtrees\c-ares\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/c-ares/portfile.cmake:31 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package c-ares:x86-windows failed with: BUILD_FAILED
[config-x86-windows-out.log](https://github.com/Microsoft/vcpkg/files/2285030/config-x86-windows-out.log)

**Comment by Voskrese** [comment]
;))

> See logs for more information:
> C:\SW\vcpkg\buildtrees\c-ares\install-x86-windows-dbg-out.log

install-x86-windows-dbg-out.log

**Comment by Voskrese** [comment]
you did not attach the file

**Comment by SpencerBarrett** [comment]
It works now.. I did a remove and install..

SPENCERBARRETT
SYSTEMS ENGINEER

SIGMADESIGN
4600 NW PACIFIC RIM BLVD
CAMAS WA 98607
C: 503.382.7117
P: 360.693.2600
F: 360.693.2581
sbarret@sigmadzn.com<mailto:sbarret@sigmadzn.com>

www.sigmadzn.com<http://www.sigmadzn.com/>  |  LinkedIn<https://www.linkedin.com/company/57014?trk=tyah&trkInfo=tarId%3A1422993589312%2Ctas%3Asigma%20design%2Cidx%3A2-1-4>
Careers<http://www.sigmadzn.com/about/careers/>  |  Newsletter Sign Up<http://visitor.r20.constantcontact.com/manage/optin?v=001YO7rQ8A-4TBQGDqRR4C_qO8BOzCCsqsKZpNTFoAur6DHtqbtiix_UV4VWyVGvb8RjTbljgmPZAward9z0UuPM7hqI9fv_O75rygX9OoEeu0%3D>

**Comment by PhoebeHui** [comment]
I can't repro this issue, It looks the issue solved, closed it, @SpencerBarrett, please reopen it if you think it's still be an issue.
