### ISSUE TITLE
[Libcrypt] update to 1.11.0

### ISSUE THREAD

**Issue by AndersBroman** [microsoft/vcpkg#40844]
### Library name

Libcrypt

### New version number

1.11.0

### Other information that may be useful (release notes, etc...)

Windows x64 and arm please.

**Comment by MonicaLiu0311** [comment]
There is currently no port named `libcrypt` in `vcpkg`([ports/libcrypt](https://github.com/microsoft/vcpkg/blob/master/ports/libcrypt)). Did you type it wrong?

**Comment by AndersBroman** [comment]
Hi,
Sorry should be a new port then:
https://github.com/caseyscarborough/libcrypt maybe the scripts here is of
help https://gitlab.com/wireshark/wireshark-vcpkg-scripts
Best regards
Anders

Den mån 9 sep. 2024 04:57MonicaLiu ***@***.***> skrev:
