### ISSUE TITLE
Ports that reference ftp.gnu.org should use ftpmirror.gnu.org instead.

### ISSUE THREAD

**Issue by john-terrell** [microsoft/vcpkg#4085]
I ran into this issue tonight.   The normal ftp.gnu.org site was down and I was unable to acquire several GNU libraries.   The mirror ftpmirror.gnu.org should be used instead as this will try to transfer from one of many local (to the client) mirrors.

Expected: Transferring GNU packages should work successfully if the main ftp.gnu.org site is offline.
Actual: Transferring GNU packages times-out when the normal ftp.gnu.org site is offline.

The fix is to simply perform a global search-replace of ftp.gnu.org to ftpmirror.gnu.org (there aren't many locations this must be done).

**Comment by john-terrell** [comment]
See here:  https://www.gnu.org/prep/ftp.en.html

**Comment by Voskrese** [comment]
I agree, you need to add mirrors, a few, I look often users have problems with this

two or three sources, if any

offer, because the program in the source code, everyone can make their own work

**Comment by bahaki386** [comment]
I couldn't install gettext:x64-windows due to this issue.

**Comment by NancyLi1013** [comment]
Hi @john-terrell thanks for posting this issue.
This issue has been fixed now. Please try to update vcpkg and use them.
