### ISSUE TITLE
Building package cpprestsdk:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by sohel364** [Microsoft/vcpkg#4089]
Error: Building package cpprestsdk:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cpprestsdk:x86-windows
  Vcpkg version: 0.0.113-nohash

**Comment by PhoebeHui** [comment]
Hi sohel364，

I can't repro this issue, could you open a new issue if the problem persists.

PS F:\vcpkg\src> ./vcpkg version
Vcpkg package management program version 2018.11.23-nohash

PS F:\vcpkg\src> ./vcpkg install cpprestsdk:x86-windows
...
Starting package 6/6: cpprestsdk:x86-windows
Building package cpprestsdk[brotli,core,default-features,websockets]:x86-windows...
-- Downloading https://github.com/Microsoft/cpprestsdk/archive/v2.10.9.tar.gz...
-- Extracting source F:/VCPKG/src/downloads/Microsoft-cpprestsdk-v2.10.9.tar.gz
-- Using source at F:/VCPKG/src/buildtrees/cpprestsdk/src/v2.10.9-0417f85bbf
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: F:/VCPKG/src/packages/cpprestsdk_x86-windows/share/cpprestsdk/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package cpprestsdk[brotli,core,default-features,websockets]:x86-windows... done
Installing package cpprestsdk[brotli,core,default-features,websockets]:x86-windows...
Installing package cpprestsdk[brotli,core,default-features,websockets]:x86-windows... done
Elapsed time for package cpprestsdk:x86-windows: 1.456 min

Total elapsed time: 2.998 min

The package cpprestsdk:x86-windows provides CMake targets:

    find_package(cpprestsdk CONFIG REQUIRED)
    # Note: 1 target(s) were omitted.
    target_link_libraries(main PRIVATE cpprestsdk::cpprest cpprestsdk::cpprestsdk_zlib_internal cpprestsdk::cpprestsdk_boost_internal cpprestsdk::cpprestsdk_op
enssl_internal)

Thanks,
Phoebe
