### ISSUE TITLE
[poco] Build error vcpkg --triplet x64-windows install poco[netssl] fails

### ISSUE THREAD

**Issue by LidiaMirkin** [microsoft/vcpkg#40902]
error: building poco:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+poco
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[poco]+Build+error
Include '[poco] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e
    vcpkg-scripts version: 5dd5017f1 2022-07-05 (2 years, 2 months ago)

**Comment by sfhacker** [comment]
God save us all!

**Comment by Cheney-W** [comment]
Please see [#30604](https://github.com/microsoft/vcpkg/issues/30604) for how to report an issue.

**Comment by dg0yt** [comment]
> vcpkg-tool version: 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e
> vcpkg-scripts version: [5dd5017](https://github.com/microsoft/vcpkg/commit/5dd5017f144d4412ac42c5506a31006b6ac16600) 2022-07-05 (2 years, 2 months ago)

Please update first.

**Comment by LidiaMirkin** [comment]
After vcpkg upgrade, it fails on openssl build - full output is attached .

[vcpkg_output.txt](https://github.com/user-attachments/files/16968863/vcpkg_output.txt)


OS: Windows 11 Pro Build: 22631.4037
vcpkg package management program version 2024-08-01-fd884a0d390d12783076341bd43d77c3a6a15658


Thanks !

**Comment by dg0yt** [comment]
Did you even read the log?
Try some cleanup.
~~~
-- Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip;https://gstreamer.freedesktop.org/src/mirror/nasm-2.16.01-win64.zip;https://vcpkg.github.io/assets/nasm/nasm-2.16.01-win64.zip -> nasm-2.16.01-win64.zip...
CMake Error at scripts/cmake/vcpkg_extract_archive.cmake:19 (message):
  C:/aWork/PictimeClientNG/vcpkg/downloads/tools/nasm was an extraction
  target, but it already exists.
~~~

**Comment by LidiaMirkin** [comment]
No, i did not read the log, sorry.

1. i am not sure i understand what you mean by "some cleanup". Could you please  clarify, so i could make it next time  ?
2. Nevertheless, i installed vcpkg from scratch to the another location and then it looks like working.

thank you to all for the valuable input !
Lidia.

**Comment by dg0yt** [comment]
vcpkg complained that a directory or file already existed. You could check and probably remove that filepath.
(ATM it is unclear if vcpkg should do that for you. I submitted #40916.)
