### ISSUE TITLE
vcpkg does not have any logs for the installed port

### ISSUE THREAD

**Issue by sdajklfw389** [microsoft/vcpkg#40907]
**Describe the bug**
I have a private project A, which consumes a private project B(port B). B has a vcpkg feature, which is enabled in vcpkg.json in A.

When the feature is enabled, the port B will install more header files into A. But it didn't.

So i would like to see the logs in the stage of vcpkg install. I came accross this post:

https://github.com/microsoft/vcpkg/issues/11185

but this only works if the package is failed by vcpkg install.

In my case, the install is "successful" only it did not install the headers brought by the feature B.

**Environment**
- OS: [Windows 10]
- cmake version 3.29.5-msvc4

**To Reproduce**
1. make two projects and two vcpkg ports.
2. try to consume one from the other. if the vcpkg install is sucessful, then there will be no logs under the vcpkg/buildtrees.

**Expected behavior**
I want to see logs under vcpkg-root/builtrees wether the vcpkg install scucceeds or not.

**Failure logs**
but instead, i only see one file: windows-x64-static.vcpkg_abi_info.txt

**Additional context**

**Comment by jimwang118** [comment]
The A and B you call are private projects, and no vcpkg installation log will be generated. Only the corresponding port log will be generated during the port installation process in vcpkg.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
