### ISSUE TITLE
`vcpkg install pcl:x64-windows-static` creates extremely large files

### ISSUE THREAD

**Issue by paulhoux** [microsoft/vcpkg#4090]
Hi,

I'm trying to build PCL as a static library for 64-bit windows. I ran the command `./vcpkg install pcl:x64-windows-static`. Building the library took an extremely long time, around 4 hours in total. It FAILED on StrawberryPerl, which could not download from its website, but I managed to obtain a ZIP-file from somewhere else and copied that to vcpkg's `downloads` folder. Then the build succeeded.

However, compared to the dynamically linked version, the `.lib` files are extremely large, rendering them useless. I'll attach a screenshot, comparing the static build with the prebuilt dynamic PCL files:
![2018-08-14_214341](https://user-images.githubusercontent.com/304908/44147018-7c9620c8-a092-11e8-830a-11e7e690a6bf.png)

What could be the cause of this? And is there a way to reduce the file size of the libraries?

-Paul

**Comment by degski** [comment]
The ones on the left are link libraries, the ones on the right are static libraries. The latter contain all the code, the ones on the right are stubs to link (at run-time) into the corresponding dll. Somewhere on you're computer there are some .dll's that have a comparable size to the static libraries. 

No, it's not possible to reduce them (you could strip symbols, for the release ones, for debug, doing that would render them useless).

The good news in all of that is that if you would like to distribute things, even if and when you only use one function in the dll version, you'd have to distribute your .exe and the whole dll. In case of the static linking there is no need to distribute anything, other than your .exe.

**Comment by Voskrese** [comment]
x64-windows-static = static
x64-windows = dynamic

in static all DEPENDENCE is collected in ONE file
in the dynamic library only own code

**Comment by Cheney-W** [comment]
Close this issue because Voskrese has answered it.
