### ISSUE TITLE
[libressl] port bug: find_package(openssl) is detect openssl libs outside vcpkg, in github ci action, instead libressl port

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#40915]
### Operating system

windows latest github ci

### Compiler

msvc

### Steps to reproduce the behavior

On github action ci with windows latest runner. run this command:
```
  vcpkg install vcpkg-ci-libressl '--triplet=x64-windows' --overlay-ports=$VCPKG_INSTALLATION_ROOT\\scripts\\test_ports
```

### Failure logs
https://github.com/talregev/curl/actions/runs/10859242578/job/30138314640?pr=22

### Additional context

I run libressl test port on github action windows ci.
https://github.com/talregev/curl/actions/runs/10859242578/job/30138314640?pr=22
and I download the logs.

[windows_logs_7696dc6fb70eff5b0a5079d78b9818f4dc486861.zip](https://github.com/user-attachments/files/17000835/windows_logs_7696dc6fb70eff5b0a5079d78b9818f4dc486861.zip)

I reproduce the problem: 
[config-x64-windows-out.log](https://github.com/user-attachments/files/17000833/config-x64-windows-out.log)

```
-- Found OpenSSL: optimized;C:/vcpkg/installed/x64-windows/lib/crypto.lib;debug;C:/Program Files/OpenSSL/lib/VC/libcrypto64MDd.lib (found version "2.0.0")
-- OpenSSL::SSL IMPORTED_LOCATION_DEBUG: C:/Program Files/OpenSSL/lib/VC/libssl64MDd.lib
CMake Error at CMakeLists.txt:19 (message):
  OpenSSL::SSL IMPORTED_LOCATION_DEBUG is not from vcpkg.
```

find_package(openssl) is detect openssl libs outside vcpkg, in github ci action.

As discuss here, is a libressl port bug.
https://github.com/microsoft/vcpkg/pull/40922#issuecomment-2362310018

> suggests a bug in the LibreSSL port and should not be worked around in every downstream port that wants to consume LibreSSL in this way.

**Comment by talregev** [comment]
Maybe it detected the openssl on the ci instead the libressl?

**Comment by dg0yt** [comment]
Maybe related to #40924: If openssl is present, libressl is built *and cached* as an empty package.

**Comment by talregev** [comment]
No it not. it building.

**Comment by dg0yt** [comment]
Well, both linked CI runs do install a cached artifact for libressl instead of building from source, so they are potential victims:
#40924 fixes that this artifact might be empty if it was created with openssl present.

And at this point, the CI runs installed vcpkg tree will have neiter openssl binaries (not requested) nor libressl binaries (empty artifact). This would well explain why `FindOpenSSL.cmake` picks "outside openssl".

**Comment by dg0yt** [comment]
(Hint: Try to run your CI with cache cleaned or disabled.)

**Comment by talregev** [comment]
> (Hint: Try to run your CI with cache cleaned or disabled.)

I already did many tests to understand what happened including cleaning the cache.
This is not the reason. It building the libressl correctly.
The problem was that find_package(openssl) detected openssl outside the vcpkg.

I already fix and tested the fix in the linked PR connected to this issue.

**Comment by dg0yt** [comment]
> The problem was that find_package(openssl) detected openssl outside the vcpkg.

Then the libressl port has a bug. Which is easily possible.

(It is only two weeks that [we were wondering](https://github.com/microsoft/vcpkg/pull/40654) why ngtcp2 got a libressl feature and dependency while calling `find_package(OpenSSL)`.)

**Comment by talregev** [comment]
> > The problem was that find_package(openssl) detected openssl outside the vcpkg.
> 
> Then the libressl port has a bug. Which is easily possible.
> 
> (It is only two weeks that [we were wondering](https://github.com/microsoft/vcpkg/pull/40654) why ngtcp2 got a libressl feature and dependency while calling `find_package(OpenSSL)`.)

The vcpkg libressl port don't have a bug. In ngtcp2, the detect of libressl is not use correctly. You should find_package(LibreSSL config) and not find_package(OpenSSL) as it say in the port.

**Comment by dg0yt** [comment]
> The vcpkg libressl port don't have a bug. 

Confirmed.


> In ngtcp2, the detect of libressl is not use correctly. You should find_package(LibreSSL config) and not find_package(OpenSSL) as it say in the port.

Well, `find_package(OpenSSL)` provides the libressl binaries from vcpkg when they are present. Verified with
https://github.com/microsoft/vcpkg/pull/40924/commits/5ca5a30b149bb2552ace82bf32bfc978350e4db4.

Port libressl doesn't provide the openssl wrapper, so it fails to provide transitive usage requirements (x64-linux: crypto and rt, according to pc files.)

**Comment by talregev** [comment]
@dg0yt I update the bug.
I hope you can help me solve it.
Thank you.
