### ISSUE TITLE
Graphite2 doesn't build under x64

### ISSUE THREAD

**Issue by crlf0710** [Microsoft/vcpkg#4091]

**Comment by crlf0710** [comment]
The machine setup: "I'm using Windows 10 Anniversary Update. My machine is using the zh-CN locale. I'm using VS 2017. I have successfully built several packages with `vcpkg` without problems.

The steps to reproduce: "I run 'vcpkg install graphite2:x64-windows'"
The outcome you expected: "I expected to see 'graphite2' successfully built and installed"
The actual outcome: "There're build errors".

Actually reading the code i've found that the json only support 32bit integer output. But the code is actually trying to output `size_t`, so the code can't build under 64bit compiler.

I'm made a few changes to the code locally to make the build succeed. Not sure if the fix is appropriate.
[various_fixes.zip](https://github.com/Microsoft/vcpkg/files/2293171/various_fixes.zip)

**Comment by ras0219-msft** [comment]
@crlf0710 Could you open those fixes as a PR? That makes it a lot easier for everyone to review and accept them if they're perfect :)
