### ISSUE TITLE
[bext-mp] build failure

### ISSUE THREAD

**Issue by jiayuehua** [microsoft/vcpkg#40925]
### Operating system

windows/linux

### Compiler

gcc

### Steps to reproduce the behavior

```Shell
./vcpkg install bext-mp
```

### Failure logs

[DEBUG] 1000: cmd_execute_and_stream_data() returned 6 after 10017396 us
error: Failed to download from mirror set
error: https://github.com/boost-ext/mp/archive/d2dbdf89e543624be8351fd52308a9cf73374dbc.tar.gz: curl failed to download with exit code 6
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0curl: (6) Could not resolve host: github.com

[DEBUG] /mnt/vss/_work/1/s/src/vcpkg/base/downloads.cpp(1051):
[DEBUG] Time in subprocesses: 10017396us
[DEBUG] Time in parsing JSON: 5us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 519us

### Additional context

the upstream repo have moved to https://github.com/qlibs/mp, also if can, update to latest release version.

**Comment by sfhacker** [comment]
Something happened here!
