### ISSUE TITLE
Using vcpkg export nuget on OSX/Linux

### ISSUE THREAD

**Issue by thomas-t1** [microsoft/vcpkg#4093]
I am trying to use the VSTS packages feed service (Nuget) to host vcpkg package sets in VSTS to enable use on e.g. hosted build servers.
In order to do this for Windows, Linux and OSX in the same way, I would like to export to nuget also for Linux and OSX targets.

However the export to nuget feature does not work properly on OSX and Linux, even if the tools is added to Linux and OSX in the tool xml file. The error is listed below, I assume the issue is related to the mono requirement, i.e. that nuget must be launched with 'mono nuget'

Any hints to how this can be implemented in the current tool xml file? Any hints on how to implement this is the code?  

The error produced when running the below command on WSL Ubuntu 18.04;

 ./vcpkg export boost-system --nuget --debug 

[DEBUG] popen("/home/thomas/vcpkg/downloads/tools/nuget-4.6.2-linux/nuget" 2>&1)
[DEBUG] _pclose() returned 32256 after     7349 us
Value was null
[DEBUG] ../src/vcpkg/tools.cpp(229)

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen this issue.
