### ISSUE TITLE
 [SDL2] Build error  with mingw

### ISSUE THREAD

**Issue by liubailin2017** [microsoft/vcpkg#40957]
**Describe the bug**

**Environment**
- OS:  Windows
- Compiler: revision

**To Reproduce**
1.  vcpkg install sdl2
2.  vcpkg install sdl2-image

The part of the  CmakeLists.txt：
find_package(SDL2 CONFIG REQUIRED)
find_package(SDL2_image CONFIG REQUIRED)
  
add_executable(${PROJECT_NAME}demo  testsdl2.cpp)

target_link_libraries(${PROJECT_NAME}demo
    PRIVATE ${PROJECT_NAME}
    PRIVATE
        $<TARGET_NAME_IF_EXISTS:SDL2::SDL2main>
        $<IF:$<TARGET_EXISTS:SDL2::SDL2>,SDL2::SDL2,SDL2::SDL2-static>
    PRIVATE $<IF:$<TARGET_EXISTS:SDL2_image::SDL2_image>,SDL2_image::SDL2_image,SDL2_image::SDL2_image-static>
    PRIVATE ${sdl2image_LIBRARIES} 
) 
 testsdl2.cpp：
 
#include <SDL2/SDL.h>

int main(int argc, char *argv[]) {
    return 0;
}

build:

cmake  -DCMAKE_C_COMPILER:FILEPATH=c:\Qt6\Tools\mingw1120_64\bin\gcc.exe -DCMAKE_CXX_COMPILER:FILEPATH=c:\Qt6\Tools\mingw1120_64\bin\g++.exe -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake  -SC:/Users/liuba/Desktop/RES-cl/src/movit -Bc:/Users/liuba/Desktop/RES-cl/src/movit/build -G "Ninja Multi-Config"

It worked fine when I used release：
cmake.exe --build c:/Users/liuba/Desktop/RES-cl/src/movit/build --config Release --target all --
But switching to debug won't work：
cmake.exe --build  c:/Users/liuba/Desktop/RES-cl/src/movit/build --config Debug --target all -- 

**Expected behavior**
 

**Failure logs**
[build] C:\windows\system32\cmd.exe /C "cd . && c:\Qt6\Tools\mingw1120_64\bin\g++.exe -g  CMakeFiles/movitdemo.dir/Debug/testsdl2.cpp.obj -o Debug\movitdemo.exe -Wl,--out-implib,Debug\libmovitdemo.dll.a -Wl,--major-image-version,0,--minor-image-version,0 -LC:/vcpkg/installed/x64-windows/debug/lib   -LC:/Users/liuba/Desktop/RES-cl/lib Debug/libmovit.a  C:/vcpkg/installed/x64-windows/debug/lib/manual-link/SDL2maind.lib  C:/vcpkg/installed/x64-windows/debug/lib/SDL2_imaged.lib  -lSDL2_image  -lmingw32  -lSDL2main  -lSDL2  -lepoxy  -lshell32  C:/vcpkg/installed/x64-windows/debug/lib/SDL2d.lib  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && C:\windows\system32\cmd.exe /C "cd /D C:\Users\liuba\Desktop\RES-cl\src\movit\build && C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noprofile -executionpolicy Bypass -file C:/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/Users/liuba/Desktop/RES-cl/src/movit/build/Debug/movitdemo.exe -installedDir C:/vcpkg/installed/x64-windows/debug/bin -OutVariable out""
[build] Warning: corrupt .drectve at end of def file
[build] c:/Qt6/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/vcpkg/installed/x64-windows/debug/lib/manual-link/SDL2maind.lib(CMakeFiles/SDL2main.dir/src/main/windows/SDL_windows_main.c.obj):(.text$mn+0x290): undefined reference to `_RTC_CheckStackVars'
[build] c:/Qt6/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/vcpkg/installed/x64-windows/debug/lib/manual-link/SDL2maind.lib(CMakeFiles/SDL2main.dir/src/main/windows/SDL_windows_main.c.obj):(.rtc$IMZ+0x0): undefined reference to `_RTC_InitBase'
[build] c:/Qt6/Tools/mingw1120_64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/vcpkg/installed/x64-windows/debug/lib/manual-link/SDL2maind.lib(CMakeFiles/SDL2main.dir/src/main/windows/SDL_windows_main.c.obj):(.rtc$TMZ+0x0): undefined reference to `_RTC_Shutdown'
[build] collect2.exe: error: ld returned 1 exit status

**Additional context**
mingw64

**Comment by dg0yt** [comment]
> * vcpkg install sdl2
> 
> * vcpkg install sdl2-image

Was this using mingw? The default triplet uses MSVC.

**Comment by dg0yt** [comment]
> > * vcpkg install sdl2
> > * vcpkg install sdl2-image
> 
> Was this using mingw? The default triplet uses MSVC.

Why do I ask. `-LC:/vcpkg/installed/x64-windows/debug/lib` is x64-windows is MSVC. Don't mix it unless you know what you are doing.

You must control the triplets when you want to use mingw.

**Comment by liubailin2017** [comment]
I tried using 
vcpkg install sdl2:x64-mingw-dynamic 
vcpkg install sdl2-image:x64-mingw-dynamic
But it's the same error.

-Sorry for my poor English
