### ISSUE TITLE
[<port name>] build failure

### ISSUE THREAD

**Issue by dparkmit24** [microsoft/vcpkg#40968]
### Operating system

Windows

### Compiler

Cmake and Visual Studio 2022 

### Steps to reproduce the behavior

```Shell
.\vcpkg.exe install aws-sdk-cpp[sqs]:x86-windows
```

### Failure logs

[DEBUG] 1008: cmd_execute_and_stream_data() returned 1 after  1000999 us
error: building aws-c-common:x86-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle aws-c-common:x86-windows: 1 s
[DEBUG] Detecting host with IsWow64Process2
[DEBUG] 1009: CreateProcessW("C:\Program Files\Git\cmd\git.exe" "--git-dir=C:\Users\davidpark\Documents\vcpkg\.git" "--work-tree=C:\Users\davidpark\Documents\vcpkg\.git" -c core.autocrlf=false show "--pretty=format:%h %cd (%cr)" -s --date=short HEAD)
[DEBUG] 1009: cmd_execute_and_stream_data() returned 0 after    43036 us
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+aws-c-common
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[aws-c-common]+Build+error+on+x86-windows&body=Copy+issue+body+from+C%3A%2FUsers%2Fdavidpark%2FDocuments%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

I'm trying to get 32-bit dlls for sqs. how can i get them?

**Comment by jimwang118** [comment]
You can get this dynamic library in the `F:\vcpkg\packages\aws-sdk-cpp_x86-windows\bin` path.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.

**Comment by dparkmit24** [comment]
Thanks!
