### ISSUE TITLE
[vcpkg]Ignore unmatched environment values

### ISSUE THREAD

**Issue by John-zhan** [microsoft/vcpkg#40966]
**Describe the bug**

**Environment**
- OS: [e.g. Windows 11 etc...]
- Compiler: 

**To Reproduce**
1. ./vcpkg install xxxx
2. See error
Repro code when

**Expected behavior**
when install don't prompt this warnning

**Failure logs**
-(please attached failure logs)

**Additional context**

**Comment by FrankXie05** [comment]
@John-zhan Please add your questions and error logs to the comment. :)
