### ISSUE TITLE
[openblas] Build error on x64-windows

### ISSUE THREAD

**Issue by ChrisNabold** [microsoft/vcpkg#40978]
Copy issue body from C:/vcpkg/installed/vcpkg/issue_body.md
I tried to install openblas and GSL from vcpkg on windows 11
But it can not be installed.
error:
error: building openblas:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle openblas:x64-windows: 3.9 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openblas
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[openblas]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

[C:\vcpkg]git pull
Already up to date.

[C:\vcpkg]vcpkg update
Using local port versions. To update the local ports, use `git pull`.
No packages need updating.

[C:\vcpkg]

**Comment by LilyWangLL** [comment]
Please see #30604 for how to report an issue, please provide the error log.

**Comment by ChrisNabold** [comment]
Dear Lilly,

 

I enclose three files – which should help you to localize the eror.

If you should need more info please let me know what you need.

The error should be easy to reproduce

Thank you

Chris Nabold

**Comment by LilyWangLL** [comment]
Please provide the error log file C:\vcpkg\buildtrees\openblas\install-x64-windows-dbg-out.log.

**Comment by ChrisNabold** [comment]
Here is the requested file again 

Regards

Chris Nabold

**Comment by LilyWangLL** [comment]
Sorry, I didn't see any log file in your comment.

**Comment by LilyWangLL** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
