### ISSUE TITLE
[draco] build failure

### ISSUE THREAD

**Issue by zzy257248** [microsoft/vcpkg#40979]
### Operating system

Windows

### Compiler

MSVC 19.38.33133.0

### Steps to reproduce the behavior

```Shell
.\vcpkg install omplapp
```

### Failure logs

```
-- Using cached google-draco-1.5.7.tar.gz.
-- Cleaning sources at D:/Code/C++/vcpkg-master/buildtrees/draco/src/1.5.7-c71437a6c1.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Code/C++/vcpkg-master/downloads/google-draco-1.5.7.tar.gz
-- Applying patch fix-compile-error-uwp.patch
-- Applying patch fix-uwperror.patch
-- Applying patch fix-pkgconfig.patch
-- Applying patch disable-symlinks.patch
-- Applying patch install-linkage.diff
-- Using source at D:/Code/C++/vcpkg-master/buildtrees/draco/src/1.5.7-c71437a6c1.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: "D:/Microsoft Visual Studio/2022/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: D:/Code/C++/vcpkg-master/buildtrees/draco/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\Code\C++\vcpkg-master\buildtrees\draco\config-x64-windows-dbg-CMakeCache.txt.log
      D:\Code\C++\vcpkg-master\buildtrees\draco\config-x64-windows-rel-CMakeCache.txt.log
      D:\Code\C++\vcpkg-master\buildtrees\draco\config-x64-windows-dbg-CMakeConfigureLog.yaml.log
      D:\Code\C++\vcpkg-master\buildtrees\draco\config-x64-windows-rel-CMakeConfigureLog.yaml.log
      D:\Code\C++\vcpkg-master\buildtrees\draco\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:269 (vcpkg_execute_required_process)
  ports/draco/portfile.cmake:19 (vcpkg_cmake_configure)
  scripts/ports.cmake:192 (include)



```

### Additional context

error: building draco:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle draco:x64-windows: 7.2 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+draco
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[draco]+Build+error+on+x64-windows&body=Copy+issue+body+from+D%3A%2FCode%2FC%2B%2B%2Fvcpkg-master%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by zzy257248** [comment]
Package: draco:x64-windows@1.5.7

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.38.33133.0
-    vcpkg-tool version: 2024-08-01-fd884a0d390d12783076341bd43d77c3a6a15658
    vcpkg-scripts version: unknown

**Comment by greenozon** [comment]
Your path has the '+'  symbol
please try to use another one not having spaces or pluses in it

**Comment by zzy257248** [comment]
> Your path has the '+' symbol please try to use another one not having spaces or pluses in it

Thanks very much! Your suggestion has been really helpful!
