### ISSUE TITLE
[igraph] remove dependency on libglfortran.so.5 on Linux

### ISSUE THREAD

**Issue by urisimchoni** [microsoft/vcpkg#40988]
### Is your feature request related to a problem? Please describe.

I have an application which uses igraph, and I integrate igraph using vcpkg and cmake. Vcpkg's general tendency towards static builds is appealing to me, as I wish to distribute binaries with as little dependencies as possible (preferably only glibc).

The vcpkg port of igraph creates a dependency on `/usr/lib64/libgfortran.so.5` - it appears like the generated .cmake file that my project finds for igraph has this lib as one of the libraries to link to. This makes the binary not-run on systems which don't have libgfortran.so installed (or have it installed at a different path such as debian-derivatives). This happens even if I have libgfortran.a available.

### Proposed solution

I would like to fix "the build system" (either igraph or the way vcpkg configures it) so that static builds use libgfortran.a.

I'd be happy to dig into this myself, but it seems like libgfortran is not a direct dependency of igraph, and I could use some pointers on how to figure out where this dependency is coming from. So far I poked around in the build files and was unable to figure this out.

### Describe alternatives you've considered

When working without vcpkg, the default igraph build uses a vendored version of its fortran-related dependencies (lapack and blas), which seems not to have this issue. Vcpkg however uses the vcpkg-driven non-vendored version.

**Comment by szhorvat** [comment]
Can you be more specific about why you think such a dependency is created?

igraph's own build system does not do this, although it might link to libraries (specifically ARPACK, LAPACK, BLAS) which may (transitively) require gfortran.

The same goes for the portfile: there is nothing that explicitly pulls in gfortran. In fact, it does not use an external ARPACK. If gfortran does get pulled in, it must be through the BLAS/LAPACK dependency, meaning that this is out of the control of the igraph port.

But again: can you be specific about why you think this is the case? I cannot test on Linux at this moment. I see no such dependency on macOS.

**Comment by szhorvat** [comment]
Another comment is that using external BLAS/LAPACK is highly recommended. It will give you significantly more performance. I would not support 

If you are on Linux, building igraph _without_ vcpkg is quite easy, and you'll get complete control over the options, including the option to use the vendored BLAS/LAPACK.  If you are aiming to create a binary that is as platform-independent as possible, this is the best option. More info: https://igraph.org/c/html/latest/igraph-Installation.html

**Comment by urisimchoni** [comment]
I'll take it up with lapack/lapack-reference packages of vcpkg. I think it's clearer to me where to look.
Thanks!
