### ISSUE TITLE
[icu] build failure

### ISSUE THREAD

**Issue by RainbowTaro2022** [microsoft/vcpkg#40981]
### Operating system

windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
.\vcpkg install icu --triplet x64-windows
Computing installation plan...
The following packages will be built and installed:
    icu[core,tools]:x64-windows@74.2#3
Detecting compiler hash for triplet x64-windows...
error: while detecting compiler information:
The log file content at "F:\Cone\vcpkg\buildtrees\detect_compiler\stdout-x64-windows.log" is:
-- Found external ninja('1.11.0').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "F:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: F:/Cone/vcpkg/buildtrees/detect_compiler/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      F:\Cone\vcpkg\buildtrees\detect_compiler\config-x64-windows-rel-CMakeCache.txt.log
      F:\Cone\vcpkg\buildtrees\detect_compiler\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:314 (vcpkg_execute_required_process)
  scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:191 (include)
```

### Failure logs

[config-x64-windows-rel-CMakeCache.txt.log](https://github.com/user-attachments/files/17002086/config-x64-windows-rel-CMakeCache.txt.log)
[config-x64-windows-out.log](https://github.com/user-attachments/files/17002088/config-x64-windows-out.log)

**Comment by RainbowTaro2022** [comment]
I am using the latest version of MSVC

**Comment by greenozon** [comment]
From your logs it is visible that you are using external cmake
`F:/python311/Lib/site-packages/cmake/data/bin/cmake.exe`
from my experience, this is error prone way, 
I suggest you remove it from the PATH and then vcpkg  will use it's "beloved" internal cmake

pls give it a try

**Comment by RainbowTaro2022** [comment]
i know it

**Comment by greenozon** [comment]
so you succeed?

**Comment by RainbowTaro2022** [comment]
[config-x64-windows-rel-CMakeCache.txt.log](https://github.com/user-attachments/files/17002795/config-x64-windows-rel-CMakeCache.txt.log)
[config-x64-windows-out.log](https://github.com/user-attachments/files/17002797/config-x64-windows-out.log)

**Comment by greenozon** [comment]
thanks,
the issue is still the same one, sorry

**Comment by greenozon** [comment]
@RainbowTaro2022  could you please run the command in debug mode?
eg:

```
vcpkg install icu --triplet x64-windows --debug
```

and attach your logs

thanks!

**Comment by jimwang118** [comment]
Sorry, i cannot reproduce this issue locally.
![image](https://github.com/user-attachments/assets/78ff48c3-a892-471f-a656-a40a1e233564)

**Comment by Poldraunic** [comment]
It seems CMake is unable to find compiler. Can you running it in a VS Deleveloper Prompt?

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
