### ISSUE TITLE
.bat failed to execute

### ISSUE THREAD

**Issue by stayfoolish7** [Microsoft/vcpkg#4099]
Program 'bootstrap-vcpkg.bat' failed to execute: Access is denied
At line:1 char:22
+ .\bootstrap-vcpkg.bat <<<< .
At line:1 char:1
+  <<<< .\bootstrap-vcpkg.bat
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

I cannot seem to run the .bat file on powershell and keep getting this error. My settings: Windows 7 and Visual Studio 2017. I have no idea what is causing this issue. Thanks for your help.

**Comment by Voskrese** [comment]
powershell version?

**Comment by stayfoolish7** [comment]
Yes

**Comment by drescherjm** [comment]
That was not a yes / no question.

**Comment by Voskrese** [comment]
@stayfoolish7 ?
`powershell get-host`

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
