### ISSUE TITLE
[fakeit] Missing *.cmake files on Linux installation

### ISSUE THREAD

**Issue by Poldraunic** [microsoft/vcpkg#41004]
**Describe the bug**
Installation of FakeIt library in manifest mode doesn't produce *.cmake files required for find_package invocation. 

**Environment**
- OS: Linux
- Compiler: GCC 13.2.0

**To Reproduce**
1. Add "FakeIt" to the manifest file.
2. Run CMake.

**Expected behavior**
Installed library provides required cmake files for it to work.

**Failure logs**
No abnormal output in the console.

**Additional context**
This was previously reported in #36180. In the merge request for this issue, there is a comment (https://github.com/microsoft/vcpkg/pull/36195#issuecomment-1989477692) from March saying it is broken since February release.

This works fine on Windows and MacOS.

**Comment by dg0yt** [comment]
There is no difference between manifest mode and classic mode installs for a particular version of a port.
However, you must understand how versions are selected in manifest mode. You may need to move `builtin-baseline`.
https://learn.microsoft.com/en-us/vcpkg/users/versioning#version-constraints

**Comment by Poldraunic** [comment]
Hi. Thanks for the reply.

I have skimmed over the article in the link you provided, and I don't know if this does something different as opposed to `baseline` for a `default-registry`. I have `baseline` set to August 2024 release (3508985146f1b1d248c67ead13f8f54be5b4f5da). I am also not setting any version constraints.

Furthermore, like I said in the original post the package works on Windows and MacOS systems.

**Comment by dg0yt** [comment]
It is not a manifest mode problem. The port authors didn't pay attention to case-sensitivity.

**Comment by dg0yt** [comment]
Please test #41036.

**Comment by Poldraunic** [comment]
Hi. 

I would be glad to. I have no idea how to test it though. Do you have a manual?

**Comment by Poldraunic** [comment]
Thank you very much for the fix and quick merge! Everything is working now!

**Comment by dg0yt** [comment]
Thanks for the confirmation :+1:
