### ISSUE TITLE
Transferred a partial file downloading google protobuf.

### ISSUE THREAD

**Issue by jjpepper** [Microsoft/vcpkg#4101]
We are having this "partial file download" issue with `https://github.com/google/protobuf/archive/v3.6.1.tar.gz`

This is a repeatable issue and we can't manually download the file because it's on a CI build machine we don't have access to.  We've seen it 4-5 times in a row.  There is no proxy, and apparently it works for the `x86-windows` triplet.  The development environment is the [Visual Studio 2017 AppVeyor image](https://www.appveyor.com/docs/build-environment/#visual-studio-2017), note however we are cloning vcpkg from scratch into c:\vcpkg rather than using the installed one (AppVeyor states that it comes with `vcpkg 0.0.113` pre-installed, I'm not sure how to make sense of that version number.

```-- Downloading https://github.com/google/protobuf/archive/v3.6.1.tar.gz... Failed. Status: 18;"Transferred a partial file"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:151 (message):
      
      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:108 (vcpkg_download_distfile)
  ports/protobuf/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:71 (include)
Error: Building package protobuf:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: protobuf:x64-windows
  Vcpkg version: 0.0.113-nohash```

**Comment by Voskrese** [comment]
`https://github.com/google/protobuf/releases`

**Comment by jjpepper** [comment]
Care to explain what you mean by those 3 links?

`https://github.com/google/protobuf/archive/v3.6.1.tar.gz` is the file that vcpkg is trying to download.

**Comment by ras0219-msft** [comment]
Hi @jjpepper,

Could you try these two things and let us know if it helps?
- First, pass `--x-use-aria2` to the `vcpkg install` command. This will use the `aria2` download client internally instead of `cmake` which may work better in your scenario.
- Second, if the above doesn't work, could you try explicitly downloading the file via appveyor's instructions[1] as `downloads\google-protobuf-v3.6.1.tar.gz`, and then run the install command?

Knowing which of those works will really help figure out a long term solution!

[1] https://www.appveyor.com/docs/how-to/download-file/

**Comment by jjpepper** [comment]
Hi Robert,
This seems to have stopped happening.  It certainly seemed repeatable at
the time.  If it happens again we will make sure it's repeatable and then
try the two suggestions you have and let you know the results.  Perhaps it
was just an intermittent/temporary fault?
