### ISSUE TITLE
vcpkg install benchmark fails Ubuntu 16.04 with clang 6.0.1

### ISSUE THREAD

**Issue by bowie7070** [Microsoft/vcpkg#4102]
I am trying to install benchmark using vcpkg on Ubuntu 16.04 with clang 6.0.1 and it fails. Any insight on how to resolve this would be appreciated.

owe043@bullet-cl:/software/vcpkg$ ./vcpkg install benchmark
The following packages will be built and installed:
    benchmark[core]:x64-linux
Starting package 1/1: benchmark:x64-linux
Building package benchmark[core]:x64-linux...
-- Using cached /software/vcpkg/downloads/google-benchmark-v1.4.1.tar.gz
-- Using source at /software/vcpkg/buildtrees/benchmark/src/v1.4.1-c49a4f802a
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: /software/vcpkg/downloads/tools/cmake-3.11.4-linux/cmake-3.11.4-Linux-x86_64/bin/cmake;/software/vcpkg/buildtrees/benchmark/src/v1.4.1-c49a4f802a;-DBENCHMARK_ENABLE_TESTING=OFF;-DCMAKE_DEBUG_POSTFIX=d;-DCMAKE_MAKE_PROGRAM=/software/vcpkg/downloads/tools/ninja-1.8.2-linux/ninja;-DCMAKE_SYSTEM_NAME=Linux;-DBUILD_SHARED_LIBS=OFF;-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/software/vcpkg/scripts/toolchains/linux.cmake;-DVCPKG_TARGET_TRIPLET=x64-linux;-DVCPKG_PLATFORM_TOOLSET=external;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=/software/vcpkg/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DVCPKG_CXX_FLAGS=;-DVCPKG_CXX_FLAGS_RELEASE=;-DVCPKG_CXX_FLAGS_DEBUG=;-DVCPKG_C_FLAGS=;-DVCPKG_C_FLAGS_RELEASE=;-DVCPKG_C_FLAGS_DEBUG=;-DVCPKG_CRT_LINKAGE=dynamic;-DVCPKG_LINKER_FLAGS=;-DCMAKE_INSTALL_LIBDIR:STRING=lib;-DCMAKE_INSTALL_BINDIR:STRING=bin;-G;Ninja;-DCMAKE_BUILD_TYPE=Debug;-DCMAKE_INSTALL_PREFIX=/software/vcpkg/packages/benchmark_x64-linux/debug
    Working Directory: /software/vcpkg/buildtrees/benchmark/x64-linux-dbg
    See logs for more information:
      /software/vcpkg/buildtrees/benchmark/config-x64-linux-dbg-out.log
      /software/vcpkg/buildtrees/benchmark/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:255 (vcpkg_execute_required_process)
  ports/benchmark/portfile.cmake:20 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package benchmark:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: benchmark:x64-linux
  Vcpkg version: 0.0.113-unknownhash

Additionally, attach any relevant sections from the log files above.

owe043@bullet-cl:/software/vcpkg$ cat /software/vcpkg/buildtrees/benchmark/config-x64-linux-dbg-out.log
-- The C compiler identification is Clang 6.0.1
-- The CXX compiler identification is Clang 6.0.1
-- Check for working C compiler: /software/clang+llvm-6.0.1-x86_64-linux-gnu-ubuntu-16.04/bin/clang
-- Check for working C compiler: /software/clang+llvm-6.0.1-x86_64-linux-gnu-ubuntu-16.04/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /software/clang+llvm-6.0.1-x86_64-linux-gnu-ubuntu-16.04/bin/clang++
-- Check for working CXX compiler: /software/clang+llvm-6.0.1-x86_64-linux-gnu-ubuntu-16.04/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.7.4")
-- Performing Test HAVE_CXX_FLAG_STD_CXX11
-- Performing Test HAVE_CXX_FLAG_STD_CXX11 - Success
-- Performing Test HAVE_CXX_FLAG_WALL
-- Performing Test HAVE_CXX_FLAG_WALL - Success
-- Performing Test HAVE_CXX_FLAG_WEXTRA
-- Performing Test HAVE_CXX_FLAG_WEXTRA - Success
-- Performing Test HAVE_CXX_FLAG_WSHADOW
-- Performing Test HAVE_CXX_FLAG_WSHADOW - Success
-- Performing Test HAVE_CXX_FLAG_WERROR
-- Performing Test HAVE_CXX_FLAG_WERROR - Success
-- Performing Test HAVE_CXX_FLAG_PEDANTIC
-- Performing Test HAVE_CXX_FLAG_PEDANTIC - Success
-- Performing Test HAVE_CXX_FLAG_PEDANTIC_ERRORS
-- Performing Test HAVE_CXX_FLAG_PEDANTIC_ERRORS - Success
-- Performing Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32
-- Performing Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32 - Success
-- Performing Test HAVE_CXX_FLAG_WFLOAT_EQUAL
-- Performing Test HAVE_CXX_FLAG_WFLOAT_EQUAL - Success
-- Performing Test HAVE_CXX_FLAG_FSTRICT_ALIASING
-- Performing Test HAVE_CXX_FLAG_FSTRICT_ALIASING - Success
-- Performing Test HAVE_CXX_FLAG_WSTRICT_ALIASING
-- Performing Test HAVE_CXX_FLAG_WSTRICT_ALIASING - Success
-- Performing Test HAVE_CXX_FLAG_WD654
-- Performing Test HAVE_CXX_FLAG_WD654 - Failed
-- Performing Test HAVE_CXX_FLAG_WTHREAD_SAFETY
-- Performing Test HAVE_CXX_FLAG_WTHREAD_SAFETY - Success
-- Performing Test HAVE_CXX_FLAG_COVERAGE
-- Performing Test HAVE_CXX_FLAG_COVERAGE - Success
-- Configuring incomplete, errors occurred!
See also "/software/vcpkg/buildtrees/benchmark/x64-linux-dbg/CMakeFiles/CMakeOutput.log".
See also "/software/vcpkg/buildtrees/benchmark/x64-linux-dbg/CMakeFiles/CMakeError.log".

owe043@bullet-cl:/software/vcpkg$ cat /software/vcpkg/buildtrees/benchmark/config-x64-linux-dbg-err.log
-- git Version: v0.0.0
-- Version: 0.0.0
-- Performing Test HAVE_THREAD_SAFETY_ATTRIBUTES
-- Performing Test HAVE_THREAD_SAFETY_ATTRIBUTES
-- Performing Test HAVE_THREAD_SAFETY_ATTRIBUTES -- failed to compile
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX -- failed to compile
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX -- failed to compile
CMake Error at CMakeLists.txt:229 (message):
  Failed to determine the source files for the regular expression backend

owe043@bullet-cl:/software/vcpkg$ clang++ --version
clang version 6.0.1 (tags/RELEASE_601/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /software/clang+llvm-6.0.1-x86_64-linux-gnu-ubuntu-16.04/bin

From my bashrc (environment variables to ensure I am using clang with its own standard library):

export CC=clang
export CXX=clang++
export CXXFLAGS=-stdlib=libc++
export LDFLAGS=-stdlib=libc++

**Comment by Voskrese** [comment]
?
```
export CC=clang
export CXX=g++
```

clang ver 5 or ver 7 ?

**Comment by bowie7070** [comment]
Hi. I'm using clang 6.0.1 which I downloaded from their website as a pre built binary and includes their standard library which I believe I am using. There are older versions of g++ and clang installed in system locations (via standard package manager installation) but the configure output indicates the version I want is being picked up. Although, maybe I'm getting the wrong standard library???

**Comment by bowie7070** [comment]
I installed the pre-built binary from the llvm website but not via the apt package manager. It was just uncompressed into a directory.

I have added the repos for xenial from that website and removed clang and reinstalled it but I still get the same error. Note this is a multi-user system and while I have sudo privileges I am concerned about making system wide changes that will affect other users in surprising ways.


owe043@bullet-cl:/software/vcpkg$ cat /software/vcpkg/buildtrees/benchmark/config-x64-linux-dbg-err.log
-- git Version: v0.0.0
-- Version: 0.0.0
-- Performing Test HAVE_THREAD_SAFETY_ATTRIBUTES
-- Performing Test HAVE_THREAD_SAFETY_ATTRIBUTES
-- Performing Test HAVE_THREAD_SAFETY_ATTRIBUTES -- failed to compile
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX -- failed to compile
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX -- failed to compile
CMake Error at CMakeLists.txt:229 (message):
  Failed to determine the source files for the regular expression backend

**Comment by bowie7070** [comment]
It seems to be that my CXXFLAGS is being ignored but not my CXX. If I set

export CXX=clang++-libc++

Everything works as expected. Note:
owe043@bullet-cl:~$ cat $(which clang++-libc++)
#!/bin/sh
clang++ -stdlib=libc++ "$@"

**Comment by Voskrese** [comment]
https://github.com/Microsoft/vcpkg/blob/master/docs/users/triplets.md#vcpkg_cxx_flags

**Comment by Voskrese** [comment]
```
root@net:~/tmp/vcpkg# export CC=clang
root@net:~/tmp/vcpkg# export CXX=clang++
root@net:~/tmp/vcpkg# ./vcpkg install benchmark
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be built and installed:
    benchmark[core]:x64-linux
Starting package 1/1: benchmark:x64-linux
Building package benchmark[core]:x64-linux...
-- Downloading https://github.com/google/benchmark/archive/v1.4.1.tar.gz...
-- Extracting source /root/tmp/vcpkg/downloads/google-benchmark-v1.4.1.tar.gz
-- Using source at /root/tmp/vcpkg/buildtrees/benchmark/src/v1.4.1-c49a4f802a
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package benchmark[core]:x64-linux... done
Installing package benchmark[core]:x64-linux...
Installing package benchmark[core]:x64-linux... done
Elapsed time for package benchmark:x64-linux: 3.598 min

Total elapsed time: 3.598 min

The package benchmark:x64-linux provides CMake targets:

    find_package(benchmark CONFIG REQUIRED)
    target_link_libraries(main PRIVATE benchmark::benchmark benchmark::benchmark_main)
```

**Comment by Voskrese** [comment]
```
export CMAKE_CXX_FLAGS="-stdlib=libc++"
export VCPKG_CXX_FLAGS="-stdlib=libc++"

export CMAKE_C_FLAGS="-stdlib=libc++"
export VCPKG_C_FLAGS="-stdlib=libc++"
```

```
root@net:~/tmp/vcpkg# ./vcpkg remove benchmark
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be removed:
    benchmark:x64-linux
Removing package benchmark:x64-linux...
Removing package benchmark:x64-linux... done
Purging package benchmark:x64-linux...
Purging package benchmark:x64-linux... done
root@net:~/tmp/vcpkg# ./vcpkg install benchmark --debug
[DEBUG] Using vcpkg-root: /root/tmp/vcpkg
The following packages will be built and installed:
    benchmark[core]:x64-linux
Starting package 1/1: benchmark:x64-linux
Building package benchmark[core]:x64-linux...
[DEBUG] popen(which cmake 2>&1)
[DEBUG] _pclose() returned 0 after   129643 us
[DEBUG] popen("/root/tmp/vcpkg/downloads/tools/cmake-3.11.4-linux/cmake-3.11.4-Linux-x86_64/bin/cmake" --version 2>&1)
[DEBUG] _pclose() returned 0 after  1275742 us
[DEBUG] popen("/root/tmp/vcpkg/downloads/tools/cmake-3.11.4-linux/cmake-3.11.4-Linux-x86_64/bin/cmake" "-DCMAKE_TRIPLET_FILE=/root/tmp/vcpkg/triplets/x64-linux.cmake" -P "/root/tmp/vcpkg/scripts/get_triplet_environment.cmake" 2>&1)
[DEBUG] _pclose() returned 0 after   143463 us
[DEBUG] popen(shasum -a 1 "/root/tmp/vcpkg/triplets/x64-linux.cmake" 2>&1)
[DEBUG] _pclose() returned 0 after   571431 us
[DEBUG] popen(shasum -a 1 "/root/tmp/vcpkg/scripts/toolchains/linux.cmake" 2>&1)
[DEBUG] _pclose() returned 0 after   168370 us
[DEBUG] popen(which ninja 2>&1)
[DEBUG] _pclose() returned 0 after    63512 us
[DEBUG] popen("/root/tmp/vcpkg/downloads/tools/ninja-1.8.2-linux/ninja" --version 2>&1)
[DEBUG] _pclose() returned 0 after   129853 us
[DEBUG] popen(which git 2>&1)
[DEBUG] _pclose() returned 0 after    62551 us
[DEBUG] popen("/usr/bin/git" --version 2>&1)
[DEBUG] _pclose() returned 0 after   174471 us
[DEBUG] system("/root/tmp/vcpkg/downloads/tools/cmake-3.11.4-linux/cmake-3.11.4-Linux-x86_64/bin/cmake" "-DCMD=BUILD" "-DPORT=benchmark" "-DCURRENT_PORT_DIR=/root/tmp/vcpkg/ports/benchmark" "-DTARGET_TRIPLET=x64-linux" "-DVCPKG_PLATFORM_TOOLSET=external" "-DVCPKG_USE_HEAD_VERSION=0" "-D_VCPKG_NO_DOWNLOADS=0" "-D_VCPKG_DOWNLOAD_TOOL=BUILT_IN" "-DGIT=/usr/bin/git" "-DFEATURES=core" "-DALL_FEATURES=" -P "/root/tmp/vcpkg/scripts/ports.cmake")
-- Using cached /root/tmp/vcpkg/downloads/google-benchmark-v1.4.1.tar.gz
-- Using source at /root/tmp/vcpkg/buildtrees/benchmark/src/v1.4.1-c49a4f802a
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
[DEBUG] system() returned 0 after 147785430 us
-- Performing post-build validation
-- Performing post-build validation done
Building package benchmark[core]:x64-linux... done
Installing package benchmark[core]:x64-linux...
Installing package benchmark[core]:x64-linux... done
Elapsed time for package benchmark:x64-linux: 2.512 min

Total elapsed time: 2.512 min

The package benchmark:x64-linux provides CMake targets:

    find_package(benchmark CONFIG REQUIRED)
    target_link_libraries(main PRIVATE benchmark::benchmark benchmark::benchmark_main)

[DEBUG] ../src/vcpkg/install.cpp(683)
[DEBUG] Exiting after 151424100 us (151390248 us)
```

**Comment by bowie7070** [comment]
Nope. Still dies.

owe043@bullet-cl:/software/vcpkg$ export CMAKE_CXX_FLAGS="-stdlib=libc++"
owe043@bullet-cl:/software/vcpkg$ export VCPKG_CXX_FLAGS="-stdlib=libc++"
owe043@bullet-cl:/software/vcpkg$ ./vcpkg install benchmark
The following packages will be built and installed:
    benchmark[core]:x64-linux
Starting package 1/1: benchmark:x64-linux
Building package benchmark[core]:x64-linux...
-- Using cached /software/vcpkg/downloads/google-benchmark-v1.4.1.tar.gz
-- Using source at /software/vcpkg/buildtrees/benchmark/src/v1.4.1-c49a4f802a
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: /software/vcpkg/downloads/tools/cmake-3.11.4-linux/cmake-3.11.4-Linux-x86_64/bin/cmake;/software/vcpkg/buildtrees/benchmark/src/v1.4.1-c49a4f802a;-DBENCHMARK_ENABLE_TESTING=OFF;-DCMAKE_DEBUG_POSTFIX=d;-DCMAKE_MAKE_PROGRAM=/software/vcpkg/downloads/tools/ninja-1.8.2-linux/ninja;-DCMAKE_SYSTEM_NAME=Linux;-DBUILD_SHARED_LIBS=OFF;-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/software/vcpkg/scripts/toolchains/linux.cmake;-DVCPKG_TARGET_TRIPLET=x64-linux;-DVCPKG_PLATFORM_TOOLSET=external;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=/software/vcpkg/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DVCPKG_CXX_FLAGS=;-DVCPKG_CXX_FLAGS_RELEASE=;-DVCPKG_CXX_FLAGS_DEBUG=;-DVCPKG_C_FLAGS=;-DVCPKG_C_FLAGS_RELEASE=;-DVCPKG_C_FLAGS_DEBUG=;-DVCPKG_CRT_LINKAGE=dynamic;-DVCPKG_LINKER_FLAGS=;-DCMAKE_INSTALL_LIBDIR:STRING=lib;-DCMAKE_INSTALL_BINDIR:STRING=bin;-G;Ninja;-DCMAKE_BUILD_TYPE=Debug;-DCMAKE_INSTALL_PREFIX=/software/vcpkg/packages/benchmark_x64-linux/debug
    Working Directory: /software/vcpkg/buildtrees/benchmark/x64-linux-dbg
    See logs for more information:
      /software/vcpkg/buildtrees/benchmark/config-x64-linux-dbg-out.log
      /software/vcpkg/buildtrees/benchmark/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:255 (vcpkg_execute_required_process)
  ports/benchmark/portfile.cmake:20 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package benchmark:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: benchmark:x64-linux
  Vcpkg version: 0.0.113-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by bowie7070** [comment]
Adding to triplets/x64-linux.cmake does work:
set(VCPKG_CXX_FLAGS -stdlib=libc++)
set(VCPKG_C_FLAGS '')

**Comment by wangli28** [comment]
Please open a new issue if this is still a problem for you.
Thanks.
