### ISSUE TITLE
[freeimage] Fatal build when add costom definition under editable mode.

### ISSUE THREAD

**Issue by ChivenZhang** [microsoft/vcpkg#41025]
**Describe the bug**
I used freeimage library. The wrong thing happend when I try to change BGRA color order into RGBA by adding new definition in CMakeLists.txt under editable mode. There are lots fatal log reported. Below shows how I operated:

**Environment**
- OS: Windows
- Compiler: MSVC2019

**To Reproduce**
> 1 vcpkg install freeimage:x64-windows --editable
> 2 add definition "#define FREEIMAGE_COLORORDER FREEIMAGE_COLORORDER_RGB" in FreeImage.h
> 3 vcpkg install freeimage:x64-windows --editable

![image](https://github.com/user-attachments/assets/abb9bd92-8529-4595-849d-1223d286cbea)

**Expected behavior**
Build successfully.

**Failure logs**
![image](https://github.com/user-attachments/assets/ef32884a-5167-4f88-abbd-7e7458f54b07)

**Additional context**

**Comment by WangWeiLin-MV** [comment]
Please append error logs.

**Comment by ChivenZhang** [comment]
> Please append error logs.

Do you mean failure logs ? If not I don't know where the error logs file locates.

**Comment by WangWeiLin-MV** [comment]
As shown in your screenshot:

```log
See logs for more information:
    D:\GitProject\vcpkg\buildtrees\freeimage\install-x64-windows-dbg-out.log
```

**Comment by ChivenZhang** [comment]
![image](https://github.com/user-attachments/assets/ba799814-bd97-4e81-a279-12e909019280)
[install-x64-windows-dbg-out.log](https://github.com/user-attachments/files/17052528/install-x64-windows-dbg-out.log)
