### ISSUE TITLE
[openal-soft] Re-enable the DirectSound backend

### ISSUE THREAD

**Issue by TomGoodIdea** [microsoft/vcpkg#41035]
### Is your feature request related to a problem? Please describe.

#15634 disabled the WinMM and DSound backends to prevent potential build errors. However, the PR's description only mentions problems with WinMM. So, it seems that the removal of DSound didn't fix anything, while breaking compatibility with pre-Vista Windows systems.

### Proposed solution

Re-enable the DirectSound backend.

**Comment by JonLiu1993** [comment]
````
To solve this problem, we disabled the WINMM and DSOUND backends in openal-soft. This does not result in any loss of functionality, because starting with Windows Vista, WINMM and DSOUND are implemented by the Windows native WASAPI.
````
@Hoikas has explained that starting from Windows Vista, WINMM and DSOUND are implemented by the Windows native WASAPI. The DALSOFT_REQUIRE_WASAPI option already meets your needs. Do you have any other questions?

**Comment by TomGoodIdea** [comment]
That's the problem, WASAPI is available only on Vista and later versions.
