### ISSUE TITLE
[VTK-8.1] Building package vtk:x64-linux failed with: POST_BUILD_CHECKS_FAILED

### ISSUE THREAD

**Issue by stefan-gavranovic** [microsoft/vcpkg#4103]
When trying to build VTK 8.1 (Linux) at the final stage I get the following error:

    -- Configuring x64-linux-dbg
    -- Configuring x64-linux-rel
    -- Building x64-linux-dbg
    -- Building x64-linux-rel
    -- Performing post-build validation
    There should be no empty directories in /home/xubuntu/Software/vcpkg/packages/vtk_x64-linux
    The following empty directories were found: 

        /home/xubuntu/Software/vcpkg/packages/vtk_x64-linux/tools/vtk

    If a directory should be populated but is not, this might indicate an error in the portfile.
    If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

        file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/a/dir ${CURRENT_PACKAGES_DIR}/some/other/dir)

    Found 1 error(s). Please correct the portfile:
        /home/xubuntu/Software/vcpkg/ports/vtk/portfile.cmake
    -- Performing post-build validation done
    Error: Building package vtk:x64-linux failed with: POST_BUILD_CHECKS_FAILED
    Please ensure you're using the latest portfiles with `.\vcpkg update`, then submit an issue at https://github.com/Microsoft/vcpkg/issues including:
      Package: vtk:x64-linux
      Vcpkg version: 0.0.113-unknownhash

Although all the files are located in `vtk/lib` folder, `vtk` is not listed as installed in `vcpkg`

**Comment by PhoebeHui** [comment]
This issue fixed now, I tried installed vtk on linux, everything installed successfully.

Starting package 19/19: vtk:x64-linux
Building package vtk[core]:x64-linux...
CMake Warning at ports/vtk/portfile.cmake:2 (message):
  You will need to install Xorg dependencies to build vtk:
  apt-get install libxt-dev
Call Stack (most recent call first):
  scripts/ports.cmake:74 (include)
-- Downloading https://github.com/Kitware/VTK/archive/v8.2.0.tar.gz...
-- Extracting source /home/vwangli/Phoebe/vcpkg/downloads/Kitware-VTK-v8.2.0.tar.gz
-- Applying patch fix-find-lz4.patch
-- Applying patch fix_ogg_linkage.patch
-- Applying patch fix-pugixml-link.patch
-- Applying patch hdf5_static.patch
-- Using source at /home/vwangli/Phoebe/vcpkg/buildtrees/vtk/src/v8.2.0-b37306c27c
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package vtk[core]:x64-linux... done
Installing package vtk[core]:x64-linux...
Installing package vtk[core]:x64-linux... done
Elapsed time for package vtk:x64-linux: 19.59 min

Total elapsed time: 24.77 min

The package vtk:x64-linux provides CMake targets:

    find_package(VTK CONFIG REQUIRED)
    # Note: 105 target(s) were omitted.
    target_link_libraries(main PRIVATE foo vtksys ${name} somelib)
