### ISSUE TITLE
Downloading vcpkg.exe failed.

### ISSUE THREAD

**Issue by robswindoll** [microsoft/vcpkg#41045]
### Operating system

Windows 11 Pro

### Compiler

MS VS

### Steps to reproduce the behavior

```Shell
While using command window and running following command I get an error.

cd vcpkg && bootstrap-vcpkg.bat

In looking with a browser at https://github.com/microsoft/vcpkg-tool, the subfolder /releases, does not appear. Possibly it is hidden to me. Note that bootstrap-vcpkg.bat was trying to download https://github.com/microsoft/vcpkg-tool/releases/download/2024-08-01/vcpkg.exe. I could not locate this file using the MS edge browser.
```

### Failure logs

C:\Windows\System32>cd vcpkg && bootstrap-vcpkg.bat
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2024-08-01/vcpkg.exe -> C:\Windows\System32\vcpkg\vcpkg.exeWhile calling Windows API function CreateFileW got error 0x00000003:
The system cannot find the path specified.

C:\Windows\System32\vcpkg\scripts\bootstrap.ps1 : Downloading vcpkg.exe failed. Please check your internet connection,
or consider downloading a recent vcpkg.exe from https://github.com/microsoft/vcpkg-tool with a browser.
At line:1 char:4
+ & {& "C:\Windows\System32\vcpkg\scripts\bootstrap.ps1" }
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,bootstrap.ps1

ScriptHalted
At C:\Windows\System32\vcpkg\scripts\bootstrap.ps1:63 char:5
+     throw
+     ~~~~~
    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
    + FullyQualifiedErrorId : ScriptHalted

### Additional context

Note that the prior command issue to clone the repository work fine:

git clone https://github.com/microsoft/vcpkg.git.

The internet connection was also working.

**Comment by dg0yt** [comment]
vcpkg in `C:\windows\System32`, seriously?

**Comment by robswindoll** [comment]
I had opened the command window as an administrator.  Not sure if this was the cause of the problem, but I was able to successfully install vcpkg by using a standard command window.

**Comment by ascpixi** [comment]
I had this error while running from a standard cmd window - I opened one with admin priviledges, and the installation succeeded for me. I'd like to also note that I was running the script from `D:\Code\vcpkg`, a location that wouldn't need any admin privilidges to read from or write to.
