### ISSUE TITLE
[New Port Request] Boost - Version 1.86.0

### ISSUE THREAD

**Issue by swproz** [microsoft/vcpkg#41040]
### Library name

Boost

### Library description

The Boost project provides free peer-reviewed portable C++ source libraries.

### Source repository URL

https://github.com/boostorg/boost

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

Boost is used everywhere - please have the latest version (1.86.0) available via vcpkg.
If Conan can do it, so can you/vcpkg - thanks!!

(//https://conan.io/center/recipes/boost)

**Comment by xavier2k6** [comment]
- #40558
