### ISSUE TITLE
GUI apps built with OpenCV from WSL vcpkg don't work

### ISSUE THREAD

**Issue by patrikhuber** [Microsoft/vcpkg#4104]
I've got `opencv:x64-linux` installed and I'm compiling an app that opens an OpenCV `highgui` window. I can compile this fine with g++ on WSL and opencv from vcpkg in WSL too.
However when executing this app on a "real" Linux machine (where X server is running), I get:

```
./test-app
OpenCV(3.4.1) Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvNamedWindow, file /mnt/c/Users/Patrik/vcpkg/buildtrees/opencv/src/opencv-3.4.1/modules/highgui/src/window.cpp, line 618
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.1) /mnt/c/Users/Patrik/vcpkg/buildtrees/opencv/src/opencv-3.4.1/modules/highgui/src/window.cpp:618: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvNamedWindow

Aborted (core dumped)
```

I suppose this is because OpenCV in vcpkg WSL is built without GUI or GTK+ support. Anything we can do about that?

@jasjuang Hi, I thought I'd CC you because you seem to work with OpenCV and vcpkg quite a lot - maybe you've encountered a similar scenario or got an idea for a solution?

Cheers :-)

**Comment by patrikhuber** [comment]
I don't think this is WSL related. I just tried the same with vcpkg on a "real" Ubuntu 16.04 (no WSL), and I got the same error in the app. Seems like OpenCV in vcpkg-linux is built in a way that does not enable opening windows with the highgui module?

**Comment by patrikhuber** [comment]
@Voskrese Not quite I think:

```
C:\Users\Patrik\vcpkg\buildtrees\opencv\src [master ≡ +1 ~0 -0 !]> ls


    Directory: C:\Users\Patrik\vcpkg\buildtrees\opencv\src


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       21.05.2018     18:49                3.4.1-273ea13f6d
d-----       24.04.2018     21:21                opencv-3.4.1
-a----       24.04.2018     21:21              0 opencv-opencv-3.4.1.tar.gz.extracted


C:\Users\Patrik\vcpkg\buildtrees\opencv\src [master ≡ +1 ~0 -0 !]> cmake -LA .
CMake Error: The source directory "C:/Users/Patrik/vcpkg/buildtrees/opencv/src" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
-- Cache values
C:\Users\Patrik\vcpkg\buildtrees\opencv\src [master ≡ +1 ~0 -0 !]> cd .\opencv-3.4.1\
C:\Users\Patrik\vcpkg\buildtrees\opencv\src\opencv-3.4.1 [master ≡ +1 ~0 -0 !]> cmake -LA .
-- Building for: Visual Studio 15 2017
CMake Error at CMakeLists.txt:11 (message):


  FATAL: In-source builds are not allowed.

         You should create a separate directory for build files.



-- Configuring incomplete, errors occurred!
-- Cache values
C:\Users\Patrik\vcpkg\buildtrees\opencv\src\opencv-3.4.1 [master ≡ +1 ~0 -0 !]> cd ..
C:\Users\Patrik\vcpkg\buildtrees\opencv\src [master ≡ +1 ~0 -0 !]> cd .\3.4.1-273ea13f6d\
C:\Users\Patrik\vcpkg\buildtrees\opencv\src\3.4.1-273ea13f6d [master ≡ +1 ~0 -0 !]> cmake -LA .
-- Building for: Visual Studio 15 2017
CMake Error at CMakeLists.txt:11 (message):


  FATAL: In-source builds are not allowed.

         You should create a separate directory for build files.



-- Configuring incomplete, errors occurred!
-- Cache values
C:\Users\Patrik\vcpkg\buildtrees\opencv\src\3.4.1-273ea13f6d [master ≡ +1 ~0 -0 !]>
```

**Comment by Voskrese** [comment]
?
`%comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2017\...\Common7\Tools\VsDevCmd.bat"`

`where cmake`
`where cl`
`where ninja`

**Comment by patrikhuber** [comment]
@Voskrese I can run all these commands successfully, except for the last one again - `FATAL: In-source builds are not allowed.`. For some reason, CMake recognises this directory as being within the source directory. Not sure why.

**Comment by Voskrese** [comment]
Remove and unpack, apparently saved cache

**Comment by jasjuang** [comment]
@patrikhuber Sorry I am not using vcpkg on linux so I won't be able to help on this one

**Comment by patrikhuber** [comment]
Thanks @jasjuang!

Btw, `sudo apt install libgtk2.0-dev pkg-config` and then reinstalling OpenCV fixed this.

**Comment by kvlevin** [comment]
@patrikhuber  I meet Same issue too.How to recomile OpenCV with vcpkg?

**Comment by patrikhuber** [comment]
@kvlevin I'm afraid this was too long ago. I would suggest you read through this issue and if there is still a problem, address this with the vcpkg team.

**Comment by kvlevin** [comment]
Thank you for reply.I did it with apt.and give up vcpkg.there are more bugs than expected.
