### ISSUE TITLE
[libmysql] Build error on x64-windows

### ISSUE THREAD

**Issue by 244916896** [microsoft/vcpkg#41044]
Copy issue body from E:/develop/c_c++/vcpkg_windows_demo.git/build/vcpkg_installed/vcpkg/issue_body.md

**Comment by 244916896** [comment]
[cmake] -- Using source at E:/develop/c_c++/vcpkg20240823.git/buildtrees/libmysql/src/sql-8.0.34-d7480bef4c.clean
[cmake] -- Found external ninja('1.10.2').
[cmake] -- Configuring x64-windows
[cmake] CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
[cmake]     Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
[cmake]     Working Directory: E:/develop/c_c++/vcpkg20240823.git/buildtrees/libmysql/x64-windows-rel/vcpkg-parallel-configure
[cmake]     Error code: 1
[cmake]     See logs for more information:
[cmake]       E:\develop\c_c++\vcpkg20240823.git\buildtrees\libmysql\config-x64-windows-dbg-CMakeCache.txt.log
[cmake]       E:\develop\c_c++\vcpkg20240823.git\buildtrees\libmysql\config-x64-windows-rel-CMakeCache.txt.log
[cmake]       E:\develop\c_c++\vcpkg20240823.git\buildtrees\libmysql\config-x64-windows-dbg-CMakeConfigureLog.yaml.log
[cmake]       E:\develop\c_c++\vcpkg20240823.git\buildtrees\libmysql\config-x64-windows-rel-CMakeConfigureLog.yaml.log
[cmake]       E:\develop\c_c++\vcpkg20240823.git\buildtrees\libmysql\config-x64-windows-out.log
[cmake] 
[cmake] Call Stack (most recent call first):
[cmake]   E:/develop/c_c++/vcpkg_windows_demo.git/build/vcpkg_installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:269 (vcpkg_execute_required_process)
[cmake]   buildtrees/versioning_/versions/libmysql/4fa6006119f50a9baff9cdf0966b065097113fd7/portfile.cmake:54 (vcpkg_cmake_configure)
[cmake]   scripts/ports.cmake:192 (include)
[cmake] 
[cmake] 
[cmake] error: building libmysql:x64-windows failed with: BUILD_FAILEDSee https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
[cmake] Elapsed time to handle libmysql:x64-windows: 1.9 min
[cmake] Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
[cmake] Then check for known issues at:
[cmake]   https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libmysql
[cmake] You can submit a new issue at:
[cmake]   https://github.com/microsoft/vcpkg/issues/new?title=[libmysql]+Build+error+on+x64-windows&body=Copy+issue+body+from+E%3A%2Fdevelop%2Fc_c%2B%2B%2Fvcpkg_windows_demo.git%2Fbuild%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md

**Comment by 244916896** [comment]
{
  "dependencies": [
    {
      "name": "fmt",
      "version>=": "10.2.1"
    },
    {
      "name":"sqlpp11",
      "version>=":"0.64",
      "features":["mysql"]
    }
  ],
  "builtin-baseline": "1de2026f28ead93ff1773e6e680387643e914ea1"
}

**Comment by dg0yt** [comment]
> `E:\develop\c_c++\...`

Try a path without special chars such as `+`, ` `, ...

**Comment by 244916896** [comment]
this is good ,thanks!
