### ISSUE TITLE
Custom Openssl Installation

### ISSUE THREAD

**Issue by Ashwin609** [microsoft/vcpkg#41066]
**Describe the bug**
I am using vcpkg for windows to build openvpn from source code on windows. Now for this i already have openssl installed, but i am not able to use this custom openssl instead vcpkg install always installs new openssl. How can i use my custom openssl.

**Comment by WangWeiLin-MV** [comment]
You could find system `openssl` by CMake function https://cmake.org/cmake/help/latest/module/FindOpenSSL.html, you may also need to specify the search path.

**Comment by dg0yt** [comment]
The general answer to such situations is to provide an empty overlay port (here: for openssl). Cf. https://devblogs.microsoft.com/cppblog/using-system-package-manager-dependencies-with-vcpkg/#using-curl-and-openssl-from-the-system-package-manager

Note that that vcpkg's openssl port also installs a wrapper for `find_package(OpenSSL)` which deals with correctly supplying debug and release binaries etc. When not using the vcpkg port, reverse dependencies might fail to build or might link the wrong configuration.

**Comment by dg0yt** [comment]
> You could find system `openssl` by CMake function https://cmake.org/cmake/help/latest/module/FindOpenSSL.html, you may also need to specify the search path.

This misses the point of the question.

**Comment by dg0yt** [comment]
@rizkyblackhat Make a proper new issue or discussion.

**Comment by dg0yt** [comment]
(I see, still the same question.) Well, FTR the proper answer is: Use an (almost) empty overlay port for openssl. Satisfying dependency vcpkg resolution, but not providing an openssl installation.
