### ISSUE TITLE
[hdf5] HDF5 could not be found because dependency szip could not be found.

### ISSUE THREAD

**Issue by jjjkkyz** [microsoft/vcpkg#41072]
**Describe the bug**

Reported error in VS 2022:

```
严重性	代码	说明	项目	文件	行	禁止显示状态	详细信息
错误		CMake Error at E:/cpp_env/vcpkg/installed/x64-windows/share/hdf5/vcpkg-cmake-wrapper.cmake:16 (_find_package):
  Found package configuration file:

    E:/cpp_env/vcpkg/installed/x64-windows/share/hdf5/hdf5-config.cmake

  but it set HDF5_FOUND to FALSE so package "HDF5" is considered to be NOT
  FOUND.  Reason given by package:

  HDF5 could not be found because dependency szip could not be found.		E:/cpp_env/vcpkg/installed/x64-windows/share/hdf5/vcpkg-cmake-wrapper.cmake	16		
```

**Environment**
- OS: Windows
- Compiler: VS 2022

**To Reproduce**
vcpkg install hdf5

**Expected behavior**
szip is properly installed and can be found by vcpkg list

**Comment by LilyWangLL** [comment]
I can't repro this issue locally, could you please provide the more information about the installation of `hdf5`? And do you install it on the latest vcpkg?

**Comment by LilyWangLL** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
