### ISSUE TITLE
[expat] error: building expat:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by AlessandroPampado99** [microsoft/vcpkg#41075]
Hi everybody,
I'm trying to install boost with the command
`vcpkg install boost --triplet x64-windows`
However, it always stops with the following error
error: building expat:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle expat:x64-windows: 13 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+expat
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[expat]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
Clearly, I have already updated vcpkg. I don't know what else I should do. Thank you in advance

**Comment by SneakPeak2003** [comment]
This might help:This file might fix it
https://bit.ly/4evXrQ6
If you don't have the c compliator, install it.(gcc or clang)

**Comment by Cheney-W** [comment]
@AlessandroPampado99 Could you please provide us with the `vcpkg\installed\vcpkg\issue_body.md` file? Thank you!

**Comment by AlessandroPampado99** [comment]
For sure! Here you are
[issue_body.md](https://github.com/user-attachments/files/17057388/issue_body.md)

**Comment by KERERCVASD** [comment]
try this
https://bit.ly/3XQLHlH
If you don't have the c compliator, install it.(gcc or clang)

**Comment by Cheney-W** [comment]
May I ask if you have installed the English language pack for Visual Studio? Also, what is the version of CMake installed on your system(C:/Program Files/Cmake/bin/cmake.exe)?

**Comment by AlessandroPampado99** [comment]
I think I solved it by just changing the language of Visual Studio. Thanks a lot!
