### ISSUE TITLE
SFML dependency dll is currently required to be manually added to build path

### ISSUE THREAD

**Issue by IronicallySerious** [microsoft/vcpkg#4107]
I am running Windows 10 and using SFML through vcpkg is not adding `lcms2.dll` to the build directory upon building the project.

The program throws an error saying `lcms2.dll` was not found and that reinstalling the program may fix it.
I am currently working around this by manually adding a verified `lcms2.dll` file to my build directory.

However, I have been facing this problem from a few weeks back. It may have broken before.

**Comment by wangli28** [comment]
Hi @IronicallySerious, thanks for posting this issue. Do you run `.\vcpkg.exe integrate project` and `.\vcpkg.exe integrate install` on your VCPKG before creating project?

**Comment by IronicallySerious** [comment]
I have seen this issue get solved on its own btw (https://github.com/microsoft/vcpkg/issues/3498). This issue can be closed now safely. I don't get this issue now.

However, to answer your question, yes I did run all the required steps as given in the readme.
