### ISSUE TITLE
Error installing coinutils pybind11

### ISSUE THREAD

**Issue by AlessandroPampado99** [microsoft/vcpkg#41089]
Hello!
I'm trying to install COIN-OR CoinUtils in Windows, according to https://gitlab.com/smspp/smspp-project/-/wikis/Installing-SMS++#requirements. However, if I  write

 vcpkg install coinutils pybind11 --triplet x64-windows

the following error appears

error: building openblas:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle openblas:x64-windows: 17 s
read_contents("C:\vcpkg\buildtrees\openblas\config-x64-windows-out.log"): permission denied 

config-x64-windows-out.log states:

MSVC
CMake Error at cmake/prebuild.cmake:1376 (try_compile):
  Cannot copy output executable

    'C:/vcpkg/buildtrees/openblas/x64-windows-dbg/getarch_build/CMakeFiles/CMakeTmp/cmTC_f9689.exe'

  to destination specified by COPY_FILE:

    'C:/vcpkg/buildtrees/openblas/x64-windows-dbg/getarch.exe'

  because:

    Permission denied (output)

Call Stack (most recent call first):
  cmake/system.cmake:170 (include)
  CMakeLists.txt:104 (include)

And I don't know how to solve it. Could you please help me? Thank you in advance.

**Comment by Osyotr** [comment]
Permission denied errors on windows are often due to AV software.

**Comment by WangWeiLin-MV** [comment]
Using the latest version of vcpkg for local installation does not reproduce the issue.

It is probably an antivirus lock race. Could you please try again?
