### ISSUE TITLE
[gdal] build failure

### ISSUE THREAD

**Issue by AmoXT** [microsoft/vcpkg#41098]
### Operating system

windows 10 x64

### Compiler

MSVC14

### Steps to reproduce the behavior

```Shell
./vcpkg install gdal:x64-windows
```

### Failure logs

PS E:\vcpkg> .\vcpkg install gdal:x64-windows
Computing installation plan...
warning: vcpkg appears to be in a Visual Studio prompt targeting x86 but installing for x64-windows. Consider using --triplet x86-windows or --triplet x86-uwp.
The following packages will be built and installed:
    gdal[core,curl,default-features,expat,geos,gif,hdf5,iconv,jpeg,lerc,libkml,libspatialite,libxml2,lzma,netcdf,openjpeg,openssl,pcre2,png,postgresql,qhull,recommended-features,sqlite3,webp,zstd]:x64-windows@3.9.2
Detecting compiler hash for triplet x64-windows...
-- Setting "%HTTP_PROXY%" environment variables to "127.0.0.1:9981".
-- Setting "%HTTPS_PROXY%" environment variables to "127.0.0.1:9981".
-- Setting "%SOCKS5_PROXY%" environment variables to "127.0.0.1:9981".
Compiler found: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from C:\Users\lenovo\AppData\Local\vcpkg\archives in 266 us. Use --debug to see more details.
Installing 1/1 gdal[core,curl,default-features,expat,geos,gif,hdf5,iconv,jpeg,lerc,libkml,libspatialite,libxml2,lzma,netcdf,openjpeg,openssl,pcre2,png,postgresql,qhull,recommended-features,sqlite3,webp,zstd]:x64-windows@3.9.2...
Building gdal[core,curl,default-features,expat,geos,gif,hdf5,iconv,jpeg,lerc,libkml,libspatialite,libxml2,lzma,netcdf,openjpeg,openssl,pcre2,png,postgresql,qhull,recommended-features,sqlite3,webp,zstd]:x64-windows@3.9.2...
-- Using cached OSGeo-gdal-v3.9.2.tar.gz.
-- Cleaning sources at E:/vcpkg/buildtrees/gdal/src/v3.9.2-9586dcef0a.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/vcpkg/downloads/OSGeo-gdal-v3.9.2.tar.gz
-- Applying patch find-link-libraries.patch
-- Applying patch fix-gdal-target-interfaces.patch
-- Applying patch libkml.patch
-- Applying patch target-is-valid.patch
-- Using source at E:/vcpkg/buildtrees/gdal/src/v3.9.2-9586dcef0a.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: E:/vcpkg/downloads/tools/cmake-3.29.2-windows/cmake-3.29.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: E:/vcpkg/buildtrees/gdal/x64-windows-dbg
    See logs for more information:
      E:\vcpkg\buildtrees\gdal\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/gdal/portfile.cmake:106 (vcpkg_cmake_install)
  scripts/ports.cmake:192 (include)

error: building gdal:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle gdal:x64-windows: 8.6 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+gdal
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[gdal]+Build+error+on+x64-windows&body=Copy+issue+body+from+E%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

[install-x64-windows-dbg-out.log](https://github.com/user-attachments/files/17079754/install-x64-windows-dbg-out.log)

**Comment by AmoXT** [comment]
It seems happen when installing. Is there anyway to avoid this problem?

**Comment by Osyotr** [comment]
> e:\vcpkg\buildtrees\gdal\src\v3.9.2-9586dcef0a.clean\apps\argparse/argparse.hpp(1780): fatal error C1001: An internal error has occurred in the compiler.

Use newer compiler ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Comment by AmoXT** [comment]
> > e:\vcpkg\buildtrees\gdal\src\v3.9.2-9586dcef0a.clean\apps\argparse/argparse.hpp(1780): fatal error C1001: An internal error has occurred in the compiler.
> 
> Use newer compiler ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

Thanks for your help. It's the time to upgrade my vs version.
