### ISSUE TITLE
Error from vcpkg.cmake: 'CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".' WSL Arch

### ISSUE THREAD

**Issue by carljohnson93** [microsoft/vcpkg#41095]
**Describe the bug**
When running "cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake" I get an error "CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".". I have `make` installed, so the actual generator does not matter, the issue still appears if I use `-G'Ninja'` (I also have `ninja` installed).

**Environment**
- OS: Windows 10, WSL Arch Linux (https://github.com/yuk7/ArchWSL)
- Compiler: GCC 14.2.1

**To Reproduce**
1. Execute following shell commands:
```bash
mkdir test && cd test
git clone --depth=1 https://github.com/microsoft/vcpkg
echo '{"dependencies":["fmt"]}' >vcpkg.json
echo 'int main() {}' >main.c
{
  echo "cmake_minimum_required(VERSION 3.10)"
  echo "project(test)"
  echo "find_package(fmt CONFIG REQUIRED)"
  echo "add_executable(main main.c)"
} >CMakeLists.txt
cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake
```

**Expected behavior**
No error

**Failure logs**
I couldn't find any failure logs

**Comment by Osyotr** [comment]
What the full error log? I suspect that the path to the toolchain is wrong.

**Comment by carljohnson93** [comment]
@Osyotr the path to the toolchain isn't wrong. I tried to specify path prefixed with ${HOME}/test/ and it made no difference. And error message says that the error occured in .../buildsystems/vcpkg.cmake so it's not that.

**Comment by Osyotr** [comment]
Ok but what is the *full* output? The message you mentioned is usually a result of some previous error.

**Comment by carljohnson93** [comment]
I'm sorry I have reinstalled windows for different reasons, and installed WSL with openSUSE tumbleweed distro this time, so I cannot provide full error output.

**Comment by dg0yt** [comment]
Then this issue can be closed,
