### ISSUE TITLE
error: in triplet x64-windows: Unable to find a valid Visual Studio instance Could not locate a complete Visual Studio instance (using vcpkg with mingw)

### ISSUE THREAD

**Issue by DPthang411** [microsoft/vcpkg#41117]
I am trying to install vcpkg with mingw then i got this bug:
error: in triplet x64-windows: Unable to find a valid Visual Studio instance 
Could not locate a complete Visual Studio instance
OS: Windows
```
Install vcpkg by bootstrap 
create new variable VCPKG_TARGET_TRIPLET=x64-mingw-dynamic
run vcpkg install glad
error appeared
```
I want the package glad to be installed but it didnt

**Comment by Osyotr** [comment]
You need to set `VCPKG_HOST_TRIPLET` too, because the default is `x64-windows` which uses VS toolchain.

**Comment by DPthang411** [comment]
it works now but i got another error which is cannot find glfw3-vcpkg.cmake(after i set cmake prefix path)

**Comment by Osyotr** [comment]
> after i set cmake prefix path

Wrong usage. You should never reference installed directory. The only thing you should set is `CMAKE_TOOLCHAIN_FILE`.
https://learn.microsoft.com/en-us/vcpkg/get_started/get-started?pivots=shell-cmd#4---build-and-run-the-project

**Comment by DPthang411** [comment]
ye but it wont find two glfw vcpkge files?

**Comment by Osyotr** [comment]
Have you tried?

**Comment by DPthang411** [comment]
you mean just set the CMAKE_TOOLCHAIN_FILE? if that the case then yes but failed

**Comment by Osyotr** [comment]
It's impossible to help without any logs whatsoever.

**Comment by LilyWangLL** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
