### ISSUE TITLE
[vcpkg-tool] Crash when adding version for a port if manifest needs formatting

### ISSUE THREAD

**Issue by Osyotr** [microsoft/vcpkg#41120]
1) Copy `test-crash-bad-formattings` to ports. The manifest in this port has CRLF line endings (which should not even trigger the warning IMHO).
2) Run `vcpkg x-add-version --all --overwrite-version`

```
error: test-crash-bad-formattings is not properly formatted
Run `vcpkg format-manifest "D:\vcpkg\ports\test-crash-bad-formattings\vcpkg.json"` to format the file
See https://learn.microsoft.com/vcpkg/commands/format-manifest?WT.mc_id=vcpkg_inproduct_cli for more information.Did you remember to commit your changes?
See https://learn.microsoft.com/vcpkg/commands/add-version?WT.mc_id=vcpkg_inproduct_cli for more information.
internal error: D:\a\_work\1\s\src\vcpkg\commands.add-version.cpp(425): vcpkg has crashed; no additional details are available.
```

Also notice missing newline in "information.Did".
Also IMHO these URLs look ugly and should respect "disable-metrics" option.

[test-crash-bad-formattings.zip](https://github.com/user-attachments/files/17090783/test-crash-bad-formattings.zip)

**Comment by BillyONeal** [comment]
In https://github.com/microsoft/vcpkg-tool/pull/1495 I fixed the missing newline but I can't repro the crash.

**Comment by BillyONeal** [comment]
Oh, wait, I missed `--all`/`--overwrite-version` derp
