### ISSUE TITLE
[glib] Build error cross-compiling x64-osx from arm64-osx host

### ISSUE THREAD

**Issue by jdpurcell** [microsoft/vcpkg#41121]
Running this command from an ARM64 host:
`vcpkg install glib --triplet=x64-osx`

Was working fine several months ago up until fde6eac0a7a864032f888796f4d2b459b2cc0c5a which seems may have introduced a regression causing an error similar to #26147 in the past. The error I'm seeing now is:

```
Installing 12/12 glib:x64-osx@2.78.4#3...
Building glib:x64-osx@2.78.4#3...
-- Found Python version '3.11.9 at /Users/runner/hostedtoolcache/Python/3.11.9/arm64/bin/python3'
-- Using meson: /Users/runner/work/kimageformats-binaries/kimageformats-binaries/vcpkg/downloads/tools/meson-1.5.1-81f7e3/meson.py
-- Downloading https://download.gnome.org/sources/glib/2.78/glib-2.78.4.tar.xz -> glib-2.78.4.tar.xz...
-- Extracting source /Users/runner/work/kimageformats-binaries/kimageformats-binaries/vcpkg/downloads/glib-2.78.4.tar.xz
-- Applying patch use-libiconv-on-windows.patch
-- Applying patch libintl.patch
-- Using source at /Users/runner/work/kimageformats-binaries/kimageformats-binaries/vcpkg/buildtrees/glib/src/glib-2-322e03f702.clean
-- Found external ninja('1.12.1').
-- Configuring x64-osx-dbg
-- Getting CMake variables for x64-osx
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
Error:     Command failed: /Users/runner/hostedtoolcache/Python/3.11.9/arm64/bin/python3 -I /Users/runner/work/kimageformats-binaries/kimageformats-binaries/vcpkg/downloads/tools/meson-1.5.1-81f7e3/meson.py setup -Dselinux=disabled -Dlibmount=disabled -Dgtk_doc=false -Dinstalled_tests=false -Dlibelf=disabled -Dman=false -Dtests=false -Dxattr=false --backend ninja --wrap-mode nodownload -Doptimization=plain --native /Users/runner/work/kimageformats-binaries/kimageformats-binaries/vcpkg/scripts/buildsystems/meson/none.txt --cross /Users/runner/work/kimageformats-binaries/kimageformats-binaries/vcpkg/buildtrees/glib/meson-x64-osx-dbg.log --libdir lib --pkgconfig.relocatable -Ddebug=true --prefix /Users/runner/work/kimageformats-binaries/kimageformats-binaries/vcpkg/packages/glib_x64-osx/debug --includedir ../include --pkg-config-path ['/Users/runner/work/kimageformats-binaries/kimageformats-binaries/vcpkg/installed/x64-osx/debug/lib/pkgconfig','/Users/runner/work/kimageformats-binaries/kimageformats-binaries/v
    Working Directory: /Users/runner/work/kimageformats-binaries/kimageformats-binaries/vcpkg/buildtrees/glib/x64-osx-dbg
    Error code: 1
    See logs for more information:
      /Users/runner/work/kimageformats-binaries/kimageformats-binaries/vcpkg/buildtrees/glib/config-x64-osx-dbg-meson-log.txt.log
      /Users/runner/work/kimageformats-binaries/kimageformats-binaries/vcpkg/buildtrees/glib/config-x64-osx-dbg-out.log
Call Stack (most recent call first):
  installed/arm64-osx/share/vcpkg-tool-meson/vcpkg_configure_meson.cmake:467 (vcpkg_execute_required_process)
  ports/glib/portfile.cmake:42 (vcpkg_configure_meson)
  scripts/ports.cmake:192 (include)
```

And the bottom of the config-x64-osx-dbg-out.log file has the following additional details:
```
../src/glib-2-322e03f702.clean/meson.build:904:2: ERROR: 'objc' compiler binary not defined in cross file [binaries] section
```

**Comment by dg0yt** [comment]
Can you share the contents of `/Users/runner/work/kimageformats-binaries/kimageformats-binaries/vcpkg/buildtrees/glib/meson-x64-osx-dbg.log`?

Port and maintainer scripts have everything prepared for OBJC on osx. Cross-builds shouldn't be different.

**Comment by jdpurcell** [comment]
And in case it helps, here it is as an attachment, along with the one from the last known working commit (f6267570d89952a13805713073f2d72796c7e791):
[fde6eac_meson-x64-osx-dbg.log](https://github.com/user-attachments/files/17098830/fde6eac_meson-x64-osx-dbg.log)
[f626757_meson-x64-osx-dbg.log](https://github.com/user-attachments/files/17098833/f626757_meson-x64-osx-dbg.log)

I pulled the logs from these Actions runs which upload the whole `vcpkg/buildtrees/glib` dir as the artifact for troubleshooting purposes:
With fde6eac0a7a864032f888796f4d2b459b2cc0c5a: https://github.com/jdpurcell/kimageformats-binaries/actions/runs/10995796811
With f6267570d89952a13805713073f2d72796c7e791: https://github.com/jdpurcell/kimageformats-binaries/actions/runs/10995713861

**Comment by dg0yt** [comment]
Thanks for those files.

I see that https://github.com/microsoft/vcpkg/commit/fde6eac0a7a864032f888796f4d2b459b2cc0c5a included the switch to `vcpkg-cmake-get-vars`. That's probably how we lost some objc properties. And native builds seem to find the binary nevertheless.
