### ISSUE TITLE
Building package libpng:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by VioletGiraffe** [Microsoft/vcpkg#4112]
```
Error: Building package libpng:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libpng:x64-windows
  Vcpkg version: 0.0.113-nohash
```

```
>vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
```
```
>git pull
Already up to date.
```
What's wrong? Is the problem on my end or on `vcpkg`'s?

**Comment by IronicallySerious** [comment]
IIRC vcpkg also provides some build log files on coming across errors like this. When I had the same error, I found that I was missing some system components used to build C++ programs. vcpkg wasn't showing these on the terminal output.

**Comment by VioletGiraffe** [comment]
I've deleted my vcpkg folder, re-downloaded and rebuilt vcpkg, and now this problem is gone. Odd, because I did to `git pull` and `bootsrap` successfully and the error still occurred.
