### ISSUE TITLE
[boost-build] Build error

### ISSUE THREAD

**Issue by Damian434** [microsoft/vcpkg#41137]
Hey, I'm trying to install dependencies found below this link: https://github.com/OTCv8/otcv8-dev

it results in: Error: Building package boost-build:x64-windows failed with: BUILD_FAILED  

I tried .\vcpkg update

package: boost-build[core]:x64-windows -> 1.78.0#1                                                                       
vcpkg-tool version: 2022-03-09-1affd32f93b299d5a907816c328ca3ededb73a7e                                                 
vcpkg-scripts version: unknown

**Comment by MonicaLiu0311** [comment]
The current version of boost-build in vcpkg is: [1.85.0#2](https://github.com/microsoft/vcpkg/blob/master/ports/boost-build/vcpkg.json).

Please update to the latest version of vcpkg:
```
git pull https://github.com/microsoft/vcpkg.git master
./vcpkg remove boost-build --recurse
./vcpkg install boost-build
```

**Comment by Osyotr** [comment]
> vcpkg-tool version: 2022-03-09-1affd32f93b299d5a907816c328ca3ededb73a7e

Don't forget to run `./bootstrap-vcpkg.sh`

**Comment by MonicaLiu0311** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
