### ISSUE TITLE
[New Port Request] sml

### ISSUE THREAD

**Issue by qljsky** [microsoft/vcpkg#41132]
### Library name

boost-ext sml

### Library description

scalable C++14 one header only State Machine Library with no dependencies

### Source repository URL

https://github.com/boost-ext/sml

**Comment by motazmuhammad** [comment]
Should not this be closed as it is already there via vcpkg install bext-sml?

**Comment by qljsky** [comment]
> Should not this be closed as it is already there via vcpkg install bext-sml?

yes,i found it,thanks
