### ISSUE TITLE
CGAL auto-linking broken on *-windows-static

### ISSUE THREAD

**Issue by diogocp** [microsoft/vcpkg#4113]
CGAL uses [auto-linking](https://github.com/CGAL/cgal/blob/releases/CGAL-4.12/Installation/include/CGAL/auto_link/auto_link.h). When using a `*-windows-static` triplet, the library renaming that vcpkg does leads to a linker error, since it cannot find a library with the `-s` static runtime suffix.

A workaround is to include `add_definitions(-DCGAL_NO_AUTOLINK)` in your `CMakeLists.txt`.

**Comment by wangli28** [comment]
Thanks for posting this issue. This issue has been fixed in PR #4975. So I am closing this issue for now.
