### ISSUE TITLE
arm64 build in manifest mode fails to build

### ISSUE THREAD

**Issue by AenBleidd** [microsoft/vcpkg#41143]
**Describe the bug**
I have a nightly build with the latest vcpkg master.
Tonight it failed with a very strange error:
```
error: expected the end of input parsing a package spec; this usually means the indicated character is not allowed to be in a package spec. Port, triplet, and feature names are all lowercase alphanumeric+hypens.
```
I suspect the reason of it is the commit f176b58f35a75f9f8f54099cd9df97d2e2793a2e

My manifest file (still builds successfully on x64):
```
{
    "name": "boinc-libs",
    "dependencies":
    [
        {
          "name": "curl",
          "features": ["schannel"],
          "default-features": false
        },
        {
          "name": "openssl",
          "features": ["ssl3", "weak-ssl-ciphers"],
          "default-features": false
        }
    ]
}
```

**Environment**
- OS: Windows
- Compiler: Visual Studio 2022 ARM64

Build log: https://github.com/BOINC/boinc/actions/runs/11004558699/job/30561485353

@BillyONeal

**Comment by AenBleidd** [comment]
Update: Looks like this is the reason https://github.com/microsoft/vcpkg-tool/pull/1474
But I haven't figured out yet what's wrong with my configuration because previously everything was working fine

**Comment by AenBleidd** [comment]
my triplet name is `arm64-windows-static`

**Comment by AenBleidd** [comment]
ok, I have figured it out: the triplet should be `arm64-windows-static` not `ARM64-windows-static`.
Issue closed.

**Comment by dg0yt** [comment]
IMO this issue should be resolved after a check whether the invalid user input creates a *sufficient*  diagnostic message.

**Comment by AenBleidd** [comment]
@dg0yt, you are correct, however that's a different story: my original issue was because of the failed build, but this was just with my wrong triplet naming that was `ok` before but `not ok` now, that just uncovered a hidden issue (not so critical, but still).
Message is misleading but that's not an issue but rather something that need to be improved.
