### ISSUE TITLE
[New Port Request] PDF-Writer

### ISSUE THREAD

**Issue by Binary-System** [microsoft/vcpkg#41168]
### Library name

PDF-Writer

### Library description

A pdf toolkit

### Source repository URL

https://github.com/galkahana/PDF-Writer

**Comment by flamberge552** [comment]
Could this be reconsidered? My main reasoning would be that opposed to existing port for [libharu](https://github.com/libharu/libharu) this library supports storing PNG data from memory, while libharu only supports reading the image from disk.
