### ISSUE TITLE
Failed to install `thrift`

### ISSUE THREAD

**Issue by kreuzerkrieg** [Microsoft/vcpkg#4119]
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:214 (message):
  Could not find win_flex.  Please install it via your package manager.
Call Stack (most recent call first):
  ports/thrift/portfile.cmake:12 (vcpkg_find_acquire_program)
  scripts/ports.cmake:71 (include)

Error: Building package thrift:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: thrift:x64-linux
  Vcpkg version: 0.0.113-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by Voskrese** [comment]
**Could not find win_flex. Please install it via your package manager.**

log files ?

**Comment by kreuzerkrieg** [comment]
>> port so far only for windows
where did you get it from?

why the vcpkg makes attempt to install it if it is for Windows only?

**Comment by Voskrese** [comment]
no one canceled the dependence

**Comment by markaren** [comment]
There is an easy fix for this, I can make a pull request tomorrow. See #4042
