### ISSUE TITLE
[msh3] update to 0.7.0

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#41200]
### Library name

msh3

### New version number

0.7.0

### Other information that may be useful (release notes, etc...)

it needed to change also msquick:
https://github.com/microsoft/msquic/blob/v2.3.5/src/inc/quic_platform.h#L574
That needed c++ define:
https://github.com/microsoft/msquic/blob/v2.3.5/src/inc/quic_platform.h#L498

Not sure how to do that.

When I tried to update:
```
msh3.cpp.obj : error LNK2001: unresolved external symbol CxPlatGetSelfSignedCert
msh3.cpp.obj : error LNK2001: unresolved external symbol CxPlatFreeSelfSignedCert
bin\msh3.dll : fatal error LNK1120: 2 unresolved externals

ninja: build stopped: subcommand failed.
```

I am not sure how to compile these symbol. I know they are depends on define cpp: QUIC_TEST_APIS
https://github.com/microsoft/msquic/blob/v2.3.5/src/inc/quic_platform.h#L498

I tried to add it via port config with `VCPKG_CXX_FLAGS` with both define in msquic and msh3, but without success.

**Comment by talregev** [comment]
I create issue on upstream of msquic:
https://github.com/microsoft/msquic/issues/4569

I also suggested some solution:
https://github.com/microsoft/msquic/pull/4574

Let's see what happen.

**Comment by MonicaLiu0311** [comment]
Fixing by https://github.com/microsoft/vcpkg/pull/42788.
