### ISSUE TITLE
[Multiwfn for MacOS] build failure

### ISSUE THREAD

**Issue by sorahiro** [microsoft/vcpkg#41210]
### Operating system

Mac OS, Apple chip

### Steps to reproduce the behavior

```Shell
conda install gcc
conda install cmake
conda install openblas
conda install flint
conda install gfortran
conda install arb
git clone --branch source_dist https://github.com/digital-chemistry-laboratory/multiwfn-mac-build.git
cd multiwfn-mac-build
cmake -B build
```

### Failure logs

cmake -B build
-- The Fortran compiler identification is GNU 11.3.0
arm64-apple-darwin20.0.0-gfortran: warning: could not understand version ‘14.00.00’
-- Checking whether Fortran compiler has -isysroot
-- Checking whether Fortran compiler has -isysroot - yes
-- Checking whether Fortran compiler supports OSX deployment target flag
-- Checking whether Fortran compiler supports OSX deployment target flag - yes
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - failed
-- Check for working Fortran compiler: /opt/anaconda3/bin/arm64-apple-darwin20.0.0-gfortran
-- Check for working Fortran compiler: /opt/anaconda3/bin/arm64-apple-darwin20.0.0-gfortran - broken
CMake Error at /opt/anaconda3/share/cmake-3.26/Modules/CMakeTestFortranCompiler.cmake:59 (message):
  The Fortran compiler

    "/opt/anaconda3/bin/arm64-apple-darwin20.0.0-gfortran"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/m/multiwfn-mac-build/build/CMakeFiles/CMakeScratch/TryCompile-maCfQ9
    
    Run Build Command(s):/opt/anaconda3/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_0766b/fast && /Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/cmTC_0766b.dir/build.make CMakeFiles/cmTC_0766b.dir/build
    Building Fortran object CMakeFiles/cmTC_0766b.dir/testFortranCompiler.f.o
    /opt/anaconda3/bin/arm64-apple-darwin20.0.0-gfortran   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk -mmacosx-version-min=14.3 -c /Users/m/multiwfn-mac-build/build/CMakeFiles/CMakeScratch/TryCompile-maCfQ9/testFortranCompiler.f -o CMakeFiles/cmTC_0766b.dir/testFortranCompiler.f.o
    arm64-apple-darwin20.0.0-gfortran: warning: ‘14.3’ is not valid for ‘-mmacosx-version-min’
    Linking Fortran executable cmTC_0766b
    /opt/anaconda3/bin/cmake -E cmake_link_script CMakeFiles/cmTC_0766b.dir/link.txt --verbose=1
    /opt/anaconda3/bin/arm64-apple-darwin20.0.0-gfortran  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk -mmacosx-version-min=14.3 CMakeFiles/cmTC_0766b.dir/testFortranCompiler.f.o -o cmTC_0766b 
    arm64-apple-darwin20.0.0-gfortran: warning: ‘14.3’ is not valid for ‘-mmacosx-version-min’
    ld: -rpath can only be used when targeting Mac OS X 10.5 or later
    collect2: error: ld returned 1 exit status
    make[1]: *** [cmTC_0766b] Error 1
    make: *** [cmTC_0766b/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

**Comment by dg0yt** [comment]
Conda is not here.

**Comment by sorahiro** [comment]
How to deal with this question? Could you do me a favor?

---- Replied Message ----
| From | Kai ***@***.***> |
| Date | 09/27/2024 11:56 |
| To | microsoft/vcpkg ***@***.***> |
| Cc | sorahiro ***@***.***>,
Author ***@***.***> |
| Subject | Re: [microsoft/vcpkg] [Multiwfn for MacOS] build failure (Issue #41210) |

Conda is not here.

**Comment by dg0yt** [comment]
The issue doesn't show any connection to vcpgk.
You install from conda.
You clone https://github.com/digital-chemistry-laboratory/multiwfn-mac-build.git.
I suggest reporting your issue there.

**Comment by WangWeiLin-MV** [comment]
Unrelated issue.
