### ISSUE TITLE
[NEWS] LLVM ver 8.0 toolchain from Visual Studio 2017

### ISSUE THREAD

**Issue by Voskrese** [Microsoft/vcpkg#4123]
Actually came into the light Clang 8.0 with official support MSVC 2017
https://llvm.org/builds/
Visual Studio extension (supports Visual Studio 2017 and later)
https://marketplace.visualstudio.com/items?itemName=LLVMExtensions.llvm-toolchain

`/p:PlatformToolset=llvm`

Visual Studio plugin ClangFormat
http://prereleases.llvm.org/win-snapshots/ClangFormat-r339319.vsix

**Comment by Voskrese** [comment]
в MSVC busybox появился и еще много утилит от gnu, идет полнаяя интеграция со всеми OS
так что не останавливаемся на вынь

**Comment by degski** [comment]
@Voskrese Please refrain from writing in Russian, if you have something to say, great, but I think you should take the trouble of putting that through google translate instead of everybody else having to do that individually.

**Comment by degski** [comment]
@Voskrese The translation from google:

> in MSVC busybox appeared and many more utilities from gnu, there is a complete integration with all OS so do not stop at the piss

I will not stop to piss, what do you mean?

**Comment by degski** [comment]
> In the latest versions of 2017 added a lot of GNU utilities, all I wanted to write

Which ones are you talking about?

> Yes, machine translation sometimes brings;)

Yes, it's entertaining sometimes, that's why it's better you do the translating, you could have at least an inkling about minor (piss-) issues, popping up.

**Comment by Voskrese** [comment]
@degski 
I wrote it was a translation error.

Do you have any complaints about that attack?

**Comment by degski** [comment]
@Voskrese I know it was a translation error, don't worry!

> Do you have any complaints about that attack?

The word `attack` translates from English to Russian like `атака`, which I guess is correct. So the machine translation keeps entertaining us (I presume you don't want to attack me). What I was asking, which GNU utilities are you talking about?

**Comment by Voskrese** [comment]
> нападки = придирки
> Attacking = nagging

;)))

I think the discussion is over.

**Comment by degski** [comment]
> What I was asking, which GNU utilities are you talking about?

The discussion is over, but what were you intending to say?
