### ISSUE TITLE
Android [TRIPLET\toolchain]

### ISSUE THREAD

**Issue by Voskrese** [Microsoft/vcpkg#4124]
The question arose on the Assembly of native libraries under arm64\android
Actually the question is, how do you configure it correctly? One NDK not enough, need Gradle, JDK, MAVEN, ANT, CMake (google)
https://github.com/Microsoft/vcpkg/blob/master/scripts/toolchains/android.cmake

Windows Build

As I think it is necessary to use ANDROID_SDK and underneath it to install the necessary utilities

AndroidSDK\cmake\3.6.4111459\bin>`cmake --help`
```

...
  Watcom WMake                 = Generates Watcom WMake makefiles.
  Android Gradle - Ninja       = Generates Android Gradle build files.
  Android Gradle - Unix Makefiles
...

```

`-G"Android Gradle - Ninja"`

**Comment by Voskrese** [comment]
vcpkg\triplets

`cp x64-linux.cmake x64-android.cmake`
edit `nano /opt/vcpkg/triplets/x64-linux.cmake`
`set(VCPKG_CMAKE_SYSTEM_NAME Linux)` -->> `set(VCPKG_CMAKE_SYSTEM_NAME Android)
`

NDK Android = /opt/android-sdk/ndk-bundle
`export ANDROID_NDK_HOME=/opt/android-sdk/ndk-bundle`

clang not support?
When using Clang constant error that can not find a folder and it does not depend on the choice of architecture, so change to GCC

```
...
clang: error: no such file or directory: 'armv7-none-linux-androideabi'
clang: warning: /opt/android-sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64: 'linker' input $<builtin>: recipe for target 
...
```

edit `nano /opt/vcpkg/scripts/toolchains/android.cmake`

`set(ANDROID_ABI arm64-v8a CACHE STRING "")` -->> x86_64, mips64, armeabi-v7a, arm64-v8a, ...
`set(ANDROID_TOOLCHAIN clang CACHE STRING "")` -->> clang or gcc
`set(ANDROID_NATIVE_API_LEVEL 21 CACHE STRING "")` -->> ... , 21, 24, 28 ... , 24-25=ver 7.0-7.1.0
`set(CMAKE_ANDROID_NDK_TOOLCHAIN_VERSION clang CACHE STRING "")` -->> clang or gcc

Do I have to clean up this line when using GCC or does it hurt?
`set(ANDROID_CPP_FEATURES "rtti exceptions" CACHE STRING "")`

**Comment by Voskrese** [comment]
`./vcpkg install openssl[*]:x64-android`

build ok

![2018-08-22_183834](https://user-images.githubusercontent.com/10104740/44459170-2d69f480-a63b-11e8-8133-f9b7d1db03c0.png)

**Comment by Voskrese** [comment]
NDK Android ver 18 альфа

`clang.exe --version`

> Android (4751641 based on r328903) **clang version 7.0.2**  (based on **LLVM 7.0.2**svn)
> Target: x86_64-w64-windows-gnu
> Thread model: posix

`ls`
```
clang++.exe          ld.lld.exe           llvm-dis.exe         llvm-profdata.exe    sanstats.exe
clang-format.exe     libwinpthread-1.dll  llvm-link.exe        llvm-readobj.exe
clang-tidy.exe       llvm-ar.exe          llvm-modextract.exe  llvm-strip.exe
clang.exe            llvm-as.exe          llvm-nm.exe          llvm-symbolizer.exe
git-clang-format     llvm-cov.exe         llvm-objcopy.exe     sancov.exe
```

**Comment by Voskrese** [comment]
вроде как разобрался, работает, кому надо будет поиском найдет
закрою

**Comment by LinArcX** [comment]
@Voskrese Hi. i try to add android triplet. but there is no path: `/opt/android-sdk/ndk-bundle` in my system.
Os: Arch Linux
Tip: I install android-skd, android-ndk from arch repos.

**Comment by Voskrese** [comment]
```
NDK Android = /opt/android-ndk
export ANDROID_NDK_HOME=/opt/android-ndk
export ANDROID_NDK=/opt/android-ndk
```

or 

`ln -S /opt/android-ndk /opt/android-sdk/ndk-bundle` ...

I write from memory, so I can not guarantee accuracy

**Comment by LinArcX** [comment]
@Voskrese  Yes, thank you.
