### ISSUE TITLE
[raylib] LNK4044 warning because of GCC flags in .vcxproj

### ISSUE THREAD

**Issue by ImmaturityRules** [microsoft/vcpkg#41257]
Building a project using raylib with CMake and MSVC gives an LNK4044 warning:

[build] LINK : warning LNK4044: unrecognized option '/LC:/vcpkg/installed/x64-windows/debug/lib -lraylib'; ignored [D:\VSCode\C\gametest\build\gametest.vcxproj]

These are GCC flags and shouldn't make it into the .vcxproj file.

My CMakeLists.txt contains:

find_package(raylib CONFIG REQUIRED)
target_link_libraries(main PRIVATE raylib)

as vcpkg specifies when raylib is installed. There is no relevant source code because I just compiled a hello world program as a sanity check. I added libpng in the same way, which didn't generate the linker warning.

**Comment by jimwang118** [comment]
Sorry, i cannot reproduce this issue locally. Can you provide a simple test project?

**Comment by ImmaturityRules** [comment]
https://github.com/ImmaturityRules/test

All I did was build this with cmake using the vcpkg toolchain file.
