### ISSUE TITLE
 openssl:x64-windows-static-md BUILD_FAILED

### ISSUE THREAD

**Issue by zll1921** [microsoft/vcpkg#41262]
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/nmake.exe" /NOLOGO /G /U /F makefile install_dev install_modules INSTALL_PDBS=OFF
    Working Directory: F:/vcpkg/buildtrees/openssl/x64-windows-static-md-dbg
    See logs for more information:
      F:\vcpkg\buildtrees\openssl\install-x64-windows-static-md-dbg-nmake-out.log
      F:\vcpkg\buildtrees\openssl\install-x64-windows-static-md-dbg-nmake-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_nmake.cmake:156 (vcpkg_execute_build_process)
  buildtrees/versioning_/versions/openssl/71beae5ba81d9198d1ca12024325630b6ad81446/windows/portfile.cmake:69 (vcpkg_build_nmake)
  buildtrees/versioning_/versions/openssl/71beae5ba81d9198d1ca12024325630b6ad81446/portfile.cmake:30 (include)
  scripts/ports.cmake:192 (include)

 F:\vcpkg\buildtrees\openssl\install-x64-windows-static-md-dbg-nmake-err.log 
Key content in the document：

crypto\aes\bsaes-x86_64.asm:1608: error: label `ossl_bsaes_ctr32_encrypt_blocks' inconsistently redefined
crypto\aes\bsaes-x86_64.asm:1370: info: label `ossl_bsaes_ctr32_encrypt_blocks' originally defined here
crypto\aes\bsaes-x86_64.asm:1608: error: parser: instruction expected
crypto\aes\bsaes-x86_64.asm:1609: error: label `PUBLIC' inconsistently redefined
crypto\aes\bsaes-x86_64.asm:1367: info: label `PUBLIC' originally defined here
crypto\aes\bsaes-x86_64.asm:1638: warning: `PTR' is not a NASM keyword [-w+ptr]

crypto\aes\bsaes-x86_64.asm:2816: error: parser: instruction expected
crypto\aes\bsaes-x86_64.asm:2823: error: parser: instruction expected
crypto\aes\bsaes-x86_64.asm:2824: warning: label alone on a line without a colon might be in error [-w+label-orphan]
NMAKE : fatal error U1077: “"F:\vcpkg\downloads\tools\nasm\nasm-2.16.01\nasm.exe"  -Ox -f win64 -DNEAR -g -o crypto\aes\libcrypto-lib-bsaes-x86_64.obj "crypto\aes\bsaes-x86_64.asm"”: 返回代码“0x1”
Stop.
NMAKE : fatal error U1077: “"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64\nmake.exe" /LU                 _build_libs”: 返回代码“0x2”
Stop.

**Comment by greenozon** [comment]
can't reproudce, just tried, 100% success

git pull
bootstrap-vcpkg.bat

<details><summary>Details</summary>
<p>

c:\Dev\vcpkg>vcpkg install openssl:x64-windows-static-md
Computing installation plan...
The following packages will be built and installed:
    openssl:x64-windows-static-md@3.3.2#1
Detecting compiler hash for triplet x64-windows-static-md...
Compiler found: C:/Dev/VS2019/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from C:\Users\user\AppData\Local\vcpkg\archives in 320 us. Use --debug to see more details.
Installing 1/1 openssl:x64-windows-static-md@3.3.2#1...
Building openssl:x64-windows-static-md@3.3.2#1...
C:\Dev\vcpkg\triplets\community\x64-windows-static-md.cmake: info: loaded community triplet from here. Community triplets are not built in the curated registry and are thus less likely to succeed.
-- Using cached openssl-openssl-210dc9a50dfd99caa1cf7c3d2fa42850124b1bbc.patch.
-- Using cached openssl-openssl-openssl-3.3.2.tar.gz.
-- Cleaning sources at C:/Dev/vcpkg/buildtrees/openssl/src/nssl-3.3.2-515f0a0017.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Dev/vcpkg/downloads/openssl-openssl-openssl-3.3.2.tar.gz
-- Applying patch cmake-config.patch
-- Applying patch command-line-length.patch
-- Applying patch script-prefix.patch
-- Applying patch asm-armcap.patch
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch unix/android-cc.patch
-- Applying patch unix/move-openssldir.patch
-- Applying patch unix/no-empty-dirs.patch
-- Applying patch unix/no-static-libs-for-shared.patch
-- Applying patch C:/Dev/vcpkg/downloads/openssl-openssl-210dc9a50dfd99caa1cf7c3d2fa42850124b1bbc.patch
-- Using source at C:/Dev/vcpkg/buildtrees/openssl/src/nssl-3.3.2-515f0a0017.clean
-- Downloading https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/download/SP_54001_64bit_UCRT/strawberry-perl-5.40.0.1-64bit-portable.zip -> strawberry-perl-5.40.0.1-64bit-portable.zip
.
-- Getting CMake variables for x64-windows-static-md
-- Getting CMake variables for x64-windows-static-md
-- Prerunning x64-windows-static-md-dbg
-- Building x64-windows-static-md-dbg
-- Prerunning x64-windows-static-md-rel
-- Building x64-windows-static-md-rel
-- Fixing pkgconfig file: C:/Dev/vcpkg/packages/openssl_x64-windows-static-md/lib/pkgconfig/libcrypto.pc
-- Fixing pkgconfig file: C:/Dev/vcpkg/packages/openssl_x64-windows-static-md/lib/pkgconfig/libssl.pc
-- Fixing pkgconfig file: C:/Dev/vcpkg/packages/openssl_x64-windows-static-md/lib/pkgconfig/openssl.pc
-- Using cached msys2-mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.5.3-3-x86_64.pkg.tar.zst.
-- Using msys root at C:/Dev/vcpkg/downloads/tools/msys2/1e74ca60daa10104
-- Fixing pkgconfig file: C:/Dev/vcpkg/packages/openssl_x64-windows-static-md/debug/lib/pkgconfig/libcrypto.pc
-- Fixing pkgconfig file: C:/Dev/vcpkg/packages/openssl_x64-windows-static-md/debug/lib/pkgconfig/libssl.pc
-- Fixing pkgconfig file: C:/Dev/vcpkg/packages/openssl_x64-windows-static-md/debug/lib/pkgconfig/openssl.pc
-- Installing: C:/Dev/vcpkg/packages/openssl_x64-windows-static-md/share/openssl/usage
-- Installing: C:/Dev/vcpkg/packages/openssl_x64-windows-static-md/share/openssl/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 6.8 s.
Elapsed time to handle openssl:x64-windows-static-md: 5.8 min
openssl:x64-windows-static-md package ABI: 269419d5db2b3cec99cf1c3f73b9112f52721a065afe735873dec2a1abff53f5
Total install time: 5.8 min
openssl is compatible with built-in CMake targets:

  find_package(OpenSSL REQUIRED)
  target_link_libraries(main PRIVATE OpenSSL::SSL)
  target_link_libraries(main PRIVATE OpenSSL::Crypto)


</p>
</details>

**Comment by greenozon** [comment]
Please also try to use English Language Pack, eg:  https://github.com/microsoft/vcpkg/issues/40377#issuecomment-2283490304
