### ISSUE TITLE
VS2022 + vcpkg + CMake: FLTK not working as sole dependency

### ISSUE THREAD

**Issue by Pique7** [microsoft/vcpkg#41288]
**Describe the bug**
I use **Visual Studio Community 2022** including **vcpkg** and  **CMake** (both installed with Visual Studio Installer). 
I have created a new CMake project with default configuration made by Visual Studio, and I use the integrated vcpkg to install the dependencies.
If I only add "fltk" with vcpkg/CMake and there is no other dependency, I get a build error concerning header files. If I then add any other arbitrary dependency (e.g. "fmt") and also add `target_link_libraries()` for this other dependency, then it works. When I remove `target_link_libraries()` for the other dependency (e.g. "fmt"), then the error occurs again.

I have only very little experience with CMake and vcpkg, so maybe I missed something obvious. This only happens with FLTK, not with other dependencies. I don't know whether this is a misbehaviour of FLTK, of CMake or of vcpkg (if this is a bug at all).

**Environment**
- OS: Windows 11
- Compiler: MSVC v1941.34120
- vcpkg version: 2024-06-10
- FLTK version: 1.3.9

**To Reproduce**
1. Install Visual Studio Community 2022 including CMake Build Tools and vcpkg.
2. Create a new CMake Project with default settings.
3. Add this to"cacheVariables" in "CMakePresets.json"
```
    "CMAKE_TOOLCHAIN_FILE": "$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
```
4. In the VS console type:
```
    ...\CMakeProject1> vcpkg new --application
    ...\CMakeProject1> vcpkg add port fltk
    ...\CMakeProject1> vcpkg install
    ...\CMakeProject1> vcpkg integrate install
```
5. Add this to CMakeLists.txt:
```
    find_package(fltk REQUIRED) 
    target_link_libraries(CMakeProject1 PRIVATE ${FLTK_LIBRARIES})
```
6. Add this to CMakeProject1.cpp:
```
#include <FL/Fl.H>
```
8. Delete CMake cache and reconfigure.
9. Build project.

**Expected behavior**
The FLTK header files should actually be accessible now.

**Failure logs**
Visual Studio error message: 
[C1083] Cannot open include file 'FL/Fl.H': No such file or directory

**Additional context**
This happens with x86 and x64 configuration. I haven't yet tried to install vcpkg independently from Visual Studio.

**Comment by Osyotr** [comment]
> target_link_libraries(CMakeProject1 PRIVATE ${FLTK_LIBRARIES})

You should probably link to the exported target instead of this.

**Comment by Pique7** [comment]
> > target_link_libraries(CMakeProject1 PRIVATE ${FLTK_LIBRARIES})
> 
> You should probably link to the exported target instead of this.

Thanks for your reply, but I don't understand what I should change. I have only little knowledge of CMake. 
My configuration works when I add another dependency the same way (e.g. "fmt" or any other).
Can you provide instructions or an example?

**Comment by Osyotr** [comment]
Vcpkg usually prints usage information after you can `vcpkg install`.
In your case you should replace `${FLTK_LIBRARIES}` with `fltk::fltk`.

**Comment by Pique7** [comment]
> Vcpkg usually prints usage information after you can `vcpkg install`. In your case you should replace `${FLTK_LIBRARIES}` with `fltk::fltk`.

Vcpkg suggests me to use `target_link_libraries(${PROJECT_NAME} PRIVATE fltk fltk_gl fltk_forms fltk_images)` but this doesn't work either (error "fltk.lib not found"). 
Btw., CMake shows a warning everytime (also in working configurations):
```
The package name passed to `find_package_handle_standard_args` (FLTK) does not match the name of the calling package (fltk). This can lead to problems in calling code that expects `find_package` result variables (e.g., `_FOUND`) to follow a certain pattern.
```


The FLTK readme file gives following example for using FLTK with CMake:
```
cmake_minimum_required(VERSION 3.15)

project(hello)

set(FLTK_DIR "/path/to/fltk"
    CACHE FILEPATH "FLTK installation or build directory")

find_package(FLTK REQUIRED CONFIG)

add_executable(hello WIN32 MACOSX_BUNDLE hello.cxx)
if (APPLE)
  target_link_libraries (hello PRIVATE "-framework cocoa")
endif (APPLE)

target_include_directories (hello PRIVATE ${FLTK_INCLUDE_DIRS})

target_link_libraries (hello PRIVATE fltk)
```
I have also tried to set "FLTK_DIR / fltk_DIR", but I don't know which directory to specify exactly here.

**Comment by Pique7** [comment]
It seems to work with following entries in `CMakeLists.txt`:
```
...
include_directories("vcpkg_installed/x64-windows/include")
find_package(fltk REQUIRED)
target_link_libraries(${PROJECT_NAME} PRIVATE ${FLTK_LIBRARIES})
```
But actually I don't want to use this solution because now it only works with x64-windows.

**Comment by dg0yt** [comment]
There are different CMake patterns, and they don't mix well. Pay attention to case - Windows filesystem may blur borders where CMake is case-sensitive.

Old CMake: Find modules, variables:
~~~cmake
find_package(FLTK REQUIRED)                                    # by https://cmake.org/cmake/help/latest/module/FindFLTK.html
target_include_directories(hello PRIVATE ${FLTK_INCLUDE_DIR})  # fixes your original compile error
target_link_libraries(hello PRIVATE ${FLTK_LIBRARIES})         # just names of libs for the linker.
~~~

Modern CMake: Config packages, imported targets:
~~~cmake
find_package(FLTK CONFIG REQUIRED)              # installed by fltk
target_link_libraries(main PRIVATE fltk::fltk)  # Imported target 'fltk::fltk', carrying "properties"
~~~

**Comment by Pique7** [comment]
Sorry, it's not a bug in vcpkg but my mistake. This CMake configuration works (both with vcpkg classic and manifest mode):
```
find_package(fltk CONFIG REQUIRED)
target_include_directories (${PROJECT_NAME} PRIVATE ${FLTK_INCLUDE_DIRS})
target_link_libraries(${PROJECT_NAME} PRIVATE fltk)
```

**Comment by dg0yt** [comment]
> Sorry, it's not a bug in vcpkg but my mistake. This CMake configuration works (both with vcpkg classic and manifest mode):
> 
> ```
> find_package(fltk CONFIG REQUIRED)
> target_include_directories (${PROJECT_NAME} PRIVATE ${FLTK_INCLUDE_DIRS})
> target_link_libraries(${PROJECT_NAME} PRIVATE fltk)
> ```

The `target_include_directories` line is redundant. With `fltk CONFIG`, `fltk` becomes an imported target and carries usage requirements.

I did intentionally suggest to use the prefixed name `fltk::fltk` target name because it enables certain early CMake diagnostics at generation time. Names without `::` can be passed to the linker, causing late errors at link time, or selecting a release lib instead a debug lib with debug lib. 

> > don't mix

You have been warned.

**Comment by Pique7** [comment]
> The `target_include_directories` line is redundant. With `fltk CONFIG`, `fltk` is an imported target and carries usage requirements.

Yes, that's correct. I thought I have tried this before without success but now I can confirm that it also works without `target_include_directories`.

> I did intentionally suggest to use the prefixed name `fltk::fltk` target name because it enables certain early CMake diagnostics at generation time. Names without `::` can be passed to the linker, causing late errors at link time, or selecting a release lib instead a debug lib with `d` suffix.

I've tried `fltk::fltk` several times but I always get an error like this:
```
CMake Error at ... (target_link_libraries):
  Target "CMakeProject1" links to:
    fltk::fltk
  but the target was not found.
...
```
Does this work with FLTK v1.3.9 or do I need a FLTK version >= 1.4 ?

**Comment by dg0yt** [comment]
> I've tried `fltk::fltk` several times but I always get an error

Thanks for the feedback. I realize that there is an unsuitable vcpkg patch to the main fltk cmake config file. When I looked at the installed files, it gave the impression that `fltk::fltk` would exist. But this is wrong for 1.3.9. vcpkg maintainers :facepalm: 

So use `fltk`, or for a similar diagnostic benefit, `$<TARGET_NAME:fltk>`.
