### ISSUE TITLE
Update Armadillo

### ISSUE THREAD

**Issue by rjzak** [microsoft/vcpkg#41319]
### Library name

Armadillo

### New version number

14.0.2

### Other information that may be useful (release notes, etc...)

https://arma.sourceforge.net/download.html

**Comment by rjzak** [comment]
Armadillo has had a minor release, it's now at 14.0.3. https://sourceforge.net/projects/arma/files/armadillo-14.0.3.tar.xz

**Comment by rcurtin** [comment]
Hey there @WangWeiLin-MV, just want to check on the status of this.  Thanks!

**Comment by rjzak** [comment]
Nudge. Any update?
