### ISSUE TITLE
[libmaxminddb] non-existent path in INTERFACE_INCLUDE_DIRECTORIES

### ISSUE THREAD

**Issue by maksis** [microsoft/vcpkg#41315]
### Operating system

Windows 11

### Compiler

MSVC

### Steps to reproduce the behavior

Clone the minimal repro repository from https://github.com/maksis/vcpkg-maxminddb and run `cmake -B build -S .`

### Failure logs

```
CMake Error in CMakeLists.txt:
  Imported target "maxminddb::maxminddb" includes non-existent path

    "C:/Projects/test/build/vcpkg_installed/x64-windows/generated"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

### Additional context

It will work after creating the `generated` directory manually

**Comment by dg0yt** [comment]
Seems to have a fix in https://github.com/maxmind/libmaxminddb/pull/354, but nobody updated the vcpkg port.

**Comment by jimwang118** [comment]
@maksis This issue has been fixed, please update vcpkg and recompile.
