### ISSUE TITLE
[libpqxx] build failure on windows, linux

### ISSUE THREAD

**Issue by mkrivos** [microsoft/vcpkg#41337]
### Operating system

Windows, Linux

### Compiler

gcc, msvc

### Steps to reproduce the behavior

```Shell
Try compile this package
```

### Failure logs

Installing 1/57 libpqxx:x64-linux@7.9.0...
Building libpqxx:x64-linux@7.9.0...
/home/rsys/vcpkg/buildtrees/versioning_/versions/libpqxx/c8078815fcddf1da8e7d8fba66100befaa779ec0: info: installing overlay port from here
-- Using cached jtv-libpqxx-7.9.0.tar.gz.
-- Cleaning sources at /home/rsys/vcpkg/buildtrees/libpqxx/src/7.9.0-eff3c4d31f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/rsys/vcpkg/downloads/jtv-libpqxx-7.9.0.tar.gz
-- Applying patch fix_build_with_vs2017.patch
-- Using source at /home/rsys/vcpkg/buildtrees/libpqxx/src/7.9.0-eff3c4d31f.clean
-- Found external ninja('1.12.1').
-- Configuring x64-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
   Command failed: /usr/bin/ninja -v
   Working Directory: /home/rsys/vcpkg/buildtrees/libpqxx/x64-linux-rel/vcpkg-parallel-configure
   Error code: 1
   See logs for more information:
     /home/rsys/vcpkg/buildtrees/libpqxx/config-x64-linux-dbg-CMakeCache.txt.log
     /home/rsys/vcpkg/buildtrees/libpqxx/config-x64-linux-rel-CMakeCache.txt.log
     /home/rsys/vcpkg/buildtrees/libpqxx/config-x64-linux-dbg-CMakeConfigureLog.yaml.log
     /home/rsys/vcpkg/buildtrees/libpqxx/config-x64-linux-rel-CMakeConfigureLog.yaml.log
     /home/rsys/vcpkg/buildtrees/libpqxx/config-x64-linux-out.log
Call Stack (most recent call first):
 /home/rsys/projects/lapdis/build_debug/vcpkg_installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:269 (vcpkg_execute_required_process)
 buildtrees/versioning_/versions/libpqxx/c8078815fcddf1da8e7d8fba66100befaa779ec0/portfile.cmake:14 (vcpkg_cmake_configure)
 scripts/ports.cmake:192 (include)

error: building libpqxx:x64-linux failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle libpqxx:x64-linux: 547 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libpqxx
You can submit a new issue at:
https://github.com/microsoft/vcpkg/issues/new?title=[libpqxx]+Build+error+on+x64-linux&body=Copy+issue+body+from+%2Fhome%2Frsys%2Fprojects%2Flapdis%2Fbuild_debug%2Fvcpkg_installed%2Fvcpkg
%2Fissue_body.md
-- Running vcpkg install - failed
CMake Error at /home/rsys/vcpkg/scripts/buildsystems/vcpkg.cmake:904 (message):
 vcpkg install failed.  See logs for more information:
 /home/rsys/projects/lapdis/build_debug/vcpkg-manifest-install.log
Call Stack (most recent call first):
 build_debug/CMakeFiles/3.30.3/CMakeSystem.cmake:6 (include)
 CMakeLists.txt:2 (project)

### Additional context

Seems that package doesn't like cmake 3.30 and above.

This issues was introduced with this commit - https://github.com/microsoft/vcpkg/commit/511d74f695bd45959d12b50b00f1b68f69e8f0b0

**Comment by dg0yt** [comment]
This issue was already fixed with https://github.com/microsoft/vcpkg/pull/39927.

You use manifest mode, so you must update either `builtin-baseline` or `overrides` to get a port update.
