### ISSUE TITLE
Package: zlib:x86-windows   Vcpkg version: 0.0.113-nohash

### ISSUE THREAD

**Issue by advaitjavadekar** [Microsoft/vcpkg#4134]
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: C:/Users/ajavadek/vcpkg/buildtrees/zlib/x86-windows-rel/vcpkg-parallel-configure
    See logs for more information:
      C:\Users\ajavadek\vcpkg\buildtrees\zlib\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:246 (vcpkg_execute_required_process)
  ports/zlib/portfile.cmake:19 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)
[config-x86-windows-out.log](https://github.com/Microsoft/vcpkg/files/2307854/config-x86-windows-out.log)

**Comment by Voskrese** [comment]
`-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.15.26726/bin/Hostx64/x86/cl.exe -- broken`

**Comment by jacknlliu** [comment]
```
The following packages will be built and installed:
    zlib[core]:x86-windows
Starting package 1/1: zlib:x86-windows
Building package zlib[core]:x86-windows...
-- Using cached D:/Workspace/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch D:/Workspace/vcpkg/ports/zlib/cmake_dont_build_more_than_needed.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: D:/Workspace/vcpkg/downloads/tools/cmake-3.11.4-windows/cmake-3.11.4-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: D:/Workspace/vcpkg/buildtrees/zlib/x86-windows-dbg
    See logs for more information:
      D:\Workspace\vcpkg\buildtrees\zlib\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/zlib/portfile.cmake:29 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package zlib:x86-windows failed with: BUILD_FAILED
```

**Comment by LarryIII** [comment]
@advaitjavadekar I installed zlib:x86-windows successfully with VS 2017 15.9.5. Could you please try again? 
 Please close this issue if you can install zlib now, thank you!

**Comment by LarryIII** [comment]
Please open a new issue if this is still a problem for you~
