### ISSUE TITLE
Possible incorrect value of CMAKE_SYSTEM_PROCESSOR for x86 Linux triplets

### ISSUE THREAD

**Issue by JohnstonJ** [microsoft/vcpkg#41347]
This code in the Linux toolchain doesn't look right to me: https://github.com/microsoft/vcpkg/blob/7adc2e4d49e8d0efc07a369079faa6bc3dbb90f3/scripts/toolchains/linux.cmake#L27-L28

I think it's setting the wrong value for `CMAKE_SYSTEM_PROCESSOR`.  I think the `x86` is not a legal value on Linux.  I haven't actually tried to use this target - I only spotted it while reviewing it to write my own toolchain file.  So consider this issue to be "code review feedback" at this point, as opposed to "this caused a problem."

CMake documentation states: https://cmake.org/cmake/help/latest/variable/CMAKE_SYSTEM_PROCESSOR.html
> this variable has the same value as the [CMAKE_HOST_SYSTEM_PROCESSOR](https://cmake.org/cmake/help/latest/variable/CMAKE_HOST_SYSTEM_PROCESSOR.html#variable:CMAKE_HOST_SYSTEM_PROCESSOR) variable

And for `CMAKE_HOST_SYSTEM_PROCESSOR`:
> On systems that support uname, this variable is set to the output of: `uname -m on GNU, Linux, Cygwin, Android`

Indeed, this is the case, from CMake source code: https://github.com/Kitware/CMake/blob/581be8a0fd648955937b16cefec05f0715bca725/Modules/CMakeDetermineSystem.cmake#L54-L59

```cmake
    if(CMAKE_HOST_SYSTEM_NAME MATCHES "Linux|CYGWIN.*|MSYS.*|^GNU$|Android")
      execute_process(COMMAND ${CMAKE_UNAME} -m
        OUTPUT_VARIABLE CMAKE_HOST_SYSTEM_PROCESSOR
        RESULT_VARIABLE val
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET)
```

Clearly, it is running `uname -m`, so the next question is - what is the value of `uname -m` expected to be on 32-bit Intel architecture?

Well, it seems there are a lot of possible values, including some other alternatives on pre-Pentium processors: https://stackoverflow.com/questions/45125516/possible-values-for-uname-m/

.... that is a long list.

So I figured up a 32-bit Alpine Linux ISO in a Hyper-V instance on my Windows 10 amd64 host, and then ran `uname -m`.  It reports `i686`.  So wouldn't this mean that the vcpkg source code is wrong?

**Comment by WangWeiLin-MV** [comment]
Thanks for your thorough investigation.

I also checked the CMake source and found little conditions like https://gitlab.kitware.com/cmake/cmake/-/blob/v3.30.5/Modules/FindJNI.cmake?ref_type=tags#L149

```cmake
if(CMAKE_SYSTEM_PROCESSOR MATCHES "^i.86$")
```

This condition might be used correctly after the change.
