### ISSUE TITLE
osx ci is fail due overtime

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#41358]
osx ci is failed lately due over time after 2 days.
2 days is not enough for compile all osx ports.

https://dev.azure.com/vcpkg/public/_build/results?buildId=107538&view=logs&j=7b75bd19-17d3-53d4-00fd-23f1a49a8ba4&t=c0c57043-5abe-5a13-5ef1-aa66ea261ab3

**Comment by jimwang118** [comment]
This is not an issue. If the CI execution time exceeds the set maximum execution time, it will interrupt on its own.

**Comment by talregev** [comment]
> This is not an issue. If the CI execution time exceeds the set maximum execution time, it will interrupt on its own.

You set the maximum execution time that osx ci cannot finish on that time.
I see the last recent it just did. I don't know if it 1 time, because many time backward, I can show you  examples that osx don't finish on the maximum execution time.

**Comment by dg0yt** [comment]
Some occurences have been observed in the past, but it could never be tracked down to a particular cause.
Extending the execution time doesn't help. If you are curious, analyze the CI log for where extra time is spent in comparison to successful runs.

**Comment by talregev** [comment]
> Some occurences have been observed in the past, but it could never be tracked down to a particular cause. Extending the execution time doesn't help. If you are curious, analyze the CI log for where extra time is spent in comparison to successful runs.

What the intended solution for this problem? To let it be?

**Comment by dg0yt** [comment]
If it is rare enough and when resources are limited, it might be reasonable to let it be. There are more pressing issues to work on. (When will we get caching for large artifacts?)

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
