### ISSUE TITLE
Error: Building package python3:x64-linux failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by bowie7070** [microsoft/vcpkg#4135]
I am trying to build boost-python with vcpkg using clang 6.0.1 on Ubuntu 16.04 and I get a build error as follows. Any insight on how to resolve this would be appreciated.

owe043@bullet-cl:/software/vcpkg$ CXX=clang++-libc++ ./vcpkg install boost-python
The following packages will be built and installed:
    boost-python[core]:x64-linux
  * python3[core]:x64-linux
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: python3:x64-linux
Building package python3[core]:x64-linux...
-- Using cached /software/vcpkg/downloads/python-cpython-v3.6.4.tar.gz
-- Extracting source /software/vcpkg/downloads/python-cpython-v3.6.4.tar.gz
-- Applying patch /software/vcpkg/ports/python3/0004-Fix-iomodule-for-RS4-SDK.patch
-- Applying patch /software/vcpkg/ports/python3/0005-Fix-DefaultWindowsSDKVersion.patch
-- Using source at /software/vcpkg/buildtrees/python3/src/v3.6.4-5bfb0301b2
-- Applying patch /software/vcpkg/ports/python3/0001-Static-library.patch
-- Building /software/vcpkg/buildtrees/python3/src/v3.6.4-5bfb0301b2-Lib-static-crt-dynamic/PCBuild/pythoncore.vcxproj for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: msbuild;/software/vcpkg/buildtrees/python3/src/v3.6.4-5bfb0301b2-Lib-static-crt-dynamic/PCBuild/pythoncore.vcxproj;/p:Configuration=Release;/t:Rebuild;/p:Platform=x64;/p:PlatformToolset=external;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No;/p:WindowsTargetPlatformVersion=;/m;/p:WholeProgramOptimization=false
    Working Directory: /software/vcpkg/buildtrees/python3/x64-linux-rel
    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:119 (vcpkg_execute_required_process)
  ports/python3/portfile.cmake:55 (vcpkg_build_msbuild)
  scripts/ports.cmake:71 (include)

Error: Building package python3:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: python3:x64-linux
  Vcpkg version: 0.0.113-unknownhash

Additionally, attach any relevant sections from the log files above.

Note:

owe043@bullet-cl:~$ echo $CC
clang
owe043@bullet-cl:~$ which clang
/software/clang+llvm-6.0.1-x86_64-linux-gnu-ubuntu-16.04/bin/clang
owe043@bullet-cl:~$ clang --version
clang version 6.0.1 (tags/RELEASE_601/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /software/clang+llvm-6.0.1-x86_64-linux-gnu-ubuntu-16.04/bin

In particular where do I look for the log files as:
owe043@bullet-cl:/software/vcpkg$ cd /software/vcpkg/buildtrees/python3/x64-linux-rel
owe043@bullet-cl:/software/vcpkg/buildtrees/python3/x64-linux-rel$ ls
owe043@bullet-cl:/software/vcpkg/buildtrees/python3/x64-linux-rel$

**Comment by bowie7070** [comment]
I've made a start on implementing the port file for Linux.

https://github.com/bowie7070/vcpkg/commit/b57c33b7d3f50e1e2222b03fd8b8819b118dcc4f

However, I can't get boost-python to discover the version inside vcpkg when it builds. It keeps finding my system version. So further changes might be required. Or possibly changes to the boost-python port file or to boost-python itself.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed in PR #8055. So I am closing this issue for now.
