### ISSUE TITLE
ERROR: Building package liblzma:x64-windows

### ISSUE THREAD

**Issue by RDelet** [Microsoft/vcpkg#4137]
I try to build boost lib with this command line: 

> vcpkg install boost:x64-windows

**But I have this error:**

> Error: Building package liblzma:x64-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: liblzma:x64-windows
>   Vcpkg version: 0.0.113-nohash

**I have this callstack:**

> Starting package 32/143: liblzma:x64-windows
> Building package liblzma[core]:x64-windows...
> -- Downloading https://github.com/xz-mirror/xz/archive/v5.2.3.tar.gz...
> -- Extracting source D:/Work/Photogrammetrie/Soft/vcpkg/downloads/xz-mirror-xz-v5.2.3.tar.gz
> -- Using source at D:/Work/Photogrammetrie/Soft/vcpkg/buildtrees/liblzma/src/v5.2.3-b3437cea7b
> -- Applying patch D:/Work/Photogrammetrie/Soft/vcpkg/ports/liblzma/enable-uwp-builds.patch
> -- Downloading https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip...
> -- Configuring x64-windows
> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
>     Command failed: ninja;-v
>     Working Directory: D:/Work/Photogrammetrie/Soft/vcpkg/buildtrees/liblzma/x64-windows-rel/vcpkg-parallel-configure
>     See logs for more information:
>       D:\Work\Photogrammetrie\Soft\vcpkg\buildtrees\liblzma\config-x64-windows-out.log

> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_configure_cmake.cmake:246 (vcpkg_execute_required_process)
>   ports/liblzma/portfile.cmake:18 (vcpkg_configure_cmake)
>   scripts/ports.cmake:71 (include)

II not have a space in my path and a use vcpkg update command before install boost.
Anyone have a solution ?

**Comment by Voskrese** [comment]
> See logs for more information:
> D:\Work\Photogrammetrie\Soft\vcpkg\buildtrees\liblzma\config-x64-windows-out.log

**Comment by RDelet** [comment]
> [1/2] cmd /c "cd .. && "D:/Work/Photogrammetrie/Soft/vcpkg/downloads/tools/cmake-3.11.4-windows/cmake-3.11.4-win32-x86/bin/cmake.exe" "D:/Work/Photogrammetrie/Soft/vcpkg/buildtrees/liblzma/src/v5.2.3-b3437cea7b" "-DCMAKE_MAKE_PROGRAM=D:/Work/Photogrammetrie/Soft/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/Work/Photogrammetrie/Soft/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=D:/Work/Photogrammetrie/Soft/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=D:/Work/Photogrammetrie/Soft/vcpkg/packages/liblzma_x64-windows""
> FAILED: ../CMakeCache.txt 
> cmd /c "cd .. && "D:/Work/Photogrammetrie/Soft/vcpkg/downloads/tools/cmake-3.11.4-windows/cmake-3.11.4-win32-x86/bin/cmake.exe" "D:/Work/Photogrammetrie/Soft/vcpkg/buildtrees/liblzma/src/v5.2.3-b3437cea7b" "-DCMAKE_MAKE_PROGRAM=D:/Work/Photogrammetrie/Soft/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/Work/Photogrammetrie/Soft/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=D:/Work/Photogrammetrie/Soft/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=D:/Work/Photogrammetrie/Soft/vcpkg/packages/liblzma_x64-windows""
> CMake Warning (dev) at CMakeLists.txt:19:
>   Syntax Warning in cmake code at column 7
> 
>   Argument not separated from preceding token by whitespace.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) at CMakeLists.txt:61:
>   Syntax Warning in cmake code at column 2
> 
>   Argument not separated from preceding token by whitespace.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- The C compiler identification is MSVC 19.0.24210.0
> -- The CXX compiler identification is MSVC 19.0.24210.0
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- broken
> CMake Error at D:/Work/Photogrammetrie/Soft/vcpkg/downloads/tools/cmake-3.11.4-windows/cmake-3.11.4-win32-x86/share/cmake-3.11/Modules/CMakeTestCCompiler.cmake:52 (message):
>   The C compiler
> 
>     "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe"
> 
>   is not able to compile a simple test program.
> 
>   It fails with the following output:
> 
>     Change Dir: D:/Work/Photogrammetrie/Soft/vcpkg/buildtrees/liblzma/x64-windows-rel/CMakeFiles/CMakeTmp
>     
>     Run Build Command:"D:/Work/Photogrammetrie/Soft/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "cmTC_599d1"
>     [1/2] Building C object CMakeFiles\cmTC_599d1.dir\testCCompiler.c.obj
>     [2/2] Linking C executable cmTC_599d1.exe
>     FAILED: cmTC_599d1.exe 
>     cmd.exe /C "cd . && D:\Work\Photogrammetrie\Soft\vcpkg\downloads\tools\cmake-3.11.4-windows\cmake-3.11.4-win32-x86\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_599d1.dir --manifests  -- C:\PROGRA~2\MICROS~3.0\VC\bin\amd64\link.exe /nologo CMakeFiles\cmTC_599d1.dir\testCCompiler.c.obj  /out:cmTC_599d1.exe /implib:cmTC_599d1.lib /pdb:cmTC_599d1.pdb /version:0.0  /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
>     MT: command "mt /nologo /manifest CMakeFiles\cmTC_599d1.dir/intermediate.manifest /out:CMakeFiles\cmTC_599d1.dir/embed.manifest /notify_update" failed (exit code 0x0) with the following output:
>     Le fichier spécifié est introuvable
>     ninja: build stopped: subcommand failed.
>     
> 
>   
> 
>   CMake will not be able to correctly generate this project.
> Call Stack (most recent call first):
>   CMakeLists.txt:2 (project)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "D:/Work/Photogrammetrie/Soft/vcpkg/buildtrees/liblzma/x64-windows-rel/CMakeFiles/CMakeOutput.log".
> See also "D:/Work/Photogrammetrie/Soft/vcpkg/buildtrees/liblzma/x64-windows-rel/CMakeFiles/CMakeError.log".
> [2/2] cmd /c "cd ../../x64-windows-dbg && "D:/Work/Photogrammetrie/Soft/vcpkg/downloads/tools/cmake-3.11.4-windows/cmake-3.11.4-win32-x86/bin/cmake.exe" "D:/Work/Photogrammetrie/Soft/vcpkg/buildtrees/liblzma/src/v5.2.3-b3437cea7b" "-DCMAKE_MAKE_PROGRAM=D:/Work/Photogrammetrie/Soft/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/Work/Photogrammetrie/Soft/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=D:/Work/Photogrammetrie/Soft/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-DLIBLZMA_SKIP_HEADERS=ON" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=D:/Work/Photogrammetrie/Soft/vcpkg/packages/liblzma_x64-windows/debug""
> FAILED: ../../x64-windows-dbg/CMakeCache.txt 
> cmd /c "cd ../../x64-windows-dbg && "D:/Work/Photogrammetrie/Soft/vcpkg/downloads/tools/cmake-3.11.4-windows/cmake-3.11.4-win32-x86/bin/cmake.exe" "D:/Work/Photogrammetrie/Soft/vcpkg/buildtrees/liblzma/src/v5.2.3-b3437cea7b" "-DCMAKE_MAKE_PROGRAM=D:/Work/Photogrammetrie/Soft/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/Work/Photogrammetrie/Soft/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=D:/Work/Photogrammetrie/Soft/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-DLIBLZMA_SKIP_HEADERS=ON" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=D:/Work/Photogrammetrie/Soft/vcpkg/packages/liblzma_x64-windows/debug""
> CMake Warning (dev) at CMakeLists.txt:19:
>   Syntax Warning in cmake code at column 7
> 
>   Argument not separated from preceding token by whitespace.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) at CMakeLists.txt:61:
>   Syntax Warning in cmake code at column 2
> 
>   Argument not separated from preceding token by whitespace.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- The C compiler identification is MSVC 19.0.24210.0
> -- The CXX compiler identification is MSVC 19.0.24210.0
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- broken
> CMake Error at D:/Work/Photogrammetrie/Soft/vcpkg/downloads/tools/cmake-3.11.4-windows/cmake-3.11.4-win32-x86/share/cmake-3.11/Modules/CMakeTestCCompiler.cmake:52 (message):
>   The C compiler
> 
>     "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe"
> 
>   is not able to compile a simple test program.
> 
>   It fails with the following output:
> 
>     Change Dir: D:/Work/Photogrammetrie/Soft/vcpkg/buildtrees/liblzma/x64-windows-dbg/CMakeFiles/CMakeTmp
>     
>     Run Build Command:"D:/Work/Photogrammetrie/Soft/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "cmTC_bd24f"
>     [1/2] Building C object CMakeFiles\cmTC_bd24f.dir\testCCompiler.c.obj
>     [2/2] Linking C executable cmTC_bd24f.exe
>     FAILED: cmTC_bd24f.exe 
>     cmd.exe /C "cd . && D:\Work\Photogrammetrie\Soft\vcpkg\downloads\tools\cmake-3.11.4-windows\cmake-3.11.4-win32-x86\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_bd24f.dir --manifests  -- C:\PROGRA~2\MICROS~3.0\VC\bin\amd64\link.exe /nologo CMakeFiles\cmTC_bd24f.dir\testCCompiler.c.obj  /out:cmTC_bd24f.exe /implib:cmTC_bd24f.lib /pdb:cmTC_bd24f.pdb /version:0.0  /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
>     MT: command "mt /nologo /manifest CMakeFiles\cmTC_bd24f.dir/intermediate.manifest /out:CMakeFiles\cmTC_bd24f.dir/embed.manifest /notify_update" failed (exit code 0x0) with the following output:
>     Le fichier spécifié est introuvable
>     ninja: build stopped: subcommand failed.
>     
> 
>   
> 
>   CMake will not be able to correctly generate this project.
> Call Stack (most recent call first):
>   CMakeLists.txt:2 (project)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "D:/Work/Photogrammetrie/Soft/vcpkg/buildtrees/liblzma/x64-windows-dbg/CMakeFiles/CMakeOutput.log".
> See also "D:/Work/Photogrammetrie/Soft/vcpkg/buildtrees/liblzma/x64-windows-dbg/CMakeFiles/CMakeError.log".
> ninja: build stopped: subcommand failed.
>

**Comment by Voskrese** [comment]
` -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- broken`

**Comment by RDelet** [comment]
I don't understand why because path exists...

![image](https://user-images.githubusercontent.com/7300189/44459730-f7148100-a60a-11e8-9347-7bf83deabbea.png)

**Comment by Voskrese** [comment]
What is installed it is visible and so, does not pass the check, apparently something was not fixed, LIB, include

**Comment by RDelet** [comment]
hum... What is a solution ? Re install visual ?

**Comment by Voskrese** [comment]
errors occurred!
See also `"D:/Work/Photogrammetrie/Soft/vcpkg/buildtrees/liblzma/x64-windows-rel/CMakeFiles/CMakeOutput.log".`
See also `"D:/Work/Photogrammetrie/Soft/vcpkg/buildtrees/liblzma/x64-windows-rel/CMakeFiles/CMakeError.log".`

**Comment by RDelet** [comment]
**OUTPUT**

> The system is: Windows - 10.0.16299 - AMD64
> Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
> Compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe 
> Build flags: ;/DWIN32;/D_WINDOWS;/W3;/utf-8;/MP;
> Id flags:  
> 
> The output was:
> 0
> Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24210 for x64
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> CMakeCCompilerId.c
> Microsoft (R) Incremental Linker Version 14.00.24210.0
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> /out:CMakeCCompilerId.exe 
> CMakeCCompilerId.obj 
> 
> 
> Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.exe"
> 
> Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.obj"
> 
> The C compiler identification is MSVC, found in "D:/Work/Photogrammetrie/Soft/vcpkg/buildtrees/liblzma/x64-windows-rel/CMakeFiles/3.11.4/CompilerIdC/CMakeCCompilerId.exe"
> 
> Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
> Compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe 
> Build flags: ;/DWIN32;/D_WINDOWS;/W3;/utf-8;/GR;/EHsc;/MP;
> Id flags:  
> 
> The output was:
> 0
> Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24210 for x64
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> CMakeCXXCompilerId.cpp
> Microsoft (R) Incremental Linker Version 14.00.24210.0
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> /out:CMakeCXXCompilerId.exe 
> CMakeCXXCompilerId.obj 
> 
> 
> Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.exe"
> 
> Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.obj"
> 
> The CXX compiler identification is MSVC, found in "D:/Work/Photogrammetrie/Soft/vcpkg/buildtrees/liblzma/x64-windows-rel/CMakeFiles/3.11.4/CompilerIdCXX/CMakeCXXCompilerId.exe"

**ERROR**

> Determining if the C compiler works failed with the following output:
> Change Dir: D:/Work/Photogrammetrie/Soft/vcpkg/buildtrees/liblzma/x64-windows-rel/CMakeFiles/CMakeTmp
> 
> Run Build Command:"D:/Work/Photogrammetrie/Soft/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "cmTC_599d1"
> [1/2] Building C object CMakeFiles\cmTC_599d1.dir\testCCompiler.c.obj
> 
> [2/2] Linking C executable cmTC_599d1.exe
> 
> FAILED: cmTC_599d1.exe 
> 
> cmd.exe /C "cd . && D:\Work\Photogrammetrie\Soft\vcpkg\downloads\tools\cmake-3.11.4-windows\cmake-3.11.4-win32-x86\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_599d1.dir --manifests  -- C:\PROGRA~2\MICROS~3.0\VC\bin\amd64\link.exe /nologo CMakeFiles\cmTC_599d1.dir\testCCompiler.c.obj  /out:cmTC_599d1.exe /implib:cmTC_599d1.lib /pdb:cmTC_599d1.pdb /version:0.0  /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
> 
> MT: command "mt /nologo /manifest CMakeFiles\cmTC_599d1.dir/intermediate.manifest /out:CMakeFiles\cmTC_599d1.dir/embed.manifest /notify_update" failed (exit code 0x0) with the following output:
> Le fichier spécifié est introuvable
> 
> ninja: build stopped: subcommand failed.

**Comment by Voskrese** [comment]
`link.exe /nologo CMakeFiles\cmTC_599d1.dir\testCCompiler.c.obj /out:cmTC_599d1.exe /implib:cmTC_599d1.lib /pdb:cmTC_599d1.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib` 

` Le fichier spécifié est introuvable`
?
`kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib`

**Comment by RDelet** [comment]
I have a same message but at end I found this
> LINK : fatal error LNK1104: cannot open file 'kernel32.lib'

But this lib is in directory

**Full error log :**

> Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
> Compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe 
> Build flags: ;/DWIN32;/D_WINDOWS;/W3;/utf-8;/MP;
> Id flags:  
> 
> The output was:
> 2
> Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24210 for x64
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> CMakeCCompilerId.c
> Microsoft (R) Incremental Linker Version 14.00.24210.0
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> /out:CMakeCCompilerId.exe 
> CMakeCCompilerId.obj 
> LINK : fatal error LNK1104: cannot open file 'kernel32.lib'
> 
> 
> Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
> Compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe 
> Build flags: ;/DWIN32;/D_WINDOWS;/W3;/utf-8;/GR;/EHsc;/MP;
> Id flags:  
> 
> The output was:
> 2
> Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24210 for x64
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> CMakeCXXCompilerId.cpp
> Microsoft (R) Incremental Linker Version 14.00.24210.0
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> /out:CMakeCXXCompilerId.exe 
> CMakeCXXCompilerId.obj 
> LINK : fatal error LNK1104: cannot open file 'kernel32.lib'
> 
> 
> Determining if the C compiler works failed with the following output:
> Change Dir: D:/Work/Photogrammetrie/Soft/vcpkg/buildtrees/liblzma/x64-windows-rel/CMakeFiles/CMakeTmp
> 
> Run Build Command:"D:/Work/Photogrammetrie/Soft/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "cmTC_5e8c7"
> [1/2] Building C object CMakeFiles\cmTC_5e8c7.dir\testCCompiler.c.obj
> 
> [2/2] Linking C executable cmTC_5e8c7.exe
> 
> FAILED: cmTC_5e8c7.exe 
> 
> cmd.exe /C "cd . && D:\Work\Photogrammetrie\Soft\vcpkg\downloads\tools\cmake-3.11.4-windows\cmake-3.11.4-win32-x86\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_5e8c7.dir --manifests  -- C:\PROGRA~2\MICROS~3.0\VC\bin\amd64\link.exe /nologo CMakeFiles\cmTC_5e8c7.dir\testCCompiler.c.obj  /out:cmTC_5e8c7.exe /implib:cmTC_5e8c7.lib /pdb:cmTC_5e8c7.pdb /version:0.0  /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
> 
> LINK Pass 1: command "C:\PROGRA~2\MICROS~3.0\VC\bin\amd64\link.exe /nologo CMakeFiles\cmTC_5e8c7.dir\testCCompiler.c.obj /out:cmTC_5e8c7.exe /implib:cmTC_5e8c7.lib /pdb:cmTC_5e8c7.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\cmTC_5e8c7.dir/intermediate.manifest CMakeFiles\cmTC_5e8c7.dir/manifest.res" failed (exit code 1104) with the following output:
> LINK : fatal error LNK1104: cannot open file 'kernel32.lib'
> 
> ninja: build stopped: subcommand failed.

**Comment by Voskrese** [comment]
Need to reinstall for x86_64 Lib

**Comment by RDelet** [comment]
OK I try this

**Comment by RDelet** [comment]
I have a same error of first error log file...

**Comment by Voskrese** [comment]
```
C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17134.0\um>tree
Структура папок тома Windows 10
Серийный номер тома: 581C-438A
C:.
├───arm
│   ├───iddcx
│   │   ├───1.0
│   │   ├───1.2
│   │   └───1.3
│   ├───nfc
│   │   └───1.0
│   ├───pos
│   │   └───1.1
│   ├───sensors
│   │   └───1.1
│   └───ucm
│       └───1.0
├───arm64
│   ├───iddcx
│   │   ├───1.0
│   │   ├───1.2
│   │   └───1.3
│   ├───nfc
│   │   └───1.0
│   ├───pos
│   │   └───1.1
│   ├───sensors
│   │   └───1.1
│   └───ucm
│       └───1.0
├───x64
│   ├───iddcx
│   │   ├───1.0
│   │   ├───1.2
│   │   └───1.3
│   ├───nfc
│   │   └───1.0
│   ├───pos
│   │   └───1.1
│   ├───sensors
│   │   └───1.1
│   └───ucm
│       └───1.0
└───x86
    ├───iddcx
    │   ├───1.0
    │   ├───1.2
    │   └───1.3
    ├───nfc
    │   └───1.0
    ├───pos
    │   └───1.1
    ├───sensors
    │   └───1.1
    └───ucm
        └───1.0
```

**Comment by Voskrese** [comment]
`ls "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17134.0\um\x64\kernel32.lib"`

**Comment by RDelet** [comment]
I uninstall Visual and windows kits and reinstall it and now it's not possible to build vcpkg... :)

I don't understand tree view
iddcx, nfc, pos, sensors, ucm is directory ?

**Comment by Voskrese** [comment]
ucm is directory

10.0.17134.0\um\x64\

**Comment by Voskrese** [comment]
https://github.com/Microsoft/vcpkg/issues/4137#issuecomment-414999134

You have - kernel32.lib

> I have all file in my C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17134.0\um\arm64

And it should be so - kernel32.lib

`C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17134.0\um\x64`

**Comment by RDelet** [comment]
Ok vcpkg rebuild without error now.
I have all lib on error log in C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17134.0\um\x64 too

**Comment by RDelet** [comment]
I restart with VS2015 reinstalled and WindowsKit reinstalled.
I check if I have all dependance file : kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib


> It fails with the following output:
> 
>   Change Dir: D:/Work/Photogrammetrie/Soft/vcpkg/buildtrees/liblzma/x64-windows-rel/CMakeFiles/CMakeTmp
>   
>   Run Build Command:"D:/Work/Photogrammetrie/Soft/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "cmTC_27a35"
>   [1/2] Building C object CMakeFiles\cmTC_27a35.dir\testCCompiler.c.obj
>   [2/2] Linking C executable cmTC_27a35.exe
>   FAILED: cmTC_27a35.exe 
>   cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_27a35.dir --manifests  -- C:\PROGRA~2\MICROS~3.0\VC\bin\amd64\link.exe /nologo CMakeFiles\cmTC_27a35.dir\testCCompiler.c.obj  /out:cmTC_27a35.exe /implib:cmTC_27a35.lib /pdb:cmTC_27a35.pdb /version:0.0  /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
>   MT: command "mt /nologo /manifest CMakeFiles\cmTC_27a35.dir/intermediate.manifest /out:CMakeFiles\cmTC_27a35.dir/embed.manifest /notify_update" failed (exit code 0x0) with the following output:
>   Le fichier spécifié est introuvable
>   ninja: build stopped: subcommand failed.

**Comment by RDelet** [comment]
I try in my home computer and i don't have problem for build zlib but it's always impossible to build on my work computer. It's possible to loosse env variable ?

**Comment by RDelet** [comment]
Hi everyone,

I re re re install VisualStudio 2015 with lot of modules and now vcpkg seems works correctly

**Comment by LarryIII** [comment]
@RDelet Could you please close this feedback when you resolved your issue? Thank you!

**Comment by Goldname98** [comment]
I am having this problem. I am using VisualStudio 2019. Uninstalling and reinstalling doesn't work. Which packages did you include when reinstalling?
