### ISSUE TITLE
[libiconv] Build error on x64-windows

### ISSUE THREAD

**Issue by Abhisar-git** [microsoft/vcpkg#41383]
Copy issue body from C:/vcpkg/installed/vcpkg/issue_body.md
I am experiencing a build failure when trying to install `zlib` using `vcpkg` on Windows 11. The error appears during the configuration phase. The build fails with the message:

error: building libiconv:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle libiconv:x64-windows: 3.4 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Also, some issue related to ninja error message is as follows:
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
  Command failed: C:/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe -v
  Working Directory: C:/vcpkg/buildtrees/zlib/x64-windows-rel/vcpkg-parallel-configure
  Error code: 1

**Expected Behavior**:
The `zlib` package should build successfully.

**Actual Behavior**:
The build fails with errors during the configuration phase.

**Steps to Reproduce**:
1. Install vcpkg on Windows 11.
2. Run `vcpkg install zlib:x64-windows`.
3. The build fails during the configuration step.

**Logs**:
Logs attached:
   - `C:\vcpkg\buildtrees\zlib\config-x64-windows-out.log`
   - `C:\vcpkg\buildtrees\zlib\config-x64-windows-dbg-CMakeCache.txt.log`

**Environment**:
- OS: Windows 11
- Compiler: Visual Studio 2022
- vcpkg version: v2024.01
I have attached a picture of the command prompt:

**Comment by autoantwort** [comment]
> Logs attached:
> 
>     * `C:\vcpkg\buildtrees\zlib\config-x64-windows-out.log`
> 
>     * `C:\vcpkg\buildtrees\zlib\config-x64-windows-dbg-CMakeCache.txt.log`

Where?

**Comment by Abhisar-git** [comment]
Actually, I am trying to install libxml2 on my system,while trying to install it i enter command 
vcpkg install libxml2 and it shows this error.
I have copied the prompt for your reference and a screenshot of command prompt.
Please do let me know if anything else is required.
![Screenshot (35)](https://github.com/user-attachments/assets/2c8019e2-f68a-46c6-bc2d-4d70aa612137)


C:\vcpkg>vcpkg install libxml2
Computing installation plan...
The following packages will be built and installed:
  * libiconv:x64-windows@1.17#4
  * liblzma:x64-windows@5.6.2
    libxml2[core,iconv,lzma,zlib]:x64-windows@2.11.9
  * vcpkg-cmake-config:x64-windows@2024-05-23
  * zlib:x64-windows@1.3.1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
Restored 1 package(s) from C:\Users\abhis\AppData\Local\vcpkg\archives in 57.1 ms. Use --debug to see more details.
Installing 1/5 libiconv:x64-windows@1.17#4...
Building libiconv:x64-windows@1.17#4...
-- Using cached libiconv-1.17.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/libiconv/src/v1.17-84a471678e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/libiconv-1.17.tar.gz
-- Applying patch 0002-Config-for-MSVC.patch
-- Applying patch 0003-Add-export.patch
-- Applying patch 0004-ModuleFileName.patch
-- Applying patch clang-fortify.patch
-- Using source at C:/vcpkg/buildtrees/libiconv/src/v1.17-84a471678e.clean
-- Getting CMake variables for x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: C:/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe -v
    Working Directory: C:/vcpkg/buildtrees/libiconv/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\libiconv\get-cmake-vars-x64-windows-dbg-CMakeCache.txt.log
      C:\vcpkg\buildtrees\libiconv\get-cmake-vars-x64-windows-rel-CMakeCache.txt.log
      C:\vcpkg\buildtrees\libiconv\get-cmake-vars-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:314 (vcpkg_execute_required_process)
  scripts/cmake/z_vcpkg_get_cmake_vars.cmake:18 (vcpkg_configure_cmake)
  scripts/cmake/vcpkg_configure_make.cmake:250 (z_vcpkg_get_cmake_vars)
  ports/libiconv/portfile.cmake:29 (vcpkg_configure_make)
  scripts/ports.cmake:192 (include)


error: building libiconv:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle libiconv:x64-windows: 2.9 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libiconv
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[libiconv]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by autoantwort** [comment]
The logs are still missing. Don't upload screen shots here. Upload the issue body from C:/vcpkg/installed/vcpkg/issue_body.md

**Comment by Abhisar-git** [comment]
Sure,
[issue_body.md](https://github.com/user-attachments/files/17288176/issue_body.md)

**Comment by dg0yt** [comment]
> ~~~
> CMake Error at C:/Users/abhis/scoop/apps/cmake/3.30.4

Try without `scoop` in `PATH`.

**Comment by Abhisar-git** [comment]
it worked.
