### ISSUE TITLE
FindGTest

### ISSUE THREAD

**Issue by xandox** [Microsoft/vcpkg#414]
Hi, I am not sure that a right place to ask questsions, but I have not found any other. 
So, I have installed gtest

> vcpkg.exe list
gtest:x64-windows-static    1.8              GoogleTest and GoogleMock testing frameworks.

And simple CMakeLists.txt

```
cmake_minimum_required(VERSION 3.6)

project(myproject CXX)

find_package(GTest REQUIRED)
enable_testing()
```

But when I try to configure project I keep getting error that GTest not found

> cmake ..\ -DCMAKE_TOOLCHAIN_FILE="$Env:VCPKG_ROOT\scripts\buildsystems\vcpkg.cmake" -G "Visual Studio 14 Win64"
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at C:/Program Files/CMake/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR
  GTEST_MAIN_LIBRARY)

So, what I am doing wrong?

**Comment by xandox** [comment]
Uh, I figurate out what is a problem. 
gtest installed with x64-windows-static triplet, but when a configure buildsystem/vcpkg.cmake thinks I going to use dinamic runtime, so CMAKE_PREFIX_PATH ware pointed to wrong place.

**Comment by ras0219-msft** [comment]
Glad you were able to resolve the problem!

In order to help other users from hitting this in the future: did you have any `x64-windows` libraries installed at the time you were hitting the issue? We could potentially emit a warning or error during the CMake build if you are using a triplet that has no packages installed.

**Comment by xandox** [comment]
>In order to help other users from hitting this in the future: did you have any x64-windows libraries installed at the time you were hitting the issue?

No, only one package in x64-windows-static triplet. 

>We could potentially emit a warning or error during the CMake build if you are using a triplet that has no packages installed.

It's a wanderfull idea!
