### ISSUE TITLE
[openimageio] /utf-8 is required on Windows, but not supplied by the cmake target

### ISSUE THREAD

**Issue by LegalizeAdulthood** [microsoft/vcpkg#41405]
### Is your feature request related to a problem? Please describe.

If you include `<openimageio.h>` on Windows you get the following compilation error:

```
1>D:\legalize\utahcpp\openimageio\build-oiio-example-default\vcpkg_installed\x64-windows\include\OpenImageIO\detail\fmt\base.h(458,28): error C2338: static_assert failed: 'Unicode support requires compiling with /utf-8'
```

This is because openimageio depends on libfmt v11 which requires this.  However, the `OpenImageIO::OpenImageIO` target doesn't add this as a `PUBLIC` compile option for this target, so the required switch is not propagated to clients of the OpenImageIO target.

### Proposed solution

Add the necessary compile option on Windows

### Describe alternatives you've considered

There really isn't one as it prevents any portion of the library from being used.

### Additional context

See attached ZIP of source code that reproduces the problem.
[oiio-utf8.zip](https://github.com/user-attachments/files/17285355/oiio-utf8.zip)

**Comment by autoantwort** [comment]
I guess this is a bug of openimageio and not vcpkg and should be reported there :)

**Comment by LegalizeAdulthood** [comment]
OK, so the CMake targets don't come from the port?

**Comment by autoantwort** [comment]
Yes, normally the cmake config files are generated by the upstream project. Sometimes they are patched in by vcpkg, but then they starts with `unofficial::`.

**Comment by dg0yt** [comment]
And still, it might be a port bug. At least I don't see the port disabling `INTERNALIZE_FMT`. This results in openimageio target not linking the fmt target, and this results in the public compile options not being forwarded.

**Comment by dg0yt** [comment]
Please test #41429, I don't have MSVC. (But I checked the generated config.)

**Comment by LegalizeAdulthood** [comment]
Works without my workaround now, thanks for the quick fix.
