### ISSUE TITLE
[BUILD_FAILED] package bzip2:x64-windows failed

### ISSUE THREAD

**Issue by Voskrese** [Microsoft/vcpkg#4141]
> Error: Building package bzip2:x64-windows failed with: BUILD_FAILED

```
wget http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz
Connecting to www.bzip.org (208.91.197.44:80)
wget: can't open 'bzip2-1.0.6.tar.gz': File exists
```

browser 

> Error. Page cannot be displayed. Please contact your service provider for more details. (26)

**It is necessary to do something with mirrors on source**
Such errors more and more

**Comment by past-due** [comment]
Commits fixing this were merged on August 8 & 9: https://github.com/Microsoft/vcpkg/commits/master/ports/bzip2

If you git clone the master branch, you should receive those fixes.
