### ISSUE TITLE
[directx-dxc] Shared library libdxil.so not found on Linux

### ISSUE THREAD

**Issue by Iyeyasu** [microsoft/vcpkg#41428]
**Describe the bug**

Linking an executable against the libraries from `directx-dxc` package in CMake, and running the compiled executable will result in an error that the library `libdxil.so` can not be found. See **Failure Logs** for error message. See **Additional context** for a possible cause.

**Environment**
- OS: Arch Linux x64
- Compiler: clang-18.1.8

**To Reproduce**

1. Install the package `directx-dxc` (I used `vcpkg.json`)
2. In cmake, link your program against the library as instructed in the docs:
```
find_package(directx-dxc CONFIG REQUIRED)
target_link_libraries(myprogram PRIVATE Microsoft::DirectXShaderCompiler)
```
3. Compile and run the program.
4. Program will fail to run and you'll see an error message about not able to find the library `libdxil.so`.

**Expected behavior**

Program should find the `libdxil.so` library and run normally.

**Failure logs**

```
> ./myprogram
myprogram: error while loading shared libraries: vcpkg_installed/x64-linux/lib/libdxil.so: cannot open shared object file: No such file or directory
```

**Additional context**

I did some digging on this and found a possible cause. After using `readelf` on the executable, it revealed that the `libdxil.so` path is different compared to `libdxcompiler.so` for some reason. Notice the weird `vcpkg_installed/x64-linux/lib` prefix with `libdxil.so`:

```
 0x0000000000000001 (NEEDED)             Shared library: [libdxcompiler.so]
 0x0000000000000001 (NEEDED)             Shared library: [vcpkg_installed/x64-linux/lib/libdxil.so]
```

I then found this Stackoverflow thread where the user had similar weird path behaviour with their shared libraries which was related to a missing `SONAME`: https://stackoverflow.com/questions/56169684/why-does-cmake-links-external-library-by-relative-path. 

I confirmed that `vcpkg_installed/x64-linux/lib/libdxil.so` doesn't have its `SONAME` set by using `readelf` and then I tried setting the `SONAME` manually with: 

```
patchelf --set-soname libdxil.so libdxil.so
```

After setting the `SONAME`, the program compiled and ran without issue! Seems like missing `SONAME` on `libdxil.so` is causing an incorrect library path to be used. This might actually be a problem that has to be solved wherever `libdxil.so` is compiled, but maybe `vcpkg` could consider patching this similar to how it patches `RPATH`'s.

**Comment by Iyeyasu** [comment]
I don't think the fix worked, as I'm now getting this error with the new version after doing a clean build:

```
[cmake] CMake Warning at Modules/vcpkg/scripts/buildsystems/vcpkg.cmake:598 (_add_executable):
[cmake]   Cannot generate a safe dependent library path for target <mytarget> because files
[cmake]   in some directories may conflict with libraries in implicit directories:
[cmake] 
[cmake]     runtime library [libdxcompiler.so] in /lib may be hidden by files in:
[cmake]       <myprojectdir>/Build/vcpkg_installed/x64-linux/lib
```

**Comment by dg0yt** [comment]
The fix is broken. https://github.com/microsoft/vcpkg/pull/41439#discussion_r1797228035

**Comment by Mengna-Li** [comment]
This is my mistake, I will fix it soon.
