### ISSUE TITLE
Incompatible compiler options

### ISSUE THREAD

**Issue by jk-jeon** [Microsoft/vcpkg#4143]
Recently I've encountered a link error (unresolved external symbol) with vcpkg-provided nana 1.6.1.
The cause was optional support of `std::string_view`.
In a header file in nana (c++defines.hpp), there is a preprocessor detecting if `std::string_view` is available, using `_MSC_VER` + `_MSVC_LANG` for MS compiler and `__cplusplus` for others. Since msvc's default is set to C++14, not C++17, the compiled binary is generated assuming no support of`std::string_view`.

Now, for my application, I always turn on /std:c++latest and /Zc:__cplusplus, and use C++17 features heavily. That alone does not cause a problem, but in a class in nana (`nana::paint::graphics`), there are member functions (functions starting with `bidi_`) whose declarations and definitions are available only when `std::string_view` is supported. (`std::string const&`-versions are enabled instead if `std::string_view` is not supported, and those versions are disabled otherwise.) As the .lib file was generated without that support while the header file included in my project exposes `std::string_view`-enabled interfaces, I got unresolved external symbols.

What can I do? Is it possible to let vcpkg to generate .lib files with custom compiler options?

[PS]
I think this kind of problems are not nana-specific, thus I didn't wrote "nana" in the title.

**Comment by degski** [comment]
> I think this kind of problems are not nana-specific, thus I didn't wrote "nana" in the title.

Yes, this is an issue that starts to pop up in more places, like on the Boost mailing list, just recently. More generally mixed language std's linking. It's both a problem forward (f.e. std::auto_ptr removed) and backwards (your example of std::string_view). This problem is gonna get worse, if left unresolved, as C++20 removes a host of things.

**Comment by jk-jeon** [comment]
Yeah, perhaps being able to specify compiler options directly can be a much harm than good,
but still it would be nice if C++ std version can be specified in vcpkg.
Or possibly would it be nicer if specific required language features can be specified?

**Comment by arthur-tacca** [comment]
I believe what you want can be achieved by creating a custom triplet: copy one of the existing ones in the triplets subdirectory, and set the `VCPKG_CXX_FLAGS` variable. You only need to specify additional flags in that variable, not the full list of switches. See the [triplets documentation](https://github.com/Microsoft/vcpkg/blob/master/docs/users/triplets.md) for some more information.

Unfortunately you will need to specify those options again when you generate your executable's project with CMake e.g. by passing `-DCMAKE_CXX_FLAGS_DEBUG=...`. What's more you must pass the full list of switches, not just additional ones. I requested that these switches be inherited from the triplet in #3807.

**Comment by degski** [comment]
@arthur-tacca Thanks (also for filing #3807).

**Comment by MikeGitb** [comment]
> Or possibly would it be nicer if specific required language features can be specified?

No,  don't go for individual features or auto detection of "appropriate" c++ language level - that way lies madness. 

On any non toy project you
 should define what language levels (and/or compilers) you want to support and then write code that runs on them without any `#ifdef` s.

I know, established practice 8s doing the exact opposite, but unless you build everything together from scratch with exactly the same settings you (or your users) will run into trouble eventually.

**Comment by MikeGitb** [comment]
Also for reference: https://github.com/Microsoft/vcpkg/issues/4004

**Comment by MikeGitb** [comment]
> Or possibly would it be nicer if specific required language features can be specified?

No,  please don't go for individual feature detection!

**Comment by jk-jeon** [comment]
@arthur-tacca  Thanks again.
@MikeGitb Thanks for reference.

Okay, it seems that a "complete solution" to this kind of problems would be quite more complicated that I thought before. But it seems (according to #4004) I can handle the problem library-wise in an ad hoc manner by modifying the `CMakeLists.txt`. But I'm not sure which `CMakeLists.txt` should be edited. Is it the file in the buildtrees directory? Or the file in the ports directory? Or something other?

It seems that the file in the ports directory is copied into the buildtrees directory, so modifying the file in the buildtrees would have no effect. But I'm not sure if it is OK to modify files in the ports directory.

**Comment by MikeGitb** [comment]
Not sure, if this is still relevant, but if your libraries are built with cmake, you should ideally not need to touch their cmake files at all. Instead add something like `set(CMAKE_CXX_VERSION c++17)` to the triplet file you are using (e.g. https://github.com/Microsoft/vcpkg/blob/master/triplets/x64-windows.cmake). 

If the library's cmake file doesn't do stupid things (which far to many do unfortunately), this will make sure that all libraries are compiled with the same language standard. Of course, you might have to delete and re-install already build libraries after you changed the triplet file.

**Comment by jk-jeon** [comment]
As I said in #5671, I found out a solution to my problem.
I'm not sure which one of `set(CMAKE_CXX_VERSION c++17)` in the triplet file or the Line 29 of ports/nana/CMakeLists.txt takes the priority, but I feel the latter one is certainly a "hack".
I absolutely agree that the ability to turn on/off certain language features or to set the standard version library-wise should be a nightmare, and the triplet solution is the best option we have.
So, I close this issue. Thanks everyone!
