### ISSUE TITLE
[New Port Request] TinyUSDZ

### ISSUE THREAD

**Issue by ksor1** [microsoft/vcpkg#41448]
### Library name

TinyUSDZ

### Library description

TinyUSDZ is secure, portable and dependency-free(depends only on C++ STL. Other 3rd-party libraries included. Yes, you don't need pxrUSD/OpenUSD library!) USDZ/USDC/USDA library written in C++14.

### Source repository URL

https://github.com/lighttransport/tinyusdz

**Comment by dg0yt** [comment]
> dependency-free ... Other 3rd-party libraries included.

This actually means: *vendored dependencies*, must be de-vendored, *extra difficulty* to port.

**Comment by dg0yt** [comment]
Extra extra difficult. There is nothing "tiny" about this package:
https://github.com/lighttransport/tinyusdz?tab=readme-ov-file#third-party-licenses
