### ISSUE TITLE
Option to avoid filename conflicts in root directories of include paths of ports

### ISSUE THREAD

**Issue by is-this-c** [microsoft/vcpkg#41457]
It is very easy to get filename conflicts due to pollution in root directories of include paths. An option to prevent putting files into root directory i.e. turn `include/directxtk/Effects.h` into `include/directxtk/directxtk/Effects.h` would work. Why is it so rigid and inflexible? Is there another way?

**Comment by MonicaLiu0311** [comment]
I'm sorry, I don't understand your question. Could you please describe what operation you were doing when you encountered this problem and provide an example?

**Comment by is-this-c** [comment]
If I install directxtk I can use `#include <Effects.h>` because vcpkg's directory layout is `include/directxtk/Effects.h`. However for example I might have another port that has `Effects.h` in its root directory. I would like an option so that vcpkg can have `include/directxtk/directxtk/Effects.h`. In other words ports put their header files into `include/port/port` so as to avoid potential filename conflicts. I would also prefer to read `#include <directxtk/Effects.h>`.

**Comment by autoantwort** [comment]
vcpkg does what the upstream project does and normally don't modify that.

**Comment by MonicaLiu0311** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
