### ISSUE TITLE
openblas is failed to install in linux

### ISSUE THREAD

**Issue by apattnaik0721013** [Microsoft/vcpkg#4145]
following command failed:
./vcpkg install openblas:x64-windows

**Comment by Voskrese** [comment]
Bad news ;)
Can log files attach to the message?

**Comment by apattnaik0721013** [comment]
following error i got. i am using cmake version 3.11.4.

CMake Warning at CMakeLists.txt:41 (message):
  CMake support is experimental.  This will not produce the same Makefiles
  that OpenBLAS ships with.  Only x86 support is currently available.


CMake Error at cmake/prebuild.cmake:68 (string):
  string no output variable specified
Call Stack (most recent call first):
  cmake/system.cmake:122 (include)
  CMakeLists.txt:44 (include)


CMake Deprecation Warning at /root/orb-slam2/vcpkg/downloads/tools/cmake-3.11.4-linux/cmake-3.11.4-Linux-x86_64/share/cmake-3.11/Modules/CMakeForceCompiler.cmake:97 (message):
  The CMAKE_FORCE_Fortran_COMPILER macro is deprecated.  Instead just set
  CMAKE_Fortran_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  cmake/f_check.cmake:27 (CMAKE_FORCE_Fortran_COMPILER)
  cmake/prebuild.cmake:84 (include)
  cmake/system.cmake:122 (include)
  CMakeLists.txt:44 (include)


CMake Error at cmake/arch.cmake:80 (if):
  if given arguments:

    "STREQUAL" "ia64"

  Unknown arguments specified
Call Stack (most recent call first):
  cmake/system.cmake:132 (include)
  CMakeLists.txt:44 (include)

**Comment by Voskrese** [comment]
`CMAKE_FORCE_Fortran_COMPILER` PGI or Intel or GNU
`set(CMAKE_FORCE_Fortran_COMPILER PGI)`

Fortran is not used in offic. version

And as far as I know the port for vcpkg is not intended for Linux, Windows only

**Comment by Voskrese** [comment]
>  Only x86 support is currently available

`Linux-x86_64` = x64

**Comment by apattnaik0721013** [comment]
thanks voskrese. i am trying to build g2o in vcpkg ,openblas is one of dependencies in g2o.
- through apt-get i can install g2o, but with vcpkg , it is failed. 
- Do you have any clue, how to resolve this issue?

**Comment by Voskrese** [comment]
https://github.com/xianyi/OpenBLAS/issues

**Comment by Voskrese** [comment]
Linux x86 ?

**Comment by vicroms** [comment]
Fixed in #5245
