### ISSUE TITLE
[azure-identity-cpp] build failure using non-default triplets

### ISSUE THREAD

**Issue by bleze** [microsoft/vcpkg#41462]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

vcpkg.exe install azure-identity-cpp --debug

NB! azure-core-cpp, azure-storage-blobs-cpp and azure-storage-queues-cpp all build fine with my triplets. Only identity sdk does not.

### Failure logs

[azure-identity-cpp.txt](https://github.com/user-attachments/files/17324726/azure-identity-cpp.txt)

### Additional context

Triplets used;

set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PLATFORM_TOOLSET v141)

**Comment by Mengna-Li** [comment]
@bleze Please provide the failure log :`C:\Development\Lasernet\vcpkg\buildtrees\azure-identity-cpp\install-x64-windows-v141-dbg-out.log`, Thanks.

**Comment by bleze** [comment]
[install-x64-windows-v141-dbg-out.log](https://github.com/user-attachments/files/17325325/install-x64-windows-v141-dbg-out.log)

**Comment by Mengna-Li** [comment]
Duplicate of https://github.com/microsoft/vcpkg/issues/38230. Please use the newer Visual Studio and try again.

**Comment by bleze** [comment]
Oh, but I'm using this 'x64 Native Tools Command Prompt for VS 2022' and I can see that it finds both compilers.
Toolset is installed for VS2022 and working.

From the .txt I can see that it uses VS2019 as the .log shows;

Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe
Detecting compiler hash for triplet x64-windows-v141...
Compiler found: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe

Not sure how to force it to use VS2022, except uninstalling VS2019?

**Comment by bleze** [comment]
Nm, we had the toolsets mixed up. We should be using v142 and not v141. Will try that instead and see how it fares..

**Comment by bleze** [comment]
identity sdk builds with v142
