### ISSUE TITLE
[glib] build failure after #37473

### ISSUE THREAD

**Issue by AenBleidd** [microsoft/vcpkg#41478]
### Operating system

Linux

### Compiler

gcc

### Steps to reproduce the behavior

`./vcpkg install glib` on docker image (clean)

### Failure logs

```
Run-time dependency gobject-introspection-1.0 found: NO (tried pkgconfig and cmake)
```

When I tried to install on the docker container `libgirepository1.0-dev` I received another error:
```
<unknown>:: Warning: Gio: (Signal)run: argument source_object: Unresolved type: 'GObject'
```
Installing pip module `packaging` didn't help

### Additional context

Build log: https://github.com/BOINC/boinc/actions/runs/11264977672/job/31327567254

Happens after: #37473

**Comment by AenBleidd** [comment]
@WangWeiLin-MV, @dg0yt, please take a look

**Comment by WangWeiLin-MV** [comment]
> Build log: https://github.com/BOINC/boinc/actions/runs/11264977672/job/31327567254

Sorry I can't find where to view detailed build logs.

> `./vcpkg install glib` on docker image (clean)

And I cannot reproduce it in container `ubunt:latest`:

```sh
apt-get update

apt-get install -y git curl unzip zip
apt-get install -y cmake make autoconf automake libtool autoconf-archive pkgconf
apt-get install -y python3 python3-jinja2 nasm
apt-get install -y libxmu-dev libxi-dev libgl-dev libglvnd-dev
apt-get install -y g++

git clone --no-checkout https://github.com/microsoft/vcpkg
sh /vcpkg/bootstrap-vcpkg.sh

cd /vcpkg
./vcpkg install glib
```

Could you provide a reproducible steps script?

**Comment by dg0yt** [comment]
> `Run-time dependency gobject-introspection-1.0 found: NO (tried pkgconfig and cmake)`

There is a new `introspection` option which the port might want to turn off.

**Comment by AenBleidd** [comment]
@WangWeiLin-MV [snap_logs_x64_.zip](https://github.com/user-attachments/files/17339287/snap_logs_x64_.zip)

**Comment by WangWeiLin-MV** [comment]
@AenBleidd 

Could you help test this patch in your repro environment?

```diff
diff --git a/ports/glib/portfile.cmake b/ports/glib/portfile.cmake
index d1ca8968abe4ba..2aec3a1d0af346 100644
--- a/ports/glib/portfile.cmake
+++ b/ports/glib/portfile.cmake
@@ -50,6 +50,7 @@ vcpkg_configure_meson(
         ${OPTIONS}
         -Ddocumentation=false
         -Dinstalled_tests=false
+        -Dintrospection=disabled
         -Dlibelf=disabled
         -Dman-pages=disabled
         -Dtests=false
```

**Comment by AenBleidd** [comment]
@WangWeiLin-MV, yep, that helps: https://github.com/BOINC/boinc/actions/runs/11289586214/job/31399745339?pr=5844
Please proceed with the PR.
