### ISSUE TITLE
[Dcmtk] Error using vcpkg with VS2022

### ISSUE THREAD

**Issue by Jalg92** [microsoft/vcpkg#41499]
Hi, I tried to use Dcmtk in visual studio 2022. 

But theres some error in osconfig.h
I don't know what I have to do. 

The error is in the line 1137.

![Image](https://github.com/user-attachments/assets/5ecf6a70-b912-454f-8762-497f16d186c6)

**Comment by autoantwort** [comment]
I would guess you have to do the following: https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/

**Comment by Jalg92** [comment]
Thank you that was my problem.
