### ISSUE TITLE
Not able to build vcpkg.exe

### ISSUE THREAD

**Issue by kenr** [Microsoft/vcpkg#4149]
Machine: 
Windows 7 (x64)

When installing vcpkg with boostrap-vcpkg.bat, the attached error occur (with additional argument -verbose).

[2018-08-23 vcpkg.exe build error.txt](https://github.com/Microsoft/vcpkg/files/2314404/2018-08-23.vcpkg.exe.build.error.txt)

Let me know if more details are needed.

**Comment by degski** [comment]
Not helpful I know, but

    The imported project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\;\Microsoft.Cpp.Default.props" was not found.

obviously has a problem.

**Comment by Voskrese** [comment]
... `V140\;\Microsoft` ... ? What does the symbol `;`

**Comment by kenr** [comment]
@degski @Voskrese Yes, I saw that one, but I'm not sure where it is from.

**Comment by degski** [comment]
@kenr It's a separator in a path list, but somehow it ended up inside the (this particular) path, which in this case does seem to have quotes.

**Comment by kenr** [comment]
The -match statement in [scripts/cleanEnvironmentHelper.ps](https://github.com/Microsoft/vcpkg/blob/33286f90044465a11c2fc7e7a7d4b790c757bc01/scripts/cleanEnvironmentHelper.ps1#L20) matches any variable that contains path (like VCTargetsPath). I think the purpose here is to only merge user and machine environment variable if the variable name is exactly path.

Changing the match statement to ^path$ resolves this issue.

**Comment by LarryIII** [comment]
PR merged. So closed this issue!
