### ISSUE TITLE
lz4 error

### ISSUE THREAD

**Issue by TimurGaliev44** [microsoft/vcpkg#41500]
[lz4]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2FUsers%2F%D0%A2%D0%B8%D0%BC%D1%83%D1%80%20%D0%93%D0%B0%D0%BB%D0%B8%D0%B5%D0%B2%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
Win11 Pro
[config-x64-windows-err.log](https://github.com/user-attachments/files/17344474/config-x64-windows-err.log)
in logs nothing to see, please help if that possible

**Comment by TimurGaliev44** [comment]
-- Downloading https://github.com/lz4/lz4/archive/v1.10.0.tar.gz -> lz4-lz4-v1.10.0.tar.gz...

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: no such file or directory
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.


Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/lz4/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:192 (include)

**Comment by greenozon** [comment]
are you able to download the source archive by hands?

**Comment by greenozon** [comment]
I could successfully build this lib up, eg:

```
c:\Dev\vcpkg>vcpkg install lz4
Computing installation plan...
The following packages will be built and installed:
    lz4:x64-windows@1.10.0
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Dev/VS2019/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from C:\Users\user\AppData\Local\vcpkg\archives in 561 us. Use --debug to see more details.
Installing 1/1 lz4:x64-windows@1.10.0...
Building lz4:x64-windows@1.10.0...
-- Downloading https://github.com/lz4/lz4/archive/v1.10.0.tar.gz -> lz4-lz4-v1.10.0.tar.gz...
-- Cleaning sources at C:/Dev/vcpkg/buildtrees/lz4/src/v1.10.0-61bd08d80e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Dev/vcpkg/downloads/lz4-lz4-v1.10.0.tar.gz
-- Applying patch target-lz4-lz4.diff
-- Using source at C:/Dev/vcpkg/buildtrees/lz4/src/v1.10.0-61bd08d80e.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig file: C:/Dev/vcpkg/packages/lz4_x64-windows/lib/pkgconfig/liblz4.pc
-- Using cached msys2-mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.5.3-3-x86_64.pkg.tar.zst.
-- Using msys root at C:/Dev/vcpkg/downloads/tools/msys2/1e74ca60daa10104
-- Fixing pkgconfig file: C:/Dev/vcpkg/packages/lz4_x64-windows/debug/lib/pkgconfig/liblz4.pc
-- Installing: C:/Dev/vcpkg/packages/lz4_x64-windows/share/lz4/usage
-- Installing: C:/Dev/vcpkg/packages/lz4_x64-windows/share/lz4/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 163 ms.
Elapsed time to handle lz4:x64-windows: 8.8 s
lz4:x64-windows package ABI: 93a6a0317c1c941316ee2d17af416d8cc92b75c53a51990cdc64b07d6503ee58
Total install time: 8.8 s
lz4 provides CMake targets:

  find_package(lz4 CONFIG REQUIRED)
  target_link_libraries(main PRIVATE lz4::lz4)

lz4 provides pkg-config modules:

  liblz4
```

**Comment by TimurGaliev44** [comment]
> are you able to download the source archive by hands?

I'll try, but didn't understand how to add this library to vcpkg to load another library. If you can, please explain

**Comment by greenozon** [comment]
the thing is that if you put the downloaded libs into downloads\  dir inside vcpkg dir
it'll not try to download it, but instead use the existing one
but anyway, thats a manual work, so you should be able to get those libs from internet ...

**Comment by TimurGaliev44** [comment]
> the thing is that if you put the downloaded libs into downloads\ dir inside vcpkg dir it'll not try to download it, but instead use the existing one but anyway, thats a manual work, so you should be able to get those libs from internet ...

Thank you so mush
