### ISSUE TITLE
[ilmbase] Patch to remove "register" keyword from half.h?

### ISSUE THREAD

**Issue by malkia** [microsoft/vcpkg#4152]
ilmbase uses the deprecated 'register' storage class (for c++17), and compiler shows this as error:

c:\...\openexr\2.2.1-1\include\openexr\half.h(462): error C2220: warning treated as error - no 'object' file ...
c:\...\openexr\2.2.1-1\include\openexr\half.h(462): warning C5033: 'register' is no longer a supported storage class [c:\...some.vcxproj]

Obviously this could be fixed locally with pragma warning, or compiler message, but best would be if a patch diff file strips it. AFAIK, there would be no longer benefits of having it in there.

**Comment by yangjz1125** [comment]
It's right.
[look this](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4340)

**Comment by NancyLi1013** [comment]
Hi @malkia, thanks for posting this issue. The port openexr has been updated to 2.3.0. The keyword "register" has been removed from half.h now in the latest source code. Please refer to this commit to see the detail changes.
https://github.com/openexr/openexr/commit/6d297f35c5dbfacc8a5e94f33b986db7ab468db9#diff-20306efc2c74c325bb6525d1708a6e3e.
@yangjz1125, thanks for your clarification.
