### ISSUE TITLE
How dafux I make vcpkg shaddap bout Debug crt

### ISSUE THREAD

**Issue by RemoveRusky** [Microsoft/vcpkg#4154]
I'm trying to fix the qt5-base static build (and update it at the same time) but I'm getting error at install phase:

Expected Debug,Static crt linkage, but the following libs had invalid crt linkage:

    C:/vcpkg/packages/qt5-base_x64-windows-static/debug/lib/manual-link/Qt5Bootstrap.lib: Release,Static

Qt will Only build this file in release mode so how can I tell vcpkg to stop being a tard and ignore the crt of that file? I tried Applying #3861 but it's still bitching. What else can I do? I'm bout to drive to ms and harass Robert directly...

**Comment by ras0219-msft** [comment]
This issue has been resolved by moving the Qt5Bootstrap.lib into the tools directory (since it isn't intended for consumption outside the Qt build).
