### ISSUE TITLE
[tesseract] build failure

### ISSUE THREAD

**Issue by StarsHarryZhu** [microsoft/vcpkg#41559]
### Operating system

windows 10

### Compiler

MSVC

### Steps to reproduce the behavior

.\vcpkg install tesseract

### Failure logs

error: building tesseract:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle tesseract:x64-windows: 1.7 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+tesseract
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[tesseract]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2FUsers%2FAdministrator%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by JackBoosY** [comment]
Please provide failure logs, and full output.

**Comment by StarsHarryZhu** [comment]
it seems solved after i reinstalled MSVC. thank you for ur attention.

**Comment by JackBoosY** [comment]
@FrankXie05 can be closed.
