### ISSUE TITLE
python support for openvdb

### ISSUE THREAD

**Issue by githubkusi** [microsoft/vcpkg#4156]
I want to add the python wrappers for openvdb. I changed the corresponding variable in portfile.cmake from _off_ to _on_

    -DOPENVDB_BUILD_PYTHON_MODULE=ON

and added the necessary dependencies to the control file. Here's the added section in CONTROL

    Feature: python
    Description: Python wrapper for OpenVDB
    Build-Depends: python3, boost-python

When I install openvdb with the command

     vcpkg install openvdb[python]:x64-windows

I get the following error message:

        -- Found the following Boost libraries:
        --   iostreams
        --   system
        --   thread
        --   date_time
        --   regex
        --   chrono
        --   atomic
        -- Found Blosc: C:/work/openvdb/vcpkg/vcpkg/installed/x64-windows
        -- Found TBB: C:/work/openvdb/vcpkg/vcpkg/installed/x64-windows
        -- Found ZLIB: C:\work\openvdb\vcpkg\vcpkg\installed\x64-windows\lib\zlib.lib (found version "1.2.11")
        -- Found ILMBase: C:/work/openvdb/vcpkg/vcpkg/installed/x64-windows
        -- Found OpenEXR: C:/work/openvdb/vcpkg/vcpkg/installed/x64-windows
        -- Found OpenEXR v2.2 at C:/work/openvdb/vcpkg/vcpkg/installed/x64-windows
        CMake Warning (dev) at openvdb/CMakeLists.txt:129 (LINK_DIRECTORIES):
          This command specifies the relative path

            SYSTEM

          as a link directory.

          Policy CMP0015 is not set: link_directories() treats paths relative to the
          source dir.  Run "cmake --help-policy CMP0015" for policy details.  Use the
          cmake_policy command to set the policy and suppress this warning.
        This warning is for project developers.  Use -Wno-dev to suppress it.

        -- Found PythonInterp: C:/Python/Python36/python.exe (found version "3.6.6")
        -- Found PythonLibs: optimized;C:/work/vcpkg/installed/x64-windows/lib/python36.lib;debug;C:/work/vcpkg/installed/x64-windows/debug/lib/python36_d.lib (found version "3.6.4")
        CMake Error at C:/Program Files/CMake/share/cmake-3.12/Modules/FindBoost.cmake:2048 (message):
          Unable to find the requested Boost libraries.

          Boost version: 1.68.0

          Boost include path:
          C:/work/openvdb/vcpkg/vcpkg/installed/x64-windows/include

          Could not find the following Boost libraries:

                  boost_python

          No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
          directory containing Boost libraries or BOOST_ROOT to the location of
          Boost.

However, boost-python was correctly built and installed, along with the other boost dependencies. What do I need to change such that boost-python is recognized the same way as e.g boost-iostreams?

**Comment by AG89z** [comment]
Hello, any future update on this?

**Comment by dg0yt** [comment]
This issue is too old to be fixed for the versions reported.
