### ISSUE TITLE
Error on install openvdb[tools]

### ISSUE THREAD

**Issue by cgolchert** [Microsoft/vcpkg#4157]
I can install the openvdb libraries but when I try to install "openvdb[tools]" I get the error below:

Error: Building package openvdb:x64-windows failed with: BUILD_FAILED
  Package: openvdb:x64-windows
  Vcpkg version: 0.0.113-nohash

I have noticed that the vcpkg version of creates the problem discussed below:

>>...Both of those builds gave me linking errors with the undefined....openvdb::v5_X::util::INVALID_IDX.

> Make sure that OPENVDB_API is expanding out properly when you build both openvdb itself and when your code uses it. Examine the logic in Platform.h regarding how it is expanded and verify with #if checks around #error statements in the code.
> 
> In particular, for shared library builds, OPENVDB_DLL must be defined. Conversely, OPENVDB_DLL should NOT be defined if you're building and linking a static openvdb library. The other important macro here is OPENVDB_PRIVATE, which should be defined when building the library itself, and must be otherwise undefined.

Perhaps this is what the tools executables are hitting. (?)

**Comment by Cheney-W** [comment]
This issue should be fixed by PR:https://github.com/Microsoft/vcpkg/pull/6028, so close this issue.
