### ISSUE TITLE
Insufficient check when configuring autotools and cross compiling using clang on Linux

### ISSUE THREAD

**Issue by abique** [microsoft/vcpkg#41581]
Hi,

The following check is insufficient to detect cross compilation when using clang on Linux, because it only works with gcc.

https://github.com/microsoft/vcpkg/blob/3207386cc93121b907a8c5498a43b7a312f4f55d/scripts/cmake/vcpkg_configure_make.cmake#L402

How would you suggest to fix it?

Cheers,
Alex

**Comment by dg0yt** [comment]
Do you use a custom triplet file? Then put the desired options into `VCPKG_MAKE_BUILD_TRIPLET` in that file.

**Comment by abique** [comment]
Yes I use a custom triple and toolchain.
Thanks!
