### ISSUE TITLE
[SerialPort] build failure

### ISSUE THREAD

**Issue by code-horse** [microsoft/vcpkg#41590]
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

find_package(Qt5SerialPort REQUIRED)
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=F:\vcpkg\scripts\buildsystems\vcpkg.cmake ..

### Failure logs

CMake Error at F:/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package):
  Could not find a package configuration file provided by "Qt5SerialPort"
  with any of the following names:

    Qt5SerialPortConfig.cmake
    qt5serialport-config.cmake

  Add the installation prefix of "Qt5SerialPort" to CMAKE_PREFIX_PATH or set
  "Qt5SerialPort_DIR" to a directory containing one of the above files.  If
  "Qt5SerialPort" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  build/vcpkg_installed/x64-windows/share/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  F:/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  CMakeLists.txt:513 (find_package)

**Comment by FrankXie05** [comment]
@code-horse Currently, vcpkg does not export the usage of `SerialPort`, you may only be able to use msbuild.

**Comment by code-horse** [comment]
> [@code-horse](https://github.com/code-horse) Currently, vcpkg does not export the usage of `SerialPort`, you may only be able to use msbuild.[@code-horse](https://github.com/code-horse)目前vcpkg没有导出`SerialPort`的用法，你可能只能使用msbuild。



> [@code-horse](https://github.com/code-horse) Currently, vcpkg does not export the usage of `SerialPort`, you may only be able to use msbuild.

Is there any way to add it manually? The project is now compiled using vcpkg for convenience.

**Comment by code-horse** [comment]
> [@code-horse](https://github.com/code-horse) Currently, vcpkg does not export the usage of `SerialPort`, you may only be able to use msbuild.

Is there any way to add it manually? The project is now compiled using vcpkg for convenience.

**Comment by FrankXie05** [comment]
You can add this port manually and submit a PR to vcpkg. Refer to https://learn.microsoft.com/en-us/vcpkg/get_started/get-started-adding-to-registry?pivots=shell-powershell

**Comment by dg0yt** [comment]
@FrankXie05 This issue is for port `qt5-serialport`.

**Comment by FrankXie05** [comment]
@code-horse Sorry, `qt5-serialport` does not have a way to export cmake now. You can use msbuild to use `qt5-serialport`. :)

**Comment by dg0yt** [comment]
Or you read the Qt5 CMake documentation:  https://doc.qt.io/qt-5/cmake-manual.html

~~~cmake
find_package(Qt5 COMPONENTS SerialPort REQUIRED)
~~~

**Comment by code-horse** [comment]
Thank you all,I use QT cmake can solve the issue.
