### ISSUE TITLE
build all libs failure

### ISSUE THREAD

**Issue by zhlongfj** [microsoft/vcpkg#41591]
### Operating system

Windows10

### Compiler

MSVC

### Steps to reproduce the behavior

vcpkg install libiconv

### Failure logs

[build-x64-windows-dbg-err.log](https://github.com/user-attachments/files/17393218/build-x64-windows-dbg-err.log)
[build-x64-windows-dbg-out.log](https://github.com/user-attachments/files/17393214/build-x64-windows-dbg-out.log)
[build-x64-windows-rel-err.log](https://github.com/user-attachments/files/17393216/build-x64-windows-rel-err.log)
[build-x64-windows-rel-out.log](https://github.com/user-attachments/files/17393219/build-x64-windows-rel-out.log)
[cmake-vars-x64-windows.cmake.log](https://github.com/user-attachments/files/17393217/cmake-vars-x64-windows.cmake.log)
[cmake-vars-x64-windows-dbg.cmake.log](https://github.com/user-attachments/files/17393215/cmake-vars-x64-windows-dbg.cmake.log)
[cmake-vars-x64-windows-rel.cmake.log](https://github.com/user-attachments/files/17393220/cmake-vars-x64-windows-rel.cmake.log)
[config-x64-windows-dbg-config.log](https://github.com/user-attachments/files/17393223/config-x64-windows-dbg-config.log)
[config-x64-windows-dbg-err.log](https://github.com/user-attachments/files/17393226/config-x64-windows-dbg-err.log)
[config-x64-windows-dbg-out.log](https://github.com/user-attachments/files/17393222/config-x64-windows-dbg-out.log)
[config-x64-windows-rel-config.log](https://github.com/user-attachments/files/17393224/config-x64-windows-rel-config.log)
[config-x64-windows-rel-err.log](https://github.com/user-attachments/files/17393221/config-x64-windows-rel-err.log)
[config-x64-windows-rel-out.log](https://github.com/user-attachments/files/17393225/config-x64-windows-rel-out.log)
[build-x64-windows-rel-err.log](https://github.com/user-attachments/files/17393233/build-x64-windows-rel-err.log)
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: F:/git/vcpkg/downloads/tools/msys2/212eb2bc95cd8a82/usr/bin/make.exe -j 17 --trace -f Makefile all
    Working Directory: F:/git/vcpkg/buildtrees/libiconv/x64-windows-rel/
    See logs for more information:
      F:\git\vcpkg\buildtrees\libiconv\build-x64-windows-rel-out.log
      F:\git\vcpkg\buildtrees\libiconv\build-x64-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:136 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:2 (vcpkg_build_make)
  ports/libiconv/portfile.cmake:39 (vcpkg_install_make)
  scripts/ports.cmake:192 (include)

error: building libiconv:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle libiconv:x64-windows: 30 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libiconv
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[libiconv]+Build+error+on+x64-windows&body=Copy+issue+body+from+F%3A%2Fgit%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

build-x64-windows-rel-err.log:
make[2]: *** [Makefile:55: libcharset.la] Error 127
make[1]: *** [Makefile:34: all] Error 2
make: *** [Makefile:41: lib/localcharset.h] Error 2

**Comment by greenozon** [comment]
Tried fresh bits 
```
git pull

```

and can't see the issues...

<details><summary>Details</summary>
<p>

c:\Dev\vcpkg>vcpkg install libiconv
Computing installation plan...
The following packages will be built and installed:
    libiconv:x64-windows@1.17#4
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Dev/VS2019/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
A suitable version of 7zip was not found (required v24.8.0).
Downloading https://github.com/ip7z/7zip/releases/download/24.08/7z2408-extra.7z
Extracting 7zip...
A suitable version of 7zr was not found (required v24.8.0).
Downloading https://github.com/ip7z/7zip/releases/download/24.08/7zr.exe
Restored 0 package(s) from C:\Users\user\AppData\Local\vcpkg\archives in 10.1 ms. Use --debug to see more details.
Installing 1/1 libiconv:x64-windows@1.17#4...
Building libiconv:x64-windows@1.17#4...
-- Using cached libiconv-1.17.tar.gz.
-- Cleaning sources at C:/Dev/vcpkg/buildtrees/libiconv/src/v1.17-84a471678e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Dev/vcpkg/downloads/libiconv-1.17.tar.gz
-- Applying patch 0002-Config-for-MSVC.patch
-- Applying patch 0003-Add-export.patch
-- Applying patch 0004-ModuleFileName.patch
-- Applying patch clang-fortify.patch
-- Using source at C:/Dev/vcpkg/buildtrees/libiconv/src/v1.17-84a471678e.clean
-- Getting CMake variables for x64-windows
-- Using cached msys2-autoconf-wrapper-20221207-1-any.pkg.tar.zst.
-- Using cached msys2-automake-wrapper-20221207-2-any.pkg.tar.zst.
-- Using cached msys2-binutils-2.42-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libtool-2.4.7-3-x86_64.pkg.tar.zst.
-- Using cached msys2-make-4.4.1-2-x86_64.pkg.tar.zst.
-- Using cached msys2-pkgconf-2.1.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-which-2.21-4-x86_64.pkg.tar.zst.
-- Using cached msys2-bash-5.2.026-1-x86_64.pkg.tar.zst.
-- Using cached msys2-coreutils-8.32-5-x86_64.pkg.tar.zst.
-- Using cached msys2-file-5.45-1-x86_64.pkg.tar.zst.
-- Using cached msys2-gawk-5.3.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-grep-1~3.0-6-x86_64.pkg.tar.zst.
-- Using cached msys2-gzip-1.13-1-x86_64.pkg.tar.zst.
-- Using cached msys2-diffutils-3.10-1-x86_64.pkg.tar.zst.
-- Using cached msys2-sed-4.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.5.3-3-x86_64.pkg.tar.zst.
-- Using cached msys2-autoconf2.71-2.71-3-any.pkg.tar.zst.
-- Using cached msys2-automake1.16-1.16.5-1-any.pkg.tar.zst.
-- Using cached msys2-libiconv-1.17-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libintl-0.22.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-zlib-1.3.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-tar-1.35-2-x86_64.pkg.tar.zst.
-- Using cached msys2-findutils-4.10.0-2-x86_64.pkg.tar.zst.
-- Using cached msys2-gmp-6.3.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-gcc-libs-13.3.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libbz2-1.0.8-4-x86_64.pkg.tar.zst.
-- Using cached msys2-liblzma-5.6.2-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libzstd-1.5.6-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libreadline-8.2.010-1-x86_64.pkg.tar.zst.
-- Using cached msys2-mpfr-4.2.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libpcre-8.45-4-x86_64.pkg.tar.zst.
-- Using cached msys2-m4-1.4.19-2-x86_64.pkg.tar.zst.
-- Using cached msys2-perl-5.38.2-2-x86_64.pkg.tar.zst.
-- Using cached msys2-ncurses-6.5-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libxcrypt-4.4.36-1-x86_64.pkg.tar.zst.
-- Using msys root at C:/Dev/vcpkg/downloads/tools/msys2/212eb2bc95cd8a82
-- Using cached msys2-mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.5.3-3-x86_64.pkg.tar.zst.
-- Using msys root at C:/Dev/vcpkg/downloads/tools/msys2/1e74ca60daa10104
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
-- Installing x64-windows-dbg
-- Building x64-windows-rel
-- Installing x64-windows-rel
-- Installing: C:/Dev/vcpkg/packages/libiconv_x64-windows/share/libiconv/usage
-- Performing post-build validation
Stored binaries in 1 destinations in 218 ms.
Elapsed time to handle libiconv:x64-windows: 4.3 min
libiconv:x64-windows package ABI: e0f72739bfa73562af051887ad07e094daa9197c31c33634fcc1796d7638b382
Total install time: 4.3 min
The package libiconv provides CMake targets:

    find_package(Iconv)
    target_link_libraries(main PRIVATE Iconv::Iconv)



</p>
</details> 


Please try to use English Language Pack, eg: https://github.com/microsoft/vcpkg/issues/40377#issuecomment-2283490304

**Comment by jimwang118** [comment]
Sorry, I cannot reproduce this issue locally. Please update `vcpkg` to the latest version, install the VS English language pack and then reinstall.

**Comment by zhlongfj** [comment]
> Sorry, I cannot reproduce this issue locally. Please update `vcpkg` to the latest version, install the VS English language pack and then reinstall.

**Comment by zhlongfj** [comment]
> Tried fresh bits
> 
> ```
> git pull
> bootstrap-vcpkg.bat
> ```
> 
> and can't see the issues...
> 
> Details
> Please try to use English Language Pack, eg: [#40377 (comment)](https://github.com/microsoft/vcpkg/issues/40377#issuecomment-2283490304)

It's ok now.

**Comment by zhlongfj** [comment]
> Tried fresh bits
> 
> ```
> git pull
> bootstrap-vcpkg.bat
> ```
> 
> and can't see the issues...
> 
> Details
> Please try to use English Language Pack, eg: [#40377 (comment)](https://github.com/microsoft/vcpkg/issues/40377#issuecomment-2283490304)

It's ok now. thks
