### ISSUE TITLE
[pcl] pcl[surface-on-nurbs] build failure

### ISSUE THREAD

**Issue by Bzz2745** [microsoft/vcpkg#41592]
### Operating system

Windows11

### Compiler

MSVC vc143

### Steps to reproduce the behavior

`vcpkg install  pcl[apps,cuda,openni2,qt,simulation,surface-on-nurbs,tools,visualization,vtk]`

### Failure logs

Installing 1/1 pcl[apps,core,cuda,opengl,openni2,qt,simulation,surface-on-nurbs,tools,visualization,vtk]:x64-windows@1.14.1#1...
Building pcl[apps,core,cuda,opengl,openni2,qt,simulation,surface-on-nurbs,tools,visualization,vtk]:x64-windows@1.14.1#1...
-- Using cached PointCloudLibrary-pcl-pcl-1.14.1.tar.gz.
-- Extracting source C:/Users/user/opt/vcpkg/downloads/PointCloudLibrary-pcl-pcl-1.14.1.tar.gz
-- Applying patch add-gcc-version-check.patch
-- Applying patch fix-check-sse.patch
-- Applying patch fix-numeric-literals-flag.patch
-- Applying patch install-layout.patch
-- Applying patch install-examples.patch
-- Applying patch fix-clang-cl.patch
-- Applying patch gh-5985-inline.patch
-- Applying patch io_ply.patch
-- Using source at C:/Users/user/opt/vcpkg/buildtrees/pcl/src/pcl-1.14.1-9b54503ead.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/Users/user/scoop/apps/cmake/3.30.5/bin/cmake.exe --build . --config Release --target install -- -v -j13
    Working Directory: C:/Users/user/opt/vcpkg/buildtrees/pcl/x64-windows-rel
    See logs for more information:
      C:\Users\user\opt\vcpkg\buildtrees\pcl\install-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/pcl/portfile.cmake:77 (vcpkg_cmake_install)
  scripts/ports.cmake:192 (include)

### Additional context

[install-x64-windows-rel-out.log](https://github.com/user-attachments/files/17393271/install-x64-windows-rel-out.log)

**Comment by dg0yt** [comment]
Not a port bug.
~~~
C:\Users\user\opt\vcpkg\buildtrees\pcl\src\pcl-1.14.1-9b54503ead.clean\surface\src\3rdparty\opennurbs\opennurbs_lookup.cpp(675) : fatal error C1001: Internal compiler error.
(compiler file 'D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 247)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com 
Please choose the Technical Support command on the Visual C++ 
 Help menu, or open the Technical Support help file for more information
  cl!RaiseException()+0x6c
  cl!RaiseException()+0x6c
  cl!InvokeCompilerPass()+0x25f
  cl!InvokeCompilerPassW()+0x14607b
  cl!CloseTypeServerPDB()+0x209c9
  cl!CloseTypeServerPDB()+0x24924
  cl!CloseTypeServerPDB()+0x2386d
  cl!InvokeCompilerPassW()+0x6b80b
  cl!recalloc()+0xa3
  cl!BaseThreadInitThunk()+0x1d
  cl!RtlUserThreadStart()+0x28
~~~
