### ISSUE TITLE
Error on install opencv[contrib]:x86-uwp --recursive

### ISSUE THREAD

**Issue by edsilv** [microsoft/vcpkg#4160]
I'm following this guide for Windows Mixed Reality Spectator View on Windows 10: https://github.com/Microsoft/MixedRealityToolkit/tree/master/SpectatorViewPlugin

On running `.\vcpkg install opencv[contrib]:x86-uwp --recurse` I'm getting 

```
Error: Building package opencv:x86-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv:x86-uwp
  Vcpkg version: 0.0.113-nohash
```

Here's the log: https://gist.github.com/edsilv/310d7c81c5b3f297ce8a963b9dc97b4a

**Comment by ras0219-msft** [comment]
Hi @edsilv, thanks for posting this issue!

Could you try installing VS2017 community and re-running the build? I notice the error message is from inside `vccorlib.h` for 2015, so perhaps this can be easily fixed by upgrading VS.

**Comment by numerouno979** [comment]
It does not work with VS2017 as well.
Here are the details of the issue that i faced with VS2017.
Do we need to install some package in VS?

**Env Details:**
- win 10 OS, 
- VS Community edition 2017 (v 15.7.6) 

**Steps to replicate:**
1) Open a command prompt with admin access, cd to intended location
2) git clone https://github.com/Microsoft/vcpkg
3) cd vcpkg
4) .\bootstrap-vcpkg.bat
5) .\vcpkg integrate install
6) .\vcpkg install opencv[contrib]:x86-uwp --recurse

**Error Details (on command prompt):**
Error: Building package eigen3:x86-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: eigen3:x86-uwp
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

**Error Details (as in log files) :**

Build started 18-03-2019 13:54:48.

Project "${INSTAL_LOCATION}\vcpkg\buildtrees\eigen3\x86-uwp-rel\CMakeFiles\CMakeTmp\cmTC_4e4c3.vcxproj" on node 1 (default targets).

C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(2128,3): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\Microsoft\WindowsXaml\v15.0\Microsoft.Windows.UI.Xaml.Cpp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [${INSTAL_LOCATION}\vcpkg\buildtrees\eigen3\x86-uwp-rel\CMakeFiles\CMakeTmp\cmTC_4e4c3.vcxproj]

Done Building Project "${INSTAL_LOCATION}\vcpkg\buildtrees\eigen3\x86-uwp-rel\CMakeFiles\CMakeTmp\cmTC_4e4c3.vcxproj" (default targets) -- FAILED.

Build FAILED.

"${INSTAL_LOCATION}\vcpkg\buildtrees\eigen3\x86-uwp-rel\CMakeFiles\CMakeTmp\cmTC_4e4c3.vcxproj" (default target) (1) ->

  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(2128,3): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\Microsoft\WindowsXaml\v15.0\Microsoft.Windows.UI.Xaml.Cpp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [${INSTAL_LOCATION}\vcpkg\buildtrees\eigen3\x86-uwp-rel\CMakeFiles\CMakeTmp\cmTC_4e4c3.vcxproj]

    0 Warning(s)

    1 Error(s)



Time Elapsed 00:00:00.52
