### ISSUE TITLE
[CGAL] update to 6.0

### ISSUE THREAD

**Issue by stripe2933** [microsoft/vcpkg#41608]
### Library name

CGAL

### New version number

6.0

### Other information that may be useful (release notes, etc...)

[GitHub Releases](https://github.com/CGAL/cgal/releases)

Notable changes:

- Requires a C++ compiler with the support of C++17 or later
- GMP/MPFR are no longer mandatory
- `boost::variant` and `boost::optional` are replaced to `std::variant` and `std::optional` in [2D and 3D Linear Geometry Kernel](https://doc.cgal.org/6.0/Manual/packages.html#PkgKernel23) (maybe could reduce the boost dependencies?)

**Comment by JonLiu1993** [comment]
Fixed by PR #41300
