### ISSUE TITLE
init vcpkg error

### ISSUE THREAD

**Issue by WangHHY19931001** [microsoft/vcpkg#41628]
env:
版本	Windows 10 专业版
版本号	22H2
安装日期	‎2022/‎10/‎23
操作系统内部版本	19045.5011
体验	Windows Feature Experience Pack 1000.19060.1000.0
cmd:
.\bootstrap-vcpkg.bat
cmd out:
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2024-09-30/vcpkg.exe -> C:\vcpkg\vcpkg.exe... done.
Validating signature... failed! 0x800B0100 Deleted!

**Comment by FrankXie05** [comment]
Please see #30604 for how to report an issue.
