### ISSUE TITLE
[intel-mkl] INTEL MKL ERROR: The specified module could not be found. mkl_avx512.2.dll. Intel MKL FATAL ERROR: Cannot load mkl_avx512.2.dll or mkl_def.2.dll.

### ISSUE THREAD

**Issue by aboelens** [microsoft/vcpkg#41627]
**Describe the bug**
I compile my code against the intel-mkl port. Compiling and linking works fine, but when running my unit tests I get the error:

INTEL MKL ERROR: The specified module could not be found. mkl_avx512.2.dll. Intel 
MKL FATAL ERROR: Cannot load mkl_avx512.2.dll or mkl_def.2.dll.

Copying the dll mkl_def.2.dll to the location of my executable solves the issue. Could this dll be installed automatically, like libiomp5md.dll, mkl_core.2.dll, and mkl_intel_thread.2.dll?

**Environment**
- OS: Windows 10
- Compiler: msvc 

**To Reproduce**
1. ./vcpkg install intel-mkl
2. See error when running code

INTEL MKL ERROR: The specified module could not be found. mkl_avx512.2.dll. Intel 
MKL FATAL ERROR: Cannot load mkl_avx512.2.dll or mkl_def.2.dll.

**Expected behavior**
I would expect mkl_def.2.dll to be installed automatically, 

**Failure logs**
-(please attached failure logs)

**Additional context**

**Comment by dg0yt** [comment]
> INTEL MKL ERROR: The specified module could not be found. mkl_avx512.2.dll. Intel

Given the literals "module" and "mkl_avx512.2.dll", I would guess that this DLL is not a linked lib (which can be discovered easily) but a plugin. There is no generic mechanism to copy plugins.
