### ISSUE TITLE
[asio] Build error on x64-linux

### ISSUE THREAD

**Issue by Aniganesh** [microsoft/vcpkg#41624]
Package: asio:x64-linux@1.30.2

**Host Environment**

- Host: x64-linux
- Compiler: GNU 11.4.0
-    vcpkg-tool version: 2024-09-30-ab8988503c7cffabfd440b243a383c0a352a023d
    vcpkg-scripts version: 111220b3c 2021-07-17 (3 years, 3 months ago)

**To Reproduce**

`vcpkg install `

**Failure logs**

```
-- Using /home/aniruddha/.local/bin/vcpkg/downloads/chriskohlhoff-asio-asio-1-30-2.tar.gz
-- Cleaning sources at /home/aniruddha/.local/bin/vcpkg/buildtrees/asio/src/sio-1-30-2-504a65d4d1.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/aniruddha/.local/bin/vcpkg/downloads/chriskohlhoff-asio-asio-1-30-2.tar.gz
-- Using source at /home/aniruddha/.local/bin/vcpkg/buildtrees/asio/src/sio-1-30-2-504a65d4d1.clean
CMake Error at /home/aniruddha/Learning progress/C++/code-crafters-redis-cpp/vcpkg_installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:48 (vcpkg_list):
  Unknown CMake command "vcpkg_list".
Call Stack (most recent call first):
  /home/aniruddha/.cache/vcpkg/registries/git-trees/17ce1a2d17d0cb0d50eb72c89a9e51f472ef31f4/portfile.cmake:16 (vcpkg_cmake_configure)
  scripts/ports.cmake:140 (include)



```

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "dependencies": [
    "asio",
    "pthreads"
  ]
}

```
</details>

**Comment by dg0yt** [comment]
> vcpkg-scripts version: [111220b](https://github.com/microsoft/vcpkg/commit/111220b3cf3311744369425d5c323a0f17941076) 2021-07-17 (3 years, 3 months ago)

Fast forward, please.

**Comment by Aniganesh** [comment]
How do I update to the latest vcpkg-scripts version? 
I cloned this repo and ran bootstrap-vcpkg.sh with telemetry disabled. Running `git pull` says it is already up to date. So I'm not sure which repo to fast forward on.

**Comment by dg0yt** [comment]
> -- Using /home/aniruddha/.local/bin/vcpkg/downloads/chriskohlhoff-asio-asio-1-30-2.tar.gz
> -- Cleaning sources at /home/aniruddha/.local/bin/vcpkg/buildtrees/asio/src/sio-1-30-2-504a65d4d1.clean. Use --editable to skip cleaning for the packages you specify.
> -- Extracting source /home/aniruddha/.local/bin/vcpkg/downloads/chriskohlhoff-asio-asio-1-30-2.tar.gz
> -- Using source at /home/aniruddha/.local/bin/vcpkg/buildtrees/asio/src/sio-1-30-2-504a65d4d1.clean

I guess that `vcpkg install` runs a modified, outdated, distro-provided vcpkg instance.
Use the actual path to the vcpkg binary in your git checkout instead.

**Comment by Aniganesh** [comment]
Thanks for your help @dg0yt . Running `whereis vcpkg` and updating that fixed my issue. Closing this issue.
