### ISSUE TITLE
[openssl] Build error on x64-windows

### ISSUE THREAD

**Issue by Vorovan** [microsoft/vcpkg#41664]
[issue_body.md](https://github.com/user-attachments/files/17445350/issue_body.md)

**Comment by greenozon** [comment]
I guess some tools does not like your username (non-English letters)

```
C:\Users\Äåíèñ\AppData\Local\vcpkg
```

Suggesting use another directory, that does not include user name

**Comment by MonicaLiu0311** [comment]
Do not use non-ASCII characters or spaces in the path.

**Comment by MonicaLiu0311** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
