### ISSUE TITLE
Google Test (gtest) package missing gmock target

### ISSUE THREAD

**Issue by kreuzerkrieg** [microsoft/vcpkg#4167]
Looks like when `gtest` package provides `GTest::GTest` and `GTest::Main` linkage macros it missing the `gmock` despite the library is shipped with package.

Linux, Ubuntu 18.04, CMake 3.9, GCC 7.3

**Comment by HarryDC** [comment]
I am seeing a similar issue under windows VS 2017, no targets defined for gmock and the library can't be found

**Comment by kreuzerkrieg** [comment]
For me, working around with `FIND_LIBRARY(GOOGLE_MOCK gmock)` solved the problem, however as I said it is a workaround, not a solution

**Comment by coryan** [comment]
Note that `GTest::GTest` and `GTest::Main` are the names given to the libraries by the `FindGTest` module distributed with CMake, while the file installed by google test calls the libraries (last time I checked) `GTest::gtest` , `GTest::gtest_main`, `GTest::gmock`, and `GTest::gmock_main`.

**Comment by JackBoosY** [comment]
Hi @kreuzerkrieg . thanks for reporting this issue!
I've added gmock into gtest and fixed gmock target. Please update vcpkg and rebuild gtest.

Thanks.
