### ISSUE TITLE
[pango] Build error on x64-linux using cross compilation

### ISSUE THREAD

**Issue by ha-mximaging** [microsoft/vcpkg#41675]
Configure CMake cache with the following error:

1> [CMake] Building pango:x64-linux@1.54.0...
1> [CMake] ...../.cache/vcpkg/registries/git-trees/ac54330a51296954a9479f950666df455bffb07a: info: installing overlay port from here
1> [CMake] -- Found Python version '3.10.12 at /usr/bin/python3'
1> [CMake] -- Using meson: .../.vcpkg/downloads/tools/meson-1.5.2-dd4692/meson.py
1> [CMake] -- Downloading https://gitlab.gnome.org//GNOME/pango/-/archive/1.54.0/pango-1.54.0.tar.gz -> GNOME-pango-1.54.0.tar.gz...
1> [CMake] [DEBUG] To include the environment variables in debug output, pass --debug-env
1> [CMake] [DEBUG] Disabling metrics because vcpkg.disable-metrics exists
1> [CMake] [DEBUG] Trying to load bundleconfig from ..../vcpkg/vcpkg-bundle.json
1> [CMake] [DEBUG] Failed to open: ...../vcpkg/vcpkg-bundle.json
1> [CMake] [DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
1> [CMake] [DEBUG] Feature flag 'binarycaching' unset
1> [CMake] [DEBUG] Feature flag 'compilertracking' unset
1> [CMake] [DEBUG] Feature flag 'registries' unset
1> [CMake] [DEBUG] Feature flag 'versions' unset
1> [CMake] [DEBUG] Feature flag 'dependencygraph' unset
1> [CMake] [DEBUG] 1000: execute_process(curl --fail -L https://gitlab.gnome.org//GNOME/pango/-/archive/1.54.0/pango-1.54.0.tar.gz --create-dirs --output ----/vcpkg/downloads/GNOME-pango-1.54.0.tar.gz.15724.part)
1> [CMake] [DEBUG] 1000: cmd_execute_and_stream_data() returned 22 after   293039 us
1> [CMake] error: Missing GNOME-pango-1.54.0.tar.gz and downloads are blocked by x-block-origin.
1> [CMake] error: https://gitlab.gnome.org//GNOME/pango/-/archive/1.54.0/pango-1.54.0.tar.gz: curl failed to download with exit code 22
1> [CMake]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
1> [CMake]                                  Dload  Upload   Total   Spent    Left  Speed
1> [CMake] 
1> [CMake] curl: (22) The requested URL returned error: 503
1> [CMake] 
1> [CMake] [DEBUG] /source/src/vcpkg/base/downloads.cpp(1030): 
1> [CMake] [DEBUG] Time in subprocesses: 293039us
1> [CMake] [DEBUG] Time in parsing JSON: 5us
1> [CMake] [DEBUG] Time in JSON reader: 0us
1> [CMake] [DEBUG] Time in filesystem: 39us
1> [CMake] [DEBUG] Time in loading ports: 0us
1> [CMake] [DEBUG] Exiting after 293 ms (293451us)
1> [CMake] 
1> [CMake] CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
1> [CMake]       
1> [CMake]       Failed to download file with error: 1
1> [CMake]       If you are using a proxy, please check your proxy setting. Possible causes are:
1> [CMake]       
1> [CMake]       1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
1> [CMake]          to `https://address:port`. This is not correct, because `https://` prefix
1> [CMake]          claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
1> [CMake]          , etc..) is an HTTP proxy. Try setting `http://address:port` to both
1> [CMake]          HTTP_PROXY and HTTPS_PROXY instead.
1> [CMake]       
1> [CMake]       2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
1> [CMake]          set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
1> [CMake]          The value set by your proxy might be wrong, or have same `https://` prefix issue.
1> [CMake]       
1> [CMake]       3. Your proxy's remote server is out of service.
1> [CMake]       
1> [CMake]       If you've tried directly download the link, and believe this is not a temporary
1> [CMake]       download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
1> [CMake]       to report this upstream download server failure.
1> [CMake]       
1> [CMake] 
1> [CMake] Call Stack (most recent call first):
1> [CMake]   scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
1> [CMake]   scripts/cmake/vcpkg_from_gitlab.cmake:113 (vcpkg_download_distfile)
1> [CMake]   ....../.cache/vcpkg/registries/git-trees/ac54330a51296954a9479f950666df455bffb07a/portfile.cmake:2 (vcpkg_from_gitlab)
1> [CMake]   scripts/ports.cmake:192 (include)
1> [CMake] error: building pango:x64-linux failed with: BUILD_FAILED

**Comment by awaisali88** [comment]
I am having this same issue. 

The gitlab gnome links seems to be down

https://gitlab.gnome.org//GNOME/pango/-/archive/1.54.0/pango-1.54.0.tar.gz

**Comment by awaisali88** [comment]
The link is not working and the build is working now.
