### ISSUE TITLE
Thrift package does not install executable

### ISSUE THREAD

**Issue by kreuzerkrieg** [Microsoft/vcpkg#4171]
Ubuntu 18.04
I expect to have the `thrift` executable in the installed/x64-linux/tools/thrift folder, the same manner as google protobuffer installs the `protoc` in the installed/x64-linux/tools/protobuf
Looks like it is the right behavior to expect, right?

**Comment by markaren** [comment]
Seems the portfile only copys the executable on Windows. But anyway, you should probably build the compiler yourself using the latest stable version (0.11.0) to ensure cross-language compability.  vcpkg seems to use distribute development builds of thrift. For instance, generated java code cannot be compiled using 0.11.0 which you would use in your Java project.

**Comment by kreuzerkrieg** [comment]
>>  vcpkg seems to distribute development builds of thrift
isnt it a bad idea?

**Comment by markaren** [comment]
> isnt it a bad idea?

I dunno. They target the master branch. But it's not 0.11.0.
But I have not faced any issues yet. I use the 0.11.0 compiler to generate python, java, javascript and c++ source files. The C++ python, java and javascript clients are able to speak to the C++ server just fine. Also the C++ clietn can talk to the Java server.

**Comment by kreuzerkrieg** [comment]
IMHO such a packaging practice may lead to extremely brittle artifacts
