### ISSUE TITLE
[libusb] Build error on arm64-linux

### ISSUE THREAD

**Issue by bingbingshu** [microsoft/vcpkg#41726]
error: building libusb:arm64-linux failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle libusb:arm64-linux: 12 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libusb
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[libusb]+Build+error+on+arm64-linux&body=Copy+issue+body+from+%2Fdata%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by FrankXie05** [comment]
Please see #30604 for how to report an issue.
