### ISSUE TITLE
[libjpeg-turbo] Build error on x64-windows

### ISSUE THREAD

**Issue by iladesio** [microsoft/vcpkg#41757]
Host: x64-windows
C/C++ Optimizing Compiler Version 19.41.34123 for x86
cmake version 3.29.5-msvc4
vcpkg package management program version 2024-06-10-02590c430e4ed9215d27870138c2e579cc338772

when I run the command "vcpkg install"

Failure Logs:
```
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe
The following packages will be built and installed:
  * flatbuffers:x64-windows@24.3.25 -- C:\Users\Ilaria\AppData\Local\vcpkg\registries\git-trees\f8e85b45608b4005d8e8b4a96cfe11a5c2686e92
  * libjpeg-turbo:x64-windows@3.0.2 -- C:\Users\Ilaria\AppData\Local\vcpkg\registries\git-trees\6d061c71a48ca2abff5cf471f77ef14d7222aa52
  * libpng:x64-windows@1.6.43#2 -- C:\Users\Ilaria\AppData\Local\vcpkg\registries\git-trees\915cc8e8e0adbfb2708a310635217811a849d709
    opencv[core,default-features]:x64-windows@4.8.0#1 -- C:\Users\Ilaria\AppData\Local\vcpkg\registries\git-trees\bc3a2d25b8cca6c318cdd710381ca152b18ae3cd
  * opencv4[core,default-features,dnn,jpeg,png,quirc,tiff,webp]:x64-windows@4.8.0#19 -- C:\Users\Ilaria\AppData\Local\vcpkg\registries\git-trees\85685a5e45ef916a21769da98c8346462ef179d0
  * protobuf:x64-windows@3.21.12#3 -- C:\Users\Ilaria\AppData\Local\vcpkg\registries\git-trees\528c56d9b29635d840b284f3e2109a370556bd89
  * quirc:x64-windows@1.2 -- C:\Users\Ilaria\AppData\Local\vcpkg\registries\git-trees\f586c894573b92fc601590eb0e38b3e54e0c7f5c
  * tiff[core,jpeg,lzma,zip]:x64-windows@4.6.0#4 -- C:\Users\Ilaria\AppData\Local\vcpkg\registries\git-trees\9aa03ccc8de52590c49943ca462d6f833d0a9118
  * vcpkg-get-python-packages:x64-windows@2024-01-24 -- C:\Users\Ilaria\AppData\Local\vcpkg\registries\git-trees\9205135e78e0cad47fd43c2f7abada1f4fbbdbaa
Additional packages (*) will be modified to complete this operation.
Restored 0 package(s) from C:\Users\Ilaria\AppData\Local\vcpkg\archives in 117 us. Use --debug to see more details.
Installing 1/9 libjpeg-turbo:x64-windows@3.0.2...
Building libjpeg-turbo:x64-windows@3.0.2...
C:\Users\Ilaria\AppData\Local\vcpkg\registries\git-trees\6d061c71a48ca2abff5cf471f77ef14d7222aa52: info: installing overlay port from here
-- Using cached libjpeg-turbo-libjpeg-turbo-3.0.2.tar.gz.
-- Cleaning sources at C:/Users/Ilaria/Desktop/Thesis/Project-Varjo-stream-main/VarjoCommunicationFramework-main/VarjoApp/examples/vcpkg_installed/vcpkg/blds/libjpeg-turbo/src/3.0.2-c04fb0ca25.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Ilaria/AppData/Local/vcpkg/downloads/libjpeg-turbo-libjpeg-turbo-3.0.2.tar.gz
-- Applying patch add-options-for-exes-docs-headers.patch
-- Applying patch workaround_cmake_system_processor.patch
-- Using source at C:/Users/Ilaria/Desktop/Thesis/Project-Varjo-stream-main/VarjoCommunicationFramework-main/VarjoApp/examples/vcpkg_installed/vcpkg/blds/libjpeg-turbo/src/3.0.2-c04fb0ca25.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/Users/Ilaria/Desktop/Thesis/Project-Varjo-stream-main/VarjoCommunicationFramework-main/VarjoApp/examples/vcpkg_installed/vcpkg/blds/libjpeg-turbo/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\Ilaria\Desktop\Thesis\Project-Varjo-stream-main\VarjoCommunicationFramework-main\VarjoApp\examples\vcpkg_installed\vcpkg\blds\libjpeg-turbo\config-x64-windows-dbg-CMakeCache.txt.log
      C:\Users\Ilaria\Desktop\Thesis\Project-Varjo-stream-main\VarjoCommunicationFramework-main\VarjoApp\examples\vcpkg_installed\vcpkg\blds\libjpeg-turbo\config-x64-windows-rel-CMakeCache.txt.log
      C:\Users\Ilaria\Desktop\Thesis\Project-Varjo-stream-main\VarjoCommunicationFramework-main\VarjoApp\examples\vcpkg_installed\vcpkg\blds\libjpeg-turbo\config-x64-windows-out.log

Call Stack (most recent call first):
  C:/Users/Ilaria/Desktop/Thesis/Project-Varjo-stream-main/VarjoCommunicationFramework-main/VarjoApp/examples/vcpkg_installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:261 (vcpkg_execute_required_process)
  C:/Users/Ilaria/AppData/Local/vcpkg/registries/git-trees/6d061c71a48ca2abff5cf471f77ef14d7222aa52/portfile.cmake:42 (vcpkg_cmake_configure)
  scripts/ports.cmake:175 (include)


error: building libjpeg-turbo:x64-windows failed with: BUILD_FAILED
Elapsed time to handle libjpeg-turbo:x64-windows: 983 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libjpeg-turbo
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[libjpeg-turbo]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2FUsers%2FIlaria%2FDesktop%2FThesis%2FProject-Varjo-stream-main%2FVarjoCommunicationFramework-main%2FVarjoApp%2Fexamples%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md
```
Anyone has a solution for this problem ?

**Comment by FrankXie05** [comment]
@iladesio Could you please provide the error logs?
```
      C:\Users\Ilaria\Desktop\Thesis\Project-Varjo-stream-main\VarjoCommunicationFramework-main\VarjoApp\examples\vcpkg_installed\vcpkg\blds\libjpeg-turbo\config-x64-windows-dbg-CMakeCache.txt.log
      C:\Users\Ilaria\Desktop\Thesis\Project-Varjo-stream-main\VarjoCommunicationFramework-main\VarjoApp\examples\vcpkg_installed\vcpkg\blds\libjpeg-turbo\config-x64-windows-rel-CMakeCache.txt.log
      C:\Users\Ilaria\Desktop\Thesis\Project-Varjo-stream-main\VarjoCommunicationFramework-main\VarjoApp\examples\vcpkg_installed\vcpkg\blds\libjpeg-turbo\config-x64-windows-out.log
```

**Comment by greenozon** [comment]
can't reproduce it

git pull
bootstrap

<details><summary>Details</summary>
<p>

c:\Dev\vcpkg>vcpkg install libjpeg-turbo
Computing installation plan...
The following packages will be built and installed:
    libjpeg-turbo:x64-windows@3.0.4
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Dev/VS2019/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from C:\Users\user\AppData\Local\vcpkg\archives in 257 us. Use --debug to see more details.
Installing 1/1 libjpeg-turbo:x64-windows@3.0.4...
Building libjpeg-turbo:x64-windows@3.0.4...
-- Using cached libjpeg-turbo-libjpeg-turbo-3.0.4.tar.gz.
-- Cleaning sources at C:/Dev/vcpkg/buildtrees/libjpeg-turbo/src/3.0.4-7f221bad90.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Dev/vcpkg/downloads/libjpeg-turbo-libjpeg-turbo-3.0.4.tar.gz
-- Applying patch add-options-for-exes-docs-headers.patch
-- Applying patch workaround_cmake_system_processor.patch
-- Using source at C:/Dev/vcpkg/buildtrees/libjpeg-turbo/src/3.0.4-7f221bad90.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig file: C:/Dev/vcpkg/packages/libjpeg-turbo_x64-windows/lib/pkgconfig/libjpeg.pc
-- Fixing pkgconfig file: C:/Dev/vcpkg/packages/libjpeg-turbo_x64-windows/lib/pkgconfig/libturbojpeg.pc
-- Downloading https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.3.0-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.3.0-1-any.pkg.tar.zst;https:/
/mirror.yandex.ru/mirrors/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.3.0-1-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.3.0-1-any.pkg.tar
.zst;https://mirrors.ustc.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.3.0-1-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.3.0-1-any.pkg.tar.zst
 -> msys2-mingw-w64-x86_64-pkgconf-1~2.3.0-1-any.pkg.tar.zst...
-- Downloading https://mirror.msys2.org/msys/x86_64/msys2-runtime-3.5.4-2-x86_64.pkg.tar.zst;https://repo.msys2.org/msys/x86_64/msys2-runtime-3.5.4-2-x86_64.pkg.tar.zst;https://mirror.yandex.ru/mirror
s/msys2/msys/x86_64/msys2-runtime-3.5.4-2-x86_64.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/msys2-runtime-3.5.4-2-x86_64.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/msys/x86_
64/msys2-runtime-3.5.4-2-x86_64.pkg.tar.zst;https://mirror.selfnet.de/msys2/msys/x86_64/msys2-runtime-3.5.4-2-x86_64.pkg.tar.zst -> msys2-msys2-runtime-3.5.4-2-x86_64.pkg.tar.zst...
-- Using msys root at C:/Dev/vcpkg/downloads/tools/msys2/21caed2f81ec917b
-- Fixing pkgconfig file: C:/Dev/vcpkg/packages/libjpeg-turbo_x64-windows/debug/lib/pkgconfig/libjpeg.pc
-- Fixing pkgconfig file: C:/Dev/vcpkg/packages/libjpeg-turbo_x64-windows/debug/lib/pkgconfig/libturbojpeg.pc
-- Installing: C:/Dev/vcpkg/packages/libjpeg-turbo_x64-windows/share/libjpeg-turbo/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 531 ms.
Elapsed time to handle libjpeg-turbo:x64-windows: 30 s
libjpeg-turbo:x64-windows package ABI: 560ccc2f194064468d4c7581a2292055db2376ccfe2a0f3642551e9160bfa727
Total install time: 30 s
libjpeg-turbo is compatible with built-in implementation-agnostic CMake targets:

    find_package(JPEG REQUIRED)
    target_include_directories(main PRIVATE JPEG::JPEG)

libjpeg-turbo provides CMake targets for the TurboJPEG C API:

    find_package(libjpeg-turbo CONFIG REQUIRED)
    target_link_libraries(main PRIVATE $<IF:$<TARGET_EXISTS:libjpeg-turbo::turbojpeg>,libjpeg-turbo::turbojpeg,libjpeg-turbo::turbojpeg-static>)


</p>
</details>

**Comment by Mengna-Li** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
