### ISSUE TITLE
[3.21.12] build failure

### ISSUE THREAD

**Issue by alokrajbits** [microsoft/vcpkg#41752]
### Operating system

Linux

### Compiler

GCC

### Steps to reproduce the behavior

change the version in the vcpkg/ports/protobuf.vcpkg.json to 3.21.12

./vcpkg install protobuf:x64-linux --overlay-ports=/path to vcpkg/ports/protobuf

### Failure logs

[DEBUG] Failed to open: /mnt/d/SourceCode/vcpkg/vcpkg/vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
[DEBUG] 1000: execute_process(curl --fail -L https://github.com/protocolbuffers/protobuf/archive/v3.21.12.tar.gz --create-dirs --output /mnt/d/SourceCode/vcpkg/vcpkg/downloads/protocolbuffers-protobuf-v3.21.12.tar.gz.51761.part)
[DEBUG] 1000: cmd_execute_and_stream_data() returned 0 after  1653567 us
[DEBUG] Trying to hash /mnt/d/SourceCode/vcpkg/vcpkg/downloads/protocolbuffers-protobuf-v3.21.12.tar.gz.51761.part
[DEBUG] /mnt/d/SourceCode/vcpkg/vcpkg/downloads/protocolbuffers-protobuf-v3.21.12.tar.gz.51761.part has hash 152f8441c325e808b942153c15e82fdb533d5273b50c25c28916ec568ada880f79242bb61ee332ac5fb0d20f21239ed6f8de02ef6256cc574b1fc354d002c6b0
error: Missing protocolbuffers-protobuf-v3.21.12.tar.gz and downloads are blocked by x-block-origin.
error: File does not have the expected hash:
url: https://github.com/protocolbuffers/protobuf/archive/v3.21.12.tar.gz
File: /mnt/d/SourceCode/vcpkg/vcpkg/downloads/protocolbuffers-protobuf-v3.21.12.tar.gz.51761.part
Expected hash: ce81add9d978a6b63d4205715eac5084e81a6753da1f6c6bad6493e60253215901bffc4a60d704a873333f2b9f94fd86cb7eb5b293035f2268c12692bd808bac
Actual hash: 152f8441c325e808b942153c15e82fdb533d5273b50c25c28916ec568ada880f79242bb61ee332ac5fb0d20f21239ed6f8de02ef6256cc574b1fc354d002c6b0
[DEBUG] /source/src/vcpkg/base/downloads.cpp(1030):

### Additional context

Need to install 3.21.12 version of protobuf, not the latest one. Please suggest a fix.

**Comment by jimwang118** [comment]
If you change the version number in vcpkg.json, you also need to change the download hash value.

**Comment by alokrajbits** [comment]
Can you please suggest where do I make this change?
I replaced the existing hash in the ports/protobuf/portfile.cmake with "expected hash", but it did not work.

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO protocolbuffers/protobuf
    REF "v${VERSION}"
    **SHA512 ce81add9d978a6b63d4205715eac5084e81a6753da1f6c6bad6493e60253215901bffc4a60d704a873333f2b9f94fd86cb7eb5b293035f2268c1269**2bd808bac
    HEAD_REF master
    PATCHES

**Comment by jimwang118** [comment]
The hash you need to replace is as follows:
`Actual hash: 152f8441c325e808b942153c15e82fdb533d5273b50c25c28916ec568ada880f79242bb61ee332ac5fb0d20f21239ed6f8de02ef6256cc574b1fc354d002c6b0`

**Comment by dg0yt** [comment]
Changing the download is not the same as using the old build recipe.  
Use versioning with manifest mode,  
or copy an old revision of `ports/protbuf` for use as an overöyay port.

**Comment by jimwang118** [comment]
@alokrajbits Was your problem solved?

**Comment by alokrajbits** [comment]
@dg0yt  @jimwang118 
I could install older protobuf 3.21.12  by replacing using older ports/protobuf using overlay ports, but got an error when installing grpc 1.51.1 on top of it. 

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    **Command failed: /mnt/d/SourceCode/vcpkg/vcpkg/downloads/tools/ninja/1.10.2-linux/ninja -v**
    Working Directory: /mnt/d/SourceCode/vcpkg/vcpkg/buildtrees/grpc/x64-linux-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      /mnt/d/SourceCode/vcpkg/vcpkg/buildtrees/grpc/config-x64-linux-dbg-CMakeCache.txt.log
      /mnt/d/SourceCode/vcpkg/vcpkg/buildtrees/grpc/config-x64-linux-rel-CMakeCache.txt.log
      /mnt/d/SourceCode/vcpkg/vcpkg/buildtrees/grpc/config-x64-linux-dbg-CMakeConfigureLog.yaml.log
      /mnt/d/SourceCode/vcpkg/vcpkg/buildtrees/grpc/config-x64-linux-rel-CMakeConfigureLog.yaml.log
      /mnt/d/SourceCode/vcpkg/vcpkg/buildtrees/grpc/config-x64-linux-out.log
 
Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:269 (vcpkg_execute_required_process)
  /mnt/d/sourcecode/vcpkg/vcpkg/ports/grpc/portfile.cmake:43 (vcpkg_cmake_configure)
  scripts/ports.cmake:192 (include)
