### ISSUE TITLE
[live555] build failure

### ISSUE THREAD

**Issue by jskim0327** [microsoft/vcpkg#41763]
### Operating system

windows

### Compiler

MSVC

### Steps to reproduce the behavior

vcpkg masnifest mode

### Failure logs

vs2022
manifest mode : vcpkg

1>-- Note: live555 only supports static library linkage. Building static library.
1>-- Downloading http://live555.com/liveMedia/public/live.2024.09.29.tar.gz -> live.2024.09.29.tar.gz...
1>[DEBUG] To include the environment variables in debug output, pass --debug-env
1>[DEBUG] Trying to load bundleconfig from C:\vcpkg\vcpkg-bundle.json
1>[DEBUG] Failed to open: C:\vcpkg\vcpkg-bundle.json
1>[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
1>[DEBUG] Metrics enabled.
1>[DEBUG] Feature flag 'binarycaching' unset
1>[DEBUG] Feature flag 'compilertracking' unset
1>[DEBUG] Feature flag 'registries' unset
1>[DEBUG] Feature flag 'versions' unset
1>[DEBUG] Feature flag 'dependencygraph' unset
1>EXEC : error : Missing live.2024.09.29.tar.gz and downloads are blocked by x-block-origin.
1>EXEC : error : http://live555.com/liveMedia/public/live.2024.09.29.tar.gz: failed: status code 404
1>[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1030):
1>[DEBUG] Time in subprocesses: 0us
1>[DEBUG] Time in parsing JSON: 10us
1>[DEBUG] Time in JSON reader: 0us
1>[DEBUG] Time in filesystem: 1149us
1>[DEBUG] Time in loading ports: 0us
1>[DEBUG] Exiting after 336 ms (311020us)

**Comment by jskim0327** [comment]
I did "vcpkg" git pull, but
the version still hasn't changed.

Please push the modified version.

**Comment by dg0yt** [comment]
Please push upstream to be less hostile to packaging recipes...
