### ISSUE TITLE
[gtest] building gtest:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by mitali929** [microsoft/vcpkg#41771]
Copy issue body from C:/KBApps/vcpkg/installed/vcpkg/issue_body.md

Issue faced at the time of installing the google test using vcpkg .
Below is the Ouput after firing the command " ./vcpkg install gtest".

PS C:\KBApps\vcpkg> ./vcpkg install gtest
Computing installation plan...
A suitable version of cmake was not found (required v3.30.1).
warning: Download failed -- retrying after 1000ms
Downloading https://github.com/Kitware/CMake/releases/download/v3.30.1/cmake-3.30.1-windows-i386.zip
Extracting cmake...
The following packages will be built and installed:
    gtest:x64-windows@1.15.2
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/KBApps/Microsoft Visual Studio/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from C:\Users\ext-bhapkarm\AppData\Local\vcpkg\archives in 183 us. Use --debug to see more details.
Installing 1/1 gtest:x64-windows@1.15.2...
Building gtest:x64-windows@1.15.2...
-- Using cached google-googletest-v1.15.2.tar.gz.
-- Cleaning sources at C:/KBApps/vcpkg/buildtrees/gtest/src/v1.15.2-41f5afb119.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/KBApps/vcpkg/downloads/google-googletest-v1.15.2.tar.gz
-- Applying patch 001-fix-UWP-death-test.patch
-- Applying patch clang-tidy-no-lint.patch
-- Applying patch fix-main-lib-path.patch
-- Using source at C:/KBApps/vcpkg/buildtrees/gtest/src/v1.15.2-41f5afb119.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: C:/KBApps/vcpkg/packages/gtest_x64-windows/src/gtest.cc
-- Installing: C:/KBApps/vcpkg/packages/gtest_x64-windows/src/gtest_main.cc
-- Installing: C:/KBApps/vcpkg/packages/gtest_x64-windows/src/gtest-all.cc
-- Installing: C:/KBApps/vcpkg/packages/gtest_x64-windows/src/gtest-assertion-result.cc
-- Installing: C:/KBApps/vcpkg/packages/gtest_x64-windows/src/gtest-death-test.cc
-- Installing: C:/KBApps/vcpkg/packages/gtest_x64-windows/src/gtest-filepath.cc
-- Installing: C:/KBApps/vcpkg/packages/gtest_x64-windows/src/gtest-internal-inl.h
-- Installing: C:/KBApps/vcpkg/packages/gtest_x64-windows/src/gtest-matchers.cc
-- Installing: C:/KBApps/vcpkg/packages/gtest_x64-windows/src/gtest-port.cc
-- Installing: C:/KBApps/vcpkg/packages/gtest_x64-windows/src/gtest-printers.cc
-- Installing: C:/KBApps/vcpkg/packages/gtest_x64-windows/src/gtest-test-part.cc
-- Installing: C:/KBApps/vcpkg/packages/gtest_x64-windows/src/gtest-typed-test.cc
-- Fixing pkgconfig file: C:/KBApps/vcpkg/packages/gtest_x64-windows/lib/pkgconfig/gmock.pc
-- Fixing pkgconfig file: C:/KBApps/vcpkg/packages/gtest_x64-windows/lib/pkgconfig/gmock_main.pc
-- Fixing pkgconfig file: C:/KBApps/vcpkg/packages/gtest_x64-windows/lib/pkgconfig/gtest.pc
-- Fixing pkgconfig file: C:/KBApps/vcpkg/packages/gtest_x64-windows/lib/pkgconfig/gtest_main.pc
-- Downloading https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst -> msys2-mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from C:\KBApps\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: C:\KBApps\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
error: Missing msys2-mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst and downloads are blocked by x-block-origin.
error: https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst: failed: status code 403
error: https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst: failed: status code 403
error: https://mirror.yandex.ru/mirrors/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst: failed: status code 403
error: https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst: failed: status code 403
error: https://mirrors.ustc.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst: failed: status code 403
error: https://mirror.selfnet.de/msys2/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst: failed: status code 403
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1030):
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 5us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 15037us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 14 s (14036782us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_acquire_msys.cmake:25 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_acquire_msys.cmake:124 (z_vcpkg_acquire_msys_download_package)
  scripts/cmake/vcpkg_acquire_msys.cmake:212 (z_vcpkg_acquire_msys_download_packages)
  scripts/cmake/vcpkg_find_acquire_program(PKGCONFIG).cmake:52 (vcpkg_acquire_msys)
  scripts/cmake/vcpkg_find_acquire_program.cmake:121 (include)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:193 (vcpkg_find_acquire_program)
  ports/gtest/portfile.cmake:49 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:192 (include)

This is the issue faced .

_**_error: building gtest:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle gtest:x64-windows: 40 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`._**_

**Comment by greenozon** [comment]
>error: https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst: failed: status code 403

seems issues with connectivity

@mitali929  could you try to get these by hands and see if you oould get it?

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
