### ISSUE TITLE
Can not use libtorrent.

### ISSUE THREAD

**Issue by dkotrada** [microsoft/vcpkg#4177]
On Ubuntu 18.04 I am trying to use libtorrent with vcpkg but I get a cmake error. I already asked for help on libtorrent project but still no luck. 
https://github.com/arvidn/libtorrent/issues/3268#issuecomment-416367206

**Comment by Voskrese** [comment]
`torrent-rasterbar.dll`
https://github.com/Microsoft/vcpkg/blob/master/ports/libtorrent/portfile.cmake

windows port
edit the script so that it is compatible with linux

**Comment by dkotrada** [comment]
ok. I think I better use Windows. :)

**Comment by NancyLi1013** [comment]
Hi @dkotrada thanks for posting this issue.
libtorrent has been updated to 1.2.2. Please try to update vcpkg and use it.

The usage is as follows:
```
find_package(LibtorrentRasterbar CONFIG REQUIRED)
target_link_libraries(main PRIVATE LibtorrentRasterbar::torrent-rasterbar)
```

Let me know if you have problems.

**Comment by NancyLi1013** [comment]
`libtorrent ` has supported to be found by find_package().
Please try to update.
If you have other problems, please open a new issue.
