### ISSUE TITLE
git clone https://github.com/microsoft/vcpkg.git
cd vcpkg
./bootstrap-vcpkg.sh  # على Linux أو macOS
.\bootstrap-vcpkg.bat # على Windows

### ISSUE THREAD

**Issue by imadhc5775** [microsoft/vcpkg#41778]
**Describe the bug**

**Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
1. ./vcpkg install xxxx
2. See error
Repro code when

**Expected behavior**

**Failure logs**
-(please attached failure logs)

**Additional context**

**Comment by WangWeiLin-MV** [comment]
No valid information.
