### ISSUE TITLE
CMake INSTALL

### ISSUE THREAD

**Issue by kreuzerkrieg** [microsoft/vcpkg#4178]
Ubuntu 18.04, CMake 3.12

Is there a way to tell `INSTALL` in CMake that I want to get dependencies provided by vcpkg to be copied to destination folder along with the target artifacts?

**Comment by NancyLi1013** [comment]
Hi @kreuzerkrieg 

Thanks for posting this issue.

There is no need to copy the dependencies to the destination folder. As long as you use the dependent packages correctly, they will be copied to the related folders automatically.

Please tell us in which case that you need to do like this if you still have questions about this issue.

Thanks.

**Comment by kreuzerkrieg** [comment]
honestly? I dont remember why did I ask this question back then :)
