### ISSUE TITLE
[osg] build with set(osg_OPENGL_PROFILE GLES2+GLES3) failure

### ISSUE THREAD

**Issue by AmoXT** [microsoft/vcpkg#41825]
### Operating system

Windows 10 x64

### Compiler

VS 2019

### Steps to reproduce the behavior

1. add 'set(osg_OPENGL_PROFILE GLES2+GLES3)' to file '.\vcpkg\triplets\x64-windows.cmake'
2. call cmd at folder '.\vcpkg' and run install command 'vcpkg install osg:x64-windows'

### Failure logs

Computing installation plan...
warning: vcpkg appears to be in a Visual Studio prompt targeting x86 but installing for x64-windows. Consider using --triplet x86-windows or --triplet x86-uwp.
The following packages will be built and installed:
    osg[core,default-features,fontconfig,freetype,nvtt,openexr,plugins]:x64-windows@3.6.5#25
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from C:\Users\lenovo\AppData\Local\vcpkg\archives in 255 us. Use --debug to see more details.
Installing 1/1 osg[core,default-features,fontconfig,freetype,nvtt,openexr,plugins]:x64-windows@3.6.5#25...
Building osg[core,default-features,fontconfig,freetype,nvtt,openexr,plugins]:x64-windows@3.6.5#25...
-- Using cached openscenegraph-OpenSceneGraph-OpenSceneGraph-3.6.5.tar.gz.
-- Cleaning sources at D:/Devs/vcpkg/buildtrees/osg/src/raph-3.6.5-499ecaa6e1.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Devs/vcpkg/downloads/openscenegraph-OpenSceneGraph-OpenSceneGraph-3.6.5.tar.gz
-- Applying patch link-libraries.patch
-- Applying patch collada.patch
-- Applying patch fix-sdl.patch
-- Applying patch fix-nvtt-squish.patch
-- Applying patch plugin-pdb-install.patch
-- Applying patch osgdb_zip_nozip.patch
-- Applying patch openexr3.patch
-- Applying patch unofficial-export.patch
-- Applying patch fix-min-max-macro.patch
-- Applying patch fix-error-c3861.patch
-- Using source at D:/Devs/vcpkg/buildtrees/osg/src/raph-3.6.5-499ecaa6e1.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: D:/Devs/vcpkg/buildtrees/osg/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\Devs\vcpkg\buildtrees\osg\config-x64-windows-dbg-CMakeCache.txt.log
      D:\Devs\vcpkg\buildtrees\osg\config-x64-windows-rel-CMakeCache.txt.log
      D:\Devs\vcpkg\buildtrees\osg\config-x64-windows-dbg-CMakeConfigureLog.yaml.log
      D:\Devs\vcpkg\buildtrees\osg\config-x64-windows-rel-CMakeConfigureLog.yaml.log
      D:\Devs\vcpkg\buildtrees\osg\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:269 (vcpkg_execute_required_process)
  ports/osg/portfile.cmake:94 (vcpkg_cmake_configure)
  scripts/ports.cmake:192 (include)

error: building osg:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle osg:x64-windows: 42 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+osg
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[osg]+Build+error+on+x64-windows&body=Copy+issue+body+from+D%3A%2FDevs%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md[config-x64-windows-dbg-CMakeCache.txt.log](https://github.com/user-attachments/files/17539924/config-x64-windows-dbg-CMakeCache.txt.log)

Files:
[config-x64-windows-dbg-CMakeConfigureLog.yaml.log](https://github.com/user-attachments/files/17539928/config-x64-windows-dbg-CMakeConfigureLog.yaml.log)
[config-x64-windows-out.log](https://github.com/user-attachments/files/17539926/config-x64-windows-out.log)
[config-x64-windows-rel-CMakeCache.txt.log](https://github.com/user-attachments/files/17539927/config-x64-windows-rel-CMakeCache.txt.log)
[config-x64-windows-rel-CMakeConfigureLog.yaml.log](https://github.com/user-attachments/files/17539925/config-x64-windows-rel-CMakeConfigureLog.yaml.log)

**Comment by AmoXT** [comment]
Is there any way to fix this problem ?

**Comment by AmoXT** [comment]
> > CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> > Please set them or make sure they are set and tested correctly in the CMake files:
> > EGL_LIBRARY (ADVANCED)
> 
> The port `osg` does not explicitly depend on `egl`. If you're using classic mode, just install `egl` before installing `osg`. If you're using manifest mode, create an overlay port for `osg` and add `egl` into its manifest.

I have solved this problem. The reason is the cmake options osg_OPENGL_PROFILE can not read from file ".\triplets\x64-windows.cmake", but from ".\ports\osg\portfile.cmake" at line 80. We can replace "set(osg_OPENGL_PROFILE "GL2")" to "set(osg_OPENGL_PROFILE, "GLES2+GLES3")" and delete the folder ".\buildtrees\osg" if you have built once. Then execute "vcpkg install osg:x64-windows" again.

**Comment by dg0yt** [comment]
> The reason is the cmake options osg_OPENGL_PROFILE can not read from file ".\triplets\x64-windows.cmake", but from ".\ports\osg\portfile.cmake" at line 80.

This is not right. Line 80 isn't reached when the triplet sets osg_OPENGL_PROFILE.
And the initial `CMakeCache.txt.log` proves that with
~~~
OPENGL_PROFILE:STRING=GLES2+GLES3
~~~
