### ISSUE TITLE
[cuda] Build failure on x64-windows

### ISSUE THREAD

**Issue by Kavik22** [microsoft/vcpkg#41834]
Package: cuda:x64-windows@10.1#13

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.41.34123.0
-    vcpkg-tool version: 2024-10-18-e392d7347fe72dff56e7857f7571c22301237ae6
    vcpkg-scripts version: unknown

**To Reproduce**

`vcpkg install libtorch`

**Failure logs**

```
-- Executing NVCC-NOTFOUND --version resulted in error: 1
CMake Error at ports/cuda/vcpkg_find_cuda.cmake:69 (message):
  Could not find CUDA.  Before continuing, please download and install CUDA
  (v10.1.0 or higher) from:

      https://developer.nvidia.com/cuda-downloads

Call Stack (most recent call first):
  ports/cuda/portfile.cmake:9 (vcpkg_find_cuda)
  scripts/ports.cmake:192 (include)



```

**Comment by autoantwort** [comment]
Did you read what you have posted?

**Comment by chinglish-my-mother-tongue** [comment]
Embarrassing!

**Comment by MonicaLiu0311** [comment]
You need to install [CUDA](https://developer.nvidia.com/) locally now.

**Comment by MonicaLiu0311** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
