### ISSUE TITLE
[<port name>] build failure

### ISSUE THREAD

**Issue by iguaguagua** [microsoft/vcpkg#41837]
### Operating system

Windows 10

### Steps to reproduce the behavior

error: In manifest mode, `vcpkg install` does not support individual package arguments.
To install additional packages, edit vcpkg.json and then run `vcpkg install` without any package arguments.
See https://learn.microsoft.com/vcpkg/users/manifests for more information.

### Failure logs

error: In manifest mode, `vcpkg install` does not support individual package arguments.
To install additional packages, edit vcpkg.json and then run `vcpkg install` without any package arguments.
See https://learn.microsoft.com/vcpkg/users/manifests for more information.

**Comment by autoantwort** [comment]
Did you read what you have posted?

**Comment by chinglish-my-mother-tongue** [comment]
Embarrassing!
