### ISSUE TITLE
[libcap] build for arm failed

### ISSUE THREAD

**Issue by US3RN2ME** [microsoft/vcpkg#41830]
### Operating system

Linux

### Compiler

GCC

### Steps to reproduce the behavior

libcap being crosscompiled for arm unable to read file format Makefile

### Failure logs

[build-arm-linux-dynamic-dbg-err.log](https://github.com/user-attachments/files/17540977/build-arm-linux-dynamic-dbg-err.log)

[build-arm-linux-dynamic-dbg-out.log](https://github.com/user-attachments/files/17540976/build-arm-linux-dynamic-dbg-out.log)

**Comment by US3RN2ME** [comment]
So the reason is that in libcap/Makefile both BUILD_CC and CC are set to arm-linux-gnueabihf-gcc. But BUILD_CC should be set to host triplet compiler

**Comment by dg0yt** [comment]
> But BUILD_CC should be set to host triplet compiler

But not in vpckg. If the port needs host stuff, it must be done when building for the host triplet, and re-used in non-native triplets.

**Comment by dg0yt** [comment]
IIUC the wrong objcopy is being used:
~~~
# okay
/usr/bin/arm-linux-gnueabihf-gcc -o empty empty.c
# not okay
objcopy --dump-section .interp=loader.txt empty /dev/null
~~~

**Comment by dg0yt** [comment]
FTR cross builds were tested before. But only to static tripets.

**Comment by US3RN2ME** [comment]
If I set obcopy to arm-linux-gnueabihf-objcopy manually by editing Makefile
I got the following error: 
```
/bin/sh: 1: ./_makenames: Exec format error
make[1]: *** [Makefile:82: cap_names.h] Error 126
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile.vcpkg:13: all] Error 2
```

Because it was compiled for arm and can't be run on linux easily.

So, to resolve that it is also needed to set BUILD_CC to host triplet compiler
```
_makenames: _makenames.c cap_names.list.h
	$(BUILD_CC) $(BUILD_CFLAGS) $(BUILD_CPPFLAGS) $< -o $@
```
If I change this $(BUILD_CC) to gcc manually by editing Makefile, libcap configures and builds successfully

I assume the reason is [here](https://github.com/microsoft/vcpkg/blob/1b63f25c4cd58a699df0beb39474e62b2efc14a1/ports/libcap/configure#L22)

**Comment by dg0yt** [comment]
Try #41852. Tested with arm64-linux-dynamic on x64 linux.

**Comment by US3RN2ME** [comment]
Build is succesfull now, thanks for you help
