### ISSUE TITLE
Can't link boost to a simple CMake application

### ISSUE THREAD

**Issue by Facon** [Microsoft/vcpkg#4188]
I'm not able to link Boost to a simple CMake project.

Example.cpp:
```
#include <boost/asio.hpp>
#include <iostream>

int main()
{
	std::cout << "Hello CMake." << std::endl;
	return 0;
}
```

CMakeLists.txt:
```
cmake_minimum_required (VERSION 3.10)

project ("Example" LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

if(CMAKE_CXX_FLAGS MATCHES "/W[0-4]")
	string(REGEX REPLACE "/W[0-4]" "/W4" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
endif()

set(Boost_USE_STATIC_LIBS ON)
find_package(BOOST 1.68.0 REQUIRED COMPONENTS system)
find_path(BOOST_INCLUDE_DIR boost)
include_directories(${BOOST_INCLUDE_DIR})

add_executable (Example "Example.cpp")
message("LIBRARY FOUND: ${Boost_SYSTEM_FOUND}")
target_link_libraries(Example boost::system)

if (CMAKE_CXX_COMPILER_ID MATCHES "Clang|AppleClang|GNU")
    target_compile_options(Example PRIVATE -Wall -Wextra -Wunreachable-code -Wpedantic)
endif()
if (CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    target_compile_options(Example PRIVATE -Wweak-vtables -Wexit-time-destructors -Wglobal-constructors -Wmissing-noreturn )
endif()
if (CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
    target_compile_options(Example PRIVATE /W4 /w44265 /w44061 /w44062 )
endif()
```

CMakeSettings.json:
```
{
  "configurations": [
    {
      "name": "x86-Debug",
      "generator": "Ninja",
      "configurationType": "Debug",
      "inheritEnvironments": [
        "msvc_x86"
      ],
      "buildRoot": "${env.USERPROFILE}\\CMakeBuilds\\${workspaceHash}\\build\\${name}",
      "installRoot": "${env.USERPROFILE}\\CMakeBuilds\\${workspaceHash}\\install\\${name}",
      "cmakeCommandArgs": "",
      "buildCommandArgs": "-v",
      "ctestCommandArgs": "",
      "variables": [
        {
          "name": "CMAKE_TOOLCHAIN_FILE",
          "value": "C:\\Users\\User\\Desktop\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake"
        }
      ]
    },
    {
      "name": "x86-Release",
      "generator": "Ninja",
      "configurationType": "RelWithDebInfo",
      "inheritEnvironments": [
        "msvc_x86"
      ],
      "buildRoot": "${env.USERPROFILE}\\CMakeBuilds\\${workspaceHash}\\build\\${name}",
      "installRoot": "${env.USERPROFILE}\\CMakeBuilds\\${workspaceHash}\\install\\${name}",
      "cmakeCommandArgs": "",
      "buildCommandArgs": "-v",
      "ctestCommandArgs": "",
      "variables": [
        {
          "name": "CMAKE_TOOLCHAIN_FILE",
          "value": "C:\\Users\\User\\Desktop\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake"
        }
      ]
    }
  ]
}
```

May it be possible to have some help with this?

**Comment by iso8859** [comment]
Hi Facon,

Have a look here
https://github.com/iso8859/vcpkg-boost

Remi

**Comment by Facon** [comment]
I have made it work in release by only putting the boost_system library like this:
`target_link_libraries(Example ${Boost_LIBRARY_DIRS}/boost_system-vc140-mt.lib)`

Nonetheless, it still doesn't work in debug it displays this message:
> 1> Command line: c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\commonextensions\microsoft\cmake\CMake\bin\cmake.exe  -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\User\CMakeBuilds\1a254f43-3165-d83b-86d3-c1019c813dc5\install\x86-Debug"  -DCMAKE_TOOLCHAIN_FILE="C:/Users/User/Desktop/vcpkg/scripts/buildsystems/vcpkg.cmake"  -DCMAKE_CXX_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/HostX86/x86/cl.exe"  -DCMAKE_C_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/HostX86/x86/cl.exe"  -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_MAKE_PROGRAM="c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\commonextensions\microsoft\cmake\Ninja\ninja.exe" "C:\Users\User\Desktop\Sources\Example"
> 1> Working directory: C:\Users\User\CMakeBuilds\1a254f43-3165-d83b-86d3-c1019c813dc5\build\x86-Debug
> 1> -- Could NOT find Boost
> 1> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> 1> -- Configuring incomplete, errors occurred!
> 1> Please set them or make sure they are set and tested correctly in the CMake files:
> 1> BOOST_INCLUDE_DIR
> 1>    used as include directory in directory C:/Users/User/Desktop/Sources/Example/Example
> 1>    used as include directory in directory C:/Users/User/Desktop/Sources/Example/Example
> 1>    used as include directory in directory C:/Users/User/Desktop/Sources/Example/Example
> 1>    used as include directory in directory C:/Users/User/Desktop/Sources/Example/Example
> 1> See also "C:/Users/User/CMakeBuilds/1a254f43-3165-d83b-86d3-c1019c813dc5/build/x86-Debug/CMakeFiles/CMakeOutput.log".
> 1>    used as include directory in directory C:/Users/User/Desktop/Sources/Example/Example
> 1>    used as include directory in directory C:/Users/User/Desktop/Sources/Example/Example
> 1> 
> 1> c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\commonextensions\microsoft\cmake\CMake\bin\cmake.exe  -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\User\CMakeBuilds\1a254f43-3165-d83b-86d3-c1019c813dc5\install\x86-Debug"  -DCMAKE_TOOLCHAIN_FILE="C:/Users/User/Desktop/vcpkg/scripts/buildsystems/vcpkg.cmake"  -DCMAKE_CXX_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/HostX86/x86/cl.exe"  -DCMAKE_C_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/HostX86/x86/cl.exe"  -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_MAKE_PROGRAM="c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\commonextensions\microsoft\cmake\Ninja\ninja.exe" "C:\Users\User\Desktop\Sources\Example" returned with exit code: 1
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> BOOST_INCLUDE_DIR
>    used as include directory in directory C:/Users/User/Desktop/Sources/Example/Example
>    used as include directory in directory C:/Users/User/Desktop/Sources/Example/Example
>    used as include directory in directory C:/Users/User/Desktop/Sources/Example/Example
>    used as include directory in directory C:/Users/User/Desktop/Sources/Example/Example
>    used as include directory in directory C:/Users/User/Desktop/Sources/Example/Example
>    used as include directory in directory C:/Users/User/Desktop/Sources/Example/Example

**Comment by linonetwo** [comment]
Hi, @Facon, you file doesn't work:

```
-- Could NOT find Boost
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
BOOST_INCLUDE_DIR
   used as include directory in directory /Users/linonetwo/repo/fast-belt
   used as include directory in directory /Users/linonetwo/repo/fast-belt
   used as include directory in directory /Users/linonetwo/repo/fast-belt
```

**Comment by shimondoodkin** [comment]
the problem is variable names are case sensitive, not BOOST rather Boost

https://cmake.org/cmake/help/latest/module/FindBoost.html
no need to find include dirs the variable specified for you already. it is just case sensitive.

more like:

```cmake
cmake_minimum_required (VERSION 3.10)

project ("Example" LANGUAGES CXX)

set(Boost_USE_STATIC_LIBS ON)
find_package(Boost REQUIRED COMPONENTS )# asio is header only no library
include_directories(${Boost_INCLUDE_DIR})

add_executable (Example "Example.cpp")
target_link_libraries(Example ${Boost_LIBRARIES})

```
