### ISSUE TITLE
[lz4] unexpected field 'license'

### ISSUE THREAD

**Issue by TyrasNistru** [microsoft/vcpkg#41888]
### Operating system

Windows 11 23H2

### Compiler

MSVC 2019

### Steps to reproduce the behavior

`.\vckpg install lz4`

### Failure logs

Computing installation plan...
error: while looking for lz4:x86-windows:
error: while loading D:\vcpkg\ports\lz4\vcpkg.json:
$.features.tools (a feature): unexpected field 'license', did you mean 'supports'?

**Comment by autoantwort** [comment]
Run `./bootstrap-vcpkg.bat`

**Comment by TyrasNistru** [comment]
Thanks, it worked!
