### ISSUE TITLE
[ffmpeg] update to 7.1

### ISSUE THREAD

**Issue by abique** [microsoft/vcpkg#41899]
### Library name

ffmpeg

### New version number

7.1

### Other information that may be useful (release notes, etc...)

https://git.ffmpeg.org/gitweb/ffmpeg.git/tag/507a51fbe9732f0f6f12f43ce12431e8faa834b7

It was released a month ago.

Thank you very much 👍

**Comment by dg0yt** [comment]
See #41856.

**Comment by abique** [comment]
Oh thank you very much!
I've checked a few days ago and it wasn't there yet, and I didn't check again this morning thank you so much!

ffmpeg 7.0 crashes on windows arm64 while encoding mp3. So I hope this update fixes it.

Thanks!

**Comment by dg0yt** [comment]
> ffmpeg 7.0 crashes on windows arm64 while encoding mp3.

I would assume that the heavy lifting (specific to CPU) is done in a dependency.

**Comment by abique** [comment]
> > ffmpeg 7.0 crashes on windows arm64 while encoding mp3.
> 
> I would assume that the heavy lifting (specific to CPU) is done in a dependency.

Possibly, if that updates doesn't fix it, then I'll debug the crash.

**Comment by abique** [comment]
https://trac.ffmpeg.org/ticket/11285

**Comment by dg0yt** [comment]
> https://trac.ffmpeg.org/ticket/11285

"the heavy lifting (specific to CPU) is done in a dependency."

**Comment by abique** [comment]
It turns out that compiling libmp3lame with clang-cl on windows arm64 works.

libmp3lame seems to be unmaintained.
