### ISSUE TITLE
[libtorch] Build error on x64-windows

### ISSUE THREAD

**Issue by sjpritchard** [microsoft/vcpkg#41907]
Package: libtorch:x64-windows@2.1.2#7

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.41.34123.0
-    vcpkg-tool version: 2024-10-18-e392d7347fe72dff56e7857f7571c22301237ae6
    vcpkg-scripts version: 4f746bc66 2024-11-01 (14 hours ago)
- PowerShell 7.4.5 x64

**To Reproduce**

`vcpkg install `

**Failure logs**

```
-- Using cached libtorch-cudnn-9-fix-e14026bc2a6cd80bedffead77a5d7b75a37f8e67.patch.
-- Using cached libtorch-cuda-thrust-missing-header-2a440348958b3f0a2b09458bd76fe5959b371c0c.patch.
-- Using cached pytorch-pytorch-v2.1.2.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/libtorch/src/v2.1.2-89de820eea.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/pytorch-pytorch-v2.1.2.tar.gz
-- Applying patch C:/vcpkg/downloads/libtorch-cudnn-9-fix-e14026bc2a6cd80bedffead77a5d7b75a37f8e67.patch
-- Applying patch C:/vcpkg/downloads/libtorch-cuda-thrust-missing-header-2a440348958b3f0a2b09458bd76fe5959b371c0c.patch
-- Applying patch cmake-fixes.patch
-- Applying patch more-fixes.patch
-- Applying patch fix-build.patch
-- Applying patch clang-cl.patch
-- Applying patch cuda-adjustments.patch
-- Applying patch fix-api-export.patch
-- Applying patch fxdiv.patch
-- Applying patch protoc.patch
-- Applying patch fix-sleef.patch
-- Applying patch fix-glog.patch
-- Applying patch fix-msvc-ICE.patch
-- Applying patch fix-calculate-minloglevel.patch
-- Applying patch force-cuda-include.patch
-- Applying patch fix-aten-cutlass.patch
-- Applying patch fix-build-error-with-fmt11.patch
-- Using source at C:/vcpkg/buildtrees/libtorch/src/v2.1.2-89de820eea.clean
-- Using cached pytorch-kineto-49e854d805d916b2031e337763928d2f8d2e1fbf.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/libtorch/src/2f8d2e1fbf-de7a6d4b27.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/pytorch-kineto-49e854d805d916b2031e337763928d2f8d2e1fbf.tar.gz
-- Applying patch kineto.patch
-- Using source at C:/vcpkg/buildtrees/libtorch/src/2f8d2e1fbf-de7a6d4b27.clean
-- Using cached NVIDIA-cudnn-frontend-12f35fa2be5994c1106367cac2fba21457b064f4.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/libtorch/src/1457b064f4-11f2c20faf.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/NVIDIA-cudnn-frontend-12f35fa2be5994c1106367cac2fba21457b064f4.tar.gz
-- Using source at C:/vcpkg/buildtrees/libtorch/src/1457b064f4-11f2c20faf.clean
-- Using flatc: C:/Users/steve/simcortex/ai_sim_assistant/vcpkg_installed/x64-windows/tools/flatbuffers/flatc.exe
-- Using protoc: C:/Users/steve/simcortex/ai_sim_assistant/vcpkg_installed/x64-windows/tools/protobuf/protoc.exe
-- Using cached pypa-get-pip-24.2.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/libtorch/src/24.2-36e81c02c7.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/pypa-get-pip-24.2.tar.gz
-- Using source at C:/vcpkg/buildtrees/libtorch/src/24.2-36e81c02c7.clean
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: C:/vcpkg/downloads/tools/python/python-3.12.7-x64/python.exe C:/vcpkg/buildtrees/libtorch/src/24.2-36e81c02c7.clean/public/get-pip.py --no-warn-script-location
    Working Directory: C:/vcpkg/buildtrees/libtorch
    Error code: Access violation
    See logs for more information:

Call Stack (most recent call first):
  C:/Users/steve/simcortex/ai_sim_assistant/vcpkg_installed/x64-windows/share/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake:44 (vcpkg_execute_required_process)
  buildtrees/versioning_/versions/libtorch/e738e2da09a82affc4bf4090d8c672579364231b/portfile.cmake:86 (x_vcpkg_get_python_packages)
  scripts/ports.cmake:192 (include)



```

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "name": "ai-sim-assistant",
  "builtin-baseline": "4f746bc66438fce2b900c3ba6094a483b871b045",
  "dependencies": [
    {
      "name": "flashlight-text",
      "version>=": "0.0.4",
      "features": [
        "kenlm"
      ]
    },
    {
      "name": "glog",
      "version>=": "0.7.1"
    },
    {
      "name": "gtest",
      "version>=": "1.15.2"
    },
    {
      "name": "jwt-cpp",
      "version>=": "0.7.0#1"
    },
    {
      "name": "kenlm",
      "version>=": "20230531#1"
    },
    {
      "name": "libtorch",
      "default-features": false,
      "version>=": "2.1.2#7"
    },
    {
      "name": "openssl",
      "version>=": "3.4.0"
    },
    {
      "name": "rapidfuzz",
      "version>=": "3.0.5"
    }
  ]
}

```
</details>

**Comment by petersteneteg** [comment]
I'm having the exact same error code but when building glad which is also using python 3.12.7

**Comment by petersteneteg** [comment]
If I run the same python script with my local python installation 3.12.3 there is no issues

**Comment by petersteneteg** [comment]
My issue goes away if I revert back to python 3.11.8
by reverting this:
https://github.com/microsoft/vcpkg/commit/7dcb4ca95bfde3cfca3a9f0a7e933f1d17cc4836#diff-26499ad5d840cada3059f7aaa8363695140b4a6811ed08697b388ab19e16ae97L3-R35

in PR https://github.com/microsoft/vcpkg/pull/41232

This could still be related to antivirus/applocker/etc issues but debugging the Access Violation crash is hard. Seems to happen somewhere in pythons importlib._bootstrap for me. Maybe the new old python has be removed from windows defender, but the new one triggers some issue? Very hard to say. Im not allowed to bypass the org antivirus settings so Im not able to try that.

**Comment by petersteneteg** [comment]
I figured out the issue.

vcpkg downloads and uses python 3.12.7 and puts that into vcpkg/downloads/tools/python/python-3.12.7-x64

But I have a local python installation of python 3.12.3 in C:\Program Files\Python312 which is also in the global PATH

And it turns out the the vcpkg python will load the _ctypes.pyd from C:\Program Files\Python312 \DLLs not the on in 
vcpkg/downloads/tools/python/python-3.12.7-x64 and the are apparently not binary compatible.
The old ctypes dll will try use PyObject_LookupAttr which craches with an access violation. 

Updating my local python version to the same version "solves" the issue.  
But the vcpkg python really should run isolated from any other installations.

**Comment by petersteneteg** [comment]
Maybe scripts/cmake/vcpkg_find_acquire_program(PYTHON3).cmake should prefix it self to the local path

**Comment by MonicaLiu0311** [comment]
@Neumann-A Could you help look into this issue?

**Comment by dg0yt** [comment]
IMO this the same problem that we see with the meson ports (other issues): On the other installations of python interferes with the version run by vcpkg.  
And there is PR for meson in particular. One think I don't like about that PR is that I assume that `vcpkg_find_acquire_program(PYTHON3)` must be fixed to do the right thing.

`vcpkg_find_acquire_program(PYTHON3)` disables the "isolated mode" for the downloaded python. This has some desired effects, but it also makes python use Windows registry and environment variables (PYTHONPATH and PYTHONHOME) when setting up the module search path. I guess this is what causes interference but I'm not an expert for python.

@petersteneteg Are these environment variables set in your system? If yes, is the problem solved by unsetting them?

**Comment by dg0yt** [comment]
> The registry lookup is the problem. I think the only way to 'solve' it is by pretending to be a venv python if vcpkg provides the tool.

Agree. 
Basically we have what is needed in vcpkg-get-python-packages, except that it *requires* packages to be defined. 
(`pip` should be a no-op?)

**Comment by MonicaLiu0311** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
