### ISSUE TITLE
[abseil] linker error on cmake clang llvm project

### ISSUE THREAD

**Issue by Chrys4lisfag** [microsoft/vcpkg#41934]
### Operating system

Windows

### Compiler

Clang LLVM

### Steps to reproduce the behavior

Install latest vcpkg: 4f746bc66438fce2b900c3ba6094a483b871b045 (#41852)

use abseil x64-windows-static

PORT INFO:
"name": "abseil",
"version": "20240722.0",

abseil-abseil-cpp-20240722.0.tar.gz

### Failure logs

I get linker error while compiling my application:
clang++: error: unknown argument: '-ignore:4221'

When using abseil through fetchcontent tag master it builds OK.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. I installed `abseil:x64-windows-static@20240722.0` and use its

**Comment by Chrys4lisfag** [comment]
> Thanks for posting this issue. I installed `abseil:x64-windows-static@20240722.0` and test its CMake usage in CMake project, it passed. Could you please provide the repro codes?
> 
> ```
>   find_package(absl CONFIG REQUIRED)
>   # note: 186 additional targets are not displayed.
>   target_link_libraries(main PRIVATE absl::any absl::log absl::base absl::bits)
> ```

Sure, will do. Have you tested on clang llvm?

**Comment by LilyWangLL** [comment]
The same issue: #13945, https://github.com/microsoft/vcpkg/issues/25300.

**Comment by dg0yt** [comment]
So building ports with MSVC, and using the result with LLVM? Can nobody add a suitable generator expression?

**Comment by Chrys4lisfag** [comment]
> So building ports with MSVC, and using the result with LLVM? Can nobody add a suitable generator expression?

Haven't had any issues with this so far. So should the issue be closed due to custom tripled must be used with clang?

**Comment by LilyWangLL** [comment]
> clang++: error: unknown argument: '-ignore:4221'

The code related to this error is upstream file https://github.com/abseil/abseil-cpp/blob/4b4f41e93d14812481b7692f89dccb1f0d609a28/absl/copts/AbseilConfigureCopts.cmake#L74C1-L104C8.

**Comment by Chrys4lisfag** [comment]
> > clang++: error: unknown argument: '-ignore:4221'
> 
> The code related to this error is upstream file https://github.com/abseil/abseil-cpp/blob/4b4f41e93d14812481b7692f89dccb1f0d609a28/absl/copts/AbseilConfigureCopts.cmake#L74C1-L104C8.

Do you still need the example repo?

**Comment by Chrys4lisfag** [comment]
When using clang-llvm to build vcpkg packages, it build ok: https://github.com/Neumann-A/my-vcpkg-triplets

But you have to edit avx include in clang to be able to compile it. Yet I don't know which other issues this can lead to as this is not officially supported tripled and you have to fix everything yourself

**Comment by LilyWangLL** [comment]
> > > clang++: error: unknown argument: '-ignore:4221'
> > 
> > 
> > The code related to this error is upstream file https://github.com/abseil/abseil-cpp/blob/4b4f41e93d14812481b7692f89dccb1f0d609a28/absl/copts/AbseilConfigureCopts.cmake#L74C1-L104C8.
> 
> Do you still need the example repo?

No.

**Comment by dg0yt** [comment]
Should `-ignore:4221` be exported at all? IMO this is for dealing with how abseil is built, but it doesn't look like something which should be forced on user projects where abseil is used.

**Comment by tekert** [comment]
Have the same error using clang and absail

**Comment by jeremicmilan** [comment]
I'm hitting the same issue.

@LilyWangLL, can we reactivate this issue and fix it? Or should we create an issue in the abseil codebase and push for a fix there?

Also, can we do something today to mitigate this issue in our projects?

**Comment by LilyWangLL** [comment]
> I'm hitting the same issue.
> 
> [@LilyWangLL](https://github.com/LilyWangLL), can we reactivate this issue and fix it? Or should we create an issue in the abseil codebase and push for a fix there?
> 
> Also, can we do something today to mitigate this issue in our projects?

This issue is about usage of `abseil`, could you please submit this issue in the upstream of `abseil`?

**Comment by SMSum** [comment]
This is still once again an issue, and has been since 2020. Surely it cannot take this much effort to remove a single line by default from this target...
