### ISSUE TITLE
CMake macro duplication

### ISSUE THREAD

**Issue by omartijn** [microsoft/vcpkg#41966]
**Describe the bug**
The `z_vcpkg_function_arguments` macro is (intentionally, it seems) duplicated between `scripts/buildsystems/vcpkg.cmake` and `scripts/cmake/z_vcpkg_function_arguments.cmake`.

**Environment**
Irrelevant

**To Reproduce**
1. Clone the repo
2. Inspect the two mentioned files, duplicate macro

**Expected behavior**
Macros and functions aren't duplicated. 

**Failure logs**
-(please attached failure logs)

**Additional context**
Running gersemi on our repo (which has vcpkg as a submodule) and using the scripts directory for definitions leads to the following warning:

```
Warning: conflicting definitions for 'z_vcpkg_function_arguments':
(used)    /home/martijn/git/software4/vcpkg/scripts/buildsystems/vcpkg.cmake:151:7
(ignored) /home/martijn/git/software4/vcpkg/scripts/cmake/z_vcpkg_function_arguments.cmake:3:7
```

**Comment by dg0yt** [comment]
> The `z_vcpkg_function_arguments` macro is (intentionally, it seems) duplicated between `scripts/buildsystems/vcpkg.cmake` and `scripts/cmake/z_vcpkg_function_arguments.cmake`.

Not an issue.

`scripts/buildsystems/vcpkg.cmake` is the toolchain file: Project mode.  
`scripts/cmake/z_vcpkg_function_arguments.cmake` is for portfiles: Script mode.

This are parallel universes which do not overlap.
https://learn.microsoft.com/en-us/vcpkg/contributing/maintainer-guide#portfiles-are-run-in-script-mode

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
