### ISSUE TITLE
boost 1.68 program_options crash

### ISSUE THREAD

**Issue by liuaifu** [Microsoft/vcpkg#4196]
The following code will crash at store() when use vcpkg, but compile it with myself compiled library is work right.

	int main(int argc, char **argv)
	{
		using namespace boost::program_options;
		options_description desc("Allowed options");
		desc.add_options()
			("help,h", "produce help message")
			("log-level", value<int>()->default_value(1), "0:trace,1:debug,2:info,3:warning,4:error,5:fatal")
			("server-ip", value<std::string>()->default_value("1.1.1.1"), "server ip")
			("server-port", value<std::string>()->default_value("8080"), "server port")
			("port", value<short>()->default_value(8080), "listen port")
			;

		variables_map vm;
		store(parse_command_line(argc, argv, desc), vm);
		notify(vm);
		......
	}

**Comment by icedream2linxi** [comment]
Please post the error message.

> 请把错误信息帖上来。

**Comment by icedream2linxi** [comment]
I tested your code and there was no crash in me.

> 我测试了你的代码，在我这里并没有发生崩溃。

**Comment by icedream2linxi** [comment]
@liuaifu 
看上去像是链接的 lib 不对。
请确认下：
1.链接的是否是 vcpkg 编译出来的 lib；
2.你这代码使用的 VS 版本与 vcpkg 编译时使用的 VS 版本是否一致；
3.链接的 lib 的 Debug、Release 版本是否没有弄错。

**Comment by liuaifu** [comment]
1.属性页中的VC++目录和C/C++常规中的附加包含目录没有引用任何除默认目录外的目录
2.系统只有VS2017
3.我仅在Debug X86下编译

**Comment by icedream2linxi** [comment]
@liuaifu 
项目属性页 Linker -> General -> Suppress Startup Banner 设置为 No。再编译，看输出信息，看链接的 lib 路径是否正确。

如果还是不行，我有两个建议：
1.新建个测试用项目，项目设置中设置好 Additional Include Directories 和 Additional Library Directories，试试是否有问题。
2.新建个测试用项目，使用 vcpkg integrate project 集成 vcpkg，试试是否有问题。

**Comment by liuaifu** [comment]
@icedream2linxi vcpkg编译出来的boost库文件签名带vc140，我自己的程序是vc141编译的，从Visual Studio Installer里看了，我只装了vc141工具集，这个vc140不知道哪冒出来的。

**Comment by icedream2linxi** [comment]
@liuaifu vc140 与 vc141 是二进制兼容的！所以，vcpkg 的 boost 库编译后自动重命名成 v140。我拿你的代码测试过，跟这个没关系。

**Comment by degski** [comment]
@liuaifu Thanks for sharing ;-).
@icedream2linxi Thanks for sharing ;-).

**Comment by liuaifu** [comment]
@icedream2linxi vcpkg integrate remove并按照1新建项目，仅加入相关代码，手工设置vcpkg的include和lib目录，编译成功但问题依旧。2就懒得试了，之前就是用的vcpkg integrate install。有人成功不代表没有问题，还有其它bug就不提了，离1.0还远，microsoft的人还需努力啊。

**Comment by liuaifu** [comment]
@degski I uninstall boost from vcpkg, and reinstall it, now it's working normally.
