### ISSUE TITLE
curl:x86-windows

### ISSUE THREAD

**Issue by acgetchell** [Microsoft/vcpkg#4197]
```
Error: Building package curl:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: curl:x86-windows
  Vcpkg version: 0.0.113-nohash
```

Full log here:

https://ci.appveyor.com/project/acgetchell/cdt-test/build/0.1.3

Test repo that generated AppVeyor build here:

https://github.com/acgetchell/CDT-test

**Comment by icedream2linxi** [comment]
Unable to view logs.
curl\install-x86-windows-dbg-out.log

**Comment by icedream2linxi** [comment]
Your problem is the same as #4189, delete C:\OpenSSL-v11-Win32 and C:\OpenSSL-v11-Win64 first.

> 你的问题与 #4189 一样，先删除 C:\OpenSSL-v11-Win32 和 C:\OpenSSL-v11-Win64 就可以了。

**Comment by acgetchell** [comment]
Yes, that fixed it. Thank you!

https://ci.appveyor.com/project/acgetchell/cdt-test/build/0.1.4
