### ISSUE TITLE
[brotli] Build error on x64-windows

### ISSUE THREAD

**Issue by BrandonKim-05** [microsoft/vcpkg#41992]
[config-x64-windows-dbg-CMakeCache.txt.log](https://github.com/user-attachments/files/17653514/config-x64-windows-dbg-CMakeCache.txt.log)
[config-x64-windows-dbg-CMakeConfigureLog.yaml.log](https://github.com/user-attachments/files/17653510/config-x64-windows-dbg-CMakeConfigureLog.yaml.log)
[config-x64-windows-out.log](https://github.com/user-attachments/files/17653513/config-x64-windows-out.log)
[config-x64-windows-rel-CMakeCache.txt.log](https://github.com/user-attachments/files/17653512/config-x64-windows-rel-CMakeCache.txt.log)
[config-x64-windows-rel-CMakeConfigureLog.yaml.log](https://github.com/user-attachments/files/17653511/config-x64-windows-rel-CMakeConfigureLog.yaml.log)
**Host Environment**

- OS: Windows 10
- Compiler: cmake

**To Reproduce:**

vcpkg install brotli

**Failure Logs:**

Computing installation plan...
The following packages will be built and installed:
    brotli:x64-windows@1.1.0#1
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from C:\Users\f21br\AppData\Local\vcpkg\archives in 628 us. Use --debug to see more details.
Installing 1/1 brotli:x64-windows@1.1.0#1...
Building brotli:x64-windows@1.1.0#1...
-- Using cached google-brotli-v1.1.0.tar.gz.
-- Cleaning sources at C:/Users/f21br/vcpkg/buildtrees/brotli/src/v1.1.0-958bece74c.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/f21br/vcpkg/downloads/google-brotli-v1.1.0.tar.gz
-- Applying patch install.patch
-- Applying patch fix-arm-uwp.patch
-- Applying patch pkgconfig.patch
-- Applying patch emscripten.patch
-- Using source at C:/Users/f21br/vcpkg/buildtrees/brotli/src/v1.1.0-958bece74c.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/Users/f21br/vcpkg/buildtrees/brotli/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\f21br\vcpkg\buildtrees\brotli\config-x64-windows-dbg-CMakeCache.txt.log
      C:\Users\f21br\vcpkg\buildtrees\brotli\config-x64-windows-rel-CMakeCache.txt.log
      C:\Users\f21br\vcpkg\buildtrees\brotli\config-x64-windows-dbg-CMakeConfigureLog.yaml.log
      C:\Users\f21br\vcpkg\buildtrees\brotli\config-x64-windows-rel-CMakeConfigureLog.yaml.log
      C:\Users\f21br\vcpkg\buildtrees\brotli\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:269 (vcpkg_execute_required_process)
  ports/brotli/portfile.cmake:14 (vcpkg_cmake_configure)
  scripts/ports.cmake:192 (include)

error: building brotli:x64-windows failed with: BUILD_FAILED

**Comment by greenozon** [comment]
attaching logs might shed more light into your case...

**Comment by BrandonKim-05** [comment]
I apologize, I've attached the logs at the top of the post. Thank you for the suggestion.

**Comment by greenozon** [comment]
Thanks

somethign very basic is missed in your env

for example, vcpkg can't find the system library kernel32.lib
which is part of Windows SDK

in my case it is located over here:

"c:\Program Files (x86)\Windows Kits\10\Lib\10.0.20348.0\um\x64\kernel32.Lib" 

another issue - rc (resource compiler could not be found)

in my case it's over here
"c:\Program Files (x86)\Windows Kits\10\bin\10.0.20348.0\x64\rc.exe" 

so looks like simlar reason..



could you double check you have installed Windws SDK and you could locate that library?

**Comment by BrandonKim-05** [comment]
Thank you so much, a fresh install of Windows SDK through Visual Studio 2022 Installer fixed the issue.
