### ISSUE TITLE
Xerces 3.2.1

### ISSUE THREAD

**Issue by e-master** [Microsoft/vcpkg#4200]
Can you please update the xerces-c package to the latest version of the library (3.2.1)?

**Comment by jwillemsen** [comment]
Looks the packages xerces-c is 3.2.2-6 so looks this one has already been resolved

**Comment by NancyLi1013** [comment]
@e-master , the package has been updated to the version 3.2.2-6. Please take a look.

**Comment by e-master** [comment]
Yes, it's good, thank you vm.
