### ISSUE TITLE
opencv4 release 4.9.0 (static windows triplets [x86/x64])

### ISSUE THREAD

**Issue by gdiObjects** [microsoft/vcpkg#42004]
**Describe the bug**
In project source code headers, the following includes are no longer valid:
#include <opencv2/opencv.hpp>
#include <opencv2/core/ocl.hpp>
 as opencv2 is now a subdirectory of opencv4 and includes referenced in opencv2/opencv.hpp reference (as an example): 
#include "opencv2/opencv_modules.hpp" this results in the following error:
"D:\vcpkg\installed\x64-windows-static\include\opencv4\opencv2\opencv.hpp(48,10): error C1083: Cannot open include file: 'opencv2/opencv_modules.hpp': No such file or directory"

**Environment**
- OS: Windows 10 Pro
- Compiler: Microsoft Visual Studio Community 2022 Version 17.11.5, Visual C++ 2022   00482-90000-00000-AA445, Microsoft Visual C++ 2022

**To Reproduce**
Steps to reproduce the behavior: Note '--recurse' may be necessary.

vcpkg install opencv[core,default-features]:x64-windows-static
vcpkg install opencv[core,default-features]:x86-windows-static
vcpkg install opencv4[calib3d,core,default-features,dnn,dshow,fs,gapi,highgui,intrinsics,jpeg,openjpeg,openmp,png,quirc,thread,tiff,webp,win32ui]:x64-windows-static
vcpkg install opencv4[calib3d,core,default-features,dnn,dshow,fs,gapi,highgui,intrinsics,jpeg,openjpeg,openmp,png,quirc,thread,tiff,webp,win32ui]:x86-windows-static

**Expected behavior**
No Compile Errors

**Failure logs**
-None

**Additional context**
Previous version (triplets) worked as expected.

**Comment by dg0yt** [comment]
> In project source code headers, the following includes are no longer valid:
> #include <opencv2/opencv.hpp>
> #include <opencv2/core/ocl.hpp>
> as opencv2 is now a subdirectory of opencv4 and includes referenced in opencv2/opencv.hpp reference (as an example):
> #include "opencv2/opencv_modules.hpp" this results in the following error:
> "D:\vcpkg\installed\x64-windows-static\include\opencv4\opencv2\opencv.hpp(48,10): error C1083: Cannot open include file: 'opencv2/opencv_modules.hpp': No such file or directory"

When `#include <opencv2/opencv.hpp>` is resolved to  
`D:\vcpkg\installed\x64-windows-static\include\opencv4\opencv2\opencv.hpp`, 
then `D:\vcpkg\installed\x64-windows-static\include\opencv4` is in the search path,  
and then `opencv2/opencv_modules.hpp` should be found, too.

(At least my `opencv4[core,contrib]` has `include/opencv4/opencv2/opencv_modules.hpp`.)

**Comment by gdiObjects** [comment]
I've just created the following issue: [opencv4] Build error on x64-windows-static #42030

I removed all opencv* installs and tried from scratch installing opencv4[core,contrib]:x64-windows-static and the install failed.

**Comment by theoractice** [comment]
I have the same issue. Just fixed the folder hierarchy and everything worked. 
Don't know why there is an `opencv4` folder.

**Comment by dg0yt** [comment]
> I've just created the following issue: [opencv4] Build error on x64-windows-static [#42030](https://github.com/microsoft/vcpkg/issues/42030)

That's an unrlelated problem *building* opencv4. Fix pending in #42015.

**Comment by dg0yt** [comment]
> Don't know why there is an opencv4 folder.

CC @cenit

**Comment by gdiObjects** [comment]
> > I've just created the following issue: [opencv4] Build error on x64-windows-static [#42030](https://github.com/microsoft/vcpkg/issues/42030)
> 
> That's an unrelated problem with _building_ opencv4. Fix pending in [#42015](https://github.com/microsoft/vcpkg/pull/42015).

I wanted to test from a clean install because you said, '(At least my opencv4[core,contrib] has include/opencv4/opencv2/opencv_modules.hpp.)'

**Comment by dg0yt** [comment]
Now you know why I have `opencv4[core,contrib]` 😆 
With https://github.com/microsoft/vcpkg/issues/42030, it is `opencv4[core,contrib,calib3d]`.

**Comment by cenit** [comment]
> > Don't know why there is an opencv4 folder.
> 
> CC [@cenit](https://github.com/cenit)

https://docs.opencv.org/4.x/d7/d9f/tutorial_linux_install.html

as you can see, opencv when built from source is now installed in an opencv4 subfolder.
This is considered the best approach, what you usually find in all systems, and vcpkg moved to that configuration. It is anyway fully masked if you use pkgconfig or cmake. In case of vs integration you might have to manually add opencv4 subfolder to the default include path

**Comment by gdiObjects** [comment]
> > > Don't know why there is an opencv4 folder.
> > 
> > 
> > CC [@cenit](https://github.com/cenit)
> 
> https://docs.opencv.org/4.x/d7/d9f/tutorial_linux_install.html
> 
> ![Image](https://github.com/user-attachments/assets/1a01d8a4-0158-45b7-bce1-5215e59a4542)
> 
> as you can see, opencv when built from source is now installed in an opencv4 subfolder. This is considered the best approach, what you usually find in all systems, and vcpkg moved to that configuration. It is anyway fully masked if you use pkgconfig or cmake. In case of vs integration you might have to manually add opencv4 subfolder to the default include path

This should work (include as default path x86 & x64).  I'll test as soon as https://github.com/microsoft/vcpkg/issues/42030 is resolved.

**Comment by theoractice** [comment]
> > > Don't know why there is an opencv4 folder.
> > 
> > 
> > CC [@cenit](https://github.com/cenit)
> 
> https://docs.opencv.org/4.x/d7/d9f/tutorial_linux_install.html
> 
> ![Image](https://github.com/user-attachments/assets/1a01d8a4-0158-45b7-bce1-5215e59a4542)
> 
> as you can see, opencv when built from source is now installed in an opencv4 subfolder. This is considered the best approach, what you usually find in all systems, and vcpkg moved to that configuration. It is anyway fully masked if you use pkgconfig or cmake. In case of vs integration you might have to manually add opencv4 subfolder to the default include path

This "best approach" is for all _Linux_ systems, however there's no "best approach“ for _Windows_. So is there any way to keep the old folder hierarchy only for Windows?
I mean, it's still reasonable to have a opencv4 subfolder under Windows, but you may expect lots of "cannot open opencv.hpp" issues from Windows users from now on.

**Comment by cenit** [comment]
I assume the very vast majority of projects will not depend on msvc integration and accept to try to answer to those issues...
many issues already appear if you google this error, and then people realize they are under an opencv4 subfolder.
Making folder structure os-specific does not look very sane. Windows official opencv installer already creates a specific folder for opencv4, so to be honest i don't think this should be a huge problem

**Comment by gdiObjects** [comment]
I added it as include path for each of my x86 & x64 targets:

D:\vcpkg\installed\x64-windows-static\include\opencv4 (for all x64 configurations)
D:\vcpkg\installed\x86-windows-static\include\opencv4 (for all x86 configurations)

and it solved my issues.

**Comment by theoractice** [comment]
> I assume the very vast majority of projects will not depend on msvc integration and I accept to try to answer to those issues...
> many issues already appear if you google this error, and then people realize headers are now under an opencv4 subfolder.
> Making folder structure os-specific does not look very sane. Windows official opencv installer already creates a specific folder for opencv4, so to be honest i don't think this should be a huge problem 

Correct me if I'm wrong, but I just tested windows installer version 4.9 and 4.10 and I didn't find the opencv4 folder. Are they creating this folder in some previous releases but finally decided not to do this?

Anyway I think it's best to keep the same behaviour with the official installers, no matter it's windows or linux. If the official windows installer really creates an opencv4 folder then I completely agree with you, but I don't see any evidence as for now.

**Comment by dg0yt** [comment]
On the positive side, vcpkg CI can now build and test opencv2 and opencv3.

**Comment by cenit** [comment]
> On the positive side, vcpkg CI can now build and test opencv2 and opencv3.

that's another point. Without the opencv4 subfolder that would have been impossible

**Comment by cenit** [comment]
> Anyway I think it's best to keep the same behaviour with the official installers, no matter it's windows or linux. If the official windows installer really creates an opencv4 folder then I completely agree with you, but I don't see any evidence as for now.

installers on windows just create an isolated folder in which opencv4 is self contained and you have to define it in your include party somehow depending on the toolchain

**Comment by Mengna-Li** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by molesmoke** [comment]
> > > Anyway I think it's best to keep the same behaviour with the official installers, no matter it's windows or linux. If the official windows installer really creates an opencv4 folder then I completely agree with you, but I don't see any evidence as for now.
> > 
> > 
> > installers on windows just create an isolated folder in which opencv4 is self contained and you have to define it in your include path somehow depending on the toolchain (meaning headers are not mixed in any other common include path, not that it even exists as a concept in windows apart from maybe some sdk folders)
> 
> I am just saying that this is a behaviour change (while OpenCV itself does not). The CI for opencv2/3 is good, though.
> 
> Visual Studio users can use this props file:
> 
> ```
> <Project>
>   <ItemDefinitionGroup Label="Globals">
>     <ClCompile>
>       <AdditionalIncludeDirectories>$(VcPkgRoot)\installed\$(VcPkgTriplet)\include\opencv4;$(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
>     </ClCompile>
>   </ItemDefinitionGroup>
> </Project>
> ```

A small improvement would be to use VcpkgInstalledDir, which will also work in manifest mode:

`<AdditionalIncludeDirectories>$(VcpkgInstalledDir)\$(VcpkgTriplet)\include\opencv4;$(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>`

**Comment by theoractice** [comment]
@molesmoke oh really? this macro is not listed in the vs2022 macro submenu. will try it when I have time. thanks.

**Comment by mfi7000** [comment]
Adding a symlink named opencv2 in the  include folder that points to opencv4/opencv2 solved it for me.
