### ISSUE TITLE
[lcms] update to <2.16>

### ISSUE THREAD

**Issue by MrGuoGuo** [microsoft/vcpkg#42010]
### Library name

lcms

### New version number

2.16

### Other information that may be useful (release notes, etc...)

https://github.com/mm2/Little-CMS/releases/tag/lcms2.16

**Comment by Mengna-Li** [comment]
Fixing by https://github.com/microsoft/vcpkg/pull/36847.

**Comment by dg0yt** [comment]
> Fixing by [#36847](https://github.com/microsoft/vcpkg/pull/36847).

Is that PR being worked on?

**Comment by dg0yt** [comment]
Duplicates #35835.

**Comment by MrGuoGuo** [comment]
When should we merge into the master branch?

**Comment by MrGuoGuo** [comment]
> Fixing by [#36847](https://github.com/microsoft/vcpkg/pull/36847).

When should we merge into the master branch?

**Comment by Mengna-Li** [comment]
Fixed by https://github.com/microsoft/vcpkg/pull/42187.
