### ISSUE TITLE
[boost-core] Build error on x64-windows-static-md-release

### ISSUE THREAD

**Issue by ejaysaya** [microsoft/vcpkg#42031]
Copy issue body from C:/_work-mumble/vcpkg/installed/vcpkg/issue_body.md

Detecting compiler hash for triplet x86-windows-static-md-release...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x86/cl.exe
Restored 0 package(s) from C:\Users\eugdev\AppData\Local\vcpkg\archives in 3.47 ms. Use --debug to see more details.
Installing 1/233 boost-core:x64-windows-static-md-release@1.85.0...
Building boost-core:x64-windows-static-md-release@1.85.0...
C:\_work-mumble\vcpkg\triplets\community\x64-windows-static-md-release.cmake: info: loaded community triplet from here. Community triplets are not built in the curated registry and are thus less likely to succeed.
-- Downloading https://github.com/boostorg/core/archive/boost-1.85.0.tar.gz -> boostorg-core-boost-1.85.0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Disabling metrics because vcpkg.disable-metrics exists
[DEBUG] Trying to load bundleconfig from C:\_work-mumble\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: C:\_work-mumble\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://github.com/boostorg/core/archive/boost-1.85.0.tar.gz
[DEBUG] Trying to hash C:\_work-mumble\vcpkg\downloads\boostorg-core-boost-1.85.0.tar.gz.7504.part
[DEBUG] C:\_work-mumble\vcpkg\downloads\boostorg-core-boost-1.85.0.tar.gz.7504.part has hash a1e774c98b537dd42018742af68f5889af1afd4e6c9809399987124e56a3b9ae2f20e8173170bc6fc0ad76fb95e2da7b9d385a4037e9ee12011fc02bf8f7e009
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/boostorg/core/archive/boost-1.85.0.tar.gz
File: C:\_work-mumble\vcpkg\downloads\boostorg-core-boost-1.85.0.tar.gz.7504.part
Expected hash: 3a7be75e52f5c20830fccb9e7391a1e4556ebb072e6324df95b1ba38bed46e24f4c9f27a62a1099eddc90f2ac1ede083f0c850e2dc27fd42375d028516f675b3
Actual hash: a1e774c98b537dd42018742af68f5889af1afd4e6c9809399987124e56a3b9ae2f20e8173170bc6fc0ad76fb95e2da7b9d385a4037e9ee12011fc02bf8f7e009
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(997):
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 2us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 254us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 1.4 s (1367281us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/boost-core/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:175 (include)

error: building boost-core:x64-windows-static-md-release failed with: BUILD_FAILED
Elapsed time to handle boost-core:x64-windows-static-md-release: 1.4 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-core
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[boost-core]+Build+error+on+x64-windows-static-md-release&body=Copy+issue+body+from+C%3A%2F_work-mumble%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by dg0yt** [comment]
Move your baseline to a8954b904ad2a6939ecd8fc213e87702fa1243ea (boost-core 1.85.0#2). Boost changed the content of 1.85.0, so hashes had to be updated.

**Comment by ejaysaya** [comment]
so what i did was downloaded the latest from https://github.com/microsoft/vcpkg/ instead of https://github.com/mumble-voip/vcpkg but we'll see.. THANKS! i'll let you know later again coz i have reset all i did

**Comment by ejaysaya** [comment]
now i only got this problem

C:\dev\mumble\build>cmake -G "NMake Makefiles" "-DVCPKG_TARGET_TRIPLET=x64-windows-static-md" "-Dstatic=ON" "-DCMAKE_TOOLCHAIN_FILE=C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DIce_HOME=C:/dev/vcpkg/installed/x64-windows-static-md" "-DCMAKE_BUILD_TYPE=Release" ..
-- Found Python interpreter version 3.9.13
-- Using Win7 as the oldest supported Windows version
-- Using (among others) the following compiler flags: /WX;/W4;/O2;/bigobj;/options:strict
-- ##################################################
-- Mumble version:              1.6.0
-- Architecture:                x86
-- Build type:                  Release
-- Using LTO in release builds: ON
-- ##################################################
CMake Error at cmake/pkg-utils.cmake:87 (message):
  Qt6 component not found: Core 6.2
Call Stack (most recent call first):
  src/CMakeLists.txt:20 (find_pkg)

**Comment by dg0yt** [comment]
Maybe you ask mumble-voip for updates? With their fork, they have to do maintenance.
