### ISSUE TITLE
applocal.ps1 dependency resolution significantly slowing down cmake build

### ISSUE THREAD

**Issue by ryanstocks00** [microsoft/vcpkg#42054]
### Discussed in https://github.com/microsoft/vcpkg/discussions/41941

<div type='discussions-op-text'>

<sup>Originally posted by **ryanstocks00** November  4, 2024</sup>
The command
```
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -executionpolicy Bypass -file ...vcpkg-src/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary ....exe -installedDir vcpkg_installed/x64-mingw-dynamic/bin -v
```
seems to take a long time to run (~20 seconds) and is added to the link command of my executable so is run every time I modify a file and recompile (often this is ~80% of my overall compilation time). I only have 4 dependencies (opencv, gdal, pdal and qtbase) so this is quite frustrating and unnecessary when just making minor modifications. Any ideas why this is so slow and how to speed it up?</div>

**Comment by dg0yt** [comment]
> I only have 4 dependencies (opencv, gdal, pdal and qtbase)

Only 4, but they are elephants, not mice. They pull in a big zoo of dynamic link libraries. This is what that step does: walk the tree of runtime dependencies of your executable and put them next to it. And Qt plugins, too. The step can be turned off (at least in cmake builds, but it doesn't give you the same chance to run the executable with the right runtime.

(Of course it is reasonable to not want to wait 20 seconds.)

**Comment by ryanstocks00** [comment]
Thanks @dg0yt - how do I turn that step off for cmake builds? I primarily just want to disable it for faster development after the first compilation run

**Comment by Osyotr** [comment]
https://github.com/microsoft/vcpkg/blob/813a241fb83adad503a391facaa6aa634631accc/scripts/buildsystems/vcpkg.cmake#L48-L52

**Comment by Mengna-Li** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
