### ISSUE TITLE
Is there any plan to support vlc

### ISSUE THREAD

**Issue by luoyouchun** [microsoft/vcpkg#4206]
Is there any plan to support vlc?

**Comment by icedream2linxi** [comment]
你有需要的话，自己写 port 提交 PR。他们是不管添加新库的。

**Comment by Voskrese** [comment]
double https://github.com/Microsoft/vcpkg/issues/1578

**Comment by NancyLi1013** [comment]
Thanks for posting this request. Please pay attention to the progress of issue #1578.
