### ISSUE TITLE
[theia] update to 0.8

### ISSUE THREAD

**Issue by StonerLing** [microsoft/vcpkg#42099]
### Library name

theia

### New version number

0.8

### Other information that may be useful (release notes, etc...)

It appears that when the theia library is installed automatically, the command line interface shows version 0.8, but the installation result is version 0.7 (as indicated in the CMake config file).

**Comment by dg0yt** [comment]
Upstream seems to be inactive since 5 years, Should this really be fixed *now*?

**Comment by StonerLing** [comment]
I believe this bug is due to an error by the author of Theia, and the code repository has not been updated further. The latest master branch has undergone significant changes without a new version being released. However, for developers using vcpkg to manage and utilize the Theia library, the mismatch in version information may lead to some misunderstandings. In summary, this is a fix that is desirable but not mandatory.

**Comment by dg0yt** [comment]
> I believe this bug is due to an error by the author of Theia, and the code repository has not been updated further.

I agree.

> The latest master branch has undergone significant changes without a new version being released.

And still, changes stopped 5 years ago.

> However, for developers using vcpkg to manage and utilize the Theia library, the mismatch in version information may lead to some misunderstandings. In summary, this is a fix that is desirable but not mandatory.

If a fix is applied in vcpkg but not by other packaging providers, this might be even more confusing and causing lock-in. As a vcpkg user, you can rely on versioning in manifest mode.

**Comment by StonerLing** [comment]
> If a fix is applied in vcpkg but not by other packaging providers, this might be even more confusing and causing lock-in

I got it.

The long period without updates has also resulted in many minor bugs. I've decided to compile from the source code myself~
