### ISSUE TITLE
[libconfig] static lib of libconfig are not available in the package

### ISSUE THREAD

**Issue by flarive** [microsoft/vcpkg#42109]
### Is your feature request related to a problem? Please describe.

Hello,

I would expect to find static versions of the libconfig .lib files.
libconfig++s.lib (for release) and libconfig++ds.lib (for debug), but are not present in the vspkg package.

I'm using vcpkg.json manifest in my project :

{
  "dependencies": [
    "eigen3",
    "glm",
    "libconfig",
    "pcg",
    "stb",
    "tinyobjloader",
    "glfw3"
  ]
}

### Proposed solution

Fix the libconfig port to include libconfig++s.lib and libconfig++ds.lib

May be not as simple as that, i don't know.

**Comment by dg0yt** [comment]
> I would expect to find static versions of the libconfig .lib files.

In vcpkg, this means you need to choose a target triplet with static library linkage, e.g. x64-windows-static or x64-windows-static-md.

> libconfig++s.lib (for release) and libconfig++ds.lib (for debug), but are not present in the vspkg package.

In vcpkg, both release and debug library are named `libconfig.lib`. From CI build logs:
~~~
libconfig:x64-windows-static:/debug/lib/libconfig++.lib
libconfig:x64-windows-static:/debug/lib/libconfig.lib
libconfig:x64-windows-static:/include/libconfig.h
libconfig:x64-windows-static:/include/libconfig.h++
libconfig:x64-windows-static:/include/libconfig.hh
libconfig:x64-windows-static:/lib/libconfig++.lib
libconfig:x64-windows-static:/lib/libconfig.lib
...
~~~

**Comment by flarive** [comment]
Thanks for your answer !
Where am I supposed to use target triplet ? In my vcpkg.json file it doesn't seems to work.

{
  "dependencies": [
    "eigen3",
    "glm",
    "libconfig:x64-windows-static",
    "pcg",
    "stb",
    "tinyobjloader",
    "glfw3"
  ]
}

**Comment by dg0yt** [comment]
How do you use your manifest? There are different ways, for command line, CMake, msbuild.
https://learn.microsoft.com/en-us/vcpkg/concepts/triplets#triplet-selection

**Comment by flarive** [comment]
I'm using msbuild
