### ISSUE TITLE
[fmt, spdlog] "/utf8 error"build failure

### ISSUE THREAD

**Issue by ysyecust** [microsoft/vcpkg#42132]
### Operating system

Windows

### Compiler

Clang

### Steps to reproduce the behavior

```Shell
like https://github.com/microsoft/vcpkg/issues/40214 
when I use spdlog v1.14.1 it works, but when I upgrade spdlog to v1.15.0, it still have the "\utf8" error
```

### Failure logs

[build] C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -IC:/Users/YSY_e/Documents/simona2/build -IC:/Users/YSY_e/Documents/simona2/simona2/loger/include -isystem C:/vcpkg/installed/x64-windows/include -O3 -DNDEBUG -std=c++20 -D_DLL -D_MT -Xclang --dependent-lib=msvcrt -Wall -Wextra -Weffc++ -Werror=uninitialized -Werror=return-type -Wconversion -Wsign-compare -Werror=unused-result -Werror=suggest-override -Wzero-as-null-pointer-constant -Wmissing-declarations -Wold-style-cast -Wnon-virtual-dtor -Werror -finput-charset=UTF-8 /utf-8 -MD -MT simona2/loger/CMakeFiles/Logger.dir/src/logger.cpp.obj -MF simona2\loger\CMakeFiles\Logger.dir\src\logger.cpp.obj.d -o simona2/loger/CMakeFiles/Logger.dir/src/logger.cpp.obj -c C:/Users/YSY_e/Documents/simona2/simona2/loger/src/logger.cpp
[build] clang++: error: no such file or directory: '/utf-8'

**Comment by WangWeiLin-MV** [comment]
Build passed with `vcpkg install spdlog:x64-mingw-dynamic`

**Comment by ysyecust** [comment]
> Build passed with `vcpkg install spdlog:x64-mingw-dynamic`

It didn't solve the problem, still got the /utf8 error
``` shell
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --build c:/Users/YSY_e/Documents/code/simona2/build --config Debug --target Logger --
[build] [1/2   0% :: 0.004] Re-checking globbed directories...
[build] [1/2  50% :: 0.048] Building CXX object simona2/loger/CMakeFiles/Logger.dir/src/logger.cpp.obj
[build] FAILED: simona2/loger/CMakeFiles/Logger.dir/src/logger.cpp.obj 
[build] C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -IC:/Users/YSY_e/Documents/code/simona2/build -IC:/Users/YSY_e/Documents/code/simona2/simona2/loger/include -isystem C:/vcpkg/installed/x64-windows/include -O0 -g -Xclang -gcodeview -std=c++20 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -Wall -Wextra -Weffc++ -Werror=uninitialized -Werror=return-type -Wconversion -Wsign-compare -Werror=unused-result -Werror=suggest-override -Wzero-as-null-pointer-constant -Wmissing-declarations -Wold-style-cast -Wnon-virtual-dtor -Werror -finput-charset=UTF-8 /utf-8 -MD -MT simona2/loger/CMakeFiles/Logger.dir/src/logger.cpp.obj -MF simona2\loger\CMakeFiles\Logger.dir\src\logger.cpp.obj.d -o simona2/loger/CMakeFiles/Logger.dir/src/logger.cpp.obj -c C:/Users/YSY_e/Documents/code/simona2/simona2/loger/src/logger.cpp
[build] clang++: error: no such file or directory: '/utf-8'
[build] ninja: build stopped: subcommand failed.
[proc] The command: "C:\Program Files\CMake\bin\cmake.EXE" --build c:/Users/YSY_e/Documents/code/simona2/build --config Debug --target Logger -- exited with code: 1
[driver] Build completed: 00:00:00.090
[build] Build finished with exit code 1

**Comment by dg0yt** [comment]
> Build passed with `vcpkg install spdlog:x64-mingw-dynamic`

gcc or clang?

**Comment by dg0yt** [comment]
> `-isystem C:/vcpkg/installed/x64-windows/include`

This error is for triplet x64-windows which is a triplet for MSVC.

**Comment by WangWeiLin-MV** [comment]
> > Build passed with `vcpkg install spdlog:x64-mingw-dynamic`
> 
> gcc or clang?

With gcc

**Comment by hghgthifg** [comment]
I have encountered the same problem. When I tried to use clang-cl instead, another problem arised.
cl.exe works well, but that's not what I expected. I want to use clang.

**Comment by dg0yt** [comment]
AFAICT there is no triplet here for non-mingw Windows clang, regardless of frontend.

**Comment by ysyecust** [comment]
Is there a plan to fix this issue, my current solution is to switch to 77dfbee: [spdlog] update to 1.15.0 (#42076) before this commit
