### ISSUE TITLE
[libsrtp] Build error on x64-linux

### ISSUE THREAD

**Issue by TalkIsCheapGiveMeMoney** [microsoft/vcpkg#42189]
Copy issue body from /usr/local/vcpkg/installed/vcpkg/issue_body.md

Change Dir: '/usr/local/vcpkg/buildtrees/libsrtp/x64-linux-dbg'

Run Build Command(s): /usr/local/vcpkg/downloads/tools/ninja/1.10.2-linux/ninja -v -v -j5 install
[1/19] /usr/bin/cc -DHAVE_CONFIG_H -I/usr/local/vcpkg/buildtrees/libsrtp/x64-linux-dbg -I/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include -I/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include -isystem /usr/local/vcpkg/installed/x64-linux/include -fPIC -g -Wall -pedantic -Wextra -Werror -MD -MT CMakeFiles/srtp2.dir/crypto/cipher/cipher_test_cases.c.o -MF CMakeFiles/srtp2.dir/crypto/cipher/cipher_test_cases.c.o.d -o CMakeFiles/srtp2.dir/crypto/cipher/cipher_test_cases.c.o -c /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/cipher/cipher_test_cases.c
FAILED: CMakeFiles/srtp2.dir/crypto/cipher/cipher_test_cases.c.o 
/usr/bin/cc -DHAVE_CONFIG_H -I/usr/local/vcpkg/buildtrees/libsrtp/x64-linux-dbg -I/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include -I/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include -isystem /usr/local/vcpkg/installed/x64-linux/include -fPIC -g -Wall -pedantic -Wextra -Werror -MD -MT CMakeFiles/srtp2.dir/crypto/cipher/cipher_test_cases.c.o -MF CMakeFiles/srtp2.dir/crypto/cipher/cipher_test_cases.c.o.d -o CMakeFiles/srtp2.dir/crypto/cipher/cipher_test_cases.c.o -c /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/cipher/cipher_test_cases.c
In file included from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/cipher.h:48:0,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/cipher/cipher_test_cases.h:44,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/cipher/cipher_test_cases.c:37:
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include/srtp.h:1170:38: error: comma at end of enumerator list [-Werror=pedantic]
     srtp_profile_aead_aes_256_gcm = 8,
                                      ^
cc1: all warnings being treated as errors
[2/19] /usr/bin/cc -DHAVE_CONFIG_H -I/usr/local/vcpkg/buildtrees/libsrtp/x64-linux-dbg -I/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include -I/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include -isystem /usr/local/vcpkg/installed/x64-linux/include -fPIC -g -Wall -pedantic -Wextra -Werror -MD -MT CMakeFiles/srtp2.dir/crypto/cipher/null_cipher.c.o -MF CMakeFiles/srtp2.dir/crypto/cipher/null_cipher.c.o.d -o CMakeFiles/srtp2.dir/crypto/cipher/null_cipher.c.o -c /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/cipher/null_cipher.c
FAILED: CMakeFiles/srtp2.dir/crypto/cipher/null_cipher.c.o 
/usr/bin/cc -DHAVE_CONFIG_H -I/usr/local/vcpkg/buildtrees/libsrtp/x64-linux-dbg -I/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include -I/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include -isystem /usr/local/vcpkg/installed/x64-linux/include -fPIC -g -Wall -pedantic -Wextra -Werror -MD -MT CMakeFiles/srtp2.dir/crypto/cipher/null_cipher.c.o -MF CMakeFiles/srtp2.dir/crypto/cipher/null_cipher.c.o.d -o CMakeFiles/srtp2.dir/crypto/cipher/null_cipher.c.o -c /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/cipher/null_cipher.c
In file included from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/datatypes.h:49:0,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/cipher/null_cipher.c:51:
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/integers.h:136:8: error: C++ style comments are not allowed in ISO C90 [-Werror]
 #endif // WORDS_BIGENDIAN
        ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/integers.h:136:8: error: (this will be reported only once per input file) [-Werror]
In file included from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/alloc.h:48:0,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/datatypes.h:50,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/cipher/null_cipher.c:51:
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/datatypes.h:170:1: error: C++ style comments are not allowed in ISO C90 [-Werror]
 // Mac OS X / Darwin features
 ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/datatypes.h:170:1: error: (this will be reported only once per input file) [-Werror]
In file included from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/cipher/null_cipher.c:51:0:
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/datatypes.h:170:1: error: C++ style comments are not allowed in ISO C90 [-Werror]
 // Mac OS X / Darwin features
 ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/datatypes.h:170:1: error: (this will be reported only once per input file) [-Werror]
In file included from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/cipher.h:48:0,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/null_cipher.h:51,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/cipher/null_cipher.c:52:
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include/srtp.h:1170:38: error: comma at end of enumerator list [-Werror=pedantic]
     srtp_profile_aead_aes_256_gcm = 8,
                                      ^
cc1: all warnings being treated as errors
[3/19] /usr/bin/cc -DHAVE_CONFIG_H -I/usr/local/vcpkg/buildtrees/libsrtp/x64-linux-dbg -I/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include -I/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include -isystem /usr/local/vcpkg/installed/x64-linux/include -fPIC -g -Wall -pedantic -Wextra -Werror -MD -MT CMakeFiles/srtp2.dir/crypto/cipher/cipher.c.o -MF CMakeFiles/srtp2.dir/crypto/cipher/cipher.c.o.d -o CMakeFiles/srtp2.dir/crypto/cipher/cipher.c.o -c /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/cipher/cipher.c
FAILED: CMakeFiles/srtp2.dir/crypto/cipher/cipher.c.o 
/usr/bin/cc -DHAVE_CONFIG_H -I/usr/local/vcpkg/buildtrees/libsrtp/x64-linux-dbg -I/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include -I/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include -isystem /usr/local/vcpkg/installed/x64-linux/include -fPIC -g -Wall -pedantic -Wextra -Werror -MD -MT CMakeFiles/srtp2.dir/crypto/cipher/cipher.c.o -MF CMakeFiles/srtp2.dir/crypto/cipher/cipher.c.o.d -o CMakeFiles/srtp2.dir/crypto/cipher/cipher.c.o -c /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/cipher/cipher.c
In file included from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/cipher.h:48:0,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/cipher/cipher.c:51:
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include/srtp.h:1170:38: error: comma at end of enumerator list [-Werror=pedantic]
     srtp_profile_aead_aes_256_gcm = 8,
                                      ^
In file included from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/datatypes.h:49:0,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/alloc.h:48,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/cipher/cipher.c:55:
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/integers.h:136:8: error: C++ style comments are not allowed in ISO C90 [-Werror]
 #endif // WORDS_BIGENDIAN
        ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/integers.h:136:8: error: (this will be reported only once per input file) [-Werror]
In file included from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/alloc.h:48:0,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/cipher/cipher.c:55:
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/datatypes.h:170:1: error: C++ style comments are not allowed in ISO C90 [-Werror]
 // Mac OS X / Darwin features
 ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/datatypes.h:170:1: error: (this will be reported only once per input file) [-Werror]
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/cipher/cipher.c: In function ‘srtp_cipher_bits_per_second’:
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/cipher/cipher.c:647:9: error: C++ style comments are not allowed in ISO C90 [-Werror]
         // Set IV
         ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/cipher/cipher.c:647:9: error: (this will be reported only once per input file) [-Werror]
cc1: all warnings being treated as errors
[4/19] /usr/bin/cc -DHAVE_CONFIG_H -I/usr/local/vcpkg/buildtrees/libsrtp/x64-linux-dbg -I/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include -I/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include -isystem /usr/local/vcpkg/installed/x64-linux/include -fPIC -g -Wall -pedantic -Wextra -Werror -MD -MT CMakeFiles/srtp2.dir/crypto/cipher/aes_icm_ossl.c.o -MF CMakeFiles/srtp2.dir/crypto/cipher/aes_icm_ossl.c.o.d -o CMakeFiles/srtp2.dir/crypto/cipher/aes_icm_ossl.c.o -c /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/cipher/aes_icm_ossl.c
FAILED: CMakeFiles/srtp2.dir/crypto/cipher/aes_icm_ossl.c.o 
/usr/bin/cc -DHAVE_CONFIG_H -I/usr/local/vcpkg/buildtrees/libsrtp/x64-linux-dbg -I/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include -I/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include -isystem /usr/local/vcpkg/installed/x64-linux/include -fPIC -g -Wall -pedantic -Wextra -Werror -MD -MT CMakeFiles/srtp2.dir/crypto/cipher/aes_icm_ossl.c.o -MF CMakeFiles/srtp2.dir/crypto/cipher/aes_icm_ossl.c.o.d -o CMakeFiles/srtp2.dir/crypto/cipher/aes_icm_ossl.c.o -c /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/cipher/aes_icm_ossl.c
In file included from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/cipher.h:48:0,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/aes_icm_ext.h:49,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/cipher/aes_icm_ossl.c:56:
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include/srtp.h:1170:38: error: comma at end of enumerator list [-Werror=pedantic]
     srtp_profile_aead_aes_256_gcm = 8,
                                      ^
In file included from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/datatypes.h:49:0,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/aes_icm_ext.h:50,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/cipher/aes_icm_ossl.c:56:
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/integers.h:136:8: error: C++ style comments are not allowed in ISO C90 [-Werror]
 #endif // WORDS_BIGENDIAN
        ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/integers.h:136:8: error: (this will be reported only once per input file) [-Werror]
In file included from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/alloc.h:48:0,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/datatypes.h:50,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/aes_icm_ext.h:50,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/cipher/aes_icm_ossl.c:56:
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/datatypes.h:170:1: error: C++ style comments are not allowed in ISO C90 [-Werror]
 // Mac OS X / Darwin features
 ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/datatypes.h:170:1: error: (this will be reported only once per input file) [-Werror]
In file included from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/aes_icm_ext.h:50:0,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/cipher/aes_icm_ossl.c:56:
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/datatypes.h:170:1: error: C++ style comments are not allowed in ISO C90 [-Werror]
 // Mac OS X / Darwin features
 ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/datatypes.h:170:1: error: (this will be reported only once per input file) [-Werror]
cc1: all warnings being treated as errors
[5/19] /usr/bin/cc -DHAVE_CONFIG_H -I/usr/local/vcpkg/buildtrees/libsrtp/x64-linux-dbg -I/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include -I/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include -isystem /usr/local/vcpkg/installed/x64-linux/include -fPIC -g -Wall -pedantic -Wextra -Werror -MD -MT CMakeFiles/srtp2.dir/srtp/srtp.c.o -MF CMakeFiles/srtp2.dir/srtp/srtp.c.o.d -o CMakeFiles/srtp2.dir/srtp/srtp.c.o -c /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/srtp/srtp.c
FAILED: CMakeFiles/srtp2.dir/srtp/srtp.c.o 
/usr/bin/cc -DHAVE_CONFIG_H -I/usr/local/vcpkg/buildtrees/libsrtp/x64-linux-dbg -I/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include -I/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include -isystem /usr/local/vcpkg/installed/x64-linux/include -fPIC -g -Wall -pedantic -Wextra -Werror -MD -MT CMakeFiles/srtp2.dir/srtp/srtp.c.o -MF CMakeFiles/srtp2.dir/srtp/srtp.c.o.d -o CMakeFiles/srtp2.dir/srtp/srtp.c.o -c /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/srtp/srtp.c
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/srtp/srtp.c:45:1: error: C++ style comments are not allowed in ISO C90 [-Werror]
 // Leave this as the top level import. Ensures the existence of defines
 ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/srtp/srtp.c:45:1: error: (this will be reported only once per input file) [-Werror]
In file included from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/srtp/srtp.c:48:0:
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include/srtp_priv.h:48:1: error: C++ style comments are not allowed in ISO C90 [-Werror]
 // Leave this as the top level import. Ensures the existence of defines
 ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include/srtp_priv.h:48:1: error: (this will be reported only once per input file) [-Werror]
In file included from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include/srtp_priv.h:51:0,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/srtp/srtp.c:48:
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include/srtp.h:1170:38: error: comma at end of enumerator list [-Werror=pedantic]
     srtp_profile_aead_aes_256_gcm = 8,
                                      ^
In file included from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/datatypes.h:49:0,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/rdbx.h:50,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include/srtp_priv.h:52,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/srtp/srtp.c:48:
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/integers.h:136:8: error: C++ style comments are not allowed in ISO C90 [-Werror]
 #endif // WORDS_BIGENDIAN
        ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/integers.h:136:8: error: (this will be reported only once per input file) [-Werror]
In file included from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/alloc.h:48:0,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/datatypes.h:50,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/rdbx.h:50,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include/srtp_priv.h:52,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/srtp/srtp.c:48:
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/datatypes.h:170:1: error: C++ style comments are not allowed in ISO C90 [-Werror]
 // Mac OS X / Darwin features
 ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/datatypes.h:170:1: error: (this will be reported only once per input file) [-Werror]
In file included from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/rdbx.h:50:0,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include/srtp_priv.h:52,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/srtp/srtp.c:48:
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/datatypes.h:170:1: error: C++ style comments are not allowed in ISO C90 [-Werror]
 // Mac OS X / Darwin features
 ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/datatypes.h:170:1: error: (this will be reported only once per input file) [-Werror]
In file included from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include/srtp_priv.h:54:0,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/srtp/srtp.c:48:
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/integers.h:136:8: error: C++ style comments are not allowed in ISO C90 [-Werror]
 #endif // WORDS_BIGENDIAN
        ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/crypto/include/integers.h:136:8: error: (this will be reported only once per input file) [-Werror]
In file included from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/srtp/srtp.c:48:0:
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include/srtp_priv.h:182:5: error: type of bit-field ‘cc’ is a GCC extension [-Werror=pedantic]
     unsigned char cc : 4;      /* CSRC count             */
     ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include/srtp_priv.h:183:5: error: type of bit-field ‘x’ is a GCC extension [-Werror=pedantic]
     unsigned char x : 1;       /* header extension flag  */
     ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include/srtp_priv.h:184:5: error: type of bit-field ‘p’ is a GCC extension [-Werror=pedantic]
     unsigned char p : 1;       /* padding flag           */
     ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include/srtp_priv.h:185:5: error: type of bit-field ‘version’ is a GCC extension [-Werror=pedantic]
     unsigned char version : 2; /* protocol version       */
     ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include/srtp_priv.h:186:5: error: type of bit-field ‘pt’ is a GCC extension [-Werror=pedantic]
     unsigned char pt : 7;      /* payload type           */
     ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include/srtp_priv.h:187:5: error: type of bit-field ‘m’ is a GCC extension [-Werror=pedantic]
     unsigned char m : 1;       /* marker bit             */
     ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include/srtp_priv.h:224:5: error: type of bit-field ‘rc’ is a GCC extension [-Werror=pedantic]
     unsigned char rc : 5;      /* reception report count */
     ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include/srtp_priv.h:225:5: error: type of bit-field ‘p’ is a GCC extension [-Werror=pedantic]
     unsigned char p : 1;       /* padding flag           */
     ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include/srtp_priv.h:226:5: error: type of bit-field ‘version’ is a GCC extension [-Werror=pedantic]
     unsigned char version : 2; /* protocol version       */
     ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include/srtp_priv.h:227:5: error: type of bit-field ‘pt’ is a GCC extension [-Werror=pedantic]
     unsigned char pt : 8;      /* payload type           */
     ^
In file included from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include/stream_list_priv.h:48:0,
                 from /usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/srtp/srtp.c:49:
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include/srtp_priv.h:48:1: error: C++ style comments are not allowed in ISO C90 [-Werror]
 // Leave this as the top level import. Ensures the existence of defines
 ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/include/srtp_priv.h:48:1: error: (this will be reported only once per input file) [-Werror]
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/srtp/srtp.c: In function ‘srtp_remove_and_dealloc_streams’:
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/srtp/srtp.c:318:12: error: initializer element is not computable at load time [-Werror]
     struct remove_and_dealloc_streams_data data = { srtp_err_status_ok, list,
            ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/srtp/srtp.c:319:53: error: initializer element is not computable at load time [-Werror]
                                                     template };
                                                     ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/srtp/srtp.c: In function ‘srtp_stream_init_keys’:
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/srtp/srtp.c:958:45: error: use of C99 long long integer constant [-Werror=long-long]
     srtp_key_limit_set(session_keys->limit, 0xffffffffffffLL);
                                             ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/srtp/srtp.c: In function ‘update_template_streams’:
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/srtp/srtp.c:3176:12: error: initializer element is not computable at load time [-Werror]
     struct update_template_stream_data data = { srtp_err_status_ok, session,
            ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/srtp/srtp.c:3177:49: error: initializer element is not computable at load time [-Werror]
                                                 new_stream_template,
                                                 ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/srtp/srtp.c:3178:49: error: initializer element is not computable at load time [-Werror]
                                                 new_stream_list };
                                                 ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/srtp/srtp.c:3176:5: error: ISO C90 forbids mixed declarations and code [-Werror=pedantic]
     struct update_template_stream_data data = { srtp_err_status_ok, session,
     ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/srtp/srtp.c: In function ‘get_protect_trailer_length’:
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/srtp/srtp.c:4704:12: error: initializer element is not computable at load time [-Werror]
     struct get_protect_trailer_length_data data = { 0, 0, is_rtp, use_mki,
            ^
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/srtp/srtp.c:4704:12: error: initializer element is not computable at load time [-Werror]
/usr/local/vcpkg/buildtrees/libsrtp/src/v2.5.0-4f54facd34.clean/srtp/srtp.c:4705:53: error: initializer element is not computable at load time [-Werror]
                                                     mki_index };
                                                     ^
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.

**Comment by jimwang118** [comment]
Sorry, i cannot reproduce this issue locally.
![Image](https://github.com/user-attachments/assets/44a03d36-44d6-4622-9e06-15c6b37b5547)

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
