### ISSUE TITLE
Build failure on x64-windows due to Ninja parameter issue

### ISSUE THREAD

**Issue by greed-106** [microsoft/vcpkg#42224]
**Problem Description**

When installing `fmt` or other libraries, the following error message occurs:

```
Command failed: D:/ymj/code/cpp/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe -v
```

Running the `ninja -v` command locally also fails, but using `ninja --version` works as expected, displaying the version correctly. I suspect this might be caused by an incorrect parameter used when calling Ninja.

Additionally, vcpkg uses its own downloaded version of Ninja instead of the one set in my system's environment variables, which raises further questions.

---

**Steps to Reproduce**

1. On a Windows system, attempt to install `fmt` using the following command:

   ```
   ./vcpkg install fmt
   ```

2. The error occurs, and the full output is as follows:

   ```
   PS D:\ymj\code\cpp\vcpkg> ./vcpkg install fmt
   Computing installation plan...
   The following packages will be built and installed:
    fmt:x64-windows@11.0.2#1
   Detecting compiler hash for triplet x64-windows...
   -- Automatically setting %HTTP(S)_PROXY% environment variables to "127.0.0.1:7890".
   Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe
   Restored 0 package(s) from C:\Users\ymj\AppData\Local\vcpkg\archives in 98.6 us. Use --debug to see more details.
   Installing 1/1 fmt:x64-windows@11.0.2#1...
   Building fmt:x64-windows@11.0.2#1...
   -- Using cached fmtlib-fmt-11.0.2.tar.gz.
   -- Cleaning sources at D:/ymj/code/cpp/vcpkg/buildtrees/fmt/src/11.0.2-c30c0a133f.clean. Use --editable to skip cleaning for the packages you specify.
   -- Extracting source D:/ymj/code/cpp/vcpkg/downloads/fmtlib-fmt-11.0.2.tar.gz
   -- Applying patch fix-write-batch.patch
   -- Applying patch fix-pass-utf-8-only-if-the-compiler-is-MSVC-at-build.patch
   -- Using source at D:/ymj/code/cpp/vcpkg/buildtrees/fmt/src/11.0.2-c30c0a133f.clean
   -- Configuring x64-windows
   CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: D:/ymj/code/cpp/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe -v
    Working Directory: D:/ymj/code/cpp/vcpkg/buildtrees/fmt/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\ymj\code\cpp\vcpkg\buildtrees\fmt\config-x64-windows-dbg-CMakeCache.txt.log
      D:\ymj\code\cpp\vcpkg\buildtrees\fmt\config-x64-windows-rel-CMakeCache.txt.log
      D:\ymj\code\cpp\vcpkg\buildtrees\fmt\config-x64-windows-dbg-CMakeConfigureLog.yaml.log
      D:\ymj\code\cpp\vcpkg\buildtrees\fmt\config-x64-windows-rel-CMakeConfigureLog.yaml.log
      D:\ymj\code\cpp\vcpkg\buildtrees\fmt\config-x64-windows-out.log
   Call Stack (most recent call first):
     installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:269 (vcpkg_execute_required_process)
     ports/fmt/portfile.cmake:12 (vcpkg_cmake_configure)
     scripts/ports.cmake:196 (include)
   
   
   error: building fmt:x64-windows failed with: BUILD_FAILED
   See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
   Elapsed time to handle fmt:x64-windows: 8.4 s
   Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
   Then check for known issues at:
     https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+fmt
   You can submit a new issue at:
     https://github.com/microsoft/vcpkg/issues/new?title=[fmt]+Build+error+on+x64-windows&body=Copy+issue+body+from+D%3A%2Fymj%2Fcode%2Fcpp%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
   
   PS D:\ymj\code\cpp\vcpkg>
   ```

3. Attempting to install other libraries results in the same error message.

---

**Environment Information**

- **Operating System**: Windows 11
- **Compiler**: MSVC, version 14.41.34120
- **vcpkg Version**: Latest master branch
- **Ninja Version**:
  - vcpkg-downloaded version: 1.10.2
  - System environment version: 1.12.1

---

**Attempts to Resolve**

1. Updated vcpkg and the port files using `git pull` and `vcpkg update`, but the issue persists.
2. Tested Ninja commands:
   - `ninja -v` fails.
   - `ninja --version` works as expected.
3. Tested the same commands on a different machine, where everything works correctly, and the issue cannot be reproduced.

---

**Additional Information**

The issue might stem from one of the following:

1. Incorrect usage of the `-v` parameter when calling Ninja within vcpkg, which should potentially be replaced by `--version`.
2. Environment-specific issues causing a conflict, as vcpkg uses its own Ninja version instead of the system version.

Looking forward to your feedback. Thank you!

3. I noticed a similar issue discussed in [[vcpkg GitHub Discussions #39179](https://github.com/microsoft/vcpkg/discussions/39179)](https://github.com/microsoft/vcpkg/discussions/39179), where the problem also seems related to Ninja's behavior and its integration with vcpkg.

**Comment by dg0yt** [comment]
> See logs for more information:
>  ...
>    D:\ymj\code\cpp\vcpkg\buildtrees\fmt\config-x64-windows-out.log

**Comment by JonLiu1993** [comment]
Please provide this error log:
````
D:\ymj\code\cpp\vcpkg\buildtrees\fmt\config-x64-windows-out.log
````

**Comment by greed-106** [comment]
> Please provide this error log:
> 
> ```
> D:\ymj\code\cpp\vcpkg\buildtrees\fmt\config-x64-windows-out.log
> ```
Here is the file, thank you for your help!
[config-x64-windows-out.log](https://github.com/user-attachments/files/17810470/config-x64-windows-out.log)

**Comment by JonLiu1993** [comment]
Please make sure you have the following installed.
- Visual Studio Desktop development with C++.
- Windows 10 SDK or Windows 11 SDK.

**Comment by BillyONeal** [comment]
> Running the `ninja -v` command locally also fails, but using `ninja --version` works as expected, displaying the version correctly. I suspect this might be caused by an incorrect parameter used when calling Ninja.

`-v` means "verbose", not "version".

**Comment by dg0yt** [comment]
https://github.com/microsoft/vcpkg/issues/42224#issuecomment-2484813418

**Comment by johanps** [comment]
Ah, but I do have both Visual Studio Desktop development with C++ and Windows 11 SDK installed. Latest visual studio 17.12.1. 
Still getting failure because of "ninja -v"

**Comment by dg0yt** [comment]
TLDNR: `ninja -v` is not the problem. The answer is in the logs written by `ninja`, in particular the config.log.

**Comment by johanps** [comment]
Ok, thx for quick replies. Unfortunately I'm unable to figure out what to do to resolve this?
[config-x64-windows-out.log](https://github.com/user-attachments/files/17827649/config-x64-windows-out.log)

**Comment by dg0yt** [comment]
You may look into the log yourself:
~~~
CMake Error at C:/Program Files/Microsoft Visual Studio/2022/Community/VC/vcpkg/scripts/buildsystems/vcpkg.cmake:639 (_add_library):
  _add_library cannot create ALIAS target "utf8_range_lib" because target
  "utf8_range::utf8_range" does not already exist.
Call Stack (most recent call first):
  cmake/upb.cmake:28 (add_library)
  CMakeLists.txt:350 (include)
~~~
So it is an entirely different problem, and it should be properly reported separately. (This is port grpc IIUC.)
