### ISSUE TITLE
qt5-quickcontrols2:x64-windows fails to build

### ISSUE THREAD

**Issue by salvasancha** [Microsoft/vcpkg#4222]
When building Qt5, QtQuickControls2 fails.

Package: qt5-quickcontrols2:x64-windows
Vcpkg version: 0.0.113-nohash

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: C:/vcpkg/downloads/tools/jom/jom-1.1.2/jom.exe

------------------
package-build-x64-windows-dbg-out.log:
cd src\ && ( if not exist Makefile C:\vcpkg\installed\x64-windows\tools\qt5\qmake.exe -o Makefile C:\vcpkg\buildtrees\qt5-quickcontrols2\src\qtquickcontrols2-5.9.2\src\src.pro "CONFIG-=release" "CONFIG+=debug" -qtconf C:/vcpkg/buildtrees/qt5-quickcontrols2/x64-windows-dbg/qt.conf ) && C:\vcpkg\downloads\tools\jom\jom-1.1.2\jom.exe -f Makefile

cd quicktemplates2\ && ( if not exist Makefile C:\vcpkg\installed\x64-windows\tools\qt5\qmake.exe -o Makefile C:\vcpkg\buildtrees\qt5-quickcontrols2\src\qtquickcontrols2-5.9.2\src\quicktemplates2\quicktemplates2.pro "CONFIG-=release" "CONFIG+=debug" -qtconf C:/vcpkg/buildtrees/qt5-quickcontrols2/x64-windows-dbg/qt.conf ) && C:\vcpkg\downloads\tools\jom\jom-1.1.2\jom.exe -f Makefile

C:\vcpkg\downloads\tools\jom\jom-1.1.2\jom.exe -f Makefile.Debug

cl -c -Yc -Fp.pch\debug\Qt5QuickTemplates2d_pch.pch -Fo.pch\debug\Qt5QuickTemplates2d_pch.obj -nologo -Zc:wchar_t -FS -Zc:rvalueCast -Zc:inline -Zc:strictStrings -Zc:throwingNew -Zc:referenceBinding -Zi -MDd -utf-8 -D_HAS_EXCEPTIONS=0 -MP -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 /Fd.obj\debug\Qt5QuickTemplates2d.vc.pdb -DUNICODE -D_UNICODE -DWIN32 -DWIN64 -DQT_NO_FOREACH -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_BUILD_QUICKTEMPLATES2_LIB -DQT_BUILDING_QT -D_CRT_SECURE_NO_WARNINGS -D_USE_MATH_DEFINES -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x040800 -DQT_NO_EXCEPTIONS -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -D_WINDLL -IC:\vcpkg\buildtrees\qt5-quickcontrols2\src\qtquickcontrols2-5.9.2\src\quicktemplates2 -I. -IC:\vcpkg\buildtrees\qt5-quickcontrols2\src\qtquickcontrols2-5.9.2\src\quicktemplates2 -IC:\vcpkg\buildtrees\qt5-quickcontrols2\src\qtquickcontrols2-5.9.2\include -IC:\vcpkg\buildtrees\qt5-quickcontrols2\src\qtquickcontrols2-5.9.2\include\QtQuickTemplates2 -IC:\vcpkg\buildtrees\qt5-quickcontrols2\src\qtquickcontrols2-5.9.2\include\QtQuickTemplates2\5.9.2 -IC:\vcpkg\buildtrees\qt5-quickcontrols2\src\qtquickcontrols2-5.9.2\include\QtQuickTemplates2\5.9.2\QtQuickTemplates2 -I..\..\include -I..\..\include\QtQuickTemplates2 -I..\..\include\QtQuickTemplates2\5.9.2 -I..\..\include\QtQuickTemplates2\5.9.2\QtQuickTemplates2 -Itmp -IC:\vcpkg\installed\x64-windows\include -IC:\vcpkg\installed\x64-windows\include\QtQuick -IC:\vcpkg\installed\x64-windows\include\QtGui -IC:\vcpkg\installed\x64-windows\include\QtQml -IC:\vcpkg\installed\x64-windows\include\QtNetwork -IC:\vcpkg\installed\x64-windows\include\QtCore -IC:\vcpkg\installed\x64-windows\include\QtQuick\5.9.2 -IC:\vcpkg\installed\x64-windows\include\QtQuick\5.9.2\QtQuick -IC:\vcpkg\installed\x64-windows\include\QtGui\5.9.2 -IC:\vcpkg\installed\x64-windows\include\QtGui\5.9.2\QtGui -IC:\vcpkg\installed\x64-windows\include\QtQml\5.9.2 -IC:\vcpkg\installed\x64-windows\include\QtQml\5.9.2\QtQml -IC:\vcpkg\installed\x64-windows\include\QtCore\5.9.2 -IC:\vcpkg\installed\x64-windows\include\QtCore\5.9.2\QtCore -I.moc\debug -IC:\vcpkg\installed\x64-windows\include -IC:\vcpkg\installed\x64-windows\share\qt5\debug\mkspecs\win32-msvc -TP ..\..\include\QtQuickTemplates2\QtQuickTemplates2Depends

QtQuickTemplates2Depends

rc /NOLOGO -D_DEBUG -DUNICODE -D_UNICODE -DWIN32 -DWIN64 -DQT_NO_FOREACH -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_BUILD_QUICKTEMPLATES2_LIB -DQT_BUILDING_QT -D_CRT_SECURE_NO_WARNINGS -D_USE_MATH_DEFINES -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x040800 -DQT_NO_EXCEPTIONS -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -D_WINDLL -fo .obj\debug\Qt5QuickTemplates2d_resource.res Qt5QuickTemplates2d_resource.rc

------------------
package-build-x64-windows-dbg-err.log:
jom 1.1.2 - empower your cores

jom: C:\vcpkg\buildtrees\qt5-quickcontrols2\x64-windows-dbg\src\quicktemplates2\Makefile.Debug [.obj\debug\qquickabstractbutton.obj] Error 2
jom: C:\vcpkg\buildtrees\qt5-quickcontrols2\x64-windows-dbg\src\quicktemplates2\Makefile.Debug [.obj\debug\qquickitemdelegate.obj] Error 2
jom: C:\vcpkg\buildtrees\qt5-quickcontrols2\x64-windows-dbg\src\quicktemplates2\Makefile.Debug [.obj\debug\qquickswipedelegate.obj] Error 2
jom: C:\vcpkg\buildtrees\qt5-quickcontrols2\x64-windows-dbg\src\quicktemplates2\Makefile.Debug [.obj\debug\qquickshortcutcontext.obj] Error 2
jom: C:\vcpkg\buildtrees\qt5-quickcontrols2\x64-windows-dbg\src\quicktemplates2\Makefile.Debug [.obj\debug\qquicktextfield.obj] Error 2
jom: C:\vcpkg\buildtrees\qt5-quickcontrols2\x64-windows-dbg\src\quicktemplates2\Makefile.Debug [.obj\debug\qquickdelaybutton.obj] Error 2
jom: C:\vcpkg\buildtrees\qt5-quickcontrols2\x64-windows-dbg\src\quicktemplates2\Makefile.Debug [.obj\debug\qquickpagelayout.obj] Error 2
jom: C:\vcpkg\buildtrees\qt5-quickcontrols2\x64-windows-dbg\src\quicktemplates2\Makefile.Debug [.obj\debug\qquickradiobutton.obj] Error 2
jom: C:\vcpkg\buildtrees\qt5-quickcontrols2\x64-windows-dbg\src\quicktemplates2\Makefile [debug] Error 2
jom: C:\vcpkg\buildtrees\qt5-quickcontrols2\x64-windows-dbg\src\Makefile [sub-quicktemplates2-make_first] Error 2
jom: C:\vcpkg\buildtrees\qt5-quickcontrols2\x64-windows-dbg\Makefile [sub-src-make_first] Error 2

**Comment by NancyLi1013** [comment]
Hi @salvasancha, thanks for posting this issue. I can install the package successfully on my machine with the latest vcpkg. So it should be fixed now. If this is still a problem for you, please open a new issue.
