### ISSUE TITLE
The name of the vcpkg manifest model cannot be the same as the dependent package name

### ISSUE THREAD

**Issue by a819721810** [microsoft/vcpkg#42223]
**Describe the bug**
The name of the vcpkg manifest model cannot be the same as the dependent package name.
![Image](https://github.com/user-attachments/assets/6a9db8d7-c898-460e-a0c6-b6da4b063195)

![Image](https://github.com/user-attachments/assets/fa89c37e-8cb4-49da-81bb-333397ff2df2)
package  not xele-trade
![Image](https://github.com/user-attachments/assets/6d3d07e7-c46e-40f8-8e54-8fc744d61e8a)

then i change name, is ok
![Image](https://github.com/user-attachments/assets/69a529b0-d554-4f57-9e77-602d6df8ce36)
![Image](https://github.com/user-attachments/assets/4395fdb8-506f-438c-8962-ef0381dee16a)

**Environment**
Linux

**Comment by WangWeiLin-MV** [comment]
Using the latest version of vcpkg for local installation does not reproduce the issue.

Please try with latest vcpkg.

**Comment by WangWeiLin-MV** [comment]
The dependent package name allows to refer to itself, so if the name is same as another existing dependency, it will be overlaid.

**Comment by BillyONeal** [comment]
This problem is not caused by the names matching, it is caused by `vcpkg_cmake_config_fixup` defaulting to `${PORT}` for `PACKAGE_NAME`.

**Comment by WangWeiLin-MV** [comment]
In my test, if set the name in `vcpkg.json` to an exist port name, it will not install it when configuring a CMake project with vcpkg manifest mode, which doesn't quite match your screenshot.

Could you give more information to reproduce your issue?

**Comment by a819721810** [comment]
> The problem in your screenshot is not caused by the names matching, it is caused by `vcpkg_cmake_config_fixup` defaulting to `${PORT}` for `PACKAGE_NAME`, and the build in question not producing a CMake package of that name.

it will produce xele-trade-config.cmake when name not  match. i think i has known why.

**Comment by a819721810** [comment]
> In my test, if set the name in `vcpkg.json` to an exist port name, it will not install it when configuring a CMake project with vcpkg manifest mode, which doesn't quite match your screenshot.
> 
> Could you give more information to reproduce your issue?

"I believe I made a mistake in my understanding. When configuring a CMake project with vcpkg manifest mode, it doesn't install the package as expected. However, I think it should raise an exception if the name in vcpkg.json conflicts with an existing dependent port name."

**Comment by BillyONeal** [comment]
Ports depending on themselves is normal, it's how feature dependencies are described. We can't elevate that to a failure.
