### ISSUE TITLE
[uWebSockets ] build failure

### ISSUE THREAD

**Issue by abhinavdhamaniya-jm** [microsoft/vcpkg#42239]
### Operating system

Windows

### Compiler

GCC

### Steps to reproduce the behavior

```Shell
This issue might be similar to [https://github.com/uNetworking/uWebSockets/issues/1545](url)

I am using vcpkg to download the uWebSockets library, here are the steps i followed -

1. Added uwebsockets under "dependencies" in vcpkg.json and ran `./vcpkg install --feature-flags=manifests`

{
  "name": "test",
  "version-string": "1.0.0",
  "dependencies": [
    "uwebsockets",
    "zlib"
  ]
}


2. Updated my CMakeLists.txt 

find_path(UWEBSOCKETS_INCLUDE_DIRS "uwebsockets/App.h" PATHS "${CMAKE_SOURCE_DIR}/vcpkg_installed/x64-windows/include/")
target_include_directories(juno-mt5-backend
        PRIVATE ${UWEBSOCKETS_INCLUDE_DIRS}
)


3. Added a sample code 



#include <string>
#include <uWebSockets/App.h>


struct TickData {
    std::string symbol;
    double bid;
    double ask;
    long timestamp;
};

int main() {

    uWS::App().get("/hello", [](auto *res, auto *req) {
        res->end("Hello World!");
    });
    
    return 0;
}




And when i run the main() function with this code, i see many errors like this in the console -

main.cpp.obj : error LNK2019: unresolved external symbol us_socket_context_on_end referenced in function "private: struct uWS::HttpContext<0> * __cdecl uWS::HttpContext<0>::init(void)" (?init@?$HttpContext@$0A@@uWS@@AEAAPEAU12@XZ)


So is it because the uWebSocket currently broken in vcpkg or i am doing something wrong?
Is there a version mismatch between uWebSockets and uSockets?
```

### Failure logs

C:\Windows\system32\cmd.exe /C "cd . && "C:\Program Files\JetBrains\CLion 2024.2.2\bin\cmake\win\x64\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\juno-mt5-backend.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1441~1.341\bin\Hostx64\x64\link.exe /nologo CMakeFiles\juno-mt5-backend.dir\src\main\bootstrap\main.cpp.obj CMakeFiles\juno-mt5-backend.dir\src\main\infrastructure\manager\Manager.cpp.obj CMakeFiles\juno-mt5-backend.dir\src\main\domain\user\service\UserService.cpp.obj CMakeFiles\juno-mt5-backend.dir\src\main\infrastructure\adapter\UserAdapter.cpp.obj CMakeFiles\juno-mt5-backend.dir\src\main\infrastructure\restapi\impl\UserController.cpp.obj CMakeFiles\juno-mt5-backend.dir\src\main\infrastructure\restapi\impl\HealthController.cpp.obj CMakeFiles\juno-mt5-backend.dir\src\main\infrastructure\mapper\UserMapper.cpp.obj CMakeFiles\juno-mt5-backend.dir\src\main\infrastructure\utils\DataConversionUtils.cpp.obj  /out:juno-mt5-backend.exe /implib:juno-mt5-backend.lib /pdb:juno-mt5-backend.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console  C:\Users\abhin\CLionProjects\juno-mt5-backend\external-libraries\oatpp\lib\oatpp-1.4.0\oatpp.lib  C:\Users\abhin\CLionProjects\juno-mt5-backend\external-libraries\oatpp-swagger\lib\oatpp-1.4.0\oatpp-swagger.lib  C:\Users\abhin\CLionProjects\juno-mt5-backend\vcpkg_installed\x64-windows\debug\lib\fmtd.lib  C:\Users\abhin\CLionProjects\juno-mt5-backend\vcpkg_installed\x64-windows\debug\lib\yaml-cppd.lib  C:\Users\abhin\CLionProjects\juno-mt5-backend\vcpkg_installed\x64-windows\lib\zlib.lib  C:\Users\abhin\CLionProjects\juno-mt5-backend\external-libraries\oatpp\lib\oatpp-1.4.0\oatpp-test.lib  wsock32.lib  ws2_32.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && C:\Windows\system32\cmd.exe /C "cd /D C:\Users\abhin\CLionProjects\juno-mt5-backend\cmake-build-debug && "C:\Program Files\JetBrains\CLion 2024.2.2\bin\cmake\win\x64\bin\cmake.exe" -E copy_directory C:/Users/abhin/CLionProjects/juno-mt5-backend/external-libraries/meta-trader-5/Libs C:/Users/abhin/CLionProjects/juno-mt5-backend/cmake-build-debug && cd /D C:\Users\abhin\CLionProjects\juno-mt5-backend\cmake-build-debug && "C:\Program Files\JetBrains\CLion 2024.2.2\bin\cmake\win\x64\bin\cmake.exe" -E copy_if_different C:/Users/abhin/CLionProjects/juno-mt5-backend/external-libraries/vcpkg/buildtrees/fmt/x64-windows-dbg/bin/fmtd.dll C:/Users/abhin/CLionProjects/juno-mt5-backend/cmake-build-debug && cd /D C:\Users\abhin\CLionProjects\juno-mt5-backend\cmake-build-debug && "C:\Program Files\JetBrains\CLion 2024.2.2\bin\cmake\win\x64\bin\cmake.exe" -E copy_if_different C:/Users/abhin/CLionProjects/juno-mt5-backend/external-libraries/vcpkg/buildtrees/yaml-cpp/x64-windows-dbg/yaml-cppd.dll C:/Users/abhin/CLionProjects/juno-mt5-backend/cmake-build-debug && cd /D C:\Users\abhin\CLionProjects\juno-mt5-backend\cmake-build-debug && "C:\Program Files\JetBrains\CLion 2024.2.2\bin\cmake\win\x64\bin\cmake.exe" -E copy C:/Users/abhin/CLionProjects/juno-mt5-backend/application.yml C:/Users/abhin/CLionProjects/juno-mt5-backend/cmake-build-debug""
LINK Pass 1: command "C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1441~1.341\bin\Hostx64\x64\link.exe /nologo CMakeFiles\juno-mt5-backend.dir\src\main\bootstrap\main.cpp.obj CMakeFiles\juno-mt5-backend.dir\src\main\infrastructure\manager\Manager.cpp.obj CMakeFiles\juno-mt5-backend.dir\src\main\domain\user\service\UserService.cpp.obj CMakeFiles\juno-mt5-backend.dir\src\main\infrastructure\adapter\UserAdapter.cpp.obj CMakeFiles\juno-mt5-backend.dir\src\main\infrastructure\restapi\impl\UserController.cpp.obj CMakeFiles\juno-mt5-backend.dir\src\main\infrastructure\restapi\impl\HealthController.cpp.obj CMakeFiles\juno-mt5-backend.dir\src\main\infrastructure\mapper\UserMapper.cpp.obj CMakeFiles\juno-mt5-backend.dir\src\main\infrastructure\utils\DataConversionUtils.cpp.obj /out:juno-mt5-backend.exe /implib:juno-mt5-backend.lib /pdb:juno-mt5-backend.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console C:\Users\abhin\CLionProjects\juno-mt5-backend\external-libraries\oatpp\lib\oatpp-1.4.0\oatpp.lib C:\Users\abhin\CLionProjects\juno-mt5-backend\external-libraries\oatpp-swagger\lib\oatpp-1.4.0\oatpp-swagger.lib C:\Users\abhin\CLionProjects\juno-mt5-backend\vcpkg_installed\x64-windows\debug\lib\fmtd.lib C:\Users\abhin\CLionProjects\juno-mt5-backend\vcpkg_installed\x64-windows\debug\lib\yaml-cppd.lib C:\Users\abhin\CLionProjects\juno-mt5-backend\vcpkg_installed\x64-windows\lib\zlib.lib C:\Users\abhin\CLionProjects\juno-mt5-backend\external-libraries\oatpp\lib\oatpp-1.4.0\oatpp-test.lib wsock32.lib ws2_32.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\juno-mt5-backend.dir/intermediate.manifest CMakeFiles\juno-mt5-backend.dir/manifest.res" failed (exit code 1120) with the following output:
main.cpp.obj : error LNK2019: unresolved external symbol us_create_timer referenced in function "private: static struct uWS::Loop * __cdecl uWS::Loop::create(void *)" (?create@Loop@uWS@@CAPEAU12@PEAX@Z)
main.cpp.obj : error LNK2019: unresolved external symbol us_timer_ext referenced in function "public: __cdecl `private: static struct uWS::Loop * __cdecl uWS::Loop::create(void *)'::`2'::<lambda_1>::operator()(struct us_timer_t *)const " (??R<lambda_1>@?1??create@Loop@uWS@@CAPEAU23@PEAX@Z@QEBA@PEAUus_timer_t@@@Z)
main.cpp.obj : error LNK2019: unresolved external symbol us_timer_close referenced in function "public: void __cdecl uWS::Loop::free(void)" (?free@Loop@uWS@@QEAAXXZ)
main.cpp.obj : error LNK2019: unresolved external symbol us_timer_set referenced in function "private: static struct uWS::Loop * __cdecl uWS::Loop::create(void *)" (?create@Loop@uWS@@CAPEAU12@PEAX@Z)
main.cpp.obj : error LNK2019: unresolved external symbol us_create_socket_context referenced in function "public: static struct uWS::HttpContext<0> * __cdecl uWS::HttpContext<0>::create(struct uWS::Loop *,struct us_socket_context_options_t)" (?create@?$HttpContext@$0A@@uWS@@SAPEAU12@PEAULoop@2@Uus_socket_context_options_t@@@Z)
main.cpp.obj : error LNK2019: unresolved external symbol us_socket_context_free referenced in function "public: void __cdecl uWS::HttpContext<0>::free(void)" (?free@?$HttpContext@$0A@@uWS@@QEAAXXZ)
main.cpp.obj : error LNK2019: unresolved external symbol us_socket_context_on_open referenced in function "private: struct uWS::HttpContext<0> * __cdecl uWS::HttpContext<0>::init(void)" (?init@?$HttpContext@$0A@@uWS@@AEAAPEAU12@XZ)
main.cpp.obj : error LNK2019: unresolved external symbol us_socket_context_on_close referenced in function "private: struct uWS::HttpContext<0> * __cdecl uWS::HttpContext<0>::init(void)" (?init@?$HttpContext@$0A@@uWS@@AEAAPEAU12@XZ)
main.cpp.obj : error LNK2019: unresolved external symbol us_socket_context_on_data referenced in function "private: struct uWS::HttpContext<0> * __cdecl uWS::HttpContext<0>::init(void)" (?init@?$HttpContext@$0A@@uWS@@AEAAPEAU12@XZ)
main.cpp.obj : error LNK2019: unresolved external symbol us_socket_context_on_writable referenced in function "private: struct uWS::HttpContext<0> * __cdecl uWS::HttpContext<0>::init(void)" (?init@?$HttpContext@$0A@@uWS@@AEAAPEAU12@XZ)
main.cpp.obj : error LNK2019: unresolved external symbol us_socket_context_on_timeout referenced in function "private: struct uWS::HttpContext<0> * __cdecl uWS::HttpContext<0>::init(void)" (?init@?$HttpContext@$0A@@uWS@@AEAAPEAU12@XZ)
main.cpp.obj : error LNK2019: unresolved external symbol us_socket_context_on_end referenced in function "private: struct uWS::HttpContext<0> * __cdecl uWS::HttpContext<0>::init(void)" (?init@?$HttpContext@$0A@@uWS@@AEAAPEAU12@XZ)
main.cpp.obj : error LNK2019: unresolved external symbol us_socket_context_ext referenced in function "public: static struct uWS::HttpContext<0> * __cdecl uWS::HttpContext<0>::create(struct uWS::Loop *,struct us_socket_context_options_t)" (?create@?$HttpContext@$0A@@uWS@@SAPEAU12@PEAULoop@2@Uus_socket_context_options_t@@@Z)
main.cpp.obj : error LNK2019: unresolved external symbol us_socket_context_loop referenced in function "protected: struct uWS::LoopData * __cdecl uWS::AsyncSocket<0>::getLoopData(void)" (?getLoopData@?$AsyncSocket@$0A@@uWS@@IEAAPEAULoopData@2@XZ)
main.cpp.obj : error LNK2019: unresolved external symbol us_create_loop referenced in function "private: static struct uWS::Loop * __cdecl uWS::Loop::create(void *)" (?create@Loop@uWS@@CAPEAU12@PEAX@Z)
main.cpp.obj : error LNK2019: unresolved external symbol us_loop_free referenced in function "public: void __cdecl uWS::Loop::free(void)" (?free@Loop@uWS@@QEAAXXZ)
main.cpp.obj : error LNK2019: unresolved external symbol us_loop_ext referenced in function "private: static struct uWS::Loop * __cdecl uWS::Loop::create(void *)" (?create@Loop@uWS@@CAPEAU12@PEAX@Z)
main.cpp.obj : error LNK2019: unresolved external symbol us_socket_write referenced in function "public: __cdecl `private: struct uWS::HttpContext<0> * __cdecl uWS::HttpContext<0>::init(void)'::`2'::<lambda_3>::operator()(struct us_socket_t *,char *,int)const " (??R<lambda_3>@?1??init@?$HttpContext@$0A@@uWS@@AEAAPEAU23@XZ@QEBA@PEAUus_socket_t@@PEADH@Z)
main.cpp.obj : error LNK2019: unresolved external symbol us_socket_timeout referenced in function "public: void * __cdecl `public: __cdecl `private: struct uWS::HttpContext<0> * __cdecl uWS::HttpContext<0>::init(void)'::`2'::<lambda_3>::operator()(struct us_socket_t *,char *,int)const '::`2'::<lambda_1>::operator()(void *,struct uWS::HttpRequest *)const " (??R<lambda_1>@?1???R<lambda_3>@?1??init@?$HttpContext@$0A@@uWS@@AEAAPEAU34@XZ@QEBA@PEAUus_socket_t@@PEADH@Z@QEBAPEAXPEAXPEAUHttpRequest@4@@Z)
main.cpp.obj : error LNK2019: unresolved external symbol us_socket_ext referenced in function "public: void * __cdecl `public: __cdecl `private: struct uWS::HttpContext<0> * __cdecl uWS::HttpContext<0>::init(void)'::`2'::<lambda_3>::operator()(struct us_socket_t *,char *,int)const '::`2'::<lambda_1>::operator()(void *,struct uWS::HttpRequest *)const " (??R<lambda_1>@?1???R<lambda_3>@?1??init@?$HttpContext@$0A@@uWS@@AEAAPEAU34@XZ@QEBA@PEAUus_socket_t@@PEADH@Z@QEBAPEAXPEAXPEAUHttpRequest@4@@Z)
main.cpp.obj : error LNK2019: unresolved external symbol us_socket_context referenced in function "protected: struct uWS::LoopData * __cdecl uWS::AsyncSocket<0>::getLoopData(void)" (?getLoopData@?$AsyncSocket@$0A@@uWS@@IEAAPEAULoopData@2@XZ)
main.cpp.obj : error LNK2019: unresolved external symbol us_socket_shutdown referenced in function "public: __cdecl `private: struct uWS::HttpContext<0> * __cdecl uWS::HttpContext<0>::init(void)'::`2'::<lambda_3>::operator()(struct us_socket_t *,char *,int)const " (??R<lambda_3>@?1??init@?$HttpContext@$0A@@uWS@@AEAAPEAU23@XZ@QEBA@PEAUus_socket_t@@PEADH@Z)
main.cpp.obj : error LNK2019: unresolved external symbol us_socket_is_shut_down referenced in function "public: void * __cdecl `public: __cdecl `private: struct uWS::HttpContext<0> * __cdecl uWS::HttpContext<0>::init(void)'::`2'::<lambda_3>::operator()(struct us_socket_t *,char *,int)const '::`2'::<lambda_1>::operator()(void *,struct uWS::HttpRequest *)const " (??R<lambda_1>@?1???R<lambda_3>@?1??init@?$HttpContext@$0A@@uWS@@AEAAPEAU34@XZ@QEBA@PEAUus_socket_t@@PEADH@Z@QEBAPEAXPEAXPEAUHttpRequest@4@@Z)
main.cpp.obj : error LNK2019: unresolved external symbol us_socket_is_closed referenced in function "public: void * __cdecl `public: __cdecl `private: struct uWS::HttpContext<0> * __cdecl uWS::HttpContext<0>::init(void)'::`2'::<lambda_3>::operator()(struct us_socket_t *,char *,int)const '::`2'::<lambda_1>::operator()(void *,struct uWS::HttpRequest *)const " (??R<lambda_1>@?1???R<lambda_3>@?1??init@?$HttpContext@$0A@@uWS@@AEAAPEAU34@XZ@QEBA@PEAUus_socket_t@@PEADH@Z@QEBAPEAXPEAXPEAUHttpRequest@4@@Z)
main.cpp.obj : error LNK2019: unresolved external symbol us_socket_close referenced in function "public: void * __cdecl `public: __cdecl `private: struct uWS::HttpContext<0> * __cdecl uWS::HttpContext<0>::init(void)'::`2'::<lambda_3>::operator()(struct us_socket_t *,char *,int)const '::`2'::<lambda_1>::operator()(void *,struct uWS::HttpRequest *)const " (??R<lambda_1>@?1???R<lambda_3>@?1??init@?$HttpContext@$0A@@uWS@@AEAAPEAU34@XZ@QEBA@PEAUus_socket_t@@PEADH@Z@QEBAPEAXPEAXPEAUHttpRequest@4@@Z)
juno-mt5-backend.exe : fatal error LNK1120: 25 unresolved externals
ninja: build stopped: subcommand failed.

**Comment by abhinavdhamaniya-jm** [comment]
This issue might be related to [https://github.com/microsoft/vcpkg/issues/31813](url)

@uNetworkingAB can you check this?

**Comment by abhinavdhamaniya-jm** [comment]
Please guide me on how can i fix this issue, i am new to cmake and vcpkg

**Comment by abhinavdhamaniya-jm** [comment]
@jimwang118 any update on this?

**Comment by jimwang118** [comment]
Upstream Tracking Issue [1811](https://github.com/uNetworking/uWebSockets/issues/1811).

**Comment by uNetworkingAB** [comment]
I haven't made this vcpkg distribution. You made it. You made it not link to usockets in your CMake build. Upstream does not even use CMake and has made no commits to vcpkg. There is no upstream issue.

**Comment by dg0yt** [comment]
> You made it not link to usockets in your CMake build. 

The vcpkg port doesn't indicate that this necessary, but carries uwebsocket's message of being "header-only". 

> Upstream does not even use CMake

The vcpkg just copies the headers, in a portfile script which happens to be written in CMake. This is equivalent to `make install`.

> There is no upstream issue.

IMO there is at least an inconsistency between dressing as "header-only" and actually having linking requirements. I don't even find a mention of the linking requirement in the READMEs. This is not a CMake issue.

The vcpkg port can extent the `usage` synopsis to inform users on how to to find an link usockets.

Or it can add unofficial CMake config or pkg-config. But maintaining such config officially upstream would be beneficial to a broader audience.

**Comment by uNetworkingAB** [comment]
> dressing as "header-only" and actually having linking requirements

There is no mention of "header-only" in the README. There is however this mention:

> µWebSockets builds on [µSockets](https://github.com/uNetworking/uSockets), a foundation library implementing eventing, networking and cryptography in three different layers.

The only mention I see about "header-only" is in the so called READMORE:

> µWebSockets is 100% standard header-only C++17 - it compiles on any platform. However, it depends on µSockets in all cases, which is platform-specific C code that runs on Linux, Windows and macOS.

In any case. I have 0 seconds of time to argue about misunderstandings. I did not make this vcpkg distribution. I don't know how vcpkg works, or how it indicates dependencies, again it is not my doing and I don't support its eventual issues. It's a third-party distribution in whatever way Microsoft made it.

And if I'm being honest, Windows as platform is like 5% of my audience so it's not worth doing a deep dive into it.

**Comment by dg0yt** [comment]
The issue isn't about Windows. I'm a community member,  and what makes vcpkg attractive for me are the the other platforms.

**Comment by dg0yt** [comment]
"The implementation is header-only C++17"
https://github.com/uNetworking/uWebSockets/blob/b9b59b2b164489f3788223fec5821f77f7962d43/misc/READMORE.md?plain=1#L15

**Comment by uNetworkingAB** [comment]
Please don't argue with me. I know my project. I have not a shred of interest in arguing about your inability to comprehend a written sentence:

> The implementation is header-only C++17 (but examples use C++20 features for brevity and elegance!), cross-platform and compiles down to a tiny binary of a handful kilobytes.
It depends on µSockets, which is a standard C project for Linux, macOS & Windows.

Further on there is no such consensus of "header-only" being mutually exclusive to having dependencies. For instance, Boost is header-only and has dependency on several libraries. In any case, this hair splitting has no use for me. Good luck fixing your port.

**Comment by dg0yt** [comment]
Fortunately, the port isn't broken. It is only uwebsockets users asking for UX improvements.

Maybe this qualifies as upstream encouraging adding unofficial cmake config (also for usockets). 

Let's check other repos first, from https://repology.org/project/uwebsockets/versions:
- AUR: https://aur.archlinux.org/packages/uwebsockets
  Adding `uwebsockets.pc`. (Why didn't they upstream?)
- Conan: https://github.com/conan-io/conan-center-index/tree/master/recipes/uwebsockets
  Doing their own proprietary CMake stuff.  (Do they even care about upstreaming?) Tests have:
  ~~~
  find_package(uwebsockets)
  target_link_libraries(${PROJECT_NAME} PRIVATE uwebsockets::uwebsockets)
  ~~~
- FreeBSD ports: nothing (AFAICS)
- Gentoo overlay GURU: nothing (AFAICS)
- LiGurOS: nothing (AFAICS)
- OpenBSD Ports: nothing (AFAICS)
- vpckg: nothing ATM. This issue.

So there is non-standard uwebsockets.pc, there is non-standard uwebsockets CMake, and there is nothing.

**Comment by uNetworkingAB** [comment]
> Fortunately, the port isn't broken.

Great. Close issue.

**Comment by dg0yt** [comment]
@abhinavdhamaniya-jm The usockets port is vendoring a CMake build system, so it could be easily extend to export CMake config with transitive usage requirements. The CMake config for uwebsockets would be trivial once usockets provides a CMake package.

Unfortunately, this will have a vcpkg lock-in effect which normally isn't desired here. To make this visible, such CMake config will be namespaced as "unofficial". So the final CMake usage pattern would look like:
~~~
find_package(unofficial-uwebsockets CONFIG REQUIRED)
target_link_libraries(app PRIVATE unofficial::uwebsockets::uwebsockets)
~~~
with proper transitive usage requirements. Your code example could be used in a test port.

**Comment by dg0yt** [comment]
@abhinavdhamaniya-jm #42538 implements the proposed CMake config. Note that the include path is so that you would need to use
~~~CXX
#include <uwebsockets/App.h>
~~~
(Windows uses case-insensitive filenames, but I would recommed to not rely on such quirks.)

**Comment by dg0yt** [comment]
(It would have been nice to use `#include <uWS/App.h>` (mirroring `uWS::App`) but I didn't want to change the current layout in absence of official recommendations.)
