### ISSUE TITLE
Error: Building package boost-build:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by nuli0355** [Microsoft/vcpkg#4227]
Package: boost-build:x64-windows
 Vcpkg version: 0.0.113-nohash
system: windows10
visual studio : vs2015 update3

please help me,thanks!

**Comment by wangli28** [comment]
@nuli0355, thank you for posting the issue, does the issue still occur? I installed it successfully with VS2015 and VCPKG latest source.

> PS E:\vcpkg> .\vcpkg.exe install boost-build:x64-windows
The following packages will be built and installed:
    boost-build[core]:x64-windows
Starting package 1/1: boost-build:x64-windows
Building package boost-build[core]:x64-windows...
A suitable version of cmake was not found (required v3.14.0). Downloading portable cmake v3.14.0...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.14.0/cmake-3.14.0-win32-x86.zip -> E:\vcpkg\downloads\cmake-3.14.0-win32-x86.zip
Extracting cmake...
-- Downloading https://github.com/boostorg/build/archive/boost-1.69.0.tar.gz...
-- Extracting source E:/vcpkg/downloads/boostorg-build-boost-1.69.0.tar.gz
-- Using source at E:/vcpkg/buildtrees/boost-build/src/ost-1.69.0-1d1e4d577d
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.69.0/LICENSE_1_0.txt...
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.69.0/boostcpp.jam...
-- Installing: E:/vcpkg/packages/boost-build_x64-windows/share/boost-build/copyright
-- Installing: E:/vcpkg/packages/boost-build_x64-windows/tools/boost-build/boostcpp.jam
-- Bootstrapping...
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-build[core]:x64-windows... done
Installing package boost-build[core]:x64-windows...
Installing package boost-build[core]:x64-windows... done
Elapsed time for package boost-build:x64-windows: 57.96 s
\
Total elapsed time: 57.96 s

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
