### ISSUE TITLE
[SFML] update to <2.6.2>

### ISSUE THREAD

**Issue by byronhaochen** [microsoft/vcpkg#42280]
### Library name

SFML

### New version number

2.6.2

### Other information that may be useful (release notes, etc...)

Library name
SFML

Library description
2.6.2

Source repository URL
https://github.com/SFML/SFML

Project homepage (if different from the source repository)
No response

Anything else that is useful to know when adding (such as optional features the library may have that should be included)
Current highest version is 2.6.1, please update to 2.6.2

**Comment by MonicaLiu0311** [comment]
Fixed by #42118.
