### ISSUE TITLE
[libmysql 8.0.34] build failure

### ISSUE THREAD

**Issue by druidfund** [microsoft/vcpkg#42302]
### Operating system

CentOS 8.5

### Compiler

GCC 8.5

### Steps to reproduce the behavior

```Shell
vcpkg install libmysql
```

### Failure logs

in "/opt/vcpkg/buildtrees/libmysql/config-x64-linux-out.log"
```
-- This is .el8. as found from 'rpm -qf /'
-- Looking for a devtoolset compiler
CMake Warning at CMakeLists.txt:394 (MESSAGE):
  Could not find devtoolset compiler/linker in /opt/rh/gcc-toolset-12


CMake Warning at CMakeLists.txt:396 (MESSAGE):
  You need to install the required packages:

   yum install gcc-toolset-12-gcc gcc-toolset-12-gcc-c++ gcc-toolset-12-binutils gcc-toolset-12-annobin-annocheck gcc-toolset-12-annobin-plugin-gcc



CMake Error at CMakeLists.txt:398 (MESSAGE):
  Or you can set CMAKE_C_COMPILER and CMAKE_CXX_COMPILER explicitly.


-- Configuring incomplete, errors occurred!
ninja: build stopped: subcommand failed.
```

### Additional context

the default gcc version of centos8.* is  gcc8.*,  is there any way to fix this for those that can not upgrade  gcc or centos  version?

**Comment by jimwang118** [comment]
The error message indicates that you have not installed the gcc compiler.

**Comment by druidfund** [comment]
> The error message indicates that the compiler was not obtained. Have you installed multiple versions of the compiler?

no multiple gcc installed, gcc 8.5 only

**Comment by dg0yt** [comment]
That package is nasty. We already build with `FORCE_UNSUPPORTED_COMPILER` for Windows. The same control would relax constraints for other platforms.

**Comment by druidfund** [comment]
> That package is nasty. We already build with `FORCE_UNSUPPORTED_COMPILER` for Windows. The same control would relax constraints for other platforms.

thanks a lot, it works by build with FORCE_UNSUPPORTED_COMPILER !
