### ISSUE TITLE
[pybind11] Don't install Python

### ISSUE THREAD

**Issue by nickanthony-dgl** [microsoft/vcpkg#42323]
### Is your feature request related to a problem? Please describe.

The vcpkg package for pybind11 lists python3 as a dependency. Having the vcpkg python3 package installed causes some problems if you want to instead use a non-vcpkg Python installation. #42322 

### Proposed solution

The pybind11 vcpkg package shouldn't make any assumptions about how Python will be installed, so I don't think "python3" should be listed as a dependency in the vcpkg.json file.

**Comment by Osyotr** [comment]
Nothing has changed since the last attempt to decouple pybind11 and python3.
https://github.com/microsoft/vcpkg/pull/40784

**Comment by nickanthony-dgl** [comment]
Thanks. I had searched for related issues before but for some reason didn't find that one. I don't really understand why an empty overlay port is better than just making the python3 optional, but I will go ahead and try that approach.

**Comment by dg0yt** [comment]
The dependency enforces a defined installation order between python3 and pybind.
The overlay port is to choose a different python3 implementation than the one provided by vcpkg.
Both things together help to ensure a reproducable result.
