### ISSUE TITLE
package_name:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by sebaspf** [Microsoft/vcpkg#4233]
After clean install of vcpkg in Windows 7, I get the an error after trying to install sdl2:
Error: Building package sdl2:x64-windows failed with: BUILD_FAILED
  Package: sdl2:x64-windows
  Vcpkg version: 0.0.113-nohash

This is what I'm doing:
git clone https://github.com/Microsoft/vcpkg
cd vcpkg
cmd /C .\bootstrap-vcpkg.bat
set VCPKG_DEFAULT_TRIPLET=x64-windows
vcpkg install sdl2

I have the same problem for every package that I try to install. Visual Studio 2017 is already in English... When I comment the line "PREFER_NINJA" in vcpkg\ports\sdl2\portfile.cmake it works fine... Is this normal?? Is there any better solution than commenting this line for every package??

Thanks in advance

[config-x64-windows-out.log](https://github.com/Microsoft/vcpkg/files/2353122/config-x64-windows-out.log)

**Comment by Voskrese** [comment]
Run Build Command 
`C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe` 

rename and try again

**Comment by sebaspf** [comment]
Thanks for the help and the quick response! Running only (without any parameters)
`C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe`
returns 
`ninja: error: loading 'build.ninja': No such file or directory`

the folder `C:/Users/XYZ/Packages/vcpkg/buildtrees/sdl2/x64-windows-rel/CMakeFiles/CMakeTmp` is empty, therefore running `"C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "cmTC_3fffd"` will also fail.

renaming ninja.exe and rerunning `vcpkg install sdl2` fails again with the same error.

[config-x64-windows-out.log](https://github.com/Microsoft/vcpkg/files/2355907/config-x64-windows-out.log)

**Comment by Voskrese** [comment]
move "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe" "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\__ninja__.exe"

**Comment by Voskrese** [comment]
`MSVC/14.15.26726/bin/Hostx64/x64/cl.exe -- broken`
=
` ninja: error: loading 'build.ninja': No such file or directory`

**Comment by Voskrese** [comment]
?
`dir C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC`

**Comment by sebaspf** [comment]
The path `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\bin\Hostx64\x64\cl.exe`exists.

`move "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe" "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake_ninja_.exe"`

```
C:\Users\XYZ\Packages\vcpkg>vcpkg.exe install sdl2
The following packages will be built and installed:
    sdl2[core]:x64-windows
Starting package 1/1: sdl2:x64-windows
Building package sdl2[core]:x64-windows...
-- Using cached C:/Users/XYZ/Packages/vcpkg/downloads/SDL-Mirror-SDL-release-2.0.
8.tar.gz
-- Using source at C:/Users/XYZ/Packages/vcpkg/buildtrees/sdl2/src/ease-2.0.8-429
57b8d01
-- Applying patch C:/Users/XYZ/Packages/vcpkg/ports/sdl2/export-symbols-only-in-s
hared-build.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/Users/XYZ/Packages/vcpkg/ports/sdl2/enable-winrt-cmake.patch

-- Applying patch failed. This is expected if this patch was previously applied.
-- Downloading https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-wi
n.zip...
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: C:/Users/XYZ/Packages/vcpkg/buildtrees/sdl2/x64-windows-re
l/vcpkg-parallel-configure
    See logs for more information:
      C:\Users\XYZ\Packages\vcpkg\buildtrees\sdl2\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:246 (vcpkg_execute_required_process)
  ports/sdl2/portfile.cmake:22 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package sdl2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sdl2:x64-windows
  Vcpkg version: 0.0.113-nohash

Additionally, attach any relevant sections from the log files above.
```

from the line:
`-- Downloading https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-wi
n.zip...` 
shulden't it be using 
`C:\Users\XYZ\Packages\vcpkg\downloads\tools\ninja\ninja-1.8.2\ninja.exe`
instead of 
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe` 
??

**Comment by Voskrese** [comment]
this assumption about a possible error, as seen above, I have a successful build

**Comment by sebaspf** [comment]
> move "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe" "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\__ninja__.exe"
>...E:\tools\vcpkg...
>copy "E:\tools\vcpkg\downloads\tools\ninja\ninja-1.8.2\ninja.exe" "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja"

Files were replaced. Both ninja.exe are the same version (1.8.2) but the files are diffrent.

Delting 'vcpkg\buildtrees\sdl2' and executing 'vcpkg.exe install sdl2'didn't work. Here is the output:
'''
The following packages will be built and installed:
    sdl2[core]:x64-windows
Starting package 1/1: sdl2:x64-windows
Building package sdl2[core]:x64-windows...
-- Using cached C:/Users/XYZ/Packages/vcpkg/downloads/SDL-Mirror-SDL-release-2.0.8.tar.gz
-- Extracting source C:/Users/XYZ/Packages/vcpkg/downloads/SDL-Mirror-SDL-release-2.0.8.tar.gz
-- Using source at C:/Users/XYZ/Packages/vcpkg/buildtrees/sdl2/src/ease-2.0.8-42957b8d01
-- Applying patch C:/Users/XYZ/Packages/vcpkg/ports/sdl2/export-symbols-only-in-shared-build.patch
-- Applying patch C:/Users/XYZ/Packages/vcpkg/ports/sdl2/enable-winrt-cmake.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: C:/Users/XYZ/Packages/vcpkg/buildtrees/sdl2/x64-windows-rel/vcpkg-parallel-configure
    See logs for more information:
      C:\Users\XYZ\Packages\vcpkg\buildtrees\sdl2\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:246 (vcpkg_execute_required_process)
  ports/sdl2/portfile.cmake:22 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package sdl2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sdl2:x64-windows
  Vcpkg version: 0.0.113-nohash

Additionally, attach any relevant sections from the log files above.
'''

Any other Ideas?

**Comment by Voskrese** [comment]
install the required libraries in
Microsoft Visual Studio\2017\Community

and put
Windows SDK

**Comment by sebaspf** [comment]
So... I have installed 10GB of Windows development tools for Visual Studio 2017 and it still doesn't work. I have tried with installing CMake 10.3 and 12.1 and it also didn't work. I commented the line "PREFER_NINJA" in every .camke file of the packages and it dependencies and some got installed but many others not. 

This problem is only on this computer, in others I could install everything without problems....

Thaks for the help.

**Comment by shijunti19** [comment]
Windows 10 doesn't work


Starting package 1/1: sdl2:x86-windows
Building package sdl2[core]:x86-windows...
Warning: The following VS instances are excluded because the English language pack is unavailable.
    E:\Program Files\Microsoft Visual Studio\2017\Community
Please install the English language pack.
-- Using cached F:/web/xiaolu/rust/vcpkg/downloads/SDL-Mirror-SDL-release-2.0.9.tar.gz
-- Using source at F:/web/xiaolu/rust/vcpkg/buildtrees/sdl2/src/ease-2.0.9-ad425106c1
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: F:/web/xiaolu/rust/vcpkg/buildtrees/sdl2/x86-windows-rel/vcpkg-parallel-configure
    See logs for more information:
      F:\web\xiaolu\rust\vcpkg\buildtrees\sdl2\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:257 (vcpkg_execute_required_process)
  ports/sdl2/portfile.cmake:19 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package sdl2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sdl2:x86-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by shijunti19** [comment]
[1/2] cmd /c "cd .. && "F:/web/xiaolu/rust/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/bin/cmake.exe" "F:/web/xiaolu/rust/vcpkg/buildtrees/sdl2/src/ease-2.0.9-ad425106c1" "-DSDL_STATIC=0" "-DSDL_SHARED=1" "-DVIDEO_VULKAN=OFF" "-DFORCE_STATIC_VCRT=0" "-DLIBC=ON" "-DCMAKE_MAKE_PROGRAM=F:/web/xiaolu/rust/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=F:/web/xiaolu/rust/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=F:/web/xiaolu/rust/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=F:/web/xiaolu/rust/vcpkg/packages/sdl2_x86-windows""
FAILED: ../CMakeCache.txt 
cmd /c "cd .. && "F:/web/xiaolu/rust/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/bin/cmake.exe" "F:/web/xiaolu/rust/vcpkg/buildtrees/sdl2/src/ease-2.0.9-ad425106c1" "-DSDL_STATIC=0" "-DSDL_SHARED=1" "-DVIDEO_VULKAN=OFF" "-DFORCE_STATIC_VCRT=0" "-DLIBC=ON" "-DCMAKE_MAKE_PROGRAM=F:/web/xiaolu/rust/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=F:/web/xiaolu/rust/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=F:/web/xiaolu/rust/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=F:/web/xiaolu/rust/vcpkg/packages/sdl2_x86-windows""
-- The C compiler identification is MSVC 19.0.24210.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe -- broken
CMake Error at F:/web/xiaolu/rust/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/share/cmake-3.12/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: F:/web/xiaolu/rust/vcpkg/buildtrees/sdl2/x86-windows-rel/CMakeFiles/CMakeTmp
    
    Run Build Command:"F:/web/xiaolu/rust/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "cmTC_4c791"
    [1/2] Building C object CMakeFiles\cmTC_4c791.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_4c791.exe
    FAILED: cmTC_4c791.exe 
    cmd.exe /C "cd . && F:\web\xiaolu\rust\vcpkg\downloads\tools\cmake-3.12.4-windows\cmake-3.12.4-win32-x86\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_4c791.dir --manifests  -- C:\PROGRA~2\MICROS~1.0\VC\bin\AMD64_~2\link.exe /nologo CMakeFiles\cmTC_4c791.dir\testCCompiler.c.obj  /out:cmTC_4c791.exe /implib:cmTC_4c791.lib /pdb:cmTC_4c791.pdb /version:0.0  /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /foCMakeFiles\cmTC_4c791.dir/manifest.res CMakeFiles\cmTC_4c791.dir/manifest.rc" failed (exit code 0) with the following output:
    系统找不到指定的文件。
    ninja: build stopped: subcommand failed.
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:6 (project)


-- Configuring incomplete, errors occurred!
See also "F:/web/xiaolu/rust/vcpkg/buildtrees/sdl2/x86-windows-rel/CMakeFiles/CMakeOutput.log".
See also "F:/web/xiaolu/rust/vcpkg/buildtrees/sdl2/x86-windows-rel/CMakeFiles/CMakeError.log".
[2/2] cmd /c "cd ../../x86-windows-dbg && "F:/web/xiaolu/rust/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/bin/cmake.exe" "F:/web/xiaolu/rust/vcpkg/buildtrees/sdl2/src/ease-2.0.9-ad425106c1" "-DSDL_STATIC=0" "-DSDL_SHARED=1" "-DVIDEO_VULKAN=OFF" "-DFORCE_STATIC_VCRT=0" "-DLIBC=ON" "-DCMAKE_MAKE_PROGRAM=F:/web/xiaolu/rust/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=F:/web/xiaolu/rust/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=F:/web/xiaolu/rust/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=F:/web/xiaolu/rust/vcpkg/packages/sdl2_x86-windows/debug""
FAILED: ../../x86-windows-dbg/CMakeCache.txt 
cmd /c "cd ../../x86-windows-dbg && "F:/web/xiaolu/rust/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/bin/cmake.exe" "F:/web/xiaolu/rust/vcpkg/buildtrees/sdl2/src/ease-2.0.9-ad425106c1" "-DSDL_STATIC=0" "-DSDL_SHARED=1" "-DVIDEO_VULKAN=OFF" "-DFORCE_STATIC_VCRT=0" "-DLIBC=ON" "-DCMAKE_MAKE_PROGRAM=F:/web/xiaolu/rust/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=F:/web/xiaolu/rust/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=F:/web/xiaolu/rust/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=F:/web/xiaolu/rust/vcpkg/packages/sdl2_x86-windows/debug""
-- The C compiler identification is MSVC 19.0.24210.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe -- broken
CMake Error at F:/web/xiaolu/rust/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/share/cmake-3.12/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: F:/web/xiaolu/rust/vcpkg/buildtrees/sdl2/x86-windows-dbg/CMakeFiles/CMakeTmp
    
    Run Build Command:"F:/web/xiaolu/rust/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "cmTC_f1664"
    [1/2] Building C object CMakeFiles\cmTC_f1664.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_f1664.exe
    FAILED: cmTC_f1664.exe 
    cmd.exe /C "cd . && F:\web\xiaolu\rust\vcpkg\downloads\tools\cmake-3.12.4-windows\cmake-3.12.4-win32-x86\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_f1664.dir --manifests  -- C:\PROGRA~2\MICROS~1.0\VC\bin\AMD64_~2\link.exe /nologo CMakeFiles\cmTC_f1664.dir\testCCompiler.c.obj  /out:cmTC_f1664.exe /implib:cmTC_f1664.lib /pdb:cmTC_f1664.pdb /version:0.0  /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /foCMakeFiles\cmTC_f1664.dir/manifest.res CMakeFiles\cmTC_f1664.dir/manifest.rc" failed (exit code 0) with the following output:
    系统找不到指定的文件。
    ninja: build stopped: subcommand failed.
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:6 (project)


-- Configuring incomplete, errors occurred!
See also "F:/web/xiaolu/rust/vcpkg/buildtrees/sdl2/x86-windows-dbg/CMakeFiles/CMakeOutput.log".
See also "F:/web/xiaolu/rust/vcpkg/buildtrees/sdl2/x86-windows-dbg/CMakeFiles/CMakeError.log".
ninja: build stopped: subcommand failed.

**Comment by wangli28** [comment]
Please open a new issue if this is still a problem for you.
