### ISSUE TITLE
[raylib] Build Error: Fixing pkgconfig file

### ISSUE THREAD

**Issue by nikita-skakun** [microsoft/vcpkg#42332]
Package: raylib:x64-linux@5.5

**Host Environment**

- Host: WSL Ubuntu (x64-linux)
- Compiler: GNU 13.3.0
-    vcpkg-tool version: 2024-11-12-eb492805e92a2c14a230f5c3deb3e89f6771c321
    vcpkg-scripts version: 5e5d0e1cd 2024-11-22 (5 hours ago)

**To Reproduce**

`vcpkg install `

**Failure logs**

```
raylib currently requires the following libraries from the system package manager:
    libgl1-mesa-dev
    libx11-dev
    libxcursor-dev
    libxinerama-dev
    libxrandr-dev
These can be installed on Ubuntu systems via sudo apt install libgl1-mesa-dev libx11-dev libxcursor-dev libxinerama-dev libxrandr-dev
Downloading raysan5-raylib-5.5.tar.gz
Successfully downloaded raysan5-raylib-5.5.tar.gz.
-- Extracting source /root/Projects/vcpkg/downloads/raysan5-raylib-5.5.tar.gz
-- Applying patch android.diff
-- Applying patch fix-link-path.patch
-- Using source at /root/Projects/vcpkg/buildtrees/raylib/src/5.5-966575b391.clean
-- De-vendoring 'cgltf.h'
-- De-vendoring 'dr_flac.h'
-- De-vendoring 'dr_mp3.h'
-- De-vendoring 'dr_wav.h'
-- De-vendoring 'miniaudio.h'
-- De-vendoring 'qoi.h'
-- De-vendoring 'sdefl.h'
-- De-vendoring 'sinfl.h'
-- De-vendoring 'stb_image.h'
-- De-vendoring 'stb_image_resize2.h'
-- De-vendoring 'stb_image_write.h'
-- De-vendoring 'stb_perlin.h'
-- De-vendoring 'stb_rect_pack.h'
-- De-vendoring 'stb_truetype.h'
-- De-vendoring 'stb_vorbis.c'
-- Configuring x64-linux
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Fixing pkgconfig file: /root/Projects/vcpkg/packages/raylib_x64-linux/lib/pkgconfig/raylib.pc
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:134 (message):
  
  /nix/store/f1gamyykr0f8n4afy910ass2jx2g9zkv-pkg-config-wrapper-0.29.2/bin/pkg-config
  --exists raylib failed with error code: 1

      ENV{PKG_CONFIG_PATH}: "/root/Projects/vcpkg/packages/raylib_x64-linux/lib/pkgconfig:/root/Projects/vcpkg/packages/raylib_x64-linux/share/pkgconfig:/root/Projects/celestium/vcpkg_installed/x64-linux/lib/pkgconfig:/root/Projects/celestium/vcpkg_installed/x64-linux/share/pkgconfig"
      output: Package raylib was not found in the pkg-config search path.

  Perhaps you should add the directory containing `raylib.pc'

  to the PKG_CONFIG_PATH environment variable

  No package 'raylib' found
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:196 (z_vcpkg_fixup_pkgconfig_check_files)
  buildtrees/versioning_/versions/raylib/293c69f77a430e6d7ed786224cd81e412c0c2db2/portfile.cmake:79 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:196 (include)



```

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "name": "celestium",
  "version": "0.1.0",
  "dependencies": [
    {
      "name": "raylib",
      "version>=": "5.5",
      "default-features": false
    }
  ],
  "builtin-baseline": "10b7a178346f3f0abef60cecd5130e295afd8da4"
}

```
</details>

**I Have Tried**
Using latest `vcpkg`, installing versions `5.5` and `5.0` of `raylib`, all with the same error.

**Comment by dg0yt** [comment]
Check your system. What is `/nix/store/f1gamyykr0f8n4afy910ass2jx2g9zkv-pkg-config-wrapper-0.29.2/bin/pkg-config` really doing? Any sysroot interfering?

**Comment by expenses** [comment]
I'm also getting this on NixOS on every package that does pkg-config stuff. Think the nix package is a bit broken.

**Comment by expenses** [comment]
Using `pkg-config-unwrapped` instead seems to work though! I'm not sure if it's really written down anywhere that you're meant to use the unwrapped package instead.. https://github.com/NixOS/nixpkgs/issues/335870 mentions it and so I tried it.

**Comment by nikita-skakun** [comment]
I stopped trying to get this to work, but if this is the solution I will mark it as closed.

**Comment by gracicot** [comment]
@nikita-skakun I'm one of the maintainer of the vcpkg package on nixos. The wrapped version of pkg-config never quite worked with vcpkg, so indeed you need `pkg-config-unwrapped` or otherwise vcpkg just won't work properly. I'm not sure why and I haven't investigated. If you are able to find the root cause of the issue, I may take a look and try to make them work together.

**Comment by dg0yt** [comment]
What does that wrapping do?

**Comment by gracicot** [comment]
@dg0yt like most wrappers in nixos, they exist to make the tools aware of the different libraries/paths available in the current scope, and it is usually done by adding additional flags to the executable, or some additional environment variables. Maybe one of those flags are interfering with the way vcpkg uses pkg-config.

**Comment by dg0yt** [comment]
To find the root cause of the issue, it might be useful to know the actual values.
(Anyone playing with sysroot?)
