### ISSUE TITLE
vcpkg, msbuild and manifest on ARM64 fails with wrong triplet

### ISSUE THREAD

**Issue by fobrs** [microsoft/vcpkg#42364]
**Describe the bug**
Using vcpkg with msbuild and manifest file on ARM64 builds fails with an error about invalid ARM64-windows triplet

**Environment**
Windows 11 on ARM64
latest VS2022 preview

**Workaround**
 Add 
`<VcpkgPlatformTarget Condition="'$(Platform)' == 'ARM64'">arm64</VcpkgPlatformTarget>
`
to line 58 of vcpkg.targets.

**Comment by dg0yt** [comment]
I guess this solved by https://github.com/microsoft/vcpkg/pull/42182.
