### ISSUE TITLE
Usage issues

### ISSUE THREAD

**Issue by pwm1234** [microsoft/vcpkg#4239]
I am trying to use vcpkg to manage my open source c++ dependencies. I have been using vcpkg for a few days now and I have some questions relating to how to create and modify ports.

1. Is there an easy way to build a port using a source tree cloned from a git repo? The use case I have is I would like vcpkg to use the latest release of opencv (3.4.3). The current version is 3.4.1 but the opencv build has changed enough between 3.4.1 and 3.4.3 that I cannot make it work. I have a non-vcpkg build of opencv working, so the problem is with adapting the opencv 3.4.3 build to the vcpkg requirements for locations of output files (mostly .cmake files that 3.4.3 now puts into x64/vc14). Since the problem is all integration related, it would be easier if I were working directly with the source code from git rather than an .tar.gz archive. 

2. Is there a way to have `vcpkg install` resume where it left off? This is related to (1) where I have a problem near the end of the build after the ``vcpkg_install_cmake()`` has succeeded but before ``vcpkg_copy_pdbs()`` is called. It is painstaking to have to repeat the entire unzip, cofigure, build, install steps when all I need to do is to adjust the .cmake config files to the correct location. I realize this is how vcpkg is able to achieve reproducible builds, but when I am developing the build, shortcuts that help bypass the unnecessary steps would be quite helpful. (Especially, when it takes an hour or so to build.)

3. Is there a way to have vcpkg run in "verbose" mode? Again, when I am developing a port to use in vcpkg, I would like to see what it is doing on the console rather than having to sift through log files.

4. Is there detailed documentation for how to rearrange the "share" files so they meet the vcpkg requirements? (I am trying to understand what opencv/portfile.cmake is doing between ``vcpkg_install_cmake()`` and ``vcpkg_copy_pdbs()``

5. Similar to (4), what is the recommended way to build or bundle executable tools? The hdf5 tools are a good example. I want the applications as part of the library build. What is the best model to follow?

6. How to best work when needing more than just the DLLs from a library? For example, with opencv, I need to build the performance tests, examples, and documentation. I would like for these to be part of the "feature" set in the control file, but that does not seem to be the way to work in vcpkg. I am looking for guidance on how work? Is is simply, build a separate copy of opencv using the vcpkg cmake toolchain file?

7. Is this the right mechanism to use to ask these kind of usage questions?

Thanks for making vcpkg available. I think vcpkg will be a big help to the C++ development community.

**Comment by PhoebeHui** [comment]
@pwm1234, we have improved most of the issue listed here, please report a new issue if these still be a question for you.

1. Yes, see https://github.com/microsoft/vcpkg/blob/master/docs/examples/packaging-github-repos.md, and currently opencv3 upgraded to 3.4.13 in vcpkg.
2. No, currently this is still not support.
3. We have --debug to print some debug information, however it can't replace the build logs, which may contain huge information.
4,5. Yes, see https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_fixup_cmake_targets.md
6. You can create a https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md and add the tests,examples, and documentation as a feature.
7. Yes, but we prefer to have a issue for each topic.
