### ISSUE TITLE
[raylib] update to 5.5.0

### ISSUE THREAD

**Issue by P5ina** [microsoft/vcpkg#42403]
### Library name

raylib

### New version number

5.5.0

### Other information that may be useful (release notes, etc...)

An official release notes:
[https://github.com/raysan5/raylib/releases/tag/5.5](https://github.com/raysan5/raylib/releases/tag/5.5)

**Comment by JonLiu1993** [comment]
Fixed by PR #35345, please use command "git pull" get the latest vcpkg and use.

**Comment by dg0yt** [comment]
Raylib 5.5 came with #42219.
