### ISSUE TITLE
[sese] download of patch fails

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#42448]
### Operating system

-----

### Steps to reproduce the behavior

```Shell
vcpkg.exe install sese
```

### Failure logs

he following packages will be built and installed:
    sese[core,sqlite3]:x64-windows@2.3.0#3
Restored 0 package(s) from E:\vcpkg_cache\binaries in 66.7 us. Use --debug to see more details.
Installing 1/1 sese[core,sqlite3]:x64-windows@2.3.0#3...
Building sese[core,sqlite3]:x64-windows@2.3.0#3...
Loading MSVC environment ....
-- Using cached libsese-sese-2.3.0-59fa66d24996eceddc2c406b043687cd13a741dd.patch.
error: Missing libsese-sese-refs_-tags_-2.3.0.tar.gz and downloads are blocked by x-block-origin.
error: https://github.com/libsese/sese/archive/refs/tags/2.3.0.tar.gz: failed: status code 404
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:231 (message):
  Download failed, halting portfile.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/sese/portfile.cmake:22 (vcpkg_from_github)
  scripts/ports.cmake:196 (include)

**Comment by dg0yt** [comment]
#42420

**Comment by WangWeiLin-MV** [comment]
Resolved in https://github.com/libsese/sese/issues/85#issuecomment-2510600827
