### ISSUE TITLE
vcpkg export package:x64-windows-static --nuget produces incorrect VcpkgTriplet inside NuGet package at scripts\buildsystems\msbuild\vcpkg.targets

### ISSUE THREAD

**Issue by joburkho** [Microsoft/vcpkg#4247]
For vcpkg master as of 2018-09-06, performing the following steps results in a vcpkg-export NuGet package that contains incorrect values for VcpkgTriplet in the vcpkg.targets file inside that NuGet package:
`cd /d D:\`
`git clone https://github.com/Microsoft/vcpkg.git`
`cd /d D:\VCPKG\`
`powershell`
`.\bootstrap-vcpkg.bat`
`.\vcpkg install flatbuffers:x64-windows-static`
`.\vcpkg install boost-interprocess:x64-windows-static`
`.\vcpkg install boost-process:x64-windows-static`
`.\vcpkg export flatbuffers:x64-windows-static boost-interprocess:x64-windows-static boost-process:x64-windows-static --nuget`

The resulting vcpkg-export-YYYYMMDD-HHMMSS.1.0.0.nupkg file currently contains a vcpkg.targets file (with a relative path inside the NuGet package of `scripts\buildsystems\msbuild\vcpkg.targets`) whose VcpkgTriplet entries do not have the `-static` at the end.  For instance, the VcpkgTriplet for x64 currently reads:
`  <PropertyGroup Condition="'$(Platform)|$(ApplicationType)|$(ApplicationTypeRevision)' == 'x64||'">`
`    <VcpkgEnabled Condition="'$(VcpkgEnabled)' == ''">true</VcpkgEnabled>`
`    <VcpkgTriplet Condition="'$(VcpkgTriplet)' == ''">x64-windows</VcpkgTriplet>`
`  </PropertyGroup>`
However, it should read:
`  <PropertyGroup Condition="'$(Platform)|$(ApplicationType)|$(ApplicationTypeRevision)' == 'x64||'">`
`    <VcpkgEnabled Condition="'$(VcpkgEnabled)' == ''">true</VcpkgEnabled>`
`    <VcpkgTriplet Condition="'$(VcpkgTriplet)' == ''">x64-windows-static</VcpkgTriplet>`
`  </PropertyGroup>`
... since the relative path to the include folder inside the NuGet package is `installed\x64-windows-static\include` and the relative path to the lib folder inside the NuGet package is `installed\x64-windows-static\lib`.  Therefore, when this current vcpkg-export NuGet package is installed in a *.vcxproj project using `Install-Package vcpkg-export-YYYYMMDD-HHMMSS -Source "D:\VCPKG"`, that *.vcxproj project will not be able to automatically find the headers and libraries inside the NuGet package that was just installed ... resulting in compiler/linking errors when that *.vcxproj project is built ... and requiring manual intervention in order to resolve those errors.

When we use `vcpkg export package1:x64-windows-static ... packageN:x64-windows-static --nuget` where all packages are using `-static`, please ensure that the appropriate values for VcpkgTriplet are written to the vcpkg.targets file such that they also include `-static`.

Aside: The following currently works as expected (i.e. similar to above, but without `-static`) because the appropriate VcpkgTriplet entries are used in that vcpkg.targets file:
`.\vcpkg install flatbuffers:x64-windows`
`.\vcpkg install boost-interprocess:x64-windows`
`.\vcpkg install boost-process:x64-windows`
`.\vcpkg export flatbuffers:x64-windows boost-interprocess:x64-windows boost-process:x64-windows --nuget`

**Comment by ras0219-msft** [comment]
Thanks for posting this issue!

This behavior is currently by design (though there's probably ways to improve!). This is because the NuGet package is intended to act _exactly_ as a vcpkg instance replacement. Since you'll need to modify your MSBuild project to get an alternative triplet while using the normal vcpkg instance (see our docs[1] for more on that), you'll also need to modify your project in the same way to get the alternate triplet when using the NuGet package.

[1] https://github.com/Microsoft/vcpkg/blob/master/docs/users/integration.md#with-msbuild

**Comment by joburkho** [comment]
Thanks for the clarification.  I definitely didn't connect the dots from the `-static` export issue to its resolution in that part of the docs. Thanks again.
