### ISSUE TITLE
[<harfbuzz>] package failure on x64-windows

### ISSUE THREAD

**Issue by lijingjian001** [microsoft/vcpkg#42519]
### Operating system

windows10

### Compiler

msvc

### Steps to reproduce the behavior

```Shell
1.clone https://github.com/niwamo/flameshot.git
2.check out branch windows-cli-support
3. add vcpkg depency and vcpkg config
4. and CmakePresets.json and CmakeUserPresets.json
2.cmake.exe -DCMAKE_TOOLCHAIN_FILE=G:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_PLATFORM_TOOLSET=v142 "-SE:/project/c or c++/tool/flameshot" "-BE:/project/c or c++/tool/flameshot/build" -G Ninja
```

### Failure logs

The log is too long, only files can be uploaded

[vcpkg-manifest-install.log](https://github.com/user-attachments/files/18006819/vcpkg-manifest-install.log)

[package-x64-windows-dbg-out.log](https://github.com/user-attachments/files/18006806/package-x64-windows-dbg-out.log)

There is an error with lnk1181 at around line 893 in "package-x64-windows-dbg-out.log" , of course, the last line indicates a sub command error I also found many hints about file names being "or" files

### Additional context

CmakePresets.json
```json
{
    "version": 2,
    "configurePresets": [
        {
            "name": "vcpkg",
            "generator": "Ninja",
            "binaryDir": "${sourceDir}/build",
            "cacheVariables": {
                "CMAKE_TOOLCHAIN_FILE": "$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
            }
        }
    ]
}
```

CMakeUserPresets.json
```json
{
    "version": 2,
    "configurePresets": [
        {
            "name": "default",
            "inherits": "vcpkg",
            "environment": {
                "VCPKG_ROOT": "G:\\vcpkg",
                 "VCPKG_PLATFORM_TOOLSET":"v142"
            }
        }
    ]
}
```
vcpkg.json
```json
{
  "dependencies": [
    "qt5-base",
    "qt5-svg",
    {
      "name": "qttools",
      "features": [
        "linguist"
      ]
    }
  ]
}
```
vcpkg-configuration.json 
```json
{
  "default-registry": {
    "kind": "git",
    "baseline": "cd124b84feb0c02a24a2d90981e8358fdee0e077",
    "repository": "https://github.com/microsoft/vcpkg"
  },
  "registries": [
    {
      "kind": "artifact",
      "location": "https://github.com/microsoft/vcpkg-ce-catalog/archive/refs/heads/main.zip",
      "name": "microsoft"
    }
  ]
}
```

**Comment by dg0yt** [comment]
> many hints about file names being "or" files

Look:

> `E:/project/c or c++/tool/flameshot`

` ` is a problem for many projects. (Due to poor quoting.)
`+` is a problem for some problems. (Due to use in regular expressions.)
Avoid special characters.

**Comment by lijingjian001** [comment]
thanks, I will try agin.
