### ISSUE TITLE
pixman:x64-linux fails to build

### ISSUE THREAD

**Issue by irishpatrick** [Microsoft/vcpkg#4252]
### Vcpkg version: 0.0.113-unknownhash

Running Ubuntu 18.04 through Windows 10 version 1803 (Ubuntu windows store app)

Steps to reproduce problem: `./vcpkg install cairo`

When installing the cairo package on 64 bit linux, the pixman library fails to build.  I included some log file output below, and highlighted in bold what I believe is the culprit.

`[6/33] /usr/bin/cc -DPACKAGE=\"pixman-1\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_VERSION=\"0.34.0\" -DUSE_SSE2 -I/home/patrick/repos/vcpkg/buildtrees/pixman/src/pixman-0.34.0/pixman/. -fPIC -MD -MT CMakeFiles/pixman-1.dir/pixman-bits-image.c.o -MF CMakeFiles/pixman-1.dir/pixman-bits-image.c.o.d -o CMakeFiles/pixman-1.dir/pixman-bits-image.c.o   -c /home/patrick/repos/vcpkg/buildtrees/pixman/src/pixman-0.34.0/pixman/pixman-bits-image.c                                              FAILED: CMakeFiles/pixman-1.dir/pixman-bits-image.c.o                                                                   /usr/bin/cc -DPACKAGE=\"pixman-1\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_VERSION=\"0.34.0\" -DUSE_SSE2 -I/home/patrick/repos/vcpkg/buildtrees/pixman/src/pixman-0.34.0/pixman/. -fPIC -MD -MT CMakeFiles/pixman-1.dir/pixman-bits-image.c.o -MF CMakeFiles/pixman-1.dir/pixman-bits-image.c.o.d -o CMakeFiles/pixman-1.dir/pixman-bits-image.c.o   -c /home/patrick/repos/vcpkg/buildtrees/pixman/src/pixman-0.34.0/pixman/pixman-bits-image.c                                                     In file included from /home/patrick/repos/vcpkg/buildtrees/pixman/src/pixman-0.34.0/pixman/pixman-private.h:34:0,                        from /home/patrick/repos/vcpkg/buildtrees/pixman/src/pixman-0.34.0/pixman/pixman-bits-image.c:35:      /home/patrick/repos/vcpkg/buildtrees/pixman/src/pixman-0.34.0/pixman/pixman-compiler.h:230:6: error:` **#error "Unknown thread local support for this system. Pixman will not work with multiple threads. Define PIXMAN_NO_TLS to acknowledge and accept this limitation and compile pixman without thread-safety support."                                                 #    error "Unknown thread local support for this system. Pixman will not work with multiple threads. Define PIXMAN_NO_TLS to acknowledge and accept this limitation and compile pixman without thread-safety support."                              ^~~~~                                                                                                             ninja: build stopped: subcommand failed.**

I have only experienced this issue on linux, not on windows.

**Comment by PhoebeHui** [comment]
@irishpatrick, thank you for posting this issue, please try to install cairo with latest vcpkg revision, and please open a new issue if this is still a problem for you.

Cairo installed successfully currently:
linux001@linuxtest01:~/vcpkg$ ./vcpkg install cairo
The following packages will be built and installed:
    cairo[core]:x64-linux
  * fontconfig[core]:x64-linux
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: fontconfig:x64-linux
Building package fontconfig[core]:x64-linux...
-- Using cached /home/linux001/vcpkg/downloads/fontconfig-2.12.4.tar.gz
-- Using source at /home/linux001/vcpkg/buildtrees/fontconfig/src/2.12.4-3074630478
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Performing CMake integration test
-- Performing post-build validation
-- Performing post-build validation done
Building package fontconfig[core]:x64-linux... done
Installing package fontconfig[core]:x64-linux...
Installing package fontconfig[core]:x64-linux... done
Elapsed time for package fontconfig:x64-linux: 4.605 s
Starting package 2/2: cairo:x64-linux
Building package cairo[core]:x64-linux...
-- Using cached /home/linux001/vcpkg/downloads/cairo-1.15.8.tar.xz
-- Using source at /home/linux001/vcpkg/buildtrees/cairo/src/1.15.8-b8303883e7
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Performing CMake integration test
-- Performing post-build validation
-- Performing post-build validation done
Building package cairo[core]:x64-linux... done
Installing package cairo[core]:x64-linux...
Installing package cairo[core]:x64-linux... done
Elapsed time for package cairo:x64-linux: 16.6 s

Total elapsed time: 21.2 s

The package cairo:x64-linux provides CMake targets:

    find_package(unofficial-cairo CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::cairo::cairo unofficial::cairo::cairo-gobject)
