### ISSUE TITLE
Add toolsrc/ to .gitignore?

### ISSUE THREAD

**Issue by patrikhuber** [microsoft/vcpkg#4253]
When you build something on Linux, git then shows a few dozen unstaged files in `toolsrc/build.rel/`.
Probably that directory should be added to `.gitignore`? Or did I somehow screw up my local installation a bit?

**Comment by PhoebeHui** [comment]
@patrikhuber, we can't add toolsrc to .gitignore, this folder contains VCPKG source files, also it shouldn't generate toolsrc/build.rel/, please clean up your local vcpkg and clone new one.
