### ISSUE TITLE
Issue installing qhull

### ISSUE THREAD

**Issue by Undertoe** [Microsoft/vcpkg#4254]
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Release;--target;install;--;-v;-j1
    Working Directory: I:/VCPKG/vcpkg/buildtrees/qhull/x64-windows-static-rel
    See logs for more information:
      I:\VCPKG\vcpkg\buildtrees\qhull\install-x64-windows-static-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/qhull/portfile.cmake:24 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package qhull:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qhull:x64-windows-static
  Vcpkg version: 0.0.113-nohash

vcpkg update says everythin gis up to date.

**Comment by Undertoe** [comment]
[install-x64-windows-static-rel-out.log](https://github.com/Microsoft/vcpkg/files/2364839/install-x64-windows-static-rel-out.log)


my rel-out.log

**Comment by Undertoe** [comment]
I guess i solved it

Deleted the tmp QHull#####.rar file found in the vcpkg/Downloads/ area and rebuilt, seems to work now.

**Comment by traversaro** [comment]
For reference, I had the same problem today while building `qhull:x64-windows-static` and deleting the qhull archive from `vcpkg/Downloads` fixed the issue for me as well.
