### ISSUE TITLE
Please add Acid game engine to vcpkg

### ISSUE THREAD

**Issue by ThinkalVB** [microsoft/vcpkg#4256]
https://github.com/Equilibrium-Games/Acid

**Comment by jepessen** [comment]
Can't you read the [documentation](https://github.com/Microsoft/vcpkg/blob/master/CONTRIBUTING.md) and try to add it by yourself?

**Comment by ThinkalVB** [comment]
sorry, I couldn't find any step by step instruction to add a package to vcpkg in your above-mentioned "documentation" link .

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
