### ISSUE TITLE
Integration of opentelemetry cpp libs with ant built failing with linker error for __std_find_trivial_1

### ISSUE THREAD

**Issue by pallavibhingarkar** [microsoft/vcpkg#42564]
Steps to reproduce:
1. 
Opentelemetry CPP is built with below options:
cmake .. -DBUILD_TESTING=OFF           \
  -DWITH_EXAMPLES=OFF                  \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo    \
  -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
  -DBUILD_SHARED_LIBS=OFF               \
  -DWITH_OTLP_GRPC=OFF                  \
  -DWITH_OTLP_HTTP=ON                  \
  -DWITH_ABSEIL=OFF                     \
  -DWITH_BENCHMARK=OFF                 \
  -DCMAKE_CXX_STANDARD=20              \
  -DWITH_ABI_VERSION_2=ON              \
  -DWITH_ABI_VERSION_1=OFF
  -DWITH_STL=CXX20

2. Integrating opentemetry libs with exsiting ant build framework gives below error:

      [make]      [make] opentelemetry_metrics.lib(instrument_metadata_validator.obj) : error LNK2019: unresolved external symbol __std_find_trivial_1 referenced in function "char const * __cdecl __std_find_trivial<char const ,unsigned char>(char const *,char const *,unsigned char)" (??$__std_find_trivial@$$CBDE@@YAPEBDPEBD0E@Z)
      [make]      [make] opentelemetry_metrics.lib(instrument_selector_factory.obj) : error LNK2001: unresolved external symbol __std_find_trivial_1
      [make]      [make] opentelemetry_metrics.lib(meter_selector_factory.obj) : error LNK2001: unresolved external symbol __std_find_trivial_1

**Comment by dg0yt** [comment]
I don't see vcpkg here.

**Comment by Mengna-Li** [comment]
I don't have more information to solve this issue. Please provide the repro steps. If it's not a vcpkg related issue, please submit it to the upstream. Thanks.

**Comment by pallavibhingarkar** [comment]
This is was due MSVC toolset = 142...changing it -> 143 resovled issue.
