### ISSUE TITLE
Issue with atlmfc:x64-windows

### ISSUE THREAD

**Issue by Pideeeh** [Microsoft/vcpkg#4257]
I can't install vtk[qt] because of the following error:

```
Starting package 1/31: atlmfc:x64-windows
Building package atlmfc[core]:x64-windows...
CMake Error at ports/atlmfc/portfile.cmake:7 (message):
  Unable to locate 'afxres.h'.  Ensure you have installed the ATL/MFC
  component of Visual Studio.
Call Stack (most recent call first):
  scripts/ports.cmake:71 (include)


Error: Building package atlmfc:x64-windows failed with: BUILD_FAILED
```

 Package: atlmfc:x64-windows
  Vcpkg version: 0.0.113-nohash

**Comment by drescherjm** [comment]
You need to add atl/mfc to your Visual Studio.

**Comment by alexkaratarakis** [comment]
To do so, start the Visual Studio Installer, under the "More" dropdown, click "Modify" and make sure the following boxes are checked:

<img width="1015" alt="atl-mfc-installer" src="https://user-images.githubusercontent.com/128712/45332227-453ee500-b524-11e8-9caf-16ac9195efe5.PNG">

**Comment by LarryIII** [comment]
@Pideeeh Please close this feedback if you resolved your issue with above helps. Thank you!

**Comment by miyu** [comment]
Installing ATL/MFC is quite confusing. Here's a config that worked for me:

![image](https://user-images.githubusercontent.com/1606755/66286249-60923600-e885-11e9-83ec-e76a206366d5.png)

For some reason, installing just v14.22 ATL & MFC didn't work (I'd get the "Ensure you have installed the ATL/MFC" error). I needed to select "C++ ATL for latest v142 build tools" and "C++ MFC for latest v142 build tools". The installer seemed to download nothing, but now things work.
