### ISSUE TITLE
[Request] Cocos2D-x package

### ISSUE THREAD

**Issue by NebuHiiEjamu** [microsoft/vcpkg#4258]
I would like to request Cocos2D-x be added to vcpkg. Even with its prerequisites installed, it is very frustrating to build with CMake, because it prefers its own copies of the prerequisite libraries. The Visual Studio project file provided with it only supports 32-bit. In addition, MSYS2/MinGW-w64 will not build it because Cocos no longer supports it on Windows, telling me to use Visual Studio instead.

I would contribute such a package myself, but I'm an utter mess at portfiles.

**Comment by Voskrese** [comment]
it is not clear what you want
do you want someone to create a library from cocos?

**Comment by NebuHiiEjamu** [comment]
Oh! Sorry. I meant the C/C++ library.

**Comment by Voskrese** [comment]
https://github.com/Microsoft/vcpkg/issues/4124

**Comment by Voskrese** [comment]
The main purpose of vcpkg for this is
what prevents to create in vcpkg library and to connect it in other projects?

**Comment by NebuHiiEjamu** [comment]
Well it's a game development library, similar to Allegro, SDL or SFML, which there are packages for.

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
