### ISSUE TITLE
[protobuf] build failure

### ISSUE THREAD

**Issue by alexander-smyslov** [microsoft/vcpkg#42582]
### Operating system

Alpine Linux

### Compiler

GCC 14.2

### Steps to reproduce the behavior

```Shell
`./vcpkg install protobuf`
```

### Failure logs

/builds/dealing/vcpkg/triplets/x64-linux.cmake: info: loaded overlay triplet from here
-- Using cached protocolbuffers-protobuf-v4.25.1.tar.gz.
-- Extracting source /builds/dealing/vcpkg/vcpkg/downloads/protocolbuffers-protobuf-v4.25.1.tar.gz
-- Applying patch fix-static-build.patch
-- Applying patch fix-default-proto-file-path.patch
-- Applying patch fix-utf8-range.patch
-- Applying patch fix-arm64-msvc.patch
-- Using source at /builds/dealing/vcpkg/vcpkg/buildtrees/protobuf/src/v4.25.1-984c7075eb.clean
-- Configuring x64-linux
-- Building x64-linux-dbg
CMake Warning at scripts/cmake/vcpkg_execute_build_process.cmake:65 (message):
  Please ensure your system has sufficient memory.
Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/protobuf/portfile.cmake:61 (vcpkg_cmake_install)
  scripts/ports.cmake:192 (include)
-- Restarting build without parallelism
-- Building x64-linux-rel
WARNING: step_script could not run to completion because the timeout was exceeded. For more control over job and script timeouts see: https://docs.gitlab.com/ee/ci/runners/configure_runners.html#set-script-and-after_script-timeouts

But successfully compile after add DISABLE_PARALLEL to vcpkg_cmake_install(DISABLE_PARALLEL) 
can create MR and there are several options
- for all 
- for linux and static build only
- option in port  ./vcpkg install protobuf[disable_parallel_build]

**Comment by dg0yt** [comment]
Before any fix, what is the actual error (in the build log) causing "Restarting build without parallelism"?

**Comment by alexander-smyslov** [comment]
We have some limitation on gitlab runner:
resources:
      limits:
        cpu: "8"
        ephemeral-storage: 30Gi
        memory: 15Gi


Use VCPKG_MAX_CONCURRENCY=4 to reduce CPU and memory consumption
Same as https://github.com/microsoft/vcpkg/issues/42281 
and https://github.com/microsoft/vcpkg/issues/40083
