### ISSUE TITLE
error when building cmake project with qt5 widget libraries

### ISSUE THREAD

**Issue by jepessen** [microsoft/vcpkg#4259]
I've installed Qt5 (64 bit) libraries with following command:

`vcpkg install qt5:x64-windows`

It worked (I've only changed the url of freetype port file). Then I'm trying to build a project with a master cmake and child cmake files. Main CMakeLists.txt is like the following one:

```
cmake_minimum_required (VERSION 3.7.0)

include(CTest)

set (CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/build/lib)
set (CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/build/lib)
set (CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/build/bin)
set (TEST_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/build/tests)
set (DOC_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/build/doc)
set (CMAKE_PREFIX_PATH ${QT_ROOT})

add_subdirectory (src)
add_subdirectory (tests)
add_subdirectory (doc)
```

A CMakeLists.txt in src folder is like this one:

```
cmake_minimum_required (VERSION 3.7.0)

project(wonderfulproject)

message (STATUS "Building project ${PROJECT_NAME}")

set (Boost_USE_STATIC_LIBS ON)
set (Boost_USE_MULTITHREADED ON)
unset (Boost_INCLUDE_DIR CACHE)
unset (Boost_LIBRARY_DIRS CACHE)
set (CMAKE_INCLUDE_CURRENT_DIR ON)
set (CMAKE_AUTOMOC ON)
set (CMAKE_AUTORCC ON)

find_package(Qt5LinguistTools REQUIRED)
find_package(Qt5Widgets REQUIRED)
find_package (Boost COMPONENTS program_options REQUIRED)
include_directories (${CMAKE_SOURCE_DIR}/src ${CMAKE_CURRENT_SOURCE_DIR} ${Boost_INCLUDE_DIRS})
file (GLOB_RECURSE PROJECT_SRC *.cpp)
file (GLOB PROJECT_QRC ${CMAKE_SOURCE_DIR}/resources/${PROJECT_NAME}/${PROJECT_NAME}.qrc)

add_executable(${PROJECT_NAME} ${PROJECT_SRC} ${PROJECT_QRC})
target_link_libraries(${PROJECT_NAME} Qt5::Widgets ${Boost_LIBRARIES})
```

Then I go to build folder and I use the following command:

```
cmake .. "-DCMAKE_TOOLCHAIN_FILE=F:\lib\vcpkg\scripts\buildsystems\vcpkg.cmake" -G "Visual Studio 15 2017 Win64"
```

CMake command does not find Qt: this is the output:

```
-- Building project wonderfulproject
CMake Error at F:/lib/vcpkg/scripts/buildsystems/vcpkg.cmake:247 (_find_package):
  By not providing "FindQt5LinguistTools.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5LinguistTools", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake

  Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
  set "Qt5LinguistTools_DIR" to a directory containing one of the above
  files.  If "Qt5LinguistTools" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  src/wonderfulproject/CMakeLists.txt:15 (find_package)


-- Configuring incomplete, errors occurred!
See also "F:/wteam/projects/myproject/build/CMakeFiles/CMakeOutput.log".
```

It's also the same with Qt5Widges (I've tried to switch order of Qt libraries in CMakeLists.txt and it's the same).

How can I solve it?

I'm using Windows 10, with vcpkg version 0.0.113-nohash and CMake 3.11.

**Comment by Voskrese** [comment]
`cmake .. "-DCMAKE_TOOLCHAIN_FILE=F:\lib\vcpkg\scripts\buildsystems\vcpkg.cmake" -G "Visual Studio 15 2017 Win64"`
+ 
`-DQt5LinguistTools_DIR="F:/lib/vcpkg/.../.../LinguistTools/..."`

**Comment by jepessen** [comment]
Ok it works. Is there a reason for which they are not defined with the port file? It's always necessary to specify them?

**Comment by Voskrese** [comment]
`edit CMAKE_TOOLCHAIN_FILE=\...\...\vcpkg.cmake"`
<<--
` -DQt5LinguistTools_DIR="F:/lib/vcpkg/.../$?triplet/$?arch/.../LinguistTools/..."`

**Comment by fferri** [comment]
To support cmake projects out of the box, the qt5* vcpkg ports need to install related *.cmake files, e.g.:

```
<destination dir>/lib/cmake/Qt5LinguistTools/Qt5LinguistToolsConfigVersion.cmake
<destination dir>/lib/cmake/Qt5LinguistTools/Qt5LinguistToolsMacros.cmake
<destination dir>/lib/cmake/Qt5LinguistTools/Qt5LinguistToolsConfig.cmake
```

and similarily for every other qt5* package.

Only in this way `find_package(Qt5XXX REQUIRED)` can work without specifying a ton of variables.

The solution proposed by @Voskrese may work, but it is not sustainable to specify `-DQt5<PACKAGE>_DIR="F:/lib/vcpkg/.../$?triplet/$?arch/.../<PACKAGE>/..."` for every Qt5 package  `<PACKAGE>`, as a project may use up to 60 of such packages.

**Comment by JackBoosY** [comment]
Hi @jepessen, thanks for reporting this issue.
Since qt5 has been upgraded to 5.12.5, this issue may be fixed.
So please update vcpkg and rebuild qt5.

Thanks.
