### ISSUE TITLE
[abseil] Missing folder in installation

### ISSUE THREAD

**Issue by usernameiwantedwasalreadytaken** [Microsoft/vcpkg#4262]
I've just installed vcpkg from master, then installed abseil (`vcpkg install abseil`). When I tried to compile this program:

```c++
#include <cstdio>
#include <absl/strings/str_format.h>

int main() {
  auto s = absl::StrFormat("Hello, %s!", "World");
  puts(s.data());
  return 0;
}
```

And got this error:

```
---- Build started: Project: AbseilTests, Configuration: Debug Win32 ------
1>main.cpp
1>c:\vcpkg\installed\x86-windows\include\absl\strings\str_format.h(75): fatal error C1083: Cannot open include file: 'absl/strings/internal/str_format/arg.h': No such file or directory
1>Done building project "AbseilTests.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

Indeed, there is no file `absl/strings/internal/str_format/arg.h` in the vcpkg installation:

```
 Directory of C:\vcpkg\installed\x86-windows\include\absl\strings\internal

11/09/2018  08:44    <DIR>          .
11/09/2018  08:44    <DIR>          ..
11/09/2018  08:44             1,720 bits.h
11/09/2018  08:44            15,248 charconv_bigint.h
11/09/2018  08:44             4,351 charconv_parse.h
11/09/2018  08:44             5,532 char_map.h
11/09/2018  08:44             6,130 escaping_test_common.h
11/09/2018  08:44             5,878 memutil.h
11/09/2018  08:44             5,733 numbers_test_common.h
11/09/2018  08:44             2,874 ostringstream.h
11/09/2018  08:44             2,608 resize_uninitialized.h
11/09/2018  08:44            11,418 stl_type_traits.h
11/09/2018  08:44            10,589 str_join_internal.h
11/09/2018  08:44            17,009 str_split_internal.h
11/09/2018  08:44             1,685 utf8.h
```

In the abseil master there is a directory `str_format` (`https://github.com/abseil/abseil-cpp/tree/master/absl/strings/internal/str_format`), so I believe this might be a case of just updating abseil to a new version (maybe master).

**Comment by usernameiwantedwasalreadytaken** [comment]
I've checked and the file downloaded by vcpkg to install abseil (`abseil-abseil-cpp-c2e00d341913bf03b4597ade5b056042e23e8c58.tar.gz`) does contain the `absl/strings/internal/str_format` folder.

The problem is in `https://github.com/Microsoft/vcpkg/blob/master/ports/abseil/CMakeLists.txt`. It is not installing this folder. Line 21 is:

```
file(GLOB INTERNAL_HEADERS "absl/${LIB}/internal/*.h")
```

But this does not include the sub directories from internal.

**Comment by OlafvdSpek** [comment]
`GLOB_RECURSE` doesn't do the trick as all files will end up directly in the internal directory.
Any thoughts?

**Comment by kjpus** [comment]
See PR #4442.

**Comment by LarryIII** [comment]
@usernameiwantedwasalreadytaken Hello, I think this issue was fixed by abseil version updating in VCPKG. Could you please try again and close this issue if it was resolved?

**Comment by OlafvdSpek** [comment]
@LarryIII 

```
error LNK2001: unresolved external symbol "unsigned char const * const absl::ascii_internal::kPropertyBits" (?kPropertyBits@ascii_internal@absl@@3QBEB)

#include <absl/strings/ascii.h>
#include <iostream>

using namespace std;

int main()
{
  cout << absl::ascii_isalpha(-1) << "\n";
  return 0;
}
```

**Comment by wangli28** [comment]
Please open a new issue if this is still a problem for you.
