### ISSUE TITLE
Failures to push artifacts to vcpkg binary cache in Azure pipelines

### ISSUE THREAD

**Issue by ahojnnes** [microsoft/vcpkg#42645]
Error message:
```
error: curl failed to put file to ...
```
See, for example: https://dev.azure.com/vcpkg/public/_build/results?buildId=110295&view=logs&j=7922e5c4-0103-5f8f-ad17-45ce9bb98e80&t=8ceef4ed-9be5-594f-e707-4e1dd58a3d21

**Comment by dg0yt** [comment]
There is a long-standing known issue with large binary artifacts. llvm is the most frequent case.
https://github.com/microsoft/vcpkg/issues/21905

**Comment by MonicaLiu0311** [comment]
Duplicate of https://github.com/microsoft/vcpkg/issues/21905.
