### ISSUE TITLE
suspended installation when install openssl-windows[core]:x64-windows

### ISSUE THREAD

**Issue by poxis** [microsoft/vcpkg#4264]
Hello, i try new install (remove folder vcpkg)  and and everytime installation is stopped without error..

>Starting package 54/56: openssl-windows:x64-windows
Building package openssl-windows[core]:x64-windows...
-- Downloading http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portable.zip...
-- Downloading https://www.openssl.org/source/openssl-1.0.2p.tar.gz...
-- Extracting source C:/vcpkg/downloads/openssl-1.0.2p.tar.gz
-- Applying patch C:/vcpkg/ports/openssl-windows/ConfigureIncludeQuotesFix.patch
-- Applying patch C:/vcpkg/ports/openssl-windows/STRINGIFYPatch.patch
-- Applying patch C:/vcpkg/ports/openssl-windows/EmbedSymbolsInStaticLibsZ7.patch
-- Downloading http://www.nasm.us/pub/nasm/releasebuilds/2.12.02/win32/nasm-2.12.02-win32.zip...
-- Downloading http://download.qt.io/official_releases/jom/jom_1_1_2.zip...
-- Configure x64-windows-rel
-- Configure x64-windows-rel done
-- Build x64-windows-rel
-- Build x64-windows-rel done
-- Configure x64-windows-dbg
-- Configure x64-windows-dbg done
-- Build x64-windows-dbg
-- Build x64-windows-dbg done
> 
and nothing else. (I waited 2 hours)

[build-x64-windows-dbg-0-err.log](https://github.com/Microsoft/vcpkg/files/2371886/build-x64-windows-dbg-0-err.log)
[build-x64-windows-dbg-0-out.log](https://github.com/Microsoft/vcpkg/files/2371887/build-x64-windows-dbg-0-out.log)
[build-x64-windows-dbg-1-err.log](https://github.com/Microsoft/vcpkg/files/2371888/build-x64-windows-dbg-1-err.log)
[build-x64-windows-dbg-1-out.log](https://github.com/Microsoft/vcpkg/files/2371889/build-x64-windows-dbg-1-out.log)

**Comment by Voskrese** [comment]
`install x64-windows.log` attach

build ok

```
Copying: out32dll.dbg/openssl.exe to C:/vcpkg/packages/openssl-windows_x64-windows/debug/bin/openssl.exe
	perl util/mkdir-p.pl "C:\vcpkg\packages\openssl-windows_x64-windows\debug"
	perl util/copy.pl apps\openssl.cnf "C:\vcpkg\packages\openssl-windows_x64-windows\debug"
Copying: apps/openssl.cnf to C:/vcpkg/packages/openssl-windows_x64-windows/debug/openssl.cnf
	perl util/copy.pl "out32dll.dbg\ssleay32.dll" "C:\vcpkg\packages\openssl-windows_x64-windows\debug\bin"
Copying: out32dll.dbg/ssleay32.dll to C:/vcpkg/packages/openssl-windows_x64-windows/debug/bin/ssleay32.dll
	perl util/copy.pl "out32dll.dbg\libeay32.dll" "C:\vcpkg\packages\openssl-windows_x64-windows\debug\bin"
Copying: out32dll.dbg/libeay32.dll to C:/vcpkg/packages/openssl-windows_x64-windows/debug/bin/libeay32.dll
	perl util/copy.pl "out32dll.dbg\ssleay32.lib" "C:\vcpkg\packages\openssl-windows_x64-windows\debug\lib"
Copying: out32dll.dbg/ssleay32.lib to C:/vcpkg/packages/openssl-windows_x64-windows/debug/lib/ssleay32.lib
	perl util/copy.pl "out32dll.dbg\libeay32.lib" "C:\vcpkg\packages\openssl-windows_x64-windows\debug\lib"
Copying: out32dll.dbg/libeay32.lib to C:/vcpkg/packages/openssl-windows_x64-windows/debug/lib/libeay32.lib
```

**Comment by poxis** [comment]
>./vcpkg install x64-windows.log
Failed at [c:\vcpkg\toolsrc\src\vcpkg\packagespec.cpp(75)] with message:
Contains invalid characters. Only alphanumeric lowercase ASCII characters and dashes are allowed
>

**Comment by Voskrese** [comment]
attach `install-x64-windows-...-err.log`

**Comment by poxis** [comment]
i no have files  "install-x64-windows*

**Comment by poxis** [comment]
[configure-do-x64-windows--dbg-err.log](https://github.com/Microsoft/vcpkg/files/2382023/configure-do-x64-windows--dbg-err.log)
[configure-do-x64-windows--dbg-out.log](https://github.com/Microsoft/vcpkg/files/2382024/configure-do-x64-windows--dbg-out.log)
[configure-perl-x64-windows--dbg-out.log](https://github.com/Microsoft/vcpkg/files/2382025/configure-perl-x64-windows--dbg-out.log)

[build-x64-windows-rel-1-err.log](https://github.com/Microsoft/vcpkg/files/2382026/build-x64-windows-rel-1-err.log)
[build-x64-windows-rel-1-out.log](https://github.com/Microsoft/vcpkg/files/2382027/build-x64-windows-rel-1-out.log)
[build-x64-windows-rel-0-err.log](https://github.com/Microsoft/vcpkg/files/2382028/build-x64-windows-rel-0-err.log)
[build-x64-windows-rel-0-out.log](https://github.com/Microsoft/vcpkg/files/2382029/build-x64-windows-rel-0-out.log)
[configure-do-x64-windows--rel-err.log](https://github.com/Microsoft/vcpkg/files/2382030/configure-do-x64-windows--rel-err.log)
[configure-do-x64-windows--rel-out.log](https://github.com/Microsoft/vcpkg/files/2382031/configure-do-x64-windows--rel-out.log)

[configure-perl-x64-windows--rel-out.log](https://github.com/Microsoft/vcpkg/files/2382032/configure-perl-x64-windows--rel-out.log)


[patch-x64-windows-0-err.log](https://github.com/Microsoft/vcpkg/files/2382033/patch-x64-windows-0-err.log)

[patch-x64-windows-1-err.log](https://github.com/Microsoft/vcpkg/files/2382034/patch-x64-windows-1-err.log)

[patch-x64-windows-2-err.log](https://github.com/Microsoft/vcpkg/files/2382035/patch-x64-windows-2-err.log)

**Comment by Voskrese** [comment]
LINK : fatal error LNK1181: cannot open input file 'out32dll\libeay32.lib'

**Comment by Voskrese** [comment]
delete all files - 
C:\Users\Admin\AppData\Local\Temp\
C:\vcpkg\buildtrees\openssl-windows\

**Comment by poxis** [comment]
idk... still no work :( 

[build-x64-windows-rel-0-err.log](https://github.com/Microsoft/vcpkg/files/2384379/build-x64-windows-rel-0-err.log)
[build-x64-windows-rel-0-out.log](https://github.com/Microsoft/vcpkg/files/2384380/build-x64-windows-rel-0-out.log)
[configure-do-x64-windows--rel-err.log](https://github.com/Microsoft/vcpkg/files/2384381/configure-do-x64-windows--rel-err.log)
[configure-do-x64-windows--rel-out.log](https://github.com/Microsoft/vcpkg/files/2384382/configure-do-x64-windows--rel-out.log)

[configure-perl-x64-windows--rel-out.log](https://github.com/Microsoft/vcpkg/files/2384383/configure-perl-x64-windows--rel-out.log)


[patch-x64-windows-0-err.log](https://github.com/Microsoft/vcpkg/files/2384384/patch-x64-windows-0-err.log)

[patch-x64-windows-1-err.log](https://github.com/Microsoft/vcpkg/files/2384386/patch-x64-windows-1-err.log)

[patch-x64-windows-2-err.log](https://github.com/Microsoft/vcpkg/files/2384387/patch-x64-windows-2-err.log)

[build-x64-windows-dbg-0-err.log](https://github.com/Microsoft/vcpkg/files/2384388/build-x64-windows-dbg-0-err.log)
[build-x64-windows-dbg-0-out.log](https://github.com/Microsoft/vcpkg/files/2384389/build-x64-windows-dbg-0-out.log)
[build-x64-windows-dbg-1-err.log](https://github.com/Microsoft/vcpkg/files/2384390/build-x64-windows-dbg-1-err.log)
[build-x64-windows-dbg-1-out.log](https://github.com/Microsoft/vcpkg/files/2384391/build-x64-windows-dbg-1-out.log)
[configure-do-x64-windows--dbg-err.log](https://github.com/Microsoft/vcpkg/files/2384392/configure-do-x64-windows--dbg-err.log)
[configure-do-x64-windows--dbg-out.log](https://github.com/Microsoft/vcpkg/files/2384393/configure-do-x64-windows--dbg-out.log)

[configure-perl-x64-windows--dbg-out.log](https://github.com/Microsoft/vcpkg/files/2384394/configure-perl-x64-windows--dbg-out.log)
[build-x64-windows-rel-1-err.log](https://github.com/Microsoft/vcpkg/files/2384395/build-x64-windows-rel-1-err.log)
[build-x64-windows-rel-1-out.log](https://github.com/Microsoft/vcpkg/files/2384396/build-x64-windows-rel-1-out.log)

**Comment by jy189** [comment]
I've met the same problem, any solution?
[build-x64-windows-dbg-0-out.log](https://github.com/Microsoft/vcpkg/files/2977133/build-x64-windows-dbg-0-out.log)
[build-x64-windows-dbg-0-err.log](https://github.com/Microsoft/vcpkg/files/2977135/build-x64-windows-dbg-0-err.log)

**Comment by Voskrese** [comment]
open shell cmd.exe
call //cmdVSenv//

`cd E:\program files\vcpkg-master\buildtrees\openssl-windows\x64-windows-dbg\openssl-1.0.2q`

`link /nologo /subsystem:console /opt:ref /debug /dll /out:out32dll.dbg\ssleay32.dll /def:ms/SSLEAY32.def`

> I see only one possible problem, gaps in the paths
> many utilities do not work well with such paths

**move** folder E:\program files\vcpkg-master
**to** E:\vcpkg-master

**Comment by jy189** [comment]
> open shell cmd.exe
> call //cmdVSenv//
> 
> `cd E:\program files\vcpkg-master\buildtrees\openssl-windows\x64-windows-dbg\openssl-1.0.2q`
> 
> `link /nologo /subsystem:console /opt:ref /debug /dll /out:out32dll.dbg\ssleay32.dll /def:ms/SSLEAY32.def`
> 
> > I see only one possible problem, gaps in the paths
> > many utilities do not work well with such paths
> 
> **move** folder E:\program files\vcpkg-master
> **to** E:\vcpkg-master

Thanks for your reply. I re-installed vcpkg in the root of C:\ and it still came out with that error message. Is there any possilbilty that something's wrong with openssl?

**Comment by NancyLi1013** [comment]
Hi @poxis, thanks for posting this issue. The port openssl-windows has been updated. I can't reproduce it on my machine. Please update the port to the latest version and try it again. Feel free to reopen it if this is still a problem for you.
