### ISSUE TITLE
Simple Curl example fails to copy release DLLs 

### ISSUE THREAD

**Issue by nomizzz** [microsoft/vcpkg#4265]
Using Windows 10 to do release builds (as opposed to the default Debug triplets) has been problematic using vcpkg, mainly because either the Release builds wind up using the debug generated libs or the final step does copy the DLLs into the binary directory.  

To figure out best practices I simplified my example to a Curl version of the [SQLite3 demo](https://github.com/Microsoft/vcpkg/blob/master/docs/examples/using-sqlite.md) from the docs.

Here's the two files in the simple project that I based off the SQLite3 demo:

```
# CMakeLists.txt
cmake_minimum_required(VERSION 3.0)
project(test)

find_path(CURL_INCLUDE_DIR curl/curl.h)
find_library(CURL_LIBRARY libcurl)

add_executable(main main.cpp)
target_include_directories(main PUBLIC ${CURL_INCLUDE_DIR})
target_link_libraries(main ${CURL_LIBRARY})
```

Then, in the spirit of the Sqlite3 demo I just print the curl version as follows:
```
// main.cpp
#include <stdio.h>
#include <curl/curl.h>

int main()
{
    printf("%s\n", curl_version());
    return 0;
}
```

The CMake commands generated a nice project which worked well for a Debug build, but when I compile it for Release with `cmake --build . --config Release` the required dlls (libcurl, LIBEAY32.DLL, SSLEAY32.dll, and zlib1.dll -- and not zlib1d.dll) do not get copied over into the ".\Release\" folder.  Do I need to define additional settings to get this to work for release?

Also, since the Curl Port uses CMake I initially tried to stick with cleaner simpler CMakeLists.txt that just had a `find_package(curl NAMES libcurl REQUIRED)` as in the SQLite3 example with a slight name adjustment, but running the build gave a `fatal error C1083: Cannot open include file: 'curl/curl.h': No such file or directory`.  What would be required to just use the find_package command with Curl instead of having to manually located the include directories and libraries?

**Comment by NancyLi1013** [comment]
Hi @nomizzz thanks for posting this issue.
Does this issue exist on your machine now? 
I can build debug and release type successfully on my local .
I used this to build:
```
find_package(CURL CONFIG REQUIRED)
target_link_libraries(MyProjectName PRIVATE CURL::libcurl)
```
Let me know if you have any problems about this issue.

Thanks.

**Comment by NancyLi1013** [comment]
Since this port has been updated and it supports `find_package().` It should be fixed now.
Please try to update vcpkg and rebuild it.
