### ISSUE TITLE
[qt 6.8.0] Runtime crash because of ICU

### ISSUE THREAD

**Issue by troopa81** [microsoft/vcpkg#42661]
**Describe the bug**

When building [QGIS](http://github.com/qgis/QGIS), I got a crash when starting the application inside the icu dll.

If we build [without ICU](https://github.com/troopa81/QGIS/commit/1655e8a121093e178c3864e9bd7bc49b8acc8f5b#diff-e5d5111297d1c878b8c128ba5cd6e260189259b0d720e8ed44a64375517692b6L74), we get no crash and the application runs fine.

An [issue](https://bugreports.qt.io/browse/QTBUG-129896) with ICU has been fixed in 6.8.1 but I understand it has been [patched](https://github.com/microsoft/vcpkg/pull/41534/files#r1849442467) so we are supposed to be OK on this.

Actually Qt is not [building](https://bugreports.qt.io/browse/COIN-1186) and releasing their binaries with ICU, so should vcpkg do the same until they maybe [change their mind](https://bugreports.qt.io/browse/QTBUG-121353) ?

**Environment**
- OS: Windows 
- Compiler: Microsoft Visual Studio 2022

**To Reproduce**
1. Build QGIS (sorry, I don't have a simple example program to test with)
2. Run it
3. See crash

**Expected behavior**
No crash

**Failure logs**

<details>
<summary>Crash screenshots in Visual Studio</summary>

**Stacktrace bottom**
![Image](https://github.com/user-attachments/assets/0d776f9a-d68a-4847-967c-9b8fe0ff7b6e)

**Stacktrace top**
![Image](https://github.com/user-attachments/assets/409069df-5dcd-4b8b-85aa-2422c1348d69)

</details>

**Additional context**

None

**Comment by JonLiu1993** [comment]
@troopa81, Thanks for your issue. I suggest that we wait for the upstream to solve this problem and release a new version of Qt. We can directly upgrade the version instead of patching. What do you think?

**Comment by troopa81** [comment]
Looking at more closely, it seems that the vcpkg included patch doesn't include this [fix](https://codereview.qt-project.org/c/qt/qtbase/+/597083), avoiding infinite recursion, which looks like exactly as the issue I get.

So, 2 possible solution:
- patch 6.8.0
- wait for 6.8.1

I'll try to propose the patch for 6.8.0 if I manage to find the time

**Comment by troopa81** [comment]
6.8.1 is already approved, so I'll test with 6.8.1
