### ISSUE TITLE
[fontconfig] Build error on wasm32-emscripten

### ISSUE THREAD

**Issue by MattiaMontanari** [microsoft/vcpkg#42691]
### Operating system

MacOS 14.4.1 (Intel) and Windows 10

### Compiler

`em++`

### Steps to reproduce the behavior

```Shell
`vcpkg install fontconfig:wasm32-emscripten`
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
    fontconfig:wasm32-emscripten@2.15.0#1
Detecting compiler hash for triplet wasm32-emscripten...
Compiler found: /Users/mattiamontanari/repos/emsdk/upstream/emscripten/em++
Restored 0 package(s) from /Users/mattiamontanari/.cache/vcpkg/archives in 13.4 us. Use --debug to see more details.
Installing 1/1 fontconfig:wasm32-emscripten@2.15.0#1...
Building fontconfig:wasm32-emscripten@2.15.0#1...
/Users/mattiamontanari/repos/vcpkg/triplets/community/wasm32-emscripten.cmake: info: loaded community triplet from here. Community triplets are not built in the curated registry and are thus less likely to succeed.
-- Found Python version '3.11.7 at /opt/anaconda3/bin/python3'
-- Using meson: /Users/mattiamontanari/repos/vcpkg/downloads/tools/meson-1.6.0-ac58a9/meson.py
-- Using cached fontconfig-fontconfig-2.15.0.tar.gz.
-- Cleaning sources at /Users/mattiamontanari/repos/vcpkg/buildtrees/fontconfig/src/2.15.0-0e63e07859.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/mattiamontanari/repos/vcpkg/downloads/fontconfig-fontconfig-2.15.0.tar.gz
-- Applying patch no-etc-symlinks.patch
-- Applying patch libgetopt.patch
-- Applying patch fix-wasm-shared-memory-atomics.patch
-- Using source at /Users/mattiamontanari/repos/vcpkg/buildtrees/fontconfig/src/2.15.0-0e63e07859.clean
-- Found external ninja('1.12.1').
-- Configuring wasm32-emscripten-dbg
-- Getting CMake variables for wasm32-emscripten
-- Configuring wasm32-emscripten-dbg done
-- Configuring wasm32-emscripten-rel
-- Configuring wasm32-emscripten-rel done
-- Package wasm32-emscripten-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: /usr/local/bin/ninja install -v
    Working Directory: /Users/mattiamontanari/repos/vcpkg/buildtrees/fontconfig/wasm32-emscripten-dbg
    Error code: 1
    See logs for more information:
      /Users/mattiamontanari/repos/vcpkg/buildtrees/fontconfig/package-wasm32-emscripten-dbg-out.log

Call Stack (most recent call first):
  installed/x64-osx/share/vcpkg-tool-meson/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
  ports/fontconfig/portfile.cmake:41 (vcpkg_install_meson)
  scripts/ports.cmake:196 (include)

error: building fontconfig:wasm32-emscripten failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle fontconfig:wasm32-emscripten: 1.1 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+fontconfig
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[fontconfig]+Build+error+on+wasm32-emscripten&body=Copy+issue+body+from+%2FUsers%2Fmattiamontanari%2Frepos%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by MattiaMontanari** [comment]
Possible duplication of [42463](https://github.com/microsoft/vcpkg/issues/42463)

**Comment by dg0yt** [comment]
#42463 is for an older version of fontconfig, failing during configuration.
This issue is for the current version of fontconfig, failing during build.

I can fix the build by disabling thread supprt, but then it still fails after the build because `vcpkg_copy_tools` doesn't know how to handle the wasm artifacts. (And I don't know either, in particular as they come in pairs of .js+.wasm.)

**Comment by dg0yt** [comment]
Oh wait, we can disable the tools.
