### ISSUE TITLE
ffmpeg[all-nonfree]:x64-windows.No such filter: 'drawtext'

### ISSUE THREAD

**Issue by xengine-qyt** [microsoft/vcpkg#42748]
**Describe the bug**
[AVFilterGraph @ 000001D8EB0EA040] No such filter: 'drawtext'
[AVFilterGraph @ 000001D8EB0EA040] Error processing filtergraph: Filter not found

**Environment**
- OS: windows
- Compiler: vcpkg package management program version 2024-12-09-1005b78fa1bf1dde1a20c2734cba4ea61ca94d9a

**To Reproduce**
1. .\vcpkg.exe install ffmpeg[all-nonfree]
2. [in1]scale=1080:1920[bgout];[bgout]drawtext=text='www.xxxa':x=w-tw-680:y=h-th-80:fontfile='SourceHanSansCN.otf':fontsize=22:fontcolor=#FF0000FF:enable='between(n,0,360)'[out]

**Expected behavior**
support drawtext filter

**Failure logs**

**Additional context**
the filter api use avfilter_graph_parse_ptr.
and I tested the https://www.gyan.dev/ffmpeg/builds/ it is work

**Comment by dg0yt** [comment]
It is not wired into `all-*`. Try
~~~
.\vcpkg.exe install ffmpeg[all-nonfree,drawtext,fontconfig]
~~~
