### ISSUE TITLE
Does vcpkg build `-static` triplet with static CRT?

### ISSUE THREAD

**Issue by patrikhuber** [microsoft/vcpkg#4274]
So, I noticed the following today:

If I compile Ceres by myself, as a static library (as is recommended by the Ceres authors), with all their build settings set to default, I can use it in a standard CMake project, which uses `/MD` (dynamic CRT).
If I use Ceres from vcpkg `x64-windows-static`, then I get loads of `Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease'` errors. To make it work, I'd need to change my project from `/MD` to `/MT`, which I don't want to do, because I still want to use the dynamic CRT for my project.

It seems to be the same with OpenCV.

This seems like quite a big flaw of vcpkg to me. Or am I missing something?

Also, there's not really a way to mix-and-match static and dynamic libraries, is there? Like if I need to use Ceres from `x64-windows-static`, but the rest of the libraries (OpenCV etc.) I'd like to use from `x64-windows`.

Thanks for any insight or help.

**Comment by patrikhuber** [comment]
Okay, I think I can use a custom triplet with the following content:

```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
```

Trying it now!

**Comment by simon-p-r** [comment]
Hey @patrikhuber 

Did this work?  I have been unable to use a mixture static and dynamic libraries in projects.

Thanks

**Comment by patrikhuber** [comment]
Sorry for the lack of update on this, and Hi @simon-p-r! I've compiled it but haven't found the time yet to try it. I'll get to it eventually over the next few days or 1-2 weeks or so.

I think in principle it's really supposed to work though, see "Per-port customization" [here](https://vcpkg.readthedocs.io/en/latest/users/triplets/) where they mix dynamic and static linkage on a per-port basis.

May I ask what sort of error(s) you get and what exactly you're trying to do?

**Comment by degski** [comment]
@patrikhuber @simon-p-r  This practice [mixing static and dynamic libs], although it might work, is not necessarily working in principle. Only under stringent assumptions can this be made to work [in a way better then by luck]. There are many pitfalls, ODR, static variables (in different TU's) and their initialization, just to name a few. To satisfy those assumptions you'd probably have to be the author of those dependent libraries. This issue has been discussed on the Boost dev mailing list and also on /r/cpp. `vcpkg` does the right thing and implicitly forces you (unless you override it) to go either one way or the other. This unfortunately has as the effect that intel tbb, f.e. (which really can only be build as a dll), forces you to make your whole project dynamically linked.

**Comment by denis-gz** [comment]
@degski Forcing developers to go radically the one way or the other, is _not_ obviously the right way for a tool which is intended to aim them in their job. In such a tool like `vcpkg`, this is a must (if there're hopes for it to have wide developers adoption) to have standard ways for a library to specify its kind to be either static or dynamic, as well as specify CRT linkage to be either static or dynamic. Without it, spending a day fighting with this "kind of" helper tool, chances are a seasoned developer will never come back to it again, and just spend another day setting up build environment to get the lib/dll binary which fits their needs. Personally me is very close to this decision.

**Comment by terrylyons** [comment]
I agree with denis-gz. I think there is a misunderstanding by the vcpkg authors here  - between what is desirable in terms of linking to the runtime and linking between developer modules.  It is crucial that there is a uniform policy for the former (and /MD almost always is the way to go), but for the latter I think it is really not clear.  I can see many cases where making dlls will cause big headaches (e.g. by default, only the specially declared variables are visible to the external user of a .dll in windows while quite a different pattern emerges for the same code for the .so user in unix).

The choice of linking my code TO a package and linking a package TO the CRT are completely different issues. The need for the latter to be consistent is totally clear. It belongs in the triplet. The choice for the former is far more fine grained and can go either way depending on the context at least for the /MD versions. When I create my boost libraries (or any others), I usually generate a static and a dll version; but both are dynamically linked (/MD) to the CRT. I think this is best practise. The choice of which one to use needs to be specified in the cmake, vsbuild, or wherever the build happens not at the time the libraries are setup.

 [https://devblogs.microsoft.com/cppblog/vcpkg-updates-static-linking-is-now-available/](https://devblogs.microsoft.com/cppblog/vcpkg-updates-static-linking-is-now-available/) To see

**Comment by terrylyons** [comment]
> I agree with @denis-gz as well, however we can't test every combination. This project is attempting to provide a set of default triplets which we test while allowing the developer as much flexibility as possible. To achieve your goal of picking and choosing how to build each library you can copy the port you would like to override the default behavior into a port-overlay folder and add a call to the force linkage function and set the linkage to your choice. You could also modify the vcpkg linkage variable in a `environment-overrides.cmake` file that you would place in the port-overlay folder (along with a copy of all the other contents of the port). If having to put both the override and the copy of the port in the overlay seems undesirable to you (you want to use mainline vcpkg but just override some default settings) we can think about a mechanism to just pull in the overrides file. Please note environment-overrides is still experimental and the magic filename may change.

The difficulty is an error, the static option in the triplets should only refer to the /MD/MT question. The port can decide whether to produce static, dll, or both for a package. We will survive if it only produces one, whichever it chooses. After all we will alway use a lib file to link to (stub or full code), whichever choice is in the package. However, the delivery of the dll to the outputs folder for "f5" for dlls is a nice touch I would be loath to lose.

**Comment by Neumann-A** [comment]
x64-windows-static -> static crt; static libraries
x64-windows-static-md -> dynamic crt; static libraries
x64-windows -> dyn crt; dyn libs if possible. 

@JackBoosY close?

**Comment by JackBoosY** [comment]
Yes, now we have official triplet `x64-windows-static-md`. Please use option `--triplet=x64-windows-static-md` in the install command.
