### ISSUE TITLE
[PkgConf] Build failure on x64-windows due to extraction issue

### ISSUE THREAD

**Issue by somearchive** [microsoft/vcpkg#42771]
**Describe the bug**  
The issue appeared spontaneously without any prior changes. Running `git pull` and `vcpkg update` did not resolve the problem.
Two issues occur with `vcpkg`:  
1. During `bootstrap-vcpkg.bat`, an error related to the `-Raw` parameter in the PowerShell `Get-Content` command appears, and the download of `vcpkg.exe` fails with an HTTP 404 error.  
2. During a build, `vcpkg` fails to install dependencies, specifically the `pkgconf` package, with the error `Could not unwrap top level directory from archive`.  

**Environment**  
- OS: Windows 10 22H2  
- Compiler: MSVC 19.36.32822  

**To Reproduce**  
1. Download the latest version of `vcpkg` from the repository.  
2. Run `bootstrap-vcpkg.bat` in a terminal.  
3. Observe the errors during the bootstrap process.  
4. Use `vcpkg` to install dependencies, e.g., run `vcpkg install libsodium:x64-windows-static`.  
5. Observe the errors during the build process.  

**Expected behavior**  
1. The bootstrap process should complete successfully, downloading the necessary files and preparing the `vcpkg` environment.  
2. The build process should install all required dependencies without errors.  

**Failure logs**  
*Bootstrap failure logs:*  
```powershell
D:\SOFTWARE [portable]\vcpkg>"D:\SOFTWARE [portable]\vcpkg\bootstrap-vcpkg.bat"
Get-Content : A parameter cannot be found that matches parameter name 'Raw'.
At D:\SOFTWARE [portable]\vcpkg\scripts\bootstrap.ps1:49 char:87
+ ... StringData (Get-Content "$PSScriptRoot\vcpkg-tool-metadata.txt" -Raw)
+                                                                     ~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-Content], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Downloading https://github.com/microsoft/vcpkg-tool/releases/download//vcpkg.exe -> \vcpkg.exe...Download failed, server returned HTTP status: 404
```
**Build failure logs**  
```powershell
1>CMake Error at scripts/cmake/vcpkg_extract_source_archive.cmake:137 (message):
1>  Could not unwrap top level directory from archive.  Pass
1>  NO_REMOVE_ONE_LEVEL to disable this.
1>Call Stack (most recent call first):
1>  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:8 (vcpkg_extract_source_archive)
1>  scripts/cmake/vcpkg_from_github.cmake:113 (vcpkg_extract_source_archive_ex)
1>  ports/pkgconf/portfile.cmake:1 (vcpkg_from_github)
1>  scripts/ports.cmake:196 (include)

1>EXEC : error : building pkgconf:x64-windows failed with: BUILD_FAILED
1>Please ensure you're using the latest port files with git pull and vcpkg update.
1>Then check for known issues at:
1>  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+pkgconf
1>You can submit a new issue at:
1>  https://github.com/microsoft/vcpkg/issues/new?title=[pkgconf]+Build+error+on+x64-windows

**Comment by dg0yt** [comment]
> ~~~
> D:\SOFTWARE [portable]

Until properly fixed, you may try to a more traditional path, without ` `, `[`, `]`, `+`, `*`, `?`, `;`, `:` etc.

**Comment by somearchive** [comment]
блять...
