### ISSUE TITLE
[LLVM] misconfiguration

### ISSUE THREAD

**Issue by MathiasMagnus** [microsoft/vcpkg#4277]
When using the `llvm-config.exe`, it reports bogus directories, hence projects depending on LLVM will fail to configure. I'm trying to build the [POCL](https://github.com/pocl/pocl) library using the LLVM Vcpkg, but the tools report directories like:

```PowerShell
PS C:\Users\mnagy> .\Source\Repos\vcpkg\installed\x64-windows\tools\llvm\llvm-config.exe --includedir
C:\Users\mnagy\Source\Repos\vcpkg\installed\x64-windows\tools/include
PS C:\Users\mnagy> .\Source\Repos\vcpkg\installed\x64-windows\tools\llvm\llvm-config.exe --libdir
C:\Users\mnagy\Source\Repos\vcpkg\installed\x64-windows\tools\lib
PS C:\Users\mnagy> .\Source\Repos\vcpkg\installed\x64-windows\tools\llvm\llvm-config.exe --bindir
C:\Users\mnagy\Source\Repos\vcpkg\installed\x64-windows\tools\tools\llvm
```
None of these directories exist.

**Comment by MathiasMagnus** [comment]
I started using the LLVM package to build POCL and I have identified 3 issues around the package:

1. Several libraries are not installed. If you check the staging dir and the install dir, a handful of libraries are missing.
2. Several executables are missing, most importantly `clang++.exe`, but several others are missing as well, once again staging dir and the install dir differ. (This is strange, because a `file(GLOB)` picks up the executables.)
3. The clang compiler installed under tools cannot find its own internal headers. This must be due to misconfiguration. If I try to compile a simple program that include `opencl-c.h` on a Linux node and the Vcpkg installed version I get:

**Linux**
```
mnagy@MATTY-GL702ZC:~$ clang-7 -c /mnt/c/Users/mnagy/Source/FileIO/11.c -std=c11 -o 11.o
In file included from /mnt/c/Users/mnagy/Source/FileIO/11.c:11:
/usr/lib/llvm-7/lib/clang/7.0.1/include/opencl-c.h:9306:20: error: redeclaration of 'abs' must not have the 'overloadable' attribute
uint __ovld __cnfn abs(int x);
```
**Windows with Vcpkg**
```
PS C:\Users\mnagy\CMakeBuilds\pocl> C:\Users\mnagy\Source\Repos\vcpkg\installed\x64-windows\tools\llvm\clang.exe -c C:\Users\mnagy\Source\FileIO\11.c -std=c11 -o .\11.o
C:\Users\mnagy\Source\FileIO\11.c:11:10: fatal error: 'opencl-c.h' file not found
#include <opencl-c.h>
         ^~~~~~~~~~~~
```
Note how Linux argues about a compilation issue that arises in the private header (forgive me for not getting around to finding the correct flags, POCL invokes it properly), while Vcpkg with Windows argues about the file not existing at all, even though its under `installed/<triplet>/lib/clang/7.0.0/include`.

**Comment by JackBoosY** [comment]
I think the existing configurations of llvm are mess, we need to rearrange and fix all the configurations.
