### ISSUE TITLE
Shasum Hardcoding 

### ISSUE THREAD

**Issue by atkawa7** [microsoft/vcpkg#4278]
Some linux systems i.e Centos/Fedora/RHEL do not have shasum. 
https://github.com/Microsoft/vcpkg/blob/master/toolsrc/src/vcpkg/base/hash.cpp#L166-L212

**Comment by averrin** [comment]
Same as arch. Any workaround?

**Comment by averrin** [comment]
So, you can create `shasum` script in your $PATH with this content:
```bash
#!/bin/bash
sha1sum $3
```

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen this issue.
