### ISSUE TITLE
No failure logs attachement available

### ISSUE THREAD

**Issue by michael-doubez** [microsoft/vcpkg#42798]
**Describe the bug**
Trying to contribute an update of libsmb2 port, builds are failing for android but I cannot access error logs in attachement.
See https://dev.azure.com/vcpkg/public/_build/results?buildId=110599&view=ms.vss-test-web.build-test-results-tab&runId=285585&resultId=100000&paneView=attachments

![Image](https://github.com/user-attachments/assets/43e23de0-3035-4962-a059-89cdbab4dab2)

I need to know if it is an issue in the port or in the android build of the library.

**Environment**
- OS: android

**To Reproduce**

Did not try to reproduce

**Expected behavior**

Be able to access failure logs.

**Failure logs**

NONE

**Additional context**

N/A

**Comment by dg0yt** [comment]
The logs are it the CI run's artifacts. 
https://dev.azure.com/vcpkg/public/_build/results?buildId=110599&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by michael-doubez** [comment]
Thank you, I had found the page but didn't notice the dots on the right hand side.

**Comment by dg0yt** [comment]
Yeah, everybody earns extra :star: :star: :star: :star: :star: for spotting that detail.
