### ISSUE TITLE
[nng] update to 1.9.0

### ISSUE THREAD

**Issue by uusdnfdsfhnttyh** [microsoft/vcpkg#42792]
### Library name

nng

### New version number

1.9.0

### Other information that may be useful (release notes, etc...)

new feature updated
https://github.com/nanomsg/nng

**Comment by MonicaLiu0311** [comment]
The latest nng version in vcpkg is already [1.9.0](https://github.com/microsoft/vcpkg/blob/master/ports/nng/vcpkg.json).

Fixed by https://github.com/microsoft/vcpkg/pull/41524.
