### ISSUE TITLE
[aom] Build error

### ISSUE THREAD

**Issue by stardeep925** [microsoft/vcpkg#42829]
root@C20241213197532:~/vcpkg# ./vcpkg install aom
Computing installation plan...
The following packages will be built and installed:
    aom[core]:x64-linux -> 3.5.0#1
Detecting compiler hash for triplet x64-linux...
Restored 0 package(s) from /root/.cache/vcpkg/archives in 7.61 us. Use --debug to see more details.
Installing 1/1 aom:x64-linux...
Building aom[core]:x64-linux...
-- Fetching https://github.com/mozilla/aom.git 9a83c6a5a55c176adbce740e47d3512edfc9ae71...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/git fetch https://github.com/mozilla/aom.git 9a83c6a5a55c176adbce740e47d3512edfc9ae71 --depth 1 -n
    Working Directory: /root/vcpkg/downloads/git-tmp
    Error code: 128
    See logs for more information:
      /root/vcpkg/buildtrees/aom/git-fetch-x64-linux-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_git.cmake:86 (vcpkg_execute_required_process)
  ports/aom/portfile.cmake:11 (vcpkg_from_git)
  scripts/ports.cmake:147 (include)

error: building aom:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+aom
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[aom]+Build+error&body=Copy+issue+body+from+%2Froot%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by FrankXie05** [comment]
> Please see [#30604](https://github.com/microsoft/vcpkg/issues/30604) for how to properly report a build failure.
