### ISSUE TITLE
Provide a way to test the port

### ISSUE THREAD

**Issue by xiaozhuai** [microsoft/vcpkg#42821]
Currently, vcpkg's CI is limited to testing whether the port can be successfully built.
This is obviously not enough as there are many issues that are not tested.
1. cmake config file
2. pc file
3. link problem
4. etc...

Therefore I think it is necessary to provide a way to test the port in the user project.
And often the contributors of the port know better how to test the port.

The simplest and most effective way is to create a PORT named `${PORT}-test`.
Here I submit a PR, which does this. #42820
You will find that all tests with static triplets on Windows fail.
When you dig deeper, you will find that only debug builds fail.

Without using the `qt5-test` port, you may not be able to detect this problem, and also it is difficult to reproduce this problem.
This issue was reported in #38930, this is a good example.

So the `xxx-test` port is not only used for testing purposes, when people submit issues, it can also be used this way to reproduce the problem.

This is just a demonstration to inspire others. I hope members can come up with a standardized testing method.

**Comment by xiaozhuai** [comment]
@BillyONeal @JavierMatosD @dg0yt

**Comment by dg0yt** [comment]
Well, at the moment I add approximately one test port per week. In `scripts/test_ports`. 
https://github.com/microsoft/vcpkg/commits/master/scripts/test_ports

**Comment by xiaozhuai** [comment]
@dg0yt Thanks for the reminder, this is exactly what I need.
