### ISSUE TITLE
[aom] Build error on x64-linux

### ISSUE THREAD

**Issue by xengine-qyt** [microsoft/vcpkg#42870]
### Operating system

rockylinux 9.5

### Compiler

gcc 11.5.0 20240719 (Red Hat 11.5.0-2) (GCC) 

### Steps to reproduce the behavior

```Shell
./vcpkg install ffmpeg[all-nonfree,iconv,drawtext,fontconfig,amf,aom,ass,fdk-aac,ffmpeg,ffplay,ffprobe,nvcodec,opengl,opencl,qsv,x264,x265,webp]:x64-linux
```

### Failure logs

-- Fetching https://aomedia.googlesource.com/aom d6f30ae474dd6c358f26de0a0fc26a0d7340a84c...
gCMake Error at scripts/cmake/vcpkg_from_git.cmake:155 (message):
  After fetching d6f30ae474dd6c358f26de0a0fc26a0d7340a84c, the requested REF
  (d6f30ae474dd6c358f26de0a0fc26a0d7340a84c) does not match its commit SHA
  returned by git rev-parse ([proxychains] DLL init: proxychains-ng 4.17

  d6f30ae474dd6c358f26de0a0fc26a0d7340a84c).  This is usually caused by
  trying to set REF to a named branch or tag rather than a commit SHA.  REF
  must be a commit SHA.  If the git server does not advertise commit SHAs
  (uploadpack.allowReachableSHA1InWant is false), you can set FETCH_REF to a
  named branch in which the desired commit SHA is in the history.  For
  example, you may be able to fix this error by changing "REF
  d6f30ae474dd6c358f26de0a0fc26a0d7340a84c" to "REF a-commit-sha FETCH_REF
  d6f30ae474dd6c358f26de0a0fc26a0d7340a84c".

      [Expected : ( d6f30ae474dd6c358f26de0a0fc26a0d7340a84c )])
      [  Actual : ( [proxychains] DLL init: proxychains-ng 4.17

  d6f30ae474dd6c358f26de0a0fc26a0d7340a84c )]
Call Stack (most recent call first):
  ports/aom/portfile.cmake:1 (vcpkg_from_git)
  scripts/ports.cmake:196 (include)

error: building aom:x64-linux failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle aom:x64-linux: 1.7 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+aom
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[aom]+Build+error+on+x64-linux&body=Copy+issue+body+from+%2Fhome%2Frockylinux%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by WangWeiLin-MV** [comment]
Using the latest version of vcpkg for local installation does not reproduce the issue.

Please clean `${VCPKG_DOWNLOADS}/temp` and try with latest vcpkg.

**Comment by xengine-qyt** [comment]
OK,it's last version. may be proxy problem
