### ISSUE TITLE
[sfml] update to 3.0.0

### ISSUE THREAD

**Issue by pascal754** [microsoft/vcpkg#42907]
### Library name

SFML

### New version number

3.0.0

### Other information that may be useful (release notes, etc...)

[SFML 3.0.0 Release](https://github.com/SFML/SFML/releases/tag/3.0.0)

According to the Release Notes:
> SFML 3 is a new major version and as such breaking changes have been made.
> To ease the pain of migration, we've written an extensive migration guide.

I have a couple of questions:

How about imgui-sfml?

Is it necessary to add major version number, for example, sfml3?

**Comment by WangWeiLin-MV** [comment]
> Is it necessary to add major version number, for example, sfml3?

We do not recommend maintaining multiple versions of the same upstream.

> How about imgui-sfml?

Upstream port should be installable simultaneously with downstream port. https://learn.microsoft.com/en-us/vcpkg/contributing/maintainer-guide#ports-in-the-current-baseline-must-be-installable-simultaneously

**Comment by eXpl0it3r** [comment]
Duplicates #43000
