### ISSUE TITLE
Is vckpkg a library manager or package manager?

### ISSUE THREAD

**Issue by congzhangzh** [microsoft/vcpkg#4292]
Hi folks,

As vcpkg mark as a package manager, it's more like a library manager but not a package manager,  it lacks the ability to install ready to use the package in it,  it's just a library repo.

What's the problem, If it's a library manager, and a package depends on it, how to distribute it,  how to mix third-party library and package self content?

No place, it's not os level mix dir, it's not the vckpkg dir(it's not designed for this), if the user level package to it, it will need:
1. when compiler, add the  header dir to search list
2. when link, add the lib dir to search list
3. when run, add bin dir path to PATH(windows), or add lib dir to LD_LIBRARY_PATH(linux）
4. when distribution, pack all the runtime lib with package self? 

Is this be expected?

https://github.com/ContinuumIO/anaconda-issues/issues/440 

Tks,
Cong

**Comment by LarryIII** [comment]
VCPKG is C++ Library Manager for Windows, Linux, and MacOS. If there are some depend libs for one port, VCPKG will make the 'Build-Depends' list in control for it. Such as https://github.com/microsoft/vcpkg/blob/master/ports/arrow/CONTROL
When a port was installed, it will post headers lib/dll into vcpkg\installed\triplets\.. folder. I think it is you expected path in windows.

**Comment by NancyLi1013** [comment]
Hi @congzhangzh, thanks for posting this issue. Hope the above answer from Larry can help you. Please feel free to reopen it if this is still a problem for you.
