### ISSUE TITLE
Japanese given as an immediate value on Visual C++ 2022 editor is not handled well

### ISSUE THREAD

**Issue by tensor5375** [microsoft/vcpkg#42937]
**Describe the bug**
　In the Visual C++ editor, when Japanese is entered as an immediate value in UTF-8, it is determined to contain invalid characters. This does not happen with boost::property_tree::ptree, even if the same string is handled, so it seems to be a nlohmann-json specific bug.

**Environment**
- OS: Windows 11 64bit
- Compiler: Visual Studio 2022(C++)
- using vcpkg
- nlohamnn-json 3.11.3

**To Reproduce**
Simply type in some Japanese words in the view, including symbols, etc., and you will probably be able to confirm the kanji.

**Expected behavior**
invalid characters in string error

**Comment by LilyWangLL** [comment]
Thanks for posting this issue, does this issue occur when using English as the input language? Could you provide a screenshot or error log of the error message?

**Comment by tensor5375** [comment]
I may have been mistaken. Please delete it.
