### ISSUE TITLE
[gmp] build failure

### ISSUE THREAD

**Issue by rjindael** [microsoft/vcpkg#42957]
### Operating system

Windows 11 ARM64

### Compiler

Clang (MSVC ABI) on Windows 11 ARM 64 

### Steps to reproduce the behavior

```Shell
vcpkg install gmp
```

### Failure logs

[-arm64-windows-dbg-err.log](https://github.com/user-attachments/files/18257605/-arm64-windows-dbg-err.log)
[-arm64-windows-dbg-out.log](https://github.com/user-attachments/files/18257606/-arm64-windows-dbg-out.log)

**Comment by rjindael** [comment]
UPDATE: Works fine, was using old version

**Comment by dg0yt** [comment]
FTR (some) gmp cross builds are broken due to #39050. Tentative fix as part of #42954.
