### ISSUE TITLE
Please add Coin3D and its co-libraries: SoQT, ...

### ISSUE THREAD

**Issue by moellney** [microsoft/vcpkg#4295]
From it's website: https://bitbucket.org/Coin3D/coin/wiki/Home

Coin3D is a high-level, retained-mode toolkit for effective 3D graphics development. It is API compatible with Open Inventor 2.1.

Coin3D is Free Software, published under the BSD 3-clause license. 

The libraries found on this page support Windows, Linux and MacOS.

I use this for over 10 years now starting with the propritary version that was moved to public domain a view years ago.

They recently added cmake support, so it migh integrate well into vcpkg.

**Comment by NancyLi1013** [comment]
Hi @moellney 

Thanks for posting this request.

Coin3D libraries `simage`, `Coin`, and `SoQt `have been added to vcpkg, Please try to update vcpkg and use these ports.
