### ISSUE TITLE
Libtorrent BUILD_FAILED for version >1.1.7 (1.1.8 & 1.1.9) [Solution Found]

### ISSUE THREAD

**Issue by YenForYang** [Microsoft/vcpkg#4296]
I've figured out that there is *at least 1* new dependency for `libtorrent` v1.1.9: `boost-scope-exit`, (there was an error involving `scope_exit.hpp` being missing).

I got past some errors relating to boost after installing the entire `boost` package.

With `PREFER_NINJA` *disabled*, here is the log:

[install-x86-windows-dbg-out_msbuild1_1_9.log](https://github.com/Microsoft/vcpkg/files/2386932/install-x86-windows-dbg-out_msbuild1_1_9.log)

*Note that the failures have nothing to do with the SHA512 hash.*

*After installing the **entire** boost distro,* (i.e. `vcpkg install boost`) I also attempted to build:
  - **v1.1.7** libtorrent

    ```
    95479ff0cbce299edccaaeb435c31b07c05f45e319f3480645d2ae45a9bdc01866edb1329426c6835a7c0cba2d6347254f5f023009ff78405b813c131b78addb
    ```

    - **SUCCESS** with PREFER_NINJA (disabling PREFER_NINJA is *untested*)
      - [config-x86-windows-out.log](https://github.com/Microsoft/vcpkg/files/2386950/config-x86-windows-out.log)
      - [install-x86-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2386951/install-x86-windows-dbg-out.log)
      - [install-x86-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/2386952/install-x86-windows-rel-out.log)
      - [patch-x86-windows-0-err.log](https://github.com/Microsoft/vcpkg/files/2386953/patch-x86-windows-0-err.log)
      - [patch-x86-windows-1-err.log](https://github.com/Microsoft/vcpkg/files/2386954/patch-x86-windows-1-err.log)

 - **v1.1.8** libtorrent

    ```
    0db79b60093fc771d3fb0a2df7d420ae874da0e5c0968e4cc28052c999ed259f339d4e8b271923a0dc71ec1433d50ad5b680d873ea3dbfa17e663e265c02975b
    ```

    -  Output in console:

        ```shell
        The following packages will be built and installed:
            libtorrent[core]:x86-windows
        Starting package 1/1: libtorrent:x86-windows
        Building package libtorrent[core]:x86-windows...
        -- Downloading https://github.com/arvidn/libtorrent/archive/libtorrent-1_1_8.tar.gz...
        -- Extracting source C:/Github/vcpkg/downloads/arvidn-libtorrent-libtorrent-1_1_8.tar.gz
        -- Using source at C:/Github/vcpkg/buildtrees/libtorrent/src/rent-1_1_8-9ceb8a466d
        -- Applying patch C:/Github/vcpkg/ports/libtorrent/add-datetime-to-boost-libs.patch
        -- Applying patch failed. This is expected if this patch was previously applied.
        -- Applying patch C:/Github/vcpkg/ports/libtorrent/boost-167.patch
        -- Applying patch failed. This is expected if this patch was previously applied.
        -- Configuring x86-windows
        -- Building x86-windows-dbg
        CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
            Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
            Working Directory: C:/Github/vcpkg/buildtrees/libtorrent/x86-windows-dbg
            See logs for more information:
              C:\Github\vcpkg\buildtrees\libtorrent\install-x86-windows-dbg-out.log

        Call Stack (most recent call first):
          scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
          ports/libtorrent/portfile.cmake:35 (vcpkg_install_cmake)
          scripts/ports.cmake:71 (include)


        Error: Building package libtorrent:x86-windows failed with: BUILD_FAILED
        Please ensure you're using the latest portfiles with `.\vcpkg update`, then
        submit an issue at https://github.com/Microsoft/vcpkg/issues including:
          Package: libtorrent:x86-windows
          Vcpkg version: 0.0.113-nohash
        ```
    - Log file (`PREFER_NINJA` is **enabled**): [install-x86-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2386979/install-x86-windows-dbg-out.log)
    - Log file (*without* `PREFER_NINJA`): [install-x86-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2386990/install-x86-windows-dbg-out.log)

**Comment by YenForYang** [comment]
Ok I figured it out (working, at least): 

For newer versions, boost >= 1.67 is auto detected (I think), and the CMakeLists.txt file changed, so the old patch no longer works.

I used something like this as the add-datetime patch:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 0c7d9c68d..83e1ae4b0 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -264,7 +264,7 @@ if (NOT cxx_std_11 IN_LIST CMAKE_CXX_COMPILE_FEATURES)
 endif()
 # Boost
 if(NOT DEFINED Boost_INCLUDE_DIR OR NOT DEFINED Boost_LIBRARIES)
-	find_package(Boost REQUIRED COMPONENTS ${required_boost_components})
+	find_package(Boost REQUIRED COMPONENTS date_time ${required_boost_components})
 endif()
 # now test the second requirement:
 if (Boost_VERSION VERSION_GREATER_EQUAL 106600)
diff --git a/simulation/libsimulator b/simulation/libsimulator
index 8209dcf79..e4fb5e171 160000
--- a/simulation/libsimulator
+++ b/simulation/libsimulator
@@ -1 +1 @@
-Subproject commit 8209dcf79b7ca8769165c240d8a6962b8574dd27
+Subproject commit e4fb5e171a6ed885e7de3192153ba77835d23dee
```

**Comment by LarryIII** [comment]
Thanks for your feedback, this issue should be fixed in https://github.com/Microsoft/vcpkg/commit/0e759709ddc7dbad0b881f9f068f1b04b2092773 with add-datetime-to-boost-libs.patch. Please re-open a issue if it is still an problem for you!
