### ISSUE TITLE
vcpkg unable to handle CUDA language

### ISSUE THREAD

**Issue by ruanjiandong** [Microsoft/vcpkg#4297]
vcpkg currently white list "CUDA_PATH" environment variable. While this is sufficient for finding CUDA package, it doesn't work when CUDA is used as a language, for example,
    cmake_minimum_required(VERSION 3.8.0)
    project(librealsense2 LANGUAGES CXX C CUDA)

For CUDA language to work, version specific CUDA_PATH_xxxxx environment variables must also be white listed due to the way in which CUDA is integrated with MSBUILD (see C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140\BuildCustomizations)

One option is for vcpkg to pass to cmake all the environment variables with CUDA_PATH prefix.

**Comment by cenit** [comment]
same problem for me @ras0219-msft @vicroms 

Without this capability, `enable_language(CUDA)` does not work and `darknet` installed through vcpkg is not GPU-enabled...
In future also many more ports will move away from `find_package(CUDA)` to the newer `enable_language(CUDA)`, so this is a very important point. Is there any work in progress or it is waiting for a community contribution?

**Comment by cenit** [comment]
side note: i tried adding
```
            L"CUDA_PATH",
            L"CUDA_PATH_V10_0",
            L"CUDA_PATH_V10_1",
            L"CUDA_TOOLKIT_ROOT_DIR",
```
in `toolsrc\src\vcpkg\base\system.cpp`. While env variables are now passed on, they are not enough to make `enable_language(CUDA)` happy.
Of course, the same build outside vcpkg environment finds CUDA without any problem

**Comment by cenit** [comment]
ok forget the last message: I was using Ninja, which is unsupported for CUDA in Windows.
With Visual Studio generators now it's ok
Opening a PR :)
