### ISSUE TITLE
[msquic] Compile port static as upstream. Apply port patches to upstream.

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#43017]
**Describe the bug**

Compile port static as upstream:
https://github.com/microsoft/vcpkg/pull/42788#issuecomment-2556525242

> The port only support dynamic library linkage ATM. Upstream supports both, but doesn't prvovide exported config for the static lib

Apply port patches to upstream:
https://github.com/microsoft/vcpkg/pull/42788#issuecomment-2562961056

> By only applying these changes on top via patches, we have less confidence that things are all correct, which can create security and quality issues. So, we should strive for getting changes in the upstream projects instead of via patch files

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This comment from the manager of `msquic` https://github.com/microsoft/vcpkg/pull/42788#issuecomment-2562961056 has already addressed this issue.

**Comment by talregev** [comment]
@LilyWangLL 
Do you want me to close this issue?

**Comment by LilyWangLL** [comment]
> [@LilyWangLL](https://github.com/LilyWangLL) Do you want me to close this issue?

Yes, thank you.
