### ISSUE TITLE
build failure with custom triplet (`/fsanitize=address` enabled)

### ISSUE THREAD

**Issue by BH2WFR** [microsoft/vcpkg#43026]
### Operating system

Windows 11 24H2

### Compiler

MSVC (VS2022)

### Steps to reproduce the behavior

**curtom triplet file `x64-windows-asan.cmake`:** (location: `vcpkg/triplet`, same as built-in triplets`)
```cmake
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_BUILD_TYPE "Debug")
set(VCPKG_C_FLAGS "/fsanitize=address")
set(VCPKG_CXX_FLAGS "/fsanitize=address")
set(VCPKG_LINKER_FLAGS "/INCREMENTAL:NO")
```

**then command:**
`vcpkg install fmt:x64-windows-asan`
`vcpkg install gflags:x64-windows-asan`

**compiles nothing, and no any headers or libraries exported.**

### Failure logs

![Image](https://github.com/user-attachments/assets/978267c9-21de-4b86-8c05-bacbaf55e81a)

package files: **with nothing exported** (no lib, no headers)
![Image](https://github.com/user-attachments/assets/1e9bafdc-37aa-472f-bb9d-a3ea686df32b)
![Image](https://github.com/user-attachments/assets/334fa6f5-995c-4e9c-af40-9d1c2051ed2d)

### Additional context

It works well with built-in triplets `x64-windows`, `x64-windows-static` ` x64-windows-static-md`.

**Comment by dg0yt** [comment]
> set(VCPKG_BUILD_TYPE "Debug")

This is officially unsupported.

You may configure "Release" to do whatever you want. YMMV.
