### ISSUE TITLE
pcre:x64-windows not copying dll into project

### ISSUE THREAD

**Issue by simon-p-r** [Microsoft/vcpkg#4304]
Hi

I am trying to use pcre in a cmake project however it doesn't copy the pcre.dll across post build, the pcre:x64-windows-static works fine.  I can make a PR to fix if I know how to change port file.

Thanks

**Comment by JackBoosY** [comment]
Hi @simon-p-r , thanks for reporting this issue!
This issue may be fixed in the recent PR. So plz update vcpkg and rebuild pcre.
Thanks.
