### ISSUE TITLE
can not install folly package -- I see folly only support x64

### ISSUE THREAD

**Issue by GenKnight** [Microsoft/vcpkg#4313]
![image](https://user-images.githubusercontent.com/12382259/45724090-18a36100-bbe7-11e8-97e3-9a18220339e0.png)

**Comment by Voskrese** [comment]
???
folly windows only x64
port only windows

**Comment by degski** [comment]
@GenKnight @Voskrese From this [thread](https://groups.google.com/forum/?fromgroups#!topic/facebook-folly/gmBlqfliUNE) one can surmise that 32-bit is not supported and confirmed to not being tested, so I think we can safely conclude: "not supported, does not work".

**Comment by Voskrese** [comment]
@degski 
https://github.com/facebook/folly/blob/master/CMakeLists.txt

```
    message(
      FATAL_ERROR
      "This build script only supports building Folly on 64-bit Windows with "
      "Visual Studio 2015 or Visual Studio 2017. "
      "MSVC version '${MSVC_VERSION}' is not supported."
)
```

**Comment by degski** [comment]
@Voskrese Well, there you have it.
@GenKnight Issue can be closed.

**Comment by GenKnight** [comment]
thanks for you help

**Comment by GenKnight** [comment]
@Voskrese @degski Thanks for your help
