### ISSUE TITLE
[Request] Prometheus-cpp

### ISSUE THREAD

**Issue by furiousbanana** [Microsoft/vcpkg#4315]
https://github.com/jupp0r/prometheus-cpp

**Comment by PhoebeHui** [comment]
Hi furiousbanana,

VCPKG has support Prometheus-cpp. you can have a try.

PS F:\vcpkg\src> .\vcpkg install prometheus-cpp
The following packages will be built and installed:
  * civetweb[core]:x86-windows
    prometheus-cpp[compression,core,pull]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: civetweb:x86-windows
Building package civetweb[core]:x86-windows...
-- Note: civetweb only supports static library linkage. Building static library.
-- Downloading https://github.com/civetweb/civetweb/archive/v1.11.tar.gz...
-- Extracting source F:/VCPKG/src/downloads/civetweb-civetweb-v1.11.tar.gz
-- Using source at F:/VCPKG/src/buildtrees/civetweb/src/v1.11-98b39112d5
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package civetweb[core]:x86-windows... done
Installing package civetweb[core]:x86-windows...
Installing package civetweb[core]:x86-windows... done
Elapsed time for package civetweb:x86-windows: 37.63 s
Starting package 2/2: prometheus-cpp:x86-windows
Building package prometheus-cpp[compression,core,pull]:x86-windows...
-- Note: prometheus-cpp only supports static library linkage. Building static library.
-- Downloading https://github.com/jupp0r/prometheus-cpp/archive/v0.6.0.tar.gz...
-- Extracting source F:/VCPKG/src/downloads/jupp0r-prometheus-cpp-v0.6.0.tar.gz
-- Using source at F:/VCPKG/src/buildtrees/prometheus-cpp/src/v0.6.0-be7c682587
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package prometheus-cpp[compression,core,pull]:x86-windows... done
Installing package prometheus-cpp[compression,core,pull]:x86-windows...
Installing package prometheus-cpp[compression,core,pull]:x86-windows... done
Elapsed time for package prometheus-cpp:x86-windows: 25.6 s

Total elapsed time: 1.054 min

The package prometheus-cpp:x86-windows provides CMake targets:

    find_package(prometheus-cpp CONFIG REQUIRED)
    target_link_libraries(main PRIVATE prometheus-cpp::core prometheus-cpp::pull)

Thanks,
Phoebe
