### ISSUE TITLE
vcpkg_fixup_cmake_targets broken for executable targets on Linux/Mac

### ISSUE THREAD

**Issue by SalvoVirga** [microsoft/vcpkg#4326]
### Problem:
As the documentation of vcpkg_fixup_cmake_targets states, it is used to correct the reference to executable targets in the generated cmake target files:

`#  Transform all references matching /bin/*.exe to /tools/<port>/*.exe`

This doesn't currently work on non-Windows environment, as they executables have no ".exe" extension. So when building an executable target on Linux/Mac the CMake target reference is broken.

### Possible Solution:
in vcpkg_fixup_cmake_targets.cmake the instance to the regex 
`"\\\${_IMPORT_PREFIX}/bin/([^ \"]+\\.exe)"`     
should be modified to       
` "\\\${_IMPORT_PREFIX}/bin/([^ \"]+)"`.      

That way both references ending with ".exe" and not would be captured.

I have a PR ready in case.

### Info:
Reproduced on Mac OSX 10.13.6 building 'flatbuffers' and using the target "flatbuffers::flatc" in a custom CMake (which is an executable generated when building flatbuffers).

**CMake Error:**
```
The imported target "flatbuffers::flatc" references the file
 "/Users/<User>/vcpkg/installed/x64-osx/bin/flatc" 
but this file does not exist.
```
The executable `flatc` is in fact (correctly) in `/Users/<User>/vcpkg/installed/x64-osx/tools/flatbuffers` but the CMake file in `/Users/<User>/vcpkg/installed/x64-osx/share/flatbuffers` refers wrongly to:
```
list(APPEND _IMPORT_CHECK_TARGETS flatbuffers::flatc )
list(APPEND _IMPORT_CHECK_FILES_FOR_flatbuffers::flatc "${_IMPORT_PREFIX}/bin/flatc" )
```

**Comment by JackBoosY** [comment]
Fixed.
