### ISSUE TITLE
Error:Building package libuuid:x86-windows failed  with: BUILD_FAILED

### ISSUE THREAD

**Issue by GenKnight** [Microsoft/vcpkg#4331]
![pic](https://user-images.githubusercontent.com/12382259/45926912-e7b38b00-bf5c-11e8-968d-9321ab3f8627.PNG)

**Comment by JackBoosY** [comment]
Hi @GenKnight , thanks for reporting this issue!
libuuid only supports unix platforms currently. If you need to use uuid in windows, plz use windows API **CoCreateGuid**.
Thanks.
