### ISSUE TITLE
[Qt5-base] Wrong qmldir for debug configuration

### ISSUE THREAD

**Issue by claudiofantacci** [Microsoft/vcpkg#4336]
As reported by @huangqinjin  here https://github.com/Microsoft/vcpkg/pull/3280#issuecomment-423499345, the following line

https://github.com/Microsoft/vcpkg/blob/90e627c7e6312d5ab04060c186e55ac58edaa634/ports/qt5-base/configure_qt.cmake#L39

should be changed in

```cmake
-qmldir ${CURRENT_INSTALLED_DIR}/qml
```

This is a regression error coming from https://github.com/Microsoft/vcpkg/commit/2a94ee4c62ad8b3468ae10fa5c0f02dc92e0c1be.
As a matter of the fact, it seems that the error did not trigger any big problem since no issues seems to be connected to this other then https://github.com/Microsoft/vcpkg/issues/2857.

I'm going to edit [`configure_qt.cmake`](https://github.com/Microsoft/vcpkg/blob/master/ports/qt5-base/configure_qt.cmake) right now, using GitHub GUI and by opening an associated PR.

**Comment by ras0219-msft** [comment]
This _should_ be fixed by the change for #2857; please let us know in that thread if there's still an issue!
