### ISSUE TITLE
Visual Studio 15.8.5 Qt C++ Project can't see installed libs but a console project can.

### ISSUE THREAD

**Issue by willkara** [microsoft/vcpkg#4339]
I have **vcpkg** version 0.0.113-nohash

**Visual Studio Community 2017** 15.8.5

**ReSharper** 2018.2.3

I successfully cloned, built and ran the _integrate install_ command. I then installed the libraries and started Visual Studio. 

I have the QT Visual Studio tools installed and tried creating a sample GUI application. Even when I tried the simple sqlite3 sample, it can't find the header file

```
#include "stdafx.h"
#include "Techne.h"
#include <sqlite3.h>      --- Says it can't find sqlite3.h in search paths

Techne::Techne(QWidget *parent)
	: QMainWindow(parent)
{
	ui.setupUi(this);
}

void Techne::on_pushButton_clicked()
{
	ui.lineEdit->setText(sqlite3_libversion());
}


```

Oddly enough, I tried a simple **Windows Console Application** and it worked. Could the QT VS tools somehow be interfering with the included paths?

**Comment by marshfolx** [comment]
you may need to check your project property and see if it is x64.

vcpkg build x86-windows in default as same as a c++ console project in vs, but your default qt version in qt vs tool option may be x64, then your qt project is set to x64 :-).

just switch you qt vs tool option and create a new project.

**Comment by PhoebeHui** [comment]
@willkara, please reopen this issue if it still be a problem for you.
