### ISSUE TITLE
Bundling actual source code, and optionally other other binary artifacts with the package?

### ISSUE THREAD

**Issue by malkia** [microsoft/vcpkg#4340]
Are there any plans, to support bundling of the actual source code built, and optionally compiled .obj, .lib files in some form (one, or separate packages)?

It came to my attention, that when I'm bundling wxWidgets for folks to use at the company, later I need to re-provide the source code somehow.

Just wondering, nothing important. I'm also trying to understand (haven't looked deeply in the toolsrc code), how the random "src/<some-form-of-guid>" is created. Alternatively I can always clean in advance, built, and then pack the first folder from "src".

Thanks! (... maybe I missed something in the docs ...)

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen this issue.
