### ISSUE TITLE
Building a tool for a cross compile

### ISSUE THREAD

**Issue by donny-dont** [microsoft/vcpkg#4348]
I'm wondering what the best way would be for building a repository with a tool and then using that tool for a cross compile scenario.

I'm looking at a CMake port of [ICU](https://github.com/LibCMaker/ICU_CMake_Files) which has cross compile capability. It expects you to build out ICU on your platform and then have those built files available to use. It seems like I could use `vcpkg export` and install as a Nuget package but I'm wondering if there's a better way to accomplish this. I've seen ragel as a dependency on harfbuzz but this is essentially a dependency on itself but with a different triplet.

**Comment by JackBoosY** [comment]
Maybe you need [this example](https://github.com/microsoft/vcpkg/pull/9137/files).
