### ISSUE TITLE
Problem with commit "[vcpkg.cmake] Remove Windows SDK detection. Let cmake detect it

### ISSUE THREAD

**Issue by 0-wiz-0** [Microsoft/vcpkg#4352]
libzip is a cross-platform zip library. I'm one of the authors.
We have no particular Windows knowledge. A user contributed an appveyor setup for it, which worked fine until this commit:
https://github.com/Microsoft/vcpkg/commit/f9d4692749ad68340a07453add49a8ef029fa155#diff-464a170117fa96bf98b2f8d224bf503c
Since then, the UWP builds (for all of arm/arm64/win/win64) of libzip on appveyor (see https://ci.appveyor.com/project/0-wiz-0/libzip/history) are broken, ending with:
````
mkdir build
cd build
cmake -DCMAKE_TOOLCHAIN_FILE=%cd%/../vcpkg/scripts/buildsystems/vcpkg.cmake .. -G "%GENERATOR%" %CMAKE_OPTS%
CMake Error at CMakeLists.txt:8 (PROJECT):
  Visual Studio 15 2017 supports Windows Store '8.0', '8.1' and '10.0', but
  not ''.  Check CMAKE_SYSTEM_VERSION.
-- Configuring incomplete, errors occurred!
See also "C:/projects/libzip/build/CMakeFiles/CMakeOutput.log".
````
(The non-UWP builds still work.)

I'm not saying this needs to be backed out, but I'd appreciate help a lot on how to get the libzip appveyor builds working again. Thanks.

**Comment by Cheney-W** [comment]
@0-wiz-0 Thanks for your feedback. I could install libzip:(x64/x86/arm)-uwp successfully with VS 2017 15.9.11. Please reopen a new issue if it is still a problem for you!

**Comment by 0-wiz-0** [comment]
The solution was to define `CMAKE_SYSTEM_VERSION` manually, see e.g.
https://github.com/nih-at/libzip/commit/a9028c905be296fa4f2b2e82829a4425bbd991f4
