### ISSUE TITLE
vcpkg PCL windows build issues

### ISSUE THREAD

**Issue by Michae1Park** [microsoft/vcpkg#4356]
Hi,

I installed pcl on my windows 10 machine using the command 
```
vcpkg install pcl:x64-windows
```
in the powershell. Once the installation was complete, I typed
```
vcpkg integrate install
```

I installed the latest Visual Studio 2017, created a project and imported 
```
#include <pcl/point_types.h>
#include <pcl/io/ply_io.h>
```
and it built perfectly.

As soon as I include 
```
#include <pcl/registration/icp.h>
```
I get errors below

![image](https://user-images.githubusercontent.com/13462319/46113467-84279880-c1bc-11e8-8f2e-1fdde6c1ba36.png)
![image](https://user-images.githubusercontent.com/13462319/46113473-9275b480-c1bc-11e8-86d3-20906467ab42.png)

I get similar issues when I include
```
#include <pcl/filters/statistical_outlier_removal.h>
```

Any ideas how to fix this problem?

Best Regards,

**Comment by Cheney-W** [comment]
1. About the error C4996, you can fix it by adding the compile option: /D _CRT_SECURE_NO_WARNINGS.
2. About the error C3861, you can fix it by removing the compile option: /permissive-. When using this compile option, VS syntax detection is more strict, and in the dist.h file, pop_t is defined in a conditional control code, when the condition is not true, pop_t is indeed undefined, so when /permissive- is turned on Will report an error.
3. Please close this issue when you resolved this problem.
