### ISSUE TITLE
vcpkg install pcl[cuda]:x64-windows  failed with BUILD_FAILED

### ISSUE THREAD

**Issue by leilaShen** [microsoft/vcpkg#4357]
Hi folks,
when I install pcl[cuda]:x64-windows, I met the BUILD_FAILED error, the screen shot is attached as below:
<img width="955" alt="error" src="https://user-images.githubusercontent.com/22429600/46118990-97c61400-c23b-11e8-9d9c-83eb63575b55.PNG">

and the log file is here:
[install-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2422184/install-x64-windows-dbg-out.log)

Anyone help? Thanks a lot!

**Comment by leilaShen** [comment]
The related section from the log file is 
D:/software/vcpkg/buildtrees/pcl/src/pcl-1.8.1-ea5032be8f/cuda/sample_consensus/src/sac_model.cu(178): here

D:\software\vcpkg\buildtrees\pcl\src\pcl-1.8.1-ea5032be8f\cuda\sample_consensus\include\pcl/cuda/sample_consensus/sac_model.h(356): warning: field of class type without a DLL interface used in a class with a DLL interface
          detected during instantiation of class "pcl::cuda::SampleConsensusModel<Storage> [with Storage=pcl::cuda::Device]" 
D:/software/vcpkg/buildtrees/pcl/src/pcl-1.8.1-ea5032be8f/cuda/sample_consensus/src/sac_model.cu(178): here

D:\software\vcpkg\buildtrees\pcl\src\pcl-1.8.1-ea5032be8f\cuda\sample_consensus\include\pcl/cuda/sample_consensus/sac_model.h(366): warning: field of class type without a DLL interface used in a class with a DLL interface
          detected during instantiation of class "pcl::cuda::SampleConsensusModel<Storage> [with Storage=pcl::cuda::Device]" 
D:/software/vcpkg/buildtrees/pcl/src/pcl-1.8.1-ea5032be8f/cuda/sample_consensus/src/sac_model.cu(178): here

D:\software\vcpkg\buildtrees\pcl\src\pcl-1.8.1-ea5032be8f\cuda\sample_consensus\include\pcl/cuda/sample_consensus/sac_model.h(350): warning: field of class type without a DLL interface used in a class with a DLL interface
          detected during instantiation of class "pcl::cuda::SampleConsensusModel<Storage> [with Storage=pcl::cuda::Host]" 
D:/software/vcpkg/buildtrees/pcl/src/pcl-1.8.1-ea5032be8f/cuda/sample_consensus/src/sac_model.cu(179): here

D:\software\vcpkg\buildtrees\pcl\src\pcl-1.8.1-ea5032be8f\cuda\sample_consensus\include\pcl/cuda/sample_consensus/sac_model.h(351): warning: field of class type without a DLL interface used in a class with a DLL interface
          detected during instantiation of class "pcl::cuda::SampleConsensusModel<Storage> [with Storage=pcl::cuda::Host]" 
D:/software/vcpkg/buildtrees/pcl/src/pcl-1.8.1-ea5032be8f/cuda/sample_consensus/src/sac_model.cu(179): here

D:\software\vcpkg\buildtrees\pcl\src\pcl-1.8.1-ea5032be8f\cuda\sample_consensus\include\pcl/cuda/sample_consensus/sac_model.h(354): warning: field of class type without a DLL interface used in a class with a DLL interface
          detected during instantiation of class "pcl::cuda::SampleConsensusModel<Storage> [with Storage=pcl::cuda::Host]" 
D:/software/vcpkg/buildtrees/pcl/src/pcl-1.8.1-ea5032be8f/cuda/sample_consensus/src/sac_model.cu(179): here

D:\software\vcpkg\buildtrees\pcl\src\pcl-1.8.1-ea5032be8f\cuda\sample_consensus\include\pcl/cuda/sample_consensus/sac_model.h(356): warning: field of class type without a DLL interface used in a class with a DLL interface
          detected during instantiation of class "pcl::cuda::SampleConsensusModel<Storage> [with Storage=pcl::cuda::Host]" 
D:/software/vcpkg/buildtrees/pcl/src/pcl-1.8.1-ea5032be8f/cuda/sample_consensus/src/sac_model.cu(179): here

D:\software\vcpkg\buildtrees\pcl\src\pcl-1.8.1-ea5032be8f\cuda\sample_consensus\include\pcl/cuda/sample_consensus/sac_model.h(366): warning: field of class type without a DLL interface used in a class with a DLL interface
          detected during instantiation of class "pcl::cuda::SampleConsensusModel<Storage> [with Storage=pcl::cuda::Host]" 
D:/software/vcpkg/buildtrees/pcl/src/pcl-1.8.1-ea5032be8f/cuda/sample_consensus/src/sac_model.cu(179): here

sac_model.cu
D:\software\vcpkg\buildtrees\pcl\src\pcl-1.8.1-ea5032be8f\cuda\sample_consensus\include\pcl/cuda/sample_consensus/sac_model.h(350): warning C4251: 'pcl::cuda::SampleConsensusModel<pcl::cuda::Device>::input_': class 'boost::shared_ptr<const pcl::cuda::PointCloudAOS<Storage>>' needs to have dll-interface to be used by clients of class 'pcl::cuda::SampleConsensusModel<pcl::cuda::Device>'
        with
        [
            Storage=pcl::cuda::Device
        ]
D:\software\vcpkg\buildtrees\pcl\src\pcl-1.8.1-ea5032be8f\cuda\common\include\pcl/cuda/point_cloud.h(202): note: see declaration of 'boost::shared_ptr<const pcl::cuda::PointCloudAOS<Storage>>'
        with
        [
            Storage=pcl::cuda::Device
        ]
D:/software/vcpkg/buildtrees/pcl/src/pcl-1.8.1-ea5032be8f/cuda/sample_consensus/src/sac_model.cu(178): note: see reference to class template instantiation 'pcl::cuda::SampleConsensusModel<pcl::cuda::Device>' being compiled
D:\software\vcpkg\buildtrees\pcl\src\pcl-1.8.1-ea5032be8f\cuda\sample_consensus\include\pcl/cuda/sample_consensus/sac_model.h(351): warning C4251: 'pcl::cuda::SampleConsensusModel<pcl::cuda::Device>::normals_': class 'boost::shared_ptr<thrust::device_vector<T,thrust::device_malloc_allocator<T>>>' needs to have dll-interface to be used by clients of class 'pcl::cuda::SampleConsensusModel<pcl::cuda::Device>'
        with
        [
            T=float4
        ]
D:\software\vcpkg\buildtrees\pcl\src\pcl-1.8.1-ea5032be8f\cuda\sample_consensus\include\pcl/cuda/sample_consensus/sac_model.h(336): note: see declaration of 'boost::shared_ptr<thrust::device_vector<T,thrust::device_malloc_allocator<T>>>'
        with
        [
            T=float4
        ]
D:\software\vcpkg\buildtrees\pcl\src\pcl-1.8.1-ea5032be8f\cuda\sample_consensus\include\pcl/cuda/sample_consensus/sac_model.h(354): warning C4251: 'pcl::cuda::SampleConsensusModel<pcl::cuda::Device>::indices_': class 'boost::shared_ptr<thrust::device_vector<T,thrust::device_malloc_allocator<T>>>' needs to have dll-interface to be used by clients of class 'pcl::cuda::SampleConsensusModel<pcl::cuda::Device>'
        with
        [
            T=int
        ]
D:\software\vcpkg\buildtrees\pcl\src\pcl-1.8.1-ea5032be8f\cuda\sample_consensus\include\pcl/cuda/sample_consensus/sac_model.h(99): note: see declaration of 'boost::shared_ptr<thrust::device_vector<T,thrust::device_malloc_allocator<T>>>'
        with
        [
            T=int
        ]
D:\software\vcpkg\buildtrees\pcl\src\pcl-1.8.1-ea5032be8f\cuda\sample_consensus\include\pcl/cuda/sample_consensus/sac_model.h(356): warning C4251: 'pcl::cuda::SampleConsensusModel<pcl::cuda::Device>::indices_stencil_': class 'boost::shared_ptr<thrust::device_vector<T,thrust::device_malloc_allocator<T>>>' needs to have dll-interface to be used by clients of class 'pcl::cuda::SampleConsensusModel<pcl::cuda::Device>'
        with
        [
            T=int
        ]
D:\software\vcpkg\buildtrees\pcl\src\pcl-1.8.1-ea5032be8f\cuda\sample_consensus\include\pcl/cuda/sample_consensus/sac_model.h(99): note: see declaration of 'boost::shared_ptr<thrust::device_vector<T,thrust::device_malloc_allocator<T>>>'
        with
        [
            T=int
        ]
D:\software\vcpkg\buildtrees\pcl\src\pcl-1.8.1-ea5032be8f\cuda\sample_consensus\include\pcl/cuda/sample_consensus/sac_model.h(366): warning C4251: 'pcl::cuda::SampleConsensusModel<pcl::cuda::Device>::rngl_': class 'thrust::random::linear_congruential_engine<unsigned int,48271,0,2147483647>' needs to have dll-interface to be used by clients of class 'pcl::cuda::SampleConsensusModel<pcl::cuda::Device>'
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include\thrust/random/linear_congruential_engine.h(280): note: see declaration of 'thrust::random::linear_congruential_engine<unsigned int,48271,0,2147483647>'
D:\software\vcpkg\buildtrees\pcl\src\pcl-1.8.1-ea5032be8f\cuda\sample_consensus\include\pcl/cuda/sample_consensus/sac_model.h(350): warning C4251: 'pcl::cuda::SampleConsensusModel<pcl::cuda::Host>::input_': class 'boost::shared_ptr<const pcl::cuda::PointCloudAOS<Storage>>' needs to have dll-interface to be used by clients of class 'pcl::cuda::SampleConsensusModel<pcl::cuda::Host>'
        with
        [
            Storage=pcl::cuda::Host
        ]
D:\software\vcpkg\buildtrees\pcl\src\pcl-1.8.1-ea5032be8f\cuda\common\include\pcl/cuda/point_cloud.h(202): note: see declaration of 'boost::shared_ptr<const pcl::cuda::PointCloudAOS<Storage>>'
        with
        [
            Storage=pcl::cuda::Host
        ]
D:/software/vcpkg/buildtrees/pcl/src/pcl-1.8.1-ea5032be8f/cuda/sample_consensus/src/sac_model.cu(179): note: see reference to class template instantiation 'pcl::cuda::SampleConsensusModel<pcl::cuda::Host>' being compiled
D:\software\vcpkg\buildtrees\pcl\src\pcl-1.8.1-ea5032be8f\cuda\sample_consensus\include\pcl/cuda/sample_consensus/sac_model.h(351): warning C4251: 'pcl::cuda::SampleConsensusModel<pcl::cuda::Host>::normals_': class 'boost::shared_ptr<thrust::host_vector<T,std::allocator<T>>>' needs to have dll-interface to be used by clients of class 'pcl::cuda::SampleConsensusModel<pcl::cuda::Host>'
        with
        [
            T=float4
        ]
D:\software\vcpkg\buildtrees\pcl\src\pcl-1.8.1-ea5032be8f\cuda\sample_consensus\include\pcl/cuda/sample_consensus/sac_model.h(336): note: see declaration of 'boost::shared_ptr<thrust::host_vector<T,std::allocator<T>>>'
        with
        [
            T=float4
        ]
D:\software\vcpkg\buildtrees\pcl\src\pcl-1.8.1-ea5032be8f\cuda\sample_consensus\include\pcl/cuda/sample_consensus/sac_model.h(354): warning C4251: 'pcl::cuda::SampleConsensusModel<pcl::cuda::Host>::indices_': class 'boost::shared_ptr<thrust::host_vector<T,std::allocator<T>>>' needs to have dll-interface to be used by clients of class 'pcl::cuda::SampleConsensusModel<pcl::cuda::Host>'
        with
        [
            T=int
        ]
D:\software\vcpkg\buildtrees\pcl\src\pcl-1.8.1-ea5032be8f\cuda\sample_consensus\include\pcl/cuda/sample_consensus/sac_model.h(99): note: see declaration of 'boost::shared_ptr<thrust::host_vector<T,std::allocator<T>>>'
        with
        [
            T=int
        ]
D:\software\vcpkg\buildtrees\pcl\src\pcl-1.8.1-ea5032be8f\cuda\sample_consensus\include\pcl/cuda/sample_consensus/sac_model.h(356): warning C4251: 'pcl::cuda::SampleConsensusModel<pcl::cuda::Host>::indices_stencil_': class 'boost::shared_ptr<thrust::host_vector<T,std::allocator<T>>>' needs to have dll-interface to be used by clients of class 'pcl::cuda::SampleConsensusModel<pcl::cuda::Host>'
        with
        [
            T=int
        ]
D:\software\vcpkg\buildtrees\pcl\src\pcl-1.8.1-ea5032be8f\cuda\sample_consensus\include\pcl/cuda/sample_consensus/sac_model.h(99): note: see declaration of 'boost::shared_ptr<thrust::host_vector<T,std::allocator<T>>>'
        with
        [
            T=int
        ]
D:\software\vcpkg\buildtrees\pcl\src\pcl-1.8.1-ea5032be8f\cuda\sample_consensus\include\pcl/cuda/sample_consensus/sac_model.h(366): warning C4251: 'pcl::cuda::SampleConsensusModel<pcl::cuda::Host>::rngl_': class 'thrust::random::linear_congruential_engine<unsigned int,48271,0,2147483647>' needs to have dll-interface to be used by clients of class 'pcl::cuda::SampleConsensusModel<pcl::cuda::Host>'
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include\thrust/random/linear_congruential_engine.h(280): note: see declaration of 'thrust::random::linear_congruential_engine<unsigned int,48271,0,2147483647>'
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include\thrust/system/cuda/detail/reduce.h(944): warning C4244: 'argument': conversion from 'Size' to 'int', possible loss of data
        with
        [
            Size=__int64
        ]
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include\thrust/system/cuda/detail/count.h(55): note: see reference to function template instantiation 'T thrust::cuda_cub::reduce_n<thrust::cuda_cub::tag,flag_iterator_t,__int64,size_type,thrust::plus<T>>(thrust::cuda_cub::execution_policy<thrust::cuda_cub::tag> &,InputIt,Size,T,BinaryOp)' being compiled
        with
        [
            T=size_type,
            InputIt=flag_iterator_t,
            Size=__int64,
            BinaryOp=thrust::plus<__int64>
        ]
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include\thrust/system/cuda/detail/count.h(71): note: see reference to function template instantiation '__int64 thrust::cuda_cub::count_if<thrust::cuda_cub::tag,InputIt,thrust::detail::equal_to_value<int>>(thrust::cuda_cub::execution_policy<thrust::cuda_cub::tag> &,InputIt,InputIt,UnaryPred)' being compiled
        with
        [
            InputIt=thrust::detail::normal_iterator<thrust::device_ptr<int>>,
            UnaryPred=thrust::detail::equal_to_value<int>
        ]
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include\thrust/detail/count.inl(40): note: see reference to function template instantiation '__int64 thrust::cuda_cub::count<thrust::cuda_cub::tag,InputIterator,EqualityComparable>(thrust::cuda_cub::execution_policy<thrust::cuda_cub::tag> &,InputIt,InputIt,const Value &)' being compiled
        with
        [
            InputIterator=thrust::detail::normal_iterator<thrust::device_ptr<int>>,
            EqualityComparable=int,
            InputIt=thrust::detail::normal_iterator<thrust::device_ptr<int>>,
            Value=int
        ]
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include\thrust/detail/count.inl(65): note: see reference to function template instantiation '__int64 thrust::count<DerivedPolicy,InputIterator,EqualityComparable>(const thrust::detail::execution_policy_base<DerivedPolicy> &,InputIterator,InputIterator,const EqualityComparable &)' being compiled
        with
        [
            DerivedPolicy=thrust::cuda_cub::tag,
            InputIterator=thrust::detail::normal_iterator<thrust::device_ptr<int>>,
            EqualityComparable=int
        ]
D:/software/vcpkg/buildtrees/pcl/src/pcl-1.8.1-ea5032be8f/cuda/sample_consensus/src/sac_model.cu(160): note: see reference to function template instantiation '__int64 thrust::count<thrust::detail::normal_iterator<thrust::device_ptr<int>>,int>(InputIterator,InputIterator,const EqualityComparable &)' being compiled
        with
        [
            InputIterator=thrust::detail::normal_iterator<thrust::device_ptr<int>>,
            EqualityComparable=int
        ]
D:/software/vcpkg/buildtrees/pcl/src/pcl-1.8.1-ea5032be8f/cuda/sample_consensus/src/sac_model.cu(152): note: while compiling class template member function 'int pcl::cuda::SampleConsensusModel<pcl::cuda::Device>::deleteIndices(const thrust::device_vector<T,thrust::device_malloc_allocator<T>> &,int,boost::shared_ptr<thrust::device_vector<int,thrust::device_malloc_allocator<int>>> &,const boost::shared_ptr<thrust::device_vector<int,thrust::device_malloc_allocator<int>>> &)'
        with
        [
            T=float4
        ]
D:/software/vcpkg/buildtrees/pcl/src/pcl-1.8.1-ea5032be8f/cuda/sample_consensus/src/sac_model.cu(178): note: see reference to class template instantiation 'pcl::cuda::SampleConsensusModel<pcl::cuda::Device>' being compiled
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include\thrust/system/cuda/detail/reduce.h(973): warning C4244: 'argument': conversion from 'Size' to 'int', possible loss of data
        with
        [
            Size=__int64
        ]
ninja: build stopped: subcommand failed.

**Comment by raahilsha** [comment]
I'm getting the exact same issue when I try to build pcl[cuda]:x64-windows. From the error message above (given all the references to DLL interface), I hoped that building pcl[cuda]:x64-windows-static would work. Unfortunately, building static also fails, generating the following log: [install-x64-windows-static-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2439692/install-x64-windows-static-dbg-out.log)

Doing a simple search for "error" in the logfile, I see the following:

D:/vcpkg/buildtrees/pcl/src/pcl-1.8.1-ea5032be8f/cuda/sample_consensus/src/sac_model_plane.cu(195): error: class "thrust::device_reference<const pcl::cuda::PointXYZRGB>" has no member "x"

With similar errors for members "y" and "z". These are also found in sac_model_1point_plane.cu. I see the exact same errors in @leilaShen 's provided logfile as well - maybe that's a starting point towards resolving this issue?

**Comment by NancyLi1013** [comment]
See #7388.

**Comment by cbezault** [comment]
@leilaShen @raahilsha What version of CUDA do you guys have installed?

**Comment by cbezault** [comment]
If this is still an issue please re-open the issue.
