### ISSUE TITLE
[Request] facebook/fbthrift

### ISSUE THREAD

**Issue by horsewww** [microsoft/vcpkg#4358]
Facebook's branch of Apache Thrift, including a new C++ server.
https://github.com/facebook/fbthrift

**Comment by soroshsabz** [comment]
ITNOA

I think it is very similar with thrift, you can see 
[portfile.cmake](https://github.com/Microsoft/vcpkg/blob/master/ports/thrift/portfile.cmake) and [Control file](https://github.com/Microsoft/vcpkg/blob/master/ports/thrift/CONTROL)

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
