### ISSUE TITLE
[vcpkg upgrade] change behavior of vcpkg upgrade --no-dry-run

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#4360]
currentlly vcpkg upgrade --no-dry-run first removes all outdated packages and then tries to Rebuild them.

The problem: If one of the packages fails to build the information of all removed packages is lost.

Solution: Either have a cache file for upgrades or use a different approach for upgrade like: remove package; rebuild package. Another solution would be to not stop the whole upgrade process if one of the builds fails.

**Comment by Neumann-A** [comment]
and maybe add a help dialog for it ....vcpkg help upgrade does not work or list the available commands

**Comment by degski** [comment]
I agree with you, `--keep-going` should be the default, I also think `--no-dry-run` should be changed to `--dry-run` (it's just too irritating to type that every time (with the obvious thick fingered typos).

**Comment by Neumann-A** [comment]
@degski since there is also the `update ` command i disagree on the change of the command `--no-dry-run`. `upate` and `upgrade` are really easy to mix up.

**Comment by NulAsh** [comment]
https://github.com/Microsoft/vcpkg/issues/3864

**Comment by NulAsh** [comment]
I see two options to solve this problem:

1. Change order of actions when upgrading. Download first package, compile it, remove previous version, install. Download second package etc... In case of any problem, interrupted package will still be installed, just previous version, and everything else will be untouched.

2. Do everything as usual, but before upgrading create a file with list of packages to upgrade. In case of problems, just start "vcpkg upgrade" again, it will find this file, and continue from the point of interruption.

**Comment by MikeGitb** [comment]
Nice that the issues around this topic got cleaned up. Is there any plan to solve the issue in the near future?

**Comment by vicroms** [comment]
There have been attempts to do this in PRs but the implementation is complicated.
Our recommendation to somewhat mitigate this problem is to use [manifests] (https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md) if possible.

We may look back into this in the future and that's why we're leaving the issue open.
