### ISSUE TITLE
Problem with FreeImage and AWS

### ISSUE THREAD

**Issue by jorrego** [Microsoft/vcpkg#4362]
I'm trying install FreeImage after AWS and the installation show me an error and viceversa:

C:\vcpkg>.\vcpkg install aws-sdk-cpp
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be built and installed:
    aws-sdk-cpp[core,dynamodb,kinesis,s3]:x86-windows
Starting package 1/1: aws-sdk-cpp:x86-windows
Building package aws-sdk-cpp[core,dynamodb,kinesis,s3]:x86-windows...
-- Downloading https://github.com/aws/aws-sdk-cpp/archive/1.6.12.tar.gz...
-- Using source at C:/vcpkg/buildtrees/aws-sdk-cpp/src/1.6.12-c48061289c
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: C:/vcpkg/buildtrees/aws-sdk-cpp/x86-windows-rel/vcpkg-parallel-configure
    See logs for more information:
      C:\vcpkg\buildtrees\aws-sdk-cpp\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:246 (vcpkg_execute_required_process)
  ports/aws-sdk-cpp/portfile.cmake:23 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package aws-sdk-cpp:x86-windows failed with: BUILD_FAILED

Package: aws-sdk-cpp:x86-windows
Vcpkg version: 0.0.113-nohash

**Comment by Voskrese** [comment]
> See logs for more information:
> C:\vcpkg\buildtrees\aws-sdk-cpp\config-x86-windows-out.log

**Comment by jorrego** [comment]
[1/2] cmd /c "cd .. && "C:/Program Files (x86)/CMake/bin/cmake.exe" "C:/vcpkg/buildtrees/aws-sdk-cpp/src/1.6.12-c48061289c" "-DENABLE_UNITY_BUILD=ON" "-DENABLE_TESTING=OFF" "-DFORCE_SHARED_CRT=0" "-DCMAKE_DISABLE_FIND_PACKAGE_Git=TRUE" "-DBUILD_ONLY=core;dynamodb;kinesis;s3" "-DCMAKE_MAKE_PROGRAM=D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=static" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/vcpkg/packages/aws-sdk-cpp_x86-windows""
FAILED: ../CMakeCache.txt 
cmd /c "cd .. && "C:/Program Files (x86)/CMake/bin/cmake.exe" "C:/vcpkg/buildtrees/aws-sdk-cpp/src/1.6.12-c48061289c" "-DENABLE_UNITY_BUILD=ON" "-DENABLE_TESTING=OFF" "-DFORCE_SHARED_CRT=0" "-DCMAKE_DISABLE_FIND_PACKAGE_Git=TRUE" "-DBUILD_ONLY=core;dynamodb;kinesis;s3" "-DCMAKE_MAKE_PROGRAM=D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=static" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/vcpkg/packages/aws-sdk-cpp_x86-windows""
-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Building AWS libraries as shared objects
-- Generating windows build config
-- Building project version: 
-- The CXX compiler identification is MSVC 19.15.26730.0
-- Check for working CXX compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx64/x86/cl.exe
-- Check for working CXX compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx64/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Encryption: Bcrypt
-- Http client: WinHttp
-- Considering core
-- Considering dynamodb
-- Considering kinesis
-- Considering s3
-- The C compiler identification is MSVC 19.15.26730.0
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx64/x86/cl.exe
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx64/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
Not able to compute versioning string, not updating.
-- Custom memory management enabled; stl objects now using custom allocators
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.12/Modules/WriteBasicConfigVersionFile.cmake:40 (message):
  No VERSION specified for WRITE_BASIC_CONFIG_VERSION_FILE()
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.12/Modules/CMakePackageConfigHelpers.cmake:211 (write_basic_config_version_file)
  cmake/utilities.cmake:96 (write_basic_package_version_file)
  aws-cpp-sdk-core/CMakeLists.txt:490 (do_packaging)


-- Configuring incomplete, errors occurred!
See also "C:/vcpkg/buildtrees/aws-sdk-cpp/x86-windows-rel/CMakeFiles/CMakeOutput.log".
[2/2] cmd /c "cd ../../x86-windows-dbg && "C:/Program Files (x86)/CMake/bin/cmake.exe" "C:/vcpkg/buildtrees/aws-sdk-cpp/src/1.6.12-c48061289c" "-DENABLE_UNITY_BUILD=ON" "-DENABLE_TESTING=OFF" "-DFORCE_SHARED_CRT=0" "-DCMAKE_DISABLE_FIND_PACKAGE_Git=TRUE" "-DBUILD_ONLY=core;dynamodb;kinesis;s3" "-DCMAKE_MAKE_PROGRAM=D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=static" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/vcpkg/packages/aws-sdk-cpp_x86-windows/debug""
FAILED: ../../x86-windows-dbg/CMakeCache.txt 
cmd /c "cd ../../x86-windows-dbg && "C:/Program Files (x86)/CMake/bin/cmake.exe" "C:/vcpkg/buildtrees/aws-sdk-cpp/src/1.6.12-c48061289c" "-DENABLE_UNITY_BUILD=ON" "-DENABLE_TESTING=OFF" "-DFORCE_SHARED_CRT=0" "-DCMAKE_DISABLE_FIND_PACKAGE_Git=TRUE" "-DBUILD_ONLY=core;dynamodb;kinesis;s3" "-DCMAKE_MAKE_PROGRAM=D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=static" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/vcpkg/packages/aws-sdk-cpp_x86-windows/debug""
-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Building AWS libraries as shared objects
-- Generating windows build config
-- Building project version: 
-- The CXX compiler identification is MSVC 19.15.26730.0
-- Check for working CXX compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx64/x86/cl.exe
-- Check for working CXX compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx64/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Encryption: Bcrypt
-- Http client: WinHttp
-- Considering core
-- Considering dynamodb
-- Considering kinesis
-- Considering s3
-- The C compiler identification is MSVC 19.15.26730.0
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx64/x86/cl.exe
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx64/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
Not able to compute versioning string, not updating.
-- Custom memory management enabled; stl objects now using custom allocators
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.12/Modules/WriteBasicConfigVersionFile.cmake:40 (message):
  No VERSION specified for WRITE_BASIC_CONFIG_VERSION_FILE()
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.12/Modules/CMakePackageConfigHelpers.cmake:211 (write_basic_config_version_file)
  cmake/utilities.cmake:96 (write_basic_package_version_file)
  aws-cpp-sdk-core/CMakeLists.txt:490 (do_packaging)


-- Configuring incomplete, errors occurred!
See also "C:/vcpkg/buildtrees/aws-sdk-cpp/x86-windows-dbg/CMakeFiles/CMakeOutput.log".
ninja: build stopped: subcommand failed.

**Comment by Voskrese** [comment]
>  See also "C:/vcpkg/buildtrees/aws-sdk-cpp/x86-windows-dbg/CMakeFiles/CMakeOutput.log".

>  See also "C:/vcpkg/buildtrees/aws-sdk-cpp/x86-windows-rel/CMakeFiles/CMakeOutput.log".

**Comment by LarryIII** [comment]
@jorrego Thanks for your feedback, This issue was fixed by source version updated, could you please close this issue? 
BTW, here is my installation log:
g:\Larry\vcpkg>vcpkg install aws-sdk-cpp
The following packages will be built and installed:
    aws-sdk-cpp[core,dynamodb,kinesis,s3]:x86-windows
Starting package 1/1: aws-sdk-cpp:x86-windows
Building package aws-sdk-cpp[core,dynamodb,kinesis,s3]:x86-windows...
-- Downloading https://github.com/aws/aws-sdk-cpp/archive/**1.6.47.tar.gz...**
-- Extracting source G:/Larry/vcpkg/downloads/aws-aws-sdk-cpp-**1.6.47.tar.gz**
-- Using source at G:/Larry/vcpkg/buildtrees/aws-sdk-cpp/src/**1.6.47-27a89d88bf**
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: G:/Larry/vcpkg/packages/aws-sdk-cpp_x86-windows/share/aws-sdk-cpp/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package aws-sdk-cpp[core,dynamodb,kinesis,s3]:x86-windows... done
Installing package aws-sdk-cpp[core,dynamodb,kinesis,s3]:x86-windows...
Installing package aws-sdk-cpp[core,dynamodb,kinesis,s3]:x86-windows... done
Elapsed time for package aws-sdk-cpp:x86-windows: 26.29 min

**Comment by LarryIII** [comment]
Thanks for you feedback. Please re-open if this is still a problem for you!
