### ISSUE TITLE
Add ability to append headers when downloading

### ISSUE THREAD

**Issue by donny-dont** [microsoft/vcpkg#4364]
Currently there is no way to append headers when calling `vcpkg_download_distfile`.

My scenario is that I'm trying to download a release from a private repo on a GitHub Enterprise instance. I would like to add a personal access token to the request so both CMake or Aria2 can download a file.

For Aria2 its a matter of adding `--header` values to the request. For CMake download supports `HTTPHEADER`. Both can take multiple values with it.

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen this issue.
