### ISSUE TITLE
opengl installation fails when platform sdk is installed in non-default location

### ISSUE THREAD

**Issue by djmott** [Microsoft/vcpkg#4377]
I have a small SSD for the OS, applications and data get installed on a mechanical RAID. I get the following error:
CMake Error at ports/opengl/portfile.cmake:20 (message):
  Cannot find Windows 10.0.17134.0 SDK.  File does not exist: C:\Program
  Files (x86)\Windows Kits\10\Lib\10.0.17134.0\um\x64\OpenGL32.Lib
Call Stack (most recent call first):
  scripts/ports.cmake:71 (include)

Error: Building package opengl:x64-windows failed with: BUILD_FAILED

**Comment by Bean5243** [comment]
You should set PROGRAM_FILES_32_BIT in portfile.cmake to your local path where OpenGL32.Lib exists.

**Comment by LarryIII** [comment]
@djmott Please close this feedback if you resolve your issue!
