### ISSUE TITLE
Error: Building package opencv: x86-uwp failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by StarWardo** [Microsoft/vcpkg#4386]
Following this REAME: https://github.com/Microsoft/MixedRealityToolkit/blob/master/SpectatorViewPlugin/README.md

When doing the following command: .\vcpkg install opencv[contrib]:x86-uwp --recurse

Error message: 

Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv:x86-uwp
  Vcpkg version: 0.0.113-nohash

C:\Users\ward\vcpkg>.\vcpkg install opencv[contrib]:x86-uwp --recurse
The following packages will be built and installed:
    opencv[contrib,core,eigen,flann,jpeg,opengl,png,tiff]:x86-uwp
Starting package 1/1: opencv:x86-uwp
Building package opencv[contrib,core,eigen,flann,jpeg,opengl,png,tiff]:x86-uwp...
-- Using cached C:/Users/ward/vcpkg/downloads/opencv-opencv-3.4.1.tar.gz
-- Using source at C:/Users/ward/vcpkg/buildtrees/opencv/src/3.4.1-273ea13f6d
-- Applying patch C:/Users/ward/vcpkg/ports/opencv/0001-winrt-fixes.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/Users/ward/vcpkg/ports/opencv/0002-install-options.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/Users/ward/vcpkg/ports/opencv/0003-disable-downloading.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/Users/ward/vcpkg/ports/opencv/0004-use-find-package-required.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/Users/ward/vcpkg/ports/opencv/0005-remove-protobuf-target.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Using cached C:/Users/ward/vcpkg/downloads/opencv-cache/data/7505c44ca4eb54b4ab1e4777cb96ac05-face_landmark_model.dat
-- Using cached C:/Users/ward/vcpkg/downloads/opencv-cache/tiny_dnn/adb1c512e09ca2c7a6faef36f9c53e59-v1.0.0a3.tar.gz
-- Using cached C:/Users/ward/vcpkg/downloads/opencv-opencv_contrib-3.4.1.tar.gz
-- Using source at C:/Users/ward/vcpkg/buildtrees/opencv/src/3.4.1-527d1a92af
-- Configuring x86-uwp
-- Building x86-uwp-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: C:/Users/ward/vcpkg/downloads/tools/cmake-3.11.4-windows/cmake-3.11.4-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No
    Working Directory: C:/Users/ward/vcpkg/buildtrees/opencv/x86-uwp-dbg
    See logs for more information:
      C:\Users\ward\vcpkg\buildtrees\opencv\install-x86-uwp-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/opencv/portfile.cmake:316 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

**Comment by Voskrese** [comment]
> See logs for more information:
> C:\Users\ward\vcpkg\buildtrees\opencv\install-x86-uwp-dbg-out.log

**Comment by ilyavitek** [comment]
Had similar issue. https://github.com/Microsoft/vcpkg/issues/4745
@StarWardo any progress?

**Comment by PhoebeHui** [comment]
Hi StarWardo,

This issue already fixed, and opencv:x86-uwp installed successfully, you can get vcpkg latest revision, and have a try.

Starting package 4/4: opencv:x86-uwp
Building package opencv[core,eigen,flann,jpeg,opengl,png,tiff]:x86-uwp...
-- Using cached F:/VCPKG/src/downloads/opencv-opencv-3.4.3.tar.gz
-- Using source at F:/VCPKG/src/buildtrees/opencv/src/3.4.3-701a6234df
-- Configuring x86-uwp
-- Building x86-uwp-dbg
-- Building x86-uwp-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package opencv[core,eigen,flann,jpeg,opengl,png,tiff]:x86-uwp... done
Installing package opencv[core,eigen,flann,jpeg,opengl,png,tiff]:x86-uwp...
Installing package opencv[core,eigen,flann,jpeg,opengl,png,tiff]:x86-uwp... done
Elapsed time for package opencv:x86-uwp: 5.99 min

Total elapsed time: 9.089 min

The package opencv provides CMake integration:

    find_package(OpenCV REQUIRED)
    target_include_directories(main PRIVATE ${OpenCV_INCLUDE_DIRS})
    target_link_libraries(main PRIVATE ${OpenCV_LIBS})

Thanks,
Phoebe
