### ISSUE TITLE
About software usage

### ISSUE THREAD

**Issue by Fish201809** [microsoft/vcpkg#4392]
Hi.
The following description was obtained when I executed VCPKG search xerces-c ++.
      Xerces-C++ is a XML parser, for parsing, generating, manipulating, and validat...
Information is not complete, How can I get a complete package description.

**Comment by NancyLi1013** [comment]
Hi @Fish201809, thanks for posting this issue. You can get a relative complete package description by these three ways:
1.  Go through the description in vcpkg/ports/xerces-c/CONTROL file.
https://github.com/microsoft/vcpkg/blob/60ecb465615ca7f9589026013ae489766b8356cb/ports/xerces-c/CONTROL
2.  Look for the branch name apache/xerces-c from vcpkg_from_github function in vcpkg/ports/xerces-c/portfile.cmake file, then search apache/xerces-c branch on the gitHub, you can see more info about the port.
https://github.com/apache/xerces-c
3. Search xerces-c on the web.
https://xerces.apache.org/xerces-c/

If you want to know the complete package descriptions about other ports, you can refer to the above ways. Hope these will help you.
