### ISSUE TITLE
shaderc: build fails

### ISSUE THREAD

**Issue by jweg** [Microsoft/vcpkg#4397]
Edit: Fix here: #4398 

Package: shaderc:x64-linux
Vcpkg version: 0.0.113-unknownhash
vcpkg revision: 0cbb8a1626f04b3316a52e44266c3b9adf316f9b
Ubuntu 18.04

Steps to reproduce: vcpkg install shaderc

Log excerpt:
FAILED: libshaderc/libshaderc_combined.a 
cd /home/jw/jw/vcpkg/buildtrees/shaderc/x64-linux-dbg/libshaderc && /usr/bin/ar -M < shaderc_combined.ar
/usr/bin/ar: SPIRVTOOLS-NOTFOUND: No such file or directory
[22/25] : && /usr/bin/c++  -fPIC  -rdynamic examples/online-compile/CMakeFiles/shaderc-online-compile.dir/main.cc.o  -o examples/online-compile/shaderc-online-compile  libshaderc/libshaderc.a libshaderc_util/libshaderc_util.a GLSLANG-NOTFOUND OSDEPENDENT-NOTFOUND OGLCOMPILER-NOTFOUND -lpthread HLSLLIB-NOTFOUND /home/jw/jw/vcpkg/installed/x64-linux/debug/lib/libSPIRV-Tools-opt.a SPIRVLIB-NOTFOUND SPIRVTOOLS-NOTFOUND && :
FAILED: examples/online-compile/shaderc-online-compile 
: && /usr/bin/c++  -fPIC  -rdynamic examples/online-compile/CMakeFiles/shaderc-online-compile.dir/main.cc.o  -o examples/online-compile/shaderc-online-compile  libshaderc/libshaderc.a libshaderc_util/libshaderc_util.a GLSLANG-NOTFOUND OSDEPENDENT-NOTFOUND OGLCOMPILER-NOTFOUND -lpthread HLSLLIB-NOTFOUND /home/jw/jw/vcpkg/installed/x64-linux/debug/lib/libSPIRV-Tools-opt.a SPIRVLIB-NOTFOUND SPIRVTOOLS-NOTFOUND && :
c++: error: GLSLANG-NOTFOUND: No such file or directory
c++: error: OSDEPENDENT-NOTFOUND: No such file or directory
c++: error: OGLCOMPILER-NOTFOUND: No such file or directory
c++: error: HLSLLIB-NOTFOUND: No such file or directory
c++: error: SPIRVLIB-NOTFOUND: No such file or directory
c++: error: SPIRVTOOLS-NOTFOUND: No such file or directory

**Comment by PhoebeHui** [comment]
I try to repro this issue on Linux, it failed with https://github.com/Microsoft/vcpkg/issues/4578.

**Comment by PhoebeHui** [comment]
@jweg, thank you for posting this issue! you can try install shaderc with latest vcpkg, and please open a new issue if this is still a problem for you.

Shaderc installed successfully on unbuntu 16.04:

linux001@linuxtest01:~/vcpkg$ ./vcpkg install shaderc:x64-linux
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be built and installed:
  * glslang[core]:x64-linux
    shaderc[core]:x64-linux
  * spirv-tools[core]:x64-linux
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: spirv-tools:x64-linux
Building package spirv-tools[core]:x64-linux...
-- Using cached /home/linux001/vcpkg/downloads/KhronosGroup-SPIRV-Tools-v2018.1.tar.gz
-- Using source at /home/linux001/vcpkg/buildtrees/spirv-tools/src/v2018.1-6c6f5348e5
-- Using cached /home/linux001/vcpkg/downloads/KhronosGroup-SPIRV-Headers-bd4c092be34081d88ec8342b1a4d9f77bcce4cac.tar.gz
-- Using source at /home/linux001/vcpkg/buildtrees/spirv-tools/src/77bcce4cac-2134a7a620
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package spirv-tools[core]:x64-linux... done
Installing package spirv-tools[core]:x64-linux...
Installing package spirv-tools[core]:x64-linux... done
Elapsed time for package spirv-tools:x64-linux: 2.969 min
Starting package 2/3: glslang:x64-linux
Building package glslang[core]:x64-linux...
-- Downloading https://github.com/KhronosGroup/glslang/archive/b5b5f918c6b72d7cf2ee73641cc6c6ddb211ca70.tar.gz...
-- Extracting source /home/linux001/vcpkg/downloads/KhronosGroup-glslang-b5b5f918c6b72d7cf2ee73641cc6c6ddb211ca70.tar.gz
-- Using source at /home/linux001/vcpkg/buildtrees/glslang/src/ddb211ca70-76c5f516b2
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package glslang[core]:x64-linux... done
Installing package glslang[core]:x64-linux...
Installing package glslang[core]:x64-linux... done
Elapsed time for package glslang:x64-linux: 1.138 min
Starting package 3/3: shaderc:x64-linux
Building package shaderc[core]:x64-linux...
-- Downloading https://github.com/google/shaderc/archive/12fb656ab20ea9aa06e7084a74e5ff832b7ce2da.tar.gz...
-- Extracting source /home/linux001/vcpkg/downloads/google-shaderc-12fb656ab20ea9aa06e7084a74e5ff832b7ce2da.tar.gz
-- Applying patch 0001-Do-not-generate-build-version.inc.patch
-- Using source at /home/linux001/vcpkg/buildtrees/shaderc/src/832b7ce2da-d5870ea381
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package shaderc[core]:x64-linux... done
Installing package shaderc[core]:x64-linux...
Installing package shaderc[core]:x64-linux... done
Elapsed time for package shaderc:x64-linux: 36.49 s

Total elapsed time: 4.715 min
