### ISSUE TITLE
Use vcpkg with cross-compiling

### ISSUE THREAD

**Issue by jasonbeach** [microsoft/vcpkg#4401]
I'm setting up vcpkg for use with an aarch64 cross-compiler and receive cmake errors on some packages.  
I created a triplet file triplets/arm64-linux.cmake: 
```
set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE /home/talon/mysource/vcpkg/scripts/toolchains/aarch64_l4t28.1.cmake)
```
The toolchain file contains:
```
set (XCOMPILE_DIR /opt/xcompile-aarch64-l4t28.1)

set (ROOTFS ${XCOMPILE_DIR}/aarch64_l4t28.1_rootfs/)
set (TOOLCHAIN_DIR ${XCOMPILE_DIR}/gcc-linaro-5.4.1-2017.05-x86_64_aarch64-linux-gnu/)

set (CMAKE_SYSTEM_NAME Linux)
set (CMAKE_SYSTEM_VERSION L4T28.1)
set (CMAKE_SYSTEM_PROCESSOR AARCH64)

set (CMAKE_C_COMPILER ${TOOLCHAIN_DIR}/bin/aarch64-linux-gnu-gcc)
set (CMAKE_CXX_COMPILER ${TOOLCHAIN_DIR}/bin/aarch64-linux-gnu-g++)
set (CMAKE_FIND_ROOT_PATH ${ROOTFS})

# CMAKE_SYSROOT is cmake 3.0+ only
set (CMAKE_SYSROOT ${ROOTFS})
set (CMAKE_UNAME ${CMAKE_SYSROOT}/bin/uname)

set (CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set (CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set (CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# resetting pkg-config paths
set(ENV{PKG_CONFIG_DIR} "")
set(ENV{PKG_CONFIG_LIBDIR} "${CMAKE_SYSROOT}/usr/lib/pkgconfig:${CMAKE_SYSROOT}/usr/local/lib/pkgconfig:${CMAKE_SYSROOT}/usr/lib/aarch64-linux-gnu/pkgconfig:${CMAKE_SYSROOT}/usr/share/pkgconfig")
set(ENV{PKG_CONFIG_SYSROOT_DIR} ${CMAKE_SYSROOT})
```
The toolchain is a linaro gcc package I've used for some time coupled with a rootfs generated from the embedded board itself. The toolchain file above has also been used for a while with

installing some packages works fine.  e.g.
 `./vcpkg install yaml-cpp:arm64-linux`
works fine while 
`./vcpkg install zeromq:arm64-linux`
doesn't.  Building zeromq with the default toolchain also works fine:
`./vcpkg install zeromq`

There are a couple of hints of what the error is: 
In the buildtrees/zeromq/config-arm64-linux-dbg-err.log file:
```
CMake Error at CMakeLists.txt:420 (zmq_check_noexcept):
  Unknown CMake command "zmq_check_noexcept".
```
In buildtrees/zeromq/arm64-linux-dbg/CMakeFiles/CMakeError.log I see
```
.../aarch64-linux-gnu/bin/ld: cannot find -lpthreads
...
CheckFunctionExists.c.o: In function `main':
CheckFunctionExists.c:(.text+0x10): undefined reference to `gethrtime'
```
Which seems to imply that the cross compiler is not being fed the right paths.

Ideas?
[config-arm64-linux-dbg-err.log](https://github.com/Microsoft/vcpkg/files/2442847/config-arm64-linux-dbg-err.log)
[config-arm64-linux-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2442848/config-arm64-linux-dbg-out.log)
[CMakeError.log](https://github.com/Microsoft/vcpkg/files/2442903/CMakeError.log)
[CMakeOutput.log](https://github.com/Microsoft/vcpkg/files/2442904/CMakeOutput.log)

**Comment by Voskrese** [comment]
`echo $TOOLCHAIN_DIR`
?

**Comment by bramburn** [comment]
weird...

**Comment by bramburn** [comment]
one solution is to use system environment, I cannot remember the arg for when building the boostrap....sh but if you install cmake, make on the system cross compile works that way.

**Comment by JackBoosY** [comment]
Hi guys, does this issue still exist?

**Comment by JackBoosY** [comment]
Hi @jasonbeach, can you please confirm whether this issue can be reproduced in the latest master?

Thanks.

**Comment by jasonbeach** [comment]
Hi, I apologize but I am no longer able to test this.

**Comment by JackBoosY** [comment]
Fine, please reopen this issue if you meet it again.
