### ISSUE TITLE
Yara not working on Linux

### ISSUE THREAD

**Issue by slay-er** [Microsoft/vcpkg#4411]
Hi! I tried to install the yara library on linux 64-bit (./vcpkg install yara:x64-linux), but it fails.

After a look at the CMakeLists.txt, I found two issues:

  -DHAVE_LIBCRYPTO -D**USE_WINDOWS_PROC**
It seems that it currently only supports windows.

  -DCUCKOO_MODULE- **D**HASH_MODULE -DDOTNET_MODULE
... and HASH_MODULE is not defined correctly.

But it still fails to compile, after I fixed the issues.

Attaching the log file.
[install-x64-linux-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2450162/install-x64-linux-dbg-out.log)

**Comment by jimmysoda** [comment]
I'm using Docker to test my changes. I created gists for two Dockerfiles:

- [Dockerfile to test yara installation with vcpkg in ubuntu xenial](https://gist.github.com/jimmysoda/2bba78cb16bd646e50b93f9fa42fefed): clones Microsoft/vcpkg with HEAD on master branch
- [Dockerfile to test fix for yara installation with vcpkg in ubuntu xenial](https://gist.github.com/jimmysoda/0557bf64d21bcaaf55d19e07bdfc5c2d): clones Simverge/vcpkg with HEAD on issue-4411-yara-linux branch

**Comment by ras0219-msft** [comment]
This should be fixed by #4431; please let us know if you still have any issues!
