### ISSUE TITLE
opencv cant read mp4 files

### ISSUE THREAD

**Issue by UMichael** [Microsoft/vcpkg#4414]
Tried using videocapture to read files it just wont read it installed with ffmpeg still same thing dont know what i'm missing

**Comment by stiv-yakovenko** [comment]
install opencv[ffmpeg]

**Comment by UMichael** [comment]
I installed it but still it won't open mp4

**Comment by stiv-yakovenko** [comment]
Give more info, what dlls are near your exe

**Comment by UMichael** [comment]
ffmpeg dll seems not to be loaded near my exe, dont know why, but i'm sure my opencv[ffmpeg] installation was ok any help please

**Comment by UMichael** [comment]
Thanks solved the issue had to get the 64bit dll file to make it work ,hope opencv gets updated to 4.0

**Comment by patrikhuber** [comment]
This sounds like it's related to #2613 and #2799.
