### ISSUE TITLE
opencv opencv_tracking341d.dll

### ISSUE THREAD

**Issue by stiv-yakovenko** [microsoft/vcpkg#4415]
How can I install opencv so I have this dll/h files and dependencies available?

**Comment by PhoebeHui** [comment]
Hi stiv-yakovenko,

You can execute ' .\vcpkg install opencv' to install opencv and after it installed successfully you can find dll/h file under .\VCPKG\src\packages\opencv_x86-windows. Please close this issue if it's solved.

Thanks,
Phoebe
