### ISSUE TITLE
Gtk-WARNING **: Could not find the icon

### ISSUE THREAD

**Issue by ishaantantra** [Microsoft/vcpkg#4417]
Gtk-WARNING **: Could not find the icon 'window-minimize-symbolic-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
        http://icon-theme.freedesktop.org/releases
![gtkmm theme error](https://user-images.githubusercontent.com/40491518/46567837-4cf17e00-c958-11e8-84e2-6bc688362c01.png)

**Comment by phanalax** [comment]
I encountered this problem on windows 10 as well, the fix is fairly simple. 
You just have to run msys2 (which is installed to vcpkg/downloads/tools/msys2 when you get gtkmm I think) and use 'pacman' to install either mingw32/mingw-w64-i686-adwaita-icon-theme or mingw64/mingw-w64-x86_64-adwaita-icon-theme.
Then after its installed you create a directory 'shared' in your build directories, and copy the icons directory from msys/mingw64/share/ to your build/share directory.
After that the app should be able to locate the icons properly.

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.

**Comment by ketsuban** [comment]
Just to confirm, is this a symptom of #6554?

**Comment by furkcom** [comment]
my share/icons folder has Adwaita and hicolor icons folder.when I run gtk app, there is no warning message display , but icons doesn't showed correctly on titlebar, same as "ishaantantra" report

**Comment by kakyoism** [comment]
> I encountered this problem on windows 10 as well, the fix is fairly simple.
> You just have to run msys2 (which is installed to vcpkg/downloads/tools/msys2 when you get gtkmm I think) and use 'pacman' to install either mingw32/mingw-w64-i686-adwaita-icon-theme or mingw64/mingw-w64-x86_64-adwaita-icon-theme.
> Then after its installed you create a directory 'shared' in your build directories, and copy the icons directory from msys/mingw64/share/ to your build/share directory.
> After that the app should be able to locate the icons properly.

Are you sure msys2 is installed via gtkmm? I just tried `vcpkg install gtkmm:x64-windows` and the build was a success, but there is no msys2 under `vcpkg/downloads/tools`.

**Comment by kakyoism** [comment]
> share/icons



> my share/icons folder has Adwaita and hicolor icons folder.when I run gtk app, there is no warning message display , but icons doesn't showed correctly on titlebar, same as "ishaantantra" report

Where exactly is your `share/icons` located? The full path or relative path to vcpkg root?

**Comment by ishaantantra** [comment]
> 
> 
> > I encountered this problem on windows 10 as well, the fix is fairly simple.
> > You just have to run msys2 (which is installed to vcpkg/downloads/tools/msys2 when you get gtkmm I think) and use 'pacman' to install either mingw32/mingw-w64-i686-adwaita-icon-theme or mingw64/mingw-w64-x86_64-adwaita-icon-theme.
> > Then after its installed you create a directory 'shared' in your build directories, and copy the icons directory from msys/mingw64/share/ to your build/share directory.
> > After that the app should be able to locate the icons properly.
> 
> Are you sure msys2 is installed via gtkmm? I just tried `vcpkg install gtkmm:x64-windows` and the build was a success, but there is no msys2 under `vcpkg/downloads/tools`.

You install mingw-w64-x86_64-adwaita-icon-theme using ` pacman -S mingw-w64-x86_64-adwaita-icon-theme`.

Find the share folder in msys2 
`<path-to-msys64>\mingw64\share e.g.- C:\msys64\mingw64\share`
Here you locate icons folder and copy it to 
`<path-to-vcpkg>\installed\x64-windows\share e.g.- D:\vcpkg\installed\x64-windows\share`

All warnings regarding could not icon are resolved from this.
Kindly note this is the procedure for 64-bit version same can be modified for 32-bit version.

**Comment by kakyoism** [comment]
@ishaantantra Thank you! Figured that out myself though. But it's a shame that icons and themes are N/A with vcpkg.

**Comment by sam20908** [comment]
@kakyoism I completely agree with you. If Gtk needs the icons, then icons therefore are a dependency, and something vcpkg should handle automatically.

**Comment by filipwtf** [comment]
So are their any plans to include the icons? Or do we have to manually install them?

**Comment by homandiy** [comment]
My code to show the path:


```
  /* icon theme "D:/vcpkg/installed/x64-windows/share/icons" */
  GtkIconTheme* icon_theme = gtk_icon_theme_get_default();
  gchar** path;
  gint n_elements;

  gtk_icon_theme_get_search_path(icon_theme,
    &path, &n_elements);

  g_print("\n\n icons theme: %s, element#: %d\n\n", *path, n_elements);
```

Now, run your code to find the path on the console:

```
 invalid for instance '000002ECD36AF8F0' of type 'preview-image'


 icons theme: C:\Users\Homan\AppData\Local\icons, element#: 12


(basic-tutorial-5.exe:32428): GLib-GObject-WARNING **: 10:10:12.532: ../gobject/gsignal.c:2529: signal 'realize' is invalid for instance '000002ECD12B9210' of type 'video/x-h265, stream-format=(string)byte-stream, alignment=(string)au, profile=(string){ main, main-10 }, width=(int)[ 64, 8192 ], height=(int)[ 64, 8192 ]'
```

Copy the icons from: C:\msys64\mingw64\share\icons
to YOUR path: C:\Users\ YOUR ACCOUNT \AppData\Local\icons

ICONS FIXED!
