### ISSUE TITLE
Update mongo-cxx-driver

### ISSUE THREAD

**Issue by VioletGiraffe** [microsoft/vcpkg#4419]
The MongoDB C++ driver is getting outdated. I've spent some time trying to follow [this example](https://github.com/mongodb/mongo-cxx-driver/blob/master/examples/mongocxx/bulk_write.cpp) and figuring out why `mongocxx::collection` class doesn't have the `create_bulk_write()` method; turns out, it was introduced in driver version 3.2. On top of that, our current driver can only work with Mongo server version 3.4, which is two major versions behind (there was 3.6, and now there's 4.0).

**Comment by lsparey** [comment]
Mongo cxx driver has been updated now

**Comment by NancyLi1013** [comment]
Hi @VioletGiraffe, thanks for posting this issue. This port has been updated to 3.4.0. Please open a new issue if you have any problems when using it.
