### ISSUE TITLE
vcpkg_apply_patches fails to apply patch 

### ISSUE THREAD

**Issue by willyd** [microsoft/vcpkg#442]
Hi, 

I am trying to write my first portfile for LMDB as stated in issue #385. 

However, I have an issue where vcpkg_apply_patches fails to apply the patch with the following error message: `fatal: git apply: bad git-diff - expected /dev/null on line 4`. The error seems to be related to the fact that the patch file has CRLF line endings since when I change them to LF everything works fine. 

The LMDB release zip archive contains LF line endings so I tried to replace those with CRLF to see if this would also fix the issue but it does not.

I can think of two ways to fix this issue:

- Patch the patch file with some shell or CMake command before applying it
- Use .gitattributes to force all .patch files to have LF line endings on checkout.

However, most patches have CRLF line endings and do apply correctly so there must something I am doing wrong. Any ideas on what this could be?

The port file can be found at https://github.com/willyd/vcpkg/tree/lmdb

**Comment by willyd** [comment]
The issue seems to occur only when there are new (and potentially deleted) files. For some reason I don't understand the line /dev/null (specifying that there is no file to compare to) did not like to end with CRLF.

Is the expected? Currently my workaround is to use a patch for existing files and copy the new files using a `file(COPY)` command in the portfile.

**Comment by ras0219-msft** [comment]
I haven't seen this issue before. Thanks for opening it, you've suggested a good workaround.

If someone else hits this issue, we can investigate further. It might be a bug in git's patch implementation, in which case a good fix would be for us to add patching as a builtin vcpkg function that we can address problems in.

**Comment by Neumann-A** [comment]
in #9966 I had to add: `-c core.autocrlf=false` to `vcpkg_apply_patches`
complete command:
`COMMAND ${GIT} --work-tree=. --git-dir=.git -c core.autocrlf=false apply "${ABSOLUTE_PATCH}" --ignore-whitespace --whitespace=nowarn --verbose`

**Comment by PhoebeHui** [comment]
This sholud not be a problem now, currently core.autocrlf=false has configured to vcpkg_apply_patches.
