### ISSUE TITLE
Unable to link gflags and cpprestsdk in RelWithDebInfo configuration

### ISSUE THREAD

**Issue by mr-const** [microsoft/vcpkg#4435]
I'm trying to build cmake generated project with a custom triplet (x64-windows-static-md)
(Visual Studio 2017)
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
```
however there are problems with link in the RelWithDebInfo configuration (Debug and Release are working okay).
CMake sets debug version of linked lib files in RelWithDebInfo configuration in vcxproj file, therefore I get 'iterator level mismatch' and other errors, because our application is set to link with release runtime and cpprestsdk with gflags are debug versions and linked against debug runtime.
Boost libraries, which are linked too, are of correct version (Release).

**Comment by Neumann-A** [comment]
#5543 see change set and the configuration mapping used in vcpkg.cmake

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
