### ISSUE TITLE
Unable to download package over ssh

### ISSUE THREAD

**Issue by jasonbeach** [microsoft/vcpkg#4439]
I'm setting up my own private repository and would like to add a port for a vendor supplied library for controlling a device.  The library comes as a zip file that is not a git repo but does use CMake.  I've saved the file on my own internal server, but when trying to create a port
```
./vcpkg create vector_nav ssh://user@myserver.com:/path/to/vnproglib-1-1-4.zip
```
I get the error
```
-- Downloading ssh://user@myserver.com:/path/to/vnproglib-1-1-4.zip...Failed. Status: 1;"Unsupported protocol"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:156 (message):
```
It seems that the `CMake file(DOWNLOAD...)` command that is used in `vcpkg_download_distfile`  assumes the file is coming from an http source.  Is there an easy way to enable CMake downloading over other protocols such as ssh?  On other CMake projects I've worked on I've used `add_custom_command` to download a file via scp.  I suppose I could change vcpkg_download_distfile to parse the URL and if it starts with ssh then execute the custom command (and could submit a pull request for it if desired).  Just seems kind of hackish.  I see there is an experimental option to use aria2 for downloads when installing ports but that doesn't have seem to be implemented in the `vcpkg create` command. Maybe that would help?

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen this issue.
