### ISSUE TITLE
Failure when receiving data from the peer

### ISSUE THREAD

**Issue by prasanpro** [Microsoft/vcpkg#4446]
When I run following command on x64 machine, I'm getting different kind of issues. Trying to solve using suggestions provided but not able to pass this hurdle.
> vcpkg install curl:x64-windows
> The following packages will be built and installed:
>     curl[core,ssl]:x64-windows
>   * openssl[core]:x64-windows
>   * openssl-windows[core]:x64-windows
> Additional packages (*) will be modified to complete this operation.
> Starting package 1/3: openssl-windows:x64-windows
> Building package openssl-windows[core]:x64-windows...
> -- Downloading http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portable.zip...
> -- Downloading http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portable.zip... Failed. Status: 56;"Failure when receiving data from the peer"
> CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:156 (message):
> 
>       Failed to download file.
>       If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
>       variables to "https://user:password@your-proxy-ip-address:port/".
>       Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_find_acquire_program.cmake:235 (vcpkg_download_distfile)
>   ports/openssl-windows/portfile.cmake:9 (vcpkg_find_acquire_program)
>   scripts/ports.cmake:71 (include)
> 
> 
> Error: Building package openssl-windows:x64-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: openssl-windows:x64-windows
>   Vcpkg version: 0.0.113-nohash
> 
> Additionally, attach any relevant sections from the log files above.

Kindly help me fix this issue.

**Comment by nicole9456** [comment]
Dear customer, 
We can't repro your issue on the latest vcpkg, could you try to double check it? thanks very much!
![image](https://user-images.githubusercontent.com/46737724/51818444-d15b6a00-2283-11e9-8a5b-2162ff41d0ef.png)

**Comment by LarryIII** [comment]
Thanks for your feedback. I installed curl:x64-windows successfully with VS 2017 15.9.11, Please try to use latest vcpkg version and reopen a new issue if it is still a problem for you!
