### ISSUE TITLE
Updating OpenVDB to latest 5.2.0

### ISSUE THREAD

**Issue by jay3d** [microsoft/vcpkg#4448]
Hi!

Here's a patch to update OpenVDB ports package to 5.2.0

Thanks for this wonderful project!

[update_openvdb_to_5.2.0.patch.txt](https://github.com/Microsoft/vcpkg/files/2468329/update_openvdb_to_5.2.0.patch.txt)

**Comment by cgolchert** [comment]
I couldn't get this to work.  I just get the error that tells me "this error is normal if it was already patched."  It then ignores it and builds/installs 5.0.0.

**Comment by NancyLi1013** [comment]
Hi @jay3d, thanks for posting this issue. Openvdb has been updated to 6.1.0 in vcpkg. Please update the port to the latest version.
