### ISSUE TITLE
Copy DLLs to output directory for all target types

### ISSUE THREAD

**Issue by chrullrich** [Microsoft/vcpkg#445]
In the MSBuild integration, applocal.ps1 automatically copies all required DLLs that vcpkg knows about to the build output directory, as long as the target is an .exe . Is there any reason it should not do that for .dll targets as well?

The relevant lines in vcpkg.targets refer to the target file as `$(OutputPath)$(TargetName).$(OutputType)`, and this only applies to .exe targets because for DLL projects, $(OutputPath) is "library".

I tried replacing that expression by both `$(OutputPath)$(TargetName)$(TargetExt)` and simply `$(TargetPath)`. It worked in both cases, with fairly simple test projects. The condition of the surrounding &lt;Target> element must also be changed to remove the check on $(OutputType).

**Comment by chrullrich** [comment]
Additionally, it might also make sense to change the scheduling for the AppLocalFromInstalled target to `BeforeTargets="CopyLocalFilesOutputGroup;RegisterOutput"` (adding the RegisterOutput target) so that automatic self-registration of EXE (and DLL) servers can succeed. Currently, the build will always fail in this situation because the module to be registered fails to load because the dependencies are missing. After all, selfreg _is_ useful during development.

**Comment by adam4813** [comment]
To expand upon this, all installed package DLLs are not copied for release AND debug targets depending on the name of the library, to the output folder of the including project.

**Comment by alexkaratarakis** [comment]
Fixed by #449
