### ISSUE TITLE
geos build error on windows-64bit

### ISSUE THREAD

**Issue by Anzai1028** [Microsoft/vcpkg#4452]
When I was using Vcpkg to build geos lib, there came out a error. 
Following is the error description:
 Starting package 1/1: geos:x86-windows
Building package geos[core]:x86-windows...
-- Using cached F:/OSG/VCPKG/vcpkg-master/downloads/geos-3.6.2.tar.bz2
-- Applying patch F:/OSG/VCPKG/vcpkg-master/ports/geos/geos_c-static-support.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: F:/OSG/VCPKG/vcpkg-master/buildtrees/geos/x86-windows-rel/vcpkg-parallel-configure
    See logs for more information:
      F:\OSG\VCPKG\vcpkg-master\buildtrees\geos\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:246 (vcpkg_execute_required_process)
  ports/geos/portfile.cmake:32 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)

**Error: Building package geos:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: geos:x86-windows
  Vcpkg version: 0.0.113-nohash**

Additionally, attach any relevant sections from the log files above.

-- Configuring errors occurred!
-- Looking for include file ieeefp.h
-- Looking for include file ieeefp.h - not found
-- Performing Test HAVE_STD_ISNAN
-- Performing Test HAVE_STD_ISNAN - Failed
-- Performing Test HAVE_STD_ISFINITE
-- Performing Test HAVE_STD_ISFINITE - Failed
(I only list the errors.)
CMake Error at include/CMakeLists.txt:57 (GenerateSourceGroups):
  Unknown CMake command "GenerateSourceGroups".

So I want someone to tell me how to fix the problem?

**Comment by hlysunnaram** [comment]
A fix is on its way in PR #4433 
It is being checked and it should be merged soon.

**Comment by ras0219-msft** [comment]
Fix is merged; @Anzai1028 could you let us know if that doesn't fix your issue so we can reopen this?

**Comment by Anzai1028** [comment]
The issue was fixed by chaning the geos' version to  3.6.3.
