### ISSUE TITLE
Make vcpkg.targets more defensive w.r.t. the naming of build configurations

### ISSUE THREAD

**Issue by FrankHeimes** [microsoft/vcpkg#4454]
I'm using Visual Studio 2017 with the vcpkg integration to build my projects.
The `vcpkg/scripts/buildsystems/msbuild/vcpkg.targets` file is of version #3504, 8. Aug. 2018.

Besides the well known build configurations `Debug` and `Release`, I also use other names that prefix or suffix additional words, like `Test Debug` or `Debug CLR`. In my project settings, I examine the configuraion name to automatically adjust certain project settings.

The problem with vcpkg is that the condition `$(VcpkgConfiguration.StartsWith('Debug'))` does match some cases, but not all. Also, creating the property `$(VcpkgNormalizedConfiguration)` as string and examining it later just to add a sub directory is more verbose than necessary.

I'd like to propose the following:
- Create a property `$(VcpkgConfigSubdir)` that is `'debug\'` if the configuration contains `'Debug'` (case-insensitive) and is empty in all other cases.
- Remove lot's of redundant code by inserting `$(VcpkgConfigSubdir)` into the strings.
- Remove the error message _"Vcpkg is unable to link because we cannot decide between Release and Debug libraries."_ because `$(VcpkgConfigSubdir)` will always be defined and the test cannot fail anymore.

I have prepared a modified version of `vcpkg.targets` that works very well that I'd like to submit.

**Comment by FrankHeimes** [comment]
> ... but decided against it due to names like (_Release_with_debug_symbols_).
> ... non debug named configurations ... (e.g. in cases like: _Deb_Config_)
> In cases where the user defines configurations he should set `$(VcpkgNormalizedConfiguration)` ...

Good point. Having thought about this for a while, I think `$(VcpkgNormalizedConfiguration)` does have a right to exist. But it should be used consistently, i.e. it should replace _all_ occurences of `VcpkgConfiguration.StartsWith('...')`

I'd still suggest using `$(VcpkgConfigSubdir)` as proposed to reduce the redundant code.
I updated my pull request appropriately.

**Comment by zufuliu** [comment]
I think at least `StartsWith()` can be replaced with `Contains()`. e.g:
```
VcpkgConfiguration.Contains('Debug')
VcpkgConfiguration.Contains('Release')
```

or
```
VcpkgConfiguration.ToLowerInvariant().Contains('debug')
VcpkgConfiguration.ToLowerInvariant().Contains('release')
```

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen this issue.
