### ISSUE TITLE
Add Tensorflow & Caffe libraries

### ISSUE THREAD

**Issue by mostafaSataki** [microsoft/vcpkg#4455]
Hi.
Please add Tensorflow & Caffe libraries .

**Comment by Neumann-A** [comment]
Duplicate of:
Tensorflow: #3048
and
Caffe: #294 (Port in #2848?)
Please search before posting issues and close this one.

**Comment by NancyLi1013** [comment]
Hi @mostafaSataki, thanks for posting this issue. Please pay attention to the progress about Tensorfow in #3048 and Caffe in #294.
