### ISSUE TITLE
Failed to build boost-atomic for windows-64bit 

### ISSUE THREAD

**Issue by Anzai1028** [Microsoft/vcpkg#4456]
![image](https://user-images.githubusercontent.com/35988042/46870516-69fae500-ce61-11e8-82d0-f363a828b9c4.png)

how to fix that? 
Error in log file are following:
**failed msvc.write-setup-script F:\OSG\VCPKG\vcpkg-master\buildtrees\boost-atomic\x86-windows-rel\boost\standalone\msvc\b02fc3b7b3ef9737c544f3057df2466b\msvc-setup.bat**

**Comment by Neumann-A** [comment]
shouldn't the title be x86-windows?

Also more details are needed. 
What excatly did you try to instal ? (Due to 2/165)
And what did you already have installed?

**Comment by LarryIII** [comment]
Thanks for your feedback. I installed boost-atomic:x86-windows successfully with VS 2017 15.9.11 + Windows 10, 64 bit machine, Please try to use latest vcpkg version and reopen a new issue if it is still a problem for you!
