### ISSUE TITLE
Failed to download  math-boost-1.68.0.tar.gz

### ISSUE THREAD

**Issue by zhang-can-lin** [Microsoft/vcpkg#4459]
Downloading https://github.com/boostorg/math/archive/boost-1.68.0.tar.gz... Failed. Status: 18;"Transferred a partial file"

**Comment by PhoebeHui** [comment]
Hi zhang-can-lin,

I can download the file successfully now, could you have a try? Please close this issue if it's solved.

Thanks,
Phoebe

**Comment by PhoebeHui** [comment]
BTW, which library do you install?

**Comment by LarryIII** [comment]
@zhang-can-lin Thanks for your feedback. We have upgrade boost version to 1.69.0 in VCPKG. Please try to use latest vcpkg version and reopen a new issue if it is still a problem for you!
