### ISSUE TITLE
Cannot extract zip file.

### ISSUE THREAD

**Issue by VincentPT** [Microsoft/vcpkg#4463]
I've tried to install cpprestsdk by following command:

> vcpkg install cpprestsdk cpprestsdk:x64-windows

But it generated an error as bellow.
...
-- Downloading http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portable.zip...
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: D:/Development/ExternalProjects/vcpkg/downloads/strawberry-perl-5.24.1.1-32bit-portable.zip
…

Environment:
Window 10 64 bit
Visual Studio 2017
CMake v3.10.2
vcpkg was pull from GitHub at revision 0178015

**Comment by cdcdx** [comment]
Change vcpkg to the NTFS format disk.

**Comment by LarryIII** [comment]
Thanks for your feedback. I installed cpprestsdk and cpprestsdk:x64-windows successfully with VS 2017 15.9.11, Please try to use latest vcpkg version and reopen a new issue if it is still a problem for you!

**Comment by lkleen** [comment]
It is still failing on a non NTFS formatted disk
