### ISSUE TITLE
Obscure vcpkg/CMake error when "Visual C++ tools for CMake" are not installed

### ISSUE THREAD

**Issue by VioletGiraffe** [microsoft/vcpkg#4470]
I've had a bunch of libraries installed no problem, but then I tried installing openblas, and it failed on the project generation phase. vcpkg output mentioned a log file, which contained the following CMake error: `Visual Studio 15 2017 could not find any instance of Visual Studio`. Some googling lead me to a solution: install "Visual C++ tools for CMake" through the VS 2017 installer.

Couldn't vcpkg parse the logs to detect this specific error in order to suggest a solution, to save the users some time and effort?

**Comment by degski** [comment]
@VioletGiraffe Yes, it could, vcpkg is open source and any PR, deemed useful, will be merged after CLA signing. I'm watching this space.

**Comment by JackBoosY** [comment]
Now, vcpkg will install cmake automaticlly when cmake not found.
