### ISSUE TITLE
ZLIB: CMake integration test failed

### ISSUE THREAD

**Issue by sum-catnip** [Microsoft/vcpkg#4485]
so im trying to install a package using zlib. The cmake integration test for zlib fails and i stops the package installation with the error: 

```
CMake Error at scripts/cmake/vcpkg_test_cmake.cmake:51 (message):
  CMake integration test failed; unable to find_package(ZLIB MODULE REQUIRED)
Call Stack (most recent call first):
  ports/zlib/portfile.cmake:47 (vcpkg_test_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package zlib:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x64-windows-static
  Vcpkg version: 0.0.113-nohash
```

i started checking the logfiles and the one that failed (test-cmake-x64-windows-static-out.log) only contained:

```
-- Building for: Visual Studio 15 2017
-- Configuring incomplete, errors occurred!
See also "E:/Programme/vcpkg/buildtrees/zlib/x64-windows-static-test/CMakeFiles/CMakeOutput.log".
```

then i went to the provided path and was presented with even fewer information:

```
The system is: Windows - 10.0.17134 - AMD64
```

also i checked all the used paths (cmake, msbuild, cl) and they all seem to be correct. Im very confused at this point.

**Comment by sum-catnip** [comment]
also doing a simple cmake . in the x64-windows-test folder works just fine...

```
PS E:\Programme\vcpkg\buildtrees\zlib\x64-windows-test> cmake .
-- The C compiler identification is MSVC 19.15.26730.0
-- The CXX compiler identification is MSVC 19.15.26730.0
-- Check for working C compiler: E:/Programme/VisualStudio/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x86/cl.exe
-- Check for working C compiler: E:/Programme/VisualStudio/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
--
 Check for working CXX compiler: E:/Programme/VisualStudio/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: E:/Programme/VisualStudio/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: E:/Programme/vcpkg/packages/zlib_x64-windows/lib/zlib.lib (found version "1.2.11")
-- Configuring done
-- Generating done
-- Build files have been written to: E:/Programme/vcpkg/buildtrees/zlib/x64-windows-test
```

**Comment by sum-catnip** [comment]
i just found out this is a .net problem (hence why msbuild couldn't run). my bad

**Comment by sum-catnip** [comment]
ok so the thing i fucked up was having my "developmentMode" set to true cuz i used .NET reflector sum time ago. So there is a file in C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v<version> where u can set the "developmentMode" to true or false. You need to disable it for each version. Unfortunately i forgot the name of the file so if this is actually the problem your facing you'll need to do some research. If you want to be sure this is actually your problem you can check the enviroment variables for a DevPath. If you want hlp you can hit me up on discord at catnip#0420

**Comment by superdopenoob** [comment]
Hello,sum-catnip,thank you for replying me.In fact,this problem only occurrs when I tried to install the SFML library to test if my vcpkg works properly,but actually what I really need is box2d library and box2d's installation has no problem.So I think I'll come back later and put away this problem right now.But I have saved your solution as a file inside my computer,thank you,my friend.
