### ISSUE TITLE
[cgal] Missing CGALExports.cmake

### ISSUE THREAD

**Issue by TheScarfix** [Microsoft/vcpkg#4490]
Can't use the current version of cgal from vcpkg. CMake throws this error:
CMake Error at C:/dev/vcpkg/installed/x64-windows/lib/cgal/CGALConfig.cmake:81 (include):
include could not find load file:
C:/dev/vcpkg/installed/x64-windows/lib/cgal/CGALExports.cmake

**Comment by jjpepper** [comment]
We are seeing the same issue.  Did you find a solution @TheScarfix ?

**Comment by TheScarfix** [comment]
I think it was fixed with #4655
