### ISSUE TITLE
Error Building package bzip2:x86-windows failed with BUILD_FAILED

### ISSUE THREAD

**Issue by DragonOsman** [Microsoft/vcpkg#4498]
I was trying to install Boost using `vcpkg`, and I got the following message at the end:
```
Error: Building package bzip2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x86-windows
  Vcpkg version: 0.0.113-nohash

Additionally, attach any relevant sections from the log files above.
```
I don't know what log files to show if there are any, but there's also this from the output:
```
Building package bzip2[core]:x86-windows...
-- Using cached C:/vcpkg/downloads/bzip2-1.0.6.tar.gz
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:91 (message):


  File does not have expected hash:

          File path: [ C:/vcpkg/downloads/bzip2-1.0.6.tar.gz ]
      Expected hash: [ 00ace5438cfa0c577e5f578d8a808613187eff5217c35164ffe044fbafdfec9e98f4192c02a7d67e01e5a5ccced630583ad1003c37697219b0f147343a3fdd12 ]
        Actual hash: [ a9479bf44d186229ec02d4f91a712f9a196e27c6ad3d41eb086592fb326cf87c552376301db3d4244b29e2b3a6eb00549d6d04908819bea8cf9ee36754e6c1b5 ]

  Please delete the file and retry if this file should be downloaded again.
```
Should I delete `bzip2-1.0.6.tar.gz ` and download it again?  And what else do I need to do?  Please help.  Thanks in advance.

**Comment by NancyLi1013** [comment]
@DragonOsman, thank you for posting this issue. From the above log , we can see that it is because the hash is not correct. Does this issue persist on your machine now? If the error is the same as before, please modify the hash and then try to download it again.

**Comment by PhoebeHui** [comment]
@DragonOsman, thanks for posting this issue!

We can't reproduce this issue locally, please try vcpkg latest revision, and open a new issue if this is still a problem for you.
