### ISSUE TITLE
libpopt port

### ISSUE THREAD

**Issue by simon-p-r** [Microsoft/vcpkg#4506]
The lipopt has no usage instructions and does not working when built dynamically.

**Comment by wangli28** [comment]
@simon-p-r, thank you for posting the issue, does the issue still occur? I installed it successfully with VS2017 15.9.11 and VCPKG latest source.

> .\vcpkg.exe install libpopt
The following packages will be built and installed:
    libpopt[core]:x86-windows
Starting package 1/1: libpopt:x86-windows
Building package libpopt[core]:x86-windows...
-- Downloading http://rpm5.org/files/popt/popt-1.16.tar.gz...
-- Extracting source F:/b/vcpkg/downloads/popt-1.16.tar.gz
-- Applying patch F:/b/vcpkg/ports/libpopt/patches/0004-vcpkg-fixmsvc.patch
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package libpopt[core]:x86-windows... done
Installing package libpopt[core]:x86-windows...
Installing package libpopt[core]:x86-windows... done
Elapsed time for package libpopt:x86-windows: 17.49 s
\
Total elapsed time: 17.49 s

**Comment by simon-p-r** [comment]
I have re-tried and it installs now.
