### ISSUE TITLE
How to work with an already downloaded source code distribution

### ISSUE THREAD

**Issue by Toninoso** [Microsoft/vcpkg#4555]
Hi,
I have a proxy in the office with the result that some packages get downloaded and built with no issues, but other fail in download phase. I can still get the package but I need to contact my IT department and they acquire it for me. 

Is there a way to install a package that was already downloaded? 

BTW below is the error that I get. Note that HTTPS_PROXY and HTTP_PROXY are both set on my machine and other packages get downloaded as expected - I can also download freetype package tar.bz2 file via the browser but proxy somehow prevents vcpkg download from freetype mirror site):

E:\Source\Repos\VcPkg>vcpkg install freetype:x64-windows
The following packages will be built and installed:
    freetype[core]:x64-windows
Starting package 1/1: freetype:x64-windows
Building package freetype[core]:x64-windows...
-- Downloading https://download-mirror.savannah.gnu.org/releases/freetype/freetype-2.8.1.tar.bz2...
-- Downloading https://download-mirror.savannah.gnu.org/releases/freetype/freetype-2.8.1.tar.bz2...
Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:156 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/freetype/portfile.cmake:4 (vcpkg_download_distfile)
  scripts/ports.cmake:71 (include)

Error: Building package freetype:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: freetype:x64-windows
  Vcpkg version: 2018.10.20-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by Toninoso** [comment]
Just dropping freetype-2.8.1.tar.bz2 file in vcpkg downloads folder was enough. It would be nice for this to be documented, or if it is, easier to find in the docs.

**Comment by votecoffee** [comment]
Sometimes you also have to add a prefix to the filename such as: msys-
