### ISSUE TITLE
Allow LLVM toolset

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#4567]
So i tried to make my own triplet and simply copied it and renamed it to x64-windows-llvm and added the line 
`set(VCPKG_PLATFORM_TOOLSET llvm)`
and/or (tried all three possibilities)
`set(CMAKE_VS_PLATFORM_TOOLSET llvm)`

only to be greeted by a error of vcpkg that the toolset is not available because it could not be found. (Although it is installed and useable.)

The problem lies within the source of vcpkg itself which seems to have hardcoded toolset candidates. 
The error is most likely in vcpkgpaths.cpp on line 154 (or/and line 141)
`Util::stable_keep_if(candidates, [&](const Toolset* t) { return *tsv == t->version; });`
*tsv is the toolset string and it is compared to the version of a candidates list. For llvm this obviously fails. 
(LLVM != v141)
Unfortunally, this candidate list is hardcoded. In my opinion the right thing to do is to parse the available toolsets from the folder: (at least for vs2017)
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Platforms`
(or whereever VS has been installed)
 or remove the check completly since it will fail the build anyway. (Although most likely not with a nice error message)

**Comment by psteinb** [comment]
After tinkering around, I ended up editing the portfile for the software I wanted to compile/link with the llvm toolset. I played a bit with toolchain files but came to the same conclusions as @Neumann-A. `VCPKG_PLATFORM_TOOLSET` doesn't work as it is checked against a list of candidates that apparently aren't updated. :-1: 
I tried to add `set(CMAKE_GENERATOR_TOOLSET "llvm" CACHE STRING "Platform Toolset" FORCE)` to the triplet file, but this is apparently not honored by `vcpkg_configure_cmake` in the `portfile.cmake`. It would be nice to tackle this.
The next level of the catastrophe I found, was that ninja (`ninja 1.9.0` was in `PATH` for me) throws an error for the `llvm` toolset in my case.
```
cmd /c "cd .. && "C:/Users/steinbac/software/vcpkg/repo/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe" "C:/Users/steinbac/software/vcpkg/repo/buildtrees/tiff/src/4.0.10-fc1d67d447" "-DCMAKE_GENERATOR_TOOLSET=llvm" "-DBUILD_TOOLS=OFF" "-DBUILD_DOCS=OFF" "-DBUILD_CONTRIB=OFF" "-DBUILD_TESTS=OFF" "-Djbig=OFF" "-Djpeg12=OFF" "-Dwebp=OFF" "-Dzstd=OFF" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/steinbac/software/vcpkg/repo/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/steinbac/software/vcpkg/repo/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/Users/steinbac/software/vcpkg/repo/packages/tiff_x64-windows""
-- Building tiff version 4.0.10
-- libtiff library version 5.4.0
CMake Error at CMakeLists.txt:71 (project):
  Generator

    Ninja

  does not support toolset specification, but toolset

    llvm

  was specified.


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
``` 
I reproduced this with raw cmake calls, so it appears to be downstream and not vcpkg related.

**Comment by Abhipray** [comment]
@psteinb Can you share what changes you made to your portfile to get it to compile with llvm?

**Comment by Neumann-A** [comment]
A Note about Ninja:
The Ninja generator does not know anything about VS Toolsets.  Try setting  CMAKE_C_COMPILER and CMAKE_CXX_COMPILER for Ninja instead. In #4609 i used a dummy call to the VS Generator with the toolset to identify/get the path to the C and CXX Compiler as well as the linker.

**Comment by Neumann-A** [comment]
https://github.com/Neumann-A/my-vcpkg-triplets
has a working llvm triplet although not all ports support switching to clang-cl
