### ISSUE TITLE
vcpkg does not work for google test

### ISSUE THREAD

**Issue by mmatrosov** [Microsoft/vcpkg#457]
Please, take a look at http://stackoverflow.com/questions/41315739/vcpkg-does-not-work-for-google-test

**Comment by traversaro** [comment]
I think that the autolinking behavior has been intentionally disabled for `gtest`, see https://github.com/Microsoft/vcpkg/issues/306 and the relative commit https://github.com/Microsoft/vcpkg/commit/61e484a640884bc33ae3754f98006ebb1b4c1f1f . What is missing is probably documentation on the libraries (I guess just gtest) that are not automatically linked.

**Comment by ras0219-msft** [comment]
To reiterate the relevant details from #306: Google Test is designed in such a way that as a user, you _must_ make an application specific decision at link-time. Therefore, we can't automatically choose which `gtest.lib`, `gmock.lib`, etc you want linked (they are mutually exclusive).

**Comment by mmatrosov** [comment]
Ok, I see, thanks for the link!
