### ISSUE TITLE
BUILD_FAILED when install opencv contrib for x86-UWP version!

### ISSUE THREAD

**Issue by matthewgan** [Microsoft/vcpkg#4574]
c:\Users\migan>git clone https://github.com/Microsoft/vcpkg
Cloning into 'vcpkg'...
remote: Enumerating objects: 218, done.
remote: Counting objects: 100% (218/218), done.
remote: Compressing objects: 100% (155/155), done.
remote: Total 46105 (delta 84), reused 154 (delta 63), pack-reused 45887
Receiving objects: 100% (46105/46105), 10.18 MiB | 6.53 MiB/s, done.
Resolving deltas: 100% (29899/29899), done.
Checking out files: 100% (2711/2711), done.

c:\Users\migan>cd vcpkg

c:\Users\migan\vcpkg>bootstrap-vcpkg.bat

Building vcpkg.exe ...

  pch.cpp
  archives.cpp
  checks.cpp
  chrono.cpp
  cofffilereader.cpp
  downloads.cpp
  enums.cpp
  files.cpp
  hash.cpp
  lineinfo.cpp
  machinetype.cpp
  stringrange.cpp
  strings.cpp
  system.cpp
  binaryparagraph.cpp
  build.cpp
  commands.autocomplete.cpp
  commands.buildexternal.cpp
  commands.cache.cpp
  commands.ci.cpp
  commands.contact.cpp
  commands.cpp
  commands.create.cpp
  commands.dependinfo.cpp
  commands.edit.cpp
  commands.env.cpp
  commands.exportifw.cpp
  commands.import.cpp
  commands.integrate.cpp
  commands.list.cpp
  commands.owns.cpp
  commands.portsdiff.cpp
  commands.search.cpp
  commands.upgrade.cpp
  commands.version.cpp
  commands.xvsinstances.cpp
  dependencies.cpp
  export.cpp
  globalstate.cpp
  help.cpp
  input.cpp
  install.cpp
  metrics.cpp
  packagespec.cpp
  packagespecparseresult.cpp
  paragraphparseresult.cpp
  paragraphs.cpp
  parse.cpp
  postbuildlint.buildtype.cpp
  postbuildlint.cpp
  remove.cpp
  sourceparagraph.cpp
  statusparagraph.cpp
  statusparagraphs.cpp
  tools.cpp
  triplet.cpp
  update.cpp
  userconfig.cpp
  vcpkgcmdarguments.cpp
  vcpkglib.cpp
  vcpkgpaths.cpp
  versiont.cpp
  visualstudio.cpp
  vcpkglib.vcxproj -> C:\Users\migan\vcpkg\toolsrc\Release\vcpkglib.lib
  vcpkg.cpp
  Generating code
  All 15262 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  vcpkg.vcxproj -> C:\Users\migan\vcpkg\toolsrc\Release\vcpkg.exe
  vcpkgmetricsuploader.cpp
  Generating code
  All 5476 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  vcpkgmetricsuploader.vcxproj -> C:\Users\migan\vcpkg\toolsrc\Release\vcpkgmetricsuploader.exe

Building vcpkg.exe... done.

c:\Users\migan\vcpkg>vcpkg integrate install
Applied user-wide integration for this vcpkg root.

All MSBuild C++ projects can now #include any installed libraries.
Linking will be handled automatically.
Installing new libraries will make them instantly available.

CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=c:/Users/migan/vcpkg/scripts/buildsystems/vcpkg.cmake"

c:\Users\migan\vcpkg>vcpkg install opencv[contrib]:x86-uwp --recurse
The following packages will be built and installed:
  * eigen3[core]:x86-uwp
  * libjpeg-turbo[core]:x86-uwp
  * liblzma[core]:x86-uwp
  * libpng[core]:x86-uwp
    opencv[contrib,core,eigen,flann,jpeg,opengl,png,tiff]:x86-uwp
  * opengl[core]:x86-uwp
  * tiff[core]:x86-uwp
  * zlib[core]:x86-uwp
Additional packages (*) will be modified to complete this operation.
Starting package 1/8: liblzma:x86-uwp
Building package liblzma[core]:x86-uwp...
A suitable version of cmake was not found (required v3.11.4). Downloading portable cmake v3.11.4...
Downloading cmake...
Downloading cmake... done.
Extracting cmake...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
Downloading 7zip... done.
Extracting 7zip...
A suitable version of nuget was not found (required v4.6.2). Downloading portable nuget v4.6.2...
Downloading nuget...
Downloading nuget... done.
Extracting 7zip... done.
Extracting cmake... done.
-- Downloading https://github.com/xz-mirror/xz/archive/v5.2.4.tar.gz...
-- Extracting source C:/Users/migan/vcpkg/downloads/xz-mirror-xz-v5.2.4.tar.gz
-- Using source at C:/Users/migan/vcpkg/buildtrees/liblzma/src/v5.2.4-0e2feaf554
-- Applying patch C:/Users/migan/vcpkg/ports/liblzma/enable-uwp-builds.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Configuring x86-uwp
-- Building x86-uwp-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: C:/Users/migan/vcpkg/downloads/tools/cmake-3.11.4-windows/cmake-3.11.4-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No
    Working Directory: C:/Users/migan/vcpkg/buildtrees/liblzma/x86-uwp-dbg
    See logs for more information:
      C:\Users\migan\vcpkg\buildtrees\liblzma\install-x86-uwp-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/liblzma/portfile.cmake:25 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package liblzma:x86-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: liblzma:x86-uwp
  Vcpkg version: 2018.10.20-nohash

Additionally, attach any relevant sections from the log files above.

c:\Users\migan\vcpkg>vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

c:\Users\migan\vcpkg>git pull
Already up to date.

c:\Users\migan\vcpkg>vcpkg install opencv[contrib]:x86-uwp --recurse
The following packages will be built and installed:
  * eigen3[core]:x86-uwp
  * libjpeg-turbo[core]:x86-uwp
  * liblzma[core]:x86-uwp
  * libpng[core]:x86-uwp
    opencv[contrib,core,eigen,flann,jpeg,opengl,png,tiff]:x86-uwp
  * opengl[core]:x86-uwp
  * tiff[core]:x86-uwp
  * zlib[core]:x86-uwp
Additional packages (*) will be modified to complete this operation.
Starting package 1/8: liblzma:x86-uwp
Building package liblzma[core]:x86-uwp...
-- Using cached C:/Users/migan/vcpkg/downloads/xz-mirror-xz-v5.2.4.tar.gz
-- Using source at C:/Users/migan/vcpkg/buildtrees/liblzma/src/v5.2.4-0e2feaf554
-- Applying patch C:/Users/migan/vcpkg/ports/liblzma/enable-uwp-builds.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Configuring x86-uwp
-- Building x86-uwp-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: C:/Users/migan/vcpkg/downloads/tools/cmake-3.11.4-windows/cmake-3.11.4-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No
    Working Directory: C:/Users/migan/vcpkg/buildtrees/liblzma/x86-uwp-dbg
    See logs for more information:
      C:\Users\migan\vcpkg\buildtrees\liblzma\install-x86-uwp-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/liblzma/portfile.cmake:25 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package liblzma:x86-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: liblzma:x86-uwp
  Vcpkg version: 2018.10.20-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by matthewgan** [comment]
i tried several times download and rebuild, all results are like the log above.
Please help check what might be wrong here?

**Comment by benzben** [comment]
I'm having the exact same issue!
A solution would be very nice.

**Comment by danielescudero** [comment]
EXACT same problem here. Other devs also having this problem

**Comment by ras0219-msft** [comment]
The branch `dev/roschuma/4574` has a fix and will be checked in to master once we have confirmed it doesn't regress other platforms.

Sorry for the trouble!

**Comment by ras0219-msft** [comment]
A fix has been committed to master. Please let us know if this problem persists after pulling!

**Comment by rdikshit** [comment]
Hi, I am still having the same problem when setting up the Spectator View Native dll : https://microsoft.github.io/MixedReality-SpectatorView/src/SpectatorView.Native/README.html
