### ISSUE TITLE
vcpkg on MSVC and /W4, /Wall

### ISSUE THREAD

**Issue by mcraveiro** [microsoft/vcpkg#4577]
Hi vcpkg developers,

Thanks again for a most excellent tool. I just realised my MSVC build had the default warning level (as opposed to GCC/Clang where I am building with ```-Wall```) and changed it to ```/W4```. However, I now see a lot of warnings coming out of the vcpkg installed libraries like so [1]:

```
c:\third_party\installs\vcpkg-export\installed\x64-windows-static\include\boost\spirit\home\qi\detail\assign_to.hpp(179): warning C4459: declaration of 'attr' hides global declaration (compiling source file C:\projects\dogen\projects\masd.dogen.utility\src\test\json_validator.cpp) [C:\projects\dogen\build\output\msvc\Release\projects\masd.dogen.utility\src\utility.vcxproj
c:\third_party\installs\vcpkg-export\installed\x64-windows-static\include\boost\spirit\home\qi\numeric\detail\numeric_utils.hpp(428): warning C4459: declaration of 'char_type' hides global declaration (compiling source file C:\projects\dogen\projects\masd.dogen.utility\src\test\json_validator.cpp) [C:\projects\dogen\build\output\msvc\Release\projects\masd.dogen.utility\src\utility.vcxproj]
c:\third_party\installs\vcpkg-export\installed\x64-windows-static\include\boost\spirit\home\qi\numeric\detail\numeric_utils.hpp(323): warning C4459: declaration of 'char_type' hides global declaration (compiling source file C:\projects\dogen\projects\masd.dogen.utility\src\test\json_validator.cpp) [C:\projects\dogen\build\output\msvc\Release\projects\masd.dogen.utility\src\utility.vcxproj]
<snip>
```

Shouldn't vcpkg be setting these libraries into some kind of "system includes"? I am not entirely familiar with MSVC but in the GCC/Clang world there is the notion of some includes not contributing to the warnings. I'll continue to investigate but in the mean time any pointers are greatly appreciated.

Many thanks

Marco

[1] https://my.cdash.org/viewBuildError.php?type=1&buildid=1550111

**Comment by mcraveiro** [comment]
OK, I'm sure I'm reading this wrong :-) but as far as I can see, system headers (i.e. ignore warnings from third parties) are a relatively new feature in VS! [1] If I really understood this correctly, it also means CMake is yet to add support for this feature [2]. Presumably, it is possible to add it manually via some hack - however, I don't quite understand how ```vcpkg.cmake``` works; if I could find the place where the include path is being updated perhaps it could be coerced to use this new flag...

[1] https://blogs.msdn.microsoft.com/vcblog/2017/12/13/broken-warnings-theory/
[2] https://gitlab.kitware.com/cmake/cmake/issues/17904

**Comment by OlafvdSpek** [comment]
Hiding warnings in third-party headers might not be a good idea.. especially in template code where the warning might be caused by a type you specified.

**Comment by mcraveiro** [comment]
Ah good point, maybe that's not a good default setting. Sorry, I'm not too sure how things work in MSVC-land - in GCC-land this has been in place for a long time so its a common thing. I assume GCC does the right thing and not ignore your own code when its part of a template expansion - but to be fair I am not sure that is the case and I hadn't even thought about it before.

At any rate, at present I cannot use ```/Wall /WX``` or even ```/W4``` because I am getting so many warnings that its impossible to see anything (I think more than a thousand at least, and all of them seem to come from Boost etc). I have zero warnings on GCC and Clang with ```-Werror -Wall``` with the same vcpkg libraries. So, for my particular case, I am more than willing to trade missing a couple of errors due to template expansion against not having any warnings at all.

So I guess the final conclusion is, it would be nice to have a flag "ignore warnings on vcpkg libraries" that is off by default but can be switched on in user projects via a ```-D``` parameter. Exact name of the flag needs thinking, of course :-)

**Comment by OlafvdSpek** [comment]
>  I assume GCC does the right thing

It doesn't, yet. 

`/W4` on MSVC might have too many false positives to be usable anyway.

**Comment by mcraveiro** [comment]
Interestingly, MS research points out that it is being used in the wild [1]:

```
In our Diagnostics Improvements Survey, 15% of 270 respondents indicated they build their code with /Wall /WX indicating they have a zero tolerance for any warnings. Another 12% indicated they build with /Wall, which implies /W4 with all off-by-default warnings enabled. Another 30% build with /W4. These were disjoint groups that altogether make 57% of users that have stricter requirements to code than the default of Visual Studio IDE – /W3 or the compiler by itself – /W1. These levels are somewhat arbitrary and in no way represent our own practices. The MSVC libraries team, for example, strives hard to have all our libraries be /W4 clean.
```

Given this, I wouldn't mind giving it a go, if the warnings were only on my code.

[1] https://blogs.msdn.microsoft.com/vcblog/2017/12/13/broken-warnings-theory/

**Comment by MikeGitb** [comment]
> /W4 on MSVC might have too many false positives to be usable anyway.

Not at all. We use it in most of our projects. Are you mixing it up with /Wall?

**Comment by mcraveiro** [comment]
@MikeGitb do you use vcpkg as well? And if so, did you not experience a flurry of warnings coming out of vcpkg installed libraries? Maybe I'm doing something wrong :-)

**Comment by ras0219-msft** [comment]
One thing to consider is to use `#pragma` statements to change the warning level around external code[1].

```cpp
#pragma warning( push, 1 )  
#include <boost/all.hpp>
#include <openssl.h>
#pragma warning( pop )  
```

This will set the global warning level to /W1 while including the external headers, but restore it to whatever you had on the command line before continuing. I personally prefer this method, because it moves configuration out of the buildsystem(s) and into code (which is easier to manage for me).

[1] https://msdn.microsoft.com/en-us/library/2c8f766e.aspx

**Comment by mcraveiro** [comment]
Thanks @ras0219-msft, I think for those targeting mainly windows this sounds like a good approach. However for those like me coming from a Linux viewpoint we'd rather not change a lot of code just to cater for MSVC. What would be really nice for our use case is something like the /external parameter. Do you think vcpkg could support this? Maybe optionally perhaps... I looked at the CMake code but unfortunately i could not figure out where the includes get set.

**Comment by mcraveiro** [comment]
Ah I see. Unfortunately this is not ideal for my set up; I was hoping to use a single level of warnings across the board like I do for GCC/Clang. Lets hope someone with knowledge of vcpkg internals can locate the place in the script where the includes are being made - I suspect this is a very small change, something like (pseudo code):

```
if (VCPKG_INCLUDE_WITH_EXTERNAL)
    set(include_command "/external")
else()
    set(include_command "/[current include command]")
endif()
...
```

We may also want to detect the VS version to ensure ```/external``` is supported I guess.

**Comment by OlafvdSpek** [comment]
> > /W4 on MSVC might have too many false positives to be usable anyway.
> 
> Not at all. We use it in most of our projects. Are you mixing it up with /Wall?

No, though:
- I think MSVC removed a few warnings
- Libraries got cleaner (less warnings)
- It depends on the type of code / project / style

**Comment by mcraveiro** [comment]
Seems like this was recently discussed in reddit [1] and there are some additional subtleties with MSVC's behaviour.

[1] https://old.reddit.com/r/cpp/comments/9vq3ch/1_year_later_msvcs_isystem_is_still_in_limbo/

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen this issue.

**Comment by atimholt** [comment]
Nothing has occurred to resolve this, and I'm having this problem right now. Please consider this comment a petition to re-open the issue.
