### ISSUE TITLE
spirv-tools will not properly build on non-Win32 systems

### ISSUE THREAD

**Issue by jherico** [Microsoft/vcpkg#4578]
https://github.com/Microsoft/vcpkg/blob/f5c8349a85df6cf9eafe24849fa734102105cb3d/ports/spirv-tools/portfile.cmake#L36

It attempts to GLOB the tool binaries using `*.exe`, which works on Windows platforms, but will find nothing on other platforms where the `.exe` extension isn't used.  The cmake will then error out on the line `file(REMOVE ${EXES})` which expects more than one argument.

The correct solution would seem to be changing the GLOB pattern from `*.exe` to just `*`.

**Comment by PhoebeHui** [comment]
@jherico, thank you for posting this issue!
This issue should fixed by commit https://github.com/Microsoft/vcpkg/commit/04263dd7a435030e2e87b0ab12432d14a0747c5c, currently spirv-tools installed successfully on Linux.
