### ISSUE TITLE
Not clear how to include header files from installed packages

### ISSUE THREAD

**Issue by harrywye** [Microsoft/vcpkg#458]
I've tried boost and eigen3. Neither installs CMake config.cmake file (and, hence find_package() does not work). How do you set include path for this type of packages?

**Comment by ras0219-msft** [comment]
For libraries that don't su

**Comment by harrywye** [comment]
Thanks for the tips, @ras0219-msft! That solved the Eigen issue. (I'm new to cmake, and in fact, I'm just trying to get back to C++ development after a long hiatus.) find_package() turned out to work for boost (via FindBoost.cmake?) without having to manually search for paths (using cmake preset variables).

What's still not clear to me is, why do I have to set the include/lib paths for every pkg I use in every project I work on? (Or, do I?) It appears that header/lib/dll files of all pkgs are installed under the same locations under %VCPKG_ROOT%, and I would expect the include/lib paths should be automatically set (by vcpkg).... I don't see that behavior for the few packages I've tried so far, boost, eigen3, opencv, lua, etc. It seems like I always have to explicitly set include/lib paths in my project cmake files. Thanks for the help!
