### ISSUE TITLE
Installation of openexr fails when there are spaces in vcpkg base directory

### ISSUE THREAD

**Issue by hitsfromdabong** [Microsoft/vcpkg#4588]
Just tried to install openexr with vcpkg in the process of installing Meshroom.

The compilation failed everytime. Unfortunately I do not have the error message right now, but it said something along the lines "ninja;-v": invalid command; also there was an error about a path, which didn't exist, where the latter part of the path started at the space in the name of my home directory.

There are numerous other reports of users experiencing this issue with other packages.

Installation went through without any error after creating another user with no spaces in his home directory.

A fix would be gratefully appreciated!

**Comment by LarryIII** [comment]
This issue should be fixed because I installed openexr successfully with a space path. Please re-open this issue if it is still an issue for you!
