### ISSUE TITLE
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:156 (message)

### ISSUE THREAD

**Issue by lamontu** [Microsoft/vcpkg#4591]
Additional packages (*) will be modified to complete this operation.
Starting package 1/80: gflags:x64-windows
Building package gflags[core]:x64-windows...
-- Downloading https://github.com/gflags/gflags/archive/v2.2.1.tar.gz...
-- Downloading https://github.com/gflags/gflags/archive/v2.2.1.tar.gz... Failed. Status: 35;"SSL connect error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:156 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:108 (vcpkg_download_distfile)
  ports/gflags/portfile.cmake:7 (vcpkg_from_github)
  scripts/ports.cmake:71 (include)

Error: Building package gflags:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: gflags:x64-windows
  Vcpkg version: 2018.10.20-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by lamontu** [comment]
PS> [Environment]::SetEnvironmentVariable("HTTP_PROXY", "https://user:password@your-proxy-ip-address:port/")

**Comment by kartikkhullar** [comment]
I am not using any proxy server, what could be wrong ?
