### ISSUE TITLE
Capitalization in CMake targets: Preserve case or not?

### ISSUE THREAD

**Issue by ShinNoNoir** [microsoft/vcpkg#4594]
I'm currently working on creating a port and noticed that after installing a library, vcpkg reports which CMake targets are provided, e.g.:
```
The package liblas:x86-windows provides CMake targets:

    find_package(liblas CONFIG REQUIRED)
    target_link_libraries(main PRIVATE liblas liblas_c)
```

A quick glance at `vcpkg/install.cpp` shows that it gets this information by scanning for `*-config.cmake` (or `*Config.cmake`). In case of libLAS, it provides the file `liblas-config.cmake`. However, the accompanying file `liblas-config-version.cmake` checks the exact spelling and enforces that users should use `find_package(libLAS)` instead. _This means that the information that vcpkg reports after installing certain libraries might be incorrect._

Currently I see the following options of addressing this issue:

* Rename the `.cmake` files such that they match the required spelling for `find_package`.
* Patch out the strict spelling enforcement in the `*config-version.cmake` file.

Are there any other solutions? Any other thoughts?

**Comment by ShinNoNoir** [comment]
I've had issues with other ports before when it came to debug targets; it's something I'll usually check and try to fix.

**Comment by ras0219-msft** [comment]
>Rename the .cmake files such that they match the required spelling for find_package.

This is the right answer (specifically just the main config file). When you write `find_package(xYz)`, CMake will search for `share/xyz/xYz-config.cmake` (among others). Therefore, if liblas wants to be found via `find_package(libLAS)`, we should name the config file `share/liblas/libLAS-config.cmake`.

**Comment by ShinNoNoir** [comment]
Still working (slowly in my spare time) on a portfile. I'm not too well-versed in CMake, but I came up with the following renaming snippet:

```
# Fix capitalization of cmake files: liblas -> libLAS
foreach(BUILD_TYPE "/debug" "")
    file(GLOB CMAKE_FILES "${CURRENT_PACKAGES_DIR}${BUILD_TYPE}/cmake/*.cmake")
    foreach(CMAKE_FILE IN LISTS CMAKE_FILES)
        string(REPLACE "liblas" "libLAS" CMAKE_FILE_PROPERLY_CASED "${CMAKE_FILE}")
        file(RENAME ${CMAKE_FILE} ${CMAKE_FILE_PROPERLY_CASED})
    endforeach()
endforeach()
```

**Comment by ShinNoNoir** [comment]
Hmm, which is not perfect either, since some of the `.cmake` files try to include other `liblas*.cmake` files. Now, for a Windows environment with a case-insensitive file system, this isn't an issue, but it is for other OSes (e.g. Linux). Maybe only `liblas-config.cmake` and `liblas-config-version.cmake` need to be renamed, but that might cause `print_cmake_information` to report both _libLAS_ and _liblas_ as available targets.

**Comment by NancyLi1013** [comment]
Hi @ShinNoNoir  thanks for posting this issue. Now `liblas `has been added to vcpkg. Please try to update vcpkg and use it. Please reopen a new issue if you have any problems using this port.
