### ISSUE TITLE
Error: Building package libvpx:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by fawdlstty** [Microsoft/vcpkg#4598]
PS E:\Github\vcpkg> vcpkg install libvpx:x64-windows libvpx:x64-windows-static
The following packages will be built and installed:
    libvpx[core]:x64-windows
    libvpx[core]:x64-windows-static
Starting package 1/2: libvpx:x64-windows
Building package libvpx[core]:x64-windows...
Warning: The following VS instances are excluded because the English language pack is unavailable.
    E:\Program Files (x86)\
Please install the English language pack.
-- Warning: Dynamic building not supported by libvpx yet. Building static.
-- Using cached E:/Github/vcpkg/downloads/libvpx-1.7.0.tar.gz
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- PERL_EXE_PATH ; E:/Github/vcpkg/downloads/tools/perl/perl/bin
-- Generating makefile
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: E:/Github/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe;--noprofile;--norc;E:/Github/vcpkg/buildtrees/libvpx/src/libvpx-1.7.0/configure;--target=x86_64-win64-vs15;--disable-examples;--disable-tools;--disable-docs
    Working Directory: E:/Github/vcpkg/buildtrees/libvpx/x64-windows
    See logs for more information:
      E:\Github\vcpkg\buildtrees\libvpx\configure-x64-windows-out.log

Call Stack (most recent call first):
  ports/libvpx/portfile.cmake:58 (vcpkg_execute_required_process)
  scripts/ports.cmake:71 (include)

Error: Building package libvpx:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libvpx:x64-windows
  Vcpkg version: 2018.10.20-nohash

Additionally, attach any relevant sections from the log files above.
PS E:\Github\vcpkg>

**Comment by fawdlstty** [comment]
libvpx:x64-windows-static、x86-windows、x86-windows-static      build failed too

**Comment by ras0219-msft** [comment]
Thanks for posting this issue!

Could you attach the log file?
>E:\Github\vcpkg\buildtrees\libvpx\configure-x64-windows-out.log

**Comment by fawdlstty** [comment]
diff missing: Try installing diffutils via your package manager.

Configuration failed. This could reflect a misconfiguration of your
toolchains, improper options selected, or another problem. If you
don't see any useful error messages above, the next step is to look
at the configure error log file (config.log) to determine what
configure was trying to do when it died.

**Comment by fawdlstty** [comment]
i can't solve the question...

**Comment by Joex3** [comment]
Seems to be a problem in the [vcpkg_acquire_msys](https://vcpkg.readthedocs.io/en/latest/maintainers/vcpkg_acquire_msys/) function. The command `diff --version` for example does nothing after acquiring (though it is listed as a dependency in the portfile for libvpx and a diff.exe exists after the installation).

A simple hotfix for now (I don't feel competent enough to do a pull request) is to manually update the msys core system. To do this open up the mingw[32/64] shell located at `%VCPKG_ROOT%\downloads\tools\msys2\msys64\mingw[32/64].exe` (with %VCPKG_ROOT% being the root directory of your vcpkg installation, e.g. `C:\vcpkg`). Now update all packages using `pacman -Syuu` and follow the instructions on screen (you have to force-quit the shell afterwards and execute the command again for some reason).

While not ideal, at least that gets it to a stage where the package is usable.

**Comment by fawdlstty** [comment]
thanks, but I try the solution, can install, but only can use vp8, can't use vp9... @Joex3

**Comment by NancyLi1013** [comment]
@fawdlstty, we cannot reproduce this issue now. Please open a new issue if this is still a problem for you.
