### ISSUE TITLE
CallDepthOverflow

### ISSUE THREAD

**Issue by OlafvdSpek** [Microsoft/vcpkg#460]
Not sure what's happening here..

1>------ Build started: Project: XCC Library, Configuration: Debug Win32 ------
1>  XCC Library.vcxproj -> C:\VC\xcc\xcc\Library\.\Debug\XCC Library.lib
1>  C:\VC\xcc\xcc\Library\Debug\
1>  C:\VC\xcc\xcc\Library\
1>  C:\VC\xcc\xcc\
1>  C:\VC\xcc\
1>  C:\VC\
1>  C:\\
1>  \

<1000 lines>

1>  \
1>  The script failed due to call depth overflow.  The call depth reached 1001 and the maximum is 1000.
1>      + CategoryInfo          : InvalidOperation: (1001:Int32) [], ParentContainsErrorRecordException
1>      + FullyQualifiedErrorId : CallDepthOverflow
1>
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(3965,9): error MSB4023: Cannot evaluate the item metadata "%(Filename)". The item metadata "%(Filename)" cannot be applied to the path "+ CategoryInfo          : InvalidOperation: %281001:Int32%29 [], ParentContainsErrorRecordException". The path is not of a legal form.
2>------ Build started: Project: XCC Mixer, Configuration: Debug Win32 ------
2>LINK : fatal error LNK1104: cannot open file 'libjpeg.lib'
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

PS C:\vc\vcpkg> ./vcpkg install zlib
-- CURRENT_INSTALLED_DIR=C:/VC/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/VC/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/VC/vcpkg/packages/zlib_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/VC/vcpkg/buildtrees/zlib
-- CURRENT_PORT_DIR=C:/vc/vcpkg/ports/zlib/.
-- Using cached C:/VC/vcpkg/downloads/zlib128.zip
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Configuring x86-windows-rel
-- Configuring x86-windows-rel done
-- Configuring x86-windows-dbg
-- Configuring x86-windows-dbg done
-- Package x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: C:/vc/vcpkg/downloads/cmake-3.5.2-win32-x86/bin/cmake.exe;--build;.;--config;Release;--target;instal
l;--;/m
    Working Directory: C:/VC/vcpkg/buildtrees/zlib/x86-windows-rel
    See logs for more information:
      C:\VC\vcpkg\buildtrees\zlib\package-x86-windows-rel-out.log
      C:\VC\vcpkg\buildtrees\zlib\package-x86-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:3 (vcpkg_execute_required_process)
  ports/zlib/portfile.cmake:18 (vcpkg_install_cmake)
  scripts/ports.cmake:73 (include)

Error: building package zlib:x86-windows failed
Please ensure sure you're using the latest portfiles with `vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x86-windows
  Vcpkg version: 0.0.65-unknownhash

Additionally, attach any relevant sections from the log files above.

[config-x86-windows-dbg-err.log.txt](https://github.com/Microsoft/vcpkg/files/672159/config-x86-windows-dbg-err.log.txt)
[config-x86-windows-dbg-out.log.txt](https://github.com/Microsoft/vcpkg/files/672158/config-x86-windows-dbg-out.log.txt)
[package-x86-windows-rel-out.log.txt](https://github.com/Microsoft/vcpkg/files/672160/package-x86-windows-rel-out.log.txt)

**Comment by OlafvdSpek** [comment]
It's not just that machine / that pkg.. other machine, other pkg:

     8>AppLocalFromInstalled:
         C:\VC\vcpkg\buildtrees\libmysql\
         C:\VC\vcpkg\buildtrees\
         C:\VC\vcpkg\
         C:\VC\
         C:\\
         \
         \
         \
         \
         \
         \

**Comment by mojovski** [comment]
same here. 
Its an issue with protobuf: https://gist.github.com/mojovski/791ed14f21b1b8a4c89b39de0f69c9c9

trying to discuss this on the protobuf repository: https://github.com/google/protobuf/issues/2582

**Comment by ras0219-msft** [comment]
The AppLocalFromInstalled target is added by Vcpkg, which indicates this is a problem on our side, not protobuf's.

The powershell call stack error indicates it is very likely to be an issue in the `scripts\buildsystems\msbuild\applocal.ps1` file. I think the problem is if the DLL in question has no dependencies then the script will enter an infinite loop of "Does this directory have any DLL dependencies? Empty string? Ok, let's see if the directory's parent has any dependencies!".

**Comment by ras0219-msft** [comment]
I believe I've fixed this issue, however I was unable to reproduce it locally since it seems to require a very old version of powershell. Please let us know if the problem persists.
