### ISSUE TITLE
find_package(CGAL) Broken

### ISSUE THREAD

**Issue by dapisani** [Microsoft/vcpkg#4614]
When attempting to find_package(CGAL), I get the following error.
_CMake Error at C:/Work/Dev/vcpkg/installed/x64-windows/lib/cgal/CGALConfig.cmake:81 (include):
  include could not find load file:_

Looking in CGALConfig.cmake
    _include(${CGAL_CONFIG_DIR}/CGALExports.cmake)_
is the offending line.
It looks like CGAL_CONFIG_DIR points to the wrong directory. CGALExports is in CGAL_MODULES_DIR.
This is a repeated issue throughout CGALConfig.cmake.

**Comment by jasjuang** [comment]
I think @maxGimeno might be able to help.

**Comment by maxGimeno** [comment]
Actually the right CGAL_DIR to provide is C:/Work/Dev/vcpkg/installed/x86-windows/share/. This way the CGAL_CONFIG_DIR points to the right dir and everything works fine. I'm not sure yet how to fix the CGALConfig.cmake in lib/cgal.
