### ISSUE TITLE
Error: Building package libmysql:x64-linux failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by 678uhb** [microsoft/vcpkg#4616]
The following packages will be built and installed:
    libmysql[core]:x64-linux
Starting package 1/1: libmysql:x64-linux
Building package libmysql[core]:x64-linux...
-- Using cached /root/vcpkg/downloads/mysql-mysql-server-mysql-8.0.4.tar.gz
-- Using source at /root/vcpkg/buildtrees/libmysql/src/ysql-8.0.4-6271934d70
-- Applying patch /root/vcpkg/ports/libmysql/ignore-boost-version.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch /root/vcpkg/ports/libmysql/system-libs.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: /root/vcpkg/downloads/tools/cmake-3.11.4-linux/cmake-3.11.4-Linux-x86_64/bin/cmake;/root/vcpkg/buildtrees/libmysql/src/ysql-8.0.4-6271934d70;-DWITHOUT_SERVER=ON;-DWITH_UNIT_TESTS=OFF;-DENABLED_PROFILING=OFF;-DWIX_DIR=OFF;-DHAVE_LLVM_LIBCPP_EXITCODE=1;-DSTACK_DIRECTION=-1;-DWINDOWS_RUNTIME_MD=ON;-DIGNORE_BOOST_VERSION=ON;-DWITH_SSL=system;-DWITH_ICU=system;-DWITH_LIBEVENT=system;-DWITH_LZMA=system;-DWITH_LZ4=system;-DWITH_ZLIB=system;-DCMAKE_MAKE_PROGRAM=/root/vcpkg/downloads/tools/ninja-1.8.2-linux/ninja;-DCMAKE_SYSTEM_NAME=Linux;-DBUILD_SHARED_LIBS=OFF;-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/root/vcpkg/scripts/toolchains/linux.cmake;-DVCPKG_TARGET_TRIPLET=x64-linux;-DVCPKG_PLATFORM_TOOLSET=external;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=/root/vcpkg/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DVCPKG_CXX_FLAGS=;-DVCPKG_CXX_FLAGS_RELEASE=;-DVCPKG_CXX_FLAGS_DEBUG=;-DVCPKG_C_FLAGS=;-DVCPKG_C_FLAGS_RELEASE=;-DVCPKG_C_FLAGS_DEBUG=;-DVCPKG_CRT_LINKAGE=dynamic;-DVCPKG_LINKER_FLAGS=;-DCMAKE_INSTALL_LIBDIR:STRING=lib;-DCMAKE_INSTALL_BINDIR:STRING=bin;-G;Ninja;-DCMAKE_BUILD_TYPE=Debug;-DCMAKE_INSTALL_PREFIX=/root/vcpkg/packages/libmysql_x64-linux/debug
    Working Directory: /root/vcpkg/buildtrees/libmysql/x64-linux-dbg
    See logs for more information:
      /root/vcpkg/buildtrees/libmysql/config-x64-linux-dbg-out.log
      /root/vcpkg/buildtrees/libmysql/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:266 (vcpkg_execute_required_process)
  ports/libmysql/portfile.cmake:37 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package libmysql:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libmysql:x64-linux
  Vcpkg version: 2018.10.20-unknownhash

Additionally, attach any relevant sections from the log files above.

 /root/vcpkg/buildtrees/libmysql/config-x64-linux-dbg-err.log

CMake Deprecation Warning at CMakeLists.txt:52 (CMAKE_POLICY):
  The OLD behavior for policy CMP0045 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

CMake Error at configure.cmake:459 (STRING):
  STRING no output variable specified
Call Stack (most recent call first):
  CMakeLists.txt:653 (INCLUDE)

**Comment by studiofuga** [comment]
More details, I'm seeing the same on my ubuntu box:

```
happycactus@Picachu:vcpkg$ uname -a
Linux Picachu 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
happycactus@Picachu:vcpkg$ gcc --version
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
```

It fails at configure stage with this error:

```
CMake Error at configure.cmake:459 (STRING):
  STRING no output variable specified
```


Checked the `configure.cmake` file (it's a mysql source file) at line 459:

```
STRING(TOLOWER ${CMAKE_SYSTEM_PROCESSOR}  processor)
```

Indeed the CMAKE_SYSTEM_PROCESSOR variable is empty: see `CMakeSystem.cmake`:

```
set(CMAKE_HOST_SYSTEM "Linux-4.15.0-42-generic")
set(CMAKE_HOST_SYSTEM_NAME "Linux")
set(CMAKE_HOST_SYSTEM_VERSION "4.15.0-42-generic")
set(CMAKE_HOST_SYSTEM_PROCESSOR "x86_64")

include("/home/happycactus/Documents/Progetti/displace/vcpkg/scripts/buildsystems/vcpkg.cmake")

set(CMAKE_SYSTEM "Linux")
set(CMAKE_SYSTEM_NAME "Linux")
set(CMAKE_SYSTEM_VERSION "")
set(CMAKE_SYSTEM_PROCESSOR "")

set(CMAKE_CROSSCOMPILING "OFF")

set(CMAKE_SYSTEM_LOADED 1)
```


The problem seems to be on MySql side, because it's using CMAKE_SYSTEM_PROCESSOR that *may* be blank sometimes. 
Is there a way to workaround this? or, eventually, is correct that the CMAKE_SYSTEM_PROCESSOR is empty?
Please note that this variable is used in other ports  too.

**Comment by JackBoosY** [comment]
Hi @678uhb, thanks for reporting this issue!
I've fixed this issue. Please update vcpkg and rebuild libmysql.

Thanks.
