### ISSUE TITLE
vcpkg_fixup_cmake_targets only updates _IMPORT_PREFIX in files named *[Cc]onfig.cmake

### ISSUE THREAD

**Issue by rickertm** [Microsoft/vcpkg#4622]
Issue #1044 and commit 338f8614e3e0e8bd96b80c88fce825f02c2e0721 addressed the updating of _IMPORT_PREFIX when moving cmake config files. However, when installing target export definitions via install(EXPORT) and including this definition via include() in the config file, the variables in this file are not updated. This file can be given a custom name via install(EXPORT ... FILE myfile.cmake).

An example for this can be found in the Coin library:
https://bitbucket.org/Coin3D/coin/src/ea82a76a76836da2d19a9d4e86c5ef5318cc7830/src/CMakeLists.txt?at=default&fileviewer=file-view-default#CMakeLists.txt-199
https://bitbucket.org/Coin3D/coin/src/ea82a76a76836da2d19a9d4e86c5ef5318cc7830/src/coin-config.cmake.in?at=default&fileviewer=file-view-default#coin-config.cmake.in-92

A possible solution for this would be to replace `"${RELEASE_SHARE}/*[Cc]onfig.cmake"` with `"${RELEASE_SHARE}/*.cmake"` in https://github.com/Microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_fixup_cmake_targets.cmake#L143

**Comment by Neumann-A** [comment]
is this related to #4753? At least #1044 has the solution for #4753 in it comments

**Comment by rickertm** [comment]
Similar to the Coin example mentioned above which uses _coin-export.cmake_, NLopt in #4753 uses _NLoptLibraryDepends.cmake_ as filename and the _IMPORT_PREFIX is therefore not corrected as it does not match `${RELEASE_SHARE}/*[Cc]onfig.cmake`.

This filename can be set arbitrarily and adding `${RELEASE_SHARE}/*[Dd]epends.cmake` in #4782 is therefore not a generic solution. Using `${RELEASE_SHARE}/*.cmake` would address both libraries and any other filename. Another option could be to specify the name via a parameter to `vcpkg_fixup_cmake_targets()`.

**Comment by rickertm** [comment]
PR #5459 fixes the issue, thank you.
