### ISSUE TITLE
find_package(wt) issue

### ISSUE THREAD

**Issue by Lyill** [Microsoft/vcpkg#4633]
When I installed the package Wt, I encoutered a bug. The installation works fine but using find_package(wt CONFIG REQUIRED) fails in CMake using VS Code.

The machine setup : Windows 10 professionnal 1803
What package and version you're building: wt 4.0.4
Any relevant error logs from the build process : 

CMake Error at D:/Libraries/vcpkg/installed/x64-windows/share/Wt/wt-target-wt.cmake:79 (message):
[cmake]   The imported target "Wt::Wt" references the file
[cmake] 
[cmake]      "D:/Libraries/vcpkg/installed/debug/lib/wtd.lib"
[cmake] 
[cmake]   but this file does not exist.  Possible reasons include:
[cmake] 
[cmake]   * The file was deleted, renamed, or moved to another location.
[cmake] 
[cmake]   * An install or uninstall procedure did not complete successfully.
[cmake] 
[cmake]   * The installation package was faulty and contained
[cmake] 
[cmake]      "D:/Libraries/vcpkg/installed/x64-windows/share/Wt/wt-target-wt.cmake"
[cmake] 
[cmake]   but not all the files it references.
[cmake] 
[cmake] Call Stack (most recent call first):
[cmake]   D:/Libraries/vcpkg/installed/x64-windows/share/Wt/wt-config.cmake:10 (include)
[cmake]   D:/Libraries/vcpkg/scripts/buildsystems/vcpkg.cmake:247 (_find_package)
[cmake]   CMakeLists.txt:10 (find_package)

However when comparing different .cmake (sqlite3 and wt) files used by vcpkg, i noticed that there was a difference in the file specified by the error log. 
These lines in wt-config.cmake : 
`# Compute the installation prefix relative to this file.`
`get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)`
`get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)`
`get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)`
`get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)`
`if(_IMPORT_PREFIX STREQUAL "/")`
  `set(_IMPORT_PREFIX "")`
`endif()`
In sqlite3, `get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)` are only present 2 times against 3 in Wt.

Nevertheless, if I remove one of the 3 lines in Wt (in all the different target files), it configures fine with CMake.

I suppose it is a bug but that also could be a bad "configuration" from my vcpkg installation ?

**Comment by vicroms** [comment]
This should be fixed in #5459 which now has been merged to `master`.
