### ISSUE TITLE
Building package sqlite3:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by MNorthup** [Microsoft/vcpkg#4634]
I ran into this while trying to install poco. Now, I'm executing this from my Command Prompt for VS 2013 (with or w/o admin rights):
C:\WINDOWS\system32>vcpkg install sqlite3
The following packages will be built and installed:
    sqlite3[core]:x86-windows
Starting package 1/1: sqlite3:x86-windows
Building package sqlite3[core]:x86-windows...
-- Using cached C:/vcpkg/downloads/sqlite-amalgamation-3240000.zip
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: C:/vcpkg/buildtrees/sqlite3/x86-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\sqlite3\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/sqlite3/portfile.cmake:29 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package sqlite3:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sqlite3:x86-windows
  Vcpkg version: 0.0.113-nohash

Additionally, attach any relevant sections from the log files above.
[install-x86-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2539368/install-x86-windows-dbg-out.log)
[CMakeLists.txt](https://github.com/Microsoft/vcpkg/files/2539377/CMakeLists.txt)

I see that sqlite3.c content references sqlite3.h (which does not exist. There is an sqlite3ext.h file. The CMakeLists.txt references sqlite3.h and sqlite3ext.h.

I currently have no idea how to fix this.

**Comment by NancyLi1013** [comment]
Hi @MNorthup, thanks for posting this issue. The package has been updated. And I can find that sqlite3.h is already in the source path .../buildtrees/sqlite3/src/3270200-2078ef6d88. I think it should be fixed now. I can install it successfully on my machine. So please update the port to the latest version and try it again. Please feel free to reopen it if this is still a problem for you.
