### ISSUE TITLE
Custom port (libraqm): DLLs have no exports

### ISSUE THREAD

**Issue by tobbi** [Microsoft/vcpkg#4638]
I added a new port for libraqm here:
https://github.com/Microsoft/vcpkg/compare/master...tobbi:add_libraqm

It compiles and copies the files to the proper directories, however, when I try to install it, I keep getting these errors:
```
Import libs were not present in C:\Users\User\vcpkg\packages\libraqm_x64-windows\debug\lib
If this is intended, add the following line in the portfile:
    SET(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)
Import libs were not present in C:\Users\User\vcpkg\packages\libraqm_x64-windows\lib
If this is intended, add the following line in the portfile:
    SET(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)
The following DLLs have no exports:

    C:/Users/User/vcpkg/packages/libraqm_x64-windows/debug/bin/raqm.dll
    C:/Users/User/vcpkg/packages/libraqm_x64-windows/bin/raqm.dll

DLLs without any exports are likely a bug in the build script.
Found 3 error(s). Please correct the portfile:
    C:\Users\User\vcpkg\ports\libraqm\portfile.cmake
-- Performing post-build validation done
Error: Building package libraqm:x64-windows failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libraqm:x64-windows
  Vcpkg version: 2018.10.20-nohash

Additionally, attach any relevant sections from the log files above.
```

The source code of the library can be found here: 
https://github.com/HOST-Oman/libraqm/tree/v0.5.0

This library depends on fribidi:
https://github.com/Microsoft/vcpkg/pull/4627

Any idea?

**Comment by ras0219-msft** [comment]
This probably means the library was not designed to be used as DLLs. Assuming that's the case, you can add
```cmake
vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
```
right below the `include(common)` line, which should fix this issue :)

**Comment by tobbi** [comment]
Thanks! It seems like it built properly. One more thing that makes me wonder: Installing works fine now, but my custom FindRAQM.cmake script can't find the include paths:
Could NOT find RAQM (missing: RAQM_INCLUDE_DIRS)

This is the cmake module responsible for finding the include dirs: https://github.com/SuperTux/supertux/blob/master/mk/cmake/FindRAQM.cmake (is there anything wrong with that?)

**Comment by tobbi** [comment]
Anyway, i'm gonna close this since the original issue is resolved. Thanks again :)
