### ISSUE TITLE
Download attempts should print the URL and destination path

### ISSUE THREAD

**Issue by masali-hp** [microsoft/vcpkg#4639]
I'm seeing this error:

     Building package zlib[core]:x86-windows...
      A suitable version of git was not found (required v2.17.1). Downloading portable git v2.17.1...
      Downloading git...
      WinHttpSendRequest() failed: 12002

I'm not sure how to debug this WinInet error - at least googling this message suggests that WinInet is what's behind this error.  A simple (one-line) tweak to vcpkg can print out the URL and path we're trying to download.  I put the URL in my browser, download the file to the location vcpkg wants to store the tool at, and move on with my life.

Ideally, the problem wouldn't occur in the first place, but downloading stuff from a scripted environment in Windows isn't an easy problem to solve.  I've seen many *different* approaches to this problem, which tells me there isn't an easy answer.

**Comment by ras0219-msft** [comment]
Half-fixed by your PR #4640, though we should also improve downloading.

I'll leave this open for now, but we may close it in the future in favor of some unified "download issues" issue.

**Comment by PhoebeHui** [comment]
Looks fixed now.
