### ISSUE TITLE
libusb: cannot build x86-windows-static.

### ISSUE THREAD

**Issue by carmangary** [Microsoft/vcpkg#4644]
Used to work until recently.
Now error given is:
Expected Debug,Dynamic crt linkage, but the following libs had invalid crt linkage

**Comment by carmangary** [comment]
I noticed that I already raised this issue.  Since I fixed the issue locally, whenever the update to libusb came in it overwrote my changes and broke it again.  My previous bug report describes the fix for this.  I assume it needs some patch files to be created to fix the vcprojx file.

**Comment by NancyLi1013** [comment]
Hi @carmangary, thanks for posting this issue. Does this issue still exist on your machine now? I can install and build it on my machine successfully with the latest vcpkg. If this is still a problem for you, please help offer the error logs.

**Comment by carmangary** [comment]
@NancyLi1013 I will check this weekend.

**Comment by carmangary** [comment]
You can close it.  It builds but not the way I want it to be built so I change the csprojx file.  I guess technically it is not a bug but a vcpkg limitation.

**Comment by NancyLi1013** [comment]
@carmangary, thanks for your quick reply. please open a new issue if you have any other problems.
