### ISSUE TITLE
[qt5] fails to build on linux due to atlmfc dependency 

### ISSUE THREAD

**Issue by dantti** [microsoft/vcpkg#4645]
Hi,
I'm trying to add a new package (cutelyst) that depends on Qt5, when I vcpkg install qt5 I get an issue when with atlmfc package:

```
daniel@bart:~/code/vcpkg$ ./vcpkg install atlmfc
The following packages will be built and installed:
    atlmfc[core]:x64-linux
Starting package 1/1: atlmfc:x64-linux
Building package atlmfc[core]:x64-linux... 
CMake Error at ports/atlmfc/portfile.cmake:7 (message):
  Unable to locate 'afxres.h'.  Ensure you have installed the ATL/MFC
  component of Visual Studio.
Call Stack (most recent call first):
  scripts/ports.cmake:71 (include)


Error: Building package atlmfc:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: atlmfc:x64-linux
  Vcpkg version: 2018.10.20-unknownhash

Additionally, attach any relevant sections from the log files above.
```

**Comment by carmangary** [comment]
atlmfc is a windows only package.  seems odd that qt5 would reference it.

**Comment by dantti** [comment]
It seems the problem is that:
 * qt5-winextras[core]:x64-linux
Wants to be installed which requires atlmfc, vcpkg should be pulling qt5-x11extras instead

**Comment by dantti** [comment]
How one can make
https://github.com/Microsoft/vcpkg/blob/master/ports/qt5/CONTROL#L4
platform dependant?

**Comment by Rastaban** [comment]
qt4-winextras is a windows only Qt5 plugin so it is okay that it references it.  It looks like someone added `qt5-winextras (windows)` to the dependency list since this PR, so it should be platform dependent now.

**Comment by JackBoosY** [comment]
Now we can build qt5 in linux, but some qt5 components like `qt5-activeqt` and `qt5-winextras` only support windows.
See [here](https://doc.qt.io/qt-5/reference-overview.html).
