### ISSUE TITLE
hwloc fails to compile on linux

### ISSUE THREAD

**Issue by jayeshbadwaik** [microsoft/vcpkg#4651]
This issue can be considered to be a sub-issue of issue #3307. The problem is that the CMakeLists.txt is tailored for windows. In order to make the package compile for linux, one needs to run linux specific commands in order to generate the correct header files. 

I have done a terribly crude version of the above in form of a CMakeLists.txt [here](https://github.com/jayeshbadwaik/vcpkg/blob/hwloc/ports/hwloc/CMakeLists.txt) ([commit](https://github.com/jayeshbadwaik/vcpkg/commit/c890afe4d944b8be92bf43846a84fcab7607cb6a)) which compiles hwloc correctly but fails to install since it is trying to run ninja somewhere. 

"Dirty" things which I've done in the CMakeLists.txt:
1. run `./autogen.sh` as a bash command from cmake
2. run `./configure` as a bash command from cmake
3. specify all the compile options with a `set` command
4. Specify linux specific source files instead of having a separating windows and linux files with `ifdef(WIN32)` like options.
5. I have completely disabled `libxml2` instead of trying to fix it. 

I will try to work on this, however, I would welcome all kinds of help on this.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed in PR #10615. `hwloc` support use `./autogen.sh` and `./configure` to compile on Linux, so I am closing this issue for now.
