### ISSUE TITLE
Add thrust package

### ISSUE THREAD

**Issue by jjpepper** [microsoft/vcpkg#4659]
Are there any plans to add the header-only parallelism library thrust?  https://github.com/thrust/thrust

**Comment by jjpepper** [comment]
I guess this is installed as part of the cuda install so it's kind of already done.

**Comment by LarryIII** [comment]
Yes, it is a part of cuda. See https://github.com/thrust/thrust/wiki/Quick-Start-Guide: "If you are using CUDA 4.0 or better then Thrust is already installed on your system."
 Currently cuda version is 9.0 in VCPKG. So there is no need to add this thrust separately.

**Comment by acdemiralp** [comment]
Thrust is also usable on systems without NVIDIA GPUs with the OpenMP/TBB backends but a CUDA install (including thrust) will fail if you do not have an NVIDIA GPU.
