### ISSUE TITLE
cannot add 'xerces-c' in Build-Depends due to invalid character

### ISSUE THREAD

**Issue by jepessen** [Microsoft/vcpkg#4662]
I'm trying to create a new port. This is the CONTROL file:

```
Source: opendds3
Version: 3.13
Description: OpenDDS is an open source C++ implementation of the Object Management Group (OMG) Data Distribution Service (DDS).
Build-Depends: ace xerces-c
```

If I run it I obtain the following error:

```
Failed at [d:\vcpkg\toolsrc\src\vcpkg\packagespec.cpp(37)] with message:
Contains invalid characters. Only alphanumeric lowercase ASCII characters and dashes are allowed
```

If I remove `xerces-c` from CONTROL the error does not appear. I suppose that the error is caused by the `-` character but since it's in the `xerces-c` name I cannot remove it. Is there a way to handle with it or it's necessary to inspect the `packagespec.cpp` file in order to resolve the bug?

**Comment by ras0219-msft** [comment]
Thanks for pointing out the really bad error message here!

The actual issue is that we comma separate dependencies :). So the fix is just:
```
Build-Depends: ace, xerces-c
```
The "invalid character" in this case was the space character.

**Comment by jepessen** [comment]
Ok, it was easy to fix then...
