### ISSUE TITLE
qt5-script 5.11.1 wrong hash

### ISSUE THREAD

**Issue by blamond** [Microsoft/vcpkg#4670]
Hi, 

Building package qt5-script[core]:x64-windows_v140...
-- Downloading http://download.qt.io/official_releases/qt/5.11/5.11.1/submodules/qtscript-everywhere-src-5.11.1.tar.xz...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:91 (message):

  File does not have expected hash:

          File path: [ D:/sw/packages/vcpkg/downloads/temp/qtscript-everywhere-src-5.11.1.tar.xz ]
      Expected hash: [ 3ce2e57a0a6b2382614f689edca0deed87afe944c1c41decb3b9f420449fa59f2b79e6330e78e01a950761a95903113eaa7fbf261886361114acf5015d93254c ]
        Actual hash: [ 609ac6675341fb2707ad3b91e955a430846253741931ada2343ab2d1ad27169a60548b1a2621369384043a4c5b983e392c3fafcffd50237563b9f4204123e411 ]

Verified the Actual hash is correct (see attached). Build completes once actual hash is updated in <vcpkg>\ports\qt5-script\portfile.cmake 

![qtscript_5 11 1_hash](https://user-images.githubusercontent.com/40252473/48150315-25514680-e273-11e8-8fe5-47b6937fd1b4.jpg)

**Comment by ras0219-msft** [comment]
Thanks for reporting this!

It should be fixed by #4629; please `git pull` and retry!
