### ISSUE TITLE
Flatbuffers version needs a bump up

### ISSUE THREAD

**Issue by harsh-telepathy** [microsoft/vcpkg#4674]
https://github.com/Microsoft/vcpkg/blob/273b8ce3d0d3533f3b959a7ecf4b0aa1eef22cab/ports/flatbuffers/CONTROL#L2

Current version as reported by flatc appears to be 1.10.0 which has some significant differences (like default values for enums and several compilation breaks on dependent libraries)

**Comment by wangli28** [comment]
Thanks for posting this issue. Flatbuffers has upgrade to 1.11.0, you can update vcpkg and rebuild.
