### ISSUE TITLE
[ranges-v3] fails to install, conflicting files

### ISSUE THREAD

**Issue by degski** [Microsoft/vcpkg#4675]
Y:\vcpkg>vcpkg upgrade --no-dry-run
    The following packages will be rebuilt:
        fftw3[core]:x64-windows-static
        range-v3[core]:x64-windows-static
    Starting package 1/4: fftw3:x64-windows-static
    Removing package fftw3:x64-windows-static...
    Removing package fftw3:x64-windows-static... done
    Purging package fftw3:x64-windows-static...
    Purging package fftw3:x64-windows-static... done
    Elapsed time for package fftw3:x64-windows-static: 55.7 ms
    Starting package 2/4: range-v3:x64-windows-static
    Removing package range-v3:x64-windows-static...
    Removing package range-v3:x64-windows-static... done
    Purging package range-v3:x64-windows-static...
    Purging package range-v3:x64-windows-static... done
    Elapsed time for package range-v3:x64-windows-static: 5.777 ms
    Starting package 3/4: fftw3:x64-windows-static
    Building package fftw3[core]:x64-windows-static...
    -- Downloading http://www.fftw.org/fftw-3.3.8.tar.gz...
    -- Extracting source Y:/vcpkg/downloads/fftw-3.3.8.tar.gz
    -- Configuring x64-windows-static
    -- Building x64-windows-static-dbg
    -- Building x64-windows-static-rel
    -- Configuring x64-windows-static
    -- Building x64-windows-static-dbg
    -- Building x64-windows-static-rel
    -- Configuring x64-windows-static
    -- Building x64-windows-static-dbg
    -- Building x64-windows-static-rel
    -- Performing post-build validation
    -- Performing post-build validation done
    Building package fftw3[core]:x64-windows-static... done
    Installing package fftw3[core]:x64-windows-static...
    Installing package fftw3[core]:x64-windows-static... done
    Elapsed time for package fftw3:x64-windows-static: 8.132 min
    Starting package 4/4: range-v3:x64-windows-static
    Building package range-v3[core]:x64-windows-static...
    -- Downloading https://github.com/ericniebler/range-v3/archive/01ccd0e552860efe00e4e3e55bf823be445aabb4.tar.gz...
    -- Extracting source Y:/vcpkg/downloads/ericniebler-range-v3-01ccd0e552860efe00e4e3e55bf823be445aabb4.tar.gz
    -- Using source at Y:/vcpkg/buildtrees/range-v3/src/be445aabb4-633c8ae91c
    -- Configuring x64-windows-static
    -- Building x64-windows-static-dbg
    -- Building x64-windows-static-rel
    -- Performing post-build validation
    -- Performing post-build validation done
    Building package range-v3[core]:x64-windows-static... done
    Installing package range-v3[core]:x64-windows-static...

    The following files are already installed in y:/vcpkg/installed/x64-windows-static and are in conflict with range-v3:x64-windows-static

        include/meta/meta.hpp
        include/meta/meta_fwd.hpp
        ...
        include/range/v3/view_facade.hpp
        include/range/v3/view_interface.hpp

    Please ensure you're using the latest portfiles with `.\vcpkg update`, then
    submit an issue at https://github.com/Microsoft/vcpkg/issues including:
      Package: range-v3:x64-windows-static
      Vcpkg version: 2018.10.20-nohash

    Additionally, attach any relevant sections from the log files above.

    Y:\vcpkg>

**Comment by alexkaratarakis** [comment]
@degski 
Did you simply delete the vs2015 files? (this would not be sufficient)
Please try:
`vcpkg remove range-v3-vs2015:x64-windows-static`
`vcpkg install range-v3:x64-windows-static`

Full context:
The reason for this is that `range-v3` previously delegated to `range-v3-vs2015` on windows, but after a recent update the ports are independent. We still keep range-v3-vs2015 around for VS2015 users.
However, you cannot have both installed at the same time.

**Comment by degski** [comment]
@alexkaratarakis 
Apparently not. I did as you said, and now I get:

    Y:\vcpkg>vcpkg remove range-v3-vs2015:x64-windows-static
    The following packages will be removed:
        range-v3-vs2015:x64-windows-static
    Removing package range-v3-vs2015:x64-windows-static...
    Warning: y:\vcpkg\installed\x64-windows-static\include\range\v3\algorithm\merge_move.hpp: file not found
    Warning: y:\vcpkg\installed\x64-windows-static\include\range\v3\algorithm\partition_move.hpp: file not found
    Warning: y:\vcpkg\installed\x64-windows-static\include\range\v3\algorithm\random_shuffle.hpp: file not found
    Warning: y:\vcpkg\installed\x64-windows-static\include\range\v3\range.hpp: file not found
    Warning: y:\vcpkg\installed\x64-windows-static\include\range\v3\utility\compressed_tuple.hpp: file not found
    Warning: y:\vcpkg\installed\x64-windows-static\include\range\v3\utility\integer_sequence.hpp: file not found
    Warning: y:\vcpkg\installed\x64-windows-static\include\range\v3\utility\meta.hpp: file not found
    Warning: y:\vcpkg\installed\x64-windows-static\include\range\v3\utility\safe_int.hpp: file not found
    Removing package range-v3-vs2015:x64-windows-static... done
    Purging package range-v3-vs2015:x64-windows-static...
    Purging package range-v3-vs2015:x64-windows-static... done

    Y:\vcpkg>vcpkg install range-v3:x64-windows-static
    The following packages will be built and installed:
        range-v3[core]:x64-windows-static
    Starting package 1/1: range-v3:x64-windows-static
    Building package range-v3[core]:x64-windows-static...
    -- Downloading https://github.com/ericniebler/range-v3/archive/01ccd0e552860efe00e4e3e55bf823be445aabb4.tar.gz...
    -- Using source at Y:/vcpkg/buildtrees/range-v3/src/be445aabb4-633c8ae91c
    -- Configuring x64-windows-static
    -- Building x64-windows-static-dbg
    -- Building x64-windows-static-rel
    -- Performing post-build validation
    -- Performing post-build validation done
    Building package range-v3[core]:x64-windows-static... done
    Installing package range-v3[core]:x64-windows-static...
    File y:\vcpkg\installed\x64-windows-static\include\range\v3\action\reverse.hpp was already present and will be overwritten
    File y:\vcpkg\installed\x64-windows-static\include\range\v3\algorithm\aux_\partition_point_n.hpp was already present and will be overwritten
    File y:\vcpkg\installed\x64-windows-static\include\range\v3\algorithm\for_each_n.hpp was already present and will be overwritten
    File y:\vcpkg\installed\x64-windows-static\include\range\v3\algorithm\sample.hpp was already present and will be overwritten
    File y:\vcpkg\installed\x64-windows-static\include\range\v3\data.hpp was already present and will be overwritten
    File y:\vcpkg\installed\x64-windows-static\include\range\v3\detail\adl_get.hpp was already present and will be overwritten
    File y:\vcpkg\installed\x64-windows-static\include\range\v3\detail\satisfy_boost_range.hpp was already present and will be overwritten
    File y:\vcpkg\installed\x64-windows-static\include\range\v3\detail\variant.hpp was already present and will be overwritten
    File y:\vcpkg\installed\x64-windows-static\include\range\v3\experimental\utility\generator.hpp was already present and will be overwritten
    File y:\vcpkg\installed\x64-windows-static\include\range\v3\experimental\view\shared.hpp was already present and will be overwritten
    File y:\vcpkg\installed\x64-windows-static\include\range\v3\index.hpp was already present and will be overwritten
    File y:\vcpkg\installed\x64-windows-static\include\range\v3\iterator_range.hpp was already present and will be overwritten
    File y:\vcpkg\installed\x64-windows-static\include\range\v3\span.hpp was already present and will be overwritten
    File y:\vcpkg\installed\x64-windows-static\include\range\v3\utility\invoke.hpp was already present and will be overwritten
    File y:\vcpkg\installed\x64-windows-static\include\range\v3\utility\polymorphic_cast.hpp was already present and will be overwritten
    File y:\vcpkg\installed\x64-windows-static\include\range\v3\utility\random.hpp was already present and will be overwritten
    File y:\vcpkg\installed\x64-windows-static\include\range\v3\utility\scope_exit.hpp was already present and will be overwritten
    File y:\vcpkg\installed\x64-windows-static\include\range\v3\version.hpp was already present and will be overwritten
    File y:\vcpkg\installed\x64-windows-static\include\range\v3\view\adjacent_filter.hpp was already present and will be overwritten
    File y:\vcpkg\installed\x64-windows-static\include\range\v3\view\cartesian_product.hpp was already present and will be overwritten
    File y:\vcpkg\installed\x64-windows-static\include\range\v3\view\drop_exactly.hpp was already present and will be overwritten
    File y:\vcpkg\installed\x64-windows-static\include\range\v3\view\exclusive_scan.hpp was already present and will be overwritten
    File y:\vcpkg\installed\x64-windows-static\include\range\v3\view\indices.hpp was already present and will be overwritten
    File y:\vcpkg\installed\x64-windows-static\include\range\v3\view\linear_distribute.hpp was already present and will be overwritten
    File y:\vcpkg\installed\x64-windows-static\include\range\v3\view\sample.hpp was already present and will be overwritten
    File y:\vcpkg\installed\x64-windows-static\include\range\v3\view\set_algorithm.hpp was already present and will be overwritten
    File y:\vcpkg\installed\x64-windows-static\include\range\v3\view\sliding.hpp was already present and will be overwritten
    Installing package range-v3[core]:x64-windows-static... done
    Elapsed time for package range-v3:x64-windows-static: 27.59 s

    Total elapsed time: 27.59 s

    The package range-v3:x64-windows-static provides CMake targets:

        find_package(range-v3 CONFIG REQUIRED)
        target_link_libraries(main PRIVATE meta range-v3)


    Y:\vcpkg>

So that looks ok [the output seems what one would expect, in view of how I hacked it].

Thank Alex.
