### ISSUE TITLE
Any plan to add libass?

### ISSUE THREAD

**Issue by scarsty** [Microsoft/vcpkg#4678]
the site is  https://github.com/libass/libass

**Comment by s-martin** [comment]
I'd appreciate as well, if libass could be added.

Is there anything I could do to help?

**Comment by scarsty** [comment]
Thanks! It is great! But it seems like unfinished?

**Comment by Corbachu** [comment]
@scarsty you mentioned it is unfinished? It is working for me - but if it's not working properly I will fix it up - just let me know what needs touching up.

**Comment by scarsty** [comment]
> @scarsty you mentioned it is unfinished? It is working for me - but if it's not working properly I will fix it up - just let me know what needs touching up.

After running " .\vcpkg.exe install libass", I found .c and .h files of libass are all installed in "installed\x86-windows\include", and no .lib and .dll files can be found in "lib" and "bin" respectively.

**Comment by NancyLi1013** [comment]
@scarsty, thanks for posting this issue. The PR #5026 has been merged. Please try to use it.
