### ISSUE TITLE
glew install error on Linux-x64

### ISSUE THREAD

**Issue by dascandy** [microsoft/vcpkg#4684]
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: /home/pebi/git/vcpkg/downloads/tools/cmake-3.11.4-linux/cmake-3.11.4-Linux-x86_64/bin/cmake;/home/pebi/git/vcpkg/buildtrees/glew/src/glew/glew-2.1.0/build/cmake;-DCMAKE_MAKE_PROGRAM=/home/pebi/git/vcpkg/downloads/tools/ninja-1.8.2-linux/ninja;-DCMAKE_SYSTEM_NAME=Linux;-DBUILD_SHARED_LIBS=OFF;-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/pebi/git/vcpkg/scripts/toolchains/linux.cmake;-DVCPKG_TARGET_TRIPLET=x64-linux;-DVCPKG_PLATFORM_TOOLSET=external;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=/home/pebi/git/vcpkg/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DVCPKG_CXX_FLAGS=;-DVCPKG_CXX_FLAGS_RELEASE=;-DVCPKG_CXX_FLAGS_DEBUG=;-DVCPKG_C_FLAGS=;-DVCPKG_C_FLAGS_RELEASE=;-DVCPKG_C_FLAGS_DEBUG=;-DVCPKG_CRT_LINKAGE=dynamic;-DVCPKG_LINKER_FLAGS=;-DCMAKE_INSTALL_LIBDIR:STRING=lib;-DCMAKE_INSTALL_BINDIR:STRING=bin;-G;Ninja;-DCMAKE_BUILD_TYPE=Debug;-DCMAKE_INSTALL_PREFIX=/home/pebi/git/vcpkg/packages/glew_x64-linux/debug
    Working Directory: /home/pebi/git/vcpkg/buildtrees/glew/x64-linux-dbg
    See logs for more information:
      /home/pebi/git/vcpkg/buildtrees/glew/config-x64-linux-dbg-out.log
      /home/pebi/git/vcpkg/buildtrees/glew/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:266 (vcpkg_execute_required_process)
  ports/glew/portfile.cmake:14 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package glew:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glew:x64-linux
  Vcpkg version: 2018.10.20-unknownhash

Everything is up to date - I barely started using this system.

Error log above says:

CMake Error at /home/pebi/git/vcpkg/downloads/tools/cmake-3.11.4-linux/cmake-3.11.4-Linux-x86_64/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY
  OPENGL_INCLUDE_DIR)
Call Stack (most recent call first):
  /home/pebi/git/vcpkg/downloads/tools/cmake-3.11.4-linux/cmake-3.11.4-Linux-x86_64/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /home/pebi/git/vcpkg/downloads/tools/cmake-3.11.4-linux/cmake-3.11.4-Linux-x86_64/share/cmake-3.11/Modules/FindOpenGL.cmake:395 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /home/pebi/git/vcpkg/scripts/buildsystems/vcpkg.cmake:247 (_find_package)
  CMakeLists.txt:40 (find_package)

vcpkg's opengl library was installed just before this.

**Comment by dascandy** [comment]
I can run glxgears just fine. OpenGL is available; did not check for development headers yet but that would be most of vcpkg's job I think.

**Comment by dascandy** [comment]
After running `sudo apt-get install libgl-dev` it works. Seems to be a compile detail somewhere?

**Comment by dascandy** [comment]
Post-install though, glew.h is not includable, as the vcpkg config does not set GLEW_NO_GLU, and it does not install GLU either.

**Comment by ras0219-msft** [comment]
Thanks for the feedback!

Could you try `dev/roschuma/4684` and see if that works a bit better?
- It should display a message indicating that you can `apt install mesa-common-dev` to get the opengl headers
- It should encode `GLEW_NO_GLU` into the installed header file

Unfortunately, we need to rely on the platform to provide an implementation of OpenGL because it can be tightly coupled to the overall system graphics stack.

**Comment by pslacerda** [comment]
The same occurred to me. Installing the freeglut port dependencies worked here. And yes, a display message indicating the working around would help a lot.

```bash
# Fedora packages
dnf install mesa-libGL-devel libXi-devel mesa-libGL \
    mesa-libGLU-devel libXrandr-devel libXxf86vm-devel
```

**Comment by JonLiu1993** [comment]
@dascandy ,Now the glew have add a display message indicating 
````
if(VCPKG_TARGET_IS_LINUX)
    message(WARNING "${PORT} requires the following libraries from the system package manager:\n    libxmu-dev\n    libxi-dev\n    libgl-dev\n\nThese can be installed on Ubuntu systems via apt-get install libxmu-dev libxi-dev libgl-dev.")
endif()
````
