### ISSUE TITLE
Fail to install osg

### ISSUE THREAD

**Issue by EngineerZhang** [microsoft/vcpkg#4687]
Hi,when I use vcpkg to install osg like this`.\vcpkg.exe install osg`,I get wrong,`The following packages will be built and installed:
  * freetype[core]:x86-windows
  * gdal[core,mysql-libmysql]:x86-windows
  * giflib[core]:x86-windows
  * ilmbase[core]:x86-windows
  * jasper[core]:x86-windows
  * libjpeg-turbo[core]:x86-windows
  * libmysql[core]:x86-windows
  * openexr[core]:x86-windows
    osg[core]:x86-windows
  * tiff[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/10: libmysql:x86-windows
Building package libmysql[core]:x86-windows...
CMake Error at ports/libmysql/portfile.cmake:10 (message):
  Oracle has dropped support in libmysql for 32-bit Windows.
Call Stack (most recent call first):
  scripts/ports.cmake:71 (include)

Error: Building package libmysql:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libmysql:x86-windows
  Vcpkg version: 2018.10.20-nohash

Additionally, attach any relevant sections from the log files above.`
How can I do?Thanks!

**Comment by Andapeng** [comment]
see also : 
#3335

**Comment by LarryIII** [comment]
Same with https://github.com/microsoft/vcpkg/issues/3335, so closed it.
