### ISSUE TITLE
glad library not supported

### ISSUE THREAD

**Issue by JankoDedic** [Microsoft/vcpkg#4689]
It can be found here https://github.com/Dav1dde/glad and it uses CMake already.

**Comment by PhoebeHui** [comment]
Hi JankoDedic,

VCPKG is support glad library, you can have a try. Please close this issue if it's resolved.

PS F:\vcpkg\src> .\vcpkg install glad
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be built and installed:
  * egl-registry[core]:x86-windows
    glad[core]:x86-windows
  * opengl-registry[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: egl-registry:x86-windows
Building package egl-registry[core]:x86-windows...
-- Downloading https://github.com/KhronosGroup/EGL-Registry/archive/e2562a9e7f567b837cdf96cf8b12e7fc0d88cc30.tar.gz...
-- Extracting source F:/VCPKG/src/downloads/KhronosGroup-EGL-Registry-e2562a9e7f567b837cdf96cf8b12e7fc0d88cc30.tar.gz
-- Using source at F:/VCPKG/src/buildtrees/egl-registry/src/fc0d88cc30-f5fda177a5
-- Installing: F:/VCPKG/src/packages/egl-registry_x86-windows/share/egl-registry/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package egl-registry[core]:x86-windows... done
Installing package egl-registry[core]:x86-windows...
Installing package egl-registry[core]:x86-windows... done
Elapsed time for package egl-registry:x86-windows: 2.241 s
Starting package 2/3: opengl-registry:x86-windows
Building package opengl-registry[core]:x86-windows...
-- Downloading https://github.com/KhronosGroup/OpenGL-Registry/archive/e18e52a14e902a9ee29c5bf87478ac2ca21bb06b.tar.gz...
-- Extracting source F:/VCPKG/src/downloads/KhronosGroup-OpenGL-Registry-e18e52a14e902a9ee29c5bf87478ac2ca21bb06b.tar.gz
-- Using source at F:/VCPKG/src/buildtrees/opengl-registry/src/2ca21bb06b-cf068ccdf1
-- Installing: F:/VCPKG/src/packages/opengl-registry_x86-windows/share/opengl-registry/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package opengl-registry[core]:x86-windows... done
Installing package opengl-registry[core]:x86-windows...
Installing package opengl-registry[core]:x86-windows... done
Elapsed time for package opengl-registry:x86-windows: 13.97 s
Starting package 3/3: glad:x86-windows
Building package glad[core]:x86-windows...
-- Note: glad only supports static library linkage. Building static library.
-- Downloading https://github.com/Dav1dde/glad/archive/v0.1.28.tar.gz...
-- Extracting source F:/VCPKG/src/downloads/Dav1dde-glad-v0.1.28.tar.gz
-- Using source at F:/VCPKG/src/buildtrees/glad/src/v0.1.28-a7d86de8dc
-- Downloading https://www.python.org/ftp/python/2.7.14/python-2.7.14.msi...
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package glad[core]:x86-windows... done
Installing package glad[core]:x86-windows...
Installing package glad[core]:x86-windows... done
Elapsed time for package glad:x86-windows: 24.33 s

Total elapsed time: 40.54 s

The package glad:x86-windows provides CMake targets:

    find_package(glad CONFIG REQUIRED)
    target_link_libraries(main PRIVATE glad::glad)

Thanks,
Phoebe

**Comment by tajuddinkhandaker** [comment]
When I call cmake in linux terminal (HW arch i386) it finds gladConfig.cmake or glad-config.cmake. But glad is already downloaded and installed using vcpkg in packages directory where in respective share folder contains config files. I could not find the reason why the following change in CMakelists.txt shows error while executing cmake.

```
find_package(glad CONFIG REQUIRED)
target_link_libraries(main PRIVATE glad::glad)
```
