### ISSUE TITLE
SDL2 install/package fails

### ISSUE THREAD

**Issue by Morten242** [Microsoft/vcpkg#469]
`vcpkg install SDL2` fails after the most recent update (https://github.com/Microsoft/vcpkg/pull/437) with multiple 'unresolved external symbol' errors.

-----
Running win10 anniversary, SDL2 has been successfully installed earlier. 
```
Please ensure sure you're using the latest portfiles with `vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sdl2:x86-windows
  Vcpkg version: 0.0.65-835693ce97f271c0213f65c1c782e8df84cfb409
```
[package log](http://morten242.com/sharex/2016/12/package-x86-windows-rel-out.log)

**Comment by codicodi** [comment]
This PR was meant to fix issue in static builds but it looks like it accidentaly broke dynamic ones. Removing /NODEFAULTLIB flags from SDL's buildscript should probably fix this. I'll test it further and propose a PR.
Sorry for the trouble!
