### ISSUE TITLE
no way to set VCPKG_ALLOW_APPLE_CLANG

### ISSUE THREAD

**Issue by justinmeiners** [Microsoft/vcpkg#4698]
When building on Mac with xcode installed, I am given the following message:

```
Building the vcpkg tool requires support for the C++ Filesystem TS.
Apple clang versions 9 and below do not have support for it.
Please install gcc6 or newer from homebrew (brew install gcc6).
If you would like to try anyway, set VCPKG_ALLOW_APPLE_CLANG.
```

However, setting this environmental variable does nothing and results in the same error.

It looks like this line in the CMakeLists should be reading from the environment `$ENV(VCPKG_ALLOW_APPLE_CLANG).`

https://github.com/Microsoft/vcpkg/blob/a6986fdbea87c5af4ab9c1eb4d8c3d52563aee65/toolsrc/CMakeLists.txt#L9

**Comment by soroshsabz** [comment]
@liangqi I think no, this issue is related to #4475 , but this issue focused on how set `VCPKG_ALLOW_APPLE_CLANG` not how to build vcpkg on apple, in another word this issue is part of #4475
