### ISSUE TITLE
bootstrap.sh will not use system cmake on linux or mac

### ISSUE THREAD

**Issue by justinmeiners** [microsoft/vcpkg#4699]
The code that searches for `cmake` will first look to see if you have one, then check if its version is valid (greater than the needed version.).

https://github.com/Microsoft/vcpkg/blob/1c2c69529e0ca44bd2fa4da68507d07aa3f310a4/toolsrc/src/vcpkg/tools.cpp#L276

However, this is only done in the vcpkg code, not the `bootstrap.sh`. This shell script installs a new version of cmake regardless of whether the current platform one is valid.

https://github.com/Microsoft/vcpkg/blob/8dc8d0e0c97550a95b764287adbad90b7df7d11d/scripts/bootstrap.sh#L195

**Expected Behaviour**

Like, vcpkg itself, the shell script should use the system cmake if a valid one is available.

**Comment by Kumar-Kishan** [comment]
Hey, @justinmeiners you can force the use of systemwide binaries if you have both cmake and ninja
by using "useSystemBinaries" switch as a workaround for now.

**Comment by PhoebeHui** [comment]
This issue should be fixed now. if it is still an issue, please reopen.
