### ISSUE TITLE
flatbuffer complation fails on ubuntu 18.10 server

### ISSUE THREAD

**Issue by cempayzin** [microsoft/vcpkg#4700]
here is the log

Cem

[1/29] /usr/bin/c++   -I/home/linxa/vcpkg/buildtrees/flatbuffers/src/v1.9.0-7dcae80280/include -I/home/linxa/vcpkg/buildtrees/flatbuffers/src/v1.9.0-$
FAILED: CMakeFiles/flatbuffers.dir/src/code_generators.cpp.o
/usr/bin/c++   -I/home/linxa/vcpkg/buildtrees/flatbuffers/src/v1.9.0-7dcae80280/include -I/home/linxa/vcpkg/buildtrees/flatbuffers/src/v1.9.0-7dcae80$
In file included from /home/linxa/vcpkg/buildtrees/flatbuffers/src/v1.9.0-7dcae80280/include/flatbuffers/flexbuffers.h:24,
                 from /home/linxa/vcpkg/buildtrees/flatbuffers/src/v1.9.0-7dcae80280/include/flatbuffers/idl.h:26,
                 from /home/linxa/vcpkg/buildtrees/flatbuffers/src/v1.9.0-7dcae80280/include/flatbuffers/code_generators.h:22,
                 from /home/linxa/vcpkg/buildtrees/flatbuffers/src/v1.9.0-7dcae80280/src/code_generators.cpp:17:
/home/linxa/vcpkg/buildtrees/flatbuffers/src/v1.9.0-7dcae80280/include/flatbuffers/util.h: In function ‘int flatbuffers::FromUTF8(const char**)’:
/home/linxa/vcpkg/buildtrees/flatbuffers/src/v1.9.0-7dcae80280/include/flatbuffers/util.h:324:45: error: type qualifiers ignored on cast result type $
   if ((static_cast<const unsigned char>(**in) << len) & 0x80) return -1;  // Bit after leading 1's must be 0.
                                             ^
cc1plus: all warnings being treated as errors
[2/29] /usr/bin/c++   -I/home/linxa/vcpkg/buildtrees/flatbuffers/src/v1.9.0-7dcae80280/include -I/home/linxa/vcpkg/buildtrees/flatbuffers/src/v1.9.0-$
FAILED: CMakeFiles/flatbuffers.dir/src/idl_gen_text.cpp.o
/usr/bin/c++   -I/home/linxa/vcpkg/buildtrees/flatbuffers/src/v1.9.0-7dcae80280/include -I/home/linxa/vcpkg/buildtrees/flatbuffers/src/v1.9.0-7dcae80$
In file included from /home/linxa/vcpkg/buildtrees/flatbuffers/src/v1.9.0-7dcae80280/include/flatbuffers/flexbuffers.h:24,
                 from /home/linxa/vcpkg/buildtrees/flatbuffers/src/v1.9.0-7dcae80280/src/idl_gen_text.cpp:20:
/home/linxa/vcpkg/buildtrees/flatbuffers/src/v1.9.0-7dcae80280/include/flatbuffers/util.h: In function ‘int flatbuffers::FromUTF8(const char**)’:
/home/linxa/vcpkg/buildtrees/flatbuffers/src/v1.9.0-7dcae80280/include/flatbuffers/util.h:324:45: error: type qualifiers ignored on cast result type $
   if ((static_cast<const unsigned char>(**in) << len) & 0x80) return -1;  // Bit after leading 1's must be 0.
                                             ^
cc1plus: all warnings being treated as errors
[3/29] /usr/bin/c++   -I/home/linxa/vcpkg/buildtrees/flatbuffers/src/v1.9.0-7dcae80280/include -I/home/linxa/vcpkg/buildtrees/flatbuffers/src/v1.9.0-$
FAILED: CMakeFiles/flatbuffers.dir/src/idl_parser.cpp.o
/usr/bin/c++   -I/home/linxa/vcpkg/buildtrees/flatbuffers/src/v1.9.0-7dcae80280/include -I/home/linxa/vcpkg/buildtrees/flatbuffers/src/v1.9.0-7dcae80$
In file included from /home/linxa/vcpkg/buildtrees/flatbuffers/src/v1.9.0-7dcae80280/include/flatbuffers/flexbuffers.h:24,
                 from /home/linxa/vcpkg/buildtrees/flatbuffers/src/v1.9.0-7dcae80280/include/flatbuffers/idl.h:26,
                 from /home/linxa/vcpkg/buildtrees/flatbuffers/src/v1.9.0-7dcae80280/src/idl_parser.cpp:23:
/home/linxa/vcpkg/buildtrees/flatbuffers/src/v1.9.0-7dcae80280/include/flatbuffers/util.h: In function ‘int flatbuffers::FromUTF8(const char**)’:
/home/linxa/vcpkg/buildtrees/flatbuffers/src/v1.9.0-7dcae80280/include/flatbuffers/util.h:324:45: error: type qualifiers ignored on cast result type $
   if ((static_cast<const unsigned char>(**in) << len) & 0x80) return -1;  // Bit after leading 1's must be 0.
                                             ^
cc1plus: all warnings being treated as errors
ninja: build stopped: subcommand failed.

**Comment by youknowone** [comment]
Check whether  #4853 fixed this problem. If not, add the condition matching to your environment into `no-werror.patch`

cc @Rastaban

**Comment by wangli28** [comment]
Thanks for posting this issue. This issue has been fixed. You can update vcpkg and rebuild it. I am closing this issue for now.

./vcpkg  install flatbuffers
The following packages will be built and installed:
    flatbuffers[core]:x64-linux
Starting package 1/1: flatbuffers:x64-linux
Building package flatbuffers[core]:x64-linux...
-- Downloading https://github.com/google/flatbuffers/archive/v1.11.0.tar.gz...
-- Extracting source /home/vwangli/Lily/vcpkg/downloads/google-flatbuffers-v1.11.0.tar.gz
-- Applying patch ignore_use_of_cmake_toolchain_file.patch
-- Applying patch no-werror.patch
-- Applying patch fix-uwp-build.patch
-- Using source at /home/vwangli/Lily/vcpkg/buildtrees/flatbuffers/src/v1.11.0-acaaed93bd
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package flatbuffers[core]:x64-linux... done
Installing package flatbuffers[core]:x64-linux...
Installing package flatbuffers[core]:x64-linux... done
Elapsed time for package flatbuffers:x64-linux: 45.75 s

Total elapsed time: 45.75 s

The package flatbuffers:x64-linux provides CMake targets:

    find_package(Flatbuffers CONFIG REQUIRED)
    target_link_libraries(main PRIVATE flatbuffers::flatbuffers)
