### ISSUE TITLE
What copyright file should be installed in case of a dual license code?

### ISSUE THREAD

**Issue by jayeshbadwaik** [Microsoft/vcpkg#4701]
Suppose a code is dual-licensed under license A and license B, then what files should be installed as the `copyright` file?

**Comment by ras0219-msft** [comment]
The most permissive license as `copyright` and the other license just as a loose file inside `share/${PORT}`. 

In code licensed as LGPL + proprietary, the lgpl license should go into `copyright` and the proprietary license should be loose.

**Comment by jayeshbadwaik** [comment]
Thanks.
