### ISSUE TITLE
Dependency packages for my port

### ISSUE THREAD

**Issue by rdxernest** [microsoft/vcpkg#4710]
Hi,
I'm trying to create a port for `prometheus-cpp`. It uses curl and calls `find_dependency` in its CMake file. Is there a way to make the port file the way it first installs `curl` from vcpkg to satisfy the port's dependency?

**Comment by MarkIanHolland** [comment]
Hi mate, 
The [build-depends](https://vcpkg.readthedocs.io/en/latest/maintainers/control-files/#build-depends) component of the CONTROL file is what you're looking for. It also looks like there is a currently PR for a prometheus-cpp port #4694.

**Comment by kreuzerkrieg** [comment]
Agggrrrr... Already created PR...

As of build-depends, already figured it out, but its kinda inconvenient, why the `./vcpkg build` command just can first invoke `install` for build-dependencies and then proceed with a build?

**Comment by MarkIanHolland** [comment]
Ah, brilliant timing 😄 
Do you mean it would be better with a (Y/n) style prompt?

**Comment by kreuzerkrieg** [comment]
I dont think the prompt is needed, build-dependencies are prerequisites, build cannot be completed without installing it. it's like `apt` or `yum`, it doesnt ask if it should install dependencies of the package you want to install, right?

**Comment by wangli28** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
