### ISSUE TITLE
Getting OpenMP with vcpkg?

### ISSUE THREAD

**Issue by AFWSI** [microsoft/vcpkg#4712]
How do I get OpenMP using vcpkg. I have searched online ,but haven't found the answer to my question. I'm trying to build something that requires the following and I have all of them but OpenMP. Or is this something that can't be get with vcpkg?

```
Dependencies

Require: Boost, GLM, Eigen Optional: TBB, OpenMP
```

**Comment by Neumann-A** [comment]
OpenMP is not a third party library. A such it is not available in vcpkg. 
OpenMP is something which the compiler you intend to use must support. 
(It is basically a language extension using a lot of #pragmas)

see https://www.openmp.org/
or https://en.wikipedia.org/wiki/OpenMP

**Comment by LarryIII** [comment]
OpenMP is integrated with Compiler(gcc, clang, MSVC...). It is not a third party library. So it is could not get by vcpkg.

**Comment by westfly** [comment]
> How do I get OpenMP using vcpkg. I have searched online ,but haven't found the answer to my question. I'm trying to build something that requires the following and I have all of them but OpenMP. Or is this something that can't be get with vcpkg?
> 
> ```
> Dependencies
> 
> Require: Boost, GLM, Eigen Optional: TBB, OpenMP
> ```

Just add  in CMakeLists.txt 
```
find_package(OpenMP REQUIRED)
```
