### ISSUE TITLE
[VTK 8.1.0] include dir has no vtk/ root

### ISSUE THREAD

**Issue by Dimension4** [microsoft/vcpkg#4720]
The VTK package's include directory is `PACKAGE_ROOT/include` but shouldn't it be `PACKAGE_ROOT/include/vtk`? I know how to fix this but is this intended behavior?

Edit: Same for libharu

**Comment by richy46** [comment]
+1

**Comment by wangli28** [comment]
Hi @Dimension4, I installed **vtk** and **libharu** successfully with Visual Studio 2017 and VCPKG latest source. I found **vtk** and **libharu** package's include directory is right. 
![image](https://user-images.githubusercontent.com/47812810/60576045-35dca100-9daf-11e9-8b77-ef0415d1687a.png)

**Comment by Dimension4** [comment]
@wangli28 It also works for me, I was just not liking that the header files are located directly in the *global* header space so one can write `#include <vtkXYZ.h>` instead of `#include <vtk/vtkXZY.h>`. But I guess this is for compatability reasons with other libraries that expect vtk to be in the root folder.
