### ISSUE TITLE
linux intellisense not synchronizing 'vcpkg/installed/x64-linux/include'

### ISSUE THREAD

**Issue by fuocor** [microsoft/vcpkg#4721]
I'm not sure if it's a vcpkg or Visual Studio tooling problem but the files in the ~/git/microsoft/vcpkg/installed/x64-linux/include are not synchronizing with Visual Studio's intellisense using WSL.

The:
 ```C:\Users\<username\AppData\Local\Microsoft\Linux\HeaderCache\1.0\1372205193\includes.xml```
contains a reference: 
```<include date="2018-11-13">/usr/git/microsoft/vcpkg/installed/x64-linux/include</include>```

and the:
 ```C:\Users\<username>\AppData\Local\Microsoft\Linux\HeaderCache\1.0\1372205193\settings.xml.unused```
has it as well
```<includeDirs><![CDATA[...;/usr/git/microsoft/vcpkg/installed/x64-linux/include]]></includeDirs>```

but none of the files are being copied the developer machine for that directory whereas all the others are.

I tried manually updating by renaming the file to ```settings.xml`` with the same result.

any help is appreciated.

**Comment by itodirel** [comment]
Hi, it seems like the problem is that you did not rename the file to remove the .unused extension. Please rename "settings.xml.unused" to "settings.xml" after you added the path to includeDirs. Please do not modify the includes.xml file.

**Comment by fuocor** [comment]
thanks, that was half of the problem. The other half is the fact that rsync does not appear to work with WSL. rsync would create the directory structure but not copy any files.
Changing it to sftp_ssh got the files copied

**Comment by Voskrese** [comment]
> Since 'rsync' doesn't work for me, I found out you can revert to the previous .zip via sftp method by:
> 
>     Rename the HeaderCache settings.xml.unused file to settings.xml
>     Change the syncMethod to sftp_ssh
>     Update from Tools->Options->Cross Platform->Connection Manager->Remote Headers Intellisense Manager

https://developercommunity.visualstudio.com/content/problem/300362/linux-cmake-intellisense-headercache-not-downloadi.html

**Comment by PhoebeHui** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.
