### ISSUE TITLE
Cannot run bootstrap-vcpkg.bat successfully.

### ISSUE THREAD

**Issue by Elite-stay** [microsoft/vcpkg#4723]
```c1xx : fatal error C1356: 无法找到 mspdbcore.dll```
I can manually compile vcpkg.sln successfully.
My vs is 2017 v15.9.0 on Windows 7. My "Visual Studio IDE" install path is ```d:\Program Files\Microsoft Visual Studio\2017\Professional```, and "" is ```C:\Program Files (x86)\Microsoft Visual Studio\Shared```.

**Comment by Voskrese** [comment]
mklink ?

**Comment by Elite-stay** [comment]
> 
> 
> mklink ?

I don't understand.

**Comment by wangli28** [comment]
@Elite-stay, thank you for posting the issue, does the issue still occur?

**Comment by Elite-stay** [comment]
> 
> 
> @Elite-stay, thank you for posting the issue, does the issue still occur?

Yes, it still occurs. I have installed visual studio 2019.

**Comment by PhoebeHui** [comment]
This shoud not a be a problem now, please get latest source and try again.
