### ISSUE TITLE
vcpkg how to  build an new installer package(such as  boost-1-64-0)

### ISSUE THREAD

**Issue by daofeizhen** [microsoft/vcpkg#4724]
I need the installer package of  boost-1-64-0,but it requires a lot of library dependencies,so how to build it?What are the naming rules for VCPKG when it compiles boost?The name of VCPKG compiling boost is different from the general compilation method that compiles boost.

**Comment by PhoebeHui** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen
