### ISSUE TITLE
opencv build error

### ISSUE THREAD

**Issue by hmoenck** [microsoft/vcpkg#4725]
Vcpkg fails to configure the opencv build. Apparently ffmpeg could not be downloaded. This can be circumvented by downloading it manually and putting it in the opencv-cache folder.  
Steps to reproduce:
- Download vcpkg (I just downloaded the zip and unzipped it)
- cd vcpkg
- bootstrap.bat
- ./vcpkg install opencv[opengl,ffmpeg,dnn]:x64-windows  

I suppose only the ffmpeg option is relevant here.  It was functional before and still is on our old/modified fork: https://github.com/BioroboticsLab/RF_vcpkg
System: Windows 7, x64  
cl: Microsoft (R) C/C++ Optimizing Compiler Version 19.15.26729 for x64  
[config-x64-windows-out.log](https://github.com/Microsoft/vcpkg/files/2579890/config-x64-windows-out.log)

**Comment by NancyLi1013** [comment]
Hi @hmoenck, thanks for posting this issue. This port has been updated. I can't reproduce it locally now. Could you please update it and try it again?
