### ISSUE TITLE
Add cmocka

### ISSUE THREAD

**Issue by ansasaki** [Microsoft/vcpkg#4728]
Please, consider adding a port of cmocka to vcpkg.

cmocka is "an elegant unit testing framework for C with support for mock objects. It only requires the standard C library, works on a range of computing platforms (including embedded) and with different compilers."

Home: https://cmocka.org/
Git: git://git.cryptomilk.org/projects/cmocka.git
Releases: https://cmocka.org/files/

**Comment by myd7349** [comment]
Hi! @ansasaki I noticed you created a PR for this lib. But it was closed because you did not sign a CLA.

Are you still work on this port? It will be great to have `cmocka` included in `vcpkg`.

**Comment by ansasaki** [comment]
Hello @myd7349,
I was working in this port, but gave up on it because of the CLA.
Feel free to create your own port for ``cmocka``.

**Comment by myd7349** [comment]
@ansasaki Thanks for letting me know that. I'd like to create a PR for this.
