### ISSUE TITLE
Runnning install behind a corporate proxy

### ISSUE THREAD

**Issue by josephwinston** [Microsoft/vcpkg#4729]
I am behind a corporate proxy (ntlm).  I receive the following error when I try to install any package.

```
$ .\vcpkg install sqlite3
The following packages will be built and installed:
    sqlite3[core]:x86-windows
Starting package 1/1: sqlite3:x86-windows
Building package sqlite3[core]:x86-windows...
A suitable version of git was not found (required v2.17.1). Downloading portable git v2.17.1...
Downloading git...
  https://github.com/git-for-windows/git/releases/download/v2.17.1.windows.1/MinGit-2.17.1-32-bit.zip -> D:\home\josephwinston\src\Remote\GIT\Mircosoft\vcpkg\downloads\MinGit-2.17.1-32-bit.zip
WinHttpSendRequest() failed: 12029
```
This happens when I set http_proxy and https_proxy to my cntlm instance.  The same error occurs with the uppercase versions of the environment are used.  Finally, I tried both uppercase and lowercase versions of the proxy environment variables pointing to ntlm directly using the form of 
http://user:password@your-proxy-ip-address:port

I do not have any issues downloading https://github.com/git-for-windows/git/releases/download/v2.17.1.windows.1/MinGit-2.17.1-32-bit.zip using a browser, wget, or curl.

Running `netsh.exe winhttp import proxy source=ie` gives me the following error:

```
Error writing proxy settings. (5) Access is denied.


Current WinHTTP proxy settings:

    Direct access (no proxy server).
```

**Comment by Voskrese** [comment]
https://blogs.technet.microsoft.com/netgeeks/2018/06/19/winhttp-proxy-settings-deployed-by-gpo/

**Comment by NancyLi1013** [comment]
@josephwinston Thanks for posting this issue. Please feel free to reopen this or open a new issue if this is still a problem for you.
