### ISSUE TITLE
Is it possible to install vspkg in 32 bit Windows?

### ISSUE THREAD

**Issue by CODER591** [Microsoft/vcpkg#4730]
Hello, I got a problem that  I clone the repository and trying to install but, I get this problem:
I have 32 bit Windows and 32 bit Visual Studio

Building vcpkg.exe ...

```
TRACKER : error TRK0002: не удалось выполнить команду: ""C:\Program Files\Micro
soft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\bin\HostX64\x86\CL.
exe" @C:\Users\Galya\AppData\Local\Temp\tmpabe08566da4a461a94982e79a8eb1031.rsp
". Код ошибки FileTracker: 0xd8 [C:\Users\Galya\Desktop\Новая папка\vcpkg\tools
rc\vcpkglib\vcpkglib.vcxproj]
Write-Error : Building vcpkg.exe failed. Please ensure you have installed Visua
l Studio with the Desktop C++ workload and the Windows SDK for Desktop C++.
C:\Users\Galya\Desktop\Новая папка\vcpkg\scripts\bootstrap.ps1:384 знак:16
+     Write-Error <<<<  "Building vcpkg.exe failed. Please ensure you have inst
alled Visual Studio with the Desktop C++ workload and the Windows SDK for Deskt
op C++."
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,Microsoft.PowerShell.Commands.WriteErrorCommand

```
I try to reinstall all Windows SDK what I have . And trying to install all  Windows SDK in VisualStudio. BUT IT woud not help. That all feels like pain in the ass. I am tired of reinstalling this all
How to fix that?

**Comment by CODER591** [comment]
@Voskrese , Не помогло. Я пробовал кучу раз перекачивать, переустанавливать СДК . Но бесполезно.
там где Tracker:
```
TRACKER : error TRK0002: не удалось выполнить команду: ""C:\Program Files\Micro
soft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\bin\HostX64\x86\CL.
```
Я прошел по тому пути, и попробовал запустить СL. 
Пишет что не совпадает разрядность необходима 64-рязрядная система. Потому и спрашиваю.

**Comment by Voskrese** [comment]
окей, тогда начнем с начала, выложите весь полный лог, что запускаете и как компилируете
по последнему сообщению у вас, Host как раз X64 = HostX64

**Comment by CODER591** [comment]
Полный лог вверху в вопросе.
1) скачал
2)распаковал
3) запустил  Командную строку разработчика VS 2017 
4) перешел в папку в которую скачал 
5) ввёл  .\bootstrap-vcpkg.bat
6) получил ошибку

**Comment by Voskrese** [comment]
2. запустил Командную строку разработчика VS 2017 

С этого места по подробнее, там две версии, для х86 и х64

**Comment by Voskrese** [comment]
странно, а по логу х64, в общем даже и не знаю что подсказать. 
попробуйте запустить powershell.exe и там выполнить bootstrap
**без** запуска "Командную строку разработчика VS 2017"

**Comment by CODER591** [comment]
Пробовал, тоже самое

сб, 17 лист. 2018 о 21:37 Voskrese <notifications@github.com> пише:

**Comment by shns** [comment]
e8371c1
It seems like using the 64bit compiler even if on 32bit Windows when x64 is specified to PreferredToolArchitecture.

**Comment by ctrlaltca** [comment]
Same problem, changing the line to `"/p:PreferredToolArchitecture=x86"` makes vcpkg build correctly on Win7 32bit.

**Comment by CODER591** [comment]
Thanks, but where i should input this line? And on whitch stage?

**Comment by CODER591** [comment]
Big Thanks, today I ll try it!

**Comment by ctrlaltca** [comment]
This problem probably deserves a proper fix, or at least a documentation change (either "use this patch" or "x86 is not working/supported.")
