### ISSUE TITLE
Qt5-Location Port Requested (for QtPositioning)

### ISSUE THREAD

**Issue by DigitalInBlue** [microsoft/vcpkg#4738]
It appears as though none of the Qt5 ports pull in the QtLocation library as the QtPositioning headers are not being installed.  A quick search shows that qtlocation-everywhere-src-5.11.2.tar.xz does not seem to be in the current ports.

**Comment by DigitalInBlue** [comment]
I don't have time to do a pull request at the moment, but a working ```portfile.cmake``` is attached.  Put it into a ```qt5-location``` folder and make a CONTROL file...and its good to go.

[portfile.cmake.txt](https://github.com/Microsoft/vcpkg/files/2587914/portfile.cmake.txt)

**Comment by JackBoosY** [comment]
Hi @DigitalInBlue, thanks for reporting this issue!
Qt5-location has been added in vcpkg. Please update vcpkg and build qt5-location.

Thanks.
