### ISSUE TITLE
Building package tiff:x86-uwp failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by ilyavitek** [Microsoft/vcpkg#4745]
C:\Users\ILYVOI\Git\vcpkg>.\vcpkg install opencv[contrib]:x86-uwp --recurse
The following packages will be built and installed:
  * libpng[core]:x86-uwp
    opencv[contrib,core,eigen,flann,jpeg,opengl,png,tiff]:x86-uwp
  * opengl[core]:x86-uwp
  * tiff[core]:x86-uwp
Additional packages (*) will be modified to complete this operation.
Starting package 1/4: tiff:x86-uwp
Building package tiff[core]:x86-uwp...
-- Using cached C:/Users/ILYVOI/Git/vcpkg/downloads/tiff-4.0.10.tar.gz
-- Using source at C:/Users/ILYVOI/Git/vcpkg/buildtrees/tiff/src/4.0.10-208d032666
-- Configuring x86-uwp
-- Building x86-uwp-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: C:/Users/ILYVOI/Git/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No
    Working Directory: C:/Users/ILYVOI/Git/vcpkg/buildtrees/tiff/x86-uwp-dbg
    See logs for more information:
      C:\Users\ILYVOI\Git\vcpkg\buildtrees\tiff\install-x86-uwp-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/tiff/portfile.cmake:37 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package tiff:x86-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: tiff:x86-uwp
  Vcpkg version: 2018.10.20-nohash

Additionally, attach any relevant sections from the log files above.

C:\Users\ILYVOI\Git\vcpkg>.\vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

C:\Users\ILYVOI\Git\vcpkg>git pull
Already up to date.

[install-x86-uwp-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2589420/install-x86-uwp-dbg-out.log)

**Comment by BenWoodford** [comment]
+1 this problem, already up to date

**Comment by blo85** [comment]
Same problem here too.

**Comment by BenWoodford** [comment]
[install-x86-uwp-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2599591/install-x86-uwp-dbg-out.log)

**Comment by BenWoodford** [comment]
Try `git checkout 02839ae4a83d505bae17d5856ce851af29c89c65` and then install `opencv` again. It solved the issue for me, evidently `libtiff:4.10` has some problems to be worked out.

**Comment by rleigh-codelibre** [comment]
@BenWoodford The libtiff update was a routine point release; I would not have expected any compatibility problems to arise from it.  However, my knowledge of UWP is sadly limited, so I don't have a great deal of insight to offer I am afraid.

**Comment by blo85** [comment]
@BenWoodford thanks for your help. Now i am getting this error:

File does not have the expected hash: url : [ https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 ].....................

during ".\vcpkg install opencv[contrib]:x86-uwp --recurse"    execution.

Ideas?
BR!

**Comment by rleigh-codelibre** [comment]
@BenWoodford Might be worth opening a separate issue since this is unrelated to `tiff` and UWP.

**Comment by paulio** [comment]
Oh same problem again. 
The following packages will be built and installed:
    opencv[contrib,core,default-features]:x86-uwp -> 4.5.5
  * opencv4[contrib,core,default-features,dnn,jpeg,png,quirc,tiff,webp]:x86-uwp -> 4.5.5#4
  * tiff[core,jpeg,lzma,zip]:x86-uwp -> 4.3.0#8
  ---------
error: building tiff:x86-uwp failed with: BUILD_FAILED

What's the workaround/fix?
