### ISSUE TITLE
Update ffmpeg to 4.x.

### ISSUE THREAD

**Issue by hanseuljun** [Microsoft/vcpkg#4750]
The version of ffmpeg is 3.3 in vcpkg while 4.1 got released recently. I guess fixing
https://github.com/Microsoft/vcpkg/pull/3578 would be a good starting point...

**Comment by jasjuang** [comment]
I will try later and see whether upgrading to 4.1 simply solves the problem in #3578. Were you able to resolve the problems in #3578 on your end?

**Comment by hanseuljun** [comment]
It's pretty awkward to say this, but your pull request works on my machine. Congratulations, it works! How about reporting the success of your pull request after you check this out in one of your machines?

**Comment by hanseuljun** [comment]
I tried vcpkg install ffmpeg with your pull request and the installation had no problems. Should I test some more? If not, congratulations! It works!

**Comment by jasjuang** [comment]
If you read the details of #3578 yes the ffmpeg port itself works but it breaks pangolin which depends on ffmpeg. Are you able to get pangolin to work?

**Comment by hanseuljun** [comment]
I tried vcpkg install pangolin --head and it failed... I see what the problem is...
I attached my error log. The error happens in [77/99], line 9606-9614...

[install-x86-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2597876/install-x86-windows-dbg-out.log)

**Comment by wangli28** [comment]
Hi @hanseuljun ,
Latest version is 4.1, you can update vcpkg and rebuild.
Thanks.

**Comment by hanseuljun** [comment]
@wangli28 Thanks for noticing me!
