### ISSUE TITLE
zziplib doesn't build on x64-linux

### ISSUE THREAD

**Issue by stoperro** [microsoft/vcpkg#4751]
zziplib doesn't compile on linux due missing configuration file. When added, it compiles.

[fix_zziplib.zip](https://github.com/Microsoft/vcpkg/files/2591670/fix_zziplib.zip)

afterwards ./vcpkg install zziplib:x64-linux should work.

**Comment by JackBoosY** [comment]
Hi @stoperro, thanks for reporting this issue!
I've fixed this issue. Please update vcpkg and rebuild zziplib.
Thanks.
