### ISSUE TITLE
cmake integration for nlopt

### ISSUE THREAD

**Issue by rjdmoore** [Microsoft/vcpkg#4753]
nlopt package installs fine for x64-windows, but when trying to build a cmake project, configuration fails with the following error:

The imported target "NLopt::nlopt" references the file
   "C:/path/to/vpckg/installed/debug/lib/nlopt.lib"
but this file does not exist...

The library exists at "C:/path/to/vpckg/installed/x64-windows/debug/lib/nlopt.lib". The error is due to incorrect definition of _IMPORT_PREFIX in NLoptLibraryDepends.cmake (can be fixed by removing one of the get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH) lines in NLoptLibraryDepends.cmake).

I'm not sure how to modify the cmake input files such that this configuration is done correctly.

**Comment by Neumann-A** [comment]
I observe a similar behavior for fftw3.
Since those files are automaticly generated by cmake it could be a cmake bug?

**Comment by vicroms** [comment]
This should have been fixed by #5459. 

I tested by adding this line at the end of the portfile and checking that the installation was successful `vcpkg_test_cmake(PACKAGE_NAME NLopt)`.

Please open a new issue if you still have this problem.
