### ISSUE TITLE
Error building Qt5-base on Debian 

### ISSUE THREAD

**Issue by Izowiuz** [microsoft/vcpkg#4755]
Today I have tried to build qt5-base on Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 and got hit by:

`Error: Building package qt5-base:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with .\vcpkg update, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
Package: qt5-base:x64-linux
Vcpkg version: 2018.10.20-unknownhash
Additionally, attach any relevant sections from the log files above.`

Contents of qt5-base/build-x64-linux-dbg-err.log:

`/home/izowiuz/git/vcpkg/buildtrees/qt5-base/src/5.11.2-86acb4d0f7/src/network/access/qnetworkaccessdebugpipebackend_p.h:0: Note: No relevant classes found. No output generated.
/home/izowiuz/git/vcpkg/buildtrees/qt5-base/src/5.11.2-86acb4d0f7/src/network/ssl/qsslsocket_openssl_p.h:0: Note: No relevant classes found. No output generated.
/home/izowiuz/git/vcpkg/buildtrees/qt5-base/src/5.11.2-86acb4d0f7/src/gui/painting/qplatformbackingstore.h:0: Note: No relevant classes found. No output generated.
/home/izowiuz/git/vcpkg/buildtrees/qt5-base/src/5.11.2-86acb4d0f7/src/widgets/kernel/qwidgetbackingstore_p.h:0: Note: No relevant classes found. No output generated.
WARNING: Failure to find: /home/izowiuz/git/vcpkg/buildtrees/qt5-base/src/5.11.2-86acb4d0f7/src/3rdparty/sqlite/sqlite3.c
make[4]: *** No rule to make target '/home/izowiuz/git/vcpkg/buildtrees/qt5-base/src/5.11.2-86acb4d0f7/src/3rdparty/sqlite/sqlite3.c', needed by '.obj/sqlite3.o'.  Stop.
make[3]: *** [sub-sqlite-make_first] Error 2
make[2]: *** [sub-sqldrivers-make_first] Error 2
make[1]: *** [sub-plugins-make_first] Error 2
make: *** [sub-src-make_first] Error 2
`

Contents of qt5-base/build-x64-linux-dbg-out.log as attachment:
[build-x64-linux-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2592195/build-x64-linux-dbg-out.log)

**Comment by JackBoosY** [comment]
Hi @Izowiuz,
Qt5 has been upgraded to 5.12.3, I can't reproduce this issue on my machine, please update vcpkg, rebuild qt5-base and recheck this issue.

Thanks.

**Comment by Izowiuz** [comment]
Although I have switched to Ubuntu 18.X releases for my dev and production machines I was able to check that this was indeed fixed under Debian 9

I have downloaded Debian 9 netboot ISO and installed it in VBox.
I have downloaded minimal set of required packages necessary to run vcpkg.
I then successfully built qt5-base package.

Seems like it is fixed :]
