### ISSUE TITLE
wxwidgets installed but not detected by FindwxWidgets.cmake

### ISSUE THREAD

**Issue by slodki** [microsoft/vcpkg#4756]
wxWidgets installed with simple `vcpkg install wxwidgets:x64-windows-static` without problems.
Simple minimal CMake project
```cmake
cmake_minimum_required(VERSION 3.12)
project(test)
find_package(wxWidgets REQUIRED
    COMPONENTS core qa html xml aui adv stc webview base scintilla)
```
[generates error](https://ci.appveyor.com/project/slodki/appveyor-tests#L39):
```
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS)
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files (x86)/CMake/share/cmake-3.12/Modules/FindwxWidgets.cmake:963 (find_package_handle_standard_args)
  C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake:247 (_find_package)
  CMakeLists.txt:6 (find_package)
```
because libraries are installed in non-standard directory (${WX_ROOT_DIR}/lib in place of ${WX_ROOT_DIR}/lib/vc141...). See
https://github.com/Kitware/CMake/blob/be9ad8279a29893943b342cc5ffdbf9868fb1b4c/Modules/FindwxWidgets.cmake#L544

**Comment by markusobi** [comment]
I created a slightly modified `FindwxWidgets.cmake`, which I placed in `vcpkg/ports/wxwidgets/Modules`, but I don't know where to fix the `CMAKE_MODULE_PATH` globally, so that cmake prefers this file over the default `FindwxWidgets.cmake`.

It works when modifying `CMAKE_MODULE_PATH ` in the project, which calls `find_package(wxWidgets MODULE REQUIRED)`, but I want to change `CMAKE_MODULE_PATH` from vcpkg.

I tried modifying the `CMAKE_MODULE_PATH` inside the portfile.cmake, but this didn't work.
The `CMAKE_MODULE_PATH` was still empty in my project.

this is what I tried to add in the https://github.com/Microsoft/vcpkg/blob/master/ports/wxwidgets/portfile.cmake :
```list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/Modules")```

**Comment by ldmnyblzs** [comment]
Try this in the vcpkg root directory:
`git checkout  6390113 ports\wxwidgets\`
It reverts wxWidgets to 3.1.0. You still have to specify `wxWidgets_LIB_DIR` manually, but after that it should work.
Neither 3.1.1 nor 3.1.2 worked for me, CMake created the wrong directory structure.

**Comment by fei4xu** [comment]
Same issue here. 
@markusobi Did you find a workaround in the end?

**Comment by markusobi** [comment]
> 
> 
> Same issue here.
> @markusobi Did you find a workaround in the end?

No, I ended up putting `list(APPEND CMAKE_MODULE_PATH "${_VCPKG_ROOT_DIR}/ports/wxwidgets/Modules")` before the `find_package(wxWidgets)` call on the client side.

The whole wxwidgets build system is a mess.

**Comment by zelid** [comment]
The same issue, @markusobi can you please share the modified vcpkg aware version of FindwxWidgets.cmake ?

**Comment by CaeruleusAqua** [comment]
My solution:
https://github.com/CaeruleusAqua/vcpkg-wx-find

**Comment by markusobi** [comment]
@zelid
I couldn't find a solution that works on linux too.

**Comment by HenryAWE** [comment]
Visual Studio solution works well on computer, but the cmake can't find the package when I use cmake to build the executable.

**Comment by Censacrof** [comment]
I'm having this issue too. I'm making a cross-platform project and I'd like to be able to use cmake on all platforms (Linux, Windows, Mac). Has anyone found a solution to this problem?

**Comment by jonathanverner** [comment]
I just stumbled into this too :-(

**Comment by jmkerloch** [comment]
Any update on this issue ? vcpkg is really useful but if we can't use it with wxWidgets there is no point in using it in our projects.

**Comment by jmkerloch** [comment]
> I created a slightly modified `FindwxWidgets.cmake`, which I placed in `vcpkg/ports/wxwidgets/Modules`, but I don't know where to fix the `CMAKE_MODULE_PATH` globally, so that cmake prefers this file over the default `FindwxWidgets.cmake`.
> 
> It works when modifying `CMAKE_MODULE_PATH ` in the project, which calls `find_package(wxWidgets MODULE REQUIRED)`, but I want to change `CMAKE_MODULE_PATH` from vcpkg.
> 
> I tried modifying the `CMAKE_MODULE_PATH` inside the portfile.cmake, but this didn't work.
> The `CMAKE_MODULE_PATH` was still empty in my project.
> 
> this is what I tried to add in the https://github.com/Microsoft/vcpkg/blob/master/ports/wxwidgets/portfile.cmake :
> `list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/Modules")`

Could you share with us the modified FindwxWidgets.cmake ?

**Comment by nickoe** [comment]
@jmkerloch  I am using this version, slightly modified from what the original author id, see the revisions on the gist.

https://gist.github.com/nickoe/d3c224a2587eff8ea959bc383a993520/

**Comment by jmkerloch** [comment]
@nickoe I just tried your file and now I can find wxWidgets from VCPKG. Thanks !

**Comment by SeanOMik** [comment]
> @jmkerloch I am using this version, slightly modified from what the original author did, see the revisions on the gist.
> 
> https://gist.github.com/nickoe/d3c224a2587eff8ea959bc383a993520/
> 
> I am not exactly sure why this special findwxwidgets cmake file is needed, it would be nice if a fix could be upstreamed in cmake or vcpkg.

I tried that but I got lots of linker errors: https://pastebin.com/xCGEJLLc

**Comment by jmkerloch** [comment]
@SeanOMik  How did you link to wxWidgets in your CMakeList.txt ?

**Comment by SeanOMik** [comment]
> @SeanOMik How did you link to wxWidgets in your CMakeList.txt ?
```
This is how I find it:
find_package(wxWidgets 3.1 COMPONENTS core base REQUIRED)
And link:
target_link_libraries(discord_client PRIVATE ${wxWidgets_LIBRARY})
```

**Comment by brad-anderson** [comment]
I've updated the patch @nickoe did for the latest version of FindwxWidgets.cmake (CMake 3.17.2).

https://gist.github.com/brad-anderson/876a8c581abf285dd20b3c532bf48bd2

**Comment by jmkerloch** [comment]
@brad-anderson how do you integrate  your FindwxWidgets.cmake on your CMakeList.txt ?

The file is working for a release  version in  Windows but for debug version the path to the .lib are not correct

For example here is the lib include for net module
`<vcpkg_root>\installed\x64-windows\lib\wxbase31u_net.lib` instead of `<vcpkg_root>\installed\x64-windows\debug\lib\wxbase31ud_net.lib`

Does anyone have an idea how to get the correct path ?

**Comment by jmkerloch** [comment]
For the debug version I wasn't selecting the correct version in Visual Studio...
But for linux wxWidgets can be install but is not found with updated FindwxWidgets.cmake

**Comment by myirci** [comment]
Hi, I also have a similar issue. 
I can build wxWidgets (3.1.4) projects from VS 2019 using the installed libraries with  vcpkg (both with dynamic and static linking: x64-windows and x64-windows-static) but with cmake (3.18.1) I could not figure out how to do that. find_package always fails and complains about missing: wxWidgets_LIBRARIES.  

Is there any progress on this issue? 
Thanks!

**Comment by LilyWangL** [comment]
I will confirm and fix this issue soon.

**Comment by JCBurnside** [comment]
can confirm that this is still broken at this point in time.

**Comment by gvcallen** [comment]
Also broken for me.

**Comment by gvcallen** [comment]
Any temporary fix for this please? Running Windows

**Comment by gvcallen** [comment]
Using this patch in CMAKE https://gist.github.com/brad-anderson/876a8c581abf285dd20b3c532bf48bd2 I am able to find wxWidgets but get loads of linking errors on Windows

**Comment by Alvaroalloc** [comment]
Did anyone find out how to do it?, or a solution will be merged to master?

**Comment by PhoebeHui** [comment]
PR https://github.com/microsoft/vcpkg/pull/13361 would address this issue.

**Comment by fedapo** [comment]
This issue seems closed as of today, but I can't still build a basic wxWidgets project with CMake under Linux. Just for the record, the same CMake project builds ok when using the wxWidgets libraries from the Linux distro (Ubuntu 20.04) instead of vcpkg. The only catch is that this line is required in `CMakeLists.txt`:

```cmake
include(${wxWidgets_USE_FILE})
```

This is not indicated in the message provided at the end of the installation of wxWidgets in vcpkg, which reads:

```shell
> ./vcpkg install wxwidgets

...

The package wxwidgets provides CMake integration:

    find_package(wxWidgets REQUIRED)
    target_include_directories(main PRIVATE ${wxWidgets_INCLUDE_DIRS})
    target_link_libraries(main PRIVATE ${wxWidgets_LIBRARIES})
```

**Comment by dg0yt** [comment]
> A note for those who are stuck: make sure your CMake build matches the `--triplet` you used when you ran `vcpkg install wxwidgets`.

This goes without saying, unrelated to wxWidgets.

There have been significant improvements in the past months, including basic CI testing of `find_package(wxWidgets)`.
However, linux support is still incomplete, due to lack of gtk3 in vcpkg (and lack of gtk4 support in wxWidgets).

**Comment by EvanBalster** [comment]
Running into this same issue.  CMake isn't able to locate a `x64-windows-static` build of wxWidgets while configuring a Visual Studio x64 project.

> @drinkitup777 A note for those who are stuck: make sure your CMake build matches the `--triplet` you used when you ran `vcpkg install wxwidgets`.

I'm building a small executable utility so I don't know how I can match the `-static` part of the triplet other than declaring `set(wxWidgets_STATIC ON)` before `find_package(wxWidgets ...`

**Comment by dg0yt** [comment]
@EvanBalster Please open a new new issue, following the current issue templates. There is just too much change in wxwidgets between 2018 and 2022. Again: CMake usage (from a user perspective) is tested in vcpkg CI.

**Comment by BunnySakura** [comment]
**The present of September 2022**
- English
  The problem has been solved, but there seems to be a small problem. Especially on VS 2022, you need to manually configure `VCPKG_TARGET_TRIPLET` to correspond to the platform information, such as `x64-windows-static`.

- 中文
  这个问题已经解决了，但是瞅着似乎还有一点小问题。尤其是在VS 2022上，需要手动配置一下`VCPKG_TARGET_TRIPLET`，改为对应平台信息，例如`x64-windows-static`。
