### ISSUE TITLE
libMpg123 x64-uwp, x86-uwp, arm-uwp. Post Build Checks Failed.  

### ISSUE THREAD

**Issue by imixal** [microsoft/vcpkg#4763]
Hi all. Thanks a lot for your work!

There are problems with post-build for UWP (all architecture).  Build is failing with status POST_BUILD_CHECKS_FAILED. 

Can you help, please?

**Comment by PhoebeHui** [comment]
@imixal, I didn't find port libmpg123 in vcpkg, please file a new issue with correct port name if it still be an problem for you.
