### ISSUE TITLE
Building sfml using vcpkg, builds only debug libraries

### ISSUE THREAD

**Issue by seccpur** [Microsoft/vcpkg#4771]
Thanks to all the vcpkg team for coming up with this versatile tool. Recently I was able to build static libraries ( latest version of vcpkg ) for sfml using the following command:

`.\vcpkg install sfml:x64-windows-static`

It built only the debug  libraries and failed to build release libraries. Please advice as to what possibly might be the reason for this. BTW I used VC++2017 to build vcpkg itself, so any connection ?

**Comment by PhoebeHui** [comment]
@seccpur, thank you for posting the issue, does the issue still occur? could you try vcpkg latest revision?

PS F:\vcpkg\src> ./vcpkg version
Vcpkg package management program version 2018.11.23-nohash

It installed successfully with vcpkg latest version and vs 2017 15.9.7:
Starting package 7/7: sfml:x64-windows-static
Building package sfml[core]:x64-windows-static...
-- Downloading https://github.com/SFML/SFML/archive/2.5.1.tar.gz...
-- Extracting source F:/VCPKG/src/downloads/SFML-SFML-2.5.1.tar.gz
-- Applying patch use-system-freetype.patch
-- Using source at F:/VCPKG/src/buildtrees/sfml/src/2.5.1-8da8c5c259
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Installing: F:/VCPKG/src/packages/sfml_x64-windows-static/share/sfml/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package sfml[core]:x64-windows-static... done
Installing package sfml[core]:x64-windows-static...
Installing package sfml[core]:x64-windows-static... done
Elapsed time for package sfml:x64-windows-static: 1.394 min

Total elapsed time: 4.474 min

The package sfml:x64-windows-static provides CMake targets:
    find_package(SFML CONFIG REQUIRED)
    # Note: 7 target(s) were omitted.
    target_link_libraries(main PRIVATE FLAC OpenAL OpenGL Vorbis)

**Comment by NancyLi1013** [comment]
@seccpur we cannot reproduce it now with the latest vcpkg. Please open a new issue if this is still a problem for you.
