### ISSUE TITLE
Building package fmilib:x64-windows failed with: POST_BUILD_CHECKS_FAILED

### ISSUE THREAD

**Issue by KevinKSY** [Microsoft/vcpkg#4772]
Package: fmilib:x64-windows
  Vcpkg version: 2018.10.20-nohash

Building pakcage fmilib:x64-windows failed due to following errors. 

-- Performing post-build validation
The following files were built for an incorrect architecture:

    ~/vcpkg/packages/fmilib_x64-windows/debug/lib/fmilib_shared.lib
Expected x64, but was: x86

    ~/vcpkg/packages/fmilib_x64-windows/lib/fmilib_shared.lib
Expected x64, but was: x86

The following files were built for an incorrect architecture:

    ~/vcpkg/packages/fmilib_x64-windows/debug/bin/fmilib_shared.dll
Expected x64, but was: x86

    ~/vcpkg/packages/fmilib_x64-windows/bin/fmilib_shared.dll
Expected x64, but was: x86

**Comment by Neumann-A** [comment]
The problem is that the portfile is not using `vcpkg_configure_cmake` and is instead directly calling cmake without the proper generator.

**Comment by NancyLi1013** [comment]
Hi @KevinKSY, thanks for posting this issue. The related PR in
https://github.com/Microsoft/vcpkg/pull/4999 has been merged to the master. And I can install it successfully on my machine with the latest vcpkg. So this issue should be fixed now.
