### ISSUE TITLE
build boost with visual studio 2015 -- win10

### ISSUE THREAD

**Issue by horatii** [microsoft/vcpkg#4792]
Package: boost-build:x86-windows-static
  Vcpkg version: 2018.10.20-nohash

**Comment by horatii** [comment]
The following packages will be built and installed:
    boost-build[core]:x86-windows
Starting package 1/1: boost-build:x86-windows
Building package boost-build[core]:x86-windows...
-- Using cached E:/3rdpartycpkg/downloads/boostorg-build-boost-1.68.0.tar.gz
-- Using source at E:/3rdpartycpkgildtrees/boost-build/src/ost-1.68.0-c9ff5ec45b
-- Using cached E:/3rdpartycpkg/downloads/boost_LICENSE_1_0.txt
-- Using cached E:/3rdpartycpkg/downloads/boost-1.68.0-boostcpp.jam
-- Installing: E:/3rdpartycpkg/packages/boost-build_x86-windows/boost-build/copyright
-- Installing: E:/3rdpartycpkg/packages/boost-build_x86-windows/tools/boost-build/boostcpp.jam
-- Bootstrapping...
CMake Error at scripts/cmakecpkg_execute_required_process.cmake:56 (message):
    Command failed: E:/3rdpartycpkg/packages/boost-build_x86-windows/tools/boost-build/bootstrap.bat;msvc
    Working Directory: E:/3rdpartycpkg/packages/boost-build_x86-windows/tools/boost-build
    See logs for more information:
      E:\3rdparty\vcpkg\buildtrees\boost-build\bootstrap-x86-windows-out.log
      E:\3rdparty\vcpkg\buildtrees\boost-build\bootstrap-x86-windows-err.log

**Comment by PhoebeHui** [comment]
@horatii, thank you for posting this issue!
Could you try with VCPKG latest version? if it still occur, could you attach logs:
E:\3rdparty\vcpkg\buildtrees\boost-build\bootstrap-x86-windows-out.log
E:\3rdparty\vcpkg\buildtrees\boost-build\bootstrap-x86-windows-err.log

It installed successfully with vcpkg latest version with VS2017 15.9.7:
PS E:\vcpkg\src> ./vcpkg version
Vcpkg package management program version 2018.11.23-nohash

PS E:\vcpkg\src> ./vcpkg install boost-build:x86-windows-static
The following packages will be built and installed:
    boost-build[core]:x86-windows-static
Starting package 1/1: boost-build:x86-windows-static
Building package boost-build[core]:x86-windows-static...
-- Downloading https://github.com/boostorg/build/archive/boost-1.69.0.tar.gz...
-- Extracting source E:/VCPKG/src/downloads/boostorg-build-boost-1.69.0.tar.gz
-- Using source at E:/VCPKG/src/buildtrees/boost-build/src/ost-1.69.0-1d1e4d577d
-- Using cached E:/VCPKG/src/downloads/boost_LICENSE_1_0.txt
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.69.0/boostcpp.jam...
-- Installing: E:/VCPKG/src/packages/boost-build_x86-windows-static/share/boost-build/copyright
-- Installing: E:/VCPKG/src/packages/boost-build_x86-windows-static/tools/boost-build/boostcpp.jam
-- Bootstrapping...
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-build[core]:x86-windows-static... done
Installing package boost-build[core]:x86-windows-static...
Installing package boost-build[core]:x86-windows-static... done
Elapsed time for package boost-build:x86-windows-static: 1.016 min

Total elapsed time: 1.016 min

**Comment by whidbey** [comment]
I have the same issue and version is
:\vcpkg>
:\vcpkg>vcpkg version
cpkg package management program version 2018.11.23-nohash

ee LICENSE.txt for license information.

**Comment by NancyLi1013** [comment]
Hi @horatii, @whidbey, thanks for posting this issue. This port has been updated to 1.70.0. I can't reproduce it now. Please open a new issue if this is still a problem for you.
