### ISSUE TITLE
Is it possible to use vcpkg on a closed offline env  , no internet network.

### ISSUE THREAD

**Issue by Eldadc** [microsoft/vcpkg#4795]
Is it possible to use vcpkg on a closed offline env  , no internet network.

**Comment by Neumann-A** [comment]
depends of what you mean by that. 
You can do the following with two PCs assuming:
* PC A has internet connection.
* PC B does not.

Install vcpkg on PC A and install all required packages for PC B.
Copy the complete vcpkg folder onto a storage device (e.g. USB)
Copy said folder to PC B and you can use vcpkg without an internet connection.

In short:
If you are offline you cannot install packages but still can use already installed packages. 
The vcpkg folder should be relocatable.

**Comment by Neumann-A** [comment]
according to the faq this is currently not possible.
https://vcpkg.readthedocs.io/en/latest/about/faq/

Hmm what you can do is install the library and stop the installation (STRG+C) after it has downloaded the library. If you then rerun the installation it typically does not download the library again. Though, this does not work for libraries depending on other libraries.

**Comment by Eldadc** [comment]
Thanks on the efforts to help me.
https://vcpkg.readthedocs.io/en/latest/specifications/export-command/

I read the article. The issue with the produce that was demonstrate is that there is no central repo for all packages , it is more more likely to be complex in a large scale of developers. It is more suitable for small teams.

**Comment by LarryIII** [comment]
Thanks for your feedback. Vcpkg always need to download source from github or download from special website when installing ports. So it cloud not work in offline env.
