### ISSUE TITLE
Building package qt5-base:x64-linux failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by IgorAnohin** [microsoft/vcpkg#4804]
*Hi all!*
I was trying to install qt5-base and got the following error:
```
The following packages will be built and installed:
    qt5-base[core]:x64-linux
Starting package 1/1: qt5-base:x64-linux
Building package qt5-base[core]:x64-linux... 
-- Using cached /home/igor-emlid/Documents/vcpkg/downloads/qtbase-everywhere-src-5.11.2.tar.xz
-- Using source at /home/igor-emlid/Documents/vcpkg/buildtrees/qt5-base/src/5.11.2-86acb4d0f7
-- Configuring x64-linux-dbg
-- Configuring x64-linux-dbg done
-- Configuring x64-linux-rel
-- Configuring x64-linux-rel done
-- Package x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: /usr/bin/make;-j4
    Working Directory: /home/igor-emlid/Documents/vcpkg/buildtrees/qt5-base/x64-linux-dbg
    See logs for more information:
      /home/igor-emlid/Documents/vcpkg/buildtrees/qt5-base/build-x64-linux-dbg-out.log
      /home/igor-emlid/Documents/vcpkg/buildtrees/qt5-base/build-x64-linux-dbg-err.log

Call Stack (most recent call first):
  ports/qt5-base/install_qt.cmake:33 (vcpkg_execute_required_process)
  ports/qt5-base/portfile.cmake:121 (install_qt)
  scripts/ports.cmake:71 (include)


Error: Building package qt5-base:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qt5-base:x64-linux
  Vcpkg version: 2018.10.20-unknownhash
```

### Logs
[build-x64-linux-dbg-err.log](https://github.com/Microsoft/vcpkg/files/2610687/build-x64-linux-dbg-err.log)
[build-x64-linux-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2610688/build-x64-linux-dbg-out.log)
[config-x64-linux-dbg-err.log](https://github.com/Microsoft/vcpkg/files/2610689/config-x64-linux-dbg-err.log)
[config-x64-linux-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2610691/config-x64-linux-dbg-out.log)
[config-x64-linux-rel-err.log](https://github.com/Microsoft/vcpkg/files/2610692/config-x64-linux-rel-err.log)
[config-x64-linux-rel-out.log](https://github.com/Microsoft/vcpkg/files/2610693/config-x64-linux-rel-out.log)

### P.s.
Looks like Qt have problem with `handleMouseEvent` function (build-x64-linux-dbg-err.log).
Does someone have the same situation in Linux?
I don't need exactly Qt5.11. Which commit can I use to get successful build(Qt5.9, 5.10, etc)?

*Thanks in advance for any help.*

**Comment by bawalou** [comment]
The error doesn't come from `handleMouseEvent`, this is just a warning. The error comes from the fact that it tries to compile `sqlite3.c` but it's missing. I was facing the same issue, and realized that in `ports/qt5-base/portfile.cmake` , the sqlite dependency folder is removed (see line 34). 

For me, commenting this line fixed the issue, but I am not sure this is the correct way to fix this.

Hope this helps !

**Comment by ZeroAbility** [comment]
Confirmed on Debian 9. Commenting that foreach allows the port to build but doesn't link to the sqlite3 libs it installed as part of the dependencies.

**Comment by JackBoosY** [comment]
Hi everyone,
Qt5 has been upgraded to 5.12.3, I can't reproduce this issue on my machine, please update vcpkg, rebuild qt5-base and recheck this issue.

Thanks.

**Comment by PhoebeHui** [comment]
Looks this issue fixed, please reopen this issue if it still be an problem for you.

**Comment by zweistein22** [comment]
[config.log](https://github.com/microsoft/vcpkg/files/3963862/config.log)
Cannot compile qt 5 on a linux system (ubuntu 18.04 and WSL) 
Latest vcpkg etc...
Error is 
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):

**Comment by zweistein22** [comment]
It also says

ERROR: Feature 'openssl-linked' was enabled, but the pre-condition '!features.securetransport && libs.openssl' failed.

[config-x64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/3963863/config-x64-linux-dbg-err.log)

**Comment by JackBoosY** [comment]
@Neumann-A Could you have a look？ This error seems fixed on your PR. 

Thanks.

**Comment by Neumann-A** [comment]
The original issue was probably closed by the update to 5.12.5 while the new issue should be fix by my PR. (There is another open issue about the openssl issue on linux )

**Comment by zweistein-frm2** [comment]
Hello @Neumann-A 

with PR do you mean your branch @ https://github.com/Neumann-A/vcpkg/ ?

I tried it also but the same error on qt5-base on linux build as described above (from zweistein22 account)

Any ideas how to proceed? I would just like to habe this qt5 linux with vcpkg.  With windows all working fine.

Regards
Andreas

**Comment by Neumann-A** [comment]
@zweistein-frm2: This one: #9260
