### ISSUE TITLE
Add support for rang lib

### ISSUE THREAD

**Issue by agauniyal** [Microsoft/vcpkg#4809]
https://github.com/agauniyal/rang

Header only lib, depends on c++11 only. Would like to get it into vcpkg so that users have another choice of package manager.

**Comment by hbobenicio** [comment]
That would be awesome (and useful)!

**Comment by JackBoos** [comment]
v3.0.0 tag is not include CMakeLists.txt, I added it in port dir manually.

**Comment by NancyLi1013** [comment]
@agauniyal , thank you for posting this issue. The PR has been merged to the master.
