### ISSUE TITLE
Error: Building package openssl-uwp:arm64-uwp failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by manjunathnbec** [microsoft/vcpkg#4811]
Error: Building package openssl-uwp:arm64-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-uwp:arm64-uwp
  Vcpkg version: 2018.11.23-nohash

**Comment by manjunathnbec** [comment]
Error: Building package openssl-uwp:arm64-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-uwp:arm64-uwp
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

C:\WINDOWS\system32>vcpkg install openssl-uwp --triplet arm64-uwp
The following packages will be built and installed:
    openssl-uwp[core]:arm64-uwp
Starting package 1/1: openssl-uwp:arm64-uwp
Building package openssl-uwp[core]:arm64-uwp...
CMake Error at ports/openssl-uwp/portfile.cmake:17 (message):
  Unsupported architecture
Call Stack (most recent call first):
  scripts/ports.cmake:71 (include)

**Comment by wangli28** [comment]
Hi @manjunathnbec, thanks for posting this issue! I installed it successfully with VCPKG latest source. Can you try vcpkg latest revision?

.\vcpkg.exe install openssl-uwp:arm64-uwp
The following packages will be built and installed:
    openssl-uwp[core]:arm64-uwp
Starting package 1/1: openssl-uwp:arm64-uwp
Building package openssl-uwp[core]:arm64-uwp...
-- Downloading https://github.com/Microsoft/openssl/archive/OpenSSL_1_0_2r_WinRT.tar.gz...
-- Extracting source F:/test/issue4925/vcpkg/downloads/Microsoft-openssl-OpenSSL_1_0_2r_WinRT.tar.gz
-- Applying patch F:/test/issue4925/vcpkg/ports/openssl-uwp/fix-uwp-rs4.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch F:/test/issue4925/vcpkg/ports/openssl-uwp/fix-uwp-configure-unicode.patch
-- Using source at F:/test/issue4925/vcpkg/buildtrees/openssl-uwp/src/0_2r_WinRT-026d55ea1b
-- Build arm64-uwp
-- Build arm64-uwp done
-- Installing: F:/test/issue4925/vcpkg/packages/openssl-uwp_arm64-uwp/bin/libeay32.dll
-- Installing: F:/test/issue4925/vcpkg/packages/openssl-uwp_arm64-uwp/bin/libeay32.pdb
-- Installing: F:/test/issue4925/vcpkg/packages/openssl-uwp_arm64-uwp/bin/ssleay32.dll
-- Installing: F:/test/issue4925/vcpkg/packages/openssl-uwp_arm64-uwp/bin/ssleay32.pdb
-- Installing: F:/test/issue4925/vcpkg/packages/openssl-uwp_arm64-uwp/lib/libeay32.lib
-- Installing: F:/test/issue4925/vcpkg/packages/openssl-uwp_arm64-uwp/lib/ssleay32.lib
-- Installing: F:/test/issue4925/vcpkg/packages/openssl-uwp_arm64-uwp/debug/bin/libeay32.dll
-- Installing: F:/test/issue4925/vcpkg/packages/openssl-uwp_arm64-uwp/debug/bin/libeay32.pdb
-- Installing: F:/test/issue4925/vcpkg/packages/openssl-uwp_arm64-uwp/debug/bin/ssleay32.dll
-- Installing: F:/test/issue4925/vcpkg/packages/openssl-uwp_arm64-uwp/debug/bin/ssleay32.pdb
-- Installing: F:/test/issue4925/vcpkg/packages/openssl-uwp_arm64-uwp/debug/lib/libeay32.lib
-- Installing: F:/test/issue4925/vcpkg/packages/openssl-uwp_arm64-uwp/debug/lib/ssleay32.lib
-- Installing: F:/test/issue4925/vcpkg/packages/openssl-uwp_arm64-uwp/share/openssl-uwp/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package openssl-uwp[core]:arm64-uwp... done
Installing package openssl-uwp[core]:arm64-uwp...
Installing package openssl-uwp[core]:arm64-uwp... done
Elapsed time for package openssl-uwp:arm64-uwp: 1.531 min

Total elapsed time: 1.531 min

The package openssl is compatible with built-in CMake targets:

    find_package(OpenSSL REQUIRED)
    target_link_libraries(main PRIVATE OpenSSL::SSL OpenSSL::Crypto)

**Comment by manjunathnbec** [comment]
thanks
