### ISSUE TITLE
Error: Building package openssl-windows:arm64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by manjunathnbec** [microsoft/vcpkg#4812]
C:\WINDOWS\system32>vcpkg install openssl-windows --triplet arm64-windows
The following packages will be built and installed:
    openssl-windows[core]:arm64-windows
Starting package 1/1: openssl-windows:arm64-windows
Building package openssl-windows[core]:arm64-windows...
-- Using cached D:/vsprojects/vcpkg/downloads/openssl-1.0.2p.tar.gz
-- Applying patch D:/vsprojects/vcpkg/ports/openssl-windows/ConfigureIncludeQuotesFix.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/vsprojects/vcpkg/ports/openssl-windows/STRINGIFYPatch.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/vsprojects/vcpkg/ports/openssl-windows/EnableWinARM32.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/vsprojects/vcpkg/ports/openssl-windows/EmbedSymbolsInStaticLibsZ7.patch
-- Applying patch failed. This is expected if this patch was previously applied.
CMake Error at ports/openssl-windows/portfile.cmake:56 (message):
  Unsupported target architecture: arm64
Call Stack (most recent call first):
  scripts/ports.cmake:71 (include)

Error: Building package openssl-windows:arm64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-windows:arm64-windows
  Vcpkg version: 2018.11.23-nohash

**Comment by wangli28** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
