### ISSUE TITLE
Error: Building package c-ares:arm-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by manjunathnbec** [microsoft/vcpkg#4813]
C:\WINDOWS\system32>vcpkg install grpc --triplet arm-windows
The following packages will be built and installed:
  * c-ares[core]:arm-windows
    grpc[core]:arm-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: c-ares:arm-windows
Building package c-ares[core]:arm-windows...
-- Using cached D:/vsprojects/vcpkg/downloads/c-ares-c-ares-cares-1_15_0.tar.gz
-- Using source at D:/vsprojects/vcpkg/buildtrees/c-ares/src/res-1_15_0-2c3995bf03
-- Configuring arm-windows
-- Building arm-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No
    Working Directory: D:/vsprojects/vcpkg/buildtrees/c-ares/arm-windows-dbg
    See logs for more information:
      D:\vsprojects\vcpkg\buildtrees\c-ares\install-arm-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/c-ares/portfile.cmake:31 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package c-ares:arm-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: c-ares:arm-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by manjunathnbec** [comment]
[install-arm-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2613069/install-arm-windows-dbg-out.log)
[install-arm-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2613071/install-arm-windows-dbg-out.log)

**Comment by NattyNarwhal** [comment]
My guess is the package isn't pulling in ADVAPI32?

**Comment by JackBoosY** [comment]
Hi @manjunathnbec, thanks for reporting this issue.
I can't reproduce this issue with the latest version of c-ares, it may be solved by some PR.
Can you update vcpkg. rebuild c-ares:arm-windows and repro it?

Thanks.

**Comment by JackBoosY** [comment]
Hi @manjunathnbec, thanks for reporting this issue.
I can't reproduce this issue with the latest version of c-ares, it may be solved by some PR.
Can you update vcpkg. rebuild c-ares:arm-windows and repro it?

Thanks.

**Comment by PhoebeHui** [comment]
I installed c-ares:arm-windows by latest vcpkg and vs2017, everything installed successfully. Please reopen this issue if it still be an problem for you.
