### ISSUE TITLE
'vcpkg install zlib' CMake integration test failed

### ISSUE THREAD

**Issue by 0blu** [Microsoft/vcpkg#4817]
Hello,
somehow I cannot get zlib successfully installed,
the build seems to run fine but the cmake test fails at the end.

```
> vcpkg install zlib
The following packages will be built and installed:
    zlib[core]:x86-windows
Starting package 1/1: zlib:x86-windows
Building package zlib[core]:x86-windows...
-- Using cached D:/Programming/GitHub/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch D:/Programming/GitHub/vcpkg/ports/zlib/cmake_dont_build_more_than_needed.patch
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: D:/Programming/GitHub/vcpkg/packages/zlib_x86-windows/share/zlib/copyright
-- Performing CMake integration test
CMake Error at scripts/cmake/vcpkg_test_cmake.cmake:51 (message):
  CMake integration test failed; unable to find_package(ZLIB MODULE REQUIRED)
Call Stack (most recent call first):
  ports/zlib/portfile.cmake:47 (vcpkg_test_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package zlib:x86-windows failed with: BUILD_FAILED
```

Versions:
```
  Package: zlib:x86-windows
  Vcpkg version: 2018.11.23-debug
```

**Comment by yangninghua** [comment]
+1

**Comment by superdopenoob** [comment]
I ran into the same question.

**Comment by akaltar** [comment]
I have experienced this problem, but I no longer do, I didn't see any zlib files modified though, and I did update my CMake version to latest. Could someone try that for a fix?

**Comment by 0blu** [comment]
I've removed zlib from the `buildtrees` and `downloads` folder, I also did a `git pull origin master` for vcpkg and updating CMake to `cmake-3.13.1` but unfortunately it's still not working.

**Comment by snechaev** [comment]
In my case the project \buildtrees\zlib\x86-windows-test\CMakeFiles\3.12.4\CompilerIdC\CompilerIdC.vcxproj relates on Win10 SDK version 10.0.10240.0. This version of SDK is not installed by default in my VS2017Pro installation (and I believe that I do not remove this SDK manually earlier). So, I just installed Win10 SDK 10.0.10240.0 with Visual Studio Installer and all started to work fine.

**Comment by rkantos** [comment]
I am also experiencing this problem... 



> In my case the project \buildtrees\zlib\x86-windows-test\CMakeFiles\3.12.4\CompilerIdC\CompilerIdC.vcxproj relates on Win10 SDK version 10.0.10240.0. This version of SDK is not installed by default in my VS2017Pro installation (and I believe that I do not remove this SDK manually earlier). So, I just installed Win10 SDK 10.0.10240.0 with Visual Studio Installer and all started to work fine.
> 
> P.S. My VS version is 15.9.6

For me I have  in \buildtrees\zlib\x86-windows-test\CMakeFiles\3.12.4\CompilerIdC\CompilerIdC.vcxproj

> <PlatformToolset>v141</PlatformToolset>
> 
> <_ProjectFileVersion>10.0.30319.1</_ProjectFileVersion>

Doesn't the 10.0.30319.1 relate to Visual C++ redistributable package 10.0.30319.1? (VS2010) Obviously with Visual Studio 2017 I don't have that but the latest version 10.0.40219.. Is it supposed to work like this?

**Comment by snechaev** [comment]
@rkantos Yes, looks like this is a version of VC++ redist. The VC++ redist packages for visual studio 2010 and 2017 are incompatible. So, if you have dependency on VC++ redist for VS2010, you need to install such a redist even you already have VC++ redist for VS2017.
So, install the latest VC++ redist for VS2010 and try again. 

P.S. I have installed VC++ redist 10.0.40219.

**Comment by NancyLi1013** [comment]
@0blu, thanks for posting this issue. Does this issue still exist on your machine now? I can install it successfully on my machine with VS 2017. If this issue is still a problem for you, please help us provide more info about this issue, such as the test environment and the error logs.

**Comment by NancyLi1013** [comment]
Please open a new issue if this is still a problem for you.
