### ISSUE TITLE
hinnant's date package fails to install for triplet x64-uwp and x86-uwp

### ISSUE THREAD

**Issue by menuet** [Microsoft/vcpkg#4819]
Hi,
I cannot install hinnant's date package in a uwp app. Is it a known limitation?
Here is the vcpkg log when doing: vcpkg date:x86-windows
Thanks

The following packages will be built and installed:
    date[core]:x86-uwp
Starting package 1/1: date:x86-uwp
Building package date[core]:x86-uwp...
CMake Warning at ports/date/portfile.cmake:4 (message):
  You will need to also install
  http://unicode.org/repos/cldr/trunk/common/supplemental/windowsZones.xml
  into your install location.

  See https://howardhinnant.github.io/date/tz.html
Call Stack (most recent call first):
  scripts/ports.cmake:71 (include)

-- Using cached D:/DEV/PERSO/EXPERIMENTS/THEIRS/vcpkg/downloads/HowardHinnant-date-v2.4.1.tar.gz
-- Using source at D:/DEV/PERSO/EXPERIMENTS/THEIRS/vcpkg/buildtrees/date/src/v2.4.1-330c730353
-- Applying patch D:/DEV/PERSO/EXPERIMENTS/THEIRS/vcpkg/ports/date/fix-date.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Configuring x86-uwp
-- Building x86-uwp-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: D:/DEV/PERSO/EXPERIMENTS/THEIRS/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No
    Working Directory: D:/DEV/PERSO/EXPERIMENTS/THEIRS/vcpkg/buildtrees/date/x86-uwp-dbg
    See logs for more information:
      D:\DEV\PERSO\EXPERIMENTS\THEIRS\vcpkg\buildtrees\date\install-x86-uwp-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/date/portfile.cmake:37 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package date:x86-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: date:x86-uwp
  Vcpkg version: 2018.11.23-nohash

**Comment by Voskrese** [comment]
> See logs for more information:
> D:\DEV\PERSO\EXPERIMENTS\THEIRS\vcpkg\buildtrees\date\install-x86-uwp-dbg-out.log

**Comment by menuet** [comment]
ok will look at them. I did not notice the line !

**Comment by LarryIII** [comment]
Thanks for your feedback. This issue was fixed in https://github.com/Microsoft/vcpkg/pull/5932
