### ISSUE TITLE
Getting error while bootstraping vcpkg

### ISSUE THREAD

**Issue by nileshbhope** [microsoft/vcpkg#4823]
Getting following error when I try to boot strap vcpkg for exe generation.

PS C:\vcpkg\scripts> .\bootstrap.ps1

Building vcpkg.exe ...

Process has exited, so the requested information is not available.
At C:\vcpkg\scripts\bootstrap.ps1:372 char:5
+     Wait-Process -InputObject $process
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (:) [], InvalidOperationException
+ FullyQualifiedErrorId : System.InvalidOperationException

C:\vcpkg\scripts\bootstrap.ps1 : Building vcpkg.exe failed. Please ensure you have installed Visual Studio with the Desktop C++ workload and the Windows SDK for Desktop C++.
At line:1 char:1
+ .\bootstrap.ps1
+ ~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,bootstrap.ps1

PS C:\vcpkg\scripts>

Also I have, Visual Studio 2017, CMake, Windows 10 64-Bit OS. I have confirmed both Visual Studio with the Desktop C++ workload and the Windows SDK for Desktop C++ installed through VS installer.

Please let me know how to resolve this issue.

**Comment by PhoebeHui** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.
