### ISSUE TITLE
grpc buid fails for arm64-uwp

### ISSUE THREAD

**Issue by gpchowdari** [microsoft/vcpkg#4824]
Command :  vcpkg install grpc --triplet arm64-uwp

Error : 

The following packages will be built and installed:
    grpc[core]:arm64-uwp
  * openssl[core]:arm64-uwp
  * openssl-uwp[core]:arm64-uwp
  * protobuf[core]:arm64-uwp
  * zlib[core]:arm64-uwp
Additional packages (*) will be modified to complete this operation.
Starting package 1/5: zlib:arm64-uwp
Building package zlib[core]:arm64-uwp...
-- Using cached C:/Purushotham/General_Installs/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch C:/Purushotham/General_Installs/vcpkg/ports/zlib/cmake_dont_build_more_than_needed.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Configuring arm64-uwp
-- Building arm64-uwp-dbg
-- Building arm64-uwp-rel
-- Installing: C:/Purushotham/General_Installs/vcpkg/packages/zlib_arm64-uwp/share/zlib/copyright
-- Performing CMake integration test
-- Performing post-build validation
-- Performing post-build validation done
Building package zlib[core]:arm64-uwp... done
Installing package zlib[core]:arm64-uwp...
Installing package zlib[core]:arm64-uwp... done
Elapsed time for package zlib:arm64-uwp: 1.56 min
Starting package 2/5: openssl-uwp:arm64-uwp
Building package openssl-uwp[core]:arm64-uwp...
CMake Error at ports/openssl-uwp/portfile.cmake:17 (message):
  Unsupported architecture
Call Stack (most recent call first):
  scripts/ports.cmake:71 (include)

Error: Building package openssl-uwp:arm64-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-uwp:arm64-uwp
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

Note : able to build grpc successsfully for  arm-uwp !!

**Comment by Voskrese** [comment]
> CMake Error at ports/openssl-uwp/portfile.cmake:17 (message):
> Unsupported architecture

edit ports/openssl-uwp/portfile.cmake fo :arm64-uwp

**Comment by gpchowdari** [comment]
adding "arm64" to  ports/openssl-uwp/portfile.cmake openssl is successfully built  but grpc build is failing with errros 

      "vcpkg\buildtrees\grpc\arm64-uwp-dbg\install.vcxproj" (default target) (1) ->
       "vcpkg\buildtrees\grpc\arm64-uwp-dbg\ALL_BUILD.vcxproj" (default target) (3) ->
       "vcpkg\buildtrees\grpc\arm64-uwp-dbg\grpc.vcxproj" (default target) (20) ->
         vcpkg\buildtrees\grpc\src\v1.14.1-55a400e627\src\core\lib\transport\transport.cc(133): error C2065: 'opeqneoneg': undeclared identifier [vcpkg\buildtrees\grpc\arm64-uwp-dbg\grpc.vcxproj]
         vcpkg\buildtrees\grpc\src\v1.14.1-55a400e627\src\core\lib\transport\transport.cc(133): error C2065: 'to': undeclared identifier [vcpkg\buildtrees\grpc\arm64-uwp-dbg\grpc.vcxproj]
         vcpkg\buildtrees\grpc\src\v1.14.1-55a400e627\src\core\lib\transport\transport.cc(133): error C2275: 'uint64_t': illegal use of this type as an expression [vcpkg\buildtrees\grpc\arm64-uwp-dbg\grpc.vcxproj]
         vcpkg\buildtrees\grpc\src\v1.14.1-55a400e627\src\core\lib\transport\transport.cc(133): error C2059: syntax error: ',' [vcpkg\buildtrees\grpc\arm64-uwp-dbg\grpc.vcxproj]
         vcpkg\buildtrees\grpc\src\v1.14.1-55a400e627\src\core\lib\transport\transport.cc(133): error C2143: syntax error: missing ';' before '{' [vcpkg\buildtrees\grpc\arm64-uwp-dbg\grpc.vcxproj]
         vcpkg\buildtrees\grpc\src\v1.14.1-55a400e627\src\core\lib\transport\transport.cc(133): error C2447: '{': missing function header (old-style formal list?) [vcpkg\buildtrees\grpc\arm64-uwp-dbg\grpc.vcxproj]
         vcpkg\buildtrees\grpc\src\v1.14.1-55a400e627\src\core\lib\transport\transport.cc(140): error C2065: 'opeqneoneg': undeclared identifier [vcpkg\buildtrees\grpc\arm64-uwp-dbg\grpc.vcxproj]
         vcpkg\buildtrees\grpc\src\v1.14.1-55a400e627\src\core\lib\transport\transport.cc(140): error C2059: syntax error: ',' [vcpkg\buildtrees\grpc\arm64-uwp-dbg\grpc.vcxproj]
         vcpkg\buildtrees\grpc\src\v1.14.1-55a400e627\src\core\lib\transport\transport.cc(141): error C2065: 'opeqneoneg': undeclared identifier [vcpkg\buildtrees\grpc\arm64-uwp-dbg\grpc.vcxproj]
         vcpkg\buildtrees\grpc\src\v1.14.1-55a400e627\src\core\lib\transport\transport.cc(141): error C2059: syntax error: ',' [vcpkg\buildtrees\grpc\arm64-uwp-dbg\grpc.vcxproj]
         vcpkg\buildtrees\grpc\src\v1.14.1-55a400e627\src\core\lib\transport\transport.cc(142): error C2065: 'opeqneoneg': undeclared identifier [vcpkg\buildtrees\grpc\arm64-uwp-dbg\grpc.vcxproj]
         vcpkg\buildtrees\grpc\src\v1.14.1-55a400e627\src\core\lib\transport\transport.cc(142): error C2059: syntax error: ',' [vcpkg\buildtrees\grpc\arm64-uwp-dbg\grpc.vcxproj]

**Comment by JackBoosY** [comment]
Hi @gpchowdari, thanks for reporting this issue.
grpc now supports arm64-uwp, please update vcpkg and rebuild grpc.

Thanks.

**Comment by Noemata** [comment]
This no longer works. :-(
