### ISSUE TITLE
vcpkg install cairo:x86-windows-static FAILED

### ISSUE THREAD

**Issue by horatii** [Microsoft/vcpkg#4828]
f:\3rdparty\vcpkg>vcpkg install cairo:x86-windows-static
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be built and installed:
    cairo[core]:x86-windows-static
  * dirent[core]:x86-windows-static
  * expat[core]:x86-windows-static
  * fontconfig[core]:x86-windows-static
  * glib[core]:x86-windows-static
Additional packages (*) will be modified to complete this operation.
Starting package 1/5: glib:x86-windows-static
Building package glib[core]:x86-windows-static...
Glib relies on DllMain and therefore cannot be built statically
CMake Error at ports/glib/portfile.cmake:13 (message):
  Glib only supports dynamic library and crt linkage
Call Stack (most recent call first):
  scripts/ports.cmake:71 (include)

Error: Building package glib:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glib:x86-windows-static
  Vcpkg version: 2018.10.20-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by horatii** [comment]
glib did not support static build?

**Comment by Voskrese** [comment]
> Glib relies on DllMain and therefore cannot be built statically
> CMake Error at ports/glib/portfile.cmake:13 (message):
> Glib only supports dynamic library and crt linkage
Glib only supports dynamic library and crt linkage
