### ISSUE TITLE
Error: Building package ilmbase:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by yinkangwan** [Microsoft/vcpkg#4839]
Package: ilmbase:x64-windows
  Vcpkg version: 2018.10.20-nohash

**Comment by EdYao** [comment]
I have the same issue

**Comment by yinkangwan** [comment]
> I have the same issue

u can download ilmbase-2.2.1.tar.gz ， then  put it in ..\vcpkg\downloads 
then  .\vcpkg.exe install ilmbase:x64-windows

**Comment by NancyLi1013** [comment]
@yinkangwan, thanks for posting this issue. I cannot reproduce it. Could you please help us confirm whether this issue still exists on your machine now?
PS E:\testport\vcpkg> .\vcpkg.exe install ilmbase:x64-windows
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be built and installed:
    ilmbase[core]:x64-windows
Starting package 1/1: ilmbase:x64-windows
Building package ilmbase[core]:x64-windows...
-- Performing post-build validation
-- Performing post-build validation done
Building package ilmbase[core]:x64-windows... done
Installing package ilmbase[core]:x64-windows...
Installing package ilmbase[core]:x64-windows... done
Elapsed time for package ilmbase:x64-windows: 35.82 s

Total elapsed time: 35.82 s

**Comment by kinsung** [comment]
Everything is OK now.

**Comment by NancyLi1013** [comment]
@kinsung, thanks for your feedback.
