### ISSUE TITLE
Cannot install vcpkg in Windows10

### ISSUE THREAD

**Issue by RekrapF** [Microsoft/vcpkg#4840]
```
Gigabyte@DESKTOP-UC7PUJO MINGW64 /vcpkg (master)
$ bootstrap-vcpkg.bat
bash: bootstrap-vcpkg.bat: command not found
```

I cannot run this .bat in git bash, maybe I miss setting some configuration in environment variable?

**Comment by nightslashs** [comment]
Assuming they treat this similar to the Linux environment you need to prefix the call with ./ to signify the local directory as most UNIX environments don't add the cwd to the path. Whereas dos environments this is the standard! So try ./bootstrap-vcpkg.bat

**Comment by vicroms** [comment]
Here's the relevant section of the docs.
On Linux you need to use `./boostrap-vcpkg.sh`

To get started:

> git clone https://github.com/Microsoft/vcpkg.git
> cd vcpkg

PS> .\bootstrap-vcpkg.bat
Linux:~/$ ./bootstrap-vcpkg.sh
