### ISSUE TITLE
Error: pdcurses 3.6 Linking Error

### ISSUE THREAD

**Issue by nexxtnos** [microsoft/vcpkg#4848]
This is my first issue ever I report, so please teach me when something is not done how it usually should, but also please have some patience :) 

So I got a Linking error when using vcpkg and pdcurses 3.6, I installed it and wanted to do a Hello World project, just to test if the librarie is working:

```
#include <iostream>
#include <curses.h>
#include <panel.h>
#include <term.h>

int main()
{
	initscr();
	keypad(stdscr, TRUE);
	nodelay(stdscr, TRUE);
	echo();
}
```
it compiles and everything but when it comes to linking this error is thrown "error LNK2001: unresolved external symbol _stdscr" 
I even created a NuGetPackage Manager .config with the vcpkg but still the linking error exists.

Please let me know if I am too blind to see something obvious or if something else is wrong. I would also be glad when someone could try and check if he gets same error.

thanks

**Comment by sryze** [comment]
@nexxtnos Have you solved this issue? I have the same problem, I'm using (pd)curses for the first time

**Comment by sryze** [comment]
Never mind, I figured it out: because pdcurses was built as a DLL I had to define `PDC_DLL_BUILD` to properly import the external variables.

```
target_compile_definitions(my_target PRIVATE -DPDC_DLL_BUILD)
```

**Comment by NancyLi1013** [comment]
Hi @nexxtnos  thanks for posting this issue.
As @sryze said above, you need to define `PDC_DLL_BUILD` to import the external variables.
We can get the related description from Line 362-370 in `curses.h` file:
```
#ifdef PDC_DLL_BUILD
# ifdef CURSES_LIBRARY
#  define PDCEX __declspec(dllexport) extern
# else
#  define PDCEX __declspec(dllimport)
# endif
#else
# define PDCEX extern
#endif
```
Please add this to your CMakeLists.txt.

`target_compile_definitions(Project_NAME PRIVATE -DPDC_DLL_BUILD)` 

 We will add the usage to this port.
@sryze thanks for your detail explanation to this issue.

Thanks.

**Comment by NancyLi1013** [comment]
I submitted a PR to fix this issue. Please try to update vcpkg and use it.
