### ISSUE TITLE
CMake 3.13.0/3.13.1 and CURL portfile.cmake 7.61.1-1 mismatch

### ISSUE THREAD

**Issue by arietto** [microsoft/vcpkg#4851]
Hello. I can't use debug curl lib (import library for dll) in my CMake 3.13.1 project. There is mismatch between expected debug lib names and file names in portfile.cmake.

**Comment by PhoebeHui** [comment]
@arietto, does this still be an issue for you? currently Curl upgrade to 7.65.0 in VCPKG, could you have a try?

**Comment by PhoebeHui** [comment]
@arietto, please reopen this issue if it still be an problem for you.
