### ISSUE TITLE
vcpkg install uwebsockets failed

### ISSUE THREAD

**Issue by MinaRoss** [Microsoft/vcpkg#4852]
.\vcpkg install uwebsockets
The following packages will be built and installed:
    uwebsockets[core]:x86-windows
Starting package 1/1: uwebsockets:x86-windows
Building package uwebsockets[core]:x86-windows...
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio 12.0\
Please install the English language pack.
-- Using cached C:/vcpkg/downloads/uWebSockets-uWebSockets-v0.14.8.tar.gz
-- Using source at C:/vcpkg/buildtrees/uwebsockets/src/v0.14.8-b18b022999
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: C:/vcpkg/buildtrees/uwebsockets/x86-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\uwebsockets\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/uwebsockets/portfile.cmake:20 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package uwebsockets:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: uwebsockets:x86-windows
  Vcpkg version: 2018.11.23-nohash

**Comment by Voskrese** [comment]
> See logs for more information:
> C:\vcpkg\buildtrees\uwebsockets\install-x86-windows-dbg-out.log

**Comment by NancyLi1013** [comment]
@MinaRoss, thanks for posting this issue. we cannot reproduce it now. Please open a new issue if this is still a problem for you.
