### ISSUE TITLE
glibmm: balancedtree.h does not compile under code page 936

### ISSUE THREAD

**Issue by fghzxm** [Microsoft/vcpkg#4856]
When building `atkmm:x86-windows` version `2018.11.23-nohash`:

    ClCompile:
      C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x86\CL.exe
        /c /I.\atkmm /I..\atk /I. /I"C:\Users\Fred\vcpkg\installed\x86-windows\include"
        /Zi /nologo /W3 /WX- /diagnostics:classic /MP /O2 /Oy- /D ATKMM_BUILD /D _WINDLL
        /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Zc:wchar_t /Zc:forScope /Zc:inline /GR
        /Fo"C:\Users\Fred\vcpkg\buildtrees\atkmm\src\atkmm-2.24.2\MSVC_Net2013\Release\Win32\obj\atkmm\\"
        /Fd"C:\Users\Fred\vcpkg\buildtrees\atkmm\src\atkmm-2.24.2\MSVC_Net2013\Release\Win32\obj\atkmm\vc141.pdb"
        /Gd /TP /FImsvc_recommended_pragmas.h /analyze- /FC /errorReport:queue /d2Zi+
        ..\atk\atkmm\action.cc ..\atk\atkmm\component.cc ..\atk\atkmm\document.cc 
        <other source files...>

The following compile error is emitted for multiple source files:

    c:\users\fred\vcpkg\installed\x86-windows\include\glibmm\balancedtree.h :
    error C4819: The file contains a character that cannot be represented in the current
                 code page (936). Save the file in Unicode format to prevent data loss

The compiler version is

    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>cl
    Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27024.1 for x86

**Comment by NancyLi1013** [comment]
Hi @fghzxm, thanks for posting this issue. I can build it successfully on my machine with VS 2017. Please open a new issue if this is still a problem for you.

**Comment by 1799103922** [comment]
- en:I have encountered this problem, just need to convert the .h file encoding to ASIN, right, there will be several files later, the same problem, also converted to ASIN

- ch:这个问题我也遇到了，只需要把那个.h文件编码转为ASIN就可以了，对了，后面还会有几个文件，同样的问题，也转为ASIN
