### ISSUE TITLE
Update of angle with Winstore fix

### ISSUE THREAD

**Issue by rollebolle** [microsoft/vcpkg#4857]
It was over a year since Angle was updated,. I've prepared a fix for the current Angle master (they dont use version numbers), which also works with UWP/Windows Store (which is disabled in the current release). Should I PR it?

**Comment by NancyLi1013** [comment]
Hi @rollebolle, thanks for posting this issue. The angle has been updated. The current version 2019-03-13-c2ee2cc-3 in chromium/3672 branch has supported UWP now. Please try to update and use it. Please open a new issue if you have other request.
