### ISSUE TITLE
Packages cpprestsdk and azure-storage-cpp fail to build

### ISSUE THREAD

**Issue by bangusi** [Microsoft/vcpkg#486]
Both these packages ( `cpprestsdk:x64-windows `and `azure-storage-cpp:x64-windows` ) are failing to build due to what appears to be broken boost dependencies.
```
error MSB3030: Could not copy the file "2_9.dll" because it was not found.
error MSB3030: Could not copy the file "stem-vc140-mt-1_62.dll" because it was not found.
```
 I have the latest version of boost  (  1.62-9 ) and I previously had both packages successfully built before.

**Comment by alexkaratarakis** [comment]
The file names I see above seem a bit broken.
`stem-vc140-mt-1_62.dll` is probably `boost_system-vc140-mt-1_62.dll` (could also be `boost_filesystem-vc140-mt-1_62.dll`)

The `2_9.dll` is probably `cpprest_2_9.dll`.

So, it is looking for the filenames with the first 8 chars chopped off.

1) I just built `cpprestsdk:x64-windows` and it works. Might be worth trying this once more to see if you consistently get this error. 
2) What is your locale?

**Comment by bangusi** [comment]
Still failing with the same error. My locale is English(US). Platform Windows 7.
I guess I may have to re-build everything.

**Comment by alexkaratarakis** [comment]
Please let me know if rebuilding fixed the issue. I looked for cases where `vcpkg` might be doing some chopping but didn't see anything out of place.

**Comment by bangusi** [comment]
Rebuilding fixed the issue.
