### ISSUE TITLE
Failed to download file: Package: openexr:x64-windows   Vcpkg version: 2018.11.23-nohash

### ISSUE THREAD

**Issue by edwin-tn** [Microsoft/vcpkg#4868]
I am running Microsoft Windows 10  visual studio 2017 community edition.
I run vcpkg install windows to build AliceVision (https://github.com/alicevision/AliceVision)

What I get:

-- Downloading http://download.savannah.nongnu.org/releases/openexr/openexr-2.2.1.tar.gz... Failed. Status: 56;"Failure when receiving data from the peer"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:156 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/openexr/portfile.cmake:6 (vcpkg_download_distfile)
  scripts/ports.cmake:71 (include)

**Comment by wangli28** [comment]
Hi @edwin-tn,
Is there a proxy for your network? Can you manually download this package successful from the link?
Thanks.

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
