### ISSUE TITLE
No postfix in debug dll of libwebm

### ISSUE THREAD

**Issue by chrisaverage** [microsoft/vcpkg#4878]
The project I have is configured to use the same output directory for release and debug configurations. All debug libraries have some postfix like "d" or "_Debug".
libwebm produces same name "libwebm.dll" in both configurations which leads to overwriting and loading wrong dll (and eventually crash).
Can I get the postfix added to debug build? I see that some vcpkg libraries have it, some don't, postfixes differ etc. between libraries. Ideally I'd like to be able to configure vcpkg so that I get consistent convention across all libraries.

**Comment by LarryIII** [comment]
@chrisaverage Thanks for your feedback. this issue was fixed in https://github.com/Microsoft/vcpkg/pull/5516

**Comment by chrisaverage** [comment]
It doesn't seem to be fixed. I don't think a file rename is a way to handle this. The debug dlls do have a "d" postfix now but they are not copied to the output directory on build and when running the app there's an error saying libwebm.dll is missing so it's still linking to the old name without the postfix.
