### ISSUE TITLE
NMAKE : fatal error U1077: 'if' : return '0x1'

### ISSUE THREAD

**Issue by FlokiLee** [Microsoft/vcpkg#4882]
I try to build the Detours Express 3.0.
I use the win10 system.

In the path C:\Program Files (x86)\Microsoft Research\Detours Express 3.0\src>
Try to command nmake.

How can I modify this fatal error U1077
The system return as below.
-------------------------------------------------------------------------

NMAKE : fatal error U1077: 'if' : return '0x1'
Stop.

**Comment by Voskrese** [comment]
https://github.com/microsoft/Detours/issues

**Comment by FlokiLee** [comment]
Sorry to bother you.
Could you help to describe it in more detail?
I do not know how to modify it.
BR.
Floki

**Comment by LarryIII** [comment]
@FlokiLee  I think your issue same with this https://github.com/Microsoft/Detours/issues/42. Please ensure the workload(the .NET desktop development workload, especially .NET Framework SDK 4.6.1.) that you installed!
If you resolved your issue, please closed this issue. Thank you!

**Comment by LarryIII** [comment]
@FlokiLee Please ensure you installed below 3 workloads in your Visual Studio! Then try to re-install it!
![capture](https://user-images.githubusercontent.com/33021067/51594583-b7422480-1f2f-11e9-8d11-28c4d7de0a8a.PNG)

**Comment by Voskrese** [comment]
@FlokiLee 
you need to generate a personal key and put it in a folder or specify the path in the project

**Comment by LarryIII** [comment]
Please open a new issue if this is still a problem for you.
