### ISSUE TITLE
HololensSpectatorViewPlugin Build failed on Visual Studio

### ISSUE THREAD

**Issue by CMLeshiba** [microsoft/vcpkg#4885]
Hi, I am trying to build the solution but it says it cannot find the SDK. I have installed the latest SDK but still experiencing the same error.

1>------ Build started: Project: SpectatorViewPlugin, Configuration: Release Win32 ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK version 10.0.15063.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".
1>Done building project "SpectatorViewPlugin.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by Voskrese** [comment]
> HololensSpectatorViewPlugin 

not found

> Windows SDK version 10.0.15063.0 was not found

edit `SpectatorViewPlugin.vcxproj`

**Comment by LarryIII** [comment]
@CMLeshiba Thanks for your feedback. Which port that you uses in you project? Could you please descirbe  your issue step by step?

**Comment by wangli28** [comment]
Hi @CMLeshiba, thanks for posting this issue. does the issue still occur?

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you.
