### ISSUE TITLE
Installing multiple libraries from a single project

### ISSUE THREAD

**Issue by DaanDeMeyer** [microsoft/vcpkg#4888]
[reproc](https://github.com/DaanDeMeyer/reproc) consists out of two libraries (reproc and reproc++) which have their own CMake config files.

When updating reproc's portfile I've stumbled upon the issue that vcpkg wants all of reproc's config files in the share/reproc directory which would break `find_package(reproc++)` (which requires reproc++'s config files to be in share/reproc++).

What's the best way to solve this?

**Comment by rubialasdelfin97** [comment]
Good load

**Comment by wangli28** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
