### ISSUE TITLE
mongo-cxx-driver build problem

### ISSUE THREAD

**Issue by duke-gh** [Microsoft/vcpkg#489]
I got a problem trying to build mongo-cxx-driver static library. While building dependence - mongo-c-driver I've got an output:
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: C:/Data/projects/vcpkg/downloads/cmake-3.5.2-win32-x86/bin/cmake.exe;--build;.;--config;Release;--target;install;--;/m
    Working Directory: C:/Data/projects/vcpkg/buildtrees/mongo-c-driver/x64-windows-static-rel
    See logs for more information:
      C:\Data\projects\vcpkg\buildtrees\mongo-c-driver\package-x64-windows-static-rel-out.log
      C:\Data\projects\vcpkg\buildtrees\mongo-c-driver\package-x64-windows-static-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:3 (vcpkg_execute_required_process)
  ports/mongo-c-driver/portfile.cmake:20 (vcpkg_install_cmake)
  scripts/ports.cmake:73 (include)
Error: building package mongo-c-driver:x64-windows-static failed
Please ensure sure you're using the latest portfiles with `vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: mongo-c-driver:x64-windows-static
  Vcpkg version: 0.0.65-b280f57002044036c1c3c9a446c06e8e0a34fb00

The problem is: bson.h: No such file or directory.

I'm using Windows 10, Russian locale.

Update: In the generated projects properties (vcpkg\buildtrees\mongo-c-driver\x64-windows-static-dbg\libmongoc.sln) I saw something like "BSON_INCLUDE_DIR-NOTFOUND" in the include paths. So I added
-DBSON_INCLUDE_DIR=${CURRENT_INSTALLED_DIR}/include
to portfile.cmake next to other options. After I got vcpkg\installed\x64-windows-static\include\libbson-1.0. If I remove libbson-1.0, I can build the library manually via visual studio solution.

**Comment by sdcb** [comment]
I failed to install mongo-c-driver:x64-windows-static too, but after I have x64-windows installed, I successfully installed the mongo-c-driver:x64-windows-static, I think it's a bug, which also related to another issue here:
https://github.com/Microsoft/vcpkg/issues/475

@alexkaratarakis could you invest it?

**Comment by codicodi** [comment]
I think the issue lies in FindBSON.cmake provided by mongo-c-driver. It assumes bson.h is located in `include/libbson-1.0`:
```
find_path(BSON_INCLUDE_DIR
  NAMES
    libbson-1.0/bson.h
  HINTS
    ${BSON_ROOT_DIR}
    ${_BSON_INCLUDEDIR}
  PATH_SUFFIXES
    include
)

set(BSON_INCLUDE_DIR "${BSON_INCLUDE_DIR}/libbson-1.0")
```

**Comment by duke-gh** [comment]
Thank you for the hint! After commenting out
`set(BSON_INCLUDE_DIR "${BSON_INCLUDE_DIR}/libbson-1.0")`
with my change from initial issue (in portfile.cmake)
'-DBSON_INCLUDE_DIR=${CURRENT_INSTALLED_DIR}/include'
it is works for me. Seems you are right - this was the reason.
