### ISSUE TITLE
xerces-c defines DLL_EXPORT

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#4899]
in Xerces_autoconf_config.hpp xerces-c wrongly defines DLL_EXPORT which has side effects to other libraries using vcpkg. (In my case linker errors using the GNU GSL due to symbol mismatches)

**Comment by nicole9456** [comment]
Dear customer, 
Thanks very much for your issue and 
I can install xerces-c and gsl successfully by vcpkg, but I am not very clear how to reproduce you issue. could you give me more information about your issue? For example: your project or detail error info, etc.

**Comment by Neumann-A** [comment]
Minimal Example: Will Fail with Linker error
```
//Uncomment to solve the Linker Error
//#ifdef DLL_EXPORT
//#define TMP_DLL_EXPORT_GUARD
//#endif
#include <xercesc/dom/DOM.hpp>
//#ifndef TMP_DLL_EXPORT_GUARD
//#undef DLL_EXPORT //Wrongly defined by xercesc
//#else
//#undef TMP_DLL_EXPORT_GUARD
//#endif

#include <gsl/gsl_rng.h>
#include <gsl/gsl_randist.h>

int main()
{
    const gsl_rng_type * T;
    gsl_rng * r;

    gsl_rng_env_setup();

    T = gsl_rng_default;
    r = gsl_rng_alloc(T);

    return gsl_ran_gaussian(r, 1);
}


```

CMake file to build:

```
cmake_minimum_required(VERSION 3.12)

project(GSL_Xerces-C-BUG)

find_package(Threads) # Dont know why this is required. 
find_package(XercesC CONFIG REQUIRED)
find_package(GSL REQUIRED)

add_executable(${PROJECT_NAME} main.cpp)

target_link_libraries(${PROJECT_NAME} PRIVATE xerces_xerces-c XercesC::XercesC)
target_link_libraries(${PROJECT_NAME} PRIVATE GSL::gsl GSL::gslcblas)
```
Don't forget to set the toolchain file for vcpkg

**Comment by JackBoosY** [comment]
Hi @Neumann-A, thanks for reporting this issue!
I've fixed this issue just now, please update vcpkg and rebuild xerces-c.

Thanks.
