### ISSUE TITLE
vcpkg install eigen3:x64-windows --recurse failed with english package

### ISSUE THREAD

**Issue by CindyB33** [Microsoft/vcpkg#4902]
This problem seems to occur many times, but download English package doesnt resolve the problem for me.
This is my output : 

>C:\vcpkg>vcpkg install eigen3:x64-windows --recurse 
The following packages will be built and installed:
    eigen3[core]:x64-windows
Starting package 1/1: eigen3:x64-windows
Building package eigen3[core]:x64-windows...
-- Using cached C:/vcpkg/downloads/eigenteam-eigen-git-mirror-3.3.5.tar.gz
-- Using source at C:/vcpkg/buildtrees/eigen3/src/3.3.5-dea2ea229a
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: C:/vcpkg/buildtrees/eigen3/x64-windows-rel/vcpkg-parallel-configure
    See logs for more information:
      C:\vcpkg\buildtrees\eigen3\config-x64-windows-out.log
Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:257 (vcpkg_execute_required_process)
  ports/eigen3/portfile.cmake:11 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)
Error: Building package eigen3:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with \`.\vcpkg update\`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: eigen3:x64-windows
  Vcpkg version: 2018.11.23-nohash
>Additionally, attach any relevant sections from the log files above. 

And this is the log file :
[config-x64-windows-out.log](https://github.com/Microsoft/vcpkg/files/2648399/config-x64-windows-out.log)

Do you have an idea ?

**Comment by Voskrese** [comment]
?

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GMP_LIBRARIES (ADVANCED)
    linked by target "mpreal_support" in directory C:/vcpkg/buildtrees/eigen3/src/3.3.5-dea2ea229a/unsupported/test

-- Configuring incomplete, errors occurred!
See also "C:/vcpkg/buildtrees/eigen3/x64-windows-rel/CMakeFiles/CMakeOutput.log".
See also "C:/vcpkg/buildtrees/eigen3/x64-windows-rel/CMakeFiles/CMakeError.log".
```

**Comment by Voskrese** [comment]
Boost ?

```
globbed: 
CMake Error at C:/Program Files/Boost/share/cmake/boost/BoostConfig.cmake:15 (include):
  include could not find load file:

C:/Projets/PCL/SuperBuild_boost_1_50/CMakeExternal/Install/Boost/share/boost-/cmake/BoostConfig.cmake
```

**Comment by CindyB33** [comment]
Hello Voskrese,
thank you for your answer !
I've just installed vcpkg and then I want to install pcl library. I havent touch any config file so I dont understand how I can set these Cmake variables ... 
All these files are not also configured by vcpkg ?

Boost had been installed correctly by vcpkg install pcl:x64-windows, so it would be surprising if it is the reason no ?

**Comment by Neumann-A** [comment]
try to add `BUILD_TESTING=OFF` to vcpkg_configure_cmake within the portfile for Eigen. 
It is defaulted to ON but is not actually building any tests because they are all deactivated.

**Comment by CindyB33** [comment]
Hello Neumann-A,
Thank you for your message. Where I have to put this line ? I've found the file vcpkg_configure_cmake.cmake but there is no line that looks like this one, so, is there a specific paragraph where I have to write it ?
Thanks :)

**Comment by Neumann-A** [comment]
Replace 
```
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS_RELEASE
        -DCMAKEPACKAGE_INSTALL_DIR=${CURRENT_PACKAGES_DIR}/share/eigen3
    OPTIONS_DEBUG
        -DCMAKEPACKAGE_INSTALL_DIR=${CURRENT_PACKAGES_DIR}/debug/share/eigen3
)
```

with 
```
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -DBUILD_TESTING=OFF
    OPTIONS_RELEASE
        -DCMAKEPACKAGE_INSTALL_DIR=${CURRENT_PACKAGES_DIR}/share/eigen3
    OPTIONS_DEBUG
        -DCMAKEPACKAGE_INSTALL_DIR=${CURRENT_PACKAGES_DIR}/debug/share/eigen3
)
```

in the eigen portfile located at vcpkgroot/ports/eigen3/

**Comment by CindyB33** [comment]
Thank you so much, it worked perfectly !

**Comment by Srabiu** [comment]
hello all,
I am having same problem, however its with version 3.3.7-c0bebf7460, the eigen portfile was configured with TESTING = OFF , here is the portfile
include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO eigenteam/eigen-git-mirror
    REF 3.3.7
    SHA512 270ab9b5c22e09aa0e70d1a26995523c5c21fb0f09da45c137c11ab4c7700fe2bdb2b343c1e063bea4be5ae61d2313ff29ebbcad519dc355a568792b4a6e9e48
    HEAD_REF master
)

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -DBUILD_TESTING=OFF
    OPTIONS_RELEASE
        -DCMAKEPACKAGE_INSTALL_DIR=${CURRENT_PACKAGES_DIR}/share/eigen3
    OPTIONS_DEBUG
        -DCMAKEPACKAGE_INSTALL_DIR=${CURRENT_PACKAGES_DIR}/debug/share/eigen3
)

vcpkg_install_cmake()

file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug)

file(READ "${CURRENT_PACKAGES_DIR}/share/eigen3/Eigen3Targets.cmake" EIGEN_TARGETS)
string(REPLACE "set(_IMPORT_PREFIX " "get_filename_component(_IMPORT_PREFIX \"\${CMAKE_CURRENT_LIST_DIR}/../..\" ABSOLUTE) #" EIGEN_TARGETS "${EIGEN_TARGETS}")
file(WRITE "${CURRENT_PACKAGES_DIR}/share/eigen3/Eigen3Targets.cmake" "${EIGEN_TARGETS}")

file(GLOB INCLUDES ${CURRENT_PACKAGES_DIR}/include/eigen3/*)
# Copy the eigen header files to conventional location for user-wide MSBuild integration
file(COPY ${INCLUDES} DESTINATION ${CURRENT_PACKAGES_DIR}/include)

# Put the licence file where vcpkg expects it
file(COPY ${SOURCE_PATH}/COPYING.README DESTINATION ${CURRENT_PACKAGES_DIR}/share/eigen3)
file(RENAME ${CURRENT_PACKAGES_DIR}/share/eigen3/COPYING.README ${CURRENT_PACKAGES_DIR}/share/eigen3/copyright)

**Comment by Neumann-A** [comment]
@Srabiu Sry couldn't reproduce your problem in a clean vcpkg clone trying to install pcl.  
I dont see any errors and the build ends with: 

```
Starting package 112/112: pcl:x64-windows
Building package pcl[core]:x64-windows...
-- Downloading https://github.com/PointCloudLibrary/pcl/archive/pcl-1.9.1.tar.gz...
-- Extracting source G:/vcpkg_dll_export/vcpkg/downloads/PointCloudLibrary-pcl-pcl-1.9.1.tar.gz
-- Applying patch pcl_utils.patch
-- Applying patch pcl_config.patch
-- Applying patch find_flann.patch
-- Using source at G:/vcpkg_dll_export/vcpkg/buildtrees/pcl/src/pcl-1.9.1-898b5a3155
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package pcl[core]:x64-windows... done
Installing package pcl[core]:x64-windows...
Installing package pcl[core]:x64-windows... done
Elapsed time for package pcl:x64-windows: 37.92 min

Total elapsed time: 1.442 h

The package pcl:x64-windows provides CMake targets:

    find_package(PCL CONFIG REQUIRED)
    target_link_libraries(main PRIVATE ${pcl_component})

```

**Comment by 08822407d** [comment]
when i install pcl, i faced eigen3 installation error too. i read the err log, and found it says zlib build error, and then i deleted the zlib folder int vcpkg/buildtrees and re-installed zlib by vcpkg, then delete eigen3 folder in buildtrees, then re-install eigen3 ,and successed
