### ISSUE TITLE
libiconv not setting ICONV_CONST correctly

### ISSUE THREAD

**Issue by IRebo** [Microsoft/vcpkg#4904]
It seems that in https://github.com/Microsoft/vcpkg/blob/master/ports/libiconv/CMakeLists.txt the ICONV_CONST is supposed to be defined to "const" using a replace from #undef ICONV_CONST. However the default config.h.in in the latest libiconv versions contains a different line instead so the replace doest nothing. Is this intended ?

**Comment by nicole9456** [comment]
Dear customer, 
After install libiconv by vcpkg, I have a check config.h.in file in (vcpkg\buildtrees\libiconv\src\1.15-dde6fc62db),it has "#undef ICONV_CONST" in line#809. And it also be replace to "#define ICONV_CONST const" in output file config.h.  
![image](https://user-images.githubusercontent.com/46737724/51653554-e9ef2a00-1fce-11e9-8474-c92dd89cd251.png)
![image](https://user-images.githubusercontent.com/46737724/51653543-d93eb400-1fce-11e9-9889-6fb64fb46c57.png)

could you try to reproduce the issue again? if it still can be reproduce, could give me more information? For example: where are you find your config.h.in? libiconv version and so on. 
Thanks very much for your support!

**Comment by IRebo** [comment]
Thanks a lot for looking into it. It seems i was looking at wrong config.h.in and misjudged the cause.

It seems indeed that config.h is correct.
My issue is actually with the generated iconv.h which is based on iconv.h.in

There is this function in iconv.h.in
extern size_t iconv (iconv_t cd, @ICONV_CONST@ char* * inbuf, size_t *inbytesleft, char* * outbuf, size_t *outbytesleft);

The @ICONV_CONST@ token shouldnt i assume be transformed to the "const" value of ICONV_CONST but if you look at the output iconv.h the definition looks like this :
extern LIBICONV_DLL_EXPORTED size_t iconv (iconv_t cd,  char* * inbuf, size_t *inbytesleft, char* * outbuf, size_t *outbytesleft);


Please note that this might be intended and i havent been able to find what part of the build process is supposed to replace the @ICONV_CONST@ token.

Sorry about the confusion.

**Comment by nicole9456** [comment]
Thanks very much for your reply! I'm understand your question and we will investigate it.

**Comment by LarryIII** [comment]
@IRebo Thanks for your feedback. I want to know how does this issue impact you, it will block yourself solution when you using it? We are making an estimate, if this has problems we have not foreseen, we will consider make a patch for this. If not, we will close this issue. We are looking forward for your reply. Thank you!

**Comment by IRebo** [comment]
Since the workaround is not too complex it does not block us.

**Comment by LarryIII** [comment]
@IRebo Thanks for your updates. Closed this issue now!
