### ISSUE TITLE
opencv:arm64-uwp build failure

### ISSUE THREAD

**Issue by AMollis** [microsoft/vcpkg#4907]
Package: opencv:arm64-uwp
  Vcpkg version: 2018.11.23-nohash

This package fails to build with the following error:

`c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.16.27023\include\emmintrin.h(24): fatal error C1189: #error:  This header is specific to X86 and X64 targets [C:\dev\work\vcpkg\buildtrees\opencv\arm64-uwp-dbg\modules\core\opencv_core.vcxproj]`

Attached build log:
[install-arm64-uwp-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2650339/install-arm64-uwp-dbg-out.log)

**Comment by Voskrese** [comment]
emmintrin.h(24): fatal error C1189: #error: **This header is specific to X86 and X64**

**Comment by ckarrer** [comment]
Did you find any workarounds?

**Comment by gilbdev** [comment]
still doesn't work for opencv4:uwp-arm64

**Comment by shibayan** [comment]
We are working on a fix with opencv repo. https://github.com/opencv/opencv/pull/16027
