### ISSUE TITLE
Error: Building package aws-sdk-cpp:arm-uwp failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by mwill195** [microsoft/vcpkg#4910]
.\vcpkg install aws-sdk-cpp:arm-uwp

The following packages will be built and installed:
    aws-sdk-cpp[core,dynamodb,kinesis,s3]:arm-uwp
Starting package 1/1: aws-sdk-cpp:arm-uwp
Building package aws-sdk-cpp[core,dynamodb,kinesis,s3]:arm-uwp...
-- Using cached C:/Users/marwi1/vcpkg/downloads/aws-aws-sdk-cpp-1.6.47.tar.gz
-- Using source at C:/Users/marwi1/vcpkg/buildtrees/aws-sdk-cpp/src/1.6.47-27a89d88bf
-- Configuring arm-uwp
-- Building arm-uwp-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: C:/Users/marwi1/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/bin/cmake.exe;--bu
ild;.;--config;Debug;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No
    Working Directory: C:/Users/marwi1/vcpkg/buildtrees/aws-sdk-cpp/arm-uwp-dbg
    See logs for more information:
      C:\Users\marwi1\vcpkg\buildtrees\aws-sdk-cpp\install-arm-uwp-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/aws-sdk-cpp/portfile.cmake:34 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

**Comment by mwill195** [comment]
Digging deeper there are link errors in some of the windows headers (winhttp.h, userenv.h) but this is because the headers exclude code based on the supplied WINAPI_FAMILY value. The build is specifying WINAPI_FAMILY_APP which then doesn't resolve to the right WINAPI_PARTITION_ value to allow the headers, which must be WINAPI_PARTITION_DESKTOP or WINAPI_PARTITION_SYSTEM.

**Comment by JackBoosY** [comment]
Hi @mwill195, it seems __mm_crc32_u8_ / __mm_crc32_u32_ / __mm_crc32_u64_ only support with **x86**/**x64** platform.

**Comment by JackBoosY** [comment]
Hi @mwill195, thanks for reporting this issue!
I've fixed this issue by upgrade version to 0.1.3.
Please update vcpkg and rebuild aws-sdk-cpp:arm-uwp.

Thanks.
