### ISSUE TITLE
vcpkg support for C++ project builds on Azure-Pipeline

### ISSUE THREAD

**Issue by vSzemkel** [Microsoft/vcpkg#4911]
I'm using AppVeyor. They have a vcpkg preinstalled on build machines for quite a long time.
C'mon guys, this is MSFT orginated package manager. Add the support for this to Azure Pipelines, please.

**Comment by bluekyu** [comment]
I resolved it using build artifacts. I forked vcpkg repository and setup Azure Pipeline in the repo. And then, I added download jobs to Azure projects.
You can see the YAML file in https://github.com/bluekyu/vcpkg/blob/rpcpp-devops/azure-pipelines.yml

And you can find documents about this: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=vsts&tabs=designer#build-completion-triggers

**Comment by lucaspimentel** [comment]
Azure Pipelines Hosted Images has [their own repo](https://github.com/Microsoft/azure-pipelines-image-generation). You should probably create this issue (or a pull request!) there instead.

**Comment by vSzemkel** [comment]
Using build artifacts for building packet manager every time I commit a change to my sources seems overwhelming. Yes @lucaspimentel, You are right - I just could'n find their repo.
