### ISSUE TITLE
[wxwidgets] not available anymore? 

### ISSUE THREAD

**Issue by b1ain** [Microsoft/vcpkg#4913]
vcpkg install wxwidgets:x64-windows yields:
Error: Cannot find definition for package `wxwidgets`.
Is it no longer supported?

Using latest vcpkg from repo, Windows 10.

**Comment by b1ain** [comment]
Ok, so this is kind of what happened last time. So I decided to create a new installation of vcpkg and try installing from there and it finds it when you do the install, how do you "reset" whatever it is that controls what vcpkg sees?

**Comment by Voskrese** [comment]
What is it all about? What's wrong? 
All in open access, source code can watch

**Comment by wangli28** [comment]
Hi @b1ain , thanks for reporting this issue.
Port wxwidgets works fine in vcpkg now. Here is my log:

> PS E:\vcpkg> .\vcpkg.exe install wxwidgets:x64-windows
The following packages will be built and installed:
    wxwidgets[core]:x64-windows
Starting package 1/1: wxwidgets:x64-windows
Building package wxwidgets[core]:x64-windows...
-- Using cached E:/vcpkg/downloads/wxWidgets-wxWidgets-v3.1.2.tar.gz
-- Using source at E:/vcpkg/buildtrees/wxwidgets/src/v3.1.2-38b1831b23
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package wxwidgets[core]:x64-windows... done
Installing package wxwidgets[core]:x64-windows...
Installing package wxwidgets[core]:x64-windows... done
Elapsed time for package wxwidgets:x64-windows: 6.33 min
\
Total elapsed time: 6.33 min

You can update and try again.
Thanks.

**Comment by Cheney-W** [comment]
@b1ain Thanks for your feedback. I could install wxwidgets:x64-windows successfully with VS 2017 15.9.11. Please reopen a new issue if it is still a problem for you!
