### ISSUE TITLE
glags-x64-windows build failed with vs2017

### ISSUE THREAD

**Issue by qdztxc** [Microsoft/vcpkg#4915]
Package: gflags:x64-windows
  Vcpkg version: 2018.11.23-nohash

vcpkg install gflags:x64-windows

D:\vcpkg>vcpkg install gflags:x64-windows
The following packages will be built and installed:
    gflags[core]:x64-windows
Starting package 1/1: gflags:x64-windows
Building package gflags[core]:x64-windows...
Warning: The following VS instances are excluded because the English language pa
ck is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview
Please install the English language pack.
-- Using cached D:/vcpkg/downloads/gflags-gflags-v2.2.2.tar.gz
-- Using source at D:/vcpkg/buildtrees/gflags/src/v2.2.2-d9283b9285
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: D:/vcpkg/buildtrees/gflags/x64-windows-rel/vcpkg-parallel
-configure
    See logs for more information:
      D:\vcpkg\buildtrees\gflags\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:257 (vcpkg_execute_required_process)

  ports/gflags/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package gflags:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: gflags:x64-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

[config-x64-windows-out.log](https://github.com/Microsoft/vcpkg/files/2656114/config-x64-windows-out.log)

**Comment by Voskrese** [comment]
>  Please install the English language pack.

**Comment by qdztxc** [comment]
Thank you. It works!
