### ISSUE TITLE
install bond failed

### ISSUE THREAD

**Issue by Yusheng9966** [Microsoft/vcpkg#4919]
d:\workspace2\github\vcpkg>vcpkg.exe install bond:x64-windows
The following packages will be built and installed:
    bond[core]:x64-windows
  * boost-algorithm[core]:x64-windows
  * boost-array[core]:x64-windows
  * boost-assign[core]:x64-windows
  * boost-atomic[core]:x64-windows
  * boost-build[core]:x64-windows
  * boost-chrono[core]:x64-windows
  * boost-circular-buffer[core]:x64-windows
  * boost-concept-check[core]:x64-windows
  * boost-container[core]:x64-windows
  * boost-container-hash[core]:x64-windows
  * boost-conversion[core]:x64-windows
  * boost-date-time[core]:x64-windows
  * boost-endian[core]:x64-windows
  * boost-exception[core]:x64-windows
  * boost-filesystem[core]:x64-windows
  * boost-foreach[core]:x64-windows
  * boost-function[core]:x64-windows
  * boost-function-types[core]:x64-windows
  * boost-functional[core]:x64-windows
  * boost-fusion[core]:x64-windows
  * boost-integer[core]:x64-windows
  * boost-intrusive[core]:x64-windows
  * boost-io[core]:x64-windows
  * boost-iostreams[core]:x64-windows
  * boost-iterator[core]:x64-windows
  * boost-lambda[core]:x64-windows
  * boost-lexical-cast[core]:x64-windows
  * boost-locale[core]:x64-windows
  * boost-math[core]:x64-windows
  * boost-modular-build-helper[core]:x64-windows
  * boost-move[core]:x64-windows
  * boost-mpl[core]:x64-windows
  * boost-numeric-conversion[core]:x64-windows
  * boost-optional[core]:x64-windows
  * boost-phoenix[core]:x64-windows
  * boost-pool[core]:x64-windows
  * boost-predef[core]:x64-windows
  * boost-preprocessor[core]:x64-windows
  * boost-proto[core]:x64-windows
  * boost-ptr-container[core]:x64-windows
  * boost-range[core]:x64-windows
  * boost-ratio[core]:x64-windows
  * boost-rational[core]:x64-windows
  * boost-regex[core]:x64-windows
  * boost-serialization[core]:x64-windows
  * boost-smart-ptr[core]:x64-windows
  * boost-spirit[core]:x64-windows
  * boost-static-assert[core]:x64-windows
  * boost-system[core]:x64-windows
  * boost-thread[core]:x64-windows
  * boost-throw-exception[core]:x64-windows
  * boost-tokenizer[core]:x64-windows
  * boost-tti[core]:x64-windows
  * boost-tuple[core]:x64-windows
  * boost-type-index[core]:x64-windows
  * boost-type-traits[core]:x64-windows
  * boost-typeof[core]:x64-windows
  * boost-unordered[core]:x64-windows
  * boost-utility[core]:x64-windows
  * boost-variant[core]:x64-windows
  * boost-winapi[core]:x64-windows
  * bzip2[core]:x64-windows
  * liblzma[core]:x64-windows
  * rapidjson[core]:x64-windows
  * zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/66: rapidjson:x64-windows
Building package rapidjson[core]:x64-windows...
Warning: The following VS instances are excluded because the English language pack is unavailable.
    e:\Program Files (x86)\Microsoft Visual Studio\2017\Community
Please install the English language pack.
-- Using cached D:/workspace2/github/vcpkg/downloads/Tencent-rapidjson-v1.1.0.tar.gz
-- Using source at D:/workspace2/github/vcpkg/buildtrees/rapidjson/src/v1.1.0-5f309373e1
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: D:/workspace2/github/vcpkg/buildtrees/rapidjson/x64-windows-rel/vcpkg-parallel-configure
    See logs for more information:
      D:\workspace2\github\vcpkg\buildtrees\rapidjson\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:257 (vcpkg_execute_required_process)
  ports/rapidjson/portfile.cmake:14 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package rapidjson:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: rapidjson:x64-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by Voskrese** [comment]
?

> Warning: The following VS instances are excluded because the English language pack is unavailable.
> e:\Program Files (x86)\Microsoft Visual Studio\2017\Community

**Please install the English language pack.**

**Comment by Yusheng9966** [comment]
> 
> 
> ?
> 
> > Warning: The following VS instances are excluded because the English language pack is unavailable.
> > e:\Program Files (x86)\Microsoft Visual Studio\2017\Community
> 
> **Please install the English language pack.**
Yes, you are right.
Both VS2015 and VS2017 was needed English language environment. It's very necessary for correct compile. I suggest to wrote this in FAQ.
Thanks very much.
