### ISSUE TITLE
fmt should not remove fmt/format.cc and fmt/ostream.cc

### ISSUE THREAD

**Issue by dcrawford1** [Microsoft/vcpkg#492]
The port file explicitly removes fmt/format.cc and fmt/ostream.cc from the installed include directory (probably because they are not *.h files).  But, these are needed when using fmt as a header only library with the cmake fmt-header-only imported target.

**Comment by ras0219-msft** [comment]
Fixed in 4f5f52ff47 with fmt package version `3.0.1-2`. Thanks for the report!
