### ISSUE TITLE
[Request] restbed + OpenSSL feature

### ISSUE THREAD

**Issue by lindevs** [microsoft/vcpkg#4925]
Hi. 
[restbed](https://github.com/Corvusoft/restbed) library support OpenSSL. When building this library with CMake we need to add `-DBUILD_SSL=YES`. Can someone create pull request to enable OpenSSL feature for restbed? 
@Tom-Henoch

**Comment by wangli28** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.

**Comment by lindevs** [comment]
Thanks.
