### ISSUE TITLE
ftp not supported in curl?

### ISSUE THREAD

**Issue by xchgrbprsp** [Microsoft/vcpkg#4926]
I want to use libcurl to download a file from a ftp server.
I installed curl using `vcpkg install curl[*]:x64-windows` without any error.
When I run my program it says `* Protocol "ftp" not supported or disabled in libcurl` but if I use http or https it works just fine.
Is ftp simply not supported or how do I enable ftp support?

I have the latest Windows 10 1803 update and libcurl version 7.61.1-DEV.

**Comment by myd7349** [comment]
Give `vcpkg install curl[non-http]:x64-windows` a try.

The `non-http` feature will turn off `USE_HTTP_ONLY`, which in turns will turn off `HTTP_ONLY`:

https://github.com/curl/curl/blob/master/CMakeLists.txt#L170

**Comment by xchgrbprsp** [comment]
It worked. Thanks a lot.
