### ISSUE TITLE
Could not find machine learning library: opennn, mlpack, and FANN

### ISSUE THREAD

**Issue by edwin-tn** [microsoft/vcpkg#4928]
Could not find machine learning library: opennn (http://www.opennn.net/), mlpack (https://www.mlpack.org/), and FANN (https://github.com/libfann/fann.)

**Comment by PhoebeHui** [comment]
mlpack and fann are avaliable in vcpkg, only openNN remains, so close this issue and reactive https://github.com/microsoft/vcpkg/issues/5062 to track openNN status.
