### ISSUE TITLE
Add CalculiX

### ISSUE THREAD

**Issue by luzpaz** [microsoft/vcpkg#4929]
Calculix - Three-Dimensional Structural Finite Element Program  
Homepage: http://www.calculix.de

Packages on other distros:
AUR: https://aur.archlinux.org/packages/calculix ([PKGbuild](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=calculix))
FreeBSD: https://www.freshports.org/cad/calculix

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
