### ISSUE TITLE
Add Gmsh

### ISSUE THREAD

**Issue by luzpaz** [microsoft/vcpkg#4930]
A three-dimensional finite element mesh generator with built-in pre- and post-processing facilities

[Homepage](http://gmsh.info/)

Packaged in other Distros:
* [Homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gmsh.rb)  
* [AUR](https://aur.archlinux.org/packages/gmsh) ([pkgbuild](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gmsh)) 
* [Linuxbrew](https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/gmsh.rb)
* [Fedora](https://src.fedoraproject.org/rpms/gmsh)
* [FreeBSD](https://www.freshports.org/cad/gmsh)

**Comment by luzpaz** [comment]
Current stable is 1.4.0 per http://gmsh.info/CHANGELOG.txt

**Comment by luzpaz** [comment]
Stable is no 4.1.3

**Comment by NancyLi1013** [comment]
It seems that this port needs to support Fortran.

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!

**Comment by xarthurx** [comment]
@JackBoosY  May I ask where does it say it needs fortran?

https://gitlab.onelab.info/gmsh/gmsh/-/tree/gmsh_4_8_4
It seems this lib can be just build as a standard lib and linked?

**Comment by xarthurx** [comment]
Stable now is 4.8.4.

**Comment by NancyLi1013** [comment]
You can create a PR to add this port if possible. @xarthurx

**Comment by xarthurx** [comment]
@NancyLi1013 
PR here: https://github.com/microsoft/vcpkg/pull/21896

I'm really not good at this and never did one before.
This is what I can do currently, so if there are any issues, especially for build systems and the `features`, please let me know or you can edit it directly.

Thank you.

**Comment by JackBoosY** [comment]
Close this issue via #21896 merged.
