### ISSUE TITLE
Update freetype to 2.9.1

### ISSUE THREAD

**Issue by luzpaz** [Microsoft/vcpkg#4931]
https://sourceforge.net/projects/freetype/files/freetype2/2.9.1/

https://github.com/Microsoft/vcpkg/tree/master/ports/freetype

**Comment by NancyLi1013** [comment]
@luzpaz , this PR has been merged to the master and it has been updated to the version 2.9.1-1. Please take a look. If you have any other requests, please reopen this issue.
Thanks.
