### ISSUE TITLE
sdl2-mixer port not creating SDL2_mixerConfig.cmake

### ISSUE THREAD

**Issue by zx64** [microsoft/vcpkg#4933]
The SDL2 package generates various cmake files (`SDL2Targets.cmake`,`SDL2Config.cmake` etc.) which allows `find_package(SDL2 REQUIRED)` to work without issue or needing to add modules to your CMake project.

Unfortunately this isn't being performed by the CMakeLists included in the `sdl2-mixer` port, so `find_package(SDL2_mixer REQUIRED)` fails.

I've locally created these files by copying the SDL2 versions from `VCROOT\installed\x64-windows\share\sdl2`, editing them to reference `SDL2_mixer` etc. which works but I'm not entirely sure how to proceed with making them autogenerated like the SDL2 package.

**Comment by vicroms** [comment]
@zx64 

Here is a [tutorial of how to import and export targets with CMake](https://gitlab.kitware.com/cmake/community/wikis/doc/tutorials/Exporting-and-Importing-Targets).
If you add support for this port feature please submit a PR 🙏

**Comment by JackBoosY** [comment]
Already fixed.
