### ISSUE TITLE
New upstream version of sdl2-mixer available

### ISSUE THREAD

**Issue by zx64** [Microsoft/vcpkg#4934]
Current port is version 2.0.2, there's now 2.0.4.
It might be worth updating the portfile to use this repo for the download source for consistency with the main SDL2 package:
https://github.com/SDL-mirror/SDL_mixer/releases/tag/release-2.0.4

(I filed this separately to #4933 since it's a much simpler change)

**Comment by wangli28** [comment]
Hi @zx64 ,
Latest version is 2.0.4, you can update vcpkg and rebuild.
Thanks.
