### ISSUE TITLE
GDAL:x64-windows BUILD_FAILED 

### ISSUE THREAD

**Issue by richy46** [Microsoft/vcpkg#4936]
HI! I have tried to build gdal for windows x64. But it failed. And it gives a very strange error in the logfile 
nmake-build-x64-windows-release-err.log.

[nmake-build-x64-windows-release-err.log](https://github.com/Microsoft/vcpkg/files/2661667/nmake-build-x64-windows-release-err.log)

C:\vcpkg>vcpkg install gdal:x64-windows
The following packages will be built and installed:
gdal[core,mysql-libmysql]:x64-windows
Starting package 1/1: gdal:x64-windows
Building package gdal[core,mysql-libmysql]:x64-windows...
-- Using cached C:/vcpkg/downloads/gdal232.zip
-- Extracting source C:/vcpkg/downloads/gdal232.zip
-- Applying patch C:/vcpkg/ports/gdal/0001-Fix-debug-crt-flags.patch
-- Extracting source C:/vcpkg/downloads/gdal232.zip
-- Applying patch C:/vcpkg/ports/gdal/0001-Fix-debug-crt-flags.patch
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
Command failed: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/nmake.exe;-f;makefile.vc;MYSQL_LIB=C:\vcpkg\installed\x64-windows\lib\libmysql.lib;MYSQL_INC_DIR=C:\vcpkg\installed\x64-windows\include\mysql;GDAL_HOME=C:\vcpkg\packages\gdal_x64-windows;DATADIR=C:\vcpkg\packages\gdal_x64-windows\share\gdal;HTMLDIR=C:\vcpkg\packages\gdal_x64-windows\share\gdal\html;GEOS_DIR=C:\vcpkg\installed\x64-windows\include;GEOS_CFLAGS=-IC:\vcpkg\installed\x64-windows\include -DHAVE_GEOS;PROJ_INCLUDE=-IC:\vcpkg\installed\x64-windows\include;EXPAT_DIR=C:\vcpkg\installed\x64-windows\include;EXPAT_INCLUDE=-IC:\vcpkg\installed\x64-windows\include;CURL_INC=-IC:\vcpkg\installed\x64-windows\include;SQLITE_INC=-IC:\vcpkg\installed\x64-windows\include;PG_INC_DIR=C:\vcpkg\installed\x64-windows\include;OPENJPEG_ENABLED=YES;OPENJPEG_CFLAGS=-IC:\vcpkg\installed\x64-windows\include;OPENJPEG_VERSION=20100;WEBP_ENABLED=YES;WEBP_CFLAGS=-IC:\vcpkg\installed\x64-windows\include;LIBXML2_INC=-IC:\vcpkg\installed\x64-windows\include;PNG_EXTERNAL_LIB=1;PNGDIR=C:\vcpkg\installed\x64-windows\include;MSVC_VER=1900;WIN64=YES;WITH_PDB=1;CXX_CRT_FLAGS=/MD;PROJ_LIBRARY=C:\vcpkg\installed\x64-windows\lib\proj.lib;PNG_LIB=C:\vcpkg\installed\x64-windows\lib\libpng16.lib;GEOS_LIB=C:\vcpkg\installed\x64-windows\lib\geos_c.lib;EXPAT_LIB=C:\vcpkg\installed\x64-windows\lib\expat.lib;CURL_LIB=C:\vcpkg\installed\x64-windows\lib\libcurl.lib wsock32.lib wldap32.lib winmm.lib;SQLITE_LIB=C:\vcpkg\installed\x64-windows\lib\sqlite3.lib;PG_LIB=C:\vcpkg\installed\x64-windows\lib\libpq.lib;OPENJPEG_LIB=C:\vcpkg\installed\x64-windows\lib\openjp2.lib;WEBP_LIBS=C:\vcpkg\installed\x64-windows\lib\webp.lib;LIBXML2_LIB=C:\vcpkg\installed\x64-windows\lib\libxml2.lib
Working Directory: C:/vcpkg/buildtrees/gdal/src-x64-windows-release/gdal-2.3.2
See logs for more information:
C:\vcpkg\buildtrees\gdal\nmake-build-x64-windows-release-err.log

Call Stack (most recent call first):
ports/gdal/portfile.cmake:205 (vcpkg_execute_required_process)
scripts/ports.cmake:71 (include)

Error: Building package gdal:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with .\vcpkg update, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
Package: gdal:x64-windows
Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

C:\vcpkg>

########################Log file####################

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation. All rights reserved.

nmake.opt(152) : fatal error U1038: internal error : lexer
Stop.

**Comment by studiofuga** [comment]
I compiled the same with the latest compiler suite, and completed successfully. You should try to update the compiler, can you?

**Comment by studiofuga** [comment]
Mine was 15.8.1 i.e. Visual Studio 2017 latest version available. Yours is outdated and unsupported.

**Comment by richy46** [comment]
Well, I downloaded visual studio 2017 professional 15.9.4. And I got the exact same problem. But I do not have the same version I have as you. With all due respect, your Vs2017 is behind on mine.

So what I did: I cleaned vcpkg folders. and just typed: "vcpkg install gdal:x64-windows. Then it got to work to download and installed 103 depending packages successfully. Then GDAL install fails. Same problem as before.

**Comment by studiofuga** [comment]
My fault, my version is 15.9.3 (I was writing by heart), 15.9.4 was released on dec, 11.
Anyway, I can confirm 15.9.3 is compiling correctly, it is possible that some a regression was introduced, but I'm skeptical. Likely it's something else.
Sorry I can't help more.

**Comment by richy46** [comment]
I think I have found the problem inside the nmake.opt file of GDAL. When I remove the comment line:

# 4275: non – DLL-interface classkey 'identifier' used as base for DLL-interface classkey 'identifier'
nmake is happy again. 

My nmake struggles with the non-ascii character: '–' even though it is inside a comment block.

**Comment by richy46** [comment]
Fixed: https://github.com/OSGeo/gdal/issues/1169.
Obviously this will probably take some time to make it in here.
