### ISSUE TITLE
opencv'reconstruct function is not defined

### ISSUE THREAD

**Issue by takumi0628** [microsoft/vcpkg#4937]
I want to use opencv's reconstruct function. After installing vcpkg, I typed command "vcpkg install opencv[sfm,vtk,contrib]:x64-windows". I have already done "vcpkg integrate install". When I built scene_reconstruction.cpp in opencv_contrib's sample, there was a err code "reconstrut is not defined.

**Comment by UnaNancyOwen** [comment]
Please define <code>CERES_FOUND</code> before including sfm header.
```cpp
#define CERES_FOUND 1
#include <opencv2/sfm.hpp>
```

**Comment by NancyLi1013** [comment]
Hi @takumi0628 and @UnaNancyOwen 
Thanks for posting this issue.

`Opencv `has been updated. Could you please try to update vcpkg and rebuild this?

**Comment by NancyLi1013** [comment]
Might this can help you some.
https://github.com/opencv/opencv_contrib/issues/476

**Comment by smartnet-club** [comment]
If you have modern versions of ceres, glog and gflags, you should apply dif:
[contrib.diff.txt](https://github.com/microsoft/vcpkg/files/4866781/contrib.diff.txt)
