### ISSUE TITLE
Failed to install vcpkg

### ISSUE THREAD

**Issue by BlueSolei** [Microsoft/vcpkg#4947]
I am trying to install vcpkg on my machine. 
I am using Windows 10 Enterprise, 64 bit, version 1607. 
I manage to clone the repo and build successfully with .\bootstrap-vcpkg.bat.
Here is a test run:
```
PS C:\vcpkg> .\vcpkg version
Vcpkg package management program version 2018.11.23-nohash

See LICENSE.txt for license information.
```

Trying to use vcpkg, failed.
The bellow command failed (runs from admin cmd):
```
PS C:\vcpkg> .\vcpkg integrate install
error while writing file: E:\Projects\ThirdParties\scripts\buildsystems\tmp\vcpkg.user.targets: The system cannot find the file specified.
```

A simple package install also fail:
```
PS C:\vcpkg> .\vcpkg install curl
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Error: invalid triplet: x86-windows
Available architecture triplets:
```

I started over (clone, bootstrap) twice from scratch, and still no success.

**Comment by CODER591** [comment]
Try solution in the end of this topic. If you have the 32-bit system
https://github.com/Microsoft/vcpkg/issues/4730

**Comment by BlueSolei** [comment]
Thanks, but my windows is 64bit, and I don't have a problem to build vcpkg.
vcpkg runs but failed logically.

**Comment by BlueSolei** [comment]
Found the issue.
I had VCPKG_ROOT env var from an older installation. 
For some reason, it failed the new installation.
Remove it solved the issue.
