### ISSUE TITLE
Build error in boost-graph with latest vcpkg (Updating after about 6 months away)

### ISSUE THREAD

**Issue by akoolenbourke** [Microsoft/vcpkg#4949]
Hi all. After months away from vcpkg I went back to get all the latest. I did a `git pull`, then `.\bootstrap-vcpkg.bat` and finallly `vcpkg upgrade --no-dry-run`. I got a long way through then hit this error.

`
Building package boost-graph[core]:x86-windows... done
Installing package boost-graph[core]:x86-windows...
Installing package boost-graph[core]:x86-windows... done
Elapsed time for package boost-graph:x86-windows: 34.87 s
Starting package 268/458: python3:x86-windows
Building package python3[core]:x86-windows...
-- Downloading https://github.com/python/cpython/archive/v3.6.4.tar.gz...
-- Extracting source D:/src/vcpkg/downloads/python-cpython-v3.6.4.tar.gz
-- Applying patch D:/src/vcpkg/ports/python3/0004-Fix-iomodule-for-RS4-SDK.patch
-- Applying patch D:/src/vcpkg/ports/python3/0005-Fix-DefaultWindowsSDKVersion.patch
-- Using source at D:/src/vcpkg/buildtrees/python3/src/v3.6.4-5bfb0301b2
-- Building D:/src/vcpkg/buildtrees/python3/src/v3.6.4-5bfb0301b2-Lib-dynamic-crt-dynamic/PCBuild/pythoncore.vcxproj for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: msbuild;D:/src/vcpkg/buildtrees/python3/src/v3.6.4-5bfb0301b2-Lib-dynamic-crt-dynamic/PCBuild/pythoncore.vcxproj;/p:Configuration=Release;/t:Rebuild;/p:Platform=Win32;/p:PlatformToolset=v141;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No;/p:WindowsTargetPlatformVersion=10.0.17763.0;/m
    Working Directory: D:/src/vcpkg/buildtrees/python3/x86-windows-rel
    See logs for more information:
      D:\src\vcpkg\buildtrees\python3\build-x86-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:119 (vcpkg_execute_required_process)
  ports/python3/portfile.cmake:55 (vcpkg_build_msbuild)
  scripts/ports.cmake:71 (include)

Error: Building package python3:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: python3:x86-windows
  Vcpkg version: 2018.11.23-nohash
`
When I re-ran `vcpkg update` -> `git pull` -> `vcpkg upgrade --no-dry-run` it said everything was up to date.

Any ideas and am I in a working state now?

Thanks

**Comment by wangli28** [comment]
@akoolenbourke, thank you for posting the issue, does the issue still occur? I installed `python3[core]:x86-windows` successfully with VS2017 15.9.11 and VCPKG latest source.

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
