### ISSUE TITLE
OpenCV DNN is broken again

### ISSUE THREAD

**Issue by emptyVoid** [Microsoft/vcpkg#4956]
```.\vcpkg install opencv[dnn,ffmpeg,ipp]``` no longer builds/installs the DNN module.

Here's the install log:
```
Starting package 154/169: opencv:x64-windows
Building package opencv[core,dnn,eigen,ffmpeg,flann,ipp,jpeg,opengl,png,tiff]:x64-windows...
-- Downloading https://github.com/opencv/opencv/archive/3.4.3.tar.gz...
-- Extracting source D:/Projects/vcpkg/downloads/opencv-opencv-3.4.3.tar.gz
-- Applying patch D:/Projects/vcpkg/ports/opencv/0001-winrt-fixes.patch
-- Applying patch D:/Projects/vcpkg/ports/opencv/0002-install-options.patch
-- Applying patch D:/Projects/vcpkg/ports/opencv/0003-disable-downloading.patch
-- Applying patch D:/Projects/vcpkg/ports/opencv/0004-use-find-package-required.patch
-- Applying patch D:/Projects/vcpkg/ports/opencv/0005-remove-custom-protobuf-find-package.patch
-- Using source at D:/Projects/vcpkg/buildtrees/opencv/src/3.4.3-a4b58ad028
-- Downloading https://github.com/tiny-dnn/tiny-dnn/archive/v1.0.0a3.tar.gz...
-- Downloading https://raw.githubusercontent.com/opencv/opencv_3rdparty/8041bd6f5ad37045c258904ba3030bb3442e3911/ffmpeg/opencv_ffmpeg.dll...
-- Downloading https://raw.githubusercontent.com/opencv/opencv_3rdparty/8041bd6f5ad37045c258904ba3030bb3442e3911/ffmpeg/opencv_ffmpeg_64.dll...
-- Downloading https://raw.githubusercontent.com/opencv/opencv_3rdparty/8041bd6f5ad37045c258904ba3030bb3442e3911/ffmpeg/ffmpeg_version.cmake...
-- Downloading https://raw.githubusercontent.com/opencv/opencv_3rdparty/bdb7bb85f34a8cb0d35e40a81f58da431aa1557a/ippicv/ippicv_2017u3_win_intel64_general_20180518.zip...
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Warning: Could not find a matching pdb file for:
    D:/Projects/vcpkg/packages/opencv_x64-windows/bin/opencv_ffmpeg343_64.dll
    D:/Projects/vcpkg/packages/opencv_x64-windows/debug/bin/opencv_ffmpeg343_64.dll

-- Performing post-build validation
-- Performing post-build validation done
Building package opencv[core,dnn,eigen,ffmpeg,flann,ipp,jpeg,opengl,png,tiff]:x64-windows... done
Installing package opencv[core,dnn,eigen,ffmpeg,flann,ipp,jpeg,opengl,png,tiff]:x64-windows...
Installing package opencv[core,dnn,eigen,ffmpeg,flann,ipp,jpeg,opengl,png,tiff]:x64-windows... done
Elapsed time for package opencv:x64-windows: 8.862 min
```
And the configure log: [config-x64-windows-out.log](https://github.com/Microsoft/vcpkg/files/2670968/config-x64-windows-out.log)

Most likely the build was broken with #4861. @cenit @ras0219-msft

Please note it was a clean build.

**Comment by cenit** [comment]
mmm that PR is unrelated to this problem IMHO. 
`opencv_ffmpeg343_64.dll` is downloaded as a binary from internet, it is not build during compilation. Some time ago we discussed about using the vcpkg's ffmpeg (I strong support that option) but consensus was not reached and so we still download prebuilt dlls.
Not having a related .pdb is by design in this case, maybe there've been some modifications in vcpkg lately which enforce some checks that are destructive in this case?

**Comment by emptyVoid** [comment]
The problem has nothing to do with the warning in install log.
If you'll look into [config-x64-windows-out.log](https://github.com/Microsoft/vcpkg/files/2670968/config-x64-windows-out.log), DNN is listed in Unavailable modules, and it's no longer being built/installed.

**Comment by emptyVoid** [comment]
I can confirm it now, ```opencv[dnn,ffmpeg,ipp]``` combination was definitely broken by the PR: I've reverted to 42fd0c982a2e201674cea1979457079bb1bce046 (PR's parent commit) and now I'm able to use the DNN module again.

**Comment by cenit** [comment]
Sorry for the problem. You are right, it is missing some pieces in the 0005 patch!!!! Sorry!!!! I will open another PR ASAP! Going out of office now, will do it tonight from home.
Again, sorry, sorry

**Comment by cenit** [comment]
@emptyVoid if you have time, please try #4963 . That was the latest version of the 0005* patch I was using. It should work, let me know

**Comment by twMr7** [comment]
Please revert PR #4861 instead, I don't see any reason to skip the working cmake file from the original opencv code.

**Comment by cenit** [comment]
Many problems have been solved for OpenCV just skipping custom files for 3rd party libraries and using the official ones. It is an unfortunate situation but the upstream developers seem to not be interested in dealing with the whole `optimized;debug` situation for VS.
Again, the `opencv[dnn]` module was *not* working, at least not if you were using VS generator (Ninja is excluded, it was working, but not for cuda, again many complications for complex deploys!).
The #4861 PR was a way to fix it, unfortunately I didn't commit&push the final patch version... I told you I am sorry for the problem, but please try PR #4963 and tell me if you experience any problem, instead of just asking to revert another PR and go back to a known broken situation...

**Comment by twMr7** [comment]
I built opencv:x64-windows port with all features and without "0005-remove-custom-protobuf-find-package.patch", the opencv[dnn] and libprotobuf looks fine to me. Can you point out which part has the linking problem for libprotobuf? or can you provide the log to show the problem?
 
[config-x64-windows-out.log](https://github.com/Microsoft/vcpkg/files/2678248/config-x64-windows-out.log)
[install-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2678249/install-x64-windows-dbg-out.log)
[install-x64-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/2678250/install-x64-windows-rel-out.log)

**Comment by emptyVoid** [comment]
It might have something to do with as issue resolved in [this commit](https://github.com/opencv/opencv/commit/60c26f8f1ec31c3b10f026ce40779c7b412a7667).
Though the fix is from 3.4.4.

For me commenting out the previous 0005 patch works too, and release configuration links to ```libprotobuf.dll```, debug to ```libprotobufd.dll```.

![Release dependency](https://user-images.githubusercontent.com/13639229/49979797-42201e80-ff83-11e8-8603-31ca040dccb0.png)
![Debug dependency](https://user-images.githubusercontent.com/13639229/49979785-316fa880-ff83-11e8-8667-433db44c5d3c.png)

I wanted to try out the new PR, though I've found no way to download the source code at PR's commit, sorry.

**Comment by emptyVoid** [comment]
The fix works for me. Thanks @cenit!

**Comment by MikePelton** [comment]
I'm confused - the fact that a fix exists is marvellous, but has that fix been committed now? If I Git Pull the vcpkg code and build opencv[dnn], will I get the DNN library actually built?

**Comment by emptyVoid** [comment]
Yeah, the fix is already merged into master.

**Comment by MikePelton** [comment]
Brilliant - many thanks.
