### ISSUE TITLE
 Building package pcl:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by ZYberTanC** [Microsoft/vcpkg#4960]
Package: pcl:x64-windows
Vcpkg version: 2018.11.23-nohash

The following packages will be built and installed:
    pcl[core]:x64-windows
Starting package 1/1: pcl:x64-windows
Building package pcl[core]:x64-windows...
-- Using cached C:/vcpkg/downloads/PointCloudLibrary-pcl-pcl-1.9.1.tar.gz
-- Using source at C:/vcpkg/buildtrees/pcl/src/pcl-1.9.1-898b5a3155
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at C:/vcpkg/scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: C:/vcpkg/buildtrees/pcl/x64-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\pcl\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  C:/vcpkg/scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  C:/vcpkg/ports/pcl/portfile.cmake:66 (vcpkg_install_cmake)
  C:/vcpkg/scripts/ports.cmake:71 (include)

Error: Building package pcl:x64-windows failed with: BUILD_FAILED

[install-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2672816/install-x64-windows-dbg-out.log)

**Comment by Cheney-W** [comment]
@ZYberTanC Thanks for your feedback. I could install pcl:x64-windows successfully with VS 2017 15.9.11. Please reopen a new issue if it is still a problem for you!
