### ISSUE TITLE
Update QT to latest 5.12 LTS

### ISSUE THREAD

**Issue by TheScarfix** [Microsoft/vcpkg#4969]

**Comment by Neumann-A** [comment]
Seems to be more work than just updating the portfiles. Tried it and it failed to compile qt5-base due to not finding freetype (although installed). Maybe an update to freetype 2.9.1 is first necessary but that is also an update which is not that straight forward.

**Comment by TheScarfix** [comment]
currently running into a problem with the qt5-declarative module not finding the qtmaind.lib, all other modules (that don't depend on qt5-declarative) work without a problem 🤔

**Comment by Neumann-A** [comment]
qtmaind.lib should be in `<installed triplet or package folder>/debug/lib/manual-link`. 
Either it is not there or qt is not searching there

**Comment by Neumann-A** [comment]
if you make a PR request I could look at it and try to solve the problem

**Comment by LarryIII** [comment]
@TheScarfix Hello there, I noticed your PR https://github.com/Microsoft/vcpkg/pull/4991 has merged, please close this issue. Thank you!

**Comment by Zingam** [comment]
How long will it take to get Qt 5.12.1 which was just released?
