### ISSUE TITLE
TinyXml Linkage error

### ISSUE THREAD

**Issue by FranciscoPDNeto** [Microsoft/vcpkg#4971]
I had a problem with the tinyXml library, I was not being able to change the condenseWhiteSpace variable with the public static inline function TiXmlBase::SetCondenseWhiteSpace. What's happen is that compiler cannot resolve the symbol of variable condenseWhiteSpace, and the inline function is trying to modify its value. The compiler is from Visual Studio 2017. My solution is to specify to compiler that condenseWhiteSpace is imported from dll, and then, on execution time, change to exported from dll.

**Comment by LarryIII** [comment]
@FranciscoPDNeto Hello, there. I noticed your PR was merged, if your issue was resolved, please close this issue.  Thank you!
