### ISSUE TITLE
Error: Building package opengl:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by hzaniatost** [Microsoft/vcpkg#4976]
I did the .\vcpkg update as instructed, but the error is the same for every version of opengl. Either without the suffix -- in case x86 was chosen --, with :x86, :x86-static, :x64, and x64:static. 

So, I believe that there is no port of opengl for windows at all. Any hints ?

vcpkg issued the following message for the compilation w/o the suffix: 

"Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opengl:x86-windows
  Vcpkg version: 2018.11.23-nohash"

I thank you in advance for any help. 

All the best,
Hilton

**Comment by Voskrese** [comment]
log attach

**Comment by hzaniatost** [comment]
Hello, @Voskrese ! 

Here is the log from my attempt to compile opengl.

I've just compiled vckpg.

------------------------------------------------------------------

C:\Users\hilton\github\vcpkg>vcpkg.exe install opengl
The following packages will be built and installed:
    opengl[core]:x86-windows
Starting package 1/1: opengl:x86-windows
Building package opengl[core]:x86-windows...
CMake Error at ports/opengl/portfile.cmake:16 (message):
  Portfile not yet configured for Windows SDK with version:
Call Stack (most recent call first):
  scripts/ports.cmake:71 (include)


Error: Building package opengl:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opengl:x86-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by hzaniatost** [comment]
I'm using Microsoft Visual Studio 2015 Version 14.X, Update 3.

Thanks a lot for any help.

**Comment by hzaniatost** [comment]
Hi, @Voskrese ! 

I've attempted again, this time with opencv[opengl]:x64-windows-static

Here is the log. It stopped in the compilation of tiff.  The error msg was:

 Portfile not yet configured for Windows SDK with version:

I'm using Microsoft Windows 10.

All the best,
Hilton

----------------------------------------------------------------------

C:\Users\hilton\github\vcpkg>vcpkg install opencv[opengl]:x64-windows-static
The following packages will be built and installed:
  * eigen3[core]:x64-windows-static
  * libjpeg-turbo[core]:x64-windows-static
  * liblzma[core]:x64-windows-static
  * libpng[core]:x64-windows-static
    opencv[core,eigen,flann,jpeg,opengl,png,tiff]:x64-windows-static
  * opengl[core]:x64-windows-static
  * tiff[core]:x64-windows-static
  * zlib[core]:x64-windows-static
Additional packages (*) will be modified to complete this operation.
Starting package 1/8: liblzma:x64-windows-static
Building package liblzma[core]:x64-windows-static...
A suitable version of cmake was not found (required v3.12.4). Downloading portable cmake v3.12.4...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.12.4/cmake-3.12.4-win32-x86.zip -> C:\Users\hilton\github\vcpkg\downloads\cmake-3.12.4-win32-x86.zip
Extracting cmake...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> C:\Users\hilton\github\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
A suitable version of nuget was not found (required v4.6.2). Downloading portable nuget v4.6.2...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v4.6.2/nuget.exe -> C:\Users\hilton\github\vcpkg\downloads\nuget.exe
-- Downloading https://github.com/xz-mirror/xz/archive/v5.2.4.tar.gz...
-- Extracting source C:/Users/hilton/github/vcpkg/downloads/xz-mirror-xz-v5.2.4.tar.gz
-- Using source at C:/Users/hilton/github/vcpkg/buildtrees/liblzma/src/v5.2.4-0e2feaf554
-- Applying patch C:/Users/hilton/github/vcpkg/ports/liblzma/enable-uwp-builds.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Downloading https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip...
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Applying patch C:/Users/hilton/github/vcpkg/ports/liblzma/auto-define-lzma-api-static.patch
-- Performing post-build validation
-- Performing post-build validation done
Building package liblzma[core]:x64-windows-static... done
Installing package liblzma[core]:x64-windows-static...
Installing package liblzma[core]:x64-windows-static... done
Elapsed time for package liblzma:x64-windows-static: 2.767 min
Starting package 2/8: eigen3:x64-windows-static
Building package eigen3[core]:x64-windows-static...
-- Downloading https://github.com/eigenteam/eigen-git-mirror/archive/3.3.5.tar.gz...
-- Extracting source C:/Users/hilton/github/vcpkg/downloads/eigenteam-eigen-git-mirror-3.3.5.tar.gz
-- Using source at C:/Users/hilton/github/vcpkg/buildtrees/eigen3/src/3.3.5-dea2ea229a
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package eigen3[core]:x64-windows-static... done
Installing package eigen3[core]:x64-windows-static...
Installing package eigen3[core]:x64-windows-static... done
Elapsed time for package eigen3:x64-windows-static: 2.667 min
Starting package 3/8: zlib:x64-windows-static
Building package zlib[core]:x64-windows-static...
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz...
-- Extracting source C:/Users/hilton/github/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch C:/Users/hilton/github/vcpkg/ports/zlib/cmake_dont_build_more_than_needed.patch
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Installing: C:/Users/hilton/github/vcpkg/packages/zlib_x64-windows-static/share/zlib/copyright
-- Performing CMake integration test
-- Performing post-build validation
-- Performing post-build validation done
Building package zlib[core]:x64-windows-static... done
Installing package zlib[core]:x64-windows-static...
Installing package zlib[core]:x64-windows-static... done
Elapsed time for package zlib:x64-windows-static: 1.807 min
Starting package 4/8: libjpeg-turbo:x64-windows-static
Building package libjpeg-turbo[core]:x64-windows-static...
-- Downloading https://github.com/libjpeg-turbo/libjpeg-turbo/commit/bd96b30b74fe166fc94218cfc64a097fafdcc05f.diff...
-- Downloading https://github.com/libjpeg-turbo/libjpeg-turbo/archive/1.5.3.tar.gz...
-- Extracting source C:/Users/hilton/github/vcpkg/downloads/libjpeg-turbo-libjpeg-turbo-1.5.3.tar.gz
-- Applying patch add-options-for-exes-docs-headers.patch
-- Applying patch linux-cmake.patch
-- Applying patch C:/Users/hilton/github/vcpkg/downloads/libjpeg-turbo-bd96b30b74fe166fc94218cfc64a097fafdcc05f.diff
-- Using source at C:/Users/hilton/github/vcpkg/buildtrees/libjpeg-turbo/src/1.5.3-3db26b6f87
-- Downloading http://www.nasm.us/pub/nasm/releasebuilds/2.12.02/win32/nasm-2.12.02-win32.zip...
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Performing CMake integration test
-- Performing post-build validation
-- Performing post-build validation done
Building package libjpeg-turbo[core]:x64-windows-static... done
Installing package libjpeg-turbo[core]:x64-windows-static...
Installing package libjpeg-turbo[core]:x64-windows-static... done
Elapsed time for package libjpeg-turbo:x64-windows-static: 2.032 min
Starting package 5/8: tiff:x64-windows-static
Building package tiff[core]:x64-windows-static...
-- Downloading http://download.osgeo.org/libtiff/tiff-4.0.10.tar.gz...
-- Extracting source C:/Users/hilton/github/vcpkg/downloads/tiff-4.0.10.tar.gz
-- Applying patch add-component-options.patch
-- Applying patch fix-cxx-shared-libs.patch
-- Applying patch crt-secure-no-deprecate.patch
-- Using source at C:/Users/hilton/github/vcpkg/buildtrees/tiff/src/4.0.10-208d032666
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Installing: C:/Users/hilton/github/vcpkg/packages/tiff_x64-windows-static/share/tiff/copyright
-- Performing CMake integration test
-- Performing post-build validation
-- Performing post-build validation done
Building package tiff[core]:x64-windows-static... done
Installing package tiff[core]:x64-windows-static...
Installing package tiff[core]:x64-windows-static... done
Elapsed time for package tiff:x64-windows-static: 3.667 min
Starting package 6/8: opengl:x64-windows-static
Building package opengl[core]:x64-windows-static...
CMake Error at ports/opengl/portfile.cmake:16 (message):
  Portfile not yet configured for Windows SDK with version:
Call Stack (most recent call first):
  scripts/ports.cmake:71 (include)


Error: Building package opengl:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opengl:x64-windows-static
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by Voskrese** [comment]
**SDK Windows Kits 10 installed?**

https://github.com/Microsoft/vcpkg/blob/master/ports/opengl/portfile.cmake

```

    if (WINDOWS_SDK MATCHES "10.")
        set(LIBGLFILEPATH  "${PROGRAM_FILES_32_BIT}\\Windows Kits\\10\\Lib\\${WINDOWS_SDK}\\um\\${TRIPLET_SYSTEM_ARCH}\\OpenGL32.Lib")
        set(LIBGLUFILEPATH "${PROGRAM_FILES_32_BIT}\\Windows Kits\\10\\Lib\\${WINDOWS_SDK}\\um\\${TRIPLET_SYSTEM_ARCH}\\GlU32.Lib")
        set(HEADERSPATH    "${PROGRAM_FILES_32_BIT}\\Windows Kits\\10\\Include\\${WINDOWS_SDK}\\um")
    elseif(WINDOWS_SDK MATCHES "8.")
        set(LIBGLFILEPATH  "${PROGRAM_FILES_32_BIT}\\Windows Kits\\8.1\\Lib\\winv6.3\\um\\${TRIPLET_SYSTEM_ARCH}\\OpenGL32.Lib")
        set(LIBGLUFILEPATH "${PROGRAM_FILES_32_BIT}\\Windows Kits\\8.1\\Lib\\winv6.3\\um\\${TRIPLET_SYSTEM_ARCH}\\GlU32.Lib")
        set(HEADERSPATH    "${PROGRAM_FILES_32_BIT}\\Windows Kits\\8.1\\Include\\um")
    else()
        message(FATAL_ERROR "Portfile not yet configured for Windows SDK with version: ${WINDOWS_SDK}")
endif()
```

**Comment by hzaniatost** [comment]
Thanks a lot for your input, @Voskrese !

I did install the SDK Windows Kit 10. Great help.

Almost everything went fine this time. Only a problem with the compilation of libpng spoiled the party.

May I guess I miss the ninja utility, similar to make ?

Could you please give us again your expert help ?

Here is the command prompt output and attached follows the log. 

All the best,
Hilton

----------------------------------------------------------------------------------------------------

C:\Users\hilton\github\vcpkg>vcpkg install opencv[opengl]:x64-windows-static
The following packages will be built and installed:
  * libpng[core]:x64-windows-static
    opencv[core,eigen,flann,jpeg,opengl,png,tiff]:x64-windows-static
  * opengl[core]:x64-windows-static
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: opengl:x64-windows-static
Building package opengl[core]:x64-windows-static...
-- Performing post-build validation
-- Performing post-build validation done
Building package opengl[core]:x64-windows-static... done
Installing package opengl[core]:x64-windows-static...
Installing package opengl[core]:x64-windows-static... done
Elapsed time for package opengl:x64-windows-static: 6.281 s
Starting package 2/3: libpng:x64-windows-static
Building package libpng[core]:x64-windows-static...
-- Downloading https://github.com/glennrp/libpng/archive/v1.6.35.tar.gz...
-- Extracting source C:/Users/hilton/github/vcpkg/downloads/glennrp-libpng-v1.6.35.tar.gz
-- Using source at C:/Users/hilton/github/vcpkg/buildtrees/libpng/src/v1.6.35-ee4b82ca22
-- Applying patch C:/Users/hilton/github/vcpkg/ports/libpng/use-abort-on-all-platforms.patch
-- Applying patch C:/Users/hilton/github/vcpkg/ports/libpng/skip-install-symlink.patch
-- Configuring x64-windows-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: C:/Users/hilton/github/vcpkg/buildtrees/libpng/x64-windows-static-rel/vcpkg-parallel-configure
    See logs for more information:
      C:\Users\hilton\github\vcpkg\buildtrees\libpng\config-x64-windows-static-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:257 (vcpkg_execute_required_process)
  ports/libpng/portfile.cmake:26 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package libpng:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libpng:x64-windows-static
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

-------------------------------------------------------------------------------------------

[config-x64-windows-static-out.log](https://github.com/Microsoft/vcpkg/files/2695570/config-x64-windows-static-out.log)

**Comment by Voskrese** [comment]
**reinstall** Microsoft Visual Studio 14.0 and full package

```

-- The C compiler identification is MSVC 19.0.24215.1
-- The ASM compiler identification is MSVC
-- Found assembler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- broken
CMake Error at C:/Users/hilton/github/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/share/cmake-3.12/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe"

  is not able to compile a simple test program.
```

**Comment by hzaniatost** [comment]
Thanks a lot, @Voskrese  ! 

I was afraid exactly that my MSVC installation was not sane. 

All the best,
Hilton

**Comment by JackBoosY** [comment]
Hi @hzaniatost , thanks for reporting this issue.
Please open a new issue if this is still a problem for you.
Thx.

**Comment by ghuser123** [comment]
@Voskrese , can you please tell in details for a newbie regarding how to install SDK Windows Kits 10 ?

**Comment by Voskrese** [comment]
@ghuser123 
https://developer.microsoft.com/en-us/windows/downloads/sdk-archive

**Comment by ghuser123** [comment]
@Voskrese , isn't the  SDK Windows Kits 10 automatically installed when Windows 10 is installed ?

**Comment by Voskrese** [comment]
> all individually, depending on what you are compiling, depending on which compiler, the dependency depends on the code, ask the person who wrote the code you are compiling

**Comment by jkang-eng** [comment]
> * Working Directory: C:/Users/hilton/github/vcpkg/buildtrees/libpng/x64-windows-static-rel/vcpkg-parallel-configure

Hi, there.
Fortunately, I'm facing the same issue.  How did you resolve the issue?
Reinstall VS2015 with "Install All" option ?? (this requires 30GB installation tho :(

**Comment by jkang-eng** [comment]
> Thanks a lot for your input, @Voskrese !
> 
> I did install the SDK Windows Kit 10. Great help.
> 
> Almost everything went fine this time. Only a problem with the compilation of libpng spoiled the party.
> 
> May I guess I miss the ninja utility, similar to make ?
> 
> Could you please give us again your expert help ?
> 
> Here is the command prompt output and attached follows the log.
> 
> All the best,
> Hilton
> 
> C:\Users\hilton\github\vcpkg>vcpkg install opencv[opengl]:x64-windows-static
> The following packages will be built and installed:
> 
> * libpng[core]:x64-windows-static
>   opencv[core,eigen,flann,jpeg,opengl,png,tiff]:x64-windows-static
> * opengl[core]:x64-windows-static
>   Additional packages (*) will be modified to complete this operation.
>   Starting package 1/3: opengl:x64-windows-static
>   Building package opengl[core]:x64-windows-static...
>   -- Performing post-build validation
>   -- Performing post-build validation done
>   Building package opengl[core]:x64-windows-static... done
>   Installing package opengl[core]:x64-windows-static...
>   Installing package opengl[core]:x64-windows-static... done
>   Elapsed time for package opengl:x64-windows-static: 6.281 s
>   Starting package 2/3: libpng:x64-windows-static
>   Building package libpng[core]:x64-windows-static...
>   -- Downloading https://github.com/glennrp/libpng/archive/v1.6.35.tar.gz...
>   -- Extracting source C:/Users/hilton/github/vcpkg/downloads/glennrp-libpng-v1.6.35.tar.gz
>   -- Using source at C:/Users/hilton/github/vcpkg/buildtrees/libpng/src/v1.6.35-ee4b82ca22
>   -- Applying patch C:/Users/hilton/github/vcpkg/ports/libpng/use-abort-on-all-platforms.patch
>   -- Applying patch C:/Users/hilton/github/vcpkg/ports/libpng/skip-install-symlink.patch
>   -- Configuring x64-windows-static
>   CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
>   Command failed: ninja;-v
>   Working Directory: C:/Users/hilton/github/vcpkg/buildtrees/libpng/x64-windows-static-rel/vcpkg-parallel-configure
>   See logs for more information:
>   C:\Users\hilton\github\vcpkg\buildtrees\libpng\config-x64-windows-static-out.log
> 
> Call Stack (most recent call first):
> scripts/cmake/vcpkg_configure_cmake.cmake:257 (vcpkg_execute_required_process)
> ports/libpng/portfile.cmake:26 (vcpkg_configure_cmake)
> scripts/ports.cmake:71 (include)
> 
> Error: Building package libpng:x64-windows-static failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
> Package: libpng:x64-windows-static
> Vcpkg version: 2018.11.23-nohash
> 
> Additionally, attach any relevant sections from the log files above.
> 
> [config-x64-windows-static-out.log](https://github.com/Microsoft/vcpkg/files/2695570/config-x64-windows-static-out.log)

Hi @hzaniatost,
Fortunately(?), I'm facing the same issue. How did you resolve the issue?
Reinstall VS2015 with "Install All" option ?? (this requires 30GB installation tho :(

**Comment by JackBoosY** [comment]
@jkang-eng Are your questions the same? Please attach your failure log.

Thanks.
