### ISSUE TITLE
VCPKG has an error with MSB3073 on vs2017?

### ISSUE THREAD

**Issue by chengshuyi** [microsoft/vcpkg#4980]
My os is windows 7 64bit and code in vs2017.

`严重性	代码	说明	项目	文件	行	禁止显示状态
错误	MSB3073	命令“C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -noprofile -File "C:\Users\Administrator\vcpkg\scripts\buildsystems\msbuild\applocal.ps1" "C:\Users\Administrator\source\repos\ConsoleApplication1\Debug\ConsoleApplication1.exe" "C:\Users\Administrator\vcpkg\installed\x86-windows\debug\bin" "Debug\ConsoleA.4A8B53C8.tlog\ConsoleApplication1.write.1u.tlog" "Debug\vcpkg.applocal.log"”已退出，代码为 -65536。	ConsoleApplication1	C:\Users\Administrator\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets	88	
`

**Comment by PhoebeHui** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.
