### ISSUE TITLE
Failed to integrate install

### ISSUE THREAD

**Issue by chengshuyi** [Microsoft/vcpkg#4981]
My environment is windows 7 64bit.

I run `bootstrap-vcpkg.bat` successfully and got a vcpkg.exe file.
Then run `cpkg integrate install` failedly in admin cmd. The error log shows:

`
Failed to copy targets file to C:\Program Files <x86>\MSBuild\Microsoft.Cpp\v4.0\V140\ImportBefore\Default\vcpkg.system.props
`

How to fix it?

Thanks for any advice!

**Comment by chengshuyi** [comment]
This problem has been solved by reinstalling the windows.

**Comment by baimafeitu** [comment]
I have the same problem. My windows version is: Win10 Home Edition, version number:19042.1052.  Visual Studio version is 2019 community. Thank you very much for your any advice!
