### ISSUE TITLE
Add new package - PolyHook 2

### ISSUE THREAD

**Issue by stevemk14ebr** [microsoft/vcpkg#4984]
Some of my users have been requesting that my library: https://github.com/stevemk14ebr/PolyHook_2_0 be added to vcpkg. Can we do it 😃 ?

**Comment by ras0219-msft** [comment]
Absolutely; we'd love to have a PR!

**Comment by NancyLi1013** [comment]
Hi @stevemk14ebr, thanks for posting this request. We have added polyhook2 to vcpkg now. Please open a new issue if you have any other problems.

**Comment by stevemk14ebr** [comment]
I forgot about this, what a nice surprise, thank you!

**Comment by Convery** [comment]
Fails to build as it's looking for headers in `headers/` while all headers are dumped in the VCPKG root dir.

**Comment by stevemk14ebr** [comment]
Might find some time this weekend to fix and add the other branch unless @NancyLi1013 wants to swoop in and fix it up.

**Comment by stevemk14ebr** [comment]
Hey I just tried this, i cannot reproduce. Fresh system, fresh vcpkg install, fresh vcpkg install, worked fine.
