### ISSUE TITLE
libmariadb build  faild after set vcpkg_toolset v140 (vs2017)

### ISSUE THREAD

**Issue by 2812140729** [Microsoft/vcpkg#4998]
vcpkg version: version 2018.11D.23-nohash

After Add Set(vcpkg_toolset v140) 

libmariadb build failed. other libs work well.

the log file say ,can't locate default vctarget file

**Comment by JackBoosY** [comment]
Hi @2812140729 , thanks for reporting this issue.
After I added toolset, libmariadb still build successful.
Could you repro it?
Thx.

**Comment by JackBoosY** [comment]
Hi @2812140729 , Please open a new issue if this is still a problem for you. Thanks.
