### ISSUE TITLE
Handling static library dependencies

### ISSUE THREAD

**Issue by mmassing** [microsoft/vcpkg#500]
I'd like to start a discussion on possible ways to handle transitive dependencies of
static libraries, and see if a standarized solution can be found for vcpkg. I'm only considering the cmake 
build perspective here, because I don't have experience using the vcpkg Visual Studio integration.

As an example, consider an application wanting to statically link against libcurl. libcurl depends on libssh2, 
but the static libcurl.lib will not record this dependency. Therefore the dependency needs to be recorded 
externally to facilitate linking.

I know of two commonly used mechanisms which try to address this issue:
- pkg-config
- Exporting targets into cmake config files

I think the latter would be the best fit for a cmake based build, as in contrast to the pkg-config solution 
this might work transparently <del> (because find_package will look for config  files before invoking the 
FindXXX script). <del>

For pkg-config to work in a cmake-based build, the individual FindXXX.cmake 
modules would need to be adapted to use pkg-config (most do not).

So what would be needed to make cmake imported targets work generically? 
At the very least, I think we would need a standarized location for the cmake config files.
Currently, some ports already install their exported target config files, but I don't know how  these 
can be picked up automatically.

Exporting targets into cmake config can only be easily implemented for cmake based ports,
this could be addressed by implementing helper scripts which 
- convert pkg-config information into a cmake config file
- write "hand-crafted" cmake configs

**Comment by mmassing** [comment]
Unforuntately, I was mistaken in assuming that cmake would first look for a config file before
using the FindXXX.cmake module. So the config-based solution wouldn't be completely transparent either.

**Comment by pfultz2** [comment]
You can force config with `find_package(${PKG} CONFIG)`.

**Comment by LilyWangL** [comment]
This issue hasn’t been updated in two year, if it is still an issue, please reopen.
