### ISSUE TITLE
zlibd1.dll is missing in installed Directory

### ISSUE THREAD

**Issue by DerKleinePunk** [Microsoft/vcpkg#5001]
zlibd1.dll is missing in installed Directory. It is build but not copy.

**Comment by Neumann-A** [comment]
since it is working for me and maybe others: Which triplet are you using?

**Comment by Cheney-W** [comment]
@DerKleinePunk Thanks for your feedback. I could install zlib:x64-windows successfully with VS 2017 15.9.11 and the zlibd1.dll is also copied into \installed\x64-windows\debug\bin . Please reopen a new issue if it is still a problem for you!
