### ISSUE TITLE
Is it possible to compile with iar compiler.

### ISSUE THREAD

**Issue by Eldadc** [microsoft/vcpkg#5008]
Is there an option to connect iar workbench or compiler with vcpkg

Thanks

**Comment by cmpute** [comment]
I guess this functionality is related to CMake rather than vcpkg. Or you mean automatically integrate vcpkg paths into IAR?

**Comment by Eldadc** [comment]
Hi,

I mean both points.

Thanks

**Comment by cmpute** [comment]
CMake with IAR could be possible: https://github.com/Kitware/CMake/blob/master/Modules/Compiler/IAR.cmake
But integrate the paths into IAR workspace may need some work

**Comment by PhoebeHui** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.
