### ISSUE TITLE
DirectXTK portfile building incorrect project for x86-uwp and x64-uwp

### ISSUE THREAD

**Issue by pvarcholik** [microsoft/vcpkg#5011]
As I understand it, DirectXTK_Windows10.sln/.vcxproj is the UWP solution/project that should be built for DirectXTK -- however, the portfile does not differentiate and builds DirectXTK_Desktop_2017.sln for any triplet. That causes linker failures for dependent UWP projects.

Please note, that solution (DirectX_Windows10.sln) does not build the tools that are built under the Desktop solution. Thus the portfile would need to take that into account when installing MakeSpriteFont.exe XWBTool.exe.

**Comment by Cheney-W** [comment]
This issue has been fixed. Thanks for reporting this issue.
