### ISSUE TITLE
assimp static triplet cmake file doesn't include the IrrXML library

### ISSUE THREAD

**Issue by akaltar** [microsoft/vcpkg#5012]
using latest vcpkg of writing on windows:

installing assimp:x64-windows-static 
then importing in a CMake project with find_package( assimp required )
doesn't put IrrXML in the ASSIMP_LIBRARIES variable, also doesn't set ASSIMP_LIBRARY_DIRS correctly for debug builds.
This results in: build failing with undefined reference to IrrXML functions.
even if I add IrrXML manually, it won't work in debug builds, since IrrXMLd is not on ASSIMP_LIBRARY_DIRS paths. (For the main libassimp_vc140d.lib the ASSIMP_LIBRARY_DIR is baked into the ASSIMP_LIBRARIES name)

IrrXML is a dependency of assimp and is built with it.

I'd try fixing this issue myself but the assimp.portfile is already doing string replacement with the ASSIMP_LIBRARIES variable that I don't understand and IrrXML isn't even mentioned(even though it seems to be installed correctly.)

**Comment by Voskrese** [comment]
rename libassimp_vc140d.lib to libassimpd.lib ?

**Comment by JackBoosY** [comment]
Hi @akaltar, thanks for reporting this issue!
Should we modify portfile.cmake and change line54-line55 with the following code?
```
  if (VCPKG_LIBRARY_LINKAGE STREQUAL dynamic)
    string(REPLACE "set( ASSIMP_LIBRARIES \${ASSIMP_LIBRARIES})"
                   "set( ASSIMP_LIBRARIES optimized \${ASSIMP_LIBRARY_DIRS}/\${ASSIMP_LIBRARIES}.lib debug \${ASSIMP_LIBRARY_DIRS}/../debug/lib/\${ASSIMP_LIBRARIES}d.lib)" ASSIMP_CONFIG ${ASSIMP_CONFIG})
  else()
    string(REPLACE "set( ASSIMP_LIBRARIES \${ASSIMP_LIBRARIES})"
                   "set( ASSIMP_LIBRARIES optimized \${ASSIMP_LIBRARY_DIRS}/\${ASSIMP_LIBRARIES}.lib \${ASSIMP_LIBRARY_DIRS}/IrrXML.lib debug \${ASSIMP_LIBRARY_DIRS}/../debug/lib/\${ASSIMP_LIBRARIES}d.lib \${ASSIMP_LIBRARY_DIRS}/../debug/lib/IrrXMLd.lib)" ASSIMP_CONFIG ${ASSIMP_CONFIG})
  endif()
```
Is that correct?

**Comment by akaltar** [comment]
I think this is almost correct, but I think you'll have to specify `debug` and `optimized` before every library you mention, so more like this: 

```if (VCPKG_LIBRARY_LINKAGE STREQUAL dynamic)
    string(REPLACE "set( ASSIMP_LIBRARIES \${ASSIMP_LIBRARIES})"
                   "set( ASSIMP_LIBRARIES optimized \${ASSIMP_LIBRARY_DIRS}/\${ASSIMP_LIBRARIES}.lib debug \${ASSIMP_LIBRARY_DIRS}/../debug/lib/\${ASSIMP_LIBRARIES}d.lib)" ASSIMP_CONFIG ${ASSIMP_CONFIG})
  else()
    string(REPLACE "set( ASSIMP_LIBRARIES \${ASSIMP_LIBRARIES})"
                   "set( ASSIMP_LIBRARIES optimized \${ASSIMP_LIBRARY_DIRS}/\${ASSIMP_LIBRARIES}.lib optimized \${ASSIMP_LIBRARY_DIRS}/IrrXML.lib debug \${ASSIMP_LIBRARY_DIRS}/../debug/lib/\${ASSIMP_LIBRARIES}d.lib debug \${ASSIMP_LIBRARY_DIRS}/../debug/lib/IrrXMLd.lib)" ASSIMP_CONFIG ${ASSIMP_CONFIG})
  endif()
```

**Comment by JackBoosY** [comment]
Hi @akaltar, I've fixed this issue.
Please update vcpkg and rebuild assimp.

Thanks.
