### ISSUE TITLE
Fail to build itk

### ISSUE THREAD

**Issue by pyfdrw** [Microsoft/vcpkg#5016]
I was using:  
Package: itk:x64-windows
Vcpkg version: 2018.11.23-nohash
and tried to install itk. But I got some mistakes.

The install step stoped at:
//////////////////////////////
Starting package 1/1: itk:x64-windows
Building package itk[core]:x64-windows...
-- Using cached D:/vcpkg/downloads/InsightSoftwareConsortium-ITK-d92873e33e8a54e933e445b92151191f02feab42.tar.gz
-- Extracting source D:/vcpkg/downloads/InsightSoftwareConsortium-ITK-d92873e33e8a54e933e445b92151191f02feab42.tar.gz
-- Using source at D:/vcpkg/buildtrees/itk/src/1f02feab42-0e31fc5de4
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: D:/vcpkg/buildtrees/itk/x64-windows-dbg
    See logs for more information:
      D:\vcpkg\buildtrees\itk\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/itk/portfile.cmake:63 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package itk:x64-windows failed with: BUILD_FAILED
///////////////////////////

The last lines of "install-x64-windows-dbg-out.log" were attached:
/////////////////////////////
**Modules\ThirdParty\VNL\src\vxl\core\vnl\CMakeFiles\itkvnl.dir\Templates\vnl_vector_fixed+float.4-.cxx.obj 
Modules\ThirdParty\VNL\src\vxl\core\vnl\CMakeFiles\itkvnl.dir\Templates\vnl_vector_fixed+float.5-.cxx.obj 
Modules\ThirdParty\VNL\src\vxl\core\vnl\CMakeFiles\itkvnl.dir\Templates\vnl_vector_fixed+float.9-.cxx.obj 
Modules\ThirdParty\VNL\src\vxl\core\vnl\CMakeFiles\itkvnl.dir\Templates\vnl_vector_fixed+int.1-.cxx.obj 
Modules\ThirdParty\VNL\src\vxl\core\vnl\CMakeFiles\itkvnl.dir\Templates\vnl_vector_fixed+int.2-.cxx.obj 
Modules\ThirdParty\VNL\src\vxl\core\vnl\CMakeFiles\itkvnl.dir\Templates\vnl_vector_fixed+int.3-.cxx.obj 
Modules\ThirdParty\VNL\src\vxl\core\vnl\CMakeFiles\itkvnl.dir\Templates\vnl_vector_fixed+int.4-.cxx.obj 
Modules\ThirdParty\VNL\src\vxl\core\vnl\CMakeFiles\itkvnl.dir\Templates\vnl_vector_fixed+uchar.16-.cxx.obj 
Modules\ThirdParty\VNL\src\vxl\core\vnl\CMakeFiles\itkvnl.dir\Templates\vnl_vector_fixed+ushort.2-.cxx.obj 
Modules\ThirdParty\VNL\src\vxl\core\vnl\CMakeFiles\itkvnl.dir\Templates\vnl_vector_fixed+vnl_bignum.1-.cxx.obj 
Modules\ThirdParty\VNL\src\vxl\core\vnl\CMakeFiles\itkvnl.dir\Templates\vnl_vector_fixed+vnl_bignum.2-.cxx.obj 
Modules\ThirdParty\VNL\src\vxl\core\vnl\CMakeFiles\itkvnl.dir\Templates\vnl_vector_fixed+vnl_bignum.3-.cxx.obj 
Modules\ThirdParty\VNL\src\vxl\core\vnl\CMakeFiles\itkvnl.dir\Templates\vnl_vector_fixed+vnl_rational.1-.cxx.obj 
Modules\ThirdParty\VNL\src\vxl\core\vnl\CMakeFiles\itkvnl.dir\Templates\vnl_vector_fixed+vnl_rational.2-.cxx.obj 
Modules\ThirdParty\VNL\src\vxl\core\vnl\CMakeFiles\itkvnl.dir\Templates\vnl_vector_fixed+vnl_rational.3-.cxx.obj 
Modules\ThirdParty\VNL\src\vxl\core\vnl\CMakeFiles\itkvnl.dir\Templates\vnl_vector_fixed+vnl_rational.4-.cxx.obj 
Modules\ThirdParty\VNL\src\vxl\core\vnl\CMakeFiles\itkvnl.dir\Templates\vnl_vector_fixed_ref+double.3-.cxx.obj 
Modules\ThirdParty\VNL\src\vxl\core\vnl\CMakeFiles\itkvnl.dir\Templates\vnl_vector_fixed_ref+double.4-.cxx.obj 
Modules\ThirdParty\VNL\src\vxl\core\vnl\CMakeFiles\itkvnl.dir\Templates\vnl_vector_fixed_ref+float.3-.cxx.obj 
ninja: build stopped: subcommand failed.
///////////////////////////

I was confused with the "+" in the file path above. Is it the true form?
Thanks!

**Comment by PhoebeHui** [comment]
Hi pyfdrw, 

The filename contains "+", see ITK source 
https://github.com/InsightSoftwareConsortium/ITK/tree/master/Modules/ThirdParty/VNL/src/vxl/core/vnl/Templates.

Please close this issue if it's solved, thanks!

**Comment by pyfdrw** [comment]
> Hi pyfdrw,
> 
> The filename contains "+", see ITK source
> https://github.com/InsightSoftwareConsortium/ITK/tree/master/Modules/ThirdParty/VNL/src/vxl/core/vnl/Templates.
> 
> Please close this issue if it's solved, thanks!

Thank you for your answer!  The filename contains "+".
But I still can not compile vtk by using vcpkg. So I do the work using cmake separately and configure it for my itk-based job.
Thanks!

**Comment by pyfdrw** [comment]
> Hi pyfdrw,
> 
> The filename contains "+", see ITK source
> https://github.com/InsightSoftwareConsortium/ITK/tree/master/Modules/ThirdParty/VNL/src/vxl/core/vnl/Templates.
> 
> Please close this issue if it's solved, thanks!

So, the issue was solved in other way.

**Comment by PhoebeHui** [comment]
Thanks pyfdrw!

ITK install fails by double-conversion which has exist issue https://github.com/Microsoft/vcpkg/issues/4334 to track, if you see another issue, feel free to report a new issue, thanks!
