### ISSUE TITLE
How integration works

### ISSUE THREAD

**Issue by alexkaratarakis** [Microsoft/vcpkg#502]
The integration is done via a targets file. VS (MSBuild to be precise) has a couple of blessed folders; targets files within them are automatically loaded for every project. 

For `vcpkg`, we have an immutable targets file that redirects to a per-user targets file (e.g. C:\Users\<username>\AppData\Local\vcpkg\vcpkg.user.targets). This is done so each user can have separate settings and also so you can modify said settings without requiring admin privileges. `vcpkg integrate install` places the aforementioned vcpkg.user.targets files which enables VS integration.
(If you want to see the exact details, vcpkg\toolsrc\src\commands_integration.cpp is the source code for this functionality)

**Comment by JunielKatarn** [comment]
This is very confusing with multiple Visual Studio / VC installations.

Where exactly is the integration happening?
How exatly does MSBuild load vcpkg.user.targets?
