### ISSUE TITLE
VS_GLOBAL_VcpkgEnabled is false by default

### ISSUE THREAD

**Issue by xrootpi** [Microsoft/vcpkg#5021]
https://github.com/Microsoft/vcpkg/blob/501abecda7b9997d4492a08114b0a94e78b46007/scripts/buildsystems/vcpkg.cmake#L174

This is could be an issue when the project cmake file is catering to create adhoc vistual studio project. It defaults to <VcpkgEnabled>false</VcpkgEnabled> in the VS project file. 
Thus preventing auto build when vcpkg install command is run. This is needed when the VS project is depended on other vcpkg ports.

**Comment by Rastaban** [comment]
This is intended behavior.  See discussion on PR #5064.
