### ISSUE TITLE
Port request: libopenmpt

### ISSUE THREAD

**Issue by debrouxl** [Microsoft/vcpkg#503]
libopenmpt is a newer derivative of the original modplug code than libmodplug, which is already in the vcpkg ports tree. libopenmpt offers better accuracy and better security than libmodplug does; it is more actively maintained. It's a better choice for the short term and the long term.

I'm not merely repeating what the official site https://lib.openmpt.org/libopenmpt/ states :-)
Although libmodplug usually does the job, I've noticed that it audibly misrenders several recent modules by Saga Musix.

**Comment by atkawa7** [comment]
@ras0219-msft can be closed now

**Comment by debrouxl** [comment]
Why ? AFAICS:
* a case-insensitive grep of "openmpt" in the whole vcpkg repo at the current HEAD revision ( f0fea1d58801167778f9f77f91ecf08a8438e135 ) comes up empty;
* libmodplug's security issues have only been partially fixed upstream;
* libmodplug's rendering inaccuracies remain.

**Comment by sagamusix** [comment]
vcpkg was being worked on but I wasn't aware that it's finished yet.

**Comment by atkawa7** [comment]
@ras0219-msft my apologies I thought I had seen this somewhere

**Comment by alexkaratarakis** [comment]
Merged, thanks!

**Comment by manxorist** [comment]
I'm the libopenmpt maintainer.
Apparently Github does not send email notifications about an issue being referenced by a pull request. (i.e. I was not notified about https://github.com/Microsoft/vcpkg/issues/503#ref-pullrequest-292196745 ).
I thus only became aware of this pull request when it had already been merged and this issue got closed.
Please see my comments on the changes: https://github.com/Microsoft/vcpkg/pull/2669
