### ISSUE TITLE
have some problem

### ISSUE THREAD

**Issue by daoqiang** [Microsoft/vcpkg#5031]
![744g l54m k h pgaq2zds](https://user-images.githubusercontent.com/16305190/50412273-23523f80-0841-11e9-9c6a-a3ca0a8f38c8.png)

**Comment by Voskrese** [comment]
? can immediately video
log txt please!

**Comment by daoqiang** [comment]
[config-x86-windows-out.log](https://github.com/Microsoft/vcpkg/files/2708327/config-x86-windows-out.log)

**Comment by daoqiang** [comment]
help me,thx

**Comment by Voskrese** [comment]
```
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe -- broken
CMake Error at C:/Program Files/CMake/share/cmake-3.12/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler
```

Install the English package or completely reinstall MSVC

**Comment by daoqiang** [comment]
The error reason is no english language pack，I have installed it and solved this problem,thank you for your help
