### ISSUE TITLE
terra

### ISSUE THREAD

**Issue by princetonpku** [microsoft/vcpkg#5032]
Terra is a low-level system programming language that is embedded in and meta-programmed by the Lua programming language. https://github.com/zdevito/terra
I think it will very useful in future. However, compile it in windows is very difficulty. Could vcpkg add it in the list? Thank you!

**Comment by DemonCyborg** [comment]
LLVM takes so long to build!

**Comment by DemonCyborg** [comment]
Initial port https://github.com/DemonCyborg/vcpkg/commits/terra (Not working yet)

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
