### ISSUE TITLE
Can't even use 'vcpkg' in Powershell

### ISSUE THREAD

**Issue by naisyrk** [Microsoft/vcpkg#5045]
Hello, I cant even use term vcpkg, I'm following this guide:
https://github.com/edubart/otclient/wiki/Compiling-on-Windows

This is from PowerShell:

> The term 'vcpkg' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spell
> ing of the name, or if a path was included, verify that the path is correct and try again.
> At line:1 char:6
> + vcpkg <<<<  install pcl:x64-windows-static
>     + CategoryInfo          : ObjectNotFound: (vcpkg:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException

Any solutions?

**Comment by voltagex** [comment]
Use `.\vcpkg` (note the dot-slash) if you're running from your vcpkg path, or add the path to your `$env:PATH`

**Comment by Codiferous** [comment]
@naisyrk Did @voltagex 's suggestion solve the problem for you?

**Comment by JackBoosY** [comment]
Hi @naisyrk, Thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.

**Comment by L4ZZA** [comment]
@JackBoosY This should have not been closed as it should be done as part of the bootstrap (see #6379)

**Comment by angeloavellar** [comment]
I have the same problem, even with the .\ it won't work

**Comment by JackBoosY** [comment]
@L4ZZA  @angeloavellar we already have a same issue here: #5413.

**Comment by mylawacad** [comment]
I solved this by running the command in the PowerShell opened with Administrator permissions

**Comment by salahbesbes** [comment]
run:  vcpkg integrate install
