### ISSUE TITLE
bzip2:x86-windows-static

### ISSUE THREAD

**Issue by 7thTool** [Microsoft/vcpkg#5048]
I'm using visual studio 2015 
.\vcpkg.exe install boost:x86-windows-static boost:x64-windows-static
I can see

-- Downloading http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz...
-- Downloading http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz... OK
-- Testing integrity of downloaded file...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:87 (message):

  File does not have expected hash:

          File path: [ C:/vcpkg/downloads/temp/bzip2-1.0.6.tar.gz ]
      Expected hash: [ 00ace5438cfa0c577e5f578d8a808613187eff5217c35164ffe044fbafdfec9e98f4192c02a7d67e01e5a5ccced630583ad1003c37697219b0f147343a3fdd12 ]
        Actual hash: [ e1a23ec1b796b08b50379c65a1efbd442a10cbb60d14b27110cca8d3c1bfd6d22d427844d9892cdb75cb47c46174e2302e1b3ebb59e460530ee7a58dbc964fbf ]

  The file may have been corrupted in transit.  This can be caused by
  proxies.  If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
  environment variables to
  "https://user:password@your-proxy-ip-address:port/".

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:162 (test_hash)
  ports/bzip2/portfile.cmake:4 (vcpkg_download_distfile)
  scripts/ports.cmake:72 (include)

Error: Building package bzip2:x86-windows-static failed with: BUILD_FAILED

**Comment by ZhilkinSerg** [comment]
I have different error

```
c:\Projects\vcpkg>vcpkg install bzip2
The following packages will be built and installed:
    bzip2[core]:x86-windows
Starting package 1/1: bzip2:x86-windows
Building package bzip2[core]:x86-windows...
-- Using cached C:/Projects/vcpkg/downloads/bzip2-1.0.6.tar.gz
-- Using source at C:/Projects/vcpkg/buildtrees/bzip2/src/1.0.6-8d81d2ad2b
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Performing CMake integration test
CMake Error at scripts/cmake/vcpkg_test_cmake.cmake:51 (message):
  CMake integration test failed; unable to find_package(BZip2 MODULE
  REQUIRED)
Call Stack (most recent call first):
  ports/bzip2/portfile.cmake:42 (vcpkg_test_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package bzip2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x86-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

c:\Projects\vcpkg>
```

**Comment by Cheney-W** [comment]
@7thTool Thanks for your feedback. This issue has been fixed. I could install boost:x86-windows-static and boost:x64-windows-static successfully with VS 2017 15.9.11. Please reopen a new issue if it is still a problem for you!
