### ISSUE TITLE
[physfs] download fails - main download site is down

### ISSUE THREAD

**Issue by past-due** [Microsoft/vcpkg#5053]
icculus.org has been having uptime issues lately.

Unfortunately, the physfs port does not currently list any mirrors.

> -- Downloading https://icculus.org/physfs/downloads/physfs-3.0.1.tar.bz2...
> -- Downloading https://icculus.org/physfs/downloads/physfs-3.0.1.tar.bz2... Failed. Status: 7;"Couldn't connect to server"
> CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:156 (message):
>      
>       Failed to download file.
>       If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
>       variables to "https://user:password@your-proxy-ip-address:port/".
>       Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
> Call Stack (most recent call first):
>   ports/physfs/portfile.cmake:4 (vcpkg_download_distfile)
>   scripts/ports.cmake:71 (include)
> Error: Building package physfs:x64-osx failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: physfs:x64-osx

**Comment by lucascebertin** [comment]
I found an alternative here:

https://src.fedoraproject.org/lookaside/extras/physfs/physfs-3.0.1.tar.bz2/sha512/ddf3b075ccb506da5e9a1ce96001be402752b9b777c2e816a85d48aff3626ff0886ea43eb07bd300fe3a9f59b9a002f54d822c51d483a4ee94b38378534c1879/

**Comment by LarryIII** [comment]
Looks like this network issue was fixed. I installed physfs sucessfully.
*****************************************
.\vcpkg.exe install physfs
The following packages will be built and installed:
    physfs[core]:x86-windows
Starting package 1/1: physfs:x86-windows
Building package physfs[core]:x86-windows...
-- Downloading https://icculus.org/physfs/downloads/physfs-3.0.1.tar.bz2...
-- Extracting source G:/VCPKG-NoSpace/vcpkg/downloads/physfs-3.0.1.tar.bz2
-- Applying patch physfs.3.0.1.GetUserProfileDirectory.patch
-- Using source at G:/VCPKG-NoSpace/vcpkg/buildtrees/physfs/src/3.0.1-cb85c8c417
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package physfs[core]:x86-windows... done
Installing package physfs[core]:x86-windows...
Installing package physfs[core]:x86-windows... done
Elapsed time for package physfs:x86-windows: 23.71 s

Total elapsed time: 23.71 s
