### ISSUE TITLE
Compile libmysql error on Windows

### ISSUE THREAD

**Issue by joa-quim** [Microsoft/vcpkg#5071]
```
C:\programs\compa_libs\vcpkg>vcpkg install libmysql
The following packages will be built and installed:
    libmysql[core]:x86-windows
Starting package 1/1: libmysql:x86-windows
Building package libmysql[core]:x86-windows...
CMake Error at ports/libmysql/portfile.cmake:10 (message):
  Oracle has dropped support in libmysql for 32-bit Windows.
Call Stack (most recent call first):
  scripts/ports.cmake:71 (include)
```
But this is Win10 64 bits and I told  it nothing to build a 32 bits version (which in fact I would even like to do)

**Comment by Voskrese** [comment]
>   Oracle has dropped support in libmysql for 32-bit Windows.
default x86

>     libmysql[core]:x86-windows

built 

vcpkg install libmysql:x64-windows

**Comment by joa-quim** [comment]
OK, thanks. But I actually found this issue when trying to build ``gdal`` and it failed because it depends on this lib.

**Comment by Voskrese** [comment]
Try to delete these lines, maybe the assembly will be successful

```
if(VCPKG_TARGET_ARCHITECTURE STREQUAL "x86" AND NOT CMAKE_SYSTEM_NAME OR CMAKE_SYSTEM_NAME STREQUAL "WindowsStore")
    message(FATAL_ERROR "Oracle has dropped support in libmysql for 32-bit Windows.")
endif()
```

**Comment by joa-quim** [comment]
Right, I try it latter. Meanwhile I'm waiting that mysql finishes to build but it's taking ages. The same thing happened yesterday when building ``gdal`` it took hours to build (had to remove the mysql dependency for it to build). Don't know why it's building ``icu`` and lots of ``boost`` stuff

```
...
-- Installing: C:/programs/compa_libs/vcpkg/packages/boost-algorithm_x64-windows/share/boost-algorithm/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-algorithm[core]:x64-windows... done
Installing package boost-algorithm[core]:x64-windows...
Installing package boost-algorithm[core]:x64-windows... done
Elapsed time for package boost-algorithm:x64-windows: 1.32 s
Starting package 43/91: icu:x64-windows
Building package icu[core]:x64-windows...
-- Using cached C:/programs/compa_libs/vcpkg/downloads/icu4c-61_1-src.tgz
-- Applying patch C:/programs/compa_libs/vcpkg/ports/icu/disable-escapestr-tool.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/programs/compa_libs/vcpkg/ports/icu/remove-MD-from-configure.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Configuring x64-windows-dbg
-- Configuring x64-windows-dbg done
-- Package x64-windows-rel
```

**Comment by joa-quim** [comment]
Nope, removing those lines just pulls the error further down
```
-- CMAKE_GENERATOR: Ninja
CMake Error at cmake/os/Windows.cmake:56 (MESSAGE):
  32 bit Windows builds are not supported.  Clean the build dir and rebuild
  using -G "Ninja Win64"
Call Stack (most recent call first):
  CMakeLists.txt:238 (INCLUDE)
```
BTW, the ``libmysql`` build took 39 minutes which looks an awful long time for the task.

**Comment by hlysunnaram** [comment]
Changes were made in PR #4413 to allow gdal package to be built with mariadb or without mysql support.
By default, it still use mysql for compatibility but it can be disabled with package feature.

Example:
```
vcpkg install gdal[core]
vcpkg install gdal[core,mysql-libmariadb]
```

**Comment by nicole9456** [comment]
Closed the issue, it already has been fixed in PR #4413 and merged  by commit 38c741f into Microsoft:master on Oct 12, 2018

**Comment by joa-quim** [comment]
It still fails for me
```
C:\programs\compa_libs\vcpkg>vcpkg install gdal
The following packages will be built and installed:
    gdal[core,mysql-libmysql]:x86-windows
  * libmysql[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: libmysql:x86-windows
Building package libmysql[core]:x86-windows...
CMake Error at C:/programs/compa_libs/vcpkg/ports/libmysql/portfile.cmake:10 (message):
  Oracle has dropped support in libmysql for 32-bit Windows.
```

**Comment by joa-quim** [comment]
Yes, but if the use of libmysql (which is still in the GDAL CONTROL file)
breaks a build, than it shouldn't be there at all. Note that GDAL itself
may be a dependency of another project build.

**Comment by hlysunnaram** [comment]
It is possible to explicitly tell the package features you want in the dependencies of an other package if the default behavior is not what you are looking for.

Anyway, you can still create a PR to change the default behavior and remove `mysql-libmysql` feature from the [Default-Features](https://github.com/Microsoft/vcpkg/blob/master/ports/gdal/CONTROL#L5).
`mysql-libmysql` was placed in `Default-Features` to keep previous compatibility but maybe this was not required at all.

**Comment by haifeng2170** [comment]
I also have this problem when tried to install poco[mysql]  or libmysql, the error is 'libmysql and libmariadb are incompatible', anyone encounter this problem?
