### ISSUE TITLE
[freetype] download fails - main download site is down

### ISSUE THREAD

**Issue by past-due** [Microsoft/vcpkg#5072]
> Building package freetype[core]:x86-windows... 
> -- Downloading https://download-mirror.savannah.gnu.org/releases/freetype/freetype-2.8.1.tar.bz2...
> -- Downloading https://download-mirror.savannah.gnu.org/releases/freetype/freetype-2.8.1.tar.bz2... Failed. Status: 7;"Couldn't connect to server"

With no download mirror for the port, installation fails. Will open a new PR.

**Comment by luzpaz** [comment]
Related to https://github.com/Microsoft/vcpkg/issues/4931
