### ISSUE TITLE
libmysql build failed (X64)

### ISSUE THREAD

**Issue by nebsar** [Microsoft/vcpkg#5074]
Error: Building package libmysql:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libmysql:x64-windows
  Vcpkg version: 2018.11.23-nohash

**Comment by Voskrese** [comment]
log?

**Comment by nebsar** [comment]
Checking patch cmake/boost.cmake...
error: while searching for:
  COULD_NOT_FIND_BOOST()?
ENDIF()?
?
IF(NOT BOOST_MINOR_VERSION EQUAL 65)?
  MESSAGE(WARNING "Boost minor version found is ${BOOST_MINOR_VERSION} "?
    "we need 65"?
    )?

error: patch failed: cmake/boost.cmake:280
error: cmake/boost.cmake: patch does not apply


Checking patch cmake/icu.cmake...
error: while searching for:
# install_root is either 'system' or is assumed to be a path.?
#?
MACRO (FIND_ICU install_root)?
  IF("${install_root}" STREQUAL "system")?
    SET(EXTRA_FIND_LIB_ARGS)?
    SET(EXTRA_FIND_INC_ARGS)?
  ELSE()?
    SET(EXTRA_FIND_LIB_ARGS HINTS "${install_root}"?
      PATH_SUFFIXES "lib" "lib64" NO_DEFAULT_PATH)?
    SET(EXTRA_FIND_INC_ARGS HINTS "${install_root}"?
      PATH_SUFFIXES "include"     NO_DEFAULT_PATH)?
  ENDIF()?
?
  FIND_PATH(ICU_INCLUDE_DIR NAMES unicode/regex.h ${EXTRA_FIND_INC_ARGS})?
  IF (NOT ICU_INCLUDE_DIR)?
    MESSAGE(FATAL_ERROR "Cannot find ICU regular expression headers")?
  ENDIF()?
?
  IF(WIN32)?
    SET(ICU_LIBS icuuc icuio icudt icuin)?
  ELSE()?
    SET(ICU_LIBS icuuc icuio icudata icui18n)?
  ENDIF()?
?
  SET(ICU_SYSTEM_LIBRARIES)?
  FOREACH(ICU_LIB ${ICU_LIBS})?
    UNSET(ICU_LIB_PATH CACHE)?
    FIND_LIBRARY(ICU_LIB_PATH NAMES ${ICU_LIB} ${EXTRA_FIND_LIB_ARGS})?
    IF(NOT ICU_LIB_PATH)?
      MESSAGE(FATAL_ERROR "Cannot find the ICU library ${ICU_LIB}")?
    ENDIF()?
    LIST(APPEND ICU_SYSTEM_LIBRARIES ${ICU_LIB_PATH})?
  ENDFOREACH()?
?
  # To do: If we include the path in ICU_INCLUDE_DIR, it leads to GUnit?
  # picking up the wrong regex.h header. And it looks like we don't need it;?
  # at least on Linux, the header gets installed in an OS path anyway.?
  IF(NOT "${install_root}" STREQUAL "system")?
    SET(ICU_INCLUDE_DIRS ${ICU_INCLUDE_DIR})?
  ENDIF()?
?
  SET(ICU_LIBRARIES ${ICU_SYSTEM_LIBRARIES})?
?
  # Needed for version information.?
  SET(ICU_COMMON_DIR ${ICU_INCLUDE_DIR})?
?
ENDMACRO()?
?
MACRO (MYSQL_USE_BUNDLED_ICU)?

error: patch failed: cmake/icu.cmake:40
error: cmake/icu.cmake: patch does not apply
Checking patch cmake/lz4.cmake...
error: while searching for:
?
MACRO (FIND_SYSTEM_LZ4)?
  FIND_PATH(PATH_TO_LZ4 NAMES lz4frame.h)?
  FIND_LIBRARY(LZ4_SYSTEM_LIBRARY NAMES lz4)?
  IF (PATH_TO_LZ4 AND LZ4_SYSTEM_LIBRARY)?
    SET(SYSTEM_LZ4_FOUND 1)?
    INCLUDE_DIRECTORIES(SYSTEM ${PATH_TO_LZ4})?

error: patch failed: cmake/lz4.cmake:25
error: cmake/lz4.cmake: patch does not apply
Checking patch cmake/lzma.cmake...
error: while searching for:
# bundled is the default?
?
MACRO (FIND_SYSTEM_LZMA)?
  FIND_PATH(PATH_TO_LZMA NAMES lzma/lzma.h)?
  FIND_LIBRARY(LZMA_SYSTEM_LIBRARY NAMES lzma)?
  IF (PATH_TO_LZMA AND LZMA_SYSTEM_LIBRARY)?
    SET(SYSTEM_LZMA_FOUND 1)?
    SET(LZMA_INCLUDE_DIR ${PATH_TO_LZMA})?
    SET(LZMA_LIBRARY ${LZMA_SYSTEM_LIBRARY})?
    MESSAGE(STATUS "LZMA_INCLUDE_DIR ${LZMA_INCLUDE_DIR}")?
    MESSAGE(STATUS "LZMA_LIBRARY ${LZMA_LIBRARY}")?
  ENDIF()?
ENDMACRO()?
?
MACRO (MYSQL_USE_BUNDLED_LZMA)?

error: patch failed: cmake/lzma.cmake:24
error: cmake/lzma.cmake: patch does not apply
Checking patch cmake/ssl.cmake...
error: while searching for:
# Provides the following configure options:?
# WITH_SSL=[yes|bundled|system|<path/to/custom/installation>]?
MACRO (MYSQL_CHECK_SSL)?
  IF(NOT WITH_SSL)?
    IF(WIN32)?
      CHANGE_SSL_SETTINGS("bundled")?

error: patch failed: cmake/ssl.cmake:104
error: cmake/ssl.cmake: patch does not apply
Checking patch cmake/zlib.cmake...
error: while searching for:
  IF(WITH_ZLIB STREQUAL "bundled")?
    MYSQL_USE_BUNDLED_ZLIB()?
  ELSE()?
    SET(ZLIB_FIND_QUIETLY TRUE)?
    INCLUDE(FindZLIB)?
    IF(ZLIB_FOUND)?
     INCLUDE(CheckFunctionExists)?
      SET(CMAKE_REQUIRED_LIBRARIES z)?
      CHECK_FUNCTION_EXISTS(crc32 HAVE_CRC32)?
      CHECK_FUNCTION_EXISTS(compressBound HAVE_COMPRESSBOUND)?
      CHECK_FUNCTION_EXISTS(deflateBound HAVE_DEFLATEBOUND)?
      SET(CMAKE_REQUIRED_LIBRARIES)?
      IF(HAVE_CRC32 AND HAVE_COMPRESSBOUND AND HAVE_DEFLATEBOUND)?
        SET(ZLIB_LIBRARY ${ZLIB_LIBRARIES} CACHE INTERNAL "System zlib library")?
        SET(WITH_ZLIB "system" CACHE STRING?
          "Which zlib to use (possible values are 'bundled' or 'system')")?
        SET(ZLIB_SOURCES "")?
      ELSE()?
        SET(ZLIB_FOUND FALSE CACHE INTERNAL "Zlib found but not usable")?
        MESSAGE(STATUS "system zlib found but not usable")?
      ENDIF()?
    ENDIF()?
    IF(NOT ZLIB_FOUND)?
      MYSQL_USE_BUNDLED_ZLIB()?
    ENDIF()?
  ENDIF()?
ENDMACRO()?

error: patch failed: cmake/zlib.cmake:51
error: cmake/zlib.cmake: patch does not apply

**Comment by Cheney-W** [comment]
@nebsar Thanks for your feedback. I could install libmysql:x64-windows successfully with VS 2017 15.9.11. Please reopen a new issue if it is still a problem for you!
