### ISSUE TITLE
new package request: libgphoto2 

### ISSUE THREAD

**Issue by fujie317** [microsoft/vcpkg#5075]
It would be nice to have camera SDK package libgphoto2 for Windows. Appreciate it if anybody can pull this off.

**Comment by Voskrese** [comment]
link?

**Comment by edmBernard** [comment]
https://sourceforge.net/projects/gphoto/files/libgphoto/2.5.22/

**Comment by Voskrese** [comment]
only mingw
https://github.com/gphoto/gphoto2/issues/85#issuecomment-327556140

**Comment by vividos** [comment]
I tried this a while back, using Visual Studio and a self written compat library:
https://github.com/vividos/libgphoto2/releases
I can't say if I done everything right, as I never used the API very much. Also only PTP2 and Canon camlibs were ported.

I recently tried another approach, which you can find here:
https://github.com/vividos/RemotePhotoTool/tree/master/build
You just need the .cmd file and the msvc folder. The .cmd file downloads the latest release, copies over the msvc folder and starts a Visual Studio build. Again, only contains the base libraries and the PTP2 and Canon camlibs, but porting other camlibs should be easy.

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!

**Comment by mms-** [comment]
Makes sense for Microsoft to invest and make libgphoto2 work with Windows, since these APIs in Windows itself haven't been updated in decades. It's another open source project that can be contributed to.
