### ISSUE TITLE
qt-location not included

### ISSUE THREAD

**Issue by craigrbarnes** [microsoft/vcpkg#5076]
The Qt5 library QtLocation is not built as part of Qt5.

**Comment by TheScarfix** [comment]
working on a pull request. Will open it as soon as #4991 is merged.

**Comment by TheScarfix** [comment]
Is included in #5293

**Comment by NancyLi1013** [comment]
@TheScarfix, thanks for your PR. @craigrbarnes, qt5-location has added to the vcpkg list, please try to use it.
