### ISSUE TITLE
Feature request: resume vcpkg install

### ISSUE THREAD

**Issue by s-martin** [microsoft/vcpkg#5078]
I had the issue, that for installing LLVM with `vcpkg install llvm` there wasn't enough drive space available.

So I rerun the command a couple of times (because I didn't check in the log what was the real reason for the failed install. Unfortunately vcpkg does a clean build when installing. For large libraries as LLVM this is really annoying, because building takes (at least on my machine) over 2 hours.

I think it would be useful to have at least a switch like `--no-clean-build` to not rebuild hundreds of library files, which were built seamlessly until the error occurred.

**Comment by PhoebeHui** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.

**Comment by jvbsl** [comment]
Imho this is still an issue. Building is already slow as it is but then if it fails and can be patched, but the complete compilation just to get to the next error takes a whole lot of time. just building the already downloaded and extracted source with a portion already built would speed up troubleshooting by a lot.
