### ISSUE TITLE
Port request: LLVM

### ISSUE THREAD

**Issue by studoot** [Microsoft/vcpkg#508]
The addition of a port for [LLVM Core](http://llvm.org/docs/CMake.html) would be splendid - personally I'm not too bothered about the other projects (LLVM, LLDB etc), but other people might be?

**Comment by Remotion** [comment]
Please do not forge about Clang too. 

And may be even Cling ?

**Comment by Voskrese** [comment]
C:\Program Files (x86)\**Microsoft Visual Studio\2017\BuildTools**\VC\Tools\ClangC2\14.10.25903\bin\HostX64/\X86 \**clang.exe**
arm  clang.exe  x64  x86

C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\ClangC2\14.10.25903\bin\HostX64>clang.exe --version
clang with Microsoft CodeGen version 3.8.0
Provided as - is without support
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\ClangC2\14.10.25903\bin\HostX64

**Comment by Mixaill** [comment]
fixed by #1388 @ras0219-msft

**Comment by kasper3** [comment]
OP wanted the LLDB package, could it be included as well?
