### ISSUE TITLE
Document how (if) to distribute a project that uses vcpkg, especially for Windows builds

### ISSUE THREAD

**Issue by voltagex** [microsoft/vcpkg#5081]
Hi,
I've just been working out how to build qBittorrent from source on Windows using vcpkg to help with the dependencies. It looks like it's as simple as adding `set(CMAKE_TOOLCHAIN_FILE "c:/git/vcpkg/scripts/buildsystems/vcpkg.cmake")` to the top of `CMakeLists.txt` but the issue there is then it's hardcoded to my paths and can't be submitted as a patch to the project.

Is there a recommended way for upstreams to use/recommend vcpkg without requring developers to make manual changes per machine?

I wonder if you could get a find_vcpkg included in CMake for this kind of purpose...

I understand if this is out of scope (but that should be documented, too).

**Comment by myd7349** [comment]
https://github.com/Microsoft/vcpkg/issues/5104

**Comment by stuaxo** [comment]
Ohh... definitely +1 on find_vcpkg is this something that would need to be requested against CMake itself ?

**Comment by PhoebeHui** [comment]
@voltagex, thanks for posting this issue!

Document has been added to vcpkg, see https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#using-an-environment-variable-instead-of-a-command-line-option

**Comment by stuaxo** [comment]
Great this should make it a easier to integrate all sorts of things.

**Comment by voltagex** [comment]
Thanks @PhoebeHui & team.
