### ISSUE TITLE
Support for more platforms!

### ISSUE THREAD

**Issue by mcandre** [microsoft/vcpkg#5084]
I would like to use one common package manager for my C/C++ libraries, across many different systems. It's awesome that vcpkg supports macOS, Windows, and Linux! Could we also test support for some more obscure systems like BSD's, Illumos, MINIX, and Haiku?

**Comment by JackBoosY** [comment]
We need more contributors to write the related toolchain code first.

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
