### ISSUE TITLE
Please update uriparser to 0.9.1, includes security fixes

### ISSUE THREAD

**Issue by hartwork** [Microsoft/vcpkg#5086]
Hi!

Just a quick heads up that [uriparser 0.9.1](https://github.com/uriparser/uriparser/releases/tag/uriparser-0.9.1) with security fixes has been released.

Thanks for updating!

**Comment by ras0219-msft** [comment]
Fixed by #5094, thanks!

**Comment by hartwork** [comment]
Thank you!
