### ISSUE TITLE
Unable to build icu:x64-windows:-cross-build option specified - please supply the path to an executable ICU's build root

### ISSUE THREAD

**Issue by jimmyleeking** [Microsoft/vcpkg#5090]
I stucked in building icu,that my powershell prompt :

```
PS E:\GitDoc\vcpkg> .\vcpkg.exe install icu:x64-windows
The following packages will be built and installed:
    icu[core]:x64-windows
Starting package 1/1: icu:x64-windows
Building package icu[core]:x64-windows...
-- Using cached E:/GitDoc/vcpkg/downloads/icu4c-61_1-src.tgz
-- Extracting source E:/GitDoc/vcpkg/downloads/icu4c-61_1-src.tgz
-- Applying patch E:/GitDoc/vcpkg/ports/icu/disable-escapestr-tool.patch
-- Applying patch E:/GitDoc/vcpkg/ports/icu/remove-MD-from-configure.patch
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: E:/GitDoc/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe;--noprofile;--norc;-c;E:/GitDoc/vcpkg/buildtrees/icu/src/icu-61.1/icu/source/runConfigureICU MSYS/MSVC --disable-samples --disable-tests --disable-static --enable-shared --host=i686-pc-mingw32 --enable-debug --disable-release --prefix=E:/GitDoc/vcpkg/packages/icu_x64-windows/debug
    Working Directory: E:/GitDoc/vcpkg/buildtrees/icu/x64-windows-dbg
    See logs for more information:
      E:\GitDoc\vcpkg\buildtrees\icu\configure-x64-windows-dbg-out.log
      E:\GitDoc\vcpkg\buildtrees\icu\configure-x64-windows-dbg-err.log

Call Stack (most recent call first):
  ports/icu/portfile.cmake:116 (vcpkg_execute_required_process)
  scripts/ports.cmake:71 (include)


Error: Building package icu:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x64-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

```

and ` configure-x64-windows-dbg-out.log`  error content:

```
configure: error: Error! Cross compiling but no --with-cross-build option specified - please supply the path to an executable ICU's build root

```

[configure-x64-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/2731312/configure-x64-windows-rel-out.log)

[msys-pacman-x64-windows-err.log](https://github.com/Microsoft/vcpkg/files/2731313/msys-pacman-x64-windows-err.log)
[msys-pacman-x64-windows-out.log](https://github.com/Microsoft/vcpkg/files/2731314/msys-pacman-x64-windows-out.log)
[patch-x64-windows-0-err.log](https://github.com/Microsoft/vcpkg/files/2731315/patch-x64-windows-0-err.log)

[patch-x64-windows-1-err.log](https://github.com/Microsoft/vcpkg/files/2731316/patch-x64-windows-1-err.log)

[configure-x64-windows-dbg-err.log](https://github.com/Microsoft/vcpkg/files/2731317/configure-x64-windows-dbg-err.log)
[configure-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2731318/configure-x64-windows-dbg-out.log)

**Comment by Voskrese** [comment]
```
checking for i686-pc-mingw32-pkg-config... no
checking for pkg-config... no
checking for ICULEHB... no
checking how to run the C preprocessor... cl -E
checking for a BSD-compatible install... /usr/bin/install -c
checking for gmake... no
checking for gnumake... no
E:/GitDoc/vcpkg/buildtrees/icu/src/icu-61.1/icu/source/runConfigureICU: ./configure failed
```

gmake = make

`mklink gmake.exe make.exe` or `cp make.exe gmake.exe`

?

**Comment by jimmyleeking** [comment]
Thanks!

but I tried, the same error did happened again.

```
checking for pkg-config... no
checking for ICULEHB... no
checking how to run the C preprocessor... cl -E
checking for a BSD-compatible install... /usr/bin/install -c
checking for gmake... /usr/bin/gmake
E:/GitDoc/vcpkg/buildtrees/icu/src/icu-61.1/icu/source/runConfigureICU: ./configure failed

```

[msys-pacman-x64-windows-err.log](https://github.com/Microsoft/vcpkg/files/2731709/msys-pacman-x64-windows-err.log)
[msys-pacman-x64-windows-out.log](https://github.com/Microsoft/vcpkg/files/2731710/msys-pacman-x64-windows-out.log)
[patch-x64-windows-0-err.log](https://github.com/Microsoft/vcpkg/files/2731711/patch-x64-windows-0-err.log)

[patch-x64-windows-1-err.log](https://github.com/Microsoft/vcpkg/files/2731712/patch-x64-windows-1-err.log)

[configure-x64-windows-dbg-err.log](https://github.com/Microsoft/vcpkg/files/2731713/configure-x64-windows-dbg-err.log)
[configure-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2731714/configure-x64-windows-dbg-out.log)

[configure-x64-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/2731715/configure-x64-windows-rel-out.log)

**Comment by jimmyleeking** [comment]
> ```
> checking for i686-pc-mingw32-pkg-config... no
> checking for pkg-config... no
> checking for ICULEHB... no
> checking how to run the C preprocessor... cl -E
> checking for a BSD-compatible install... /usr/bin/install -c
> checking for gmake... no
> checking for gnumake... no
> E:/GitDoc/vcpkg/buildtrees/icu/src/icu-61.1/icu/source/runConfigureICU: ./configure failed
> ```
> gmake = make
> 
> `mklink gmake.exe make.exe` or `cp make.exe gmake.exe`
> 
> ?

**Comment by jimmyleeking** [comment]
> ```
> checking for i686-pc-mingw32-pkg-config... no
> checking for pkg-config... no
> checking for ICULEHB... no
> checking how to run the C preprocessor... cl -E
> checking for a BSD-compatible install... /usr/bin/install -c
> checking for gmake... no
> checking for gnumake... no
> E:/GitDoc/vcpkg/buildtrees/icu/src/icu-61.1/icu/source/runConfigureICU: ./configure failed
> ```
> gmake = make
> 
> `mklink gmake.exe make.exe` or `cp make.exe gmake.exe`
> 
> ?



> ```
> checking for i686-pc-mingw32-pkg-config... no
> checking for pkg-config... no
> checking for ICULEHB... no
> checking how to run the C preprocessor... cl -E
> checking for a BSD-compatible install... /usr/bin/install -c
> checking for gmake... no
> checking for gnumake... no
> E:/GitDoc/vcpkg/buildtrees/icu/src/icu-61.1/icu/source/runConfigureICU: ./configure failed
> ```
> gmake = make
> 
> `mklink gmake.exe make.exe` or `cp make.exe gmake.exe`
> 
> ?

Thanks!

but I tried, the same error did happened again.

```
checking for pkg-config... no
checking for ICULEHB... no
checking how to run the C preprocessor... cl -E
checking for a BSD-compatible install... /usr/bin/install -c
checking for gmake... /usr/bin/gmake
E:/GitDoc/vcpkg/buildtrees/icu/src/icu-61.1/icu/source/runConfigureICU: ./configure failed

```

[configure-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2731718/configure-x64-windows-dbg-out.log)

[configure-x64-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/2731719/configure-x64-windows-rel-out.log)
[configure-x64-windows-dbg-err.log](https://github.com/Microsoft/vcpkg/files/2731720/configure-x64-windows-dbg-err.log)

**Comment by Voskrese** [comment]
**reinstall msys2**

delete folder E:/GitDoc/vcpkg/downloads/tools/msys2

**Comment by jimmyleeking** [comment]
It's same result.now I try to build only release version,that is success.

Edit triplet for x64-windows

```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_BUILD_TYPE release)

```

Powershell log:
```
PS E:\GitDoc\vcpkg> .\vcpkg.exe install icu:x64-windows
The following packages will be built and installed:
    icu[core]:x64-windows
Starting package 1/1: icu:x64-windows
Building package icu[core]:x64-windows...
-- Using cached E:/GitDoc/vcpkg/downloads/icu4c-61_1-src.tgz
-- Applying patch E:/GitDoc/vcpkg/ports/icu/disable-escapestr-tool.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch E:/GitDoc/vcpkg/ports/icu/remove-MD-from-configure.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Package x64-windows-rel
-- Package x64-windows-rel done
-- Warning: Could not find a matching pdb file for:
    E:/GitDoc/vcpkg/packages/icu_x64-windows/bin/icudt61.dll

-- Performing post-build validation
-- Performing post-build validation done
Building package icu[core]:x64-windows... done
Installing package icu[core]:x64-windows...
Installing package icu[core]:x64-windows... done
Elapsed time for package icu:x64-windows: 11.75 min

Total elapsed time: 11.75 min
```

maybe it's some wrong configure for makefile's configuration or source code ?,I still no idea how to disable cross-

**Comment by Cheney-W** [comment]
@jimmyleeking Thanks for your feedback. I could install icu:x64-windows successfully with VS 2017 15.9.11. Please reopen a new issue if it is still a problem for you!

**Comment by soroush-rabiei** [comment]
I have same problem:

```configure: error: Error! Cross compiling but no --with-cross-build option specified - please supply the path to an executable ICU's build root```

**vcpkg version**: 2020.02.04-nohash
**msvc version**: 14.0 (VS 2015)

[Uploading configure-x64-windows-dbg-err.log…]()
