### ISSUE TITLE
boost-locale:arm-windows fails to install when trying to install  boost-log, boost-program-options for arm-windows

### ISSUE THREAD

**Issue by cirvine-MSFT** [microsoft/vcpkg#5103]
PS X:\acdc> python .\build\scripts\build.py --clean --install-deps --arch arm
Starting Build
Target OS: Windows
Flavor: windows-arm-msvc-debug
Arch: arm
Config: debug
CMake Generator: Visual Studio 15 2017
Compiler: msvc
Clean: True
Source Path: X:\src
Bin Path: X:\bin\windows-arm-msvc-debug
Applied user-wide integration for this vcpkg root.
---- vcpkg output starts here ----
All MSBuild C++ projects can now #include any installed libraries.
Linking will be handled automatically.
Installing new libraries will make them instantly available.

CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=X:/acdc/build/vcpkg/scripts/buildsystems/vcpkg.cmake"
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
The following packages are already installed:
    boost-build[core]:x86-windows
The following packages will be built and installed:
  * boost-align[core]:arm-windows
  * boost-asio[core]:arm-windows
  * boost-context[core]:arm-windows
  * boost-coroutine[core]:arm-windows
  * boost-date-time[core]:arm-windows
  * boost-dynamic-bitset[core]:arm-windows
  * boost-filesystem[core]:arm-windows
  * boost-interprocess[core]:arm-windows
  * boost-locale[core]:arm-windows
    boost-log[core]:arm-windows
  * boost-multi-index[core]:arm-windows
  * boost-parameter[core]:arm-windows
  * boost-phoenix[core]:arm-windows
  * boost-pool[core]:arm-windows
    boost-program-options[core]:arm-windows
  * boost-property-tree[core]:arm-windows
  * boost-proto[core]:arm-windows
  * boost-random[core]:arm-windows
  * boost-serialization[core]:arm-windows
  * boost-spirit[core]:arm-windows
  * boost-tokenizer[core]:arm-windows
  * boost-tti[core]:arm-windows
  * boost-variant[core]:arm-windows
  * boost-xpressive[core]:arm-windows
  * brotli[core]:arm-windows
    cpprestsdk[brotli,core,default-features,websockets]:arm-windows
  * openssl[core]:arm-windows
  * openssl-windows[core]:arm-windows
  * websocketpp[core]:arm-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/30: boost-locale:arm-windows
Building package boost-locale[core]:arm-windows...
-- Using cached X:/acdc/build/vcpkg/downloads/boostorg-locale-boost-1.68.0.tar.gz
-- Using source at X:/acdc/build/vcpkg/buildtrees/boost-locale/src/ost-1.68.0-590dc9a6a1
-- Building arm-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: X:/acdc/build/vcpkg/installed/x86-windows/tools/boost-build/b2.exe;--stagedir=X:/acdc/build/vcpkg/buildtrees/boost-locale/arm-windows-rel/stage;--build-dir=X:/acdc/build/vcpkg/buildtrees/boost-locale/arm-windows-rel;--user-config=X:/acdc/build/vcpkg/buildtrees/boost-locale/arm-windows-rel/user-config.jam;boost.locale.iconv=off;boost.locale.posix=off;/boost/locale//boost_locale;boost.locale.icu=off;-j12;--debug-configuration;--debug-building;--debug-generators;--disable-icu;--ignore-site-config;--hash;-q;-sZLIB_INCLUDE="X:/acdc/build/vcpkg/installed/arm-windows/include";-sBZIP2_INCLUDE="X:/acdc/build/vcpkg/installed/arm-windows/include";threading=multi;threadapi=win32;runtime-link=shared;link=shared;address-model=32;architecture=arm;toolset=msvc-14.1;-sZLIB_BINARY=zlib;-sZLIB_LIBPATH="X:/acdc/build/vcpkg/installed/arm-windows/lib";-sBZIP2_BINARY=bz2;-sBZIP2_LIBPATH="X:/acdc/build/vcpkg/installed/arm-windows/lib";variant=release;debug-symbols=on
    Working Directory: X:/acdc/build/vcpkg/buildtrees/boost-locale/src/ost-1.68.0-590dc9a6a1/build
    See logs for more information:
      X:\acdc\build\vcpkg\buildtrees\boost-locale\build-arm-windows-rel-out.log

Call Stack (most recent call first):
  installed/arm-windows/share/boost-build/boost-modular-build.cmake:270 (vcpkg_execute_required_process)
  ports/boost-locale/portfile.cmake:20 (boost_modular_build)
  scripts/ports.cmake:71 (include)

Error: Building package boost-locale:arm-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-locale:arm-windows
  Vcpkg version: 2018.11.23-nohash
[build-arm-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/2737928/build-arm-windows-rel-out.log)

[build-arm-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/2737937/build-arm-windows-rel-out.log)

[build-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2737938/build-x64-windows-dbg-out.log)

[build-x64-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/2737939/build-x64-windows-rel-out.log)

[build-x86-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2737940/build-x86-windows-dbg-out.log)

[build-x86-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/2737941/build-x86-windows-rel-out.log)

**Comment by PhoebeHui** [comment]
@cirvine-MSFT, boost build tool start to support to build with arm from 1_73, please try to get latest source and try again.

I have double confrimed, it built successfully for me, please reopen this issue if it still be a problem for you.

PS F:\VCPKG\boost_173\vcpkg> ./vcpkg install boost-locale:arm-windows
Computing installation plan...
The following packages will be built and installed:
    boost-locale[core]:arm-windows
Starting package 1/1: boost-locale:arm-windows
Building package boost-locale[core]:arm-windows...
-- Using community triplet arm-windows. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: F:\VCPKG\boost_173\vcpkg\triplets\community\arm-windows.cmake
-- Using cached F:/VCPKG/boost_173/vcpkg/downloads/boostorg-locale-boost-1.73.0.tar.gz
-- Extracting source F:/VCPKG/boost_173/vcpkg/downloads/boostorg-locale-boost-1.73.0.tar.gz
-- Applying patch 0001-Fix-boost-ICU-support.patch
-- Using source at F:/VCPKG/boost_173/vcpkg/buildtrees/boost-locale/src/ost-1.73.0-3a88fc7440
-- Including F:/VCPKG/boost_173/vcpkg/ports/boost-locale/b2-options.cmake
-- Building arm-windows-rel
-- Building arm-windows-rel done
-- Building arm-windows-dbg
-- Building arm-windows-dbg done
-- Packaging arm-windows-rel
-- Packaging arm-windows-rel done
-- Packaging arm-windows-dbg
-- Packaging arm-windows-dbg done
-- Packaging headers
-- Packaging headers done
-- Using cached F:/VCPKG/boost_173/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: F:/VCPKG/boost_173/vcpkg/packages/boost-locale_arm-windows/share/boost-locale/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-locale[core]:arm-windows... done
Installing package boost-locale[core]:arm-windows...
Installing package boost-locale[core]:arm-windows... done
Elapsed time for package boost-locale:arm-windows: 28.39 s
