### ISSUE TITLE
CmakeSettings example uses absolute path ?

### ISSUE THREAD

**Issue by stuaxo** [microsoft/vcpkg#5104]
I'm pretty new to C++ and Windows dev ... from what I've seen CMakeSettings.json should be in git.

The [example here](https://github.com/Microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md#cmake-toolchain-file) adds a path in ```D:\\src\\vcpkg\\....\\vcpkg.cmake```.

Is there any way this could be somewhere under the user profile ?
I can't expect other users of my code to have the same drive mappings as I do, even if I do move it from ```D:\```.

Or should I add a copy vcpkg.cmake somewhere in my own source repo ?

**Comment by myd7349** [comment]
An alternative method:

Create a new environment variable named `VCPKG_ROOT` and assign the root dir of `vcpkg` to it. Then, you may write your setting file like this: https://github.com/myd7349/Ongoing-Study/blob/master/cpp/CMake/vcpkg_cmake_toolchain_demo/CMakeSettings.json

You can also specify the toolchain file in CMakeLists.txt: https://github.com/myd7349/Ongoing-Study/blob/master/cpp/CMake/hello_qt/CMakeLists.txt

**Comment by stuaxo** [comment]
It would be great if VCPKG_ROOT (or more in line with other tools VCPKG_HOME) was a standard part of VC_PKG.

In this way, it would be straightforward to have something like pythons virtualenv, just by setting the environment variable to different paths.

**Comment by PhoebeHui** [comment]
@stuaxo, thank you for posting this issue!
 Document has been added to vcpkg, see https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#using-an-environment-variable-instead-of-a-command-line-option
