### ISSUE TITLE
VTK dlls are placed in tools instead of bin

### ISSUE THREAD

**Issue by at-2500** [Microsoft/vcpkg#5109]
I found this problem on Windows 10, but it does apply to all OSs supported by vcpkg.

## Problem Description

In VTKs [`portfile.cmake`](../tree/master/ports/vtk/portfile.cmake) the cmake variable `VTK_INSTALL_RUNTIME_DIR` is set to `tools` instead of `bin`.
This results in the VTK DLLs being installed into `vcpkg/installed/x64-windows/tools` instead of `vcpkg/installed/x64-windows/bin`.
In turn, this means that [`applocal.ps1`](../tree/master/scripts/buildsystems/msbuild/applocal.ps1) on Windows will **silently** fail to copy those DLLs into the build folder after the build has finished.

## How to reproduce

1. Run `vcpkg install vtk:x64-windows` or any other target triplet on Windows or on any other OS.
2. Check `vcpkg/installed/x64-windows/bin` folder: No VTK DLLs.
3. Check `vcpkg/installed/x64-windows/tools` folder: There are the VTK DLLs.
4. Build any cmake project that depends on VTK using vcpkg's VTK linking dynamically: No DLLs will be placed in the build folder after building the project.

## Proposed Fix

My proposed fixes would include
1. Changing the `VTK_INSTALL_RUNTIME_DIR` to `bin`
2. Now, the build will fail because `vtkEncodeString-8.1.exe` and `vtkHashSource-8.1.exe` are placed in bin. Those tools are references in the VTK cmake targets file as supposed to be in `vcpkg/installed/x64-windows/tool/vtk/*.exe`, to where they need to get moved.
3. Improving `applocal.ps1` so that it doesn't fail silently if it cannot find dlls required to run the exe/use the dll.

The fix for the VTK package is in MR #5150.

**Comment by luzpaz** [comment]
This fix seems to fix #5069
