### ISSUE TITLE
[Request] Local repository

### ISSUE THREAD

**Issue by soroshsabz** [microsoft/vcpkg#5119]
ITNOA

Hi, I think if vcpkg having a mirroring procedures and capability, then we can use all packages in vcpkg in large company with LAN speed, and without needed to internet.

I think it is cool features.

I think vcpkg must be provide local server (LAN access) for satisfy this requirement. and vcpkg command must be discover local server and install from that if available. like nuget and etc...

Thx

**Comment by soroshsabz** [comment]
@PhoebeHui I think it is vcpkg-feature not port feature

thanks :)

**Comment by soroshsabz** [comment]
I think it is very important feature for production use and for large scale software development compony

@PhoebeHui  any plan for this feature?

thanks :)

**Comment by PhoebeHui** [comment]
@soroshsabz , yes, it's a vcpkg feature. thanks for pointing out this! 

Currently we suggest a workaround to user, it should work. 
1. Download the source code with a web browser from: <the source address>.
2. Save it inside <path_to_vcpkg>/downloads/.
3. Then try to install the port again.

We didn't have a final plan for this now, hopefully we could address it in future.

**Comment by soroshsabz** [comment]
@PhoebeHui Did you think Package Federation point in [vcpkg roadmap](https://github.com/microsoft/vcpkg/wiki/Roadmap) could resolve this requirement?

**Comment by PhoebeHui** [comment]
@soroshsabz, we have a good start for it now, see PR https://github.com/microsoft/vcpkg/pull/12532
