### ISSUE TITLE
Deal with max-path

### ISSUE THREAD

**Issue by alexkaratarakis** [microsoft/vcpkg#512]
What can `vcpkg` do to mitigate max-path issues?

**Comment by alexkaratarakis** [comment]
Related: #426

**Comment by MikeGitb** [comment]
Just to clarify: Is this still an issue on Windows 10? Afaik max_path was removed there.

**Comment by alexkaratarakis** [comment]
If you are referring to [this](https://mspoweruser.com/ntfs-260-character-windows-10/), then it may help, but it is not enabled by default and we haven't tested it in `vcpkg` to verify the behavior. 

I would say it is still relevant even for windows 10.

**Comment by MikeGitb** [comment]
That is really disappointing.

**Comment by LilyWangL** [comment]
This issue hasn’t been updated in two year, if it is still an issue, please reopen.
