### ISSUE TITLE
[Request] Integrate with OneGet

### ISSUE THREAD

**Issue by soroshsabz** [microsoft/vcpkg#5120]
ITNOA

Hi,

I think it is good idea to integrate vcpkg with [OneGet](https://github.com/OneGet/oneget) and capable to be PackageManagementProvider in OneGet architecture model.

In this sencario all developers can use package management command in powershell like `Install-Package` or many other commands. and feel like dot net developer that can be used nuget in powershell.

I think in this can you can verily say vcpkg is integrate with powershell. I think the same and consistent spirit with all package management in windows is very important as a user experience. However, it is entirely at the discretion of developer to chose it or using legacy form.

**Comment by PhoebeHui** [comment]
@soroshsabz, we're happy to answer any questions we can to support this effort, but for now we'd prefer to support you or other contributors than to take ownership ourselves. None of our core team is very familiar with oneget, so we feel you'll do a much better job than we could! Please reopen or create a new issue if you have any questions..

**Comment by soroshsabz** [comment]
related to https://github.com/dotnet/sdk/issues/18053#issue-910300340

**Comment by soroshsabz** [comment]
related to https://github.com/microsoft/winget-cli/issues/674#issue-776023590

**Comment by soroshsabz** [comment]
related to https://github.com/microsoft/winget-cli/issues/221#issue-621305863

**Comment by ethanbergstrom** [comment]
@soroshsabz I have a basic OneGet provider for OneGet out on PowerShell gallery, though to be honest, with present state of how difficult it is to get WinGet to even install correctly on Windows Server, I don't plan on iterating on it until installing WinGet itself is easier.

**Comment by soroshsabz** [comment]
@ethanbergstrom  your package is great and I hope to add another [winget](https://github/microsoft/winget) feature to your package, but I think this issue is about `vcpkg` not `winget`

thanks again for sharing :)

**Comment by PhoebeHui** [comment]
Unfortunately, we can’t reopen this issue until a PR is opened, please consider making a pull request!

**Comment by soroshsabz** [comment]
@PhoebeHui I think with [PowerShell Crescendo](https://learn.microsoft.com/en-us/powershell/utility-modules/crescendo/overview?view=ps-modules) wrapper, we can provide a fast solution for PowerShell friendly CLI, and then integrate with OneGet

thanks

**Comment by soroshsabz** [comment]
I hope to every overhaul to CLI (such as https://github.com/microsoft/vcpkg-tool/pull/864), make little closer to PowerShell friendly CLI
