### ISSUE TITLE
Contains invalid characters. Only alphanumeric lowercase ASCII characters and dashes are allowed

### ISSUE THREAD

**Issue by lmj01** [Microsoft/vcpkg#5128]
PS H:\vcpkg> .\vcpkg.exe install llvm:x64-windows
Failed at [h:\vcpkg\toolsrc\src\vcpkg\packagespec.cpp(37)] with message:
Contains invalid characters. Only alphanumeric lowercase ASCII characters and dashes are allowed
PS H:\vcpkg>

in #4662 , occur the same problem, but the solution is not for this

**Comment by Cheney-W** [comment]
@lmj01 Thanks for your feedback. I could install llvm:x64-windows successfully with VS 2017 15.9.11. Please reopen a new issue if it is still a problem for you!
