### ISSUE TITLE
[qt5] x86-windows-static build failure

### ISSUE THREAD

**Issue by sdcb** [microsoft/vcpkg#513]
I'm using Windows 10.0.14393, my machine is using the zh-CN locale, when I run: "vcpkg install qt5:x86-windows-static", I got a failure (expect succeed), please view attachments for more details.

[ConsoleOutput.txt](https://github.com/Microsoft/vcpkg/files/697910/ConsoleOutput.txt)
[install-x86-windows-static-err.txt](https://github.com/Microsoft/vcpkg/files/697912/install-x86-windows-static-err.txt)
[install-x86-windows-static-out.txt](https://github.com/Microsoft/vcpkg/files/697914/install-x86-windows-static-out.txt)

I think the failure maybe caused by libpq (as install-x86-windows-static-out.log says)

**Comment by bagong** [comment]
Same for qt5:x64-windows-static

For programs that depend on Qt this devaluates the entire line of static packages, because using dynamically linked Qt wont easily allow to use statically packages compiled with /MT

**Comment by ras0219-msft** [comment]
Confirmed to still reproduce in latest qt5 port (5.8-1).

**Comment by Retik** [comment]
Still present for qt5:x64-windows-static. 

[config-x64-windows-static-rel-out.txt](https://github.com/Microsoft/vcpkg/files/1089913/config-x64-windows-static-rel-out.txt)
[config-x64-windows-static-rel-err.txt](https://github.com/Microsoft/vcpkg/files/1089914/config-x64-windows-static-rel-err.txt)

**Comment by KindDragon** [comment]
Maybe force Qt to build as the dynamic library, until we fix this?

**Comment by bagong** [comment]
It would be nice to update qt to 5.9.1 which was released today. It's a major task mainly, I think, because build time is so crazily long. Maybe it could be done if people work together? I think effort should go into that challenge, and there either fix static or add that fake static option...

**Comment by Retik** [comment]
The problem is just with configuration and dependency resolution. I don't think it would be hard to fix if somebody knew what they were doing.

**Comment by oldmud0** [comment]
I unfortunately have the same problem.

**Comment by ras0219-msft** [comment]
In b3363294 I've added a "fail fast" error message to at least save new users the pain of building for 20+ minutes just to have it fail at the end.

**Comment by oldmud0** [comment]
That is very disappointing. I have tried to convince my the leader of the GPLv3 project I contribute to, to stop using static builds, but he does it anyway for end-user convenience and now wants me to do it for him. Now I have no choice but to confront him on it, or switch back to manual builds.

**Comment by JackBoosY** [comment]
Hi @sdcb, thanks for reporting this issue.
Since qt has been upgrade to 5.12.4, we fixed this issue. Please update vcpkg and rebuild qt5.

Thanks.
