### ISSUE TITLE
Update gdal to 2.4.0

### ISSUE THREAD

**Issue by luzpaz** [Microsoft/vcpkg#5132]
https://github.com/Microsoft/vcpkg/tree/master/ports/gdal
https://trac.osgeo.org/gdal/wiki/Release/2.4.0-News

**Comment by NancyLi1013** [comment]
@luzpaz ,this PR has been merged to the master and gdal has been updated to the latest version. If you still have any other requests about this port, please reopen this issue.
Thanks.
