### ISSUE TITLE
Update proj4 to 6.1.1

### ISSUE THREAD

**Issue by luzpaz** [microsoft/vcpkg#5138]
Changelog: https://github.com/OSGeo/proj.4/releases/tag/5.2.0

https://github.com/Microsoft/vcpkg/tree/master/ports/proj4

**Comment by luzpaz** [comment]
Or create a new port called `proj5` ?

**Comment by luzpaz** [comment]
https://github.com/OSGeo/PROJ/releases/tag/6.1.1

**Comment by JackBoosY** [comment]
#7192

**Comment by JackBoosY** [comment]
#7917 is fixing this issue.

**Comment by JackBoosY** [comment]
Hi @luzpaz, thanks for reporting this issue.
I've upgrade proj4 in #7917, please update vcpkg and rebuild proj4.

Thanks.
