### ISSUE TITLE
[New ports request] xtensor, xtl and xsimd

### ISSUE THREAD

**Issue by zhihaoy** [Microsoft/vcpkg#5140]
Used in public: https://deque.blog/2019/01/11/pythagorean-triples-in-modern-c/
URL: https://github.com/QuantStack/xtensor

**Comment by Codiferous** [comment]
I believe I've merged the PRs for all three of these libraries (thanks, @myd7349!). @zhihaoy Could you give the libraries a try and close this issue if everything works for you? 😄

**Comment by zhihaoy** [comment]
Works for me for now.  I might consider to help porting xtensor-blas later :)
