### ISSUE TITLE
osx 10.14.2 spdlog

### ISSUE THREAD

**Issue by yangxingpping** [Microsoft/vcpkg#5143]
On osx 10.14.2, after I install spdlog with Vcpkg and try to use it, clang++ complian that .../vcpkg/installed/x64-osx/include/spdlog/fmt/bundled/core.h not found, an I found that folder bundled is not exist. so I create it and copy all head files hand by hand, after that, it's work.
environment: 
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix

**Comment by yangxingpping** [comment]
It's still failed.

**Comment by markaren** [comment]
Try to add the definition ```SPDLOG_FMT_EXTERNAL``` , although it should not be necessary with the latest port.  https://github.com/Microsoft/vcpkg/blob/master/ports/spdlog/portfile.cmake

**Comment by yangxingpping** [comment]
Thank you,  it's work!

**Comment by myd7349** [comment]
I created a new PR(#5175 ) to fix this issue. Hope it will work.
