### ISSUE TITLE
require fox-toolkit library in the vcpkg

### ISSUE THREAD

**Issue by bbw2008927** [microsoft/vcpkg#5147]
Hi support,
Recently, when I try to compile SUMO(traffic simulator), I find out I need to compile fox-toolkit by my own.
So is there possible to add fox-toolkit into vcpkg list
http://www.fox-toolkit.org/
Best Regards

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
