### ISSUE TITLE
Add mixxx

### ISSUE THREAD

**Issue by luzpaz** [microsoft/vcpkg#5151]
Mixxx is Free DJ software that gives you everything you need to perform live mixes. 

http://mixxx.org

https://github.com/mixxxdj/mixxx/releases/tag/release-2.2.0

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!

**Comment by Holzhaus** [comment]
Question: Is this desired? AFAIK vcpkg is just for libraries, not end-user applications?
