### ISSUE TITLE
[llvm] CLANG_INSTALL_PREFIX has wrong value

### ISSUE THREAD

**Issue by pgoodman** [microsoft/vcpkg#5153]
When doing a `find_package(Clang CONFIG REQUIRED)` in a project using vcpkg's toolchain file, I noticed that Clang's CMake setup is a bit messed up. The specific error is:

```
CMake Error at /build/vcpkg/installed/x64-osx/share/clang/ClangConfig.cmake:18 (include):
  include could not find load file:

    /build/vcpkg/installed/lib/cmake/clang/ClangTargets.cmake
Call Stack (most recent call first):
  /build/vcpkg/scripts/buildsystems/vcpkg.cmake:247 (_find_package)
  CMakeLists.txt:78 (find_package)
```

In `ClangConfig.cmake` on we have:

```cmake
set(CLANG_CMAKE_DIR "${CLANG_INSTALL_PREFIX}/lib/cmake/clang")
...
include("${CLANG_CMAKE_DIR}/ClangTargets.cmake")
```

This leads me to believe that `CLANG_INSTALL_PREFIX` is incorrect. Specifically, the installation prefix lacks the os/target `x64-osx`, and perhaps other things. This seems to be the same problem as what is listed here: https://answers.launchpad.net/ubuntu/+source/llvm-toolchain-5.0/+question/663810

**Comment by pgoodman** [comment]
I'm working on a patch. The problem I think is that the existing `.patch` file updates LLVM's cmake info, but Clang requires a similar update that must be kept up-to-date with LLVM. The patch I'm trying right now is:

```patch
diff --git a/cmake/modules/CMakeLists.txt b/cmake/modules/CMakeLists.txt
index ac4b0b7..13a271d 100644
--- a/cmake/modules/CMakeLists.txt
+++ b/cmake/modules/CMakeLists.txt
@@ -1,4 +1,4 @@
-set(LLVM_INSTALL_PACKAGE_DIR lib${LLVM_LIBDIR_SUFFIX}/cmake/llvm)
+set(LLVM_INSTALL_PACKAGE_DIR share/llvm)
 set(llvm_cmake_builddir "${LLVM_BINARY_DIR}/${LLVM_INSTALL_PACKAGE_DIR}")
 
 # First for users who use an installed LLVM, create the LLVMExports.cmake file.

diff a/tools/clang/cmake/modules/CMakeLists.txt b/tools/clang/cmake/modules/CMakeLists.txt
--- a/tools/clang/cmake/modules/CMakeLists.txt
+++ b/tools/clang/cmake/modules/CMakeLists.txt
@@ -4,8 +4,8 @@
-set(CLANG_INSTALL_PACKAGE_DIR lib${LLVM_LIBDIR_SUFFIX}/cmake/clang)
+set(CLANG_INSTALL_PACKAGE_DIR share/clang)
 set(clang_cmake_builddir "${CMAKE_BINARY_DIR}/${CLANG_INSTALL_PACKAGE_DIR}")

 # Keep this in sync with llvm/cmake/CMakeLists.txt!
-set(LLVM_INSTALL_PACKAGE_DIR lib${LLVM_LIBDIR_SUFFIX}/cmake/llvm)
+set(LLVM_INSTALL_PACKAGE_DIR lib${LLVM_LIBDIR_SUFFIX}/cmake/llvm)
 set(llvm_cmake_builddir "${LLVM_BINARY_DIR}/${LLVM_INSTALL_PACKAGE_DIR}")
 
 get_property(CLANG_EXPORTS GLOBAL PROPERTY CLANG_EXPORTS)
 ```

**Comment by pgoodman** [comment]
Okay I have done some more attempts. I must have compiled LLVM+Clang about 10 times today. So with the above patch, what I observed happening is that, regardless of me specifying that the `CLANG_INSTALL_PACKAGE_DIR` should be `share/clang`, all the Clang CMake target files would still end up in `share/llvm`, but then `ClangConfig.cmake` would try to include from `share/clang`, and not find the right files. So I went and tried with making the Clang and LLVM install package directories the same. This seems OK.

The next issue I faced is that using `find_package` with Clang requires that the `clang-7` binary be found. This binary is moved out of the `bin` directory and into a `tools` by the portfile. I disabled this copying/deleting and hit on the linter failure with the function `check_bin_folders_are_not_present_in_static_build`. It's not obvious to me why this is a requirement. This function was introduced in 4bf461c9cd136df6aa12a02d7f6ec09b91f8acb7. @alexkaratarakis can you explain to me why `bin` and `debug/bin` are not allowed to be present for static builds?

Alternatively, I would love if someone found an alternative to make this "just work."

**Comment by alexkaratarakis** [comment]
@pgoodman Static builds are expected to only have headers and `lib` files. If you have a non-empty `bin\` directory, then it is very likely that the build is not static (`dll`s) or that there are `exe`s. Applications are not really in scope for `vcpkg`, so any `exe`s that might be produced are deleted (if the option is available we tell the build to not build them at all) OR, if they are needed as part of a library build, are moved to the `tools/` dir.

The  `vcpkg_fixup_cmake_targets` is used to redirect references to `/bin/*.exe`

```
#.rst:
# .. command:: vcpkg_fixup_cmake_targets
#
#  Transform all /debug/share/<port>/*targets-debug.cmake files and move them to /share/<port>.
#  Removes all /debug/share/<port>/*targets.cmake and /debug/share/<port>/*config.cmake
#
#  Transform all references matching /bin/*.exe to /tools/<port>/*.exe
#
#  ::
#  vcpkg_fixup_cmake_targets([CONFIG_PATH <config_path>])
#
#  ``CONFIG_PATH``
#    *.cmake files subdirectory (like "lib/cmake/${PORT}").
#
```

So, if it cannot be found, is it possibly placed in a different (sub)directory than expected?

**Comment by JackBoosY** [comment]
Related: #9622.
