### ISSUE TITLE
Missing QtGraphicalEffects on Windows x64 with VC++ 2017 with Qt 5.11.2

### ISSUE THREAD

**Issue by Mikalai** [Microsoft/vcpkg#5160]
1. Attempted to build https://github.com/Fagrell/clean-editor with vcpkg.
2. Launch cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_TOOLCHAIN_FILE=H:/code2/vcpkg/scripts/buildsystems/vcpkg.cmake
3. Build solution. In bin/Debug appeared plugins and qml folders and Qt and other dependency libraries. 
4. Attempt to start clean-editor-qml.exe failed. Error: 
QQmlApplicationEngine failed to load component
qrc:/views/MainView.qml:16 Type MenuComponent unavailable
qrc:/components/MenuComponent.qml:6 module "QtGraphicalEffects" is not installed
5. I have installation of Qt 5.11.2 from Qt unified installer. Copied C:\Qt\5.11.2\msvc2017_64\qml\QtGraphicalEffects to the local qml directory.
6. Application started.
7. Also noticed that \vcpkg\installed\x64-windows\qml doesn't have QtGraphicalEffects, though "vcpkg install qt5-graphicaleffects:x64-windows" claims that it is already installed:

The following packages are already installed:
    qt5-graphicaleffects[core]:x64-windows
Starting package 1/1: qt5-graphicaleffects:x64-windows
Package qt5-graphicaleffects:x64-windows is already installed

Did I miss some steps using vcpkg or this is a bug?

**Comment by Mikalai** [comment]
Not sure if it matters but files like 
vcpkg\buildtrees\qt5-graphicaleffects\package-build-x64-windows-dbg-out.log
vcpkg\buildtrees\qt5-graphicaleffects\package-build-x64-windows-rel-out.log
vcpkg\buildtrees\qt5-graphicaleffects\package-install-x64-windows-dbg-out.log
vcpkg\buildtrees\qt5-graphicaleffects\package-install-x64-windows-rel-out.log
vcpkg\buildtrees\qt5-graphicaleffects\package-makefiles-x64-windows-dbg-out.log
vcpkg\buildtrees\qt5-graphicaleffects\package-makefiles-x64-windows-rel-out.log

contains next message:
"Some of the required modules (qtHaveModule(quick)) are not available."
"Skipped."

**Comment by TheScarfix** [comment]
Hi @Mikalai, is qt5-declarative (aka Qt Quick) installed with vcpkg? If not can you try rebuilding after you install it. Added qt5-declarative as a dependency in #4991, the plugin is building for me.

**Comment by Mikalai** [comment]
Hi @TheScarfix, thanks for help. 
Adding extra dependency to vcpkg\ports\qt5-graphicaleffects\CONTROL (Build-Depends: qt5-modularscripts, qt5-base, qt5-declarative) and rebuilding of qt5-graphicaleffects fixed the problem: qt5-graphicaleffects is built and all required files are deployed when projects are build with vcpkg.cmake toolchain
