### ISSUE TITLE
install wxwidgets:x86-uwp

### ISSUE THREAD

**Issue by timhirrel** [Microsoft/vcpkg#5163]
C:\Users\timhi\vcpkg>.\vcpkg install wxwidgets:x86-uwp
The following packages will be built and installed:
  * expat[core]:x86-uwp
  * libjpeg-turbo[core]:x86-uwp
  * libpng[core]:x86-uwp
  * tiff[core]:x86-uwp
    wxwidgets[core]:x86-uwp
Additional packages (*) will be modified to complete this operation.
Starting package 1/5: libpng:x86-uwp
Building package libpng[core]:x86-uwp...
-- Using cached C:/Users/timhi/vcpkg/downloads/glennrp-libpng-v1.6.36.tar.gz
-- Using source at C:/Users/timhi/vcpkg/buildtrees/libpng/src/v1.6.36-ef43c59022
-- Applying patch C:/Users/timhi/vcpkg/ports/libpng/use-abort-on-all-platforms.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/Users/timhi/vcpkg/ports/libpng/skip-install-symlink.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Configuring x86-uwp
-- Building x86-uwp-dbg
-- Building x86-uwp-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package libpng[core]:x86-uwp... done
Installing package libpng[core]:x86-uwp...
Installing package libpng[core]:x86-uwp... done
Elapsed time for package libpng:x86-uwp: 38.53 s
Starting package 2/5: libjpeg-turbo:x86-uwp
Building package libjpeg-turbo[core]:x86-uwp...
-- Downloading https://github.com/libjpeg-turbo/libjpeg-turbo/commit/bd96b30b74fe166fc94218cfc64a097fafdcc05f.diff...
-- Downloading https://github.com/libjpeg-turbo/libjpeg-turbo/archive/1.5.3.tar.gz...
-- Extracting source C:/Users/timhi/vcpkg/downloads/libjpeg-turbo-libjpeg-turbo-1.5.3.tar.gz
-- Applying patch add-options-for-exes-docs-headers.patch
-- Applying patch linux-cmake.patch
-- Applying patch C:/Users/timhi/vcpkg/downloads/libjpeg-turbo-bd96b30b74fe166fc94218cfc64a097fafdcc05f.diff
-- Using source at C:/Users/timhi/vcpkg/buildtrees/libjpeg-turbo/src/1.5.3-3db26b6f87
-- Downloading http://www.nasm.us/pub/nasm/releasebuilds/2.12.02/win32/nasm-2.12.02-win32.zip...
-- Configuring x86-uwp
-- Building x86-uwp-dbg
-- Building x86-uwp-rel
-- Performing CMake integration test
-- Performing post-build validation
-- Performing post-build validation done
Building package libjpeg-turbo[core]:x86-uwp... done
Installing package libjpeg-turbo[core]:x86-uwp...
Installing package libjpeg-turbo[core]:x86-uwp... done
Elapsed time for package libjpeg-turbo:x86-uwp: 1.293 min
Starting package 3/5: tiff:x86-uwp
Building package tiff[core]:x86-uwp...
-- Downloading http://download.osgeo.org/libtiff/tiff-4.0.10.tar.gz...
-- Extracting source C:/Users/timhi/vcpkg/downloads/tiff-4.0.10.tar.gz
-- Applying patch add-component-options.patch
-- Applying patch fix-cxx-shared-libs.patch
-- Applying patch crt-secure-no-deprecate.patch
-- Using source at C:/Users/timhi/vcpkg/buildtrees/tiff/src/4.0.10-208d032666
-- Configuring x86-uwp
-- Building x86-uwp-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: C:/Users/timhi/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No
    Working Directory: C:/Users/timhi/vcpkg/buildtrees/tiff/x86-uwp-dbg
    See logs for more information:
      C:\Users\timhi\vcpkg\buildtrees\tiff\install-x86-uwp-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/tiff/portfile.cmake:38 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package tiff:x86-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: tiff:x86-uwp
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

from install-x86-uwp-dbg-out.log:

  5>c:\users\timhi\vcpkg\buildtrees\tiff\src\4.0.10-208d032666\port\lfind.c(49): error C2143: syntax error: missing ')' before '*' [C:\Users\timhi\vcpkg\buildtrees\tiff\x86-uwp-dbg\libtiff\tiff.vcxproj]
     5>c:\users\timhi\vcpkg\buildtrees\tiff\src\4.0.10-208d032666\port\lfind.c(49): error C2081: 'size_t': name in formal parameter list illegal [C:\Users\timhi\vcpkg\buildtrees\tiff\x86-uwp-dbg\libtiff\tiff.vcxproj]
     5>c:\users\timhi\vcpkg\buildtrees\tiff\src\4.0.10-208d032666\port\lfind.c(49): error C2143: syntax error: missing '{' before '*' [C:\Users\timhi\vcpkg\buildtrees\tiff\x86-uwp-dbg\libtiff\tiff.vcxproj]
     5>c:\users\timhi\vcpkg\buildtrees\tiff\src\4.0.10-208d032666\port\lfind.c(49): error C2146: syntax error: missing ';' before identifier 'size' [C:\Users\timhi\vcpkg\buildtrees\tiff\x86-uwp-dbg\libtiff\tiff.vcxproj]
     5>c:\users\timhi\vcpkg\buildtrees\tiff\src\4.0.10-208d032666\port\lfind.c(50): error C2059: syntax error: 'type' [C:\Users\timhi\vcpkg\buildtrees\tiff\x86-uwp-dbg\libtiff\tiff.vcxproj]
     5>Done Building Project "C:\Users\timhi\vcpkg\buildtrees\tiff\x86-uwp-dbg\libtiff\tiff.vcxproj" (default targets) -- FAILED.
     3>Done Building Project "C:\Users\timhi\vcpkg\buildtrees\tiff\x86-uwp-dbg\ALL_BUILD.vcxproj" (default targets) -- FAILED.
     1>Done Building Project "C:\Users\timhi\vcpkg\buildtrees\tiff\x86-uwp-dbg\install.vcxproj" (default targets) -- FAILED.

Build FAILED.

       "C:\Users\timhi\vcpkg\buildtrees\tiff\x86-uwp-dbg\install.vcxproj" (default target) (1) ->
       "C:\Users\timhi\vcpkg\buildtrees\tiff\x86-uwp-dbg\ALL_BUILD.vcxproj" (default target) (3) ->
       "C:\Users\timhi\vcpkg\buildtrees\tiff\x86-uwp-dbg\port\port.vcxproj" (default target) (4) ->
       (ClCompile target) -> 
         c:\users\timhi\vcpkg\buildtrees\tiff\src\4.0.10-208d032666\port\lfind.c(49): error C2143: syntax error: missing ')' before '*' [C:\Users\timhi\vcpkg\buildtrees\tiff\x86-uwp-dbg\port\port.vcxproj]
         c:\users\timhi\vcpkg\buildtrees\tiff\src\4.0.10-208d032666\port\lfind.c(49): error C2081: 'size_t': name in formal parameter list illegal [C:\Users\timhi\vcpkg\buildtrees\tiff\x86-uwp-dbg\port\port.vcxproj]
         c:\users\timhi\vcpkg\buildtrees\tiff\src\4.0.10-208d032666\port\lfind.c(49): error C2143: syntax error: missing '{' before '*' [C:\Users\timhi\vcpkg\buildtrees\tiff\x86-uwp-dbg\port\port.vcxproj]
         c:\users\timhi\vcpkg\buildtrees\tiff\src\4.0.10-208d032666\port\lfind.c(49): error C2146: syntax error: missing ';' before identifier 'size' [C:\Users\timhi\vcpkg\buildtrees\tiff\x86-uwp-dbg\port\port.vcxproj]
         c:\users\timhi\vcpkg\buildtrees\tiff\src\4.0.10-208d032666\port\lfind.c(50): error C2059: syntax error: 'type' [C:\Users\timhi\vcpkg\buildtrees\tiff\x86-uwp-dbg\port\port.vcxproj]

       "C:\Users\timhi\vcpkg\buildtrees\tiff\x86-uwp-dbg\install.vcxproj" (default target) (1) ->
       "C:\Users\timhi\vcpkg\buildtrees\tiff\x86-uwp-dbg\ALL_BUILD.vcxproj" (default target) (3) ->
       "C:\Users\timhi\vcpkg\buildtrees\tiff\x86-uwp-dbg\libtiff\tiff.vcxproj" (default target) (5) ->
         c:\users\timhi\vcpkg\buildtrees\tiff\src\4.0.10-208d032666\port\lfind.c(49): error C2143: syntax error: missing ')' before '*' [C:\Users\timhi\vcpkg\buildtrees\tiff\x86-uwp-dbg\libtiff\tiff.vcxproj]
         c:\users\timhi\vcpkg\buildtrees\tiff\src\4.0.10-208d032666\port\lfind.c(49): error C2081: 'size_t': name in formal parameter list illegal [C:\Users\timhi\vcpkg\buildtrees\tiff\x86-uwp-dbg\libtiff\tiff.vcxproj]
         c:\users\timhi\vcpkg\buildtrees\tiff\src\4.0.10-208d032666\port\lfind.c(49): error C2143: syntax error: missing '{' before '*' [C:\Users\timhi\vcpkg\buildtrees\tiff\x86-uwp-dbg\libtiff\tiff.vcxproj]
         c:\users\timhi\vcpkg\buildtrees\tiff\src\4.0.10-208d032666\port\lfind.c(49): error C2146: syntax error: missing ';' before identifier 'size' [C:\Users\timhi\vcpkg\buildtrees\tiff\x86-uwp-dbg\libtiff\tiff.vcxproj]
         c:\users\timhi\vcpkg\buildtrees\tiff\src\4.0.10-208d032666\port\lfind.c(50): error C2059: syntax error: 'type' [C:\Users\timhi\vcpkg\buildtrees\tiff\x86-uwp-dbg\libtiff\tiff.vcxproj]

    0 Warning(s)
    10 Error(s)

**Comment by PhoebeHui** [comment]
@timhirrel , what's msvc version do you install? tiff[core]:x86-uwp installed successfully with vs2017 latest release 15.9.7.

PS F:\vcpkg\src> .\vcpkg install tiff:x86-uwp
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be built and installed:
    tiff[core]:x86-uwp
Starting package 1/1: tiff:x86-uwp
Building package tiff[core]:x86-uwp...
-- Using cached F:/VCPKG/src/downloads/tiff-4.0.10.tar.gz
-- Using source at F:/VCPKG/src/buildtrees/tiff/src/4.0.10-1f346d015a
-- Configuring x86-uwp
-- Building x86-uwp-dbg
-- Building x86-uwp-rel
-- Installing: F:/VCPKG/src/packages/tiff_x86-uwp/share/tiff/copyright
-- Performing CMake integration test
-- Performing post-build validation
-- Performing post-build validation done
Building package tiff[core]:x86-uwp... done
Installing package tiff[core]:x86-uwp...
Installing package tiff[core]:x86-uwp... done
Elapsed time for package tiff:x86-uwp: 3.031 min

Total elapsed time: 3.031 min

The package tiff is compatible with built-in CMake targets:

    find_package(TIFF REQUIRED)
    target_link_libraries(main PRIVATE TIFF::TIFF)

**Comment by PhoebeHui** [comment]
Additionally,  .\vcpkg install wxwidgets:x86-uwp failed when install expat package since 'expat does not currently support UWP', which has exist issue https://github.com/Microsoft/vcpkg/issues/3174 to track.

**Comment by Cheney-W** [comment]
@timhirrel , Since tiff:x86-uwp could be installed successfully with latest VCPKG and VS2017 15.9.11, and there is an issue https://github.com/Microsoft/vcpkg/issues/3174 to track that expat does not currently support UWP, so we close this issue first.
