### ISSUE TITLE
What about porting ninja to vcpkg ?

### ISSUE THREAD

**Issue by hzaniatost** [microsoft/vcpkg#5167]

**Comment by Voskrese** [comment]
ninja - Ninja is a small build system
It's not a library

https://github.com/ninja-build/ninja/releases

**Comment by hzaniatost** [comment]
Hi, Voskrese ! Привет !

Ok, got it.

So, vcpkg is only interested in libraries, not in applications. Is that
correct ?

All the best,
Hilton

**Comment by Voskrese** [comment]
All this is at the discretion of the programmer, you can collect any tools for yourself, including MSBuild and CMake

https://github.com/Microsoft/msbuild/

**Comment by MikeGitb** [comment]
@hzaniatost : Can't speak for the project maintainers, but vcpkg is not meant to be a system package manager like apt. Instead it's a library package manager for c++ libraries. 

If you are interested in a windows system package manager, something like https://chocolatey.org/ might suite your needs (not tested it myself).
