### ISSUE TITLE
Flann not building; Ubuntu 18.04.1

### ISSUE THREAD

**Issue by MikePelton** [microsoft/vcpkg#5168]
Hi - have tried various ways to get round this but to no avail. The output's listed at the bottom, and the error is below. The core of the error is "No SOURCES given to target: flann" - there's [some history](https://github.com/mariusmuja/flann/issues/369) with this issue using cmake 3.11 and greater, but in theory it should build with cmake 3.10.x - I'm using 3.10.2. This is an otherwise fresh Ubuntu 18.04.1 - "all" I'm trying to do is to get theia to build from vcpkg, but it fails at the flann hurdle. Driving me nuts - all help welcome!

CMake Error at /media/root/DataVolume/vcpkg/scripts/buildsystems/vcpkg.cmake:159 (_add_library):
  No SOURCES given to target: flann
Call Stack (most recent call first):
  src/cpp/CMakeLists.txt:93 (add_library)

CMake Error at /media/root/DataVolume/vcpkg/scripts/buildsystems/vcpkg.cmake:159 (_add_library):
  No SOURCES given to target: flann_cpp
Call Stack (most recent call first):
  src/cpp/CMakeLists.txt:38 (add_library)

-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.15") 
-- Found GTest: /media/root/DataVolume/vcpkg/installed/x64-linux/lib/libgtest.a  
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Install prefix: /media/root/DataVolume/vcpkg/packages/flann_x64-linux/debug
-- Build type: Debug
-- Building C bindings: ON
-- Building examples: OFF
-- Building tests: ON
-- Building documentation: OFF
-- Building python bindings: OFF
-- Building matlab bindings: OFF
-- Building CUDA library: OFF
-- Using OpenMP support: ON
-- Using MPI support: OFF
-- Configuring done
-- Build files have been written to: /media/root/DataVolume/vcpkg/buildtrees/flann/x64-linux-dbg

**Comment by MikePelton** [comment]
Flann 1.9.1-8 *does* build on Windows under cmake 3.13.2 and after a pleasant hour or so upgrading cmake on Ubuntu to 3.13.3 I can confirm it *does not* build on Ubuntu with the later cmake. HELP!

**Comment by Voskrese** [comment]
cmake? **Only Linux** PATCH

https://github.com/chambbj/flann-feedstock/blob/011245e79b497dcd22ca12a7903e5b502232f569/recipe/cmake.patch

**Comment by MikePelton** [comment]
Hi Voskrese - your comment's a bit cryptic for me - is that a note to yourself or are you suggesting I should be doing something different?

**Comment by Voskrese** [comment]
you yourself were looking for how to fix the error? watched the code?

>  No SOURCES given to target: flann_cpp

comment 

```
...
#    add_library(flann_cpp SHARED "")
...
```

**Comment by MikePelton** [comment]
Hi and thanks for coming back so fast - I understand what you're saying now in terms of how to fix the issue for me, but we need to fix this for the whole vcpkg community - it's a bug! All the best, Mike

**Comment by JackBoosY** [comment]
Hi @MikePelton, thanks for reporting this issue!
Flann should be fixed with PR #6294. Please update vcpkg and rebuild flann.

Thanks.
