### ISSUE TITLE
Cannot Compile ZeroMQ for either ARM/ARM64

### ISSUE THREAD

**Issue by dwcullop** [Microsoft/vcpkg#5171]
Greetings!  I'm am using Windows 10.0.17763.253 and Visual Studio 2017 15.9.3.  I'm trying to build [ZeroMQ ](https://github.com/zeromq/libzmq) using your wonderful tool, and while it works great for  the `x64-windows` and `x86-windows` triplets, it fails when I try to build for ARM or ARM64.  

To reproduce, try either of the following:
1) Run: `vcpkg install zeromq:arm64-windows`
OR
1) Run: `vcpkg install zeromq:arm-windows`

They both will yield a build failure in the same place, and I've attached these logs so that you can see the problem:
1) [install-arm64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2766442/install-arm64-windows-dbg-out.log)
1) [install-arm-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2766443/install-arm-windows-dbg-out.log)

I hope I've given you enough information to help resolve this issue.  If not, please let me know and I will give you whatever is needed.  Also, if I need to take this up with the ZeroMQ people, let me know, and I can do that as well.

**Comment by Voskrese** [comment]
```
\src\clock.cpp(260): error C2065: 'CLOCK_MONOTONIC': undeclared identifier
\src\clock.cpp(260): error C3861: 'clock_gettime': identifier not found 
```
https://github.com/zeromq/libzmq/issues

https://github.com/zeromq/libzmq/search?q=CLOCK_MONOTONIC&type=Issues

**Comment by dwcullop** [comment]
> ```
> \src\clock.cpp(260): error C2065: 'CLOCK_MONOTONIC': undeclared identifier
> \src\clock.cpp(260): error C3861: 'clock_gettime': identifier not found 
> ```

Yes, the problem is that `clock_gettime` is not an API that is available on Windows platforms.

> https://github.com/zeromq/libzmq/issues
> https://github.com/zeromq/libzmq/search?q=CLOCK_MONOTONIC&type=Issues

Thank you for the links, but I had already checked the ZeroMQ issues for anything that might fix the issue, but I didn't find any more than you did.  Are you saying that this is not a VcPkg issue and that I should open an issue in the ZeroMQ repo?  I can certainly do that, but since I'm not building ZeroMQ except via VcPkg, I thought I would try this first.

**Comment by LarryIII** [comment]
Not a vcpkg issue, it because zeromq does not support ARM/ARM64, you have reported the issue to zeromq, so closed this issue in vcpkg. Once this issue was fixed, we will pick up it again.
