### ISSUE TITLE
vcpg don`t build on windows

### ISSUE THREAD

**Issue by aPSopt** [Microsoft/vcpkg#5174]
Guys, second day the vspkg cant be build on win10. 
It is not serious. 
Are you doing any test before commit?
In any case you could revert changes for debug.

**Comment by Voskrese** [comment]
log?

[vcpkg.zip](https://github.com/Microsoft/vcpkg/files/2768223/vcpkg.zip)

**Comment by aPSopt** [comment]
I mean that the vcpkg.exe sefl cant be build.
I launch bootstrap-vcpkg.bat and it cant build vcpkglib.vcxproj + vcpkg.vcxproj + vcpkgmetricsuploader.vcxproj by the reason that it cant fidn Microsoft.Cpp.Default.props.
It cant find the Microsoft.Cpp.Default.props because it search in the wrong path - it search in the root on the disk where vcpkg was clone.

Somebody push this bug time to time every few month.

**Comment by PhoebeHui** [comment]
@aPSopt, does the issue still occur? could you try vcpkg latest revision? and share the log here if it still fail.

**Comment by aPSopt** [comment]
@PhoebeHui, now it works fine. Thx!
