### ISSUE TITLE
building qhull causes vcpkg.exe to be removed

### ISSUE THREAD

**Issue by edoreshef** [Microsoft/vcpkg#5187]
Hello,

need a little help, I'm running 'vcpkg install pcl:x64-windows' and half way though there is a problem around building of 'qhull'. The build doesn't complain on error and actually produces 'buildtrees\qhull\x64-windows-rel\qhull.exe'. The problem is that after the build is completed the vcpkg.exe file **simply gets deleted** (have to bootstrap again to rebuild it) and the build just stops (as you can see below).

```
Starting package 1/36: qhull:x64-windows
Building package qhull[core]:x64-windows...
-- Downloading https://github.com/qhull/qhull/archive/5a79a0009454c86e9848646b3c296009125231bf.tar.gz...
-- Extracting source C:/vcpkg/downloads/qhull-qhull-5a79a0009454c86e9848646b3c296009125231bf.tar.gz
-- Using source at C:/vcpkg/buildtrees/qhull/src/09125231bf-a00bd08e2d
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel

C:\vcpkg>
```

[install-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2774145/install-x64-windows-dbg-out.log)
[install-x64-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/2774146/install-x64-windows-rel-out.log)
[config-x64-windows-out.log](https://github.com/Microsoft/vcpkg/files/2774147/config-x64-windows-out.log)

Thank you for helping,
Edo

**Comment by wangli28** [comment]
Hi @edoreshef, thank you for posting the issue, does the issue still occur? I installed it successfully with VS2017 15.9.11 and VCPKG latest source. I didn't find any error around building of `qhull`.

> PS E:\vcpkg> .\vcpkg.exe install pcl:x64-windows
The following packages will be built and installed:
/  * boost-algorithm[core]:x64-windows
/  * boost-any[core]:x64-windows
/  * boost-array[core]:x64-windows
......
/ * flann[core]:x64-windows
/    pcl[core]:x64-windows
/  * qhull[core]:x64-windows
/  * zstd[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/91: boost-modular-build-helper:x64-windows
Building package boost-modular-build-helper[core]:x64-windows...
-- Performing post-build validation
......
Starting package 57/91: qhull:x64-windows
Building package qhull[core]:x64-windows...
-- Using cached E:/vcpkg/downloads/qhull-qhull-v7.2.1.tar.gz
-- Using source at E:/vcpkg/buildtrees/qhull/src/v7.2.1-68a173ff84
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package qhull[core]:x64-windows... done
Installing package qhull[core]:x64-windows...
Installing package qhull[core]:x64-windows... done
Elapsed time for package qhull:x64-windows: 41.83 s
......
Building package pcl[core]:x64-windows... done
Installing package pcl[core]:x64-windows...
Installing package pcl[core]:x64-windows... done
Elapsed time for package pcl:x64-windows: 41.22 min
/
Total elapsed time: 54.34 min
/
The package pcl:x64-windows provides CMake targets:
/
    find_package(PCL CONFIG REQUIRED)
    target_link_libraries(main PRIVATE ${pcl_component})

**Comment by edoreshef** [comment]
Sorry, i should have updated. It ended up being thr antivirus deleting the file because a signature change.
