### ISSUE TITLE
Building vcpkg.exe fails: The "CppClean" task was not given a value for the required parameter "FilePatternsToDeleteOnClean"

### ISSUE THREAD

**Issue by heaths** [microsoft/vcpkg#5189]
Cloned vcpkg on a Windows 10 RS5 machine with several VS instances, including the one selected - VS2019 Preview, which does have the following Windows SDKs installed along with the Desktop C++ workload and most optional components:

```
Microsoft.VisualStudio.Component.Windows10SDK.17134
Microsoft.VisualStudio.Component.Windows10SDK.17763
Win10SDK_10.0.17134                                
Win10SDK_10.0.17763                                
```

But running bootstrap-vcpkg.bat results in the following error:

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VC\v160\Microsoft.CppClean.targets(76,5): error MSB4044: The "CppClean" task was not given a value for the required parameter "FilePatternsToDeleteOnClean". [E:\Source\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
E:\Source\vcpkg\scripts\bootstrap.ps1 : Building vcpkg.exe failed. Please ensure you have installed Visual Studio with the Desktop C++ workload and the Windows SDK for Desktop C++.
At line:1 char:4
+ & {& 'E:\Source\vcpkg\scripts\bootstrap.ps1' }
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,bootstrap.ps1
```

I can build other native projects on this box using the same instance of Visual Studio.

**Comment by Rody66** [comment]
I have the same problem with C++/CLI project on VS 2019 preview 1.
`1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VC\v160\Microsoft.CppClean.targets(76,5): error MSB4044: The "CppClean" task was not given a value for the required parameter "FilePatternsToDeleteOnClean".`
Is there some advice hot fix it?

**Comment by sawich** [comment]
I fixed it
Just Retarget solution to last sdk ver.

**Comment by heaths** [comment]
@sawich, that is not always an acceptable solution. Behaviors can change across versions, and when statically linking that can have undesirable effects.

**Comment by PhoebeHui** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.
