### ISSUE TITLE
Install CMake project to vcpkg

### ISSUE THREAD

**Issue by zhouzekai** [Microsoft/vcpkg#5191]
vcpkg works fine to install almost every package I need, it helps me install c++ package on windows easily.

Sometimes, I need to develop the library. For example, I download the pcl(poind cloud library) source code, and modified some part of its source code. Use the CMake tool to generate the project, then an INSTALL project will be generated. The INSTALL project will copy the includes, lib, bin to CMAKE_INSTALL_PREFIX. Is there any convenient way to install them to vcpkg? I don't want to copy the file(includes, lib, bin) to the correspond directory manually every time.

Any help will be appreciated.

**Comment by MikeGitb** [comment]
As a workaround:

For many libraries, you could probably just alter the portfile such that it clones the data from your local repository (never tried that enough). If you then let vcpkg install the package from head it should always fetch, compile and install the latest version you committed.
