### ISSUE TITLE
"./vcpkg env" command error on macOS

### ISSUE THREAD

**Issue by onegaz** [microsoft/vcpkg#5197]
Encounted error when running "./vcpkg env" on macOS. The following is error message.
bash-3.2$ ./vcpkg env 
sh: cmd: command not found

OS version:
bash-3.2$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.14.2
BuildVersion:   18C54

Update vcpkg source code and rerun bootstrap-vcpkg.sh does not help.

Tried to run with debug enabled:
bash-3.2$ ./vcpkg env --debug --triplet x64-osx
[DEBUG] Using vcpkg-root: \~/oss/vcpkg
[DEBUG] popen(which cmake 2>&1)
[DEBUG] _pclose() returned 0 after     5024 us
[DEBUG] popen("\~/oss/vcpkg/downloads/tools/cmake-3.12.4-osx/cmake-3.12.4-Darwin-x86_64/CMake.app/Contents/bin/cmake" --version 2>&1)
[DEBUG] _pclose() returned 0 after    15533 us
[DEBUG] popen("\~/oss/vcpkg/downloads/tools/cmake-3.12.4-osx/cmake-3.12.4-Darwin-x86_64/CMake.app/Contents/bin/cmake" "-DCMAKE_TRIPLET_FILE=\~/oss/vcpkg/triplets/x64-osx.cmake" -P "\~/oss/vcpkg/scripts/get_triplet_environment.cmake" 2>&1)
[DEBUG] _pclose() returned 0 after    17335 us
[DEBUG] popen(sha1sum "\~/oss/vcpkg/triplets/x64-osx.cmake" 2>&1)
[DEBUG] _pclose() returned 32512 after     3268 us
[DEBUG] popen(shasum -a 1 "\~/oss/vcpkg/triplets/x64-osx.cmake" 2>&1)
[DEBUG] _pclose() returned 0 after    27398 us
[DEBUG] popen(sha1sum "\~/oss/vcpkg/scripts/toolchains/osx.cmake" 2>&1)
[DEBUG] _pclose() returned 32512 after     2969 us
[DEBUG] popen(shasum -a 1 "\~/oss/vcpkg/scripts/toolchains/osx.cmake" 2>&1)
[DEBUG] _pclose() returned 0 after    24736 us
[DEBUG] system(cmd)
sh: cmd: command not found
[DEBUG] system() returned 32512 after 2146 us
[DEBUG] ../src/vcpkg/commands.env.cpp(73)
[DEBUG] Exiting after 102735 us (100371 us)

**Comment by PhoebeHui** [comment]
@onegaz, thank you for posting this issue!
execute ./vcpkg --help, it shows that:
vcpkg env                       Creates a clean shell environment for development or compiling.

From https://github.com/Microsoft/vcpkg/blob/master/toolsrc/src/vcpkg/commands.env.cpp#L69:
It will call cmd, and it's trick to start cmd in macos.

**Comment by PhoebeHui** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.
