### ISSUE TITLE
[QScintilla] Moc bug 

### ISSUE THREAD

**Issue by VladBolotov** [microsoft/vcpkg#5198]
I have a class derived from QsciScintilla and I am getting Linker error. But if QsciScintilla is a member of a class its okay. It's looks like something wrong witht a MOC. Previously I had no such errors with QSci build manually, so is it VCPKG specific problem or am I doing something wrong?
```
Vcpkg 2018.11.23-nohash
Qt 5.11.2
QScintilla 2.10-7
```
``` 
Code: LNK 2001 
Description: unresolved external symbol "public: static struct QMetaObject const QsciScintilla::staticMetaObject" (?staticMetaObject@QsciScintilla@@2UQMetaObject@@B) 
File: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\mocs_compilation.cpp.obj 
Line: 1 
```
CMakeLists.txt
```
cmake_minimum_required(VERSION 3.0)

project(QSciBug)

#Qt specific
set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTORCC ON)

#Qt
find_package(Qt5Widgets CONFIG REQUIRED)
find_package(Qt5Core CONFIG REQUIRED)
find_package(Qt5PrintSupport CONFIG REQUIRED)

set(SOURCES 
	Main.cpp
	#Good/TextEditor.hpp
	#Good/TextEditor.cpp
	Bad/TextEditor.hpp
	Bad/TextEditor.cpp
)

# find_package??? create custom???
if(CMAKE_BUILD_TYPE STREQUAL "Debug")
	set(QScintillaLib "D:/tools/vcpkg/packages/qscintilla_x64-windows/debug/lib/qscintilla2.lib")
endif()


add_executable(${PROJECT_NAME} WIN32 ${SOURCES})
target_link_libraries(${PROJECT_NAME} 
${QScintillaLib}
Qt5::Widgets 
Qt5::Core 
Qt5::PrintSupport)

```
Main.cpp
```C++
#include <qapplication.h>
#include <qmainwindow.h>

//#include "Good/TextEditor.hpp"
#include "Bad/TextEditor.hpp"

int main(int argc, char** argv) {
	QApplication app(argc, argv);

	auto window  = new QMainWindow;
	window->setCentralWidget(new TextEditor);
	window->show();

	return QApplication::exec();
}
```

Good/TextEditor.hpp

```C++
#pragma once

#include <Qsci/qsciscintilla.h>

class TextEditor : public QWidget {
	Q_OBJECT
public:
	explicit TextEditor(QWidget* parent = nullptr);

private:
	QsciScintilla* m_sciEditor;
};
```
Good/TextEditor.cpp

```C++
#include "TextEditor.hpp"

#include <qlayout.h>

TextEditor::TextEditor(QWidget *parent) : 
	QWidget(parent),
	m_sciEditor(new QsciScintilla(this))
{
	auto layout = new QHBoxLayout;
	layout->addWidget(m_sciEditor);
	setLayout(layout);
}
```
Bad/TextEditor.hpp
```C++
#pragma once

#include <Qsci/qsciscintilla.h>

class TextEditor : public QsciScintilla {
	Q_OBJECT
public:
	explicit TextEditor(QWidget* parent = nullptr);
};
```
Bad/TextEditor.cpp
```C++
#include "TextEditor.hpp"
TextEditor::TextEditor(QWidget *parent) : 
	QsciScintilla(parent)
{
}
```

**Comment by Neumann-A** [comment]
I think your are missing a:

`#include <moc_TextEditor.cpp>` in your TextEditor.cpp

In your Bad Version QsciScintilla defines the missing symbol.

Note: Does QsciScintilla not have a proper cmake target ?

**Comment by JackBoosY** [comment]
@VladBolotov 
Can you comment out Q_OBJEXT in your class declaration and try to compile again?

**Comment by VladBolotov** [comment]
@JackBoosY 

It worked, but you’ll get "unusable" solution (moc, properties, signals/slots do not work).

**Comment by JackBoosY** [comment]
@VladBolotov Maybe you should create a issue on [here](https://sourceforge.net/p/scintilla/bugs/)?

**Comment by VladBolotov** [comment]
@JackBoosY

QScintilla and Scintilla is two different projects. QScintilla is a project from riverbankcomputing and the only option for bug report is mailing list (I couldn’t find any other options). I send an email about my problem (it was Jan 21, 2019) and doesn’t get anything.

**Comment by Neumann-A** [comment]
@JackBoosY should be closed. Is not a vcpkg issue.

**Comment by JackBoosY** [comment]
@VladBolotov I think this is a upstream issue, we need to wait for upstream to fix this issue and update to the new version.

**Comment by JackBoosY** [comment]
Hi @VladBolotov, since QScintilla was updated to 2.11.4, does this issue exists?

**Comment by Scopeuk** [comment]
I have experienced this error as the default package has dynamic link scope it was necessary to add add_definitions(-DQSCINTILLA_DLL) to my project CMakeLists.txt to switch the library dependency to dynamic linking.

**Comment by JackBoosY** [comment]
Reopen this issue since it's not resolved completely.

**Comment by JonLiu1993** [comment]
@VladBolotov, does this issue exist since QScintilla has been updated to 2.12.0?

**Comment by JackBoosY** [comment]
I will close this issue now, please ping me if anyone meet this again.
