### ISSUE TITLE
Building curl[ssh, tool]:x64-windows-static fails 

### ISSUE THREAD

**Issue by anluoma** [Microsoft/vcpkg#5200]
Compiling curl with following feature curl[ssh, tool] fails when linking. Other features works ok and ssh and tool separately works. Dynamic linking compiles with same options.

Steps to reproduce: vcpkg install curl[ssh, tool]:x64-windows-**static** 
Machine: Windows 10 Enterprise,1803.

Latest git head:
commit ce7c2294c9985a2eab4baa95f7176b43be5b30d8 (master)

`LINK: command "D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\link.exe src\CMakeFiles\curl.dir\slist_wc.c.obj src\CMakeFiles\curl.dir\tool_binmode.c.obj src\CMakeFiles\curl.dir\tool_bname.c.obj src\CMakeFiles\curl.dir\tool_cb_dbg.c.obj src\CMakeFiles\curl.dir\tool_cb_hdr.c.obj src\CMakeFiles\curl.dir\tool_cb_prg.c.obj src\CMakeFiles\curl.dir\tool_cb_rea.c.obj src\CMakeFiles\curl.dir\tool_cb_see.c.obj src\CMakeFiles\curl.dir\tool_cb_wrt.c.obj src\CMakeFiles\curl.dir\tool_cfgable.c.obj src\CMakeFiles\curl.dir\tool_convert.c.obj src\CMakeFiles\curl.dir\tool_dirhie.c.obj src\CMakeFiles\curl.dir\tool_doswin.c.obj src\CMakeFiles\curl.dir\tool_easysrc.c.obj src\CMakeFiles\curl.dir\tool_filetime.c.obj src\CMakeFiles\curl.dir\tool_formparse.c.obj src\CMakeFiles\curl.dir\tool_getparam.c.obj src\CMakeFiles\curl.dir\tool_getpass.c.obj src\CMakeFiles\curl.dir\tool_help.c.obj src\CMakeFiles\curl.dir\tool_helpers.c.obj src\CMakeFiles\curl.dir\tool_homedir.c.obj src\CMakeFiles\curl.dir\tool_hugehelp.c.obj src\CMakeFiles\curl.dir\tool_libinfo.c.obj src\CMakeFiles\curl.dir\tool_main.c.obj src\CMakeFiles\curl.dir\tool_metalink.c.obj src\CMakeFiles\curl.dir\tool_msgs.c.obj src\CMakeFiles\curl.dir\tool_operate.c.obj src\CMakeFiles\curl.dir\tool_operhlp.c.obj src\CMakeFiles\curl.dir\tool_panykey.c.obj src\CMakeFiles\curl.dir\tool_paramhlp.c.obj src\CMakeFiles\curl.dir\tool_parsecfg.c.obj src\CMakeFiles\curl.dir\tool_strdup.c.obj src\CMakeFiles\curl.dir\tool_setopt.c.obj src\CMakeFiles\curl.dir\tool_sleep.c.obj src\CMakeFiles\curl.dir\tool_urlglob.c.obj src\CMakeFiles\curl.dir\tool_util.c.obj src\CMakeFiles\curl.dir\tool_vms.c.obj src\CMakeFiles\curl.dir\tool_writeout.c.obj src\CMakeFiles\curl.dir\tool_xattr.c.obj src\CMakeFiles\curl.dir\__\lib\strtoofft.c.obj src\CMakeFiles\curl.dir\__\lib\nonblock.c.obj src\CMakeFiles\curl.dir\__\lib\warnless.c.obj src\CMakeFiles\curl.dir\__\lib\curl_ctype.c.obj src\CMakeFiles\curl.dir\curl.rc.res /out:src\curl.exe /implib:src\curl.lib /pdb:src\curl.pdb /version:0.0 /machine:x64 /MANIFEST:NO /DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF /subsystem:console lib\libcurl.lib wldap32.lib winmm.lib ws2_32.lib advapi32.lib crypt32.lib advapi32.lib D:\Source\Repos\vcpkg\installed\x64-windows-static\lib\zlib.lib D:\Source\Repos\vcpkg\installed\x64-windows-static\lib\libssh2.lib crypt32.lib D:\Source\Repos\vcpkg\installed\x64-windows-static\lib\zlib.lib D:\Source\Repos\vcpkg\installed\x64-windows-static\lib\libssh2.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib" failed (exit code 1120) with the following output:
Microsoft (R) Incremental Linker Version 14.16.27024.1
Copyright (C) Microsoft Corporation.  All rights reserved.

libssh2.lib(global.obj) : error LNK2019: unresolved external symbol OPENSSL_add_all_algorithms_noconf referenced in function _libssh2_init_if_needed
libssh2.lib(global.obj) : error LNK2019: unresolved external symbol ENGINE_load_builtin_engines referenced in function _libssh2_init_if_needed
libssh2.lib(global.obj) : error LNK2019: unresolved external symbol ENGINE_register_all_complete referenced in function _libssh2_init_if_needed
libssh2.lib(hostkey.obj) : error LNK2019: unresolved external symbol RSA_free referenced in function hostkey_method_ssh_rsa_dtor
libssh2.lib(openssl.obj) : error LNK2001: unresolved external symbol RSA_free
libssh2.lib(hostkey.obj) : error LNK2019: unresolved external symbol DSA_free referenced in function hostkey_method_ssh_dss_dtor
libssh2.lib(openssl.obj) : error LNK2001: unresolved external symbol DSA_free
libssh2.lib(hostkey.obj) : error LNK2019: unresolved external symbol EVP_DigestUpdate referenced in function hostkey_method_ssh_rsa_signv
libssh2.lib(openssl.obj) : error LNK2001: unresolved external symbol EVP_DigestUpdate
libssh2.lib(kex.obj) : error LNK2001: unresolved external symbol EVP_DigestUpdate
libssh2.lib(hostkey.obj) : error LNK2019: unresolved external symbol EVP_DigestFinal referenced in function hostkey_method_ssh_rsa_signv
libssh2.lib(openssl.obj) : error LNK2001: unresolved external symbol EVP_DigestFinal
libssh2.lib(kex.obj) : error LNK2001: unresolved external symbol EVP_DigestFinal
libssh2.lib(channel.obj) : error LNK2019: unresolved external symbol RAND_bytes referenced in function libssh2_channel_x11_req_ex
libssh2.lib(kex.obj) : error LNK2001: unresolved external symbol RAND_bytes
libssh2.lib(transport.obj) : error LNK2001: unresolved external symbol RAND_bytes
libssh2.lib(knownhost.obj) : error LNK2019: unresolved external symbol EVP_sha1 referenced in function knownhost_check
libssh2.lib(mac.obj) : error LNK2001: unresolved external symbol EVP_sha1
libssh2.lib(knownhost.obj) : error LNK2019: unresolved external symbol HMAC_CTX_init referenced in function knownhost_check
libssh2.lib(mac.obj) : error LNK2001: unresolved external symbol HMAC_CTX_init
libssh2.lib(knownhost.obj) : error LNK2019: unresolved external symbol HMAC_CTX_cleanup referenced in function knownhost_check
libssh2.lib(mac.obj) : error LNK2001: unresolved external symbol HMAC_CTX_cleanup
libssh2.lib(knownhost.obj) : error LNK2019: unresolved external symbol HMAC_Init_ex referenced in function knownhost_check
libssh2.lib(mac.obj) : error LNK2001: unresolved external symbol HMAC_Init_ex
libssh2.lib(knownhost.obj) : error LNK2019: unresolved external symbol HMAC_Update referenced in function knownhost_check
libssh2.lib(mac.obj) : error LNK2001: unresolved external symbol HMAC_Update
libssh2.lib(knownhost.obj) : error LNK2019: unresolved external symbol HMAC_Final referenced in function knownhost_check
libssh2.lib(mac.obj) : error LNK2001: unresolved external symbol HMAC_Final
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol BIO_new_file referenced in function _libssh2_pub_priv_keyfile
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol BIO_free referenced in function _libssh2_pub_priv_keyfile
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol BIO_ctrl referenced in function _libssh2_pub_priv_keyfile
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol BIO_new_mem_buf referenced in function _libssh2_pub_priv_keyfilememory
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol BN_num_bits referenced in function _libssh2_dsa_sha1_sign
libssh2.lib(kex.obj) : error LNK2001: unresolved external symbol BN_num_bits
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol BN_new referenced in function _libssh2_dsa_new
libssh2.lib(kex.obj) : error LNK2001: unresolved external symbol BN_new
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol BN_bin2bn referenced in function _libssh2_dsa_new
libssh2.lib(kex.obj) : error LNK2001: unresolved external symbol BN_bin2bn
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol BN_bn2bin referenced in function _libssh2_dsa_sha1_sign
libssh2.lib(kex.obj) : error LNK2001: unresolved external symbol BN_bn2bin
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol RSA_new referenced in function _libssh2_rsa_new
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol RSA_size referenced in function _libssh2_rsa_sha1_sign
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol RSA_sign referenced in function _libssh2_rsa_sha1_sign
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol RSA_verify referenced in function _libssh2_rsa_sha1_verify
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol DSA_SIG_new referenced in function _libssh2_dsa_sha1_verify
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol DSA_SIG_free referenced in function _libssh2_dsa_sha1_sign
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol DSA_do_sign referenced in function _libssh2_dsa_sha1_sign
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol DSA_do_verify referenced in function _libssh2_dsa_sha1_verify
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol DSA_new referenced in function _libssh2_dsa_new
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol EVP_Cipher referenced in function _libssh2_cipher_crypt
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol EVP_MD_CTX_init referenced in function _libssh2_dsa_sha1_verify
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol EVP_DigestInit referenced in function _libssh2_dsa_sha1_verify
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol EVP_CipherInit referenced in function _libssh2_cipher_init
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol EVP_CIPHER_CTX_init referenced in function _libssh2_cipher_init
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol OpenSSL_add_all_ciphers referenced in function _libssh2_pub_priv_keyfile
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol EVP_get_cipherbyname referenced in function _libssh2_pub_priv_keyfile
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol EVP_get_digestbyname referenced in function _libssh2_dsa_sha1_verify
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol EVP_PKEY_get1_RSA referenced in function gen_publickey_from_rsa_evp
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol EVP_PKEY_get1_DSA referenced in function gen_publickey_from_dsa_evp
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol EVP_PKEY_free referenced in function _libssh2_pub_priv_keyfile
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol PEM_read_bio_RSAPrivateKey referenced in function _libssh2_rsa_new_private
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol PEM_read_bio_DSAPrivateKey referenced in function _libssh2_dsa_new_private
libssh2.lib(openssl.obj) : error LNK2019: unresolved external symbol PEM_read_bio_PrivateKey referenced in function _libssh2_pub_priv_keyfile
libssh2.lib(kex.obj) : error LNK2019: unresolved external symbol BN_CTX_new referenced in function diffie_hellman_sha1
libssh2.lib(kex.obj) : error LNK2019: unresolved external symbol BN_CTX_free referenced in function diffie_hellman_sha1
libssh2.lib(kex.obj) : error LNK2019: unresolved external symbol BN_rand referenced in function diffie_hellman_sha1
libssh2.lib(kex.obj) : error LNK2019: unresolved external symbol BN_clear_free referenced in function kex_method_diffie_hellman_group1_sha1_key_exchange
libssh2.lib(kex.obj) : error LNK2019: unresolved external symbol BN_set_word referenced in function kex_method_diffie_hellman_group1_sha1_key_exchange
libssh2.lib(kex.obj) : error LNK2019: unresolved external symbol BN_mod_exp referenced in function diffie_hellman_sha1
libssh2.lib(crypt.obj) : error LNK2001: unresolved external symbol EVP_des_ede3_cbc
libssh2.lib(crypt.obj) : error LNK2001: unresolved external symbol EVP_rc4
libssh2.lib(crypt.obj) : error LNK2001: unresolved external symbol EVP_bf_cbc
libssh2.lib(crypt.obj) : error LNK2001: unresolved external symbol EVP_cast5_cbc
libssh2.lib(crypt.obj) : error LNK2001: unresolved external symbol EVP_aes_128_cbc
libssh2.lib(crypt.obj) : error LNK2001: unresolved external symbol EVP_aes_128_ctr
libssh2.lib(crypt.obj) : error LNK2001: unresolved external symbol EVP_aes_192_cbc
libssh2.lib(crypt.obj) : error LNK2001: unresolved external symbol EVP_aes_192_ctr
libssh2.lib(crypt.obj) : error LNK2001: unresolved external symbol EVP_aes_256_cbc
libssh2.lib(crypt.obj) : error LNK2001: unresolved external symbol EVP_aes_256_ctr
libssh2.lib(crypt.obj) : error LNK2019: unresolved external symbol EVP_CIPHER_CTX_cleanup referenced in function crypt_dtor
libssh2.lib(mac.obj) : error LNK2019: unresolved external symbol EVP_md5 referenced in function mac_method_hmac_md5_hash
libssh2.lib(mac.obj) : error LNK2019: unresolved external symbol EVP_sha256 referenced in function mac_method_hmac_sha2_256_hash
libssh2.lib(mac.obj) : error LNK2019: unresolved external symbol EVP_sha512 referenced in function mac_method_hmac_sha2_512_hash
libssh2.lib(mac.obj) : error LNK2019: unresolved external symbol EVP_ripemd160 referenced in function mac_method_hmac_ripemd160_hash
src\curl.exe : fatal error LNK1120: 66 unresolved externals
ninja: build stopped: subcommand failed.`

**Comment by JackBoosY** [comment]
Hi @anluoma , thanks for reporting this issue!
This bug has been fixed in #5682. You need to update and rebuild it.
Thx.
