### ISSUE TITLE
Can't install libmysql on OSX 10.14.2

### ISSUE THREAD

**Issue by izzyreal** [microsoft/vcpkg#5204]
Ultimately I'm trying to install Poco with mysql connector support. Or if someone can recommend a go-to stack for http server + mysql connector support, I'm open to suggestions. Many thanks in advance.

  Package: libmysql:x64-osx
  Vcpkg version: 2018.11.23-unknownhash

config-x64-osx-dbg-out.log:

-- Running cmake version 3.12.4
-- Found Git: /usr/bin/git (found version "2.17.2 (Apple Git-113)") 
-- Configuring with MAX_INDEXES = 64U
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_GENERATOR: Ninja
-- Performing Test HAVE_BUGGY_CLANG_VERSION
-- Performing Test HAVE_BUGGY_CLANG_VERSION - Failed
-- Performing Test HAVE_SUPPORTED_CLANG_VERSION
-- Performing Test HAVE_SUPPORTED_CLANG_VERSION - Success
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void *
-- Check size of void * - done
-- SIZEOF_VOIDP 8
-- MySQL 8.0.4-rc
-- Packaging as: mysql-8.0.4-rc-osx10.14-x86_64
-- Performing Test C_LD_GOLD_RESULT
-- Performing Test C_LD_GOLD_RESULT - Failed
-- Performing Test CXX_LD_GOLD_RESULT
-- Performing Test CXX_LD_GOLD_RESULT - Failed
-- Found /Users/izmarverhage/git/vcpkg/installed/x64-osx/include/boost/version.hpp 
-- BOOST_VERSION_NUMBER is #define BOOST_VERSION 106800
-- BOOST_INCLUDE_DIR /Users/izmarverhage/git/vcpkg/installed/x64-osx/include
-- Performing Test HAVE_LLVM_LIBCPP
-- Performing Test HAVE_LLVM_LIBCPP - Failed
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Looking for floor
-- Looking for floor - found
-- Looking for __infinity
-- Looking for __infinity - not found
-- Looking for __infinity in m
-- Looking for __infinity in m - not found
-- Looking for gethostbyname_r
-- Looking for gethostbyname_r - not found
-- Looking for gethostbyname_r in nsl_r
-- Looking for gethostbyname_r in nsl_r - not found
-- Looking for gethostbyname_r in nsl
-- Looking for gethostbyname_r in nsl - not found
-- Looking for bind
-- Looking for bind - found
-- Looking for crypt
-- Looking for crypt - found
-- Looking for setsockopt
-- Looking for setsockopt - found
-- Looking for dlopen
-- Looking for dlopen - found
-- Looking for sched_yield
-- Looking for sched_yield - found
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Looking for timer_create
-- Looking for timer_create - not found
-- Looking for timer_create in rt
-- Looking for timer_create in rt - not found
-- Looking for atomic_thread_fence
-- Looking for atomic_thread_fence - found
-- Looking for backtrace
-- Looking for backtrace - found
-- Looking for include file alloca.h
-- Looking for include file alloca.h - found
-- Looking for include file arpa/inet.h
-- Looking for include file arpa/inet.h - found
-- Looking for include file dlfcn.h
-- Looking for include file dlfcn.h - found
-- Looking for include file endian.h
-- Looking for include file endian.h - not found
-- Looking for include file execinfo.h
-- Looking for include file execinfo.h - found
-- Looking for include file fpu_control.h
-- Looking for include file fpu_control.h - not found
-- Looking for include file grp.h
-- Looking for include file grp.h - found
-- Looking for include file ieeefp.h
-- Looking for include file ieeefp.h - not found
-- Looking for include file langinfo.h
-- Looking for include file langinfo.h - found
-- Looking for include file malloc.h
-- Looking for include file malloc.h - not found
-- Looking for include file netinet/in.h
-- Looking for include file netinet/in.h - found
-- Looking for include file poll.h
-- Looking for include file poll.h - found
-- Looking for include file pwd.h
-- Looking for include file pwd.h - found
-- Looking for include file strings.h
-- Looking for include file strings.h - found
-- Looking for include file sys/cdefs.h
-- Looking for include file sys/cdefs.h - found
-- Looking for include file sys/ioctl.h
-- Looking for include file sys/ioctl.h - found
-- Looking for include file sys/mman.h
-- Looking for include file sys/mman.h - found
-- Looking for include file sys/resource.h
-- Looking for include file sys/resource.h - found
-- Looking for include file sys/select.h
-- Looking for include file sys/select.h - found
-- Looking for include file sys/socket.h
-- Looking for include file sys/socket.h - found
-- Looking for include files curses.h, term.h
-- Looking for include files curses.h, term.h - found
-- Looking for include file termios.h
-- Looking for include file termios.h - found
-- Looking for include file termio.h
-- Looking for include file termio.h - not found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file sys/wait.h
-- Looking for include file sys/wait.h - found
-- Looking for include file sys/param.h
-- Looking for include file sys/param.h - found
-- Looking for include file fnmatch.h
-- Looking for include file fnmatch.h - found
-- Looking for include file sys/un.h
-- Looking for include file sys/un.h - found
-- Looking for include file vis.h
-- Looking for include file vis.h - found
-- Looking for include file sasl/sasl.h
-- Looking for include file sasl/sasl.h - found
-- Looking for include file sys/devpoll.h
-- Looking for include file sys/devpoll.h - not found
-- Looking for include file sys/epoll.h
-- Looking for include file sys/epoll.h - not found
-- Looking for TAILQ_FOREACH
-- Looking for TAILQ_FOREACH - found
-- Looking for _aligned_malloc
-- Looking for _aligned_malloc - not found
-- Looking for backtrace
-- Looking for backtrace - found
-- Looking for printstack
-- Looking for printstack - not found
-- Looking for index
-- Looking for index - found
-- Looking for chown
-- Looking for chown - found
-- Looking for cuserid
-- Looking for cuserid - not found
-- Looking for directio
-- Looking for directio - not found
-- Looking for ftruncate
-- Looking for ftruncate - found
-- Looking for fchmod
-- Looking for fchmod - found
-- Looking for fcntl
-- Looking for fcntl - found
-- Looking for fdatasync
-- Looking for fdatasync - found
-- Looking for fdatasync
-- Looking for fdatasync - not found
-- Looking for fedisableexcept
-- Looking for fedisableexcept - not found
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for fsync
-- Looking for fsync - found
-- Looking for gethrtime
-- Looking for gethrtime - not found
-- Looking for getnameinfo
-- Looking for getnameinfo - found
-- Looking for getpass
-- Looking for getpass - found
-- Looking for getpassphrase
-- Looking for getpassphrase - not found
-- Looking for getpwnam
-- Looking for getpwnam - found
-- Looking for getpwuid
-- Looking for getpwuid - found
-- Looking for getrlimit
-- Looking for getrlimit - found
-- Looking for getrusage
-- Looking for getrusage - found
-- Looking for initgroups
-- Looking for initgroups - found
-- Looking for issetugid
-- Looking for issetugid - found
-- Looking for getuid
-- Looking for getuid - found
-- Looking for geteuid
-- Looking for geteuid - found
-- Looking for getgid
-- Looking for getgid - found
-- Looking for getegid
-- Looking for getegid - found
-- Looking for madvise
-- Looking for madvise - found
-- Looking for malloc_info
-- Looking for malloc_info - not found
-- Looking for memrchr
-- Looking for memrchr - not found
-- Looking for mlock
-- Looking for mlock - found
-- Looking for mlockall
-- Looking for mlockall - found
-- Looking for mmap64
-- Looking for mmap64 - not found
-- Looking for poll
-- Looking for poll - found
-- Looking for posix_fallocate
-- Looking for posix_fallocate - not found
-- Looking for posix_memalign
-- Looking for posix_memalign - found
-- Looking for pread
-- Looking for pread - found
-- Looking for pthread_condattr_setclock
-- Looking for pthread_condattr_setclock - not found
-- Looking for pthread_sigmask
-- Looking for pthread_sigmask - found
-- Looking for setfd
-- Looking for setfd - not found
-- Looking for sigaction
-- Looking for sigaction - found
-- Looking for sleep
-- Looking for sleep - found
-- Looking for stpcpy
-- Looking for stpcpy - found
-- Looking for stpncpy
-- Looking for stpncpy - found
-- Looking for strlcpy
-- Looking for strlcpy - found
-- Looking for strndup
-- Looking for strndup - found
-- Looking for strlcat
-- Looking for strlcat - found
-- Looking for strsignal
-- Looking for strsignal - found
-- Looking for fgetln
-- Looking for fgetln - found
-- Looking for strsep
-- Looking for strsep - found
-- Looking for tell
-- Looking for tell - not found
-- Looking for vasprintf
-- Looking for vasprintf - found
-- Looking for memalign
-- Looking for memalign - not found
-- Looking for nl_langinfo
-- Looking for nl_langinfo - found
-- Looking for ntohll
-- Looking for ntohll - not found
-- Looking for epoll_create
-- Looking for epoll_create - not found
-- Looking for inet_ntop
-- Looking for inet_ntop - found
-- Looking for kqueue
-- Looking for kqueue - found
-- Looking for timeradd
-- Looking for timeradd - found
-- Looking for timerclear
-- Looking for timerclear - found
-- Looking for timercmp
-- Looking for timercmp - found
-- Looking for timerisset
-- Looking for timerisset - found
-- Looking for include file sys/time.h
-- Looking for include file sys/time.h - found
-- Looking for include file sys/times.h
-- Looking for include file sys/times.h - found
-- Looking for times
-- Looking for times - found
-- Looking for gettimeofday
-- Looking for gettimeofday - found
-- Looking for lrand48
-- Looking for lrand48 - found
-- Looking for TIOCGWINSZ
-- Looking for TIOCGWINSZ - found
-- Looking for FIONREAD
-- Looking for FIONREAD - found
-- Looking for FIONREAD
-- Looking for FIONREAD - found
-- Looking for isinf
-- Looking for isinf - found
-- Performing Test HAVE_CXX_ISINF
-- Performing Test HAVE_CXX_ISINF - Success
-- Looking for timer_create
-- Looking for timer_create - not found
-- Looking for timer_settime
-- Looking for timer_settime - not found
-- Looking for kqueue
-- Looking for kqueue - found
-- Looking for EVFILT_TIMER
-- Looking for EVFILT_TIMER - found
-- Check if the system is big endian
-- Searching 16 bit integer
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Check size of uint8_t
-- Check size of uint8_t - done
-- Check size of uint16_t
-- Check size of uint16_t - done
-- Check size of uint32_t
-- Check size of uint32_t - done
-- Check size of uint64_t
-- Check size of uint64_t - done
-- Check size of char *
-- Check size of char * - done
-- Check size of long
-- Check size of long - done
-- Check size of short
-- Check size of short - done
-- Check size of int
-- Check size of int - done
-- Check size of long long
-- Check size of long long - done
-- Check size of off_t
-- Check size of off_t - done
-- Check size of time_t
-- Check size of time_t - done
-- Check size of ulong
-- Check size of ulong - failed
-- Check size of u_int32_t
-- Check size of u_int32_t - done
-- Check size of socklen_t
-- Check size of socklen_t - done
-- Performing Test HAVE_VISIBILITY_HIDDEN
-- Performing Test HAVE_VISIBILITY_HIDDEN - Success
-- Performing Test HAVE_CLOCK_GETTIME
-- Performing Test HAVE_CLOCK_GETTIME - Success
-- Performing Test HAVE_CLOCK_REALTIME
-- Performing Test HAVE_CLOCK_REALTIME - Success
-- Looking for include files time.h, sys/time.h
-- Looking for include files time.h, sys/time.h - found
-- Looking for O_NONBLOCK
-- Looking for O_NONBLOCK - found
-- Performing Test HAVE_PAUSE_INSTRUCTION
-- Performing Test HAVE_PAUSE_INSTRUCTION - Success
-- Looking for C++ include cxxabi.h
-- Looking for C++ include cxxabi.h - found
-- Performing Test HAVE_ABI_CXA_DEMANGLE
-- Performing Test HAVE_ABI_CXA_DEMANGLE - Success
-- Performing Test HAVE_BUILTIN_UNREACHABLE
-- Performing Test HAVE_BUILTIN_UNREACHABLE - Success
-- Performing Test HAVE_BUILTIN_EXPECT
-- Performing Test HAVE_BUILTIN_EXPECT - Success
-- Performing Test HAVE_BUILTIN_STPCPY
-- Performing Test HAVE_BUILTIN_STPCPY - Success
-- Performing Test HAVE_GCC_ATOMIC_BUILTINS
-- Performing Test HAVE_GCC_ATOMIC_BUILTINS - Success
-- Performing Test HAVE_GCC_SYNC_BUILTINS
-- Performing Test HAVE_GCC_SYNC_BUILTINS - Success
-- Performing Test HAVE_SYS_GETTID
-- Performing Test HAVE_SYS_GETTID - Success
-- Performing Test HAVE_PTHREAD_GETTHREADID_NP
-- Performing Test HAVE_PTHREAD_GETTHREADID_NP - Failed
-- Performing Test HAVE_PTHREAD_THREADID_NP
-- Performing Test HAVE_PTHREAD_THREADID_NP - Success
-- Performing Test HAVE_INTEGER_PTHREAD_SELF
-- Performing Test HAVE_INTEGER_PTHREAD_SELF - Failed
-- Performing Test HAVE_IMPLICIT_DEPENDENT_NAME_TYPING
-- Performing Test HAVE_IMPLICIT_DEPENDENT_NAME_TYPING - Failed
-- Looking for netinet/in6.h
-- Looking for netinet/in6.h - not found
-- Check size of struct in6_addr
-- Check size of struct in6_addr - failed
-- Performing Test HAVE_SOCKADDR_IN_SIN_LEN
-- Performing Test HAVE_SOCKADDR_IN_SIN_LEN - Success
-- Performing Test HAVE_SOCKADDR_IN6_SIN6_LEN
-- Performing Test HAVE_SOCKADDR_IN6_SIN6_LEN - Success
-- Looking for include file numa.h
-- Looking for include file numa.h - not found
-- Looking for include file numaif.h
-- Looking for include file numaif.h - not found
-- NUMA library missing or required version not available
-- Found ZLIB: /Users/izmarverhage/git/vcpkg/installed/x64-osx/debug/lib/libz.a (found version "1.2.11") 
-- Found OpenSSL: /Users/izmarverhage/git/vcpkg/installed/x64-osx/debug/lib/libcrypto.a (found version "1.0.2q")  
-- Check size of mbstate_t
-- Check size of mbstate_t - done
-- Performing Test HAVE_LANGINFO_CODESET
-- Performing Test HAVE_LANGINFO_CODESET - Success
-- Looking for wcsdup
-- Looking for wcsdup - found
-- Check size of wchar_t
-- Check size of wchar_t - done
-- Check size of wint_t
-- Check size of wint_t - done
-- Found Curses: /usr/lib/libcurses.dylib  
-- Performing Test HAVE_DECL_TGOTO
-- Performing Test HAVE_DECL_TGOTO - Success
-- Looking for strvis
-- Looking for strvis - found
-- Looking for strunvis
-- Looking for strunvis - found
-- PATH_TO_LZ4 /Users/izmarverhage/git/vcpkg/installed/x64-osx/include
-- LZ4_LIBRARY /Users/izmarverhage/git/vcpkg/installed/x64-osx/debug/lib/liblz4d.a
-- Looking for lzma_auto_decoder in /Users/izmarverhage/git/vcpkg/installed/x64-osx/debug/lib/liblzma.a
-- Looking for lzma_auto_decoder in /Users/izmarverhage/git/vcpkg/installed/x64-osx/debug/lib/liblzma.a - found
-- Looking for lzma_easy_encoder in /Users/izmarverhage/git/vcpkg/installed/x64-osx/debug/lib/liblzma.a
-- Looking for lzma_easy_encoder in /Users/izmarverhage/git/vcpkg/installed/x64-osx/debug/lib/liblzma.a - found
-- Looking for lzma_lzma_preset in /Users/izmarverhage/git/vcpkg/installed/x64-osx/debug/lib/liblzma.a
-- Looking for lzma_lzma_preset in /Users/izmarverhage/git/vcpkg/installed/x64-osx/debug/lib/liblzma.a - found
-- Found LibLZMA: /Users/izmarverhage/git/vcpkg/installed/x64-osx/include (found version "5.2.4") 
-- Found the following ICU libraries:
--   uc (required)
--   io (required)
--   dt (required)
--   in (required)
--   data (required)
-- Found ICU: /Users/izmarverhage/git/vcpkg/installed/x64-osx/include (found version "61.1") 
-- ICU_MAJOR_VERSION = 61
-- ICU_INCLUDE_DIRS /Users/izmarverhage/git/vcpkg/installed/x64-osx/include
-- ICU_LIBRARIES /Users/izmarverhage/git/vcpkg/installed/x64-osx/debug/lib/libicuuc.a;/Users/izmarverhage/git/vcpkg/installed/x64-osx/debug/lib/libicuio.a;/Users/izmarverhage/git/vcpkg/installed/x64-osx/debug/lib/libicudata.a;/Users/izmarverhage/git/vcpkg/installed/x64-osx/debug/lib/libicui18n.a;/Users/izmarverhage/git/vcpkg/installed/x64-osx/debug/lib/libicudata.a
-- No WITH_CURL has been set. Not using any curl library.
-- CURL_LIBRARY = 
-- CURL_INCLUDE_DIR = 
-- Performing Test HAVE_TAUTOLOGICAL_UNDEFINED_COMPARE
-- Performing Test HAVE_TAUTOLOGICAL_UNDEFINED_COMPARE - Success
-- Configuring incomplete, errors occurred!

config-x64-osx-dbg-err.log:

CMake Deprecation Warning at CMakeLists.txt:52 (CMAKE_POLICY):
  The OLD behavior for policy CMP0045 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

getconf: no such configuration parameter `LEVEL1_DCACHE_LINESIZE'
CMake Error at extra/re2/CMakeLists.txt:74 (ADD_COMPILE_FLAGS):
  Unknown CMake command "ADD_COMPILE_FLAGS".

**Comment by valbendan** [comment]
same thing happened on my machine (macOS 10.15.2)

error log:
```txt
dtrees/libmysql/config-x64-osx-dbg-err.log
CMake Deprecation Warning at CMakeLists.txt:52 (CMAKE_POLICY):
  The OLD behavior for policy CMP0045 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


getconf: no such configuration parameter `LEVEL1_DCACHE_LINESIZE'
CMake Error at extra/re2/CMakeLists.txt:74 (ADD_COMPILE_FLAGS):
  Unknown CMake command "ADD_COMPILE_FLAGS".
```

**Comment by Toxe** [comment]
Hello, I have the same problem.

```
$ ./vcpkg install libmysql
Computing installation plan...
The following packages will be built and installed:
    libmysql[core]:x64-osx
Starting package 1/1: libmysql:x64-osx
Building package libmysql[core]:x64-osx...
-- Using cached /opt/vcpkg/downloads/mysql-mysql-server-mysql-8.0.4.tar.gz
-- Using source at /opt/vcpkg/buildtrees/libmysql/src/ysql-8.0.4-a02d75c4bb
-- Configuring x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: /opt/vcpkg/downloads/tools/cmake-3.14.0-osx/cmake-3.14.0-Darwin-x86_64/CMake.app/Contents/bin/cmake /opt/vcpkg/buildtrees/libmysql/src/ysql-8.0.4-a02d75c4bb -DWITHOUT_SERVER=ON -DWITH_UNIT_TESTS=OFF -DENABLED_PROFILING=OFF -DWIX_DIR=OFF -DHAVE_LLVM_LIBCPP_EXITCODE=1 -DSTACK_DIRECTION=-1 -DWINDOWS_RUNTIME_MD=ON -DIGNORE_BOOST_VERSION=ON -DWITH_SSL=system -DWITH_ICU=system -DWITH_LIBEVENT=system -DWITH_LZMA=system -DWITH_LZ4=system -DWITH_ZLIB=system -DCMAKE_MAKE_PROGRAM=/opt/local/bin/ninja -DCMAKE_SYSTEM_NAME=Darwin -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/opt/vcpkg/scripts/toolchains/osx.cmake -DVCPKG_TARGET_TRIPLET=x64-osx -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/opt/vcpkg/packages/libmysql_x64-osx/debug
    Working Directory: /opt/vcpkg/buildtrees/libmysql/x64-osx-dbg
    Error code: 1
    See logs for more information:
      /opt/vcpkg/buildtrees/libmysql/config-x64-osx-dbg-out.log
      /opt/vcpkg/buildtrees/libmysql/config-x64-osx-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:304 (vcpkg_execute_required_process)
  ports/libmysql/portfile.cmake:38 (vcpkg_configure_cmake)
  scripts/ports.cmake:90 (include)


Error: Building package libmysql:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libmysql:x64-osx
  Vcpkg version: 2020.02.04-unknownhash-external
```

And the contents of `buildtrees/libmysql/config-x64-osx-dbg-err.log`:

```
CMake Deprecation Warning at CMakeLists.txt:52 (CMAKE_POLICY):
  The OLD behavior for policy CMP0045 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


getconf: no such configuration parameter `LEVEL1_DCACHE_LINESIZE'
CMake Error at extra/re2/CMakeLists.txt:74 (ADD_COMPILE_FLAGS):
  Unknown CMake command "ADD_COMPILE_FLAGS".
```

**Comment by Toxe** [comment]
@izzyreal Does this problem still happen for you? It should be fixed by now and this issue can probably be closed.

**Comment by izzyreal** [comment]
@Toxe I'm not working on the related project anymore, but I'm fine closing this.
