### ISSUE TITLE
Add pdal-c

### ISSUE THREAD

**Issue by jimmysoda** [Microsoft/vcpkg#5205]
PDAL now has a C API available at https://github.com/PDAL/CAPI.

**Comment by PhoebeHui** [comment]
Hi jimmysoda,

VCPKG has support pdal-c, you can have a try '.\vcpkg install pdal-c:x64-windows'
...
Building package pdal-c[core]:x64-windows... done
Installing package pdal-c[core]:x64-windows...
Installing package pdal-c[core]:x64-windows... done
Elapsed time for package pdal-c:x64-windows: 18.3 s

Total elapsed time: 10.12 min

Thanks,
Phoebe

**Comment by jimmysoda** [comment]
Thanks @PhoebeHui and @vicroms!
