### ISSUE TITLE
Visual c++ not found

### ISSUE THREAD

**Issue by DigiAngel** [Microsoft/vcpkg#5211]
I see other tickets open...I ran verbose and saw nothing besides the error shown.
![2019-01-22 10_32_04-windows 10 snapshot 1 running - oracle vm virtualbox](https://user-images.githubusercontent.com/947191/51554722-343ba400-1e33-11e9-811f-26398ae99de9.png)

**Comment by MikePelton** [comment]
Hi DigiAngel - if you run this in the Visual Studio 2017 Command console (instead of PowerShell) you'll do better - I suspect the environment variables (e.g. the path to "cc") that point to the compiler etc aren't set up. A file called something like vc_vars.bat is run in the command console and that sets everything up.

**Comment by DigiAngel** [comment]
Thank you.  Sadly this did not appear to be the case.
![2019-01-22 11_51_01-windows 10 snapshot 1 running - oracle vm virtualbox](https://user-images.githubusercontent.com/947191/51558170-0c047300-1e3c-11e9-8e7e-fc93f767ff8f.png)

**Comment by MikePelton** [comment]
Interesting... just to ask the dumb question, does Visual Studio run if you just launch it as an application in its own right? Looks like one of your earlier images is the "Help About" dialog so it probably does, but if I ask this it saves someone else asking the same question! Also, if you type "devenv" in the Developer Command prompt, does that run? If devenv.exe (the Visual Studio executable) is in the path and working, my diagnosis is completely wrong....

**Comment by DigiAngel** [comment]
Well devenv gives me nothing after a full uninstall and reinstall of VS2017 Community edition.  
![2019-01-23 10_26_06-windows 10 snapshot 1 running - oracle vm virtualbox](https://user-images.githubusercontent.com/947191/51625066-7f1fef00-1ef9-11e9-95b2-ff74838aac70.png)

**Comment by PhoebeHui** [comment]
Hi DigiAngel,

Could you have a try below command: they are from ".\VCPKG\src\scripts\bootstrap.ps1",  what's output in your PowerShell, mine is like below. 

PS F:\vcpkg\src> $output = & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -prerelease -legacy -products * -format xml

PS F:\vcpkg\src>  Get-Variable output

Name                           Value
----                           -----
output                         {<?xml version="1.0"?>, <instances>,   <instance>,     <instanceId>xxxxxxxx</instanceId>...}

PS F:\vcpkg\src> [xml]$asXml = $output

PS F:\vcpkg\src>  foreach ($instance in $asXml.instances.instance)
>> {
>>   Get-Variable instance
>> }
>>

Name                           Value
----                           -----
instance                       instance
instance                       instance

Thanks,
Phoebe

**Comment by DigiAngel** [comment]
Thank you...command output:
~~~
Name                           Value
----                           -----
output                         {Visual Studio Locator version 2.5.2+gebb9f26a3d [query version 1.18.21.37008], Copyr...
~~~

**Comment by PhoebeHui** [comment]
Looks similar issue with https://github.com/Microsoft/vcpkg/issues/3881, it try to find vswhere.exe under C:\Program Files (x86)\Microsoft Visual Studio\Installer\. From your output value, it seems that you don't pass the options,  the command simplify: vswhere.exe -prerelease -legacy -products * -format xml

**Comment by DigiAngel** [comment]
I'm going to completely redo this VM in Windows 7....I'll reopen if I run into the same issue...thanks all.
