### ISSUE TITLE
Not clear with cross platform setup

### ISSUE THREAD

**Issue by dan-ryan** [microsoft/vcpkg#5215]
I'm looking to integrate VCPKG into a large C++ project. The documentation isn't exactly clear for my situation. 

We have our main library on Github with uses other libraries of ours on Github (all private).
Our development OS is a Mac. The main IDE is Xcode. This library is integrated into an iOS project. One of the subprojects is also used in a Visual C++ windows project.
We have a Python build script, which spits out a CMake for the various systems we support which include Android and Linux. CircleCI (Linux and Mac servers) run the build script and runs tests, etc. 

A team member should be able to clone these Github projects and able to run them without hassle but able to update the libraries if needed. 

What is the ideal way to get VCPKG integrated?

**Comment by PhoebeHui** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.
