### ISSUE TITLE
openssl uwp builds do not pass WACK

### ISSUE THREAD

**Issue by stammen** [Microsoft/vcpkg#523]
The uwp builds of openssl do not pass Windows App Certification Kit (WACK) . Here is how to reproduce:

1. Install openssl with vcpkg using 
    vcpkg install openssl:x86-uwp

2. Create a new Visual Studio 2015 C++ Blank App (Universal Windows)

3. In MainPage.xaml.cpp add the following header:

    #include <openssl/ssl.h>

4. In MainPage::MainPage()  add the following code:
    
    OpenSSL_add_all_algorithms();

5. Select Release/x86 build configuration

6. Create the x86 app package for the Store and run the Windows App Certification Kit

7. Run the Supported API test

8. Test fails with the following results: (It appears that the openssl dlls are linking against the desktop version of the runtime libs). 

API ??0Object@Platform@@Q$AAA@XZ in vccorlib140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API ?AlignedFree@Heap@Details@Platform@@SAXPAX@Z in vccorlib140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API ?Allocate@Heap@Details@Platform@@SAPAXII@Z in vccorlib140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API ?FlushFactoryCache@@YGXXZ in vccorlib140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API ?Free@Heap@Details@Platform@@SAXPAX@Z in vccorlib140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API ?GetActivationFactoryByPCWSTR@@YGJPAXAAVGuid@Platform@@PAPAX@Z in vccorlib140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API ?GetIBoxArrayVtable@Details@Platform@@YGPAXPAX@Z in vccorlib140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API ?GetIidsFn@@YGJHPAKPBU__s_GUID@@PAPAVGuid@Platform@@@Z in vccorlib140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API ?InitializeData@Details@Platform@@YAJH@Z in vccorlib140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API ?ReleaseTarget@ControlBlock@Details@Platform@@AAEXXZ in vccorlib140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API ?UninitializeData@Details@Platform@@YAXH@Z in vccorlib140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API ?__abi_WinRTraiseAccessDeniedException@@YGXXZ in vccorlib140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API ?__abi_WinRTraiseCOMException@@YGXJ@Z in vccorlib140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API ?__abi_WinRTraiseChangedStateException@@YGXXZ in vccorlib140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API ?__abi_WinRTraiseClassNotRegisteredException@@YGXXZ in vccorlib140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API ?__abi_WinRTraiseDisconnectedException@@YGXXZ in vccorlib140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API ?__abi_WinRTraiseFailureException@@YGXXZ in vccorlib140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API ?__abi_WinRTraiseInvalidArgumentException@@YGXXZ in vccorlib140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API ?__abi_WinRTraiseInvalidCastException@@YGXXZ in vccorlib140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API ?__abi_WinRTraiseNotImplementedException@@YGXXZ in vccorlib140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API ?__abi_WinRTraiseNullReferenceException@@YGXXZ in vccorlib140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API ?__abi_WinRTraiseObjectDisposedException@@YGXXZ in vccorlib140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API ?__abi_WinRTraiseOperationCanceledException@@YGXXZ in vccorlib140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API ?__abi_WinRTraiseOutOfBoundsException@@YGXXZ in vccorlib140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API ?__abi_WinRTraiseOutOfMemoryException@@YGXXZ in vccorlib140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API ?__abi_WinRTraiseWrongThreadException@@YGXXZ in vccorlib140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API ?__abi_translateCurrentException@@YGJ_N@Z in vccorlib140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API __CxxFrameHandler3 in vcruntime140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API __std_type_info_destroy_list in vcruntime140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API _except_handler4_common in vcruntime140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API memchr in vcruntime140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API memcpy in vcruntime140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API memmove in vcruntime140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API memset in vcruntime140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API strchr in vcruntime140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API strrchr in vcruntime140.dll is not supported for this application type. LIBEAY32.dll calls this API.
API GetModuleHandleW in kernel32.dll is not supported for this application type. LIBEAY32.dll calls this API.
API GetStartupInfoW in kernel32.dll is not supported for this application type. LIBEAY32.dll calls this API.
API LoadLibraryExW in kernel32.dll is not supported for this application type. LIBEAY32.dll calls this API.
API UnhandledExceptionFilter in kernel32.dll is not supported for this application type. LIBEAY32.dll calls this API.

**Comment by stammen** [comment]
Fixed in PR https://github.com/Microsoft/vcpkg/pull/524

**Comment by alexkaratarakis** [comment]
Closing fixed issue.
