### ISSUE TITLE
vcpkg export example

### ISSUE THREAD

**Issue by keiichi-morisato** [microsoft/vcpkg#5230]
I would like to request a step-by-step guide on exporting a simple header only, header and DLL bin nuget package.

- Simple header-only file export
- DLL export (if possible both debug and release in same package) with a header-file.

CoApp made this process extremely simple but it is no longer supported and we would like to integrate with Azure Pipelines to push package to our Feed.

**Comment by PhoebeHui** [comment]
See https://devblogs.microsoft.com/cppblog/vcpkg-introducing-export-command/.
