### ISSUE TITLE
Cannot specify specific version of cpprestsdk in cmake.

### ISSUE THREAD

**Issue by cirvine-MSFT** [microsoft/vcpkg#5231]
We are not able to specify the specific version of cpprestsdk required for our build.
e.g.
```
find_package(cpprestsdk 2.10.9 EXACT REQUIRED)
```

From [https://cmake.org/cmake/help/v3.12/command/find_package.html](https://cmake.org/cmake/help/v3.12/command/find_package.html)

>For a candidate package configuration file <config-file>.cmake the corresponding version file is located >next to it and named either <config-file>-version.cmake or <config-file>Version.cmake. If no such version >file is available then the configuration file is assumed to not be compatible with any requested version.

**Comment by wangli28** [comment]
Thanks for posting this issue. Closed as duplicate of #5040.
