### ISSUE TITLE
Add port of ompl (completed)

### ISSUE THREAD

**Issue by jcsantamaria** [microsoft/vcpkg#5234]
I've completed a port of Open Motion Planning Library (OMPL): https://github.com/ompl/ompl 
What is the procedure to submit a pull request?  (I created the branch dev/jcsantamaria/ompl but I cannot push to the repository due to lack of permissions).
Thanks.

**Comment by NancyLi1013** [comment]
Hi @jcsantamaria, thanks for posting this issue. Please refer to the following URL to submit a pull request and hope this will help you.
https://github.com/Microsoft/vcpkg/blob/master/CONTRIBUTING.md
https://github.com/Microsoft/vcpkg/blob/master/docs/examples/packaging-github-repos.md

**Comment by NancyLi1013** [comment]
@jcsantamaria, thanks for your PR #5350.
