### ISSUE TITLE
New Package Suggestion (OpenIGTLInk)

### ISSUE THREAD

**Issue by MarkVabulas** [microsoft/vcpkg#5236]
There is a library called OpenIGTLink with the primary distribution here on github (https://github.com/openigtlink/OpenIGTLink).  It's a niche package, but it integrates easily with things like ITK and VTK, and the build system for it is very cut and dry.

**Comment by NancyLi1013** [comment]
Hi @MarkVabulas, thanks for posting this request. This port has been merged to the master.
