### ISSUE TITLE
qt5-base configure uses wrong $PATH separators

### ISSUE THREAD

**Issue by Dlougach** [Microsoft/vcpkg#5246]
configure_qt uses Windows path separators for PATH environment variable:

`set(ENV{PATH} "$ENV{PATH};${PERL_EXE_PATH}")`

Here there is a semicolon instead of a colon. On my environment this resulted in PATH variable similar to "/usr/local/bin:/usr/bin;/usr/bin", which effectively excluded /usr/bin from search path.

**Comment by Voskrese** [comment]
windows = `;`
set(ENV{PATH} "$ENV{PATH};${PERL_EXE_PATH}")

linux = `:`
set(ENV{PATH} "$ENV{PATH}:${PERL_EXE_PATH}")

**Comment by mauricek** [comment]
As I stumbled over this as well, anyone looking at this?
Otherwise I could have a shot at his during next week.
