### ISSUE TITLE
problem bootstrapping vcpkg as 'system' user (SysWOW64 issue)

### ISSUE THREAD

**Issue by daef** [microsoft/vcpkg#5248]
I'm trying to bootstrap vcpkg as 'Local System' (from a service) - which fails.

It looks like SysWOW64 redirection is messing things up: https://github.com/Microsoft/msbuild/issues/185

Is there any way to use msbuild64 or override env:TMP for the bootstrap process?
(cleanEnvironmentHelper.ps1 seems to undo any environmental changes I try)

edit: removed troubleshooting comments, crossposted issue to https://github.com/Microsoft/msbuild/issues/4107

**Comment by daef** [comment]
Manually executing the same command VERBOSE tells me gets executed seems to work:

```
C:\WINDOWS\system32>"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe" "/p:VCPKG_VERSION=-nohash" "/p:DISABLE_METRICS=0" /p:Configuration=Release /p:Platform=x86 /p:PlatformToolset=v141 /p:TargetPlatformVersion=10.0.17763.0 /p:PreferredToolArchitecture=x64 /verbosity:minimal /m /nologo "C:\ad\vcpkg\toolsrc\dirs.proj"
  pch.cpp
  archives.cpp
  checks.cpp
[...]
```

**Comment by daef** [comment]
https://groups.google.com/forum/#!topic/go-cd/Y8grt9hkrYc seem to have experienced the same problem years ago with go - but no real solution came up...

**Comment by daef** [comment]
setting TMP to another directory and patching cleanEnvironmentHelper.ps1 to ignore the 'tmp' variable seem to do the trick:

```
diff --git a/scripts/cleanEnvironmentHelper.ps1 b/scripts/cleanEnvironmentHelper.ps1
index a3792ecd..ea7fd810 100644
--- a/scripts/cleanEnvironmentHelper.ps1
+++ b/scripts/cleanEnvironmentHelper.ps1
@@ -10,6 +10,9 @@ $nameSet = ($specialEnvironmentMap.Keys + $machineEnvironmentMap.Keys + $userEnv
 # Any environment variable in the $nameSet should be restored to its original value
 foreach ($name in $nameSet)
 {
+    if ($name -eq 'tmp') {
+      continue;
+    }
     if ($specialEnvironmentMap.ContainsKey($name))
     {
         [Environment]::SetEnvironmentVariable($name, $specialEnvironmentMap[$name], 'Process')
```

The path cl tries to access (C:\WINDOWS\system32\config\systemprofile\AppData\Local\Temp\) exists and is writable thou - I don't get the difference

**Comment by ras0219-msft** [comment]
Thanks for posting this issue!

Looking at your comments in the other thread, it seems like the right answer is for us to detect if we are running as the system user and perhaps change the temp environment variable accordingly.

I'd be happy to review a PR for such a feature!

**Comment by damian123** [comment]
Here is a build log that might explain why it does not work, and possibly juggle the brains on someone so this issue can get fixed. Thanks in advance!!
[build.txt](https://github.com/Microsoft/vcpkg/files/2929489/build.txt)

To get this log file I had to do the following:

1. Open a command prompt with admin rights
2. Open a command prompt with the **nt authority\system** user: `psexec -i -s cmd.exe`
3. `git clone https://github.com/Microsoft/vcpkg.git`
4. `"c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\Build\vcvars64.bat"`
5. Edit bootstrap.ps1 to "/verbosity:diag",
6. bootstrap-vcpkg.bat -verbose >c:\temp\build.txt

**Comment by johnzhuacl** [comment]
Looks like keep `TMP` in `cleanEnvironmentHelper.ps1` solve the problem. I am able to build vcpkg in Jenkins which is running under 'nt authority\system`

**Comment by wangli28** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
