### ISSUE TITLE
What is the magic behind vcpkg_test_cmake()?

### ISSUE THREAD

**Issue by joa-quim** [microsoft/vcpkg#5249]
I am trying to write a portfile to a new package. Managed to make it build but can't pass the ``vcpkg_test_cmake(PACKAGE_NAME GMT MODULE)`` step. No matter what I try

```
CMake integration test failed; unable to find_package(GMT MODULE REQUIRED)
```

**Comment by myd7349** [comment]
https://github.com/Microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_test_cmake.cmake

**Comment by joa-quim** [comment]
I also tried to decode that but no way. I think found the issue. My project
produces exes and that is the reason why it fails the consistency check,
but the error message is completely uninformative about it. The only thing
one sees is that all build correctly but the install fails for an obscure
reason.

**Comment by myd7349** [comment]
This should be fixed in https://github.com/microsoft/vcpkg/pull/5574.

**Comment by PhoebeHui** [comment]
vcpkg_test_cmake disabled now, and the error message friendly informed user to remove .exe or debug/include etc. Related to https://github.com/microsoft/vcpkg/blob/master/docs/examples/packaging-zipfiles.md
