### ISSUE TITLE
nlohmann-json doesn't have cmake support

### ISSUE THREAD

**Issue by armedturret** [Microsoft/vcpkg#5253]
I am unable to call the find_package command for the nlohmann-json library in cmake as the portfile for it appears only to copy the header and the license. Is it possible to change the port to use the proper cmake targets?

**Comment by myd7349** [comment]
https://github.com/Microsoft/vcpkg/pull/5095

**Comment by armedturret** [comment]
I'm gonna try to make a PR fixing the package rename issue.

**Comment by SuperWig** [comment]
https://github.com/Microsoft/vcpkg/pull/5258
