### ISSUE TITLE
Error: Building package icu:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by abe4it** [Microsoft/vcpkg#5259]
It seems like the URL is wrong in the cmake. cvpkg can't download the file: http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20181211.tar.xz

Command log:
The following packages will be built and installed:
  * icu[core]:x86-windows
    tesseract[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: icu:x86-windows
Building package icu[core]:x86-windows...
-- Using cached D:/SourceCode/CPP/Extra/OCR/vcpkg/downloads/icu4c-61_1-src.tgz
-- Applying patch D:/SourceCode/CPP/Extra/OCR/vcpkg/ports/icu/disable-escapestr-tool.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/SourceCode/CPP/Extra/OCR/vcpkg/ports/icu/remove-MD-from-configure.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Acquiring MSYS2...
-- Downloading http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20181211.tar.xz...
-- Downloading http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20181211.tar.xz... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:156 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:76 (vcpkg_download_distfile)
  ports/icu/portfile.cmake:75 (vcpkg_acquire_msys)
  scripts/ports.cmake:71 (include)

Error: Building package icu:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x86-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by JackBoos** [comment]
yeah, me too.
consider to create a new PR.

**Comment by nicole9456** [comment]
@abe4it could you do double check the issue? I can't repro it.  This should a server error and it has been fixed. 
I closed the issue, if you still repro it, could you please re-open it? Thanks very much!

**Comment by JackBoos** [comment]
more details:
PS D:\work\vcpkg> .\vcpkg.exe install icu
The following packages will be built and installed:
    icu[core]:x86-windows
Starting package 1/1: icu:x86-windows
Building package icu[core]:x86-windows...
-- Using cached D:/work/vcpkg/downloads/icu4c-61_1-src.tgz
-- Applying patch D:/work/vcpkg/ports/icu/disable-escapestr-tool.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/work/vcpkg/ports/icu/remove-MD-from-configure.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Acquiring MSYS2...
-- Downloading http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20181211.tar.xz...
-- Downloading http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20181211.tar.xz... Failed. Status: 18;"Transferred
 a partial file"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:156 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:76 (vcpkg_download_distfile)
  ports/icu/portfile.cmake:75 (vcpkg_acquire_msys)
  scripts/ports.cmake:71 (include)


Error: Building package icu:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x86-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by abe4it** [comment]
I thought the link was wrong initially in the package. However, it seems like the server is not working during the day time in Pacific Time Zone.
I just tried to download the file manually (using chrome), and I got that "This site can’t be reached".

**Comment by JackBoos** [comment]
@abe4it  It could be a firewall blocking the download request, plz check your network. Maybe you need a VPN or SS?

**Comment by JackBoosY** [comment]
Hi @abe4it , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.

**Comment by PhilLab** [comment]
@JackBoosY As requested, I opened a new issue because this is still / again a problem: #6660
