### ISSUE TITLE
Error building openblas while trying to install Blaze

### ISSUE THREAD

**Issue by sursu** [microsoft/vcpkg#5267]
When I try to install `blaze` via `vcpkg install blaze` I get the following error:

```
Error: Building package openblas:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openblas:x64-linux
  Vcpkg version: 2018.11.23-unknownhash
```
You seem to have had this issue for 1 year: [3000](https://github.com/Microsoft/vcpkg/issues/3000)
Maybe it was solved for Windows.
But, I am on Ubuntu 18.04 and it fails.

**Comment by zhihaoy** [comment]
OpenBLAS has been upgraded in vcpkg ports to 0.3.5, please upgrade the ports tree, and, if that doesn't resolve your issue, please attach the full log.

**Comment by NancyLi1013** [comment]
Hi @sursu , thanks for posting this issue. I can't reproduce it on Ubuntu 16.04. Please feel free to reopen this issue if this is still a problem for you.
