### ISSUE TITLE
winpcap x64 static fails

### ISSUE THREAD

**Issue by johnpyrce** [Microsoft/vcpkg#5268]
-- Performing post-build validation
Expected Debug,Static crt linkage, but the following libs had invalid crt linkage:

    C:/Users/jpyrce/Projects/vcpkg/packages/winpcap_x64-windows-static/debug/lib/Packet.lib: Release,Static
    C:/Users/jpyrce/Projects/vcpkg/packages/winpcap_x64-windows-static/debug/lib/wpcap.lib: Release,Static

To inspect the lib files, use:
    dumpbin.exe /directives mylibfile.lib
Found 1 error(s). Please correct the portfile:
    C:\Users\jpyrce\Projects\vcpkg\ports\winpcap\portfile.cmake
-- Performing post-build validation done
Error: Building package winpcap:x64-windows-static failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: winpcap:x64-windows-static
  Vcpkg version: 2018.11.23-nohash

**Comment by JackBoosY** [comment]
Hi everyone, this issue has been fixed.
Thx,
