### ISSUE TITLE
Add SoLoud

### ISSUE THREAD

**Issue by Skylark13** [microsoft/vcpkg#5281]
Hello, 

I am impressed at how many libraries I use in my hobby projects are already available in vcpkg.
One that is not is SoLoud: http://sol.gfxile.net/soloud/  +  https://github.com/jarikomppa/soloud
It is not built using cmake but should be easy to adapt.

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
