### ISSUE TITLE
cairo: update to 1.16.0

### ISSUE THREAD

**Issue by luzpaz** [Microsoft/vcpkg#5284]
https://cairographics.org/news/cairo-1.16.0/  
https://cairographics.org/releases/cairo-1.16.0.tar.xz

https://github.com/Microsoft/vcpkg/tree/master/ports/cairo

**Comment by NancyLi1013** [comment]
Hi @luzpaz , thanks for posting this issue. Now the package has been updated to the version 1.6.0 on the master. Please take a look.
