### ISSUE TITLE
vcpkg should detect partially installed windows SDK and abort early

### ISSUE THREAD

**Issue by dankegel** [microsoft/vcpkg#5299]
This is rather like https://github.com/Microsoft/vcpkg/issues/4137 except I haven't tried any workarounds yet.  

vcpkg version 2018.11.23-nohash freshly installed on win10,
both on a Win 10 enterprise build 1803 box with vs2015update3 and win sdk 10.0.15063.468
and on a Win 10 Pro version 1803 with vs2017 and win sdk 10.0.15063.674, .17134.12, and .17763.132.
On the vs2017 system, 'vcpkg install boost' and 'vcpkg install graphicsmagick' succeed, yay.
On the vs2015u3 system, either fails trying to install liblzma, unable to find the C compiler 
because rc.exe can't find... something :-(

'vcpkg install liblzma' says

```
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: C:/cygwin64/home/buildbot/xsrc/vcpkg/buildtrees/liblzma/x86-windows-rel/vcpkg-parallel-configure
    See logs for more information:
      C:\cygwin64\home\buildbot\xsrc\vcpkg\buildtrees\liblzma\config-x86-windows-out.log

config-x86-windows-out.log says

-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe -- broken
CMake Error at C:/cygwin64/home/buildbot/xsrc/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/share/cmake-3.12/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/cygwin64/home/buildbot/xsrc/vcpkg/buildtrees/liblzma/x86-windows-rel/CMakeFiles/CMakeTmp

    Run Build Command:"C:/cygwin64/home/buildbot/xsrc/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "cmTC_cf9cc"
    [1/2] Building C object CMakeFiles\cmTC_cf9cc.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_cf9cc.exe
    FAILED: cmTC_cf9cc.exe 
    cmd.exe /C "cd . && C:\cygwin64\home\buildbot\xsrc\vcpkg\downloads\tools\cmake-3.12.4-windows\cmake-3.12.4-win32-x86\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_cf9cc.dir --manifests  -- C:\PROGRA~2\MICROS~1.0\VC\bin\AMD64_~2\link.exe /nologo CMakeFiles\cmTC_cf9cc.dir\testCCompiler.c.obj  /out:cmTC_cf9cc.exe /implib:cmTC_cf9cc.lib /pdb:cmTC_cf9cc.pdb /version:0.0  /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /foCMakeFiles\cmTC_cf9cc.dir/manifest.res CMakeFiles\cmTC_cf9cc.dir/manifest.rc" failed (exit code 0) with the following output:
    The system cannot find the file specified
    ninja: build stopped: subcommand failed.
```

What is rc looking for...?  I mean, I guess it's looking for manifest.res or something, but that error message could be friendlier.  Probably I'm just not living cleanly.

My skill level is essentially zero at vcpkg and visual studio, despite the fact that I've at least superficially used most versions of MS-DOS, Windows and Microsoft C ever released, know x86 assembly pretty well, and have lost large amounts of source code to SourceSafe :-)  My irrational hatred of Microsoft often gets in the way of using their tools.

So, can I buy a clue?  Thanks!

**Comment by Voskrese** [comment]
run shell
where.exe rc.exe

install Win SDK

`where rc`

```
C:\Program Files (x86)\Windows Kits\10\bin\x64\rc.exe
C:\Program Files (x86)\Windows Kits\10\bin\x86\rc.exe
```

**Comment by dankegel** [comment]
Thanks.

```
C:\cygwin64\home\buildbot\xsrc\vcpkg>where rc
C:\Program Files (x86)\Windows Kits\10\bin\10.0.15063.0\x64\rc.exe

C:\cygwin64\home\buildbot\xsrc\vcpkg>vcpkg env --debug --triplet x86-windows
[DEBUG] Using vcpkg-root: C:\cygwin64\home\buildbot\xsrc\vcpkg
[DEBUG] Found path: C:\Program Files\CMake\bin\cmake.exe
[DEBUG] _wpopen(""C:\cygwin64\home\buildbot\xsrc\vcpkg\downloads\tools\cmake-3.12.4-windows\cmake-3.12.4-win32-x86\bin\cmake.exe" --version 2>&1")
[DEBUG] _pclose() returned 0 after    69776 us
[DEBUG] _wpopen(""C:\cygwin64\home\buildbot\xsrc\vcpkg\downloads\tools\cmake-3.12.4-windows\cmake-3.12.4-win32-x86\bin\cmake.exe" "-DCMAKE_TRIPLET_FILE=C:/cygwin64/home/buildbot/xsrc/vcpkg/triplets/x86-windows.cmake" -P "C:/cygwin64/home/buildbot/xsrc/vcpkg/scripts/get_triplet_environment.cmake" 2>&1")
[DEBUG] _pclose() returned 0 after    69572 us
[DEBUG] CreateProcessW(cmd.exe /c ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"  amd64_x86   2>&1 <NUL && cmd")
Microsoft Windows [Version 10.0.17134.523]
(c) 2018 Microsoft Corporation. All rights reserved.
```

As for SDK 8.1, I didn't mention it, but it's already installed:
```
C:\>dir "\Program Files (x86)\Windows Kits\8.1\bin\x86\rc.exe"
 Volume in drive C has no label.
 Volume Serial Number is A868-B52B

 Directory of C:\Program Files (x86)\Windows Kits\8.1\bin\x86

10/24/2014  05:21 PM            75,920 rc.exe
               1 File(s)         75,920 bytes
               0 Dir(s)  226,184,568,832 bytes free
```
It occurred to me that procmon.exe could tell me what rc.exe was upset about, so I tried that... as you suspected, rc.exe is not run.  After digging around for a while, it seems like the first Process Exit with failure was cmake.exe, and right before that, it tried to do CreateFile on ...vcpkg\downloads\tools\ninja\ninja-1.8.2\rc \foCMakeFiles\cmTC_2fa53.dir\manifest.res ...
which looks like cmake brain damage (or win32 newoldthing wizardry); a commandline is
being misparsed, and although the path of interest ends at the space, the whole commandline is being treated as a path.  Several Process Exits with failure follow in relatively quick succession.

According to procmon,
on the failing system, the cmake being run is vcpkgs\downloads\tools\cmake-3.12.4-windows...
but on the system that's working, the cmake being run is c:\Program Files\CMake\cmake.exe, which is 3.13.2.

That's rather freaky.  On the bad system, c:\Program Files\CMake\cmake.exe is 3.11.2.
So I tried installing the latest cmake, 3.13.4.  Alas, that didn't help; even running that, got the same error.

Didn't know what else to look at, so I tried on a second system with visual c++ 2015.
That went even worse.  bootstrap-vcpkg.bat couldn't find rc.exe, even though the win 10 sdk
is installed.   
```
C:> where rc.exe
```
outputs c:\program files (x86)\Windows Kits\10\bin\10.0.15063.0\x64\rc.exe

Is that wrong?

I'm getting the general impression that Visual Studio 2015 is not really supported by vcpkg, is that correct?

**Comment by Voskrese** [comment]
probably the reason is different

but you can change Win SDK through triplet

> set (CMAKE_SYSTEM_VERSION "10.0.17134")

`set (CMAKE_SYSTEM_VERSION "8.1")`

**Comment by dankegel** [comment]
Going by your last reply I suspected that the Windows 10 SDK was incompletely installed.
https://stackoverflow.com/questions/43847542/rc-exe-no-longer-found-in-vs-2015-command-prompt
suggested rerunning setup for visual studio, so I double-clicked 
control panel / programs / Microsoft Visual Studio Professional 2015 with Updates,
chose Modify, Universal Windows App Development Tools, 
checked Windows 10 SDK (10.0.10586),
and clicked Next.  That fixed the second machine.

Trying the first machine now... it takes about half an hour.  Yay microsoft tools!

**Comment by dankegel** [comment]
Fixed the second machine, too.

To sum up:

1) vcpkg seems to require rc.exe to be present in 
```
C:\Program Files (x86)\Windows Kits\10\bin\x64\rc.exe
C:\Program Files (x86)\Windows Kits\10\bin\x86\rc.exe
```

2) it is easy to have a partially installed windows SDK where rc.exe is present but not in that location, and this situation is not a problem for other uses of visual studio

3) vcpkg has failure modes both during bootstrap and while building liblzma (a common dependency) that are fixed by running visual studio's setup and checking the checkbox for a windows sdk (even if it's already there in the filesystem)

4) it would improve usability if the bootstrap batch file and vcpkg itself were more proactive about noticing that rc.exe is not where vcpkg wants it, and providing a very clear diagnostic (e.g. "Suggestion: run visual studio setup to update your installation, and make sure check the checkbox for at least windows 10 sdk is checked")

**Comment by dankegel** [comment]
Thanks to Voskrese for the tips.  I have not tried setting CMAKE_SYSTEM_VERSION but that sounds... useful.

**Comment by PhoebeHui** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.
