### ISSUE TITLE
Package `ogdf` cannot be installed if `coinutils` has been installed first (and viceversa)

### ISSUE THREAD

**Issue by vicroms** [microsoft/vcpkg#5306]
Package `ogdf` embeds `coinutils` library.

If the user has one of them installed, and tries to install the other, the following message appears.
`ogdf` should be modified to detect the presence of `coinutils` and skip embedding the library.

```
The following files are already installed in D:/github/vcpkg/installed/x64-windows and are in conflict with coinutils:x64-windows

    include/coin/CoinAlloc.hpp
    include/coin/CoinBuild.hpp
    .
    .
    .
    include/coin/config_default.h
```

**Comment by Voskrese** [comment]
vcpkg\buildtrees\ogdf\x64-windows-static-dbg>`cmake . -LA`
```

COIN_INSTALL_CMAKE_DIR:STRING=lib/cmake/OGDF
COIN_INSTALL_INCLUDE_DIR:PATH=include
COIN_INSTALL_LIBRARY_DIR:STRING=lib
```

https://github.com/ogdf/ogdf/blob/master/doc/defines.md

The default is COIN_OSI_CLP
But the CLP library is not necessary to install?!

Can remove? and used as a dependency on coinutils
