### ISSUE TITLE
Port Request: Godot engine

### ISSUE THREAD

**Issue by luzpaz** [microsoft/vcpkg#5307]
Build games using the Godot Engine  
https://godotengine.org  
https://godotengine.org/download/windows  
https://github.com/godotengine/godot/releases/tag/3.0.6-stable

**Comment by Calinou** [comment]
Godot isn't meant to be used as a library, so this doesn't make sense to my knowledge.

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
