### ISSUE TITLE
[New port request] blitz, gvdb, osl...

### ISSUE THREAD

**Issue by danilopeixoto** [microsoft/vcpkg#5310]
- [ ] cork
- [x] blitz
- [x] gmp
- [ ] gvdb
- [ ] netgen
- [ ] nglib
- [ ] opentissue
- [ ] optix
- [ ] osl
- [ ] tetgen
- [ ] vega
- [ ] opensubdiv

**Comment by Voskrese** [comment]
link's , preferably under the assembly CMake or MSBuild

**Comment by danilopeixoto** [comment]
cork (https://github.com/gilbo/cork, MSBuild)
blitz (https://github.com/blitzpp/blitz, MSBuild)
field3d (https://github.com/imageworks/Field3D, CMake)
gvdb (https://github.com/NVIDIA/gvdb-voxels, CMake)
materialx (https://github.com/materialx/MaterialX, CMake)
netgen (https://github.com/NGSolve/netgen, CMake)
ngsolve (https://github.com/NGSolve/ngsolve, CMake)
opencolorio (https://github.com/imageworks/OpenColorIO, CMake)
openimageio (https://github.com/OpenImageIO/oiio, CMake)
opensubdiv (https://github.com/PixarAnimationStudios/OpenSubdiv, CMake)
opentissue (https://github.com/erleben/OpenTissue, CMake)
osl (https://github.com/imageworks/OpenShadingLanguage, CMake)
partio (https://github.com/wdas/partio, CMake)
se-expr (https://github.com/wdas/SeExpr, CMake)
tetgen (http://wias-berlin.de/software/tetgen, CMake)
usd (https://github.com/PixarAnimationStudios/USD, CMake)
vega-fem (http://run.usc.edu/vega/download.html, CMake)

**Comment by theblackunknown** [comment]
@danilopeixoto please have a look at #8006 to see if it fits your need

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!

**Comment by virtualritz** [comment]
Why not keep it open until all requested ports have been added? Seems like less work than re-opening and closing it again for each PR?
