### ISSUE TITLE
boost exports incorrect library set when exported with vcpkg export --raw

### ISSUE THREAD

**Issue by byronfa** [microsoft/vcpkg#5321]
When one uses BOOST_DYN_LINK, the library pattern searched for appears to be of the form:
boost_system-vc141-mt-x64-1_69.lib

The only pattern exported via raw export is:
boost_system-vc140-mt.lib

As a result the exported directory is insufficient.

(This was easy for me to miss since I often run integrated..  when integrated visual studio finds the relevant [long/correctly] named lib files buried in vcpkg directory outside of the normal export directory.

**Comment by ByronFaber** [comment]
Doing reading in old issues, I see this is a side-affect of some cmake related choices in the naming of generated the .lib files.  I found this 'feature' trying to use exported binaries out of vcpkg, in a non-cmake project that heavily used BOOST_DYN_LINK.

**Comment by JonLiu1993** [comment]
@ByronFaber ,Thanks for posting this issue,Can you try again with the latest vcpkg and see if the problem persists? If this bug still exists, please provide your reproduction steps

**Comment by PhoebeHui** [comment]
This is by design, see https://github.com/microsoft/vcpkg/issues/601#issuecomment-276220946.
