### ISSUE TITLE
Could not find a package configuration file provided by "libssh"

### ISSUE THREAD

**Issue by Zingam** [Microsoft/vcpkg#5322]
CMake Error at C:/SDKs/vcpkg/scripts/buildsystems/vcpkg.cmake:247 (_find_package):
1> [CMake]   Could not find a package configuration file provided by "libssh" with any
1> [CMake]   of the following names:
1> [CMake] 
1> [CMake]     libsshConfig.cmake
1> [CMake]     libssh-config.cmake
1> [CMake] 
1> [CMake]   Add the installation prefix of "libssh" to CMAKE_PREFIX_PATH or set
1> [CMake]   "libssh_DIR" to a directory containing one of the above files.  If "libssh"
1> [CMake]   provides a separate development package or SDK, be sure it has been
1> [CMake]   installed.

I do clearly see such a file:

<a href="http://tinypic.com?ref=alhvzs" target="_blank"><img src="http://i67.tinypic.com/alhvzs.png" border="0" alt="Image and video hosting by TinyPic"></a>

Do I misunderstand something about how to use find_package or it is an omission?
I use VS2019

**Comment by JackBoosY** [comment]
Hi @Zingam , this issue has been fixed.
Thx.
