### ISSUE TITLE
[New port request] Paraview

### ISSUE THREAD

**Issue by luzpaz** [microsoft/vcpkg#5330]
> ParaView is an open-source, multi-platform data analysis and visualization application. ParaView users can quickly build visualizations to analyze their data using qualitative and quantitative techniques. The data exploration can be done interactively in 3D or programmatically using ParaView’s batch processing capabilities.

Homepage: https://www.paraview.org  
Current Stable: 5.6.0  
Release Notes: Release notes: https://blog.kitware.com/paraview-5-6-0-release-notes/  
Building instructions: https://www.paraview.org/Wiki/ParaView:Build_And_Install

**Comment by JackBoosY** [comment]
Need to add port CGNS first.

**Comment by NancyLi1013** [comment]
It's duplicated to #9180.
