### ISSUE TITLE
port [libffi] not work ASM [x64-windows]

### ISSUE THREAD

**Issue by Voskrese** [Microsoft/vcpkg#5332]
```
win64.S
c1: fatal error C1356: unable to find mspdbcore.dll
Microsoft (R) Macro Assembler (x64) Version 14.14.26429.4
Copyright (C) Microsoft Corporation.  All rights reserved.

 Assembling: win64.asm
win64.asm(1) : error A2088:END directive required at end of file
```

not CL.EXE, **must ML64.EXE**

edit CMakeLists.txt

~~project(libffi ASM C)~~

work x64

```
project(libffi C)
enable_language(ASM_MASM)
```

discussion https://gitlab.kitware.com/cmake/cmake/issues/17532

error **win64.asm(1)** : error A2088:END directive required at end of file

> no find win64.asm

p.s. ver 3.2.1 - 3.3 https://github.com/libffi/libffi/releases

p.p.s Fork that uses the Cmake build system https://github.com/newlawrence/Libffi

> Windows x86 - Microsoft Visual C++ Compiler
> Windows x86-64 - Microsoft Visual C++ Compiler

**Comment by JackBoosY** [comment]
Hi @Voskrese ,
libffi:x64-windows built successful on my VM.
Here is log:

> PS F:\vcpkg> .\vcpkg.exe install libffi:x64-windows
The following packages will be built and installed:
    libffi[core]:x64-windows
Starting package 1/1: libffi:x64-windows
Building package libffi[core]:x64-windows...
-- Using cached F:/vcpkg/downloads/libffi-libffi-v3.1.tar.gz
-- Using source at F:/vcpkg/buildtrees/libffi/src/v3.1-206c189062
-- Applying patch F:/vcpkg/ports/libffi/export-global-data.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package libffi[core]:x64-windows... done
Installing package libffi[core]:x64-windows...
Installing package libffi[core]:x64-windows... done
Elapsed time for package libffi:x64-windows: 20.13 s
\
Total elapsed time: 20.13 s

**Comment by Voskrese** [comment]
hmm... yes, work

Not clear what was the problem apparently with the environment
