### ISSUE TITLE
[New port request] Add libmesh

### ISSUE THREAD

**Issue by luzpaz** [microsoft/vcpkg#5334]
> The libMesh library provides a framework for the numerical simulation of partial differential equations using arbitrary unstructured discretizations on serial and parallel platforms. A major goal of the library is to provide support for adaptive mesh refinement (AMR) computations in parallel while allowing a research scientist to focus on the physics they are modeling. 

> libMesh currently supports 1D, 2D, and 3D steady and transient simulations on a variety of popular geometric and finite element types. The library makes use of high-quality, existing software whenever possible. PETSc or the Trilinos Project are used for the solution of linear systems on both serial and parallel platforms, and LASPack is included with the library to provide linear solver support on serial machines. An optional interface to SLEPc is also provided for solving both standard and generalized eigenvalue problems. 

https://github.com/libMesh/libmesh  
https://github.com/libMesh/libmesh/releases/tag/v1.3.1  
http://libmesh.github.io/installation.html

**Comment by Voskrese** [comment]
does not compile under MSVC
found a good post, gathered successfully

http://hillyuan.blogspot.com/2017/11/build-libmesh-in-windows-under-msys2.html

**Comment by JackBoosY** [comment]
Hi @luzpaz, thanks for reporting this issue.
The port has been added in vcpkg, please update vcpkg and try to build it.

Thanks.
