### ISSUE TITLE
Update hunspell to 1.7.0

### ISSUE THREAD

**Issue by luzpaz** [Microsoft/vcpkg#5335]
https://github.com/hunspell/hunspell/releases/tag/v1.7.0

https://github.com/Microsoft/vcpkg/tree/master/ports/hunspell  
CC @Mixaill

**Comment by NancyLi1013** [comment]
Hi @luzpaz, thanks for posting this issue. The PR has been merged to the master and the package has been updated to 1.7.0. Please take a look.
Thanks.
