### ISSUE TITLE
How to find vcpkg.cmake path automaticaly in build script?

### ISSUE THREAD

**Issue by soroshsabz** [Microsoft/vcpkg#5341]
ITNOA

Hi,

I want to know is there any solution to find vcpkg.cmake path?
I want to write a build script to compile our projects.
In this script I want to use `cmake .. -DCMAKE_TOOLCHAIN_FILE=[vcpkg root]\scripts\buildsystems\vcpkg.cmake`, but my problem is how to find systematic and automatic find [vcpkg root] path? is there any environment variable or any facilities to find vcpkg root path? I want a mechanism like `vswhere.exe` in Visual Studio installer.

thx

**Comment by martin-s** [comment]
I think it depends on the lookup of the .vcpkg-root file. But not 100% sure.
You can also overwrite the root path with the parameter "--vcpkg-root". Keep also in mind that a .vcpkg-root file has to be in the path the parameter points to.

**Comment by soroshsabz** [comment]
@martin-s thanks for replays, but I have some of questions.

* Is vcpkg-root file?
* where is this file?
* how can I use this file?
* how to force vcpkg fill it when install on client?

* I think vcpkg-root is environment variable that user can fill it to change vcpkg root path. but my problem is, I want to find a way to find vcpkg root path autonomous, without any instructions and work by customer/developer in each client.

thx

**Comment by martin-s** [comment]
> 
> 
> @martin-s thanks for replays, but I have some of questions.
> 
>     * Is vcpkg-root file?
>     * where is this file?
https://github.com/Microsoft/vcpkg/blob/master/.vcpkg-root
If the file is missing, I think vcpkg is returning an error.
>     * how can I use this file?
You don't have to use it. It just has to be in the root path.
>     * how to force vcpkg fill it when install on client?
> 
>     * I think vcpkg-root is environment variable that user can fill it to change vcpkg root path. but my problem is, I want to find a way to find vcpkg root path autonomous, without any instructions and work by customer/developer in each client.
vcpkg-root can be set with a parameter or an environment variable. I prefer parameter.
Deploy the vcpkg-root file along with the executable. Then you should be fine. If the executable doesn't find the file, it goes recursively up the folders until it finds one. See https://github.com/Microsoft/vcpkg/blob/26e8a0d3793927307467637d63b105b201ca21d3/toolsrc/src/vcpkg.cpp#L93-L96
> 
> thx

**Comment by soroshsabz** [comment]
@martin-s 

> vcpkg-root can be set with a parameter or an environment variable. I prefer parameter.

My question is why vcpkg does not create environment variable during integration or installation or provide facilities to found it?

I want to use vcpkg.cmake in my own build script for own project, but I do not know how to find it? ( I think it is problem for CI tools and large team.)

thanks

**Comment by martin-s** [comment]
> My question is why vcpkg does not create environment variable during integration or installation or provide facilities to found it?

This is a good question. Do you have looked in C:\Users\<user>\AppData\Local\vcpkg?

**Comment by soroshsabz** [comment]
@martin-s thank you very mush, it is very good answer, I use it for our project very soon, but I still think it is maybe good idea to vcpkg officially provide environment variable or something like `vswhere`.

Did you suggest me to create another issue for feature request about this facilities?

thanks very mush for helping me.

**Comment by martin-s** [comment]
If it helps: 

> where /R c: vcpkg.exe

**Comment by am2222** [comment]
> @martin-s thank you very mush, it is very good answer, I use it for our project very soon, but I still think it is maybe good idea to vcpkg officially provide environment variable or something like `vswhere`.
> 
> Did you suggest me to create another issue for feature request about this facilities?
> 
> thanks very mush for helping me.

I agree, For example if we want to use vcpkg libraries to compile libraries using python setup.py there is a need to find directories and it is not that easy
