### ISSUE TITLE
glfw3

### ISSUE THREAD

**Issue by Kurimatzu** [Microsoft/vcpkg#5344]
vcpkg install glfw3
```
The following packages will be built and installed:
    glfw3[core]:x86-windows
Starting package 1/1: glfw3:x86-windows
Building package glfw3[core]:x86-windows...
-- Using cached C:/vcpkg/vcpkg/downloads/glfw-glfw-3.2.1.tar.gz
-- Using source at C:/vcpkg/vcpkg/buildtrees/glfw3/src/3.2.1-28ab61727b
CMake Error at scripts/cmake/vcpkg_configure_cmake.cmake:113 (message):
  Unable to determine appropriate generator for: -x86-v142
Call Stack (most recent call first):
  ports/glfw3/portfile.cmake:21 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package glfw3:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glfw3:x86-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.
```

**Comment by Voskrese** [comment]
Unable to determine appropriate generator for: -x86 -v142

v142 to 140-141?

**Comment by Kurimatzu** [comment]
> Unable to determine appropriate generator for: -x86 -v142
> 
> v142 to 140-141?

I'm using VS Preview 2019, will it be a problem?

**Comment by Voskrese** [comment]
update vcpkg and try again

**Comment by PhoebeHui** [comment]
@Kurimatzu, the error due to no CMake generator for v142(VS 2019 preview 2.2), it doesn't configure v142 in .\scripts\cmake\vcpkg_configure_cmake.cmake, also need upgrade CMake version to latest version 3.14 to support this.

I installed it successfully when upgraded CMake to 3.14, and added below configuration to vcpkg_configure_cmake.cmake line 113

    elseif(VCPKG_TARGET_ARCHITECTURE MATCHES "x86" AND VCPKG_PLATFORM_TOOLSET MATCHES "v142")
        set(GENERATOR "Visual Studio 16 2019")
        set(ARCH "Win32")
    elseif(VCPKG_TARGET_ARCHITECTURE MATCHES "x64" AND VCPKG_PLATFORM_TOOLSET MATCHES "v142")
        set(GENERATOR "Visual Studio 16 2019")
        set(ARCH "x64")
    elseif(VCPKG_TARGET_ARCHITECTURE STREQUAL "arm" AND VCPKG_PLATFORM_TOOLSET MATCHES "v142")
        set(GENERATOR "Visual Studio 16 2019")
        set(ARCH "ARM")
    elseif(VCPKG_TARGET_ARCHITECTURE STREQUAL "arm64" AND VCPKG_PLATFORM_TOOLSET MATCHES "v142")
        set(GENERATOR "Visual Studio 16 2019")
        set(ARCH "ARM64")
