### ISSUE TITLE
hello am trying to build boost-iostreams using windows x64 triplet from vcpkg i keep getting errors like this:

### ISSUE THREAD

**Issue by Srabiu** [Microsoft/vcpkg#5345]
Am trying to build boost i get stuck with boost-iostreams error, please any help would be greatly appreciated.

Starting package 1/21: boost-iostreams:x64-windows
Building package boost-iostreams[core]:x64-windows...
-- Using cached C:/vcpkg/downloads/boostorg-iostreams-boost-1.69.0.tar.gz
-- Using source at C:/vcpkg/buildtrees/boost-iostreams/src/ost-1.69.0-d55146db23
-- Using cached C:/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: C:/vcpkg/buildtrees/boost-iostreams/x64-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\boost-iostreams\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/boost-iostreams/portfile.cmake:27 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package boost-iostreams:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-iostreams:x64-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by Voskrese** [comment]
See logs for more information:

C:\vcpkg\buildtrees\boost-iostreams\install-x64-windows-dbg-out.log

**Comment by PhoebeHui** [comment]
@Srabiu, could you share C:\vcpkg\buildtrees\boost-iostreams\install-x64-windows-dbg-out.log? I install it successfully now.

Starting package 36/36: boost-iostreams:x64-windows
Building package boost-iostreams[core]:x64-windows...
-- Downloading https://github.com/boostorg/iostreams/archive/boost-1.69.0.tar.gz...
-- Extracting source F:/VCPKG/src/downloads/boostorg-iostreams-boost-1.69.0.tar.gz
-- Applying patch Removeseekpos.patch
-- Using source at F:/VCPKG/src/buildtrees/boost-iostreams/src/ost-1.69.0-d55146db23
-- Using cached F:/VCPKG/src/downloads/boost_LICENSE_1_0.txt
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: F:/VCPKG/src/packages/boost-iostreams_x64-windows/share/boost-iostreams/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-iostreams[core]:x64-windows... done
Installing package boost-iostreams[core]:x64-windows...
Installing package boost-iostreams[core]:x64-windows... done
Elapsed time for package boost-iostreams:x64-windows: 24.31 s

Total elapsed time: 4.046 min

PS F:\vcpkg\src> .\vcpkg version
Vcpkg package management program version 2018.11.23-nohash

**Comment by ulrichard** [comment]
Maybe related to this, in my vcpkg export directory, all other boost dll and pdb files have the correct suffixes  (-vc141-mt-x64-1_69) but the iostream files miss them completely.
The file name is simply: boost_iostreams.dll

**Comment by PhoebeHui** [comment]
@ulrichard, it should be a different issue, the suffixes removed by https://github.com/Microsoft/vcpkg/commit/0e759709ddc7dbad0b881f9f068f1b04b2092773, @McDamon , is there any reason to remove the suffixes of boost-iostream?

**Comment by Srabiu** [comment]
ive rectified the issue: i completely removed boost-iostream and all its dependencies, rebuilt and worked perfectly. from my experience working with vcpkg you may install a package and it fails the next time even on the same portfiles.
