### ISSUE TITLE
Package: zlib:x64-windows

### ISSUE THREAD

**Issue by chenbingrun2008** [Microsoft/vcpkg#5361]
Vcpkg version: 2018.11.23-debug

**Comment by chenbingrun2008** [comment]
D:\Softwares\Python\ThridLibs\vc-packages\vcpkg-master\toolsrc\msbuild.x64.debug
>vcpkg install tesseract:x64-windows
The following packages will be built and installed:
  * giflib[core]:x64-windows
  * icu[core]:x64-windows
  * leptonica[core]:x64-windows
  * libjpeg-turbo[core]:x64-windows
  * liblzma[core]:x64-windows
  * libpng[core]:x64-windows
    tesseract[core]:x64-windows
  * tiff[core]:x64-windows
  * zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/9: zlib:x64-windows
Building package zlib[core]:x64-windows...
A suitable version of git was not found (required v2.20.0). Downloading portable
 git v2.20.0...
Downloading git...
  https://github.com/git-for-windows/git/releases/download/v2.20.0.windows.1/Por
tableGit-2.20.0-32-bit.7z.exe -> D:\Softwares\Python\ThridLibs\vc-packages\vcpkg
-master\downloads\PortableGit-2.20.0-32-bit.7z.exe
Extracting git...
A suitable version of 7zip was not found (required v18.1.0). Downloading portabl
e 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> D:\Softwares\
Python\ThridLibs\vc-packages\vcpkg-master\downloads\7-zip.commandline.18.1.0.nup
kg
Extracting 7zip...
A suitable version of nuget was not found (required v4.6.2). Downloading portabl
e nuget v4.6.2...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v4.6.2/nuget.exe -> D:\Softwares\Py
thon\ThridLibs\vc-packages\vcpkg-master\downloads\nuget.exe
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz...
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz... Failed. Status: 7;"Coul
dn't connect to server"
-- Downloading https://downloads.sourceforge.net/project/libpng/zlib/1.2.11/zlib
-1.2.11.tar.gz...
-- Downloading https://downloads.sourceforge.net/project/libpng/zlib/1.2.11/zlib
-1.2.11.tar.gz... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:156 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/is
sues

Call Stack (most recent call first):
  ports/zlib/portfile.cmake:3 (vcpkg_download_distfile)
  scripts/ports.cmake:71 (include)


Error: Building package zlib:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x64-windows
  Vcpkg version: 2018.11.23-debug

**Comment by JackBoosY** [comment]
Dear @chenbingrun2008 :
My build info here:

> PS E:\vcpkg> .\vcpkg.exe install zlib:x64-windows
The following packages will be built and installed:
    zlib[core]:x64-windows
Starting package 1/1: zlib:x64-windows
Building package zlib[core]:x64-windows...
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz...
-- Applying patch E:/vcpkg/ports/zlib/cmake_dont_build_more_than_needed.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: E:/vcpkg/packages/zlib_x64-windows/share/zlib/copyright
-- Performing CMake integration test
-- Performing post-build validation
-- Performing post-build validation done
Building package zlib[core]:x64-windows... done
Installing package zlib[core]:x64-windows...
Installing package zlib[core]:x64-windows... done
Elapsed time for package zlib:x64-windows: 34.79 s
Total elapsed time: 34.79 s

Download zlib source package from www.zlib.net, not from downloads.sourceforge.net.
Can you update vcpkg and repro it?

**Comment by PhoebeHui** [comment]
The website appears to be back up for now, we can installed it successfully, we will look into a longer-term solution for the problem in the future.
