### ISSUE TITLE
Errors building qt5 modules on linux

### ISSUE THREAD

**Issue by TheScarfix** [microsoft/vcpkg#5362]
Hello,

I have a problem with building the qt5 modules on linux. I fixed the qmake scripts to find qmake on linux and also use make instead of jom but I still can't get the modules to build correctly (include folder stays mostly empty and other problems).

Thanks in advance.

**Comment by JackBoosY** [comment]
Hi @TheScarfix, thanks for reporting this issue!
I've fixed qt5-linux build, please update vcpkg and rebuild qt5.

Thanks.
