### ISSUE TITLE
vtk:x64-windows failed with: BUILD_FAILED fatal error LNK1168

### ISSUE THREAD

**Issue by wanderhappy** [Microsoft/vcpkg#5363]
The following packages will be built and installed:
    vtk[core]:x64-windows
Starting package 1/1: vtk:x64-windows
Building package vtk[core]:x64-windows...
-- Using cached D:/Program Files/vcpkg/downloads/Kitware-VTK-v8.1.0.tar.gz
-- Using source at D:/Program Files/vcpkg/buildtrees/vtk/src/v8.1.0-1e04cd9d51
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: D:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: D:/Program Files/vcpkg/buildtrees/vtk/x64-windows-dbg
    See logs for more information:
      D:\Program Files\vcpkg\buildtrees\vtk\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/vtk/portfile.cmake:174 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package vtk:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: vtk:x64-windows
  Vcpkg version: 2018.11.23-nohash

install-x64-windows-dbg-out.log:
LINK : fatal error LNK1168: cannot open bin\vtkCommonCore-8.1.dll for writing

**Comment by JackBoosY** [comment]
Hi @wanderhappy ,
I haven't received error during build vtk:x64-windows, could you upload the error log "D:\Program Files\vcpkg\buildtrees\vtk\install-x64-windows-dbg-out.log" for tracking?

Here is my log:
> PS E:\vcpkg> .\vcpkg.exe install vtk:x64-windows
The following packages will be built and installed:
    vtk[core]:x64-windows
Starting package 1/1: vtk:x64-windows
Building package vtk[core]:x64-windows...
-- Downloading https://github.com/Kitware/VTK/archive/v8.1.0.tar.gz...
-- Extracting source E:/vcpkg/downloads/Kitware-VTK-v8.1.0.tar.gz
-- Applying patch dont-define-ssize_t.patch
-- Applying patch use-fixed-find-hdf5.patch
-- Applying patch disable-workaround-findhdf5.patch
-- Applying patch fix-find-libproj4.patch
-- Applying patch fix-find-libharu.patch
-- Applying patch fix-find-mysql.patch
-- Applying patch fix-find-odbc.patch
-- Applying patch fix-find-lz4.patch
-- Using source at E:/vcpkg/buildtrees/vtk/src/v8.1.0-1e04cd9d51
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package vtk[core]:x64-windows... done
Installing package vtk[core]:x64-windows...
Installing package vtk[core]:x64-windows... done
Elapsed time for package vtk:x64-windows: 31.02 min
Total elapsed time: 31.02 min

And I noticed your vcpkg verison is low, plz use git or use command "vcpkg upgrade --no-dry-run" to update vcpkg before rebuild.
Thx.

**Comment by wanderhappy** [comment]
sometimes received the error during building x64-windows-dbg and sometimes during building x64-windows-rel. 
[install-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2863095/install-x64-windows-dbg-out.log)
[install-x64-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/2863096/install-x64-windows-rel-out.log)

**Comment by JackBoosY** [comment]
> Thank you for your kind reply @JackBoosY . I have upgraded vcpkg and disabled my anti-virus(MSE), but it still reports build-error. Sometimes received the error during building x64-windows-dbg and sometimes during building x64-windows-rel.
> [install-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2863095/install-x64-windows-dbg-out.log)
> [install-x64-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/2863096/install-x64-windows-rel-out.log)

By reading log, i found at least 3 files not found in path "bin": vtkCommonCore-8.1.dll, vtkIOImage-8.1.dll and vtkFiltersCore-8.1.dll.
This is not a special phenomenon, so I consider that have problem with path "bin\".
Could you remove vtk by using command "vcpkg remove vtk --recuse" and then delete path "vcpkg\buildtrees\vtk\" and try again?

**Comment by wanderhappy** [comment]
vtk is not in the package list and I deleted vtk build files, but still reports error.
[install-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2863261/install-x64-windows-dbg-out.log)

**Comment by JackBoosY** [comment]
@ras0219-msft
Plz have a look. According to these logs, some dlls are built, but some random built fails.

**Comment by Neumann-A** [comment]
@wanderhappy: Maybe a stupid question: How much disk space have you remaining? I ran once into "random" build failures with LLVM when I ran out of disk space while building and the reported errors were not really helping or point in that direction

**Comment by JackBoosY** [comment]
> @wanderhappy: Maybe a stupid question: How much disk space have you remaining? I ran once into "random" build failures with LLVM when I ran out of disk space while building and the reported errors were not really helping or point in that direction

build llvm need at least 40GB disk space. Quite huge huh?

**Comment by wanderhappy** [comment]
> @wanderhappy: Maybe a stupid question: How much disk space have you remaining? I ran once into "random" build failures with LLVM when I ran out of disk space while building and the reported errors were not really helping or point in that direction

35GB left in my disk. Is it enough for VTK?

**Comment by lewning** [comment]
it seems that we got the same question. for me, i cannot open bin\vtkCommonColor-8.2.dll, but it did stay in that folder.Did u solve this problem later?
[install-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/3000062/install-x64-windows-dbg-out.log)
BTW 36GB left in my disk.

**Comment by wanderhappy** [comment]
> it seems that we got the same question. for me, i cannot open bin\vtkCommonColor-8.2.dll, but it did stay in that folder.Did u solve this problem later?
> [install-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/3000062/install-x64-windows-dbg-out.log)
> BTW 36GB left in my disk.
I tried to install vtk this morning, and it works . But still don't know why...

**Comment by LarryIII** [comment]
Thanks for your feedback. I installed vtk:x64-windows successfully with VS 2017 15.9.11, Please try to use latest vcpkg version and reopen a new issue if it stable reproduce this problem for you!
