### ISSUE TITLE
glbinding fails to install

### ISSUE THREAD

**Issue by marcojez** [Microsoft/vcpkg#537]
I get the following error message when I try to install glbinding:

```
-- Performing post-build validation
The following files are placed in
C:/vcpkg/packages/glbinding_x64-windows and
C:/vcpkg/packages/glbinding_x64-windows/debug:

    C:/vcpkg/packages/glbinding_x64-windows/glcontexts.exe
    C:/vcpkg/packages/glbinding_x64-windows/glfunctions.exe
    C:/vcpkg/packages/glbinding_x64-windows/glmeta.exe
    C:/vcpkg/packages/glbinding_x64-windows/glqueries.exe
    C:/vcpkg/packages/glbinding_x64-windows/debug/glcontextsd.exe
    C:/vcpkg/packages/glbinding_x64-windows/debug/glfunctionsd.exe
    C:/vcpkg/packages/glbinding_x64-windows/debug/glmetad.exe
    C:/vcpkg/packages/glbinding_x64-windows/debug/glqueriesd.exe

Files cannot be present in those directories.

Found 1 error(s). Please correct the portfile:
    C:\vcpkg\ports\glbinding\portfile.cmake

```

Am I the only one experiencing this?

**Comment by alexkaratarakis** [comment]
This works for me. Just to be sure, can you (re)try with the following steps:
1) `git pull` to get the latest version
2) Run `scripts\bootstrap.ps1` again. 
3) Use `vcpkg version` to verify that you have at least version v0.0.67. 
4) `vcpkg remove --purge glbinding:x64-windows`
5) `vcpkg install glbinding:x64-windows`

These executables never get built for me, so this is somewhat odd (as opposed to having them build, and then the portfile removes them afterwards, which is prone to race issues if the build does something weird).

**Comment by marcojez** [comment]
Same result after performing the steps you listed. I'll try to investigate further...

**Comment by marcojez** [comment]
I figured out what's happening. Those executables are only built if GLFW is found by CMake (see source/tools/*/CMakeLists.txt). GLFW is not listed as a dependency for glbinding, so it will only break on systems where package glfw3 is present (that's my case).

glbinding's cmake files don't offer the choice to exclude those tools from the build process, so deleting the executables at the end (if they were generated) is probably the only way to solve this issue.
