### ISSUE TITLE
[Feature request] asynchronous download dependencies

### ISSUE THREAD

**Issue by soroshsabz** [microsoft/vcpkg#5378]
ITNOA

I think it is good idea to asynchronous  download dependencies alongside building and installing another dependency. I think it is increasing system utilization, and significantly decreasing dependency installing time.
 
for more motivation of this feature request, Just think of installing a library with more than 20 requirements that each of them has big size.

**Comment by Voskrese** [comment]
There is an interesting project for Windows, a ready project for these needs
The only thing left is to integrate it into vcpkg ;)

https://sourceforge.net/projects/wpkg/

**Comment by PhoebeHui** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.

**Comment by soroshsabz** [comment]
@PhoebeHui Yes I think it is need today and so reopen that, Microsoft must increase the priority of that ;)
