### ISSUE TITLE
invalid crt linkage in building winpcap statically

### ISSUE THREAD

**Issue by felfelche** [Microsoft/vcpkg#5387]
I tried to build `winpcap` using static library with the triplet `x64-windows-static`  but following error occurred:

	Expected Debug,Static crt linkage, but the following libs had invalid crt linkage:
	
		C:/vcpkg/packages/winpcap_x64-windows-static/debug/lib/Packet.lib: Release,Static
		C:/vcpkg/packages/winpcap_x64-windows-static/debug/lib/wpcap.lib: Release,Static
	
	To inspect the lib files, use:
		dumpbin.exe /directives mylibfile.lib
	Found 1 error(s). Please correct the portfile:
		C:\vcpkg\ports\winpcap\portfile.cmake
	-- Performing post-build validation done
	Error: Building package winpcap:x64-windows-static failed with: POST_BUILD_CHECKS_FAILED
	Please ensure you're using the latest portfiles with `.\vcpkg update`, then
	submit an issue at https://github.com/Microsoft/vcpkg/issues including:
	Package: winpcap:x64-windows-static
	Vcpkg version: 2018.11.23-nohash

I need to build library with static mode

**Comment by felfelche** [comment]
This issue is duplicated with #5268

**Comment by JackBoosY** [comment]
Hi everyone, this issue has been fixed.
Thx,
