### ISSUE TITLE
Error: Building package eigen3:x86-uwp failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by rohitdesaidev** [Microsoft/vcpkg#5390]
I am using vcpkg for building hololens spectator view plugin and followed the given steps from 

https://github.com/Microsoft/MixedRealityToolkit/blob/master/SpectatorViewPlugin/README.md

when is try the following step 
https://github.com/Microsoft/MixedRealityToolkit/blob/master/SpectatorViewPlugin/README.md

I get this error 

The following packages will be built and installed:
  * eigen3[core]:x86-uwp
  * libjpeg-turbo[core]:x86-uwp
  * libpng[core]:x86-uwp
    opencv[contrib,core,eigen,flann,jpeg,opengl,png,tiff]:x86-uwp
  * opengl[core]:x86-uwp
  * tiff[core]:x86-uwp
  * zlib[core]:x86-uwp
Additional packages (*) will be modified to complete this operation.
Starting package 1/7: eigen3:x86-uwp
Building package eigen3[core]:x86-uwp...
A suitable version of cmake was not found (required v3.12.4). Downloading portable cmake v3.12.4...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.12.4/cmake-3.12.4-win32-x86.zip -> C:\Users\Rohit\Desktop\unityprojects\Holographic_Space_for_BIM_MixedReality\Virtual_Hologram\vcpkg\downloads\cmake-3.12.4-win32-x86.zip
Extracting cmake...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> C:\Users\Rohit\Desktop\unityprojects\Holographic_Space_for_BIM_MixedReality\Virtual_Hologram\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
A suitable version of nuget was not found (required v4.6.2). Downloading portable nuget v4.6.2...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v4.6.2/nuget.exe -> C:\Users\Rohit\Desktop\unityprojects\Holographic_Space_for_BIM_MixedReality\Virtual_Hologram\vcpkg\downloads\nuget.exe
A suitable version of git was not found (required v2.20.0). Downloading portable git v2.20.0...
Downloading git...
  https://github.com/git-for-windows/git/releases/download/v2.20.0.windows.1/PortableGit-2.20.0-32-bit.7z.exe -> C:\Users\Rohit\Desktop\unityprojects\Holographic_Space_for_BIM_MixedReality\Virtual_Hologram\vcpkg\downloads\PortableGit-2.20.0-32-bit.7z.exe
Extracting git...
-- Downloading https://github.com/eigenteam/eigen-git-mirror/archive/3.3.7.tar.gz...
-- Extracting source C:/Users/Rohit/Desktop/unityprojects/Holographic_Space_for_BIM_MixedReality/Virtual_Hologram/vcpkg/downloads/eigenteam-eigen-git-mirror-3.3.7.tar.gz
-- Using source at C:/Users/Rohit/Desktop/unityprojects/Holographic_Space_for_BIM_MixedReality/Virtual_Hologram/vcpkg/buildtrees/eigen3/src/3.3.7-c0bebf7460
-- Downloading https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip...
-- Configuring x86-uwp
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: C:/Users/Rohit/Desktop/unityprojects/Holographic_Space_for_BIM_MixedReality/Virtual_Hologram/vcpkg/buildtrees/eigen3/x86-uwp-rel/vcpkg-parallel-configure
    See logs for more information:
      C:\Users\Rohit\Desktop\unityprojects\Holographic_Space_for_BIM_MixedReality\Virtual_Hologram\vcpkg\buildtrees\eigen3\config-x86-uwp-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:256 (vcpkg_execute_required_process)
  ports/eigen3/portfile.cmake:11 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package eigen3:x86-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: eigen3:x86-uwp
  Vcpkg version: 2018.11.23-nohash

Note : I also tried with cloning master branch with latest update. but still faces this issue.

**Comment by PhoebeHui** [comment]
@rohitdesaidev, thank you for posting this issue! could you provide "C:\Users\Rohit\Desktop\unityprojects\Holographic_Space_for_BIM_MixedReality\Virtual_Hologram\vcpkg\buildtrees\eigen3\config-x86-uwp-out.log"

I installed eigen3:x86-uwp successfully.
PS F:\vcpkg\src> ./vcpkg install eigen3:x86-uwp
The following packages will be built and installed:
    eigen3[core]:x86-uwp
Starting package 1/1: eigen3:x86-uwp
Building package eigen3[core]:x86-uwp...
-- Using cached F:/VCPKG/src/downloads/eigenteam-eigen-git-mirror-3.3.7.tar.gz
-- Using source at F:/VCPKG/src/buildtrees/eigen3/src/3.3.7-c0bebf7460
-- Configuring x86-uwp
-- Building x86-uwp-dbg
-- Building x86-uwp-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package eigen3[core]:x86-uwp... done
Installing package eigen3[core]:x86-uwp...
Installing package eigen3[core]:x86-uwp... done
Elapsed time for package eigen3:x86-uwp: 2.9 min

Total elapsed time: 2.9 min

The package eigen3:x86-uwp provides CMake targets:

    find_package(Eigen3 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Eigen3::Eigen)

PS F:\vcpkg\src> ./vcpkg version
Vcpkg package management program version 2018.11.23-nohash

**Comment by rohitdesaidev** [comment]
Dear Phoebe,

Thanks for getting back to me, I am attaching the required log file.
Please let me know if you need more information.

Thank you,
Rohit Desai

**Comment by PhoebeHui** [comment]
@rohitdesaidev, i got it, it's failed when config, do you install the UWP workload in Visual studio?

**Comment by rohitdesaidev** [comment]
Hi Phoebe,

Thanks for your reply, I have installed UWP workload in my Visual Studio.
Please find the screenshot below.

Thanks,
Rohit Desai

**Comment by Rosehart** [comment]
Since this is labeled that it "needs-repro". I am also having this issue.

**Comment by Rosehart** [comment]
After reading Rohit's log, I noticed we both have quite long paths. I redid all the steps in a c:/shortpath/ folder and now everything builds as expected. Maybe add a clear error message when paths are too long?

**Comment by LarryIII** [comment]
Thanks let us know the problem was caused by long path. Added reminder in https://github.com/Microsoft/vcpkg/pull/6136
