### ISSUE TITLE
[Port bug]Build itk in x86-windows failed.

### ISSUE THREAD

**Issue by JackBoosY** [Microsoft/vcpkg#5396]
I tried to use command ".\vckpg.exe install itk" to build itk, but failed.
Here is output:

> PS E:\vcpkg> .\vcpkg.exe install itk
The following packages will be built and installed:
    itk[core]:x86-windows
Starting package 1/1: itk:x86-windows
Building package itk[core]:x86-windows...
-- Using cached E:/vcpkg/downloads/InsightSoftwareConsortium-ITK-d92873e33e8a54e933e445b92151191f02feab42.tar.gz
-- Extracting source E:/vcpkg/downloads/InsightSoftwareConsortium-ITK-d92873e33e8a54e933e445b92151191f02feab42.tar.gz
-- Using source at E:/vcpkg/buildtrees/itk/src/1f02feab42-0e31fc5de4
-- Configuring x86-windows-dbg
-- Configuring x86-windows-rel
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: E:/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: E:/vcpkg/buildtrees/itk/x86-windows-dbg
    See logs for more information:
      E:\vcpkg\buildtrees\itk\install-x86-windows-dbg-out.log
Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/itk/portfile.cmake:63 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)
Error: Building package itk:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: itk:x86-windows
  Vcpkg version: 2018.11.23-nohash
Additionally, attach any relevant sections from the log files above.

log:
[install-x86-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2878059/install-x86-windows-dbg-out.log)

Log shows one file(maybe more) cannot find:
> E:\vcpkg\installed\x86-windows\include\double-conversion\double-conversion.h(31): fatal error C1083: Cannot open include file: 'double-conversion/utils.h': No such file or directory

And I found it in source path "buildtrees\itk\ITK\Modules\ThirdParty\DoubleConversion\src\double-conversion". Maybe .cmake has problem.

**Comment by MarkIanHolland** [comment]
https://github.com/Microsoft/vcpkg/pull/5115

**Comment by NancyLi1013** [comment]
This issue should be fixed now. I can install it successfully on my machine. So I close it.
