### ISSUE TITLE
Package Names: libname vs name

### ISSUE THREAD

**Issue by OlafvdSpek** [microsoft/vcpkg#540]
Some packages use the lib prefix, some don't..
Since most (all?) pkgs are libs I think the prefix is redundant and it'd make more sense to drop it everywhere.

**Comment by ras0219-msft** [comment]
It is definitely redundant in general -- we're pretty much only packaging libraries!

However, we've kept it on some packages to keep the experience as familiar as possible for users coming from other platforms with other package managers. Especially if the project calls itself "libXYZ", we wouldn't want to introduce confusion by renaming it to XYZ.

**Comment by OlafvdSpek** [comment]
libbzip2: http://www.bzip.org/

It's not about particular libs though.. the lib prefix is troublesome because in a sorted list, like https://github.com/Microsoft/vcpkg/tree/master/ports,  a lib can now be in two positions, either in the 'normal' position or in the "lib" sub-list.

Other platforms are consistent (internally), either using the lib prefix for all libs or not using the prefix at all.

**Comment by ras0219-msft** [comment]
Yeah, that's true.

We could strip the `lib` prefix for every package but add implicit aliases in all user-facing interfaces for `libX` -> `X`. This would preclude us from properly handling two packages named `X` and `libX`, however that really shouldn't be allowed in general to avoid user confusion.

There may be some libraries that would be negatively impacted by that. I don't know any specific examples personally, but perhaps someone else knows a library that starts (for example) with "liblib" or is short enough to be confusing without the "lib" prefix -- libc++ perhaps, if we could support it as a package.

**Comment by codicodi** [comment]
@ras0219-msft,  libxml2? No one really refers to it without the prefix. Quick search reveals there actually is a (related, but nonetheless different) piece of software calling itself xml2: https://cran.r-project.org/web/packages/xml2/index.html.
Another problematic case might be libiconv. `iconv` is just an API standard, with several implementations out there (libiconv, win-iconv, the one in glibc...).

**Comment by bagong** [comment]
I was just going to make a case for the opposite: most libraries we have here are from the unix world which has rather strict conventions about library naming. And - more importantly - many projects have established build traditions on Windows too, so you know which name to expect and you might already have a (cross-platform) buildsystem using the libraries with their established names. If you rename them all to a consistent 'lib'-free name such, code will get more complex and require more rework than just changing the root-folder to the library. Also in the future vcpkg may well give up it's lib-only policy. If, what I hope, it gets kind of a Windows homebrew, it will be used for more than just building.

**Comment by LilyWangL** [comment]
This issue hasn’t been updated in two year, if it is still an issue, please reopen.
