### ISSUE TITLE
Building package cpprestsdk:x86-windows failed

### ISSUE THREAD

**Issue by Buggynours** [Microsoft/vcpkg#5401]
[config-x86-windows-out.log](https://github.com/Microsoft/vcpkg/files/2880840/config-x86-windows-out.log)
[CMakeOutput.log](https://github.com/Microsoft/vcpkg/files/2880574/CMakeOutput.log)
[CMakeError.log](https://github.com/Microsoft/vcpkg/files/2880584/CMakeError.log)

C:\Applic\vcpkg>vcpkg install cpprestsdk cpprestsdk:x64-windows
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be built and installed:
  * boost-asio[core]:x64-windows
    cpprestsdk[core,websockets]:x86-windows
    cpprestsdk[core,websockets]:x64-windows
  * openssl[core]:x64-windows
  * websocketpp[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/5: cpprestsdk:x86-windows
Building package cpprestsdk[core,websockets]:x86-windows...
-- Using cached C:/Applic/vcpkg/downloads/Microsoft-cpprestsdk-v2.10.6.tar.gz
-- Using source at C:/Applic/vcpkg/buildtrees/cpprestsdk/src/v2.10.6-0e55601d7f
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: C:/Applic/vcpkg/buildtrees/cpprestsdk/x86-windows-rel/vcpkg-parallel-configure
    See logs for more information:
      C:\Applic\vcpkg\buildtrees\cpprestsdk\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:257 (vcpkg_execute_required_process)
  ports/cpprestsdk/portfile.cmake:24 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package cpprestsdk:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cpprestsdk:x86-windows
  Vcpkg version: 2018.10.20-nohash

**Comment by PhoebeHui** [comment]
@Buggynours, thank you for posting this issue, do you install windows SDK 10?

From CMakeError.log, it seems couldn't find ucrtd.lib, it should under the C:\Program Files (x86)\Windows Kits\10\Lib\10.0.xxxxx.0\ucrt\x86 in default if you installed windows sdk 10.

**Comment by Buggynours** [comment]
Le 21/02/2019 à 03:44, Phoebe a écrit :
>
> @Buggynours <https://github.com/Buggynours>, thank you for posting 
> this issue, do you install windows SDK 10?
>
> From CMakeError.log, it seems couldn't find ucrtd.lib, it should under 
> the C:\Program Files (x86)\Windows Kits\10\Lib\10.0.xxxxx.0\ucrt\x86 
> in default if you installed windows sdk 10.
>
Yes, there are five versions xxxxx being 10150, 10240, 10586, 14393, 
17763. Each containing ucrt\arm, arm64, x64 and x86.

There is also a Windows Kits\8.1\lib that does not contain ucrt.

Maybe the compiling process is looking in the wrong directory. Indeed 
when creating a new vs2015 project, it takes by default 8.1 as Target 
Platform Version.

**Comment by LarryIII** [comment]
@Buggynours In fact, there is no ucrtd.lib in windows sdk 8.1, it should be in Windows 10 kits. I think this issue should be resolved if you used the VS 2017.
