### ISSUE TITLE
Thank you for this.

### ISSUE THREAD

**Issue by Briananas** [Microsoft/vcpkg#5402]
I just discovered that there is a thing like vcpkg. I did c++ development only on linux because you can install cpp libs with one command no linking etc needed it gets automated. No this is possible with windows. I just wanted to thank everyone who helped making this. <3

**Comment by PhoebeHui** [comment]
Thank you for the positive feedback! ☺

VCPKG aim to helping people manage C and C++ libraries on Windows, Linux and MacOS. This tool and ecosystem are constantly evolving; your involvement are vital to its success! See more from https://vcpkg.readthedocs.io/en/latest/.
