### ISSUE TITLE
Attack of the Ass Dragon

### ISSUE THREAD

**Issue by cgolchert** [microsoft/vcpkg#5403]
Quite a number of pull request not being addressed.  If the people with write access are overwhelmed maybe it is time for more automation.

Openvdb 6.x:
I have many opened PR now here on vcpkg. I gave my full availability to fix problems if necessary. It is becoming a little bit frustrating to not see any progress...

_Originally posted by @cenit in https://github.com/Microsoft/vcpkg/pull/5265#issuecomment-465327323_

**Comment by vicroms** [comment]
Hi @cgolchert we are actively working on automating the PR review process, it is one of our priorities at the moment. 

There's still some work to be done on our side to make sure that the CI system is reliable and that PR submitters can have access to relevant information regarding their builds. But we hope to have this system working soon.
