### ISSUE TITLE
[Suggestion]Check windows desktop SDK/windows store SDK when building uwp port

### ISSUE THREAD

**Issue by JackBoosY** [microsoft/vcpkg#5406]
When I build libpng with x64-uwp, I received some errors.
Console:

> PS E:\vcpkg> .\vcpkg.exe install libpng:x64-uwp
The following packages will be built and installed:
    libpng[core]:x64-uwp
  \* zlib[core]:x64-uwp
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: zlib:x64-uwp
Building package zlib[core]:x64-uwp...
-- Using cached E:/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch E:/vcpkg/ports/zlib/cmake_dont_build_more_than_needed.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Configuring x64-uwp
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: E:/vcpkg/buildtrees/zlib/x64-uwp-rel/vcpkg-parallel-configure
    See logs for more information:
      E:\vcpkg\buildtrees\zlib\config-x64-uwp-out.log
\
Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:256 (vcpkg_execute_required_process)
  ports/zlib/portfile.cmake:19 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)
\
\
Error: Building package zlib:x64-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x64-uwp
  Vcpkg version: 2018.11.23-nohash
\
Additionally, attach any relevant sections from the log files above.

And log shows:
> CMake Error at CMakeLists.txt:4 (project):
  A Windows Store component with CMake requires both the Windows Desktop SDK
  as well as the Windows Store '10.0' SDK.  Please make sure that you have
  both installed

This issue may occur again because two SDKs are not required to be installed when installing vcpkg and Visual Studio.

So, I recommend displaying this on cmd or powershell instead of log files.

**Comment by PhoebeHui** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.
