### ISSUE TITLE
<mysql/mysql.h> not found

### ISSUE THREAD

**Issue by OlafvdSpek** [Microsoft/vcpkg#541]
`#include <mysql/mysql.h>`

I think this is an upstream issue but on Linux this just works.. on Windows `<mysql.h>` works but the difference is kinda annoying.
Could <mysql/mysql.h> be provided?

**Comment by sdcb** [comment]
If you mysql/mysql.h is expected for everyone, I can make a PR to switch to create a mysql folder.
And libmariadb may not conflicted with mysql.

**Comment by ras0219-msft** [comment]
I think that `mysql/mysql.h` is the desirable path for both packages [1]. We should change this, thanks for bringing it up!

[1] https://www.archlinux.org/packages/extra/i686/libmariadbclient/
