### ISSUE TITLE
vcpkg install boost-asio error 

### ISSUE THREAD

**Issue by NghiaHanoi** [Microsoft/vcpkg#5412]
I have following errors during install boost-asio 
vcpkg install boost-asio error 

Console:
->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
 The  following packages will be built and installed:
    boost-asio[core]:x86-windows
Starting package 1/1: boost-asio:x86-windows
Building package boost-asio[core]:x86-windows...
-- Using cached C:/vcpkg/downloads/boostorg-asio-boost-1.69.0.tar.gz
-- Using source at C:/vcpkg/buildtrees/boost-asio/src/ost-1.69.0-b288466bcf
-- Packaging headers
-- Packaging headers done
-- Using cached C:/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: C:/vcpkg/packages/boost-asio_x86-windows/share/boost-asio/copyright
-- Performing post-build validation
There should be no empty directories in C:/vcpkg/packages/boost-asio_x86-windows
The following empty directories were found:

    C:/vcpkg/packages/boost-asio_x86-windows/include/boost

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/a/dir ${CURRENT_PACKAGES_DIR}/some/other/dir)

Found 1 error(s). Please correct the portfile:
    C:\vcpkg\ports\boost-asio\portfile.cmake
-- Performing post-build validation done
Error: Building package boost-asio:x86-windows failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-asio:x86-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
This folder is empty after run install command:  vcpkg\packages\boost-asio_x86-windows\include\boost
Please help.

**Comment by LarryIII** [comment]
@NghiaHanoi Thanks for your feedback. I installed boost-asio successfully with VS 2017 15.9.11, Please try to use latest vcpkg version and reopen a new issue if it is still a problem for you!
