### ISSUE TITLE
No finder for exiv2, Non-Trivial-Linking, Missing WXMP

### ISSUE THREAD

**Issue by nartes** [Microsoft/vcpkg#5415]
Would be good to providea finder. Since it's hard to manage linking of libexiv2.a easily. It reports WXMP missing. Have no idea what is that. It's good, that out-dated ubuntu containers have something working from repos.

Linux problem, no idea about windows, mac osx.

**Comment by wangli28** [comment]
Hi @nartes, thank you for posting the issue, does the issue still occur? I installed exiv2 successfully with Ubuntu Server 18.04 and VCPKG latest source. Can you provide related log for this issue?

> ~/vcpkg$ ./vcpkg install exiv2
The following packages will be built and installed:
/    exiv2[core]:x64-linux
/  * expat[core]:x64-linux
/  * gettext[core]:x64-linux
/  * libiconv[core]:x64-linux
Additional packages (*) will be modified to complete this operation.
Starting package 1/4: expat:x64-linux
Building package expat[core]:x64-linux...
-- Downloading https://github.com/libexpat/libexpat/archive/R_2_2_6.tar.gz...
......
Building package exiv2[core]:x64-linux... done
Installing package exiv2[core]:x64-linux...
Installing package exiv2[core]:x64-linux... done
Elapsed time for package exiv2:x64-linux: 35.46 s
/
Total elapsed time: 44.83 s
/
The package exiv2:x64-linux provides CMake targets:
/
    find_package(exiv2 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE xmp exiv2lib)
