### ISSUE TITLE
[New port request] simdjson

### ISSUE THREAD

**Issue by myd7349** [Microsoft/vcpkg#5418]
https://github.com/lemire/simdjson

**Comment by lemire** [comment]
If someone wants to work on a pull request, I am willing to help.

**Comment by myd7349** [comment]
Hi! @lemire 

I have created a port for `simdjson` in `vcpkg` the other day. It seems the port do fine on `x64-windows/linux/osx`. But there is something wrong with `ARM` and `x86`. Are these as expected?

**Comment by lemire** [comment]
@myd7349  That's correct. Currently we only support x64. This is explicit in the documentation.

There are plans to support 64-bit ARM in the near future.

Speaking for myself, I have no interesting in supporting legacy 32-bit or 16-bit platforms. It is 64-bit all the way in 2019 for me.

**Comment by myd7349** [comment]
@lemire Thanks for your reply. Maybe we can use `simdjson` via `vcpkg` in a few days. :-)

**Comment by lemire** [comment]
@myd7349 I doubt that we can support UWP at this time.

**Comment by myd7349** [comment]
Hi! @lemire I think I have figured out what happened with `x64-uwp`:

>7>e:\vcpkg\buildtrees\simdjson\src\b2f096a4ff-3604fbb5d0\include\simdjson\numberparsing.h(334): error C4146: unary minus operator applied to unsigned type, result still unsigned (compiling source file E:\vcpkg\buildtrees\simdjson\src\b2f096a4ff-3604fbb5d0\src\stage2_build_tape.cpp) [E:\vcpkg\buildtrees\simdjson\x64-uwp-dbg\src\simdjson.vcxproj]

By changing this line:

```cpp
int64_t signed_answer = negative ? -i : i;
```

to

```cpp
int64_t signed_answer = negative ? -static_cast<int64_t>(i) : static_cast<int64_t>(i);
```

`vcpkg install simdjson:x64-uwp` will success.

Maybe I can create a PR for this.

**Comment by myd7349** [comment]
@lemire Good news! We can use `simdjson` in `vcpkg` from now on.

Thanks for your help to make it work out. Cheers!

**Comment by lemire** [comment]
Please see https://github.com/lemire/simdjson/issues/116
