### ISSUE TITLE
Openssl fails to build in linux

### ISSUE THREAD

**Issue by Paco93** [microsoft/vcpkg#5420]
$ ./vcpkg install openssl
The following packages will be built and installed:
    openssl[core]:x64-linux
  * openssl-unix[core]:x64-linux
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: openssl-unix:x64-linux
Building package openssl-unix[core]:x64-linux...
-- Using cached /home/gennaro/vcpkg/downloads/openssl-1.0.2q.tar.gz
-- Using source at /home/gennaro/vcpkg/buildtrees/openssl-unix/src/1.0.2q-5e90f013d2
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: /home/gennaro/vcpkg/downloads/tools/cmake-3.12.4-linux/cmake-3.12.4-Linux-x86_64/bin/cmake;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: /home/gennaro/vcpkg/buildtrees/openssl-unix/x64-linux-dbg
    See logs for more information:
      /home/gennaro/vcpkg/buildtrees/openssl-unix/install-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/openssl-unix/portfile.cmake:48 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package openssl-unix:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-unix:x64-linux
  Vcpkg version: 2018.11.23-unknownhash

Additionally, attach any relevant sections from the log files above.

Log file install-x64-linux-dbg-err.log reports the following: 
ninja: error: build.ninja:102: lexing error

**Comment by sanxiyn** [comment]
I can't reproduce this.

**Comment by the-j0k3r** [comment]
> I can't reproduce this.

Nor me. Likely a dirty build dir. @Paco93 try running (if nothing in directory is unmerged or you mind getting lost.)

```
git clean -xfd
git reset --hard
git pull --rebase upstream master
```
*upstream - This assume your clone is a fork and its setup to track upstream i.e. this repo 

Then  try compiling again.

**Comment by NancyLi1013** [comment]
Hi @Paco93, thanks for posting this issue. I can't reproduce it on my machine. Please open a new issue if this is still a problem for you.
