### ISSUE TITLE
protobuf 3.6.1.3 build failed in windows platform

### ISSUE THREAD

**Issue by whidbey** [microsoft/vcpkg#5425]
vcpkg.exe install protobuf
vcpkg.exe install protobuf specify the triplet x86/x64 event static also fails

c:\vcpkg>.\vcpkg.exe install protobuf --triplet x86-windows
The following packages will be built and installed:
    protobuf[core]:x86-windows
Starting package 1/1: protobuf:x86-windows
Building package protobuf[core]:x86-windows...
-- Using cached C:/vcpkg/downloads/google-protobuf-v3.6.1.3.tar.gz
-- Using source at C:/vcpkg/buildtrees/protobuf/src/v3.6.1.3-7828b8304d
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12
in32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: C:/vcpkg/buildtrees/protobuf/x86-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\protobuf\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/protobuf/portfile.cmake:57 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package protobuf:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: protobuf:x86-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by myd7349** [comment]
Could you attach the log file mentioned in the error message?

> C:\vcpkg\buildtrees\protobuf\install-x86-windows-dbg-out.log

**Comment by PhoebeHui** [comment]
@whidbey, thank you for posting this issue, could you provide 
C:\vcpkg\buildtrees\protobuf\install-x86-windows-dbg-out.log?

I installed it successfully with VCPKG latest revision and VS2017 15.9.7:

PS F:\VCPKG\src> ./vcpkg install protobuf
The following packages will be built and installed:
    protobuf[core]:x86-windows
Starting package 1/1: protobuf:x86-windows
Building package protobuf[core]:x86-windows...
-- Using cached F:/VCPKG/src/downloads/google-protobuf-v3.6.1.3.tar.gz
-- Using source at F:/VCPKG/src/buildtrees/protobuf/src/v3.6.1.3-7828b8304d
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: F:/VCPKG/src/packages/protobuf_x86-windows/tools/protobuf/protoc.exe
-- Installing: F:/VCPKG/src/packages/protobuf_x86-windows/share/protobuf/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package protobuf[core]:x86-windows... done
Installing package protobuf[core]:x86-windows...
Installing package protobuf[core]:x86-windows... done
Elapsed time for package protobuf:x86-windows: 4.668 min

Total elapsed time: 4.668 min

The package protobuf:x86-windows provides CMake targets:
    find_package(protobuf CONFIG REQUIRED)
    target_link_libraries(main PRIVATE protobuf::libprotoc protobuf::libprotobuf)

**Comment by whidbey** [comment]
I am sorry i using vs2015.and can't find the log as I change to the 3.6.1 works fine for me;

**Comment by whidbey** [comment]
I resovled by edit to 3.6.1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO google/protobuf
    REF v3.6.1
    SHA512  1bc175d24b49de1b1e41eaf39598194e583afffb924c86c8d2e569d935af21874be76b2cbd4d9655a1d38bac3d4cd811de88bc2c72d81bad79115e69e5b0d839
    HEAD_REF master
    PATCHES
        fix-uwp.patch
        disable-lite.patch
        version-rc-msvc.patch
)

**Comment by wangli28** [comment]
Hi @whidbey, latest version is 3.7.1, I installed it successfully with VS2015 and VCPKG latest source. You can update vcpkg and rebuild.

> PS E:\vcpkg> .\vcpkg.exe install protobuf
The following packages will be built and installed:
    protobuf[core]:x86-windows
Starting package 1/1: protobuf:x86-windows
Building package protobuf[core]:x86-windows...
-- Downloading https://github.com/google/protobuf/archive/v3.7.1.tar.gz...
-- Extracting source E:/vcpkg/downloads/google-protobuf-v3.7.1.tar.gz
-- Applying patch fix-uwp.patch
-- Applying patch disable-lite.patch
-- Using source at E:/vcpkg/buildtrees/protobuf/src/v3.7.1-42e34786ef
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: E:/vcpkg/packages/protobuf_x86-windows/tools/protobuf/protoc.exe
-- Installing: E:/vcpkg/packages/protobuf_x86-windows/share/protobuf/copyright
PS E:\vcpkg>

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.

**Comment by whidbey** [comment]
thanks
