### ISSUE TITLE
[New port request] hidapi

### ISSUE THREAD

**Issue by nazar554** [microsoft/vcpkg#5429]
https://github.com/signal11/hidapi

**Comment by NancyLi1013** [comment]
Hi @nazar554  thanks for posting this request. This port has been added to vcpkg. Please try to update vcpkg and use it.

**Comment by kejxu** [comment]
> Hi @nazar554 thanks for posting this request. This port has been added to vcpkg. Please try to update vcpkg and use it.

just adding to the response from @NancyLi1013, the `hidapi` port added was simplified (consumes the `.sln` file for VS build) and only for Windows. `hidapi` on Linux distributions have Debian package distributions already, and adding Linux and MacOS ports into `vcpkg` are still work-in-progress (or work-to-be-planned) for the `hidapi` contributors.
