### ISSUE TITLE
comand failed ninja;-v

### ISSUE THREAD

**Issue by ChrisAmm** [Microsoft/vcpkg#5434]
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: C:/vcpkg/buildtrees/opencv/x86-windows-rel/vcpkg-parallel-configure
    See logs for more information:
      C:\vcpkg\buildtrees\opencv\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:256 (vcpkg_execute_required_process)
  ports/opencv/portfile.cmake:238 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package opencv:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv:x86-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.
PS C:\vcpkg> ./vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

**Comment by ChrisAmm** [comment]
Solution: trying to build in x86. Correct is x64. Forgot to close Environment Variables after adding VCPKG_DEFAULT_TRIPLET and value x64-windows...

**Comment by Voskrese** [comment]
@ChrisAmm 

See logs for more information: 

C:\vcpkg\buildtrees\opencv\config-x86-windows-out.log

**Comment by PhoebeHui** [comment]
@ChrisAmm, thank you for posting this issue, does this issue still occur? could you attach 
C:\vcpkg\buildtrees\opencv\config-x86-windows-out.log?

I can't repro the issue
PS F:\VCPKG\src> ./vcpkg install opencv:x86-windows
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be built and installed:
    opencv[core,eigen,flann,jpeg,opengl,png,tiff]:x86-windows
Starting package 1/1: opencv:x86-windows
Building package opencv[core,eigen,flann,jpeg,opengl,png,tiff]:x86-windows...
-- Using cached F:/VCPKG/src/downloads/opencv-opencv-3.4.3.tar.gz
-- Using source at F:/VCPKG/src/buildtrees/opencv/src/3.4.3-701a6234df
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package opencv[core,eigen,flann,jpeg,opengl,png,tiff]:x86-windows... done
Installing package opencv[core,eigen,flann,jpeg,opengl,png,tiff]:x86-windows...
Installing package opencv[core,eigen,flann,jpeg,opengl,png,tiff]:x86-windows... done
Elapsed time for package opencv:x86-windows: 11.44 min

Total elapsed time: 11.44 min

The package opencv provides CMake integration:
    find_package(OpenCV REQUIRED)
    target_include_directories(main PRIVATE ${OpenCV_INCLUDE_DIRS})
    target_link_libraries(main PRIVATE ${OpenCV_LIBS})

**Comment by LarryIII** [comment]
Thanks for your feedback. I installed opencv successfully with VS 2017 15.9.11, Please try to use latest vcpkg version and reopen a new issue if it is still a problem for you!
