### ISSUE TITLE
unresolved external symbol _jpeg_std_error

### ISSUE THREAD

**Issue by OlafvdSpek** [Microsoft/vcpkg#544]
I've got a static library that uses jpeg, png and more. The lib itself builds fine but apps using the lib fail to link.. does auto-linking not work in such cases?

**Comment by OlafvdSpek** [comment]
I added bz2.lib etc to additional dependencies of the static library but then I get a `LINK : fatal error LNK1181: cannot open input file 'bz2.lib'`

**Comment by ras0219-msft** [comment]
I'm assuming you're using the MSBuild per-project integration (since that is most likely to cause this issue).

Basically, you will need to add the NuGet package to every project in your solution (otherwise we can't trigger the auto-link).

**Comment by OlafvdSpek** [comment]
I'm using user-wide..

Right, it was missing "%(AdditionalDependencies)". Thx
```
2>MainFrm.obj : error LNK2001: unresolved external symbol _DirectSoundCreate@12
2>XCC Mixer.obj : error LNK2001: unresolved external symbol _GdiplusStartup@12
2>XCC Library.lib(virtual_image.obj) : error LNK2001: unresolved external symbol _GdipAlloc@4
```
