### ISSUE TITLE
Openscenegraph: Update to 3.6.3

### ISSUE THREAD

**Issue by luzpaz** [microsoft/vcpkg#5443]
https://github.com/openscenegraph/OpenSceneGraph/releases/tag/OpenSceneGraph-3.6.3

ref: https://github.com/Microsoft/vcpkg/issues/705

**Comment by luzpaz** [comment]
Related:
#4396  
#4183  
#4687  
#5082  
#1544  
#5574

**Comment by wangli28** [comment]
@luzpaz, thanks for posting this issue! Openscenegraph has upgrade to 3.6.3.
