### ISSUE TITLE
Building opencv error

### ISSUE THREAD

**Issue by JoelMontana** [Microsoft/vcpkg#5444]
Error: Building package opencv:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv:x64-windows
  Vcpkg version: 2018.11.23-nohash

**Comment by JoelMontana** [comment]
A restart of my computer could solve the problem.

**Comment by JoelMontana** [comment]
A restart of my computer solved the problem.

**Comment by PhoebeHui** [comment]
Looks the issue solved, close it.
