### ISSUE TITLE
nlopt trying to link debug lib

### ISSUE THREAD

**Issue by radarsat1** [microsoft/vcpkg#5446]
Maybe similar to #4601

I did `vcpkg install nlopt:x64-windows`, which exited with success, and in my project I added `find_package(NLopt CONFIG REQUIRED)` but configuration fails with:

```
CMake Error at C:/Users/sinclairs/projects/vcpkg/installed/x64-windows/share/nlopt/NLoptLibraryDepends.cmake:75 (message):
  The imported target "NLopt::nlopt" references the file

     "C:/Users/sinclairs/projects/vcpkg/installed/debug/lib/nlopt.lib"

  but this file does not exist.  Possible reasons include:```

**Comment by JackBoosY** [comment]
Hi @radarsat1 , thanks for reporting this issue!
I found nothing wrong with using nlopt in x64-Debug/x64-Release.  Did you update vcpkg?

**Comment by Neumann-A** [comment]
> "C:/Users/sinclairs/projects/vcpkg/installed/debug/lib/nlopt.lib"

the triplet is missing. Check the generated configs/targets. I am currently not able to even build nlopt

**Comment by NancyLi1013** [comment]
Hi @radarsat1, I try to use this port and build it on my local. It can be built successfully. Please feel free to reopen this issue if this is still a problem for you.
