### ISSUE TITLE
vcpkg_build_cmake question

### ISSUE THREAD

**Issue by kreuzerkrieg** [Microsoft/vcpkg#5457]
In `vcpkg_build_cmake` function, there is nothing that sets the `PARALLEL_ARG` to anything meaningful like `set(PARALLEL_ARG "-j${PROCS}")`
Is it a bug or somehow, magically, the build will be paralleled?

**Comment by Voskrese** [comment]
ninja -j?
cmake --build -j? .
msbuild /m:?
more

**Comment by kreuzerkrieg** [comment]
> ninja -j?
> cmake --build -j? .
> msbuild /m:?
> more

I dont see `-j` applied, the MSBuild does get the `/m` but no `-j` for `make`/`cmake`, except cases where no parallel build required, then `-j1` applied

**Comment by Voskrese** [comment]
My edits, you can also add \ change scripts for yourself, as you wish

```
    set(PARALLEL_ARG)
    set(NO_PARALLEL_ARG)

    if(_VCPKG_CMAKE_GENERATOR MATCHES "Ninja")
        set(BUILD_ARGS "-v") # verbose output
        set(NO_PARALLEL_ARG "-j1")
    elseif(_VCPKG_CMAKE_GENERATOR MATCHES "Visual Studio")
        set(BUILD_ARGS
            "/p:VCPkgLocalAppDataDisabled=true"
#            "/p:UseIntelMKL=No"
            "/p:UseIntelMKL=Yes"
        )
        set(PARALLEL_ARG "/m")
    elseif(_VCPKG_CMAKE_GENERATOR MATCHES "NMake")
        # No options are currently added for nmake builds
	elseif(_VCPKG_CMAKE_GENERATOR MATCHES "MinGW Makefiles")
		# Example. Help improve.
        set(BUILD_ARGS
            --keep-going -j4 
        )
		set(NO_PARALLEL_ARG
			--keep-going -j1
		)
	elseif(_VCPKG_CMAKE_GENERATOR MATCHES "MSYS Makefiles")
        set(BUILD_ARGS
            --keep-going -j4 
        )
		set(NO_PARALLEL_ARG
			--keep-going -j1
		)
    else()
```

**Comment by kreuzerkrieg** [comment]
Do you mean adding it in your port? If yes, I mean, why not adjust the `vcpkg_build_cmake` function just to do the right thing instead adding this code again and again to the port file

**Comment by Voskrese** [comment]
[vcpkg_build_cmake.cmake.txt](https://github.com/Microsoft/vcpkg/files/2916063/vcpkg_build_cmake.cmake.txt)

**Comment by kreuzerkrieg** [comment]
no `-j` for Ninja. not required?
and why `-j4` for MinGW/MSYS?

**Comment by Voskrese** [comment]
required, required ninja -jN ;)) error compile projects set a multithreaded assembly on some projects

sorry google translate

**Comment by kreuzerkrieg** [comment]
Ok, Ninja takes care of parallel build, no need to add `-jX` to cmake invocation
