### ISSUE TITLE
Building package harfbuzz:x64-linux failed

### ISSUE THREAD

**Issue by Roman-Koshelev** [microsoft/vcpkg#5460]
./vcpkg install harfbuzz:x64-linux
The following packages will be built and installed:
    harfbuzz[core,ucdn]:x64-linux
Starting package 1/1: harfbuzz:x64-linux
Building package harfbuzz[core,ucdn]:x64-linux... 
-- Using cached /home/kosh/vcpkg/downloads/harfbuzz-harfbuzz-1.8.4.tar.gz
-- Using source at /home/kosh/vcpkg/buildtrees/harfbuzz/src/1.8.4-e7fe7a2838
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: /home/kosh/vcpkg/downloads/tools/cmake-3.12.4-linux/cmake-3.12.4-Linux-x86_64/bin/cmake;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: /home/kosh/vcpkg/buildtrees/harfbuzz/x64-linux-dbg
    See logs for more information:
      /home/kosh/vcpkg/buildtrees/harfbuzz/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/harfbuzz/portfile.cmake:59 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package harfbuzz:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: harfbuzz:x64-linux
  Vcpkg version: 2018.11.23-unknownhash

Additionally, attach any relevant sections from the log files above.

[62/63] : && /usr/bin/c++  -fPIC -fno-rtti -fno-exceptions -fno-threadsafe-statics -fdiagnostics-color -g   CMakeFiles/test-buffer-serialize.dir/src/test-buffer-serialize.cc.o  -o test-buffer-serialize -L/usr/lib/gcc/x86_64-linux-gnu/7 -Bsymbolic-functions libharfbuzz.a /home/kosh/vcpkg/installed/x64-linux/debug/lib/libfreetyped.a /home/kosh/vcpkg/installed/x64-linux/debug/lib/libbz2d.a /home/kosh/vcpkg/installed/x64-linux/debug/lib/libpng16d.a /home/kosh/vcpkg/installed/x64-linux/debug/lib/libz.a /home/kosh/vcpkg/installed/x64-linux/debug/lib/libz.a -lgcc -lgcc_s -lc -lgcc -lgcc_s && :
ninja: build stopped: subcommand failed.

~/vcpkg/buildtrees/harfbuzz/x64-linux-dbg$ /usr/bin/c++  -fPIC -fno-rtti -fno-exceptions -fno-threadsafe-statics -fdiagnostics-color -g   CMakeFiles/test-buffer-serialize.dir/src/test-buffer-serialize.cc.o  -o test-buffer-serialize -L/usr/lib/gcc/x86_64-linux-gnu/7 -Bsymbolic-functions libharfbuzz.a /home/kosh/vcpkg/installed/x64-linux/debug/lib/libfreetyped.a /home/kosh/vcpkg/installed/x64-linux/debug/lib/libbz2d.a /home/kosh/vcpkg/installed/x64-linux/debug/lib/libpng16d.a /home/kosh/vcpkg/installed/x64-linux/debug/lib/libz.a /home/kosh/vcpkg/installed/x64-linux/debug/lib/libz.a -lgcc -lgcc_s -lc -lgcc -lgcc_s
(успешное выполнение команды)

**Comment by mauricek** [comment]
The relevant part is above [62/63] indicating a linker error.

FAILED: test-would-substitute
: && /usr/bin/c++  -fPIC -fno-rtti -fno-exceptions -fno-threadsafe-statics -fdiagnostics-color -g   CMakeFiles/test-would-substitute.dir/src/test-would-substitute.cc.o  -o test-would-substitute -L/usr/lib/gc
c/x86_64-linux-gnu/7 -Bsymbolic-functions libharfbuzz.a /home/mkalinow/dev/vcpkg/installed/x64-linux/debug/lib/libfreetyped.a /home/mkalinow/dev/vcpkg/installed/x64-linux/debug/lib/libbz2d.a /home/mkalinow/d
ev/vcpkg/installed/x64-linux/debug/lib/libpng16d.a /home/mkalinow/dev/vcpkg/installed/x64-linux/debug/lib/libz.a /home/mkalinow/dev/vcpkg/installed/x64-linux/debug/lib/libz.a -lgcc -lgcc_s -lc -lgcc -lgcc_s
&& :
/home/mkalinow/dev/vcpkg/installed/x64-linux/debug/lib/libfreetyped.a(autofit.c.o): In function `af_shaper_get_cluster':
/home/mkalinow/dev/vcpkg/buildtrees/freetype/src/2.9.1-7d839e348f/src/autofit/afshaper.c:489: undefined reference to `hb_shape'
/home/mkalinow/dev/vcpkg/buildtrees/freetype/src/2.9.1-7d839e348f/src/autofit/afshaper.c:509: undefined reference to `hb_shape'
collect2: error: ld returned 1 exit status

**Comment by wangli28** [comment]
Hi @Roman-Koshelev, thanks for posting this issue.
I can't reproduce this issue locally, does the issue persist? can you try vcpkg latest revision?

 ./vcpkg install harfbuzz
The following packages will be built and installed:
    harfbuzz[core,ucdn]:x64-linux
    ragel[core]:x64-linux
Additional packages (*) will be modified to complete this operation.
......
Starting package 2/2: harfbuzz:x64-linux
Building package harfbuzz[core,ucdn]:x64-linux...
-- Downloading https://github.com/harfbuzz/harfbuzz/archive/2.5.1.tar.gz...
-- Extracting source /home/vwangli/Lily/vcpkg/downloads/harfbuzz-harfbuzz-2.5.1.tar.gz
-- Applying patch 0001-fix-cmake-export.patch
-- Applying patch 0002-fix-uwp-build.patch
-- Applying patch 0003-remove-broken-test.patch
-- Applying patch find-package-freetype-2.patch
-- Applying patch glib-cmake.patch
-- Using source at /home/vwangli/Lily/vcpkg/buildtrees/harfbuzz/src/2.5.1-0bacf31247
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Installing: /home/vwangli/Lily/vcpkg/packages/harfbuzz_x64-linux/share/harfbuzz/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package harfbuzz[core,ucdn]:x64-linux... done
Installing package harfbuzz[core,ucdn]:x64-linux...
Installing package harfbuzz[core,ucdn]:x64-linux... done
Elapsed time for package harfbuzz:x64-linux: 43.52 s

Total elapsed time: 1.18 min

The package harfbuzz:x64-linux provides CMake targets:

    find_package(harfbuzz CONFIG REQUIRED)
    target_link_libraries(main PRIVATE harfbuzz::harfbuzz)

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
