### ISSUE TITLE
How to build DLL(MT MTD MD MDD) for VS2017?

### ISSUE THREAD

**Issue by ChinaChenMingQuan** [microsoft/vcpkg#5466]
vs2017 c++ dll project, Runtime Library Options have MDD, MD, MTD, MT. but vcpkg build dll Runtime Library Options is unknown. so how to build DLL(MT MTD MD MDD) for VS2017?

From Google Translate.

**Comment by Neumann-A** [comment]
\<arch\>-windows in general builds with dynamic CRT linkage (MD MDD)
\<arch\>-windows-static builds with static CRT linkage (MT MTD)

Information about this can be found in \<vcpkgroot\>/triplets/\<chose_your_triplet\>.cmake where `VCPKGT_CRT_LINKAGE` is set

**Comment by LarryIII** [comment]
See detailed reply from @Neumann-A
