### ISSUE TITLE
install azure-storage-cpp:x64-windows-static failed

### ISSUE THREAD

**Issue by fuocor** [Microsoft/vcpkg#547]
Package: azure-storage-cpp:x64-windows-static
  Vcpkg version: 0.0.66-fd0adc561dd93c2cdf0762eeefa0438537a6760a

Error: building package azure-storage-cpp:x64-windows-static failed

there is a large number of warning C4273 followed by a slew of  error C2491

**Comment by alexkaratarakis** [comment]
Can you post the build logs that failed?
Note that when a build fails, `vcpkg` will show you the full path of the relevant logs.

**Comment by PhoebeHui** [comment]
@fuocor, thank you for posting this issue, please try to install azure-storage-cpp:x64-windows-static with vcpkg latest revision, and please open a new issue if this is still a problem for you.

It installed successfully with VS2017 15.9.7:
Starting package 7/7: azure-storage-cpp:x64-windows-static
Building package azure-storage-cpp[core]:x64-windows-static...
-- Downloading https://github.com/Azure/azure-storage-cpp/archive/v6.0.0.tar.gz...
-- Extracting source F:/VCPKG/src/downloads/Azure-azure-storage-cpp-v6.0.0.tar.gz
-- Applying patch F:/VCPKG/src/ports/azure-storage-cpp/pplx-do-while.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Using source at F:/VCPKG/src/buildtrees/azure-storage-cpp/src/v6.0.0-94994e5b00
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Installing: F:/VCPKG/src/packages/azure-storage-cpp_x64-windows-static/share/azure-storage-cpp/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package azure-storage-cpp[core]:x64-windows-static... done
Installing package azure-storage-cpp[core]:x64-windows-static...
Installing package azure-storage-cpp[core]:x64-windows-static... done
Elapsed time for package azure-storage-cpp:x64-windows-static: 3.846 min

Total elapsed time: 6.715 min
