### ISSUE TITLE
Prometheus-cpp -> CivetWeb::CivetWeb

### ISSUE THREAD

**Issue by datacore-tcastro** [microsoft/vcpkg#5472]
Hi, 

(Machine setup: windows 10 1803, locale eng)
I installed prometheus 0.6.0:

> vcpkg.exe install prometheus-cpp:x64-windows-static

Also looks like it pulls civetweb 1.11
The installs completes fine:

> The package prometheus-cpp:x64-windows-static provides CMake targets:
> 
>     find_package(prometheus-cpp CONFIG REQUIRED)
>     target_link_libraries(main PRIVATE prometheus-cpp::core prometheus-cpp::pull)

On my own project when I try to do exactly those two last lines I have a problem running cmake:

> cmake .. -DCMAKE_GENERATOR_PLATFORM=x64 -DBUILD_TESTS=OFF -DCMAKE_TOOLCHAIN_FILE=G:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static

> CMake Error at G:/vcpkg/scripts/buildsystems/vcpkg.cmake:165 (_add_library):
>   Target "mproj" links to target "CivetWeb::CivetWeb" but the target was not
>   found.  Perhaps a find_package() call is missing for an IMPORTED target, or
>   an ALIAS target is missing?

Looking at the visual studio files it looks like it's trying to link to CivetWeb::CivetWeb.lib as if it were part of the environment, rather than vcpkg install, eg: G:\vcpkg\installed\x64-windows-static\debug\lib\civetweb.lib

Is this behaviour expected?

Thank you!

**Comment by wangli28** [comment]
I add three commands to the last of CMakeLists.txt.
`SET(prometheus-cpp_DIR "E:\\vcpkg\\installed\\x64-windows-static\\share\\prometheus-cpp")`
`find_package(prometheus-cpp CONFIG REQUIRED)`
`target_link_libraries(CMakeProject1 PRIVATE prometheus-cpp::core prometheus-cpp::pull)`
Then I runned cmake and got this error:

> 1> Command line: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe  -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\vwangli\CMakeBuilds\2ad95cd1-4c6a-f83b-8cdd-bf454050a4e4\install\x64-Debug"  -DCMAKE_CXX_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.14.26428/bin/HostX64/x64/cl.exe"  -DCMAKE_C_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.14.26428/bin/HostX64/x64/cl.exe"  -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "E:\vwangli\source\repos\CMakeProject1"
1> Working directory: C:\Users\vwangli\CMakeBuilds\2ad95cd1-4c6a-f83b-8cdd-bf454050a4e4\build\x64-Debug
1> CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
1>   Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
1> Call Stack (most recent call first):
1>   C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake(378): (_FPHSA_FAILURE_MESSAGE)
1>   C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.11/Modules/FindZLIB.cmake(112): (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
1>   C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.11/Modules/CMakeFindDependencyMacro.cmake(48): (find_package)
1>   E:/vcpkg/installed/x64-windows-static/share/prometheus-cpp/prometheus-cpp-config.cmake(29): (find_dependency)
1>   E:\vwangli\source\repos\CMakeProject1\CMakeProject1/CMakeLists.txt(11): (find_package)
1> 
1> 
1> -- Configuring incomplete, errors occurred!
1> See also "C:/Users/vwangli/CMakeBuilds/2ad95cd1-4c6a-f83b-8cdd-bf454050a4e4/build/x64-Debug/CMakeFiles/CMakeOutput.log".
1> See also "C:/Users/vwangli/CMakeBuilds/2ad95cd1-4c6a-f83b-8cdd-bf454050a4e4/build/x64-Debug/CMakeFiles/CMakeError.log".
1> C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe  -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\vwangli\CMakeBuilds\2ad95cd1-4c6a-f83b-8cdd-bf454050a4e4\install\x64-Debug"  -DCMAKE_CXX_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.14.26428/bin/HostX64/x64/cl.exe"  -DCMAKE_C_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.14.26428/bin/HostX64/x64/cl.exe"  -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "E:\vwangli\source\repos\CMakeProject1" returned with exit code: 1
CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.11/Modules/FindZLIB.cmake:112 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.11/Modules/CMakeFindDependencyMacro.cmake:48 (find_package)
  E:/vcpkg/installed/x64-windows-static/share/prometheus-cpp/prometheus-cpp-config.cmake:29 (find_dependency)
  CMakeProject1/CMakeLists.txt:11 (find_package)

**Comment by JackBoosY** [comment]
Hi @datacore-tcastro , thanks for reporting this issue!
The problem is that the _depends_port-config.cmake_ file is **not** generated on other ports that this port depends on, and **no** dependencies are indicated in _prometheus-cpp-config.cmake._ 
We will fix this in the future.
Thanks.

**Comment by datacore-tcastro** [comment]
Hi @JackBoosY, 
looks like civetweb does not have any .cmake files installed at all - so if I manually change the prometheus-cpp-config.cmake to add the dependency it can't find it.
Is this a vcpkg issue or is it specific to prometheus and civetweb? 
If this is specific to those and there is an example fix you can point me at I'm happy to help?
Thanks!

**Comment by JackBoosY** [comment]
Hi @datacore-tcastro , we need to create these missing cmake files, such as:

- port-config.cmake
- port-config-version.cmake
- port-targets.cmake
- port-targets-debug.cmake
- port-targets-release.cmake

You can find some similar cmake files from the path ```vcpkg\installed\triplet\share\```.
Thanks.

**Comment by PhoebeHui** [comment]
@datacore-tcastro, thanks for reporting this issue. PR https://github.com/microsoft/vcpkg/pull/7166 has fixed this issue.
