### ISSUE TITLE
openvdb[tools] wll not build

### ISSUE THREAD

**Issue by cgolchert** [Microsoft/vcpkg#5473]
This might just be that the tools need to be updated for 6.0.x

C:\dev\vcpkg>vcpkg install openvdb[tools] --recurse
The following packages will be built and installed:
    openvdb[core,tools]:x64-windows
Starting package 1/1: openvdb:x64-windows
Building package openvdb[core,tools]:x64-windows...
-- Using cached C:/dev/vcpkg/downloads/AcademySoftwareFoundation-openvdb-v6.0.0.tar.gz
-- Using source at C:/dev/vcpkg/buildtrees/openvdb/src/v6.0.0-26159680da
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: C:/dev/vcpkg/buildtrees/openvdb/x64-windows-rel/vcpkg-parallel-configure
    See logs for more information:
      C:\dev\vcpkg\buildtrees\openvdb\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:256 (vcpkg_execute_required_process)
  ports/openvdb/portfile.cmake:31 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package openvdb:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openvdb:x64-windows
  Vcpkg version: 2018.11.23-nohash

**Comment by PhoebeHui** [comment]
@cgolchert, thank you for posting this issue!
Could you attach 
C:\dev\vcpkg\buildtrees\openvdb\config-x64-windows-out.log and ./buildtrees/openvdb/x64-windows-rel/CMakeFiles/CMakeOutput.log?

**Comment by gheith** [comment]
A similar issue for OpenVDB v6.0.0 might also be happening on Linux Ubuntu 18.04. The relevant error files are attached.

Please advise if more information are needed to help fix this issue.

[config-x64-linux-dbg-err.log](https://github.com/Microsoft/vcpkg/files/2948186/config-x64-linux-dbg-err.log)
[config-x64-linux-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2948187/config-x64-linux-dbg-out.log)

**Comment by cgolchert** [comment]
The system is: Windows - 10.0.17763 - AMD64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe 
Build flags: ;/DWIN32;/D_WINDOWS;/W3;/utf-8;/MP;
Id flags:  

The output was:
0
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

CMakeCCompilerId.c
Microsoft (R) Incremental Linker Version 14.00.24215.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:CMakeCCompilerId.exe 
CMakeCCompilerId.obj 


Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.exe"

Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.obj"

The C compiler identification is MSVC, found in "C:/dev/vcpkg/buildtrees/openvdb/x64-windows-rel/CMakeFiles/3.12.4/CompilerIdC/CMakeCCompilerId.exe"

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
Compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe 
Build flags: ;/DWIN32;/D_WINDOWS;/W3;/utf-8;/GR;/EHsc;/MP;
Id flags:  

The output was:
0
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

CMakeCXXCompilerId.cpp
Microsoft (R) Incremental Linker Version 14.00.24215.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:CMakeCXXCompilerId.exe 
CMakeCXXCompilerId.obj 


Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.exe"

Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.obj"

The CXX compiler identification is MSVC, found in "C:/dev/vcpkg/buildtrees/openvdb/x64-windows-rel/CMakeFiles/3.12.4/CompilerIdCXX/CMakeCXXCompilerId.exe"

Determining if the C compiler works passed with the following output:
Change Dir: C:/dev/vcpkg/buildtrees/openvdb/x64-windows-rel/CMakeFiles/CMakeTmp

Run Build Command:"C:/dev/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "cmTC_5bdd2"
[1/2] Building C object CMakeFiles\cmTC_5bdd2.dir\testCCompiler.c.obj

[2/2] Linking C executable cmTC_5bdd2.exe



Detecting C compiler ABI info compiled with the following output:
Change Dir: C:/dev/vcpkg/buildtrees/openvdb/x64-windows-rel/CMakeFiles/CMakeTmp

Run Build Command:"C:/dev/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "cmTC_ec81f"
[1/2] Building C object CMakeFiles\cmTC_ec81f.dir\CMakeCCompilerABI.c.obj

[2/2] Linking C executable cmTC_ec81f.exe





Detecting C [] compiler features compiled with the following output:
Change Dir: C:/dev/vcpkg/buildtrees/openvdb/x64-windows-rel/CMakeFiles/CMakeTmp

Run Build Command:"C:/dev/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "cmTC_5c0f5"
[1/2] Building C object CMakeFiles\cmTC_5c0f5.dir\feature_tests.c.obj

[2/2] Linking C executable cmTC_5c0f5.exe



    Feature record: C_FEATURE:1c_function_prototypes
    Feature record: C_FEATURE:1c_variadic_macros
Determining if the CXX compiler works passed with the following output:
Change Dir: C:/dev/vcpkg/buildtrees/openvdb/x64-windows-rel/CMakeFiles/CMakeTmp

Run Build Command:"C:/dev/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "cmTC_0091c"
[1/2] Building CXX object CMakeFiles\cmTC_0091c.dir\testCXXCompiler.cxx.obj

[2/2] Linking CXX executable cmTC_0091c.exe



Detecting CXX compiler ABI info compiled with the following output:
Change Dir: C:/dev/vcpkg/buildtrees/openvdb/x64-windows-rel/CMakeFiles/CMakeTmp

Run Build Command:"C:/dev/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "cmTC_97ff1"
[1/2] Building CXX object CMakeFiles\cmTC_97ff1.dir\CMakeCXXCompilerABI.cpp.obj

[2/2] Linking CXX executable cmTC_97ff1.exe





Detecting CXX [] compiler features compiled with the following output:
Change Dir: C:/dev/vcpkg/buildtrees/openvdb/x64-windows-rel/CMakeFiles/CMakeTmp

Run Build Command:"C:/dev/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "cmTC_4164d"
[1/2] Building CXX object CMakeFiles\cmTC_4164d.dir\feature_tests.cxx.obj

[2/2] Linking CXX executable cmTC_4164d.exe



    Feature record: CXX_FEATURE:0cxx_aggregate_default_initializers
    Feature record: CXX_FEATURE:1cxx_alias_templates
    Feature record: CXX_FEATURE:1cxx_alignas
    Feature record: CXX_FEATURE:1cxx_alignof
    Feature record: CXX_FEATURE:1cxx_attributes
    Feature record: CXX_FEATURE:1cxx_attribute_deprecated
    Feature record: CXX_FEATURE:1cxx_auto_type
    Feature record: CXX_FEATURE:1cxx_binary_literals
    Feature record: CXX_FEATURE:1cxx_constexpr
    Feature record: CXX_FEATURE:1cxx_contextual_conversions
    Feature record: CXX_FEATURE:1cxx_decltype
    Feature record: CXX_FEATURE:1cxx_decltype_auto
    Feature record: CXX_FEATURE:0cxx_decltype_incomplete_return_types
    Feature record: CXX_FEATURE:1cxx_default_function_template_args
    Feature record: CXX_FEATURE:1cxx_defaulted_functions
    Feature record: CXX_FEATURE:1cxx_defaulted_move_initializers
    Feature record: CXX_FEATURE:1cxx_delegating_constructors
    Feature record: CXX_FEATURE:1cxx_deleted_functions
    Feature record: CXX_FEATURE:1cxx_digit_separators
    Feature record: CXX_FEATURE:1cxx_enum_forward_declarations
    Feature record: CXX_FEATURE:1cxx_explicit_conversions
    Feature record: CXX_FEATURE:1cxx_extended_friend_declarations
    Feature record: CXX_FEATURE:1cxx_extern_templates
    Feature record: CXX_FEATURE:1cxx_final
    Feature record: CXX_FEATURE:1cxx_func_identifier
    Feature record: CXX_FEATURE:1cxx_generalized_initializers
    Feature record: CXX_FEATURE:1cxx_generic_lambdas
    Feature record: CXX_FEATURE:1cxx_inheriting_constructors
    Feature record: CXX_FEATURE:1cxx_inline_namespaces
    Feature record: CXX_FEATURE:1cxx_lambdas
    Feature record: CXX_FEATURE:1cxx_lambda_init_captures
    Feature record: CXX_FEATURE:1cxx_local_type_template_args
    Feature record: CXX_FEATURE:1cxx_long_long_type
    Feature record: CXX_FEATURE:1cxx_noexcept
    Feature record: CXX_FEATURE:1cxx_nonstatic_member_init
    Feature record: CXX_FEATURE:1cxx_nullptr
    Feature record: CXX_FEATURE:1cxx_override
    Feature record: CXX_FEATURE:1cxx_range_for
    Feature record: CXX_FEATURE:1cxx_raw_string_literals
    Feature record: CXX_FEATURE:1cxx_reference_qualified_functions
    Feature record: CXX_FEATURE:1cxx_return_type_deduction
    Feature record: CXX_FEATURE:1cxx_right_angle_brackets
    Feature record: CXX_FEATURE:1cxx_rvalue_references
    Feature record: CXX_FEATURE:1cxx_sizeof_member
    Feature record: CXX_FEATURE:1cxx_static_assert
    Feature record: CXX_FEATURE:1cxx_strong_enums
    Feature record: CXX_FEATURE:1cxx_template_template_parameters
    Feature record: CXX_FEATURE:1cxx_thread_local
    Feature record: CXX_FEATURE:1cxx_trailing_return_types
    Feature record: CXX_FEATURE:1cxx_unicode_literals
    Feature record: CXX_FEATURE:1cxx_uniform_initialization
    Feature record: CXX_FEATURE:1cxx_unrestricted_unions
    Feature record: CXX_FEATURE:1cxx_user_literals
    Feature record: CXX_FEATURE:1cxx_variable_templates
    Feature record: CXX_FEATURE:1cxx_variadic_macros
    Feature record: CXX_FEATURE:1cxx_variadic_templates

**Comment by cgolchert** [comment]
[CMakeOutput.log](https://github.com/Microsoft/vcpkg/files/2948959/CMakeOutput.log)

**Comment by JackBoosY** [comment]
@cgolchert  Sorry, I need you to attach file “**C:\dev\vcpkg\buildtrees\openvdb\config-x64-windows-out.log**”. 
Thanks.

**Comment by cgolchert** [comment]
[config-x64-windows-out.log](https://github.com/Microsoft/vcpkg/files/3010286/config-x64-windows-out.log)

**Comment by cgolchert** [comment]
[config-x64-windows-out.log](https://github.com/Microsoft/vcpkg/files/3010293/config-x64-windows-out.log)

**Comment by Cheney-W** [comment]
This issue should be fixed by PR:https://github.com/Microsoft/vcpkg/pull/6028, so close this issue.
