### ISSUE TITLE
smpeg2 win64 fails to build

### ISSUE THREAD

**Issue by cjvaijo** [Microsoft/vcpkg#5475]
**Output from command:**
 vcpkg.exe install smpeg2
The following packages will be built and installed:
    smpeg2[core]:x64-windows
Starting package 1/1: smpeg2:x64-windows
Building package smpeg2[core]:x64-windows...
-- Downloading https://www.libsdl.org/projects/smpeg/release/smpeg2-2.0.0.tar.gz...
-- Applying patch E:/Code/vcpkg/ports/smpeg2/correct-sdl-headers-dir.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: E:/Code/vcpkg/buildtrees/smpeg2/x64-windows-dbg
    See logs for more information:
      E:\Code\vcpkg\buildtrees\smpeg2\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/smpeg2/portfile.cmake:24 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package smpeg2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: smpeg2:x64-windows
  Vcpkg version: 2018.11.23-nohash

**Referenced log file attached. Highlights:**
E:\Code\vcpkg\buildtrees\smpeg2\src\smpeg2-2.0.0\audio\MPEGaudio.cpp(170): error C2660: 'SDL_CreateThread': function does not take 3 arguments

e:\code\vcpkg\installed\x64-windows\include\sdl2\SDL_stdinc.h(163): error C2365: 'SDL_FALSE': redefinition; previous definition was 'enumerator'
e:\code\vcpkg\installed\x64-windows\include\sdl2\SDL_stdinc.h(409): warning C4273: 'isdigit': inconsistent dll linkage
e:\code\vcpkg\installed\x64-windows\include\sdl2\SDL_stdinc.h(340): error C2371: 'SDL_DUMMY_ENUM': redefinition; different basic types
...
[install-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2911629/install-x64-windows-dbg-out.log)

**Comment by vicroms** [comment]
Hi @cjvaijo 

I have an outstanding PR that fixes the issues in `smpeg2` (#5459).

Unfortunately it is bundled with a bunch of other changes; if you would like to take a look at the fixes here are the relevant commits.

* [Fix SDL headers.](https://github.com/Microsoft/vcpkg/pull/5459/commits/1c53e90563fc2fa72902517aa9988c340b9c8eff)
* [Fix invalid types comparison for some platforms.](https://github.com/Microsoft/vcpkg/pull/5459/commits/23393370757cd7f67c6fac5446b8d0c8eb984a06)

**Comment by cjvaijo** [comment]
Hi @vicroms 

Thanks for your patches; smpeg2 builds successfully in both x64 and x86 with them applied.

**Comment by vicroms** [comment]
Fix has been merged with master, so I'm closing this issue now.
