### ISSUE TITLE
qt5-base opengl error on configure Debian 9.8.0

### ISSUE THREAD

**Issue by ZeroAbility** [microsoft/vcpkg#5480]
qt5-base[core] : x64-linux version 2018.11.23-unknownhash

During configure step the OpenGL test fails (ES2 related). Adding "-no-opengl" to line 97 of the portfile.cmake in vcpkg/ports/qt5-base seems to suppress the error. Similar issues were reported [here](https://stackoverflow.com/questions/41555492/compiling-qt-on-linux-mint-the-opengl-functionality-test-failed) during a normal configure, not specific to vcpkg. Since the Linux specific condition starting on  line 91 only includes CORE_OPTIONS parameter, then it may be related to Qt5 requirements [here](https://doc.qt.io/qt-5/linux.html). If that is the case, it should probably warn the user to install the dependencies (especially mesa libs). Installing libgl1-mesa-dev package allows the configure to complete without error. It might also make sense to consider a mesa port from their [source](https://www.mesa3d.org/repository.html). There doesn't appear to be one.

**Comment by Voskrese** [comment]
https://github.com/Microsoft/vcpkg/issues/3484#issuecomment-398718248

Need to do port

**Comment by ZeroAbility** [comment]
This didn't seem to be an issue on Debian 10. Could probably be closed unless there are other reports.

**Comment by Voskrese** [comment]
@ZeroAbility 
Mesa3D port in the development
https://github.com/microsoft/vcpkg/pull/9966/files

**Comment by JackBoosY** [comment]
cc @Neumann-A

**Comment by Neumann-A** [comment]
@JackBoosY. No need to CC me. vcpkg needs to first figure out how to deal with system libraries on a port basis. Until then there is nothing to do here. Newer Linux distros probably need/use `libgvnd` instead of `mesa` since it is vendor neutral.

**Comment by ZeroAbility** [comment]
This version of Debian is EOL. If there are no other related issues, this can probably be closed.
