### ISSUE TITLE
Could not find a matching pdb file for

### ISSUE THREAD

**Issue by martin-s** [microsoft/vcpkg#5489]
See issue #1766 and #587. It's a brand new repo clone.
If dumpbin.exe prints localized message, script fails to find pdb files:

> -- Warning: Could not find a matching pdb file for:
>     C:/Users/martin/Downloads/vcpkg-martin/packages/unrar_x86-windows/bin/unrar.dll
>     C:/Users/martin/Downloads/vcpkg-martin/packages/unrar_x86-windows/debug/bin/unrar.dll

If I print out environment variable "VSLANG", it is empty.

Tested on Windows 10, vcpkg head version, Microsoft (R) COFF/PE Dumper Version 14.00.24215.1, 
Visual Studio 2015 Community 14.0.25431.01 Update 3
Language: non-english
Port: unrar

And yes, a pdb file is available in the buildtrees folder, for debug as well as release build.

**Comment by PhoebeHui** [comment]
This issue shoud be fixed, please get latest source and try again.

**Comment by rainman110** [comment]
@PhoebeHui I just stumbled upon the same error with a fresh vcpkg install. Even with an additional English language pack installed, `dumpbin` insists of printing a German error message instead, resulting in a failure in PDB detection. Can we reopen this issue?

**Comment by sfhacker** [comment]
This issue is from 2019! God save us all!

**Comment by rainman110** [comment]
> This issue is from 2019! God save us all!

@sfhacker What is it you want to tell me? If an "old" issue persist, it still exist.

**Comment by smkanadl** [comment]
Same here. English version of VS 2022, manually calling dumpbin gives english output, but when I intercept the output from `pdb_line` in `vcpkg_copy_pdbs` by manually adding a `message` command, the message is in German and copy pdb failes.
