### ISSUE TITLE
[vulkan] Visual Studio does not find header file

### ISSUE THREAD

**Issue by jimorc** [Microsoft/vcpkg#5496]
I did:

> vcpkg install vulkan:x64-windows
> vcpkg install vulkan:x86-windows

Here is the output from one of them:

> c:\vcpkg>vcpkg install vulkan:x86-windows
> The following packages will be built and installed:
>     vulkan[core]:x86-windows
> Starting package 1/1: vulkan:x86-windows
> Building package vulkan[core]:x86-windows...
> -- Querying VULKAN_SDK Enviroment variable
> -- Searching C:/VulkanSDK/1.1.82.1/include/vulkan/ for vulkan.h
> -- Found vulkan.h
> -- Found Vulkan SDK version 1.1.82.1
> -- Performing post-build validation
> -- Performing post-build validation done
> Building package vulkan[core]:x86-windows... done
> Installing package vulkan[core]:x86-windows...
> Installing package vulkan[core]:x86-windows... done
> Elapsed time for package vulkan:x86-windows: 2.979 s

And before you ask, yes, I had done:

> vcpkg integrate install

I created a new Empty project in VS, added a cpp file and entered:

> #include <vul

Normally, VS would display a list of all headers or header directories that start with "vul", but no list is displayed. If I complete the line:

> #include <vulkan/vulkan.h>

I get an error message stating 'cannot open source file "vulkan/vulkan.h"'
If I add "C:/VulkanSDK/1.1.82.1/include/" to the list of include directories, then vulkan.h is found. But if I do that, then I don't need the vulkan vcpkg package.

Windows 10 with all updates applied.
vcpkg (latest, installed on 2019-02-28)
vcpkg vulkan package 1.1.82.1-1
Visual Studio 2017 Community version 15.9.2

**Comment by jimorc** [comment]
Correction, VS version is 15.9.7.

**Comment by Voskrese** [comment]
`set EDITOR notepad.exe`

`vcpkg edit vulkan`

```
message(STATUS "Querying VULKAN_SDK Enviroment variable")
file(TO_CMAKE_PATH "$ENV{VULKAN_SDK}" VULKAN_DIR)
set(VULKAN_INCLUDE "${VULKAN_DIR}/Include/vulkan/")
set(VULKAN_ERROR_DL "Before continuing, please download and install Vulkan from:\n    https://vulkan.lunarg.com/sdk/home\n")

if(NOT DEFINED ENV{VULKAN_SDK})
    message(FATAL_ERROR "Could not find Vulkan SDK. ${VULKAN_ERROR_DL}")
endif()

message(STATUS "Searching " ${VULKAN_INCLUDE} " for vulkan.h")
if(NOT EXISTS "${VULKAN_INCLUDE}/vulkan.h")
    message(FATAL_ERROR "Could not find vulkan.h. ${VULKAN_ERROR_DL}")
endif()
message(STATUS "Found vulkan.h")
```

```
${VULKAN_DIR}/Include/vulkan/vulkan.h
${VULKAN_INCLUDE}/vulkan.h
```

**Comment by jimorc** [comment]
Well, thanks for replying, I guess. Let's look at what you wrote:

vcpkg edit vulkan

This opens vulkan's portfile.cmake file. Yes the lines below it are 
included in that file. The final two lines show where the vulkan.h file 
is. I agree. That is not the problem I am having.

The vcpkg README.md file states:

"In Visual Studio, you can create a New Project (or open an existing 
one). All installed libraries are immediately ready to be|#include|'d 
and used in your project without additional configuration."

This does not happen for me, as I stated in the bug report. vulkan.h is 
not found.

Jim

**Comment by cwfitzgerald** [comment]
This is because the vulkan port does not actually copy the vulkan headers over, all it does is verify that they exist under the VULKAN_SDK. You are then responsible for actually adding the include path. This is because actually properly installing the SDK isn't easy. While it isn't easy to fix the problem, there should be a notice saying how you need to include it in your project.

**Comment by cwfitzgerald** [comment]
vcpkg will now tell you the proper way to use it when you install the vulkan package!
