### ISSUE TITLE
Cannot install poco:x64-windows on windows 10 64bits

### ISSUE THREAD

**Issue by stereomatchingkiss** [Microsoft/vcpkg#5515]
vcpkg install poco work, but vcpkg install poco:x64-windows do not

Install poco with following command, visual studio is vc2016, hash code of git is "1afa2b0f7ba4079ff1bb1dd7724733b0cfc583d2"

1. Steps to reproduce

"vcpkg install poco:x64-windows"

Got error messages

**The following packages will be built and installed:
    poco[core]:x64-windows
Starting package 1/1: poco:x64-windows
Building package poco[core]:x64-windows...
-- Using cached C:/Users/yyyy/programs/Qt/3rdLibs/vcpkg/downloads/pocoproject-poco-poco-1.9.0-release.tar.gz
-- Using source at C:/Users/yyyy/programs/Qt/3rdLibs/vcpkg/buildtrees/poco/src/.0-release-b9087a46d0
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: C:/Users/yyyy/programs/Qt/3rdLibs/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: C:/Users/yyyy/programs/Qt/3rdLibs/vcpkg/buildtrees/poco/x64-windows-dbg
    See logs for more information:
      C:\Users\yyyy\programs\Qt\3rdLibs\vcpkg\buildtrees\poco\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/poco/portfile.cmake:42 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package poco:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: poco:x64-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.**

2. Run .\vcpkg update

response

**Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.**

3. run git pull

response

**Already up to date.**

**Comment by Voskrese** [comment]
@yyyy
Working Directory: `C:/Users/yyyy/programs/Qt/3rdLibs/vcpkg/buildtrees/poco/x64-windows-dbg`
**See logs for more information:**
C:\Users\yyyy\programs\Qt\3rdLibs\vcpkg\buildtrees\poco\install-x64-windows-dbg-out.log

**Comment by stereomatchingkiss** [comment]
I put the file(install-x64-windows-dbg-out.log) at [mega.nz](https://mega.nz/#!ct1X2aiR!qQVzgDQRgt0zgyUmArWKb0amOVep6D6xmVpoHo57ce4) since it is too long

**Comment by Voskrese** [comment]
delete libssl.lib and libcrypto.lib x86? and
recompile libcurl, libopenssl?

**Comment by Voskrese** [comment]
open cmd.exe

set | findstr openssl

?

**Comment by Voskrese** [comment]
`[494/600] cmd.exe /C "cd . && C:\Users\yyyy\programs\Qt\3rdLibs\vcpkg\downloads\tools\cmake-3.12.4-windows\cmake-3.12.4-win32-x86\bin\cmake.exe -E vs_link_dll --intdir=Crypto\CMakeFiles\Crypto.dir --manifests  -- C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\link.exe  Crypto\CMakeFiles\Crypto.dir\src\Cipher.cpp.obj Crypto\CMakeFiles\Crypto.dir\src\CipherFactory.cpp.obj Crypto\CMakeFiles\Crypto.dir\src\CipherImpl.cpp.obj Crypto\CMakeFiles\Crypto.dir\src\CipherKey.cpp.obj Crypto\CMakeFiles\Crypto.dir\src\CipherKeyImpl.cpp.obj Crypto\CMakeFiles\Crypto.dir\src\CryptoException.cpp.obj Crypto\CMakeFiles\Crypto.dir\src\CryptoStream.cpp.obj Crypto\CMakeFiles\Crypto.dir\src\CryptoTransform.cpp.obj Crypto\CMakeFiles\Crypto.dir\src\DigestEngine.cpp.obj Crypto\CMakeFiles\Crypto.dir\src\ECDSADigestEngine.cpp.obj Crypto\CMakeFiles\Crypto.dir\src\ECKey.cpp.obj Crypto\CMakeFiles\Crypto.dir\src\ECKeyImpl.cpp.obj Crypto\CMakeFiles\Crypto.dir\src\EVPPKey.cpp.obj Crypto\CMakeFiles\Crypto.dir\src\KeyPair.cpp.obj Crypto\CMakeFiles\Crypto.dir\src\KeyPairImpl.cpp.obj Crypto\CMakeFiles\Crypto.dir\src\OpenSSLInitializer.cpp.obj Crypto\CMakeFiles\Crypto.dir\src\PKCS12Container.cpp.obj Crypto\CMakeFiles\Crypto.dir\src\RSACipherImpl.cpp.obj Crypto\CMakeFiles\Crypto.dir\src\RSADigestEngine.cpp.obj Crypto\CMakeFiles\Crypto.dir\src\RSAKey.cpp.obj Crypto\CMakeFiles\Crypto.dir\src\RSAKeyImpl.cpp.obj Crypto\CMakeFiles\Crypto.dir\src\X509Certificate.cpp.obj  /out:bin\PocoCryptod.dll /implib:lib\PocoCryptod.lib /pdb:bin\PocoCryptod.pdb /dll /version:60.0 /machine:x64 /debug /INCREMENTAL  lib\PocoFoundationd.lib C:\OpenSSL-Win32\lib\libssl.lib C:\OpenSSL-Win32\lib\libcrypto.lib C:\Users\yyyy\programs\Qt\3rdLibs\vcpkg\installed\x64-windows\debug\lib\pcred.lib C:\Users\yyyy\programs\Qt\3rdLibs\vcpkg\installed\x64-windows\debug\lib\zlibd.lib iphlpapi.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd ."`

`FAILED: bin/PocoCryptod.dll lib/PocoCryptod.lib `

**delete in the system pach**  C:\OpenSSL-Win32

` C:\OpenSSL-Win32\lib\libssl.lib C:\OpenSSL-Win32\lib\libcrypto.lib`

**Comment by Voskrese** [comment]
On note, CMake x86 looks for the default x84 library. If you use CMake x64 then and Curl/OpenSSL will be x64

**Comment by stereomatchingkiss** [comment]
Thanks, after delete the folder, I can install poco 64 bits.
Do I have a way to ask vcpkg use CMake x64 as build tool?

**Comment by Voskrese** [comment]
vcpkg automatically does everything, interfere modules from cmake, all will not provide, there are no ideal tools

**Comment by stereomatchingkiss** [comment]
Thanks, I think this issue is solved, vcpkg save me lots of times

**Comment by Voskrese** [comment]
vcpkg install OpenSSL[*] ?

**Comment by LarryIII** [comment]
@stereomatchingkiss Thanks for your feedback, Looks like you first issue was resolved. 
For the last issue "can't find "SecureSMTPClientSession" and others ssl related classes in the Poco/Net folder", could you please re-open a new issue with detailed steps if it is still a problem for you!
