### ISSUE TITLE
Windows vcpkg sometimes downloading cmake when it is already in path

### ISSUE THREAD

**Issue by foopoiuyt** [microsoft/vcpkg#5523]
On Windows 10 in Japanese (cp932), we have one machine which is having tools already in path redownloaded by vcpkg.

`vcpkg install lib`  shows
`A suitable version of cmake was not found (required v3.12.4). Downloading portable cmake v3.12.4...
Downloading cmake...`
where we would expect it to use the version in path as `where cmake` gives
`A:\work\Tools\cmake\bin\cmake.exe` and that executable exists and is runnable by the user.

Adding some logging, we see it attempting to look for that file and decide the file is not there. There seems to be a discrepancy between the results of std::experimental::filesystem::exists and std::filesystem::exists for deciding if the file exists with the former returning false and the latter returning true, where true seems to be the correct result.

**Comment by Voskrese** [comment]
set path=..path...;A:\work\Tools\cmake\bin

where cmake

**Comment by foopoiuyt** [comment]
What we see is that find_from_PATH in files.cpp does not return the cmake.exe binary that exists in the path and what happens is that on https://github.com/Microsoft/vcpkg/blob/3d12e5ca72d948121463beec6e48290877684471/toolsrc/src/vcpkg/base/files.cpp#L274 this->exists(p) returns false, but changing from std::experimental::filesystem to std::filesystem causes the existing file to be seen.

**Comment by NancyLi1013** [comment]
Hi @foopoiuyt 

Sorry for the late reply.

I noticed that you downloaded `cmake 3.12.4`. vcpkg has updated it as `3.14` now. Please try to update vcpkg to the latest version.

Could you please help confirm where cmake is installed and which version is installed  in your local ?
In older to make sure that there is no need to download cmake again, you can install it to C:/ directory. If the version is more that 3.14 (It is the version that vcpkg provides currently), it won't be downloaded again.

**Comment by NancyLi1013** [comment]
Please let me know if you still have any questions about this.

**Comment by NancyLi1013** [comment]
I'm going to close this issue since no response in a long time.
Please feel free to reopen this if it is still a problem for you.
