### ISSUE TITLE
Add CMake support for Visual Studio 2019

### ISSUE THREAD

**Issue by drako0812** [Microsoft/vcpkg#5527]
Package: sfml:x64-windows
Vcpkg version: 2018.11.23-nohash

Currently SFML fails to build after installing Visual Studio 2019 Community RC with the following console output:

~~~
CMake Error at scripts/cmake/vcpkg_configure_cmake.cmake:113 (message):
  Unable to determine appropriate generator for: -x64-v142
Call Stack (most recent call first):
  ports/sfml/portfile.cmake:22 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package sfml:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sfml:x64-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.
~~~

I understand if the maintainers want to wait until VS 2019 is fully released, but I thought I'd at least make the problem apparent. Also, don't know if we're waiting for an updated CMake.

**Comment by MathiasMagnus** [comment]
If 2017 is not installed, the no package can be installed, because Vcpkg argues about no complete toolchain being available. Looking inside the code, Vcpkg does not look for any products with version 16 or above.
