### ISSUE TITLE
the problem of installing pangolin with vcpkg for windows x64

### ISSUE THREAD

**Issue by wulang584513** [Microsoft/vcpkg#5528]
I am installing the pangolin library in the windows 10(x64) with vcpkg ,but I have suffered the following problem: 
-- Downloading http://www.nasm.us/pub/nasm/releasebuilds/2.14/win32/nasm-2.14-win32.zip...
-- Downloading http://www.nasm.us/pub/nasm/releasebuilds/2.14/win32/nasm-2.14-win32.zip... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:156 (message): 
 Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
Error: Building package libjpeg-turbo:x64-windows failed with: BUILD_FAILED

could you give me some help? thanks!

**Comment by jwillemsen** [comment]
Looks the www.nasm.us website is sometimes down making it impossible to download the file

**Comment by LarryIII** [comment]
@wulang584513 Thanks for the feedback. I did not reproduce this issue anymore. Please reopen a new issue if it is still a problem for you!
