### ISSUE TITLE
[nmap] integration of nmap port package

### ISSUE THREAD

**Issue by mjaafar** [Microsoft/vcpkg#5529]
I am doing an integration of nmap package on vcpkg [nmap]. Succeded in primary configuration. But, having trouble with libssl and libssh2. I made a patch for the support (libeay32/ssleay32).
I used the:

find_file(SSLDLL ssleay32.dll PATHS ${VCPKG_ROOT_DIR}/installed/${TARGET_TRIPLET}/bin)
to catch the ssl library. In fact, after that I got an error related to the SHA256 support for the openSSL
even the version is : OPENSSL_VERSION 1.0.2q in the vcpkg packages.

configure: error: Your version of OpenSSL does not support SHA-256. Please install OpenSSL 0.9.8 or later.

Can someone help. Do I need to

**Comment by Voskrese** [comment]
nmap used npcap
https://github.com/nmap/npcap/releases

no port vccpkg npcap

**Comment by wangli28** [comment]
Hi @mjaafar ,
Can you create a pull request, and send your patch to us? We will help you solve this problem.

Thanks.

**Comment by mjaafar** [comment]
I am working on the pull request in few 

Here the log files 

[build-x86-windows-rel-err.log](https://github.com/Microsoft/vcpkg/files/2931094/build-x86-windows-rel-err.log)
[build-x86-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/2931096/build-x86-windows-rel-out.log)

**Comment by mjaafar** [comment]
related issue : adding feature 
[nmap] Integration of nmap netwotk utilities #5530

**Comment by mjaafar** [comment]
pull request cretaed : https://github.com/Microsoft/vcpkg/pull/5545

**Comment by wangli28** [comment]
Thanks for posting this issue, the issue has been fixed in #5545, so I am closing this issue for now.
