### ISSUE TITLE
librealsense2 does not build (install) on Linux

### ISSUE THREAD

**Issue by TIS-Christopher** [Microsoft/vcpkg#5549]
Currently vcpkg fails to build/install realsense2 under linux (ubuntu 18.04, gcc 8.2,WSL) due to a failed step in the debug configuration build.

It seems the error is in the port file of librealsense2 at 
https://github.com/Microsoft/vcpkg/blob/93d87ae5c44d6873122edfb9edbc324bab77785e/ports/realsense2/portfile.cmake#L39

when replaced with 

`"-DCMAKE_DEBUG_POSTFIX=_d"`

it seems to work.

**Comment by claudiofantacci** [comment]
I think we can close this issue @vicroms.
