### ISSUE TITLE
[openexr] IlmImf-2_3.dll is installed into the wrong folder

### ISSUE THREAD

**Issue by mengfan1102** [Microsoft/vcpkg#5553]
[environment]
system: Windows 10.0.17134.590
vcpkg: 2018.11.23-nohash
openexr: 2.3.0-2

[issue]
My vcpkg is installed in `D:\ProgramFiles\vcpkg`, after installed the openexr:x64-windows, the `IlmImf-2_3.dll` and `IlmImf-2_3_d.dll` are installed into a wrong folder `D:\bin`, while other dll and lib are seems installed correctly.

So I have to manually move the `IlmImf-2_3.dll` to `D:\ProgramFiles\vcpkg\installed\x64-windows\bin`, and `IlmImf-2_3_d.dll` to `D:\ProgramFiles\vcpkg\installed\x64-windows\debug\bin`

It seems this issue is related to the cmake configuration of openexr:
[https://github.com/openexr/openexr/issues/355](https://github.com/openexr/openexr/issues/355)

**Comment by LarryIII** [comment]
Thanks for your feedback. This issue has been fixed in https://github.com/Microsoft/vcpkg/pull/5677 with a patch. So I am closing this issue for now.
