### ISSUE TITLE
Exported qt5-base package is broken

### ISSUE THREAD

**Issue by bouffa** [Microsoft/vcpkg#5566]
With #5456  pull request, `qmake.exe` is no longer installed into `(vcpkg_root)/packages/qt5-base_(triplet)/tools/qt5` folder, but directly to the `(vcpkg_root)/installed/(triplet)/tools/qt5` folder.

This will make the `vcpkg export` command export a `qt5-base` package without `qmake.exe`, making it broken (CMake error because of not finding `qmake.exe` when using the package).

The problem could not be limited to qmake.exe executable

**Comment by Rastaban** [comment]
It looks like there are a few other related missing files.  I am working on a targeted fix hopefully addresses this issue, if I am not successful we may need to revert #5456 for now.
