### ISSUE TITLE
vcpkg fails to install packages from case-sensitive file system because of cl.exe

### ISSUE THREAD

**Issue by nunoplopes** [microsoft/vcpkg#5567]
I cannot install any vcpkg package because I did the git checkout of vcpkg from Cygwin, which apparently is now using case sensitive filesystem(?).
According to https://developercommunity.visualstudio.com/content/problem/276297/clexe-breaks-with-case-sensitive-paths.html, the fix seems to be add '/d1scalableinclude-' to cl.exe's arguments. I tested and it works.

**Comment by Voskrese** [comment]
https://github.com/glfw/glfw/issues/1370#issue-376805282

example
Adding to CMakeLists.tx
`target_compile_options(glfw PRIVATE "$<$<C_COMPILER_ID:MSVC>:/d1scalableinclude->")`

**Comment by LarryIII** [comment]
@nunoplopes This issue should be fixed in VS 2019. Could you please try to install VS 2019 and use vcpkg to install any port to verify whether this issue still active?

**Comment by nunoplopes** [comment]
It works fine with VS 2019, yes, thanks.
