### ISSUE TITLE
applocal.ps1 depends on dumpbin.exe

### ISSUE THREAD

**Issue by wm1** [Microsoft/vcpkg#557]
vcpkg/scripts/buildsystems/msbuild/applocal.ps1:
    $(dumpbin /DEPENDENTS $targetBinary | 
    ..

What about if dumpbin is not in %PATH%? I only have msbuild in path, and it is smart enough to figure out where the compiler is.

**Comment by ras0219-msft** [comment]
Generally, applocal.ps1 is intended to be run inside a build environment, such as inside the VS developer prompt or during an MSBuild invocation (as a post-build task).

Could you elaborate more about what situation are you in that is solved by running the script outside of the above environments?

**Comment by wm1** [comment]
MSBuild can find the location of the compiler/linker tools without my intervention; it can also build for different platforms from a single command prompt, while with VS developer prompt I have to open one command window for each platform. Therefore I prefer to have MSBuild in PATH and do not open VS developer prompt whenever possible.

```
with VS-template based vcxproj:

msbuild /p:Platform=x64 will invoke:
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\CL.exe

msbuild /p:Platform=x86 will invoke:
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\CL.exe
```

**Comment by ras0219-msft** [comment]
Certainly, Msbuild is a much nicer entry to the compiler than constantly switching developer prompts.

However, I'm still curious about what you're looking to achieve by running `applocal.ps1` from your main command prompt -- as long as `applocal.ps1` is being invoked from _inside_ MSBuild (such as a PostBuildStep), it should work correctly. Additionally, Vcpkg internally handles the developer prompt for you, so inside a portfile the `applocal.ps1` script will also run correctly.

We really haven't authored the `applocal.ps1` script to be a "public" script that's easy to take out of Vcpkg and use elsewhere; if there's a significant need, that might be an interesting direction to go in the future, but I'd like to know what that need is before considering that script as part of our public "API".

**Comment by wm1** [comment]
I see. I was reading the said applocal.ps1 file and made an assumption that it was invoked on a bare-bone environment. Actually it is not. When msbuild tries to build a vcxproj, it automatically adjusts PATH etc. to the right VC toolset. 

```
\msbuild\Microsoft.Cpp\v4.0\v140\Microsoft.CppBuild.targets
  <Target Name="InitializeBuildStatus" DependsOnTargets="PrepareForBuild">
  <Target Name="PrepareForBuild" DependsOnTargets="SetBuildDefaultEnvironmentVariables;SetUserMacroEnvironmentVariables;GetResolvedWinMD;$(PrepareForBuildDependsOn)">

\msbuild\Microsoft.Cpp\v4.0\v140\Microsoft.Cpp.Current.targets
  <Target Name="SetBuildDefaultEnvironmentVariables"
    <SetEnv Name   ="PATH"
            Value  ="$(ExecutablePath)"
            Prefix ="false">
      <Output TaskParameter="OutputEnvironmentVariable" PropertyName="Path"/>
    </SetEnv>

\msbuild\Microsoft.Cpp\v4.0\v140\Platforms\x64\PlatformToolsets\v140\Toolset.props
    <ExecutablePath Condition="'$(ExecutablePath)' == ''">$(VC_ExecutablePath_x64);$(WindowsSDK_ExecutablePath);$(VS_ExecutablePath);$(MSBuild_ExecutablePath);$(FxCopDir);$(PATH);</ExecutablePath>
```

Therefore dumpbin is indeed located when msbuild the project. I double verified it by adding a line of "(get-command dumpbin).Path" to applocal.ps1, and checked the msbuild output contains C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\dumpbin.exe.

Thanks for your time. There is no issue on vcpkg side.

**Comment by calumr** [comment]
Is dumpbin on the path when building a csproj? I don't think it is, so I get errors when building my C# app from within VS:

9>  dumpbin : The term 'dumpbin' is not recognized as the name of a cmdlet, function, script file, or operable program. 
9>  Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by ensafi** [comment]
Apparently not.  My C# project does not have dumpbin.exe in its path and I get the same Vcpkg related error from applocal.ps1, but my C++ projects all find dumpbin.exe because it resides next to cl.exe, which gets added to PATH by MSBuild.
