### ISSUE TITLE
Error: Building package boost-build:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by aprole** [Microsoft/vcpkg#5572]
I'm trying to install the dependencies for cpprestsdk but vcpkg is giving errors when installing boost. Also in the bootstrap-x64-windows-err.log it says "'cl' is not recognized as an internal or external command....". But I'm running this in Visual studio 2017 command prompt and cl is a recognized command. Have also tried it in Powershell with the same result. I have also tried it with an installed version of CMake, then uninstalled CMake and no difference.

C:\Users\aprole\vcpkg>vcpkg install --triplet x64-windows boost-system zlib openssl boost-date-time boost-regex websocketpp
The following packages will be built and installed:
  * boost-algorithm[core]:x64-windows
  * boost-array[core]:x64-windows
  * boost-asio[core]:x64-windows
  * boost-atomic[core]:x64-windows
  * boost-bind[core]:x64-windows
  * boost-build[core]:x64-windows
  * boost-chrono[core]:x64-windows
  * boost-concept-check[core]:x64-windows
  * boost-container[core]:x64-windows
  * boost-container-hash[core]:x64-windows
  * boost-context[core]:x64-windows
  * boost-conversion[core]:x64-windows
  * boost-coroutine[core]:x64-windows
    boost-date-time[core]:x64-windows
  * boost-exception[core]:x64-windows
  * boost-function[core]:x64-windows
  * boost-function-types[core]:x64-windows
  * boost-functional[core]:x64-windows
  * boost-fusion[core]:x64-windows
  * boost-intrusive[core]:x64-windows
  * boost-io[core]:x64-windows
  * boost-iterator[core]:x64-windows
  * boost-lambda[core]:x64-windows
  * boost-lexical-cast[core]:x64-windows
  * boost-math[core]:x64-windows
  * boost-modular-build-helper[core]:x64-windows
  * boost-mpl[core]:x64-windows
  * boost-numeric-conversion[core]:x64-windows
  * boost-optional[core]:x64-windows
  * boost-pool[core]:x64-windows
  * boost-range[core]:x64-windows
  * boost-ratio[core]:x64-windows
  * boost-rational[core]:x64-windows
    boost-regex[core]:x64-windows
  * boost-smart-ptr[core]:x64-windows
    boost-system[core]:x64-windows
  * boost-thread[core]:x64-windows
  * boost-throw-exception[core]:x64-windows
  * boost-tokenizer[core]:x64-windows
  * boost-tuple[core]:x64-windows
  * boost-type-index[core]:x64-windows
  * boost-type-traits[core]:x64-windows
  * boost-typeof[core]:x64-windows
  * boost-unordered[core]:x64-windows
  * boost-utility[core]:x64-windows
    openssl[core]:x64-windows
  * openssl-windows[core]:x64-windows
    websocketpp[core]:x64-windows
    zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/49: boost-build:x64-windows
Building package boost-build[core]:x64-windows...
-- Using cached C:/Users/aprole/vcpkg/downloads/boostorg-build-boost-1.69.0.tar.gz
-- Using source at C:/Users/aprole/vcpkg/buildtrees/boost-build/src/ost-1.69.0-1d1e4d577d
-- Using cached C:/Users/aprole/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Using cached C:/Users/aprole/vcpkg/downloads/boost-1.69.0-boostcpp.jam
-- Installing: C:/Users/aprole/vcpkg/packages/boost-build_x64-windows/share/boost-build/copyright
-- Installing: C:/Users/aprole/vcpkg/packages/boost-build_x64-windows/tools/boost-build/boostcpp.jam
-- Bootstrapping...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: C:/Users/aprole/vcpkg/packages/boost-build_x64-windows/tools/boost-build/bootstrap.bat;msvc
    Working Directory: C:/Users/aprole/vcpkg/packages/boost-build_x64-windows/tools/boost-build
    See logs for more information:
      C:\Users\aprole\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-out.log
      C:\Users\aprole\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-err.log

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:53 (vcpkg_execute_required_process)
  scripts/ports.cmake:71 (include)

Error: Building package boost-build:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-build:x64-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

[bootstrap-x64-windows-err.log](https://github.com/Microsoft/vcpkg/files/2938274/bootstrap-x64-windows-err.log)
[bootstrap-x64-windows-out.log](https://github.com/Microsoft/vcpkg/files/2938275/bootstrap-x64-windows-out.log)
[bootstrap.log](https://github.com/Microsoft/vcpkg/files/2938288/bootstrap.log)

**Comment by Voskrese** [comment]
vcpkg env --triplet x64-windows --debug

**Comment by aprole** [comment]
Just ran again with the --debug flag

C:\Users\aprole\vcpkg>vcpkg install --triplet x64-windows --debug boost-system zlib openssl boost-date-time boost-regex websocketpp
[DEBUG] Using vcpkg-root: C:\Users\aprole\vcpkg
The following packages will be built and installed:
  * boost-algorithm[core]:x64-windows
  * boost-array[core]:x64-windows
  * boost-asio[core]:x64-windows
  * boost-atomic[core]:x64-windows
  * boost-bind[core]:x64-windows
  * boost-build[core]:x64-windows
  * boost-chrono[core]:x64-windows
  * boost-concept-check[core]:x64-windows
  * boost-container[core]:x64-windows
  * boost-container-hash[core]:x64-windows
  * boost-context[core]:x64-windows
  * boost-conversion[core]:x64-windows
  * boost-coroutine[core]:x64-windows
    boost-date-time[core]:x64-windows
  * boost-exception[core]:x64-windows
  * boost-function[core]:x64-windows
  * boost-function-types[core]:x64-windows
  * boost-functional[core]:x64-windows
  * boost-fusion[core]:x64-windows
  * boost-intrusive[core]:x64-windows
  * boost-io[core]:x64-windows
  * boost-iterator[core]:x64-windows
  * boost-lambda[core]:x64-windows
  * boost-lexical-cast[core]:x64-windows
  * boost-math[core]:x64-windows
  * boost-modular-build-helper[core]:x64-windows
  * boost-mpl[core]:x64-windows
  * boost-numeric-conversion[core]:x64-windows
  * boost-optional[core]:x64-windows
  * boost-pool[core]:x64-windows
  * boost-range[core]:x64-windows
  * boost-ratio[core]:x64-windows
  * boost-rational[core]:x64-windows
    boost-regex[core]:x64-windows
  * boost-smart-ptr[core]:x64-windows
    boost-system[core]:x64-windows
  * boost-thread[core]:x64-windows
  * boost-throw-exception[core]:x64-windows
  * boost-tokenizer[core]:x64-windows
  * boost-tuple[core]:x64-windows
  * boost-type-index[core]:x64-windows
  * boost-type-traits[core]:x64-windows
  * boost-typeof[core]:x64-windows
  * boost-unordered[core]:x64-windows
  * boost-utility[core]:x64-windows
    openssl[core]:x64-windows
  * openssl-windows[core]:x64-windows
    websocketpp[core]:x64-windows
    zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/49: boost-build:x64-windows
Building package boost-build[core]:x64-windows...
[DEBUG] _wpopen(""C:\Users\aprole\vcpkg\downloads\tools\cmake-3.12.4-windows\cmake-3.12.4-win32-x86\bin\cmake.exe" --version 2>&1")
[DEBUG] _pclose() returned 0 after    25903 us
[DEBUG] _wpopen(""C:\Users\aprole\vcpkg\downloads\tools\cmake-3.12.4-windows\cmake-3.12.4-win32-x86\bin\cmake.exe" "-DCMAKE_TRIPLET_FILE=C:/Users/aprole/vcpkg/triplets/x64-windows.cmake" -P "C:/Users/aprole/vcpkg/scripts/get_triplet_environment.cmake" 2>&1")
[DEBUG] _pclose() returned 0 after    23750 us
[DEBUG] Found path: C:\Program Files\Git\cmd\git.exe
[DEBUG] _wpopen(""C:\Users\aprole\vcpkg\downloads\tools\git-2.20.0-windows\cmd\git.exe" --version 2>&1")
[DEBUG] _pclose() returned 0 after    34059 us
[DEBUG] _wpopen(""C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease -legacy -products * -format xml 2>&1")
[DEBUG] _pclose() returned 0 after    76451 us
[DEBUG] CreateProcessW(cmd.exe /c ""C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\Build\vcvarsall.bat" -vcvars_ver=14.1 amd64   2>&1 <NUL & "C:\Users\aprole\vcpkg\downloads\tools\cmake-3.12.4-windows\cmake-3.12.4-win32-x86\bin\cmake.exe" "-DCMD=BUILD" "-DPORT=boost-build" "-DCURRENT_PORT_DIR=C:/Users/aprole/vcpkg/ports/boost-build" "-DTARGET_TRIPLET=x64-windows" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DVCPKG_USE_HEAD_VERSION=0" "-DDOWNLOADS=C:/Users/aprole/vcpkg/downloads" "-D_VCPKG_NO_DOWNLOADS=0" "-D_VCPKG_DOWNLOAD_TOOL=BUILT_IN" "-DGIT=C:/Users/aprole/vcpkg/downloads/tools/git-2.20.0-windows/cmd/git.exe" "-DFEATURES=core" "-DALL_FEATURES=" -P "C:/Users/aprole/vcpkg/scripts/ports.cmake"")
[ERROR:vcvarsall.bat] Invalid argument found : -vcvars_ver=14.1
[ERROR:~nx0] Error in script usage. The correct usage is:
Syntax:
    vcvarsall.bat [arch]
  or
    vcvarsall.bat [arch] [version]
  or
    vcvarsall.bat [arch] [platform_type] [version]
where :
    [arch]: x86 | amd64 | x86_amd64 | x86_arm | x86_arm64 | amd64_x86 | amd64_arm | amd64_arm64
    [platform_type]: {empty} | store | uwp
    [version] : full Windows 10 SDK number (e.g. 10.0.10240.0) or "8.1" to use the Windows 8.1 SDK.

The store parameter sets environment variables to support Universal Windows Platform application
development and is an alias for 'uwp'.

For example:
    vcvarsall.bat x86_amd64
    vcvarsall.bat x86_amd64 10.0.10240.0
    vcvarsall.bat x86_arm uwp 10.0.10240.0
    vcvarsall.bat x86_arm onecore 10.0.10240.0
    vcvarsall.bat x64 8.1
    vcvarsall.bat x64 store 8.1

Please make sure either Visual Studio or C++ Build SKU is installed.
-- Using cached C:/Users/aprole/vcpkg/downloads/boostorg-build-boost-1.69.0.tar.gz
-- Using source at C:/Users/aprole/vcpkg/buildtrees/boost-build/src/ost-1.69.0-1d1e4d577d
-- Using cached C:/Users/aprole/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Using cached C:/Users/aprole/vcpkg/downloads/boost-1.69.0-boostcpp.jam
-- Installing: C:/Users/aprole/vcpkg/packages/boost-build_x64-windows/share/boost-build/copyright
-- Installing: C:/Users/aprole/vcpkg/packages/boost-build_x64-windows/tools/boost-build/boostcpp.jam
-- Bootstrapping...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: C:/Users/aprole/vcpkg/packages/boost-build_x64-windows/tools/boost-build/bootstrap.bat;msvc
    Working Directory: C:/Users/aprole/vcpkg/packages/boost-build_x64-windows/tools/boost-build
    See logs for more information:
      C:\Users\aprole\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-out.log
      C:\Users\aprole\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-err.log

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:53 (vcpkg_execute_required_process)
  scripts/ports.cmake:71 (include)


[DEBUG] CreateProcessW() returned 1 after 3106215 us
Error: Building package boost-build:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-build:x64-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.
[DEBUG] ..\src\vcpkg\install.cpp(405)
[DEBUG] Exiting after 3384592 us (3382187 us)

**Comment by Alex5956** [comment]
donwload vs 2015 => https://stackoverflow.com/questions/44290672/how-to-download-visual-studio-community-edition-2015-not-2017
