### ISSUE TITLE
Failed to build Wt

### ISSUE THREAD

**Issue by khengling** [Microsoft/vcpkg#558]
Dependencies were build an installed successfully.

The following package failed to build:
Package: wt:x86-windows
Vcpkg version: 0.0.66-0d50c6704ddc563f459b901297bbb909adaa6e51

Please see attached installation and build logs for more details.
[wt-installation-log.txt](https://github.com/Microsoft/vcpkg/files/712946/wt-installation-log.txt)
[package-x86-windows-rel-out.log.txt](https://github.com/Microsoft/vcpkg/files/712947/package-x86-windows-rel-out.log.txt)

**Comment by ras0219-msft** [comment]
Ok, looking at the package log, boost isn't getting properly linked in. I'll see if I can repro it locally.

**Comment by ras0219-msft** [comment]
On Windows, wt is going out of it's way to rely on the boost autolink behavior. The fix is to patch in an option to suppress using boost autolink on Windows. I'm testing it now and will push it shortly.

**Comment by khengling** [comment]
Thanks Robert for the update! Looking forward to the patch.

**Comment by ras0219-msft** [comment]
Patched and pushed. Let me know if that solves the issue for you!

**Comment by khengling** [comment]
Hi Robert,

Thanks. I tried to update vcpkg to the latest version. The following error
occurred when I ran the following command:

powershell -exec bypass scripts\bootstrap.ps1


Build FAILED.

       "E:\vcpkg\toolsrc\vcpkg.sln" (default target) (1) ->
       "E:\vcpkg\toolsrc\vcpkgtest\vcpkgtest.vcxproj" (default target) (6)
->
       (ClCompile target) ->
         e:\vcpkg\toolsrc\src\tests_dependencies.cpp(1): fatal error C1083:
Cannot open include file: 'CppUnitTest.h':
       No such file or directory
[E:\vcpkg\toolsrc\vcpkgtest\vcpkgtest.vcxproj]
         e:\vcpkg\toolsrc\src\tests_paragraph.cpp(1): fatal error C1083:
Cannot open include file: 'CppUnitTest.h': No
       such file or directory [E:\vcpkg\toolsrc\vcpkgtest\vcpkgtest.vcxproj]

    0 Warning(s)
    2 Error(s)


Therefore, I couldn't test your fix. Please advise.

On Wed, Jan 25, 2017 at 6:56 AM, Robert Schumacher <notifications@github.com

**Comment by khengling** [comment]
Hi Robert,

The vcpkg problem has been resolved. The Wt can be built successfully now.
Thanks a lot!
