### ISSUE TITLE
Building package glib:x64-windows-static failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Brooklyn2001** [microsoft/vcpkg#5581]
Error: Building package glib:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glib:x64-windows-static
  Vcpkg version: 2018.11.23-nohash

**Comment by Voskrese** [comment]
read log

**"Glib only supports dynamic library and crt linkage"**

**Comment by PhoebeHui** [comment]
@Brooklyn2001, glib doesn't support static build, only supports dynamic library and crt linkage.

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/3100
