### ISSUE TITLE
Rename vcpkg-cmake-wrapper.cmake to vcpkg-cmake-find_package-wrapper.cmake

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#5588]
or similar to make it more clear what the wrapper actual does. 
Without a clear name the toolchain file must be inspected to actual know what it is doing.

(alternative: vcpkg-cmake-find_package-redirection.cmake)

**Comment by PhoebeHui** [comment]
This issue hasn’t been updated in a year, if you still want to rename it, please reopen.
