### ISSUE TITLE
Can we expose the "install" progress?

### ISSUE THREAD

**Issue by floridoug** [microsoft/vcpkg#5589]
If I'm not mistaken, I saw that vcpkg uses "ninja" under the hood.  Ninja does a good job of communicating the on-going build process succinctly (e.g. on step 50 of 1000).

It would be great to expose this build progress during installs; otherwise, for a long-running build process, all we see is "Building package xyz..." with no idea for how long it will take to complete.

If exposing the ninja-provided info isn't feasible for some reason (or I'm mistaken that ninja is being used), then perhaps we could communicate some sort of progress?

Thanks for your consideration ;-)

**Comment by wangli28** [comment]
Same with #4879

**Comment by nightslashs** [comment]
I am planning to look into this functionality, just to confirm I'm on the same page are we thinking outputting something similar to ninja's build system?
<img width="583" alt="screen shot 2019-03-08 at 9 22 33 am" src="https://user-images.githubusercontent.com/4615660/54044745-943c9e80-4184-11e9-9de0-d02371e47e17.png">

Or something more like cmake's build system where it prints very verbosely line by line?

**Comment by nightslashs** [comment]
Additionally are we thinking about enabling this via command line flag or by default?

**Comment by floridoug** [comment]
Personally, I prefer ninja's style, but having some type of feedback would be good.  ;-)

Re:  command line or default, perhaps default to the ninja style by default (i.e. when launching the build interactively from the command line) and provide a command line option to satisfy other use cases.

An example of an "other use case" might be to provide more verbose output like the cmake example mentioned above (is that different from the undocumented vcpkg "--debug" option?).

Another example might be to suppress the feedback, if so desired.

How does that sound?

**Comment by LindyBalboa** [comment]
Yes this would be nice!

**Comment by NancyLi1013** [comment]
Hi @floridoug, thanks for posting this issue. It's duplicated with #4879. Please track this issue here.
