### ISSUE TITLE
 Building package coroutine: x64-windows/x86-windows failed

### ISSUE THREAD

**Issue by wangli28** [Microsoft/vcpkg#5593]
I tried to install coroutine with command `.\vcpkg.exe install coroutine:x86-windows`. I got this error:

> The following packages will be built and installed:
    coroutine[core]:x86-windows
/  * ms-gsl[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: ms-gsl:x86-windows
Building package ms-gsl[core]:x86-windows...
-- Using cached E:/vcpkg/downloads/Microsoft-GSL-7d78b743e43ecba06ca47426d03d9d16076dec16.tar.gz
-- Using source at E:/vcpkg/buildtrees/ms-gsl/src/16076dec16-a8337c6865
-- Up-to-date: E:/vcpkg/packages/ms-gsl_x86-windows/include
-- Installing: E:/vcpkg/packages/ms-gsl_x86-windows/include/gsl
-- Installing: E:/vcpkg/packages/ms-gsl_x86-windows/include/gsl/gsl
-- Installing: E:/vcpkg/packages/ms-gsl_x86-windows/include/gsl/gsl_algorithm
-- Installing: E:/vcpkg/packages/ms-gsl_x86-windows/include/gsl/gsl_assert
-- Installing: E:/vcpkg/packages/ms-gsl_x86-windows/include/gsl/gsl_byte
-- Installing: E:/vcpkg/packages/ms-gsl_x86-windows/include/gsl/gsl_util
-- Installing: E:/vcpkg/packages/ms-gsl_x86-windows/include/gsl/multi_span
-- Installing: E:/vcpkg/packages/ms-gsl_x86-windows/include/gsl/pointers
-- Installing: E:/vcpkg/packages/ms-gsl_x86-windows/include/gsl/span
-- Installing: E:/vcpkg/packages/ms-gsl_x86-windows/include/gsl/string_span
-- Installing: E:/vcpkg/packages/ms-gsl_x86-windows/share/ms-gsl/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package ms-gsl[core]:x86-windows... done
Installing package ms-gsl[core]:x86-windows...
Installing package ms-gsl[core]:x86-windows... done
Elapsed time for package ms-gsl:x86-windows: 9.343 s
Starting package 2/2: coroutine:x86-windows
Building package coroutine[core]:x86-windows...
-- Downloading https://github.com/luncliff/coroutine/archive/1.4.tar.gz...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:91 (message):
/
/
  File does not have expected hash:
/
          File path: [ E:/vcpkg/downloads/temp/luncliff-coroutine-1.4.tar.gz ]
      Expected hash: [ 981c9c728c7888995880a97e8533fa31f41085ef57e1c61e53e555f329d20d4a882d9de724d9e93e3d009dc3fe0669fe4d1af403654a9373e4aab44c933628a3 ]
        Actual hash: [ 6154988fca025a196d68ca025ce95fd972ed8aed15475d4da9d4038a4a3f498b1e0a4f570ff250f3a45e97b79ac6a2a2fe08abe645a389d5f1a68fd89cc58021 ]
/
  The file may have been corrupted in transit.  This can be caused by
  proxies.  If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
  environment variables to
  "https://user:password@your-proxy-ip-address:port/".
/
/
/
Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:163 (test_hash)
  scripts/cmake/vcpkg_from_github.cmake:108 (vcpkg_download_distfile)
  ports/coroutine/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:71 (include)
/
/
Error: Building package coroutine:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: coroutine:x86-windows
  Vcpkg version: 2018.11.23-nohash
/
Additionally, attach any relevant sections from the log files above.

**Comment by wangli28** [comment]
I also tried to install coroutine: x64-windows with command `.\vcpkg.exe install coroutine:x64-windows`. I got this error:

> The following packages will be built and installed:
    coroutine[core]:x64-windows
Starting package 1/1: coroutine:x64-windows
Building package coroutine[core]:x64-windows...
-- Downloading https://github.com/luncliff/coroutine/archive/1.4.tar.gz...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:91 (message):
/
/
  File does not have expected hash:
/
          File path: [ E:/vcpkg/downloads/temp/luncliff-coroutine-1.4.tar.gz ]
      Expected hash: [ 981c9c728c7888995880a97e8533fa31f41085ef57e1c61e53e555f329d20d4a882d9de724d9e93e3d009dc3fe0669fe4d1af403654a9373e4aab44c933628a3 ]
        Actual hash: [ 6154988fca025a196d68ca025ce95fd972ed8aed15475d4da9d4038a4a3f498b1e0a4f570ff250f3a45e97b79ac6a2a2fe08abe645a389d5f1a68fd89cc58021 ]
/
  The file may have been corrupted in transit.  This can be caused by
  proxies.  If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
  environment variables to
  "https://user:password@your-proxy-ip-address:port/".
/
/
/
Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:163 (test_hash)
  scripts/cmake/vcpkg_from_github.cmake:108 (vcpkg_download_distfile)
  ports/coroutine/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:71 (include)
/
/
Error: Building package coroutine:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: coroutine:x64-windows
  Vcpkg version: 2018.11.23-nohash
/
Additionally, attach any relevant sections from the log files above.

**Comment by Voskrese** [comment]
?

`vcpkg.exe edit coroutine`

to replace

981c9c728c7888995880a97e8533fa31f41085ef57e1c61e53e555f329d20d4a882d9de724d9e93e3d009dc3fe0669fe4d1af403654a9373e4aab44c933628a3 ]

**Actual hash**: 

[ 6154988fca025a196d68ca025ce95fd972ed8aed15475d4da9d4038a4a3f498b1e0a4f570ff250f3a45e97b79ac6a2a2fe08abe645a389d5f1a68fd89cc58021 ]

**Comment by Voskrese** [comment]
> CMake Error at ports/coroutine/portfile.cmake:12 (message):

  **This library doesn't support x86 arch.  Please use x64 instead or contact  maintainer**

`vcpkg.exe install coroutine:x64-windows`

```
Starting package 2/2: coroutine:x64-windows
Building package coroutine[core]:x64-windows...
-- Using cached E:/tools/vcpkg/downloads/luncliff-coroutine-1.4.tar.gz
-- Using source at E:/tools/vcpkg/buildtrees/coroutine/src/1.4-383ec8c08d
-- Using Guideline Support Library at E:/tools/vcpkg/installed/x64-windows/include
-- Using DLL linkage
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: E:/tools/vcpkg/packages/coroutine_x64-windows/share/coroutine/copyright
-- Installing: E:/tools/vcpkg/packages/coroutine_x64-windows/debug/bin/coroutine.dll
-- Installing: E:/tools/vcpkg/packages/coroutine_x64-windows/bin/coroutine.dll
-- Performing post-build validation
-- Performing post-build validation done
Building package coroutine[core]:x64-windows... done
Installing package coroutine[core]:x64-windows...
Installing package coroutine[core]:x64-windows... doneInstalling package coroutine[core]:x64-windows... done
```

**Comment by JackBoosY** [comment]
@Voskrese  the point is source hash not correct.

**Comment by JackBoosY** [comment]
Already fixed.

**Comment by luncliff** [comment]
@wangli28 First of all, i'm sorry for the error with the hash. 
About a month ago, I found a mistake in my code so I decided to make a force push for the tag.
I will be cautious and  for later update and support for vcpkg.

Thanks !
