### ISSUE TITLE
[moos-core]Port bug with Building x64-windows/x86-windows

### ISSUE THREAD

**Issue by wangli28** [microsoft/vcpkg#5594]
I tried to install coroutine with command `.\vcpkg.exe install moos-core:x86-windows`. I got this error:

> PS E:\vcpkg> .\vcpkg.exe install moos-core:x86-windows
The following packages will be built and installed:
    moos-core[core]:x86-windows
Starting package 1/1: moos-core:x86-windows
Building package moos-core[core]:x86-windows...
-- Using cached E:/vcpkg/downloads/themoos-core-moos-v10.4.0.tar.gz
-- Using source at E:/vcpkg/buildtrees/moos-core/src/v10.4.0-b118d91331
-- Applying patch E:/vcpkg/ports/moos-core/cmake_fix.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- MOOS VCPKG SOURCE_PATH E:/vcpkg/buildtrees/moos-core/src/v10.4.0-b118d91331
-- MOOS INSTALL -DCMAKE_INSTALL_PREFIX=E:/vcpkg/packages/moos-core_x86-windows
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: E:/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: E:/vcpkg/buildtrees/moos-core/x86-windows-dbg
    See logs for more information:
      E:\vcpkg\buildtrees\moos-core\install-x86-windows-dbg-out.log
/
Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/moos-core/portfile.cmake:30 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)
/
/
Error: Building package moos-core:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: moos-core:x86-windows
  Vcpkg version: 2018.11.23-nohash
/
Additionally, attach any relevant sections from the log files above.

I also tried to install coroutine: x64-windows with command` .\vcpkg.exe install moos-core:x64-windows` I got the same error.

**Comment by JackBoosY** [comment]
Missing definitions:
`add_definitions(-DMOOS_POCO_DLL)`
`add_definitions(-DFoundation_EXPORTS)`

and missing includes in tools and tests.

**Comment by JackBoosY** [comment]
Hi @pmnewman, can you help me solve the problem of not generating MOOS.lib on the x86-windows trplet?
Thanks.

**Comment by JackBoosY** [comment]
PR has merged. Close this issue.
