### ISSUE TITLE
OpenEXR builds and runs test which takes a very long time 

### ISSUE THREAD

**Issue by dokipen3d** [Microsoft/vcpkg#5596]
Please could we disable the fuzz tests that get run as it takes quite a while to get through them.

thanks
dan

**Comment by Voskrese** [comment]
no test

https://github.com/Microsoft/vcpkg/blob/master/ports/openexr/portfile.cmake

https://github.com/Microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_test_cmake.md

I personally commented out this line everywhere

`vcpkg_test_cmake(PACKAGE_NAME `
-->> 
`# vcpkg_test_cmake(PACKAGE_NAME`

**Comment by dokipen3d** [comment]
There are still some executables that run during build though. I'm not sure where in the cmake they are being invoked (b44ExpLogTable etc)

**Comment by dokipen3d** [comment]
It looks like there is an executable build as part of the build process which generates some look up tables which are then used in the library. Probably something which constexpr would be useful for.
