### ISSUE TITLE
Openssl on windows

### ISSUE THREAD

**Issue by manang** [Microsoft/vcpkg#5605]
Hi,
I'm trying to use openssl in my project on windows.
When I launch my application I have the following error:
OPENSSL_Uplink(00007FF8C8EAE000,08): no OPENSSL_Applink

I installed openssl and I copied the dlls in c:\Windows\System32
do you know how I can solve this issue?
Thanks

**Comment by Voskrese** [comment]
ARCH ?

**Comment by manang** [comment]
x64,
I included <openssl/applink.c> (.c and not .h) in my project.
I compiled without vspkg openssl and I don't have this problem.
But I think that with this include is ok.
Thanks
