### ISSUE TITLE
Error: building package libjpeg-turbo:arm-uwp failed

### ISSUE THREAD

**Issue by mkwiczalayandex** [Microsoft/vcpkg#561]
c:\develop\repos\vcpkg>vcpkg.exe install opencv:arm-uwp
The specified configuration type is missing.  The tools for the
configuration might not be installed.
-- CURRENT_INSTALLED_DIR=C:/develop/repos/vcpkg/installed/arm-uwp
-- DOWNLOADS=C:/develop/repos/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/develop/repos/vcpkg/packages/libjpeg-turbo_arm-uwp
-- CURRENT_BUILDTREES_DIR=C:/develop/repos/vcpkg/buildtrees/libjpeg-turbo
-- CURRENT_PORT_DIR=c:/develop/repos/vcpkg/ports/libjpeg-turbo/.
-- Using cached C:/develop/repos/vcpkg/downloads/libjpeg-turbo-1.4.90.zip
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch C:/develop/repos/vcpkg/ports/libjpeg-turbo/add-options-for-exes-docs-headers.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/develop/repos/vcpkg/ports/libjpeg-turbo/add-options-for-exes-docs-headers.patch done
-- Configuring arm-uwp-rel
-- Configuring arm-uwp-rel done
-- Configuring arm-uwp-dbg
-- Configuring arm-uwp-dbg done
-- Package arm-uwp-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: C:/Program Files (x86)/CMake/bin/cmake.exe;--build;.;--config;Release;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/m
    Working Directory: C:/develop/repos/vcpkg/buildtrees/libjpeg-turbo/arm-uwp-rel
    See logs for more information:
      C:\develop\repos\vcpkg\buildtrees\libjpeg-turbo\package-arm-uwp-rel-out.log
      C:\develop\repos\vcpkg\buildtrees\libjpeg-turbo\package-arm-uwp-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:16 (vcpkg_execute_required_process)
  ports/libjpeg-turbo/portfile.cmake:39 (vcpkg_install_cmake)
  scripts/ports.cmake:73 (include)

Error: building package libjpeg-turbo:arm-uwp failed
Please ensure sure you're using the latest portfiles with `vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libjpeg-turbo:arm-uwp
  Vcpkg version: 0.0.66-0d50c6704ddc563f459b901297bbb909adaa6e51

Additionally, attach any relevant sections from the log files above.

**Comment by Mixaill** [comment]
Please try fixes from #794
