### ISSUE TITLE
[vcpkg] cmake build logs get overwritten by cmake install logs

### ISSUE THREAD

**Issue by Neumann-A** [Microsoft/vcpkg#5610]
the problem is that the build script is using the same logfile e.g. install-x64-linux-dbg-out.log as the install script. Observed e.g. in package kealib (and many more)

**Comment by wangli28** [comment]
Hi @Neumann-A, can you provide an example?
Thanks.

**Comment by Neumann-A** [comment]
@wangli28: I close this on. I thought I saw some strange behavior but I was unable to reproduce it anymore. Sry for that one.
