### ISSUE TITLE
How to change the source download address？

### ISSUE THREAD

**Issue by zcwbnu** [microsoft/vcpkg#5611]
I install osgearth with vcpkg, I found the download version is not lastest: https://github.com/gwaldron/osgearth/archive/osgearth-2.10.tar.gz . How can I change the source download version？

I manually downloaded a new version  osgearth2.10-master and replaced the old version (with the same name), however vcpkg alway report built failed.

**Comment by Voskrese** [comment]
https://github.com/Microsoft/vcpkg/blob/master/ports/osgearth/portfile.cmake
```
```

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO gwaldron/osgearth
REF osgearth-2.10
```

osgearth-2.10

**Comment by zcwbnu** [comment]
@Voskrese  I replaced “osgearth-2.10” with “master”，it always report built error.
I want to use the url: https://github.com/gwaldron/osgearth/archive/master.zip, How can I change the portife.cmake file?

**Comment by Voskrese** [comment]
```
vcpkg_download_distfile(
    VS2017PATCH
    URLS "https://github.com/remoe/osgearth/commit/f7081cc4f9991c955c6a0ef7b7b50e48360d14fd.diff"
FILENAME "osgearth-f7081cc4f9991c955c6a0ef7b7b50e48360d14fd.patch"
```

**Comment by zcwbnu** [comment]
I changed "vcpkg_download_distfile" and "vcpkg_from_github" as follows:
vcpkg_download_distfile(
    VS2017PATCH
    URLS "https://github.com/gwaldron/osgearth/archive/master.zip"
    FILENAME "osgearth-master.zip"
    SHA512 cdd9337c1b08627422e753c603968be533b6ebc38a2bd9dcf2c03c7af190702992638b826f6496be17665e154fe70476814b9dd2ee10c647c1f595ee950d545c
)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO gwaldron/osgearth
    REF master
    SHA512 0
    HEAD_REF master
    PATCHES ${VS2017PATCH}
)

![vcpkg](https://user-images.githubusercontent.com/18117662/54086573-7c803880-4385-11e9-8947-90767403ac3f.PNG)
I think the "vcpkg_download_distfile" is OK ,but the "vcpkg_from_github" is error.
How can I  change "master.tar.gz" to "master.zip"

**Comment by Voskrese** [comment]
SHA512 ?

**Comment by Voskrese** [comment]
extract master.tar.gz to vcpkg\buildtrees\osgearth\...\src\..

try again

**Comment by vicroms** [comment]
Hi @zcwbnu 

If you wan't `vcpkg` to build the latest from master then you don't need to modify the portfile.

Just run:
`./vcpkg install osgearth --head`

Here's the relevant section of the docs for [`vcpkg_from_github()`](https://github.com/Microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_from_github.md):

> HEAD_REF
The unstable git commit-ish (ideally a branch) to pull for --head builds.
For most projects, this should be master. The chosen branch should be one that is expected to be always buildable on all supported platforms.

**Comment by Cheney-W** [comment]
@zcwbnu , please refer to this [PR](https://github.com/microsoft/vcpkg/pull/4176) to fulfill your needs. If you have other questions, please resubmit an issue. Thank you!
