### ISSUE TITLE
Error: building package opencv:x64-uwp failed (also x86-uwp)

### ISSUE THREAD

**Issue by mkwiczalayandex** [Microsoft/vcpkg#562]
-- CURRENT_INSTALLED_DIR=C:/develop/repos/vcpkg/installed/x64-uwp
-- DOWNLOADS=C:/develop/repos/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/develop/repos/vcpkg/packages/opencv_x64-uwp
-- CURRENT_BUILDTREES_DIR=C:/develop/repos/vcpkg/buildtrees/opencv
-- CURRENT_PORT_DIR=c:/develop/repos/vcpkg/ports/opencv/.
-- Using cached C:/develop/repos/vcpkg/downloads/opencv-92387b1ef8fad15196dd5f7fb4931444a68bc93a.zip
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch C:/develop/repos/vcpkg/ports/opencv/opencv-installation-options.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/develop/repos/vcpkg/ports/opencv/opencv-installation-options.patch done
-- Configuring x64-uwp-rel
-- Configuring x64-uwp-rel done
-- Configuring x64-uwp-dbg
-- Configuring x64-uwp-dbg done
-- Package x64-uwp-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: C:/Program Files (x86)/CMake/bin/cmake.exe;--build;.;--config;Release;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/m
    Working Directory: C:/develop/repos/vcpkg/buildtrees/opencv/x64-uwp-rel
    See logs for more information:
      C:\develop\repos\vcpkg\buildtrees\opencv\package-x64-uwp-rel-out.log
      C:\develop\repos\vcpkg\buildtrees\opencv\package-x64-uwp-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:16 (vcpkg_execute_required_process)
  ports/opencv/portfile.cmake:49 (vcpkg_install_cmake)
  scripts/ports.cmake:73 (include)

Error: building package opencv:x64-uwp failed
Please ensure sure you're using the latest portfiles with `vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv:x64-uwp
  Vcpkg version: 0.0.66-0d50c6704ddc563f459b901297bbb909adaa6e51

Additionally, attach any relevant sections from the log files above.

**Comment by ras0219-msft** [comment]
Unfortunately, the `opencv` portfile doesn't currently support building for UWP.

+@stammen who may be interested.

**Comment by stammen** [comment]
What is the error in

C:\develop\repos\vcpkg\buildtrees\opencv\package-x64-uwp-rel-out.log
C:\develop\repos\vcpkg\buildtrees\opencv\package-x64-uwp-rel-err.log

**Comment by mkwiczalayandex** [comment]
There is 123 Errors.
First one:
```
5>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\agile.h(19): fatal error C1189: #error:  agile.h can only be used with /ZW (compiling source file C:\develop\repos\vcpkg\buildtrees\opencv\src\opencv-92387b1ef8fad15196dd5f7fb4931444a68bc93a\modules\videoio\src\cap_winrt_bridge.cpp) [C:\develop\repos\vcpkg\buildtrees\opencv\x64-uwp-rel\modules\world\opencv_world.vcxproj]
         cap_winrt_video.cpp 
```
Files in attachment.
[opencv.zip](https://github.com/Microsoft/vcpkg/files/718706/opencv.zip)

**Comment by zabulus** [comment]
What should be done here? 
Just add /ZW compilation flag for CMAKE_SYSTEM_NAME==WindowsStore? 
Shouldn't CMake itself add it?

**Comment by adamyaxley** [comment]
This happens for me too with Vcpkg version: 0.0.75:

Error: Building package opencv:x86-uwp failed with: BUILD_FAILED
Please ensure sure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv:x86-uwp
  Vcpkg version: 0.0.75-cabf99d53fda160af95629f508228b47a7cf25c7

After inspecting buildtrees/opencv/config-x86-rel-err.log it looks like it fails to find the precompiled headers:

CMake Error at cmake/OpenCVUtils.cmake:911 (add_library):
  Cannot find source file:

    C:/vcpkg/buildtrees/opencv/x86-uwp-rel/modules/core/opencv_core_pch.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  cmake/OpenCVModule.cmake:784 (ocv_add_library)
  cmake/OpenCVModule.cmake:729 (_ocv_create_module)
  modules/core/CMakeLists.txt:34 (ocv_create_module)


CMake Error at cmake/OpenCVUtils.cmake:911 (add_library):
  Cannot find source file:

    C:/vcpkg/buildtrees/opencv/x86-uwp-rel/modules/flann/opencv_flann_pch.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  cmake/OpenCVModule.cmake:784 (ocv_add_library)
  cmake/OpenCVModule.cmake:729 (_ocv_create_module)
  cmake/OpenCVModule.cmake:942 (ocv_create_module)
  modules/flann/CMakeLists.txt:2 (ocv_define_module)

**Comment by NancyLi1013** [comment]
This issue should be fixed. Please open a new issue if this is still a problem for you.
