### ISSUE TITLE
VS integration fails when "msbuild *.vcxproj" from command line

### ISSUE THREAD

**Issue by wm1** [Microsoft/vcpkg#563]
**Repro**:
- vcpkg integrate install
- vcpkg install wtl
- in VS 2015, create a new VC++ Win32 project
- add #include <wtl/atlapp.h> to one of source code. notice that auto completion finds the header file
- build in VS works fine: `Build started: Project: Win32Project1, Configuration: Debug Win32` 
- open a command window. 
  * msbuild.exe *.sln also works fine: `Building solution configuration "Debug|x86"`
  * msbuild.exe *.vcxproj fails with `win32project1.cpp(7): fatal error C1083: Cannot open include file: 'wtl\atlapp.h': No such file or directory`

**Cause**:
The vcxproj file generated by VS template does not contains a `Platform` property. When vcpkg.targets is called, it cannot figure out the correct value of `VcpkgTriplet`, thus won't update include path accordingly.
```
D:\git\github\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets
%LOCALAPPDATA%\vcpkg\vcpkg.user.targets
%ProgramFiles(x86)%\MSBuild\Microsoft.Cpp\v4.0\V140\ImportBefore\Default\vcpkg.system.props
%ProgramFiles(x86)%\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Default.props
D:\Projects\Win32Project1\Win32Project1\Win32Project1.vcxproj
```

**Comment by alexkaratarakis** [comment]
I believe 030ed271179ac57479d4bfec2e64b9457486d4c5 fixes this. 
Could you verify that it works for you?

**Comment by wm1** [comment]
It works now. thanks,
