### ISSUE TITLE
Failed To Download ninja “Failure when receiving data from the peer”  "Couldn't connect to server"

### ISSUE THREAD

**Issue by 874656645** [microsoft/vcpkg#5631]
situation 1：

PS C:\Windows\system32> vcpkg install zlib
The following packages will be built and installed:
    zlib[core]:x86-windows
Starting package 1/1: zlib:x86-windows
Building package zlib[core]:x86-windows...
Warning: The following VS instances are excluded because the English language pack is unavailable.
    D:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
Please install the English language pack.
-- Using cached F:/OpenSourceProject/vcpkg/downloads/zlib1211.tar.gz
-- Using source at F:/OpenSourceProject/vcpkg/buildtrees/zlib/src/1.2.11-f690224aeb
-- Downloading https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip...
-- **Downloading https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip... Failed. Status: 56;"Failure when receiving data from the peer"**
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:156 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:248 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_configure_cmake.cmake:131 (vcpkg_find_acquire_program)
  ports/zlib/portfile.cmake:22 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package zlib:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x86-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

situation 2：

PS C:\Users\CuiZhan> vcpkg install zlib
The following packages will be built and installed:
    zlib[core]:x86-windows
Starting package 1/1: zlib:x86-windows
Building package zlib[core]:x86-windows...
Warning: The following VS instances are excluded because the English language pack is unavailable.
    D:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
Please install the English language pack.
-- Using cached F:/OpenSourceProject/vcpkg/downloads/zlib1211.tar.gz
-- Using source at F:/OpenSourceProject/vcpkg/buildtrees/zlib/src/1.2.11-f690224aeb
-- Downloading https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip...
-- Downloading https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:156 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:248 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_configure_cmake.cmake:131 (vcpkg_find_acquire_program)
  ports/zlib/portfile.cmake:22 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package zlib:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x86-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by Voskrese** [comment]
Warning: The following VS instances are excluded because the English language pack is unavailable.
D:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
Please install the English language pack.

Please install the English language pack.

**Comment by wangli28** [comment]
Hi @874656645,

Please install the English language package of Visual Studio following these steps:

1. Open Visual Studio Installer.
2. Click 'Modify' and choose 'Language packs'.
3. Choose English and install it.

You can install zlib again after install the English language package successfully.

Thanks

**Comment by 874656645** [comment]
> Warning: The following VS instances are excluded because the English language pack is unavailable.
> D:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
> Please install the English language pack.
> Please install the English language pack.

Thanks  a lot. It worked when I've installed vs2017's English language pack.
In fact I have vs2015 and vs2017 on my computer. I've installed vs2015's english language pack. But it did not work. I just want to build the lib version of vs2015, so can I specify the version of compiler with vcpkg?  What am I supposed to do if I can?
I appreciate your help very much and anticipate your response in the respect .

**Comment by JackBoosY** [comment]
Hi @874656645 , You can add this code to every cmake file in the path "vcpkg/triplets/":
`set(VCPKG_PLATFORM_TOOLSET v140)`

**Comment by 874656645** [comment]
> Hi @874656645 , You can add this code to every cmake file in the path "vcpkg/triplets/":
> set(VCPKG_PLATFORM_TOOLSET v140)
> And then rebuild ports.

Hello there, What do you mean "rebuild ports"? I've added that code and rebuilded vcpkg, but it did not work.

**Comment by JackBoosY** [comment]
Hi @874656645 , if there is still a download failure problem, please use the displayed url: ```https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip``` to manually download and put the downloaded zip under ```vcpkg\downloads``` directory, and then rebuild zlib.
Thx.

**Comment by 874656645** [comment]
Downloading is not a problem any more after I install vs2017‘s English language package. Although I don't know the connection between this two problems, the strange hint is a little misunderstanding for me. 
I've added that code and rebuilded vcpkg, but it did not work. It‘s still compiled with vs2017. By the way, I use win10 system. Do you have any idea with what's going on？

**Comment by JackBoosY** [comment]
@874656645  Please provide the log that failed after installing the English Language Pack, thanks.

**Comment by 874656645** [comment]
[1/2] cmd /c "cd .. && "D:/Program Files/CMake/bin/cmake.exe" "F:/OpenSourceProject/vcpkg/buildtrees/zlib/src/1.2.11-f690224aeb" "-DSKIP_INSTALL_FILES=ON" "-DSKIP_BUILD_EXAMPLES=ON" "-DCMAKE_MAKE_PROGRAM=F:/OpenSourceProject/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=F:/OpenSourceProject/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=F:/OpenSourceProject/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=F:/OpenSourceProject/vcpkg/packages/zlib_x86-windows""
FAILED: ../CMakeCache.txt 
cmd /c "cd .. && "D:/Program Files/CMake/bin/cmake.exe" "F:/OpenSourceProject/vcpkg/buildtrees/zlib/src/1.2.11-f690224aeb" "-DSKIP_INSTALL_FILES=ON" "-DSKIP_BUILD_EXAMPLES=ON" "-DCMAKE_MAKE_PROGRAM=F:/OpenSourceProject/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=F:/OpenSourceProject/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=F:/OpenSourceProject/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=F:/OpenSourceProject/vcpkg/packages/zlib_x86-windows""
CMake Warning at F:/OpenSourceProject/vcpkg/scripts/buildsystems/vcpkg.cmake:95 (message):
  There are no libraries installed for the Vcpkg triplet x86-windows.
Call Stack (most recent call first):
  D:/Program Files/CMake/share/cmake-3.14/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:4 (project)


-- The C compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe -- broken
CMake Error at D:/Program Files/CMake/share/cmake-3.14/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: F:/OpenSourceProject/vcpkg/buildtrees/zlib/x86-windows-rel/CMakeFiles/CMakeTmp
    
    Run Build Command(s):F:/OpenSourceProject/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe cmTC_dced7 
    [1/2] Building C object CMakeFiles\cmTC_dced7.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_dced7.exe
    FAILED: cmTC_dced7.exe 
    cmd.exe /C "cd . && "D:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_dced7.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- "D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64_x86\link.exe" /nologo CMakeFiles\cmTC_dced7.dir\testCCompiler.c.obj  /out:cmTC_dced7.exe /implib:cmTC_dced7.lib /pdb:cmTC_dced7.pdb /version:0.0  /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /foCMakeFiles\cmTC_dced7.dir/manifest.res CMakeFiles\cmTC_dced7.dir/manifest.rc" failed (exit code 0) with the following output:
    系统找不到指定的文件。
    ninja: build stopped: subcommand failed.

**Comment by JackBoosY** [comment]
@874656645 Could you re-clone vcpkg and install this port in another directory?
Thx.

**Comment by 874656645** [comment]
It does not work. Here is the out log.

[1/2] cmd /c "cd ../../x86-windows-dbg && "D:/Program Files/CMake/bin/cmake.exe" "E:/vcpkg/buildtrees/zlib/src/1.2.11-f690224aeb" "-DSKIP_INSTALL_FILES=ON" "-DSKIP_BUILD_EXAMPLES=ON" "-DCMAKE_MAKE_PROGRAM=E:/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=E:/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=E:/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-DSKIP_INSTALL_HEADERS=ON" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=E:/vcpkg/packages/zlib_x86-windows/debug""
FAILED: ../../x86-windows-dbg/CMakeCache.txt 
cmd /c "cd ../../x86-windows-dbg && "D:/Program Files/CMake/bin/cmake.exe" "E:/vcpkg/buildtrees/zlib/src/1.2.11-f690224aeb" "-DSKIP_INSTALL_FILES=ON" "-DSKIP_BUILD_EXAMPLES=ON" "-DCMAKE_MAKE_PROGRAM=E:/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=E:/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=E:/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-DSKIP_INSTALL_HEADERS=ON" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=E:/vcpkg/packages/zlib_x86-windows/debug""
CMake Warning at E:/vcpkg/scripts/buildsystems/vcpkg.cmake:95 (message):
  There are no libraries installed for the Vcpkg triplet x86-windows.
Call Stack (most recent call first):
  D:/Program Files/CMake/share/cmake-3.14/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:4 (project)


-- The C compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe -- broken
CMake Error at D:/Program Files/CMake/share/cmake-3.14/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: E:/vcpkg/buildtrees/zlib/x86-windows-dbg/CMakeFiles/CMakeTmp
    
    Run Build Command(s):E:/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe cmTC_ed5c4 
    [1/2] Building C object CMakeFiles\cmTC_ed5c4.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_ed5c4.exe
    FAILED: cmTC_ed5c4.exe 
    cmd.exe /C "cd . && "D:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_ed5c4.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- "D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64_x86\link.exe" /nologo CMakeFiles\cmTC_ed5c4.dir\testCCompiler.c.obj  /out:cmTC_ed5c4.exe /implib:cmTC_ed5c4.lib /pdb:cmTC_ed5c4.pdb /version:0.0  /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /foCMakeFiles\cmTC_ed5c4.dir/manifest.res CMakeFiles\cmTC_ed5c4.dir/manifest.rc" failed (exit code 0) with the following output:
    系统找不到指定的文件。
    ninja: build stopped: subcommand failed.
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)


-- Configuring incomplete, errors occurred!
See also "E:/vcpkg/buildtrees/zlib/x86-windows-dbg/CMakeFiles/CMakeOutput.log".
See also "E:/vcpkg/buildtrees/zlib/x86-windows-dbg/CMakeFiles/CMakeError.log".
[2/2] cmd /c "cd .. && "D:/Program Files/CMake/bin/cmake.exe" "E:/vcpkg/buildtrees/zlib/src/1.2.11-f690224aeb" "-DSKIP_INSTALL_FILES=ON" "-DSKIP_BUILD_EXAMPLES=ON" "-DCMAKE_MAKE_PROGRAM=E:/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=E:/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=E:/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=E:/vcpkg/packages/zlib_x86-windows""
FAILED: ../CMakeCache.txt 
cmd /c "cd .. && "D:/Program Files/CMake/bin/cmake.exe" "E:/vcpkg/buildtrees/zlib/src/1.2.11-f690224aeb" "-DSKIP_INSTALL_FILES=ON" "-DSKIP_BUILD_EXAMPLES=ON" "-DCMAKE_MAKE_PROGRAM=E:/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=E:/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=E:/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=E:/vcpkg/packages/zlib_x86-windows""
CMake Warning at E:/vcpkg/scripts/buildsystems/vcpkg.cmake:95 (message):
  There are no libraries installed for the Vcpkg triplet x86-windows.
Call Stack (most recent call first):
  D:/Program Files/CMake/share/cmake-3.14/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:4 (project)


-- The C compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe -- broken
CMake Error at D:/Program Files/CMake/share/cmake-3.14/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: E:/vcpkg/buildtrees/zlib/x86-windows-rel/CMakeFiles/CMakeTmp
    
    Run Build Command(s):E:/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe cmTC_4f404 
    [1/2] Building C object CMakeFiles\cmTC_4f404.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_4f404.exe
    FAILED: cmTC_4f404.exe 
    cmd.exe /C "cd . && "D:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_4f404.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- "D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64_x86\link.exe" /nologo CMakeFiles\cmTC_4f404.dir\testCCompiler.c.obj  /out:cmTC_4f404.exe /implib:cmTC_4f404.lib /pdb:cmTC_4f404.pdb /version:0.0  /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /foCMakeFiles\cmTC_4f404.dir/manifest.res CMakeFiles\cmTC_4f404.dir/manifest.rc" failed (exit code 0) with the following output:
    系统找不到指定的文件。
    ninja: build stopped: subcommand failed.
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)


-- Configuring incomplete, errors occurred!
See also "E:/vcpkg/buildtrees/zlib/x86-windows-rel/CMakeFiles/CMakeOutput.log".
See also "E:/vcpkg/buildtrees/zlib/x86-windows-rel/CMakeFiles/CMakeError.log".
ninja: build stopped: subcommand failed.

**Comment by JackBoosY** [comment]
@ras0219-msft I think it's a Visual Studio bug.

**Comment by LilyWangL** [comment]
@874656645 Does this issue still occur?

**Comment by 874656645** [comment]
Thank you for help. Maybe it is the Internet problem of my company for all the downloading errors. I always fail to visit GitHub when I am at the company.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vcpkg"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月22日(星期三) 下午5:43
收件人:&nbsp;"microsoft/vcpkg"<vcpkg@noreply.github.com&gt;;
抄送:&nbsp;"记忆碎片"<874656645@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/vcpkg] Failed To Download ninja “Failure when receiving data from the peer”  "Couldn't connect to server" (#5631)





 
@874656645 Does this issue still occur?

**Comment by LilyWangL** [comment]
Thanks for your reply, I close this pr temporarily, if you have other question about VCPKG, please open a new issue.
