### ISSUE TITLE
bootstrap-vcpkg.bat not found

### ISSUE THREAD

**Issue by Peeping-Peacock** [Microsoft/vcpkg#5633]
Same problem as #4840

Cannot find any of the commands in bash

If someone could explain how to solve this trivial problem so that other people like me bumbling around wont bother people with more important problems it would be much appreciated.

**Comment by nightslashs** [comment]
The .bat file is for a dos terminal whereas a bash terminal will need to use bootstrap-vcpkg.sh

**Comment by vicroms** [comment]
Here's the relevant section of the docs.

To get started:

```
> git clone https://github.com/Microsoft/vcpkg.git
> cd vcpkg

PS> .\bootstrap-vcpkg.bat
Linux:~/$ ./bootstrap-vcpkg.sh
```

**Comment by Peeping-Peacock** [comment]
Thank you all! 
It was a problem with using the wrong .exe like nightslashs suggested, how embarrassing.

Thanks again for the help!

**Comment by deon16** [comment]
I am complete new here and having a same issue? Any ideas?
using default command under Windows 10 (.\bootstrap-vcpkg.bat) presents me with:

.bootstrap-vcpkg.bat: command not found windows 10

**Comment by degski** [comment]
@super21z I danced around the x-mas-tree and had much success with that. Just to be clear, I first [before dancing] turned the (tree-)lights of for 10 secs, and then on again for 5 secs, repeating this process 5 times (obviously).
