### ISSUE TITLE
find_package(Qt) in VS2019 issue

### ISSUE THREAD

**Issue by Zingam** [microsoft/vcpkg#5636]
I have Qt5 installed in `C:\SDKs\Qt\5.12.0\msvc2017_64` and env variable set to the same path:

```CMake
# Add Qt5 install location to search path
if (NOT DEFINED ENV{Qt5_ROOT})
  message (FATAL_ERROR "Environment variable Qt5_ROOT not found. Is Qt5 installed? ")
endif ()

cmake_policy (SET CMP0074 NEW)
list (APPEND CMAKE_PREFIX_PATH $ENV{Qt5_ROOT})

# Find includes in corresponding build directories
set(CMAKE_INCLUDE_CURRENT_DIR ON)
# Instruct CMake to run moc automatically when needed
set(CMAKE_AUTOMOC ON)
# Create code from a list of Qt designer ui files
set(CMAKE_AUTOUIC ON)

# Find the QtWidgets library
find_package (Qt5 COMPONENTS Core Widgets CONFIG REQUIRED)
target_link_libraries (${PROJECT_NAME}
  PRIVATE
    Qt5::Widgets
)
```

I get the warning in `VS2019`:

```
1> [CMake] CMake version: 3.13.19010201-MSVC_2
1> [CMake] CMake Warning (dev) at C:/SDKs/vcpkg/scripts/buildsystems/vcpkg.cmake:253 (_find_package):
1> [CMake]   Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
1> [CMake]   Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
1> [CMake]   command to set the policy and suppress this warning.
1> [CMake] 
1> [CMake]   Environment variable Qt5_ROOT is set to:
1> [CMake] 
1> [CMake]     C:\SDKs\Qt\5.12.0\msvc2017_64
1> [CMake] 
1> [CMake]   For compatibility, CMake is ignoring the variable.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   Sources/SSHCopy/CMakeLists.txt:72 (find_package)
1> [CMake] This warning is for project developers.  Use -Wno-dev to suppress it.
1> [CMake] Shared libraries to install:
```

**Comment by Neumann-A** [comment]
> Commands created by the function() and macro() commands record policy settings when they are created and use the pre-record policies when they are invoked. If the function or macro implementation sets policies, the changes automatically propagate up through callers until they reach the closest nested policy stack entry.

So you must define the policy before the toolchain file is loaded. Maybe use a wrapper toolchain for that which just includes the vcpkg toolchain after setting policies. There is no other way because the vcpkg toolchain defines a hook/macro redefinition for `find_package() `

**Comment by Zingam** [comment]
`vcpkg` integrates itself into VS2019. I use `vcpkg` to get the files but I don't use it's toolchain. I provide my `find_package` modules. In my case `vcpkg` interferes uninvited.

**Comment by Neumann-A** [comment]
It cannot be taught to behave due to:

> Commands created by the function() and macro() commands record policy settings when they are created and use the pre-record policies when they are invoked.

the find_package macro is created with the toolchain file which is loaded before your code is executed. 
You have to supply VS2019 somehow with a costume toolchain file which sets the policy and then includes the vcpkg toolchain. 
This seems not to be a vcpkg but more a VS2019 issues, so please also report it there.

**Comment by Neumann-A** [comment]
@JackBoosY: should be closed
