### ISSUE TITLE
[New Port Request] catapult-server

### ISSUE THREAD

**Issue by st-wong** [microsoft/vcpkg#5642]
I'm trying to build this [project](https://github.com/nemtech/catapult-server/blob/master/BUILDING.md) using vcpkg but have been facing many challenges. Mainly during building, it fails to detect the right packages managed by vcpkg after passing in the toolchain file flag (-DCMAKE_TOOLCHAIN_FILE=[vcpkg root]\scripts\buildsystems\vcpkg.cmake). Any help is much appreciated, thanks.

**Comment by nightslashs** [comment]
Try to invoke the cmake command with "-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON" which will let us know where it is searching for various things. If you could run that command and attach the output that would be very helpful!

**Comment by st-wong** [comment]
Will update on this soon, I recently moved to vs 2019 so the errors now are not the same as before but I'll look into getting what I had before and post the output. Thanks.

**Comment by st-wong** [comment]
Finally got around to this, re-installed VS 2017 and made it work with instructions here:
https://gist.github.com/st-wong/531a36aaa492d0308cfc06689813bd94

**Comment by st-wong** [comment]
VS 2019 works now with version 16.1.x onwards and I got the build working without using VCPKG Boost Libs. Whenever I use Boost libs from VCPKG, during `msbuild /p:Configuration=RelWithDebInfo /p:Platform=x64 ALL_BUILD.vcxproj` process, I keep getting errors on not being able to copy the lib files from the vcpkg folder to the project folder and I have removed `read-only` attribute on the vcpkg/install folder.

I got things working by using a manual boost build instead and even modified VCPKG mongo-cxx-driver to use the manual boost build too.

Two things I will need help is:
- How to generate boost libs to use 1.69 version? I have modified generate-port to 1.69 but script seems to fail on downloads and generating SHA
- How to get VCPKG boost libs to work with the project?

**Comment by LeonineKing1199** [comment]
If you wanna regress to 1.69, check out:
>  If you need to then pin a specific library forward, that is as easy as checking out the appropriate version of ports\<package>\.

from:
https://github.com/microsoft/vcpkg/blob/master/docs/about/faq.md#how-do-i-use-different-versions-of-a-library-on-one-machine

**Comment by st-wong** [comment]
```
If you wanna regress to 1.69, check out:

If you need to then pin a specific library forward, that is as easy as checking out the appropriate version of ports<package>.

from:
https://github.com/microsoft/vcpkg/blob/master/docs/about/faq.md#how-do-i-use-different-versions-of-a-library-on-one-machine
```

This probably works with other libs as I have done with some of them on my fork, but for boost, I believe generate-port script is needed which doesn't seem to work  as I mentioned.

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
