### ISSUE TITLE
Qt5 installation error on Ubuntu (wsl)

### ISSUE THREAD

**Issue by Ben1980** [microsoft/vcpkg#5655]
Cant build/install qt5 on ubuntu (wsl). Probably related to #5362 and #4755.
Error:unable to find qmake.

------
Starting package 1/28: qt5-websockets:x64-linux
Building package qt5-websockets[core]:x64-linux...
CMake Warning at installed/x64-linux/share/qt5modularscripts/qt_modular_library.cmake:6 (message):
  Qt5's buildsystem uses very long paths and may fail on your system.

  We recommend moving vcpkg to a short path such as 'C:\src\vcpkg' or using
  the subst command.
Call Stack (most recent call first):
  ports/qt5-websockets/portfile.cmake:5 (qt_modular_library)
  scripts/ports.cmake:71 (include)

-- Using cached /mnt/c/Develop/vcpkg/downloads/qtwebsockets-everywhere-src-5.12.1.tar.xz
-- Using source at /mnt/c/Develop/vcpkg/buildtrees/qt5-websockets/src/5.12.1-b7138f8e70
CMake Error at scripts/cmake/vcpkg_configure_qmake.cmake:23 (message):
  vcpkg_configure_qmake: unable to find qmake.
Call Stack (most recent call first):
  installed/x64-linux/share/qt5modularscripts/qt_modular_library.cmake:45 (vcpkg_configure_qmake)
  ports/qt5-websockets/portfile.cmake:5 (qt_modular_library)
  scripts/ports.cmake:71 (include)

Error: Building package qt5-websockets:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qt5-websockets:x64-linux
  Vcpkg version: 2018.11.23-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by vicroms** [comment]
PR #5624 is currently being worked on, and it fixes Qt 5 builds for some packages in Linux and Mac.

**Comment by Ben1980** [comment]
Just an update, after git pull/update/upgrade today i get now the following error:

-- Using cached /mnt/c/Develop/vcpkg/downloads/qtwebsockets-everywhere-src-5.12.1.tar.xz
-- Using source at /mnt/c/Develop/vcpkg/buildtrees/qt5-websockets/src/5.12.1-b7138f8e70
-- Configuring x64-linux-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: /usr/bin/qmake;CONFIG-=debug;CONFIG+=release;CONFIG+=staticlib;/mnt/c/Develop/vcpkg/buildtrees/qt5-websockets/src/5.12.1-b7138f8e70;-qtconf;/mnt/c/Develop/vcpkg/buildtrees/qt5-websockets/x64-linux-rel/qt.conf
    Working Directory: /mnt/c/Develop/vcpkg/buildtrees/qt5-websockets/x64-linux-rel
    Error code: 1
    See logs for more information:
      /mnt/c/Develop/vcpkg/buildtrees/qt5-websockets/config-x64-linux-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_qmake.cmake:37 (vcpkg_execute_required_process)
  installed/x64-linux/share/qt5modularscripts/qt_modular_library.cmake:45 (vcpkg_configure_qmake)
  ports/qt5-websockets/portfile.cmake:5 (qt_modular_library)
  scripts/ports.cmake:71 (include)


Error: Building package qt5-websockets:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qt5-websockets:x64-linux
  Vcpkg version: 2018.11.23-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by vicroms** [comment]
Hi @Ben1980 

Please attach the contents of `vcpkg/buildtrees/qt5-websockets/config-x64-linux-rel-err.log`.

**Comment by Ben1980** [comment]
Its again qmake, but this time its looking for Qt.....
config-x64-linux-rel-err.log: qmake: could not find a Qt installation of ''

**Comment by S3riousSam** [comment]
The content of "config-x64-linux-rel-err.log" file for me:
> qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory

**Comment by JackBoosY** [comment]
@Ben1980 I noticed that there is a warning:
> CMake Warning at installed/x64-linux/share/qt5modularscripts/qt_modular_library.cmake:6 (message):
Qt5's buildsystem uses very long paths and may fail on your system.

And your error log shows:
> could not find a Qt installation of ''

So, please re-clone vcpkg in the root path and rebuild qt5.

Thanks.

**Comment by JackBoosY** [comment]
Hi @Ben1980, thanks for reporting this issue!
I've fixed qt5-linux build, please update vcpkg and rebuild qt5.

Thanks.
