### ISSUE TITLE
CMAKE_SYSTEM_VERSION question

### ISSUE THREAD

**Issue by 0-wiz-0** [Microsoft/vcpkg#5658]
We're using vcpkg on appveyor to provide dependencies for the CI of https://github.com/nih-at/libzip/
We don't know much about Windows or vcpkg; someone was so nice to set this up for us once. A couple months ago it stopped working for UWP, it's still working on x86 and arm (not UWP), see e.g. https://ci.appveyor.com/project/0-wiz-0/libzip

You can see a failing log at e.g.
https://ci.appveyor.com/project/0-wiz-0/libzip/build/job/cy4xs58ae9kd2s59
The build ends with
````
cmake -DCMAKE_TOOLCHAIN_FILE=%cd%/../vcpkg/scripts/buildsystems/vcpkg.cmake .. -G "%GENERATOR%" %CMAKE_OPTS%
CMake Error at CMakeLists.txt:8 (PROJECT):
  Visual Studio 15 2017 supports Windows Store '8.0', '8.1' and '10.0', but
  not ''.  Check CMAKE_SYSTEM_VERSION.
````
where `GENERATOR` is `Visual Studio 15 2017` and `CMAKE_OPTS` is `-DCMAKE_SYSTEM_NAME=WindowsStore`.

Can someone please help us? What do we need to pass where so the UWP build will start working and the non-UWP build stay working?

Thank you.

**Comment by Voskrese** [comment]
?
`-DCMAKE_SYSTEM_VERSION=8.1 or ...`

`set(CMAKE_SYSTEM_VERSION 8.1)  or ...`

**Comment by 0-wiz-0** [comment]
Thank you, that lets it proceed to a different error. The UWP build does not find the BCrypt symbols even though `bcrypt.h` is included. If you have an idea for that as well I'd be grateful, but I don't expect that :)

**Comment by Voskrese** [comment]
call envVScmd

`where $INCLUDE:bcrypt.h`

`C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared\bcrypt.h`

install Windows SDK ! ))

**Comment by 0-wiz-0** [comment]
Thanks again for the answer.
The problem is not that the header is not found -- it is found and used (at least I don't see an error about that). And I'm pretty sure the SDK is installed, see this part in the cmake output:
````
GetInstalledSDKLocations:
  Searching for SDKs targeting "Windows, 8.1".
ResolveSDKReferences:
    Reading SDK manifest file "C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1\ExtensionSDKs\Microsoft.VCLibs\12.0\SDKManifest.xml".
````
But at least some symbols (probably all) are missing. There are errors like:
````
warning C4013: 'BCRYPT_SUCCESS' undefined; 
warning C4013: 'BCryptOpenAlgorithmProvider' undefined
warning C4013: 'GetFileSizeEx' undefined
(more)
````
see https://ci.appveyor.com/project/0-wiz-0/libzip/build/job/c82bjgcym5jrkll3 for the full log.
