### ISSUE TITLE
Trying to package VST3 SDK, but...

### ISSUE THREAD

**Issue by NebuHiiEjamu** [microsoft/vcpkg#5660]
So I've been trying to make a PR for VST3. After a lot of frustration, I've almost finished it, however, there are some issues:

- Built libraries (static only for Windows, by the way, can't do DLL) mostly have really generic filenames (ie. base.lib and sdk.lib) which, if changed, may make building plugins out of the box a bit... difficult

- The header path is also very generic ("public.sdk/source/") and I can't change that without people needing to make sweeping include path changes to plugin code.

- The SDK has the option to use the system Expat (vcpkg dependency in this case). However, attempting to build this results in expat.h not being found during build time, despite its detection at configure time. I'm not sure where the include path is getting changed, if at all, but the only way I can do a successful compile, currently, is by explicitly using its internal Expat copy.

CONTROL:
```
Source: vst3sdk
Version: 3.6.12
Build-Depends: expat
Description: VST 3 Plug-In SDK

Feature: tools
Description: VSTGUI Tools
```

portfile.cmake (explicit install phase is incomplete, VST3's CMake files do not have an INSTALL target):
```
include(vcpkg_common_functions)

set(VERSION 3.6.12)

vcpkg_download_distfile(ARCHIVE
    URLS "https://download.steinberg.net/sdk_downloads/vstsdk3612_03_12_2018_build_67.zip"
    FILENAME "vst3sdk.zip"
    SHA512 7f39bf01c055c6ae11f8d982222b511446b9dd9d04ba41344d0d9692ecf491f1e994e8e7e432fef3846eb768ba88a537be46a0b2cd6b9793b72f211ea5c67630
)

vcpkg_extract_source_archive_ex(
    OUT_SOURCE_PATH SOURCE_PATH
    ARCHIVE ${ARCHIVE}
    REF ${VERSION}
)

set(VSTGUI_HAVE_TOOLS "OFF")
if("tools" IN_LIST FEATURES)
    set(VSTGUI_HAVE_TOOLS "ON")
endif()

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}/VST3_SDK
    PREFER_NINJA
    OPTIONS
        -DSMTG_ADD_VST3_HOSTING_SAMPLES=OFF
        -DSMTG_ADD_VST3_PLUGINS_SAMPLES=OFF
        -DSMTG_VSTGUI_TOOLS=${VSTGUI_HAVE_TOOLS}
)

vcpkg_build_cmake()

if("tools" IN_LIST FEATURES)
    file(MAKE_DIRECTORY ${CURRENT_PACKAGES_DIR}/tools/vst3sdk)
    file(INSTALL ${CMAKE_BINARY_DIR}/bin/Release/ImageStitcher.exe DESTINATION ${CURRENT_PACKAGES_DIR}/tools/vst3sdk)
    file(INSTALL ${CMAKE_BINARY_DIR}/bin/Release/uidesccompressor.exe DESTINATION ${CURRENT_PACKAGES_DIR}/tools/vst3sdk)
    vcpkg_copy_tool_dependencies(${CURRENT_PACKAGES_DIR}/tools/vst3sdk)
endif()

file(INSTALL ${SOURCE_PATH}/VST3_SDK/LICENSE.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/vst3sdk/copyright)
```

**Comment by PhoebeHui** [comment]
@NebuHiiEjamu, cou;ld you submit a PR for this?

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue and submit a PR for this port, but we're closing it for now.

**Comment by GavinRay97** [comment]
This would be great to have!

If I understand it right, the issues mentioned in the PR aren't blockers but more "things to be aware of"?
What I got from it:

- Can't build shared libs/`.dll` for some reason, only static
	- Built libs are named `base.lib` and `sdk.lib`
- Header path forcibly `public.sdk/source/` and there's not much to be done about it, outside from massive code changes
- Unable to use system `libexpat`, must build using VST3's internal copy

Personally I am fine with all of these and I think a good number of people would be.

This is a high-value library that (IMO) is painful to manually set up in projects due to the way their CMake stuff is authored.

@PhoebeHui If I re-open this PR would it get accepted?

@NebuHiiEjamu Do you have any interest in finishing this/submitting a PR?
If not, may I re-use your existing work to submit the PR and credit you?

**Comment by GavinRay97** [comment]
Okay there were some changes in the CMake stuff. I've never written a Port before and I also don't know CMake very well, but based on the earlier draft, I think roughly something like this should be close?

I'm not very experienced with C++ stuff, I  will try to figure out how to test this out and see if it works on a local CMake project.

```json
{
  "name": "vst3sdk",
  "version-string": "3.7.3_build_20",
  "homepage": "https://github.com/steinbergmedia/vst3sdk",
  "description": "Steinberg VST 3 Plug-In SDK",
  "dependencies": [],
  "default-features": [],
  "features": [
    {
      "name": "SMTG_ADD_VSTGUI",
      "description": "Enables VSTGUI support in the SDK",
      "dependencies": []
    }
  ]
}
```
```cmake
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO steinbergmedia/vst3sdk
    REF v3.7.3_build_20
)

vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
        # Name in JSON     # CMake Variable -D definition
        SMTG_ADD_VSTGUI    SMTG_ADD_VSTGUI
)

vcpkg_configure_cmake(
  SOURCE_PATH "${SOURCE_PATH}"
  PREFER_NINJA
  OPTIONS
    ${FEATURE_OPTIONS}
    -DSMTG_ADD_VST3_PLUGINS_SAMPLES=OFF
)

vcpkg_install_cmake()
vcpkg_fixup_cmake_targets()

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/doc")

file(
    INSTALL ${SOURCE_PATH}/LICENSE.txt
    DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT}
    RENAME copyright)
```
