### ISSUE TITLE
how to set the parallel core number?

### ISSUE THREAD

**Issue by yajiedesign** [microsoft/vcpkg#5663]
I am use  incredibuild with vcpkg use command `BuildConsole /command="vcpkg.exe install qt5:x64-windows-static"`. 
But vcpkg only assigns the same number of tasks as my cpu core, which makes incredibuild not work adequately. Incredibuild requires a large number of tasks. How to set the number of tasks is similar to `make -j n'?

**Comment by PhoebeHui** [comment]
@yajiedesign, you can  set the core number by set(VCPKG_CONCURRENCY corenumber) in qt5 portfile.cmake file. Reopen this issue if it still be a problem for you.
