### ISSUE TITLE
PCL can not found on this meachine

### ISSUE THREAD

**Issue by charles-sun0v0** [microsoft/vcpkg#5664]

**Comment by sunchaothu** [comment]
I've installed pcl though  vcpkg as below
![pcl](https://user-images.githubusercontent.com/14788898/54329776-2691e600-464e-11e9-861f-4906f968964b.PNG)

Then I  tried to create a cmake project on vs2017 with CMakeLists.txt:
```cmake
cmake_minimum_required(VERSION 2.6)

project(point2mesh)
find_package(pcl CONFIG REQUIRED)
add_subdirectory("point2mesh")
```
also with CMakeSetting.json
```json
"configurations": [
    {
      "name": "x64-Debug",
      "generator": "Visual Studio 15 2017 Win64",
      "configurationType": "Debug",
      "inheritEnvironments": [ "msvc_x64" ],
      "buildRoot": "${projectDir}\\build\\Release_x64",
      "installRoot": "${env.ProgramFiles}\\${name}",
      "cmakeCommandArgs": "-T host=x64",
      "buildCommandArgs": "",
      "ctestCommandArgs": "",
      "variables": [
        {
          "name": "CMAKE_TOOLCHAIN_FILE",
          "value": "E:/dev_tool/vcpkg/scripts/buildsystems/vcpkg.cmake"
        }
      ]
    },
    {
      "name": "x64-Release",
      "generator": "Visual Studio 15 2017 Win64",
      "configurationType": "RelWithDebInfo",
      "inheritEnvironments": [ "msvc_x64" ],
      "buildRoot": "${projectDir}\\build\\Release_x64",
      "installRoot": "${env.ProgramFiles}\\${name}",
      "cmakeCommandArgs": "-T host=x64",
      "buildCommandArgs": "",
      "ctestCommandArgs": "",
      "variables": [
        {
          "name": "CMAKE_TOOLCHAIN_FILE",
          "value": "E:/dev_tool/vcpkg/scripts/buildsystems/vcpkg.cmake"
        }
      ]
    }
  ]
```
but when I generate cmakecache, error occurs: 
```
1> CMake Warning at E:/dev_tool/vcpkg/installed/x64-windows/share/pcl/PCLConfig.cmake:58 (message):
1>   PCL can not be found on this machine
1> Call Stack (most recent call first):
1>   E:/dev_tool/vcpkg/installed/x64-windows/share/pcl/PCLConfig.cmake(437): (pcl_report_not_found)
1>   E:/dev_tool/vcpkg/scripts/buildsystems/vcpkg.cmake(241): (_find_package)
1>   E:\workspace\Lab\point2mesh\point2mesh\CMakeLists.txt(4): (find_package)
```

**Comment by sunchaothu** [comment]
By setting the PCL_DIR
set(PCL_DIR "E:\\dev_tool\\vcpkg\\installed\\x64-windows\\share\\pcl") it finally worked; But I want to know set_DIR is a normal way to use vcpkg?

**Comment by JackBoosY** [comment]
Hi @sunchaothu, thanks for reporting this issue!
We can use the installed port without setting the PORT_DIR path, you only need to change a few configurations:
Modify _CMakeSettings.json_ 
- add these configure:
```"variables": [
  {
    "name": "CMAKE_TOOLCHAIN_FILE",
    "value": "F:\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake"
  }
]
```
- modify _"generator"_ from "**ninja**" to "**Visual Studio 15/16 2015/2017 Win64**"
- comment ```"buildCommandArgs": "-v",```
- Modify other parameters related to the triplet.

I guess your problem may be these:

1. **inheritEnvironments** should be `msvc_x64_x64`.
2. `vcpkg.cmake` path is wrong.
3.  your vcpkg **files** are broken.

**Comment by sunchaothu** [comment]
Thank you for your  reply @JackBoosY ! I have modified CMakeSetting as [above] (https://github.com/Microsoft/vcpkg/issues/5664#issuecomment-472693482) before，but I still have to set PORT_DIR;  I also changed **inheritEnvironments** from `msvc_x64`  to `msvc_x64_x64` and I am sure vcpkg.cmake path is right, but it didn't work. I notice that the error is report by `/vcpkg/installed/x64-windows/share/pcl/PCLConfig.cmake:58 `, so the config.cmake is found but the PCL DIR seems not be set properly.

**Comment by JackBoosY** [comment]
@sunchaothu  Are the other ports working properly? And, did you integrate vcpkg by these command ` vcpkg integrate project` / ` vcpkg integrate install`?

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
