### ISSUE TITLE
On the inability of vcpkg to install a library

### ISSUE THREAD

**Issue by xdw-123** [Microsoft/vcpkg#5667]
Libpq library cannot be installed

**Comment by wangli28** [comment]
Hi @xdw-123,
Can you provide more information? How did you build this library? And what information did vcpkg gives to you?
Thanks.

**Comment by wangli28** [comment]
@xdw-123, thank you for posting the issue, does the issue still occur? I installed it successfully with VS2017 15.9.11 and VCPKG latest source. Please open a new issue if this is still a problem for you.
