### ISSUE TITLE
Use the shell's associated '.txt' text editor if VS Code isn't available

### ISSUE THREAD

**Issue by OlafvdSpek** [microsoft/vcpkg#567]
```
./vcpkg edit lzo
Visual Studio Code was not found and the environmental variable EDITOR is not set
```

You might want to launch the editor associated with .cpp or with .txt..

**Comment by ras0219-msft** [comment]
We do currently look at the `%EDITOR%` environment variable, but this would be a really nice improvement to the out-of-the-box experience!

**Comment by OlafvdSpek** [comment]
What other software uses %EDITOR%?

**Comment by LilyWangL** [comment]
This issue hasn’t been updated in two year, if it is still an issue, please reopen.
