### ISSUE TITLE
openmvg:x64-windows build failed

### ISSUE THREAD

**Issue by rkcarroll** [Microsoft/vcpkg#5670]
Here is vcpkg upgrade output:
Building package openmvg[core]:x64-windows...
-- Using cached E:/Libs/vcpkg/downloads/openMVG-openMVG-v1.4.tar.gz
-- Using source at E:/Libs/vcpkg/buildtrees/openmvg/src/v1.4-d4d82a8f15
-- Applying patch E:/Libs/vcpkg/ports/openmvg
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch fixcmake.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No
    Working Directory: E:/Libs/vcpkg/buildtrees/openmvg/x64-windows-dbg
    See logs for more information:
      E:\Libs\vcpkg\buildtrees\openmvg\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/openmvg/portfile.cmake:77 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package openmvg:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openmvg:x64-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

Here is the error in the log file:
    13>E:\Libs\vcpkg\buildtrees\openmvg\src\v1.4-d4d82a8f15\src\openMVG\matching\regions_matcher.cpp : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj [E:\Libs\vcpkg\buildtrees\openmvg\x64-windows-dbg\openMVG\matching\openMVG_matching.vcxproj]
    13>cl : Command line error D8040: error creating or communicating with child process [E:\Libs\vcpkg\buildtrees\openmvg\x64-windows-dbg\openMVG\matching\openMVG_matching.vcxproj]
    13>Done Building Project "E:\Libs\vcpkg\buildtrees\openmvg\x64-windows-dbg\openMVG\matching\openMVG_matching.vcxproj" (default targets) -- FAILED.

**Comment by LarryIII** [comment]
@rkcarroll Thanks for your feedback. I installed openmvg:x64-windows successfully with VS 2017 15.9.11, Please try to use latest vcpkg version and reopen a new issue if it is still a problem for you!
