### ISSUE TITLE
[nana] ports/nana/CMakeLists.txt is outdated

### ISSUE THREAD

**Issue by jk-jeon** [microsoft/vcpkg#5671]
Line 2:
`project(nana VERSION 1.5.5 LANGUAGES CXX)`

The current version is 1.6.2.

Line 29:

`target_compile_features(nana PUBLIC cxx_std_14)`

This causes #4143. Changing this line to

`target_compile_features(nana PUBLIC cxx_std_17)`

solves the issue, but is it the "right" way to solve it? As discussed in #4143, enforcing a certain C++ version in this certain place does not seem to be a good idea.

**Comment by MikeGitb** [comment]
Doesn't nana have a cmake file itself?

**Comment by jk-jeon** [comment]
It has, but for whatever reason the file
````https://github.com/cnjinhao/nana/blob/master/CMakeLists.txt````
is not used for the vcpkg version. I don't know the internals of vcpkg well, but I guess that is because of the existence of the following file:
````https://github.com/Microsoft/vcpkg/blob/master/ports/nana/CMakeLists.txt````
It seems not so common that there is a CMakeLists.txt in the port directory.

**Comment by PhoebeHui** [comment]
The CMakeLists.txt from nana doesn't export cmake targets, so commit [ee3183c58](
https://github.com/microsoft/vcpkg/commit/ee3183c58aff16b954ca5d609821a7b67a0a363b#diff-67dedf2b67d075fc3bb484319de1a030) add the the CMakeLists.txt for it. I will summit a PR to fix this issue.
