### ISSUE TITLE
vcpkg hung on update

### ISSUE THREAD

**Issue by aPSopt** [Microsoft/vcpkg#5673]
Today I update and build vcpkg (before I dont update about 3 weeks).
Then I launch command "vcpkg update" as usual update. And the vcpkg loads cpu and don`t stop about 30 minutes. I break the execution because usually it finich update in about 20 seconds and then I try again. 
The vcpkg loads cpu again and now it works almost 8 hours.

**Comment by aPSopt** [comment]
What kind of information should I add?

**Comment by vicroms** [comment]
Hi @aPSopt 

Can you try running:

```
git pull
./bootstrap-vcpkg.bat (./bootstrap-vcpkg.sh on Linux)
./vcpkg update
``

**Comment by aPSopt** [comment]
Hmmmm, now it works
