### ISSUE TITLE
zlib:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by TheScarfix** [Microsoft/vcpkg#5674]
Installation of zlib fails for me with following error: 
CMake Error at scripts/cmake/vcpkg_test_cmake.cmake:56 (message):
  CMake integration test failed; unable to find_package(ZLIB MODULE REQUIRED)

**Comment by myd7349** [comment]
https://github.com/Microsoft/vcpkg/pull/5635

**Comment by vicroms** [comment]
It is a known issue with our `vcpkg_test_cmake()` function, my suggestion is to remove the call.
