### ISSUE TITLE
conditionally deactivate port features for arch that don't support them

### ISSUE THREAD

**Issue by Rastaban** [microsoft/vcpkg#5676]
It would be nice if there was a good way to conditionally disable port features for unsupported architectures.

For example it would be good to have sse2 be a on by default feature for fftw3 on x86/x64 but disabled for arm.  See #4783

**Comment by PhoebeHui** [comment]
This should be resolved by [Supports](https://github.com/microsoft/vcpkg/blob/e62d1361288e83eba786395b60361ab35ba83800/docs/maintainers/control-files.md#supports).
