### ISSUE TITLE
short path doesn't work

### ISSUE THREAD

**Issue by DrPingy** [microsoft/vcpkg#5686]
**Short path for vcpkg**

I use the short path „T:/“ for my Visual Studio 2017 projects. It is the same location as “D:/…/Visual Studio 2017/Projects”.
I install vcpkg in “T:/”. So it is in “T:/vcpkg”. It has worked fine till I have a bad idea, a very bad idea.
I installed Visual Studio 2019 RC.
Go back to VS2017 vcpkg doesn’t work.
I have 2 problems.
First vcpkg will use the toolset v14.2. I solved this with _set(VCPKG_PLATFORM_TOOLSET v141)_ in the triplets.
Second vcpkg don’t use the short path! With the full path some compiles doesn’t work.

What can I do that vcpkg use the short path?

These things are not solving the problems: uninstall vs2019, complete delete vcpkg, --vcpkg-root.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. About your second question, could you please provide the repro codes?

**Comment by DrPingy** [comment]
This post is very old. Some updates later my problems are solved.
