### ISSUE TITLE
[libssh] Update the version to 0.8

### ISSUE THREAD

**Issue by SRLut3t1um** [microsoft/vcpkg#5690]
Currently it is only possible to download LibSSH 0.7.

**Comment by illera88** [comment]
Any update on this? How can we add libssh 0.8?

**Comment by illera88** [comment]
there is a PR for this https://github.com/Microsoft/vcpkg/pull/4983

**Comment by NancyLi1013** [comment]
Please wait for PR #4983 merged.

**Comment by NancyLi1013** [comment]
Hi @SRLut3t1um thanks for posting this issue.
`Libssh `has been updated to 0.9.3.
Please try to update vcpkg and use this port.
