### ISSUE TITLE
Strawberry-perl-5.24.1.1-32bit-portable.zip download so slow?

### ISSUE THREAD

**Issue by wxl2578** [Microsoft/vcpkg#5691]

**Comment by qis** [comment]
@vicroms I've had issues with strawberry-perl for a very long time now. Let me round this up for you.

Their servers are absolutely horrible. Every second time I try to build `openssl` on Windows in a newly checked out `vcpkg` directory, it fails.

What I usually do in such a case, is use `wget` to download it in WSL into the `downloads` directory. This is what you can expect to happen:

```
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/qis/.wget-hsts'. HSTS will be disabled.
--2019-03-18 15:40:19--  http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portable.zip
Resolving strawberryperl.com (strawberryperl.com)... 64.90.49.174
Connecting to strawberryperl.com (strawberryperl.com)|64.90.49.174|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 120982168 (115M) [application/zip]
Saving to: ‘strawberry-perl-5.24.1.1-32bit-portable.zip’

strawberry-perl-5.24.1.1-32bi  21%[=========>                                        ]  24.88M  4.95MB/s    in 6.3s

2019-03-18 15:40:26 (3.93 MB/s) - Connection closed at byte 26092155. Retrying.

--2019-03-18 15:40:27--  (try: 2)  http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portable.z                                                                                 ip
Connecting to strawberryperl.com (strawberryperl.com)|64.90.49.174|:80... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 120982168 (115M), 94890013 (90M) remaining [application/zip]
Saving to: ‘strawberry-perl-5.24.1.1-32bit-portable.zip’

strawberry-perl-5.24.1.1-32bit-portable.zip        100%[+++++++++++++++++++++++======================================================================================>] 115.38M  4.36MB/s    in 20s

2019-03-18 15:40:47 (4.51 MB/s) - ‘strawberry-perl-5.24.1.1-32bit-portable.zip’ saved [120982168/120982168]
```

I've asked @ras0219-msft that Microsoft hosts this file since the company has the necessary resources, but apparently there are some organizational and/or legal issues?

Is there another option to make it less painful? Perhaps check if `perl.exe` is in `%Path%` and use that (provided the version requirements are met)?

**Comment by wxl2578** [comment]
Thanks for the reply, I downloaded it manually.

**Comment by qis** [comment]
@wxl2578 Could you please re-open it? The issue still persists.

**Comment by traversaro** [comment]
> Their servers are absolutely horrible. Every second time I try to build openssl on Windows in a newly checked out vcpkg directory, it fails. 

Related old issue: https://github.com/Microsoft/vcpkg/issues/932 .

**Comment by qis** [comment]
@traversaro Are you sure that this is an issue with your firewall? I'm 99% sure it's not and the strawberry-perl server is just bad. Observing the same problem from 3 different locations and ISPs.

**Comment by traversaro** [comment]
> @traversaro Are you sure that this is an issue with your firewall? I'm 99% sure it's not and the strawberry-perl server is just bad. Observing the same problem from 3 different locations and ISPs.

Back in time, `http://strawberryperl.com` downloads were working fine at my home, and failing at my work place. To be honest, I am not sure if it was the firewall or the ISP or something else.

**Comment by wxl2578** [comment]
> @wxl2578 Could you please re-open it? The issue still persists.
The crux of the problem is the strawberry-perl server. There are already similar issue. Unless the cpprestsdk team changes the download source, the problem will exist, and many people have such problems. From google translate .
