### ISSUE TITLE
Omitting PREFER_NINJA has no effect on Linux and macOS

### ISSUE THREAD

**Issue by letmaik** [microsoft/vcpkg#5694]
https://github.com/Microsoft/vcpkg/blob/9ca11f3a6dc7ef8838c6bc078dfb6ce4c288833e/scripts/cmake/vcpkg_configure_cmake.cmake#L84-L87

The second if statement is always successful in Linux and macOS because the triplets `x64-linux` and `x64-osx` do define `VCPKG_CMAKE_SYSTEM_NAME`. It looks a bit like this logic was meant for Windows only but here it applies to other systems as well.

The result of this is that ninja is always used on Linux and macOS, even if `PREFER_NINJA` is left out. ~~The workaround is to specify a generator explicitly.~~ EDIT: Just realized `GENERATOR` only accepts Ninja, Visual Studio, and NMake Makefiles. Hmm...

Suggestion: If Make is not supported anymore (which is fine), then `PREFER_NINJA` should be deprecated.

**Comment by PhoebeHui** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.
