### ISSUE TITLE
How to update port?

### ISSUE THREAD

**Issue by OlafvdSpek** [microsoft/vcpkg#570]
The documentation explains how to port a new library but not how to update an existing port. How do you go about doing this?

I'd like to update rapidjson to 1.1.

**Comment by codicodi** [comment]
If there weren't any changes affecting build/installation, someting like this should work: https://github.com/Microsoft/vcpkg/pull/468/files

**Comment by adam4813** [comment]
Updating isn't an in-depth task it usually is just changing the filename, download link, and SHA512 checksum in the portfile.cmake file and the version in the CONTROL file unless as @codicodi said it changed the build or installation scripts.

**Comment by OlafvdSpek** [comment]
I know, but it seems creating that part from scratch is currently simpler then updating it.

**Comment by bagong** [comment]
Yea, `vcpkg upgrade` is still missing ;)

**Comment by NancyLi1013** [comment]
Hi @OlafvdSpek, thanks for posting this issue. It has been mentioned in https://github.com/microsoft/vcpkg/blob/adfbc44bcceb1bdc59b504c0f2e4e134c74821b7/docs/about/faq.md.

**How do I update libraries?
The vcpkg update command lists all packages which are out-of-sync with your current portfiles. To update a package, follow the instructions in the command.**
