### ISSUE TITLE
LINK : fatal error LNK1104: cannot open file 'msvcprt.lib'

### ISSUE THREAD

**Issue by harishsk** [Microsoft/vcpkg#5704]
My Environment:

- Windows 10 Version 1809 OS Build 17763.379
- Visual Studio Community 2017 Version 15.9.9
- Installed VS components
{
	"version": "1.0",
	"components": [
		"Microsoft.VisualStudio.Workload.ManagedDesktop",
		"Microsoft.VisualStudio.Workload.NativeDesktop",
		"Microsoft.VisualStudio.Workload.Universal",
		"Microsoft.VisualStudio.Workload.Python",
		"microsoft.net.componentgroup.targetingpacks.common",
		"microsoft.visualstudio.component.entityframework",
		"microsoft.visualstudio.component.debugger.justintime",
		"microsoft.net.component.4.7.1.sdk",
		"microsoft.visualstudio.component.vc.diagnostictools",
		"microsoft.visualstudio.component.vc.cmake.project",
		"microsoft.visualstudio.component.vc.atl",
		"microsoft.visualstudio.component.vc.testadapterforboosttest",
		"microsoft.visualstudio.component.vc.testadapterforgoogletest",
		"microsoft.component.vc.runtime.ucrtsdk",
		"microsoft.visualstudio.component.windows81sdk",
		"microsoft.visualstudio.component.windows10sdk.17134",
		"microsoft.visualstudio.component.windows10sdk.16299.desktop",
		"microsoft.visualstudio.component.vc.140",
		"microsoft.component.cookiecuttertools",
		"microsoft.component.pythontools.web",
		"component.cpython3.x64",
		"microsoft.visualstudio.component.typescript.2.8",
		"microsoft.visualstudio.component.typescript.3.0",
		"component.microsoft.windows.driverkit",
		"component.microsoft.windows.cppwinrt"
	]
}

Repro Steps:
- Clone vcpkg repo
- bootstrap-vcpkg.bat

I get the errors listed below. Can you please let me know what I am missing?

  vcpkglib.vcxproj -> C:\Users\harishsk\projects\vcpkg\toolsrc\msbuild.x86.release\vcpkglib.lib
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild .targets(402,5): warning MSB8038: Spectre mitigation is enabled but Spectre mitigated libraries are not f ound.  Verify that the Visual Studio Workload includes the Spectre mitigated libraries.  See https://aka. ms/Ofhn4c for more information. [C:\Users\harishsk\projects\vcpkg\toolsrc\vcpkg\vcpkg.vcxproj]
  vcpkg.cpp
**LINK : fatal error LNK1104: cannot open file 'msvcprt.lib' [C:\Users\harishsk\projects\vcpkg\toolsrc\vcpk g\vcpkg.vcxproj]**
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild .targets(402,5): warning MSB8038: Spectre mitigation is enabled but Spectre mitigated libraries are not f ound.  Verify that the Visual Studio Workload includes the Spectre mitigated libraries.  See https://aka. ms/Ofhn4c for more information. [C:\Users\harishsk\projects\vcpkg\toolsrc\vcpkgmetricsuploader\vcpkgmetri csuploader.vcxproj]
  vcpkgmetricsuploader.cpp
**LINK : fatal error LNK1104: cannot open file 'msvcprt.lib' [C:\Users\harishsk\projects\vcpkg\toolsrc\vcpk gmetricsuploader\vcpkgmetricsuploader.vcxproj]**
C:\Users\harishsk\projects\vcpkg\scripts\bootstrap.ps1 : Building vcpkg.exe failed. Please ensure you
have installed Visual Studio with the Desktop C++ workload and the Windows SDK for Desktop C++.
At line:1 char:4
+ & {& 'C:\Users\harishsk\projects\vcpkg\scripts\bootstrap.ps1' }
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,bootstrap.ps1

**Comment by Voskrese** [comment]
Spectre mitigation is enabled but Spectre mitigated libraries are not f ound. Verify that the Visual Studio Workload includes the Spectre mitigated libraries.

**Comment by harishsk** [comment]
Yes, that was the issue. Thanks.
