### ISSUE TITLE
Failure to build openssl-windows

### ISSUE THREAD

**Issue by richardeakin** [Microsoft/vcpkg#5713]
Hi there,

I'm trying to use vcpkg to install cpprestsdk, and it's failing on OpenSLL (I really only need x64 target but it is failing on both x86 and x64 with the same error message).

Running latest public Windows 10, latest vcpkg master branch, and followed the instructions in the main readme. Here's the relevant log:

```
Building package openssl-windows[core]:x86-windows...
-- Using cached D:/code/cpp/msw/vcpkg/downloads/openssl-1.0.2q.tar.gz
-- Applying patch D:/code/cpp/msw/vcpkg/ports/openssl-windows/ConfigureIncludeQuotesFix.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/code/cpp/msw/vcpkg/ports/openssl-windows/STRINGIFYPatch.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/code/cpp/msw/vcpkg/ports/openssl-windows/EnableWinARM32.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/code/cpp/msw/vcpkg/ports/openssl-windows/EmbedSymbolsInStaticLibsZ7.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Configure x86-windows-rel
-- Configure x86-windows-rel done
-- Build x86-windows-rel
-- Build x86-windows-rel done
-- Configure x86-windows-dbg
-- Configure x86-windows-dbg done
-- Build x86-windows-dbg
-- Build x86-windows-dbg done
-- Installing: D:/code/cpp/msw/vcpkg/packages/openssl-windows_x86-windows/share/openssl-windows/copyright
-- Performing CMake integration test
CMake Error at scripts/cmake/vcpkg_test_cmake.cmake:71 (message):
  CMake integration test failed; unable to find_package(OpenSSL MODULE
  REQUIRED)
Call Stack (most recent call first):
  ports/openssl-windows/portfile.cmake:171 (vcpkg_test_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package openssl-windows:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-windows:x86-windows
  Vcpkg version: 2018.11.23-nohash
```

**Comment by Voskrese** [comment]
> -- Performing CMake integration test
> CMake Error at scripts/cmake/vcpkg_test_cmake.cmake:71 (message):
>   CMake integration test failed; unable to find_package(OpenSSL MODULE
>   REQUIRED)
> Call Stack (most recent call first):
>   ports/openssl-windows/portfile.cmake:171 (vcpkg_test_cmake)

if you need a package and do not understand, disable the proving test

edit port `ports/openssl-windows/portfile.cmake`

comment out the line

## vcpkg_test_cmake

**Comment by jwillemsen** [comment]
We see the same errors since a few days using Visual Studio 2015, see https://github.com/DOCGroup/ACE_TAO/blob/master/azure-pipelines.yml for our yaml file

**Comment by richardeakin** [comment]
Okay, works with that line commented out, thanks! Not sure I understand why the test fails, maybe this is something the openssl port maintainer would look at?

**Comment by Voskrese** [comment]
bug port

**Comment by richardeakin** [comment]
@Voskrese bug report to where? If this is the wrong place.

**Comment by andrewfb** [comment]
Just confirming a fresh install of vcpkg as of 15 minutes ago fails in the same way for me attempting `vcpkg install cpprestsdk:x64-windows`, and that the above commenting-out fix also solves it on my machine.

**Comment by jwillemsen** [comment]
The error given by cmake is:
```
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
``

**Comment by jwillemsen** [comment]
Proposed #5747 as fix, vcpkg_test_cmake uses ninja by default, make sure it is installed and on our path

**Comment by Priyatham10** [comment]
> Okay, works with that line @Voskrese mentioned commented out, thanks! Not sure I understand why the test fails, maybe this is something the openssl port maintainer would look at?

No it doesn't work for me

**Comment by the-j0k3r** [comment]
Assuming the failures are on a git clone that you have no code to lose, try running.

`git clean -xfd` then retrying to compile as normal. 
Its my goto command to make sure nothing interferes in compile.

**Comment by jwillemsen** [comment]
Should be fixed

**Comment by LarryIII** [comment]
vcpkg_test_cmake() has been disabled by c2ad1ba. With that change openssl-windows will build so I am closing this issue for now. Please re-open if this is still an issue for you. Thank you!
