### ISSUE TITLE
Does vcpkg integration support VS2019,?

### ISSUE THREAD

**Issue by zhulika** [microsoft/vcpkg#5714]
I find that installing packages with Visual Studio 2019 fails, if `vcpkg integrate` mode is active.

Disabling the integration "fixes" the problem ("cannot find vcruntime.h" when building libsodium, for example).

**Comment by jjpepper** [comment]
Take a look at [this](https://vcpkg.readthedocs.io/en/latest/users/triplets/#VCPKG_VISUAL_STUDIO_PATH) for setting which visual studio install for Vcpkg to use.  This fixed some cannot find vcruntime.h problems for me while trying to install python3

**Comment by PhoebeHui** [comment]
It supports VS2019 nicely now, please get latest source and try again.
