### ISSUE TITLE
libsodium dynamic CRT post-build failure

### ISSUE THREAD

**Issue by zhulika** [microsoft/vcpkg#5715]
I've seen several comments about people wanting dynamic CRT with static libs and I need something similar with libsodium.

When I try to create a triplet, I get lots of warnings about invalid linkage:

```
-- Performing post-build validation
Expected Debug,Dynamic crt linkage, but the following libs had invalid crt linkage:

    D:/work/github/vcpkg/packages/libsodium_x64-windows-static-md/debug/lib/libsodium.lib: Debug,Static

To inspect the lib files, use:
    dumpbin.exe /directives mylibfile.lib
Expected Release,Dynamic crt linkage, but the following libs had invalid crt linkage:

    D:/work/github/vcpkg/packages/libsodium_x64-windows-static-md/lib/libsodium.lib: Release,Static

To inspect the lib files, use:
    dumpbin.exe /directives mylibfile.lib
Found 2 error(s). Please correct the portfile:
    D:\work\github\vcpkg\ports\libsodium\portfile.cmake
-- Performing post-build validation done
Error: Building package libsodium:x64-windows-static-md failed with: POST_BUILD_CHECKS_FAILED
```

Incidentally, can someone tell me what is the point of having a DLL version of libsodium? Surely, having your encryption logic in a shared DLL with a well-published API is a security risk?

**Comment by Neumann-A** [comment]
That is not something suported by libsodium by default. If you want to have it you have to go into the buildtree of libsodium and change the configurations (Release/Debug) within the libsodium.sln file yourself. After that you should be able to run your costume triplet without that error and vcpkg will be able to install it.

**Comment by zhulika** [comment]
Thank you very much for your suggestion. I did try that but it doesn't seem to work for me.

If you have the time to read this, here is what I did:

After creating the triplet definition, I noticed that there are several possible candidates for the solution file to edit:

`...\vcpkg\buildtrees\libsodium\src\1.0.17-c3f6e35d7b\libsodium.sln`
`...\vcpkg\buildtrees\libsodium\src\1.0.17-c3f6e35d7b\builds\msvc\vs2010\libsodium.sln`
`...\vcpkg\buildtrees\libsodium\src\1.0.17-c3f6e35d7b\builds\msvc\vs2012\libsodium.sln`
`...\vcpkg\buildtrees\libsodium\src\1.0.17-c3f6e35d7b\builds\msvc\vs2013\libsodium.sln`
`...\vcpkg\buildtrees\libsodium\src\1.0.17-c3f6e35d7b\builds\msvc\vs2015\libsodium.sln`
`...\vcpkg\buildtrees\libsodium\src\1.0.17-c3f6e35d7b\builds\msvc\vs2017\libsodium.sln`

I edited the projects that were referenced by the first one in the list, as this appears to be what the build uses:

`D:\work\github\vcpkg>vcpkg install libsodium:x64-windows-static-md`
`[...]`
`-- Using source at D:/work/github/vcpkg/buildtrees/libsodium/src/1.0.17-c3f6e35d7b`
`-- Building D:/work/github/vcpkg/buildtrees/libsodium/src/1.0.17-c3f6e35d7b/libsodium.vcxproj for Release`
`-- Building D:/work/github/vcpkg/buildtrees/libsodium/src/1.0.17-c3f6e35d7b/libsodium.vcxproj for Debug`
`[...]`

I deleted the contents of what I believe to be the intermediate folder: "D:\work\github\vcpkg\buildtrees\libsodium\src\1.0.17-c3f6e35d7b\Build" and then ran the "vcpkg install: libsodium:x64-windows-static-md" to build with my triplet, using the dynamic CRT versions of the vcxproj files.

The result of the build was as I mentioned in my original post.

Is there anything else that I can try out? This is the first time that I have tried to customise vcpkg.

**Comment by zhulika** [comment]
> 
> 
> > Surely, having your encryption logic in a shared DLL with a well-published API is a security risk?
> 
> No?

I'm fairly new to this, so there could be something that I'm missing, but I am wondering how do you ensure that the shared library cannot be replaced by a trojan?

**Comment by OlafvdSpek** [comment]
If the trojan can do that it's already game over...

**Comment by zhulika** [comment]
Ah, maybe we're considering the situation from different positions. I was thinking that the user will be able to steal the keys that are hard-coded into my program by replacing the libsodium and looking at the arguments passed in. I'm not talking about some third party trying to steal the user's keys which is what I think you talking about?

Probably not a common case, but it just "feels" a bit risky to me.

**Comment by OlafvdSpek** [comment]
The user would find the keys anyway by analyzing your program itself.

**Comment by OlafvdSpek** [comment]
> That is not something suported by libsodium by default. If you want to have it you have to go into the buildtree of libsodium and change the configurations (Release/Debug) within the libsodium.sln file yourself.

Wouldn't it be simpler for libsodium to provide cmake files?

**Comment by Neumann-A** [comment]
> Wouldn't it be simpler for libsodium to provide cmake files?

yeah, but that has nothing to do with vcpkg and must be done by the libsodium maintainers.

**Comment by zhulika** [comment]
> Wouldn't it be simpler for libsodium to provide cmake files?

My incidental question was not aimed specifically at libsodium, but was rather about why anyone would want to export their security logic to a shared library. Your answer showed me that we are thinking about different cases, so I can now see that there may be a case where it is harmless to do this, thank you.

In my case, I'll make sure that I use a static library, because I don't want anyone to be able to splice their code into the encryption/decryption entry points.

**Comment by JackBoosY** [comment]
@zhulika When you use unofficial triplets, you have to solve the build issues yourself.

> but was rather about why anyone would want to export their security logic to a shared library
What does it mean?

Data security is not guaranteed by the CRT linkage, and security-related code is generated as dynamic libraries. Unless your computer is under control, I don't think any Trojan has the ability to replace these libraries.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by dannypike** [comment]
@JackBoos  My question wasn't actually answered, but I am aware that you are coming from a completely different position and my case is something that libsodium doesn't want to support. So, that's fine. I will just create my own build and move on.

Thanks for your time :)
