### ISSUE TITLE
[glib] *.pc files are not being installed

### ISSUE THREAD

**Issue by realnc** [microsoft/vcpkg#5718]
I just started using vcpkg on macOS 10.13. Well, tried to. I did:

    ./vcpkg install glib

This installed glib and all its deps into `installed/x64-osx/lib`. But the `pkgconfig` directory is missing and the `*.pc` files of glib and its deps are not being installed. As a result, I can't build any of my software against the installed dependencies.

I have not found anything in the vcpkg documentation, and web searches turn up nothing.

**Comment by smcv** [comment]
Using GLib's Meson build system (#10389) would probably fix this.

**Comment by realnc** [comment]
I haven't used vcpkg for a long time (since the bug report, actually, due to the bug.) So I have no interest in this bug. Feel free to close this.

**Comment by Redcxx** [comment]
+1

**Comment by JackBoosY** [comment]
Close this issue via #11884 merged.
