### ISSUE TITLE
Can't install any packages. vcpkg.exe has crashed. Windows 10 x64

### ISSUE THREAD

**Issue by davima** [Microsoft/vcpkg#5720]
Hi guys,
great work you've done! But I can't seem to install any packages. I have cloned the repo, then ran the  .\bootstrap-vcpkg.bat and then when trying to install any package I get a message saying that vcpkg has crashed:
The following packages will be built and installed:
    zlib[core]:x64-windows
Starting package 1/1: zlib:x64-windows
Building package zlib[core]:x64-windows...
vcpkg.exe has crashed.
Please send an email to:
    vcpkg@microsoft.com
containing a brief summary of what you were trying to do and the following data blob:

Version=2018.11.23-nohash
EXCEPTION='exists: The filename, directory name, or volume label syntax is incorrect.
: ""C:\Program Files\PostgreSQL\9.5\bin"/cmake.cmd"'
CMD=
C:\Dev\vscode\vcpkg\vcpkg.exe|
install|
zlib:x64-windows|

Thanks in advance.

**Comment by Voskrese** [comment]
incorrect PATH  "C:\Program Files\PostgreSQL\9.5\bin" `cmake`

`open cmd.exe`
`set | findstr cmake`

**Comment by stekyne** [comment]
I'm getting this as well.

 EXCEPTION='exists: The filename, directory name, or volume label syntax is incorrect.
[00:03:42] : "C:\projects\csound\msvc\deps\binC:\projects\csound\msvc\deps\/cmake.cmd"'

**Comment by Voskrese** [comment]
~~cmake.cmd~~
cmake.exe

default
C:\Program Files\cmake\bin
or
C:\Program Files (x86)\cmake\bin

**Comment by stekyne** [comment]
Well, it's not like I can affect where this path is being directed. Plus it's malformed. It contains two paths concatenated incorrectly. This was found on our CI so it must be a bug I presume?

**Comment by Voskrese** [comment]
move the paths in search of the environment first of all CMAKE.EXE

1. C:\Program Files (x86)\cmake\bin
2. C:\projects\csound\msvc\deps

example
PATH=C:\Program Files (x86)\cmake\bin;C:\projects\csound\msvc\deps;...

**Comment by schmidtyd** [comment]
The problem appears to be in files.cpp:find_from_PATH() function.

<code>
auto paths = Strings::split(System::get_environment_variable("PATH").value_or_exit(VCPKG_LINE_INFO), ";");
</code>

When I run vcpkg via Visual studio this command fills the path variable correctly. However, when I run vcpkg normally from the command line, that code inserts the current working directory into the PATH list. This wouldn't be a problem except that quotations are put around the current working directory path. This leads to a poorly formed path and the exe crashing when the <code>this->exists(p)</code> command is run. 

My list of paths when run from visual studio:
PATH: C:\Users\daschmi\cmder\bin
PATH: C:\Program Files\CMake\bin
etc....

My list of paths when run from the command line:
PATH: "C:\Users\daschmi\source\vcpkg"          **<-- problem child**
PATH: C:\Users\daschmi\cmder\bin
PATH: C:\Program Files\CMake\bin
etc...

**Comment by davima** [comment]
I was able to run it by running it in cygwin instead of PowerShell

**Comment by wangli28** [comment]
@davima, thank you for posting the issue, does the issue still occur?

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
