### ISSUE TITLE
Mandating Minimum Compiler Version

### ISSUE THREAD

**Issue by cwfitzgerald** [microsoft/vcpkg#5721]
When looking at packaging libraries targeting very modern subsets of C++, they often only support more modern compilers than vcpkg supports. For example, if you need `<optional>` you need gcc-8 or better. However, vcpkg works with gcc-5.4 due to supporting Ubuntu 16.04. What is the recommended way of dealing with this? _Is_ there a way of dealing with this?

**Comment by BillyONeal** [comment]
I believe the correct way to handle this will be to add that compiler to a triplet but I don't see an amazing way documented to override the compiler right now. Doing it nicely might require adding a toolchain or modifying the existing Linux toolchain to have that knob: https://github.com/microsoft/vcpkg/tree/master/scripts/toolchains

(I observe that MinGW is in a similar state on Windows and it has its own toolchain)

**Comment by cenit** [comment]
Isn’t the chainload toolchain mechanism in vcpkg here for this reason? I remember doing something like this to force gcc version...

**Comment by BillyONeal** [comment]
@cenit That helps if you're using `vcpkg.cmake` as your toolchain and want to use a different compiler but not if you want to change the compiler used to build the ports themselves.

**Comment by cenit** [comment]
You're right. I did it many years ago and was not remembering even the project anymore...

**Comment by Neumann-A** [comment]
@BillyONeal: Custom triplet with VCPKG_CHAINLOAD_TOOLCHAIN set..... That is how I built everything with `clang-cl`

**Comment by BillyONeal** [comment]
Ah yes, thanks @Neumann-A ! @cwfitzgerald can you confirm that's an acceptable workaround?

**Comment by cenit** [comment]
So it was real, I did it too...

**Comment by BillyONeal** [comment]
Hmmm OK. Going to close this for now; if folks have similar issues please open a new issue.
