### ISSUE TITLE
[wxWidgets]Missing wxWidgets-config.cmake file in share directory

### ISSUE THREAD

**Issue by JackBoosY** [microsoft/vcpkg#5725]
Related to #1843.
Found **config.cmake** in `src\build\cmake` but could not use it.

**Comment by slodki** [comment]
Current `FindwxWidgets.cmake` module logic cannot be easily fixed for `vcpkg` builds of wxWidgets - it uses official wxWidgets team's directory structure to identify build type. (#4756)

Exporting cmake config file is the only solution to use wxWidgets from vcpkg port IMHO.

**Comment by zelid** [comment]
I'm having the same issue, @slodki can you please provide an example of exporting cmake config to make wxWidgets be found from vcpkg?

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/4756
