### ISSUE TITLE
Cannot download MSYS2

### ISSUE THREAD

**Issue by roelandschoukens** [microsoft/vcpkg#5727]
The download url does not work, it also fails when downloading via a browser.

```
>vcpkg install icu
```
```
The following packages will be built and installed:
    icu[core]:x64-windows
Starting package 1/1: icu:x64-windows
Building package icu[core]:x64-windows...
-- Using cached C:/Users/roeland/lib/vcpkg/downloads/icu4c-61_1-src.tgz
-- Applying patch C:/Users/roeland/lib/vcpkg/ports/icu/disable-escapestr-tool.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/Users/roeland/lib/vcpkg/ports/icu/remove-MD-from-configure.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Acquiring MSYS2...
-- Downloading http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20181211.tar.xz...
-- Downloading http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20181211.tar.xz... Failed. Status: 18;"Transferred a partial file"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:172 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:76 (vcpkg_download_distfile)
  ports/icu/portfile.cmake:75 (vcpkg_acquire_msys)
  scripts/ports.cmake:71 (include)


Error: Building package icu:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x64-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.
```

**Comment by Voskrese** [comment]
no download problems
on your side of the problem

`cd C:/Users/roeland/lib/vcpkg/downloads`
`wget http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20181211.tar.xz`

**Comment by roelandschoukens** [comment]
The download consistently gets interrupted after a few minutes. You cannot reproduce this with `wget` because `wget` will automatically resume the download if this happens.

**Comment by PhoebeHui** [comment]
@roelandschoukens, thanks for posting this issue!

We can't reproduce this issue locally, here is a workaround may work for you:
1. Download the source code with a web browser from: http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20181211.tar.xz
2. Save it inside <path_to_vcpkg>/downloads/.
3. Run ./vcpkg install icu:x64-windows again

**Comment by JackBoosY** [comment]
@roelandschoukens You can also use this [link ](http://mirrors.ustc.edu.cn/msys2/distrib/x86_64/msys2-base-x86_64-20181211.tar.xz)to download msys2.

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.

**Comment by MaverickTse** [comment]
This is still a problem. repo.msys2.org is inaccesible from Hong Kong, Japan, Germany, San Francisco, etc...
Is it possible to use sourceforge as the default download source?

**Comment by JackBoosY** [comment]
@MaverickTse That's msys official site... Just wait for fix would be okay.

**Comment by MaverickTse** [comment]
The situation has been over a year but MSYS2 side seems ignoring the problem. See:
https://github.com/msys2/MSYS2-packages/issues/1098

While i can change vcpkg_acquire_msys.cmake to use China's mirror for my own use, others probably would run into the same issue.... and the version of msys2 is old

**Comment by akizminet** [comment]
I have the same problem. [repo.msys2.org](repo.msys2.org) has died.

**Comment by JackBoosY** [comment]
Since this issue  lasts too long, please track #10322.

Thanks.
