### ISSUE TITLE
[New port request] Gtsam

### ISSUE THREAD

**Issue by Tomas-Lee** [microsoft/vcpkg#5728]
Gtsam is a common factor graph optimization library used for lots of simultaneous localization and mapping Programs. Please help to support it.
The related URL is : https://bitbucket.org/gtborg/gtsam
Git URL is https://bitbucket.org/gtborg/gtsam.git

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!

**Comment by lgp8z** [comment]
why not merge to master?

**Comment by NancyLi1013** [comment]
@lgp8z 
Thanks for posting this request again. Since there are still some problems in static build. 
You can open a new PR or reopen my PR to continue the work if you still require for this port.
