### ISSUE TITLE
roadrunner library not available in visual studio after install

### ISSUE THREAD

**Issue by CiaranWelsh** [microsoft/vcpkg#5738]
I have installed somebody elses library using vcpkg. Since the binaries are available I've chosen to take the approach discussed in the FAQ where the zipped binaries are downloaded and the portfile.cmake is used to copy the library files into the correct places. The script I've ended up with is the following, which seems to install correctly when I use `vcpkg install roadrunner:x86-windows-rel`. The problem is that even after install and using `vcpkg integrate install` the library is unavailable in visual studio. I think the problem is most likely my inexperience rather than a bug but some help with the would be greatly appreciated. Here are the files I'm using: 

Triplet file
-----------
```
set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_BUILD_TYPE release)
```

CONTROL
-----------
```
Source: roadrunner
Version: 1.5.3
Description: library for running ODE simulations 
```

portfile.cmake
---------------
```
include(vcpkg_common_functions)

vcpkg_download_distfile(ARCHIVE
    URLS "https://sourceforge.net/projects/libroadrunner/files/libroadrunner-1.5.0/roadrunner-1.5.0-vs12-llvm-3.5-win32.zip"
    FILENAME "rr1.5.0.zip"
    SHA512 b5e5d85af68c06f76437b9c070e4f287dfa88c46a92767b0d81dc463d895d93d816f503bc76ccfdb4a37479cfa9b9b17baa6003c793bc7109860b5edc11037d2
)

vcpkg_extract_source_archive_ex(
    OUT_SOURCE_PATH SOURCE_PATH
    ARCHIVE ${ARCHIVE} 
)


file(MAKE_DIRECTORY
	${CURRENT_PACKAGES_DIR}/include
	${CURRENT_PACKAGES_DIR}/lib
	${CURRENT_PACKAGES_DIR}/share
	)

file(COPY
	${SOURCE_PATH}/lib
	DESTINATION ${CURRENT_PACKAGES_DIR}
	)
file(COPY
	${SOURCE_PATH}/share
	DESTINATION ${CURRENT_PACKAGES_DIR}
	)
file(COPY
	${SOURCE_PATH}/include
	DESTINATION ${CURRENT_PACKAGES_DIR}
	)

file(COPY ${CURRENT_BUILDTREES_DIR}/src/rr1-ab456cf2e4/LICENSE.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/roadrunner)
file(RENAME ${CURRENT_PACKAGES_DIR}/share/roadrunner/LICENSE.txt ${CURRENT_PACKAGES_DIR}/share/roadrunner/copyright)
```

Thanks

**Comment by Cheney-W** [comment]
@CiaranWelsh You should add this sentence: 
"\<VcpkgTriplet Condition="'$(Platform)'=='Win32'"\>x86-windows-rel\</VcpkgTriplet\>" 
after "\<PropertyGroup Label="Globals"\>" of the project.vcxproj file. 
You can refer to Eric's [blog](https://devblogs.microsoft.com/cppblog/vcpkg-updates-static-linking-is-now-available/).

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you.
