### ISSUE TITLE
can use vapkg install lib compile with vc-ltl

### ISSUE THREAD

**Issue by xspeed1989** [microsoft/vcpkg#5742]
VC-LTL is an open source CRT library based on the MS VCRT that reduce program binary size and say goodbye to Microsoft runtime DLLs, such as msvcr120.dll, api-ms-win-crt-time-l1-1-0.dll and other dependencies.

https://github.com/Chuyu-Team/VC-LTL

**Comment by wangli28** [comment]
same with https://github.com/Microsoft/vcpkg/issues/4805

**Comment by NancyLi1013** [comment]
Duplicated of #4805, Please pay attention to the progress of issue #4805.
