### ISSUE TITLE
DLL lines in output

### ISSUE THREAD

**Issue by OlafvdSpek** [Microsoft/vcpkg#575]
When building a project, the output contains lines like `1>  C:\VC\xcc\Mixer\Debug\libbz2.dll`

When stepping through errors with F4 these lines are somehow picked up, not sure why.
I set MSBuild output verbosity to minimal, I'm not sure what benefit those lines add to the output.

**Comment by ras0219-msft** [comment]
Those are how `applocal.ps1` communicates with MSBuild for some dependency tracking. However, you're certainly right that they should really only be displayed in more detailed MSBuild log modes.

**Comment by ras0219-msft** [comment]
Ok, this should be fixed in 44810f2. Thanks for the report!

**Comment by OlafvdSpek** [comment]
> StandardOutputImportance="Normal"

Does this fix the F4 issue?

Unrelated to that, perhaps Importance could be even lower than Normal?
