### ISSUE TITLE
cannot install ignite

### ISSUE THREAD

**Issue by tujiaw** [microsoft/vcpkg#5756]

**Comment by vicroms** [comment]
@tujiaw 
Can you provide more information for this issue? (e.g.: steps to reproduce) 

We don't currently have a port for an `ignite` package. Is `ignite` a library?
Please consider making a new PR to add this library to vcpkg.

**Comment by tujiaw** [comment]
https://github.com/apache/ignite
Apache Ignite is a memory-centric distributed database, caching, and processing platform for transactional, analytical, and streaming workloads delivering in-memory speeds at petabyte scale.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
