### ISSUE TITLE
VCPKG unable to find_package(OpenSSL MODULE REQUIRED) when build Folly

### ISSUE THREAD

**Issue by QuellaZhang** [Microsoft/vcpkg#5759]
Hi all,

We use VCPKG to build Folly project to detect compiler regressions of MSVC, recently it failed due to CMake error "CMake integration test failed; unable to find_package(OpenSSL MODULE REQUIRED)". And we found it failed from VCPKG version bdc5d538a59e4983ab184d65963bac2678d35947, it was built successfully in the previous version. This issue also appeared when we built Git project(Git is also built by VCPKG), can you help to look at this? Thank you in advance!

**Repro steps:**

1. git clone https://github.com/Microsoft/vcpkg  D:\VCPKG\src
2. cd D:\VCPKG\src
3. devenv /upgrade .\toolsrc\vcpkg.sln
4. set _CL_=/D_SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING
5. msbuild /p:Configuration=Release /p:Platform=x86 /p:WindowsTargetPlatformVersion=10.0.17134.0 toolsrc\vcpkg.sln /t:Rebuild
6. set _CL_=
7. set path=%cd%\toolsrc\msbuild.x86.release;%path%
8. vcpkg install folly:x64-windows --head

**Failures:**
-- Build x64-windows-dbg done
-- Installing: D:/Folly/vcpkg/src/packages/openssl-windows_x64-windows/share/openssl-windows/copyright
-- Performing CMake integration test
**CMake Error** at scripts/cmake/vcpkg_test_cmake.cmake:71 (message):
  CMake integration test failed; unable to find_package(OpenSSL MODULE REQUIRED)
Call Stack (most recent call first):
  ports/openssl-windows/portfile.cmake:171 (vcpkg_test_cmake)
  scripts/ports.cmake:71 (include)

**Error**: Building package openssl-windows:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-windows:x64-windows
  Vcpkg version: 2018.11.23

Additionally, attach any relevant sections from the log files above.

**Comment by jwillemsen** [comment]
See https://github.com/Microsoft/vcpkg/pull/5747 for a change which very likely also fix this

**Comment by jwillemsen** [comment]
With #5747 applied I get the attached compile errors with folly

[install-x64-windows-static-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2991225/install-x64-windows-static-dbg-out.log)

**Comment by QuellaZhang** [comment]
This issue is no longer reproduced in the latest VCPKG version, so closed it now.
