### ISSUE TITLE
Use of std::filesystem (PR #5651) breaks vcpkg install on Windows 10 x64 with VS2017

### ISSUE THREAD

**Issue by teeekay** [Microsoft/vcpkg#5764]
@grdowns
I am running Win10 pro v1809 x64 with VS2017.
I was unable to compile vcpkg, with multiple errors about files.h(11)

It seems PR #5651 breaks ability to compile vcpkg for some installations of Visual Studio.  When I changed this PR back to use

 `namespace stdfs = std::experimental::filesystem;` 

vcpkg compiled fine.

When I used my other machine with Win 10 Pro v1809 with VS2015, vcpkg compiled fine. (Of course that would be _MSC_VER = 1900 which would not pass the check for _MSC_VER > 1900, and so will not use std::filesystem either.)

Is there a way to use `std::filesystem` in VS2017?  There is a note here suggesting this is not the standard for visual studio yet.  https://docs.microsoft.com/en-us/cpp/standard-library/filesystem?view=vs-2017

**Comment by grdowns** [comment]
Hey @teeekay, thanks for raising the issue! I've reverted the PR to fix the problem until we can investigate further the bugs that #5651 attempts to mitigate. As for using `std::filesystem` in VS2017, this will require additional discussion within the team, with the possibility that we may continue to use `std::experimental::filesystem`. I'll update this issue if/when we take action on this. Thanks again!
