### ISSUE TITLE
Is it safe to delete folders under buildtrees?

### ISSUE THREAD

**Issue by madkoala** [Microsoft/vcpkg#577]
Is it safe to delete folders under buildtrees after successful build?

**Comment by sdcb** [comment]
I think it's totally safe, I often delete it to free disk room.

**Comment by madkoala** [comment]
@sdcb Thanks!

**Comment by ras0219-msft** [comment]
Yep, totally fine.

Note that the source code is contained here, so deleting it will remove your ability to source-level-debug into libraries (the PDBs should still be available for non-source debugging though).
