### ISSUE TITLE
grpc package installation fails

### ISSUE THREAD

**Issue by Garu94** [Microsoft/vcpkg#5772]
Package: openssl-windows:x86-windows
 Vcpkg version: 2018.11.23-nohash

On Windows 10, I tried building grpc with vcpkg, but the build failed with this output:

`Performing CMake integration test
CMake Error at scripts/cmake/vcpkg_test_cmake.cmake:71 (message):
  CMake integration test failed; unable to find_package(OpenSSL MODULE
  REQUIRED)
Call Stack (most recent call first):
  ports/openssl-windows/portfile.cmake:171 (vcpkg_test_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package openssl-windows:x86-windows failed with: BUILD_FAILED`

**Comment by jwillemsen** [comment]
Will be fixed by https://github.com/Microsoft/vcpkg/pull/5747

**Comment by Garu94** [comment]
> Will be fixed by #5747

Thank you, I was able to "solve" this before by commenting out the line that performed the test, but your answer is the actual solution.

**Comment by LarryIII** [comment]
vcpkg_test_cmake() has been disabled by https://github.com/Microsoft/vcpkg/commit/c2ad1baafccc91bf7e9e60a390eb91cf4e130062.  With that change openssl-windows will build so I am closing this issue for now. Please re-open if this is still a issue for you. Thank you!
