### ISSUE TITLE
freetype:x86-windows with static runtime build error

### ISSUE THREAD

**Issue by xspeed1989** [Microsoft/vcpkg#5774]
Mismatching number of debug and release binaries. Found 1 for debug but 0 for release.
Debug binaries

    E:/vcpkg/packages/freetype_x86-windows/debug/lib/freetyped.lib

Release binaries

Release binaries were not found

The following DLLs have no exports:

    E:/vcpkg/packages/freetype_x86-windows/bin/freetype.dll

DLLs without any exports are likely a bug in the build script.
There should be no empty directories in E:/vcpkg/packages/freetype_x86-windows
The following empty directories were found:

    E:/vcpkg/packages/freetype_x86-windows/lib

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/a/dir ${CURRENT_PACKAGES_DIR}/some/other/dir)

Found 3 error(s). Please correct the portfile:
    E:\vcpkg\ports\freetype\portfile.cmake
-- Performing post-build validation done
Error: Building package freetype:x86-windows failed with: POST_BUILD_CHECKS_FAILED

**Comment by PhoebeHui** [comment]
@xspeed1989, thanks you for posting this issue!

The PR has merged, and freetype.lib placed .\packages\freetype_x86-windows\lib correctly.

**Comment by xspeed1989** [comment]
@PhoebeHui you are welcome
