### ISSUE TITLE
gdal:x64-windows-static BUILD_FAILED

### ISSUE THREAD

**Issue by JuttaAnders** [Microsoft/vcpkg#5778]
Dear Maintainer, any reason why is not possible to build GDAL statically?
_Error: GDAL's nmake buildsystem does not support building static libraries_

```
Starting package 14/14: gdal:x64-windows-static
Building package gdal[core]:x64-windows-static...
CMake Error at ports/gdal/portfile.cmake:14 (message):
  GDAL's nmake buildsystem does not support building static libraries
Call Stack (most recent call first):
  scripts/ports.cmake:71 (include)


Error: Building package gdal:x64-windows-static failed with: BUILD_FAILED
```

**Comment by Voskrese** [comment]
?
**gdal does not support building static libraries**

build dynamic )) or modify the code so that you can statically build ))

**Comment by JuttaAnders** [comment]
Hello Voskrese, do you think that GDAL 2.x does not support building static libraries or it is its port to vcpkg that is non able to do that?

**Comment by JuttaAnders** [comment]
@wangli28 I am just tring to build GDAL statically by running
`vcpkg install gdal:x64-windows-static`
but the build process ends with the message of my first post.

**Comment by Voskrese** [comment]
port author is debugged only under dynamic
If you have the time and desire, you can fix the code so that the assembly is static

all in your hands
