### ISSUE TITLE
Resolve-Path : Cannot find path

### ISSUE THREAD

**Issue by OlafvdSpek** [Microsoft/vcpkg#578]
While trying to build a library project..
The project itself doesn't use vcpkg.

```
1>  Resolve-Path : Cannot find path 'C:\VC\ctemplate-2.3\Debug\libctemplate.dll' because it does not exist.
1>  At C:\vc\vcpkg\scripts\buildsystems\msbuild\applocal.ps1:5 char:37
1>  +     $targetBinaryPath = Resolve-Path <<<<  $targetBinary
1>      + CategoryInfo          : ObjectNotFound: (C:\VC\ctemplate...ibctemplate.dll:String) [Resolve-Path], ItemNotFoundException
1>      + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ResolvePathCommand
1>
1>  Split-Path : Cannot bind argument to parameter 'Path' because it is null.
1>  At C:\vc\vcpkg\scripts\buildsystems\msbuild\applocal.ps1:6 char:34
1>  +     $targetBinaryDir = Split-Path <<<<  $targetBinaryPath -parent
1>      + CategoryInfo          : InvalidData: (:) [Split-Path], ParameterBindingValidationException
1>      + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.SplitPathCommand
1>
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(3965,9): error MSB4023: Cannot evaluate the item metadata "%(Filename)". The item metadata "%(Filename)" cannot be applied to the path "Resolve-Path : Cannot find path %27C:\VC\ctemplate-2.3\Debug\libctemplate.dll%27 because it does not exist.". The path is not of a legal form.
```

**Comment by ras0219-msft** [comment]
Ok, I changed the behavior to catch and quietly exit with 33ce94a.

For curiosity's sake: does that file (`C:\VC\ctemplate-2.3\Debug\libctemplate.dll`) not exist? We may be constructing the output path incorrectly for your project.

**Comment by OlafvdSpek** [comment]
Now that you ask the question.. no it doesn't. In fact, VS was warning about some inconsistency in the project settings. The name was changed to libctemplate-debug..

https://github.com/OlafvdSpek/ctemplate/blob/master/vsprojects/libctemplate/libctemplate.vcxproj

**Comment by ras0219-msft** [comment]
It looks like the `OutputFile` setting is a Linker-specific setting that doesn't get propagated back up to the main project's output path (which is `TargetPath`). By default, `OutputFile` is actually set to inherit from the main project's settings: `$(OutDir)$(TargetName)$(TargetExt)`

Generally [1], it looks like `TargetPath` is composed of `$(TargetDir)$(TargetName)$(TargetExt)`. So, the preferred way to change the output DLL name would be to change the "Target Name" property under Project Properties -> General. This can be done per-configuration so you can still name the Debug DLL differently. It would hopefully also clear up the VS inconsistency warnings.

Regardless, I think the change in 33ce94a is sufficient for the original problem, so I'll close this issue.

[1] https://social.msdn.microsoft.com/Forums/vstudio/en-US/d3c6e2de-1e87-49c2-b059-df074868e315/msbuild-targetpath?forum=msbuild
