### ISSUE TITLE
Missing intel parallelstl

### ISSUE THREAD

**Issue by Ben1980** [microsoft/vcpkg#5793]
Supporting intel parallelstl would be very nice. TBB support is already there
https://github.com/intel/parallelstl

**Comment by Voskrese** [comment]
https://github.com/intel/parallelstl#prerequisites
Prerequisites **C++ compiler with:**

    Support for C++11
    Support for **OpenMP* 4.0** SIMD constructs

msvc cl 2.0

https://github.com/intel/parallelstl/blob/releases/build/windows.inc

**intel** `icl`

**Comment by Ben1980** [comment]
Some background: https://github.com/01org/tbb/releases is stating that ParallelSTL is included since 2018 U3. Unfortunately this is not the case for TBB over vcpkg.

**Comment by Voskrese** [comment]
You can Install it, but the compiler won't be able to use it if we're talking about MSVC CL

**Comment by Ben1980** [comment]
Doing it manually I had no problem on GCC8/Clang7 and VS2017. 
Basically intels parallel STL was the alternative i used instead of [libc++](https://libcxx.llvm.org/cxx1z_status.html) which, unfortunately, is not supporting [P0024R2](https://wg21.link/P0024R2)

**Comment by Voskrese** [comment]
especially nothing to compile, there are common include
I'm talking about assembly use

windows
[pstl.zip](https://github.com/Microsoft/vcpkg/files/3002782/pstl.zip)

**Comment by Voskrese** [comment]
test
[parallelstl.zip](https://github.com/microsoft/vcpkg/files/3290635/parallelstl.zip)

add to CMakeLists.txt

```
install(TARGETS ${targets}
        RUNTIME DESTINATION bin
        LIBRARY DESTINATION lib
        ARCHIVE DESTINATION lib
)
```

**Comment by NancyLi1013** [comment]
Hi @Ben1980  thanks for posting this request. This port has been added to vcpkg. Please try to update vcpkg and use it.
