### ISSUE TITLE
Add mirror support for `vcpkg_download_distfile`

### ISSUE THREAD

**Issue by gwvo** [Microsoft/vcpkg#58]
port files refer directly to URLs of external websites, e.g. for Curl: `"https://curl.haxx.se/download/curl-7.48.0.tar.bz2"`. That is very brittle, in that if that site were to go down, suddenly potentially a lot of programmers can't build their code.

That may be an acceptable trade-off for individual programmers, but for a larger organization having the teams ability to work depend on many external sites may be a deal breaker, unless there was some easy way to (locally?) cache things.

**Comment by Ninetainedo** [comment]
Do you think about a local cache ? Like downloading all libraries and ship them along with vcpkg ?
What about mirror downloads ?

**Comment by ras0219-msft** [comment]
I think mirrors are definitely a great idea.

Additionally, we already first check the `downloads\` folder before making external contact so you can (ahead of time) download and store all the source code you depend on and copy them to `downloads\` before running `vcpkg install curl`.

**Comment by Ninetainedo** [comment]
I'm working on this issue right now.
If the file is successfully downloaded but I get the wrong hash, should I try a mirror or print a FATAL_ERROR ?

**Comment by Ninetainedo** [comment]
In #83 I opted for the second option: once a file successed to download, I never try to download anymore, even if the HASH doesn't match.

**Comment by votecoffee** [comment]
When I pre-download files, sometimes I have to add a prefix like 'msys-'.  If you look in the downloads temp folder, it will create an empty file while attempting to download and this will help give a clue of the filename it expects, which is not always the same as the filename it is downloading.
