### ISSUE TITLE
Is there any plans to config some packages by vcpkg itself?(Windows)

### ISSUE THREAD

**Issue by Akarinnnnn** [Microsoft/vcpkg#5803]
For example, I want pugixml use wchar_t instead of char, so far I have to change these generated project file to build wchar_t version.

**Comment by MikeGitb** [comment]
Can't you make the change in the port file?

**Comment by Voskrese** [comment]
C:\Users\**USERNAME**\AppData\Local\Microsoft\MSBuild\v4.0

edit Microsoft.Cpp.x64.user.props or Microsoft.Cpp.Win32.user.props or ...

**EXAMPLE**
add 
```
<PropertyGroup Label="UserMacros" />
<ItemDefinitionGroup>
<ClCompile>
<AdditionalOptions> /d1scalableinclude- /Zi /wd4146 /wd4996 /w44242 /w44254 /wd4100 /wd4255 /wd4548 /wd4574 /wd4668 /wd4710 /wd4711 /wd4820 /wd4646 /wd4100 /wd4121 /wd4201 /wd4214 /wd4244 /wd4018 /wd4554 /wd4090 /wd4267 /wd4101 /wd4334 /wd4723 /analyze- /Zc:wchar_t- %(AdditionalOptions)</AdditionalOptions>
```

**Comment by Akarinnnnn** [comment]
Sorry,
I mean changed pugixml's config Header(pugiconfig.hpp) ,uncomment  
```#define PUGIXML_WCHAR_MODE```

> // Uncomment this to enable wchar_t mode
#define PUGIXML_WCHAR_MODE

there also other macros to control it's behavior

**Comment by Voskrese** [comment]
it is clear, meant only the pugixml project?
I thought the question is about global global settings

Apparently then you need to close

**Comment by Akarinnnnn** [comment]
> it is clear, meant only the pugixml project?
> I thought the question is about global global settings
> 
> Apparently then you need to close

yes, only pugixml project, 
to change it's behavior, I have to change
```VCPKG\installed\x64-windows\include\pugiconfig.hpp```, to make IDE recognize functions different from default version
Rebuild
```
VCPKG\buildtrees\pugixml\x64-windows-dbg\pugixml.vcxproj
VCPKG\buildtrees\pugixml\x64-windows-rel\pugixml.vcxproj
```
After changed
```VCPKG\buildtrees\pugixml\src\v1.9-b1b3e70dc2\src\pugiconfig.hpp```
And copy build output into
```
VCPKG\installed\x64-windows\lib
VCPKG\installed\x64-windows\bin
VCPKG\installed\x64-windows\debug\bin
VCPKG\installed\x64-windows\debug\lib
```
It's a little complicated.

**Comment by Voskrese** [comment]
`vcpkg edit pugixml`

```
vcpkg_apply_patches ...
file(REMOVE_RECURSE ... 
file(COPY ...
```

https://github.com/Microsoft/vcpkg/commit/1b0fd3880fd3795b70235029c0c218cefff158db#diff-8d4f7710442a49dce42c8bf0cc3b4443

**Comment by Akarinnnnn** [comment]
like this?
```
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
	OPTIONS
        -DBUILD_DEFINES="PUGIXML_API=__declspec\(dllexport\)"
        -DBUILD_DEFINES="PUGIXML_WCHAR_MODE"
)
```

**Comment by Voskrese** [comment]
Try, wrote as an example

**Comment by Akarinnnnn** [comment]
> Can't you make the change in the port file?

thanks. Patched by wchar_t.patch
```
diff --git a/src/pugiconfig.hpp b/src/pugiconfig.hpp
index f739e06..122d7d2 100644
--- a/src/pugiconfig.hpp
+++ b/src/pugiconfig.hpp
@@ -15,7 +15,7 @@
 #define HEADER_PUGICONFIG_HPP
 
 // Uncomment this to enable wchar_t mode
-// #define PUGIXML_WCHAR_MODE
+#define PUGIXML_WCHAR_MODE
 
 // Uncomment this to enable compact mode
 // #define PUGIXML_COMPACT
```
if VCPKG can specify which patches to use in CLI, this maybe easier
