### ISSUE TITLE
How to let visual studio automatically recognize my own built OpenCV-contribute with vcpkg?

### ISSUE THREAD

**Issue by zdptrsz** [microsoft/vcpkg#5805]
For a series of complicated reasons, I finally built OpenCV-contrib with Cmake-gui.Failed more than 20 times with vcpkg.I get the lib and dll files now .I know I can modify the attribute configuration table in VS to import the opencv-contrib.
But I was deeply shocked by the automatic integration of vcpkg, it is too smart!
So how could I let VS recongnize the local .lib and .dll files automatically/smartly？
I  think nuget and vcpkg can help me,but I search by Google,and did not succeed.
I know I can copy files to vcpkg\installed\x64-windows\lib.but It’s very troublesome to upgrade and uninstall the opencv-contrib.
so can you help me?What is the principle of vcpkg automatically integrated into VS?

**Comment by Akarinnnnn** [comment]
VCPKG\installed\x64-windows\lib\XXX.lib
VCPKG\installed\x64-windows\bin\XXX.dll
VCPKG\installed\x64-windows\debug\bin\XXX.lib(Debug ver.)
VCPKG\installed\x64-windows\debug\lib\XXX.dll(Debug ver.)

VCPKG\installed\x64-windows\include\<Header Name>
先试试

**Comment by zdptrsz** [comment]
> VCPKG\installed\x64-windows\lib\XXX.lib
> VCPKG\installed\x64-windows\bin\XXX.dll
> VCPKG\installed\x64-windows\debug\bin\XXX.lib(Debug ver.)
> VCPKG\installed\x64-windows\debug\lib\XXX.dll(Debug ver.)
> 
> VCPKG\installed\x64-windows\include<Header Name>
> 先试试

thanks very much！I know the method, but when is use the：./vcpkg list  
the OpenCV-cont will show??I think it’s very troublesome to upgrade and uninstall the opencv-contrib.

**Comment by zdptrsz** [comment]
who can help me？？

**Comment by PhoebeHui** [comment]
@zdptrsz, give some information, hope it's helpful for you.
1. After install VS2017 on windows(Just an example), you can check "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Common.props". it contains 

![image](https://user-images.githubusercontent.com/20694052/58526757-aa498080-8202-11e9-9142-3e82a0892c1e.png)

2. You can find it import ..\Scripts\buildsystems\msbuild\vcpkg.targets in vcpkg.user.targets

![image](https://user-images.githubusercontent.com/20694052/58526812-e4b31d80-8202-11e9-87a0-67b58f379a4d.png)
3. You can check what's included in ..\Scripts\buildsystems\msbuild\vcpkg.targets what's included.

**Comment by PhoebeHui** [comment]
@zdptrsz, please file a new issue, if you need more information.
