### ISSUE TITLE
[tbb] CMake integration failed

### ISSUE THREAD

**Issue by heungson** [Microsoft/vcpkg#5810]
I found the posts with the similar problems but none of them solved my problem. I need any clues. 

First I got this error.

```
CMake Error at scripts/cmake/vcpkg_test_cmake.cmake:75 (message):
  CMake integration test failed; unable to find_package(TBB CONFIG REQUIRED)
Call Stack (most recent call first):
  ports/tbb/portfile.cmake:89 (vcpkg_test_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package tbb:x64-windows failed with: BUILD_FAILED
```

And then I looked into the error log file in C:\Lib\vcpkg\buildtrees\tbb

```
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
```
But I have ninja.exe and it is in PATH. It works just find when I execute it with CMD.

If I execute 
`ninja -GNinja . `
independently at test folder (x64-windows-test) it builds using gcc and ends successfully.

I have VC14 and, gcc and g++ with MinGW installed.

It'll be appreciated if you could give me some hints. Thanks!

**Comment by PhoebeHui** [comment]
@heungson, thanks for posting this issue!

I can't reproduce this issue, can you try getting vcpkg latest revision and installing again? vcpkg_test_cmake() has been disabled since it had several issues that were causing failures to install otherwise perfectly good packages.

**Comment by heungson** [comment]
@PhoebeHui , Recently I changed the whole system and now it works fine. I think the problem was that gcc and visual studio mingled with each other. Anyway it's good to hear vcpkg_test_cmake() has been disabled.
Thank you~!
