### ISSUE TITLE
PCL 1.9.1: boost error about file path memeber initialization

### ISSUE THREAD

**Issue by bbw2008927** [microsoft/vcpkg#5812]
Hi 
I use vcpkg to install pcl by vcpkg install pcl:x64-windows.
vcpkg complete to compile without error.
When I develop, I get same error as 
https://stackoverflow.com/questions/53737774/e0145-member-may-not-be-initialized-cmake-vs2017/54200907#54200907.

I follow answer of link above to add #define, but it doesn't work.
The code is very simple:
```
// pcl_demo2.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"
#include <gL/glut.h>
#include <pcl/io/io.h>
#include <pcl/io/ply_io.h>
#include <pcl/io/pcd_io.h>
#include <pcl/visualization/cloud_viewer.h>
#include <vtkAutoInit.h>         
VTK_MODULE_INIT(vtkRenderingOpenGL);
VTK_MODULE_INIT(vtkInteractionStyle);
#include <iostream>
#define BOOST_FILESYSTEM_SOURCE
int user_data;
using std::cout;
void viewerOneOff(pcl::visualization::PCLVisualizer& viewer)
{
	viewer.setBackgroundColor(1.0, 0.5, 1.0);   
}
int main()
{
	pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);
	char strfilepath[256] = "E:\\rabbit.pcd";
	if (-1 == pcl::io::loadPCDFile(strfilepath, *cloud)) {
		std::cout << "error input!" << std::endl;
		return -1;
	}
	std::cout << cloud->points.size() << std::endl;
	pcl::visualization::CloudViewer viewer("Cloud Viewer");     
	viewer.showCloud(cloud);
	viewer.runOnVisualizationThreadOnce(viewerOneOff);
	system("pause");
	return 0;
}

```

**Comment by JackBoosY** [comment]
Hi @bbw2008927, thanks for reporting this issue.
Since boost has been upgrade to 1.70.0, this issue may be fixed.
Can you update vcpkg and rebuild pcl?

Thanks.

**Comment by bbw2008927** [comment]
Thanks, JackBoosY
It worked. I deleted orignal vcpkg and used git pull to install again.
And then new pcl can work.
These are test  code:
#include "pch.h"
#include <pcl/io/io.h>
#include <pcl/io/ply_io.h>
#include <pcl/io/pcd_io.h>
#include <pcl/visualization/cloud_viewer.h>
#include <vtkAutoInit.h>         
#include <iostream>
#define BOOST_FILESYSTEM_SOURCE
int user_data;
using std::cout;
void viewerOneOff(pcl::visualization::PCLVisualizer& viewer)
{
	viewer.setBackgroundColor(1.0, 0.5, 1.0);
}
int main()
{
	pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);
	char strfilepath[256] = "E:\\rabbit.pcd";
	if (-1 == pcl::io::loadPCDFile(strfilepath, *cloud)) {
		std::cout << "error input!" << std::endl;
		return -1;
	}
	std::cout << cloud->points.size() << std::endl;
	pcl::visualization::CloudViewer viewer("Cloud Viewer");
	viewer.showCloud(cloud);
	viewer.runOnVisualizationThreadOnce(viewerOneOff);
	system("pause");
	return 0;
}
