### ISSUE TITLE
Openssl installation failed in X64-Windows

### ISSUE THREAD

**Issue by cheerdown** [microsoft/vcpkg#5815]

**Comment by cheerdown** [comment]
![捕获](https://user-images.githubusercontent.com/36782174/54983615-2ac3e900-4fe8-11e9-88cb-37fd6422fac7.JPG)

when i install evpp，this failure shows。
err.log：
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage

**Comment by cheerdown** [comment]
![捕获](https://user-images.githubusercontent.com/36782174/54983882-a2921380-4fe8-11e9-94e3-d2f679ea757a.JPG)
the complete screenshots

**Comment by wangli28** [comment]
Same with #5713.

**Comment by vicroms** [comment]
@cheerdown can you try pulling the latest master and installing again?

`vcpkg_test_cmake()` has been disabled since it had several issues that were causing failures to install otherwise perfectly good packages.

**Comment by jwillemsen** [comment]
See #5713

**Comment by vicroms** [comment]
@cheerdown any updates on this issue?
You can also try to comment the `vcpkg_test_cmake()` line inside the ports that are giving you problems.

**Comment by PhoebeHui** [comment]
@cheerdown, does the issue still persist?

**Comment by PhoebeHui** [comment]
@cheerdown, please open a new issue if it's still be an issue for you.
