### ISSUE TITLE
Where to find current build status

### ISSUE THREAD

**Issue by martin-s** [microsoft/vcpkg#5823]
I've seen a build list in other issue (see example below). Is there a current list that shows the port status for the e.g. linux platform?

Regressions in `vtk:x64-osx` and `collada-dom:x64-linux`.

| x64-osx     | master | test | notes          |
| ----------- | ------ | ---- | -------------- |
| collada-dom | Fail   | Pass |
| vtk         | Pass   | Fail | **Regression** |
| pcl         | Pass   | Skip |
| vtk-dicom   | Pass   | Skip |

| x64-linux   | master | test | notes          |
| ----------- | ------ | ---- | -------------- |
| collada-dom | Pass   | Fail | **Regression** |

| x64-uwp     | master | test | notes          |
| ----------- | ------ | ---- | -------------- |
| freetype-gl | Skip   | Fail |
| pangolin    | Skip   | Fail |
| opencsg     | Skip   | Fail |
| glew        | Fail   | Pass |
| pixel       | Skip   | Fail |

[Build Debug Log Output for `collada-dom`](https://github.com/Microsoft/vcpkg/files/2985887/install-x64-linux-dbg-out.log)

_Originally posted by @vicroms in https://github.com/Microsoft/vcpkg/pull/5722#issuecomment-474620117_

**Comment by vicroms** [comment]
Hi @martin-s 

RIght now, build status and logs are only accesible by Microsoft internals;
we provide build status to PR submitters to aid in their debugging process. 

We are working on automating the feedback process and making logs and status available to PR submitters.

To my knowledge there's no documentation of which ports build on each platform. But this is something we should consider having in the future.

**Comment by JackBoosY** [comment]
Related: #6618.

**Comment by PhoebeHui** [comment]
Currently we have 'Supports'  to indicate the port support or unsupport on the platform.
