### ISSUE TITLE
boost-iostreams always requires zstdd.dll even on release builds

### ISSUE THREAD

**Issue by yamcenutzer** [microsoft/vcpkg#5825]
using vc2017/2015

an app using boost-iostreams and linked against appropriate libs (boost,.., zlib, etc) will work if compiled in debug mode,
but in release mode, the app won't run since it depends on zstdd.dll (the debug variant, which isn't available)

I guess it has something to do with how the dependencies are specified in boost-iostreams/...../src/CMakeLists.txt near line 33: 
...
find_library(ZSTD_LIBRARY NAMES zstdd zstd_staticd zstd zstd_static)
target_link_libraries(boost_iostreams PRIVATE ${ZSTD_LIBRARY})
...

**Comment by yamcenutzer** [comment]
FYI, this changed from boost 1.68 to 1.69.
IN 1.68 the problem wasn't there, as iostremas didn't require zstd:
here a excerpt from the appro cmakelists.txt from 1.68:
.....
find_package(ZLIB REQUIRED)
target_link_libraries(boost_iostreams PRIVATE ZLIB::ZLIB)

find_package(BZip2 REQUIRED)
target_link_libraries(boost_iostreams PRIVATE BZip2::BZip2)

find_package(LibLZMA REQUIRED)
target_include_directories(boost_iostreams PRIVATE ${LIBLZMA_INCLUDE_DIRS})
target_link_libraries(boost_iostreams PRIVATE ${LIBLZMA_LIBRARIES})
.....

**Comment by yamcenutzer** [comment]
sorry, pressed the wrong button..

**Comment by Neumann-A** [comment]
Is this fixed (Discussion seems to resolve the issue due to boost upgrade)? If not try #5543 else close issue please

**Comment by yamcenutzer** [comment]
no it isn't. release builds of boost_iostreams still depend on libzstdd.dll

BTW the same is true for libfmt  (release builds want fmtd.dll)

**Comment by Neumann-A** [comment]
the zstd issue should be fixed in #5543 now. For fmt are you using `find_package(fmt CONFIG)`?

**Comment by yamcenutzer** [comment]
yes, I use find_package(fmt CONFIG REQUIRED) or find_package(fmt REQUIRED CONFIG), i dunno the difference so I tried both, and then in the link_libraries I use fmf::fmt to get it

**Comment by Neumann-A** [comment]
> BTW the same is true for libfmt (release builds want fmtd.dll)
>yes, I use find_package(fmt CONFIG REQUIRED) or find_package(fmt REQUIRED CONFIG), i dunno the difference so I tried both, and then in the link_libraries I use fmf::fmt to get it

Are you looking at Release configuration or another configuration like RelWithDebInfo or MinSizeRel? As far as I took a look into the generated configs for FMT those are correct.

**Comment by yamcenutzer** [comment]
you're right Release (which I never use) works,
but the other two RelwithDbgInfo (which I always use) and MinSizeRel (which I also never use) are asking for fmtd, which isn't there...

**Comment by Neumann-A** [comment]
see #5621 how to solve it. But there is a commit in #5543 which automaticcally maps those configurations from the toolchain file

**Comment by yamcenutzer** [comment]
OK, then I guess I neeed to wait for #5543  to be accepted
Thx,

**Comment by yamcenutzer** [comment]
...that doesn't seem to be happening any time soon

**Comment by cbezault** [comment]
I'll get on #5534 asap.

**Comment by yamcenutzer** [comment]
to get back to the original question:
boost-iostreams still just insists on linking against the debug version zstd (zstdd.lib) in release builds

**Comment by WenyinWei** [comment]
Hello guys, I also meet the problem while compiling a project utilizing boost-iostream. Do you any good ideas to fix it or workaround?

**Comment by WenyinWei** [comment]
I directly dragged my compiled zstdd.dll to my executable working dir and it works now. Seems that the zstdd.dll cannot be found easily by vcpkg.

**Comment by yamcenutzer** [comment]
I changed the cmakelists.txt in the portfile for iostreams to do something like this:
if(MSVC)
    set_property(TARGET boost_iostreams PROPERTY OUTPUT_NAME_RELEASE boost_iostreams-vc140-mt)
    set_property(TARGET boost_iostreams PROPERTY OUTPUT_NAME_DEBUG boost_iostreams-vc140-mt-gd)

    set_property(TARGET boost_iostreams PROPERTY RUNTIME_OUTPUT_NAME_RELEASE boost_iostreams)
    set_property(TARGET boost_iostreams PROPERTY RUNTIME_OUTPUT_NAME_DEBUG boost_iostreamsd)
    if (CMAKE_BUILD_TYPE:STRING STREQUAL "Debug")
        find_library(ZSTD_LIBRARY NAMES zstdd zstd_staticd)
        target_link_libraries(boost_iostreams PRIVATE ${ZSTD_LIBRARY})
    else()
        find_library(ZSTD_LIBRARY NAMES zstd zstd_static)
        target_link_libraries(boost_iostreams PRIVATE ${ZSTD_LIBRARY})
    endif()
else()
    find_library(ZSTD_LIBRARY NAMES zstd zstd_static)
    target_link_libraries(boost_iostreams PRIVATE ${ZSTD_LIBRARY})
endif()



and then built iostreams again.
it still is a hack.

I personally don't get the point of vcpkg if there is no unified way of finding the included libs esp. if libs depend on each other

The original intent of vcpkg of making thios stuff available to vstudio is long gone, I believe.
vcpkg claims to be cross platform. Then it should define cross platfom unified way of finding libs.
Currently this would be cmake find_package or so

**Comment by cdcseacave** [comment]
Having the same issue, lately all Release versions of boost-iostreams depend on zstdd.dll

**Comment by Neumann-A** [comment]
`find_library(ZSTD_LIBRARY NAMES zstdd zstd_staticd zstd zstd_static NAMES_PER_DIR)` should do the trick

**Comment by yamcenutzer** [comment]
yes , seems to work now.
As a side note, is there a specific reason for the different naming scheme for boost-iostreams.dll ( as in : different from all other boost dlls)?

Thx

**Comment by cbezault** [comment]
In general we don't want vcpkg users to have to use any magic #6624 merged the fix that @Neumann-A recommended to you. There are historical reasons for the iostream naming that I can't recall right now, maybe @ras0219-msft can remind me.

**Comment by yamcenutzer** [comment]
> In general we don't want vcpkg users to have to use any magic 

exactly my point.
so what would be the one uniform way to find libraries when using vcpkg with cmake?
find_package doesn't always work, and in this special case it also doesn't work for boost-iostreams trying to find zstd, which is why this magic was used.

Wasn't that (one of) the mission statement(s) for vcpkg? one lib manager to rule them all?.. :-)

For vs (msbuild) users it already works using the include *.lib magic, but that really is msbuild specific.

**Comment by NancyLi1013** [comment]
Hi @yamcenutzer thanks for posting this issue.
This issue should be fixed now by the PR #6624. 
Please close this issue if it is not a problem for you.

Thanks.
