### ISSUE TITLE
Need feature: vcpkg should return the root of specified package

### ISSUE THREAD

**Issue by junjiemars** [microsoft/vcpkg#5826]
Need feature: vcpkg should return the root of specified package

So, to include the header and link library more easy in a Makefile  or by hand.

vcpkg help list
The argument should be a substring to search for, or no argument to display all installed libraries.
Example:
  vcpkg list png

Options:
    --x-full-desc                            Do not truncate long text
    --x-root                                   Return the root path of specified package
    --triplet <t>                            Set the default triplet for unqualified packages
    --vcpkg-root <path>                      Specify the vcpkg directory to use instead of current directory or tool directory

for example:
vcpkg list pthreads:x64-windows --x-root
should returns e:/vcpkg/installed

**Comment by Neumann-A** [comment]
> So, to include the header and link library more easy in a Makefile or by hand.

that seems to go against the intended use of vcpkg. 
Either use Visual Studio integration or CMake and a find_package call. 

> for example:
vcpkg list pthreads:x64-windows --x-root
should returns e:/vcpkg/packages

that would also be the wrong root (should probably be `e:/vcpkg/packages/<packagename>-<triplet>`) but the packages dir is just a 'temporary' directory. The real working directory is `/vcpkg/installed/<triplet>/`

**Comment by junjiemars** [comment]
1. vcpkg is a individual C package manager not a  auxiliary tool of CMake' or Visual Studio, so we can use raw Makefile to compile and link package.

2. /vcpkg/installed/ as the root is right.

**Comment by MikeGitb** [comment]
> Either use Visual Studio integration or CMake and a find_package call.

Not all packages support find_package and not all projects use cmake and or msvc.

**Comment by PhoebeHui** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.
