### ISSUE TITLE
can vcpkg suport qt5webengine?

### ISSUE THREAD

**Issue by xspeed1989** [microsoft/vcpkg#5828]
can vcpkg suport qt5webengine?

**Comment by JackBoosY** [comment]
@Neumann-A Could you have a look? Thanks.

**Comment by Neumann-A** [comment]
There is no reason to not have it. In the time there was only one qt port it was actually build. The only thing it requires is a lot of time to compile if I remember correctly. Just try to add it like the other qt5-subports but don't make it a dependency in the qt5 port. Maybe the qt5 port should be rewritten to use features for every qt5 subport.

**Comment by pwilkin** [comment]
I just tried to do it and it's not that easy, since the build for WebEngine requires Flex, Bison and GPerf and only GPerf has a package in vcpkg.

**Comment by Neumann-A** [comment]
>WebEngine requires Flex, Bison and GPerf

but you can use vcpkg_find_acquire_program for those... 
I did it in #9860 but qt webengine still fails due to not finding an include file which strangely exists. (Don't understand whats going on here)

**Comment by pwilkin** [comment]
True, I adapted your changes, but my compile now breaks due to some new "compatibility breaking" mechanism introduced in the new VS2019 (error C3848 while compiling chromium/third_party/sfntly/src/cpp/src/sfntly/font.cc). Do you know where to disable specific VS compiler errors for qmake?

**Comment by Neumann-A** [comment]
> error C3848

it fails due to missing `const` specifiers. That needs to be patched in the source and probably can not be fixed by a compiler switch.

**Comment by isanych** [comment]
Here extract from my python script patching one of previous versions for vs2019 (linux change for lto support):
```
replace_in_file("qtwebengine/src/3rdparty/chromium/ui/gfx/image/image_generic.cc",
                "bool operator()(const ImageSkiaRep& rep1, const ImageSkiaRep& rep2) {",
                "bool operator()(const ImageSkiaRep& rep1, const ImageSkiaRep& rep2) const {")
replace_in_file("qtwebengine/src/3rdparty/chromium/third_party/sfntly/src/cpp/src/sfntly/table/header.cc",
                "const HeaderPtr rhs) {",
                "const HeaderPtr rhs) const {")
replace_in_file("qtwebengine/src/3rdparty/chromium/third_party/sfntly/src/cpp/src/sfntly/table/header.h",
                "const HeaderPtr h2) = 0;",
                "const HeaderPtr h2) const = 0;")
replace_in_file("qtwebengine/src/3rdparty/chromium/third_party/sfntly/src/cpp/src/sfntly/table/header.h",
                "const HeaderPtr h2);",
                "const HeaderPtr h2) const;")
replace_in_file("qtwebengine/src/3rdparty/chromium/v8/src/compiler/register-allocator.h",
                "bool operator()(LiveRange* a, LiveRange* b) {",
                "bool operator()(LiveRange* a, LiveRange* b) const {")
if is_linux:
    replace_in_file("qtscript/src/3rdparty/javascriptcore/JavaScriptCore/jit/JITStubs.h",
                    "EncodedJSValue JIT_STUB cti_vm_throw(STUB_ARGS_DECLARATION);",
                     "EncodedJSValue JIT_STUB cti_vm_throw(STUB_ARGS_DECLARATION) __attribute__((used));")
```

**Comment by pwilkin** [comment]
Got to the point you mentioned. It's probably related to this: 

https://bugreports.qt.io/browse/QTBUG-65677
