### ISSUE TITLE
Triplets are not accepted in package names in response_file

### ISSUE THREAD

**Issue by studiofuga** [microsoft/vcpkg#5840]
Create a `sample.txt` file with the following content:

`zlib:x86-windows` 

Then launch vcpkg with any command like build, install or export:

`.\vcpkg.exe install @sample.txt`

**Expected behaviour**: The zlib package is installed for the triplet x86-windows

**Effective behaviour**: "Error: invalid triplet: x86-windows"

**Comment by PhoebeHui** [comment]
This bug seems to be fixed now.

PS F:\vcpkg\src> .\vcpkg.exe install "@sample.txt"
Computing installation plan...
The following packages are already installed:
    zlib[core]:x86-windows
Package zlib:x86-windows is already installed

Total elapsed time: 1.104 ms

The package zlib is compatible with built-in CMake targets:

    find_package(ZLIB REQUIRED)
    target_link_libraries(main PRIVATE ZLIB::ZLIB)
