### ISSUE TITLE
[Request] fswatch

### ISSUE THREAD

**Issue by warrenrentlytics** [microsoft/vcpkg#5843]
https://github.com/emcrisostomo/fswatch

Has > 2,800 stars. Seems worthy of being included.

**Comment by NancyLi1013** [comment]
Hi @warrenrentlytics, thanks for posting this issue. We try to add this port and find some problems in source:
1. libfswatch_config.h are not found in source.
2. This port only supports Linux.
3. Without build documentation.
4. Some macro such as PACKAGE_STRING PACKAGE_NAME PACKAGE_BUGREPORT PACKAGE PACKAGE_URL are not found.
5. It seems like that the port has code bug in source. eg: optarg and getopt not found.
Considering the above problems in source, we won't add this port to the vcpkg list currently till these problems are solved.

**Comment by warrenrentlytics** [comment]
Thank you for looking into this.

**Comment by SamuelMarks** [comment]
Can we reopen this? - Keen for fswatch. - Can try and add the port.
