### ISSUE TITLE
libcurl broken

### ISSUE THREAD

**Issue by johannes1971** [microsoft/vcpkg#5845]
The version of libcurl that is currently in vcpkg, with version string "libcurl/7.61.1-DEV WinSSL zlib/1.2.11", is:

1. Out of date. The latest is 7.64.1
2. A "dev" version, i.e. unstable and untested. 
3. Broken: there is a high chance of crashes in curl_multi_remove_handle. This is fixed by the developers in 7.64.1.
4. Built without support for loading client certificates from files, a feature I need badly.

I'm being blocked by issues 3 and 4.

**Comment by PhoebeHui** [comment]
@johannes1971, Curl currently upgrade to 7.65.0, also support several feature now,  could you check if it contains the one you want?
see feature in https://github.com/microsoft/vcpkg/blob/master/ports/curl/CONTROL

**Comment by johannes1971** [comment]
I checked the latest version in vcpkg, and it works fine - thanks!

**Comment by PhoebeHui** [comment]
Glad to hear that!
