### ISSUE TITLE
[qt5] upgrade to qt5.9.1

### ISSUE THREAD

**Issue by sdcb** [Microsoft/vcpkg#585]
http://blog.qt.io/blog/2017/01/23/qt-5-8-released/
http://blog.qt.io/blog/2017/06/30/qt-5-9-1-released/

**Comment by barcharcraz** [comment]
I'd be interested in using the new "Lite" configure system for this.

**Comment by nagua** [comment]
I have done a bit of the required work for a qt5.8 port. For more detail see my answer to #787 .

**Comment by bagong** [comment]
+1
A working static build would be particularly appreciated ;) Thanks!

**Comment by MikeGitb** [comment]
@sdcb : Can be closed right?

**Comment by sdcb** [comment]
@MikeGitb Of course, thanks for all your great work.

**Comment by MikeGitb** [comment]
Just to avoid confusion: I'm not associated with ms or this project and in fact haven't made any contributions to it so far.
