### ISSUE TITLE
Can't build cpprestsdk - Error: Building package boost-compatibility:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by mraghup** [microsoft/vcpkg#5856]
Trying to build the latest cpprestsdk and I am getting the following error:

```
-- Downloading https://github.com/boostorg/compatibility/archive/boost-1.69.0.tar.gz...
-- Downloading https://github.com/boostorg/compatibility/archive/boost-1.69.0.tar.gz... Failed. Status: 4;"A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision."
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:172 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:108 (vcpkg_download_distfile)
  ports/boost-compatibility/portfile.cmake:5 (vcpkg_from_github)
  scripts/ports.cmake:71 (include)


Error: Building package boost-compatibility:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-compatibility:x64-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.
```

I tried setting both HTTP_PROXY and HTTPS_PROXY and tried running vcpkg update. None of the solutions helped.

**Comment by vicroms** [comment]
Hi @mraghup

We're unable to reproduce this issue locally. 

But maybe this workaround will work for you.

1) Download the source code with a web browser from: https://github.com/boostorg/compatibility/archive/boost-1.69.0.tar.gz
2) Save it inside `<path_to_vcpkg>/downloads/`.
3) Run `./vcpkg install cpprestsdk` again

**Comment by mraghup** [comment]
Sorry, it still does't work. It throws the same error. Honestly, I don't have to build the source. Where can I download the 2.10.2 pre-built binaries?

Thanks again.

**Comment by mraghup** [comment]
Never mind. I used NuGet extension through VS2017 to get the correct package. Thanks.

**Comment by mraghup** [comment]
Back from the dead again. Apparently, I have to to build cpprestsdk from source. Following a suggestion from the issue [1276](https://github.com/Microsoft/vcpkg/issues/1276), I tried building boost separately to see if I have better luck. Here's the full console output. I wish there was more info than just "BUILD_FAILED"

c:\vcpkg>.\vcpkg.exe install boost-system:x64-windows
The following packages will be built and installed:
  * boost-assert[core]:x64-windows
  * boost-build[core]:x64-windows
  * boost-compatibility[core]:x64-windows
  * boost-config[core]:x64-windows
  * boost-core[core]:x64-windows
  * boost-detail[core]:x64-windows
  * boost-integer[core]:x64-windows
  * boost-modular-build-helper[core]:x64-windows
  * boost-predef[core]:x64-windows
  * boost-preprocessor[core]:x64-windows
  * boost-static-assert[core]:x64-windows
    boost-system[core]:x64-windows
  * boost-winapi[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/13: boost-compatibility:x64-windows
Building package boost-compatibility[core]:x64-windows...
-- Downloading https://github.com/boostorg/compatibility/archive/boost-1.69.0.tar.gz...
-- Downloading https://github.com/boostorg/compatibility/archive/boost-1.69.0.tar.gz... Failed. Status: 4;"A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision."
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:172 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:108 (vcpkg_download_distfile)
  ports/boost-compatibility/portfile.cmake:5 (vcpkg_from_github)
  scripts/ports.cmake:71 (include)


Error: Building package boost-compatibility:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-compatibility:x64-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by vicroms** [comment]
@mraghup 

I'm unable to reproduce your issue with a fresh copy from master, are you behind a proxy?

You should still be able to use this workaround:

1. Download `boost-compatibility` source code from https://github.com/boostorg/compatibility/archive/boost-1.69.0.tar.gz using a web browser.
2. Save it as `boostorg-compatibility-boost-1.69.0.tar.gz`.
3. Copy the downloaded file into `<vcpkg_folder>/downloads/`.
4. Run `./vcpkg install cpprestsdk` again.

This time, the download step should be skipped and you will be able to proceed with the install.

**Comment by mraghup** [comment]
@vicroms 
Thanks for the step 2. I saved it without renaming earlier. Now vcpkg skips this file but runs into the same issue with another file.

-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.65.1/LICENSE_1_0.txt...
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.65.1/LICENSE_1_0.txt... Failed. Status: 4;"A requested feature, protocol or op
tion was not found built-in in this libcurl due to a build-time decision."
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:172 (message):

      Failed to download file.

It seems to be either my proxy or firewall. Will try again, from home.

Thanks.

**Comment by wangli28** [comment]
Hi @mraghup, thanks for posting this issue, does the issue persist?

**Comment by wangli28** [comment]
Please open a new issue if this is still a problem for you.
