### ISSUE TITLE
Downloading freeglut failed

### ISSUE THREAD

**Issue by 874656645** [Microsoft/vcpkg#5861]
Hi guys, I run into problems when I install freeglut lib. I can not download freeglut-3.0.0.tar.gz. Do you have any ideas for this situation?
![image](https://user-images.githubusercontent.com/5737120/55212667-8b8f3380-522b-11e9-98cc-37d9a2028cf9.png)

**Comment by vicroms** [comment]
Hi @874656645 

We're unable to reproduce this issue locally. 

But maybe this workaround will work for you.

1) Download the source code with a web browser from: https://svwh.dl.sourceforge.net/project/freeglut/freeglut/3.0.0/freeglut-3.0.0.tar.gz
2) Save it inside `<path_to_vcpkg>/downloads/`.
3) Run `./vcpkg install freeglut:x64-windows` again

**Comment by PhoebeHui** [comment]
This issue temporarily happen when download the source, the workaround should work, please let us know if it still block you.

**Comment by 874656645** [comment]
Yes, I tried just now. I got this:


vcpkg install freeglut
The following packages will be built and installed:
    freeglut[core]:x86-windows
Starting package 1/1: freeglut:x86-windows
Building package freeglut[core]:x86-windows...
A suitable version of git was not found (required v2.21.0). Downloading portable git v2.21.0...
Downloading git...
  https://github.com/git-for-windows/git/releases/download/v2.21.0.windows.1/PortableGit-2.21.0-32-bit.7z.exe -> F:\OpenSourceProject\vcpkg\downloads\PortableGit-2.21.0-32-bit.7z.exe
WinHttpReceiveResponse() failed: 12002

**Comment by GreenEminence** [comment]
I'm having the same issue and the `extract-err.log` shows this:
`CMake Error: Problem with archive_write_header(): Can't create ''
CMake Error: Current file: freeglut-3.0.0/progs/test-shapes-gles1/android_toolchain.cmake
CMake Error: Problem extracting tar: C:/Users/greeneminence/dev/vcpkg/downloads/freeglut-3.0.0.tar.gz`

**Comment by 874656645** [comment]
I guess it is the issue of networks. You can download the package manually and put it in the downloads folder. You can find the download link in the log file.
