### ISSUE TITLE
How can I build poco library with mysql feature

### ISSUE THREAD

**Issue by yuntong613** [microsoft/vcpkg#5864]
It seem that poco default building doesn't install libmysql first.what can I do for mysql support versiong building

**Comment by vicroms** [comment]
Hi @yuntong613, 

You can check which features are offered by a package by checking their CONTROL file.

In this case by reviewing `ports/poco/CONTROL` we can see that there's a `mysql` feature, which installs `libmysql`.

To install it run:

`./vcpkg install poco[mysql]`

**Comment by PhoebeHui** [comment]
Looks there is no reason to keep this issue active, feel free to reopen it if it still be an issue for you.
