### ISSUE TITLE
vcpkg runs very slow

### ISSUE THREAD

**Issue by unbored** [Microsoft/vcpkg#5867]
It waits for a long time when it runs to next step. Even running 'vcpkg list' it costs several minutes to exit after showing the installed packages. Pressing Control-C when it waits leads to pop up of a window showing that 'vcpkg.exe stopped working', then current powershell window lost response. The same thing occurs when it runs to 'Building package XXX...', 'Performing post-build validation' and many other places. No errors occur if wait patiently. 
I remember it used to be normal before the last update and a new compile I made several days ago. I wonder if there is a log showing what vcpkg is actually doing.

**Comment by vicroms** [comment]
HI @unbored 

Can you give us more details about your setup? 
What VS version(s) are you using?
What packages have you noticed that have this issue?

Build time and speed is dependent on the package itself.

I have noticed that sometimes `vcpkg` stops printing output to the console during a building step, (probably the buffer isn't getting flushed), but in those cases pressing ENTER in the console causes the buffer to be printed at once; if nothing gets printed, it means that `vcpkg` is still on the same build step.

**Comment by unbored** [comment]
@vicroms I'm using VS 2015 update 3 and Win10 17763.134.
I don't think it is related to the packages. I just run 'vcpkg list' and it will stuck.
I just created a new repo and moved directories 'buildtrees', 'downloads', 'installed' and 'packages' to the new one and found the problem solved. I've no idea what happend to the old one.

**Comment by vicroms** [comment]
Well, glad that it works now.
