### ISSUE TITLE
protobuf fails to install

### ISSUE THREAD

**Issue by degski** [microsoft/vcpkg#5869]
[extract-err.log](https://github.com/Microsoft/vcpkg/files/3022550/extract-err.log)

I also manually downloaded the file and the file-hashes stack up, so it's certain the download is not corrupt.

**Comment by vicroms** [comment]
Hi @degski

I've tried unsuccessfully to reproduce this issue. 

It seems to be an issue with zlib, but I cannot get a repro even when deleting my cached protobuf files.
Here's a couple of things you could try:
1) Pulling the most up-to-date `vcpkg`.
```
git pull origin master
./bootstrap-vcpkg.bat
rm -r buildtrees/protobuf
rm downloads/google-protobuf*
./vcpkg install protobuf
```

2) Running vcpkg in a clean environment (try this if the former doesn't work).
```
./vcpkg env
vcpkg install protobuf
exit

# Notice the lack of "./" in the second command, use "exit" to get back to PowerShell.
```

**Comment by degski** [comment]
@vicroms I've tried both 1. and 2., with the exact same result [the extract-err.log says exactly the same as it did before].

    CMake Error: Problem with archive_write_header(): Can't create ''
    CMake Error: Current file: protobuf-3.7.1/examples/third_party/zlib.BUILD
    CMake Error: Problem extracting tar: Y:/vcpkg/downloads/google-protobuf-v3.7.1.tar.gz

When I look into: `Y:\vcpkg\buildtrees\protobuf\src\TEMP\protobuf-3.7.1\examples\third_party` there is actually nothing [empty folder]. As compared to the contents of the archive, about half is extracted (I mean some stuff is there, but clearly not all).

    Some facts:
        cmake version 3.14.0.
        I run everything from elevated command prompt(s).
        The disk(s) are not full.
        Changed the PS execution policy to unrestricted for the current user (no change).
        I run no AV.

**Comment by Chingyat** [comment]
I have the same issue.
```
CMake Error: Problem with archive_write_header(): Can't create ''
CMake Error: Current file: protobuf-3.7.1/examples/third_party/zlib.BUILD
CMake Error: Problem extracting tar: Z:/Code/vcpkg/downloads/google-protobuf-v3.7.1.tar.gz
```
I found that the file `protobuf-3.7.1/examples/third_party/zlib.BUILD` in the archive is a symbolic link to `../../third_party/zlib.BUILD`. So I manually extracted the archive and replaced the symbolic link with the file it links to.  Then I recompressed the archive and modified the hash in the portfile. Re-run the install command.
```
.\vcpkg install protobuf
```
It built successfully. 
I hope this would help you.

**Comment by degski** [comment]
@vicroms The same issue is now also affecting (failing) the build of SFML (#6220). Please have a look at @Chingyat 's comment.

**Comment by MaoKwen** [comment]
Have the same issue while building `SDL2` package. By following @Chingyat 's comment it built successfully.

Note: package portfile located in `<path-to-vcpkg>\ports\<package-name>\portfile.cmake`.

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/6220
