### ISSUE TITLE
vcpkg_copy_pdbs fails if dumpbin output is localized

### ISSUE THREAD

**Issue by codicodi** [Microsoft/vcpkg#587]
I noticed that after 'VS2017 support' upgrade pdbs are not picked up correctly for me.
Installation output:
```
>vcpkg install zlib
...
-- Warning: Could not find a matching pdb file for:
    G:/libraries/vcpkg/packages/zlib_x64-windows/bin/zlib1.dll
    G:/libraries/vcpkg/packages/zlib_x64-windows/debug/bin/zlibd1.dll
...
Package zlib:x64-windows is installed
```
This is probably because vcpkg_copy_pdbs searches for `PDB file found at` string, which may look a little diffrent if output is localized. For example, in Polish translation:
`  Znaleziono plik PDB w pozycji „G:\libraries\vcpkg\buildtrees\zlib\x64-windows-rel\Release\zlib.pdb”`
Btw this is pretty unexpected beacuse I explicitly installed only English language pack for VS2017.

**Comment by alexkaratarakis** [comment]
I will investigate how I can make this locale independent.
Regarding the last sentence, is your system locale Polish? In which case, `dumpbin.exe` follows the system locale instead of the language bug you have installed which would indicate a bug. I will file a bug about this issue.

**Comment by codicodi** [comment]
Yes it is. To be precise: IDE's language is correctly set to English but cmd line output (from dumpbin, cl etc) is localized. I see both laguages listed in installer but trying to remove one of them does nothing (installer "runs" for a few seconds but nothing gets unistalled). I think this problem is already known as I've seen a few bug reports online with similar issues.

**Comment by alexkaratarakis** [comment]
Should be fixed. Please confirm :)

**Comment by codicodi** [comment]
Works now, thanks!

**Comment by Erlkoenig90** [comment]
I stumbled on this exact error, with MSVC set to German and no English language pack installed. Dumpbin silently reverts to German and PDB files aren't installed. I'd suggest adding a check for whether dumpbin's output is actually english (e.g. check for presence of `Dump of file`), and if it isn't, print a warning suggesting to install the English language pack rather than have the user debug this themselves.
