### ISSUE TITLE
VCPkg integration with SCons build system

### ISSUE THREAD

**Issue by jediry** [microsoft/vcpkg#5872]
Hello,

I am investigating adding SCons support to VCPkg. I see that there is a scripts/buildsystems directory containing integrations for msbuild and CMake, so this seems like the natural place to add a SCons "tool". I imagine the syntax within an SConstruct file using this tool looking something like this:

`packages += env.VCPkg('boost-smart-ptr', STATIC=true)`
`packages += env.VCPkg('fftw3')`
`...`
`env.Program('my_program', LIBS=packages.libs())`

...possibly with some (currently unspecified) integration with SCons's Configure mechanism for detecting the presence of headers/libs, so that we skip the VCPkg download/build if the desired packages are already otherwise available.

Questions:
1. Is this a change that is likely to be accepted?
2. Is anyone already working on this, or have they in the past?
3. Is there a way to query for the list of files that _would be built_ without actually building a package? SCons wants to know build outputs before they're built in order to do dependency analysis. Thus, it would be extremely useful to be able to generate the list of files that would be built, given a package name and triplet. I could not find such a command in the command-line help of vcpkg.exe...does it exist? If not, how hard would it be to add this?

**Comment by jediry** [comment]
UPDATE: since posting this, I have mostly implemented this, in the SCons source, without needing any changes to vcpkg. However, my last question is still pertinent: without being able to get a list of built files that a package build produces, the integration is...awkward. I basically have to front-load the building of a package into the wrong phase of SCons setup, so that I can get the list of built files early enough for SCons to compute build dependencies. I would like to fix this if possible.

I can think of two basic solutions:
1. Add a flag to "vcpkg install" that simulates a build without building anything, but just spits out the list of files that would be built. At first glance, this seems difficult...from inspecting the source, it appears that vcpkg doesn't know what files will be built, but instead just invokes CMake to build the package and then discovers what it built. But perhaps there's some way to get CMake to report what it would build?
2. Maintain a cache of built file .lists that can be queried. Two variations here come to mind:
  a. Maintain a web service from which vcpkg.exe can download the built file .list file for a given package + triplet + feature list. These files could be generated by actually building each project on a continuous integration server somewhere, which would also serve the purpose of ensuring that each package builds correctly.
  b. Have a continuous integration server that builds each project, and then checks in the resulting .list files into the vcpkg Git repo.

Option (1.) seems more desirable, since it avoids the need for setting up additional web service and/or any automated processes on a CI server. However, if (1.) is intractable, then (2.a.) or (2.b.) could provide a viable way to predict build artifacts.

**Comment by axsaucedo** [comment]
Is this a planned feature or still in discussion? The integration in cmake works quite well as it doesn't force users to add any custom modifications besides passing the `-DCMAKE_TOOLCHAIN_FILE=` parameter. A similar solution for scons would also be ideal

**Comment by axsaucedo** [comment]
@jediry for the meantime it woudl actually be quite useful if you have managed to identify a recommended way to implement this, if you have an example that would be quite useful as well! Thank you
