### ISSUE TITLE
opencv failed build

### ISSUE THREAD

**Issue by Barashuk** [microsoft/vcpkg#5873]
Guys, I’m really bad at writing in English, so help me figure it out. When assembling, writes "Command filed: ninja; -v".
 System: Windows 8.1(ver 6.3 build 9600), Visual Studio 2015 Update 3 ver 14.0.25431.01
CMake 3.13.3

Logs:
[config-x86-windows-static-out.log](https://github.com/Microsoft/vcpkg/files/3024800/config-x86-windows-static-out.log)
[CMakeOutput.log](https://github.com/Microsoft/vcpkg/files/3024799/CMakeOutput.log)
[CMakeError.log](https://github.com/Microsoft/vcpkg/files/3024798/CMakeError.log)

**Comment by Voskrese** [comment]
`command "rc /foCMakeFiles\cmTC_6c993.dir/manifest.res CMakeFiles\cmTC_6c993.dir/manifest.rc"`

`rc.exe` Не удается найти указанный файл

в Windows SDK

**Comment by Barashuk** [comment]
I add path rc.exe to PATH variable, but error did not disappear.
path to rc.exe
C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x86
C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64

**Comment by Voskrese** [comment]
смаке и vcpkg ищет sdk через реестр

попробуте скопировать два файла rc.exe и rc ...dll в 
C:\Program Files (x86)\Windows Kits\10\bin

В общем вижу только в этом ошибку. Может кто еще подскажет

**Comment by Barashuk** [comment]
Пробовал не помогло. Установил так же все Windows SDK и они не помогли. Конечно, перезагрузку ПК после установки делал.

**Comment by Voskrese** [comment]
Windows sdk 8.0-8.1 стоит?
На сколько я знаю, msvc 2015 первоначально использовал sdk 8.1.
И еще, попробуйте использовать х86 битную смаке, возможно смаке  х64 ищет в реестре под свою арч, но там ничего нет, все пути лежат в  WoW64

**Comment by PhoebeHui** [comment]
Duplicated to issue https://github.com/microsoft/vcpkg/issues/5299. please reopen it if it still be an issue for you.

You can workaround this by installing windows sdk by VS, then the rc.exe path will set to
C:\Program Files (x86)\Windows Kits\10\bin\x64\rc.exe
C:\Program Files (x86)\Windows Kits\10\bin\x86\rc.exe
