### ISSUE TITLE
Error in .\vcpkg install sqlite3

### ISSUE THREAD

**Issue by xDzai94** [microsoft/vcpkg#5875]
PS C:\Users\x\vcpkg> .\vcpkg install sqlite3
The following packages will be built and installed:
    sqlite3[core]:x86-windows
Starting package 1/1: sqlite3:x86-windows
Building package sqlite3[core]:x86-windows...
-- Using cached C:/Users/x/vcpkg/downloads/sqlite-amalgamation-3260000.zip
-- Using source at C:/Users/x/vcpkg/buildtrees/sqlite3/src/3260000-c1b7ab1eed
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: C:/Users/x/vcpkg/buildtrees/sqlite3/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\x\vcpkg\buildtrees\sqlite3\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:269 (vcpkg_execute_required_process)
  ports/sqlite3/portfile.cmake:25 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package sqlite3:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sqlite3:x86-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

I have no idea what is the likely solution for problem encountered here, can anyone please help ?

**Comment by xDzai94** [comment]
[CMakeError.log](https://github.com/Microsoft/vcpkg/files/3025296/CMakeError.log)
[config-x86-windows-out.log](https://github.com/Microsoft/vcpkg/files/3025297/config-x86-windows-out.log)

**Comment by Voskrese** [comment]
```
    RC Pass 1: command "rc /foCMakeFiles\cmTC_01657.dir/manifest.res CMakeFiles\cmTC_01657.dir/manifest.rc" failed (exit code 0) with the following output:
    The system cannot find the file specified
```

command "rc -  `cannot find the file specified`

**Comment by PhoebeHui** [comment]
@xDzai94, thanks for posting this issue!

I installed it successfully, does the issue still persist? could you get vcpkg latest revision and have a try?

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
