### ISSUE TITLE
OpenCV 4.x

### ISSUE THREAD

**Issue by micham1111** [microsoft/vcpkg#5876]
I suggest to add a new library for the public catalog, OpenCV 4.x

**Comment by vicroms** [comment]
Hi @micham1111 

There's a PR in progress #5169 to add OpenCV 4.

It has proven to be an extensive endeavor, but it looks like it is finally coming together.

**Comment by micham1111** [comment]
thanks.
How to install OpenCV4.x?
the command  ./vcpkg search opencv  stil return opencv   3.4.3-8

**Comment by vicroms** [comment]
Hi @michan1111

It should be a simple `vcpkg install opencv`.
The current default version is OpenCV 4.1.1.


Do you have the latest vcpkg sources?
Please try these instructions:

```
cd <path to vcpkg>
git pull origin master
./bootstrap-vcpkg.bat
./vcpkg install opencv
```

**Comment by micham1111** [comment]
Thanks.
