### ISSUE TITLE
libsodium for x64-linux (patch)

### ISSUE THREAD

**Issue by fhajji** [Microsoft/vcpkg#5883]
libsodium still fails to compile on Linux. Here's a patch to fix this:

[libsodium-portfile.cmake.patch.txt](https://github.com/Microsoft/vcpkg/files/3026678/libsodium-portfile.cmake.patch.txt)

Basically, it's about adding calls to 'autogen.sh', 'configure', 'make' in the non-WIN32 case.

**Comment by past-due** [comment]
@fhajji: There's actually a PR (#5600) to port `libsodium` over to a CMake build system that works better on all platforms. Maybe give that a try?

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
