### ISSUE TITLE
qt5-base:x64-linux - Qt's configure script is confused about libpq

### ISSUE THREAD

**Issue by Izowiuz** [microsoft/vcpkg#5884]
Short introduction of the situation first :P

When we are compiling Qt statically, dynamically loaded plugins are disabled.
As per Qt's config:

> Note: Using static linking will disable the use of dynamically
loaded plugins. Make sure to import all needed static plugins,
or compile needed modules into the library.

Basically, to import them we have to use Q_IMPORT_PLUGIN macro and link to static plugins (for example, Qt5::QPSQLDriverPlugin under CMake).

Now here comes the problem.

I'm using qt5-base package for my application under Ubuntu 18.04.2 LTS. Said application requires both sqlite and postgresql Qt drivers. When I install qt5-base I see that VCPKG installs libpq - which is necessary to fulfill postgresql dependency - but by inspecting config-x64-linux-rel-err.log file I see that PostgreSQL driver is disabled:

>Qt Sql Drivers:
  DB2 (IBM) .............................. no
  InterBase .............................. no
  MySql .................................. no
  OCI (Oracle) ........................... no
  ODBC ................................... no
  PostgreSQL ............................. no
  SQLite2 ................................ no
  SQLite ................................. yes
    Using system provided SQLite ......... yes
  TDS (Sybase) ........................... no

To make Qt configure happy I have to install system package libpq-dev. Now, when I actually try to use static postgresql plugin I get a few link errors:

> /home/izowiuz/vcpkg/installed/x64-linux/lib/libpq.a(fe-connect.c.o): In function `connectFailureMessage':
fe-connect.c:(.text+0xcfb): undefined reference to `inet_net_ntop'
fe-connect.c:(.text+0xd43): undefined reference to `inet_net_ntop'
/home/izowiuz/vcpkg/installed/x64-linux/lib/libpq.a(fe-connect.c.o): In function `PQconnectPoll':
fe-connect.c:(.text+0x3c89): undefined reference to `getpeereid'
collect2: error: ld returned 1 exit status
CMakeFiles/mrserver_release.dir/build.make:803: recipe for target 'mrserver_release' failed
make[2]: *** [mrserver_release] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/mrserver_release.dir/all' failed
make[1]: *** [CMakeFiles/mrserver_release.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

Analyzing further, I see that my project is configured to use VCPKG provided libpq as denoted by:

>[CMake] -- Found PostgreSQL: /home/izowiuz/vcpkg/installed/x64-linux/lib/libpq.a (found version "9.6.3") 
[CMake] -- Found OpenSSL: /home/izowiuz/vcpkg/installed/x64-linux/lib/libcrypto.a (found version "1.0.2q")  

This is of course fixed by manually linking to the system library, in my case:

> target_link_libraries(${TARGET_FULL_NAME}
    PRIVATE
		/usr/lib/x86_64-linux-gnu/libpq.a
    ==== REST OF THE STUFF ====
    )

Which in turn allows me to use postgresql driver.

**Comment by Izowiuz** [comment]
Hmm, not sure if my cmakefoo is solid enough, but maybe what is needed is additional external dependency added to:

> Remove vendored dependencies to ensure they are not picked up by the build
foreach(DEPENDENCY freetype zlib harfbuzzng libjpeg libpng double-conversion sqlite)
    if(EXISTS ${SOURCE_PATH}/src/3rdparty/${DEPENDENCY})
        file(REMOVE_RECURSE ${SOURCE_PATH}/src/3rdparty/${DEPENDENCY})
    endif()
endforeach()

**Comment by Izowiuz** [comment]
As per quote from https://bugreports.qt.io/browse/QTBUG-52995

> The correct way to compile against a different PostgreSQL installation is to have its pg_config script first in PATH or pass the path to that pg_config in the -psql_config option.

`configure -psql_config $PGDIR/bin/pg_config {...}`

So now I just have to find out how to do it in CMake : P

**Comment by Izowiuz** [comment]
It seems that, at least on Windows 10, pg_config is in location: 

> [some_path]\vcpkg\downloads\tools\perl\c\bin

This does not seem like something that can be safely passed to Qt's configure script, hmm.

**Comment by Izowiuz** [comment]
Well, currently libpq port is not building pq_config utility on Linux. On Windows it is downloaded from somewhere, I believe? Fix for this should probably modify libpq port to allow for building and installation of additional utilities, for 'proper' [as pointed out in old QTBUG-52995 report] fix.

**Comment by edmBernard** [comment]
@Izowiuz I just got the same issue with soci and the postgresql backend, did you planned to PR a fix on libpq port in vcpkg ?

**Comment by Izowiuz** [comment]
I didn't have time to take a deeper look at it, yet.
From what I remember the problematic part is pkg_config_paths.h file which is normally generated during make'ing of libpq project. 
It would have to be provided in a same matter as pg_config.linux.h in libpq's port directory OR somehow generated on-the-fly.

**Comment by edmBernard** [comment]
thanks, I have find this https://www.postgresql.org/docs/10/libpq-build.html . I will test on my side too.

**Comment by edmBernard** [comment]
ok thanks for you help I was able to fix libpq for my need I will make a PR for libpq on linux

**Comment by JackBoosY** [comment]
Please reopen this issue if it still bother you.
