### ISSUE TITLE
CGAL Library update

### ISSUE THREAD

**Issue by JoelMontana** [Microsoft/vcpkg#5888]
Please update the CGAL library to version 4.14. 

cgal  4.13-2           The Computational Geometry Algorithms Library (CGAL) is a C++ library that aim

https://www.cgal.org

Many thanks in advance.

**Comment by wangli28** [comment]
PR #5734

**Comment by JoelMontana** [comment]
The command "vcpkg upgrade cgal" doesn't update CGAL to 4.14. How can I update CGAL?

**Comment by lrineau** [comment]
I think you need to call `vcpkg update` before `vcpkg upgrade`. And as far as I know, `vcpkg upgrade` does not talk the package name as option. I think you can upgrade one package by using: `vcpkg install cgal` (and it will install the update if needed).

**Comment by JoelMontana** [comment]
Thanks for your help. VCPKG installs the version 4.13-2. 
vcpkg remove cgal
vcpkg install cgal           (x64-windows)

**Comment by JoelMontana** [comment]
Unfortunately, an update to 4.14 doesn't work.

**Comment by lrineau** [comment]
Does not work, how so?

**Comment by JoelMontana** [comment]
I get this output. 
![vcpkg](https://user-images.githubusercontent.com/47979576/55738924-5ef7ca80-5a28-11e9-811e-bd0351cccfe3.png)

**Comment by lrineau** [comment]
Should not you call 'git pull' to get the refreshed version of the vcpkg repository?

**Comment by JoelMontana** [comment]
It works now. git pull helped. Thx again.
