### ISSUE TITLE
 [New port request] heimdal

### ISSUE THREAD

**Issue by Voskrese** [microsoft/vcpkg#5890]
https://github.com/heimdal/heimdal
Heimdal is an implementation of Kerberos 5 (and some more stuff)

**Building** Heimdal for **Windows**
https://github.com/heimdal/heimdal/blob/master/windows/README.md

**PreBuilt**
https://www.secure-endpoints.com/binaries/heimdal/Heimdal-AMD64-full-7-4-0-40.msi
Kerberos V (Heimdal)
Kerberos V for Windows (x86_64) 
https://sourceforge.net/projects/heimdal-win/files/

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
