### ISSUE TITLE
 [New port request] MIT Kerberos

### ISSUE THREAD

**Issue by Voskrese** [microsoft/vcpkg#5892]
https://github.com/krb5/krb5

MIT Kerberos for Windows
https://github.com/krb5/krb5/tree/master/src/windows

MIT Kerberos for Windows 4.1
https://web.mit.edu/kerberos/dist/
https://web.mit.edu/kerberos/dist/kfw/4.1/kfw-4.1-amd64.msi
https://web.mit.edu/kerberos/dist/kfw/4.1/kfw-4.1-src.zip

**Comment by SeanFarrow** [comment]
Is this now available? It's something I'm looking for.

**Comment by sharadhr** [comment]
I was about to add a new port request when I noticed this. This has not been added, please re-open and reconsider adding.
