### ISSUE TITLE
zlib:x64-windows  Vcpkg version: 2018.11.23-nohash

### ISSUE THREAD

**Issue by DLoveS1314** [Microsoft/vcpkg#5896]

**Comment by vicroms** [comment]
Hi @DLoveS1314 

Please provide more details on this issue.

**Comment by tan-wei** [comment]
Just like #5949?

**Comment by tan-wei** [comment]
And #5959?

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
