### ISSUE TITLE
vcpkg generates wrong path for windows toolchain

### ISSUE THREAD

**Issue by aahmed-se** [microsoft/vcpkg#5897]
```
PS C:\Users\test\vcpkg> .\vcpkg integrate install
Applied user-wide integration for this vcpkg root.

All MSBuild C++ projects can now #include any installed libraries.
Linking will be handled automatically.
Installing new libraries will make them instantly available.

CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=C:/Users/test/vcpkg/scripts/buildsystems/vcpkg.cmake"
PS C:\Users\test\vcpkg> .\vcpkg integrate powershell
```

the slashes are forward when it should be backward for a windows env.

**Comment by arthur-tacca** [comment]
Have you actually tried using forward slashes when passing the `-DCMAKE_TOOLCHAIN_FILE` parameter? Did you get an error? What error did you get? It works fine for me - even with a combination of forward and backward slashes!

Many places that takes paths in Windows accept forward slashes too. This is especially true in CMake, where it's generally better to use forward slashes for consistency between different platforms. Unless you have a specific problem, this does not seem like a bug to me.

**Comment by aahmed-se** [comment]
yes I did try,  the build gave different result in cmake with forward and backward slashes.

**Comment by Cheney-W** [comment]
@aahmed-se 
Could you provide the different result and the corresponding DCMAKE_TOOLCHAIN_FILE value to us?

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you.
