### ISSUE TITLE
libpqxx upgrade to 6.3.3

### ISSUE THREAD

**Issue by cluidolt** [Microsoft/vcpkg#5899]
https://github.com/jtv/libpqxx/pull/67 is open in 6.0.0 so an upgrade of libpqxx is required.
 
include/pqxx/tablereader.hxx and include/pqxx/tablewriter.hxx have to be patched to compile using  Visual Studio 15.9.6

the attached patch-file contains the necessary patch for theses files (and the new version numbers)

[libpqxx-6.3.3.patch.zip](https://github.com/Microsoft/vcpkg/files/3030816/libpqxx-6.3.3.patch.zip)

**Comment by wangli28** [comment]
Hi @cluidolt,
Latest version is 6.4.3, you can update vcpkg and rebuild.
Thanks.
