### ISSUE TITLE
[New Port Request] libheif

### ISSUE THREAD

**Issue by luzpaz** [microsoft/vcpkg#5901]
libheif is a ISO/IEC 23008-12:2017 HEIF file format decoder and encoder.

http://www.libheif.org/  
https://github.com/strukturag/libheif/  
https://github.com/strukturag/libheif/releases/tag/v1.4.0

[![Packaging status](https://repology.org/badge/vertical-allrepos/libheif.svg)](https://repology.org/project/libheif/versions)

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
