### ISSUE TITLE
[New port request] libgpod

### ISSUE THREAD

**Issue by tan-wei** [microsoft/vcpkg#5908]
[https://github.com/fadingred/libgpod]() is a library which is used to read/write iPod database. Unfortunately, it uses `autotools` instead of `cmake` to build the library. I find that all the dependencies are ported in `vcpkg`, so I think it is not that hard for `cmake `master to port.
If I have enough time to writing a good `CMakeLists.txt` file, I would like to add it. :-P

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Port libgpod has been added to VCPKG, you can update vcpkg and build it.

**Comment by tan-wei** [comment]
Thanks very much!
