### ISSUE TITLE
[Qt5] Update to 5.12.3

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#5929]

**Comment by TheScarfix** [comment]
5.12.3 is planned for next Friday, I'll start a pull request then.

**Comment by Neumann-A** [comment]
@TheScarfix If your are updating please include the fix from commit https://github.com/Microsoft/vcpkg/pull/5543/commits/568bb77eb00af9c99139d5d6d55059d31a393cfa (if it is not in master by then).
