### ISSUE TITLE
arrow:x64-windows does not compile with VC2019

### ISSUE THREAD

**Issue by jeanga** [microsoft/vcpkg#5943]
Hello, 

I could not compile arrow:x64-windows with VC2019.

Here is an extract of the error messages:
`
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.20.27508\include\xstring(382): error C2027: use of undefined type 'std::basic_ostream<char,std::char_traits<char>>'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.20.27508\include\iosfwd(212): note: see declaration of 'std::basic_ostream<char,std::char_traits<char>>'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.20.27508\include\xstring(4238): note: see reference to function template instantiation 'std::basic_ostream<char,std::char_traits<char>> &std::_Insert_string<char,std::char_traits<char>,unsigned __int64>(std::basic_ostream<char,std::char_traits<char>> &,const _Elem *const ,const _SizeT)' being compiled
        with
        [
            _Elem=char,
            _SizeT=unsigned __int64
        ]`

And the full log file:
[install-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/3042737/install-x64-windows-dbg-out.log)

Thanks for any help !
Jean

**Comment by Voskrese** [comment]
try `[*]`
`install arrow[*]:x64-windows`

**Comment by philjdf** [comment]
Do we know Arrow builds on VS2019 outside of vcpkg? It seems unlikely that your error is related to an issue with the port itself. I have a pending PR to move to Arrow 0.13 (the latest release), maybe that will fix it.

**Comment by jaredburkeen** [comment]
I'm getting the same compiler error when attempting to compile some non-arrow software, I'm guessing we may need to wait on Microsoft to patch this before upgrading our build system.

```
[251/581] Compiling CECppEssentials\test\Util_test.cpp
Util_test.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.20.27508\include\xstring(382): error C2027: use of undefined type 'std::basic_ostream<char,std::char_traits<char>>'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.20.27508\include\iosfwd(212): note: see declaration of 'std::basic_ostream<char,std::char_traits<char>>'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.20.27508\include\xstring(4238): note: see reference to function template instantiation 'std::basic_ostream<char,std::char_traits<char>> &std::_Insert_string<char,std::char_traits<char>,unsigned __int64>(std::basic_ostream<char,std::char_traits<char>> &,const _Elem *const ,const _SizeT)' being compiled
        with
        [
            _Elem=char,
            _SizeT=unsigned __int64
        ]
```

**Comment by jaredburkeen** [comment]
I installed the latest version 16.0.1 (released today) and the issue persists.
I reported the issue to Microsoft:
https://developercommunity.visualstudio.com/content/problem/525532/visual-studio-2019-compilation-issue.html

**Comment by Rastaban** [comment]
Arrow is probably missing an `#include <sstream>`.

**Comment by GPSnoopy** [comment]
I've been compiling Arrow 0.14 fine with VS2019 using this PR #7211.

**Comment by PhoebeHui** [comment]
@jeanga, I can't repro this issue with latest source and VS2019 16.6.0, it should be fixed now. Does it still e a problem for you?

**Comment by PhoebeHui** [comment]
Please reopen this issue if it still be a problem for you.
