### ISSUE TITLE
Unable to install libraw on a vcpkg root contained in an exFAT drive

### ISSUE THREAD

**Issue by traversaro** [microsoft/vcpkg#5951]
With the vcpkg commit https://github.com/Microsoft/vcpkg/commit/e33ffb6f905fb6c7446003ce15028bc1f5606cf7 with Visual Studio 2017 on Windows Version 1709 OS Build 16299.192, if I try to install libraw in a vcpkg root that is contained in an `exFAT` driver, I get the following error: 
~~~
PS D:\superinstaller\vcpkg> .\vcpkg.exe install libraw:x64-windows
The following packages will be built and installed:
    libraw[core]:x64-windows
Starting package 1/1: libraw:x64-windows
Building package libraw[core]:x64-windows...
-- Using cached D:/superinstaller/vcpkg/downloads/LibRaw-LibRaw-0.19.0.tar.gz
-- Using source at D:/superinstaller/vcpkg/buildtrees/libraw/src/0.19.0-172926edff
-- Using cached D:/superinstaller/vcpkg/downloads/LibRaw-cmake-a71f3b83ee3dccd7be32f9a2f410df4d9bdbde0a
-- Extracting source D:/superinstaller/vcpkg/downloads/LibRaw-cmake-a71f3b83ee3dccd7be32f9a2f410df4d9bdbde0a
CMake Error at D:/superinstaller/vcpkg/scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;-E;tar;xjf;D:/superinstaller/vcpkg/downloads/LibRaw-cmake-a71f3b83ee3dccd7be32f9a2f410df4d9bdbde0a
    Working Directory: D:/superinstaller/vcpkg/buildtrees/libraw/src
    Error code: 1
    See logs for more information:
      D:\superinstaller\vcpkg\buildtrees\libraw\extract-err.log

Call Stack (most recent call first):
  D:/superinstaller/vcpkg/scripts/cmake/vcpkg_extract_source_archive.cmake:43 (vcpkg_execute_required_process)
  D:/superinstaller/vcpkg/ports/libraw/portfile.cmake:19 (vcpkg_extract_source_archive)
  D:/superinstaller/vcpkg/scripts/ports.cmake:71 (include)


Error: Building package libraw:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libraw:x64-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.
PS D:\superinstaller\vcpkg>
~~~

The `D:\superinstaller\vcpkg\buildtrees\libraw\extract-err.log` log contains: 
~~~
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: D:/superinstaller/vcpkg/downloads/LibRaw-cmake-a71f3b83ee3dccd7be32f9a2f410df4d9bdbde0a
~~~

Several other ports work fine in the exFAT, so I guess there is something strange in CMake and in the libraw tarball. 
Related issues:
* https://phabricator.mitk.org/T24971 
* https://github.com/Microsoft/vcpkg/issues/1549

**Comment by traversaro** [comment]
I opened an issue on this in CMake : https://gitlab.kitware.com/cmake/cmake/issues/19132 .

**Comment by PhoebeHui** [comment]
@traversaro, thanks for report issue to cmake!

You can temporarily using an earlier version of cmake(v3.13.4) to avoid this issue.
However it may cause some ports that require a higher cmake version to fail to build.

Steps:
1.	Open vcpkg/scripts/vcpkgTools.xml.
2.	Modify all cmake version numbers in the paragraph <tool name="cmake" os="windows"> from 3.14.0 to 3.13.4.
3.	Rebuild needs port.

**Comment by JackBoosY** [comment]
Duplicate cmake issue: https://gitlab.kitware.com/cmake/cmake/issues/19102.

**Comment by traversaro** [comment]
Just to understand @JackBoosY , why this issue was closed? The workaround proposed by @PhoebeHui  (thanks!) is the definitive solution? In that case probably it would make sense to document it somewhere in vcpkg's docs.

**Comment by JackBoosY** [comment]
@traversaro  Sorry, this issue should be turned on before upgrading cmake to the fixed version.

**Comment by JackBoosY** [comment]
Hi @traversaro, thanks for reporting this issue.
I've upgrade the min cmake version to 3.17.2 in vcpkg, please update vcpkg and rebuild libraw.

Thanks.
