### ISSUE TITLE
vcpkg is not integrated in VS 2017 and 2019: No such file or directory

### ISSUE THREAD

**Issue by beckseba** [Microsoft/vcpkg#5956]
Hello,

I installed vcpkg in order to reach a simple Integration of some packages in visual Studio 2019. I followed the steps which were indicated in the README. Hence, I cloned the git Version and I used the command 'vcpkg integrate install'. I have tested the Integration with the two packages 'opencv' and 'zlib'. I use a x64 Windows maschine and yes, I installed the corresponding x64 Version of both packages. However, I have also tested the Integration with VS 2017 which also failed. I will be glad about each answer to this post.

Best Regards

**Comment by beckseba** [comment]
The packages are located in C:\Program Files\vcpkg\installed\x64-windows\include and as I already said I used the 'vcpck integrate install' comand to integrated the packages. I have also adapted the settings of the debugger in VS to the x64 machine. Furthermore, the linker and C/C++ properties of my test Project are attached now.

Thank you.

<img width="612" alt="CC++_General" src="https://user-images.githubusercontent.com/49301482/55701995-6d68c680-59d5-11e9-83e0-2a222ae33709.PNG">
<img width="614" alt="Linker_Input" src="https://user-images.githubusercontent.com/49301482/55702004-7194e400-59d5-11e9-868a-d1ccc5cdd7b9.PNG">
<img width="614" alt="Linker_General" src="https://user-images.githubusercontent.com/49301482/55702012-76599800-59d5-11e9-86c9-9fbcbd20bee3.PNG">

**Comment by degski** [comment]
@beckseba  `C:\Program Files\vcpkg\installed\x64-windows\include` is not the best choice to install `vcpkg` in, there will unavoidably be some tools that don't grok the space in the path. In theory all is good, in  practice it has been proven time after time that it can fail.

**Comment by beckseba** [comment]
Thank you for your response. Which folder do you recommend for using as installation path?

**Comment by degski** [comment]
Any, as long as it has no spaces in it. `d:\vcpkg\installed\x64-windows\include`, f.e., as I hope you don't stick everything on your c-drive.

**Comment by beckseba** [comment]
Okay, and now, your suggestion is to test it again using annother drive/path for vcpkg?

**Comment by degski** [comment]
I'm not saying this has anything to do with it, but for most of the users it [the integration] works fine. Just yesterday, after installing VS2019 in parallel with VS2017, I removed and thereafter re-installed the integration successfully [in both VS17/19], just saying. I would change the path in any event, only trouble can come from it without any benefit.

**Comment by beckseba** [comment]
I have reinstalled vcpkg directly to the c-drive and now it is working, even if I don't know why. Thank you for the support.

**Comment by degski** [comment]
@beckseba I think I tried to make it clear why this might not work, but failed apparently! I would suggest to in the future split your hard-disk up in  2 0r 3 partitions (google it) and then make a split between `system` and `data`.

**Comment by beckseba** [comment]
@degski  thank you very much, I will consider your suggestions in future.

**Comment by bashbers** [comment]
My issue was that I installed the wrong version of a package. So make sure you installed the right version, otherwise Intellisense will not autocomplete your package!

Eg: `vcpkg install sdl2:x64-windows`

**Comment by TheAifam5** [comment]
Ok, what about when I installed to `C:\vcpkg` and have same issue? 
And yes, I build vcpkg, integrated powershell and `vcpkg integrate install`

I have only VS2019 installed and `#include` does show any of installed packages.
