### ISSUE TITLE
Fails freeimage windows compilation - MSVC

### ISSUE THREAD

**Issue by zancos** [Microsoft/vcpkg#5962]
```
Package: freeimage:x86-windows
Vcpkg version: 2018.11.23-nohash
```

Using MSVC 2013
The dependent package are properly build.

**Comment by zancos** [comment]
Because `ogre` depends on `freeimage`, it is also failing.

**Comment by traversaro** [comment]
I guess this was fixed by https://github.com/Microsoft/vcpkg/pull/5969 , can you try with the latest master?

**Comment by LarryIII** [comment]
Thanks for your feedback. this issue was fixed in https://github.com/Microsoft/vcpkg/pull/5969, please try again.

**Comment by zancos** [comment]
Sorry, you are right. Wrong master checked out version from my side.
Please, close this issue, and sorry again.
