### ISSUE TITLE
install --head fails inside travis HTTP error while getting 

### ISSUE THREAD

**Issue by fradav** [microsoft/vcpkg#5966]
I'm note sure it's a problem with vcpkg or travis but :

```
$ ./vcpkg install eigen3 --head
The following packages will be built and installed:
    eigen3[core]:x64-linux (from HEAD)
Starting package 1/1: eigen3:x64-linux
Building package eigen3[core]:x64-linux from HEAD... 
-- Downloading https://api.github.com/repos/eigenteam/eigen-git-mirror/git/refs/heads/master...
-- Downloading https://api.github.com/repos/eigenteam/eigen-git-mirror/git/refs/heads/master... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:172 (message):
      
      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:149 (vcpkg_download_distfile)
  ports/eigen3/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:71 (include)


Error: Building package eigen3:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: eigen3:x64-linux
  Vcpkg version: 2018.11.23-unknownhash-external
```

**Comment by fradav** [comment]
Somehow it has been solved, I don't know what changed.

**Comment by fradav** [comment]
Talked too soon, it failed on my latest build. I've still no idea what's going on.

**Comment by wangli28** [comment]
Hi @fradav, thanks for posting this issue.
I can't reproduce this issue locally, does the issue persist? can you try vcpkg latest revision?

vwangli@vwangli003:~/Lily/vcpkg$ ./vcpkg install eigen3 --head
The following packages will be built and installed:
    eigen3[core]:x64-linux (from HEAD)
Starting package 1/1: eigen3:x64-linux
Building package eigen3[core]:x64-linux from HEAD...
-- Downloading https://api.github.com/repos/eigenteam/eigen-git-mirror/git/refs/heads/master...
-- Skipping hash check for /home/vwangli/Lily/vcpkg/downloads/temp/eigenteam-eigen-git-mirror-master.tar.gz.version.
-- Downloading https://github.com/eigenteam/eigen-git-mirror/archive/master.tar.gz...
-- Skipping hash check for /home/vwangli/Lily/vcpkg/downloads/temp/eigenteam-eigen-git-mirror-master.tar.gz.
-- Extracting source /home/vwangli/Lily/vcpkg/downloads/eigenteam-eigen-git-mirror-master.tar.gz
-- Using source at /home/vwangli/Lily/vcpkg/buildtrees/eigen3/src/head/master-277c07f1d2
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package eigen3[core]:x64-linux... done
Installing package eigen3[core]:x64-linux...
Installing package eigen3[core]:x64-linux... done
Elapsed time for package eigen3:x64-linux: 7.889 s

Total elapsed time: 7.889 s

The package eigen3:x64-linux provides CMake targets:
    find_package(Eigen3 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Eigen3::Eigen)

**Comment by fradav** [comment]
No, you can close the issue.
