### ISSUE TITLE
Make lide265 installable via vcpkg 

### ISSUE THREAD

**Issue by al-sabr** [microsoft/vcpkg#5973]
Hi everyone,

I would like to ask if there is the possibility to be able to install **libde265** with the command line utility vcpkg which makes package installation really simple.

Project repo : https://github.com/strukturag/libde265

Feature request : https://github.com/strukturag/libde265/issues/203

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
