### ISSUE TITLE
find_boost 1.69 

### ISSUE THREAD

**Issue by jcsantamaria** [microsoft/vcpkg#5975]
Building a project that depends on boost does not work because cmake is not able to find boost.

The error is:
CMake Warning at C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/FindBoost.cmake:847 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/FindBoost.cmake:959 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  C:/Sandbox/GitHub/vcpkg/scripts/buildsystems/vcpkg.cmake:197 (_find_package)
  ompl/CMakeModules/FindPython.cmake:179 (find_package)
  CMakeLists.txt:83 (find_boost_python)

**Comment by wangli28** [comment]
Hi @jcsantamaria, can you provide more information for this issue? How did you build this project?

**Comment by jcsantamaria** [comment]
I am manually executing the steps described here: [ompl](https://bitbucket.org/ompl/ompl/src/tip/.appveyor.yml?fileviewer=file-view-default)

In a powershell, I prepare the context:
`
./vcpkg env --triplet x64-windows
set platform=x64
set CTEST_OUTPUT_ON_FAILURE=1
set CMAKE_TOOLCHAIN_FILE=-DCMAKE_TOOLCHAIN_FILE="c:\Sandbox\GitHub\vcpkg\scripts\buildsystems\vcpkg.cmake"
set CMAKE_GENERATOR=-G"Visual Studio 15 2017 Win64"
set VCPKG_ARCH=x64-windows
`

Then, created a build folder and executed:
`cmake %CMAKE_GENERATOR% -DCMAKE_BUILD_TYPE=%configuration% %CMAKE_TOOLCHAIN_FILE% -DOMPL_REGISTRATION=OFF ..`

These are the versions of tools reported by cmake:
`-- The CXX compiler identification is MSVC 19.16.27030.1
-- The C compiler identification is MSVC 19.16.27030.1
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Building Release
-- Found Eigen3: C:/Sandbox/GitHub/vcpkg/installed/x64-windows/include/eigen3 (Required is at least version "2.91.0") 
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Could NOT find FLANN (missing: FLANN_LIBRARIES FLANN_INCLUDE_DIRS) 
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Could NOT find SPOT (missing: SPOT_LIBRARIES SPOT_INCLUDE_DIRS) 
-- Found PY_numpy: C:\ProgramData\Anaconda3\lib\site-packages\numpy\__init__.py  
-- Could NOT find PY_pyplusplus (missing: PY_PYPLUSPLUS) 
-- Could NOT find PY_pygccxml (missing: PY_PYGCCXML) 
-- Could NOT find castxml (missing: CASTXML) 
`

But the 

> New Boost version may have incorrect or missing dependencies and imported

 message appears multiple times:
`C:\Sandbox\ompl-1.4.1\build>cmake %CMAKE_GENERATOR% -DCMAKE_BUILD_TYPE=%configuration% %CMAKE_TOOLCHAIN_FILE% -DOMPL_REGISTRATION=OFF ..
-- Building Release
CMake Warning at C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/FindBoost.cmake:847 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/FindBoost.cmake:959 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  C:/Sandbox/GitHub/vcpkg/scripts/buildsystems/vcpkg.cmake:197 (_find_package)
  CMakeLists.txt:62 (find_package)
CMake Warning at C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/FindBoost.cmake:847 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/FindBoost.cmake:959 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  C:/Sandbox/GitHub/vcpkg/scripts/buildsystems/vcpkg.cmake:197 (_find_package)
  CMakeLists.txt:62 (find_package)
CMake Warning at C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/FindBoost.cmake:847 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/FindBoost.cmake:959 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  C:/Sandbox/GitHub/vcpkg/scripts/buildsystems/vcpkg.cmake:197 (_find_package)
  CMakeLists.txt:62 (find_package)
`

I hope this helps.

**Comment by jcsantamaria** [comment]
I kept digging into this.

The build is using the installed version of CMake (cmake-3.12).

The FindBoost.cmake in the Modules folder of the CMake tool has these lines (starting at 846):
`    if(NOT Boost_VERSION VERSION_LESS 106900)
      message(WARNING "New Boost version may have incorrect or missing dependencies and imported targets")
    endif()
`

So, it appears that the accompanying CMake tool to Visual Studio 2017 (version 15.9.11) is not configured to use boost 1.69 or above.

It appears that support for boost 1.69 was added to CMake 3.13: [https://gitlab.kitware.com/cmake/cmake/merge_requests/2522](https://gitlab.kitware.com/cmake/cmake/merge_requests/2522)

**Comment by NancyLi1013** [comment]
Hi @jcsantamaria, thanks for posting this issue. Could you update CMake to the latest version ( It is 3.14.0 now in vcpkg ) and try it again?

**Comment by NancyLi1013** [comment]
Please feel free to reopen it if this is still a problem for you.

**Comment by patrikhuber** [comment]
Hi @NancyLi1013, I'm getting this warning again with the latest VS 2022, its integrated CMake (3.24), and the latest Boost from vcpkg (1.80):

```
CMake Warning at C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.24/Modules/FindBoost.cmake:1384 (message):
1> [CMake] New Boost version may have incorrect or missing dependencies and imported targets
```

**Comment by dg0yt** [comment]
This is a normal *warning* when using a version of boost newer than the one requesed with `find_package`.
*It is not an error by itself*, but can be a useful piece of information in the case of unexpected errors.

**Comment by patrikhuber** [comment]
To be honest I find it a rather annoying and (in most cases) unnecessary warning. It completely clutters up the terminal output of CMake - it's not just the above two lines but an 11-line warning with call stack. In normal operation, this warning is unnecessary and just clutter, and it actually hides potentially more important things in the CMake configure output. At the minimum, there should be an option to suppress this warning, or, it shouldn't be enabled by default, there should be an opt-in debug-logging switch for this.

**Comment by dg0yt** [comment]
This warning is from the `FindBoost.cmake` module in CMake, not from vcpkg. 
https://github.com/Kitware/CMake/blob/48c69eeafe5e480b5baa0c6766d4d2e3c7f5a4ad/Modules/FindBoost.cmake#L1383-L1385

The variable to disable this warning exists since CMake 3.20
https://cmake.org/cmake/help/latest/module/FindBoost.html

**Comment by patrikhuber** [comment]
That's great, thank you very much @dg0yt! (I still wish the warning was opt-in as opposed to opt-out, but the variable is good enough.)

**Comment by dg0yt** [comment]
I also didn't know about the variable until now. Sometimes it is annoying to have these stack traces in vcpkg logs because they make it more difficult to see the actual errors. So I really wonder if it would be appropriate for vcpkg to print a clear `STATUS` message (stdout, no call stack) in instead of the `WARNING` (stderr, callstack) when the variable is unset. This could be implemented in a wrapper. It is vcpkg's responsibility to take care of boost port dependencies.
