### ISSUE TITLE
Error: Building package capnproto:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by sandeshghimire** [Microsoft/vcpkg#5977]
capnproto fails to build 
C:\Repo\vcpkg>vcpkg.exe install capnproto
The following packages will be built and installed:
    capnproto[core]:x86-windows
Starting package 1/1: capnproto:x86-windows
Building package capnproto[core]:x86-windows...
Building DLLs not supported. Building static instead.
-- Using cached C:/Repo/vcpkg/downloads/capnproto-capnproto-v0.7.0.tar.gz
-- Using source at C:/Repo/vcpkg/buildtrees/capnproto/src/v0.7.0-b4a52715c4
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:202 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No;/m
    Working Directory: C:/Repo/vcpkg/buildtrees/capnproto/x86-windows-dbg
    See logs for more information:
      C:\Repo\vcpkg\buildtrees\capnproto\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/capnproto/portfile.cmake:27 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package capnproto:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: capnproto:x86-windows
  Vcpkg version: 2018.11.23-nohash

**Comment by PhoebeHui** [comment]
@sandeshghimire, thanks for posting this issue!

I installed capnproto:x86-windows successfully with VS2017 15.9.7 and latest VCPKG revision.
Could you attach the failure log: C:\Repo\vcpkg\buildtrees\capnproto\install-x86-windows-dbg-out.log?

**Comment by sandeshghimire** [comment]
The problem is fixed, it was a symbolic link problem on windows, after switching to development mode the problem went away

**Comment by PhoebeHui** [comment]
Great, thanks for your feedback!
