### ISSUE TITLE
question of .vcxproj

### ISSUE THREAD

**Issue by xspeed1989** [microsoft/vcpkg#5978]
can i set a search order of VcpkgTriplet like this

    <VcpkgTriplet Condition="'$(Platform)'=='Win32'">x86-windows</VcpkgTriplet>
    <VcpkgTriplet Condition="'$(Platform)'=='x64'">x64-windows,x64-windows-static</VcpkgTriplet>

or i can set some lib  that compiled with  x64-windows-static  and another is x64-windows

**Comment by Cheney-W** [comment]
@xspeed1989 
You can't set the search order of VcpkgTriplet, \<VcpkgTriplet Condition="'$(Platform)'=='x64'"\>x64-windows,x64-windows-static\</VcpkgTriplet\> is incorrect, this will make all of x64-windows and x64-windows-static include and lib are not available. With the set of VcpkgTriplet, x64-static and x64-dynamic can only exist one at a time.

**Comment by PhoebeHui** [comment]
@xspeed1989, please reopen this if it still be an problem for you.
