### ISSUE TITLE
vcpkg is not adding the right linked ressources's path when project configured with CMake

### ISSUE THREAD

**Issue by gdeverlant** [microsoft/vcpkg#5980]
As you can see in the screenshot there is a mistake in 2 libraries:

![image](https://user-images.githubusercontent.com/26530975/55671060-1e634a00-588c-11e9-960d-680ed8cefec1.png)

The correct path should be :

````
C:\vcpkg\packages\pcre_x86-windows\debug\lib\pcred.lib
C:\vcpkg\packages\zlib_x86-windows\debug\lib\zlibd.lib
````

demo project : 
[multiverses-bug.zip](https://github.com/Microsoft/vcpkg/files/3050623/multiverses-bug.zip)

**Comment by NancyLi1013** [comment]
Hi @gdeverlant, thanks for posting this issue. I try to add your demo project to Visual Studio on my local. I can build it successfully. It seems that there is no need to add these libs to **Additional Dependencies**. Could you please help provide the steps to reproduce? BTW, I doubt why pcred.lib and zlibd.lib will be listed in poco packages diretory?

**Comment by NancyLi1013** [comment]
Please feel free to reopen it if this is still a problem for you.
