### ISSUE TITLE
SDL2: Log output to system console on Windows is disabled

### ISSUE THREAD

**Issue by Zingam** [microsoft/vcpkg#5984]
SDL_Log does not output to the Windows console in a debug configuration

**Comment by NancyLi1013** [comment]
Hi @Zingam, thanks for posting this issue. Could you please help provide more info about this issue?
Such as the screenshot, the detail output info or the steps to reproduce?

**Comment by NancyLi1013** [comment]
Please feel free to reopen it if this is still a problem for you.
