### ISSUE TITLE
Error installing boost

### ISSUE THREAD

**Issue by piusogs** [microsoft/vcpkg#5988]
Installing boost is failing on Ubuntu 18.04.2.
The process failed while trying to install boost-test,

**Comment by wangli28** [comment]
Hi @piusogs, thanks for posting this issue.
I can't reproduce this issue locally, does the issue persist? can you try vcpkg latest revision?

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
