### ISSUE TITLE
Error of the installation gdal library

### ISSUE THREAD

**Issue by VladimirBalun** [microsoft/vcpkg#5996]
Hello everyone, I tried install gdal library with vcpkg, but I got the following error only on 17 package(first 16 packages were installed successfully):

    Installing package netcdf-c[core]:x86-windows... done
    Elapsed time for package netcdf-c:x86-windows: 2.262 min
    Starting package 17/17: gdal:x86-windows
    Building package gdal[core]:x86-windows...
    -- Downloading http://download.osgeo.org/gdal/2.4.0/gdal240.zip...
    -- Extracting source D:/Libraries/vcpkg/downloads/gdal240.zip
    -- Applying patch D:/Libraries/vcpkg/ports/gdal/0001-Fix-debug-crt-flags.patch
    -- Applying patch D:/Libraries/vcpkg/ports/gdal/0002-Fix-static-build.patch
    -- Extracting source D:/Libraries/vcpkg/downloads/gdal240.zip
    -- Applying patch D:/Libraries/vcpkg/ports/gdal/0001-Fix-debug-crt-flags.patch
    -- Applying patch D:/Libraries/vcpkg/ports/gdal/0002-Fix-static-build.patch
    -- Building x86-windows-rel
    -- Building x86-windows-rel done
    -- Building x86-windows-dbg
    -- Building x86-windows-dbg done
    -- Packaging x86-windows
    CMake Error at ports/gdal/portfile.cmake:274 (file):
      file must be called with at least two arguments.
    Call Stack (most recent call first):
      scripts/ports.cmake:71 (include)

    Error: Building package gdal:x86-windows failed with: BUILD_FAILED
    Please ensure you're using the latest portfiles with `.\vcpkg update`, then submit an issue at https://github.com/Microsoft/vcpkg/issues including:
      Package: gdal:x86-windows
      Vcpkg version: 2018.11.23-nohash

I ran installation of the gdal library with command:

    vcpkg install gdal

My system properties:
* OS: Windows 10 (x64)
* VS 2017 (Version 15.9.6)
* vcpkg (Version 2018.11.23-nohash)

**Comment by wangli28** [comment]
Hi @VladimirBalun, thanks for posting this issue.
I can't reproduce this issue locally, does the issue persist? can you try vcpkg latest revision?

PS E:\Lily\vcpkg> .\vcpkg.exe install gdal
The following packages will be built and installed:
    gdal[core]:x86-windows
  * geos[core]:x86-windows
  * libpq[core]:x86-windows
  * libwebp[core]:x86-windows
  * opengl[core]:x86-windows
  * openjpeg[core]:x86-windows
  * proj[core]:x86-windows
......
Starting package 7/7: gdal:x86-windows
Building package gdal[core]:x86-windows...
-- Downloading http://download.osgeo.org/gdal/2.4.1/gdal241.zip...
-- Extracting source E:/Lily/vcpkg/downloads/gdal241.zip
-- Applying patch E:/Lily/vcpkg/ports/gdal/0001-Fix-debug-crt-flags.patch
-- Applying patch E:/Lily/vcpkg/ports/gdal/0003-Fix-std-fabs.patch
-- Extracting source E:/Lily/vcpkg/downloads/gdal241.zip
-- Applying patch E:/Lily/vcpkg/ports/gdal/0001-Fix-debug-crt-flags.patch
-- Applying patch E:/Lily/vcpkg/ports/gdal/0003-Fix-std-fabs.patch
-- Building x86-windows-rel
-- Building x86-windows-rel done
-- Building x86-windows-dbg
-- Building x86-windows-dbg done
-- Packaging x86-windows
-- Performing post-build validation
-- Performing post-build validation done
Building package gdal[core]:x86-windows... done
Installing package gdal[core]:x86-windows...
Installing package gdal[core]:x86-windows... done
Elapsed time for package gdal:x86-windows: 22.51 min

Total elapsed time: 27.07 min

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
