### ISSUE TITLE
Provide CMake imported targets instead of variables

### ISSUE THREAD

**Issue by Orphis** [Microsoft/vcpkg#6]
In modern CMake, you are not supposed to give the user a list of variables but an imported target you use directly with "target_link_libraries".
It's a bit sad to see the example requiring CMake 3.0 but using patterns from CMake 2.6 dating from the CMake stone age.

https://cmake.org/cmake/help/v3.6/command/add_library.html#imported-libraries

**Comment by ras0219-msft** [comment]
Could you be more specific about what list of variables we're providing?

**Comment by Orphis** [comment]
`find_library(CPPREST_LIBRARY cpprest_2_8)
find_path(CPPREST_INCLUDE_DIR cpprest/version.h)

include_directories(${CPPREST_INCLUDE_DIR})
link_libraries(${CPPREST_LIBRARY})`

You should be providing instead something like "find_package(vcpkg::cpprest_2_8 REQUIRED)" and then have people link against the target "vcpkg::cpprest_2_8".
You can generate files for find_package directly that create the imported targets for you.
The pkg-config CMake support upstream has been doing that.

**Comment by ras0219-msft** [comment]
I've filed an issue against cpprestsdk. Thanks for bringing this up!

**Comment by Orphis** [comment]
Well, that's not specific to cpprestsdk, it's first your example that isn't great, and then you don't provide a good mechanism to link the libs provided by vcpkg to the targets in our projects.

**Comment by ras0219-msft** [comment]
We do support all the normal CMake integration (`find_package` and so forth) for packages that provide it. For example, `find_package(zlib)` should work correctly.

Is there a package that externally supports cmake but is not being packaged correctly?

**Comment by Orphis** [comment]
Well, you should then really use find_package() instead in your example and have the cpprestsdk either provide the imported targets or patch it in your ports file to add support for them.

For Zlib that would be:
>find_package(ZLIB REQUIRED)
>target_link_libraries(MyExecutable PRIVATE ZLIB::ZLIB)

Don't forget the PUBLIC / PRIVATE after target_link_libraries either in examples.
Don't use link_libraries, usage is not recommended as per CMake's documentation. You don't want everything to link against it, just your executable or library, and that should be explicit.

**Comment by stoperro** [comment]
It took me a while to learn why find_package(cpprestsdk REQUIRED) doesn't work. Could somehow vcpkg provide warn if someone does it like that that this less standard way of using libraries is needed? I thought my installation was broken. I see now in Readme.md there is:

> If you're using a library that does not provide CMake integration, you will need to explicitly search for the files and add them yourself using find_path() and find_library().

but I only understand it now when I found this issue... others may have a hard time to find it too.
