### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by alcroito** [microsoft/vcpkg#6003]
Hi,
Any plans to add iOS support, now that CMake /somewhat/ supports iOS?

https://cmake.org/cmake/help/v3.14/release/3.14.html#platforms

**Comment by jasjuang** [comment]
would like to have iOS support at some point in the future too

**Comment by alcroito** [comment]
A WIP initial implementation that I did can be found at https://github.com/Microsoft/vcpkg/pull/6275 if anybody is interested to test it.
