### ISSUE TITLE
Upgrade to Cuda 10

### ISSUE THREAD

**Issue by Fleischner** [Microsoft/vcpkg#6004]
Would be nice to get cuda 10.
https://devblogs.microsoft.com/cppblog/cuda-10-1-available-now-with-support-for-latest-microsoft-visual-studio-2019-versions/

Is there a port that blocks upgrade?

**Comment by cenit** [comment]
if you have cuda 10 installed, the portfile will happily detect it. Unfortunately the portfile is not able to install by itself CUDA, it just checks and verify the installation. Current portfile works ok with cuda10 and cuda10.1
