### ISSUE TITLE
 .\bootstrap-vcpkg.bat Error: can't building vcpkg.exe

### ISSUE THREAD

**Issue by Checkmate986212** [Microsoft/vcpkg#6009]
I use the VS2019.
When I bootstrap vcpkg, I get an error from the compiler.

MSBUILD : error MSB1009: 项目文件不存在。
C:\Windows\System32\vcpkg\scripts\bootstrap.ps1 : Building vcpkg.exe failed. Please ensure you have installed Visual Studio with the Desktop C++ workload and the Windows SDK for Desktop C++.

I have installed all the possible Windows SDK in VS installer
![image](https://user-images.githubusercontent.com/43061147/55785947-e8b99d80-5ae5-11e9-9b88-5df69cdec0d2.png)

**Comment by degski** [comment]
You **should not/can not** install `vcpkg` in `C:\Windows\System32\`. Yuo will never ever have enough privileges to use a build-system. Install `vcpkg` to the root of any drive, but preferably not on `C:`. Also, don't put it in a path with spaces in it.

**Comment by Checkmate986212** [comment]
> You **should not/can not** install `vcpkg` in `C:\Windows\System32\`. You will never ever have enough privileges to use a build-system. Install `vcpkg` to the root of any drive, but preferably not on `C:`. Also, don't put it in a path with spaces in it.

Thank you very much, now I can install vcpkg
