### ISSUE TITLE
How to fix libCGAL-vc140-mt-4.14-l-900.lib Link error ( VCPKG CGAL update 4.14 )

### ISSUE THREAD

**Issue by JoelMontana** [microsoft/vcpkg#6013]
I'm getting the error message "Linker Tools Error LNK1104" can't find libCGAL-vc140-mt-4.14-I-900.lib"

I'm using VCPKG with Visual Studio and linker flag /MD or /MDd. The same setup worked with CGAL 4.13. The error came after the update to 4.14 with VCPKG.

Even a small new CGAL program will not be translated. I tried debug/release mode with x64.

**Comment by Neumann-A** [comment]
Question one:
Do you use CMake or the Visual Studio integration?

Question two:
Which triplet are you using? x64-windows? Is cgal:x64-windows installed (and not maybe the x86-windows triplet)?

**Comment by JoelMontana** [comment]
I use the Visual Studio integration. 

I installed cgal:x64-windows 4.14-1 and cgal:x86-windows 4.14-1 and boost:x64 /booxt:x86
The error message is: cannot open source file "CGAL/compiler_config.h" config.h

**Comment by mengfan1102** [comment]
Vcpkg will install CGAL as "header only".

I found that I have to add the `CGAL_HEADER_ONLY` preprocessor definition in Visual Studio: "Properties  - C/C++ - Preprocessor", then it should be built correctly.

**Comment by NancyLi1013** [comment]
Hi @JoelMontana, thanks for posting this issue. Does this issue still exist on your machine now?

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
