### ISSUE TITLE
Renaming of debug libraries through CMAKE_DEBUG_POSTFIX or other means

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#6014]
as discussed in #5543

Original title:
Usage of CMAKE_DEBUG_POSTFIX within ports (find_package not working for some debug libraries)

`CMAKE_DEBUG_POSTFIX` cannot be set to "d" or the library cannot be renamed to include the "d" if there already exists an established old `find_package` handling within cmake for the library in question.

__Why?__
It currently breaks all downstream usages of `find_package` for that library/port. Be it internal in vcpkg or external. `find_package` will only be able to resolve the release libraries in these cases and thus links against those even in a debug build. 

__When can this be ignored?__
The port comes with a config.cmake or the `find_package` command integrated within CMake defines targets or knows how to differentiate between release/debug libraries. 

__How can this be solved?__
Revert renaming of all afflicted libraries within vcpkg and solve all caused regressions. 
(see #5543 for a list of ports to check)
alternative: find another way to handle it (probably have a solution for that)

**Comment by Neumann-A** [comment]
After thinking about this issue, I came up wie the following priority list:
1. Do whatever the package maintainer intended to do. If the package does not add the extra "d" vcpkg should also not do it. Reason: That is probably what downstream targets expect and would make sure that `find_library `and `find_package` calls within those downstream targets work as intended
2. Do whatever CMake expects for `find_package` to work as expected. In most cases this is also not adding an extra "d"
3. If 1) and 2) are in conflict with each other (like in PCRE) find a workaround within vcpkg. In the workaround find_package must do whatever most downstream targets would expect. If downstream targets are not in consent about it -> force one possible solution. Since vcpkg does not require the "d" to differentiate between release and debug libraries and `find_package` will do the right thing without the extra "d" the "d" should not be added to the library name by vcpkg. (Lazy resoultion because vcpkg can simply use `find_package` without adding any additional code.)

**Comment by Neumann-A** [comment]
related: https://github.com/Microsoft/vcpkg/pull/5543#issuecomment-481592472

**Comment by Neumann-A** [comment]
closed by current idea in #5543 which uses a override in find_library to also search for common debug library suffixes.

**Comment by PhoebeHui** [comment]
@Neumann-A, thanks for bringing up this!

Related documentation added to vcpkg, see https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-rename-binaries-outside-the-names-given-by-upstream

Please reopen this if it's still be an issue for you.
