### ISSUE TITLE
strtk does not seem to depend on "boost" but only on "boost-random"

### ISSUE THREAD

**Issue by jeanga** [Microsoft/vcpkg#6023]
As the title says, strtk only includes <boost/random.hpp> which makes a whole lot less than depending on "boost".

HTH,
Jean

**Comment by wangli28** [comment]
Hi @jeanga,
I installed strtk, checked its source code. And I found that it depends on the librarys not just random, but also convert and regex.
Thanks.

**Comment by jeanga** [comment]
Hum... This is embarassing... I don't know how I did not see those...
There is also some boost spririt in it... (which probably means all of boost comes in...)
strtk will be "no go" for me with so many boost depends.... :-(
