### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by illidan1980** [microsoft/vcpkg#6026]
Building vcpkg.exe ...

  pch.cpp
  archives.cpp
  checks.cpp
  chrono.cpp
  cofffilereader.cpp
  downloads.cpp
  enums.cpp
  files.cpp
  hash.cpp
  machinetype.cpp
  strings.cpp
  stringview.cpp
  system.cpp
  system.print.cpp
  binaryparagraph.cpp
  build.cpp
  commands.autocomplete.cpp
  commands.buildexternal.cpp
  commands.cache.cpp
  commands.ci.cpp
  commands.contact.cpp
  commands.cpp
f:\vcpkg\toolsrc\src\vcpkg\build.cpp(517): error C2065: 'port_file': undeclared identifier [F:\vcpkg\toolsrc\vcpkglib\v
cpkglib.vcxproj]
  commands.create.cpp
  commands.dependinfo.cpp
  commands.edit.cpp
  commands.env.cpp
  commands.exportifw.cpp
  commands.import.cpp
  commands.integrate.cpp
  commands.list.cpp
  commands.owns.cpp
  commands.portsdiff.cpp
  commands.search.cpp
  commands.upgrade.cpp
  commands.version.cpp
  commands.xvsinstances.cpp
  dependencies.cpp
  export.cpp
  globalstate.cpp
  help.cpp
  input.cpp
  install.cpp
  metrics.cpp
  packagespec.cpp
  packagespecparseresult.cpp
  paragraphparseresult.cpp
  paragraphs.cpp
  parse.cpp
f:\vcpkg\toolsrc\src\vcpkg\install.cpp(229): error C2039: 'println': is not a member of 'vcpkg::System' [F:\vcpkg\tools
rc\vcpkglib\vcpkglib.vcxproj]
  f:\vcpkg\toolsrc\include\vcpkg\base\system.h(8): note: see declaration of 'vcpkg::System'
f:\vcpkg\toolsrc\src\vcpkg\install.cpp(229): error C3861: 'println': identifier not found [F:\vcpkg\toolsrc\vcpkglib\vc
pkglib.vcxproj]
f:\vcpkg\toolsrc\src\vcpkg\install.cpp(248): error C2039: 'println': is not a member of 'vcpkg::System' [F:\vcpkg\tools
rc\vcpkglib\vcpkglib.vcxproj]
  f:\vcpkg\toolsrc\include\vcpkg\base\system.h(8): note: see declaration of 'vcpkg::System'
f:\vcpkg\toolsrc\src\vcpkg\install.cpp(248): error C3861: 'println': identifier not found [F:\vcpkg\toolsrc\vcpkglib\vc
pkglib.vcxproj]
  postbuildlint.buildtype.cpp
  postbuildlint.cpp
  remove.cpp
  sourceparagraph.cpp
  statusparagraph.cpp
  statusparagraphs.cpp
  tools.cpp
  triplet.cpp
  update.cpp
  userconfig.cpp
  vcpkgcmdarguments.cpp
  vcpkglib.cpp
  vcpkgpaths.cpp
  versiont.cpp
  visualstudio.cpp
F:\vcpkg\scripts\bootstrap.ps1 : Building vcpkg.exe failed. Please ensure you have installed Visual Studio with the
Desktop C++ workload and the Windows SDK for Desktop C++.
At line:1 char:4
+ & {& 'F:\vcpkg\scripts\bootstrap.ps1' }
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,bootstrap.ps1

I definitely have all the prereqs. This seems a legitimate build issue.

**Comment by coryan** [comment]
same here.

**Comment by Voskrese** [comment]
install `Windows SDK for Desktop C++` , install Windows SDK ))

**Comment by wangli28** [comment]
Hi @illidan1980, thank you for posting the issue, does the issue still occur?

**Comment by NancyLi1013** [comment]
Hi @illidan1980,  please install Visual Studio with `Windows SDK for Desktop C++` and then try to build it again. Please feel free to reopen this issue if this is still a problem for you.
