### ISSUE TITLE
Opus UWP build is not supported

### ISSUE THREAD

**Issue by gpchowdari** [microsoft/vcpkg#6039]
The following packages will be built and installed:
    opus[core]:arm-uwp
Starting package 1/1: opus:arm-uwp
Building package opus[core]:arm-uwp...
CMake Error at ports/opus/portfile.cmake:2 (message):
  UWP builds not supported
Call Stack (most recent call first):
  scripts/ports.cmake:71 (include)

Error: Building package opus:arm-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opus:arm-uwp
  Vcpkg version: 2018.11.23-nohash

**Comment by PhoebeHui** [comment]
@gpchowdari, currently Opus support UWP, related PR https://github.com/microsoft/vcpkg/pull/6007.

I tried, everything installed successfully.
The following packages will be built and installed:
    opus[core]:arm-uwp
Starting package 1/1: opus:arm-uwp
Building package opus[core]:arm-uwp...
-- Downloading https://github.com/xiph/opus/archive/e85ed7726db5d677c9c0677298ea0cb9c65bdd23.tar.gz...
-- Extracting source F:/VCPKG/src/downloads/xiph-opus-e85ed7726db5d677c9c0677298ea0cb9c65bdd23.tar.gz
-- Using source at F:/VCPKG/src/buildtrees/opus/src/b9c65bdd23-4dd2a46170
-- Configuring arm-uwp
-- Building arm-uwp-dbg
-- Building arm-uwp-rel
-- Installing: F:/VCPKG/src/packages/opus_arm-uwp/share/opus/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package opus[core]:arm-uwp... done
Installing package opus[core]:arm-uwp...
Installing package opus[core]:arm-uwp... done
Elapsed time for package opus:arm-uwp: 1.182 min

Total elapsed time: 1.182 min

The package opus:arm-uwp provides CMake targets:

    find_package(Opus CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Opus::opus)
