### ISSUE TITLE
cpprestsdk cannot find boost

### ISSUE THREAD

**Issue by yamcenutzer** [Microsoft/vcpkg#604]
trying to build cpprestsdk, but if fails to find boost (using vs2015)
## vcpkg list :
boost:x64-windows           1.63             Peer-reviewed portable C++ source libraries
bzip2:x64-windows           1.0.6            High-quality data compressor.
fmt:x64-windows             3.0.1-1          Formatting library for C++. It can be used as a s...
openssl:x64-windows         1.0.2k-1         OpenSSL is an open source project that provides a...
range-v3:x86-windows        20150729-vcpkg2  Range library for C++11/14/17.
rapidjson:x64-windows       1.0.2-1          A fast JSON parser/generator for C++ with both SA...
rapidxml:x86-windows        1.13             RapidXml is an attempt to create the fastest XML ...
spdlog:x64-windows          0.11.0           Very fast, header only, C++ logging library
zlib:x64-windows            1.2.11           A compression library
zlib:x64-windows-static     1.2.11           A compression library

## cpprestsdk error:

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;C:/robinmi/vcpkg/buildtrees/cpprestsdk/src/cpprestsdk-2.9.0/Release;-DBUILD_TESTS=O
FF;-DBUILD_SAMPLES=OFF;-DCPPREST_EXCLUDE_WEBSOCKETS=OFF;-DBUILD_SHARED_LIBS=ON;-DCMAKE_CXX_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc;-D
CMAKE_C_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_
PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_CXX_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Zi;-DCMAKE_C_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBU
G /Zi;-DCMAKE_SHARED_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF;-DCMAKE_EXE_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /
OPT:REF /OPT:ICF;-G;Visual Studio 14 2015 Win64;-DCMAKE_VERBOSE_MAKEFILE=ON;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_TOOLCHAIN_FILE=C:/robinmi/vcp
kg/triplets/x64-windows.cmake;-DCMAKE_PREFIX_PATH=C:/robinmi/vcpkg/installed/x64-windows;-DCMAKE_INSTALL_PREFIX=C:/robinmi/vcpkg/packages/cp
prestsdk_x64-windows
    Working Directory: C:/robinmi/vcpkg/buildtrees/cpprestsdk/x64-windows-rel
    See logs for more information:
      C:\robinmi\vcpkg\buildtrees\cpprestsdk\config-x64-windows-rel-out.log
      C:\robinmi\vcpkg\buildtrees\cpprestsdk\config-x64-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:88 (vcpkg_execute_required_process)
  ports/cpprestsdk/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:73 (include)

Error: building package cpprestsdk:x64-windows failed
Please ensure sure you're using the latest portfiles with `vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cpprestsdk:x64-windows
  Vcpkg version: 0.0.70-d776322d2a99aebff6147081e98fac434e6f6dc6

Additionally, attach any relevant sections from the log files above.

C:\robinmi\vcpkg>vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

C:\robinmi\vcpkg>git pull
Already up-to-date.

## config error log:

CMake Error at C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:1812 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.63.0

  Boost include path: C:/robinmi/vcpkg/installed/x64-windows/include

  Could not find the following Boost libraries:

          boost_regex
          boost_date_time

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMakeLists.txt:110 (find_package)

-- Setting msvc options
-- websocketpp not found, using the embedded version

**Comment by ras0219-msft** [comment]
Hi @yamcenutzer, could you confirm this is still occurring with the latest Vcpkg?

**Comment by yamcenutzer** [comment]
HI,
Didn't have the time to do full regression, but after removing/purging boost,ssl, websockets, then 
- git pull in vcpkg
- bootstrap
- update
- and finally installing cpprestsdk (which installs the other stuff again) it is now working:

Vcpkg package management program version 0.0.71-a0eb236eaa21d44351d0adcf7e4525f0a99e0c08
