### ISSUE TITLE
Qmake on project with Qt5 SVG module fails

### ISSUE THREAD

**Issue by Kissaki** [microsoft/vcpkg#6042]
I am trying to compile a Qt project which uses the Qt5 SVG module but no CMake.
INCLUDE, LIB and PATH have been adjusted to include the Qt tools, include, lib and manual link folders.

The build generally works fine, with other libraries and Qt itself.
However, for the project making use of the Qt5 SVG module with `QT  *= svg` fails with
```
Project ERROR: Unknown module(s) in QT: svg
Failed on project configuration with qmake
```

Is this supposed to work? Am I missing something? How do I make Qt recognize the separately installed svg module? I can see the lib and dll files in place in the vcpkg installed folder next to the main Qt library. Another project which makes use of `QT *= network sql xml`, which all seems to be included in the main port, works fine in this setup.

**Comment by Kissaki** [comment]
Running `qmake -query` shows that the configuration is generated wrongly. Every variable has a `<varname>/dev` duplicate with the path that would be correct.

`dev` is my root parent folder on the partition I am building/using vcpkg from. So that name may be coming from there.

```
QT_INSTALL_ARCHDATA:C:/dev/[…]/vcpkg/packages/qt5-base_x64-windows/share/qt5
QT_INSTALL_ARCHDATA/dev:C:/dev/[…]/vcpkg/installed/x64-windows/share/qt5
```

**Comment by JackBoosY** [comment]
Duplicate with #6085.
