### ISSUE TITLE
Missing documentation for WINDOWS_EXPORT_ALL_SYMBOLS guidelines

### ISSUE THREAD

**Issue by grdowns** [microsoft/vcpkg#6043]
https://github.com/Microsoft/vcpkg/pull/5784#issuecomment-476908733

**Comment by Neumann-A** [comment]
If one reads https://github.com/Microsoft/vcpkg/blob/master/CONTRIBUTING.md carefully it could be said that it is already defined: 

> Patches should be considered a last resort to implement compatibility when there's no other way.

> When patches can't be avoided, do not modify the default behavior.

It is in the same league of problems as #6014.

Maybe we should create a list of common problems/issues which have been observed within vcpkg and make those examples explicit in the documentation.

**Comment by PhoebeHui** [comment]
Thanks Griffin! Documentation has added to vcpkg, see https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-add-cmake_windows_export_all_symbols
