### ISSUE TITLE
How to install linux shared library， not static library

### ISSUE THREAD

**Issue by Ultraman95** [Microsoft/vcpkg#6048]

**Comment by Neumann-A** [comment]
as far as i understand the current status it is currently not supported by vcpkg. (probably in the future?)
But you could theoretically create  a new `x64-linux-shared` triplet (look into the triplet folder) with the following content:
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic) # changed to dynamic original x64-linux triplet uses static here

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
```
but do not expect it to work for everything

**Comment by Ultraman95** [comment]
谢谢

**Comment by Neumann-A** [comment]
@Ultraman95 please close the issue if the question has been answered. According to google translate it looks like it :)

**Comment by elesos** [comment]
see English please

**Comment by ivanstepanovftw** [comment]
English
