### ISSUE TITLE
Update netcdf-c to use szip targets & find_package in config mode

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#6050]
https://github.com/Microsoft/vcpkg/pull/5543#issuecomment-482068538

suggest it uses some other way to find szip (not using szipConfig.cmake) and thus only links against the release version.

(I dont have time to actual fix this.)

**Comment by Neumann-A** [comment]
@wangli28 label port bug would be more appropriate here.

**Comment by JackBoosY** [comment]
After looking at `szip-targets-debug.cmake` and `szip-targets-release.cmake`, I don't think there is any problem with using keyword `CONFIG` to find szip. Maybe some PR fixed it?
szip-targets-debug.cmake:
```
set(CMAKE_IMPORT_FILE_VERSION 1)

# Import target "szip-static" for configuration "Debug"
set_property(TARGET szip-static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(szip-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/debug/lib/libszip_D.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS szip-static )
list(APPEND _IMPORT_CHECK_FILES_FOR_szip-static "${_IMPORT_PREFIX}/debug/lib/libszip_D.lib" )

# Import target "szip-shared" for configuration "Debug"
set_property(TARGET szip-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(szip-shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "${_IMPORT_PREFIX}/debug/lib/szip_D.lib"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/debug/bin/szip_D.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS szip-shared )
list(APPEND _IMPORT_CHECK_FILES_FOR_szip-shared "${_IMPORT_PREFIX}/debug/lib/szip_D.lib" "${_IMPORT_PREFIX}/debug/bin/szip_D.dll" )

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
```
szip-targets-release.cmake:
```
set(CMAKE_IMPORT_FILE_VERSION 1)

# Import target "szip-static" for configuration "Release"
set_property(TARGET szip-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(szip-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libszip.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS szip-static )
list(APPEND _IMPORT_CHECK_FILES_FOR_szip-static "${_IMPORT_PREFIX}/lib/libszip.lib" )

# Import target "szip-shared" for configuration "Release"
set_property(TARGET szip-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(szip-shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/szip.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/szip.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS szip-shared )
list(APPEND _IMPORT_CHECK_FILES_FOR_szip-shared "${_IMPORT_PREFIX}/lib/szip.lib" "${_IMPORT_PREFIX}/bin/szip.dll" )

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
```

**Comment by Neumann-A** [comment]
The interesting think is that netcdf-c seems to link against those targets in CMake but does not need them in the link command?

`[135/136] cmd.exe /C "cd . && C:\PROGRA~2\MICROS~4\2019\COMMUN~1\VC\Tools\MSVC\1423~1.281\bin\Hostx64\x64\link.exe /lib  /machine:x64 /out:liblib\netcdf.lib libdispatch\CMakeFiles\dispatch.dir\dparallel.c.obj libdispatch\CMakeFiles\dispatch.dir\dcopy.c.obj libdispatch\CMakeFiles\dispatch.dir\dfile.c.obj libdispatch\CMakeFiles\dispatch.dir\ddim.c.obj libdispatch\CMakeFiles\dispatch.dir\datt.c.obj libdispatch\CMakeFiles\dispatch.dir\dattinq.c.obj libdispatch\CMakeFiles\dispatch.dir\dattput.c.obj libdispatch\CMakeFiles\dispatch.dir\dattget.c.obj libdispatch\CMakeFiles\dispatch.dir\derror.c.obj libdispatch\CMakeFiles\dispatch.dir\dvar.c.obj libdispatch\CMakeFiles\dispatch.dir\dvarget.c.obj libdispatch\CMakeFiles\dispatch.dir\dvarput.c.obj libdispatch\CMakeFiles\dispatch.dir\dvarinq.c.obj libdispatch\CMakeFiles\dispatch.dir\ddispatch.c.obj libdispatch\CMakeFiles\dispatch.dir\nclog.c.obj libdispatch\CMakeFiles\dispatch.dir\dstring.c.obj libdispatch\CMakeFiles\dispatch.dir\dutf8.c.obj libdispatch\CMakeFiles\dispatch.dir\dinternal.c.obj libdispatch\CMakeFiles\dispatch.dir\doffsets.c.obj libdispatch\CMakeFiles\dispatch.dir\ncuri.c.obj libdispatch\CMakeFiles\dispatch.dir\nclist.c.obj libdispatch\CMakeFiles\dispatch.dir\ncbytes.c.obj libdispatch\CMakeFiles\dispatch.dir\nchashmap.c.obj libdispatch\CMakeFiles\dispatch.dir\nctime.c.obj libdispatch\CMakeFiles\dispatch.dir\nc.c.obj libdispatch\CMakeFiles\dispatch.dir\nclistmgr.c.obj libdispatch\CMakeFiles\dispatch.dir\utf8proc.c.obj libdispatch\CMakeFiles\dispatch.dir\dwinpath.c.obj libdispatch\CMakeFiles\dispatch.dir\dutil.c.obj libdispatch\CMakeFiles\dispatch.dir\drc.c.obj libdispatch\CMakeFiles\dispatch.dir\dauth.c.obj libdispatch\CMakeFiles\dispatch.dir\dreadonly.c.obj libdispatch\CMakeFiles\dispatch.dir\dnotnc4.c.obj libdispatch\CMakeFiles\dispatch.dir\dnotnc3.c.obj libdispatch\CMakeFiles\dispatch.dir\crc32.c.obj libdispatch\CMakeFiles\dispatch.dir\daux.c.obj libdispatch\CMakeFiles\dispatch.dir\dinfermodel.c.obj libdispatch\CMakeFiles\dispatch.dir\dgroup.c.obj libdispatch\CMakeFiles\dispatch.dir\dvlen.c.obj libdispatch\CMakeFiles\dispatch.dir\dcompound.c.obj libdispatch\CMakeFiles\dispatch.dir\dtype.c.obj libdispatch\CMakeFiles\dispatch.dir\denum.c.obj libdispatch\CMakeFiles\dispatch.dir\dopaque.c.obj libdispatch\CMakeFiles\dispatch.dir\dfilter.c.obj libdispatch\CMakeFiles\dispatch.dir\dv2i.c.obj libsrc\CMakeFiles\netcdf3.dir\v1hpg.c.obj libsrc\CMakeFiles\netcdf3.dir\putget.c.obj libsrc\CMakeFiles\netcdf3.dir\attr.c.obj libsrc\CMakeFiles\netcdf3.dir\nc3dispatch.c.obj libsrc\CMakeFiles\netcdf3.dir\nc3internal.c.obj libsrc\CMakeFiles\netcdf3.dir\var.c.obj libsrc\CMakeFiles\netcdf3.dir\dim.c.obj libsrc\CMakeFiles\netcdf3.dir\ncx.c.obj libsrc\CMakeFiles\netcdf3.dir\lookup3.c.obj libsrc\CMakeFiles\netcdf3.dir\ncio.c.obj libsrc\CMakeFiles\netcdf3.dir\memio.c.obj libsrc\CMakeFiles\netcdf3.dir\posixio.c.obj libsrc4\CMakeFiles\netcdf4.dir\nc4dispatch.c.obj libsrc4\CMakeFiles\netcdf4.dir\nc4attr.c.obj libsrc4\CMakeFiles\netcdf4.dir\nc4dim.c.obj libsrc4\CMakeFiles\netcdf4.dir\nc4grp.c.obj libsrc4\CMakeFiles\netcdf4.dir\nc4type.c.obj libsrc4\CMakeFiles\netcdf4.dir\nc4var.c.obj libsrc4\CMakeFiles\netcdf4.dir\ncfunc.c.obj libsrc4\CMakeFiles\netcdf4.dir\nc4internal.c.obj libsrc4\CMakeFiles\netcdf4.dir\ncindex.c.obj libhdf5\CMakeFiles\netcdfhdf5.dir\nc4hdf.c.obj libhdf5\CMakeFiles\netcdfhdf5.dir\nc4info.c.obj libhdf5\CMakeFiles\netcdfhdf5.dir\hdf5file.c.obj libhdf5\CMakeFiles\netcdfhdf5.dir\hdf5attr.c.obj libhdf5\CMakeFiles\netcdfhdf5.dir\hdf5dim.c.obj libhdf5\CMakeFiles\netcdfhdf5.dir\hdf5grp.c.obj libhdf5\CMakeFiles\netcdfhdf5.dir\hdf5type.c.obj libhdf5\CMakeFiles\netcdfhdf5.dir\hdf5internal.c.obj libhdf5\CMakeFiles\netcdfhdf5.dir\hdf5create.c.obj libhdf5\CMakeFiles\netcdfhdf5.dir\hdf5open.c.obj libhdf5\CMakeFiles\netcdfhdf5.dir\hdf5var.c.obj libhdf5\CMakeFiles\netcdfhdf5.dir\nc4mem.c.obj libhdf5\CMakeFiles\netcdfhdf5.dir\nc4memcb.c.obj libhdf5\CMakeFiles\netcdfhdf5.dir\hdf5cache.c.obj libhdf5\CMakeFiles\netcdfhdf5.dir\hdf5dispatch.c.obj oc2\CMakeFiles\oc2.dir\oc.c.obj oc2\CMakeFiles\oc2.dir\daplex.c.obj oc2\CMakeFiles\oc2.dir\dapparse.c.obj oc2\CMakeFiles\oc2.dir\dapy.c.obj oc2\CMakeFiles\oc2.dir\occompile.c.obj oc2\CMakeFiles\oc2.dir\occurlfunctions.c.obj oc2\CMakeFiles\oc2.dir\ocdata.c.obj oc2\CMakeFiles\oc2.dir\ocdebug.c.obj oc2\CMakeFiles\oc2.dir\ocdump.c.obj oc2\CMakeFiles\oc2.dir\ocinternal.c.obj oc2\CMakeFiles\oc2.dir\ocnode.c.obj oc2\CMakeFiles\oc2.dir\ochttp.c.obj oc2\CMakeFiles\oc2.dir\ocread.c.obj oc2\CMakeFiles\oc2.dir\ocutil.c.obj oc2\CMakeFiles\oc2.dir\xxdr.c.obj libdap2\CMakeFiles\dap2.dir\constraints.c.obj libdap2\CMakeFiles\dap2.dir\dapcvt.c.obj libdap2\CMakeFiles\dap2.dir\dapodom.c.obj libdap2\CMakeFiles\dap2.dir\daputil.c.obj libdap2\CMakeFiles\dap2.dir\ncdaperr.c.obj libdap2\CMakeFiles\dap2.dir\cdf.c.obj libdap2\CMakeFiles\dap2.dir\cache.c.obj libdap2\CMakeFiles\dap2.dir\dapdump.c.obj libdap2\CMakeFiles\dap2.dir\dapdebug.c.obj libdap2\CMakeFiles\dap2.dir\dapattr.c.obj libdap2\CMakeFiles\dap2.dir\ncd2dispatch.c.obj libdap2\CMakeFiles\dap2.dir\getvara.c.obj libdap2\CMakeFiles\dap2.dir\dceconstraints.c.obj libdap2\CMakeFiles\dap2.dir\dcetab.c.obj libdap2\CMakeFiles\dap2.dir\dceparse.c.obj libdap2\CMakeFiles\dap2.dir\dcelex.c.obj libdap4\CMakeFiles\dap4.dir\d4crc32.c.obj libdap4\CMakeFiles\dap4.dir\d4curlfunctions.c.obj libdap4\CMakeFiles\dap4.dir\d4fix.c.obj libdap4\CMakeFiles\dap4.dir\d4data.c.obj libdap4\CMakeFiles\dap4.dir\d4file.c.obj libdap4\CMakeFiles\dap4.dir\d4parser.c.obj libdap4\CMakeFiles\dap4.dir\d4meta.c.obj libdap4\CMakeFiles\dap4.dir\d4varx.c.obj libdap4\CMakeFiles\dap4.dir\d4dump.c.obj libdap4\CMakeFiles\dap4.dir\d4swap.c.obj libdap4\CMakeFiles\dap4.dir\d4chunk.c.obj libdap4\CMakeFiles\dap4.dir\d4printer.c.obj libdap4\CMakeFiles\dap4.dir\d4read.c.obj libdap4\CMakeFiles\dap4.dir\d4http.c.obj libdap4\CMakeFiles\dap4.dir\d4util.c.obj libdap4\CMakeFiles\dap4.dir\d4odom.c.obj libdap4\CMakeFiles\dap4.dir\d4cvt.c.obj libdap4\CMakeFiles\dap4.dir\d4debug.c.obj libdap4\CMakeFiles\dap4.dir\ncd4dispatch.c.obj libdap4\CMakeFiles\dap4.dir\ezxml_extra.c.obj libdap4\CMakeFiles\dap4.dir\ezxml.c.obj liblib\CMakeFiles\netcdf.dir\nc_initialize.c.obj  && cd ."`

Other netcdf-c problem (libcurl wrong in the target file):
`INTERFACE_LINK_LIBRARIES "hdf5::hdf5_hl-static;hdf5::hdf5-static;\$<\$<NOT:\$<CONFIG:DEBUG>>:${_IMPORT_PREFIX}/lib/zlib.lib>;\$<\$<CONFIG:DEBUG>:${_IMPORT_PREFIX}/debug/lib/zlibd.lib>;${_IMPORT_PREFIX}/lib/libcurl.lib;${_IMPORT_PREFIX}/debug/lib/libcurl-d.lib"`

SZIP linkage is resolved via the HDF5 target

**Comment by JackBoosY** [comment]
Does this issue resolved?

**Comment by Neumann-A** [comment]
since #9361 was merged it should be solved.
