### ISSUE TITLE
libharu fails to build on non-Windows platforms if the linkage is static

### ISSUE THREAD

**Issue by ChrisTX** [microsoft/vcpkg#6053]
In the libharu portfile, there's an issue that static libraries are assumed to have a `.lib` extension. The exact location is [here](https://github.com/Microsoft/vcpkg/blob/master/ports/libharu/portfile.cmake#L35-L38). Naturally, this breaks on Linux or macOS since the respective files would have a `.a` or `.so`/`.dylib` file extension. Replacing the extension with `CMAKE_STATIC_LIBRARY_SUFFIX` and `CMAKE_IMPORT_LIBRARY_SUFFIX` (on Windows) and remove the `.so`/`.dylib` file and renaming to `libharu${CMAKE_STATIC_LIBRARY_SUFFIX}` should resolve the issue on macOS/Linux.

**Comment by JackBoosY** [comment]
In Windows the static library suffix should be `.lib`, in Linux the static library suffix should be `.a`, in osx the static library suffix should be `.a`.
See [documentation](https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_common_definitions.cmake).

So I don't think it's a problem.

**Comment by ChrisTX** [comment]
At the time of posting, it was a problem, because the lines I referred to in OP were renaming files with the `.lib` extension on all platforms, see the previous file version [here](https://github.com/microsoft/vcpkg/blob/5cdc61bf75a82015a67e8f2ed74578652263a4e8/ports/libharu/portfile.cmake#L23-L26) In the mean time, !6730 was merged and introduced a fix for this issue, see [here.](https://github.com/microsoft/vcpkg/pull/6730/commits/c5f681fc8e17e6dc62548d08f50ceeec0b8bd475)
