### ISSUE TITLE
vcpkg_configure_qmake looks for incorrect qmake names on Linux

### ISSUE THREAD

**Issue by ChrisTX** [microsoft/vcpkg#6054]
`vcpkg_configure_qmake` currently assumes that QMake is called `qmake`. On Linux, this is not the case, and the correct name would be `qmake-qt5`. [The mistake is here](https://github.com/Microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_configure_qmake.cmake#L20). If the system symlinks `qmake` to `qmake-qt5` (or some other Qt) for compatibility reasons, this will additionally cause the wrong Qt5 installation being consumed silently.

**Comment by NancyLi1013** [comment]
Hi @ChrisTX, thanks for posting this issue. Could you please help provide the steps to reproduce and the error info?

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.

**Comment by ChrisTX** [comment]
@wangli28 I'm sorry, I was on vacation and did not see the request for more information - although I do not understand what you need:

The `qmake` binary on Linux is suffixed with a `-qt4` or `-qt5`, i.e. they're called `qmake-qt4` and `qmake-qt5`. The binary `qmake` could refer to either Qt3's binary (on e.g. RHEL), [`qtchooser`](https://code.qt.io/cgit/qtsdk/qtchooser.git/) (on Debian and derivatives) or on distros that dropped Qt4, to actual `qmake-qt5` (on e.g. ArchLinux) or not exist at all (e.g. on Fedora). `qmake-qt5` exists on all systems and does the right thing.

A repro would thus be:
1. Install Fedora or RHEL
2. Try to use Qt with vcpkg

**Comment by ChrisTX** [comment]
I've also forgot to mention this: The `qt5-base` package in vcpkg will also produce a `qmake-qt5` binary, not a `qmake` one. Thus, on distros where `qmake` does the right thing, it still uses the system QMake over the one you've just built.

**Comment by JackBoosY** [comment]
@ChrisTX  qt5-base generates qmake name in linux as `qmake` instead of `qmake-qt4` or `qmake-qt5`.
```
@@:~/work/vcpkg$  ll installed/x64-linux/tools/qt5/
total 134384
drwxrwxr-x 2 user user     4096 Jul 10 08:06 ./
drwxrwxr-x 6 user user     4096 Jul 11 06:06 ../
-rwxrwxr-x 1 user user     6344 Jul 10 02:38 fixqt4headers.pl*
-rwxrwxr-x 1 user user   888032 Jul 10 02:38 moc*
-rwx------ 1 user user  3449328 Jul 10 02:38 qdbuscpp2xml*
-rwx------ 1 user user  3478000 Jul 10 02:38 qdbusxml2cpp*
-rwx------ 1 user user  3310064 Jul 10 02:38 qlalr*
-rwxrwxr-x 1 user user 25006000 Jul 10 02:38 qmake*
-rwxrwxr-x 1 user user 23951088 Jul 10 08:06 qml*
-rwxrwxr-x 1 user user  3896384 Jul 10 08:06 qmlcachegen*
-rwxrwxr-x 1 user user 24020720 Jul 10 08:06 qmleasing*
-rwxrwxr-x 1 user user  3433136 Jul 10 08:06 qmlimportscanner*
-rwxrwxr-x 1 user user  3392016 Jul 10 08:06 qmllint*
-rwxrwxr-x 1 user user  3244592 Jul 10 08:06 qmlmin*
-rwxrwxr-x 1 user user  5153912 Jul 10 08:06 qmlpreview*
-rwxrwxr-x 1 user user  5231736 Jul 10 08:06 qmlprofiler*
-rwxrwxr-x 1 user user 21267888 Jul 10 08:06 qmltestrunner*
-rw-r--r-- 1 user user      325 Jul 10 02:38 qt_debug.conf
-rw-r--r-- 1 user user      277 Jul 10 02:38 qt_release.conf
-rwx------ 1 user user  3228112 Jul 10 02:38 qvkgen*
-rwxrwxr-x 1 user user   871616 Jul 10 02:38 rcc*
-rwxrwxr-x 1 user user    48146 Jul 10 02:38 syncqt.pl*
-rwx------ 1 user user  3666416 Jul 10 02:38 uic*

```

**Comment by JackBoosY** [comment]
@Neumann-A Could you please take a look?

Thanks.

**Comment by Neumann-A** [comment]
@JackBoosY https://github.com/microsoft/vcpkg/blob/6d36e2a86baf8d227fc6dce587bd69997d67fb5e/scripts/cmake/vcpkg_configure_qmake.cmake#L24

you could change that line from `qmake` to `qmake-qt5 qmake` but for the search within vcpkg it does not matter since both searches are with `NO_DEFAULT_PATH`

**Comment by JackBoosY** [comment]
@Neumann-A I'm thinking about whether we need to rename it.

**Comment by JackBoosY** [comment]
I suspect that if we rename it, it will cause other problems. 
If we make a copy and change the name, it may also cause the problem of missing configuration files.

**Comment by JackBoosY** [comment]
I don’t think we need to do this, please manually copy these executables to the corresponding folder.
