### ISSUE TITLE
Multithreading missing from fftw3.dll

### ISSUE THREAD

**Issue by MikaelSlevinsky** [microsoft/vcpkg#6056]
I'm trying to add Windows CI through Appveyor for my package [FastTransforms](https://github.com/MikaelSlevinsky/FastTransforms). It has dependencies on a BLAS, such as OpenBLAS, and FFTW3, so naturally I thought that vcpkg could provide both of these dependencies.

However, upon further inspection, it appears that the FFTW package available in vcpkg does not support threading. See for example [the bin manifest](https://ci.appveyor.com/project/MikaelSlevinsky/fasttransforms/build/job/jeicoutp1h4xqc0a#L33) where the only `dll`'s from FFTW are related to the different sizes of floating-point types. See also [the error in calling `fftw_init_threads();`](https://ci.appveyor.com/project/MikaelSlevinsky/fasttransforms/build/job/jeicoutp1h4xqc0a#L102).

In unix, an FFTW package usually offers either `fftw3_threads` or `fftw3_omp`, but it appears that in Windows `dll`'s can't depend on each other, and others have proposed some workarounds to include the threading functionality in the main `dll`, such as https://github.com/LuaAndC/mxe/commit/ebdde3842c665b0c2f5239942fbfb76638cf2b4d. Will FFTW's threading be available through vcpkg?

**Comment by Neumann-A** [comment]
there is probably a cmake option for fftw3. Consider adding a featurepack to fftw3 which adds the threading or omp version. Currently it is not supported.

**Comment by hlysunnaram** [comment]
There is a [threads feature](https://github.com/Microsoft/vcpkg/blob/master/ports/fftw3/CONTROL#L20) in the `fftw3` package.

It is not enabled by default so maybe you can try to install the package with the following command line:

```
vcpkg install fftw3[core,threads]
```

**Comment by MikaelSlevinsky** [comment]
Thanks! That seems promising, but I can't get Appveyor to recognize/build the feature successfully.

Appveyor's vcpkg version is 2018.11.23-nohash, but [they say](https://www.appveyor.com/docs/lang/cpp/) that you can install a fresh version. I install it, update it, but still the [FFTW build fails](https://ci.appveyor.com/project/MikaelSlevinsky/fasttransforms/builds/23785507/job/8ml8dsftr4mskccw#L1626) with a CMAKE error.

**Comment by Neumann-A** [comment]
@hlysunnaram You are right it actual exists and git blame tells me I was the one who added it. I did not remember that neither did I actually test it. I probably just saw it as a CMake option and while adding the arch features also added it to the list. 

@MikaelSlevinsky can you post the log install-x64-windows-dbg-out.log

**Comment by MikaelSlevinsky** [comment]
I wish I could -- I don't have a Windows computer to reproduce, and can't extract the log from Appveyor since the error stops the build.

**Comment by Neumann-A** [comment]
@MikaelSlevinsky give x64-windows-static a try. It compiled for me. Probably threads needs a restriction on static targets only because else linker errors of unresolved fftw3 internal symbols are popping up within the log

**Comment by PhoebeHui** [comment]
I tried fftw3[core,threads]:x86-windows-static, it installed successfully.

But for fftw3[core,threads]:x86-windows, it failed, attach the failure logs:
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3159734/install-x86-windows-dbg-out.log)

**Comment by JackBoosY** [comment]
If we don't use ** CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS **, there will be a lot of LIN2019 / LNK2001 errors when building fftw3 [threads], because some functions are not declared as exportable, the following are these functions:
imax
- mksolver_ct_hook
- mksolver_hc2hc_hook
- mksolver
- mkplan_d
- mkplan_dft
- mkplan_rdft
- mkplan_rdft2
- mktensor_1d
- mktensor_2d
- mkproblem_dft
- mkproblem_dft_d
- mkproblem_rdft
- mkproblem_rdft_d
- mkproblem_rdft2
- solvtab_exec
- dft_solve
- ops_zero
- ops_add2
- tensor_tornk1
- plan_destroy_internal
- choose_radix
- ct_applicable
- tensor_copy
- tensor_destroy
- solver_register
- pickdim
- rdft_solve
- hc2hc_applicable
- rdft2_solve
- rdft2_inplace_strides
- rdft2_strides
- set_planner_hooks

**Comment by nickdademo** [comment]
@JackBoosY What's the fix in this case?

Passing `-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON` to the CMake configure step in the port file doesn't seem work for non-static builds.

**Comment by JackBoosY** [comment]
@nickdademo If you still want to build a dynamic library. Follow PR #5784 and add the content they removed.
Thanks.

**Comment by JackBoosY** [comment]
Hi everyone, due to source issues, we can only build static libraries in vcpkg, update vcpkg and rebuild fftw3.
Thanks.
