### ISSUE TITLE
vcpkg integrate install not working in 32-bit windows

### ISSUE THREAD

**Issue by sdcb** [Microsoft/vcpkg#606]
This issue is caused by the code in $\vcpkg\toolsrc\src\commands_integrate.cpp:
https://github.com/Microsoft/vcpkg/blob/master/toolsrc/src/commands_integrate.cpp#L16-L17
https://github.com/Microsoft/vcpkg/blob/master/toolsrc/src/commands_integrate.cpp#L19

The "Program Files (x86)" folder is incorrect in 32-bit windows, I switched to "Program Files" and running "vcpkg integrate install" again, everything just worked.

**Comment by alexkaratarakis** [comment]
@sdcb Please let me know if the fix works for you.

**Comment by sdcb** [comment]
@alexkaratarakis Unfortunately I was using vcpkg in my relative's house then, they installed 32-bit win7, currently my workstation is on win10-x64. 
If you used Environment Variable to present "Program Files" folder, I think we fixed it.

**Comment by alexkaratarakis** [comment]
I have verified that it works on Win7 32bit. : )
