### ISSUE TITLE
VS 2019 checks for UWP and 32 bit

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/vcpkg#6062]
https://github.com/Microsoft/vcpkg/commit/74e0c1a7849a898ddd5bd6863bf191dc2a60ddef

The commit above added checks explicitly disallowing VS 2019 for UWP and 32 bit. This was causing an issue, because my setup only has VS 2019, and VS 2019 does not give an option for installing the v141 UWP toolset anymore, only the standard v141 toolset. With the release of VS 2019 and cmake 3.14, this does not seem to be an issue anymore. I don't know the exact reason this was added, but maybe it should be removed. 

@ras0219-msft you committed the original change, so maybe you have more info.

**Comment by PhoebeHui** [comment]
@ThadHouse, thanks for posting this issue!

This issue has fixed by PR https://github.com/microsoft/vcpkg/pull/6265
