### ISSUE TITLE
[sqlite-orm] Update to v1.3

### ISSUE THREAD

**Issue by soroshsabz** [microsoft/vcpkg#6067]
ITNOA

Please update [sqlite-orm](https://github.com/fnc12/sqlite_orm) to [v1.3](https://github.com/fnc12/sqlite_orm/releases/tag/v1.3) that release in 3 days ago :)

thanks

**Comment by NancyLi1013** [comment]
Hi @soroshsabz, thanks for posting this issue. The port has been updated to 1.3 in this PR #6894. Please update and try to use it.
