### ISSUE TITLE
vcpkg does not build with clang on mac os

### ISSUE THREAD

**Issue by soroshsabz** [Microsoft/vcpkg#6068]
ITNOA

Hi

After resolved #4698 , we can set VCPKG_ALLOW_APPLE_CLANG, but after I set it, I see below errors when I try to build it

```

[1/64] Building CXX object CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o

FAILED: CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o 

/Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang  -DDISABLE_METRICS=0 -I../include -O3 -DNDEBUG   -std=c++1z -MD -MT CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o -MF CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o.d -o CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o -c ../src/vcpkg.cpp

In file included from ../src/vcpkg.cpp:24:

../include/vcpkg/base/files.h:8:10: fatal error: 'experimental/filesystem' file not found

#include <experimental/filesystem>

         ^~~~~~~~~~~~~~~~~~~~~~~~~

1 error generated.

[2/64] Building CXX object CMakeFiles/vcpkg.dir/src/vcpkg/base/checks.cpp.o

FAILED: CMakeFiles/vcpkg.dir/src/vcpkg/base/checks.cpp.o 

/Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang  -DDISABLE_METRICS=0 -I../include -O3 -DNDEBUG   -std=c++1z -MD -MT CMakeFiles/vcpkg.dir/src/vcpkg/base/checks.cpp.o -MF CMakeFiles/vcpkg.dir/src/vcpkg/base/checks.cpp.o.d -o CMakeFiles/vcpkg.dir/src/vcpkg/base/checks.cpp.o -c ../src/vcpkg/base/checks.cpp

In file included from ../src/vcpkg/base/checks.cpp:1:

../include/pch.h:43:10: fatal error: 'experimental/filesystem' file not found

#include <experimental/filesystem>

         ^~~~~~~~~~~~~~~~~~~~~~~~~

1 error generated.

[3/64] Building CXX object CMakeFiles/vcpkg.dir/src/vcpkg/archives.cpp.o

FAILED: CMakeFiles/vcpkg.dir/src/vcpkg/archives.cpp.o 

/Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang  -DDISABLE_METRICS=0 -I../include -O3 -DNDEBUG   -std=c++1z -MD -MT CMakeFiles/vcpkg.dir/src/vcpkg/archives.cpp.o -MF CMakeFiles/vcpkg.dir/src/vcpkg/archives.cpp.o.d -o CMakeFiles/vcpkg.dir/src/vcpkg/archives.cpp.o -c ../src/vcpkg/archives.cpp

In file included from ../src/vcpkg/archives.cpp:1:

../include/pch.h:43:10: fatal error: 'experimental/filesystem' file not found

#include <experimental/filesystem>

         ^~~~~~~~~~~~~~~~~~~~~~~~~

1 error generated.

ninja: build stopped: subcommand failed.

The command "if [[ "$CXX" == "clang" && "$TRAVIS_OS_NAME" == "osx" ]]; then ./bootstrap-vcpkg.sh --allowAppleClang ; else ./bootstrap-vcpkg.sh ; fi" failed and exited with 1 during .
```
How to resolve this problem?

LLVM information:

```
LLVM version

Apple LLVM version 10.0.0 (clang-1000.11.45.5)

Target: x86_64-apple-darwin17.7.0

Thread model: posix

InstalledDir: /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

OS X information:

```
Operating System Details

ProductName:	Mac OS X

ProductVersion:	10.13.6

BuildVersion:	17G65
```

**Comment by cbezault** [comment]
Could you give compiling it a shot with the Xcode 10.2 tool chain. Clang only added support for filesystem under 7.0 (your version of clang corresponds to 6.x). If that doesn't work I would guess your tool chain is compiling against libc++ instead of libstdc++. Try switching to using libstdc++.

**Comment by david-antiteum** [comment]
There is no filesystem in Xcode 10.2. It appears in one beta but was removed in the final version.

**Comment by cbezault** [comment]
@soroshsabz There you have it. You need to build vcpkg with a version of the standard library + compiler that supports the filesystem TS.

**Comment by soroshsabz** [comment]
@cbezault But in documents in CMakeLists.txt vcpkg says need clang 9.0 or above !!!

I think it is need to correct

**Comment by david-antiteum** [comment]
Xcode 10 is not based on clang 9 but, probably in clang 7. See here https://gist.github.com/yamaya/2924292#gistcomment-2874891

One solution is to install clang using, for example, brew. Look here: https://embeddedartistry.com/blog/2017/2/20/installing-clangllvm-on-osx

My solution is to wait a bit until Xcode 11 is released in June (beta)-September (final) :)

**Comment by soroshsabz** [comment]
@david-antiteum But as you can see `Apple LLVM version 10.0.0 (clang-1000.11.45.5)` my LLVM version is 10.0.0 , `clang-1000.11.45.5` meanis clang 7 ?

**Comment by david-antiteum** [comment]
Apple uses since a few years ago different version numbers than clang. For example:

Xcode 8.3  --> swift 3.1 --> llvm 4.0.0
Xcode 9.0  --> swift 4.0 --> llvm 4.0.0
Xcode 9.3  --> swift 4.1 --> llvm 5.0.2
Xcode 10.0 --> swift 4.2 --> llvm 6.0.1

(from https://gist.github.com/yamaya/2924292#gistcomment-2738480)

**Comment by soroshsabz** [comment]
@david-antiteum thanks, I follow https://embeddedartistry.com/blog/2017/2/20/installing-clangllvm-on-osx tutorial and resolved my problem thanks :)

**Comment by david-antiteum** [comment]
Xcode 11 has support for <filesystem> for macOS 10.15
