### ISSUE TITLE
OpenSSL UWP build should be split into separate library

### ISSUE THREAD

**Issue by chrullrich** [Microsoft/vcpkg#607]
The OpenSSL port is currently at version 1.0.2k, which is correct for the non-UWP build, yet the UWP build is still using version 1.0.2j (**but installs as 1.0.2k**). The UWP-adapted code comes from another Microsoft GitHub project, Microsoft/openssl, which has not had a commit in more than two months. I suggest that the UWP build be split out into its own port or removed entirely.

When I created the PR to upgrade OpenSSL from 1.0.2j to 1.0.2k two days ago, I mentioned in the PR comment, **in bold,** that it only updated the _non-UWP_ part, so the committer would know that merging the PR might need to be deferred until the UWP code had been updated as well.

**Comment by ras0219-msft** [comment]
For many other libraries, we would have strongly considered delayed the merge until UWP was also updated.

However, due to the sensitive nature of OpenSSL, we made the call to merge it immediately. We do need to improve the situation w.r.t. different platforms having different library versions -- this problem isn't specific to OpenSSL and will get worse if we consider targeting non-Windows platforms.

**Comment by ras0219-msft** [comment]
Also, I sent a mail to the primary contributor of Microsoft/openssl and he's informed me that they've just updated to 1.0.2k. I'll look at pulling in that update soon as well, which will resolve the immediate issue (though, as mentioned above, this is a more general problem that will need a general solution).

**Comment by ras0219-msft** [comment]
I'll close this issue now, since the particular fracture around openssl has been resolved. All platforms are now receiving 1.0.2j.
