### ISSUE TITLE
Libraries not found by CMake after setting CMAKE_TOOLCHAIN_FILE

### ISSUE THREAD

**Issue by illera88** [Microsoft/vcpkg#6073]
Hi,
As you can see in the following image I have sqlite3 installed and I'm setting CMAKE_TOOLCHAIN_FILE so it can be found. But it does not find it. Same thing with other libraries installed with vcpkg.

![2019-04-12 12_44_11-Inbox (3) - agarciaillera@gmail com - Gmail](https://user-images.githubusercontent.com/5193128/56062302-c8c1ee00-5d20-11e9-9c89-41afb8476f39.jpg)

I tried static and dynamic version (picture one is static).

Am I missing something?

**Comment by Neumann-A** [comment]
- CMake defaults to x64 for VS 2019 (it is written in the GUI but a bit too hidden), so you have to set x86 explicitly
- toolchain file must be loaded while configuring. So delete the cache and choose the third (of four) option to select a toolchain file while configuring

**Comment by Neumann-A** [comment]
![grafik](https://user-images.githubusercontent.com/30894796/56062802-eb2e2880-5d6d-11e9-990a-1f04d8904d03.png)

See x64 default, select 3rd option rest should be straight forward.

**Comment by illera88** [comment]
Thank you so much. The problem was not the architecture but that I was not specifying the toolchain when configuring.

Thank you so much!

**Comment by illera88** [comment]
I found another problem. If I want to use the static versions of a library I should set `VCPKG_TARGET_TRIPLET` to `x86-windows-static` but I can only do that once the configuration has been done and therefore the non static version has been already set.

How can I indicate the build to use the static version?

thank you

**Comment by Neumann-A** [comment]
Define the variable before configuring by hand.Its the add entry in the upper right of the gui barely visible in your first picture.

**Comment by illera88** [comment]
Thank you!
