### ISSUE TITLE
gdal: update to 2.4.1

### ISSUE THREAD

**Issue by luzpaz** [Microsoft/vcpkg#6074]
http://download.osgeo.org/gdal/2.4.1/

Other open issues impacted: 
- [ ] #5996
- [ ] #3258
- [ ] #3408
- [ ] #3397
- [ ] #3725
- [ ] #3816
- [ ] #5082

**Comment by wangli28** [comment]
Hi @luzpaz,
Latest version is 2.4.1, you can update vcpkg and rebuild.
Thanks.
