### ISSUE TITLE
Nana is outdated

### ISSUE THREAD

**Issue by ventsin** [microsoft/vcpkg#6079]
The new version, 1.7, is out:
http://nanapro.org/en-us/blog/?p=121
https://github.com/cnjinhao/nana

**Comment by ventsin** [comment]
It seems they have released a hotfix under the version 1.7.1:
http://nanapro.org/en-us/blog/?p=144

**Comment by wangli28** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
