### ISSUE TITLE
dealing with runtime-only DLLs

### ISSUE THREAD

**Issue by marcojez** [Microsoft/vcpkg#608]
I'm trying to set up a portfile for the ChaiScript library ([http://chaiscript.com](http://chaiscript.com)). I got it to build properly, but the post-build validation complains about some DLLs not having their LIB counterpart in the */lib directory. The point is, ChaiScript is an header-only library, and those DLLs are meant to be loaded dynamically from code (they are a sort of run-time plug-in). They are not meant to be linked at build time, so no import libraries are generated for them. Does the portfile have any control over the post-build validation process, which seems to be harmful in this case?

**Comment by alexkaratarakis** [comment]
cd0b7d644b2ba61618b70ae58f50d2e880dbe509 introduces the notion of "Policies".
Basically, if a package does something that deviates from the norm, it should explicitly state so.
In your particular case, you can add the following line in your portfile:
`SET(VCPKG_POLICY_DLLS_WITHOUT_LIBS disabled)`

This will add an appropriate entry in the BUILD_INFO file. That file is used by `vcpkg` to make decisions for the post build checks. 

Note that in this case, `vcpkg` will not be able to autodetect that you are using this library and copy the dlls app-locally. If you using this library in your application, you will have to somehow take its dlls into account. I think adding a warning message in the portfile that notifies the user about this would be useful.
