### ISSUE TITLE
help add repo  gstreamer and it's various plugins

### ISSUE THREAD

**Issue by zuowanbushiwo** [microsoft/vcpkg#6092]
gstreamer is strong and powerfull, many open source depend on it. but it is complex  to port。

**Comment by Voskrese** [comment]
Already have a request
https://github.com/Microsoft/vcpkg/issues/1474

And here is the port, but...
https://github.com/fujii/vcpkg/tree/gstreamer

**Comment by zuowanbushiwo** [comment]
@Voskrese thanks, how about those plugins ,gst-plugins-good, gst-plugins-base?

**Comment by Voskrese** [comment]
@zuowanbushiwo Yes, as if, until you do it yourself, no one will do it

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
