### ISSUE TITLE
[library support]please support the library mitab

### ISSUE THREAD

**Issue by iHuahua** [microsoft/vcpkg#6094]
Pls support the open source c++ library [mitab](http://mitab.maptools.org/), thx

**Comment by Voskrese** [comment]
very old code

`notepad mitab-1.7.0\cpl\cpl_config.h.vc`

edit to

```
#if _MSC_VER < 1400
/* Define if you have the vprintf function.  */
#define HAVE_VPRINTF
#define HAVE_VSNPRINTF
#define vsnprintf _vsnprintf
#endif

#if _MSC_VER < 1400
#define HAVE_SNPRINTF
#define snprintf _snprintf
#endif
```

`vcpkg env`

`cd mitab-1.7.0` 

`nmake -f makefile.vc`

**Comment by iHuahua** [comment]
thanks for reply. than i want to link it with cmake. pls

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
Or if anyone wish to add this port, please ping me.

Thanks.
