### ISSUE TITLE
[binn] Remove CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS

### ISSUE THREAD

**Issue by grdowns** [microsoft/vcpkg#6097]
Port accidentally merged while containing `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS`. See #5637 for new port PR and #6043 regarding `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS`.

**Comment by cenit** [comment]
we can add it to #5937 after a merge with master

**Comment by PhoebeHui** [comment]
CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS currently removed in binn, so close this issue.
