### ISSUE TITLE
Migrate to SHA-512

### ISSUE THREAD

**Issue by ras0219-msft** [Microsoft/vcpkg#61]
We currently use MD5 for integrity checking downloads, however this is provably breakable (even if improbable). We should upgrade all hashes to SHA-512 and require it going forward.

**Comment by Ninetainedo** [comment]
That should be fairly easy to change.
Should we support MD5 for backward compatibility ?
Or, given the small amount of portfiles, should we update everything ?

**Comment by KindDragon** [comment]
Sourceforge show only MD5 and SHA-1 for files https://sourceforge.net/projects/boost/files/boost/1.61.0/

**Comment by ras0219-msft** [comment]
@Ninetainedo I think because we're still small, we can update everything and avoid the burden of backcompat.

@KindDragon Yeah, for Sourceforge this means you (as a maintainer) would ideally download the file once, check the SHA1 against sourceforge's SHA-1, and then generate a SHA-512 hash locally for the portfile.

**Comment by Ninetainedo** [comment]
> @KindDragon Yeah, for Sourceforge this means you (as a maintainer) would ideally download the file once, check the SHA-1 against sourceforge's SHA-1, and then generate a SHA-512 hash locally for the portfile.

Isn't that what is already done by vcpkg ?

**Comment by ras0219-msft** [comment]
Yep, that's what the `vcpkg create` does currently for MD5 (though it's still up to you to check the download site's provided SHA).

**Comment by Ninetainedo** [comment]
Is there a reason to check the site's provided SHA instead of making it ourselves using the `FILE` command ?
By the way, I'm currently working on this. I've changed the concerned vcpkg files and I'm updating each portfile.

**Comment by ras0219-msft** [comment]
The original downloader may want to verify the site's SHA (if provided) to ensure their initial download is correct, especially if it's over HTTP instead of HTTPS. Generally, if it's HTTPS, that shouldn't be needed.

**Comment by peters** [comment]
@ras0219-msft Can you add a helper command in order to obtain the SHA512 hash for a given file?

`Get-FileHash -Algorithm SHA512 lib.zip | FL` is a tad verbose.

**Comment by Ninetainedo** [comment]
This is slightly off-topic: it's not really related to vcpkg.
You could build yourself a small script to do so.

**Comment by ras0219-msft** [comment]
@peters This sounds like it might be a good idea. Could you open a separate issue?
