### ISSUE TITLE
nlohmann-json outputs its copyright in wrong folder

### ISSUE THREAD

**Issue by RoguePointer80** [Microsoft/vcpkg#6103]
the natvis and cmake files are outputted under `share/nlohmann_json`, but the copyright file is under `share/nlohmann-json`.

I'm opening this very simple issue to link it with the commit + PR (to come very shortly)

**Comment by SuperWig** [comment]
It's a bug to not have it there. 
The CMake files need to be in `nlohmann_json` since the target is `nlohmann_json::nlohmann_json`
The copyright needs to match the package name which is `nlohmann-json` and underscores can't be used for package names.

**Comment by RoguePointer80** [comment]
Good morning. Thank you for the explanation. 
If I understand correctly, the problem arises because the CMake target is not the same as the package name.

| usage | value  |
|--------------|--------------|
| target name | nlohmann_json |
| package name | nlohmann-json|

> underscores can't be used for package names
So unless the package author is willing to change the package name to have a single word, like `nlohmannjson`, using the hyphen is the only option.

What about the CMake target name? can we change it to use a hyphen? [According to the doc](https://cmake.org/cmake/help/latest/policy/CMP0037.html) it can. Do you believe it would make sense to have the CMake targets use a hyphen instead of an underscore, with the end goal being to have a uniform naming for the package, and all files in the same folder?

**Comment by SuperWig** [comment]
That's what was done originally but it would break libs that target the proper one.

https://github.com/Microsoft/vcpkg/pull/5258

**Comment by RoguePointer80** [comment]
Understood.
I thought it would be an easy fix and I could contribute. But I believe there is no easy workaround; I am no expert with CMake. 
The bottom line is that it was probably wrong to assume that all output files under share should be in the same subfolder. Clearly, there are CMake target files, and package files, which in this particular case are not the same folder.
