### ISSUE TITLE
[Windows-Korean]BUILD_FAILED sdl2 and curl

### ISSUE THREAD

**Issue by 0-jun** [microsoft/vcpkg#6105]
I'm using 
- windows 10 pro 1803, os build : 17134.706
- os language : Korean
- vs2015 update3
- cmake3.13.4

When i install sdl2 and curl, i got message below.
`CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: C:/cmake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
Error: Building package sdl2:x86-windows failed with: BUILD_FAILED `
 Package: sdl2:x86-windows
  Vcpkg version: 2018.11.23-nohash

And, this is my log.
```
FAILED: CMakeFiles/SDL2.dir/src/main/windows/version.rc.res 
"C:/cmake/bin/cmcldeps.exe" RC C:\Users\chase\Desktop\vcpkg\buildtrees\sdl2\src\ease-2.0.9-ad425106c1\src\main\windows\version.rc CMakeFiles\SDL2.dir\src\main\windows\version.rc.res.d CMakeFiles\SDL2.dir\src\main\windows\version.rc.res "참고: 포함 파일: " "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe" C:\PROGRA~2\WI3CF2~1\10\bin\x64\rc.exe -DSDL2_EXPORTS -DUSING_GENERATED_CONFIG_H -D_USE_MATH_DEFINES -IC:\Users\chase\Desktop\vcpkg\buildtrees\sdl2\x86-windows-dbg\include -IC:\Users\chase\Desktop\vcpkg\buildtrees\sdl2\src\ease-2.0.9-ad425106c1\include -IC:\Users\chase\Desktop\vcpkg\buildtrees\sdl2\src\ease-2.0.9-ad425106c1\src\video\khronos -c65001 /DWIN32 /D_DEBUG /foCMakeFiles\SDL2.dir\src\main\windows\version.rc.res C:\Users\chase\Desktop\vcpkg\buildtrees\sdl2\src\ease-2.0.9-ad425106c1\src\main\windows\version.rc
```

**Comment by JackBoosY** [comment]
Hi @0-jun, thanks for reporting this issue.
Please remove cmake you installed manually, and then rebuild sdl2 and curl.

Thanks.

**Comment by JackBoosY** [comment]
If this issue is still not resolved, please reopen it.
