### ISSUE TITLE
ZeroC Ice Support

### ISSUE THREAD

**Issue by ZeroAbility** [microsoft/vcpkg#6106]
Is there any interest or possibility in making a port for this?

https://github.com/zeroc-ice/ice

Thanks in advance.

**Comment by ZeroAbility** [comment]
Depends on this:

https://github.com/zeroc-ice/mcpp

**Comment by ZeroAbility** [comment]
A port PR may be forthcoming depending on the results of this PR with ZeroC:

https://github.com/zeroc-ice/ice/pull/706

**Comment by ZeroAbility** [comment]
Based on a discussion with ZeroC they are not interested in merging the changes to their current version branch at this time. If there isn't any further interest in this port I would suggest closing this issue.

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
Or if anyone wish to add this port, please ping me.

Thanks.

**Comment by bold84** [comment]
I would like to have this reopened. I will contribute a port of it soon (nearly done).
