### ISSUE TITLE
wrong/invalid path in packagenameconfig.cmake files. _IMPORT_PREFIX not set

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#6113]
https://github.com/Microsoft/vcpkg/blob/5ab041409b82d4621697d8181fbcee8cb3a337f4/scripts/cmake/vcpkg_fixup_cmake_targets.cmake#L146

This line does not work in packagenameconfig.cmake files because _IMPORT_PREFIX is not set within them. For xconfig.cmake files another replacement must be used. Found by regressions in #5543 by ports depending on ceres failing to find glog.

**Comment by Neumann-A** [comment]
Question:
Does vcpkg define an appropriate variable to the installed root directory?

**Comment by JackBoosY** [comment]
Related: #7524.

**Comment by JackBoosY** [comment]
The installed root is always related to the selected triples because it changes.
And vcpkg toolchain provides the selected triples to find the correct installation root directory.

**Comment by BillyONeal** [comment]
>Does vcpkg define an appropriate variable to the installed root directory?

We have `${_VCPKG_INSTALLED_DIR}`; does that do what you need?

**Comment by Neumann-A** [comment]
should probably be `${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}` because that is the correct import prefix but it assumes that the vcpkg toolchain is used.

**Comment by Neumann-A** [comment]
vcpkg now adds VCPKG_IMPORT_PREFIX
