### ISSUE TITLE
Make git patch failures FATAL if the package was not cached

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#6137]
To keep vcpkg clean of unnecessary patches it would be helpful to enforce that git patches are actually applied correctly to packages if the buildtree was not cached. 
Updating a port can make some patches obsolete and a typically error is to forget to remove those patches.

**Comment by cenit** [comment]
https://github.com/Microsoft/vcpkg/blob/7e8d7b381d4282cfb4c998f93dd03666a68e7fd1/scripts/cmake/vcpkg_apply_patches.cmake#L52
It should be enough to modify this line. If you want to try you can do it, and enjoy fixing regressions. Maybe it’s better to wait for a couple of PR to be merged, they should fix many ports and it would avoid duplicating work

**Comment by cenit** [comment]
Also this would require updating all the portfile to the new patching system. I think 50% only are ready... 
while being very interesting (no more PR with broken patches, a lot of damage has been done in the past with this), this is a lot of work

**Comment by cenit** [comment]
@cbezault you can close this one :)

**Comment by cenit** [comment]
for a moment i thought you changed job 🤣
