### ISSUE TITLE
FR: please enforce on packages prerequisite detection and installation

### ISSUE THREAD

**Issue by 4creators** [Microsoft/vcpkg#614]
My proposal is to enforce on packages prerequisite detection and installation policy. This would ensure that build errors are rare and that alone would significantly improve user experience with vcpkg. During my first test of vcpkg I have encoutered build errors with libtheora, libogg, libssh2 and unnecessary installation of x86 CMake v3.7.2 by sqlite3 which was already installed as x64 version.

**Comment by OlafvdSpek** [comment]
What were the bugs in ogg, ssh2 and theora?

**Comment by 4creators** [comment]
@OlafvdSpek I have created issues for them and they are tracked jointly by #611

**Comment by ras0219-msft** [comment]
I believe the issues in #611 were resolved, which also resolves this issue. If this isn't the case, let me know and I can reopen this issue.
