### ISSUE TITLE
Error:Building package osg:x64-windows failed

### ISSUE THREAD

**Issue by Desch03** [microsoft/vcpkg#6140]

**Comment by Desch03** [comment]
Starting package 29/30: osg:x64-windows
Building package osg[core]:x64-windows...
-- Downloading https://github.com/openscenegraph/OpenSceneGraph/archive/OpenSceneGraph-3.6.2.tar.gz...
-- Extracting source H:/osgEarth_2/vcpkg-master/downloads/openscenegraph-OpenSceneGraph-OpenSceneGraph-3.6.2.tar.gz
-- Applying patch H:/osgEarth_2/vcpkg-master/ports/osg/collada.patch
-- Applying patch H:/osgEarth_2/vcpkg-master/ports/osg/static.patch
-- Using source at H:/osgEarth_2/vcpkg-master/buildtrees/osg/src/raph-3.6.2-a71b4e7564
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:202 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No;/m
    Working Directory: H:/osgEarth_2/vcpkg-master/buildtrees/osg/x64-windows-dbg
    See logs for more information:
      H:\osgEarth_2\vcpkg-master\buildtrees\osg\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/osg/portfile.cmake:43 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package osg:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: osg:x64-windows
  Vcpkg version: 2018.11.23-nohash

**Comment by Desch03** [comment]
Hi just received this message when using vcpkg for osgEarth. the command is the following: vcpkg install osgearth:x64-windows. I don't know what should I do except posting the full message. Thanks to all for enlighten me.

**Comment by Voskrese** [comment]
**See logs for more information:**
`H:\osgEarth_2\vcpkg-master\buildtrees\osg\install-x64-windows-dbg-out.log`

**Comment by Desch03** [comment]
Hi,

Link error with tiff library:   

  "H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\install.vcxproj" (cible par défaut) (1) ->
       "H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\ALL_BUILD.vcxproj" (cible par défaut) (3) ->
       "H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj" (cible par défaut) (268) ->
       (Link cible) -> "H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\install.vcxproj" (cible par défaut) (1) ->
       "H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\ALL_BUILD.vcxproj" (cible par défaut) (3) ->
       "H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj" (cible par défaut) (268) ->
       (Link cible) -> 
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_std_error referenced in function TIFFjpeg_create_compress [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_ojpeg.c.obj) : error LNK2001: unresolved external symbol jpeg_std_error [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_CreateCompress referenced in function TIFFjpeg_create_compress [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_CreateDecompress referenced in function TIFFjpeg_create_decompress [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_ojpeg.c.obj) : error LNK2001: unresolved external symbol jpeg_CreateDecompress [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_set_defaults referenced in function TIFFjpeg_set_defaults [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_set_colorspace referenced in function TIFFjpeg_set_colorspace [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_set_quality referenced in function TIFFjpeg_set_quality [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_suppress_tables referenced in function TIFFjpeg_suppress_tables [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_start_compress referenced in function TIFFjpeg_start_compress [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_write_scanlines referenced in function TIFFjpeg_write_scanlines [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_finish_compress referenced in function TIFFjpeg_finish_compress [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_write_raw_data referenced in function TIFFjpeg_write_raw_data [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_write_tables referenced in function TIFFjpeg_write_tables [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_read_header referenced in function TIFFjpeg_read_header [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_ojpeg.c.obj) : error LNK2001: unresolved external symbol jpeg_read_header [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_start_decompress referenced in function TIFFjpeg_start_decompress [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_ojpeg.c.obj) : error LNK2001: unresolved external symbol jpeg_start_decompress [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_read_scanlines referenced in function TIFFjpeg_read_scanlines [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_ojpeg.c.obj) : error LNK2001: unresolved external symbol jpeg_read_scanlines [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_finish_decompress referenced in function TIFFjpeg_finish_decompress [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_read_raw_data referenced in function TIFFjpeg_read_raw_data [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_ojpeg.c.obj) : error LNK2001: unresolved external symbol jpeg_read_raw_data [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_has_multiple_scans referenced in function TIFFjpeg_has_multiple_scans [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_abort referenced in function TIFFjpeg_error_exit [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_destroy referenced in function TIFFjpeg_destroy [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_ojpeg.c.obj) : error LNK2001: unresolved external symbol jpeg_destroy [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_jpeg.c.obj) : error LNK2019: unresolved external symbol jpeg_resync_to_restart referenced in function TIFFjpeg_data_src [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol __imp_lzma_code referenced in function LZMAEncode [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol __imp_lzma_end referenced in function LZMASetupDecode [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol __imp_lzma_memusage referenced in function LZMADecode [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol __imp_lzma_lzma_preset referenced in function TIFFInitLZMA [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol __imp_lzma_stream_encoder referenced in function LZMAPreEncode [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         tiffd.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol __imp_lzma_stream_decoder referenced in function LZMADecode [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]
         H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\bin\osgPlugins-3.6.2\osgdb_tiffd.dll : fatal error LNK1120: 27 unresolved externals [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]

Thanks.
David

**Comment by Desch03** [comment]
[install-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/3099431/install-x64-windows-dbg-out.log)
The full file.

**Comment by Desch03** [comment]
> 
> 
> **See logs for more information:**
> `H:\osgEarth_2\vcpkg-master\buildtrees\osg\install-x64-windows-dbg-out.log`

**Comment by Voskrese** [comment]
`vcpkg remove tiff:install-x64-windows`

`vcpkg install tiff[*]:install-x64-windows` + lzma + jpeg ...

**Comment by tqjxlm** [comment]
Exactly same error here. The solution provided by @Voskrese did not work for me. In my vcpkg environment, tiff, liblzma, openjpeg and jpeg-turbo are all up-to-date. Reinstallation would not help, either.

I'm using Visual Studio 201 and trying to compile the x64-windows version of osg.

**Comment by Desch03** [comment]
Hi,
Sorry for delay.
I did the following and it doesn't work too:

  vcpkg remove openjpeg:x64-windows --recurse
  vcpkg remove liblzma:x64-windows --recurse
  vcpkg remove libjpeg-turbo:x64-windows --recurse
  vcpkg remove tiff:x64-windows --recurse
  
Then I installed them one by one:
  vcpkg install openjpeg[*]:x64-windows
  vcpkg install liblzma[*]:x64-windows
  vcpkg install libjpeg-turbo[*]:x64-windows
  vcpkg install tiff[*]:x64-windows
 
Finally, I launched the installation again:
  vcpkg install osgearth:x64-windows

Then the same error appears.
[install-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/3130339/install-x64-windows-dbg-out.log)

Could you tell me what I did wrong and what should I do? 

Thanks a lot again.
David

**Comment by Voskrese** [comment]
install [*]
[*] !!!

**Comment by Voskrese** [comment]
libtiff defauilt compiled static, problem link dinamic

**Comment by jepessen** [comment]
Is there a reason for which tiff links statically instead of dynamic by default, or it's a portfile issue? I'm expecting that if I build it with x64-windows triplet instead of x64-windows-static the linking is dynamic instead that static, or I'm wrong? I'm saying this because I'd like to know if in order to check the issue and find a solution I need to work with osg package or with tiff one...

**Comment by Voskrese** [comment]
`vcpkg edit tiff`

vcpkg_check_linkage(ONLY_STATIC_LIBRARY)

to 

## vcpkg_check_linkage(ONLY_STATIC_LIBRARY)

**Comment by jepessen** [comment]
This is a nice solution. Creating a pull request for it can cause problems to other libraries rather than osg? Is possible in vcpkg check how many ports depend on a specific one?

**Comment by Voskrese** [comment]
I find it difficult to answer, I myself have encountered it recently in another project, and here the solution has matured

**Comment by jepessen** [comment]
Anyway I don't understand why it should be a problem. If I build a library and I obtain the .lib file, I link aganinst it, and it should not care if the .lib is a static library of refers to a dynamic one, the important thing is that osg can find it and find symbols, so in both cases osg should find symbols. What I'm missing in order to understand this issue well?

**Comment by Voskrese** [comment]
https://stackoverflow.com/questions/51576035/static-linking-search-for-dynamic-symbols-vs-2015

>  tiffd.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol __imp_lzma_end referenced in function LZMASetupDecode [H:\osgEarth_2\vcpkg-master\buildtrees\osg\x64-windows-dbg\src\osgPlugins\tiff\osgdb_tiff.vcxproj]

> From my understanding is that __imp_ symbols means the linker is trying to find the dll.

**Comment by jepessen** [comment]
I've the suspect that the source of 'evil' is that exported functions in `tiff` library are defined with `extern` keywork istead of using the classical `__declspec(dllexport)`, `__declspec(dllimport)` and corresponding ones in Linux. Maybe changing `extern` with commands for exporting and importing functions in `tiff` library can solve the issue?

**Comment by ceranco** [comment]
Hi, I have this problem as well.
Is there any update?

**Comment by alanjt** [comment]
Exactly the same as logged above.
I have even tried with a clean vcpkg that only has  .\vcpkg install --triplet x64-windows osg applied.

**Comment by Haojia521** [comment]
Hi everyone, I try to solve this issue and open a pr #6674 .
