### ISSUE TITLE
vcpkg install gtk fail

### ISSUE THREAD

**Issue by dry-git** [microsoft/vcpkg#6145]
![image](https://user-images.githubusercontent.com/47135274/56412601-5d939100-62b7-11e9-94f5-1d81b4d4e406.png)
vcpkg install gtk fail when install libepoxy 
compiler crash ?
the console message:

$ ./vcpkg.exe install gtk
The following packages will be built and installed:
  * atk[core]:x86-windows
  * bzip2[core]:x86-windows
  * cairo[core]:x86-windows
  * dirent[core]:x86-windows
  * expat[core]:x86-windows
  * fontconfig[core]:x86-windows
  * freetype[core]:x86-windows
  * gdk-pixbuf[core]:x86-windows
  * gettext[core]:x86-windows
  * glib[core]:x86-windows
    gtk[core]:x86-windows
  * harfbuzz[core,glib,ucdn]:x86-windows
  * libepoxy[core]:x86-windows
  * libffi[core]:x86-windows
  * libiconv[core]:x86-windows
  * libpng[core]:x86-windows
  * pango[core]:x86-windows
  * pcre[core]:x86-windows
  * pixman[core]:x86-windows
  * ragel[core]:x86-windows
  * zlib[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/21: libepoxy:x86-windows
Building package libepoxy[core]:x86-windows...
-- Using cached F:/msys64/home/dry_ruijie/vcpkg/downloads/anholt-libepoxy-1.4.3.tar.gz
-- Using source at F:/msys64/home/dry_ruijie/vcpkg/buildtrees/libepoxy/src/1.4.3-d354d88b66
-- Configuring x86-windows-rel

**Comment by wangli28** [comment]
Hi @dry-git, thank you for posting the issue, does the issue still occur? Can you provide the install log?

**Comment by gauss02** [comment]
I have the same problem.

![image](https://user-images.githubusercontent.com/1323920/56801604-6b658b00-6850-11e9-8095-7a96cd716024.png)

and no log output (log file 0 KB)

![image](https://user-images.githubusercontent.com/1323920/56801640-82a47880-6850-11e9-9f66-67fa88838588.png)

**Comment by liyiliuxingyu** [comment]
PS D:\WorkSpace\C++\vcpkg> .\vcpkg install gtk:x64-windows
The following packages will be built and installed:
    gtk[core]:x64-windows
  * pango[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: pango:x64-windows
Building package pango[core]:x64-windows...
-- Using cached D:/WorkSpace/C++/vcpkg/downloads/pango-1.40.11.tar.xz
-- Using source at D:/WorkSpace/C++/vcpkg/buildtrees/pango/src/1.40.11-f997ae867d
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:202 (message):
    Command failed: D:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v
    Working Directory: D:/WorkSpace/C++/vcpkg/buildtrees/pango/x64-windows-dbg
    See logs for more information:
      D:\WorkSpace\C++\vcpkg\buildtrees\pango\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/pango/portfile.cmake:25 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package pango:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: pango:x64-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by liyiliuxingyu** [comment]
Please help me .I have no idea.

**Comment by dry-git** [comment]
区域语言要改成英文的，同事vs也把需要改成英文，试试看。------------------ 原始邮件 ------------------
发件人: "流星雨"<notifications@github.com>
发送时间: 2019年5月19日(星期天) 上午10:35
收件人: "microsoft/vcpkg"<vcpkg@noreply.github.com>;
抄送: "dry-git"<923151719@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [microsoft/vcpkg] vcpkg install gtk fail (#6145)



Please help me .I have no idea.
 
&mdash;

**Comment by hair-man** [comment]
Change language to english [vs2019] and get "pango:x64-windows build failed"

log->
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3225322/install-x64-windows-dbg-out.log)

**Comment by hair-man** [comment]
#6622

**Comment by JackBoosY** [comment]
Hi @dry-git, can you update vcpkg and rebuild pango again?

Thanks.

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
