### ISSUE TITLE
vcpkg glib failed with BUILD_FAILED

### ISSUE THREAD

**Issue by dry-git** [microsoft/vcpkg#6147]
$ ./vcpkg.exe install glib
The following packages will be built and installed:
    glib[core]:x86-windows
Starting package 1/1: glib:x86-windows
Building package glib[core]:x86-windows...
-- Using cached F:/msys64/home/dry_ruijie/vcpkg/downloads/glib-2.52.3.tar.xz
-- Using source at F:/msys64/home/dry_ruijie/vcpkg/buildtrees/glib/src/2.52.3-624b8d46d4
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:202 (message):
    Command failed: F:/msys64/home/dry_ruijie/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v
    Working Directory: F:/msys64/home/dry_ruijie/vcpkg/buildtrees/glib/x86-windows-dbg
    See logs for more information:
      F:\msys64\home\dry_ruijie\vcpkg\buildtrees\glib\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/glib/portfile.cmake:48 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package glib:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glib:x86-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

the log file:
[config-x86-windows-out.log](https://github.com/Microsoft/vcpkg/files/3097861/config-x86-windows-out.log)
[install-x86-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/3097862/install-x86-windows-dbg-out.log)

**Comment by JackBoosY** [comment]
Hi @dry-git , thanks for reporting this issue!
It seems that there are many non-standard characters in the glib source code, so the build system does not recognize them. Sadly, it also caused patch failure.

**Comment by JackBoosY** [comment]
Hi @dry-git , it seems that static compilation by setting glib has solved this problem.
Can you update vcpkg and try it again?

**Comment by PhoebeHui** [comment]
@dry-git, does this still be an issue for you? I tried latest vcpkg with VS2017 15.9.11, it installed successfully.

PS F:\vcpkg\src> ./vcpkg install glib:x86-windows
The following packages will be built and installed:
    glib[core]:x86-windows
Starting package 1/1: glib:x86-windows
Building package glib[core]:x86-windows...
-- Using cached F:/VCPKG/src/downloads/glib-2.52.3.tar.xz
-- Using source at F:/VCPKG/src/buildtrees/glib/src/2.52.3-b89919d7eb
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package glib[core]:x86-windows... done
Installing package glib[core]:x86-windows...
Installing package glib[core]:x86-windows... done
Elapsed time for package glib:x86-windows: 1.469 min

Total elapsed time: 1.469 min

The package glib:x86-windows provides CMake targets:

    find_package(unofficial-glib CONFIG REQUIRED)
    # Note: 1 target(s) were omitted.
    target_link_libraries(main PRIVATE unofficial::glib::gio unofficial::glib::glib unofficial::glib::gmodule unofficial::glib::gobject)

**Comment by dry-git** [comment]
no,I solved this out------------------ 原始邮件 ------------------
发件人: "Phoebe"<notifications@github.com>
发送时间: 2019年5月28日(星期二) 下午2:21
收件人: "microsoft/vcpkg"<vcpkg@noreply.github.com>;
抄送: "dry-git"<923151719@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [microsoft/vcpkg] vcpkg glib failed with BUILD_FAILED (#6147)



@dry-git, does this still be an issue for you? I tried latest vcpkg with VS2017 15.9.11, it installed successfully.
 
PS F:\vcpkg\src> ./vcpkg install glib:x86-windows
 The following packages will be built and installed:
 glib[core]:x86-windows
 Starting package 1/1: glib:x86-windows
 Building package glib[core]:x86-windows...
 -- Using cached F:/VCPKG/src/downloads/glib-2.52.3.tar.xz
 -- Using source at F:/VCPKG/src/buildtrees/glib/src/2.52.3-b89919d7eb
 -- Configuring x86-windows
 -- Building x86-windows-dbg
 -- Building x86-windows-rel
 -- Performing post-build validation
 -- Performing post-build validation done
 Building package glib[core]:x86-windows... done
 Installing package glib[core]:x86-windows...
 Installing package glib[core]:x86-windows... done
 Elapsed time for package glib:x86-windows: 1.469 min
 
Total elapsed time: 1.469 min
 
The package glib:x86-windows provides CMake targets:
 find_package(unofficial-glib CONFIG REQUIRED) # Note: 1 target(s) were omitted. target_link_libraries(main PRIVATE unofficial::glib::gio unofficial::glib::glib unofficial::glib::gmodule unofficial::glib::gobject)  
&mdash;

**Comment by PhoebeHui** [comment]
Great to know it doesn't block you now.
