### ISSUE TITLE
nanodbc nanodbc error LNK2019: unresolved external symbol - on basic connection/opertaion

### ISSUE THREAD

**Issue by IshaanKarnik** [microsoft/vcpkg#6157]
I am unable to use nanodbc which was built using vcpkg.

I get error LNK2019: unresolved external symbol error on every method call.

However when I manually build nanodbc everything works fine.

Sample : 
`error LNK2019: unresolved external symbol "public: __cdecl nanodbc::connection::connection(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,long)" (??0connection@nanodbc@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00J@Z) referenced in function main`

**Comment by IshaanKarnik** [comment]
Using the nanodbc library built using vcpkg gives error LNK2019: unresolved external symbol.
Manually building the same library (with the same version) lets the program be compiled and executed successfully.

**Comment by NancyLi1013** [comment]
Hi @IshaanKarnik, thanks for posting this issue. Could you help provide the project case you used?

**Comment by IshaanKarnik** [comment]
It appears to be a problem the library as I made a clean manual build but the problem still exist.

**Comment by JackBoosY** [comment]
Hi @IshaanKarnik, which triplet do you choose to install? Also, please attach the error log displayed in the error message.
Thanks.

**Comment by IshaanKarnik** [comment]
I used x64-windows.
Being a old error I don't have the error log as we moved to different library.

**Comment by JackBoosY** [comment]
@IshaanKarnik Sorry, I can't reproduce it on x64-windows, maybe you should provide the error log.

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
