### ISSUE TITLE
poco x64-windows build failure

### ISSUE THREAD

**Issue by spechacek** [Microsoft/vcpkg#6160]
When trying to build poco x64-windows, Error: Building package libpq:x64-windows failed with: BUILD_FAILED. This happens even with a fresh clone of the vcpkg repo.

[install-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/3100244/install-x64-windows-dbg-out.log)

**Comment by mcraveiro** [comment]
Hi @spechacek,

It seems like its failing to link the postgres library:

```
   Creating library libpqd.lib and object libpqd.exp
fe-secure-openssl.c.obj : error LNK2019: unresolved external symbol sk_num referenced in function verify_peer_name_matches_certificate
fe-secure-openssl.c.obj : error LNK2019: unresolved external symbol sk_value referenced in function verify_peer_name_matches_certificate
fe-secure-openssl.c.obj : error LNK2019: unresolved external symbol sk_free referenced in function verify_peer_name_matches_certificate
fe-secure-openssl.c.obj : error LNK2019: unresolved external symbol SSL_load_error_strings referenced in function pgtls_init
fe-secure-openssl.c.obj : error LNK2019: unresolved external symbol SSLv23_method referenced in function initialize_SSL
fe-secure-openssl.c.obj : error LNK2019: unresolved external symbol SSL_library_init referenced in function pgtls_init
```

It has some similarities to the problems described in https://github.com/Microsoft/vcpkg/issues/731, in particular this comment:

> The problem is (probably) that Qt's build doesn't take into account transitive dependencies. Because our pq package is built with OpenSSL support, if Qt wants to link executables it needs to pull in that transitive dependency.

I'm not quite sure what the answer to this problem is but it may be worth trying a static build and see if the errors change or not...

**Comment by Voskrese** [comment]
Compiled without SSLv23_method

OpenSSL NO default method from TLSv1 to SSLv23 to enable and AES-GCM

**Comment by spechacek** [comment]
Hello @Voskrese ,

I am unfamiliar with how you were able to compile without the SSLv23_method. What were the file modifications or vcpkg command line options you used to make it work?

Thanks!

**Comment by Voskrese** [comment]
@spechacek 
I honestly do not know, especially did not delve, but the internet a lot of information about this problem

`google translate`

But you are clearly missing these characters\OBJ code .с

**Comment by spechacek** [comment]
Closing issue. I tried building the package on another dev workstation and it seems to have built without any errors. I guess it must be an environment issue that is causing it to fail.

**Comment by ollie-dawes** [comment]
Ran `./vcpkg install poco:x64-windows` today and ran into the same issue. It may well be an environment issue but it would be nice to know what is causing this.

**Host Environment**
- OS: `Microsoft Windows 10 Home (10.0.18362 Build 18362)`
- Compiler: `Microsoft (R) C/C++ Optimizing Compiler Version 19.21.27702.2 for x64`

**Failure logs** 
```
PS S:\vcpkg> ./vcpkg install poco:x64-windows
The following packages will be built and installed:
  * libpq[core]:x64-windows
    poco[core]:x64-windows
  * zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: libpq:x64-windows
Building package libpq[core]:x64-windows...
-- Using cached S:/vcpkg/downloads/postgresql-9.6.3.tar.bz2
-- Using source at S:/vcpkg/buildtrees/libpq/src/stgresql-9-d40671c654
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: S:/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: S:/vcpkg/buildtrees/libpq/x64-windows-dbg
    See logs for more information:
      S:\vcpkg\buildtrees\libpq\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/libpq/portfile.cmake:29 (vcpkg_install_cmake)
  scripts/ports.cmake:74 (include)


Error: Building package libpq:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libpq:x64-windows
  Vcpkg version: 2019.07.18-nohash
```

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3464993/install-x64-windows-dbg-out.log)

**Comment by Voskrese** [comment]
@ollie-dawes 

`C:\Program Files\OpenSSL-Win64\lib\VC\libssl64MDd.lib ws2_32.lib secur32.lib advapi32.lib shell32.lib crypt32.lib C:\Program Files\OpenSSL-Win64\lib\VC\libcrypto64MDd.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\libpq.dir/intermediate.manifest CMakeFiles\libpq.dir/manifest.res" failed (exit code 1120) with the following output:`

```
   Creating library libpqd.lib and object libpqd.exp
fe-secure-openssl.c.obj : error LNK2019: unresolved external symbol sk_num referenced in function verify_peer_name_matches_certificate
fe-secure-openssl.c.obj : error LNK2019: unresolved external symbol sk_value referenced in function verify_peer_name_matches_certificate
fe-secure-openssl.c.obj : error LNK2019: unresolved external symbol sk_free referenced in function verify_peer_name_matches_certificate
fe-secure-openssl.c.obj : error LNK2019: unresolved external symbol SSL_load_error_strings referenced in function pgtls_init
fe-secure-openssl.c.obj : error LNK2019: unresolved external symbol SSLv23_method referenced in function initialize_SSL
fe-secure-openssl.c.obj : error LNK2019: unresolved external symbol SSL_library_init referenced in function pgtls_init
libpqd.dll : fatal error LNK1120: 6 unresolved externals
```

**DELETE folder**

`C:\Program Files\OpenSSL-Win64`
