### ISSUE TITLE
Boost fails to build with BUILD_FAILED on Windows 10 1809

### ISSUE THREAD

**Issue by Plutoberth** [Microsoft/vcpkg#6161]
Hey! I'm trying to install boost (the full library) with vcpkg. 

Here are the steps that I performed:
```
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
.\bootstrap-vcpkg.bat 
.\vcpkg integrate install
.\vcpkg install boost:x86-windows (I also tried just 'boost', and just 'boost-asio')
```
Package: `boost-regex:x86-windows`
Vcpkg version: `2018.11.23-nohash`
Visual Studio 2019 Version `16.0.2`
Windows 10 Version `1809`
Log files:
[build-x86-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/3100246/build-x86-windows-rel-out.log)
[The output from vcpkg](https://github.com/Microsoft/vcpkg/files/3100247/Output.txt)

Thanks in advance :D

**Comment by mcraveiro** [comment]
Hi @Plutoberth,

I had a quick look at your log, and the most important bit is this one I think:

```
warning: Did not find command for MSVC toolset. If you have Visual Studio 2017 installed you will need to specify the full path to the command, set VS150COMNTOOLS for your installation, or build from the 'Visual Studio Command Prompt for VS 2017'.
```

Perhaps you are building from a regular shell? If so, try opening the Visual Studio command prompt instead, it puts the VS binaries in the path, etc. Also, bear in mind you are doing a 32-bit build, so you need the 32-bit command line shortcut I think.

Good luck

**Comment by Plutoberth** [comment]
@mcraveiro Thanks for helping. Looks like it's exactly the same failure mode as last time even after using the VS Dev console. I think that it might be because I'm using VS2019 and not VS2017. 

log:
```
Starting package 12/122: boost-regex:x86-windows
Building package boost-regex[core]:x86-windows...
-- Downloading https://github.com/boostorg/regex/archive/boost-1.69.0.tar.gz...
-- Extracting source C:/Users/Nir/Documents/Projects/vcpkg/downloads/boostorg-regex-boost-1.69.0.tar.gz
-- Using source at C:/Users/Nir/Documents/Projects/vcpkg/buildtrees/boost-regex/src/ost-1.69.0-80bf9a4997
-- Building x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: C:/Users/Nir/Documents/Projects/vcpkg/installed/x86-windows/tools/boost-build/b2.exe;--stagedir=C:/Users/Nir/Documents/Projects/vcpkg/buildtrees/boost-regex/x86-windows-rel/stage;--build-dir=C:/Users/Nir/Documents/Projects/vcpkg/buildtrees/boost-regex/x86-windows-rel;--user-config=C:/Users/Nir/Documents/Projects/vcpkg/buildtrees/boost-regex/x86-windows-rel/user-config.jam;-j4;--debug-configuration;--debug-building;--debug-generators;--disable-icu;--ignore-site-config;--hash;-q;-sZLIB_INCLUDE="C:/Users/Nir/Documents/Projects/vcpkg/installed/x86-windows/include";-sBZIP2_INCLUDE="C:/Users/Nir/Documents/Projects/vcpkg/installed/x86-windows/include";threading=multi;threadapi=win32;runtime-link=shared;link=shared;address-model=32;architecture=x86;toolset=msvc-14.1;-sZLIB_BINARY=zlib;-sZLIB_LIBPATH="C:/Users/Nir/Documents/Projects/vcpkg/installed/x86-windows/lib";-sBZIP2_BINARY=bz2;-sBZIP2_LIBPATH="C:/Users/Nir/Documents/Projects/vcpkg/installed/x86-windows/lib";variant=release;debug-symbols=on
    Working Directory: C:/Users/Nir/Documents/Projects/vcpkg/buildtrees/boost-regex/src/ost-1.69.0-80bf9a4997/build
    Error code: 1
    See logs for more information:
      C:\Users\Nir\Documents\Projects\vcpkg\buildtrees\boost-regex\build-x86-windows-rel-out.log

Call Stack (most recent call first):
  installed/x86-windows/share/boost-build/boost-modular-build.cmake:270 (vcpkg_execute_required_process)
  ports/boost-regex/portfile.cmake:20 (boost_modular_build)
  scripts/ports.cmake:71 (include)


Error: Building package boost-regex:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-regex:x86-windows
  Vcpkg version: 2018.11.23-nohash

```
[build-x86-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/3100489/build-x86-windows-rel-out.log)

**Comment by cenit** [comment]
VS2019 is unsupported both by vcpkg and by boost. Things should improve soon with boost 1.70 and some updates on vcpkg

**Comment by Voskrese** [comment]
` Visual Studio 2019 Version 16.0.2`
`error: msvc initialization: parameter 'version' inconsistent`

**Comment by Plutoberth** [comment]
Thanks @cenit & @Voskrese . I guess that I should've guessed this because VS2019 is still really new. I'll look deeper into the log files next time.

**Comment by Voskrese** [comment]
for good there are global settings files, by default they are naturally empty
`E:\tools\vcpkg\installed\x86-windows\tools\boost-build` **boost-build.jam**

`using msvc : [version] : [c++-compile-command] : [compiler options] ;`

_project-config.jam, user-config.jam_

mini hack
to automatically find MSVC
can add paths and version

edit msvc.jam
`E:\tools\vcpkg\installed\x86-windows\tools\boost-build\src\tools\` **msvc.jam**
