### ISSUE TITLE
uWebSocket needs to be updated to install from master branch

### ISSUE THREAD

**Issue by JadeVand** [microsoft/vcpkg#6163]
Currently vcpkg installs the 0.14 revision. Vcpkg needs to correctly install from the updated master branch.

**Comment by PhoebeHui** [comment]
Related PR https://github.com/Microsoft/vcpkg/pull/6133

**Comment by JadeVand** [comment]
Thank you for updating me on this and for the ports update!

**Comment by PhoebeHui** [comment]
Since the PR merged, I guess we can close this issue now.

**Comment by JadeVand** [comment]
@PhoebeHui Thank you so much!
