### ISSUE TITLE
vcpkg not properly integrating with VS2017

### ISSUE THREAD

**Issue by bCalabrese** [Microsoft/vcpkg#6164]
I'm unable to include any installed packages in a VS2017 project.
What I've done so far is:

1. Installed a fresh build of vcpkg
2. Installed all requisite packages for the project
3. Ran vcpkg integrate install
4. Re-installed Visual Studio

Visual Studio links everything correctly when running the project on my laptop, but I am unable to get it working on my desktop. This is the output I get when trying to build the project.
>1>------ Rebuild All started: Project: LearnOpenGL, Configuration: Release Win32 ------
1>Build started 4/20/2019 11:35:28 PM.
1>Target _PrepareForClean:
1>  Deleting file "Release\LearnOpenGL.tlog\LearnOpenGL.lastbuildstate".
1>Target InitializeBuildStatus:
1>  Touching "Release\LearnOpenGL.tlog\unsuccessfulbuild".
1>Target VcpkgTripletSelection:
1>  Using triplet "x86-windows" from "C:\Source\vcpkg\installed"
1>Target ClCompile:
1>  main.cpp
1>  c:\source\learnopengl\learnopengl\main.cpp(1): fatal error C1083: Cannot open include file: 'glad/glad.h': No such file or directory
1>  stb_image.cpp
1>Done building target "ClCompile" in project "LearnOpenGL.vcxproj" -- FAILED.
1>
1>Done building project "LearnOpenGL.vcxproj" -- FAILED.
1>
1>Build FAILED.
1>
1>c:\source\learnopengl\learnopengl\main.cpp(1): fatal error C1083: Cannot open include file: 'glad/glad.h': No such file or directory
1>    0 Warning(s)
1>    1 Error(s)
1>
1>Time Elapsed 00:00:00.48
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

I've noticed that the triplet path seems to be pointing to the wrong directory -- I belive I used to have an installation of vcpkg in C:\Source\vcpkg, but the current installation is in C:\vcpkg. I've tried reinstalling it at the old path instead, but I get the same error. I'm unsure what steps I should take to help resolve this issue.

**Comment by Neumann-A** [comment]
You probably want to look at %LOCALAPPDATA%\vcpkg and see where the files there are redirecting. 
If you moved vcpkg int a new directory a `vcpkg integrate install` at the new path should be enough to fix the path issues

**Comment by bCalabrese** [comment]
Deleting the folder in vcpkg folder from %LOCALAPPDATA%, and moving the vcpkg app folder into C:\Program Files seems to have resolved my issue. After rerunning `vcpkg integrate install` the correct path is specified in the triplet and everything links properly. Thank you for the help, I really appreciate it.
