### ISSUE TITLE
I could not build dlib in linux，how fix the issue:Cannot find source file: external/libpng/png.c

### ISSUE THREAD

**Issue by zdptrsz** [microsoft/vcpkg#6167]
Building package dlib[core]:x64-linux... 
-- Using cached /home/justin/Coding/vcpkg/downloads/davisking-dlib-v19.16.tar.gz
-- Extracting source /home/justin/Coding/vcpkg/downloads/davisking-dlib-v19.16.tar.gz
-- Applying patch fix-mac-jpeg.patch
-- Applying patch fix-sqlite3-fftw-linkage.patch
-- Using source at /home/justin/Coding/vcpkg/buildtrees/dlib/src/v19.16-9e1923f4db
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: /home/justin/Coding/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake;/home/justin/Coding/vcpkg/buildtrees/dlib/src/v19.16-9e1923f4db;-DDLIB_LINK_WITH_SQLITE3=ON;-DDLIB_USE_FFTW=ON;-DDLIB_PNG_SUPPORT=ON;-DDLIB_JPEG_SUPPORT=ON;-DDLIB_USE_BLAS=ON;-DDLIB_USE_LAPACK=ON;-DDLIB_USE_CUDA=OFF;-DDLIB_GIF_SUPPORT=OFF;-DDLIB_USE_MKL_FFT=OFF;-DCMAKE_DEBUG_POSTFIX=d;-DCMAKE_MAKE_PROGRAM=/home/justin/Coding/vcpkg/downloads/tools/ninja-1.8.2-linux/ninja;-DCMAKE_SYSTEM_NAME=Linux;-DBUILD_SHARED_LIBS=OFF;-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/justin/Coding/vcpkg/scripts/toolchains/linux.cmake;-DVCPKG_TARGET_TRIPLET=x64-linux;-DVCPKG_PLATFORM_TOOLSET=external;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=/home/justin/Coding/vcpkg/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DVCPKG_CXX_FLAGS=;-DVCPKG_CXX_FLAGS_RELEASE=;-DVCPKG_CXX_FLAGS_DEBUG=;-DVCPKG_C_FLAGS=;-DVCPKG_C_FLAGS_RELEASE=;-DVCPKG_C_FLAGS_DEBUG=;-DVCPKG_CRT_LINKAGE=dynamic;-DVCPKG_LINKER_FLAGS=;-DCMAKE_INSTALL_LIBDIR:STRING=lib;-DCMAKE_INSTALL_BINDIR:STRING=bin;-DDLIB_ENABLE_ASSERTS=ON;-G;Ninja;-DCMAKE_BUILD_TYPE=Debug;-DCMAKE_INSTALL_PREFIX=/home/justin/Coding/vcpkg/packages/dlib_x64-linux/debug
    Working Directory: /home/justin/Coding/vcpkg/buildtrees/dlib/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /home/justin/Coding/vcpkg/buildtrees/dlib/config-x64-linux-dbg-out.log
      /home/justin/Coding/vcpkg/buildtrees/dlib/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:282 (vcpkg_execute_required_process)
  ports/dlib/portfile.cmake:33 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package dlib:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: dlib:x64-linux
  Vcpkg version: 2018.11.23-unknownhash

Additionally, attach any relevant sections from the log files above.
--------------------
how could I give vcpkg the png.c file Manual？？
[config-x64-linux-dbg-err.log](https://github.com/Microsoft/vcpkg/files/3101555/config-x64-linux-dbg-err.log)
[config-x64-linux-dbg-out.log](https://github.com/Microsoft/vcpkg/files/3101556/config-x64-linux-dbg-out.log)

**Comment by JackBoosY** [comment]
Hi @zdptrsz, thanks for reporting this issue!
I checked the port log in git and made sure it was fixed in #6292.
The only problem is that the **COPYRIGHT** is uppercase in portfile.cmake.
After my PR merge, please update vcpkg and rebuild dlib.

Thanks.

**Comment by JackBoosY** [comment]
PR has been merged. Close this issue.
