### ISSUE TITLE
Could NOT find Threads (missing: THREADS_PTHREADS_WIN32_LIBRARY)

### ISSUE THREAD

**Issue by vivekhegde7** [microsoft/vcpkg#6169]
getting below error..

CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
Could NOT find Threads (missing: THREADS_PTHREADS_WIN32_LIBRARY)
Call Stack (most recent call first):
/usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
cmake/FindThreads.cmake:232 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
CMakeLists.txt:116 (find_package)

**Comment by vivekhegde7** [comment]
I am building OpenScap using vcpkg and Visual Studio2017.
while.. cmake -D ENABLE_PYTHON3=FALSE -D CMAKE_TOOLCHAIN_FILE=c:/devel/vcpkg/scripts/buildsystems/vcpkg.cmake ..
getting the above error.
Is there any way to set variable and path THREADS_PTHREADS_WIN32_LIBRARY 
anything to be edit in CMakeLists.txt for vcpkg pthread library?

**Comment by Voskrese** [comment]
PTHREADS_WIN32_LIBRARY

Win32? Windows?

/usr/share ... *unix ?

**Comment by Voskrese** [comment]
ubuntu

apt-get install pthread//s* or pthread//s-dev --<< lib and header

**Comment by vivekhegde7** [comment]
Windows 2012

**Comment by Voskrese** [comment]
full log attach

**Comment by vivekhegde7** [comment]
I am running cmake..


C:\devel\openscap\build>cmake -D ENABLE_PYTHON3=FALSE -D CMAKE_TOOLCHAIN_FILE=c:
/devel/vcpkg/scripts/buildsystems/vcpkg.cmake ..
-- OpenSCAP 1.3.0
-- (see C:/devel/openscap/README.md for build instructions)
--
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find DBUS (missing: DBUS_INCLUDE_DIRS DBUS_LIBRARIES)
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find Perl (missing: PERL_EXECUTABLE)
-- Could NOT find PerlLibs (missing: PERL_LIBRARY PERL_INCLUDE_PATH)
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (Re
quired is exact version "2")
-- Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE)
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR)
CMake Error at C:/Program Files/CMake/share/cmake-3.14/Modules/FindPackageHandle
StandardArgs.cmake:137 (message):
  Could NOT find Threads (missing: THREADS_PTHREADS_WIN32_LIBRARY)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.
cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindThreads.cmake:234 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  C:/devel/vcpkg/scripts/buildsystems/vcpkg.cmake:234 (_find_package)
  CMakeLists.txt:111 (find_package)

**Comment by vivekhegde7** [comment]
CmakeLists.txt


cmake_minimum_required(VERSION 2.6)

project("openscap")
set(OPENSCAP_VERSION_MAJOR "1")
set(OPENSCAP_VERSION_MINOR "3")
set(OPENSCAP_VERSION_PATCH "0")
set(OPENSCAP_VERSION "${OPENSCAP_VERSION_MAJOR}.${OPENSCAP_VERSION_MINOR}.${OPENSCAP_VERSION_PATCH}")
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}/cmake/")

message(STATUS "OpenSCAP ${OPENSCAP_VERSION}")
message(STATUS "(see ${CMAKE_SOURCE_DIR}/README.md for build instructions)")
message(STATUS " ")

# Strictly speaking in-source will work but will be very messy, let's
# discourage our users from using them
if ("${CMAKE_SOURCE_DIR}" STREQUAL "${CMAKE_BINARY_DIR}")
	message(FATAL_ERROR "In-source builds are not supported! Please use out of source builds:\n"
		"$ cd openscap\n"
		"$ rm CMakeCache.txt\n"
		"$ cd build\n"
		"$ cmake ../\n"
		"$ make -j4"
		)
endif()

if(CMAKE_BUILD_TYPE STREQUAL "Release" OR CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
	set(NDEBUG 1)
endif()

# In Microsoft Visual Studio, store built binaries to a single directory.
# We need to build all the binaries in a single directory on Windows, because
# vcpkg tool fails to fetch dependent DLLs (libxml, libcurl, etc.) if
# oscap.exe is build to a different directory than openscap.dll.
# See the discussion in https://github.com/Microsoft/vcpkg/issues/1002
if(MSVC)
	set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR})
	set(CMAKE_PDB_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR})
	set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR})
	set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR})
endif()

# ---------- INCLUDES CMAKE MODULES

include(GNUInstallDirs)
include(FindPkgConfig)
include(CheckLibraryExists)
include(CheckFunctionExists)
include(CheckIncludeFile)
include(CheckCSourceCompiles)
include(CMakeDependentOption)

# ---------- DEPENDENCIES

find_package(ACL)
if(ACL_FOUND)
	check_library_exists(acl acl_extended_file "" HAVE_ACL_EXTENDED_FILE)
	check_include_file(acl/libacl.h HAVE_ACL_LIBACL_H)
	check_include_file(sys/acl.h HAVE_SYS_ACL_H)
endif()

find_package(AptPkg)

find_package(Blkid)
if(BLKID_FOUND)
	check_library_exists(blkid blkid_get_tag_value "" HAVE_BLKID_GET_TAG_VALUE)
endif()

find_package(Cap)
if(CAP_FOUND)
	check_library_exists(cap cap_get_pid "" HAVE_CAP_GET_PID)
endif()

find_package(CURL)
find_package(DBus)
find_package(Doxygen)
find_package(GConf)
find_package(Ldap)
find_package(OpenDbx)
find_package(PCRE REQUIRED)
find_package(PerlLibs)
find_package(Popt)

find_package(Procps)
if(PROCPS_FOUND)
	check_library_exists(procps dev_to_tty "" HAVE_DEV_TO_TTY)
	check_include_file(proc/devname.h HAVE_PROC_DEVNAME_H)
endif()

find_package(PythonLibs 2 EXACT)
find_package(PythonInterp)

find_package(RPM)
if(RPM_FOUND)
	check_library_exists(rpm rpmReadConfigFiles "" HAVE_RPMREADCONFIGFILES)
	check_library_exists(rpm headerFormat "" HAVE_HEADERFORMAT)
	check_library_exists(rpmio rpmFreeCrypto "" HAVE_RPMFREECRYPTO)
	check_library_exists(rpm rpmFreeFilesystems "" HAVE_RPMFREEFILESYSTEMS)
	set(HAVE_RPMVERCMP 1)
endif()

find_package(SELinux)
find_package(SWIG)
find_package(LibXml2 REQUIRED)
find_package(LibXslt REQUIRED)
find_package(BZip2)

# PThread
set(CMAKE_THREAD_PREFER_PTHREAD)
set(THREADS_PREFER_PTHREAD_FLAG)
set(THREADS_USE_PTHREADS_WIN32 true)
find_package(Threads REQUIRED)
check_library_exists(pthread pthread_timedjoin_np "" HAVE_PTHREAD_TIMEDJOIN_NP)
check_library_exists(pthread pthread_setname_np "" HAVE_PTHREAD_SETNAME_NP)
check_library_exists(pthread pthread_getname_np "" HAVE_PTHREAD_GETNAME_NP)

# WITH_CRYPTO
set(WITH_CRYPTO "gcrypt" CACHE STRING "gcrypt|nss3")
if(NOT (${WITH_CRYPTO} EQUAL "nss3"))
	# gcrypt
	find_package(GCrypt)
else()
	# nss3
	find_package(NSS)
endif()
if(GCRYPT_FOUND OR NSS_FOUND)
	set(CRYPTO_FOUND TRUE)
endif()

check_library_exists(rt clock_gettime "" HAVE_CLOCK_GETTIME)
check_function_exists(posix_memalign HAVE_POSIX_MEMALIGN)
check_function_exists(memalign HAVE_MEMALIGN)
check_function_exists(fts_open HAVE_FTS_OPEN)
check_function_exists(strsep HAVE_STRSEP)
check_function_exists(strptime HAVE_STRPTIME)

check_include_file(syslog.h HAVE_SYSLOG_H)
check_include_file(stdio_ext.h HAVE_STDIO_EXT_H)
check_include_file(shadow.h HAVE_SHADOW_H)
check_include_file(sys/systeminfo.h HAVE_SYS_SYSTEMINFO_H)
check_include_file(getopt.h HAVE_GETOPT_H)
check_include_file(sys/uio.h HAVE_UIO_H)

**Comment by Voskrese** [comment]
vcpkg owns phread

vcpkg install _package_

fails to fetch libxml, libcurl, etc

You have not installed any packages. And what makes you think it's so easy to assemble your code like magic???

**Comment by vivekhegde7** [comment]
C:\devel\vcpkg>.\vcpkg install curl libxml2 libxslt bzip2
The following packages are already installed:
    bzip2[core]:x86-windows
    curl[core,ssl,winssl]:x86-windows
    libxml2[core]:x86-windows
    libxslt[core]:x86-windows
    pcre[core]:x86-windows
    pthreads[core]:x86-windows
Starting package 1/6: curl:x86-windows
Package curl:x86-windows is already installed
Elapsed time for package curl:x86-windows: 744.3 us
Starting package 2/6: pcre:x86-windows
Package pcre:x86-windows is already installed
Elapsed time for package pcre:x86-windows: 699.5 us
Starting package 3/6: libxslt:x86-windows
Package libxslt:x86-windows is already installed
Elapsed time for package libxslt:x86-windows: 685.8 us
Starting package 4/6: libxml2:x86-windows
Package libxml2:x86-windows is already installed
Elapsed time for package libxml2:x86-windows: 685.4 us
Starting package 5/6: bzip2:x86-windows
Package bzip2:x86-windows is already installed
Elapsed time for package bzip2:x86-windows: 693.6 us
Starting package 6/6: pthreads:x86-windows
Package pthreads:x86-windows is already installed
Elapsed time for package pthreads:x86-windows: 680.4 us

Total elapsed time: 5.856 ms

already installed above required pkgs

**Comment by Voskrese** [comment]
> Oh, I don't even know, it's a private case, with a third-party code.
> You need to write not here and there that you collect
@tara-raj Can support managers what will answer?

_Sorry for my English, Google translate_

**Comment by Voskrese** [comment]
And why do you write here because there is official documentation?
http://static.open-scap.org/openscap-1.2/oscap_user_manual.html

6.4. Building OpenSCAP on Windows

Windows is in **cygwin**
./autogen.sh

**Comment by Voskrese** [comment]
@vivekhegde7 
You better make a request. To add a library **OpenSCAP** 
Really... Will wait so long until there is an interested person in the same matter ))

**Comment by NancyLi1013** [comment]
Hi @vivekhegde7, thanks for posting this issue. I try to add the port OpenSCAP and I had the same issue with you. It seems like a bug. I noticed that you had posted here https://github.com/OpenSCAP/openscap/issues/1321.
We will investigate this issue further. 
@Voskrese, thanks for your kind help.

**Comment by Voskrese** [comment]
are many dependencies that do not compile under MSVC, only under mingw and cygwin

**Comment by JackBoosY** [comment]
Hi @vivekhegde7, thanks for reporting this issue.
I've added this port in vcpkg, please update vcpkg and try to install it.

Thanks.
