### ISSUE TITLE
boost:x64-windows-static fails to install (wrong versions?)

### ISSUE THREAD

**Issue by yamcenutzer** [Microsoft/vcpkg#617]
##boost 1.63

...
-- Installing: D:/robinmi/vcpkg/packages/boost_x64-windows-static/debug/lib/libboost_thread-vc140-mt-gd-1_62.lib
-- Installing: D:/robinmi/vcpkg/packages/boost_x64-windows-static/debug/lib/libboost_thread-vc140-mt-sgd-1_63.lib
-- Installing: D:/robinmi/vcpkg/packages/boost_x64-windows-static/debug/lib/libboost_timer-vc140-mt-gd-1_62.lib
-- Installing: D:/robinmi/vcpkg/packages/boost_x64-windows-static/debug/lib/libboost_timer-vc140-mt-sgd-1_63.lib
-- Installing: D:/robinmi/vcpkg/packages/boost_x64-windows-static/debug/lib/libboost_type_erasure-vc140-mt-gd-1_62.lib
-- Installing: D:/robinmi/vcpkg/packages/boost_x64-windows-static/debug/lib/libboost_type_erasure-vc140-mt-sgd-1_63.lib
-- Installing: D:/robinmi/vcpkg/packages/boost_x64-windows-static/debug/lib/libboost_unit_test_framework-vc140-mt-gd-1_62.lib
-- Installing: D:/robinmi/vcpkg/packages/boost_x64-windows-static/debug/lib/libboost_unit_test_framework-vc140-mt-sgd-1_63.lib
-- Installing: D:/robinmi/vcpkg/packages/boost_x64-windows-static/debug/lib/libboost_wave-vc140-mt-gd-1_62.lib
-- Installing: D:/robinmi/vcpkg/packages/boost_x64-windows-static/debug/lib/libboost_wave-vc140-mt-sgd-1_63.lib
-- Installing: D:/robinmi/vcpkg/packages/boost_x64-windows-static/debug/lib/libboost_wserialization-vc140-mt-gd-1_62.lib
-- Installing: D:/robinmi/vcpkg/packages/boost_x64-windows-static/debug/lib/libboost_wserialization-vc140-mt-sgd-1_63.lib
-- Packaging x64-windows-static-dbg done
-- Performing post-build validation

-- Performing post-build validation
Expected [Debug,static] crt linkage, but the following libs had invalid crt linkage:

    D:/robinmi/vcpkg/packages/boost_x64-windows-static/debug/lib/boost_exception-vc140-mt-gd-1_62.lib: [Debug,dynamic]
    D:/robinmi/vcpkg/packages/boost_x64-windows-static/debug/lib/boost_test_exec_monitor-vc140-mt-gd-1_62.lib: [Debug,dynamic]

To inspect the lib files, use:
    dumpbin.exe /directives mylibfile.lib
Expected [Release,static] crt linkage, but the following libs had invalid crt linkage:

    D:/robinmi/vcpkg/packages/boost_x64-windows-static/lib/boost_exception-vc140-mt-1_62.lib: [Release,dynamic]
    D:/robinmi/vcpkg/packages/boost_x64-windows-static/lib/boost_test_exec_monitor-vc140-mt-1_62.lib: [Release,dynamic]

To inspect the lib files, use:
    dumpbin.exe /directives mylibfile.lib
Found 2 error(s). Please correct the portfile:
    D:\robinmi\vcpkg\ports\boost\portfile.cmake

**Comment by ras0219-msft** [comment]
```
-- Installing: D:/robinmi/vcpkg/packages/boost_x64-windows-static/debug/lib/libboost_timer-vc140-mt-gd-1_62.lib
-- Installing: D:/robinmi/vcpkg/packages/boost_x64-windows-static/debug/lib/libboost_timer-vc140-mt-sgd-1_63.lib
```

This is really bizarre -- the same behavior @KindDragon was seeing in #598. I've added some additional assertions to the boost portfile in 0b2dd9b to ensure we've completely purged the previous build trees and package. Could you pull the latest and try rebuilding?

**Comment by KindDragon** [comment]
This bug happens for me only with vcpkg 0.0.65, bug disappear after updating to version 0.0.70

**Comment by yamcenutzer** [comment]
Using 
Vcpkg package management program version 0.0.71-c6ab2a962600b5c1c506b7dbf70d5719c4c8aaf1

yes, looks better now.
Do I need to rebuild the shared ones too?,
might as well do it :-)

**Comment by ras0219-msft** [comment]
It's probably a good idea. You can do `vcpkg owns 1_62.lib` to find any "misplaced" import libs from boost 1.62 to ensure you've completely purged the issue from your system.

Since this issue appears fixed in the latest versions, I'll close it now.
