### ISSUE TITLE
grpc Fails on ARM/ARM64

### ISSUE THREAD

**Issue by dwcullop** [Microsoft/vcpkg#6177]
I am trying to build grpc on both ARM and ARM64 for Windows, and it is failing because of its ZLib dependency.  Can someone explain why this is happening and what it would take to resolve?  I'm happy to put time into resolving this, if I know what I need to do.

The 64-bit fails like this:
```
C:\Code\GitHub\vcpkg> vcpkg install grpc:arm64-windows
The following packages will be built and installed:
  * c-ares[core]:arm64-windows
    grpc[core]:arm64-windows
  * openssl[core]:arm64-windows
  * openssl-windows[core]:arm64-windows
  * protobuf[core]:arm64-windows
  * zlib[core]:arm64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/6: zlib:arm64-windows
Building package zlib[core]:arm64-windows...
Unsupported toolchain combination. Target was: arm64 but supported ones were:
x86,amd64,x86_amd64,amd64_x86
```

The 32-bit version fails to build as well:
```
C:\Code\GitHub\vcpkg> vcpkg install grpc:arm-windows
The following packages will be built and installed:
  * c-ares[core]:arm-windows
    grpc[core]:arm-windows
  * openssl[core]:arm-windows
  * openssl-windows[core]:arm-windows
  * protobuf[core]:arm-windows
  * zlib[core]:arm-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/6: zlib:arm-windows
Building package zlib[core]:arm-windows...
Unsupported toolchain combination. Target was: arm but supported ones were:
x86,amd64,x86_amd64,amd64_x86
```

**Comment by dwcullop** [comment]
Does the "needs-repro" tag mean that you were not able to recreate the issue or does it mean you need the steps to recreate the issue?  For me, neither of the following two commands complete successfully:

   1) `vcpkg install grpc:arm64-windows`
   1) `vcpkg install grpc:arm-windows`

Why is vcpkg not even attempting to build the zlib?  How can I get past that, just to see how far the build would go?

**Comment by dwcullop** [comment]
This issue turned out to be my fault.  I didn't have all of the compiler support libraries for Visual Studio installed for ARM/ARM64.  Once they were installed completely, the issue went away.

I guess my takeaway is that maybe the messaging around "Unsupported toolchain combination. Target was: arm64 but supported ones were: x86,amd64,x86_amd64,amd64_x86"  could be changed to something that tells the user that the compiler support is missing on their system.  If it had said something like that, I surely would've checked all the compiler installation options before filing an issue like this.

**Comment by tom-r-o** [comment]
@dwcullop , I'm also getting the same error you mentioned:

> Unsupported toolchain combination. Target was: arm64 but supported ones were: x86,amd64,x86_amd64,amd64_x86

Can you share which libraries you installed for Visual Studio?
I have VS2015, 2017 and 2019 installed, and there are a lot of ARM build tools available for installation (I'd rather not install all of them, as they take up quite a lot of drive space)
