### ISSUE TITLE
Project that depends on vcpkg library is never considered up-to-date

### ISSUE THREAD

**Issue by crusader-mike** [microsoft/vcpkg#6179]
Win7, MSVC 2017, latest vcpkg. Here is how output looks like:

```
1>------ Build started: Project: o2ftool, Configuration: Debug x64 ------
1>Build started 4/19/2019 5:31:55 PM.
1>Target ResolveProjectReferences:
1>Target InitializeBuildStatus:
1>  Touching "x64\Debug\o2ftool.tlog\unsuccessfulbuild".
1>Target VcpkgTripletSelection:
1>  Using triplet "x64-windows" from "c:\vcpkg\installed\x64-windows\"
1>Target ClCompile:
1>  All outputs are up-to-date.
1>Target ResolvedLinkLib:
1>  Target SetBuildDefaultEnvironmentVariables:
1>Target Link:
1>  All outputs are up-to-date.
1>  o2ftool.vcxproj -> C:\<blah-blah>\Debug\o2ftool.exe
1>Target AppLocalFromInstalled:
1>  C:\<blah-blah>\Debug\aws-cpp-sdk-core.dll
1> ...
1>  C:\<blah-blah>\Debug\zlibd1.dll
1>Target _CopyFilesMarkedCopyLocal:
1>  Touching "C:\<blah-blah>\o2ftool\x64\Debug\o2ftool.vcxproj.CopyComplete".
1>Target GetCopyToOutputDirectoryItems:
1>Target FinalizeBuildStatus:
1>  Deleting file "x64\Debug\o2ftool.tlog\unsuccessfulbuild".
1>  Touching "x64\Debug\o2ftool.tlog\o2ftool.lastbuildstate".
1>
1>Build succeeded.
1>    0 Warning(s)
1>    0 Error(s)
1>
1>Time Elapsed 00:00:00.67
========== Build: 1 succeeded, 0 failed, 2 up-to-date, 0 skipped ==========
```

Regardless how many time I build it, it finds smth to do every time... Looks like some sort of a bug, here is what output looks like on 'Diagnostic' lvl:
```
3>------ Up-To-Date check: Project: o2ftool, Configuration: Debug x64 ------
3>Project is not up-to-date: build output '㩃呜卆卜潴慲敧屘畃牲湥屴楂屮敄畢屧睡⵳灣⵰摳⵫潣敲搮汬਍㩃呜卆卜潴慲敧屘畃牲湥屴楂屮敄畢屧睡⵳ⵣ癥湥⵴瑳敲浡搮汬਍㩃呜卆卜潴慲敧屘畃牲湥屴楂屮敄畢屧睡⵳ⵣ潣浭湯搮汬਍㩃呜卆卜潴慲敧屘畃牲湥屴楂屮敄畢屧睡⵳档捥獫浵⹳汤൬䌊尺䙔屓瑓牯条塥䍜牵敲瑮䉜湩䑜扥杵慜獷挭灰猭此猭⸳汤൬䌊尺䙔屓瑓牯条塥䍜牵敲瑮䉜湩䑜扥杵捜灰敲瑳㉟ㅟ搰搮汬਍㩃呜卆卜潴慲敧屘畃牲湥屴楂屮敄畢屧楬换牵⵬⹤汤൬䌊尺䙔屓瑓牯条塥䍜牵敲瑮䉜湩䑜扥杵穜楬摢⸱汤൬䌊尺䙔屓瑓牯条塥䍜牵敲瑮䉜湩䑜扥杵睜獡潴慲敧搮汬਍' is missing
3>------ Build started: Project: o2ftool, Configuration: Debug x64 ------
3>Build started 4/22/2019 5:32:51 PM.
3>Environment at start of build:
<blah-blah-blah>
```

I have no idea where this long line of garbage came from and why my project depends on it, but I can't find anything in vcxproj files and this happens **only** if I try to use vcpkg library in my code.

**Comment by crusader-mike** [comment]
@wangli28 I am pretty sure it is a bug or corruption somewhere. Probably MSVC2017, but I have no idea how to diagnose it, i.e. how to figure out where build output `㩃呜卆卜潴慲敧屘畃牲湥屴楂屮敄畢屧睡⵳灣⵰摳⵫潣敲搮汬਍㩃呜卆卜潴慲敧屘畃牲湥屴楂屮敄畢屧睡⵳ⵣ癥湥⵴瑳敲浡搮汬਍㩃呜卆卜潴慲敧屘畃牲湥屴楂屮敄畢屧睡⵳ⵣ潣浭湯搮汬਍㩃呜卆卜潴慲敧屘畃牲湥屴楂屮敄畢屧睡⵳档捥獫浵⹳汤൬䌊尺䙔屓瑓牯条塥䍜牵敲瑮䉜湩䑜扥杵慜獷挭灰猭此猭⸳汤൬䌊尺䙔屓瑓牯条塥䍜牵敲瑮䉜湩䑜扥杵捜灰敲瑳㉟ㅟ搰搮汬਍㩃呜卆卜潴慲敧屘畃牲湥屴楂屮敄畢屧楬换牵⵬⹤汤൬䌊尺䙔屓瑓牯条塥䍜牵敲瑮䉜湩䑜扥杵穜楬摢⸱汤൬䌊尺䙔屓瑓牯条塥䍜牵敲瑮䉜湩䑜扥杵睜獡潴慲敧搮汬਍` came from...

**Comment by crusader-mike** [comment]
Any idea how to diagnose it? I.e. figure out where "build outputs" come from?

**Comment by JackBoosY** [comment]
@crusader-mike, thanks for reporting this issue!
We will have a look later.
Thanks.

**Comment by crusader-mike** [comment]
Hmm... Found where garbage comes from -- here is how my `C:\<blah>\o2ftool\x64\Release\o2ftool.tlog\o2ftool.write.1u.tlog` file looks like:
```
^C:\<blah>\o2ftool\o2ftool.vcxproj
C:\<blah>\Release\o2ftool.ipdb
C:\<blah>\Release\o2ftool.iobj
^C:\<blah>\Release\o2ftool.exe
C:\<blah>\o2ftool\x64\Release\vcpkg.applocal.log
㩃呜卆卜潴慲敧屘畃牲湥屴楂屮敒敬獡履睡⵳灣⵰摳⵫潣敲搮汬਍㩃呜卆卜潴慲敧屘畃牲湥屴楂屮敒敬獡履睡⵳ⵣ癥湥⵴瑳敲浡搮汬਍㩃呜卆卜潴慲敧屘畃牲湥屴楂屮敒敬獡履睡⵳ⵣ潣浭湯搮汬਍㩃呜卆卜潴慲敧屘畃牲湥屴楂屮敒敬獡履睡⵳档捥獫浵⹳汤൬䌊尺䙔屓瑓牯条塥䍜牵敲瑮䉜湩剜汥慥敳慜獷挭灰猭此猭⸳汤൬䌊尺䙔屓瑓牯条塥䍜牵敲瑮䉜湩剜汥慥敳捜灰敲瑳㉟ㅟ⸰汤൬䌊尺䙔屓瑓牯条塥䍜牵敲瑮䉜湩剜汥慥敳汜扩畣汲搮汬਍㩃呜卆卜潴慲敧屘畃牲湥屴楂屮敒敬獡履決扩⸱汤൬䌊尺䙔屓瑓牯条塥䍜牵敲瑮䉜湩剜汥慥敳睜獡潴慲敧搮汬਍
```
Seems like someone tried to write `^C:\<blah>\o2ftool\x64\Release\vcpkg.applocal.log` as last line and accidentally wrote garbage instead. Now, who is writing to `write.1u.tlog` file?

**Comment by crusader-mike** [comment]
... and if you open said file in binary editor it looks like this:
![image](https://user-images.githubusercontent.com/22357016/56762516-a8a11e80-6765-11e9-8209-ef1805230350.png)

which means that writer for some reason decided to switch from UTF-8 (with BOM) to ASCII right in the middle of it.

**Comment by crusader-mike** [comment]
Looks like a bug in msbuild... [Here is](https://github.com/Microsoft/vcpkg/blob/4f7d4dc66f242a2b86ce38673c7dd9c32110257f/scripts/buildsystems/msbuild/vcpkg.targets#L85) place in vcpkg that adds lines to that file and [here is](https://github.com/Microsoft/msbuild/blob/master/src/Tasks/FileIO/WriteLinesToFile.cs#L19) related place in msbuild that selects encoding by default for `WriteLinesToFile` action. It looks like UTF-8 is selected by default and is never changed.

Any ideas how to fix or workaround this? I am a bit short on time -- can't wait for next MSVC2017 release...

**Comment by crusader-mike** [comment]
Ok... According to Process Monitor bogus lines are added by `applocal.ps1` which in turn is executed via `vcpkg.targets` through Exec command via line that look like this:
`C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe  -ExecutionPolicy Bypass -noprofile -File "c:\vcpkg\scripts\buildsystems\msbuild\applocal.ps1" "C:\<blah>\Debug\o2ftool.exe" "c:\vcpkg\installed\x64-windows\debug\bin" "x64\Debug\o2ftool.tlog\o2ftool.write.1u.tlog" "x64\Debug\vcpkg.applocal.log"`

i.e. powershell script ends up using wrong encoding to add data to `tlog` file...

**Comment by crusader-mike** [comment]
Anyway, I am too short on time to investigate intricacies of powershell's default encoding, but [this](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/add-content?view=powershell-6) page claims that default encoding is always `UTF8NoBOM`. Older versions seem to default to `system's active code page (usually ANSI)`. I am not sure how to properly fix this issue, but for me adding `-Encoding Unicode` to [this line](https://github.com/Microsoft/vcpkg/blob/4f7d4dc66f242a2b86ce38673c7dd9c32110257f/scripts/buildsystems/msbuild/applocal.ps1#L25) solved all problems.

**Comment by crusader-mike** [comment]
... you guys probably should review all places powershell is used having this problem with default encoding in mind

**Comment by JackBoosY** [comment]
Hi @crusader-mike, it seems that you want to create a new port support in vcpkg. And I don't know if there are any spaces or non-ASCII characters in your vcpkg path.
So I can't reproduce it now. Can you create a PR first and upload the port o2ftool?
Thanks.

**Comment by crusader-mike** [comment]
> it seems that you want to create a new port support in vcpkg.

@JackBoosY What? No!! vcpkg has a bug in logic that populates `*.1u.tlog` files -- it uses powershell script to append lines to the end of it and (depending on environment, I assume) powershell default encoding is either UTF-16 or UTF-8/ASCII. In latter case MSVC can't properly read this file and related project is always considered not up-to-date. Please, read carefully posts above -- they point at exact location of the problem.

> I don't know if there are any spaces or non-ASCII characters in your vcpkg path.

It doesn't matter... And no, vcpkg is in `c:\vcpkg`


> So I can't reproduce it now. 

Did you try using Windows 7?

**Comment by JackBoosY** [comment]
@crusader-mike I know what you mean, sorry.
It is correct in Win10 and I will check it again in Win7.

**Comment by crusader-mike** [comment]
@JackBoosY Can you attach your `tlog` file? Or confirm that `applocal.ps1` (located [here](https://github.com/Microsoft/vcpkg/blob/4f7d4dc66f242a2b86ce38673c7dd9c32110257f/scripts/buildsystems/msbuild/vcpkg.targets#L85)) actually gets executed via `powershell`? It appends few lines to `tlog` file -- I am curious about:
- encoding of data that already exists in that file
- what gets appended to said file using `applocal.ps1`
- and what encoding it gets appended with

**Comment by JackBoosY** [comment]
Here is my tlog:
[ConsoleApplication1.write.1u.tlog.txt](https://github.com/Microsoft/vcpkg/files/3125737/ConsoleApplication1.write.1u.tlog.txt)

**Comment by crusader-mike** [comment]
@JackBoosY Here is my `1u.tlog` file (open it in binary editor and note how encoding gets switched to ANSII/UTF-8 right in the middle):
[o2ftool.write.1u.tlog.zip](https://github.com/Microsoft/vcpkg/files/3128764/o2ftool.write.1u.tlog.zip)

And every time I press F7 I get smth like this in the output:
```
1>------ Build started: Project: o2ftool, Configuration: Debug x64 ------
1>o2ftool.vcxproj -> C:\<blah>\Debug\o2ftool.exe
========== Build: 1 succeeded, 0 failed, 2 up-to-date, 0 skipped ==========
```

Here is my `vcpkg.applocal.log` file (note that it's encoding is ASCII/UTF-8, not UTF-16):
[vcpkg.applocal.log.zip](https://github.com/Microsoft/vcpkg/files/3128774/vcpkg.applocal.log.zip)

Both of these files get populated by `scripts\buildsystems\msbuild\applocal.ps1` which gets executed like this (I can see this in process monitor):
```
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe  -ExecutionPolicy Bypass -noprofile -File "c:\vcpkg\scripts\buildsystems\msbuild\applocal.ps1" "C:\TFS\StorageX\Current\Bin\Debug\o2ftool.exe" "c:\vcpkg\installed\x64-windows\debug\bin" "x64\Debug\o2ftool.tlog\o2ftool.write.1u.tlog" "x64\Debug\vcpkg.applocal.log"
```

I ran this line manually from `Developer Command Prompt for VS 2017` and observed lines being added to tlog file in wrong encoding. So, I am 100% sure this is because my powershell default encoding is ASCII (or UTF-8). I don't know why -- maybe because my powershell version is too old:
```
PS C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
2      0      -1     -1
```

In any case -- it doesn't matter... If tlog file is expected to be in UTF-16 -- `applocal.ps1` script shouldn't assume that powershell's encoding is UTF-16, it should explicitly specify it (for example, by adding `-Encoding Unicode` to `Add-Content` command at [line 25](https://github.com/Microsoft/vcpkg/blob/4f7d4dc66f242a2b86ce38673c7dd9c32110257f/scripts/buildsystems/msbuild/applocal.ps1#L25)).

In addition to everything said so far -- note that your `1u.tlog` file contains duplicates. I get same thing from time to time, but not always -- looks like some sort of minor problem, you may want to look into it (I never had time to figure it out).

**Comment by JackBoosY** [comment]
Port related(all with x64-windows):
- aws-sdk-cpp
- cpprest
- libcurl
- zlib

I noticed that the library you are using is not under _vcpkg/installed/x64-windows/bin_, which may also cause this to happen.

**Comment by crusader-mike** [comment]
Yeah, they point to libraries copied to my `$(OutDir)` from `vcpkg/installed/x64-windows/[debug/]bin` -- aren't this supposed to be like this? So that if these files are outdated, copy step gets re-executed again...

I doubt this has anything to do with wrong encoding being used for appending data to `1u.tlog` files
