### ISSUE TITLE
Error: Building package boost-compatibility:x86-windows-static-custom failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Wings-Fantasy** [Microsoft/vcpkg#6183]
F:\C++工作空间\酷Q插件\coolq-cpp-sdk\vcpkg>vcpkg --vcpkg-root "F:\C++工作空间\酷Q插件\coolq-cpp-sdk\vcpkg" --triplet x86-windows-static-custom install boost-algorithm
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be built and installed:
    boost-algorithm[core]:x86-windows-static-custom
  * boost-array[core]:x86-windows-static-custom
  * boost-assert[core]:x86-windows-static-custom
  * boost-bind[core]:x86-windows-static-custom
  * boost-build[core]:x86-windows-static-custom
  * boost-compatibility[core]:x86-windows-static-custom
  * boost-concept-check[core]:x86-windows-static-custom
  * boost-config[core]:x86-windows-static-custom
  * boost-container[core]:x86-windows-static-custom
  * boost-container-hash[core]:x86-windows-static-custom
  * boost-conversion[core]:x86-windows-static-custom
  * boost-core[core]:x86-windows-static-custom
  * boost-detail[core]:x86-windows-static-custom
  * boost-exception[core]:x86-windows-static-custom
  * boost-function[core]:x86-windows-static-custom
  * boost-function-types[core]:x86-windows-static-custom
  * boost-functional[core]:x86-windows-static-custom
  * boost-fusion[core]:x86-windows-static-custom
  * boost-integer[core]:x86-windows-static-custom
  * boost-intrusive[core]:x86-windows-static-custom
  * boost-iterator[core]:x86-windows-static-custom
  * boost-modular-build-helper[core]:x86-windows-static-custom
  * boost-move[core]:x86-windows-static-custom
  * boost-mpl[core]:x86-windows-static-custom
  * boost-optional[core]:x86-windows-static-custom
  * boost-predef[core]:x86-windows-static-custom
  * boost-preprocessor[core]:x86-windows-static-custom
  * boost-range[core]:x86-windows-static-custom
  * boost-regex[core]:x86-windows-static-custom
  * boost-smart-ptr[core]:x86-windows-static-custom
  * boost-static-assert[core]:x86-windows-static-custom
  * boost-throw-exception[core]:x86-windows-static-custom
  * boost-tuple[core]:x86-windows-static-custom
  * boost-type-index[core]:x86-windows-static-custom
  * boost-type-traits[core]:x86-windows-static-custom
  * boost-typeof[core]:x86-windows-static-custom
  * boost-unordered[core]:x86-windows-static-custom
  * boost-utility[core]:x86-windows-static-custom
Additional packages (*) will be modified to complete this operation.
Starting package 1/38: boost-compatibility:x86-windows-static-custom
Building package boost-compatibility[core]:x86-windows-static-custom...
-- Using cached F:/C++工作空间/酷Q插件/coolq-cpp-sdk/vcpkg/downloads/boostorg-compatibility-boost-1.69.0.tar.gz
-- Using source at F:/C++工作空间/酷Q插件/coolq-cpp-sdk/vcpkg/buildtrees/boost-compatibility/src/ost-1.69.0-b809a8cf93
CMake Error at ports/boost-compatibility/portfile.cmake:13 (include):
  include could not find load file:

    F:/C++工作空间/酷Q插件/coolq-cpp-sdk/vcpkg/installed/x86-windows-static-custom/share/boost-vcpkg-helpers/boost-modular-headers.cmake
Call Stack (most recent call first):
  scripts/ports.cmake:71 (include)

Error: Building package boost-compatibility:x86-windows-static-custom failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-compatibility:x86-windows-static-custom
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by wangli28** [comment]
Hi @Wings-Fantasy, thanks for reporting this issue!
I found there are some Chinese characters in your vcpkg path. However, we have weekly support with it. Can you re-clone vcpkg in a non-Chinese path and try to install this port again?
Thanks.

**Comment by Downstream1998** [comment]
> Hi @Wings-Fantasy, thanks for reporting this issue!
> I found there are some Chinese characters in your vcpkg path. However, we have weekly support with it. Can you re-clone vcpkg in a non-Chinese path and try to install this port again?
> Thanks.

I met the same problem, I cloned vcpkg in D:\Program Files\, and get the same error messaging while installing boost.

**Comment by Wings-Fantasy** [comment]
> > Hi @Wings-Fantasy, thanks for reporting this issue!
> > I found there are some Chinese characters in your vcpkg path. However, we have weekly support with it. Can you re-clone vcpkg in a non-Chinese path and try to install this port again?
> > Thanks.
> 
> I met the same problem, I cloned vcpkg in D:\Program Files, and get the same error messaging while installing boost.

There can be no white space characters in the path

**Comment by Wings-Fantasy** [comment]
> Hi @Wings-Fantasy, thanks for reporting this issue!
> I found there are some Chinese characters in your vcpkg path. However, we have weekly support with it. Can you re-clone vcpkg in a non-Chinese path and try to install this port again?
> Thanks.

Thank you very much, I moved the path to "F:\" and can now use it.

**Comment by wangli28** [comment]
Thanks for your feedback, I am closing this issue for now.
