### ISSUE TITLE
'mysql/mysql.h': No such file or directory

### ISSUE THREAD

**Issue by OlafvdSpek** [Microsoft/vcpkg#619]
The vcpkg include dir doesn't appear to be included.. but I've no idea why.
Is this how it's supposed to look?

![vcpkg](https://cloud.githubusercontent.com/assets/2218936/22481849/f67ef366-e7f6-11e6-8b34-befb2be1cbbd.PNG)

**Comment by ras0219-msft** [comment]
That looks correct; we unfortunately at the moment do not show up in the Inherited Values list. I've talked to some of our MSBuild people about how we can improve this (and a few other lower priority issues), but it hasn't been implemented yet.

I pushed some more diagnostics in 8b21933, could you update to (equal or above) that version and rebuild your project with verbosity normal? You should get two extra lines in the output, but only when building with normal or above verbosity:
```
1>------ Build started: Project: Project1, Configuration: Debug Win32 ------
1>Build started 1/31/2017 5:04:50 PM.
1>Target InitializeBuildStatus:
1>  Creating "Debug\Project1.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.


1>Target VcpkgTripletSelection:
1>  Using triplet "x86-windows" from "D:\src\vcpkg\installed\x86-windows\"


1>Target ClCompile:
1>  All outputs are up-to-date.
1>  Source1.cpp
1>Target Link:
1>  Project1.vcxproj -> C:\Users\roschuma\Documents\Visual Studio 2017\Projects\Project1\Debug\Project1.exe
1>  Project1.vcxproj -> C:\Users\roschuma\Documents\Visual Studio 2017\Projects\Project1\Debug\Project1.pdb (Partial PDB)
1>Target FinalizeBuildStatus:
1>  Deleting file "Debug\Project1.tlog\unsuccessfulbuild".
1>  Touching "Debug\Project1.tlog\Project1.lastbuildstate".
1>
1>Build succeeded.
1>
1>Time Elapsed 00:00:00.95
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```
Assuming those values are what you expect, the next possibility is that `%(AdditionalIncludeDirectories)` has been overridden somewhere that the IDE doesn't report.

**Comment by OlafvdSpek** [comment]
Got a warning on the first build, but not on the second. Posting here just in case:
```
Build succeeded.

       "C:\vc\vcpkg\toolsrc\dirs.proj" (default target) (1) ->
       "C:\vc\vcpkg\toolsrc\vcpkg\vcpkg.vcxproj" (Build target) (2:2) ->
       (Link target) ->
         C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(638,5): warning MSB5018: Fa
       iled to delete the temporary file "C:\Users\Olaf\AppData\Local\Temp\tmp94148a16f5b04a1b8236196fa313d1e6.tmp". Th
       e process cannot access the file 'C:\Users\Olaf\AppData\Local\Temp\tmp94148a16f5b04a1b8236196fa313d1e6.tmp' beca
       use it is being used by another process. [C:\vc\vcpkg\toolsrc\vcpkg\vcpkg.vcxproj]

    1 Warning(s)
    0 Error(s)
```

**Comment by ras0219-msft** [comment]
Ok, to sanity check that the file is where it's expected, could you run
```
PS D:\src\vcpkg> vcpkg owns mysql.h
libmysql:x86-windows: x86-windows/include/mysql.h
```
I have an outdated version of `libmysql` (5.7.16) which put the headers in an incorrect location.
```
PS D:\src\vcpkg> vcpkg list mysql
libmysql:x86-windows        5.7.16           A MySQL client library for C development.
```
This was fixed in 5.7.17.

Assuming that you have 5.7.17 and `x86-windows/include/mysql/mysql.h`, could you then run MSBuild in _detailed_ output mode, locate the actual CL.EXE invocation for your project, and confirm that `/IC:\vc\vcpkg\installed\x86-windows\include` is put on the command line?

**Comment by OlafvdSpek** [comment]
```
PS C:\vc\vcpkg> ./vcpkg owns mysql.h
libmysql:x86-windows: x86-windows/include/mysql/mysql.h
PS C:\vc\vcpkg> ./vcpkg list mysql
libmysql:x86-windows        5.7.17           A MySQL client library for C development.
```

**Comment by ras0219-msft** [comment]
Glad to help! Really happy to see warnings being fixed the right way 😄.
