### ISSUE TITLE
PCL vcpkg integrate install didn't work

### ISSUE THREAD

**Issue by jmw992** [microsoft/vcpkg#6190]
I am trying to get PCL 1.91 to work I ran `vcpkg install pcl:x64-windows-static` and it built no problem.

Next I ran `vcpkg integrate install`, again it output
```
All MSBuild C++ projects can now #include any installed libraries.
Linking will be handled automatically.
Installing new libraries will make them instantly available.

CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=D:/vcpkg/scripts/buildsystems/vcpkg.cmake"
```
I made a test project in visual studio and none of the PCL libraries are included, and when I take I search through the .vcxproj file I don't see anything pop up for PCL or vcpkg.

I had tried a fix from #2323 where I updated vcpkg.targets file (scripts\buildsystems\msbuild\vcpkg.targets) by changing "x86-windows" to "x86-windows-static" and "x64-windows" to "x64-windows-static".  But it did not fix the issue.

I've attached the zip of the project file in case it is any help.
[mcube.zip](https://github.com/Microsoft/vcpkg/files/3109465/mcube.zip)

The only tricky thing with I can come up with about my situation is I've placed the vcpkg in my D drive as all of the PCL libraries require about 40 gb of memory.  If there's any other diagnostic info you'd like I'm happy to help

**Comment by JackBoosY** [comment]
Hi @jmw992, when using static libraries, we must manually modify the. vcxproj file and add the following code:
```
<PropertyGroup Label="Globals">
 <!-- .... --> 
<VcpkgTriplet Condition="'$(Platform)'=='Win32'">x86-windows-static</VcpkgTriplet>
<VcpkgTriplet Condition="'$(Platform)'=='x64'">x64-windows-static</VcpkgTriplet>
</PropertyGroup>
```
Here is the document: [Vcpkg updates: Static linking is now available](https://devblogs.microsoft.com/cppblog/vcpkg-updates-static-linking-is-now-available/)

**Comment by Neumann-A** [comment]
If you want a simple VS tab to select the triplet you probably want to try out #4361.

**Comment by jmw992** [comment]
@JackBoos So I added those lines and unfortunately the linking still does not work.  My code looks like the following
```
  <PropertyGroup Label="Globals">
    <VCProjectVersion>15.0</VCProjectVersion>
    <ProjectGuid>{7972A067-45AC-44D6-9B4E-DF3628651D62}</ProjectGuid>
    <RootNamespace>mcube</RootNamespace>
    <WindowsTargetPlatformVersion>10.0.17763.0</WindowsTargetPlatformVersion>
    <VcpkgTriplet Condition="'$(Platform)'=='Win32'">x86-windows-static</VcpkgTriplet>
    <VcpkgTriplet Condition="'$(Platform)'=='x64'">x64-windows-static</VcpkgTriplet>
  </PropertyGroup>
```
[vcpkgTest.zip](https://github.com/Microsoft/vcpkg/files/3112974/vcpkgTest.zip)

@Neumann-A I apologize I'm not seeing the action required to get that vcpkg tab on VS property page from that link.  Is there a vcpkg command with MSBUILD / CMAKE that I need to use for that?  So far I have built the projects just using visual studio's new project command.

**Comment by Neumann-A** [comment]
@jmw992 I just rebased #4361 and fixed the merge issues. If you want to use #4361 you have to merge it into your repo of vcpkg and remove integration first (This might not be required). Than bootstrap/recompile and reintegrate vcpkg again. After that the property page in Visual Studio should be visible. You can check %LOCALAPPDATA%\vcpkg\. There should be 4 files there after the integration  (insted of 3).

**Comment by jmw992** [comment]
Thanks that fixed it for me

**Comment by Neumann-A** [comment]
@jmw992 please close the issue if it is solved

**Comment by JackBoosY** [comment]
@Neumann-A 
I will close this issue after your PR merge.
Thanks.

**Comment by JackBoosY** [comment]
Fixed.
