### ISSUE TITLE
vcpkg install verbose output

### ISSUE THREAD

**Issue by alcroito** [Microsoft/vcpkg#6191]
Hi,

Is there a verbose option when building a package using vcpkg install? If not, is there some workaround to print out the build process of the package (so compilation commands, etc.)?

**Comment by tan-wei** [comment]
You can find some log files under `VCPKG_ROOT/buildtrees/xxx`, I think they are verbose enough.

**Comment by PhoebeHui** [comment]
@tan-wei, thanks for posting the helpful message!

**Comment by bsergean** [comment]
It would be very good to have this, to know what files gets built etc... right now I am trying to build my library, and it gets built 'very fast', which makes me wonder if anything is happening at all.

**Comment by bsergean** [comment]
In a way that would be equivalent to a --progress.

**Comment by bsergean** [comment]
I had to google this ... and remember I had asked this a while ago. I still think a command line option to see what's going on would be quite helpful.

**Comment by soroush** [comment]
Google took me here. Indeed a command-line option like `--verbose` would be very beneficial. It just needs to redirect stdout and stderr both to files and stdout stderr. I am not sure how `tee`-like features work on Windows, though it must be possible.

**Comment by technic** [comment]
Build tools like ninja can report some sort of progress. An option to redirecting its output to stdout (in addition to log file) can be useful. Please reopen

**Comment by liudonghua123** [comment]
I would like to vote for `--verbose` option. 

I just tried to install `boost boost:x64-windows` and it hangs on `boost-fiber` for almost a few hours, I want to know whether the install process is dead or not and what the installation is doing.

**Comment by sryze** [comment]
+1 for `--verbose`, I know that we can look at the build logs but adding a flag to vcpkg command is way easier than opening some logs. I don't see why this would be a problem to implement to be honest (and IMO it should have been implemented from the start).

**Comment by RealLitb** [comment]
If you run vcpkg in Docker, it's a PITA to read the log messages after the fact. A --verbose would really be helpful here.

**Comment by jg185366** [comment]
There is an undocumented `--debug` option that can be used as an approximation for `--verbose`. It seems like this flag was intended to be used for development of `vcpkg` itself, but I have found it useful for finding where `vcpkg install` gets stuck.

**Comment by JohnstonJ** [comment]
+1 for reopening this.

**Comment by pitrou** [comment]
@jimwang118 @autoantwort @tan-wei @BillyONeal Could any of you please reopen this, especially in lite of https://github.com/microsoft/vcpkg/issues/6191#issuecomment-1536002960 ?

**Comment by BillyONeal** [comment]
@pitrou I don't see a cause of action here to reopen. There would need to be at minimum a description of which specific information desired and how such a switch would work. The requests in the original are for information vcpkg does not have and for which building instrumentation to collect would be extremely expensive if it's practical at all.

**Comment by pitrou** [comment]
@BillyONeal From my comment at https://github.com/microsoft/vcpkg/issues/30622#issuecomment-3197542830 we can see that the `vcpkg_execute_required_process` function is involved in the call stack.

The message that instructs the user to read some log files is actually [generated by that function](https://github.com/microsoft/vcpkg/blob/fae69ad1f4d77ef5b28f82e7c16e22e356e897c6/scripts/cmake/vcpkg_execute_required_process.cmake#L127-L133), so I'm not sure why it would be impossible to change that to print out the logs directly, at least when certain option or environment variable is enabled.

```
-- Configuring amd64-windows-static-md-release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/vcpkg/buildtrees/boost-headers/amd64-windows-static-md-release-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\boost-headers\config-amd64-windows-static-md-release-rel-CMakeCache.txt.log
      C:\vcpkg\buildtrees\boost-headers\config-amd64-windows-static-md-release-rel-CMakeConfigureLog.yaml.log
      C:\vcpkg\buildtrees\boost-headers\config-amd64-windows-static-md-release-out.log
Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:269 (vcpkg_execute_required_process)
  installed/x64-windows/share/vcpkg-boost/boost-install.cmake:55 (vcpkg_cmake_configure)
  ports/boost-headers/portfile.cmake:12 (boost_configure_and_install)
  scripts/ports.cmake:191 (include)
error: building boost-headers:amd64-windows-static-md-release failed with: BUILD_FAILED
```

**Comment by pitrou** [comment]
Ok, I've opened https://github.com/microsoft/vcpkg/issues/46976 since it seems this issue wasn't going anywhere.

**Comment by BillyONeal** [comment]
> The message that instructs the user to read some log files is actually [generated by that function](https://github.com/microsoft/vcpkg/blob/fae69ad1f4d77ef5b28f82e7c16e22e356e897c6/scripts/cmake/vcpkg_execute_required_process.cmake#L127-L133), so I'm not sure why it would be impossible to change that to print out the logs directly, at least when certain option or environment variable is enabled.

The original issue says 'compilation commands' which are in the build system we are invoking, not invoking ourselves.
