### ISSUE TITLE
Live555 won't download

### ISSUE THREAD

**Issue by F0I0l0I0P** [Microsoft/vcpkg#6194]

**Comment by Voskrese** [comment]
all ok

**Comment by F0I0l0I0P** [comment]
Hi I'm getting errors building with
vcpkg install live555:x86-windows --head

Shouldn't
http://www.live555.com/live.2019.03.06.tar.gz
be
http://live555.com/liveMedia/public/live.2019.03.06.tar.gz

I was also reading somewhere where someone was saying using the --head flag should make it use live.latest.tar.gz is that right?

The following packages will be built and installed:
    live555[core]:x86-windows (from HEAD)
Starting package 1/1: live555:x86-windows
Building package live555[core]:x86-windows from HEAD...
live555 cannot currently be built dynamically. Building static instead.
-- Downloading http://www.live555.com/live.2019.03.06.tar.gz...
-- Downloading http://www.live555.com/live.2019.03.06.tar.gz... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:172 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/live555/portfile.cmake:11 (vcpkg_download_distfile)
  scripts/ports.cmake:71 (include)


Error: Building package live555:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: live555:x86-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by Cheney-W** [comment]
Thanks for report this issue. It has been fixed by PR:https://github.com/Microsoft/vcpkg/pull/6176 .
