### ISSUE TITLE
[openssl] compile failed in 32-bit OS

### ISSUE THREAD

**Issue by sdcb** [Microsoft/vcpkg#620]
This failure is caused by perl in this command:

> C:\_\3rd\vcpkg>C:/_/3rd/vcpkg/downloads/tools/perl/perl/bin/perl.exe Configure enable-static-engine enable-capieng no-asm no-ssl2 VC-WIN32 --prefix=C:/_/3rd/vcpkg/packages/openssl_x86-windows --openssl dir=C:/_/3rd/vcpkg/packages/openssl_x86-windows

And output message is:

> 该版本的 C:\_\3rd\vcpkg\downloads\tools\perl\perl\bin\perl.exe 与您运行的 Windows 版本不兼容。请查看
> 计算机的系统信息，了解是否需要 x86 (32 位)或 x64 (64 位)版本的程序，然后联系软件发布者。

I think we need to use a 32-bit perl in 32-bit windows.

**Comment by alexkaratarakis** [comment]
Good catch. Switched to the 32-bit version. Thanks!
