### ISSUE TITLE
GEOS builds succesfully, can't include files in project

### ISSUE THREAD

**Issue by ssohin** [Microsoft/vcpkg#6200]
Package: GEOS

Windows 10 
VS2019
Package Version:
`geos:x64-windows 3.6.3-3          Geometry Engine Open Source`

Issue: 

GEOS builds successfully, but I can't include it in my CMake project. I also tried using VS2017.
I was successfully able to build and include the sqlite3 by following the vcpkg example tutorial, but when I try to do the same for geos, VS gives me this  error:

` CMake Warning at C:/Users/username/source/repos/vcpkg/scripts/buildsystems/vcpkg.cmake: (_find_package):`

`
By not providing "FindGEOS.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "GEOS", but
CMake did not find one.`

`
Could not find a package configuration file provided by "GEOS" with any of
the following names:`

`
GEOSConfig.cmake
geos-config.cmake
`

`
Add the installation prefix of "GEOS" to CMAKE_PREFIX_PATH or set
"GEOS_DIR" to a directory containing one of the above files.  If "GEOS"
provides a separate development package or SDK, be sure it has been
installed.`

**Comment by Neumann-A** [comment]
Not a vcpkg issue. 
As it seems from the sources of geos @ https://git.osgeo.org/gitea/geos/geos.git it is not exporting any targets. As such you have to provide your own FindGEOS.cmake or ask the maintainers upstream to export their library via cmake.

**Comment by ssohin** [comment]
Thanks, I wanted to confirm that.
