### ISSUE TITLE
How to get latest pcre version?

### ISSUE THREAD

**Issue by kinglezhuang** [Microsoft/vcpkg#6204]
Currently, we just can search pcre 8.41 in vcpkg, we want to get latest verison, how to do?

**Comment by Neumann-A** [comment]
go into the pcre portfile (ports/pcre/portfile.cmake) and replace `set(PCRE_VERSION 8.41)` with the version you want you probably also want to update the control file. Maybe also submit a PR to update the version within vcpkg

**Comment by kinglezhuang** [comment]
Got it. thanks

**Comment by PhoebeHui** [comment]
@Neumann-A, thank you for posting the answer!
