### ISSUE TITLE
Add matio

### ISSUE THREAD

**Issue by traversaro** [Microsoft/vcpkg#621]
It would be great to have a port of the matio library ( https://sourceforge.net/projects/matio/ ). 

Debian package : https://packages.debian.org/source/sid/libmatio . 
Homebrew formula : https://github.com/Homebrew/homebrew-science/blob/master/libmatio.rb .

**Comment by atkawa7** [comment]
@traversaro see #1393

**Comment by atkawa7** [comment]
@ras0219-msft Could you close this?

**Comment by traversaro** [comment]
Thanks a lot @atkawa7 !
