### ISSUE TITLE
About priority of $(VcpkgRoot) .

### ISSUE THREAD

**Issue by shihaonan369** [microsoft/vcpkg#6213]
After export package to nuget package and remove it from vcpkg, dependencies will invalid.
I check the vcpkg.targets which in nuget package,  the following code cause $(VcpkgRoot) set to install path of vcpkg.
`<VcpkgRoot Condition="'$(VcpkgRoot)' == ''">$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), .vcpkg-root))\installed\$(VcpkgTriplet)\</VcpkgRoot>`
Is that a feature of vcpkg?
In my case,  I hope to use libs and headers which in nuget package, so i create a pull request #6214 , include a bug fix that resolve import vcpkg.targets failure.

**Comment by PhoebeHui** [comment]
@shihaonan369, the PR has been merged, please get vcpkg latest source and try again.
