### ISSUE TITLE
mongo-c-driver installation failure on centos7.3 x64 with g++8.2.1

### ISSUE THREAD

**Issue by lordoffox** [microsoft/vcpkg#6219]
[root@localhost vcpkg]# ./vcpkg install mongo-c-driver
The following packages will be built and installed:
    mongo-c-driver[core]:x64-linux
Starting package 1/1: mongo-c-driver:x64-linux
Building package mongo-c-driver[core]:x64-linux...
-- Using cached /home/vcpkg/downloads/mongodb-mongo-c-driver-1.13.0.tar.gz
-- Using source at /home/vcpkg/buildtrees/mongo-c-driver/src/1.13.0-9145f39841
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:202 (message):
    Command failed: /home/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake;--build;.;--config;Debug;--target;install;--;-v
    Working Directory: /home/vcpkg/buildtrees/mongo-c-driver/x64-linux-dbg
    See logs for more information:
      /home/vcpkg/buildtrees/mongo-c-driver/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/mongo-c-driver/portfile.cmake:36 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package mongo-c-driver:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: mongo-c-driver:x64-linux
  Vcpkg version: 2018.11.23-unknownhash

Additionally, attach any relevant sections from the log files above.

[root@localhost vcpkg]# tail /home/vcpkg/buildtrees/mongo-c-driver/install-x64-linux-dbg-out.log
[212/213] : && /opt/rh/devtoolset-8/root/usr/bin/cc -fPIC -g  -rdynamic src/libmongoc/CMakeFiles/mongoc-stat.dir/__/tools/mongoc-stat.c.o  -o src/libmongoc/mongoc-stat  -Wl,-rpath,/home/vcpkg/buildtrees/mongo-c-driver/x64-linux-dbg/src/libmongoc:/home/vcpkg/buildtrees/mongo-c-driver/x64-linux-dbg/src/libbson src/libmongoc/libmongoc-1.0.so.0.0.0 /home/vcpkg/installed/x64-linux/debug/lib/libssl.a /home/vcpkg/installed/x64-linux/debug/lib/libcrypto.a -lrt -lresolv /home/vcpkg/installed/x64-linux/debug/lib/libz.a src/libbson/libbson-1.0.so.0.0.0 -lrt -lm -pthread && :
FAILED: src/libmongoc/mongoc-stat 
: && /opt/rh/devtoolset-8/root/usr/bin/cc -fPIC -g  -rdynamic src/libmongoc/CMakeFiles/mongoc-stat.dir/__/tools/mongoc-stat.c.o  -o src/libmongoc/mongoc-stat  -Wl,-rpath,/home/vcpkg/buildtrees/mongo-c-driver/x64-linux-dbg/src/libmongoc:/home/vcpkg/buildtrees/mongo-c-driver/x64-linux-dbg/src/libbson src/libmongoc/libmongoc-1.0.so.0.0.0 /home/vcpkg/installed/x64-linux/debug/lib/libssl.a /home/vcpkg/installed/x64-linux/debug/lib/libcrypto.a -lrt -lresolv /home/vcpkg/installed/x64-linux/debug/lib/libz.a src/libbson/libbson-1.0.so.0.0.0 -lrt -lm -pthread && :
src/libmongoc/libmongoc-1.0.so.0.0.0：对‘dlsym’未定义的引用
src/libmongoc/libmongoc-1.0.so.0.0.0：对‘dlerror’未定义的引用
src/libmongoc/libmongoc-1.0.so.0.0.0：对‘dladdr’未定义的引用
src/libmongoc/libmongoc-1.0.so.0.0.0：对‘dlopen’未定义的引用
src/libmongoc/libmongoc-1.0.so.0.0.0：对‘dlclose’未定义的引用
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by sbrown89** [comment]
Same issue on Fedora 31
[224/225] : && /usr/lib64/ccache/cc -fPIC -g  -rdynamic src/libmongoc/CMakeFiles/mongoc-stat.dir/__/tools/mongoc-stat.c.o  -o src/libmongoc/mongoc-stat  -Wl,-rpath,/media/psf/lib/vcpkg/buildtrees/mongo-c-driver/x64-linux-dbg/src/libmongoc:/media/psf/lib/vcpkg/buildtrees/mongo-c-driver/x64-linux-dbg/src/libbson src/libmongoc/libmongoc-1.0.so.0.0.0 /media/psf/lib/vcpkg/installed/x64-linux/debug/lib/libssl.a /media/psf/lib/vcpkg/installed/x64-linux/debug/lib/libcrypto.a -lrt -lresolv /media/psf/lib/vcpkg/installed/x64-linux/debug/lib/libz.a src/libbson/libbson-1.0.so.0.0.0 -pthread && :
FAILED: src/libmongoc/mongoc-stat 
: && /usr/lib64/ccache/cc -fPIC -g  -rdynamic src/libmongoc/CMakeFiles/mongoc-stat.dir/__/tools/mongoc-stat.c.o  -o src/libmongoc/mongoc-stat  -Wl,-rpath,/media/psf/lib/vcpkg/buildtrees/mongo-c-driver/x64-linux-dbg/src/libmongoc:/media/psf/lib/vcpkg/buildtrees/mongo-c-driver/x64-linux-dbg/src/libbson src/libmongoc/libmongoc-1.0.so.0.0.0 /media/psf/lib/vcpkg/installed/x64-linux/debug/lib/libssl.a /media/psf/lib/vcpkg/installed/x64-linux/debug/lib/libcrypto.a -lrt -lresolv /media/psf/lib/vcpkg/installed/x64-linux/debug/lib/libz.a src/libbson/libbson-1.0.so.0.0.0 -pthread && :
/usr/bin/ld: src/libmongoc/libmongoc-1.0.so.0.0.0: undefined reference to `dlsym'
/usr/bin/ld: src/libmongoc/libmongoc-1.0.so.0.0.0: undefined reference to `dlerror'
/usr/bin/ld: src/libmongoc/libmongoc-1.0.so.0.0.0: undefined reference to `dladdr'
/usr/bin/ld: src/libmongoc/libmongoc-1.0.so.0.0.0: undefined reference to `dlopen'
/usr/bin/ld: src/libmongoc/libmongoc-1.0.so.0.0.0: undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by tosone** [comment]
https://github.com/mongodb/mongo-c-driver/blob/debian/1.15.1-1/src/libmongoc/CMakeLists.txt#L675 should be like this

``` bash
target_link_libraries (mongoc-stat mongoc_shared ${CMAKE_DL_LIBS})
```

I have no idea this bug belongs to `mongo-c-driver` or `vcpkg`.

Want some help.

**Comment by NancyLi1013** [comment]
Hi @lordoffox 
Sorry for the late reply.
Have you solved this issue ?
