### ISSUE TITLE
SFML fails to install

### ISSUE THREAD

**Issue by degski** [microsoft/vcpkg#6220]
This is the same issue as issue #5869 .

    CMake Error: Problem with archive_write_header(): Can't create ''
    CMake Error: Current file: SFML-2.5.1/extlibs/libs-osx/Frameworks/FLAC.framework/FLAC
    CMake Error: Problem extracting tar: Y:/vcpkg/downloads/SFML-SFML-2.5.1.tar.gz

@vicroms @ras0219-msft @Chingyat It appears this is an [active CMake issue](https://gitlab.kitware.com/cmake/cmake/issues/19102). So, it's related to enabling UTF-8 system-wide on Win10-1809 ~~(I think I have that, will check)~~ Well, not totally true, I **did** have it, but in-voluntarily, [see](https://gitlab.kitware.com/cmake/cmake/issues/19102#note_558431) (observe the 'Beta', Whiskey Tango Foxtrot), and yes, it does fix the problem (for now, until CMake gets fixed).

The above also fixes issue #5869 .

**Comment by degski** [comment]
@wangli28 [Tick box Beta: Use Unicode UTF-8 for worldwide language support in intl.cpl](https://gitlab.kitware.com/cmake/cmake/issues/19102#note_558431) on Win10-Home-x64-1809-17763.437, reboot and try and install a package with sym-links in the source code [protobuf, SFML, but there will surely be others]. It's a beta-feature in Windows and/or CMake possibly needs fixing, it's not a vcpkg-problem.

**Comment by Voskrese** [comment]
`COMMAND ${CMAKE_COMMAND} -E env LANG=en_US.UTF-8 -E tar` ?

`env LANG=en_US.UTF-8 abiword &`
or
`export LC_ALL=en_US.UTF-8`

**Comment by Voskrese** [comment]
```
cmake -E env LANG=UTF-8 tar xf harfbuzz-2.3.1.tar.gz
tar: can't create symlink 'harfbuzz-2.3.1/README' to 'README.md': No such file or directory

cmake -E env LC_ALL=en_US.UTF-8 tar xf harfbuzz-2.3.1.tar.gz
tar: can't create symlink 'harfbuzz-2.3.1/README' to 'README.md': No such file or directory
```

```
cmake -E tar xf harfbuzz-2.3.1.tar.gz
cmake -E tar: warning: skipping symbolic link "harfbuzz-2.3.1/README" -> "README.md".

`locale RU+EN`

```
chcp
Текущая кодовая страница: 866
```

```

**Comment by JackBoosY** [comment]
Same with #6448 #6564.

**Comment by PhoebeHui** [comment]
Duplicated to issue https://github.com/Microsoft/vcpkg/issues/5951.
