### ISSUE TITLE
sdl2-mixer in release configuration link to sdl2d

### ISSUE THREAD

**Issue by ShadowTeolog** [Microsoft/vcpkg#6223]
just installed sdl2-mixer release library after build linked with debug version SDL2. 
This result "dll not found exception" for release build of final program using this library.
Possible result of a9979e3f30a30d768cb600b6cb8851b4da7ec92e commit,  this commit fixes all sdl2 dependent modules debug configuration link with release SDL2.dll, now we have inversion.

**Comment by Neumann-A** [comment]
same issue as #6152
solved by #6152 or #6199

**Comment by ShadowTeolog** [comment]
Yes, #6199 fixes it
