### ISSUE TITLE
Using proxy behind corporate firewall

### ISSUE THREAD

**Issue by markiemarkus** [microsoft/vcpkg#6227]
fresh windows 10 machine.
vs 2019 in place
cmake 3.1.4 installed
vcpkg installed and integrated
vckpg search sqlite       - works fine
vckpg install sqlite3
fails due to ssl error because of the proxy

tried 
netsh winhttp set proxy "http://machine\user@password:proxyhost:port"
netsh winhttps set proxy "http://machine\\user@password:proxyhost:port"
set http_proxy = "http://machine\user@password:proxyhost:port"
set https_proxy ="https://machine\\user@password:proxyhost:port"

no luck

any other options?

**Comment by markiemarkus** [comment]
tried the following where using "proxyhost:port"
http://woshub.com/using-powershell-behind-a-proxy/

New error

-- Downloading https://sqlite.org/2019/sqlite-amalgamation-3270200.zip... Failed. Status: 4;"A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision."
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:172 (message):

after which talks about https_proxy and http_proxy again

**Comment by pratikpc** [comment]
https://github.com/Microsoft/vcpkg/issues/125
CMake download uses BITS so you need to set Proxy via IE

**Comment by markiemarkus** [comment]
> #125
> See if that helps?

Hi
#125 does not help, because I have already downloaded cmake and installed that without issue

**Comment by markiemarkus** [comment]
as a temporary workaround I can manually download the zip, drop it into the downloads folder and install from that point on

**Comment by wangli28** [comment]
Hi @markiemarkus, thanks for posting this issue. I can't reproduce this issue locally, does the issue persist?

**Comment by wangli28** [comment]
Please open a new issue if this is still a problem for you.

**Comment by cbruegg** [comment]
This is still a problem :/

**Comment by LilyWangL** [comment]
@cbruegg If this issue is still exist, could you open a new issue to submit this problem?
