### ISSUE TITLE
[ECM] wrong information printed

### ISSUE THREAD

**Issue by drdanz** [microsoft/vcpkg#6228]
After `vcpkg install ecm`, this information is printed:

```
The package ecm:x64-windows provides CMake targets:

    find_package(find-modules CONFIG REQUIRED)
    # Note: 8 target(s) were omitted.
    target_link_libraries(main PRIVATE EGL::EGL X11::XCB GLIB2::GLIB2 Sasl2::Sasl2)

    find_package(modules CONFIG REQUIRED)
    target_link_libraries(main PRIVATE mylib mylib ${module_name}::${ecm_fpwc_comp})
```

This is completely wrong, if I understand correctly, `print_cmake_information` looks for `add_library` in all the cmake files in share, and these prints come from the `FindXXX.cmake` files offered by the library.

**Comment by traversaro** [comment]
I guess this can be solved by adding a custom `usage` file in the ECM port (like for example in https://github.com/microsoft/vcpkg/blob/a3a6530631df905eb5c0e26d0b20d7d548e0c465/ports/librdkafka/usage), but I could not find any vcpkg docs on these type of files.

**Comment by JackBoosY** [comment]
Hi @drdanz, thanks for reporting this issue!
I've added usage to ecm, please update vcpkg and rebuild ecm.

Thanks.
