### ISSUE TITLE
[geotrans] windows endian issue

### ISSUE THREAD

**Issue by treigilbert** [microsoft/vcpkg#6230]
[geotrans] compiles and installs correctly on windows, but throws an error when reading the egm96.grd data file for conversions.

Solved by defining LITTLE_ENDIAN for read_binary to swap bytes.

In port CMakeLists.txt file add_definitions(-DLITTLE_ENDIAN)

I added it at this location:
if(WIN32)
    if (BUILD_SHARED_LIBS)
        add_definitions(
            -DMSP_CCS_EXPORTS
            -D_USRDLL
        )
    endif()
    add_definitions(-D_CRT_SECURE_NO_WARNINGS)
    add_definitions(-DLITTLE_ENDIAN)
else()
    find_package(Threads REQUIRED)
    target_link_libraries(MSPdtcc PRIVATE Threads::Threads ${CMAKE_DL_LIBS})
endif()

**Comment by treigilbert** [comment]
To do coordinate conversions, [geotrans] loads data files at runtime. For my install the data files are copied to vcpkg/installed/x64-windows/share/geotrans/data/ when vcpkg installs geotrans. Geotrans locates the files using an environment variable set to that path. At runtime on Windows x64, geotrans throws an error when checking that the loaded data files values are valid. [geotrans] compiles and installs in vcpkg, compiling and linking programs with geotrans works fine, running the programs throws an error during geotrans initialization when a coordinate conversion is called. Adding add_definitions(-DLITTLE_ENDIAN) to the CMakeLists.txt fixed the issue for my install.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
