### ISSUE TITLE
Export requires x86 build !!

### ISSUE THREAD

**Issue by chris1248** [microsoft/vcpkg#6232]
I built (or installed) a package for x64-windows called gdal.
I was very suprised to see vcpkg build with no errors, and very pleased to see gdal build successfully with all those millions of dependencies.
Way to go guys!!!!

But I went to export my work and ran into this error:

c:\code\tools\vcpkg>vcpkg export gdal --7zip
The following packages need to be built:
    gdal:x86-windows
There are packages that have not been built.
To build them, run:
    vcpkg install gdal:x86-windows

No No No. We aren't supporting Win32 and never will build this for Win32 in a million gazillion years. 
I expect this feature to work, not get bogged down in a requirement that I don't have nor want.

**Comment by Voskrese** [comment]
`vcpkg export gdal:x64-windows --7zip` ?

> to the x86 platform, everything is in open source, we are waiting for a port from you for this platform

**Comment by chris1248** [comment]
Great that works. Why isn't this feature documented? I had to go out to stackoverflow to find out where to start with this undocumented feature.

**Comment by Voskrese** [comment]
x86 platform defaults if not configured another platform
and export the platform you want, which is configured via triplet

`vcpkg export gdal:x8088-windows-3.1 --7zip` )

**Comment by PhoebeHui** [comment]
@chris1248, thank you for posting this issue!

It mentioned in https://github.com/microsoft/vcpkg/blob/master/docs/specifications/export-command.md 
See example in part ii. User has a vcpkg root that works and wants to share it.

**Comment by PhoebeHui** [comment]
Also see blog https://blogs.msdn.microsoft.com/vcblog/2017/05/03/vcpkg-introducing-export-command/
