### ISSUE TITLE
Long time eco system strategy

### ISSUE THREAD

**Issue by Fleischner** [microsoft/vcpkg#6233]
Open for discussion:

1) Continue to increase library count to create a position of strength
2) Create a documentation page that shows library conformance status with the vcpkg proposed packaging rules
3) Cooperate with cmake team to push features for better integration into an package management system
4) Community clean up builds and try to push changes upstream. Use position of strength to 'blaim' non-conformant behavior 
5) Find a proper way to early embed module support, to prevent competitor managers that could split the community
6) Continue to evolve CI, port tests, and custom checkers to find remaining issues
7) At this stage it might become feasible to get the issue count low (Since January it seems to be already stabilized after continuously growing over the last year. Great work!) But still a frighteningly large amount of work is wasted on fixing recurrent issues.
8) With all libraries in one place, cross platform support and a working tool-chain infrastructure, Conan could start to cache vcpkg build results, leading to an unified infrastructure for source build, and binary distributions. (Assuming vs tooling supports all major three compilers at that time) 
8) With all libraries in one place, community and SG15 can focus on analyzing the required set of features, to either evolve cmake or to create a sane replacement
9) Cooperate with cmake to enable auto translation/migration to the new system.
10) Declare the new build system and vcpkg/conan duo as the de facto standard for c++ build and package management

**Comment by Knitschi** [comment]
In my opinion, the Standard C++ Foundation should get more involved into these problems. I would not mind if they provided a build-system that works on all relevant platforms and a package manager implementation. The C++ community would hugely benefit from having one official way for building stuff and getting packages.

**Comment by Fleischner** [comment]
I fear this will not happen. As an observer I would say C++ ISO is mainly influenced by the large players that have their specialized build solutions that are all incompatible. Also getting things into ISO is complicated because it needs to be fine for all platforms and beyond. Not just the relevant ones. So a 98% solution is not acceptable.

My remaining hope is that the community can come up with a system (for the relevant platforms) that is de-facto standard due to its widespread adoption. Vcpgk is by far the most realistic approach towards this status.

Also the new SG15 tooling group looks promising. I hope someone from the vcpkg core team is attending at the meetings.

**Comment by BillyONeal** [comment]
@Fleischner I believe we're already doing pretty much everything you've enumerated here; I don't really see an "issue" though. Is there concrete action you're suggesting?

**Comment by PhoebeHui** [comment]
@Fleischner, let us know if you have more suggestions, thanks for your contribution!
