### ISSUE TITLE
Building package curl:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by EricPrits** [microsoft/vcpkg#6234]
Package: curl:x64-windows
 Vcpkg version: 2018.11.23-nohash

here is the errro I get when trying to install CUrl

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: C:/Program Files/vcpkg/buildtrees/curl/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Program Files\vcpkg\buildtrees\curl\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:273 (vcpkg_execute_required_process)
  ports/curl/portfile.cmake:90 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package curl:x64-windows failed with: BUILD_FAILED

**Comment by EricPrits** [comment]
Error message in the logs say it cant find the CoreFoundation Framework

-- Found Perl: C:/Program Files/vcpkg/downloads/tools/perl/perl/bin/perl.exe (found version "5.24.1") 
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE  
-- Looking for getch in ws2_32;
-- Looking for getch in ws2_32; - found
-- Looking for getch in winmm;ws2_32
-- Looking for getch in winmm;ws2_32 - found
CMake Error at CMakeLists.txt:336 (message):
  CoreFoundation framework not found


-- Configuring incomplete, errors occurred!
See also "C:/Program Files/vcpkg/buildtrees/curl/x64-windows-rel/CMakeFiles/CMakeOutput.log".
See also "C:/Program Files/vcpkg/buildtrees/curl/x64-windows-rel/CMakeFiles/CMakeError.log".
ninja: build stopped: subcommand failed.

**Comment by EricPrits** [comment]
Looing at the CMkaeErrorLog.txt it says it can find pthread.h

`CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory
ninja: build stopped: subcommand failed.`

I see that commit #4081 addressed this however even using the latest version I am still having this issue

**Comment by wangli28** [comment]
Hi @EricPrits, does the issue still occur? I installed it successfully with Visual Studio 2017 and VCPKG latest source.

PS F:\test\vcpkg> .\vcpkg.exe install curl:x64-windows
The following packages are already installed:
    curl[core,ssl,winssl]:x64-windows
Starting package 1/1: curl:x64-windows
Package curl:x64-windows is already installed
Elapsed time for package curl:x64-windows: 1.631 ms

Total elapsed time: 1.727 ms

The package curl is compatible with built-in CMake targets:

    find_package(CURL REQUIRED)
    target_link_libraries(main PRIVATE ${CURL_LIBRARIES})
    target_include_directories(main PRIVATE ${CURL_INCLUDE_DIRS})

**Comment by EricPrits** [comment]
Yes the issue is now resolved, the cause was using the command:

`vcpkg install curl[*]:x64-windows`

When I specified the specific packages it worked

**Comment by bakyac7** [comment]
I am experiencing the same error here working on visual studio code, was your command something like this:

`vcpkg install curl[core,non-http,schannel,ssl,sspi]:x64-windows`

**Comment by dg0yt** [comment]
> I am experiencing the same error here working on visual studio code, was your command something like this:
> 
> `vcpkg install curl[core,non-http,schannel,ssl,sspi]:x64-windows`

@baykac7 How do you know it is the same error? It is not the same curl and vcpkg, two years later. Better open a new issue.
