### ISSUE TITLE
[New port request] flashlight

### ISSUE THREAD

**Issue by myd7349** [microsoft/vcpkg#6247]
https://github.com/facebookresearch/flashlight

**Comment by Voskrese** [comment]
Depends: `arrayfire` ((

**Comment by Voskrese** [comment]
+ Depends: NCCL +gloo \\no Windows (((
https://github.com/facebookincubator/gloo/issues/170#issuecomment-470667888

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by jacobkahn** [comment]
Port added for the CUDA backend in https://github.com/microsoft/vcpkg/pull/14676 :). Improvements forthcoming!
