### ISSUE TITLE
Building package openjpeg:x64-osx failed

### ISSUE THREAD

**Issue by Athius** [microsoft/vcpkg#6254]
Hi everyone,

Package: openjpeg:x64-osx
Vcpkg version: 2018.11.23-unknownhash

I'm trying to install vtk[qt,python] but I have an issue at the begining of the installation:

`Starting package 1/67: openjpeg:x64-osx
Building package openjpeg[core]:x64-osx...
-- Using cached /mypath/vcpkg/downloads/uclouvain-openjpeg-v2.3.0.tar.gz
-- Using source at /mypath/vcpkg/buildtrees/openjpeg/src/v2.3.0-711dc321d0
-- Configuring x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: /mypath/vcpkg/downloads/tools/cmake-3.14.0-osx/cmake-3.14.0-Darwin-x86_64/CMake.app/Contents/bin/cmake;/mypath/vcpkg/buildtrees/openjpeg/src/v2.3.0-711dc321d0;-DBUILD_CODEC:BOOL=OFF;-DOPENJPEG_INSTALL_PACKAGE_DIR=share/openjpeg;-DOPENJPEG_INSTALL_INCLUDE_DIR=include;-DCMAKE_MAKE_PROGRAM=/mypath/vcpkg/downloads/tools/ninja-1.8.2-osx/ninja;-DCMAKE_SYSTEM_NAME=Darwin;-DBUILD_SHARED_LIBS=OFF;-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/mypath/vcpkg/scripts/toolchains/osx.cmake;-DVCPKG_TARGET_TRIPLET=x64-osx;-DVCPKG_PLATFORM_TOOLSET=external;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=/mypath/vcpkg/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DVCPKG_CXX_FLAGS=;-DVCPKG_CXX_FLAGS_RELEASE=;-DVCPKG_CXX_FLAGS_DEBUG=;-DVCPKG_C_FLAGS=;-DVCPKG_C_FLAGS_RELEASE=;-DVCPKG_C_FLAGS_DEBUG=;-DVCPKG_CRT_LINKAGE=dynamic;-DVCPKG_LINKER_FLAGS=;-DCMAKE_INSTALL_LIBDIR:STRING=lib;-DCMAKE_INSTALL_BINDIR:STRING=bin;-G;Ninja;-DCMAKE_BUILD_TYPE=Debug;-DCMAKE_INSTALL_PREFIX=/mypath/vcpkg/packages/openjpeg_x64-osx/debug
    Working Directory: /mypath/vcpkg/buildtrees/openjpeg/x64-osx-dbg
    Error code: 1
    See logs for more information:
      /mypath/vcpkg/buildtrees/openjpeg/config-x64-osx-dbg-out.log
      /mypath/vcpkg/buildtrees/openjpeg/config-x64-osx-dbg-err.log
Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:282 (vcpkg_execute_required_process)
  ports/openjpeg/portfile.cmake:10 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)
`

I attach the content of the log.
[config-x64-osx-dbg-err.log](https://github.com/Microsoft/vcpkg/files/3126925/config-x64-osx-dbg-err.log)
[config-x64-osx-dbg-out.log](https://github.com/Microsoft/vcpkg/files/3126926/config-x64-osx-dbg-out.log)

I'm working on macOs 10.14.4 with cmake 3.14.3.
Is vcpkg is stable on macOs (I had couldn't install it if I didn't install gcc with homebrew)?

**Comment by PhoebeHui** [comment]
@Athius, from you log, it failed with 'CMake Error: INSTALL(EXPORT) given unknown export "OpenJPEGTargets"', I tried it with latest source, it built successfuly for me, please get vcpkg latest source and try again. Feel free to reopen if it still be a probelm for you.

 ./vcpkg install  openjpeg:x64-osx
Computing installation plan...
The following packages will be built and installed:
    openjpeg[core]:x64-osx
Starting package 1/1: openjpeg:x64-osx
Building package openjpeg[core]:x64-osx...
-- Downloading https://github.com/uclouvain/openjpeg/archive/v2.3.1.tar.gz...
-- Extracting source /Users/vcpkg/vcpkg/downloads/uclouvain-openjpeg-v2.3.1.tar.gz
-- Using source at /Users/vcpkg/vcpkg/buildtrees/openjpeg/src/v2.3.1-62ecc2f533
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
-- Building x64-osx-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package openjpeg[core]:x64-osx... done
Installing package openjpeg[core]:x64-osx...
Installing package openjpeg[core]:x64-osx... done
Elapsed time for package openjpeg:x64-osx: 9.965 s

Total elapsed time: 9.966 s

The package openjpeg:x64-osx provides CMake targets:

    find_package(OpenJPEG CONFIG REQUIRED)
    target_link_libraries(main PRIVATE openjp2)
