### ISSUE TITLE
boost [1.69] error MSVC [2019]

### ISSUE THREAD

**Issue by Voskrese** [Microsoft/vcpkg#6255]
https://www.boost.org/doc/libs/1_69_0/boost/config/compiler/visualc.hpp

```
#     define BOOST_COMPILER_VERSION 14.0
#   elif _MSC_VER < 1920
#     define BOOST_COMPILER_VERSION 14.1
#   else
#     define BOOST_COMPILER_VERSION _MSC_VER
#   endif
# endif

#  define BOOST_COMPILER "Microsoft Visual C++ version " BOOST_STRINGIZE(BOOST_COMPILER_VERSION)
#endif
```

https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/preprocessor/predefined-macros.md

```
Visual Studio 2013 (12.0) | 1800
Visual Studio 2015 (14.0) | 1900
Visual Studio 2017 RTW (15.0) | 1910
Visual Studio 2017 version 15.3 | 1911
Visual Studio 2017 version 15.5 | 1912
Visual Studio 2017 version 15.6 | 1913
Visual Studio 2017 version 15.7 | 1914
Visual Studio 2017 version 15.8 | 1915
Visual Studio 2017 version 15.9 | 1916
Visual Studio 2019 RTW (16.0) | 1920
```

edit to ?
```
#     define BOOST_COMPILER_VERSION 14.1
#   elif _MSC_VER < 2000
#     define BOOST_COMPILER_VERSION 14.2
#   else
```

**Comment by TheScarfix** [comment]
wait for boost 1.70 which supports VS2019, PR is #6141

**Comment by Voskrese** [comment]
> I don’t have 2019, MSVC 2017 itself has a lot of problems with supporting new compiler versions
> I wrote for those who need 1.69, because the update is not always supported by other packages.

**Comment by jeanga** [comment]
I have installed VS2019 but with VS2017 toolset installed.
My triplet file contains:
 set(VCPKG_PLATFORM_TOOLSET v141)
Which should explicit use VS2017's version of the compiler.

So why does the recent commit fail?
(see attached log file)
[build-x64-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/3130107/build-x64-windows-rel-out.log)

Thanks!

**Comment by Voskrese** [comment]
in fact ... I do not see much point in updating the MSVC version and boost
enough v120 and v140 - v1.68

Why chase for updates, no major changes

> under v120 all the old code is going, the new one is

**Comment by Voskrese** [comment]
build MSVC 2019 and BOOST all ok ... )
https://github.com/Microsoft/vcpkg/issues/6302#issuecomment-489328400
