### ISSUE TITLE
unable to install  Corrade package on windows 

### ISSUE THREAD

**Issue by SYNTAXDZ** [microsoft/vcpkg#6260]
unable to install  corrade:x86-windows with vcpkg version: 2018.11.23-nohash

**Comment by wangli28** [comment]
Hi @SYNTAXDZ, thank you for posting the issue. Can you provide more information, such as your environment information and VS version? And what information did vcpkg gives to you?

**Comment by NancyLi1013** [comment]
Hi @SYNTAXDZ, I can install it successfully on my local. Please open a new issue if this is still a problem for you.

PS E:\testport\vcpkg> .\vcpkg.exe install corrade
The following packages will be built and installed:
    corrade[core,interconnect,pluginmanager,testsuite,utility]:x86-windows
Starting package 1/1: corrade:x86-windows
Building package corrade[core,interconnect,pluginmanager,testsuite,utility]:x86-windows...
-- Downloading https://github.com/mosra/corrade/archive/v2019.01.tar.gz...
-- Extracting source E:/testport/vcpkg/downloads/mosra-corrade-v2019.01.tar.gz
-- Applying patch fixC2666.patch
-- Using source at E:/testport/vcpkg/buildtrees/corrade/src/v2019.01-910c0f8340
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package corrade[core,interconnect,pluginmanager,testsuite,utility]:x86-windows... done
Installing package corrade[core,interconnect,pluginmanager,testsuite,utility]:x86-windows...
Installing package corrade[core,interconnect,pluginmanager,testsuite,utility]:x86-windows... done
Elapsed time for package corrade:x86-windows: 2.824 min

Total elapsed time: 2.824 min

The package corrade:x86-windows provides CMake targets:

    find_package(Corrade CONFIG REQUIRED)
    # Note: 2 target(s) were omitted.
    target_link_libraries(main PRIVATE ${test_name} ${plugin_name} ${plugin_name} ${plugin_name})
