### ISSUE TITLE
[New port request] Criterion

### ISSUE THREAD

**Issue by zhihaoy** [microsoft/vcpkg#6261]
Criterion is a dead-simple, non-intrusive unit testing framework for C and C++.

https://criterion.readthedocs.io/en/master/intro.html

**Comment by zhihaoy** [comment]
This has 9 dependencies.  A number of them can be found in vcpkg, but still, this port requires lots of work.  I did some initial ones here: https://github.com/zhihaoy/Criterion/tree/cmake-overhaul , but I'm not committing to finishing it, yet.

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
