### ISSUE TITLE
curl install error on windows 7 64 

### ISSUE THREAD

**Issue by RRS-MJM** [microsoft/vcpkg#6270]
When attempting to install curl I get the following console output:

vcpkg install curl:x64-windows
The following packages will be built and installed:
    curl[core,ssl,winssl]:x64-windows
Starting package 1/1: curl:x64-windows
Building package curl[core,ssl,winssl]:x64-windows...
-- Using cached C:/osg_stuff/vcpkg/downloads/curl-curl-curl-7_61_1.tar.gz
-- Using source at C:/osg_stuff/vcpkg/buildtrees/curl/src/url-7_61_1-e11be184c4
-- Downloading http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portable.zip...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:96 (message):

  File does not have expected hash:

          File path: [ C:/osg_stuff/vcpkg/downloads/temp/strawberry-perl-5.24.1.1-32bit-portable.zip ]
      Expected hash: [ a6e685ea24376f50db5f06c5b46075f1d3be25168fa1f27fa9b02e2ac017826cee62a2b43562f9b6c989337a231ba914416c110075457764de2d11f99d5e0f26 ]
        Actual hash: [ 8f98bd70d11a339ea42acc1e0c6eda600a4cf546a689adf9d1f23de2b76d5bf7bc029ad9b15b3bcedef936ed1dcd4adb5f7a3b398cd164c6bf4b01a30e89b6b2 ]

  The file may have been corrupted in transit.  This can be caused by
  proxies.  If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
  environment variables to
  "https://user:password@your-proxy-ip-address:port/".

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:179 (test_hash)
  scripts/cmake/vcpkg_find_acquire_program.cmake:257 (vcpkg_download_distfile)
  ports/curl/portfile.cmake:86 (vcpkg_find_acquire_program)
  scripts/ports.cmake:71 (include)

Error: Building package curl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: curl:x64-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

Help please!!

**Comment by Voskrese** [comment]
`cmake -E sha512sum C:/osg_stuff/vcpkg/downloads/temp/strawberry-perl-5.24.1.1-32bit-portable.zip` ?

**Comment by vicroms** [comment]
@RRS-MJM 
Please try this workaround:
1 - Copy the actual hash (`8f98bd70d11a339ea42acc1e0c6eda600a4cf546a689adf9d1f23de2b76d5bf7bc029ad9b15b3bcedef936ed1dcd4adb5f7a3b398cd164c6bf4b01a30e89b6b2`)
2 - Open file: `<vcpkg folder>/ports/curl/portfile.cmake`
3 - Replace SHA512 with the actual hash of the downloaded file.

**Change line 7**

https://github.com/Microsoft/vcpkg/blob/050e71d01dc9e65e6cdf1d13534fc14889e4ae38/ports/curl/portfile.cmake#L3-L14

**Comment by JackBoosY** [comment]
Hi @RRS-MJM , please download http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portable.zip manually, and put it to _C:/osg_stuff/vcpkg/downloads/temp/_ , then rerun command `vcpkg install curl:x64-windows`.
Thanks.

**Comment by PhoebeHui** [comment]
@RRS-MJM, does the issue solve? noted that curl upgraded to 7.65.0 now.

**Comment by PhoebeHui** [comment]
Please reopen this if it still be an issue for you.
