### ISSUE TITLE
osg install error on windows 7 64

### ISSUE THREAD

**Issue by RRS-MJM** [Microsoft/vcpkg#6272]
When attempting to install osg on 64 bit windows 7, I get the following console output

Building package osg[core]:x64-windows...
-- Downloading https://github.com/openscenegraph/OpenSceneGraph/archive/OpenSceneGraph-3.6.2.tar.gz...
-- Extracting source C:/osg_stuff/vcpkg/downloads/openscenegraph-OpenSceneGraph-OpenSceneGraph-3.6.2.tar.gz
-- Applying patch C:/osg_stuff/vcpkg/ports/osg/collada.patch
-- Applying patch C:/osg_stuff/vcpkg/ports/osg/static.patch
-- Using source at C:/osg_stuff/vcpkg/buildtrees/osg/src/raph-3.6.2-a71b4e7564
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:202 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No;/m
    Working Directory: C:/osg_stuff/vcpkg/buildtrees/osg/x64-windows-dbg
    See logs for more information:
      C:\osg_stuff\vcpkg\buildtrees\osg\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/osg/portfile.cmake:43 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package osg:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: osg:x64-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

Any ideas??

**Comment by JackBoosY** [comment]
Duplicate with #6140.
So Close it.

Please track issue #6140 process.
Thanks.
