### ISSUE TITLE
atlmfc:x64-windows-static failed : BUILD_FAILED

### ISSUE THREAD

**Issue by koudic** [Microsoft/vcpkg#6273]
Vcpkg version: 2018.11.23-nohash

**Comment by vicroms** [comment]
The ATL/MFC component must be installed using the Visual Studio installer.

After you install them `vcpkg install atlmfc:x64-windows-static` should succeed.

@koudic can you confirm whether you have ATL/MFC components installed?

**Comment by koudic** [comment]
@vicroms, thanks for the tip, only ATL was installed, after installing the MFC component everything worked out with the installation.

**Comment by wangli28** [comment]
Hi @koudic, thank you for posting the issue, this issue has been resolved, so I am closing this issue for now.
