### ISSUE TITLE
Port request: libnoise

### ISSUE THREAD

**Issue by RobertHue** [Microsoft/vcpkg#6274]
libnoise is a portable C++ library that is used to generate coherent noise, a type of smoothly-changing noise. This type of noise is often used by graphics programmers to generate natural-looking textures, planetary terrain, and other things:

http://libnoise.sourceforge.net/index.html

Can you please add that library? :)

**Comment by Voskrese** [comment]
vcxproj dynamic only Win32\x86

[noise.zip](https://github.com/Microsoft/vcpkg/files/3134575/noise.zip)

**Comment by RobertHue** [comment]
I tried adding it by typing the following:

- **vcpkg create** libnoise https://downloads.sourceforge.net/project/libnoise/libnoise%20sources/1.0.0/libnoisesrc-1.0.0.zip

but the build failed at:  

- **vcpkg build** libnoise

> -- Using cached D:/Programming/_Packages/vcpkg/downloads/libnoisesrc-1.0.0.zip
> -- Using source at D:/Programming/_Packages/vcpkg/buildtrees/libnoise/src/1.0.0-ac477545fc
> -- Configuring x86-windows
> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
>     Command failed: ninja;-v
>     Working Directory: D:/Programming/_Packages/vcpkg/buildtrees/libnoise/x86-windows-rel/vcpkg-parallel-configure
>     Error code: 1
>     See logs for more information:
>       D:\Programming\_Packages\vcpkg\buildtrees\libnoise\
[config-x86-windows-out.log](https://github.com/Microsoft/vcpkg/files/3138090/config-x86-windows-out.log)
config-x86-windows-out.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_configure_cmake.cmake:273 (vcpkg_execute_required_process)
>   ports/libnoise/portfile.cmake
[portfile.cmake.txt](https://github.com/Microsoft/vcpkg/files/3138102/portfile.cmake.txt)


>   scripts/ports.cmake:71 (include)
> 
> 
> Elapsed time for package libnoise:x86-windows: 1.063 s
> Error: Building package libnoise:x86-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: libnoise:x86-windows
>   Vcpkg version: 2018.11.23-nohash
> 
> Additionally, attach any relevant sections from the log files above.
> 

also added NO_REMOVE_ONE_LEVEL to vcpkg_extract_source_archive_ex because otherwhise it would end up with:

>  Could not unwrap top level directory from archive.  Pass
>   NO_REMOVE_ONE_LEVEL to disable this.

**Comment by Voskrese** [comment]
platform? windows or linux or ... ?
cmake no support libnoise
