### ISSUE TITLE
graphqlparser:x64-windows-static fails to install

### ISSUE THREAD

**Issue by anluoma** [microsoft/vcpkg#6280]
vcpkg install graphqlparser:x64-windows-static fails to install.

Reason behind this is that cmake script tries to copy graphqlparser.pdb alltough it's not generated during build.

**Comment by anluoma** [comment]
Attaching also a patch file to fix this issue.

Add following line to portfile.cmake

`PATCHES static-compile-fix.patch`

[static-compile-fix.patch.txt](https://github.com/Microsoft/vcpkg/files/3137341/static-compile-fix.patch.txt)

**Comment by vicroms** [comment]
Hi @anluoma

Seeing as you've already solve the issue locally, would you be able to submit a pull request to fix this in vcpkg?

**Comment by JackBoosY** [comment]
Hi @anluoma , thanks for reporting this issue!
I've fixed this issue by #6359.
Thanks.
