### ISSUE TITLE
On Linux a lot of libraries ignore -DCMAKE_BUILD_TYPE=DEBUG

### ISSUE THREAD

**Issue by crusader-mike** [microsoft/vcpkg#6285]
`find_package` and `find_library` ignores build type for many libraries (On Linux). In my experience using `-DCMAKE_BUILD_TYPE=DEBUG` leads to linking with release version of these libraries:

- curl
- z
- ssl
- crypto
- azurestorage
- uuid
- xml2
- lzma
- all Boost libs

following libs get linked fine (i.e. debug version gets linked):

- all aws-sdk-cpp libs
- cpprest

Any idea what could be wrong and how to fix it? Do I have update each port of offending lib separately?

**Comment by Neumann-A** [comment]
could be related to: https://github.com/Microsoft/vcpkg/issues/6014
probably solved by #5543

**Comment by crusader-mike** [comment]
@Neumann-A -- this is all work-in-progress. Any estimate for completion?

Also, it would be nice to establish a convention for ports to report their "findings" -- i.e. `find_package/library` should always report something meaningful to console (right now many ports don't do that and I have no idea which lib was selected).

**Comment by Neumann-A** [comment]
@crusader-mike: would be good if you would test #5543 and tell me if it fixes some of the above issues on linux. I am mainly testing on windows and some packages have quite a different naming "convention" on linux.

**Comment by crusader-mike** [comment]
@Neumann-A Uhh... smth isn't right in your branch... This is portion of my linker line that contains vcpkg stuff (when compiled with `-DCMAKE_BUILD_TYPE=DEBUG`):
```
/home/user/vcpkg/installed/x64-linux/lib/libcurl.a
/home/user/vcpkg/installed/x64-linux/lib/libz.a 
/home/user/vcpkg/installed/x64-linux/debug/lib/libaws-cpp-sdk-s3.a 
/home/user/vcpkg/installed/x64-linux/debug/lib/libaws-cpp-sdk-core.a 
/home/user/vcpkg/installed/x64-linux/lib/libcurl.a 
/home/user/vcpkg/installed/x64-linux/lib/libssl.a 
/home/user/vcpkg/installed/x64-linux/lib/libcrypto.a 
/home/user/vcpkg/installed/x64-linux/lib/libz.a 
/home/user/vcpkg/installed/x64-linux/debug/lib/libaws-c-event-stream.a 
/home/user/vcpkg/installed/x64-linux/debug/lib/libaws-c-common.a 
-lrt 
/home/user/vcpkg/installed/x64-linux/debug/lib/libaws-checksums.a 
-lpthread /home/user/vcpkg/installed/x64-linux/lib/libazurestorage.a 
/home/user/vcpkg/installed/x64-linux/lib/libuuid.a 
/home/user/vcpkg/installed/x64-linux/lib/libxml2.a 
/home/user/vcpkg/installed/x64-linux/debug/lib/liblzma.a 
/home/user/vcpkg/installed/x64-linux/debug/lib/libz.a 
-lm 
/home/user/vcpkg/installed/x64-linux/debug/lib/libcpprest.a 
-lpthread 
/home/user/vcpkg/installed/x64-linux/lib/libz.a 
/home/user/vcpkg/installed/x64-linux/lib/libssl.a 
/home/user/vcpkg/installed/x64-linux/lib/libcrypto.a 
-ldl 
/home/user/vcpkg/installed/x64-linux/lib/libboost_log.a 
/home/user/vcpkg/installed/x64-linux/lib/libboost_log_setup.a 
/home/user/vcpkg/installed/x64-linux/lib/libboost_filesystem.a
/home/user/vcpkg/installed/x64-linux/lib/libboost_thread.a 
/home/user/vcpkg/installed/x64-linux/lib/libboost_date_time.a 

/home/user/vcpkg/installed/x64-linux/lib/libboost_regex.a 
/home/user/vcpkg/installed/x64-linux/lib/libboost_chrono.a 
/home/user/vcpkg/installed/x64-linux/lib/libboost_atomic.a 
-lcrypt 
-pthread
```

I see some improvements (like `z` ans `zma`), but also note that both debug and release version if `z` got picked up.

**Comment by Neumann-A** [comment]
@crusader-mike: can I have a look at the CMakeLists.txt (or whatever file your are using to link against the dependencies) and a log of a fresh configure step of cmake. There should be a lot of vcpkg messages.  One small detail: `find_library`  behavior is not changed by vcpkg. Prefer `find_package.`

**Comment by crusader-mike** [comment]
@Neumann-A I've attached configure step log. In terms of CMakeLists.txt -- it is a bunch of projects that have very simple definitions, pulling in various libs through the `find_package` (with exception of `azure-storage-cpp` -- see #6277. Quite possibly it is the reason why I ended up release version of 

[cmake-cfg.log](https://github.com/Microsoft/vcpkg/files/3144778/cmake-cfg.log)

**Comment by crusader-mike** [comment]
... btw, I wonder -- why there are so many repetitions on linker cmd line?

**Comment by Neumann-A** [comment]
@crusader-mike. Did you rebuild the packages with #5543 installed? If not the configs will not be correct. 

> why there are so many repetitions on linker cmd line?

what do you mean by that?

If you use `find_library` you have to take care of the circumstance that debug und release names might be different.

**Comment by crusader-mike** [comment]
> @crusader-mike. Did you rebuild the packages with #5543 installed? If not the configs will not be correct.

I used the head of `Neumann-A:patch-2` branch. Am I missing smth here?

> > why there are so many repetitions on linker cmd line?
>
> what do you mean by that?

E.g. `libz.a` is mentioned 4 times... There is no good reason (that I am aware of) for that


> If you use `find_library` you have to take care of the circumstance that debug und release names might be different.

Hmm... I have no idea how to do it right in context of vcpkg. I am not particularly proficient with cmake either. I thought vcpkg intercepts `find_library` and there takes debug build into account (since only vcpkg knows where debug libs are).

> can you also give me a list of files in your vcpkg lib and debug/lib folder. I want to compare file names

Here: [filelist.txt](https://github.com/Microsoft/vcpkg/files/3144802/filelist.txt)

**Comment by Neumann-A** [comment]
@crusader-mike: 
there is something wrong with your packages according to the portfile your debug curl version should have been renamed to` libcurl.lib `but it is still named` libcurl-d.lib`.
The other thing i noticed the libz.lib linkage should be fixed in your output but it isn't. The logs clearly state the replacement with:
`-- VCPKG-find_package: with ZLIB_LIBRARIES: /home/user/vcpkg/installed/x64-linux/$<$<CONFIG:DEBUG>:debug/>lib/libz.a` and
`-- VCPKG-find_package: with ZLIB_LIBRARY: /home/user/vcpkg/installed/x64-linux/$<$<CONFIG:DEBUG>:debug/>lib/libz.a` are you linking against something strange here?

The others libraries seem to be found by other means than `find_package `

**Comment by crusader-mike** [comment]
> @crusader-mike:
> there is something wrong with your packages according to the portfile your debug curl version should have been renamed to`libcurl.lib`but it is still named` libcurl-d.lib`.

Didn't do anything -- started from scratch, cloned your repository, switched the branch, ran install, built my project. In fact, if you check linker cmdline I quoted -- `libcurl.lib` is included, just from release directory.

> The other thing i noticed the libz.lib linkage should be fixed in your output but it isn't. The logs clearly state the replacement with:
> `-- VCPKG-find_package: with ZLIB_LIBRARIES: /home/user/vcpkg/installed/x64-linux/$<$<CONFIG:DEBUG>:debug/>lib/libz.a` and
> `-- VCPKG-find_package: with ZLIB_LIBRARY: /home/user/vcpkg/installed/x64-linux/$<$<CONFIG:DEBUG>:debug/>lib/libz.a` are you linking against something strange here?
> 

Well, there is one debug `libz.a` on my cmdline, but other three are release. I assume they got pulled in by other misbehaving libs (like boost/etc)

> The others libraries seem to be found by other means than `find_package `

in my cmake files there is only one `find_library` (the only way to discover `cpprest`), everything else is `find_package`.

**Comment by Neumann-A** [comment]
@crusader-mike: Do you have any non standard CMake `Find<Package>.cmake` files in your project? I think I found the issue with libcurl. The renaming in the portfile is no longer required and even harmful in this case. I opened #6386 to remove the renaming in libcurl.

What CMake version do you use?

> in my cmake files there is only one find_library (the only way to discover cpprest), everything else is find_package.

thats not correct. cpprest has a config file! Maybe try `find_package(cpprestsdk CONFIG REQUIRED)`. It then should automatically include zlib, opensll, and the boost libraries. 

`azurestoreage` is also a `find_library` call or not?

**Comment by Neumann-A** [comment]
found the reason for
```
/home/user/vcpkg/installed/x64-linux/lib/libssl.a 
/home/user/vcpkg/installed/x64-linux/lib/libcrypto.a 
```
by pure accident. 
CMakes FindOpenSSL is to blame and the fact that vcpkg does not install the debug libraries with an additional d.

**Comment by crusader-mike** [comment]
> @crusader-mike: Do you have any non standard CMake `Find<Package>.cmake` files in your project?

Nope. All my cmake files are rather trivial.

> I think I found the issue with libcurl. The renaming in the portfile is no longer required and even harmful in this case. I opened #6386 to remove the renaming in libcurl.

Neat :)

> What CMake version do you use?

3.14.3


> > in my cmake files there is only one find_library (the only way to discover cpprest), everything else is find_package.
> 
> thats not correct. cpprest has a config file! Maybe try `find_package(cpprestsdk CONFIG REQUIRED)`. It then should automatically include zlib, opensll, and the boost libraries.

Yes, my mistake -- I used `find_package` for `azurestorage`, not `cpprestsdk`.

> `azurestoreage` is also a `find_library` call or not?

Here is the only place in my cmake files that uses `find_library`.
```
# Azure stuff
find_package(cpprestsdk CONFIG REQUIRED)
find_path(WASTORAGE_INCLUDE_DIR was/blob.h)
find_library(WASTORAGE_LIBRARY azurestorage)
find_package(Boost REQUIRED COMPONENTS log)
find_library(UUID_LIBRARY uuid)
find_package(LibXml2 REQUIRED)

target_include_directories(tools PRIVATE ${WASTORAGE_INCLUDE_DIR})
target_link_libraries(tools PRIVATE ${WASTORAGE_LIBRARY} ${UUID_LIBRARY} ${LIBXML2_LIBRARIES} cpprestsdk::cpprest Boost::log)
```

**Comment by Neumann-A** [comment]
> CMakes FindOpenSSL is to blame and the fact that vcpkg does not install the debug libraries with an additional d.

unfortunately that is only true for windows.... hmm.. 

Can you give me the values of `CMAKE_PREFIX_PATH`?

**Comment by crusader-mike** [comment]
@Neumann-A how can I get this variable? My `CMakeCache.txt` file doesn't have `CMAKE_PREFIX_PATH`

**Comment by Neumann-A** [comment]
@crusader-mike message(STATUS ${CMAKE_PREFIX_PATH}) somewhere in your CMakeLists.txt?

**Comment by crusader-mike** [comment]
Huh... It doesn't seem right to me:
`/home/user/vcpkg/installed/x64-linux/home/user/vcpkg/installed/x64-linux/debug`

this is produced by debug build using official vcpkg version `2112801abafbc0778f441bec6bce237c7eced31c` (not your branch).

**Comment by Neumann-A** [comment]
Need to add quotes around the variable but its readable. Which generator are you using? From the order of paths it looks like you are not setting cmake_build_type. Hmm or it is a problem with all upper case. Will take another look when i am not on mobile.

**Comment by Neumann-A** [comment]
Yeah the regex is too restrictive....

**Comment by crusader-mike** [comment]
Here is my cmake cmd line:
`cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake -DBUILD_VERSION="$BuildVersionFull" -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc <path-to-root>`

**Comment by Neumann-A** [comment]
@crusader-mike #6402 makes the reges case insentive. So that -DCMAKE_BUILD_TYPE=DEBUG should be correctly set the `CMAKE_PREFIX_PATH`

in debug it should be:
`/home/user/vcpkg/installed/x64-linux/debug;/home/user/vcpkg/installed/x64-linux`
while in release it should be the other way around.

**Comment by crusader-mike** [comment]
@Neumann-A Well, as you could see -- in my `CMAKE_PREFIX_PATH` order is wrong and semicolon is missing. Something isn't right somewhere...

**Comment by Neumann-A** [comment]
@crusader-mike 
> semicolon is missing. 

it requires extra quotes to see that, e.g. `message(STATUS "${CMAKE_PREFIX_PATH}")`

> order is wrong
try -DCMAKE_BUILD_TYPE=Debug instead of all uppercase. As I said #6402 makes the regex in the toolchain file case insensitive.

**Comment by crusader-mike** [comment]
@Neumann-A Huh... Using `Debug` instead of `DEBUG` caused almost all libraries to be linked properly (i.e. debug version)... with exception of `libcurl`, `libz`, `libssl` and `libcrypto` and I suspect all of these were pulled in by `libcurl`. Looks like `curl` port needs some work.

Also, build fails now with a bunch of messages like this:
```
/home/user/vcpkg/installed/x64-linux/debug/lib/libazurestorage.a(retry_policies.cpp.o): In function `_GLOBAL__sub_I_00100_0_retry_policies.cpp':
/home/user/vcpkg/buildtrees/azure-storage-cpp/src/v6.0.0-352a3c139d/Microsoft.WindowsAzure.Storage/src/retry_policies.cpp:157: undefined reference to `__gcov_init'
/home/user/vcpkg/installed/x64-linux/debug/lib/libazurestorage.a(retry_policies.cpp.o): In function `_GLOBAL__sub_D_00100_1_retry_policies.cpp':
/home/user/vcpkg/buildtrees/azure-storage-cpp/src/v6.0.0-352a3c139d/Microsoft.WindowsAzure.Storage/src/retry_policies.cpp:157: undefined reference to `__gcov_exit'
/home/user/vcpkg/installed/x64-linux/debug/lib/libazurestorage.a(retry_policies.cpp.o):(.data.rel+0x40): undefined reference to `__gcov_merge_add'
/home/user/vcpkg/installed/x64-linux/debug/lib/libazurestorage.a(operation_context.cpp.o): In function `_GLOBAL__sub_I_00100_0_operation_context.cpp':
/home/user/vcpkg/buildtrees/azure-storage-cpp/src/v6.0.0-352a3c139d/Microsoft.WindowsAzure.Storage/src/operation_context.cpp:55: undefined reference to `__gcov_init'
/home/user/vcpkg/installed/x64-linux/debug/lib/libazurestorage.a(operation_context.cpp.o): In function `_GLOBAL__sub_D_00100_1_operation_context.cpp':
/home/user/vcpkg/buildtrees/azure-storage-cpp/src/v6.0.0-352a3c139d/Microsoft.WindowsAzure.Storage/src/operation_context.cpp:55: undefined reference to `__gcov_exit'
/home/user/vcpkg/installed/x64-linux/debug/lib/libazurestorage.a(operation_context.cpp.o):(.data.rel+0x40): undefined reference to `__gcov_merge_add'
/home/user/vcpkg/installed/x64-linux/debug/lib/libazurestorage.a(cloud_core.cpp.o): In function `_GLOBAL__sub_I_00100_0_cloud_core.cpp':
/home/user/vcpkg/buildtrees/azure-storage-cpp/src/v6.0.0-352a3c139d/Microsoft.WindowsAzure.Storage/src/cloud_core.cpp:98: undefined reference to `__gcov_init'
```

Looks like it is limited only to `azure-storage-cpp` and it is missing `-lgcov`. Any idea how to fix it properly and what is `gcov` lib? (shouldn't it be mentioned somewhere in `ports`?)

**Comment by crusader-mike** [comment]
> in debug it should be:
> `/home/user/vcpkg/installed/x64-linux/debug;/home/user/vcpkg/installed/x64-linux`
> while in release it should be the other way around.

I think it is a bad idea -- if smth is wrong (file got deleted/etc) you may accidentally pickup debug library in release build. 

Side note: for some reason calling `cmake -DCMAKE_BUILD_TYPE=Release blah` after `cmake -DCMAKE_BUILD_TYPE=Debug blah` doesn't cause libraries to be rediscovered -- I end up linking debug libraries. Any idea why? I expected related `find_library/find_package` commands to be re-executed, since variable (they depend on) changed.

**Comment by Neumann-A** [comment]
>I think it is a bad idea

Both paths are required to generate correct target information for debug and release! Else the CMake generates target only have one configuration which means multi config generators dont work correctly.

> with exception of libcurl, libz, libssl and libcrypto

did you update to the must recent version of vcpkg? the curl linkage should be fixed with the renaming removal (#6386). The OpenSSL linkage is still in the works (#6409)

> Any idea how to fix it properly and what is gcov lib? 

hmm gcov is coder coverage tool. Maybe a simple CMake definition is missing to deactivate code coverage information for that port. 

> doesn't cause libraries to be rediscovered
ah interesting thats a similar problem to what mutli config generators have. CMake is properly not rerunning the toolchain file. #5543 will probably solve it anyday for the meantine delete the cache if you change configurations.

**Comment by crusader-mike** [comment]
> Both paths are required to generate correct target information for debug and release! Else the CMake generates target only have one configuration which means multi config generators dont work correctly.

Uhm... whatever mechanism is used to properly build makefiles for multiple configurations -- we shouldn't end up referring/fallingback to release libraries in debug build and vice versa. Imho, it is an invitation for problems. 


> did you update to the must recent version of vcpkg? the curl linkage should be fixed with the renaming removal (#6386). The OpenSSL linkage is still in the works (#6409)

No, I fell behind -- vcpkg dir is now being checked in into my TFS and contains some extra changes. Sync-ing with latest version takes time now and I don't do it very often. But info is appreciated -- once OpenSSL stuff is sorted out -- I'll sync and try again.


> hmm gcov is coder coverage tool. Maybe a simple CMake definition is missing to deactivate code coverage information for that port.

Looks like `azure-storage-cpp` port needs some tinkering...


> ah interesting thats a similar problem to what mutli config generators have. CMake is properly not rerunning the toolchain file. #5543 will probably solve it anyday for the meantine delete the cache if you change configurations.

Can you elaborate a bit about this one? Is it a `CMake` or vcpkg problem?

**Comment by Neumann-A** [comment]
> we shouldn't end up referring/fallingback to release libraries in debug build and vice versa. Imho, it is an invitation for problems.

CMake has some strange fallbacks. E.g. see #6393

> Sync-ing with latest version takes time now

hmm you probably customized your ports right? I opened #6572. If the ports are configurable from the triplet merging from master should be much easier. 

> Can you elaborate a bit about this one?

The problem is that `CMAKE_PREFIX_PATH` can only be defined once and will look for -config.cmake files only once. As such there can only be one -config for a find_package call which must include debug and release information to be correct. Otherwise CMakes falls back to whatever it finds first in `CMAKE_CONFIGURATION_TYPES` using a multi config generator. The only way to circumvent this fallback is to define `CMAKE_MAP_IMPORTED_CONFIG_<CONFIG>` and stop CMake from doing whatever it thinks is correct. 

> Is it a CMake or vcpkg problem?

Depends on your view. If CMake would support generator expressions in CMAKE_PREFIX_PATH it could be easily solved since CMake would require to rerun everytime the configuration is changed. On the other hand vcpkg could provide overrides that all libraries are linked correctly. That is what I try with #5543 and even ERROR on wrong linkage. But finding problems always takes more or less a day for a single triplet.....

**Comment by crusader-mike** [comment]
[Hmm](https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html)... How about this arrangement:

- `CMAKE_PREFIX_PATH` always consists of only one path, e.g. `/home/user/vcpkg/installed/x64-linux`
- related `find_XXX` routine takes current value of `CMAKE_BUILD_TYPE` into account and (if it is `Debug`) adds `/debug` to `CMAKE_PREFIX_PATH` and (if necessary) appends whatever debug prefix given library uses (e.g. `_d`)

In this way rerunning build with different build type should work and picking incorrect library build is impossible. 

Will this work?

**Comment by crusader-mike** [comment]
@Neumann-A Does it make sense (or am I clueless)?

**Comment by Neumann-A** [comment]
> related find_XXX routine takes current value of CMAKE_BUILD_TYPE into account and (if it is Debug) adds /debug to CMAKE_PREFIX_PATH and (if necessary) appends whatever debug prefix given library uses (e.g. _d)

First: CMAKE_BUILD_TYPE is not set for multi configuration generators.
Second: You can have a look at the scripts changes required to do that correctly in #6555 even for multi config generators. But it is not that easily done and has a lot of corner cases which must be dealt with.

**Comment by crusader-mike** [comment]
> First: CMAKE_BUILD_TYPE is not set for multi configuration generators.

@Neumann-A, are you saying that `find_XXX` function gets executed when cmake builds makefile/ninja/etc files and therefore can't observe `CMAKE_BUILD_TYPE` yet? Can it generate a logic that (when executed by make/ninja/etc) will select correct path to binary depending on value of `CMAKE_BUILD_TYPE`?

> Second: You can have a look at the scripts changes required to do that correctly in #6555 even for multi config generators. But it is not that easily done and has a lot of corner cases which must be dealt with.

Will do. Thanks!

**Comment by crusader-mike** [comment]
@Neumann-A I have updated to the latest `vcpkg` and almost all of libs (that I am using) are linked properly in debug with exception of `libcurl` (and it's dependencies). I tried both:
```
target_link_libraries(myapp PRIVATE CURL::libcurl)
```
and 
```
target_link_libraries(myapp PRIVATE ${CURL_LIBRARIES})
target_include_directories(myapp PRIVATE ${CURL_INCLUDE_DIRS})
```

Is it possible to workaround this somehow or I have to wait for `libcurl` port to be fixed?

**Comment by crusader-mike** [comment]
I've submitted #7373 and #7311 for curl and azurestoragecpp problems respectively. Closing this discussion. Thank you for help, @Neumann-A .
