### ISSUE TITLE
[cpprest] is missing boost-asio dependency on linux

### ISSUE THREAD

**Issue by crusader-mike** [microsoft/vcpkg#6300]
%subj%. This causes installation errors like in #6278. I believe all you need is to add `boost-asio (!uwp&!windows)` to `ports/cpprestsdk/CONTROL`.

**Comment by Rastaban** [comment]
Thanks for reporting this.  Did you add `boost-asio` to the dependency on your machine to verify that it fixed the issue?

**Comment by crusader-mike** [comment]
yep

**Comment by PhoebeHui** [comment]
@crusader-mike, could you help summit a PRs for this? if not, I can help to do this.

**Comment by crusader-mike** [comment]
Guys, change is trivial. Just include it with some other change.

**Comment by wangli28** [comment]
This issue has been fixed, so I am closing this issue for now.

**Comment by crusader-mike** [comment]
Thank you, @wangli28

**Comment by JackBoosY** [comment]
Hi @crusader-mike, thanks for reporting this issue!
This issue has been fixed in PR #6380. Please update vcpkg and rebuild cpprest.

Thanks.
