### ISSUE TITLE
vcpkg is not update include path

### ISSUE THREAD

**Issue by fawdlstty** [microsoft/vcpkg#6301]
I encountered this problem: after installing some packages in the local VCPKG, I used vs2017 to create a new project, but the new project did not recognize the path of VCPKG, so I had to add the path manually
For example, include path add D:\GitHub\vcpkg\installed\x86-windows\include;D:\GitHub\vcpkg\installed\x86-windows\lib
It's a random problem that I haven't seen on other computers;The problem computer environment is win7, equipped with vc2013 and vs2017

**Comment by ventsin** [comment]
Have you tried to run `./vcpkg integrate install`?

**Comment by fawdlstty** [comment]
I have run the command and remove include/library path from project settings, but encounter a trouble

![20190505092634](https://user-images.githubusercontent.com/7323999/57186796-39bb8680-6f18-11e9-8868-2aebb065507f.png)

if I set the library path, it still recognition

**Comment by Voskrese** [comment]
`ZLIB::ZLIB` not working, encountered in many packages
use the file name `zlib `and `zlibd`

**Comment by PhoebeHui** [comment]
@fawdlstty, thanks for posting this issue!

I can't reproduce this issue with vs2017 15.9.11 on win7. BTW, VCPKG require Visual Studio 2015 Update 3 or newer (on Windows).

What I tried:
1. Get VCPKG latest revision
2. ./vcpkg install zlib
3. ./vcpkg integrate install
4. Open vs2017 and create a console application
5. Add '#include<zlib.h>' in ConsoleApplication.cpp
6. Try to build it or you can find zlib.h by 'Open Document <zlib.h>', and check that zlib.h referenced from ./installed/x86-windows/include correctly.

**Comment by fawdlstty** [comment]
I don't know why. Problem solved

**Comment by chebum** [comment]
The problem can be reproduced this way:
```
vcpkg install zlib:x64-windows-static
vcpkg integrate install 
```

Simple console app from https://github.com/Microsoft/vcpkg/issues/6301#issuecomment-490250792 won't compile.

Additional `vcpkg install zlib` solves the problem.
