### ISSUE TITLE
So again, can anyone write tutorial how to import package? 

### ISSUE THREAD

**Issue by goodguysoft** [microsoft/vcpkg#6311]
I need to import just header only library; it is supposed to be trivial. The library is `cppcodec`, it encodes and decodes base64 and some similar encodings.
So, I created `cppcodec` folder, added `include` folder here and control file. Now I import it:

`vcpkg import c:\@work\cppcodec\CONTROL c:\@work\cppcodec\include\ c:\@work\cppcodec\`

Import succeeds, `cppcodec_x64-windows-static` folder is created in packages one.

However, `vcpkg` doesn't see this folder, it doesn't display this package in `list` and can not install it. It is annoying, because how is that possible that `vcpkg` reports that import is successful and now simply fails silently to install the package?

Anyway, can anyone write working tutorial how to import package to `vcpkg` from local drive?

**Comment by tan-wei** [comment]
[This link](https://vcpkg.readthedocs.io/) is what you need.

**Comment by tan-wei** [comment]
And [this](https://github.com/Microsoft/vcpkg/blob/master/docs/examples/packaging-github-repos.md)

**Comment by Voskrese** [comment]
not a working tool, does not register in the database
same as copy manually

**Comment by NancyLi1013** [comment]
Hi @goodguysoft 

Thanks for posting this issue.
So sorry for late reply.
Is this still a problem for you now?

**Comment by goodguysoft** [comment]
Hi, thanks you for your reply. No, it is not a problem for me personally already, but as I see, this command actually doesn't work already, so may be developers have to remove it from documentation to not confuse new and inexperienced `vspkg` users.

**Comment by NancyLi1013** [comment]
Thanks for your reply and suggestion about this issue.
We will go further investigation about this command.

Thanks again.
