### ISSUE TITLE
Error: Building package opengl:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by RobertHue** [microsoft/vcpkg#6322]
Hello! 
I do have the same problem as  #5866 and #5495
```
CMake Error at ports/opengl/portfile.cmake:20 (message):
          Cannot find Windows 10.0.18362.0 SDK.     File does not exist: 
          C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\x86\OpenGL32.Lib
          Call Stack (most recent call first):          scripts/ports.cmake:71 (include)
```
my windows kits are installed here though:
**D:\Windows Kits**\10\Lib\10.0.18362.0\um\x86

I know it's closed, but I'm just asking for some fix for it.

**Reason for this behavior:**
the port-cmake of opengl makes an assumptions on specific paths:

    if (WINDOWS_SDK MATCHES "10.")
        set(LIBGLFILEPATH  "${PROGRAM_FILES_32_BIT}\\Windows Kits\\10\\Lib\\${WINDOWS_SDK}\\um\\${TRIPLET_SYSTEM_ARCH}\\OpenGL32.Lib")
        set(LIBGLUFILEPATH "${PROGRAM_FILES_32_BIT}\\Windows Kits\\10\\Lib\\${WINDOWS_SDK}\\um\\${TRIPLET_SYSTEM_ARCH}\\GlU32.Lib")
        set(HEADERSPATH    "${PROGRAM_FILES_32_BIT}\\Windows Kits\\10\\Include\\${WINDOWS_SDK}\\um")

Is it good too ask the ${PROGRAM_FILES_32_BIT} variable?

- So what should I do now? 
- Installing Visual Studio again? 
- Or can I give vcpkg some hint for searching at some other location for those libs?
- the last post suggested reading from the registry. Is that viable?
`HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows Kits\Installed Roots`
KitsRoot10="PATH_TO_WINDOWS_KITS"

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/5495
