### ISSUE TITLE
POCO x86-windows-static missing required library (IPHLPAPI.lib)

### ISSUE THREAD

**Issue by gdiObjects** [microsoft/vcpkg#6323]
The POCO foundationmt library needs to be linked against IPHLPAPI.lib because it uses the GetAdaptersInfo() call (iphlpapi.h).

The simple solution is to add the following to stdafx.h
#pragma comment(lib, "IPHLPAPI.lib")

**Comment by PhoebeHui** [comment]
@gdiObjects, thanks for reporting this issue, this issue fixed now.
