### ISSUE TITLE
LINK : fatal error LNK1104: cannot open file 'ucrtd.lib'

### ISSUE THREAD

**Issue by FishHe** [microsoft/vcpkg#6324]
I have installed windows 10 sdk, but vcpkg can't find it.

[1/2] cmd /c "cd .. && "H:/ProgramData/CMake/bin/cmake.exe" "H:/ProgramDesign/VCPKG/vcpkg/buildtrees/zlib/src/1.2.11-f690224aeb" "-DSKIP_INSTALL_FILES=ON" "-DSKIP_BUILD_EXAMPLES=ON" "-DCMAKE_MAKE_PROGRAM=H:/ProgramDesign/VCPKG/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=H:/ProgramDesign/VCPKG/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=H:/ProgramDesign/VCPKG/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=H:/ProgramDesign/VCPKG/vcpkg/packages/zlib_x64-windows""
FAILED: ../CMakeCache.txt 
cmd /c "cd .. && "H:/ProgramData/CMake/bin/cmake.exe" "H:/ProgramDesign/VCPKG/vcpkg/buildtrees/zlib/src/1.2.11-f690224aeb" "-DSKIP_INSTALL_FILES=ON" "-DSKIP_BUILD_EXAMPLES=ON" "-DCMAKE_MAKE_PROGRAM=H:/ProgramDesign/VCPKG/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=H:/ProgramDesign/VCPKG/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=H:/ProgramDesign/VCPKG/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=H:/ProgramDesign/VCPKG/vcpkg/packages/zlib_x64-windows""
CMake Warning at H:/ProgramDesign/VCPKG/vcpkg/scripts/buildsystems/vcpkg.cmake:107 (message):
  There are no libraries installed for the Vcpkg triplet x64-windows.
Call Stack (most recent call first):
  H:/ProgramData/CMake/share/cmake-3.14/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:4 (project)

-- The C compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- broken
CMake Error at H:/ProgramData/CMake/share/cmake-3.14/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: H:/ProgramDesign/VCPKG/vcpkg/buildtrees/zlib/x64-windows-rel/CMakeFiles/CMakeTmp
    
    Run Build Command(s):H:/ProgramDesign/VCPKG/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe cmTC_b7e4c 
    [1/2] Building C object CMakeFiles\cmTC_b7e4c.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_b7e4c.exe
    FAILED: cmTC_b7e4c.exe 
    cmd.exe /C "cd . && H:\ProgramData\CMake\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_b7e4c.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\x64\mt.exe --manifests  -- D:\PROGRA~1\MICROS~1.0\VC\bin\amd64\link.exe /nologo CMakeFiles\cmTC_b7e4c.dir\testCCompiler.c.obj  /out:cmTC_b7e4c.exe /implib:cmTC_b7e4c.lib /pdb:cmTC_b7e4c.pdb /version:0.0  /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    LINK Pass 1: command "D:\PROGRA~1\MICROS~1.0\VC\bin\amd64\link.exe /nologo CMakeFiles\cmTC_b7e4c.dir\testCCompiler.c.obj /out:cmTC_b7e4c.exe /implib:cmTC_b7e4c.lib /pdb:cmTC_b7e4c.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\cmTC_b7e4c.dir/intermediate.manifest CMakeFiles\cmTC_b7e4c.dir/manifest.res" failed (exit code 1104) with the following output:
    LINK : fatal error LNK1104: cannot open file 'ucrtd.lib'
    ninja: build stopped: subcommand failed.
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)

-- Configuring incomplete, errors occurred!
See also "H:/ProgramDesign/VCPKG/vcpkg/buildtrees/zlib/x64-windows-rel/CMakeFiles/CMakeOutput.log".
See also "H:/ProgramDesign/VCPKG/vcpkg/buildtrees/zlib/x64-windows-rel/CMakeFiles/CMakeError.log".
[2/2] cmd /c "cd ../../x64-windows-dbg && "H:/ProgramData/CMake/bin/cmake.exe" "H:/ProgramDesign/VCPKG/vcpkg/buildtrees/zlib/src/1.2.11-f690224aeb" "-DSKIP_INSTALL_FILES=ON" "-DSKIP_BUILD_EXAMPLES=ON" "-DCMAKE_MAKE_PROGRAM=H:/ProgramDesign/VCPKG/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=H:/ProgramDesign/VCPKG/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=H:/ProgramDesign/VCPKG/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-DSKIP_INSTALL_HEADERS=ON" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=H:/ProgramDesign/VCPKG/vcpkg/packages/zlib_x64-windows/debug""
FAILED: ../../x64-windows-dbg/CMakeCache.txt 
cmd /c "cd ../../x64-windows-dbg && "H:/ProgramData/CMake/bin/cmake.exe" "H:/ProgramDesign/VCPKG/vcpkg/buildtrees/zlib/src/1.2.11-f690224aeb" "-DSKIP_INSTALL_FILES=ON" "-DSKIP_BUILD_EXAMPLES=ON" "-DCMAKE_MAKE_PROGRAM=H:/ProgramDesign/VCPKG/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=H:/ProgramDesign/VCPKG/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=H:/ProgramDesign/VCPKG/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-DSKIP_INSTALL_HEADERS=ON" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=H:/ProgramDesign/VCPKG/vcpkg/packages/zlib_x64-windows/debug""
CMake Warning at H:/ProgramDesign/VCPKG/vcpkg/scripts/buildsystems/vcpkg.cmake:107 (message):
  There are no libraries installed for the Vcpkg triplet x64-windows.
Call Stack (most recent call first):
  H:/ProgramData/CMake/share/cmake-3.14/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:4 (project)

-- The C compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- broken
CMake Error at H:/ProgramData/CMake/share/cmake-3.14/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: H:/ProgramDesign/VCPKG/vcpkg/buildtrees/zlib/x64-windows-dbg/CMakeFiles/CMakeTmp
    
    Run Build Command(s):H:/ProgramDesign/VCPKG/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe cmTC_8c2ed 
    [1/2] Building C object CMakeFiles\cmTC_8c2ed.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_8c2ed.exe
    FAILED: cmTC_8c2ed.exe 
    cmd.exe /C "cd . && H:\ProgramData\CMake\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_8c2ed.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\x64\mt.exe --manifests  -- D:\PROGRA~1\MICROS~1.0\VC\bin\amd64\link.exe /nologo CMakeFiles\cmTC_8c2ed.dir\testCCompiler.c.obj  /out:cmTC_8c2ed.exe /implib:cmTC_8c2ed.lib /pdb:cmTC_8c2ed.pdb /version:0.0  /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    LINK Pass 1: command "D:\PROGRA~1\MICROS~1.0\VC\bin\amd64\link.exe /nologo CMakeFiles\cmTC_8c2ed.dir\testCCompiler.c.obj /out:cmTC_8c2ed.exe /implib:cmTC_8c2ed.lib /pdb:cmTC_8c2ed.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\cmTC_8c2ed.dir/intermediate.manifest CMakeFiles\cmTC_8c2ed.dir/manifest.res" failed (exit code 1104) with the following output:
    LINK : fatal error LNK1104: cannot open file 'ucrtd.lib'
    ninja: build stopped: subcommand failed.
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)

-- Configuring incomplete, errors occurred!
See also "H:/ProgramDesign/VCPKG/vcpkg/buildtrees/zlib/x64-windows-dbg/CMakeFiles/CMakeOutput.log".
See also "H:/ProgramDesign/VCPKG/vcpkg/buildtrees/zlib/x64-windows-dbg/CMakeFiles/CMakeError.log".
ninja: build stopped: subcommand failed.

**Comment by Voskrese** [comment]
https://github.com/Microsoft/vcpkg/issues/5854#issuecomment-478252275

full reinstall windows sdk

**Comment by LarryIII** [comment]
@FishHe I noticed the V140 tools was set, please ensure you installed C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\.. before run vcpkg install.

**Comment by FishHe** [comment]
I fully reinstalled windows sdk and vcpkg, and it works.....
@LarryIII @Voskrese Thanks~
