### ISSUE TITLE
Who can help me ？

### ISSUE THREAD

**Issue by Qianzujin** [microsoft/vcpkg#6334]
![image](https://user-images.githubusercontent.com/49854479/57283717-628f7780-70e2-11e9-9e85-e5e9d12868ec.png)
Who can help me ？
谁能帮帮我？

**Comment by myd7349** [comment]
If you put `vcpkg` on `C:`, maybe you should also run PowerShell with Administrator Privilege.

**Comment by Qianzujin** [comment]
![image](https://user-images.githubusercontent.com/49854479/57284816-7fc54580-70e4-11e9-9af8-3f2393a64adf.png)

**Comment by Qianzujin** [comment]
> If you put `vcpkg` on `C:`, maybe you should run PowerShell with Administrator Privilege.

It seems that VPN is needed
好像是需要vpn

**Comment by myd7349** [comment]
Just try it again. The connection to GitHub is not always stable in China.

**Comment by Qianzujin** [comment]
> 再试一次吧。与GitHub的连接在中国并不总是稳定的。

Yes, I've tried it many times.

**Comment by Qianzujin** [comment]
![image](https://user-images.githubusercontent.com/49854479/57286511-f3b51d00-70e7-11e9-9c90-b8fe34f16160.png)
error-log：
 命令行 error D8000 :C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64_x86\cl.exe 中有内部编译器错误。系统将会提示你稍后向 Microsoft 发送错误报告。

**Comment by Qianzujin** [comment]
> @Qianzujin Which port do you need to build? What is your Visual Studio version?
> And please attach the following log files:
> ![57286511-f3b51d00-70e7-11e9-9c90-b8fe34f16160](https://user-images.githubusercontent.com/47264268/57288891-f6fed780-70ec-11e9-8d60-42e871f4cba7.png)
> 
> Thanks.

error-log：
命令行 error D8000 :C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64_x86\cl.exe 中有内部编译器错误。系统将会提示你稍后向 Microsoft 发送错误报告。

**Comment by Qianzujin** [comment]
> > @Qianzujin Which port do you need to build? What is your Visual Studio version?
> > And please attach the following log files:
> > ![57286511-f3b51d00-70e7-11e9-9c90-b8fe34f16160](https://user-images.githubusercontent.com/47264268/57288891-f6fed780-70ec-11e9-8d60-42e871f4cba7.png)
> > Thanks.
> 
> error-log：
> 命令行 error D8000 :C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64_x86\cl.exe 中有内部编译器错误。系统将会提示你稍后向 Microsoft 发送错误报告。

This is Chinese.

**Comment by JackBoosY** [comment]
@Qianzujin Sorry, I cannot repro it in my machine(Win10-Chinese/VisualStudio2017-Chinese ver15.9.7).
Can you provide me more details? Such as:
- Port name
- Visual Studio version.
- Upload these two logs.
- Do you install Visual Studio english language package?

Thanks.

> 对不起，我在我的机器上无法复现这个问题(中文Win10/中文VisualStduio2017 v15.9.7)。你能提供更多的信息吗？
例如:
Port 名称
使用的Visual Studio 版本
上传*-out.log与*-err.log
已经安装过Visual Studio 英文语言包了吗?

**Comment by Qianzujin** [comment]
> @Qianzujin Sorry, I cannot repro it in my machine(Win10-Chinese/VisualStudio2017-Chinese ver15.9.7).
> Can you provide me more details? Such as:
> 
> * Port name
> * Visual Studio version.
> * Upload these two logs.
> * Do you install Visual Studio english language package?
> 
> Thanks.
> 
> > 对不起，我在我的机器上无法复现这个问题(中文Win10/中文VisualStduio2017 v15.9.7)。你能提供更多的信息吗？
> > 例如:
> > Port 名称
> > 使用的Visual Studio 版本
> > 上传*-out.log与*-err.log
> > 已经安装过Visual Studio 英文语言包了吗?



> @Qianzujin Sorry, I cannot repro it in my machine(Win10-Chinese/VisualStudio2017-Chinese ver15.9.7).
> Can you provide me more details? Such as:
> 
> * Port name
> * Visual Studio version.
> * Upload these two logs.
> * Do you install Visual Studio english language package?
> 
> Thanks.
> 
> > 对不起，我在我的机器上无法复现这个问题(中文Win10/中文VisualStduio2017 v15.9.7)。你能提供更多的信息吗？
> > 例如:
> > Port 名称
> > 使用的Visual Studio 版本
> > 上传*-out.log与*-err.log
> > 已经安装过Visual Studio 英文语言包了吗?

> >I don't know the port number.
> > vs2015 community
> > Error log has been uploaded
> > i dont know Visual Studio english language package


[bootstrap-x86-windows-err.log](https://github.com/microsoft/vcpkg/files/3160115/bootstrap-x86-windows-err.log)
[bootstrap-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/3160116/bootstrap-x86-windows-out.log)
@aliakseis @JackBoosY

**Comment by Qianzujin** [comment]
> > @Qianzujin Sorry, I cannot repro it in my machine(Win10-Chinese/VisualStudio2017-Chinese ver15.9.7).
> > Can you provide me more details? Such as:
> > 
> > * Port name
> > * Visual Studio version.
> > * Upload these two logs.
> > * Do you install Visual Studio english language package?
> > 
> > Thanks.
> > > 对不起，我在我的机器上无法复现这个问题(中文Win10/中文VisualStduio2017 v15.9.7)。你能提供更多的信息吗？
> > > 例如:
> > > Port 名称
> > > 使用的Visual Studio 版本
> > > 上传*-out.log与*-err.log
> > > 已经安装过Visual Studio 英文语言包了吗?
> 
> > @Qianzujin Sorry, I cannot repro it in my machine(Win10-Chinese/VisualStudio2017-Chinese ver15.9.7).
> > Can you provide me more details? Such as:
> > 
> > * Port name
> > * Visual Studio version.
> > * Upload these two logs.
> > * Do you install Visual Studio english language package?
> > 
> > Thanks.
> > > 对不起，我在我的机器上无法复现这个问题(中文Win10/中文VisualStduio2017 v15.9.7)。你能提供更多的信息吗？
> > > 例如:
> > > Port 名称
> > > 使用的Visual Studio 版本
> > > 上传*-out.log与*-err.log
> > > 已经安装过Visual Studio 英文语言包了吗?
> 
> > > I don't know the port number.
> > > vs2015 community
> > > Error log has been uploaded
> > > i dont know Visual Studio english language package
> 
> [bootstrap-x86-windows-err.log](https://github.com/microsoft/vcpkg/files/3160115/bootstrap-x86-windows-err.log)
> [bootstrap-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/3160116/bootstrap-x86-windows-out.log)
> @aliakseis @JackBoosY

I don't know what the Visual Studio English Language Pack is. The version I installed is in Chinese.

**Comment by Qianzujin** [comment]
> > @Qianzujin Sorry, I cannot repro it in my machine(Win10-Chinese/VisualStudio2017-Chinese ver15.9.7).
> > Can you provide me more details? Such as:
> > 
> > * Port name
> > * Visual Studio version.
> > * Upload these two logs.
> > * Do you install Visual Studio english language package?
> > 
> > Thanks.
> > > 对不起，我在我的机器上无法复现这个问题(中文Win10/中文VisualStduio2017 v15.9.7)。你能提供更多的信息吗？
> > > 例如:
> > > Port 名称
> > > 使用的Visual Studio 版本
> > > 上传*-out.log与*-err.log
> > > 已经安装过Visual Studio 英文语言包了吗?
> 
> > @Qianzujin Sorry, I cannot repro it in my machine(Win10-Chinese/VisualStudio2017-Chinese ver15.9.7).
> > Can you provide me more details? Such as:
> > 
> > * Port name
> > * Visual Studio version.
> > * Upload these two logs.
> > * Do you install Visual Studio english language package?
> > 
> > Thanks.
> > > 对不起，我在我的机器上无法复现这个问题(中文Win10/中文VisualStduio2017 v15.9.7)。你能提供更多的信息吗？
> > > 例如:
> > > Port 名称
> > > 使用的Visual Studio 版本
> > > 上传*-out.log与*-err.log
> > > 已经安装过Visual Studio 英文语言包了吗?
> 
> > > I don't know the port number.
> > > vs2015 community
> > > Error log has been uploaded
> > > i dont know Visual Studio english language package
> 
> [bootstrap-x86-windows-err.log](https://github.com/microsoft/vcpkg/files/3160115/bootstrap-x86-windows-err.log)
> [bootstrap-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/3160116/bootstrap-x86-windows-out.log)
> @aliakseis @JackBoosY

I don't know what the Visual Studio English Language Pack is. The version I installed is in Chinese.

**Comment by Qianzujin** [comment]
![image](https://user-images.githubusercontent.com/49854479/57424647-f9774380-724a-11e9-9138-6a5d08a14e8c.png)

**Comment by JackBoosY** [comment]
@Qianzujin I recommend that you install Visual Studio 2017 and rebuild vcpkg again, and you can still use Visual Studio 2015 for development work.

**Comment by Qianzujin** [comment]
> @Qianzujin我建议你再安装Visual Studio 2017并重新构建vcpkg，你仍然可以使用Visual Studio 2015进行开发工作。

oh

**Comment by aliakseis** [comment]
I didn't observe privileges related problems with C:/vcpkg.
I see "Command failed: C:/Users/.../bootstrap.bat" in the trace. I'd try running this file manually and see what happens.

**Comment by JackBoosY** [comment]
@Qianzujin Please tell me if you still have problem with boost-build after installed Visual Studio 2017.
Thanks.

**Comment by Qianzujin** [comment]
> @Qianzujin请告诉我你是否在安装Visual Studio 2017后仍然遇到boost-build问题。
> 谢谢。

Okay, I'll try to install it this weekend.
It's working time now.(⊙︿⊙)

**Comment by zengjingcheng** [comment]
![image](https://user-images.githubusercontent.com/33272922/57500656-c7331800-7316-11e9-840f-ecd3ce7016b9.png)
i think i meet the same problem. And i checked my VS2015. It has both Chinese and English language package.
the failed line in log is
...found 124 targets...
...updating 16 targets...
msvc.write-setup-script D:\vcpkg\buildtrees\boost-system\x64-windows-rel\boost\standalone\msvc\a1c47416b677e1e61abd4f30699dc29c\msvc-setup.bat
compile-c-c++ D:\vcpkg\buildtrees\boost-system\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\error_code.obj
error_code.cpp
msvc.link.dll D:\vcpkg\buildtrees\boost-system\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\boost_system-vc140-mt-x64-1_69.dll
   Creating library D:\vcpkg\buildtrees\boost-system\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\boost_system-vc140-mt-x64-1_69.lib and object D:\vcpkg\buildtrees\boost-system\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\boost_system-vc140-mt-x64-1_69.exp
msvc.manifest.dll D:\vcpkg\buildtrees\boost-system\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\boost_system-vc140-mt-x64-1_69.dll
'mt' is not recognized as an internal or external command,
operable program or batch file.

        if exist "D:\vcpkg\buildtrees\boost-system\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\boost_system-vc140-mt-x64-1_69.dll.manifest" (
            call "D:\vcpkg\buildtrees\boost-system\x64-windows-rel\boost\standalone\msvc\a1c47416b677e1e61abd4f30699dc29c\msvc-setup.bat" amd64 >nul
 mt -manifest "D:\vcpkg\buildtrees\boost-system\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\boost_system-vc140-mt-x64-1_69.dll.manifest" "-outputresource:D:\vcpkg\buildtrees\boost-system\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\boost_system-vc140-mt-x64-1_69.dll;2"
        )
    
...failed msvc.manifest.dll D:\vcpkg\buildtrees\boost-system\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\boost_system-vc140-mt-x64-1_69.dll D:\vcpkg\buildtrees\boost-system\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\boost_system-vc140-mt-x64-1_69.lib D:\vcpkg\buildtrees\boost-system\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\boost_system-vc140-mt-x64-1_69.pdb D:\vcpkg\buildtrees\boost-system\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\boost_system-vc140-mt-x64-1_69.pdb...
...removing D:\vcpkg\buildtrees\boost-system\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\boost_system-vc140-mt-x64-1_69.dll
...removing D:\vcpkg\buildtrees\boost-system\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\boost_system-vc140-mt-x64-1_69.lib
...removing D:\vcpkg\buildtrees\boost-system\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\boost_system-vc140-mt-x64-1_69.pdb
...failed updating 1 target...
...updated 11 targets...

**Comment by PhoebeHui** [comment]
@Qianzujin, could you check where the 'mt' located in your machine? and install windows sdk via VS if you didn't.

In my machine, it located C:\Program Files (x86)\Windows Kits\10\bin\x86\mt.exe
Open VS2015 x86 Native tools command:
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC>where mt
C:\Program Files (x86)\Windows Kits\10\bin\x86\mt.exe

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
