### ISSUE TITLE
[poco] The release libraries are linked to debug pcred.dll which is not automatically copied

### ISSUE THREAD

**Issue by mmahnic** [microsoft/vcpkg#6349]
Machine: Windows 10, Build 17763
Application: Using POCO libraries (using PCRE), x86-windows or x64-windows
Build: Release
Desired outcome: The application is linked to pcre.dll (Release) and starts normally.
Actual outcome: 
   * The program can’t start because pcred.dll is missing from your computer. 
   * The POCO release libraries are linked to the debug version of PCRE (pcred.dll) which is also not automatically copied to the Release target directory.

This is related to a fix for #302 that added find_pcre.patch.

**Comment by JackBoosY** [comment]
Hi @mmahnic, thanks for reporting this issue,
I've fixed this issue, please update vcpkg and rebuild poco.

Thanks.
