### ISSUE TITLE
How to use Vcpkg with Hosted TFS? [was: Missing TFS Build feature]

### ISSUE THREAD

**Issue by Pantau123** [microsoft/vcpkg#635]
Hi,
i miss a Feature to get vcpkg on a hosted TFS Server...
It is planned to build this Feature??

**Comment by ras0219-msft** [comment]
Hi Pantau123,

We definitely support being hosted inside other version control systems, including TFS! There is a spectrum of configurations that you can use, depending on what's best for your particular project. The extremes are:

- Check in _only_ the `installed\` folder containing binaries+headers to your main repository and manage Vcpkg externally (possibly a separate git repo). This will likely be the most familiar for TFS users who previously checked in prebuilt 3rd-party libraries. This will not enable our MSBuild integration by default, but it could be made to work (I'd be happy to help you with that if you choose this). You'll be able to easily take updates via `git pull` in your separate Vcpkg repo and git will help you merge your local customizations with any changes we make.
- Check in a full copy of Vcpkg into your tree. This will make it harder to take updates (you won't be able to `git pull`), but you can more easily install new libraries from the catalog and track the customizations you make against your own source code. If you value having a single monorepo, this option lets you keep that advantage.
- Finally, some users choose to manage Vcpkg entirely through a `git submodule`, with nearly nothing checked into their main source tree. While TFVC obviously doesn't support Git Submodules, you can achieve something very similar by checking in a file or adding a Label that "maps" the separate Vcpkg repository to your current sources.

To give you more specific advice, I'd need to know a bit more about your current workflows. If you're interested, please send us a mail at vcpkg@microsoft.com and we'd be happy to help!

**Comment by tizzo233** [comment]
Hi,
I am trying to set up my tfs hosted project to build with vcpkg installed libraries. I have checked the installed\ folder to my project. How do configure msbuild launched by TFS to use this folder, when searching for the dependencies? Do I have to update each project properties file to look in that folder for sources?

**Comment by ras0219-msft** [comment]
Hi @tizzo233!

Since the above post we've added the `export` command, which enables a much smoother workflow here.

The easiest way to handle this is now to use `vcpkg export <packages> --nuget`. This will create a complete NuGet bundle which you can upload to a local NuGet feed for consumption. NuGet also supports installing from the local filesystem, so checking in the NuGet package to your TFS instance could also work.

Alternatively, you can use `vcpkg export <packages> --raw` which will create a flat layout that you can check in to TFS. You'll need to import the targets file at `scripts\buildsystems\msbuild\vcpkg.targets` into your MSBuild projects towards the top.

**Comment by tizzo233** [comment]
This is great thanks!

**Comment by tizzo233** [comment]
Hi, so I tried the nuget route, but I am having issues with pushing the nuget package to my tfs feed. It seems to be a common problem. Installing from local filesystem is also giving me errors.
So it looks like checking in the flattenned layout would be the best approach. How do I import the targets file to my MSBuild projects? Is this a setting in the project properties file?
Thanks

**Comment by LilyWangL** [comment]
This issue hasn’t been updated in two year, if it is still an issue, please reopen.
