### ISSUE TITLE
Stricter version in CONTROL file

### ISSUE THREAD

**Issue by invy** [microsoft/vcpkg#6351]
Since vcpkg treats version in CONTORL file as string it allows to put everything there.
This solution has of course good pragmatic side with such huge variety of libraries, but some ports have just 'lacking' version information or have something 'useless':
ports/beast/CONTROL:Version: 0
ports/atlmfc/CONTROL:Version: 0
ports/getopt/CONTROL:Version: 0
ports/catch/CONTROL:Version: alias
some packages have (IMO) rather unneeded prefix/suffix:
ports/cpptoml/CONTROL:Version: v0.1.1
ports/libzip/CONTROL:Version: rel-1-5-2
ports/log4cplus/CONTROL:Version: REL_2_0_3
ports/opencl/CONTROL:Version: 2.2 (2017.07.18)

Additionally vcpkg just accepts almost empty CONTROL file (w/o description and version)
I think vcpkg should check for empty version or just "0" and fail.
Prefixes should be rather denied during review unless they are inherent part of the version of some specific port, like in case of openssl: 1.0.2q

**Comment by PhoebeHui** [comment]
For CONTROL file, we have doc [control-files.md](https://github.com/microsoft/vcpkg/blob/e62d1361288e83eba786395b60361ab35ba83800/docs/maintainers/control-files.md), and from the [roadmap](https://github.com/microsoft/vcpkg/wiki/Roadmap) it will be changed in future.
