### ISSUE TITLE
Failed Install OpenCV Cuda

### ISSUE THREAD

**Issue by ferdyandannes** [microsoft/vcpkg#6362]
Hello, I have several question related to the installation of opencv[cuda]
I tried to install opencv CUDA, but it always failed like this error :  

Elapsed time for package cuda:x64-windows: 2.55 s
Starting package 3/3: opencv:x64-windows
Building package opencv[contrib,core,cuda,eigen,flann,jpeg,opengl,png,tiff]:x64-windows...
-- Using cached F:/vcpkg/downloads/opencv-opencv-3.4.3.tar.gz
-- Using source at F:/vcpkg/buildtrees/opencv/src/3.4.3-701a6234df
-- Using cached F:/vcpkg/downloads/opencv-cache/data/7505c44ca4eb54b4ab1e4777cb96ac05-face_landmark_model.dat
-- Using cached F:/vcpkg/downloads/opencv-cache/tiny_dnn/adb1c512e09ca2c7a6faef36f9c53e59-v1.0.0a3.tar.gz
-- Using cached F:/vcpkg/downloads/opencv-opencv_contrib-3.4.3.tar.gz
-- Using source at F:/vcpkg/buildtrees/opencv/src/3.4.3-98dbf13329
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:202 (message):
    Command failed: F:/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v
    Working Directory: F:/vcpkg/buildtrees/opencv/x64-windows-dbg
    See logs for more information:
      F:\vcpkg\buildtrees\opencv\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/opencv/portfile.cmake:323 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package opencv:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv:x64-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

Based on this error, I already using the newest version of vcpkg but it keep give me this error, is there any one has solve this problem? Thank you

My Log file : 
https://github.com/ferdyandannes/log

This is my environment : 
CUDA : CUDA 9 (V9.0.176)
CUDNN : 7.0.5
GTX 1050 2GB
Visual Studio 2017 version 15.9.11

**Comment by Voskrese** [comment]
`-- Could NOT find Protobuf (missing: Protobuf_LIBRARIES Protobuf_INCLUDE_DIR) `

**Comment by Voskrese** [comment]
https://github.com/ferdyandannes/log
opencv/x64-windows

hmm ...

> -- Install configuration: "Release"
ok
> -- Install configuration: "Debug"
failed

c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt/host_config.h(133): fatal error C1189: #error: -- unsupported Microsoft Visual Studio version! Only the versions 2012, 2013, 2015 and 2017 are supported!

**Comment by Voskrese** [comment]
https://github.com/microsoft/vcpkg/issues/289#issuecomment-487523558

> edit host_config.h, my locations CUDA
> C:\Program Files\PGI\win64\2018\cuda\9.2\include\crt\host_config.h
> 
> #if _MSC_VER < 1600 || _MSC_VER > 1913
> #error -- unsupported Microsoft Visual Studio version! Only the versions 2012, 2013, 2015 and 2017 are supported!
> 
> to
> #if _MSC_VER < 1600 || _MSC_VER > 1920

**Comment by ferdyandannes** [comment]
> [#289 (comment)](https://github.com/microsoft/vcpkg/issues/289#issuecomment-487523558)
> 
> > edit host_config.h, my locations CUDA
> > C:\Program Files\PGI\win64\2018\cuda\9.2\include\crt\host_config.h
> > #if _MSC_VER < 1600 || _MSC_VER > 1913
> > #error -- unsupported Microsoft Visual Studio version! Only the versions 2012, 2013, 2015 and 2017 are supported!
> > to
> > #if _MSC_VER < 1600 || _MSC_VER > 1920

Hence based on my error, do you think that I must change to higher version of CUDA or change the version of visual studio (for example VS 2019) ?

**Comment by Voskrese** [comment]
`_MSC_VER > 1913` to `_MSC_VER > 3000` ))

**Comment by Voskrese** [comment]
_MSC_VER > 1913 = `MSVC 2017 rev 3` = `201703 `= `1703`

**Comment by ferdyandannes** [comment]
> _MSC_VER > 1913 = `MSVC 2017 rev 3` = `(Visual Studio 2017 version 15.6)`
> 
> https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B
> Visual Studio `2017 version 15.9.11` = `1916`
> 
> from `< 1600 || > 1920` before
> 
> > if you don't quite understand, put CUDA 10+ there are no such problems, and the integration is fixed

Okay thank you very much for your suggestion
I will try it soon

**Comment by ferdyandannes** [comment]
> _MSC_VER > 1913 = `MSVC 2017 rev 3` = `(Visual Studio 2017 version 15.6)`
> 
> https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B
> Visual Studio `2017 version 15.9.11` = `1916`
> 
> from `< 1600 || > 1920` before
> 
> > if you don't quite understand, put CUDA 10+ there are no such problems, and the integration is fixed

Thank for your suggestion, right now my openCV able to run with CUDA without any problem
