### ISSUE TITLE
[ace] Add support for features (ssl, wchar, xml)

### ISSUE THREAD

**Issue by florin-crisan** [microsoft/vcpkg#6372]
I need to be able to use the additional features of ACE (such as ACE_SSL), which is not currently built by vcpkg.

Pull request coming shortly

**Comment by florin-crisan** [comment]
Merged into master

https://github.com/microsoft/vcpkg/pull/6376

**Comment by gnaggnoyil** [comment]
Correct me if I'm wrong, but I thought the `uses_wchar=1` option when building ACE does not *add* the API that support wchar to the original API, but rather *replace* it. The description in `CONTROL` file therefore seems to be misleading.
