### ISSUE TITLE
hash mismatch error due to #6127

### ISSUE THREAD

**Issue by jasjuang** [microsoft/vcpkg#6377]
I cleared my downloads folder and this still happens

```
Starting package 1/30: qt5-speech:x64-windows
Building package qt5-speech[core]:x64-windows...
-- Downloading http://download.qt.io/official_releases/qt/5.12/5.12.1/submodules/qtspeech-everywhere-src-5.12.1.tar.xz...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:96 (message):


  File does not have expected hash:

          File path: [ C:/dev/vcpkg/downloads/temp/qtspeech-everywhere-src-5.12.1.tar.xz ]
      Expected hash: [ 9623a83cdfbed07dffcd8f0808c2a514c97fda72b68827d917f1a8ee3072286ef8bce06b114db94d7a0c3fc79425c2540fa5cadc6551367fd4431e5396395932 ]
        Actual hash: [ 321f6dafe0751af1e9cb5bd32f340ae445d2d148a8d2060bd5bd65d034f242547a79667253a4d1e220ccd4f59ea36a7fbe1b50093f36e2017b872f2b858050d2 ]

  The file may have been corrupted in transit.  This can be caused by
  proxies.  If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
  environment variables to
  "https://user:password@your-proxy-ip-address:port/".
```

**Comment by TheScarfix** [comment]
Update first so you get the new modularscripts which download 5.12.3 :)

**Comment by jasjuang** [comment]
Can you let me know what do you mean by "update"? I am on the latest master and I did bootstrap again and remove the everything in downloads folder but the error is still there.

**Comment by TheScarfix** [comment]
Use vcpkg update and vcpkg upgrade to update the installed libraries.

**Comment by jasjuang** [comment]
Due to the initial failure I don't have the old qt5 installed anymore, I can only install from scratch by calling `vcpkg install qt5-speech` and it doesn't work due to the hash error.

**Comment by TheScarfix** [comment]
Does it try to install qt5-modularscripts? Because your version of it tries to download 5.12.1, which fails because the hash is for 5.12.3. Try removing qt5-modularscripts and reinstalling it and then qt5-speech again

**Comment by jasjuang** [comment]
Thanks. For some reason I need to `vcpkg remove qt5-modularscripts` and then `vcpkg install qt5-modularscripts` and then `vcpkg install qt5-speech` to make it work.
