### ISSUE TITLE
availability of the headers and libs of installed packages

### ISSUE THREAD

**Issue by amigo421** [Microsoft/vcpkg#638]
thisis not a bug or feature request, just please clarify the understanding
I've installed cpprestsdk (and supporting libs ), and perfromed integrate install too.
from your doc, this should be available from c++ sources like this:
#include <cpprest/json.h>
and explicit linking is not required. 
is it correct understanding? 

because , the include above doesn't work, my cmake project can't find this. 
could you explain how of this magic expecting work? I don't see that LIB/INCLUDE env variables extended with a path to the new packages....

just for sure - I've tried in my fav IDE qt creator, to make test clear - tried in VS2017 (latest update) ,
the same problem.
can this be related with that I'm using cmake-based project in both cases, including VS2017?

**Comment by amigo421** [comment]
cmake version of the using doesn't work as well , 
the attempt to use this via cmake way gave me this (VS2017, cmake project):
added line (into cmakelists: find_package(cpprest REQUIRED)


> 1> Command line: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe  -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\amigo421\AppData\Local\CMakeBuild\39defcff-d11d-d230-8cd8-3df6ab0284b6\build\install" -DCMAKE_TOOLCHAIN_FILE=C:\dev\workspace\vcpkg\scripts\buildsystems\vcpkg.cmake --DCMAKE_BUILD_TYPE="Debug" "C:\dev\workspace\algolist"
> 1> Working directory: C:\Users\amigo421\AppData\Local\CMakeBuild\39defcff-d11d-d230-8cd8-3df6ab0284b6\build\x64-Debug
> 1> CMake Error at C:\dev\workspace\algolist\CMakeLists.txt:8 (find_package):
> 1>   By not providing "Findcpprest.cmake" in CMAKE_MODULE_PATH this project has
> 1>   asked CMake to find a package configuration file provided by "cpprest", but
> 1>   CMake did not find one.
> 1> 
> 1>   Could not find a package configuration file provided by "cpprest" with any
> 1>   of the following names:
> 1> 
> 1>     cpprestConfig.cmake
> 1>     cpprest-config.cmake
> 1> 
> 1>   Add the installation prefix of "cpprest" to CMAKE_PREFIX_PATH or set
> 1>   "cpprest_DIR" to a directory containing one of the above files.  If
> 1>   "cpprest" provides a separate development package or SDK, be sure it has
> 1>   been installed.
> 1> 
> 1

**Comment by ras0219-msft** [comment]
Hi Amigo,

Thanks for the question. Unfortunately, that particular section of docs (and the message displayed after `integrate install`) applies specifically to the MSBuild integration -- that is the experience you should get if you create a new project in Visual Studio (linking automatically handled and header files automatically on your compile line).

When using CMake, we've opted for a more native approach: we make the headers, libraries, and config modules available through the standard `find_path()`, `find_library()` and `find_package()`. I suspect you tried `find_package(cpprest REQUIRED)`, which _would_ work for many libraries! However, the upstream cpprestsdk project unfortunately does not provide a `find_package()` config module (we are considering generating these config files automatically in #616). Therefore, you will need to use something like

```cmake
find_library(CPPREST_LIBRARY NAMES cpprest_2_9)
find_path(CPPREST_INCLUDE_DIR "cpprest/http_client.h")
if(CPPREST_INCLUDE_DIR MATCHES "NOTFOUND" OR CPPREST_LIBRARY MATCHES "NOTFOUND")
  message(FATAL_ERROR "Could not find cpprestsdk")
endif()

# replace with target_X_Ys as appropriate
include_directories(${CPPREST_INCLUDE_DIR})
link_libraries(${CPPREST_LIBRARY})
```
For cpprestsdk specifically, you will also need to find and link Boost, OpenSSL, and Zlib. For those other libraries, `find_package()` will work exactly as you expected.

For buildsystems other than CMake and MSBuild, you will need to add the paths directly [1].

Finally, I'll leave this issue open to track improving in our documentation and clarifying this experience; the above should definitely be made clearer for first time users!

[1] https://github.com/Microsoft/vcpkg/blob/master/docs/EXAMPLES.md#example-1-2-c

**Comment by amigo421** [comment]
tried your advice, but unsuccessful.
started from zlib and openssl, as you said those should work without manual work (unlike cpprest).

so this is a log of cmake (from the output of qt creator)
(you see that toolchain has been specified, in a parameters of cmake,
see screenshots below , to confirm that all components are okay) 
> Running "C:\dev\cxx\CMake\bin\cmake.exe C:/dev/workspace/algolist "-GCodeBlocks - NMake Makefiles" "-DCMAKE_CXX_COMPILER:STRING=C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/BIN/amd64/cl.exe" "-DCMAKE_C_COMPILER:STRING=C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/BIN/amd64/cl.exe" "-DCMAKE_PREFIX_PATH:STRING=%{Qt:QT_INSTALL_PREFIX}" "-DCMAKE_TOOLCHAIN_FILE:FILEPATH=C:/dev/workspace/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DQT_QMAKE_EXECUTABLE:STRING="" in C:\Users\amigo421\AppData\Local\Temp\qtc-cmake-6xde6r.
> -- The C compiler identification is MSVC 19.0.24210.0
> -- The CXX compiler identification is MSVC 19.0.24210.0
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/BIN/amd64/cl.exe
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/BIN/amd64/cl.exe -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/BIN/amd64/cl.exe
> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/BIN/amd64/cl.exe -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Could NOT find ZLIB (missing:  ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
> -- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing:  OPENSSL_LIBRARIES OPENSSL_INCLUDE_DIR) 
> -- Found Git: C:/dev/tools/git/cmd/git.exe (found version "2.9.0.windows.1") 
> 

![image](https://cloud.githubusercontent.com/assets/3259933/22739548/21317ff8-ee1d-11e6-9b5e-15902bc035d4.png)


![image](https://cloud.githubusercontent.com/assets/3259933/22739639/7e18af3e-ee1d-11e6-9d2b-d1c54d7c13c1.png)

**Comment by amigo421** [comment]
just for sure - tried this from VSCode with CMakeTools,
the same output with not found libs - zlib and openssl

**Comment by ras0219-msft** [comment]
Thanks for the detailed responses. I think the issue is that you're targeting 64-bit and all the packages you've installed are `x86-windows`. Could you first try running `vcpkg install zlib:x64-windows openssl:x64-windows` and then re-configure your CMake [1]?

If that doesn't fix it:
The generator _shouldn't_ affect the results. However, to ensure that we've completely eliminated the IDE and generator as possible causes, could you try a from-scratch configure on the command line using the default MSBuild generator? Specifically, do _not_ reuse an existing buildtree. When changing the toolchain file, CMake often doesn't regenerate correctly -- and deleting the CMakeCache.txt isn't sufficient!

If you're able to generate correctly using the command line, then I would guess that the IDE simply didn't purge enough of the CMake state when you changed the `CMAKE_TOOLCHAIN_FILE` property. If that's the problem, completely deleting the buildtree and having the IDE rebuild it from scratch (with the right settings) should solve it.

If it still doesn't work, my only guess would be that we may not handle `DCMAKE_PREFIX_PATH:STRING=%{Qt:QT_INSTALL_PREFIX}"` correctly (I think that's _very_ unlikely, but it's the only remaining factor I see).

[1] As an aside, we always use the files inside the `installed\` directory, not the `packages\` directory. `vcpkg list` will give you the correct list of actively installed packages, and `vcpkg owns` can be used to find specific files like `zlib.h`.

**Comment by amigo421** [comment]
this is an attempt to install cpprestsdk:x64-windows

![image](https://cloud.githubusercontent.com/assets/3259933/22771670/42a77d2c-eea9-11e6-90f9-d49db5aaba0c.png)

**Comment by amigo421** [comment]
another issue with an installing openssl:x64-windows
(just for sure - I'm using C++ Build Tools from 2015, not from 2017,
WinSDK 8.1 and WinSDK 10.
I see you are using 8.1 for the build of vcpkg, but 10 for the packages)

![image](https://cloud.githubusercontent.com/assets/3259933/22772017/4a17017a-eeab-11e6-85a2-7f5e74da4ff2.png)

from build-x64-windows-rel-out.log
> Copying: ./ssl/dtls1.h to inc32/openssl/dtls1.h
> 	perl .\util\copy-if-different.pl ".\ssl\kssl.h" "inc32\openssl\kssl.h"
> Copying: ./ssl/kssl.h to inc32/openssl/kssl.h
> 	perl .\util\copy-if-different.pl ".\ssl\srtp.h" "inc32\openssl\srtp.h"
> Copying: ./ssl/srtp.h to inc32/openssl/srtp.h
> 	perl util/copy.pl ms\applink.c inc32\openssl\applink.c
> Copying: ms/applink.c to inc32/openssl/applink.c
> 	cl /Fotmp32dll\uplink.obj -Iinc32 -Itmp32dll /MD /Ox -DOPENSSL_THREADS  -DDSO_WIN32 -W3 -Gs0 -Gy -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -DUNICODE -D_UNICODE -D_CRT_SECURE_NO_DEPRECATE -DOPENSSL_USE_APPLINK -I. -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_SSL2 -DOPENSSL_NO_KRB5 -DOPENSSL_NO_JPAKE -DOPENSSL_NO_WEAK_SSL_CIPHERS -DOPENSSL_NO_DYNAMIC_ENGINE /Zi /Fdtmp32dll/lib -D_WINDLL  -c ms\uplink.c
> uplink.c
> C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um\winbase.h(55): fatal error C1083: Cannot open include file: 'bemapiset.h': No such file or directory
>

**Comment by ras0219-msft** [comment]
That's great to hear! (-- zlib is working)

Thanks for posting that log snippet -- I was about to ask for them 😉.

It looks like there may be an issue with your Windows 10 SDK. The recommended fix [1] was to reinstall it.

[1] https://social.msdn.microsoft.com/Forums/en-US/c089302e-c3ad-43f9-b89a-f20f46b4b4ab/windows-sdk-100102400-missing-file-bemapiseth?forum=windowssdk

**Comment by ras0219-msft** [comment]
Note that we explicitly ignore your environment settings and set the compiler paths internally for the VS install we determined is needed. Among other things, you can add `vcpkg.exe` to your system path and we will always do the right thing (change to the right directory, find the compiler, etc). We always prefer 2017 if it's available and fall back to 2015 if it's not. They are completely binary compatible, so this is safe to do.

As for the 8.1 vs 10 SDK bug, we're actively working on fixing that one 😄.

All of the above said, I'm not sure how your x86 builds worked fine and your x64 ones are having such trouble. Could you send us the build logs for your boost-x64-windows build at vcpkg@microsoft.com?

**Comment by amigo421** [comment]
re-install sdk 10 fixed the problem with bemapi header. but the build of boost still doesn't work, I'll send the logs on the email

**Comment by amigo421** [comment]
sent two emails with openssl issue description and logs and boost ones

**Comment by amigo421** [comment]
another issue with a trying to use CatchLib.
please assist with a using this
(earlier I was including catchlib by ExternalProject_Add from cmake script directly,
you see commented out line)

> C:\dev\workspace\vcpkg>vcpkg install catch:x64-windows
> Package catch:x64-windows is already installed
confirmation that Catch has been installed.

cmake_minimum_required(VERSION 3.2)
project(algolist_tests)

```
# include(AddCatch)
find_package(catch REQUIRED)

file(GLOB SOURCE_FILES "*.cpp")
if (${MSVC})
    set(CMAKE_CXX_FLAGS_DEBUG "/MTd")
...
```

> CMake Error at tests/unit/CMakeLists.txt:5 (find_package):
>   By not providing "Findcatch.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "catch", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "catch" with any of
>   the following names:
> 
>     catchConfig.cmake
>     catch-config.cmake
> 
>   Add the installation prefix of "catch" to CMAKE_PREFIX_PATH or set
>   "catch_DIR" to a directory containing one of the above files.  If "catch"
>   provides a separate development package or SDK, be sure it has been
>   installed.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "C:/dev/workspace/algolist/build/CMakeFiles/CMakeOutput.log".
> [vscode] cmake exited with return code 1

**Comment by ras0219-msft** [comment]
Looking at the boost logs, I found:
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory
```
Searching online, this error _generally_ occurred for users who had CTP versions of 2015 installed. Could you triple check that you have VS2015 update 3 installed? (Boost unfortunately still builds with 2015 for the moment).

**Comment by amigo421** [comment]
I don't use VS itself, only c++ build tools, I believed that is an installer only and this downloads latest CRT, SDK, etc from the inet...
okay, let me check. 
thank you!

**Comment by amigo421** [comment]
can be closed. all works fine. as you described above
