### ISSUE TITLE
./vcpkg install libmysql:x64-linux    FAIL   !!!!

### ISSUE THREAD

**Issue by ywj11407** [microsoft/vcpkg#6389]
### config-x64-linux-dbg-err.log
CMake Deprecation Warning at CMakeLists.txt:52 (CMAKE_POLICY):
  The OLD behavior for policy CMP0045 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

CMake Warning (dev) at /third/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/share/cmake-3.14/Modules/CheckIncludeFiles.cmake:120 (message):
  Policy CMP0075 is not set: Include file check macros honor
  CMAKE_REQUIRED_LIBRARIES.  Run "cmake --help-policy CMP0075" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  CMAKE_REQUIRED_LIBRARIES is set to:

    m;crypt;dl;-lpthread;rt;atomic

  For compatibility with CMake 3.11 and below this check is ignoring it.
Call Stack (most recent call first):
  configure.cmake:188 (CHECK_INCLUDE_FILES)
  CMakeLists.txt:653 (INCLUDE)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at configure.cmake:459 (STRING):
  STRING no output variable specified
Call Stack (most recent call first):
  CMakeLists.txt:653 (INCLUDE)

CMake Error at cmake/readline.cmake:71 (MESSAGE):
  Curses library not found.  Please install appropriate package,

      remove CMakeCache.txt and rerun cmake.On Debian/Ubuntu, package name is libncurses5-dev, on Redhat and derivates it is ncurses-devel.
Call Stack (most recent call first):
  cmake/readline.cmake:99 (FIND_CURSES)
  cmake/readline.cmake:190 (MYSQL_USE_BUNDLED_EDITLINE)
  CMakeLists.txt:681 (MYSQL_CHECK_EDITLINE)

### config-x64-linux-dbg-out.log

-- Running cmake version 3.14.0
-- Found Git: /usr/bin/git (found version "2.17.1") 
-- Configuring with MAX_INDEXES = 64U
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_GENERATOR: Ninja
-- Looking for SHM_HUGETLB
-- Looking for SHM_HUGETLB - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void *
-- Check size of void * - done
-- SIZEOF_VOIDP 8
-- Performing Test HAVE_NOT_C_BUG_LOOP_VECTORIZE
-- Performing Test HAVE_NOT_C_BUG_LOOP_VECTORIZE - Success
-- Performing Test HAVE_NOT_CXX_BUG_LOOP_VECTORIZE
-- Performing Test HAVE_NOT_CXX_BUG_LOOP_VECTORIZE - Success
-- Performing Test HAVE_NOT_C_SHIFT_OR_OPTIMIZATION_BUG
-- Performing Test HAVE_NOT_C_SHIFT_OR_OPTIMIZATION_BUG - Success
-- Performing Test HAVE_NOT_CXX_SHIFT_OR_OPTIMIZATION_BUG
-- Performing Test HAVE_NOT_CXX_SHIFT_OR_OPTIMIZATION_BUG - Success
-- Performing Test HAVE_C_FLOATING_POINT_FUSED_MADD
-- Performing Test HAVE_C_FLOATING_POINT_FUSED_MADD - Failed
-- Performing Test HAVE_CXX_FLOATING_POINT_FUSED_MADD
-- Performing Test HAVE_CXX_FLOATING_POINT_FUSED_MADD - Failed
-- MySQL 8.0.4-rc
-- Packaging as: mysql-8.0.4-rc-Linux-
-- Performing Test C_LD_GOLD_RESULT
-- Performing Test C_LD_GOLD_RESULT - Success
-- Performing Test CXX_LD_GOLD_RESULT
-- Performing Test CXX_LD_GOLD_RESULT - Success
-- Found /third/vcpkg/installed/x64-linux/include/boost/version.hpp 
-- BOOST_VERSION_NUMBER is #define BOOST_VERSION 106700
-- BOOST_INCLUDE_DIR /third/vcpkg/installed/x64-linux/include
-- Performing Test HAVE_LLVM_LIBCPP
-- Performing Test HAVE_LLVM_LIBCPP - Failed
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for floor
-- Looking for floor - not found
-- Looking for floor in m
-- Looking for floor in m - found
-- Looking for gethostbyname_r
-- Looking for gethostbyname_r - found
-- Looking for bind
-- Looking for bind - found
-- Looking for crypt
-- Looking for crypt - not found
-- Looking for crypt in crypt
-- Looking for crypt in crypt - found
-- Looking for setsockopt
-- Looking for setsockopt - found
-- Looking for dlopen
-- Looking for dlopen - not found
-- Looking for dlopen in dl
-- Looking for dlopen in dl - found
-- Looking for sched_yield
-- Looking for sched_yield - found
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Looking for timer_create
-- Looking for timer_create - not found
-- Looking for timer_create in rt
-- Looking for timer_create in rt - found
-- Looking for atomic_thread_fence
-- Looking for atomic_thread_fence - not found
-- Looking for atomic_thread_fence in atomic
-- Looking for atomic_thread_fence in atomic - found
-- Looking for backtrace
-- Looking for backtrace - found
-- Looking for include file alloca.h
-- Looking for include file alloca.h - found
-- Looking for include file arpa/inet.h
-- Looking for include file arpa/inet.h - found
-- Looking for include file dlfcn.h
-- Looking for include file dlfcn.h - found
-- Looking for include file endian.h
-- Looking for include file endian.h - found
-- Looking for include file execinfo.h
-- Looking for include file execinfo.h - found
-- Looking for include file fpu_control.h
-- Looking for include file fpu_control.h - found
-- Looking for include file grp.h
-- Looking for include file grp.h - found
-- Looking for include file ieeefp.h
-- Looking for include file ieeefp.h - not found
-- Looking for include file langinfo.h
-- Looking for include file langinfo.h - found
-- Looking for include file malloc.h
-- Looking for include file malloc.h - found
-- Looking for include file netinet/in.h
-- Looking for include file netinet/in.h - found
-- Looking for include file poll.h
-- Looking for include file poll.h - found
-- Looking for include file pwd.h
-- Looking for include file pwd.h - found
-- Looking for include file strings.h
-- Looking for include file strings.h - found
-- Looking for include file sys/cdefs.h
-- Looking for include file sys/cdefs.h - found
-- Looking for include file sys/ioctl.h
-- Looking for include file sys/ioctl.h - found
-- Looking for include file sys/mman.h
-- Looking for include file sys/mman.h - found
-- Looking for include file sys/resource.h
-- Looking for include file sys/resource.h - found
-- Looking for include file sys/select.h
-- Looking for include file sys/select.h - found
-- Looking for include file sys/socket.h
-- Looking for include file sys/socket.h - found
-- Looking for include files curses.h, term.h
-- Looking for include files curses.h, term.h - not found
-- Looking for include file termios.h
-- Looking for include file termios.h - found
-- Looking for include file termio.h
-- Looking for include file termio.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file sys/wait.h
-- Looking for include file sys/wait.h - found
-- Looking for include file sys/param.h
-- Looking for include file sys/param.h - found
-- Looking for include file fnmatch.h
-- Looking for include file fnmatch.h - found
-- Looking for include file sys/un.h
-- Looking for include file sys/un.h - found
-- Looking for include file vis.h
-- Looking for include file vis.h - not found
-- Looking for include file sasl/sasl.h
-- Looking for include file sasl/sasl.h - not found
-- Looking for include file sys/devpoll.h
-- Looking for include file sys/devpoll.h - not found
-- Looking for include file sys/epoll.h
-- Looking for include file sys/epoll.h - found
-- Looking for TAILQ_FOREACH
-- Looking for TAILQ_FOREACH - found
-- Looking for _aligned_malloc
-- Looking for _aligned_malloc - not found
-- Looking for backtrace
-- Looking for backtrace - found
-- Looking for printstack
-- Looking for printstack - not found
-- Looking for index
-- Looking for index - found
-- Looking for chown
-- Looking for chown - found
-- Looking for cuserid
-- Looking for cuserid - found
-- Looking for directio
-- Looking for directio - not found
-- Looking for ftruncate
-- Looking for ftruncate - found
-- Looking for fchmod
-- Looking for fchmod - found
-- Looking for fcntl
-- Looking for fcntl - found
-- Looking for fdatasync
-- Looking for fdatasync - found
-- Looking for fdatasync
-- Looking for fdatasync - found
-- Looking for fedisableexcept
-- Looking for fedisableexcept - found
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for fsync
-- Looking for fsync - found
-- Looking for gethrtime
-- Looking for gethrtime - not found
-- Looking for getnameinfo
-- Looking for getnameinfo - found
-- Looking for getpass
-- Looking for getpass - found
-- Looking for getpassphrase
-- Looking for getpassphrase - not found
-- Looking for getpwnam
-- Looking for getpwnam - found
-- Looking for getpwuid
-- Looking for getpwuid - found
-- Looking for getrlimit
-- Looking for getrlimit - found
-- Looking for getrusage
-- Looking for getrusage - found
-- Looking for initgroups
-- Looking for initgroups - found
-- Looking for issetugid
-- Looking for issetugid - not found
-- Looking for getuid
-- Looking for getuid - found
-- Looking for geteuid
-- Looking for geteuid - found
-- Looking for getgid
-- Looking for getgid - found
-- Looking for getegid
-- Looking for getegid - found
-- Looking for madvise
-- Looking for madvise - found
-- Looking for malloc_info
-- Looking for malloc_info - found
-- Looking for memrchr
-- Looking for memrchr - found
-- Looking for mlock
-- Looking for mlock - found
-- Looking for mlockall
-- Looking for mlockall - found
-- Looking for mmap64
-- Looking for mmap64 - found
-- Looking for poll
-- Looking for poll - found
-- Looking for posix_fallocate
-- Looking for posix_fallocate - found
-- Looking for posix_memalign
-- Looking for posix_memalign - found
-- Looking for pread
-- Looking for pread - found
-- Looking for pthread_condattr_setclock
-- Looking for pthread_condattr_setclock - found
-- Looking for pthread_sigmask
-- Looking for pthread_sigmask - found
-- Looking for setfd
-- Looking for setfd - not found
-- Looking for sigaction
-- Looking for sigaction - found
-- Looking for sleep
-- Looking for sleep - found
-- Looking for stpcpy
-- Looking for stpcpy - found
-- Looking for stpncpy
-- Looking for stpncpy - found
-- Looking for strlcpy
-- Looking for strlcpy - not found
-- Looking for strndup
-- Looking for strndup - found
-- Looking for strlcat
-- Looking for strlcat - not found
-- Looking for strsignal
-- Looking for strsignal - found
-- Looking for fgetln
-- Looking for fgetln - not found
-- Looking for strsep
-- Looking for strsep - found
-- Looking for tell
-- Looking for tell - not found
-- Looking for vasprintf
-- Looking for vasprintf - found
-- Looking for memalign
-- Looking for memalign - found
-- Looking for nl_langinfo
-- Looking for nl_langinfo - found
-- Looking for ntohll
-- Looking for ntohll - not found
-- Looking for epoll_create
-- Looking for epoll_create - found
-- Looking for inet_ntop
-- Looking for inet_ntop - found
-- Looking for kqueue
-- Looking for kqueue - not found
-- Looking for timeradd
-- Looking for timeradd - found
-- Looking for timerclear
-- Looking for timerclear - found
-- Looking for timercmp
-- Looking for timercmp - found
-- Looking for timerisset
-- Looking for timerisset - found
-- Looking for include file sys/time.h
-- Looking for include file sys/time.h - found
-- Looking for include file sys/times.h
-- Looking for include file sys/times.h - found
-- Looking for times
-- Looking for times - found
-- Looking for gettimeofday
-- Looking for gettimeofday - found
-- Looking for lrand48
-- Looking for lrand48 - found
-- Looking for TIOCGWINSZ
-- Looking for TIOCGWINSZ - found
-- Looking for FIONREAD
-- Looking for FIONREAD - found
-- Looking for FIONREAD
-- Looking for FIONREAD - not found
-- Looking for isinf
-- Looking for isinf - found
-- Performing Test HAVE_CXX_ISINF
-- Performing Test HAVE_CXX_ISINF - Success
-- Looking for timer_create
-- Looking for timer_create - found
-- Looking for timer_settime
-- Looking for timer_settime - found
-- Looking for kqueue
-- Looking for kqueue - not found
-- Looking for EVFILT_TIMER
-- Looking for EVFILT_TIMER - not found
-- Check if the system is big endian
-- Searching 16 bit integer
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Check size of uint8_t
-- Check size of uint8_t - done
-- Check size of uint16_t
-- Check size of uint16_t - done
-- Check size of uint32_t
-- Check size of uint32_t - done
-- Check size of uint64_t
-- Check size of uint64_t - done
-- Check size of char *
-- Check size of char * - done
-- Check size of long
-- Check size of long - done
-- Check size of short
-- Check size of short - done
-- Check size of int
-- Check size of int - done
-- Check size of long long
-- Check size of long long - done
-- Check size of off_t
-- Check size of off_t - done
-- Check size of time_t
-- Check size of time_t - done
-- Check size of ulong
-- Check size of ulong - done
-- Check size of u_int32_t
-- Check size of u_int32_t - done
-- Check size of socklen_t
-- Check size of socklen_t - done
-- Performing Test HAVE_VISIBILITY_HIDDEN
-- Performing Test HAVE_VISIBILITY_HIDDEN - Success
-- Performing Test HAVE_CLOCK_GETTIME
-- Performing Test HAVE_CLOCK_GETTIME - Success
-- Performing Test HAVE_CLOCK_REALTIME
-- Performing Test HAVE_CLOCK_REALTIME - Success
-- Looking for include files time.h, sys/time.h
-- Looking for include files time.h, sys/time.h - found
-- Looking for O_NONBLOCK
-- Looking for O_NONBLOCK - found
-- Performing Test HAVE_FAKE_PAUSE_INSTRUCTION
-- Performing Test HAVE_FAKE_PAUSE_INSTRUCTION - Success
-- Performing Test HAVE_HMT_PRIORITY_INSTRUCTION
-- Performing Test HAVE_HMT_PRIORITY_INSTRUCTION - Failed
-- Looking for C++ include cxxabi.h
-- Looking for C++ include cxxabi.h - found
-- Performing Test HAVE_ABI_CXA_DEMANGLE
-- Performing Test HAVE_ABI_CXA_DEMANGLE - Success
-- Performing Test HAVE_BUILTIN_UNREACHABLE
-- Performing Test HAVE_BUILTIN_UNREACHABLE - Success
-- Performing Test HAVE_BUILTIN_EXPECT
-- Performing Test HAVE_BUILTIN_EXPECT - Success
-- Performing Test HAVE_BUILTIN_STPCPY
-- Performing Test HAVE_BUILTIN_STPCPY - Success
-- Performing Test HAVE_GCC_ATOMIC_BUILTINS
-- Performing Test HAVE_GCC_ATOMIC_BUILTINS - Success
-- Performing Test HAVE_GCC_SYNC_BUILTINS
-- Performing Test HAVE_GCC_SYNC_BUILTINS - Success
-- Performing Test HAVE_SYS_GETTID
-- Performing Test HAVE_SYS_GETTID - Success
-- Performing Test HAVE_PTHREAD_GETTHREADID_NP
-- Performing Test HAVE_PTHREAD_GETTHREADID_NP - Failed
-- Performing Test HAVE_PTHREAD_THREADID_NP
-- Performing Test HAVE_PTHREAD_THREADID_NP - Failed
-- Performing Test HAVE_INTEGER_PTHREAD_SELF
-- Performing Test HAVE_INTEGER_PTHREAD_SELF - Success
-- Performing Test HAVE_IMPLICIT_DEPENDENT_NAME_TYPING
-- Performing Test HAVE_IMPLICIT_DEPENDENT_NAME_TYPING - Failed
-- Looking for netinet/in6.h
-- Looking for netinet/in6.h - not found
-- Check size of struct in6_addr
-- Check size of struct in6_addr - failed
-- Performing Test HAVE_SOCKADDR_IN_SIN_LEN
-- Performing Test HAVE_SOCKADDR_IN_SIN_LEN - Failed
-- Performing Test HAVE_SOCKADDR_IN6_SIN6_LEN
-- Performing Test HAVE_SOCKADDR_IN6_SIN6_LEN - Failed
-- Looking for include file numa.h
-- Looking for include file numa.h - not found
-- Looking for include file numaif.h
-- Looking for include file numaif.h - not found
-- NUMA library missing or required version not available
-- Found ZLIB: /third/vcpkg/installed/x64-linux/debug/lib/libz.a (found version "1.2.11") 
-- Found OpenSSL: /third/vcpkg/installed/x64-linux/debug/lib/libcrypto.a (found version "1.0.2o")  
-- Check size of mbstate_t
-- Check size of mbstate_t - done
-- Performing Test HAVE_LANGINFO_CODESET
-- Performing Test HAVE_LANGINFO_CODESET - Success
-- Looking for wcsdup
-- Looking for wcsdup - found
-- Check size of wchar_t
-- Check size of wchar_t - done
-- Check size of wint_t
-- Check size of wint_t - done
-- Could NOT find Curses (missing: CURSES_LIBRARY CURSES_INCLUDE_PATH) 
-- Configuring incomplete, errors occurred!
See also "/third/vcpkg/buildtrees/libmysql/x64-linux-dbg/CMakeFiles/CMakeOutput.log".
See also "/third/vcpkg/buildtrees/libmysql/x64-linux-dbg/CMakeFiles/CMakeError.log".

### patch-x64-linux-0-err.log

Checking patch cmake/boost.cmake...
error: while searching for:
  COULD_NOT_FIND_BOOST()?
ENDIF()?
?
IF(NOT BOOST_MINOR_VERSION EQUAL 65)?
  MESSAGE(WARNING "Boost minor version found is ${BOOST_MINOR_VERSION} "?
    "we need 65"?
    )?

error: patch failed: cmake/boost.cmake:280
error: cmake/boost.cmake: patch does not apply

### patch-x64-linux-1-err.log

Checking patch cmake/icu.cmake...
error: while searching for:
# install_root is either 'system' or is assumed to be a path.?
#?
MACRO (FIND_ICU install_root)?
  IF("${install_root}" STREQUAL "system")?
    SET(EXTRA_FIND_LIB_ARGS)?
    SET(EXTRA_FIND_INC_ARGS)?
  ELSE()?
    SET(EXTRA_FIND_LIB_ARGS HINTS "${install_root}"?
      PATH_SUFFIXES "lib" "lib64" NO_DEFAULT_PATH)?
    SET(EXTRA_FIND_INC_ARGS HINTS "${install_root}"?
      PATH_SUFFIXES "include"     NO_DEFAULT_PATH)?
  ENDIF()?
?
  FIND_PATH(ICU_INCLUDE_DIR NAMES unicode/regex.h ${EXTRA_FIND_INC_ARGS})?
  IF (NOT ICU_INCLUDE_DIR)?
    MESSAGE(FATAL_ERROR "Cannot find ICU regular expression headers")?
  ENDIF()?
?
  IF(WIN32)?
    SET(ICU_LIBS icuuc icuio icudt icuin)?
  ELSE()?
    SET(ICU_LIBS icuuc icuio icudata icui18n)?
  ENDIF()?
?
  SET(ICU_SYSTEM_LIBRARIES)?
  FOREACH(ICU_LIB ${ICU_LIBS})?
    UNSET(ICU_LIB_PATH CACHE)?
    FIND_LIBRARY(ICU_LIB_PATH NAMES ${ICU_LIB} ${EXTRA_FIND_LIB_ARGS})?
    IF(NOT ICU_LIB_PATH)?
      MESSAGE(FATAL_ERROR "Cannot find the ICU library ${ICU_LIB}")?
    ENDIF()?
    LIST(APPEND ICU_SYSTEM_LIBRARIES ${ICU_LIB_PATH})?
  ENDFOREACH()?
?
  # To do: If we include the path in ICU_INCLUDE_DIR, it leads to GUnit?
  # picking up the wrong regex.h header. And it looks like we don't need it;?
  # at least on Linux, the header gets installed in an OS path anyway.?
  IF(NOT "${install_root}" STREQUAL "system")?
    SET(ICU_INCLUDE_DIRS ${ICU_INCLUDE_DIR})?
  ENDIF()?
?
  SET(ICU_LIBRARIES ${ICU_SYSTEM_LIBRARIES})?
?
  # Needed for version information.?
  SET(ICU_COMMON_DIR ${ICU_INCLUDE_DIR})?
?
ENDMACRO()?
?
MACRO (MYSQL_USE_BUNDLED_ICU)?

error: patch failed: cmake/icu.cmake:40
error: cmake/icu.cmake: patch does not apply
Checking patch cmake/lz4.cmake...
error: while searching for:
?
MACRO (FIND_SYSTEM_LZ4)?
  FIND_PATH(PATH_TO_LZ4 NAMES lz4frame.h)?
  FIND_LIBRARY(LZ4_SYSTEM_LIBRARY NAMES lz4)?
  IF (PATH_TO_LZ4 AND LZ4_SYSTEM_LIBRARY)?
    SET(SYSTEM_LZ4_FOUND 1)?
    INCLUDE_DIRECTORIES(SYSTEM ${PATH_TO_LZ4})?

error: patch failed: cmake/lz4.cmake:25
error: cmake/lz4.cmake: patch does not apply
Checking patch cmake/lzma.cmake...
error: while searching for:
# bundled is the default?
?
MACRO (FIND_SYSTEM_LZMA)?
  FIND_PATH(PATH_TO_LZMA NAMES lzma/lzma.h)?
  FIND_LIBRARY(LZMA_SYSTEM_LIBRARY NAMES lzma)?
  IF (PATH_TO_LZMA AND LZMA_SYSTEM_LIBRARY)?
    SET(SYSTEM_LZMA_FOUND 1)?
    SET(LZMA_INCLUDE_DIR ${PATH_TO_LZMA})?
    SET(LZMA_LIBRARY ${LZMA_SYSTEM_LIBRARY})?
    MESSAGE(STATUS "LZMA_INCLUDE_DIR ${LZMA_INCLUDE_DIR}")?
    MESSAGE(STATUS "LZMA_LIBRARY ${LZMA_LIBRARY}")?
  ENDIF()?
ENDMACRO()?
?
MACRO (MYSQL_USE_BUNDLED_LZMA)?

error: patch failed: cmake/lzma.cmake:24
error: cmake/lzma.cmake: patch does not apply
Checking patch cmake/ssl.cmake...
error: while searching for:
# Provides the following configure options:?
# WITH_SSL=[yes|bundled|system|<path/to/custom/installation>]?
MACRO (MYSQL_CHECK_SSL)?
  IF(NOT WITH_SSL)?
    IF(WIN32)?
      CHANGE_SSL_SETTINGS("bundled")?

error: patch failed: cmake/ssl.cmake:104
error: cmake/ssl.cmake: patch does not apply
Checking patch cmake/zlib.cmake...
error: while searching for:
  IF(WITH_ZLIB STREQUAL "bundled")?
    MYSQL_USE_BUNDLED_ZLIB()?
  ELSE()?
    SET(ZLIB_FIND_QUIETLY TRUE)?
    INCLUDE(FindZLIB)?
    IF(ZLIB_FOUND)?
     INCLUDE(CheckFunctionExists)?
      SET(CMAKE_REQUIRED_LIBRARIES z)?
      CHECK_FUNCTION_EXISTS(crc32 HAVE_CRC32)?
      CHECK_FUNCTION_EXISTS(compressBound HAVE_COMPRESSBOUND)?
      CHECK_FUNCTION_EXISTS(deflateBound HAVE_DEFLATEBOUND)?
      SET(CMAKE_REQUIRED_LIBRARIES)?
      IF(HAVE_CRC32 AND HAVE_COMPRESSBOUND AND HAVE_DEFLATEBOUND)?
        SET(ZLIB_LIBRARY ${ZLIB_LIBRARIES} CACHE INTERNAL "System zlib library")?
        SET(WITH_ZLIB "system" CACHE STRING?
          "Which zlib to use (possible values are 'bundled' or 'system')")?
        SET(ZLIB_SOURCES "")?
      ELSE()?
        SET(ZLIB_FOUND FALSE CACHE INTERNAL "Zlib found but not usable")?
        MESSAGE(STATUS "system zlib found but not usable")?
      ENDIF()?
    ENDIF()?
    IF(NOT ZLIB_FOUND)?
      MYSQL_USE_BUNDLED_ZLIB()?
    ENDIF()?
  ENDIF()?
ENDMACRO()?

error: patch failed: cmake/zlib.cmake:51
error: cmake/zlib.cmake: patch does not apply

**Comment by JackBoosY** [comment]
Hi @ywj11407, thanks for reporting this issue!
I've fixed this issue. Please update vcpkg and rebuild libmysql.

Thanks.
