### ISSUE TITLE
Add 'build-only' dependencies

### ISSUE THREAD

**Issue by invy** [microsoft/vcpkg#6390]
It would be useful to specify dependencies only needed for package to be built, but irrelevant for installation. For example:

Build-Depends: zlib
Only-BuildDep: python3

This would mean, that package uses as dependency zlib and it is inherent for it to function, but during the bulid step python3 is involved for some code generation for example and can be 'dropped' later.

On one hand we have tools which can be downloaded. But sometimes it would be nice to build tools yourself and use them.

**Comment by PhoebeHui** [comment]
@invy, we have port[core] which only specify the needed dependencies for a port. Feel free to reopen this if I misunderstand something here.
