### ISSUE TITLE
[OpenSSL] Unable to find debug libraries on Windows

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#6394]
Reason (example from FindOpenSSL in CMake):
   ```
 find_library(LIB_EAY_DEBUG
      NAMES
        libcrypto${_OPENSSL_MSVC_ARCH_SUFFIX}${_OPENSSL_MSVC_RT_MODE}d
        libcrypto${_OPENSSL_MSVC_RT_MODE}d
        libcryptod
        libeay32${_OPENSSL_MSVC_RT_MODE}d
        libeay32d
        cryptod
      NAMES_PER_DIR
      ${_OPENSSL_ROOT_HINTS_AND_PATHS}
      PATH_SUFFIXES
        ${_OPENSSL_PATH_SUFFIXES}
    )
```

The libraries require an extra "d" in debug to be found by CMake

**Comment by NNemec** [comment]
I just stumbled over the same issue: As it seems, about half of the libraries have that "d" the other half don't (no idea how representative that statistic is - that's just based on the packages I have installed.) Which is correct? Should debug libraries have a "d" added or not? Having to deal with a mixture is a real pain..

**Comment by Neumann-A** [comment]
there is no general solution. See: #6014

**Comment by Neumann-A** [comment]
duplicate of #710
