### ISSUE TITLE
Segmentation fault running openvdb[tools]

### ISSUE THREAD

**Issue by aadityacs** [microsoft/vcpkg#6396]
I installed vdb first ( vcpkg install openvdb) followed by the tools ( vcpkg install openvdb[tools] ).

The necessary pre-req libraries were also installed first (vcpkg install zlib boost openexr tbb ).

I then integrated the install .

To execute the vdb_viewer , I cd into the folder with the executable vcpkg/installed/x86-windows/tools/openvdb .
I copy over an example model file ( tried many from the website https://www.openvdb.org/download/ - buddha.vdb for example here ) and tried running the command ./vdb_view buddha.vdb and it results in a segmentation fault.

Further, the package library is out-dated compared to the official release. Could someone kindly fix this ?

**Comment by JackBoosY** [comment]
@BillyONeal Can you please take a look?

Thanks.

**Comment by BillyONeal** [comment]
@aadityacs "Segmentation fault in the resulting program" sounds like a bug in the library, not a bug in vcpkg.

As for "out of date version", it looks like the version in vcpkg is 7.1.0 which matches the latest version in https://github.com/AcademySoftwareFoundation/openvdb as of 2020-11-05.

Is this still relevant?

**Comment by JonLiu1993** [comment]
@aadityacs ,Thanks for posting this issue,The latest version of openvdb in vcpkg is 8.2.0. You can use the latest version of openvdb to see if the problem is solved. I encountered a different error locally according to your reproduction steps and cannot reproduce your error.

./vcpkg install openvdb[tools] 
````
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: F:/test9/vcpkg/packages/openvdb_x86-windows/share/openvdb/usage
-- Installing: F:/test9/vcpkg/packages/openvdb_x86-windows/share/openvdb/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\AppData\Local\vcpkg\archives\c0\c09b48e69061717b1659041a941c8fe43f43af4a615424544136589f30f045ee.zip
Installing package openvdb[core,tools]:x86-windows...
Elapsed time for package openvdb:x86-windows: 2.235 min

Total elapsed time: 7.743 min

The package openvdb provides CMake targets:

    find_package(OpenVDB CONFIG REQUIRED)
    target_link_libraries(main PRIVATE OpenVDB::openvdb)
````
./vcpkg integrate install
````
PS F:\test9\vcpkg> ./vcpkg integrate install
Applied user-wide integration for this vcpkg root.

All MSBuild C++ projects can now #include any installed libraries.
Linking will be handled automatically.
Installing new libraries will make them instantly available.

CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=F:/test9/vcpkg/scripts/buildsystems/vcpkg.cmake"
````
cd into the folder with the executable vcpkg/installed/x86-windows/tools/openvdb
````
PS F:\test9\vcpkg\installed\x86-windows\tools\openvdb> ls


    Directory: F:\test9\vcpkg\installed\x86-windows\tools\openvdb


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         2022/1/27     18:51          60928 blosc.dll
-a----         2022/1/27     18:53         429056 glew32.dll
-a----         2022/1/27     18:53         194048 glfw3.dll
-a----         2022/1/27     18:54         275456 Half-2_5.dll
-a----         2022/1/27     18:54         183296 Iex-2_5.dll
-a----         2022/1/27     18:54        2652160 IlmImf-2_5.dll
-a----         2022/1/27     18:54          35328 IlmThread-2_5.dll
-a----         2022/1/27     18:50          97792 lz4.dll
-a----         2022/1/27     18:51          62464 snappy.dll
-a----         2022/1/27     18:58        2137088 vdb_lod.exe
-a----         2022/1/27     18:57         599040 vdb_render.exe
-a----        2021/12/27     17:52          74752 zlib1.dll
-a----         2022/1/26     19:07         509952 zstd.dll

````
I copy over an example model file ( tried many from the website https://www.openvdb.org/download/ - buddha.vdb for example here ) and tried running the command ./vdb_view icosahedron.vdb   ./vdb_view  icosahedron.vdb   
 ./vdb_view  sphere.vdb   ./vdb_view smoke.vdb
````
PS F:\test9\vcpkg\installed\x86-windows\tools\openvdb> ./vdb_view buddha.vdb
FATAL: IoError: could not get size of file buddha.vdb
PS F:\test9\vcpkg\installed\x86-windows\tools\openvdb> ./vdb_view icosahedron.vdb
ERROR: GLFW Error 65542: WGL: The driver does not appear to support OpenGL
PS F:\test9\vcpkg\installed\x86-windows\tools\openvdb> ./vdb_view sphere.vdb
ERROR: GLFW Error 65542: WGL: The driver does not appear to support OpenGL
PS F:\test9\vcpkg\installed\x86-windows\tools\openvdb> ./vdb_view smoke.vdb
ERROR: GLFW Error 65542: WGL: The driver does not appear to support OpenGL
````

**Comment by BillyONeal** [comment]
Closing this due to lack of response on an old issue that looks like an upstream thing.
