### ISSUE TITLE
building graphicsmagick failed while installing io2d on macOS

### ISSUE THREAD

**Issue by ziyi-yan** [microsoft/vcpkg#6399]
## The machine setup
```bash
~ $ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226
```
## The steps to reproduce
```bash
./vcpkg install io2d
```
## The outcome you expected
io2d would be built and installed without any error messages.

## The actual outcome
cmake reports it failed while building graphicsmagick[core]:x64-osx package

## What package and version you're building
graphicsmagick 1.3.31

## Any relevant error logs from the build process.
Logs in terminal
```bash
vcpkg $ ./vcpkg install io2d
The following packages will be built and installed:
  * cairo[core]:x64-osx
  * gettext[core]:x64-osx
  * glib[core]:x64-osx
  * graphicsmagick[core]:x64-osx
    io2d[core]:x64-osx
  * libffi[core]:x64-osx
  * pcre[core]:x64-osx
Additional packages (*) will be modified to complete this operation.
Starting package 1/7: graphicsmagick:x64-osx
Building package graphicsmagick[core]:x64-osx...
-- Downloading https://sourceforge.net/projects/graphicsmagick/files/graphicsmagick/1.3.31/GraphicsMagick-1.3.31-windows-source.7z...
-- Extracting source /Users/ziyi/vcpkg/downloads/GraphicsMagick-1.3.31-windows-source.7z
-- Applying patch dynamic_bzip2.patch
-- Applying patch disable_graphicsmagick_modules.patch
-- Using source at /Users/ziyi/vcpkg/buildtrees/graphicsmagick/src/1.3.31-3b1f227ad3
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:202 (message):
    Command failed: /Users/ziyi/vcpkg/downloads/tools/cmake-3.14.0-osx/cmake-3.14.0-Darwin-x86_64/CMake.app/Contents/bin/cmake;--build;.;--config;Debug;--target;install;--;-v
    Working Directory: /Users/ziyi/vcpkg/buildtrees/graphicsmagick/x64-osx-dbg
    See logs for more information:
      /Users/ziyi/vcpkg/buildtrees/graphicsmagick/install-x64-osx-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/graphicsmagick/portfile.cmake:35 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package graphicsmagick:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: graphicsmagick:x64-osx
  Vcpkg version: 2018.11.23-unknownhash

Additionally, attach any relevant sections from the log files above.
```
Logs in `/Users/ziyi/vcpkg/buildtrees/graphicsmagick/install-x64-osx-dbg-out.log`
[install-x64-osx-dbg-out.log](https://github.com/microsoft/vcpkg/files/3168645/install-x64-osx-dbg-out.log)

**Comment by ziyi-yan** [comment]
It seems a cross platform-related bug. Could you please take a look? @josuegomes 
Are there any instructions about making a cross-platform package?

**Comment by josuegomes** [comment]
I made some changes to CMakeLists.txt. Could you please give it a try?
Put it under ports/graphicsmagick
If it works I can submit a PR.

I tested in my Linux box. 64-bit only build. I didn't try to use the compiled library though.

[CMakeLists.txt](https://github.com/microsoft/vcpkg/files/3168987/CMakeLists.txt)

**Comment by ziyi-yan** [comment]
I replaced it and built it successfully. But I encounter another problem in building "glib", I can't use my program to test it. Could you provide some code for testing "graphicsmagick"?

**Comment by josuegomes** [comment]
Adjust Makefile accordingly.

[gm-sample.zip](https://github.com/microsoft/vcpkg/files/3169124/gm-sample.zip)

**Comment by ziyi-yan** [comment]
Per the screenshot, I think it works. Thanks!
<img width="1552" alt="屏幕快照 2019-05-11 下午11 36 34" src="https://user-images.githubusercontent.com/44582639/57571861-c220b680-7445-11e9-89e9-3b8836896bb5.png">

**Comment by josuegomes** [comment]
OK, thank you. It's working. I have submitted a PR.
