### ISSUE TITLE
[glib] cannot build glib while installing io2d on macOS

### ISSUE THREAD

**Issue by ziyi-yan** [microsoft/vcpkg#6406]
## The machine setup
```bash
~ $ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226
```
## The steps to reproduce
```bash
./vcpkg install io2d
```
## The outcome you expected
io2d would be built and installed without any error messages.

## The actual outcome
Error: Building package glib:x64-osx failed with: BUILD_FAILED

## What package and version you're building
glib-2.52.3

## Any relevant error logs from the build process.
Logs in terminal
```bash
vcpkg $ ./vcpkg install io2d
The following packages will be built and installed:
  * cairo[core]:x64-osx
  * glib[core]:x64-osx
    io2d[core]:x64-osx
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: glib:x64-osx
Building package glib[core]:x64-osx...
-- Using cached /Users/ziyi/vcpkg/downloads/glib-2.52.3.tar.xz
-- Using source at /Users/ziyi/vcpkg/buildtrees/glib/src/2.52.3-34a15219ec
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:202 (message):
    Command failed: /Users/ziyi/vcpkg/downloads/tools/cmake-3.14.0-osx/cmake-3.14.0-Darwin-x86_64/CMake.app/Contents/bin/cmake;--build;.;--config;Debug;--target;install;--;-v
    Working Directory: /Users/ziyi/vcpkg/buildtrees/glib/x64-osx-dbg
    See logs for more information:
      /Users/ziyi/vcpkg/buildtrees/glib/install-x64-osx-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/glib/portfile.cmake:45 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package glib:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glib:x64-osx
  Vcpkg version: 2018.11.23-unknownhash

Additionally, attach any relevant sections from the log files above.

```
## Build log
`/Users/ziyi/vcpkg/buildtrees/glib/install-x64-osx-dbg-out.log` file is attached below:
[install-x64-osx-dbg-out.log](https://github.com/microsoft/vcpkg/files/3169210/install-x64-osx-dbg-out.log)

**Comment by ziyi-yan** [comment]
Hi @koprok, could you please take a look? It seems that you've worked on Linux support of glib. I would really appreciate it if you can help. Thanks!

**Comment by koprok** [comment]
Hello @ziyi-yan. Unfortunately, I don't have a Mac OS system at hand and I cannot try to build glib by myself. Anyway, could you please attach the contents of /Users/ziyi/vcpkg/buildtrees/glib/install-x64-osx-dbg-out.log file. This is the build log for glib and it will contain the actual compiler error that has occurred.

**Comment by ziyi-yan** [comment]
The building log file has been attached at the end of issue description. The content is too long so I didn't put it here. @koprok

**Comment by koprok** [comment]
@ziyi-yan, after a quick look at the log file, it seems to me that (maybe) there is something wrong with your compiler configuration. Doing a google search for the particular gcc error from the log leads me to this: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=63651
Sorry, but I cannot help with this any more, as I am not a MacOS developer.

**Comment by ziyi-yan** [comment]
Thank you a lot! It seems that gcc does not support some features in AppleClang. I solved it after [installing the header files](https://github.com/neovim/neovim/issues/9050#issuecomment-424417456) and using AppleClang for build configuration. Just put it here for other reference.
