### ISSUE TITLE
SDL2, my code doesn't link anymore

### ISSUE THREAD

**Issue by ericmitt** [Microsoft/vcpkg#641]
Hey I used to test SDL2 with the below code. 
Since few weeks this code doesn't link anymore:
      1>boost_test_exec_monitor-vc140-mt-gd-1_63.lib(test_main.obj) : error LNK2019: unresolved external symbol "int __cdecl test_main(int,char * * const)" (?test_main@@YAHHQAPAD@Z) referenced in function "public: void __thiscall test_main_caller::operator()(void)" (??Rtest_main_caller@@QAEXXZ)

Steps to reproduce:
Create a console project in Visual Studio
Copy paste the code below in the consoleApplication code

```cpp
#include "stdafx.h"
#include <iostream>
#include <SDL2/SDL.h>
#include <SDL2/SDL_opengl.h>

using std::cout;

int main(int argc, char* argv[]) {
	
	// Init SDL
	SDL_Init(SDL_INIT_VIDEO); 
	
	// Create a window. Window mode MUST include SDL_WINDOW_OPENGL for use with OpenGL.
	SDL_Window *window = SDL_CreateWindow(
		"SDL2/OpenGL Demo", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 640, 480, SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE
	);

	// Create an OpenGL context associated with the window.
	SDL_GLContext glcontext = SDL_GL_CreateContext(window);

	// Now, regular OpenGL functions ...
	glMatrixMode(GL_PROJECTION | GL_MODELVIEW);
	glLoadIdentity();
	glOrtho(-320, 320, 240, -240, 0, 1);

	// ... can be used alongside SDL2.
	SDL_Event e;
	ZeroMemory(&e, sizeof(e));
	
	SDL_PollEvent(&e);

	float x = 0.0, y = 30.0;

	while (e.type != SDL_KEYDOWN&&e.type != SDL_QUIT) {  // Enter main loop.

		SDL_PollEvent(&e);      // Check for events.

		glClearColor(0, 0, 0, 1);          // Draw with OpenGL.
		glClear(GL_COLOR_BUFFER_BIT);
		glRotatef(10.0, 0.0, 0.0, 1.0);
		
		glBegin(GL_TRIANGLES);
		glColor3f(1.0f, 0.0f, 0.0f); glVertex2f(x, y + 90.0f);
		glColor3f(0.0f, 1.0f, 0.0f); glVertex2f(x + 90.0f, y - 90.0f);
		glColor3f(0.0f, 0.0f, 1.0f); glVertex2f(x - 90.0f, y - 90.0f);
		glEnd();

		SDL_GL_SwapWindow(window);  // Swap the window/buffer to display the result.
		SDL_Delay(10);              // Pause briefly before moving on to the next cycle.

	}

	// Once finished with OpenGL functions, the SDL_GLContext can be deleted.
	SDL_GL_DeleteContext(glcontext);

	// Done! Close the window, clean-up and exit the program. 
	SDL_DestroyWindow(window);
	SDL_Quit();
	return 0;

}
```

**Comment by ras0219-msft** [comment]
First, could you please post the output of `vcpkg list sdl2` and `vcpkg list boost`?

Then, try removing boost and see if that solves the issue. There are some problems with both boost and SDL2 (they create `.lib` files which both try to define `_main`), but I am able to successfully link the code above with:
```
D:\src\vcpkg>vcpkg list sdl2
sdl2:x64-windows            2.0.4
sdl2:x86-windows            2.0.4            Simple DirectMedia Layer is a cross-platform deve...
D:\src\vcpkg>vcpkg list boost
boost:x64-windows           1.62-12          Peer-reviewed portable C++ source libraries
boost:x64-windows-static    1.62-4           Peer-reviewed portable C++ source libraries
boost:x86-windows           1.63             Peer-reviewed portable C++ source libraries
```
Note that I needed to set Project Properties -> Linker -> System -> SubSystem to Console.

**Comment by codicodi** [comment]
@ras0219-msft, was the `boost_test_exec_monitor` library moved to `manual-link\`?

**Comment by ras0219-msft** [comment]
I checked in my enlistment, and for boost 1.63 it is not. However, despite that, I was able to link the above code successfully.

As a separate issue, we do need to move that particular lib, but it may not be the root cause here (or if it is, we are seeing different behavior on different machines).

I should also note in my above comment that I was testing x86-windows.

**Comment by codicodi** [comment]
> different behavior on different machines

SDL2 - 2.0.4 is a pretty old version, try updating.
BTW the desired output for above code should be error, because no automatically linked linked library should provide `main`.

**Comment by ericmitt** [comment]
C:\Users\ericmitt>vcpkg list boost
boost:x86-windows           1.63
C:\Users\ericmitt>vcpkg list sdl2
sdl2:x86-windows            2.0.5-2

with this config I have the link error.

**Comment by ras0219-msft** [comment]
Aha, @codicodi found the issue. Basically, SDL2 is designed to implement main for you by default. Because this would conflict with other libraries, you need to manually opt-in to that behavior. You can either  add `SDL2main.lib` to your linker inputs, or you can add a line into your source file:
```
#pragma comment(lib, "SDL2main.lib")
```

We additionally need to move `boost_test_exec_monitor` so it is not automatically linked, but adding SDL2main may fix your issue immediately.

**Comment by Zingam** [comment]
> Aha, @codicodi found the issue. Basically, SDL2 is designed to implement main for you by default. Because this would conflict with other libraries, you need to manually opt-in to that behavior. You can either add `SDL2main.lib` to your linker inputs, or you can add a line into your source file:
> 
> ```
> #pragma comment(lib, "SDL2main.lib")
> ```
> We additionally need to move `boost_test_exec_monitor` so it is not automatically linked, but adding SDL2main may fix your issue immediately.

This is poorly explained in the docs. Why is "SDL2main" inside of a "manual-link" subfolder? Such improvisation requires modification of search paths.
