### ISSUE TITLE
AdditionalLibraryDirectories for lib targets

### ISSUE THREAD

**Issue by SpareSimian** [microsoft/vcpkg#6412]
I'm working on a port for cyrus-sasl and it's got an intermediate target that's a library (not a DLL). The lib.exe command fails because LIBPATH lacks the vcpkg install path. The fix is to add a <Lib> section to scripts\buildsystems\msbuild\vcpkg.targets after the <Link> one with the same <AdditionalLibraryDirectories> sections.

**Comment by Voskrese** [comment]
?

```
vcpkg_extract_source_archive_ex(
    OUT_SOURCE_PATH SOURCE_PATH
    ARCHIVE ${ARCHIVE} 
	PATCHES
		patch.patch
)

if(VCPKG_LIBRARY_LINKAGE STREQUAL dynamic)
	vcpkg_install_msbuild(
		SOURCE_PATH ${SOURCE_PATH}
		PROJECT_SUBPATH win32/cyrus-sasl-all-in-one.sln
		USE_VCPKG_INTEGRATION
		ALLOW_ROOT_INCLUDES
)
elseif(VCPKG_LIBRARY_LINKAGE STREQUAL static)
	vcpkg_install_msbuild(
		SOURCE_PATH ${SOURCE_PATH}
		PROJECT_SUBPATH win32/cyrus-sasl-core.sln
		USE_VCPKG_INTEGRATION
		ALLOW_ROOT_INCLUDES
)
endif()
```

**dynamic** cyrus-sasl-all-in-one.sln
**static** cyrus-sasl-core.sln

**Comment by SpareSimian** [comment]
I'm thinking more like this.
[vcpkg-libpath.patch.txt](https://github.com/microsoft/vcpkg/files/3169818/vcpkg-libpath.patch.txt)

**Comment by Voskrese** [comment]
> Link --> Lib -- duplicates

in the project cyrus-sasl, the extra environment is disabled, so it does not add from vcpkg

`%(AdditionalLibraryDirectories)`

I put a patch, look carefully. in general, everything is in your hands

**Comment by Voskrese** [comment]
As an option, you can try, but I did not do it

`OPTIONS "/p:AdditionalLibraryDirectories=${CURRENT_INSTALLED_DIR}/lib"`

```
if(VCPKG_LIBRARY_LINKAGE STREQUAL dynamic)
	vcpkg_install_msbuild(
		SOURCE_PATH ${SOURCE_PATH}
		PROJECT_SUBPATH win32/cyrus-sasl-all-in-one.sln
		USE_VCPKG_INTEGRATION
		ALLOW_ROOT_INCLUDES
		OPTIONS "/p:AdditionalLibraryDirectories=${CURRENT_INSTALLED_DIR}/lib"
		OPTIONS "/p:RuntimeLibrary=MultiThreaded"
		OPTIONS_DEBUG "/p:AdditionalLibraryDirectories=${CURRENT_INSTALLED_DIR}/debug/lib"
		OPTIONS_DEBUG "/p:RuntimeLibrary=MultiThreadedDebug"
)
```

**Comment by SpareSimian** [comment]
Ok, thanks, I see it now. I see two more instances of lmdb.lib in sasldb.vcxproj that need to be patched to lmdbd.lib in the two Debug configurations. Now that I see what to do this should be straightforward.
