### ISSUE TITLE
Error: Building package ompl:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by BurhanMohayeddin** [microsoft/vcpkg#6414]
Hi. I have problems related to installing "ompl" by using "vcpkg". When I execute "vcpkg install ompl[app]" I get error above. I have attached the log file also. I installed VS2015. Please, can you help me? Thank you very much.
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3170346/install-x86-windows-dbg-out.log)

**Comment by Neumann-A** [comment]
hmm can you try with a newer Visual Studio version?

**Comment by BurhanMohayeddin** [comment]
Thank you very much for your attention. Sure, I will do an write the result soon.

**Comment by BurhanMohayeddin** [comment]
Hey, thank you very much for your help. I have uninstalled VS2015 and installed VS2017 and everything worked.
