### ISSUE TITLE
Zlib CMAKE Error

### ISSUE THREAD

**Issue by godblezzme29** [microsoft/vcpkg#6422]
Hello, I have problem with my opencv installation
I run this command .\vcpkg install opencv[core]:x64-windows
But it shows error like this : 
F:\vcpkg>.\vcpkg install opencv[core]:x64-windows
The following packages will be built and installed:
    opencv[core]:x64-windows
  * zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: zlib:x64-windows
Building package zlib[core]:x64-windows...
-- Using cached F:/vcpkg/downloads/zlib1211.tar.gz
-- Using source at F:/vcpkg/buildtrees/zlib/src/1.2.11-f690224aeb
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: F:/vcpkg/buildtrees/zlib/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      F:\vcpkg\buildtrees\zlib\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:273 (vcpkg_execute_required_process)
  ports/zlib/portfile.cmake:22 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package zlib:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x64-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

Log error : 
https://github.com/godblezzme29/log-error/blob/master/config-x64-windows-out.log

Based on this log, I found that there is problem with the ninja, Is there anyone has solved this problem?
Previously when I have VS 2015 and VS 2017 everything is work with no problem, but after I uninstall my VS 2015, it has error with the installation.

*update : I already re-install VS 2015 but it has same error

My environment : 
VS 2017
Windows 10

**Comment by cenit** [comment]
#6416

**Comment by wangli28** [comment]
PR #6420

**Comment by wangli28** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
