### ISSUE TITLE
Error: Building package zlib:x64-windows failed with: BUILD_FAILED（Command failed: ninja;-v）

### ISSUE THREAD

**Issue by LiuliHub** [microsoft/vcpkg#6423]
D:\vcpkg>vcpkg install osg:x64-windows
The following packages will be built and installed:
  * bzip2[core]:x64-windows
  * curl[core,ssl,winssl]:x64-windows
  * expat[core]:x64-windows
  * freetype[core]:x64-windows
  * gdal[core]:x64-windows
  * geos[core]:x64-windows
  * giflib[core]:x64-windows
  * hdf5[core]:x64-windows
  * jasper[core]:x64-windows
  * libiconv[core]:x64-windows
  * libjpeg-turbo[core]:x64-windows
  * liblzma[core]:x64-windows
  * libpng[core]:x64-windows
  * libpq[core]:x64-windows
  * libwebp[core]:x64-windows
  * libxml2[core]:x64-windows
  * netcdf-c[core]:x64-windows
  * openexr[core]:x64-windows
  * opengl[core]:x64-windows
  * openjpeg[core]:x64-windows
  * openssl[core]:x64-windows
  * openssl-windows[core]:x64-windows
    osg[core]:x64-windows
  * proj[core]:x64-windows
  * proj4[core]:x64-windows
  * sqlite3[core]:x64-windows
  * szip[core]:x64-windows
  * tiff[core]:x64-windows
  * zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/29: zlib:x64-windows
Building package zlib[core]:x64-windows...
-- Using cached D:/vcpkg/downloads/zlib1211.tar.gz
-- Extracting source D:/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Using source at D:/vcpkg/buildtrees/zlib/src/1.2.11-f690224aeb
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: D:/vcpkg/buildtrees/zlib/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\zlib\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:273 (vcpkg_execute_required_process)
  ports/zlib/portfile.cmake:22 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package zlib:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x64-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

D:\vcpkg>

**Comment by wangli28** [comment]
PR #6420.

**Comment by wangli28** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
