### ISSUE TITLE
Add `cppcodec` header-only library to `vcpkg`

### ISSUE THREAD

**Issue by goodguysoft** [microsoft/vcpkg#6427]
`vcpkg` doesn't have any header-only C++ base64 library now, so it may be good idea to add `cppcodec` to `vcpkg`. This library is not the fastest one, however, it has modern C++ templates based interface, so it is useful for high level programming where the application has to encode comparably small amount of data and hence easier development and deployment are more impotant than higher performance. I use this header only library under Windows (VS 2015 and 2017), Ubuntu (gcc 8.2) and Android (clang). I have control and Cmake files already for this library and can share it with you if you want, or it is trivial for `vcpkg` team to implement own `cppcodec` package, because the ony job required to do is to download sources from github and copy include files to installation folder.

**Comment by Voskrese** [comment]
```
set(VCPKG_POLICY_EMPTY_PACKAGE enabled)

set(VCPKG_POLICY_EMPTY_PACKAGE enabled) # = "PolicyEmptyPackage";
set(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled) # = "PolicyDLLsWithoutLIBs";
set(VCPKG_POLICY_ONLY_RELEASE_CRT enabled) # = "PolicyOnlyReleaseCRT";
set(VCPKG_POLICY_EMPTY_INCLUDE_FOLDER enabled) # = "PolicyEmptyIncludeFolder";
set(VCPKG_POLICY_ALLOW_OBSOLETE_MSVCRT enabled) # = "PolicyAllowObsoleteMsvcrt";
```

**Comment by NancyLi1013** [comment]
@goodguysoft , thanks for posting this request. The port has been merged to the master. Please open a new issue or PR if you have any problems when using this port.

**Comment by goodguysoft** [comment]
Current `cppcodec` port is good; I just didn't realize that you have it already.
