### ISSUE TITLE
Cannot bootstrap with Set-StrictMode -Version Latest in PowerShell profile

### ISSUE THREAD

**Issue by chwarr** [Microsoft/vcpkg#643]
As of commit af0727cbc000ff2b9d3d7489c417d69170fc3a5f I can no longer bootstrap if my PowerShell profile contains `Set-StrictMode -Version Latest`.

Here's the interaction and spew if my profile contains _one the line_ `Set-StrictMode -Version Latest`:

```
PS C:\src\vcpkg> git log --oneline -1
d4fa0b3 Add CUDA portfile
PS C:\src\vcpkg> git clean -dxf
PS C:\src\vcpkg> powershell -exec bypass scripts\bootstrap.ps1

Download nuget
No suitable version of nuget was found (requires 3.3.0 or higher). Download portable
version?
[Y] Yes  [N] No  [A] Always Allow Downloads  [?] Help (default is "Y"): y
C:\src\vcpkg\scripts\findVisualStudioInstallationInstances.ps1 : The variable
'$entryCount' cannot be retrieved because it has not been set.
At C:\src\vcpkg\scripts\findAnyMSBuildWithCppPlatformToolset.ps1:9 char:42
+ ... onInstances = & $scriptsDir\findVisualStudioInstallationInstances.ps1
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (entryCount:String) [findVisualStudi.
   ..onInstances.ps1], RuntimeException
    + FullyQualifiedErrorId : VariableIsUndefined,findVisualStudioInstallationInstances.ps1
```

Here's the same interaction and (abbreviated) spew if my profile is an empty file:

```
PS C:\src\vcpkg> git log --oneline -1
d4fa0b3 Add CUDA portfile
PS C:\src\vcpkg> git clean -dxf
Removing downloads/
PS C:\src\vcpkg> powershell -exec bypass scripts\bootstrap.ps1

Download nuget
No suitable version of nuget was found (requires 3.3.0 or higher). Download portable
version?
[Y] Yes  [N] No  [A] Always Allow Downloads  [?] Help (default is "Y"): y
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2/7/2017 11:19:37 PM.
     1>Project "C:\src\vcpkg\toolsrc\dirs.proj" on node 1 (default targets).
...
```

I incorrectly assumed that `Set-StrictMode -Version Latest` in my profile would only affect the profile as it was running. However, it [affects](https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.core/set-strictmode) the current and all child scopes, so including it in my profile _did_ change it for subsequent scripts due to the [nature of scopes and profiles](https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.core/about/about_scopes).

This all being said, these failures indicate that there are some improvements that can be made in the scripts wrt. uninitialized variable and the like.

**Comment by ras0219-msft** [comment]
Thank you very much for the detailed analysis; this is definitely a bug we need to fix.

**Comment by alexkaratarakis** [comment]
e1aea256b84d2c1ac5c29db0e5e40ed536e3157f fixes the wrong variable name and guards against 0 instances.

**Comment by chwarr** [comment]
As of 2e94dfe (which is a child of e1aea25), I can bootstrap now.
I'm not sure whether you wanted to keep this open for other strict-mode things, so please close when you see fit.

**Comment by alexkaratarakis** [comment]
Right, I had left this open to do some extra verification; it is now done. 
I have added `Set-StrictMode -Version Latest` in my profile to catch such issues in the future. 

Thanks!
