### ISSUE TITLE
[ Feature request ] Support zsh integration

### ISSUE THREAD

**Issue by LinArcX** [microsoft/vcpkg#6432]

**Comment by wangli28** [comment]
Thanks for posting this issue. Can you provide more information about zsh integration?

**Comment by LinArcX** [comment]
@wangli28 Hi. look at this:
https://github.com/microsoft/vcpkg#tab-completion--auto-completion

**Comment by bpoebiapl** [comment]
please support zsh auto completion
![image](https://user-images.githubusercontent.com/18179088/66170864-f0b35e00-e680-11e9-98db-115082e61cde.png)

**Comment by gsfreema** [comment]
It isn't mentioned here, but macOS Catalina switched the default shell from bash to zsh so having integration for zsh would be very useful for macOS users.

**Comment by u3IFw2wfJ** [comment]
Any update about this as of today?

**Comment by LilyWangL** [comment]
@ras0219-msft Could you help take a look this issue?
