### ISSUE TITLE
Error: Building package boost-exception:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by arthurlapertosa** [microsoft/vcpkg#6437]
I have tried everything to get it installed, but nothing seems to work.

Prompt text:

C:\Users\arthu\vcpkg>vcpkg install boost-test:x86-windows
The following packages will be built and installed:
  * boost-algorithm[core]:x86-windows
  * boost-bind[core]:x86-windows
  * boost-chrono[core]:x86-windows
  * boost-container[core]:x86-windows
  * boost-conversion[core]:x86-windows
  * boost-exception[core]:x86-windows
  * boost-function[core]:x86-windows
  * boost-function-types[core]:x86-windows
  * boost-functional[core]:x86-windows
  * boost-fusion[core]:x86-windows
  * boost-intrusive[core]:x86-windows
  * boost-io[core]:x86-windows
  * boost-iterator[core]:x86-windows
  * boost-mpl[core]:x86-windows
  * boost-numeric-conversion[core]:x86-windows
  * boost-optional[core]:x86-windows
  * boost-range[core]:x86-windows
  * boost-ratio[core]:x86-windows
  * boost-rational[core]:x86-windows
  * boost-regex[core]:x86-windows
  * boost-system[core]:x86-windows
    boost-test[core]:x86-windows
  * boost-timer[core]:x86-windows
  * boost-type-index[core]:x86-windows
  * boost-typeof[core]:x86-windows
  * boost-unordered[core]:x86-windows
  * boost-winapi[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/27: boost-exception:x86-windows
Building package boost-exception[core]:x86-windows...
-- Using cached C:/Users/arthu/vcpkg/downloads/boostorg-exception-boost-1.69.0.tar.gz
-- Using source at C:/Users/arthu/vcpkg/buildtrees/boost-exception/src/ost-1.69.0-2efe4bac04
-- Building x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: C:/Users/arthu/vcpkg/installed/x86-windows/tools/boost-build/b2.exe;--stagedir=C:/Users/arthu/vcpkg/buildtrees/boost-exception/x86-windows-rel/stage;--build-dir=C:/Users/arthu/vcpkg/buildtrees/boost-exception/x86-windows-rel;--user-config=C:/Users/arthu/vcpkg/buildtrees/boost-exception/x86-windows-rel/user-config.jam;-j12;--debug-configuration;--debug-building;--debug-generators;--disable-icu;--ignore-site-config;--hash;-q;-sZLIB_INCLUDE="C:/Users/arthu/vcpkg/installed/x86-windows/include";-sBZIP2_INCLUDE="C:/Users/arthu/vcpkg/installed/x86-windows/include";threading=multi;threadapi=win32;runtime-link=shared;link=shared;address-model=32;architecture=x86;toolset=msvc-14.1;-sZLIB_BINARY=zlib;-sZLIB_LIBPATH="C:/Users/arthu/vcpkg/installed/x86-windows/lib";-sBZIP2_BINARY=bz2;-sBZIP2_LIBPATH="C:/Users/arthu/vcpkg/installed/x86-windows/lib";variant=release;debug-symbols=on
    Working Directory: C:/Users/arthu/vcpkg/buildtrees/boost-exception/src/ost-1.69.0-2efe4bac04/build
    Error code: 1
    See logs for more information:
      C:\Users\arthu\vcpkg\buildtrees\boost-exception\build-x86-windows-rel-out.log

Call Stack (most recent call first):
  installed/x86-windows/share/boost-build/boost-modular-build.cmake:272 (vcpkg_execute_required_process)
  ports/boost-exception/portfile.cmake:14 (boost_modular_build)
  scripts/ports.cmake:71 (include)

Error: Building package boost-exception:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-exception:x86-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

C:\Users\arthu\vcpkg>git pull
Already up to date.

**Comment by wangli28** [comment]
Hi @arthurlapertosa, thanks for posting this issue. Can you provide more information, such as your environment information and VS version?

**Comment by mt19997** [comment]
I have the same issue. It happens with VS 2019 preview on my machine (on x64) with the following error in the build log:

notice: found boost-build.jam at C:/Development/vcpkg/installed/x64-windows/tools/boost-build/boost-build.jam
notice: loading Boost.Build from C:/Development/vcpkg/installed/x64-windows/tools/boost-build/src/kernel
>notice: Site configuration files will be ignored due to the
>notice: --ignore-site-config command-line option.
>notice: Loading explicitly specified user configuration file:
>    C:\Development\vcpkg\buildtrees\boost-exception\x64-windows-rel\user-config.jam
>notice: Searching 'C:\Development\vcpkg\buildtrees\boost-exception\x64-windows-rel' for user-config configuration file 'user-config.jam'.
>notice: Loading user-config configuration file 'user-config.jam' from 'C:/Development/vcpkg/buildtrees/boost-exception/x64-windows-rel'.
>
>warning: Did not find command for MSVC toolset. If you have Visual Studio 2017 installed you will need to specify the full path to the command, set VS150COMNTOOLS for your installation, or build from the 'Visual Studio Command Prompt for VS 2017'.
>
>notice: will use 'cl.exe' for msvc, condition <toolset>msvc
>notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>', setup: 'C:/Development/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>', setup: 'x86'
>notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>32', setup: 'C:/Development/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>32', setup: 'x86'
>notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>', setup: 'C:/Development/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>', setup: 'x86'
>notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>32', setup: 'C:/Development/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>32', setup: 'x86'
>notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>64', setup: 'C:/Development/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>64', setup: 'amd64'
>notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>64', setup: 'C:/Development/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>64', setup: 'amd64'
>notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>ia64/<address-model>', setup: 'C:/Development/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>ia64/<address-model>', setup: 'x86_ia64'
>notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>ia64/<address-model>64', setup: 'C:/Development/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>ia64/<address-model>64', setup: 'x86_ia64'
>notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>', setup: 'C:/Development/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>', setup: 'x86_arm'
>notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>32', setup: 'C:/Development/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>32', setup: 'x86_arm'
>notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>', setup: 'C:/Development/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>', setup: 'x86_arm64'
>notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>64', setup: 'C:/Development/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>64', setup: 'x86_arm64'
>notice: [cmdline-cfg] toolset msvc-14.1 not previously configured; attempting to auto-configure now
>error: msvc initialization: parameter 'version' inconsistent
>error: no value was specified in earlier initialization
>error: an explicit value is specified now

Starting from a VS command prompt does not help.

**Comment by smallp** [comment]
same issue. I saw there is "notice: [cmdline-cfg] toolset msvc-14.1 not previously configured", but I have only msvc-14.2. Is this the key point?

**Comment by mt19997** [comment]
I think so. There are several boost related issues on the board - and all that I saw is that they are waiting for the integration of boost-1.70

**Comment by mt19997** [comment]
#6330 see here

**Comment by wangli28** [comment]
PR #6141 has been merged. I installed it successfully with VS2019 and VCPKG latest source. You can update vcpkg and rebuild.

>  .\vcpkg.exe install boost-exception:x86-windows
The following packages will be built and installed:
/  * boost-assert[core]:x86-windows
/  * boost-build[core]:x86-windows
/  * boost-compatibility[core]:x86-windows
/  * boost-config[core]:x86-windows
/  * boost-container-hash[core]:x86-windows
/  * boost-core[core]:x86-windows
/  * boost-detail[core]:x86-windows
/    boost-exception[core]:x86-windows
......
Starting package 20/20: boost-exception:x86-windows
Building package boost-exception[core]:x86-windows...
-- Using cached F:/Lily/issue6475/vcpkg/downloads/boostorg-exception-boost-1.70.0.tar.gz
-- Using source at F:/Lily/issue6475/vcpkg/buildtrees/boost-exception/src/ost-1.70.0-586c64cc78
-- Building x86-windows-rel
-- Building x86-windows-rel done
-- Building x86-windows-dbg
-- Building x86-windows-dbg done
-- Packaging x86-windows-rel
-- Packaging x86-windows-rel done
-- Packaging x86-windows-dbg
-- Packaging x86-windows-dbg done
-- Packaging headers
-- Packaging headers done
-- Using cached F:/Lily/issue6475/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: F:/Lily/issue6475/vcpkg/packages/boost-exception_x86-windows/share/boost-exception/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-exception[core]:x86-windows... done
Installing package boost-exception[core]:x86-windows...
Installing package boost-exception[core]:x86-windows... done
Elapsed time for package boost-exception:x86-windows: 16.29 s
/
Total elapsed time: 2.909 min
