### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by YarikTiutiunnyk** [microsoft/vcpkg#6445]
PS D:\MLpack\DEV\vcpkg> .\vcpkg install mlpack:x64-windows
The following packages will be built and installed:
  * armadillo[core]:x64-windows
  * boost[core]:x64-windows
  * boost-accumulators[core]:x64-windows
  * boost-align[core]:x64-windows
  * boost-asio[core]:x64-windows
  * boost-assign[core]:x64-windows
  * boost-beast[core]:x64-windows
  * boost-bimap[core]:x64-windows
  * boost-callable-traits[core]:x64-windows
  * boost-circular-buffer[core]:x64-windows
  * boost-compute[core]:x64-windows
  * boost-context[core]:x64-windows
  * boost-contract[core]:x64-windows
  * boost-convert[core]:x64-windows
  * boost-coroutine[core]:x64-windows
  * boost-coroutine2[core]:x64-windows
  * boost-crc[core]:x64-windows
  * boost-disjoint-sets[core]:x64-windows
  * boost-dll[core]:x64-windows
  * boost-dynamic-bitset[core]:x64-windows
  * boost-fiber[core]:x64-windows
  * boost-flyweight[core]:x64-windows
  * boost-geometry[core]:x64-windows
  * boost-gil[core]:x64-windows
  * boost-graph[core]:x64-windows
  * boost-graph-parallel[core]:x64-windows
  * boost-hana[core]:x64-windows
  * boost-heap[core]:x64-windows
  * boost-hof[core]:x64-windows
  * boost-icl[core]:x64-windows
  * boost-interprocess[core]:x64-windows
  * boost-interval[core]:x64-windows
  * boost-local-function[core]:x64-windows
  * boost-lockfree[core]:x64-windows
  * boost-log[core]:x64-windows
  * boost-logic[core]:x64-windows
  * boost-metaparse[core]:x64-windows
  * boost-mp11[core]:x64-windows
  * boost-msm[core]:x64-windows
  * boost-multi-array[core]:x64-windows
  * boost-multiprecision[core]:x64-windows
  * boost-odeint[core]:x64-windows
  * boost-parameter[core]:x64-windows
  * boost-parameter-python[core]:x64-windows
  * boost-poly-collection[core]:x64-windows
  * boost-polygon[core]:x64-windows
  * boost-process[core]:x64-windows
  * boost-program-options[core]:x64-windows
  * boost-property-map[core]:x64-windows
  * boost-ptr-container[core]:x64-windows
  * boost-python[core]:x64-windows
  * boost-qvm[core]:x64-windows
  * boost-random[core]:x64-windows
  * boost-safe-numerics[core]:x64-windows
  * boost-scope-exit[core]:x64-windows
  * boost-signals2[core]:x64-windows
  * boost-sort[core]:x64-windows
  * boost-stacktrace[core]:x64-windows
  * boost-statechart[core]:x64-windows
  * boost-test[core]:x64-windows
  * boost-timer[core]:x64-windows
  * boost-type-erasure[core]:x64-windows
  * boost-ublas[core]:x64-windows
  * boost-units[core]:x64-windows
  * boost-uuid[core]:x64-windows
  * boost-vmd[core]:x64-windows
  * boost-wave[core]:x64-windows
  * boost-xpressive[core]:x64-windows
  * boost-yap[core]:x64-windows
  * clapack[core]:x64-windows
    mlpack[core]:x64-windows
  * openblas[core]:x64-windows
  * openssl[core]:x64-windows
  * openssl-windows[core]:x64-windows
  * python3[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/75: openblas:x64-windows
Building package openblas[core]:x64-windows...
-- Using cached D:/MLpack/DEV/vcpkg/downloads/xianyi-OpenBLAS-v0.3.6.tar.gz
-- Using source at D:/MLpack/DEV/vcpkg/buildtrees/openblas/src/v0.3.6-30d8688cb4
-- Downloading http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portable.zip...
-- Downloading http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portable.zip... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:172 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:262 (vcpkg_download_distfile)
  ports/openblas/portfile.cmake:42 (vcpkg_find_acquire_program)
  scripts/ports.cmake:71 (include)

Error: Building package openblas:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openblas:x64-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by Voskrese** [comment]
`cd D:/MLpack/DEV/vcpkg/downloads`
`wget http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portable.zip`

or more..

copy `strawberry-perl-5.24.1.1-32bit-portable.zip` to folder `D:/MLpack/DEV/vcpkg/downloads`

**Comment by JackBoosY** [comment]
Hi @YarikTiutiunnyk, please download http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portable.zip manually, put it into _vcpkg/downloads/_ and **rerun** install command.
Thanks.

**Comment by danieltuzes** [comment]
@Voskrese are you sure @YarikTiutiunnyk has wget?
@YarikTiutiunnyk: it seems that you cannot download http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portable.zip, although the link is valid.
1. Please check if you can reach the file, for example, with a browser.
2. If you can, something prevents your script downloading the file. For me, it was my firewall that prohibited (AFAIK) cmake to access the internet. Try to allow your script to reach the file, for example, by configuring your firewall.
3. If you cannot do step 2, @Voskrese suggested to download the file manually with another program, like the command line program wget, or you can also download it with a browser. After you got the file, copy it to `vcpkg/downloads` folder, `D:/MLpack/DEV/vcpkg/downloads`.

**Comment by JackBoosY** [comment]
@danieltuzes He obviously uses windows.
Maybe we should prompt it in powershell.
There are too many such problems.

**Comment by YarikTiutiunnyk** [comment]
but this comsnd also does not work
and I you can't reach the file with a browser.


PS C:\Users\Yarik> cd D:\MLpack\DEV\vcpkg\downloads
PS D:\MLpack\DEV\vcpkg\downloads> wget http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portab
le.zip
wget : Unable to connect to the remote server
At line:1 char:1
+ wget http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by JackBoosY** [comment]
@YarikTiutiunnyk  Of course, you don't have wget. Can you download it using IE or other tools?

**Comment by danieltuzes** [comment]
@JackBoosY  it seems he has wget (I also have, it comes with many packages). If @YarikTiutiunnyk is right, and cannot access with a browser, there must some network problem.

@YarikTiutiunnyk I provide a link to my own server, you can download it from here:
Replace AAA with tuzes.elte in
http://AAA.hu/strawberry-perl-5.24.1.1-32bit-portable.zip

**Comment by YarikTiutiunnyk** [comment]
Thank you so much
