### ISSUE TITLE
.\bootstrap-vcpkg.bat Error

### ISSUE THREAD

**Issue by thohemp** [microsoft/vcpkg#6447]
### **Output:**

```
C:\vcpkg\scripts\bootstrap.ps1` : Building vcpkg.exe failed. Please ensure you have installed Visual 'Studio with the Desktop C++ workload and the Windows SDK for Desktop C++.
In Zeile:1 Zeichen:4
+ & {& C:\vcpkg\scripts\bootstrap.ps1}
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,bootstrap.ps1
```

Installed:
```
VC++ 2017 version 15.9 v14.16 latest v141 tools
Windows 10 SDK (10.0.17763.0)
```

**Comment by JackBoosY** [comment]
Hi @thohemp, It seems that you have not installed the required SDK, can I know which additional components are you installed?
Thanks.

**Comment by thohemp** [comment]
From the C++ package for desktop development:

![grafik](https://user-images.githubusercontent.com/42150441/57701767-f3bf9a80-765c-11e9-95d2-f94072b1ccec.png)

**Comment by PhoebeHui** [comment]
@thohemp, does this issue still persist for you?

**Comment by PhoebeHui** [comment]
@thohemp, please make sure install English lauguage package, and reopen this issue if it still be a problem for you.
