### ISSUE TITLE
Remove double builds from ports

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#6450]
I checked the logs of a CI build and the following ports seem to perform a unnecessary double build (triplet:x64-windows-static)
- [ ] libp7
- [ ] winpcap
- [ ] clockutils
- [ ] libobd (boost,sqlite,pqsql)
- [ ] freerdp
- [ ] libusb-win32
- [ ] gsoap
- [ ] jbigkit

**Comment by wangli28** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
