### ISSUE TITLE
GLM header can't be found

### ISSUE THREAD

**Issue by marcojez** [microsoft/vcpkg#6461]
After upgrading the GLM package today, client code can no longer find header file <glm/glm.hpp>, because the include path is not exported along with the CMake target. 

In order to fix this, just change the first install() command in CMakeLists.txt from:

```
install(
    TARGETS glm EXPORT glm-config
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}/
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}/
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}/
)
```

to:

```
install(
    TARGETS glm EXPORT glm-config
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}/
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}/
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}/
    INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
)
```

(note the addition of the INCLUDES DESTINATION option).

**Comment by ras0219-msft** [comment]
Thanks for posting this issue!

The problem was that `include(GNUInstallDirs)` was placed _after_ the use of `CMAKE_INSTALL_INCLUDEDIR`, so it wasn't defined yet.

I've opened #6466 to fix this.
