### ISSUE TITLE
Can we have support for mathgl?

### ISSUE THREAD

**Issue by AntonioMiguel** [microsoft/vcpkg#6462]
Please,  can we have support for this scientific plot library?  
Good work ... vcpkg changes everything in VS.
Thanks in advance.

**Comment by cenit** [comment]
#6463 in this PR you can find a draft of a port for mathgl, please try it and let me know if it works or not

**Comment by NancyLi1013** [comment]
Hi @AntonioMiguel, thanks for posting this request. This port has been added to vcpkg. Please try to update vcpkg and use it.
@cenit, thanks for your PR and efforts.
