### ISSUE TITLE
Error: Building package ogre:x64-linux failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by YgabrielsY** [microsoft/vcpkg#6476]
Building the ogre package failed on my windows machine using the windows subsystem for linux with ubuntu. The errors are:

CMake Error at ports/ogre/portfile.cmake:86 (file):
    file must be called with at least two arguments.
Call Stack (most recent call first):
    scripts/ports.cmake:71 (include)

Commenting out line 86 in ports/ogre/portfile.cmake makes the installation run through. Line 86: file(REMOVE ${REL_CFGS} ${DBG_CFGS}) seems to cause the issue.

**Comment by PhoebeHui** [comment]
@YgabrielsY, does this still be a problem for you, could you get latest souce and try again?

I can't repro this issue with WSL Ubuntu 18.04:

Computing installation plan...
The following packages will be built and installed:
    ogre[core]:x64-linux
Starting package 1/1: ogre:x64-linux
Building package ogre[core]:x64-linux...
ogre currently requires the following library from the system package manager:
    Xaw

It can be installed on Ubuntu systems via apt-get install libxaw7-dev
-- Using cached /home/ubuntu18/vcpkg/downloads/OGRECave-ogre-8083067c1835147de5d82015347d95c710e36bc0.tar.gz
-- Using source at /home/ubuntu18/vcpkg/buildtrees/ogre/src/c710e36bc0-fd78f2aff5
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Installing: /home/ubuntu18/vcpkg/packages/ogre_x64-linux/share/ogre/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package ogre[core]:x64-linux... done
Installing package ogre[core]:x64-linux...
Installing package ogre[core]:x64-linux... done
Elapsed time for package ogre:x64-linux: 38.36 min

Total elapsed time: 38.36 min

The package ogre:x64-linux provides CMake targets:

    find_package(OGRE CONFIG REQUIRED)
    # Note: 17 target(s) were omitted.
    target_link_libraries(main PRIVATE OgreHLMS OgreMain Codec_EXR OgreBites)

**Comment by YgabrielsY** [comment]
Thanks for coming back at me, no the problem doesn't persist anymore!
