### ISSUE TITLE
Can't install PCL x64 static, BUILD_FAILED error

### ISSUE THREAD

**Issue by AlanCasanova7** [microsoft/vcpkg#6480]
This is the message I get everytime i try to:
>vcpkg install pcl:x64-windows-static-md-v141

The following packages will be built and installed:
    pcl[core]:x64-windows-static-md-v141
Starting package 1/1: pcl:x64-windows-static-md-v141
Building package pcl[core]:x64-windows-static-md-v141...
-- Using cached C:/Users/Alan/Documents/Workspace/vcpkg/downloads/PointCloudLibrary-pcl-pcl-1.9.1.tar.gz
-- Using source at C:/Users/Alan/Documents/Workspace/vcpkg/buildtrees/pcl/src/pcl-1.9.1-898b5a3155
-- Configuring x64-windows-static-md-v141
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: C:/Users/Alan/Documents/Workspace/vcpkg/buildtrees/pcl/x64-windows-static-md-v141-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\Alan\Documents\Workspace\vcpkg\buildtrees\pcl\config-x64-windows-static-md-v141-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:273 (vcpkg_execute_required_process)
  ports/pcl/portfile.cmake:41 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package pcl:x64-windows-static-md-v141 failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: pcl:x64-windows-static-md-v141
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

I can install the dynamic one but it always fails with the static one and I can't understand why, any help will be appreciated.

The following is my triplet:
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_PLATFORM_TOOLSET v141)

**Comment by Neumann-A** [comment]
Without logs no help possible......please attach:
```
See logs for more information:
C:\Users\Alan\Documents\Workspace\vcpkg\buildtrees\pcl\config-x64-windows-static-md-v141-out.log
```

**Comment by AlanCasanova7** [comment]
You are right, I apologize, here it is:
`[1/2] cmd /c "cd .. && "C:/Users/Alan/Documents/Workspace/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe" "C:/Users/Alan/Documents/Workspace/vcpkg/buildtrees/pcl/src/pcl-1.9.1-898b5a3155" "-DBUILD_surface_on_nurbs=ON" "-DBUILD_tools=OFF" "-DBUILD_CUDA=OFF" "-DBUILD_GPU=OFF" "-DPCL_BUILD_WITH_BOOST_DYNAMIC_LINKING_WIN32=0" "-DPCL_BUILD_WITH_FLANN_DYNAMIC_LINKING_WIN32=0" "-DPCL_BUILD_WITH_QHULL_DYNAMIC_LINKING_WIN32=0" "-DPCL_SHARED_LIBS=0" "-DWITH_CUDA=OFF" "-DWITH_LIBUSB=OFF" "-DWITH_OPENNI2=OFF" "-DWITH_PCAP=OFF" "-DWITH_PNG=ON" "-DWITH_QHULL=ON" "-DWITH_QT=OFF" "-DWITH_VTK=ON" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/Alan/Documents/Workspace/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows-static-md-v141" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/Alan/Documents/Workspace/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/Users/Alan/Documents/Workspace/vcpkg/packages/pcl_x64-windows-static-md-v141""
FAILED: ../CMakeCache.txt 
cmd /c "cd .. && "C:/Users/Alan/Documents/Workspace/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe" "C:/Users/Alan/Documents/Workspace/vcpkg/buildtrees/pcl/src/pcl-1.9.1-898b5a3155" "-DBUILD_surface_on_nurbs=ON" "-DBUILD_tools=OFF" "-DBUILD_CUDA=OFF" "-DBUILD_GPU=OFF" "-DPCL_BUILD_WITH_BOOST_DYNAMIC_LINKING_WIN32=0" "-DPCL_BUILD_WITH_FLANN_DYNAMIC_LINKING_WIN32=0" "-DPCL_BUILD_WITH_QHULL_DYNAMIC_LINKING_WIN32=0" "-DPCL_SHARED_LIBS=0" "-DWITH_CUDA=OFF" "-DWITH_LIBUSB=OFF" "-DWITH_OPENNI2=OFF" "-DWITH_PCAP=OFF" "-DWITH_PNG=ON" "-DWITH_QHULL=ON" "-DWITH_QT=OFF" "-DWITH_VTK=ON" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/Alan/Documents/Workspace/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows-static-md-v141" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/Alan/Documents/Workspace/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/Users/Alan/Documents/Workspace/vcpkg/packages/pcl_x64-windows-static-md-v141""
-- The C compiler identification is MSVC 19.16.27030.1
-- The CXX compiler identification is MSVC 19.16.27030.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Found OpenMP_C: -openmp (found version "2.0") 
-- Found OpenMP_CXX: -openmp (found version "2.0") 
-- Found OpenMP: TRUE (found version "2.0")  
-- Found OpenMP
-- Found Eigen: C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/include/eigen3  
-- Eigen found (include: C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/include/eigen3, version: 3.3.7)
-- Found FLANN: C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/lib/flann_cpp.lib (Required is at least version "1.7.0") 
-- FLANN found (include: C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/include, lib: optimized;C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/lib/flann_cpp.lib;debug;C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/debug/lib/flann_cpp-gd.lib)
-- Could NOT find OpenNI (missing: OPENNI_LIBRARIES OPENNI_INCLUDE_DIRS) 
-- OpenNI grabber support: not building because OpenNI not found
-- Could NOT find FZAPI (missing: FZAPI_LIBS FZAPI_INCLUDE_DIRS) 
-- Fotonic camera support: not building because FZAPI not found
-- Could NOT find ENSENSO (missing: ENSENSO_LIBRARIES ENSENSO_INCLUDE_DIRS) 
-- IDS-Imaging Ensenso camera support: not building because Ensenso not found
-- Could NOT find davidSDK (missing: DAVIDSDK_LIBRARY DAVIDSDK_INCLUDE_DIR) 
-- David Vision Systems SDK support: not building because davidSDK not found
-- Could NOT find DSSDK (missing: DSSDK_LIBRARIES DSSDK_INCLUDE_DIRS) 
-- DepthSense SDK support: not building because DSSDK not found
-- Could NOT find RSSDK (missing: RSSDK_LIBRARIES RSSDK_INCLUDE_DIRS) 
-- RealSense SDK support: not building because RSSDK not found
-- Found ZLIB: optimized;C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/lib/zlib.lib;debug;C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/debug/lib/zlibd.lib (found version "1.2.11") 
-- Found PNG: optimized;C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/lib/libpng16.lib;debug;C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/debug/lib/libpng16d.lib (found version "1.6.37") 
-- Found Qhull: optimized;C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/lib/qhullstatic.lib;debug;C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/debug/lib/qhullstatic_d.lib  
-- QHULL found (include: C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/include, lib: optimized;C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/lib/qhullstatic.lib;debug;C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/debug/lib/qhullstatic_d.lib)
CMake Error at C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/share/vtk/VTKTargets.cmake:886 (message):
  The imported target "vtkGUISupportMFC" references the file

     "C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/debug/bin/vtkGUISupportMFC-8.2.dll"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/share/vtk/VTKTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/share/vtk/VTKConfig.cmake:122 (include)
  C:/Users/Alan/Documents/Workspace/vcpkg/scripts/buildsystems/vcpkg.cmake:246 (_find_package)
  CMakeLists.txt:366 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/Users/Alan/Documents/Workspace/vcpkg/buildtrees/pcl/x64-windows-static-md-v141-rel/CMakeFiles/CMakeOutput.log".
[2/2] cmd /c "cd ../../x64-windows-static-md-v141-dbg && "C:/Users/Alan/Documents/Workspace/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe" "C:/Users/Alan/Documents/Workspace/vcpkg/buildtrees/pcl/src/pcl-1.9.1-898b5a3155" "-DBUILD_surface_on_nurbs=ON" "-DBUILD_tools=OFF" "-DBUILD_CUDA=OFF" "-DBUILD_GPU=OFF" "-DPCL_BUILD_WITH_BOOST_DYNAMIC_LINKING_WIN32=0" "-DPCL_BUILD_WITH_FLANN_DYNAMIC_LINKING_WIN32=0" "-DPCL_BUILD_WITH_QHULL_DYNAMIC_LINKING_WIN32=0" "-DPCL_SHARED_LIBS=0" "-DWITH_CUDA=OFF" "-DWITH_LIBUSB=OFF" "-DWITH_OPENNI2=OFF" "-DWITH_PCAP=OFF" "-DWITH_PNG=ON" "-DWITH_QHULL=ON" "-DWITH_QT=OFF" "-DWITH_VTK=ON" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/Alan/Documents/Workspace/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows-static-md-v141" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/Alan/Documents/Workspace/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/Users/Alan/Documents/Workspace/vcpkg/packages/pcl_x64-windows-static-md-v141/debug""
FAILED: ../../x64-windows-static-md-v141-dbg/CMakeCache.txt 
cmd /c "cd ../../x64-windows-static-md-v141-dbg && "C:/Users/Alan/Documents/Workspace/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe" "C:/Users/Alan/Documents/Workspace/vcpkg/buildtrees/pcl/src/pcl-1.9.1-898b5a3155" "-DBUILD_surface_on_nurbs=ON" "-DBUILD_tools=OFF" "-DBUILD_CUDA=OFF" "-DBUILD_GPU=OFF" "-DPCL_BUILD_WITH_BOOST_DYNAMIC_LINKING_WIN32=0" "-DPCL_BUILD_WITH_FLANN_DYNAMIC_LINKING_WIN32=0" "-DPCL_BUILD_WITH_QHULL_DYNAMIC_LINKING_WIN32=0" "-DPCL_SHARED_LIBS=0" "-DWITH_CUDA=OFF" "-DWITH_LIBUSB=OFF" "-DWITH_OPENNI2=OFF" "-DWITH_PCAP=OFF" "-DWITH_PNG=ON" "-DWITH_QHULL=ON" "-DWITH_QT=OFF" "-DWITH_VTK=ON" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/Alan/Documents/Workspace/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows-static-md-v141" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/Alan/Documents/Workspace/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/Users/Alan/Documents/Workspace/vcpkg/packages/pcl_x64-windows-static-md-v141/debug""
-- The C compiler identification is MSVC 19.16.27030.1
-- The CXX compiler identification is MSVC 19.16.27030.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Found OpenMP_C: -openmp (found version "2.0") 
-- Found OpenMP_CXX: -openmp (found version "2.0") 
-- Found OpenMP: TRUE (found version "2.0")  
-- Found OpenMP
-- Found Eigen: C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/include/eigen3  
-- Eigen found (include: C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/include/eigen3, version: 3.3.7)
-- Found FLANN: C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/lib/flann_cpp.lib (Required is at least version "1.7.0") 
-- FLANN found (include: C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/include, lib: optimized;C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/lib/flann_cpp.lib;debug;C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/debug/lib/flann_cpp-gd.lib)
-- Could NOT find OpenNI (missing: OPENNI_LIBRARIES OPENNI_INCLUDE_DIRS) 
-- OpenNI grabber support: not building because OpenNI not found
-- Could NOT find FZAPI (missing: FZAPI_LIBS FZAPI_INCLUDE_DIRS) 
-- Fotonic camera support: not building because FZAPI not found
-- Could NOT find ENSENSO (missing: ENSENSO_LIBRARIES ENSENSO_INCLUDE_DIRS) 
-- IDS-Imaging Ensenso camera support: not building because Ensenso not found
-- Could NOT find davidSDK (missing: DAVIDSDK_LIBRARY DAVIDSDK_INCLUDE_DIR) 
-- David Vision Systems SDK support: not building because davidSDK not found
-- Could NOT find DSSDK (missing: DSSDK_LIBRARIES DSSDK_INCLUDE_DIRS) 
-- DepthSense SDK support: not building because DSSDK not found
-- Could NOT find RSSDK (missing: RSSDK_LIBRARIES RSSDK_INCLUDE_DIRS) 
-- RealSense SDK support: not building because RSSDK not found
-- Found ZLIB: optimized;C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/lib/zlib.lib;debug;C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/debug/lib/zlibd.lib (found version "1.2.11") 
-- Found PNG: optimized;C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/lib/libpng16.lib;debug;C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/debug/lib/libpng16d.lib (found version "1.6.37") 
-- Found Qhull: optimized;C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/lib/qhullstatic.lib;debug;C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/debug/lib/qhullstatic_d.lib  
-- QHULL found (include: C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/include, lib: optimized;C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/lib/qhullstatic.lib;debug;C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/debug/lib/qhullstatic_d.lib)
CMake Error at C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/share/vtk/VTKTargets.cmake:886 (message):
  The imported target "vtkGUISupportMFC" references the file

     "C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/debug/bin/vtkGUISupportMFC-8.2.dll"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/share/vtk/VTKTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  C:/Users/Alan/Documents/Workspace/vcpkg/installed/x64-windows-static-md-v141/share/vtk/VTKConfig.cmake:122 (include)
  C:/Users/Alan/Documents/Workspace/vcpkg/scripts/buildsystems/vcpkg.cmake:246 (_find_package)
  CMakeLists.txt:366 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/Users/Alan/Documents/Workspace/vcpkg/buildtrees/pcl/x64-windows-static-md-v141-dbg/CMakeFiles/CMakeOutput.log".
ninja: build stopped: subcommand failed.`

**Comment by claudiofantacci** [comment]
I recently installed both `vtk` and `pcl` (shared, not static) from `vcpkg` without problems. Here are the library that I succesfully compiled and isntalled:
```
vtk:x64-windows                                    8.2.0-4          Software system for 3D computer graphics, image 
vtk[mpi]:x64-windows                                                MPI functionality for VTK
vtk[qt]:x64-windows                                                 Qt functionality for VTK
pcl:x64-windows                                    1.9.1-4          Point Cloud Library (PCL) is open source library...
pcl[qt]:x64-windows                                                 Qt support for PCL
pcl[tools]:x64-windows                                              Build PCL utilities
```

However, for a succesfull compilation, I had to add `Visual C++ MFC for x86 and x64` to my Visual Studio installation from the `Tools -> Get Tools and Features` tab.

After that everything went just fine.

**Comment by AlanCasanova7** [comment]
> I recently installed both `vtk` and `pcl` (shared, not static) from `vcpkg` without problems. Here are the library that I succesfully compiled and isntalled:
> 
> ```
> vtk:x64-windows                                    8.2.0-4          Software system for 3D computer graphics, image 
> vtk[mpi]:x64-windows                                                MPI functionality for VTK
> vtk[qt]:x64-windows                                                 Qt functionality for VTK
> pcl:x64-windows                                    1.9.1-4          Point Cloud Library (PCL) is open source library...
> pcl[qt]:x64-windows                                                 Qt support for PCL
> pcl[tools]:x64-windows                                              Build PCL utilities
> ```
> 
> However, for a succesfull compilation, I had to add `Visual C++ MFC for x86 and x64` to my Visual Studio installation from the `Tools -> Get Tools and Features` tab.
> 
> After that everything went just fine.

I can also install it dinamically, however i cannot succed to install it statically.

**Comment by Jiloc** [comment]
same error also for pcl:x64-windows-static-md-v142

**Comment by claudiofantacci** [comment]
I'm trying compiling pcl static. Let's see how it goes 😄

**Comment by claudiofantacci** [comment]
I was able to compile `pcl:x64-windows-static` by running `vcpkg install pcl:x64-windows-static`.
I had no prior static library installed, I'm on `master` at commit 5b6b66512b84267c1b93ef577dea3a811a255c82, I'm using VS Enterprise edition `15.9.3`.

The only side effect is that the whole 120 library compilation took just too many GB of my hard drive that is now full. So I'm deleting just now all the library to avoid crippling my workstation.

PS: @traversaro 😝

**Comment by Jiloc** [comment]
I confirm that the static works, I did the same. Is the MD option that causes the problem. thank you @claudiofantacci

**Comment by cbezault** [comment]
@AlanCasanova please re-open if this is still an issue.
