### ISSUE TITLE
vcpkg.cmake module errors in osx gcc

### ISSUE THREAD

**Issue by soroshsabz** [microsoft/vcpkg#6484]
ITNOA

I got new error on travis with below message:

```
CMake Warning (dev) at third_party/vcpkg/scripts/buildsystems/vcpkg.cmake:182 (if):
  Policy CMP0057 is not set: Support new IN_LIST if() operator.  Run "cmake
  --help-policy CMP0057" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  IN_LIST will be interpreted as an operator when the policy is set to NEW.
  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  tests/CMakeLists.txt:13 (add_executable)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at third_party/vcpkg/scripts/buildsystems/vcpkg.cmake:182 (if):
  if given arguments:
    "MACOSX_BUNDLE" "IN_LIST" "ARGV"

  Unknown arguments specified
Call Stack (most recent call first):
  tests/CMakeLists.txt:13 (add_executable)

-- Configuring incomplete, errors occurred!

See also "/Users/travis/build/fnc12/sqlite_orm/compile/CMakeFiles/CMakeOutput.log".

The command "cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=../third_party/vcpkg/scripts/buildsystems/vcpkg.cmake
```

for more detailed please see https://travis-ci.org/fnc12/sqlite_orm/jobs/533558496

thanks

**Comment by soroshsabz** [comment]
@seanwarren please see my errors

thanks

**Comment by seanwarren** [comment]
@soroshsabz, I believe this error is occuring because your `cmake_minimum_required` is set to <3.3. CMake 3.3 introduced the `IN_LIST` operator. As a workaround, you can either increase your `cmake_minimum_required` to >=3.3 or use this command to enable IN_LIST: `cmake_policy(SET CMP0057 NEW)`.

I will create a PR to use a more backwards compatible construct

**Comment by soroshsabz** [comment]
@seanwarren thanks for replay but this error does not exist before this day

**Comment by seanwarren** [comment]
@soroshsabz, yes PR #5681 introduced this issue - sorry about that. I'm just testing a PR which will fix it; I should be able to raise this in the next few hours. If you need to work around it in the meantime please try one of the approaches above.

**Comment by soroshsabz** [comment]
@seanwarren thanks a lot :)
