### ISSUE TITLE
tbb:x64-uwp. build failed

### ISSUE THREAD

**Issue by wuweido-com** [microsoft/vcpkg#6488]
This bit is required for Windows Store apps.
Found 1 error(s). Please correct the portfile:
    ..\vcpkg\ports\tbb\portfile.cmake
-- Performing post-build validation done
Error: Building package tbb:x64-uwp failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: tbb:x64-uwp

**Comment by LarryIII** [comment]
See here https://github.com/intel/tbb/blob/tbb_2019/doc/Release_Notes.txt, tbb did not support uwp platform.
