### ISSUE TITLE
expat install build failed

### ISSUE THREAD

**Issue by zia95** [microsoft/vcpkg#6489]
Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\expat\extract-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive.cmake:43 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:98 (vcpkg_extract_source_archive)
  scripts/cmake/vcpkg_from_github.cmake:114 (vcpkg_extract_source_archive_ex)
  ports/expat/portfile.cmake:6 (vcpkg_from_github)
  scripts/ports.cmake:71 (include)

Error: Building package expat:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: expat:x86-windows-static
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

error log:
CMake Error: Problem with archive_write_header(): Can't create ''
CMake Error: Current file: libexpat-R_2_2_6/README.md
CMake Error: Problem extracting tar: C:/vcpkg/downloads/libexpat-libexpat-R_2_2_6.tar.gz

**Comment by zia95** [comment]
I fixed the issue by turning off UTF-8 beta....

**Comment by yapingxin** [comment]
> 
> 
> I fixed the issue by turning off UTF-8 beta....

Big thanks to you! I meet the same issue today and resolved by applying your solution.

**Comment by PhoebeHui** [comment]
It looks  a cmake issue, see more information in issue #6220.

**Comment by HWiman** [comment]
> I fixed the issue by turning off UTF-8 beta....

Turning off "Beta: Use Unicode UTF-8.." indeed solves the problem. I had no idea were to find it, but it is explained here: https://stackoverflow.com/questions/56419639/what-does-beta-use-unicode-utf-8-for-worldwide-language-support-actually-do
