### ISSUE TITLE
How to remove vcpkg from computer

### ISSUE THREAD

**Issue by GdLinkLock** [Microsoft/vcpkg#649]
Thanks for supplying  an awesome tool！
But I have a question，Is there a way to remove vcpkg from computer？

**Comment by alexkaratarakis** [comment]
`vcpkg`'s removal is simply to delete the `vcpkg` directory. This would be the directory where you cloned this repository (or extracted the downloaded zip file).

**Comment by GdLinkLock** [comment]
thank you!
