### ISSUE TITLE
Error: Building package libmysql:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by zengquanshen** [microsoft/vcpkg#6491]
The following packages will be built and installed:
    libmysql[core]:x86-windows
Starting package 1/1: libmysql:x86-windows
Building package libmysql[core]:x86-windows...
CMake Error at ports/libmysql/portfile.cmake:10 (message):
  Oracle has dropped support in libmysql for 32-bit Windows.
Call Stack (most recent call first):
  scripts/ports.cmake:71 (include)

**Comment by wangli28** [comment]
> Oracle has dropped support in libmysql for 32-bit Windows.

You can build `libmysql` with command `vcpkg install libmysql:x64-windows`. 
Thanks.

**Comment by PhoebeHui** [comment]
@zengquanshen, please install libmysql:x64-windows instead.
