### ISSUE TITLE
[question] how to use if I already have a toolchain file?

### ISSUE THREAD

**Issue by diskshard** [microsoft/vcpkg#6494]
If I'm already using a cmake toolchain file, what is the recommended way to inject the vcpkg one? 
Thanks in advance

**Comment by Neumann-A** [comment]
define your toolchain file as VCPKG_CHAINLOAD_TOOLCHAIN_FILE and use vcpkg.cmake as the main cmake toolchain

**Comment by diskshard** [comment]
Thanks!
