### ISSUE TITLE
`cccapstone` can not compile

### ISSUE THREAD

**Issue by goodguysoft** [microsoft/vcpkg#6495]
I just install `capstone`, `capstone[arm]` and `cccapstone` for `x64-windows-static` triplet. Compilation just doesn't work. The error follows:

`\vcpkg\installed\x64-windows-static\include\cccapstone\cppbindings\cscapstonehelper.hh(3): fatal error C1083: Cannot open include file: 'capstone.h': No such file or directory`

There are also other `cccapstone` headers that contain the same error.

The reason is that `vcpkg` installs `capstone` to its own folder and not to `include` folder root or `cccapstone` subfolder, and `cccapstone` uses `#include <capstone.h>` instead of `#include <capstone/capstone.h>`.

Additionally, `ArmDisasm.hh` contains syntax error: `CArmDisasm` class constructor name is `CArmDisasm86` for any reason.

Please fix that.

**Comment by JackBoosY** [comment]
This is indeed a port error, even though we recommend installing the header file in _include/port_name_.

**Comment by JackBoosY** [comment]
Hi @goodguysoft, thanks for reporting this issue!
I've fix this issue. Please update vcpkg and rebuild cccapstone.

Thanks.
