### ISSUE TITLE
z3:x64-windows-static exe

### ISSUE THREAD

**Issue by trmcnealy** [microsoft/vcpkg#6496]
When building z3 with x64-windows-static, the z3.exe is not installed into the .\vcpkg\installed\x64-windows-static\bin\z3.exe

**Comment by cenit** [comment]
we cannot accept .exe in bin folder, that's reserved for dll (in non-static builds)
.exe tools are moved to the tools folder, if it's not there we should check the portfile

**Comment by JackBoosY** [comment]
Hi @trmcnealy, thanks for reporting this issue!
I've fix this issue. Please update vcpkg and rebuild z3.

Thanks.
