### ISSUE TITLE
FindPackage GDAL not working for debug libraries....

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#6502]
https://github.com/microsoft/vcpkg/blob/9d473a69545ac648b9ea2067c007b57dfad7462b/ports/gdal/portfile.cmake#L301
(it not the only line)
 
breaking #6014 :-1: and with it #5543. 

don't rename libraries without a very good reason and check at least the FindModule which comes with cmake....: 

```
find_library(GDAL_LIBRARY
  NAMES ${_gdal_lib} gdal gdal_i gdal1.5.0 gdal1.4.0 gdal1.3.2 GDAL
  HINTS
     ENV GDAL_DIR
     ENV GDAL_ROOT
     ${_gdal_libpath}
  PATH_SUFFIXES lib
)
```

**Comment by JackBoosY** [comment]
We want to use two different ways to use the debug/release library:
1. Use a different name: the release library name should **not** be suffixed, the debug library name should be added **d**/**_d**/**-d** suffix.
2. Use the correct **port-target-debug/release.cmake** according to the **debug/release** macro to load the correct library based on the path.
    And for the solution, use the vcpkg toolchain to use different libraries.

**Comment by Neumann-A** [comment]
@JackBoosY 

> the debug library name should be added d/_d/-d suffix.

See #6014 why this is generally a bad idea. If the library is expected to have the suffix it is ok because downstream users will expect it. If you rename it if it is not expected you break downstream users. This is the case for GDAL. How vcpkg is currently setup it will only link GDAL release libraries in downstream debug and release configuration.

> Use the correct port-target-debug/release.cmake according to the debug/release macro to load the correct library based on the path.

GDAL does not expot a target/config file. As such it cannot be found in config mode. If it would, I would have not made an issue out of it since then the library names does not matter at all. The only way GDAL is found is by CMakes findGDAL module, which does what is posted in my original post above.

**Comment by JackBoosY** [comment]
@Neumann-A I partially agree with you that the suffix must be what the author **expects**, using the suffix **just** to **manually** identify the type of library (debug/release).
If we want the program to automatically link to the corresponding library, we **must** do this with the correct **configuration** file.

**Comment by dg0yt** [comment]
Port gdal has received an updated wrapper.
