### ISSUE TITLE
Boost-1.70: Boost.Variant builds version 1.69

### ISSUE THREAD

**Issue by degski** [microsoft/vcpkg#6514]
As you can see in the below build output, Boost.Variant builds the 1.69 version instead of 1.70:

    Starting package 205/288: boost-tti:x64-windows-static
    Building package boost-tti[core]:x64-windows-static...
    -- Downloading https://github.com/boostorg/tti/archive/boost-1.70.0.tar.gz...
    -- Extracting source Y:/vcpkg/downloads/boostorg-tti-boost-1.70.0.tar.gz
    -- Using source at Y:/vcpkg/buildtrees/boost-tti/src/ost-1.70.0-d052f3cdbb
    -- Packaging headers
    -- Packaging headers done
    -- Using cached Y:/vcpkg/downloads/boost_LICENSE_1_0.txt
    -- Installing: Y:/vcpkg/packages/boost-tti_x64-windows-static/share/boost-tti/copyright
    -- Performing post-build validation
    -- Performing post-build validation done
    Building package boost-tti[core]:x64-windows-static... done
    Installing package boost-tti[core]:x64-windows-static...
    Installing package boost-tti[core]:x64-windows-static... done
    Elapsed time for package boost-tti:x64-windows-static: 4.345 s
    Starting package 206/288: boost-variant:x64-windows-static
    Building package boost-variant[core]:x64-windows-static...
    -- Using cached Y:/vcpkg/downloads/boostorg-variant-boost-1.69.0.tar.gz
    -- Extracting source Y:/vcpkg/downloads/boostorg-variant-boost-1.69.0.tar.gz
    -- Using source at Y:/vcpkg/buildtrees/boost-variant/src/ost-1.69.0-1e60a54f5e
    -- Packaging headers
    -- Packaging headers done
    -- Using cached Y:/vcpkg/downloads/boost_LICENSE_1_0.txt
    -- Installing: Y:/vcpkg/packages/boost-variant_x64-windows-static/share/boost-variant/copyright
    -- Performing post-build validation
    -- Performing post-build validation done
    Building package boost-variant[core]:x64-windows-static... done
    Installing package boost-variant[core]:x64-windows-static...
    Installing package boost-variant[core]:x64-windows-static... done
    Elapsed time for package boost-variant:x64-windows-static: 2.601 s
    Starting package 207/288: boost-spirit:x64-windows-static
    Building package boost-spirit[core]:x64-windows-static...
    -- Downloading https://github.com/boostorg/spirit/archive/boost-1.70.0.tar.gz...
    -- Extracting source Y:/vcpkg/downloads/boostorg-spirit-boost-1.70.0.tar.gz
    -- Using source at Y:/vcpkg/buildtrees/boost-spirit/src/ost-1.70.0-b8169479f8
    -- Packaging headers
    -- Packaging headers done
    -- Using cached Y:/vcpkg/downloads/boost_LICENSE_1_0.txt
    -- Installing: Y:/vcpkg/packages/boost-spirit_x64-windows-static/share/boost-spirit/copyright
    -- Performing post-build validation
    -- Performing post-build validation done

**Comment by JackBoosY** [comment]
Although boost has been upgraded to v1.70.0 (PR#6141), the following parts have not been upgraded:
- boost-di
- boost-modular-build-helper
- boost-signals
- boost-variant

**Comment by degski** [comment]
@JackBoosY It is not possible to mix and match different versions of Boost. You now have a Boost.Core-1.70 and Boost.Config-1.70 that are used on Boost.Variant-1.69. There is no guarantee (and no effort as such to achieve this) that this will work. **It is simply not acceptable**.

**Comment by OlafvdSpek** [comment]
> Although boost has been upgraded to v1.70.0 (PR #6141), the following parts have not been upgraded:

Why?

**Comment by JackBoosY** [comment]
@degski @OlafvdSpek yeah, we will fix them.

**Comment by ras0219-msft** [comment]
@degski @OlafvdSpek The reason boost-variant was left at 1.69 is due to a critical regression in 1.70 which breaks several downstream libraries: https://github.com/boostorg/variant/issues/69

When leaving variant at 1.69, the rest of the catalog is able to successfully build.

Now that there is a fix available upstream, the best way forward would be to backport that fix to 1.70 to update boost-variant.
