### ISSUE TITLE
glib miss a file, gobject-introspection missing altogether

### ISSUE THREAD

**Issue by ghost** [microsoft/vcpkg#6523]
1. The install script of [glib](https://github.com/GNOME/glib) does NOT install `msvc_recommended_pragmas.h` under `<vcpkg>/installed/include`. I had to manually clone the glib repository to get that file

2. An install package for [gobject-introspection](https://gitlab.gnome.org/GNOME/gobject-introspection) seems to be missing altogether?

**Comment by PhoebeHui** [comment]
The glib issue has been fixed now.

For the new port, If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
