### ISSUE TITLE
Hinnant's date package fails to build for remote-api x86-windows or x64-windows

### ISSUE THREAD

**Issue by shanepowell** [microsoft/vcpkg#6530]
The current date library is failing to build for the remote-api option with vcpkg on multiple machines with a log error of:

I get:
-- Using source at C:/gitdepot/vcpkg/buildtrees/date/src/d7bed2f039-cf9419e85a
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:202 (message):
    Command failed: C:/gitdepot/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v
    Working Directory: C:/gitdepot/vcpkg/buildtrees/date/x86-windows-dbg
    See logs for more information:
      C:\gitdepot\vcpkg\buildtrees\date\install-x86-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/date/portfile.cmake:32 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package date:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: date:x86-windows
  Vcpkg version: 2018.11.23-nohash

The install-x86-windows-dbg-err.log file contains:
ninja: error: build.ninja:59: bad $-escape (literal $ must be written as $$)
  LINK_LIBRARIES = $<BUILD_INTERFACE:optimized C:\gitdepot\vcpkg\install...
                   ^ near here

The same error happens if a compile for x86-windows or x64-windows.

**Comment by shanepowell** [comment]
I worked around the issue by changing the file:
vcpkg\ports\date\CMakeLists.txt

line:
  target_link_libraries(tz PUBLIC $<BUILD_INTERFACE:${CURL_LIBRARIES}>)

to:
  target_link_libraries(tz PUBLIC ${CURL_LIBRARIES})

I know nothing about cmake so I have no idea if this is a "good" fix or not.

**Comment by ccorn** [comment]
I get no such problems (running vcpkg in a 32-bit Win7 VM with VS2017).
Note that I do not have ninja installed, and this seems to be a ninja sensitivity.

**Comment by ccorn** [comment]
After a "git pull" in the vcpkg directory, rebuild of vcpkg and `vcpkg update`,  I can now reproduce the issue. `vcpkg install date[remote-api]` fails with an error message that points to a wrongly generated `tz.vcxproj`. It contains (at four places):

~~~
    <Link>
      <AdditionalDependencies>$&lt;BUILD_INTERFACE:optimized;[...]
~~~
`cmake --version` is 3.14.3.

**Comment by ccorn** [comment]
The superficial reason seems to be that `${CURL_LIBRARIES}` are several words.
[Quoting as suggested](https://cmake.org/cmake/help/latest/command/target_link_libraries.html#overview) did not help.
However, I doubt that usage of `BUILD_INTERFACE` is appropriate here anyway. If I understand the [docs](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#output-related-expressions) correctly, `BUILD_INTERFACE` is a filter for uses in the buildtree. I suspect that the actually intended semantics are those of [`PRIVATE`](https://cmake.org/cmake/help/latest/command/target_link_libraries.html#libraries-for-a-target-and-or-its-dependents) i.e. [implementation-only](https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#transitive-usage-requirements) instead (the `curl` headers are referenced in the implementation `src/tz.cpp` only):
~~~ diff
index 292c1758..97050ab1 100644
--- a/ports/date/CMakeLists.txt
+++ b/ports/date/CMakeLists.txt
@@ -18,8 +18,8 @@ target_include_directories(tz PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DI

 if(HAS_REMOTE_API)
   find_package(CURL REQUIRED)
-  target_link_libraries(tz PUBLIC $<BUILD_INTERFACE:${CURL_LIBRARIES}>)
-  target_include_directories(tz PUBLIC $<BUILD_INTERFACE:${CURL_INCLUDE_DIRS}>)
+  target_link_libraries(tz PRIVATE ${CURL_LIBRARIES})
+  target_include_directories(tz PRIVATE ${CURL_INCLUDE_DIRS})
 endif()

 if(BUILD_SHARED_LIBS)
~~~
That said, I am not familiar with CMake. and there might well be a subtlety that escapes me. However, I could successfully `vcpkg install date[remote-api]` with the above diff and build (using CMake) and run  the first [example: the current local time](https://github.com/howardhinnant/date/wiki/Examples-and-Recipes#the-current-local-time) successfully. It does indeed download and extract `~/Downloads/tzdata` on first use.

**Comment by PhoebeHui** [comment]
@ccorn, thanks for posting the issue and fix!

Could you summit a PR? The VCPKG-PR-Eager will help test your fix.

**Comment by PhoebeHui** [comment]
@shanepowell, this issue currently fixed, please get latest vcpkg source and try again.
