### ISSUE TITLE
[OpenSSL] Remove OpenSSL does not remove OpenSSL-windows

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#6537]
Currently that is by design but I would rather like to see one OpenSSL package within vcpkg instead of three. Is there not an alternative way for that? Something like including different portfiles within the portfile of OpenSSL instead of having three packages?

Something like (pseudocode):

```
if(WINDOWS)
  include(portfile-windows.cmake)
elseif(LINUX)
    include(portfile-linux.cmake)
elseif(MacOS)
    include(portfile-MacOS.cmake)
else()
    msg(Not supported)  
endif
```

(I know that changing any of the portfile-os.cmake would require a rebuild on the other OS but I think it is a small price to pay compared with the three different packages currently used. )

**Comment by Rastaban** [comment]
The same issue exists with ports like boost and qt5.  The problem is that the way the 'alias' workaround is currently done puts the openssl port as the leaf of the dependency tree.  We have been toying with the idea of adding a first class concept of an 'alias' port that could flip that dependency.

**Comment by Neumann-A** [comment]
closed since i reworked openssl to a single port in one PR.
