### ISSUE TITLE
Error: Building package theia:x64-windows failed with: BUILD_FAILED after installing lz4

### ISSUE THREAD

**Issue by edwin-tn** [microsoft/vcpkg#6539]
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3198325/install-x64-windows-dbg-out.log)

**Comment by cenit** [comment]
Could you please try #6371?

**Comment by JackBoosY** [comment]
Hi @edwin-tn. thanks for reporting this issue.
I cannot reproduce this issue on vcpkg latest version. Can you update vcpkg and repro it?

Thanks.

**Comment by edwin-tn** [comment]
problems solved...
