### ISSUE TITLE
How will binary incompatible toolchains be handled?

### ISSUE THREAD

**Issue by feverzsj** [Microsoft/vcpkg#654]
is it possible to select vc2015 or vc2018 when install package?

**Comment by sdcb** [comment]
I think you mean VS2017/VC19.0 :)
Since VS2015/VS2017 are binary compatible, this question are not important.

**Comment by feverzsj** [comment]
what about future vs? For example, vs202x could break the binary compatibility like they always did.

**Comment by sdcb** [comment]
@feverzsj I think they'll consider it later.

**Comment by ras0219-msft** [comment]
Hi @feverzsj!

This is one of the challenges triplets are designed to solve. In the future, whenever we need to support a new incompatible build environment (say, Xbox or VS-next-binary-revision), we can add triplets to allow a completely independent side-by-side set of libraries to be built and managed. (*As an aside, you can do this as well if you need it!*)

To look at it from another angle, we see and manage the difference between VS2013 and VS2015/2017 the same as the difference between x64 and ARM.

**Comment by feverzsj** [comment]
@ras0219-msft sounds reasonable. So we'll have something like x64-msvc140, x86-msvc141 for packages of different toolsets? That's definitely a must-have feature as other build systems like boost.build did.

**Comment by ras0219-msft** [comment]
That's exactly right.
