### ISSUE TITLE
CMake-hdf5-1.10.5.tar.gz Hash Error

### ISSUE THREAD

**Issue by Jimmy-Hu** [microsoft/vcpkg#6547]
I tried to install pcl library. However, after downloading of CMake-hdf5-1.10.5.tar.gz file (from https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.5/src/CMake-hdf5-1.10.5.tar.gz), some error messages shown up like below. I re-download again, and the error still occurred. Does anyone has the same problem?

My environment is OS: Windows 10 Pro 1809.

```
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:96 (message):


  File does not have expected hash:

          File path: [ ***/vcpkg/downloads/CMake-hdf5-1.10.5.tar.gz ]
      Expected hash: [ a25ea28d7a511f9184d97b5b8cd4c6d52dcdcad2bffd670e24a1c9a6f98b03108014a853553fa2b00d4be7523128b5fd6a4454545e3b17ff8c66fea16a09e962 ]
        Actual hash: [ 45206910674604d05f86903314da3281f9bef9478d2bffc9a4c3f6a1a2187360813269eb6e487a0c463b47ef3a0e1780c9a606244c66b864124d339c567b8aee ]

  Please delete the file and retry if this file should be downloaded again.
```

**Comment by Neumann-A** [comment]
If i look into the folder https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.5/src/

I find:
>  CMake-hdf5-1.10.5.ta..> | 2019-03-01 08:19 | 13M

so it is likely a problem on your end. I tested it with current master and it works fine

> some error messages

More than one of those hash error messages? Faulty disk, virus, corrupted download?

**Comment by Jimmy-Hu** [comment]
@Neumann-A Thanks for your reply.
I download this file manually successfully. The file size is 12.6 MB. However the hash still mismatch, so that it can't be build. The actual hash is also [ 45206910674604d05f86903314da3281f9bef9478d2bffc9a4c3f6a1a2187360813269eb6e487a0c463b47ef3a0e1780c9a606244c66b864124d339c567b8aee ]. I wonder that is it possible that the file was update and the expected hash is not update yet?

**Comment by ras0219-msft** [comment]
I've just re-downloaded the file and got a25ea28d7a511f9184d97b5b8cd4c6d52dcdcad2bffd6..... with a 13.0 MB file.

It looks like (for some reason) your download is corrupted. Is it possible for you to try downloading the file over a VPN or from a different computer?

**Comment by Jimmy-Hu** [comment]
@ras0219-msft Thanks for your reply and suggestion.
I use VPN and download it from a different computer, and the file with 13.0 MB size is extracted successfully.
