### ISSUE TITLE
OpenEXR package install fails on OSX if the underlying filesystem is case sensitive

### ISSUE THREAD

**Issue by jherico** [microsoft/vcpkg#6548]
https://github.com/microsoft/vcpkg/blob/ed612380878e8bf631e7d9f7434a75ca850f0101/ports/openexr/portfile.cmake#L66

Because of the logic here the code below will attempt to copy the LICENSE file into `${CURRENT_PACKAGES_DIR}/share/OpenEXR/copyright`.  This is fine on Windows systems where NTFS is case preserving, as well as on OSX systems where the filesystem is also case preserving, but one of our developers has a _case-sensitive_ filesystem, which is an optional feature for APFS.  On his system when he attempts to build OpenEXR he gets the error 

     The software license must be available at ${CURRENT_PACKAGES_DIR}/share/openexr/copyright

**Comment by wangli28** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
