### ISSUE TITLE
Problem with shared static variable between dll

### ISSUE THREAD

**Issue by JacqKrol** [microsoft/vcpkg#6550]
I installed the lib gtkmm and run asample program from the manual (base.cc). A run-time error occurred because the dll pangomm called the function **wrap_register** from glibmm which has a static variable **wrap_func_table** but because pangomm has its own copy not initialized a run-time error occurs when this variable is referenced in wrap_register.

How can I solve this problem ? I hoped vcpkg would solve these kind of linking issues automatically.

**Comment by NNemec** [comment]
I think I have a fix already - going to prepare a PR

**Comment by JacqKrol** [comment]
Ok, thanks.  I expect the same  problem not only for pangomm.dll but also for the atkmm.dll. 

Were these dll statically compiled with glibmm, so that the functions were included in the dlls ?


Sent from Mail for Windows 10

**Comment by NNemec** [comment]
The problem was that since #5937 glibmm could only be built as static library but atkmm, pangomm and gtkmm each can only be linked as dynamic libary, leading to up to three copies of the glibmm static data in one executable. My fix reverts that change so that glibmm is also built as dynamic libary.
