### ISSUE TITLE
vcpkgmetricsuploader is detected as SONAR.PSDownloader!g1 by Symantec Endpoint Protection

### ISSUE THREAD

**Issue by Thieum** [microsoft/vcpkg#6551]
![image](https://user-images.githubusercontent.com/944894/58121451-815b3700-7bd5-11e9-8fe2-2b08f895b882.png)
The exe gets quarantined.
Using Windows 7 x64. Symantec Endpoint Protection 14.2 build 1031

**Comment by Rastaban** [comment]
This is good to know, although I am not sure what to do about it.

More information on the risk: https://www.symantec.com/security-center/writeup/2017-032721-5748-99

**Comment by PhoebeHui** [comment]
Same issue with https://github.com/Microsoft/vcpkg/issues/3345.

**Comment by JEJ0** [comment]
I just installed the current vcpkg and encountered this as well.  I've following this thread and [#3345](https://github.com/microsoft/vcpkg/issues/3345).   I see these closed but don't see any resolution.

What I do see is that Norton is very, very unhappy on my system with this tool.  I've gotten SONAR reports about the metrics upload (and I'll also put in a vote for making metrics opt-in.  I'm surprised that it is opt-out, and not terribly well documented opt-out).  Norton is now saying that it needs to restart to finish cleaning out the security risks.

This is not the level of security awareness I expect Microsoft to have.  Minimally fix this to be opt-in.  Beyond that, work with your security teams to get the uploader qualified by at least the major vendors.
