### ISSUE TITLE
g++:error:unrecognized command line option ‘-std=c++1z’

### ISSUE THREAD

**Issue by emlysoft** [microsoft/vcpkg#6556]
I have encountered an error in vcpkg compilation on CentOS7:
g++:error:unrecognized command line option ‘-std=c++1z’

My GCC version is 4.8

**Comment by ras0219-msft** [comment]
Unfortunately, we use the Filesystem TS, available in GCC 6 (April 27, 2016) and above.

This link may help you to get a newer version of GCC on your OS: https://linuxhostsupport.com/blog/how-to-install-gcc-on-centos-7/
