### ISSUE TITLE
PCL installation - Error: Building package pcl:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by justPub** [microsoft/vcpkg#6559]
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:202 (message):
    Command failed: F:/YK/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe;--build;.;--config;Release;--target;install;--;-v
    Working Directory: F:/YK/vcpkg/buildtrees/pcl/x86-windows-rel
    See logs for more information:
      F:\YK\vcpkg\buildtrees\pcl\install-x86-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/pcl/portfile.cmake:70 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package pcl:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: pcl:x86-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by Neumann-A** [comment]
>See logs for more information:
F:\YK\vcpkg\buildtrees\pcl\install-x86-windows-rel-out.log

Please attach logs.

**Comment by justPub** [comment]
[install-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/3209906/install-x86-windows-rel-out.log)

**Comment by wangli28** [comment]
I found this in your build log, is your device storage full?
> F:\YK\vcpkg\buildtrees\pcl\src\pcl-1.9.1-80abf3ea0d\surface\src\surfel_smoothing.cpp : fatal error C1085: Cannot write compiler generated file: 'F:\YK\vcpkg\buildtrees\pcl\x86-windows-rel\surface\CMakeFiles\pcl_surface.dir\src\surfel_smoothing.cpp.obj': No space left on device

**Comment by justPub** [comment]
oh,maybe, that‘s it. The remaining space is really insufficient.Thanks, i will try.
