### ISSUE TITLE
[OpenGL] Is this port required?

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#6563]
I do not quite understand why this port exists. It just copies files around from the windows sdk. Is there any reason for the existence of the opengl port?

**Comment by OlafvdSpek** [comment]
Perhaps to satisfy dependencies?

**Comment by Neumann-A** [comment]
> Perhaps to satisfy dependencies?

find_package(OpenGL REQUIRED) should be enough for that.

**Comment by cenit** [comment]
Not everyone uses CMake ;)

**Comment by PhoebeHui** [comment]
I noticed 6 ports depend on opengl via CONTROL file at least, I think it's easy to add dependency  to these ports.
