### ISSUE TITLE
[libbf] Creates a hard to delete aux folder in the buildtree. 

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#6564]
because it is a restricted name on windows.

code to delete:
`rd /S /Q "\\?\<full_vcpkg_path>\buildtrees\libbf\src\v1.0.0-5bf953e697\aux"`

`v1.0.0-5bf953e697` might chance with future changes to the port

**Comment by JackBoosY** [comment]
The unzipped folder name should be **_aux** instead of **aux**

**Comment by Neumann-A** [comment]
since this port shouldn't be build on windows. I will close the issue as soon as #6577 is merged.

**Comment by JackBoosY** [comment]
@Neumann-A  Please do not close this issue until the unpacking issue is resolved.

**Comment by Neumann-A** [comment]
ok. But if I look at the github repository of libbf https://github.com/mavam/libbf the folder is called aux and not _aux.

**Comment by JackBoosY** [comment]
@Neumann-A Well... I'm wrong, but it cannot be decompressed by vcpkg, and can be decompressed using tools.

**Comment by Rastaban** [comment]
from https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file

> Do not use the following reserved names for the name of a file:
> 
> CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Also avoid these names followed immediately by an extension; for example, NUL.txt is not recommended. For more information, see Namespaces.
>

**Comment by Rastaban** [comment]
We have had issues with other ports creating an aux folder on the build machines.

**Comment by Rastaban** [comment]
reported upstream, they are open for a PR to remove this directory because it is probably unused anyway. 
 https://github.com/mavam/libbf/issues/44

**Comment by Rastaban** [comment]
merged upstream https://github.com/mavam/libbf/pull/45

**Comment by Rastaban** [comment]
This has been fixes upstream for libbf, we will pick up the fix on their next release.  Closing issue.  @JackBoosY feel free to open another issue if you think there are other things to do unrelated to libbf.
