### ISSUE TITLE
could not find vs if not installed in default path

### ISSUE THREAD

**Issue by feverzsj** [Microsoft/vcpkg#657]
My vs2015/2017 is not installed in any of $ProgramFiles. And findAnyMSBuildWithCppPlatformToolset.ps1 failed to find any of them. So I have to hard-coded the path in it.

the error output:

Could not find MSBuild with C++ support. VS2015 or above with C++ support need to be installed.
location D:\vcpkg\scripts\findAnyMSBuildWithCppPlatformToolset.ps1:32 : 6
+ throw <<<<  "Could not find MSBuild with C++ support. VS2015 or above with C++ support need to be
 installed."
    + CategoryInfo          : OperationStopped: (Could not find ...o be installed.:String) [], Run
   timeException
    + FullyQualifiedErrorId : Could not find MSBuild with C++ support. VS2015 or above with C++ su
   pport need to be installed.

**Comment by ras0219-msft** [comment]
Thanks for reporting this!

I modified the `findAnyMSBuildWithCppPlatformToolset.ps1` script to use the registry to find your VS2015 installation in the branch [dev/roschuma/find-vs](/Microsoft/vcpkg/tree/dev/roschuma/find-vs). Could you try that out and see if it fixes your issue?

**Comment by feverzsj** [comment]
@ras0219-msft yes, the new script successfully find the vs.

**Comment by ras0219-msft** [comment]
Thanks!
