### ISSUE TITLE
apr:x64-osx does not build

### ISSUE THREAD

**Issue by benbrackenc74** [microsoft/vcpkg#6571]
Running:
`./vcpkg install apr`

results in:

> The following packages will be built and installed:
    apr[core]:x64-osx (from HEAD)
Starting package 1/1: apr:x64-osx
Building package apr[core]:x64-osx from HEAD...
-- Using cached /Users/benbracken/vcpkg/downloads/apr-1.6.5.tar.bz2
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:202 (message):
    Command failed: /Users/benbracken/vcpkg/downloads/tools/cmake-3.14.0-osx/cmake-3.14.0-Darwin-x86_64/CMake.app/Contents/bin/cmake;--build;.;--config;Debug;--target;install;--;-v
    Working Directory: /Users/benbracken/vcpkg/buildtrees/apr/x64-osx-dbg
    See logs for more information:
      /Users/benbracken/vcpkg/buildtrees/apr/install-x64-osx-dbg-out.log
Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/apr/portfile.cmake:35 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)
Error: Building package apr:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: apr:x64-osx

[install-x64-osx-dbg-out.log](https://github.com/microsoft/vcpkg/files/3209106/install-x64-osx-dbg-out.log)

With errors like:
```/Users/benbracken/vcpkg/buildtrees/apr/src/apr-1.6.5/include/apr_errno.h:52:21: error: expected function body after function declarator APR_DECLARE(char *) apr_strerror(apr_status_t statcode, char *buf,```

**Comment by PhoebeHui** [comment]
This issue has been fixed now, I tried with latest source, it built successfully for me.

./vcpkg install apr
Computing installation plan...
The following packages will be built and installed:
    apr[core]:x64-osx
Starting package 1/1: apr:x64-osx
Building package apr[core]:x64-osx...
-- Downloading https://www.apache.org/dist/apr/apr-1.7.0.tar.bz2...
-- Extracting source /Users/vcpkg/vcpkg/downloads/apr-1.7.0.tar.bz2
-- Using source at /Users/vcpkg/vcpkg/buildtrees/apr/src/apr-1-3a6fcafcf9
-- Configuring apr
-- apr requires pkg-config from the system package manager (example: "sudo apt-get install pkg-config")
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
-- Building x64-osx-rel
-- Installing x64-osx-dbg
-- Installing x64-osx-rel
-- Installing: /Users/vcpkg/vcpkg/packages/apr_x64-osx/share/apr/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package apr[core]:x64-osx... done
Installing package apr[core]:x64-osx...
Installing package apr[core]:x64-osx... done
Elapsed time for package apr:x64-osx: 56.71 s

Total elapsed time: 56.71 s
