### ISSUE TITLE
Error: Building package libzip:x64-linux

### ISSUE THREAD

**Issue by emlysoft** [microsoft/vcpkg#6573]
[root@localhost vcpkg]# ./vcpkg install libzip
The following packages will be built and installed:
    libzip[bzip2,core,openssl]:x64-linux
Starting package 1/1: libzip:x64-linux
Building package libzip[bzip2,core,openssl]:x64-linux...
-- Using cached /usr/local/src/vcpkg/downloads/nih-at-libzip-rel-1-5-2.tar.gz
-- Using source at /usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:202 (message):
    Command failed: /usr/local/src/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake;--build;.;--config;Debug;--target;install;--;-v
    Working Directory: /usr/local/src/vcpkg/buildtrees/libzip/x64-linux-dbg
    See logs for more information:
      /usr/local/src/vcpkg/buildtrees/libzip/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/libzip/portfile.cmake:35 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package libzip:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libzip:x64-linux
  Vcpkg version: 2018.11.23-unknownhash

Additionally, attach any relevant sections from the log files above.

install-x64-linux-dbg-out.log：

In file included from /usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib/zip_crypto_gnutls.h:40:0,
                 from /usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib/zip_crypto.h:45,
                 from /usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib/zip_winzip_aes.c:36:
/usr/include/gnutls/crypto.h:35:10: 错误：未知的类型名‘gnutls_cipher_algorithm_t’
          gnutls_cipher_algorithm_t cipher,
          ^
/usr/include/gnutls/crypto.h:36:10: 错误：未知的类型名‘gnutls_datum_t’
          const gnutls_datum_t * key,
          ^
/usr/include/gnutls/crypto.h:37:10: 错误：未知的类型名‘gnutls_datum_t’
          const gnutls_datum_t * iv);
          ^
/usr/include/gnutls/crypto.h:59:34: 错误：未知的类型名‘gnutls_cipher_algorithm_t’
 int gnutls_cipher_get_block_size(gnutls_cipher_algorithm_t algorithm);
                                  ^
/usr/include/gnutls/crypto.h:60:31: 错误：未知的类型名‘gnutls_cipher_algorithm_t’
 int gnutls_cipher_get_iv_size(gnutls_cipher_algorithm_t algorithm);
                               ^
/usr/include/gnutls/crypto.h:61:32: 错误：未知的类型名‘gnutls_cipher_algorithm_t’
 int gnutls_cipher_get_tag_size(gnutls_cipher_algorithm_t algorithm);
                                ^
/usr/include/gnutls/crypto.h:66:34: 错误：未知的类型名‘gnutls_mac_algorithm_t’
 size_t gnutls_mac_get_nonce_size(gnutls_mac_algorithm_t algorithm);
                                  ^
/usr/include/gnutls/crypto.h:68:8: 错误：未知的类型名‘gnutls_mac_algorithm_t’
        gnutls_mac_algorithm_t algorithm,
        ^
/usr/include/gnutls/crypto.h:75:25: 错误：未知的类型名‘gnutls_mac_algorithm_t’
 int gnutls_hmac_get_len(gnutls_mac_algorithm_t algorithm);
                         ^
/usr/include/gnutls/crypto.h:76:22: 错误：未知的类型名‘gnutls_mac_algorithm_t’
 int gnutls_hmac_fast(gnutls_mac_algorithm_t algorithm,
                      ^
/usr/include/gnutls/crypto.h:81:8: 错误：未知的类型名‘gnutls_digest_algorithm_t’
        gnutls_digest_algorithm_t algorithm);
        ^
/usr/include/gnutls/crypto.h:85:25: 错误：未知的类型名‘gnutls_digest_algorithm_t’
 int gnutls_hash_get_len(gnutls_digest_algorithm_t algorithm);
                         ^
/usr/include/gnutls/crypto.h:86:22: 错误：未知的类型名‘gnutls_digest_algorithm_t’
 int gnutls_hash_fast(gnutls_digest_algorithm_t algorithm,
                      ^
In file included from /usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib/zip_crypto.h:45:0,
                 from /usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib/zip_winzip_aes.c:36:
/usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib/zip_crypto_gnutls.h:45:20: 错误：字段‘ctx_128’的类型不完全
  struct aes128_ctx ctx_128;
                    ^
/usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib/zip_crypto_gnutls.h:46:20: 错误：字段‘ctx_192’的类型不完全
  struct aes192_ctx ctx_192;
                    ^
/usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib/zip_crypto_gnutls.h:47:20: 错误：字段‘ctx_256’的类型不完全
  struct aes256_ctx ctx_256;
                    ^
[106/114] /usr/bin/cc -DHAVE_CONFIG_H -Ilib/.. -I/usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib -I/usr/local/src/vcpkg/installed/x64-linux/include -fPIC -g -MD -MT lib/CMakeFiles/zip.dir/zip_algorithm_bzip2.c.o -MF lib/CMakeFiles/zip.dir/zip_algorithm_bzip2.c.o.d -o lib/CMakeFiles/zip.dir/zip_algorithm_bzip2.c.o   -c /usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib/zip_algorithm_bzip2.c
[107/114] /usr/bin/cc -DHAVE_CONFIG_H -Ilib/.. -I/usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib -I/usr/local/src/vcpkg/installed/x64-linux/include -fPIC -g -MD -MT lib/CMakeFiles/zip.dir/zip_unchange_archive.c.o -MF lib/CMakeFiles/zip.dir/zip_unchange_archive.c.o.d -o lib/CMakeFiles/zip.dir/zip_unchange_archive.c.o   -c /usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib/zip_unchange_archive.c
[108/114] /usr/bin/cc -DHAVE_CONFIG_H -Ilib/.. -I/usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib -I/usr/local/src/vcpkg/installed/x64-linux/include -fPIC -g -MD -MT lib/CMakeFiles/zip.dir/zip_source_winzip_aes_decode.c.o -MF lib/CMakeFiles/zip.dir/zip_source_winzip_aes_decode.c.o.d -o lib/CMakeFiles/zip.dir/zip_source_winzip_aes_decode.c.o   -c /usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib/zip_source_winzip_aes_decode.c
[109/114] /usr/bin/cc -DHAVE_CONFIG_H -Ilib/.. -I/usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib -I/usr/local/src/vcpkg/installed/x64-linux/include -fPIC -g -MD -MT lib/CMakeFiles/zip.dir/zip_crypto_gnutls.c.o -MF lib/CMakeFiles/zip.dir/zip_crypto_gnutls.c.o.d -o lib/CMakeFiles/zip.dir/zip_crypto_gnutls.c.o   -c /usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib/zip_crypto_gnutls.c
FAILED: lib/CMakeFiles/zip.dir/zip_crypto_gnutls.c.o 
/usr/bin/cc -DHAVE_CONFIG_H -Ilib/.. -I/usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib -I/usr/local/src/vcpkg/installed/x64-linux/include -fPIC -g -MD -MT lib/CMakeFiles/zip.dir/zip_crypto_gnutls.c.o -MF lib/CMakeFiles/zip.dir/zip_crypto_gnutls.c.o.d -o lib/CMakeFiles/zip.dir/zip_crypto_gnutls.c.o   -c /usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib/zip_crypto_gnutls.c
In file included from /usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib/zip_crypto_gnutls.h:40:0,
                 from /usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib/zip_crypto.h:45,
                 from /usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib/zip_crypto_gnutls.c:38:
/usr/include/gnutls/crypto.h:35:10: 错误：未知的类型名‘gnutls_cipher_algorithm_t’
          gnutls_cipher_algorithm_t cipher,
          ^
/usr/include/gnutls/crypto.h:36:10: 错误：未知的类型名‘gnutls_datum_t’
          const gnutls_datum_t * key,
          ^
/usr/include/gnutls/crypto.h:37:10: 错误：未知的类型名‘gnutls_datum_t’
          const gnutls_datum_t * iv);
          ^
/usr/include/gnutls/crypto.h:59:34: 错误：未知的类型名‘gnutls_cipher_algorithm_t’
 int gnutls_cipher_get_block_size(gnutls_cipher_algorithm_t algorithm);
                                  ^
/usr/include/gnutls/crypto.h:60:31: 错误：未知的类型名‘gnutls_cipher_algorithm_t’
 int gnutls_cipher_get_iv_size(gnutls_cipher_algorithm_t algorithm);
                               ^
/usr/include/gnutls/crypto.h:61:32: 错误：未知的类型名‘gnutls_cipher_algorithm_t’
 int gnutls_cipher_get_tag_size(gnutls_cipher_algorithm_t algorithm);
                                ^
/usr/include/gnutls/crypto.h:66:34: 错误：未知的类型名‘gnutls_mac_algorithm_t’
 size_t gnutls_mac_get_nonce_size(gnutls_mac_algorithm_t algorithm);
                                  ^
/usr/include/gnutls/crypto.h:68:8: 错误：未知的类型名‘gnutls_mac_algorithm_t’
        gnutls_mac_algorithm_t algorithm,
        ^
/usr/include/gnutls/crypto.h:75:25: 错误：未知的类型名‘gnutls_mac_algorithm_t’
 int gnutls_hmac_get_len(gnutls_mac_algorithm_t algorithm);
                         ^
/usr/include/gnutls/crypto.h:76:22: 错误：未知的类型名‘gnutls_mac_algorithm_t’
 int gnutls_hmac_fast(gnutls_mac_algorithm_t algorithm,
                      ^
/usr/include/gnutls/crypto.h:81:8: 错误：未知的类型名‘gnutls_digest_algorithm_t’
        gnutls_digest_algorithm_t algorithm);
        ^
/usr/include/gnutls/crypto.h:85:25: 错误：未知的类型名‘gnutls_digest_algorithm_t’
 int gnutls_hash_get_len(gnutls_digest_algorithm_t algorithm);
                         ^
/usr/include/gnutls/crypto.h:86:22: 错误：未知的类型名‘gnutls_digest_algorithm_t’
 int gnutls_hash_fast(gnutls_digest_algorithm_t algorithm,
                      ^
In file included from /usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib/zip_crypto.h:45:0,
                 from /usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib/zip_crypto_gnutls.c:38:
/usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib/zip_crypto_gnutls.h:45:20: 错误：字段‘ctx_128’的类型不完全
  struct aes128_ctx ctx_128;
                    ^
/usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib/zip_crypto_gnutls.h:46:20: 错误：字段‘ctx_192’的类型不完全
  struct aes192_ctx ctx_192;
                    ^
/usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib/zip_crypto_gnutls.h:47:20: 错误：字段‘ctx_256’的类型不完全
  struct aes256_ctx ctx_256;
                    ^
[110/114] /usr/bin/cc -DHAVE_CONFIG_H -Ilib/.. -I/usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib -I/usr/local/src/vcpkg/installed/x64-linux/include -fPIC -g -MD -MT lib/CMakeFiles/zip.dir/zip_utf-8.c.o -MF lib/CMakeFiles/zip.dir/zip_utf-8.c.o.d -o lib/CMakeFiles/zip.dir/zip_utf-8.c.o   -c /usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib/zip_utf-8.c
[111/114] /usr/bin/cc -DHAVE_CONFIG_H -Ilib/.. -I/usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib -I/usr/local/src/vcpkg/installed/x64-linux/include -fPIC -g -MD -MT lib/CMakeFiles/zip.dir/zip_source_file.c.o -MF lib/CMakeFiles/zip.dir/zip_source_file.c.o.d -o lib/CMakeFiles/zip.dir/zip_source_file.c.o   -c /usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib/zip_source_file.c
[112/114] /usr/bin/cc -DHAVE_CONFIG_H -Ilib/.. -I/usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib -I/usr/local/src/vcpkg/installed/x64-linux/include -fPIC -g -MD -MT lib/CMakeFiles/zip.dir/zip_source_winzip_aes_encode.c.o -MF lib/CMakeFiles/zip.dir/zip_source_winzip_aes_encode.c.o.d -o lib/CMakeFiles/zip.dir/zip_source_winzip_aes_encode.c.o   -c /usr/local/src/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8/lib/zip_source_winzip_aes_encode.c
ninja: build stopped: subcommand failed.

**Comment by emlysoft** [comment]
My gcc version is 8.2.0, Perhaps the reason the version is too high, let me try it.

**Comment by emlysoft** [comment]
I tried GCC 6.3.1 GCC 4.9.2, the same error！

**Comment by PhoebeHui** [comment]
@emlysoft, thanks for posting this issue!

I installed libzip successfully with latest vcpkg and gcc7.4.0 on Ubuntu 18.04, could you have a try?

./vcpkg install libzip
The following packages will be built and installed:
    libzip[bzip2,core,openssl]:x64-linux
Starting package 1/1: libzip:x64-linux
Building package libzip[bzip2,core,openssl]:x64-linux...
-- Using cached /home/vcpkg/downloads/nih-at-libzip-rel-1-5-2.tar.gz
-- Using source at /home/vcpkg/buildtrees/libzip/src/rel-1-5-2-11aa1391e8
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Installing: /home/vcpkg/packages/libzip_x64-linux/share/libzip/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package libzip[bzip2,core,openssl]:x64-linux... done
Installing package libzip[bzip2,core,openssl]:x64-linux...
Installing package libzip[bzip2,core,openssl]:x64-linux... done
Elapsed time for package libzip:x64-linux: 8.606 s

Total elapsed time: 8.606 s

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
