### ISSUE TITLE
[qt5-base][ms-angle] File conflict. 

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#6579]
```
Installing package qt5-base[core]:x64-windows...
The following files are already installed in G:/vcpkg_test/vcpkg/installed/x64-windows and are in conflict with qt5-base:x64-windows

Installed by ms-angle:x64-windows
    bin/libEGL.dll
    bin/libGLESv2.dll
    lib/libEGL.lib
    lib/libGLESv2.lib
```
(triplet x64-windows)

Solution: Move both into separate folders?

**Comment by Voskrese** [comment]
maybe we should add the option `--force-install`
file overwriting and deletion from the previous package in the database

_and use at your own risk_ ))

**Comment by Voskrese** [comment]
@ras0219-msft 
By the way, how to cancel the check after manually editing the database \status and * .list

whether it is possible to remove the check at all, a useless function, on the contrary, prevents you from editing the necessary

**Comment by seanwarren** [comment]
An alternative option might be to get Qt5 to use the vcpkg install of ms-angle by setting `ANGLE_DIR` in the Qt5 portfile (and making ms-angle a dependency on windows)

See also: https://doc.qt.io/qt-5/windows-requirements.html

**Comment by JackBoosY** [comment]
@Voskrese I think using the force-install feature may cause some invisible problems.
We should connect the ports as much as possible and prevent such problems from occurring.

**Comment by Voskrese** [comment]
Yes, I do not argue, but this is all for developers, the system should be flexible and customizable
Naturally, the --force option is not recommended, but it will be useful.

but it all depends on you) I just suggest

**Comment by heydojo** [comment]
> An alternative option might be to get Qt5 to use the vcpkg install of ms-angle by setting ANGLE_DIR in the Qt5 portfile (and making ms-angle a dependency on windows)

See also: https://doc.qt.io/qt-5/windows-requirements.html

This is the optimal way but:

- Qt commonly ship their own patched versions of dependent software (like ANGLE)
- It creates an additional maintenance burden of an unknown amount to maintain compatible build versions shared amongst projects dependant upon said software

Side note: The whole of Qt is like this. The exact same files copied multiple times into the installation folders for each Qt plugin. Files which should be inside the **installed\x64-windows\bin** directory are inside the **installed\x64-windows\tools** directory.

**Comment by JackBoosY** [comment]
@heydojo The `bin` directory only saves the dynamic library, and `tools` holds the generated tools.

**Comment by Neumann-A** [comment]
Qt no longer builds angle
