### ISSUE TITLE
[openni] Linker error (x64-windows)

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#6580]
Error:
` LINK : fatal error LNK1104: cannot open file 'MSCOREE.lib'`

should probably have an extra check in the portfile that something must be installed

**Comment by Neumann-A** [comment]
Full log:
[build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/3212270/build-x64-windows-rel-out.log)

**Comment by Voskrese** [comment]
`vcpkg env --triplet ...`

`where $LIB:MSCOREE.lib`

`C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\Lib\um\x64\mscoree.lib`

**Comment by Neumann-A** [comment]
@voskrese: I don't need a workaround. I need a fix in the portfile that checks wehter the requirements are installed and give an early error message otherwise. I am just analyzing all build_failures from one of my PRs  and opening up issues if I find something strange.

**Comment by Voskrese** [comment]
ok

**Comment by JackBoosY** [comment]
Hi @Neumann-A, I can't repro this issue, can you repro it now?

**Comment by Neumann-A** [comment]
@JackBoosY:
         LINK : fatal error LNK1104: cannot open file 'MSCOREE.lib' [E:\qt_5.12.4\buildtrees\openni2\x64-windows\2.2-beta2-a8c7829707\Source\Drivers\Kinect\Kinect.vcxproj]

The portfile just needs a detection of what is missing and tell the user before he tries to install the port.

**Comment by JackBoosY** [comment]
Warning message has been added into portfile.cmake.

Close this issue.
