### ISSUE TITLE
[nmap] Build error due to openssl (x64-windows)?

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#6581]
[build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/3212310/build-x64-windows-rel-out.log)
[build-x64-windows-rel-err.log](https://github.com/microsoft/vcpkg/files/3212311/build-x64-windows-rel-err.log)
[msys-pacman-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/3212314/msys-pacman-x64-windows-out.log)

Probably also something missing.

**Comment by Voskrese** [comment]
I think there is a mistake

```
'--with-openssl=G:/vcpkg_test/qt5test/installed/x64-windows/bin/'
'--with-libssh2=G:/vcpkg_test/qt5test/installed/x64-windows/bin/'
'--with-libssl-prefix=G:/vcpkg_test/qt5test/installed/x64-windows/bin/'
```

prefix
--with-libssl-prefix=G:/vcpkg_test/qt5test/ **installed/x64-windows**

**Comment by Neumann-A** [comment]
seems to build with that. -> Port bug. Also the paths should probably be set in OPTIONS_DEBUG and _RELEASE to that debug/release openssl, ssh2 gets linked?

**Comment by JackBoosY** [comment]
```
cl : Command line warning D9002 : ignoring unknown option '--version'
cl : Command line error D8003 : missing source filename
configure: error: Your version of OpenSSL does not support SHA-256. Please install OpenSSL 0.9.8 or later.
configure: error: /f/vcpkg/buildtrees/nmap/src/nmap-7-04a0102d9c/nping/configure failed for nping
```

In file `vcpkg\buildtrees\nmap\src\nmap-7-04a0102d9c\nping\configure` Line 5098:
```  as_fn_error $? "Your version of OpenSSL does not support SHA-256. Please install OpenSSL 0.9.8 or later." "$LINENO" 5```

line 5088: `$as_echo "#define HAVE_OPENSSL 1" >>confdefs.h`  maybe `confdefs.h` not found?

**Comment by JackBoosY** [comment]
It seems that nping configure cannot find the openssl libraries.
In _nmap_source\nping\configure_ line 5090:
```
OPENSSL_LIBS="-lssl -lcrypto"
```
But the openssl libraries in windows should be **libeay32.lib** and **ssleay32.lib**.
I tried to change them to -llibeay32 and -lssleay32 but didn't work.

Any ideas guys?

**Comment by Neumann-A** [comment]
@JackBoosY Try explicit full paths without the extra -l ?

**Comment by Neumann-A** [comment]
@JackBoosY In general libeay32 and ssleay32 require additional windows dependencies.
In qt this is:
`PSQL_LIBS=${PSQL_RELEASE} ${SSL_RELEASE} ${EAY_RELEASE} ws2_32.lib secur32.lib advapi32.lib shell32.lib crypt32.lib user32.lib gdi32.lib"`
so you probably need to also add `ws2_32.lib secur32.lib advapi32.lib shell32.lib crypt32.lib user32.lib gdi32.lib`

**Comment by JackBoosY** [comment]
@Neumann-A Replace this line with `OPENSSL_LIBS="ssleay32.lib libeay32.lib"`, works.

**Comment by JackBoosY** [comment]
@Neumann-A Thanks for reporting this issue.
#7811 has been merged, please update vcpkg and rebuild nmap.

Thanks.
