### ISSUE TITLE
[realsense2] Win7 Build error (x64-windows)

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#6582]
>        G:\vcpkg_test\vcpkg\buildtrees\realsense2\src\v2.16.1-6d4bf74367\src\win7\win7-uvc.cpp(14): fatal error C1189: #error: ( "Librealsense Error!: Featuring UVC Metadata requires WinSDK 10.0.10586.0.  Install the required toolset to proceed. Alternatively, uncheck ENFORCE_METADATA option in CMake GUI tool") [G:\vcpkg_test\vcpkg\buildtrees\realsense2\x64-windows-dbg\realsense2.vcxproj]

also requires extra guarding or changes to the portfile if something is missing.

**Comment by NancyLi1013** [comment]
Hi @Neumann-A, thanks for posting this issue. Could you help provide the reproduce steps or error logs? I try to install and build it on my machine. This port can be installed successfully.
```
PS D:\vcpkg> .\vcpkg.exe install realsense2:x64-windows
The following packages will be built and installed:
    realsense2[core]:x64-windows
Starting package 1/1: realsense2:x64-windows
Building package realsense2[core]:x64-windows...
-- Downloading https://github.com/IntelRealSense/librealsense/archive/v2.16.1.ta
r.gz...
-- Extracting source D:/vcpkg/downloads/IntelRealSense-librealsense-v2.16.1.tar.
gz
-- Using source at D:/vcpkg/buildtrees/realsense2/src/v2.16.1-6d4bf74367
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package realsense2[core]:x64-windows... done
Installing package realsense2[core]:x64-windows...
Installing package realsense2[core]:x64-windows... done
Elapsed time for package realsense2:x64-windows: 14.47 min

Total elapsed time: 14.47 min

The package realsense2:x64-windows provides CMake targets:

    find_package(realsense2 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE realsense2::realsense2 realsense2::realse
nse-file)
```

**Comment by Neumann-A** [comment]
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/3215561/config-x64-windows-out.log)
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3215562/install-x64-windows-dbg-out.log)

Probably a Win7 issue. I checked and I have more than one Win10 SDK in VS2017 installed

**Comment by NancyLi1013** [comment]
@Neumann-A, sorry for the late reply. During these days, I try to install the port on Win7 with different Win 10 SDK versions in VS2017. I found that this issue was related with Win 8.1 SDK. So please check if you have installed Windows 8.1 SDK in VS2017 on your machine. If yes, you can uninstalled Win 8.1 SDK  in VS2017. This issue should be fixed.

**Comment by Neumann-A** [comment]
@NancyLi1013: Checked it and have the Win8.1 SDK installed. Is there a way to detect this circumstance and abort the build early with a message saying that realsense2 does not work with Win8.1 SDK?

**Comment by NancyLi1013** [comment]
@Neumann-A, thanks for your suggestion. It seems that there is no available way to detect this circumstance now. But we can add the message in portfile.cmake:
```
message("${PORT} does not work with Win 8.1 SDK on Windows 7. If you have installed, please try to remove it from individual components in VS.")
```
Do you agree with this or you have another better way to solve this issue?

**Comment by NancyLi1013** [comment]
Personally, this is a workaround issue. We can remove Win8.1 SDK from Visual Studio in Win 7 to fix this issue.
Please feel free to reopen if you have any concern or good suggestion about this issue.
