### ISSUE TITLE
[LLVM] Linker error missing ld.lib (x64-windows)

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#6584]
Reason:
```
find_library(DL_LIBRARY_PATH dl)
if (DL_LIBRARY_PATH)
  list(APPEND LIBS dl)
endif()
```
in G:\vcpkg_test\vcpkg\buildtrees\llvm\src\llvm-7.0.0.src\tools\clang\tools\libclang\CMakeLists.txt

should probably be `list(APPEND LIBS "${DL_LIBRARY_PATH}")`

**Comment by Neumann-A** [comment]
LLVM could also use an update to 8.0.0. But to be honest LLVM is most likely used with --head anyway ;)

**Comment by JackBoosY** [comment]
PR has been merged, close this issue.
