### ISSUE TITLE
[libgeotiff] Missing find_dependency(PROJ4) in config file

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#6592]
If I read the configure logs correctly it tries to link target proj and not library proj supplied by proj config file. For this to work correctly libgeotiff must make a call to find_dependency(PROJ4) before including its target/depens cmake files.

**Comment by Voskrese** [comment]
maybe worth using `symlink ` in such conflicting cases

example
```
add_custom_target(symlink
    ${CMAKE_COMMAND} -E create_symlink ${CMAKE_INSTALL_PREFIX}//bin/proj.dll ${CMAKE_INSTALL_PREFIX}/bin//projd.dll
    COMMAND ${CMAKE_COMMAND} -E create_symlink ${CMAKE_INSTALL_PREFIX}/Include ${CMAKE_INSTALL_PREFIX}/debug/include)
```

`cmake -E create_symlink`

```
execute_process(COMMAND  ${CMAKE_COMMAND}  -E create_symlink
    "@CMAKE_SOURCE_DIR@/include" # Old name
    "@CMAKE_INSTALL_PREFIX@/include" # New name
)
```

**Comment by Voskrese** [comment]
@Neumann-A Thank you, Sasha ))
