### ISSUE TITLE
Error: Building package pango:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by dumiaomiao** [microsoft/vcpkg#6622]
Starting package 20/21: pango:x64-windows
Building package pango[core]:x64-windows...
-- Using cached E:/vcpkg/downloads/pango-1.40.11.tar.xz
-- Using source at E:/vcpkg/buildtrees/pango/src/1.40.11-f997ae867d
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:202 (message):
    Command failed: E:/CMake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v
    Working Directory: E:/vcpkg/buildtrees/pango/x64-windows-dbg
    See logs for more information:
      E:\vcpkg\buildtrees\pango\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/pango/portfile.cmake:25 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package pango:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: pango:x64-windows
  Vcpkg version: 2018.11.23-nohash

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3219567/install-x64-windows-dbg-out.log)

**Comment by JackBoosY** [comment]
Hi @dumiaomiao, please attach the error log `E:\vcpkg\buildtrees\pango\install-x64-windows-dbg-out.log`.

Thanks.

**Comment by JackBoosY** [comment]
```
E:\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h: warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
E:\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(95): error C2001: newline in constant
E:\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(297): error C2001: newline in constant
E:\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(484): error C2001: newline in constant
E:\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(551): error C2001: newline in constant
E:\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(616): error C2001: newline in constant
E:\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(622): error C2001: newline in constant
E:\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(628): error C2001: newline in constant
```

Your source code seems to be unicode encoded, and the compiler can't handle this problem.

Please delete folder _buildress/pango_ and file _downloads/pangomm-2.40.1.tar.xz_ , and rebuild pango.

Thanks.

**Comment by hair-man** [comment]
same error and build failed.
`> ./vcpkg install pango:x64-windows
The following packages will be built and installed:
    pango[core]:x64-windows
Starting package 1/1: pango:x64-windows
Building package pango[core]:x64-windows...
-- Using cached C:/Users/Administrator/source/repos/vcpkg/downloads/pango-1.40.11.tar.xz
-- Using source at C:/Users/Administrator/source/repos/vcpkg/buildtrees/pango/src/1.40.11-f997ae867d
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:202 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v
    Working Directory: C:/Users/Administrator/source/repos/vcpkg/buildtrees/pango/x64-windows-dbg
    See logs for more information:
      C:\Users\Administrator\source\repos\vcpkg\buildtrees\pango\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/pango/portfile.cmake:25 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package pango:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: pango:x64-windows
  Vcpkg version: 2018.11.23-nohash`

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3223430/install-x64-windows-dbg-out.log)

**Comment by hair-man** [comment]
> ```
> E:\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h: warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
> E:\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(95): error C2001: newline in constant
> E:\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(297): error C2001: newline in constant
> E:\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(484): error C2001: newline in constant
> E:\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(551): error C2001: newline in constant
> E:\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(616): error C2001: newline in constant
> E:\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(622): error C2001: newline in constant
> E:\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(628): error C2001: newline in constant
> ```
> 
> Your source code seems to be unicode encoded, and the compiler can't handle this problem.
> 
> Please delete folder _buildress/pango_ and file _downloads/pangomm-2.40.1.tar.xz_ , and rebuild pango.
> 
> Thanks.

C:\Users\Administrator\source\repos\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(95): error C2001: newline in constant
C:\Users\Administrator\source\repos\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(297): error C2001: newline in constant
C:\Users\Administrator\source\repos\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(484): error C2001: newline in constant
C:\Users\Administrator\source\repos\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(551): error C2001: newline in constant
C:\Users\Administrator\source\repos\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(616): error C2001: newline in constant
C:\Users\Administrator\source\repos\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(622): error C2001: newline in constant
C:\Users\Administrator\source\repos\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(628): error C2001: newline in constant
C:\Users\Administrator\source\repos\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(634): error C2001: newline in constant
C:\Users\Administrator\source\repos\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h: warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
C:\Users\Administrator\source\repos\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(95): error C2001: newline in constant
C:\Users\Administrator\source\repos\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(297): error C2001: newline in constant
C:\Users\Administrator\source\repos\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(484): error C2001: newline in constant
C:\Users\Administrator\source\repos\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(551): error C2001: newline in constant
C:\Users\Administrator\source\repos\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(616): error C2001: newline in constant
C:\Users\Administrator\source\repos\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(622): error C2001: newline in constant
C:\Users\Administrator\source\repos\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(628): error C2001: newline in constant
C:\Users\Administrator\source\repos\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(634): error C2001: newline in constant
C:\Users\Administrator\source\repos\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h: warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
C:\Users\Administrator\source\repos\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(95): error C2001: newline in constant
C:\Users\Administrator\source\repos\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(297): error C2001: newline in constant
C:\Users\Administrator\source\repos\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(484): error C2001: newline in constant
C:\Users\Administrator\source\repos\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(551): error C2001: newline in constant
C:\Users\Administrator\source\repos\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(616): error C2001: newline in constant
C:\Users\Administrator\source\repos\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(622): error C2001: newline in constant
C:\Users\Administrator\source\repos\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(628): error C2001: newline in constant
C:\Users\Administrator\source\repos\vcpkg\buildtrees\pango\src\1.40.11-f997ae867d\pango\pango-language-sample-table.h(634): error C2001: newline in constant

useless for me

**Comment by wangli28** [comment]
I installed it successfully with VS2019.22.27706.1 and VCPKG latest source.

PS F:\Lily\vcpkg> .\vcpkg.exe install pango:x64-windows
The following packages will be built and installed:
    pango[core]:x64-windows
Starting package 1/1: pango:x64-windows
Building package pango[core]:x64-windows...
-- Using cached F:/Lily/vcpkg/downloads/pango-1.40.11.tar.xz
-- Using source at F:/Lily/vcpkg/buildtrees/pango/src/1.40.11-f997ae867d
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package pango[core]:x64-windows... done
Installing package pango[core]:x64-windows...
Installing package pango[core]:x64-windows... done
Elapsed time for package pango:x64-windows: 1.072 min

Total elapsed time: 1.072 min

**Comment by gf109** [comment]
Add 
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /utf-8")
into the vcpkg\ports\pango\CMakeLists.txt
Rebuild.

Same issue in gtk too.
Everytime the code page warnning and following errors
you should try add "/utf-8" option to cl.exe.

**Comment by dumiaomiao** [comment]
> Add
> set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /utf-8")
> into the vcpkg\ports\pango\CMakeLists.txt
> Rebuild.
> 
> Same issue in gtk too.
> Everytime the code page warnning and following errors
> you should try add "/utf-8" option to cl.exe.

thanks, it worked.😄

E:\vcpkg>vcpkg install pango:x64-windows
The following packages will be built and installed:
    pango[core]:x64-windows
Starting package 1/1: pango:x64-windows
Building package pango[core]:x64-windows...
-- Downloading http://ftp.gnome.org/pub/GNOME/sources/pango/1.40/pango-1.40.11.tar.xz...
-- Extracting source E:/vcpkg/downloads/pango-1.40.11.tar.xz
-- Applying patch 0001-fix-static-symbols-export.diff
-- Using source at E:/vcpkg/buildtrees/pango/src/1.40.11-f997ae867d
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package pango[core]:x64-windows... done
Installing package pango[core]:x64-windows...
Installing package pango[core]:x64-windows... done
Elapsed time for package pango:x64-windows: 51.69 s

Total elapsed time: 51.69 s

**Comment by dumiaomiao** [comment]
E:\vcpkg>vcpkg install gtk:x64-windows
The following packages will be built and installed:
    gtk[core]:x64-windows
Starting package 1/1: gtk:x64-windows
Building package gtk[core]:x64-windows...
-- Downloading https://ftp.gnome.org/pub/gnome/sources/gtk+/3.22/gtk+-3.22.19.tar.xz...
-- Extracting source E:/vcpkg/downloads/gtk+-3.22.19.tar.xz
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:202 (message):
    Command failed: E:/CMake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v
    Working Directory: E:/vcpkg/buildtrees/gtk/x64-windows-dbg
    See logs for more information:
      E:\vcpkg\buildtrees\gtk\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/gtk/portfile.cmake:33 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package gtk:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: gtk:x64-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

**Same solution as above**
add 
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /utf-8")
into
vcpkg\ports\gtk\CMakeLists.txt
rebulid.

E:\vcpkg>vcpkg install gtk:x64-windows
The following packages will be built and installed:
    gtk[core]:x64-windows
Starting package 1/1: gtk:x64-windows
Building package gtk[core]:x64-windows...
-- Downloading https://ftp.gnome.org/pub/gnome/sources/gtk+/3.22/gtk+-3.22.19.tar.xz...
-- Extracting source E:/vcpkg/downloads/gtk+-3.22.19.tar.xz
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package gtk[core]:x64-windows... done
Installing package gtk[core]:x64-windows...
Installing package gtk[core]:x64-windows... done
Elapsed time for package gtk:x64-windows: 14.98 min

Total elapsed time: 14.98 min

**Comment by JackBoosY** [comment]
Hi everyone. I've fixed this issue. Please update vcpkg and rebuild pango/gtk.

Thanks.
