### ISSUE TITLE
[shiva] Building failed with "Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE)"

### ISSUE THREAD

**Issue by wangli28** [microsoft/vcpkg#6633]
My device version: Windows10 1809
My VS version: VS2017
I tried install shiva-sfml with command `.\vcpkg.exe install shiva-sfml`, I got this error:

Starting package 88/89: shiva:x86-windows
Building package shiva[core]:x86-windows...
-- Downloading https://github.com/Milerius/shiva/archive/1.0.tar.gz...
-- Extracting source E:/test/vcpkg/downloads/Milerius-shiva-1.0.tar.gz
-- Using source at E:/test/vcpkg/buildtrees/shiva/src/1.0-2860004d47
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: E:/test/vcpkg/buildtrees/shiva/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      E:\test\vcpkg\buildtrees\shiva\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:273 (vcpkg_execute_required_process)
  ports/shiva/portfile.cmake:11 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package shiva:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: shiva:x86-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

Attach this log:
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/3222355/config-x86-windows-out.log)

**Comment by Voskrese** [comment]
`set(PYTHON_EXECUTABLE ${PYTHON3})` or PYTHON2

**Comment by JackBoosY** [comment]
@Voskrese Thanks, but no work, I think this is definitely a vcpkg bug.

**Comment by Voskrese** [comment]
CMake Error at `E:/test/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake` 137 (message):

`  Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE)`

`"E:/test/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe" "E:/test/vcpkg/buildtrees/shiva/src/1.0-2860004d47" "-DSHIVA_BUILD_TESTS=OFF" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=E:/test/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=E:/test/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=E:/test/vcpkg/packages/shiva_x86-windows/debug"`

`-DPYTHON_EXECUTABLE="E:/test/vcpkg/.../.../.../python"`

```
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA # Disable this option if project cannot be built with Ninja
    OPTIONS
           ....
           -DPYTHON_EXECUTABLE=${PYTHON3}
)
```
