### ISSUE TITLE
Add LASLib

### ISSUE THREAD

**Issue by Highlife1911** [microsoft/vcpkg#6634]
Add LASLib https://github.com/LAStools/LAStools/tree/master/LASlib

**Comment by NancyLi1013** [comment]
Hi @Highlife1911, thanks for posting this request. It's duplicated of #2357, #3338. Please pay attention to the progress of issue #2357.

**Comment by Highlife1911** [comment]
LASLib and liblas are different libraries. liblas is deprecated and the author does not recommend it for new projects.

**Comment by NancyLi1013** [comment]
Hi @Highlife1911, sorry for my mistake last time. LASLib has been included in lastools port. Please try to update vcpkg and use it.
