### ISSUE TITLE
Unknown parameter bash for integrate

### ISSUE THREAD

**Issue by linonetwo** [microsoft/vcpkg#6638]
After install, following readme https://github.com/microsoft/vcpkg#tab-completion--auto-completion , I got:

```shell
% ./vcpkg integrate bash
Unknown parameter bash for integrate
% ./vcpkg integrate zsh 
Unknown parameter zsh for integrate
```

**Comment by JackBoosY** [comment]
Hi @linonetwo, please provide your linux/unix system version info.
Thanks.

**Comment by linonetwo** [comment]
I'm in MacOS 10.14.5 (18F132)   zsh 5.7.1 (x86_64-apple-darwin18.2.0)

Closing this since it's not important compare to the fact that It's not easy to use boost.

**Comment by Cchalongg** [comment]
My love
