### ISSUE TITLE
applocal.ps1 should check dependencies timestamps

### ISSUE THREAD

**Issue by willyd** [microsoft/vcpkg#664]
[applocal.ps1](https://github.com/Microsoft/vcpkg/blob/master/scripts/buildsystems/msbuild/applocal.ps1#L21) only checks if the dependency was previously copied. I believe it should also check if the files are different to avoid keeping and old copy of a port dll in the output directory of a consuming project.

And while you are at it, it could try to hardlink the dll if possible and copy otherwise.

**Comment by LilyWangL** [comment]
This issue hasn’t been updated in a year, if it is still an issue, please reopen.
