### ISSUE TITLE
curl[tool] fails

### ISSUE THREAD

**Issue by ray42** [microsoft/vcpkg#6643]
It seems like the most recent changes to the curl port has broken the "tool" feature package installation:

==================================
C:\vcpkgtest2>vcpkg install curl[tool] --featurepackages
The following packages will be built and installed:
    curl[core,ssl,tool,winssl]:x86-windows
Starting package 1/1: curl:x86-windows
Building package curl[core,ssl,tool,winssl]:x86-windows...
-- Using cached C:/vcpkgtest2/downloads/curl-curl-curl-7_65_0.tar.gz
-- Using source at C:/vcpkgtest2/buildtrees/curl/src/url-7_65_0-51a6e078ba
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: C:/vcpkgtest2/packages/curl_x86-windows/share/curl/copyright
CMake Error at ports/curl/portfile.cmake:137 (file):
  file failed to open for reading (No such file or directory):

    C:/vcpkgtest2/packages/curl_x86-windows/share/curl/curl-target-release.cmake
Call Stack (most recent call first):
  scripts/ports.cmake:71 (include)

Error: Building package curl:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: curl:x86-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

==================================

We have a nightly build which failed when https://github.com/microsoft/vcpkg/pull/6429 was merged in. Editing the file ports/curl/portfile.cmake file to rename curl-target-release.cmake to CURLTarget-release.cmake fixes this.

**Comment by PhoebeHui** [comment]
@ray42, thank you for report this issue!

My fault, I updated it in #6429, but suddenly removed by following commits, Sorry for the breaks.
Summit a fix https://github.com/microsoft/vcpkg/pull/6649.

**Comment by PhoebeHui** [comment]
Fix merged, please open a new issue if you encounter other issue related to curl 7.65.0.
