### ISSUE TITLE
libWebP[all] FAILED (x86-windows-static | x64-windows-static)

### ISSUE THREAD

**Issue by gdiObjects** [microsoft/vcpkg#6646]
NOTE: libwebp[core] x86-windows-static | libwebp[core]:x64-windows-static both work.
used "git pull," then ".\vcpkg update" first

D:\Development\Projects\vcpkg>.\vcpkg install libwebp[all]:x86-windows-static --recurse
The following packages will be rebuilt:
    libwebp[all,core]:x86-windows-static
Starting package 1/2: libwebp:x86-windows-static
Removing package libwebp:x86-windows-static...
Removing package libwebp:x86-windows-static... done
Purging package libwebp:x86-windows-static...
Purging package libwebp:x86-windows-static... done
Elapsed time for package libwebp:x86-windows-static: 71.46 ms
Starting package 2/2: libwebp:x86-windows-static
Building package libwebp[all,core]:x86-windows-static...
-- Using cached D:/Development/Projects/vcpkg/downloads/webmproject-libwebp-v1.0.2.tar.gz
-- Extracting source D:/Development/Projects/vcpkg/downloads/webmproject-libwebp-v1.0.2.tar.gz
-- Applying patch 0001-build-fixes.patch
-- Applying patch 0002-cmake-config-add-backwards-compatibility.patch
-- Applying patch 0003-remove-missing-symbol.patch
-- Applying patch 0004-add-missing-linked-library.patch
-- Using source at D:/Development/Projects/vcpkg/buildtrees/libwebp/src/v1.0.2-80b0c41c25
-- Configuring x86-windows-static
-- Building x86-windows-static-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:202 (message):
    Command failed: D:/Development/Projects/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v
    Working Directory: D:/Development/Projects/vcpkg/buildtrees/libwebp/x86-windows-static-dbg
    See logs for more information:
      D:\Development\Projects\vcpkg\buildtrees\libwebp\install-x86-windows-static-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/libwebp/portfile.cmake:60 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package libwebp:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libwebp:x86-windows-static
  Vcpkg version: 2018.11.23-nohash
[install-x86-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/3225181/install-x86-windows-static-dbg-out.log)
[config-x86-windows-static-out.log](https://github.com/microsoft/vcpkg/files/3225182/config-x86-windows-static-out.log)

**Comment by JackBoosY** [comment]
Hi @gdiObjects, thanks for reporting this issue!
I've fixed this issue. Please update vcpkg and rebuild libwebp[all].

Thanks.
