### ISSUE TITLE
freeimage FAILED (x86-windows-static | x64-windows-static)

### ISSUE THREAD

**Issue by gdiObjects** [microsoft/vcpkg#6647]
used "git pull," then ".\vcpkg update" first

D:\Development\Projects\vcpkg>.\vcpkg install freeimage:x86-windows-static
The following packages will be built and installed:
    freeimage[core]:x86-windows-static
Starting package 1/1: freeimage:x86-windows-static
Building package freeimage[core]:x86-windows-static...
-- Downloading http://downloads.sourceforge.net/freeimage/FreeImage3180.zip...
-- Using source at D:/Development/Projects/vcpkg/buildtrees/freeimage/src/eImage3180-2288df34d2
-- Configuring x86-windows-static
-- Building x86-windows-static-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:202 (message):
    Command failed: D:/Development/Projects/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v
    Working Directory: D:/Development/Projects/vcpkg/buildtrees/freeimage/x86-windows-static-dbg
    See logs for more information:
      D:\Development\Projects\vcpkg\buildtrees\freeimage\install-x86-windows-static-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/freeimage/portfile.cmake:54 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package freeimage:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: freeimage:x86-windows-static
  Vcpkg version: 2018.11.23-nohash
[install-x86-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/3225352/install-x86-windows-static-dbg-out.log)
[config-x86-windows-static-out.log](https://github.com/microsoft/vcpkg/files/3225353/config-x86-windows-static-out.log)

**Comment by JackBoosY** [comment]
#6648 may also solve this problem.

**Comment by JackBoosY** [comment]
Hi @gdiObjects, can you update vcpkg and try to rebuild freeimage again?

Thanks.

**Comment by gdiObjects** [comment]
I tested both libweb[all] static x86 & static x64 + freeimage static x86 & static x64 and all built perfectly (haven't used the code, but building them first is important).

**Comment by JackBoosY** [comment]
@gdiObjects Okay, please open a new issue if there is a usage problem.
