### ISSUE TITLE
[libjpeg-turbo] Requires wrapper to correctly find debug/release variant

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#6656]
From CMake FindJPEG.cmake:
```
set(jpeg_names ${JPEG_NAMES} jpeg jpeg-static libjpeg libjpeg-static)
foreach(name ${jpeg_names})
  list(APPEND jpeg_names_debug "${name}d")
endforeach()
```

**Comment by JackBoosY** [comment]
The upstream should support it.

**Comment by Neumann-A** [comment]
for the time vcpkg should install a vcpkg_cmake_wrapper to make sure that the right libraries are always found

**Comment by JackBoosY** [comment]
@Neumann-A We already do that. See https://github.com/microsoft/vcpkg/blob/master/ports/libjpeg-turbo/vcpkg-cmake-wrapper.cmake

**Comment by Neumann-A** [comment]
That is not enough. You have to do a `find_library` call for `JPEG_LIBRARY_RELEASE` and `JPEG_LIBRARY_DEBUG` before the find_package call and make sure that those variables are correctly set. The point of the current wrapper is just to add the target `JPEG::JPEG`.
But the current wrapper is just a copy of a newer findJPEG within cmake another example why vcpkg should have FindModules instead of the wrappers.

**Comment by PhoebeHui** [comment]
Related to https://github.com/microsoft/vcpkg/issues/15731

**Comment by JackBoosY** [comment]
Upstraem PR https://gitlab.kitware.com/cmake/cmake/-/merge_requests/1974.

**Comment by dg0yt** [comment]
I would like to note that `libjpeg-turbo` is just one (compatible) implementation of the library to be found by `FindJPEG.cmake`.

**Comment by Neumann-A** [comment]
@JackBoosY:
 You can close https://gitlab.kitware.com/cmake/cmake/-/issues/22481. 
 The vcpkg maintainer guidelines forbid messing with upstream naming as such I changed title of this issue to correctly reflect what needs to be done.

**Comment by JackBoosY** [comment]
@Neumann-A Any way, use `FindJPEG.cmake` will fail to find the debug library generated in vcpkg.
So I have an idea:
1. Export all the jpeg targets.
2. Add cmake wrapper to avoid use `FindJPEG.cmake` in vcpkg toolchain.

**Comment by Neumann-A** [comment]
Please no. Just fix the default `FindJPEG.cmake` which comes with CMake.

**Comment by JackBoosY** [comment]
@Neumann-A  We can't patch `FindJPEG.cmake` in our side, the only way is add wrapper or copy the correct `FindJPEG.cmake` to _share/JPEG_.

**Comment by dg0yt** [comment]
>> Just fix the default `FindJPEG.cmake` which comes with CMake.
>
> We can't patch FindJPEG.cmake in our side, the only way is add wrapper or copy the correct FindJPEG.cmake to share/JPEG.

@JackBoosY Together with the issue's title, I assume @Neumann-A meant fixing *by adding a suitable wrapper*, not fixing the module files. It was meant to make clear that it is wrong to "avoid use FindJPEG.cmake".

**Comment by JackBoosY** [comment]
@dg0yt See the upstream code https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/FindJPEG.cmake#L61-64:
```cmake
set(jpeg_names ${JPEG_NAMES} jpeg jpeg-static libjpeg libjpeg-static)
foreach(name ${jpeg_names})
  list(APPEND jpeg_names_debug "${name}d")
endforeach()

if(NOT JPEG_LIBRARY)
  find_library(JPEG_LIBRARY_RELEASE NAMES ${jpeg_names} NAMES_PER_DIR)
  find_library(JPEG_LIBRARY_DEBUG NAMES ${jpeg_names_debug} NAMES_PER_DIR)
  include(${CMAKE_CURRENT_LIST_DIR}/SelectLibraryConfigurations.cmake)
  select_library_configurations(JPEG)
  mark_as_advanced(JPEG_LIBRARY_RELEASE JPEG_LIBRARY_DEBUG)
endif()
```
The suffix `d` is mandatory and we cannot fix it in any way.

**Comment by Neumann-A** [comment]
@JackBoosY  
Just like expat: 
https://github.com/microsoft/vcpkg/blob/master/ports/expat/vcpkg-cmake-wrapper.cmake

do the `find_library` call with the "vcpkg correct names" before the `find_package` call.

> The suffix d is mandatory and we cannot fix it in any way.

(feels like speaking to a wall which I really don't get)

**Comment by PhoebeHui** [comment]
I would help follow up this issue and continue the PR https://github.com/microsoft/vcpkg/pull/18742/

**Comment by dg0yt** [comment]
> The suffix `d` is mandatory and we cannot fix it in any way.

@JackBoosY You fix this by calling `find_library(JPEG_LIBRARY_DEBUG ...)` in the wrapper with custom parameters. This creates a cache variable `JPEG_LIBRARY_DEBUG`, and the following call in the pristine cmake find module is a no-op. This is what cmake cache variables were created for.

**Comment by JackBoosY** [comment]
@dg0yt So since libjpeg expoted the targets, why not to use them. I think they are more safe than the `FindJPEG.cmake`.

**Comment by dg0yt** [comment]
> @dg0yt So since libjpeg expoted the targets, why not to use them. I think they are more safe than the `FindJPEG.cmake`.

I'm not sure which exported targets you are refering to.
This issue is about cmake's `FindJPEG.cmake` module. vcpkg claims to support cmake down to version 3.1 in user projects. So vcpkg must ensure that `find_package(JPEG)' provides the right configuration. 
**You must not ask for user projects to change.** Behaviour with vcpkg must be the same as without vcpkg, only that libs, definitions, includes etc. must come from the installed ports.
