### ISSUE TITLE
Error: Building package icu:x86-windows failed due to msys2 not downloadable

### ISSUE THREAD

**Issue by PhilLab** [microsoft/vcpkg#6660]
```
PS D:\DEVELOPMENT\vcpkg> .\vcpkg.exe install icu:x64-windows
The following packages will be built and installed:
    icu[core]:x64-windows
Starting package 1/1: icu:x64-windows
Building package icu[core]:x64-windows...
-- Using cached D:/DEVELOPMENT/vcpkg/downloads/icu4c-61_1-src.tgz
-- Applying patch D:/DEVELOPMENT/vcpkg/ports/icu/disable-escapestr-tool.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/DEVELOPMENT/vcpkg/ports/icu/remove-MD-from-configure.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Acquiring MSYS2...
-- Downloading http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20181211.tar.xz...
-- Downloading http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20181211.tar.xz... Failed. Status: 6;"Couldn't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:172 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:76 (vcpkg_download_distfile)
  ports/icu/portfile.cmake:75 (vcpkg_acquire_msys)
  scripts/ports.cmake:71 (include)


Error: Building package icu:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x64-windows
  Vcpkg version: 2018.11.23-nohash
```

**Comment by JackBoosY** [comment]
Hi @PhilLab, can you open this [page](http://repo.msys2.org/distrib/x86_64)? I still cannot reproduce this issue. And it seems you need a proxy to solve this problem.

BTW:
```
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
```

**Comment by PhilLab** [comment]
@JackBoosY thanks for the reply. No, I cannot open the page and I never used proxies on this machine - would be the first site to require them.

https://downforeveryoneorjustme.com/msys2.org Also reports the site being down, so maybe it is a regional problem (I am located in Germany)?

**Comment by PhilLab** [comment]
I just now used the following workaround, inspired by [#5727](https://github.com/microsoft/vcpkg/issues/5727#issuecomment-483554157) is:

1. Use a mirror like http://mirrors.ustc.edu.cn/msys2/distrib/x86_64/msys2-base-x86_64-20181211.tar.xz . This one is real slow but it is reachable. The file signatures are checked, aren't they?
2. Save it inside <path_to_vcpkg>/downloads/.
3. Run ./vcpkg install icu:x64-windows again

**Comment by JackBoosY** [comment]
Glad to hear that :)
We only need to make sure that the mirrored data is the same as the source data.

**Comment by PhilLab** [comment]
@JackBoosY Does vcpck check the signatures of all downloaded files? And it is not this one file only, a bunch of other files also fail to download afterwards. Installing package icu strangely succeeds anyways

**Comment by JackBoosY** [comment]
@PhilLab Yes, all downloaded files need to be checked by SHA512.
And I think there is a problem with your network.
