### ISSUE TITLE
[ImGui] ImGui is meant to be extended using the imgui_internal.h header, but this header is not public

### ISSUE THREAD

**Issue by ghassanpl** [microsoft/vcpkg#6665]
It would be great if this header was exposed in some way.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue, now `imgui_internal.h` will be installed by imgui, you can use it in your project.
![image](https://user-images.githubusercontent.com/94091114/177488469-3733511d-9381-4e1b-bd36-094e78cfbf5e.png)
