### ISSUE TITLE
Document Required Dependencies to Build

### ISSUE THREAD

**Issue by Silvenga** [microsoft/vcpkg#6666]
We spent way to log tracking down this when building new CI images. When installing only the `Microsoft.VisualStudio.Workload.NativeDesktop` workloads (Desktop development with C++) using the command line, by default optional/recommended packages are not installed (e.g. when installing for CI). If you attempt to run the bootstrapper, the following is given:

```
Building vcpkg.exe ...

  TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(320,5): error MSB6006: "CL.exe" exited with code 5. [C:\__w\2\s\profiler\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
C:\__w\2\s\profiler\vcpkg\scripts\bootstrap.ps1 : Building vcpkg.exe failed. 
Please ensure you have installed Visual Studio with the Desktop C++ workload 
and the Windows SDK for Desktop C++.
```

This may be caused by the bootstrap script selecting the build version based on the install VS version. For example, when VS2019 is installed, the script selects VC 142. This may not be the case e.g. VS2019 is installed, but is using VC 141.

I think the docs should be updated to specify that the `Microsoft.VisualStudio.Component.VC.Tools.x86.x64` (MSVC v142 - VS 2019 C++ x64/x86 build tools (v14.21)) component must be installed along with Desktop development with C++.

**Comment by PhoebeHui** [comment]
@Silvenga, thank you for posting this issue!

It mentioned in https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md#VCPKG_VISUAL_STUDIO_PATH. 

VCPKG_PLATFORM_TOOLSET
Specifies the VS-based C/C++ compiler toolchain to use.

See VCPKG_VISUAL_STUDIO_PATH for the full selection algorithm.

Valid settings:
The Visual Studio 2019 platform toolset is v142.
The Visual Studio 2017 platform toolset is v141.
The Visual Studio 2015 platform toolset is v140.
