### ISSUE TITLE
depend-info does not handle features

### ISSUE THREAD

**Issue by cwfitzgerald** [microsoft/vcpkg#6668]
I have a tool that, among other things, parses down the output of vcpkg to determine if any packages are installed that don't need to be. I call `list` to get the list of all packages installed. This includes features. When I call depend-info, the command cannot handle features at all. Because of this there are a lot of packages that the installed features depend on that are marked as unneeded.

For example I have a package `foo` that I want to keep installed. `foo[core]` has no dependencies. `foo[bar]` depends on `baz`. `foo[core,bar]` is currently installed. From `list` I will know that `foo[core,bar], baz` is what is currently installed. However from `depend-info` I will have to ask for the dependencies of `foo`, not `foo[core,bar]`. This will give me an empty list of dependencies. I then assume `baz` is a package that isn't needed and go to remove it. This is obviously in error as `foo[baz]` is installed and depends on it. As far as I can tell, the only way to get around this issue is to parse down the CONTROL files manually, which is what I'll end up doing.

**Comment by NancyLi1013** [comment]
Hi @cwfitzgerald, thanks for posting this feature. Now this feature has been implemented. Please try to update vcpkg to the latest version and try to use it.
