### ISSUE TITLE
Post-build validation for sqlite3:x86-windows-static fails

### ISSUE THREAD

**Issue by o-mdr** [Microsoft/vcpkg#667]
Steps to reproduce

```
 .\vcpkg install sqlite3:x86-windows-static
```

SQLite3 portfile configuration is incorrect for `x86-windows-static`

> C:\git\vcpkg\downloads\cmake-3.5.2-win32-x86.zip
> C:\git\vcpkg\downloads
> -- CURRENT_INSTALLED_DIR=C:/git/vcpkg/installed/x86-windows-static
> -- DOWNLOADS=C:/git/vcpkg/downloads
> -- CURRENT_PACKAGES_DIR=C:/git/vcpkg/packages/sqlite3_x86-windows-static
> -- CURRENT_BUILDTREES_DIR=C:/git/vcpkg/buildtrees/sqlite3
> -- CURRENT_PORT_DIR=C:/git/vcpkg/ports/sqlite3/.
> -- Downloading http://www.sqlite.org/2016/sqlite-amalgamation-3120200.zip...
> -- Downloading http://www.sqlite.org/2016/sqlite-amalgamation-3120200.zip... OK
> -- Testing integrity of downloaded file...
> -- Testing integrity of downloaded file... OK
> -- Extracting source C:/git/vcpkg/downloads/sqlite-amalgamation-3120200.zip
> -- Extracting done
> -- Configuring x86-windows-static-rel
> -- Configuring x86-windows-static-rel done
> -- Configuring x86-windows-static-dbg
> -- Configuring x86-windows-static-dbg done
> -- Package x86-windows-static-rel
> -- Package x86-windows-static-rel done
> -- Package x86-windows-static-dbg
> -- Package x86-windows-static-dbg done
> -- Performing post-build validation
> DLLs should not be present in a static build, but the following DLLs were found:
> 
>     C:/git/vcpkg/packages/sqlite3_x86-windows-static/bin/sqlite3.dll
>     C:/git/vcpkg/packages/sqlite3_x86-windows-static/debug/bin/sqlite3.dll
> 
> Found 1 error(s). Please correct the portfile:
>     C:\git\vcpkg\ports\sqlite3\portfile.cmake
> PS C:\git\vcpkg>

**Comment by sdcb** [comment]
@o-mdr you should upgrade vcpkg to latest version. Currently sqlite3 version is 3.15.

**Comment by o-mdr** [comment]
@sdcb done. It's still there.

```
 C:\git\vcpkg> powershell -exec bypass scripts\bootstrap.ps1
PS C:\git\vcpkg> .\vcpkg version
Vcpkg package management program version 0.0.71-d9462fdf490d3396cac58b1a935b1b8a982b3a72
PS C:\git\vcpkg> .\vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
PS C:\git\vcpkg> git pull
Already up-to-date.
```

and then

```
PS C:\git\vcpkg> .\vcpkg install sqlite3:x86-windows-static
```
> CMake Error: Could not find CMAKE_ROOT !!!
> CMake has most likely not been installed correctly.
> Modules directory not found in
> C:/git/vcpkg/downloads/cmake-3.7.2-win32-x86/share/cmake-3.7
> -- CURRENT_INSTALLED_DIR=C:/git/vcpkg/installed/x86-windows-static
> -- DOWNLOADS=C:/git/vcpkg/downloads
> -- CURRENT_PACKAGES_DIR=C:/git/vcpkg/packages/sqlite3_x86-windows-static
> -- CURRENT_BUILDTREES_DIR=C:/git/vcpkg/buildtrees/sqlite3
> -- CURRENT_PORT_DIR=C:/git/vcpkg/ports/sqlite3/.
> -- Using cached C:/git/vcpkg/downloads/sqlite-amalgamation-3150000.zip
> -- Testing integrity of cached file...
> -- Testing integrity of cached file... OK
> -- Extracting done
> -- Configuring x86-windows-static-rel
> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
>     Command failed: C:/git/vcpkg/downloads/cmake-3.7.2-win32-x86/bin/cmake.exe;C:/git/vcp
> INDOWS /W3 /utf-8 /GR /EHsc /MP;-DCMAKE_C_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /MP;-DCMAK
> O2 /Oi /Gy /DNDEBUG /Zi;-DCMAKE_C_FLAGS_RELEASE=/MT /O2 /Oi /Gy /DNDEBUG /Zi;-DCMAKE_SHAR
> KEFILE=ON;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_TOOLCHAIN_FILE=C:/git/vcpkg/triplets/x86-win
>     Working Directory: C:/git/vcpkg/buildtrees/sqlite3/x86-windows-static-rel
>     See logs for more information:
>       C:\git\vcpkg\buildtrees\sqlite3\config-x86-windows-static-rel-out.log
>       C:\git\vcpkg\buildtrees\sqlite3\config-x86-windows-static-rel-err.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_configure_cmake.cmake:89 (vcpkg_execute_required_process)
>   ports/sqlite3/portfile.cmake:12 (vcpkg_configure_cmake)
>   scripts/ports.cmake:73 (include)
> 
> 
> Error: building package sqlite3:x86-windows-static failed
> Please ensure sure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: sqlite3:x86-windows-static
>   Vcpkg version: 0.0.71-d9462fdf490d3396cac58b1a935b1b8a982b3a72
> 
> Additionally, attach any relevant sections from the log files above.

**Comment by sdcb** [comment]
> CMake Error: Could not find CMAKE_ROOT !!!
> CMake has most likely not been installed correctly.
> Modules directory not found in
I think this is your issue here.

**Comment by o-mdr** [comment]
Thanks @sdcb. Indeed - that was the problem.
