### ISSUE TITLE
Define cmake variables not set in script mode while reading portfiles

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#6677]
The following variables are required so that find_library might be used in portfiles for ports not using CMake but requiring paths to dependent libraries.  
```
if(WIN32)
    set(CMAKE_FIND_LIBRARY_PREFIXES "")
    set(CMAKE_FIND_LIBRARY_SUFFIXES ".lib")
elseif(VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(CMAKE_FIND_LIBRARY_PREFIXES "lib")
    set(CMAKE_FIND_LIBRARY_SUFFIXES ".so;.a")
elseif(VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    set(CMAKE_FIND_LIBRARY_PREFIXES "lib")
    set(CMAKE_FIND_LIBRARY_SUFFIXES ".dylib;.so;.a")
endif()
```
(Might be an incomplete list)

**Comment by Voskrese** [comment]
Linux separator `;` <- No errors with this?

.. `SUFFIXES .so .a)` it also works

Windows DDL ? `SUFFIXES .lib .dll)`
PREFIXES "") ?

**Comment by Neumann-A** [comment]
> Linux separator ; <- No errors with this?

That is a cmake list seperator: `SUFFIXES .so .a` is the same as  `SUFFIXES ".so;.a"` 
The defaults were taken from [here](https://stackoverflow.com/questions/28194215/default-values-for-cmake-find-library-prefixes-cmake-find-library-suffixes/28253243)

>PREFIXES "") ?

Just means an empty list. I wanted to be verbose here

**Comment by Voskrese** [comment]
why I ask about UNIX and seperator `;` in UNIX seperator default `:`

> PREFIXES "") ?

why empty? that's the question, because it means not to look in other folders
`...PREFIXES bin lib)`

example
linux
`PREFIXES lib64 lib32)`

**Comment by Neumann-A** [comment]
> why I ask about UNIX and seperator ; in UNIX seperator default :

We are not in UNIX syntax but in CMAKE syntax
https://cmake.org/cmake/help/v3.14/manual/cmake-language.7.html#lists

> why empty? that's the question, because it means not to look in other folders

That is not a folder prefix but a "names" prefix
https://cmake.org/cmake/help/v3.14/variable/CMAKE_FIND_LIBRARY_PREFIXES.html
