### ISSUE TITLE
Add Irrlicht

### ISSUE THREAD

**Issue by traversaro** [Microsoft/vcpkg#668]
It would be great to have a port of the Irrlicht library ( http://irrlicht.sourceforge.net/ ).

Debian package : https://packages.debian.org/source/sid/libs/irrlicht .
Homebrew formula : https://github.com/Homebrew/homebrew-core/blob/e5c28bbc0b70a9bc988fcc04565626493e2a14d5/Formula/irrlicht.rb .

**Comment by NancyLi1013** [comment]
@traversaro , thank you for posting this issue and the PR.
