### ISSUE TITLE
freeimage x86-windows-static | x64-windows-static

### ISSUE THREAD

**Issue by gdiObjects** [microsoft/vcpkg#6686]
when I include calls to freeimage (from within a class library function) such as:
FREE_IMAGE_FORMAT imgType = :FreeImage_GetFileTypeU(lpszFileName);

the vc linker links my project as a static library:
Creating library D:\Development\Projects\fotoXplorer\Release\fotoXplorer.lib and object D:\Development\Projects\fotoXplorer\Release\fotoXplorer.exp

when I comment out any FreeImage_XXXX calls..all is OK.

**Comment by JackBoosY** [comment]
Sorry, I don't know what you are talking about. I suggest:
1. Use Visual Stduio project(vcxproj)  and build your project as a static library?
2. Use CMake project and build your project as a static library?

For <1>, what the project generates depends on which one you selected in the _project-properties-General-Configuration_ Type.
For <2>. what is generated by the project depends on the "**shared**" or "**static**" set in **add_library**.

**Comment by gdiObjects** [comment]
Hello,
I've created a sample dialog box based app (solution) using MFC which shows the linking problem.  

Instructions:
	1.  Build (release, x86) and run this simple dialog program.
	2.  Uncomment the 'FreeImage Library' code in function CMainDialog::SampleFunction()
	3.  Build and (try) to run again.
Notice VC tries to create a library, and not an executable.

I've also noticed that when building the x64 versions (release|debug), VC can't locate "FreeImage.h" even though I installed it (.\vcpkg install freeimage:x64-windows-static).  I would suggest a batch-build x64 | x86 (debug and release).

The sample is built using Visual Studio 2017 Community Edition
[FreeImageSample.zip](https://github.com/microsoft/vcpkg/files/3239555/FreeImageSample.zip)

**Comment by JackBoosY** [comment]
When I leave these comments and build, shows:
>1>------ Build started: Project: FreeImageSample, Configuration: Release Win32 ------
1>MainDialog.cpp
1>Generating code
1>0 of 233 functions ( 0.0%) were compiled, the rest were copied from previous compilation.
1>  0 functions were new in current compilation
1>  2 functions had inline decision re-evaluated but remain unchanged
1>Finished generating code
1>FreeImageSample.vcxproj -> F:\FreeImageSample\Release\FreeImageSample.exe
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========


And remove these comments and rebuild, shows:
> 1>------ Build started: Project: FreeImageSample, Configuration: Release Win32 ------
1>stdafx.cpp
1>FreeImageSample.cpp
1>MainDialog.cpp
1>   Creating library F:\FreeImageSample\Release\FreeImageSample.lib and object F:\FreeImageSample\Release\FreeImageSample.exp
1>Generating code
1>All 233 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
1>Finished generating code
1>Half-2_3_s.lib(half.cpp.obj) : error LNK2005: "private: static short __cdecl half::convert(int)" (?convert@half@@CAFH@Z) already defined in Half-2_3.lib(Half-2_3.dll)
1>F:\FreeImageSample\Release\FreeImageSample.exe : fatal error LNK1169: one or more multiply defined symbols found
1>Done building project "FreeImageSample.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by gdiObjects** [comment]
I added it to the .vcxproj file (as VCPKG does when integrated, which it is as my other projects use Exiv2)

Here are the results.  Although, I think you are missing my point so I will hilite it in bold.

**Uncommented**
------ Rebuild All started: Project: FreeImageSample, Configuration: Release Win32 ------
stdafx.cpp
FreeImageSample.cpp
MainDialog.cpp
   **Creating library D:\Development\Side Projects\FreeImageSample\Release\FreeImageSample.lib and object D:\Development\Side Projects\FreeImageSample\Release\FreeImageSample.exp**
Generating code
All 233 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
Finished generating code
Half-2_3_s.lib(half.cpp.obj) : error LNK2005: "private: static short __cdecl half::convert(int)" (?convert@half@@CAFH@Z) already defined in Half-2_3.lib(Half-2_3.dll)
D:\Development\Side Projects\FreeImageSample\Release\FreeImageSample.exe : fatal error LNK1169: one or more multiply defined symbols found
Done building project "FreeImageSample.vcxproj" -- FAILED.
------ Rebuild All started: Project: FreeImageSample, Configuration: Debug Win32 ------
stdafx.cpp
FreeImageSample.cpp
MainDialog.cpp
Generating Code...
Half-2_3_s_d.lib(half.cpp.obj) : error LNK2005: "private: static short __cdecl half::convert(int)" (?convert@half@@CAFH@Z) already defined in Half-2_3_d.lib(Half-2_3_d.dll)
   **Creating library D:\Development\Side Projects\FreeImageSample\Debug\FreeImageSample.lib and object D:\Development\Side Projects\FreeImageSample\Debug\FreeImageSample.exp**
D:\Development\Side Projects\FreeImageSample\Debug\FreeImageSample.exe : fatal error LNK1169: one or more multiply defined symbols found
Done building project "FreeImageSample.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 2 failed, 0 skipped ==========

When the code in SampleFunction() is commented out it builds FreeImageSample.exe (as it should).

**Commented**
------ Rebuild All started: Project: FreeImageSample, Configuration: Release Win32 ------
stdafx.cpp
FreeImageSample.cpp
MainDialog.cpp
Generating code
All 233 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
Finished generating code
**FreeImageSample.vcxproj -> D:\Development\Side Projects\FreeImageSample\Release\FreeImageSample.exe**
------ Rebuild All started: Project: FreeImageSample, Configuration: Debug Win32 ------
stdafx.cpp
FreeImageSample.cpp
MainDialog.cpp
Generating Code...
**FreeImageSample.vcxproj -> D:\Development\Side Projects\FreeImageSample\Debug\FreeImageSample.exe**
========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========

Notice how in the second rebuild all (commented) there's no output entry for **Creating library D:\Development\Side Projects\FreeImageSample\Release\FreeImageSample.lib and object D:\Development\Side Projects\FreeImageSample\Release\FreeImageSample.exp**.

There's nothing in the source | solution | project files that would trigger vc thinking its building a library, and not an executable.

**Comment by Soyal7** [comment]
I'm trying to use static OIIO library and I get the same following error:

> 1>Half-2_3_s.lib(half.cpp.obj) : error LNK2005: "class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl operator<<(class std::basic_ostream<char,struct std::char_traits<char> > &,class half)" (??6@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@AEAV01@Vhalf@@@Z) already defined in Half-2_3.lib(Half-2_3.dll)
> 1>Half-2_3_s.lib(half.cpp.obj) : error LNK2005: "private: static short __cdecl half::convert(int)" (?convert@half@@CAFH@Z) already defined in Half-2_3.lib(Half-2_3.dll)

Did you come up with an idea how to solve this?

**Comment by gdiObjects** [comment]
Hello,
No solution.  I tried to explain that the created libraries were changing the output of the target that is linking to them.  I even supplied a sample.

**Comment by Rastaban** [comment]
Offline quote from @ras0219-msft 

> I think the problem is that whoever produces half-2_3 is shipping both static and dynamic libs (half-2_3-s)

**Comment by JackBoosY** [comment]
Please reopen this issue if it still bother you.

Thanks.
