### ISSUE TITLE
MSYS based builds hang PowerShell

### ISSUE THREAD

**Issue by emptyVoid** [microsoft/vcpkg#6688]
When installing ```msys```-based packages via a ```PowerShell``` script there's a high probability the script will hang until ```gpg-agent.exe``` is terminated (e.g. via ```Task Manager```).

I've experienced this behavior with ```ffmpeg``` and ```x264```, possibly ```libvpx``` and ```nmap``` suffer from it too.

Adding the following lines to ```ffmpeg``` and ```x264``` port files resolves the issue:
https://github.com/microsoft/vcpkg/blob/58c7cfaae9ed50876843a795d7badb3b384f24b6/ports/icu/portfile.cmake#L213-L219

Though I think it would be better to somehow resolve this in ```vcpkg_acquire_msys```.

**Comment by cenit** [comment]
in #6407 it was solved inside the PR itself. Of course it was not just related to that port, so it's better to propagate it to every msys port.
How would you do it inside `vcpkg_acquire_msys`? It looks like a cleaner approach but I'd not have any idea on the implementation... I think it's better if you just open a PR with those lines inside all the other 4 msys ports...

**Comment by emptyVoid** [comment]
Here's what I've just tried.
1. I added the lines from ```icu``` port right to the end of ```vcpkg_acquire_msys``` function:
```patch
diff --git a/scripts/cmake/vcpkg_acquire_msys.cmake b/scripts/cmake/vcpkg_acquire_msys.cmake
index adbd58ca..df53d2d5 100644
--- a/scripts/cmake/vcpkg_acquire_msys.cmake
+++ b/scripts/cmake/vcpkg_acquire_msys.cmake
@@ -113,5 +113,13 @@ function(vcpkg_acquire_msys PATH_TO_ROOT_OUT)
     message(STATUS "Acquiring MSYS Packages... OK")
   endif()

+  # Deal with a stale process created by MSYS
+  if (NOT VCPKG_CMAKE_SYSTEM_NAME OR VCPKG_CMAKE_SYSTEM_NAME STREQUAL "WindowsStore")
+      vcpkg_execute_required_process(
+          COMMAND TASKKILL /F /IM gpg-agent.exe /fi "memusage gt 2"
+          WORKING_DIRECTORY ${SOURCE_PATH}
+      )
+  endif()
+
   set(${PATH_TO_ROOT_OUT} ${PATH_TO_ROOT} PARENT_SCOPE)
 endfunction()
```
2. Removed them from ```icu``` portfile:
```patch
diff --git a/ports/icu/portfile.cmake b/ports/icu/portfile.cmake
index 91cba5db..e395a40c 100644
--- a/ports/icu/portfile.cmake
+++ b/ports/icu/portfile.cmake
@@ -211,9 +211,9 @@ file(COPY ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/icu)
 file(RENAME ${CURRENT_PACKAGES_DIR}/share/icu/LICENSE ${CURRENT_PACKAGES_DIR}/share/icu/copyright)

 # Deal with a stale process created by MSYS
-if (NOT VCPKG_CMAKE_SYSTEM_NAME OR VCPKG_CMAKE_SYSTEM_NAME STREQUAL "WindowsStore")
-    vcpkg_execute_required_process(
-        COMMAND TASKKILL /F /IM gpg-agent.exe /fi "memusage gt 2"
-        WORKING_DIRECTORY ${SOURCE_PATH}
-    )
-endif()
+#if (NOT VCPKG_CMAKE_SYSTEM_NAME OR VCPKG_CMAKE_SYSTEM_NAME STREQUAL "WindowsStore")
+#    vcpkg_execute_required_process(
+#        COMMAND TASKKILL /F /IM gpg-agent.exe /fi "memusage gt 2"
+#        WORKING_DIRECTORY ${SOURCE_PATH}
+#    )
+#endif()
```
3. And built 4 ```msys```-based ports with ```& .\vcpkg.exe install ffmpeg icu libvpx x264``` from a ```PowerShell``` script.

The 4 ports have installed successfully -- no build errors, no stale ```gpg-agent``` process, no script hanging.

PS: ```nmap``` doesn't want to build, though I think it's related to #6581.

**Comment by cenit** [comment]
So it is not respawned. I was fearing that, and so my uncertainty about not doing it at the end

**Comment by emptyVoid** [comment]
After some testing I'd say ```gpg-agent``` gets spawned on initial ```msys``` setup only, when a bunch of ```gpg``` related messages appear in the console. Subsequent ```vcpkg_acquire_msys``` calls from other ports briefly spawn ```gpg```, whereas ```gpg-agent``` does not get respawned even when additional ```msys``` packages are being installed.
