### ISSUE TITLE
MSMPI x64 fails to build

### ISSUE THREAD

**Issue by cjvaijo** [Microsoft/vcpkg#669]
Most likely linked to: #650 

Adding the MSMPI:x64-windows fails to build on Windows 64-bit. I have installed the MSMpiSetup8-0.exe redistributable as instructed, however this installed (by default) in C:\Program Files\Microsoft MPI on 64-windows. The cmake scripts for the package MSMPI seems to be looking in C:\Program Files (x86) for the mpiexec.exe file, which it does not find there. For reference, the environment variable PROGRAMFILES, as used by the cmake script, is set to the following on my system:
C:\Program Files\Microsoft MPI\Bin>echo %PROGRAMFILES%
C:\Program Files

Error output from vcpkg:

D:\WorkingFolder\git\vcpkg>vcpkg install msmpi:x64-windows
-- CURRENT_INSTALLED_DIR=D:/WorkingFolder/git/vcpkg/installed/x64-windows
-- DOWNLOADS=D:/WorkingFolder/git/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/WorkingFolder/git/vcpkg/packages/msmpi_x64-windows
-- CURRENT_BUILDTREES_DIR=D:/WorkingFolder/git/vcpkg/buildtrees/msmpi
-- CURRENT_PORT_DIR=D:/WorkingFolder/git/vcpkg/ports/msmpi/.
-- Using cached D:/WorkingFolder/git/vcpkg/downloads/msmpisdk-8.0.msi
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Using cached D:/WorkingFolder/git/vcpkg/downloads/MSMpiSetup-8.0.exe
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
CMake Error at ports/msmpi/portfile.cmake:44 (message):
    Could not find:
      C:\Program Files (x86)/Microsoft MPI/Bin/mpiexec.exe
    Please install the MSMPI redistributable package before trying to install this port.
    The appropriate installer has been downloaded to:
      D:/WorkingFolder/git/vcpkg/downloads/MSMpiSetup-8.0.exe

Call Stack (most recent call first):
  scripts/ports.cmake:73 (include)

Error: building package msmpi:x64-windows failed
Please ensure sure you're using the latest portfiles with `vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: msmpi:x64-windows
  Vcpkg version: 0.0.71-f22750084899e158446fc0968da22f0f8492186d

**Comment by alexkaratarakis** [comment]
The issue here is that CMake is 32-bit, so it gets C:\Program Files (x86)\ as an answer to %PROGRAMFILES%.
I am guessing you don't have CMake installed, so `vcpkg` auto-downloaded a portable version of CMake, which is 32-bit. A workaround would be to install the 64-bit version of cmake in your system and delete the portable CMake from the `downloads\` folder. 

I am investigating ways to get Program Files in a way that is unaffected by process bitness.

**Comment by alexkaratarakis** [comment]
I have fixed the issue. Please do a `git pull` and try building again.
Let me know of the outcome!

**Comment by cjvaijo** [comment]
Works great now, thanks for fixing the issue so quickly!
