### ISSUE TITLE
sol2: namespaced target causes include directory to not be set

### ISSUE THREAD

**Issue by Laoo4** [microsoft/vcpkg#6693]
Installed `sol2:x64-linux` through vcpkg. The target creation in `installed/x64-linux/share/sol2-targets.cmake` looks like this:
```
# Create imported target sol2
add_library(sol2::sol2 INTERFACE IMPORTED)

set_target_properties(sol2::sol2 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)
```

The issue arises when `sol2-config.cmake` checks whether the `sol2` target exists:
```
include("${CMAKE_CURRENT_LIST_DIR}/sol2-targets.cmake")

MESSAGE(STATUS ${CMAKE_CURRENT_LIST_DIR})

if (TARGET sol2)
    get_target_property(SOL2_INCLUDE_DIRS
        sol2 INTERFACE_INCLUDE_DIRECTORIES)
    set_and_check(SOL2_INCLUDE_DIRS "${SOL2_INCLUDE_DIRS}")
    set(SOL2_LIBRARIES sol2)
endif()
```

`sol2::sol2` does exist, but `sol2` _doesn't_. This causes `SOL2_INCLUDE_DIRS` to not be set, meaning it can't be used in `target_include_directories`.

My band-aid fix was to manually remove the namespace from `sol2-targets.cmake` like so:
```
add_library(sol2 INTERFACE IMPORTED)

set_target_properties(sol2 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)
```

**Comment by JackBoosY** [comment]
In sol2's CMakeLists.txt:
```
add_library(sol2 INTERFACE)
add_library(sol2::sol2 ALIAS sol2)
```

So, is _cmake/sol2-config.cmake.in_ incorrect?

**Comment by dantti** [comment]
I can confirm it is including wrong include paths.

**Comment by JackBoosY** [comment]
Hi @Laoo4, thanks for reporting this issue.
I've fixed this issue. Please update vcpkg and rebuild sol2.

Thanks.
