### ISSUE TITLE
Python2 and Python3 Should be Uninstallable on Non-Windows Platform

### ISSUE THREAD

**Issue by cwfitzgerald** [microsoft/vcpkg#6700]
Python2 and Python3 are both windows only currently. I think it should be opened up to all platforms at some point, but that's another issue. There should be a guard in the portfile to make sure it errors gracefully on mac and linux instead of erroring when trying to call msbuild.

**Comment by PhoebeHui** [comment]
I don't think it could be a problem now,  it support to build python3 on unix with commit https://github.com/microsoft/vcpkg/commit/fe3e544fa57c0dc37190a1e06353e1a4b15c9ecd#diff-1cc3d0044b3426b7a8f0db86989a3561, feel free to reopen if it still be a problem for you.
