### ISSUE TITLE
 Building package boost-build:x64-windows-static failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by hzxGoForward** [microsoft/vcpkg#6701]
# Environment

```none
Microsoft Windows [version: 10.0.17134.765]
terminal:windows Powershell
terminal:classic cmd line
```

# Steps to reproduce

I build the [bitoin](https://github.com/bitcoin/bitcoin/tree/master/build_msvc) source code, and execute the command:
.\vcpkg install --triplet x64-windows-static boost-filesystem boost-signals2 boost-test libevent openssl zeromq berkeleydb secp256k1 leveldb

then there are following errors:

Additional packages (*) will be modified to complete this operation.
Starting package 1/55: boost-build:x64-windows-static
Building package boost-build[core]:x64-windows-static...
-- Using cached C:/vcpkg-master/downloads/boostorg-build-boost-1.70.0.tar.gz
-- Using source at C:/vcpkg-master/buildtrees/boost-build/src/ost-1.70.0-ad28c1be18
-- Using cached C:/vcpkg-master/downloads/boost_LICENSE_1_0.txt
-- Using cached C:/vcpkg-master/downloads/boost-1.70.0-boostcpp.jam
-- Installing: C:/vcpkg-master/packages/boost-build_x64-windows-static/share/boost-build/copyright
-- Installing: C:/vcpkg-master/packages/boost-build_x64-windows-static/tools/boost-build/boostcpp.jam
-- Bootstrapping...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: C:/vcpkg-master/packages/boost-build_x64-windows-static/tools/boost-build/bootstrap.bat;msvc
    Working Directory: C:/vcpkg-master/packages/boost-build_x64-windows-static/tools/boost-build
    Error code: 2
    See logs for more information:
      C:\vcpkg-master\buildtrees\boost-build\bootstrap-x64-windows-static-out.log
      C:\vcpkg-master\buildtrees\boost-build\bootstrap-x64-windows-static-err.log

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:58 (vcpkg_execute_required_process)
  scripts/ports.cmake:71 (include)

**Error: Building package boost-build:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-build:x64-windows-static
  Vcpkg version: 2018.11.23-nohash**

Additionally, attach any relevant sections from the log files above.

so I opend the log file and there are following log file:
 the bootstrap-x64-windows-static-out.log

Bootstrapping the build engine

Failed to bootstrap the build engine
Please consult bootstrap.log for further diagnostics.

while the boots trap-x64-windows-static-err.log is says:

the Chinese words say there are internal compiling error in “C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe”.

Is there something wrong with my Visual studio 2015, or something wrong with vcpkg?

[bootstrap-x64-windows-static-err.log](https://github.com/microsoft/vcpkg/files/3239837/bootstrap-x64-windows-static-err.log)
[bootstrap-x64-windows-static-out.log](https://github.com/microsoft/vcpkg/files/3239838/bootstrap-x64-windows-static-out.log)

**Comment by PhoebeHui** [comment]
@hzxGoForward, thanks for posting this issue!

It looks a compiler bug and it fixed now, I installed it successfully with VS2017 15.9.7. Could you upgrade your toolset and try again?

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
