### ISSUE TITLE
vcpkg_from_git is inherently broken

### ISSUE THREAD

**Issue by invy** [microsoft/vcpkg#6707]
vcpkg_from_git and especially the compression in the 'git archive' step is broken / incompatible with test_hash, as gzip produces different results from the same .tar file not only on different platforms but also sometimes on the same system.
The 'closest' way to working around the problem is demonstrated here:
https://github.com/microsoft/vcpkg/blob/master/ports/fdlibm/portfile.cmake

But it will fail when the archive is cached in downloaded directory and you'll try to use the same vcpkg installation from the other platform. (ok this is maybe not intended use, but thinkable with WSL or just samba share)

Better way of archiving the git commit has to be introduced or the validation of the archived file has to be changed:
First option: If you stick to the workaround approach: when missmatch happens in cached archive, try to redownload it.
Second option: maybe just zcat | sha512sum - could work? But I'm not sure that there are any guarantees about the identity of two tar archives, as there could be the metadata, which could differ on different platforms.
Third option: since we are dealing with git and git already gives you the guarantee, I think it's too paranoidal from vcpkg to check the created archive against some hash sum, it's kinda makes not much sense anyway...

**Comment by invy** [comment]
The workaround is also not working as the 'hash' of the gzip changes everywhere...
So I think the best approach is to remove the hash check in case of git anyway.

**Comment by Rastaban** [comment]
I agree that relying on the guarantee of git is probably the best solution.  Would you be interested in making this change or should I assign it to one of the team members?

**Comment by invy** [comment]
@Rastaban I could but our company is not signing CLA. I'll be glad to provide my input.
For example, the question is still open on what to do with cached data, there is a hash check again.
I've just came up with replacing log level in message to WARNING and changed comment to indicate the possible point of failure.

**Comment by Rastaban** [comment]
If the portfile uses a label for the REF then it is possible for the upstream library to change the label.  Normally this would cause a build failure due to the hash change.  This is the desired behavior.  To get a similar behavior without the SHA512 parameter we would need to either require the git sha to be used as the REF, or have an additional parameter that requires the git sha when the REF is a label.  @ras0219-msft I am interested in hearing your thoughts on this.
