### ISSUE TITLE
unable to build opencv using vcpkg

### ISSUE THREAD

**Issue by NarendraKintali** [microsoft/vcpkg#6712]
This is the error, which I see on shell window.

CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:202

I faced the same issue installing x64. I updated my vcpkg and even ran "git pull"
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/3242163/config-x64-windows-out.log)

please help me in fixing the issue.

Thanks

**Comment by cenit** [comment]
There’s no problem in the config log you posted. Please give me all the details that you can provide.

**Comment by NarendraKintali** [comment]
Thank you @cenit issue got resolved, after running the same command for multiple times ..tesseract installed successfully.

**Comment by cenit** [comment]
It should happen at the first attempt but still better than a full failure. Please close the issue if it’s ok for you
