### ISSUE TITLE
VSINSTALLDIR failed v140

### ISSUE THREAD

**Issue by Voskrese** [microsoft/vcpkg#6713]
open CMD.exe
`echo %VCINSTALLDIR%`
%VCINSTALLDIR%
`echo %VSINSTALLDIR%`
%VSINSTALLDIR%

triplet  x64-windows.cmake
`set(VCPKG_PLATFORM_TOOLSET v140)`

`vcpkg env --triplet x64-windows`

`echo %VCINSTALLDIR%`
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\

`echo %VSINSTALLDIR%`
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\

**Comment by PhoebeHui** [comment]
@Voskrese, thanks for posting this issue!

I think %VSINSTALLDIR% expected to be C:\Program Files (x86)\Microsoft Visual Studio 14.0\ here.

Tried:
C:\Windows\system32>echo %VSINSTALLDIR%
%VSINSTALLDIR%

C:\Windows\system32>echo %VCINSTALLDIR%
%VCINSTALLDIR%

C:\Windows\system32>"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"

C:\Windows\system32>echo %VCINSTALLDIR%
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\

C:\Windows\system32>echo %VSINSTALLDIR%
C:\Program Files (x86)\Microsoft Visual Studio 14.0\

**Comment by Voskrese** [comment]
@PhoebeHui 
Yes, that's right, if you make a clean call to variables

`call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"`

```
echo %VCINSTALLDIR%
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
```

and through the environment **VCPKG** env, wrong, that wrote
```
echo %VSINSTALLDIR%
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\
```

VCPKG env --triplet ... 
cl /?
mt /?
more
