### ISSUE TITLE
Error: Building package nlopt:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Georgezhong1** [microsoft/vcpkg#6714]
Error: Building package nlopt:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
   Package: nlopt:x64-windows
   Vcpkg version: 2018.11.23-nohash

I cloned the latest version of vcpkg, but it still shows the error that I need to update vcpkg file. why it happens and how to solve it?

**Comment by JackBoosY** [comment]
Hi @Georgezhong1, please provide me the error logs.

Thanks.

**Comment by Georgezhong1** [comment]
I did not find error logs, but here are all the things that displayed
----------------------------------------------------------------------------------------------------------------

The following packages will be built and installed:
    nlopt[core]:x64-windows
Starting package 1/1: nlopt:x64-windows
Building package nlopt[core]:x64-windows...
-- Note: nlopt only supports static library linkage. Building static library.
-- Using cached D:/codes/Github/FicTrac/vcpkg/downloads/stevengj-nlopt-v2.6.1.tar.gz
-- Using source at D:/codes/Github/FicTrac/vcpkg/buildtrees/nlopt/src/v2.6.1-41e726ed12
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:202 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v
    Working Directory: D:/codes/Github/FicTrac/vcpkg/buildtrees/nlopt/x64-windows-dbg
    See logs for more information:
      D:\codes\Github\FicTrac\vcpkg\buildtrees\nlopt\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/nlopt/portfile.cmake:18 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package nlopt:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: nlopt:x64-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by PhoebeHui** [comment]
@Georgezhong1, thanks for posting this issue!

I installed nlopt:x64-windows successfully with latest vcpkg and VS2019 16.2 preview 2, do you add some custom setting?
Related issue https://github.com/microsoft/vcpkg/issues/3201.

PS F:\vcpkg> ./vcpkg install nlopt:x64-windows
The following packages will be built and installed:
    nlopt[core]:x64-windows
Starting package 1/1: nlopt:x64-windows
Building package nlopt[core]:x64-windows...
-- Note: nlopt only supports static library linkage. Building static library.
-- Downloading https://github.com/stevengj/nlopt/archive/v2.6.1.tar.gz...
-- Extracting source F:/vcpkg/downloads/stevengj-nlopt-v2.6.1.tar.gz
-- Using source at F:/vcpkg/buildtrees/nlopt/src/v2.6.1-41e726ed12
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: F:/vcpkg/packages/nlopt_x64-windows/share/nlopt/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package nlopt[core]:x64-windows... done
Installing package nlopt[core]:x64-windows...
Installing package nlopt[core]:x64-windows... done
Elapsed time for package nlopt:x64-windows: 2.363 min

Total elapsed time: 2.363 min

The package nlopt:x64-windows provides CMake targets:

    find_package(NLopt CONFIG REQUIRED)
    target_link_libraries(main PRIVATE NLopt::nlopt)

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
