### ISSUE TITLE
LibRaw: include(SelectLibraryConfigurations) missing from findlibraw_debug_fix.patch

### ISSUE THREAD

**Issue by mloskot** [microsoft/vcpkg#6715]
Original [FindLibRaw.cmake](https://github.com/LibRaw/LibRaw-cmake/blob/c8a802885e838381a7531ea0e555b9b42c8622e5/cmake/modules/FindLibRaw.cmake) from LibRaw-cmake project does not contain the line ` include(SelectLibraryConfigurations)`, but the current patch calls the macro:

https://github.com/microsoft/vcpkg/blob/b286cd50ddefb3d9457e261bf6518b1a46f4a830/ports/libraw/findlibraw_debug_fix.patch#L20-L22

----

The patch has been proposed to the upstram https://github.com/LibRaw/LibRaw-cmake/pull/7

/cc @trylle

**Comment by trylle** [comment]
Hi, @mloskot. Am preparing a PR to fix this.

From a cursory check, it looks like some files in unrelated ports arrow/findzstd.patch and unicorn-lib/CMakeLists.txt are also missing this include, @JackBoosY.

**Comment by mloskot** [comment]
@trylle I didn't check it all. I have got focused on preparing the patch for `FindLibRaw.cmake` to pushed it to the upstream. Once this succeeds, I was going to do the same with `lcms2_debug_fix.patch`. Then, move to reviewing the rest :)

**Comment by mloskot** [comment]
PR ref #6742

**Comment by ras0219-msft** [comment]
Should be fixed by #6742. Thanks!

**Comment by JackBoosY** [comment]
Hi @mloskot, please close this issue if it has been fixed.

Thanks.
