### ISSUE TITLE
Boost-thread: doesn't build in release-only

### ISSUE THREAD

**Issue by ThijsWithaar** [microsoft/vcpkg#6717]
On travis-ci, the following stanza fails if a release-only build is made.
The compiler version (8 or 9) does not make a difference.

    - os: osx
      osx_image: xcode10.2
      compiler: gcc
      env:
        - VCPKG_DIR=${TRAVIS_BUILD_DIR}/vcpkg
      install:
        - brew update && brew unlink gcc && brew install gcc@9 && export CC=gcc-9 CXX=g++-9
        - brew install ninja
        - git clone --depth 1 -b soxr https://github.com/ThijsWithaar/vcpkg.git ${VCPKG_DIR}
        # If this is uncommented, the build fails, otherwise it succeeds
        #- echo "set(VCPKG_BUILD_TYPE release)" >> ${VCPKG_DIR}/triplets/x64-osx.cmake
        - ${TRAVIS_BUILD_DIR}/vcpkg/vcpkg install boost-thread

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/8613
