### ISSUE TITLE
[CMake][assimp] target "assimp::assimp" not found

### ISSUE THREAD

**Issue by Rasphino** [microsoft/vcpkg#6719]
OS: Archlinux x86-64
I use assimp in my CMakeLists.txt as follow:
```
find_package(assimp REQUIRED)
......
message("assimp: ${ASSIMP_LIBRARIES}")
......
target_link_libraries(Ex0 PRIVATE assimp::assimp)
```

And CMake find assimp library successfully:
```
assimp: optimized;/home/rasp/git/vcpkg/installed/x64-linux/lib/libassimp.a;/home/rasp/git/vcpkg/installed/x64-linux/lib/libIrrXML.a;/home/rasp/git/vcpkg/installed/x64-linux/lib/libz.a;debug;/home/rasp/git/vcpkg/installed/x64-linux/lib/../debug/lib/libassimpd.a;/home/rasp/git/vcpkg/installed/x64-linux/lib/../debug/lib/libIrrXMLd.a;/home/rasp/git/vcpkg/installed/x64-linux/lib/../debug/lib/libz.a
```

But failed to find `assimp::assimp`:
```
CMake Error at /home/rasp/git/vcpkg/scripts/buildsystems/vcpkg.cmake:169 (_add_executable):
  Target "Ex0" links to target "assimp::assimp" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
```

Is it a bug? Or is there anything wrong with my CMakeLists.txt file?

Thanks in advance!

**Comment by Rasphino** [comment]
After this [pr](https://github.com/microsoft/vcpkg/pull/6593#issue-281914940), cmake works with `${ASSIMP_LIBRARIES}`, but still couldn't find `assimp::assimp`

**Comment by JackBoosY** [comment]
INSTALL(TARGET) command in source\code\CMakeLists.txt:
>INSTALL( TARGETS assimp
  LIBRARY DESTINATION ${ASSIMP_LIB_INSTALL_DIR}
  ARCHIVE DESTINATION ${ASSIMP_LIB_INSTALL_DIR}
  RUNTIME DESTINATION ${ASSIMP_BIN_INSTALL_DIR}
  FRAMEWORK DESTINATION ${ASSIMP_LIB_INSTALL_DIR}
  COMPONENT ${LIBASSIMP_COMPONENT})

This port does not declare any [EXPORT <export-name>], so we can't use it.

**Comment by Rasphino** [comment]
I find the usage of `assimp::assimp` in issue #3062, which says we should use assimp::assimp instead of ${ASSIMP_LIBRARIES}. 
Anyway, thanks for your time. I will close this issue, but I think it will be better to add a `usage` file to assimp, just like some other packages, e.g., [glew](https://github.com/microsoft/vcpkg/tree/master/ports/glew) does~
