### ISSUE TITLE
C++ / VSCode problem (The preLaunchTask)

### ISSUE THREAD

**Issue by AbuRajih** [microsoft/vcpkg#6721]
Hi guys I have problem with C++ in my VSCode it does not work with me

**My steps was** :
1. I Install MinGW with edit the path.
2. I downloaded C/C++ extension.
3. I created c_cpp_properties.json

**This is c_cpp_properties.json code:**

```
{
"configurations": [
{

"name": "Win32",
"includePath": [
"${workspaceFolder}",
"C:/MinGW/lib/gcc/mingw32/8.2.0/include/c++",
"C:/MinGW/include",
"C:/MinGW/bin",
"C:/MinGW/lib/gcc/mingw32/8.2.0/include/c++/mingw32",
"C:/MinGW/lib/gcc/mingw32/8.2.0/include/c++/backward",
"C:/MinGW/lib/gcc/mingw32/8.2.0/include",
"C:/MinGW/lib/gcc/mingw32/8.2.0/include-fixed",
"C:/MinGW/lib/gcc/mingw32/8.2.0/include/c++/tr1",
"C:/MinGW/mingw32/include"
],
"defines": [
"_DEBUG",
"UNICODE",
"_UNICODE"
],
"compilerPath": "C:\\\\MinGW\\\\bin\\\\gcc.exe",
"cStandard": "c11",
"cppStandard": "c++17",
"intelliSenseMode": "clang-x64",
"browse": {
"path": [
"${workspaceFolder}",
"C:/MinGW/lib/gcc/mingw32/8.2.0/include/c++",
"C:/MinGW/lib/gcc/mingw32/8.2.0/include",
"C:/MinGW/lib/gcc/mingw32/8.2.0/include-fixed",
"C:/MinGW/include/*",
"C:/MinGW/lib/gcc/mingw32/8.2.0/include/c++",
"C:/MinGW/lib/gcc/mingw32/8.2.0/include/c++/mingw32",
"C:/MinGW/lib/gcc/mingw32/8.2.0/include/c++/backward",
"C:/MinGW/include"
],
"limitSymbolsToIncludedHeaders": true,
"databaseFilename": ""
}
}
],
"version": 4
}
```

4. I created tasks.json

**This is tasks.json code:**

```
{
    "tasks": [
        {
            "type": "shell",
            "label": "build",
            "command": "g++",
            "args": [
                "-g", "${file}"
            ],
            "group" : {
               "kind": "build",
               "isDefault": true 
           }
        }
    ],
    "version": "2.0.0"
}
```

5. I created launch.json 

**This is launch.json code:**

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "build",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\MinGW\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "build"
        }
    ]
}
```

Before I start test the code I just check if g++ work or not ,
it is work there is no problem with it
### img: https://prnt.sc/nwbtow

But when I run the code it does not work it shows me error's

This is my simple C++ code

```
#include<iostream>
using namespace std;
int main(){
cout << "Hello World";
    return 0;
}

```

The error's
1. https://prnt.sc/nwc6zb
2. https://prnt.sc/nwc7dk
3. It does not create .exe file 

I need help please

**Comment by JackBoosY** [comment]
Vcpkg depends on Visual Studio, please make sure Visual Studio is installed. 
The problem is that you are missing the **wchar.h** file, however this file is provided by Visual Studio.

Thanks.

**Comment by grdowns** [comment]
Hey @AbuRajih, for questions regarding the C++ extension in VS Code in the future, please visit [Microsoft/cpptools](https://github.com/microsoft/vscode-cpptools).

However, I notice that your `"build"` preLaunchTask does not name the resulting executable. `g++` will default to naming the executable `a.out`. I also noticed that your debug configuration points to the executable `"${fileDirname}\\${fileBasenameNoExtension}.exe"`, which will resolve to the current file open. For example, the file `<some directory>\main.cpp` will resolve to `<some directory>\main.exe`.

To amend this problem, change the contents of your `tasks.json` file to the following:

```
{
    "tasks": [
        {
            "type": "shell",
            "label": "build",
            "command": "g++",
            "args": [
                "-g", "${file}", "-o", "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "group" : {
               "kind": "build",
               "isDefault": true 
           }
        }
    ],
    "version": "2.0.0"
}
```
Note the changes made to the `args` array. Here we are specifying `gcc`'s `-o` option to change the output executable name from `a.out` to `${fileBasenameNoExtension}.exe` (e.g. `main.cpp`). The `${fileDirname}\\` portion of the filename will ensure that the executable is placed in the directory that the debug configuration is looking for.

Thanks for raising the issue, I hope that this helps!
