### ISSUE TITLE
Integrating CUDA and cmake for install opencv cuda

### ISSUE THREAD

**Issue by godblezzme29** [microsoft/vcpkg#6728]
Hi guys, I tried to install opencv cuda using vcpkg, but it seems like the cmake can not found the version of my cuda. when I run this script :
./vcpkg install opencv[cuda] --recurse
it gives me this error : 
Starting package 2/3: cuda:x64-linux
Building package cuda[core]:x64-linux...
CMake Error at ports/cuda/portfile.cmake:26 (message):
  Could not find CUDA.  Before continuing, please download and install CUDA
  (V9.0.0 or higher) from:

      https://developer.nvidia.com/cuda-downloads

  

  Also ensure vcpkg has been rebuilt with the latest version (v0.0.104 or
  later)
Call Stack (most recent call first):
  scripts/ports.cmake:71 (include)

Error: Building package cuda:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cuda:x64-linux
  Vcpkg version: 2018.11.23-unknownhash

Additionally, attach any relevant sections from the log files above.

Based on this error, I think that the cmake can not detect my cuda. Is there anyone know how to integrating my cuda with the cmake so the cmake able to detect my cuda? Thank you very much

My environment : 
OS : Ubuntu 16.04
CUDA : 9

**Comment by cenit** [comment]
For #5169 I will surely do it
