### ISSUE TITLE
HDF5 port issue

### ISSUE THREAD

**Issue by cjvaijo** [Microsoft/vcpkg#673]
Trying to install the hdf5 (tested both x64-windows and x86-windows) port does not seem to work. There are issues trying to locate zlib and szip packages (even though they are installed). I'm trying to build on Windows 7 x64, en-US locale, using VS2015 Update 3.

Attached are the log files from buildtrees and my list of installed libraries.
[vcpkg_installed.txt](https://github.com/Microsoft/vcpkg/files/776980/vcpkg_installed.txt)
[config-x64-windows-rel-err.txt](https://github.com/Microsoft/vcpkg/files/776985/config-x64-windows-rel-err.txt)
[config-x64-windows-rel-out.txt](https://github.com/Microsoft/vcpkg/files/776986/config-x64-windows-rel-out.txt)
[config-x86-windows-rel-err.txt](https://github.com/Microsoft/vcpkg/files/776987/config-x86-windows-rel-err.txt)
[config-x86-windows-rel-out.txt](https://github.com/Microsoft/vcpkg/files/776988/config-x86-windows-rel-out.txt)

The output from vcpkg:
D:\WorkingFolder\git\vcpkg>vcpkg install hdf5:x64-windows
-- CURRENT_INSTALLED_DIR=D:/WorkingFolder/git/vcpkg/installed/x64-windows
-- DOWNLOADS=D:/WorkingFolder/git/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/WorkingFolder/git/vcpkg/packages/hdf5_x64-windows
-- CURRENT_BUILDTREES_DIR=D:/WorkingFolder/git/vcpkg/buildtrees/hdf5
-- CURRENT_PORT_DIR=D:/WorkingFolder/git/vcpkg/ports/hdf5/.
-- Using cached D:/WorkingFolder/git/vcpkg/downloads/hdf5-1.8.18.tar.bz2
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Configuring x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: D:/WorkingFolder/git/vcpkg/downloads/cmake-3.7.2-win32-x86/bin/cmake.exe;D:/
WorkingFolder/git/vcpkg/buildtrees/hdf5/src/hdf5-1.8.18;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP
=1;-DBUILD_TESTING=OFF;-DHDF5_BUILD_EXAMPLES=OFF;-DHDF5_BUILD_TOOLS=OFF;-DHDF5_BUILD_CPP_LIB=OFF
;-DHDF5_ENABLE_PARALLEL=ON;-DHDF5_ENABLE_Z_LIB_SUPPORT=ON;-DHDF5_ENABLE_SZIP_SUPPORT=ON;-DHDF5_E
NABLE_SZIP_ENCODING=ON;-DHDF5_INSTALL_DATA_DIR=share/hdf5/data;-DHDF5_INSTALL_CMAKE_DIR=share/hd
f5;-DBUILD_SHARED_LIBS=ON;-DCMAKE_CXX_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP;-DCMAKE
_C_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /MP;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_P
ACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DBoost_COMPILE
R=-vc140;-DCMAKE_CXX_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Zi;-DCMAKE_C_FLAGS_RELEASE=/MD /O2
/Oi /Gy /DNDEBUG /Zi;-DCMAKE_SHARED_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:IC
F;-DCMAKE_EXE_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF;-G;Ninja;-DCMAKE_VER
BOSE_MAKEFILE=ON;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_TOOLCHAIN_FILE=D:/WorkingFolder/git/vcpkg/tr
iplets/x64-windows.cmake;-DCMAKE_PREFIX_PATH=D:/WorkingFolder/git/vcpkg/installed/x64-windows;-D
CMAKE_INSTALL_PREFIX=D:/WorkingFolder/git/vcpkg/packages/hdf5_x64-windows
    Working Directory: D:/WorkingFolder/git/vcpkg/buildtrees/hdf5/x64-windows-rel
    See logs for more information:
      D:\WorkingFolder\git\vcpkg\buildtrees\hdf5\config-x64-windows-rel-out.log
      D:\WorkingFolder\git\vcpkg\buildtrees\hdf5\config-x64-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:95 (vcpkg_execute_required_process)
  ports/hdf5/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:73 (include)

Error: building package hdf5:x64-windows failed
Please ensure sure you're using the latest portfiles with `vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: hdf5:x64-windows
  Vcpkg version: 0.0.72-edec017ecec2e2a8ad57a0b5ee660b59a9479aac

Additionally, attach any relevant sections from the log files above.

**Comment by ras0219-msft** [comment]
Thanks for reporting this! I'm not sure what caused the regression, but HDF5 unfortunately was not looking for the correct library names on windows. It additionally discounted the CMake config file, because we only install one of `{static, dynamic}` and it requested both.

I fixed this by manually specifying the locations and names of the `szip` library files. This isn't ideal, but it works.

**Comment by cjvaijo** [comment]
Tested it now, and it works fine. Thanks!
