### ISSUE TITLE
How to install tesseract "eng" "traindata" using vcpkg ?

### ISSUE THREAD

**Issue by NarendraKintali** [microsoft/vcpkg#6731]
I installed tesseract successfully using vcpkg and integrated it. But when I runt tesseract based C++ program on Visual Studio 2017, I see the following error. Please help me in fixing this.

**Error opening data file C:\Users\kintali\source\repos\TesseractTest\x64\Debug\/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!** 

I even downloaded "eng.trainedata" and copied it into root folder mentioned in the error, but still no use.

**Comment by JackBoosY** [comment]
Tesseract doesn't have any features right now. 
We need to add these features.

**Comment by NarendraKintali** [comment]
How to add the features...?

**Comment by NarendraKintali** [comment]
I downloaded and copied "eng.traineddata" to tessdata folder, Now I dont have error. Is it the right way to do.

**Comment by Voskrese** [comment]
-DTESSDATA_PREFIX=///downloaded and copied "eng.traineddata" to "tessdata" folder////

**Comment by PhoebeHui** [comment]
@NarendraKintali, yes, see related issue https://github.com/tesseract-ocr/tesseract/issues/1309.

**Comment by NarendraKintali** [comment]
Thank you @PhoebeHui I solved the issue.
