### ISSUE TITLE
MPG123 x64 port issue

### ISSUE THREAD

**Issue by cjvaijo** [Microsoft/vcpkg#674]
Building the x86 version works fine, but the x64-windows version fails to build. The vc solution that is used does not contain a build target for x64. Opening the solution in VS(2015) and adding a x64 target, then building in VS works fine, but vcpkg does not perform this. Bulding on Windows 7 x64, en-US locale, VS2015 Update 3.

Log files attached.
[build-x64-windows-rel-out.txt](https://github.com/Microsoft/vcpkg/files/776997/build-x64-windows-rel-out.txt)

Output from vcpkg:
D:\WorkingFolder\git\vcpkg>vcpkg install mpg123:x64-windows
-- CURRENT_INSTALLED_DIR=D:/WorkingFolder/git/vcpkg/installed/x64-windows
-- DOWNLOADS=D:/WorkingFolder/git/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/WorkingFolder/git/vcpkg/packages/mpg123_x64-windows
-- CURRENT_BUILDTREES_DIR=D:/WorkingFolder/git/vcpkg/buildtrees/mpg123
-- CURRENT_PORT_DIR=D:/WorkingFolder/git/vcpkg/ports/mpg123/.
-- Using cached D:/WorkingFolder/git/vcpkg/downloads/mpg123-1.23.3.tar.bz2
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch D:/WorkingFolder/git/vcpkg/ports/mpg123/0001-Modify-2010-libmpg123.vcxproj-to-
use-VS-2015-along-w.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/WorkingFolder/git/vcpkg/ports/mpg123/0001-Modify-2010-libmpg123.vcxproj-to-
use-VS-2015-along-w.patch done
-- Building D:/WorkingFolder/git/vcpkg/buildtrees/mpg123/src/mpg123-1.23.3/ports/MSVC++/2010/lib
mpg123/libmpg123.vcxproj for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: msbuild;D:/WorkingFolder/git/vcpkg/buildtrees/mpg123/src/mpg123-1.23.3/ports
/MSVC++/2010/libmpg123/libmpg123.vcxproj;/p:Configuration=Release_x86_Dll;/p:Platform=x64;/p:VCP
kgLocalAppDataDisabled=true;/p:UseIntelMKL=No;/m
    Working Directory: D:/WorkingFolder/git/vcpkg/buildtrees/mpg123/x64-windows-rel
    See logs for more information:
      D:\WorkingFolder\git\vcpkg\buildtrees\mpg123\build-x64-windows-rel-out.log
      D:\WorkingFolder\git\vcpkg\buildtrees\mpg123\build-x64-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:53 (vcpkg_execute_required_process)
  ports/mpg123/portfile.cmake:23 (vcpkg_build_msbuild)
  scripts/ports.cmake:73 (include)

Error: building package mpg123:x64-windows failed
Please ensure sure you're using the latest portfiles with `vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: mpg123:x64-windows
  Vcpkg version: 0.0.72-edec017ecec2e2a8ad57a0b5ee660b59a9479aac

Additionally, attach any relevant sections from the log files above.

**Comment by ras0219-msft** [comment]
Were you able to successfully use the built DLLs after adding the configuration and building? In the vcxproj, it looks like there are a lot of lines in the PreLinkEvent like
```
cl /I "..\.." /EP /TC "$(ProjectDir)..\..\..\..\src\libmpg123\synth_stereo_sse_s32.S" /nologo &gt; "$(ProjectDir)..\libmpg123\Release\synth_stereo_sse_s32.asm"
yasm -a x86 -p gas -r raw -f win32 -g null -m x86 -o "$(ProjectDir)..\libmpg123\Release\synth_stereo_sse_s32.o" "$(ProjectDir)..\libmpg123\Release\synth_stereo_sse_s32.asm"
```
that _sound_ x86 specific.

**Comment by cjvaijo** [comment]
Did a test, and that seem to work. Compiled the lib itself and the example program feedseek and used it on a mp3. Dumping the headers of the dll and exe show x64 machine arch. It is true there is a lot of x86 seemingly spesific yasm in the vcxproj file... don't know if they are used at all...

D:\WorkingFolder\git\vcpkg\buildtrees\mpg123\src\mpg123-1.23.3\ports\MSVC++\2010
\libmpg123\Release>dumpbin /headers libmpg123.dll
Microsoft (R) COFF/PE Dumper Version 14.00.24215.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file libmpg123.dll

PE signature found

File Type: DLL

FILE HEADER VALUES
            8664 machine (x64)
               7 number of sections
        58ADA93F time date stamp Wed Feb 22 16:07:43 2017

-----------------------------------------------
D:\WorkingFolder\git\vcpkg\buildtrees\mpg123\src\mpg123-1.23.3\ports\MSVC++\2010
\libmpg123\Release>dumpbin /headers feedseek.exe
Microsoft (R) COFF/PE Dumper Version 14.00.24215.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file feedseek.exe

PE signature found

File Type: EXECUTABLE IMAGE

FILE HEADER VALUES
            8664 machine (x64)
               9 number of sections
        58ADAA28 time date stamp Wed Feb 22 16:11:36 2017
-------------------------------------------
D:\WorkingFolder\git\vcpkg\buildtrees\mpg123\src\mpg123-1.23.3\ports\MSVC++\2010
\libmpg123\Release>feedseek 02-morph-in.mp3 fs.mp3
Note: Disabling all formats.
Note: Want to enable format 8000/3 for encodings 0x200.
Note: Want to enable format 11025/3 for encodings 0x200.
Note: Want to enable format 12000/3 for encodings 0x200.
Note: Want to enable format 16000/3 for encodings 0x200.
Note: Want to enable format 22050/3 for encodings 0x200.
Note: Want to enable format 24000/3 for encodings 0x200.
....

**Comment by cjvaijo** [comment]
Supplementary, I find no evidence in the compile lot that any of the yasm (or assembly files) are actually used in any way, maybe they should, but the lib seems to work anyhow. Log attached.
[libmpg123.txt](https://github.com/Microsoft/vcpkg/files/793942/libmpg123.txt)

**Comment by Mixaill** [comment]
Please try to use port from #780

**Comment by cjvaijo** [comment]
This works fine now, thank you.
