### ISSUE TITLE
Library request: QuantLib

### ISSUE THREAD

**Issue by chrullrich** [microsoft/vcpkg#676]
https://quantlib.org/

I tried to create the port myself, but it is beyond me.

They have both CMake and MSBuild projects, but neither appears entirely usable:

- CMake
  - supports only DLL build (and see below), not static
  - has no option to turn off building the largish test suite
  - does not declare that it needs Boost.DateTime
  - has no installation support whatsoever, but that is probably better done in the port anyway

- MSBuild
  - supports only static build (one .lib, ~460 MiB for Release and ~1.2 GiB for Debug), not DLL
  - always does the same test suite as above

As for building dynamic, there is the additional problem that neither the word "dllexport" nor any .def file appears anywhere in the source tree. Consequently, the DLL that the CMake project produces has no exported symbols. Changing the .vcxproj to build a DLL leads to the same result. Applying the workaround from https://stackoverflow.com/questions/225432/#answer-32284832 produces an import library, but I have not yet tested if it works.

**Comment by codicodi** [comment]
You don't need complicated workarounds to export from dll - CMake has a nice built-in option for that: [WINDOWS_EXPORT_ALL_SYMBOLS](https://cmake.org/cmake/help/v3.4/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html).

**Comment by chrullrich** [comment]
Yes, that is what the SO link is about ...

**Comment by codicodi** [comment]
Ah, right. My mobile browser didn't center on a specific answer and I thought you're refering to the accepted one. 
Anyway, several ports use this approach and it works great as long as there are no global data symbols involved.
