### ISSUE TITLE
Missing buildsystem integration file applocal.py after using export on macOS

### ISSUE THREAD

**Issue by stfnp** [microsoft/vcpkg#6783]
When trying to use a subset of libraries that was exported via `vcpkg export` I got this error message:

    /usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/vsts/agent/2.150.3/work/1/s/build/vcpkg-export-x64-osx/scripts/buildsystems/osx/applocal.py': [Errno 2] No such file or directory

The missing file, `scripts/buildsystems/osx/applocal.py` was recently introduced in #5681. The error disappears when reverting to a previous commit. My guess would be that the export command hasn't been updated yet to include that file in its output. It seems to do so with the equivalent `applocal.ps1` on Windows.

**Comment by JackBoosY** [comment]
Hi @stfnp, does this issue still exist?

**Comment by stfnp** [comment]
Sorry, I haven't been using vcpkg lately so I don't know if this is still a problem.

**Comment by JackBoosY** [comment]
@stfnp Please reopen this issue if it still exists.
