### ISSUE TITLE
[fribidi] Meson produces libfribidi.a on `x64-windows-static`

### ISSUE THREAD

**Issue by vicroms** [microsoft/vcpkg#6789]
Output produced by Meson when installing `fribidi:x64-windows-static` is incorrect.

The following binaries are produced:
* `lib/libfribidi.a`
* `debug/lib/libfribidi.a`

Which are inconsistent with Windows binary naming conventions.

**Comment by Voskrese** [comment]
meson default static all extension .a

**Comment by lb90** [comment]
See here: https://mesonbuild.com/FAQ.html#why-does-building-my-project-with-msvc-output-static-libraries-called-libfooa

**Comment by Voskrese** [comment]
@lb90 How to prescribe this globally for the Win32 platform?
https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_configure_meson.cmake

**Comment by Voskrese** [comment]
extra cmake setting ))

```
    if(WIN32)
        set(CMAKE_EXTRA_LINK_EXTENSIONS ".lib" ".a")
        set(CMAKE_FIND_LIBRARY_PREFIXES "lib" "")
        set(EXECUTABLE_SUFFIX ".exe" )
        set(CMAKE_FIND_LIBRARY_SUFFIXES ".dll" ".dll.a" ".a" ".lib")
    endif()
```

**Comment by JackBoosY** [comment]
@vicroms  Maybe we need to change **vcpkg_configure_meason.cmake** / **vcpkg_install_meason.cmake** to set `name_suffix=lib` as the default option?

**Comment by JackBoosY** [comment]
Solved.
