### ISSUE TITLE
Error: Building package spdlog:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by jpo38** [microsoft/vcpkg#6794]
I'm getting the following error when running:
set VCPKG_DEFAULT_TRIPLET=x64-windows
set VCPKG_ROOT=C:\dev\vobs_nrf_driver\vcpkg-master
set PATH=%PATH%;%VCPKG_ROOT%
vcpkg install --head spdlog

> CMake Error at scripts/cmake/vcpkg_fixup_cmake_targets.cmake:42 (message):
> 
>   'C:/dev/vobs_nrf_driver/vcpkg-master/packages/spdlog_x64-windows/debug/lib/cmake/spdlog'
>   does not exist.
> Call Stack (most recent call first):
>   ports/spdlog/portfile.cmake:22 (vcpkg_fixup_cmake_targets)
>   scripts/ports.cmake:71 (include)
> 
> 
> Error: Building package spdlog:x64-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: spdlog:x64-windows
>   Vcpkg version: 2018.11.23-nohash
> 
> Additionally, attach any relevant sections from the log files above.

I ran vcpkg update and it reported:

> Using local portfile versions. To update the local portfiles, use `git pull`.
> No packages need updating.

**Comment by jpo38** [comment]
Just tested using master (I was using an earlier version) and I see the same problem.

**Comment by JackBoosY** [comment]
Hi @jpo38, when you install the port with the `--head` parameter, vcpkg will download and use the port's **latest** code to install, and the **default** port code used by vcpkg is **not** necessarily the latest port code.

I can't reproduce this issue on the latest version of vcpkg. Can you update vcpkg and rebuild spdlog:x64-windows?

Thanks.

**Comment by jpo38** [comment]
Hello,

Just downloaded vcpkg:
C:\dev\vcpkg-master>bootstrap-vcpkg.bat
C:\dev\vcpkg-master>set VCPKG_DEFAULT_TRIPLET=x64-windows

Still getting the error:

C:\dev\vcpkg-master>vcpkg install --head spdlog
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be built and installed:
  * fmt[core]:x64-windows
    spdlog[core]:x64-windows (from HEAD)
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: fmt:x64-windows
Building package fmt[core]:x64-windows...
A suitable version of cmake was not found (required v3.14.0). Downloading portable cmake v3.14.0...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.14.0/cmake-3.14.0-win32-x86.zip -> C:\dev\vcpkg-master\downloads\cmake-3.14.0-win32-x86.zip
Extracting cmake...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> C:\dev\vcpkg-master\downloads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
A suitable version of nuget was not found (required v4.6.2). Downloading portable nuget v4.6.2...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v4.6.2/nuget.exe -> C:\dev\vcpkg-master\downloads\nuget.exe
A suitable version of git was not found (required v2.21.0). Downloading portable git v2.21.0...
Downloading git...
  https://github.com/git-for-windows/git/releases/download/v2.21.0.windows.1/PortableGit-2.21.0-32-bit.7z.exe -> C:\dev\vcpkg-master\downloads\PortableGit-2.21.0-32-bit.7z.exe
Extracting git...
-- Downloading https://github.com/fmtlib/fmt/archive/5.3.0.tar.gz...
-- Extracting source C:/dev/vcpkg-master/downloads/fmtlib-fmt-5.3.0.tar.gz
-- Using source at C:/dev/vcpkg-master/buildtrees/fmt/src/5.3.0-9fc40447dd
-- Downloading https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip...
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: C:/dev/vcpkg-master/packages/fmt_x64-windows/share/fmt/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package fmt[core]:x64-windows... done
Installing package fmt[core]:x64-windows...
Installing package fmt[core]:x64-windows... done
Elapsed time for package fmt:x64-windows: 1.786 min
Starting package 2/2: spdlog:x64-windows
Building package spdlog[core]:x64-windows from HEAD...
-- Downloading https://api.github.com/repos/gabime/spdlog/git/refs/heads/v1.x...
-- Skipping hash check for C:/dev/vcpkg-master/downloads/temp/gabime-spdlog-v1.x.tar.gz.version.
-- Downloading https://github.com/gabime/spdlog/archive/v1.x.tar.gz...
-- Skipping hash check for C:/dev/vcpkg-master/downloads/temp/gabime-spdlog-v1.x.tar.gz.
-- Extracting source C:/dev/vcpkg-master/downloads/gabime-spdlog-v1.x.tar.gz
-- Applying patch disable-master-project-check.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Using source at C:/dev/vcpkg-master/buildtrees/spdlog/src/head/v1.x-bda0b893e5
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_fixup_cmake_targets.cmake:45 (message):
  'C:/dev/vcpkg-master/packages/spdlog_x64-windows/debug/lib/cmake/spdlog'
  does not exist.
Call Stack (most recent call first):
  ports/spdlog/portfile.cmake:22 (vcpkg_fixup_cmake_targets)
  scripts/ports.cmake:71 (include)


Error: Building package spdlog:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: spdlog:x64-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by JackBoosY** [comment]
@jpo38 Yeah, I know.
This is because the _*.cmake_ build path for the code downloaded via `--head` has changed, causing the build to fail. This is not a port bug, we can update this port if needed.
