### ISSUE TITLE
Error: Building package zlib:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Sarzn** [microsoft/vcpkg#6795]
Package: zlib:x86-windows
  Vcpkg version: 2018.11.23-nohash

**Comment by wangli28** [comment]
Hi @Sarzn, thanks for posting this issue. Can you provide the install log?

**Comment by PhoebeHui** [comment]
@Sarzn, please attach failure logs and reopen this issue if it's still be an issue for you.
