### ISSUE TITLE
Add Bond

### ISSUE THREAD

**Issue by codeandroid** [Microsoft/vcpkg#68]
https://microsoft.github.io/bond/

> Bond is an open source, cross-platform framework for working with schematized data. It supports cross-language serialization/deserialization and powerful generic mechanisms for efficiently manipulating data.

Note: The bond compiler is written in Haskell. I'm not aware of an official binary release.

**Comment by chwarr** [comment]
I need to re-work the Bond CMake files a bit, but I have this working on my machine. (Though, it only produces the lib files. You'll need to use your own gbc to do codegen--for now. See related issue, #59.)

I think I'll be able to get a PR ready on Friday or Monday.

**Comment by chwarr** [comment]
Created a PR for the library-only version.
