### ISSUE TITLE
boost-thread from 1.70 fails rel build with VS 2019

### ISSUE THREAD

**Issue by 9prady9** [microsoft/vcpkg#6800]
The following patch error is present in patch log and attached is the full release build log. I believe debug build goes through find as I don't see any errors in the respective log.
```
Checking patch include/boost/thread/win32/thread_primitives.hpp...
error: while searching for:
    {?
        namespace win32?
        {?
            namespace detail { typedef ticks_type (WINAPI *gettickcount64_t)(); }?
            extern BOOST_THREAD_DECL boost::detail::win32::detail::gettickcount64_t gettickcount64;?
?
            enum event_type?

error: patch failed: include/boost/thread/win32/thread_primitives.hpp:70
error: include/boost/thread/win32/thread_primitives.hpp: patch does not apply
```
[build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/3261775/build-x64-windows-rel-out.log)

**Comment by 9prady9** [comment]
@wangli28 Thanks! for the fix

**Comment by wangli28** [comment]
This issue has been fixed. So I am closing this issue for now.
