### ISSUE TITLE
vcpkg install clapack fails - apline linux

### ISSUE THREAD

**Issue by bhosaleajay** [microsoft/vcpkg#6808]
Get the following error while running ./vcpkg install --triplet x64-linux-musl clapack

vcpkg/buildtrees/clapack/src/clapack-3-7f93e8d7c1/F2CLIBS/libf2c/uninit.c:236:10: fatal error: fpu_control.h: No such file or directory
 #include "fpu_control.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
[24/1618] /usr/bin/cc -DNO_BLAS_WRAP -I/home/vagrant/temp/vcpkg/buildtrees/clapack/src/clapack-3-7f93e8d7c1/INCLUDE -I/home/vagrant/temp/vcpkg/buildtrees/clapack/src/clapack-3-7f93e8d7c1/F2CLIBS/libf2c -IF2CLIB
S/libf2c -fPIC -g -MD -MT F2CLIBS/libf2c/CMakeFiles/f2c.dir/sig_die.c.o -MF F2CLIBS/libf2c/CMakeFiles/f2c.dir/sig_die.c.o.d -o F2CLIBS/libf2c/CMakeFiles/f2c.dir/sig_die.c.o   -c /home/vagrant/temp/vcpkg/buildtr
ees/clapack/src/clapack-3-7f93e8d7c1/F2CLIBS/libf2c/sig_die.c
[25/1618] /usr/bin/cc -DNO_BLAS_WRAP -I/home/vagrant/temp/vcpkg/buildtrees/clapack/src/clapack-3-7f93e8d7c1/INCLUDE -I/home/vagrant/temp/vcpkg/buildtrees/clapack/src/clapack-3-7f93e8d7c1/F2CLIBS/libf2c -IF2CLIB
S/libf2c -fPIC -g -MD -MT F2CLIBS/libf2c/CMakeFiles/f2c.dir/pow_ci.c.o -MF F2CLIBS/libf2c/CMakeFiles/f2c.dir/pow_ci.c.o.d -o F2CLIBS/libf2c/CMakeFiles/f2c.dir/pow_ci.c.o   -c /home/vagrant/temp/vcpkg/buildtrees
/clapack/src/clapack-3-7f93e8d7c1/F2CLIBS/libf2c/pow_ci.c
ninja: build stopped: subcommand failed.

**Comment by wangli28** [comment]
Hi @bhosaleajay, thanks for posting this issue. Can you provide your triplet file `x64-linux-musl.cmake`?

**Comment by bhosaleajay** [comment]
Here are contents of the x64-linux-musl.cmake - thanks for any help in advance


set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)

**Comment by ras0219-msft** [comment]
It looks like clapack doesn't support muslc:

1. https://packages.debian.org/search?searchon=contents&keywords=fpu_control.h&mode=path&suite=stable&arch=any
indicates that `fpu_control.h` is provided by the c library

2. https://pkgs.alpinelinux.org/contents?file=fpu_control.h&path=&name=&branch=edge
indicates that `fpu_control.h` is _not_ provided by alpine linux (muslc)

3. https://github.com/openmeeg/clapack/blob/543e60b09fde5ea3329f1f0b597c8951e3858533/F2CLIBS/libf2c/uninit.c#L236
indicates that the `#include "fpu_control.h"` is not obviously optional.

If you are looking to build a library that uses clapack (like opencv), you may want to try removing the clapack dependency from its `Build-Depends` line and see if it builds.

**Comment by JackBoosY** [comment]
I found `fpu_control.h` in _/usr/include/x86_64-linux-gnu/_, and my gcc version is 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1).
As @ras0219-msft said, this header file is not available in all Linux distributions, and I found it to be part of glibc.
So please install glibc or using the same version of gcc as me before rebuild this port after .

Thanks.

**Comment by bhosaleajay** [comment]
I am actually looking to build fully static version of my project which depends on armadillo - which i am trying to install using vcpkg - here is the armadillo port file 

include(vcpkg_common_functions)

vcpkg_check_linkage(ONLY_STATIC_LIBRARY)

vcpkg_from_gitlab(
    GITLAB_URL https://gitlab.com
    OUT_SOURCE_PATH SOURCE_PATH
    REPO conradsnicta/armadillo-code
    REF f00d3225b1c005775044369723f31cecc3cd6569
    SHA512 ca3574edf5de8c752867403c3856ed9569fbed2ce9729585cae59be5751493c2e71121319b0a812e2ea56baada6b6f62fbc84ce6f1efb362347e5fd4141ccf1b
    HEAD_REF 9.400.x
    PATCHES
        remove_custom_modules.patch
)

file(REMOVE ${SOURCE_PATH}/cmake_aux/Modules/ARMA_FindBLAS.cmake)
file(REMOVE ${SOURCE_PATH}/cmake_aux/Modules/ARMA_FindLAPACK.cmake)
file(REMOVE ${SOURCE_PATH}/cmake_aux/Modules/ARMA_FindOpenBLAS.cmake)

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -DDETECT_HDF5=false
)

vcpkg_install_cmake()
vcpkg_fixup_cmake_targets(CONFIG_PATH share/armadillo/CMake TARGET_PATH share/armadillo)

vcpkg_copy_pdbs()

file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/include)
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/share)

file(INSTALL ${SOURCE_PATH}/LICENSE.txt  DESTINATION ${CURRENT_PACKAGES_DIR}/share/armadillo RENAME copyright)

**Comment by LilyWangL** [comment]
Thanks for posting this issue. `armadillo` can build successfully on Linux, please reopen this issue if this is still a problem for you.
