### ISSUE TITLE
Package mongo-cxx-driver does not install "include\options" directory

### ISSUE THREAD

**Issue by LeonineKing1199** [Microsoft/vcpkg#681]
I've noticed that my install of the mongo-cxx-driver package doesn't include the directory: `vcpkg\installed\x86-windows\include\mongocxx\options` as it should. There's many references in the header files to an options directory which is found here: https://github.com/mongodb/mongo-cxx-driver/tree/releases/stable/src/mongocxx/options

I'm currently unable to use many header files such as `<mongocxx/client>` which contains: `#include <mongocxx/options/client.hpp>`

**Comment by alexkaratarakis** [comment]
Thanks for reporting this. 
6d2b407b28417009fec0964b7339280d337dae6c should fix the issue.
