### ISSUE TITLE
[physfs] CMake finds the package but can't include physfs.h in VS

### ISSUE THREAD

**Issue by jesta88** [microsoft/vcpkg#6815]
This is for a CMake project in VS 2019. All other vcpkg packages work fine (SDL2, vulkan, spirv, etc.)

`1> [CMake] -- Found PhysFS: C:/Users/***/vcpkg/installed/x64-windows/debug/lib/physfs.lib`

![image](https://user-images.githubusercontent.com/5116779/59110576-6dba0b00-890d-11e9-9ea0-4386fbb18597.png)

**Comment by wangli28** [comment]
Have you executed the command `.\vcpkg.exe integrate install` on your `vcpkg` window?

**Comment by jesta88** [comment]
Yes. I use 8+ packages from vcpkg and never had any issue with those. I link physfs in CMake but the include dir is not found in VS. Tested on multiple machines too.

**Comment by PhoebeHui** [comment]
@jesta88, thanks for posting this issue!

However, I can't reproduce this issue, what I tried:
1.  ./vcpkg install physfs:x64-windows
2. ./vcpkg integrate install
3. Create a cmake project in VS2019(16.2 preview 2.0).
4. Setting the configuration(x64-Debug, the generator and toolchain file)
5. Add below code to the end of CMakeLists.txt, xxx is your project name.
   find_package(physfs REQUIRED) 
   target_include_directories(xxx PRIVATE ${PHYSFS_INCLUDE_DIR})
6. Add #include <physfs.h> to xxx.cpp file.
7. Save it, and it build automatically.
8. physfs.h find correctly.

**Comment by jesta88** [comment]
Normally in "proper" CMake you don't include an external lib's directories, you simply link to a lib that exported an interface. I guess the physfs CMakeLists was made with the older, wrong practices. 

Kind of a shame since almost all other libraries have proper exported targets. Maybe that's something we can fix with a patch in vcpkg? I'll investigate and report back.

Thanks!

**Comment by JackBoosY** [comment]
Hi @jesta88, When you use a **non-exported** port, you must use the **vcpkg toolchain** generated by the command `vcpkg integrate install` to use the various paths of the port correctly.

**Comment by jesta88** [comment]
Thanks for the clarification, I thought `vcpkg integrate install` was a one-time thing.
