### ISSUE TITLE
Windows sdk

### ISSUE THREAD

**Issue by wcowboy** [microsoft/vcpkg#6828]
### 

The following packages will be built and installed:
    opencv[core,eigen,flann,jpeg,opengl,png,tiff]:x86-windows

  * opengl[core]:x86-windows
  Additional packages (*) will be modified to complete this operation.
  Starting package 1/2: opengl:x86-windows
  Building package opengl[core]:x86-windows...
  CMake Error at ports/opengl/portfile.cmake:20 (message):
    Cannot find Windows 10.0.17763.0 SDK.  File does not exist: C:\Program
    Files (x86)\Windows Kits\10\Lib\10.0.17763.0\um\x86\OpenGL32.Lib
  Call Stack (most recent call first):
    scripts/ports.cmake:71 (include)

Error: Building package opengl:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opengl:x86-windows
  Vcpkg version: 2018.11.23-nohash

## And when I try again**.\vcpkg install opengl[core]:x86-windows**, prompt me：

The following packages will be built and installed:
    opengl[core]:x86-windows
Starting package 1/1: opengl:x86-windows
Building package opengl[core]:x86-windows...
CMake Error at ports/opengl/portfile.cmake:20 (message):
  Cannot find Windows 10.0.17763.0 SDK.  File does not exist: C:\Program
  Files (x86)\Windows Kits\10\Lib\10.0.17763.0\um\x86\OpenGL32.Lib
Call Stack (most recent call first):
  scripts/ports.cmake:71 (include)

Error: Building package opengl:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opengl:x86-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

## Windows sdk problem?

But I have downloaded windows sdk 10.0.17763.0 through vs install, and it can also be used in vs2017, then I don't know how to solve it, so I need your help.

**Comment by BeatWolf** [comment]
Also searching for the solution for this

**Comment by heydojo** [comment]
Why **x86**? Surely:
`vcpkg install opencv:x64-windows`
instead?

I noticed a hard coded dependency upon v141 : https://github.com/microsoft/vcpkg/blob/master/ports/opencv/portfile.cmake#L336
when I was checked to see if this port can do x64 too.

For reference, the current stable platform version is v142 when using VS2019.

**Comment by Voskrese** [comment]
File does not exist: 

C:\Program
Files (x86)\Windows Kits\10\Lib\10.0.17763.0\um\x86\OpenGL32.Lib

**Comment by PhoebeHui** [comment]
@wcowboy, could check if "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\um\x86\OpenGL32.Lib" exist under your windows sdk 10.0.17763.0? if not, you might need to find why it's not there, reinstall windows sdk might work.

**Comment by PhoebeHui** [comment]
@wcowboy, OpenGL requires that you install Windows 10 SDK, you can install it by running the Visual Studio Installer, reopen this if it still be an problem for you.
