### ISSUE TITLE
CMake can't find libuuid package

### ISSUE THREAD

**Issue by MarkIngramUK** [microsoft/vcpkg#6832]
Applies at least to commit 2ca3476.

Following a `vcpkg install libuuid`, CMake is unable to find the package using `find_package(libuuid REQUIRED)`.

**Comment by LilyWangL** [comment]
Hi @MarkIngramUK, you should use `find_library` to find libuuid. This is my CMakeLists.txt:
```
cmake_minimum_required (VERSION 3.9)

project (testuuid C)

add_executable(testuuid main.c)

find_path(LIBUUID_INCLUDE_DIR uuid.h PATH_SUFFIXES uuid)
find_library(LIBUUID_LIBRARY libuuid.a)
include_directories(${LIBUUID_INCLUDE_DIR})
target_link_libraries(testuuid PUBLIC ${LIBUUID_LIBRARY})
```

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed, so I am closing this issue for now.

**Comment by MarkIngramUK** [comment]
@LilyWangL , is it not a requirement that all packages support `find_package`?
