### ISSUE TITLE
openmvs build error

### ISSUE THREAD

**Issue by Huang88888888Fei** [microsoft/vcpkg#6837]
While building openMVS with vs 2015 win64, I have following problems. ( I think the problem is the usage of 'constexpr'  in C++ 14. )

in err-log:
e:\vcpkg\buildtrees\openmvs\src\v1.0-4d893b0edd\libs\common\Types.h(641): error C3250: 'ret': declaration is not allowed in 'constexpr' function body
e:\vcpkg\buildtrees\openmvs\src\v1.0-4d893b0edd\libs\common\Types.h(641): error C3249: illegal statement or sub-expression for 'constexpr' function
e:\vcpkg\buildtrees\openmvs\src\v1.0-4d893b0edd\libs\common\Types.h(642): error C3249: illegal statement or sub-expression for 'constexpr' function
e:\vcpkg\buildtrees\openmvs\src\v1.0-4d893b0edd\libs\common\Types.h(643): error C3249: illegal statement or sub-expression for 'constexpr' function

and the Types.h (line 629~ line 651):
template<typename T>
constexpr T powi(T base, int exp) {
	T result(1);
	while (exp) {
		if (exp & 1)
			result *= base;
		exp >>= 1;
		base *= base;
	}
	return result;
}
constexpr int log2i(int val) {
	int ret = -1;
	while (val > 0) {
		val >>= 1;
		ret++;
	}
	return ret;
}
template <int N> constexpr inline int log2i() { return 1+log2i<(N>>1)>(); }
template <>   constexpr inline int log2i<0>() { return -1; }
template <>   constexpr inline int log2i<1>() { return 0; }
template <>   constexpr inline int log2i<2>() { return 1; }

When I remove the 'constexpr' before the function, I have following problems.

MVS.lib(Camera.cpp.obj) : error LNK2005: "int __cdecl SEACAVE::log2i(int)" (?log2i@SEACAVE@@YAHH@Z) already defined in InterfaceCOLMAP.cpp.obj
MVS.lib(Image.cpp.obj) : error LNK2005: "int __cdecl SEACAVE::log2i(int)" (?log2i@SEACAVE@@YAHH@Z) already defined in InterfaceCOLMAP.cpp.obj
MVS.lib(PointCloud.cpp.obj) : error LNK2005: "int __cdecl SEACAVE::log2i(int)" (?log2i@SEACAVE@@YAHH@Z) already defined in InterfaceCOLMAP.cpp.obj
MVS.lib(Platform.cpp.obj) : error LNK2005: "int __cdecl SEACAVE::log2i(int)" (?log2i@SEACAVE@@YAHH@Z) already defined in InterfaceCOLMAP.cpp.obj
IO.lib(Image.cpp.obj) : error LNK2005: "int __cdecl SEACAVE::log2i(int)" (?log2i@SEACAVE@@YAHH@Z) already defined in InterfaceCOLMAP.cpp.obj
IO.lib(PLY.cpp.obj) : error LNK2005: "int __cdecl SEACAVE::log2i(int)" (?log2i@SEACAVE@@YAHH@Z) already defined in InterfaceCOLMAP.cpp.obj
IO.lib(ImageSCI.cpp.obj) : error LNK2005: "int __cdecl SEACAVE::log2i(int)" (?log2i@SEACAVE@@YAHH@Z) already defined in InterfaceCOLMAP.cpp.obj
IO.lib(ImageBMP.cpp.obj) : error LNK2005: "int __cdecl SEACAVE::log2i(int)" (?log2i@SEACAVE@@YAHH@Z) already defined in InterfaceCOLMAP.cpp.obj
IO.lib(ImageTGA.cpp.obj) : error LNK2005: "int __cdecl SEACAVE::log2i(int)" (?log2i@SEACAVE@@YAHH@Z) already defined in InterfaceCOLMAP.cpp.obj
IO.lib(ImageDDS.cpp.obj) : error LNK2005: "int __cdecl SEACAVE::log2i(int)" (?log2i@SEACAVE@@YAHH@Z) already defined in InterfaceCOLMAP.cpp.obj
IO.lib(ImagePNG.cpp.obj) : error LNK2005: "int __cdecl SEACAVE::log2i(int)" (?log2i@SEACAVE@@YAHH@Z) already defined in InterfaceCOLMAP.cpp.obj
IO.lib(ImageJPG.cpp.obj) : error LNK2005: "int __cdecl SEACAVE::log2i(int)" (?log2i@SEACAVE@@YAHH@Z) already defined in InterfaceCOLMAP.cpp.obj
IO.lib(ImageTIFF.cpp.obj) : error LNK2005: "int __cdecl SEACAVE::log2i(int)" (?log2i@SEACAVE@@YAHH@Z) already defined in InterfaceCOLMAP.cpp.obj
Common.lib(Common.cpp.obj) : error LNK2005: "int __cdecl SEACAVE::log2i(int)" (?log2i@SEACAVE@@YAHH@Z) already defined in InterfaceCOLMAP.cpp.obj
Common.lib(Timer.cpp.obj) : error LNK2005: "int __cdecl SEACAVE::log2i(int)" (?log2i@SEACAVE@@YAHH@Z) already defined in InterfaceCOLMAP.cpp.obj
Common.lib(Util.cpp.obj) : error LNK2005: "int __cdecl SEACAVE::log2i(int)" (?log2i@SEACAVE@@YAHH@Z) already defined in InterfaceCOLMAP.cpp.obj
Common.lib(Log.cpp.obj) : error LNK2005: "int __cdecl SEACAVE::log2i(int)" (?log2i@SEACAVE@@YAHH@Z) already defined in InterfaceCOLMAP.cpp.obj
Common.lib(Types.cpp.obj) : error LNK2005: "int __cdecl SEACAVE::log2i(int)" (?log2i@SEACAVE@@YAHH@Z) already defined in InterfaceCOLMAP.cpp.obj

Please help me. Thanks!

**Comment by PhoebeHui** [comment]
@Huang88888888Fei, thanks for posting this issue!

I got latest vcpkg revision and tried to build openmvs with VS2017 15.9.11, it installed successfully. So I think It might be your compiler version doesn't support C++14 constexpr or a compiler issue that fixed now, so you need upgrade your compiler and try again.

Starting package 98/98: openmvs:x64-windows
Building package openmvs[core]:x64-windows...
-- Note: openmvs only supports static library linkage. Building static library.
-- Downloading https://github.com/cdcseacave/openMVS/archive/v1.0.tar.gz...
-- Extracting source F:/VCPKG/src/downloads/cdcseacave-openMVS-v1.0.tar.gz
-- Applying patch glfw3_target_compat.patch
-- Using source at F:/VCPKG/src/buildtrees/openmvs/src/v1.0-4d893b0edd
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: F:/VCPKG/src/packages/openmvs_x64-windows/share/openmvs/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package openmvs[core]:x64-windows... done
Installing package openmvs[core]:x64-windows...
Installing package openmvs[core]:x64-windows... done
Elapsed time for package openmvs:x64-windows: 13.14 min

Total elapsed time: 52.32 min

The package openmvs:x64-windows provides CMake targets:

    find_package(OpenMVS CONFIG REQUIRED)
    target_link_libraries(main PRIVATE IO MVS Math Common)

**Comment by Huang88888888Fei** [comment]
@PhoebeHui 
Thank you for replying! And I think you are right. Using VS2017 can slove the problem. But I solve this problem in the VS2015. I replaced the `constexpr ` with `inline` before the function `powi` and `logi`.  I found it in old version of OpenMVS. Thank you very much! And I think we can close this issue?

**Comment by PhoebeHui** [comment]
Yes, thanks for closing it.
