### ISSUE TITLE
Add FFMS2

### ISSUE THREAD

**Issue by wrosecrans** [microsoft/vcpkg#684]
Requesting a package for FFMS2:
https://github.com/FFMS/ffms2

It depends on ffmpeg  -  (  #2 ), and ffmpeg has some dependencies, but it does build with MSVC 2015 so it should be relatively straightforward to support.  By default, the build script for ffms2 builds a limited ffmpeg with some options disabled if they aren't useful to ffms, but it'd probably make sense to use a generic ffmpeg and link ffms2 to that rather than the one it builds by default.

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
