### ISSUE TITLE
SDL1 and SDL2 result is faulting linked application.

### ISSUE THREAD

**Issue by rioki** [microsoft/vcpkg#6841]
I have had a well running SDL2 application. I installed OGRE wich pulls SDL1 as a dependency. As a result the application links with SDL2 and SDL1, resulting in a mess, since some functions are linked to SDL2 and some to SDL1. The annoying part is that the core OGRE library does not even need SDL1, just the tutorial utility. 

Is there a way to prevent linking every library installed? This is basically a different case like #306, just that they are not the optional bits.

**Comment by cbezault** [comment]
If core OGRE does not need SDL1 you can drop it from the dependencies and add it back as a feature. Are you using MSBuild or CMake for your project. If you're using CMake per #306 it shouldn't be linking every library. If using MSBuild #306 mentions a property, `VcpkgAutoLink` that you can set to false to disable auto-linking every installed library and then explicitly link to SDL2.

**Comment by rioki** [comment]
Thank you for the info, I will look into VcpkgAutoLink as that is exactly what I need. I really like vcpkg, but I don't mind referencing the one or other library.
The problem of OGRE is that it is composed of multiple parts. Some can be defined as the "core" and some as the support libraries. The support libraries use SDL1 to create a window and rendering context, but I do that through other means (including SDL2) and thus don't need it. 
I will look into VcpkgAutoLink and see if I can improve the documentation and PR that if I feel like it's worth it.
