### ISSUE TITLE
Failed to build osg [Mac OS]

### ISSUE THREAD

**Issue by coderc264** [microsoft/vcpkg#6848]
Hi all, i tried to install open scene graph library on my Mac machine, but i get this error:

./vcpkg install osg
The following packages will be built and installed:
    osg[core]:x64-osx
Starting package 1/1: osg:x64-osx
Building package osg[core]:x64-osx...
-- Note: osg only supports dynamic library linkage. Building dynamic library.
-- Using cached /Users/roberto/vcpkg/downloads/openscenegraph-OpenSceneGraph-OpenSceneGraph-3.6.3.tar.gz
-- Using source at /Users/roberto/vcpkg/buildtrees/osg/src/raph-3.6.3-e8b171e32a
-- Configuring x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: /Users/roberto/vcpkg/downloads/tools/cmake-3.14.0-osx/cmake-3.14.0-Darwin-x86_64/CMake.app/Contents/bin/cmake;/Users/roberto/vcpkg/buildtrees/osg/src/raph-3.6.3-e8b171e32a;-DOSG_USE_UTF8_FILENAME=ON;-DCMAKE_MAKE_PROGRAM=/Users/roberto/vcpkg/downloads/tools/ninja-1.8.2-osx/ninja;-DCMAKE_SYSTEM_NAME=Darwin;-DBUILD_SHARED_LIBS=ON;-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/Users/roberto/vcpkg/scripts/toolchains/osx.cmake;-DVCPKG_TARGET_TRIPLET=x64-osx;-DVCPKG_PLATFORM_TOOLSET=external;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=/Users/roberto/vcpkg/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DVCPKG_CXX_FLAGS=;-DVCPKG_CXX_FLAGS_RELEASE=;-DVCPKG_CXX_FLAGS_DEBUG=;-DVCPKG_C_FLAGS=;-DVCPKG_C_FLAGS_RELEASE=;-DVCPKG_C_FLAGS_DEBUG=;-DVCPKG_CRT_LINKAGE=dynamic;-DVCPKG_LINKER_FLAGS=;-DCMAKE_INSTALL_LIBDIR:STRING=lib;-DCMAKE_INSTALL_BINDIR:STRING=bin;-G;Ninja;-DCMAKE_BUILD_TYPE=Debug;-DCMAKE_INSTALL_PREFIX=/Users/roberto/vcpkg/packages/osg_x64-osx/debug
    Working Directory: /Users/roberto/vcpkg/buildtrees/osg/x64-osx-dbg
    Error code: 1
    See logs for more information:
      /Users/roberto/vcpkg/buildtrees/osg/config-x64-osx-dbg-out.log
      /Users/roberto/vcpkg/buildtrees/osg/config-x64-osx-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:282 (vcpkg_execute_required_process)
  ports/osg/portfile.cmake:21 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package osg:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: osg:x64-osx
  Vcpkg version: 2018.11.23-unknownhash

Additionally, attach any relevant sections from the log files above.

Contents of  /Users/roberto/vcpkg/buildtrees/osg/config-x64-osx-dbg-out.log file :

-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- broken
-- Configuring incomplete, errors occurred!
See also "/Users/roberto/vcpkg/buildtrees/osg/x64-osx-dbg/CMakeFiles/CMakeOutput.log".
See also "/Users/roberto/vcpkg/buildtrees/osg/x64-osx-dbg/CMakeFiles/CMakeError.log".

**Comment by coderc264** [comment]
The same issue appened in Mint 19.1 fresh install

Building package osg[core]:x64-linux...
-- Note: osg only supports dynamic library linkage. Building dynamic library.
-- Downloading https://github.com/openscenegraph/OpenSceneGraph/archive/OpenSceneGraph-3.6.3.tar.gz...
-- Extracting source /home/roberto/vcpkg/downloads/openscenegraph-OpenSceneGraph-OpenSceneGraph-3.6.3.tar.gz
-- Applying patch collada.patch
-- Using source at /home/roberto/vcpkg/buildtrees/osg/src/raph-3.6.3-e8b171e32a
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:202 (message):
    Command failed: /home/roberto/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake;--build;.;--config;Debug;--target;install;--;-v
    Working Directory: /home/roberto/vcpkg/buildtrees/osg/x64-linux-dbg
    See logs for more information:
      /home/roberto/vcpkg/buildtrees/osg/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/osg/portfile.cmake:27 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package osg:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: osg:x64-linux
  Vcpkg version: 2018.11.23-unknownhash

**Comment by JackBoosY** [comment]
Hi @coderc264, thanks for reporting this issue!
This issue should be fixed in some PRs. Please update vcpkg and rebuild osg.

Thanks.
