### ISSUE TITLE
Add FFTW and FFTW++

### ISSUE THREAD

**Issue by wrosecrans** [microsoft/vcpkg#685]
Requesting a package for FFTW. It is an open source Fourier transform library at 
http://www.fftw.org/

And fftw++ is a companion C++ wrapper:
https://github.com/dealias/fftwpp

**Comment by jakirkham** [comment]
Upstream is working on Windows support for FFTW via CMake. They accepted PR ( https://github.com/FFTW/fftw3/pull/103 ) recently, which adds a CMake-based build for Windows. However they are sorting out a few issues that are coming out of this implementation. Would be good if some Windows experts could help advise them.

**Comment by JackBoosY** [comment]
Hi @wrosecrans, thanks for reporting this issue.
Vcpkg now support fftw3, please update vcpkg and try to build fftw3.

Thanks.

**Comment by JackBoosY** [comment]
Hi @wrosecrans, `fftw++` has been added in vcpkg(named fftwpp), please update vcpkg and try to install it.

Thanks.
