### ISSUE TITLE
qt5-declarative port file lacks debug encapsulation

### ISSUE THREAD

**Issue by heydojo** [microsoft/vcpkg#6857]
https://github.com/microsoft/vcpkg/blob/master/ports/qt5-declarative/portfile.cmake

```powershell
set(qt5decpath ${CURRENT_PACKAGES_DIR}/share/qt5/debug/mkspecs/modules/qt_lib_qmldevtools_private.pri)
file(READ "${qt5decpath}" _contents)
string(REPLACE [[QT.qmldevtools_private.libs = $$QT_MODULE_HOST_LIB_BASE]] [[QT.qmldevtools_private.libs = $$QT_MODULE_LIB_BASE]]  _contents "${_contents}")
file(WRITE "${qt5decpath}" "${_contents}")
```

Becomes:

```powershell
if (NOT DEFINED VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL "debug")
	set(qt5decpath ${CURRENT_PACKAGES_DIR}/share/qt5/debug/mkspecs/modules/qt_lib_qmldevtools_private.pri)
	file(READ "${qt5decpath}" _contents)
	string(REPLACE [[QT.qmldevtools_private.libs = $$QT_MODULE_HOST_LIB_BASE]] [[QT.qmldevtools_private.libs = $$QT_MODULE_LIB_BASE]]  _contents "${_contents}")
	file(WRITE "${qt5decpath}" "${_contents}")
endif()
```

If you want to use a triplet to only build release and not debug.
Otherwise  `vcpkg install qt5-declarative:x64-windows` will fail with the message:

> CMake Error at ports/qt5-declarative/portfile.cmake:10 (file):
>   file failed to open for reading (No such file or directory):

Please feel free to make these suggested changes to vcpkg if they solve the issue.
I am not at liberty to sign the contributors agreement, so have not proposed a merge.
Easy pickup for someone with write access to the tree IMO. ⚽️

**Comment by JackBoosY** [comment]
Hi @heydojo, thanks for reporting this issue!
I've fixed this issue just now. Please update vcpkg and rebuild qt5-declarative.

Thanks.

**Comment by heydojo** [comment]
Welcome 💃
