### ISSUE TITLE
Error: Building package zlib:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by aprykhus** [microsoft/vcpkg#6859]
Trying to install gtk through vcpkg as per https://www.gtk.org/download/windows.php. Machine is running Windows 10 64-bit 1809 with VS2017 and VS2019 Community installed all fully patched.

Repro steps:
1) Run PowerShell as admin.
2) .\bootstrap-vcpkg.bat
3) .\vcpkg install gtk:x64-windows
Error below

Things I've tried:
Error in attached log references 14.20.27508 directory in compiler path under MSVC directory but that doesn't exist on machine, it's actually 14.21.27702.
Path in error in attached log

C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x64/cl.exe

Actual path to cl.exe
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\bin\Hostx64\x64

Tried adding CL env variable with correct path and re-running bootstrap-vcpkg.bat but it fails.
Patched VS2017/2019
Ran vcpkg update
Deleted vcpkg repo and re-cloned.
Ran with VS2019 Developer Command Prompt.
cl.exe compiles a sample c program successfully so compiler is working.
Tried installing other packages, boost seems to install (shows in vcpkg list) but there's a different error, something about not able to locate batch.bat. But I tried CURL package and that gives the exact same error as gtk.

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/3278217/config-x64-windows-out.log)
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/3278219/config-x64-windows-out.log)

ERROR 
---------------------------------------------------------------------------------------
CMake Error at gitclones/vcpkg/scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: D:/Documents/gitclones/vcpkg/buildtrees/zlib/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\Documents\gitclones\vcpkg\buildtrees\zlib\config-x64-windows-out.log

Call Stack (most recent call first):
  gitclones/vcpkg/scripts/cmake/vcpkg_configure_cmake.cmake:273 (vcpkg_execute_required_process)
  gitclones/vcpkg/ports/zlib/portfile.cmake:22 (vcpkg_configure_cmake)
  gitclones/vcpkg/scripts/ports.cmake:71 (include)

Error: Building package zlib:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x64-windows
  Vcpkg version: 2018.11.23-nohash
---------------------------------------------------------------------------------------

**Comment by aprykhus** [comment]
Deleted the vcpkg repo on D drive and downloaded to C drive. That got further but still throws BUILD_FAILED error.

[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/3279397/config-x86-windows-out.log)

**Comment by Cheney-W** [comment]
@aprykhus Thanks for reporting this issue. Could you do as below steps:
1. Clone a new vcpkg into your computer, whatever C or D drive.
2. Modify scripts\bootstrap.ps1 line 371 from /verbosity:minimal to /verbosity:normal and save it.
3. .\bootstrap-vcpkg.bat > vcpkg.log
4. .\vcpkg.exe install zlib
If the error still occur, please send the vcpkg.log and the config error log to us.

**Comment by aprykhus** [comment]
Thanks for your reply. Followed those steps and still get the error:
[vcpkg.log](https://github.com/microsoft/vcpkg/files/3282626/vcpkg.log)
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/3282630/config-x86-windows-out.log)

**Comment by Cheney-W** [comment]
@aprykhus Please see the compile log of CMakeCCompilerId.c in x86-windows-rel(or x86-windows-dbg)\CMakeFIles\CMakeOutput.log. 
I think there should be some error in your compiler. I suggest you repair your VS or reinstall it. I tested it with the same version of vs as yours, and zlib was installed successfully.

**Comment by aprykhus** [comment]
VS2019 windows console app threw error "MSB6006 "CL.exe" exited with code 2." Repairing VS2019 fixed the compiler in VS2019 but '.\vcpkg install zlib' still throws same error. Since you can't repro and I'm not spending any more time on this I'll close this issue and open a new one later if necessary.

**Comment by jefmir** [comment]
hello 
I have the same problem with vcpkg  in installing any package
help me please

**Comment by jefmir** [comment]
ohhhhh   its on 379 not 371

tax alot

**Comment by Cheney-W** [comment]
@jefmir Could you please open a new issue for this? Thank you.

**Comment by pengguoqing** [comment]
I have the same problem with vcpkg in installing zlib, but I have resolved this problem.
Maybe you can also try to update VS2019 to the latest version and install it again
