### ISSUE TITLE
multiply defined symbols when use hdf5

### ISSUE THREAD

**Issue by giorgk** [microsoft/vcpkg#6869]
I have been able to install successfully hdf5 using `vcpkg install hdf5`.
Using VS2017 I attempt to compile the following program
https://support.hdfgroup.org/ftp/HDF5/current/src/unpacked/examples/h5_crtdat.c
During compilation I get the many errors similar to
LNK2005	_H5open already defined in hdf5_D.lib(hdf5_D.dll)
LNK2005	_H5check_version already defined in hdf5_D.lib(hdf5_D.dll)	etc. 
and at the end
LNK1169	one or more multiply defined symbols found

I have used the `vcpkg integrate install` 
Any ideas what's wrong here?

**Comment by Neumann-A** [comment]
try defining `H5_BUILT_AS_DYNAMIC_LIB` if you are using x64-windows

**Comment by giorgk** [comment]
That worked!
Just for completeness [this link](https://stackoverflow.com/questions/34144852/hdf5-as-dynamic-linked-library-qt-c-under-windows) shows how to set the variable under VS and not only

**Comment by wangli28** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
