### ISSUE TITLE
Add OpenImageIO

### ISSUE THREAD

**Issue by wrosecrans** [Microsoft/vcpkg#687]
Requesting a package for OpenImageIO, a library used in many VFX apps for reading and writing a variety of image formats:
https://github.com/OpenImageIO/oiio

It has support for several popular image file formats, including TIFF, JPEG/JFIF, OpenEXR, PNG, HDR/RGBE, ICO, BMP, Targa, JPEG-2000, RMan Zfile, FITS, DDS, Softimage PIC, PNM, DPX, Cineon, IFF, Field3D, Ptex, Photoshop PSD, Wavefront RLA, SGI, WebP, GIF, DICOM, many "RAW" digital camera formats, and a variety of movie formats (readable as individual frames).

Several of the prerequisites are already supported by Vcpkg, such as libpng.  Others like OpenEXR are not yet supported by Vcpkg.  A lot of the plugins are optionally built, so it my be practical to do a limited OIIO, and then add support for additional formats by adding their prerequisite libs to Vcpkg over time.

**Comment by laserallan** [comment]
I am working on it but I'm targeting getting all the way to open shading language.
Feel free to grab it and play around with it though: https://github.com/laserallan/vcpkg
