### ISSUE TITLE
AWS SDK linkage

### ISSUE THREAD

**Issue by kreuzerkrieg** [microsoft/vcpkg#6882]
For some reason I get 

> ~/Development/vcpkg/installed/x64-linux/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
> dso_dlfcn.c:(.text+0x11): undefined reference to `dlopen'

I've tried everything I can think of, still no luck
My CMake file looks like
```
cmake_minimum_required(VERSION 3.14)
project(S3Test)

set(CMAKE_CXX_STANDARD 17)

find_package(OpenSSL REQUIRED)
find_package(aws-cpp-sdk-core CONFIG REQUIRED)
find_package(aws-cpp-sdk-dynamodb CONFIG REQUIRED)
find_package(aws-cpp-sdk-kinesis CONFIG REQUIRED)
find_package(aws-cpp-sdk-s3 CONFIG REQUIRED)

add_executable(S3Test main.cpp)
target_link_libraries(S3Test PRIVATE
                      ${CMAKE_DL_LIBS}
                      OpenSSL::SSL
                      OpenSSL::Crypto
                      aws-cpp-sdk-s3
                      aws-cpp-sdk-core
                      aws-cpp-sdk-dynamodb
                      aws-cpp-sdk-kinesis
                      pthread
                      dl
                      )
```
Any help is appreciated

**Comment by Voskrese** [comment]
https://github.com/FreeTDS/freetds/issues/54#issuecomment-190743440

**Comment by kreuzerkrieg** [comment]
BTW, cloned the original repo of AWS SDK, built it locally and it works

**Comment by Voskrese** [comment]
x64-linux/lib/**libcrypto**.a(dso_dlfcn.o): In function dlfcn_globallookup

**libcrypto** undefined reference to **dlopen**

`export LDFLAGS="-L$LIBDIR/lib -ldl"`

**Comment by kreuzerkrieg** [comment]
> FreeTDS/freetds#54 (comment)

just saw your reply
how come bug that was closed in 2016 still exists in this build? are you sure?

**Comment by Voskrese** [comment]
add libraries `-ldl`. reassemble and tell us

> I'm not sure about anything)

**Comment by kreuzerkrieg** [comment]
> add libraries -ldl. reassemble and tell us
so, what I've got to do is to remove the package, run `export LDFLAGS="-L$LIBDIR/lib -ldl"` and then reinstall package?

**Comment by Voskrese** [comment]
it is necessary to do this in the CMAKE environment, as far as I know VKPKG ignores external parameters

**Comment by kreuzerkrieg** [comment]
what do you mean by "CMAKE environment" should I add it to the port file?

**Comment by Voskrese** [comment]
this is my guess on the DL account

> wait, maybe someone will answer more intelligently

You can try with your system library by copying it to the right place VCPKG

> the original backup

**Comment by kreuzerkrieg** [comment]
Looks like the problem went away in the latest master
