### ISSUE TITLE
Failed to build opencl on Linux

### ISSUE THREAD

**Issue by dvp2015** [microsoft/vcpkg#6884]
The opencl portfiles.cmake tries to install libraries with Windows library name: OpenCL.lib. Linux expects libOpenCL.so.1.2 (and symbolik links). These libraries are actually built.

Log:

> ╰─ ./vcpkg install opencl
The following packages will be built and installed:
    opencl[core]:x64-linux
Starting package 1/1: opencl:x64-linux
Building package opencl[core]:x64-linux...
-- Note: opencl only supports dynamic library linkage. Building dynamic library.
-- Using cached /home/dvp/dev/vcpkg/downloads/KhronosGroup-OpenCL-Headers-f039db6764d52388658ef15c30b2237bbda49803.tar.gz
-- Using source at /home/dvp/dev/vcpkg/buildtrees/opencl/src/7bbda49803-1683b7bb6a
-- Installing: /home/dvp/dev/vcpkg/packages/opencl_x64-linux/include/CL
-- Installing: /home/dvp/dev/vcpkg/packages/opencl_x64-linux/include/CL/cl_dx9_media_sharing_intel.h
-- Installing: /home/dvp/dev/vcpkg/packages/opencl_x64-linux/include/CL/cl_gl.h
-- Installing: /home/dvp/dev/vcpkg/packages/opencl_x64-linux/include/CL/cl_egl.h
-- Installing: /home/dvp/dev/vcpkg/packages/opencl_x64-linux/include/CL/opencl.h
-- Installing: /home/dvp/dev/vcpkg/packages/opencl_x64-linux/include/CL/cl_gl_ext.h
-- Installing: /home/dvp/dev/vcpkg/packages/opencl_x64-linux/include/CL/cl_ext.h
-- Installing: /home/dvp/dev/vcpkg/packages/opencl_x64-linux/include/CL/cl_d3d11.h
-- Installing: /home/dvp/dev/vcpkg/packages/opencl_x64-linux/include/CL/cl_ext_intel.h
-- Installing: /home/dvp/dev/vcpkg/packages/opencl_x64-linux/include/CL/cl_va_api_media_sharing_intel.h
-- Installing: /home/dvp/dev/vcpkg/packages/opencl_x64-linux/include/CL/cl_d3d10.h
-- Installing: /home/dvp/dev/vcpkg/packages/opencl_x64-linux/include/CL/cl.h
-- Installing: /home/dvp/dev/vcpkg/packages/opencl_x64-linux/include/CL/cl_platform.h
-- Installing: /home/dvp/dev/vcpkg/packages/opencl_x64-linux/include/CL/cl_dx9_media_sharing.h
-- Using cached /home/dvp/dev/vcpkg/downloads/KhronosGroup-OpenCL-CLHPP-5dd8bb9e32a8e2f72621566b296ac8143a554270.tar.gz
-- Using source at /home/dvp/dev/vcpkg/buildtrees/opencl/src/143a554270-b3029d29f7
-- Generating OpenCL C++ headers done
-- Using cached /home/dvp/dev/vcpkg/downloads/KhronosGroup-OpenCL-ICD-Loader-26a38983cbe5824fd5be03eab8d037758fc44360.tar.gz
-- Using source at /home/dvp/dev/vcpkg/buildtrees/opencl/src/758fc44360-e8fe074a5b
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
CMake Error at ports/opencl/portfile.cmake:66 (file):
  file INSTALL cannot find
  "/home/dvp/dev/vcpkg/buildtrees/opencl/x64-linux-rel/OpenCL.lib".
Call Stack (most recent call first):
  scripts/ports.cmake:71 (include)

Error: Building package opencl:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencl:x64-linux
  Vcpkg version: 2018.11.23-unknownhash

Additionally, attach any relevant sections from the log files above.

>

**Comment by wangli28** [comment]
Related PR: #4204

**Comment by JackBoosY** [comment]
Hi @dvp2015, thanks for reporting this issue!
It seems this issue has been fixed in #4204. Please update vcpkg and rebuild opencl.

Thanks.
