### ISSUE TITLE
how to use osgearth in a project

### ISSUE THREAD

**Issue by jepessen** [microsoft/vcpkg#6885]
I've installed osgearth with following command:

```{bash}
vcpkg install osgearth:x64-windows
```

But I don't understand how I can use it. I've tried to create the following CMake project:

```{bash}
cmake_minimum_required (VERSION 3.10.0)

project (osgmap)

add_definitions (-DOSGMAP_EXPORTS)

include_directories (${CMAKE_CURRENT_SOURCE_DIR}/..)
find_package (Osg REQUIRED)
find_package (OsgEarth REQUIRED)

set (PROJECT_SRC
  Dummy.cpp
  )

add_library (${PROJECT_NAME} SHARED ${PROJECT_SRC})
target_link_libraries (${PROJECT_NAME} mapapi)
target_compile_features (${PROJECT_NAME} PUBLIC cxx_std_17)
```
I can find osg but not osgearth. I've tried many combination.

What's the correct way to include osgearth in my projects?

**Comment by PhoebeHui** [comment]
@jepessen, see below doc to get start:
https://github.com/microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md

Noted that osgearth is a library that without native cmake support, please reference part 'Handling libraries without native cmake support'

**Comment by PhoebeHui** [comment]
@jepessen, please reopen this if it still be an problem for you.
