### ISSUE TITLE
Add OpenEXR 

### ISSUE THREAD

**Issue by traversaro** [Microsoft/vcpkg#689]
It would be great to have a port of the OpenEXR library ( https://github.com/openexr/openexr ).

Debian package : https://packages.debian.org/source/sid/openexr .
Homebrew formula : https://github.com/Homebrew/homebrew-core/blob/ba0aa68066a89c0654152aba22819736b06987af/Formula/openexr.rb .

Once the port has been added, the freeimage port should be modified to use vcpkg's OpenEXR instead of its own internal version, see https://github.com/Microsoft/vcpkg/pull/366#issue-192123893 . The main problem is that the OpenEXR build system runs executables compiled by the project itself, that prevent crosscompilation.

Related to https://github.com/Microsoft/vcpkg/issues/687 .

**Comment by laserallan** [comment]
I have a temporary one going here:
https://github.com/laserallan/vcpkg
My intention is to get everything needed for open shading language to build but it's quite a struggle.

**Comment by cloudhan** [comment]
I find a modified fork https://github.com/wjakob/openexr by one of authors of PBRT 3rd. In this fork, the dev added CMake support
