### ISSUE TITLE
Failed to install PCL

### ISSUE THREAD

**Issue by Clubbable** [microsoft/vcpkg#6890]
Hi, I am following the tutorial at http://unanancyowen.com/en/pcl-vcpkg/ to try to install PCL using vcpkg for Windows 10. Currently, I am trying to install the DLL libraries for PCL using the command:

`>vcpkg.exe install pcl[openni2,qt,pcap]:x64-windows --featurepackages`

However, I got an error with the following:

`Starting package 156/158: openni2:x64-windows
Building package openni2[core]:x64-windows...
-- Downloading https://github.com/OpenNI/OpenNI2/archive/2.2-beta2.tar.gz...
-- Extracting source F:/vcpkg-master/downloads/OpenNI-OpenNI2-2.2-beta2.tar.gz
-- Using source at F:/vcpkg-master/buildtrees/openni2/src/2.2-beta2-a8c7829707
-- Applying patch F:/vcpkg-master/ports/openni2/upgrade_projects.patch
-- Applying patch F:/vcpkg-master/ports/openni2/inherit_from_parent_or_project_defaults.patch
-- Applying patch F:/vcpkg-master/ports/openni2/replace_environment_variable.patch
-- Building F:/vcpkg-master/buildtrees/openni2/x64-windows/2.2-beta2-a8c7829707/OpenNI.sln for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: msbuild;F:/vcpkg-master/buildtrees/openni2/x64-windows/2.2-beta2-a8c7829707/OpenNI.sln;/p:Configuration=Release;/t:Rebuild;/p:Platform=x64;/p:PlatformToolset=v141;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No;/p:WindowsTargetPlatformVersion=10.0.17763.0;/m
    Working Directory: F:/vcpkg-master/buildtrees/openni2/x64-windows-rel
    Error code: 1
    See logs for more information:
      F:\vcpkg-master\buildtrees\openni2\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:119 (vcpkg_execute_required_process)
  ports/openni2/portfile.cmake:35 (vcpkg_build_msbuild)
  scripts/ports.cmake:71 (include)

Error: Building package openni2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openni2:x64-windows
  Vcpkg version: 2018.11.23-nohash`

Additionally, attach any relevant sections from the log files above.`

I went through the logs and attached it here
[build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/3287311/build-x64-windows-rel-out.log)

Here is the offending line:

`27>LINK : fatal error LNK1104: cannot open file 'MSCOREE.lib' [F:\vcpkg-master\buildtrees\openni2\x64-windows\2.2-beta2-a8c7829707\Source\Drivers\Kinect\Kinect.vcxproj]`

It appears that I am missing MSCOREE.lib, how should I fix this?

**Comment by Voskrese** [comment]
`vcpkg env --triplet x64-windows`
`where $lib:MSCOREE.lib`
?
`edit `or patch to` Kinect.vcxproj`

```
<Link>
      <AdditionalDependencies>MSCOREE.lib;%(AdditionalDependencies)</AdditionalDependencies>
```

**Comment by Clubbable** [comment]
Doesn't seem to be a problem anymore
