### ISSUE TITLE
The Contributor License Agreement is toxic. Remove it.

### ISSUE THREAD

**Issue by skychef** [microsoft/vcpkg#6899]
The majority of contributors are in no position to agree to the Microsoft Contributor License Agreement.

https://github.com/microsoft/vcpkg/blob/master/LICENSE.txt
is the software license.

The BSD license makes it very clear that the entire project is copyright the **Microsoft Corporation**.

The Contributor License Agreement forces assignment of all copyright to the Microsoft Corporation along with some other arbitrary grants of license.

**This is essentially no different to working for the Microsoft Corporation (a business) for free.**
**The Microsoft Contributor License Agreement is therefore a direct attack upon the spirit and ideas which underpin free and open source software.**

If copyright was being assigned to a non-profit, then a contributor license is appropriate.
If an employee at Microsoft wants to work on vcpkg, a private contributor license is appropriate.

Requiring every Github account to agree to an arbitrary contributor license before submitting patches to the project is not appropriate.

> You must secure permission from Your employer to make the Submission before signing this Agreement.

The only employer who can grant this is Microsoft. It is not in the interest of any other employer to ever grant this permission. Mainly because they are in direct competition with Microsoft.
All this policy does is breed private forks behind closed doors. Resulting in a stagnant tree and a project going through the motions of death by a thousand cuts.

> You grant Microsoft, and those who receive the Submission directly or indirectly from Microsoft, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license in the Submission to reproduce, prepare derivative works of, publicly display, publicly perform, and distribute the Submission and such derivative works, and to sublicense any or all of the foregoing rights to third parties.

The BSD license already covers this.

> You grant Microsoft, and those who receive the Submission directly or indirectly from Microsoft, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license under Your patent claims that are necessarily infringed by the Submission or the combination of the Submission with the Project to which it was Submitted to make, have made, use, offer to sell, sell and import or otherwise dispose of the Submission alone or with the Project.

This clause relies upon personally identifying the patent holder after the fact in any legal defence.
Notice that the granting of rights does not go both ways. In that you are not granted a  "perpetual, worldwide, non-exclusive, royalty-free, irrevocable license" to any of Microsoft's patents in return.

> Each party reserves all rights not expressly granted in this Agreement. No additional licenses or rights whatsoever (including, without limitation, any implied licenses) are granted by implication, exhaustion, estoppel or otherwise.

This can easily be challenged via legal action due to the BSD license of the code itself.

> You represent that You are legally entitled to grant the above licenses.

Programmers are not lawyers. Nor do they need to grant licenses to Microsoft.

> You agree to notify Microsoft in writing of any facts or circumstances of which You later become aware that would make Your representations in this Agreement inaccurate in any respect.

But you don't even provide an address.

> You agree that contributions to Projects and information about contributions may be maintained indefinitely and disclosed publicly, including Your name and other information that You submit with Your Submission.

You can't legally opt European users into uses of their personally identifiable information. You have to notify and obtain agreement for every single instance according to GDPR. You cannot use blanket statements like these in legalese.

> the parties consent to exclusive jurisdiction and venue in the Superior Court of King County, Washington. The parties waive all defenses of lack of personal jurisdiction and forum non-conveniens.

This subjects all signed parties to American law. Defences is spelt with a "c" and the paragraph attempts to invalidate the legal rights of non American citizens who are observant and subject of and to different laws and different legislation, according to their local and national jurisdictions.

>  This Agreement is the entire agreement between the parties, and supersedes any and all prior agreements, understandings or communications, written or oral, between the parties relating to the subject matter hereof. This Agreement may be assigned by Microsoft.

Therefore invalidating the BSD license in the root of the project folder. Unless you only use the source code without signing the agreement.

There is also no copy of the Contributor License Agreement in the root of the repository.

Please set up a non-profit and get rid of this ridiculous abomination from the project. The Contributor License Agreement is quite obviously a trap. And only Microsoft employees should ever sign it. And in private.

**Comment by MikeGitb** [comment]
I have signed this in the past (for a different ms repo) and have felt uneasy with this ever since.

I think I'll terminate it and just don't contribute code changes that would require it. I certainly haven't contributed anything major to this repo, so it probably doesn't matter to MS , but I wonder if the cla dissuades some/many other potential contributors (especially professionals) as well.

**Comment by ras0219-msft** [comment]
Thank you for this feedback! We are not currently considering changes to our CLA process at this time.
