### ISSUE TITLE
"annot load image "﻿./darknet/data/obj/images/P1.png STB Reason: can't fopen

### ISSUE THREAD

**Issue by kumarankit1996** [microsoft/vcpkg#6904]
I have been trying to run Yolo v3 using the instruction from: 
https://pjreddie.com/darknet/yolo/
But the error remains the same. I am using google cloud VM instance!
Following are the snippet

1. error
![error](https://user-images.githubusercontent.com/47122709/59524462-93a95780-8e99-11e9-8dbe-af695faad2d3.PNG)
2. data directory
![data directory](https://user-images.githubusercontent.com/47122709/59524478-a2900a00-8e99-11e9-991f-18f5f7f7b76f.PNG)
3. train.txt
![train](https://user-images.githubusercontent.com/47122709/59524482-ab80db80-8e99-11e9-9c61-5e621e90c34b.png)
4. voc.data
![voc data](https://user-images.githubusercontent.com/47122709/59524497-b3d91680-8e99-11e9-9ee7-a941a7266b49.PNG)
5. voc. names
![voc names](https://user-images.githubusercontent.com/47122709/59524525-bb002480-8e99-11e9-971c-ced3307f86ca.PNG)
6. executing code
![execute](https://user-images.githubusercontent.com/47122709/59524571-de2ad400-8e99-11e9-9c27-c93d8fad54ad.PNG)

**Comment by cenit** [comment]
Did you install darknet from vcpkg or from its own repository?

**Comment by cenit** [comment]
Also, can you try PR #6787 and tell me if you encounter the same problem? If so we are in time to fix it there

**Comment by kumarankit1996** [comment]
I tried cloning from darknet the original repository!

**Comment by cenit** [comment]
So this is an issue for the original repository. Sorry :)

**Comment by PhoebeHui** [comment]
Please report the issue to Upstream instead. BTW, you can try darknet provided by vcpkg and see if it meets your requirements.
