### ISSUE TITLE
vcpkg install osg-qt  error 

### ISSUE THREAD

**Issue by kinsung** [microsoft/vcpkg#6909]
vcpkg install osg-qt:x86-windows osg-qt:x64-windows

LINK : fatal error LNK1181: cannot open input file 'optimized.lib'
ninja: build stopped: subcommand failed.

Same thing as these two issue, but they're closed.
https://github.com/microsoft/vcpkg/issues/6436
https://github.com/microsoft/vcpkg/issues/6457

**Comment by JackBoosY** [comment]
This is a zlib issue. When osg builds the debug version, Find-zlib.cmake incorrectly uses the release version of zlib, causing optimized.lib to not be found correctly.

Related: #6883.

**Comment by kinsung** [comment]
How to fix it?

**Comment by JackBoosY** [comment]
You can use this [link](https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/FindZLIB.cmake) to download the latest _FINDZLIB.cmake_ and replace the file in cmake to temporarily solve this problem.

**Comment by kinsung** [comment]
Thank you.
