### ISSUE TITLE
Building package libusb:x64-linux failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by hygxy** [microsoft/vcpkg#6914]
I was trying to install the libfreenect2 via vcpkg on Ubuntu 16.04 and got the following error:

The following packages will be built and installed:
    libfreenect2[core]:x64-linux
  * libusb[core]:x64-linux
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: libusb:x64-linux
Building package libusb[core]:x64-linux...
-- Using cached ~/vcpkg/downloads/libusb-libusb-v1.0.22.tar.gz
-- Using source at ~/vcpkg/buildtrees/libusb/src/v1.0.22-991efb2d0f
-- Building msvc/libusb_static_2015.vcxproj for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: msbuild;~/vcpkg/buildtrees/libusb/x64-linux-rel/v1.0.22-991efb2d0f/msvc/libusb_static_2015.vcxproj;/p:Configuration=Release;/t:Rebuild;/p:Platform=x64;/p:PlatformToolset=external;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No;/p:WindowsTargetPlatformVersion=;/m;/p:WholeProgramOptimization=false
    Working Directory: ~/vcpkg/buildtrees/libusb/x64-linux-rel/v1.0.22-991efb2d0f
    Error code: 1
    See logs for more information:
      ~/vcpkg/buildtrees/libusb/build-x64-linux-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_msbuild.cmake:157 (vcpkg_execute_required_process)
  ports/libusb/portfile.cmake:29 (vcpkg_install_msbuild)
  scripts/ports.cmake:71 (include)

Error: Building package libusb:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libusb:x64-linux
  Vcpkg version: 2018.11.23-unknownhash

I installed vcpkg at location: ~/vcpkg. Besides, I can install libfreenect2 without vcpkg successfully on my platform.

**Comment by wangli28** [comment]
Hi @hygxy, thanks for posting this issue. Can you provide this log?
`~/vcpkg/buildtrees/libusb/build-x64-linux-rel-out.log`

**Comment by hygxy** [comment]
Hi @wangli28 , here is the log file :

Microsoft (R) Build Engine version 16.0.0.0 for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

Parallel builds (/m: or /maxcpucount:) are not yet supported on Mono/Unix. Defaulting to /m:1
Build started 6/15/2019 11:00:33 PM.
__________________________________________________
Project "~/vcpkg/buildtrees/libusb/x64-linux-rel/v1.0.22-991efb2d0f/msvc/libusb_static_2015.vcxproj" (Rebuild target(s)):

~/vcpkg/buildtrees/libusb/x64-linux-rel/v1.0.22-991efb2d0f/msvc/libusb_static_2015.vcxproj(26,3): error MSB4019: The imported project "/Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

Done building project "libusb_static_2015.vcxproj" -- FAILED.

Build FAILED.

~/vcpkg/buildtrees/libusb/x64-linux-rel/v1.0.22-991efb2d0f/msvc/libusb_static_2015.vcxproj(26,3): error MSB4019: The imported project "/Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.19

**Comment by Voskrese** [comment]
`The imported project "/Microsoft.Cpp.Default.props" was not found`

**Comment by PhoebeHui** [comment]
This port is up
