### ISSUE TITLE
cmake link is broken

### ISSUE THREAD

**Issue by Clubbable** [microsoft/vcpkg#6915]
Hi, just today I got the master again, and ran the command "`vcpkg.exe install pcl`"

But there is an error on "downloading cmake"

```
Starting package 1/121: zlib:x86-windows
Building package zlib[core]:x86-windows...
A suitable version of cmake was not found (required v3.14.0). Downloading portable cmake v3.14.0...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.14.0/cmake-3.14.0-win32-x86.zip -> E:\vcpkg-master\downloads\cmake-3.14.0-win32-x86.zip
WinHttpQueryDataAvailable() failed: 12002
```

I can't seem to download the cmake zip from `https://github.com/Kitware/CMake/releases/download/v3.14.0/cmake-3.14.0-win32-x86.zip`, why is that?

**Comment by Voskrese** [comment]
search does not help?
https://github.com/microsoft/vcpkg/search?q=WinHttp&type=Issues

https://github.com/microsoft/vcpkg/issues/702#issuecomment-408908538

**Comment by Clubbable** [comment]
I am actually not behind a corporate network, but the reason it failed seems just to be that I had heavy network traffic. Once I got rid of the networking traffic, download seems to proceed fine.

Also if I just manually download cmake, move it into downloads folder as suggested by https://github.com/microsoft/vcpkg/issues/6227, it also works
