### ISSUE TITLE
[non-Windows] `vcpkg install` fails from within a path containing spaces (parse_shasum_output)

### ISSUE THREAD

**Issue by past-due** [microsoft/vcpkg#6916]
1. Clone the vcpkg repo into a path containing one or more spaces
2. `./bootstrap-vcpkg.sh`
3. Run `vcpkg install <any port>`

(Abbreviated example log output):
```
The following packages will be built and installed:
    glew[core]:x64-osx
Starting package 1/1: glew:x64-osx
Building package glew[core]:x64-osx...
Expected output of the form [hash filename
] (3 tokens), but got
[<hash>  /<snip>/test build/vcpkg/triplets/x64-osx.cmake
] (4 tokens)
```
the `test build` folder contains a space, and this throws off [`parse_shasum_output` in `vcpkg/toolsrc/src/vcpkg/base/hash.cpp`](https://github.com/microsoft/vcpkg/blob/b39b0899cb403aa1f2e86f9e111d16d6f1328737/toolsrc/src/vcpkg/base/hash.cpp#L180)

**Comment by Rastaban** [comment]
fixed with #7216
