### ISSUE TITLE
Add Google Or-Tools

### ISSUE THREAD

**Issue by navidR** [microsoft/vcpkg#692]
https://github.com/google/or-tools

Robust library for operation research.

[edited by @ras0219-msft to fix the link]

**Comment by bangusi** [comment]
@navidR Check your link; it points to a non-existing page ( 404 )

**Comment by navidR** [comment]
Correct link : https://github.com/google/or-tools
Copy this link.

BTW there is definitely something funny going on here, 
[ https://github.com/google/or-tools ](Or-Tools)

**Comment by OlafvdSpek** [comment]
https://github.com/google/or-tools

**Comment by atkawa7** [comment]
@ras0219-msft can be closed now

**Comment by navidR** [comment]
Any update on this? I couldn't find any PR related to this issue.

**Comment by navidR** [comment]
Any explanation?

**Comment by atkawa7** [comment]
@navidR my bad I confused this with ceres-solver which is available

**Comment by atkawa7** [comment]
@navidR you could help build it ?

**Comment by zhihaoy** [comment]
+1

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
