### ISSUE TITLE
Linking fails with capstone (unresolved external symbol)

### ISSUE THREAD

**Issue by VelocityRa** [microsoft/vcpkg#6937]
```bash
set "VCPKG_DEFAULT_TRIPLET=x64-windows"
vcpkg install capstone[x86]
vcpkg integrate install
```

* No CMake code that I should add is printed in the output like with most other libraries.

* If I don't add anything to my project's `target_link_libraries`, linking fails with "unresolved external symbol" errors.
* If I do, it's not found.

* I can _see_ `capstone_dll.lib` built in vcpkg's directories, yet it's not found (I even tried adding `capstone_dll` as a target but the base path is wrong, VS looks for it in the root path, not inside vcpkg's dirs)

Pinging @DanOlivier  and @ras0219-msft who created the port.

**Comment by JackBoosY** [comment]
Hi @VelocityRa, due to capstone doesn't have config.cmake file, you can use find_library to get the port library name, and then use target_link_libraries to use it.

**Comment by VelocityRa** [comment]
@JackBoosY Oh I see,
```cmake
find_library(CAPSTONE_LIBRARY capstone_dll)
```
worked, thanks!
