### ISSUE TITLE
Boost build disables auto-linking

### ISSUE THREAD

**Issue by hkaiser** [Microsoft/vcpkg#694]
What is the rationale of disabling auto-linking for the Boost libraries (`BOOST_ALL_NO_LIB` is defined)? 

We are trying to create a port-file for our library [HPX](https://github.com/STEllAR-GROUP/hpx). So far HPX was relying on auto-linking the boost libraries. Do we have to change our build system in order to be able to be supported by vcpkg?

**Comment by ras0219-msft** [comment]
Hi @hkaiser,

For CMake users, we want to embrace the common, cross-platform core that CMake defines. Therefore, when using CMake, we model the same experience (i.e. no-auto-linking) as on other platforms so you can minimize per-platform differences.

In this case, if I understand your buildsystem correctly, we would unfortunately need to patch the conditional at [1], treating MSVC the same as other compilers. This can be done inside Vcpkg if you'd prefer to avoid any upstream changes; we have utility routines for patching sources in cases like this when needed [2] [3].

As an aside, it should be perfectly safe to always link the libraries that are auto-linked by Boost, so this could be safely changed upstream and result in more functionality (support building boost without auto-linking on Windows) with 3 less lines of platform-specific buildscript.

[1] https://github.com/STEllAR-GROUP/hpx/blob/0cb47e2ae2195b97f8b6ca575f69e8dc7f869614/cmake/HPX_SetupBoost.cmake#L141

[2] https://github.com/Microsoft/vcpkg/blob/master/ports/curl/portfile.cmake#L10-L13
[3] https://github.com/Microsoft/vcpkg/blob/master/ports/curl/0001_cmake.patch

**Comment by ras0219-msft** [comment]
Additionally, it is a core design goal of Vcpkg that we should be able to build your project without any Vcpkg-specific code (you should never need to "test" whether you're under Vcpkg or not). We do, however, often need the ability to customize some features that you may not have exposed previously (cmake config file install directory, for example).

I would be more than happy to help you find ways to add the extensibility points we need in a way that will benefit your other customers as well (customizations they can use) -- without any Vcpkg-specific tests.

**Comment by hkaiser** [comment]
@ras0219-msft Thanks for the feedback. We'll play around with things a bit more and will get back to you asap.

**Comment by ras0219-msft** [comment]
I'll close this since any further issues are unlikely to be on the topic of Boost's auto-linking.

I look forward to seeing the PR!

**Comment by ras0219-msft** [comment]
@hkaiser I've pushed 63454f61 which will override the `Boost_USE_STATIC_LIBS` setting when using Vcpkg, so you should be able to remove your Vcpkg-specific handling of that macro (you can always set it to ON and everything will work fine).

@chwarr I believe this could make Bond easier as well.

**Comment by hkaiser** [comment]
@ras0219-msft thanks, I'll have a look for the next release of HPX. For the current version I'll leave things as is, though.

**Comment by chwarr** [comment]
Thanks, @ras0219-msft. I'll try it out with the next release of Bond.

**Comment by vitalyster** [comment]
> Therefore, when using CMake, we model the same experience (i.e. no-auto-linking) as on other platforms so you can minimize per-platform differences.

Currently, boost libraries are built with tagged layout, so it is different from "other platforms", it should use `--layout=system` to allow build systems to link boost_<libraryname> on all platforms without detecting compiler specific suffixes and so on.
