### ISSUE TITLE
How do I tell vcpkg to utilize multiple CPU cores when building packages?

### ISSUE THREAD

**Issue by TheCodeFiend** [microsoft/vcpkg#6942]
I have Googled, Binged, and StackOverflowed for an answer to this question.  I've wrapped quotes around the words.  Maybe I just don't know the right combinations of keywords, but I can't find anything on this topic.

I have 4 cores, and I want vcpkg to tell the compiler to utilize as many as it can to compile faster.  As an example, let's say I want to install boost:x64-windows.  When I do, it never uses more than 25% CPU.

How do I make this work?

**Comment by Rastaban** [comment]
Vcpkg builds one library at a time and relies on the build system of each library to use multiple cores. In the case of boost libraries there is a significant amount of file copying that would probably not use more than one core which is probably why you mostly see low cpu utilization.  If there is a specific boost library that you think should be using multiple cores that is not then I can have someone look into it.

**Comment by heydojo** [comment]
> I have 4 cores, and I want vcpkg to tell the compiler to utilize as many as it can to compile faster.

It does this by default. Unless...

> As an example, let's say I want to install boost:x64-windows. When I do, it never uses more than 25% CPU.

It's not feasible for a port to do so because: _Insert reason here_.

**Comment by TheCodeFiend** [comment]
> Vcpkg builds one library at a time and relies on the build system of each library to use multiple cores. In the case of boost libraries there is a significant amount of file copying that would probably not use more than one core which is probably why you mostly see low cpu utilization. If there is a specific boost library that you think should be using multiple cores that is not then I can have someone look into it.

Thanks for the information!
