### ISSUE TITLE
[proj4]: x64-windows install no longer produces dlls

### ISSUE THREAD

**Issue by jumpinjackie** [microsoft/vcpkg#6949]
Something in a9303736fdda58cf5ff3ccc969be917580493c91 has broken the `proj4` port for Windows.

It no longer produces dlls for the `x64-windows` triplet. It seems to always want to build as static (evidenced by the lack of `bin` and `debug/bin` folders and way bigger `.lib` files upon completion)

**Comment by JackBoosY** [comment]
#7192 should fix this issue.

**Comment by JackBoosY** [comment]
Hi @jumpinjackie, thanks for reporting this issue.
I've fixed this issue now, please update vcpkg and rebuild proj4.

Thanks.
