### ISSUE TITLE
Add spatialite

### ISSUE THREAD

**Issue by ymartin59** [Microsoft/vcpkg#695]
`spatialite` is a `sqlite` fork with spatial support. It consists in `libspatialite` and `spatialite` command line to open and operate a spatialite database.

Home for `libspatialite`: https://www.gaia-gis.it/fossil/libspatialite/home
Home for `spatialite-tools`: https://www.gaia-gis.it/fossil/spatialite-tools/index

As `sqlite` port is already available, writing port for `spatialite` should not take too much effort.

**Comment by alex85k** [comment]
Working on it, almost ready.

**Comment by alexkaratarakis** [comment]
`spatialite` merged!
