### ISSUE TITLE
vcpkg nghttp2 not working with cmake

### ISSUE THREAD

**Issue by WoutervDijk** [microsoft/vcpkg#6951]
Hey all.

I am trying to get nghttp2 to work with my cross-platform project using vcpkg and cmake. I installed nghttp2 by 
`vcpkg install curl[http2]` on Windows. Which installs both curl and nghttp2. My CMakeLists file is as follows: 
```
cmake_minimum_required (VERSION 3.8)
project ("testProject")
add_subdirectory (testProject)
find_package(CURL REQUIRED)
find_package(unofficial-curlpp CONFIG REQUIRED)
find_package(nlohmann_json REQUIRED)
add_executable(hello testProject/testProject.cpp)
target_include_directories(hello PRIVATE ${CURL_INCLUDE_DIRS})
target_link_libraries(hello unofficial::curlpp::curlpp nlohmann_json::nlohmann_json ${CURL_LIBRARIES})
```
Now I got two problems: First of all, if I try to include the nghttp2 header I get a lot of errors. I have no idea what I am missing:

`#include <nghttp2/nghttp2.h>`
The result is around 128 errors. These are errors in the nghttp2.h file. VS2019 does find header.
Couple of example errors:

 > Severity	Code	Description	Project	File	Line	Suppression State
> Error	C2061	syntax error: identifier 'nghttp2_on_header_callback2'	C:\Documents\C++\testProject\CMakeLists.txt	C:\Documents\C++\vcpkg-master\installed\x64-windows\include\nghttp2\nghttp2.h	2218	
> Error	C2061	syntax error: identifier 'nghttp2_on_header_callback'	C:\Documents\C++\testProject\CMakeLists.txt	C:\Documents\C++\vcpkg-master\installed\x64-windows\include\nghttp2\nghttp2.h	2208	
> Error	C2061	syntax error: identifier 'nghttp2_on_begin_headers_callback'	C:\Documents\C++\testProject\CMakeLists.txt	C:\Documents\C++\vcpkg-master\installed\x64-windows\include\nghttp2\nghttp2.h	2195	
> Error (active)	E0079	expected a type specifier	hello.exe - x64-Debug	C:\Documents\C++\vcpkg-master\installed\x64-windows\include\nghttp2\nghttp2.h	914	
> Error (active)	E0090	function returning function is not allowed	hello.exe - x64-Debug	C:\Documents\C++\vcpkg-master\installed\x64-windows\include\nghttp2\nghttp2.h	915	
> Error (active)	E0020	identifier "nghttp2_data_source_read_callback" is undefined	hello.exe - x64-Debug	C:\Documents\C++\vcpkg-master\installed\x64-windows\include\nghttp2\nghttp2.h	932	
> Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	C:\Documents\C++\testProject\CMakeLists.txt	C:\Documents\C++\vcpkg-master\installed\x64-windows\include\nghttp2\nghttp2.h	915	
> Error	C2143	syntax error: missing ';' before '*'	C:\Documents\C++\testProject\CMakeLists.txt	C:\Documents\C++\vcpkg-master\installed\x64-windows\include\nghttp2\nghttp2.h	915	
> Error	C2143	syntax error: missing ')' before '*'	C:\Documents\C++\testProject\CMakeLists.txt	C:\Documents\C++\vcpkg-master\installed\x64-windows\include\nghttp2\nghttp2.h	915	

Second if I would get this to work. Is there any way to also have libnghttp2_asio built via vcpkg. This is not built by default, source: https://nghttp2.org/documentation/libnghttp2_asio.html. Otherwise this would be a great addition to vcpkg.
Thanks.

**Comment by LilyWangL** [comment]
Hi @WoutervDijk, thanks for posting this issue. Due to port **nghttp2** doesn't provide `-config.cmake` files, so you need use `find_library` and `find_path` to find it. Like this:
```
cmake_minimum_required (VERSION 3.8)

project ("CMakeProject4")

add_executable(CMakeProject4 CMakeProject4/CMakeProject4.cpp)

find_path(nghttp2_INCLUDE_DIRS nghttp2.h PATH_SUFFIXES nghttp2)
set(nghttp2_INCLUDE_DIRS ${nghttp2_INCLUDE_DIRS}/../)
include(SelectLibraryConfigurations)
find_library(nghttp2_LIBRARY_RELEASE NAMES nghttp2)
find_library(nghttp2_LIBRARY_DEBUG NAMES nghttp2 HINTS debug)
select_library_configurations(nghttp2)

target_include_directories(CMakeProject4 PRIVATE ${nghttp2_INCLUDE_DIRS})
target_link_libraries(CMakeProject4 PRIVATE nghttp2)
```
And you need to submit an issue on nghttp2 [source page](https://github.com/nghttp2/nghttp2/issues) to report these errors you encountered when using nghttp2.h.

**Comment by WoutervDijk** [comment]
Thanks you very much for you response @LilyWangL. However, it still does not seem to work unfortunately. I still get around 129 build errors. I used the following cmake code:

```
cmake_minimum_required (VERSION 3.8)

project ("testProject")
add_subdirectory (testProject)
add_executable(hello testProject/testProject.cpp)

find_path(nghttp2_INCLUDE_DIRS nghttp2.h PATH_SUFFIXES nghttp2)
set(nghttp2_INCLUDE_DIRS ${nghttp2_INCLUDE_DIRS}/../)
include(SelectLibraryConfigurations)
find_library(nghttp2_LIBRARY_RELEASE NAMES nghttp2)
find_library(nghttp2_LIBRARY_DEBUG NAMES nghttp2 HINTS debug)
select_library_configurations(nghttp2)

target_include_directories(hello PRIVATE ${nghttp2_INCLUDE_DIRS})
target_link_libraries(hello nghttp2)
```
And the following very short code:
```
#include <nghttp2/nghttp2.h>

int main()
{
	nghttp2_session *x;
	return 0;
}
```
Note that all these errors are generated in the nghttp2.h file except one which is in the testproject.cpp file stating "Cannot open include file: 'nghttp2/nghttp2.h' : No such file or directory". However, Visual studio intellisense does recognize the include of nghttp2.h and code completion therefore works. The builder just doesn't seem to work.
One of the 128 errors in nghttp2.h file is e.g. "syntax error: 'const'" line 2726 code C2059.

As a side note, will vcpkg eventually support libnghttp2_asio, which is included in nghttp2, but not build by default. This would be a great addition to vcpkg. Source: https://nghttp2.org/documentation/libnghttp2_asio.html

**Comment by JackBoosY** [comment]
@WoutervDijk I think these compile errors are source bug, please report the new issue on the [official page](https://github.com/nghttp2/nghttp2/issues).

Thanks.

**Comment by JackBoosY** [comment]
Close this PR until upstream fixes this.

**Comment by antrv** [comment]
```using ssize_t = std::make_signed_t<size_t>;```
before include
```#include <nghttp2/nghttp2.h>```
makes nghttp2.h compilable

**Comment by antrv** [comment]
also `target_link_libraries(hello nghttp2)` must be `target_link_libraries(hello ${nghttp2_LIBRARY_DEBUG})` or `target_link_libraries(hello ${nghttp2_LIBRARY_RELEASE})`

**Comment by dg0yt** [comment]
> also `target_link_libraries(hello nghttp2)` must be `target_link_libraries(hello ${nghttp2_LIBRARY_DEBUG})` or `target_link_libraries(hello ${nghttp2_LIBRARY_RELEASE})`

No. After 
~~~
select_library_configurations(nghttp2)
~~~
it is
~~~
target_link_libraries(hello ${nghttp2_LIBRARY})
~~~
