### ISSUE TITLE
qt5-declarative build failing

### ISSUE THREAD

**Issue by isanych** [microsoft/vcpkg#6962]
```
$ docker run --rm -ti isanych/build-vcpkg:ubuntu
# git clone https://github.com/microsoft/vcpkg.git
# cd vcpkg/
# ./bootstrap-vcpkg.sh
# ./vcpkg install qt5-declarative
...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: /usr/bin/make;qmake_all
    Working Directory: /vcpkg/buildtrees/qt5-declarative/x64-linux-dbg
    Error code: 2
    See logs for more information:
      /vcpkg/buildtrees/qt5-declarative/package-makefiles-x64-linux-dbg-out.log
      /vcpkg/buildtrees/qt5-declarative/package-makefiles-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_qmake.cmake:46 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_build_qmake.cmake:61 (run_jom)
  installed/x64-linux/share/qt5modularscripts/qt_modular_library.cmake:56 (vcpkg_build_qmake)
  installed/x64-linux/share/qt5modularscripts/qt_modular_library.cmake:160 (qt_modular_build_library)
  ports/qt5-declarative/portfile.cmake:5 (qt_modular_library)
  scripts/ports.cmake:71 (include)


Error: Building package qt5-declarative:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qt5-declarative:x64-linux
  Vcpkg version: 2018.11.23-unknownhash

Additionally, attach any relevant sections from the log files above.
```
/vcpkg/buildtrees/qt5-declarative/package-makefiles-x64-linux-dbg-err.log
```
/vcpkg/buildtrees/qt5-declarative/x64-linux-dbg/tools/qml/qmlimportscanner_wrapper.sh: 6: exec: /vcpkg/buildtrees/qt5-declarative/x64-linux-dbg/bin/qmlimportscanner: not found
/vcpkg/installed/x64-linux/share/qt5/debug/mkspecs/features/qt.prf:291: Error parsing JSON at 1:1: illegal value
Project ERROR: Failed to parse qmlimportscanner output.
make[1]: *** [sub-qml-qmake_all] Error 3
make: *** [sub-tools-qmake_all] Error 2
```
/vcpkg/buildtrees/qt5-declarative/package-makefiles-x64-linux-dbg-out.log
```
cd src/ && /vcpkg/installed/x64-linux/tools/qt5/qmake -o Makefile /vcpkg/buildtrees/qt5-declarative/src/5.12.3-93b4ba5375/src/src.pro CONFIG-=release CONFIG+=debug CONFIG+=staticlib -qtconf /vcpkg/buildtrees/qt5-declarative/x64-linux-dbg/qt.conf
cd src/ && /usr/bin/make -f Makefile qmake_all
...
cd qmlimportscanner/ && /vcpkg/installed/x64-linux/tools/qt5/qmake -o Makefile /vcpkg/buildtrees/qt5-declarative/src/5.12.3-93b4ba5375/tools/qmlimportscanner/qmlimportscanner.pro CONFIG-=release CONFIG+=debug CONFIG+=staticlib -qtconf /vcpkg/buildtrees/qt5-declarative/x64-linux-dbg/qt.conf
cd qmlimportscanner/ && /usr/bin/make -f Makefile qmake_all
make[2]: Entering directory '/vcpkg/buildtrees/qt5-declarative/x64-linux-dbg/tools/qmlimportscanner'
make[2]: Nothing to be done for 'qmake_all'.
make[2]: Leaving directory '/vcpkg/buildtrees/qt5-declarative/x64-linux-dbg/tools/qmlimportscanner'
cd qmlcachegen/ && /vcpkg/installed/x64-linux/tools/qt5/qmake -o Makefile /vcpkg/buildtrees/qt5-declarative/src/5.12.3-93b4ba5375/tools/qmlcachegen/qmlcachegen.pro CONFIG-=release CONFIG+=debug CONFIG+=staticlib -qtconf /vcpkg/buildtrees/qt5-declarative/x64-linux-dbg/qt.conf
cd qmlcachegen/ && /usr/bin/make -f Makefile qmake_all
make[2]: Entering directory '/vcpkg/buildtrees/qt5-declarative/x64-linux-dbg/tools/qmlcachegen'
make[2]: Nothing to be done for 'qmake_all'.
make[2]: Leaving directory '/vcpkg/buildtrees/qt5-declarative/x64-linux-dbg/tools/qmlcachegen'
cd qml/ && /vcpkg/installed/x64-linux/tools/qt5/qmake -o Makefile /vcpkg/buildtrees/qt5-declarative/src/5.12.3-93b4ba5375/tools/qml/qml.pro CONFIG-=release CONFIG+=debug CONFIG+=staticlib -qtconf /vcpkg/buildtrees/qt5-declarative/x64-linux-dbg/qt.conf
Makefile:147: recipe for target 'sub-qml-qmake_all' failed
make[1]: Leaving directory '/vcpkg/buildtrees/qt5-declarative/x64-linux-dbg/tools'
Makefile:67: recipe for target 'sub-tools-qmake_all' failed
```
Dockerfile could be found in #6959
In order to fix it I have to add exec flag to qt5 tools: `chmod +x /vcpkg/installed/x64-linux/tools/qt5/*` (#6959) and to change `qmake_all` to `all` in https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_build_qmake.cmake

**Comment by JackBoosY** [comment]
Not working:
>/home/master/vcpkg/buildtrees/qt5-declarative/x64-linux-dbg/tools/qml/qmlimportscanner_wrapper.sh: 6: exec: /home/master/vcpkg/buildtrees/qt5-declarative/x64-linux-dbg/bin/qmlimportscanner: not found
/home/master/vcpkg/installed/x64-linux/share/qt5/debug/mkspecs/features/qt.prf:291: Error parsing JSON at 1:1: illegal value
Project ERROR: Failed to parse qmlimportscanner output.
make[1]: *** [sub-qml-qmake_all] Error 3
make: *** [sub-tools-qmake_all] Error 2

**Comment by cenit** [comment]
Same problem here. Anyone already bisected damaging commit?

**Comment by JackBoosY** [comment]
By executing the command `make` in _buildtrees / qt5-declarative / x64-linux-debug_, the executables will be successfully generated, but why?

**Comment by heydojo** [comment]
I'm not questioning this report as it is valid.

Just pointing out that Ubuntu has up to date Qt binaries (including Qt plugins) so you really don't need to build Qt using vcpkg to use it in a docker image.
You should install the parts of Qt you need using apt-get (after and apt-get update of course) for instance, instead of trying to build them.

My assessment of Qt in vcpkg is that it is "alpha" quality in that there are features missing and the ports are not quite complete but basic functionality is there. In short, it's not really ready for a production system and until 5.12.4 lands in vcpkg there now exist some unpatched security issues in 5.12.3.
Qt in vcpkg also arbitrarily builds the postgres db plugin and sqlite (you only need sqlite TBH) and it's a very old version of postgres to boot.
The version of openssl in vcpkg which Qt is built against is also not only out of date but is EOL at the end of this year.

So, honestly; go with Ubuntu's prebuilt binaries instead if you can. Your docker image will certainly be smaller.

**Comment by isanych** [comment]
@heydojo, I cannot use ubuntu (and especially fresh ubuntu) for building our build dependencies, I was using it only as easy to reproduce example. And unfortunately I also need qtwebengine which is not in vcpkg (hopefully yet). For now I'm building all dependencies via vcpkg and building qt separately (had to generate proper pkgconfig files in vcpkg for that - will create merge request at some point). But I hope that at some point I will be able to build all necessary libraries via vcpkg only.

**Comment by heydojo** [comment]
@isanych that explains it.
WebEngine was in vcpkg once upon a time but was removed. The maintenance burden involved I imagine being the reason (4-6 hrs build time currently if you don't have the pre-compiled headers bug fixed.)

If you are interested, I have a WebEngine vcpkg port in a tree for one of my forks:
https://gitlab.com/TW3/bhawk/tree/staging/ports/vcpkg
There are graphical bugs though (svg rendering IIRC) and I'm waiting for Qt 5.12.4 to land in vcpkg to be able to confirm it's not been fixed. YMMV.

**Comment by JackBoosY** [comment]
Hi everyone, thanks for reporting this issue!
I've fixed qt5-linux build, please update vcpkg and rebuild qt5.

Thanks.
