### ISSUE TITLE
[Windows] case-insensitive filesystem

### ISSUE THREAD

**Issue by Voskrese** [microsoft/vcpkg#6965]
Windows case-insensitive filesystem **problem**

I try to **port lasem**, I get an error

```
[125/138] Generating resources.h with a meson_exe.py custom command.
../src/buf-master-169b84daba/tests/resources.gresource.xml: Child process exited with code -1073741511.
[126/138] Generating resources.c with a meson_exe.py custom command.
../src/buf-master-169b84daba/tests/resources.gresource.xml: Child process exited with code -1073741511.
```

I could not understand for a long time, but I kind of found
example
`git clone https://github.com/GNOME/lasem.git`

> warning: the following paths have collided (e.g. case-sensitive paths
> on a case-insensitive filesystem) and only one from the same
> colliding group is in the working tree:

```
  'tests/data/mathml/testsuite/Presentation/TablesAndMatrices/mtable/mtableAalign3.png'
  'tests/data/mathml/testsuite/Presentation/TablesAndMatrices/mtable/mtableaalign3.png'
```

can make default folder **only buildtrees** case sensitive?

code on powershell
for the current folder and the following ones, from the place where we are

`(Get-ChildItem -Recurse -Directory).FullName | ForEach-Object {fsutil.exe file setCaseSensitiveInfo $_ enable}`

disable
`(Get-ChildItem -Recurse -Directory).FullName | ForEach-Object {fsutil.exe file setCaseSensitiveInfo $_ disable}`

**Comment by JackBoosY** [comment]
Since git is **case** sensitive, but windows **doesn't**, when you clone lasem in windows, it will **overwrite** case-sensitive files/directories. Because this is a Windows feature, I think your solution won't solve this problem. The only workaround is to notify the upstream to rename these files/directories.

**Comment by Voskrese** [comment]
Yes, I tried many different ways and methods, it did not help

windows does not work at all with the case-sensitive
