### ISSUE TITLE
ITK: wrong path for some libraries

### ISSUE THREAD

**Issue by Athius** [microsoft/vcpkg#6975]
Hi,
I successfully build and install itk, vtk, vtk-dicom and qt on Windows 10 using the following command:
    ` .\vcpkg.exe install --recurse itk[vtk]:x64-windows vtk-dicom[gdcm]:x64-windows vtk[qt,python]:x64-windows`

I try now to build a simple program (empty main that depends on ITK). The CMake configuration succeed (Visual Studio 2017 x64 solution) but when I try build the program, I have the following error:
    `LINK : fatal error LNK1104: impossible d'ouvrir le fichier '\lib\double-conversion.lib'`

When I open the project properties I see many libraries with not the full path (in bold):

**\lib\double-conversion.lib**
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\itksys-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\itkvnl_algo-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\itkvnl-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\itkv3p_netlib-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\itknetlib-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\itkvcl-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\itkNetlibSlatec-5.0.lib
**\debug\lib\zlibd.lib**
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKMetaIO-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKPath-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKLabelMap-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKPolynomials-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKBiasCorrection-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKDICOMParser-5.0.lib
**\lib\expat.lib**
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\itkgdcmDICT-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\itkgdcmMSFF-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKznz-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKniftiio-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKgiftiio-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\libhdf5_D.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\libhdf5_cpp_D.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOBioRad-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOBruker-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOCSV-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOGE-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOHDF5-5.0.lib
**\lib\jpeg.lib**
**\debug\lib\jpegd.lib**
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\itkopenjpeg-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOJPEG2000-5.0.lib
**\lib\tiff.lib**
**\debug\lib\tiffd.lib**
**\lib\lzma.lib**
**\debug\lib\lzmad.lib**
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOLSM-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\itkminc2-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOMINC-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOMRC-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKNrrdIO-5.0.lib
**\lib\libpng16.lib**
**\debug\lib\libpng16d.lib**
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOSiemens-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOSpatialObjects-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOStimulate-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKTransformFactory-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOTransformHDF5-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOTransformInsightLegacy-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOTransformMatlab-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKKLMRegionGrowing-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\itklbfgs-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKOptimizersv4-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKTestKernel-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKVideoIO-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKVtkGlue-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKWatersheds-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\libszip_D.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOIPL-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOXML-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOTransformBase-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKOptimizers-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOBMP-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOGDCM-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\itkgdcmIOD-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\itkgdcmDSED-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\lib\expat.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\itkgdcmCommon-5.0.lib
crypt32.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\itkgdcmjpeg8-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\itkgdcmjpeg12-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\itkgdcmjpeg16-5.0.lib
openjp2.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\itkgdcmcharls-5.0.lib
rpcrt4.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOGIPL-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOJPEG-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOTIFF-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOMeshBYU-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOMeshFreeSurfer-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOMeshGifti-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOMeshOBJ-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOMeshOFF-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOMeshVTK-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOMeshBase-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKQuadEdgeMesh-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOMeta-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIONIFTI-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIONRRD-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOPNG-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOVTK-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKIOImageBase-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKVideoCore-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKVTK-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\vtkRenderingOpenGL2-8.2.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\vtkInteractionWidgets-8.2.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\vtkInteractionStyle-8.2.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\vtkImagingSources-8.2.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\vtkIOImage-8.2.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\zlibd.lib
comctl32.lib
wsock32.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\vtkRenderingFreeType-8.2.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\freetyped.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\vtkRenderingCore-8.2.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\vtkFiltersSources-8.2.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\vtkFiltersGeneral-8.2.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\vtkFiltersCore-8.2.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\vtkCommonExecutionModel-8.2.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\vtkCommonDataModel-8.2.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\vtkCommonTransforms-8.2.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\vtkCommonMisc-8.2.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\vtkCommonMath-8.2.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\vtkCommonCore-8.2.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKStatistics-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKSpatialObjects-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKMesh-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKTransform-5.0.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKCommon-5.0.lib
ws2_32.lib
Psapi.lib
D:\LIBS\vcpkg\installed\x64-windows\debug\lib\ITKVNLInstantiation-5.0.lib
kernel32.lib
user32.lib
gdi32.lib
winspool.lib
shell32.lib
ole32.lib
oleaut32.lib
uuid.lib
comdlg32.lib
advapi32.lib

I don't know if it's a ITK issue or vcpkg.

The correct path of those libraries are the path where I install vcpkg (in my case: D:\LIBS\vcpkg\installed\x64-windows)

Did someone as the same error ? 

Thank you

**Comment by wangli28** [comment]
Hi @Athius, are you using cmake project or MSVC project? How do you set up your project? I can't repro this error with cmake project. This is my demo:

**CMakeLists.txt**
```
cmake_minimum_required (VERSION 3.8)

# Add source to this project's executable.
add_executable (CMakeProject4 "CMakeProject4.cpp" "CMakeProject4.h")

# TODO: Add tests and install targets if needed.

SET(ITK_DIR "F:\\test\\vcpkg\\installed\\x64-windows\\share\\itk")

find_package(ITK CONFIG REQUIRED)
# Note: 80 target(s) were omitted.
target_link_libraries(CMakeProject4 PRIVATE ITKVTK ITKznz itksys itkvcl)
```
**CMakeSettings.json**
```
{
  "configurations": [
    {
      "name": "x64-Debug",
      "generator": "Visual Studio 15 2017",
      "configurationType": "Debug",
      "inheritEnvironments": [
        "msvc_x64_x64"
      ],
      "buildRoot": "${env.USERPROFILE}\\CMakeBuilds\\${workspaceHash}\\build\\${name}",
      "installRoot": "${env.USERPROFILE}\\CMakeBuilds\\${workspaceHash}\\install\\${name}",
      "cmakeCommandArgs": "",
      //"buildCommandArgs": "-v",
      "ctestCommandArgs": "",
      "variables": [
        {
          "name": "CMAKE_TOOLCHAIN_FILE",
          "value": "F:\\test\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake"
        }
      ]
    }
  ]
}
```

I built the program successfully.
```
>------ Build started: Project: CMakeLists, Configuration: Debug ------
  Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
  Copyright (C) Microsoft Corporation. All rights reserved.
  
  Build started 6/21/2019 8:58:44 AM.
  Project "C:\Users\vwangli\CMakeBuilds\ff803e27-f0c4-433a-a66e-d231757f901c\build\x64-Debug\CMakeProject4\CMakeProject4.vcxproj" on node 1 (default targets).
  Project "C:\Users\vwangli\CMakeBuilds\ff803e27-f0c4-433a-a66e-d231757f901c\build\x64-Debug\CMakeProject4\CMakeProject4.vcxproj" (1) is building "C:\Users\vwangli\CMakeBuilds\ff803e27-f0c4-433a-a66e-d231757f901c\build\x64-Debug\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
  InitializeBuildStatus:
    Creating "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
  CustomBuild:
    All outputs are up-to-date.
  FinalizeBuildStatus:
    Deleting file "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
    Touching "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
  Done Building Project "C:\Users\vwangli\CMakeBuilds\ff803e27-f0c4-433a-a66e-d231757f901c\build\x64-Debug\ZERO_CHECK.vcxproj" (default targets).
  InitializeBuildStatus:
    Creating "CMakeProject4.dir\Debug\CMakeProject4.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
  CustomBuild:
    All outputs are up-to-date.
  VcpkgTripletSelection:
    Not using Vcpkg because VcpkgEnabled is "false"
  ClCompile:
    All outputs are up-to-date.
  Link:
    All outputs are up-to-date.
    CMakeProject4.vcxproj -> C:\Users\vwangli\CMakeBuilds\ff803e27-f0c4-433a-a66e-d231757f901c\build\x64-Debug\CMakeProject4\Debug\CMakeProject4.exe
  PostBuildEvent:
    setlocal
    powershell -noprofile -executionpolicy Bypass -file F:/test/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/Users/vwangli/CMakeBuilds/ff803e27-f0c4-433a-a66e-d231757f901c/build/x64-Debug/CMakeProject4/Debug/CMakeProject4.exe -installedDir F:/test/vcpkg/installed/x86-windows/debug/bin -OutVariable out
    if %errorlevel% neq 0 goto :cmEnd
    :cmEnd
    endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
    :cmErrorLevel
    exit /b %1
    :cmDone
    if %errorlevel% neq 0 goto :VCEnd
    :VCEnd
  FinalizeBuildStatus:
    Deleting file "CMakeProject4.dir\Debug\CMakeProject4.tlog\unsuccessfulbuild".
    Touching "CMakeProject4.dir\Debug\CMakeProject4.tlog\CMakeProject4.lastbuildstate".
  Done Building Project "C:\Users\vwangli\CMakeBuilds\ff803e27-f0c4-433a-a66e-d231757f901c\build\x64-Debug\CMakeProject4\CMakeProject4.vcxproj" (default targets).
  
  Build succeeded.
      0 Warning(s)
      0 Error(s)
  
  Time Elapsed 00:00:01.21

Build succeeded.
```

**Comment by Athius** [comment]
Hi @wangli28,
I generate the Visual Studio solution with CMake GUI or inside Visual Code, I generate a Ninja Makefile.

I use this CMakeLists.txt file:

```
cmake_minimum_required(VERSION 3.11)

project(TestQt_VTK_ITK)

# ITK
find_package(ITK REQUIRED)
include(${ITK_USE_FILE})

add_executable(${PROJECT_NAME} src/main.cpp)
target_link_libraries(${PROJECT_NAME} PRIVATE ${ITK_LIBRARIES})

set_target_properties(${PROJECT_NAME} PROPERTIES
		CXX_STANDARD 14
		CXX_STANDARD_REQUIRED YES
		CXX_EXTENSIONS NO)
target_include_directories(${PROJECT_NAME} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/include ${CMAKE_CURRENT_BINARY_DIR} ${QtCore_location} ${QtWidgets_location})
```
In Visual Studio 2017 (community version), I obtain this:

```1>------ Début de la génération : Projet : ZERO_CHECK, Configuration : Debug x64 ------
2>------ Début de la génération : Projet : TestQt_VTK_ITK, Configuration : Debug x64 ------
2>main.cpp
2>LINK : fatal error LNK1104: impossible d'ouvrir le fichier '\lib\double-conversion.lib'
2>Génération du projet "TestQt_VTK_ITK.vcxproj" terminée -- ÉCHEC.
========== Génération : 1 a réussi, 1 a échoué, 0 mis à jour, 0 a été ignoré ==========
```

And with Ninja (inside Visual Code 1.35.1) I obtain this:

```[build] Starting build
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --build d:/Projects/TestQt_VTK_ITK/build --config Debug --target all -- -j 14
[build] ninja: error: '/lib/double-conversion.lib', needed by 'TestQt_VTK_ITK.exe', missing and no known rule to make it
[build] Build finished with exit code 1
```

**Comment by Neumann-A** [comment]
`target_link_libraries(${PROJECT_NAME} PRIVATE ${ITK_LIBRARIES})`

vs. 

`target_link_libraries(CMakeProject4 PRIVATE ITKVTK ITKznz itksys itkvcl)`

@Athius Use the ITK targets instead of `ITK_LIBRARIES`

**Comment by Athius** [comment]
I change the target_link_libraries and it's working but it's not a normal behavior: on the documentation of ITK 5.0 (book 1 section 2.5.1 Hello World) they use the ITK_LIBRARIES variable.
@Neumann-A where did you find the variables ITKVTK, ITKznz, etc...?

**Comment by Neumann-A** [comment]
>  not a normal behavior

probably outdated documentation without taking modern CMake into account. 

> where did you find the variables ITKVTK, ITKznz, etc..

I just copied wangli28 code here. If you want to know all the targets there should be a` itk-target-(release|debug).cmake` (or similar) in `<vcpkg-root>/installed/<triplet>/share/itk`

**Comment by Athius** [comment]
I succeed to build my app by using each targets.

Thanks again for your answers
