### ISSUE TITLE
Cannot open include file: 'GL/glew.h' while installing vtk

### ISSUE THREAD

**Issue by giorgk** [microsoft/vcpkg#6976]
Hi I'm trying to install pcl which seems to depend on vtk. 
The failed package and vcpkg version is
Package: vtk:x86-windows
Vcpkg version: 2018.11.23-nohash
The file 
vcpkg\buildtrees\vtk\x86-windows-dbg\ThirdParty\glew\vtk_glew.h 
has the following line:
`# include <GL/glew.h>` which according to log file breaks the building
```
vcpkg\buildtrees\vtk\x86-windows-dbg\ThirdParty\glew\vtk_glew.h(40): fatal error C1083: Cannot open include file: 'GL/glew.h': No such file or directory
ninja: build stopped: subcommand failed.
```

However when I include the GL/glew.h file in a project with VS2017 it compiles fine
Any help?
Thank you

**Comment by fps92** [comment]
Same problem here #7111

**Comment by PhoebeHui** [comment]
@giorgk, can you try the solution mentioned in https://github.com/microsoft/vcpkg/issues/7111, does the problem persist for you?

**Comment by DeveloperPaul123** [comment]
This happened to me as well today with the same failure (using cmake `3.15.1`). Haven't tried again after downgrading CMake as suggested in #7111. 

````
OS: Windows 10
Package: vtk:x64-windows
Vcpkg version: 2019.07.18-nohash
````

**Comment by PhoebeHui** [comment]
This issue tracked by https://github.com/microsoft/vcpkg/issues/7519.
