### ISSUE TITLE
Cpprestsdk build fails in VS2017

### ISSUE THREAD

**Issue by Alximik90** [microsoft/vcpkg#6978]
All dependencies are build successfully, but linker fails

[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/3310935/config-x86-windows-out.log)
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3310936/install-x86-windows-dbg-out.log)

**Comment by wangli28** [comment]
Hi @Alximik90, I can't reproduce this issue locally. I installed it successfully with Visual Studio 2017 and VCPKG latest source. can you try vcpkg latest revision?

PS F:\test\vcpkg> .\vcpkg.exe install cpprestsdk
The following packages will be built and installed:
  * brotli[core]:x86-windows
    cpprestsdk[brotli,core,default-features,websockets]:x86-windows
  * websocketpp[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: brotli:x86-windows
......
Starting package 3/3: cpprestsdk:x86-windows
Building package cpprestsdk[brotli,core,default-features,websockets]:x86-windows...
-- Downloading https://github.com/Microsoft/cpprestsdk/archive/v2.10.13.tar.gz...
-- Extracting source F:/test/vcpkg/downloads/Microsoft-cpprestsdk-v2.10.13.tar.gz
-- Using source at F:/test/vcpkg/buildtrees/cpprestsdk/src/v2.10.13-fe1b687772
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: F:/test/vcpkg/packages/cpprestsdk_x86-windows/share/cpprestsdk/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package cpprestsdk[brotli,core,default-features,websockets]:x86-windows... done
Installing package cpprestsdk[brotli,core,default-features,websockets]:x86-windows...
Installing package cpprestsdk[brotli,core,default-features,websockets]:x86-windows... done
Elapsed time for package cpprestsdk:x86-windows: 1.412 min

Total elapsed time: 1.908 min

**Comment by kapilash** [comment]
I am facing the same issue on one my development environment.  I could not repro the issue in the other.

FWIW, I cleaned up everything and reinstalled. 

```
ws_client_wspp.cpp.obj : error LNK2019: unresolved external symbol SSLv3_method referenced in function "public: __cdecl boost::asio::ssl::context::context(enum boost::asio::ssl::context_base::method)" (??0context@ssl@asio@boost@@QEAA@W4method@context_base@123@@Z)
ws_client_wspp.cpp.obj : error LNK2019: unresolved external symbol SSLv3_server_method referenced in function "public: __cdecl boost::asio::ssl::context::context(enum boost::asio::ssl::context_base::method)" (??0context@ssl@asio@boost@@QEAA@W4method@context_base@123@@Z)
ws_client_wspp.cpp.obj : error LNK2019: unresolved external symbol SSLv3_client_method referenced in function "public: __cdecl boost::asio::ssl::context::context(enum boost::asio::ssl::context_base::method)" (??0context@ssl@asio@boost@@QEAA@W4method@context_base@123@@Z)
ws_client_wspp.cpp.obj : error LNK2019: unresolved external symbol SSLv23_method referenced in function "public: __cdecl boost::asio::ssl::context::context(enum boost::asio::ssl::context_base::method)" (??0context@ssl@asio@boost@@QEAA@W4method@context_base@123@@Z)
ws_client_wspp.cpp.obj : error LNK2019: unresolved external symbol SSLv23_server_method referenced in function "public: __cdecl boost::asio::ssl::context::context(enum boost::asio::ssl::context_base::method)" (??0context@ssl@asio@boost@@QEAA@W4method@context_base@123@@Z)
ws_client_wspp.cpp.obj : error LNK2019: unresolved external symbol SSLv23_client_method referenced in function "public: __cdecl boost::asio::ssl::context::context(enum boost::asio::ssl::context_base::method)" (??0context@ssl@asio@boost@@QEAA@W4method@context_base@123@@Z)
x509_cert_utilities.cpp.obj : error LNK2019: unresolved external symbol X509_STORE_CTX_get_chain referenced in function "bool __cdecl web::http::client::details::verify_cert_chain_platform_specific(class boost::asio::ssl::verify_context &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?verify_cert_chain_platform_specific@details@client@http@web@@YA_NAEAVverify_context@ssl@asio@boost@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
Binaries\cpprest_2_10d.dll : fatal error LNK1120: 18 unresolved externals
ninja: build stopped: subcommand failed.
```

**Comment by kapilash** [comment]
I had openssl binaries installed on my system. I uninstalled them, tried building again and the issue got resolved.  Looks like linker was trying to use the libraries from the installed location.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
