### ISSUE TITLE
Failed to install gtk

### ISSUE THREAD

**Issue by spartan-117** [microsoft/vcpkg#6979]
Hello I just discovered vcpkg and I am really happabout what it does.
I wish to install gtkmm but it fail building gtk
Here what I've got :
>vcpkg install gtkmm:x64-windows
[source-gen-err.log](https://github.com/microsoft/vcpkg/files/3311759/source-gen-err.log)

The following packages will be built and installed:
  * atkmm[core]:x64-windows
  * cairomm[core]:x64-windows
  * gtk[core]:x64-windows
    gtkmm[core]:x64-windows
  * pangomm[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/5: gtk:x64-windows
Building package gtk[core]:x64-windows...
-- Using cached D:/qhm11/Documents/NSS/GTK/vcpkg/downloads/gtk+-3.22.19.tar.xz
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: D:/qhm11/Documents/NSS/GTK/vcpkg/downloads/tools/python/python3/python.exe;D:/qhm11/Documents/NSS/GTK/vcpkg/installed/x64-windows/tools/glib/gdbus-codegen;--interface-prefix;org.Gtk.;--c-namespace;_Gtk;--generate-c-code;gtkdbusgenerated;./gtkdbusinterfaces.xml
    Working Directory: D:/qhm11/Documents/NSS/GTK/vcpkg/buildtrees/gtk/src/gtk+-3.22.19/gtk
    Error code: 1
    See logs for more information:
      D:\qhm11\Documents\NSS\GTK\vcpkg\buildtrees\gtk\source-gen-err.log

Call Stack (most recent call first):
  ports/gtk/portfile.cmake:19 (vcpkg_execute_required_process)
  scripts/ports.cmake:71 (include)

Error: Building package gtk:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: gtk:x64-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by wangli28** [comment]
Hi @spartan-117, could you provide your environment information and VS version? I installed **gtkmm:x64-windows** successfully with Visual Studio 2017 and VCPKG latest source.

**Comment by SinisterMJ** [comment]
I got the same error, with VS2019 Community and VS2017 Community installed on my system.

**Comment by spartan-117** [comment]
H @wangli28 thank you for the quick response.
I'm using VS 2019 community 16.1.3 with cmake 14.3.
I also tried at work today where it's a enterprise vs 2019 trial.
I've got same error with gtk and gtk:x64-windows

**Comment by wangli28** [comment]
PR #7051 has been merged. This issue has been fixed. So I am closing this issue for now.
