### ISSUE TITLE
[libxlsxwriter] upgraded to 0.8.7

### ISSUE THREAD

**Issue by jmcnamara** [microsoft/vcpkg#6982]
Hi,

I've release a new version of libxlsxwriter, 0.8.7, https://github.com/jmcnamara/libxlsxwriter

If I want to update the version in vcpkg should I submit a pull request? Something like the following?:

```diff
diff --git a/ports/libxlsxwriter/CONTROL b/ports/libxlsxwriter/CONTROL
index 0cf7ed96..8848ce5f 100644
--- a/ports/libxlsxwriter/CONTROL
+++ b/ports/libxlsxwriter/CONTROL
@@ -1,4 +1,4 @@
 Source: libxlsxwriter
-Version: 0.8.6-1
+Version: 0.8.7-1
 Description: Libxlsxwriter is a C library that can be used to write text, numbers, formulas and hyperlinks to multiple worksheets in an Excel 2007+ XLSX file.
 Build-Depends: zlib
diff --git a/ports/libxlsxwriter/portfile.cmake b/ports/libxlsxwriter/portfile.cmake
index f60d2f88..d56b521d 100644
--- a/ports/libxlsxwriter/portfile.cmake
+++ b/ports/libxlsxwriter/portfile.cmake
@@ -3,8 +3,8 @@ include(vcpkg_common_functions)
 vcpkg_from_github(
     OUT_SOURCE_PATH SOURCE_PATH
     REPO jmcnamara/libxlsxwriter
-    REF RELEASE_0.8.6
-    SHA512 60822dc5f87531edc97cf774e234f25229a605d4430061c24b95c387318e6e05dde1b0f2f433cea14c6f84ee901c1dffe0d174bfd7e2a8459f59bcee900097db
+    REF RELEASE_0.8.7
+    SHA512 20bf09f084808a8db00315848213c550fb809b587ea49ce3b25b310de981c176a44c518452507b6e00ca3f0a8e0056d88a6f575c031d54aa68791575cb9ab285
        HEAD_REF master
        PATCHES
         0001-fix-build-error.patch
```

John

**Comment by Voskrese** [comment]
edit it yourself in the browser

https://github.com/microsoft/vcpkg/blob/master/ports/libxlsxwriter/portfile.cmake
https://github.com/microsoft/vcpkg/blob/master/ports/libxlsxwriter/CONTROL

![2019-06-21_092035](https://user-images.githubusercontent.com/10104740/59890994-02d8fb80-9406-11e9-9690-47647166b7ce.png)

**Comment by jmcnamara** [comment]
@Voskrese Thanks. 

I guess my question is: should I submit a Pull Request after I make the changes? Is that the standard procedure for updating a port/package?

**Comment by jmcnamara** [comment]
@Voskrese If you get a chance could you look at my PR:  #6992

**Comment by Voskrese** [comment]
https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/3764/artifacts?artifactName=x64-windows%20port%20build%20failure%20logs&api-version=5.1-preview.5&%24format=zip

`buildtrees\libxlsxwriter\src\ease_0.8.7-5d13031923\include\xlsxwriter\utility.h(20): fatal error C1083: Cannot open include file: 'strings.h': No such file or directory`

**Comment by jmcnamara** [comment]
@Voskrese Thank you. I'll fix that and resubmit.

**Comment by jmcnamara** [comment]
@Voskrese I've fixed that issue and re-did the PR, if you have time to have a look.

**Comment by Voskrese** [comment]
I'm not deciding anything here
contact the person who accepts the merger

![2019-06-26_115819](https://user-images.githubusercontent.com/10104740/60150140-fab7fc00-9809-11e9-8782-7b1ea8a21e02.png)
