### ISSUE TITLE
Build Failed gtk:x64-windows

### ISSUE THREAD

**Issue by flametrav** [microsoft/vcpkg#6984]
![Capture](https://user-images.githubusercontent.com/42415593/59921872-c2927100-9437-11e9-919d-14334968a3ab.PNG)

I got this when I tried to install gtk
Please help

**Comment by SinisterMJ** [comment]
Got the same error, the data in the log is:

Traceback (most recent call last):
  File "D:/Development/vcpkg/installed/x64-windows/tools/glib/gdbus-codegen", line 37, in <module>
    from codegen import codegen_main
ModuleNotFoundError: No module named 'codegen'


The last few lines before this in the build:

Building package gtk[core]:x64-windows...
-- Downloading https://ftp.gnome.org/pub/gnome/sources/gtk+/3.22/gtk+-3.22.19.tar.xz...
-- Extracting source D:/Development/vcpkg/downloads/gtk+-3.22.19.tar.xz
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: D:/Development/vcpkg/downloads/tools/python/python3/python.exe;D:/Development/vcpkg/installed/x64-windows/tools/glib/gdbus-codegen;--interface-prefix;org.Gtk.;--c-namespace;_Gtk;--generate-c-code;gtkdbusgenerated;./gtkdbusinterfaces.xml
    Working Directory: D:/Development/vcpkg/buildtrees/gtk/src/gtk+-3.22.19/gtk
    Error code: 1
    See logs for more information:
      D:\Development\vcpkg\buildtrees\gtk\source-gen-err.log

Call Stack (most recent call first):
  ports/gtk/portfile.cmake:19 (vcpkg_execute_required_process)
  scripts/ports.cmake:71 (include)

**Comment by yonamine** [comment]
I got the same error.... any clue?

**Comment by PeisongXiao** [comment]
I got the same problem and I looked into it. It seems that there's something wrong with the codegen module in python. And I tried to install that module, but after that, still no codegen_main. Anyone with better ideas?

**Comment by PeisongXiao** [comment]
Good news: I got it working by removing the vcpkg\downloads\tools\python\python3\python37._pth file

**Comment by rivy** [comment]
Same here... removal of "[vcpkg.root]\downloads\tools\python\python3\python37._pth" allows successful compile/install completion.

**Comment by yonamine** [comment]
> Good news: I got it working by removing the vcpkg\downloads\tools\python\python3\python37._pth file

This workaround worked here.
Thanks

**Comment by wangli28** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
