### ISSUE TITLE
User-wide integration not working with new windows terminal

### ISSUE THREAD

**Issue by PankajBhojwani** [microsoft/vcpkg#6985]
Hello! I am running Microsoft Windows 10 Enterprise Insider Preview. I managed to install the libraries I wanted using vcpkg ([cpprestsdk](https://github.com/Microsoft/cpprestsdk)). I also used user-wide integration. 

When I create a new project in Visual Studio 2019, I can go ahead and #include the cpprestsdk files that I want and it works fine. However, when I open up the [Windows Terminal](https://github.com/microsoft/terminal) project, I cannot seem to do the same - I get a "cannot open source file" error. 

Any idea how I can fix this?

EDIT: I tried the [Linking Nuget file](https://vcpkg.readthedocs.io/en/latest/users/integration/) procedure and that did not work either.

**Comment by Voskrese** [comment]
full log error???

**Comment by PankajBhojwani** [comment]
I am not sure where to find that/what you mean by that, do you want the full error list?

**Comment by PankajBhojwani** [comment]
Here is the error list:

![errorList](https://user-images.githubusercontent.com/26824113/60035434-affb8000-9661-11e9-8e86-0ebb044d343f.png)

Here is the output when I try to build:

![buildErrors](https://user-images.githubusercontent.com/26824113/60035450-b853bb00-9661-11e9-803f-64c1e450194e.png)

**Comment by Voskrese** [comment]
nuget resore or `msbuild /t:restore` ?

**Comment by PankajBhojwani** [comment]
![nuget](https://user-images.githubusercontent.com/26824113/60035839-9c9ce480-9662-11e9-9e0a-91fa233b91c0.png)

**Comment by Voskrese** [comment]
test version, why the executable does not compile)))

[microsoft-terminal.zip](https://github.com/microsoft/vcpkg/files/3321757/microsoft-terminal.zip)

**Comment by PankajBhojwani** [comment]
I'm sorry, I don't understand your question. Could you explain in a little more detail what information you want me to give you?

**Comment by Voskrese** [comment]
> Building the Code
> 
> This repository uses git submodules for some of its dependencies. To make sure submodules are restored or updated, be sure to run the following prior to building:
> 
> git submodule update --init --recursive

**Comment by PankajBhojwani** [comment]
I ran that command and am still getting the same errors

**Comment by PankajBhojwani** [comment]
Yes I used vcpkg integrate install. As I mentioned, when I open up a new project in visual studio 2019 I can #include the files I need without needing to do anything else. But when I open up this existing project, I get the errors I pasted above.

**Comment by PankajBhojwani** [comment]
It is very easy to repro, just clone the [Windows Terminal project](https://github.com/microsoft/terminal), open it in VS 2019 and try to `#include` any files you have installed with vcpkg.

**Comment by PankajBhojwani** [comment]
Solved: I had to install with the command `vcpkg install cpprestsdk --triplet x64-uwp` because this is a uwp project
