### ISSUE TITLE
 Building package zeromq:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by lenin41211** [microsoft/vcpkg#6989]
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/3316529/config-x64-windows-out.log)

  Error code: 1
    See logs for more information:
      D:\lenin\worklog\june 22\vcpkg\buildtrees\zeromq\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:274 (vcpkg_execute_required_process)

  ports/zeromq/portfile.cmake:23 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package zeromq:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zeromq:x64-windows
  Vcpkg version: 2019.06.21-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by JackBoosY** [comment]
It seems a space-inside-path issue.

**Comment by lenin41211** [comment]
thank you, I fixed it

**Comment by JackBoosY** [comment]
@lenin41211 Please don't close this issue until someone make a PR to fix it.

**Comment by JackBoosY** [comment]
vcpkg rename bug:
```
PS F:\space inside> .\vcpkg.exe install zeromq:x64-windows
The following packages will be built and installed:
    zeromq[core]:x64-windows
Starting package 1/1: zeromq:x64-windows
Building package zeromq[core]:x64-windows...
A suitable version of cmake was not found (required v3.14.0). Downloading portable cmake v3.14.0...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.14.0/cmake-3.14.0-win32-x86.zip -> F:\space inside\downloads\cmake-3.14.0-win32-x86.zip
Extracting cmake...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> F:\space inside\downloads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
A suitable version of nuget was not found (required v4.6.2). Downloading portable nuget v4.6.2...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v4.6.2/nuget.exe -> F:\space inside\downloads\nuget.exe
A suitable version of git was not found (required v2.21.0). Downloading portable git v2.21.0...
Downloading git...
  https://github.com/git-for-windows/git/releases/download/v2.21.0.windows.1/PortableGit-2.21.0-32-bit.7z.exe -> F:\space inside\downloads\PortableGit-2.21.0-32-bit.7z.exe
Extracting git...
Failed to do post-extract rename-in-place.
fs.rename(F:\space inside\downloads\tools\git-2.21.0-1-windows.partial.8280, F:\space inside\downloads\tools\git-2.21.0-1-windows, operation not permitted)
PS F:\space inside>
```

**Comment by Voskrese** [comment]
`builds/msvc` I don't have such a folder, I have `builds\deprecated-msvc`
and compiles without errors

**Comment by Rastaban** [comment]
This should be complete now.
