### ISSUE TITLE
Building package python3:x64-linux failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by dvoprm** [microsoft/vcpkg#6990]
**OS**: ubuntu18

**LOG**:
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: msbuild;/home/weiqisheng/vcpkg/buildtrees/python3/src/v3.7.3-1161ad7a91-Lib-static-crt-dynamic/**PCBuild**/pythoncore.vcxproj;/p:Configuration=Release;/t:Rebuild;/p:Platform=x64;/p:PlatformToolset=external;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No;/p:WindowsTargetPlatformVersion=;/m;/p:WholeProgramOptimization=false
    Working Directory: /home/weiqisheng/vcpkg/buildtrees/python3/x64-linux-rel
    **Error code: No such file or directory**
    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:119 (vcpkg_execute_required_process)
  ports/python3/portfile.cmake:37 (vcpkg_build_msbuild)
  scripts/ports.cmake:71 (include)

So I list the directory **/home/weiqisheng/vcpkg/buildtrees/python3/src/v3.7.3-1161ad7a91-Lib-static-crt-dynamic**, and I find that PCBuild and PCbuild are different.
v3.7.3-1161ad7a91-Lib-static-crt-dynamic git:(master) l
total 1.1M
drwxr-xr-x 19 weiqisheng weiqisheng 4.0K 3月  26 04:21 .
drwxr-xr-x  3 weiqisheng weiqisheng 4.0K 6月  22 13:32 ..
-rw-r--r--  1 weiqisheng weiqisheng  11K 3月  26 04:21 aclocal.m4
drwxr-xr-x  2 weiqisheng weiqisheng 4.0K 3月  26 04:21 .azure-pipelines
-rw-r--r--  1 weiqisheng weiqisheng  631 3月  26 04:21 CODE_OF_CONDUCT.rst
-rwxr-xr-x  1 weiqisheng weiqisheng  44K 3月  26 04:21 config.guess
-rwxr-xr-x  1 weiqisheng weiqisheng  36K 3月  26 04:21 config.sub
-rwxr-xr-x  1 weiqisheng weiqisheng 493K 3月  26 04:21 configure
-rw-r--r--  1 weiqisheng weiqisheng 164K 3月  26 04:21 configure.ac
drwxr-xr-x 18 weiqisheng weiqisheng 4.0K 3月  26 04:21 Doc
-rw-r--r--  1 weiqisheng weiqisheng 1.6K 3月  26 04:21 .gitattributes
drwxr-xr-x  2 weiqisheng weiqisheng 4.0K 3月  26 04:21 .github
-rw-r--r--  1 weiqisheng weiqisheng 1.6K 3月  26 04:21 .gitignore
drwxr-xr-x  2 weiqisheng weiqisheng 4.0K 3月  26 04:21 Grammar
drwxr-xr-x  3 weiqisheng weiqisheng 4.0K 3月  26 04:21 Include
-rwxr-xr-x  1 weiqisheng weiqisheng 7.0K 3月  26 04:21 install-sh
drwxr-xr-x 33 weiqisheng weiqisheng 4.0K 3月  26 04:21 Lib
-rw-r--r--  1 weiqisheng weiqisheng  13K 3月  26 04:21 LICENSE
drwxr-xr-x  2 weiqisheng weiqisheng 4.0K 3月  26 04:21 m4
drwxr-xr-x  8 weiqisheng weiqisheng 4.0K 3月  26 04:21 Mac
-rw-r--r--  1 weiqisheng weiqisheng  63K 3月  26 04:21 Makefile.pre.in
drwxr-xr-x  3 weiqisheng weiqisheng 4.0K 3月  26 04:21 Misc
drwxr-xr-x 13 weiqisheng weiqisheng 4.0K 3月  26 04:21 Modules
drwxr-xr-x  4 weiqisheng weiqisheng 4.0K 3月  26 04:21 Objects
drwxr-xr-x  2 weiqisheng weiqisheng 4.0K 3月  26 04:21 Parser
drwxr-xr-x  6 weiqisheng weiqisheng 4.0K 3月  26 04:21 PC
drwxr-xr-x  2 weiqisheng weiqisheng 4.0K 3月  26 04:21 **PCbuild**
drwxr-xr-x  2 weiqisheng weiqisheng 4.0K 3月  26 04:21 Programs
-rw-r--r--  1 weiqisheng weiqisheng  43K 3月  26 04:21 pyconfig.h.in
drwxr-xr-x  3 weiqisheng weiqisheng 4.0K 3月  26 04:21 Python
-rw-r--r--  1 weiqisheng weiqisheng 9.9K 3月  26 04:21 README.rst
-rw-r--r--  1 weiqisheng weiqisheng 100K 3月  26 04:21 setup.py
drwxr-xr-x 23 weiqisheng weiqisheng 4.0K 3月  26 04:21 Tools
-rw-r--r--  1 weiqisheng weiqisheng 6.0K 3月  26 04:21 .travis.yml

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/6700

**Comment by jasonsmr** [comment]
same on debian in wsl windows
