### ISSUE TITLE
[New port request] mimalloc

### ISSUE THREAD

**Issue by myd7349** [microsoft/vcpkg#6996]
https://github.com/microsoft/mimalloc

**Comment by Voskrese** [comment]
[mimalloc.zip](https://github.com/microsoft/vcpkg/files/3318989/mimalloc.zip)

test windows x64 shared

**Comment by cenit** [comment]
I’d love a Microsoft policy that all their c/c++ libs must be published also on vcpkg. It would make everything much easier!
