### ISSUE TITLE
getWindowsSDK.ps1 requires modifications to execution policy to run, breaks previous behavior

### ISSUE THREAD

**Issue by cjvaijo** [Microsoft/vcpkg#700]
The script will not run out-of-the-box. E.g. trying to install the new version of the opengl port produces the following output: 
D:\Code\vcpkg>vcpkg.exe install opengl:x64-windows
-- CURRENT_INSTALLED_DIR=D:/Code/vcpkg/installed/x64-windows
-- DOWNLOADS=D:/Code/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/Code/vcpkg/packages/opengl_x64-windows
-- CURRENT_BUILDTREES_DIR=D:/Code/vcpkg/buildtrees/opengl
-- CURRENT_PORT_DIR=D:/Code/vcpkg/ports/opengl/.
D:/Code/vcpkg/scripts/getWindowsSDK.ps1 : File D:\Code\vcpkg\scripts\getWindowsSDK.ps1 cannot be loaded because running
 scripts is disabled on this system. For more information, see about_Execution_Policies at http://go.microsoft.com/fwli
nk/?LinkID=135170.
At line:1 char:1
+ D:/Code/vcpkg/scripts/getWindowsSDK.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
CMake Error at scripts/cmake/vcpkg_get_windows_sdk.cmake:8 (message):
  Could not find Windows SDK
Call Stack (most recent call first):
  ports/opengl/portfile.cmake:4 (vcpkg_get_windows_sdk)
  scripts/ports.cmake:73 (include)

Error: Building package opengl:x64-windows failed with: BUILD_FAILED
Please ensure sure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opengl:x64-windows
  Vcpkg version: 0.0.74-b831a7d9ee5f97df506b14058d5fc970260d692a

Additionally, attach any relevant sections from the log files above.

Output from powershell also shows this:
PS D:\Code\vcpkg\scripts> .\getWindowsSDK.ps1
.\getWindowsSDK.ps1 : File D:\Code\vcpkg\scripts\getWindowsSDK.ps1 cannot be loaded because running scripts is disabled
 on this system. For more information, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ .\getWindowsSDK.ps1
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by ras0219-msft** [comment]
Sorry about that! Could you try out fa3f9dd? I've added `-ExecutionPolicy Bypass` which should fix your issue.

**Comment by cjvaijo** [comment]
Works fine now, thank you!

D:\WorkingFolder\git\vcpkg>vcpkg version
Vcpkg package management program version 0.0.74-fa3f9dd9628ebafd3ba65fb3abde6c1d6f0448fc

See LICENSE.txt for license information.

D:\WorkingFolder\git\vcpkg>vcpkg install opengl:x64-windows
-- CURRENT_INSTALLED_DIR=D:/WorkingFolder/git/vcpkg/installed/x64-windows
-- DOWNLOADS=D:/WorkingFolder/git/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/WorkingFolder/git/vcpkg/packages/opengl_x64-windows
-- CURRENT_BUILDTREES_DIR=D:/WorkingFolder/git/vcpkg/buildtrees/opengl
-- CURRENT_PORT_DIR=D:/WorkingFolder/git/vcpkg/ports/opengl/.
-- Performing post-build validation
-- Performing post-build validation done
Package opengl:x64-windows is installed
