### ISSUE TITLE
cmake can not find mosquitto

### ISSUE THREAD

**Issue by zlinwei** [microsoft/vcpkg#7009]
cmake can not find mosquitto

**Comment by wangli28** [comment]
Hi @zlinwei, can you provide more information? How did you use this port? And what information did you get?

**Comment by zlinwei** [comment]
```cmake
find_package(mosquitto CONFIG REQUIRED)
```
then I got
```cmake
CMake Error at /home/locate/vcpkg/scripts/buildsystems/vcpkg.cmake:266 (_find_package):
  Could not find a package configuration file provided by "mosquitto" with
  any of the following names:

    mosquittoConfig.cmake
    mosquitto-config.cmake

  Add the installation prefix of "mosquitto" to CMAKE_PREFIX_PATH or set
  "mosquitto_DIR" to a directory containing one of the above files.  If
  "mosquitto" provides a separate development package or SDK, be sure it has
  been installed.
```

So I had to specify the location of libmosquitto.so like this:
```cmake
target_link_libraries(target path_to/vcpkg/installed/x64-linux/lib/libmosquitto.so)
```

**Comment by Voskrese** [comment]
ln -S path_to/vcpkg/installed/x64-linux/lib/libmosquitto.so path_to/vcpkg/installed/x64-linux/lib/mosquitto.so
?

**Comment by zlinwei** [comment]
> `ln -S path_to/vcpkg/installed/x64-linux/lib/libmosquitto.so path_to/vcpkg/installed/x64-linux/lib/mosquitto.so`
> ?

If I use it on Windows, How should I do?

**Comment by Voskrese** [comment]
@zlinwei `mklink /?`
