### ISSUE TITLE
Specify triplets as a general parameter instead of for each package

### ISSUE THREAD

**Issue by mikebmcl** [microsoft/vcpkg#7017]
Right now I need to say something like ".\vcpkg install qt5-base qt5-base:x64-windows qt5-imageformats qt5-imageformats:x64-windows", etc. I'd prefer if I could just type something like ".\vcpkg install --triplets x86-windows x64-windows --packages qt5-base qt5-imageformats", etc. When installing more than one triplet for multiple output targets, especially when more than two packages are involved or when more than two triplets are involved, it's a lot of excess typing.

Maybe this is already available and the documentation doesn't reflect it. Either way, for me it'd be a major enhancement if the feature existed and the documentation reflected its existence.

**Comment by vicroms** [comment]
Hi @mikebmcl 

That scenario is not currently supported by **vcpkg**.
A workaround to minimize typing could be to do something like this:
```
./vcpkg install qt5-base qt5-imageformats --triplet x86-windows
./vcpkg install qt5-base qt5-imageformats --triplet x64-windows
```

**Comment by NancyLi1013** [comment]
Hi @mikebmcl 

Does the workload from @vicroms can meet your demands?
