### ISSUE TITLE
gtk dll names missing minor version number

### ISSUE THREAD

**Issue by ndeadly** [microsoft/vcpkg#7027]
The gtk .dll files created by vcpkg are missing the minor version number found in the corresponding .lib filenames, eg. `gobject-2.0.lib`  -> `gobject-2.dll`

This is causing python's [weasyprint](https://github.com/Kozea/WeasyPrint) library to fail as it tries to dynamically import these .dlls expecting the minor version number to be present in the name as in the .lib files

If this is by design this issue can be closed and I'll submit a pull request to weasyprint instead.

**Comment by JackBoosY** [comment]
@ndeadly 
When gtk is built using _SOURCE_PATH/build/win32/vs15/gtk+.sln_, it will generate `${NAME}${MAJOR_VER}-win32.lib` and `${NAME}${MAJOR_VER}-win32.dll`, so I think this is by design.
