### ISSUE TITLE
[gdal]: Release pdb also duplicated into "lib" folder on x64-windows.

### ISSUE THREAD

**Issue by jumpinjackie** [microsoft/vcpkg#7029]
I don't know how his happens, but building `gdal:x64-windows` will also copy the release .pdb into the lib folder (in addition to the bin folder).

It's annoying enough for me to open this issue due to the size of the `gdal204.pdb` file (110MB), which adds noticeable weight to an archive when I do a `vcpkg export` with gdal in it.

Current workaround is to just manually delete this duplicate file after installing and before exporting.

**Comment by JackBoosY** [comment]
Some developers use pdb files to debug their programs. Maybe we can add a switch to choose to store the pdb file.

**Comment by jumpinjackie** [comment]
@JackBoosY That's not my issue. I know pdb files are generated. 

It's just for some ports (like `gdal`), they are being duplicated across different folders (`bin` and `lib`) on install

**Comment by wangli28** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
