### ISSUE TITLE
Troubles getting up and running with vcpkg & cmake

### ISSUE THREAD

**Issue by brupelo** [Microsoft/vcpkg#703]
Today I've started using vcpkg as a good replacement of nuget, the main idea was being able to install my libraries without too much hazzle on my cmake swig modules. So here's the steps I've followed:

 - `git clone https://github.com/Microsoft/vcpkg`
 - `powershell -exec bypass scripts\bootstrap.ps1`
 - `vcpkg integrate install`
 - `vcpkg install sdl2-x86-windows`
 - Added vcpkg to my PATH

Once the setup was ready to go I decided to try it out on a simple CMake project to see if this was working out of the box, so I've just created a couple of files:

CMakeLists.txt:

    cmake_minimum_required(VERSION 2.8.9)
    project (hello)
    add_executable(hello main.cpp)

main.cpp:

    #include <iostream>
    #include <conio.h>

    #include <SDL2\SDL.h>

    int main(int argc, char *argv[]){
       std::cout << "Hello World!" << std::endl;
       getch();
       return 0;
    }

After that I've generated the project and tried to build it, the result was this error on my sublime text console:

    [1/2] C:\PROGRA~2\MI0E91~1.0\VC\bin\X86_AM~1\cl.exe  /nologo /TP   /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MD /O2 /Ob2 /DNDEBUG /showIncludes /FoCMakeFiles\hello.dir\main.cpp.obj /FdCMakeFiles\hello.dir\ /FS -c D:\sources\personal\c++\vcpkg_tests\test1\main.cpp
    FAILED: CMakeFiles/hello.dir/main.cpp.obj 
    C:\PROGRA~2\MI0E91~1.0\VC\bin\X86_AM~1\cl.exe  /nologo /TP   /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MD /O2 /Ob2 /DNDEBUG /showIncludes /FoCMakeFiles\hello.dir\main.cpp.obj /FdCMakeFiles\hello.dir\ /FS -c D:\sources\personal\c++\vcpkg_tests\test1\main.cpp
    D:\sources\personal\c++\vcpkg_tests\test1\main.cpp(4): fatal error C1083: Cannot open include file: 'SDL2\SDL.h': No such file or directory
    ninja: build stopped: subcommand failed.

Alright, fair enough, let's assume I'll need to make something extra in that case... Then I've decided I'd just try it out one of the available [youtube tutorials](https://www.youtube.com/watch?v=zo6nqFVBd5o), so i've tried to follow it (almost... cos i didn't have the source used by Eric on the video) and I've used this one:

	// ConsoleApplication1.cpp : Defines the entry point for the console application.
	//

	#include "stdafx.h"
	#include <SDL2\SDL.h>

	int main(int argc, char* argv[])
	{
		return 0;
	}

And once I've tried to build it the output was this [one](https://dl.dropboxusercontent.com/u/21334722/Uploads/2017/02/devenv_2017-02-22_16-10-39.png).

So, what am I missing here? I would have expected this empty code to work out of the box... Maybe I missed something on the vcpkg installation? (I've cloned and installed vcpkg on a vstudio2015 x64 cmd prompt btw), here's some relevant info which gives me vcpkg:

    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC>vcpkg list
    sdl2:x86-windows            2.0.5-2          Simple DirectMedia Layer is a cross
    -platform deve...
    zlib:x86-windows-static     1.2.11           A compression library

    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC>vcpkg version
    Vcpkg package management program version 0.0.74-fa3f9dd9628ebafd3ba65fb3abde6c1d6f0448fc

    See LICENSE.txt for license information.

Please, advice... :)

PS: I've allowed installed the portable cmake version cos my cmake system-wide was too old (3.7.2)

**Comment by brupelo** [comment]
In order to speed it up the the issue, I've also opened a [SO question](http://stackoverflow.com/questions/42395981/get-up-and-running-vcpkg)... But I can see the vcpkg tag is still brand new on StackOverflow :-D , hopefully this project will get traction

**Comment by KindDragon** [comment]
Check this instruction: https://github.com/Microsoft/vcpkg/blob/master/docs/EXAMPLES.md#example-1-2-b

**Comment by brupelo** [comment]
@KindDragon Just right now I was trying that cmake example and failing miserably, here's my [output](https://dl.dropboxusercontent.com/u/21334722/Uploads/2017/02/ConEmu64_2017-02-22_17-02-29.png)

**Comment by codicodi** [comment]
Regarding the 'uresolved symbol main' error: a few problematic libraries aren't linked by default, you need to do so explicitly (vcpkg sets up appropriate library search paths though). `SDL2main.lib` is one of them, just add it to linker inputs. Alternatively you can add `#define SDL_MAIN_HANDLED` before including any SDL headers to prevent them from replacing your main function.

**Comment by brupelo** [comment]
It seems the cmake "Sublime Text 2 - Ninja" and "Sublime Text 2 - NMake Makefiles" don't work well with vcpkg, example [here](https://dl.dropboxusercontent.com/u/21334722/Uploads/2017/02/cmd_2017-02-22_17-56-08.png)

**Comment by brupelo** [comment]
It seems the cmake "Sublime Text 2 - Ninja" and "Sublime Text 2 - NMake Makefiles" generators don't work well with "-DCMAKE_TOOLCHAIN_FILE=D:\src\vcpkg\scripts\buildsystems\vcpkg.cmake".

So my final solution was adding manually the vcpkg to my CMakeLists.txt all the include&lib files, it's far away to be an optimal solution and it defies the purpose of vcpkg in the first place, so summing up:

Will you guys provide support for Sublime Text 2 generators to play nicely with vcpkg? That'd be awesome :)

**Comment by alexkaratarakis** [comment]
@brupelo 
`vcpkg integrate install` makes all packages you have installed automatically available within Visual Studio. It basically says "look in that folder for binaries" to Visual Studio. Therefore, you only need to run it once total. You don't need to run it for each VS instance and you don't need to run it if you install/remove packages in `vcpkg`. 

In CMake, you have to specify the toolchain file to make the packages available (KindDragon's link above).

As for the generators, it sounds like that is an issue on the CMake side, i.e. an issue with the generators for Sublime.

**Comment by ras0219-msft** [comment]
I tried out the Sublime Text 2 - Ninja generator, and it worked fine on my machine. One caveat was that I needed to launch Sublime from the same VS developer prompt that I used to configure the generator.

This particular project was configured with:
```
cmake .. "-DCMAKE_TOOLCHAIN_FILE=D:\src\vcpkg\scripts\buildsystems\vcpkg.cmake" -G "Sublime Text 2 - Ninja" -DVCPKG_TARGET_TRIPLET=x86-windows-static -DCMAKE_BUILD_TYPE=Debug
```

![image](https://cloud.githubusercontent.com/assets/12301622/23244839/ead74da4-f93c-11e6-9c4d-2c7877620586.png)

**Comment by brupelo** [comment]
@ras0219-msft Your test puzzles me because I've tried to reproduce over here with this simple [test-cases](https://github.com/brupelo/vcpkg_tests) and I couldn't, could you please to confirm they work over there? In order to reproduce here's the steps:

 1. Open a vsx64 cmd prompt
 2. vcpkg install sdl2 sqlite3
 3. `git clone https://github.com/brupelo/vcpkg_tests` && cd vcpkg_tests
 4. cd test_sdl2 && mkdir build
 5. cmake .. "-DCMAKE_TOOLCHAIN_FILE=D:\src\vcpkg\scripts\buildsystems\vcpkg.cmake" -G "Sublime Text 2 - Ninja" -DVCPKG_TARGET_TRIPLET=x86-windows-static -DCMAKE_BUILD_TYPE=Debug
 
that's for sdl2, for sqlite3 you can give it a shot to test_sqlite3. They both should spawn you some errors. It'd be great to make them work though... as you can see in the repo I also include 2 additional tests where I manually search the libraries installed on vcpkg... but that obviously defies the real purpose of having vcpkg in the first place.

**Comment by codicodi** [comment]
Looks like you installed x86 dlls (default configuration) and try to build x64 application with x86 static libs. 
You need install libraries for the same triplet you are passing to VCPKG_TARGET_TRIPLET and then use cmd prompt for appropriate architecture.

**Comment by ras0219-msft** [comment]
To complete that with concrete steps:
1. Open a vsx64 cmd prompt
2. vcpkg install sdl2:x64-windows
3. `git clone https://github.com/brupelo/vcpkg_tests && cd vcpkg_tests/test_sdl2`
4. Replace the contents of CMakeLists.txt with:
```cmake
cmake_minimum_required(VERSION 3.0)
project(test_sdl2)

find_path(SDL2_INCLUDE_DIR SDL2/SDL.h)
find_library(SDL2_LIBRARY SDL2)
find_library(SDL2_MAIN SDL2main)

add_executable(main main.cpp)
target_include_directories(main PUBLIC ${SDL2_INCLUDE_DIR})
target_link_libraries(main PRIVATE ${SDL2_LIBRARY} ${SDL2_MAIN})
```
5. `mkdir build && cd build`
6. `cmake .. "-DCMAKE_TOOLCHAIN_FILE=D:\software\vcpkg\scripts\buildsystems\vcpkg.cmake" -G "Sublime Text 2 - Ninja" -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_BUILD_TYPE=Debug`

It turns out that SDL2 is _not_ found by the built-in CMake `FindSDL.cmake` script (sorry for leading you astray there!). Generally, you can search for "find library X with cmake" and get a decent result: http://stackoverflow.com/a/29447053

**Comment by brupelo** [comment]
@ras0219-msft @codicodi Thank you very much guys for your help! everything works like a charm now in both Visual Studio and Sublime Text now, this project is awesome and promising :)

One question though, what'd you say are the general steps you need to do in order to include a library in the CMakeLists? I mean, yeah, for [SDL](https://github.com/brupelo/vcpkg_tests/blob/master/test_sdl2_manual/CMakeLists.txt) & [Sqlite](https://github.com/brupelo/vcpkg_tests/blob/master/test_sqlite3/CMakeLists.txt) is already clear thanks to the docs & @ras0219-msft help. But what'd be the general procedure you need to follow when you want to add a vcpkg library into the CMakeLists? 

I mean, I definitely don't want to include hardcoded paths poiting out to the vcpkg libraries, doing so would be quite a bad solution if you want to bootstrap your project on the end-user machine

Btw, one last note, why do you guys include opengl as a package? That one should be already included in the windows sdk, shouldn't? Plus, if you install it like `vcpkg install opengl` it gives errors.

**Comment by ras0219-msft** [comment]
Here's some (outdated) official documentation on the subject: https://cmake.org/Wiki/CMake:How_To_Find_Libraries.

Here's the technical details behind `find_package()`, which is desirable to use when possible: https://cmake.org/cmake/help/v3.0/command/find_package.html.

Generally, you'll want to start with a search for "find X cmake". If all else fails, you can always fall back onto a combination of `find_library` and `find_path` (search the docs at [1]) which let you express "I want to link a library called foo.lib and include a header called foo.h -- find it for me". You should never need to hardcode Vcpkg paths into your build script; come file an issue if we have provided no other way.

For more help, I recommend a general purpose CMake tutorial and then perhaps the CMake forums.

The reason for the `opengl` package is for users of Visual Studio. In VS, we automatically handle the include paths and linking libraries, so installing both `opengl` and `sdl2` means that you can just do File -> New Project, paste in some code you found randomly on the internet, and have a working application (most SDL2 samples _assume_ you link opengl without telling you to).

[1] https://cmake.org/cmake/help/v3.7/index.html
