### ISSUE TITLE
[New port request] Paho MQTT C++ library

### ISSUE THREAD

**Issue by thedevilfish** [microsoft/vcpkg#7032]
This is a port request for: Eclipse's Paho MQTT C++ Client library which enables C++ 11 applications to connect to a MQTT broker to publish messages, and to subscribe to topics and receive published messages.

**Comment by thedevilfish** [comment]
See Pull request #7033

**Comment by thedevilfish** [comment]
@PhoebeHui Pull Request #7033 is ready. Need someone to review the PR.

**Comment by NancyLi1013** [comment]
Hi @thedevilfish, thanks for posting this request and your PR. It has been merged.
