### ISSUE TITLE
[mongo-c-driver] FindPackage doesn't work properly on Linux

### ISSUE THREAD

**Issue by Pospelove** [microsoft/vcpkg#7040]
```cmake
find_package(mongo-c-driver REQUIRED)
find_package(libbson REQUIRED)

message(MONGOC ${MONGOC_LIBRARIES})
message(BSON ${BSON_LIBRARIES})
```
Outputs valid values on Windows, but on Linux outputs nothing.

The contents of `vcpkg/installed/x64-linux/lib`:
```
libbson-1.0.a
libbson-1.0.so
libbson-1.0.so.0
libbson-1.0.so.0.0.0
libbson-static-1.0.a
libbsoncxx-static.a
libcrypto.a
libmongoc-1.0.a
libmongoc-1.0.so
libmongoc-1.0.so.0
libmongoc-1.0.so.0.0.0
libmongocxx-static.a
libssl.a
libz.a
pkgconfig
```

**Comment by Pospelove** [comment]
Thank you for the fast reply, but it doesn't work.
```cmake
find_package(mongo-c-driver CONFIG REQUIRED)
target_link_libraries(main PRIVATE ${MONGOC_LIBRARIES})
target_include_directories(main PRIVATE ${MONGOC_INCLUDE_DIRS})
```
`${MONGOC_LIBRARIES}` is empty on Linux.

**Comment by wangli28** [comment]
Hi @Pospelove, I can't reproduce this issue locally. How did you use this port on Linux?

**Comment by Pospelove** [comment]
Hi @wangli28. 
Steps to reproduce:
```sh
vcpkg install mongo-c-driver
vcpkg integrate install

mkdir build
cd ./build 
cmake -DCMAKE_TOOLCHAIN_FILE=<my_path_to_vcpkg>/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release .. 
cmake --build .
```

My `CMakeLists.txt`:
```cmake
cmake_minimum_required(VERSION 3.12)
project(test LANGUAGES C CXX)
find_package(mongo-c-driver CONFIG REQUIRED)
message(MONGOC_LIBRARIES ${MONGOC_LIBRARIES})
```

CMake Output:
```
MONGOC_LIBRARIES
```

**Comment by lsparey** [comment]
It could be ${MONGOC_STATIC_LIBRARIES} that you need to use

**Comment by Pospelove** [comment]
It works. Thank you.
```cmake
# MONGOC_LIBRARIES is non-empty on Windows
# MONGOC_STATIC_LIBRARIES is non-empty on Linux
target_link_libraries(main ${MONGOC_LIBRARIES} ${MONGOC_STATIC_LIBRARIES})
```

I think `${MONGOC_STATIC_LIBRARIES}` should be added to usage.

**Comment by wangli28** [comment]
Hi @Pospelove, thanks for your steps! I reproduce it locally. I found the difference in **mongo-c-driver-config.cmake**.
When building mongo-c-driver as a **static** library, _mongo-c-driver-config.cmake L67_ shows:
```
set (MONGOC_STATIC_LIBRARIES ${MONGOC_STATIC_LIBRARY} ${ZLIB_STATIC_LIBRARY} ${BSON_STATIC_LIBRARIES})
```
And when building mongo-c-driver as a **dynamic** library, _mongo-c-driver-config.cmake L62_ shows:
```
set (MONGOC_LIBRARIES ${MONGOC_LIBRARY} ${BSON_LIBRARIES})
```
In order to maintain the same as the official macro name, I just modified **usage** according to this difference. You can use `${MONGOC_STATIC_LIBRARIES}` instead of `${MONGOC_LIBRARIES}` in Linux.
Thanks!
