### ISSUE TITLE
[WINDOWS] THREADS_PTHREADS_WIN32_LIBRARY

### ISSUE THREAD

**Issue by Voskrese** [microsoft/vcpkg#7044]
faced with the problem THREADS_PTHREADS version 3
the fact is that most people use the old version, new does not see, even with a wrapper

if you specify explicitly then everything works

but there are projects that explicitly link by library name

```
OPTIONS_DEBUG # automatic templates
   -DLIBUSB_LIBRARIES=${CURRENT_INSTALLED_DIR}/debug/lib/libusb-1.0.lib
   -DTHREADS_PTHREADS_WIN32_LIBRARY=${CURRENT_INSTALLED_DIR}/debug/lib/pthreadVC2.lib
 OPTIONS 
   -DLIBUSB_LIBRARIES=${CURRENT_INSTALLED_DIR}/lib/libusb-1.0.lib
   -DTHREADS_PTHREADS_WIN32_LIBRARY=${CURRENT_INSTALLED_DIR}/lib/pthreadVC2.lib
```

example
https://github.com/steve-m/librtlsdr

had to symbolic link pthreadVC3.lib -->> pthreadVC2.lib

**Comment by cenit** [comment]
Instead of patching our pthread v3 portfile to rename/copy pthreadVC3.lib —> pthreadVC2.lib, do you thing it would be impossible to fix the problem upstream in the libraries that still expect the **ancient** v2?

**Comment by Voskrese** [comment]
no copy, symbolic reference ))
you have to write a script wrapper ((

**Comment by cenit** [comment]
What do you mean with symbolic references? If it is a file link, unfortunately before win10 1803 and even then without developer mode enabled, it requires admin privileges and so it’s out of question.
In any case any “double entry” to the same file would cause maybe some problems with vcpkg auto linking for vs solutions (same symbol in different libs)

Can you tell me in that project exactly where is the wrong pthread linking line? Maybe it’s not easy to locate? What about patching that project so to be pthreadVC* version independent?

**Comment by Voskrese** [comment]
for a personal directory that is not created as an administrator, you do not need any privileges to create a symbolic link
and if many people work with one project, then in any case there are permissions to record

and this is not the only project, there are about 8 of them, which I faced

**Comment by cenit** [comment]
https://github.com/steve-m/librtlsdr/blob/f68bb2fa772ad94f58c59babd78353667570630b/cmake/Modules/FindThreads.cmake#L88

https://github.com/steve-m/librtlsdr/blob/f68bb2fa772ad94f58c59babd78353667570630b/cmake/Modules/FindThreads.cmake#L91

In these 2 lines the explicit “2” must be changed maybe to a version symbol

**Comment by cenit** [comment]
> for a personal directory that is not created as an administrator, you do not need any privileges to create a symbolic link

What os version do you use? To create symbolic links in Windows you had always needed admin privileges, even if you were working in your home folder. Things changed one year ago, but still you had to opt-in in the new mechanism (developer mode)

**Comment by Voskrese** [comment]
I just voiced the problem that many face, in more detail I do not have time to figure out
I go for less resistance

\\sorry google translate

**Comment by cenit** [comment]
That’s exactly what I look for: least resistance. And that maybe means just a copy of the file, from VC3 to VC2, apart from the symbolic redundancy that may create.
@ras0219-msft what do you think?

**Comment by Neumann-A** [comment]
Stupid question: Can you not simply delete the FindThreads module and use CMakes buildin FindThreads module and set `THREADS_PREFER_PTHREAD_FLAG`?

**Comment by Voskrese** [comment]
I did not think about it, we should try to just remove the module

**Comment by Voskrese** [comment]
@Neumann-A 
Is it possible to set a priority in the search for modules?

suppose, search first in VCPKG then in CMAKE share MODULE and last with the project files?

**Comment by cenit** [comment]
CMake integrated thread module doesn’t look for posix thread implementations on Windows afaik, no matter how much hard you ask for them. I had also to write a custom module for darknet/yolo back in the time, but I didn’t overlay the official one. I can understand the problem that pthreadVC2 has been there for a long time, i’d patch problematic projects to bring them to the modern age, but still can also understand replicating files, if it’s so simple and fixes *many* projects in a glimpse.

**Comment by cenit** [comment]
> Is it possible to set a priority in the search for modules?

That’s what `CMAKE_MODULE_PATH` is there for

**Comment by Voskrese** [comment]
> That’s what CMAKE_MODULE_PATH is there for

it is understandable, globally in VCPKG
What is the default priority in the CMAKE?

**Comment by cenit** [comment]
First of all, look in the folders in that path (in the order they are written), then look in the internal repository (share/cmake-x.y/Modules).
vcpkg does not have a single module folder, each port writes its own module in its share folder (similar to the config mode)

**Comment by Voskrese** [comment]
Well, as implemented in meson dependency search via cmake
https://github.com/microsoft/vcpkg/pull/6977#issuecomment-504146129
