### ISSUE TITLE
option to generate a list of all urls of packages to download

### ISSUE THREAD

**Issue by duyanning** [microsoft/vcpkg#7045]
I am in china.
It is very hard for me to download some packages.
I have to Ctrl-C when vcpkg hangs up while downloading,
and then copy the url from the console, paste it into another downloader which is configured with a proxy.
I hope vcpkg to add an option to generate all urls of packages that need to download while installing.

**Comment by ZeroAurora** [comment]
Or let 3rd downloader (like aria2) handle all download link?
BTW, you can use `sed` or other replacing tools to replace links to mirrors in China (I used vscode's tool and feel quite comfortable).

**Comment by NancyLi1013** [comment]
Hi @duyanning 
Thanks for posting this issue.
This URL might help you some.
https://github.com/JackBoos/vcpkg/commits/mirror_zhCN

We're planning to add official mirror in the future.
The PR #12532 will also fix this kind of issues.

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/11040, which used to track the progress.
