### ISSUE TITLE
Add OpenSceneGraph

### ISSUE THREAD

**Issue by michaelaeriksen** [Microsoft/vcpkg#705]
Please add support for OpenSceneGraph http://www.openscenegraph.org/

**Comment by Mixaill** [comment]
Already done.
https://github.com/Microsoft/vcpkg/tree/master/ports/osg

**Comment by atkawa7** [comment]
@ras0219-msft And this too!

**Comment by luzpaz** [comment]
Please update to 3.6.3  https://github.com/openscenegraph/OpenSceneGraph/releases/tag/OpenSceneGraph-3.6.3

**Comment by JackBoosY** [comment]
@luzpaz Plz post a new issue. Thx.

**Comment by luzpaz** [comment]
Devs this ticket can be closed.
