### ISSUE TITLE
VCPKG failed to build due to error MSB8020: The build tools for v142 (Platform Toolset = 'v142') cannot be found with MSVC on windows

### ISSUE THREAD

**Issue by spacelg** [microsoft/vcpkg#7065]
VCPKG failed to build due to error MSB8020: The build tools for v142 (Platform Toolset = 'v142') cannot be found with MSVC on windows. It can be first reproduced on master branch f3db66b reversion. Could you please help look at this? Thanks a lot!

Repro steps:
1. git clone https://github.com/Microsoft/vcpkg  D:\VCPKG\src
2. Open a VS 2017 x86 command prompt and browse to D:\vcpkg
3. devenv /upgrade .\toolsrc\vcpkg.sln
4. cd src
5. msbuild /p:Configuration=Release /p:Platform=x86 /p:WindowsTargetPlatformVersion=10.0.17134.0 toolsrc\vcpkg.sln /t:Rebuild

[log_x86_build.log](https://github.com/microsoft/vcpkg/files/3333978/log_x86_build.log)

Failures:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v142 (Platform Toolset = 'v142') cannot be found. To build using the v142 build tools, please install v142 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [D:\VCPKG\src\toolsrc\vcpkglib\vcpkglib.vcxproj]
Done Building Project "D:\VCPKG\src\toolsrc\vcpkglib\vcpkglib.vcxproj" (default targets) -- FAILED.
Done Building Project "D:\VCPKG\src\toolsrc\vcpkg\vcpkg.vcxproj" (Rebuild target(s)) -- FAILED.

**Comment by Voskrese** [comment]
`bootstrap-vcpkg.bat`
build ok msvc 2017

**Comment by degski** [comment]
You are making it far more complicated then it is!
steps:

0. d:
1. git clone https://github.com/microsoft/vcpkg.git
2. Open a command prompt and browse to d:\vcpkg
3. bootstrap-vcpkg.bat
4. vcpkg integrate install
5. done

**Comment by heydojo** [comment]
https://github.com/microsoft/vcpkg/blob/master/README.md

Please read the documentation. And the issues section of the github page for this project are not a support forum.
Please do not be offended. As none is intended.
Thanks.

**Comment by degski** [comment]
@heydojo 

> And the issues section of the github page for this project are not a support forum.

Yes, it is, it has been done like this since its inception. You could have noticed that @wangli28 (a Microsoft person) added the label 'Question' to this 'issue', i.e. by this action [adding the label] you can deduce that posing a question in perfectly OK.

**Comment by spacelg** [comment]
Hi All,

This issue can be still reproduced on latest master branch. Could you please provide a work around to us to solve this issue?

Thanks,
Lin

**Comment by vicroms** [comment]
Hi @spacelg 

This was my fault, I inadvertently committed changes to the Visual Studio project files.
PR #7117  should revert this changes.

**Comment by vicroms** [comment]
This should be fixed by #7117. Please reopen if the issue persists.
