### ISSUE TITLE
ModuleNotFoundError: No module named 'codegen'

### ISSUE THREAD

**Issue by schwarzaviv** [microsoft/vcpkg#7066]
trying to install gtk with vcpkg.
get the following error message:

Building package gtk:x64-windows failed with: BUILD_FAILED.
Vcpkg version 2019.06.21-nohash

Log file says:
Traceback (most recent call last):
  File "C:/vcpkg/installed/x64-windows/tools/glib/gdbus-codegen", line 37, in <module>
    from codegen import codegen_main
ModuleNotFoundError: No module named 'codegen'

Attached cmd screenshot
![gtk error](https://user-images.githubusercontent.com/52283170/60264287-83f32f80-98eb-11e9-8dbb-1d849b836462.png)

**Comment by cskrisz** [comment]
#7051

**Comment by schwarzaviv** [comment]
#7051 solves the issue
