### ISSUE TITLE
vcpkg install szip:x64-windows BUILD_FAILED

### ISSUE THREAD

**Issue by fps92** [microsoft/vcpkg#7067]
Hi there,
im new on using the vcpkg-tool.
I installed the opencv-library successfully. Noch I want to install the pcl:x64-windows library and ran into an issue I dont understand and can't solve

This is my command window output:

> 

`C:\vcpkg>vcpkg` install pcl:x64-windows

The following packages will be built and installed:
  * atlmfc[core]:x64-windows
  * boost-algorithm[core]:x64-windows
...
-- Using cached C:/vcpkg/downloads/szip-2.1.1.tar.gz
-- Using source at C:/vcpkg/buildtrees/szip/src/szip-2.1.1-6b767acfa7
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: C:/vcpkg/buildtrees/szip/x64-windows-rel/vcpkg-parallel-c
onfigure
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\szip\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:275 (vcpkg_execute_required_process)

  ports/szip/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:73 (include)

**Error: Building package szip:x64-windows failed with: BUILD_FAILED**
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: szip:x64-windows
  Vcpkg version: 2019.06.21-nohash

Additionally, attach any relevant sections from the log files above.`

I appreciate your help

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/3334715/config-x64-windows-out.log)

**Comment by thedevilfish** [comment]
Your log (line 16) clearly states that cmake cannot find your visual studio path. 
```
-- The C compiler identification is unknown
CMake Error at CMakeLists.txt:2 (PROJECT):
  No CMAKE_C_COMPILER could be found.
```

Can you please add Visual Studio to your PATH variable and try again?

**Comment by fps92** [comment]
Thanks for your help.
I missed some informations:

**What version of Visual Studio are you using? 2015?:**
Using Windows 7 and VS 2017

**Can you make sure that Visual Studio is in your PATH variable?**
I'm not really expereinced at this. I already know _how_ to set the path variable, but I don't know what to write there. 
This? `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community`

**Do you have windows 10 SDK installed?**
Visual Studio Installer says: Windows 10 SDK (10.0.17763.0) installed

**Comment by thedevilfish** [comment]
Hmm... can you paste your environment variables here? You can do that on your command prompt easily. For example: `C:\>set > C:\temp\env.txt` will create a file in `C:\Temp` called `env.txt` and attach it here. Let me see if I see anything suspicious.

**Comment by fps92** [comment]
[env.txt](https://github.com/microsoft/vcpkg/files/3335030/env.txt)

**Comment by Voskrese** [comment]
open CMD.exe

`vcpkg env --triplet x64-windows`

`echo %VCINSTALLDIR%`
`echo %VSINSTALLDIR%`

?

**Comment by fps92** [comment]
c:\vcpkg>vcpkg env --triplet x64-windows
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Alle Rechte vorbehalten.

c:\vcpkg>echo %VCINSTALLDIR%
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\

c:\vcpkg>echo %VSINSTALLDIR%
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\

**Comment by Voskrese** [comment]
you have not installed any components for msvc 2017 Community
which is hard to say, reinstall and supplement

**Comment by fps92** [comment]
hm, I already reinstalled MSVC 2017 Community this morning.
In the following you see the optional features I installed
![msvs install workloads](https://user-images.githubusercontent.com/52284319/60273144-bc980680-98f5-11e9-8eb5-65d255d8f3eb.PNG)

**Comment by Voskrese** [comment]
`atlmfc[core]:x64-windows` ? mfc )
in fact, this is not a fact, put on the full))

**Comment by fps92** [comment]
> `atlmfc[core]:x64-windows` ? mfc )
> in fact, this is not a fact, put on the full))

Sorry, I don't understand what you want me to say. I'm new with this topic

**Comment by Voskrese** [comment]
![2019-06-27_221648](https://user-images.githubusercontent.com/10104740/60273749-5dec8000-9929-11e9-8c0b-80e75520af92.png)

**Comment by fps92** [comment]
Okay thank you. 
I installer the MFC for x86 and x64
But the same result.. :/

![current error](https://user-images.githubusercontent.com/52284319/60274396-434de300-98f8-11e9-94b1-c5181de236ce.PNG)

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/3335174/config-x64-windows-out.log)

**Comment by thedevilfish** [comment]
After looking at your PATH variable, it looks very heavily polluted. There are multiple paths to CMake, Windows kits and Visual Studio. I think that's why your command prompt is confused and cmake cannot find the compiler. I would suggest you clean up your PATH variable and only keep the things you need.

**Comment by fps92** [comment]
> 
> 
> After looking at your PATH variable, it looks very heavily polluted. There are multiple paths to CMake, Windows kits and Visual Studio. I think that's why your command prompt is confused and cmake cannot find the compiler. I would suggest you clean up your PATH variable and only keep the things you need.

I see. But I'm also a little confused. Should I only change my PATH variables or should I also delete variables like VS110COMNTOOLS ?
I can't see what is nessesary for me and what isn't...

Excuse the circumstances

**Comment by thedevilfish** [comment]
In my humble opinion, I wouldn't touch the VS110COMNTOOLS variables. My suggestion would be to remove any duplicates in the PATH variables and see if that fixes the problem.

**Comment by fps92** [comment]
Okay, the problem has to be a CMake-Failure.

**CMakeError.log:**
"C:\vcpkg\buildtrees\szip\x64-windows-dbg\CMakeFiles\3.14.0\CompilerIdC\CompilerIdC.vcxproj" (Standardziel) (1) ->
(Link Ziel) -> 
  **LINK : fatal error LNK1104: cannot open file 'ucrtd.lib'** [C:\vcpkg\buildtrees\szip\x64-windows-dbg\CMakeFiles\3.14.0\CompilerIdC\CompilerIdC.vcxproj]


How can I solve this problem? I know there are many issues like this out there, but they did not help me at all :/

[CMakeError.log](https://github.com/microsoft/vcpkg/files/3338804/CMakeError.log)
[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/3338805/CMakeOutput.log)
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/3338816/config-x64-windows-out.log)

**Comment by fps92** [comment]
Finally the problem is solved.
An absolute obvious mistake. 
As you all said: multiple pathes to Windows kit on the environment variable PATH. So Cmake reached the wrong kit 8.x and not 10 as expected and where my ucrtd.lib lives.

Thank you all so much :+1:

**Comment by thedevilfish** [comment]
@fps92 glad we all could help!
