### ISSUE TITLE
Update OpenSSL 1.0.2q to 1.0.2s

### ISSUE THREAD

**Issue by ZacharLDZ** [microsoft/vcpkg#7078]
I need to keep OpenSSL always up to date in my project (client requirement) so if someone would update the existing windows and linux ports to the newest OpenSSL 1.0.2s packages I would be grateful :)

**Comment by thedevilfish** [comment]
I believe there is talk of upgrading OpenSSL to 1.1.1 to the latest which supports TLS 1.3 (and not to upgrade to 1.0.2s). Please see Issue #4267

**Comment by heydojo** [comment]
@ZacharLDZ Updating the [port file](https://github.com/microsoft/vcpkg/blob/master/ports/openssl-windows/portfile.cmake) for OpenSSL windows is fairly trivial.

If your "Client" requires you to do something as a condition that you are paid, would you kindly ask yourself who's job that really is?
Thanks.

**Comment by thedevilfish** [comment]
@heydojo people want everything for free these days.

**Comment by jwillemsen** [comment]
See https://github.com/microsoft/vcpkg/pull/6854

**Comment by grdowns** [comment]
#6854 is merged. You should be able to use `1.0.2s` now, @ZacharLDZ!
