### ISSUE TITLE
"Invalid cross-device link" when using vcpkg in docker

### ISSUE THREAD

**Issue by ZbigniewRA** [microsoft/vcpkg#7079]
I have the same problem as @andreadps described in a comment here:
https://github.com/Microsoft/vcpkg/issues/3399#issuecomment-481381853

I am building vcpkg from inside a Docker container. If I build my required ports in two steps like below:

``` 
RUN ./vcpkg install first_thing
RUN ./vcpkg install other_thing
```

The second build will fail like this:

```
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:79 (file):
  file RENAME failed to rename

    /home/ubuntu/Projects/vcpkg/downloads/temp

  to

    /home/ubuntu/Projects/vcpkg/downloads/temp0

  because: Invalid cross-device link
```

I have tried it on 3 different machines:
- Ubuntu 16.04, kernel 4.4.0
- Ubuntu 18.04, kernel 4.15.0
- Ubuntu 18.04, kernel 4.18.0

Always the same result.
It also happens with many different packages.

"Invalid cross-device link" issue is also described in Docker issue tracker, but only for kernel 4.19. On 4.18 and below there are no problems. But with vcpkg inside docker problem happens regardless of the kernel version.
See: https://github.com/docker/for-linux/issues/480

**Comment by Cheney-W** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/4245
