### ISSUE TITLE
xtensor failed to build (seriously, make a copy of some files)

### ISSUE THREAD

**Issue by degski** [microsoft/vcpkg#7085]
The following packages will be built and installed:
    xtensor[core,xsimd]:x64-windows-static
Starting package 1/1: xtensor:x64-windows-static
Building package xtensor[core,xsimd]:x64-windows-static...
CMake Error at scripts/ports.cmake:37 (message):
  Unsupported target triplet.  Triplet file does not exist:

Error: Building package xtensor:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: xtensor:x64-windows-static
  Vcpkg version: 2019.06.21-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by myd7349** [comment]
I have reproduced this error, and solved by recompling `vcpkg.exe`:
> E:\vcpkg>cd
E:\vcpkg
>
>E:\vcpkg>bootstrap-vcpkg.bat
>
>Building vcpkg.exe ..

**Comment by degski** [comment]
@myd7349 Indeed! Thank you, I did not think of that as I did rebuild `vcpkg` very recently.

**Comment by Mun1z** [comment]
I'ts do'nt worked for me =/

> I have reproduced this error, and solved by recompling `vcpkg.exe`:
> 
> > E:\vcpkg>bootstrap-vcpkg.bat
> > Building vcpkg.exe ..

**Comment by degski** [comment]
@Mun1z You did not forget `git pull` by any chance (before the rebuild)?
