### ISSUE TITLE
Error: Building package zlib:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by smartseal** [microsoft/vcpkg#7088]
-- The C compiler identification is MSVC 19.0.24234.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe -- broken
CMake Error at E:/github/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/share/cmake-3.14/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: E:/github/vcpkg/buildtrees/zlib/x86-windows-rel/CMakeFiles/CMakeTmp
    
    Run Build Command(s):E:/github/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe cmTC_37a29 
    [1/2] Building C object CMakeFiles\cmTC_37a29.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_37a29.exe
    FAILED: cmTC_37a29.exe 
    cmd.exe /C "cd . && E:\github\vcpkg\downloads\tools\cmake-3.14.0-windows\cmake-3.14.0-win32-x86\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_37a29.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~2\MICROS~1.0\VC\bin\AMD64_~2\link.exe /nologo CMakeFiles\cmTC_37a29.dir\testCCompiler.c.obj  /out:cmTC_37a29.exe /implib:cmTC_37a29.lib /pdb:cmTC_37a29.pdb /version:0.0  /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /foCMakeFiles\cmTC_37a29.dir/manifest.res CMakeFiles\cmTC_37a29.dir/manifest.rc" failed (exit code 0) with the following output:
    系统找不到指定的文件。
    ninja: build stopped: subcommand failed.
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)

-- Configuring incomplete, errors occurred!
See also "E:/github/vcpkg/buildtrees/zlib/x86-windows-rel/CMakeFiles/CMakeOutput.log".
See also "E:/github/vcpkg/buildtrees/zlib/x86-windows-rel/CMakeFiles/CMakeError.log".
ninja: build stopped: subcommand failed.

**Comment by Voskrese** [comment]
cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_37a29.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests

**Comment by smartseal** [comment]
mt.exe? Is it a tool packaged with vcpkg?

**Comment by smartseal** [comment]
I found mt.exe in the windows sdk directory, but vcpkg didn't find it.
How should I config it?

C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x86\mt.exe

**Comment by Voskrese** [comment]
`vcpkg env --triplet x86-windows --debug`

`where mt.exe`

**Comment by smartseal** [comment]
e:\github\vcpkg>vcpkg env --triplet x86-windows --debug
[DEBUG] Using vcpkg-root: e:\github\vcpkg
[DEBUG] _wpopen(""e:\github\vcpkg\downloads\tools\cmake-3.14.0-windows\cmake-3.14.0-win32-x86\bin\cmake.exe" --version 2>&1")
[DEBUG] _pclose() returned 0 after   279667 us
[DEBUG] _wpopen(""e:\github\vcpkg\downloads\tools\cmake-3.14.0-windows\cmake-3.14.0-win32-x86\bin\cmake.exe" "-DCMAKE_TRIPLET_FILE=e:/github/vcpkg/triplets/x86-windows.cmake" -P "e:/github/vcpkg/scripts/get_triplet_environment.cmake" 2>&1")
[DEBUG] _pclose() returned 0 after    80964 us
[DEBUG] _wpopen(""C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease -legacy -products * -format xml 2>&1")
[DEBUG] _pclose() returned 0 after    55285 us
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
Please install the English language pack.
[DEBUG] CreateProcessW(cmd.exe /c ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"  amd64_x86   2>&1 <NUL && cmd")
Microsoft Windows [Version 10.0.14393]

**Comment by smartseal** [comment]
where can I download english language pack for vs 2017 community?

**Comment by smartseal** [comment]
this is not closed? why is it marked as close?

**Comment by Voskrese** [comment]
what are you talking about? I do not see any marks at all) although I should close
VCPKG requires the installation of the English locale, because in the parameters forcibly worth 1033

**Comment by Voskrese** [comment]
english language pack for Microsoft **Visual Studio 14.0** ? ))

**Comment by smartseal** [comment]
I compile using another machine using vcpkg, which is ok. Then I copied it back to my machine and do the rest developing works. 
I close this issue for now. And thanks
