### ISSUE TITLE
[opengl] installation fails with Windows SDK version 8.1

### ISSUE THREAD

**Issue by brupelo** [Microsoft/vcpkg#709]
I'm trying to use opengl32.lib with vs2015 but it seems adding opengl32.lib on the linker input libs won't do it... isn't opengl shipped with vs2015 by default? Anyway, because this fact I decide installing it using vcpkg, so I open a prompt and I run `vcpkg install opengl`, the output is this:

    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC>vcpkg install opengl
    -- CURRENT_INSTALLED_DIR=D:/software/vcpkg/installed/x86-windows
    -- DOWNLOADS=D:/software/vcpkg/downloads
    -- CURRENT_PACKAGES_DIR=D:/software/vcpkg/packages/opengl_x86-windows
    -- CURRENT_BUILDTREES_DIR=D:/software/vcpkg/buildtrees/opengl
    -- CURRENT_PORT_DIR=D:/software/vcpkg/ports/opengl/.
    CMake Error at ports/opengl/portfile.cmake:11 (message):
      Portfile not yet configured for Windows SDK with version: 8.1
    Call Stack (most recent call first):
      scripts/ports.cmake:73 (include)

    Error: Building package opengl:x86-windows failed with: BUILD_FAILED
    Please ensure sure you're using the latest portfiles with `.\vcpkg update`, then

    submit an issue at https://github.com/Microsoft/vcpkg/issues including:
      Package: opengl:x86-windows
      Vcpkg version: 0.0.74-fa3f9dd9628ebafd3ba65fb3abde6c1d6f0448fc

    Additionally, attach any relevant sections from the log files above.

Any idea how to solve this?

**Comment by brupelo** [comment]
Additional note here, it seems the problem with the missing opengl library on visual studio was because one row of my linker input was:

opengl32.lib kernel32.lib
user32.lib

It seems you need to put libraries on different rows... Not sure if this issue is relevant anymore... I mean, yeah, trying to install opengl fails but it's shipped with vs anyway, so... I'll leave it open for the time being

**Comment by alexkaratarakis** [comment]
ec02f5bb264af821369fd6de9028758ae12447f1 should fix this.

**Comment by brupelo** [comment]
@alexkaratarakis Thanks, your commit did the job perfectly :)
