### ISSUE TITLE
build tesseract:x64-linux error

### ISSUE THREAD

**Issue by liangshoulong** [microsoft/vcpkg#7096]
CMake Error at ports/tesseract/portfile.cmake:34 (file):
  file COPY cannot find
  "/home/lsl/vcpkg/packages/tesseract_x64-linux/bin/tesseract.exe".
Call Stack (most recent call first):
  scripts/ports.cmake:73 (include)

**Comment by wangli28** [comment]
Hi @liangshoulong, Thanks for posting this issue. Maybe your VCPKG version is old, I installed `tesseract:x64-linux` failed on the latest VCPKG and got this error. This is a port bug.
```
CMake Error at /home/vwangli/Lily/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
Call Stack (most recent call first):
  /home/vwangli/Lily/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /home/vwangli/Lily/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/share/cmake-3.14/Modules/FindPkgConfig.cmake:41 (find_package_handle_standard_args)
  /home/vwangli/Lily/vcpkg/scripts/buildsystems/vcpkg.cmake:266 (_find_package)
  CMakeLists.txt:96 (find_package)
```

**Comment by zhbanito** [comment]
Port need correction from line 38:
`set(EXTENSION )
if(WIN32)
   set(EXTENSION ".exe")
endif()
file(COPY ${CURRENT_PACKAGES_DIR}/bin/tesseract${EXTENSION} DESTINATION ${CURRENT_PACKAGES_DIR}/tools/tesseract)`

**Comment by wangli28** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
