### ISSUE TITLE
[openssl] Generate suffixed debug libraries

### ISSUE THREAD

**Issue by ras0219-msft** [microsoft/vcpkg#710]
The default OpenSSL build produced debug libraries that are _not_ suffixed with "d". This means that CMake's "FindOpenSSL" module is unable to properly generate library variables compatible with Multi-Configuration generators (like Visual Studio).

Workaround: Generate two separate VS solutions, one with `-DCMAKE_BUILD_TYPE=Release` and one with `-DCMAKE_BUILD_TYPE=Debug`. Only build release from the release solution and debug from the debug solution.

Found in #675.

**Comment by JackBoosY** [comment]
@ras0219-msft  Any suggestions? I will fix this issue later.

**Comment by JackBoosY** [comment]
Related: #5543.

**Comment by Neumann-A** [comment]
see PR #6409

**Comment by Neumann-A** [comment]
The easy fix for this one is install a vcpkg-cmake-wrapper for it which simply defines LIB_EAY_DEBUG SSL_EAY_DEBUG as well as the according _RELEASE variables before the find_package call . This makes the subsequent find_library calls in FindOpenSSL do nothing without changing the general behavior of the module. Also defining the release variables is only required to generate similar imported targets on Linux as on Windows. The FindOpenSSL module does only differentiate between DEBUG/RELEASE on Windows.

**Comment by dg0yt** [comment]
Is this issue still valid?

**Comment by JackBoosY** [comment]
@dg0yt Nope, although openssl libraries were renamed to `libssl` / `libcrypto`, the debug suffix is still empty.

**Comment by dg0yt** [comment]
@JackBoosY I don't understand the answer, but perhaps my question wasn't clear enough. Reworded:

Does vcpkg still need a debug postfix for openssl?

Possible reasons:
 - Upstream uses a debug postfix.
 - Vcpkg is unable to handle debug variants without debug postfix.
 - Users are unable to handle debug variants without debug postfix.

**Comment by Neumann-A** [comment]
@dg0yt did you close this issue with the openssl wrapper PR?

**Comment by dg0yt** [comment]
@Neumann-A I did not implement "Generate suffixed debug libraries".

But I added the `find_library` calls to the wrapper. 
I even validated the wrapper as part of my validation PR, but I guess this piece of code will be lost before the vcpkg team reached a consensus on an interface for validation. 😞

**Comment by Neumann-A** [comment]
@JackBoosY this can be closed
