### ISSUE TITLE
Question: could we skip SHA512 validation when use REF to download form github?

### ISSUE THREAD

**Issue by lennonwoo** [microsoft/vcpkg#7100]
I wanna use vcpkg's vcpkg_from_github function to download certain tag via REF in `portfile.cmake`, the template command is as follow.
```
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO ORG_NAME/REPO_NAME
    REF tag_name
)
```

The problem is that there are lots of ROS packages that I need to generate their `portfile.cmake`(I am a GSoC student working on using vcpkg to build ROS pacakges), and I couldn't determine the SHA512 during `portfile.cmake`'s template expansion time.

But in vcpkg, we must append the SHA512 if we want to download from certain tag. Could we add an option to skip SHA512 when use vcpkg_from_xxx related functions, or are there some reason like sha512 is needed for cache or something else that make thing hard?

**Comment by cenit** [comment]
why not keeping a list of sha512 together with your list of refs?

**Comment by invy** [comment]
This actually corellates with my issue: #6707 

It makes no sense to check for checksume while fetching from git, because git takes care of the validith of the revisions.
I think same approach could be taken here.

**Comment by vicroms** [comment]
@lennonwoo  

Here's how you can obtain the `SHA512` for your ports:

1. In your `portfile.cmake` file put any placeholder string as the value for `SHA512`
2. Try to install your portfile `./vcpkg install my-port`, it should fail and show something like this:
    ```
    File does not have expected hash:
              File path: [ D:/vcpkg/downloads/my-port-REF.tar.gz ]
          Expected hash: [ PLACEHOLDER_STRING_TO_BE_REPLACED_WITH_REAL_HASH ]
            Actual hash: [ 2e82a4bddcd6c4669541f5945c2d240fb1b4fdd6e239200246d3dd50ce98733f0a4f6d3daa56f865d8c88779c036099c52a9ae85d47ad263686b68a88d832dff ]
    ```
3. Copy the `Actual hash:` in your `portfile.cmake` file.

@invy 
That is not a problem when fetching archives from **GitHub**. 

Hash values for archives from GitHub have been consistent regardless of platform, the only times that a SHA512 changes is when a tag gets pointed to a different revision by upstream projects.

**Comment by lennonwoo** [comment]
@vicroms 

This is a solution if I could post-sed my generated `portfile.cmake`. But I still wanna an option to skip SHA512 when we use vcpkg_from_xxx related functions.

**Comment by vicroms** [comment]
A PR has been merged to enable skipping the SHA512 validation when using `vcpkg_from_git()`.

It is required that:

* the package URL has to be `https://`,
* the REF has to be stable, i.e. a Git commit hashes.

I'll bring the discussion to the team to enable the same approach for similar functions.

**Comment by invy** [comment]
@vicroms it's not the problem while fetching from github, you are correct, but the SHA check stil has less sense here. Furthermore, what is the point of having vcpkg_from_github, vcpkg_from_gitlab, when this functionality can be perfectly covered by vcpkg_from_git.

**Comment by PhoebeHui** [comment]
If it is still an issue, please reopen
