### ISSUE TITLE
Error: Building package sdl2:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Predelnik** [microsoft/vcpkg#7106]
Package: sdl2:x86-windows
Vcpkg version: 2019.06.21-nohash

Just trying to do the basic things from readme. It's probably some issue with my configuration.

Log:
https://gist.github.com/Predelnik/8e4ebb8f6855e9749fdd9c9998b856f7

Basically cmake tests fail with
> LINK : fatal error LNK1104: cannot open file 'ucrtd.lib'

I have tried updating cmake, setting `DCMAKE_SYSTEM_VERSION` manually in triplet, installing specific SDK version which I found in some other issue as supposed solution, nothing seems to have any effect.

Running `cmake` standalone, it passes tests for msvc 2019 just fine. What am I missing here?

**Comment by Voskrese** [comment]
CMAKE_SYSTEM_VERSION stopped working, apparently something changed
But  VCPKG_CMAKE_SYSTEM_VERSION doesn't work the same way
https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md

SDK is selected for some reason that last installed

**Comment by Predelnik** [comment]
@Voskrese gave me an idea. I noticed that I have "windows driver kit" installed  which has higher version than rest of normal kits for some reason in my case it was 10.0.18362.0 and my latest currently installed sdk is 10.0.17763.0.  This driver kit seems to miss ucrt stuff. After uninstalling it everything seems to work. Maybe this is a rare case but I still think that this is valid issue which other people might also face it in some cases and find puzzling, feel free to close this but I think that proper solution for configurations such as this also might need to be implemented.

**Comment by yuehuang010** [comment]
I hit this error and found that that it was using a different version of CMake.  Could you start a clean cmd and allow vcpkg to download its own CMake.

**Comment by Predelnik** [comment]
I definteily had separate cmake install but I'm not sure if vcpkg was using or not, it was one of the latest vesions anyway.

The problem is that I already fixed this as I described in the comment so I can't reproduce it now, but I strongly believe that removing windows driver kit made this issue solved. Maybe someone should try to install it and see if it is reproduced.

**Comment by PhoebeHui** [comment]
I tried but I can't repro this issue, the ucrt library installed correctly for all window sdk revision for me.
