### ISSUE TITLE
Realsense2 postbuild validation fails

### ISSUE THREAD

**Issue by claudiofantacci** [microsoft/vcpkg#7109]
Package: realsense2:x64-windows
Vcpkg version: 2019.06.21-nohash

`realsense` tools release compilation process generates a `realsense-gl.lib` that however is not present in the debug build because tools are disabled.
As a result, the following error occurs. 

```
❯ vcpkg install realsense2[tools]
The following packages will be built and installed:
    realsense2[core,tools]:x64-windows
Starting package 1/1: realsense2:x64-windows
Building package realsense2[core,tools]:x64-windows...
-- Using cached C:/Users/cfantacci/vcpkg/downloads/IntelRealSense-librealsense-v2.22.0.tar.gz
-- Extracting source C:/Users/cfantacci/vcpkg/downloads/IntelRealSense-librealsense-v2.22.0.tar.gz
-- Applying patch fix_openni2.patch
-- Using source at C:/Users/cfantacci/vcpkg/buildtrees/realsense2/src/v2.22.0-b9e8f8bf6e
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
Mismatching number of debug and release binaries. Found 2 for debug but 3 for release.
Debug binaries

    C:/Users/cfantacci/vcpkg/packages/realsense2_x64-windows/debug/lib/realsense-filed.lib
    C:/Users/cfantacci/vcpkg/packages/realsense2_x64-windows/debug/lib/realsense2d.lib

Release binaries

    C:/Users/cfantacci/vcpkg/packages/realsense2_x64-windows/lib/realsense-file.lib
    C:/Users/cfantacci/vcpkg/packages/realsense2_x64-windows/lib/realsense2-gl.lib
    C:/Users/cfantacci/vcpkg/packages/realsense2_x64-windows/lib/realsense2.lib


Mismatching number of debug and release binaries. Found 1 for debug but 2 for release.
Debug binaries

    C:/Users/cfantacci/vcpkg/packages/realsense2_x64-windows/debug/bin/realsense2d.dll

Release binaries

    C:/Users/cfantacci/vcpkg/packages/realsense2_x64-windows/bin/realsense2-gl.dll
    C:/Users/cfantacci/vcpkg/packages/realsense2_x64-windows/bin/realsense2.dll


Found 2 error(s). Please correct the portfile:
    C:\Users\cfantacci\vcpkg\ports\realsense2\portfile.cmake
-- Performing post-build validation done
Error: Building package realsense2:x64-windows failed with: POST_BUILD_CHECKS_FAILED
```

Is there a way to bypass/skip/disable this postbuild check or is there another way to get it through?

**Comment by vicroms** [comment]
As of now there's no way to disable this post-build validation.
The easiest workaround would be to also build the tools for the debug configuration.

The right fix would be to provide a way to disable the post-build check using a `VCPKG_POLICY_` that can be set in a per port-file basis.

**Comment by claudiofantacci** [comment]
Hi @vicroms thanks for reaching  out 👍 

> The right fix would be to implement a way to disable the post-build check using a `VCPKG_POLICY_` that can be set in a per port-file basis.

That would be ideal as some of the post-build checks may not apply, in general, for all libraries.
My understanding is that this is something that is not present yet and should be implemented by a `vcpkg` developer/maintainer. Am I right?
Otherwise, I would be happy to update the port with a specific policy, although I found nothing about `VCPKG_POLICY_` that, by the trailing underscore, seems a "private" `vcpkg` variable.

**Comment by vicroms** [comment]
You're correct, it is not implemented yet. 

An example of an existing policy can be seen in the `openssl` port, where we use `set(VCPKG_POLICY_EMPTY_PACKAGE enabled)` to mark the port as a sort of meta-package.

**Comment by claudiofantacci** [comment]
Got it 👍 

Well, my two cents here is that policy to skip this particular post-build check is particularly useful to have in `vcpkg` sleeve 😄

**Comment by PhoebeHui** [comment]
I added a workaround for removing the mismatch dlls and libs, so this issue shouldn't block you now, please get latest source and try again, I will let this issue active to track the feature status.

**Comment by davidbun** [comment]
Compilation is failed in the different location
The log is hereunder:
======
Building package realsense2[core]:x64-windows...
-- Using cached C:/vcpkg/downloads/IntelRealSense-librealsense-v2.22.0.tar.gz
CMake Error at scripts/cmake/vcpkg_extract_source_archive_ex.cmake:87 (file):
  file SHA512 failed to read file
  "C:/vcpkg/ports/realsense2/fix_openni2.patch": No such file or directory
Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:114 (vcpkg_extract_source_archive_ex)
  ports/realsense2/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:91 (include)


Error: Building package realsense2:x64-windows failed with: BUILD_FAILED

**Comment by davidbun** [comment]
The build line is one of 3 - all of them give the same error message
.\vcpkg install realsense2
.\vcpkg install realsense2[core, tools]
.\vcpkg install realsense2[core, tools, openni2]

**Comment by PhoebeHui** [comment]
Does C:/vcpkg/ports/realsense2/fix_openni2.patch exist? could you double check?

**Comment by davidbun** [comment]
C:/vcpkg/ports/realsense2/fix_openni2.patch does not exist

**Comment by PhoebeHui** [comment]
Please checkout that file, and try again.

**Comment by PhoebeHui** [comment]
@davidbun, I checked, the patch exist in source, see https://github.com/microsoft/vcpkg/blob/master/ports/realsense2/fix_openni2.patch, it looks your local source has something wrong, you need pull or clone vcpkg source.

For updating the revision, we update many ports revision to latest in regular, but if you need some specific changes in latest release, then you can report an issue(issue template 'Request an update to an existing port'),  then we will consider to update it in priority.

**Comment by JackBoosY** [comment]
Should be fixed.
