### ISSUE TITLE
vcpkg install vtk:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by fps92** [microsoft/vcpkg#7111]
Hey,
after successfully installing szip:x64-windows and some other packages with vcpkg I ran into another problem while trying to install pcl:x64-windows...

Using Windows 7 and VS 2017
![MSVC Components](https://user-images.githubusercontent.com/52284319/60445954-9f7a7500-9c20-11e9-92ac-c98d20317139.PNG)

**PS D:\vcpkg> .\vcpkg install pcl:x64-windows**
The following packages will be built and installed:
    pcl[core]:x64-windows
  * vtk[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/57: vtk:x64-windows
Building package vtk[core]:x64-windows...
-- Using cached D:/vcpkg/downloads/Kitware-VTK-v8.2.0.tar.gz
-- Using source at D:/vcpkg/buildtrees/vtk/src/v8.2.0-b37306c27c
-- Configuring x64-windows
**CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):**
    Command failed: ninja;-v
    Working Directory: D:/vcpkg/buildtrees/vtk/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\vtk\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:282 (vcpkg_execute_required_process

  ports/vtk/portfile.cmake:107 (vcpkg_configure_cmake)
  scripts/ports.cmake:73 (include)

**Error: Building package vtk:x64-windows failed with: BUILD_FAILED**
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: vtk:x64-windows
  Vcpkg version: 2019.06.21-nohash

Additionally, attach any relevant sections from the log files above.

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/3344845/config-x64-windows-out.log)
[vcpkg_configure_cmake.txt](https://github.com/microsoft/vcpkg/files/3344865/vcpkg_configure_cmake.txt)
[environment.txt](https://github.com/microsoft/vcpkg/files/3345206/environment.txt)

**Comment by Voskrese** [comment]
```
CMake Error at CMakeLists.txt:156 (export):
  export EXPORT or TARGETS specifier missing.
```

**Comment by fps92** [comment]
How can i counteract this?

**Comment by Voskrese** [comment]
`Error at CMakeLists.txt:156`

edit `D:/vcpkg/buildtrees/vtk/src/v8.2.0-b37306c27c/CMakeLists.txt` str `156`

**Comment by fps92** [comment]
@Voskrese First of all: Thanks for your help!

Am I right with the  `vcpkg edit <pkg>` -command? 
This is what i get:



```
PS D:\vcpkg> .\vcpkg edit vtk
**Error: Visual Studio Code was not found and the environment variable EDITOR is not set or invalid.**
The following paths were examined:

    C:/Program Files/Microsoft VS Code Insiders/Code - Insiders.exe
    C:/Program Files/Microsoft VS Code/Code.exe
    C:/Program Files (x86)/Microsoft VS Code Insiders/Code - Insiders.exe
    C:/Program Files (x86)/Microsoft VS Code/Code.exe
    C:/Users/frsp/AppData/Local/Programs/Microsoft VS Code Insiders/Code - Insiders.exe
    C:/Users/frsp/AppData/Local/Programs/Microsoft VS Code/Code.exe

You can also set the environmental variable EDITOR to your editor of choice.
```

**Comment by fps92** [comment]
> `Error at CMakeLists.txt:156`
> 
> edit `D:/vcpkg/buildtrees/vtk/src/v8.2.0-b37306c27c/CMakeLists.txt` str `156`

what do you mean by "edit"?
I don't know what these ports are and where to link to... :(

**Comment by wangli28** [comment]
Same with #6889

**Comment by fps92** [comment]
@wangli28 Thanks for your help
I already ran into issue #6889 , but for me it did not help...

It runs this error after the modification of the _CMakeLists.exe_ in  _...\vcpkg\buildtrees\vtk\src\v8.2.0-b37306c27c_

```
PS D:\vcpkg> .\vcpkg install vtk[core]:x64-windows
The following packages will be built and installed:
    vtk[core]:x64-windows
Starting package 1/1: vtk:x64-windows
Building package vtk[core]:x64-windows...
-- Using cached D:/vcpkg/downloads/Kitware-VTK-v8.2.0.tar.gz
-- Using source at D:/vcpkg/buildtrees/vtk/src/v8.2.0-b37306c27c
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v
    Working Directory: D:/vcpkg/buildtrees/vtk/x64-windows-dbg
    See logs for more information:
      D:\vcpkg\buildtrees\vtk\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/vtk/portfile.cmake:134 (vcpkg_install_cmake)
  scripts/ports.cmake:73 (include)


Error: Building package vtk:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: vtk:x64-windows
  Vcpkg version: 2019.06.21-nohash

Additionally, attach any relevant sections from the log files above.
```

**Comment by fps92** [comment]
After trying to install vtk:x86-windows I ended up with a nearly similar error.


```
PS C:\Users\frsp> vcpkg install vtk:x86-windows
The following packages will be built and installed:
 
...

Building package bzip2[core]:x86-windows... done
Installing package bzip2[core]:x86-windows...
Installing package bzip2[core]:x86-windows... done
Elapsed time for package bzip2:x86-windows: 19.86 s
...
Building package libpng[core]:x86-windows... done
Installing package libpng[core]:x86-windows...
Installing package libpng[core]:x86-windows... done
Elapsed time for package libpng:x86-windows: 19.74 s
...
Building package freetype[core]:x86-windows... done
Installing package freetype[core]:x86-windows...
Installing package freetype[core]:x86-windows... done
Elapsed time for package freetype:x86-windows: 20.37 s
...
Starting package 4/27: **glew:x86-windows
Building package glew[core]:x86-windows...
-- Using cached D:/vcpkg/downloads/glew-2.1.0.tgz
-- Using source at D:/vcpkg/buildtrees/glew/src/glew-58abdfb190
-- Configuring x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:58 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" D:/vcpkg/buildtrees/g
lew/src/glew-58abdfb190/build/cmake -DBUILD_UTILS=OFF -DBUILD_SHARED_LIBS=ON -DV
CPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/vcpkg/scripts/toolchains/windows.cmake -DVCPKG_
TARGET_TRIPLET=x86-windows -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=
v141 -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGIS
TRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM
_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -D
CMAKE_TOOLCHAIN_FILE=D:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_
ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -D
VCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS
_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_TARGET_ARCHITE
CTURE=x86 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -G
 "Visual Studio 15 2017" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=D:/vcpk
g/packages/glew_x86-windows/debug
    Working Directory: D:/vcpkg/buildtrees/glew/x86-windows-dbg
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\glew\config-x86-windows-dbg-out.log
      D:\vcpkg\buildtrees\glew\config-x86-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:291 (vcpkg_execute_required_process)

  ports/glew/portfile.cmake:19 (vcpkg_configure_cmake)
  scripts/ports.cmake:73 (include)


Error: Building package glew:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glew:x86-windows
  Vcpkg version: 2019.06.21-nohash

Additionally, attach any relevant sections from the log files above.
PS C:\Users\frsp>
```
[config-x86-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/3353889/config-x86-windows-dbg-err.log)
[config-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3353891/config-x86-windows-dbg-out.log)


same while installing vtk[core]:x64-windows the glew package is the problem...

**Comment by fps92** [comment]
Okay this failure ist occured by the **wrong version of CMake**.

The vtk-package needs cmake **v3.14.0**
On my device cmake **v3.15.x** was installed. 
After uninstalling cmake, vcpkg downloaded the needed version of CMake and it worked.

**Comment by xiefeihua** [comment]
thx ！！！

**Comment by Archetype90** [comment]
This solution worked for me as well (uninstalling cmake and allow vcpkg to grab the correct version). I did have an error after it downloaded cmake, and chose to restart my PC. After that everything worked great!

**Comment by zdptrsz** [comment]
> Okay this failure ist occured by the **wrong version of CMake**.
> 
> The vtk-package needs cmake **v3.14.0**
> On my device cmake **v3.15.x** was installed.
> After uninstalling cmake, vcpkg downloaded the needed version of CMake and it worked.

how to uninstal cmake,I also need to uninstall cmake

**Comment by zdptrsz** [comment]
> Downgrading CMake from 3.15.2 to 3.14.6 worked for me. Nevertheless, the error reporting from vcpkg should probably be improved.

how Downgrading ?
