### ISSUE TITLE
Builed failed server returned nothing no headers no data

### ISSUE THREAD

**Issue by HassanQayyum1993** [microsoft/vcpkg#7113]
C:\Program Files (x86)\vcpkg>vcpkg install openssl
The following packages will be built and installed:
    openssl[core]:x86-windows
  * openssl-windows[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: openssl-windows:x86-windows
Building package openssl-windows[core]:x86-windows...
-- Using cached C:/Program Files (x86)/vcpkg/downloads/openssl-1.0.2q.tar.gz
-- Using source at C:/Program Files (x86)/vcpkg/buildtrees/openssl-windows/src/openssl-1-4adeeb536f
-- Downloading http://download.qt.io/official_releases/jom/jom_1_1_3.zip...
-- Downloading http://download.qt.io/official_releases/jom/jom_1_1_3.zip... Failed. Status: 52;"Server returned nothing (no headers, no data)"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:172 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:262 (vcpkg_download_distfile)
  ports/openssl-windows/portfile.cmake:41 (vcpkg_find_acquire_program)
  scripts/ports.cmake:73 (include)

Error: Building package openssl-windows:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-windows:x86-windows
  Vcpkg version: 2019.06.21-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by cskrisz** [comment]
It's working for me now. Would you try again?

**Comment by HassanQayyum1993** [comment]
Still not working. I think if send https request it will work, as I opened the link manualy but can't open with http could tell where the link is placed so I can change it to https

**Comment by cskrisz** [comment]
In `scripts\cmake\vcpkg_find_acquire_program.cmake`.

**Comment by HassanQayyum1993** [comment]
Thanks it worked

**Comment by wangli28** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
