### ISSUE TITLE
Windows.h not found while building package openssl-windows:x64-windows failed with

### ISSUE THREAD

**Issue by singh0506** [microsoft/vcpkg#7115]
I am building `openssl-windows:x64-windows` using vckpg, but got error like windows.h file not found.
console log:

```
c:\workspaceForvcpkg\vcpkg>.\vcpkg install stimgen:x64-windows
The following packages will be built and installed:
  * clara[core]:x64-windows
  * jsoncpp[core]:x64-windows
  * libzip[bzip2,core,openssl]:x64-windows
  * openssl[core]:x64-windows
  * openssl-windows[core]:x64-windows
    stimgen[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/6: openssl-windows:x64-windows
Building package openssl-windows[core]:x64-windows...
-- Using cached C:/workspaceForvcpkg/vcpkg/downloads/openssl-1.0.2q.tar.gz
-- Using source at C:/workspaceForvcpkg/vcpkg/buildtrees/openssl-windows/src/openssl-1-4adeeb536f
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x64-windows-rel
-- Configure x64-windows-rel done
-- Build x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: nmake;-f;ms\ntdll.mak;install
    Working Directory: C:/workspaceForvcpkg/vcpkg/buildtrees/openssl-windows/x64-windows-rel
    Error code: 2
    See logs for more information:
      C:\workspaceForvcpkg\vcpkg\buildtrees\openssl-windows\build-x64-windows-rel-1-out.log
      C:\workspaceForvcpkg\vcpkg\buildtrees\openssl-windows\build-x64-windows-rel-1-err.log

Call Stack (most recent call first):
  ports/openssl-windows/portfile.cmake:112 (vcpkg_execute_required_process)
  scripts/ports.cmake:71 (include)


Error: Building package openssl-windows:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-windows:x64-windows
  Vcpkg version: 2018.11.23-nohash
[build-x64-windows-rel-1-err.log](https://github.com/microsoft/vcpkg/files/3346480/build-x64-windows-rel-1-err.log)
[build-x64-windows-rel-1-out.log](https://github.com/microsoft/vcpkg/files/3346481/build-x64-windows-rel-1-out.log)

Additionally, attach any relevant sections from the log files above.
```

**Comment by Voskrese** [comment]
`vcpkg env --triplet x64-windows --debug`

`where $include:windows.h`

**Comment by singh0506** [comment]
thanks voskrese for your reply. But still issues is not resolved. can you please see below console log.

c:\workspaceforvcpkg\vcpkg>.\vcpkg env --triplet x64-windows --debug
[DEBUG] Using vcpkg-root: c:\workspaceforvcpkg\vcpkg
[DEBUG] Found path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe
[DEBUG] _wpopen(""c:\workspaceforvcpkg\vcpkg\downloads\tools\cmake-3.14.0-windows\cmake-3.14.0-win32-x86\bin\cmake.exe" --version 2>&1")
[DEBUG] _pclose() returned 0 after   142769 us
[DEBUG] _wpopen(""c:\workspaceforvcpkg\vcpkg\downloads\tools\cmake-3.14.0-windows\cmake-3.14.0-win32-x86\bin\cmake.exe" "-DCMAKE_TRIPLET_FILE=c:/workspaceforvcpkg/vcpkg/triplets/x64-windows.cmake" -P "c:/workspaceforvcpkg/vcpkg/scripts/get_triplet_environment.cmake" 2>&1")
[DEBUG] _pclose() returned 0 after    69726 us
[DEBUG] _wpopen(""C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease -legacy -products * -format xml 2>&1")
[DEBUG] _pclose() returned 0 after    74304 us
[DEBUG] CreateProcessW(cmd.exe /c ""C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\Build\vcvarsall.bat" -vcvars_ver=14.1 amd64   2>&1 <NUL && cmd")
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.13
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
Microsoft Windows [Version 10.0.17134.765]
(c) 2018 Microsoft Corporation. All rights reserved.

c:\workspaceforvcpkg\vcpkg>where $include:windows.h
INFO: Could not find files for the given pattern(s).

**Comment by Voskrese** [comment]
`where $include:windows.h`
C:\Program Files (x86)\**Windows Kits\10**\Include\10.0.17763.0\um\Windows.h

reinstall Win SDK

**Comment by singh0506** [comment]
even if windows.h is there on path C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um in my machine. But while using cmd "where $include:windows.h" , it's not finding out.

moreover, I am having winsdk 10 all version. But still facing this problem

note: I am using VS2017 on window 10.

**Comment by Voskrese** [comment]
still installed Win SDK ? versions which?

**Comment by singh0506** [comment]
![image](https://user-images.githubusercontent.com/52322026/60507419-c0f16480-9ce5-11e9-86b0-7f774f8d7129.png)


please find attached file , you can see sdk version.

**Comment by Voskrese** [comment]
` C:\Program Files (x86)\ Windows Kits\10 \Include\10.0.18362.0\um\Windows.h` ?

**Comment by singh0506** [comment]
yes. it is there.

**Comment by Voskrese** [comment]
`vcpkg env --triplet x64-windows --debug`

`where mt`

**Comment by PhoebeHui** [comment]
@singh0506, I guess this issue also solved, right?
