### ISSUE TITLE
Error: Building package opencv:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by robohoss** [microsoft/vcpkg#7119]
Error: Building package opencv:x64-windows failed with: BUILD_FAILED

Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv:x64-windows
  Vcpkg version: 2019.06.21-nohash

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3347700/install-x64-windows-dbg-out.log)

**Comment by cskrisz** [comment]
```
fatal error C1088: Cannot flush compiler intermediate file: 'C:\Users\Bryan\AppData\Local\Temp\_CL_16c240e6db': No space left on device
```
You ran out of space.

**Comment by robohoss** [comment]
Thanks!  I freed-up some disk space and the build completed normally.
