### ISSUE TITLE
Linking issue with libnoise

### ISSUE THREAD

**Issue by n42k** [microsoft/vcpkg#7121]
After successful installation of libnoise, upon compiling the following code, I get linker errors:

```
#include <noise/noise.h>
#include <iostream>

int main(int argc, char* argv[]) {
	noise::module::Perlin p;
	std::cout << p.GetValue(0.5, 0.5, 0.5) << std::endl;
}
```

Errors:
```
1>main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl noise::module::Perlin::Perlin(void)" (__imp_??0Perlin@module@noise@@QEAA@XZ) referenced in function main
1>main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual double __cdecl noise::module::Perlin::GetValue(double,double,double)const " (__imp_?GetValue@Perlin@module@noise@@UEBANNNN@Z) referenced in function main
1>main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl noise::module::Perlin::~Perlin(void)" (__imp_??1Perlin@module@noise@@UEAA@XZ) referenced in function main
```

I have a working vcpkg installation, along with user-wide integration: I can use other libraries such as libpng.

I've tested with both a x86 and x64 build on MSVS, with libnoise:x86-windows and libnoise:x64-windows, version 1.0.0, both giving the same errors.

Is this a configuration issue on my side, or a problem with the portfile? Can someone replicate the errors?

**Comment by Voskrese** [comment]
libnoise statically linked?

**Comment by myd7349** [comment]
https://github.com/RobertHue/libnoise/blob/d7e68784a2b24c632868506780eba336ede74ecd/src/noise/module/modulebase.h#L33-L43

**Comment by n42k** [comment]
Using `libnoise:x86-windows-static` or `libnoise:x64-windows-static` results in the same error.

**Comment by percentcer** [comment]
I've run into the same issue. @n42k, were you able to resolve it?

**Comment by n42k** [comment]
Negative, did no progress on the issue.

**Comment by JackBoosY** [comment]
Hi @n42k, thanks for reporting this issue!
To use `libnoise-static`, please add **NOISE_STATIC** to the precompiled macro.

Thanks.
