### ISSUE TITLE
libxslt:x64-osx  broken

### ISSUE THREAD

**Issue by augustblack** [microsoft/vcpkg#7132]
The following packages will be built and installed:
    libxslt[core]:x64-osx
Starting package 1/1: libxslt:x64-osx
Building package libxslt[core]:x64-osx...
-- Downloading https://github.com/GNOME/libxslt/archive/v1.1.33.tar.gz...
-- Extracting source /Users/augustblack/vcpkg/downloads/GNOME-libxslt-v1.1.33.tar.gz
-- Applying patch 0001-Fix-makefile.patch
-- Using source at /Users/augustblack/vcpkg/buildtrees/libxslt/src/v1.1.33-742f11ffe2
-- Configuring x64-osx-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:58 (message):
    Command failed: cscript configure.js cruntime=/MD debug=no prefix=/Users/augustblack/vcpkg/packages/libxslt_x64-osx include=/Users/augustblack/vcpkg/installed/x64-osx/include lib=/Users/augustblack/vcpkg/installed/x64-osx/lib bindir=$(PREFIX)\tools sodir=$(PREFIX)\bin
    Working Directory: /Users/augustblack/vcpkg/buildtrees/libxslt/src/v1.1.33-742f11ffe2/win32
    Error code: No such file or directory
    See logs for more information:

Call Stack (most recent call first):
  ports/libxslt/portfile.cmake:58 (vcpkg_execute_required_process)
  scripts/ports.cmake:73 (include)

Error: Building package libxslt:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libxslt:x64-osx
  Vcpkg version: 2019.06.21-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by dmn-star-home** [comment]
_configure.js_ is configure script for libxslt, specific for Windows with Scripting Host (_cscript.exe_). I don't think it can be run on macOS. May be the libxslt vcpkg port is windows only.

**Comment by Voskrese** [comment]
>  libxslt vcpkg port is windows only.

yes

https://github.com/microsoft/vcpkg/blob/master/ports/libxslt/portfile.cmake
`COMMAND ${NMAKE} /f Makefile.msvc rebuild OUTDIR=${OUTDIR}`

**Comment by dmn-star-home** [comment]
Okay, I get it. The error message like this "Not supported OS" would be nice.  May be someone can label this issue as the feature request for macOS/Linux support?

**Comment by PhoebeHui** [comment]
Related to https://github.com/microsoft/vcpkg/pull/8306

**Comment by dmn-star** [comment]
libxslt port works now on OS X too.  #8589 

Building package libxslt[core]:x64-osx... done
Installing package libxslt[core]:x64-osx...
Installing package libxslt[core]:x64-osx... done

Thanks.

**Comment by JackBoosY** [comment]
Hi @augustblack, thanks for reporting this issue.
Port libxslt now support UNIX, please update vcpkg and rebuild it.

Thanks.
