### ISSUE TITLE
Why not CoApp?

### ISSUE THREAD

**Issue by mloskot** [Microsoft/vcpkg#714]
The [FAQ](https://github.com/Microsoft/vcpkg/blob/master/docs/FAQ.md) provides very good answer to "Why not NuGet/Conan/Chocolatey?" questions.

Please, could anyone update the FAQ and answer Why not CoApp?

**Comment by OlafvdSpek** [comment]
CoApp is dead. Was it ever really alive?

**Comment by mloskot** [comment]
Perhaps. Yes, it was/is/kind of or wasn't...that's the point of my question.

CoApp kicked off under Microsoft's umbrella, moved forward pretty well and achieved state of fair usability.
Later, [CoApp collaborated with/contributed to NuGet](https://blogs.msdn.microsoft.com/vcblog/2013/04/26/nuget-for-c/) developing tools for native packages.

Currently, CoApp status is unclear:
* Microsoft has not announced anything about the project future, has it?
* CoApp maintainers [seems not laying down their arms](https://github.com/coapp/coapp.powershell/issues/126)

General public, especially CoApp contributors and supporters, deserve a word of explanation, which hopefully could be delivered via vcpkg FAQ.

**Comment by ras0219-msft** [comment]
CoApp unfortunately suffers from the limits of the platform it's built upon: NuGet. Each of our points about why NuGet isn't currently optimal for C++ applies to CoApp as well.

As for any inquiries about CoApp, I would point you to the CoApp project on GitHub. It seems like you did get a response from @virmitio in the issue you linked:
> We do apologize for out lack of attentiveness in recent history. Both Garrett and myself have been moved to other projects and have little to no time available for ongoing maintenance of CoApp.
If there are individuals interested in taking responsibility for said tasks, please reach out to me and we will try to make arrangements for such.
