### ISSUE TITLE
[New port request] [SpiderMonkey] mozjs

### ISSUE THREAD

**Issue by Voskrese** [microsoft/vcpkg#7147]
SpiderMonkey is Mozilla's JavaScript engine written in C and C++.
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Build_Documentation
https://github.com/mozilla/gecko-dev.git
http://ftp.mozilla.org/pub/spidermonkey/prereleases/

SpiderMonkey tarballs with GNOME patches
https://github.com/ptomato/mozjs
ftp://ftp.gnome.org/pub/gnome/teams/releng/tarballs-needing-help/mozjs/

windows deps
MOZILLABUILD \\ MOZTOOLS
https://ftp.mozilla.org/pub/mozilla/libraries/win32/

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
