### ISSUE TITLE
[New port request] gjs

### ISSUE THREAD

**Issue by Voskrese** [microsoft/vcpkg#7148]
Use the GNOME platform libraries in your JavaScript programs.
GJS powers GNOME Shell, Polari, GNOME Documents, and many other apps.

https://gitlab.gnome.org/GNOME/gjs
https://gitlab.gnome.org/GNOME/gjs/tree/master/win32

deps: https://github.com/microsoft/vcpkg/issues/7147

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
