### ISSUE TITLE
BUILD_FAILED

### ISSUE THREAD

**Issue by shimachao** [microsoft/vcpkg#7153]
PS D:\Documents\项目文档\vcpkg> .\vcpkg.exe install curl:x64-windows
The following packages will be built and installed:
    curl[core,ssl,winssl]:x64-windows
  * zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: zlib:x64-windows
Building package zlib[core]:x64-windows...
-- Using cached D:/Documents/项目文档/vcpkg/downloads/zlib1211.tar.gz
-- Using source at D:/Documents/项目文档/vcpkg/buildtrees/zlib/src/1.2.11-f690224aeb
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:58 (message):
    Command failed: ninja -v
    Working Directory: D:/Documents/项目文档/vcpkg/buildtrees/zlib/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\Documents\项目文档\vcpkg\buildtrees\zlib\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:282 (vcpkg_execute_required_process)
  ports/zlib/portfile.cmake:22 (vcpkg_configure_cmake)
  scripts/ports.cmake:73 (include)

Error: Building package zlib:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x64-windows
  Vcpkg version: 2019.06.26-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by myd7349** [comment]
Hi! Please attach this file: D:\Documents\项目文档\vcpkg\buildtrees\zlib\config-x64-windows-out.log

**Comment by VisionTekF** [comment]
[
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3749814/install-x64-windows-dbg-out.log)
](url)
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/3749815/config-x64-windows-out.log)
