### ISSUE TITLE
qt5-datavis3d and qt5-declarative build fail because of the download files whose versions are dismatch

### ISSUE THREAD

**Issue by tan-wei** [microsoft/vcpkg#7161]
After some tries (with or without proxy), I think the hash in `ports\qt5-datavis3d\portfile.cmake` should be updated.

Log is shown below:
```log
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:96 (message):


  File does not have expected hash:

          File path: [ C:/vcpkg/downloads/temp/qtdatavis3d-everywhere-src-5.12.1.tar.xz ]
      Expected hash: [ cb295deb9aa33132294d7d7f4daaa53dd9ab4815e2d3a2c916d88e1882e018a49d8d66db9088f69375d8da759a3f3566f251802aaba82d74cad2eb45d9bbbcff ]
        Actual hash: [ a0eff0f58515720d9c8e37bce16a3f6f719ca748c6228f183eb7e2fe2cc024195e5122cc29b9d0dba3319a9d6147105c0b253fb5e633e16db1fb20cca563d956 ]

  The file may have been corrupted in transit.  This can be caused by
  proxies.  If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
  environment variables to
  "https://user:password@your-proxy-ip-address:port/".



Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:179 (test_hash)
  installed/x86-windows/share/qt5modularscripts/qt_modular_library.cmake:15 (vcpkg_download_distfile)
  installed/x86-windows/share/qt5modularscripts/qt_modular_library.cmake:159 (qt_modular_fetch_library)
  ports/qt5-datavis3d/portfile.cmake:5 (qt_modular_library)
  scripts/ports.cmake:73 (include)


Error: Building package qt5-datavis3d:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qt5-datavis3d:x86-windows
  Vcpkg version: 2019.06.26-nohash

Additionally, attach any relevant sections from the log files above.
```

**Comment by tan-wei** [comment]
Wait, I find that `qtdatavis3d-everywhere-src-5.12.1.tar.xz` is downloaded instead of `qtdatavis3d-everywhere-src-5.12.3.tar.xz`. Maybe it is the problem. By the way, vcpkg is updated right now (f9fedc930).

**Comment by tan-wei** [comment]
The same with `qt5-declarative`:
```log
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:96 (message):


  File does not have expected hash:

          File path: [ C:/vcpkg/downloads/temp/qtdeclarative-everywhere-src-5.12.1.tar.xz ]
      Expected hash: [ 0caddcfee36cbf52bacd3a400d304511255715e2b5a58c1621ca8120610427c57511785457a9e7fa55975b86e7924a3cffddeb7e2e8e6622af85b7ebac35dd20 ]
        Actual hash: [ e06032da5c1c151200215f55728b9ce0fac299076f0ca3150143525a56bcce15eb72f6aa982b439e3920d1cd7a30468b3f0913f135d644ecda277d763fb5e1b5 ]

  The file may have been corrupted in transit.  This can be caused by
  proxies.  If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
  environment variables to
  "https://user:password@your-proxy-ip-address:port/".



Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:179 (test_hash)
  installed/x64-windows/share/qt5modularscripts/qt_modular_library.cmake:15 (vcpkg_download_distfile)
  installed/x64-windows/share/qt5modularscripts/qt_modular_library.cmake:159 (qt_modular_fetch_library)
  ports/qt5-declarative/portfile.cmake:5 (qt_modular_library)
  scripts/ports.cmake:73 (include)


Error: Building package qt5-declarative:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qt5-declarative:x64-windows
  Vcpkg version: 2019.06.26-nohash

Additionally, attach any relevant sections from the log files above.
```

**Comment by tan-wei** [comment]
Now for `Qt` in the latest `vcpkg`, `5.12.3` is the right version. So for other `qt` components, `5.12.3` files are downloaded and build successfully. But for these two components (maybe more than 2, I don't know), it will download `5.12.1`, so the dismatching for hash is expected.

**Comment by wangli28** [comment]
Hi @tan-wei, I can't reproduce this issue locally. I installed qt5-datavis3d and qt5-declarative successfully with VCPKG latest source. And VCPKG downloaded version 5.12.3 for qt5-datavis3d and qt5-declarative. This is my build log:

**.\vcpkg.exe install qt5-datavis3d**
......
Building package qt5-datavis3d[core]:x86-windows...
......
-- Downloading http://download.qt.io/official_releases/qt/5.12/5.12.3/submodules/qtdatavis3d-everywhere-src-5.12.3.tar.xz...
-- Extracting source F:/test/PR7051/vcpkg/downloads/qtdatavis3d-everywhere-src-5.12.3.tar.xz
-- Using source at F:/test/PR7051/vcpkg/buildtrees/qt5-datavis3d/src/5.12.3-2bc0d7cd80
......
Elapsed time for package qt5-datavis3d:x86-windows: 2.44 min
Total elapsed time: 45.57 min

 **.\vcpkg.exe install qt5-declarative**
The following packages will be built and installed:
    qt5-declarative[core]:x86-windows
Starting package 1/1: qt5-declarative:x86-windows
Building package qt5-declarative[core]:x86-windows...
......
-- Downloading http://download.qt.io/official_releases/qt/5.12/5.12.3/submodules/qtdeclarative-everywhere-src-5.12.3.tar.xz...
-- Extracting source F:/test/PR7051/vcpkg/downloads/qtdeclarative-everywhere-src-5.12.3.tar.xz
-- Using source at F:/test/PR7051/vcpkg/buildtrees/qt5-declarative/src/5.12.3-93b4ba5375
......
Elapsed time for package qt5-declarative:x86-windows: 22.2 min
Total elapsed time: 22.2 min

**Comment by tan-wei** [comment]
> 
> 
> Hi @tan-wei, I can't reproduce this issue locally. I installed qt5-datavis3d and qt5-declarative successfully with VCPKG latest source. And VCPKG downloaded version 5.12.3 for qt5-datavis3d and qt5-declarative. This is my build log:
> 
> **.\vcpkg.exe install qt5-datavis3d**
> ......
> Building package qt5-datavis3d[core]:x86-windows...
> ......
> -- Downloading http://download.qt.io/official_releases/qt/5.12/5.12.3/submodules/qtdatavis3d-everywhere-src-5.12.3.tar.xz...
> -- Extracting source F:/test/PR7051/vcpkg/downloads/qtdatavis3d-everywhere-src-5.12.3.tar.xz
> -- Using source at F:/test/PR7051/vcpkg/buildtrees/qt5-datavis3d/src/5.12.3-2bc0d7cd80
> ......
> Elapsed time for package qt5-datavis3d:x86-windows: 2.44 min
> Total elapsed time: 45.57 min
> 
> **.\vcpkg.exe install qt5-declarative**
> The following packages will be built and installed:
> qt5-declarative[core]:x86-windows
> Starting package 1/1: qt5-declarative:x86-windows
> Building package qt5-declarative[core]:x86-windows...
> ......
> -- Downloading http://download.qt.io/official_releases/qt/5.12/5.12.3/submodules/qtdeclarative-everywhere-src-5.12.3.tar.xz...
> -- Extracting source F:/test/PR7051/vcpkg/downloads/qtdeclarative-everywhere-src-5.12.3.tar.xz
> -- Using source at F:/test/PR7051/vcpkg/buildtrees/qt5-declarative/src/5.12.3-93b4ba5375
> ......
> Elapsed time for package qt5-declarative:x86-windows: 22.2 min
> Total elapsed time: 22.2 min

OK, the problem is wired, I review `${VCPKG_ROOT}\ports\qt5-modularscripts\qt_modular_library.cmake`, find that `5.12.3` is the version:
```cmake
set(MAJOR_MINOR 5.12)
set(FULL_VERSION ${MAJOR_MINOR}.3)
set(ARCHIVE_NAME "${NAME}-everywhere-src-${FULL_VERSION}.tar.xz")
```
I will try to clean some directories and then retry it.

**Comment by tan-wei** [comment]
OK, I think I find the problem.
# Background
Firstly, I would say `qt` is installed `5.12.1` before. Then I run `vcpkg upgrade --no-dry-run` to update all libraries. When `qt` is building, the error comes out.

# Problem
In the directory `${VCPKG_ROOT}\installed\x86-windows\share\qt5modularscripts`, the older ones are located here and the upgrade process do not remove them, so when I run `vcpkg install qt5-datavis3d`, it will still download `5.12.1`, not the latest `5.12.3`. But the hash test will check the new value, so it fails.

# Result
After I delete all files in `${VCPKG_ROOT}\installed\x86-windows\share` manually, it works!

# Question
Is there something wrong with `vcpkg upgrade` or `vcpkg remove`? Files in `${VCPKG_ROOT}\installed\{ARCH}-windows\share\qt5modularscripts` are not deleted. Thanks!

**Comment by tan-wei** [comment]
By the way. Some opnions about `vcpkg upgrade --no-dry-run`.

After some upgrades, I find the operation is **dangerous** for me. It will remove all the libraries which are going to update, then a long time build process. However, once something goes wrong, e.g downloading process fails, the whole process stops. It seems no way to recover. So I call it **dangerous**.

In this issue, it remains some kind of inconsistent status: some files are still in `installed` directory.
Then the story is on.

**Comment by TheScarfix** [comment]
the qt5 port currently uses the modularscripts port to determine the version which is downloaded for sub packages like declarative. If your qt5-modularscripts port is outdated this error happens.

**Comment by tan-wei** [comment]
> the qt5 port currently uses the modularscripts port to determine the version which is downloaded for sub packages like declarative. If your qt5-modularscripts port is outdated this error happens.

Yes, you are right. The strange thing is why `vcpkg upgrade --no-dry-run` does not remove it.

**Comment by tan-wei** [comment]
If someone meets this build error, maybe the issue can help he or she.
