### ISSUE TITLE
Request, OpenImageIO 2.0.8

### ISSUE THREAD

**Issue by Miaua** [microsoft/vcpkg#7163]
Hi
Could you please update OpenImageIO from 1.8.16 to 2.0.8?
I have not been able to build it on my own on Windows 10.

Also if possible, a tutorial video how to build it on Windows 10 would be awesome, 
because all the info of building OpenImageIO is outdated and the official project tutorial did not work on Windows 10. Also looks like it needs non free intel ICC compiler to build.

Looks like the jpeg lib is missing in vcpkg. There is open and turbo jpeg, but tiff can't build without jpeg and OpenImageIO can't build witn no tiff.

The tiff 4GB file size limit was removed with bigtiff version of the libtiff. If possible, the 64bit libtiff would be good addon to vcpkg.

**Comment by robertsimmons514** [comment]
> Hi
> Could you please update OpenImageIO from 1.8.16 to 2.0.8?
> I have not been able to build it on my own on Windows 10.
> 
> Also if possible, a tutorial video how to build it on Windows 10 would be awesome,
> because all the info of building OpenImageIO is outdated and the official project tutorial did not work on Windows 10. Also looks like it needs non free intel ICC compiler to build.
> 
> Looks like the jpeg lib is missing in vcpkg. There is open and turbo jpeg, but tiff can't build without jpeg and OpenImageIO can't build witn no tiff.
> 
> The tiff 4GB file size limit was removed with bigtiff version of the libtiff. If possible, the 64bit libtiff would be good addon to vcpkg.

**Comment by wangli28** [comment]
Hi everyone, latest version is 2.0.8, you can update vcpkg and rebuild.

**Comment by PhoebeHui** [comment]
@Miaua, you simply use './vcpkg install OpenImageIO'  to build OpenImageIO in vcpkg, and it will install the dependency as well.
