### ISSUE TITLE
OpenImageIO debug dll linked against release OpenExr

### ISSUE THREAD

**Issue by DaWelter** [microsoft/vcpkg#7164]
Hi,

first, thanks for making vcpkg. As to the issue here, the title tells it all.

Here is a screenshot with the debug DLL of OpenImageIO. It shows OIIO linked against IlmImf-2_3.dll. But the correct DLL would be IlmImf-2_3_d.dll, which is actually present in the debug/bin directory.
![openimageio_debug](https://user-images.githubusercontent.com/15868645/60686224-ca2a2f00-9ea7-11e9-9708-8f7ec702c1aa.PNG)

I digged through the config files for a bit and managed to fix my issue for now. In portfile.cmake of OpenImageIO I added DOPENEXR_CUSTOM_LIB_SUFFIX like so:
```
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -DOIIO_BUILD_TOOLS=OFF
        -DOIIO_BUILD_TESTS=OFF
        -DHIDE_SYMBOLS=ON
        -DUSE_DICOM=OFF
        -DUSE_FFMPEG=OFF
        -DUSE_FIELD3D=OFF
        -DUSE_FREETYPE=OFF
        -DUSE_GIF=OFF
        -DUSE_LIBRAW=${USE_LIBRAW}
        -DUSE_NUKE=OFF
        -DUSE_OCIO=OFF
        -DUSE_OPENCV=OFF
        -DUSE_OPENJPEG=OFF
        -DUSE_OPENSSL=OFF
        -DUSE_PTEX=OFF
        -DUSE_PYTHON=OFF
        -DUSE_QT=OFF
        -DUSE_WEBP=OFF
        -DBUILDSTATIC=${BUILDSTATIC}
        -DLINKSTATIC=${LINKSTATIC}
        -DBUILD_MISSING_PYBIND11=OFF
        -DBUILD_MISSING_DEPS=OFF
        -DCMAKE_DISABLE_FIND_PACKAGE_Git=ON
        -DVERBOSE=ON
    OPTIONS_DEBUG
        -DOPENEXR_CUSTOM_LIB_DIR=${CURRENT_INSTALLED_DIR}/debug/lib
        -DOPENEXR_CUSTOM_LIB_SUFFIX="_d"
)
```
Don't think it is the correct fix though because imo cmake should not find the release libs in the first place.

After some more digging I could see the FindOpenEXR.cmake script searching in the "non-debug" lib dirs, too. The search paths are collected in GENERIC_LIBRARY_PATHS. Its contents was
```
E:/Dev/vcpkg/installed/x64-windows/debug/lib;E:/Dev/vcpkg/installed/x64-windows/include/../lib;E:/Dev/vcpkg/installed/x64-windows/include/../lib;/usr/local/lib;/usr/local/lib/;/usr/lib;/usr/lib/;/sw/lib;/opt/local/lib;/OpenEXR/lib/static
```

**Comment by cenit** [comment]
It’s not a port bug while a cmake default behavior. 
#6393 was supposed to fix it for any port

**Comment by JackBoosY** [comment]
Hi @DaWelter, thanks for reporting this issue.
I've fixed this issue, please update vcpkg and rebuild openimageio.

Thanks.
