### ISSUE TITLE
[New port request] XML Security Library

### ISSUE THREAD

**Issue by dmn-star-home** [microsoft/vcpkg#7168]
XML Security Library

https://github.com/lsh123/xmlsec

XMLSec library provides C based implementation for major XML Security
standards:

* XML Signature Syntax and Processing
  https://www.w3.org/TR/xmldsig-core

* XML Encryption Syntax and Processing
  https://www.w3.org/TR/xmlenc-core/
XMLSec is based on well known LibXML (http://xmlsoft.org), LibXSLT
(http://xmlsoft.org/XSLT) and OpenSSL (https://www.openssl.org) libraries

**Comment by PhoebeHui** [comment]
The changes has merged to vcpkg.
