### ISSUE TITLE
Add libusb and libusb-win32

### ISSUE THREAD

**Issue by debrouxl** [Microsoft/vcpkg#717]
libusb is a portable library for accessing USB devices: http://libusb.info/ .

libusb-win32 is a Windows-specific port of an older version of libusb, with capabilities important to several other libraries or applications, such as filter driver mode: https://sourceforge.net/p/libusb-win32/wiki/Home/ .

The following use case for libusb-win32's filter driver mode is relevant to me: having both the manufacturer's driver for the manufacturer's stack, and an open-source libusb-win32-based driver for the open-source stack (which has some features the manufacturer's stack doesn't have) in a working state on a given computer. Users can then freely choose to use either stack, one at a time; after the initial setup, the user experience is pretty seamless.

**Comment by Mixaill** [comment]
@debrouxl Please check #1093 and #1107 ports
