### ISSUE TITLE
[New port request] [Netscape Portable Runtime] NSPR

### ISSUE THREAD

**Issue by Voskrese** [microsoft/vcpkg#7171]
Netscape Portable Runtime (NSPR) provides a platform-neutral API for system level and libc-like functions. The API is used in the Mozilla clients, many of Red Hat's and Oracle's server applications, and other software offerings.
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSPR
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSPR/NSPR_build_instructions

Windows deps: 
MOZILLABUILD \ MOZTOOLS
https://ftp.mozilla.org/pub/mozilla/libraries/win32/

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
