### ISSUE TITLE
[New port request] [Network Security Services] NSS

### ISSUE THREAD

**Issue by Voskrese** [microsoft/vcpkg#7172]
Network Security Services (NSS) is a set of libraries designed to support cross-platform development of security-enabled client and server applications. Applications built with NSS can support SSL v3, TLS, PKCS 5, PKCS 7, PKCS 11, PKCS 12, S/MIME, X.509 v3 certificates, and other security standards.
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Building

https://ftp.mozilla.org/pub/security/nss/releases/NSS_3_44_RTM/src/

**Comment by myd7349** [comment]
https://nss-crypto.org/

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
