### ISSUE TITLE
problems with hdf5 RelWithDebInfo configuration

### ISSUE THREAD

**Issue by SergeiDelov** [microsoft/vcpkg#7179]
Using VS2019/"Open folder" workflow.

Everything is fine with Release/Debug build.

With RelWithDebInfo I'm getting:

D:\tfs\Engine\libhdf5_cpp_D.lib(H5File.cpp.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in BinExporter.cpp.obj
D:\tfs\Engine\libhdf5_cpp_D.lib(H5File.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MD_DynamicRelease' in BinExporter.cpp.obj

vcpkg updated /packages rebuilt 2 days ago.

Looks like linker uses debug libraries as input.

**Comment by cenit** [comment]
It’s a bad cmake default behavior
#6393 was supposed to fix it for any port

**Comment by Neumann-A** [comment]
should be closed since #6393 has been merged

**Comment by Neumann-A** [comment]
@JackBoosY close?

**Comment by JackBoosY** [comment]
Fixed.
