### ISSUE TITLE
Problem with building fluidsynch for x64-windows mode

### ISSUE THREAD

**Issue by pvinhha** [microsoft/vcpkg#7180]
Below are the log messages:
The following packages will be built and installed:
    fluidsynth[core]:x64-windows
  * gettext[core]:x64-windows
  * glib[core]:x64-windows
  * libffi[core]:x64-windows
  * libiconv[core]:x64-windows
  * pcre[core]:x64-windows
  * zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/7: libffi:x64-windows
Building package libffi[core]:x64-windows...
-- Using cached C:/src/vcpkg/downloads/libffi-libffi-v3.1.tar.gz
-- Using source at C:/src/vcpkg/buildtrees/libffi/src/v3.1-206c189062
-- Applying patch C:/src/vcpkg/ports/libffi/export-global-data.patch
-- Applying patch failed. This is expected if this patch was previously applied.
CMake Error at scripts/cmake/vcpkg_configure_cmake.cmake:113 (message):
  Unable to determine appropriate generator for: -x64-v142
Call Stack (most recent call first):
  ports/libffi/portfile.cmake:22 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package libffi:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libffi:x64-windows
  Vcpkg version: 2018.11.23-nohash

Both vcpkg boot and update have been checked for updates.  Please advice for a solution.  Thanks.

**Comment by wangli28** [comment]
Hi @pvinhha, thanks for posting this issue! I can't reproduce it locally. I installed `fluidsynth:x64-windows` successfully with Visual Studio 2019 and vcpkg latest version. What is your cmake version?

**Comment by NancyLi1013** [comment]
`libffi `has been updated. We cannot reproduce this issue now. Please update vcpkg and try it again. 
Please feel free to reopen this or open a new issue if this is still a problem for you. 
Note: Please provide the steps to reproduce and attach your failure log if this issue still exists on your machine.
