### ISSUE TITLE
Glew does not compile on Ubuntu 18.04, WSL

### ISSUE THREAD

**Issue by odin-loki** [microsoft/vcpkg#7181]
Hello,

Everything is up to date and build trees and downloads have been deleted and the compile retried.
I try to install Glew and I get this:

odin@Odin:/mnt/c/Projects/vcpkg$ ./vcpkg install glew
The following packages will be built and installed:
    glew[core]:x64-linux
Starting package 1/1: glew:x64-linux
Building package glew[core]:x64-linux...
-- Using cached /mnt/c/Projects/vcpkg/downloads/glew-2.1.0.tgz
-- Using source at /mnt/c/Projects/vcpkg/buildtrees/glew/src/glew-58abdfb190
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:58 (message):
    Command failed: /mnt/c/Projects/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake /mnt/c/Projects/vcpkg/buildtrees/glew/src/glew-58abdfb190/build/cmake -DBUILD_UTILS=OFF -DCMAKE_MAKE_PROGRAM=/mnt/c/Projects/vcpkg/downloads/tools/ninja-1.8.2-linux/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/mnt/c/Projects/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/mnt/c/Projects/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/mnt/c/Projects/vcpkg/packages/glew_x64-linux/debug
    Working Directory: /mnt/c/Projects/vcpkg/buildtrees/glew/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /mnt/c/Projects/vcpkg/buildtrees/glew/config-x64-linux-dbg-out.log
      /mnt/c/Projects/vcpkg/buildtrees/glew/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:291 (vcpkg_execute_required_process)
  ports/glew/portfile.cmake:19 (vcpkg_configure_cmake)
  scripts/ports.cmake:73 (include)

Error: Building package glew:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glew:x64-linux
  Vcpkg version: 2019.06.26-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by odin-loki** [comment]
Here is the Log File from
      /mnt/c/Projects/vcpkg/buildtrees/glew/config-x64-linux-dbg-out.log
      /mnt/c/Projects/vcpkg/buildtrees/glew/config-x64-linux-dbg-err.log

-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring incomplete, errors occurred!
See also "/mnt/c/Projects/vcpkg/buildtrees/glew/x64-linux-dbg/CMakeFiles/CMakeOutput.log".


CMake Error at /mnt/c/Projects/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY
  OPENGL_INCLUDE_DIR)
Call Stack (most recent call first):
  /mnt/c/Projects/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /mnt/c/Projects/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/share/cmake-3.14/Modules/FindOpenGL.cmake:394 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /mnt/c/Projects/vcpkg/scripts/buildsystems/vcpkg.cmake:266 (_find_package)
  CMakeLists.txt:40 (find_package)

**Comment by odin-loki** [comment]
It stated it could not find OpenGL. So I installed it and it still did not work.

**Comment by odin-loki** [comment]
And I tried to reproduce it and it seems like its reproducable.

**Comment by wangli28** [comment]
I can't reproduce this issue locally, I installed it successfully with VCPKG latest source on Linux.

vwangli@vwangli003:~/Lily/vcpkg$ ./vcpkg install glew
The following packages will be built and installed:
    glew[core]:x64-linux
Starting package 1/1: glew:x64-linux
Building package glew[core]:x64-linux...
-- Using cached /home/vwangli/Lily/vcpkg/downloads/glew-2.1.0.tgz
-- Using source at /home/vwangli/Lily/vcpkg/buildtrees/glew/src/glew-58abdfb190
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Installing: /home/vwangli/Lily/vcpkg/packages/glew_x64-linux/share/glew/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package glew[core]:x64-linux... done
Installing package glew[core]:x64-linux...
Installing package glew[core]:x64-linux... done
Elapsed time for package glew:x64-linux: 8.094 s

Total elapsed time: 8.094 s

The package glew is compatible with built-in CMake targets:

    find_package(GLEW REQUIRED)
    target_link_libraries(main PRIVATE GLEW::GLEW)

**Comment by odin-loki** [comment]
I am using vcpkg with Ubuntu 18.04, Windows Linux Subsystem on Windows 10 Pro. I am not using Native Linux.

**Comment by PhoebeHui** [comment]
@odin-loki, I can't repro this issue on WSL with latest vcpkg source , does this still be an issue for you?

**Comment by PhoebeHui** [comment]
Please report a new issue and attach failure logs if this still be an problem for you.
