### ISSUE TITLE
cgicc does not compile on Ubuntu 18.04 WSL

### ISSUE THREAD

**Issue by odin-loki** [microsoft/vcpkg#7182]
Hello,

Everything is up to date, I have deleted the downloads and buildtress folder and tried to compile and it still did not compile.
I try to compile cgicc and it does not compile on Ubuntu 18.04 WSL.
I get this message:

odin@Odin:/mnt/c/Projects/vcpkg$ ./vcpkg install cgicc
The following packages will be built and installed:
    cgicc[core]:x64-linux
Starting package 1/1: cgicc:x64-linux
Building package cgicc[core]:x64-linux...
-- Downloading http://ftp.gnu.org/gnu/cgicc/cgicc-3.2.19.tar.gz...
-- Extracting source /mnt/c/Projects/vcpkg/downloads/cgicc-3.2.19.tar.gz
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: /mnt/c/Projects/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v
    Working Directory: /mnt/c/Projects/vcpkg/buildtrees/cgicc/x64-linux-dbg
    See logs for more information:
      /mnt/c/Projects/vcpkg/buildtrees/cgicc/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/cgicc/portfile.cmake:21 (vcpkg_install_cmake)
  scripts/ports.cmake:73 (include)

Error: Building package cgicc:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cgicc:x64-linux
  Vcpkg version: 2019.06.26-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by JackBoosY** [comment]
Hi @odin-loki, thanks for reporting this issue!
I've fixed it, please update vcpkg and rebuild cgicc.

Thanks.
