### ISSUE TITLE
Does Anyone else have integration issues?

### ISSUE THREAD

**Issue by odin-loki** [microsoft/vcpkg#7183]
Hello,

Does anyone have vcpkg integration issues? I can get vcpkg intellisense on Windows C++ Projects. But do not get any vcpkg intellisense on Linux and Cmake Projects. On Linux I can only get the WSL packages and not the VCPKG packages.

I tried refreshing remote intellisense headers and had no luck.

Any advice?

**Comment by LilyWangL** [comment]
@odin-loki, thanks for posting this issue. You can create cmake project and link the vcpkg's library on Linux. Could you provide a simple repro project?

**Comment by odin-loki** [comment]
Hello,

The issue here was a warning message in a Visusl Studio asking for a remote linux connection when using the Linux Subsystem. Visual Studio uses the Subsystem automatically OR the Linux Remote Connection.
________________________________

**Comment by PhoebeHui** [comment]
@odin-loki, does this still be a problem for you?

**Comment by odin-loki** [comment]
No.
________________________________

**Comment by PhoebeHui** [comment]
Thanks for your quick response!
