### ISSUE TITLE
Error: Building package armadillo:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by aminmlp** [microsoft/vcpkg#7184]
I want to install mlpack c++ with vcpkg but vcpkg cannot install armadillo.

E:\vcpkg-master\vcpkg-master\vcpkg-master>vcpkg install armadillo:x64-windows
The following packages will be built and installed:
    armadillo[core]:x64-windows
Starting package 1/1: armadillo:x64-windows
Building package armadillo[core]:x64-windows...
-- Note: armadillo only supports static library linkage. Building static library.
-- Downloading https://gitlab.com/conradsnicta/armadillo-code/-/archive/f00d3225b1c005775044369723f31cecc3cd6569/armadillo-code-f00d3225b1c005775044369723f31cecc3cd6569.tar.gz...
-- Downloading https://gitlab.com/conradsnicta/armadillo-code/-/archive/f00d3225b1c005775044369723f31cecc3cd6569/armadillo-code-f00d3225b1c005775044369723f31cecc3cd6569.tar.gz... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:172 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_gitlab.cmake:105 (vcpkg_download_distfile)
  ports/armadillo/portfile.cmake:5 (vcpkg_from_gitlab)
  scripts/ports.cmake:73 (include)

Error: Building package armadillo:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: armadillo:x64-windows
  Vcpkg version: 2019.06.26-nohash

Additionally, attach any relevant sections from the log files above.

please help me

**Comment by wangli28** [comment]
Hi @aminmlp 

We're unable to reproduce this issue locally.

But maybe this workaround will work for you.

1. Download the source code with a web browser from: 
https://gitlab.com/conradsnicta/armadillo-code/-/archive/f00d3225b1c005775044369723f31cecc3cd6569/armadillo-code-f00d3225b1c005775044369723f31cecc3cd6569.tar.gz

2. Save it inside <path_to_vcpkg>/downloads/.

3. Run ./vcpkg install cpprestsdk again

**Comment by aminmlp** [comment]
it does not work for me

**Comment by aminmlp** [comment]
I downloaded that file and copied to vcpkg download folder but when I run "vcpkg install armadillo:x64-windows" again, I have same error.
I have search a lot, the file (https://gitlab.com/conradsnicta/armadillo-code/-/archive/f00d3225b1c005775044369723f31cecc3cd6569/armadillo-code-f00d3225b1c005775044369723f31cecc3cd6569.tar.gz) is in google cloud and google cloud has been filtered for my country. 
it is possible with anti-filter such as psiphon 3.
but vcpkg has to be set with psiphon 3.
is there anyone to how set vcpkg with psiphon 3?

**Comment by wangli28** [comment]
If you downloaded the source code successfully and copied it to _<path_to_vcpkg>/downloads/_, vcpkg will find the source code and unzip it. Like this:

PS E:\Lily\vcpkg> .\vcpkg.exe install armadillo:x64-windows
The following packages will be built and installed:
    armadillo[core]:x64-windows
Starting package 1/1: armadillo:x64-windows
Building package armadillo[core]:x64-windows...
-- Note: armadillo only supports static library linkage. Building static library.
**-- Using cached E:/Lily/vcpkg/downloads/conradsnicta-armadillo-code-f00d3225b1c005775044369723f31cecc3cd6569.tar.gz
-- Extracting source E:/Lily/vcpkg/downloads/conradsnicta-armadillo-code-f00d3225b1c005775044369723f31cecc3cd6569.tar.gz**
-- Applying patch remove_custom_modules.patch
-- Using source at E:/Lily/vcpkg/buildtrees/armadillo/src/ecc3cd6569-c7b5ad093a
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
......

**Comment by aminmlp** [comment]
it does not work my friend. I do not know why?
[image: image.png]
E:\vcpkg-master\vcpkg-master\vcpkg-master>.\vcpkg.exe install
armadillo:x64-windows
The following packages will be built and installed:
    armadillo[core]:x64-windows
Starting package 1/1: armadillo:x64-windows
Building package armadillo[core]:x64-windows...
-- Note: armadillo only supports static library linkage. Building static
library.
-- Downloading
https://gitlab.com/conradsnicta/armadillo-code/-/archive/f00d3225b1c005775044369723f31cecc3cd6569/armadillo-code-f00d3225b1c005775044369723f31cecc3cd6569.tar.gz.
..
-- Downloading
https://gitlab.com/conradsnicta/armadillo-code/-/archive/f00d3225b1c005775044369723f31cecc3cd6569/armadillo-code-f00d3225b1c005775044369723f31cecc3cd6569.tar.gz...
Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:172 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at
https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_gitlab.cmake:105 (vcpkg_download_distfile)
  ports/armadillo/portfile.cmake:5 (vcpkg_from_gitlab)
  scripts/ports.cmake:73 (include)


Error: Building package armadillo:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: armadillo:x64-windows
  Vcpkg version: 2019.06.26-nohash

Additionally, attach any relevant sections from the log files above.

again I have a same problem.

**Comment by aminmlp** [comment]
> If you downloaded the source code successfully and copied it to _<path_to_vcpkg>/downloads/_, vcpkg will find the source code and unzip it. Like this:
> 
> PS E:\Lily\vcpkg> .\vcpkg.exe install armadillo:x64-windows
> The following packages will be built and installed:
> armadillo[core]:x64-windows
> Starting package 1/1: armadillo:x64-windows
> Building package armadillo[core]:x64-windows...
> -- Note: armadillo only supports static library linkage. Building static library.
> **-- Using cached E:/Lily/vcpkg/downloads/conradsnicta-armadillo-code-f00d3225b1c005775044369723f31cecc3cd6569.tar.gz -- Extracting source E:/Lily/vcpkg/downloads/conradsnicta-armadillo-code-f00d3225b1c005775044369723f31cecc3cd6569.tar.gz**
> -- Applying patch remove_custom_modules.patch
> -- Using source at E:/Lily/vcpkg/buildtrees/armadillo/src/ecc3cd6569-c7b5ad093a
> -- Configuring x64-windows
> -- Building x64-windows-dbg
> -- Building x64-windows-rel
> ......

why it does not work for me ?
I downloaded it and copy that to <path_to_vcpkg>/downloads/
why ?

**Comment by wangli28** [comment]
Hi @aminmlp, I found the reason. The source code which downloaded using a web browser is different, its name missing "conradsnicta-". You can rename it to **conradsnicta-armadillo-code-f00d3225b1c005775044369723f31cecc3cd6569.tar.gz**, and install the port again.

**Comment by aminmlp** [comment]
thanks a lot my buddy. finally it is worked

**Comment by shuitianxu** [comment]
The issue has been solved.
