### ISSUE TITLE
Error installing glfw3:x64-linux

### ISSUE THREAD

**Issue by akshit-sharma** [microsoft/vcpkg#7187]
already installed: xinerama, xcursor (sudo apt install libxinerama-dev libxcursor-dev)
steps performed: vcpkg install glfw3

vcpkg output is contained in two files ([vcpkg_output.txt](https://github.com/microsoft/vcpkg/files/3365204/vcpkg_output.txt) and [vcpkg_error.txt](https://github.com/microsoft/vcpkg/files/3365202/vcpkg_error.txt)).

CMake error are divided into two files ([config-x64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/3365206/config-x64-linux-dbg-err.log) and [config-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/3365207/config-x64-linux-dbg-out.log)).

**Comment by e-zl** [comment]
I got the same error.

**Comment by JackBoosY** [comment]
@akshit-sharma  @e-zl Thanks for reporting this issue!
Please install xorg-dev and libglu1-mesa-dev to try to fix this issue.

Thanks.

**Comment by akshit-sharma** [comment]
Thanks, it is working now. It would be helpful to have this information in the installation also.
The vcpkg say about xinerama and xcursor but not about xorg-dev and libglu1-mesa-dev.
```
GLFW3 currently requires the following libraries from the system package manager:
    xinerama
    xcursor
```

**Comment by JackBoosY** [comment]
@akshit-sharma Thanks for test.
I've added these message to linux/osx build.
