### ISSUE TITLE
powershell prompts do not display when using alternate console hosts

### ISSUE THREAD

**Issue by alexhultman** [Microsoft/vcpkg#719]
```
powershell -exec bypass scripts\bootstrap.ps1
scriptsbootstrap.ps1 : The term 'scriptsbootstrap.ps1' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:1
+ scriptsbootstrap.ps1
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (scriptsbootstrap.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Windows 10 x64
Visual Studio 2015 Update 3 (Community Edition)
Git 2.7.1

**Comment by alexhultman** [comment]
Oh wtf, I swapped \ with / and now it works. I am officially a retard. Update README?

**Comment by alexhultman** [comment]
FYI: This is because I run the "Git Bash" terminal rather than Cmd.exe. I also found that if you try and install anything in the git bash terminal it just blocks forever. It only works in cmd.exe. Maybe it could be possible to support the git bash terminal?

I think many devs have very bad feelings for the windows cmd.exe and especially how its auto complete is not really helping (you type 4 letters, hit tab, now you have something that doesn't even match your 4 initial letters).

**Comment by cloudhan** [comment]
try
```
powershell -exec bypass scripts/bootstrap.ps1
```
notice the forward slash...

**Comment by ras0219-msft** [comment]
When trying out git bash locally, everything seems to work fine (note that I've added vcpkg to my path)
```
$ vcpkg remove curl
The following packages will be removed:
    curl:x86-windows
Removing package curl:x86-windows...
Removing package curl:x86-windows... done

$ vcpkg install curl
Package curl:x86-windows is installed
```
What commands were you running and where did it hang?

In general, you will need to swap out backslashes for forward slashes in our help documentation (as @cloudhan observed). Unfortunately, there's no way we can make all three of {cmd, powershell, bash} happy here. Since bash users are more likely to be advanced users, we'd prefer to cater towards cmd/powershell in our help documentation.

We _might_ be able to detect our parent process and adjust help text coming out of vcpkg appropriately (substituting slashes), but this wouldn't help at all for our core static documentation.

**Comment by alexhultman** [comment]
I actually wrote that I changed \ with / and got the installation working but then removed this message. The main point is that I cannot get it to work after installing it. For me it only works in cmd.exe, not the git bash - it just hangs forever. In cmd.exe it worked very well though, clearly a massive step forward for open source C++ on Windows.

**Comment by ras0219-msft** [comment]
Could you include a console transcript of what you're trying to do and how it doesn't work? I'd love to fix it if possible, but I need to reproduce the issue first.

**Comment by alexhultman** [comment]
Yes will give more info in a while

**Comment by alexhultman** [comment]
I cannot reproduce this anymore..

**Comment by alexhultman** [comment]
I know how to reproduce now. The issue is when you clone vcpkg and do the install process. Everything works in the "git bash terminal" until you try and install a package. Then (in the cmd.exe / developer prompt) it will ask "Download cmake" and give you [y]Yes [n] No [A] Always. This question does not show up in the git bash terminal, only in cmd.exe and developer promt. This makes it seem vcpkg just hangs since it waits for input without showing it.

**Comment by alexhultman** [comment]
BITS transfer I think this is called, this step that fails

**Comment by donno** [comment]
Try using winpty, like so:
`winpty powershell -exec bypass scripts/bootstrap.ps1`

That program normally helps with running Window Console applications under  Cygwin/MinGW.
For example, if you have official Windows distribution of Python 2.7 installed, you will experience similar pain to powershell that you mention, where running the interactive prompt does not write anything to the "Git Bash" window. 

(I believe Git Bash comes with this tool out of box).

**Comment by mcgoo** [comment]
I think this has recently started causing my builds on AppVeyor to fail. A workaround is to `echo yes > %VCPKG_ROOT%\Downloads\AlwaysAllowDownloads` to agree to the downloads in advance and skip the prompt. Maybe a command line option to disable interactive prompts, like `vcpkg install --yes <pkgname>` would be useful?

**Comment by alexkaratarakis** [comment]
@alexhultman @mcgoo 
f4d11d7c9ea98007af88684db12de351b83bd976 removes download prompts.
There were many issues around these prompts plus one of the goals of `vcpkg` is to be as script-friendly as possible (e.g. for CI builds) so we decided to remove them.

**Comment by JackBoosY** [comment]
Hi @alexhultman , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
