### ISSUE TITLE
SPRIV-Tools missing cmake targets

### ISSUE THREAD

**Issue by cwfitzgerald** [microsoft/vcpkg#7190]
Commit 66f1d9a747ed5f048ed23248b9163d7490da02c2 seems to have removed the cmake-target patch from spriv-tools, meaning it cannot be found through cmake's find_package functions.

**Comment by DethRaid** [comment]
This issue blocks me as well. Please add back the cmake-target patch

**Comment by Voskrese** [comment]
https://github.com/microsoft/vcpkg/blob/master/ports/spirv-tools/portfile.cmake

```
    PATCHES
        comment-distutils.patch
```
local port to
```

#    PATCHES
#        comment-distutils.patch
```

**Comment by wangli28** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
