### ISSUE TITLE
[glbinding] x64-windows-static builds error on link

### ISSUE THREAD

**Issue by sstsai** [microsoft/vcpkg#7191]
error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease'

**Comment by Voskrese** [comment]
glbinding builds
error LNK2038 in libraries ?

predict here will not work, attach all the log files and describe in more detail

**Comment by sstsai** [comment]
libraries build fine in vcpkg.  trying to link to the static libraries results in error mentioned above.
[test1.zip](https://github.com/microsoft/vcpkg/files/3367014/test1.zip)

**Comment by NancyLi1013** [comment]
Hi @sstsai  thanks for posting this issue. 
I noticed this info from `build.txt` file in your above attachment:

> C:\portable\Documents\workspace\MSVCRTD.lib(exe_main.obj) : error LNK2019: unresolved external symbol main referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)
> C:\portable\Documents\workspace\test1.exe : fatal error LNK1120: 1 unresolved externals
>   ninja: build stopped: subcommand failed.

I didn't see any failures about `LNK2038` you described. Please provide the related log or files as for `LNK2038` error.
