### ISSUE TITLE
Question: could we skip check_for_files_in_include function when trigger postbuildlint

### ISSUE THREAD

**Issue by lennonwoo** [microsoft/vcpkg#7197]
I am working on using `vcpkg` to build the ROS packages, the thing is that the ROS packages have some pure cmake packages like [ament_cmake_ros](https://github.com/ros2/ament_cmake_ros/tree/master/ament_cmake_ros), this package won't contain `include` directory after the build.

I am not sure detail responsibility of the [check_for_files_in_include function](https://github.com/microsoft/vcpkg/blob/master/toolsrc/src/vcpkg/postbuildlint.cpp#L80) in postbuildlint, could we skip this check?

**Comment by traversaro** [comment]
You can use the `VCPKG_POLICY_EMPTY_INCLUDE_FOLDER` policy, see https://github.com/microsoft/vcpkg/blob/master/ports/ecm/portfile.cmake#L30 for a usage example.

**Comment by lennonwoo** [comment]
Thanks, I found `VCPKG_POLICY_EMPTY_PACKAGE` also could useful if we want to use vcpkg to deal with pure cmake package.
