### ISSUE TITLE
mpir fails to build with VS2017 on Windows 10

### ISSUE THREAD

**Issue by stoperro** [Microsoft/vcpkg#720]
In log it complains that:

`error MSB8036: The Windows SDK version 7 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [F:\vcpkg\buildtrees\mpir\src\mpir-2.7.2\build.vc14\dll_mpir_gc\dll_mpir_gc.vcxproj]`

If I open the solution in VS and retarget it to whatever toolset and Windows SDK platform I have, then installation works.

**Comment by Mixaill** [comment]
Try to use **mpir** port from #770

**Comment by stoperro** [comment]
Now I get:
`CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: msbuild;F:/vcpkg2/buildtrees/mpir/src/mpir-3.0.0/build.vc15/dll_mpir_gc/dll_mpir_gc.vcxproj;/p:Configuration=Release;/p:Platform=x64;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No;/m`

In build-x64-windows-rel-out.log:
```1>Project "F:\vcpkg2\buildtrees\mpir\src\mpir-3.0.0\build.vc15\dll_mpir_gc\dll_mpir_gc.vcxproj" on node 1 (default targets).
     1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Platforms\x64\PlatformToolsets\v141\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [F:\vcpkg2\buildtrees\mpir\src\mpir-3.0.0\build.vc15\dll_mpir_gc\dll_mpir_gc.vcxproj]
     1>Done Building Project "F:\vcpkg2\buildtrees\mpir\src\mpir-3.0.0\build.vc15\dll_mpir_gc\dll_mpir_gc.vcxproj" (default targets) -- FAILED.

Build FAILED.```

So newer SDK is now used, but still not the one I have.

**Comment by Mixaill** [comment]
Oops, try #775
