### ISSUE TITLE
add VCPKG_PROXY

### ISSUE THREAD

**Issue by looooj** [microsoft/vcpkg#7200]
#vcpkg\toolsrc\src\vcpkg\base\downloads.cpp
#  static void winhttp_download_file
   
        //...     
        HINTERNET hSession = 0;
        auto vcpkg_proxy = System::get_environment_variable("VCPKG_PROXY");
        if ( vcpkg_proxy.has_value() ) {

            StringView tmp(*vcpkg_proxy.get());
            auto proxy = Strings::to_utf16(tmp);
            hSession =  WinHttpOpen(L"vcpkg/1.0",
                                    WINHTTP_ACCESS_TYPE_NAMED_PROXY,
                                    proxy.c_str(),
                                    WINHTTP_NO_PROXY_BYPASS,
                                    0);
            Checks::check_exit(VCPKG_LINE_INFO, hSession, "WinHttpOpen() failed: %d", 
            GetLastError());
        } 
        else
        {
        //... original code 
        }

**Comment by wangli28** [comment]
Hi @looooj, thanks for posting this issue. Can you provide more information for this issue?

**Comment by looooj** [comment]
//  example
        //  set VCPKG_PROXY=127.0.0.1:1080,  winhttp_download_file will use proxy download
        //  test on window10 ok
        
        //  vcpkg\toolsrc\src\vcpkg\base\downloads.cpp 
        //  static void winhttp_download_file
        //  orginal code use "ie proxy or system proxy", now use env "VCPKG_PROXY"

        //... orginal code
        HINTERNET hSession = 0;
        auto vcpkg_proxy = System::get_environment_variable("VCPKG_PROXY");
        if ( vcpkg_proxy.get() && vcpkg_proxy.get()->length() > 1 ) {

            StringView tmp(*vcpkg_proxy.get());
            auto proxy = Strings::to_utf16(tmp);
            hSession =  WinHttpOpen(L"vcpkg/1.0",
                                    WINHTTP_ACCESS_TYPE_NAMED_PROXY,
                                    proxy.c_str(),
                                    WINHTTP_NO_PROXY_BYPASS,
                                    0);
            Checks::check_exit(VCPKG_LINE_INFO, hSession, "WinHttpOpen() failed: %d", GetLastError());
        }
        else {
        
            hSession =  WinHttpOpen(L"vcpkg/1.0",
                                        IsWindows8Point1OrGreater() ? WINHTTP_ACCESS_TYPE_AUTOMATIC_PROXY
                                                                    : WINHTTP_ACCESS_TYPE_DEFAULT_PROXY,
                                        WINHTTP_NO_PROXY_NAME,
                                        WINHTTP_NO_PROXY_BYPASS,
                                        0);
            Checks::check_exit(VCPKG_LINE_INFO, hSession, "WinHttpOpen() failed: %d", GetLastError());

            // Win7 IE Proxy fallback
            if (IsWindows7OrGreater() && !IsWindows8Point1OrGreater())
            {
                // First check if any proxy has been found automatically
                WINHTTP_PROXY_INFO proxyInfo;
                DWORD proxyInfoSize = sizeof(WINHTTP_PROXY_INFO);
                auto noProxyFound = !WinHttpQueryOption(hSession, WINHTTP_OPTION_PROXY, &proxyInfo, &proxyInfoSize) ||
                                    proxyInfo.dwAccessType == WINHTTP_ACCESS_TYPE_NO_PROXY;

                // If no proxy was found automatically, use IE's proxy settings, if any
                if (noProxyFound)
                {
                    WINHTTP_CURRENT_USER_IE_PROXY_CONFIG ieProxy;
                    if (WinHttpGetIEProxyConfigForCurrentUser(&ieProxy) && ieProxy.lpszProxy != nullptr)
                    {
                        WINHTTP_PROXY_INFO proxy;
                        proxy.dwAccessType = WINHTTP_ACCESS_TYPE_NAMED_PROXY;
                        proxy.lpszProxy = ieProxy.lpszProxy;
                        proxy.lpszProxyBypass = ieProxy.lpszProxyBypass;
                        WinHttpSetOption(hSession, WINHTTP_OPTION_PROXY, &proxy, sizeof(proxy));
                    }
                }
            }
        }
        // ...orginal code

**Comment by donny-dont** [comment]
@LilyWangL I'm also hitting the issue where `vcpkg.exe` does not use the `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` values when its attempting to download the tools it needs listed in the  `vcpkgTools.xml` file.

I'm guessing it would be better to just use the standard values instead of a new `VCPKG_PROXY` but I'd be open to implementing either.

**Comment by PhoebeHui** [comment]
This should not be a problem now, please get latest source and try again.
