### ISSUE TITLE
Bundling cmake and ninja

### ISSUE THREAD

**Issue by MoAlyousef** [microsoft/vcpkg#7210]
Hello
I'm not sure if this had been asked before, but why is vcpkg bundling cmake and ninja with each bootstrap?
It could check for system-wide installs of these executables.
It kinda becomes annoying when you want multiple instances of vcpkg for versioning.

**Comment by MikeGitb** [comment]
I guess it is because it is simple and vcpkg always tries to use the latest version of those tools which is rarely what is installed in a computer. 

Does this cause any problems for you? What exactly makes this annoying?

**Comment by MoAlyousef** [comment]
> I guess it is because it is simple and vcpkg always tries to use the latest version of those tools which is rarely what is installed in a computer.
> 
> Does this cause any problems for you? What exactly makes this annoying?

I have several instances of vcpkg for different library versions. I usually delete unnecessary folders, however if I have to add a library vcpkg would still have to download cmake(again) even though I do have the most recent cmake in my system (3.16).

**Comment by NancyLi1013** [comment]
Hi @MoAlyousef 

Sorry for the late reply.

Could  you please help confirm where `cmake` is installed in your local?

I tried to install different `cmake `versions in differnet directories and the results are different.
In older to make sure that there is no need to download `cmake `again, you can install it to `C:/` directory. If the version is more that `3.14` (It is the version that vcpkg provides currently), it won't be downloaded again.

**Comment by MoAlyousef** [comment]
> Hi @MoAlyousef
> 
> Sorry for the late reply.
> 
> Could you please help confirm where `cmake` is installed in your local?
> 
> I tried to install different `cmake `versions in differnet directories and the results are different.
> In older to make sure that there is no need to download `cmake `again, you can install it to `C:/` directory. If the version is more that `3.14` (It is the version that vcpkg provides currently), it won't be downloaded again.
> As for `ninja `, you can use the same way to check it agian.

Thank you for your reply. I’m currently not in front of my windows machine, but CMake isn’t in C:\. However its path is in the environment PATH. I’m facing this issue also on Linux and Mac OS, I have cmake installed in a system PATH. 
The other issue is that if I use my system cmake to install a library, it adds the config file to /usr/share, while the vcpkg downloaded cmake doesn’t seem to be able to access it, and vice versa.

**Comment by NancyLi1013** [comment]
@MoAlyousef 
Is this issue not a problem for you now?

**Comment by MoAlyousef** [comment]
It's non-optimal, but it's not a bug, also it seems I was the only person annoyed by it, so I closed it.

**Comment by NancyLi1013** [comment]
Thanks for your update.  Currently, CMake has been updated to 3.17.2 in vcpkg.  So this issue should not be existed on Windows platform. As for Linux, I didn't install CMake on my local. I'm not sure what the specific condition is. Sorry, I cannot help you some in this point.
