### ISSUE TITLE
Cmake: library considered bud not accepted

### ISSUE THREAD

**Issue by michalpolic** [microsoft/vcpkg#7214]
Hello, I have instaled libraries (using VCPKG): 
- openblas, 
- clapack, 
- suitesparse

and tried to add them into project in CMakeLists.txt:
find_package(OpenBLAS REQUIRED) ...
find_package(CLAPACK REQUIRED) ...
find_package(SuiteSparse REQUIRED) ...

and get in all the examples above the error, e.g.:
```
Could not find a configuration file for package "OpenBLAS" that is
  compatible with requested version "".

  The following configuration files were considered but not accepted:
    D:/School/Research/Reconstruction3D/Software/vcpkg/installed/x64-windows/share/openblas/OpenBLASConfig.cmake, version: 0.3.6 (64bit)
```

I have tried reinstall all the libraries using 2 computers, several commits of VCPKG, the VisualStudio 2015, 2017 and CMake: 3.12.4, 3.14.0, 3.15.0-rc3 but the error remains the same. If I specify the version, so that required versions match found version, the error remains the same:
```
Could not find a configuration file for package "OpenBLAS" that is
  compatible with requested version "0.3.6".

  The following configuration files were considered but not accepted:
    D:/School/Research/Reconstruction3D/Software/vcpkg/installed/x64-windows/share/openblas/OpenBLASConfig.cmake, version: 0.3.6 (64bit)
```

Please, do you have any idea what may be wrong? 
Thank you in advance.

**Comment by cenit** [comment]
`version: 0.3.6 (64bit)` gives you an hint.

You are trying to build a x86 (32bit) program saying that you want to link it to a 64bit library. Then the mess.
Just check the script that you are using to trigger the build, there lies the problem :)

**Comment by michalpolic** [comment]
Thank you, I missed that setting.

**Comment by Jerry-2005** [comment]
@michalpolic 
Hi Michal,
I also have same issue, could you please kindly share your settings?
Thanks very much.
