### ISSUE TITLE
Sources and tools should be downloaded as a one separate step before actual build

### ISSUE THREAD

**Issue by invy** [microsoft/vcpkg#7219]
Currently when building multiple packages, sources are downloaded bofore building each package separately. When building many packages, sometimes build fails because some package or tool cannot be donwloaded which causes build to failure.
Better solution would be to download all required packages and tools in one go before even considering building them.

**Comment by degski** [comment]
@invy Don't know why this isn't the default, but if you pass:

    vcpkg upgrade --no-dry-run --keep-going

one failed download will not stop the whole batch [and you having to figure which out of all those packages got removed], but keeps on building the ones that do succeed. So, this has the effect you talk about, apart from that the package is now removed [which is not great], as opposed to keeping the old installed version.

I agree with you that this whole thing is not very well designed.

**Comment by invy** [comment]
@degski This would not solve my problem as I'm doing clean build on CI for a bunch of packages. And the network problems do occur a bit too often.

**Comment by strega-nil** [comment]
Closed as complete -- `--download-only` is now a thing.
