### ISSUE TITLE
[New Port request] add urdl

### ISSUE THREAD

**Issue by akainq** [microsoft/vcpkg#7224]
Urdl is a cross-platform C++ library for downloading web content using a URL. It provides an easy-to-use extension to standard C++ iostreams and an asynchronous interface for use with Boost.Asio.
https://github.com/chriskohlhoff/urdl

**Comment by NancyLi1013** [comment]
Hi @akainq, thanks for posting this issue. I try to add this port and find that it doesn't currently support boost 1.70 . So we cannot add it now.

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
