### ISSUE TITLE
[x264:x64-linux-dyn] Not building on non-windows platform because of vcpkg_acquire_msys()

### ISSUE THREAD

**Issue by aspioupiou** [microsoft/vcpkg#7225]
Trying to build x264 on linux / macOs platform crashes. 
Error : 
CMake Error at scripts/cmake/vcpkg_acquire_msys.cmake:43 (message):
  vcpkg_acquire_msys() can only be used on Windows hosts
Call Stack (most recent call first):
  ports/x264/portfile.cmake:16 (vcpkg_acquire_msys)
  scripts/ports.cmake:71 (include)

Error: Building package x264:x64-linux-dyn failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: x264:x64-linux-dyn

**Comment by feliwir** [comment]
I can't build `ffmpeg[*]` on Linux either

**Comment by aspioupiou** [comment]
Has anyone made any work on this ?

**Comment by PhoebeHui** [comment]
Currently, x264 built successfully on linux, please get latest source and try again.

./vcpkg install x264
Computing installation plan...
The following packages will be built and installed:
    x264[core]:x64-linux
Detecting compiler hash for triplet x64-linux...
Starting package 1/1: x264:x64-linux
Building package x264[core]:x64-linux...
-- Downloading https://github.com/mirror/x264/archive/303c484ec828ed0d8bfe743500e70314d026c3bd.tar.gz...
-- Extracting source /home/phoebe/vcpkg/downloads/mirror-x264-303c484ec828ed0d8bfe743500e70314d026c3bd.tar.gz
-- Applying patch uwp-cflags.patch
-- Using source at /home/phoebe/vcpkg/buildtrees/x264/src/14d026c3bd-bca2ebf740.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Installing x64-linux-dbg
-- Installing x64-linux-rel
-- Fixing pkgconfig
-- Fixing pkgconfig - release
-- Checking file: /home/phoebe/vcpkg/packages/x264_x64-linux/lib/pkgconfig/x264.pc
-- Fixing pkgconfig - debug
-- Checking file: /home/phoebe/vcpkg/packages/x264_x64-linux/debug/lib/pkgconfig/x264.pc
-- Fixing pkgconfig --- finished
-- Installing: /home/phoebe/vcpkg/packages/x264_x64-linux/share/x264/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package x264[core]:x64-linux... done
Installing package x264[core]:x64-linux...
Installing package x264[core]:x64-linux... done
Elapsed time for package x264:x64-linux: 57.27 s

Total elapsed time: 58.09 s
