### ISSUE TITLE
Error build libdisasm:x86-windows-static

### ISSUE THREAD

**Issue by yezilaoda** [microsoft/vcpkg#7246]
D:\vcpkg>vcpkg.exe install libdisasm:x86-windows-static
The following packages will be built and installed:
    libdisasm[core]:x86-windows-static
Starting package 1/1: libdisasm:x86-windows-static
Building package libdisasm[core]:x86-windows-static...
-- Using cached D:/vcpkg/downloads/libdisasm-0.23.tar.gz
-- Applying patch D:/vcpkg/ports/libdisasm/sizeofvoid.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Configuring x86-windows-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:58 (message):
    Command failed: ninja -v
    Working Directory: D:/vcpkg/buildtrees/libdisasm/x86-windows-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\libdisasm\config-x86-windows-static-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:290 (vcpkg_execute_required_process)
  ports/libdisasm/portfile.cmake:23 (vcpkg_configure_cmake)
  scripts/ports.cmake:73 (include)

Error: Building package libdisasm:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libdisasm:x86-windows-static
  Vcpkg version: 2019.06.26-nohash

**Comment by wangli28** [comment]
Hi @yezilaoda, thanks for posting this issue. I can't reproduce this issue locally, can you provide the error log?
```
See logs for more information:
D:\vcpkg\buildtrees\libdisasm\config-x86-windows-static-err.log
```
