### ISSUE TITLE
vcpkg hangs when install hdf5:x64-windows

### ISSUE THREAD

**Issue by dave1717** [microsoft/vcpkg#7251]
On my PC runs Microsoft Windows 10 Pro, Version 1809. I tried to install a hdf5-library for a C++ VS-project with vcpkg:
vcpkg install hdf5:x64-windows

However the installation process seems to hang at 'Builiding x64-windows-rel' (no CPU-load and no apparent progress for more than 15min). Do you have any idea what the problem might be? 
Here the cmd-output:
//------------------------------------------------------------------------
The following packages will be built and installed:
    hdf5[core]:x64-windows
  * szip[core]:x64-windows
  * zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: zlib:x64-windows
Building package zlib[core]:x64-windows...
-- Using cached C:/vcpkg-master/vcpkg-master/downloads/zlib1211.tar.gz
-- Using source at C:/vcpkg-master/vcpkg-master/buildtrees/zlib/src/1.2.11-f690224aeb
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: C:/vcpkg-master/vcpkg-master/packages/zlib_x64-windows/share/zlib/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package zlib[core]:x64-windows... done
Installing package zlib[core]:x64-windows...
Installing package zlib[core]:x64-windows... done
Elapsed time for package zlib:x64-windows: 7.096 s
Starting package 2/3: szip:x64-windows
Building package szip[core]:x64-windows...
-- Using cached C:/vcpkg-master/vcpkg-master/downloads/szip-2.1.1.tar.gz
-- Using source at C:/vcpkg-master/vcpkg-master/buildtrees/szip/src/szip-2.1.1-6b767acfa7
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package szip[core]:x64-windows... done
Installing package szip[core]:x64-windows...
Installing package szip[core]:x64-windows... done
Elapsed time for package szip:x64-windows: 31.67 s
Starting package 3/3: hdf5:x64-windows
Building package hdf5[core]:x64-windows...
-- Using cached C:/vcpkg-master/vcpkg-master/downloads/CMake-hdf5-1.10.5.tar.gz
-- Using source at C:/vcpkg-master/vcpkg-master/buildtrees/hdf5/src/hdf5-c7a3a597c4
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
-- Building x64-windows-rel

//------------------------------------------------------------------------

Thanks a lot for any help!

**Comment by JackBoosY** [comment]
@dave1717 Thanks for reporting this issue!
Please attach log _C:/vcpkg-master/vcpkg-master/buildtrees/hdf5/build-x64-windows-rel-out.log_.

Thanks.

**Comment by dave1717** [comment]
Thank you for your reply! I tried to install the package again, but now I get a building error (what I find odd, since the installation should run exactly as some days before (note: I removed the packages szip:x64-windows and zlib:x64-windows previous to the installation) ). Here the relevant part of the cmd-output:

//------------------------------------------------------------------
...
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v
    Working Directory: C:/vcpkg-master/vcpkg-master/buildtrees/hdf5/x64-windows-dbg
    See logs for more information:
      C:\vcpkg-master\vcpkg-master\buildtrees\hdf5\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/hdf5/portfile.cmake:53 (vcpkg_install_cmake)
  scripts/ports.cmake:73 (include)


Error: Building package hdf5:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: hdf5:x64-windows
  Vcpkg version: 2019.06.26-nohash
//------------------------------------------------------------------

I can not find the log-file build-x64-windows-rel-out.log in the indicated directory. But here are the other logs which might be helpful:
[config-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/3391092/config-x64-windows-rel-out.log)
[config-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3391093/config-x64-windows-dbg-out.log)
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3391094/install-x64-windows-dbg-out.log)

Thanks again!

**Comment by Cheney-W** [comment]
@dave1717 
What's the version of your cmake? I saw you used a local cmake, could you try to remove the cmake.exe path from the PATH environment variable and re-install this port in a new vcpkg folder?

**Comment by dave1717** [comment]
The cmake version is 3.15.0-rc4. I removed the cmake.exe path from the PATH environment variables, then I reinstalled the vcpkg (deleted the old directory). However, the installation of the hdf5-library seems again to hang at 'Building x64-windows-dbg'-step (I assume it should not take longer than ~10 mins). Probably I misunderstood what you meant by 're-install this port in a new vcpkg folder' - could you please help me at this step?

**Comment by JackBoosY** [comment]
@dave1717 Please provide your Visual Studio version. Reinstall vcpkg to eliminate the problem of building vcpkg, and it doesn't look like this.

Thanks.

**Comment by dave1717** [comment]
The Visual Studio community version is 16.1.6. Reinstall vcpkg does not eliminate the problem.

**Comment by dave1717** [comment]
Please note: By looking at the task manager there are two cmake processes without any activity. Probably cmake slows the building down (?).
![cmakeProcess](https://user-images.githubusercontent.com/48215064/61217717-96090680-a710-11e9-9682-266f16891f6f.png)

**Comment by dave1717** [comment]
As a workaround I followed https://stackoverflow.com/questions/24325508/getting-stared-with-hdf5-on-visual-studio-2013-with-visual-c-2013 and setup the directories in VS manually. Now it is working.
