### ISSUE TITLE
does it support resuming compilation later

### ISSUE THREAD

**Issue by adevelopcr** [microsoft/vcpkg#7253]
I want to use vcpkg to install qt5 which is quite big library and the laptop takes much time to compile
I want to run the compilation only when I am not using the laptob
so can I interrupt the compilation (Ctrl + C) then resume it later ?

**Comment by JackBoosY** [comment]
@adevelopcr The construction process of each port is divided into configuration **debug-build** **debug-configuration** **release-build** **release-installation**. If the build process is forcibly terminated, the port will be **completely** rebuilt.

**Comment by heydojo** [comment]
`Ctrl + C` breaks the compilation process everywhere including vcpkg's running process in a powershell instance or a command prompt window.
This is the accepted default across platforms so, no you cannot interrupt the compilation and resume it later.
You can pause the the console output (but not background compilation processes) using the scr lk (scroll lock) key but it doesn't do what you want to do.

I recommend:

- Assess if you really need to build Qt

What parts of Qt does your application need?
Could you not use the Qt binaries already available for your operating system instead?

- Consider using a powerful dedicated build machine (server or desktop) to build large software libraries and programs instead

The last thing the World needs is more people arbitrarily learning how to compile Qt without any specific reason, when pre-compiled binaries are available everywhere.

Unless you absolutely must have a feature not compiled into the pre-compiled offerings out there - then there is literally no point in compiling Qt. Use the Qt opensource installer or your distribution's (if on Linux) package manager instead.

Qt in vcpkg is not ready for production or even the latest available version (5.12.4 is currently the latest LTS release while 5.12.3 exists in vcpkg as of 15/07/2019.)

**Comment by MikeGitb** [comment]
On bash/linux you can pause a running process by ctrl-z. I'd assume that powershell has something similar.

**Comment by JackBoosY** [comment]
If this issue is still not resolved, please reopen it.
