### ISSUE TITLE
GDAL: Mismatch pdb x64-windows Debug and Release

### ISSUE THREAD

**Issue by tfiner** [microsoft/vcpkg#7256]
Using ChkMatch from http://www.debuginfo.com/tools/chkmatch.html before I end up failing to load the pdbs while debugging:

x64 Release
`E:\vcpkg\installed\x64-windows\bin (master -> origin)
λ c:\Users\Tim\tools\ChkMatch.exe -c gdal204.dll gdal204.pdb
ChkMatch - version 1.0
Copyright (C) 2004 Oleg Starodumov
http://www.debuginfo.com/

Executable: gdal204.dll
Debug info file: gdal204.pdb

Executable:
TimeDateStamp: 5d28bf07
Debug info: 2 ( CodeView )
TimeStamp: 5d28bf07  Characteristics: 0  MajorVer: 0  MinorVer: 0
Size: 96  RVA: 00e85844  FileOffset: 00e84444
CodeView format: RSDS
Signature: {0cf310df-e81e-44dd-9866-489fca0dd3a9}  Age: 288
PdbFile: E:\vcpkg\buildtrees\gdal\src-x64-windows-release\gdal-2.4.1\gdal204.pdb
Debug info: 12 ( Unknown )
TimeStamp: 5d28bf07  Characteristics: 0  MajorVer: 0  MinorVer: 0
Size: 20  RVA: 00e858a4  FileOffset: 00e844a4
Debug info: 13 ( Unknown )
TimeStamp: 5d28bf07  Characteristics: 0  MajorVer: 0  MinorVer: 0
Size: 960  RVA: 00e858b8  FileOffset: 00e844b8

Debug information file:
Format: PDB 7.00
Signature: {0cf310df-e81e-44dd-9866-489fca0dd3a9}  Age: 312

Result: Unmatched (reason: Age mismatch)`

x64 Debug
`E:\vcpkg\installed\x64-windows\debug\bin (master -> origin)
λ c:\Users\Tim\tools\ChkMatch.exe -c gdal204.dll gdal204.pdb
ChkMatch - version 1.0
Copyright (C) 2004 Oleg Starodumov
http://www.debuginfo.com/

Executable: gdal204.dll
Debug info file: gdal204.pdb

Executable:
TimeDateStamp: 5d28be94
Debug info: 2 ( CodeView )
TimeStamp: 5d28be94  Characteristics: 0  MajorVer: 0  MinorVer: 0
Size: 94  RVA: 01d4c23c  FileOffset: 01d4b43c
CodeView format: RSDS
Signature: {2e712a55-eae7-4a31-a666-19ffbd1215c2}  Age: 274
PdbFile: E:\vcpkg\buildtrees\gdal\src-x64-windows-debug\gdal-2.4.1\gdal204.pdb
Debug info: 12 ( Unknown )
TimeStamp: 5d28be94  Characteristics: 0  MajorVer: 0  MinorVer: 0
Size: 20  RVA: 01d4c29c  FileOffset: 01d4b49c

Debug information file:
Format: PDB 7.00
Signature: {2e712a55-eae7-4a31-a666-19ffbd1215c2}  Age: 298

Result: Unmatched (reason: Age mismatch)`

**Comment by JackBoosY** [comment]
Confirmed, but I don't know why.

**Comment by dg0yt** [comment]
This is an ABI changing spot in GDAL:
https://github.com/OSGeo/gdal/blob/16a208e8c8c469b954b14d1c4d02e28c3a972019/gdal/port/cpl_multiproc.h#L62-L70

Options:
- Don't define `DEBUG`. Side effects on the total GDAL code base unknown. Definitely needs more work such as defining `WITH_PDB`.
- Patch this spot. Side effects should be visible at build time. But there might be other spots like this.
- Generate PDBs in the release build, by defining `WITH_PDB`.

For `DEBUG`, `WITH_PDB`, see gdal's `nmake.opt`. I don't build windows triplets outside CI, sonfeedback is needed.

**Comment by dg0yt** [comment]
Is this issue still valid, after switch to the CMake build system with gdal 3.5.0?

**Comment by JackBoosY** [comment]
> Is this issue still valid, after switch to the CMake build system with gdal 3.5.0?

I will checkout this later.

**Comment by dg0yt** [comment]
GDAL eliminated difference between debug and release builds, but I don't remember if this is already in the current release.

**Comment by PhoebeHui** [comment]
```
GDAL eliminated difference between debug and release builds.
```

It was already in currently vcpkg release now, if I understand this correctlly.
