### ISSUE TITLE
C:\Program : The term 'C:\Program' is not recognized

### ISSUE THREAD

**Issue by Aneutronic** [Microsoft/vcpkg#726]
The command line spits this error out at me when I try to invoke vcpkg from the command line while in the default directory cmd starts you in: C:\WINDOWS\system32. I am doing this from an elevated command prompt, by the way.

This is the command I issued while trying to update some of my library installations by reinstalling them after "remove --purge"-ing them as the instructions say:
`vcpkg install boost:x64-windows boost:x86-windows curl:x64-windows curl:x86-windows fmt:x64-windows fmt:x64-windows-static fmt:x86-windows fmt:x86-windows-static freetype:x64-windows freetype:x86-windows gflags:x64-windows gflags:x86-windows glew:x64-windows glew:x86-windows libssh2:x64-windows libssh2:x86-windows lua:x64-windows lua:x86-windows mpir:x64-windows mpir:x86-windows openssl:x64-windows openssl:x86-windows rapidjson:x64-windows rapidjson:x86-windows zlib:x64-windows zlib:x86-windows`

This is the error message I get back:
`C:\Program : The term 'C:\Program' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:1 char:1
+ C:\Program Files\vcpkg\scripts\fetchDependency.ps1 -Dependency cmake
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Launching powershell failed or was denied`

The version of vcpkg I am using is fully updated. I know, because I just barely updated it before trying to update my libraries. It did not do this before. As the error message says, I think the bug lies in a syntax error in the "fetchDependency.ps1" file; however, I do not have the expertise to fix it.

Thank you for any help you an provide!

Edit: I tried the vcpkg library installation command again from the vcpkg directory this time, thinking that it would not have to search through as many directories to orient itself or what have you; however, it still gave the exact same error, still from an elevated command prompt.

**Comment by alexkaratarakis** [comment]
@Aneutronic 
6e094c089151de165d3a78ec573a5c32db5e0b56 should fix this. Please do the following:
1) git pull
2) Run bootstrap.ps1 again
3) Run your install command again

Let me know if the fix worked!

**Comment by Aneutronic** [comment]
Nope. It didn't work. I still got:
'C:\Program : The term 'C:\Program' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:1 char:1
+ C:\Program Files\vcpkg\scripts\fetchDependency.ps1 -Dependency cmake
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Launching powershell failed or was denied'

when I tried to launch:
'vcpkg install boost:x64-windows boost:x86-windows curl:x64-windows curl:x86-windows fmt:x64-windows fmt:x64-windows-static fmt:x86-windows fmt:x86-windows-static freetype:x64-windows freetype:x86-windows gflags:x64-windows gflags:x86-windows glew:x64-windows glew:x86-windows libssh2:x64-windows libssh2:x86-windows lua:x64-windows lua:x86-windows mpir:x64-windows mpir:x86-windows openssl:x64-windows openssl:x86-windows rapidjson:x64-windows rapidjson:x86-windows zlib:x64-windows zlib:x86-windows'

It looks like the problem is still there. Is there another error log somewhere that I should be using?

Thank you for your assistance!

**Comment by alexkaratarakis** [comment]
Got it. This and another issue of handling space when calling powershell should be resolved by 3eb0526468d07824900c462ccfacdeffd7fa1969.

**Comment by cmpute** [comment]
Note: openblas meets the space problem as well.

**Comment by jeffinchiangmai** [comment]
The vcpkg description is wrong. Writing to the command prompt only comes back with errors.
vcpkg search and vcpkg install are obviously not recognised at the command prompt, so why write it?

**Comment by alexkaratarakis** [comment]
@jeffinchiangmai What are the errors?
