### ISSUE TITLE
tesseract 4.0.0. Failed build

### ISSUE THREAD

**Issue by Brooklyn2001** [microsoft/vcpkg#7262]
-- Extracting source C:/dev/vcpkg/downloads/tesseract-ocr-tesseract-4.0.0.tar.gz
-- Applying patch use-vcpkg-icu.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch ws2-32.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch leptonica.patch
-- Using source at C:/dev/vcpkg/buildtrees/tesseract/src/4.0.0-030345c012
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/dev/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: C:/dev/vcpkg/buildtrees/tesseract/x64-windows-dbg
    See logs for more information:
      C:\dev\vcpkg\buildtrees\tesseract\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/tesseract/portfile.cmake:28 (vcpkg_install_cmake)
  scripts/ports.cmake:73 (include)

Error: Building package tesseract:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: tesseract:x64-windows
  Vcpkg version: 2019.06.26-nohash

**Comment by wangli28** [comment]
Hi @Brooklyn2001, thanks for posting this issue!
Please attach log _C:\dev\vcpkg\buildtrees\tesseract\install-x64-windows-dbg-out.log_.

Thanks!

**Comment by Brooklyn2001** [comment]
log
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3397371/install-x64-windows-dbg-out.log)

**Comment by PhoebeHui** [comment]
@Brooklyn2001, thanks for posting this issue!

From your build logs, it seems tesseract has conflict with other ports, it shouldn't use C:\dev\vcpkg\installed\x64-windows\include\platform.h, it should use platform.h under its source tree or other path, could you clean your vcpkg source, and try to install tesseract again? btw, tesseract has upgrade to 4.1.0, pull latest source before install it.

failures:
C:\dev\vcpkg\installed\x64-windows\include\platform.h(394): error C2039: 'string_view': is not a member of 'std'

**Comment by Brooklyn2001** [comment]
after uninstall scintilla tesseract was builded. Thanks
