### ISSUE TITLE
cannot install sfml library with new MSVC compiler 2019 on board, because vcpkg implicitly requires MSVC 2017

### ISSUE THREAD

**Issue by alphaquant2** [microsoft/vcpkg#7265]

**Comment by degski** [comment]
Works for me with only VS2019 installed, something else is wrong.

**Comment by thedevilfish** [comment]
Yup works on mine as well. Can you please provide the error information or logs?

**Comment by alphaquant2** [comment]
OK for you!
here is the records I get with PowerShell


PS E:\alpha\math\C++\librairies\vcpkg-master> .\vcpkg install sfml
The following packages will be built and installed:
    sfml[core]:x86-windows
Starting package 1/1: sfml:x86-windows
Building package sfml[core]:x86-windows...
-- Using cached E:/alpha/math/C++/librairies/vcpkg-master/downloads/SFML-SFML-2.5.1.tar.gz
-- Using source at E:/alpha/math/C++/librairies/vcpkg-master/buildtrees/sfml/src/2.5.1-8da8c5c259
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: E:/alpha/math/C++/librairies/vcpkg-master/buildtrees/sfml/x86-windows-rel/vcpkg-parallel-configure
    See logs for more information:
      E:\alpha\math\C++\librairies\vcpkg-master\buildtrees\sfml\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:259 (vcpkg_execute_required_process)
  ports/sfml/portfile.cmake:22 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package sfml:x86-windows failed with: BUILD_FAILED

**Comment by degski** [comment]
> OK for you!

I bet you I'm not the only one.

    See logs for more information:
    E:\alpha\math\C++\librairies\vcpkg-master\buildtrees\sfml\config-x86-windows-out.log

Did you have a look at the log? It might be helpful to upload/post that, so we can see what's the message is.

**Comment by alphaquant2** [comment]
thanks for the help
here is the log attached
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/3392675/config-x86-windows-out.log)

**Comment by degski** [comment]
Thanks, did you have VS2017 installed before, and uninstalled it [coz it looks like that's what we are seeing]?

**Comment by alphaquant2** [comment]
yes indeed I put VS2019 alongside for one month, then I uninstalled VS2017
Jérôme

**Comment by degski** [comment]
You should do a `git pull` run `bootstrap-vcpkg.bat` and try again.

**Comment by alphaquant2** [comment]
I was able to do all you proposed and it worked fine, thanks a lot - issue closed!
I have now installed:
sfml:x86-windows                                   2.5.1-1          Simple and fast multimedia library

regards, Jérôme

**Comment by degski** [comment]
@alphaquant2 You're welcome!

**Comment by wangli28** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
