### ISSUE TITLE
Libraries which would be nice for Compiler Explorer to have

### ISSUE THREAD

**Issue by strega-nil** [microsoft/vcpkg#7268]
The Microsoft CE servers should end up using vcpkg as the installer for libraries. The following libraries are available through the regular CE servers, but are not yet available in vcpkg's ports.

  - [x] [brigand]
  - [x] [cmcstl2]
  - [x] [ctbignum]
  - [x] [hfsm2]; note that CE uses hfsm 1, which hasn't been updated in ~a year.
  - [x] [kvasir-mpl]
  - [x] [libguarded]
  - [x] [ned14-outcome]
  - [ ] [scylladb-seastar]
  - [x] [agner-fog-vcl]

[brigand]: https://github.com/edouarda/brigand
[cmcstl2]: https://github.com/CaseyCarter/cmcstl2
[ctbignum]: https://github.com/niekbouman/ctbignum
[hfsm2]: https://github.com/andrew-gresyk/HFSM2
[kvasir-mpl]: https://github.com/kvasir-io/mpl
[libguarded]: https://github.com/copperspice/libguarded
[ned14-outcome]: https://github.com/ned14/outcome
[scylladb-seastar]: https://github.com/scylladb/seastar
[agner-fog-vcl]: https://www.agner.org/optimize/vectorclass.pdf

**Comment by NancyLi1013** [comment]
It seems that only  `scylladb-seastar` needs to be added now.

If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by theidexisted** [comment]
I wich to add scylladb-seastar. The projects have these dependencies:

```
    ninja-build
    ragel
    libhwloc-dev
    libnuma-dev
    libpciaccess-dev
    libcrypto++-dev
    libboost-all-dev
    libxml2-dev
    xfslibs-dev
    libgnutls28-dev
    liblz4-dev
    libsctp-dev
    gcc
    make
    libprotobuf-dev
    protobuf-compiler
    python3
    systemtap-sdt-dev
    libtool
    cmake
    libyaml-cpp-dev
    libc-ares-dev
    stow
    g++
    libfmt-dev
    diffutils
    valgrind
```
Some of them are missing from vcpkg now, do we need to add the dependencies at first?

**Comment by PhoebeHui** [comment]
@theidexisted, the dependencies need to be added firstly if they are required from the port.
