### ISSUE TITLE
Cannot Install Cairo as a Static Library

### ISSUE THREAD

**Issue by trainingmode** [microsoft/vcpkg#7270]
I've been trying to install Cairo using the latest vcpkg with

`.\vcpkg install cairo:x64-windows-static`

to build, but run into

```
Error: Building package glib:x64-windows-static failed with: BUILD_FAILED

Package: glib:x64-windows-static

Vcpkg version: 2019.06.26-nohash
```

when encountering the glib dependency.

How might I remedy this? Thank you so much for any help!

**Comment by Voskrese** [comment]
cairo? **glib**  failed with: BUILD_FAILED

not support static glib

**Comment by trainingmode** [comment]
Yes, the glib dependency needed to build Cairo failed. As per the info given by vcpkg:

`PS > .\vcpkg install cairo:x64-windows-static`

`The following packages will be built and installed:
    cairo[core]:x64-windows-static
  * dirent[core]:x64-windows-static
  * expat[core]:x64-windows-static
  * fontconfig[core]:x64-windows-static
  * glib[core]:x64-windows-static`

The full output is below:

`The following packages will be built and installed:
    cairo[core]:x64-windows-static
  * dirent[core]:x64-windows-static
  * expat[core]:x64-windows-static
  * fontconfig[core]:x64-windows-static
  * glib[core]:x64-windows-static
Additional packages (*) will be modified to complete this operation.
Starting package 1/5: glib:x64-windows-static
Building package glib[core]:x64-windows-static...
-- Note: glib only supports dynamic library linkage. Building dynamic library.
CMake Error at scripts/cmake/vcpkg_check_linkage.cmake:42 (message):
  Refusing to build unexpected dynamic library against the static CRT.  If
  this is desired, please configure your triplet to directly request this
  configuration.
Call Stack (most recent call first):
  ports/glib/portfile.cmake:10 (vcpkg_check_linkage)
  scripts/ports.cmake:73 (include)


Error: Building package glib:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glib:x64-windows-static
  Vcpkg version: 2019.06.26-nohash`

I will mess about with the cmake script for glib (I think it's in /ports/glib/portfile.cmake) in hopes that I can get it to build statically.

**Comment by Voskrese** [comment]
The network has patches for static assembly

**Comment by trainingmode** [comment]
I set that up as a triplet, yes?

And thank you very much, I'm so grateful for your help :)

**Comment by Voskrese** [comment]
> do not mix dynamic libraries with static libraries
> then there will be a lot of problems with linking

imho

https://github.com/microsoft/vcpkg/blob/master/ports/glib/portfile.cmake

delete

```
# Glib uses winapi functions not available in WindowsStore
if(VCPKG_CMAKE_SYSTEM_NAME STREQUAL WindowsStore)
    message(FATAL_ERROR "Error: UWP builds are currently not supported.")
endif()

# Glib relies on DllMain on Windows
if (NOT VCPKG_CMAKE_SYSTEM_NAME)
    vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY ONLY_DYNAMIC_CRT)
endif()
```

add `vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY ONLY_DYNAMIC_CRT)`

**Comment by trainingmode** [comment]
Thanks so much Voskrese, I've finally got it working as it should be!

I removed what you said but instead of adding dynamic I added:

`vcpkg_check_linkage(ONLY_STATIC_LIBRARY ONLY_STATIC_CRT)`

Doing this finally got glib to build and the debug succeeded, but the release failed. I tried updating glib versions in the portfile, but just ran into ninja build errors even after I tried deleting `PREFER_NINJA` so I switched back to 2.52.3.

Finally found the solution under `vcpkg_configure_cmake`. You need to swap `-DGLIB_SKIP_TOOLS=ON` to apply to both debug and release like so:

'''
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -DGLIB_VERSION=${GLIB_VERSION}
        -DGLIB_SKIP_TOOLS=ON
    OPTIONS_DEBUG
        -DGLIB_SKIP_HEADERS=ON
)
```

Afterwards, glib built properly and the Cairo build continued on as normal.

**Comment by zcream** [comment]
Has something changed? I get the same error

```
-- Note: glib only supports dynamic library linkage. Building dynamic library.
CMake Error at scripts/cmake/vcpkg_check_linkage.cmake:42 (message):
  Refusing to build unexpected dynamic library against the static CRT.  If
  this is desired, please configure your triplet to directly request this
  configuration.
Call Stack (most recent call first):
  ports/glib/portfile.cmake:6 (vcpkg_check_linkage)
  scripts/ports.cmake:76 (include)
```

In portfile.cmake, I have

```
# Glib relies on DllMain on Windows
if (VCPKG_TARGET_IS_WINDOWS)
    vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
endif()
```

I changed to `vcpkg_configure_cmake`

```
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS ${FEATURE_OPTIONS}
        -DGLIB_VERSION=${GLIB_VERSION}
        -DGLIB_SKIP_TOOLS=ON
    OPTIONS_DEBUG
        -DGLIB_SKIP_HEADERS=ON
)
```

**Comment by trainingmode** [comment]
Hello zcream, please try updating the linkage check to the following:

`vcpkg_check_linkage(ONLY_STATIC_LIBRARY ONLY_STATIC_CRT)`

It should look like:
```
# Glib relies on DllMain on Windows
if (VCPKG_TARGET_IS_WINDOWS)
     vcpkg_check_linkage(ONLY_STATIC_LIBRARY ONLY_STATIC_CRT)
endif()
```

The error you received is questioning if you should perform the desired linkage, as you'll be mixing a dynamic library with a static library. To get it to pass, you need to explicitly state that you want to perform the build and link the library by using the `ONLY_STATIC_LIBRARY` and `ONLY_STATIC_CRT` flags.

**Comment by zcream** [comment]
Hi. I made the change you mentioned as well as    `-DGLIB_SKIP_TOOLS=ON ` mentioned earlier.
I get the following error
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: C:/Users/Administrator/vcpkg/buildtrees/pango/x64-windows
-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\Administrator\vcpkg\buildtrees\pango\config-x64-windows-static-ou
t.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:299 (vcpkg_execute_required_process)

  ports/pango/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:76 (include)
```

**Comment by zcream** [comment]
This is the part that now fails the build 

```
       message(STATUS "Configuring ${TARGET_TRIPLET}")
        vcpkg_execute_required_process(
            COMMAND ninja -v
            WORKING_DIRECTORY ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/vcpkg-parallel-configure
            LOGNAME config-${TARGET_TRIPLET}
        )
```

**Comment by trainingmode** [comment]
It seems the way I fixed any Ninja build errors was by switching Glib back to version 2.52.3. Unfortunately, that's all I can offer for now as I have since moved on from Cairo (and this is one example of why). I ended up writing my own renderer.

**Comment by zcream** [comment]
This thread was very helpful to me. Thanks anyway. How did you revert to a previous version of glib i.e. 2.52.3 ? vcpkg only allow date-based filtering of libraries, IMO.

**Comment by trainingmode** [comment]
No problem, sorry I couldn't be of more help. I think I either downloaded the package from the official repository [(located here)](https://developer.gnome.org/glib/) or I managed to revert it somehow using vcpkg (but I don't remember how to do that).
