### ISSUE TITLE
PMDK:x64-windows failed

### ISSUE THREAD

**Issue by weishuo2** [microsoft/vcpkg#7274]
Error: Building package pmdk:x64-windows failed with: BUILD_FAILED
 Package: pmdk:x64-windows
 Vcpkg version: 2019.06.26-nohash

**Comment by wangli28** [comment]
Hi @weishuo2, can you provide the information about your environment? And attach your build log.
Thanks!

**Comment by weishuo2** [comment]
------------------ 原始邮件 ------------------
发件人: "wangli28"<notifications@github.com>;
发送时间: 2019年7月17日(星期三) 上午10:49
收件人: "microsoft/vcpkg"<vcpkg@noreply.github.com>;
抄送: "华中科技大学魏硕"<2411602273@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [microsoft/vcpkg] PMDK:x64-windows failed (#7274)




Hi @weishuo2, can you provide the information about your environment? And attach your build log.
 Thanks!

**Comment by weishuo2** [comment]
windows10,vs2019




------------------ 原始邮件 ------------------
发件人: "wangli28"<notifications@github.com>;
发送时间: 2019年7月17日(星期三) 上午10:49
收件人: "microsoft/vcpkg"<vcpkg@noreply.github.com>;
抄送: "华中科技大学魏硕"<2411602273@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [microsoft/vcpkg] PMDK:x64-windows failed (#7274)




Hi @weishuo2, can you provide the information about your environment? And attach your build log.
 Thanks!

**Comment by wangli28** [comment]
I can't reproduce this issue locally. I installed it successfully with Visual Studio 2019 and VCPKG latest source. Do you run command `git pull` before installing this port.

.\vcpkg.exe install pmdk:x64-windows
The following packages will be built and installed:
    pmdk[core]:x64-windows
Starting package 1/1: pmdk:x64-windows
Building package pmdk[core]:x64-windows...
-- Downloading https://github.com/pmem/pmdk/archive/1.6.tar.gz...
......
Building package pmdk[core]:x64-windows... done
Installing package pmdk[core]:x64-windows...
Installing package pmdk[core]:x64-windows... done
Elapsed time for package pmdk:x64-windows: 12.7 min

Total elapsed time: 12.7 min

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.

**Comment by Hyuga-Hinata** [comment]
Error: Building package pmdk:x64-windows failed with: BUILD_FAILED                                                                  Please ensure you're using the latest portfiles with `.\vcpkg update`, then                                                         submit an issue at https://github.com/Microsoft/vcpkg/issues including:                                                               Package: pmdk:x64-windows                                                                                                           Vcpkg version: 2020.06.15-nohash

**Comment by Hyuga-Hinata** [comment]
Error: Building package pmdk:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then  submit an issue at https://github.com/Microsoft/vcpkg/issues including: 
Package: pmdk:x64-windows
Vcpkg version: 2020.06.15-nohash
