### ISSUE TITLE
"vcpkg install python3" fails with VS 2015

### ISSUE THREAD

**Issue by pederson** [microsoft/vcpkg#7284]
executing command "vcpkg.exe install python3:x64-windows --debug" gives the following output:

*****************************************************************************************************
[DEBUG] Using vcpkg-root: C:\Users\aagarwal\Documents\ankur_files\Packages\vcpkg
The following packages will be built and installed:
    python3[core]:x64-windows
Starting package 1/1: python3:x64-windows
Building package python3[core]:x64-windows...
[DEBUG] Found path: C:\Program Files\CMake\bin\cmake.exe
[DEBUG] _wpopen(""C:\Users\aagarwal\Documents\ankur_files\Packages\vcpkg\downloads\tools\cmake-3.14.0-windows\cmake-3.14.0-win32-x86\bin\cmake.exe" --version 2>&1")
[DEBUG] _pclose() returned 0 after  1146020 us
[DEBUG] _wpopen(""C:\Users\aagarwal\Documents\ankur_files\Packages\vcpkg\downloads\tools\cmake-3.14.0-windows\cmake-3.14.0-win32-x86\bin\cmake.exe" "-DCMAKE_TRIPLET_FILE=C:/Users/aagarwal/Documents/ankur_files/Packages/vcpkg/triplets/x64-windows.cmake" -P "C:/Users/aagarwal/Documents/ankur_files/Packages/vcpkg/scripts/get_triplet_environment.cmake" 2>&1")
[DEBUG] _pclose() returned 0 after   840735 us
[DEBUG] Found path: C:\Program Files\Git\cmd\git.exe
[DEBUG] _wpopen(""C:\Users\aagarwal\Documents\ankur_files\Packages\vcpkg\downloads\tools\git-2.21.0-1-windows\mingw32\bin\git.exe" --version 2>&1")
[DEBUG] _pclose() returned 0 after    41932 us
[DEBUG] CreateProcessW(cmd.exe /c ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"  x64   2>&1 <NUL & "C:\Users\aagarwal\Documents\ankur_files\Packages\vcpkg\downloads\tools\cmake-3.14.0-windows\cmake-3.14.0-win32-x86\bin\cmake.exe" "-DCMD=BUILD" "-DPORT=python3" "-DCURRENT_PORT_DIR=C:/Users/aagarwal/Documents/ankur_files/Packages/vcpkg/ports/python3" "-DTARGET_TRIPLET=x64-windows" "-DTARGET_TRIPLET_FILE=C:\Users\aagarwal\Documents\ankur_files\Packages\vcpkg\triplets\x64-windows.cmake" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DVCPKG_USE_HEAD_VERSION=0" "-DDOWNLOADS=C:/Users/aagarwal/Documents/ankur_files/Packages/vcpkg/downloads" "-D_VCPKG_NO_DOWNLOADS=0" "-D_VCPKG_DOWNLOAD_TOOL=BUILT_IN" "-DFEATURES=core" "-DALL_FEATURES=" "-DVCPKG_CONCURRENCY=5" "-DGIT=C:/Users/aagarwal/Documents/ankur_files/Packages/vcpkg/downloads/tools/git-2.21.0-1-windows/mingw32/bin/git.exe" -P "C:/Users/aagarwal/Documents/ankur_files/Packages/vcpkg/scripts/ports.cmake"")
-- Using cached C:/Users/aagarwal/Documents/ankur_files/Packages/vcpkg/downloads/python-cpython-v3.7.3.tar.gz
-- Extracting source C:/Users/aagarwal/Documents/ankur_files/Packages/vcpkg/downloads/python-cpython-v3.7.3.tar.gz
-- Using source at C:/Users/aagarwal/Documents/ankur_files/Packages/vcpkg/buildtrees/python3/src/v3.7.3-1161ad7a91
-- Building C:/Users/aagarwal/Documents/ankur_files/Packages/vcpkg/buildtrees/python3/src/v3.7.3-1161ad7a91-Lib-dynamic-crt-dynamic/PCBuild/pythoncore.vcxproj for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:58 (message):
    Command failed: msbuild C:/Users/aagarwal/Documents/ankur_files/Packages/vcpkg/buildtrees/python3/src/v3.7.3-1161ad7a91-Lib-dynamic-crt-dynamic/PCBuild/pythoncore.vcxproj /p:Configuration=Release /t:Rebuild /p:Platform=x64 /p:PlatformToolset=v140 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion= /m
    Working Directory: C:/Users/aagarwal/Documents/ankur_files/Packages/vcpkg/buildtrees/python3/x64-windows-rel
    Error code: 1
    See logs for more information:
      C:\Users\aagarwal\Documents\ankur_files\Packages\vcpkg\buildtrees\python3\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:119 (vcpkg_execute_required_process)
  ports/python3/portfile.cmake:37 (vcpkg_build_msbuild)
  scripts/ports.cmake:73 (include)

[DEBUG] CreateProcessW() returned 1 after 50195420 us
Error: Building package python3:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: python3:x64-windows
  Vcpkg version: 2019.06.26-nohash

Additionally, attach any relevant sections from the log files above.
[DEBUG] ..\src\vcpkg\install.cpp(444)
[DEBUG] Exiting after 53335714 us (53325761 us)
*****************************************************************************************************

And the contents of build-x64-windows-rel-out.log are:
*****************************************************************************************************
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 7/15/2019 2:38:44 PM.
     1>Project "C:\Users\aagarwal\Documents\ankur_files\Packages\vcpkg\buildtrees\python3\src\v3.7.3-1161ad7a91-Lib-dynamic-crt-dynamic\PCBuild\pythoncore.vcxproj" on node 1 (Rebuild target(s)).
     1>C:\Users\aagarwal\Documents\ankur_files\Packages\vcpkg\buildtrees\python3\src\v3.7.3-1161ad7a91-Lib-dynamic-crt-dynamic\PCBuild\python.props(85,31): error MSB4184: The expression "[System.Version]::Parse('')" cannot be evaluated. Version string portion was too short or too long. [C:\Users\aagarwal\Documents\ankur_files\Packages\vcpkg\buildtrees\python3\src\v3.7.3-1161ad7a91-Lib-dynamic-crt-dynamic\PCBuild\pythoncore.vcxproj]
     1>Done Building Project "C:\Users\aagarwal\Documents\ankur_files\Packages\vcpkg\buildtrees\python3\src\v3.7.3-1161ad7a91-Lib-dynamic-crt-dynamic\PCBuild\pythoncore.vcxproj" (Rebuild target(s)) -- FAILED.

Build FAILED.

       "C:\Users\aagarwal\Documents\ankur_files\Packages\vcpkg\buildtrees\python3\src\v3.7.3-1161ad7a91-Lib-dynamic-crt-dynamic\PCBuild\pythoncore.vcxproj" (Rebuild target) (1) ->
         C:\Users\aagarwal\Documents\ankur_files\Packages\vcpkg\buildtrees\python3\src\v3.7.3-1161ad7a91-Lib-dynamic-crt-dynamic\PCBuild\python.props(85,31): error MSB4184: The expression "[System.Version]::Parse('')" cannot be evaluated. Version string portion was too short or too long. [C:\Users\aagarwal\Documents\ankur_files\Packages\vcpkg\buildtrees\python3\src\v3.7.3-1161ad7a91-Lib-dynamic-crt-dynamic\PCBuild\pythoncore.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.02
*****************************************************************************************************

From what I can tell, this might be an issue of not setting a value for the msbuild argument WindowsTargetPlatformVersion, which is an automatic build error for VS2015 (see: https://thinkinginsideadifferentbox.wordpress.com/2018/12/29/automatic-detection-of-installed-windowstargetplatformversion/)

**Comment by lwkobe** [comment]
Hi,  you need to update vs2015   and install Windows 10 SDK into Visual Studio. this link (https://social.msdn.microsoft.com/Forums/vstudio/en-US/2f3d5130-f3f9-4771-a6f2-c5883aea0414/installing-windows-10-sdk-into-visual-studio?forum=vssetup)
maybe help you.

**Comment by PhoebeHui** [comment]
@pederson, please install windows sdk via VS, and try again.

@lwkobe, thanks for your reply.
