### ISSUE TITLE
Why does LLVM require atlmfc?

### ISSUE THREAD

**Issue by ubsan** [microsoft/vcpkg#7287]
I just built LLVM 8.0 with vcpkg, with the atlmfc dependency commented out, and it worked (x86-windows). Why is it still there?

cc #2400 #1912 8791faba96649f9536e33f41c14781652790d084

**Comment by crusader-mike** [comment]
I noticed same thing in other ports -- certain configurations "over-depend". It is especially bad when you deal with components -- some libraries have a lot of them and pulling one little component could drop entire Boost on you (even though it isn't used at all). Classify it as a port bug, I guess...

**Comment by crackedmind** [comment]
atlmfc dependency just checking atlmfc installation. if you have already installed atlmfc, llvm will build successfull without this dependency. llvm internally uses atl for DIA (Debug Interface Access) to manipulate pdb files. It can be disabled through cmake (enabled by default).

**Comment by ubsan** [comment]
@crackedmind oh? I don't have atlmfc installed, and 8.0.0 seemed to compile (the reason I figured this out is because I deleted it, because I don't want to install atlmfc if it's unnecessary)

**Comment by ubsan** [comment]
Hmm! looks like I might have had a part of ATL installed somehow? It worked on one of my machines, but not on the build server. Sorry!
