### ISSUE TITLE
luajit library is linked to debug vc++ libraries

### ISSUE THREAD

**Issue by 375gnu** [microsoft/vcpkg#7288]
Both debug and release versions of luajit are linked against VCRUNTIME140D.dll and ucrtbased.dll

**Comment by JackBoosY** [comment]
@375gnu 
According to the results of the dependcy walker analysis, luajit's release library relies on VCRUNTIME140.dll instead of VCRUNTIME140D.dll.

Can you confirm it?

**Comment by 375gnu** [comment]
@JackBoosY 

I have spent some time trying to find the root cause of the issue. So the problem is caused by VC++ tools: during the build infamous mspdbsrv and vctip and something else what I wasn't able to identify are spawned to process created files (create files with debug info and so on). Every single time one of these processes doesn't stop and continue to keep built minilua.exe open.
The build process looks like:
1) a debug version of minilua is compiled
2) minilua is used to compile rest of data
3) debug version of lua51.dll is installed to its destination
4) vcpkg tries to build a release version of minilua but it's unable cause minilua.exe is blocked
5) vcpkg ignores failure and installs debug version as release one.

I think dbg & rel builds should use different directories.

**Comment by Rastaban** [comment]
I agree that the debug and release builds should have different output directories, unfortunately it does not look like the `msvcbuild` script they provide has a destination directory.  The library is not too large so we could probably just copy the contents of the `${SOURCE_PATH}/src` directory to `${CURRENT_BUILDTREES_DIR}/${triplet}-dbg` and `${CURRENT_BUILDTREES_DIR}/${triplet}-rel` for each of the builds.

**Comment by JackBoosY** [comment]
Hi @375gnu Can you test #7764 to solve this issue?

**Comment by 375gnu** [comment]
Hi @JackBoosY, with your PR luajit is compiled and installed properly. Thank you!

**Comment by JackBoosY** [comment]
@375gnu Please update vcpkg and rebuild luajit.

Thanks.
