### ISSUE TITLE
VS2015u3 boost-system 1.70 build fails due to tool chain identification and/or port mismatch

### ISSUE THREAD

**Issue by whozcraig** [microsoft/vcpkg#7295]
Please note this worked without issue until boost 1.70 venture.  I originally discovered this while trying to build the **cpprestsdk** for x64-windows, and narrowed it down to this.

Some platform and toolchain info
Windows 10 Pro
Microsoft Visual Studio Professional 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.7.03056

There are several unusual build failures, but all roads eventually lead to boost 1.70

**boost-system:x64-windows** 
Steps to Reproduce:
1. git a clean vcpkg
2. run bootstrap-vcpkg.bat
3. vcpkg install boost-system:x64-windows

The resulting failure takes us to the following, which is hopefully helpful in tracking down the disconnect: [build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/3399969/build-x64-windows-rel-out.log)

Bending my mind was the lack of a *compiler* on the build line that failed. Just the switches. Odd.

**Trying x86 Instead**
Remember, this was discovered while attempting to build cpprestsdk. When switching to x86, again on a virgin clean vcpkg clone+bootstrap, I narrowed this failure down to **boost-thread**. Note that boost-system:x86-windows had no issue, but later boost-thread reported this: [build-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/3400006/build-x86-windows-rel-out.log)

Of particular note was the apparent miss-identification of the library for boost-chrono. That dependency was built successfully, but according to the build-failure log, the library being sought was 

> C:/vcpkg/installed/x86-windows/lib/boost_chrono-vc140-mt.lib

whereas the actual library on disk built during dependencies is/was:

> C:/vcpkg/installed/x86-windows/lib/boost_chrono-vc6.lib

Whatever else is happening, it appears there is a disconnect in platform ids at this point.

Finally, note that *nothing* has changed regarding the tool chain on this machine for almost a year. VS2015u3 has been solid and unflappable, and was so until the recent changes in what appears to be boost (huge assumption on my part, but I'm sure you're correct me if that's inaccurate). 

If you need anything else, let me know. IF I'm doing something wrong, _definitely_ let me know. I was saddened by this, as vcpkg worked so well for our needs until this. Thanks.

**Comment by whozcraig** [comment]
If there is something else you need from me, please let me know. I had hoped the included logs and steps were sufficient to explain my problem, but if not, and there is additional info needed, feel free to ask. Likewise, If you need any scripts or tests executed to gather instrumentation.

**Comment by whozcraig** [comment]
Still unclear if there is something else I need to provide for this issue. If the build logs aren't enough please advise whatever information is needed. Thanks.

**Comment by whozcraig** [comment]
I now have two (and soon more) VS2015u3 environments that produce this problem. I'm not sure what repro steps you want. I'll be happy to scrape any system information you need, and I may be able to provide remote-desktop support access to one of the rigs. I sincerely would like this looked at, so again, if I'm missing something regarding information I need to provide, **please** let me know what else you need, or what I can do to assist.

**Comment by whozcraig** [comment]
Update: There is no update. With the latest pick of vcpkg, bootstrap and following instructions above, the identical problems continue to happen. 

Same platform

**Windows 10 Pro
Microsoft Visual Studio Professional 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.7.03056**

### **boost-system x64-windows still fails**
In case anyone cares, the boost-system problem mentioned above still generates this for the link line:: 

    [compile-c-c++ C:\vcpkg\buildtrees\boost-system\x64-windows-rel\boost\build\c9b01f15b8fde3c2f6a38607fe67ea92\error_code.obj
    msvc.link.dll C:\vcpkg\buildtrees\boost-system\x64-windows-rel\boost\build\c9b01f15b8fde3c2f6a38607fe67ea92\boost_system-vc6-mt-x64-1_70.dll
    '/DLL' is not recognized as an internal or external command, operable program or batch file.

          /DLL /DEBUG /OPT:REF,ICF /subsystem:console /out:"C:\vcpkg\buildtrees\boost-system\x64-windows-rel\boost\build\c9b01f15b8fde3c2f6a38607fe67ea92\boost_system-vc6-mt-x64-1_70.dll" /IMPLIB:"C:\vcpkg\buildtrees\boost-system\x64-windows-rel\boost\build\c9b01f15b8fde3c2f6a38607fe67ea92\boost_system-vc6-mt-x64-1_70.lib"    @"C:\vcpkg\buildtrees\boost-system\x64-windows-rel\boost\build\c9b01f15b8fde3c2f6a38607fe67ea92\boost_system-vc6-mt-x64-1_70.dll.rsp"
        if %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%

    ...failed msvc.link.dll C:\vcpkg\buildtrees\boost-system\x64-windows-rel\boost\build\c9b01f15b8fde3c2f6a38607fe67ea92\boost_system-vc6-mt-x64-1_70.dll C:\vcpkg\buildtrees\boost-system\x64-windows-rel\boost\build\c9b01f15b8fde3c2f6a38607fe67ea92\boost_system-vc6-mt-x64-1_70.lib C:\vcpkg\buildtrees\boost-system\x64-windows-rel\boost\build\c9b01f15b8fde3c2f6a38607fe67ea92\boost_system-vc6-mt-x64-1_70.pdb C:\vcpkg\buildtrees\boost-system\x64-windows-rel\boost\build\c9b01f15b8fde3c2f6a38607fe67ea92\boost_system-vc6-mt-x64-1_70.pdb...
    ...failed updating 1 target...
    ...updated 6 targets...](url)

You're reading that correctly. **There is no program name before the cmdline switches**; the same as a month ago were anyone to open the attached log and inspect it. Also worth mentioning, the library name being created is **wrong**. It is this:

    boost_system-vc6-mt-x64-1_70.dll 

it should be this:

    boost_system-vc140-mt-x64-1_70.dll 
    
For whatever reason, vcpkg and/or boost seem to believe that they're building with VC6.0, which I haven't had installed, nor owned, on a development workstation in well over a decade, and certainly not this one. 

### **boost-thread x86-windows still fails**

The identical problem of building x86 boost-system on VS2015u3 also fails, with one share symptom: the files are written with the wrong tool chain id for dependent projects, but not when actually trying to wire up the dependencies. That deserves an explanation.

Building `boost-thread:x86-windows` by doing this:

    c:\vcpkg>.\vcpkg install boost-thread:x86-windows

will kick off a build task list of 54 packages. Most of them aren't even really builds per'se; they're literally just copying headers into include folders (boost is, after all, a template library for the most part). Once it does start building the actual libraries needed for boost-thread, several are built, including the following, taken from installed/x86-windows/lib:

```
08/14/2019  05:24 PM             3,474 boost_atomic-vc6-mt.lib
08/14/2019  05:23 PM            24,590 boost_chrono-vc6-mt.lib
08/14/2019  05:24 PM            45,356 boost_container-vc6-mt.lib
08/14/2019  05:25 PM            29,702 boost_date_time-vc6-mt.lib
08/14/2019  05:24 PM            31,886 boost_exception-vc6-mt.lib
08/14/2019  05:25 PM             8,072 boost_math_c99-vc6-mt.lib
08/14/2019  05:25 PM             8,210 boost_math_c99f-vc6-mt.lib
08/14/2019  05:25 PM             8,210 boost_math_c99l-vc6-mt.lib
08/14/2019  05:25 PM             6,816 boost_math_tr1-vc6-mt.lib
08/14/2019  05:25 PM             6,952 boost_math_tr1f-vc6-mt.lib
08/14/2019  05:25 PM             6,952 boost_math_tr1l-vc6-mt.lib
08/14/2019  05:24 PM         1,184,614 boost_regex-vc6-mt.lib
08/14/2019  05:23 PM             2,220 boost_system-vc6-mt.lib
              13 File(s)      1,367,054 bytes
```

Note that these libraries all have something in common: Like the previous problem, the tool chain is misidentified. That vc6 should be vc140. That's important, because the actual failure (the 54th and final project, boost-thread, fails with this:

    error: Unable to find file or target named
    error:     '/boost//C:/vcpkg2/installed/x86-windows/lib/boost_chrono-vc140-mt.lib'
    error: referred to from project at
    error:     '..'

The odd path notwithstanding (anyone taking a guess at what /boost// is doing in front of that file is welcome comment) the _file name_ is wrong (or I should say, the file name is _right_ , but was wrong when it was actually generated?

Directly above in the same log is this:

```
notice: Loading explicitly specified user configuration file:
    C:\vcpkg2\buildtrees\boost-thread\x86-windows-rel\user-config.jam
notice: Searching 'C:\vcpkg2\buildtrees\boost-thread\x86-windows-rel' for user-config configuration file 'user-config.jam'.
notice: Loading user-config configuration file 'user-config.jam' from 'C:/vcpkg2/buildtrees/boost-thread/x86-windows-rel'.
notice: [msvc-cfg] msvc-14.0 detected, command: 'C:\vs2015\VC\bin\cl.exe'
notice: will use 'C:\vs2015\VC\bin\amd64_x86\cl.exe' for msvc, condition <toolset>msvc-6.0
notice: [msvc-cfg] condition: '<toolset>msvc-6.0/<architecture>/<address-model>', setup: 'C:/vcpkg2/installed/x86-windows/share/boost-build/nothing.bat x86'
notice: [msvc-cfg] condition: '<toolset>msvc-6.0/<architecture>/<address-model>32', setup: 'C:/vcpkg2/installed/x86-windows/share/boost-build/nothing.bat x86'
notice: [msvc-cfg] condition: '<toolset>msvc-6.0/<architecture>x86/<address-model>', setup: 'C:/vcpkg2/installed/x86-windows/share/boost-build/nothing.bat x86'
notice: [msvc-cfg] condition: '<toolset>msvc-6.0/<architecture>x86/<address-model>32', setup: 'C:/vcpkg2/installed/x86-windows/share/boost-build/nothing.bat x86'
```

which I found interesting, because the correct tool chain appears detected, then one line later, the _wrong_ tool chain seems to be selected. If that isn't the case, kindly correct the error of my ways.

I haven't given up yet, but I'm about to. I have two developers that are running out of things to do while waiting for advice or a response on this, so if you have anything (willing to try meditation and chanting) please let me know.

**Comment by whozcraig** [comment]
So I gave up. It's been over a month since I asked for any assistance on this, two days later the issues was marked for "needs repro", and though I begged and pleaded, have heard nothing but crickets since. So, I...

1. Wiped, then installed virgin-pure licensed Windows 10 Pro on a new SSD.
2. Windows Update to current.
3. Installed VS2015U3 from hash-checked ISO to c:\vs2015
4. Windows Update to current
5. Installed git version 2.23.0.windows.1
6. Cloned master vcpkg
7. Ran bootstrap.bat
8. Ran vcpkg install boost-thread:x86-windows
9. Build failure is STILL there.

You can't get cleaner than that. If you did that and it doesn't repro in your rig, then kindly tell me what you did different than above, because at this point I'm concluding the words "needs-repro" means "did-not-try-to-repro"

After much pain, I found the last sha hash of the repository _prior_ to update to boost 1.70, checked that out, then proceeded from (7) onward in the above list, and the build SUCCEEDS (which I somewhat expected, as I've been saying all along this has to do with the boost upgrade). So please let that settle any question about whether it is my environment or not. 

Related to the above, in the failing case (current of master), when perusing the build library results, all libs that _should_ be boost\*vc140-mt.lib are instead boost\*vc6-mt.lib, which eventually leads to failure when someone expecting vc140 libs doesn't find them. That problem does NOT happen prior to the boost 1.70 upgrade checked in back in May. Synced to that hash, the build succeeds without issue and all generated libs are vc140-mt as expected. 

I don't know where the problem is, and I suspect I never will, as I simply don't have anymore time to pour into this. I was originally the proponent for vcpkg to management, but it looks like they're going to choose a different package management system now, in part because of this issue. 

Thanks. I hope someday someone else finds this useful.

**Comment by whozcraig** [comment]
Here is your repro:

Install VS2015 to any path _other_ than the default path. (I used c:\vs2015 because I hate the MS love-affair with long, space-embedded path names that eventually end up clogging my PATH environment). Use that for vcpkg build and management

_That's it_

Doing everything else as you normally would, building will fail for both boost-thread:x86-windows and boost-system:x64-windows, and in both cases it is because the build detection (a) find the correct build tools, but then (b) derives the toolset moniker (vc120, vc140, vc141, vc6) from the actual folder path to those tools. Since it doesn't succeed in matching known paths mapped to monikers the derivation algorithm runs home to momma and defaults to vc6, which is completely wrong. Later code that _correctly_ detects the vc140 build tool usage expects to find libraries from dependent projects matching that moniker, but none exist.

Thanks for the help. Somehow I suspect this stands no chance of being fixed anytime soon.

**Comment by NancyLi1013** [comment]
@whozcraig  thanks for posting this issue. If this is still a problem for you, please don't close it. Sorry for the late reply.

**Comment by PhoebeHui** [comment]
@whozcraig, very sorry for late reply.

Boost currently upgrade to 1.71.0, could you build boost-thread with latest source and see if this issue repro? I can't repro it with 1.71.0.

The name looks correct for me.
12/09/2019  03:41 PM             3,506 boost_atomic-vc140-mt.lib
12/09/2019  03:39 PM            24,688 boost_chrono-vc140-mt.lib
12/09/2019  03:41 PM            45,564 boost_container-vc140-mt.lib
12/09/2019  03:43 PM            29,820 boost_date_time-vc140-mt.lib
12/09/2019  03:39 PM            32,646 boost_exception-vc140-mt.lib
12/09/2019  03:43 PM             8,148 boost_math_c99-vc140-mt.lib
12/09/2019  03:43 PM             8,286 boost_math_c99f-vc140-mt.lib
12/09/2019  03:43 PM             8,286 boost_math_c99l-vc140-mt.lib
12/09/2019  03:43 PM             6,882 boost_math_tr1-vc140-mt.lib
12/09/2019  03:43 PM             7,018 boost_math_tr1f-vc140-mt.lib
12/09/2019  03:43 PM             7,018 boost_math_tr1l-vc140-mt.lib
12/09/2019  03:41 PM         1,186,870 boost_regex-vc140-mt.lib
12/09/2019  03:38 PM             2,246 boost_system-vc140-mt.lib
12/09/2019  03:44 PM            28,802 boost_thread-vc140-mt.lib

**Comment by PhoebeHui** [comment]
@whozcraig, does this still be a problem for you? btw, boost upgrade to 1_72_0 currently.

**Comment by BillyONeal** [comment]
We no longer install boost 1.70, closing this.
