### ISSUE TITLE
warning/error if unsupported compiler used?

### ISSUE THREAD

**Issue by mcgoo** [microsoft/vcpkg#730]
Thanks for vcpkg.

I just spent a couple of hours updating vcpkg and some installed ports. openssl:x64-windows was failing to build for me, which seemed improbable. 

The fix was to update to the current RC of 2017 - I guess I was on Nov 16, but I am not sure.

It would be great if vcpkg complained if the toolchain you are using is older than the version it is tested against.

**Comment by LeonineKing1199** [comment]
What's funny is, I can't get openssl:x64-windows to build with the official msvc 2017.

I keep getting:
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.
    Working Directory: C:/Users/cmazakas/vcpkg/buildtrees/openssl/x64-windows-rel
    See logs for more information:
      C:\Users\cmazakas\vcpkg\buildtrees\openssl\build-x64-windows-rel-out.log
      C:\Users\cmazakas\vcpkg\buildtrees\openssl\build-x64-windows-rel-err.log

Call Stack (most recent call first):
  ports/openssl/portfile.cmake:43 (vcpkg_execute_required_process)
  scripts/ports.cmake:73 (include)


Error: Building package openssl:x64-windows failed with: BUILD_FAILED
Please ensure sure you're using the latest portfiles with `vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl:x64-windows
  Vcpkg version: 0.0.73-053608f47b61a972ea35b26dfb4bd858edd2e709

Additionally, attach any relevant sections from the log files above.
```

Funny part is, 32 bit version builds fine, actually. Seems interesting. I haven't tried building with msvc 2015 yet. If it does work though, let's hear it for ABI compatibility between 2015 and 2017!

**Comment by LilyWangL** [comment]
This issue hasn’t been updated in two year, if it is still an issue, please reopen.
