### ISSUE TITLE
boost_uuid not found

### ISSUE THREAD

**Issue by ooxi** [microsoft/vcpkg#7300]
Wanting to use [boost-uuid](https://www.boost.org/doc/libs/1_70_0/libs/uuid/doc/index.html) I tried installing it using vcpkg

```
vcpkg install boost-uuid
```

and requiring that component using in my `CMakeLists.txt`

```
find_package(Boost REQUIRED COMPONENTS "uuid")
```

However, the CMake configuration fails with the following message

```
-- The C compiler identification is Clang 8.0.0
-- The CXX compiler identification is Clang 8.0.0
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:1832 (message):
  No header defined for uuid; skipping header check
Call Stack (most recent call first):
  /opt/vcpkg/scripts/buildsystems/vcpkg.cmake:230 (_find_package)
  test/CMakeLists.txt:25 (find_package)


CMake Error at /usr/share/cmake/Modules/FindBoost.cmake:2165 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.70.0

  Boost include path: /opt/vcpkg/installed/x64-linux/include

  Could not find the following Boost libraries:

          boost_uuid

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  /opt/vcpkg/scripts/buildsystems/vcpkg.cmake:230 (_find_package)
  test/CMakeLists.txt:25 (find_package)


-- Configuring incomplete, errors occurred!
See also "[...]/build/CMakeFiles/CMakeOutput.log".
```

But the package seems to be installed correctly

```
$> vcpkg list boost-uuid
boost-uuid:x64-linux                               1.70.0           Boost uuid module
```

Installing all of boost using `vcpkg install boost` did not resolve the issue, either.

**Comment by PhoebeHui** [comment]
@ooxi, boost-uuid is header only library, you can't use it by find_package(Boost REQUIRED COMPONENTS "uuid"). Please add following code to your CMakeList.txt instead, and it can find boost-uuid headers correctly.

find_package(Boost REQUIRED)
target_include_directories(Project PUBLIC ${Boost_INCLUDE_DIRS})

Please let me know if it doesn't work for you.

**Comment by ooxi** [comment]
Thanks @PhoebeHui

**Comment by OliverHeilmann** [comment]
> @ooxi, boost-uuid is header only library, you can't use it by find_package(Boost REQUIRED COMPONENTS "uuid"). Please add following code to your CMakeList.txt instead, and it can find boost-uuid headers correctly.
> 
> find_package(Boost REQUIRED) target_include_directories(Project PUBLIC ${Boost_INCLUDE_DIRS})
> 
> Please let me know if it doesn't work for you.

This approach works once Boost has already been installed. Is there a way to specifically install only the UUID aspect of it? Perhaps this is simply just the copying of the header files from the Boost repository...

If this is correct, I'd imagine it would look something like:

```cmake
target_include_directories(Project 
    PUBLIC 
        uuid-header1.hpp
        uuid-header2.hpp
        uuid-headern.hpp
)
```

But I'd imagine there are quite a lot of headers to include so perhaps this isn't the most elegant solution? Thanks in advance!
