### ISSUE TITLE
 [azure-storage-cpp:x64-linux] linking fails in debug

### ISSUE THREAD

**Issue by crusader-mike** [microsoft/vcpkg#7311]
You end up with bunch of missing symbols related to `gcov`. Looks like the reason is [this line](https://github.com/Azure/azure-storage-cpp/blob/b00cc6788dc6f09088fe97a3c3bde86d4d52ccf5/Microsoft.WindowsAzure.Storage/src/CMakeLists.txt#L67)

What is the proper way of addressing this issue? I am not keen on adding `-lgcov` to my compilation options just because somehow my project ended up being dependent on `azure-storage-cpp`.

Should I add a patch to `azure-storage-cpp` port to get rid of `-fprofile-arcs -ftest-coverage`?

Should I add `gcov` dependency somewhere in port definition? (where?)

**Comment by crusader-mike** [comment]
To clarify: I can workaround this, my question is "what is the correct way to address this issue?".

**Comment by vicroms** [comment]
Hi @crusader-mike 

In my opinion it makes sense to remove this kind of instrumentation options from the build.

The right way to do it would be to generate a patch that removes those flags from the CMakeLists.txt and apply said patch in the portfile.

**Comment by crusader-mike** [comment]
@vicroms Thank you. I'll make a PR when I have a chance
