### ISSUE TITLE
openimageio[libraw]:x64-windows

### ISSUE THREAD

**Issue by nelsonrios** [microsoft/vcpkg#7312]
Getting build failures.  Tried 2 different machines with VS 2017 and one with VS 2019:

-- Using source at D:/vcpkg/buildtrees/openimageio/src/ease-2.0.8-1be86a4a75
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: D:/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: D:/vcpkg/buildtrees/openimageio/x64-windows-dbg
    See logs for more information:
      D:\vcpkg\buildtrees\openimageio\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/openimageio/portfile.cmake:64 (vcpkg_install_cmake)
  scripts/ports.cmake:73 (include)

Error: Building package openimageio:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openimageio:x64-windows
  Vcpkg version: 2019.06.26-nohash

**Comment by PhoebeHui** [comment]
@nelsonrios, thanks for reporting this issue! currently it fixed and merged to master, please get latest master and try again.
