### ISSUE TITLE
[New port request] libcerf

### ISSUE THREAD

**Issue by AlexanderTaeschner** [microsoft/vcpkg#7314]
A self-contained numeric library that provides an efficient and accurate implementation of complex error functions, along with Dawson, Faddeeva, and Voigt functions.

Homepage: https://jugit.fz-juelich.de/mlz/libcerf

Used for example by gnuplot.

**Comment by Voskrese** [comment]
tested windows x64 dynamic

[libcerf.zip](https://github.com/microsoft/vcpkg/files/3405292/libcerf.zip)
