### ISSUE TITLE
Error: Building package libtorrent:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by pmahend1** [microsoft/vcpkg#7324]
Package: libtorrent:x86-windows
  Vcpkg version: 2019.06.26-nohash

```
PS C:\workspace\vcpkg> .\vcpkg.exe install libtorrent --triplet x86-windows
The following packages will be built and installed:
    libtorrent[core]:x86-windows
Starting package 1/1: libtorrent:x86-windows
Building package libtorrent[core]:x86-windows...
-- Using cached C:/workspace/vcpkg/downloads/arvidn-libtorrent-76c2794923c4c101ff715be11d794f7fefc6c524.tar.gz
-- Using source at C:/workspace/vcpkg/buildtrees/libtorrent/src/7fefc6c524-4dcf88171d
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/workspace/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: C:/workspace/vcpkg/buildtrees/libtorrent/x86-windows-dbg
    See logs for more information:
      C:\workspace\vcpkg\buildtrees\libtorrent\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/libtorrent/portfile.cmake:24 (vcpkg_install_cmake)
  scripts/ports.cmake:73 (include)


Error: Building package libtorrent:x86-windows failed with: BUILD_FAILED
```

**Comment by pmahend1** [comment]
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3408263/install-x86-windows-dbg-out.log)

**Comment by Voskrese** [comment]
`[1/157] C:\PROGRA~2\MICROS~1\2019\Professional\VC\Tools\MSVC\14.21.27702\bin\Hostx64\x86\cl.exe   /TP -DBOOST_ALL_NO_LIB -DBOOST_ASIO_ENABLE_CANCELIO -DBOOST_ASIO_HAS_STD_CHRONO -DBOOST_EXCEPTION_DISABLE -DTORRENT_BUILDING_LIBRARY -DTORRENT_BUILDING_SHARED -DTORRENT_NO_DEPRECATE -DTORRENT_USE_ASSERTS -DTORRENT_USE_LIBCRYPTO -DTORRENT_USE_OPENSSL -DWIN32_LEAN_AND_MEAN -D_CRT_SECURE_NO_DEPRECATE -D_FILE_OFFSET_BITS=64 -D_SCL_SECURE_NO_DEPRECATE -D_WIN32_WINNT=0x0600 -Dtorrent_rasterbar_EXPORTS -IC:\workspace\vcpkg\buildtrees\libtorrent\src\7fefc6c524-4dcf88171d\include -IC:\workspace\vcpkg\buildtrees\libtorrent\src\7fefc6c524-4dcf88171d\ed25519\src -IC:\workspace\vcpkg\installed\x86-windows\include /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1    /W4 /wd4251 /wd4275 /wd4373 /wd4268 /wd4503 /Zc:wchar_t /Zc:forScope /MP /bigobj /EHsc -std:c++14 /showIncludes /FoCMakeFiles\torrent-rasterbar.dir\src\announce_entry.cpp.obj /FdCMakeFiles\torrent-rasterbar.dir\ /FS -c C:\workspace\vcpkg\buildtrees\libtorrent\src\7fefc6c524-4dcf88171d\src\announce_entry.cpp`

FAILED: `CMakeFiles/torrent-rasterbar.dir/src/announce_entry.cpp.obj `

can the reason in this

`-D_FILE_OFFSET_BITS=64`

`vcpkg\installed\x86-windows`

> _FILE_OFFSET_BITS=64 to switch to 64-bit types on 32-bit systems

**Comment by pmahend1** [comment]
@Voskrese are you asking me? I am on 64 bit machine.
libtorrent:x86-windows-static installs and builds fine.

**Comment by pmahend1** [comment]
This was fixed in later port updates/rebuilding vcpkg.
