### ISSUE TITLE
Running .\bootstrap-vcpkg.bat does not generate the vcpkg.exe file

### ISSUE THREAD

**Issue by hongqimei** [microsoft/vcpkg#7326]
PS D:\GIT\vcpkg> .\bootstrap-vcpkg.bat
PS D:\GIT\vcpkg>

**Comment by wangli28** [comment]
Hi @ukreal, what information did you get when you ran `.\bootstrap-vcpkg.bat` on VCPKG?

**Comment by ukreal** [comment]
@wangli28 
just
PS D:\GIT\vcpkg> .\bootstrap-vcpkg.bat
PS D:\GIT\vcpkg>

**Comment by ukreal** [comment]
Nothing else after running @wangli28

**Comment by wangli28** [comment]
@ukreal 
Did you creat vcpkg according to this document?
https://github.com/microsoft/vcpkg#quick-start

**Comment by RailRunner166** [comment]
I had the same problem, but it ended up being a problem with my antivirus (which I never originally installed so idk how it even got there) quarantining it, so if in doubt, just check your antivirus' quarantine

**Comment by PhoebeHui** [comment]
@ukreal, does this issue persist for you? have you try RailRunner166's methond?

**Comment by PhoebeHui** [comment]
@hongqimei, you can also reference https://github.com/microsoft/vcpkg/issues/9704#issuecomment-576414004 if you still have this issue.
