### ISSUE TITLE
[New Port Request] Imgui-sfml

### ISSUE THREAD

**Issue by Metsuro** [microsoft/vcpkg#7333]
With the inclusion of both imgui and sfml I was hoping we could get this library included.

https://github.com/eliasdaler/imgui-sfml

**Comment by NancyLi1013** [comment]
Hi @Metsuro , thanks for posting this request. Please see details in #7429.

**Comment by NancyLi1013** [comment]
This port has been added to vcpkg. Please try to update vcpkg and use this port.
