### ISSUE TITLE
vcpkg_apply_patches used unsafely in conditionals

### ISSUE THREAD

**Issue by Rastaban** [microsoft/vcpkg#7335]
If patches are conditionally applied to the SOURCE_PATH they they will still be there when unrelated triplets are built.  Ports that conditionally applies patches using vcpkg_apply_patches need to guard itself by either taking into account the triplet in the source path or by deleting the source to force it to be re-extracted clean on every build.

Doing a quick scan of the ports directory the following ports may have this issue:

+ ccfits
+ freexl
+ itpp
+ mpg123
+ qwt
+ sdl1

all other uses of vcpkg_apply_patches I found was either not conditional or no applied to the source path.

This issues does not affect the other vcpkg_* functions with a PATCHES parameter because they factor in the patches to create the hash used in the directory name.  Avoiding issues like this are actually one of the reasons why the PATCHES parameters were added to those functions.

**Comment by Voskrese** [comment]
you can add an option to delete the SOURCE\src folder
in case of successful compilation 

like here, do not delete folders after compilation

`	SKIP_CLEAN`

```
vcpkg_install_msbuild(
    SOURCE_PATH ${SOURCE_PATH}
    PROJECT_SUBPATH "libao.vcxproj"
	SKIP_CLEAN
	LICENSE_SUBPATH COPYING
	USE_VCPKG_INTEGRATION
)
```
