### ISSUE TITLE
[new port request] libopus

### ISSUE THREAD

**Issue by brucechase** [microsoft/vcpkg#7337]
like to see libopus added to the list of new port requests

**Comment by Rastaban** [comment]
We have a library named `opus`, is this possibly the one you are looking for?

From the port control file:
```
Source: opus
Version: 1.3.1
Homepage: https://github.com/xiph/opus
Description: Totally open, royalty-free, highly versatile audio codec
```

**Comment by NancyLi1013** [comment]
Hi @brucechase, thanks for posting this request. Please feel free to reopen it and help provide the library homepage link if this is a new port that is not in vcpkg list.
