### ISSUE TITLE
vcpkg doesn't warn that wrong compiler is used x86 while x64 is needed

### ISSUE THREAD

**Issue by stoperro** [Microsoft/vcpkg#734]
I tried to compile boost for x64. It failed with:
> C:\vcpkg\buildtrees\boost\x64-windows-dbg\boost\bin.v2\libs\atomic\build\8357493a7f6e005580c195c9283bcb08\lockpool.obj : fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'x64'

Turns out in command line cl.exe was for x86 architecture. When I used:
> C:\vcpkg>"c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
> C:\vcpkg>cl
> Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24210 for x64

Compilation finished just fine.

One can say now that vcpkg was misused, but new user will have a hard time figuring it out. vcpkg could check if 32 bit cl.exe is used when `--triplet x64-windows` was selected and print what should be done in such situation. Alternatively vcpkg could on its own (not with current environment) search for right version of visual c++ compiler.

**Comment by ras0219-msft** [comment]
It's definitely our goal to locate the correct compiler for the triplet chosen. Thanks for reporting this, I'll try to repro it locally and get it fixed.

**Comment by stoperro** [comment]
If I remember correctly, when I used clean prompt, compilation tasks (called by vcpkg, `b2.exe` most likely) were not finding `cl.exe` at all - hence I called `vcvarsall.bat` (and I don't do that by default cause it's always hard to find on disk :) ) before calling `vcpkg install`, but forgot about selecting arch in vcvarsall.

**Comment by ras0219-msft** [comment]
Ok, **that's** definitely a bug.

While fixing the Boost build for VS 2017, I disabled Boost's automatic compiler detection in favor of our own. By design, we internally locate `vcvarsall.bat` and call it with the right architecture parameter. If that's not working, that's the real Vcpkg bug that we need to fix.

Could you give us a solid repro description? Make sure you're using the latest version of vcpkg (make sure to re-bootstrap as well!), then try installing a package from a clean command prompt. When the install fails, please post the failure log here.

Also, what versions of VS do you have installed (I see 2015 -- do you also have 2017)?

**Comment by stoperro** [comment]
On the PC that I've reported the issue, I have newest 2015 indeed, and previously had installed also 2017 RC - but it's removed now. From past experiences with RCs I won't be shocked that there are some leftovers from that RC that could caused the issue, although I see that VS installers are working better now :)

I will try to reproduce it again, but today our enterprise antivirus started quarantining jam0.exe when bootstrapping boost build... so now I'm not getting to the point when issue was visible. I've reported false positive to them, I hope they will fix it soon... Note: this didn't happen before and I assume it didn't cause the issue, as now it doesn't get to libraries compilation phase and previously it did.

I have other private PC that has newest 2017 and will try to reproduce it there later today.

Regarding: "(make sure to re-bootstrap as well!),"
I've been only using "./vcpkg update" according to:
"Please ensure sure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost:x64-windows
  Vcpkg version: 0.0.75-b03b578ffc27a9f0d4d9c7a8edc8edeea487dce3"
(note this was printed now, likely exact same version was used when I encountered the issue, but I'm not 100% sure)

Won't "./vcpkg update" do this re-bootstrapping? Is it only for updating packages, and not rebuilding vcpkg when needed? If so, I didn't get it from description - I thought it magically makes my vcpkg fully up to date with all newest fixes and features. Also, how to do re-bootstrapping if not this way? You mean remove it and re-download?

**Comment by stoperro** [comment]
Ok, I get now the re-bootstrapping, when I did "./vcpkg update" today and it instructed me what to do (powershell stuff). On my PC with only VS2017 RTM the Boost installation works, although I still have issue as mentioned in #683.

Still don't know if I can reproduce the issue on PC with VS2015.

**Comment by stoperro** [comment]
Ok, finally managed to reproduce it, maybe not exactly as it fails
```
C:\vcpkg3>vcpkg.exe update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

C:\vcpkg3>git pull
Already up-to-date.

C:\vcpkg3>cl
'cl' is not recognized as an internal or external command,
operable program or batch file.

C:\vcpkg3>vcpkg.exe install boost:x64-windows
...
-- Performing post-build validation
There should be no empty directories in C:/vcpkg3/packages/boost_x64-windows
The following empty directories were found:
...
Error: Building package boost:x64-windows failed with: POST_BUILD_CHECKS_FAILED
Please ensure sure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost:x64-windows
  Vcpkg version: 0.0.76-5cc80c1e974a2a52f863b98cc387a2285803521b
```

Looking at logs, now bootstrapping of Boost Build system fails as it doesn't see cl.exe in command line (in bootstrap-err.log):
```
'cl' is not recognized as an internal or external command,
operable program or batch file.
```
So as if this "internally calling of vcvarsall.bat didn't work maybe?

[vcpkg.zip](https://github.com/Microsoft/vcpkg/files/848498/vcpkg.zip)

**Comment by stoperro** [comment]
With newest version bootstrapping succeeded, but then compilation fails with similar error, from C:\vcpkg\buildtrees\boost\build-x64-windows-static-rel-out-0.log:
`
notice: Loading user-config configuration file 'user-config.jam' from 'C:/vcpkg/buildtrees/boost/x64-windows-static-rel'.
notice: [msvc-cfg] msvc-14.0 detected, command: 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.exe'
notice: will use 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.exe' 'cl.exe' for msvc, condition <toolset>msvc-14.0
notice: [msvc-cfg] condition: '<toolset>msvc-14.0/<architecture>/<address-model>', setup: ''
`
...
`
notice: [msvc-cfg] condition: '<toolset>msvc-14.0/<architecture>arm/<address-model>32', setup: ''
warning: toolset msvc initialization:
warning: can not find user-provided command 'cl.exe'
warning: initialized from C:/vcpkg/buildtrees/boost/x64-windows-static-rel\user-config.jam:7
notice: will use 'cl.exe' for msvc, condition <toolset>msvc-14.1
notice: [msvc-cfg] condition: '<toolset>msvc-14.1/<architecture>/<address-model>', setup: ''
`
...
`
notice: Searching '.' for project-config configuration file 'project-config.jam'.
notice: Loading project-config configuration file 'project-config.jam' from '.'.
`
...
`
compile-c-c++ C:\vcpkg\buildtrees\boost\x64-windows-static-rel\boost\architecture\ab56ecc12c4e2df376c90f2b25a756ee\32.obj
'cl' is not recognized as an internal or external command,
operable program or batch file.
`

**Comment by ras0219-msft** [comment]
Thanks for pinging this back up.

It's very strange that all the cmake-based libraries are working correctly but boost is not -- you were successfully able to build zlib, bzip2, etc.

Here are a few commands that should give us more insight into the problem:

`vcpkg --debug env` will launch cmd inside the same environment we use to build packages (environment variables scrubbed, path set up, etc). Inside that environment, could you run `where.exe cl`?

`.\scripts\findAnyMSBuildWithCppPlatformToolset.ps1 -verbose` will print a bunch of diagnostics about how we are specifically looking for a C++ toolset to use.

**Comment by stoperro** [comment]
Thank you for the help with debugging.

So this is the default (for x86 it seems).
```
C:\vcpkg>cl --version
'cl' is not recognized as an internal or external command, operable program or batch file.
C:\vcpkg>cl
'cl' is not recognized as an internal or external command, operable program or batch file.
C:\vcpkg>vcpkg.exe --debug env
[DEBUG] _wspawnlpe(cmd.exe /c ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86  2>&1 && cmd")
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\vcpkg>cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24210 for x86
C:\vcpkg>where cl
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.exe
```

Now this is for x64:
```
C:\vcpkg>vcpkg.exe --debug env --triplet x64-windows-static
[DEBUG] _wspawnlpe(cmd.exe /c ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcva
rsall.bat" x64  2>&1 && cmd")
The specified configuration type is missing.  The tools for the
configuration might not be installed.
...
C:\vcpkg>cl
'cl' is not recognized as an internal or external command,
operable program or batch file.
```

This error is returned by vcvarsall.bat. Same if I call it directly.

I've checked it and x64 means that host is x64(!) and target is x64 bit. I remember reading on VC blog a while ago a longer explanation why there is no x64 hosted C++ compiler (in short: internal pointers size increase, so worse performance). Has it changed and now we have x64 hosted VC compiler? (this would be good for precompiled headers :) ) Now I see that VS2017 on my other PC has in fact 64 bit binaries.
Before if there was no x64 hosted compiler then call should have been changed to "x86_amd64", so that 32 bit cl.exe binary compiles 64 bit target.

If it turns out that I've lived in cave for the past few years and in fact we already have VC++ compiler 64 bit binary for VS2015 and simply my VS installation is bad (not unlikely, also I see this indicates that it should have it: https://msdn.microsoft.com/en-us/library/x4d2c09s.aspx), could vcpkg check it and warn user that he has no required tools to compile given target? Or at least check if cl.exe is available and don't even try to go further if not. Unfortunately vcvarsall in VS2015 doesn't seem to return error codes.

**Comment by stoperro** [comment]
Similar issue when trying arm-uwp:
```
F:\vcpkg>vcpkg.exe --debug env --triplet arm-uwp
[DEBUG] _wspawnlpe(cmd.exe /c ""C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" arm  2>&1 && cmd")
[ERROR:vcvarsall.bat] Invalid argument found : arm
```
I've tried fixing it so for arm vcpkg will use "amd64_arm uwp":
[vcvarsall_architecture_selection.zip](https://github.com/Microsoft/vcpkg/files/959900/vcvarsall_architecture_selection.zip)

But later boost compilation failed with some other errors:
`C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\ucrt\corecrt.h(226): fatal error C1189: #error:  Compiling Desktop applications for the ARM platform is not supported.`

Maybe it's more complicated: https://blogs.msdn.microsoft.com/vcblog/2014/07/18/using-boost-libraries-in-windows-store-and-phone-applications/

**Comment by stoperro** [comment]
On newest versions of vcpkg the issue seems fixed :)
