### ISSUE TITLE
[New Port Request] KlayGE

### ISSUE THREAD

**Issue by myd7349** [microsoft/vcpkg#7346]
Library name: KlayGE

Library description: KlayGE is a cross-platform open source game engine with plugin-based architecture. 

Source repository URL: https://github.com/gongminmin/KlayGE

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
