### ISSUE TITLE
Specific Version Librarys

### ISSUE THREAD

**Issue by Clinkz24** [microsoft/vcpkg#7349]
Is there a plan to support installing a specific version library?
I think if this problem is not solved for a long time, then VCPKG cannot be an enterprise solution.
tks

**Comment by Voskrese** [comment]
no
do not update specific ports or use the option
`--overlay-ports=<path>`

**Comment by cenit** [comment]
I agree with Voskrese. In the enterprise the midterm solution (and also very elastic solution!) is to adopt an overlay to the port folder

**Comment by cbezault** [comment]
Like @Voskrese and @cenit have stated the current way to pin to specific libraries is to grab the version of a library from the vcpkg git history and saving it to a port overlay folder. @vicroms is working #7377 which will let you easily find all the versions available in the vcpkg git history for a port.

Unfortunately if we never supported a version of a library you will not be able get it from us. There also might be issues in the older port files which we will not assist in resolving.

In many cases, however, you could just use the newest port and change the version downloaded to the one you desire. There will of course be situations where that won't be possible but again, we will not offer support, as it is a custom setup.
