### ISSUE TITLE
[<port name>] build failure

### ISSUE THREAD

**Issue by z-ninja** [microsoft/vcpkg#7351]
**Host Environment**
- OS: WIndows 7
- Compiler: visual studio 2015

**To Reproduce**
vcpkg.exe install boost-beast

**Failure logs** 
The following packages will be built and installed:
    boost-beast[core]:x86-windows
Starting package 1/1: boost-beast:x86-windows
Building package boost-beast[core]:x86-windows...
-- Using cached C:/vcpkg-master/downloads/boostorg-beast-boost-1.70.0.tar.gz
-- Extracting source C:/vcpkg-master/downloads/boostorg-beast-boost-1.70.0.tar.g
z
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:58 (message):
    Command failed: C:/vcpkg-master/downloads/tools/cmake-3.14.0-windows/cmake-3
.14.0-win32-x86/bin/cmake.exe -E tar xjf C:/vcpkg-master/downloads/boostorg-beas
t-boost-1.70.0.tar.gz
    Working Directory: C:/vcpkg-master/buildtrees/boost-beast/src/TEMP
    Error code: 1
    See logs for more information:
      C:\vcpkg-master\buildtrees\boost-beast\extract-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive.cmake:43 (vcpkg_execute_required_pr
ocess)
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:98 (vcpkg_extract_source_a
rchive)
  scripts/cmake/vcpkg_from_github.cmake:114 (vcpkg_extract_source_archive_ex)
  ports/boost-beast/portfile.cmake:5 (vcpkg_from_github)
  scripts/ports.cmake:74 (include)

Error: Building package boost-beast:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-beast:x86-windows
  Vcpkg version: 2019.07.18-nohash

Additionally, attach any relevant sections from the log files above.

log:
cmake -E tar: warning: unknown warning
CMake Error: Problem with archive_write_finish_entry(): File size could not be restored
CMake Error: Problem extracting tar: C:/vcpkg-master/downloads/boostorg-beast-boost-1.70.0.tar.gz

**Additional context**
I also tried to build boost previously, but got BUILD_FAILED after 1xx packages build successfully. Any package after boost-beast including boost-beast is failing.

**Comment by cenit** [comment]
Same as #7352
Somehow the os is preventing you writing inside that folder. Either permissions or disk full?
