### ISSUE TITLE
[sdl2_mixer] Remove load-time requirement on `mpg123.dll` etc.

### ISSUE THREAD

**Issue by lethal-guitar** [microsoft/vcpkg#7356]
The `SDL2_mixer.dll` provided by vcpkg should be loadable without requiring optional transitive dependencies (such as `mpg123.dll`) to be present. According to SDL2_mixer's [home page](https://www.libsdl.org/projects/SDL_mixer):

> FLAC, MikMod, Ogg Vorbis and MP3 loading libraries are dynamically loaded, so if you don't need to load those formats, you *don't need to include those shared libraries*

(Emphasis mine). When using a pre-built binary from the SDL2_mixer page, this is indeed the case: An executable depending on `SDL2_mixer.dll` can be started without the other DLLs being present.

But this is not the case when using vcpkg. This caught me by surprise when switching my project from manual dependency management to using vcpkg, and I ended up with a user not being
able to run my application anymore, because my release process only includes `SDL2_mixer.dll` with the Application I'm shipping (I'm not using any of the functionality provided by those other dependencies).

See [my AppVeyor build](https://ci.appveyor.com/api/buildjobs/pctvd0w7dywi53d7/artifacts/rigel_build.zip) for reference, it contains the `SDL2_mixer.dll` from vcpkg which has load-time dependencies.

**Comment by JackBoosY** [comment]
@lethal-guitar 
I didn't find the `load_library` function in the sdl2-mixer source. If I only build sdl2-mixer[core], it don't need to rely on several other libraries (see the dependency library through the tools Dependency Walker).

So I guess the sdl2-mixer official so-called "dynamic loading" refers to loading different libraries according to different features?

**Comment by lethal-guitar** [comment]
@JackBoosY thanks for looking into this! The dynamic loading happens via [`SDL_LoadFunction`](https://wiki.libsdl.org/SDL_LoadFunction), which is part of SDL itself. 

You can find an example here: https://hg.libsdl.org/SDL_mixer/file/c52db177a8bd/music_mpg123.c#l63

**Comment by JackBoosY** [comment]
After delving into the code, I found that we don't need to add these dependencies to build the sdl2-mixer.

**Comment by JackBoosY** [comment]
@lethal-guitar I've fixed this issue. Please update vcpkg and rebuild sdl2_mixer.

Thanks.
