### ISSUE TITLE
Hello hello BUILD_FAILED

### ISSUE THREAD

**Issue by duliani** [microsoft/vcpkg#7357]
I am trying to build package from github with vcpkg

**Comment by duliani** [comment]
[RINGMesh-master-Win64-vs2015 (3).zip](https://github.com/microsoft/vcpkg/files/3415454/RINGMesh-master-Win64-vs2015.3.zip)

**Comment by wangli28** [comment]
Hi @duliani, thanks for posting issue! Can you provide more information about this issue? You can creat vcpkg according to this document.
https://github.com/microsoft/vcpkg#quick-start

**Comment by cbezault** [comment]
Hi @duliani, the information provided is greatly insufficient, it's unclear what package you're trying to build or where the error in the build is.

Please re-open a new issue with information concerning steps to reproduce the issue and at the very least the logs of the build and the port you were attempting to build which failed.

Thanks
