### ISSUE TITLE
Could you please kindly include tensorflow, keras?

### ISSUE THREAD

**Issue by jesukiranspurgen** [microsoft/vcpkg#7365]
Would it please be possible to install tensorflow, keras through vcpkg?

**Comment by NancyLi1013** [comment]
Hi @jesukiranspurgen 

`tensorflow `has been added to vcpkg, please try to update vcpkg and use it. As for `keras ` still needs to be added.

If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
