### ISSUE TITLE
How do I install vcpkg?

### ISSUE THREAD

**Issue by Const-me** [microsoft/vcpkg#7367]
I’ve followed installation guide very carefully, bootstrap-vcpkg.bat printed many pages of text at the end it printed “Building vcpkg.exe... done.”
Yet, when I type `vcpkg search` at the command prompt, I’m, getting error:
> 'vcpkg' is not recognized as an internal or external command, operable program or batch file.

Do I need to keep the source code repository to use vcpkg, or did the installation script copied it somewhere so it can be safely removed? If later, where? Different Microsoft’s  blog posts say different locations, `c:\vcpkg\installed` or `C:\Dev\vcpkg` but I have neither of them created, does it mean the installer script has failed?

How do I integrate vcpkg in path?

I don’t like keeping executable files writeable by non-elevated processes. Can I move vcpkg.exe to program files and update NTFS permissions accordingly? Will it still work? How does it search for data files i.e. libraries/repository, does it keep data under %userprofile% according to MS recommendations?

Do you have an MSI that installs the software? Or at least a complete installation guide which works and compatible with the current version of vcpkg?

Thanks in advance.

**Comment by vicroms** [comment]
Hi @Const-me

Thanks for giving **vcpkg** a try! 

After running `bootstrap-vcpkg.bat` the **vcpkg** executable is built and dropped in the root of the vcpkg folder.  

The executable is not added to `PATH` nor are any files copied to a different location, there is no actual "install" process, the bootstraping process just builds `vcpkg.exe`.

Everything you need to use **vcpkg** is inside the folder in which you cloned it, 
if you ever want to uninstall vcpkg just delete the project folder.

To use **vcpkg** from the command line, run "./vcpkg <any command>" from the folder containing `vcpkg.exe`.

You can add the folder containing `vcpkg.exe` to your PATH variable manually, and then you will be able to do `vcpkg <any command>`.

> Do I need to keep the source code repository to use vcpkg?

Yes, the project folder contains not only vcpkg's source code, but also: 

* a number of CMake scripts needed to run vcpkg in `<vcpkg>/scripts` and `<vcpkg>/triplets`,
* library ports, the recipes to build each library, in `<vcpkg>/ports`,
* the libraries you install `<vcpkg>/installed`, 
* downloaded libraries' source code `<vcpkg>/buildtrees`, 
* and downloaded utilites in `<vcpkg>/downloads`.

You can think of this folder as an environment that will be maintained by vcpkg, all of vcpkg's operations are performed within these directories (even if you invoke it from a different directory in the command line).

When you want to update vcpkg just run these commands:

```
git pull origin master
./bootstrap-vcpkg.bat
```

This will update your library ports **[1]** and get the latest vcpkg source code, it is a good practice to bootstrap (rebuild) vcpkg each time you update to new sources.

Installing libraries usually entails a great number of file generating, copying, moving and deleting operations, so I don't recommend cloning vcpkg in a restricted location.

**[1]** `git pull` updates the port recipes, but does not actually modify your installed libraries.
To update your installed libraries you need to run:
`vcpkg update`
`vcpkg upgrade --no-dry-run`

**Comment by thatrobotguy** [comment]
I am running into the same issue.

I run `.\bootstrap-vcpkg.bat` in powershell and I do **NOT** see a `vcpkg.exe` file under the root directory where I cloned the repo.

I saw that the script printed out this location:
```
vcpkg.vcxproj -> C:\Users\Andrew Schueler\vcpkg\toolsrc\msbuild.x86.release\vcpkg.exe
```
But that also does not contain the executable. In fact, that location in the directory structure does not exist.

I checked git for more branches and master appears to the the only valid branch. What should I do?

**Comment by Daniw2009872** [comment]
How do you run the .bat file? I tried just clicking it and nothing appeared. How did you get the long strands of text you said?

**Comment by Daniw2009872** [comment]
@Const-me I tried running the file as you did but I keep getting an error message. Can you walk me through it?

**Comment by RodneyYourAreGoodAtThis** [comment]
I run ./bootstrap-vcpkg.bat but it keeps telling me that it cannot find VS code; VS code is clearly installed and i have been struggling with it as one does. Please help.

**Comment by narasimhan11102** [comment]
![image](https://user-images.githubusercontent.com/76741184/103304065-a197dc80-4a2d-11eb-800c-283ba0cf6fe8.png)
Hi @Const-me
When I run the bootstrap command I get this error but I have already installed VS code. Can you please help me in resolving this issue?

**Comment by vicroms** [comment]
@narasimhan11102 

You need to install the Visual Studio C++ compiler. 
Visual Studio and Visual Studio Code are different products.

**Comment by punderiino** [comment]
Storyyy

**Comment by Aradon267** [comment]
> You can add the folder containing `vcpkg.exe` to your PATH variable manually, and then you will be able to do `vcpkg <any command>`.

I added the 'vcpkg.exe'(with the full path) file to my PATH variable but I still can't use it everywhere and the libraries that I downloaded at the regular folder can't be used anywhere..
That's what I've put in the system and user variables:
![image](https://user-images.githubusercontent.com/86805354/147868363-e1f8ba23-b39e-4891-82a5-810768d37c3a.png)
When on a different folder and using a command I'm getting:
'vcpkg' is not recognized as an internal or external command,
operable program or batch file.
When using `#include`(the project is outside of the vcpkg folder) with libraries I've downloaded I'm getting:
![image](https://user-images.githubusercontent.com/86805354/147868404-37758433-873e-4556-ab6b-961168392615.png)

**Comment by achimismaili** [comment]
I have the same problem in VS Pro 2022, it seems that I need to convince our help desk that it must be updated to >= 17.3, then I can use nuget package manager instead of vcpkg ...
(according to https://devblogs.microsoft.com/cppblog/announcing-nuget-packagereference-support-for-c-cli-msbuild-projects-targeting-net-core/)

**Comment by dg0yt** [comment]
> I have the same problem [...]

@achimismaili Really? There have been multiple sub-issues here, but AFAIU the original issue is resolved by bootstrapping now downloading binaries. You should probbably open another issue, with precise information.

**Comment by dg0yt** [comment]
> I added the 'vcpkg.exe'(with the full path) file to my PATH variable but I still can't use it everywhere and the libraries that I downloaded at the regular folder can't be used anywhere..
> That's what I've put in the system and user variables:

@Aradon267 I assume you already found it, but FTR the `PATH` environment variable lists directories (e.g. `C:\dev\vcpkg`), not full paths with filename.
