### ISSUE TITLE
Add graphviz 

### ISSUE THREAD

**Issue by traversaro** [microsoft/vcpkg#737]
It would be great to have a port of the graphviz library ( https://github.com/ellson/graphviz ).

Debian package : https://packages.debian.org/source/sid/graphviz .
Homebrew formula : https://github.com/Homebrew/homebrew-core/blob/master/Formula/graphviz.rb .
Repology page : https://repology.org/metapackage/graphviz/versions .

**Comment by luzpaz** [comment]
Graphviz has moved from github to gitlab: https://gitlab.com/graphviz/graphviz

**Comment by luzpaz** [comment]
FYI, here is the scoop formula: https://github.com/lukesampson/scoop/blob/master/bucket/graphviz.json

**Comment by Voskrese** [comment]
ver 2.41
https://github.com/Voskrese/vcpkg/tree/master/ports/graphviz

test windows x64 dynamic

**Comment by NancyLi1013** [comment]
I noticed that this port needs to depend on RxSpencer .
 https://github.com/ellson/MOTHBALLED-graphviz/blob/master/CMakeLists.txt#L89

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
