### ISSUE TITLE
[New Port Request] xtensor-io

### ISSUE THREAD

**Issue by zhihaoy** [microsoft/vcpkg#7371]
Library name: xtensor-io

Library description: 
xtensor plugin to read and write images, audio files, numpy (compressed) npz and HDF5

Source repository URL: https://github.com/QuantStack/xtensor-io

Project homepage (if different from the source repository): https://xtensor-io.readthedocs.io/en/latest/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): We at minimal need read npz files.

**Comment by NancyLi1013** [comment]
Hi @zhihaoy, thanks for posting this request. This port has been added to vcpkg. Please try to update and use it.

**Comment by zhihaoy** [comment]
Thanks!
