### ISSUE TITLE
How do I set CMake variable globally (for all ports)?

### ISSUE THREAD

**Issue by crusader-mike** [microsoft/vcpkg#7372]
Is there a way to set CMake variable (e.g. `set(CMAKE_INTERPROCEDURAL_OPTIMIZATION TRUE)`) for all ports at once?

**Comment by jepessen** [comment]
You can try to put it inside the triplet file that you want to use.

**Comment by crusader-mike** [comment]
@jepessen Tried it, no effect. Probably because `vcpkg install` results in [this](https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_execute_build_process.cmake#L41) `execute_process` and apparently it doesn't inherit current CMake variables?

**Comment by cbezault** [comment]
There is currently no way to set a CMake variable globally for all builds.
You can define a variable inside a triplet and it will be available in all portfiles but each portfile must call `vcpkg_configure_cmake` to set the variables that will be available to the build besides a whitelist that we ass along.

One possible implementation for this would be to read a `VCPKG_PASSTHROUGH_CMAKE_VARIABLES` variable in `vcpkg_configure_cmake` which can then pass along all variables listed in `VCPKG_PASSTHROUGH_CMAKE_VARIABLES`. Then you could define `VCPKG_PASSTHROUGH_CMAKE_VARIABLES` in your triplet.

**Comment by crusader-mike** [comment]
@cbezault I've realized that while vcpkg uses CMake to drive package build and install -- each individual port can (and often does) run it's own build system. Therefore "passing CMake flag to every build" simply doesn't make sense in general. Correct solution would be to create a global **feature** (similar to `VCPKG_LIBRARY_LINKAGE`) which gets set in triplet file and require ports to support it.

Do you think it is relatively easy to introduce things like:
`VCPKG_LIBRARY_LTO[_<CONFIG>]` -- turns on/off LTO
`VCPKG_LIBRARY_SYM_GC[_<CONFIG>]` -- turn on/off unused symbol cleanup (`-ffunction-sections -fdata-sections -Wl,--gc-sections` in case of gcc)

Should I even attempt this effort? This will likely result in updates to many ports...
