### ISSUE TITLE
Error: Building package boost-regex:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by ZoeZhang91** [microsoft/vcpkg#7378]
The following packages will be built and installed:
    boost-regex[core]:x64-windows
Starting package 1/1: boost-regex:x64-windows
Building package boost-regex[core]:x64-windows...
-- Using cached D:/vcpkg/downloads/boostorg-regex-boost-1.70.0.tar.gz
-- Using source at D:/vcpkg/buildtrees/boost-regex/src/ost-1.70.0-e31fa0647d
CMake Error at ports/boost-regex/portfile.cmake:19 (include):
  include could not find load file:

    D:/vcpkg/installed/x64-windows/share/boost-build/boost-modular-build.cmake
Call Stack (most recent call first):
  scripts/ports.cmake:74 (include)

Error: Building package boost-regex:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-regex:x64-windows
  Vcpkg version: 2019.07.18-nohash

Additionally, attach any relevant sections from the log files above

win10, vs2017, cmake 3.14.
I've checked the file boost-modular-build.cmake, actually it does not exist.
And I've followed several of the issue suggestions, like git pull vcpkg, update boost to the newest version,  filepath without whitespace, modify vs2017 and so on, but the same error still occurs···

Thank you for any help.

**Comment by PhoebeHui** [comment]
@ZoeZhang91, could you remove boost-build:x64-windows and reinstall boost-regex[core]:x64-windows again?

**Comment by ZoeZhang91** [comment]
> @ZoeZhang91, could you remove boost-build:x64-windows and reinstall boost-regex[core]:x64-windows again?

thank you for your reply.
yes，i‘ve tried these before，but still got the error.

and i successfully built the total boost  just now by the following solutions：
vcpkg remove boost-modular-build-helper:x64-windows --recurse
vcpkg install boost-modular-build-helper:x64-windows   --recurse

**Comment by PhoebeHui** [comment]
@ZoeZhang91, this should be regression issue involved recently, thanks for reporting this issue!

**Comment by jadsonleno123** [comment]
estou com o mesmo problema, ja tentei de tudo principalmente os posts anteriores que vcs falaram sobre solução e nada...


-- Cleaning sources at C:/vcpkg/buildtrees/boost-regex/src/ost-1.74.0-ccd5cfd86e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/boostorg-regex-boost-1.74.0.tar.gz
-- Using source at C:/vcpkg/buildtrees/boost-regex/src/ost-1.74.0-ccd5cfd86e.clean
-- Including C:/vcpkg/ports/boost-regex/b2-options.cmake
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
    Command failed: C:/vcpkg/installed/x64-windows/tools/boost-build/b2.exe --stagedir=C:/vcpkg/buildtrees/boost-regex/x64-windows-rel/stage --build-dir=C:/vcpkg/buildtrees/boost-regex/x64-windows-rel --user-config=C:/vcpkg/buildtrees/boost-regex/x64-windows-rel/user-config.jam -j4 --debug-configuration --debug-building --debug-generators --disable-icu --ignore-site-config --hash -q -sZLIB_INCLUDE=C:/vcpkg/installed/x64-windows/include -sBZIP2_INCLUDE=C:/vcpkg/installed/x64-windows/include -sLZMA_INCLUDE=C:/vcpkg/installed/x64-windows/include -sZSTD_INCLUDE=C:/vcpkg/installed/x64-windows/include threading=multi threadapi=win32 runtime-link=shared link=shared address-model=64 architecture=x86 -sZLIB_BINARY=zlib -sZLIB_LIBPATH=C:/vcpkg/installed/x64-windows/lib -sBZIP2_BINARY=bz2 -sBZIP2_LIBPATH=C:/vcpkg/installed/x64-windows/lib -sLZMA_BINARY=lzma -sLZMA_LIBPATH=C:/vcpkg/installed/x64-windows/lib -sZSTD_BINARY=zstd -sZSTD_LIBPATH=C:/vcpkg/installed/x64-windows/lib variant=release debug-symbols=on
    Working Directory: C:/vcpkg/buildtrees/boost-regex/src/ost-1.74.0-ccd5cfd86e.clean/build
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\boost-regex\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:346 (vcpkg_execute_required_process)
  ports/boost-regex/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:136 (include)


Error: Building package boost-regex:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-regex:x64-windows
  Vcpkg version: 2020.11.12-nohash

**Comment by PhoebeHui** [comment]
@jadsonleno123, please report a new issue with failures logs instead.

**Comment by jadsonleno123** [comment]
[Novo Documento de Texto.txt](https://github.com/microsoft/vcpkg/files/5639881/Novo.Documento.de.Texto.txt)

**Comment by jadsonleno123** [comment]
Esses são minhas falhas...!

**Comment by PhoebeHui** [comment]
@jadsonleno123, please install English language pack via vs installer and try again,

If the issue persist, pelease open a new issue with failure log 'C:\vcpkg\buildtrees\boost-regex\build-x64-windows-rel-out.log'.
