### ISSUE TITLE
[vcpkg] vcpkg_find_acquire_program fails to extract python2 with msiexec

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#7381]
**Execution scenario:**
gitlab-runner registered as a service running with user (not admin) priveleges.
(logging in with the user and doing the same works; so the service part somehow breaks msiexec)

**Error example:**
```
Building package qt5-datavis3d[core]:x64-windows-mpi...
-- Downloading http://download.qt.io/official_releases/qt/5.12/5.12.3/submodules/qtdatavis3d-everywhere-src-5.12.3.tar.xz...
-- Extracting source A:/downloads/qtdatavis3d-everywhere-src-5.12.3.tar.xz
-- Using source at A:/buildtrees/qt5-datavis3d/src/5.12.3-2bc0d7cd80
-- Downloading https://www.python.org/ftp/python/2.7.14/python-2.7.14.msi...
Auf den Windows Installer-Dienst konnte nicht zugegriffen werden. Dies kann auftreten, wenn der Windows Installer nicht richtig installiert wurde. Wenden Sie sich an den Support, um weitere Unterst�tzung zu erhalten.

-- Configuring x64-windows-mpi-rel 
```
Translation: Windows Installer-Service could not be accessed....

**Real Error:** (msiexec log from a testrun outside vcpkg)
```
=== Verbose logging started: 17.07.2019  12:51:55  Build type: SHIP UNICODE 5.00.10011.00  Calling process: C:\Windows\system32\msiexec.exe ===
MSI (c) (D4:34) [12:51:55:979]: Resetting cached policy values
MSI (c) (D4:34) [12:51:55:979]: Machine policy value 'Debug' is 0
MSI (c) (D4:34) [12:51:55:979]: ******* RunEngine:
           ******* Product: \\node02.imt.uni-luebeck.de\Scratch\neumann\Python2\python2.msi
           ******* Action: 
           ******* CommandLine: **********
MSI (c) (D4:34) [12:51:55:979]: Client-side and UI is none or basic: Running entire install on the server.
MSI (c) (D4:34) [12:51:55:979]: Grabbed execution mutex.
MSI (c) (D4:34) [12:51:55:983]: Es konnte keine Verbindung mit dem Server hergestellt werden. Fehler: 0x80070005

MSI (c) (D4:34) [12:51:55:984]: Note: 1: 2774 2: 0x80070005 
1: 2774 2: 0x80070005 
MSI (c) (D4:34) [12:51:55:984]: Failed to connect to server.
MSI (c) (D4:34) [12:51:55:985]: MainEngineThread is returning 1601
=== Verbose logging stopped: 17.07.2019  12:51:55 ===
```

Workaround: 
- Add manually extracted Python2 DIR to CMAKE_PROGRAM_PATH in custom triplet

Questions: 
- Which rights are actually required to run msiexec? 
- Why does running as a service break it?
- Should vcpkg use a different approach to extract the .msi file?
- Should vcpkg enable logging for msiexec?

**Comment by Ghabry** [comment]
Can confirm this.
I run vcpkg through a Jenkins Service and it fails with the same error.
Manually starting the Windows Installer doesn't help, must be some Windows Service isolation feature? No idea how to solve :(

**Comment by dg0yt** [comment]
Is this still an issue?

**Comment by samever7** [comment]
Still a issue, catch this when install grpc, like below:
A suitable version of 7zip was not found (required v19.0.0). Downloading portable 7zip v19.0.0...
Extracting 7zip...
msiexec failed while extracting 'D:\vcpkg\downloads\7z1900-x64.msi' with message:  // empty here

Still the same after I manually installed 7zip v19.0.0.

**Comment by samever7** [comment]
Actually for me every time when install something, if 7Zip needed it'll pop out this error:

A suitable version of 7zip was not found (required v19.0.0). Downloading portable 7zip v19.0.0...
Extracting 7zip...
msiexec failed while extracting  "xxxxxx"

Is there anyone can help?

**Comment by samever7** [comment]
All right, I removed the vcpkg folder and create a new one from scratch, this issue has gone now.

**Comment by dg0yt** [comment]
@samever7 There is a lot of ongoing work on the msiexec issue in the last 48 h.
