### ISSUE TITLE
[New Port Request] NTL

### ISSUE THREAD

**Issue by strega-nil** [microsoft/vcpkg#7389]
Library name: NTL (Number Theory Library)

Library description: A library for doing number theory

Source repository URL: (none)

Project homepage (if different from the source repository): https://shoup.net/ntl/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): N/A

**Comment by Voskrese** [comment]
`src + include`
`<RuntimeLibrary>MultiThreaded</RuntimeLibrary>`

msvc project
[WinNTL-11_3_2.zip](https://github.com/microsoft/vcpkg/files/3426903/WinNTL-11_3_2.zip)

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
