### ISSUE TITLE
Can't find vcpkg headers in vs2019

### ISSUE THREAD

**Issue by chrdwhdhxtszpzclljxk** [microsoft/vcpkg#7394]
when I use vcpkg installed ffmpeg, vs2019 can not find the ffmpeg header file  ?

**Comment by cbezault** [comment]
Have you run `vcpkg integrate install` and added `-DCMAKE_TOOLCHAIN_FILE=[vcpkg root]\scripts\buildsystems\vcpkg.cmake` to VS?
Was your setup working with vs2017?

To answer your question vcpkg is supposed to be vs2019 compatible.

**Comment by chrdwhdhxtszpzclljxk** [comment]
thanks,It's ok now .first I install ffmpeg with x86-windows-static, not ok。when install with x86-windows,it's ok now.
