### ISSUE TITLE
Using vcpkg without CMake

### ISSUE THREAD

**Issue by wrathofodin** [microsoft/vcpkg#7397]
I see that CMake is used to write ports (portfile.cmake).

What if I'm using other build systems like Premake? 

Is it possible to create integration with a different build system other than CMake?

**Comment by Voskrese** [comment]
https://github.com/microsoft/vcpkg/search?q=Premake&unscoped_q=Premake

example
https://github.com/microsoft/vcpkg/blob/master/ports/ode/portfile.cmake

**Comment by cbezault** [comment]
Yes you can use arbitrary build systems with vcpkg, though things are easier in general with a CMake build system.
There are cases where it's easier for us to provide a CMake build system for a library than it is to use the existing build system.
In general, however, you can just think of CMake as vcpkg's scripting language.
