### ISSUE TITLE
Enable dynamic building of gRPC

### ISSUE THREAD

**Issue by dzenanz** [microsoft/vcpkg#740]
As gRPC should now be [normally build-able using CMake](grpc/grpc#1096) , dynamic building should be re-enabled in vcpkg.

**Comment by KindDragon** [comment]
gRPC is not yet released with these changes

**Comment by dzenanz** [comment]
Ah, right - this is a commit in master branch. Then we will wait until it makes it into some release.

**Comment by Retik** [comment]
With gRPC 1.3.1 being included in vcpkg, can this feature be enabled now?

**Comment by KindDragon** [comment]
Doesn't link: `LINK : fatal error LNK1181: cannot open input file 'gpr.lib'`

**Comment by KindDragon** [comment]
https://github.com/grpc/grpc/issues/11261

**Comment by mathisloge** [comment]
[https://github.com/grpc/grpc/releases](https://github.com/grpc/grpc/releases ) 
gRPC is now on VErsion 1.6. 
With Cmake. should now be enabled?

**Comment by dzenanz** [comment]
CMake is now the recommended way to build on Windows: grpc/grpc#11462

**Comment by KindDragon** [comment]
Yes, but grpc/grpc#11261 still not fixed

**Comment by ik-wg** [comment]
Adding -DBUILD_SHARED_LIBS=True indeed builds the dlls but they are mostly empty, since there`re no windows specific __declspec dllexport. Damn we really need this.

**Comment by Neumann-A** [comment]
@Cheney-W close. Upstream issue. grpc doesn't export symbols and the build doesn't work with BUILD_SHARED_LIBS and CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS
