### ISSUE TITLE
[New Port Request] log4cpp

### ISSUE THREAD

**Issue by iceseyes** [microsoft/vcpkg#7408]
Library name: log4cpp

Library description:
Log4cpp is library of C++ classes for flexible logging to files, syslog, IDSA and other destinations. It is modeled after the Log4j Java library, staying as close to their API as is reasonable

Source repository URL: https://sourceforge.net/p/log4cpp/codegit/ci/master/tree/

Project homepage (if different from the source repository): http://log4cpp.sourceforge.net/

**Comment by Voskrese** [comment]
[log4cpp.zip](https://github.com/microsoft/vcpkg/files/3430917/log4cpp.zip)

tested windows x64 dynamic

**Comment by NancyLi1013** [comment]
Hi @iceseyes  Thanks for posting this request. This port has been added to vcpkg. Please try to update vcpkg and use this port.
