### ISSUE TITLE
shiva[core]:x64-windows build failure - python config failure: Python is 32-bit, chosen compiler is 64-bit

### ISSUE THREAD

**Issue by timautry** [microsoft/vcpkg#7411]
**Host Environment**
- OS: [Windows 10 - 1903 - Build 18362.239]
- Compiler: VS2017 - Tools: MSVC 14.16.27023 Redist: MSVC 14.16.27012
                   VS2019 - Tools: MSVC 14.21.27702 Redist: MSVC 14.21.27702

**To Reproduce**
`./vcpkg install shiva[core]:x64-windows`

**Failure logs** 
**_VS2017 Community:_**
SYSTEM@ANDROMEDA 07/24/2019 19:23:32 D:\Git\vs2017
->vcpkg install shiva[core]:x64-windows
The following packages will be built and installed:
    shiva[core]:x64-windows
Starting package 1/1: shiva:x64-windows
Building package shiva[core]:x64-windows...
-- Using cached D:/Git/vcpkg.downloads/Milerius-shiva-1.0.tar.gz
-- Using source at D:/Git/vs2017/buildtrees/shiva/src/1.0-2860004d47
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:58 (message):
    Command failed: ninja -v
    Working Directory: D:/Git/vs2017/buildtrees/shiva/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\Git\vs2017\buildtrees\shiva\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:290 (vcpkg_execute_required_process)
  ports/shiva/portfile.cmake:13 (vcpkg_configure_cmake)
  scripts/ports.cmake:74 (include)

Error: Building package shiva:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: shiva:x64-windows
  Vcpkg version: 2019.07.18-nohash-external

Additionally, attach any relevant sections from the log files above.

**_VS2019 Community:_**
SYSTEM@ANDROMEDA 07/24/2019 19:24:53 D:\Git\vs2019
->vcpkg install shiva[core]:x64-windows
The following packages will be built and installed:
    shiva[core]:x64-windows
Starting package 1/1: shiva:x64-windows
Building package shiva[core]:x64-windows...
-- Using cached D:/Git/vcpkg.downloads/Milerius-shiva-1.0.tar.gz
-- Using source at D:/Git/vs2019/buildtrees/shiva/src/1.0-2860004d47
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:58 (message):
    Command failed: ninja -v
    Working Directory: D:/Git/vs2019/buildtrees/shiva/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\Git\vs2019\buildtrees\shiva\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:290 (vcpkg_execute_required_process)
  ports/shiva/portfile.cmake:13 (vcpkg_configure_cmake)
  scripts/ports.cmake:74 (include)

Error: Building package shiva:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: shiva:x64-windows
  Vcpkg version: 2019.07.18-nohash-external

Additionally, attach any relevant sections from the log files above.

-Please attach any additional failure logs mentioned in the console output.
[vs2017_buildtrees_shiva_config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/3429094/vs2017_buildtrees_shiva_config-x64-windows-out.log)
[vs2019_buildtrees_shiva_config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/3429095/vs2019_buildtrees_shiva_config-x64-windows-out.log)

**Additional context**
1. I can rename the ./downloads/tools/python/python2 (version 2.7.16 32-bit downloaded and installed by vcpkg) folder to ./downloads/tools/python/python2-32-bit and download the 64-bit version of python 2.7.16 and put it in a new ./downloads/tools/python/python2  folder and reissue the .\vcpkg.exe install shiva[core]:x64-windows command in both VS2017 and VS2019 and it will install correctly.
2. Looking at the logs, starting at bottom and counting 14 lines up there is the following error line:
-- Found PythonInterp: D:/Git/vcpkg.downloads/tools/python/python2/python.exe (found version "2.7.16") 
CMake Error at D:/Git/vs2019/installed/x64-windows/share/cmake/pybind11/FindPythonLibsNew.cmake:122 (message):
  **Python config failure: Python is 32-bit, chosen compiler is 64-bit**
3. I'm not sure how making this change will affect/effect other installed packages or packages to be installed in the future?
4. Should we create both a python2-32 and python2-64 folder and have vcpkg look in the appropriate folder depending of whether you're compiling something 32 or 64 bit in windows?

Thank you for any guidance and assistance.

**Comment by Voskrese** [comment]
remove pybind11

install pybind11 // python x64

?

**Comment by timautry** [comment]
What do you mean by "install pybind11 // python x64"?

1. When pybindll is installed, it was installed via command line ".\vcpkg.exe install pybind11[core]:x64-windows".
2. So I tried the following:
SYSTEM@ANDROMEDA 07/24/2019 20:10:14 D:\Git\vs2019
->vcpkg remove pybind11 --recurse
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be removed:
  * coolprop:x64-windows
    pybind11:x64-windows
Additional packages (*) need to be removed to complete this operation.
Removing package coolprop:x64-windows...
Removing package coolprop:x64-windows... done
Purging package coolprop:x64-windows...
Purging package coolprop:x64-windows... done
Removing package pybind11:x64-windows...
Removing package pybind11:x64-windows... done
Purging package pybind11:x64-windows...
Purging package pybind11:x64-windows... done

SYSTEM@ANDROMEDA 07/24/2019 20:10:30 D:\Git\vs2019
->vcpkg install shiva[core]:x64-windows
The following packages will be built and installed:
  * pybind11[core]:x64-windows
    shiva[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: pybind11:x64-windows
Building package pybind11[core]:x64-windows...
-- Using cached D:/Git/vcpkg.downloads/pybind-pybind11-v2.2.4.tar.gz
-- Using source at D:/Git/vs2019/buildtrees/pybind11/src/v2.2.4-c609b9e396
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/Git/vs2019/packages/pybind11_x64-windows/share/pybind11/copyright/LICENSE
-- Performing post-build validation
-- Performing post-build validation done
Building package pybind11[core]:x64-windows... done
Installing package pybind11[core]:x64-windows...
Installing package pybind11[core]:x64-windows... done
Elapsed time for package pybind11:x64-windows: 10.5 s
Starting package 2/2: shiva:x64-windows
Building package shiva[core]:x64-windows...
-- Using cached D:/Git/vcpkg.downloads/Milerius-shiva-1.0.tar.gz
-- Using source at D:/Git/vs2019/buildtrees/shiva/src/1.0-2860004d47
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:58 (message):
    Command failed: ninja -v
    Working Directory: D:/Git/vs2019/buildtrees/shiva/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\Git\vs2019\buildtrees\shiva\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:290 (vcpkg_execute_required_process)
  ports/shiva/portfile.cmake:13 (vcpkg_configure_cmake)
  scripts/ports.cmake:74 (include)


Error: Building package shiva:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: shiva:x64-windows
  Vcpkg version: 2019.07.18-nohash-external

Additionally, attach any relevant sections from the log files above. 
 
But shiva still fails as pybind11 is installing the 32-bit version of python2 disregarding the x64-windows triplet.

**Comment by timautry** [comment]
Did some research - .\scripts\vcpkg_find_acquire_program.cmake has hard coded urls to download the 32-bit versions python-2.7.16.msi and python-3.7.3-embed-win32.zip. 
1. Maybe there is a need to have vcpkg evaluate the bitness and install a version of the 32-bit and 64-bit versions of python accordingly?
2. This may also need to be done for Strawberry Perl, Aria2, nuget and other 32 versus 64 bit tools/utility packages also? 
3. Also would it be possible to have vcpkg search the %PATH% variable for things like doxygen, 7zip, wix, etc and use the installed versions if they are correct and/or compatible instead of downloading and installing a version in the downloads\tools folder?
Thank you much all for the hard work!!!
Tim

**Comment by Voskrese** [comment]
```
vcpkg install shiva[*]:x64-windows
The following packages will be built and installed:
  * nlohmann-json[core]:x64-windows
    shiva[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: nlohmann-json:x64-windows
Building package nlohmann-json[core]:x64-windows...
-- Using cached E:/tools/vcpkg/downloads/nlohmann-json-v3.6.1/CMakeLists.txt
-- Using cached E:/tools/vcpkg/downloads/nlohmann-json-v3.6.1/LICENSE.MIT
-- Using cached E:/tools/vcpkg/downloads/nlohmann-json-v3.6.1/nlohmann_json.natvis
-- Using cached E:/tools/vcpkg/downloads/nlohmann-json-v3.6.1/cmake/config.cmake.in
-- Using cached E:/tools/vcpkg/downloads/nlohmann-json-v3.6.1/single_include/nlohmann/json.hpp
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: E:/tools/vcpkg/packages/nlohmann-json_x64-windows/share/nlohmann-json/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package nlohmann-json[core]:x64-windows... done
Installing package nlohmann-json[core]:x64-windows...
Installing package nlohmann-json[core]:x64-windows... done
Elapsed time for package nlohmann-json:x64-windows: 43.09 s
Starting package 2/2: shiva:x64-windows
Building package shiva[core]:x64-windows...
-- Downloading https://github.com/Milerius/shiva/archive/1.0.tar.gz...
-- Extracting source E:/tools/vcpkg/downloads/Milerius-shiva-1.0.tar.gz
-- Using source at E:/tools/vcpkg/buildtrees/shiva/src/1.0-2860004d47
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package shiva[core]:x64-windows... done
Installing package shiva[core]:x64-windows...
Installing package shiva[core]:x64-windows... done
The package shiva:x64-windows provides CMake targets:

    find_package(cmake CONFIG REQUIRED)
    target_link_libraries(main PRIVATE ${ModuleAlias} ${RealModuleName})

    find_package(shiva CONFIG REQUIRED)
    # Note: 15 target(s) were omitted.
    target_link_libraries(main PRIVATE shiva::pp shiva::dll shiva::ecs shiva::lua)
```


**python 32 bit**

**Comment by timautry** [comment]
Another thought, is I've compiled vcpkg with the -win64 option when running .\bootstrap.bat to create a 64 bit version of vcpkg.exe, where most would not bother to add this option which would default to a 32 bit version of vcpkg even on a 64 bit machine.
I'm not sure if this plays into the issue I'm having or not.
Thanks for any information you can provide on this subject!
Have a wonderful day.

**Comment by Voskrese** [comment]
`vcpkg install shiva[*]:x64-windows` <<-- [*]

> try to install with all dependencies, it seems to me that this function does not always work correctly

**Comment by timautry** [comment]
Whether one uses an "asterisk", "core", or "nothing" as there are no additional options for package shiva, nonetheless here is the results:
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.14
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

SYSTEM@ANDROMEDA 07/25/2019 13:04:07 D:\Git\vs2017
_->.\vcpkg.exe install shiva[*]:x64-windows_
The following packages will be built and installed:
    shiva[core]:x64-windows
Starting package 1/1: shiva:x64-windows
Building package shiva[core]:x64-windows...
-- Using cached D:/Git/vcpkg.downloads/Milerius-shiva-1.0.tar.gz
-- Using source at D:/Git/vs2017/buildtrees/shiva/src/1.0-2860004d47
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:58 (message):
    Command failed: ninja -v
    Working Directory: D:/Git/vs2017/buildtrees/shiva/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\Git\vs2017\buildtrees\shiva\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:290 (vcpkg_execute_required_process)
  ports/shiva/portfile.cmake:13 (vcpkg_configure_cmake)
  scripts/ports.cmake:74 (include)


Error: Building package shiva:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: shiva:x64-windows
  Vcpkg version: 2019.07.18-nohash-external

Additionally, attach any relevant sections from the log files above.
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/3432595/config-x64-windows-out.log)

It wants a 64 bit python not the 32 bit installed by vcpkg that is hard coded in  .\scripts\vcpkg_find_acquire_program.cmake

**Comment by JackBoosY** [comment]
Hi @timautry, thanks for reporting this issue!
We added python 64-bit support just now, please update vcpkg and rebuild shiva.

Thanks.
