### ISSUE TITLE
[gtk] update to 3.22.30

### ISSUE THREAD

**Issue by memecode** [microsoft/vcpkg#7412]
Library name: GTK

New version number: v3.22.30

The current GTK build is very VERY old: v3.22.19 (circa 2017-08-22). I'm running into bugs that have been fixed a long time ago when using it. So I don't know if v3.22.30 is the right call, but it's the latest. I do know that  a 2 year old version is not OK. Could we update to something from this year at least?

I'm currently experimenting with just changing the portfile to point to the latest version and rebuilding. But I'm worried that other dependent libs are also very out of date. GTK has a long list of deps.

**Comment by memecode** [comment]
Or maybe you should target v3.24.10?

**Comment by Voskrese** [comment]
glib, gtk, gstreamer ... officially switched to MESON

> with MESON there are some problems in the search for dependencies and this direction does not develop in VCPKG, at least under WINDOWS

**Comment by memecode** [comment]
> 
> 
> glib, gtk, gstreamer ... officially switched to MESON
> 
> > with MESON there are some problems in the search for dependencies and this direction does not develop in VCPKG, at least under WINDOWS

Is there an actual recipe or guide to build GTK with meson? I doesn't work out of the box for me.

**Comment by Voskrese** [comment]
no, but there are examples, let's say a project

https://github.com/wingtk/gvsbuild

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/11797.
