### ISSUE TITLE
[New Port Request] openHEVC

### ISSUE THREAD

**Issue by Voskrese** [microsoft/vcpkg#7414]
Library name: openHEVC

Library description: openHEVC is a fork of Libav with only the files needed to decode HEVC content, it was created for research purposes. Most people will not need to use this and should use the libav HEVC decoder available at https://github.com/OpenHEVC/ffmpeg instead (see https://ffmpeg.org/documentation.html for documentation).

Source repository URL: openHEVC

Project homepage (if different from the source repository): https://github.com/OpenHEVC/openHEVC

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

`DEPS ` YASM: **LIB** ! **INCLUDE** ! https://github.com/microsoft/vcpkg/issues/7415

**Comment by NancyLi1013** [comment]
Hi @Voskrese thanks for posting this request.
There are many errors when building on Windows. It seems that it is not easy to fix them now.
So currently we can only add support for Linux. 
As for OSX, I'm not sure the status since I haven't built it on Mac.

**Comment by Voskrese** [comment]
Hi @NancyLi1013 , thanks

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
