### ISSUE TITLE
Error : error LNK2001: unresolved external symbol ___std_terminate

### ISSUE THREAD

**Issue by sharmaenmi1996** [microsoft/vcpkg#7420]
1>------ Build started: Project: VESGenVideo, Configuration: Release Win32 ------
1>     Creating library ..\..\bin\VESGenVideo.lib and object ..\..\bin\VESGenVideo.exp
1>BlackflyGigE.obj : error LNK2001: unresolved external symbol ___std_terminate
1>mfcs140.lib(nolib.obj) : error LNK2001: unresolved external symbol ___std_terminate
1>mfcs140.lib(dllmodul.obj) : error LNK2001: unresolved external symbol ___std_terminate
1>mfcs140.lib(stdafx.obj) : error LNK2001: unresolved external symbol ___std_terminate
1>BlackflyGigE.obj : error LNK2001: unresolved external symbol "void __stdcall `eh vector destructor iterator'(void *,unsigned int,unsigned int,void (__thiscall*)(void *))" (??_M@YGXPAXIIP6EX0@Z@Z)
1>mfcs140.lib(nolib.obj) : error LNK2001: unresolved external symbol "void __stdcall `eh vector destructor iterator'(void *,unsigned int,unsigned int,void (__thiscall*)(void *))" (??_M@YGXPAXIIP6EX0@Z@Z)
1>mfcs140.lib(dllmodul.obj) : error LNK2001: unresolved external symbol "void __stdcall `eh vector destructor iterator'(void *,unsigned int,unsigned int,void (__thiscall*)(void *))" (??_M@YGXPAXIIP6EX0@Z@Z)
1>mfcs140.lib(stdafx.obj) : error LNK2001: unresolved external symbol "void __stdcall `eh vector destructor iterator'(void *,unsigned int,unsigned int,void (__thiscall*)(void *))" (??_M@YGXPAXIIP6EX0@Z@Z)
1>BlackflyGigE.obj : error LNK2001: unresolved external symbol __imp____acrt_iob_func
1>BlackflyGigE.obj : error LNK2001: unresolved external symbol __imp____stdio_common_vfprintf
1>DirectShow.obj : error LNK2001: unresolved external symbol "void __stdcall `eh vector constructor iterator'(void *,unsigned int,unsigned int,void (__thiscall*)(void *),void (__thiscall*)(void *))" (??_L@YGXPAXIIP6EX0@Z1@Z)
1>DirectShow.obj : error LNK2001: unresolved external symbol __imp____stdio_common_vsprintf
1>DirectShow.obj : error LNK2001: unresolved external symbol __imp____stdio_common_vswprintf_s
1>PGSpinnaker.obj : error LNK2001: unresolved external symbol __imp____std_exception_copy
1>PGSpinnaker.obj : error LNK2001: unresolved external symbol __imp____std_exception_destroy
1>stdafx.obj : error LNK2001: unresolved external symbol __Init_thread_epoch
1>mfcs140.lib(nolib.obj) : error LNK2001: unresolved external symbol __Init_thread_epoch
1>mfcs140.lib(dllmodul.obj) : error LNK2001: unresolved external symbol __Init_thread_epoch
1>mfcs140.lib(stdafx.obj) : error LNK2001: unresolved external symbol __Init_thread_epoch
1>stdafx.obj : error LNK2001: unresolved external symbol __Init_thread_footer
1>mfcs140.lib(nolib.obj) : error LNK2001: unresolved external symbol __Init_thread_footer
1>mfcs140.lib(dllmodul.obj) : error LNK2001: unresolved external symbol __Init_thread_footer
1>mfcs140.lib(stdafx.obj) : error LNK2001: unresolved external symbol __Init_thread_footer
1>stdafx.obj : error LNK2001: unresolved external symbol __Init_thread_header
1>mfcs140.lib(nolib.obj) : error LNK2001: unresolved external symbol __Init_thread_header
1>mfcs140.lib(dllmodul.obj) : error LNK2001: unresolved external symbol __Init_thread_header
1>mfcs140.lib(stdafx.obj) : error LNK2001: unresolved external symbol __Init_thread_header
1>mfcs140.lib(nolib.obj) : error LNK2001: unresolved external symbol "void __cdecl operator delete(void *,unsigned int)" (??3@YAXPAXI@Z)
1>mfcs140.lib(dllmodul.obj) : error LNK2001: unresolved external symbol "void __cdecl operator delete(void *,unsigned int)" (??3@YAXPAXI@Z)
1>mfcs140.lib(stdafx.obj) : error LNK2001: unresolved external symbol "void __cdecl operator delete(void *,unsigned int)" (??3@YAXPAXI@Z)
1>mfcs140.lib(nolib.obj) : error LNK2001: unresolved external symbol "void __cdecl operator delete[](void *,unsigned int)" (??_V@YAXPAXI@Z)
1>mfcs140.lib(dllmodul.obj) : error LNK2001: unresolved external symbol "void __cdecl operator delete[](void *,unsigned int)" (??_V@YAXPAXI@Z)
1>mfcs140.lib(stdafx.obj) : error LNK2001: unresolved external symbol "void __cdecl operator delete[](void *,unsigned int)" (??_V@YAXPAXI@Z)
1>mfcs140.lib(nolib.obj) : error LNK2001: unresolved external symbol @_guard_check_icall@4
1>mfcs140.lib(dllmodul.obj) : error LNK2001: unresolved external symbol @_guard_check_icall@4
1>mfcs140.lib(stdafx.obj) : error LNK2001: unresolved external symbol @_guard_check_icall@4
1>mfcs140.lib(rawdllmainproxy.obj) : error LNK2001: unresolved external symbol @_guard_check_icall@4
1>..\..\bin\VESGenVideo.dll : fatal error LNK1120: 15 unresolved externals

**Comment by wangli28** [comment]
Hi @sharmaenmi1996, thanks for posting this issue. Can you provide more information about this issue? What did you do with VCPKG?

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you.
