### ISSUE TITLE
[openvdb] build failure

### ISSUE THREAD

**Issue by Const-me** [microsoft/vcpkg#7425]
**Host Environment**
Windows 10 1803
VS 2017 community 15.9.4
Vcpkg package management program version 2019.07.18-nohash

**To Reproduce**
create `x64-static.cmake` triplet file with the following content:
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
```
Run the command:
`./vcpkg install openvdb:x64-static`

Go get some coffee. It takes 20 minutes on my PC, which has a quad core Xeon, 16GB RAM, Samsung 850 Pro SSD, 120 mbit/sec cable.

**Failure logs** 
```
Building package openvdb[core]:x64-static...
-- Downloading https://github.com/AcademySoftwareFoundation/openvdb/archive/v6.1.0.tar.gz...
-- Extracting source C:/Z/vcpkg/downloads/AcademySoftwareFoundation-openvdb-v6.1.0.tar.gz
-- Applying patch 0001-remove-pkgconfig.patch
-- Applying patch 0002-fix-cmake-modules.patch
-- Applying patch 0003-fix-cmake.patch
-- Using source at C:/Z/vcpkg/buildtrees/openvdb/src/v6.1.0-405cd4b264
-- Configuring x64-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:58 (message):
    Command failed: ninja -v
    Working Directory: C:/Z/vcpkg/buildtrees/openvdb/x64-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Z\vcpkg\buildtrees\openvdb\config-x64-static-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:290 (vcpkg_execute_required_process)
  ports/openvdb/portfile.cmake:31 (vcpkg_configure_cmake)
  scripts/ports.cmake:74 (include)

Error: Building package openvdb:x64-static failed with: BUILD_FAILED
```

Here's the error from config-x64-static-out.log:

```
-- ----------------------------------------------------
-- ----------- Configuring OpenVDBBinaries ------------
-- ----------------------------------------------------
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
BLOSC_blosc_LIBRARY
    linked by target "openvdb_static" in directory C:/Z/vcpkg/buildtrees/openvdb/src/v6.1.0-405cd4b264/openvdb

-- Configuring incomplete, errors occurred!
```

**Additional context**
Initially I tried `x64-windows-static` triplet, but it's less then ideal for my use case. I do use CRT DLLs, and I have appropriate merge modules in the installer of the product. Also Intel's `tbb` dependency failed to build with static CRT.

The built-in `x64-windows` triplet works OK for that package, but I don't like 37 DLLs with the code which is never called. I like linker.

**Comment by Const-me** [comment]
To workaround, edit the file `ports\openvdb\0002-fix-cmake-modules.patch`
Go to the line 175 which says
`SET ( _blosc_library_name "blosc" )`
Change into 
`SET ( _blosc_library_name "libblosc" )`

Have not yet tested the result, but at least it builds now.

I only need Windows build, have no idea if it gonna work for other OSes or compilers.

**Comment by JackBoosY** [comment]
@Const-me  For unofficially supported triplets may cause some settings to fail, thanks for reporting this issue!
