### ISSUE TITLE
[liblzma] build failure

### ISSUE THREAD

**Issue by Const-me** [microsoft/vcpkg#7426]
**Host Environment**
Windows 10 1803
VS 2017 community 15.9.4
Vcpkg package management program version 2019.07.18-nohash

**To Reproduce**
Create `win32-static.cmake` triplet file with the following content:
```
set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_BUILD_TYPE debug)
```
Then run `./vcpkg install liblzma:win32-static`

**Failure logs** 
```
-- Performing post-build validation
The folder /include is empty or not present. This indicates the library was not correctly installed.
Found 1 error(s). Please correct the portfile:
    C:\Z\vcpkg\ports\liblzma\portfile.cmake
-- Performing post-build validation done
Error: Building package liblzma:win32-static failed with: POST_BUILD_CHECKS_FAILED
```

**Comment by cenit** [comment]
Hi @const-me
Unfortunately while vcpkg *almost* work with release-only triplets, I have to say that debug-only triplets will give you many headaches. 
In fact, there’s no clean solution in any port that installs both debug/include and include folders by default to not delete debug/include if the other one is not available... I think that we could ping @ras0219-msft to see if he has any clear path in mind for this situation

**Comment by Const-me** [comment]
@cenit Thanks for the comment. That’s what I’ve figured out experimenting with these things. I knew vcpkg exists, but until couple days ago when I needed openvdb I had not any experience using it.

It’s not a huge deal, actually.

The unused release config doubles build time from 10 to 20 minutes, adds 500MB of build results, but I hope I won’t do it too often. Once I’ll build these packages with the settings that I need, I’m only planning to update them once in ~6 months or so. I’m almost there BTW, it already works fine, but ideally need a reply to #7442 for better debug symbols included.

**Comment by JackBoosY** [comment]
Close this issue via #7481 merged.
