### ISSUE TITLE
Nuget triplet selection

### ISSUE THREAD

**Issue by Const-me** [microsoft/vcpkg#7428]
I’ve exported a nuget package from vcpkg with the following command:
`./vcpkg export openvdb:x64-static openvdb:win32-static --nuget --nuget-id=openvdb --nuget-version=6.1.0`

Trying to use it but can’t. VC++ build system has added the following include directory:
`packages\openvdb.6.1.0\installed\x64-windows\include`
That directory doesn’t exist. I have another one which does exist:
`packages\openvdb.6.1.0\installed\x64-static\include`

I’ve defined `x64-static` custom triple because I wanted static libraries instead of DLLs.

**Proposed solution**

I want nuget packages working out of the box.

While vcpkg was making my nuget package, it knew the correct triplets, i.e. that the package contains 3 configurations, debug win32, release win32, and release x64. It had an opportunity to fix it inside the nuget package, in the `\scripts\buildsystems\msbuild\vcpkg.targets` file, but didn’t.

The proposed automatic selection won’t work in 100% cases, when there’re multiple triplets for the same architecture. In this case it’s reasonable to print a warning while creating the package, with the link to https://vcpkg.readthedocs.io/en/latest/users/integration/#triplet-selection and do nothing else i.e. revert to the current behavior.

**Describe alternatives you've considered**

The [current solution is manual](https://vcpkg.readthedocs.io/en/latest/users/integration/#triplet-selection) and it does work, with the following addition to the .vcxproj:

	<VcpkgTriplet Condition="'$(Platform)'=='Win32'">win32-static</VcpkgTriplet>
	<VcpkgTriplet Condition="'$(Platform)'=='x64'">x64-static</VcpkgTriplet>

However, it would be nice to be automatic. There's no GUI to switch that. Users need to unload the project, manually edit the vcproj, reload the project, there's always a risk they'll break something and come to me asking how to fix. Also, I can't rename triplets just on my side because it will break their projects.

**Comment by contre** [comment]
Why did you define your own triplets instead of using the provided x86-windows-static and x64-windows-static triplets? Do you get different behavior if you use those instead?

**Comment by Const-me** [comment]
@contre Yes, indeed. I need dynamic CRT, but I want the stuff I'm building, openvdb + it's dependencies, to be static libraries.

**Comment by jonathanverner** [comment]
I stumbled into the same problem with exported packages using cmake. The generated `/scripts/buildsystems/vcpkg.cmake` tries to guess the triplet automatically based on the platform, but that will fail for custom triplets.

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/3042.
