### ISSUE TITLE
Multiple values for --triplet and %VCPKG_DEFAULT_TRIPLET%

### ISSUE THREAD

**Issue by vrubleg** [microsoft/vcpkg#7432]
I usually install a every new library for 4 different triplets: `x86-windows-static,x64-windows-static,x86-windows-crtdll,x64-windows-crtdll` (`crtdll` is for `VCPKG_CRT_LINKAGE=dynamic` and `VCPKG_LIBRARY_LINKAGE=static`, I would provide it as a preinstalled option). And it takes time to type something like:
```
vcpkg install fmt:x64-windows-crtdll fmt:x64-windows-static fmt:x86-windows-crtdll fmt:x86-windows-static
```

I propose to add support specifying of multiple triplets in the `--triplet` argument:
```
vcpkg install fmt --triplet x64-windows-crtdll;x64-windows-static;x86-windows-crtdll;x86-windows-static
```

And to make it even better, please support multiple triplets in the `%VCPKG_DEFAULT_TRIPLET%` environment variable, like this:
```
set VCPKG_DEFAULT_TRIPLET=x64-windows-crtdll;x64-windows-static;x86-windows-crtdll;x86-windows-static
vcpkg install fmt
```
`;` is usually used as a delimiter for environment variables, but `,` could be supported also.

**Comment by seven-mile** [comment]
Did vcpkg make any progress on this issue? I hope my build tools can find packages by some specific priority, too...
