### ISSUE TITLE
[Azure-c-shared-utility:x86-uwp] build failure

### ISSUE THREAD

**Issue by L1hunt** [microsoft/vcpkg#7439]
**Host Environment**
- OS: Windows 10
- Compiler: revision

**To Reproduce**
` .\vcpkg install azure-iot-sdk-c:x86-uwp
[install-x86-uwp-dbg-out.log](https://github.com/microsoft/vcpkg/files/3436341/install-x86-uwp-dbg-out.log)
[install-x86-uwp-dbg-out.log](https://github.com/microsoft/vcpkg/files/3436352/install-x86-uwp-dbg-out.log)

`

**Failure logs** 
The following packages will be built and installed:
  * azure-c-shared-utility[core]:x86-uwp
    azure-iot-sdk-c[core]:x86-uwp
  * azure-uamqp-c[core]:x86-uwp
  * azure-uhttp-c[core]:x86-uwp
  * azure-umqtt-c[core]:x86-uwp
Additional packages (*) will be modified to complete this operation.
Starting package 1/5: azure-c-shared-utility:x86-uwp
Building package azure-c-shared-utility[core]:x86-uwp...
-- Note: azure-c-shared-utility only supports static library linkage. Building static library.
-- Using cached C:/Users/Elwin/vcpkg_new/downloads/Azure-azure-c-shared-utility-f0642196af85aeb4f2717d9cc11176290f321fb8.tar.gz
-- Using source at C:/Users/Elwin/vcpkg_new/buildtrees/azure-c-shared-utility/src/290f321fb8-f6bb8a755c
-- Configuring x86-uwp
-- Building x86-uwp-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/Users/Elwin/vcpkg_new/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
    Working Directory: C:/Users/Elwin/vcpkg_new/buildtrees/azure-c-shared-utility/x86-uwp-dbg
    See logs for more information:
      C:\Users\Elwin\vcpkg_new\buildtrees\azure-c-shared-utility\install-x86-uwp-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/azure-c-shared-utility/portfile.cmake:35 (vcpkg_install_cmake)
  scripts/ports.cmake:74 (include)

Error: Building package azure-c-shared-utility:x86-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: azure-c-shared-utility:x86-uwp
  Vcpkg version: 2019.07.18-nohash

**Additional context**
The same errors appear if I try to build any of the triplet ":xxx-uwp" libraries. I can successfully build the ":x86-windows" and ":x86-windows-static" libraries.

**Comment by JackBoosY** [comment]
Hi @L1hunt, thanks for reporting this issue!
By reading the code, I found that some of the functions included in it do **NOT** support the uwp app, and there is **NO** alternative function that supports uwp, so I think this port does not support uwp.

We need to wait for the official support uwp to update this port to solve this issue.

Thanks.
