### ISSUE TITLE
Add MessagePack

### ISSUE THREAD

**Issue by nzbart** [Microsoft/vcpkg#744]
Is there any chance of adding [MessagePack](http://msgpack.org/index.html) as a library?

MessagePack is, from their website:

>It's like JSON.
>but fast and small.
>
>MessagePack is an efficient binary serialization format. It lets you exchange data among multiple languages like JSON. But it's faster and smaller. Small integers are encoded into a single byte, and typical short strings require only one extra byte in addition to the strings themselves.

**Comment by ras0219-msft** [comment]
We'd be happy to accept a PR for messagepack!

**Comment by Mixaill** [comment]
Added in #769

**Comment by nzbart** [comment]
Thanks, @Mixaill!
