### ISSUE TITLE
Global compiler options?

### ISSUE THREAD

**Issue by Const-me** [microsoft/vcpkg#7442]
I’m using vcpkg to build openvdb into a set of static libraries, with VC++ 2017.

Works pretty well after a couple of manual patches.

But ideally, I’d like to pass [/Z7 compiler switch](https://docs.microsoft.com/en-us/cpp/build/reference/z7-zi-zi-debug-information-format?view=vs-2019) so the .lib files included in `openvdb.6.1.0.nupkg` contain complete debug information, which then go to the .pdb file made by the projects using the libraries I’m building.

Is there a way to tell vcpkg to append compiler flags to whatever ninja/cmake build systems are building the library and it’s dependencies?

Thanks in advance.

**Comment by cloudhan** [comment]
Maybe have a look at https://github.com/microsoft/vcpkg/blob/master/scripts/toolchains/windows.cmake

**Comment by cenit** [comment]
> But ideally, I’d like to pass /Z7 compiler switch so the .lib 

Should already be set up so...

**Comment by PhoebeHui** [comment]
The option already added, looks this issue can be closed.
