### ISSUE TITLE
[atlmfc:x64-windows] build failure

### ISSUE THREAD

**Issue by walden1** [microsoft/vcpkg#7446]
**Host Environment**
- OS: Windows 10
- Compiler: revision

**To Reproduce**
`./vcpkg install qt5:x64-windows`
'The following packages will be built and installed:
  * atlmfc[core]:x64-windows
    qt5[core]:x64-windows
  * qt5-speech[core]:x64-windows
  * qt5-svg[core]:x64-windows
  * qt5-tools[core]:x64-windows
  * qt5-virtualkeyboard[core]:x64-windows
  * qt5-websockets[core]:x64-windows
  * qt5-winextras[core]:x64-windows
  * qt5-xmlpatterns[core]:x64-windows'

**Failure logs** 
'Building package atlmfc[core]:x64-windows...
CMake Error at ports/atlmfc/portfile.cmake:7 (message):
  Unable to locate 'afxres.h'.  Ensure you have installed the ATL/MFC
  component of Visual Studio.
Call Stack (most recent call first):
  scripts/ports.cmake:74 (include)

Error: Building package atlmfc:x64-windows failed with: BUILD_FAILED'

**Comment by contre** [comment]
Have you checked to make sure you have both ATL and MFC installed for visual studio under the desktop workload?

Additionally, if you have multiple Visual Studio versions installed, make sure that ATL and MFC are installed for the version being used by vcpkg which I believe defaults to the latest version. I personally ran into this issue with a different package and didn’t realize it was using 2019 when I normally use 2017.

**Comment by PhoebeHui** [comment]
@walden1, please install ATL and MFC component via vs installer, and try again, you can reference https://github.com/microsoft/vcpkg/issues/4257
