### ISSUE TITLE
[New Port Request] <PcapPlusPlus>

### ISSUE THREAD

**Issue by realsarm** [microsoft/vcpkg#7447]
Library name: PcapPlusPlus

Library description: PcapPlusPlus is a multiplatform C++ library for capturing, parsing and crafting of network packets. It is designed to be efficient, powerful and easy to use.

Source repository URL: https://github.com/seladb/PcapPlusPlus

Project homepage (if different from the source repository): https://pcapplusplus.github.io/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by seladb** [comment]
Updated project homepage: https://pcapplusplus.github.io/

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by NancyLi1013** [comment]
pcapplusplus has been added to vcpkg now, please update to the latest vcpkg via git pull and try to use this port.
