### ISSUE TITLE
Can't compile a project with gtest under VS 2017 (VS 2015 toolchain)

### ISSUE THREAD

**Issue by olegtarasov** [microsoft/vcpkg#745]
I've pulled the latest commit from github, executed `vcpkg integrate install` and tried to build a project which uses gtest. The compiler can't find the include file `gtest/gtest.h`. The project uses VS 2015 toolchain.

**Comment by ras0219-msft** [comment]
Did you make sure to run `vcpkg install gtest`?

Are you trying to build for 64-bit? If so, you'll need to install `gtest:x64-windows`.

Finally, are you using the VS2017 IDE with the VS2015 toolchain? We do currently have a known issue where cross-targeting between the IDE and toolchain version can cause problems.

**Comment by olegtarasov** [comment]
Yes, I am compiling for x64 and I had `gtest:x64-windows` already installed. Just to be sure, I removed the package with `--purge` flag and installed it anew. The result didn't change. I'm trying to compile from VS 2017 with the VS 2015 toolchain. The same project compiles from VS 2015 just fine.

**Comment by ras0219-msft** [comment]
Thanks. This is unfortunately a known issue -- you'll need to use the 2015 ide/msbuild to get user-wide integration for 2015 projects.

An alternative workaround is to use our per-project integration (the NuGet package) which will work inside the 2017 ide.

**Comment by Cheney-W** [comment]
Verified on VS2019 with VS2015 toolset, this issue remains.
