### ISSUE TITLE
[librdkafka] Snappy compression option

### ISSUE THREAD

**Issue by rotrida** [microsoft/vcpkg#7454]
librdkafka is not being compiled with the "snappy" option. I've made some changes here to fix it.
[CONTROL.txt](https://github.com/microsoft/vcpkg/files/3440953/CONTROL.txt)

[portfile.cmake.txt](https://github.com/microsoft/vcpkg/files/3440959/portfile.cmake.txt)

**Comment by wangli28** [comment]
Hi @rotrida, can you creat a pull request to commit your changes?
Thanks!

**Comment by rotrida** [comment]
Done. Thanks!
