### ISSUE TITLE
[New Port Request] <pdqsort>

### ISSUE THREAD

**Issue by clibdev** [microsoft/vcpkg#7455]
Library name: 
pdqsort

Library description:
Pattern-defeating quicksort (pdqsort) is a novel sorting algorithm that combines the fast average case of randomized quicksort with the fast worst case of heapsort, while achieving linear time on inputs with certain patterns. pdqsort is an extension and improvement of David Mussers introsort. All code is available for free under the zlib license.

Source repository URL:
https://github.com/orlp/pdqsort

**Comment by longnguyen2004** [comment]
header only library, should be easy, just copy the library to the include folder

**Comment by wangli28** [comment]
Thanks for posting this issue! Pdqsort has been added to vcpkg, you can update vcpkg and build it.

**Comment by clibdev** [comment]
Thanks.
