### ISSUE TITLE
[cpp-redis] build failure: linux-docker

### ISSUE THREAD

**Issue by ahmedyarub** [microsoft/vcpkg#7460]
As mentioned in this issue:
https://github.com/cpp-redis/cpp_redis/issues/45

I cannot use cpp-redis in Docker, while it works in Ubuntu Bionic without any problem.

**Describe the bug**
Trying to create a Docker image for a C++ application using cpp-redis installed with VCPKG and built with CMake 13.4.5:

>  [100%] Linking CXX executable micro-service
> /usr/bin/ld: cannot find -lcpp_redis
> /usr/bin/ld: cannot find -ltacopie
> collect2: error: ld returned 1 exit status
> make[2]: *** [micro-service] Error 1

This doesn't happen on my Ubuntu 1804.

A temporary solution would be providing full path for the files like this:
```
        ${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/libcpp_redis.a
        ${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/libtacopie.a
```
For some reason I need that only in the case of cpp-redis and tacopie.

I tried using pkg-config which could find the library but I still had the same errors only in Docker:
```
find_package(PkgConfig REQUIRED)
pkg_check_modules(cpp_redis REQUIRED cpp_redis)

```
Making verbose build generates the same building command both in my Ubuntu and inside Docker. However, I get the error only in Docker:
`/usr/bin/c++  -O3 -DNDEBUG   CMakeFiles/micro-service.dir/main.cpp.o CMakeFiles/micro-service.dir/microsvc_controller.cpp.o CMakeFiles/micro-service.dir/foundation/basic_controller.cpp.o CMakeFiles/micro-service.dir/cache/redis_cache.cpp.o  -o micro-service /usr/lib64/libsoci_sqlite3.so.4.0.0 /tmp/vcpkg/installed/x64-linux/lib/libfmt.a -lcpp_redis -ltacopie /tmp/vcpkg/installed/x64-linux/lib/libhttp_parser.a /usr/lib64/libsoci_core.so.4.0.0 -lpthread /usr/lib/x86_64-linux-gnu/libdl.so /tmp/vcpkg/installed/x64-linux/lib/libsqlite3.a`

**To Reproduce**
1. Download this project https://github.com/ahmedyarub/micro-service
2. Do docker build .

**Expected behavior**
A Docker image is created without errors

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version: 4.3.1-1

**Comment by JonLiu1993** [comment]
@ahmedyarub ,Thanks for posting this issue,I'm not familiar with docker, and for the time being we don't have an environment for docker to reproduce this problem. Does this problem still exist?

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
