### ISSUE TITLE
Error compiling boost-locale:x64-linux with centos7.6

### ISSUE THREAD

**Issue by ywj11407** [microsoft/vcpkg#7470]
Additional packages (*) will be modified to complete this operation.
Starting package 1/73: boost-locale:x64-linux
Building package boost-locale[core]:x64-linux...
-- Using cached /smb/third/vcpkg/downloads/boostorg-locale-boost-1.70.0.tar.gz
-- Using source at /smb/third/vcpkg/buildtrees/boost-locale/src/ost-1.70.0-64535d0e00
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
CMake Error at installed/x64-linux/share/boost-build/boost-modular-build.cmake:93 (message):
  No libraries were produced.  This indicates a failure while building the
  boost library.
Call Stack (most recent call first):
  ports/boost-locale/portfile.cmake:20 (boost_modular_build)
  scripts/ports.cmake:74 (include)

Error: Building package boost-locale:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-locale:x64-linux
  Vcpkg version: 2019.07.18-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by ywj11407** [comment]
i had git pull ,but still have this problem

**Comment by YgabrielsY** [comment]
I have the same issue. it does not seem to be possible to get the boost libraries compiled on linux using vcpkg right now.

**Comment by PhoebeHui** [comment]
@ywj11407  @YgabrielsY, I can't repro this issue on Ubuntu 18.04, I'm not if it's an issue on centos7.6

-- Downloading https://github.com/boostorg/locale/archive/boost-1.71.0.tar.gz...
-- Extracting source /home/linux001/Phobe/vcpkg/downloads/boostorg-locale-boost-1.71.0.tar.gz
-- Using source at /home/linux001/Phobe/vcpkg/buildtrees/boost-locale/src/ost-1.71.0-ce04fa497f
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Packaging headers
-- Packaging headers done
-- Using cached /home/linux001/Phobe/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: /home/linux001/Phobe/vcpkg/packages/boost-locale_x64-linux/share/boost-locale/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-locale[core]:x64-linux... done
Installing package boost-locale[core]:x64-linux...
Installing package boost-locale[core]:x64-linux... done
Elapsed time for package boost-locale:x64-linux: 53.53 s

Total elapsed time: 53.53 s

**Comment by PhoebeHui** [comment]
@ywj11407, boost currently upgrade to 1_73, please try lastest source and reopen this PR if it still be a problem for you.
