### ISSUE TITLE
[libmariadb] Unresolved External Symbol

### ISSUE THREAD

**Issue by jmin911** [microsoft/vcpkg#7477]
**Describe the bug**
The July 24 commit breaks VC projects that uses libmariadb.  The static link of the lib fails with unresolved external symbols.

**Environment**
- OS: Windows
- Compiler: VC 2017

**To Reproduce**
1. ./vcpkg install libmariadb:x86-windows-static
2. Write VC code to use the lib.
3. Build the VC project.
4. Fails at link stage with unresolved external symbols.

**Expected behavior**
Project should build successfully.

**Failure logs** 
mariadbclient.lib(ma_client_plugin.obj) : error LNK2001: unresolved external symbol auth_gssapi_client_client_plugin

**Additional context**
It was working prior to July 24 commit.

**Comment by cbezault** [comment]
@JackBoosY it's unclear to me why #7710 would fix this issue. Could you elaborate?

**Comment by jmin911** [comment]
This issue has been fixed by #7710 .
Because some plugins were included in the static build but there were no libs to resolve some of the functions used in the plugins, creating the unresolved external symbol error.

**Comment by JackBoosY** [comment]
@cbezault Some plugins should not be added to the list and declare their function interface when statically built.
