### ISSUE TITLE
[New Port Request] libtins

### ISSUE THREAD

**Issue by realsarm** [microsoft/vcpkg#7480]
Library name: libtins

Library description: libtins is a high-level, multiplatform C++ network packet sniffing and crafting library.

Source repository URL: https://github.com/mfontanini/libtins

Project homepage (if different from the source repository): http://libtins.github.io/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by NancyLi1013** [comment]
Hi @realsarm, thanks for posting this request. This port has been added to vcpkg. https://github.com/microsoft/vcpkg/tree/master/ports/libtins 
Please try to update vcpkg to the latest version.
