### ISSUE TITLE
Adding github repos that has cmake in an automatic way

### ISSUE THREAD

**Issue by realsarm** [microsoft/vcpkg#7482]
**Is your feature request related to a problem? Please describe.**
No

**Proposed solution**
Most github libraries includes cmake or make files that could be added in a more programtic way to vcpkg.
This feature widen the usage of vcpkg.

**Comment by MikeGitb** [comment]
On the one hand, I think a vcpkg install www.github.com/foo/bar.git --head would certainly be handy, on the other hand I'm a bit sceptical how well this would work in practice. Imho it would certainly be worth it to implement it and test it on a couple of repos.

**Comment by realsarm** [comment]
Good thing about most libraries is that they provide useful cmake file that can be parsed by even the client vcpkg and turn into the vcpkg cmakes

This would certainly extend the windows development power since it is so hard to link libraries to complex c++ project without using decent package manger

This also empower github since linux and mac users can use this instead of built-in package mangers they have

**Comment by PhoebeHui** [comment]
It's a good idea ideally, however, most libraries need to be tested and solved the issues that in different platform before it supported, It may Upsteam issue or others, it depends on many factors, it costs much time to solve the problems. If there is no issue in libraries, it has no big difference to add a port automatically or not. Currently we may not interest this.
