### ISSUE TITLE
[xerces-c] produces strange files in installed/x64-linux/lib

### ISSUE THREAD

**Issue by crusader-mike** [microsoft/vcpkg#7490]
**Host Environment**
- OS: CentOS 7
- Compiler: g++ (GCC) 8.2.1 20180905 (Red Hat 8.2.1-3)

**To Reproduce**
`./vcpkg install xerces-c`

**Failure logs** 
```
$ ls -l installed/x64-linux/lib/
-rw-r--r--. 1 user user 12969802 Jul 31 15:16 libxerces-c-3.2.a
lrwxrwxrwx. 1 user user       17 Jul 31 15:16 libxerces-c.so -> libxerces-c-3.2.a
drwxrwxr-x. 2 user user       24 Jul 31 15:16 pkgconfig

$ ls -l installed/x64-linux/lib/pkgconfig/
-rw-r--r--. 1 user user 483 Jul 31 15:16 xerces-c.pc
```

Also, `config-*-err.log` files contain strange entry:
```
CMake Warning at /home/user/vcpkg/scripts/buildsystems/vcpkg.cmake:107 (message):
  There are no libraries installed for the Vcpkg triplet x64-linux.
```

**Comment by JackBoosY** [comment]
In _source\cmake\XercesDll.cmake_:23 :
```
set(BUILD_SHARED_LIBS ON CACHE BOOL "Build shared libraries")
```

Forced to set a dynamic library caused this issue.

**Comment by crusader-mike** [comment]
What is the proper way to fix it -- should I patch it so it sets this variable only if `VCPKG_LIBRARY_LINKAGE` is static? (assuming this variable is visible at that point)

Trying to avoid breaking other triplets...

**Comment by JackBoosY** [comment]
Just delete this line should fix this issue.

**Comment by crusader-mike** [comment]
Hmm... nope -- it doesn't help. Trying to figure out who creates these symlinks...

On a side note: is it ok that some packages (zstd/xerces-c/etc) create `.pc` files in `installed/x64-linux/lib/`?

**Comment by crusader-mike** [comment]
Found it in `src/CMakeLists.txt`:
```
elseif(UNIX)
  # For strict libtool compatibility on Unix.  It's a horrible hack to
  # set the version in the filename, and create the symlink at install
  # time.  Note: could be dropped when the SONAME is updated and
  # libtool compatibility is no longer required.
  set_target_properties(xerces-c PROPERTIES OUTPUT_NAME "xerces-c-${INTERFACE_VERSION_D}")
  file(GENERATE
    OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/InstallLibrarySymlink.cmake"
    CONTENT "execute_process(COMMAND ln -sf \"$<TARGET_FILE_NAME:xerces-c>\" \"\$ENV{DESTDIR}${CMAKE_INSTALL_FULL_LIBDIR}/libxerces-c.so\")")
  install(SCRIPT "${CMAKE_CURRENT_BINARY_DIR}/InstallLibrarySymlink.cmake")
```

somebody was very naughty...

**Comment by hailIulius** [comment]
Is there any way to link agains a dynamic [xercec-c] library on Linux? Now the one installed by vcpkg is a static one on linux by default

**Comment by crusader-mike** [comment]
@hailIulius here is one way to do it: https://github.com/microsoft/vcpkg/blob/master/docs/examples/overlay-triplets-linux-dynamic.md
