### ISSUE TITLE
`vcpkg export` should have output directory and --help options

### ISSUE THREAD

**Issue by strega-nil** [microsoft/vcpkg#7492]
See title: `vcpkg export --help` only works because it prints help on unknown flags:

```
PS> .\vcpkg.exe export --help
Unknown option(s) for command 'export':
    --help

Example:  vcpkg export zlib zlib:x64-windows boost --nuget
...
```

Also, having an output directory would be really nice. Currently, what one is forced to do is build the package, and then move it, as opposed to just putting it where it's needed.

**Comment by crusader-mike** [comment]
What about option "include sources"? Afaik, on windows you need them for stepping into vcpkg libraries code.

**Comment by Thomas1664** [comment]
@BillyONeal @LilyWangLL I think vcpkg now has this functionality so the issue can be closed. (help works the other way around: `vcpkg --help export`)

**Comment by LilyWangLL** [comment]
This issue has been fixed, so I am closing this issue for now.
