### ISSUE TITLE
Some ports need to be updated

### ISSUE THREAD

**Issue by ehsan-mohammadi** [microsoft/vcpkg#7495]
Here is a list of some ports that need to be updated (Some ports has been checked; means that they are updated now):

- - [x] `ade` **MERGED**
- - [ ] `aws-c-common`
- - [ ] `aws-lambda-cpp`
- - [x] `blosc` **MERGED**
- - [x] `boost-callable-traits` **MERGED**
- - [ ] `boost-contract`
- - [ ] `boost-hana`
- - [ ] `boost-histogram`
- - [ ] `boost-outcome`
- - [x] `brynet` **MERGED**
- - [ ] `caf`
- - [ ] `casclib`
- - [x] `catch2` **MERGED**
- - [x] `chakracore` **MERGED**
- - [x] `cjson` **MERGED**
- - [x] `clp` **MERGED**
- - [x] `console-bridge`
- - [x] `coroutine`
- - [x] `cppzmq` **MERGED**
- - [ ] `curl`
- - [ ] `dimcli` **MERGED**
- - [x] `directxmesh` **MERGED**
- - [x] `directxtex` **MERGED**
- - [x] `directxtk` **MERGED**
- - [x] `double-conversion` **MERGED**
- - [x] `duktape`
- - [ ] `exiv2`
- - [x] `expat` **MERGED**
- - [x] `fastcdr`
- - [ ] `gdcm`
- - [x] `graphite2`
- - [x] `harfbuzz` **MERGED**
- - [ ] `hwloc`
- - [x] `imgui` **MERGED**
- - [x] `itk`
- - [x] `jsoncons` **MERGED**
- - [x] `jsoncpp` **MERGED**
- - [x] `kangaru` **MERGED**
- - [ ] `leptonica`
- - [x] `libarchive`
- - [ ] `libfabric` **MERGED**
- - [x] `libffi`
- - [ ] `libideviceactivation`
- - [x] `libmodbus` **MERGED**
- - [x] `libpmemobj-cpp` **MERGED**
- - [x] `libpqxx`
- - [x] `libssh2`
- - [ ] `libusb`
- - [ ] `matio`
- - [x] `mbedtls` **MERGED**
- - [ ] `mozjpeg`
- - [x] `msgpack` **MERGED**
- - [ ] `openimageio`
- - [ ] `openmvg`
- - [x] `protobuf` **MERGED**
- - [ ] `sentencepiece`
- - [x] `shogun`
- - [ ] `spdk`
- - [x] `spectra` **MERGED**
- - [x] `string-theory` **MERGED**
- - [x] `telnetpp`

**Comment by PhoebeHui** [comment]
PR https://github.com/microsoft/vcpkg/pull/7217 might contains some of them.

**Comment by ehsan-mohammadi** [comment]
> PR #7217 might contains some of them.

Thanks. I'll check this PR and update my issue.

**Comment by driver1998** [comment]
You may also want to check out https://github.com/microsoft/vcpkg/pull/6119.

**Comment by smkanadl** [comment]
#7834 contains an update to libmodbus.

**Comment by ehsan-mohammadi** [comment]
@driver1998 @smkanadl Many thanks!
