### ISSUE TITLE
[New Port Request] <DuckX>

### ISSUE THREAD

**Issue by amir1376irani** [microsoft/vcpkg#7498]
Library name: DuckX

Library description: C++ library for creating and updating Microsoft Word (.docx) files

Source repository URL: https://github.com/amiremohamadi/DuckX

**Comment by ehsan-mohammadi** [comment]
@amir1376irani `DuckX` merged. Please close the issue.

**Comment by wangli28** [comment]
Thanks for posting this issue. Duckx has been added to vcpkg. So I am closing this issue for now.
