### ISSUE TITLE
Boost picks up site-config, which will break builds

### ISSUE THREAD

**Issue by MikeGitb** [Microsoft/vcpkg#75]
I can't instal boost on my machine (Win10, VS2015 U3) it seems as if the build script expects a g++ compiler.

This is the output from powershell:

> -- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
  Command failed:
  C:/xTools/vcpkg/vcpkg/buildtrees/boost/src/boost_1_61_0/b2.exe;--stagedir=C:/xTools/vcpkg/vcpkg/buildtrees/boost/x64-windows-rel/stage;--build-dir=C:/xTools/vcpkg/vcpkg/buildtrees/boost/x64-windows-rel;--toolset=msvc;-j4;-q;--without-python;threading=multi;link=shared;runtime-link=shared;--debug-configuration;address-model=64;variant=release
>
>
>  Working Directory: C:/xTools/vcpkg/vcpkg/buildtrees/boost/src/boost_1_61_0
>
>  See logs for more information:
>
>      C:\xTools\vcpkg\vcpkg\buildtrees\boost\build-x64-windows-rel-out.log
>      C:\xTools\vcpkg\vcpkg\buildtrees\boost\build-x64-windows-rel-err.log
>
>  Call Stack (most recent call first):
>  ports/boost/portfile.cmake:38 (vcpkg_execute_required_process)
>  scripts/ports.cmake:84 (include)`

> Error: build command failed

And this is the content of `C:\xTools\vcpkg\vcpkg\buildtrees\boost\build-x64-windows-rel-out.log`

> notice: found boost-build.jam at C:/xTools/vcpkg/vcpkg/buildtrees/boost/src/boost_1_61_0/boost-build.jam
notice: loading Boost.Build from C:/xTools/vcpkg/vcpkg/buildtrees/boost/src/boost_1_61_0/tools/build/src
notice: Searching 'C:\WINDOWS' [...] 'C:\xTools\vcpkg\vcpkg\buildtrees\boost\src\boost_1_61_0\tools/build/src' 'C:/xTools/vcpkg/vcpkg/buildtrees/boost/src/boost_1_61_0/tools/build/src/kernel' 'C:/xTools/vcpkg/vcpkg/buildtrees/boost/src/boost_1_61_0/tools/build/src/util' 'C:/xTools/vcpkg/vcpkg/buildtrees/boost/src/boost_1_61_0/tools/build/src/build' 'C:/xTools/vcpkg/vcpkg/buildtrees/boost/src/boost_1_61_0/tools/build/src/tools' 'C:/xTools/vcpkg/vcpkg/buildtrees/boost/src/boost_1_61_0/tools/build/src/contrib' 'C:/xTools/vcpkg/vcpkg/buildtrees/boost/src/boost_1_61_0/tools/build/src/.' for site-config configuration file 'site-config.jam'.
notice: Loading site-config configuration file 'site-config.jam' from 'C:/Users/<user>'.
warning: toolset gcc initialization: can not find tool g++
warning: initialized from C:\Users\<user>l\site-config.jam:1
C:/xTools/vcpkg/vcpkg/buildtrees/boost/src/boost_1_61_0/tools/build/src/tools\gcc.jam:150: in gcc.init from module gcc
error: toolset gcc initialization:
error: no command provided, default command 'g++' not found
error: initialized from C:\Users\<user>\site-config.jam:1
C:/xTools/vcpkg/vcpkg/buildtrees/boost/src/boost_1_61_0/tools/build/src/build\toolset.jam:43: in toolset.using from module toolset
C:/xTools/vcpkg/vcpkg/buildtrees/boost/src/boost_1_61_0/tools/build/src/build\project.jam:1052: in using from module project-rules
C:\Users\<user>\site-config.jam:1: in modules.load from module site-config
C:/xTools/vcpkg/vcpkg/buildtrees/boost/src/boost_1_61_0/tools/build/src\build-system.jam:249: in load-config from module build-system
C:/xTools/vcpkg/vcpkg/buildtrees/boost/src/boost_1_61_0/tools/build/src\build-system.jam:351: in load-configuration-files from module build-system
C:/xTools/vcpkg/vcpkg/buildtrees/boost/src/boost_1_61_0/tools/build/src\build-system.jam:524: in load from module build-system
C:\xTools\vcpkg\vcpkg\buildtrees\boost\src\boost_1_61_0\tools\build\src/kernel\modules.jam:295: in import from module modules
C:\xTools\vcpkg\vcpkg\buildtrees\boost\src\boost_1_61_0\tools\build\src/kernel/bootstrap.jam:139: in boost-build from module
C:\xTools\vcpkg\vcpkg\buildtrees\boost\src\boost_1_61_0\boost-build.jam:17: in module scope from module

**Comment by ras0219-msft** [comment]
Thanks for posting the logs!

I think this is the problem:

> notice: Loading site-config configuration file 'site-config.jam' from 'C:/Users/'.
> warning: toolset gcc initialization: can not find tool g++
> warning: initialized from C:\Users<user>l\site-config.jam:1
> C:/xTools/vcpkg/vcpkg/buildtrees/boost/src/boost_1_61_0/tools/build/src/tools\gcc.jam:150: in gcc.init from module gcc
> error: toolset gcc initialization:
> error: no command provided, default command 'g++' not found
> error: initialized from C:\Users<user>\site-config.jam:1

To immediately fix this, rename your `C:\Users<user>l\site-config.jam` to something else. We should fix the portfile to suppress picking up the `site-config.jam`.

**Comment by MikeGitb** [comment]
Thank you very much! That solved the problem. Must have been a leftover from a previous boost installation. As far as I'm concerned this issue can be closed or do you want to keep this open?
