### ISSUE TITLE
pkgconfig subdirectory in installed/x64-linux/lib

### ISSUE THREAD

**Issue by crusader-mike** [microsoft/vcpkg#7504]
Some projects (`zstd`/`xerces-c`/etc) put `.pc` files into `installed/x64-linux/lib/pkgconfig` and `installed/x64-linux/debug/lib/pkgconfig`.

What is the purpose of these files? Do they have to be removed during port install? Why they get generated in two places?

**Comment by Voskrese** [comment]
https://www.google.com/search?client=firefox-b-d&q=pkgconfig

**Comment by crusader-mike** [comment]
@Voskrese, huh... I've never heard of this "google" service. It looks useful. Thanks! :-)

I asked because port isn't supposed to generate `shared` directory in `debug` (validation fails), but having `pkgconfig` in two places doesn't trigger validation logic. Was curious for reasons why.

**Comment by Voskrese** [comment]
windows !

vcpkg\installed\x64-windows\bin>`pkg-config  --variable pc_path pkg-config`

> ../lib/pkgconfig;../share/pkgconfig

`pkg-config --libs --cflags glib-2.0`

> -IE:/tools/vcpkg/installed/x64-windows/bin/../include/glib-2.0 -IE:/tools/vcpkg/installed/x64-windows/bin/../lib/glib-2.0/include -lintl -LE:/tools/vcpkg/installed/x64-windows/bin/../lib -lglib-2.0

https://www.google.com/search?client=firefox-b-d&q=pkgconfig
-->>
https://www.freedesktop.org/wiki/Software/pkg-config/

example

`-Dpkg_config_path=${CURRENT_INSTALLED_DIR}/debug/lib/pkgconfig,${CURRENT_INSTALLED_DIR}/debug/share/pkgconfig`
`set(ENV{PKG_CONFIG_PATH} "${CURRENT_INSTALLED_DIR}/lib/pkgconfig/${_SEP}$ENV{PKG_CONFIG_PATH}")`

**Comment by crusader-mike** [comment]
I see... Thanks!

> what exactly in the official documentation is not clear?

I am still in the middle of reading it, but once am I done -- I'll send you a list of questions. ;-)
