### ISSUE TITLE
[qscintilla] Add targets

### ISSUE THREAD

**Issue by stijnherfst** [microsoft/vcpkg#7507]
It seems that qscintilla does not have any cmake targets and thus cannot be included in a project without manually hardcoding the paths. I've looked into adding this myself, but I'm unfamiliar with qmake and how to handle it here.

**Comment by NancyLi1013** [comment]
Hi @stijnherfst 
Thanks for posting this issue.
As far as I have known, `qscintilla` is built by `qmake `instead of `cmake`.
It seems that it's not possible to add `cmake `targets for the port that is built by `qcmake`.

**Comment by NancyLi1013** [comment]
I'm going to close this issue for now. 
Please open a new issue if you have other requirements about `qscintilla`.
