### ISSUE TITLE
[libpq] build failure

### ISSUE THREAD

**Issue by silentmissile** [microsoft/vcpkg#7513]
**Host Environment**
- OS: [Windows]
- Compiler: MSVC2017

**To Reproduce**
`./vcpkg install libpq`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
PS F:\Source\vcpkg-master> .\vcpkg.exe install libpq:x64-windows
The following packages will be built and installed:
    libpq[core]:x64-windows
Starting package 1/1: libpq:x64-windows
Building package libpq[core]:x64-windows...
-- Using cached F:/Source/vcpkg-master/downloads/postgresql-9.6.3.tar.bz2
-- Using source at F:/Source/vcpkg-master/buildtrees/libpq/src/stgresql-9-d40671c654
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "D:/Program Files/cmake/bin/cmake.exe" --build . --config Debug --target install -- -v
    Working Directory: F:/Source/vcpkg-master/buildtrees/libpq/x64-windows-dbg
    See logs for more information:
      F:\Source\vcpkg-master\buildtrees\libpq\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/libpq/portfile.cmake:29 (vcpkg_install_cmake)
  scripts/ports.cmake:74 (include)

Error: Building package libpq:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libpq:x64-windows
  Vcpkg version: 2019.07.18-nohash

Additionally, attach any relevant sections from the log files above.

-Please attach any additional failure logs mentioned in the console output.
error message in buildtree\libpq\install-x64-windows-dbg-out.log

F:\Source\vcpkg-master\buildtrees\libpq\src\stgresql-9-d40671c654\src\interfaces\libpq\win32.c(311): warning C4267: 'function': conversion from 'size_t' to 'DWORD', possible loss of data
F:\Source\vcpkg-master\buildtrees\libpq\src\stgresql-9-d40671c654\src\interfaces\libpq\win32.c(321): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
F:\Source\vcpkg-master\buildtrees\libpq\src\stgresql-9-d40671c654\src\interfaces\libpq\win32.c(323): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
[38/39] cmd.exe /C "cmd.exe /C ""D:\Program Files\cmake\bin\cmake.exe" -E __create_def F:\Source\vcpkg-master\buildtrees\libpq\x64-windows-dbg\CMakeFiles\libpq.dir\exports.def F:\Source\vcpkg-master\buildtrees\libpq\x64-windows-dbg\CMakeFiles\libpq.dir\exports.def.objs && cd F:\Source\vcpkg-master\buildtrees\libpq\x64-windows-dbg" && "D:\Program Files\cmake\bin\cmake.exe" -E vs_link_dll --intdir=CMakeFiles\libpq.dir --rc="D:\Windows Kits\10\bin\10.0.17763.0\x64\rc.exe" --mt="D:\Windows Kits\10\bin\10.0.17763.0\x64\mt.exe" --manifests  -- "D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\link.exe"  CMakeFiles\libpq.dir\src\port\pgstrcasecmp.c.obj CMakeFiles\libpq.dir\src\port\pqsignal.c.obj CMakeFiles\libpq.dir\src\port\thread.c.obj CMakeFiles\libpq.dir\src\port\crypt.c.obj CMakeFiles\libpq.dir\src\port\noblock.c.obj CMakeFiles\libpq.dir\src\port\chklocale.c.obj CMakeFiles\libpq.dir\src\port\snprintf.c.obj CMakeFiles\libpq.dir\src\port\dirmod.c.obj CMakeFiles\libpq.dir\src\port\pgsleep.c.obj CMakeFiles\libpq.dir\src\port\open.c.obj CMakeFiles\libpq.dir\src\port\system.c.obj CMakeFiles\libpq.dir\src\port\dirent.c.obj CMakeFiles\libpq.dir\src\port\inet_aton.c.obj CMakeFiles\libpq.dir\src\port\inet_net_ntop.c.obj CMakeFiles\libpq.dir\src\port\win32error.c.obj CMakeFiles\libpq.dir\src\port\win32setlocale.c.obj CMakeFiles\libpq.dir\src\port\getaddrinfo.c.obj CMakeFiles\libpq.dir\src\port\strlcpy.c.obj CMakeFiles\libpq.dir\src\backend\libpq\md5.c.obj CMakeFiles\libpq.dir\src\backend\libpq\ip.c.obj CMakeFiles\libpq.dir\src\backend\utils\mb\wchar.c.obj CMakeFiles\libpq.dir\src\backend\utils\mb\encnames.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-auth.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-connect.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-exec.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-lobj.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-misc.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-print.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-protocol2.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-protocol3.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-secure-openssl.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-secure.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\libpq-events.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\pqexpbuffer.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\libpq-dist.rc.res CMakeFiles\libpq.dir\src\interfaces\libpq\pthread-win32.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\win32.c.obj  /out:libpqd.dll /implib:libpqd.lib /pdb:libpqd.pdb /dll /version:0.0 /machine:x64 /debug /INCREMENTAL  /DEF:CMakeFiles\libpq.dir\exports.def  "D:\Program Files\OpenSSL-Win64\lib\VC\libssl64MDd.lib" ws2_32.lib secur32.lib advapi32.lib shell32.lib crypt32.lib "D:\Program Files\OpenSSL-Win64\lib\VC\libcrypto64MDd.lib" kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd ."
FAILED: libpqd.dll libpqd.lib 
cmd.exe /C "cmd.exe /C ""D:\Program Files\cmake\bin\cmake.exe" -E __create_def F:\Source\vcpkg-master\buildtrees\libpq\x64-windows-dbg\CMakeFiles\libpq.dir\exports.def F:\Source\vcpkg-master\buildtrees\libpq\x64-windows-dbg\CMakeFiles\libpq.dir\exports.def.objs && cd F:\Source\vcpkg-master\buildtrees\libpq\x64-windows-dbg" && "D:\Program Files\cmake\bin\cmake.exe" -E vs_link_dll --intdir=CMakeFiles\libpq.dir --rc="D:\Windows Kits\10\bin\10.0.17763.0\x64\rc.exe" --mt="D:\Windows Kits\10\bin\10.0.17763.0\x64\mt.exe" --manifests  -- "D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\link.exe"  CMakeFiles\libpq.dir\src\port\pgstrcasecmp.c.obj CMakeFiles\libpq.dir\src\port\pqsignal.c.obj CMakeFiles\libpq.dir\src\port\thread.c.obj CMakeFiles\libpq.dir\src\port\crypt.c.obj CMakeFiles\libpq.dir\src\port\noblock.c.obj CMakeFiles\libpq.dir\src\port\chklocale.c.obj CMakeFiles\libpq.dir\src\port\snprintf.c.obj CMakeFiles\libpq.dir\src\port\dirmod.c.obj CMakeFiles\libpq.dir\src\port\pgsleep.c.obj CMakeFiles\libpq.dir\src\port\open.c.obj CMakeFiles\libpq.dir\src\port\system.c.obj CMakeFiles\libpq.dir\src\port\dirent.c.obj CMakeFiles\libpq.dir\src\port\inet_aton.c.obj CMakeFiles\libpq.dir\src\port\inet_net_ntop.c.obj CMakeFiles\libpq.dir\src\port\win32error.c.obj CMakeFiles\libpq.dir\src\port\win32setlocale.c.obj CMakeFiles\libpq.dir\src\port\getaddrinfo.c.obj CMakeFiles\libpq.dir\src\port\strlcpy.c.obj CMakeFiles\libpq.dir\src\backend\libpq\md5.c.obj CMakeFiles\libpq.dir\src\backend\libpq\ip.c.obj CMakeFiles\libpq.dir\src\backend\utils\mb\wchar.c.obj CMakeFiles\libpq.dir\src\backend\utils\mb\encnames.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-auth.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-connect.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-exec.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-lobj.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-misc.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-print.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-protocol2.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-protocol3.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-secure-openssl.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-secure.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\libpq-events.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\pqexpbuffer.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\libpq-dist.rc.res CMakeFiles\libpq.dir\src\interfaces\libpq\pthread-win32.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\win32.c.obj  /out:libpqd.dll /implib:libpqd.lib /pdb:libpqd.pdb /dll /version:0.0 /machine:x64 /debug /INCREMENTAL  /DEF:CMakeFiles\libpq.dir\exports.def  "D:\Program Files\OpenSSL-Win64\lib\VC\libssl64MDd.lib" ws2_32.lib secur32.lib advapi32.lib shell32.lib crypt32.lib "D:\Program Files\OpenSSL-Win64\lib\VC\libcrypto64MDd.lib" kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd ."
LINK Pass 1: command "D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\link.exe CMakeFiles\libpq.dir\src\port\pgstrcasecmp.c.obj CMakeFiles\libpq.dir\src\port\pqsignal.c.obj CMakeFiles\libpq.dir\src\port\thread.c.obj CMakeFiles\libpq.dir\src\port\crypt.c.obj CMakeFiles\libpq.dir\src\port\noblock.c.obj CMakeFiles\libpq.dir\src\port\chklocale.c.obj CMakeFiles\libpq.dir\src\port\snprintf.c.obj CMakeFiles\libpq.dir\src\port\dirmod.c.obj CMakeFiles\libpq.dir\src\port\pgsleep.c.obj CMakeFiles\libpq.dir\src\port\open.c.obj CMakeFiles\libpq.dir\src\port\system.c.obj CMakeFiles\libpq.dir\src\port\dirent.c.obj CMakeFiles\libpq.dir\src\port\inet_aton.c.obj CMakeFiles\libpq.dir\src\port\inet_net_ntop.c.obj CMakeFiles\libpq.dir\src\port\win32error.c.obj CMakeFiles\libpq.dir\src\port\win32setlocale.c.obj CMakeFiles\libpq.dir\src\port\getaddrinfo.c.obj CMakeFiles\libpq.dir\src\port\strlcpy.c.obj CMakeFiles\libpq.dir\src\backend\libpq\md5.c.obj CMakeFiles\libpq.dir\src\backend\libpq\ip.c.obj CMakeFiles\libpq.dir\src\backend\utils\mb\wchar.c.obj CMakeFiles\libpq.dir\src\backend\utils\mb\encnames.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-auth.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-connect.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-exec.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-lobj.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-misc.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-print.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-protocol2.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-protocol3.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-secure-openssl.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\fe-secure.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\libpq-events.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\pqexpbuffer.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\libpq-dist.rc.res CMakeFiles\libpq.dir\src\interfaces\libpq\pthread-win32.c.obj CMakeFiles\libpq.dir\src\interfaces\libpq\win32.c.obj /out:libpqd.dll /implib:libpqd.lib /pdb:libpqd.pdb /dll /version:0.0 /machine:x64 /debug /INCREMENTAL /DEF:CMakeFiles\libpq.dir\exports.def D:\Program Files\OpenSSL-Win64\lib\VC\libssl64MDd.lib ws2_32.lib secur32.lib advapi32.lib shell32.lib crypt32.lib D:\Program Files\OpenSSL-Win64\lib\VC\libcrypto64MDd.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\libpq.dir/intermediate.manifest CMakeFiles\libpq.dir/manifest.res" failed (exit code 1120) with the following output:
Microsoft (R) Incremental Linker Version 14.16.27032.1
Copyright (C) Microsoft Corporation.  All rights reserved.

   Creating library libpqd.lib and object libpqd.exp
fe-secure-openssl.c.obj : error LNK2019: unresolved external symbol sk_num referenced in function verify_peer_name_matches_certificate
fe-secure-openssl.c.obj : error LNK2019: unresolved external symbol sk_value referenced in function verify_peer_name_matches_certificate
fe-secure-openssl.c.obj : error LNK2019: unresolved external symbol sk_free referenced in function verify_peer_name_matches_certificate
fe-secure-openssl.c.obj : error LNK2019: unresolved external symbol SSL_load_error_strings referenced in function pgtls_init
fe-secure-openssl.c.obj : error LNK2019: unresolved external symbol SSLv23_method referenced in function initialize_SSL
fe-secure-openssl.c.obj : error LNK2019: unresolved external symbol SSL_library_init referenced in function pgtls_init
libpqd.dll : fatal error LNK1120: 6 unresolved externals
ninja: build stopped: subcommand failed.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Voskrese** [comment]
`D:\Program Files\OpenSSL-Win64\lib\VC\libssl64MDd.lib ws2_32.lib secur32.lib advapi32.lib shell32.lib crypt32.lib D:\Program Files\OpenSSL-Win64\lib\VC\libcrypto64MDd.lib`

**delete** `D:\Program Files\OpenSSL-Win64`

**Comment by silentmissile** [comment]
thank you, I should remove the previous openssl installation

it's resolved
