### ISSUE TITLE
Debug build of libflac fails

### ISSUE THREAD

**Issue by Drako** [Microsoft/vcpkg#752]
The debug build fails with the following linker error:

cpu.c.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_FLAC__cpu_info_asm_ia32" in Funktion "_ia32_cpu_info".

(unresolved external symbol for the non German folks)

**Comment by codicodi** [comment]
Looks like a little upstream regression - previous version (FLAC-1.3.1) checked if nasm is available (`#ifdef FLAC__HAS_NASM...`) before calling any assembly routines. While solution proposed in #732 should work fine, I think the best way to handle this would be to acquire nasm and simply add assembly sources to generated project.

**Comment by Drako** [comment]
Hm, I'll have to see how to do that with CMake/the port file.

**Comment by Drako** [comment]
I just installed the x64 version of nasm and added it to PATH.

While installing libflac x64-windows worked, the old error from above still came with x86.
(probably because ia32 = x86)

The nasm version (x86 vs x64) should not really matter as both are capable of creating object files of the opposite architecture.
So I'm still wondering how to get that working without disabling assembly for x86.

**Comment by codicodi** [comment]
Vcpkg has a mechanism for downloading tools automatically - `vcpkg_find_acquire_program`.
Take a look at https://github.com/codicodi/vcpkg/commit/c24afa97a20600048a249eb74184031ee6b6de24, this should do the trick.

**Comment by Drako** [comment]
Ah, that's nice.
Okay, I also didn't think of adding the assembly sources to cmake.

As your solution seems to solve the issue far better than mine I'll close my pull request.
