### ISSUE TITLE
[thrift:x64-osx] build failure

### ISSUE THREAD

**Issue by esride-jts** [microsoft/vcpkg#7533]
[install-x64-osx-dbg-out.log](https://github.com/microsoft/vcpkg/files/3463784/install-x64-osx-dbg-out.log)
**Host Environment**
- OS: MacOS High Sierra
- Compiler: Apple LLVM version 9.1.0 (clang-902.0.39.2)

**To Reproduce**
`./vcpkg install thrift:x64-osx`

**Failure logs** 
Building package thrift[core]:x64-osx...
-- Using cached /Users/jts/Projects/Microsoft/vcpkg/downloads/apache-thrift-acdd4226c210336e9e15eb812e5932a645fcd5ce.tar.gz
-- Using source at /Users/jts/Projects/Microsoft/vcpkg/buildtrees/thrift/src/a645fcd5ce-c6651aaf0e
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: /Users/jts/Projects/Microsoft/vcpkg/downloads/tools/cmake-3.14.0-osx/cmake-3.14.0-Darwin-x86_64/CMake.app/Contents/bin/cmake --build . --config Debug --target install -- -v
    Working Directory: /Users/jts/Projects/Microsoft/vcpkg/buildtrees/thrift/x64-osx-dbg
    See logs for more information:
      /Users/jts/Projects/Microsoft/vcpkg/buildtrees/thrift/install-x64-osx-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/thrift/portfile.cmake:43 (vcpkg_install_cmake)
  scripts/ports.cmake:74 (include)

Error: Building package thrift:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: thrift:x64-osx
  Vcpkg version: 2019.07.18-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by jgiannuzzi** [comment]
This happens because the version of bison provided on macOS is outdated (2.3). Thrift requires at least version 2.5.

A solution for building thrift with vcpkg is to install a newer version of bison with homebrew, and then put it in the PATH:

```
brew install bison
PATH="/usr/local/opt/bison/bin:$PATH" ./vcpkg install thrift:x64-osx
```

Ideally, vcpkg should download its own copy of bison on macOS, like [it does on Windows](https://github.com/microsoft/vcpkg/blob/c7ab9d3110813979a873b2dbac630a9ab79850dc/scripts/cmake/vcpkg_find_acquire_program.cmake#L230).
