### ISSUE TITLE
[<opencv-contrib>] <add tracking and bgsub module>

### ISSUE THREAD

**Issue by Amin-Tgz** [microsoft/vcpkg#7539]
Some contrib module doesn't exist in OpenCV-contrib port like
[background subtraction](https://github.com/opencv/opencv_contrib/tree/master/modules/bgsegm) or [tracking ](https://github.com/opencv/opencv_contrib/tree/master/modules/tracking)and they are crucial for some projects.
Plz add them 😭
thanks in advance ❤️👌

**Comment by MonicaLiu0311** [comment]
vcpkg does not have this port at present, close this issue.
