### ISSUE TITLE
[cpprestsdk]:x86-uwp/x64-uwp build failure in VS2019

### ISSUE THREAD

**Issue by shashi4u** [microsoft/vcpkg#7540]
**Host Environment**
- OS: Windows
- Compiler: Build Tools v142

**To Reproduce**
`vcpkg install cpprestsdk:x86-uwp`
or
`vcpkg install cpprestsdk:x64-uwp`

**Failure logs** 
**c:\vcpkg>vcpkg.exe install cpprestsdk:x86-uwp**
The following packages will be built and installed:
    cpprestsdk[core,default-features,websockets]:x86-uwp
  * zlib[core]:x86-uwp
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: zlib:x86-uwp
Building package zlib[core]:x86-uwp...
-- Using cached C:/vcpkg/downloads/zlib1211.tar.gz
-- Using source at C:/vcpkg/buildtrees/zlib/src/1.2.11-f690224aeb
-- Configuring x86-uwp
-- Building x86-uwp-dbg
-- Building x86-uwp-rel
-- Installing: C:/vcpkg/packages/zlib_x86-uwp/share/zlib/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package zlib[core]:x86-uwp... done
Installing package zlib[core]:x86-uwp...
Installing package zlib[core]:x86-uwp... done
Elapsed time for package zlib:x86-uwp: 43.71 s
Starting package 2/2: cpprestsdk:x86-uwp
Building package cpprestsdk[core,default-features,websockets]:x86-uwp...
-- Using cached C:/vcpkg/downloads/Microsoft-cpprestsdk-v2.10.14.tar.gz
-- Using source at C:/vcpkg/buildtrees/cpprestsdk/src/v2.10.14-101423beaf
-- Configuring x86-uwp
-- Building x86-uwp-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-w
in32-x86/bin/cmake.exe --build . --config Debug --target install -- /p:VCPkgLoca
lAppDataDisabled=true /p:UseIntelMKL=No /m
    Working Directory: C:/vcpkg/buildtrees/cpprestsdk/x86-uwp-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\cpprestsdk\install-x86-uwp-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/cpprestsdk/portfile.cmake:43 (vcpkg_install_cmake)
  scripts/ports.cmake:74 (include)

Error: Building package cpprestsdk:x86-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cpprestsdk:x86-uwp
  Vcpkg version: 2019.07.18-nohash

**Log File:** [install-x86-uwp-dbg-out.log](https://github.com/microsoft/vcpkg/files/3464633/install-x86-uwp-dbg-out.log)

**c:\vcpkg>vcpkg.exe install cpprestsdk:x64-uwp**
The following packages will be built and installed:
    cpprestsdk[core,default-features,websockets]:x64-uwp
  * zlib[core]:x64-uwp
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: zlib:x64-uwp
Building package zlib[core]:x64-uwp...
-- Using cached C:/vcpkg/downloads/zlib1211.tar.gz
-- Using source at C:/vcpkg/buildtrees/zlib/src/1.2.11-f690224aeb
-- Configuring x64-uwp
-- Building x64-uwp-dbg
-- Building x64-uwp-rel
-- Installing: C:/vcpkg/packages/zlib_x64-uwp/share/zlib/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package zlib[core]:x64-uwp... done
Installing package zlib[core]:x64-uwp...
Installing package zlib[core]:x64-uwp... done
Elapsed time for package zlib:x64-uwp: 53.26 s
Starting package 2/2: cpprestsdk:x64-uwp
Building package cpprestsdk[core,default-features,websockets]:x64-uwp...
-- Using cached C:/vcpkg/downloads/Microsoft-cpprestsdk-v2.10.14.tar.gz
-- Using source at C:/vcpkg/buildtrees/cpprestsdk/src/v2.10.14-101423beaf
-- Configuring x64-uwp
-- Building x64-uwp-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-w
in32-x86/bin/cmake.exe --build . --config Debug --target install -- /p:VCPkgLoca
lAppDataDisabled=true /p:UseIntelMKL=No /m
    Working Directory: C:/vcpkg/buildtrees/cpprestsdk/x64-uwp-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\cpprestsdk\install-x64-uwp-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/cpprestsdk/portfile.cmake:43 (vcpkg_install_cmake)
  scripts/ports.cmake:74 (include)

Error: Building package cpprestsdk:x64-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cpprestsdk:x64-uwp
  Vcpkg version: 2019.07.18-nohash

**Log File:** [install-x64-uwp-dbg-out.log](https://github.com/microsoft/vcpkg/files/3464634/install-x64-uwp-dbg-out.log)

**Comment by Voskrese** [comment]
```
         c1xx: error C2338: two-phase name lookup is not supported for C++/CLI, C++/CX, or OpenMP; use /Zc:twoPhase-
         c1xx: fatal error C1903: unable to recover from previous error(s); stopping compilation
```

**Comment by ahmedyarub** [comment]
I'm getting this:

> LINK : warning LNK4044: unrecognized option '/LD:/cpp/vcpkg/installed/x64-windows/debug/lib'; ignored
> LINK : warning LNK4044: unrecognized option '/lbrotlidec'; ignored
> LINK : warning LNK4044: unrecognized option '/LD:/cpp/vcpkg/installed/x64-windows/debug/lib'; ignored
> LINK : warning LNK4044: unrecognized option '/lbrotlienc'; ignored
>    Creating library Binaries\cpprest_2_10d.lib and object Binaries\cpprest_2_10d.exp
> http_compression.cpp.obj : error LNK2019: unresolved external symbol BrotliDecoderCreateInstance referenced in function "public: virtual void __cdecl web::http::compression::builtin::brotli_decompressor::reset(void)" (?reset@brotli_decompressor@builtin@compression@http@web@@UEAAXXZ)
> http_compression.cpp.obj : error LNK2019: unresolved external symbol BrotliDecoderDestroyInstance referenced in function "public: virtual __cdecl web::http::compression::builtin::brotli_decompressor::~brotli_decompressor(void)" (??1brotli_decompressor@builtin@compression@http@web@@UEAA@XZ)
> http_compression.cpp.obj : error LNK2019: unresolved external symbol BrotliDecoderDecompressStream referenced in function "public: virtual unsigned __int64 __cdecl web::http::compression::builtin::brotli_decompressor::decompress(unsigned char const *,unsigned __int64,unsigned char *,unsigned __int64,enum web::http::compression::operation_hint,unsigned __int64 &,bool &)" (?decompress@brotli_decompressor@builtin@compression@http@web@@UEAA_KPEBE_KPEAE1W4operation_hint@345@AEA_KAEA_N@Z)
> http_compression.cpp.obj : error LNK2019: unresolved external symbol BrotliEncoderSetParameter referenced in function "public: virtual void __cdecl web::http::compression::builtin::brotli_compressor::reset(void)" (?reset@brotli_compressor@builtin@compression@http@web@@UEAAXXZ)
> http_compression.cpp.obj : error LNK2019: unresolved external symbol BrotliEncoderCreateInstance referenced in function "public: virtual void __cdecl web::http::compression::builtin::brotli_compressor::reset(void)" (?reset@brotli_compressor@builtin@compression@http@web@@UEAAXXZ)
> http_compression.cpp.obj : error LNK2019: unresolved external symbol BrotliEncoderDestroyInstance referenced in function "public: virtual __cdecl web::http::compression::builtin::brotli_compressor::~brotli_compressor(void)" (??1brotli_compressor@builtin@compression@http@web@@UEAA@XZ)
> http_compression.cpp.obj : error LNK2019: unresolved external symbol BrotliEncoderCompressStream referenced in function "public: virtual unsigned __int64 __cdecl web::http::compression::builtin::brotli_compressor::compress(unsigned char const *,unsigned __int64,unsigned char *,unsigned __int64,enum web::http::compression::operation_hint,unsigned __int64 &,bool &)" (?compress@brotli_compressor@builtin@compression@http@web@@UEAA_KPEBE_KPEAE1W4operation_hint@345@AEA_KAEA_N@Z)
> http_compression.cpp.obj : error LNK2019: unresolved external symbol BrotliEncoderIsFinished referenced in function "public: virtual unsigned __int64 __cdecl web::http::compression::builtin::brotli_compressor::compress(unsigned char const *,unsigned __int64,unsigned char *,unsigned __int64,enum web::http::compression::operation_hint,unsigned __int64 &,bool &)" (?compress@brotli_compressor@builtin@compression@http@web@@UEAA_KPEBE_KPEAE1W4operation_hint@345@AEA_KAEA_N@Z)
> http_compression.cpp.obj : error LNK2019: unresolved external symbol BrotliEncoderHasMoreOutput referenced in function "public: virtual unsigned __int64 __cdecl web::http::compression::builtin::brotli_compressor::compress(unsigned char const *,unsigned __int64,unsigned char *,unsigned __int64,enum web::http::compression::operation_hint,unsigned __int64 &,bool &)" (?compress@brotli_compressor@builtin@compression@http@web@@UEAA_KPEBE_KPEAE1W4operation_hint@345@AEA_KAEA_N@Z)
> Binaries\cpprest_2_10d.dll : fatal error LNK1120: 9 unresolved externals
> ninja: build stopped: subcommand failed.

**Comment by Rastaban** [comment]
PR upstream to address C2338 https://github.com/microsoft/cpprestsdk/pull/1248

**Comment by mediabuff** [comment]
Is there a fix for x86-uwp

**Comment by PhoebeHui** [comment]
@mediabuff, you can temporarily work around by removing  'add_compile_options(/permissive-)' in line#193 on Release\CMakeLists.txt in cpprestsdk before this issue solved.

**Comment by strega-nil** [comment]
Hey @mediabuff, you should be able to update vcpkg and use cpprestsdk now thanks to @BillyONeal and @JackBoosY 😄
