### ISSUE TITLE
[llvm] build failure

### ISSUE THREAD

**Issue by 404Polaris** [microsoft/vcpkg#7543]
**Host Environment**
- OS: Windows10 x64 1903
- Compiler: msvc 14.1 x86

**To Reproduce**
`./vcpkg install llvm`

**Failure logs** 
The following packages will be built and installed:
    llvm[core]:x86-windows
Starting package 1/1: llvm:x86-windows
Building package llvm[core]:x86-windows...
-- Using cached D:/Program Files/vcpkg/downloads/llvm-8.0.0.src.tar.xz
-- Extracting source D:/Program Files/vcpkg/downloads/llvm-8.0.0.src.tar.xz
-- Using cached D:/Program Files/vcpkg/downloads/cfe-8.0.0.src.tar.xz
-- Extracting source D:/Program Files/vcpkg/downloads/cfe-8.0.0.src.tar.xz
-- Applying patch install-cmake-modules-to-share.patch
-- Applying patch fix-build-error.patch
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Restarting Build without parallelism because memory exceeded
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "D:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v
    Working Directory: D:/Program Files/vcpkg/buildtrees/llvm/x86-windows-dbg
    See logs for more information:
      D:\Program Files\vcpkg\buildtrees\llvm\install-x86-windows-dbg-out.log
      D:\Program Files\vcpkg\buildtrees\llvm\install-x86-windows-dbg-out-1.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/llvm/portfile.cmake:54 (vcpkg_install_cmake)
  scripts/ports.cmake:74 (include)

Error: Building package llvm:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: llvm:x86-windows
  Vcpkg version: 2019.07.18-nohash

**Comment by Voskrese** [comment]
**See logs for more information:**

```
D:\Program Files\vcpkg\buildtrees\llvm\install-x86-windows-dbg-out.log
D:\Program Files\vcpkg\buildtrees\llvm\install-x86-windows-dbg-out-1.log
```

**Comment by 404Polaris** [comment]
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3465009/install-x86-windows-dbg-out.log)
[Uploading install-x86-windows-dbg-out-1.log…]()

**Comment by Voskrese** [comment]
```

[1211/2665] cmd.exe /C "cd . && "D:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=tools\llvm-dis\CMakeFiles\llvm-dis.dir --rc=D:\WINDOW~1\10\bin\100177~1.0\x64\rc.exe --mt=D:\WINDOW~1\10\bin\100177~1.0\x64\mt.exe --manifests  -- D:\PROGRA~1\MICROS~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\link.exe  tools\llvm-dis\CMakeFiles\llvm-dis.dir\llvm-dis.cpp.obj tools\llvm-dis\CMakeFiles\llvm-dis.dir\__\__\resources\windows_version_resource.rc.res  /out:bin\llvm-dis.exe /implib:lib\llvm-dis.lib /pdb:bin\llvm-dis.pdb /version:0.0  /machine:X86 /STACK:10000000 /debug /INCREMENTAL /subsystem:console  lib\LLVMBitReader.lib lib\LLVMCore.lib lib\LLVMSupport.lib lib\LLVMBinaryFormat.lib lib\LLVMSupport.lib psapi.lib shell32.lib ole32.lib uuid.lib advapi32.lib delayimp.lib -delayload:shell32.dll -delayload:ole32.dll lib\LLVMDemangle.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
FAILED: bin/llvm-dis.exe 
cmd.exe /C "cd . && "D:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=tools\llvm-dis\CMakeFiles\llvm-dis.dir --rc=D:\WINDOW~1\10\bin\100177~1.0\x64\rc.exe --mt=D:\WINDOW~1\10\bin\100177~1.0\x64\mt.exe --manifests  -- D:\PROGRA~1\MICROS~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\link.exe  tools\llvm-dis\CMakeFiles\llvm-dis.dir\llvm-dis.cpp.obj tools\llvm-dis\CMakeFiles\llvm-dis.dir\__\__\resources\windows_version_resource.rc.res  /out:bin\llvm-dis.exe /implib:lib\llvm-dis.lib /pdb:bin\llvm-dis.pdb /version:0.0  /machine:X86 /STACK:10000000 /debug /INCREMENTAL /subsystem:console  lib\LLVMBitReader.lib lib\LLVMCore.lib lib\LLVMSupport.lib lib\LLVMBinaryFormat.lib lib\LLVMSupport.lib psapi.lib shell32.lib ole32.lib uuid.lib advapi32.lib delayimp.lib -delayload:shell32.dll -delayload:ole32.dll lib\LLVMDemangle.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
Microsoft (R) Incremental Linker Version 14.16.27032.1
Copyright (C) Microsoft Corporation.  All rights reserved.

FINAL LINK: command "D:\PROGRA~1\MICROS~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\link.exe tools\llvm-dis\CMakeFiles\llvm-dis.dir\llvm-dis.cpp.obj tools\llvm-dis\CMakeFiles\llvm-dis.dir\__\__\resources\windows_version_resource.rc.res /out:bin\llvm-dis.exe /implib:lib\llvm-dis.lib /pdb:bin\llvm-dis.pdb /version:0.0 /machine:X86 /STACK:10000000 /debug /INCREMENTAL /subsystem:console lib\LLVMBitReader.lib lib\LLVMCore.lib lib\LLVMSupport.lib lib\LLVMBinaryFormat.lib lib\LLVMSupport.lib psapi.lib shell32.lib ole32.lib uuid.lib advapi32.lib delayimp.lib -delayload:shell32.dll -delayload:ole32.dll lib\LLVMDemangle.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:tools\llvm-dis\CMakeFiles\llvm-dis.dir/intermediate.manifest tools\llvm-dis\CMakeFiles\llvm-dis.dir/manifest.res" failed (exit code 1104) with the following output:
Microsoft (R) Incremental Linker Version 14.16.27032.1
Copyright (C) Microsoft Corporation.  All rights reserved.

LINK : fatal error LNK1104: cannot open file 'bin\llvm-dis.exe'
```

I don’t even know, nothing is clear from the log
something is missing

**Comment by Voskrese** [comment]
most likely not enough memory

based on the above written warning

>  - Restarting Build without parallelism because memory exceeded

**Comment by 404Polaris** [comment]
> **See logs for more information:**
> 
> ```
> D:\Program Files\vcpkg\buildtrees\llvm\install-x86-windows-dbg-out.log
> D:\Program Files\vcpkg\buildtrees\llvm\install-x86-windows-dbg-out-1.log
> ```

may be it's memory exceeded,the max memory of x86 liner is 4G,but how to slove it.

**Comment by 404Polaris** [comment]
> most likely not enough memory
> 
> based on the above written warning
> 
> > - Restarting Build without parallelism because memory exceeded
> 
> disable multi-threaded build, close all applications

my pc has 32GB RAM,And memory usage is not high.

**Comment by 404Polaris** [comment]
I think the problem may be that 32-bit linkers cannot exceed 4 GB of memory.

**Comment by Voskrese** [comment]
32-bit 2 GB

add flag ?

`LINKER_FLAGS - /LARGEADDRESSAWARE`

> set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} /LARGEADDRESSAWARE") # can handle addresses larger than 2 gigabytes

**Comment by 404Polaris** [comment]
> 32-bit 2 GB
> 
> add flag ?
> 
> `LINKER_FLAGS - /LARGEADDRESSAWARE`
> 
> > set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} /LARGEADDRESSAWARE") # can handle addresses larger than 2 gigabytes

thank you.i will try it.

**Comment by cenit** [comment]
> Restarting Build without parallelism because memory exceeded

that message might be also misleading. Sometimes the linker is really unable to find references, it's not a memory error. Unfortunately vcpkg always try to resume building with the same error message

**Comment by 404Polaris** [comment]
It still doesn't work properly, nor does x64. I guess it might be Ninja's problem.

If I use VS to open the cmake project directly and compile it, it will make a similar error.

But if I use cmake to build the sln project, it can be compiled in vs.

**Comment by cenit** [comment]
Remove the `PREFER_NINJA` from the portfile. If it works, then please also open a pull request pointing to this issue

**Comment by 404Polaris** [comment]
> Remove the `PREFER_NINJA` from the portfile. If it works, then please also open a pull request pointing to this issue
> 
> https://github.com/microsoft/vcpkg/blob/22e0b9f376a66e6717f820e6c382c4112191ef9b/ports/llvm/portfile.cmake#L42

it works,but many empty directories need to be deleted. I've opened a pull request.

**Comment by cbezault** [comment]
It's odd I'm not able to reproduce this issue locally. I've built LLVM several times over the last few days using Ninja.

**Comment by 404Polaris** [comment]
> It's odd I'm not able to reproduce this issue locally. I've built LLVM several times over the last few days using Ninja.

I've reinstalled the system (Chinese) and it still doesn't work. Then I installed the English version of Windows in the virtual machine and it works properly.

**Comment by JackBoosY** [comment]
@404Polaris If this issue still exist, please reopen your PR.

Thanks.

**Comment by JackBoosY** [comment]
@404Polaris Any progress?

**Comment by 404Polaris** [comment]
> @404Polaris Any progress?

I find that this problem is related to the system language. Simply replacing the system language can not solve this problem. It must be installed in English.

**Comment by JackBoosY** [comment]
@Rastaban Is the setting we requested like this?

**Comment by 404Polaris** [comment]
> @Rastaban Is the setting we requested like this?

I found that it was security software that caused the problem. I installed other security software on the operating system (ZhCN), and when I shut close it, everything went well.

**Comment by metablaster** [comment]
If anyone finds out that it's not security software, you may need to remove:
`VCPKG_FORCE_SYSTEM_BINARIES`
from your environment, that caused failure in my case
