### ISSUE TITLE
[poco] ssl/https support on windows failed

### ISSUE THREAD

**Issue by debugfan** [microsoft/vcpkg#7555]
**Describe the bug**
vcpkg uses the develop branch of poco, but its ssl/https support on Windows is malfunction in this version. 

**Reason & Workaround**
Poco current develop branch enables both NetSSL_OpenSSL and NetSSL_Win options when build on Windows. and Its header files are mixed and overwritten after installed by vcpkg, 
but NetSSL_OpenSSL and NetSSL_Win used to support ssl/https with different implements, shouldn't be mixed. 
It seems only its current develop branch has this problem. A simplest workaround is using a stable or master version of poco as port instead.

**Environment**
- OS: Windows

**To Reproduce**
1. ./vcpkg install poco
2. Create a project, copy sample codes under NetSSL_OpenSSL or NetSSL_Win
3. Just run it simply, program will crash.

**Comment by cbezault** [comment]
Thanks for reporting this, is there an issue in the upstream we can track?

**Comment by debugfan** [comment]
> Thanks for reporting this, is there an issue in the upstream we can track?

Someone has recently opened a relative issue in the upstream: https://github.com/pocoproject/poco/issues/2760
But this issue seems to exist a long time, and only occur while installed by vcpkg.
People who use master or stable branch or install manually will maybe ignore this issue,
so it will be probably a long time to wait developers in the upstream to notice and fix it.

**Comment by JackBoosY** [comment]
Hi @debugfan, does #7698 fixed this issue?

**Comment by debugfan** [comment]
> Hi @debugfan, does #7698 fixed this issue?

Yes, it fixed. Nice work!
