### ISSUE TITLE
Add json

### ISSUE THREAD

**Issue by Drako** [Microsoft/vcpkg#756]
There is a nice modern header only json library:
https://github.com/nlohmann/json

Maybe another name would be clever as just "json" calls for name collisions.

**Comment by ras0219-msft** [comment]
`json-modern` sounds great to me.

**Comment by Drako** [comment]
`nlohmann-json` sounds good to me.
Maybe it would also be good to put the header not into `include/` but into `include/nlohmann/`.

**Comment by mloskot** [comment]
`json4modern`

**Comment by nlohmann** [comment]
nlohmann-json would be fine with me. :-)

**Comment by mloskot** [comment]
@nlohmann Cheers :)

**Comment by nlohmann** [comment]
If - apart from the name - there are any issues integrating the library, I would be happy to help (though MSVC is not exactly my expertise, but the library is known to work with MSVC 2015).

**Comment by ras0219-msft** [comment]
Hi Niels, thanks for coming over!

The only remaining concern I have is the header file name. While we certainly can and will package things in their current state, I'd like to request that you take the system package manager

**Comment by Drako** [comment]
I suppose this can be closed as the PR has been merged.
