### ISSUE TITLE
[openexr] build failure

### ISSUE THREAD

**Issue by silentmissile** [microsoft/vcpkg#7572]
**Host Environment**
- OS: [Windows10]
- Compiler: MSVC2017

**To Reproduce**
`./vcpkg install openexr:x64-windows`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.

I'm really confused, there is no warning or error message, toFloat.exe test seems passed because I can see a window with characters rolling then close automatically

but I wait several hours, the PowerShell stoped at building openext-dbg, and the CPU occupation keeps 0

-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by cbezault** [comment]
So your issue is that openxr built as debug but then hangs and doesn't build release?

**Comment by silentmissile** [comment]
exactly, that's what I mean

**Comment by Rastaban** [comment]
I am having a difficult time reproducing this issue.  Could you attach the logs from `buildtrees\openexr` under the vcpkg root along with the vcpkg console output?  This is what I see:

```
Building package openexr[core]:x64-windows...
-- Downloading https://github.com/openexr/openexr/archive/v2.3.0.tar.gz...
-- Extracting source D:/vcpkg/vcpkg/downloads/openexr-openexr-v2.3.0.tar.gz
-- Applying patch fix_clang_not_setting_modern_cplusplus.patch
-- Applying patch fix_install_ilmimf.patch
-- Using source at D:/vcpkg/vcpkg/buildtrees/openexr/src/v2.3.0-c9e3a0ec1b
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/vcpkg/vcpkg/packages/openexr_x64-windows/share/openexr/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package openexr[core]:x64-windows... done
Installing package openexr[core]:x64-windows...
Installing package openexr[core]:x64-windows... done
Elapsed time for package openexr:x64-windows: 3.129 min
```

**Comment by ThomasWilshaw** [comment]
Sorry to re open this issue but I'm having the same plroblem, the build proces hangs after building dbg to the point that I have to manually reboot the machine to close the terminal. Attached are the log files.

Thanks
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/4087635/config-x86-windows-out.log)

[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4087636/install-x86-windows-dbg-out.log)
[patch-x86-windows-0-err.log](https://github.com/microsoft/vcpkg/files/4087637/patch-x86-windows-0-err.log)

[patch-x86-windows-1-err.log](https://github.com/microsoft/vcpkg/files/4087638/patch-x86-windows-1-err.log)

[patch-x86-windows-2-err.log](https://github.com/microsoft/vcpkg/files/4087639/patch-x86-windows-2-err.log)

[x86-windows.vcpkg_abi_info.txt](https://github.com/microsoft/vcpkg/files/4087640/x86-windows.vcpkg_abi_info.txt)

**Comment by JackBoosY** [comment]
Seems to be _C:\Users\Tom\Documents\repos\vcpkg\buildtrees\openexr\x86-windows-dbg\OpenEXR\IlmImf\dwaLookups.exe_ stuck.

**Comment by JackBoosY** [comment]
@ThomasWilshaw Is this issue always reproducible? If possible, add `DISABLE_PARALLEL_CONFIGURE` to _VCPKG_PATH/ports/openexr/portfile.cmake_ line 26 and try again.

**Comment by ThomasWilshaw** [comment]
So just to clarify, line 26 should now read:

`PREFER_NINJA DISABLE_PARALLEL_CONFIGURE`

**Comment by JackBoosY** [comment]
@ThomasWilshaw Yes, I want to troubleshoot parallel builds.

**Comment by ThomasWilshaw** [comment]
Hi, sorry for the delayed reply.

I deleted the all the previous openexr buildtree files, made the edit you suggested and rebuilt. It appears to have worked. I did also do a git update of vcpkg but there didn't appear to be anything related to openexr in there.

Thanks,
Tom

**Comment by JackBoosY** [comment]
@ThadHouse Thanks for your feedback.
