### ISSUE TITLE
Installed GTK+, Visual studio can't find the librarie headers

### ISSUE THREAD

**Issue by Dimilo7** [microsoft/vcpkg#7579]
I successfully installed GTK+ with vcpkg on win64. On the official GTK website it says, once you installed GTK with vcpkg you should be ready to work in VIsual Studio, as it will recognize the library immediately. Well that's not what happens. Whenever I include <gtk/gtk.h> it says cannot open source file "gtk/gtk.h" and "Cannot open include file: 'gtk/gtk.h': No such file or directory"

Any way to fix this?
Thanks!

**Comment by Voskrese** [comment]
in project $(VcpkgRoot)include

<cl
`$(VcpkgRoot)include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>`
</cl

link or lib 
```
<AdditionalLibraryDirectories>
$(VcpkgRoot)lib;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
```
</link or </lib

**Comment by Dimilo7** [comment]
Thanks for your answer. I actually found a way simpler solution. GTK on their website recommend to download the 64 bit version of gtk, while my vs is running on 32 bits. I just assumed it to be 64 too. So yeah, thanks for the answer anyways!
