### ISSUE TITLE
Could not find MSBuild for VS 2017

### ISSUE THREAD

**Issue by martin-traverse** [Microsoft/vcpkg#758]
Bootstrap script fails with this message:
Could not find MSBuild version with C++ support. VS2015 or VS2017 (with C++) needs to be installed.

Looking into the cause, I found the Configuration Console tool is not reporting any VS 2017 instances:

C:\Dev\Lib\vcpkg>downloads\nuget-packages\Microsoft.VisualStudio.Setup.Configuration.Native.1.5.125-rc\tools\x64\Microsoft.VisualStudio.Setup.Configuration.Console.exe all
Microsoft (R) Visual Studio Setup Configuration Utility, version 1.5.125-rc
Copyright (c) Microsoft Corporation. All rights reserved.

C:\Dev\Lib\vcpkg>

I do not have VS 2015 installed (I don't want to install it just to make this work)!

I hacked the script to insert the location and was able to build, but thought I should report in case other people without VS 2015 have the same problem. No idea on why the config console isn't picking up any locations, happy to answer questions if that helps.

**Comment by ras0219-msft** [comment]
What version of VS2017 do you have (Help->About)? Did you update VS2017 to the RTW build released on Tuesday?

**Comment by martin-traverse** [comment]
Hi, thanks for getting back to me. You're right, this was an issue with the installation of VS 2017, I had the right version but for some reason the installation hadn't completed cleanly. Uninstall, reboot, re-install fixed it.

**Comment by trisp3ar** [comment]
What modifications have you done to which script? I ran into the same error and I'm clueless what to do.
