### ISSUE TITLE
[New Port Request] Libcrafter

### ISSUE THREAD

**Issue by realsarm** [microsoft/vcpkg#7580]
Library name: Libcrafter

Library description:Libcrafter is a high level library for C++ designed to create and decode network 
packets. It is able to craft or decode packets of most common networks protocols, 
send them on the wire, capture them and match requests and replies.
It enables the creation of networking tools in a few lines with a interface 
very similar to Scapy. 

Source repository URL: https://github.com/pellegre/libcrafter

**Comment by NancyLi1013** [comment]
Hi @realsarm thanks for posting this issue. This port has been added to vcpkg. Please try to update vcpkg and use it.
