### ISSUE TITLE
build failure: can't build vcpkg

### ISSUE THREAD

**Issue by eric72** [microsoft/vcpkg#7584]
Hi,

I got  a problem when i try to build vcpkg on windows with bash command prompt and powershell.
When i do : 
./bootstrap-vcpkg.sh 
or
.\bootstrap-vcpkg.bat

it say vcpkg is not an intern command.
I have open both file, and i saw it's build for linux environment.
How can i resolve this please ?

**Host Environment**
- OS: Windows 10
- Compiler: MinGW64

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs** 
-PID is not an i ntern command
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by cbezault** [comment]
We don't support building vcpkg under MinGW.
