### ISSUE TITLE
Could not find vcvarsall.bat for VS 2017

### ISSUE THREAD

**Issue by martin-traverse** [Microsoft/vcpkg#759]
Could be related to the previous issue, I'm not sure. Here is the console output:

C:\Dev\Lib\vcpkg>vcpkg install sdl2
Could not detect vcvarsall.bat.
The following paths were examined:
    VC/Auxiliary/Build/vcvarsall.bat
    C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/vcvarsall.bat

C:\Dev\Lib\vcpkg>vcpkg version
Vcpkg package management program version 0.0.75-da09a8136d32890ab5f3804d9abcc5f9685a30e0

See LICENSE.txt for license information.

**Comment by martin-traverse** [comment]
As per my previous ticket, I do not have VS 2015 installed, just VS 2017.

**Comment by mloskot** [comment]
Do you have "VC+Build Tools 2015" installed as part of VS2017 installation?

There are known issues with those tools:
* https://github.com/Microsoft/vcpkg/issues/745#issuecomment-285173708
* [Unusable VC++ Build Tools 2015 installed with VS2017](https://developercommunity.visualstudio.com/content/problem/22031/unusable-vc-build-tools-2015-installed-with-vs2017.html)

Looks like vcpkg is trying to use VS2015 toolset anyway.

**Comment by ras0219-msft** [comment]
Previous issue: #758.

**Comment by martin-traverse** [comment]
Hi, thanks for getting back to me. You're right, this was an issue with the installation of VS 2017, I had the right version but for some reason the installation hadn't completed cleanly. Uninstall, reboot, re-install fixed it.
