### ISSUE TITLE
[New Port Request] Mecab

### ISSUE THREAD

**Issue by xuchaoUCAS** [microsoft/vcpkg#7590]
Library name: Mecab

Library description: A morphological analysis engine based on CRF

Source repository URL: https://github.com/taku910/mecab

Project homepage (if different from the source repository): https://taku910.github.io/mecab/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
The machine setup: "I'm using Windows Server 2016 Datacenter. My machine is using the en-us locale. I successfully ran ' vcpkg install mecab"
The steps to reproduce: "I run 'vcpkg list'"
The outcome you expected: "I expected to see 'mecab:x86-windows                                  0.996            A morphological analysis engine based on CRF'"
The actual outcome: the same as expected

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
