### ISSUE TITLE
libmysql:x64-windows build failure

### ISSUE THREAD

**Issue by fengyc** [microsoft/vcpkg#7593]
**Host Environment**
- OS: windows10
- Compiler: vs2017 build tool

**To Reproduce**
`./vcpkg install libmysql`

**Failure logs** 
```
PS C:\Programs\vcpkg> .\vcpkg.exe install libmysql
The following packages will be built and installed:
    libmysql[core]:x64-windows
Starting package 1/1: libmysql:x64-windows
Building package libmysql[core]:x64-windows...
-- Using cached C:/Programs/vcpkg/downloads/mysql-mysql-server-mysql-8.0.4.tar.gz
-- Using source at C:/Programs/vcpkg/buildtrees/libmysql/src/ysql-8.0.4-a1c62ff6ee
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/Programs/cmake-3.15.2-win64-x64/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: C:/Programs/vcpkg/buildtrees/libmysql/x64-windows-dbg
    See logs for more information:
      C:\Programs\vcpkg\buildtrees\libmysql\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/libmysql/portfile.cmake:58 (vcpkg_install_cmake)
  scripts/ports.cmake:74 (include)


Error: Building package libmysql:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libmysql:x64-windows
  Vcpkg version: 2019.07.18-nohash

Additionally, attach any relevant sections from the log files above.
```
Build log in ` C:\Programs\vcpkg\buildtrees\libmysql\install-x64-windows-dbg-out.log`

C:\Programs\vcpkg\buildtrees\libmysql\src\ysql-8.0.4-a1c62ff6ee\sql\log_event.cc(13386): warning C4267: 'argument': conversion from 'size_t' to 'uint', possible loss of data
C:\Programs\vcpkg\buildtrees\libmysql\src\ysql-8.0.4-a1c62ff6ee\sql\log_event.cc(14295): warning C4267: '+=': conversion from 'size_t' to 'int', possible loss of data
[276/417] cmd.exe /C "cd . && C:\Programs\cmake-3.15.2-win64-x64\bin\cmake.exe -E vs_link_exe --intdir=libmysql\CMakeFiles\libmysql_api_test.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100162~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100162~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MIB055~1\2017\BUILDT~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\link.exe  libmysql\CMakeFiles\libmysql_api_test.dir\api_test.c.obj libmysql\CMakeFiles\libmysql_api_test.dir\__\versioninfo_exe.rc.res  /out:runtime_output_directory\libmysql_api_test.exe /implib:libmysql\libmysql_api_test.lib /pdb:runtime_output_directory\libmysql_api_test.pdb /version:0.0  /machine:x64 /debug /INCREMENTAL /INCREMENTAL:NO /subsystem:console  ws2_32.lib archive_output_directory\clientlib.lib archive_output_directory\dbug.lib archive_output_directory\strings.lib archive_output_directory\vio.lib archive_output_directory\mysys.lib archive_output_directory\mysys_ssl.lib C:\Programs\vcpkg\installed\x64-windows\debug\lib\zlibd.lib C:\Programs\vcpkg\installed\x64-windows\debug\lib\ssleay32.lib C:\Programs\vcpkg\installed\x64-windows\debug\lib\libeay32.lib archive_output_directory\auth_win_client.lib archive_output_directory\dbug.lib archive_output_directory\mysys.lib archive_output_directory\dbug.lib archive_output_directory\mysys.lib archive_output_directory\strings.lib C:\Programs\vcpkg\installed\x64-windows\debug\lib\zlibd.lib crypt32.lib ws2_32.lib Secur32.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cmd.exe /C "cd /D C:\Programs\vcpkg\buildtrees\libmysql\x64-windows-dbg\libmysql && C:\Programs\vcpkg\buildtrees\libmysql\x64-windows-dbg\runtime_output_directory\libmysql_api_test.exe > C:/Programs/vcpkg/buildtrees/libmysql/x64-windows-dbg/libmysql/libmysql_api_test.out""
FAILED: runtime_output_directory/libmysql_api_test.exe 
cmd.exe /C "cd . && C:\Programs\cmake-3.15.2-win64-x64\bin\cmake.exe -E vs_link_exe --intdir=libmysql\CMakeFiles\libmysql_api_test.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100162~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100162~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MIB055~1\2017\BUILDT~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\link.exe  libmysql\CMakeFiles\libmysql_api_test.dir\api_test.c.obj libmysql\CMakeFiles\libmysql_api_test.dir\__\versioninfo_exe.rc.res  /out:runtime_output_directory\libmysql_api_test.exe /implib:libmysql\libmysql_api_test.lib /pdb:runtime_output_directory\libmysql_api_test.pdb /version:0.0  /machine:x64 /debug /INCREMENTAL /INCREMENTAL:NO /subsystem:console  ws2_32.lib archive_output_directory\clientlib.lib archive_output_directory\dbug.lib archive_output_directory\strings.lib archive_output_directory\vio.lib archive_output_directory\mysys.lib archive_output_directory\mysys_ssl.lib C:\Programs\vcpkg\installed\x64-windows\debug\lib\zlibd.lib C:\Programs\vcpkg\installed\x64-windows\debug\lib\ssleay32.lib C:\Programs\vcpkg\installed\x64-windows\debug\lib\libeay32.lib archive_output_directory\auth_win_client.lib archive_output_directory\dbug.lib archive_output_directory\mysys.lib archive_output_directory\dbug.lib archive_output_directory\mysys.lib archive_output_directory\strings.lib C:\Programs\vcpkg\installed\x64-windows\debug\lib\zlibd.lib crypt32.lib ws2_32.lib Secur32.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cmd.exe /C "cd /D C:\Programs\vcpkg\buildtrees\libmysql\x64-windows-dbg\libmysql && C:\Programs\vcpkg\buildtrees\libmysql\x64-windows-dbg\runtime_output_directory\libmysql_api_test.exe > C:/Programs/vcpkg/buildtrees/libmysql/x64-windows-dbg/libmysql/libmysql_api_test.out""
Microsoft (R) Incremental Linker Version 14.16.27032.1
Copyright (C) Microsoft Corporation.  All rights reserved.

**Additional context**

**Comment by fco06** [comment]
PS D:\Application\C++\lib\vcpkg> .\vcpkg install libmysql
The following packages will be built and installed:
    libmysql[core]:x64-windows
Starting package 1/1: libmysql:x64-windows
Building package libmysql[core]:x64-windows...
-- Using cached D:/Application/C++/lib/vcpkg/downloads/mysql-mysql-server-mysql-8.0.4.tar.gz
-- Using source at D:/Application/C++/lib/vcpkg/buildtrees/libmysql/src/ysql-8.0.4-a1c62ff6ee
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:58 (message):
    Command failed: ninja -v
    Working Directory: D:/Application/C++/lib/vcpkg/buildtrees/libmysql/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\Application\C++\lib\vcpkg\buildtrees\libmysql\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:296 (vcpkg_execute_required_process)
  ports/libmysql/portfile.cmake:38 (vcpkg_configure_cmake)
  scripts/ports.cmake:74 (include)
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/3500786/config-x64-windows-out.log)

**Comment by fco06** [comment]
for me, the Error in compile.' it seems due to '++' in your directory D:\Application\C++\lib\vcpkg\buildtrees\dlib\x64-windows-dbg. See https://gitlab.kitware.com/cmake/cmake/issues/16207.
Now it's work

**Comment by fengyc** [comment]
@fco06 Two errors are differenct. In my case,  the code has been configured and compiled, but got a failure execution of libmysql_api_test.exe, due to system path or something incorrect.

Attempt to execute libmysql_api_test.ext in termial, cmd:

    C:\Programs\vcpkg\buildtrees\libmysql\x64-windows-dbg\libmysql>..\runtime_output_directory\libmysql_api_test.exe

 Then get a system error: could not load zlibd1.dll and SSLEASY32.dll. It seems libmysql_api_test.exe is dynamically linked to those two libraries.

**Comment by NancyLi1013** [comment]
Hi @fengyc and @fco06 
`libmysql `has been updated to 8.0.20.
Could you please try to update vcpkg and rebuild this?

**Comment by PhoebeHui** [comment]
We haven't been able to repro this, if more information comes up, or this issue appears again, please reopen.
