### ISSUE TITLE
Could NOT find GLEW (missing: GLEW_INCLUDE_DIRS GLEW_LIBRARIES)

### ISSUE THREAD

**Issue by linuxaged** [microsoft/vcpkg#7597]
Can not find installed glew library when doing CMake configure
    
        cmake -DCMAKE_TOOLCHAIN_FILE=C:/workspace/vcpkg/scripts/buildsystems/vcpkg.cmake

**Environment**
- OS: Win10 Pro 64bit
- Compiler: VS2017
- CMake: 3.15

**To Reproduce**
1. ./vcpkg install glew
2. CMakeLists.txt

        find_package(OpenGL REQUIRED)
        find_package(GLEW REQUIRED)
        target_link_libraries(myApp ${OPENGL_LIBRARY} GLEW::GLEW)

**Comment by linuxaged** [comment]
Related post https://www.reddit.com/r/cpp_questions/comments/8zuhkx/trying_to_working_with_vcpkg_and_glew/

**Comment by PhoebeHui** [comment]
Related to issue https://github.com/microsoft/vcpkg/issues/7519.

**Comment by PhoebeHui** [comment]
@linuxaged, PR#7519 merged, please get vcpkg latest source and rebuild glew and try again.

**Comment by Daniate** [comment]
Add `list(APPEND CMAKE_PREFIX_PATH "C:/workspace/vcpkg/packages/glew_x64-windows")` before `find_package`
