### ISSUE TITLE
How do I specify build dependencies of default features

### ISSUE THREAD

**Issue by fbergmann** [microsoft/vcpkg#7609]
Trying to write my first port, I encountered the following issue. My library has support for different XML parsing libraries, and just needs one of them. So while there is a `Feature: expat` and a `Feature: libxml2` that depend on the correspoding libraries, if I specify 

`Default-Features: expat`

and then run `vcpkg depend-info`, I don't see expat listed as a built dependency, as I would have expected. However, adding: 

`Build-Depends: expat`

seems wrong as well, as then the library would depend on `expat` even though it would only be using `libxml2`. 

When asking a question please also include where you looked for an answer (so we can update the documentation if needed).

* https://github.com/microsoft/vcpkg/blob/master/docs/specifications/feature-packages.md
* https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/control-files.md
* https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/portfile-functions.md

**Comment by cbezault** [comment]
Could you post the full CONTROL file?

**Comment by cbezault** [comment]
Also as a follow up, can your library tolerate both the expat and libxml2 features to be specified and can the library tolerate having neither specified?

**Comment by fbergmann** [comment]
So far, this is the [CONTROL] file for now, interestingly it does not complain about the Build-Depends line at all. I'll change it back to always depend on expat if necessary (as the library will be fine linking against both libraries). However, no xml parsing library is not an option.

**Comment by cbezault** [comment]
So as for your question about why depend-info was not returning what you expected that is a bug which is being addressed by #7643. Do expat and libxml2 provide the same interface?

**Comment by NancyLi1013** [comment]
Hi @fbergmann 
Do you have any other questions about this?

**Comment by NancyLi1013** [comment]
I'm closing this issue for now since inactive in a long time.
