### ISSUE TITLE
ICO package build failure

### ISSUE THREAD

**Issue by JayDalton** [microsoft/vcpkg#7611]
**Host Environment**
- OS: Windows 10 1809 x64
- Compiler: MSVC ++ 15.9 v14.16 latest v141 tools 

**To Reproduce**
`./vcpkg install icu:x86-windows`

**Failure logs** 
- PS C:\Repository\vcpkg> .\vcpkg.exe install icu:x86-windows
The following packages will be built and installed:
    icu[core]:x86-windows
Starting package 1/1: icu:x86-windows
Building package icu[core]:x86-windows...
-- Using cached C:/Repository/vcpkg/downloads/icu4c-61_1-src.tgz
-- Using source at C:/Repository/vcpkg/buildtrees/icu/src/c-61_1-src-b2757af884
-- Acquiring MSYS Packages...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:58 (message):
    Command failed: C:/Repository/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -Sy --noconfirm --needed make automake1.15"
    Working Directory: C:/Repository/vcpkg/downloads/tools/msys2
    Error code: 1
    See logs for more information:
      C:\Repository\vcpkg\buildtrees\icu\msys-pacman-x86-windows-out.log
      C:\Repository\vcpkg\buildtrees\icu\msys-pacman-x86-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:106 (vcpkg_execute_required_process)
  ports/icu/portfile.cmake:77 (vcpkg_acquire_msys)
  scripts/ports.cmake:74 (include)

Error: Building package icu:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x86-windows
  Vcpkg version: 2019.07.18-nohash

Additionally, attach any relevant sections from the log files above.

** msys-pacman-x86-windows-err.log **
warning: Public keyring not found; have you run 'pacman-key --init'?
error: mingw32: key "AD351C50AE085775EB59333B5F92EFC1A47D45A1" is unknown
error: key "AD351C50AE085775EB59333B5F92EFC1A47D45A1" could not be looked up remotely
error: mingw64: key "AD351C50AE085775EB59333B5F92EFC1A47D45A1" is unknown
error: key "AD351C50AE085775EB59333B5F92EFC1A47D45A1" could not be looked up remotely
error: msys: key "AD351C50AE085775EB59333B5F92EFC1A47D45A1" is unknown
error: key "AD351C50AE085775EB59333B5F92EFC1A47D45A1" could not be looked up remotely
error: mingw32: key "AD351C50AE085775EB59333B5F92EFC1A47D45A1" is unknown
error: key "AD351C50AE085775EB59333B5F92EFC1A47D45A1" could not be looked up remotely
error: failed to update mingw32 (invalid or corrupted database (PGP signature))
error: mingw64: key "AD351C50AE085775EB59333B5F92EFC1A47D45A1" is unknown
error: key "AD351C50AE085775EB59333B5F92EFC1A47D45A1" could not be looked up remotely
error: failed to update mingw64 (invalid or corrupted database (PGP signature))
error: msys: key "AD351C50AE085775EB59333B5F92EFC1A47D45A1" is unknown
error: key "AD351C50AE085775EB59333B5F92EFC1A47D45A1" could not be looked up remotely
error: failed to update msys (invalid or corrupted database (PGP signature))
error: failed to synchronize all databases 

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Voskrese** [comment]
The easiest way is, delete msys folder. 
and try again

Well, you need to update your certificates and update the msys

**Comment by NancyLi1013** [comment]
Hi @JayDalton  thanks for posting this issue. Does this issue still exist on your machine now ?

**Comment by NancyLi1013** [comment]
Please feel free to reopen this issue or open a new issue if it is still a problem for you.

Thanks.
