### ISSUE TITLE
[check] build failure during linking

### ISSUE THREAD

**Issue by fbergmann** [microsoft/vcpkg#7612]
It seems the check port requires some symbols that are not linked in, and should be either be provided as dependency, or not used on Windows. 

**Host Environment**
- OS: Windows
- Compiler: msvc 14.22.27905

**To Reproduce**
Steps to reproduce the behavior, compile a library against libcheck, and it will fail at the linking stage. In my case I used [libSBML](https://github.com/fbergmann/vcpkg/tree/master/ports/libsbml). 

`./vcpkg build libsbml[check]`

**Failure logs** 

```
check.lib(check_run.c.obj) : error LNK2019: unresolved external symbol _clock_gettime referenced in function _tcase_run_tfun_nofork
check.lib(check_log.c.obj) : error LNK2001: unresolved external symbol _clock_gettime
check.lib(check_log.c.obj) : error LNK2019: unresolved external symbol _gettimeofday referenced in function _xml_lfun
check.lib(check_log.c.obj) : error LNK2019: unresolved external symbol _localtime_r referenced in function _xml_lfun
```

**Comment by JackBoosY** [comment]
It seems that functions `clock_gettime`/`gettimeofday`/`localtime_r` only support linux, and we should not build the test project.

**Comment by NancyLi1013** [comment]
Since these functions `clock_gettime/gettimeofday/localtime_r` only support linux. You need to link `compat.lib ` on windows. 
Would you be able to create a PR to add this port? We'll add it if you don't have enough time.

Thanks.

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
