### ISSUE TITLE
[New Port Request] google libphonenumber

### ISSUE THREAD

**Issue by JayDalton** [microsoft/vcpkg#7615]
Library name: Google LibPhoneNumber

Library description: Google's common Java, C++ and JavaScript library for parsing, formatting, and validating international phone numbers

Source repository URL: https://github.com/google/libphonenumber

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included): only the C++ version

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
