### ISSUE TITLE
Cannot call `vcpkg` from an outside directory to install a package (since commit e79f0dc5)

### ISSUE THREAD

**Issue by kmhofmann** [microsoft/vcpkg#7616]
**Describe the bug**
Some change in commit `e79f0dc5328f28b2b3942e2cd0e9b0c1accca4a1` introduced a bug that makes calling vcpkg from outside directories fail.

Assuming `vcpkg` is cloned and bootstrapped in directory `~/projects/vcpkg`, the following behavior happens:

    / $ ~/projects/vcpkg/vcpkg install eigen3
    error checking existence of file /home/user/projects/vcpkg/vcpkg/.vcpkg-root: Not a directory

Seems it looks for `.vcpkg-root` in the wrong location (off by one).
The problem also appears when the `vcpkg` directory is put on the PATH.

What should happen: installs `eigen3` package (or any other package that's specified)

This works with commits made on master before `e79f0dc5328f28b2b3942e2cd0e9b0c1accca4a1`.

**Environment**
- OS: Linux (Ubuntu 16.04, but issue should also be present on other versions/distributions).
- Compiler: GCC 9.1

**To Reproduce**
1. Clone and bootstrap vcpkg
2. Go to a directory above and call the `vcpkg install ...` executable with an absolute path.
3. The error message "error checking existence of file /home/user/projects/vcpkg/vcpkg/.vcpkg-root: Not a directory" is emitted.

**Expected behavior**
Package installation should succeed.

**Comment by ubsan** [comment]
Currently checking this out

**Comment by ubsan** [comment]
Oh, that was dumb. I fixed the code on Windows, but didn't finish it on Unix.

**Comment by ubsan** [comment]
Fixed by #7619
