### ISSUE TITLE
Have scripts/cmake/vcpkg_acquire_msys.cmake use the cache when available.

### ISSUE THREAD

**Issue by ASxa86** [microsoft/vcpkg#7617]
****

**Is your feature request related to a problem? Please describe.**
I am attempting to run vcpkg in an "offline" mode. By this, I mean I have all of the packages I need downloaded in my downloads folder. Then, on a machine with no internet connection, I run vcpkg install **_library_**. For the most part, this works well. There are a couple of libraries that depend on msys2 (ffmpeg, icu) and make use of the call vcpkg_acquire_msys(). The problem is this call will attempt to download msys2 packages from the internet even though I already have the msys2 packages downloaded and saved to a cache directory in $DOWNLOADS/tools/msys2/msys64/var/cache/pacman/pkg. This is preventing me from completing my builds with vcpkg.

**Proposed solution**
I propose that within vcpkg_acquire_msys.cmake:~106, before the call to vcpkg_execute_required_process() (this invokes the package query on the internet), there is a check made to the msys2 pacman cache to determine if the packages already exist. If they do, then there is nothing to do here.

**Describe alternatives you've considered**
My current work around is to comment out the call to vcpkg_execute_required_process() as I already have the msys2 packages installed but this becomes a maintenance issue whenever I need to update my offline version of vcpkg.

**Comment by ASxa86** [comment]
It appears this is still an issue. Will there be any support for an offline version of vcpkg? I'm trying to update an air-gap network with the latest vcpkg but it doesn't seem like there is any support for building packages from cached libraries and tools. I'm still having to manually go in and modify vcpkg to skip downloading.

**Comment by emptyVoid** [comment]
@ASxa86, can you, please, try the following -- replace `-Sy` flag with `-S` and check if the internet connection would still be an issue:
https://github.com/microsoft/vcpkg/blob/e792d1c171a18d32401db0f95251515cc15056f5/scripts/cmake/vcpkg_acquire_msys.cmake#L168

**Comment by emptyVoid** [comment]
Well that's a bit weird... I've just tried the same on my PC with Ethernet cable unplugged -- and the install succeeded.

**Comment by ASxa86** [comment]
Yeah, I even confirmed I have all of the packages and the mingw32.db file on the machine. I wonder if my machine has some security restrictions applied that is preventing this from working.

**Comment by NancyLi1013** [comment]
Hi @ASxa86  and @emptyVoid 

Thanks for posting this issue and joining in the discussion of this issue.

Since it's similar to #11837. Let's track this issue and move our attention there.
