### ISSUE TITLE
[qt5] build failure : x86-windows-static

### ISSUE THREAD

**Issue by dsb67** [microsoft/vcpkg#7618]
**Host Environment**
- OS: Windows
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.22.27905 for x86

**To Reproduce**
`./vcpkg install qt5`

**Failure logs** 
Starting package 2/29: qt5-declarative:x86-windows-static
Building package qt5-declarative[core]:x86-windows-static...
CMake Warning at installed/x86-windows-static/share/qt5modularscripts/qt_modular_library.cmake:6 (message):
  qt5-declarative's buildsystem uses very long paths and may fail on your
  system.

  We recommend moving vcpkg to a short path such as 'C:\src\vcpkg' or using
  the subst command.
Call Stack (most recent call first):
  installed/x86-windows-static/share/qt5modularscripts/qt_modular_library.cmake:164 (qt_modular_fetch_library)
  ports/qt5-declarative/portfile.cmake:5 (qt_modular_library)
  scripts/ports.cmake:74 (include)

-- Using cached X:/vcpkg-master/downloads/qtdeclarative-everywhere-src-5.12.3.tar.xz
-- Using source at X:/vcpkg-master/buildtrees/qt5-declarative/src/5.12.3-93b4ba5375
-- Configuring x86-windows-static-rel
-- Configuring x86-windows-static-rel done
-- Configuring x86-windows-static-dbg
-- Configuring x86-windows-static-dbg done
-- Package makefiles-x86-windows-static-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:58 (message):
    Command failed: X:/vcpkg-master/downloads/tools/jom/jom-1.1.3/jom.exe qmake_all
    Working Directory: X:/vcpkg-master/buildtrees/qt5-declarative/x86-windows-static-dbg
    Error code: 2
    See logs for more information:
      X:\vcpkg-master\buildtrees\qt5-declarative\package-makefiles-x86-windows-static-dbg-out.log
      X:\vcpkg-master\buildtrees\qt5-declarative\package-makefiles-x86-windows-static-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_qmake.cmake:48 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_build_qmake.cmake:63 (run_jom)
  installed/x86-windows-static/share/qt5modularscripts/qt_modular_library.cmake:57 (vcpkg_build_qmake)
  installed/x86-windows-static/share/qt5modularscripts/qt_modular_library.cmake:165 (qt_modular_build_library)
  ports/qt5-declarative/portfile.cmake:5 (qt_modular_library)
  scripts/ports.cmake:74 (include)

Error: Building package qt5-declarative:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qt5-declarative:x86-windows-static
  Vcpkg version: 2019.07.18-nohash

Additionally, attach any relevant sections from the log files above.

x:\NBS>vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

-Please attach any additional failure logs mentioned in the console output.

**Additional context**

jom 1.1.3 - empower your cores

'X:\vcpkg-master\buildtrees\qt5-declarative\x86-windows-static-dbg\bin\qmlimportscanner.exe' is not recognized as an internal or external command,
operable program or batch file.
X:/vcpkg-master/installed/x86-windows-static/share/qt5/debug/mkspecs/features/qt.prf:291: Error parsing JSON at 1:1: illegal value
Project ERROR: Failed to parse qmlimportscanner output.
jom: X:\vcpkg-master\buildtrees\qt5-declarative\x86-windows-static-dbg\tools\Makefile [sub-qml-qmake_all] Error 3
jom: X:\vcpkg-master\buildtrees\qt5-declarative\x86-windows-static-dbg\Makefile [sub-tools-qmake_all] Error 2

**Comment by JackBoosY** [comment]
Duplicate with #4560.
