### ISSUE TITLE
[New Port Request] JUCE

### ISSUE THREAD

**Issue by myd7349** [microsoft/vcpkg#7625]
Library name: JUCE

Library description: The JUCE cross-platform C++ framework

Source repository URL: https://github.com/WeAreROLI/JUCE

Project homepage (if different from the source repository): https://juce.com

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
