### ISSUE TITLE
[libpmemobj-cpp] Missing cmake targets

### ISSUE THREAD

**Issue by seghcder** [microsoft/vcpkg#7632]
****

**Is your feature request related to a problem? Please describe.**
LibPMemObj appears to be missing final cmake configuration to make targets available via find_pkg. Many other packages provide this info at the end of an install:
```
The package fmt:x86-windows provides CMake targets:
    find_package(fmt CONFIG REQUIRED)
    target_link_libraries(main PRIVATE fmt::fmt fmt::fmt-header-only)
```
However this is missing for libpmemobj-cpp

**Proposed solution**
Make libpmemobj-cpp cmake targets available after vcpkg installation

**Describe alternatives you've considered**
Workaround is to use find_path / find_library in CMake file

**Additional context**
Thanks!

**Comment by LilyWangLL** [comment]
This issue has been fix, you can rebuild `libpmemobj-cpp` and use the following codes to use it.
```
Elapsed time to handle libpmemobj-cpp:x64-windows: 20.9 s

Total elapsed time: 28.82 s

libpmemobj-cpp is header-only and can be used from CMake via:

    find_path(LIBPMEMOBJ_CPP_INCLUDE_DIRS "libpmemobj++/allocation_flag.hpp")
    target_include_directories(main PRIVATE ${LIBPMEMOBJ_CPP_INCLUDE_DIRS})
```
