### ISSUE TITLE
Find VS Code in non-default locations

### ISSUE THREAD

**Issue by Mixaill** [Microsoft/vcpkg#764]
Currently **vcpkg** searches for **VS Code** only in **Program Files** ([toolsrc/src/commands_edit.cpp](https://github.com/Microsoft/vcpkg/blob/39772adbfe37b03f7302b3a0d974404519c643ce/toolsrc/src/commands_edit.cpp#L29))

It would be nice if **vcpkg** also did a search for the installation path in the registry:
```
keys (VS Code Release):
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{F8A2A208-72B3-4D61-95FC-8A65D340689B}_is1
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{F8A2A208-72B3-4D61-95FC-8A65D340689B}_is1

keys (VS Code Insider):
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{C26E74D1-022E-4238-8B9D-1E7564A36CC9}_is1
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{C26E74D1-022E-4238-8B9D-1E7564A36CC9}_is1

Value:
InstallLocation
```

**Comment by ras0219-msft** [comment]
As a workaround, we will respect the `EDITOR` environment variable which you can set to the path to `Code.exe`.

**Comment by Mixaill** [comment]
Wow, that was fast :)
