### ISSUE TITLE
Breaking Windows Irrlicht port change on 7/20?

### ISSUE THREAD

**Issue by JasonGoemaat** [microsoft/vcpkg#7640]
**Describe the bug**
When building minetest on windows using VCPKG for the dependencies, the build succeeds but the app fails due to character encoding issues.  I see on 7/20 a change was made to character handling defines using a patch, I'm guessing that broke the build.  If different code is generated that would break existing projects that is a problem...

**Environment**
- OS: Windows 10
- Compiler: 

**To Reproduce**
1. Follow minetest build instructions in [the readme](https://github.com/minetest/minetest/)

    cmake . -G"Visual Studio 15 2017 Win64" -DCMAKE_TOOLCHAIN_FILE=D:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_GETTEXT=0 -DENABLE_CURSES=0
    cmake --build . --config Release

In the call to `CFileSystem::createAndOpenFile()` an ansi string is passed, but debugging into the Irrlicht method it treats it as unicode.

**Expected behavior**
The game should compile and run

**Failure logs** 
*none*

**Additional context**
[PR](https://github.com/microsoft/vcpkg/pull/7354)

**Comment by Voskrese** [comment]
edit `CMakeLists.txt`

replace

`set(IRR_ROOT_DIR "")`

to 

`set(IRR_ROOT_DIR .)`

**Comment by Voskrese** [comment]
ver 1.9
**customized** version of Irrlicht 1.9.0 and runs on **Windows machines only**

http://irrlicht.sourceforge.net/?p=1596

https://github.com/zaki/irrlicht

**Comment by JackBoosY** [comment]
Close this issue via #7726 merged.
