### ISSUE TITLE
[ffmpeg] build failure

### ISSUE THREAD

**Issue by Voskrese** [microsoft/vcpkg#7646]
bug control file 

`vcpkg install ffmpeg[*]:x64-windows`

> The following packages will be built and installed:
>     ffmpeg[bzip2,core,ffmpeg,ffplay,ffprobe,ffserver,gpl,lzma,nonfree,opencl,openssl,vpx,x264]:x64-windows
> Starting package 1/1: ffmpeg:x64-windows
> Building package ffmpeg[bzip2,core,ffmpeg,ffplay,ffprobe,ffserver,gpl,lzma,nonfree,opencl,openssl,vpx,x264]:x64-windows...
> CMake Warning:
>   No source or binary directory provided.  Both will be assumed to be the
>   same as the current working directory, but note that this warning will
>   become a fatal error in future CMake releases.

https://github.com/microsoft/vcpkg/blob/master/ports/ffmpeg/CONTROL

extra line breaks

> 
> Description: a library to decode, encode, transcode, mux, demux, stream, filter and play pretty much anything that humans and machines have created. **[BUG]** <<--
>   FFmpeg is the leading multimedia framework, able to decode, encode, transcode, mux, demux, stream, filter and play pretty much anything that humans and machines have created. It supports the most obscure ancient formats up to the cutting edge. No matter if they were designed by some standards committee, the community or a corporation. It is also highly portable: FFmpeg compiles, runs, and passes our testing infrastructure FATE across Linux, Mac OS X, Microsoft Windows, the BSDs, Solaris, etc. under a wide variety of build environments, machine architectures, and configurations.

**Comment by wangli28** [comment]
I can't reproduce it locally. I installed it successfully with Visual Studio 2017 and vcpkg latest source. There are no warnings on my VM. This is my build log:

Starting package 8/8: ffmpeg:x64-windows
Building package ffmpeg[bzip2,core,ffmpeg,ffplay,ffprobe,ffserver,gpl,lzma,nonfree,opencl,openssl,vpx,x264]:x64-windows...
-- Downloading http://ffmpeg.org/releases/ffmpeg-4.1.tar.bz2...
-- Extracting source F:/0812/vcpkg/downloads/ffmpeg-4.1.tar.bz2
-- Applying patch create-lib-libraries.patch
-- Applying patch detect-openssl.patch
-- Applying patch configure_opencv.patch
-- Applying patch fix_windowsinclude-in-ffmpegexe-1.patch
-- Applying patch fix_windowsinclude-in-ffmpegexe-2.patch
-- Applying patch fix_libvpx_windows_linking.patch
-- Applying patch fix-debug-build.patch
-- Using source at F:/0812/vcpkg/buildtrees/ffmpeg/src/ffmpeg-4-bb005b3e35
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Building Options: --enable-asm --enable-yasm --disable-doc --enable-debug --enable-runtime-cpudetect --enable-nonfree --enable-gpl --enable-openssl --enable-ffmpeg --enable-ffplay --enable-ffprobe --enable-libvpx --enable-libx264 --enable-opencl --enable-lzma --enable-bzlib  --extra-cflags=-DHAVE_UNISTD_H=0 --disable-static --enable-shared
-- Building Relase Options:  --extra-cflags=-MD --extra-cxxflags=-MD
-- Building ffmpeg for Release
-- Building Debug Options:  --extra-cflags=-MDd --extra-cxxflags=-MDd --debug
-- Building ffmpeg for Debug
-- Generating F:\0812\vcpkg\packages\ffmpeg_x64-windows\debug\lib\avcodec.lib
-- Generating F:\0812\vcpkg\packages\ffmpeg_x64-windows\debug\lib\avdevice.lib
-- Generating F:\0812\vcpkg\packages\ffmpeg_x64-windows\debug\lib\avfilter.lib
-- Generating F:\0812\vcpkg\packages\ffmpeg_x64-windows\debug\lib\avformat.lib
-- Generating F:\0812\vcpkg\packages\ffmpeg_x64-windows\debug\lib\avutil.lib
-- Generating F:\0812\vcpkg\packages\ffmpeg_x64-windows\debug\lib\postproc.lib
-- Generating F:\0812\vcpkg\packages\ffmpeg_x64-windows\debug\lib\swresample.lib
-- Generating F:\0812\vcpkg\packages\ffmpeg_x64-windows\debug\lib\swscale.lib
-- Generating F:\0812\vcpkg\packages\ffmpeg_x64-windows\lib\avcodec.lib
-- Generating F:\0812\vcpkg\packages\ffmpeg_x64-windows\lib\avdevice.lib
-- Generating F:\0812\vcpkg\packages\ffmpeg_x64-windows\lib\avfilter.lib
-- Generating F:\0812\vcpkg\packages\ffmpeg_x64-windows\lib\avformat.lib
-- Generating F:\0812\vcpkg\packages\ffmpeg_x64-windows\lib\avutil.lib
-- Generating F:\0812\vcpkg\packages\ffmpeg_x64-windows\lib\postproc.lib
-- Generating F:\0812\vcpkg\packages\ffmpeg_x64-windows\lib\swresample.lib
-- Generating F:\0812\vcpkg\packages\ffmpeg_x64-windows\lib\swscale.lib
-- Installing: F:/0812/vcpkg/packages/ffmpeg_x64-windows/share/ffmpeg/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package ffmpeg[bzip2,core,ffmpeg,ffplay,ffprobe,ffserver,gpl,lzma,nonfree,opencl,openssl,vpx,x264]:x64-windows... done
Installing package ffmpeg[bzip2,core,ffmpeg,ffplay,ffprobe,ffserver,gpl,lzma,nonfree,opencl,openssl,vpx,x264]:x64-windows...
Installing package ffmpeg[bzip2,core,ffmpeg,ffplay,ffprobe,ffserver,gpl,lzma,nonfree,opencl,openssl,vpx,x264]:x64-windows... done
Elapsed time for package ffmpeg:x64-windows: 26.19 min

Total elapsed time: 50.21 min

**Comment by Voskrese** [comment]
@wangli28 

maybe this is an extra validation \ check, from the imported code
https://github.com/microsoft/vcpkg/pull/7129/files

but still there is an extra line feed, and this is not permissible

while I close of course
