### ISSUE TITLE
[New Port Request] tk

### ISSUE THREAD

**Issue by greenbrettmichael** [microsoft/vcpkg#7648]
Library name:
tk
Library description:
widget toolkit for tcl
Source repository URL:
https://github.com/tcltk/tk
Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
This package depends on this port request https://github.com/microsoft/vcpkg/issues/7647 . This port was dropped in this vcpkg commit for being incomplete, e69e5ad81d91198cfa1a871587a81b069007a02d

**Comment by greenbrettmichael** [comment]
@alexkaratarakis do you happen to remember the details on this port?

**Comment by silentmissile** [comment]
3 months later, I'm waiting for it, too

**Comment by kayarre** [comment]
what is meant by commit being dropped as incomplete?

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by EeliK** [comment]
tcl seems to be there now, is there a chance to get tk, too?
