### ISSUE TITLE
Outdated cppwinrt reference

### ISSUE THREAD

**Issue by tim-weis** [Microsoft/vcpkg#765]
Since publishing the initial [vcpkg](https://github.com/Microsoft/vcpkg/tree/master/ports/cppwinrt), the [C++/WinRT](https://github.com/Microsoft/cppwinrt) repository has been updated from a preview to an RTM release. The package description files should be updated to account for this change.

**Comment by ras0219-msft** [comment]
Thanks for the ping 😄.

Fixed by 71f1e11.
