### ISSUE TITLE
boost build faild

### ISSUE THREAD

**Issue by xpengc** [microsoft/vcpkg#7661]
**Host Environment**
- OS: windous
- Compiler:win7
**To Reproduce**
`./vcpkg install boost`

**Failure logs** 
Package: boost-build:x86-windows
vcpkg version : 2019.07.18 -nohash

**Comment by wangli28** [comment]
Hi @xpengc, thanks for posting this issue!
I can't reproduce this issue locally. I installed `boost-build:x86-windows` successfully with Windows 7 and vcpkg latest source. Could you provide your build log?

**Comment by xpengc** [comment]
Maybe this problem due to using Chinese for VS language . After changing the languate to English, boost-regex:x86-windows failed.  error log is: rule "msvc.init" unknow in moudle "toolset" .And syntax error at EOF of msvc.jam

**Comment by PhoebeHui** [comment]
If it is still an issue, please reopen.
