### ISSUE TITLE
[vcpkg] Port build tools for usage on the host. Where should those files be stored? 

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#7674]
related to #7667 
Qt builds a lot of additional tools/libs for the host and not the target system. 
Is there a common location or a policy where to put those files?
I figured out that a lot of build problems with the qt buildsystem is due to not properly separating those two different things.

Example:
Tools build for the host: e.g. qmake, uic, moc, rcc, designer, qml etc.
Libraries build for the host: Qt5Bootstrap.lib, Qt5QmlDevTools.lib

**Comment by Neumann-A** [comment]
I think i found a good solution: Since all host systems must also be vcpkg target triplets we can store the host libraries in tools/${PORT} in the target triplet which belongs to the host. And tell qt to use the binaries build in the hosts target triplet.
e.g. a build of qt5:arm64-windows on a x64 machine would use the tools from x64-windows(-static)/tools/qt5/bin

**Comment by cbezault** [comment]
That sort of works and is one of the hacks that we've used to get ports like protobuf-c to work. I'm currently working on a set of changes that should allow us to have tool dependencies in vcpkg. Until then there isn't really an official stance on how to do tools in vcpkg.
