### ISSUE TITLE
dlib:x64-windows build failure

### ISSUE THREAD

**Issue by fco06** [microsoft/vcpkg#7680]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2017

**To Reproduce**
`./vcpkg install dlib:x64-windows`

**Failure logs** 
The following packages will be built and installed:
    dlib[core]:x64-windows
Starting package 1/1: dlib:x64-windows
Building package dlib[core]:x64-windows...
-- Note: dlib only supports static library linkage. Building static library.
-- Using cached D:/Application/C++/lib/vcpkg/downloads/davisking-dlib-v19.17.tar.gz
-- Using source at D:/Application/C++/lib/vcpkg/buildtrees/dlib/src/v19.17-1edcba5375
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: D:/Application/C++/lib/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: D:/Application/C++/lib/vcpkg/buildtrees/dlib/x64-windows-dbg
    See logs for more information:
      D:\Application\C++\lib\vcpkg\buildtrees\dlib\install-x64-windows-dbg-out.log
      D:\Application\C++\lib\vcpkg\buildtrees\dlib\install-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/dlib/portfile.cmake:51 (vcpkg_install_cmake)
  scripts/ports.cmake:74 (include)

Error: Building package dlib:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: dlib:x64-windows
  Vcpkg version: 2019.07.18-nohash

[install-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/3500813/install-x64-windows-dbg-err.log)
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3500814/install-x64-windows-dbg-out.log)

**Comment by PhoebeHui** [comment]
@fco06, from the failure 'RegularExpression::compile(): Nested *?+. RegularExpression::compile(): Error in compile.'  it seems due to '++' in your directory. See https://gitlab.kitware.com/cmake/cmake/issues/16207.

**Comment by fco06** [comment]
It's ok, thanks :)
