### ISSUE TITLE
 Error: Building package qt5-speech:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by maorp** [microsoft/vcpkg#7683]
**Host Environment**
- OS: Windows.

**To Reproduce**
vcpkg install qt5:x64-windows

**Failure logs** 
 Error: Building package qt5-speech:x64-windows failed with: BUILD_FAILED

**Comment by wangli28** [comment]
Hi @maorp, thanks for posting this issue!
I can't reproduce this issue locally. I installed `qt5-speech:x64-windows` successfully with Visual Studio 2017 and vcpkg latest source. Could you provide your build log?

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
