### ISSUE TITLE
[curl] build failure

### ISSUE THREAD

**Issue by h1063135843** [microsoft/vcpkg#7684]
**Host Environment**
- OS:Windows
- Compiler: VS2019

**To Reproduce**
`./vcpkg install curl:x64-windows`

**Failure logs** 
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: D:/ProgramData/CMAKE/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: D:/ProgramData/vcpkg/buildtrees/curl/x64-windows-dbg
    See logs for more information:
      D:\ProgramData\vcpkg\buildtrees\curl\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/curl/portfile.cmake:133 (vcpkg_install_cmake)
  scripts/ports.cmake:74 (include)

Error: Building package curl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: curl:x64-windows
  Vcpkg version: 2019.07.18-nohash

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3501294/install-x64-windows-dbg-out.log)

**Comment by PhoebeHui** [comment]
@h1063135843, thanks for reporting this issue. 

From your log, it failed with 'fatal error C1001: An internal error has occurred in the compiler.' it looks a compiler bug, however I can't repro this issue with same toolset revsion(14.22.27905) and windows sdk(10.0.18362.0) with you. Everything build successfully for me, if the issue persist for you, please following [doc](https://docs.microsoft.com/en-us/cpp/overview/how-to-report-a-problem-with-the-visual-cpp-toolset?view=vs-2019#how-to-generate-a-repro) to get a preprocessed file, and report a vs feedback to compiler team.
