### ISSUE TITLE
[nghttp2] update to 1.39.2

### ISSUE THREAD

**Issue by geraldcombs** [microsoft/vcpkg#7686]
Library name: nghttp2

New version number: 1.39.2

This is a security update that fixes DoS issues discovered by Netflix: https://github.com/nghttp2/nghttp2/releases/tag/v1.39.2

**Comment by ehsan-mohammadi** [comment]
Now, `nghttp2` updated to the new version. Please close this issue.

**Comment by geraldcombs** [comment]
Thanks!
