### ISSUE TITLE
[New Port Request] opencensus-cpp

### ISSUE THREAD

**Issue by curtpm** [microsoft/vcpkg#7688]
Library name:
opencensus-cpp

Library description:
A stats collection and distributed tracing framework

Source repository URL:
https://github.com/census-instrumentation/opencensus-cpp

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JackBoosY** [comment]
Hi @curtpm, thanks for reporting this issue.
The port has been added in vcpkg, please update vcpkg and try to build it.

Thanks.
