### ISSUE TITLE
[New Port Request] cilantro

### ISSUE THREAD

**Issue by norlesh** [microsoft/vcpkg#7689]
Library name: Cilantro

Library description: A Lean and Efficient Library for Point Cloud Data Processing

Source repository URL: https://github.com/kzampog/cilantro

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by norlesh** [comment]
In support of my request I'd just like to point out that Cilantro only has two other dependencies (Pangolin and Eigen3 -  plus GLEW which is a dependency of Pangolin anyhow) which are already in the vcpkg system as opposed to the plethora that PCL pulls in, and bench marks provided by the Cilantro authors in a published paper appear to blow PCL out of the water!

**Comment by norlesh** [comment]
It appears the library was to good to be true - wont' work in Visual Studio without some work to the actual source code (due to conflicting OpenMP version support on different platforms as VS is still back at version 2.x while others are past that and using unsigned for loops).

**Comment by Voskrese** [comment]
intel icl, llvm clang, mingw gcc ?
linux, macos :wink:

**Comment by norlesh** [comment]
> intel icl, llvm clang, mingw gcc ?
> linux, macos 😉
"cilantro is developed and tested on Ubuntu 14.04, 16.04, and 18.04 variants using CMake" ... Initially I had read a thread in the Issues section that had reported limited success building on Windows - but my own attempts lead me to believe those reports had been overly optimistic... I have since retreated back to working with PCL
