### ISSUE TITLE
[New Port Request] opendht

### ISSUE THREAD

**Issue by pmahend1** [microsoft/vcpkg#7691]
**Library name:**  opendht

**Library description:** A C++11 Distributed Hash Table implementation

**Source repository URL:** https://github.com/savoirfairelinux/opendht

**Project homepage (if different from the source repository):** NA

**Anything else that is useful to know when adding (such as optional features the library may have that should be included):**  Provides CMake targets

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by ecouter** [comment]
would like to add this port to vcpkg !
