### ISSUE TITLE
Building vcpkg.exe fails

### ISSUE THREAD

**Issue by afamiglietti79** [microsoft/vcpkg#7704]
Hi All! I'm running windows 10 and visual studio 2017, and I can't get vcpkg to build. I run .\bootstrap-vcpkg.bat from powershell and get the following error: 

`C:\Users\afamiglietti\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj(27,3): error MSB4
019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\
BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Default.props" was not found.
 Confirm that the path in the <Import> declaration is correct, and that the fil
e exists on disk.
C:\Users\afamiglietti\vcpkg\toolsrc\vcpkg\vcpkg.vcxproj(27,3): error MSB4019: T
he imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildT
ools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Default.props" was not found. Confi
rm that the path in the <Import> declaration is correct, and that the file exis
ts on disk.
C:\Users\afamiglietti\vcpkg\toolsrc\vcpkgmetricsuploader\vcpkgmetricsuploader.v
cxproj(27,3): error MSB4019: The imported project "C:\Program Files (x86)\Micro
soft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Defau
lt.props" was not found. Confirm that the path in the <Import> declaration is c
orrect, and that the file exists on disk.
C:\Users\afamiglietti\vcpkg\scripts\bootstrap.ps1 : Building vcpkg.exe failed.
Please ensure you have installed Visual Studio with the Desktop C++ workload
and the Windows SDK for Desktop C++.
At line:1 char:4
+ & {& 'C:\Users\afamiglietti\vcpkg\scripts\bootstrap.ps1' }
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,bootstrap.ps1`

I've installed the Desktop C++ workload, and every Windows SDK I can find in Visual Studio. A quick look at the visual studio directory confirms the path given in the error does not exist...

Any idea what's going wrong?

**Comment by contre** [comment]
It looks like it is using the build tools and not the IDE install. Is it your intent for it to use the IDE?

**Comment by afamiglietti79** [comment]
I wouldn't say I intend either way, just trying to get it working :) If I need to install another dependency, I'm happy to do that, just point me at what I need to install...

**Comment by contre** [comment]
I believe you are falling foul of vcpkg’s automatic detection of tool sets to use. 

https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md#vcpkg_visual_studio_path Describes the algo they use to determine what tools to use and I believe that your build tools install is coming up first in the list. Something is not right in your build tools install and hence the error you’re getting.

Not exactly sure what you need to do to fix it but anted to help point you in the right direction.

**Comment by afamiglietti79** [comment]
Oh! I get it now. I went it and installed the SDK in the "build tools" section of the Visual Studio installer. Working now! Thanks!
