### ISSUE TITLE
[tesseract:x64-windows] build failure

### ISSUE THREAD

**Issue by abcping123** [microsoft/vcpkg#7709]
**Host Environment**
- OS: Windows 10 v1903
- Compiler: Visual Studio 2017

**To Reproduce**
`vcpkg install tesseract`

**Failure logs** 
```
ninja: error: 'C:/Intel/vcpkg-master/installed/x64-windows/debug/lib/webp.lib', 
needed by 'bin/tesseract.exe', missing and no known rule to make it
```

There is only webp**d**.lib in debug-lib folder, maybe some spell mistake?

```
vcpkg depend-info tesseract
libjpeg-turbo:
liblzma:
zlib:
giflib:
libpng: zlib
tiff: libjpeg-turbo, liblzma, zlib
leptonica: giflib, libjpeg-turbo, libpng, tiff, zlib
tesseract: leptonica
```
But I checked out the dependencies, and found no webp needed.

**Comment by abcping123** [comment]
I upgrade lastest leptonica 1.78.0 (1.76.0 before), maybe it supports webp in this version.

**Comment by JackBoosY** [comment]
It's a leptonica config.cmake bug.

**Comment by JackBoosY** [comment]
Hi @abcping123, thanks for reporting this issue.
I've fixed this issue. Please update vcpkg and rebuild tesseract.

Thanks.
