### ISSUE TITLE
SOUI

### ISSUE THREAD

**Issue by wb136959813** [microsoft/vcpkg#7711]
Library name:soui

Library description:SOUI is currently one of the few lightweight open-source DirectUI libraries for quickly developing window desktop programs. Its predecessor was Duiengine, and earlier it was derived from the Jinshan Guardian open source version of the UI library Bkwin. After years of continuous updates, this library is available.

Source repository URL:https://github.com/SOUI2/

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
