### ISSUE TITLE
Local cmake installation failure

### ISSUE THREAD

**Issue by tfussell** [Microsoft/vcpkg#772]
After the commits improving local dependency installation yesterday afternoon, local cmake installation has stopped working. The last good commit appears to be 47b53b9015deaa2f569d788447254c8bc3de96a9. 

Here is the output of the command on my machine running Windows 8.1 with Visual Studio 2017 RC:

```
C:\Users\Thomas\Development\vcpkg-ms>vcpkg install zlib

Download cmake
No suitable version of cmake was found (requires 3.8.0 or higher). Download portable version?
[Y] Yes  [N] No  [A] Always Allow Downloads  [?] Help (default is "Y"): y
Expected dependency downloaded path to be C:/Users/Thomas/Development/vcpkg-ms/downloads/cmake-3.8.0-rc1-win32-x86/bin/c
make.exe, but was C:/Users/Thomas/Development/vcpkg-ms/downloads/cmake-3.8.0-rc1-win32-x86.zip
```

Investigating the problem, it seems that in `vcpkg_paths.cpp` (line 75), fetchDependency.ps1 returns the `$downloadPath` for cmake which is `"$downloadsDir\cmake-3.8.0-rc1-win32-x86.zip"`, but line 85 then compares that `$downloadPath` with `expected_download_path` which is a parameter set to `downloads_folder / "cmake-3.8.0-rc1-win32-x86" / "bin" / "cmake.exe"`. I can make a pull request to fix this, but I'm not sure which one should be changed, expected_download_path or actual_download_path.

To reproduce the problem, it should be sufficient to remove cmake from `%PATH%` and delete the local from the `vcpkg/downloads/` folder if it exists and then attempt to install a package with vcpkg.

**Comment by ras0219-msft** [comment]
Hi @tfussell,

Thank you very much for reporting this issue with such a detailed analysis! We've been able to fix it much faster due to your efforts 👍.
