### ISSUE TITLE
How do I search which OS a port is supported on?

### ISSUE THREAD

**Issue by vadi2** [microsoft/vcpkg#7724]
> When asking a question please also include where you looked for an answer (so we can update the documentation if needed).

Searched in `./vcpkg help` and markdown documentation in github.

How can I see what OS's a port is supported on? https://devblogs.microsoft.com/cppblog/vcpkg-2019-07-update/ hints that not all ports are supported on all OS's, and I couldn't find a clear way to see this per-port.

**Comment by cbezault** [comment]
There isn't currently a way to see which OSes support which ports but we're currently working on it. The numbers in that blog post came from our CI system.
