### ISSUE TITLE
paho-mqttpp3 missing reference to C library headers

### ISSUE THREAD

**Issue by Pedersen175** [microsoft/vcpkg#7725]
Seems like Paho CPP library cannot find Paho C library headers when using Paho CPP in a project. In Visual Studio 2017: Including "mqtt/async_client.h" returns error "Cannot open include file: 'MQTTAsync.h'"

Currently installed with "vcpkg integrate install" called:
paho-mqtt:x86-windows 1.3.0
paho-mqttpp3:x86-windows 1.0.1
paho-mqttpp3[ssl]:x86-windows

Problem can temporary be circumvent by adding "Additional Include Directories" in Visual Studio project file: <CHECKOUTDIR>\vcpkg\packages\paho-mqtt_x86-windows\include\paho-mqtt

Any known way to easily fix this? Using checkoutdir is not a durable solution as vcpkg directory might be different for people.

**Comment by Pedersen175** [comment]
Temporary solution to use in "Additional Include Directories": $(VcpkgRoot)include\paho-mqtt

**Comment by shuitianxu** [comment]
Now can find reference to C library headers.
