### ISSUE TITLE
[tbb] Doesn't fail to build without make installed

### ISSUE THREAD

**Issue by cbezault** [microsoft/vcpkg#7727]
**Bug**
TBB "succeeds" to build without make installed.

**Environment**
- OS: Linux
- Compiler: GCC8

**To Reproduce**
1. Get a machine without make installed
2. ./vcpkg install tbb
3. ./vcpkg install openvdb[core]

Openvdb will fail to build because tbb didn't actually build itself.

**Expected behavior**
TBB should be marked as BUILD_FAILED.

**Comment by JackBoosY** [comment]
@cbezault The tool `make` should be installed by **default** in LINUX. How can we fix this issue?

**Comment by cbezault** [comment]
Make wasn't installed by default on the Ubuntu vm I was working on. Anyway it's not really that having make or not is the issue here. It's that we didn't correctly identify that the port wasn't correctly built.

**Comment by JackBoosY** [comment]
I cannot repro this issue on my linux vm.
My gcc version is 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11).

**Comment by cbezault** [comment]
Do you have make installed?

**Comment by JackBoosY** [comment]
I found this:
In _SOURCE_PATH/cmake/TBBBuild.cmake_ line 150-164:
```
    set(make_tool_name make)
    if (CMAKE_SYSTEM_NAME MATCHES "Windows")
        set(make_tool_name gmake)
    elseif (CMAKE_SYSTEM_NAME MATCHES "Android")
        set(make_tool_name ndk-build)
    endif()

    find_program(TBB_MAKE_TOOL ${make_tool_name} DOC "Make-tool to build Intel TBB." REQUIRED)
    mark_as_advanced(TBB_MAKE_TOOL)

    if (NOT TBB_MAKE_TOOL)
        message(STATUS "Intel TBB can not be built: required make-tool (${make_tool_name}) was not found")
        set(${tbb_build_CONFIG_DIR} ${tbb_build_CONFIG_DIR}-NOTFOUND PARENT_SCOPE)
        return()
    endif()
```

If no build tool is found, the build process will exit without warning or error.
So I think we should add keyword `REQUIRED` to `find_program` to solve this issue.

**Comment by JackBoosY** [comment]
Related: #8864.

**Comment by JackBoosY** [comment]
Close this issue via #9188 merged.
