### ISSUE TITLE
[winpcap:x86-windows-static ] build failure

### ISSUE THREAD

**Issue by ricjhill** [microsoft/vcpkg#7732]
**Host Environment**
- OS: [ Microsoft Windows [Version 10.0.17134.950] ] 
- Compiler:   gcc version 8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)

**To Reproduce**
`./vcpkg install xxxx`
vcpkg install winpcap:x86-windows-static

**Failure logs** 
-Cut and past the appropriate build messages from the console output.

The following packages will be built and installed:
    winpcap[core]:x86-windows-static
Starting package 1/1: winpcap:x86-windows-static
Building package winpcap[core]:x86-windows-static...
-- Using cached C:/Users/Nutzer/vcpkg/downloads/WpcapSrc_4_1_3.zip
-- Using cached C:/Users/Nutzer/vcpkg/downloads/Wpcap_license.htm
-- Extracting source C:/Users/Nutzer/vcpkg/downloads/WpcapSrc_4_1_3.zip
-- Applying patch C:/Users/Nutzer/vcpkg/buildtrees/winpcap/src/packetNtx.patch
-- Applying patch C:/Users/Nutzer/vcpkg/buildtrees/winpcap/src/wpcap.patch
-- Applying patch C:/Users/Nutzer/vcpkg/ports/winpcap/create_lib.patch
-- Applying patch C:/Users/Nutzer/vcpkg/ports/winpcap/fix-create-lib-batch.patch
-- Using source at C:/Users/Nutzer/vcpkg/buildtrees/winpcap/src/4_1_3-33a2717018
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:58 (message):
    Command failed: devenv.exe Packet.sln /Upgrade
    Working Directory: C:/Users/Nutzer/vcpkg/buildtrees/winpcap/src/4_1_3-33a2717018/packetNtx/Dll/Project
    Error code: The system cannot find the file specified
    See logs for more information:

Call Stack (most recent call first):
  ports/winpcap/portfile.cmake:59 (vcpkg_execute_required_process)
  scripts/ports.cmake:75 (include)

Error: Building package winpcap:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: winpcap:x86-windows-static
  Vcpkg version: 2019.07.19-nohash

Additionally, attach any relevant sections from the log files above.

-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JackBoosY** [comment]
@ricjhill It seems that vcpkg can't find _ports/winpcap/Packet.sln_ or has no permission to copy it to buildtrees folder.
Please confirm that this file exists and rebuild winpcap after the non-system disk clone vcpkg.

My log:
```
PS F:\vcpkg> .\vcpkg.exe install winpcap:x86-windows-static
The following packages will be built and installed:
    winpcap[core]:x86-windows-static
Starting package 1/1: winpcap:x86-windows-static
Building package winpcap[core]:x86-windows-static...
-- Using cached F:/vcpkg/downloads/WpcapSrc_4_1_3.zip
-- Using cached F:/vcpkg/downloads/Wpcap_license.htm
-- Extracting source F:/vcpkg/downloads/WpcapSrc_4_1_3.zip
-- Applying patch F:/vcpkg/buildtrees/winpcap/src/packetNtx.patch
-- Applying patch F:/vcpkg/buildtrees/winpcap/src/wpcap.patch
-- Applying patch F:/vcpkg/ports/winpcap/create_lib.patch
-- Applying patch F:/vcpkg/ports/winpcap/fix-create-lib-batch.patch
-- Using source at F:/vcpkg/buildtrees/winpcap/src/4_1_3-33a2717018
-- Building F:/vcpkg/buildtrees/winpcap/src/4_1_3-33a2717018/packetNtx/Dll/Project/Packet.sln for Release
-- Building F:/vcpkg/buildtrees/winpcap/src/4_1_3-33a2717018/packetNtx/Dll/Project/Packet.sln for Debug
-- Building F:/vcpkg/buildtrees/winpcap/src/4_1_3-33a2717018/wpcap/PRJ/wpcap.sln for Release
-- Building F:/vcpkg/buildtrees/winpcap/src/4_1_3-33a2717018/wpcap/PRJ/wpcap.sln for Debug
-- Installing: F:/vcpkg/packages/winpcap_x86-windows-static/include/bittypes.h
-- Installing: F:/vcpkg/packages/winpcap_x86-windows-static/include/ip6_misc.h
-- Installing: F:/vcpkg/packages/winpcap_x86-windows-static/include/Packet32.h
-- Installing: F:/vcpkg/packages/winpcap_x86-windows-static/include/pcap.h
-- Installing: F:/vcpkg/packages/winpcap_x86-windows-static/include/pcap-bpf.h
-- Installing: F:/vcpkg/packages/winpcap_x86-windows-static/include/pcap-namedb.h
-- Installing: F:/vcpkg/packages/winpcap_x86-windows-static/include/pcap-stdinc.h
-- Installing: F:/vcpkg/packages/winpcap_x86-windows-static/include/remote-ext.h
-- Installing: F:/vcpkg/packages/winpcap_x86-windows-static/include/Win32-Extensions.h
-- Installing: F:/vcpkg/packages/winpcap_x86-windows-static/include/pcap/bluetooth.h
-- Installing: F:/vcpkg/packages/winpcap_x86-windows-static/include/pcap/bpf.h
-- Installing: F:/vcpkg/packages/winpcap_x86-windows-static/include/pcap/namedb.h
-- Installing: F:/vcpkg/packages/winpcap_x86-windows-static/include/pcap/pcap.h
-- Installing: F:/vcpkg/packages/winpcap_x86-windows-static/include/pcap/sll.h
-- Installing: F:/vcpkg/packages/winpcap_x86-windows-static/include/pcap/usb.h
-- Installing: F:/vcpkg/packages/winpcap_x86-windows-static/include/pcap/vlan.h
-- Installing: F:/vcpkg/packages/winpcap_x86-windows-static/lib/Packet.lib
-- Installing: F:/vcpkg/packages/winpcap_x86-windows-static/lib/wpcap.lib
-- Installing: F:/vcpkg/packages/winpcap_x86-windows-static/debug/lib/Packet.lib
-- Installing: F:/vcpkg/packages/winpcap_x86-windows-static/debug/lib/wpcap.lib
-- Performing post-build validation
-- Performing post-build validation done
Building package winpcap[core]:x86-windows-static... done
Installing package winpcap[core]:x86-windows-static...
Installing package winpcap[core]:x86-windows-static... done
Elapsed time for package winpcap:x86-windows-static: 2.281 min

Total elapsed time: 2.281 min

PS F:\vcpkg>
```

Thanks.

**Comment by ricjhill** [comment]
It  seems like  I  download  the  source  from 

 https://www.winpcap.org/install/bin/WpcapSrc_4_1_3.zip

When this  is  installed  Packet.slmn does  not  exist in  vcpkg\ports\winpcap    Packet.vcxproj  exists


 Directory of C:\Users\Nutzer\vcpkg\ports\winpcap

16/08/2019  11:59    <DIR>          .
16/08/2019  11:59    <DIR>          ..
16/08/2019  11:59               173 CONTROL
16/08/2019  11:59               805 create_bin.bat
16/08/2019  11:59             1,097 create_lib.patch
16/08/2019  11:59             1,577 fix-create-lib-batch.patch
16/08/2019  11:59            43,409 Packet.vcxproj
16/08/2019  11:59            39,841 packetNtx.patch.in
16/08/2019  11:59             6,009 portfile.cmake
16/08/2019  11:59            42,602 wpcap.patch.in
16/08/2019  11:59            24,419 wpcap.vcxproj
               9 File(s)        159,932 bytes

**Comment by JackBoosY** [comment]
@ricjhill You can unzip _vcpkg/downloads/WpcapSrc_4_1_3.zip_ and find **Packet.sln** in _source\packetNtx\Dll\Project_

**Comment by ricjhill** [comment]
Hmm  there is no  source\packetNtx     dir   . I  can find  Packet.sln    in two locatons 

This is the orginal (unzipped)
C:\Users\Nutzer\vcpkg\downloads\WpcapSrc_4_1_3\winpcap\packetNtx\Dll\Project

I  assume  it  is  was  copied to

C:\Users\Nutzer\vcpkg\buildtrees\winpcap\src\4_1_3-33a2717018\packetNtx\Dll\Project

and  

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       16/11/2006     17:29            601 GNUmakefile
-a----       21/08/2019     12:27          33933 Packet.dsp
-a----       22/09/2003     01:16            831 Packet.dsw
-a----       08/08/2008     10:13           4500 Packet.sln
-a----       21/08/2019     12:27          33965 Packet.vcproj

**Comment by ricjhill** [comment]
So why  cant  the  file  be  found

```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:58 (message):
    Command failed: devenv.exe Packet.sln /Upgrade
    Working Directory: C:/Users/Nutzer/vcpkg/buildtrees/winpcap/src/4_1_3-33a2717018/packetNtx/Dll/Project
    Error code: The system cannot find the file specified
```

**Comment by ricjhill** [comment]
Maybe  devenv  isnt  on  the  path...  and  the  error  message is not  clear

**Comment by JackBoosY** [comment]
I guess the reason is you don't have admin permission, because vcpkg is installed on the system disk.

**Comment by ricjhill** [comment]
Ive  run these commands as an admin. Id  expect that  would  be  enough. Whats maybe  interesting is that  Ive  got  Build Tools 2019  installed and  I  cant  find devenv. exe in its install. I  will trying again after   instaling  the  2019 Community   IDE.

**Comment by ricjhill** [comment]
So, this is the situation. I  installed Visual Studio 2019 Community Edition with the default components.

I then opened  the  native tools CMD  for  x64.  I  found  it  by  typing 'native' in the  search bar.

cd C:\Users\Nutzer\vcpkg
C:\Users\Nutzer\vcpkg>vcpkg install winpcap:x64-windows-static

was  successful, the  libs were placed in C:/Users/Nutzer/vcpkg/packages/winpcap_x64-windows-static/

I though Id try  the  x86  version so I  ran  

C:\Users\Nutzer\vcpkg>vcpkg install winpcap

that  work, so you  can close this bug

**Comment by ricjhill** [comment]
To summarise. Buildtools 2019 did not  contain the  devenv.exe so vcpkg build was failing.  Thanks for your help.

```
C:\Users\Nutzer\vcpkg>vcpkg install winpcap
The following packages will be built and installed:
    winpcap[core]:x86-windows
Starting package 1/1: winpcap:x86-windows
Building package winpcap[core]:x86-windows...
-- Using cached C:/Users/Nutzer/vcpkg/downloads/WpcapSrc_4_1_3.zip
-- Using cached C:/Users/Nutzer/vcpkg/downloads/Wpcap_license.htm
-- Extracting source C:/Users/Nutzer/vcpkg/downloads/WpcapSrc_4_1_3.zip
-- Applying patch C:/Users/Nutzer/vcpkg/buildtrees/winpcap/src/packetNtx.patch
-- Applying patch C:/Users/Nutzer/vcpkg/buildtrees/winpcap/src/wpcap.patch
-- Applying patch C:/Users/Nutzer/vcpkg/ports/winpcap/create_lib.patch
-- Applying patch C:/Users/Nutzer/vcpkg/ports/winpcap/fix-create-lib-batch.patch
-- Using source at C:/Users/Nutzer/vcpkg/buildtrees/winpcap/src/4_1_3-2020b05bdd
-- Building C:/Users/Nutzer/vcpkg/buildtrees/winpcap/src/4_1_3-2020b05bdd/packetNtx/Dll/Project/Packet.sln for Release
-- Building C:/Users/Nutzer/vcpkg/buildtrees/winpcap/src/4_1_3-2020b05bdd/packetNtx/Dll/Project/Packet.sln for Debug
-- Building C:/Users/Nutzer/vcpkg/buildtrees/winpcap/src/4_1_3-2020b05bdd/wpcap/PRJ/wpcap.sln for Release
-- Building C:/Users/Nutzer/vcpkg/buildtrees/winpcap/src/4_1_3-2020b05bdd/wpcap/PRJ/wpcap.sln for Debug
-- Installing: C:/Users/Nutzer/vcpkg/packages/winpcap_x86-windows/include/bittypes.h
-- Installing: C:/Users/Nutzer/vcpkg/packages/winpcap_x86-windows/include/ip6_misc.h
-- Installing: C:/Users/Nutzer/vcpkg/packages/winpcap_x86-windows/include/Packet32.h
-- Installing: C:/Users/Nutzer/vcpkg/packages/winpcap_x86-windows/include/pcap.h
-- Installing: C:/Users/Nutzer/vcpkg/packages/winpcap_x86-windows/include/pcap-bpf.h
-- Installing: C:/Users/Nutzer/vcpkg/packages/winpcap_x86-windows/include/pcap-namedb.h
-- Installing: C:/Users/Nutzer/vcpkg/packages/winpcap_x86-windows/include/pcap-stdinc.h
-- Installing: C:/Users/Nutzer/vcpkg/packages/winpcap_x86-windows/include/remote-ext.h
-- Installing: C:/Users/Nutzer/vcpkg/packages/winpcap_x86-windows/include/Win32-Extensions.h
-- Installing: C:/Users/Nutzer/vcpkg/packages/winpcap_x86-windows/include/pcap/bluetooth.h
-- Installing: C:/Users/Nutzer/vcpkg/packages/winpcap_x86-windows/include/pcap/bpf.h
-- Installing: C:/Users/Nutzer/vcpkg/packages/winpcap_x86-windows/include/pcap/namedb.h
-- Installing: C:/Users/Nutzer/vcpkg/packages/winpcap_x86-windows/include/pcap/pcap.h
-- Installing: C:/Users/Nutzer/vcpkg/packages/winpcap_x86-windows/include/pcap/sll.h
-- Installing: C:/Users/Nutzer/vcpkg/packages/winpcap_x86-windows/include/pcap/usb.h
-- Installing: C:/Users/Nutzer/vcpkg/packages/winpcap_x86-windows/include/pcap/vlan.h
-- Installing: C:/Users/Nutzer/vcpkg/packages/winpcap_x86-windows/lib/Packet.lib
-- Installing: C:/Users/Nutzer/vcpkg/packages/winpcap_x86-windows/lib/wpcap.lib
-- Installing: C:/Users/Nutzer/vcpkg/packages/winpcap_x86-windows/debug/lib/Packet.lib
-- Installing: C:/Users/Nutzer/vcpkg/packages/winpcap_x86-windows/debug/lib/wpcap.lib
-- Installing: C:/Users/Nutzer/vcpkg/packages/winpcap_x86-windows/bin/Packet.dll
-- Installing: C:/Users/Nutzer/vcpkg/packages/winpcap_x86-windows/bin/wpcap.dll
-- Installing: C:/Users/Nutzer/vcpkg/packages/winpcap_x86-windows/debug/bin/Packet.dll
-- Installing: C:/Users/Nutzer/vcpkg/packages/winpcap_x86-windows/debug/bin/wpcap.dll
-- Performing post-build validation
-- Performing post-build validation done

Building package winpcap[core]:x86-windows... done
Installing package winpcap[core]:x86-windows...
Installing package winpcap[core]:x86-windows... done
Elapsed time for package winpcap:x86-windows: 6.309 min
```

**Comment by JackBoosY** [comment]
I am curious if you did not install devenv how do you build vcpkg.

**Comment by ricjhill** [comment]
Good  question. I  missed that.   I  have  a  cpp toolchain installed


$whereis  cpp
cpp: /usr/bin/cpp /lib/cpp /mnt/c/ProgramData/chocolatey/bin/cpp.exe /mnt/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/cpp.exe /usr/share/man/man1/cpp.1.gz
