### ISSUE TITLE
Powershell integration writing on a wrong profile path

### ISSUE THREAD

**Issue by izxle** [microsoft/vcpkg#7734]
**Describe the bug**
When running the Powershell integration, the .ps1 file was written in `$home\PowerShell/Microsoft.PowerShell_profile.ps1` but running `$profile` returned `$home\WindowsPowerShell/Microsoft.PowerShell_profile.ps1`, this meant the Import module command was not being run.

**Environment**
- OS: Windows 10

**To Reproduce**
1. ./vcpkg install xxxx
2. See error
Repro code when

**Expected behavior**
The ps1 file should be written in the correct directory

**Failure logs** 
After I changed the file to the correct directory I got this error:

    Microsoft.PowerShell_profile.ps1 cannot be loaded because running scripts is disabled on this 
    system. For more information, see about_Execution_Policies at ...

This was fixed by changing the Execution policy

**Comment by wangli28** [comment]
Thanks for posting this issue! Duplicate with #5413, so I am closing this issue for now.
