### ISSUE TITLE
poco[mysql] build failure

### ISSUE THREAD

**Issue by fco06** [microsoft/vcpkg#7736]
**Host Environment**
- OS: Windows 10
- Compiler: VS2017

**To Reproduce**
`./vcpkg install poco poco[mysql] --recurse`

**Failure logs** 
PS D:\Application\cpp\lib\vcpkg> .\vcpkg.exe install poco poco[mysql] --recurse
The following packages will be rebuilt:
    poco[core,mysql]:x64-windows
Starting package 1/2: poco:x64-windows
Removing package poco:x64-windows...
Removing package poco:x64-windows... done
Purging package poco:x64-windows...
Purging package poco:x64-windows... done
Elapsed time for package poco:x64-windows: 1.186 s
Starting package 2/2: poco:x64-windows
Building package poco[core,mysql]:x64-windows...
Warning: abi keys are missing values:
    expat
    libmysql
    libpng
    libpq
    pcre
    sqlite3
    zlib

-- Using cached D:/Application/cpp/lib/vcpkg/downloads/pocoproject-poco-8a127d6f16795d914cadc342d3f4f3b9b7999e3b.tar.gz
-- Using source at D:/Application/cpp/lib/vcpkg/buildtrees/poco/src/b9b7999e3b-76e03302ae
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: D:/Application/cpp/lib/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
    Working Directory: D:/Application/cpp/lib/vcpkg/buildtrees/poco/x64-windows-dbg
    See logs for more information:
      D:\Application\cpp\lib\vcpkg\buildtrees\poco\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/poco/portfile.cmake:83 (vcpkg_install_cmake)
  scripts/ports.cmake:75 (include)

Error: Building package poco:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: poco:x64-windows
  Vcpkg version: 2019.07.19-nohash

** ERROR LOG **
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3511827/install-x64-windows-dbg-out.log)

**Comment by JackBoosY** [comment]
As #7698 said, poco[mysql] requires official support for the latest mysql version.

**Comment by linquize** [comment]
Current situation is that libmysql is already 8.0, but poco is still 1.9.2.

Waiting for vcpkg to merge poco 1.10 #10326, in order to support building poco with libmysql 8.0

**Comment by JackBoosY** [comment]
Now this issue is partly resolved but still has some problem, please track #14249.
