### ISSUE TITLE
cmake find_package cannot find harfbuzz

### ISSUE THREAD

**Issue by XHMM** [microsoft/vcpkg#7737]
I installed `freetype` and `harfbuzz` using `vcpkg`, but when i camke build, it can find `freetype` but cannot find `harfbuzz`, why?

cmakefile:
```
find_package(Freetype REQUIRED)
if(NOT FREETYPE_FOUND)
    message(STATUS "freetype:   NO")
else()
    message(STATUS "freetype:   YES (ver ${FREETYPE_VERSION})")
endif()

find_package(harfbuzz CONFIG REQUIRED)
if(NOT HARFBUZZ_FOUND)
    message(STATUS "harfbuzz:    NO")
else()
    message(STATUS "harfbuzz:    YES (ver ${HARFBUZZ_VERSION})")
endif()
```

output:
![image](https://user-images.githubusercontent.com/24786522/63209214-8fefb680-c110-11e9-8e4f-a7b65ed2aa1a.png)

**Comment by wangli28** [comment]
Port name in variable `harfbuzz_FOUND` need same with `find_package`, like this:
```
find_package(Freetype REQUIRED)
if(NOT Freetype_FOUND)
    message(STATUS "freetype:   NO")
else()
    message(STATUS "freetype:   YES (ver ${FREETYPE_VERSION})")
endif()

find_package(harfbuzz CONFIG REQUIRED)
if(NOT harfbuzz_FOUND)
    message(STATUS "harfbuzz:    NO")
else()
    message(STATUS "harfbuzz:    YES (ver ${HARFBUZZ_VERSION})")
endif()
```
My output:
![image](https://user-images.githubusercontent.com/47812810/63245826-ad00c280-c293-11e9-8d2f-7b836f3ab0e3.png)

**Comment by XHMM** [comment]
thanks, I am new to cmake, I always thought `xx` in `xx_FOUND`  should be all uppercase.

I also found that `Freetype_FOUND` and `FREETYPE_FOUND` both worked, but `harfbuzz_FOUND` work and `HARFBUZZ_FOUND` not work. 😅
