### ISSUE TITLE
Packages should install batch forwarders into `tools\`

### ISSUE THREAD

**Issue by ras0219-msft** [microsoft/vcpkg#774]
Related to #761.

For users that would like to run package-specific tools, it would be most convenient to only have one directory to add to their path. The obvious choice is the `tools\` folder for their current working architecture.

However, in the general case executables can require conflicting app-local DLLs and therefore must be installed into separate subdirectories.

This is a common problem faced by other platforms such as Chocolatey and Git for Windows. The most common solution is batch files to forward to the true executable, however other options include symlinks (requires admin access by default on Windows) and generating stub forwarding executables.

**Comment by LilyWangL** [comment]
This issue hasn’t been updated in a year, if it is still an issue, please reopen.
