### ISSUE TITLE
qt5-base install error

### ISSUE THREAD

**Issue by ehsan-mohammadi** [microsoft/vcpkg#7742]
I updated `harfbuzz` to the new version (#7740). But after that, when I try to install `qt5-base` for `x64-windows-static` triplet, I get this error:

> ERROR: Feature 'system-harfbuzz' was enabled, but the pre-condition 'features.harfbuzz && libs.harfbuzz' failed.

Any help?

**Comment by Neumann-A** [comment]
One of the configure.json in the source path of qt5-base is probably doing a test on the harfbuzz library and is missing the information that it needs to link the dependent libraries of harbuzz. 
You probably need to turn on `verbose` in `configure_qt.cmake` in qt5-base to somehow be able to debug it.

**Comment by ehsan-mohammadi** [comment]
@Neumann-A Many thanks, I'll do your suggestion.

**Comment by PhoebeHui** [comment]
Related to https://github.com/microsoft/vcpkg/pull/10146

**Comment by PhoebeHui** [comment]
This issue should be fixed now, harfbuzz has upgraded to 2.6.6.

**Comment by FrankHeimes** [comment]
@PhoebeHui I just attempted to update my `vcpkg` packages and OPs exact same error happened to me again, even though `harfbuzz` has arrived at version 2.7.2. So the error has either _not_ been fixed or it has been reintroduced.
