### ISSUE TITLE
What ports have been tested for a triplet

### ISSUE THREAD

**Issue by pwm1234** [microsoft/vcpkg#7748]
In the changelog and release notes, there is a port count per triplet tested list. How do I find out what ports have been tested for what triplets? I ask because I am having trouble getting my vcpkg build/installation to work on linux-x64 (ubuntu 18) and I would like to know the ports that have not been tested on linux-x64.

**Comment by Neumann-A** [comment]
I dont think this will give you the information you want. 
If CI is succesful it just means the port builds successfully. 
It does not mean you can actually use the port successfully. 

Although I would also like to have a list to know when a failure I see is actually an expected failure and when not.

**Comment by pwm1234** [comment]
Yes, that is exactly what I am looking for. I would like to know whether or not CI is unsuccessful at building the port. That will help me know what ports I should avoid on a particular platform (aka triplet).

**Comment by Neumann-A** [comment]
Download build-results from latest baseline build (x64-linux here):
https://dev.azure.com/vcpkg/public/_build/results?buildId=9824&view=results

XML with all ports and their build status. Or you klick on the test failure report to see which ports failed

**Comment by PhoebeHui** [comment]
Currently, we also have https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt to list the expected failed ports.

**Comment by PhoebeHui** [comment]
@pwm1234, reopen this issue if it still be a problem for you.
