### ISSUE TITLE
[liblas] generated cmake config has absolute path to build machine

### ISSUE THREAD

**Issue by pwm1234** [microsoft/vcpkg#7749]
**Host Environment**
- OS: Ubuntu 18
- Compiler: gcc 7.4

**To Reproduce**
`./vcpkg install liblas`
`./vcpkg export liblas`

**Failure logs** 
`share/cmake/libLAS/libls-depends-release.cmake` has absolute paths in its definition of `IMPORTED_LINK_INTERFACE_LIBRARIES` that are wrong when exported.

**Comment by Neumann-A** [comment]
are you setting `VCPKG_BUILD_TYPE` to release in your own triplet?

nevertheless the call to
`vcpkg_fixup_cmake_targets`
should be unconditional in the portfile of liblas

**Comment by pwm1234** [comment]
I am just using the predefined triplet `x64-linux`. I will make the call to `vcpkg_fixup_cmake_targets` unconditional and see what changes.

**Comment by pwm1234** [comment]
When I made the call to `vcpkg_fixup_cmake_targets` unconditional, I got the following error:

-- Using source at /home/local/SRI/e27290/projects/aspn-mapmatch/vcpkg/buildtrees/liblas/src/libLAS-1-3593c22f96
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
CMake Error at scripts/cmake/vcpkg_fixup_cmake_targets.cmake:53 (message):
  
 ```
 '/home/local/SRI/e27290/projects/aspn-mapmatch/vcpkg/packages/liblas_x64-linux/debug/share/cmake/liblas'
  does not exist.
Call Stack (most recent call first):
  ports/liblas/portfile.cmake:42 (vcpkg_fixup_cmake_targets)
  scripts/ports.cmake:74 (include)
```
which goes away when I explicitly set VCPKG_BUILD_TYPE in the x64-linux triplet file. But some ports do not build correctly on linux when building only the release configuration.

**Comment by Voskrese** [comment]
default triplet? x64-linux?

**Comment by pwm1234** [comment]
Yes, I am using the default triplet, which is `x64-linux`, with no changes, which means `VCPKG_BUILD_TYPE` is not set.

**Comment by JackBoosY** [comment]
I think `IMPORTED_LINK_INTERFACE_LIBRARIES` should use a relative path instead of an absolute path.

**Comment by JackBoosY** [comment]
Hi @pwm1234, thanks for reporting this issue.
I've fixed this issue, please update vcpkg and rebuild liblas.

Thanks.
