### ISSUE TITLE
[New Port Request] <qgis>

### ISSUE THREAD

**Issue by longhuan2018** [microsoft/vcpkg#7761]
Library name: qgis

Library description: QGIS is a free, open source, cross platform (lin/win/mac) geographical information system (GIS) 

Source repository URL: https://github.com/qgis/QGIS

Project homepage (if different from the source repository): http://qgis.org

It also dependent on the libspatialindex and qtkeychain libraries, which are not yet included in vcpkg, so you also need to create ports for these dependent libraries.
- [x] New port libspatialindex

- [x] New port qtkeychain

- [x] New port qgis

**Comment by longhuan2018** [comment]
If you want to compile qgis server, it needs fastcgi support.

- [ ] New port fastcgi

**Comment by Voskrese** [comment]
src lib fastcgi
[libfcgi.zip](https://github.com/microsoft/vcpkg/files/3525516/libfcgi.zip)

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
