### ISSUE TITLE
[yaml-cpp] Wrong include path

### ISSUE THREAD

**Issue by degva** [microsoft/vcpkg#7765]
****
(I'm kinda new to cmake and vcpkg, but looking around found this issue)

OS: Archlinux w/ Linux 5.2.8

**Is your feature request related to a problem? Please describe.**
The path YAML_CPP_INCLUDE_DIR was pointing to a non existing path: `vcpkg/installed/x64-linux/share/yaml-cpp/../../../include` when `vcpkg/installed/x64-linux/share/yaml-cpp/../../include`was the needed result. Configuration worked, but compiling did not.

**Proposed solution**
I've found that the portfile had a "replace" string that was not happening. Basically the -config.cmake had a `../../../include` instead of `../include`.

So, I've made this change 856c2eff19597d149742c35e7b0a2e209e037c9b and now it works as expected, yet I'm not sure if this breaks in other OSs.

**Comment by JackBoosY** [comment]
@degva 
```
string(REPLACE "set(YAML_CPP_INCLUDE_DIR \"\${YAML_CPP_CMAKE_DIR}/../include\")"
               "set(YAML_CPP_INCLUDE_DIR \"\${YAML_CPP_CMAKE_DIR}/../../include\")" YAML_CONFIG "${YAML_CONFIG}")
```
means replace `${YAML_CPP_CMAKE_DIR}/../include` to `${YAML_CPP_CMAKE_DIR}/../../include\`, but your change seems to have no effect.

Can you comment the `string(REPLACE)` and build and then the `yaml-cpp-config.cmake`?

Thanks.

**Comment by degva** [comment]
My bad, I meant this:

```
string(REPLACE "set(YAML_CPP_INCLUDE_DIR \"\${YAML_CPP_CMAKE_DIR}/../../../include\")"
               "set(YAML_CPP_INCLUDE_DIR \"\${YAML_CPP_CMAKE_DIR}/../../include\")" YAML_CONFIG "${YAML_CONFIG}")
```

Commenting out the replace, I get:
`set(YAML_CPP_INCLUDE_DIR "${YAML_CPP_CMAKE_DIR}/../../../include")`

**Comment by JackBoosY** [comment]
@degva The path `${YAML_CPP_CMAKE_DIR}` is the path to `yaml-cpp-config.cmake`, so it should be `vcpkg/installed/triplet/share/yaml-cpp`.
And `${YAML_CPP_CMAKE_DIR}/../../include` should be `vcpkg/installed/triplet/share/yaml-cpp/../../include` == `vcpkg/installed/triplet/include`, I think it's correct.

**Comment by degva** [comment]
Right, this `vcpkg/installed/triplet/share/yaml-cpp/../../include` == `vcpkg/installed/triplet/include` is correct, but the search string in the string(REPLACE) is not. At least in my case 🤔 

In order to the replace string to be executed, the search string: `set(YAML_CPP_INCLUDE_DIR \"\${YAML_CPP_CMAKE_DIR}/../include\")` should be replaced with this: `set(YAML_CPP_INCLUDE_DIR \"\${YAML_CPP_CMAKE_DIR}/../../../include\")`

See my commit here: https://github.com/degva/vcpkg/commit/856c2eff19597d149742c35e7b0a2e209e037c9b

Maybe I'm missing something?

**Comment by JackBoosY** [comment]
@degva So, if you replace the path string with `${YAML_CPP_CMAKE_DIR}/../../../include`, it will fail to find these headers beacuse `${YAML_CPP_CMAKE_DIR}/../../../include` == `vcpkg/installed/include`.

**Comment by JackBoosY** [comment]
@degva So, if you replace the path string with `${YAML_CPP_CMAKE_DIR}/../../../include`, it will fail to find these header files just because the path `${YAML_CPP_CMAKE_DIR}/../../../include` == path `vcpkg/installed/include`(missing `triplet`).

**Comment by degva** [comment]
Sorry, I think we are not understanding. Basically, just as you said, the "triplet" is missing, therefore the search string is wrong and it should be changed. Let me explain myself again.

Installing yaml-cpp with the current version of the portfile, gives you the following in the `yaml-cpp-config.cmake` file:

```set(YAML_CPP_INCLUDE_DIR "${YAML_CPP_CMAKE_DIR}/../../../include")
```

But that is wrong because, like you said, will miss the `triplet` part.

Now, going to the portfile, there's a search(REPLACE) on line 31 that changes that line in the `yaml-cpp-config.cmake` that goes like this:

```string(REPLACE "set(YAML_CPP_INCLUDE_DIR \"\${YAML_CPP_CMAKE_DIR}/../include\")"
"set(YAML_CPP_INCLUDE_DIR \"\${YAML_CPP_CMAKE_DIR}/../../include\")" YAML_CONFIG "${YAML_CONFIG}")
```

Here the search string on that string(REPLACE) is wrong, there's no other line setting the YAML_CPP_INCLUDE_DIR that is like this: `${YAML_CPP_CMAKE_DIR}/../include`. That should be changed to this  `${YAML_CPP_CMAKE_DIR}/../../../include` and keep the rest of the string(REPLACE) intact. 

Doing that change, gives you the following on the `yaml-cpp-config.cmake` file (which is what we want):

```set(YAML_CPP_INCLUDE_DIR "${YAML_CPP_CMAKE_DIR}/../../include")
```

**Comment by JackBoosY** [comment]
@degva I think our unmodified yaml-cpp-config.cmake file is different. My content is:
```
# - Config file for the yaml-cpp package
# It defines the following variables
#  YAML_CPP_INCLUDE_DIR - include directory
#  YAML_CPP_LIBRARIES    - libraries to link against

# Compute paths
get_filename_component(YAML_CPP_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
set(YAML_CPP_INCLUDE_DIR "${YAML_CPP_CMAKE_DIR}/../include")

# Our library dependencies (contains definitions for IMPORTED targets)
include("${YAML_CPP_CMAKE_DIR}/yaml-cpp-targets.cmake")

# These are IMPORTED targets created by yaml-cpp-targets.cmake
set(YAML_CPP_LIBRARIES "yaml-cpp")
```
I found this path in yaml-cpp-config.cmake.in to be **@CONFIG_INCLUDE_DIRS@**, and this variable has two settings in _source\CMakeLists.txt_:
```set(CONFIG_INCLUDE_DIRS "${YAML_CPP_SOURCE_DIR}/include")```
And
```set(CONFIG_INCLUDE_DIRS "\${YAML_CPP_CMAKE_DIR}/${REL_INCLUDE_DIR}")```

The first path is `${vcpkg_path}/buildtrees/yaml-cpp/src/-cpp-0.6.2-25b050bfa8/include`,
and the second is `/../include`.

I think the correct solution is make a patch to fix it.

**Comment by JackBoosY** [comment]
Hi @degva , thanks for reporting this issue.
I've fixed this issue. Please update vcpkg and rebuild yaml-cpp.

Thanks.
