### ISSUE TITLE
Error installing openblas

### ISSUE THREAD

**Issue by ChrisNabold** [microsoft/vcpkg#7776]
PS C:\vcpkg> .\vcpkg install openblas
The following packages will be built and installed:
    openblas[core]:x86-windows
Starting package 1/1: openblas:x86-windows
Building package openblas[core]:x86-windows...
CMake Error at ports/openblas/portfile.cmake:4 (message):
  openblas can only be built for x64 currently
Call Stack (most recent call first):
  scripts/ports.cmake:75 (include)

Error: Building package openblas:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openblas:x86-windows
  Vcpkg version: 2019.07.19-nohash

**Comment by ehsan-mohammadi** [comment]
@Chris-Bond Refer to the error message, `openblas` currently available and build for `x64`.
