### ISSUE TITLE
How supported / not supported is MinGW on Windows?

### ISSUE THREAD

**Issue by vadi2** [microsoft/vcpkg#7794]
The amount of packages supported by vcpkg is pretty great and almost close to what we require in our project. However, we build with MinGW for Windows and now MSVC, and switching just for the package manager is not an option.

I see there's been an answer to this [over here](https://github.com/microsoft/vcpkg/issues/4418#issuecomment-428168157), but it is a little unclear. If we were to use vcpkg with MinGW on Windows, are we fighting an uphill battle?

**Comment by cbezault** [comment]
The comment that you linked to states that building `vcpkg` the tool with MinGW is not supported. However, you can always use the MinGW compiler/toolchain to build libraries with vcpkg. Currently we don't test anything but _hopefully_ most of the ports that work on Linux will work with MinGW.

**Comment by vadi2** [comment]
Thanks. I don't understand what https://github.com/microsoft/vcpkg/pull/5117/files is about - is that building `vcpkg` itself with MinGW?

**Comment by Voskrese** [comment]
Why not?

MinGW has CMAKE under WINDOWS and builds in exactly the same way

TOOLCHAIN ​​+ CMAKE + GCC = lib, bin, include

the only thing, MSYS has its own CMAKE, a little fixed

**Comment by vadi2** [comment]
Yes I agree, we don't want to make our contributors install 2 compilers when we only use one - and Visual Studio is measured in gigs.

vcpkg has all the packages we need, unlike other package managers, but the hard msvc requirement makes it a barrier to adoption where msvc isn't used as the compiler :)

Thanks for the answer!

**Comment by Voskrese** [comment]
Yes and still, there is one big nuance, where in the ports the folder is indicated \ the folder is added ../mingw32/bin or ../mingw64/bin

then NINJA will consider the default compiler to be GCC, not MSVC cl.exe

> 
> да и еще, есть один большой нюанс, где в портах указана папка\добавлена папка ../mingw32/bin или ../mingw64/bin
> 
> то NINJA будет считать компилятором по умолчанию GCC, а не MSVC cl.exe

**Comment by vadi2** [comment]
Are you saying it's a vcpkg or an MSYS problem?

We use MinGW that comes with the Qt's Windows installer.

**Comment by Voskrese** [comment]
it's not that the problem, for some reason NINJA considers it to be the compiler, what it finds first

therefore, in the TOOLCHAIN ​​file, use other paths, as you already mentioned, let's say that comes with QT

> это не то чтобы проблема, NINJA почему то считает компилятором, то что находит первым
> 
> поэтому в файле TOOLCHAIN использовать другие пути, как вы уже упомянули, допустим который идет с QT

**Comment by vadi2** [comment]
And that's the file that you tried to modify in vcpkg, right? So vcpkg would need to be fixed here to accept other compilers?

**Comment by Voskrese** [comment]
https://github.com/microsoft/vcpkg/pull/5117/files

VCPKG_CMAKE_SYSTEM_NAME STREQUAL "MinGW"
```
    elseif(VCPKG_CMAKE_SYSTEM_NAME STREQUAL "MinGW")
        list(APPEND _csc_OPTIONS "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=${VCPKG_ROOT_DIR}/scripts/toolchains/mingw.cmake")
    endif()
```
-->>
triplets/mingw64.cmake

`set(VCPKG_CMAKE_SYSTEM_NAME MinGW)`

**Comment by Voskrese** [comment]
example MIPSel

scripts\toolchains
[mips32r2.cmake.txt](https://github.com/microsoft/vcpkg/files/3529416/mips32r2.cmake.txt)

triplets
[mipsel.cmake.txt](https://github.com/microsoft/vcpkg/files/3529418/mipsel.cmake.txt)

**Comment by vadi2** [comment]
So you do that for every library you want to compile with vcpkg?

**Comment by Voskrese** [comment]
in general, everything is in your hands, nothing prevents you from adding new tools
VCPKG as a layer between them

**Comment by vadi2** [comment]
Если можете, доработайте пожалуйста, нам в [мадлете](https://github.com/Mudlet/Mudlet) очень поможет )

**Comment by alcroito** [comment]
I think if https://github.com/microsoft/vcpkg/pull/9137 gets merged, this issues's status could be changed to fixed.
