### ISSUE TITLE
How do I update packages installed from --head

### ISSUE THREAD

**Issue by Consti10** [microsoft/vcpkg#7813]
Assuming I have installed any library via vcpkg from --head ,example command:
`vcpkg install magnum[sdl2application,glfwapplication] --head --triplet x64-windows`

how do I update ? running
`.\vcpkg upgrade --no-dry-run`

installed the latest release of the library instead of latest verison of --head

**Comment by cbezault** [comment]
Once something is installed via `--head` the only real way to upgrade it is to remove and install again with `--head`.
