### ISSUE TITLE
cpprest 2.9.0-2 failure when programm starting

### ISSUE THREAD

**Issue by Pantau123** [Microsoft/vcpkg#782]
Hi i ahve a Problem when i want to start a Programm which include the cpprest in Version 2.9.0-2. I receive the failure that the ordinal number 407 from the dll "SSLEAY32.dll" isn't found. vcpkg has installed the openssl Version 1.0.2k-2.
Can anybody help me?

**Comment by ras0219-msft** [comment]
Hi Pantau123, could you go into more details about what exact steps you've taken? Something like

1. I have VS 2017 installed
2. I cloned vcpkg and ran bootstrap
3. `vcpkg install cpprestsdk`
4. I created a new project in VS2017 and copied the "Getting Started" sample from Cpprestsdk's GitHub
5. I built it (which was successful), but upon running it could not find SSLEAY32.

**Comment by JackBoosY** [comment]
Hi @Pantau123 , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
