### ISSUE TITLE
 Building package openssl-windows:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by seysamas** [microsoft/vcpkg#7825]
Hi!
I'm using instructions here https://tdlib.github.io/td/build.html?language=JavaScript
to build TDLib. for windows 10 enterprise, version 1803 x64 based, os build 17134.950 with 16 GB of RAM.
I have a problem  with this command:
`./vcpkg.exe install openssl:x64-windows zlib:x64-windows`
Erros is this:
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:58 (message):
    Command failed: nmake -f ms\ntdll.mak install

```
but the mentioned file exists.
Also, I have pulled the repo and rebuild vcpkg again.
I have run this command too:
`.\vcpkg integrate install`

thanks for your time reading this and helping me!

**Comment by Voskrese** [comment]
absolutely nothing is clear from the description
log files Erros ???

**Comment by seysamas** [comment]
```
  Command failed: nmake -f ms\ntdll.mak install
    Working Directory: blahblahblah/vcpkg/buildtrees/openssl-windows/x64-windows-rel
    Error code: The system cannot find the file specified
    See logs for more information:

Call Stack (most recent call first):
  ports/openssl-windows/portfile.cmake:119 (vcpkg_execute_required_process)
  scripts/ports.cmake:84 (include)


Error: Building package openssl-windows:x64-windows failed with: BUILD_FAILED
```

**Comment by Voskrese** [comment]
`vcpkg env --debug`

`where nmake`

?

**Comment by seysamas** [comment]
you mean
` ./vcpkg.exe env --debug --triplet x64-windows` ?

**Comment by Voskrese** [comment]
`vcpkg /?`

> vcpkg env                       Creates a clean shell environment for development or compiling.

**Comment by seysamas** [comment]
`PS E:\ServerSide-Projects\microservices\telegram_notif\td\vcpkg> .\vcpkg.exe env --debug --triplet x64-windows
[DEBUG] Using vcpkg-root: E:\ServerSide-Projects\microservices\telegram_notif\td\vcpkg
[DEBUG] Found path: C:\Program Files\CMake\bin\cmake.exe
[DEBUG] _wpopen(""C:\Program Files\CMake\bin\cmake.exe" --version 2>&1")
[DEBUG] _pclose() returned 0 after    52928 us
[DEBUG] _wpopen(""C:\Program Files\CMake\bin\cmake.exe" "-DCMAKE_TRIPLET_FILE=E:/ServerSide-Projects/microservices/telegram_notif/td/vcpkg/triplets/x64-windows.cmake" -P "E:/ServerSide-Projects/microservices/telegram_notif/td/vcpkg/scripts/get_triplet_environment.cmake" 2>&1")
[DEBUG] _pclose() returned 0 after    34157 us
[DEBUG] _wpopen(""C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease -legacy -products * -format xml 2>&1")
[DEBUG] _pclose() returned 0 after    33040 us
[DEBUG] CreateProcessW(cmd.exe /c ""C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" -vcvars_ver=14.1 amd64   2>&1 <NUL && cmd")
[ERROR:vcvarsall.bat] Invalid argument found : -vcvars_ver=14.1
[ERROR:~nx0] Error in script usage. The correct usage is:
Syntax:
    vcvarsall.bat [arch]
  or
    vcvarsall.bat [arch] [version]
  or
    vcvarsall.bat [arch] [platform_type] [version]
where :
    [arch]: x86 | amd64 | x86_amd64 | x86_arm | x86_arm64 | amd64_x86 | amd64_arm | amd64_arm64
    [platform_type]: {empty} | store | uwp
    [version] : full Windows 10 SDK number (e.g. 10.0.10240.0) or "8.1" to use the Windows 8.1 SDK.

The store parameter sets environment variables to support Universal Windows Platform application
development and is an alias for 'uwp'.

For example:
    vcvarsall.bat x86_amd64
    vcvarsall.bat x86_amd64 10.0.10240.0
    vcvarsall.bat x86_arm uwp 10.0.10240.0
    vcvarsall.bat x86_arm onecore 10.0.10240.0
    vcvarsall.bat x64 8.1
    vcvarsall.bat x64 store 8.1

Please make sure either Visual Studio or C++ Build SKU is installed.
Microsoft Windows [Version 10.0.17134.950]
(c) 2018 Microsoft Corporation. All rights reserved.

E:\ServerSide-Projects\microservices\telegram_notif\td\vcpkg>vcpkg install openssl:x64-windows zlib:x64-windows
The following packages will be built and installed:
    openssl[core]:x64-windows
  * openssl-windows[core]:x64-windows
    zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: openssl-windows:x64-windows
Building package openssl-windows[core]:x64-windows...
-- Using cached E:/ServerSide-Projects/microservices/telegram_notif/td/vcpkg/downloads/openssl-1.0.2s.tar.gz
-- Using source at E:/ServerSide-Projects/microservices/telegram_notif/td/vcpkg/buildtrees/openssl-windows/src/openssl-1-c41872ef97
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x64-windows-rel
-- Configure x64-windows-rel done
-- Build x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:58 (message):
    Command failed: nmake -f ms\ntdll.mak install
    Working Directory: E:/ServerSide-Projects/microservices/telegram_notif/td/vcpkg/buildtrees/openssl-windows/x64-windows-rel
    Error code: The system cannot find the file specified
    See logs for more information:

Call Stack (most recent call first):
  ports/openssl-windows/portfile.cmake:119 (vcpkg_execute_required_process)
  scripts/ports.cmake:84 (include)


Error: Building package openssl-windows:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-windows:x64-windows
  Vcpkg version: 2019.08.16-nohash

Additionally, attach any relevant sections from the log files above.
`

**Comment by Voskrese** [comment]
> [ERROR:vcvarsall.bat] Invalid argument found : -vcvars_ver=14.1
> [ERROR:~nx0] Error in script usage. The correct usage is:

install \add component *VC140**

**Comment by PhoebeHui** [comment]
@seysamas, it seems visual studio related component not installed correctly.

Open visual studio 2017 installer:
1, In Workloads tab, check 'Desktop development with C++', check 'Universal windows Platform development' for building UWP.
2, In Individual components, check additional components:
    ARM:
       Visual C++ compilers and libraries for ARM
       Visual C++ compilers and libraries for ARM64
    ATL/MFC:
      Visual C++ ATL for x86 and x64
      Visual C++ MFC for x86 and x64
    Windows 10 SDK(10.0.17763.0)

**Comment by PhoebeHui** [comment]
@seysamas, please check if above components correctly installed, and reopen this if it still be an problem for you.

**Comment by abobaki** [comment]
Hello!

i have all the components above installed, and still have the same issue.

```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: C:/dev/vcpkg/downloads/tools/jom/jom-1.1.3/jom.exe -j 1 -f makefile install_sw install_ssldirs
    Working Directory: C:/dev/vcpkg/buildtrees/openssl/x64-windows-rel
    Error code: 2
    See logs for more information:
      C:\dev\vcpkg\buildtrees\openssl\build-x64-windows-rel-1-out.log
      C:\dev\vcpkg\buildtrees\openssl\build-x64-windows-rel-1-err.log

Call Stack (most recent call first):
  ports/openssl/windows/portfile.cmake:97 (vcpkg_execute_required_process)
  ports/openssl/portfile.cmake:36 (include)
  scripts/ports.cmake:146 (include)


error: building openssl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openssl]+Build+error
Include '[openssl] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e
    vcpkg-scripts version: e6c8c2bc0 2022-07-07 (12 hours ago)

You can also use the prefilled template from C:\dev\vcpkg\installed\vcpkg\issue_body.md.
```
