### ISSUE TITLE
Dependency on VCRUNTIME140.dll with GTK+ built via vcpkg

### ISSUE THREAD

**Issue by kakyoism** [microsoft/vcpkg#7829]
My app ends up depending on `VCRUNTIME140.dll` even when the vcproj specifies `/MT` instead of `/MD`. It's unacceptable for us to ask users to install the dll by downloading the VC redistributable. But I can't figure out a way to statically link these since the dependencies are in one of the vcpkg-built libs when running `vcpkg install gtk:x64-windows`. Worse, I don't know which lib introduces this dependency.

Any idea how to fix it?

**Comment by Neumann-A** [comment]
```
Source: gtk
Version: 3.22.19-2
Description: Portable library for creating graphical user interfaces.
Build-Depends: glib, atk, gdk-pixbuf, pango, cairo, libepoxy, gettext

# Glib relies on DllMain on Windows
if(NOT VCPKG_CMAKE_SYSTEM_NAME)
    if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
        message("Glib relies on DllMain and therefore cannot be built statically")
        set(VCPKG_LIBRARY_LINKAGE "dynamic")
    endif()
    if(VCPKG_CRT_LINKAGE STREQUAL "static")
        message(FATAL_ERROR "Glib only supports dynamic library and crt linkage")
    endif()
endif()
```

**Comment by kakyoism** [comment]
@Neumann-A Thanks. Oh, well...

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed, so I am closing this issue for now.
