### ISSUE TITLE
[libssh2] install fails, when OpenSSL is installed

### ISSUE THREAD

**Issue by Drako** [Microsoft/vcpkg#783]
When I `.\vcpkg install libssh2--triplet x64-windows`, this installs openssl as a dependency, which is fine.

The install then fails though at the linking stage, as it tries to link against the OpenSSL version
I have installed at C:\OpenSSL (which is x86).

**Comment by ras0219-msft** [comment]
Hey Drako, we've made some significant improvements against environment contamination in the recent version 0.0.76.

Could you `git pull` and re-run `bootstrap.ps1`, then try building libssh2 again?

**Comment by Drako** [comment]
I just tested it and libssh2 still find `C:\OpenSSL` and tries to link against that. :(

**Comment by codicodi** [comment]
This is probably related to #710: In debug builds external libs may be preferred by CMake if they have the suffix. Note that they are picked up just fine because [FindOpenSSL.cmake](https://github.com/Kitware/CMake/blob/master/Modules/FindOpenSSL.cmake#L70) passes `C:\OpenSSL` as a hardcoded hint.

**Comment by ras0219-msft** [comment]
Thanks @codicodi!

I think I've fixed this with 8dc2699e5dc7. I saw no realistic easier way besides hardcoding a blacklist for the hardcoded directories in `FindOpenSSL.cmake` (so far still hoping we do not need to override `find_package()`).
