### ISSUE TITLE
add library 

### ISSUE THREAD

**Issue by vija9751** [microsoft/vcpkg#7831]
please include  library 

glib-2.0/ glib.h
gnutls/gnutls.h
network/network.h
LIBGVM_MODULES /libgvm_base
LIBGVM_UTIL/  libgvm_util
gvm-libs

**Comment by PhoebeHui** [comment]
@vija9751, could you provide source repository URL as well? BTW, you can use 'Request a new port' template to ask to support a new library in future.

**Comment by vija9751** [comment]
> @vija9751, could you provide source repository URL as well? BTW, you can use 'Request a new port' template to ask to support a new library in future.

when i use cmake with vcpkg to run a  source code from linux to windows these library are missing 

glib-2.0/ glib.h
gnutls/gnutls.h
network/network.h
LIBGVM_MODULES /libgvm_base
LIBGVM_UTIL/ libgvm_util
gvm-libs

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by giorgiozoppi** [comment]
I am interested to port this https://www.gnupg.org/ftp/gcrypt/gnutls/v3.6/gnutls-3.6.15.tar.xz

**Comment by giorgiozoppi** [comment]
i created the files.

**Comment by NancyLi1013** [comment]
@giorgiozoppi 

You can create a pull request for `gnutls` if you are willing to do this work.
