### ISSUE TITLE
[halide] Port installs pre-built binaries

### ISSUE THREAD

**Issue by vicroms** [microsoft/vcpkg#7838]
**Describe the bug**
`halide` port downloads and installs pre-built binaries instead of building from source.

**Environment**
- OS: All

**To Reproduce**
1. `./vcpkg install halide`

**Expected behavior**
The `halide` library should be built from source by **vcpkg**.

**Failure logs** 
N/A

**Additional context**
Installation will always succeed because it just downloads and unzips the binaries and headers, note that this are Windows binaries, so they won't work on non-Windows platforms.

**Comment by JackBoosY** [comment]
Close this issue via #8102.
