### ISSUE TITLE
[ogdf] build failure

### ISSUE THREAD

**Issue by halsten** [microsoft/vcpkg#7841]
Hi,

I have tried to install OGDF recently and it failed to do so. I have pasted below some information and the output form my trial. I have also did a `git pull' and a `vcpkg upgrade` and the results were the same. Obviously, I do have an internet connection and I verified it was working fine. Probably the URL being used is dead.

**Host Environment**
- OS: Win10
- Compiler: VS2017

**To Reproduce**
`./vcpkg install ogdf`

**Failure logs** 
The following packages will be built and installed:
    ogdf[core]:x86-windows
Starting package 1/1: ogdf:x86-windows
Building package ogdf[core]:x86-windows...
-- Downloading http://www.ogdf.net/lib/exe/fetch.php/tech%3aogdf-snapshot-2018-03-28.zip...
-- Downloading http://www.ogdf.net/lib/exe/fetch.php/tech%3aogdf-snapshot-2018-03-28.zip... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:172 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/ogdf/portfile.cmake:3 (vcpkg_download_distfile)
  scripts/ports.cmake:85 (include)

**Additional context**
Error: Building package ogdf:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ogdf:x86-windows
  Vcpkg version: 2019.08.16-nohash

--halsten

**Comment by wangli28** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
