### ISSUE TITLE
[New Port Request] swig

### ISSUE THREAD

**Issue by dan-shaw** [microsoft/vcpkg#7843]
Library name: swig

Library description: SWIG is a software development tool that connects programs written in C and C++ with a variety of high-level programming languages.

Source repository URL:  https://github.com/swig/swig

Needed for #7823

**Comment by Voskrese** [comment]
DEPS:
JAVA_INCLUDE JAVA_BIN
PERL5_INCLUDE PERL5_LIB
PYTHON_INCLUDE PYTHON_LIB
TCL_INCLUDE TCL_LIB
R_INCLUDE R_LIB
RUBY_INCLUDE RUBY_LIB

[New Port Request] java, perl5, tcl, r_core, ruby ? ))

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by Napolitain** [comment]
Hi, can we reopen this issue ?

**Comment by hcyang99** [comment]
> Hi, can we reopen this issue ?

Swig is using GNU Autotools, someone needs to port it to CMake first ...
