### ISSUE TITLE
Partial file download failure in find_acquire_program

### ISSUE THREAD

**Issue by Pantau123** [Microsoft/vcpkg#785]
Hi, if i want to install openssl:x86-windows-static i receive following message:

CMake Error at D:/Tools/vcpkg/scripts/cmake/vcpkg_find_acquire_program.cmake:103 (file):
  file DOWNLOAD HASH mismatch

    for file: [D:/Tools/vcpkg/downloads/strawberry-perl-5.24.1.1-32bit-portable.zip]
      expected hash: [a6e685ea24376f50db5f06c5b46075f1d3be25168fa1f27fa9b02e2ac017826cee62a2b43562f9b6c989337a231ba91441
6c110075457764de2d11f99d5e0f26]
        actual hash: [9c50ebbe6e61923bae4a823a8adcac88ea0a11fd8381c0c58f1cd5186375a8808c8bc41f7f5fee7343dc1710a8bd84df04
8bcef79e52649765c348686d8c40ae]
             status: [18;"Transferred a partial file"]

Call Stack (most recent call first):
  D:/Tools/vcpkg/ports/openssl/portfile.cmake:9 (vcpkg_find_acquire_program)
  D:/Tools/vcpkg/scripts/ports.cmake:73 (include)

**Comment by ras0219-msft** [comment]
It looks like the download failed partially through. You'll need to delete that file and re-run the install.

If `vcpkg` is unable to download the file correctly for you after several tries, first **let us know** so we can fix it! Then, you can download the file yourself from [1] and place it in the downloads folder.

[1] http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portable.zip

**Comment by zengqu** [comment]
File path: [ D:/WorkingCode/github/vcpkg/downloads/zlib1211.tar.gz ]
      Expected hash: [ 73fd3fff4adeccd4894084c15ddac89890cd10ef105dd5e1835e1e9bbb6a49ff229713bd197d203edfa17c2727700fce65a2a235f07568212d820dca88b528ae ]
        Actual hash: [ 21d41682753190217393559eb210c8b1a76212c17fcf4cf6070eada04c135b1f0163988cbac98d786438a777c7186ba782bf099d9d51f239d158bf7435da3f45 ]

I had got an same error when i am download zlib, how can i fix it?

**Comment by ras0219-msft** [comment]
Hi @zengqu, could you try deleting the file and re-running the install process? If this continues to give you errors, try downloading it directly from [1] and placing it in the downloads directory.

[1] https://downloads.sourceforge.net/project/libpng/zlib/1.2.11/zlib-1.2.11.tar.gz

**Comment by JackBoosY** [comment]
Hi @Pantau123 , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
