### ISSUE TITLE
[opencv4:x64-windows] build failure

### ISSUE THREAD

**Issue by melhashash** [microsoft/vcpkg#7856]
**Host Environment**
- OS: Windows 10
- Compiler: C/C++ Optimizing Compiler Version 19.00.24215.1 for x64

**To Reproduce**
`vcpkg.exe install opencv4[contrib,nonfree]:x64-windows`

**Failure logs** 
Package: opencv4:x64-windows
Vcpkg version: 2019.08.16-nohash

**Additional context**
ninja: build stopped: subcommand failed.
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/3534027/config-x64-windows-out.log)
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3534028/install-x64-windows-dbg-out.log)

**Comment by cenit** [comment]
I never tried using VS2015 to build opencv 4.1.x and I don’t have any machine ready for that

@vicroms  @Rastaban what about adding more configurations to the CI? Same triplets as of now, but different gcc versions on Linux, different clang versions on MacOS, and different msvc versions on Windows. We would highlight problems like this

@Napester: I assume you can’t update to a newer version, am i right? If not, please update to VS2017 or better to VS2019 and you should not receive any build error

**Comment by JackBoosY** [comment]
@Napester Thanks for reporting this issue.
Please install Windows SDK version above 10.0.17134.0 and then rebuild opencv4.

Thanks.
