### ISSUE TITLE
Why is VCPKG_CONCURRENCY set to logical cores +1?

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#7858]
From the code:
`return System::get_num_logical_cores() + 1;`

@cbezault: 
You probably implemented that. Why did you add 1? 
I probably shouldn't use that then for makes -j option or should I?

**Comment by cbezault** [comment]
From kitware's blog.

For minimum build times, you want to use a value of N that is one more than the number of cores on the machine.  So, if you have a quad core Linux machine, you would run make –j5.

**Comment by invy** [comment]
If you'll look at the implementation of the function, it returns 0 if fails. So I guess this is quick way to ensure function always returns usable value.
The other question is, why the function is defined as int, and not uint... we can't get a negative number of cores, can't we? :)

**Comment by Neumann-A** [comment]
>For minimum build times, you want to use a value of N that is one more than the number of cores on the machine. So, if you have a quad core Linux machine, you would run make –j5.

@cbezault: Thats probably a very arbitary choice... see https://unix.stackexchange.com/questions/208568/how-to-determine-the-maximum-number-to-pass-to-make-j-option 
The perfect value strongly depends on what is build on how the machine building is setup. VCPKG_CONCURRENCY should simply return the number of available logical cores. Everything else is just an arbitary modification of that value without a good reasoning behind it or needs a lot more datapoints (like estimated ram usage of the port while building etc...).

**Comment by cbezault** [comment]
re-open if you have a convincing reason why this is a problem. We're not in the business of dynamically determining the optimal build settings (yet).
