### ISSUE TITLE
[poco x86-windows] build failure

### ISSUE THREAD

**Issue by tan-wei** [microsoft/vcpkg#7866]
**Host Environment**
- OS: Windws_zhCN
- Compiler: VS 2017

**To Reproduce**
`./vcpkg install poco`

**Failure logs** 
```
The following packages will be built and installed:
    poco[core]:x86-windows
Starting package 1/1: poco:x86-windows
Building package poco[core]:x86-windows...
-- Using cached C:/vcpkg/downloads/pocoproject-poco-8a127d6f16795d914cadc342d3f4f3b9b7999e3b.tar.gz
-- Using source at C:/vcpkg/buildtrees/poco/src/b9b7999e3b-76e03302ae
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
    Working Directory: C:/vcpkg/buildtrees/poco/x86-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\poco\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/poco/portfile.cmake:83 (vcpkg_install_cmake)
  scripts/ports.cmake:85 (include)


Error: Building package poco:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: poco:x86-windows
  Vcpkg version: 2019.08.16-nohash

Additionally, attach any relevant sections from the log files above.
```
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3536980/install-x86-windows-dbg-out.log)

**Additional context**
I've changed system locale under the Language for non-Unicode programs with English, without the change, it sometimes makes the build process fail. However, it still fail after I change it.
Also I try to clean the `buildtree` directiory, it doesn't work.

**Comment by tan-wei** [comment]
Maybe conflict with `libharu`? I find the error located in `hdpf.h` related to `libharu`.

**Comment by NancyLi1013** [comment]
Hi @tan-wei, thanks for posting this issue. I try to install this port on my local and it can be built successfully. I noticed that there are some non-English messages in the above log you attached. My test Environment:
**OS**:  Windows 64
**Compiler**: VS 2017 (15.9.14)
Could you help provide more info about the reproduce steps? Or what's the special in your environment? Maybe it is related to your non-Unicode changes.

**Comment by JackBoosY** [comment]
poco's feature pdf conflict with libharu, so there are some redefinition errors.

**Comment by tan-wei** [comment]
> 
> 
> Hi @tan-wei, thanks for posting this issue. I try to install this port on my local and it can be built successfully. I noticed that there are some non-English messages in the above log you attached. My test Environment:
> **OS**: Windows 64
> **Compiler**: VS 2017 (15.9.14)
> Could you help provide more info about the reproduce steps? Or what's the special in your environment? Maybe it is related to your non-Unicode changes.

Yes, I've tried as I described. I think the problem is confilict with `libharu` which is installed with `vtk`. I clean build process without any other libraries installed will be sucessful I think.

**Comment by tan-wei** [comment]
> 
> 
> poco's feature pdf conflict with libharu, so there are some redefinition errors.

I think so. So is there any solution? Or we can not avoid this problem? Thanks!

**Comment by JackBoosY** [comment]
@tan-wei I just created a PR to fix this problem. See #7892.

**Comment by tan-wei** [comment]
> 
> 
> @tan-wei I just created a PR to fix this issue. See #7892.

Thanks very much. The issue will be closed after the PR is merged.

**Comment by JackBoosY** [comment]
Hi @tan-wei, thanks for reporting this issue.
I've fixed this issue. Please update vcpkg and rebuild poco.

Thanks.

**Comment by tan-wei** [comment]
Thanks, I've tried and I can confirm it works. Thanks very much!
