### ISSUE TITLE
GTest package has different targets than the upstream code.

### ISSUE THREAD

**Issue by coryan** [microsoft/vcpkg#7874]
**Describe the bug**

When compiled from source googletest creates 4 targets `GTest::{gtest,gmock,gtest_main,gmock_main`, when compiled via vcpkg the target names for `gmock` are different, namely `GMock::gmock` and `GMock::gmock_main`.

This sort of inconsistency is a problem if one wants to support packages installed manually as well as packages installed via `vcpkg`.

**Environment**

Tested on Linux (Ubuntu 18.04), but I think it applies to all platforms.

**To Reproduce**

1. ./vcpkg install gtest

Then try to use the package as `GTest::gmock`.

**Expected behavior**

I expect vcpkg to create the same target names as the packages do. But maybe this expectation is wrong?

**Failure logs** 

N/A

**Additional context**

I think that is all?

**Comment by JackBoosY** [comment]
@coryan In the pre-modification version of #7316, gtest did not export the gmock namespace, so I fixed it.
I think we should use gtest::gmock instead of gmock::gmock.

**Comment by JackBoosY** [comment]
Hi @coryan, thanks for reporting this issue.
I've fixed this issue. Please update vcpkg and rebuild gtest.

Thanks.
