### ISSUE TITLE
[boost:win64-windows] build failure

### ISSUE THREAD

**Issue by zlf1734** [microsoft/vcpkg#7876]
**Host Environment**
- OS: [windows10/64bit.]
- Compiler: vs2019

**To Reproduce**
`./vcpkg install boost:x64-windows`

**Failure logs** 
Downloading https://github.com/boostorg/math/archive/boost-1.70.0.tar.gz... Failed. Status: 18;"Transferred a partial file"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:172 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:108 (vcpkg_download_distfile)
  ports/boost-math/portfile.cmake:5 (vcpkg_from_github)
  scripts/ports.cmake:85 (include)

Error: Building package boost-math:x64-windows failed with: BUILD_FAILED

**Additional context**

**Comment by tan-wei** [comment]
Just download fail, please retry or using a proxy. Also you can download the file by yourself with a download tool, then put it into directory `downloads`.

**Comment by zlf1734** [comment]
I've tried to download the package, but it's incomplete and can't be decompressed correctly. how can I get the right link? thanks

**Comment by tan-wei** [comment]
> 
> 
> I've tried to download the package, but it's incomplete and can't be decompressed correctly. how can I get the right link? thanks

Use a proxy may help.

**Comment by JackBoosY** [comment]
@zlf1734 It seems that your network cannot connect to the boost site.
And I guess you can't manually download the boost in this [link](https://github.com/boostorg/math/archive/boost-1.70.0.tar.gz).

So, please use other links to download **boost-1.70.0** and put it in _vcpkg / downloads_, then reinstall boost.

Thanks.

**Comment by PhoebeHui** [comment]
@zlf1734, you can reference https://github.com/microsoft/vcpkg/issues/5727#issuecomment-483554157 if you could download boost manually, btw, boost currently upgrade to 1.71.0, you can get the latest source and try again.
