### ISSUE TITLE
[gtk:arm64-windows] Some dependencies of gtk cannot be built

### ISSUE THREAD

**Issue by AlvinLIQ** [microsoft/vcpkg#7881]
**Host Environment**
- OS: [Windows]
- Compiler: cmake

`./vcpkg install libffi:arm64-windows`
CMake Error at ports/libffi/portfile.cmake:4 (message):
  Architecture not supported
Call Stack (most recent call first):
  scripts/ports.cmake:85 (include)

`./vcpkg install libepoxy:arm64-windows`
WARNING: Unknown options: "enable-egl, enable-glx"
Project name: libepoxy
Project version: 1.5.3
Appending CFLAGS from environment: ' /DWIN32 /D_WINDOWS /W3 /utf-8  /MD /O2 /Oi /Gy /DNDEBUG /Z7'
Appending LDFLAGS from environment: ' /DEBUG  /INCREMENTAL:NO /OPT:REF /OPT:ICF'
Appending CPPFLAGS from environment: ' '

meson.build:1:0: ERROR: Could not invoke sanity test executable: [WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

`./vcpkg install gtk:arm64-windows`

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:58 (vcpkg_execute_required_process)
  ports/libepoxy/portfile.cmake:12 (vcpkg_configure_meson)
  scripts/ports.cmake:85 (include)

**Comment by JackBoosY** [comment]
Related: [#4402](https://github.com/mesonbuild/meson/issues/4402).

**Comment by JackBoosY** [comment]
Confirmed, but I don't know how to fix this issue now.

**Comment by LilyWangLL** [comment]
`graphene` is dependency of `gtk`, it doesn't support architecture `arm`, If there are process or new change about support of `graphene`, please reopen this issue.
