### ISSUE TITLE
vcpkg install error

### ISSUE THREAD

**Issue by IRelaxxx** [microsoft/vcpkg#7890]
**Describe the bug**
When trying to install opencv `vcpkg install opencv[core]:x64-windows` works, but `vcpkg install opencv[core,contrib]:x64-windows` throws 

> Error: Contains invalid characters. Only alphanumeric lowercase ASCII characters and dashes are allowed: opencv[core

**Environment**
- OS:Windows 8.1 64 bit
- Compiler: n.a.

**To Reproduce**
1. ./vcpkg install opencv[core,contrib]:x64-windows
2. See error

**Expected behavior**
Opencv should be installed with the core and contrib modules

**Additional context**
Reinstalling vcpkg did not solve the issue.

**Comment by IRelaxxx** [comment]
It seems this is an issue with Powershell, i just used an msys terminal and it worked.

**Comment by PhoebeHui** [comment]
@IRelaxxx, I can't repro this issue, from the error, it looks ',' in opencv[core,contrib]:x64-windows parsed failed, it considered ',' as invalid characters in your Powershell.

For me, the Powershell version:
$psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.14393.3053
....

**Comment by degski** [comment]
@PhoebeHui I get a similar message, but just when doing a 'git pull' on the `vcpkg` repo. I'm not using Powershell, but the ordinary [elevated] command prompt.

    remote: Enumerating objects: 131, done.
    remote: Counting objects: 100% (131/131), done.

    Receiving objects: 100% (233/233), 99.43 KiB | 1.12 MiB/s, done.
    Resolving deltas: 100% (133/133), completed with 61 local objects.
    From https://github.com/Microsoft/vcpkg
       c446b0621..fc135e20e  master     -> origin/master
    Updating c446b0621..fc135e20e
    Fast-forward
     ports/abseil/CONTROL                              |    2 +-
     ports/abseil/fix-config.patch                     |   26 +
     ports/abseil/portfile.cmake                       |    6 +-
     ports/boost/CONTROL                               |   28 +-
     ports/casclib/CONTROL                             |    2 +-
     ports/casclib/ctype_for_mac.patch                 |   15 +-
     ports/casclib/portfile.cmake                      |    4 +-
     ports/cgl/CMakeLists.txt                          |  143 ++
     ports/cgl/CONTROL                                 |    5 +
     ports/cgl/Config.cmake.in                         |    5 +
     ports/cgl/fix-c1083-error.patch                   |   30 +
     ports/cgl/portfile.cmake                          |   28 +
     ports/chartdir/CONTROL                            |    4 +
     ports/chartdir/Config.cmake.in                    |   21 +
     ports/chartdir/chartdir.h                         |    6 +
     ports/chartdir/portfile.cmake                     |   96 +
     ports/chartdir/usage                              |    4 +
     ports/cpprestsdk/CONTROL                          |   11 +-
     ports/fastcdr/CONTROL                             |    2 +-
     ports/fastcdr/portfile.cmake                      |    4 +-
     ports/fluidsynth/CONTROL                          |    4 +-
     ports/fluidsynth/force-x86-gentables.patch        |   34 +
     ports/fluidsynth/portfile.cmake                   |    3 +-
     ports/fmt/portfile.cmake                          |   28 +-
     ports/gppanel/00001-fix-build.patch               |   24 +
     ports/gppanel/CMakeLists.txt                      |   32 +
     ports/gppanel/CONTROL                             |    5 +
     ports/gppanel/portfile.cmake                      |   42 +
     ports/gppanel/usage                               |    4 +
     ports/json5-parser/00001-fix-build.patch          |   27 +
     ports/json5-parser/CONTROL                        |    5 +
     ports/json5-parser/portfile.cmake                 |   27 +
     ports/json5-parser/usage                          |    4 +
     ports/libguarded/CONTROL                          |    4 +
     ports/libguarded/portfile.cmake                   |   15 +
     ports/liblsl/CONTROL                              |    2 +-
     ports/liblsl/fix-install.patch                    |   13 +
     ports/liblsl/portfile.cmake                       |   11 +-
     ports/libwebp/0006-fix-dependecies-platform.patch |   16 +
     ports/libwebp/CONTROL                             |    2 +-
     ports/libwebp/portfile.cmake                      |    1 +
     ports/log4cpp/CONTROL                             |    5 +
     ports/log4cpp/fix-install-targets.patch           |   13 +
     ports/log4cpp/portfile.cmake                      |   36 +
     ports/magic-enum/CONTROL                          |    2 +-
     ports/magic-enum/portfile.cmake                   |    4 +-
     ports/magnum/004-khrplatform-include.patch        |   13 +
     ports/magnum/portfile.cmake                       |    1 +
     ports/minifb/CONTROL                              |    4 +
     ports/minifb/fix-arm-build-error.patch            |   40 +
     ports/minifb/fix-build-error.patch                |   25 +
     ports/minifb/fix-install-error.patch              |   54 +
     ports/minifb/portfile.cmake                       |   32 +
     ports/moos-ui/CONTROL                             |    4 +-
     ports/moos-ui/portfile.cmake                      |   19 +-
     ports/nmap/CONTROL                                |    4 +-
     ports/nmap/build.sh                               |   24 -
     ports/nmap/detect-crypto-library.patch            |   75 -
     ports/nmap/fix-msvc-prj.patch                     | 1986 +++++++++++++++++++++
     ports/nmap/fix-snprintf.patch                     |   39 +
     ports/nmap/fix-ssize_t.patch                      |   16 +
     ports/nmap/portfile.cmake                         |  219 ++-
     ports/opencv3/CONTROL                             |    2 +-
     ports/opencv3/portfile.cmake                      |    2 +-
     ports/openni2/CONTROL                             |    2 +-
     ports/openni2/portfile.cmake                      |   18 +-
     ports/orc/0004-update-tzdata.patch                |   15 +
     ports/orc/CONTROL                                 |    1 +
     ports/orc/portfile.cmake                          |    1 +
     ports/pcre/CONTROL                                |    2 +-
     ports/pcre/portfile.cmake                         |    2 +-
     ports/poco/CONTROL                                |    6 +-
     ports/poco/portfile.cmake                         |   11 +-
     ports/poco/unbundled_pdf.patch                    |   30 -
     ports/poco/use-vcpkg-libharu.patch                |   18 +
     ports/wpilib/CONTROL                              |    6 +-
     ports/wpilib/portfile.cmake                       |    5 +-
     ports/yaml-cpp/0002-fix-include-path.patch        |   13 +
     ports/yaml-cpp/CONTROL                            |    2 +-
     ports/yaml-cpp/portfile.cmake                     |   29 +-
     toolsrc/VERSION.txt                               |    2 +-
     toolsrc/src/vcpkg-test/stringview.cpp             |   17 +
     toolsrc/src/vcpkg/base/stringview.cpp             |    2 +-
     toolsrc/src/vcpkg/parse.cpp                       |   94 +-
     84 files changed, 3267 insertions(+), 373 deletions(-)
     create mode 100644 ports/abseil/fix-config.patch
     create mode 100644 ports/cgl/CMakeLists.txt
     create mode 100644 ports/cgl/CONTROL
     create mode 100644 ports/cgl/Config.cmake.in
     create mode 100644 ports/cgl/fix-c1083-error.patch
     create mode 100644 ports/cgl/portfile.cmake
     create mode 100644 ports/chartdir/CONTROL
     create mode 100644 ports/chartdir/Config.cmake.in
     create mode 100644 ports/chartdir/chartdir.h
     create mode 100644 ports/chartdir/portfile.cmake
     create mode 100644 ports/chartdir/usage
     create mode 100644 ports/fluidsynth/force-x86-gentables.patch
     create mode 100644 ports/gppanel/00001-fix-build.patch
     create mode 100644 ports/gppanel/CMakeLists.txt
     create mode 100644 ports/gppanel/CONTROL
     create mode 100644 ports/gppanel/portfile.cmake
     create mode 100644 ports/gppanel/usage
     create mode 100644 ports/json5-parser/00001-fix-build.patch
     create mode 100644 ports/json5-parser/CONTROL
     create mode 100644 ports/json5-parser/portfile.cmake
     create mode 100644 ports/json5-parser/usage
     create mode 100644 ports/libguarded/CONTROL
     create mode 100644 ports/libguarded/portfile.cmake
     create mode 100644 ports/liblsl/fix-install.patch
     create mode 100644 ports/libwebp/0006-fix-dependecies-platform.patch
     create mode 100644 ports/log4cpp/CONTROL
     create mode 100644 ports/log4cpp/fix-install-targets.patch
     create mode 100644 ports/log4cpp/portfile.cmake
     create mode 100644 ports/magnum/004-khrplatform-include.patch
     create mode 100644 ports/minifb/CONTROL
     create mode 100644 ports/minifb/fix-arm-build-error.patch
     create mode 100644 ports/minifb/fix-build-error.patch
     create mode 100644 ports/minifb/fix-install-error.patch
     create mode 100644 ports/minifb/portfile.cmake
     delete mode 100644 ports/nmap/build.sh
     delete mode 100644 ports/nmap/detect-crypto-library.patch
     create mode 100644 ports/nmap/fix-msvc-prj.patch
     create mode 100644 ports/nmap/fix-snprintf.patch
     create mode 100644 ports/nmap/fix-ssize_t.patch
     create mode 100644 ports/orc/0004-update-tzdata.patch
     delete mode 100644 ports/poco/unbundled_pdf.patch
     create mode 100644 ports/poco/use-vcpkg-libharu.patch
     create mode 100644 ports/yaml-cpp/0002-fix-include-path.patch
     create mode 100644 toolsrc/src/vcpkg-test/stringview.cpp
    Failed at [Y:\vcpkg\toolsrc\src\vcpkg\packagespec.cpp(44)] with message:
    Contains invalid characters. Only alphanumeric lowercase ASCII characters and dashes are allowed

**Comment by PhoebeHui** [comment]
@degski, we recommend to use Powershell, and after 'git pull', it's better to run bootstrap-vcpkg.bat to rebuild vcpkg, since the VCPKG source also update.

For stray version of vcpkg.exe, except vcpkg\vcpkg.exe, I didn't have other version, I didn't clean source in recent 8 months, I'm not sure how them generated in your side, you can clean them.

**Comment by degski** [comment]
@PhoebeHui Why do you recommend Powershell [just curious]? 

As to the stray-versions, I don't know either how they got there [I did not put them there], but they are older than 8 months. At some point `vcpkg` must have been putting them there. Yes, I removed them :-).

**Comment by PhoebeHui** [comment]
@degski, I recommend Powershell since:
 vcpkg supports auto-completion of commands, package names, options etc in Powershell, see [doc](https://github.com/microsoft/vcpkg#tab-completion--auto-completion).
Another is that someone mentioned it cause unknown error before by cmd, I'm not clear now, however, if you encounter similar issue, please let us know.

**Comment by degski** [comment]
Thanks. I just have some batch scripts, so auto-completion is not an issue and so far I've never had a problem with `cmd`. In the meanwhile `cmd` is being overhauled, so I doubt it will be a problem in the future. 

No need for auto-bootstrap then?

**Comment by PhoebeHui** [comment]
For auto-bootstrap, you have brought this up in https://github.com/microsoft/vcpkg/issues/7328, for me, it's great idea, let's see the discussion from users and other team members.

**Comment by degski** [comment]
@PhoebeHui You're better at finding those things than I, yes, that's the one.

**Comment by IRelaxxx** [comment]
@PhoebeHui My PS Version is 4.0

**Comment by cbezault** [comment]
@degski those stray versions are ... interesting ... I've never seen anything like that locally.
If you wanted to try to implement the thing you're talking about you would need to support VS2015 which has a watered down c++14 implementation.
You would also need to support GCC 6.5.

**Comment by degski** [comment]
@cbezault The strays, well, I don't know, been using `vcpkg` for quite a while now. Let's just assume for the moment that the problem has gone away over time (until it doesn't).

I'm looking into that now, my biggest issue will be to hang the code properly in the existing code [and respect style and 'the' way of doing things]. I'll have to check what VS15 and GCC-6.5 support, I have VS19 and GCC-8.3 (for now).

**Comment by PhoebeHui** [comment]
@IRelaxxx, could you upgrade your Powershell and try to build again?

**Comment by IRelaxxx** [comment]
@PhoebeHui I upgrade to Powershell 5.1 and the issue is gone

**Comment by PhoebeHui** [comment]
Great to hear that! It seems vcpkg required Powershell 5.0 for some features. you can search 'powershell' in vcpkg for related information
