### ISSUE TITLE
[New Port Request] libndpi-dev

### ISSUE THREAD

**Issue by regexizer** [microsoft/vcpkg#7894]
Library name:
libndpi-dev
Library description:
nDPI is a ntop-maintained superset of the popular OpenDPI library. Released under the LGPL license, its goal is to extend the original library by adding new protocols that are otherwise available only on the paid version of OpenDPI.
Source repository URL:
https://packages.debian.org/sid/libndpi-dev

B.R

**Comment by regexizer** [comment]
what is going on? it took 6 weeks ...
u guys rly pay for this?!!!
shame!

**Comment by JackBoosY** [comment]
@regexizer Sorry for late, but we already have more than 200 new port issues asking us to add ports.
So, please understand us. 
If we added this port, we will notice you in this issue.

Thanks.

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
