### ISSUE TITLE
[New Port Request] libmagic-dev

### ISSUE THREAD

**Issue by regexizer** [microsoft/vcpkg#7895]
Library name:
libmagic-dev
Library description:
This library can be used to classify files according to magic number tests.
Source repository URL:
https://packages.debian.org/sid/libmagic-dev

B.R

**Comment by regexizer** [comment]
what is going on? it took 6 weeks ...
u guys rly pay for this?!!!
shame!

**Comment by NancyLi1013** [comment]
Hi @regexizer thanks for posting this request.
This port has been added to vcpkg. Please update vcpkg and try to use it.
