### ISSUE TITLE
[New Port Request] cityhash

### ISSUE THREAD

**Issue by regexizer** [microsoft/vcpkg#7899]
Library name:
cityhash
Library description:
CityHash provides hash functions for strings.  The functions mix the
input bits thoroughly but are not suitable for cryptography
Source repository URL:
https://github.com/google/cityhash

B.R

**Comment by Voskrese** [comment]
why so many requests? don’t even look that they are repeated
https://github.com/microsoft/vcpkg/pull/7879

**Comment by regexizer** [comment]
sorry 'bout that ;)

**Comment by Voskrese** [comment]
I'm not in this sense, the rest of the queries are similar, you can query the whole DEBIAN

Is there any windows \ msvc support?

**Comment by regexizer** [comment]
not sure about libprotoident, but rest of them should be compatible with windows ( as i know ! )

**Comment by NancyLi1013** [comment]
Hi @regexizer  thanks for posting this request. The PR #7879 has been merged to master. Please try to update vcpkg and use it.
