### ISSUE TITLE
[New Port Request] libprotoident

### ISSUE THREAD

**Issue by regexizer** [microsoft/vcpkg#7900]
Library name:
libprotoident
Library description:
Libprotoident is a library designed to perform application protocol 
identification using a very limited form of deep packet inspection, i.e. using
the first four bytes of application payload sent in each direction
Source repository URL:
https://github.com/wanduow/libprotoident

B.R

**Comment by regexizer** [comment]
wt. is going on? it took 6 weeks ...
u guys rly pay for this?!!!

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
