### ISSUE TITLE
[eigen] build failure

### ISSUE THREAD

**Issue by ollp** [microsoft/vcpkg#7902]
**Host Environment**
- OS: windows
- Compiler: latest

**To Reproduce**
download ;latest Eigen
`./vcpkg install arm64=windows C:\Users\Bent\Source\Repos\eigenteam\eigen-git-mirror`

**Failure logs** 
Failed at [..\src\vcpkg\packagespec.cpp(82)] with message:
Contains invalid characters. Only alphanumeric lowercase ASCII characters and dashes are allowed

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by shuitianxu** [comment]
Hi,@ollp Thanks for reporting this issue.
The command looks wrong here, you can use './vcpkg install eigen3:arm64-windows --head' to install Eigen latest source from github.

Console output:
PS F:\7902\vcpkg> ./vcpkg install eigen3:arm64-windows --head
The following packages will be built and installed:
    eigen3[core]:arm64-windows (from HEAD)
Starting package 1/1: eigen3:arm64-windows
Building package eigen3[core]:arm64-windows from HEAD...
A suitable version of powershell-core was not found (required v6.2.1). Downloading portable powershell-core v6.2.1...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v6.2.1/PowerShell-6.2.1-win-x86.zip -> F:\7902\vcpkg\downloads\PowerShell-6.2.1-win-x86.zip
Extracting powershell-core...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> F:\7902\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
A suitable version of nuget was not found (required v4.6.2). Downloading portable nuget v4.6.2...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v4.6.2/nuget.exe -> F:\7902\vcpkg\downloads\nuget.exe
Warning: abi keys are missing values:
    head

A suitable version of git was not found (required v2.21.0). Downloading portable git v2.21.0...
Downloading git...
  https://github.com/git-for-windows/git/releases/download/v2.21.0.windows.1/PortableGit-2.21.0-32-bit.7z.exe -> F:\7902\vcpkg\downloads\PortableGit-2.21.0-32-bit.7z.exe
Extracting git...
-- Downloading https://api.github.com/repos/eigenteam/eigen-git-mirror/git/refs/heads/master...
-- Skipping hash check for F:/7902/vcpkg/downloads/temp/eigenteam-eigen-git-mirror-master.tar.gz.version.
-- Downloading https://github.com/eigenteam/eigen-git-mirror/archive/master.tar.gz...
-- Skipping hash check for F:/7902/vcpkg/downloads/temp/eigenteam-eigen-git-mirror-master.tar.gz.
-- Extracting source F:/7902/vcpkg/downloads/eigenteam-eigen-git-mirror-master.tar.gz
-- Using source at F:/7902/vcpkg/buildtrees/eigen3/src/head/master-cf9c94a0ba
-- Configuring arm64-windows
-- Building arm64-windows-dbg
-- Building arm64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package eigen3[core]:arm64-windows... done
Installing package eigen3[core]:arm64-windows...
Installing package eigen3[core]:arm64-windows... done
Elapsed time for package eigen3:arm64-windows: 1.533 min

Total elapsed time: 1.533 min

The package eigen3:arm64-windows provides CMake targets:

    find_package(Eigen3 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Eigen3::Eigen)

**Comment by ollp** [comment]
Hi shuitianxu  

Thank you! 
That works and unfortunately first time using any package for c++ usual I write my self.
Trying to figure to next step sens first time ever...……
using this stuff. so I can get it installed.

ollp

**Comment by ollp** [comment]
Hi shuitianxu

Thank you my bad works perfect!

**Comment by shuitianxu** [comment]
You are welcome.
