### ISSUE TITLE
[CI] If a regression occurs also report the featureset

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#7905]
Just as the title says. Regressions should be reported with the build featureset. I recently came across a port which was regressing but I was unable to reproduce the problem locally. The reason i was unable to reproduce the regression was because the default feature was not the one tested by CI. So CI should report regression with the build feature set to avoid those cases.

**Comment by Rastaban** [comment]
This would be good.  We are getting ready to make a wave a changes to the CI system and should be able to do this at the same time.
