### ISSUE TITLE
[opencv[cuda]] build failure

### ISSUE THREAD

**Issue by RRathmann** [microsoft/vcpkg#7913]
**Host Environment**
- OS: Windows 10
- Compiler: The CXX compiler identification is MSVC 19.22.27905.0
- CUDA 10.1

**To Reproduce**
`./vcpkg install opencv[cuda]`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:58 (message):
    Command failed: ninja -v
    Working Directory: C:/DevTools/Development/Tools/Microsoft/vcpkg-2019-08-26/buildtrees/opencv4/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\DevTools\Development\Tools\Microsoft\vcpkg-2019-08-26\buildtrees\opencv4\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:296 (vcpkg_execute_required_process)
  ports/opencv4/portfile.cmake:244 (vcpkg_configure_cmake)
  scripts/ports.cmake:85 (include)

Error: Building package opencv4:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv4:x86-windows
  Vcpkg version: 2019.08.16-nohash

**Additional context**
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/3543005/config-x86-windows-out.log)

**Comment by Voskrese** [comment]
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.

`--     Extra dependencies:          opengl32 glu32 cudart_static.lib C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/Win32/cuda.lib CUDA_nppc_LIBRARY-NOTFOUND CUDA_nppial_LIBRARY-NOTFOUND CUDA_nppicc_LIBRARY-NOTFOUND CUDA_nppicom_LIBRARY-NOTFOUND CUDA_nppidei_LIBRARY-NOTFOUND CUDA_nppif_LIBRARY-NOTFOUND CUDA_nppig_LIBRARY-NOTFOUND CUDA_nppim_LIBRARY-NOTFOUND CUDA_nppist_LIBRARY-NOTFOUND CUDA_nppisu_LIBRARY-NOTFOUND CUDA_nppitc_LIBRARY-NOTFOUND CUDA_npps_LIBRARY-NOTFOUND CUDA_cublas_LIBRARY-NOTFOUND CUDA_cufft_LIBRARY-NOTFOUND -LIBPATH:"C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/Win32"`

**Comment by cenit** [comment]
Unfortunately cuda feature is unavailable with x86 triplets, only x64 ones work.
I will try to investigate how much difficult it would be to support x86 using an older version of cuda
