### ISSUE TITLE
progress bar

### ISSUE THREAD

**Issue by deguangchow** [microsoft/vcpkg#7918]
I hope you can add a progress bar when downloading or compiling, just like 'apt' in Linux.

**Comment by cbezault** [comment]
I'm not sure this is going to happen any time soon but it's a reasonable feature request, maybe a community member can pick it up.

**Comment by NikBomb** [comment]
I would like to contribute, I use vcpkg and I feel that a progress bar is a very good feature to add.

**Comment by PhoebeHui** [comment]
The feature would be added by PR https://github.com/microsoft/vcpkg/pull/12550
