### ISSUE TITLE
flatbuffers:x86-windows cmake Error at ports/flatbuffers/portfile.cmake:46

### ISSUE THREAD

**Issue by cxq2003** [Microsoft/vcpkg#793]
Package: flatbuffers:x86-windows
 Vcpkg version: 0.0.76-a92ecac8a79c9b03ba3aa86b1478f75c4d2f8847

Builds ok, but CMake Error at ports/flatbuffers/portfile.cmake:46 (file):
  file RENAME failed to rename
  C:/vcpkg/packages/flatbuffers_x86-windows/bin/flatc.exe
to
  C:/vcpkg/packages/flatbuffers_x86-windows/tools/flatc.exe
because: No such file or directory

I assure the exist of  "C:/vcpkg/packages/flatbuffers_x86-windows/bin/flatc.exe".

**Comment by Mixaill** [comment]
Please try fix from #795
