### ISSUE TITLE
Warnings about dll interface after installing protobuf with vcpkg

### ISSUE THREAD

**Issue by kakyoism** [microsoft/vcpkg#7936]
I don't recall seeing the following warnings when building `protobuf` examples from source. These warnings only happen when building applications using the vcpkg-installed `protobuf`:

```
1>e:\_dev\vcpkg\installed\x64-windows\include\google\protobuf\io\coded_stream.h(881): warning C4251: 'google::protobuf::io::CodedOutputStream::default_serialization_deterministic_': struct 'std::atomic<bool>' needs to have dll-interface to be used by clients of class 'google::protobuf::io::CodedOutputStream'
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xxatomic(162): note: see declaration of 'std::atomic<bool>'
1>e:\_dev\vcpkg\installed\x64-windows\include\google\protobuf\stubs\logging.h(102): warning C4251: 'google::protobuf::internal::LogMessage::message_': class 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>' needs to have dll-interface to be used by clients of class 'google::protobuf::internal::LogMessage'
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xstring(4373): note: see declaration of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'
1>e:\_dev\vcpkg\installed\x64-windows\include\google\protobuf\arena_impl.h(251): warning C4251: 'google::protobuf::internal::ArenaImpl::lifecycle_id_generator_': struct 'std::atomic<__int64>' needs to have dll-interface to be used by clients of class 'google::protobuf::internal::ArenaImpl'
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xxatomic(162): note: see declaration of 'std::atomic<__int64>'
1>e:\_dev\vcpkg\installed\x64-windows\include\google\protobuf\arena_impl.h(285): warning C4251: 'google::protobuf::internal::ArenaImpl::threads_': struct 'std::atomic<google::protobuf::internal::ArenaImpl::SerialArena *>' needs to have dll-interface to be used by clients of class 'google::protobuf::internal::ArenaImpl'
1>e:\_dev\vcpkg\installed\x64-windows\include\google\protobuf\arena_impl.h(284): note: see declaration of 'std::atomic<google::protobuf::internal::ArenaImpl::SerialArena *>'
1>e:\_dev\vcpkg\installed\x64-windows\include\google\protobuf\arena_impl.h(286): warning C4251: 'google::protobuf::internal::ArenaImpl::hint_': struct 'std::atomic<google::protobuf::internal::ArenaImpl::SerialArena *>' needs to have dll-interface to be used by clients of class 'google::protobuf::internal::ArenaImpl'
1>e:\_dev\vcpkg\installed\x64-windows\include\google\protobuf\arena_impl.h(284): note: see declaration of 'std::atomic<google::protobuf::internal::ArenaImpl::SerialArena *>'
1>e:\_dev\vcpkg\installed\x64-windows\include\google\protobuf\arena_impl.h(287): warning C4251: 'google::protobuf::internal::ArenaImpl::space_allocated_': struct 'std::atomic<unsigned __int64>' needs to have dll-interface to be used by clients of class 'google::protobuf::internal::ArenaImpl'
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xxatomic(162): note: see declaration of 'std::atomic<unsigned __int64>'
1>e:\_dev\vcpkg\installed\x64-windows\include\google\protobuf\arena_impl.h(299): warning C4251: 'google::protobuf::internal::ArenaImpl::options_': struct 'google::protobuf::internal::ArenaImpl::Options' needs to have dll-interface to be used by clients of class 'google::protobuf::internal::ArenaImpl'
1>e:\_dev\vcpkg\installed\x64-windows\include\google\protobuf\arena_impl.h(68): note: see declaration of 'google::protobuf::internal::ArenaImpl::Options'
1>e:\_dev\vcpkg\installed\x64-windows\include\google\protobuf\implicit_weak_message.h(97): warning C4251: 'google::protobuf::internal::ImplicitWeakMessage::data_': class 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>' needs to have dll-interface to be used by clients of class 'google::protobuf::internal::ImplicitWeakMessage'
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xstring(4373): note: see declaration of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'
1>e:\_dev\vcpkg\installed\x64-windows\include\google\protobuf\generated_message_util.h(176): warning C4251: 'google::protobuf::internal::CachedSize::size_': struct 'std::atomic<int>' needs to have dll-interface to be used by clients of class 'google::protobuf::internal::CachedSize'
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xxatomic(162): note: see declaration of 'std::atomic<int>'
1>e:\_dev\vcpkg\installed\x64-windows\include\google\protobuf\metadata_lite.h(226): warning C4251: 'google::protobuf::internal::LiteUnknownFieldSetter::buffer_': class 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>' needs to have dll-interface to be used by clients of class 'google::protobuf::internal::LiteUnknownFieldSetter'
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xstring(4373): note: see declaration of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'
1>e:\_dev\vcpkg\installed\x64-windows\include\google\protobuf\inlined_string_field.h(158): warning C4251: 'google::protobuf::internal::InlinedStringField::value_': class 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>' needs to have dll-interface to be used by clients of class 'google::protobuf::internal::InlinedStringField'
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xstring(4373): note: see declaration of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'
1>e:\_dev\vcpkg\installed\x64-windows\include\google\protobuf\unknown_field_set.h(182): warning C4251: 'google::protobuf::UnknownFieldSet::fields_': class 'std::vector<google::protobuf::UnknownField,std::allocator<_Ty>>' needs to have dll-interface to be used by clients of class 'google::protobuf::UnknownFieldSet'
```

Did I miss any compiler flags related to vcpkg?

**Comment by JackBoosY** [comment]
Hi @kakyoism, sorry for late.
I can't repro this issue in the latest version, can you confirm that?

Thanks.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you.

**Comment by LilyWangLL** [comment]
Ping @kakyoism for response. Now the version of `protobuf` is 3.18.0, and PR#21485 will update `protobuf` to version 3.19.3, does this issue still occur on latest version of protobuf? If this issue still exist, please provide the detail repro steps and repro codes.

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.

**Comment by fbrier** [comment]
@kakyoism Are you building a debug or release version? I see these same errors building debug. I have not checked whether they do not appear in release.

**Comment by jdoubleu** [comment]
I'm still experiencing the issue.

I've prepared a minimal reproduction repository: https://github.com/jdoubleu/vcpkg-issue-7936.
As you can see in the CI, it's failing: https://github.com/jdoubleu/vcpkg-issue-7936/runs/7675842357?check_suite_focus=true#step:4:95

I was able to narrow down the issue to the following pre-conditions:
1. CMake must be used with the Visual Studio generator (i.e. `Visual Studio 17 2022`).
2. The warning level needs to be [increased](https://github.com/jdoubleu/vcpkg-issue-7936/blob/main/CMakeLists.txt#L22).
    * In my case, I even enabled warnings to trigger errors, so the actual build fails. 

The following issues seem related:
* https://github.com/protocolbuffers/protobuf/issues/8691

**Comment by jdoubleu** [comment]
I noticed, that the definition `PROTOBUF_USE_DLLS` is set to `__declspec(dllimport)`, although [`set(Protobuf_USE_STATIC_LIBS ON)` is set in CMake](https://github.com/jdoubleu/vcpkg-issue-7936/blob/main/CMakeLists.txt#L6). This might have no impact, depending on how the PackageConfig file is setup in vcpkg.

For reference: https://github.com/protocolbuffers/protobuf/blob/main/cmake/README.md#dlls-vs-static-linking

**Comment by jdoubleu** [comment]
When building and linking against `libprotobuf` dynamically, there's no real way around this issue. While you can ignore or even disable the warning, you'll get into more trouble with ABI stability in the future. As Google [suggests](https://github.com/protocolbuffers/protobuf/blob/main/cmake/README.md#dlls-vs-static-linking), you should prefer linking Protobuf statically.

Now, in order to build `libprotobuf` as a static library, you need to choose the `x64-windows-static` triplet rather than just `x64-windows-static`. It looks like the [portfile doesn't honor](https://github.com/microsoft/vcpkg/blob/master/ports/protobuf/portfile.cmake#L16) the `Protobuf_USE_STATIC_LIBS` variable from the [default package resolving logic](https://cmake.org/cmake/help/latest/module/FindProtobuf.html).

Unfortunately, using `x64-windows-static` will also [cause the library to be linked against the static version](https://github.com/microsoft/vcpkg/blob/master/ports/protobuf/portfile.cmake#L17) of the MSVC runtime. When you try to [link your main executable against `libprotobuf`](https://github.com/jdoubleu/vcpkg-issue-7936/blob/b136fc76f2996142f4c04bfa0f3c354361bb0ad3/CMakeLists.txt#L20), you'll get a bunch of these errors:
```
libprotobufd.lib(common.cc.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in main.obj
```

That's because you also need to link your main executable against the static MSVC runtime (see [`MSVC_RUNTIME_LIBRARY` property](https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html)). The `libprotobuf` CMake target does not expose this (e.g. thorugh `INTERFACE_` properties); I'm not even sure if that's possible with CMake.

I ended up [overlaying the triplet configuration](https://vcpkg.io/en/docs/users/triplets.html), explicitly [setting `VCPKG_CRT_LINKAGE ` to `dynamic`](https://github.com/jdoubleu/vcpkg-issue-7936/blob/main/triplets/x64-windows-static.cmake#L2).

I still got a waning when including the headers, but that's more of an issue from Protobuf than of vcpkg.

**Comment by JackBoosY** [comment]
Waiting for the upstream fix this issue (https://github.com/protocolbuffers/protobuf/issues/8691). Then I will repoen this and have an update.

**Comment by jotalanusse** [comment]
Is this issue fixed yet? I'm still getting these warnings while using the latest version of Protobuf `v4.25.1` in vcpkg.
