### ISSUE TITLE
#7793 broke --overlay-triplets

### ISSUE THREAD

**Issue by BurningEnlightenment** [microsoft/vcpkg#7943]
Since #7793 has been merged it is assumed that the `.vcpkg-root` file will be located in the parent directory of the directory containing the target triplet. This assumption is obviously bogus if `--overlay-triplets` is used to specify a target triplet outside of the vcpkg folder.
I.e. `--overlay-triplets` is currently broken and unusable without manually specifying the vcpkg root.

**Environment**
- OS: platform independent
- Compiler: compiler independent

**To Reproduce**
1.` cp ./triplets/x64-windows-static.cmake ../custom-triplets/x64-windows-custom.cmake`
2. `./vcpkg install --triplet x64-windows-custom --overlay-triplets=../custom-triplets/ any-package`
3. See error:
> CMake Error at scripts/ports.cmake:15 (message):
>  Could not find .vcpkg-root

**Expected behavior**
no error.

**Comment by kiwixz** [comment]
It's fixed 👍
