### ISSUE TITLE
[pango] update to 1.44.5

### ISSUE THREAD

**Issue by Vultraz** [microsoft/vcpkg#7946]
Library name: pango

New version number: 1.44.5

Other information that may be useful (release notes, etc...): I tried to update to 1.44.5 (current vcpkg version is 1.40.11), but there are a whole bunch of changes to file layout and the build system since current that need to be accounted for. I don't have experience working with cmake so I can't do this myself.

**Comment by PhoebeHui** [comment]
Pango has new revision, duplicate of https://github.com/microsoft/vcpkg/issues/15576
