### ISSUE TITLE
  Package: openblas:x86-windows   

### ISSUE THREAD

**Issue by Lancelot899** [microsoft/vcpkg#7947]
Package: openblas:x86-windows                                                                                         
 Vcpkg version: 2019.08.23-nohash

**Comment by ehsan-mohammadi** [comment]
@Lancelot899 Can you please tell me what's the problem?

**Comment by ehsan-mohammadi** [comment]
Also, read this #7776 issue. Maybe it helps you :)

**Comment by cbezault** [comment]
openblas only build for x64
