### ISSUE TITLE
[jsoncpp] build failure - regression in 65d4bc1

### ISSUE THREAD

**Issue by rpavlik** [microsoft/vcpkg#7951]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019 x64
- CMake: 3.15.2.

**To Reproduce**
`.\vcpkg.exe install jsoncpp --triplet x64-windows`

with https://github.com/microsoft/vcpkg/commit/65d4bc146bf7c1c21989b680497b1f6f9a09c967

**Failure logs** 
```
PS C:\vcpkg> .\vcpkg.exe install jsoncpp --triplet x64-windows
The following packages will be built and installed:
    jsoncpp[core]:x64-windows
Starting package 1/1: jsoncpp:x64-windows
Building package jsoncpp[core]:x64-windows...
-- Using cached C:/vcpkg/downloads/open-source-parsers-jsoncpp-1.9.1.tar.gz
-- Using source at C:/vcpkg/buildtrees/jsoncpp/src/1.9.1-f819ab5ce5
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/execute_process.cmake:12 (message):
    This command cannot be executed in Download Mode.
    Halting portfile execution.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_execute_build_process.cmake:41 (execute_process)
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/jsoncpp/portfile.cmake:28 (vcpkg_install_cmake)
  scripts/ports.cmake:85 (include)


Error: Building package jsoncpp:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: jsoncpp:x64-windows
  Vcpkg version: 2019.08.27-nohash

Additionally, attach any relevant sections from the log files above.
```

**Additional context**

Rolling back to the previous commit, rebuilding vcpkg, and trying again works.

**Comment by JackBoosY** [comment]
Hi @rpavlik, thanks for reporting this issue.
I cannot repro this issue on my machine, and it seems that is a cmake issue.

So, can you remove the custom installed cmake and try again?

Thanks.

**Comment by rpavlik** [comment]
Weird, I thought vcpkg used its own cmake - it certainly used its own lots-of-other-things-I-actually-have-installed. But, when trying installing this package again without cmake installed (I had 3.15.9 I think - whatever choco gave me) it did download 3.14.0, and it did work then. So, something about that patch is broken by cmake between 3.14.0 and 3.15.9 apparently.

**Comment by LilyWangL** [comment]
Hi @rpavlik, I installed it successfully with cmake 3.15.3 and vcpkg latest source. Could you upgrade cmake to version 3.15.3 and install it again?

Thanks.

**Comment by JackBoosY** [comment]
@rpavlik Vcpkg now uses user-installed cmake first.

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen it.
