### ISSUE TITLE
Race condition in source directory if cmake customizes sources (configure_file, ...)

### ISSUE THREAD

**Issue by bitwiser73** [microsoft/vcpkg#7952]
**Describe the bug**
Package build sometimes fails because of a race condition inside source directory while vcpkg executes cmake to generate build directories. Some projects are customizing the sources directory (using for example CMake's `configure_file`).

I had random failures while building package with "permission denied" or "configure_file: Problem configuring file".

**Environment**
- OS: Windows 10 1809
- Compiler: 19.22.27905.0

**To Reproduce**
It happened with a port I have not release yet but I guess it could happened any projects doing some in-place source modification or with the following ports:
```
fontconfig/CMakeLists.txt:76:    configure_file(fonts.conf.in ${CMAKE_SOURCE_DIR}/fonts.conf @ONLY)
gdk-pixbuf/CMakeLists.txt:18:    configure_file(${CMAKE_SOURCE_DIR}/config.h.win32 ${CMAKE_SOURCE_DIR}/config.h COPYONLY)
gdk-pixbuf/CMakeLists.txt:20:    configure_file(${CMAKE_SOURCE_DIR}/config.h.linux ${CMAKE_SOURCE_DIR}/config.h COPYONLY)
glib/CMakeLists.txt:286:    configure_file(gobject/glib-mkenums.in ${CMAKE_SOURCE_DIR}/gobject/glib-mkenums @ONLY) # uses GLIB_VERSION
glib/CMakeLists.txt:289:    configure_file(gio/gdbus-2.0/codegen/gdbus-codegen.in ${CMAKE_SOURCE_DIR}/gio/gdbus-2.0/codegen/gdbus-codegen COPYONLY)
libnice/CMakeLists.txt:13:configure_file(${CMAKE_SOURCE_DIR}/win32/vs9/config.h ${CMAKE_SOURCE_DIR}/config.h COPYONLY)
libnice/CMakeLists.txt:14:configure_file(${CMAKE_SOURCE_DIR}/win32/vs9/libnice.def ${CMAKE_SOURCE_DIR}/libnice.def COPYONLY)
```
Do some vcpkg remove / install until permission denied or any other error triggers.

**Expected behavior**
Sometimes package build is failing, I would expect to work everytime.

**Failure logs** 
[config-x64-windows-static-out.log](https://github.com/microsoft/vcpkg/files/3552847/config-x64-windows-static-out.log)

**Additional context**
Using process monitor I understood that vcpkg creates two concurrents CMake processes to generate debug and release directories. Therefore `configure_file` can fail for various reasons. 

Involved process are selected below.

![vcpkg_issue_procmon_cmake_capture](https://user-images.githubusercontent.com/23187701/63892261-80f9e580-c9e7-11e9-99db-9b092932ea64.png)

![vcpkg_issue_procmon_cmake_debug](https://user-images.githubusercontent.com/23187701/63892262-80f9e580-c9e7-11e9-84a1-2ae3d5b34e1e.png)

![vcpkg_issue_procmon_cmake_release](https://user-images.githubusercontent.com/23187701/63892263-81927c00-c9e7-11e9-818d-5fa3014ea4da.png)

**Comment by Rastaban** [comment]
Does this happen inside of a call to [vcpkg_configure_cmake](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_configure_cmake.md)?  If so you should use the `DISABLE_PARALLEL_CONFIGURE` flag.  

From the documentation:

> **DISABLE_PARALLEL_CONFIGURE**
> Disables running the CMake configure step in parallel. This is needed for libraries which write back into their source directory during configure.

**Comment by bitwiser73** [comment]
Thank you, did not see this flag
