### ISSUE TITLE
[gtest] CMake warning CMP0012 

### ISSUE THREAD

**Issue by curtpm** [microsoft/vcpkg#7953]
****
Using cmake 3.14.0 I see the following error when using gtest/gmock on Ubuntu 19.04

installed gtest with:
```
vcpkg install gtest
```

reference target with:
```
find_package(GTest CONFIG REQUIRED)
```

```
CMake Warning (dev) at vcpkg/installed/x64-linux/share/gtest/GTestConfig.cmake:27 (if):
  if given arguments:

    "ON"

  An argument named "ON" appears in a conditional statement.  Policy CMP0012
  is not set: if() recognizes numbers and boolean constants.  Run "cmake
  --help-policy CMP0012" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.
```

looking at the GTestConfig.cmake file this is the section that is causing the warning: 

```
include(CMakeFindDependencyMacro)
if (ON)   <----- This check 
  set(THREADS_PREFER_PTHREAD_FLAG )
  find_dependency(Threads)
endif()

include("${CMAKE_CURRENT_LIST_DIR}/GMockTargets.cmake")
check_required_components("")
```

**Comment by NancyLi1013** [comment]
Hi @curtpm thanks for posting this issue.
I noticed that `CMP0012 `was introduced in `CMake `version 2.8.0. 
I also did some tests about this. I found that if we used 2.8.0 or above version by `cmake_minimum_required ()`, there would be no warning messages.

But if we used `CMake `version below 2.8.0, it would post CMP0012 warning messages.
So I want to confirm with you if you used 3.14 in `cmake_minimum_required ()`?

**Comment by curtpm** [comment]
Yes it was cmake 3.14.0

**Comment by NancyLi1013** [comment]
Thanks for your reply.
I cannot reproduce this issue on my local using `CMake `3.14.
Only when I used `CMake `version less than 2.8 or not used `cmake_minimum_required (VERSION 3.14)`, it would post `CMP0012 `warning messages.
Could you please try to add this and try it again?
```
if(POLICY CMP0012)
  cmake_policy(SET CMP0012 NEW)
endif()
```

**Comment by NancyLi1013** [comment]
Could you help confirm if the above suggestion can work for you?

**Comment by NancyLi1013** [comment]
I'm going to closing this issue for now since there's been no response.
Please reopen this if it is still a problem for you.
