### ISSUE TITLE
vcpkg macros not defined when using v140 toolset in vs2019

### ISSUE THREAD

**Issue by terrylyons** [microsoft/vcpkg#7957]
**Describe the bug**
The macros $(VcpkgRoot) is not defined. 

When the toolset is v140 the $(VcpkgTriplet) macro is appropriately defined to be x64-windows-v140 by my vcxproj project file, and correctly propagates as such when looking at macro settings inside visual studio; however build fails. If the toolset is  v141 or v142  extra variables are automatically defined including $(vcpkroot), appropriate paths are selected and build succeeds normally.

The v140 choice does not define any other Vcp* named macros - in particular to root for the vcpkg.

the content of the v140 triplet is
set(VCPKG_PLATFORM_TOOLSET v140)
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

**Environment**
- OS:windows 10
- 16.2.2

**To Reproduce**
0. Have VS set up with all three toolsets v140 v141 v142
1. Edit the project files as recommended (see attached)
3. Examine the defined macros in the build system when different toolsets are selected
4. Try to build the project with the different toolsets (having first installed via vcpkg the correct libraries - the build succeeds for 142, 141 but fails on a path error for 140 

**Expected behavior**
the build should succeed for all three toolsets
**Failure logs** 
[TestVspkg.log](https://github.com/microsoft/vcpkg/files/3553998/TestVspkg.log)

**Additional context**

[TestVspkg.vcxproj.txt](https://github.com/microsoft/vcpkg/files/3554071/TestVspkg.vcxproj.txt)

**Comment by Voskrese** [comment]
add tag <LIB> or <LINK>
`$(VcpkgRoot)\$(VcpkgTriplet)\lib;$(VcpkgRoot)lib;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>`

add tag <ClCompile>
`$(VcpkgRoot)\$(VcpkgTriplet)\include;$(VcpkgRoot)include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>`

**Comment by terrylyons** [comment]
Looks good, but how does this differentiate between 140, 141,142. Is it missing somewhere?


VcpkgRoot is not defined in 140 and is in the other two.



Terry

On 29 Aug 2019, at 14:31, Voskrese <notifications@github.com<mailto:notifications@github.com>> wrote:


add tag or
$(VcpkgRoot)\$(VcpkgTriplet)\lib;$(VcpkgRoot)lib;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>

add tag
$(VcpkgRoot)\$(VcpkgTriplet)\include;$(VcpkgRoot)include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>

**Comment by Voskrese** [comment]
`$(VcpkgRoot)`

**Comment by Voskrese** [comment]
most likely I did not understand the question, do I need to reassign TOOLSET?

but why if you use set (VCPKG_PLATFORM_TOOLSET v140)

if you do not have MSVC 2015 installed, then why indicate v140?

**Comment by terrylyons** [comment]
Sadly, I have most versions of visual studio installed. 2008 and 2010 and 2015 for python extensions; 2013 for certain cuda based apps. This is the windows developer way... simpler for the user.  Older software still works.

Fortunately visual studio 2019 handles all this easily. I can build them all inside 2017/2019, just changing the toolset and windows target. I routinely use 2015/v140 /8.1 to build some of my console programs inside VS2019.

I followed the vcpkg example where  by modifying the vcxproj file visual studio selects and defines the triplet name to x64-windows-v14x as I change toolset between 140 141 and 142.

The V141 and v142 settings in VS2019 both work, select correct libraries and build; the v140 setting should also work I suppose. But it falls over; the most obvious error seems to be that the paths seem not to have the vcpkgroot inserted and the macro and several others are not defined. They are defined for the other two toolset that work.

I hope this makes sense.

Terry

On 29 Aug 2019, at 16:08, Voskrese <notifications@github.com<mailto:notifications@github.com>> wrote:

most likely I did not understand the question, do I need to reassign TOOLSET?

but why if you use set (VCPKG_PLATFORM_TOOLSET v140)

if you do not have MSVC 2015 installed, then why indicate v140?

As I said, I do have the v140 toolset installed (and vs2015 although I am using and building with the toolset in vs2019).

I indicate v140 because I want/need to build with v140. Just as I might want/need to build with clang, or an XP_compatible toolset...

One cannot deduce the toolset used in a build from the version of visual studio one is using. The options are limited by the toolset installed (usually installed by installing different visual studio versions or SDKs; there is a special 2008 toolset maintained for python 2.7).

If the code assumes it is being called by vs2015 when toolset v140 is used I can see potential for malfunction?

**Comment by Voskrese** [comment]
v120
v140
v141
v142

should work through TRIPLET

`vcpkg integrate install`
automatically integrated into the project during assembly

**Comment by terrylyons** [comment]
Would you like me to try v120 from vs2019.  I would need to create triplets and install the libraries first. I have run

vcpkg integrate install

Should I run it again; as I said the integration works fine for 141 and 142.

Terry

On 29 Aug 2019, at 22:40, Voskrese <notifications@github.com<mailto:notifications@github.com>> wrote:


v120
v140
v141
v142

should work through TRIPLET

vcpkg integrate install
automatically integrated into the project during assembly

**Comment by Voskrese** [comment]
honestly I do not understand the essence of the issue
no headers found in your project

I already wrote a solution

about compiler compatibility, this is a separate issue

**Comment by terrylyons** [comment]
Just to say I did do

vcpkg integrate install 

at the beginning. 

I would be delighted if I have simply misunderstood something. The tool seems fantastic.

**Comment by terrylyons** [comment]
Thank you for your attention!  Who said anything about headers?

My situation is that, in vs2019 with a new console project with a simple boost dependency, and with boost installed via vcpkg I cannot successfully build it if I set my toolkit to v140.

The error seems to be that the automation fails to inject some variables into the ms-build build process. In particular the root directory for the vcpkg is not set.

The error does not occur in vs2019 if the setting is v142 or v141.

To the best of my knowledge the triplets used for installation etc are set up appropriately. One for each toolset. Is that a mistake?

Apologies if it is still not clear.

On 29 Aug 2019, at 23:00, Voskrese <notifications@github.com<mailto:notifications@github.com>> wrote:


honestly I do not understand the essence of the issue
no headers found in your project

I already wrote a solution

about compiler compatibility, this is a separate issue

**Comment by Voskrese** [comment]
> **Failure logs**
> [TestVspkg.log](https://github.com/microsoft/vcpkg/files/3553998/TestVspkg.log)

> TestVspkg.cpp(21): fatal error C1083: Cannot open include file: 'boost/filesystem/operations.hpp': No such file or directory


in General, I don't know what else to recommend, maybe someone else will tell you

**Comment by terrylyons** [comment]
Yes, that error breaks the build. The other choices (141 142) instead prepend a path built out of the root directory and the triplet information to this path and run correctly.

I don’t know the design of the code however it seems to me likely that somewhere in vcpkg there is some vs2015 specific code that is (wrongly) triggered by the v140 option which VS2019 does not like. The corresponding VS2017 code triggered by the v141 option might be close enough that the vs2019 does the anticipated thing.

Thinking about it, I am not at all sure how the default integration works in vcpkg when one has multiple versions of vs installed. Does vcpkg autoinstall a different version of a package for each version of VS present? That would be cool.  If so I wonder what is the naming convention and path convention.

Thanks for your interest!!


On 29 Aug 2019, at 23:55, Voskrese <notifications@github.com<mailto:notifications@github.com>> wrote:


Failure logs
TestVspkg.log<https://github.com/microsoft/vcpkg/files/3553998/TestVspkg.log>

TestVspkg.cpp(21): fatal error C1083: Cannot open include file: 'boost/filesystem/operations.hpp': No such file or directory

in General, I don't know what else to recommend, maybe someone else will tell you

**Comment by CallumJamieson** [comment]
I have exactly the same problem and it is very frustrating....

**Comment by degski** [comment]
I've simply defined and set `VCPKG_ROOT` in my environment, and that works.

**Comment by Neumann-A** [comment]
@terrylyons: Where is or MSBuild for v140 located? You can check `<vcpkgroot\toolsrc\src\vcpkg\commands.integrate.cpp>` how the integration basically works. It could be that it is not properly installed for the v140 toolset when the others are available? The idea is that it installs a redirection in one of the MSBuild files which loads the file in `%LOCALAPPDATA%/vcpkg/vcpkg.user.targets` which itself redirects to a file in the  `<vcpkgroot\scripts\buildsystems\msbuild\vcpkg.targets>`

The variable which gets installed is: 
```
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!-- version 1 -->
  <PropertyGroup>
    <VCLibPackagePath Condition="'$(VCLibPackagePath)' == ''">$(LOCALAPPDATA)\vcpkg\vcpkg.user</VCLibPackagePath>
  </PropertyGroup>
  <Import Condition="'$(VCLibPackagePath)' != '' and Exists('$(VCLibPackagePath).targets')" Project="$(VCLibPackagePath).targets" />
</Project>
```
so if your project does not have/show you the variable `VCLibPackagePath` it is not integrated into the v140 toolchain.

**Comment by terrylyons** [comment]
This looks helpful. I have not had time to go back, but I will. I find that vcpkg is fundamentally changing things for me – dramatically reducing the number of prop files I need – for boost etc. But the lack of different platforms is a big issue so I hope we can get to the bottom of it.

In case you see something my VS2015 toolkit in VS2019 comes via the installation of VS2015 enterprise.

I currently have Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3

And among the many work packages those that seem potentially relevant are
Visual C++ 2015   00322-80000-00000-AA535
Microsoft Visual C++ 2015
Clang with Microsoft CodeGen   14.0.25516
Clang with Microsoft CodeGen
Intel® Parallel Studio XE 2019 Update 4 Composer Edition for C++ Windows*   Package ID: w_comp_lib_2019.4.228
Intel® Parallel Studio XE 2019 Update 4 Composer Edition for C++ Windows* Integration for Microsoft* Visual Studio* 2015, Version 19.0.6.14, Copyright © 2002-2019 Intel Corporation. All rights reserved.
* Other names and brands may be claimed as the property of others.
Intel® Parallel Studio XE 2019 Update 4 Composer Edition for Fortran Windows*   Package ID: w_comp_lib_2019.4.228
Intel® Parallel Studio XE 2019 Update 4 Composer Edition for Fortran Windows* Integration for Microsoft Visual Studio* 2015, Version 19.0.0052.14, Copyright © 2002-2019 Intel Corporation. All rights reserved.
Visual Assist   10.9.2341.2
For more information about Visual Assist, see the Whole Tomato Software website at http://www.WholeTomato.com. Copyright (c)1997-2019 Whole Tomato Software, LLC

Visual C++ for Cross Platform Mobile Development (Android)   14.0.25401.00
Visual C++ for Cross Platform Mobile Development (Android)

Visual C++ for Cross Platform Mobile Development (iOS)   14.0.25401.00
Visual C++ for Cross Platform Mobile Development (iOS)

Visual C++ for Linux Development   1.0.5
Visual C++ for Linux Development

**Comment by PhoebeHui** [comment]
This should not be a problem now, My VM have vs2019 16.7.14 with vs2015 toolset installed, and the project build with v140 successfully. Please get latest source and try again, please report a new issue if the problem persists for you.
