### ISSUE TITLE
 openssl-unix:x64-linux build failed

### ISSUE THREAD

**Issue by newbiediver** [microsoft/vcpkg#7960]
CMake Error at ports/openssl-unix/portfile.cmake:41 (message):
  Could not find make.  Please install it through your package manager.
Call Stack (most recent call first):
  scripts/ports.cmake:85 (include)

Error: Building package openssl-unix:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-unix:x64-linux
  Vcpkg version: 2019.08.27-unknownhash

it seems that has problem above. "openssl-unix" But it's ok on windows.
I'm using vcpkg and it would download 1.70 version of boost.
(No appearance 1.71 on vcpkg)
Please check!

**Comment by shuitianxu** [comment]
I do not repro this issue.

vzhahu@vzhahu0030:~/7960/vcpkg$ ./vcpkg install openssl-unix:x64-linux
The following packages will be built and installed:
    openssl-unix[core]:x64-linux
Starting package 1/1: openssl-unix:x64-linux
Building package openssl-unix[core]:x64-linux...
-- Downloading https://www.openssl.org/source/openssl-1.0.2s.tar.gz...
-- Extracting source /home/vzhahu/7960/vcpkg/downloads/openssl-1.0.2s.tar.gz
-- Applying patch ConfigureIncludeQuotesFix.patch
-- Applying patch STRINGIFYPatch.patch
-- Applying patch EmbedSymbolsInStaticLibsZ7.patch
-- Using source at /home/vzhahu/7960/vcpkg/buildtrees/openssl-unix/src/1.0.2s-20                                                                             837d8435
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/aes.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/asn1.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/asn1_mac.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/asn1t.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/bio.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/bn.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/buffer.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/camellia.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/cmac.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/cms.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/comp.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/conf.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/conf_api.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/crypto.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/des.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/des_old.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/dh.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/dsa.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/dso.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/dtls1.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/e_os2.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/ebcdic.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/ec.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/ecdh.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/ecdsa.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/engine.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/err.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/evp.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/hmac.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/krb5_asn.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/kssl.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/lhash.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/md4.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/md5.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/mdc2.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/modes.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/obj_mac.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/objects.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/ocsp.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/opensslconf.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/opensslv.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/ossl_typ.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/pem.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/pem2.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/pkcs12.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/pkcs7.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/pqueue.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/rand.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/rc2.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/rc4.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/ripemd.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/rsa.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/safestack.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/sha.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/srp.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/srtp.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/ssl.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/ssl2.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/ssl23.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/ssl3.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/stack.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/symhacks.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/tls1.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/ts.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/txt_db.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/ui.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/ui_compat.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/whrlpool.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/x509.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/x509_vfy.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/include/o                                                                             penssl/x509v3.h
-- Installing: /home/vzhahu/7960/vcpkg/packages/openssl-unix_x64-linux/share/ope                                                                             nssl-unix/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package openssl-unix[core]:x64-linux... done
Installing package openssl-unix[core]:x64-linux...
Installing package openssl-unix[core]:x64-linux... done
Elapsed time for package openssl-unix:x64-linux: 3.317 min

Total elapsed time: 3.317 min

 openssl-unix:x64-linux install ok.

**Comment by JackBoosY** [comment]
If this issue is still not resolved, please reopen it.
