### ISSUE TITLE
boost-regex build failure

### ISSUE THREAD

**Issue by lbc3402785** [microsoft/vcpkg#7965]
**Host Environment**
- OS: [e.g. Windows10]
- Compiler: vs2015 x64

**To Reproduce**
`./vcpkg install boost`

**Failure logs** 
Error: Building package boost-regex:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-regex:x64-windows
  Vcpkg version: 2019.08.27-nohash

**Comment by kakyoism** [comment]
I had a failure around here, not sure if it's related:
```
Installing package boost-assign[core]:x64-windows...
Installing package boost-assign[core]:x64-windows... done
Elapsed time for package boost-assign:x64-windows: 4.678 s
Starting package 39/86: boost-convert:x64-windows
Building package boost-convert[core]:x64-windows...
-- Downloading https://github.com/boostorg/convert/archive/boost-1.70.0.tar.gz...
-- Extracting source E:/_dev/vcpkg/downloads/boostorg-convert-boost-1.70.0.tar.gz
-- Using source at E:/_dev/vcpkg/buildtrees/boost-convert/src/ost-1.70.0-3c76e05768
-- Packaging headers
-- Packaging headers done
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:79 (file):
  file RENAME failed to rename

    E:/_dev/vcpkg/downloads/temp

  to

    E:/_dev/vcpkg/downloads/temp0

  because: No such file or directory

Call Stack (most recent call first):
  installed/x64-windows/share/boost-vcpkg-helpers/boost-modular-headers.cmake:17 (vcpkg_download_distfile)
  ports/boost-convert/portfile.cmake:14 (boost_modular_headers)
  scripts/ports.cmake:85 (include)


Error: Building package boost-convert:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-convert:x64-windows
  Vcpkg version: 2019.08.16-nohash

Additionally, attach any relevant sections from the log files above.
```

**Comment by degski** [comment]
@kakyoism 

> Additionally, attach any relevant sections from the log files above.

The text seems to indicate quite clearly what to do.

> My vcpkg is the latest as of this write-up.

You did 'bootstrap', i.e. rebuild again?

**Comment by PhoebeHui** [comment]
@lbc3402785, I can't repro this issue with VS2015 update3, please get latest vcpkg and .execute bootstrap-vcpkg.bat, if the issue persist, please provide failure log 'build-x64-windows-dbg-out.log', you can find it under .\buildtrees\boost-regex.

**Comment by PhoebeHui** [comment]
@kakyoism, for the issue that you mentioned, please reference issue https://github.com/microsoft/vcpkg/issues/4245.

@lbc3402785, if this still be an problem for you, please attach failure log and reopen this issue.
