### ISSUE TITLE
libpng find_package broken

### ISSUE THREAD

**Issue by sjdrc** [microsoft/vcpkg#7968]
**Describe the bug**
When installing libpng and attempting to use through cmake, I get the error in the log section below.

Package installed correctly and I followed the instructions it gave:
```
The package libpng:x64-linux provides CMake targets:

    find_package(libpng CONFIG REQUIRED)
    target_link_libraries(main PRIVATE png_static)
```

**Environment**
- OS: Ubuntu 18.04
- Compiler: gcc 7.4.0/cmake 3.14.3

**To Reproduce**
1. ./vcpkg install libpng
2. In my project's CMakeLists.txt do `find_package(libpng CONFIG REQUIRED)`

**Expected behavior**
I should be able to find libpng with `find_package`

**Failure logs** 
```
CMake Error at /home/sebastien/.ezvcpkg/2019.07/scripts/buildsystems/vcpkg.cmake:266 (_find_package):
  Could not find a package configuration file provided by "libpng" with any
  of the following names:

    libpngConfig.cmake
    libpng-config.cmake

  Add the installation prefix of "libpng" to CMAKE_PREFIX_PATH or set
  "libpng_DIR" to a directory containing one of the above files.  If "libpng"
  provides a separate development package or SDK, be sure it has been
  installed.
```

**Additional context**
vcpkg folder `installed/x64-linux/share/libpng` contains the following files:
```
libpng16.cmake
libpng16-debug.cmake
libpng16-release.cmake
```

Renaming to:
```
libpngConfig.cmake
libpngConfig-debug.cmake
libpngConfig-release.cmake
```

lets cmake find the package as expected.

**Comment by vicroms** [comment]
Hi @sjdrc 

PR #7972 should fix this issue.

I will note, that the traditional way to include **libpng** is by using the built-in CMake module (call **`find_package(PNG REQUIRED)`** instead).

**Comment by sjdrc** [comment]
Ah right, if that is the case, should the `The package libpng:x64-linux provides CMake targets:` message recommend using `find_package(PNG REQUIRED)` instead?

**Comment by vicroms** [comment]
The message is auto-generated by **vcpkg** when config files are detected, in this case it can be overridden by providing a `usage` file.

However, once the PR is merged both `find_package(libpng CONFIG)` and `find_package(PNG MODULE)` will work.
