### ISSUE TITLE
[VTK] build of pcl:x64-windows

### ISSUE THREAD

**Issue by davidbun** [microsoft/vcpkg#7969]
**Host Environment**
- Windows 10 Pro x64
- Compiler: VS2017

**To Reproduce**
`./vcpkg install pcl:x64-windows`

**Failure logs** 
Building package vtk[core]:x64-windows...
-- Using cached C:/vcpkg/downloads/Kitware-VTK-v8.2.0.tar.gz
-- Using source at C:/vcpkg/buildtrees/vtk/src/v8.2.0-b37306c27c
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_fixup_cmake_targets.cmake:98 (message):
  'C:/vcpkg/packages/vtk_x64-windows/debug/share/vtk' does not exist.
Call Stack (most recent call first):
  ports/vtk/portfile.cmake:139 (vcpkg_fixup_cmake_targets)
  scripts/ports.cmake:85 (include)

Error: Building package vtk:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: vtk:x64-windows
  Vcpkg version: 2019.08.27-nohash

**Comment by cbezault** [comment]
See #7967

**Comment by davidbun** [comment]
Just to clarify that the issue is related to the VTK:

.\vcpkg install vtk:x64-windows

leads to the same error message

**Comment by cbezault** [comment]
If you could give the PR a shot to see if it fixes your issue that would be great!

**Comment by davidbun** [comment]
I am so sorry, dear cbezault, but it is my first time that I am using vcpkg to add the dependencies into the VS. Tried to take a look into #7967 but did not understood. Can you give light push what should I do to try to fix this issue? Appreciate your help in advance

**Comment by Neumann-A** [comment]
@davidbun you need to remove glew once and reinstall it. Otherwise the required wrapper fr glew is not going to be installed

**Comment by davidbun** [comment]
@Neumann-A - Thx, figured out that few minutes ago. Both updates from #7967 worked well for VTK. Now I am running the PCL and will let you know

**Comment by davidbun** [comment]
Finally, works including PCL
Thx a lot for your help

**Comment by PhoebeHui** [comment]
@davidbun, PR#7967 merged, VTK works well now, and looks no issue for PCL.
