### ISSUE TITLE
qca and qwt can not be installed! It seems than qmake can not be found!

### ISSUE THREAD

**Issue by cxq2003** [Microsoft/vcpkg#797]
C:\vcpkg>.\vcpkg install qwt
-- CURRENT_INSTALLED_DIR=C:/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/vcpkg/packages/qwt_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/vcpkg/buildtrees/qwt
-- CURRENT_PORT_DIR=C:/vcpkg/ports/qwt/.
-- Using cached C:/vcpkg/downloads/qwt-6.1.3.zip
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting source C:/vcpkg/downloads/qwt-6.1.3.zip
-- Extracting done
-- Applying patch C:/vcpkg/ports/qwt/build-shared-lib.patch
-- Applying patch C:/vcpkg/ports/qwt/build-shared-lib.patch done
CMake Error at scripts/cmake/vcpkg_configure_qmake.cmake:30 (BUILD_ERROR):
  Unknown CMake command "BUILD_ERROR".
Call Stack (most recent call first):
  ports/qwt/portfile.cmake:24 (vcpkg_configure_qmake)
  scripts/ports.cmake:73 (include)

Error: Building package qwt:x86-windows failed with: BUILD_FAILED
Please ensure sure you're using the latest portfiles with `.\vcpkg update`, then

submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qwt:x86-windows
  Vcpkg version: 0.0.76-0038dd86bc97df8f0c528d0b9235b9bfb9400e48

**Comment by ras0219-msft** [comment]
Thanks for reporting this. I believe I've fixed qwt with f17fd50 (qt5 package version 5.7.1-6).

Could you please rebuild qt5 with the latest portfiles and try qwt again?

**Comment by cxq2003** [comment]
qt5 and qwt works!
But qca failed!

Environment: Visual studio 2017 under windows 7 sp1 zh_cn 64bit

C:\vcpkg>vcpkg install qca
-- CURRENT_INSTALLED_DIR=C:/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/vcpkg/packages/qca_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/vcpkg/buildtrees/qca
-- CURRENT_PORT_DIR=C:/vcpkg/ports/qca/.
-- Cloning done
-- Adding worktree
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: C:/Git/cmd/git.exe;worktree;add;-f;--detach;C:/vcpkg/buildtr
ees/qca/src;19ec49f89a0a560590ec733c549b92e199792837
    Working Directory: C:/vcpkg/downloads/qca.git
    See logs for more information:
      C:\vcpkg\buildtrees\qca\worktree-out.log
      C:\vcpkg\buildtrees\qca\worktree-err.log

Call Stack (most recent call first):
  ports/qca/portfile.cmake:38 (vcpkg_execute_required_process)
  scripts/ports.cmake:73 (include)


Error: Building package qca:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qca:x86-windows
  Vcpkg version: 0.0.76-5f3597927266a0b40172ba73c583fb0da5d3404e
