### ISSUE TITLE
[New Port Request] <cppkafka>

### ISSUE THREAD

**Issue by zlinwei** [microsoft/vcpkg#7970]
Library name:  cppkafka

Library description: Modern C++ Apache Kafka client library (wrapper for librdkafka)

Source repository URL:https://github.com/mfontanini/cppkafka

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by NancyLi1013** [comment]
Hi @zlinwei, thanks for posting this request. This port has been added to vcpkg. Please try to update vcpkg and use it.

**Comment by zlinwei** [comment]
Thank you!
