### ISSUE TITLE
[<libgeotiff>] debug lib has wrong name

### ISSUE THREAD

**Issue by pwm1234** [microsoft/vcpkg#7971]
**Host Environment**
- OS: Windows
- Compiler: v141

**To Reproduce**
`./vcpkg install libgeotiff`

The debug library is named `installed\x64-windows\debug\lib\geotiff_d_i.lib` but the find_package logic (from the toolchain file?) does not include the `_d` postfix.

**Comment by Neumann-A** [comment]
If I remember correctly GeoTIFF exports targets. So if you would use the targets it will work correctly. 
If you have a dependency which ships its own FindGeoTIFF just delete that file.
Hmm have to make a PR for liblas to delete that file.

**Comment by pwm1234** [comment]
You are right. I am not sure what happened before, but I double-checked my current build and the right name is used for the debug geotiff library. Sorry for the false alarm. Thanks for your help!
