### ISSUE TITLE
[New Port Request] libbitcoin-system

### ISSUE THREAD

**Issue by xuing** [microsoft/vcpkg#7982]
Library name:
**libbitcoin-system**
Library description:
**Bitcoin Cross-Platform C++ Development Toolkit** 
Source repository URL:
https://github.com/libbitcoin/libbitcoin-system
Project homepage :
https://github.com/libbitcoin

Thanks！

and the Libbitcoin project also has other  libraries in homepage.

**Comment by Milerius** [comment]
It's will be really interesting @ras0219-msft but it's seems to be a bit hard no ?

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by j-bruel** [comment]
Can we re-open this issue?
