### ISSUE TITLE
Add libvpx

### ISSUE THREAD

**Issue by rossbrower** [Microsoft/vcpkg#799]
https://github.com/webmproject/libvpx

**Comment by rossbrower** [comment]
I started working on this here: https://github.com/rossbrower/vcpkg. It builds (at least for me) but doesn't yet put the outputs in the right place so it's definitely not ready for a PR.  I don't have a great deal of experience in this area so if someone wants to help push me in the right direction or take over this port it would be appreciated.

**Comment by Mixaill** [comment]
I'll probably submit libvpx and freerdp ports in next 12 hours.

**Comment by rossbrower** [comment]
Wow thanks! You are saving me many hours of frustration.

**Comment by Mixaill** [comment]
Try to use port from #806.
