### ISSUE TITLE
[New Port Request] frida

### ISSUE THREAD

**Issue by Pospelove** [microsoft/vcpkg#7993]
Library name: Frida

Library description: Dynamic instrumentation toolkit for developers, reverse-engineers, and security researchers.

Source repository URL: https://github.com/frida/frida

Project homepage: www.frida.re

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by aspfate** [comment]
Can we add this now?
