### ISSUE TITLE
[osg] build failure on x64-linux

### ISSUE THREAD

**Issue by ASxa86** [microsoft/vcpkg#7996]
**Host Environment**
- OS: Linux (RedHat 7.6)
- Compiler: GCC v8.2.1

**To Reproduce**
`./vcpkg install osg:x64-linux`

**Failure logs** 
-- Building x64-linux-dbg
-- Building x64-linux-rel
CMake Error at ports/osg/portfile.cmake:37 (file):
  file must be called with at least two arguments.
Call Stack (most recent call first):
  scripts/ports.cmake:74 (include)

Error: Building package osg:x64-linux failed with: BUILD_FAILED

**Additional context**
The problem lies within the osg/portfile.cmake:37. It attempts to call file(REMOVE_RECURSE ${OSG_TOOLS}) but ${OSG_TOOLS} is empty. This is because osg/portfile.cmake:35 attempts to call file(GLOB OSG_TOOLS ${CURRENT_PACKAGES_DIR}/bin/*.exe) but no *.exe files exist within buildtrees/osg/x64-linux-dbg/bin/ as this is a Linux system and not windows. My work around is to comment these scripts out as I currently don't need the osg tools. The actually solution should, at a minimum, perform a system check before making these copies. 

Something like if(NOT WIN32), etc...

Edit: A couple lines below it is also attempting to copy osg plugins as *.dll. As osg is currently failing on lines above, it has not yet hit the dll copy failures but I imagine this will cause the same issues.

**Comment by martin-s** [comment]
Or you can check if directory exists before. This wouldn't require to introduce platform dependent code.

**Comment by ASxa86** [comment]
This may be a separate issue but it appears that osgEarth suffers from the same issues as OSG. The portfile does not account for Linux systems. Additionally, osg and osgEarth portfiles are looking for the osgPlugins directory in the wrong location on Linux.

**Comment by martin-s** [comment]
I agree. Let's just focus on OSG. You can try that:
```
IF(OSG_TOOLS) {
# COPY...
# REMOVE_RECURSE
}
```
If you take the new available VCPKG_TARGET_EXECUTABLE_SUFFIX, you can make it even more generic on the glob approach.

**Comment by JackBoosY** [comment]
Hi @ASxa86, thanks for reporting this issue!
I've fixed it, please update vcpkg and rebuild osg.

Thanks.

**Comment by ASxa86** [comment]
Great! I'll give it a shot later this evening. Thank you.
