### ISSUE TITLE
Changing the location of Windows SDK

### ISSUE THREAD

**Issue by vahisht** [microsoft/vcpkg#7998]
Hi,

I'm currently dealing with this issue: https://github.com/Microsoft/vcpkg/issues/5866
I have the proper Windows SDK installed, but since my C HDD is rather small, VC installed these SDKs to a location on my D drive. Now the OpenGL installation cannot find the SDKs because it's looking for them at: 
C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\...
but they're not there, they are at:
D:\Windows Kits\10\Lib\10.0.17763.0\...

How can I tell vcpkg to look for SDKs on this other location? Thanks!

**Comment by PhoebeHui** [comment]
@vahisht, in VCPKG, it try to find windows sdk by environment variable '$env:ProgramFiles' and '${env:ProgramFiles(x86)}',  so you can check the 2 variables value, from your logs, it seems that point to 'C:\Program Files (x86)', try to workaround by override that value to windows sdk location manually in VCPKG, not sure if that works, 

I tried to install VS and SDKs to D drive by VS installer, however, it installed sdks to C:\Program Files (x86)\, so I haven't try that workaround yet. let me know if that works.

See
[bootstrap.ps1](https://github.com/microsoft/vcpkg/blob/8cd2d17460d7c8d1dc74491cd890691f9546dc8c/scripts/bootstrap.ps1#L254) and [vcpkg_get_windows_sdk.cmake](https://github.com/microsoft/vcpkg/blob/7d72108b9a09e92342ff695c074766fb068049df/scripts/cmake/vcpkg_get_windows_sdk.cmake)

**Comment by PhoebeHui** [comment]
@cbezault, do you have any good suggestion?

**Comment by vahisht** [comment]
@PhoebeHui Thanks for the tip! I already tried a different workaround as suggested by the user **cwbhhjl** in #5495 , which relies on a Windows directory junction placed in the C:\Program Files (x86)\Windows Kits\ that links to the correct folder on the other drive. This solution does work, even though it requires some magic with cmd (not powershell).

Specifically what you want to do is use the [mklink](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink) command with the /J parameter

**Comment by PhoebeHui** [comment]
@vahisht, mklink the correct folder looks more intelligent, great to hear that works! I will close this issue, and left #5495 open to track, let's see if we have a good solution to handle this in future.
