### ISSUE TITLE
port which requires an older dependency

### ISSUE THREAD

**Issue by theblackunknown** [microsoft/vcpkg#8008]
Hi there,

As I was looking to create a port for [NVIDIA/MDL-SDK](https://github.com/NVIDIA/MDL-SDK), I noticed that it requires a LLVM 3.4.1 however the current LLVM port target a 8.0.0 [(as of writing)](https://github.com/microsoft/vcpkg/commit/22bc820f5eb4057287f4af7d0e2974d0291dece4#diff-55ff26982131ee12d476cbced323a70b)

I know that [FAQ says](https://github.com/microsoft/vcpkg/blob/master/docs/about/faq.md#how-do-i-use-different-versions-of-a-library-on-one-machine) we should maintain our own vcpkg to have a library at an older version, but does this also applies to library dependencies as well ?

Otherwise it would mean we can only create port which build ok with the latest version available on vcpkg, isn't it ?

**Comment by Voskrese** [comment]
clang_PATH in Ungrouped Entries (only if not found in the PATH),
for example: C:/projects/thirdparty/LLVM-3.4.1-win32/bin/clang.exe

python_PATH in Ungrouped Entries (only of not found in the PATH),
for example: C:/projects/thirdparty/python_2_7_1/bin/python.exe

Qt5_DIR in Ungrouped Entries,
for example: C:/Qt/5.10.1/msvc2015_64


download and ...

cmake ... ninja ...

-DQt5_DIR=...path...
-Dclang_PATH=...

**Comment by theblackunknown** [comment]
Sounds like a good way to proceed, are you aware of any other port which does this ?

**Comment by Voskrese** [comment]
https://github.com/microsoft/vcpkg/search?q=vcpkg_download_distfile&unscoped_q=vcpkg_download_distfile

**Comment by PhoebeHui** [comment]
Thanks Voskrese for the comments! @theblackunknown, does this still be an problem for you?

**Comment by theblackunknown** [comment]
@PhoebeHui I have enough info to try to get my port up and running now
I need more time to spend on it to see if I can get a successful outcome
Thanks for the suggestion so far

**Comment by PhoebeHui** [comment]
Thanks, we would love to see your contributions!
