### ISSUE TITLE
Add freerdp

### ISSUE THREAD

**Issue by rossbrower** [Microsoft/vcpkg#801]
https://github.com/FreeRDP/FreeRDP

**Comment by rossbrower** [comment]
Can we do one for the 2.0 beta as well (https://github.com/FreeRDP/FreeRDP/releases/tag/2.0.0-beta1%2Bandroid11)? Or I presumably can extrapolate from the stable version to build the beta.

**Comment by Mixaill** [comment]
Please try #810
