### ISSUE TITLE
Vcpkg's manifest file?

### ISSUE THREAD

**Issue by xahon** [microsoft/vcpkg#8010]
I don't really understand how do I manage my projects. I expected that `vcpkg` can create a manifest file (Like `package.json` for node or `cargo.toml` for rust) that keeps track of packages and their versions and then I just need to make something like `vcpkg install` in the root of my project and `vcpkg` download, install and make other stuff for me. But it looks like I need push vcpkg's sources in each my projects' repos (Not as a submodule because it stores packages info somewhere inside it's directory). What do you advise me?

**Comment by cbezault** [comment]
Manifest files are in the cards but haven't been implemented yet. Right now cloning into each of your projects the the recommended workflow. The use case you are describing is high on our list of TODOs.

**Comment by xahon** [comment]
@cbezault I can't even rebuilt all my packages because there is no such install command. I've accidentaly compiled everything with `gcc` and now want to rebuild everything with `clang`.  So, as far as I understood I need to remove all my packages and install them again with proper environment variables for CC, CXX?

**Comment by traversaro** [comment]
Related PRs:
* https://github.com/microsoft/vcpkg/pull/11203
* https://github.com/microsoft/vcpkg/pull/11757

**Comment by xahon** [comment]
@linquize sorry, don't have free time to check. Close for now
