### ISSUE TITLE
[New Port Request] flatUI, SDL_GUI, rlottie

### ISSUE THREAD

**Issue by TerensTare** [microsoft/vcpkg#8011]
Library name:
flatUI, SDL_GUI, samsung/rlottie
Library description:
GUI libraries
Source repository URL:
https://github.com/google/flatui
https://github.com/mozeal/SDL_gui
https://github.com/Samsung/rlottie#previewing-lottie-json-files
Project homepage (if different from the source repository):
http://google.github.io/flatui/
Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
