### ISSUE TITLE
[New Port Request] Vector Class Library  (x86_x64 SIMD abstraction layer)

### ISSUE THREAD

**Issue by am-randomBit** [microsoft/vcpkg#8012]
Library name: **Vector Class Library**

Library description: **It's the most comprehensive  c++ abstraction layer for SIMD (SSE...AVX512) on x86_x64 .**  Written by Agner Fog , which means a lot.

Source repository URL:  https://github.com/vectorclass

It has 2 versions , version 2 requires c++17 support which is fair enough. v1 is legacy and unnecessary.
In same repository , it has an Add-on folder with extra functions for some common applications of vector processing  : vector3d, quaternion, decimal, complex and random.

**Comment by LilyWangL** [comment]
PR #7573

**Comment by NancyLi1013** [comment]
Hi @am-randomBit 
Thanks for posting this request.
Since this port has been added. please update vcpkg and try to use it. I'm closing this issue for now.
