### ISSUE TITLE
[New Port Request] Gazebo

### ISSUE THREAD

**Issue by Electric-Turtle** [microsoft/vcpkg#8014]
Library name: Gazebo

Library description: A physics and robot simulation framework. It is near ubiquitous in the world of robotics research.

Direct from their website:
"Robot simulation is an essential tool in every roboticist's toolbox. A well-designed simulator makes it possible to rapidly test algorithms, design robots, perform regression testing, and train AI system using realistic scenarios. Gazebo offers the ability to accurately and efficiently simulate populations of robots in complex indoor and outdoor environments. At your fingertips is a robust physics engine, high-quality graphics, and convenient programmatic and graphical interfaces. Best of all, Gazebo is free with a vibrant community."

Source repository URL: https://bitbucket.org/osrf/gazebo/src/default/

Project homepage (if different from the source repository): gazebosim.org

Anything else that is useful to know when adding (such as optional features the library may have that should be included):  Gazeo depends on some of the "ignition" libraries: https://ignitionrobotics.org/home. Ignition Math, Ignition Msgs, and Ignition Transport are required as dependencies (possibly others).

**Comment by traversaro** [comment]
Related PR: https://github.com/microsoft/vcpkg/pull/7781 .

**Comment by Voskrese** [comment]
**windows** ver
release ver ok, debug failed

some bugs found, there are more

`protoc.exe` error, debug failed
`doxygen` gen html error `'PERL_PATH' 'MSCGEN_PATH'` search failed

deps: RUBY - RONN - (ign-tools)
`gem install ronn` - deps msys\mingw ))

```
av\src\VideoEncoder.cc(21): fatal error C1083: Cannot open include file: 'sys/ioctl.h'
av\include\ignition/common/ffmpeg_inc.hh(36): fatal error C1083: Cannot open include file: 'libavcodec/avcodec.h'
LINK : fatal error LNK1181: cannot open input file 'swscale.lib'
```

msvc v141

ign-msgs4 - `protoc.exe` error, debug failed - release ok
ign-msgs3 - `protoc.exe` error, debug failed - release ok
ign-common3 - ok
ign-common2 - ok
ign-tools - ok
ign-cmake0 - ok
ign-cmake1 - ok
ign-cmake2 - ok
ign-cmake3 - ok
ign-math4 - ok
ign-math5 - ok
ign-math6 - ok

ign-transport6 - DEPS: ign-msgs3 - failed - release ok
ign-transport7 - DEPS: ign-msgs4 - failed - release ok

... )

**Comment by traversaro** [comment]
cc @seanyen

**Comment by Voskrese** [comment]
ign-transport6 - settings are not disabled, not working

```
HAVE_IFADDRS:BOOL=OFF 
BUILD_TESTING=OFF
```

in consequence of the error

NetUtils.cc

```
#ifdef HAVE_IFADDRS
# include <ifaddrs.h>
//# include <sys/ioctl.h>
#endif
```

this port on Windows is not possible in this form

libprotobuf error, debug failed - FindIgnProtobuf.cmake ( ign-cmake0 ) no debug version


`ign-msgs4` the file names overlap `ign-msgs3`

**Comment by Electric-Turtle** [comment]
Thanks for looking into this stuff and isolating some of the bugs. Although Gazebo was designed around platform-neutral dependencies, making it portable to Windows (in theory), it looks like the OSRF dev team didn't really put much effort into deploying on non-Linux platforms.  

I'll look into trying to fix some of these problems when I have time. :)

**Comment by Voskrese** [comment]
in the site is written under the assembly MSVC 2013\v120
apparently new compilers are not supported

**Comment by traversaro** [comment]
> in the site is written under the assembly MSVC 2013\v120
apparently new compilers are not supported

The website is unfortunately quite outdated, see https://bitbucket.org/osrf/gazebo_tutorials/issues/92/remove-or-update-windows-installation . Despite what is written on the website, Gazebo 10 is able to build in Visual Studio 2015 and 2017 mainly due to the amazing work of Microsoft (in particular @seanyen), see https://bitbucket.org/osrf/gazebo/issues/2129/visual-studio-2015-compatibility and https://bitbucket.org/osrf/gazebo/pull-requests/3060/windows-patches-to-build-gazebo9/diff . 

I had a few ports of Gazebo-related libraries working in vcpkg in https://github.com/traversaro/vcpkg/tree/superinstaller, see https://github.com/j-rivero/vcpkg_ignition/issues/2#issuecomment-481096571, that have at least partial fix for problems related by @Voskrese . For example, some protobuf-related errors in ign-msgs1 are due to the fact that that package compiles and uses its own protobuf message generator, and so the protobuf `dll` needs to be correctly found. 

If you are interested in getting Gazebo 10 in vcpkg, a first step I recently worked on is the PR https://github.com/microsoft/vcpkg/pull/7781 that contains the dependencies `ign-cmake0` and `ign-math4`, and uncovered some issues on `arm` triplets. As soon as that PR is merged I will be happy to work in adding more ignition libraries to vcpkg, so a review for that PR would be highly welcome!

**Comment by Voskrese** [comment]
`ign-msgs3` or `ign-transport6` DEPS: LIB Protobuf `FindIgnProtobuf.cmake ( ign-cmake0 )`
no DLL

in general, you need to watch patches on the hitlab https://bitbucket.org/ignitionrobotics

**Comment by traversaro** [comment]
The PR  has been merged. Based on http://gazebosim.org/tutorials?tut=install_dependencies_from_source&cat=install, the other ignition dependencies that are needed for Gazebo 10 are: 
* [ ] ignition-common1
* [ ] ignition-fuel-tools1
* [ ] ignition-msgs1
* [ ] ignition-transport4
* [ ] sdformat6

I think I will personally work at the moment on `ignition-transport4` and ` ignition-msgs1`, but if anyone wants to work on other ports he will be welcome!

**Comment by traversaro** [comment]
As discussed in https://github.com/microsoft/vcpkg/pull/8178#issuecomment-575038212 , developing the gazebo10 port resulted in a lot of patch that are part of gazebo11, so it make sense to directly develop a port containing gazebo11.  I do not plan do to this in the immediate future, but I would be glad to help anyone that wants to work on this.

**Comment by traversaro** [comment]
With the merge of https://bitbucket.org/osrf/gazebo/pull-requests/3130 all the patches developed in https://github.com/microsoft/vcpkg/pull/8178#issuecomment-575038212 to smoothly add a vcpkg port of Gazebo have  been merged upstream, so gazebo11 should be packagable  in vcpkg without any additional patch.

**Comment by Electric-Turtle** [comment]
> developing the gazebo10 port resulted in a lot of patch that are part of gazebo11, so it make sense to directly develop a port containing gazebo11

I agree with this approach, especially considering Gazebo11 is an LTS release and Gazebo10 is not.


> so gazebo11 should be packagable in vcpkg without any additional patch.

This may not be the case.  Gazebo11 depends on different versions of the various ignition-* libraries and a different version of sdformat.  The way vcpkg has those libraries packaged now, the version numbers are _part of_ the library name itself.  E.g. vcpkg has sdformat6 available, but _not_ sdformat8 (which is what Gazebo11 requires).  The same is true of some of the other dependencies of Gazebo11 and their recursive subdependencies.

However, I was able to build all of Gazebo11's dependencies from source on Windows 10 without too much headache. It stands to reason taking the extra step of building vcpkg portfiles for them won't be so bad either.

**Comment by traversaro** [comment]
> > so gazebo11 should be packagable in vcpkg without any additional patch.
> 
> This may not be the case. Gazebo11 depends on different versions of the various ignition-* libraries and a different version of sdformat. The way vcpkg has those libraries packaged now, the version numbers are _part of_ the library name itself. E.g. vcpkg has sdformat6 available, but _not_ sdformat8 (which is what Gazebo11 requires). The same is true of some of the other dependencies of Gazebo11 and their recursive subdependencies.

Sorry, I probably was not clear, I meant that the Gazebo 11 port did not need any local patch to add via `vcpkg_apply_patches`. It will also require to add ports for all the required ignition libraries, but as most of the ignition library permit to install side-by-side different major versions, and  thanks to the [`ignition_modular_library`](https://github.com/microsoft/vcpkg/blob/2019.12/ports/ignition-modularscripts/ignition_modular_library.cmake#L38) CMake macro, that should not be a bit problem either.

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
