### ISSUE TITLE
Gtk can't load svg files

### ISSUE THREAD

**Issue by cosarara** [microsoft/vcpkg#8015]
**Describe the bug**
When gtk and librsvg are installed, gtk should be able to load svg pictures, but it can't. This is similar to the following bug in MINGW: https://github.com/msys2/MINGW-packages/issues/818

**Environment**
- OS: Windows 10 x64 1903
- Compiler: Visual C++ 2019   00435-60000-00000-AA464

**To Reproduce**
1. ./vcpkg install gtk:x64-windows
2. ./vcpkg install librsvg:x64-windows
3. ./vcpkg integrate install
4. Create a new project in visual studio with the following code:

```C++
#include <stdio.h>
#include <stdlib.h>
#include <gtk/gtk.h>

static void
activate(GtkApplication* app,
	gpointer        user_data)
{
	GtkWidget* window;
	GdkPixbuf* pixbuf;
	GtkWidget* image;
	GError* err = NULL;

	window = gtk_application_window_new(app);
	gtk_window_set_title(GTK_WINDOW(window), "Window");
	gtk_window_set_default_size(GTK_WINDOW(window), 200, 200);

	pixbuf = gdk_pixbuf_new_from_file("test.svg", &err);
	if (!pixbuf) {
		fprintf(stderr, "Unable to load pixbuf: %s\n", err->message);
		exit(1);
	}
	image = gtk_image_new_from_pixbuf(pixbuf);

	gtk_container_add(GTK_CONTAINER(window), image);

	gtk_widget_show_all(window);
}

int
main(int    argc,
	char** argv)
{
	GtkApplication* app;
	int status;

	app = gtk_application_new("org.gtk.example", G_APPLICATION_FLAGS_NONE);
	g_signal_connect(app, "activate", G_CALLBACK(activate), NULL);
	status = g_application_run(G_APPLICATION(app), argc, argv);
	g_object_unref(app);

	return status;
}
```
5. Add any svg file to the project directory with the name `test.svg`, for instance https://upload.wikimedia.org/wikipedia/commons/0/02/SVG_logo.svg
6. Run the program in VS
7. See the error in the console:
> Unable to load pixbuf: Couldn't recognize the image file format for file 'test.svg'

**Expected behavior**
A window should open displaying the svg file. That's what the code does when gtk is properly configured to support svg (for instance, on any linux distro).

**Additional context**
It seems gdk-pixbuf can't find `pixbufloader-svg.dll` and friends. On linux distros the `gdk-pixbuf2` package usually includes a program named `gdk-pixbuf-query-loaders` that could help, but it seems it is not built here.

**Comment by AlvinZhangH** [comment]
Yes, test.svg can not be  display in a window, but Untitled.png can display:
 
pixbuf = gdk_pixbuf_new_from_file("F:/8015/test/Project2/x64/Debug/Untitled.png", &err);

**Comment by cosarara** [comment]
So is this closed Wontfix? Because this is not a question, Gtk works with SVG on all platforms if built to support it.

**Comment by cosarara** [comment]
I insist: this is a bug, not a question. Gtk should be able to load SVG files when librsvg is installed.

**Comment by Febbe** [comment]
> 

I second this.

**Comment by dg0yt** [comment]
> > I insist: this is a bug, not a question. Gtk should be able to load SVG files when librsvg is installed.
> 
> I second this.

It is not a bug. To enable SVG support, gtk would need to be instructed to build with SVG support and corresponding dependencies. Installing librsvg is not enough.

**Comment by dg0yt** [comment]
So `librsvg` is a plugin-style addition... 
Maybe another port to be reverted back to it official build system.
