### ISSUE TITLE
[New Port Request] libigl

### ISSUE THREAD

**Issue by sirvelo** [microsoft/vcpkg#8016]
Library name: libigl

Library description: libigl is a simple C++ geometry processing library.

Source repository URL:  https://github.com/libigl/libigl/

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

Windows shared libraries are required.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Closed as duplicate of #2601. Please pay attention to the progress of issue #2601.
