### ISSUE TITLE
[New Port Request] SLikeNet

### ISSUE THREAD

**Issue by Pospelove** [microsoft/vcpkg#8019]
Library name: SLikeNet

Library description: SLikeNet™ is an Open Source/Free Software cross-platform network engine written in C++ and specifially designed for games (and applications which have comparable requirements on a network engine like games) building upon the discontinued RakNet network engine which had more than 13 years of active development. 

Source repository URL: https://github.com/SLikeSoft/SLikeNet

Project homepage: https://www.slikenet.com/

**Comment by JackBoosY** [comment]
Hi @Pospelove, thanks for reporting this issue.
This port has been added in vcpkg, please update vcpkg and try to install it.

Thanks.
