### ISSUE TITLE
[New Port Request] <librem>

### ISSUE THREAD

**Issue by movetothesky** [microsoft/vcpkg#8027]
Library name: librem

Library description: http://www.creytiv.com/rem.html

Source repository URL: http://www.creytiv.com/rem.html

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
