### ISSUE TITLE
[New Port Request] libopenvizsla

### ISSUE THREAD

**Issue by desowin** [microsoft/vcpkg#8033]
Library name: libopenvizsla

Library description: An attempt to reimplement OpenVizsla host software in plain C.

Source repository URL: https://github.com/matwey/libopenvizsla

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included): It would be good to build not only the library, but also the tools using the library. Currently tools contains two utilities: load and sample.

**Comment by desowin** [comment]
OpenVizsla is a Open Hardware FPGA-based USB analyzer. Unlike other similar devices on the market, hardware design files are available as well as full source code for the firmware and client software of the device.

**Comment by PhoebeHui** [comment]
@desowin, I noticed you draft libopenvizsla in your repository https://github.com/desowin/vcpkg/blob/libopenvizsla/ports/libopenvizsla/portfile.cmake, welcome to create a PR in VCPKG!

**Comment by desowin** [comment]
@PhoebeHui It doesn't really work and I have no idea how to proceed it further. Is it appropriate/recommended to open PRs to vcpkg in such case?

**Comment by PhoebeHui** [comment]
@desowin, what's issue blocked you? if it's related to VCPKG or cmake configuration, then we could help to take a look. If it failed due to the source itself issue, then should ask the libopenvizsla maintainer to fix the source issue firstly, we may postpone supporting it in VCPKG.

**Comment by desowin** [comment]
@PhoebeHui The issue is related to cmake configuration. I have fixed libopenvizsla source code to be compatible with Visual Studio and it is now merged upstream. To get it compiling with Visual Studio, I generated VS solution with cmake and manually altered the solution to contain proper include paths and libraries.

**Comment by PhoebeHui** [comment]
@desowin, I tried to build libopenvizsla on windows, after modified the CMakeList.txt, it configured successfully,  however it build failed:
```
F:\VCPKG\src\buildtrees\libopenvizsla\src\763aee1167-c55aae46e9\tools\ovextcap\main.c(9): fatal error C1083: Cannot open include file: 'getopt.h': No such file or directory
```
```
F:\VCPKG\src\buildtrees\libopenvizsla\src\763aee1167-c55aae46e9\src\ov.c(110): error C2375: 'ov_new': redefinition; different linkage
F:\VCPKG\src\buildtrees\libopenvizsla\src\763aee1167-c55aae46e9\include\ov.h(53): note: see declaration of 'ov_new'
F:\VCPKG\src\buildtrees\libopenvizsla\src\763aee1167-c55aae46e9\src\ov.c(153): error C2375: 'ov_open': redefinition; different linkage
F:\VCPKG\src\buildtrees\libopenvizsla\src\763aee1167-c55aae46e9\include\ov.h(54): note: see declaration of 'ov_open'
F:\VCPKG\src\buildtrees\libopenvizsla\src\763aee1167-c55aae46e9\src\ov.c(204): error C2375: 'ov_free': redefinition; different linkage
F:\VCPKG\src\buildtrees\libopenvizsla\src\763aee1167-c55aae46e9\include\ov.h(55): note: see declaration of 'ov_free'
F:\VCPKG\src\buildtrees\libopenvizsla\src\763aee1167-c55aae46e9\src\ov.c(212): error C2375: 'ov_get_usb_speed': redefinition; different linkage
F:\VCPKG\src\buildtrees\libopenvizsla\src\763aee1167-c55aae46e9\include\ov.h(57): note: see declaration of 'ov_get_usb_speed'
...
```

I didn't find the header getopt.h in libopenvizsla, and the error looks source issue.  I can share the CMakeList.txt file if you want to do further investigation, or I will take a look at  this issue later.

**Comment by desowin** [comment]
@PhoebeHui the `getopt.h` is supposed to be a system library. It is part of system libraries on Linux, while on Windows, vcpkg provides it in `ports/getopt-win32` package.

The VS solution I used is so horrible hack that it does not seem wise to merge it. The proper solution is to update/patch CMakeList.txt to properly work with vcpkg.

**Comment by NancyLi1013** [comment]
Hi @desowin 
Would you like to make a pull request for `libopenvizsla`?

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
