### ISSUE TITLE
[evpp] build failure

### ISSUE THREAD

**Issue by how0723** [microsoft/vcpkg#8037]
**Host Environment**
- OS: [Linux]
- Compiler: 7.4

**To Reproduce**
`./vcpkg install evpp`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: /home/yehao/workspace/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v
    Working Directory: /home/yehao/workspace/vcpkg/buildtrees/evpp/x64-linux-dbg
    See logs for more information:
      /home/yehao/workspace/vcpkg/buildtrees/evpp/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/evpp/portfile.cmake:37 (vcpkg_install_cmake)
  scripts/ports.cmake:85 (include)

Error: Building package evpp:x64-linux failed with: BUILD_FAILED

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JackBoosY** [comment]
confirmed. Missing glog include path.

**Comment by how0723** [comment]
@JackBoosY thanks

**Comment by how0723** [comment]
can fix?

**Comment by JackBoosY** [comment]
Fixing in #8050.

**Comment by JackBoosY** [comment]
@how0723 Thanks for reporting this issue.
I've fixed this issue. Please update vcpkg and rebuild evpp.

Thanks.
