### ISSUE TITLE
Antlr4 Link error under visual studio 2017

### ISSUE THREAD

**Issue by cxq2003** [Microsoft/vcpkg#804]
-- CURRENT_INSTALLED_DIR=C:/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/vcpkg/packages/antlr4_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/vcpkg/buildtrees/antlr4
-- CURRENT_PORT_DIR=C:/vcpkg/ports/antlr4/.
-- Downloading http://www.antlr.org/download/antlr4-cpp-runtime-4.6-source.zip..
.
-- Downloading http://www.antlr.org/download/antlr4-cpp-runtime-4.6-source.zip..
. OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Downloading https://raw.githubusercontent.com/antlr/antlr4/4.6/LICENSE.txt...

-- Downloading https://raw.githubusercontent.com/antlr/antlr4/4.6/LICENSE.txt...
 OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting source C:/vcpkg/downloads/antlr4-cpp-runtime-4.6-source.zip
-- Extracting done
-- Applying patch C:/vcpkg/ports/antlr4/crt_mt.patch
-- Applying patch C:/vcpkg/ports/antlr4/crt_mt.patch done
-- Building C:/vcpkg/buildtrees/antlr4/src/runtime/antlr4cpp-vs2015.vcxproj for
Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: msbuild;C:/vcpkg/buildtrees/antlr4/src/runtime/antlr4cpp-vs2
015.vcxproj;/p:Configuration=Release DLL;/t:Rebuild;/p:Platform=x86;/p:PlatformT
oolset=v141;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No;/p:WindowsTarget
PlatformVersion=10.0.14393.0;/m
    Working Directory: C:/vcpkg/buildtrees/antlr4/x86-windows-rel
    See logs for more information:
      C:\vcpkg\buildtrees\antlr4\build-x86-windows-rel-out.log
      C:\vcpkg\buildtrees\antlr4\build-x86-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:79 (vcpkg_execute_required_process)
  ports/antlr4/portfile.cmake:32 (vcpkg_build_msbuild)
  scripts/ports.cmake:73 (include)

Error: Building package antlr4:x86-windows failed with: BUILD_FAILED
Please ensure sure you're using the latest portfiles with `.\vcpkg update`, then

submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: antlr4:x86-windows
  Vcpkg version: 0.0.76-0038dd86bc97df8f0c528d0b9235b9bfb9400e48
------------------------------------------------------
The Link error is:
ANTLRFileStream.obj : error LNK2001: unresolved extern symbo "__declspec(dllimport) public: static class std::locale::id std::codecvt<char32_t,char,struct _Mbstatet>::id" (__imp_?id@?$codecvt@_UDU_Mbstatet@@@std@@2V0locale@2@A) [C:\vcpkg\buildtrees\antlr4\src\runtime\antlr4cpp-vs2015.vcxproj]

**Comment by alexkaratarakis** [comment]
Please let me know if you can build `antlr4` successfully now.

**Comment by cxq2003** [comment]
antlr4 builds ok1
