### ISSUE TITLE
[abseil] build failure

### ISSUE THREAD

**Issue by surebrec** [microsoft/vcpkg#8040]
**Host Environment**
- OS: Windows 10
- Package: abseil:x64-windows
- Vcpkg version: 2019.08.27-nohash

**To Reproduce**
`vcpkg install abseil boost-filesystem boost-program-options boost-serialization ceres eigen3 flann gsl-lite gtest --triplet x64-windows`

**Failure logs** 
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: c:/vcpkg/buildtrees/abseil/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      c:\vcpkg\buildtrees\abseil\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:296 (vcpkg_execute_required_process)
  ports/abseil/portfile.cmake:20 (vcpkg_configure_cmake)
  scripts/ports.cmake:85 (include)

Error: Building package abseil:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: abseil:x64-windows
  Vcpkg version: 2019.08.27-nohash

**Additional**
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
Please install the English language pack.

**Comment by PhoebeHui** [comment]
@surebrec, from your log, looks you doesn't install English language pack. VCPKG requires English  language pack, see [doc](https://github.com/microsoft/vcpkg/blob/3dda86bd2785933485225202a710cde22c3b1ae1/CHANGELOG.md#vcpkg-00100), please install it and try again. 

I tried to install abseil with latest vcpkg version, everything build successfully for me.

**Comment by surebrec** [comment]
english lang pack solves the problem. thank you! I ignored the message about the English language pack, as it was just a "warning")
