### ISSUE TITLE
[RelWithDebInfo]debug build link to release glslang lib

### ISSUE THREAD

**Issue by harokyang** [microsoft/vcpkg#8041]
Platform is x64-windows

When build my project with debug configuration, I got link error like
`LNK2038 mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in xxxx.cpp.obj   glslang.lib(xxxxxxx.cpp.obj)`

After checking the commandline for linkage, I found out that glslang was pointed to the release version, instead of the one under debug folder
Later I found that there is no glslangConfig-debug.cmake undervcpkg\installed\x64-windows\share\glslang
Only release configuration existed inside glslangConfig.cmake

**Comment by JackBoosY** [comment]
@harokyang Thanks for reporting this issue.
I've fixed this issue, please update vcpkg and rebuild glslang.

Thanks.

**Comment by harokyang** [comment]
Now I got the oppsite error
It try to link debug version with a release build

**Comment by harokyang** [comment]
Interesting
If I use cmake commandline to build the project, it works
But if I use cmake integration with Visual Studio 2019, it failed

**Comment by harokyang** [comment]
Tested with more detail

If set configuration to Debug, project will be built as debug and linked with debug libs
If set to Release, project will be built as release and linked with release libs
If set to RelWithDebInfo, project will be built as release but linked with debug libs(Failed with glslang)

Also if build with VS 2019 which use ninja generator with cmake
neither Release or RelWithDebInfo will success(All linked with debug libs)

This is the command line copied from Output window of VS 2019 when generate cmake cache
`Command line: "cmd.exe" /c ""C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="D:\git\pulsar\out\install\x64-Release" -DCMAKE_BUILD_TYPE:STRING="Release" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.22.27905/bin/HostX64/x64/cl.exe" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.22.27905/bin/HostX64/x64/cl.exe"  -DCMAKE_TOOLCHAIN_FILE="D:/git/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE="RelWithDebInfo" -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "D:\git\pulsar" 2>&1"`

running it in console, then build with cmake manually got the exactly same link failure

**Comment by harokyang** [comment]
Here is the content of my Findglslang.cmake
to find glslang(both Release and Debug libs) at vcpkg installed folder

`include(FindPackageHandleStandardArgs)
include(SelectLibraryConfigurations)

set(GLSLANG_PATH "${XRAY_3RDPARTY_DIR}/glslang")

# Serach the 3rdparty directory first
find_library(GLSLANG_LIBRARY_RELEASE NAMES glslang PATH_SUFFIXES lib HINTS ${GLSLANG_PATH} NO_DEFAULT_PATH)
if(GLSLANG_LIBRARY_RELEASE)
    find_library(GLSLANG_LIBRARY_RELEASE NAMES glslang PATH_SUFFIXES lib HINTS ${GLSLANG_PATH} NO_DEFAULT_PATH)
    find_library(OGLCOMPILER_LIBRARY_RELEASE NAMES OGLCompiler PATH_SUFFIXES lib HINTS ${GLSLANG_PATH} NO_DEFAULT_PATH)
    find_library(OSDEPENDENT_LIBRARY_RELEASE NAMES OSDependent PATH_SUFFIXES lib HINTS ${GLSLANG_PATH} NO_DEFAULT_PATH)
    find_library(HLSL_LIBRARY_RELEASE NAMES HLSL PATH_SUFFIXES lib HINTS ${GLSLANG_PATH} NO_DEFAULT_PATH)
    find_library(SPIRV_LIBRARY_RELEASE NAMES SPIRV PATH_SUFFIXES lib HINTS ${GLSLANG_PATH} NO_DEFAULT_PATH)
    find_library(GLSLANG_LIBRARY_DEBUG NAMES glslangd PATH_SUFFIXES DEBUG/lib HINTS ${GLSLANG_PATH} NO_DEFAULT_PATH)
    find_library(OGLCOMPILER_LIBRARY_DEBUG NAMES OGLCompilerd PATH_SUFFIXES DEBUG/lib HINTS ${GLSLANG_PATH} NO_DEFAULT_PATH)
    find_library(OSDEPENDENT_LIBRARY_DEBUG NAMES OSDependentd PATH_SUFFIXES DEBUG/lib HINTS ${GLSLANG_PATH} NO_DEFAULT_PATH)
    find_library(SPIRV_LIBRARY_DEBUG NAMES SPIRVd PATH_SUFFIXES DEBUG/lib HINTS ${GLSLANG_PATH} NO_DEFAULT_PATH)
    find_library(HLSL_LIBRARY_DEBUG NAMES HLSLd PATH_SUFFIXES DEBUG/lib HINTS ${GLSLANG_PATH} NO_DEFAULT_PATH)
    find_path(GLSLANG_INCLUDE_DIR NAMES glslang/Public/ShaderLang.h PATH_SUFFIXES include HINTS ${GLSLANG_PATH} NO_DEFAULT_PATH)
    find_path(SPIRV_INCLUDE_DIR NAMES SPIRV/spirv.hpp PATH_SUFFIXES include HINTS ${GLSLANG_PATH} NO_DEFAULT_PATH)
    find_program(GLSLANG_VALIDATOR_EXE NAMES glslangValidator PATH_SUFFIXES bin HINTS ${GLSLANG_PATH} NO_DEFAULT_PATH)
else()
    # Then search default locations
    find_library(GLSLANG_LIBRARY_RELEASE NAMES glslang PATH_SUFFIXES lib)
    find_library(OGLCOMPILER_LIBRARY_RELEASE NAMES OGLCompiler PATH_SUFFIXES lib)
    find_library(OSDEPENDENT_LIBRARY_RELEASE NAMES OSDependent PATH_SUFFIXES lib)
    find_library(HLSL_LIBRARY_RELEASE NAMES HLSL PATH_SUFFIXES lib)
    find_library(SPIRV_LIBRARY_RELEASE NAMES SPIRV PATH_SUFFIXES lib)
    find_library(GLSLANG_LIBRARY_DEBUG NAMES glslangd PATH_SUFFIXES DEBUG/lib)
    find_library(OGLCOMPILER_LIBRARY_DEBUG NAMES OGLCompilerd PATH_SUFFIXES DEBUG/lib)
    find_library(OSDEPENDENT_LIBRARY_DEBUG NAMES OSDependentd PATH_SUFFIXES DEBUG/lib)
    find_library(SPIRV_LIBRARY_DEBUG NAMES SPIRVd PATH_SUFFIXES DEBUG/lib)
    find_library(HLSL_LIBRARY_DEBUG NAMES HLSLd PATH_SUFFIXES DEBUG/lib)
    find_path(GLSLANG_INCLUDE_DIR NAMES glslang/Public/ShaderLang.h PATH_SUFFIXES include)
    find_path(SPIRV_INCLUDE_DIR NAMES SPIRV/spirv.hpp PATH_SUFFIXES include)
    find_program(GLSLANG_VALIDATOR_EXE NAMES glslangValidator PATH_SUFFIXES bin)
endif()

select_library_configurations(GLSLANG)
select_library_configurations(OGLCOMPILER)
select_library_configurations(OSDEPENDENT)
select_library_configurations(SPIRV)
select_library_configurations(HLSL)

find_package_handle_standard_args(glslang
    DEFAULT_MSG
    GLSLANG_LIBRARY
    OGLCOMPILER_LIBRARY
    OSDEPENDENT_LIBRARY
    SPIRV_LIBRARY
    HLSL_LIBRARY
    GLSLANG_INCLUDE_DIR
    SPIRV_INCLUDE_DIR
)

add_library(glslang::OGLCompiler STATIC IMPORTED)
if(OGLCOMPILER_LIBRARY_RELEASE)
    set_property(TARGET glslang::OGLCompiler APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
    set_target_properties(glslang::OGLCompiler PROPERTIES
        IMPORTED_LOCATION_RELEASE ${OGLCOMPILER_LIBRARY_RELEASE})
endif()
if(OGLCOMPILER_LIBRARY_DEBUG)
    set_property(TARGET glslang::OGLCompiler APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
    set_target_properties(glslang::OGLCompiler PROPERTIES
        IMPORTED_LOCATION_DEBUG ${OGLCOMPILER_LIBRARY_DEBUG})
endif()

add_library(glslang::OSDependent STATIC IMPORTED)
if(OSDEPENDENT_LIBRARY_RELEASE)
    set_property(TARGET glslang::OSDependent APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
    set_target_properties(glslang::OSDependent PROPERTIES
        IMPORTED_LOCATION_RELEASE ${OSDEPENDENT_LIBRARY_RELEASE})
endif()
if(OSDEPENDENT_LIBRARY_DEBUG)
    set_property(TARGET glslang::OSDependent APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
    set_target_properties(glslang::OSDependent PROPERTIES
        IMPORTED_LOCATION_DEBUG ${OSDEPENDENT_LIBRARY_DEBUG})
endif()

add_library(glslang::HLSL STATIC IMPORTED)
if(HLSL_LIBRARY_RELEASE)
    set_property(TARGET glslang::HLSL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
    set_target_properties(glslang::HLSL PROPERTIES
        IMPORTED_LOCATION_RELEASE ${HLSL_LIBRARY_RELEASE})
endif()
if(HLSL_LIBRARY_DEBUG)
    set_property(TARGET glslang::HLSL APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
    set_target_properties(glslang::HLSL PROPERTIES
        IMPORTED_LOCATION_DEBUG ${HLSL_LIBRARY_DEBUG})
endif()

add_library(glslang::glslang STATIC IMPORTED)
if(GLSLANG_LIBRARY_RELEASE)
    set_property(TARGET glslang::glslang APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
    set_target_properties(glslang::glslang PROPERTIES
        IMPORTED_LOCATION_RELEASE ${GLSLANG_LIBRARY_RELEASE})
endif()
if(GLSLANG_LIBRARY_DEBUG)
    set_property(TARGET glslang::glslang APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
    set_target_properties(glslang::glslang PROPERTIES
        IMPORTED_LOCATION_DEBUG ${GLSLANG_LIBRARY_DEBUG})
endif()
set_target_properties(glslang::glslang PROPERTIES INTERFACE_INCLUDE_DIRECTORIES ${GLSLANG_INCLUDE_DIR})
target_link_libraries(glslang::glslang INTERFACE glslang::OGLCompiler glslang::OSDependent glslang::HLSL)

add_library(glslang::SPIRV STATIC IMPORTED)
if(SPIRV_LIBRARY_RELEASE)
    set_property(TARGET glslang::SPIRV APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
    set_target_properties(glslang::SPIRV PROPERTIES
        IMPORTED_LOCATION_RELEASE ${SPIRV_LIBRARY_RELEASE})
endif()
if(SPIRV_LIBRARY_DEBUG)
    set_property(TARGET glslang::SPIRV APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
    set_target_properties(glslang::SPIRV PROPERTIES
        IMPORTED_LOCATION_DEBUG ${SPIRV_LIBRARY_DEBUG})
endif()
set_target_properties(glslang::SPIRV PROPERTIES INTERFACE_INCLUDE_DIRECTORIES ${SPIRV_INCLUDE_DIR})
target_link_libraries(glslang::SPIRV INTERFACE glslang::glslang)

find_package_handle_standard_args(glslangValidator
    "Cannot find glslangValidator, Shader won't be compiled offline"
    GLSLANG_VALIDATOR_EXE
)

add_executable(glslangValidator IMPORTED)
set_target_properties(glslangValidator PROPERTIES IMPORTED_LOCATION ${GLSLANG_VALIDATOR_EXE})

mark_as_advanced(
    GLSLANG_LIBRARY
    OGLCOMPILER_LIBRARY
    OSDEPENDENT_LIBRARY
    HLSL_LIBRARY
    SPIRV_LIBRARY
)
`
I can't tell much difference between my module and the configs come with vcpkg
But the module does work with both cmake command line and VS 2019 cmake+ninja
while the configs failed with VS 2019

**Comment by JackBoosY** [comment]
@harokyang It seems that the debug library path in `find_library` should be `PATH_SUFFIXES debug/lib`.
And I cannot repro this on Visual Studio 2019. Here is my CMakeLists.txt:
```
# CMakeList.txt : CMake project for CMakeProject1, include source and define
# project specific logic here.
#
cmake_minimum_required (VERSION 3.8)

# Add source to this project's executable.
add_executable (CMakeProject1 "CMakeProject1.cpp" "CMakeProject1.h")

# TODO: Add tests and install targets if needed.
find_package(glslang CONFIG REQUIRED)
message("glslang: ${glslang_FOUND}")
target_link_libraries(CMakeProject1 PRIVATE glslang::HLSL glslang::SPIRV glslang::glslang glslang::OGLCompiler)
```

For msvc project, I don't know how to use this port, can you provide me some test code?

Thanks.

**Comment by harokyang** [comment]
Here is a simple [test](https://github.com/harokyang/glslang_test.git) project
I included my Findglslang.cmake module
Remember to switch to x64-Release configuration

Also I found that this glslang-config.cmake didn't handle include search path, you have to target to vcpkg include path exclusively

**Comment by LilyWangL** [comment]
I configure project successfully on Visual Studio 2019 with your [test](https://github.com/harokyang/glslang_test) project. This is my log:
```
2> CMake generation started for configuration: 'x64-Release'.
2> Command line: "cmd.exe" /c ""C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\Desktop\glslang_test-42a3fae6b549b8850b3b40b6bcc401099ae768cb\glslang_test-42a3fae6b549b8850b3b40b6bcc401099ae768cb\out\install\x64-Release" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.22.27905/bin/HostX64/x64/cl.exe" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.22.27905/bin/HostX64/x64/cl.exe"  -DCMAKE_TOOLCHAIN_FILE="F:/0912/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE="RelWithDebInfo" -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "C:\Users\Desktop\glslang_test-42a3fae6b549b8850b3b40b6bcc401099ae768cb\glslang_test-42a3fae6b549b8850b3b40b6bcc401099ae768cb" 2>&1"
2> Working directory: C:\Users\Desktop\glslang_test-42a3fae6b549b8850b3b40b6bcc401099ae768cb\glslang_test-42a3fae6b549b8850b3b40b6bcc401099ae768cb\out\build\x64-Release
2> [CMake] glslang: TRUE
2> [CMake] -- Configuring done
2> [CMake] -- Generating done
2> [CMake] -- Build files have been written to: C:/Users/Desktop/glslang_test-42a3fae6b549b8850b3b40b6bcc401099ae768cb/glslang_test-42a3fae6b549b8850b3b40b6bcc401099ae768cb/out/build/x64-Release
2> [CMake] 
2> Extracted includes paths.
2> Extracted CMake variables.
2> Extracted source files and headers.
2> Extracted code model.
2> CMake generation finished.
```
Please check this steps before creating cmake project:

1. Run this command `.\vcpkg.exe integrate install` on vcpkg before creating cmake project. You need restart Visual Studio 2019 after running this command.
2. You need add right cmakeToolchain path when you set up your **CMakeSettings.json**, like this:
`"cmakeToolchain": "F:/0912/vcpkg/scripts/buildsystems/vcpkg.cmake"`

Thanks.

**Comment by harokyang** [comment]
@LilyWangL You can pass the build, because in CMakeLists.txt line 16
it is `find_package(glslang REQUIRED)`, which invoke the Findglslang.cmake I provided, which solved the issue
If you change it to `find_package(glslang CONFIG REQUIRED)` to invoke glslang-config.cmake provided with vcpkg, it will fail

**Comment by LilyWangL** [comment]
I can't repro it. I change it to `find_package(glslang CONFIG REQUIRED)`, and configure project successfully. Do you add cmakeToolchain to your **CMakeSettings.json**?

**Comment by harokyang** [comment]
@LilyWangL Of coursse I did
I have multiple libs like tbb glm glfw3 oiio managed by vcpkg
They all works fine except this glslang

**Comment by harokyang** [comment]
Finally I found the reason behind this issue, and have a solution

The reason is:
1. In Visual Studio(not vscode), a Release config is actually labelled as RelWithDebInfo in CMakeSettings.json
2. cmake will try to match the same config between project and linked libraries
3. vcpkg only build Debug and Release configs, there is no RelWithDebInfo for any package
4. When cmake failed to find a matched config for an imported library, it will fallback to the first config listed in the property IMPORTED_CONFIGURATIONS
5. glslangConfig.cmake included glslangConfig-debug.cmake before glslangConfig-release.cmake(by alphabet?) which makes Debug appeared before Release. But in my own Findglslang.cmake, I listed Release before Debug

And here is the solution according to this [cmake manual page](https://cmake.org/cmake/help/latest/prop_tgt/MAP_IMPORTED_CONFIG_CONFIG.html)
add the following properties for all the glslang libs in glslangConfig.cmake
```
set_target_properties(glslang::xxxxxx PROPERTIES
  MAP_IMPORTED_CONFIG_MINSIZEREL Release
  MAP_IMPORTED_CONFIG_RELWITHDEBINFO Release
  )
```

Thanks

**Comment by JackBoosY** [comment]
@Rastaban I think this is a common issue.

**Comment by JackBoosY** [comment]
vcpkg's support for `RelWithDebInfo` is not good.

@ras0219-msft  Do we need to support it?

**Comment by Neumann-A** [comment]
@JackBoosY: This can be closed since the vcpkg toolchain now maps those configurations correctly.

**Comment by JackBoosY** [comment]
@Neumann-A Could you provide me the related PR? I want to double confirm this.

**Comment by JackBoosY** [comment]
I think this issue should be fixed.
