### ISSUE TITLE
[PhysX] Support platforms other than Windows 

### ISSUE THREAD

**Issue by no-preserve-root** [microsoft/vcpkg#8045]
PhysX supports platforms by shipping build presets (`physx/buildtools/presets/public` in the source tree). Following presets are included in PhysX 4.1.1:

* Android-19, arm64-v8a (`android-arm64-v8a.xml`)
* Android-19, armeabi-v7a with NEON (`android.xml`)
* iOS Xcode PhysX general settings (`ios64.xml`)
* Linux-aarch64 gcc (`linux-aarch64.xml`)
* Linux clang (`linux.xml`)
* macOS Xcode (`mac64.xml`)
* VC12 Win32 (`vc12win32.xml`)
* VC12 Win64 (`vc12win64.xml`)
* **VC14 Win32 (`vc14win32.xml`)**
* **VC14 Win64 (`vc14win64.xml`)**
* VC15 UWP 32bit (`vc15uwp32.xml`)
* VC15 UWP 64bit (`vc15uwp64.xml`)
* VC15 UWP ARM 32bit (`vc15uwparm32.xml`)
* VC15 UWP ARM 64bit (`vc15uwparm64.xml`)
* **VC15 Win32 (`vc15win32.xml`)**
* **VC15 Win64 (`vc15win64.xml`)**
* **VC16 Win32 (`vc16win32.xml`)**
* **VC16 Win64 (`vc16win64.xml`)**

Currently, the `portfile.cmake` only handles VC14+ Windows builds (not UWP) with both bit sizes (bolded). Support for UWP should be straightforward, support for Linux and macOS should be implementable along the same lines as the Windows support.

As far as I can tell, this requires extending the `preset.xml` generation, using CMake over MSBuild on non-MS-platforms, and fixes to some paths.

**Comment by Haeri** [comment]
*Bump*
Would be super cool to get at least linux or macos working. Unfortunately I can't even do a local workaround cause it aborts during the installation due to unsupported paltform

**Comment by Adela0814** [comment]
Fixed by PR https://github.com/microsoft/vcpkg/pull/13849
