### ISSUE TITLE
[VCPKG] script function failed

### ISSUE THREAD

**Issue by Voskrese** [microsoft/vcpkg#8047]
trying to build a cpp-common package
https://github.com/ros/roscpp_core
crashes with an error
`Maximum recursion depth of 1000 exceeded`

```
-- Using CATKIN_SKIP_TESTING: ON (implying CATKIN_ENABLE_TESTING=OFF)
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: E:/tools/vcpkg/buildtrees/ros-cpp-common/x64-windows-rel/test_results
-- Found gmock: gmock and gtests will be built
CMake Error at E:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake:247 (_add_library):
  Maximum recursion depth of 1000 exceeded
Call Stack (most recent call first):
  E:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake:247 (_add_library)

```
https://github.com/microsoft/vcpkg/blob/ba34f17814a865ca292865d37643d52b12fe0e92/scripts/buildsystems/vcpkg.cmake#L187

delete this function, assembly is successful
**What could be the reason?**

add parameter, unsuccessful
https://cmake.org/cmake/help/latest/variable/CMAKE_MAXIMUM_RECURSION_DEPTH.html
```
if(NOT CMAKE_MAXIMUM_RECURSION_DEPTH)
  set(CMAKE_MAXIMUM_RECURSION_DEPTH 3000)
endif()
```

**Comment by PhoebeHui** [comment]
@Voskrese, since it required package 'CATKIN' which doesn't support in vcpkg, could you provide the repro steps, portfile.cmake and CMakeLists.txt file could help us address this issue.

**Comment by Neumann-A** [comment]
Seems like somebody tried to overwrite add_library and then loaded the vcpkg toolchain.

**Comment by Neumann-A** [comment]
Yeah catkin overwrites add_library

**Comment by Voskrese** [comment]
@PhoebeHui 

CMakeLists - cpp_common
https://github.com/ros/roscpp_core/blob/kinetic-devel/cpp_common/CMakeLists.txt

catkin
https://github.com/ros/catkin/tree/kinetic-devel/cmake

pre-install cmake files
[catkin.zip](https://github.com/microsoft/vcpkg/files/3578203/catkin.zip)

**Comment by traversaro** [comment]
Note that @lennonwoo have been working on a GSoC project about bringing the ROS packages (including `roscpp_core`, I guess) to vcpkg. A recap of his work is available at https://lennonwoo.github.io/2019/08/20/Support-creating-Windows-packages-for-ROS2-in-Bloom-in-GSoC-2019/ .

**Comment by Voskrese** [comment]
Yesterday evening I collected about 40 ports, from ROS
I did not meet any special problems, everything is going successfully, except for one
https://github.com/ros/roscpp_core/tree/kinetic-devel/rostime

**Comment by traversaro** [comment]
Actually my previous  comment was wrong, as the GSoC project was on bringing ROS2 packages on vcpkg, not ROS(1) packages, sorry for the noise.

**Comment by Voskrese** [comment]
@traversaro 
I met a comment somewhere that ROS2 is not supported on Windows

**Comment by Voskrese** [comment]
@Neumann-A 
> Yeah catkin overwrites add_library

If guilty **catkin** 
Close

**Comment by okmechak** [comment]
Facing similar error whyli trying to configure deal.ii project using vcpkg(deal.ii dependce on Boost which is installed under vcpkg):

>...
>Include C:/Users/ofcra/Source/dealii/cmake/checks/check_03_compiler_bugs.cmake
>Include C:/Users/ofcra/Source/dealii/cmake/configure/configure_1_cuda.cmake
DEAL_II_WITH_CUDA is set to off.
>Include C:/Users/ofcra/Source/dealii/cmake/configure/configure_1_lapack.cmake
>CMake Error at cmake/macros/macro_find_package.cmake:23 (STRING):
>  Maximum recursion depth of 1000 exceeded
>Call Stack (most recent call first):
> cmake/macros/macro_find_package.cmake:27 (_FIND_PACKAGE)
> cmake/macros/macro_find_package.cmake:27 (_FIND_PACKAGE)
> cmake/macros/macro_find_package.cmake:27 (_FIND_PACKAGE)
> ...
>C:/Users/ofcra/Source/vcpkg/scripts/buildsystems/vcpkg.cmake:263 (_find_package)
>  cmake/configure/configure_1_lapack.cmake:22 (FIND_PACKAGE)
>  C:/Users/ofcra/builds/dealii/CMakeFiles/CMakeTmp/evaluate_expression.tmp:1 (FEATURE_LAPACK_FIND_EXTERNAL)
>  cmake/macros/macro_evaluate_expression.cmake:30 (INCLUDE)
>  cmake/macros/macro_configure_feature.cmake:237 (EVALUATE_EXPRESSION)
>  cmake/configure/configure_1_lapack.cmake:116 (CONFIGURE_FEATURE)
>  cmake/macros/macro_verbose_include.cmake:19 (INCLUDE)
> CMakeLists.txt:124 (VERBOSE_INCLUDE)
> ....
