### ISSUE TITLE
[gdal] build failure when installing osg

### ISSUE THREAD

**Issue by ChisonShang** [microsoft/vcpkg#8058]
**Host Environment**
- OS: [Windows10]
- Compiler: Visual Studio Community 2017 15.9.15

**To Reproduce**
`./vcpkg install osg:x64-windows`
or
`./vcpkg install gdal:x64-windows`

**Failure logs** 
-cl : Command line warning D9024 : unrecognized source file type 'Files\vcpkg\vcpkg-master\installed\x64-windows\include', object file assumed
cl : Command line warning D9027 : source file 'Files\vcpkg\vcpkg-master\installed\x64-windows\include' ignored
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.EXE"' : return code '0x2'
Stop.

**Additional context**
I have located where my problem is.
In the log, there are several warnings have the same part
"cl : Command line warning D9027 : source file '**Files**\vcpkg\vcpkg-master\installed\x64-windows\include' ignored"
But my path of vcpkg.exe is "**...:\Program Files...**", maybe the **space** in my path was considered **separator**. So when I moved vcpkg.exe to another location without space in the path, this problem disappeared.

**Space-Inside-Path issue needs to be fixed. Vcpkg supports paths with spaces, this is gdal port bug.**

**Comment by JackBoosY** [comment]
Hi @ChisonShang , thanks for reporting this issue!
The .mk file used in gdal needs to include a header file with a space path, but makefile cannot use double quotes to solve this problem currently. So we cannot fix this issue now. :(

**Comment by alexandre-lejeune** [comment]
Hi, I've the same issue.

I'd like to install osg, and gdal build failed. 
In x64 that's OK, but osg build failed, and in x86 that's gdal who failed.

Did you find a solution since to fix it?

Thanks, Alex

**Comment by JackBoosY** [comment]
@alexandre-lejeune Please use a short path with no spaces to clone vcpkg and try again.

Thanks.

**Comment by alexandre-lejeune** [comment]
Thanks, I'll try it

**Comment by alexandre-lejeune** [comment]
Hi,
Thanks @JackBoosY I remove vcpkg folfer to restart in clean environment, and put new vcpkg folder on C root.
After 21 hours of building that's right.
Have a good day.
