### ISSUE TITLE
error :failed with BUILD_FAILED when Building package openssl-windows:x86-windows

### ISSUE THREAD

**Issue by ZhouJJJKKK** [microsoft/vcpkg#8064]
**Describe the bug**
fail when building package openssl-windows:x86 ,which is one part of poco

**Environment**
- OS: Windows 10
- Compiler: latest visual studio 2017

**To Reproduce**
1. ./vcpkg install poco
Repro code when

**Expected behavior**
expect success

**Failure logs** 
D:\vcpkg-master>vcpkg install poco
The following packages will be built and installed:
  * libpng[core]:x86-windows
  * libpq[core]:x86-windows
  * openssl[core]:x86-windows
  * openssl-windows[core]:x86-windows
    poco[core]:x86-windows
  * sqlite3[core]:x86-windows
  * zlib[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/7: openssl-windows:x86-windows
Building package openssl-windows[core]:x86-windows...
-- Using cached D:/vcpkg-master/downloads/openssl-1.0.2s.tar.gz
-- Using source at D:/vcpkg-master/buildtrees/openssl-windows/src/openssl-1-c41872ef97
-- Downloading http://download.qt.io/official_releases/jom/jom_1_1_3.zip...
-- Downloading http://download.qt.io/official_releases/jom/jom_1_1_3.zip... Failed. Status: 52;"Server returned nothing (no headers, no data)"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:172 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:285 (vcpkg_download_distfile)
  ports/openssl-windows/portfile.cmake:41 (vcpkg_find_acquire_program)
  scripts/ports.cmake:85 (include)

Error: Building package openssl-windows:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-windows:x86-windows
  Vcpkg version: 2019.08.27-nohash

**Additional context**

**Comment by JackBoosY** [comment]
It seems that you can't connect to the qt website. I am sure you can't manually download the jom using this [link](http://download.qt.io/official_releases/jom/jom_1_1_3.zip).

Please use a proxy/VPN/SS to download tools.

Thanks.

**Comment by JackBoosY** [comment]
Hi @ZhouJJJKKK, does this issue still bother you?

**Comment by JackBoosY** [comment]
If this issue is still not resolved, please reopen it.
