### ISSUE TITLE
New cppkafka port doesn't honour VCPKG_LIBRARY_LINKAGE=dynamic

### ISSUE THREAD

**Issue by giles45** [microsoft/vcpkg#8067]
Good to see the new cppkafka port. However, it doesn't honour the VCPKG_LIBRARY_LINKAGE setting. That is, it is always building a static library.

**Environment**
- OS: Windows
- Compiler: MSVC 2019

**To Reproduce**
1. .\vcpkg install cppkafka:x86-windows

**Expected behavior**
For this scenario, I would expect vcpkg to generate cppkafka.dll in vcpkg\installed\x86-windows\bin (and debug\bin); instead it generates the static library cppkafka.lib in vcpkg\installed\x86-windows\lib

**Additional context**
We have an existing cppkafka port file that we generated independently, which we have been using. Though we not experienced at creating port files, I have attached the one we used in case it is helpful.

[cppkafka.zip](https://github.com/microsoft/vcpkg/files/3579471/cppkafka.zip)

**Comment by Neumann-A** [comment]
reason in cppkafka:
```
if(CPPKAFKA_BUILD_SHARED)
    message(STATUS "Build will generate a shared library. "
            "Use CPPKAFKA_BUILD_SHARED=0 to perform a static build")
    set(CPPKAFKA_LIBRARY_TYPE SHARED)
else()
    message(STATUS "Build will generate a static library.")
    set(CPPKAFKA_LIBRARY_TYPE STATIC)
    add_definitions("-DCPPKAFKA_STATIC=1")
    set(CMAKE_POSITION_INDEPENDENT_CODE ON)
endif()
```

**Comment by NancyLi1013** [comment]
Hi @giles45 thanks for posting this issue. This issue should be fixed now. Please try to update vcpkg and use it.
