### ISSUE TITLE
Libraries that needs patches to build in a path with space

### ISSUE THREAD

**Issue by alexkaratarakis** [Microsoft/vcpkg#807]
The underlying build system of the following libraries needs patching to work if it is located in a path with space:
(checked = `vcpkg` has the needed patches)
- [x] openssl - Patches upstreamed!
- [ ] libvpx
- [x] libxml2
- [x] openblas - Patches upstreamed!
- [x] libvorbis 
- [ ] icu
- [ ] jsonnet
- [x] readosm - No patching required
- [x] FreeXL - No patching required

**Comment by JackBoosY** [comment]
Hi @alexkaratarakis , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
