### ISSUE TITLE
[New Port Request] alglib

### ISSUE THREAD

**Issue by rubengura** [microsoft/vcpkg#8074]
I'm trying to install the library alglib through vcpkg. 

I tried `vcpkg search alglib` but I got nothing as a result. I was wondering if the library is included.

Thank you in advance,

Library name: alglib
Library description: Cross-platform numerical analysis and data processing library.
Source repository URL: Original github repository not found,
Project homepage: http://www.alglib.net/

As far as I'm concerned there aren't any additional features to consider when adding the library, but please consider that I'm new with C++ programming and I may be missing important information related to the package.

**Comment by PhoebeHui** [comment]
@rubengura, you got nothing since alglib doesn't added in VCPKG, I edited the format and please help fill the related information.

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
