### ISSUE TITLE
Installation of powershell-core fails

### ISSUE THREAD

**Issue by lucaregini** [microsoft/vcpkg#8078]
**Describe the bug**
I am executing a "vcpkg install fltk" on an host that doesn't have powershell-core.
vcpkg tries to install it automatically but installation fails. The link from which vcpkg tries to download it ( https://github.com/PowerShell/PowerShell/releases/download/v6.2.1/PowerShell-6.2.1-win-x86.zip -> c:\Dev\Retro\vcpkg\downloads\PowerShell-6.2.1-win-x86.zip)  is reacheable and I am able to download the PowerShell-6.2.1-win-x86 zip archive from internet explorer.

**Environment**
- OS: Windows 10
- Compiler: Visual studio 2019

**To Reproduce**
1. vcpkg install fltk
2. See error: 

c:\Dev\Retro\vcpkg>vcpkg install fltk
The following packages will be built and installed:
    fltk[core]:x86-windows
  * libjpeg-turbo[core]:x86-windows
  * libpng[core]:x86-windows
  * zlib[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/4: zlib:x86-windows
Building package zlib[core]:x86-windows...
A suitable version of powershell-core was not found (required v6.2.1). Downloading portable powershell-core v6.2.1...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v6.2.1/PowerShell-6.2.1-win-x86.zip -> c:\Dev\Retro\vcpkg\downloads\PowerShell-6.2.1-win-x86.zip
WinHttpSendRequest() failed: 12002

**Expected behavior**
vcpkg downloads and install correctly powershell core.

**Failure logs** 
-(please attached failure logs)

**Additional context**

**Comment by cenit** [comment]
Are you behind a proxy?
I have the same problem: #7207
Luckily at least your issue got noticed

**Comment by lucaregini** [comment]
You nailed it! I found that the root cause is the proxy. Of course this is a big no-no for adopting vcpkg in all enterprises that use proxy. And in Europe there are still quite a few!

**Comment by cenit** [comment]
Also in the US ;)
not sure why this is not considered important, since at least at the beginning, proper proxy support was considered a priority

**Comment by BillyONeal** [comment]
I'm closing this because we just made a bunch of changes to proxy handling (which I think would fix this) and this issue is over 2 years old. Please file a new issue if the problem persists with a current vcpkg.
