### ISSUE TITLE
zeromq install faied on centos  

### ISSUE THREAD

**Issue by whidbey** [microsoft/vcpkg#8081]
**Describe the bug**

**Environment**
- OS: Linux /centos
- Compiler: gcc 4.8.5 /7.3.1

**To Reproduce**
1. ./vcpkg install zeromq
2. See error
[root@localhost vcpkg]# ./vcpkg install zeromq
The following packages will be built and installed:
    zeromq[core]:x64-linux
Starting package 1/1: zeromq:x64-linux
Building package zeromq[core]:x64-linux...
-- Using cached /root/vcpkg/downloads/zeromq-libzmq-b5db4b4421c8b2766321e70e5e9ca07c197fac47.tar.gz
-- Using source at /root/vcpkg/buildtrees/zeromq/src/7c197fac47-b27273d565
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
ok
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: /root/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v
    Working Directory: /root/vcpkg/buildtrees/zeromq/x64-linux-dbg
    See logs for more information:
      /root/vcpkg/buildtrees/zeromq/install-x64-linux-dbg-out.log
      /root/vcpkg/buildtrees/zeromq/install-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/zeromq/portfile.cmake:32 (vcpkg_install_cmake)
  scripts/ports.cmake:85 (include)

Error: Building package zeromq:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zeromq:x64-linux
  Vcpkg version: 2019.08.27-unknownhash

Additionally, attach any relevant sections from the log files above.
**Expected behavior**

**Failure logs** 
CMake Error at cmake_install.cmake:72 (file):
  file INSTALL cannot find
  "/root/vcpkg/buildtrees/zeromq/x64-linux-dbg/doc/zmq.html".

**Additional context**

**Comment by PhoebeHui** [comment]
@whidbey, thanks for reporting this issue, however, I can't repro this issue with gcc 7.4.1 on Ubuntu 18.04 , can you remove /root/vcpkg/buildtrees/zeromq/src, try to rebuild and check if the issue still happen again?

**Comment by myd7349** [comment]
Hi! @PhoebeHui I have reproduced this error on a Ubuntu 19.04 VM with `asciidoc` installed.
Hi! @whidbey Can you give this patch a try? https://github.com/microsoft/vcpkg/pull/8119

**Comment by whidbey** [comment]
thanks it works..may close?
