### ISSUE TITLE
cmake: <package>/lib/cmake folder linting

### ISSUE THREAD

**Issue by Mixaill** [Microsoft/vcpkg#809]
Something is not OK with `/lib/cmake/` support.

When I place files in `<package>/lib/cmake/` I get an error:
>The `/lib/cmake` folder should be moved to just `/cmake`
 
But when I place files `<package>/cmake/` I get:
>The following cmake files were found outside `/share/<package>`. Please place cmake files in `/share/<package>`

O_o

**Comment by ras0219-msft** [comment]
This is unfortunately some detritus that was left around while we were still firming up where to place the cmake config files.

The final resting place is as described in the last step of the goose chase: `/share/<package>/cmake`. I've also pushed 3e01505 which fixes the first message to point directly at the destination.

Thanks for reporting this!
