### ISSUE TITLE
Why some packages are old and how to replace new version manually?

### ISSUE THREAD

**Issue by ejamshidiasl** [microsoft/vcpkg#8091]
Hello
i need some packages like fltk and sqlite3 but they are not latest release. i downloaded latest release and build them. Now is it possible to replace or update to latest release?

**Comment by ehsan-mohammadi** [comment]
@ejamshidiasl Some PRs are about the port update (For example see #8089 or #8086). We should note that by updating a port, doesn't occur port broken. So, we need to check the port after the update. Currently, there're some tests that check the PRs and try to build it for multiple platforms. Finally, I think it's better to try to do the best improve port and not just modify references to a newer release.
