### ISSUE TITLE
[New Port Request] caffe

### ISSUE THREAD

**Issue by how0723** [microsoft/vcpkg#8093]
Library name: caffe

Library description: Caffe: a fast open framework for deep learning.

Source repository URL: https://github.com/BVLC/caffe

Project homepage (if different from the source repository): http://caffe.berkeleyvision.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by Voskrese** [comment]
https://github.com/microsoft/vcpkg/search?q=Caffe&type=Issues

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
