### ISSUE TITLE
[googleapis] update to 0.1.5

### ISSUE THREAD

**Issue by curtpm** [microsoft/vcpkg#8097]
Library name:
googleapis

New version number:
0.1.5

Other information that may be useful (release notes, etc...)
Update protobuf files:
https://github.com/googleapis/cpp-cmakefiles/releases/tag/v0.1.5

**Comment by ehsan-mohammadi** [comment]
@curtpm Already an open PR(#8077) exists for the update this port to 0.1.5 version.
