### ISSUE TITLE
OpenCV is not linking to libjpeg-turbo

### ISSUE THREAD

**Issue by compiling** [Microsoft/vcpkg#81]
The build configuration for OpenCV links to libjpeg in the 3rdparty libs folder instead of the libjpeg-turbo installed as a dependency.

Likewise, it also links to libpng in 3rdparty instead of the pre-installed libpng.

Build log:
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\link.exe /ERRORREPORT:QUEUE /OUT:"D:\projects\vcpkg\buildtrees\opencv\x64-windows-rel\bin\Release\opencv_world310.dll" /INCREMENTAL:NO /NOLOGO /LIBPATH:D:/projects/vcpkg/buildtrees/opencv/src/3rdparty/lib /LIBPATH:D:/projects/vcpkg/buildtrees/opencv/src/3rdparty/lib/Release kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib "D:\projects\vcpkg\installed\x64-windows\lib\zlib.lib" D:\projects\vcpkg\buildtrees\opencv\src\3rdparty\ippicv\unpack\ippicv_win\lib\intel64\ippicvmt.lib "D:\projects\vcpkg\installed\x64-windows\lib\zlib.lib" **..\..\3rdparty\lib\Release\libjpeg.lib** ..\..\3rdparty\lib\Release\libwebp.lib **..\..\3rdparty\lib\Release\libpng.lib** ..\..\3rdparty\lib\Release\libtiff.lib ..\..\3rdparty\lib\Release\libjasper.lib ..\..\3rdparty\lib\Release\IlmImf.lib vfw32.lib comctl32.lib gdi32.lib ole32.lib setupapi.lib ws2_32.lib "D:\projects\vcpkg\installed\x64-windows\lib\zlib.lib"

**Comment by ras0219-msft** [comment]
Thanks for reporting this! I've ensured OpenCV now links against the built `libjpeg-turbo`, `libpng`, `zlib`, and `tiff` by deleting the relevant `3rdparty` directories.
