### ISSUE TITLE
[geographiclib] `find_package(GeographicLib) does not work on Linux

### ISSUE THREAD

**Issue by JamesOldfield** [microsoft/vcpkg#8104]
If I put `find_package(GeographicLib)` in my application, having installed GeographicLib with vcpkg, the library is not found by CMake. There are a few reasons for this:

## Nesting

The config gets installed with an extra level of nesting e.g.:

    /path/to/vcpkg/installed/x64-linux/share/geographiclib/GeographicLib/geographiclib-config.cmake

This means that the config is not found by `find_package`. I found this can be fix by changing code in the geographiclib port file from this (introduced in #7697):

    if (VCPKG_TARGET_IS_WINDOWS)
        vcpkg_fixup_cmake_targets(CONFIG_PATH cmake)
    else()
        vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake)
    endif()

To this:

    if (VCPKG_TARGET_IS_WINDOWS)
        vcpkg_fixup_cmake_targets(CONFIG_PATH cmake)
    else()
        vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/GeographicLib)
    endif()

This results in the config being installed to:

    /path/to/vcpkg/installed/x64-linux/share/geographiclib/geographiclib-config.cmake

## Cross compiling variable

After installing GeographicLib with the portfile changed as described above, `find_package(GeographicLib)` still fails with the following mysterious error:

    The following configuration files were considered but not accepted:
    
      /path/to/vcpkg/installed/x64-linux/share/geographiclib/geographiclib-config.cmake, version: 1.47 (cross-compiling = OFF)

It turns out that geographiclib captures the `CMAKE_CROSSCOMPILING` variable at build time and checks it matches at `find_package` time (the check is actually in `geographiclib-config-version.cmake`). But when vcpkg builds GeographicLib, that variable is set to `"OFF"`, whereas when configuring my application it is set to `"FALSE"`! Despite both being falsey, GeographicLib's cmake script does a string comparison (presumably necessary for non-falsey values that specify an actual target architecture), so the test fails.

I'm not sure what the best way around this, especially since I'm not sure how the two values end up different. Perhaps `remove-tools-and-fix-version.patch` could also remove this check.

## Package name 

This is more minor, but after installing the package, vcpkg shows a message telling you to use 

    find_package(geographiclib CONFIG REQUIRED)
    target_link_libraries(main PRIVATE GeographicLib_STATIC GeographicLib::GeographicLib_STATIC)

In fact the right package name is `GeographicLib` in camel case. Even if the config is found, it will be rejected unless you get the case right (there's a test for it in `geographiclib-config-version.cmake`). Additionally, you only need one of those targets (I've only tested the unprefixed version).

**Comment by JackBoosY** [comment]
@JamesOldfield  Thanks for reporting this issue.
For Package name, vcpkg uses the **all-lowercase** port name, so I just added the usage.

**Comment by JackBoosY** [comment]
Close this issue via PR merged.

**Comment by JamesOldfield** [comment]
@JackBoosY  Fantastic, thanks for fixing this so quickly.
