### ISSUE TITLE
Error in installing package using vcpkg

### ISSUE THREAD

**Issue by SoumenKunduTantra** [microsoft/vcpkg#8105]
I had followed the installation step of  vcpkg as given in the link https://github.com/microsoft/vcpkg  

> git clone https://github.com/Microsoft/vcpkg.git
> cd vcpkg
>bootstrap-vcpkg.bat
>vcpkg integrate install

Upto the last command  `vcpkg integrate install ` it worked properly.

But when I actually trying to install the package it is giving following error.
```
D:\vcpkg>vcpkg install sdl2 curl
The following packages will be built and installed:
    curl[core,ssl,winssl]:x64-windows
    sdl2[core]:x64-windows
  * zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: sdl2:x64-windows
Building package sdl2[core]:x64-windows...
CMake Error at D:/vcpkg/scripts/cmake/vcpkg_download_distfile.cmake:79 (file):
  file RENAME failed to rename

    /d/vcpkg/D:/vcpkg/downloads/temp

  to

    /d/vcpkg/D:/vcpkg/downloads/temp0

  because: No such file or directory

Call Stack (most recent call first):
  D:/vcpkg/scripts/cmake/vcpkg_from_github.cmake:108 (vcpkg_download_distfile)
  D:/vcpkg/ports/sdl2/portfile.cmake:3 (vcpkg_from_github)
  D:/vcpkg/scripts/ports.cmake:85 (include)


Could not copy into file: D:\vcpkg\packages\sdl2_x64-windows\share\sdl2\vcpkg_abi_info.txt
```
vcpkg_abi_info.txt is given below.
[vcpkg_abi_info.txt](https://github.com/microsoft/vcpkg/files/3589803/vcpkg_abi_info.txt)

**Comment by cbezault** [comment]
Hmm those paths look really messed up. Are you working inside of wsl?

**Comment by SoumenKunduTantra** [comment]
No I am installing it in pure Windows OS.
OS : Windows 10 Home.
Bit : 64 bit

**Comment by PhoebeHui** [comment]
@SoumenKunduTantra, I can't repro your issue, the logs are mess, are you build with custom triplet, from your command it seems that you build with x86-windows, however the following log says it built with x64-windows, can you get clean vcpkg and try to build again?

see [vcpkg_download_distfile.cmake](https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_download_distfile.cmake#L79),  from your log ' /d/vcpkg/D:/vcpkg/downloads/temp', it seems the ${DOWNLOADS} value has something wrong, it should be 'D:/vcpkg/downloads/temp'.

The DOWNLOADS variable set by [ports.cmake](https://github.com/microsoft/vcpkg/blob/9241e6c4b2ca8dbf8ec2c0997084d63bf48ce460/scripts/ports.cmake#L25)

**Comment by SoumenKunduTantra** [comment]
I deleted the entire vcpkg and started from initial.

1. I downloaded the vcpkg from https://github.com/microsoft/vcpkg
and followed the below steps.
2. .\bootstrap-vcpkg.bat
3. .\vcpkg.exe integrate install
Upto to the above step it worked perfectly. Now when I am running the below command it is giving error.
4. .\vcpkg.exe install sdl2 curl
```
Error: invalid triplet: d:\vcpkg-master\triplets\x64-windows.cmake
Available architecture triplets:
  arm-uwp
  arm-windows
  arm64-uwp
  arm64-windows
  x64-linux
  x64-osx
  x64-uwp
  x64-windows
  x64-windows-static
  x86-uwp
  x86-windows
  x86-windows-static
```

As  per some documentation I also set **VCPKG_DEFAULT_TRIPLET = D:\vcpkg-master\triplets\x64-windows.cmake** in environmental variable and tried but same error(error coming on point no 4) occurring.

(Note. All the above command run on **Windows PowerShell(Admin)**)

**Comment by SoumenKunduTantra** [comment]
If this https://github.com/microsoft/vcpkg/issues/8105#issuecomment-529793732 is the issue, then kindly suggest any solution to this.

**Comment by PhoebeHui** [comment]
@SoumenKunduTantra, I have no idea.

**Comment by SoumenKunduTantra** [comment]
I followed the same procedure given in https://github.com/microsoft/vcpkg on another PC. 
Still same issue https://github.com/microsoft/vcpkg/issues/8105#issue-490993940 occurring on that PC too.

**Comment by Perbudag** [comment]
I had a similar problem, try moving the vcpkg folder to your Downloads or Documents folder.

**Comment by PhoebeHui** [comment]
Hi @SoumenKunduTantra, @Perbudag, have you solve the issue finally?

**Comment by SoumenKunduTantra** [comment]
Hi @PhoebeHui Thanks for your reply. My system was reinstalled with fresh OS of Windows 10. After that when I tried installing vcpkg it got installed properly without any error.

**Comment by PhoebeHui** [comment]
Glad you got the issue fixed!
