### ISSUE TITLE
My build script needs to gather all the PDBs for the build. Is there a way to find the vcpkg PDB path?

### ISSUE THREAD

**Issue by bobk2824** [microsoft/vcpkg#8106]
In order to be able to debug memory dump files that customers may submit, I need to save all symbol files for each build.

I'd rather not have to enter the vcpkg path for each build environment.

Since msbuild can somehow find the vcpkg path, I'm hoping that my build script can also it, although I don't see the vcpkg path in any of the C++ directories or any of the VC macros.

This can be solved in one of 2 ways:

1. The build script can get the vcpkg path through some build env variable and copy the PDBs from there.
2. The build process currently copies only the .dll from vcpkg to the output directory. Is there any way for it to copy BOTH the .dll and .pdb files?

Thanks,

Bob

**Comment by PhoebeHui** [comment]
@bobk2824, in vcpkg, after install the port, it will copy the .dll and .pdb to .\installed\[triplet]\bin folder, does that you want?

**Comment by bobk2824** [comment]
I understand that.
Here is the issue:
When I compile a project, it creates the executables and PDB files and puts them in the output folder.
For any DLLs provided by vcpkg, the DLLs are copied from the vcpkg folder to the output folder of the build.
When it is done the output folder has all of the executables and most of the PDBs. It is missing the PDBs from vcpkg.

The question is, I need to automate packaging of the build, which includes gathering together ALL of the PDB files, including those that were generated by vcpkg. How can I do that?
How can my build script know where the PDB files are? Somehow it knows where the vcpkg DLLs are and copies them over, but I don't see any VC macros that can help me find the vcpkg installation directory.

To make this clearer, there is not just one build environment, so I want to make creation of a build environment as easy as possible. I could require a environment variable be created that indicates the vcpkg install directory, but it seems like the build process already knows that somehow and it would be redundant to have to specify that.

Thanks!

**Comment by bobk2824** [comment]
I have a possible solution:
It looks like the vcpkg integrate command creates a folder here:
%LOCALAPPDATA%\vcpkg
Inside this folder is the file: vcpkg.path.txt
It contains one line that is the install patch of vcpkg.
My script can read that file and then be able to find the PDB files it needs.
It isn't as easy as I'd like but it should work.

I'm surprised this hasn't come up. When I do a "gold" build that goes to many customers, I need to record all the libraries used and keep a copy of all PDBs in case we need to analyze a memory dump. As you might have guessed, this recently happened and we found we were missing key PDB files, hampering the resolution of the issue.

Thanks,
Bob
