### ISSUE TITLE
[mathgl]build failure on x86-windows

### ISSUE THREAD

**Issue by freeyyc** [microsoft/vcpkg#8114]
vcpkg  build mathgl failed:

C:\vcpkg>vcpkg install mathgl[fltk] --recurse
The following packages will be rebuilt:
    mathgl[core,fltk,jpeg,opengl,png,zlib]:x86-windows
Starting package 1/2: mathgl:x86-windows
Removing package mathgl:x86-windows...
Removing package mathgl:x86-windows... done
Purging package mathgl:x86-windows...
Purging package mathgl:x86-windows... done
Elapsed time for package mathgl:x86-windows: 108.1 ms
Starting package 2/2: mathgl:x86-windows
Building package mathgl[core,fltk,jpeg,opengl,png,zlib]:x86-windows...
-- Using cached C:/vcpkg/downloads/mathgl-2.4.3.tar.gz
-- Using source at C:/vcpkg/buildtrees/mathgl/src/2.4.3-92b5a9880f
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v
    Working Directory: C:/vcpkg/buildtrees/mathgl/x86-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\mathgl\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/mathgl/portfile.cmake:90 (vcpkg_install_cmake)
  scripts/ports.cmake:85 (include)

Error: Building package mathgl:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: mathgl:x86-windows
  Vcpkg version: 2019.08.27-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by JackBoosY** [comment]
Hi @freeyyc, thanks for reporting this issue.
This issue has been fixed in #8145. please update vcpkg and rebuild mathgl.

Thanks.
