### ISSUE TITLE
[New Port Request] <ZeroC-ICE>

### ISSUE THREAD

**Issue by zlinwei** [microsoft/vcpkg#8117]
Library name: ZeroC-ICE

Library description: RPC Framework

Source repository URL: https://github.com/zeroc-ice/ice.git

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by davidebeatrici** [comment]
Duplicate of #6106.

**Comment by LilyWangL** [comment]
Closed as duplicate of #6106.
