### ISSUE TITLE
vcpkg boost:x86-windows build failure. Virus detected

### ISSUE THREAD

**Issue by fpgaman** [microsoft/vcpkg#8118]
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/3595141/config-x86-windows-out.log)

[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/3595135/config-x86-windows-out.log)
**Host Environment**
- OS: [Windows 10.]
- Compiler: revision Visual Studio 2019 community

**To Reproduce**
Attempting to install GTK for Visual Studio using the instructions here:
https://docs.microsoft.com/en-us/cpp/build/vcpkg?view=vs-2019

`./vcpkg install boost:x86-windows`

1. Run bootstrap-vcpkg.bat (runs successfully)
2. Run vcpkg install boost:x86-windows.
Part way through the process, the Bitdefender anti-virus program detects a virus: Shortly after that, VCPKG fails

**Failure logs** 
Here is the message from Bitdefender:
The file C:\Projects\GTK\VCPKG\buildtrees\zlib\x86-windows-rel\CMakeFiles\3.15.3\CompilerIdC\CMakeCCompilerId.exe is infected with Gen:Variant.Fugrafa.4624 and was moved to quarantine.

Right after the message from Bitdefender vcpkg fails. Here are the last messages from vcpkg:
Installing package boost-iterator[core]:x86-windows... done
Elapsed time for package boost-iterator:x86-windows: 4.721 s
Starting package 32/146: liblzma:x86-windows
Building package liblzma[core]:x86-windows...
-- Downloading https://github.com/xz-mirror/xz/archive/v5.2.4.tar.gz...
-- Extracting source C:/Projects/GTK/VCPKG/downloads/xz-mirror-xz-v5.2.4.tar.gz
-- Applying patch enable-uwp-builds.patch
-- Using source at c:/Projects/GTK/VCPKG/buildtrees/liblzma/src/v5.2.4-66bfe33102
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: c:/Projects/GTK/VCPKG/buildtrees/liblzma/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      c:\Projects\GTK\VCPKG\buildtrees\liblzma\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:296 (vcpkg_execute_required_process)
  ports/liblzma/portfile.cmake:15 (vcpkg_configure_cmake)
  scripts/ports.cmake:85 (include)

Error: Building package liblzma:x86-windows failed with: BUILD_FAILED

**Additional context**
 I have disabled Bitdefender firewalls, but it looks like one of the files generated by vcpkg has a virus in it. 
I am attempting to install GTK for Visual Studio 2019 for use with the Analog Devices IIO-Oscilloscope project to run on Windows

**Comment by Neumann-A** [comment]
Not a vcpkg issue: If it is an issue it is a CMake issue but I somehow doubt it. 
` C:\Projects\GTK\VCPKG\buildtrees\zlib\x86-windows-rel\CMakeFiles\3.15.3\CompilerIdC\CMakeCCompilerId.exe` Is a very simple program build using cmake to just identify the used C compiler and in general should mostly contain some macros to do so. If bitdefender is saying it is infected you probably have a serious virus problem on your PC.

**Comment by drescherjm** [comment]
Could also be a false positive on the AV.

**Comment by cbezault** [comment]
Agreed, either CMake is compromised or this is a false positive.

**Comment by fpgaman** [comment]
Hello Neumann-A
"If bitdefender is saying it is infected you probably have a serious virus problem on your PC."
I ran a virus scan with Bitdefender and it comes up clean, and Bitdefender is up to date. Is it possible that there is a hidden virus somewhere in the VCPKG process? If Bitdefender is reporting a false positive, how would I determine that?

**Comment by cbezault** [comment]
The file that bitdefender flagged is not provided by vcpkg. It is provided by Kitware to help CMake determine information about your compiler.

There's a few options here:
1. Kitware is compromised
2. Your desktop/network is compromised
3. This is a false positive (the most likely option I think)

Unless you are a malware/security expert I don't believe you are in a position to determine if this is a false positive. Please contact Bitware support.

**Comment by fpgaman** [comment]
I was able to get VCPkg to run successfully by disabling the Bitdefender virus checker. I am assuming that the virus detection is a false positive.

**Comment by ianmanifacier** [comment]
I had the same problem almost a year later

**Comment by drescherjm** [comment]
You may want to just exclude your whole vcpkg folder from your AV.
