### ISSUE TITLE
[New Port Request] PAPI

### ISSUE THREAD

**Issue by jaeheum** [microsoft/vcpkg#8124]
Library name: PAPI (Performance Application Programming Interface)

Library description: PAPI provides the tool designer and application engineer with a consistent interface and methodology for use of the performance counter hardware found in most major microprocessors. PAPI enables software engineers to see, in near real time, the relation between software performance and processor events.

Source repository URL: https://bitbucket.org/icl/papi.git

Project homepage (if different from the source repository): http://icl.cs.utk.edu/papi/index.html

Anything else that is useful to know when adding (such as optional features the library may have that should be included): besides the libraries, papi comes with binaries (papi_*) that provide useful information to users.

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
