### ISSUE TITLE
Are updates folder and status file neccessary?

### ISSUE THREAD

**Issue by IIFE** [microsoft/vcpkg#8128]
Hi,

When using vcpkg, I've noticed the following items are created/updated:
installed/vcpkg/updates
installed/vcpkg/status

I am currently checking the vcpkg folder into source control (TFS) so that it can be shared with other devs and the build server.

The problem is if I try to run a vcpkg command, those items need to be checked out for edit before the command can be run.

Are those items actually required for any vcpkg command to run correctly? Or can I remove them?

Thanks.

**Comment by PhoebeHui** [comment]
@IIFE, I don't think you need check in installed/vcpkg/updates and installed/vcpkg/status into TFS, you can ignore them, and they will generated when use vcpkg.
you can reference https://github.com/microsoft/vcpkg/blob/master/.gitignore

**Comment by IIFE** [comment]
It appears the installed/vcpkg/status file is required for vcpkg to know what packages are installed.

**Comment by PhoebeHui** [comment]
What are you trying to share in team? the installed package built by vcpkg? or some custome changes in vcpkg?

**Comment by IIFE** [comment]
I'm just checking in the whole vcpkg folder (without buildtrees, downloads, and packages) into TFS so that when another developer gets the code, all they need to do is run vcpkg integrate install. I don't want to export the packages as that will involve changing the project files.

The problem I'm finding is that because the vcpkg folder is checking into TFS, if I attempt to run a command (i.e remove), the command fails because vcpkg is trying to modify files under source control, and those need to be checked out before they can be modified.

I guess this is just an inconvenience of TFS.

Thanks.

**Comment by PhoebeHui** [comment]
@IIFE, yes, installed/vcpkg/status record the status of installed package, when you install a new package or change the status of of one port,  it will add record to this file, so it ask you to checkout this file firstly before modify here. I don't have a good suggestion for this now, you don't want to export the packages, maybe you can try to use git instead.

**Comment by IIFE** [comment]
Git is not an option unfortunately.

I'll close the issue as I don't think there is much more to be done.

Thanks.

**Comment by IIFE** [comment]
Actually a further related question please.

Can you please explain the purpose of the .list files under installed\vcpkg\info.

Thanks.

**Comment by PhoebeHui** [comment]
Looking at the info in .list files under installed\vcpkg\info, which record the heads/libs/dll/tools files for a port, AFAIK, these files will be used when export or remove a port. Please reopen this issue if it still be a question for you.
