### ISSUE TITLE
integrate sqlite3 Failure: error MSB3030

### ISSUE THREAD

**Issue by cxq2003** [Microsoft/vcpkg#813]
After the success install of sqlite3, (.\vcpkg install sqlite3), and integrate (.\vcpkg integrate install).
I new a project “sqlite3Test” of win32 console under vc2017, and add the sqlite3 example from sqlite.org/quickstart.html.
The sqlite3Test.exe is ok, but error MSB3030 show as follow:
....15.0\bin\Microsoft.common.currentVersion.targets(4146,5):error MSB3030: can not copy "l" ,......

**Comment by ras0219-msft** [comment]
Hi cxq2003, could you provide some more details? What is the file that failed to copy?

**Comment by cxq2003** [comment]
The complete error shows:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4146,5): error MSB3030: could not copy “l”，because it could not be found。

The error location of  Microsoft.common.currentVersion.targets(4146,5):
    <Copy
        SourceFiles="@(ReferenceCopyLocalPaths)"
        DestinationFiles="@(ReferenceCopyLocalPaths->'$(OutDir)%(DestinationSubDirectory)%(Filename)%(Extension)')"
        SkipUnchangedFiles="$(SkipCopyUnchangedFiles)"
        OverwriteReadOnlyFiles="$(OverwriteReadOnlyFiles)"
        Retries="$(CopyRetryCount)"
        RetryDelayMilliseconds="$(CopyRetryDelayMilliseconds)"
        UseHardlinksIfPossible="$(CreateHardLinksForCopyLocalIfPossible)"
        UseSymboliclinksIfPossible="$(CreateSymbolicLinksForCopyLocalIfPossible)"
        Condition="'$(UseCommonOutputDirectory)' != 'true'"
            >

**Comment by ras0219-msft** [comment]
By chance, do you have vcpkg in a directory with non-ascii characters in the path?

**Comment by cxq2003** [comment]
c:\vcpkg

**Comment by bagong** [comment]
> By chance, do you have vcpkg in a directory with non-ascii characters in the path?

@ras0219-msft ,  I was about to file an issue for this. It seems all builds fail if non-ascii characters are in the vcpkg- (or build-) path. Is there any way around this. Could you explain what the problem is. I tried the builds both with Ninja and MSbuild. Ninja already fails in the compiler test, and that is a known ninja issue. But MSBuild breaks at the beginning of the build, reproducibly in other build contexts. (see https://gist.github.com/bagong/5fb249e592c3fef8fae20dedbc5f1a2a).

I know this goes away if you move vcpkg to a path that is ascii only, but in certain debug contexts it could be required to build where an application would be used (users don't want to change their name to use an app ;) ). So is there a solution for this?

**Comment by ras0219-msft** [comment]
@bagong We've tried to make things work as well as possible, but unfortunately a lot of the more custom library build systems simply don't handle Unicode (or even just simple spaces!) correctly on Windows :(. Which means that, in the general case, we'll always need to ask users to put vcpkg in a short no-Unicode path, which strongly demotivates any partial fixes. I believe last time we investigated we found that even cmake didn't handle Unicode correctly, but it has been a while so my memory is a bit hazy.

Filing a separate issue would be good for this. I would like to fix it in the long term; it just doesn't seem very fruitful to prioritize over other things for now.

**Comment by bagong** [comment]
> which strongly demotivates any partial fixes

Yes, right! ;) But we all want to get thing done, I see the problem.

> I would like to fix it in the long term; it just doesn't seem very fruitful to prioritize over other things for now.

I understand, and it's only partly in your hands. I think cmake has actually done their part of it since about v3.2, this feels more like a msbuild issue.

Thanks for listening and answering. You're doing a great job!

**Comment by JackBoosY** [comment]
Hi @cxq2003 , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
