### ISSUE TITLE
Create a symlink to vcpkg to access vcpkg globally

### ISSUE THREAD

**Issue by akss13** [microsoft/vcpkg#8133]
****
Automate the creation of symlink of vcpkg file in vcpkg directory on linux machines to access vcpkg globally on system.

**Proposed solution**
Modiy the bootstrap.sh to create symlink in bin directory or in local bin directory

**Comment by PhoebeHui** [comment]
Move the discussion to https://github.com/microsoft/vcpkg/issues/16445.
