### ISSUE TITLE
Building package itk:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by dentx22** [microsoft/vcpkg#8149]
C:\Users\Dentx>C:\tools\vcpkg\vcpkg.exe install itk:x64-windows
The following packages will be built and installed:
    itk[core]:x64-windows
Starting package 1/1: itk:x64-windows
Building package itk[core]:x64-windows...
-- Using cached C:/tools/vcpkg/downloads/InsightSoftwareConsortium-ITK-v5.0.0.t
r.gz
-- Using source at C:/tools/vcpkg/buildtrees/itk/src/v5.0.0-07add98b16
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:58 (message):
    Command failed: C:/tools/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3
14.0-win32-x86/bin/cmake.exe C:/tools/vcpkg/buildtrees/itk/src/v5.0.0-07add98b1
 -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF -DDO_NOT_INSTALL_ITK_TEST_DRIVER=ON -
ITK_INSTALL_DATA_DIR=share/itk/data -DITK_INSTALL_DOC_DIR=share/itk/doc -DITK_I
STALL_PACKAGE_DIR=share/itk -DITK_LEGACY_REMOVE=ON -DITK_FUTURE_LEGACY_REMOVE=O
 -DITK_USE_64BITS_IDS=ON -DITK_USE_CONCEPT_CHECKING=ON -DITK_USE_SYSTEM_EXPAT=O
 -DITK_USE_SYSTEM_JPEG=ON -DITK_USE_SYSTEM_PNG=ON -DITK_USE_SYSTEM_TIFF=ON -DIT
_USE_SYSTEM_ZLIB=ON -DITK_USE_SYSTEM_EIGEN=ON -DITK_FORBID_DOWNLOADS=OFF -DITK_
KIP_PATH_LENGTH_CHECKS=ON -DITK_USE_SYSTEM_HDF5=ON -DModule_ITKVtkGlue=OFF -DMo
ule_IOSTL=ON -DModule_MorphologicalContourInterpolation=ON -DModule_RLEImage=ON
-DGDCM_USE_SYSTEM_OPENJPEG=ON "-DCMAKE_MAKE_PROGRAM=D:/Program Files (x86)/Micr
soft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/
inja/ninja.exe" -DBUILD_SHARED_LIBS=ON -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/tool
/vcpkg/scripts/toolchains/windows.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DVC
KG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=v142 -DCMAKE_EXPORT_NO_PACKAGE_
EGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_
YSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE
VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=C:/tools/v
pkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINAT
ON=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -D
CPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKA
E=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL
LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -G Ninja -DCMAKE_BUILD_TYPE
Debug -DCMAKE_INSTALL_PREFIX=C:/tools/vcpkg/packages/itk_x64-windows/debug
    Working Directory: C:/tools/vcpkg/buildtrees/itk/x64-windows-dbg
    Error code: 1
    See logs for more information:
      C:\tools\vcpkg\buildtrees\itk\config-x64-windows-dbg-out.log
      C:\tools\vcpkg\buildtrees\itk\config-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:299 (vcpkg_execute_required_process

  ports/itk/portfile.cmake:27 (vcpkg_configure_cmake)
  scripts/ports.cmake:74 (include)

Error: Building package itk:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: itk:x64-windows
  Vcpkg version: 2019.07.18-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by PhoebeHui** [comment]
@dentx22, the path with kernel32.lib look like 'C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\x64'  I can't repro your issue, my system drive is C. Could you open x64 Native tools command prompt, and execute 'set lib' command, what's output?

For me:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>set lib
LIB=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\ATLMFC\lib\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\lib\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.7.2\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64;

LIBPATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\ATLMFC\lib\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\lib\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\lib\x86\store\references;C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.18362.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.18362.0;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;

**Comment by dentx22** [comment]
C:\Windows\System32>set lib
LIB=d:\Program Files (x86)\Microsoft Visual Studio\2019\
14.22.27905\ATLMFC\lib\x86;d:\Program Files (x86)\Micros
ommunity\VC\Tools\MSVC\14.22.27905\lib\x86;C:\Program Fi
ETFXSDK\4.7.2\lib\um\x86;D:\Windows Kits\10\lib\10.0.183
 Kits\10\lib\10.0.18362.0\um\x86;
LIBPATH=d:\Program Files (x86)\Microsoft Visual Studio\2
SVC\14.22.27905\ATLMFC\lib\x86;d:\Program Files (x86)\Mi
19\Community\VC\Tools\MSVC\14.22.27905\lib\x86;d:\Progra
Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\l
D:\Windows Kits\10\UnionMetadata\10.0.18362.0;D:\Windows
.18362.0;C:\Windows\Microsoft.NET\Framework\v4.0.30319;
