### ISSUE TITLE
Error: Building package sdl2:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Krautler07** [microsoft/vcpkg#8156]
Hello :)

after succesfully passing the readme instructions through to the package installation, installation " .\vcpkg install sdl2 curl" fails with the following log-report:

[1/2] cmd /c "cd .. && "C:/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe" "C:/vcpkg/buildtrees/sdl2/src/ease-2.0.9-520d112c65" "-DSDL_STATIC=0" "-DSDL_SHARED=1" "-DVIDEO_VULKAN=OFF" "-DFORCE_STATIC_VCRT=0" "-DLIBC=ON" "-DCMAKE_MAKE_PROGRAM=C:/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/vcpkg/packages/sdl2_x86-windows""
FAILED: ../CMakeCache.txt 
cmd /c "cd .. && "C:/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe" "C:/vcpkg/buildtrees/sdl2/src/ease-2.0.9-520d112c65" "-DSDL_STATIC=0" "-DSDL_SHARED=1" "-DVIDEO_VULKAN=OFF" "-DFORCE_STATIC_VCRT=0" "-DLIBC=ON" "-DCMAKE_MAKE_PROGRAM=C:/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/vcpkg/packages/sdl2_x86-windows""
CMake Warning at C:/vcpkg/scripts/buildsystems/vcpkg.cmake:97 (message):
  There are no libraries installed for the Vcpkg triplet x86-windows.
Call Stack (most recent call first):
  C:/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/share/cmake-3.14/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:6 (project)

-- The C compiler identification is MSVC 19.0.24245.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe -- broken
CMake Error at C:/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/share/cmake-3.14/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/vcpkg/buildtrees/sdl2/x86-windows-rel/CMakeFiles/CMakeTmp
    
    Run Build Command(s):C:/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe cmTC_021df 
    [1/2] Building C object CMakeFiles\cmTC_021df.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_021df.exe
    FAILED: cmTC_021df.exe 
    cmd.exe /C "cd . && C:\vcpkg\downloads\tools\cmake-3.14.0-windows\cmake-3.14.0-win32-x86\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_021df.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~2\MICROS~1.0\VC\bin\AMD64_~2\link.exe /nologo CMakeFiles\cmTC_021df.dir\testCCompiler.c.obj  /out:cmTC_021df.exe /implib:cmTC_021df.lib /pdb:cmTC_021df.pdb /version:0.0  /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /foCMakeFiles\cmTC_021df.dir/manifest.res CMakeFiles\cmTC_021df.dir/manifest.rc" failed (exit code 0) with the following output:
    Das System kann die angegebene Datei nicht finden
    ninja: build stopped: subcommand failed.
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:6 (project)

-- Configuring incomplete, errors occurred!
See also "C:/vcpkg/buildtrees/sdl2/x86-windows-rel/CMakeFiles/CMakeOutput.log".
See also "C:/vcpkg/buildtrees/sdl2/x86-windows-rel/CMakeFiles/CMakeError.log".
[2/2] cmd /c "cd ../../x86-windows-dbg && "C:/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe" "C:/vcpkg/buildtrees/sdl2/src/ease-2.0.9-520d112c65" "-DSDL_STATIC=0" "-DSDL_SHARED=1" "-DVIDEO_VULKAN=OFF" "-DFORCE_STATIC_VCRT=0" "-DLIBC=ON" "-DCMAKE_MAKE_PROGRAM=C:/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/vcpkg/packages/sdl2_x86-windows/debug""
FAILED: ../../x86-windows-dbg/CMakeCache.txt 
cmd /c "cd ../../x86-windows-dbg && "C:/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe" "C:/vcpkg/buildtrees/sdl2/src/ease-2.0.9-520d112c65" "-DSDL_STATIC=0" "-DSDL_SHARED=1" "-DVIDEO_VULKAN=OFF" "-DFORCE_STATIC_VCRT=0" "-DLIBC=ON" "-DCMAKE_MAKE_PROGRAM=C:/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/vcpkg/packages/sdl2_x86-windows/debug""
CMake Warning at C:/vcpkg/scripts/buildsystems/vcpkg.cmake:97 (message):
  There are no libraries installed for the Vcpkg triplet x86-windows.
Call Stack (most recent call first):
  C:/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/share/cmake-3.14/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:6 (project)

-- The C compiler identification is MSVC 19.0.24245.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe -- broken
CMake Error at C:/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/share/cmake-3.14/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/vcpkg/buildtrees/sdl2/x86-windows-dbg/CMakeFiles/CMakeTmp
    
    Run Build Command(s):C:/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe cmTC_a7707 
    [1/2] Building C object CMakeFiles\cmTC_a7707.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_a7707.exe
    FAILED: cmTC_a7707.exe 
    cmd.exe /C "cd . && C:\vcpkg\downloads\tools\cmake-3.14.0-windows\cmake-3.14.0-win32-x86\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_a7707.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~2\MICROS~1.0\VC\bin\AMD64_~2\link.exe /nologo CMakeFiles\cmTC_a7707.dir\testCCompiler.c.obj  /out:cmTC_a7707.exe /implib:cmTC_a7707.lib /pdb:cmTC_a7707.pdb /version:0.0  /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /foCMakeFiles\cmTC_a7707.dir/manifest.res CMakeFiles\cmTC_a7707.dir/manifest.rc" failed (exit code 0) with the following output:
    Das System kann die angegebene Datei nicht finden
    ninja: build stopped: subcommand failed.

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:6 (project)

-- Configuring incomplete, errors occurred!
See also "C:/vcpkg/buildtrees/sdl2/x86-windows-dbg/CMakeFiles/CMakeOutput.log".
See also "C:/vcpkg/buildtrees/sdl2/x86-windows-dbg/CMakeFiles/CMakeError.log".
ninja: build stopped: subcommand failed.

Terminal Output:
PS C:\vcpkg> .\vcpkg install sdl2 curl
The following packages will be built and installed:
    curl[core,ssl,winssl]:x86-windows
    sdl2[core]:x86-windows
  * zlib[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: sdl2:x86-windows
Building package sdl2[core]:x86-windows...
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
Please install the English language pack.
-- Using cached C:/vcpkg/downloads/SDL-Mirror-SDL-release-2.0.9.tar.gz
-- Using source at C:/vcpkg/buildtrees/sdl2/src/ease-2.0.9-520d112c65
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: C:/vcpkg/buildtrees/sdl2/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\sdl2\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:296 (vcpkg_execute_required_process)
  ports/sdl2/portfile.cmake:25 (vcpkg_configure_cmake)
  scripts/ports.cmake:85 (include)

Error: Building package sdl2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sdl2:x86-windows
  Vcpkg version: 2019.08.27-nohash

Using Win 10, VSC on latest version
As it looks to me that the compiler is not working properly I already re-installed the compiler several times without complications.

Thanks for the support!

**Comment by PhoebeHui** [comment]
@Krautler07, please install the English language pack and try again, VCPKG required English language pack.

**Comment by deguangchow** [comment]
Why does the English language pack affect compilation?
 It's really puzzling!
@Krautler07

**Comment by deguangchow** [comment]
It works!
Running the following executable file to install the English language pack, and it's necessary to restart the operating system.

 vs_langpack.exe
[https://download.microsoft.com/download/0/2/8/02851F14-44A7-4B31-80F4-E3A428AC58B8/vs_langpack.exe](url)

**Comment by PhoebeHui** [comment]
@deguangchow, see [CHANGELOG.md](https://github.com/microsoft/vcpkg/blob/ab51cc9aa13010d60c4adf2f16578c85b3a4a7b6/CHANGELOG.md):

vcpkg now requires the English language pack of Visual Studio to be installed. This is needed because several libraries fail to build in non-English languages, so vcpkg sets the build environment to English to bypass these issues.

You can also install it by VS installer:
Open VS installer ->Modify->Language packs->English
