### ISSUE TITLE
[qt] update to 5.12.5

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#8157]
since qt 5.12.4 has been merged today we can move on to qt 5.12.5 which was released yesterday. Why did nobody say anything? .... probably a good time to test the update routine I added. I wish there would be a way to automatically update the hashes also.

**Comment by cenit** [comment]
> Just update to qt 5.12.4 several hours ago, may be we should wait for some days.

it took too much time for that update, which was a big "infrastructure" one. I vote for a quick update to 5.12.5 and then let it cool down with bugfix if necessary

**Comment by Neumann-A** [comment]
hmm should i add a feature [latest] to qt which is qt 5.13.1? would require openssl 1.1.1 first. (i assume that it only requires updating the hashes)
