### ISSUE TITLE
[loguru] This port is not a header-only library any more

### ISSUE THREAD

**Issue by eruanno123** [microsoft/vcpkg#8158]
****

**Is your feature request related to a problem? Please describe.**
Since v2.0.0 Loguru is not a header-only library any more. However current port behaves like it is header-only.

**Proposed solution**
Extend existing port so it can generate proper binary output for Loguru 2.0.0. Allow finding Loguru with `find_package`.

**Comment by giellamoswhard** [comment]
I'm stuck with the same problem.
Ubuntu 19.04

**Comment by PhoebeHui** [comment]
@eruanno123, the PR has been merged, please get latest source and try again.

**Comment by virtuosonic** [comment]
I still have this issue on windows with vs. This library isn't header only
