### ISSUE TITLE
Impossible to add a CMake only port

### ISSUE THREAD

**Issue by drdanz** [Microsoft/vcpkg#816]
I would like to package a library that is composed only of CMake modules ([Extra CMake Modules (ECM)](https://api.kde.org/ecm/manual/ecm.7.html)), but there are no include files and vcpkg fails with:
```
The folder /include is empty. This indicates the library was not correctly installed.
```
It would be useful a way to skip this check.

**Comment by alexkaratarakis** [comment]
I will add a policy to skip the /include folder check.
