### ISSUE TITLE
bootstrap  dirs.proj not found

### ISSUE THREAD

**Issue by DogeisReady** [microsoft/vcpkg#8164]
**Describe the bug**
MSBUILD error: Projektdata could not be found
Switch: C:\Windows\system32\vcpkg\toolsrc\dirs.proj

**Environment**
- OS: Windows 10
-Visual Studio 17
-Windows SDK
Both are found by bootstrap.

**To Reproduce**
1.git clone
2.  ./bootstrap-vcpkg.bat or
 ./bootstrap-vcpkg.ps1 -VerbosePS C:\Windows\system32\vcpkg\scripts> .\bootstrap.ps -Verbose

3. Error
AUSFÜHRLICH: Examining C:\Windows\system32\vcpkg\scripts for .vcpkg-root
AUSFÜHRLICH: Examining C:\Windows\system32\vcpkg for .vcpkg-root - Found
AUSFÜHRLICH: VS Candidates:
PreferenceWeight3::StableRelease::15.7.27703.2000::C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
PreferenceWeight1::Legacy::10.0::c:\Program Files (x86)\Microsoft Visual Studio 10.0
AUSFÜHRLICH: Inspecting: PreferenceWeight3::StableRelease::15.7.27703.2000::C:\Program Files (x86)\Microsoft Visual
Studio\2017\Professional
AUSFÜHRLICH: Picking: PreferenceWeight3::StableRelease::15.7.27703.2000::C:\Program Files (x86)\Microsoft Visual
Studio\2017\Professional
AUSFÜHRLICH: Finding WinSDK
AUSFÜHRLICH:
AUSFÜHRLICH: Looking for Windows 10 SDK
AUSFÜHRLICH: C:\Program Files (x86)\Windows Kits\10\Include - Found
AUSFÜHRLICH: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\windows.h - Found
AUSFÜHRLICH: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\sdkddkver.h - Found
AUSFÜHRLICH: Found 10.0.18362.0
AUSFÜHRLICH: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\windows.h - Found
AUSFÜHRLICH: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\shared\sdkddkver.h - Found
AUSFÜHRLICH: Found 10.0.17134.0
AUSFÜHRLICH: C:\Program Files (x86)\Windows Kits\10\Include - Found
AUSFÜHRLICH: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\windows.h - Found
AUSFÜHRLICH: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\sdkddkver.h - Found
AUSFÜHRLICH: Found 10.0.18362.0
AUSFÜHRLICH: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\windows.h - Found
AUSFÜHRLICH: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\shared\sdkddkver.h - Found
AUSFÜHRLICH: Found 10.0.17134.0
AUSFÜHRLICH: C:\Program Files\Windows Kits\10\Include - Not Found
AUSFÜHRLICH: C:\Program Files (x86)\Windows Kits\10\Include - Found
AUSFÜHRLICH: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\windows.h - Found
AUSFÜHRLICH: C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\sdkddkver.h - Found
AUSFÜHRLICH: Found 10.0.18362.0
AUSFÜHRLICH: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\um\windows.h - Found
AUSFÜHRLICH: C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\shared\sdkddkver.h - Found
AUSFÜHRLICH: Found 10.0.17134.0
AUSFÜHRLICH:
AUSFÜHRLICH: Looking for Windows 8.1 SDK
AUSFÜHRLICH: C:\Program Files\Windows Kits\8.1\Include - Not Found
AUSFÜHRLICH: C:\Program Files (x86)\Windows Kits\8.1\Include - Not Found
AUSFÜHRLICH:

AUSFÜHRLICH: The following Windows SDKs were found:
AUSFÜHRLICH: 10.0.18362.0
AUSFÜHRLICH: 10.0.17134.0
AUSFÜHRLICH: 10.0.18362.0
AUSFÜHRLICH: 10.0.17134.0
AUSFÜHRLICH: 10.0.18362.0
AUSFÜHRLICH: 10.0.17134.0
AUSFÜHRLICH: Vorgang "CIM-Instanzen aufzählen" mit den folgenden Parametern durchführen, "'namespaceName' =
root\cimv2,'className' = win32_operatingsystem".
AUSFÜHRLICH: Vorgang "CIM-Instanzen aufzählen" wurde abgeschlossen.

Building vcpkg.exe ...

AUSFÜHRLICH: Clean-Executing: C:\Program Files (x86)\Microsoft Visual
Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe "/p:VCPKG_VERSION=-nohash" "/p:DISABLE_METRICS=0"
/p:Configuration=Release /p:Platform=x86 /p:PlatformToolset=v141 /p:TargetPlatformVersion=10.0.18362.0
/p:PreferredToolArchitecture=x64 /verbosity:minimal /m /nologo "C:\Windows\system32\vcpkg\toolsrc\dirs.proj"
MSBUILD : error MSB1009: Die Projektdatei ist nicht vorhanden.
Schalter: C:\Windows\system32\vcpkg\toolsrc\dirs.proj
AUSFÜHRLICH: Execution terminated with exit code 1.

The env Variable $PROFILE  is empty. As this issue occured and could be resolved by changing the Profile User File. I havent found another similar Issue, if there is already a Solution/Issue im sincerely sorry for my lack of competence finding that Issue/Solution.

The Issue is happening at my Work-Environment, i can only reproduce or execute steps next Monday, since i dont have access to my Laptop during the Weekend.

**Comment by JackBoosY** [comment]
Hi @DogeisReady, does this issue still exist?

**Comment by DogeisReady** [comment]
I did not continue using it, could be still an issue. Did not find a solution

**Comment by JackBoosY** [comment]
Okay, please repoen it if it still exists.
