### ISSUE TITLE
Many ports fail when built as release only

### ISSUE THREAD

**Issue by Rastaban** [microsoft/vcpkg#8165]
Many ports fail when built as release only because the portfile.cmake expects the debug files to exist.  This can be reproduced by adding

`set(VCPKG_BUILD_TYPE release)`

to a triplet file.  See @Neumann-A's PR #6368 as an example.  While none of the CI tested triplets do this, we want to support its use in custom triplets so the failing ports should be addressed.

Attached are the logs from PR #6368, it has a bunch of these types of failures:

```
2019-05-09T19:15:23.2493680Z -- Building C:/vsts/_work/1/s/buildtrees/cppunit/src-x86-windows/cppunit-1.14.0/src/cppunit/cppunit_dll.vcxproj for Release
2019-05-09T19:15:52.8391200Z CMake Error at ports/cppunit/portfile.cmake:45 (file):
2019-05-09T19:15:52.8392138Z   file COPY cannot find
2019-05-09T19:15:52.8393281Z   "C:/vsts/_work/1/s/buildtrees/cppunit/src-x86-windows/cppunit-1.14.0/lib/cppunitd_dll.dll".
```

This should be fixed by adding a if-debug-build check around the copy.

[logs_2661912 (1).zip](https://github.com/microsoft/vcpkg/files/3611653/logs_2661912.1.zip)

**Comment by Rastaban** [comment]
Most of these fixes should be straightforward so it would be great for a new contributor.  If someone has time to really tackle a bunch of them then I encourage them to open a draft PR similar to #6368 that they can use to iterate on finding new failures and then check in the fixes as separate PRs.

**Comment by Neumann-A** [comment]
I am still thinking if we should really fix them or just overwrite the file command with an appropiate fix. 
Alternativly replacing those with a `vcpkg_copy_file_if_configuration` / `vcpkg_install_file_if_configuration` / `vcpkg_rename_file_if_configuration` or similar would also be a way to fix it. Maybe the team could come up with a way it should be handled in general instead of adding a lot of `if() endif()` into the portfiles.

**Comment by Voskrese** [comment]
good idea to sort
I would still physically separate these assemblies
many problems with linking

currently
```
└───x64-windows
    │   files.built
    │
    └───debug
            files.built
```

would be perfect
```
└───x64-windows
    ├───debug
    │       files.built
    │
    └───release
            files.built
```

**Comment by JackBoosY** [comment]
@Neumann-A I agree with you. I think we should provide some functions to solve this problem.

**Comment by PhoebeHui** [comment]
Closing in favor of https://github.com/microsoft/vcpkg/issues/1626.
