### ISSUE TITLE
Upgrade removes packages when vcpkg is not up to date

### ISSUE THREAD

**Issue by carmangary** [microsoft/vcpkg#8167]
On Windows 10, if vcpkg is not build with latest source and an upgrade is attempted of some package,  the package will be removed and an error saying upgrade cannot occur with old version of vcpkg will be presented.

To reproduce:  
1) build some older version of vcpkg by swithing to an older branch 
2) install opencv:x86-windows-static from that same branch
3) git pull to update to current
4) issue vcpkg upgrade.  It will inform you opencv is out of date and mention to use --no-dry-run
5) issue vcpkg upgrade --no-dry-run
6) error message occurs and opencv is no longer installed.  opencv must be reinstalled again

**Comment by degski** [comment]
@PhoebeHui 

This is and stays a big weakness (and intensely irritating, happened again today). I've written some code that does auto-bootstrapping, it works (on Windows). What I would need is some input, and some help from another user to fill in some blanks for nix. I suspect it's simpler on nix as (as far as I know, exe's are writable, contrary to Windows, where the current executable is write-protected, which then requires launching a copy bla bla, yes it's hacky, no way around that as far as I can see). The way the main exe is written (vcpkg.cpp, notably the `inner()` function) makes my solution a bit non-standard (but un-intrusive) for C++). It could be better if `inner ()` was restructured somewhat, for that, some input and coop from a vcpkg-dev would be required (or maybe my solution is judged OKish?).

I've cloned `vcpkg` and added my stuff:

https://github.com/degski/vcpkg/blob/master/toolsrc/include/vcpkg/autobootstrap.h
https://github.com/degski/vcpkg/blob/master/toolsrc/src/vcpkg/autobootstrap.cpp

And then there are 2 additional lines in:

https://github.com/degski/vcpkg/blob/master/toolsrc/src/vcpkg.cpp

**Comment by dan-shaw** [comment]
@carmangary #7201 should fix this. Should be merged soon.

**Comment by carmangary** [comment]
> @carmangary #7201 should fix this. Should be merged soon.

Fantastic!  Thank you for quickly addressing it.

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/4360.
