### ISSUE TITLE
applocal.ps1 failure

### ISSUE THREAD

**Issue by ghost** [microsoft/vcpkg#8169]
**Describe the bug**
/// Package information after "Additional context" (yes, is just one package) ///
By the output window in Visual Studio, it seems vcpkg cannot copy DLLs into the directory in where the executable is, the program can be build but it will have missings DLLs and cannot start. It seems vcpkg cannot copy DLLs because "it doesn't have permission" plus other things. The output of the output window is in "Failure logs".

**Environment**
- OS: Windows 10
- Compiler: I have VS Studio 2019 up to date.

**To Reproduce**
Very easy, trying to solve the problem I erased vcpkg, and reinstalled again, added the library and put the command integrate install. The C++ project was also erased; solution, reference from "recent", everything. Ok, I created a new project and added the .h, .cpp and resource files (images and similar) one by one. Builded and the errors are still there. More information in "Additional context".

**Expected behavior**
Expected the DLLs to be in the directory in which the .exe file is. Basically, to be able to run the program because vcpkg manage that for me.

**Failure logs** 
I attached two images at the bottom.

**Additional context**
Before having errors I created a new user in the computer with administrator rights, now I use only this one, the other user profile still exists. Ok, now, to have everything clean, I erased vcpkg (by "erasing vcpkg" I have been meaning: erase everything, not just the .exe file or something like that) and reinstalled again in the new user. I also created a new project in the new user in VS 2019, which is the same that the other project (by that, I mean it has a copy of the same .h and .cpp files), again, to have everything clean (as new) for the new user. That is the background before the errors. There were no errors before this. That's all.

//////////
Package: SFML:x64-windows [Also, this is the only package I have installed (with it dependencies that were automatically downloaded and installed obviously)]
I am aware that SFML has dependencies, but "basically" the project depends "only on SFML", that is why I said it is just one package.

If you want to build the project, I am going to leave a link to it in my OneDrive, the file is "The program.zip", just add the .h, .cpp and the resource files (images and similar) to a new C++ empty project in Visual Studio. The project properties that were altered are very few:

Configuration properties
----General
--------Output Directory: $(SolutionDir)Binaries\$(Platform)\$(Configuration)\
--------Intermediate Directory: $(SolutionDir)Binaries\Intermediates\$(Platform)\$(Configuration)\
--------C++ Language Standard: C++17
----Advanced
--------Character Set: Use Unicode Character Set
----C/C++
--------Language
------------C++ Language Standard: C++17

I also use a precompiled header, the name is pch.h, the .cpp file is pch.cpp
Project: https://1drv.ms/u/s!AkVRV9eGJ20rgQ4gDg0dhWTZAMwK?e=vfTssP
Run the project in Debug x64

For debugging purposes, if you want the necessary DLLs that the vcpkg apparently cannot copy to the directory of the executable, I also am going to leave a link to my OneDrive for the .zip file for them: https://1drv.ms/u/s!AkVRV9eGJ20rgQ9JqpTUE1YZ9M_S?e=Br2d60

One last thing, the project is a project that you do alongside a book, the book is "SFML Game Development", good book:
> https://www.packtpub.com/game-development/sfml-game-development
> https://github.com/SFML/SFML-Game-Development-Book

![Ouput part 1](https://user-images.githubusercontent.com/53422531/64902959-2363cb00-d66e-11e9-8345-368082f0b621.png)

![Ouput part 2](https://user-images.githubusercontent.com/53422531/64902975-5b6b0e00-d66e-11e9-8ced-d7453c456ddb.png)

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
