### ISSUE TITLE
[openssl:x64-android] make: perl: Command not found

### ISSUE THREAD

**Issue by jomof** [microsoft/vcpkg#8174]
**Host Environment**
- OS: Windows 10
- Compiler: Using clang from Android NDK

**To Reproduce**
- Open powershell 
- ```cd {vcpkg-root}```
- Add a triplet for android (it's just x64-linux.cmake with 
 VCPKG_CMAKE_SYSTEM_NAME=Android)
```
     PS C:\vcpkg> cat .\triplets\x64-android.cmake
       set(VCPKG_TARGET_ARCHITECTURE x64)
       set(VCPKG_CRT_LINKAGE dynamic)
       set(VCPKG_LIBRARY_LINKAGE static)
       set(VCPKG_CMAKE_SYSTEM_NAME Android)
```
- Set path to android NDK. Shouldn't matter which version:
```  
$env:ANDROID_NDK_HOME="C:\Microsoft\AndroidNDK64\android-ndk-r15c\"
```

- Try to build the package:
```
 .\vcpkg.exe install openssl:x64-android
```
- Error from the log:
```
Error from log: make: perl: Command not found
```

**Fix**
```
diff --git a/ports/openssl-unix/portfile.cmake b/ports/openssl-unix/portfile.cmake
index a5915f1b9..f4edba101 100644
--- a/ports/openssl-unix/portfile.cmake
+++ b/ports/openssl-unix/portfile.cmake
@@ -32,7 +32,7 @@ vcpkg_extract_source_archive_ex(
 )

 if(CMAKE_HOST_WIN32)
-    vcpkg_acquire_msys(MSYS_ROOT PACKAGES make)
+    vcpkg_acquire_msys(MSYS_ROOT PACKAGES perl make)
     set(BASH ${MSYS_ROOT}/usr/bin/bash.exe)
     set(MAKE ${MSYS_ROOT}/usr/bin/make.exe)
 else()
```

**Failure logs** 
[install-x64-android-dbg-out.log](https://github.com/microsoft/vcpkg/files/3612901/install-x64-android-dbg-out.log)

**Comment by Voskrese** [comment]
https://github.com/microsoft/vcpkg/blob/28e77c7bd6f0f289e9d99f5135c11b9e60123eba/ports/openssl-unix/portfile.cmake#L14

**Comment by jomof** [comment]
Isn't that finding a Windows Perl not the Msys2 Perl package which is what's needed?

**Comment by Voskrese** [comment]
both are built through MINGW, but in the first case there are additional modules

in General, there is no difference, so it is strange why do not find PERL

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. `x64-android` is a community triplet, and there are no update about this issue for a long time. If there are new process or change of this issue, please reopen this issue.
