### ISSUE TITLE
[New Port Request] WinReg

### ISSUE THREAD

**Issue by GiovanniDicanio** [microsoft/vcpkg#8179]
Library name: WinReg

Library description: High-level C++ wrapper around Windows C-interface Registry API

Source repository URL: https://github.com/GiovanniDicanio/WinReg

Project homepage (if different from the source repository):

Attached are the `CONTROL` and `porfile.cmake` files, compressed in a single .zip file.

[winreg_vcpkg_files.zip](https://github.com/microsoft/vcpkg/files/3613687/winreg_vcpkg_files.zip)

**Comment by AlvinZhangH** [comment]
Hi @GiovanniDicanio, thanks for reporting this issue. The port winreg has been added in #8190. Thanks.

**Comment by GiovanniDicanio** [comment]
Thanks @AlvinZhangH.

**Comment by VideoPlayerCode** [comment]
Great! :) Best C++ registry library on Windows!

**Comment by GiovanniDicanio** [comment]
Thank you very much @VideoPlayerCode! :) Glad you liked it.
