### ISSUE TITLE
abseil, C++17, and cmake variables

### ISSUE THREAD

**Issue by jweg** [microsoft/vcpkg#8181]
Hi,
it seems abseil through vcpkg cannot be used by code compiled as C++17.

The problem is vcpkg compiles abseil with -std=gnu++11. ABI problems ensue (if the user code compiles with, say, -std=c++17 on GCC7, using abseil's detection for <string_view> will choose to typedef absl::string_view to GCC's <string_view> for user code, but use abseil's compatilbility replacement for abseil itself. Calling something like absl::StrCat(std::string("xxx")) then results in interesting crashes -- the two string_view's have the same data members, but the order in memory is flipped)
I could not find a way to force abseil to always choose absl::string_view.

So we can make a custom triplet with "set(VCPKG_CXX_FLAGS -std=c++17)".
Now the option will show up in the command line, but it's superseded by another setting of the -std option:

    /usr/bin/c++ [...] -fPIC -std=c++17 -g [...] -std=gnu++11 [...]

The gnu++11 comes from this code in abseil:
absl/copts/AbseilConfigureCopts.cmake:
    ...
    elseif(NOT "${CMAKE_CXX_STANDARD}")
      message(STATUS "No CMAKE_CXX_STANDARD set, assuming 11")
      set(ABSL_CXX_STANDARD 11)
    else()
      set(ABSL_CXX_STANDARD "${CMAKE_CXX_STANDARD}")
    endif()
ABSL_CXX_STANDARD is later used to explicitly set the CXX_STANDARD property on all abseil targets.

This means setting the compiler options is not enough; I must set the CMake variable
accordingly, or rather, just set the variable and let CMake handle this compiler option.

Note that this is not the same as this issue: https://github.com/microsoft/vcpkg/pull/4374
That was from before vcpkg uses abseil's official cmake support.

Also, I don't think abseil is to blame here: setting the language standard explicitly should be okay, and checking whether the variable is set by the user first seems well-behaved enough.
Instead, vcpkg should make it possible to set CMake variables. From my understanding, that's not possible in a triplet file at the moment. Just setting compiler options seems like coming late after the fact (and potentially after other decisions have been made in the build logic, now based on wrong assumptions).

Is there a way to handle these situations? 

Also, is it me or is all this a bit brittle? I wouldn't even have seen the problem if the member order in the two string_view implementations was the same, but of course any number of much more subtle problems could have arisen. And it makes me wonder how many sleeping ABI problems like that I have between my code and vcpkg libs. Properly setting the C++ standard is just one of many settings. Am I paranoid or is this just C++ and we must live with it?

**Comment by malkia** [comment]
I'm hitting similar issue with vs2017. All our code is compiled with /std:c++17, and when reusing the precompiled from vcpkg abseil library I'm getting this: ```error LNK2019: unresolved external symbol "bool __cdecl absl::flags_internal::AbslParseFlag(class std::basic_string_view<char,struct std::char_traits<char> >,int *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?AbslParseFlag@flags_internal@absl@@YA_NV?$basic_string_view@DU?$char_traits@D@std@@@std@@PEAHPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@@Z) referenced in function "bool __cdecl absl::flags_internal::InvokeParseFlag<int>(class std::basic_string_view<char,struct std::char_traits<char> >,int *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (??$InvokeParseFlag@H@flags_internal@absl@@YA_NV?$basic_string_view@DU?$char_traits@D@std@@@std@@PEAHPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@@Z)
3><scrubbed.exe> : fatal error LNK1120: 1 unresolved externals```

This is due to https://github.com/abseil/abseil-cpp/blob/master/absl/base/config.h#L446 - basically vcpkg compiles this in default mode (e.g. c++11 I guess), while we are compiling (and reusing abseil) in c++17

hence this code (link above) would not work for us: ```#ifdef __has_include
#if __has_include(<string_view>) && __cplusplus >= 201703L
#define ABSL_HAVE_STD_STRING_VIEW 1
#endif
#7643 ```

**Comment by sharpe5** [comment]
I've just hit the exact same problem in MSVC 2017.

Everything works nicely with C++14, but not if the project is set C++17. 

I cannot justify downgrading my entire project to C++17 just to use this library.

**Comment by spindensity** [comment]
After update to the latest, there's a feature named `abseil[c++17]`, but when installing it with the `vcpkg install abseil[c++17]`, some error occurred:

```
Error: <unknown>:1:9: invalid character in feature name (must be lowercase, digits, '-', or '*')
   on expression: "abseil[c++17]"
                           ^
```

**Comment by linquize** [comment]
Let's change the feature name to `cpp17` instead

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
