### ISSUE TITLE
[New Port Request] glade

### ISSUE THREAD

**Issue by sjsam** [microsoft/vcpkg#8182]
I am surprised that glade is not found in **vcpkg search**. 

When **gtk** and **gtkmm** are already in the packages list, there is little reason to omit the much needed glade UI designer since much of the gtk UI development is done through glade.

Kindly add **glade** to the vcpkg libraries.

Library name: glade
Library description:
Source repository URL:
Project homepage (if different from the source repository):
Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
@sjsam, glade not found in vcpkg search that means vcpkg doesn't  support glade now, I edit the title and please fill above information, BTW, you can reference 'Request a new port' template to ask to support a new port.

**Comment by sjsam** [comment]
Thank you for the prompt response. 
Library name         : glade
Library description :  Glade is a RAD tool to enable quick & easy development of user interfaces for the GTK+ toolkit and the GNOME desktop environment.
Source repository URL : https://glade.gnome.org/sources.html 
Project homepage (if different from the source repository) : https://glade.gnome.org/
Anything else that is useful to know when adding (such as optional features the library may have that should be included) : Glade is extensively used these days to simplify the process of application development with Gtk. Since the vcpkg already support Gtk and Gtkmm, it is desired that **glade** is also made available through vcpkg. Kindly add a new port for the same.

**Comment by sjsam** [comment]
Hello, It has been a month since I put the port request. Please, could you give an update on this?

**Comment by JackBoosY** [comment]
@sjsam Since GTK cannot build in Linux, we need to fix GTK first.

**Comment by liberforce** [comment]
> Since GTK cannot build in Linux, we need to fix GTK first.

@JackBoosY :  On Windows, you mean?

BTW, recent GTK+ 3 versions can build using the [meson](http://mesonbuild.com/) build system, avoiding the autotools complexity. That build system only has a dependency on Python 3 and Ninja, so building on Windows should be much simpler, and you won't have to maintain an alternative build system by yourself.

**Comment by JackBoosY** [comment]
@liberforce Thanks for advice, I'll try it later.

**Comment by sjsam** [comment]
Eh! 

> 
> 
> > Since GTK cannot build in Linux, we need to fix GTK first.
> 
> @JackBoosY : On Windows, you mean?
> 
> BTW, recent GTK+ 3 versions can build using the [meson](http://mesonbuild.com/) build system, avoiding the autotools complexity. That build system only has a dependency on Python 3 and Ninja, so building on Windows should be much simpler, and you won't have to maintain an alternative build system by yourself.
> 
> More info in the README of GTK+ 3.24.12:
> https://gitlab.gnome.org/GNOME/gtk/blob/075dcc142aa525778268165095de019b736f3efa/README.win32#L184
Ehh!  I have built gtk on Windows before using a - more or less - official tutorial found at
gnome.org 
But since, the vcpkg already have stable ports to gtk and gtkmm, why is so much delay in adding
glade which is a must have for gtk(mm) developers?

**Comment by afraidofdark** [comment]
It would be awesome to see glade in vcpkg. Without it, distributing the gtk is not complate IMHO. Keep up the good work please.

**Comment by sjsam** [comment]
I am eagerly waiting for an update on this dear VCPKG team !

**Comment by dan-shaw** [comment]
This PR seems to need Meson or pkg-config support improving. Our plan is to wait for #9861 and #10395 to merge before we work on this PR. In the meantime, if anyone is able to get `glade` working somehow, it would be great if you could submit a PR.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.

**Comment by raphaelsom** [comment]
Any updates?
