### ISSUE TITLE
[dcmtk] build failure

### ISSUE THREAD

**Issue by smzahraee** [microsoft/vcpkg#8183]
**Host Environment**
- ubuntu 18.04
- Compiler: gcc

**To Reproduce**
`./vcpkg install dcmtk`

**Failure logs** 
dcmtk/install-x64-linux-dbg-err.log
CMake Warning (dev) at ofstd/libsrc/cmake_install.cmake:41:
  Syntax Warning in cmake code at column 148

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  ofstd/cmake_install.cmake:42 (include)
  cmake_install.cmake:93 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at ofstd/libsrc/cmake_install.cmake:41 (file):
  file INSTALL cannot find
  "/home/mohsen/vcpkg/buildtrees/dcmtk/x64-linux-dbg/lib/libofstd".
Call Stack (most recent call first):
  ofstd/cmake_install.cmake:42 (include)
  cmake_install.cmake:93 (include)

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/dcmtk/portfile.cmake:39 (vcpkg_install_cmake)
  scripts/ports.cmake:91 (include)

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
