### ISSUE TITLE
osg build failure

### ISSUE THREAD

**Issue by ccliuyang** [microsoft/vcpkg#8184]
**Host Environment**
- OS:Ubuntu 18.04.3
- Compiler: gcc 7.4

**To Reproduce**
`./vcpkg install osg`

**Failure logs** 
lib/libosgTextd.so.3.6.4：对‘XML_SetUserData’未定义的引用
lib/libosgTextd.so.3.6.4：对‘XML_ParserFree’未定义的引用
lib/libosgTextd.so.3.6.4：对‘FT_Init_FreeType’未定义的引用
lib/libosgTextd.so.3.6.4：对‘FT_Get_Postscript_Name’未定义的引用
lib/libosgTextd.so.3.6.4：对‘FT_Get_MM_Var’未定义的引用
lib/libosgTextd.so.3.6.4：对‘FT_Get_PS_Font_Info’未定义的引用
lib/libosgTextd.so.3.6.4：对‘FT_Select_Size’未定义的引用
lib/libosgTextd.so.3.6.4：对‘FT_Get_Sfnt_Table’未定义的引用
lib/libosgTextd.so.3.6.4：对‘FT_Get_Char_Index’未定义的引用
lib/libosgTextd.so.3.6.4：对‘XML_ParserCreate’未定义的引用
lib/libosgTextd.so.3.6.4：对‘FT_Get_BDF_Property’未定义的引用
lib/libosgTextd.so.3.6.4：对‘FT_Load_Glyph’未定义的引用
lib/libosgTextd.so.3.6.4：对‘FT_New_Face’未定义的引用
lib/libosgTextd.so.3.6.4：对‘FT_Load_Sfnt_Table’未定义的引用
lib/libosgTextd.so.3.6.4：对‘FT_Has_PS_Glyph_Names’未定义的引用
lib/libosgTextd.so.3.6.4：对‘FT_Get_X11_Font_Format’未定义的引用
lib/libosgTextd.so.3.6.4：对‘FT_Get_Glyph_Name’未定义的引用
lib/libosgTextd.so.3.6.4：对‘XML_GetErrorCode’未定义的引用
lib/libosgTextd.so.3.6.4：对‘XML_GetCurrentLineNumber’未定义的引用
lib/libosgTextd.so.3.6.4：对‘FT_Get_Next_Char’未定义的引用
lib/libosgTextd.so.3.6.4：对‘XML_SetElementHandler’未定义的引用
lib/libosgTextd.so.3.6.4：对‘FT_Get_Sfnt_Name_Count’未定义的引用
lib/libosgTextd.so.3.6.4：对‘FT_Done_Face’未定义的引用
lib/libosgTextd.so.3.6.4：对‘FT_Get_First_Char’未定义的引用
lib/libosgTextd.so.3.6.4：对‘XML_SetCharacterDataHandler’未定义的引用
lib/libosgTextd.so.3.6.4：对‘FT_Get_Sfnt_Name’未定义的引用
lib/libosgTextd.so.3.6.4：对‘XML_GetBuffer’未定义的引用
lib/libosgTextd.so.3.6.4：对‘XML_SetDoctypeDeclHandler’未定义的引用
lib/libosgTextd.so.3.6.4：对‘XML_ParseBuffer’未定义的引用
lib/libosgTextd.so.3.6.4：对‘XML_ErrorString’未定义的引用
lib/libosgTextd.so.3.6.4：对‘FT_Done_FreeType’未定义的引用
lib/libosgTextd.so.3.6.4：对‘FT_Select_Charmap’未定义的引用

**Additional context**
On the linux, I set OSG_USE_UTF8_FILENAME = OFF

**Comment by JackBoosY** [comment]
Related PR: #8060.

**Comment by ccliuyang** [comment]
I use'd your pr, but it occus others problems. There's no this problem of the version of osg 3.6.3 , I compared the file of osgText/CMakeList.text, the different is 

if(OSG_TEXT_USE_FONTCONFIG AND Fontconfig_FOUND)
    MESSAGE(STATUS "osgText will be linked with FontConfig library")
    list(APPEND TARGET_LIBRARIES Fontconfig::Fontconfig)
    ADD_DEFINITIONS(-DWITH_FONTCONFIG)
else()
    MESSAGE(STATUS "osgText will not be linked with FontConfig library")
endif()

On linux, the fontconfig is comiled as static library, If fontconfig comiled as dynamic library, It will linked freetype and libexpat, so it occus this problem, but I don't know how to fix it.

**Comment by JackBoosY** [comment]
@ccliuyang The PR is work in progress now. I'm fixing these issues.

**Comment by JackBoosY** [comment]
Hi @ccliuyang, I've fixed it, please update vcpkg and rebuild osg.

Thanks.
