### ISSUE TITLE
How do I create triplet and cmake inside toolchain directory for arm64 configuration on linux  to insall packages using vcpkg

### ISSUE THREAD

**Issue by singh0506** [microsoft/vcpkg#8185]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).

**Comment by singh0506** [comment]
i have created triplet file as below content
set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Generic)
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE ${CMAKE_CURRENT_LIST_DIR}/../scripts/toolchains/linux-gcc-arm-none-eabi-8-2019-q3-update.cmake)


and also made cmake file as below content

set(tools /home/glider/tools/gcc-arm-none-eabi-8-2019-q3-update)
set(CMAKE_CXX_COMPILER ${tools}/bin/arm-none-eabi-g++)
set(CMAKE_C_COMPILER ${tools}/bin/arm-none-eabi-gcc)
set(CMAKE_NO_SYSTEM_FROM_IMPORTED FALSE)


if(NOT _VCPKG_LINUX_TOOLCHAIN)
set(_VCPKG_LINUX_TOOLCHAIN 1)
if(CMAKE_HOST_SYSTEM_NAME STREQUAL  "Linux")
    set(CMAKE_CROSSCOMPILING ON CACHE BOOL "")
endif()
set(CMAKE_SYSTEM_NAME Generic CACHE STRING "")

string(APPEND CMAKE_EXE_LINKER_FLAGS_INIT " ${VCPKG_LINKER_FLAGS} --specs=nosys.specs -flto -ffreestanding -nostdlib")
string(APPEND CMAKE_C_FLAGS_INIT " -fPIC ${VCPKG_C_FLAGS} -ffreestanding -flto")
string(APPEND CMAKE_CXX_FLAGS_INIT " -fPIC ${VCPKG_CXX_FLAGS} ")
string(APPEND CMAKE_C_FLAGS_DEBUG_INIT " ${VCPKG_C_FLAGS_DEBUG} -ffreestanding -flto")
string(APPEND CMAKE_CXX_FLAGS_DEBUG_INIT " ${VCPKG_CXX_FLAGS_DEBUG} ")
string(APPEND CMAKE_C_FLAGS_RELEASE_INIT " ${VCPKG_C_FLAGS_RELEASE} -ffreestanding -flto")
string(APPEND CMAKE_CXX_FLAGS_RELEASE_INIT " ${VCPKG_CXX_FLAGS_RELEASE} ")
	
endif()



but I am getting error while building gtest as below:
tools/gcc-arm-none-eabi-8-2019-q3-update/bin/arm-none-eabi-g++   -isystem /home/glider/vcpkgforArm/vcpkg/buildtrees/gtest/src/59f4ade3fb-a16f07815b/googletest/include -isystem /home/glider/vcpkgforArm/vcpkg/buildtrees/gtest/src/59f4ade3fb-a16f07815b/googletest -fPIC -g   -Wall -Wshadow -Werror -Wno-error=dangling-else -DGTEST_HAS_PTHREAD=0 -fexceptions -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -std=c++11 -MD -MT googlemock/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.obj -MF googlemock/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.obj.d -o googlemock/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.obj -c /home/glider/vcpkgforArm/vcpkg/buildtrees/gtest/src/59f4ade3fb-a16f07815b/googletest/src/gtest_main.cc
FAILED: googlemock/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.obj 

tools/gcc-arm-none-eabi-8-2019-q3-update/arm-none-eabi/include/c++/8.3.1/limits:363:3: **error: template with C linkage**
   template<typename _Tp>
   ^~~~~~~~


can anyone please help here ?

**Comment by PhoebeHui** [comment]
@singh0506, vcpkg doesn't support this, only support arm-windows, arm64-windows, arm-uwp, arm64-uwp

**Comment by singh0506** [comment]
@PhoebeHui  thanks for your comment, but can't we create custom triplet ? I tried for custom triplet as arm64-linux.

**Comment by Voskrese** [comment]
triplet and toolchain supported
but the port is tested in the working version only on the triplet that is in VCPKG

if you have your own triplet and toolchain you should update the port yourself

**Comment by singh0506** [comment]
created triplet with below content :
----------------------------------------------------------
set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE ${CMAKE_CURRENT_LIST_DIR}/../scripts/toolchains/linux-gcc-arm-none-eabi-8-2019-q3-update.cmake)
-------------------------------------------------------------------------------------------------

And also created cmake file as toolchain as below content:
#set(tools /home/glider/tools/gcc-arm-none-eabi-8-2019-q3-update)
set(CMAKE_CXX_COMPILER /usr/bin/arm-linux-gnueabi-g++)
set(CMAKE_C_COMPILER /usr/bin/arm-linux-gnueabi-gcc)
set(CMAKE_NO_SYSTEM_FROM_IMPORTED FALSE)
set(CMAKE_INCLUDE_PATH /usr/include/tcl8.6)
set(CMAKE_LIBRARY_PATH /usr/lib/tcl8.6)
set(CMAKE_PROGRAM_PATH /usr/bin/tclsh)


if(NOT _VCPKG_LINUX_TOOLCHAIN)
set(_VCPKG_LINUX_TOOLCHAIN 1)
if(CMAKE_HOST_SYSTEM_NAME STREQUAL  "Linux")
    set(CMAKE_CROSSCOMPILING ON CACHE BOOL "")
endif()
set(CMAKE_SYSTEM_NAME  Linux  CACHE STRING "")

string(APPEND CMAKE_EXE_LINKER_FLAGS_INIT " ${VCPKG_LINKER_FLAGS}")
string(APPEND CMAKE_C_FLAGS_INIT " -fPIC ${VCPKG_C_FLAGS}")
string(APPEND CMAKE_CXX_FLAGS_INIT " -fPIC ${VCPKG_CXX_FLAGS} ")
string(APPEND CMAKE_C_FLAGS_DEBUG_INIT " ${VCPKG_C_FLAGS_DEBUG}")
string(APPEND CMAKE_CXX_FLAGS_DEBUG_INIT " ${VCPKG_CXX_FLAGS_DEBUG} ")
string(APPEND CMAKE_C_FLAGS_RELEASE_INIT " ${VCPKG_C_FLAGS_RELEASE}")
string(APPEND CMAKE_CXX_FLAGS_RELEASE_INIT " ${VCPKG_CXX_FLAGS_RELEASE} ")
	
endif()

----------------------------------------------------------------------------------------

But how to update port? can you please suggest?

**Comment by Voskrese** [comment]
firstly, I don't know what you're going to compile, the second is imposed so many patches that there is not disassemble

it is easier to create from scratch your own, separately

all PORT files are here
https://github.com/microsoft/vcpkg/tree/master/ports

**Comment by invy** [comment]
You can create your own triplet, it's not the problem. The bigger problem ist to make ports you need compile for your target architecture.
You also don't need vcpkg.cmake toolchain and you can just use CMAKE_PREFIX_PATH to point cmake to configuration files so it'll be able to find packages.
I even would recomend dropping vcpkg toolchain especially in this case. Just see vcpkg as a tool to automatically build packages you need.

**Comment by Rastaban** [comment]
#7976 may be relevant here.  While we have only a handful of triplets that we run the full CI tests, we want to support custom and community triplets so you can build is any useful configuration.

**Comment by vicroms** [comment]
Hi @singh0506 

You seem to have both a CMake toolchain and a valid triplet file. Based on the output from the logs, it appears that the correct compiler is being invoked and the problem is within the library's code itself. 

```
tools/gcc-arm-none-eabi-8-2019-q3-update/bin/arm-none-eabi-g++   -isystem /home/glider/vcpkgforArm/vcpkg/buildtrees/gtest/src/59f4ade3fb-a16f07815b/googletest/include -isystem /home/glider/vcpkgforArm/vcpkg/buildtrees/gtest/src/59f4ade3fb-a16f07815b/googletest -fPIC -g   -Wall -Wshadow -Werror -Wno-error=dangling-else -DGTEST_HAS_PTHREAD=0 -fexceptions -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -std=c++11 -MD -MT googlemock/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.obj -MF googlemock/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.obj.d -o googlemock/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.obj -c /home/glider/vcpkgforArm/vcpkg/buildtrees/gtest/src/59f4ade3fb-a16f07815b/googletest/src/gtest_main.cc
FAILED: googlemock/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.obj 

tools/gcc-arm-none-eabi-8-2019-q3-update/arm-none-eabi/include/c++/8.3.1/limits:363:3: **error: template with C linkage**
   template<typename _Tp>
   ^~~~~~~~
```

You can find the file where the error occurs and make the necessary changes to fix the compilation error (`<vcpkg_path>/buildtrees/gtest/src/59f4ade3fb-a16f07815b/googletest/src/gtest_main.cc`).

I found the following issue related to that error in GTest's repository, however no fix is available (https://github.com/google/googletest/issues/1372). It would be great if you can solve this issue, and open a pull request against the `google/googletest` repository to fix this issue for all downstream users!

**Comment by PhoebeHui** [comment]
@singh0506, vcpkg currently has triplets\community\arm64-linux.cmake triplet now, please reopen this issue if it doesn't meet your requirements.
