### ISSUE TITLE
[x64-linux dynamic curl] build failure

### ISSUE THREAD

**Issue by mz02005** [microsoft/vcpkg#8195]
**Host Environment**
- OS: ubuntu 18.04
- Compiler: gcc7

**To Reproduce**
Modifiy vcpkg/triplets/x64-linux.cmake, set the 'VCPKG_LIBRARY_LINKAGE' = dynamic
`./vcpkg install --triplet x64-linux curl`

**Failure logs** 
Starting package 1/1: curl:x64-linux
Building package curl[core,openssl,ssl]:x64-linux...
-- Using cached /home/mz/works/vcpkg/downloads/curl-curl-curl-7_65_2.tar.gz
-- Using source at /home/mz/works/vcpkg/buildtrees/curl/src/url-7_65_2-b8c5dc84aa
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Installing: /home/mz/works/vcpkg/packages/curl_x64-linux/share/curl/copyright
-- Performing post-build validation
There should be no empty directories in /home/mz/works/vcpkg/packages/curl_x64-linux
The following empty directories were found:

    /home/mz/works/vcpkg/packages/curl_x64-linux/bin
    /home/mz/works/vcpkg/packages/curl_x64-linux/debug/bin

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/a/dir ${CURRENT_PACKAGES_DIR}/some/other/dir)

Found 1 error(s). Please correct the portfile:
    /home/mz/works/vcpkg/ports/curl/portfile.cmake
-- Performing post-build validation done
Error: Building package curl:x64-linux failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: curl:x64-linux
  Vcpkg version: 2019.09.12-unknownhash

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/7222.
