### ISSUE TITLE
[curl] sFTP protocol not supported

### ISSUE THREAD

**Issue by christophe-calmejane** [microsoft/vcpkg#8196]
Even when installing **curl[non-http]** package for windows, **sFTP** protocol is missing (HTTPS is present though). I don't want to use winssl, I chose the default ssl backend.

Is there any technical reason why all protocols are not enabled when choosing the **non-http** feature for curl port?
Would it be possible to enable sFTP?
Thanks

**Comment by Rastaban** [comment]
Have you tried using `curl[ssh]`?  I that feature will implicitly enable `curl[non-http]` and should enable sFTP.  I don't think there is a technical reason why all protocols are not enabled, it is probably because the features in vcpkg reflect the way the upstream Curl CMake options are set up which do not enable sFTP unless explicitly enabling ssh.

**Comment by christophe-calmejane** [comment]
Unfortunately when you choose curl[tool] is automatically disable libssh2.
I checked the generated cmake cache file, and it says: CMAKE_USE_LIBSSH2:BOOL=OFF
sFTP can only be enabled if libssh2 is used (based on what I can see in cURL source code).

**Comment by christophe-calmejane** [comment]
FYI, I updated to the latest vcpkg today. I've seen that curl is now on v7.66.0 and I'm now able to use sFTP along with curl[non-http], curl[openssl] and curl[ssh].
I don't know if you changed something in the curl port, or if it's just a fix from curl itself, but it looks OK to me now!

**Comment by NancyLi1013** [comment]
Hi @christophe-calmejane  thanks for posting this issue. curl has been updated to version v7.66.0 that fixed many issues. Please refer to this https://curl.haxx.se/changes.html#7_66_0 if you're interested in these changes. This issue has been fixed now. I'll close it.

**Comment by Reckoning47** [comment]
Hello,
It seems I am facing this issue with the current release from vcpkg. Is there a way to get sftp working on the current release 8.17.0?
