### ISSUE TITLE
How to upgrade the built-in cmake version of vcpkg

### ISSUE THREAD

**Issue by zdptrsz** [microsoft/vcpkg#8197]
Vcpkg version: 2019.09.12-nohash
My platform is win10+VS2019. In order to solve the VTK build problem, I upgraded the vcpkg version and executed the .\bootstrap-vcpkg.bat command. But still reported an error, I checked the log, it should be the cmake version is too old, vcpkg how to upgrade the built-in cmake version, it is obvious that cmake.exe is not automatically upgraded, I am in \vcpkg\downloads\tools\
I found the cmake-3.14.0-windows folder, the version number is older, I think I should upgrade it to cmake-3.14.2? How should I enter the command?
I also want to upgrade after tools such as nuget and 7zip. How to solve it?
thank you very much!

**Comment by zdptrsz** [comment]
https://github.com/microsoft/vcpkg/issues/7111
Some people mentioned that he can uninstall or even downgrade cmake.exe version, but did not mention how to do it! This problem has been bothering me for a long time. Please tell me how to uninstall or change the built-in tool version of vcpkg

**Comment by Rastaban** [comment]
See https://github.com/microsoft/vcpkg/blob/master/scripts/vcpkgTools.xml and https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_find_acquire_program.cmake for the two places where vcpkg decides what versions of tools to download.  You should be able to update those locations and it will download as needed on the next run of vcpkg.

**Comment by PhoebeHui** [comment]
@zdptrsz, a exist PR https://github.com/microsoft/vcpkg/pull/7801 to upgrade cmake, you can reference to upgrade it.

**Comment by degski** [comment]
Why not just use the machine installed version iff it is newer than the 'minimum required' one?

**Comment by zdptrsz** [comment]
> Why not just use the machine installed version iff it is newer than the 'minimum required' one?

I can not how to tell vcpkg.Vcpkg would use the built-in cmake tool  automatically.



the log shows:
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - failed
-- Check size of unsigned int
-- Check size of unsigned int - done
-- Using unsigned int
CMake Error at D:/Software/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/share/cmake-3.14/Modules/TestBigEndian.cmake:107 (message):
  TEST_BIG_ENDIAN found no result!
Call Stack (most recent call first):
  Common/Core/CMakeLists.txt:286 (test_big_endian)

**Comment by zdptrsz** [comment]
Thank you for your help.
I modified the documentation https://github.com/microsoft/vcpkg/blob/master/scripts/vcpkgTools.xml
And deleted the downloads/tool folder, it was successful.
Although the strange thing is that the cmake.exe which it used is installed on my machine, not the version of built-in-vcpkg, it can be compiled temporarily.
Thank you very much.

**Comment by zdptrsz** [comment]
[vcpkgTools.zip](https://github.com/microsoft/vcpkg/files/3619842/vcpkgTools.zip)
I modified the  vcpkgTools.xml

**Comment by degski** [comment]
@zdptrsz I was more addressing the vcpkg-devs, I understand you cannot change that.
