### ISSUE TITLE
bootstrap script should check "git" instead of "git.exe"

### ISSUE THREAD

**Issue by ZeppLu** [Microsoft/vcpkg#820]
Since I'm using Windows 10 with WSL installed, I've created a simple batch script `git.bat` to wrap `bash` to run `git` command, and I believe there're a number of people doing the same. So I suggest that [`scripts\bootstrap.ps1`](https://github.com/Microsoft/vcpkg/blob/master/scripts/bootstrap.ps1#L11) script should check `git` rather than a simple `git.exe`

**Comment by alexkaratarakis** [comment]
@ZeppLu Sounds reasonable.
