### ISSUE TITLE
macOS: applocal.py incorrectly tries to copy libraries not from vcpkg installation

### ISSUE THREAD

**Issue by MattGuerrette** [microsoft/vcpkg#8203]
**Describe the bug**
On macOS, the applocal.py post build script attempts to copy libraries that are not linked from vcpkg. This cause a problem during compilation with configured cmake project with Xcode

**Environment**
- OS: macOS
- Compiler: 
Xcode Version 11.0 (11A419c) 
Apple clang version 11.0.0 (clang-1100.0.33.8)

**To Reproduce**
1. ./vcpkg install [any library]
2. Create CMake project with two targets. 
    One being a shared library created using add_library(mySharedLib SHARED xxx)
    Second being a executable target that is a macOS bundled application (.app)
3. Link the library created using add_library into the executable
     target_link_libraries(myBundleApp PRIVATE mySharedLib)
4. Generate Xcode project using CMake and the vcpkg toolchain file
5. Attempt to build the project. An error will be thrown attempting to copy mySharedLib from the vcpkg installation which is **wrong**

**Expected behavior**
In short, the script needs to check if the dependency its attempting to copy is actually part of the vcpkg installation (i.e the user installed it using vcpkg). Otherwise, it should do nothing and expect that the library is being included from elsewhere on the user's system.

**Failure logs** 
python /Users/mguerrette/Development/vcpkg/scripts/buildsystems/osx/applocal.py /Users/mguerrette/Development/Vixen/build/macOS/Debug/VixenTest.app/Contents/MacOS/VixenTest /Users/mguerrette/Development/vcpkg/installed/x64-osx/debug
INFO | fixing executable '/Users/mguerrette/Development/Vixen/build/macOS/Debug/VixenTest.app/Contents/MacOS/VixenTest'
INFO | changing rpath '@rpath/libVixenEngine.dylib' in binary /Users/mguerrette/Development/Vixen/build/macOS/Debug/VixenTest.app/Contents/MacOS/VixenTest
INFO | ensuring directory '/Users/mguerrette/Development/Vixen/build/macOS/Debug/VixenTest.app/Contents/Frameworks' exists: /Users/mguerrette/Development/Vixen/build/macOS/Debug/VixenTest.app/Contents/Frameworks
INFO | copying missing dependency in bundle: libVixenEngine.dylib
INFO | cp: /Users/mguerrette/Development/vcpkg/installed/x64-osx/debug/lib/libVixenEngine.dylib: No such file or directory

ERROR | quitting early: couldn't fix dependency @rpath/libVixenEngine.dylib of /Users/mguerrette/Development/Vixen/build/macOS/Debug/VixenTest.app/Contents/MacOS/VixenTest

**Additional context**
This script as it is currently written assumes all dynamic libraries are linked with use of vcpkg. It needs to be updated because many projects will link using vcpkg libraries as well as other non vcpkg libraries.

**Comment by toloudis** [comment]
I am having the same issue.   ( Additionally, I want to build in a python3 virtual environment but the applocal.py script needs to be invoked with python2.  The generated build.make files just call it with `python applocal...`. )

**Comment by ikoruk** [comment]
Having the same issue, any updates?

**Comment by PhoebeHui** [comment]
cc @seanwarren

**Comment by omartijn** [comment]
For me the following change makes it not fail and create a working bundle:

```diff
diff --git a/scripts/buildsystems/osx/applocal.py b/scripts/buildsystems/osx/applocal.py
index e01223c7e..5237f1fdd 100644
--- a/scripts/buildsystems/osx/applocal.py
+++ b/scripts/buildsystems/osx/applocal.py
@@ -259,6 +259,11 @@ def fix_dependency(binary, dep):
     else:
         return True

+    # if the source path doesn't exist it's probably not a dependency
+    # originating with vcpkg and we should leave it alone
+    if not os.path.exists(qtnamesrc):
+        return True
+
     dep_ok = True
     # check that rpath of 'dep' inside binary has been correctly set
     # (ie: relative to exepath using '@executable_path' syntax)
@@ -417,4 +422,4 @@ def main():


 if __name__ == "__main__":
-    main()
\ No newline at end of file
+    main()
```

It's probably not the cleanest solution, we basically don't do anything if we cannot find the library in the expected location. The assumption made here is that that means that the library didn't originate in vcpkg. This seems to work in practice, but there may be some corner-cases.
