### ISSUE TITLE
[New Port Request] vlc-qt

### ISSUE THREAD

**Issue by how0723** [microsoft/vcpkg#8204]
Library name: vlc-qt

Library description: VLC-Qt - a simple library to connect Qt application with libVLC https://vlc-qt.tano.si

Source repository URL: https://github.com/vlc-qt/vlc-qt

Project homepage (if different from the source repository): https://vlc-qt.tano.si

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
