### ISSUE TITLE
vcpkg integrate install only integrate with preview version of visual studio 2019

### ISSUE THREAD

**Issue by eskech** [microsoft/vcpkg#8215]
If you have both "normal" visual studio 2019 (version: 16.2.5) and the preview version of visual studio 2019 (16.3.0-preview 4.0) the command vcpkg integrate install only integrate
with the preview version.
Not sure how to solve this or what would be the best solution.
integrate with both versions?

**Comment by PhoebeHui** [comment]
@eskech, does this still be a question for you with latest vcpkg?

**Comment by eskech** [comment]
Sorry for the long delay on me getting back to you. I have not testet it in a long time. After the feature I needed was pushed into the 2019 version I have not been running the review version. So You could just close it if I was the only one that reported it.

**Comment by PhoebeHui** [comment]
@eskech, thanks for your reply! we haven't got extra new issue for this, it's a very particular case, and I think it will not be supported for a long time, so closing this now.
