### ISSUE TITLE
[spdlog] arm-linux build failure 

### ISSUE THREAD

**Issue by smzahraee** [microsoft/vcpkg#8216]
**Host Environment**
- OS: [Ubuntu 18.04]
- Compiler: gcc

**To Reproduce**
`./vcpkg install spdlog --triplet arm-linux`

**Failure logs** 
Starting package 1/1: spdlog:arm-linux
Building package spdlog[core]:arm-linux...
-- Using cached /home/mohsen/vcpkg/downloads/gabime-spdlog-v1.3.1.tar.gz
-- Using source at /home/mohsen/vcpkg/buildtrees/spdlog/src/v1.3.1-fef0d0df4a
-- Configuring arm-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: /home/mohsen/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake /home/mohsen/vcpkg/buildtrees/spdlog/src/v1.3.1-fef0d0df4a -DSPDLOG_FMT_EXTERNAL=ON -DSPDLOG_BUILD_BENCH=OFF -DCMAKE_MAKE_PROGRAM=/opt/fslc-wayland/2.7/sysroots/x86_64-fslcsdk-linux/usr/bin/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/opt/fslc-wayland/2.7/sysroots/x86_64-fslcsdk-linux/usr/share/cmake/OEToolchainConfig.cmake -DVCPKG_TARGET_TRIPLET=arm-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/home/mohsen/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_TARGET_ARCHITECTURE=arm -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/mohsen/vcpkg/packages/spdlog_arm-linux/debug
    Working Directory: /home/mohsen/vcpkg/buildtrees/spdlog/arm-linux-dbg
    Error code: 1
    See logs for more information:
      /home/mohsen/vcpkg/buildtrees/spdlog/config-arm-linux-dbg-out.log
      /home/mohsen/vcpkg/buildtrees/spdlog/config-arm-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:305 (vcpkg_execute_required_process)
  ports/spdlog/portfile.cmake:20 (vcpkg_configure_cmake)
  scripts/ports.cmake:91 (include)

Error: Building package spdlog:arm-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: spdlog:arm-linux
  Vcpkg version: 2019.09.12-unknownhash

cat  /home/mohsen/vcpkg/buildtrees/spdlog/config-arm-linux-dbg-err.log
CMake Error at /home/mohsen/vcpkg/scripts/buildsystems/vcpkg.cmake:256 (_find_package):
  Could not find a package configuration file provided by "fmt" with any of
  the following names:

    fmtConfig.cmake
    fmt-config.cmake

  Add the installation prefix of "fmt" to CMAKE_PREFIX_PATH or set "fmt_DIR"
  to a directory containing one of the above files.  If "fmt" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:59 (find_package)

**Additional context**
i am Able to build spdlog with triplet x86-linux
a also built fmt, protobuf, asio whit this configuration

**Comment by JackBoosY** [comment]
Please make sure that `fmt-config.cmake` exists in the path `/home/mohsen/vcpkg/packages/fmt_arm-linux/share/fmt/` first. And set `CMAKE_MODULE_PATH` to `/home/mohsen/vcpkg/installed/arm-linux/share/`.

**Comment by smzahraee** [comment]
> Please make sure that `fmt-config.cmake` exists in the path `/home/mohsen/vcpkg/packages/fmt_arm-linux/share/fmt/` first. And set `CMAKE_MODULE_PATH` to `/home/mohsen/vcpkg/installed/arm-linux/share/`.

first is okay
and who can i set `CMAKE_MODULE_PATH`?

**Comment by JackBoosY** [comment]
@smzahraee you can write it into _YOUR_VCPKG_PATH`/triplets/arm-linux.cmake_.

**Comment by smzahraee** [comment]
with following config in arm-linux 

set(VCPKG_TARGET_ARCHITECTURE arm)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)

set(CMAKE_MODULE_PATH /home/mohsen/vcpkg/installed/arm-linux/share/)
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE /opt/fslc-wayland/2.7/sysroots/x86_64-fslcsdk-linux/usr/share/cmake/OEToolchainConfig.cmake)


failed 

./vcpkg install spdlog --triplet arm-linux
The following packages will be built and installed:
    spdlog[core]:arm-linux
Starting package 1/1: spdlog:arm-linux
Building package spdlog[core]:arm-linux...
CMake Error at scripts/cmake/vcpkg_common_functions.cmake:1 (include):
  include could not find load file:

    execute_process
Call Stack (most recent call first):
  scripts/ports.cmake:90 (include)


Error: Building package spdlog:arm-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: spdlog:arm-linux
  Vcpkg version: 2019.09.12-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by JackBoosY** [comment]
My fault, remove changes from my suggestion and modify _VCPKG_PATH/buildtrees/spdlog/src/SOME_HASH/CMakeLists.txt_ line 59 from `find_package(fmt REQUIRED CONFIG)` to `find_package(fmt REQUIRED PATHS /home/mohsen/vcpkg/packages/fmt_arm-linux/share/fmt/ CONFIG)`.
Or use this [patch](https://github.com/microsoft/vcpkg/files/3625593/fix-cmake-find-path.zip).

It's just for you.

**Comment by smzahraee** [comment]
`find_package(fmt PATHS /home/mohsen/vcpkg/packages/fmt_arm-linux/share/fmt/... NO_DEFAULT_PATH)`
worked for me but what is vcpkg solution?

**Comment by JackBoosY** [comment]
@smzahraee Sorry but `arm-linux` is not an officially supported triplet, so we can't modify it for this triplet.

**Comment by Rastaban** [comment]
We are in the process of adding "community triplets" See PR #7976.  This would be a great candidate for that.  While we don't plan on running the full CI testing suite against `arm-linux` we are interested in making it easy for the community to use vcpkg in these types of scenarios.

**Comment by traversaro** [comment]
I am not sure as I do not know the details of the `arm-linux` triplet, but perhaps this  comment is relevant: https://github.com/microsoft/vcpkg/pull/11323#issuecomment-629813053 .
