### ISSUE TITLE
[protobuf]ubuntu-android build failure

### ISSUE THREAD

**Issue by smzahraee** [microsoft/vcpkg#8218]
**Host Environment**
- OS: [Ubuntu 18.04]
- Compiler: NDK

**To Reproduce**
`./vcpkg install protobuf`

**Failure logs** 
error: undefined reference to '__android_log_write'

with this command:
/opt/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=armv7-none-linux-androideabi21 --gcc-toolchain=/opt/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/opt/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/sysroot  -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -march=armv7-a -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -frtti -fexceptions  -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Qunused-arguments -Wl,-z,noexecstack -Wl,--gc-sections CMakeFiles/protoc.dir/home/mohsen/vcpkg/buildtrees/protobuf/src/v3.9.1-c12428cdd0/src/google/protobuf/compiler/main.cc.o  -o protoc-3.9.1.0  libprotocd.a libprotobufd.a -latomic -lm

**Comment by Rastaban** [comment]
Because we don't have an official android triplet it may be useful if you share that too.

**Comment by vicroms** [comment]
Hi @smzahraee 

I found the following related [issue on the `protobuf` repository](https://github.com/protocolbuffers/protobuf/issues/2719).
