### ISSUE TITLE
[SOCI] Installing the ODBC backend does not allow for MySQL backend

### ISSUE THREAD

**Issue by shogerr** [microsoft/vcpkg#8223]
If a user installs soci with `vcpkg install soci[boost, odbc]`, then the only backends available are empty and odbc. It seems there should still be the default mysql backend available.

mysql does not exist as a feature, so it's not possible to, `vcpkg install soci[mysql]`.

I have not tried `vcpkg install soci[odbc, postgresql]` to see if both backends show up yet.

Either way, this leaves a user unable to install mysql backend, as there is no explicit option for this. Possibly vcpkg maintainers wished the backends to be mutually exclusive for some reason?

**Comment by shogerr** [comment]
I just went in and did a `vckpg install soci[boost]:x86-windows`, and found out only the empty backend is included. This is probably more of a bug than a feature, as it's looking like there is no way to use the mysql backend at when one uses vcpkg for dependency management.

**Comment by NancyLi1013** [comment]
Hi @shogerr 
Thanks for posting this issue.
You want to add `mysql` as a feature and then use `vcokg install socl[mysql] `. Is this right?
As for `boost` feature, what are the expected results that you want to see?

**Comment by shogerr** [comment]
I would have to revisit this issue, but if I recall, I expected some database support to be added if you used `boost`. If I recall, you end up with an unusable installation with `soci[boost]`. That is, you can't make a connection to any database, because no driver support is installed with this package.

Your first statement sounds correct as well. There may be no way to install and use MySQL with the current setup in use. If I get a chances to revisit this, I will comment further.

**Comment by NancyLi1013** [comment]
@shogerr 
Thanks for your above info.
Personally, in current state, if we only build with `boost` feature, the databases are not included now.  
Here are some configure logs when only building with `boost`:
```
Boost: 
-- BOOST_RELEASE_VERSION                    =  
-- BOOST_INCLUDE_DIR                        =  
-- BOOST_LIBRARIES                          =  
-- MySQL: disabled, since WITH_MYSQL=OFF 
-- ODBC: disabled, since WITH_ODBC=OFF 
-- Oracle: disabled, since WITH_ORACLE=OFF 
-- PostgreSQL: disabled, since WITH_POSTGRESQL=OFF 
-- SQLite3: disabled, since WITH_SQLITE3=OFF 
-- Firebird: disabled, since WITH_FIREBIRD=OFF 
-- DB2: disabled, since WITH_DB2=OFF 
```
If we want to use some databases, we might need to use` vcpkg install soci[odbc]` or `vcpkg install soci[sqlite3]`.

For `mysql `feature, it might need to be added in the future.
You mentioned above that we cannot make a connection to any database, since there is no driver installed.
It seems that there are only .lib or .dll files generated if we building with the features.

**Comment by NancyLi1013** [comment]
@shogerr 
Please let me know if you still have questions about this issue.

**Comment by NancyLi1013** [comment]
Closing this issue for now since no response in a long time.
Please feel free to reopen this if is still a problem for you.
