### ISSUE TITLE
[osg-qt] build failure

### ISSUE THREAD

**Issue by ccliuyang** [microsoft/vcpkg#8225]
**Host Environment**
- OS:Ubuntu 18.04.3
- Compiler: gcc 7.4

**To Reproduce**
`./vcpkg install osg-qt`

**Failure logs** 
/usr/bin/ld: 找不到 -lpcre2-16_LIBRARY_DEBUG-NOTFOUND
/usr/bin/ld: 找不到 -llibpq_LIBRARY_DEBUG-NOTFOUND
/usr/bin/ld: 找不到 -lQt5ThemeSupport_LIBRARY_DEBUG-NOTFOUND
/usr/bin/ld: 找不到 -lQt5EventDispatcherSupport_LIBRARY_DEBUG-NOTFOUND
/usr/bin/ld: 找不到 -lQt5PlatformCompositorSupport_LIBRARY_DEBUG-NOTFOUND
/usr/bin/ld: 找不到 -lQt5FontDatabaseSupport_LIBRARY_DEBUG-NOTFOUND

**Comment by JackBoosY** [comment]
I'm fixing osg:x64-linux on #8060, and building osg-qt needs to build osg first. So I am curious how you built osg successfully.
Can you provide the error log?

Thanks.

**Comment by ccliuyang** [comment]
I modify the gdal, osg, osgearth, Just build success on linux, don't test on linux and windows.


diff --git a/ports/gdal/portfile.cmake b/ports/gdal/portfile.cmake
index a336e1f1e..6a8b4a8d5 100644
--- a/ports/gdal/portfile.cmake
+++ b/ports/gdal/portfile.cmake
@@ -346,14 +346,14 @@ elseif (VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Linux" OR VCPKG_CMAKE_SYSTEM_NAME STRE
     set(OUT_PATH_RELEASE ${SOURCE_PATH_RELEASE}/../../make-build-${TARGET_TRIPLET}-release)
     file(MAKE_DIRECTORY ${OUT_PATH_RELEASE})
     vcpkg_execute_required_process(
-      COMMAND "${SOURCE_PATH_RELEASE}/configure" --prefix=${OUT_PATH_RELEASE}
+      COMMAND "${SOURCE_PATH_RELEASE}/configure" --prefix=${OUT_PATH_RELEASE} --enable-static=no --enable-shared=yes  --with-crypto=${CURRENT_INSTALLED_DIR} --with-geos=${CURRENT_INSTALLED_DIR} --with-webp=${CURRENT_INSTALLED_DIR} --with-sqlite3=${CURRENT_INSTALLED_DIR} --with-xml2=${CURRENT_INSTALLED_DIR} --with-curl=${CURRENT_INSTALLED_DIR} --with-expat=${CURRENT_INSTALLED_DIR}  --with-jpeg=${CURRENT_INSTALLED_DIR} --with-libz=${CURRENT_INSTALLED_DIR}  --with-proj=${CURRENT_INSTALLED_DIR} --with-png=${CURRENT_INSTALLED_DIR} 
       WORKING_DIRECTORY ${SOURCE_PATH_RELEASE}
       LOGNAME config-${TARGET_TRIPLET}-rel
     )
 
     message(STATUS "Building ${TARGET_TRIPLET}-rel")
     vcpkg_execute_required_process(
-      COMMAND make
+      COMMAND make -j 16
       WORKING_DIRECTORY ${SOURCE_PATH_RELEASE}
       LOGNAME make-build-${TARGET_TRIPLET}-release
     )
@@ -382,14 +382,14 @@ elseif (VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Linux" OR VCPKG_CMAKE_SYSTEM_NAME STRE
     set(OUT_PATH_DEBUG ${SOURCE_PATH_RELEASE}/../../make-build-${TARGET_TRIPLET}-debug)
     file(MAKE_DIRECTORY ${OUT_PATH_DEBUG})
     vcpkg_execute_required_process(
-      COMMAND "${SOURCE_PATH_DEBUG}/configure" --prefix=${OUT_PATH_DEBUG}
+      COMMAND "${SOURCE_PATH_DEBUG}/configure" --prefix=${OUT_PATH_DEBUG}  --enable-static=no --enable-shared=yes --with-crypto=${CURRENT_INSTALLED_DIR} --with-geos=${CURRENT_INSTALLED_DIR} --with-webp=${CURRENT_INSTALLED_DIR} --with-sqlite3=${CURRENT_INSTALLED_DIR} --with-xml2=${CURRENT_INSTALLED_DIR} --with-curl=${CURRENT_INSTALLED_DIR}  --with-expat=${CURRENT_INSTALLED_DIR}  --with-jpeg=${CURRENT_INSTALLED_DIR} --with-libz=${CURRENT_INSTALLED_DIR} --with-proj=${CURRENT_INSTALLED_DIR} --with-png=${CURRENT_INSTALLED_DIR} 
       WORKING_DIRECTORY ${SOURCE_PATH_DEBUG}
       LOGNAME config-${TARGET_TRIPLET}-debug
     )
 
     message(STATUS "Building ${TARGET_TRIPLET}-dbg")
     vcpkg_execute_required_process(
-      COMMAND make
+      COMMAND make -j 16
       WORKING_DIRECTORY ${SOURCE_PATH_DEBUG}
       LOGNAME make-build-${TARGET_TRIPLET}-debug
     )
diff --git a/ports/osg/CONTROL b/ports/osg/CONTROL
old mode 100644
new mode 100755
diff --git a/ports/osg/collada.patch b/ports/osg/collada.patch
old mode 100644
new mode 100755
diff --git a/ports/osg/portfile.cmake b/ports/osg/portfile.cmake
old mode 100644
new mode 100755
index 8c6b5f299..d9ddd3523
--- a/ports/osg/portfile.cmake
+++ b/ports/osg/portfile.cmake
@@ -10,6 +10,8 @@ vcpkg_from_github(
 	HEAD_REF master
     PATCHES
         collada.patch
+	fix-example-application.patch
+	fix-osgtext.patch
 )
 
 if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
@@ -18,10 +20,18 @@ else()
     set(OSG_DYNAMIC ON)
 endif()
 file(REMOVE ${SOURCE_PATH}/CMakeModules/FindSDL2.cmake)
+set(OSG_USE_UTF8_FILENAME ON)
+if (VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Linux")
+    message("Build osg requires gcc with version higher than 4.7.")
+    set(OSG_USE_UTF8_FILENAME OFF)
+endif()
 vcpkg_configure_cmake(
     SOURCE_PATH ${SOURCE_PATH}
     OPTIONS
-        -DOSG_USE_UTF8_FILENAME=ON
+        -DOSG_USE_UTF8_FILENAME=${OSG_USE_UTF8_FILENAME}
+   	-DDYNAMIC_OPENSCENEGRAPH=${OSG_DYNAMIC}
+	-DDYNAMIC_OPENTHREADS=${OSG_DYNAMIC}
+	-DBUILD_OSG_APPLICATIONS=ON
 )
 
 vcpkg_install_cmake()
@@ -32,16 +42,20 @@ file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/include)
 set(OSG_TOOL_PATH ${CURRENT_PACKAGES_DIR}/tools/osg)
 file(MAKE_DIRECTORY ${OSG_TOOL_PATH})
 
-file(GLOB OSG_TOOLS ${CURRENT_PACKAGES_DIR}/bin/*.exe)
+file(GLOB OSG_TOOLS ${CURRENT_PACKAGES_DIR}/bin/*)
 file(COPY ${OSG_TOOLS} DESTINATION ${OSG_TOOL_PATH})
 file(REMOVE_RECURSE ${OSG_TOOLS})
-file(GLOB OSG_TOOLS_DBG ${CURRENT_PACKAGES_DIR}/debug/bin/*.exe)
+file(GLOB OSG_TOOLS_DBG ${CURRENT_PACKAGES_DIR}/debug/bin/*)
 file(REMOVE_RECURSE ${OSG_TOOLS_DBG})
 
-file(GLOB OSG_PLUGINS_DBG ${CURRENT_PACKAGES_DIR}/debug/bin/osgPlugins-3.6.4/*.dll)
+file(GLOB OSG_PLUGINS_DBG ${CURRENT_PACKAGES_DIR}/debug/lib/osgPlugins-3.6.4/*)
 file(COPY ${OSG_PLUGINS_DBG} DESTINATION ${CURRENT_PACKAGES_DIR}/debug/tools/osg/osgPlugins-3.6.4)
-file(GLOB OSG_PLUGINS_REL ${CURRENT_PACKAGES_DIR}/bin/osgPlugins-3.6.4/*.dll)
+file(GLOB OSG_PLUGINS_REL ${CURRENT_PACKAGES_DIR}/lib/osgPlugins-3.6.4/*)
 file(COPY ${OSG_PLUGINS_REL} DESTINATION ${OSG_TOOL_PATH}/osgPlugins-3.6.4)
+file(COPY ${OSG_PLUGINS_REL} DESTINATION ${CURRENT_PACKAGES_DIR}/bin/osgPlugins-3.6.4)
+file(COPY ${OSG_PLUGINS_DBG} DESTINATION ${CURRENT_PACKAGES_DIR}/debug/bin/osgPlugins-3.6.4)
+
+file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/bin ${CURRENT_PACKAGES_DIR}/debug/bin)
 file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/bin/osgPlugins-3.6.4/)
 file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/bin/osgPlugins-3.6.4/)
 
@@ -55,4 +69,4 @@ file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/lib/pkgconfig ${CURRENT_PACKAGES_DIR
 
 if(VCPKG_LIBRARY_LINKAGE STREQUAL static)
     file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/bin ${CURRENT_PACKAGES_DIR}/debug/bin)
-endif()
\ No newline at end of file
+endif()
diff --git a/ports/osg/static.patch b/ports/osg/static.patch
old mode 100644
new mode 100755
diff --git a/ports/osgearth/portfile.cmake b/ports/osgearth/portfile.cmake
index 8f74dea63..ed33bb4d8 100644
--- a/ports/osgearth/portfile.cmake
+++ b/ports/osgearth/portfile.cmake
@@ -17,6 +17,7 @@ vcpkg_from_github(
     HEAD_REF master
     PATCHES 
 		RocksDB.patch
+		osgearth.patch
 )
 
 vcpkg_configure_cmake(
@@ -33,14 +34,15 @@ set(OSGEARTH_TOOL_PLUGIN_PATH ${OSGEARTH_TOOL_PATH}/${OSG_PLUGINS_SUBDIR})
 file(MAKE_DIRECTORY ${OSGEARTH_TOOL_PATH})
 file(MAKE_DIRECTORY ${OSGEARTH_TOOL_PLUGIN_PATH})
 
-file(GLOB OSGEARTH_TOOLS ${CURRENT_PACKAGES_DIR}/bin/*.exe)
-file(GLOB OSGDB_PLUGINS ${CURRENT_PACKAGES_DIR}/bin/osgdb*.dll)
+file(GLOB OSGEARTH_TOOLS ${CURRENT_PACKAGES_DIR}/bin/*)
+file(GLOB OSGDB_PLUGINS ${CURRENT_PACKAGES_DIR}/lib64/osgdb*)
 
 file(COPY ${OSGEARTH_TOOLS} DESTINATION ${OSGEARTH_TOOL_PATH})
 file(COPY ${OSGDB_PLUGINS} DESTINATION ${OSGEARTH_TOOL_PLUGIN_PATH})
 
-file(REMOVE_RECURSE ${OSGEARTH_TOOLS})
-file(REMOVE_RECURSE ${OSGDB_PLUGINS})
+
+# file(REMOVE_RECURSE ${OSGEARTH_TOOLS})
+# file(REMOVE_RECURSE ${OSGDB_PLUGINS})
 
 #Debug
 file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/include)
@@ -51,15 +53,15 @@ set(OSGEARTH_DEBUG_TOOL_PLUGIN_PATH ${OSGEARTH_DEBUG_TOOL_PATH}/${OSG_PLUGINS_SU
 file(MAKE_DIRECTORY ${OSGEARTH_DEBUG_TOOL_PATH})
 file(MAKE_DIRECTORY ${OSGEARTH_DEBUG_TOOL_PLUGIN_PATH})
 
-file(GLOB OSGEARTH_DEBUG_TOOLS ${CURRENT_PACKAGES_DIR}/debug/bin/*.exe)
-file(GLOB OSGDB_DEBUG_PLUGINS ${CURRENT_PACKAGES_DIR}/debug/bin/osgdb*.dll)
+file(GLOB OSGEARTH_DEBUG_TOOLS ${CURRENT_PACKAGES_DIR}/debug/bin/*)
+file(GLOB OSGDB_DEBUG_PLUGINS ${CURRENT_PACKAGES_DIR}/debug/lib64/osgdb*)
 
 file(COPY ${OSGEARTH_DEBUG_TOOLS} DESTINATION ${OSGEARTH_DEBUG_TOOL_PATH})
 file(COPY ${OSGDB_DEBUG_PLUGINS} DESTINATION ${OSGEARTH_DEBUG_TOOL_PLUGIN_PATH})
 
-file(REMOVE_RECURSE ${OSGEARTH_DEBUG_TOOLS})
-file(REMOVE_RECURSE ${OSGDB_DEBUG_PLUGINS})
-
+# file(REMOVE_RECURSE ${OSGEARTH_DEBUG_TOOLS})
+# file(REMOVE_RECURSE ${OSGDB_DEBUG_PLUGINS})
+file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/bin ${CURRENT_PACKAGES_DIR}/debug/bin)
 
 # Handle copyright
 file(COPY ${SOURCE_PATH}/LICENSE.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/osgearth)

**Comment by ccliuyang** [comment]
osgearth.patch
`diff --git a/CMakeLists.txt b/CMakeLists.txt
index 25b7bff..aff51e1 100755
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -141,7 +141,7 @@ FIND_PACKAGE(GDAL)
 FIND_PACKAGE(GEOS)
 FIND_PACKAGE(Sqlite3)
 FIND_PACKAGE(Poco)
-
+FIND_PACKAGE(OpenSSL)
 FIND_PACKAGE(LevelDB)
 
 SET (WITH_STATIC_ROCKSDB FALSE CACHE BOOL "Use static library of RocksDB")
diff --git a/src/osgEarth/CMakeLists.txt b/src/osgEarth/CMakeLists.txt
index e6a6667..a81e976 100644
--- a/src/osgEarth/CMakeLists.txt
+++ b/src/osgEarth/CMakeLists.txt
@@ -413,7 +413,7 @@ ENDIF(WIN32)
 
 OPTION(NRL_STATIC_LIBRARIES "Link osgEarth against static GDAL and cURL, including static OpenSSL, Proj4, JPEG, PNG, and TIFF." OFF)
 if(NOT NRL_STATIC_LIBRARIES)
-  LINK_WITH_VARIABLES(${LIB_NAME} OSG_LIBRARY OSGUTIL_LIBRARY OSGSIM_LIBRARY OSGTERRAIN_LIBRARY OSGDB_LIBRARY OSGFX_LIBRARY OSGVIEWER_LIBRARY OSGTEXT_LIBRARY OSGGA_LIBRARY OSGSHADOW_LIBRARY OPENTHREADS_LIBRARY CURL_LIBRARY GDAL_LIBRARY OSGMANIPULATOR_LIBRARY)
+  LINK_WITH_VARIABLES(${LIB_NAME} OPENSSL_LIBRARIES OSG_LIBRARY OSGUTIL_LIBRARY OSGSIM_LIBRARY OSGTERRAIN_LIBRARY OSGDB_LIBRARY OSGFX_LIBRARY OSGVIEWER_LIBRARY OSGTEXT_LIBRARY OSGGA_LIBRARY OSGSHADOW_LIBRARY OPENTHREADS_LIBRARY CURL_LIBRARY GDAL_LIBRARY OSGMANIPULATOR_LIBRARY)
 else(NOT NRL_STATIC_LIBRARIES)
   LINK_WITH_VARIABLES(${LIB_NAME} OSG_LIBRARY OSGUTIL_LIBRARY OSGSIM_LIBRARY OSGTERRAIN_LIBRARY OSGDB_LIBRARY OSGFX_LIBRARY OSGVIEWER_LIBRARY OSGTEXT_LIBRARY OSGGA_LIBRARY OSGSHADOW_LIBRARY OPENTHREADS_LIBRARY CURL_LIBRARY GDAL_LIBRARY OSGMANIPULATOR_LIBRARY SSL_EAY_RELEASE LIB_EAY_RELEASE TIFF_LIBRARY PROJ4_LIBRARY PNG_LIBRARY JPEG_LIBRARY)
 endif(NOT NRL_STATIC_LIBRARIES)`

**Comment by JackBoosY** [comment]
Confirmed, fix this issue after osg:x64-linux fixed.
