### ISSUE TITLE
libffi build fails

### ISSUE THREAD

**Issue by navidR** [Microsoft/vcpkg#823]
> C:\Users\navid\AppData\Local\Lib\vcpkg > .\vcpkg.exe install libffi
-- CURRENT_INSTALLED_DIR=C:/Users/navid/AppData/Local/Lib/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/Users/navid/AppData/Local/Lib/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/navid/AppData/Local/Lib/vcpkg/packages/libffi_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/Users/navid/AppData/Local/Lib/vcpkg/buildtrees/libffi
-- CURRENT_PORT_DIR=C:/Users/navid/AppData/Local/Lib/vcpkg/ports/libffi/.
-- Using cached C:/Users/navid/AppData/Local/Lib/vcpkg/downloads/libffi-3.1.zip
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch C:/Users/navid/AppData/Local/Lib/vcpkg/ports/libffi/export-global-data.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/Users/navid/AppData/Local/Lib/vcpkg/ports/libffi/export-global-data.patch done
-- Configuring x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: C:/Users/navid/AppData/Local/Lib/vcpkg/downloads/cmake-3.8.0-rc1-win32-x86/bin/cmake.exe;C:/Users/navid/AppData/Local/Lib/vcpkg/buildtrees/libffi/src/libffi-3.1;-DFFI_CONFIG_FILE=C:/Users/navid/AppData/Local/Lib/vcpkg/ports/libffi/fficonfig.h;-DBUILD_SHARED_LIBS=ON;-DCMAKE_CXX_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP;-DCMAKE_C_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /MP;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DBoost_COMPILER=-vc140;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DCMAKE_TOOLCHAIN_FILE=C:/Users/navid/AppData/Local/Lib/vcpkg/triplets/x86-windows.cmake;-DCMAKE_CXX_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Zi;-DCMAKE_C_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Zi;-DCMAKE_SHARED_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF;-DCMAKE_EXE_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF;-G;Visual Studio 14 2015;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_PREFIX_PATH=C:/Users/navid/AppData/Local/Lib/vcpkg/installed/x86-windows;-DCMAKE_INSTALL_PREFIX=C:/Users/navid/AppData/Local/Lib/vcpkg/packages/libffi_x86-windows
    Working Directory: C:/Users/navid/AppData/Local/Lib/vcpkg/buildtrees/libffi/x86-windows-rel
    See logs for more information:
      C:\Users\navid\AppData\Local\Lib\vcpkg\buildtrees\libffi\config-x86-windows-rel-out.log
      C:\Users\navid\AppData\Local\Lib\vcpkg\buildtrees\libffi\config-x86-windows-rel-err.log

>Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:98 (vcpkg_execute_required_process)
  ports/libffi/portfile.cmake:20 (vcpkg_configure_cmake)
  scripts/ports.cmake:73 (include)

>Error: Building package libffi:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libffi:x86-windows
  Vcpkg version: 0.0.76-c433841ef5bcb42b460b95b48c2d425ebd746e1a

>Additionally, attach any relevant sections from the log files above.
C:\Users\navid\AppData\Local\Lib\vcpkg >

**Comment by navidR** [comment]
config-x86-windows-rel-out.log : 

>-- The C compiler identification is MSVC 19.0.24210.0
-- The CXX compiler identification is MSVC 19.0.24210.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/navid/AppData/Local/Lib/vcpkg/buildtrees/libffi/x86-windows-rel

**Comment by navidR** [comment]
config-x86-windows-rel-err.log :

>CMake Error at CMakeLists.txt:66 (add_library):
  Cannot find source file:

    C:/Users/navid/AppData/Local/Lib/vcpkg/buildtrees/libffi/x86-windows-rel/win32.obj

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: CMake can not determine linker language for target: libffi
CMake Warning:
  Manually-specified variables were not used by the project:

    Boost_COMPILER
    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY
    CMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY
    CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP

**Comment by ras0219-msft** [comment]
As part of libffi's configure step, it appears that it assembles a source and object file via
```cmake
if(CMAKE_SIZEOF_VOID_P EQUAL 4)
    set(ARCH_ASM_NAME win32)
    set(ARCH_ASSEMBLER ml /safeseh)
else()
    set(ARCH_ASM_NAME win64)
    set(ARCH_ASSEMBLER ml64)
endif()

execute_process(
    COMMAND cl /nologo /EP /I. /Iinclude ${CMAKE_SOURCE_DIR}/src/x86/${ARCH_ASM_NAME}.S 
    WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
    OUTPUT_FILE ${ARCH_ASM_NAME}.asm)

# Produced *.asm file could be just added to sources.
# It works in x64 mode, but for some strange reason MASM returns error code when in x86,
# (even though it didn't report any errors and correctly generated object file)
# which in turn causes MSBUILD to stop.
execute_process(
    COMMAND ${ARCH_ASSEMBLER} /c /Zi ${ARCH_ASM_NAME}.asm
    WORKING_DIRECTORY ${CMAKE_BINARY_DIR})
```
I suspect that on your machine, the call to the assembler failed to produce the correct output.

Could you:
1. Confirm that the assembly file was generated. This should be a file called `win32.asm` inside the `x86-windows-rel\` folder.
2. Open a x86 tools developer prompt and run ```ml /safeseh /c /Zi win32.asm``` inside the `x86-windows-rel\` folder. Does it produce a win32.obj? Does it report anything of use?

**Comment by navidR** [comment]
1. Yes.
2. 
>C:\Users\navid\AppData\Local\Lib\vcpkg\buildtrees\libffi\x86-windows-rel > ml /safeseh /c /Zi win32.asm
Microsoft (R) Macro Assembler Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

> Assembling: win32.asm
win32.asm(1) : error A2088:END directive required at end of file

**Comment by navidR** [comment]
I should mention win32.asm is although generated but it is empty , I am trying track down the main issue, if I had any sufficient success I will report.

**Comment by JackBoosY** [comment]
Hi @navidR ,thanks for reporting this issue!
I found nothing wrong with build libffi in latest version. Maybe it's fixed. Could you update vcpkg and repro it?
Thx.

**Comment by JackBoosY** [comment]
Please open a new issue if this is still a problem for you.
Thx.
