### ISSUE TITLE
[vcpkg] If CONTROL has invalid syntax-> Report filepath/name in error

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#8231]
So I changed around 22 control files and got this meaningful error message:
```
$ ./vcpkg.exe install qt5:x64-windows-static
Failed at [G:\vcpkg_test\qt_5.12.4\toolsrc\src\vcpkg\packagespec.cpp(44)] with message:
Contains invalid characters. Only alphanumeric lowercase ASCII characters and dashes are allowed
```
So would it be too much to ask to return the filename with the invalid syntax?

**Comment by Neumann-A** [comment]
It would also be helpful if it would give the line and column number. 

Because it is not obvious to me whats wrong here:
```
Source: ms-stl
Version: 2019-09-17
Homepage: https://github.com/microsoft/STL
Build-Depends: boost
Description: Microsoft's C++ Standard Library
```

**Comment by PhoebeHui** [comment]
@Neumann-A, I met similar issue before. it happened when I wrote Build-Depends in CONTROL file, The space required between 2 ports, and the ports name should be lower case. then solved that issue.

eg, Build-Depends: bzip2, eigen3, liblzma

**Comment by Voskrese** [comment]
https://github.com/microsoft/STL
`boost-math` ?

p.s. `boost (ALL)` \\ `boost (*)` ?

**Comment by Neumann-A** [comment]
@Voskrese: thanks for the comment but already corrected locally :) That was actually the reason I was touching the control file of that port again.

**Comment by Voskrese** [comment]
and yes, if there is a mistake, will be hard to find among ... ports

**Comment by Rastaban** [comment]
I agree that this is *really* annoying.  Internally we pass around the strings so by the time it gets to where the value is being parsed we have lost the file/line information.  I would like the internal representation changed so the strings have diagnostic information attached and the error messages can give context.

**Comment by PhoebeHui** [comment]
I think it has a good support  in vcpkg.json now, I change the name to '3FD', and it reports the following useful information, so I would mark this solved, @Neumann-A, what do you think?

```
PS E:\vcpkg\clean\vcpkg> ./vcpkg install 3fd
Computing installation plan...
Errors occurred while parsing E:\vcpkg\clean\vcpkg\ports\3fd\vcpkg.json
    $.name (an identifier): must be lowercase alphanumeric+hyphens and not reserved (see https://github.com/Microsoft/vcpkg/tree/master/docs/specifications/manifests.md for more information)
Error: failed to load port from E:\vcpkg\clean\vcpkg\ports\3fd
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
```
