### ISSUE TITLE
How do I include a package that uses a package which is also found in vcpkg

### ISSUE THREAD

**Issue by Laro88** [microsoft/vcpkg#8235]
I am using cereal for serialization of objects, and this uses rapidjson internally. I would also like to use rapidjson natively since cereal makes a couple of changes inside its reference to rapidjson.

This results in my linker process freaking out with some defined allready defined and what not.

Is there any way to handle this (lack of proper word) "package reuse"?

**Comment by invy** [comment]
How exactly is your linker freaking out? I could imagine this happens because cereal links statically to rapidjson and you are also linking to it statically. What triplets are involved?

**Comment by degski** [comment]
@invy It's all header only, but cereal uses its own moded internal version (which then clashes with the vcpkg one).

**Comment by invy** [comment]
@degski I see.
Looks like to be known problem:
https://github.com/USCiLab/cereal/issues/121

**Comment by PhoebeHui** [comment]
@Laro88, see cereal issue https://github.com/USCiLab/cereal/issues/121,  you might need to update cereal to point the native rapidjason version that you want, I don't have a good suggestion for this, please let me know if you expect VCPKG to do something here.

**Comment by PhoebeHui** [comment]
@Laro88, feel free reopen this issue if you think vcpkg could do something here.

**Comment by msftradford** [comment]
Hey @PhoebeHui, we just started running into this issue as well. Vcpkg could explicitly define a cereal-flavored namespace for cereal's rapidjson inside of rapidjson.h. This will ensure that it does not conflict with direct rapidjson usage in the same binary. Here is the patch that contains the fix which has been tested with the latest cereal portfile:

```
diff --git a/include/cereal/external/rapidjson/rapidjson.h b/include/cereal/external/rapidjson/rapidjson.h
index 3eefe60a..69b9ed91 100644
--- a/include/cereal/external/rapidjson/rapidjson.h
+++ b/include/cereal/external/rapidjson/rapidjson.h
@@ -115,7 +115,7 @@
     \see CEREAL_RAPIDJSON_NAMESPACE
 */
 #ifndef CEREAL_RAPIDJSON_NAMESPACE
-#define CEREAL_RAPIDJSON_NAMESPACE rapidjson
+#define CEREAL_RAPIDJSON_NAMESPACE cereal::rapidjson
 #endif
 #ifndef CEREAL_RAPIDJSON_NAMESPACE_BEGIN
 #define CEREAL_RAPIDJSON_NAMESPACE_BEGIN namespace CEREAL_RAPIDJSON_NAMESPACE {
```
