### ISSUE TITLE
building opencv with cuda problem

### ISSUE THREAD

**Issue by emregulerr** [microsoft/vcpkg#8236]
http://prntscr.com/p7p88a

**Comment by emregulerr** [comment]
Log file is here...

[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/3626183/config-x86-windows-out.log)

**Comment by Voskrese** [comment]
cuda 10.1+ x86 Installed? 

As far as I understand, the above 5 version is no x86 cuda

**Comment by Voskrese** [comment]
Maybe need to remove the support x86?

**Comment by emregulerr** [comment]
How can I do?

**Comment by JackBoosY** [comment]
Duplicate with #7913.
