### ISSUE TITLE
[New Port Request] <poppler>

### ISSUE THREAD

**Issue by Hideki2103** [microsoft/vcpkg#8238]
Library name:poppler

Library description: a free programming library used to view PDF documents

Source repository URL: https://poppler.freedesktop.org/poppler-0.78.0.tar.xz

Project homepage (if different from the source repository): https://poppler.freedesktop.org

Anything else that is useful to know when adding (such as optional features the library may have that should be included):Installing poppler after installing Qt5 creates a library that allows programmers to easily load and render PDF files.

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now
