### ISSUE TITLE
3 libs needs to update

### ISSUE THREAD

**Issue by whidbey** [microsoft/vcpkg#8240]
1.simpleini =>needs to update ports/simpleini/portfile.cmake
 file(COPY ${SOURCE_PATH}/simpleini.h DESTINATION ${CURRENT_PACKAGES_DIR}/include)
file(COPY ${SOURCE_PATH}/SimpleIni.h DESTINATION ${CURRENT_PACKAGES_DIR}/include)
as linux can't detect simpleini.h 

2.cpp-redis needs to update from  https://github.com/Cylix/cpp_redis to https://github.com/cpp-redis/cpp_redis
3.tacopie needs to update from https://github.com/Cylix/tacopie to https://github.com/cpp-redis/tacopie

thanks.

**Comment by PhoebeHui** [comment]
@whidbey, thanks for reporting this issue, I have summit a update.

**Comment by PhoebeHui** [comment]
The fix has merged.

**Comment by whidbey** [comment]
thanks,but still not work 
this is the error log ,fullly pull the lastest version;

[root@localhost vcpkg]# ./vcpkg install simpleini
The following packages will be built and installed:
    simpleini[core]:x64-linux
Starting package 1/1: simpleini:x64-linux
Building package simpleini[core]:x64-linux...
-- Using cached /root/vcpkg/downloads/brofield-simpleini-fe082fa81f4a55ddceb55056622136be616b3c6f.tar.gz
-- Using source at /root/vcpkg/buildtrees/simpleini/src/be616b3c6f-d6d01d7f61
CMake Error at ports/simpleini/portfile.cmake:12 (file):
  file COPY cannot find
  "/root/vcpkg/buildtrees/simpleini/src/be616b3c6f-d6d01d7f61/Simpleini.h".
Call Stack (most recent call first):
  scripts/ports.cmake:94 (include)

**Comment by whidbey** [comment]
cpp-redis is ok
simpleini is fault.
