### ISSUE TITLE
Some file names downloaded directly are inconsistent with those downloaded using tools.

### ISSUE THREAD

**Issue by deguangchow** [microsoft/vcpkg#8244]
Files downloaded with other tools by copying link paths are different from those downloaded by built-in tools. For example:

> vcpkg install openvpn3
……
> -- Downloading https://github.com/ARMmbed/mbedtls/archive/mbedtls-2.16.2.tar.gz...

**vcpkg\downloads\temp\ARMmbed-mbedtls-mbedtls-2.16.2.tar.gz**
size: 2396(KB)

As it has taken a long time, the downloading operation was interrupted.

Downloading the file with other tools by the Following URL:
[https://github.com/ARMmbed/mbedtls/archive/mbedtls-2.16.2.tar.gz](url)

**vcpkg\downloads\mbedtls-mbedtls-2.16.2.tar.gz**
size: 2396(KB)

Renaming the file name from 'mbedtls-mbedtls-2.16.2.tar.gz' to 'ARMmbed-mbedtls-mbedtls-2.16.2.tar.gz' and do it again:

> vcpkg install openvpn3
……
> -- Using cached F:/github/vcpkg/downloads/ARMmbed-mbedtls-mbedtls-2.16.2.tar.gz
> CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:96 (message):
> File does not have expected hash:
> 
          File path: [ F:/github/vcpkg/downloads/ARMmbed-mbedtls-mbedtls-2.16.2.tar.gz ]
      Expected hash: [ 55af897ea3a1455ec4c16980a504a542333e8465bdf89d77b756e6d9893c394166ec880734ecdb10ec0643ddc828bf21e2dd8891b1b4a431e9c57e63a07915aa ]
        Actual hash: [ c1668de4c067b283a38e5613dd7d2945debd6e885fae807d7d642371d8ccf568d24efd6a1128811fbc713aeada999f854a6f70e73f8215fb886c881266e64354 ]

So, I want to know why it`s different and how to solve it.

**Comment by PhoebeHui** [comment]
@deguangchow, see [vcpkg_from_github.cmake](https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_from_github.cmake#L108)

The download filename defined as ${ORG_NAME}-${REPO_NAME}-${SANITIZED_REF}.tar.gz in vcpkg,
eg: https://github.com/ARMmbed/mbedtls/archive/mbedtls-2.16.2.tar.gz.
Then the name is ARMmbed-mbedtls-mbedtls-2.16.2.tar.gz
