### ISSUE TITLE
realsense2[tools]:x64-windows build failure

### ISSUE THREAD

**Issue by davidbun** [microsoft/vcpkg#8246]
Windows 10 Pro, 64-bits

**To Reproduce**
./vcpkg install realsense2[tools]:x64-windows

**Failure logs** 
-Mismatching number of debug and release binaries. Found 2 for debug but 4 for release.
Debug binaries

    C:/vcpkg/packages/realsense2_x64-windows/debug/lib/realsense-filed.lib
    C:/vcpkg/packages/realsense2_x64-windows/debug/lib/realsense2d.lib

Release binaries

    C:/vcpkg/packages/realsense2_x64-windows/lib/glfw3.lib
    C:/vcpkg/packages/realsense2_x64-windows/lib/realsense-file.lib
    C:/vcpkg/packages/realsense2_x64-windows/lib/realsense2-gl.lib
    C:/vcpkg/packages/realsense2_x64-windows/lib/realsense2.lib

Mismatching number of debug and release binaries. Found 1 for debug but 2 for release.
Debug binaries

    C:/vcpkg/packages/realsense2_x64-windows/debug/bin/realsense2d.dll

Release binaries

    C:/vcpkg/packages/realsense2_x64-windows/bin/realsense2-gl.dll
    C:/vcpkg/packages/realsense2_x64-windows/bin/realsense2.dll

Found 2 error(s). Please correct the portfile:
    C:\vcpkg\ports\realsense2\portfile.cmake
-- Performing post-build validation done
Error: Building package realsense2:x64-windows failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: realsense2:x64-windows
  Vcpkg version: 2019.09.12-nohash

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by davidbun** [comment]
+ latest version ported is 2.22, while the latest version on RealSense site is 2.28 and publicly released one is 2.25

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/7109.
