### ISSUE TITLE
suitesparse installed, umfpack.h not found

### ISSUE THREAD

**Issue by danieltuzes** [microsoft/vcpkg#8257]
**Describe the bug**
I successfully installed suitesparse:x64-windows, but even after reloading all, Visual Studio 2019 (16.2.5) still cannot find the installed package, starting with umpack.h.

Using the following lines in the vcxproj file
```
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <IncludePath>%VCPKG_ROOT%\packages\suitesparse_x64-windows\include\suitesparse;include;$(IncludePath)</IncludePath>
```
with `%VCPKG_ROOT%` pointing to root of the vcpkg directory, I can compile, but IntelliSense still say `cannot oopen source file umfpack.h`

**Environment**
- OS: Windows 10
- Compiler: MSVC++ 14.22 _MSC_VER == 1922

**To Reproduce**
1. ./vcpkg install suitesparse:x64-windows
2. error: `cannot oopen source file umfpack.h`
3. add `%VCPKG_ROOT%\packages\suitesparse_x64-windows\include\suitesparse` to the IncludePath in the project's vcxproj file
4. delete .vs directory
5. Reopen VS and the project file, clear the project
6. IntelliSense still says `cannot oopen source file umfpack.h`, but code compiles

**Expected behavior**
VS finds suitesparse automatically, IntelliSense do so too.

**Comment by danieltuzes** [comment]
I have just tested it on another computer but with the same OS and compiler. The problem occurred on that setup too.

**Comment by LilyWangL** [comment]
Hi @danieltuzes, I can't reproduce this issue locally. Please run this command `.\vcpkg.exe integrate install` and `.\vcpkg.exe integrate project` on vcpkg before creating project. You need restart Visual Studio 2019 after running this command.

Thanks.

**Comment by danieltuzes** [comment]
Hi @LilyWangL 
I run those commands already, I have working FFTW and Boost libs, but I rerun it again. The problem still exists. I just created a test solution and project file with a main.cpp like
```
#include <iostream>
#include <umfpack.h>

int main()
{
    std::cout << "Hello World!\n";
}

```
and it says the same: 

> fatal error C1083: Cannot open include file: 'umfpack.h': No such file or directory

On Debug and Release modes too. Note: bc of openBLAS, only x64 version is available.

**Comment by danieltuzes** [comment]
VS also says:
```
PS C:\local\vcpkg> .\vcpkg.exe integrate project
Created nupkg: C:\local\vcpkg\scripts\buildsystems\vcpkg.C.local.vcpkg.1.0.0.nupkg

With a project open, go to Tools->NuGet Package Manager->Package Manager Console and paste:
    Install-Package vcpkg.C.local.vcpkg -Source "C:\local\vcpkg\scripts\buildsystems"
```
I tried this too, after I didn't succeed with `.\vcpkg.exe integrate install` and `.\vcpkg.exe integrate project`.

**Comment by danieltuzes** [comment]
Now I changed
`#include <umfpack.h>`
to
`#include <suitesparse/umfpack.h>`
and it seems working now. I don't know if I should have used it like that, but now it is working.
