### ISSUE TITLE
[New Port Request] libdivide

### ISSUE THREAD

**Issue by eater-of-souls** [microsoft/vcpkg#8264]
https://github.com/ridiculousfish/libdivide

Optimized integer division

From the readme:

> ```libdivide.h```  is a header-only C/C++ library for optimizing integer division. Integer division is one of the slowest instructions on most CPUs e.g. on current x64 CPUs a 64-bit integer division has a latency of up to 90 clock cycles whereas a multiplication has a latency of only 3 clock cycles. libdivide allows you to replace expensive integer divsion instructions by a sequence of shift, add and multiply instructions that will calculate the integer division much faster.

**Comment by NancyLi1013** [comment]
Hi @eater-of-souls thanks for posting this request. `libdivide` has been added to vcpkg. Please try to update vcpkg and use it.
