### ISSUE TITLE
how to install package to the seperate directories

### ISSUE THREAD

**Issue by suiye223** [microsoft/vcpkg#8265]
I  install several libraries , and they was instlled together in the dir vcpkg\installed\x86-windows\include ,can we install them in seperate dir such as \include\ffmpeg \include\sdl2.
thank you

**Comment by Rastaban** [comment]
Currently vcpkg allows each package to decide if it installs files into the top level include directory or into a subdirectory.  There is not a way to force each of them into their own directory (without modifying every portfile).

However this is a common question/request and we are interested in adding this feature sometime in the future.

**Comment by suiye223** [comment]
thanks very much.
