### ISSUE TITLE
[vcpkg] some vcpkg parts fail due to invocation of vcvarsall.bat when cmd has autorun set up

### ISSUE THREAD

**Issue by chris-morgan** [microsoft/vcpkg#8268]
**Host Environment**

- OS: Windows 10
- Compiler: MSVC 2017.

**To Reproduce**

1. Have similar autorun config to me;
2. `./vcpkg install gtk:x64-windows`

**Failure logs** 
```
[…]
Starting package 1/21: libepoxy:x64-windows
Building package libepoxy[core]:x64-windows...
'"\clink.bat"' is not recognized as an internal or external command,
operable program or batch file.
-- Using cached C:/code/gtk/vcpkg/downloads/anholt-libepoxy-1.5.3.tar.gz
-- Using source at C:/code/gtk/vcpkg/buildtrees/libepoxy/src/1.5.3-d7b9d32fcb
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Configuring x64-windows-dbg
-- Configuring x64-windows-dbg done
-- Package x64-windows-rel
-- Package x64-windows-dbg
Error: Building package libepoxy:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libepoxy:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.
```
**Additional context**

I have `HKEY_CURRENT_USER\Software\Microsoft\Command Processor\Autorun` set to `C:\Users\me\AppData\Local\autorun.cmd`, and that file contains the following:

<pre>
@echo off
set LS_COLORS=<em>[long value, skipping]</em>
chcp 65001 > NUL
doskey /macrofile=%LOCALAPPDATA%\doskey-macros
"%CLINK_DIR%\clink.bat" inject --quiet --profile "%LOCALAPPDATA%\clink"
</pre>

When attempting to install GTK, it failed until I stubbed autorun.cmd out. I’m not actually certain which line caused it to fail, but I’m guessing it was CLINK_DIR, which *is* set in my environment, but I suppose something in the stack resets the environment, causing it to be absent, and the autorun.cmd to fail.

All `cmd` invocations should be run with the `/D` (“Disable execution of AutoRun commands from registry”) option.

**Comment by onting** [comment]
I have same problem please help me!

**Comment by JackBoosY** [comment]
@ras0219-msft Can you have a look?

Thanks.

**Comment by Cheney-W** [comment]
@chris-morgan 
1. When exeute `./vcpkg install xxx`, the script **vcvarsall.bat** will be called for setting the compilation environment. However, when the AutoRun is added into _HKEY_CURRENT_USER\Software\Microsoft\Command Processor_ or _HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor_,  vcvarsall.bat failed to run.
  This is a known issue in VS, and you could get more info from [here](https://developercommunity.visualstudio.com/content/problem/771628/autorun-in-hklmhkcusoftwaremicrosoftcommand-proces.html). 

2. About use **/D** option when call the cmd script, it will affect the execution of **vcvarsall.bat**, then the compilation environment cannot be set successfully.

**Comment by Cheney-W** [comment]
This issue still occurs in the latest vcpkg(2021-08-03-1a6d67b8150e94b7f473c6ab1c0cfd).

**Comment by FrankXie05** [comment]
Fixed by PR https://github.com/microsoft/vcpkg-tool/pull/1201
