### ISSUE TITLE
[New Port Request] libgmp

### ISSUE THREAD

**Issue by pastia** [microsoft/vcpkg#8270]
Library name: libgmp

Library description: The GNU Multiple Precision Arithmetic Library

Source repository URL: https://gmplib.org/

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by degski** [comment]
There is `mpir` if your interested, it's (almost) a drop-in replacement for `gmp`. What's going to be a problem, the same is true for `mpir`, is that to be even slightly usable, mpir (and gmp) need to be compiled for your specific hardware. The current `mpir` is built using 'generic c', this is just utterly slow, and you can just as well implement 'schoolbook' multiplication/division yourself.
