### ISSUE TITLE
fail to upgrade after getting the latest version

### ISSUE THREAD

**Issue by giorgk** [microsoft/vcpkg#8279]
**Describe the bug**
After fetching the latest version (5c5c9ea) I run 
`vcpkg.exe update`
and then 
`vcpkg.exe upgrade`
and I got the following error message:
Failed at [f:\ucdavis\vcpkg\toolsrc\src\vcpkg\packagespec.cpp(44)] with message:
Contains invalid characters. Only alphanumeric lowercase ASCII characters and dashes are allowed

**Environment**
- OS: Windows

**Comment by myd7349** [comment]
Please run `bootstrap-vcpkg.bat` and try again.

**Comment by giorgk** [comment]
This seem to work, however the upgrade seem to have screwed up something so that after `vcpkg integrate install` VS2017 does not find any include file

**Comment by cenit** [comment]
It is possible that the upgrade failed after purging old files. In that case, you don’t have anymore the old libraries installed and you have to reinstall them

**Comment by giorgk** [comment]
I suspect you are right but I cannot confirm as I decided to delete and start with a fresh clone of vcpkg. Yet I was getting the same issue. The reason is that the `vcpkg install boost` for example was installing the x86 and my codes  were looking for the x64 include files. 
Just for completeness I had to go to Properties->VC++Directories and examine the include directories.
