### ISSUE TITLE
openexr build failure

### ISSUE THREAD

**Issue by giorgk** [microsoft/vcpkg#8283]
**Host Environment**
- OS: Windows

**To Reproduce**
I came across this error when I attempted to build any library that depends on openexr such as
`.\vcpkg install osg`, `.\vcpkg install devil[tiff]` and of course `.\vcpkg install openexr`

**Failure logs** 
These are the lines when the openexr installation started
```
Building package openexr[core]:x86-windows...
-- Using cached F:/UCDAVIS/vcpkg/downloads/openexr-openexr-v2.3.0.tar.gz
-- Using source at F:/UCDAVIS/vcpkg/buildtrees/openexr/src/v2.3.0-c9e3a0ec1b
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Restarting Build without parallelism because memory exceeded
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Release --target install -- -v
    Working Directory: F:/UCDAVIS/vcpkg/buildtrees/openexr/x86-windows-rel
    See logs for more information:
      F:\UCDAVIS\vcpkg\buildtrees\openexr\install-x86-windows-rel-out.log
      F:\UCDAVIS\vcpkg\buildtrees\openexr\install-x86-windows-rel-out-1.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/openexr/portfile.cmake:30 (vcpkg_install_cmake)
  scripts/ports.cmake:91 (include)
```
**Additional context**
The file install-x86-windows-rel-out-1.log at the end reports:
LINK : fatal error LNK1104: cannot open file 'IlmBase\ImathTest\ImathTest.exe'
ninja: build stopped: subcommand failed.

**Comment by giorgk** [comment]
By default `.\vcpkg install openexr` attempts to install the x86-windows version which fails.
The x64-windows was installed without any problems. 
I have also found that my antivirus program puts the ImathTest.exe file into quarantine.
However I tried to install it with the protection off and still fails

**Comment by giorgk** [comment]
Closed it accidentally

**Comment by JackBoosY** [comment]
@giorgk I cannot repro your issue. Maybe you didn't completely revoke the isolation of ImathTest.exe.

**Comment by JackBoosY** [comment]
Hi @giorgk Does this issue still bother you?

**Comment by giorgk** [comment]
@JackBoosY 
No, all is good.
Generally I have found that there are other libraries that get stuck when the antivirus is running.
So I try always to remember to deactivate it before compiling anything.
