### ISSUE TITLE
openal-soft  x64 build failure

### ISSUE THREAD

**Issue by mruizf** [microsoft/vcpkg#8284]
**Host Environment**
- OS:  Windows/Linux etc...]
- Compiler: vs2015

**To Reproduce**
`./vcpkg install openal-soft:x64-windows`

**Failure logs** 

` Unable to empty directory: E:/vcpkg/packages/openal-soft_x64-windows
    Files are likely in use.
Error: Building package openal-soft:x64-windows failed with: BUILD_FAILED`

**Comment by JackBoosY** [comment]
This seems to be the path _E:/vcpkg/packages/openal-soft_x64-windows_ files/folders are occupied, please close the process after rebuild `openal-soft`.

Thanks.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
