### ISSUE TITLE
ESP8266Wifi

### ISSUE THREAD

**Issue by moschmdt** [microsoft/vcpkg#8285]
Library name: ESP8266Wifi.h

Library description: 

Source repository URL: https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266WiFi

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by Voskrese** [comment]
?
> Source repository URL:

**Comment by moschmdt** [comment]
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/src/ESP8266WiFi.h

**Comment by Voskrese** [comment]
WiFi module firmware for ESP8266 ?

**Comment by moschmdt** [comment]
most recent

**Comment by Voskrese** [comment]
I asked if it was a separate library... or WiFi module \ driver
And it seems he is going a separate tool chain, platform ESP8266 

> it seems to me that your request is simply inappropriate here

**Comment by NancyLi1013** [comment]
Hi @moschmdt,  thanks for posting this request.
Could you please help make it more clear about this request? 

> I asked if it was a separate library... or WiFi module \ driver
> And it seems he is going a separate tool chain, platform ESP8266
> 
> it seems to me that your request is simply inappropriate here

As @Voskrese  said above, we don't know what you want us to add now.
Only `ESP8266Wifi.h` file?

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
