### ISSUE TITLE
curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104

### ISSUE THREAD

**Issue by korilin** [microsoft/vcpkg#8286]
When I use ``sudo ./bootstrap-vcpkg.sh`` in my debian,  it get a err like this.
I tried switching networks, but it's still useless.

Downloading cmake...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   620    0   620    0     0    823      0 --:--:-- --:--:-- --:--:--   822
 26 35.4M   26 9740k    0     0  11298      0  0:54:51  0:14:42  0:20:09     0
curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104

**Comment by LilyWangL** [comment]
@Rastaban Could you help test this? I can't reproduce it on Linux Ubuntu 18.04.2. And I have no Debian VM.
Thanks.

**Comment by AndrewTsao** [comment]
@arukione  Check you firewall. If you are in China, you need set git http proxy. 请参考 [配置终端代理解决 go get 命令国内无法使用](https://abelsu7.top/2019/05/22/go-get-using-proxy/)

**Comment by PhoebeHui** [comment]
@korilin, does this still be a problem for you?

**Comment by korilin** [comment]
> @korilin, does this still be a problem for you?
I have used @AndrewTsao 's suggestion to solve the problem.
