### ISSUE TITLE
[opengl] build failure - Windows SDK path hardcoded

### ISSUE THREAD

**Issue by AlessandroMenti** [microsoft/vcpkg#8288]
**Host Environment**
- OS: Microsoft Windows 10 1903 (build: 18362.356)
- Compiler: Microsoft Visual Studio 2019

**To Reproduce**
`./vcpkg install opengl`

**Failure logs** 
```
Building package opengl[core]:x64-windows...
CMake Error at ports/opengl/portfile.cmake:20 (message):
  Cannot find Windows 10.0.17763.0 SDK.  File does not exist: C:\Program
  Files (x86)\Windows Kits\10\Lib\10.0.17763.0\um\x64\OpenGL32.Lib
Call Stack (most recent call first):
  scripts/ports.cmake:91 (include)


Error: Building package opengl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opengl:x64-windows
  Vcpkg version: 2019.09.12-nohash
```

**Additional context**
The portfiles for OpenGL hardcode the Windows 8 and 10 SDK paths:

```
    vcpkg_get_program_files_32_bit(PROGRAM_FILES_32_BIT)
    vcpkg_get_windows_sdk(WINDOWS_SDK)

    if (WINDOWS_SDK MATCHES "10.")
        set(LIBGLFILEPATH  "${PROGRAM_FILES_32_BIT}\\Windows Kits\\10\\Lib\\${WINDOWS_SDK}\\um\\${TRIPLET_SYSTEM_ARCH}\\OpenGL32.Lib")
        set(LIBGLUFILEPATH "${PROGRAM_FILES_32_BIT}\\Windows Kits\\10\\Lib\\${WINDOWS_SDK}\\um\\${TRIPLET_SYSTEM_ARCH}\\GlU32.Lib")
        set(HEADERSPATH    "${PROGRAM_FILES_32_BIT}\\Windows Kits\\10\\Include\\${WINDOWS_SDK}\\um")
    elseif(WINDOWS_SDK MATCHES "8.")
        set(LIBGLFILEPATH  "${PROGRAM_FILES_32_BIT}\\Windows Kits\\8.1\\Lib\\winv6.3\\um\\${TRIPLET_SYSTEM_ARCH}\\OpenGL32.Lib")
        set(LIBGLUFILEPATH "${PROGRAM_FILES_32_BIT}\\Windows Kits\\8.1\\Lib\\winv6.3\\um\\${TRIPLET_SYSTEM_ARCH}\\GlU32.Lib")
        set(HEADERSPATH    "${PROGRAM_FILES_32_BIT}\\Windows Kits\\8.1\\Include\\um")
    else()
        message(FATAL_ERROR "Portfile not yet configured for Windows SDK with version: ${WINDOWS_SDK}")
    endif()
```

This assumes that the Windows SDK is always installed in the default path, which might not always be the case (on my machine, it was installed into `D:\Program Files (x86)\Windows Kits\10`, hence the error).

From a quick search, the issue seems to also affect the `wincrypt` and `winsock2` ports.

A possible fix (at least for the Windows 10 SDK) would be to have CMake read the installation path from `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Kits\Installed Roots` (value name: `KitsRoot10`) and to use it instead of the hardcoded one - I can draft a PR if needed.

**Comment by PhoebeHui** [comment]
@AlessandroMenti, thanks for reporting this issue, could you summit a PR for this?

**Comment by Neumann-A** [comment]
Do you also know how to solve it in qmake's syntax/*.prl files (#7675)

**Comment by Voskrese** [comment]
**cmake**

`get_filename_component(WINDOWS_KIT_10_PATH "[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows Kits\\Installed Roots;KitsRoot10]" ABSOLUTE CACHE)`

> C:\Program Files (x86)\Windows Kits\10\

> 
`get_filename_component(WINDOWS_KIT_81_PATH "[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows Kits\\Installed Roots;KitsRoot81]" ABSOLUTE CACHE)`

or 

7.1
`get_filename_component(WINDOWS_KIT_71_PATH "[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\Windows\v7.1;InstallationFolder]" ABSOLUTE CACHE)`

8.0
`get_filename_component(WINDOWS_KIT_80_PATH "[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\Windows\v8.0;InstallationFolder]" ABSOLUTE CACHE)`

8.1
`get_filename_component(WINDOWS_KIT_81_PATH "[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\Windows\v8.1;InstallationFolder]" ABSOLUTE CACHE)`

10.0
`get_filename_component(WINDOWS_KIT_10_PATH "[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\Windows\v10.0;InstallationFolder]" ABSOLUTE CACHE)`

> C:\Program Files (x86)\Windows Kits\10\

**Comment by Voskrese** [comment]
to locate system libraries) `CMAKE_STANDARD_LIBRARIES`
it is enough to include them in the build system, in the CMAKE parameters

`list(APPEND CMAKE_STANDARD_LIBRARIES ...` ?

**Comment by Voskrese** [comment]
https://cmake.org/cmake/help/latest/variable/CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION.html

> set a CMAKE_WINDOWS_KITS_10_DIR environment variable

> look for Windows 10 SDKs in a custom location

**Comment by AlessandroMenti** [comment]
@PhoebeHui: of course!
@Neumann-A: I'll have to check that issue first.
@Voskrese: thanks for the inputs!

I've started working on a PR for this, see #8329 - I'll improve it in the next days.

**Comment by Voskrese** [comment]
https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_get_windows_sdk.cmake

```
# Returns Windows SDK number via out variable "ret"
function(vcpkg_get_windows_sdk ret)
    set(WINDOWS_SDK $ENV{WindowsSDKVersion})
    string(REPLACE "\\" "" WINDOWS_SDK "${WINDOWS_SDK}")
    set(${ret} ${WINDOWS_SDK} PARENT_SCOPE)
endfunction()
```

$ENV{WindowsSDKVersion}

open `C:\Program Files (x86)\Microsoft Visual ...\...\...\Common7\Tools\vsdevcmd\core\winsdk.bat`

```
set WindowsSdkDir=
set WindowsLibPath=
set WindowsSDKVersion=
set WindowsSDKLibVersion=
set WindowsSdkBinPath=
set UCRTVersion=
set UniversalCRTSdkDir=
set WindowsSDKVerBinPath=
```

version - `vcpkg_get_windows_sdk_version(WINDOWS_SDK)`
```
function(vcpkg_get_windows_sdk_version ret)
    set(WINDOWS_SDK $ENV{WindowsSDKVersion})
    string(REPLACE "\\" "" WINDOWS_SDK "${WINDOWS_SDK}")
    set(${ret} ${WINDOWS_SDK} PARENT_SCOPE)
endfunction()
```

> echo %WindowsSDKVersion%
> 10.0.17763.0\

dir - `vcpkg_get_windows_sdk_dir(WINDOWS_SDK)`
```
function(vcpkg_get_windows_sdk_dir ret)
    set(WINDOWS_SDK $ENV{WindowsSDKVersion})
    string(REPLACE "\\" "" WINDOWS_SDK "${WINDOWS_SDK}")
    set(${ret} ${WINDOWS_SDK} PARENT_SCOPE)
endfunction()
```

> echo %WindowsSDKDir%
> C:\Program Files (x86)\Windows Kits\10\

**Comment by ras0219** [comment]
I think the best approach here would be to run a CMake build that simply performs something like
```
project(opengl NONE)
find_library(OGL opengl32)
install(FILES ${OGL} DESTINATION lib)
```

This should correctly find opengl from whichever windows sdk we're using to configure cmake projcets.

**Comment by Neumann-A** [comment]
>This should correctly find opengl from whichever windows sdk we're using to configure cmake projcets.

Probably needs an opengl selector somehow since opengl32 from the windows sdk is not the only possibility if mesa is installed
