### ISSUE TITLE
How do I get the latest code on github.

### ISSUE THREAD

**Issue by ava-YangL** [microsoft/vcpkg#8291]
When I use `vcpkg_from_github` in https://github.com/microsoft/vcpkg/pull/8233 , e.g.

    vcpkg_from_github( 
        OUT_SOURCE_PATH SOURCE_PATH
        REPO chokkan/crfsuite
        REF 0.12
        SHA512 7cb02c1ac72613bafd639e1ef9a7ce7ddb0d36b2e7038c45f9745ad177344c3f20c7df48dfc1bdce364af1d0a85957a918ed8fee078232d5a2c91ab3796ee7f0
        HEAD_REF master)

The code will be downloaded from Downloading https://github.com/chokkan/crfsuite/archive/0.12.tar.gz, which is different from the code in https://github.com/chokkan/crfsuite. 
For example, the os.h file under include.
Could you please tell me how to get the latest code via `vcpkg_from_github`?
Thanks.

**Comment by LilyWangL** [comment]
Hi @ava-YangL, you can get the latest code from latest commit on crfsuite source page(https://github.com/chokkan/crfsuite/commits/master). You need modify verison in CONTROL file and REF in portfile.cmake, See more information here:
https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/control-files.md#version
https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_from_github.md#ref

**Comment by ava-YangL** [comment]
It works! Thanks Lily  👍 👍
