### ISSUE TITLE
pkg restclient-cpp can not resolve symbol 

### ISSUE THREAD

**Issue by how0723** [microsoft/vcpkg#8294]
**Describe the bug**
1>main.obj : error LNK2019: 无法解析的外部符号 "struct RestClient::Response __cdecl RestClient::get(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?get@RestClient@@YA?AUResponse@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)，该符号在函数 main 中被引用
can not resolve symbol 

**Environment**
- OS: win10 x64
- Compiler: msvc2017

**To Reproduce**
1. ./vcpkg install restclient-cpp:x64
2. See error
Repro code when

**Expected behavior**

**Failure logs** 
 error LNK2019: 无法解析的外部符号 "struct RestClient::Response __cdecl RestClient::get(class std::basic_string<char,struct std::char_traits,class std::allocator > const &)" (?get@RestClient@@ya?AUResponse@1@AEBV?$basic_string@DU?$char_traits@D@std@@v?$allocator@D@2@@std@@@z)，该符号在函数 main 中被引用

**Additional context**

**Comment by Voskrese** [comment]
> Failure logs
> -(please attached failure logs)

**Comment by how0723** [comment]
@Voskrese not build failure. I use it in vs2017 and not work well.  shows ：error LNK2019: 无法解析的外部符号 "struct RestClient::Response __cdecl RestClient::get(class std::basic_string<char,struct std::char_traits,class std::allocator > const &)" (?get@RestClient@@ya?AUResponse@1@AEBV?$basic_string@DU?$char_traits@D@std@@v?$allocator@D@2@@std@@@z)，该符号在函数 main 中被引用

无法解析的外部符号 means can not resolve symbol

**Comment by how0723** [comment]
@Voskrese restclient-cpp  build success

**Comment by Voskrese** [comment]
static or dynamik ?
(please attached failure logs) !!!

**Comment by how0723** [comment]
@Voskrese  dynamik

**Comment by Voskrese** [comment]
> you understand, there is too little source data, it is very difficult to understand what you are doing and what you are compiling
> 
> without input  source data, nothing is clear

**Comment by scholervb** [comment]
i tried building x86 and x64 ones today, seems they are successfully build.

**vcpkg.exe install restclient-cpp
vcpkg.exe install restclient-cpp:x64-windows**

Computing installation plan...
The following packages will be built and installed:
  * curl[core,non-http,ssl,sspi,winssl]:x64-windows
    restclient-cpp[core]:x64-windows
  * zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: zlib:x64-windows
Building package zlib[core]:x64-windows...
-- Using cached D:/AAD/abc/vcpkg-master/downloads/zlib1211.tar.gz
-- Using source at D:/AAD/abc/vcpkg-master/buildtrees/zlib/src/1.2.11-deec42f53b
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/AAD/abc/vcpkg-master/packages/zlib_x64-windows/share/zlib/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package zlib[core]:x64-windows... done
Installing package zlib[core]:x64-windows...
Installing package zlib[core]:x64-windows... done
Elapsed time for package zlib:x64-windows: 32.67 s
Starting package 2/3: curl:x64-windows
Building package curl[core,non-http,ssl,sspi,winssl]:x64-windows...
-- Using cached D:/AAD/abc/vcpkg-master/downloads/curl-curl-5a1fc8d33808d7b22f57bdf9403cda7ff07b0670.tar.gz
-- Using source at D:/AAD/abc/vcpkg-master/buildtrees/curl/src/7ff07b0670-12eb9d7696
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/AAD/abc/vcpkg-master/packages/curl_x64-windows/share/curl/curl-config
-- Installing: D:/AAD/abc/vcpkg-master/packages/curl_x64-windows/share/curl/vcpkg-cmake-wrapper.cmake
-- Installing: D:/AAD/abc/vcpkg-master/packages/curl_x64-windows/share/curl/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package curl[core,non-http,ssl,sspi,winssl]:x64-windows... done
Installing package curl[core,non-http,ssl,sspi,winssl]:x64-windows...
Installing package curl[core,non-http,ssl,sspi,winssl]:x64-windows... done
Elapsed time for package curl:x64-windows: 4.661 min
Starting package 3/3: restclient-cpp:x64-windows
Building package restclient-cpp[core]:x64-windows...
-- Note: restclient-cpp only supports static library linkage. Building static library.
-- Using cached D:/AAD/abc/vcpkg-master/downloads/mrtazz-restclient-cpp-0.5.2.tar.gz
-- Using source at D:/AAD/abc/vcpkg-master/buildtrees/restclient-cpp/src/0.5.2-148354f9a9
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/AAD/abc/vcpkg-master/packages/restclient-cpp_x64-windows/share/restclient-cpp/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package restclient-cpp[core]:x64-windows... done
Installing package restclient-cpp[core]:x64-windows...
Installing package restclient-cpp[core]:x64-windows... done
Elapsed time for package restclient-cpp:x64-windows: 21.63 s

Total elapsed time: 5.568 min

The package restclient-cpp:x64-windows provides CMake targets:

    find_package(restclient-cpp CONFIG REQUIRED)
    target_link_libraries(main PRIVATE restclient-cpp)
