### ISSUE TITLE
[New Port Request] <pjproject/pjlib>

### ISSUE THREAD

**Issue by leoliuasia** [microsoft/vcpkg#8298]
Library name:
pjproject/pjlib

Library description:
PJLIB is an Open Source, small footprint framework library written in C for making scalable applications. Because of its small footprint, it can be used in embedded applications (we hope so!), but yet the library is also aimed for facilitating the creation of high performance protocol stacks.

PJLIB is released under GPL terms.

Source repository URL:
https://github.com/pjsip/pjproject/tree/master/pjlib

Project homepage (if different from the source repository):
https://www.pjsip.org/docs/latest-2/pjlib/docs/html/index.htm

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by Voskrese** [comment]
[pjlib.zip](https://github.com/microsoft/vcpkg/files/3641012/pjlib.zip)

tested win x64 dynamic

**Comment by Voskrese** [comment]
add port file

`file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/pjlib)`

> vcpkg_install_msbuild(
>     SOURCE_PATH ${SOURCE_PATH}
>     PROJECT_SUBPATH "pjlib/build/pjlib.vcxproj"
>     SKIP_CLEAN
>     LICENSE_SUBPATH COPYING
>     INCLUDES_SUBPATH pjlib/include ALLOW_ROOT_INCLUDES
>     USE_VCPKG_INTEGRATION
> )
> 
> file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/pjlib)

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
