### ISSUE TITLE
NuGet per Project integration failed

### ISSUE THREAD

**Issue by Pantau123** [Microsoft/vcpkg#830]
Hi,
i want to make a per Project inclusion for vcpkg.
In PS i have typed the command `.\vcpkg.exe integrate project` and i received the Response 

> With a project open, go to Tools->NuGet Package Manager->Package Manager Console and paste:
>     Install-Package vcpkg.D.Tools.vcpkg -Source "D:/Tools/vcpkg/scripts/buildsystems"

I had opened my Project and inserted in the Package Manager Console ` Install-Package vcpkg.D.Tools.vcpkg -Source "D:/Tools/vcpkg/scripts/buildsystems"`
I received the following error Message:

> + Install-Package : Exception 'System.AggregateException' thrown when trying to add source 'http://packagesource'. Please verify all your online package sources are available.At line:1 char:1

How can i fix this??
I have Vs2015 Sp3

**Comment by alexkaratarakis** [comment]
In Visual Studio, go to: Tools -> Options -> NuGet Package Manager -> Package Sources
There should be an entry with url `http://packagesource`.

This is an entry that appears when you click the `+` at the top; it is meant to be modified right after creation, but if it is not, it creates issues like the one you are having. Click the `x` at the top to remove it, and click ok. 

After that integration should work.

**Comment by alexkaratarakis** [comment]
@Pantau123 please let me know if it still doesn't work for you.
