### ISSUE TITLE
How to I modify locally downloaded package and rebuild it?

### ISSUE THREAD

**Issue by kakyoism** [microsoft/vcpkg#8305]
I'd love to:

- Have access to the source code of an installed package, i.e., a package available after running `vcpkg install`;

- Modify the source code;
- Then rerun `vcpkg install` to make it available to all my VC projects again.

It's unclear how I could achieve this. I've tried to look into the `installed` packages, but they don't have source folders in there.

**Comment by Rastaban** [comment]
When vcpkg builds the source code is placed under the `buildtrees` folder, so you should be able to find what you are looking for there.  To can then put your changes into a [patch](https://github.com/microsoft/vcpkg/blob/master/docs/examples/patching.md) so they don't get lost if vcpkg cleans things up.

Good luck!

**Comment by zcream** [comment]
Hi. I added some files under buildtrees, however if I try vcpkg install, it does not rebuild. I get the message - the following packages are already installed.
How do I rebuild using the modified sources under buildtrees.

**Comment by somanuell** [comment]
Please how to rebuild a package after changing the source?


> I just want to edit a C++ file and rebuild the triplet to test a theory and make a well informed ticket for the developers. How can I achieve this please?

**Comment by Rullec** [comment]
> Please how to rebuild a package after changing the source?
> 
> > I just want to edit a C++ file and rebuild the triplet to test a theory and make a well informed ticket for the developers. How can I achieve this please?

Hi! I found the answer here `https://github.com/microsoft/vcpkg/discussions/26323`. 
Not sure whether you still need it or not. ;-)
