### ISSUE TITLE
[New Port Request] mmx

### ISSUE THREAD

**Issue by eater-of-souls** [microsoft/vcpkg#8309]
Library name: mmx

Library description: single header libraries for C/C++

Source repository URL: https://github.com/vurtun/mmx

**Comment by PhoebeHui** [comment]
mmx lacks of license,  I reported issue https://github.com/vurtun/mmx/issues/26 to mmx.

**Comment by PhoebeHui** [comment]
The port mmx has been added to VCPKG, you can get it by pulling latest vcpkg source.
