### ISSUE TITLE
[spdlog] update to 1.4.1

### ISSUE THREAD

**Issue by curtpm** [microsoft/vcpkg#8311]
Library name:
spdlog 

New version number:
1.4.1 

Other information that may be useful (release notes, etc...)
https://github.com/gabime/spdlog/releases/tag/v1.4.1

**Comment by NancyLi1013** [comment]
Related PR #8779.

**Comment by PhoebeHui** [comment]
PR https://github.com/microsoft/vcpkg/pull/8779 has been merged. spdlog upgraded to 1.4.2.
