### ISSUE TITLE
[New Port Request] async.h (header-only)

### ISSUE THREAD

**Issue by eater-of-souls** [microsoft/vcpkg#8316]
Library name: async.h

Library description: Stackless Async Subroutines for C

Source repository URL: https://github.com/naasking/async.h

**Comment by eater-of-souls** [comment]
Slightly off-topic question: is there are automated way to create PR's for header-only libraries?

**Comment by Voskrese** [comment]
`vcpkg create` $port $url

blank for create port

https://github.com/Voskrese/vcpkg/blob/master/scripts/https://github.com/Voskrese/vcpkg/blob/master/scripts/templates/portfile.in.cmake/portfile.in.cmake
