### ISSUE TITLE
Error: Building package sdl2:x86-windows failed with: BUILD_FAILED - VS2017 on Win7

### ISSUE THREAD

**Issue by jwithers512** [Microsoft/vcpkg#832]
c:\src\vcpkg>.\vcpkg install sdl2 curl
-- CURRENT_INSTALLED_DIR=C:/src/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/src/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/src/vcpkg/packages/sdl2_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/src/vcpkg/buildtrees/sdl2
-- CURRENT_PORT_DIR=c:/src/vcpkg/ports/sdl2/.
-- Using cached C:/src/vcpkg/downloads/SDL2-2.0.5.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch C:/src/vcpkg/ports/sdl2/dont-ignore-default-libs.patch
-- Applying patch failed. This is expected if this patch was previously applied.

-- Applying patch C:/src/vcpkg/ports/sdl2/dont-ignore-default-libs.patch done
-- Configuring x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: c:/src/vcpkg/downloads/cmake-3.8.0-rc1-win32-x86/bin/cmake.e
xe;C:/src/vcpkg/buildtrees/sdl2/src/SDL2-2.0.5;-DSDL_STATIC=OFF;-DSDL_SHARED=ON;
-DFORCE_STATIC_VCRT=OFF;-DLIBC=ON;-DBUILD_SHARED_LIBS=ON;-DCMAKE_CXX_FLAGS= /DWI
N32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP;-DCMAKE_C_FLAGS= /DWIN32 /D_WINDOWS /W3
/utf-8 /MP;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE
_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DBoost_COMPILER
=-vc140;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=O
N;-DCMAKE_TOOLCHAIN_FILE=C:/src/vcpkg/triplets/x86-windows.cmake;-DCMAKE_CXX_FLA
GS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Zi;-DCMAKE_C_FLAGS_RELEASE=/MD /O2 /Oi /Gy
/DNDEBUG /Zi;-DCMAKE_SHARED_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF
 /OPT:ICF;-DCMAKE_EXE_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:
ICF;-G;Visual Studio 15 2017;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_PREFIX_PATH=C:/s
rc/vcpkg/installed/x86-windows;-DCMAKE_INSTALL_PREFIX=C:/src/vcpkg/packages/sdl2
_x86-windows
    Working Directory: C:/src/vcpkg/buildtrees/sdl2/x86-windows-rel
    See logs for more information:
      C:\src\vcpkg\buildtrees\sdl2\config-x86-windows-rel-out.log
      C:\src\vcpkg\buildtrees\sdl2\config-x86-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:98 (vcpkg_execute_required_process)
  ports/sdl2/portfile.cmake:50 (vcpkg_configure_cmake)
  scripts/ports.cmake:73 (include)

Error: Building package sdl2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sdl2:x86-windows
  Vcpkg version: 0.0.76-830c5eab4e49d5656d50cf6c613e9bbaf628f2f6

Additionally, attach any relevant sections from the log files above.

config-x86-windows-rel-out.log:
CMake Error at CMakeLists.txt:6 (project):
  No CMAKE_C_COMPILER could be found.

config-x86-windows-rel-err.log:
-- The C compiler identification is unknown
-- Configuring incomplete, errors occurred!
See also "C:/src/vcpkg/buildtrees/sdl2/x86-windows-rel/CMakeFiles/CMakeOutput.log".
See also "C:/src/vcpkg/buildtrees/sdl2/x86-windows-rel/CMakeFiles/CMakeError.log".

CMakeOutput.log:
The system is: Windows - 6.1.7601 - x86

CMakeError.log:
Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler:  
Build flags: ;/DWIN32;/D_WINDOWS;/W3;/utf-8;/MP
Id flags:  

The output was:
1
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 3/21/2017 4:19:34 PM.
Project "C:\src\vcpkg\buildtrees\sdl2\x86-windows-rel\CMakeFiles\3.8.0-rc1\CompilerIdC\CompilerIdC.vcxproj" on node 1 (default targets).
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Platforms\Win32\PlatformToolsets\v141\Toolset.targets(34,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\src\vcpkg\buildtrees\sdl2\x86-windows-rel\CMakeFiles\3.8.0-rc1\CompilerIdC\CompilerIdC.vcxproj]
Done Building Project "C:\src\vcpkg\buildtrees\sdl2\x86-windows-rel\CMakeFiles\3.8.0-rc1\CompilerIdC\CompilerIdC.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\src\vcpkg\buildtrees\sdl2\x86-windows-rel\CMakeFiles\3.8.0-rc1\CompilerIdC\CompilerIdC.vcxproj" (default target) (1) ->
(Desktop_PlatformPrepareForBuild target) -> 
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Platforms\Win32\PlatformToolsets\v141\Toolset.targets(34,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\src\vcpkg\buildtrees\sdl2\x86-windows-rel\CMakeFiles\3.8.0-rc1\CompilerIdC\CompilerIdC.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.95

**Comment by ras0219-msft** [comment]
Thanks for reporting this!

I've pushed 85169fa which should fix this issue by selecting a newer Windows SDK on Win7. Please let us know if this solves your issue!

**Comment by jwithers512** [comment]
Now I'm seeing different errors:
c:\src\vcpkg>.\vcpkg install sdl2 curl

Download cmake
No suitable version of cmake was found (requires 3.8.0 or higher). Download
portable version?
[Y] Yes  [N] No  [A] Always Allow Downloads  [?] Help (default is "Y"): y
Expected dependency downloaded path to be c:/src/vcpkg/downloads/cmake-3.8.0-rc1
-win32-x86/bin/cmake.exe, but was C:/src/vcpkg/downloads/cmake-3.8.0-rc1-win32-x
86/bin/cmake.exe

c:\src\vcpkg>.\vcpkg install sdl2 curl
-- CURRENT_INSTALLED_DIR=C:/src/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/src/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/src/vcpkg/packages/sdl2_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/src/vcpkg/buildtrees/sdl2
-- CURRENT_PORT_DIR=c:/src/vcpkg/ports/sdl2/.
-- Downloading http://libsdl.org/release/SDL2-2.0.5.tar.gz...
-- Downloading http://libsdl.org/release/SDL2-2.0.5.tar.gz... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting source C:/src/vcpkg/downloads/SDL2-2.0.5.tar.gz
-- Extracting done
-- Applying patch C:/src/vcpkg/ports/sdl2/dont-ignore-default-libs.patch
-- Applying patch C:/src/vcpkg/ports/sdl2/dont-ignore-default-libs.patch done
-- Configuring x86-windows-rel
-- Configuring x86-windows-rel done
-- Configuring x86-windows-dbg
^C
c:\src\vcpkg>.\vcpkg install curl
-- CURRENT_INSTALLED_DIR=C:/src/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/src/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/src/vcpkg/packages/zlib_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/src/vcpkg/buildtrees/zlib
-- CURRENT_PORT_DIR=c:/src/vcpkg/ports/zlib/.
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz...
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting source C:/src/vcpkg/downloads/zlib1211.tar.gz
-- Extracting done
-- Configuring x86-windows-rel
-- Configuring x86-windows-rel done
-- Configuring x86-windows-dbg
^C
c:\src\vcpkg>.\vcpkg list
No packages are installed. Did you mean `search`?

c:\src\vcpkg>

**Comment by ras0219-msft** [comment]
>-- Configuring x86-windows-rel done
-- Configuring x86-windows-dbg
^C

Did you experience a hang at that point and therefore killed the program? How long did you wait before killing it?

Could you look at the log files at `buildtrees\sdl2\config-x86-windows-dbg-*.log` and post the last dozen lines of them?

**Comment by jwithers512** [comment]
Yes, it hung at that point three times.  One of them sat for at least a half hour before I killed it.  Both of the *-dbg-*.logs are empty.

**Comment by JackBoosY** [comment]
Hi @jwithers512 , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
