### ISSUE TITLE
glib ulong inconsistent on windows

### ISSUE THREAD

**Issue by zhaofeng-shu33** [microsoft/vcpkg#8321]
**Describe the bug**
It is known that on win64 platform, unsigned long is 4 bytes; on linux64 platform, it is 8 bytes. Some functions like `g_bit_nth_lsf_impl` accepts gulong as a parameter, whose type is not redefined like guinit64 on windows. It could lead to problems if a ginit64 variable is passed to such function.
**Environment**
- OS:  Windows and Linux
- Compiler: MSVC and gcc

**To Reproduce**
Sample program:
```C
#include <glib.h>
#include <glib/gprintf.h>

int main() {
    guint64 elem = 4294967296;
    gint offset = g_bit_nth_lsf(elem, -1);
    g_printf("%d\n", offset);
}
```
We compile and run the above code on Linux and Windows respectively.

The build pipeline for linux is available at [here](https://dev.azure.com/freewind201301/glib-fail-expose/_build/results?buildId=41&view=logs&jobId=12f1170f-54f2-53f3-20dd-22fc7dff55f9&taskId=5caf77c8-9b10-50ef-b5c7-ca89c63e1c86&lineStart=35&lineEnd=36&colStart=1&colEnd=1).
The program on linux outputs an integer 32.

We compile and run the same problem on windows, available at [here](https://ci.appveyor.com/project/zhaofeng-shu33/glib-fail-expose) using vcpkg unofficial glib library. The program source code is the same. But the output is -1 on windows, which is different.
This kind of difference could lead to program crash when porting existing codes from linux to windows.

**Additional context**
None

**Comment by Rastaban** [comment]
vcpkg uses the glib library from gnome and adds an unofficial cmake wrapper to make it easier to integrate into build systems.  While unfortunate, this looks like an issue with glib and not vcpkg itself.  For this reason I am closing the issue.  If there is something you think vcpkg could do to help this then feel free to reopen the issue and let us know.
