### ISSUE TITLE
tesseract:x64 build failure

### ISSUE THREAD

**Issue by traczu120** [microsoft/vcpkg#8323]
**Host Environment**
- OS: Windows 10

**To Reproduce**
`./vcpkg install tesseract:x64-windows`

```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/DEV/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: C:/DEV/vcpkg/buildtrees/tesseract/x64-windows-dbg
    See logs for more information:
      C:\DEV\vcpkg\buildtrees\tesseract\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/tesseract/portfile.cmake:47 (vcpkg_install_cmake)
  scripts/ports.cmake:91 (include)
```

**Comment by LilyWangL** [comment]
Hi @traczu120, thanks for posting this issue. I can't reproduce it locally with vcpkg latest source. Could you provide your build log? 
`C:\DEV\vcpkg\buildtrees\tesseract\install-x64-windows-dbg-out.log`

Thanks.

**Comment by PhoebeHui** [comment]
@traczu120 , we can't repro this issue, everything build successfully for me, please reopen this issue and attach the failure logs if it still be an problem for you.
