### ISSUE TITLE
ompl build failure

### ISSUE THREAD

**Issue by Gredin67** [microsoft/vcpkg#8325]
**Host Environment**
- OS: Windows 10
- Compiler: VS2015 v3 (platform toolset v140)

**To Reproduce**
`./vcpkg install ompl:x64-windows`

Vcpkg version: 2019.09.12-nohash

**Failure logs** 
Building package ompl:x64-windows failed with: BUILD_FAILED
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v
Working Directory: D:/vcpkg/buildtrees/ompl/x64-windows-dbg
See logs for more information:
D:\vcpkg\buildtrees\ompl\install-x64-windows-dbg-out.log
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3648310/install-x64-windows-dbg-out.log)
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3648311/install-x86-windows-dbg-out.log)

Call Stack (most recent call first):
scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
ports/ompl/portfile.cmake:42 (vcpkg_install_cmake)
scripts/ports.cmake:91 (include)

**Additional context**
I tried setting the platform toolset in x64-windows.cmake :
set(VCPKG_PLATFORM_TOOLSET v140)

I also tried to build ompl:x86-windows without success

**Comment by JackBoosY** [comment]
Hi @gnu-lorien, thanks for reporting this issue.
ompl need C11 standard, please update your Visual Studio to 2017+.

Thanks.

**Comment by Voskrese** [comment]
? /std:c++11 not ignoring

**Comment by JackBoosY** [comment]
Does this issue still bother you?

**Comment by gnu-lorien** [comment]
@JackBoosY I'm not the one who reported the issue. I'm not sure why I was tagged in this.

**Comment by JackBoosY** [comment]
@gnu-lorien, sorry I call the wrong man.

**Comment by JackBoosY** [comment]
If this issue is still not resolved, please reopen it.
