### ISSUE TITLE
[pmdk:x64-windows]build failure.

### ISSUE THREAD

**Issue by gottagogottagoGxj** [microsoft/vcpkg#8333]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).
My installation process has been a failure.It's going to show every time——“CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):”and"
    Working Directory: E:/StudySoftware/pmdk/vcpkg/buildtrees/pmdk/x64-windows-rel
    Error code: 1
    See logs for more information:
      E:\StudySoftware\pmdk\vcpkg\buildtrees\pmdk\build-x64-windows-rel-out.log"
Then I open the build-x64-windows-rel-out.log file,I find
`error C2220: warning treated as error - no 'object' file generated`
and
`warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss `

**Comment by JackBoosY** [comment]
Hi @gottagogottagoGxj, does this issue still bother you?

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
