### ISSUE TITLE
Central repository for all developers.

### ISSUE THREAD

**Issue by Eldadc** [microsoft/vcpkg#8337]
How to make a Central repository for all dev team without installing the packages on each developer machine.

Thanks

**Comment by Voskrese** [comment]
nuget ?

**Comment by Eldadc** [comment]
Nuget or zip.
I prefer zip file in Artifactory.

Thanks

**Comment by Voskrese** [comment]
https://www.nuget.org

**Comment by Rastaban** [comment]
Also see the vcpkg export command.  This allows you to use vcpkg to build on one machine and then export the libraries in various formats including Nuget and zip.
