### ISSUE TITLE
[portaudio] Expose CMake targets, not just headers/libraries?

### ISSUE THREAD

**Issue by jimbo1qaz** [microsoft/vcpkg#8343]
****

**Is your feature request related to a problem? Please describe.**
http://www.portaudio.com/docs/v19-doxydocs/compile_cmake.html#cmake_building upstream exposes targets accessible via `find_package(portaudio)`.

However, when I run `vcpkg install portaudio`, I do not get a message saying CMake targets were added. (`vcpkg install sqlite3` has a message.) Subsequently, if I try running `find_package(portaudio REQUIRED)` in another project using CMake vcpkg, it does not find it.

Similar to https://github.com/microsoft/vcpkg/issues/7632

**Proposed solution**
According to upstream docs, portaudio's CMakeLists.txt is designed to allow find_package() to work. vcpkg should expose these targets to projects using vcpkg.

**Describe alternatives you've considered**
vcpkg already exposes the headers and dynamic/static .lib, but this requires more complexity to use in another CMake project than find_package.

(I don't know how find_package works.)

**Additional context**
Windows 10 x64 1903, en-US, CMake (not msbuild).

**Comment by vicroms** [comment]
Hi @jimbo1qaz 

I took a look at our `portaudio` port and it seems to be outdated, which explains the lack of CMake targets. Would you be able to create a PR to update it to a more recent version?

**Comment by jimbo1qaz** [comment]
portaudio is an old and very slow-moving library... According to http://www.portaudio.com/download.html, pa_stable_v190600_20161030 is the most recent release. portaudio v19 was released back in 2007, and has the API not had breaking changes since then?

**Comment by vicroms** [comment]
@NancyLi1013

They have a Git repo, which means that we can use `vcpkg_from_git()` to fetch a stable commit or tag.

https://app.assembla.com/spaces/portaudio/git/source

`git clone  https://git.assembla.com/portaudio.git`

**Comment by NancyLi1013** [comment]
Hi @jimbo1qaz thanks for posting this issue. This port has been updated. This issue should be fixed now. Please try to update vcpkg and use it.
@vicroms thanks for the info you provided above.
