### ISSUE TITLE
Build directory is encoded in exported artefacts potentially causing build failures

### ISSUE THREAD

**Issue by mcraveiro** [microsoft/vcpkg#8351]
Hi vcpkg Developers,

Thanks very much for a really useful tool. I have a question regarding how builds and exports within vcpkg interact. More specifically, I noticed that the directory I use to build (e.g. ```/home/marco/Development```) is encoded on the exported zip. For this I unziped an export (e.g. ```vcpkg-export-20190919-151230```) and grepped:

```
grep -ire "/home/marco/Development" * | grep -v ^Binary
installed/x64-linux/include/Wt/WConfig.h:#define RUNDIR "/home/marco/Development/vcpkg/packages/wt_x64-linux/var/run/wt"
installed/x64-linux/include/Wt/WConfig.h:#define WT_CONFIG_XML "/home/marco/Development/vcpkg/packages/wt_x64-linux/etc/wt/wt_config.xml"
installed/x64-linux/include/Wt/WConfig.h:#define WTHTTP_CONFIGURATION "/home/marco/Development/vcpkg/packages/wt_x64-linux/etc/wt/wthttpd"
installed/x64-linux/include/openssl/opensslconf.h:#define ENGINESDIR "/home/marco/Development/vcpkg/packages/openssl-unix_x64-linux/lib/engines"
installed/x64-linux/lib/pkgconfig/cpp_redis.pc:prefix=/home/marco/Development/vcpkg/packages/cpp-redis_x64-linux
installed/x64-linux/lib/pkgconfig/libzstd.pc:prefix=/home/marco/Development/vcpkg/packages/zstd_x64-linux
...
```
As you can see, there are plenty of matches of the original build directory. Now, in general, this has not caused me any problems - in fact that is the reason I hadn't noticed this problem up to now. However, I started using ODB, which has the following:

```
installed/x64-linux/share/odb/odb_pgsqlConfig.cmake:  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:odb::libodb>;/home/marco/Development/vcpkg/installed/x64-linux/lib/libpq.a"
```

Because I was unpacking the export at a different location in the build machine, it failed to link:

```
ninja: error: '/home/marco/Development/vcpkg/installed/x64-linux/lib/libpq.a', needed by 'stage/bin/hedgr.backend.web', missing and no known rule to make it 
 ```

So my question is, is it a vcpkg requirement that one should always build and unpack in exactly the same path, or is there a cleaner way of handling path changes?

Many thanks for your time.

Marco

**Comment by cbezault** [comment]
We export exactly what ports/libraries create. If a port/library chooses to write down absolute paths during its build we currently have no way of handling that.

**Comment by mcraveiro** [comment]
Hi @cbezault,

Thanks very much for your prompt reply. Given the complexity of CMake, I guess there is no easy way to validate that the port is doing the right thing... Perhaps its just a case of making users aware that they need to build and export to exactly the same location if they want to avoid strange linking errors. Since there isn't much more we can do with this ticket, I'll close it.

Cheers

**Comment by mcraveiro** [comment]
Note to future self: the only solution I have found to this problem thus far is to build vcpkg locally at _exactly_ the same location as it will be included from within Travis/CI.
