### ISSUE TITLE
Error: Building package tiff:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Luna19950606** [microsoft/vcpkg#8358]
Package: tiff:x64-windows
  Vcpkg version: 2019.09.12-nohash

Error: Building package tiff:x64-windows failed with: BUILD_FAILED

**Comment by LilyWangL** [comment]
Hi @Luna19950606, I can't reproduce this issue locally. Can you provide your build log?

**Comment by Luna19950606** [comment]
Lily Thank you so much for replying me! But I already find a solution. I just mannually downloaded the required installing files and then run the script agian and it worked.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
