### ISSUE TITLE
Update `vcpkg create`

### ISSUE THREAD

**Issue by Rastaban** [microsoft/vcpkg#8363]
The `vcpkg create` command is outdated.  Its output should be modernized.  See @Neumann-A's comment to #8353.  Also it is missing the Homepage tag in the control file.

**Comment by Neumann-A** [comment]
It would be good if the create template would contain the following functions:
- a hint to lookup common variables in `vcpkg_common_definitions`
- `vcpkg_check_features`
- `vcpkg_fail_port_install`
- `vcpkg_fixup_cmake_targets`

**Comment by vpaladino778** [comment]
I could probably get around to doing this over the weekend. I see that @Rastaban is assigned to this, does that mean he's already in working on this?

**Comment by cbezault** [comment]
No it doesn't it means that he is assigned to dealing with comments on this issue and providing guidance to anyone looking to fix it.

**Comment by vpaladino778** [comment]
Okay cool, i'll work on this today, problem open a pull request today or tomorrow

**Comment by JackBoosY** [comment]
I wish I can improve this function in #9430.

**Comment by Cheney-W** [comment]
This issue has been fixed in the latest vcpkg(2021-08-03-1a6d67b8150e94b7f473c6ab1c0cfd), so close it.
