### ISSUE TITLE
Assimp update to v5.0.0

### ISSUE THREAD

**Issue by rundheim** [microsoft/vcpkg#8367]
Library name:The Asset Importer Lib

New version number: v5.0.0 release

https://github.com/assimp/assimp/releases

**Comment by snagels** [comment]
Doesn't the CONTROL file still contain wrong version ?

**Comment by NancyLi1013** [comment]
@snagels thanks for your friendly remind. I will update it later.

**Comment by NancyLi1013** [comment]
Hi @rundheim thanks for posting this issue. This port has been updated to the latest version. Please try to update vcpkg and use it.

**Comment by rundheim** [comment]
Thank you very much for a quick update of the library.
I have tried to update vcpkg and it works fine.
