### ISSUE TITLE
vcpkg install fails is Strawberry perl's gcc is in PATH

### ISSUE THREAD

**Issue by vaintroub** [microsoft/vcpkg#837]
I do 

  vcpkg install aws-sdk-cpp:x64-windows-static

it  fails:

Error: building package aws-sdk-cpp:x64-windows-static failed
Please ensure sure you're using the latest portfiles with `vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: aws-sdk-cpp:x64-windows-static
  Vcpkg version: 0.0.71-e1aea256b84d2c1ac5c29db0e5e40ed536e3157f

...

 C:\vcpkg\buildtrees\aws-sdk-cpp\config-x64-windows-static-rel-out.loghas this:

-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Building AWS libraries as static objects
-- Generating windows build config
-- Building project version: 1.0.61
-- The CXX compiler identification is unknown
-- Check for working CXX compiler: C:/Strawberry/c/bin/c++.exe
-- Check for working CXX compiler: C:/Strawberry/c/bin/c++.exe -- broken
-- Configuring incomplete, errors occurred!
See also "C:/vcpkg/buildtrees/aws-sdk-cpp/x64-windows-static-rel/CMakeFiles/CMakeOutput.log".
See also "C:/vcpkg/buildtrees/aws-sdk-cpp/x64-windows-static-rel/CMakeFiles/CMakeError.log".

**Comment by ras0219-msft** [comment]
Thanks for reporting this!

I notice you are using vcpkg 71. We have made some significant improvement in sanitizing the environment since then, so could you pull, re run bootstrap.ps1, then try again

**Comment by LilyWangL** [comment]
This issue hasn’t been updated in two year, if it is still an issue, please reopen.
