### ISSUE TITLE
Support a more smooth deployment of msys2

### ISSUE THREAD

**Issue by crlf0710** [microsoft/vcpkg#8374]
Hello, I'm trying to use vcpkg on travis to install a few libraries. This process involves `msys2` so vcpkg pulls msys2 from internet and run a self update. Then there's a core update of msys2. So it needs manual intervention, and the build process hangs there...

I wonder if there's anything we can do to make it through...

**Comment by PhoebeHui** [comment]
Move the discussion to https://github.com/microsoft/vcpkg/issues/12636.
