### ISSUE TITLE
[New Port Request] protobuf-c

### ISSUE THREAD

**Issue by ndragon70** [microsoft/vcpkg#8380]
Library name: protobuf-c

Library description: Protocol Buffers implementation in C

Source repository URL: https://github.com/protobuf-c/protobuf-c

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JackBoosY** [comment]
Hi @ndragon70, thanks for reporting this issue!
I've added it, please update vcpkg and try to build it.

Thanks.
