### ISSUE TITLE
I can't build glew, glfw3

### ISSUE THREAD

**Issue by GoodayTH** [microsoft/vcpkg#8389]
Environment
Windows10, MS VS Community 2017 15.9.16.

c:\GIT\vcpkg>vcpkg.exe install glew --triplet x64-windows
The following packages will be built and installed:
    glew[core]:x64-windows
Starting package 1/1: glew:x64-windows
Building package glew[core]:x64-windows...
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
Please install the English language pack.
-- Using cached C:/GIT/vcpkg/downloads/glew-2.1.0.tgz
-- Using source at C:/GIT/vcpkg/buildtrees/glew/src/glew-58abdfb190
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" C:/GIT/vcpkg/buildtrees/glew/src/glew-58abdfb190/build/cmake -DBUILD_UTILS=OFF -DCMAKE_MAKE_PROGRAM=C:/GIT/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe -DBUILD_SHARED_LIBS=ON -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/GIT/vcpkg/scripts/toolchains/windows.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=v140 -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=C:/GIT/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=C:/GIT/vcpkg/packages/glew_x64-windows/debug
    Working Directory: C:/GIT/vcpkg/buildtrees/glew/x64-windows-dbg
    Error code: 1
    See logs for more information:
      C:\GIT\vcpkg\buildtrees\glew\config-x64-windows-dbg-out.log
      C:\GIT\vcpkg\buildtrees\glew\config-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:305 (vcpkg_execute_required_process)
  ports/glew/portfile.cmake:19 (vcpkg_configure_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package glew:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glew:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.

[config-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/3667470/config-x64-windows-dbg-err.log)

**Comment by JackBoosY** [comment]
@GoodayTH Please install the English language pack and set the default language of Visual Studio to English and try again.

Thanks.

**Comment by GoodayTH** [comment]
Thank you I will try it

**Comment by GoodayTH** [comment]
Thank you @JackBoosY it work!
