### ISSUE TITLE
Error: Building Package libuv:x64-windows failes with: Build_Failed

### ISSUE THREAD

**Issue by Purpurea** [Microsoft/vcpkg#839]
I had followed the instruction https://github.com/Microsoft/vcpkg to install vcpkg

now i have an issue by
C:\src\vcpkg> .\vcpkg install sdl2 curl
that comes not comlple   to C:\     only _   after 1hour

**the log of vcpkg_extract_source_archive.cmake.txt** 

include(vcpkg_execute_required_process)
function(vcpkg_extract_source_archive ARCHIVE)
 if(NOT ARGC EQUAL 2)
set(WORKING_DIRECTORY 
${CURRENT_BUILDTREES_DIR}/src)
else()
set(WORKING_DIRECTORY ${ARGV1})
endif()
 get_filename_component(ARCHIVE_FILENAME 
${ARCHIVE} NAME)
 if(NOT EXISTS ${WORKING_DIRECTORY}/${ARCHIVE_FILENAME}.extracted)
message(STATUS "Extracting source ${ARCHIVE}")
 file(MAKE_DIRECTORY
 ${WORKING_DIRECTORY})
**vcpkg_execute_required_process(**
COMMAND ${CMAKE_COMMAND} -E tar xjf ${ARCHIVE}
WORKING_DIRECTORY ${WORKING_DIRECTORY}
LOGNAME extract          )
 file(WRITE ${WORKING_DIRECTORY}/${ARCHIVE_FILENAME}.extracted)
endif()
 message(STATUS "Extracting done"
endfunction()
****

is the process incomlete?

by run again, I get the log
-- Building Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:4 (message):
    Commad failed: cmd:/C; .....     more information in the attachement.
![issue_vcpkg](https://cloud.githubusercontent.com/assets/24254727/24225063/c733e550-0f5e-11e7-9845-0a016eda0017.png)

**Comment by ras0219-msft** [comment]
Hi @Purpurea, I'm having a bit of trouble understanding your issue, so let me restate:

> You ran `vcpkg install sdl2 curl` and it didn't complete after an hour. The hang was inside of the cmake extract step.

I'm not sure what would cause that. Could you post the console log where it hangs?

> `.\vcpkg install libuv:x64-windows` fails

Could you post the log files linked there? Specifically:
- `C:\src\vcpkg-master\buildtrees\libuv\x64-windows-build-rel-out.log`
- `C:\src\vcpkg-master\buildtrees\libuv\x64-windows-build-rel-err.log`

**Comment by Purpurea** [comment]
Hi, thanks for the response.

The Log for **C:\src\vcpkg-master\buildtrees\libuv\x64-windows-build-rel-out.log**
git clone https://chromium.googlesource.com/external/gyp build/gyp
['-Dtarget_arch=x64', '-Duv_library=shared_library', '.\\uv.gyp', '-I', '.\\common.gypi', '--depth=.', '-Dhost_arch=x86']
Project files generated.
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu erm”glichen, mssen Sie den Schalter "/m" hinzufgen.
  fs-poll.c
  inet.c
  threadpool.c
  uv-common.c
src\inet.c(171): warning C4244: "=": Konvertierung von "__int64" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\inet.c(198): warning C4244: "Initialisierung": Konvertierung von "__int64" in "unsigned int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\inet.c(294): warning C4244: "Initialisierung": Konvertierung von "__int64" in "const int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\fs-poll.c(188): warning C4244: "Funktion": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\fs-poll.c(191): warning C4244: "=": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
  version.c
  async.c
  core.c
  detect-wakeup.c
  dl.c
  error.c
  fs.c
  fs-event.c
  getaddrinfo.c
  getnameinfo.c
src\win\fs-event.c(84): warning C4267: "Initialisierung": Konvertierung von "size_t" nach "int", Datenverlust m”glich [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs-event.c(350): warning C4267: "=": Konvertierung von "size_t" nach "int", Datenverlust m”glich [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs-event.c(420): warning C4267: "=": Konvertierung von "size_t" nach "int", Datenverlust m”glich [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
  handle.c
src\win\fs.c(185): warning C4244: "Funktion": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(199): warning C4244: "Funktion": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(919): warning C4267: "Funktion": Konvertierung von "size_t" nach "int", Datenverlust m”glich [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(951): warning C4267: "Funktion": Konvertierung von "size_t" nach "int", Datenverlust m”glich [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(953): warning C4267: "Funktion": Konvertierung von "size_t" nach "int", Datenverlust m”glich [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(1337): warning C4267: "Funktion": Konvertierung von "size_t" nach "unsigned int", Datenverlust m”glich [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(1524): warning C4267: "=": Konvertierung von "size_t" nach "int", Datenverlust m”glich [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(1581): warning C4267: "=": Konvertierung von "size_t" nach "USHORT", Datenverlust m”glich [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(1582): warning C4267: "=": Konvertierung von "size_t" nach "USHORT", Datenverlust m”glich [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(1610): warning C4267: "=": Konvertierung von "size_t" nach "USHORT", Datenverlust m”glich [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(1611): warning C4267: "=": Konvertierung von "size_t" nach "USHORT", Datenverlust m”glich [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(1929): warning C4244: "return": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(1943): warning C4244: "return": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(1979): warning C4244: "return": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(2015): warning C4244: "return": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(2036): warning C4244: "return": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(2059): warning C4244: "return": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(2079): warning C4244: "return": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(2099): warning C4244: "return": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(2122): warning C4244: "return": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(2143): warning C4244: "return": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(2166): warning C4244: "return": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(2187): warning C4244: "return": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(2212): warning C4244: "return": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(2233): warning C4244: "return": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(2247): warning C4244: "return": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(2267): warning C4244: "return": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(2287): warning C4244: "return": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(2301): warning C4244: "return": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(2322): warning C4244: "return": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(2336): warning C4244: "return": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(2350): warning C4244: "return": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(2367): warning C4244: "return": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(2380): warning C4267: "=": Konvertierung von "size_t" nach "ULONG", Datenverlust m”glich [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(2387): warning C4244: "return": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(2413): warning C4244: "return": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(2435): warning C4244: "return": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(2452): warning C4244: "return": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(2476): warning C4244: "return": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\fs.c(2494): warning C4244: "return": Konvertierung von "ssize_t" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
  loop-watcher.c
src\win\getaddrinfo.c(127): warning C4267: "+=": Konvertierung von "size_t" nach "int", Datenverlust m”glich [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
  pipe.c
  thread.c
  poll.c
  process.c
src\win\pipe.c(1053): warning C4244: "Funktion": Konvertierung von "ULONG_PTR" in "DWORD", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\pipe.c(1072): warning C4244: "Funktion": Konvertierung von "ULONG_PTR" in "DWORD", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\pipe.c(2065): warning C4267: "Funktion": Konvertierung von "size_t" nach "int", Datenverlust m”glich [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
  process-stdio.c
  req.c
  signal.c
src\win\process.c(628): warning C4244: "=": Konvertierung von "__int64" in "int", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\process.c(748): warning C4267: "Funktion": Konvertierung von "size_t" nach "int", Datenverlust m”glich [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\process.c(784): warning C4267: "Funktion": Konvertierung von "size_t" nach "int", Datenverlust m”glich [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\process.c(803): warning C4267: "=": Konvertierung von "size_t" nach "int", Datenverlust m”glich [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
  snprintf.c
  stream.c
  tcp.c
  tty.c
  timer.c
src\win\tcp.c(369): warning C4244: "Funktion": Konvertierung von "ULONG_PTR" in "DWORD", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\tcp.c(388): warning C4244: "Funktion": Konvertierung von "ULONG_PTR" in "DWORD", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\tty.c(934): warning C4244: "Initialisierung": Konvertierung von "ULONG_PTR" in "DWORD", m”glicher Datenverlust [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\tty.c(2097): warning C4267: "return": Konvertierung von "size_t" nach "int", Datenverlust m”glich [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
  udp.c
  util.c
  winapi.c
src\win\util.c(1172): warning C4267: "Funktion": Konvertierung von "size_t" nach "int", Datenverlust m”glich [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
src\win\util.c(1247): warning C4267: "Funktion": Konvertierung von "size_t" nach "int", Datenverlust m”glich [C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\libuv.vcxproj]
  winsock.c
     Bibliothek "C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\Release\libuv.lib" und Objekt "C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\Release\libuv.exp" werden erstellt.
  Code wird generiert.
  Codegenerierung ist abgeschlossen.
  libuv.vcxproj -> C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\Release\\libuv.dll
  libuv.vcxproj -> C:\src\vcpkg-master\buildtrees\libuv\x64-windows-src\libuv-1.10.1\Release\libuv.pdb (Full PDB)
Batchvorgang abbrechen (J/N)? 

--------------

the Log of **C:\src\vcpkg-master\buildtrees\libuv\x64-windows-build-rel-err.log**

Cloning into 'build/gyp'...
Checking out files:   0% (6/1646)   
Checking out files:   0% (7/1646)   
Checking out files:   1% (17/1646)   
Checking out files:   2% (33/1646)   
Checking out files:   3% (50/1646)   
Checking out files:   4% (66/1646)   
Checking out files:   5% (83/1646)   
Checking out files:   6% (99/1646)   
Checking out files:   7% (116/1646)   
Checking out files:   8% (132/1646)   
Checking out files:   9% (149/1646)   
Checking out files:  10% (165/1646)   
Checking out files:  11% (182/1646)   
Checking out files:  12% (198/1646)   
Checking out files:  13% (214/1646)   
Checking out files:  13% (224/1646)   
Checking out files:  14% (231/1646)   
Checking out files:  15% (247/1646)   
Checking out files:  16% (264/1646)   
Checking out files:  17% (280/1646)   
Checking out files:  18% (297/1646)   
Checking out files:  19% (313/1646)   
Checking out files:  20% (330/1646)   
Checking out files:  21% (346/1646)   
Checking out files:  22% (363/1646)   
Checking out files:  23% (379/1646)   
Checking out files:  24% (396/1646)   
Checking out files:  25% (412/1646)   
Checking out files:  26% (428/1646)   
Checking out files:  27% (445/1646)   
Checking out files:  28% (461/1646)   
Checking out files:  29% (478/1646)   
Checking out files:  30% (494/1646)   
Checking out files:  31% (511/1646)   
Checking out files:  32% (527/1646)   
Checking out files:  33% (544/1646)   
Checking out files:  34% (560/1646)   
Checking out files:  35% (577/1646)   
Checking out files:  36% (593/1646)   
Checking out files:  37% (610/1646)   
Checking out files:  38% (626/1646)   
Checking out files:  39% (642/1646)   
Checking out files:  40% (659/1646)   
Checking out files:  40% (667/1646)   
Checking out files:  41% (675/1646)   
Checking out files:  42% (692/1646)   
Checking out files:  43% (708/1646)   
Checking out files:  44% (725/1646)   
Checking out files:  45% (741/1646)   
Checking out files:  46% (758/1646)   
Checking out files:  47% (774/1646)   
Checking out files:  48% (791/1646)   
Checking out files:  49% (807/1646)   
Checking out files:  50% (823/1646)   
Checking out files:  51% (840/1646)   
Checking out files:  52% (856/1646)   
Checking out files:  53% (873/1646)   
Checking out files:  54% (889/1646)   
Checking out files:  55% (906/1646)   
Checking out files:  56% (922/1646)   
Checking out files:  57% (939/1646)   
Checking out files:  58% (955/1646)   
Checking out files:  59% (972/1646)   
Checking out files:  60% (988/1646)   
Checking out files:  61% (1005/1646)   
Checking out files:  62% (1021/1646)   
Checking out files:  63% (1037/1646)   
Checking out files:  64% (1054/1646)   
Checking out files:  65% (1070/1646)   
Checking out files:  66% (1087/1646)   
Checking out files:  67% (1103/1646)   
Checking out files:  68% (1120/1646)   
Checking out files:  69% (1136/1646)   
Checking out files:  70% (1153/1646)   
Checking out files:  70% (1161/1646)   
Checking out files:  71% (1169/1646)   
Checking out files:  72% (1186/1646)   
Checking out files:  73% (1202/1646)   
Checking out files:  74% (1219/1646)   
Checking out files:  75% (1235/1646)   
Checking out files:  76% (1251/1646)   
Checking out files:  77% (1268/1646)   
Checking out files:  78% (1284/1646)   
Checking out files:  79% (1301/1646)   
Checking out files:  80% (1317/1646)   
Checking out files:  81% (1334/1646)   
Checking out files:  82% (1350/1646)   
Checking out files:  83% (1367/1646)   
Checking out files:  84% (1383/1646)   
Checking out files:  85% (1400/1646)   
Checking out files:  86% (1416/1646)   
Checking out files:  87% (1433/1646)   
Checking out files:  88% (1449/1646)   
Checking out files:  89% (1465/1646)   
Checking out files:  90% (1482/1646)   
Checking out files:  91% (1498/1646)   
Checking out files:  92% (1515/1646)   
Checking out files:  93% (1531/1646)   
Checking out files:  94% (1548/1646)   
Checking out files:  94% (1561/1646)   
Checking out files:  95% (1564/1646)   
Checking out files:  96% (1581/1646)   
Checking out files:  97% (1597/1646)   
Checking out files:  98% (1614/1646)   
Checking out files:  99% (1630/1646)   
Checking out files: 100% (1646/1646)   
Checking out files: 100% (1646/1646), done.
^C

_I mean the last line is close the window after one hour._

**Comment by ras0219-msft** [comment]
Ok, while trying to reproduce this issue I fixed several others. Could you try pulling the latest and trying again? It should not take more than 10 or so minutes to build, so don't worry about waiting a whole hour.

**Comment by Purpurea** [comment]
okay thanks libuv works,

the other Openssl also, but the boost and the zlib stopes/hanging in the Configuring x64-window-rel line

in the log
**config-x64-windows-rel-err.log**
**config-x64-windows-rel-out.log**

no lines written, empty

## **_Could you fixed for zlib and boost the same as libuv_**

I have followed the instruction by https://github.com/uWebSockets/uWebSockets
cmd: vcpkg install libuv:x64-windows boost:x64-windows openssl:x64-windows zlib:x64-windows

![close_libuv_vcpkg](https://cloud.githubusercontent.com/assets/24254727/24266268/7ea7ae04-1006-11e7-8e21-5cf2ce9eb15c.png)

**Comment by ras0219-msft** [comment]
Ok, it sounds like your machine is having trouble building CMake-based projects.

Could you try creating a simple CMake project (for example, cloning https://github.com/jameskbride/cmake-hello-world) and building it?
```
git clone https://github.com/jameskbride/cmake-hello-world
mkdir cmake-hello-world/build
cd cmake-hello-world/build
cmake --trace ..
cmake --build .
```
If you do not have cmake installed, we have downloaded a copy for you inside C:/src/vcpkg-master/downloads/cmake-3.8.0-rc1-win32-x86/bin/cmake.exe

**Comment by Purpurea** [comment]
hello, I get an issue for cmake --trace ..   
#else /* unknown compiler */
than stops the compilation in line  241 by output variable
![issue_cmake_trace](https://cloud.githubusercontent.com/assets/24254727/24326060/5f225b28-11a6-11e7-8c8f-bd5000792558.jpg)

what can I do?

**Comment by buffos** [comment]
I have the same problem. It builds other packages fine.
When i try to build libuv i get

```
Error: Building package libuv:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libuv:x86-windows
  Vcpkg version: 0.0.80-unknownhash

```

the same for x64 version.  I have pulled the latest version of vcpkg manager

**Comment by ras0219-msft** [comment]
What version(s) of Visual Studio do you have installed on your machine? Where did you install them?

Could you run `.\scripts\findAnyMSBuildWithCppPlatformToolset.ps1 -verbose` and post the output?

**Comment by swirlingsand** [comment]
I'm having an issue with zlib too!   cmake results -> Build succeeded, 0 warnings 0 errors
https://github.com/Microsoft/vcpkg/issues/1060

**Comment by JackBoosY** [comment]
Hi @Purpurea , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
