### ISSUE TITLE
Boost MS-MPI version problems

### ISSUE THREAD

**Issue by drnuke** [microsoft/vcpkg#8393]
Building package msmpi[core]:x86-windows...
-- Using cached C:/Users/117725/source/repos/vcpkg/downloads/msmpisdk-10.0.12498.msi
-- Using cached C:/Users/117725/source/repos/vcpkg/downloads/msmpisetup-10.0.12498.exe
CMake Error at ports/msmpi/portfile.cmake:43 (message):
    The version of the installed MSMPI redistributable packages does not match the version to be installed
      Expected version: 10.0.12498
      Found version: 10.1.12498
    Please upgrade the installed version on your system.
    The appropriate installer for the expected version has been downloaded to:
      C:/Users/117725/source/repos/vcpkg/downloads/msmpisetup-10.0.12498.exe

Call Stack (most recent call first):
  scripts/ports.cmake:94 (include)

Error: Building package msmpi:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: msmpi:x86-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by LilyWangL** [comment]
Hi @drnuke, did you download version: 10.1.12498 packages before building msmpi? The version of msmpi on vcpkg is 10.0.12498. You can remove version: 10.1.12498 packages and rebuild msmpi.

Thanks

**Comment by drnuke** [comment]
No. I downloaded nothing. I just installed the package as directed. Nothing
special

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed, please install _VCPKG_PATH/downloads/msmpisetup-10.0.12498.exe_ first, and rebuild msmpi.
