### ISSUE TITLE
netcdf-cxx4 doesn't provide information on how to use it in cmake

### ISSUE THREAD

**Issue by lakinwecker** [microsoft/vcpkg#8396]
**Describe the bug**
Installing the package gets you this output:
```
➜ ./vcpkg install netcdf-cxx4
The following packages are already installed:
    netcdf-cxx4[core]:x64-linux
Starting package 1/1: netcdf-cxx4:x64-linux
Package netcdf-cxx4:x64-linux is already installed
Elapsed time for package netcdf-cxx4:x64-linux: 7.493 us

Total elapsed time: 13.32 us
```
But there are no instructions on how to integrate it with your build.

```
find_library(NetCDFCxx4 netcdf-cxx4)
target_link_libraries(main PRIVATE ${NetCDFCxx4})
```
worked for me, but I'm not sure if that is the recommended way to do it or not.

**Environment**
- OS: Linux (arch linux)
- Compiler: clang 8.0.1 / g++ 9.1.0

**To Reproduce**
1. ./vcpkg install netcdf-cxx4
2. See above error.

**Expected behavior**
I feel all of the vcpkg libraries should print out the appropriate cmake commands for including them in your build.

**Comment by JackBoosY** [comment]
We need to add `vcpkg_cmake_wrapper.cmake`.
As a temporary workaround, you can use the following code:
```
find_path(netcdf-c_INCLUDE_DIRS NAMES netcdf.h)
include(SelectLibraryConfigurations)
find_library(netcdf-c_LIBRARY_RELEASE NAMES netcdf PATH_SUFFIXES debug/lib)
find_library(netcdf-c_LIBRARY_DEBUG NAMES netcdf)
select_library_configurations(netcdf-c)
```

**Comment by lakinwecker** [comment]
@JackBoosY Thanks for the answer.  Isn't this the code you would need to link against netcdf-c and not netcdf-cxx4?

**Comment by JackBoosY** [comment]
@lakinwecker Sorry, I was wrong. Here is the correct code:
```
find_path(netcdf-c_INCLUDE_DIRS NAMES netcdf)
include(SelectLibraryConfigurations)
find_library(netcdf-c_LIBRARY_RELEASE NAMES netcdf-cxx4 PATH_SUFFIXES debug/lib)
find_library(netcdf-c_LIBRARY_DEBUG NAMES netcdf-cxx4)
select_library_configurations(netcdf-c)
```

**Comment by NancyLi1013** [comment]
Hi @lakinwecker 

`netcdf-cxx4` has been updated to export cmake targets, please try to update vcpkg to the latest version to rebuild this port.

The usage is like this:
```
 find_package(netCDFCxx CONFIG REQUIRED)
 target_link_libraries(main PRIVATE netCDF::netcdf netCDF::netcdf-cxx4)
```
