### ISSUE TITLE
restclient-cpp can not resolve symbol

### ISSUE THREAD

**Issue by how0723** [microsoft/vcpkg#8404]
Describe the bug
1>main.obj : error LNK2019: 无法解析的外部符号 "struct RestClient::Response __cdecl RestClient::get(class std::basic_string<char,struct std::char_traits,class std::allocator > const &)" (?get@RestClient@@ya?AUResponse@1@AEBV?$basic_string@DU?$char_traits@D@std@@v?$allocator@D@2@@std@@@z)，该符号在函数 main 中被引用
can not resolve symbol

Environment

OS: win10 x64
Compiler: msvc2017
To Reproduce

./vcpkg install restclient-cpp:x64
See error
Repro code when
Expected behavior

Failure logs
error LNK2019: 无法解析的外部符号 "struct RestClient::Response __cdecl RestClient::get(class std::basic_string<char,struct std::char_traits,class std::allocator > const &)" (?get@RestClient@@ya?AUResponse@1@AEBV?$basic_string@DU?$char_traits@D@std@@v?$allocator@D@2@@std@@@z)，该符号在函数 main 中被引用

Additional context

**Comment by JackBoosY** [comment]
Hi @how0723, thanks for reporting this issue.
I think this is a usage issue. Therefore, please provide a demo code.

Thanks.

**Comment by how0723** [comment]
my code :

#include "restclient-cpp/restclient.h"
int main()
{
RestClient::Response r = RestClient::get("http://url.com")
RestClient::Response r = RestClient::post("http://url.com/post", "application/json", "{\"foo\": \"bla\"}")
RestClient::Response r = RestClient::put("http://url.com/put", "application/json", "{\"foo\": \"bla\"}")
RestClient::Response r = RestClient::patch("http://url.com/patch", "application/json", "{\"foo\": \"bla\"}")
RestClient::Response r = RestClient::del("http://url.com/delete")
RestClient::Response r = RestClient::head("http://url.com")
RestClient::Response r = RestClient::options("http://url.com")
}

**Comment by JackBoosY** [comment]
Confirmed, missing dlls and libs.

**Comment by JackBoosY** [comment]
Hi @how0723, thanks for reporting this issue.
According to [#110](https://github.com/mrtazz/restclient-cpp/issues/110), restclient-cpp does not export any symbols, and I have not found any `dllexports` in its code.
If there is officially supported Windows in the future, we will upgrade this port.

Thanks.
