### ISSUE TITLE
[New Port Request] luxcorerender

### ISSUE THREAD

**Issue by luzpaz** [microsoft/vcpkg#8406]
Library name: LuxCoreRender

Library description: LuxCore is the new LuxCoreRender v2.x C++ and Python API. It is released under Apache Public License v2.0 and can be freely used in open source and commercial applications.

Source repository URL: https://github.com/LuxCoreRender/LuxCore

Project homepage (if different from the source repository): https://wiki.luxcorerender.org/LuxCore_API  

Anything else that is useful to know when adding (such as optional features the library may have that should be included):  
Official Website: https://www.luxcorerender.org/

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
