### ISSUE TITLE
Tools (qmlscene, designer, etc.) in vcpkg qt5:x64-windows build crash due to missing dlls

### ISSUE THREAD

**Issue by spindensity** [microsoft/vcpkg#8408]
**Describe the bug**

Tools (qmlscene, designer, etc)  in vcpkg:x64-windows build crashes.

**Environment**

- OS: Win10 1903
- MSVC 2017 15.9.16

**To Reproduce**

1. `vcpkg install qt5:x64-windows`;
2. Run command `%VCPKG_ROOT%\installed\x64-windows\tools\qt5\bin\qmlscene.exe --help`;, nothing outputs, the program just crashes silently;
4. Open `%VCPKG_ROOT%\installed\x64-windows\tools\qt5\bin` directory in file explorer and double click `designer.exe`, the program crashes due to missing dlls.

**Expected behavior**

Tools work like them in the official distribution.

**Comment by Neumann-A** [comment]
That is a generell problem with how qt is integrated into vcpkg and how vcpkg handles packages. Sry, there is nothing which could be done here to solve the problem.
As far as I remember qmlscene is build by qt5-declarative so you have to use the version in `%VCPKG_ROOT%\installed\x64-windows\tools\qt5-declarative\bin\qmlscene.exe`. Alternatively, you could add the path `%VCPKG_ROOT%\installed\x64-windows\bin` to your `PATH` variable or build qt5 static.
