### ISSUE TITLE
How do I support package that build from diffrent files

### ISSUE THREAD

**Issue by Eldadc** [microsoft/vcpkg#8420]
How do I support package that build from different files ?
No compile is necessary to build packages , Just simple binaries.

Thanks

**Comment by cbezault** [comment]
You would add a port which doesn't do any "install" calls, it would just download the binary and put it in the appropriate place in the installed dir.

**Comment by Eldadc** [comment]
Ok. Seems fine solution. Can you please give an example.
Thanks

**Comment by Eldadc** [comment]
How can we point to a ZIP file in a repo in my port.
Thanks

**Comment by PhoebeHui** [comment]
@Eldadc, see https://github.com/microsoft/vcpkg/blob/master/docs/examples/packaging-zipfiles.md for details. And please create a new issue if you have any questions for this.
