### ISSUE TITLE
Building opencv3 as dynamic libraries on macOS

### ISSUE THREAD

**Issue by 0xced** [microsoft/vcpkg#8421]
I'm opening this issue with the goal of documenting how I built the `opencv3` as a dynamic library on macOS.

First, I added a new triplet `x64-osx-dynamic.cmake` in the `triplets` directory, copied from `x64-osx.cmake` and changed `VCPKG_LIBRARY_LINKAGE` from `static` to `dynamic`

```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
```

Then I built opencv3 with the new triplet: `./vcpkg install opencv3 --triplet x64-osx-dynamic`

It failed with this error (extracted from the log file):

```
dyld: Library not loaded: @rpath/libprotoc.3.9.1.0.dylib
  Referenced from: ~/vcpkg/installed/x64-osx-dynamic/tools/protobuf/protoc
  Reason: image not found
```

So I added a symbolic link `lib -> ../lib` inside `~/vcpkg/installed/x64-osx-dynamic/tools` because the (single) RPATH of `~/vcpkg/installed/x64-osx-dynamic/tools/protobuf/protoc` is defined with `@loader_path/../lib` and it doesn't match how the `protoc` binary is installed.

Note: the *correct* way to fix this issue is probably to fix the rpath load command of `protoc` (but I have no idea how to do this in the vcpkg pipeline).

```
otool -l ~/vcpkg/installed/x64-osx-dynamic/tools/protobuf/protoc
[…]
Load command 18
          cmd LC_RPATH
      cmdsize 32
         path @loader_path/../lib (offset 12)
[…]
```

Building again with `./vcpkg install opencv3 --triplet x64-osx-dynamic` finally succeeded and all the opencv3 *.dylib files are found in `~/vcpkg/installed/x64-osx-dynamic/lib`.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. `opencv3:x64-osx` can install succeed. `x64-osx-dynamic` is a community triplet, and there are no update about this issue for a long time. If there are new process or change of this issue, please reopen this issue.
