### ISSUE TITLE
 Unable to locate 'afxres.h'

### ISSUE THREAD

**Issue by hachling** [microsoft/vcpkg#8423]
Building package atlmfc[core]:x64-windows...
CMake Error at ports/atlmfc/portfile.cmake:7 (message):
  Unable to locate 'afxres.h'.  Ensure you have installed the ATL/MFC
  component of Visual Studio.
Call Stack (most recent call first):
  scripts/ports.cmake:94 (include)

Error: Building package atlmfc:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: atlmfc:x64-windows
  Vcpkg version: 2019.09.12-nohash

file afxres.h is located at:
vcpkg\downloads\tools\perl\c\i686-w64-mingw32\include
Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\include

**Comment by hachling** [comment]
./vcpkg.exe install cpprestsdk:x64-windows

during an installation of cpprestsdk, i see the following errors:
Building package zlib[core]:x64-windows...
'"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\include"\cmake.cmd" --version 2>&1' is not recognized as an internal or external command,
operable program or batch file.
'"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\include"\cmake.exe" --version 2>&1' is not recognized as an internal or external command,
operable program or batch file.
'"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\include"\cmake.bat" --version 2>&1' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Voskrese** [comment]
https://github.com/microsoft/vcpkg/search?q=cmake.cmd&type=Issues

**Comment by hachling** [comment]
checked the validity of the path. all seems fine.
Also, happened on 2 different machines.

**Comment by hachling** [comment]
the errors mentioned in my second comment do not appear in the second machine but still the result is the same.
i succeed to install cppresksdk and fail to install azure-storage-cpp with the error:

Building package gettext[core]:x64-windows... done
Installing package gettext[core]:x64-windows...
Installing package gettext[core]:x64-windows... done
Elapsed time for package gettext:x64-windows: 45.68 s
Starting package 3/4: atlmfc:x64-windows
Building package atlmfc[core]:x64-windows...
CMake Error at ports/atlmfc/portfile.cmake:7 (message):
  Unable to locate 'afxres.h'.  Ensure you have installed the ATL/MFC
  component of Visual Studio.
Call Stack (most recent call first):
  scripts/ports.cmake:94 (include)


Error: Building package atlmfc:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: atlmfc:x64-windows
  Vcpkg version: 2019.09.12-nohash

**Comment by contre** [comment]
Vcpkg may choose a different installation of visual studio than you expect. Either specify which version to use or check that atl/mfc is installed for all versions.

**Comment by Voskrese** [comment]
you don't provide any lairs
you don't write about the actions you've done

> I can write from myself that I have no such problems and recommend to close?!

describe your problem in more detail

`where $include:afxres.h`

> C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\include\afxres.h

**Comment by hachling** [comment]
i have VS2017 and 2015 installed.
first i installed vcpkg according to:
https://github.com/Microsoft/vcpkg#quick-start

i am using git for windows as the command line interface to use vcpkg.
i am following the guidelines according to:
https://github.com/Azure/azure-storage-cpp

i then installed cpprestsdk:
./vcpkg.exe install cpprestsdk:x64-windows

This succeeded successfully.

and then attempted to install azure-storage-cpp:
c/projects/eng/vcpkg (master)
$ ./vcpkg.exe install azure-storage-cpp:x64-windows
The following packages will be built and installed:
  * atlmfc[core]:x64-windows
    azure-storage-cpp[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: atlmfc:x64-windows
Building package atlmfc[core]:x64-windows...
CMake Error at ports/atlmfc/portfile.cmake:7 (message):
  Unable to locate 'afxres.h'.  Ensure you have installed the ATL/MFC
  component of Visual Studio.
Call Stack (most recent call first):
  scripts/ports.cmake:94 (include)


Error: Building package atlmfc:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: atlmfc:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.


PATH is:
ALLUSERSPROFILE=C:\ProgramData
ANDROID_SDK_HOME=C:\Android
APPDATA=C:\Users\shlomi.apel\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=IL-SHLOMIA
ComSpec=C:\WINDOWS\system32\cmd.exe
DriverData=C:\Windows\System32\Drivers\DriverData
HOMEDRIVE=C:
HOMEPATH=\Users\shlomi.apel
LOCALAPPDATA=C:\Users\shlomi.apel\AppData\Local
LOGONSERVER=\\ZDC06
NUMBER_OF_PROCESSORS=8
OneDrive=C:\Users\shlomi.apel\OneDrive
OS=Windows_NT
Path=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Sennheiser\SoftphoneSDK\;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Users\shlomi.apel\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Program Files\dotnet\;C:\Android;C:\Windows\System32;c:\shared;C:\mybin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\include;"C:\Users\shlomi.apel\AppData\Local\Microsoft\WindowsApps;C:\shared;C:\mybin";
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=8e0a
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\shlomi.apel\AppData\Local\Temp
TMP=C:\Users\shlomi.apel\AppData\Local\Temp
UATDATA=C:\WINDOWS\CCM\UATData\D9F8C395-CAB8-491d-B8AC-179A1FE1BE77
USERDNSDOMAIN=ZERTO.LOCAL
USERDOMAIN=ZERTO
USERDOMAIN_ROAMINGPROFILE=ZERTO
USERNAME=shlomi.apel
USERPROFILE=C:\Users\shlomi.apel
VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
windir=C:\WINDOWS

what additional information is missing?

**Comment by hachling** [comment]
$ find -name afxres.h

./Program Files (x86)/Microsoft Visual Studio 14.0/VC/atlmfc/include/afxres.h
./projects/eng/vcpkg/downloads/tools/perl/c/i686-w64-mingw32/include/afxres.h

**Comment by Voskrese** [comment]
why do you execute this command? just wondering
`find -name afxres.h`

**Comment by contre** [comment]
Vcpkg version is from 9-12, try a later version?

**Comment by JackBoosY** [comment]
Path=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files (x86)\Sennheiser\SoftphoneSDK;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Users\shlomi.apel.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Program Files\dotnet;C:\Android;C:\Windows\System32;c:\shared;C:\mybin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;**C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\include**;"C:\Users\shlomi.apel\AppData\Local\Microsoft\WindowsApps;C:\shared;C:\mybin";

I think the `afxres.h` path is correct.

**Comment by hachling** [comment]
The issue was resolved. i saw that even though the workload for c++ was added to VS2017, MFC was not checked by default.
after adding it, everything seems to work.
