### ISSUE TITLE
yoga build failure

### ISSUE THREAD

**Issue by handicraftsman** [microsoft/vcpkg#8428]
**Host Environment**
- Manjaro Linux
- Compiler: not important, but gcc 9.1.0

**To Reproduce**
`./vcpkg install yoga`

**Failure logs** 
```
CMake Error at ports/yoga/portfile.cmake:26 (file):
  file INSTALL cannot find
  "/home/handicraftsman/Platforms/vcpkg/buildtrees/yoga/x64-linux-rel/Release/yogacore.lib".
Call Stack (most recent call first):
  scripts/ports.cmake:94 (include)
```

**Additional context**
Seems to install windows's .lib static library format without checking its operating system.

**Comment by JackBoosY** [comment]
Hi @handicraftsman, thanks for reporting this issue.
I've fix it, please update vcpkg and rebuild yoga.

Thanks.
