### ISSUE TITLE
[sdl2-mixer[mpg123]] incorrect build on Windows

### ISSUE THREAD

**Issue by tannergooding** [microsoft/vcpkg#8429]
**Host Environment**
- OS: Windows 10 1903, x64
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28103

**To Reproduce**
* `.\vcpkg.exe install sdl2-mixer[mpg123]`
  * Same applies for the other extensions `[libflac]`, `[libmodplug]`, `[libvorbis]`, and `[opusfile]`
* Check the build output logs (`.\buildtrees\sdl2-mixer\install-x64-windows-debg-out.log`
* Observe that `MPG123_DYNAMIC` is set to effectively `.\installed\x64-windows\debug\lib\libmpg123.lib"`
  * `-DMPG123_DYNAMIC=\"C:/repos/vcpkg/installed/x64-windows/debug/lib/libmpg123.lib\"`

**Expected Behavior**
The build should be setting this to the dynamic link library `libmpg123.dll`, rather than the static link library (unless explicitly building with static linking in mind) and should not be resolving the full path to this library (it should instead, likely, be using the relative name and relying on the OS resolution logic to find it).

This ultimately looks to be because the root `CMakeLists.txt` file (https://github.com/microsoft/vcpkg/blob/master/ports/sdl2-mixer/CMakeLists.txt ) is accounting for this and instead just returns whatever `find_library` resolves.

**Comment by tannergooding** [comment]
FYI. @JackBoosY, as it looks like this is fallout from https://github.com/microsoft/vcpkg/pull/8335

**Comment by JackBoosY** [comment]
@tannergooding It's make sense.

**Comment by JackBoosY** [comment]
Hi @tannergooding, thanks for reporting this issue.
I've fixed this issue, please update vcpkg and rebuild sdl2-mixer.
I wish it's the last fix :)

Thanks.
