### ISSUE TITLE
How do I link the same library in debug and release build?

### ISSUE THREAD

**Issue by zhaofeng-shu33** [microsoft/vcpkg#8442]
On windows platform, visual studio is a multi-target build system.  Currently, I use the following way to handle the case when I need to link the same library of different build type (using `googletest` as an example):
```CMake
if(WIN32)
target_link_libraries(TestAll debug ${GTEST_MAIN_LIBRARY_DEBUG} debug ${GTEST_LIBRARY_DEBUG})
target_link_libraries(TestAll optimized ${GTEST_MAIN_LIBRARY} optimized ${GTEST_LIBRARY})
endif()
```
If I only use `target_link_libraries(TestAll ${GTEST_MAIN_LIBRARY} ${GTEST_LIBRARY})` just like on other systems. The compilation is fine but I cannot debug my build for two reasons:

1. dynamic libraries are not copied to Debug directory automatically (maybe vcpkg bug?).
1. I cannot locate the line where my program crashes (It depends on the 3rd party library anyway; if my program does not have bug, the program can run normally by linking release 3rd party library)

I can indeed use the verbose way to link debug 3rd party library in debug build and it works file:

1. debug dynamic libraries are automatically copied to Debug directory.
1. No strange behaviour occurs when debugging my program

I find that some vcpkg port uses a wrapper to handle debug and release linkage.
First it finds the library name, then it resets the library path, for example in `liblemon` port file:
```CMake
SET(LEMON_LIBRARY
  optimized "${CMAKE_CURRENT_LIST_DIR}/../../lib/${LEMON_LIB_NAME}"
  debug "${CMAKE_CURRENT_LIST_DIR}/../../debug/lib/${LEMON_LIB_NAME}"
  CACHE FILEPATH "LEMON library")
```
For this library, the user can use `target_link_libraries` normally without worrying about multi-target linkage problem. But many package ports do not have this convenient way.

There is a [related issue](https://github.com/microsoft/vcpkg/issues/1626#issuecomment-324185781) about my problem. I wonder
what is the proper way to handle such linkage currently.

**Comment by Neumann-A** [comment]
Learn to use CMake targets instead of variables. 
e.g. link against `GTest::GTest` and/or `GTest::Main`
those targets should be setup to handle both cases

**Comment by zhaofeng-shu33** [comment]
Using CMake targets works. Thanks.

**Comment by softempire** [comment]
Can you point me the document for "CMake targets" you mentioned here?

**Comment by zhaofeng-shu33** [comment]
```
find_package(GTest REQUIRED)
target_link_libraries(your_target GTest::GTest GTest::Main)
```
