### ISSUE TITLE
[angelscript] update to 2.34.0

### ISSUE THREAD

**Issue by johannes1971** [microsoft/vcpkg#8445]
Library name: angelscript

New version number: 2.34.0

There appears to be some confusion with the version number. The version that is in vcpkg right now is labeled 2.34.0 but is not the final release version; in particular, it includes a bug whereby the scripting engine cannot catch two exceptions in the same script function. It's also about two months old, while 2.34.0 was released on 22 september 2019 (less than two weeks ago). Could you please update to the latest release version? Thanks :-)

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
