### ISSUE TITLE
[boost 1.71.0] build failed under openSUSE Tumbleweed

### ISSUE THREAD

**Issue by dmn-star** [microsoft/vcpkg#8446]
Building package boost-build[core]:x64-linux...
- Downloading https://github.com/boostorg/build/archive/boost-1.70.0.tar.gz...  **_Why 1.70.0?_**
-- Extracting source /home/dmn/dev/tools/vcpkg/downloads/boostorg-build-boost-1.70.0.tar.gz
-- Applying patch arm64msvc.patch
-- Using source at /home/dmn/dev/tools/vcpkg/buildtrees/boost-build/src/ost-1.70.0-ad28c1be18
-- Using cached /home/dmn/dev/tools/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.70.0/boostcpp.jam...
-- Installing: /home/dmn/dev/tools/vcpkg/packages/boost-build_x64-linux/share/boost-build/copyright
-- Installing: /home/dmn/dev/tools/vcpkg/packages/boost-build_x64-linux/tools/boost-build/boostcpp.jam
-- Bootstrapping...
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-build[core]:x64-linux... done
Installing package boost-build[core]:x64-linux...
Installing package boost-build[core]:x64-linux... done
Elapsed time for package boost-build:x64-linux: 6.46 s
Starting package 18/81: boost-system:x64-linux
Building package boost-system[core]:x64-linux...
-- Downloading https://github.com/boostorg/system/archive/boost-1.71.0.tar.gz...
-- Extracting source /home/dmn/dev/tools/vcpkg/downloads/boostorg-system-boost-1.71.0.tar.gz
-- Using source at /home/dmn/dev/tools/vcpkg/buildtrees/boost-system/src/ost-1.71.0-c6a1ad9630
**_CMake Error at installed/x64-linux/share/boost-build/boost-modular-build.cmake:26 (message):
  Could not find b2_** in
  /home/dmn-star/dev/tools/vcpkg/installed/x64-linux/tools/boost-build
Call Stack (most recent call first):
  ports/boost-system/portfile.cmake:16 (boost_modular_build)
  scripts/ports.cmake:94 (include)

Error: Building package boost-system:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-system:x64-linux
  Vcpkg version: 2019.09.12-unknownhash

**Comment by PhoebeHui** [comment]
@dmn-star, boost has been upgrade to 1.73.0, could you get latest source, and see if this still be a problem for you?

**Comment by dmn-star** [comment]
Works on Ubuntu 20.04 LTS / WSL2 now. An incredibly long  boost module package downloading time! I'll try it on openSUSE later.

**Comment by dmn-star** [comment]
Works on openSUSE Tumbleweed too. Thanks!

**Comment by PhoebeHui** [comment]
Good to know!
