### ISSUE TITLE
[New Port Request] ace+tao

### ISSUE THREAD

**Issue by thkvc** [microsoft/vcpkg#8447]
Library name: ace+tao

Library description: ACE is a C++ framework for implementing distributed and networked applications, TAO is a C++ implementation of the OMG's CORBA standard.

Source repository URL: https://github.com/DOCGroup/ACE_TAO

Project homepage (if different from the source repository): http://download.dre.vanderbilt.edu/

**Comment by cenit** [comment]
./vcpkg install ace

:)

**Comment by thkvc** [comment]
it only install ace

**Comment by jwillemsen** [comment]
See https://github.com/microsoft/vcpkg/pull/8468

**Comment by ordisbold** [comment]
it will install TAO as well.

./vcpkg install ace[tao]

**Comment by ordisbold** [comment]
Oh wow... I didn't even know that that there was request!! Haha...

**Comment by thkvc** [comment]
thank you. i will try it. :)

**Comment by NancyLi1013** [comment]
Hi @thkvc thanks for posting this request. Do you need us to add `tao `as a separate port now?
I noticed that @ordisbold has submitted a PR to add `tao `as a feature for `ace`.
So I don't know whether this can meed you demand.
