### ISSUE TITLE
Create simple survey/voting project to prioritize new vcpkg port request

### ISSUE THREAD

**Issue by 4creators** [microsoft/vcpkg#845]
vcpkg has already added a lot of ports but backlog seen as open issues labelled as "new-port-request" is quite large. I would like to propose creating short and simple survey / voting project-issue  to allow community vote and express it's opinions on ports priority and importance.

**Comment by Mixaill** [comment]
We can simply create Trello board with voting for:
* new ports requests
* ports update requests

where the guys from MSFT and active community members can show their current activity.

**Comment by ras0219-msft** [comment]
Note that GitHub can easily filter and sort by thumbs-up:
https://github.com/Microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+label%3A%22new+port+request+-+consider+making+a+PR%21%22+sort%3Areactions-%2B1-desc

This is what we have been looking at so far when we take a break from infrastructure work to add new packages -- however most ports are contributed by awesome community members (like @Mixaill and many many more).

We also tend to focus on packages that require a lot more effort to package that would be beyond the reach of many community members (such as ffmpeg, which required adding MSYS2 support).

**Comment by PhoebeHui** [comment]
Looks this issue can be closed, please reopen it if I misunderstand something here.
