### ISSUE TITLE
[itk] build failure

### ISSUE THREAD

**Issue by thkvc** [microsoft/vcpkg#8450]
**Host Environment**
- OS: [Windows]
- Compiler: msvc

**To Reproduce**
`./vcpkg install itk`

**Reason**
in portfile.cmake set "-DITK_USE_64BITS_IDS=ON"
x64 build ok, x86 build error

**Comment by drescherjm** [comment]
For me it built fine without that.

**Comment by thkvc** [comment]
default is "-DITK_USE_64BITS_IDS=ON", it build ok in x64 but error in x86

**Comment by thkvc** [comment]
good job. thank @JackBoosY

**Comment by JackBoosY** [comment]
@thkvc Please update vcpkg and rebuild itk.

Thanks.
