### ISSUE TITLE
[New Port Request] <OIS>

### ISSUE THREAD

**Issue by zoloypzuo** [microsoft/vcpkg#8451]
Library name: OIS

Library description: Cross Platform Object Oriented Input Lib System. Meant to be very robust and compatiable with many systems and operating systems.

Source repository URL: https://github.com/wgois/OIS

Project homepage (if different from the source repository): /

Anything else that is useful to know when adding (such as optional features the library may have that should be included): /

**Comment by vpaladino778** [comment]
I'll see if i can make this port

**Comment by NancyLi1013** [comment]
Since this port has been added, I'm going to close this issue for now.
@vpaladino778  Thanks for your efforts to this issue.
