### ISSUE TITLE
Does function vcpkg_replace_string replace all instances

### ISSUE THREAD

**Issue by skychef** [microsoft/vcpkg#8456]
https://github.com/microsoft/vcpkg/blob/47c6b3f557f305969bb271d10ad4b0b0d936ad23/scripts/cmake/vcpkg_replace_string.cmake#L4

Does the function replace just the first instance matched or every single instance found inside the file?

Could the line

> #  Replace a string in a file.

Be modified to reflect the exact behaviour please? I looked at the documentation at https://vcpkg.readthedocs.io/ and was unable to find information about this.

Thanks!

**Comment by mohsan-604** [comment]
https://github.com/microsoft/vcpkg/blob/47c6b3f557f305969bb271d10ad4b0b0d936ad23/scripts/cmake/vcpkg_replace_string.cmake#L4

**Comment by skychef** [comment]
Answering my own question here:
https://cmake.org/cmake/help/latest/command/string.html#replace
It looks to be cmake, so:

> Replace all occurrences of <match_string> in the <input> with <replace_string> and store the result in the <output_variable>.
