### ISSUE TITLE
[New Port Request] libb2

### ISSUE THREAD

**Issue by kotlinFan** [microsoft/vcpkg#8459]
Library name: BLAKE2

Library description: Fast secure hashing. C library providing BLAKE2b, BLAKE2s, BLAKE2bp, BLAKE2sp 

Source repository URL: https://github.com/BLAKE2/libb2

Project homepage: https://blake2.net/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): Reference implementations is usefull too: https://github.com/BLAKE2/BLAKE2

**Comment by NancyLi1013** [comment]
Hi @kotlinFan thanks for posting this request.
This port has been added to vcpkg. Please update vcpkg and try to use it.
