### ISSUE TITLE
[New Port Request] upb

### ISSUE THREAD

**Issue by jozefizso** [microsoft/vcpkg#8460]
Library name: μpb (often written 'upb')

Library description: a small protobuf implementation in C

Source repository URL: https://github.com/protocolbuffers/upb/

Project homepage (if different from the source repository): https://github.com/protocolbuffers/upb/

it look slike it library is now required to build grpc 1.24 (https://github.com/grpc/grpc/issues/20392)

**Comment by JackBoosY** [comment]
Hi @jozefizso, thanks for reporting this issue.
This port has been added in vcpkg, please update vcpkg and try to install it.

Thanks.
