### ISSUE TITLE
[libpq] update to 12.0 / improvements to vcpkg_configure_make

### ISSUE THREAD

**Issue by TheScarfix** [microsoft/vcpkg#8462]
PostgreSQL 12.0 was just released and I am trying to get it to work with the new vcpkg_configure_make command. However psql needs a C99 compliant compiler, which cl is not. So I think I would need the possibility to use gcc with vcpkg_configure_cmake on Windows.

**Comment by Neumann-A** [comment]
How about using clang-cl instead of gcc?

**Comment by NancyLi1013** [comment]
The related PR #8551.
