### ISSUE TITLE
[New Port Request] Gappa

### ISSUE THREAD

**Issue by vlj** [microsoft/vcpkg#8467]
Library name:
Gappa 

Library description:
It's a tool that validate floating point computation. The workflow is : the developper writes a file describing the formula and the assumption on the input and then the tool returns intervals where the output of the formula belongs and a proof that can be mechanicaly checked of this result.

Source repository URL:
http://gappa.gforge.inria.fr/
Project homepage (if different from the source repository):
http://gappa.gforge.inria.fr/

The tool is gcc centered ,I opened a PR with the port (checked only on Windows with msvc) : 
https://github.com/microsoft/vcpkg/pull/8466

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
