### ISSUE TITLE
How to configure debug project to run released libraries from the vcpkg

### ISSUE THREAD

**Issue by davidbun** [microsoft/vcpkg#8469]
Most of the time, the debug version of the project does not require to work with debug version of the library installed by the vcpkg. How can I configure the project to work all the time with released libraries / DLLs? How easy it can be reconfigured to run the debug version of libraries (if required)?
A lot of thanks in advance

**Comment by Neumann-A** [comment]
If you use CMake

`-DCMAKE_MAP_IMPORTED_CONFIG_DEBUG="Release;"`

the ; is required so that `CMAKE_MAP_IMPORTED_CONFIG_DEBUG` contains an empty string "" which maps to `IMPORTED_CONFIGURATION`

**Comment by Neumann-A** [comment]
>I use VS2017 and would like to modify the VS2017 project settings to have an option to run the debug version of my project with release versions of the libraries installed by vcpkg

That sounds like a really bad idea. -> Iterator debug level and other problems.

**Comment by PhoebeHui** [comment]
We would suggest not to do that, mixing debug and release code is bad practice.
See https://stackoverflow.com/questions/11658915/mixing-debug-and-release-library-binary-bad-practice/55816027.
