### ISSUE TITLE
How do I configure vcpkg for wsl building?

### ISSUE THREAD

**Issue by Sdynest** [microsoft/vcpkg#8470]
I installed WSL and configured it through bash vcpkg and the necessary libraries as I used sqlite3 in the tutorial, but Visual Studio cannot find libraries with `x64-linux` triplet. Can you help me with that issue.

`CMake Warning at /mnt/c/programs/vcpkg/scripts/buildsystems/vcpkg.cmake:104 (message):
  There are no libraries installed for the Vcpkg triplet x64-linux.		/mnt/c/programs/vcpkg/scripts/buildsystems/vcpkg.cmake`

**Comment by Voskrese** [comment]
```
sudo apt-get update -y && 
sudo apt-get upgrade -y && 
sudo apt-get dist-upgrade -y && 
sudo apt-get install build-essential software-properties-common -y && 
sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y && 
sudo apt-get update -y && 
sudo apt-get install gcc-9 g++-9 -y && 
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 80 --slave /usr/bin/g++ g++ /usr/bin/g++-9 && 
sudo update-alternatives --config gcc
```

Linux:~/$ `./bootstrap-vcpkg.sh`

`vcpkg install sqlite3:x64-linux`

**Comment by Voskrese** [comment]
https://github.com/microsoft/vcpkg/issues/8461#issuecomment-538700129

VisualStudio will not use libraries built under GCC

**Comment by Sdynest** [comment]
I want to build a project for Linux in Windows using VS19 and familiar tools. Having looked for a way to do this, I came across an article that says you can build a Linux project from VS using WSL and it misled me.

**Comment by Voskrese** [comment]
the project can be created in MSVC for Linux and work in WSL from under MSVC, but everything that is created in WSL for Linux can be used ONLY under Linux

**Comment by Sdynest** [comment]
Ok, I understood that, thank you
