### ISSUE TITLE
[libyuv] Missing includes

### ISSUE THREAD

**Issue by chrisaverage** [microsoft/vcpkg#8471]
libyuv has a `libyuv.h` header placed in the include directory, but it's only a "container" header and all includes are in `/libyuv` subdirectory. This subdirectory is not copied from build dir though.

**Comment by vpaladino778** [comment]
Just to clarify, in order to solve this problem, the `/libyuv` subfolder needs to be copied to the `/include` directory?

**Comment by chrisaverage** [comment]
Yes. I believe the original CMakeLists.txt file did exactly that, but the port has a `fix_cmakelists.patch` patch file attached that changes it to just that single header file. I didn't want to just change that back since I don't know the intent of the author behind it.

**Comment by AlvinZhangH** [comment]
Hi @chrisaverage thanks for posting this issue. This issue has been fixed. Please try to update vcpkg and use it.
