### ISSUE TITLE
freexl build failure - NMAKE fatal error U1065 invalid option 'j'

### ISSUE THREAD

**Issue by timautry** [microsoft/vcpkg#8472]
**Host Environment**
- OS: Windows 10 1903 18362.388
- Compiler:  VS2017 v15.9.16 and VS2019 v16.3.2

**To Reproduce**
`./vcpkg install freexl` 
(My default triplet is x64-windows and vcpkg is built using the -win64 option)

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
This is the same for both VS2017 and VS2019 except for the vcpkg directory

SYSTEM@ANDROMEDA 10/06/2019 18:29:22 D:\Git\vs2019
->vcpkg install freexl 
The following packages will be built and installed:
    freexl[core]:x64-windows
Starting package 1/21 freexl:x64-windows
Building package freexl[core]:x64-windows...
-- Using cached D:/Git/vcpkg.downloads/freexl-1.0.4.tar.gz
-- Using source at D:/Git/vs2019/buildtrees/freexl/src/freexl-1-3b5078fc45
-- Building and installing x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/nmake.exe" /NOLOGO /G /U -j 17 -f makefile.vc all install INSTALLDIR=D:/Git/vs2019/packages/freexl_x64-windows/debug INSTALLED_ROOT="D:/Git/vs2019/installed/x64-windows/debug" INST_DIR="D:/Git/vs2019/packages/freexl_x64-windows/debug" LINK_FLAGS=/debug "LIBS_ALL="D:/Git/vs2019/installed/x64-windows/debug/lib/libiconv.lib"       "D:/Git/vs2019/installed/x64-windows/debug/lib/libcharset.lib""
    Working Directory: D:/Git/vs2019/buildtrees/freexl/x64-windows-dbg
    Error code: 2
    See logs for more information:
      D:\Git\vs2019\buildtrees\freexl\build-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_nmake.cmake:174 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_install_nmake.cmake:64 (vcpkg_build_nmake)
  ports/freexl/portfile.cmake:27 (vcpkg_install_nmake)
  scripts/ports.cmake:94 (include)

Error: Building package freexl:x64-windows failed with: BUILD_FAILED
-Please attach any additional failure logs mentioned in the console output.

[build-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/3694958/build-x64-windows-dbg-err.log)

**Additional context**
This is from the latest vcpkg "git pull" from git to my two different VCPKG roots, one for VS2017 and one for VS2019, performed at ~ 18:00 US Eastern Time.

**Comment by Voskrese** [comment]
@JackBoosY 
https://github.com/microsoft/vcpkg/pull/8267/commits/72af04ffe5ac68ec008299797636b8c32aef2ad1

only
`scripts/cmake/vcpkg_build_nmake.cmake`

delete `-j ${VCPKG_CONCURRENCY}`

**Comment by JackBoosY** [comment]
Hi @timautry, thanks for reporting this issue.
I've fixed it, please update vcpkg and rebuild freexl.

Thanks.
