### ISSUE TITLE
x264 build failure - /usr/bin/bash -j invalid option

### ISSUE THREAD

**Issue by ghost** [microsoft/vcpkg#8473]
**Host Environment**
-OS: Windows 10 1903 18362.388
-Compiler: VS2017 v15.9.16 and VS2019 v16.3.2

**To Reproduce**
`./vcpkg install x264`
(My default triplet is x64-windows and vcpkg is built using the -win64 option)

**Failure logs** 
-Cut and past the appropriate build messages from the console output.

This is the same for both VS2017 and VS2019 except for the vcpkg directory

SYSTEM@ANDROMEDA 10/06/2019 18:30:59 D:\Git\vs2019
->vcpkg install x264
The following packages will be built and installed:
    x264[core]:x64-windows
Starting package 1/1: x264:x64-windows
Building package x264[core]:x64-windows...
-- Using cached D:/Git/vcpkg.downloads/mirror-x264-303c484ec828ed0d8bfe743500e70314d026c3bd.tar.gz
-- Using source at D:/Git/vs2019/buildtrees/x264/src/14d026c3bd-bca2ebf740
-- Using generator make
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: D:/Git/vcpkg.downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c -j 17 make
    Working Directory: D:/Git/vs2019/buildtrees/x264/x64-windows-dbg
    See logs for more information:
      D:\Git\vs2019\buildtrees\x264\build-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:123 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:24 (vcpkg_build_make)
  ports/x264/portfile.cmake:33 (vcpkg_install_make)
  scripts/ports.cmake:94 (include)

Error: Building package x264:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: x264:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.
[build-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/3694966/build-x64-windows-dbg-err.log)

-Please attach any additional failure logs mentioned in the console output.

**Additional context**
This is from the latest vcpkg "git pull" from git to my two different VCPKG roots, one for VS2017 and one for VS2019, performed at ~ 18:00 US Eastern Time.

**Comment by Voskrese** [comment]
@JackBoosY 

not correct
`msys64/usr/bin/bash.exe --noprofile --norc -c -j 17 make`

it must be
`msys64/usr/bin/bash.exe --noprofile --norc -c make -j 17 `

https://github.com/microsoft/vcpkg/commit/72af04ffe5ac68ec008299797636b8c32aef2ad1

?
`COMMAND ${MAKE} ${MAKE_OPTS} -j ${VCPKG_CONCURRENCY} `

**Comment by oracleoftroy** [comment]
I have the same error and have been looking into working around it. -j is an option for make, but is being passed into bash instead.

The issue stems from scripts/cmake/vcpkg_build_make.cmake lines 55 and 57-58, where the make command is being set in the options. When the make command is assembled on line 124, it sticks in some extra options in the wrong spot.

line 124: `${MAKE} -j ${VCPKG_CONCURRENCY} ${MAKE_OPTS}`
expands to: `path/to/bash.exe --noprofile --norc -c -j <some number> make`
instead of : `path/to/bash.exe --noprofile --norc -c make -j <some number>`

I changed line 55 to:
`set(MAKE ${BASH} --noprofile --norc -c ${_VCPKG_PROJECT_SUBPATH}make)`

line 57-58 to:
```
set(MAKE_OPTS "")
set(INSTALL_OPTS "install")
```

This gets around the error, though it might be better to move the -j option to MAKE_OPTS instead of subverting the options and adding it willy-nilly like it currently does.

Sadly, the build still fails when trying to do the rename on line 37 of the portfile.cmake for x254

`file(RENAME ${CURRENT_PACKAGES_DIR}/bin/x264.exe ${CURRENT_PACKAGES_DIR}/tools/x264/x264.exe)`

The error is

```
file RENAME failed to rename

    D:/Tools/vcpkg/packages/x264_x64-windows/bin/x264.exe

  to

    D:/Tools/vcpkg/packages/x264_x64-windows/tools/x264/x264.exe

  because: File exists
```

I find this odd because the `x264_x64-windows\tools\x264` directory is completely empty, so I'm not sure what file it thinks exists. I also do not have a `x264_x64-windows/bin` directory.

**Comment by Christsnatcher** [comment]
I just updated vcpkg and - out of curiousity - tried to install x264, now getting the same error message as @oracleoftroy:

For x86-windows:

```
D:\Code\Repos\vcpkg>vcpkg install x264
The following packages will be built and installed:
    x264[core]:x86-windows
Starting package 1/1: x264:x86-windows
Building package x264[core]:x86-windows...
-- Using cached D:/Code/Repos/vcpkg/downloads/mirror-x264-303c484ec828ed0d8bfe743500e70314d026c3bd.tar.gz
-- Using source at D:/Code/Repos/vcpkg/buildtrees/x264/src/14d026c3bd-bca2ebf740
-- Using generator make
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Configuring x86-windows-dbg
-- Configuring x86-windows-rel
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing x86-windows-dbg
-- Installing x86-windows-rel
CMake Error at ports/x264/portfile.cmake:37 (file):
  file RENAME failed to rename

    D:/Code/Repos/vcpkg/packages/x264_x86-windows/bin/x264.exe

  to

    D:/Code/Repos/vcpkg/packages/x264_x86-windows/tools/x264/x264.exe

  because: File exists

Call Stack (most recent call first):
  scripts/ports.cmake:94 (include)
```
For x64-windows:

```
D:\Code\Repos\vcpkg>vcpkg install x264:x64-windows
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpk
The following packages will be built and installed:
    x264[core]:x64-windows
Starting package 1/1: x264:x64-windows
Building package x264[core]:x64-windows...
-- Using cached D:/Code/Repos/vcpkg/downloads/mirror-x264-303c484ec828ed0d8bfe743500e70314d026c3bd.tar.gz
-- Using source at D:/Code/Repos/vcpkg/buildtrees/x264/src/14d026c3bd-bca2ebf740
-- Using generator make
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing x64-windows-dbg
-- Installing x64-windows-rel
CMake Error at ports/x264/portfile.cmake:37 (file):
  file RENAME failed to rename

    D:/Code/Repos/vcpkg/packages/x264_x64-windows/bin/x264.exe

  to

    D:/Code/Repos/vcpkg/packages/x264_x64-windows/tools/x264/x264.exe

  because: File exists

Call Stack (most recent call first):
  scripts/ports.cmake:94 (include)
```
The "toold" directory is stays empty during the building process, neither an "x264" subfolder nor an x264.exe are present there at any time, so I honestly don't know why the rename command fails. Maybe "copy" would be better here?

**Comment by spindensity** [comment]
After updating vcpkg, getting the same problem here.

**Stdout**

```
Building package x264[core]:x64-windows...
-- Using cached D:/Repository/vcpkg/downloads/mirror-x264-303c484ec828ed0d8bfe743500e70314d026c3bd.tar.gz
-- Using source at D:/Repository/vcpkg/buildtrees/x264/src/14d026c3bd-bca2ebf740
-- Using generator make
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing x64-windows-dbg
-- Installing x64-windows-rel
CMake Error at ports/x264/portfile.cmake:37 (file):
  file RENAME failed to rename

    D:/Repository/vcpkg/packages/x264_x64-windows/bin/x264.exe

  to

    D:/Repository/vcpkg/packages/x264_x64-windows/tools/x264/x264.exe

  because: File exists

Call Stack (most recent call first):
  scripts/ports.cmake:94 (include)


Error: Building package x264:x64-windows failed with: BUILD_FAILED
```

**Comment by JackBoosY** [comment]
`make: Nothing to be done for 'default'.` I'm looking into it.

**Comment by jasjuang** [comment]
Just ran into the same problem and looking forward to the fix

**Comment by JackBoosY** [comment]
Hi @timautry, thanks for reporting this issue.
I've fixed it, please update vcpkg and rebuild x264.

Thanks.

**Comment by timautry** [comment]
Thank you @JackBoosY - works great on both latest builds of VS2017 and VS2019 - super work and I appreciate it very much. Take care and have a wonderful week!!!

**Comment by VFoV** [comment]
I'm coming across a similar error message when trying to build x264. Let me know if I should post this as a new issue, I suspect it will be an easy fix as I am a novice and unfamiliar with compilers.

OS: Windows 10 1909
Compiler: VS 2019 16.6.3

C:\vcpkg-master> .\vcpkg install x264
Computing installation plan...
The following packages will be built and installed:
    x264[core]:x86-windows
Starting package 1/1: x264:x86-windows
Building package x264[core]:x86-windows...
-- Using cached C:/vcpkg-master/downloads/mirror-x264-303c484ec828ed0d8bfe743500e70314d026c3bd.tar.gz
-- Using source at C:/vcpkg-master/buildtrees/x264/src/14d026c3bd-bca2ebf740
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Configuring x86-windows-dbg
-- Configuring x86-windows-rel
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/vcpkg-master/downloads/tools/msys2/msys64/usr/bin/make.exe -j 9 --trace -f Makefile all
    Working Directory: C:/vcpkg-master/buildtrees/x264/x86-windows-dbg
    See logs for more information:
      C:\vcpkg-master\buildtrees\x264\build-x86-windows-dbg-out.log
      C:\vcpkg-master\buildtrees\x264\build-x86-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:200 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:24 (vcpkg_build_make)
  ports/x264/portfile.cmake:29 (vcpkg_install_make)
  scripts/ports.cmake:76 (include)


Error: Building package x264:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: x264:x86-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.
[build-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4878730/build-x86-windows-dbg-out.log)
[build-x86-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/4878732/build-x86-windows-dbg-err.log)

**Comment by Christsnatcher** [comment]
Hello,

I just checked and the package build fails both for x86 and x64 again as well, this time with a fatal MSYS2 error (it seems configure arguments are passed to link.exe instead, configure isn't run at all):

D:\Code\Repos\vcpkg>vcpkg install x264
Computing installation plan...
The following packages will be built and installed:
    x264[core]:x86-windows
Starting package 1/1: x264:x86-windows
Building package x264[core]:x86-windows...
-- Downloading https://github.com/mirror/x264/archive/303c484ec828ed0d8bfe743500e70314d026c3bd.tar.gz...
-- Extracting source D:/Code/Repos/vcpkg/downloads/mirror-x264-303c484ec828ed0d8bfe743500e70314d026c3bd.tar.gz
-- Applying patch uwp-cflags.patch
-- Using source at D:/Code/Repos/vcpkg/buildtrees/x264/src/14d026c3bd-bca2ebf740
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Configuring x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: D:/Code/Repos/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc --debug -c " CC='D:/Code/Repos/vcpkg/downloads/tools/msys2/msys64/usr/share/automake-1.16/compile cl.exe -nologo' CXX='D:/Code/Repos/vcpkg/downloads/tools/msys2/msys64/usr/share/automake-1.16/compile cl.exe -nologo' LD='link.exe -verbose' AR='D:/Code/Repos/vcpkg/downloads/tools/msys2/msys64/usr/share/automake-1.16/ar-lib lib.exe -verbose' RANLIB=':' CCAS=':' NM='dumpbin.exe -symbols -headers -all' DLLTOOL='link.exe -verbose -dll' ./../src/14d026c3bd-bca2ebf740/configure --build=x86_64-pc-mingw32 --target=i686-pc-mingw32 --host=i686-pc-mingw32 --enable-strip --disable-lavf --disable-swscale --disable-avs --disable-ffms --disable-gpac --disable-lsmash --disable-asm --enable-debug --disable-silent-rules --verbose --enable-shared --disable-static --prefix=/D/Code/Repos/vcpkg/installed/x86-windows/debug --bindir='${prefix}'/../tools/x264/debug/bin --sbindir='${prefix}'/../tools/x264/deb
ug/sbin --includedir='${prefix}'/../include --datarootdir='${prefix}'/share/x264"
    Working Directory: D:/Code/Repos/vcpkg/buildtrees/x264/x86-windows-dbg
    Error code: 1
    See logs for more information:
      D:\Code\Repos\vcpkg\buildtrees\x264\config-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:461 (vcpkg_execute_required_process)
  ports/x264/portfile.cmake:15 (vcpkg_configure_make)
  scripts/ports.cmake:76 (include)


Error: Building package x264:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: x264:x86-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

D:\Code\Repos\vcpkg>

Find my log files attached, many thanks in advance for helping!
[x264.zip](https://github.com/microsoft/vcpkg/files/4879993/x264.zip)

**Comment by JackBoosY** [comment]
@VFoV Can you make sure your vcpkg is latest?

**Comment by VFoV** [comment]
> @VFoV Can you make sure your vcpkg is latest?

I've just reinstalled and ran the bootstrapping and integration and run the command:

C:\vcpkg-master> .\vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

**Comment by VFoV** [comment]
> @VFoV Can you make sure your vcpkg is latest?

Hello, I re-cloned vcpkg from the github page, re-ran the boostrapping and integration then ran .\vcpkg update. I then ran the x264 install again and 
[config.log](https://github.com/microsoft/vcpkg/files/4884165/config.log)
got this error:

Starting package 68/79: x264:x64-windows
Building package x264[core]:x64-windows...
-- Downloading https://github.com/mirror/x264/archive/303c484ec828ed0d8bfe743500e70314d026c3bd.tar.gz...
-- Extracting source C:/vcpkg/downloads/mirror-x264-303c484ec828ed0d8bfe743500e70314d026c3bd.tar.gz
-- Applying patch uwp-cflags.patch
-- Using source at C:/vcpkg/buildtrees/x264/src/14d026c3bd-bca2ebf740
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc --debug -c " CC='C:/vcpkg/downloads/tools/msys2/msys64/usr/share/automake-1.16/compile cl.exe -nologo' CXX='C:/vcpkg/downloads/tools/msys2/msys64/usr/share/automake-1.16/compile cl.exe -nologo' LD='link.exe -verbose' AR='C:/vcpkg/downloads/tools/msys2/msys64/usr/share/automake-1.16/ar-lib lib.exe -verbose' RANLIB=':' CCAS=':' NM='dumpbin.exe -symbols -headers -all' DLLTOOL='link.exe -verbose -dll' ./../src/14d026c3bd-bca2ebf740/configure --build=x86_64-pc-mingw32 --target=x86_64-pc-mingw32 --host=x86_64-pc-mingw32 --enable-strip --disable-lavf --disable-swscale --disable-avs --disable-ffms --disable-gpac --disable-lsmash --disable-asm --enable-debug --disable-silent-rules --verbose --enable-shared --disable-static --prefix=/C/vcpkg/installed/x64-windows/debug --bindir='${prefix}'/../tools/x264/debug/bin --sbindir='${prefix}'/../tools/x264/debug/sbin --includedir='${prefix}'/../include --datarootdir='${prefix}'/share/x264"
    Working Directory: C:/vcpkg/buildtrees/x264/x64-windows-dbg
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\x264\config-x64-windows-dbg-out.log
[config-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4884161/config-x64-windows-dbg-out.log)

**Comment by Christsnatcher** [comment]
Hello,

I'm back to this topic because I run into the very same issue as described by @VFoV when trying to build x264 x86 / x64 via vcpkg, here're the error messages:

**x86-windows:**

```
D:\Code\Repos\vcpkg>vcpkg install x264:x86-windows
Computing installation plan...
The following packages will be built and installed:
    x264[core]:x86-windows
Starting package 1/1: x264:x86-windows
Building package x264[core]:x86-windows...
-- Downloading https://github.com/mirror/x264/archive/303c484ec828ed0d8bfe743500e70314d026c3bd.tar.gz...
-- Extracting source D:/Code/Repos/vcpkg/downloads/mirror-x264-303c484ec828ed0d8bfe743500e70314d026c3bd.tar.gz
-- Applying patch uwp-cflags.patch
-- Using source at D:/Code/Repos/vcpkg/buildtrees/x264/src/14d026c3bd-bca2ebf740
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Configuring x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: D:/Code/Repos/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc --debug -c " CC='D:/Code/Repos/vcpkg/downloads/tools/msys2/msys64/usr/share/automake-1.16/compile cl.exe -nologo' CXX='D:/Code/Repos/vcpkg/downloads/tools/msys2/msys64/usr/share/automake-1.16/compile cl.exe -nologo' LD='link.exe -verbose' AR='D:/Code/Repos/vcpkg/downloads/tools/msys2/msys64/usr/share/automake-1.16/ar-lib lib.exe -verbose' RANLIB=':' CCAS=':' NM='dumpbin.exe -symbols -headers -all' DLLTOOL='link.exe -verbose -dll' ./../src/14d026c3bd-bca2ebf740/configure --build=x86_64-pc-mingw32 --target=i686-pc-mingw32 --host=i686-pc-mingw32 --enable-strip --disable-lavf --disable-swscale --disable-avs --disable-ffms --disable-gpac --disable-lsmash --disable-asm --enable-debug --disable-silent-rules --verbose --enable-shared --disable-static --prefix=/D/Code/Repos/vcpkg/installed/x86-windows/debug --bindir='${prefix}'/../tools/x264/debug/bin --sbindir='${prefix}'/../tools/x264/deb
ug/sbin --includedir='${prefix}'/../include --datarootdir='${prefix}'/share/x264"
    Working Directory: D:/Code/Repos/vcpkg/buildtrees/x264/x86-windows-dbg
    Error code: 1
    See logs for more information:
      D:\Code\Repos\vcpkg\buildtrees\x264\config-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:461 (vcpkg_execute_required_process)
  ports/x264/portfile.cmake:15 (vcpkg_configure_make)
  scripts/ports.cmake:76 (include)


Error: Building package x264:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: x264:x86-windows
  Vcpkg version: 2020.06.15-nohash
```

**x64-windows:**

```
D:\Code\Repos\vcpkg>vcpkg install x264:x64-windows
Computing installation plan...
The following packages will be built and installed:
    x264[core]:x64-windows
Starting package 1/1: x264:x64-windows
Building package x264[core]:x64-windows...
-- Using cached D:/Code/Repos/vcpkg/downloads/mirror-x264-303c484ec828ed0d8bfe743500e70314d026c3bd.tar.gz
-- Using source at D:/Code/Repos/vcpkg/buildtrees/x264/src/14d026c3bd-bca2ebf740
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: D:/Code/Repos/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc --debug -c " CC='D:/Code/Repos/vcpkg/downloads/tools/msys2/msys64/usr/share/automake-1.16/compile cl.exe -nologo' CXX='D:/Code/Repos/vcpkg/downloads/tools/msys2/msys64/usr/share/automake-1.16/compile cl.exe -nologo' LD='link.exe -verbose' AR='D:/Code/Repos/vcpkg/downloads/tools/msys2/msys64/usr/share/automake-1.16/ar-lib lib.exe -verbose' RANLIB=':' CCAS=':' NM='dumpbin.exe -symbols -headers -all' DLLTOOL='link.exe -verbose -dll' ./../src/14d026c3bd-bca2ebf740/configure --build=x86_64-pc-mingw32 --target=x86_64-pc-mingw32 --host=x86_64-pc-mingw32 --enable-strip --disable-lavf --disable-swscale --disable-avs --disable-ffms --disable-gpac --disable-lsmash --disable-asm --enable-debug --disable-silent-rules --verbose --enable-shared --disable-static --prefix=/D/Code/Repos/vcpkg/installed/x64-windows/debug --bindir='${prefix}'/../tools/x264/debug/bin --sbindir='${prefix}'/../tools/x264
/debug/sbin --includedir='${prefix}'/../include --datarootdir='${prefix}'/share/x264"
    Working Directory: D:/Code/Repos/vcpkg/buildtrees/x264/x64-windows-dbg
    Error code: 1
    See logs for more information:
      D:\Code\Repos\vcpkg\buildtrees\x264\config-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:461 (vcpkg_execute_required_process)
  ports/x264/portfile.cmake:15 (vcpkg_configure_make)
  scripts/ports.cmake:76 (include)


Error: Building package x264:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: x264:x64-windows
  Vcpkg version: 2020.06.15-nohash
```

It looks as if configure arguments were passed to link.exe instead, but apparently the src itself is flawed: I tried to build the program using my personal MSYS2 installation and x86 failed with exactly the same "No C compiler found" error when running ./configure, while the x64 build succeeded. Maybe x264 does not support 32-bit builds in the first place? But even if that would be true it would unfortunately not explain why the x64-windows build also fails with vcpkg. Find all my logs attached, thank you!
[x264.zip](https://github.com/microsoft/vcpkg/files/4886993/x264.zip)

**Comment by JackBoosY** [comment]
In config.log:
```
checking for -Werror=unknown-warning-option... no
Failed commandline was:
--------------------------------------------------
F:/vcpkg/downloads/tools/msys2/msys64/usr/share/automake-1.16/compile cl.exe -nologo conftest.c  -D_WIN32_WINNT=0x0601 -DWIN32_LEAN_AND_MEAN -DWIN32 -D_WINDOWS -MDd -D_DEBUG -Ob0 -Od  -Wall -I. -I$(SRCPATH) -D_POSIX_C_SOURCE=200112L  -Werror=unknown-warning-option  -LF:/vcpkg/installed/x86-windows/debug/lib -VERBOSE -no-undefined -machine:x86  -o conftest
./../src/14d026c3bd-bca2ebf740.clean/configure: line 158: F:/vcpkg/downloads/tools/msys2/msys64/usr/share/automake-1.16/compile: No such file or directory
--------------------------------------------------
Failed program was:
--------------------------------------------------
int main (void) {  return 0; }
--------------------------------------------------
checking for -lshell32... no
Failed commandline was:
--------------------------------------------------
F:/vcpkg/downloads/tools/msys2/msys64/usr/share/automake-1.16/compile cl.exe -nologo conftest.c  -D_WIN32_WINNT=0x0601 -DWIN32_LEAN_AND_MEAN -DWIN32 -D_WINDOWS -MDd -D_DEBUG -Ob0 -Od  -Wall -I. -I$(SRCPATH) -D_POSIX_C_SOURCE=200112L  -lshell32  -LF:/vcpkg/installed/x86-windows/debug/lib -VERBOSE -no-undefined -machine:x86  -o conftest
./../src/14d026c3bd-bca2ebf740.clean/configure: line 158: F:/vcpkg/downloads/tools/msys2/msys64/usr/share/automake-1.16/compile: No such file or directory
--------------------------------------------------
Failed program was:
--------------------------------------------------
int main (void) {  return 0; }
--------------------------------------------------
checking whether windres works... no
Failed commandline was:
--------------------------------------------------
windres --target=pe-i386  -o conftest.o conftest.rc
/bin/sh: gcc: command not found
windres: preprocessing failed.
--------------------------------------------------
Failed program was:
--------------------------------------------------
0 RCDATA {0}
--------------------------------------------------
checking whether !WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP) is true... no
--------------------------------------------------
./../src/14d026c3bd-bca2ebf740.clean/configure: line 189: F:/vcpkg/downloads/tools/msys2/msys64/usr/share/automake-1.16/compile: No such file or directory
--------------------------------------------------
Failed program was:
--------------------------------------------------
#include <winapifamily.h>
#if !(!WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)) 
#error  
#endif 
--------------------------------------------------
x264 configure script
Command line options: "--build=i686-pc-mingw32" "--target=i686-pc-mingw32" "--host=i686-pc-mingw32" "--enable-strip" "--disable-lavf" "--disable-swscale" "--disable-avs" "--disable-ffms" "--disable-gpac" "--disable-lsmash" "--disable-asm" "--enable-debug" "--disable-silent-rules" "--verbose" "--enable-shared" "--disable-static" "--prefix=/F/vcpkg/installed/x86-windows/debug" "--bindir=${prefix}/../tools/x264/debug/bin" "--sbindir=${prefix}/../tools/x264/debug/sbin" "--includedir=${prefix}/../include" "--datarootdir=${prefix}/share/x264"

checking whether F:/vcpkg/downloads/tools/msys2/msys64/usr/share/automake-1.16/compile cl.exe -nologo works... no
Failed commandline was:
--------------------------------------------------
F:/vcpkg/downloads/tools/msys2/msys64/usr/share/automake-1.16/compile cl.exe -nologo conftest.c -m32  -D_WIN32_WINNT=0x0601 -DWIN32_LEAN_AND_MEAN -DWIN32 -D_WINDOWS -MDd -D_DEBUG -Ob0 -Od  -Wall -I. -I$(SRCPATH) -D_POSIX_C_SOURCE=200112L    -m32 -LF:/vcpkg/installed/x86-windows/debug/lib -VERBOSE -no-undefined -machine:x86   -Wl,--large-address-aware -Wl,--dynamicbase,--nxcompat,--tsaware -o conftest
./../src/14d026c3bd-bca2ebf740.clean/configure: line 158: F:/vcpkg/downloads/tools/msys2/msys64/usr/share/automake-1.16/compile: No such file or directory
--------------------------------------------------
Failed program was:
--------------------------------------------------
int main (void) {  return 0; }
--------------------------------------------------
DIED: No working C compiler found.
```

@Neumann-A Could you please take a look?

Thanks.

**Comment by JackBoosY** [comment]
`F:/vcpkg/downloads/tools/msys2/msys64/usr/share/automake-1.16/compile: No such file or directory`

Only have `F:/vcpkg/downloads/tools/msys2/msys64/usr/share/automake-1.15` on my machine.

**Comment by JackBoosY** [comment]
I think #11836 should fix this issue.

**Comment by Christsnatcher** [comment]
Looks good, let's hope for the best. Thank you all very much!

**Comment by timautry** [comment]
I close, I no longer use product.

**Comment by Christsnatcher** [comment]
Well, but other people, e.g. myself still do, you know? So please don't stop working on a fix, many thanks!

**Comment by JackBoosY** [comment]
@Christsnatcher Anyway, I'm still tracking this issue.

**Comment by Christsnatcher** [comment]
@JackBoosY Thank you very much, that's really appreciated.
