### ISSUE TITLE
google-cloud-cpp build failure 

### ISSUE THREAD

**Issue by heylaender** [microsoft/vcpkg#8475]
**Host Environment**
- OS: Windows

**To Reproduce**
.\vcpkg.exe install google-cloud-cpp:x86-windows-static

**Failure logs** 
Error: Cannot find definition for package `googleapis`.

**Additional context**
google-cloud-cpp depends on googleapis which is no longer available.

**Comment by JackBoosY** [comment]
Hi @heylaender, thanks for reporting this issue.
Sadly, I cannot repro it. So, please provide the log files(config and install), Visual Studio version, Windows SDK version.

Thanks.

**Comment by heylaender** [comment]
If I search for the dependence package it doesn't appear:

D:\vcpkg>.\vcpkg.exe search google
abseil               2019-05-08-1     an open-source collection designed to augment the C++ standard library. Abseil...
cartographer         1.0.0-1          Google 2D & 3D SLAM package
fruit                3.4.0-1          Fruit, a dependency injection framework for C++ by Google
glog                 0.4.0-2          C++ implementation of the Google logging module
google-cloud-cpp     0.14.0           C++ Client Libraries for Google Cloud Platform APIs.
gtest                2019-08-14-2     GoogleTest and GoogleMock testing frameworks.
leveldb              1.22-1           LevelDB is a fast key-value storage library written at Google that provides an...
protobuf             3.10.0           Protocol Buffers - Google's data interchange format
spdlog[benchmark]                     Use google benchmark
tesseract            4.1.0-2          An OCR Engine that was developed at HP Labs between 1985 and 1995... and now a...

If your library is not listed, please open an issue at and/or consider making a pull request:
    https://github.com/Microsoft/vcpkg/issues

D:\vcpkg>.\vcpkg.exe install google-cloud-cpp:x86-windows-static
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Error: Cannot find definition for package `googleapis`.

I'm using Visual Studio Enterprise 2017 Version 15.9.13. Logs at this stage are not created.

**Comment by heylaender** [comment]
I've installed the Package Manager from scratch and it seems to work now - thx for your investigation.

**Comment by JackBoosY** [comment]
@heylaender weird, `google-cloud-cpp` should automatically find `googleapis` built by vcpkg.
