### ISSUE TITLE
[PDAL] Plugins should be included

### ISSUE THREAD

**Issue by grandmaster789** [microsoft/vcpkg#8478]
****

**Is your feature request related to a problem? Please describe.**
Using the vcpkg PDAL package to read pointcloud data has worked great for me, until a client supplied one in e57 format. After doing some cursory investigation, reading/writing this format is included as a plugin for PDAL, but none of the plugins are included in the vcpkg build.

**Proposed solution**
Please include plugins in order to support more pointcloud file formats.

**Describe alternatives you've considered**
The alternative is to return to building directly from source and setting the appropriate cmake options. Because of the myriad of dependencies this is probably not going to be a straightforward process imho.

**Comment by cbezault** [comment]
Plugins should be added as features.
