### ISSUE TITLE
  Package: openssl-windows:x64-windows   Vcpkg version: 2019.09.12-nohash build failure

### ISSUE THREAD

**Issue by mwindowshz** [microsoft/vcpkg#8479]
**Host Environment**
- OS: Windows 10 64bit
- Compiler: vc142 (vs2019)

**To Reproduce**
`.vcpkg install openssl-windows:x64-windows`

**Failure logs** 
The following packages will be built and installed:
    openssl-windows[core]:x64-windows
Starting package 1/1: openssl-windows:x64-windows
Building package openssl-windows[core]:x64-windows...
-- Using cached E:/dev/vcpkg/downloads/openssl-1.0.2s.tar.gz
-- Using source at E:/dev/vcpkg/buildtrees/openssl-windows/src/openssl-1-c41872ef97
-- Downloading http://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win32/nasm-2.14.02-win32.zip...
-- Downloading http://download.qt.io/official_releases/jom/jom_1_1_3.zip...
-- Downloading http://download.qt.io/official_releases/jom/jom_1_1_3.zip... Failed. Status: 6;"Couldn't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:294 (vcpkg_download_distfile)
  ports/openssl-windows/portfile.cmake:41 (vcpkg_find_acquire_program)
  scripts/ports.cmake:94 (include)

Error: Building package openssl-windows:x64-windows failed with: BUILD_FAILED

Thank you👌

**Comment by JackBoosY** [comment]
Hi @mwindowshz, thanks for reporting this issue.
It seems that this is the problem that you can't access the jom download url. Can you manually download jom using this [link](http://download.qt.io/official_releases/jom/jom_1_1_3.zip)?
If you can't, please use another link to download jom 1.1.3 and put the zip package to directory _VCPKG_PATH/downloads_ and rebuild openssl-windows.

Thanks.

**Comment by JackBoosY** [comment]
Does this issue still bother you?

**Comment by JackBoosY** [comment]
If this issue is still not resolved, please reopen it.
