### ISSUE TITLE
gettext doesn't convert charsets

### ISSUE THREAD

**Issue by 375gnu** [microsoft/vcpkg#8484]
**Describe the bug**
I have an application which keeps translations in UTF-8, to display them in a user's native encoding I use `bind_textdomain_codeset(const char * domainname, const char * codeset )` but calls to `gettext()` return strings in UTF-8.

**Environment**
- OS: Windows
- Compiler: MSVC2015u3

**Expected behavior**
Strings returned by `gettext()` are converted to local encoding.

**Comment by vpaladino778** [comment]
Is this a vcpkg issue?

**Comment by JackBoosY** [comment]
Hi @375gnu, thanks for reporting this issue.
Can you provide a demo project to repro this issue?

Thanks.

**Comment by 375gnu** [comment]
Hi @JackBoosY, I pushed it to https://github.com/375gnu/vcpkg_bug/tree/master/gettext_8484. output.png shows the issue, correct output should have 8 letters only, actually there are 16.

**Comment by JackBoosY** [comment]
@375gnu I still cannot repro it. It's my result:
![image](https://user-images.githubusercontent.com/47264268/66459518-c0682700-eaa7-11e9-9672-06bbe55f0d21.png)

The only difference is that I use the msvc project instead of the cmake project.

**Comment by 375gnu** [comment]
@JackBoosY it looks like you don't have a translation. You need to translate test.po to your language and put it to `%YOUR_TWO_LETTER_LANGUAGE_CODE%/LC_MESSAGES/test.mo`

**Comment by JackBoosY** [comment]
@375gnu Sorry, I have not used this port experience.
Which label needs to be changed?

**Comment by 375gnu** [comment]
> Which label needs to be changed?

@JackBoosY didn't get. Are you asking how to create translation file or about something else?

**Comment by JackBoosY** [comment]
@375gnu How to translate "test.po" file? Should I use a tool to change the character set to utf-8 / unicode or something else? Which label should I change in this file? Can you give some templates?

Thanks.

**Comment by 375gnu** [comment]
@JackBoosY 

Step 1, edit test.po, this file should be in UTF-8 (and it already is):
1. Replace `be` with your language code in `"Language: be\n"` and `"Language-Team: be\n"`
1. Replace `праверка` with your language translation for `test` in `msgstr "праверка\n"`
1. You can also update `"Plural-Forms:"` field but we don't care for it now.

Step 2:
1. download `gettext` for windows from https://mlocati.github.io/articles/gettext-iconv-windows.html
1. create directory for your translation `%LANG%\LC_MESSAGES` where LANG has the same value as on step 1
1. convert test.po to binary form: `msgfmt -o %LANG%\LC_MESSAGES\test.mo test.po`

Step 3:
1. Replace CP1251 in test.cpp with your non Unicode encoding.
1. Compile and run the test application.

Alternative way:
Temporary set regional settings to be_BY (Belarusian, Belarus in the Control Panel) (Windows' interface should stay in English) and run the test application.

**Comment by 375gnu** [comment]
Or you can tell me your language and i will create a test file, according to your profile it should be Chinese.

**Comment by JackBoosY** [comment]
@375gnu My machine is en-US, but I hope you can make a Chinese files. : )

**Comment by 375gnu** [comment]
@JackBoosY I've pushed updated file. With locale set to zh_CN.UTF-8 it works file on my GNU/Linux.

**Comment by JackBoosY** [comment]
@375gnu Sadly, I still can't reproduce it on my zh-CN machine. This is my result (complete use of your provided file):

![image](https://user-images.githubusercontent.com/47264268/66891465-d469d680-f01b-11e9-9455-c66095d2be8d.png)

What did I miss?

**Comment by 375gnu** [comment]
@JackBoosY I forgot to push all changes, please try now. Btw, instead of changing locale settings you can try to define environment variable `LANGUAGE=zh`, this is a GNU gettext extension and should be supported on all platforms.

**Comment by JackBoosY** [comment]
@375gnu Thanks, confirmed.

**Comment by JackBoosY** [comment]
Then, I found that the actual character set of the output string is `UTF-8`, but it is printed as `ANSI`.
In the absence of knowledge of `gettext`, we need official support.

**Comment by 375gnu** [comment]
i'd say that the problem is not in gettext itself but in libiconv used by gettext

**Comment by JackBoosY** [comment]
@375gnu I think gettext doesn't really use iconv right now.
Because only `DEPENDS_ON_LIBICONV` is defined in CMakeLists.txt and `HAVE_ICONV` is not defined, but in the code:
```
#if DEPENDS_ON_LIBICONV && HAVE_ICONV
```

Rebuilt after adding -DHAVE_ICONV, an error occurred:
```
gettext-runtime\intl\dcigettext.c(1316): error C2065: 'ICONV_CONST': undeclared identifier
```
`ICONV_CONST` definition not found after looking up the header file of libiconv.

**Comment by 375gnu** [comment]
the problem is that libiconv on windows is built without ENABLE_RELOCATABLE, while gettext with.
I tried to build gettext without ENABLE_RELOCATABLE, and it seems that it works fine.
