### ISSUE TITLE
Error: Building package qt5:x86-windows failed with: BUILD_FAILED: VS 2017 on Windows 10

### ISSUE THREAD

**Issue by JunHo-Seo** [Microsoft/vcpkg#849]
I tried to install qt5 library with `.\vcpkg install qt5` command, but failed to with an message:
```
Error: Building package qt5:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qt5:x86-windows
  Vcpkg version: 0.0.77-3ff95e2a76719645633e2cac4d07b47ef790a3e2

Additionally, attach any relevant sections from the log files above.
'doskey' is not recognized as an internal or external command,
operable program or batch file.
'doskey' is not recognized as an internal or external command,
operable program or batch file.
'doskey' is not recognized as an internal or external command,
operable program or batch file.
'doskey' is not recognized as an internal or external command,
operable program or batch file.
```

I tried `.\vcpkg update` or `git pull` but it was already an up-to-date. Also, I can normally run `doskey` command in cmd or powershell. What's the problem?

**Comment by ras0219-msft** [comment]
I suspect the 'doskey' messages are from a strange interaction between your shell profile and our sanitized internal environment. We run all processes inside Vcpkg in a restricted environment (we cloak all your environment variables) in order to ensure robust builds as much as possible.

Unfortunately, the message `Error: Building package qt5:x86-windows failed with: BUILD_FAILED` doesn't contain the actual failure. Immediately above that, you likely got a message like:
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: D:/src/vcpkg/downloads/cmake-3.8.0-rc1-win32-x86/bin/cmake.exe;--build;.;--config;Release;--target;install;--;-v
    Working Directory: D:/src/vcpkg/buildtrees/uwebsockets/x86-windows-rel
    See logs for more information:
      D:\src\vcpkg\buildtrees\uwebsockets\package-x86-windows-rel-out.log
      D:\src\vcpkg\buildtrees\uwebsockets\package-x86-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_execute_required_process)
  ports/uwebsockets/portfile.cmake:19 (vcpkg_install_cmake)
  scripts/ports.cmake:73 (include)
```

Could you post that message and the last dozen lines of each of the log files listed, if any?

**Comment by JunHo-Seo** [comment]
Actually I got this error above:
```
-- CURRENT_INSTALLED_DIR=C:/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/vcpkg/packages/qt5_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/vcpkg/buildtrees/qt5
-- CURRENT_PORT_DIR=C:/vcpkg/ports/qt5/.
-- [download 0% complete]
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:103 (file):
  file DOWNLOAD HASH mismatch

    for file: [C:/vcpkg/downloads/jom_1_1_2.zip]
      expected hash: [830cd94ed6518fbe4604a0f5a3322671b4674b87d25a71349c745500d38e85c0fac4f6995242fc5521eb048e3966bb5ec2a96a06b041343ed8da9bba78124f34]
        actual hash: [cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e]
             status: [22;"HTTP response code said error"]

Call Stack (most recent call first):
  ports/qt5/portfile.cmake:9 (vcpkg_find_acquire_program)
  scripts/ports.cmake:73 (include)
```

It might be related with some network problem?

**Comment by ras0219-msft** [comment]
Yeah, it might be a network issue. Could you delete the downloaded file (C:/vcpkg/downloads/jom_1_1_2.zip) and try again?

**Comment by JunHo-Seo** [comment]
I think I found out what's the problem. When I tried to download jom manually from the link you given, the [server](http://ftp.jaist.ac.jp/pub/qtproject/official_releases/jom/jom_1_1_2.zip) showed an 500 internal server error. But when I tried to download it from the [UK mirror](http://ftp.mirrorservice.org/sites/download.qt-project.org/official_releases/jom/), it worked without any problem. I just assume that qt's server automatically select Japan server for me (as I'm living in Korea, it is quite reasonable), but the Japan server has an error. Well, in short, I can install qt5 now.

I still got doskey-related message after `Package qt5:x86-windows is installed`, but I think it's fine.

**Comment by JunHo-Seo** [comment]
Wait, I got this error when trying to build basic qt application on visual studio 2017, debug x86:
![image](https://cloud.githubusercontent.com/assets/17694801/24355939/e7d248e2-1332-11e7-8b4d-409d8b4b843b.png)
There's no error when building in release mode. Is this related with this issue?

Here's the code:
```
#include <QtWidgets/qapplication.h>
#include <QtWidgets/qmainwindow.h>

int main(int argc, char** argv)
{
	QApplication app{argc, argv};
	QMainWindow mainWindow;
	mainWindow.show();
	return app.exec();
}
```

**Comment by ras0219-msft** [comment]
Ok, so it appears that Qt application deployment is actually quite complicated [1]. I'm not a Qt expert, but I looked over the docs and the sources for windeployqt and found that (_basically_) each Qt Module maps to a plugins directory that has to be deployed with the application.

I've attempted to replicate this behavior in 558d54dd (qt5 package version 5.7.1-7). When you have Qt5 installed, we will automatically perform a similar deployment process as the windeployqt application for Qt apps. I was able to repro your issue and confirm that this solves it on my machine.

I do know how painful Qt is to rebuild, so if you want to try it out (just between us 😉), you can copy `ports\qt5\qtdeploy.ps1` to `installed\x86-windows\plugins\` and `installed\x86-windows\debug\plugins\`, then simply do a Rebuild of your app. Make sure to delete that file and do a full clean build of the new Qt5 package when you're done to make sure everything is totally correct.

[1] https://doc.qt.io/qt-5/windows-deployment.html

**Comment by ras0219-msft** [comment]
Let us know if this didn't work for you!
