### ISSUE TITLE
How do I install a library from a network shared folder?

### ISSUE THREAD

**Issue by bairog** [microsoft/vcpkg#8491]
Lets say I have a shared folder on local network server where I've placed some library sources (e. g. szip).
And I need to install that library via vcpkg.
I've tried to change portfile.cmake to the following
```
vcpkg_download_distfile(ARCHIVE
    URLS "\\\\127.0.0.1\\vcpkg_packages\\szip-2.1.1.tar.gz"
    FILENAME "szip-2.1.1.tar.gz"
    SHA512 ada6406efb096cd8a2daf8f9217fe9111a96dcae87e29d1c31f58ddd2ad2aa7bac03f23c7205dc9360f3b62d259461759330c7189ef0c2fe559704b1ea9d40dd
)
```
But I'm getting **Failed. Status : 6, "Couldn't resolve host name"** error
![Безымянный](https://user-images.githubusercontent.com/44995181/66371089-f70c4780-e9aa-11e9-84fd-b0f572b61db6.jpg)
So how to specify network shared folder correctly (I'm on Windows 10 x64 1903)?

**Comment by vicroms** [comment]
@bairog 

Try changing the URL to `file://127.0.0.1/vcpkg_packages/szip-2.1.1.tar.gz"

**Comment by Neumann-A** [comment]
you could also easily set the variable env variable `VCPKG_DOWNLOADS` to a folder containing all the downloaded libraries.

**Comment by bairog** [comment]
> nging the URL to `file://127.0.0.1/vcpkg_packages/szip-2.1.1.tar.gz`

Thx, it's working
