### ISSUE TITLE
x264 x86-windows / x264 x64-windows

### ISSUE THREAD

**Issue by Christsnatcher** [microsoft/vcpkg#8497]
Windows 8.1 x64
MSYS2 bash

vcpkg install x264:x86-windows / vcpkg install x264:x64-windows

Failure logs attached, as well as build error logs.

The build error logs clearly show that bash does not know the -j argument which is used for building and therefore terminates.
[cmd_x86.zip](https://github.com/microsoft/vcpkg/files/3701282/cmd_x86.zip)
[cmd_x64.zip](https://github.com/microsoft/vcpkg/files/3701283/cmd_x64.zip)
[build-x86-windows-dbg-err.zip](https://github.com/microsoft/vcpkg/files/3701285/build-x86-windows-dbg-err.zip)
[build-x64-windows-dbg-err.zip](https://github.com/microsoft/vcpkg/files/3701286/build-x64-windows-dbg-err.zip)
[ports.zip](https://github.com/microsoft/vcpkg/files/3701289/ports.zip)

**Comment by Voskrese** [comment]
https://github.com/microsoft/vcpkg/issues/8473

**Comment by JackBoosY** [comment]
Duplicate with #8473.
