### ISSUE TITLE
vcpkg should detect missing Windows SDK

### ISSUE THREAD

**Issue by lsalamon** [Microsoft/vcpkg#85]
When running ".\vcpkg install cpprestsdk" at command line I get this error:
-- CURRENT_INSTALLED_DIR=C:/Users/MYUSER/AppData/Roaming/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/Users/MYUSER/AppData/Roaming/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/MYUSER/AppData/Roaming/vcpkg/packages/cpprestsdk_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/Users/MYUSER/AppData/Roaming/vcpkg/buildtrees/cpprestsdk
-- CURRENT_PORT_DIR=C:/Users/MYUSER/AppData/Roaming/vcpkg/ports/cpprestsdk/.
-- Cloning done
-- Adding worktree and patching done
-- Configuring x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
  Command failed: C:/Program Files
  (x86)/CMake/bin/cmake.exe;C:/Users/MYUSER/AppData/Roaming/vcpkg/buildtrees/cpprestsdk/src/Release;-DBUILD_TESTS=OFF;-DBUILD_SAMPLES=OFF;-DCPPREST_EXCLUDE_WEBSOCKETS=ON;-G;Visual
  Studio 14
  2015;-DCMAKE_VERBOSE_MAKEFILE=ON;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_TOOLCHAIN_FILE=C:/Users/MYUSER/AppData/Roaming/vcpkg/triplets/x86-windows.cmake;-DCMAKE_PREFIX_PATH=C:/Users/MYUSER/AppData/Roaming/vcpkg/installed/x86-windows;-DCMAKE_INSTALL_PREFIX=C:/Users/MYUSER/AppData/Roaming/vcpkg/packages/cpprestsdk_x86-windows

  Working Directory:
  C:/Users/MYUSER/AppData/Roaming/vcpkg/buildtrees/cpprestsdk/x86-windows-rel

  See logs for more information:

```
  C:\Users\MYUSER\AppData\Roaming\vcpkg\buildtrees\cpprestsdk\config-x86-windows-rel-out.log
  C:\Users\MYUSER\AppData\Roaming\vcpkg\buildtrees\cpprestsdk\config-x86-windows-rel-err.log
```

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:27 (vcpkg_execute_required_process)
  ports/cpprestsdk/portfile.cmake:34 (vcpkg_configure_cmake)
  scripts/ports.cmake:96 (include)

Error: build command failed
#### LOGS contents for C:\Users\MYUSER\AppData\Roaming\vcpkg\buildtrees\cpprestsdk\config-x86-windows-rel-out.log:

-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Configuring incomplete, errors occurred!
See also "C:/Users/MYUSER/AppData/Roaming/vcpkg/buildtrees/cpprestsdk/x86-windows-rel/CMakeFiles/CMakeOutput.log".
See also "C:/Users/MYUSER/AppData/Roaming/vcpkg/buildtrees/cpprestsdk/x86-windows-rel/CMakeFiles/CMakeError.log".

My CMAKE version is : cmake-3.6.2-win32-x86

**Comment by ras0219-msft** [comment]
Hi lsalamon, thanks for reporting this issue.

- Do you have Visual Studio 2015 Update 3 installed?
- What are the contents of the environment variable "VS140COMNTOOLS"?
- Are you able to build trivial CMake projects externally to Vcpkg?

**Comment by lsalamon** [comment]
Hi R. Schumacher, this is the answers:
- Version 14.0.25421.03 Update 3
- VS140COMNTOOLS=H:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
- no errors on build Vcpkg

**Comment by ras0219-msft** [comment]
Can you build a cmake project normally from the command line without using vcpkg at all? Something like a simple "hello, world!" project.

**Comment by lsalamon** [comment]
No, no success in my "Hellow, world!" project. But this help me to correct environment. I try to build https://github.com/jameskbride/cmake-hello-world and this give me direction: "The Windows SDK version 10.0.10586.0 was not found." in CMakeError.log.
After that I install SDK and build successful.
-- CURRENT_INSTALLED_DIR=C:/Users/MYUSER/AppData/Roaming/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/Users/MYUSER/AppData/Roaming/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/MYUSER/AppData/Roaming/vcpkg/packages/cpprestsdk_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/Users/MYUSER/AppData/Roaming/vcpkg/buildtrees/cpprestsdk
-- CURRENT_PORT_DIR=C:/Users/MYUSER/AppData/Roaming/vcpkg/ports/cpprestsdk/.
-- Cloning done
-- Adding worktree and patching done
-- Configuring x86-windows-rel
-- Configuring x86-windows-rel done
-- Configuring x86-windows-dbg
-- Configuring x86-windows-dbg done
-- Build x86-windows-rel
-- Build x86-windows-rel done
-- Build x86-windows-dbg
-- Build x86-windows-dbg done
-- Package x86-windows-rel
-- Package x86-windows-rel done
-- Package x86-windows-dbg
-- Package x86-windows-dbg done
-- Warning: Could not find a matching pdb file for:
    C:/Users/MYUSER/AppData/Roaming/vcpkg/packages/cpprestsdk_x86-windows/bin/cpprest_2_8.dll

-- Performing post-build validation
-- Performing post-build validation done
Package cpprestsdk:x86-windows is installed

Tanks
