### ISSUE TITLE
FindPackage SFML fails

### ISSUE THREAD

**Issue by giellamoswhard** [microsoft/vcpkg#8503]
**Describe the bug**
After I've install SFML

`find_package(SFML CONFIG REQUIRED) `

fails with

> find_package(SFML) called with no component

**Environment**
- OS: Ubuntu 19.04
- Compiler: revision GCC 8.3

**To Reproduce**
1. ./vcpkg install sfml
2. See error
Repro code when

**Expected behavior**

**Failure logs** 
-(please attached failure logs)

**Additional context**

**Comment by JackBoosY** [comment]
According to [this document](https://en.sfml-dev.org/forums/index.php?topic=23676.0), I think we need to add `components` to `find_package`.
We should add a usage.

**Comment by JackBoosY** [comment]
Hi @giellamoswhard, thanks for reporting this issue.
I've added usage with sfml. Please update vcpkg and follow the usage.

Thanks.

**Comment by atimholt** [comment]
I know this is closed, but I ran into the same problem today (2020-11-28) after `git pull`-ing, `vcpkg\bootstrap.bat\`-ing, and `vcpkg upgrade`-ing. Usually, to find usage information, I run `vcpkg install [port]` again and read its output, which did not return the new usage information.

If there is some way to access package usage information from the command line—besides navigating to `VCPKG_ROOT` and `Get-Content`/`cat`-ing the usage file—this is not indicated anywhere in the CLI usage information output (i.e. the output of the commands `vcpkg [nothing/anything that doesn't form an expected command line invoke]`, and `vcpkg help [topic]`). Is manual exploration of `VCPKG_ROOT` the intended method of learning about package metadata? It's a bit onerous.

**Comment by JackBoosY** [comment]
@atimholt Please open a new issue to report that, thanks!
