### ISSUE TITLE
c7542de3f31defef6344e9acb05adf7d39f6d4a8 breaks qt6 cmake build for android

### ISSUE THREAD

**Issue by liangqi** [microsoft/vcpkg#8506]
**Describe the bug**
CMAKE_TRY_COMPILE_PLATFORM_VARIABLES in cmake overwrites the one in android ndk

**Environment**
- OS: [RHEL 7.6]
- Compiler: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
- Android NDK r20

**To Reproduce**
We have some work before for building qt6 for android with cmake, without any issue, the fork is at https://github.com/tronical/vcpkg qt branch. Then I tried a merge from master about two weeks ago at https://github.com/liangqi/vcpkg qt-snapshot-2019-09-25 branch.

We tried to add following line in our CMakeLists.txt file:

message(">>>>>>> ${CMAKE_TRY_COMPILE_PLATFORM_VARIABLES}")

It was following before,

>>>>>>> ANDROID_TOOLCHAIN;ANDROID_ABI;ANDROID_PLATFORM;ANDROID_STL;ANDROID_PIE;ANDROID_CPP_FEATURES;ANDROID_ALLOW_UNDEFINED_SYMBOLS;ANDROID_ARM_MODE;ANDROID_ARM_NEON;ANDROID_DISABLE_FORMAT_STRING_CHECKS;ANDROID_CCACHE

And it is:

>>>>>>> VCPKG_TARGET_TRIPLET;VCPKG_APPLOCAL_DEPS;VCPKG_CHAINLOAD_TOOLCHAIN_FILE;_VCPKG_ROOT_DIR

We have arm-android/arm64-android/x64-android/x86-android four configurations, all un-default values than arm-android(armv7) will fail to detect EGL and related.

We tried --trace and found two places touched CMAKE_TRY_COMPILE_PLATFORM_VARIABLES,

/opt/android/android-ndk-r20/build/cmake/android.toolchain.cmake(262):  set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES ANDROID_TOOLCHAIN ANDROID_ABI ANDROID_PLATFORM ANDROID_STL ANDROID_PIE ANDROID_CPP_FEATURES ANDROID_ALLOW_UNDEFINED_SYMBOLS ANDROID_ARM_MODE ANDROID_ARM_NEON ANDROID_DISABLE_FORMAT_STRING_CHECKS ANDROID_CCACHE )
/home/qt/vcpkg/scripts/buildsystems/vcpkg.cmake(286):  set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES VCPKG_TARGET_TRIPLET VCPKG_APPLOCAL_DEPS VCPKG_CHAINLOAD_TOOLCHAIN_FILE _VCPKG_ROOT_DIR )

Revert c7542de3f31defef6344e9acb05adf7d39f6d4a8 helped us to get a build like before.

**Comment by Neumann-A** [comment]
So 
`set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES VCPKG_TARGET_TRIPLET VCPKG_APPLOCAL_DEPS VCPKG_CHAINLOAD_TOOLCHAIN_FILE _VCPKG_ROOT_DIR )`
should simply be 
`set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES VCPKG_TARGET_TRIPLET VCPKG_APPLOCAL_DEPS VCPKG_CHAINLOAD_TOOLCHAIN_FILE _VCPKG_ROOT_DIR ${CMAKE_TRY_COMPILE_PLATFORM_VARIABLES })`
or 
`list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES VCPKG_TARGET_TRIPLET VCPKG_APPLOCAL_DEPS VCPKG_CHAINLOAD_TOOLCHAIN_FILE _VCPKG_ROOT_DIR)`

could you try out this change to vcpkg.cmake?

**Comment by liangqi** [comment]
@Neumann-A thanks.

Both works here, at least at cmake step and build.

Perhaps the 2nd one is better? ^_^
