### ISSUE TITLE
[googleapis] build failure

### ISSUE THREAD

**Issue by heylaender** [microsoft/vcpkg#8510]
**Host Environment**
- OS: Windows 10
- Compiler: Microsoft Visual Studio Enterprise 2017 Version 15.9.13

**To Reproduce**
.\vcpkg.exe install googleapis:x86-windows-static

with triplets

set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

**Failure logs** 
D:\vcpkg>.\vcpkg.exe install googleapis:x86-windows-static
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be built and installed:
    googleapis[core]:x86-windows-static
Starting package 1/1: googleapis:x86-windows-static
Building package googleapis[core]:x86-windows-static...
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
Please install the English language pack.
-- Using cached D:/vcpkg/downloads/googleapis-cpp-cmakefiles-v0.1.5.tar.gz
-- Using source at D:/vcpkg/buildtrees/googleapis/src/v0.1.5-d3c44adbd6
-- Configuring x86-windows-static
-- Building x86-windows-static-dbg
-- Building x86-windows-static-rel
-- Installing: D:/vcpkg/packages/googleapis_x86-windows-static/share/googleapis/copyright
-- Performing post-build validation
Expected Debug,Dynamic crt linkage, but the following libs had invalid crt linkage:

    D:/vcpkg/packages/googleapis_x86-windows-static/debug/lib/googleapis_cpp_api_annotations_protos.lib: Debug,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/debug/lib/googleapis_cpp_api_auth_protos.lib: Debug,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/debug/lib/googleapis_cpp_api_client_protos.lib: Debug,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/debug/lib/googleapis_cpp_api_http_protos.lib: Debug,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/debug/lib/googleapis_cpp_api_resource_protos.lib: Debug,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/debug/lib/googleapis_cpp_bigtable_protos.lib: Debug,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/debug/lib/googleapis_cpp_devtools_cloudtrace_v2_trace_protos.lib: Debug,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/debug/lib/googleapis_cpp_devtools_cloudtrace_v2_tracing_protos.lib: Debug,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/debug/lib/googleapis_cpp_iam_v1_iam_policy_protos.lib: Debug,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/debug/lib/googleapis_cpp_iam_v1_options_protos.lib: Debug,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/debug/lib/googleapis_cpp_iam_v1_policy_protos.lib: Debug,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/debug/lib/googleapis_cpp_longrunning_operations_protos.lib: Debug,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/debug/lib/googleapis_cpp_rpc_error_details_protos.lib: Debug,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/debug/lib/googleapis_cpp_rpc_status_protos.lib: Debug,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/debug/lib/googleapis_cpp_spanner_protos.lib: Debug,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/debug/lib/googleapis_cpp_type_expr_protos.lib: Debug,Static

To inspect the lib files, use:
    dumpbin.exe /directives mylibfile.lib
Expected Release,Dynamic crt linkage, but the following libs had invalid crt linkage:

    D:/vcpkg/packages/googleapis_x86-windows-static/lib/googleapis_cpp_api_annotations_protos.lib: Release,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/lib/googleapis_cpp_api_auth_protos.lib: Release,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/lib/googleapis_cpp_api_client_protos.lib: Release,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/lib/googleapis_cpp_api_http_protos.lib: Release,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/lib/googleapis_cpp_api_resource_protos.lib: Release,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/lib/googleapis_cpp_bigtable_protos.lib: Release,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/lib/googleapis_cpp_devtools_cloudtrace_v2_trace_protos.lib: Release,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/lib/googleapis_cpp_devtools_cloudtrace_v2_tracing_protos.lib: Release,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/lib/googleapis_cpp_iam_v1_iam_policy_protos.lib: Release,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/lib/googleapis_cpp_iam_v1_options_protos.lib: Release,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/lib/googleapis_cpp_iam_v1_policy_protos.lib: Release,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/lib/googleapis_cpp_longrunning_operations_protos.lib: Release,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/lib/googleapis_cpp_rpc_error_details_protos.lib: Release,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/lib/googleapis_cpp_rpc_status_protos.lib: Release,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/lib/googleapis_cpp_spanner_protos.lib: Release,Static
    D:/vcpkg/packages/googleapis_x86-windows-static/lib/googleapis_cpp_type_expr_protos.lib: Release,Static

To inspect the lib files, use:
    dumpbin.exe /directives mylibfile.lib
Found 2 error(s). Please correct the portfile:
    D:\vcpkg\ports\googleapis\portfile.cmake
-- Performing post-build validation done
Error: Building package googleapis:x86-windows-static failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: googleapis:x86-windows-static
  Vcpkg version: 2019.09.12-nohash
[install-x86-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/3703277/install-x86-windows-static-dbg-out.log)
[install-x86-windows-static-rel-out.log](https://github.com/microsoft/vcpkg/files/3703278/install-x86-windows-static-rel-out.log)

Tried to build the whole chain for port google-cloud-cpp with triplets

set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

doesn't work.

**Comment by LilyWangL** [comment]
Hi @heylaender, you need to add a new triplet file and modify VCPKG_CRT_LINKAGE to dynamic.

Thanks.

**Comment by heylaender** [comment]
Where must I add which file (filename)? 

If I look into  the BUILD_INFO (D:\vcpkg\packages\googleapis_x86-windows-static) it has the right info:

CRTLinkage: dynamic
LibraryLinkage: static

But the linkage is static.

**Comment by JackBoosY** [comment]
@heylaender You can create a new triplet file(such as `x86-windows-static-crt-dynamic.cmake`) in _VCPKG_PATH/triplets/_, and add these code in it:
```
set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
```
Then use command `.\vcpkg install googleapis:x86-windows-static-crt-dynamic` to install `googleapis`.

**Comment by heylaender** [comment]
It is working with this setting - thx
