### ISSUE TITLE
[jxrlib] To support community using 4creators/jxrlib repo as a source for the jxrlib port a release and tag has been created

### ISSUE THREAD

**Issue by 4creators** [microsoft/vcpkg#8511]
`vcpkg` community has decided to use [4creators/jxrlib](https://github.com/4creators/jxrlib) repo as a source for building the library.  Due to this and demands form a community for creating at least source release of the `jxrlib` with a tag in the repo a new release has been created.

Please use [v2019.10.09](https://github.com/4creators/jxrlib/releases/tag/v2019.10.9) tag and released source code packages in [zip](https://github.com/4creators/jxrlib/archive/v2019.10.9.zip) and [tar.gz](https://github.com/4creators/jxrlib/archive/v2019.10.9.tar.gz) formats as a common base for port and binary builds in the future.

**Comment by Voskrese** [comment]
Tell me, what's the difference?

![2019-10-09_054256](https://user-images.githubusercontent.com/10104740/66435888-655b1380-ea58-11e9-99e3-f19d886e72a7.png)

![2019-10-09_054424](https://user-images.githubusercontent.com/10104740/66435903-6c822180-ea58-11e9-98f3-e20f9e436504.png)

**Comment by 4creators** [comment]
Do you need to see a difference between last commit and last tag and release?

**Comment by cenit** [comment]
Nope but the tag is pointing to the same commit and since commit is even more stable than a tag, it’s better to use that.
But this opens another question: why are not we using ufficial download link?

**Comment by PhoebeHui** [comment]
In this case, we usually use commit(f752187986) of latest release to download source since it's more stable, and we will write the release version 'v2019.10.9' in CONTROL file.  I will update this port.

**Comment by PhoebeHui** [comment]
The fix has been merged, thanks for posting this issue.
