### ISSUE TITLE
[New Port Request] libosrm (open source routing machine)

### ISSUE THREAD

**Issue by riccardopenco** [microsoft/vcpkg#8516]
Library name: libosrm

Library description: open source library for routing using OpenStreetMap data

Source repository URL: https://github.com/Project-OSRM/osrm-backend

Project homepage (if different from the source repository): http://project-osrm.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by tomnsh** [comment]
At present, many people use Open Source Routing Machine. Would you consider re-opening this issue
