### ISSUE TITLE
compile both VS2015 and VS2017

### ISSUE THREAD

**Issue by wjx0912** [microsoft/vcpkg#8517]
i have install both VS2015 and VS2017, but after i do :

**vcpkg.exe install jsoncpp**

it only compile vs2017, how to compile vs2015 also?

**Comment by cenit** [comment]
Vs2017 (and 2019) are abi compatible with 2015, so it should be not necessary. Am I missing something?

**Comment by JackBoosY** [comment]
Hi @wjx0912, you can use Visual Studio 2015 using this set:
```
set(VCPKG_PLATFORM_TOOLSET v140)
```
Just add it into your triplet file in _VCPKG_PATH/triplets/_.

Thanks.

**Comment by wjx0912** [comment]
hi, @cenit 
thanks for your reply, i'll test the compatible  of 15/17/19.
