### ISSUE TITLE
problem when running "./vcpkg install opengl:x64-windows"

### ISSUE THREAD

**Issue by pbvelikov** [microsoft/vcpkg#8519]
There was an issue running "./vcpkg install tesseract:x64-windows"
This should be included in my report:
        Package: opengl:x64-windows
        Vcpkg version: 2019.09.12-nohash

and this is the complete output of my "./vcpkg install tesseract:x64-windows" command:
The following packages will be built and installed:
  * giflib[core]:x64-windows
  * leptonica[core]:x64-windows
  * libjpeg-turbo[core]:x64-windows
  * liblzma[core]:x64-windows
  * libpng[core]:x64-windows
  * libwebp[core]:x64-windows
  * opengl[core]:x64-windows
    tesseract[core]:x64-windows
  * tiff[core]:x64-windows
  * zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/10: zlib:x64-windows
Building package zlib[core]:x64-windows...
A suitable version of git was not found (required v2.21.0). Downloading portable git v2.21.0...
Extracting git...
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz...
-- Extracting source D:/INSTALL/Development/vcpkg-master/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Using source at D:/INSTALL/Development/vcpkg-master/buildtrees/zlib/src/1.2.11-f690224aeb
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/INSTALL/Development/vcpkg-master/packages/zlib_x64-windows/share/zlib/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package zlib[core]:x64-windows... done
Installing package zlib[core]:x64-windows...
Installing package zlib[core]:x64-windows... done
Elapsed time for package zlib:x64-windows: 33.44 s
Starting package 2/10: libpng:x64-windows
Building package libpng[core]:x64-windows...
-- Downloading https://github.com/glennrp/libpng/archive/v1.6.37.tar.gz...
-- Extracting source D:/INSTALL/Development/vcpkg-master/downloads/glennrp-libpng-v1.6.37.tar.gz
-- Applying patch use-abort-on-all-platforms.patch
-- Applying patch fix-libm-unix.patch
-- Using source at D:/INSTALL/Development/vcpkg-master/buildtrees/libpng/src/v1.6.37-6445e5863e
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package libpng[core]:x64-windows... done
Installing package libpng[core]:x64-windows...
Installing package libpng[core]:x64-windows... done
Elapsed time for package libpng:x64-windows: 17.66 s
Starting package 3/10: libjpeg-turbo:x64-windows
Building package libjpeg-turbo[core]:x64-windows...
-- Downloading https://github.com/libjpeg-turbo/libjpeg-turbo/archive/2.0.2.tar.gz...
-- Extracting source D:/INSTALL/Development/vcpkg-master/downloads/libjpeg-turbo-libjpeg-turbo-2.0.2.tar.gz
-- Applying patch add-options-for-exes-docs-headers.patch
-- Applying patch workaround_cmake_system_processor.patch
-- Using source at D:/INSTALL/Development/vcpkg-master/buildtrees/libjpeg-turbo/src/2.0.2-3c759cce19
-- Downloading http://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win32/nasm-2.14.02-win32.zip...
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package libjpeg-turbo[core]:x64-windows... done
Installing package libjpeg-turbo[core]:x64-windows...
Installing package libjpeg-turbo[core]:x64-windows... done
Elapsed time for package libjpeg-turbo:x64-windows: 32.06 s
Starting package 4/10: liblzma:x64-windows
Building package liblzma[core]:x64-windows...
-- Downloading https://github.com/xz-mirror/xz/archive/v5.2.4.tar.gz...
-- Extracting source D:/INSTALL/Development/vcpkg-master/downloads/xz-mirror-xz-v5.2.4.tar.gz
-- Applying patch enable-uwp-builds.patch
-- Using source at D:/INSTALL/Development/vcpkg-master/buildtrees/liblzma/src/v5.2.4-66bfe33102
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/INSTALL/Development/vcpkg-master/packages/liblzma_x64-windows/share/liblzma/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package liblzma[core]:x64-windows... done
Installing package liblzma[core]:x64-windows...
Installing package liblzma[core]:x64-windows... done
Elapsed time for package liblzma:x64-windows: 22.08 s
Starting package 5/10: tiff:x64-windows
Building package tiff[core]:x64-windows...
-- Downloading http://download.osgeo.org/libtiff/tiff-4.0.10.tar.gz...
-- Extracting source D:/INSTALL/Development/vcpkg-master/downloads/tiff-4.0.10.tar.gz
-- Applying patch fix-stddef.patch
-- Applying patch cmakelists.patch
-- Using source at D:/INSTALL/Development/vcpkg-master/buildtrees/tiff/src/4.0.10-229dd2f530
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/INSTALL/Development/vcpkg-master/packages/tiff_x64-windows/share/tiff/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package tiff[core]:x64-windows... done
Installing package tiff[core]:x64-windows...
Installing package tiff[core]:x64-windows... done
Elapsed time for package tiff:x64-windows: 1.006 min
Starting package 6/10: giflib:x64-windows
Building package giflib[core]:x64-windows...
-- Note: giflib only supports static library linkage. Building static library.
-- Downloading https://nchc.dl.sourceforge.net/project/giflib/giflib-5.1.4.tar.bz2...
-- Extracting source D:/INSTALL/Development/vcpkg-master/downloads/giflib-5.1.4.tar.bz2
-- Applying patch msvc-guard-unistd-h.patch
-- Applying patch fix-compile-error.patch
-- Using source at D:/INSTALL/Development/vcpkg-master/buildtrees/giflib/src/5.1.4-8e625bd21e
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/INSTALL/Development/vcpkg-master/packages/giflib_x64-windows/share/giflib/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package giflib[core]:x64-windows... done
Installing package giflib[core]:x64-windows...
Installing package giflib[core]:x64-windows... done
Elapsed time for package giflib:x64-windows: 13.13 s
Starting package 7/10: opengl:x64-windows
Building package opengl[core]:x64-windows...
CMake Error at ports/opengl/portfile.cmake:20 (message):
  Cannot find Windows 10.0.17763.0 SDK.  File does not exist: C:\Program
  Files (x86)\Windows Kits\10\Lib\10.0.17763.0\um\x64\OpenGL32.Lib
Call Stack (most recent call first):
  scripts/ports.cmake:94 (include)

Error: Building package opengl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opengl:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by JackBoosY** [comment]
Hi @pbvelikov, the error info shows:
```
Cannot find Windows 10.0.17763.0 SDK. File does not exist: C:\Program
Files (x86)\Windows Kits\10\Lib\10.0.17763.0\um\x64\OpenGL32.Lib
```
Please install Windows 10 SDK using Visual Studio Installer first.

Thanks.

**Comment by pbvelikov** [comment]
Hi,
I have this SDK installed a long time ago, but on disk D:, so the file in question is available and located here: D:\Windows Kits\10\Lib\10.0.17763.0\um\x64\OpenGL32.Lib

Why is ./vcpkg looking for it on C:?

**Comment by PhoebeHui** [comment]
Duplicated to  https://github.com/microsoft/vcpkg/issues/8288.
