### ISSUE TITLE
[pmdk] update to 1.7

### ISSUE THREAD

**Issue by igchor** [microsoft/vcpkg#8526]
Library name: PMDK

New version number: 1.7

Other information that may be useful:
https://github.com/pmem/pmdk/releases/tag/1.7

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.

**Comment by igchor** [comment]
I noticed that you have taken commit from master instead of 1.7. I would like to have version to be equal exactly to 1.7 instead of d2f6f5b0032eb5678ec6c5c3dff03509caa4b817. I think the version in CONTROL should also be specified as 1.7 and not 2019-10-10.

Thanks
