### ISSUE TITLE
[ffmpeg] build failure: configure script is not executable

### ISSUE THREAD

**Issue by marcbertola** [microsoft/vcpkg#8528]
While compiling ffmpeg for x64-linux, the `configure` file (part of ffmpeg source) called by `build_linux.sh` is not executable, and the build fails.

See workaround indicated under "Additional Context" - I explicitly enable the executable permission of the `configure` file before it is invoked from `build_linux.sh`

**Host Environment**
- OS: Linux x64 Ubuntu 18.04
- Compiler: gcc

**To Reproduce**
Add Triplet: x64-linux-dynamic.cmake

```cmake
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
```
Install:
```bash
./vcpkg install ffmpeg:x64-linux-dynamic
```

**Failure logs** 

Replaced local path with XXXXX for privacy:

```
Command failed: /bin/bash --noprofile --norc XXXXX/vcpkg/ports/ffmpeg/build_linux.sh XXXXX/vcpkg/buildtrees/ffmpeg/x64-linux-dynamic-rel XXXXX/vcpkg/buildtrees/ffmpeg/src/n4.2-02d8c63f80 XXXXX/vcpkg/packages/ffmpeg_x64-linux-dynamic "--enable-asm --enable-yasm --disable-doc --enable-debug --enable-runtime-cpudetect --disable-openssl --disable-ffmpeg --disable-ffplay --disable-ffprobe --disable-libvpx --disable-libx264 --disable-opencl --disable-lzma --disable-bzlib --enable-avresample --enable-cuda --enable-nvenc --enable-cuvid --disable-libnpp  --disable-static --enable-shared "
    Working Directory: XXXXX/vcpkg/buildtrees/ffmpeg/x64-linux-dynamic-rel
    Error code: 126
    See logs for more information:
      XXXXX/vcpkg/buildtrees/ffmpeg/build-x64-linux-dynamic-rel-out.log
      XXXXX/vcpkg/buildtrees/ffmpeg/build-x64-linux-dynamic-rel-err.log
```

Contents of `XXXXX/vcpkg/buildtrees/ffmpeg/build-x64-linux-dynamic-rel-err.log`

```
/home/mbertola/code/clean/vcpkg-suosdk/ports/ffmpeg/build_linux.sh: line 20: /home/mbertola/code/clean/vcpkg-suosdk/buildtrees/ffmpeg/src/n4.2-02d8c63f80/configure: Permission denied
```

**Additional context**
Adding `chmod a+x "$PATH_TO_SRC_DIR/configure"` to `build_linux.sh` works.

```bash
echo "=== CONFIGURING ==="
chmod a+x "$PATH_TO_SRC_DIR/configure"
"$PATH_TO_SRC_DIR/configure" "--prefix=$PATH_TO_PACKAGE_DIR" $4
```

**Comment by marcbertola** [comment]
I added the `chmod` as part of pull request 9165. Feel free to comment and/or propose better ways to move forward.
https://github.com/microsoft/vcpkg/pull/9165

**Comment by JackBoosY** [comment]
Does this issue still exist?

**Comment by LilyWangLL** [comment]
Thanks for posting this issue, please reopen this issue if it still be a problem for you.
