### ISSUE TITLE
[ffmpeg] add support in portfile for NVIDIA hardware acceleration

### ISSUE THREAD

**Issue by marcbertola** [microsoft/vcpkg#8530]
Hello, 

FFmpeg has support for NVIDIA hardware decode and encode acceleration for H.264 and H.265 (HEVC). However, the existing portfile does not expose this functionality via the features described in the CONTROL file. 

I have successfully managed to make a few small modifications to the existing `CONTROL` and `portfile.cmake` to accomplish this, and have already compiled successfully for x64-windows, x64-linux and cross-compiled from x64-linux to aarch64-linux (NVIDIA Jetson Xavier board). What is the correct procedure to perform a code review of the changes and pull request?

Also worth noting: ffmpeg's scripts depend on the presence of the header-only `FFmpeg/nv-codec-headers` repo. To implement my fix, I needed to add a new port for this, and create a dependency on it in the `CONTROL` file.
https://github.com/FFmpeg/nv-codec-headers

**Comment by cenit** [comment]
Just open a Pull request containing all your fixes, you will be guided in case any modification  is necessary

**Comment by marcbertola** [comment]
Ok, I need to get some other dependencies compiled before I can try this, but if testing goes well, I'll kick off the process.

**Comment by zhuohekeji** [comment]
> Ok, I need to get some other dependencies compiled before I can try this, but if testing goes well, I'll kick off the process.

Hi, marcbertola. Does the ffmpeg in vcpkg support `ffnvcodec` now? I didn't find any change in `portfile.cmake` and `CONTROL`.  How can I compile ffmpeg with NVIDIA hardware acceleration? Thanks!

**Comment by marcbertola** [comment]
Sorry - haven't gotten around to publishing it, but it works. I'll get a PR together asap and let you know as soon as it's ready.

**Comment by marcbertola** [comment]
Pull request has been submitted.
https://github.com/microsoft/vcpkg/pull/9165

**Comment by NancyLi1013** [comment]
Hi @marcbertola 

Thanks for your great effors and patience.
Since the PR has been merged,I close this issue now.
