### ISSUE TITLE
[embree3] find_package returns invalid include & library path

### ISSUE THREAD

**Issue by mathijs727** [microsoft/vcpkg#8531]
After installing embree3 through vcpkg, `find_package(embree 3 REQUIRED)` returns an invalid include & library path.

Vcpkg moves the file `embree-config.cmake` from the build root to `installed/x64-windows/share/embree3/`.
On the first line `EMBREE_ROOT_DIR` is defined as `${CMAKE_CURRENT_LIST_DIR}/.`.
Obviously Embree is not located in the share folder itself but two folders up (`installed/x64-windows/`) which results in incorrect paths being returned for both the include path & library files.

**Environment**
- OS: Windows 10
- Compiler: 19.23.28106.4 for x64

**To Reproduce**
1. ./vcpkg install embree3
2. find_package(embree 3 REQUIRED)
3. target_include_libraries(mytarget PUBLIC ${EMBREE_INCLUDE_DIRS})

**Comment by AlvinZhangH** [comment]
Hi @mathijs727 thanks for posting this issue. This issue has been fixed. Please try to update vcpkg and use it.

**Comment by xarthurx** [comment]
@AlvinZhangH 

After install the library, there is no cmake integration suggestion like other packages, such as:
```
find_package(lib CONFIG REQUIRED)
target_link_libraries(main PRIVATE xxx:xxx)
```
popped up.

Actually I reach this post when I use `find_package(embree CONFIG REQUIRED)` and got an error of versions.

Would it be possible to add such a suggestion to the install script?
