### ISSUE TITLE
bootstrap build failure

### ISSUE THREAD

**Issue by edidada** [microsoft/vcpkg#8537]
**Host Environment**
- OS: Windows 10
- Compiler:   Package: boost-build:x64-windows
  Vcpkg version: 2019.09.12-nohash

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: D:/vcpkg/packages/boost-build_x64-windows/tools/boost-build/bootstrap.bat msvc
    Working Directory: D:/vcpkg/packages/boost-build_x64-windows/tools/boost-build
    Error code: 2
    See logs for more information:
      D:\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-out.log
      D:\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-err.log

**Comment by LilyWangL** [comment]
Hi @edidada, I can't reproduce it locally. Can you provide your build log?
```
D:\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-out.log
D:\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-err.log
```
Thanks.

**Comment by timautry** [comment]
Ports boost-build & boost-modular-build-helper, last time I checked (yesterday), both have incorrect versions numbers 1.70.0 versus the version they're supposed to be building, 1.71.0 (these two seem to always be missed when the boost libraries are upgraded. Here is the findings of my research:
1. boost-build: CONTROL and portfile.cmake needs version changed to 1.71, the SHA512 needs to be updated for the new version and I believe the arm64msvc.patch is no longer needed as the new boostcpp.jam file seems to already have all the added arm64 entries.
2. boost-modular-build-helper: boost-modular-build.cmake, CONTROL, and Jamroot.jam, all need the version updated from 1.70 to 1.71.
3. The 3rd item I've discovered is all the boost libraries are being built with the first msvc toolset found, and this is by the boost design. Boost (b2/bjam) allows for the toolset= option or it can be specified in a port-config.jam, site-config.jam or the user-config.jam, so one could specify the desired toolset boost uses to build all the libraries, in my case I would like it to default to the v141 toolset for VS2017 and v142 for VS2019.
Note: I have VS2017 and VS2019 installed with all available toolsets for each and I have 2 versions of vcpkg installed completely built by each versions primary toolset, compilers and linkers, all x64-windows, in addition to building vcpkg with the -win64 option.
So I guess what I'm asking is where would one make the add/change in the group of portfiles to make boost build using the default toolset, compiler and linker for the version of visual studio you are using?

**Comment by gtumanyan** [comment]
- [ ] Change version to 1.71.0 in portfile.cmake and CONTROL
- [ ] Replace first SHA512 in portfile.cmake with this new one ce1c070bea936d054791db3a5205dfcfa53f8a798e3c798a555fd580798a375b1e0c831dbf6803a1866fa67fdb040d35e412eac618bb5073271e209f1600b8a7
- [ ] Remove arm64msvc.patch from portfile.cmake

**You are ready to go!**

**Comment by PhoebeHui** [comment]
Related to https://github.com/microsoft/vcpkg/pull/9093

**Comment by PhoebeHui** [comment]
@edidada, currently boost has been upgrade t0 1.74.0, please get latest source and try again, and report an new issue with failrure logs if the issue persist.
