### ISSUE TITLE
zlib:x86 build failure

### ISSUE THREAD

**Issue by edidada** [microsoft/vcpkg#8538]
**Host Environment**
- OS: [e.g. Windows
dditional packages (*) will be modified to complete this operation.
Starting package 1/111: zlib:x86-windows
Building package zlib[core]:x86-windows...
-- Using cached D:/vcpkg/downloads/zlib1211.tar.gz
-- Using source at D:/vcpkg/buildtrees/zlib/src/1.2.11-f690224aeb
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: D:/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: D:/vcpkg/buildtrees/zlib/x86-windows-dbg
    See logs for more information:
      D:\vcpkg\buildtrees\zlib\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/zlib/portfile.cmake:32 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package zlib:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x86-windows
  Vcpkg version: 2019.09.12-nohash

**Comment by LilyWangL** [comment]
Hi @edidada, can you provide your build log?
```
See logs for more information:
D:\vcpkg\buildtrees\zlib\install-x86-windows-dbg-out.log
```

**Comment by PhoebeHui** [comment]
@edidada, we can't repro this issue, please reopen this issue and attach the failure logs if it still be an problem for you.
