### ISSUE TITLE
[vtk] Move atlmfc (windows) from Build-Depends to Feature

### ISSUE THREAD

**Issue by bhwqy** [microsoft/vcpkg#8539]
**Environment**
OS: Windows 10
Visual Studio Version: 16.3.3
Vcpkg version: 2019.09.12-nohash

**Problem Description**
Currently, Visual Studio does not supports MFC by default. Consider move atlmfc (windows) from Build-Depends to Feature.

**Proposed solution**
Small changes in CONTROL and portfile.cmake as the following. Tested on the environment described above.

In CONTROL

5c5,9
\< Build-Depends: zlib, libpng, tiff, libxml2, jsoncpp, glew, freetype, expat, hdf5, libjpeg-turbo, proj4, lz4, libtheora, atlmfc (windows), eigen3, double-conversion, pugixml, libharu, sqlite3, netcdf-c
\---
\> Build-Depends: zlib, libpng, tiff, libxml2, jsoncpp, glew, freetype, expat, hdf5, libjpeg-turbo, proj4, lz4, libtheora, eigen3, double-conversion, pugixml, libharu, sqlite3, netcdf-c
\>
\> Feature: atlmfc
\> Description: mfc functionality for vtk on Windows
\> Build-Depends: atlmfc

In portfile.cmake

35a36,42
\> if ("atlmfc" IN_LIST FEATURES)
\>       set(Module_vtkGUISupportMFC ON)
\> else()
\>       set(Module_vtkGUISupportMFC OFF)
\> endif()
\>
\>
100,104c107,111
\< if(NOT VCPKG_CMAKE_SYSTEM_NAME)
\<     set(Module_vtkGUISupportMFC ON)
\< else()
\<     set(Module_vtkGUISupportMFC OFF)
\< endif()
\---
\> \# if(NOT VCPKG_CMAKE_SYSTEM_NAME)
\> \#     set(Module_vtkGUISupportMFC ON)
\> \# else()
\> \#     set(Module_vtkGUISupportMFC OFF)
\> \# endif()

**Comment by NancyLi1013** [comment]
Hi @bhwqy thanks for posting this issue. We have updated atlmfc as feature. Please try to update vcpkg and use it.
