### ISSUE TITLE
A lot of "The directory is not empty." errors when updgrade packages

### ISSUE THREAD

**Issue by goodguysoft** [microsoft/vcpkg#8546]
I try to update `vcpkg` packages with `vcpkg update --no-dry-run`. Unfortunatelly, I get a lot of errors similar to this one:

`Failure to remove_all(c:\\vcpkg\packages\boost-any_x64-windows-static) due to file c:\\vcpkg\packages\boost-any_x64-windows-static\share: The directory is not empty.`

I receive a lot of such errors for `eigen` and different packages from `boost` project, so it looks like it is `vcpkg` itself issue and not ports one.

After multiple restarts it finally started to build updated libraries versions, but it didn't build any libraries where this error occurred, so I had to install them later manually.

**Comment by LilyWangL** [comment]
PR #7201

**Comment by NulAsh** [comment]
Maybe your antivirus affects directory tree deletion?

**Comment by goodguysoft** [comment]
Who knows? My antivirus is also Microsoft's one (Security Essentials on Windows 7 x64).

**Comment by NulAsh** [comment]
Sometimes I also see the same error when deleting folders with Far Manager. For some reason, if you try to delete folder immediately after deleting files from it, sometimes it fails to delete. You can wait a little or change deletion order. With Far, i usually do the following - when first error message "Directory not empty" shows, i press "Skip all". It deletes all files and most of folders. On the second step, i delete remaining folders. I think this bug can be related to indexing or antivirus work. You can also try my patch. #6741

**Comment by Cheney-W** [comment]
I can't reproduce this issue in the latest vcpkg(2021-08-03-1a6d67b8150e94b7f473c6ab1c0cfd) with the command: .`\vcpkg.exe upgrade --no-dry-run`
