### ISSUE TITLE
[New Port Request] ThorsSerializer

### ISSUE THREAD

**Issue by Pospelove** [microsoft/vcpkg#8548]
Library name: ThorsSerializer

Library description:

Yet another JSON/YAML/Binary serialization library for C++.

Unlike other libraries, this one does not require you to build DOM of your object before serialization. Using a declarative C++ style you define what C++ classes (and members) you want to serialize "ThorSerializer" will generate the appropriate code automagically.

Source repository URL: https://github.com/Loki-Astari/ThorsSerializer

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
