### ISSUE TITLE
[libftdi1]LibFTDI1Config.cmake contains invalid path to libusb-1.0.lib

### ISSUE THREAD

**Issue by desowin** [microsoft/vcpkg#8550]
**Describe the bug**
When I try to write new port for libopenvizsla (#8033), the build fails because it cannot find '/lib/libusb-1.0.lib'. Please check the https://github.com/desowin/vcpkg/tree/libopenvizsla to see my attempt.

**Environment**
- OS: Windows 10
- Compiler: Microsoft Visual Studio Community 2019

**To Reproduce**
1.Get vcpkg from https://github.com/desowin/vcpkg/tree/libopenvizsla
2. ./vcpkg install libopenvizsla
3. Check vcpkg\buildtrees\libopenvizsla\install-x86-windows-dbg-err.log
(optional) 4. Open installed\x86-windows\share\libftdi1\LibFTDI1Config.cmake and notice there is:
set ( LIBFTDI_LIBRARIES    "ftdi1;${_IMPORT_PREFIX}/lib/libusb-1.0.lib" )

I believe the ${_IMPORT_PREFIX}/lib/libusb-1.0.lib is the problematic part.

**Expected behavior**
The project should compile and link just fine.

**Failure logs** 
ninja: warning: multiple rules generate openvizsla.lib. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
ninja: error: '/lib/libusb-1.0.lib', needed by 'openvizsla.lib', missing and no known rule to make it

**Additional context**
I would really like if someone suggested how to solve the other issues I will observe after this one is fixed (most likely it'll fail due to lack of libzip detection)

**Comment by Voskrese** [comment]
problem dynamic | static linking

compile ignore error, mix
ninja -w dupbuild=warn

**Comment by NancyLi1013** [comment]
Hi @desowin 
Thanks for posting this issue.
I try to build `libopenvizsla` with Ninja, I met the error:
`ninja: error: build.ninja:277: multiple rules generate openvizsla.lib [-w dupbuild=err]`
This is a bug for ninja that is introduced in 1.8.0.

I comment `PREFER_NINJA` out, then try to build it again, the errors are:
```
5>F:\tools\vcpkg\buildtrees\libopenvizsla\src\cfa81a25ab-694f37b55f\src\ov.c(110): error C2375: 'ov_new': redefinition; different linkage [F:\tools\vcpkg\buildtrees\libopenvizsla\x86-windows-dbg\openvizsla.vcxproj]
         F:\tools\vcpkg\buildtrees\libopenvizsla\src\cfa81a25ab-694f37b55f\include\ov.h(53): note: see declaration of 'ov_new'
     5>F:\tools\vcpkg\buildtrees\libopenvizsla\src\cfa81a25ab-694f37b55f\src\ov.c(153): error C2375: 'ov_open': redefinition; different linkage [F:\tools\vcpkg\buildtrees\libopenvizsla\x86-windows-dbg\openvizsla.vcxproj]
         F:\tools\vcpkg\buildtrees\libopenvizsla\src\cfa81a25ab-694f37b55f\include\ov.h(54): note: see declaration of 'ov_open'
     5>F:\tools\vcpkg\buildtrees\libopenvizsla\src\cfa81a25ab-694f37b55f\src\ov.c(204): error C2375: 'ov_free': redefinition; different linkage [F:\tools\vcpkg\buildtrees\libopenvizsla\x86-windows-dbg\openvizsla.vcxproj]
         F:\tools\vcpkg\buildtrees\libopenvizsla\src\cfa81a25ab-694f37b55f\include\ov.h(55): note: see declaration of 'ov_free'
     5>F:\tools\vcpkg\buildtrees\libopenvizsla\src\cfa81a25ab-694f37b55f\src\ov.c(212): error C2375: 'ov_get_usb_speed': redefinition; different linkage [F:\tools\vcpkg\buildtrees\libopenvizsla\x86-windows-dbg\openvizsla.vcxproj]
         F:\tools\vcpkg\buildtrees\libopenvizsla\src\cfa81a25ab-694f37b55f\include\ov.h(57): note: see declaration of 'ov_get_usb_speed'
     5>F:\tools\vcpkg\buildtrees\libopenvizsla\src\cfa81a25ab-694f37b55f\src\ov.c(225): error C2375: 'ov_set_usb_speed': redefinition; different linkage [F:\tools\vcpkg\buildtrees\libopenvizsla\x86-windows-dbg\openvizsla.vcxproj]
         F:\tools\vcpkg\buildtrees\libopenvizsla\src\cfa81a25ab-694f37b55f\include\ov.h(58): note: see declaration of 'ov_set_usb_speed'
```
So I think that this is not related with `libftdi1
`.
Could you please try to check it again?

**Comment by NancyLi1013** [comment]
@desowin 
Please let me know if this is still a problem for you.

**Comment by NancyLi1013** [comment]
I'm closing issue for now since there is no response.

Please feel free to reopen this if it is still a problem for you.
