### ISSUE TITLE
SDL2 build failure

### ISSUE THREAD

**Issue by Ilkhom-S** [microsoft/vcpkg#8553]
**Host Environment**
- OS:  Windows
- Compiler: latest

**To Reproduce**
`./vcpkg install sdl2`

**Failure logs** 
CMake Error: Problem with archive_write_header(): Can't create ''
CMake Error: Current file: SDL-release-2.0.9/android-project-ant/AndroidManifest.xml
CMake Error: Problem extracting tar: C:/vcpkg/downloads/SDL-Mirror-SDL-release-2.0.9.tar.gz

**Comment by LilyWangL** [comment]
Hi @Ilkhom-S, I can't reproduce it locally. Can you provide the complete log? You can attach the log file on this issue.

**Comment by JackBoosY** [comment]
Hi @Ilkhom-S, thanks for reporting this issue,
I think it's a cmake bug, see [here](https://gitlab.kitware.com/cmake/cmake/issues/19132).

The solution is to modify _VCPKG_PATH/scripts/vcpkgTools.xml_ to change the cmake version to below 3.14.0, or use the workaround in cmake.

Here is my vcpkgTools.xml:
Line 3-9
```
    <tool name="cmake" os="windows">
        <version>3.13.4</version>
        <exeRelativePath>cmake-3.13.4-win32-x86\bin\cmake.exe</exeRelativePath>
        <url>https://github.com/Kitware/CMake/releases/download/v3.13.4/cmake-3.13.4-win32-x86.zip</url>
        <sha512>285f8bc0beaa6987a6d76f12747332a5c403ecd8c129c7029d56dd32468ed8ff4a87d6e5639ac341161c918e9caf33f39582881205cbbfc00d9796547258d06c</sha512>
        <archiveName>cmake-3.13.4-win32-x86.zip</archiveName>
    </tool>
```

**Comment by Ilkhom-S** [comment]
Hello @JackBoosY , 
Thanks for helping. After downgrading version to 3.13.4 , it works.
