### ISSUE TITLE
[jsoncpp] :x64-windows build failure

### ISSUE THREAD

**Issue by winkyz** [microsoft/vcpkg#8573]
**Host Environment**
- OS: [e.g. Windows10]
- Compiler: Merge pull request #8565 from jspaith/iot-provisioning

**To Reproduce**
`.\vcpkg.exe install jsoncpp:x64-windows`

**Failure logs** 
PS C:\Users\Admin\Downloads\vcpkg-master> .\vcpkg.exe install jsoncpp:x64-windows
The following packages will be built and installed:
    jsoncpp[core]:x64-windows
Starting package 1/1: jsoncpp:x64-windows
Building package jsoncpp[core]:x64-windows...
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
Please install the English language pack.
-- Using cached C:/Users/Admin/Downloads/vcpkg-master/downloads/open-source-parsers-jsoncpp-1.9.1.tar.gz
-- Using source at C:/Users/Admin/Downloads/vcpkg-master/buildtrees/jsoncpp/src/1.9.1-f819ab5ce5
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/Users/Admin/Downloads/vcpkg-master/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe C:/Users/Admin/Downloads/vcpkg-master/buildtrees/jsoncpp/src/1.9.1-f819ab5ce5 -DJSONCPP_WITH_CMAKE_PACKAGE:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=OFF -DJSONCPP_WITH_PKGCONFIG_SUPPORT:BOOL=OFF -DJSONCPP_WITH_TESTS:BOOL=OFF -DCMAKE_MAKE_PROGRAM=C:/Users/Admin/Downloads/vcpkg-master/downloads/tools/ninja/ninja-1.8.2/ninja.exe -DBUILD_SHARED_LIBS=ON -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/Admin/Downloads/vcpkg-master/scripts/toolchains/windows.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=v140 -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=C:/Users/Admin/Downloads/vcpkg-master/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=C:/Users/Admin/Downloads/vcpkg-master/packages/jsoncpp_x64-windows/debug
    Working Directory: C:/Users/Admin/Downloads/vcpkg-master/buildtrees/jsoncpp/x64-windows-dbg
    Error code: 1
    See logs for more information:
      C:\Users\Admin\Downloads\vcpkg-master\buildtrees\jsoncpp\config-x64-windows-dbg-out.log
      C:\Users\Admin\Downloads\vcpkg-master\buildtrees\jsoncpp\config-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:305 (vcpkg_execute_required_process)
  ports/jsoncpp/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package jsoncpp:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: jsoncpp:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.
PS C:\Users\Admin\Downloads\vcpkg-master> .\vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by LilyWangL** [comment]
Hi @winkyz, I installed it successfully with vcpkg latest source. I found this warning in your build log. Did you install the English language pack on your Visual Studio Installer?
```
Warning: The following VS instances are excluded because the English language pack is unavailable.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
Please install the English language pack.
```

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
