### ISSUE TITLE
How do I use packages installed by vcpkg in Visual Studio 2019 and Visual Studio 2019 Preview?

### ISSUE THREAD

**Issue by fishnet37222** [microsoft/vcpkg#8574]
I'm trying to use vcpkg to manage the third-party libraries for a C++ project I'm creating.

I have set the `VCPKG_DEFAULT_TRIPLET` environment variable to `x64-windows`.  I have installed boost, poco, xerces-c, and wxwidgets using vcpkg.  All four of them installed without any errors.

I ran the command `vcpkg integrate install` and did not get any errors.  However, when I create an empty C++ project in Visual Studio 2019, I do not see any header files for those packages in the intelli-sense drop-down.

I tried building the project as the instructions at [https://github.com/microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md](https://github.com/microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md) state to no avail.

I'm using Microsoft Windows [Version 10.0.18999.1].  I have the latest versions of both Visual Studio 2019 and Visual Studio 2019 Preview installed.

**Comment by fishnet37222** [comment]
Something that wasn't in the documentation is that you need to make sure you have the correct configuration selected in the drop-down in Visual Studio.  I had only installed the 64-bit versions of the libraries but Visual Studio selects the 32-bit configuration of C++ projects by default.  Once I removed the 32-bit configuration from my project, the issues disappeared.

**Comment by navono** [comment]
vcpkg installed version and Visual Studio configruation matched, but compile still failed.

**Comment by MidnQP** [comment]
> Something that wasn't in the documentation is that you need to make sure you have the correct configuration selected in the drop-down in Visual Studio. I had only installed the 64-bit versions of the libraries but Visual Studio selects the 32-bit configuration of C++ projects by default. Once I removed the 32-bit configuration from my project, the issues disappeared.

@fishnet37222 Another point for **everyone** to keep in concern is...
> Are your building for `Debug` or `Release`?

Because some packages like `curl[tool]` has the _Release_ libraries named to `libcurl.lib`, but the _Debug_ lib is named `libcurl-d.lib`. Similarly, `zlibd.lib`. So, change **Linker > General > Additional Library dependency**  accordingly.
