### ISSUE TITLE
How do I get vcpkg installed library directory to include them in build script

### ISSUE THREAD

**Issue by am2222** [microsoft/vcpkg#8577]
Hi,
I have a simple question about using vcpkg, I know how I can integrate it with vs but I wanted to include the installed libraries in build script of my code to install it using python install command. So far I could manually get the directory of `E:\vcpkg\installed\x86-windows\include` and add this directory to include path of my code and it works. But is there any environment variable so I can check to find where is installed directory of vcpkg? or even is it safe to use this directory directly?

**Comment by PhoebeHui** [comment]
@am2222, you can use '${VCPKG_ROOT_DIR}\installed\${TRIPLET}\include' instead, but you should specify VCPKG_ROOT_DIR and TRIPLET.

**Comment by am2222** [comment]
@PhoebeHui Hi, Is that a kind of system environment? or it is CMAKE variable?

**Comment by PhoebeHui** [comment]
@am2222, it's environment variable that we used in portfile.cmake, it's not a system environment.

**Comment by am2222** [comment]
@PhoebeHui So I can not access it using python setup.py environment, right?

**Comment by PhoebeHui** [comment]
Yes

**Comment by Voskrese** [comment]
call env ... msvc cmd

set include=%include%;e:\vcpkg\....\include
set lib=%lib%;e:\vcpkg\....\lib

python setup.py build

**Comment by am2222** [comment]
@Voskrese thanks so much.
I have one question related to lib environment variable. If I set it I don't need to define it in setup.py anymore? Since I have a problem with my library, despite that I define the directory of vcpkg in setup.py it still raises link error.
```
ext_modules = [
    Extension(
        include_dirs=[],
        # extra_link_args=[r'"/LIBPATH:E:\Personal\SideWorks\vcpkg\installed\x86-windows\lib"'],
        libraries =['gdal','geos','geos_c'],
        library_dirs =['E:\Personal\SideWorks\vcpkg\installed\x86-windows\lib'],
        language='c++'
    ),
]
```
This is a part of my setup.py, I asked a detailed question about it in stackoverflow but I am not sure whether my problem is with wrong use of vcpkg or somewhere else.
https://stackoverflow.com/questions/58365268/link-library-lib-using-setup-py

**Comment by Voskrese** [comment]
python env in distutils.cfg

python3\Lib\distutils\distutils.cfg - global
site.cfg - local 

https://github.com/Voskrese/vcpkg/blob/master/ports/python3-setuptools/distutils-rel.cfg.in

**Comment by am2222** [comment]
@Voskrese thanks very much
