### ISSUE TITLE
[nanorange] Showing in update/upgrade

### ISSUE THREAD

**Issue by SuperWig** [microsoft/vcpkg#8578]
This might apply to other ports, though the issue is due to the nature of how the nanorange port is installed (via `--head`) this means it shows up under update
```
The following packages differ from their port versions:
    nanorange:x64-windows            abc34279d71369527e4da43cc4d02cf77446f79a -> 0.0.0
```
Which means when `upgrade` is run it'll fail to update `nanorange` and thus mean I have to reinstall it.

---

Is it possible to have a different update detection or simply just excluding it?

**Comment by Cheney-W** [comment]
This issue still occurs in the latest vcpkg(2021-08-03-1a6d67b8150e94b7f473c6ab1c0cfd).

**Comment by Cheney-W** [comment]
The current version of vcpkg.exe can correctly identify the version installed with `--head`, and this issue has been resolved.
