### ISSUE TITLE
How to manually force rebuild of an installed package?

### ISSUE THREAD

**Issue by haimat** [Microsoft/vcpkg#858]
I have installed the `nana` package, which worked fine. Now their sources have been updated, and I want to update to that latest version. It is basically one source file that has been changed, so I downloaded it and saved it locally into `vcpkg-root/buildtrees/nana/src/...`.

However, how can I force to recompile and reinstall that package now?
The `vcpkg update` command does not help, nor did a `remove` and `install` combo help.

**Comment by tobiaskohlbau** [comment]
`vcpkg remove --purge [name]` and `vcpkg install [name]` should do the trick

**Comment by haimat** [comment]
Thanks!
