### ISSUE TITLE
ffmpeg:x64-windows build failure

### ISSUE THREAD

**Issue by ZeeshanParacha-941** [microsoft/vcpkg#8582]
**Host Environment**
- OS:  Windows 10
- Compiler: revision

**To Reproduce**
`.\vcpkg install pthreads opencv[ffmpeg]`

**Failure logs** 
-Error: Building package ffmpeg:x64-windows failed with: BUILD_FAILED
-Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ffmpeg:x64-windows
  Vcpkg version: 2019.09.12-nohash

**Additional context**
`.\vcpkg update`

**Comment by GAInTheHouse** [comment]
I am facing the same issue. I am trying to install YOLO V3 on my laptop.

**Comment by LilyWangL** [comment]
Hi @ZeeshanParacha-941, could you provide your build log?

**Comment by PhoebeHui** [comment]
@ZeeshanParacha-941 @GAInTheHouse, we can't repro this issue, everything build successfully for me, please reopen this issue and attach the failure logs if it still be an problem for you.
