### ISSUE TITLE
[New Port Request] Gnu Debugger GDB

### ISSUE THREAD

**Issue by chumbichubago** [microsoft/vcpkg#8597]
Library name: GDB

Library description: The GNU Project debugger, allows you to see what is going on `inside' another program while it executes -- or what another program was doing at the moment it crashed. 

Source repository URL: sourceware.org/git/binutils-gdb.git

Project homepage (if different from the source repository): https://www.gnu.org/software/gdb/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): See the Project homepage

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
