### ISSUE TITLE
boost SHA512 mismatch

### ISSUE THREAD

**Issue by amc522** [Microsoft/vcpkg#86]
Expected:
a1c7338e2d2dbac8552ede7c554640d22cbb2fda7fbc325dc3cdcb51e769713626695426ffc158cbe0e1729dd9a7b5ad18af4800d74e24539e8d8564268c2b9d

Current:    CF83E1357EEFB8BDF1542850D66D8007D620E4050B5715DC83F4A921D36CE9CE47D0D13C5D85F2B0FF8318D2877EEC2F63B931BD47417A81A538327AF927DA3E

**Comment by amc522** [comment]
I had cleaned my build folder several times, and tried to install boost several times. Each time returning with the same incorrect hash. Tried one more time and everything works. Goblins in the wires or something. So thanks for having hash checks.

**Comment by ras0219-msft** [comment]
Yeah, Sourceforge is really problematic. Hopefully #83 will help with this!
