### ISSUE TITLE
[New Port Request] marble

### ISSUE THREAD

**Issue by ig-or** [microsoft/vcpkg#8602]
Library name:  Marble

Library description: Find your way and explore the world!

Source repository URL: git://anongit.kde.org/marble

Project homepage (if different from the source repository): https://marble.kde.org

Looks like working on my side, for Windows10 x64; can/should I make a pull request? Or, should 100% work on all the supported platforms?

Best regards, Igor

**Comment by PhoebeHui** [comment]
@ig-or, please make a pull request for it, and our CI test system will help you test the PR in Linux, windows and MacOS, let's see if it will fail on others platform.

Thanks for your contribution!

**Comment by ig-or** [comment]
Will do. Thank you for such a useful project

**Comment by ig-or** [comment]
as expected, not all the platforms are supported. Windows static build also not supported, dynamic is OK. Can we somehow specify what triplets and platforms are supported by the library?

**Comment by PhoebeHui** [comment]
@ig-or, you can use [vcpkg_fail_port_install.md](https://github.com/microsoft/vcpkg/blob/f5c732b40d43f062278f247036b773477823813b/docs/maintainers/vcpkg_fail_port_install.md) to specify the platform and architecture that it doesn't support.

Let me know if you need more help, and very appreciate for you contribution!

**Comment by ig-or** [comment]
Now it tells following:
https://github.com/microsoft/vcpkg/pull/8628

_There are no build logs for marble build.
This is usually because the build failed early and outside of a task that is logged._

Is this expected behavior?
