### ISSUE TITLE
[grpc:x64-windows-static] build failure

### ISSUE THREAD

**Issue by Jiefei-Wang** [microsoft/vcpkg#8603]
**Host Environment**
- OS: Windows 10 x64
- Compiler: No idea, I have both gcc and VS 2017 installed

**To Reproduce**
I just follow the instruction in [google cloud installation](https://github.com/googleapis/google-cloud-cpp/blob/master/README.md#windows) and literally install/re-install every dependencies on my machine, so all libraries should be up-to-date

`.\vcpkg install grpc:x64-windows-static`

**Failure logs** 
Console:

> Starting package 6/10: grpc:x64-windows-static
> Building package grpc[core]:x64-windows-static...
> -- Downloading https://github.com/grpc/grpc/archive/v1.23.1.tar.gz...
> -- Extracting source C:/Users/Jeff/Desktop/temp/vcpkg/downloads/grpc-grpc-v1.23.1.tar.gz
> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
>     Command failed: C:/ProgramData/chocolatey/lib/cmake.portable/tools/cmake-3.15.4-win64-x64/bin/cmake.exe -E tar xjf C:/Users/Jeff/Desktop/temp/vcpkg/downloads/grpc-grpc-v1.23.1.tar.gz
>     Working Directory: C:/Users/Jeff/Desktop/temp/vcpkg/buildtrees/grpc/src/TEMP
>     Error code: 1
>     See logs for more information:
>       C:\Users\Jeff\Desktop\temp\vcpkg\buildtrees\grpc\extract-err.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_extract_source_archive.cmake:43 (vcpkg_execute_required_process)
>   scripts/cmake/vcpkg_extract_source_archive_ex.cmake:108 (vcpkg_extract_source_archive)
>   scripts/cmake/vcpkg_from_github.cmake:114 (vcpkg_extract_source_archive_ex)
>   ports/grpc/portfile.cmake:13 (vcpkg_from_github)
>   scripts/ports.cmake:94 (include)
> 
> 
> Error: Building package grpc:x64-windows-static failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: grpc:x64-windows-static
>   Vcpkg version: 2019.09.12-nohash
> 
> Additionally, attach any relevant sections from the log files above.

Log:

> CMake Error: Problem with archive_write_header(): Can't create ''
> CMake Error: Current file: grpc-1.23.1/test/core/http/python_wrapper.sh
> CMake Error: Problem extracting tar: C:/Users/Jeff/Desktop/temp/vcpkg/downloads/grpc-grpc-v1.23.1.tar.gz

I will appreciate any help. Thanks!

**Comment by JackBoosY** [comment]
@Jiefei-Wang Please see #8553.

**Comment by Jiefei-Wang** [comment]
Thanks you @JackBoosY !

**Comment by torstymctorst** [comment]
> 
> 
> Thanks you @JackBoosY ! I also found another solution, just turn off the UTF-8 support on windows in the language settings and it will work.

Worked for me too ( #9078 )
