### ISSUE TITLE
[liblzma] build failure

### ISSUE THREAD

**Issue by ET-1** [microsoft/vcpkg#8611]
**Host Environment**
- OS: CentOS Linux release 7.2.1511 (Core) 
- Compiler: gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) 

**To Reproduce**
`./vcpkg install openimageio`

**Failure logs** 
Console:

The following packages will be built and installed:
  * boost-asio[core]:x64-linux
  * boost-context[core]:x64-linux
  * boost-coroutine[core]:x64-linux
  * boost-dynamic-bitset[core]:x64-linux
  * boost-iostreams[core]:x64-linux
  * boost-random[core]:x64-linux
  * boost-serialization[core]:x64-linux
  * boost-spirit[core]:x64-linux
  * libjpeg-turbo[core]:x64-linux
  * liblzma[core]:x64-linux
  * libpng[core]:x64-linux
  * openexr[core]:x64-linux
    openimageio[core]:x64-linux
  * openssl[core]:x64-linux
  * openssl-unix[core]:x64-linux
  * tiff[core]:x64-linux
  * zlib[core]:x64-linux
Additional packages (*) will be modified to complete this operation.
Starting package 1/17: liblzma:x64-linux
Building package liblzma[core]:x64-linux...
-- Using cached /home/260351/vcpkg/downloads/xz-mirror-xz-v5.2.4.tar.gz
-- Using source at /home/260351/vcpkg/buildtrees/liblzma/src/v5.2.4-66bfe33102
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: /home/260351/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v
    Working Directory: /home/260351/vcpkg/buildtrees/liblzma/x64-linux-dbg
    See logs for more information:
      /home/260351/vcpkg/buildtrees/liblzma/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/liblzma/portfile.cmake:20 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package liblzma:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: liblzma:x64-linux
  Vcpkg version: 2019.09.12-unknownhash

Additionally, attach any relevant sections from the log files above.

Log:
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/3728518/install-x64-linux-dbg-out.log)

**Comment by Neumann-A** [comment]
Seems like the compiler is too old.

see:
https://github.com/Microsoft/vcpkg/issues/5152

**Comment by ET-1** [comment]
@Neumann-A  I updated my gcc version to gcc (GCC) 7.3.0. But the same error is still there.

**Comment by JackBoosY** [comment]
@ET-1 I think even if you upgrade gcc to 7.3.0, the default version of gcc is still the older one.
In order to confirm this, please provide the message after executing the command "gcc -v".

Thanks.

**Comment by ET-1** [comment]
@JackBoosY  Thank you for your answer. Here is the message.

[260351@w26-260351 vcpkg]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-pc-linux-gnu/7.3.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../configure -enable-checking=release -enable-languages=c,c++ -disable-multilib
Thread model: posix
gcc version 7.3.0 (GCC)

**Comment by JackBoosY** [comment]
@ET-1 Could you also provide me the log file _/home/260351/vcpkg/buildtrees/liblzma/install-x64-linux-dbg-out.log_ ?

Thanks.

**Comment by ET-1** [comment]
@JackBoosY Sure
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/3732555/install-x64-linux-dbg-out.log)

**Comment by JackBoosY** [comment]
The keyword `restrict` needs to use the gcc option `--std=c99`, which we may need to add to the build configuration.

**Comment by ET-1** [comment]
Thanks for your effort. But it does not work.

when I run  "$ ./vcpkg install openimageio"

console log:

The following packages will be built and installed:
  * boost-asio[core]:x64-linux
  * boost-context[core]:x64-linux
  * boost-coroutine[core]:x64-linux
  * boost-dynamic-bitset[core]:x64-linux
  * boost-iostreams[core]:x64-linux
  * boost-random[core]:x64-linux
  * boost-serialization[core]:x64-linux
  * boost-spirit[core]:x64-linux
  * libjpeg-turbo[core]:x64-linux
  * liblzma[core]:x64-linux
  * libpng[core]:x64-linux
  * openexr[core]:x64-linux
    openimageio[core]:x64-linux
  * openssl[core]:x64-linux
  * openssl-unix[core]:x64-linux
  * tiff[core]:x64-linux
  * zlib[core]:x64-linux
Additional packages (*) will be modified to complete this operation.
Starting package 1/17: liblzma:x64-linux
Building package liblzma[core]:x64-linux...
CMake Error at scripts/ports.cmake:73 (message):
  Unable to empty directory: /home/260351/vcpkg/packages/liblzma_x64-linux

    Files are likely in use.


Could not copy into file: /home/260351/vcpkg/packages/liblzma_x64-linux/share/liblzma/vcpkg_abi_info.txt

I attached the dbg-out log.
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/3732809/install-x64-linux-dbg-out.log)



When I try "$ sudo ./vcpkg install openimageio " same error happened as I in first comment

**Comment by JackBoosY** [comment]
```
Unable to empty directory: /home/260351/vcpkg/packages/liblzma_x64-linux
Files are likely in use.
```
Please close the files or directories which in _/home/260351/vcpkg/packages/liblzma_x64-linux_.

Thanks.

**Comment by ET-1** [comment]
@JackBoosY Close all files and directories except terminal. The same error still happened.

**Comment by JackBoosY** [comment]
@ET-1 Sorry, forgot `C99` options. Please use this:
[CMakeLists.txt](https://github.com/microsoft/vcpkg/files/3733484/CMakeLists.txt)

**Comment by ET-1** [comment]
@JackBoosY Thank you. The same error is still there.

**Comment by tpet93** [comment]
After implementing @JackBoosY 's fix. I was getting errors:
`error: ‘SIG_SETMASK’ undeclared (first use in this function)`

I added an additional -D_POSIX_SOURCE flag which seems to have fixed the issue

Changed CMakeLists lines:
at around line 136
 ```
target_compile_definitions(LibLZMA PRIVATE -DHAVE_VISIBILITY=1 -Drestrict=__restrict)
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=c99 -D_POSIX_SOURCE")

```

**Comment by JackBoosY** [comment]
@ET-1 Can you confirm that the modification of @tpet93 works?

**Comment by JackBoosY** [comment]
Please reopen this issue if it still bother you.
