### ISSUE TITLE
[imgui[example]]: Shouldn't the headers be placed in a sub-folder?

### ISSUE THREAD

**Issue by VioletGiraffe** [microsoft/vcpkg#8629]
Here's what I get in `\include\` after installing imgui[example]. Isn't this wrong?

![image](https://user-images.githubusercontent.com/1175926/66945285-71963080-f057-11e9-896e-56e651768664.png)

**Comment by NancyLi1013** [comment]
Hi @VioletGiraffe thanks for posting this issue. The headers are needed by `libigl[example]`. So they are placed as expected now.

**Comment by NancyLi1013** [comment]
Please open a new issue if you have other problems.

Thanks again.
