### ISSUE TITLE
PMDK:x64-windows installation failed in windows server 2019

### ISSUE THREAD

**Issue by abhilashuk** [microsoft/vcpkg#8637]
**Host Environment**
- OS: Windows Server 2019
- Compiler: revision

**To Reproduce**
`./vcpkg install pmdk:x64-windows

Dependencies Installed:
Visual Studio 2019
Perl
Latest Windows SDK 

**Failure logs** 
-C:\Users\Administrator\vcpkg>.\vcpkg install pmdk:x64-windows
The following packages will be built and installed:
    pmdk[core]:x64-windows
Starting package 1/1: pmdk:x64-windows
Building package pmdk[core]:x64-windows...
-- Downloading https://github.com/pmem/pmdk/archive/d2f6f5b0032eb5678ec6c5c3dff03509caa4b817.tar.gz...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:99 (message):

  File does not have expected hash:

          File path: [ C:/Users/Administrator/vcpkg/downloads/temp/pmem-pmdk-d2f6f5b0032eb5678ec6c5c3dff03509caa4b817.tar.gz ]
      Expected hash: [ 8ac50f9ea03e140eeb5fcd25ea34591b38cb76cfaa2a8622155d54b90c1cadb9fe046deeaa422163e2cd82a993a9b736523e932d66cb458ff1d2111649587e8a ]
        Actual hash: [ e93b9168eb99c5fb942ff622d6995e71e18055415a327345279cd30db5a65e8b1fc63bea3b3275e3f12935bb93e66082b1cc7c23b8331eef82349ef5f0387468 ]

  The file may have been corrupted in transit.  This can be caused by
  proxies.  If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
  environment variables to
  "https://user:password@your-proxy-ip-address:port/".

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:182 (test_hash)
  scripts/cmake/vcpkg_from_github.cmake:108 (vcpkg_download_distfile)
  ports/pmdk/portfile.cmake:13 (vcpkg_from_github)
  scripts/ports.cmake:94 (include)

Error: Building package pmdk:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: pmdk:x64-windows
  Vcpkg version: 2019.09.12-nohash

**Comment by abhilashuk** [comment]
Just an update:
Proxy has been set before using git config --global http.proxy <>

**Comment by PhoebeHui** [comment]
@abhilashuk, thanks for report this issue!

PR https://github.com/microsoft/vcpkg/pull/8586 should address this issue as well. As a workaround, you can open\ports\pmdk\portfile.cmake, and update the SHA512 to e93b9168eb99c5fb942ff622d6995e71e18055415a327345279cd30db5a65e8b1fc63bea3b3275e3f12935bb93e66082b1cc7c23b8331eef82349ef5f0387468. and try to build again, it should not block you.

**Comment by abhilashuk** [comment]
Can I bypass this download from https://github.com/pmem/pmdk/archive/d2f6f5b0032eb5678ec6c5c3dff03509caa4b817.tar.gz by downloading separately and copy into some location.
$ ./vcpkg install pmdk:x64-windows
The following packages will be built and installed:
    pmdk[core]:x64-windows
Starting package 1/1: pmdk:x64-windows
Building package pmdk[core]:x64-windows...
A suitable version of cmake was not found (required v3.14.0). Downloading portable cmake v3.14.0...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.14.0/cmake-3.14.0-win32-x86.zip -> C:\Users\Administrator\abhilash\vcpkg\downloads\cmake-3.14.0-win32-x86.zip
Extracting cmake...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> C:\Users\Administrator\abhilash\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
A suitable version of nuget was not found (required v4.6.2). Downloading portable nuget v4.6.2...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v4.6.2/nuget.exe -> C:\Users\Administrator\abhilash\vcpkg\downloads\nuget.exe
A suitable version of powershell-core was not found (required v6.2.1). Downloading portable powershell-core v6.2.1...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v6.2.1/PowerShell-6.2.1-win-x86.zip -> C:\Users\Administrator\abhilash\vcpkg\downloads\PowerShell-6.2.1-win-x86.zip
Extracting powershell-core...
-- Downloading https://github.com/pmem/pmdk/archive/d2f6f5b0032eb5678ec6c5c3dff03509caa4b817.tar.gz...
-- Downloading https://github.com/pmem/pmdk/archive/d2f6f5b0032eb5678ec6c5c3dff03509caa4b817.tar.gz... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:108 (vcpkg_download_distfile)
  ports/pmdk/portfile.cmake:13 (vcpkg_from_github)
  scripts/ports.cmake:94 (include)


Error: Building package pmdk:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: pmdk:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by abhilashuk** [comment]
I could do wget and git clone of other repo, so again this might not be related to proxy, any help would be much appreciated.

**Comment by PhoebeHui** [comment]
@abhilashuk, the PR merged, could you get latest VCPKG, and try to build again?

**Comment by abhilashuk** [comment]
I am still seeing the below issue
C:\Users\Administrator\vcpkg>.\vcpkg install pmdk:x64-windows
The following packages will be built and installed:
    pmdk[core]:x64-windows
Starting package 1/1: pmdk:x64-windows
Building package pmdk[core]:x64-windows...
A suitable version of cmake was not found (required v3.14.0). Downloading portable cmake v3.14.0...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.14.0/cmake-3.14.0-win32-x86.zip -> C:\Users\Administrator\vcpkg\downloads\cmake-3.14.0-win32-x86.zip
Extracting cmake...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> C:\Users\Administrator\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
A suitable version of nuget was not found (required v4.6.2). Downloading portable nuget v4.6.2...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v4.6.2/nuget.exe -> C:\Users\Administrator\vcpkg\downloads\nuget.exe
A suitable version of powershell-core was not found (required v6.2.1). Downloading portable powershell-core v6.2.1...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v6.2.1/PowerShell-6.2.1-win-x86.zip -> C:\Users\Administrator\vcpkg\downloads\PowerShell-6.2.1-win-x86.zip
Extracting powershell-core...
-- Downloading https://github.com/pmem/pmdk/archive/bc5e309485df61c452d08367e4b13ba9dfed5071.tar.gz...
-- Downloading https://github.com/pmem/pmdk/archive/bc5e309485df61c452d08367e4b13ba9dfed5071.tar.gz... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:108 (vcpkg_download_distfile)
  ports/pmdk/portfile.cmake:13 (vcpkg_from_github)
  scripts/ports.cmake:94 (include)

I have set proxy and proxy seems to be working as I could clone vcpkg and rest of the packages. Still I am not sure why I am seeing the above failure.

**Comment by PhoebeHui** [comment]
@abhilashuk, I can't repro your issue with latest vcpkg, It might related to proxy.
As a workaround, you can follow:
1. Download it from https://github.com/pmem/pmdk/archive/bc5e309485df61c452d08367e4b13ba9dfed5071.tar.gz manually.
2. Rename it to pmem-pmdk-bc5e309485df61c452d08367e4b13ba9dfed5071.tar.gz
3. Put it to .\downloads folder
4. ./vcpkg install pmdk:x64-windows

**Comment by abhilashuk** [comment]
Excellent, it worked.

Thanks for the workaround.

**Comment by PhoebeHui** [comment]
Great!
