### ISSUE TITLE
How do I ... Implement Crosscompiling

### ISSUE THREAD

**Issue by Pantau123** [microsoft/vcpkg#8644]
Hi,
i want to know if there is a opportunity to make a Setup for triplet arm-Linux a crosscompiler from Windows to arm Linux (for example the linaro cross Compiler)???

**Comment by cbezault** [comment]
If you provide a functioning toolchain that can cross-compile from windows to linux you can create a triplet which uses it.

**Comment by Pantau123** [comment]
I Need an example… I had test it with a user defined triplet, but that fails with Errors...

**Comment by cbezault** [comment]
https://github.com/qis/toolchains

Qis has a few examples of custom toolchains. Not exactly the one you're looking for (that probably doesn't exist).

**Comment by arthur-tacca** [comment]
Using arm with Linux is not supported for vcpkg even when you're building natively, see  #3647.

I assume that means that cross compiling for arm Linux with vcpkg is also impossible, but I don't know much about cross compilation so I could be wrong. It would certainly be an impressive workaround.

**Comment by Voskrese** [comment]
vcpkg supported for in platform - windows x64, x86 -macos -Linux x64, x86?

and you can use any toolchain for cross-compile
you just need to write it correctly

**Comment by marcbertola** [comment]
> the main and only problem that will arise is the compatibility of PORTs that you yourself will have to edit for the platform

Agreed, your mileage may vary. My recent experience with cross-compiling certain ports (Linux x64 to Linux aarch64) is that some portfiles assume that if you're compiling for arm64, then your host must be a Windows machine. They then proceed to hard-code a bunch of stuff for Windows. I had to give up on Boost and cpprestsdk because of this -- just installed the packages directly via `apt install`.

**Comment by Pantau123** [comment]
It's a big Advantage if you can develope your Application with VS and use CMAKE to cross compile and use both to checkin in your tfs and the tfs produce a correct arm Application.

**Comment by zweistein-frm2** [comment]
Actually quite a delusion that linux - arm (raspberry pi) is not supported in vcpkg.  vcpkg itself can be build natively, but then ....  would need an example to proceed myself, otherwise too much time to invest.
Regards

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed, so I am closing this issue for now.
