### ISSUE TITLE
ffmpeg build failure

### ISSUE THREAD

**Issue by pdehne** [microsoft/vcpkg#8660]
**Host Environment**
- OS: Windows
- Compiler: Visual Studio 2019

**To Reproduce**
`./vcpkg install ffmpeg:arm-uwp`

**Failure logs** 

```
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:306 (file):
file option PERMISSIONS may not appear before PATTERN or REGEX.
Call Stack (most recent call first):
ports/ffmpeg/portfile.cmake:136 (vcpkg_find_acquire_program)
scripts/ports.cmake:94 (include)
```

**Additional context**
The problem seems to be in scripts/cmake/vcpkg_find_acquire_program.cmake, introduced in commit 0433989b:
````
if(DEFINED _vfa_RENAME)
        file(INSTALL ${ARCHIVE_PATH} DESTINATION ${PROG_PATH_SUBDIR} RENAME ${_vfa_RENAME} PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
else()
        file(COPY ${ARCHIVE_PATH} DESTINATION ${PROG_PATH_SUBDIR} PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
````

Removing everything after and including PERMISSIONS fixes this errors. The build is still not working though, it stops with assembly compile errors:

```
Error running assembler at /c/d/vcpkg/downloads/tools/gas-preprocessor/gas-preprocessor.pl line 1174.
make: *** [/c/d/vcpkg/buildtrees/ffmpeg/src/n4.2-02d8c63f80/ffbuild/common.mak:71: libavutil/arm/float_dsp_neon.o] Error 1
make: *** Waiting for unfinished jobs....
Error running assembler at /c/d/vcpkg/downloads/tools/gas-preprocessor/gas-preprocessor.pl line 1174.
make: *** [/c/d/vcpkg/buildtrees/ffmpeg/src/n4.2-02d8c63f80/ffbuild/common.mak:71: libavutil/arm/float_dsp_vfp.o] Error 1
```

**Comment by JackBoosY** [comment]
Confirmed, @cenit could you have a look?
Thanks.

**Comment by cenit** [comment]
Sure, I'll look into it asap

**Comment by songshizhao** [comment]
same error

**Comment by shibayan** [comment]
I read the cmake manual, but `FILE_PERMISSIONS` seems to be correct.
(`PERMISSIONS` => `FILE_PERMISSIONS`)

https://cmake.org/cmake/help/v3.14/command/file.html#copy

**Comment by shibayan** [comment]
The build error on ARM32 is due to regression in VS16.3.
You can choose to use libav's gas-preprocessor.pl or wait for the release of VS16.5.

https://github.com/libav/gas-preprocessor/blob/master/gas-preprocessor.pl
https://developercommunity.visualstudio.com/content/problem/757709/armasm-fails-to-handle-it-instructions.html

**Comment by songshizhao** [comment]
> The build error on ARM32 is due to regression in VS16.3.
> You can choose to use libav's gas-preprocessor.pl or wait for the release of VS16.5.
> 
> https://github.com/libav/gas-preprocessor/blob/master/gas-preprocessor.pl
> https://developercommunity.visualstudio.com/content/problem/757709/armasm-fails-to-handle-it-instructions.html

I changed the gas-preprocessor.pl file in download folder, and response is as below:
------
  File does not have expected hash:

          File path: [ C:/vcpkg/downloads/gas-preprocessor.pl ]
      Expected hash: [ f6965875608bf2a3ee337e00c3f16e06cd9b5d10013da600d2a70887e47a7b4668af87b3524acf73dd122475712af831495a613a2128c1adb5fe0b4a11d96cd3 ]
        Actual hash: [ 47165cf016e570442eeceffe69d781099991c48274e47e6debb04d5312390e2716ebe73406b5672cb7e94b80a0ea101163a1c72b560fbba8125482554daab401 ]

  Please delete the file and retry if this file should be downloaded again.
-----
so how can I change it ?

**Comment by shibayan** [comment]
The following parts need to be rewritten.
https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_find_acquire_program.cmake#L222

**Comment by songshizhao** [comment]
is this the latest gas-preprocessor.pl you mentioned?
https://github.com/libav/gas-preprocessor/blob/master/gas-preprocessor.pl
Unfortunately the problem is not resolved
The error is the same as the beginning

**Comment by shibayan** [comment]
Since the error of gas-preprocessor.pl is different from the error of cmake file, it is necessary to change to `PERMISSIONS` => `FILE_PERMISSIONS` by referring to this comment and related PR change.
https://github.com/microsoft/vcpkg/issues/8660#issuecomment-559939170

**Comment by songshizhao** [comment]
I dont quite understand cmake ,so I try to remove all the PERMISSIONS words
line 306 of  scripts/cmake/vcpkg_find_acquire_program.cmake changed like this:
file(COPY ${ARCHIVE_PATH} DESTINATION ${PROG_PATH_SUBDIR})
and it is working this time
just let you know and thank you for your help 👍

**Comment by JackBoosY** [comment]
Does this issue still exist?

**Comment by pdehne** [comment]
No. I just tried another compile and the error no longer occurs.

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
