### ISSUE TITLE
[assimp] Incorrect link behavior

### ISSUE THREAD

**Issue by jherico** [microsoft/vcpkg#8662]
**Describe the bug**

Attempting to use the assimp package fails with the error 
> ...\installed\x64-windows\bin\assimp-vc142-mt.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x300

To use assimp I'm installing it via `vcpkg install assimp --triplet x64-windows`

In my project I'm targeting assimp by using the following lines in CMake

    find_package(assimp CONFIG REQUIRED)
    target_link_libraries(${TARGET_NAME} PRIVATE assimp::assimp)

When I try to build and link my project I get the above link error.  Investigating the project settings I see that the linker is attempting to use the DLL file as link input, rather than a lib file.  Manually changing the project to target the lib file allows me to build and run, but only works until the next time I run cmake.

![image](https://user-images.githubusercontent.com/1533642/67113875-69411100-f18f-11e9-8510-76c361c08cdd.png)

**Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019 16.3.3

**To Reproduce**
1. ./vcpkg install assimp --triplet x64-windows
2. In cmake use the `find_package` and `target_link_libraries` logic as above to target the assimp package
3.  Build and link the client application

**Expected behavior**
Link succeeds

**Failure logs** 
```
1>------ Build started: Project: ZERO_CHECK, Configuration: Release x64 ------
2>------ Build started: Project: vr_openxr, Configuration: Release x64 ------
2>D:\ezvcpkg\fa7a3eaec35409d60dbc456d5229b54c192f11de\installed\x64-windows\bin\assimp-vc142-mt.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x300
2>Done building project "vr_openxr.vcxproj" -- FAILED.
========== Build: 1 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========
```

**Comment by jherico** [comment]
Possibly related to https://github.com/assimp/assimp/issues/2685 ?

**Comment by jherico** [comment]
Created new assimp bug here https://github.com/assimp/assimp/issues/2721

**Comment by Voskrese** [comment]
attach the file itself `assimp-vc142-mt.dll`
I think 
linked not correct

**Comment by jherico** [comment]
[assimp-vc142-mt.dll.zip](https://github.com/microsoft/vcpkg/files/3745140/assimp-vc142-mt.dll.zip)
[assimp-vc142-mt.lib.zip](https://github.com/microsoft/vcpkg/files/3745141/assimp-vc142-mt.lib.zip)

**Comment by Voskrese** [comment]
all ok

dumpbin /DEPENDENTS assimp-vc142-mt.dll

```
  Image has the following dependencies:

    zlib1.dll
    KERNEL32.dll
    MSVCP140.dll
    VCRUNTIME140.dll
    VCRUNTIME140_1.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-time-l1-1-0.dll
```

add deps zlib1.dll ?

**Comment by jherico** [comment]
I think you're missing the point.  The cmake config is injecting the `.dll` into the list of link libraries, instead of the corresponding `.lib` file.  The DLL itself is fine, it's just not a suitable input to the linker.

**Comment by Voskrese** [comment]
read initially not closely
the reason is different

sorry
