### ISSUE TITLE
How do I link GDAL to library compile

### ISSUE THREAD

**Issue by am2222** [microsoft/vcpkg#8664]
Hi,
I want to compile a library which is using gdal and I have to link it, I am currently adding `vcpkg\installed\x86-windows\include` to the include directory and also added `vcpkg\installed\x86-windows\lib` as libraries directory into my setup.py file. but it still raises liker error
```
d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /nodefaultlib:libucrt.lib ucrt.lib /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO "/LIBPATH:C:\Program Files\Python36\libs" "/LIBPATH:C:\Program Files\Python36\PCbuild\amd64" "/LIBPATH:d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.7.2\lib\um\x64" "/LIBPATH:D:\Windows Kits\10\lib\10.0.17763.0\ucrt\x64" "/LIBPATH:D:\Windows Kits\10\lib\10.0.17763.0\um\x64" /LIBPATH:E:\Personal\SideWorks\vcpkg\installed\x86-windows\lib gdal.lib geos.lib geos_c.lib /EXPORT:PyInit_pydggrid build\temp.win-amd64-3.6\Release\Personal\Lab\DGGRID\pydggrid-master\src\main.obj build\temp.win-amd64-3.6\Release\Personal\Lab\DGGRID\pydggrid-master\src\lib\dggrid\binpres.obj .
.
.
.
build\temp.win-amd64-3.6\Release\Personal\Lab\DGGRID\pydggrid-master\src\lib\dglib.obj /OUT:build\lib.win-amd64-3.6\pydggrid.cp36-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.6\Release\Personal\Lab\DGGRID\pydggrid-master\src\pydggrid.cp36-win_amd64.lib
Creating library build\temp.win-amd64-3.6\Release\Personal\Lab\DGGRID\pydggrid-master\src\pydggrid.cp36-win_amd64.lib and object build\temp.win-amd64-3.6\Release\Personal\Lab\DGGRID\pydggrid-master\src\pydggrid.cp36-win_amd64.exp
gridgen.obj : error LNK2001: unresolved external symbol GDALAllRegister
quadclip.obj : error LNK2001: unresolved external symbol CSLPartialFindString
DgOutShapefile.obj : error LNK2001: unresolved external symbol DBFWriteStringAttribute
build\lib.win-amd64-3.6\pydggrid.cp36-win_amd64.pyd : fatal error LNK1120: 215 unresolved externals
error: command 'd:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX86\\x64\\link.exe' failed with exit status 1120

```
```
ext_modules = [
    Extension(
        include_dirs=[],
        # extra_link_args=[r'"/LIBPATH:E:\Personal\SideWorks\vcpkg\installed\x86-windows\lib"'],
        libraries =['gdal','geos','geos_c'],
        library_dirs =['E:\Personal\SideWorks\vcpkg\installed\x86-windows\lib'],
        language='c++'
    ),
]
```
I think this is because of my wrong linking method. I found that there is a CMAKE function named `find_gdal` (https://github.com/Kitware/CMake/blob/master/Modules/FindGDAL.cmake) which sets some environment variables. however I am using python's setup.py to build the library so I don't access to this command. Is there any way to link this library manually?

**Comment by am2222** [comment]
https://github.com/microsoft/vcpkg/issues/5891

**Comment by Voskrese** [comment]
?
`https://github.com/am2222/pydggrid`

set "boost_dir=E:/tools/vcpkg/installed/x64-windows/include/boost"

`E:\tools\vcpkg\installed\x64-windows\python3\python -mpip install git+https://github.com/am2222/pydggrid`

> "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.23.28105\bin\HostX64\x64\cl.exe" /c /nologo /Ox /W3 /GL /DNDEBUG /MT -IC:\temp\pip-req-build-nt2e76t9\src\lib\shapelib\include -IC:\temp\pip-req-build-nt2e76t9\src\lib\proj4lib\include -I/usr/local/include/python3.6 -IE:\tools\vcpkg\installed\x64-windows\python3\Library\include -IE:/tools/vcpkg/installed/x64-windows/include/boost -IE:\tools\vcpkg\installed\x64-windows\python3\Library\include -IE:/tools/vcpkg/installed/x64-windows/python3/include -IE:/tools/vcpkg/installed/x64-windows/include -IE:\tools\vcpkg\installed\x64-windows\python3\include -IE:\tools\vcpkg\installed\x64-windows\python3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.23.28105\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.23.28105\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" -IE:/tools/vcpkg/installed/x64-windows/include /EHsc /TpC:\temp\pip-req-build-nt2e76t9\src\main.cpp /Fobuild\temp.win-amd64-3.7\Release\temp\pip-req-build-nt2e76t9\src\main.obj /EHsc /DVERSION_INFO=\"0.0.14\" -D_hypot=hypot /w /Y-

>      Creating library build\temp.win-amd64-3.7\Release\temp\pip-req-build-nt2e76t9\src\pydggrid.cp37-win_amd64.lib and object build\temp.win-amd64-3.7\Release\temp\pip-req-build-nt2e76t9\src\pydggrid.cp37-win_amd64.exp
>   main.obj : error LNK2001: unresolved external symbol PyUnicode_AsEncodedString
>   main.obj : error LNK2001: unresolved external symbol PyBaseObject_Type
>   main.obj : error LNK2001: unresolved external symbol PyMem_Calloc
>   main.obj : error LNK2001: unresolved external symbol PyCFunction_Type
>   main.obj : error LNK2001: unresolved external symbol PyWeakref_NewRef
>   main.obj : error LNK2001: unresolved external symbol PyThreadState_Get
>   main.obj : error LNK2001: unresolved external symbol PyLong_AsUnsignedLong
>   main.obj : error LNK2001: unresolved external symbol PyThread_get_key_value
>   main.obj : error LNK2001: unresolved external symbol PyBytes_AsString
>   main.obj : error LNK2001: unresolved external symbol PyErr_NormalizeException
>   main.obj : error LNK2001: unresolved external symbol PyErr_Occurred
>   main.obj : error LNK2001: unresolved external symbol PyLong_FromSsize_t
>   main.obj : error LNK2001: unresolved external symbol PyUnicode_DecodeUTF8
>   main.obj : error LNK2001: unresolved external symbol PyEval_SaveThread
>   main.obj : error LNK2001: unresolved external symbol _PyThreadState_UncheckedGet
>   main.obj : error LNK2001: unresolved external symbol PyExc_RuntimeError
>   main.obj : error LNK2001: unresolved external symbol PyObject_SetAttrString
>   main.obj : error LNK2001: unresolved external symbol PyInstanceMethod_Type
>   main.obj : error LNK2001: unresolved external symbol PyExc_MemoryError
>   main.obj : error LNK2001: unresolved external symbol PyLong_FromUnsignedLongLong
>   main.obj : error LNK2001: unresolved external symbol Py_GetVersion
>   main.obj : error LNK2001: unresolved external symbol PyCapsule_GetContext
>   main.obj : error LNK2001: unresolved external symbol PyFrame_GetLineNumber
>   main.obj : error LNK2001: unresolved external symbol PyFloat_AsDouble
>   main.obj : error LNK2001: unresolved external symbol PyLong_AsUnsignedLongLong
>   main.obj : error LNK2001: unresolved external symbol PyGILState_Release
>   main.obj : error LNK2001: unresolved external symbol PyBytes_AsStringAndSize
>   main.obj : error LNK2001: unresolved external symbol _Py_NoneStruct
>   main.obj : error LNK2001: unresolved external symbol PyLong_AsLongLong
>   main.obj : error LNK2001: unresolved external symbol PyTuple_New
>   main.obj : error LNK2001: unresolved external symbol PyDict_Size
>   main.obj : error LNK2001: unresolved external symbol PyFloat_FromDouble
>   main.obj : error LNK2001: unresolved external symbol PyErr_SetString
>   main.obj : error LNK2001: unresolved external symbol PyExc_ValueError
>   main.obj : error LNK2001: unresolved external symbol PyDict_Next
>   main.obj : error LNK2001: unresolved external symbol PyErr_Format
>   main.obj : error LNK2001: unresolved external symbol PyThreadState_New
>   main.obj : error LNK2001: unresolved external symbol _Py_FalseStruct
>   main.obj : error LNK2001: unresolved external symbol PyFloat_Type
>   main.obj : error LNK2001: unresolved external symbol PyType_IsSubtype
>   main.obj : error LNK2001: unresolved external symbol PyErr_Restore
>   main.obj : error LNK2001: unresolved external symbol PyTuple_GetItem
>   main.obj : error LNK2001: unresolved external symbol PyErr_ExceptionMatches
>   main.obj : error LNK2001: unresolved external symbol PyCapsule_GetPointer
>   main.obj : error LNK2001: unresolved external symbol PyModule_AddObject
>   main.obj : error LNK2001: unresolved external symbol PyErr_Fetch
>   main.obj : error LNK2001: unresolved external symbol PyLong_AsLong
>   main.obj : error LNK2001: unresolved external symbol PyObject_ClearWeakRefs
>   main.obj : error LNK2001: unresolved external symbol PyList_New
>   main.obj : error LNK2001: unresolved external symbol PyUnicode_DecodeUTF16
>   main.obj : error LNK2001: unresolved external symbol PyModule_Create2
>   main.obj : error LNK2001: unresolved external symbol PyType_Ready
>   main.obj : error LNK2001: unresolved external symbol PyObject_GetAttrString
>   main.obj : error LNK2001: unresolved external symbol PyErr_Clear
>   main.obj : error LNK2001: unresolved external symbol PyList_Append
>   main.obj : error LNK2001: unresolved external symbol PyTuple_Size
>   main.obj : error LNK2001: unresolved external symbol PyException_SetTraceback
>   main.obj : error LNK2001: unresolved external symbol PyCapsule_New
>   main.obj : error LNK2001: unresolved external symbol PyCapsule_GetName
>   main.obj : error LNK2001: unresolved external symbol PyBytes_Size
>   main.obj : error LNK2001: unresolved external symbol PyDict_New
>   main.obj : error LNK2001: unresolved external symbol PyInstanceMethod_New
>   main.obj : error LNK2001: unresolved external symbol PyObject_IsInstance
>   main.obj : error LNK2001: unresolved external symbol PyUnicode_DecodeUTF32
>   main.obj : error LNK2001: unresolved external symbol PyMem_Free
>   main.obj : error LNK2001: unresolved external symbol PyTuple_SetItem
>   main.obj : error LNK2001: unresolved external symbol PyDict_GetItemString
>   main.obj : error LNK2001: unresolved external symbol PyThread_create_key
>   main.obj : error LNK2001: unresolved external symbol PyObject_GetItem
>   main.obj : error LNK2001: unresolved external symbol PyObject_CallObject
>   main.obj : error LNK2001: unresolved external symbol PyEval_InitThreads
>   main.obj : error LNK2001: unresolved external symbol PyObject_HasAttrString
>   main.obj : error LNK2001: unresolved external symbol PyProperty_Type
>   main.obj : error LNK2001: unresolved external symbol _Py_NotImplementedStruct
>   main.obj : error LNK2001: unresolved external symbol PyGILState_Ensure
>   main.obj : error LNK2001: unresolved external symbol PyCapsule_SetContext
>   main.obj : error LNK2001: unresolved external symbol PyNumber_Check
>   main.obj : error LNK2001: unresolved external symbol PyNumber_Long
>   main.obj : error LNK2001: unresolved external symbol PyThreadState_DeleteCurrent
>   main.obj : error LNK2001: unresolved external symbol PyExc_TypeError
>   main.obj : error LNK2001: unresolved external symbol PyThreadState_Clear
>   main.obj : error LNK2001: unresolved external symbol PyCFunction_NewEx
>   main.obj : error LNK2001: unresolved external symbol PyCapsule_Type
>   main.obj : error LNK2001: unresolved external symbol PyEval_GetBuiltins
>   main.obj : error LNK2001: unresolved external symbol PyDict_Copy
>   main.obj : error LNK2001: unresolved external symbol PyObject_Str
>   main.obj : error LNK2001: unresolved external symbol PyUnicode_AsUTF8String
>   main.obj : error LNK2001: unresolved external symbol PyExc_IndexError
>   main.obj : error LNK2001: unresolved external symbol PyExc_ImportError
>   main.obj : error LNK2001: unresolved external symbol _Py_TrueStruct
>   main.obj : error LNK2001: unresolved external symbol PyExc_SystemError
>   main.obj : error LNK2001: unresolved external symbol PyObject_SetItem
>   main.obj : error LNK2001: unresolved external symbol PyDict_DelItemString
>   main.obj : error LNK2001: unresolved external symbol PyUnicode_FromString
>   main.obj : error LNK2001: unresolved external symbol PyEval_AcquireThread
>   main.obj : error LNK2001: unresolved external symbol _PyType_Lookup
>   main.obj : error LNK2001: unresolved external symbol PyGILState_GetThisThreadState
>   main.obj : error LNK2001: unresolved external symbol PyObject_Repr
>   main.obj : error LNK2001: unresolved external symbol PyNumber_Float
>   main.obj : error LNK2001: unresolved external symbol PyType_Type
>   main.obj : error LNK2001: unresolved external symbol PyThread_set_key_value
>   main.obj : error LNK2001: unresolved external symbol _PyObject_GetDictPtr
>   build\lib.win-amd64-3.7\pydggrid.cp37-win_amd64.pyd : fatal error LNK1120: 102 unresolved externals
>   error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Tools\\MSVC\\14.23.28105\\bin\\HostX64\\x64\\link.exe' failed with exit status 1120

`cl.exe" /c /nologo /Ox /W3 /GL /DNDEBUG /MT`

MT - static
`gridgen.obj : error LNK2001: unresolved external symbol GDALAllRegister` - static symbol 

> __imp_GDALAllRegister - dynamic

python lib static !

**Comment by am2222** [comment]
@Voskrese 
Hi,
The pydggrid is the older version which gdal is not used in it. the newest version is using gdal and I am trying to compile it on windows to be able to make it's python wrapper work
so you mean I have to remove /mt from end of cl command?

**Comment by Voskrese** [comment]
yes.

**Comment by am2222** [comment]
@Voskrese I think I found my mistake. I was addressing wrong architecture as lib and includes directory.

**Comment by JackBoosY** [comment]
@am2222 So, this issue was solved?

**Comment by am2222** [comment]
@JackBoosY Actually my code compiles well. but When I run it I face can not find dll error which I think something is wrong with gdal again, since I remember we need to define some global windows variables such as `gdal_data` whenever we need to use gdal on windows and here I have not defined it .
I have also added vcpkg bin directory to the path environment variable but did not get any results yet. I recently found an issue with `proj.lib` port on vcpkg and I think that also might be a reason.

**Comment by JackBoosY** [comment]
@am2222 Yes, the library name that GDAL calls proj has a default value (`proj.dll`), or uses the value in the registry. And I should solved this issue by PR #7917, please update vcpkg and rebuild proj4/gdal.

**Comment by am2222** [comment]
@JackBoosY Hi, Sure I will check it to see if the error is because of that issue or I am doing something wrong. Thanks for your help

**Comment by janholt** [comment]
@JackBoosY Thanks for proj4 6.2.
There is still a difficulty on `Debug` that gdal tries to load `porj.dll`, but we have `proj_d.dll`.
Solution that works for me on `x64-windows` is to add `"PROJ_FLAGS=-DPROJ_STATIC -DPROJ_VERSION=5"` to `NMAKE_OPTIONS` in gdal portfile.
Here is exerption from gdal nmake.opt:
```
# PROJ stuff
# Uncomment the following lines to link PROJ library statically. Otherwise
# it will be linked dynamically during runtime.
# To use the new API of proj5 or later, use
#PROJ_FLAGS = -DPROJ_STATIC -DPROJ_VERSION=5
# for proj 4.x:
#PROJ_FLAGS = -DPROJ_STATIC -DPROJ_VERSION=4
```
And still "FindPackage GDAL not working for debug libraries.... 6502".

**Comment by am2222** [comment]
@janholt I think I could build it but could not make my code work yet

**Comment by am2222** [comment]
@janholt Hi,
I think there is a kind of ug in compiling GDAL, Maybe I am doing something wrong, I added the following directories into path
```
---\vcpkg\installed\x64-windows\share\gdal
---\vcpkg\installed\x64-windows\lib
---\vcpkg\installed\x64-windows\bin
```
and then tried to run one of the gdal tools in following directory
```
--\vcpkg\installed\x64-windows\tools
```
and I get these errors
```
---------------------------
gdalserver.exe - Entry Point Not Found
---------------------------
The procedure entry point inflateValidate could not be located in the dynamic link library E:\Personal\SideWorks\vcpkg\installed\x64-windows\bin\libpng16.dll. 
---------------------------
OK   
---------------------------
---------------------------
gdalserver.exe - Entry Point Not Found
---------------------------
The procedure entry point crc32_combine could not be located in the dynamic link library E:\Personal\SideWorks\vcpkg\installed\x64-windows\bin\gdal204.dll. 
---------------------------
OK   
---------------------------
---------------------------
gdalserver.exe - Entry Point Not Found
---------------------------
The procedure entry point gzdirect could not be located in the dynamic link library E:\Personal\SideWorks\vcpkg\installed\x64-windows\bin\libxml2.dll. 
---------------------------
OK   
---------------------------
```

**Comment by am2222** [comment]
Also I have another issue, when I am using this command `find_package(GDAL REQUIRED)` I get a wrong  path, it returns 
```
C:/Program Files/Python36/Lib/site-packages/osgeo/lib/gdal_i.lib
C:/Program Files/Python36/Lib/site-packages/osgeo/include/gdal
```
which is for my previous gdal versions which I had installed on python and now I have removed those packages and there is not any environment variable related to those paths set. I am still investigating the possible places that cmake might search to find above paths

**Comment by JackBoosY** [comment]
I have changed the gdal build method to `nmake` / `make` in #9100, then check if I can solve this issue.
