### ISSUE TITLE
[openexr] Linkage issues on Linux

### ISSUE THREAD

**Issue by JoelFilho** [microsoft/vcpkg#8668]
**Host Environment**
- OS: Linux (Ubuntu 18.04, WSL)
- Compiler: gcc 7/8, clang 8/9

### The Issues

**1\. OpenEXR is built with dynamic linkage on Linux, which has `VCPKG_LIBRARY_LINKAGE static` as default.**

To solve this issue, it's relatively straight-forward: OpenEXR does not use the default `BUILD_STATIC` and `BUILD_DYNAMIC` parameters, so we can add to `portfile.cmake`:

```cmake
string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "static" OPENEXR_BUILD_STATIC)
string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "dynamic" OPENEXR_BUILD_SHARED)
#...
vcpkg_configure_cmake( #...
  OPTIONS
    -DOPENEXR_BUILD_STATIC=${OPENEXR_BUILD_STATIC}
    -DOPENEXR_BUILD_SHARED=${OPENEXR_BUILD_SHARED}
#... 
```

This way, we are able to build the static library. 

Forcing dynamic linkage, however, yields an "empty `bin` folder" error, which can be fixed with the default suggested solution, since the folders are empty because [the binary files are moved](https://github.com/microsoft/vcpkg/blob/master/ports/openexr/portfile.cmake#L56).

```cmake
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/bin ${CURRENT_PACKAGES_DIR}/debug/bin)
```

**2\. Linking executables to OpenEXR yields error `libI***-2_3.so.24: cannot open shared object file: No such file or directory`.**

This problems arises with the current version and also after the fix and building with forced dynamic linkage. It also happens when trying to run the executable tools generated by OpenEXR, which is probably the easiest way to verify this problem.

**3\. The static libraries can't be found with the current [`FindOpenEXR.cmake`](https://github.com/microsoft/vcpkg/blob/master/ports/openexr/FindOpenEXR.cmake)**

Trying to build, for instance, OpenImageIO, after building OpenEXR as a static library, yields the error:

```
CMake Error at /.../vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenEXR (missing: OpenEXR_LIBRARIES) (Required is at least
  version "2.0")
Call Stack (most recent call first):
  /.../vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /.../vcpkg/installed/x64-linux/share/openexr/FindOpenEXR.cmake:90 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /.../vcpkg/installed/x64-linux/share/openexr/vcpkg-cmake-wrapper.cmake:5 (_find_package)
  /.../vcpkg/scripts/buildsystems/vcpkg.cmake:218 (include)
  src/cmake/externalpackages.cmake:72 (find_package)
  CMakeLists.txt:137 (include)
```

This happens due to the fact that static libraries in OpenEXR 2.3 are compiled with the suffix `_s` after the version indicator (e.g. [Half](https://github.com/openexr/openexr/blob/f4055c33bb128bd4544d265b167337c584364716/IlmBase/Half/CMakeLists.txt#L63)). 

Adding the `_s` suffix to library names  in `FindOpenEXR.cmake` seems to fix this specific problem, but I'm not sure it's the correct/optimal way to do it, hence I haven't submitted draft PR with fixes for 1 and 3.

**Comment by cenit** [comment]
Usually here we prefer to produce libraries with the same name, independent from shared/static. So instead of patching the findopenexr, what do you think about patching the openexr CMakeLists.txt so that it produces target with the same name, independent of shared/static? Would it be feasible for you in a PR?

**Comment by cenit** [comment]
About the problem with the shared libs, it should be enough for you to add the lib folder to the LD_LIBRARY_PATH

**Comment by JoelFilho** [comment]
> Usually here we prefer to produce libraries with the same name, independent from shared/static. So instead of patching the findopenexr, what do you think about patching the openexr CMakeLists.txt so that it produces target with the same name, independent of shared/static?

Makes sense. For version 2.4 (still not released), they refactored their CMake targets to reflect linkage (i.e. target names have the suffix), going even further in that direction, but we can definitely work this out easily for this version in vcpkg, as we don't build both versions for a single triplet.

> Would it be feasible for you in a PR?

Yes, I believe I can do it.

> About the problem with the shared libs, it should be enough for you to add the lib folder to the LD_LIBRARY_PATH

Adding it makes it work. My question came from the fact that I hadn't had problems with other dynamic libraries so far. 

In my specific case, I'm working with OpenImageIO, which is being compiled as dynamic because of the problems in #8049, and the output from `ldd` is:

```
linux-vdso.so.1 (0x00007fffedd2a000)
libOpenImageIO.so.2.1 => /.../vcpkg/installed/x64-linux/lib/libOpenImageIO.so.2.1 (0x00007f9b749aa000)
libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f9b745f0000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9b74250000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9b74030000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9b73c30000)
libIlmImf-2_3.so.24 => /.../vcpkg/installed/x64-linux/lib/libIlmImf-2_3.so.24 (0x00007f9b73730000)
libIex-2_3.so.24 => /.../vcpkg/installed/x64-linux/lib/libIex-2_3.so.24 (0x00007f9b73510000)
libHalf-2_3.so.24 => /.../vcpkg/installed/x64-linux/lib/libHalf-2_3.so.24 (0x00007f9b732c0000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9b730a0000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9b72e90000)
/lib64/ld-linux-x86-64.so.2 (0x00007f9b75a00000)
libIlmThread-2_3.so.24 => not found
```

I have no idea why this happens, but I will work on a PR with the solution to the other two problems.

**Comment by PhoebeHui** [comment]
@JoelFilho, thanks for submitting the PR, currently it merged.
