### ISSUE TITLE
[New Port Request] <SimpleITK>

### ISSUE THREAD

**Issue by thkvc** [microsoft/vcpkg#8672]
Library name: SimpleITK

Library description: a simplified layer build on top of the Insight Toolkit (ITK), intended to facilitate its use in rapid prototyping, education and interpreted languages. 

Source repository URL: https://github.com/SimpleITK/SimpleITK

Project homepage (if different from the source repository): http://www.simpleitk.org/

**Comment by NancyLi1013** [comment]
Hi @thkvc  thanks for posting this request. SimpleITK needs to support for Lua 5.3 
https://github.com/SimpleITK/SimpleITK/issues/849

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
