### ISSUE TITLE
[opencv[sfm]] build failure

### ISSUE THREAD

**Issue by akshit-sharma** [microsoft/vcpkg#8676]
**Describe the bug**
While building opencv with contrib libraries, I also installed vtk and sfm libraries. The sfm library does not have its corresponding header file in the installed directory of opencv2 includes.

**Environment**
- OS: Windows
- Compiler: MSVC 2019

**To Reproduce**
1. ```./vcpkg install opencv[sfm,vtk,contrib]:x86-windows```
2. Look through ```vcpkg/installed/x86-windows/include/opencv2``` folder to find ```sfm.hpp```.

**Expected behavior**
Expected to see ```sfm.hpp``` file in ```vcpkg/installed/x86-windows/include/opencv2/```.

**Additional context**
Finding ```viz.hpp``` inside vcpkg.
```
akshit:vcpkg$ find . -name viz.hpp
./buildtrees/opencv/src/3.4.3-6bc372f345/modules/viz/include/opencv2/viz.hpp
./buildtrees/opencv4/src/4.1.1-521dd00bd2/modules/viz/include/opencv2/viz.hpp
./installed/x86-windows/include/opencv2/viz.hpp
./packages/opencv4_x86-windows/include/opencv2/viz.hpp
```
Finding ```sfm.hpp``` inside vcpkg
```
akshit:vcpkg$ find . -name sfm.hpp
./buildtrees/opencv/src/3.4.3-98dbf13329/modules/sfm/include/opencv2/sfm.hpp
./buildtrees/opencv4/src/4.1.1-521dd00bd2/modules/sfm/include/opencv2/sfm.hpp
```

**Comment by cenit** [comment]
Can you please share config logs?

**Comment by akshit-sharma** [comment]
Which config log should I share?
One inside buildtrees?

[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/3748573/config-x86-windows-out.log)

config-x86-windows-err.log is empty.

**Comment by JackBoosY** [comment]
This issue will fix in #8557.

**Comment by JackBoosY** [comment]
Hi, does this issue still exist?

**Comment by akshit-sharma** [comment]
It seems to work now.
