### ISSUE TITLE
 bash: vcpkg: command not found / trying to install GTK library using vcpkg

### ISSUE THREAD

**Issue by gameboy0123** [microsoft/vcpkg#8688]
Hi, I'm trying to install the GTK library with Git Bash by following the steps provided on the GTK website. This may be a silly question, but I'm on the last step which says to run vcpkg install gtk:x64-windows. However, Git Bash returns bash: vcpkg: command not found, so I'm not sure how to finish the installation process. If it helps, I also had reference #5633 regarding the error bootstrap-vcpkg.bat not found, so maybe it's a syntax thing I'm missing?

**Comment by JackBoosY** [comment]
@gameboy0123 Which OS do you use? You can find `bootstrap-vcpkg.bat`/`bootstrap-vcpkg.sh` in vcpkg root directory. If you can't find them, please update vcpkg using command `git pull` and switch branch to `master`.

And for Windows, you should run `bootstrap-vcpkg.bat`, for Linux/MacOS should run `bootstrap-vcpkg.sh`.

**Comment by gameboy0123** [comment]
I'm on Windows. I managed to get `./bootstrap-vcpkg.bat` to work and built vcpkg.exe, but I'm unsure of how to continue from here. The GTK website seems to suggest there's an additional step to finish the installation by running `vcpkg install gtk:x64-windows` but I'm unsure how to run that in GitBash as it doesn't seem to recognize any form of `vcpkg install gtk:x64-windows`. Sorry if this isn't the right place to be asking, I'm just trying to get things sorted.
