### ISSUE TITLE
[New Port Request] Intel(r) SPMD Program Compiler

### ISSUE THREAD

**Issue by xarthurx** [microsoft/vcpkg#8698]
Library name: 
Intel(r) SPMD Program Compiler

Library description:
ispc is a compiler for a variant of the C programming language, with extensions for single program, multiple data programming. Under the SPMD model, the programmer writes a program that generally appears to be a regular serial program, though the execution model is actually that a number of program instances execute in parallel on the hardware.

Source repository URL:
https://github.com/ispc/ispc/

Project homepage (if different from the source repository):
https://ispc.github.io

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
if building `embree3` with this library and the `tbb` library enabled (default by the official repo), compiling speed will decrease.

**Comment by JackBoosY** [comment]
Need to add llvm-filecheck, git, cyg.

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by xarthurx** [comment]
@NancyLi1013  which means you're not planning to add it?
