### ISSUE TITLE
MSBuild properties for vcpkg directories

### ISSUE THREAD

**Issue by rossbrower** [microsoft/vcpkg#870]
Are there msbuild macros to point to directories within VCPKG? I would hate to have to rely on developers/build servers having the same directory structure. 

More specifically I have a project which uses libwebm and I need the libwebm.dll to get copied to the output of any project which references my project. Fortunately libwebm.dll is copied to the output directory of the project which references it so I can do a hack like the following to ensure it is always copied:

`<ItemGroup>
    <Content Include="$(SolutionDir)$(Configuration)\libwebm.dll">
      <Link>libwebm.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
</ItemGroup>`

However, another situation has come up with a managed C# project needing a copy of the binaries from a VCPKG port (OpenSSL). I would rather not have to copy these dlls into the codebase for the C# project. If there was a macro I could do something like the following:

`<ItemGroup>
    <Content Include="$(vcpkg)\packages\openssl_x86-windows\bin\libeay32.dll">
      <Link>libeay32.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
</ItemGroup>`

**Comment by ras0219-msft** [comment]
Hi @rossbrower,

For C++ MSBuild projects using either the user-wide integration or our per-project NuGet, we inject the targets file located at [scripts\buildsystems\msbuild\vcpkg.targets](https://github.com/Microsoft/vcpkg/blob/master/scripts/buildsystems/msbuild/vcpkg.targets). This targets file defines several variables of use; for your situation, I think `VcpkgRoot` would be the best, which expands to `installed\$(VcpkgTriplet)\`.

However, we have had issues in the past with trying to use this targets file in C# projects, so I don't think it is as simple as an `<Include...`.

We'd like to improve the situation here, so more details about your particular scenario would be very helpful! How are you pulling in Vcpkg for your C++ project (user-wide, NuGet, direct targets file, manually)?

**Comment by rossbrower** [comment]
Thanks, I was poking around in the source and missed that targets file. 

To answer your question I have been using the user-wide integration on the build server and on my development machine. 

In the first case above I have a C++ project which wraps the libwebm port (to expose to C#). When this C++ project builds, the libwebm.dll is correctly copied to the output directory. However, the libwebm.dll is not copied to the output of C# projects which reference the wrapper. This is not a new problem for me with C# projects so the .csproj hack above works pretty well. It would be cleaner to use the macros which you've now brought to my attention. Ideally your targets file could do something similar so this hack is not needed.

In the second case, I have a C# project which uses P/Invoke to call the dll provided by the port. I need to pull that dll into the output of the C# project. The dll can't be referenced from C# so it must be added as content. Rather than putting the dll into the source code of the C# project I would like to pull it from the output of the VCPKG port. However, this location might be in a different place for different developers or on the build server. If I could use the macros from vcpkg.targets I could ensure that the dll is correctly copied to the output of the C# project and to the output of any other C# projects which reference it. 

I hope that helps.

**Comment by BillyONeal** [comment]
@rossbrower We do have `$(VcpkgInstalledDir)`:

https://github.com/microsoft/vcpkg/blob/030cfaa24de9ea1bbf0a4d9c615ce7312ba77af1/scripts/buildsystems/msbuild/vcpkg.targets#L21-L23

does that give you what you need?

**Comment by PhoebeHui** [comment]
@rossbrower, please reopen this issue if it still be problem for you.

[VcpkgInstalledDirectory (Installed Directory)](https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md#vcpkginstalleddirectory-installed-directory)
