### ISSUE TITLE
[New Port Request] <ZED SDK>

### ISSUE THREAD

**Issue by aliabbas2810** [microsoft/vcpkg#8702]
Library name:
ZED SDK
Library description:
The ZED SDK allows you to add depth and motion sensing to your application. Available as a standalone installer, the ZED SDK includes applications, tools and sample projects with source code. 
Source repository URL:

Project homepage (if different from the source repository):
https://www.stereolabs.com/developers/release/#sdkdownloads_anchor

**Comment by JackBoosY** [comment]
@aliabbas2810 I found this SDK is an executable. Does it support command line installation?

**Comment by aliabbas2810** [comment]
Sorry for late reply. The stereolabs provide just the executable file so I don't know if it support commant line installation. The SDK requires CUDA toolkit. In my case I am using it with OpenCV, PCL and all of them can be installed using vcpkg so I thought it would be good to if I am able to install this SDK using vcpkg.

**Comment by JackBoosY** [comment]
@aliabbas2810 I made a draft to install `ZED-SDK` in #8802, but I don't know if we need to install the library/binary/other files.

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
