### ISSUE TITLE
[libpng] CMake can't link to libpng_static due to missing .lib in build

### ISSUE THREAD

**Issue by leecbaker** [microsoft/vcpkg#8704]
**Describe the bug**
When linking to the static version of libpng, CMake reports a missing file. This prevents CMake from configuring my project.

**Environment**
- OS: Windows Server 2019 on Github Actions
- Compiler: Visual Studio 2019 Enterprise: VisualStudio/16.3.0+29318.209

**To Reproduce**
1. `./vcpkg install libpng:x64-windows-static`
2. `find_package(libpng CONFIG REQUIRED)`
3. target_link_libraries(target PUBLIC png_static)
4. cmake
5. Error message: 
```CMake Error at C:/vcpkg/installed/x64-windows-static/share/libpng/libpng16.cmake:77 (message):
  The imported target "png_static" references the file

     "C:/vcpkg/installed/x64-windows-static/debug/lib/libpng16_staticd.lib"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "C:/vcpkg/installed/x64-windows-static/share/libpng/libpng16.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  C:/vcpkg/installed/x64-windows-static/share/libpng/libpngConfig.cmake:6 (include)
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:263 (_find_package)
  src/CMakeLists.txt:144 (find_package)
```

**Expected behavior**
Expected: libpng to be found by find_package() and linked successfully.

**Failure logs** 
See above.

**Additional context**

**Comment by PhoebeHui** [comment]
@leecbaker, thanks for posting this issue! Above PR should address this issue.

**Comment by leecbaker** [comment]
@PhoebeHui Thanks for looking at this.

**Comment by leecbaker** [comment]
I see #8716 is ready to merge- is anything holding this up?

**Comment by freddy77** [comment]
I can confirm this PR is needed to fix libpng static.

**Comment by PhoebeHui** [comment]
@leecbaker, @freddy77 , the PR has been merged, please get latest source and try to build libpng again.

**Comment by freddy77** [comment]
It's working great, thanks
