### ISSUE TITLE
log4cpp:x86-windows-static produces a dynamic library

### ISSUE THREAD

**Issue by zoliszel** [microsoft/vcpkg#8708]
**Describe the bug**
Hi,

I came across the above mentioned issue today when I was trying to statically link log4cpp into one of my projects. Basically the issue is that the CMake used by the original source code will by definition create a dynamically linked artifact: 
https://github.com/orocos-toolchain/log4cpp/blob/master/CMakeLists.txt#L24
https://github.com/orocos-toolchain/log4cpp/blob/master/CMakeLists.txt#L39

In order to build a static library those directives will need to be adjusted.

I'have attached a patch for both the log4cpp makefile to adjust those directives and for vcpkgs to apply the patch in the port when a statically linked library is requested. 

[log4cpp-patches.zip](https://github.com/microsoft/vcpkg/files/3762239/log4cpp-patches.zip)

Hope this helps,
Kind Regards,
Zoltan

**Environment**
- OS: Windows
- Compiler: Visual Studio 2019

**To Reproduce**
1. ./vcpkg install log4cpp:x86-windows-static
2. The generated lib will still try to link to log4cpp.dll

**Expected behavior**
The lib should be a static library not a dynamic one. 

**Failure logs** 
No errors. 

**Additional context**
See above

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
