### ISSUE TITLE
imgui_examples build failure

### ISSUE THREAD

**Issue by BenKey** [microsoft/vcpkg#8713]
**Host Environment**
- Windows 10 Pro 1903 64-bit
- Build Tools for Visual Studio 2019

**To Reproduce**
Install imgui, imgui[example], and imgui-sfml as follows.

`vcpkg install imgui imgui[example] imgui-sfml --triplet x86-windows`

**Failure logs** 

The build fails with the following error.

> Microsoft (R) Build Engine version 16.3.1+1def00d3d for .NET Framework
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> Build started 10/23/2019 10:40:48 PM.
>      1>Project "E:\vcpkg\buildtrees\imgui\src\v1.73-a85d24b4b8\examples\imgui_examples.sln" on node 1 (Rebuild target(s)).
>      1>E:\vcpkg\buildtrees\imgui\src\v1.73-a85d24b4b8\examples\imgui_examples.sln.metaproj : error MSB4126: The specified solution configuration "Release|x86" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [E:\vcpkg\buildtrees\imgui\src\v1.73-a85d24b4b8\examples\imgui_examples.sln]
>      1>Done Building Project "E:\vcpkg\buildtrees\imgui\src\v1.73-a85d24b4b8\examples\imgui_examples.sln" (Rebuild target(s)) -- FAILED.
> 
> Build FAILED.
> 
>        "E:\vcpkg\buildtrees\imgui\src\v1.73-a85d24b4b8\examples\imgui_examples.sln" (Rebuild target) (1) ->
>        (ValidateSolutionConfiguration target) -> 
>          E:\vcpkg\buildtrees\imgui\src\v1.73-a85d24b4b8\examples\imgui_examples.sln.metaproj : error MSB4126: The specified solution configuration "Release|x86" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [E:\vcpkg\buildtrees\imgui\src\v1.73-a85d24b4b8\examples\imgui_examples.sln]
> 
>     0 Warning(s)
>     1 Error(s)
> 
> Time Elapsed 00:00:00.36
> 

**Additional context**

The problem is that it is attempting to build the Release|x86 solution configuration. It should be using the Release|Win32 solution configuration.

I do not see a way to control which solution configuration is used. If it is possible to do so, that would suffice to solve this problem.

**Comment by BenKey** [comment]
Thanks. I had no idea how the platform was specified.

*-- *

*Ciao,*
*Ben Key*
*Email: bkey76@gmail.com <bkey76@gmail.com>*
*Website: https://sullivanandkey.com/ <https://sullivanandkey.com/>*
*-- *

**Comment by JackBoosY** [comment]
Does this issue still exist?

**Comment by BenKey** [comment]
No.
*-- *

*Ciao,*
*Benilda Key*
*Email: bkey76@gmail.com <bkey76@gmail.com>*
*Website: https://sullivanandkey.com/ <https://sullivanandkey.com/>*
*-- *
