### ISSUE TITLE
duktape build failure

### ISSUE THREAD

**Issue by BenKey** [microsoft/vcpkg#8714]
**Host Environment**
- Windows 10 Pro 1903 64-bit
- Build Tools for Visual Studio 2019

**To Reproduce**

Install duktape as follows.

`vcpkg install duktape --triplet x64-windows`

**Failure logs** 

> Starting package 1/1: duktape:x64-windows
> Building package duktape[core]:x64-windows...
> -- Downloading https://github.com/svaarala/duktape/archive/v2.4.0.tar.gz...
> -- Extracting source E:/vcpkg/downloads/svaarala-duktape-v2.4.0.tar.gz
> -- Using source at E:/vcpkg/buildtrees/duktape/src/v2.4.0-8a89dd584b
> -- Downloading https://www.python.org/ftp/python/2.7.16/python-2.7.16.msi...
> -- Downloading https://github.com/pypa/get-pip/archive/309a56c5fd94bd1134053a541cb4657a4e47e09d.tar.gz...
> -- Extracting source E:/vcpkg/downloads/pypa-get-pip-309a56c5fd94bd1134053a541cb4657a4e47e09d.tar.gz
> -- Using source at E:/vcpkg/buildtrees/duktape/src/7a4e47e09d-f4730c06c6
> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
> Collecting pip
>   Using cached https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl
> Installing collected packages: pip
>   Found existing installation: pip 19.3.1
>     Uninstalling pip-19.3.1:
>       Successfully uninstalled pip-19.3.1
> Successfully installed pip-19.3.1
> Traceback (most recent call last):
>   File "E:/vcpkg/buildtrees/duktape/src/v2.4.0-8a89dd584b/tools/configure.py", line 29, in <module>
>     import yaml
> ImportError: No module named yaml
> CMake Error at ports/duktape/portfile.cmake:48 (file):
>   file failed to open for reading (No such file or directory):
> 
>     E:/vcpkg/buildtrees/duktape/src/v2.4.0-8a89dd584b/src/duk_config.h
> 

The problem is that configure.py depends on yaml which is not available.

**Comment by PhoebeHui** [comment]
@BenKey, thanks for posting this issue!

This issue due to the wrong path for pip referenced in portfile, I will summit a PR for this.

**Comment by PhoebeHui** [comment]
@BenKey, the fix has been merged, you can get latest vcpkg and try to build duktape again.
