### ISSUE TITLE
[cpr] cpr outputs ZLIB::ZLIB in its IMPORTED_LINK_INTERFACE_LIBRARIES_<config>

### ISSUE THREAD

**Issue by barcharcraz** [microsoft/vcpkg#8715]
****

**Is your feature request related to a problem? Please describe.**
When I go to use CPR I get an error that I'm linking to ZLIB::ZLIB but that target was not found

**Proposed solution**
I suspect a find_dependency call is missing in cpr's port (it appears the entire install process is added by vcpkg)

**Describe alternatives you've considered**
Just calling find_package(ZLIB) in my buildsystem (should not be necessary )

**Comment by JackBoosY** [comment]
Hi @barcharcraz, thanks for reporting this issue.
Which triplet do you use? And please provide your OS version and Compiler version.

Thanks.

**Comment by barcharcraz** [comment]
OS version is windows 10 (latest stable I think), and x64-windows-static. Tried both VS 2019 preview and int preview.

**Comment by NancyLi1013** [comment]
Hi @barcharcraz, I have checked cpr source code and noticed that cpr has nothing to do with zlib.  Could you help us provide the steps to reproduce this issue or tell us how to use cpr on your local? 
If possible, please provide your project case. 

Thanks.

**Comment by barcharcraz** [comment]
I suspect that zlib becomes involved because curl is using it for http compression support.

That's why you don't necessarily see zlib mentioned. I'll look into it more at some point and provide a reproduction project

**Comment by barcharcraz** [comment]
OK steps to repro with vcpkg revision 34eff46c92019fe9e107779ec4b6ec3716194ab3

`vcpkg.exe install cpr:x64-windows-static`
Look in `installed/x64-windows-static/share/cpr/cprTargets-release.cmake` (or -debug)
Observe: 

```
set_target_properties(cpr PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "${_IMPORT_PREFIX}/lib/libcurl.lib;winmm;ws2_32;advapi32;crypt32;advapi32;ZLIB::ZLIB"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/cpr.lib"
  )
```
That reference to ZLIB::ZLIB needs to be resolved by find_dependency_macro in the cprConfig.cmake template (also the cprConfig.cmake in the port directory should probably be cprConfig.cmake.in and be configured with `configure_package_config_file`

**Comment by NancyLi1013** [comment]
Thanks for your instant reply. Could you please remove "1" here 

In your local `installed/x64-windows-static/share/curl/CURLConfig.cmake` file
```
include(CMakeFindDependencyMacro)
if()
  find_dependency(OpenSSL )
endif()
if(ON)
  find_dependency(ZLIB 1)
endif()
```
and try it again. I suspect that zlib version 1 cannot be found.

**Comment by barcharcraz** [comment]
Sure, but that config file is unlikely to do anything with cmake <= 3.17 because the built in find module will be used instead. (3.17 updates that module to try config mode)

**Comment by JackBoosY** [comment]
I cannot found `ZLIB::ZLIB` in my generated `cprTargets-debug.cmake`/`cprTargets-release.cmake`, here is the details:
```
#----------------------------------------------------------------
# Generated CMake target import file for configuration "Debug".
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Import target "cpr" for configuration "Debug"
set_property(TARGET cpr APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(cpr PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "${_IMPORT_PREFIX}/debug/lib/libcurl-d.lib"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/debug/lib/cpr.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS cpr )
list(APPEND _IMPORT_CHECK_FILES_FOR_cpr "${_IMPORT_PREFIX}/debug/lib/cpr.lib" )

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
```

Can you provide the log _VCPKG_PATH/buildtrees/cpr/config-x64-windows-static-out.log_ ?

Thanks,

**Comment by barcharcraz** [comment]
[config-x64-windows-static-out.log](https://github.com/microsoft/vcpkg/files/4027590/config-x64-windows-static-out.log)
