### ISSUE TITLE
curl[ssh,tool]:x64-linux fails (undefined reference to 'deflate')

### ISSUE THREAD

**Issue by phoyd** [microsoft/vcpkg#8733]
Building `curl[ssh,tool]:x64-linux` on a fresh vcpkg clone on Linux Mint 19.2 fails. 

Steps to reproduce: 
```
$ cc --version
cc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
$ git clone https://github.com/Microsoft/vcpkg.git
$ cd vcpkg
$ ./bootstrap-vcpkg.sh
$ ./vcpkg install curl[ssh,tool]
```
results is:
```
Error: Building package curl:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: curl:x64-linux
  Vcpkg version: 2019.09.12-unknownhash
```
expected is: 
successful build of libcurl with tool and ssh support.

Transcript of the build in the attachment.

[curl-build-failure.txt](https://github.com/microsoft/vcpkg/files/3769199/curl-build-failure.txt)

**Comment by JackBoosY** [comment]
Seems cannot link to zlib.

**Comment by Voskrese** [comment]
@JackBoosY 

`vcpkg install curl[*]:x64-windows`

`CMake Error at ports/curl/portfile.cmake:48 (message):`
  **sectransp is not supported on non-Apple platforms**

`sectransp (!windows)` ?

**Comment by JackBoosY** [comment]
@Voskrese In CONTROL:
```
Feature: ssl
Build-Depends: curl[openssl] (!windows&!osx), curl[winssl] (windows), curl[sectransp] (osx)
Description: Default SSL backend
```

And 
```
Feature: sectransp
Description: SSL support (sectransp)
```

**Comment by JackBoosY** [comment]
Hi @phoyd, thanks for reporting this issue.
I've fixed it. Please update vcpkg and rebuild curl[ssh.tool].

Thanks.
