### ISSUE TITLE
vcpkg install errors

### ISSUE THREAD

**Issue by smasherprog** [Microsoft/vcpkg#874]
Steps to reproduce:
vcpkg install fltk:x86-windows-static

Error: Building package fltk:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fltk:x86-windows-static
  Vcpkg version: 0.0.78-a312cb493959055e13fc5376fff66d46c25c5c59

Attached are the error logs from the build

[config-x86-windows-static-rel-out.log.txt](https://github.com/Microsoft/vcpkg/files/880840/config-x86-windows-static-rel-out.log.txt)
[config-x86-windows-static-rel-err.log.txt](https://github.com/Microsoft/vcpkg/files/880841/config-x86-windows-static-rel-err.log.txt)

**Comment by ras0219-msft** [comment]
I believe this is fixed by 5414655, please let us know if the problem persists!
