### ISSUE TITLE
Can the build use perl?

### ISSUE THREAD

**Issue by winterz** [microsoft/vcpkg#8743]
I'm starting out with vcpkg.  trying to write a ports for libical, which I'd like to contribute.
I'm almost ready to submit a pull request.

but it dawns on me that the libical buildsystem requires perl.
how to handle the perl requirement?

**Comment by cbezault** [comment]
Call `vcpkg_find_acquire(PERL)` in the portfile.

**Comment by winterz** [comment]
thanks for the rapid response!
