### ISSUE TITLE
[New Port Request] Azure-Kinect-Sensor-SDK

### ISSUE THREAD

**Issue by jasjuang** [microsoft/vcpkg#8747]
Can we get Azure-Kinect-Sensor-SDK in vcpkg? This repo also belongs to Microsoft. Ping @UnaNancyOwen.

Library name: Azure-Kinect-Sensor-SDK

Library description: A cross platform (Linux and Windows) user mode SDK to read data from your Azure Kinect device. 

Source repository URL: https://github.com/microsoft/Azure-Kinect-Sensor-SDK

Project homepage: https://Azure.com/Kinect

**Comment by JackBoosY** [comment]
Hi @jasjuang, thanks for reporting this issue!
I've added it into vcpkg, please update vcpkg and try to build it.

Thanks.
