### ISSUE TITLE
Error: Building package plplot:x64-windows-static failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by MrBeee** [microsoft/vcpkg#8751]
Hi,

I'm trying to get started with plplot in conjunction with the wxwidgets library. I'd like to use static linkage. From the documentation I understand I should therefore use the following command:
> PS D:\Source\VS19\vcpkg> .\vcpkg.exe install plplot[wxwidgets]:x64-windows-static --recurse

I used the --recurse flag as the plplot library was first built without any wxwidgets dependency. This went flawlessly both for dynamic and static linkage.

Now I get the following error message:

> CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
>    Command failed: D:/Source/VS19/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: D:/Source/VS19/vcpkg/buildtrees/plplot/x64-windows-static-dbg
    See logs for more information:
      D:\Source\VS19\vcpkg\buildtrees\plplot\install-x64-windows-static-dbg-out.log

>Call Stack (most recent call first):
 > scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/plplot/portfile.cmake:48 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)

>Error: Building package plplot:x64-windows-static failed with: BUILD_FAILED

Not sure what I am doing wrong here..

**Comment by PhoebeHui** [comment]
@MrBeee, thanks for posting this issue, I have submitted a PR for fixing this issue.

**Comment by PhoebeHui** [comment]
@MrBeee , the PR has been merged, please get latest source and try again.
