### ISSUE TITLE
[boost-lexical-cast] Depends on boost.math?

### ISSUE THREAD

**Issue by myd7349** [microsoft/vcpkg#8753]
It seems that `boost-lexical-cast` depends on `boost-math`:
https://github.com/boostorg/lexical_cast/blob/87ce72192836787ff7bc8628abf0f0a68d56001d/include/boost/lexical_cast/detail/inf_nan.hpp#L34-L35
But `boost-math` is not in its `Build-Depends` list.

I tried to add `boost-math` to `boost-lexical-cast`'s `Build-Depends`:
https://github.com/microsoft/vcpkg/pull/8752/commits/d1ce9dc03b76e22f25c49811259bb72c88c18def (https://github.com/microsoft/vcpkg/pull/8752)
and the CI system reports an error:
https://dev.azure.com/vcpkg/public/_build/results?buildId=17136

**Comment by JackBoosY** [comment]
Hi @myd7349, does this issue still exist?

**Comment by traversaro** [comment]
> 
> 
> Hi @myd7349, does this issue still exist?

Hi @JackBoosY, I just experienced this same issue in https://github.com/microsoft/vcpkg/pull/13320#issuecomment-691482468, so I guess it is still present.

**Comment by traversaro** [comment]
More in particular, according to https://github.com/microsoft/vcpkg/pull/11131#issuecomment-622992539 there is a circular dependency between `boost-lexical-cast` and `boost-math`, and circular dependencies are not supported in vcpkg.
