### ISSUE TITLE
[New Port Request] <7zip-cpp>

### ISSUE THREAD

**Issue by how0723** [microsoft/vcpkg#8759]
Library name:7zip-cpp

Library description:Fork of SevenZip++ for modern builds.

Source repository URL:https://github.com/getnamo/7zip-cpp

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by NancyLi1013** [comment]
Hi @how0723  thanks for posting this request. 
This port needs to depend on many include files that from `7zip`. But these files are not been added to current `7zip`.
So we need to fix `7zip `first.

**Comment by how0723** [comment]
thank you



---Original---
