### ISSUE TITLE
Error: Building package cpprestsdk:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by zardozard** [Microsoft/vcpkg#876]
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: F:/Development/vcpkg-master/downloads/cmake-3.8.0-rc1-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;-

-;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No;/m
    Working Directory: F:/Development/vcpkg-master/buildtrees/cpprestsdk/x64-windows-dbg
    See logs for more information:
      F:\Development\vcpkg-master\buildtrees\cpprestsdk\package-x64-windows-dbg-out.log
[package-x64-windows-dbg-out.txt](https://github.com/Microsoft/vcpkg/files/881565/package-x64-windows-dbg-out.txt)
      F:\Development\vcpkg-master\buildtrees\cpprestsdk\package-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:35 (vcpkg_execute_required_process)
  ports/cpprestsdk/portfile.cmake:38 (vcpkg_install_cmake)
  scripts/ports.cmake:73 (include)

Error: Building package cpprestsdk:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cpprestsdk:x64-windows
  Vcpkg version: 0.0.78-

Additionally, attach any relevant sections from the log files above.
PS F:\Development\vcpkg-master> .\vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

**Comment by ras0219-msft** [comment]
I believe this is fixed by 5414655, please let us know if the problem persists!

**Comment by swtsvn** [comment]
Still getting error with x64 installation with latest:

The following packages will be built and installed:
    cpprestsdk[brotli,core,default-features,websockets]:x64-windows
Starting package 1/1: cpprestsdk:x64-windows
Building package cpprestsdk[brotli,core,default-features,websockets]:x64-windows...
-- Using cached B:/IGS/cozmo resources/cpprestsdk/vcpkg/downloads/Microsoft-cpprestsdk-v2.10.8.tar.gz
-- Using source at B:/IGS/cozmo resources/cpprestsdk/vcpkg/buildtrees/cpprestsdk/src/v2.10.8-9ddf85cf92
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: V:/Softwares/cmake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: B:/IGS/cozmo resources/cpprestsdk/vcpkg/buildtrees/cpprestsdk/x64-windows-dbg
    See logs for more information:
      B:\IGS\cozmo resources\cpprestsdk\vcpkg\buildtrees\cpprestsdk\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/cpprestsdk/portfile.cmake:43 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package cpprestsdk:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cpprestsdk:x64-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by me89** [comment]
Same here. It built nearly 100 dependencies. I tried vcpkg update which asks from git pull, which I made as well. but stops downloading for cpprestsdk

```
D:\share\libs\code\vcpkg>vcpkg install cpprestsdk cpprestsdk:x64-windows
The following packages will be built and installed:
  * boost-algorithm[core]:x64-windows
  * boost-asio[core]:x64-windows
  * boost-atomic[core]:x64-windows
  * boost-concept-check[core]:x64-windows
  * boost-container[core]:x64-windows
  * boost-context[core]:x64-windows
  * boost-conversion[core]:x64-windows
  * boost-coroutine[core]:x64-windows
  * boost-date-time[core]:x64-windows
  * boost-exception[core]:x64-windows
  * boost-function[core]:x64-windows
  * boost-function-types[core]:x64-windows
  * boost-functional[core]:x64-windows
  * boost-fusion[core]:x64-windows
  * boost-io[core]:x64-windows
  * boost-iterator[core]:x64-windows
  * boost-lambda[core]:x64-windows
  * boost-lexical-cast[core]:x64-windows
  * boost-math[core]:x64-windows
  * boost-numeric-conversion[core]:x64-windows
  * boost-optional[core]:x64-windows
  * boost-pool[core]:x64-windows
  * boost-range[core]:x64-windows
  * boost-regex[core]:x64-windows
  * boost-smart-ptr[core]:x64-windows
  * boost-thread[core]:x64-windows
  * boost-tokenizer[core]:x64-windows
  * boost-tuple[core]:x64-windows
  * boost-type-index[core]:x64-windows
  * boost-unordered[core]:x64-windows
  * brotli[core]:x64-windows
    cpprestsdk[brotli,core,default-features,websockets]:x86-windows
    cpprestsdk[brotli,core,default-features,websockets]:x64-windows
  * openssl[core]:x64-windows
  * openssl-windows[core]:x64-windows
  * websocketpp[core]:x64-windows
  * zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/37: cpprestsdk:x86-windows
Building package cpprestsdk[brotli,core,default-features,websockets]:x86-windows...
-- Using cached D:/share/libs/code/vcpkg/downloads/Microsoft-cpprestsdk-v2.10.8.tar.gz
-- Using source at D:/share/libs/code/vcpkg/buildtrees/cpprestsdk/src/v2.10.8-9ddf85cf92
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: D:/share/libs/code/vcpkg/buildtrees/cpprestsdk/x86-windows-dbg
    See logs for more information:
      D:\share\libs\code\vcpkg\buildtrees\cpprestsdk\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/cpprestsdk/portfile.cmake:43 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)
```
