### ISSUE TITLE
[New Port Request] new nanoGUI

### ISSUE THREAD

**Issue by xarthurx** [microsoft/vcpkg#8761]
Library name: nanoGUI (new)

Library description:
The nanoGUI has been re-written by the author with modern graphics support with new hosting repo.

The original repo is:
https://github.com/wjakob/nanogui

Source repository URL:
https://github.com/mitsuba-renderer/nanogui

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
We can also merge the new into the old port, but since the new one needs cpp17 support, it may fail people using the original `nanogui`.

**Comment by xarthurx** [comment]
Is this issue abandoned? @AlvinZhangH

**Comment by AlvinZhangH** [comment]
@xarthurx This issue is not abandoned, just that the processing priority has been reduced.

**Comment by NancyLi1013** [comment]
Since this port has been added, I'm closing this issue for now.

**Comment by Tanishq-Banyal** [comment]
> Since this port has been added, I'm closing this issue for now.

No, this port has not been Added.

As of May 2021, `vcpkg install nanogui` installs the old version of nanoGUI from this repo :-
https://github.com/wjakob/nanogui

But this version is deprecated and **NEW** nanoGUI is available from this repo :-
https://github.com/mitsuba-renderer/nanogui

Hence I request you to reopen this issue as the author asked for NEW nanoGUI, not old nanoGUI.

**Comment by NancyLi1013** [comment]
@Tanishq-Banyal Thanks for your attention to this port.

In this case, I think we should try to update `nanogui ` to the new repo instead of adding new one.

**Comment by Tanishq-Banyal** [comment]
> @Tanishq-Banyal Thanks for your attention to this port.
> 
> In this case, I think we should try to update `nanogui ` to the new repo instead of adding new one.

Yes exactly

**Comment by NancyLi1013** [comment]
It would be better to open a new issue for this.

**Comment by Tanishq-Banyal** [comment]
> It would be better to open a new issue for this.

There are already #11743 and #8761 for same thing, and both of them got closed without resolving.

**Comment by NancyLi1013** [comment]
There is another issue https://github.com/microsoft/vcpkg/issues/17052 for tracking `nanogui`.

For this issue, the original issue is to add this port to vcpkg. So I think it has been solved.

For #11743, we have declared that it was duplicated to #17052.

**Comment by Tanishq-Banyal** [comment]
> There is also a PR #17171 to fix these issues.

But it never got merged, author review pending....

**Comment by NancyLi1013** [comment]
If you are interested in this port, you can comment on the PR #17171. There are still some problems that need to investigate. So it is still in progress.
