### ISSUE TITLE
[Download Link Down] http://download.qt.io/official_releases/jom/jom_1_1_3.zip...

### ISSUE THREAD

**Issue by maulanarachmat** [microsoft/vcpkg#8762]
Hello,
I'm trying to 'vcpkg install gdal'
Here are some of the output:

> C:\vcpkg-master>vcpkg install gdal
> The following packages will be built and installed:
>   * curl[core,ssl,winssl]:x86-windows
>   * expat[core]:x86-windows
>     gdal[core]:x86-windows
>   * geos[core]:x86-windows
>   * hdf5[core]:x86-windows
>   * libiconv[core]:x86-windows
>   * liblzma[core]:x86-windows
>   * libpng[core]:x86-windows
>   * libpq[core]:x86-windows
>   * libwebp[core]:x86-windows
>   * libxml2[core]:x86-windows
>   * netcdf-c[core]:x86-windows
>   * opengl[core]:x86-windows
>   * openjpeg[core]:x86-windows
>   * openssl[core]:x86-windows
>   * openssl-windows[core]:x86-windows
>   * proj4[core,database]:x86-windows
>   * sqlite3[core,tool]:x86-windows
>   * szip[core]:x86-windows
>   * zlib[core]:x86-windows
> Additional packages (*) will be modified to complete this operation.
> ...

> Starting package 9/20: openssl-windows:x86-windows
> Building package openssl-windows[core]:x86-windows...
> -- Downloading http://strawberryperl.com/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip...
> -- Downloading https://www.openssl.org/source/openssl-1.0.2s.tar.gz...
> -- Extracting source C:/vcpkg-master/downloads/openssl-1.0.2s.tar.gz
> -- Applying patch ConfigureIncludeQuotesFix.patch
> -- Applying patch STRINGIFYPatch.patch
> -- Applying patch EnableWinARM32.patch
> -- Applying patch EmbedSymbolsInStaticLibsZ7.patch
> -- Applying patch EnableWinARM64.patch
> -- Using source at C:/vcpkg-master/buildtrees/openssl-windows/src/openssl-1-c41872ef97
> -- Downloading http://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win32/nasm-2.14.02-win32.zip...
> -- Downloading http://download.qt.io/official_releases/jom/jom_1_1_3.zip...

I stuck for a long time on the last line which '**'Downloading http://download.qt.io/official_releases/jom/jom_1_1_3.zip"**
When i tried to download manually on the respective link, I can't donwload it too.

Is there any otherway /link to get this package? or to successfully do 'vcpkg install gdal'
Thank You

**Comment by JackBoosY** [comment]
@maulanarachmat Thanks for reporting this issue.
Since I don't know which link you can visit, please download jom v1.1.3 manually and put it into _VCPKG_PATH/downloads_ and rebuild gdal.

**Comment by maulanarachmat** [comment]
I do try download it manually,but it still connection timeout. Here my manual download link:

> http://download.qt.io/official_releases/jom/ then choose jom_1_1_3.zip

**Comment by JackBoosY** [comment]
@maulanarachmat The path is in  _VCPKG_PATH\scripts\cmake\vcpkg_find_acquire_program.cmake_ line 128-130:
```
    set(URL "http://download.qt.io/official_releases/jom/jom_1_1_3.zip")
    set(ARCHIVE "jom_1_1_3.zip")
    set(HASH 5b158ead86be4eb3a6780928d9163f8562372f30bde051d8c281d81027b766119a6e9241166b91de0aa6146836cea77e5121290e62e31b7a959407840fc57b33)
```

**Comment by eos1d3** [comment]
It is being redirected to https://mirrors.tuna.tsinghua.edu.cn/qt/official_releases/jom/jom_1_1_3.zip

The original link gives 302 error.
