### ISSUE TITLE
[openssl] fails on windows with custom triplet

### ISSUE THREAD

**Issue by bjornpiltz** [microsoft/vcpkg#8772]
**Host Environment**
- OS: Windows
- Compiler: msvc2019

**To Reproduce**
`./vcpkg install openssl:<triplet>`

**Failure logs** 
```
Building package openssl-unix[core]:<triplet>...
CMake Error at ports/openssl-unix/portfile.cmake:4 (message):
  This port is only for openssl on Unix-like systems
Call Stack (most recent call first):
  scripts/ports.cmake:94 (include)


Error: Building package openssl-unix:<triplet> failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-unix:<triplet>
  Vcpkg version: 2019.09.12-nohash
```

**Additional context**
Apparently the custom triplet confuses the dependencies [here](https://github.com/microsoft/vcpkg/blob/47d206e149e88201333b5ca8fe55c30e2b1a8177/ports/openssl/CONTROL#L5) and vcpkg tries to install openssl-unix instead of openssl-windows.

**Comment by cbezault** [comment]
What is the name of your triplet. Until #8601 gets merged we just do a string compare against your triplet name in resolving dependencies.

**Comment by bjornpiltz** [comment]
Ok, I fixed it for now by prepending "windows-x64-" to the port name.
