### ISSUE TITLE
[Boost-Fiber] Include directory not present inside boost folder

### ISSUE THREAD

**Issue by FerzanVivec** [microsoft/vcpkg#8773]
I don't know if this is a bug but there is no directory called fiber inside boost folder. Boost fiber documentation begins with the following include:
#include <boost/fiber/all.hpp>

However, only fiber stuff I found is in context folder:
#include <boost/context/all.hpp>

Is this normal? I'm planning to release my source code on github, and I don't want people to experience build problems because of this.

I compiled boost with static-release flag.

**Environment**
- OS: Windows 10
- Compiler: Visual Studio Community 2019 / Version 16.3.6

**Comment by PhoebeHui** [comment]
@FerzanVivec, if you navigate to boost-fiber https://github.com/boostorg/fiber/tree/develop/include/boost/fiber, you can find that the headers under boost/fiber, so #include <boost/fiber/all.hpp> should be correct.  boost/context should be another boost component.

**Comment by PhoebeHui** [comment]
BTW, you install boost-fiber before use it.
