### ISSUE TITLE
[New Port Request] gnuradio

### ISSUE THREAD

**Issue by ferrellsl** [microsoft/vcpkg#8778]
Library name:gnuradio

Library description:GNU Radio is a free & open-source software development toolkit that provides signal processing blocks to implement software radios. It can be used with readily-available, low-cost external RF hardware to create software-defined radios, or without hardware in a simulation-like environment. It is widely used in hobbyist, academic, and commercial environments to support both wireless communications research and real-world radio systems.

Source repository URL:https://github.com/gnuradio/gnuradio

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JackBoosY** [comment]
This port's dependencies are not include in vcpkg now:
- alsa
- gmp
- gsm
- mplib
- oss
- portaudio
- sphinx
- swig
- uhd

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by dkozel** [comment]
@JackBoosY Most of the unpackaged dependencies are not required to build a workable GNU Radio installation. Infact, I'm not sure that any of those are. Swig has been replaced by Pybind11 in the next release of GNU Radio.
