### ISSUE TITLE
freeimage is missing "FreeImagePlus"

### ISSUE THREAD

**Issue by Mutantpenguin** [Microsoft/vcpkg#878]
It does exists in the "buildtrees", but neither in the "packages" nor "installed" folders.

**Comment by ras0219-msft** [comment]
Thanks for noticing this!

I've added a FreeImagePlus build in 96f30ca (package version 3.17.0-1). Please try it out and let us know if it works for you!

**Comment by Mutantpenguin** [comment]
Works great. Thank you very much!
