### ISSUE TITLE
Need MaterialX support in vcpkg

### ISSUE THREAD

**Issue by ZhongLingXiao** [microsoft/vcpkg#8780]
****

**I do not find materialx library in vcpkg**

The link list here:
https://github.com/materialx/MaterialX

thanks

**Comment by NancyLi1013** [comment]
Hi @ZhongLingXiao thanks for posting this request. I have committed a pull request. Does this meet your demand?
Any suggestion from you is needed here. Please help take a look.

Thanks.

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
