### ISSUE TITLE
[halide] Can't be found by CMake, OK with MSBuild

### ISSUE THREAD

**Issue by gc435** [microsoft/vcpkg#8782]
**Host Environment**
- OS: Windows 10 version 1903
- Compiler: VS 2019 16.3.6
- Halide version release_2019_08_27 on x64-windows

**To Reproduce**
1. Create new CMake project
2. Add `find_package(halide CONFIG REQUIRED)` to CMakeLists.txt

**Failure logs** 
```
/vcpkg.cmake:263 (_find_package):
  Could not find a package configuration file provided by "halide" with any
  of the following names:

    halideConfig.cmake
    halide-config.cmake

  Add the installation prefix of "halide" to CMAKE_PREFIX_PATH or set
  "halide_DIR" to a directory containing one of the above files.  If "halide"
  provides a separate development package or SDK, be sure it has been
  installed.	
```

**Additional context**
`vcpkg install halide` appears to have succeeded.  Halide is found by MSBuild projects.  It only fails to be found with CMake projects.

Did I miss an obvious step?  I admit I'm a CMake beginner.  However, I use other packages such as **Catch2** and **Boost** without problems.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed, so I am closing this issue for now.
