### ISSUE TITLE
how to integrate with VS2017?

### ISSUE THREAD

**Issue by yes89929** [microsoft/vcpkg#8783]
I installed PCL(Point Cloud Library) and integrated packages following below steps

1. modify "x64-windows.cmake"

   - set(VCPKG_VISUAL_STUDIO_PATH "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community")

   - set(VCPKG_PLATFORM_TOOLSET v141)

2. Excute comands in PowerShell

   - .\vcpkg install pcl[pcap]:x64-windows

   - .\vcpkg integrate install

I made a test project using VS2017, and build test [code](https://gist.github.com/UnaNancyOwen/9f9459d3c10f7a6325ebebabda9865f7#file-main-cpp).
But, VS2017 cannot find source

I checked "\AppData\Local\vcpkg". There are 3 files(config, vcpkg.path.txt, vcpkg.user.targets).
I heard if integration is succeed, 4 files are in this folder, not 3 files.

I also checked "C:\vcpkg\installed\x64-windows\lib". There is "boost_atomic-vc140-mt.lib".
In my think, this file must be vc141.

**Comment by Voskrese** [comment]
~~set(VCPKG_VISUAL_STUDIO_PATH "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community")~~

`set(VCPKG_VISUAL_STUDIO_PATH "C:\\Program Files (x86)\\Microsoft Visual Studio\\Preview\\Community")`

or 

`set(VCPKG_VISUAL_STUDIO_PATH "C:/Program Files (x86)/Microsoft Visual Studio/Preview/Community")`

**Comment by Voskrese** [comment]
log files error

**Comment by yes89929** [comment]
I'm very sorry. It's my mistake.
I didn't change solution platform from x86 to x64.
I was really an idiot.

And, thank you for your interest in my question.
