### ISSUE TITLE
[New Port Request] nanoflann

### ISSUE THREAD

**Issue by KohMat** [microsoft/vcpkg#8784]
Library name: nanoflann

Library description: a C++11 header-only library for Nearest Neighbor (NN) search with KD-trees

Source repository URL: https://github.com/jlblancoc/nanoflann.git

Project homepage (if different from the source repository): http://jlblancoc.github.io/nanoflann/

**Comment by AlvinZhangH** [comment]
Hi @KohMat thanks for posting this request.
These port have been added to vcpkg. Please update vcpkg and try to use them.
