### ISSUE TITLE
[opencv[cuda]] build failure

### ISSUE THREAD

**Issue by Gabe-L** [microsoft/vcpkg#8789]
**Host Environment**
- OS: Windows 10
- Compiler: unknown

**To Reproduce**
`./vcpkg install opencv[cuda] --recurse`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Installing opencv itself works fine, however when attempting to add it again with cuda I get the errors shown in the attached files

[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/3783518/config-x86-windows-out.log)

**Comment by Voskrese** [comment]
x86 not support

**Comment by Gabe-L** [comment]
@Voskrese Ah that makes sense, would I need to download a different version of cuda for this to work or just install through vcpkg a different way?

**Comment by Voskrese** [comment]
why do you need x86 in memory limit, use x64

**Comment by JackBoosY** [comment]
@Gabe-L Seems like cuda 10 dropped support with x86 platform, please install `opencv[cuda]:x64-windows`.

Thanks.
