### ISSUE TITLE
[New Port Request] lensfun

### ISSUE THREAD

**Issue by Yusheng9966** [microsoft/vcpkg#8801]
Library name: lensfun

Library description: a open source database of photographic lenses and their characteristics

Source repository URL: https://github.com/lensfun/lensfun

Project homepage (if different from the source repository): https://lensfun.github.io/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
